### ISSUE TITLE
ctrl + clicking foreign key link doesn't open new tab on MacOS Mojave 10.14.6 DBeaver version Version 7.2.2.202010041557

### ISSUE THREAD

**Issue by mwalkerr** [dbeaver/dbeaver#10003]
#### System information: 
- MacOS Mojave 10.14.6
- DBeaver version Version 7.2.2.202010041557

#### Connection specification:
- MySQL

#### Describe the problem you're observing:
I've added a virtual foreign key and when clicking the link on the foreign key column, the new table is shown in the same tab. The documentation says that ctrl+clicking the link will open the referenced table in a new tab, but I am unable to do this

#### Steps to reproduce, if exist:
1. Add virtual foreign key
2. ctrl+click the link

**Comment by akilovich** [comment]
`Ctrl + left click` is a system shortcut on macOS, so we changed it there to `command + left click`.

**Comment by kseniiaguzeeva** [comment]
verified
