### ISSUE TITLE
Query runtime reporting incorrectly

### ISSUE THREAD

**Issue by seabass9** [dbeaver/dbeaver#10009]
#### System information: 
- MacOS 10.15.4
- Version 7.2.2.202010041557

#### Connection specification:
- Vertica 9.1 JDBC

#### Describe the problem you're observing:
Duration shown on the bottom right doesn't seem correct. It does not coincide with the duration shown in the transaction log, which does seem correct.

**Comment by kseniiaguzeeva** [comment]
Which difference and SQL statement do you have? I have compared difference for table creating, and it is only 1 ms

**Comment by uslss** [comment]
there are no updates for a long time.
If the issue is still actual for you - feel free to reopen the ticket
