### ISSUE TITLE
Weird behavior with column named "call_only_ad_headline1"

### ISSUE THREAD

**Issue by DenyWatanabe** [dbeaver/dbeaver#10008]
This is an issue related to google bigquery, not sure if it also applies to other databases.

When performing a select against a table, if a column called "call_only_ad_headline1" is present in the select list, the query doesn't return any rows, instead the status resulting from an update (0 rows updated) is shown.

Just removing the column from the select list gets the behavior back to normal. Same happens if the column is called "call_only_ad_headline2", no other column names that I've tried trigger this weird issue.

For now the workaround is using backquotes around the column names, seems like debeaver is treating that name as a reserved word or something.

Of course the reason I'm thinking this is related to dbeaver is that when submitting the exact same query in the Google Cloud Platform BigQuery interface, it works as expected and returns rows even if the aforementioned columns are included in the select list.

**Comment by uslss** [comment]
Could you try to update driver? https://cloud.google.com/bigquery/providers/simba-drivers

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
