### ISSUE TITLE
Functions Not Loading In Postgres 

### ISSUE THREAD

**Issue by bhagatkhyati5** [dbeaver/dbeaver#10017]
![image](https://user-images.githubusercontent.com/72433097/95461462-e31b6d00-0993-11eb-8c06-b1d18592682c.png)
On loading functions in some database can't able to load for about 15 mins

**Comment by uslss** [comment]
Hi @bhagatkhyati5 ,
seems you've got a filter for Functions enabled. Try to clear it and check if the problem is solved.
![image](https://user-images.githubusercontent.com/31996417/95462105-bd846880-097f-11eb-90a3-9247a6fa27cd.png)
