### ISSUE TITLE
[Postgresql]- Showing Messages In Data Grid or Message Grid

### ISSUE THREAD

**Issue by emretuna01** [dbeaver/dbeaver#10012]
It would be great to see the messages in the data grid of dbeaver like pgadmin

here is the example screenshot to be understanding better

![image](https://user-images.githubusercontent.com/42046428/95435897-d844e600-095b-11eb-90f3-f3235fb91cf0.png)

**Comment by uslss** [comment]
Hi @emretuna01 ,
seems it is already implemented. Does it solve your problem?
![image](https://user-images.githubusercontent.com/31996417/95438010-6621d080-095e-11eb-91ec-3baa2774002d.png)

**Comment by emretuna01** [comment]
oh sorry i couldn't see it . it can solve my needs 
thanks
