### ISSUE TITLE
How To Pre-generate Specific DB configurations?

### ISSUE THREAD

**Issue by IgalTov** [dbeaver/dbeaver#10015]
- Operating system (distribution) and version: macOS (Mojave and above)
- DBeaver version: Community 7.2.1

- Database name and version: Snowflake

Hi,
I'm working to automate database connections for users, meaning that when a user opens his laptop - opens DBeaver - he'll see all the database connections ready on his Database Navigator list. This doesn't mean they'll work, as the user will need to receive username/password separately to access it.
I've noticed I can export Projects, but not DB navigator configuration. Is this something that can be done / how can this be done?

**Comment by p91paul** [comment]
This should be the file you're looking for:
~/Library/DBeaverData/workspace6/General/.dbeaver/data-sources.json

**Comment by IgalTov** [comment]
@p91paul Thank you! unfortunately, it seems there's only a "workspace2" folder, with /Scripts inside it and doesn't have the General folder as mentioned.
I tried looking for data-sources.json directly, but it was not found.

**Comment by IgalTov** [comment]
@p91paul Funny enough, it works with Jamf's MDM solution Composer when capturing it, but still not found in that directory. It seems to be coming from the ROOT folder.
Thanks again!
