### ISSUE TITLE
Limit minimum resulset fetch size

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#10010]
Setting fetch size to a very small value (e.g. 1) leads to a very weird behavior of resultset viewer. It fetches results multiple times + it may lead to scripts re-execution (if query consists of multiple SQL statements).

We need to set some minimum fetch size value.
E.g. 100.

**Comment by serge-rider** [comment]
Done

**Comment by uslss** [comment]
Resultset fetch size could be set less than 100 without any warning, but it is applied as 100.
![image](https://user-images.githubusercontent.com/31996417/95436861-04ad3200-095d-11eb-8c93-f2ef916e4991.png)

**Comment by serge-rider** [comment]
Preference page fixed

**Comment by uslss** [comment]
verified

**Comment by anurbol** [comment]
Hello, 

I appreciate your work, but shouldn't the original problem be fixed instead of fixing symptoms? 

I often deal with large tables and 100 rows is still too big for me.

**Comment by cyberbeat** [comment]
Yes, this is a bad solution. I often have a slow connection, and default fetching 100 rows with some blobs/longtexts takes forever. Fetch sizes of 1 or 10 also make sense in many cases. Please revert setting a minimum here!

**Comment by vonhutrong** [comment]
> Yes, this is a bad solution. I often have a slow connection, and default fetching 100 rows with some blobs/longtexts takes forever. Fetch sizes of 1 or 10 also make sense in many cases. Please revert setting a minimum here!

Yes, I also need to set it to 10 or 5 for faster first featching.

**Comment by stdkoehler** [comment]
> Yes, this is a bad solution. I often have a slow connection, and default fetching 100 rows with some blobs/longtexts takes forever. Fetch sizes of 1 or 10 also make sense in many cases. Please revert setting a minimum here!

+1 for my data it takes very long and often I also run out of java heap space.
Also, the current solution is not very transparent. It always reset to 100 without any information. I had to find this issue to understand that this is desired behaviour and not a bug or a "usage error".

**Comment by p91paul** [comment]
I believe commenting on old and closed issues is at risk of being ignored by the project owners, who look at open issues to see what to do. I suggest you open a new issue.

**Comment by vonhutrong** [comment]
Hi @cyberbeat and @stdkoehler,
I have created a new issue [here](https://github.com/dbeaver/dbeaver/issues/14486#issue-1043796497).
Thanks @p91paul for your advice.
