### ISSUE TITLE
Database Loading is very slow in Postgres.

### ISSUE THREAD

**Issue by bhagatkhyati5** [dbeaver/dbeaver#10013]
Functions and Table Loading is very very slow. Took about more than 30 mins to load, still hasn't load, as compared to PG admin, its gets load in 1-2 mins
![image](https://user-images.githubusercontent.com/72433097/95441080-52369880-0977-11eb-941c-35409949165d.png)

**Comment by kseniiaguzeeva** [comment]
- Do you use SSH,SSL etc?
- Could please tell what is written in Query Manager (Window>Show view>Query Manager)
- Which Postgres and DBeaver version do you use?
- What table sizes do you have?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
