### ISSUE TITLE
Fuzzy search in 'open database object' dialog

### ISSUE THREAD

**Issue by mwalkerr** [dbeaver/dbeaver#10021]
Same request as https://github.com/dbeaver/dbeaver/issues/435 but for the "open database object" search

**Comment by kseniiaguzeeva** [comment]
Could you please provide a bit more info? Steps to reproduce and actual result would be helpful.

**Comment by mwalkerr** [comment]
@kseniiaguzeeva updated the description with a link to the feature implemented somewhere else

**Comment by uslss** [comment]
for now, masks could be used in open database object search.
