### ISSUE TITLE
Close all unsaved tabs and application without saving button

### ISSUE THREAD

**Issue by muhammedOzbilici** [dbeaver/dbeaver#10027]
Version is 7.2.1.202009201907

When I try to close Dbeaver application and if there are unsaved multiple tabs, it shows this popup;

![Adsız](https://user-images.githubusercontent.com/7340804/95567585-cdf21d00-0a2b-11eb-84cc-e709d0b17653.png)

It would be better to have a button like "close all tabs and application without save"

**Comment by uslss** [comment]
thanks for suggestion

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/issues/5675 duplicate
