### ISSUE TITLE
Import table option dissapeared from table context menu

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10025]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.2.3 EA

#### Steps to reproduce, if exist:
Open table's context menu

Expected: option to import data exists
Actual result:
![dbeaver_60DWSt6YhU](https://user-images.githubusercontent.com/51405061/95554137-55359580-0a18-11eb-8cb4-c43387b8da32.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
