### ISSUE TITLE
Error resolving dependencies

### ISSUE THREAD

**Issue by TCorrege** [dbeaver/dbeaver#10026]
First Installation of DBeaver to use Postgre

#### System information: 
- W10 1903
- DBeaver version 7.2.2.202010041557
- Java version 8 update 101
- Additional extensions  : none

#### Describe the problem you're observing:
unabble  to access to https://dbeaver.io/files/jdbc
to get files 

- net.postgis-jdbc:RELEASE 
- net.postgis-geometry:RELEASE

#### Include any warning/errors/backtraces from the logs
Maven artifact 'maven:/net.postgis:postgis-jdbc:RELEASE' not found

**Comment by michalk-k** [comment]
Have the same on Kubuntu 20.
It worked previous week but today I found it not working at all. It stop working on its own (how is it possible?)
Any clues what happened and how to resolve/workaround it?

**Comment by michalk-k** [comment]
I resolved my issue by:
1. removing files from snap
2. restarting dbeaver
3. creating new postgresql database or importing project (all connections)

However once I import configuration (Import General/Preferences) the issue is back. I'm really not aware about changes I made to config which would affect libraries. I can provide the preferences file if it could help you debugging the problem.

PS. At this stage I'm not sure it's the same issue as OP has. but still looks similar.

**Comment by yonisade** [comment]
Do you use a proxy to access the internet?

**Comment by michalk-k** [comment]
No. I tried various connection types (inlc hotspot on my mobile). No changes.

HA.. I did another experiment.

1. I exported Preferences from working DBeaver  
2. I imported "broken" config which causes the issue. DBeaver asked for its restart, After that the issue appeared as expected
3. I imported config exported at beginning of this test case. After restart  DBeaver remains broken

**Comment by yonisade** [comment]
As a workaround, you can download the driver manually from here:
https://jdbc.postgresql.org/download.html
(use version 42.2.14 specifically, if you need SSH Tunnel working)

**Comment by michalk-k** [comment]
Probably nailed it down to the download path which points to snap directory. This path might change (in stored config I had snap/dbeaver-ce/79/... while currently such path doesn't exists any more. There is 81 instead of 79.

Maybe question is why imported "bad" preferences cannot be fixed by importing preferences exported second ago. But it needs more testing

**Comment by TCorrege** [comment]
Thank you for answers !
To solve  :

 DL postgresql-42.2.17.jar from https://jdbc.postgresql.org/download.html ( Yoni : 👍)) 
copy file to  C:\Users\%username%\AppData\Roaming\DBeaverData\drivers ( or some where else ...) (unlock if necessary)
Databases/ driverManager PostgreSQL /  Edit /  Add a file : select the copied file below

Enjoy...

**Comment by gex1x** [comment]
It's error about SSL cerificate of repository you use. I used repo1.maven.org and insalled their certificate. You must save cert file from repo and import it in java cacerts:
keytool -import -alias maven_repo -keystore (your jdk home path)\lib\security\cacerts -file maven_repo.cer
default password: changeit
And before use you system wide java, turn off Beaver local jdk, rename jdk folder to something another, e.g. jdk.bak

**Comment by abhishekdanej** [comment]
Initially my proxy was not set ..so it failed to download the driver. But then it said that the RELEASE file is not available from maven. I restarted dbeaver and it worked for me.

**Comment by thmsklngr** [comment]
Hi,

for those who may still struggle with downloading drivers - check your settings. I had the same problem and recognized, that the default location on Linux is set to /usr/share/dbeaver - a location, where normal users may not have access to. So, I solved my issue by setting the download location to /home/myuser/.dbeaver_drivers (or whatever you may choose). After that I reset all drivers to default and was able to download and update them. Worked like a charme.

Regards, Thomas

**Comment by leobasilio** [comment]
> Probably nailed it down to the download path which points to snap directory. This path is being stored in exported preferences but might change (in stored prefs I had snap/dbeaver-ce/79/... while currently such path doesn't exist any more. There is 81 instead of 79.
> 
> Maybe question is why imported "bad" preferences cannot be fixed by importing preferences exported second ago. But it needs more testing
> 
> Ah... and changing the path doesn't help immediately. Restart of DBeaver is needed. After that DBeaver asks for downloading something but this time it works.

I just had the same problem and this helped me. A snap update was applied while I was using the dbeaver and the drivers location folder was not updated to the new location. I had to manually fix it at the preferences dialog.

**Comment by pud3ll** [comment]
It got it solved by Downloading from https://jdbc.postgresql.org/download.html
![image](https://user-images.githubusercontent.com/65213098/122721207-0fa0bc00-d279-11eb-8fb5-733915a6c48f.png)
and then went to driver settings, deleted everything else and add the file I downloaded ( the folder location didn't seem to matter
![image](https://user-images.githubusercontent.com/65213098/122721802-c0a75680-d279-11eb-933a-e8e59f48be06.png)

**Comment by pud3ll** [comment]
It got it solved by Downloading from https://jdbc.postgresql.org/download.html
![image](https://user-images.githubusercontent.com/65213098/122723768-006f3d80-d27c-11eb-9563-fcb7b77d7020.png)
and then went to driver settings, deleted everything else and add the file I downloaded ( the folder location didn't seem to matter
![![image](https://user-images.githubusercontent.com/65213098/122723768-006f3d80-d27c-11eb-9563-fcb7b77d7020.png)](https://user-images.githubusercontent.com/65213098/122723703-ee8d9a80-d27b-11eb-8d18-7f40af09adff.png)

**Comment by patrick-cardoso** [comment]
> > Probably nailed it down to the download path which points to snap directory. This path is being stored in exported preferences but might change (in stored prefs I had snap/dbeaver-ce/79/... while currently such path doesn't exist any more. There is 81 instead of 79.
> > Maybe question is why imported "bad" preferences cannot be fixed by importing preferences exported second ago. But it needs more testing
> > Ah... and changing the path doesn't help immediately. Restart of DBeaver is needed. After that DBeaver asks for downloading something but this time it works.
> 
> I just had the same problem and this helped me. A snap update was applied while I was using the dbeaver and the drivers location folder was not updated to the new location. I had to manually fix it at the preferences dialog.

Great! This is the best way!
I am adjusted the path, restart dbeaver, and all works.
Thank you so much @leobasilio and @michalk-k 
![image](https://user-images.githubusercontent.com/19351082/123103326-4529de80-d40c-11eb-9dee-3e7e80e25b65.png)

**Comment by Dekai** [comment]
For me, fixed this issue by importing maven website cert into dbeaver jre cacerts which is under folder Application/DBeaver/Contents/eclipse/jre/Contents/Home/lib/security, this is Mac path, Windows could be different

**Comment by JulianDietzel** [comment]
> Probably nailed it down to the download path which points to snap directory. This path is being stored in exported preferences but might change (in stored prefs I had snap/dbeaver-ce/79/... while currently such path doesn't exist any more. There is 81 instead of 79.
> 
> Maybe question is why imported "bad" preferences cannot be fixed by importing preferences exported second ago. But it needs more testing
> 
> Ah... and changing the path doesn't help immediately. Restart of DBeaver is needed. After that DBeaver asks for downloading something but this time it works.

This fixed it for me. For everyone as inexperienced with DBeaver as me:
 The dialogue to change this can be found under `Window > Preferences > Connections > Drivers`, then change the path under the section `Drivers location`, labeled `Local folder` to the one with the path with newest version. (In my case the path that worked was `/home/<user>/snap/dbeaver/current/.local/share/DBeaverData/drivers`, with the change being that `current` previously was a number)
Then as mentioned in the original post, restart DBeaver and it should work.
