### ISSUE TITLE
How to add all columns into the Transaction log for querying, not 'select *'

### ISSUE THREAD

**Issue by nlpsuge** [dbeaver/dbeaver#10028]
#### System information: 
- Operating system (distribution) and version
Fedora 32

- DBeaver version
7.2.2

#### Connection specification:
- Database name and version
MySQL 8

#### Describe your question:
Is there any way to add all columns into the Transaction log for querying, not just 'select * from a_table'.

I see that updating and inserting sqls has columns.

I like to copy SQLs in Transaction log so that it can save me some time to write sqls by hand.

**Comment by uslss** [comment]
It isn't possible. The transaction log shows a query that was executed.
If you need to see columns, you could use autosuggestion in SQL editor. If you place the cursor after "*" symbol in query and press Ctrl+Space - * will be replaced by columns name.

**Comment by nlpsuge** [comment]
@uslss 
Thank you. This is quite useful. It will improve my workflow.
