### ISSUE TITLE
MySQL: Moving Object Up and Down

### ISSUE THREAD

**Issue by iambudi** [dbeaver/dbeaver#10039]
#### System information: 
- Mac OS Cataline 10.15.7
- DBeaver Version 7.2.2.202010041557

#
### Connection specification:
- MySQL 8 with MySQL Java Connector 8.0.21

#### Describe your question:
Moving up and down field object in table view (columns) does not immediately reflect the reorder change, unless it's saved first and refresh. It's a tedious work when there are a lot of objects to reorder.

![image](https://user-images.githubusercontent.com/31809529/95639458-b7e36b80-0ac2-11eb-8d6d-bb4aa80815bd.png)

I can't remember if DBeaver could do this before. Any configuration to allow this?

**Comment by uslss** [comment]
seems it is bug.
thanks for the report :)

**Comment by serge-rider** [comment]
Fixed

**Comment by iambudi** [comment]
In MacOS Big Sur the bug raises again. I tried from version 7.23 to 7.30.

**Comment by iambudi** [comment]
Should i open a new issue or we can reopen this? Thanks.
