### ISSUE TITLE
Data type auto-assigning when importing from CSV to an existed table

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10034]
Please add data type auto-assigning when importing from CSV to an existed table. Table rows data types will be used by default.

**Additional context**
The ticket is based on https://github.com/dbeaver/dbeaver/issues/9756

**Comment by kseniiaguzeeva** [comment]
Not all column types are indicated correctly in Column mapping.
SQLite
![dbeaver_GyaNgMMLPI](https://user-images.githubusercontent.com/51405061/98796033-fb136000-241b-11eb-83be-a1c34649ef2b.png)
MySQL
![dbeaver_doTxNOP6V8](https://user-images.githubusercontent.com/51405061/98796049-ffd81400-241b-11eb-9213-ba55a3051d10.png)

But the import works correctly inspite of it, when the exact column for import is marked

**Comment by uslss** [comment]
verified
