### ISSUE TITLE
When procedure text is larger than varchar(max), text is truncated when trying to view the source of the proc

### ISSUE THREAD

**Issue by JasonLesser54321** [dbeaver/dbeaver#10045]
Very long procedures (longer than varchar(max)) are truncated when you try to view the source of the procedure. 

DBever is probably using varchar(max) when it should be using the TEXT data type to retrieve the procedure text.
![image](https://user-images.githubusercontent.com/72715161/95694291-0c324b00-0c7d-11eb-9e8a-e1f078d4b689.png)
The only way I have been able to get around this is running the following script: 

-- Replace proc name to get proc text
DECLARE @i NUMERIC(14,0), @X NUMERIC(14,0), @Z TEXT
SET @i = 0
SET @X = (select COUNT(*) from syscomments where object_name(id) = 'proc_name_here')
WHILE @i <= @X 
BEGIN
  SET @Z = @Z + (select [text] from syscomments where object_name(id) = 'proc_name_here' AND colid = @i )
  SET @i = @i + 1 
END 
SELECT @Z

**Comment by uslss** [comment]
Hi @JasonLesser54321 ,
what database do you use? Could you provide a procedure example?
Thanks in advance

**Comment by JasonLesser54321** [comment]
Database: Sybase 
[proc.txt](https://github.com/dbeaver/dbeaver/files/5374567/proc.txt)

**Comment by LonwoLonwo** [comment]
Hello @JasonLesser54321 
Yes, we are reading procedure definition from table syscomments and text column, which have varchar(255) type. But we are reading each row and gluing all lines in one definition.

So, first - is this problem actual for you in [new DBeaver versions](https://dbeaver.io/)?
Second - clarify you database parameters, please.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
