### ISSUE TITLE
Table's Properties/DDL screens displays all postgres triggers as being After Insert

### ISSUE THREAD

**Issue by GeorgeAGeorgopoulos** [dbeaver/dbeaver#10041]
#### System information: 
- Operating system: Windows 10
- DBeaver version: 7.2.2.202010041557
- Additional extensions

#### Connection specification:
- Database Postgres: 9.5 or  9.6
- Driver name: org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
In the database navigator/Properties/DDL screen all triggers are displayed as 'After insert' regardless of their actual timing and manipulation settings.
The database navigator/Properties/Triggers listing displays the correct values for timing and manipulation.

#### Steps to reproduce, if exist:
Upgrade from version Version 7.2.1.202009201907 to Version 7.2.2.202010041557
In the db navigator, navigate to a table that has a trigger that you know i

s not just 'After insert'.
Observe the DDL code of the trigger in the table's Properties/DDL screen, under the CREATE TABLE... code.  The trigger creation DDL code displays as 'AFTER INSERT'.  
If you navigate to the table's Properties/Triggers screen where all the triggers of the table are listed, the columns titled 'Timing' and 'Manipulation' display the correct values for the trigger.

#### Include any warning/errors/backtraces from the logs

![dbnavigator_properties_triggers_screenshot](https://user-images.githubusercontent.com/14107386/95655164-0702be00-0b0e-11eb-952c-be821c4483d3.jpg)
![dbnavigator_properties_ddl_screenshot](https://user-images.githubusercontent.com/14107386/95655166-08cc8180-0b0e-11eb-9d02-6cd0a01e6c51.jpg)

**Comment by MorozovaMariya** [comment]
Version 7.2.2 - Same Error (

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
verified
