### ISSUE TITLE
Db2 "Generate SQL"/CALL for user defined functions generates wrong syntax

### ISSUE THREAD

**Issue by gerhard81** [dbeaver/dbeaver#10059]
Hi,

Generate SQL Call for Db2 (LUW) user defined functions generates wrong syntax.
Syntax generated for i.e. SYSPROC.ADMIN_GET_INTRA_PARALLEL
`SELECT  "SYSPROC".ADMIN_GET_MEM_USAGE(:null)
`

_org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42601]: An unexpected token "END-OF-STATEMENT" was found following "ADMIN_GET_MEM_USAGE()".  Expected tokens may include:  "<table_expr>".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.26.14_

The correct syntax must be
`SELECT * FROM TABLE ( "SYSPROC".ADMIN_GET_MEM_USAGE(:null))`

Regards,
Gerhard

**Comment by uslss** [comment]
Thanks for the bug report

**Comment by LonwoLonwo** [comment]
@gerhard81 

`SELECT * FROM TABLE ( "SYSPROC".ADMIN_GET_MEM_USAGE(:null))` does not work for me

but `SELECT SCHEMA_NAME.FUNCTION_NAME(:PARAM1) FROM SYSIBM.SYSDUMMY1` is much better. 

This call function method is mentioned in the documentation on z/os https://www.ibm.com/docs/en/db2-for-zos/11?topic=objects-creation-user-defined-functions but works for LUW to.

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.0.4

![115261817-a0093600-a13c-11eb-9c7d-422962fc4639](https://user-images.githubusercontent.com/45152336/115666816-b508e380-a34d-11eb-9abf-bcaf39ffb902.png)

**Comment by uslss** [comment]
verified

**Comment by gerhard81** [comment]
@LonwoLonwo

Your implementation is correct for scalar functions.
But it is not correct when the function is a table function which returns a table as resultset.
In this case the function has to be called in the following way:

`SELECT * FROM TABLE ( "SYSPROC".ADMIN_GET_MEM_USAGE(:null))`

The documentation link you mentioned is for Db2 z/OS but when you call a table function in Db2 (LUW = Linux, Unix, and Windows) the function call is different .

https://www.ibm.com/support/producthub/db2/docs/content/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.routines.doc/doc/t0009218.html

It depends what type of function has to be executed.
- scalar function -> you are right
- table function returning a table as resulset -> you're call is wrong and result in a
![image](https://user-images.githubusercontent.com/69924414/115753739-d0024480-a39b-11eb-907e-b1b1ac215f26.png)

The correct syntax is as I mentioned in the very first message.
![image](https://user-images.githubusercontent.com/69924414/115753866-f0320380-a39b-11eb-8dc3-9b67e4a880c2.png)

**Comment by LonwoLonwo** [comment]
Ok. Now we have different CALL statements for table and scalar functions.
Fixed.

**Comment by LonwoLonwo** [comment]
Also functions icon fixed.

![2021-04-23 22_33_55-DBeaver Enterprise 21 0 3 - _none_ Script-9](https://user-images.githubusercontent.com/45152336/115930651-88121900-a492-11eb-9736-58c7a1517bf5.png)

**Comment by uslss** [comment]
verified
