### ISSUE TITLE
SQL Editor auto-completion enhancement.

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#10069]
For now, we make proposals based on the list of objects contained in the parent, or send a request to the appropriate database with the name of the object pattern. 

Sometimes in the second case, the name of the schema/ directory/database also gets into the object name template. We need to find such cases and cut the search pattern.

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/issues/4957 can be used for tests

**Comment by LonwoLonwo** [comment]
Basically, the changes concerned cases when full names were used in the SQLEditor to search for procedures, tables, packages. now in the case of using the full name and part of the name of the procedure/table and other things - the auto-complete should work better (for procedures most often with ctrl + space)

![2020-12-15 09_29_06-](https://user-images.githubusercontent.com/45152336/102192289-a3a95980-3ecb-11eb-8266-fb3a028de463.png)
![2020-12-15 09_30_00-DBeaver Enterprise 7 3 0 - _dvdrental 12_ Script-50](https://user-images.githubusercontent.com/45152336/102192291-a441f000-3ecb-11eb-9b48-eb16354cd164.png)

**Comment by uslss** [comment]
verified
