### ISSUE TITLE
Ctrl+\ doesn't open a new tab with resultest if it is executed after Ctrl+Enter

### ISSUE THREAD

**Issue by PaulSlater25** [dbeaver/dbeaver#10067]
#### System information: 
- Windows 10 Build 19041
- DBeaver version 7.2.2

#### Connection specification:
- SQLite

#### Describe your question:
In version 7.2.2 once I've used Ctrl+\ to get results in a new tab all subsequent queries open a new tab. If I go to an existing tab and query with Ctrl+Enter, a new tab is created where it used to replace the selected results tab. Is this expected behaviour? DBeaver might have done this in earlier versions but I can't remember that it did. 
Thanks, Paul

**Comment by uslss** [comment]
Hi @PaulSlater25 ,
unfortunately, cannot reproduce an issue. Could you provide a video?
Also, you can try to Reset workspace (File - Reset workspace state) and Reset UI Settings (File - Reset UI Seettings)

**Comment by PaulSlater25** [comment]
I tried both resets and unfortunately that didn't help. I did a video and as it doesn't 'see' keystrokes I used the dropdown menu to execute the SQL. Sadly the dropdown isn't seen in the video so it doesn't prove or demonstrate the problem. To show this I had two select statements. Using CTRL+Enter (keyboard or menu) on either puts the results into one tab. Using Ctrl+\ on one then opens a second tab. From then on, Ctrl+Enter always opens a new tab, regardless of which result tab is selected. It's almost as if Ctrl+\ is now a switch that says 'always open a new results tab'.

BTW, sorry about the big title. I put the comment in there before I realised how the forum works. I thought I'd edited it, but obviously didn't.

**Comment by uslss** [comment]
thanks for the clarification :)

**Comment by mahonetim** [comment]
Also experiencing this same issue on Snowflake

**Comment by kseniiaguzeeva** [comment]
verified
