### ISSUE TITLE
Grants on Postgres sequence fail from certain menu.

### ISSUE THREAD

**Issue by ludo-21south** [dbeaver/dbeaver#10068]
#### System information: 
- Ubuntu 18.04 LTS
- Dbeaver 7.2.2.202010041557 (but I had this since version 6.3.3)

#### Connection specification:
- PostgreSQL 11.5
- default driver (version 2.5.0)
- SSH tunnel in use 

#### Describe the problem you're observing:
When trying to alter or grant rights specifically on sequences from within a user (on the permissions tab) I get no error but the changes are not stored either (you can see the client refresh and revert). When I do the exact same thing from the perspective of the sequence itself, it works like a charm. When running the command in a query editor, the changes are also **not** applied. Refreshing and/or disconnecting and connecting made no difference.

#### Steps to reproduce, if exist:
Go to any random user/role in your database, go to permissions. Select a sequence and click "Grant all". Then click "Save" in the bottom right corner. You should see the changes revert.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by LonwoLonwo** [comment]
Permissions work for schemas/tables/views and functions,
but for Sequences and Materialized views information is not saved

also not correct statement for GRANT EXECUTE. Always "ON FUNCTION" instead "ON PROCEDURE" for procedures.

**Comment by LonwoLonwo** [comment]
Fixed in 7.3.0

Incorrect statement for procedures will be fixed here https://github.com/dbeaver/dbeaver/issues/10501

**Comment by kseniiaguzeeva** [comment]
verified
