### ISSUE TITLE
Color code by database

### ISSUE THREAD

**Issue by izzy-bitbean** [dbeaver/dbeaver#10076]
Is it possible to add color coding to databases within the same connection as I have staging and production databases on the same server and would like to be able to differentiate between them visually the same way we can visually differentiate between different connections?

I so far made 2 connections to the same server and hid one in each and defined one connection as production and the other as staging, but wondering if it can be done in the same connection for each db.

**Comment by p91paul** [comment]
as a suggestion, you could create 2 connections to the same server, and use filters to only show the development database on one connection and only production on the other.

**Comment by izzy-bitbean** [comment]
Yes that's basically what I did. Thank you
