### ISSUE TITLE
An error appears in Error log if EE database exist in DB Navigator

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10085]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.2.3
- Additional extensions

Precondition: 
EE and CE DBeavers are installed for 1 user
#### Steps to reproduce, if exist:
1. Create  a connection for EE database in DBeaver EE
2. Close DBeaver EE
3. Open DBeaver CE
4. Open an object in DB Navigator tree
[log.txt](https://github.com/dbeaver/dbeaver/files/5391385/log.txt)

**Comment by serge-rider** [comment]
Fixed (proper handle of missing providers)

**Comment by kseniiaguzeeva** [comment]
verified
