### ISSUE TITLE
A trigger difined as "FOR EACH STATEMENT" is shown as "FOR EACH ROW"

### ISSUE THREAD

**Issue by marcgise** [dbeaver/dbeaver#10084]
#9835 ## System information: 
- Operating system (distribution) and version: Ubuntu 20.10
- DBeaver version: 7.2.2

#### Connection specification:
- Database name and version: PostgreSql 12.2
- Driver name: PostgreSql 42.2.18
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
A trigger defined as FOR EACH STATEMENT is displayed in the definition as FOR EACH ROW

#### Steps to reproduce, if exist:
![image](https://user-images.githubusercontent.com/4680243/96251863-5edb7200-0fb1-11eb-8177-dcc3b09b4780.png)

If you execute the following script, it shows the correct SQL:
select pg_get_triggerdef(oid)
from pg_trigger
where tgname = '__XXX_trigger_on_insert_position';

CREATE TRIGGER __XXX_trigger_on_insert_position AFTER INSERT ON "XXXXXXX".posicion REFERENCING NEW TABLE AS new_positions **FOR EACH STATEMENT** EXECUTE FUNCTION __XXX_on_insert_position()

**Comment by ShadelessFox** [comment]
Should be fixed in 7.2.3.
