### ISSUE TITLE
child tables are not found with dbeaver 7.2.2

### ISSUE THREAD

**Issue by manhug** [dbeaver/dbeaver#10081]
#### Connection specification:
- Database name and version : greenplum 6.5
- Driver name : postgresql.42.2.18

the child tables are not found with dbeaver 7.2.2 .
but, the child tables are found properly with dbeaver 7.0.1

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed. Both partitions and child tables now must load correctly.

**Comment by kseniiaguzeeva** [comment]
verified
