### ISSUE TITLE
SQL Error [42501]: ERROR: permission denied

### ISSUE THREAD

**Issue by kerrmcintosh** [dbeaver/dbeaver#10080]
#### System information: 
- Operating system (distribution) and version macOS High Sierra 10.13.6
- DBeaver version 7.2.2

#### Connection specification:
- Database name and version

#### Describe your question:

Probably basic stuff. I'm just trying out DBeaver for the first time to set up a Postgresql database.

I chose new database connection - Postgres
Host: localhost, Database: postgres,  Username: postgres and system password ... All connected
but when I right click create new database or schema I get the error

"SQL Error [42501]: ERROR: permission denied to create database ERROR: permission denied to create database"

Also, no databases I've created on localhost with pgadmin / psql are showing

Nothing in error log.

Where could I be doing wrong?

**Comment by uslss** [comment]
Hi @kerrmcintosh ,
could you provide a log?
Also, you should check Show All Databases option in properties to see all databases.
![image](https://user-images.githubusercontent.com/31996417/96458680-dd424900-1229-11eb-8bd8-de7123fc5eb6.png)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
