### ISSUE TITLE
No results returned with filter in table "Data" view on macOS Mojave 10.14.6, DBeaver Version 7.2.2.202010041557

### ISSUE THREAD

**Issue by mwalkerr** [dbeaver/dbeaver#10089]
#### System information: 
- macOS Mojave 10.14.6 
- Version 7.2.2.202010041557
- SSHJ extension

#### Connection specification:
- MySQL [5.7.12-log]
- MySQL Connector Java [mysql-connector-java-5.1.44 ( Revision: b3cda4f864902ffdde495b9df93937c3e20009be )]
- SSH tunnel with SSHJ

#### Describe the problem you're observing:
I entered a filter in the filter box of the table Data view (to the right of the box with the table name in green) but 0 rows were returned. There were results for the filter, however, which I was able to see by (1) clicking the green table name to show the query with the filter (2) opening a new script and (3) pasting the query into the script and running it. Also went to the transaction log and copied the latest query run (from the Data view), ran it, and saw the expected results. This is the same query as before except with the "limit" included. I used "Invalidate/Reconnect" on the connection and now I'm seeing the expected results. I cleared the filter on the Data view and refreshed the results to see that I was still able to fetch rows from the table. I added the filter back and again got 0 results again.

#### Include any warning/errors/backtraces from the logs
I see the following logs:
```SQL Error [08S01]: The last packet successfully received from the server was 152,316,767 milliseconds ago.  The last packet sent successfully to the server was 152,317,159 milliseconds ago. is longer than the server configured value of 'interactive_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.```
If the connection was broken, though, I would have expected to not be able to fetch any results when the filter was removed and to not have been able to fetch the correct results when running from the script.

**Comment by mwalkerr** [comment]
My concern with this is that there was no way to tell if the row I was searching for actually didn't exist or if there was an issue with the connection. There was no warning/error from DBeaver and results were fetched without the filter so it definitely looked as if there were just no results for the filter. Having to manually verify a filter by running it in a separate script would significantly detract from the utility of the data view filter

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
Hello @mwalkerr 

Is this issue still reproducible in the latest DBeaver version? https://dbeaver.io/download/
We added many enhancements for the data viewer and filters.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
