### ISSUE TITLE
Fetch size can be set only 100 in Data Editor properties

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10083]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.2.3 EA

#### Steps to reproduce, if exist:
1. Open a table in Data Editor
2. Press Settings button in bottom toolbar
3. Set fetchsize more then 100 in the properties
4. Press Apply

Expected: the entered number is displayed
Actual result: the fetch size changes to 100

Workaround: set the fetchsize in the bottom toolbar of Data Editor
![ElfO5TsAMr](https://user-images.githubusercontent.com/51405061/96246463-57b46400-0fb1-11eb-8d28-34a72d292989.gif)

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by AdrianoBortoloto** [comment]
How can I set unlimited fetch (zero value)? Every time I try to change to zero it backs to 100... I checked 'Use SQL to limit fetch size' but it doesn't take effect, the fetch size remains 100 even if I limit the query with a larger number (limit 200 for example).

**Comment by cyberbeat** [comment]
This seems not to be fixed? I am using eclipse plugin with this version:

DBeaver IDE	21.0.2.202104042040	org.jkiss.dbeaver.ide.feature.feature.group	JKISS

I am unable to enter another value than 100. After leaving the textfield it always resets back to 100.
