### ISSUE TITLE
Dbeaver CE Ubuntu snap can't read SSH key in ~/.ssh

### ISSUE THREAD

**Issue by kaincenteno** [dbeaver/dbeaver#10098]
#### System information: 
- Operating system (distribution) and version
Ubuntu 20.04
- DBeaver version
7.2.2.202010041557
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
SSH

#### Describe the problem you're observing:
When trying to create a connecting, if you try using a private key that lives in ~/.ssh it won't allow you to

**Comment by uslss** [comment]
thanks for the bug report

**Comment by benzkji** [comment]
this is probably because of the security restrictions that are enforced, when using snap? agent does not work either, here.

**Comment by AlainBenbassat** [comment]
The solution is to give DBeaver permission to access the ssh folder.

- Open the "Ubuntu Software" app
- click on the tab "Installed"
- click on "dbeaver-ce"

![db1](https://user-images.githubusercontent.com/16761652/106354306-2c038280-62f1-11eb-996f-459ed946a206.png)

- then click on the "Permissions button"

![db2](https://user-images.githubusercontent.com/16761652/106354330-5a815d80-62f1-11eb-9208-c7feb9e29e32.png)

- enable "ssh-keys: allows reading ssh user configuration and keys"

![db3](https://user-images.githubusercontent.com/16761652/106354379-b946d700-62f1-11eb-92ee-849f6f556ef5.png)

**Comment by ndlarsen** [comment]
Consider editing the snap so it's installable with the `--classic` argument. This also enables retaining configurations then uninstalling the snap.

**Comment by riednyko** [comment]
For reading private keys in ~/.ssh you need to manually connect the plugin 
`sudo snap connect dbeaver-ce:ssh-keys` for access to private keys
and
`sudo snap connect dbeaver-ce:ssh-public-keys` for access to public keys.

Or you can use the solution written above by @AlainBenbassat
