### ISSUE TITLE
Improve table filtering in Database Navigator

### ISSUE THREAD

**Issue by ljubadr** [dbeaver/dbeaver#10091]
**Is your feature request related to a problem? Please describe.**
When filtering tables in **Database Navigator** by using the input `Enter a part of table name here`, it's not possible to filter multiple tables at the same time. I know I can use the "configure Tables filters" but this is not useful when I need to change filter often

**Describe the solution you'd like**
Is it possible make this filter accept regex? Or at least accept `|` as `OR`?

**Describe alternatives you've considered**
I found that by double clicking **Tables** and then pressing `ctrl+f` this new search behaves the way that I would like the **Database Navigator** filter to behave

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by uslss** [comment]
already implemented
