### ISSUE TITLE
CSV import with creating table

### ISSUE THREAD

**Issue by hanct** [dbeaver/dbeaver#10094]
Hi all,
I am re-opening this issue which someone has raised out in year 2017. See [here(https://github.com/dbeaver/dbeaver/issues/2415).
Note that this is not a duplicate of [#130](https://github.com/dbeaver/dbeaver/issues/130)

This is to suggest a feature, where dbeaver can import a CSV file, and able to create a new table from it, and automatically import the data in the CSV file into the new table.  It would really be a awesome feature to have.

**Comment by uslss** [comment]
Hi @hanct ,
this feature is already implemented.
You could choose Import data in context menu e.g. for Table folder (not for a table) and then import CSV to a new table.
![image](https://user-images.githubusercontent.com/31996417/96423028-76a93500-1201-11eb-848a-d16865683b8b.png)

**Comment by hanct** [comment]
Hi, thanks. Maybe know which version implement this? Mine has all the menu items (except import data) based on your screenshot when I right click. I am using dbeaver 6.1.4

**Comment by uslss** [comment]
it is implemented in 7.2.x version. You could try the recent version - 7.2.3
