### ISSUE TITLE
[SQL Server] View cannot be opened

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10096]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.2.3 EA

#### Connection specification:
- Database name and version SQL Server

#### Steps to reproduce, if exist:
Open a view if exists (or create a new one and open in Data Editor)

Expected: the correct table is displayed
Actual result: Error appears in Data Editor: "Error executing query"
![dbeaver_ufCwYyQIU1](https://user-images.githubusercontent.com/51405061/96353103-bbce4980-10d1-11eb-9dac-a7531ee2a2ee.png)
#### Include any warning/errors/backtraces from the logs
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/5396514/dbeaver-debug.log)
[.log](https://github.com/dbeaver/dbeaver/files/5396513/default.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
