### ISSUE TITLE
MSSQL + DBeaver creating indexes...

### ISSUE THREAD

**Issue by ravenlost** [dbeaver/dbeaver#10099]
Hello, 

How can I create a non-clustered index ? When I right click on the Indexes folder from a table, select **Create New Index**, I cannot change the Type. It's grayed out on "Other". 

Also, it would be nice if we could give a custom name to our indexes right from that screen.

P.S. running DBeaver 7.2.3 on Linux.

Thanks!!
Pat

**Comment by uslss** [comment]
seems it is not implemented.
Your issue is marked as a feature request.
Thanks for suggestion

**Comment by ravenlost** [comment]
> seems it is not implemented.
> Your issue is marked as a feature request.
> Thanks for suggestion

Thank you.

**Comment by LonwoLonwo** [comment]
I added two general types to choose from - non-clustered and clustered. And left the default (that is, in fact, non-clustered)

**Comment by ravenlost** [comment]
> I added two general types to choose from - non-clustered and clustered. And left the default (that is, in fact, non-clustered)

Awesome! Thank you :+1:

**Comment by uslss** [comment]
verified
