### ISSUE TITLE
Sample Database

### ISSUE THREAD

**Issue by Goldstoned** [dbeaver/dbeaver#10102]
Hi

I am new to debeaver on a MAC. I am trying to find a local sample database for SQL Server to use. Please can someone point me in the right direction as to where I can find and load one?

Many Thanks

#### System information: 
- Operating system (distribution) and version
- DBeaver version

#### Connection specification:
- Database name and version

**Comment by uslss** [comment]
Hi @Goldstoned ,
DBeaver hasn't got local sample database for SQL Server.
You can find it here https://docs.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-ver15&tabs=ssms
