### ISSUE TITLE
Force cancel is annoying

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#10101]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.2.2
- Additional extensions

#### Connection specification:
- Database name and version Oracle 12
- Driver name ojdbc 19
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When cancelling a long running query, after a timeout I get the window below:
![immagine](https://user-images.githubusercontent.com/2157006/96441494-e6bbb900-1209-11eb-9aad-ea0517ac040d.png)

Now that is what happens:

- If I click yes, the database connection is closed. However, my sql editor is now unusable because the query is still recorded as runnng (see screenshot below)
- If I click no, the "Database not responing" window will show again and again and again until I click yes. I don't really have the option of letting it complete cancel (maybe a transaction needs to be rolled back). The fact that it's a modal dialog that doesn't allow me to do anything even on other connections adds to the annoying.

![immagine](https://user-images.githubusercontent.com/2157006/96442252-1ae3a980-120b-11eb-9b31-a8c381e98a8c.png)

**Comment by uslss** [comment]
Thanks for the bug report

**Comment by p91paul** [comment]
Also, I add, force closing should actually just invalidate the single  connection (i.e. disconnect and reconnect) when "separate connection for each script" is enable. Right now all connections to that database are killed, and all table editors are closed as a consequence.

**Comment by serge-rider** [comment]
Several improvements were added. 
Dummy confirmation dialog removed. SQL editor mustn't be blocked after query hang.

**Comment by uslss** [comment]
verified
