### ISSUE TITLE
Order Columns?

### ISSUE THREAD

**Issue by shaun-ba** [dbeaver/dbeaver#10106]
So as of version "Version 7.2.1.202009201907" is this still broken?

I've just spent half hour organising a filter, all the columns ordering and such, clicked save filter but cannot find a button to change to the saved filter??

All I want to do is order columns, I don't think that should be such a difficult feature, is this not possible with DBeaver?

Referencing this issue, I replied but it remained closed: https://github.com/dbeaver/dbeaver/issues/4166

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it in DBeaver 7.2.3. This file keeps filter settings %APPDATA%\DBeaverData\workspace6\.metadata\.plugins\org.jkiss.dbeaver.core\saved-data-filter.xml
Do you use this button Save filter settings?
![dbeaver_O7W8DcKH2v](https://user-images.githubusercontent.com/51405061/96467124-48dce400-1233-11eb-93fa-c90cb40bafa6.png)

**Comment by shaun-ba** [comment]
.

**Comment by shaun-ba** [comment]
.

**Comment by uslss** [comment]
if you talk about filter history it is saved after app restart in EE version only
![image](https://user-images.githubusercontent.com/31996417/96711223-e526f800-13a5-11eb-9bd1-634ce03c4fab.png)

**Comment by shaun-ba** [comment]
.

**Comment by uslss** [comment]
Both Column ordering and Filters (at the column header - 1 at the picture below) and Custom filters (2) where Column order and filters could be saved permanently using Save filter settings for current object button (3). 
![2020-10-21_14h41_21](https://user-images.githubusercontent.com/31996417/96715409-33d79080-13ac-11eb-9c61-4df95614d5b5.png)

History filter in Filter field is saved for the current app session only.

**Comment by shaun-ba** [comment]
.

**Comment by uslss** [comment]
@shaun-ba 
seems, we've talked about different features. If I understand you correctly, you tell about filters history that includes both column ordering and column filter and got the possibility to switch between those filters?
Such kind of feature isn't implemented, looks like a feature request

**Comment by shaun-ba** [comment]
.

**Comment by kseniiaguzeeva** [comment]
You can save one ordering/filter setting pressing Save filter settings for current object button (3).

**Comment by shaun-ba** [comment]
.

**Comment by serge-rider** [comment]
You can have only one column configuration per table. There is no such thing as "preset" for table columns view. After you save columns ordering/filters this configuration will be used next time you open this table.

@shaun-ba please be polite. People are trying to help you (for free).

**Comment by shaun-ba** [comment]
.

**Comment by serge-rider** [comment]
This feature is in CE version.

**Comment by p91paul** [comment]
I for one think that saving many different column layouts/orderings/filters is not a basic feature. In fact, I do not know of any database tool, free or otherwise, offering it. Nice feature request though.

As an alternative, you could save a simple script with your mostly used queries. By writing your own queries you can select any column layout, filter or sorting you desire. If the primary key columns are selected, and the table is fully qualified with the schema/database, you are also able to make cell modifications as in the table editor.
