### ISSUE TITLE
Move the setting section Appearance from General to User interface in Preferences

### ISSUE THREAD

**Issue by tati-kru** [dbeaver/dbeaver#10105]
It's a bit strange that DBeaver settings for themes, colors and fonts are in the General section instead of User interface.

**Comment by serge-rider** [comment]
@LonwoLonwo check patchPreferencePages method

**Comment by LonwoLonwo** [comment]
So. 
![2020-10-26 13_30_52-Window](https://user-images.githubusercontent.com/45152336/97448603-e1fdb000-1941-11eb-81c7-f30194f7d15c.png)

![2020-10-28 17_19_33-Preferences](https://user-images.githubusercontent.com/45152336/97448610-e4600a00-1941-11eb-8a58-078f802b87bd.png)

These pages moved from "General" settings into "User Interface" and "Editors". ("Editors" renamed from "Database Editors").

**Comment by kseniiaguzeeva** [comment]
Verified.
Note: Label decorations can be find in EE only.
