### ISSUE TITLE
dbeaver 7.2.3 deletion with uuid : binding not supported

### ISSUE THREAD

**Issue by mortifia** [dbeaver/dbeaver#10104]
this same deletion work fine in pgAdmin 4 

im use postgresql12 in ubuntu in wsl2 

![image](https://user-images.githubusercontent.com/22671054/96455452-8afb2b00-121d-11eb-8e00-b51d38942119.png)

**Comment by uslss** [comment]
duplicates #9964 .
Probably fix will be included in the 7.2.2 hotfix version that will be released today evening.
