### ISSUE TITLE
Data format pattern explanation.

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#10103]
It so happens that the data format settings use Oracle date patterns or others.
And we use standard Java patterns, where the case of letters is important.

Therefore, we need to create the ability to view the standard used in the DBeaver date formatting pattern.

Perhaps link to the article on the[ wiki](https://github.com/dbeaver/dbeaver/wiki)

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/issues/9390

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
Link to https://dbeaver.com/docs/wiki/Managing-Data-Formats/ in Data Format settings added
