### ISSUE TITLE
private key conversion doesn't seem to work without password

### ISSUE THREAD

**Issue by lyn1337** [dbeaver/dbeaver#10118]
#### System information: 
- Void Linux
- DBeaver version 7.2.2
- Additional extensions: none

#### Connection specification:
- mariadb via SSH tunnel 
- Authentication: Public Key

My SSH tunnel couldn't be opened. It appears the set private key needed conversion, which seemed to have failed due to the fact that my key isn't equipped with a password itself.

```
2020-10-20 19:04:52.395 - Specified private key cannot be converted:
Saving key "/tmp/.dbeaver-temp5908045879929263143/mariaDB-17546caca6c-72ad6451a667c46f.pem" failed: passphrase is too short (minimum five characters).
```

**Comment by uslss** [comment]
thanks for the bug report

**Comment by juliogc** [comment]
Same here:

**System information:**

- Ubuntu 20.04
- DBeaver version 7.2.3.202010191702
- Additional extensions: none

**Connection specification:**

- postgresql via SSH tunnel
- Authentication: Public Key

```
Specified private key cannot be converted:
Saving key "/tmp/.dbeaver-temp7249041726461356959/postgres-jdbc-175b35bd091-5cf3367c80964a37.pem" failed: passphrase is too short (minimum five characters).
```

**Comment by juliogc** [comment]
@lyn1337 A little update, I make this work by installing [DBeaver - SSHJ support](https://marketplace.eclipse.org/content/dbeaver-sshj-support) (also available at Help > Install new software)

**Comment by ShadelessFox** [comment]
Hello, @lyn1337, @juliogc is your problem with JSCH was solved after upgrading to newest version? Thank you,

**Comment by juliogc** [comment]
Hey @ShadelessFox 
First I tried with 7.2.4 and I had the same issue but in 7.2.5 everything is fine in JSch connections

Thank you

**Comment by grahamsutton** [comment]
Confirmed, upgrading from 7.2.4 to 7.2.5 also resolved the `Specified private key cannot be converted:` issue for me on Ubuntu 20.04 LTS.

**Comment by anton-reviakin** [comment]
7.3.0.202011291229 can't connect via ssh with key too
`Specified private key cannot be converted:
Saving key "/tmp/.dbeaver-temp140241000604814722/mysql8-176205c3c7b-789452e8359d298e.pem" failed: Permission denied.`

**Comment by ShadelessFox** [comment]
Hello, @anton-reviakin, thanks for the response. Can you try changing permissions of private key file you have specified in the SSH settings to see if it works? `chmod 600` should make the deal.

**Comment by anton-reviakin** [comment]
> Hello, @anton-reviakin, thanks for the response. Can you try changing permissions of private key file you have specified in the SSH settings to see if it works? `chmod 600` should make the deal.

Now works - I istalled SSHJ. But can't open a dropdown of ENUM field - only mousewheel

**Comment by ShadelessFox** [comment]
> Now works - I installed SSHJ. But can't open a dropdown of ENUM field - only mousewheel
Is the JSch not working even after changing file permissions? Also can you provide more details about dropdown you're talking about?

**Comment by slondr** [comment]
Still having this issue in DBeaver 21.2 using jsch

**Comment by ShadelessFox** [comment]
Hello @slondr,

Please create a separate issue and provide more details about your problem. This ticket is closed.
