### ISSUE TITLE
Adding a query with a variable to an existing task fails

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#10112]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 7.2.2
- Additional extensions N.A.

#### Connection specification:
- Database name and version Oracle 12
- Driver name ojdbc19
- Do you use tunnels or proxies (SSH, SOCKS, etc)? N.A.

#### Describe the problem you're observing:
I can create a data export task from a script containing variables (es ${var}). However, once created I'm unable to add another query to the same task using the same variable ${var} using the "Edit task" feature. Variable substitution won't be applied to new queries so columns for the query will not be loaded, making field mapping impossibile.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by ShadelessFox** [comment]
Hello, @p91paul, I cannot reproduce the issue using newer version (7.2.5). Can you please check on your side whether the problem was solved or not? Thank you in advance.

**Comment by p91paul** [comment]
looks like it.
Thanks!!
