### ISSUE TITLE
After 7.1.5 opening table list on schema is very slow for Db2

### ISSUE THREAD

**Issue by slavus** [dbeaver/dbeaver#10110]
#### System information: 
- Operating system (distribution) and version - Linux Opensuse tumbleweed
- DBeaver version - any version after 7.1.4 - this behaviour appeared in 7.1.5

#### Connection specification:
- Database name and version : Db2 11.5
- Driver name - db2
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
After upgrade to 7.1.5 and later opening table list on schema is very slow for Db2. It lasts for couple of minutes. 
In version before this was not the case. It looks like this was added with:
_Database navigator: Database size statistics was added for PostgreSQL, MySQL, SQL Server, DB2_

#### Include any warning/errors/backtraces from the logs
Dbeaver is executing 2 queries in this activity: 
 
`
SELECT *  FROM SYSCAT.TABLES WHERE TABSCHEMA = ?   AND TYPE IN ('G','H','L','T','U') ORDER BY TABNAME WITH UR     
`
This one is fast.

And this one is slow:
`
SELECT TABNAME, SUM(DATA_OBJECT_P_SIZE + INDEX_OBJECT_P_SIZE + LONG_OBJECT_P_SIZE + LOB_OBJECT_P_SIZE + XML_OBJECT_P_SIZE) AS TOTAL_SIZE_IN_KB
FROM SYSIBMADM.ADMINTABINFO
WHERE TABSCHEMA =?
GROUP BY TABNAME                                                                                                                     
`
I think there is a problem with ADMINTABINFO, something similar is documented here https://www.ibm.com/support/pages/db2-9x-query-against-sysibmadmadmintabinfo-too-slow

**Comment by uslss** [comment]
could you try if it reproducible against 7.2.3?

**Comment by slavus** [comment]
Same thing in all versions from 7.1.5 to 7.2.3. I have tired them all

**Comment by LonwoLonwo** [comment]
Hello @slavus 
I do not see other good table statistics reading solutions. Perhaps you have suggestions?

Also you can disable reading of table statistic in connection view settings:
![2021-04-07 15_13_12-](https://user-images.githubusercontent.com/45152336/113865017-473cb380-97b4-11eb-83eb-a9d21149b5de.png)

**Comment by serge-rider** [comment]
Statistics read can be slow for big databases. There is no good solution for everyone.
It can be disabled via context menu or in the preferences.

If you work with big prodaction databases then probably disabling statistics read is a good idea.
