### ISSUE TITLE
Ability to import CSV file into mysql with `ON DUPLICATE KEY UPDATE` option

### ISSUE THREAD

**Issue by ziofat** [dbeaver/dbeaver#10117]
#### System information: 
- Operating system (distribution) and version: Windows 10 and MacOS X
- DBeaver version: DbEaverEE 7.2.0

#### Connection specification:
- Database name and version

#### Describe your question:
As I am trying to import some updated data to mysql again, I found there are no ways to set  `ON DUPLICATE KEY UPDATE` or `REPLACE INTO`. Which cause duplicate key errors.

**Comment by kseniiaguzeeva** [comment]
Please try to use MySQL restore tool. 
Select Tools>Restore database in MySQL schema context menu and set settings in **Extra command args** field
![Screenshot 2020-10-21 at 16 04 14](https://user-images.githubusercontent.com/51405061/96723458-43100b80-13b7-11eb-90bd-d9bd030832b5.png)

**Comment by ziofat** [comment]
This method does not support CSV files AFAIK.

**Comment by kseniiaguzeeva** [comment]
Unfortunately it is not supported for CSV files. You should have SQL file.

**Comment by ziofat** [comment]
Well then this will be a feature request for import CSV file with `REPLACE INTO` through data transfer.
![image](https://user-images.githubusercontent.com/8521174/96830425-05ba8500-146e-11eb-9e80-5891a1ebadf2.png)

Like phpMyAdmin has an option for import CSV files with `ON DUPLICATE KEY UPDATE` option.

**Comment by kseniiaguzeeva** [comment]
Ok, I've changed it in feature request

**Comment by serge-rider** [comment]
Will be implemented in #10533
