### ISSUE TITLE
Is it an bug?

### ISSUE THREAD

**Issue by anityche** [dbeaver/dbeaver#10113]
#### System information: 
- Operating system (distribution) and version
win 10
- DBeaver version
7.2.3

#### Connection specification:
- Database name and version
postgreSQL 

#### Describe your question:

<pre>
### normal query 
select  *
from (
        select to_char(now(), 'yyyymmdd')::int as a
        union 
        select '20201019'::int as a
        union 
        select '20201018'::int as a
) t
where 1=1 
    and (a between 20201019 and 20201020
        or a >= 20201019
    )
 
### real DB query 
select 
    to_char(init_regi_dttm, 'yyyymmdd')
    ,init_regi_dttm 
from nsdbaptn.md_ptn_xxx_opt_dtl_hst
where goods_cd in (
    select distinct goods_cd 
    from nsdbaptn.md_ptn_xxx_opt_dtl_hst
    where 1=1 
    and ns_link_stat_cd = '49'
--    and to_char(init_regi_dttm, 'yyyymmdd')::int between 20201018 and 20201020    -- why not?
    and init_regi_dttm >= (now() - interval '2 day')    -- why not?
)
</pre>

download version 7.2.3 today.

**Comment by uslss** [comment]
hi @anityche 
could you clarify what problem happens in your case?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
