### ISSUE TITLE
SQLite - How to add column?

### ISSUE THREAD

**Issue by holden321** [dbeaver/dbeaver#10116]
Trying to add a column to an existing table by

`ALTER TABLE streams ADD errors_total INTEGER DEFAULT 0`

The result is only fake column in DBeaver interface 'Read-only: No corresponding table column'

http://joxi.net/v29W73LIZJGWxr

Is somewhere a special button for commit changes?

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
cannot reproduce it anymore against 7.3.0
