### ISSUE TITLE
Dependence object oracle

### ISSUE THREAD

**Issue by mipi21** [dbeaver/dbeaver#10119]
Please add features on oracle db.
For a table oracle we can se the depends for example a view or package witch use the table.

Thanks

**Comment by kseniiaguzeeva** [comment]
Please describe where do you want to see it exactly? Screenshot of a place will help.

**Comment by mipi21** [comment]
Hi, we can add in proprerties of table if possible.
![image](https://user-images.githubusercontent.com/6546228/96744932-d6503d80-13c5-11eb-8c29-6283c29278b6.png)

Thanks

**Comment by p91paul** [comment]
dba_dependencies/all_dependencies would be the place to get the information for this feature

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea!

**Comment by ShadelessFox** [comment]
Now dependent types can be viewed for tables, views and packages.
![image](https://user-images.githubusercontent.com/35821147/101892206-27a1cf80-3bb4-11eb-8c50-adbad8c94acc.png)

**Comment by mipi21** [comment]
wow

thanks

**Comment by uslss** [comment]
verified.
Will be available in 7.3.1

**Comment by p91paul** [comment]
nice
