### ISSUE TITLE
Error while edit postgresql inet fields

### ISSUE THREAD

**Issue by Kazun3500** [dbeaver/dbeaver#10122]
#### System information: 
- Operating system (distribution) and version

linux (ununtu 20.04 and debian sid)
- DBeaver version
 7.2.3.202010191702

#### Connection specification:
- Database name and version
postgresql 9.3+
- Driver name
![image](https://user-images.githubusercontent.com/13629272/96685892-6ec6cd80-1386-11eb-9227-c0cd2354b6fb.png)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
Cant edit (add or upgrade( any inet fields
[Запись экрана от 21.10.2020 09_35_39.zip](https://github.com/dbeaver/dbeaver/files/5414023/21.10.2020.09_35_39.zip)
![image](https://user-images.githubusercontent.com/13629272/96687465-99198a80-1388-11eb-96fe-87ca697fff7b.png)

#### Include any warning/errors/backtraces from the logs
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/5413992/dbeaver-debug.log)

**Comment by kseniiaguzeeva** [comment]
It should be fixed in scope of https://github.com/dbeaver/dbeaver/issues/9964#issuecomment-713126342
Please try early access version https://dbeaver.io/files/ea/

**Comment by kseniiaguzeeva** [comment]
Can reproduce it in EA version 7.2.3.202010202034

**Comment by LonwoLonwo** [comment]
Fixed in 7.2.5

**Comment by uslss** [comment]
verified
