### ISSUE TITLE
.sql file doesn't open

### ISSUE THREAD

**Issue by imidoriya** [dbeaver/dbeaver#10120]
If I assign dbeaver as the default application for a `.sql` file on MacOS or right click and open with dbeaver, it does not open the sql file.

I'd like it to open a new sql editor tab with the contents of the file.

Currently, I'm just opening the sql file up in another editor and then doing a copy / paste, but it would be nice if I could just double click an sql file and have it open in dbeaver.

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea.

**Comment by akilovich** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified
