### ISSUE TITLE
Can't disable resultset fetch size

### ISSUE THREAD

**Issue by bnserig** [dbeaver/dbeaver#10121]
#### System information: 
- Windows 10 64bits 2004
- 7.2.3
- DevStyle Darkest Dark Theme 1.11.0 & DBeaver Office Support 1.1.80

#### Connection specification:
- DB2 for i (V7R1M0)
- jt400 10.4

#### Describe the problem you're observing:
I want to disable result fetch size but I can't set it below 100.

#### Steps to reproduce, if exist:
Go to Preferences > Database Editors > Results
Edit resultset fetch size to 0
When we click on Apply it resets itself to 100

![image](https://user-images.githubusercontent.com/37617999/96686025-420eb800-137e-11eb-85c9-6a72fd5e49c0.png)

**Comment by kseniiaguzeeva** [comment]
It was implemented in 7.2.3 as a part of fix https://github.com/dbeaver/dbeaver/issues/10010.
Now you can set fetch size 100 and more.

**Comment by robobobeng** [comment]
Prior to version 7.2.3 it was possible to set fetch size to -1, which meant "infinity". It's not possible anymore and it's very annoying.

**Comment by serge-rider** [comment]
Yep, that makes sense.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
Changing the value of fetch size in Preferences has no effect.
Works ok if the value is changed in toolbar

**Comment by serge-rider** [comment]
Fixed
