### ISSUE TITLE
Unable to switch AWS role when connecting to Athena database

### ISSUE THREAD

**Issue by pdpark** [dbeaver/dbeaver#10129]
#### System information: 
- Operating system (distribution) and version: MacOS 10.15.7
- DBeaver version: 7.2.3

#### Connection specification:
- Database name and version: AWS Athena
- JDBC Driver: Simba Athena JDBC Driver, version 2.0.14

#### Describe your question:

I am unable to switch to an AWS role when connecting to an Athena database. When setting up the connection per the instructions for the Athena JDBC driver, I get the error: 

**_[Simba][AthenaJDBC] (100121) An error has occurred.
  No AWS profile named 'prodaccess'_**

The links to download the Athena JDBC driver and documentation pdf can be found here: https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html. 

See the instructions on pages 36 & 37 of the pdf under "Example: Using a Profile to Switch Roles". 

The example URL shown below is based on this AWS documentation example: [switch role scenario](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-cli.html#switch-role-cli-scenario-prod-env).

```
jdbc:awsathena://AwsRegion=us-east-1;S3OutputLocation= s3://my-athena-resultbucket/test/;AwsCredentialsProviderClass=com.simba.athena.amazonaws.auth.profile.Profile CredentialsProvider;AwsCredentialsProviderArguments=prodaccess;
```
I am setting the values for `AwsCredentialsProviderClass` and `AwsCredentialsProviderArguments` in DBeaver through the "Driver Properties" tab of the Connection Configuration dialog.

Note that the AWS documentation example will create the "prodaccess" profile in the `~/.aws/config` file, **NOT** the `~/.aws/credentials` file. 

The profile settings in the `~/.aws/config` file look like this:

[profile prodaccess]
role_arn=<role_arn>
source_profile=default

Also, the DBeaver connection dialog requires values in AWS Access Key and AWS Secret Key - they are not needed in this scenario.

**Comment by kseniiaguzeeva** [comment]
It is limitation of CE driver. Feature is not supported.
