### ISSUE TITLE
Error in CE 7.2.3 when sorting results

### ISSUE THREAD

**Issue by 11thPlague** [dbeaver/dbeaver#10127]
I often use sp_who in Sybase then sort by database name to see who is connected to which database.  This has worked fine until version 7.2.3.

Using the latest dBeaver Community Edition, it generates an error: SQL Error [102] [37000]: Incorrect syntax near ')'.  and shows the command being run as "SELECT * FROM ( sp_who) z_q ORDER BY z_q.dbname".    Even trying to manually run "SELECT * FROM (sp_who) fails with the same message." 

Not sure what changed, but this latest version isn't working.  Sorting columns on normal tables works fine, though.  Just not sp_who.

**Comment by uslss** [comment]
cannot reproduce it.
If I Execute just `sp_who` and then trying to sort it - works ok.
probably some special steps are needed?

**Comment by 11thPlague** [comment]
No special steps are needed.  I've attached the image to highlight the command I run then the sort button I click that immediately triggers the error condition specified at the outset.  It had worked fine for years before this.

![DBeaverError](https://user-images.githubusercontent.com/12241503/96887705-d77b7c00-1452-11eb-9e6d-66a6d89ecb61.jpg)

**Comment by uslss** [comment]
cannot reproduce it against 7.3.0
If the issue is still actual for you - feel free to reopen it.

**Comment by 11thPlague** [comment]
Yes, this is still an issue with the latest version.
