### ISSUE TITLE
Adding Dameng database support

### ISSUE THREAD

**Issue by wasd345** [dbeaver/dbeaver#10133]
中国达梦数据库官网 http://www.dameng.com/

表和表字段修改不了
1：表字段修改不了
2：表注释和列注释修改不了

**Comment by kseniiaguzeeva** [comment]
Please write comments in English.

**Comment by wasd345** [comment]
> Please write comments in English.

ok thank you

**Comment by wasd345** [comment]
Hello, big man, the English version of China's dream database official website has been online, please support as soon as possible, thank you
http://en.dameng.com/products.aspx?TypeId=97&;FId=t3:97:3

**Comment by kseniiaguzeeva** [comment]
Thank you for the news. It is in our plans to do it, but we don't know when exactly.

**Comment by Laughdie** [comment]
现在支持达梦数据库和瀚高数据库吗？
