### ISSUE TITLE
Quick filter in DB Navigator: multiple database filters + Fast favorites

### ISSUE THREAD

**Issue by Dimas-sc** [dbeaver/dbeaver#10137]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.2.3

#### Connection specification:
- Database name and version: MySQL 5

#### Describe your question:
Is it possible to filter two different table names in the database object filter? Like "table1|table2"
Is there a fast way to alternate between show only favorites tables / show all?

We're evaluating to migrate from Heidi SQL and, as we work with many databases and tables, we love these two features: fast filter + fast favorites.

Thx

**Comment by kseniiaguzeeva** [comment]
Thank you for interesting in DBeaver. Yes, both options are available:
You can filter different table names:
1. Using the filter button in the object editor.
- Uncheck / check the Enable box to remove or apply the filter.
- Also you can save the filter using the field at the bottom and use the saved filter later.
![Screenshot 2020-10-24 at 11 33 24](https://user-images.githubusercontent.com/51405061/97077915-4a6e2980-15f0-11eb-9e79-7d0947773f08.png)

2. It is possible to use the same filter in DB Navigator tree. Select Filter in an object's context menu.
![Screenshot 2020-10-24 at 12 00 00](https://user-images.githubusercontent.com/51405061/97077961-c8323500-15f0-11eb-984e-0bc6f3599b7e.png)

Here is wiki article https://github.com/dbeaver/dbeaver/wiki/Configure-Filters
Please feel free to ask any other questions.

**Comment by Dimas-sc** [comment]
Hi, how can I reopen the issue?

I saw this save filter options but it's no the same I was asking for, the filters management is slow and static, I'd like to:

1. (and most important) use the input text filter in the DB Navigator to filter for example two (or more) tables: table1|table2
2. possibility to mark favorites tables from the same DB Navigator and toggle it hidden or not with a button. It can be done with the saved filters you said, but this management is slow and tedious.

**Comment by Dimas-sc** [comment]
> 
> 
> Thank you for interesting in DBeaver. Yes, both options are available:
> You can filter different table names:
> 
>     1. Using the filter button in the object editor.
> 
> 
>     * Uncheck / check the Enable box to remove or apply the filter.
> 
>     * Also you can save the filter using the field at the bottom and use the saved filter later.
>       ![Screenshot 2020-10-24 at 11 33 24](https://user-images.githubusercontent.com/51405061/97077915-4a6e2980-15f0-11eb-9e79-7d0947773f08.png)
> 
> 
>     1. It is possible to use the same filter in DB Navigator tree. Select Filter in an object's context menu.
>        ![Screenshot 2020-10-24 at 12 00 00](https://user-images.githubusercontent.com/51405061/97077961-c8323500-15f0-11eb-984e-0bc6f3599b7e.png)
> 
> 
> Here is wiki article https://github.com/dbeaver/dbeaver/wiki/Configure-Filters
> Please feel free to ask any other questions.

I need to create a new ticket?

**Comment by kseniiaguzeeva** [comment]
I reopen it, thank you for the details.

**Comment by kseniiaguzeeva** [comment]
We are going to implement it.

**Comment by Dimas-sc** [comment]
Nice, thx!! Can't wait for the 8.0 release 👏👏

**Comment by Dimas-sc** [comment]
An addendum: it'd be very helpful the possibility to filter at the same time databases and tables. At others tools there are two separate input filters:

------------------------------
| database filter | tables filter |
------------------------------

**Comment by Savers80** [comment]
I have open this request feature, that is related with this 
https://github.com/dbeaver/dbeaver/issues/11798

**Comment by LonwoLonwo** [comment]
Implemented.
You can use space, pipe (|) or comma (,) for multiple filters (connections, containers, tables etc.) in DBeaver 21.1.1

![2021-06-14 23_49_34-DBeaver Enterprise 21 1 1](https://user-images.githubusercontent.com/45152336/121958892-c9c19080-cd6c-11eb-8cad-5306e2ad3890.png)

![2021-06-14 23_50_07-DBeaver Enterprise 21 1 1](https://user-images.githubusercontent.com/45152336/121958895-ca5a2700-cd6c-11eb-8606-d12e76637a56.png)

![2021-06-14 23_51_32-DBeaver Enterprise 21 1 1](https://user-images.githubusercontent.com/45152336/121958897-ca5a2700-cd6c-11eb-8069-fc165f69cbc7.png)

**Comment by Dimas-sc** [comment]
Can't wait to update and try it!! 🙌

**Comment by uslss** [comment]
verified
