### ISSUE TITLE
Postgresql UUID primary keys not supported for edits in table

### ISSUE THREAD

**Issue by pauldaustin** [dbeaver/dbeaver#10130]
#### System information: 
- Operating system (distribution) and version: Windows 10 64-bit
- DBeaver version: 7.2.3

#### Connection specification:
- Postgresql2
- Driver name: org.postgresql:postgresql:42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
When editing data in the Data table you can't save records that have a UUID column. It throws an error that binding is not supported. I thought it did work until a recent version change.

#### Steps to reproduce, if exist:
```
CREATE TABLE uuid_table (
	id2 uuid NOT NULL,
	"name" text NOT NULL,
	id uuid NOT NULL,
	CONSTRAINT newtable_pk PRIMARY KEY (id2)
);
insert into uuid_table
(id,name)
values (
'89624d6d-4170-4ef5-b79d-f623c7a5fc35',
'test')
```

Open the Data table and change the name test to test2 and then click save.

#### Include any warning/errors/backtraces from the logs
```
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_CA
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Wed Oct 21 08:59:21 PDT 2020
Object parameter [00000000-0000-0000-9999-000000000004] binding not supported
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. It duplicates #9964 
The issue will be fixed in 7.2.4. You can try early access https://dbeaver.io/files/ea/
