### ISSUE TITLE
about Smart Commit Mode

### ISSUE THREAD

**Issue by vladius1972** [dbeaver/dbeaver#10135]
DBeaver ce 7.2.3
Windows 10

#### Describe your question:
Page: https://github.com/dbeaver/dbeaver/wiki/Auto-and-Manual-Commit-Modes
Text: "When smart commit is enabled and you are in manual commit mode then DBeaver will monitor your activity."
Perhaps more correct for this mode such a text: "When smart commit is enabled and you are in Auto-commit mode then DBeaver will monitor your activity." or DBeaver bug?

**Comment by kseniiaguzeeva** [comment]
thank you for your attention. Corrected
