### ISSUE TITLE
Sequence Oracle not visible in Navigation Database

### ISSUE THREAD

**Issue by mipi21** [dbeaver/dbeaver#10136]
Hi, I can't see sequences on oracle in Navigation Database, i'ts a problem o my setting in DBeaver? 
On sqlDeveloper the sequece is visible

![image](https://user-images.githubusercontent.com/6546228/96863091-a5741500-1466-11eb-92cd-7cec66bffa23.png)

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. 
Please check whether filter line was used at the top of DB Navigator or filter in context menu.  
![Screenshot 2020-10-23 at 11 38 59](https://user-images.githubusercontent.com/51405061/96976498-9ce21400-1524-11eb-8efe-a7609072f9d6.png)
![Screenshot 2020-10-23 at 11 39 13](https://user-images.githubusercontent.com/51405061/96976503-9eabd780-1524-11eb-9f0b-d28caf969a30.png)

If there are no filters in filter settings please tell your OS, Oracle and DBeaver version.

**Comment by mipi21** [comment]
Sorry there are a filter.

Thanks for all
