### ISSUE TITLE
Multiple Values for Parameter in Task

### ISSUE THREAD

**Issue by j-coates** [dbeaver/dbeaver#10131]
I have a report that I need to export for multiple values of a parameter. For example, different customers for a single customer report.

Basically what I'm looking for is a way to have a task run through a query multiple times and input a set list of values into a single parameter one at a time.

I tried editing the task in the tasks.json file to include multiple parameters and also copied the query multiple times and tried a different parameter for each without success. I'm assuming that failed because each query didn't contain all the parameters.

**Comment by kseniiaguzeeva** [comment]
Am I correct that you have a query with a bind parameter in export task and you want:
1. To set different values for one bind parameter and export the query results in one file?
2. Or to have possibility to change a bind parameter when press the button to run task?

**Comment by j-coates** [comment]
Sort of your first option, but instead I need it in separate files. I'm exporting results from one aggregate system to be used in multiple singular systems. The list of parameter values never changes, but I have to transfer the files every week.

Now that I'm explaining it, all I need to do is copy the query and hard-code the values in for each copy. I'm apparently trying to make this more difficult than it needs to be.

**Comment by kseniiaguzeeva** [comment]
Thank you for the clarifying.
Now it is available in Enterprise Edition. You can create separate export tasks and include them in one composite task.
Also you can schedule it in Enterprise Edition (for example to run the task every Monday).
Please see scheduler description in wiki
https://github.com/dbeaver/dbeaver/wiki/Task-Scheduler
