### ISSUE TITLE
How to get previous versions of Office Extensions

### ISSUE THREAD

**Issue by emhlbmc** [dbeaver/dbeaver#10147]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
6.x

#### Describe your question:
When install office extension on DBeaver, I only found the latest version of the plugin(https://dbeaver.io/update/office/), and it doesn't match my DBeaver version. 
So where could I get the all previous versions? 
Thanks.

**Comment by kseniiaguzeeva** [comment]
You can find all last versions of extensions in archive https://dbeaver.io/files/6.0.0/repository-office/
