### ISSUE TITLE
Default Data Source in SQL Editor #5318 was never answered!

### ISSUE THREAD

**Issue by elrod-johnson** [dbeaver/dbeaver#10146]
Default Data Source in SQL Editor [#5318](https://github.com/dbeaver/dbeaver/issues/5318)

i would love to comment on this existing issue, but it was closed with this very unhelpful comment:
**[already implemented]( https://github.com/dbeaver/dbeaver/issues/5318#issuecomment-582958359-permalink)**.

what does this comment mean?
**if it was implemented, where was it implemented? how do i use it?**

i can find no way to set the default data source for a project.
dbeaver's online help has no search capability that i could find.
google doesn't tell me how to do it.

so i'll ask again:
is it possible to set a default data source for a project or a folder in a project so that every new .sql file is automatically associated with that data source?
if so, how do i set it?
thanks

**Comment by uslss** [comment]
For now, New SQL editor active data source depends on the context.
As for me in case of opening SQL editor for a project which contains one connection only, a new editor is automatically associated with this connection (gif attached).
Does it solve your problem?
![2020-10-23_13h10_52](https://user-images.githubusercontent.com/31996417/96991757-9b6b1880-1531-11eb-98e3-37d452abe254.gif)

**Comment by elrod-johnson** [comment]
thanks for the reply. 
here's my project setup:
![image](https://user-images.githubusercontent.com/11749682/97061683-82239580-154c-11eb-885e-9caf7adb8b2c.png)

i want any scripts i add to folder 'E:\__FVHS\!!!!!__AdminSIS_missing_maestro_data' to be automatically associated to the project data source. 

i don't create my .sql scripts in dbeaver. i create them programatically elsewhere, but they end up in the above folder. i just use dbeaver to tweak them if needed and to run them against the selected project data source. 

right now, if i add a .sql file to the folder using my external script generator, then open the scripts per your .gif, i don't see the new .sql file, only the old ones where i've manually selected the data source for each one.

is there any way to make dbeaver pick up the newly added scripts? 
thanks for your help.

**Comment by p91paul** [comment]
Pressing f5 on the folder in the projects view should do the trick. I don't think your script will be associated with any data source though, because of them not being created in dbeaver, you'll need to associate them manually.

**Comment by elrod-johnson** [comment]
Pressing f5 has no bearing on my issue.

**Comment by uslss** [comment]
feature request related #11448
