### ISSUE TITLE
Postgres Duplicate Row with SERIAL key duplicates the Key field!

### ISSUE THREAD

**Issue by Nij4t2** [dbeaver/dbeaver#10148]
#### System information: 
- Windows 10 Pro release 2004
- DBeaver version 7.2.3.202010191702
- Additional extensions: None

#### Connection specification:
- Postgres
- PostgreSql JDBCDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
In the DBeaver UI for a table with a PK column with type SERIAL, I click the 'Duplicate Current Row' button, and the current row is duplicated.  If I then try to save the record, an error results, because it turns out that it has duplicated the key value in addition to every other column.
_I believe that this might be a regression in this week's version of DBeaver_.
As an aside, if I then manually edit the key value so that it is now unique, future attempts to use code to insert to the table will now fail with duplicate key errors, as the sequence on the table is now returning the duplicate key value (i.e. that I manually edited).

#### Steps to reproduce, if exist:
* Highlight row in table with SERIAL PK column;
* Click Duplicate Current Row button;
* Note that the PK key column has been duplicated; 
![image](https://user-images.githubusercontent.com/40146284/96964284-1ddbe400-1502-11eb-9ded-d33203bf6b4d.png)

* 'Save' and get duplicate key error.

An example of how I see this SERIAL column definition: I note that sometimes I think I have seen a reference to the sequence column in the default value, but this is not the case here:
![image](https://user-images.githubusercontent.com/40146284/96964395-495ece80-1502-11eb-8d85-d8cf7902c371.png)

Finally, something is very odd about this... if I try to manually clear the column to NULL to activate the default value, what appears to happen is that the row is supposedly saved with a PK column value of NULL... where that column should be NOT NULL:
![image](https://user-images.githubusercontent.com/40146284/96965306-d35b6700-1503-11eb-8c09-90fff2bdf469.png)
It appears as if I can save the record, ans I do so without error, but if I close and reopen the window I can't see the record.

**Comment by Nij4t2** [comment]
On a related note, if I 'generate sql' on this table for an INSERT statement, the generated sql includes setting the PK column, which I believe is in error. If I try the same for a table where the PK column is set as 'int4 NOT NULL (Identiy: Always)' the generated SQL does _not_ include the primary key column.

**Comment by LonwoLonwo** [comment]
Information in default field for serial data types restored. 
PK key column data duplicate fixed. 
Generate SQl fixed - no data, when PK is serial.

**Comment by kseniiaguzeeva** [comment]
Could you please also fix:
1. Autocomplete of serial value doesn't work when it is the only column.
![dbeaver_LduT5tObFH](https://user-images.githubusercontent.com/51405061/97098277-3972f600-168c-11eb-9bce-4508a68ba47c.png)
2. An incorrect autocomplete of the serial cell **in the second row**  in the table with two or more columns
![xd9NLJgad2](https://user-images.githubusercontent.com/51405061/97098279-3f68d700-168c-11eb-9bbc-a8a1ad1fdcc8.gif)

3. Wrong SQL expression is generated via Data Editor context menu. Select Generate SQL>Insert into
Actual result:
```sql
INSERT INTO "serial"
("serial", column1)
VALUES(NULL, 'q');
```
Expected:
```sql
INSERT INTO "Xeniia"."serial" (column1)
	VALUES ('q');
```

It can be tested in PostgreSQL12 dvdrental.Xeniia.serial
DBeaver	7.2.4.202010241024

**Comment by kseniiaguzeeva** [comment]
Verified issue with about Generate SQL and duplicating rows with seial type. Separate ticket https://github.com/dbeaver/dbeaver/issues/10168 is created for other issues from comment above
