### ISSUE TITLE
Content Viewer data handling improvements

### ISSUE THREAD

**Issue by Zbambus** [dbeaver/dbeaver#10149]
I just jumped from community editiion 7.2.0 to 7.2.3.

The one fature change that surprised me was that the default view mode of content of a CLOB now was binary mode (hitting Shift+Enter when cell is chosen in result grid) . This **probably** makes sense as plain text is supposed to be handled by a CLOB column instaed of a BLOB.

Unfortunately I have inherited a database where the BLOB column is used to store both text and binary files in a ratio 99% text and 1% binary, and BLOB was chosen in order to accomodate the 1% cases, but in 99% of the cases when I want to see the content of the column, text is what I want to see.  Yes, not the best solution, but there it is!

I looked through preferences up to see if I could find somewhere to set the default mode of presentation, but was unable to locate this. That would have solved this situation nicely as I could just set such an parameter/option to "Text".

My next search involved if there is a key combination that would let me toggle between the modes ("Text"/"Binary"). That would involve one more command entered on the keyboard after opening the view of the content, but that was fine as opposed to now having to use the mouse to point on the "Text" tab and activate this, which is very time consuming as the mouse pointer might be anywhere on my 3-screen setup. I was unable to locate this as well.

So to sum it up : 

1) Is there a way to determine what presentation mode is to be default when viewing content from a BLOB column?
2) Is there a way to use the keyboard to toggle between the presentation modes when viewing content from a BLOB/CLOB column?
3) Is there a way to determine what presentation modes are to be available when viewing content from a BLOB/CLOB column? Today BLOB comes with "Text" and "Binary", while CLOB comes with "Text", "Binary", "JSON" and "XML".  There is really no reason to not include "JSON" and "XML" for BLOB presentation as such a column might contain Json and XML content as well.

If the answer is **no** to the questions above, could it be considered as candidates for a future release? As of now I'm probably downgrading to 7.2.0 again because my daily work very much involves having to look at the content of said column and the extra effort of using the mouse to change presentation mode becomes a huge obstacle.  Every action, that can not be solved with key combinations on the keyboard but involves a mouse, is to be avoided in the name of efficiency, in my opinion.

Thanks for the effort to develop dBeaver which is a fantastic piece of software!

**Comment by kseniiaguzeeva** [comment]
Thanks for the suggestion. Additional view configuration needs to be added.

**Comment by Zbambus** [comment]
Hi good people at dBeaver.
Any desicion taken, upon which release, this request might be added to the configuration of dBeaver?

**Comment by Matvey16** [comment]
@Zbambus Currently planned for 21.2.1

**Comment by Zbambus** [comment]
Thanks for the update, and looking forward to be able to download and use the new releases of dBeaver as they are made available.

**Comment by CComparon** [comment]
Not sure if #13243 is a strict subset of this issue, but I'll be happy as long as JSON columns will be displayed as JSON by default or at least if DBeaver remembers my choice for this column.
![image](https://user-images.githubusercontent.com/12992190/126079059-29e1f57c-42af-4593-b2cc-c5e451255954.png)
Many thanks!

**Comment by ShadelessFox** [comment]
Now we save last manually chosen content viewer for column.

Since the title was changed, the initial request was mostly ignored. We can further improve support for different viewers according to no. 1, 2 and 3.

**Comment by Zbambus** [comment]
The work done so far on this item is that the preferred viewing mode for a column is saved for the "Value" column?

![image](https://user-images.githubusercontent.com/47529756/139644316-fa4fbcdc-d8a7-4a4e-9899-b0093607f1a2.png)

But what if the user hits "Shift+Enter" on a column containing BLOB/CLOB? Then a complete new window is opened and the content of the current column is displayed in this window. And the BLOB still is presented as Binary as default. Even if I change to Text, the next time I hit "Shift+Enter", it's Binary again.

Refering to the intial request, this was the window/display that was described.

![image](https://user-images.githubusercontent.com/47529756/139644838-25b65628-4c98-4f5e-b8a4-904e8ccb4a50.png)

This is perhaps what "ShadelessFox" is refering to in the last comment? That this screen is one of the "different viewers"? And that these "viewers" are already planned to be targeted in an upcoming release?

A very quick fix for this viewer would be to always add Text/Binary/JSON/XML banners and introduce key combination(s) that allows the user to switch between the different modes. Then the default behaviour of presenting BLOB as Binary and CLOB as Text, which makes sense, is perfectly fine, as it will only be a quick touch on the keyboard to get the presentation mode that is desired by the user for that particular situation.

![image](https://user-images.githubusercontent.com/47529756/139645653-509c594b-3154-4431-8f66-b1bd609995af.png)

Either a key combination  that just toggles cyclically through the different presentations or a set of key combinations that target each presentaton directly e.g. 

Ctrl+Shift+T -> Text
Ctrl+Shift+B -> Binary
Ctrl+Shift+J -> JSON
Ctrl+Shift+X -> XML

**Comment by ShadelessFox** [comment]
2. Implemented ability to define keybindings for switching between content viewers (no keybindings are set by default):

![image](https://user-images.githubusercontent.com/35821147/151137148-79a1f8f4-d971-43c3-9202-dc6c88b04542.png)

3. Textual content viewers (JSON, XML) are now also available for binary data:

![image](https://user-images.githubusercontent.com/35821147/151137389-a0f80a0c-e1a1-4037-91c7-235d993c9d86.png)

**Comment by Matvey16** [comment]
Verified
