### ISSUE TITLE
Named parameters in while loop

### ISSUE THREAD

**Issue by Oltrox** [dbeaver/dbeaver#10145]
- Windows 10
- DBeaver 7.2.2

- Oracle 11G Express

I want to bind parameters inside of an anonymous block... but in a while loop. When I do this, dbeaver only request the parameters one time, and then uses the same parameters to the next iterations. 

Step 1:
![Screenshot_1](https://user-images.githubusercontent.com/18354160/96930411-08c76c80-1492-11eb-88e8-64c43593b358.png)

Step:2
![Screenshot_2](https://user-images.githubusercontent.com/18354160/96930439-13820180-1492-11eb-8524-1af229020b89.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by kseniiaguzeeva** [comment]
Some clarifications were required. The behavior you described happens on the server side. Therefore it works as expected.

**Comment by Oltrox** [comment]
yeah, but how I can clean these parameterse, cause it uses the same values for every iteration, and I dont want that

**Comment by p91paul** [comment]
I believe there's nothing dbeaver can do. That begin/end block is seen by Oracle as a single statement. The database itself does not support getting multiple parameters for them.
