### ISSUE TITLE
cassandr key space problem

### ISSUE THREAD

**Issue by thomas81528262** [dbeaver/dbeaver#10144]
#### System information: 
- Operating system (distribution) and version
Widnow 10
- DBeaver version
DBeaver Enterprise
7.2.0.203009071746

#### Connection specification:
- Database name and version
Cassandra

#### Describe the problem you're observing:

If the keyspace mix with lowercase and uppercase can not query the keyspace.
It always show the message can not find the keyspace.

for example:

db --> working

dbTEST --> not working

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
It is not a bug.
You must enclose your keyspace in double quotes if it was created in mixed case. This is not a DBeaver issues but Cassandra CQL language limitation, see https://docs.datastax.com/en/cql-oss/3.x/cql/cql_reference/ucase-lcase_r.html or https://docs.datastax.com/en/developer/java-driver/4.9/manual/case_sensitivity/

DBeaver encloses keyspace name in double quotes automatically if you use autocompletion (ctrl+space).

**Comment by thomas81528262** [comment]
It already add the quotes, but still fail. Here is the example.

![image](https://user-images.githubusercontent.com/20622045/98482222-c81b6300-21b4-11eb-99d9-84f88ab3a5dc.png)
![image](https://user-images.githubusercontent.com/20622045/98482244-ed0fd600-21b4-11eb-8076-bcf60eea7d9b.png)

**Comment by kseniiaguzeeva** [comment]
_It is actual if you made Read Data in SQL console for such schema name (e.g. NewKeyspace.users)._

**Comment by serge-rider** [comment]
By some reason it fails during active keyspace change. This is reproducible on MacOS only. 
Fixed (I add explicit quotes for keyspace name during cluster connect procedure).

**Comment by kseniiaguzeeva** [comment]
verified
