### ISSUE TITLE
errors in older .sql files

### ISSUE THREAD

**Issue by selster** [dbeaver/dbeaver#10142]
I have a lot of .sql files from previous work with dBeaver.  I am finding that the older files will make funny errors when run, today, for instance
select * from pbm1712a, will say: ERROR: relation "pbm1712a" does not exist, in the older .sql file; but if I open up a new instance of the sql editor, the same command will "find" the file. I can't figure out why the below will not find pbm1712a, in the old sql file but will in a new instance:

set session my.vars.id = '033209365'; -- 
drop table if exists zzSet;
create table zzSet (mapn text);
insert into zzSet select trim(current_setting('my.vars.id')::text);
select * from pbm1712a where apn ilike (select mapn from zzSet)

pbm1712a is listed in dBeaver's explorer.

![pbm1712a](https://user-images.githubusercontent.com/8466033/96897458-76987780-1443-11eb-8035-39608278b0f3.jpg)

Thanks, Steve

**Comment by kseniiaguzeeva** [comment]
Could you please check whether a correct database and schema are selected in upper toolbar of SQL Editor for older scripts?
![dbeaver_EJ3MvLCCGB](https://user-images.githubusercontent.com/51405061/97555466-360f9f80-19e9-11eb-8b04-e4a93d43ef5a.png)

**Comment by uslss** [comment]
there are no updates on the issue for a long time.
If it is still actual for you - feel free to reopen the ticket with an additional info
