### ISSUE TITLE
Incorrect DDL for Created Materialized Views

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#10154]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.2.3

#### Connection specification:
- Database name and version Oracle

#### Describe the problem you're observing:
Case 1:
The error message is shown in the Declaration tab for Created (not saved) MV
#### Steps to reproduce, if exist:
Start MV creation and switch to declaration tab - error message is shown
![image](https://user-images.githubusercontent.com/31996417/97005591-54881d80-1547-11eb-98ca-fc8fe2cd241c.png)

Case 2:
In case of creation MV with the name of already existing MV, DDL from existing MV is shown.
#### Steps to reproduce, if exist:
1. Start the creation of MV (Sys.NewView MV already exists, new MV got the same name)
2. Open Declaration tab - DDL from existing MV is shown.
![image](https://user-images.githubusercontent.com/31996417/97006115-0889a880-1548-11eb-9dd4-d6e258348b89.png)

**Comment by LonwoLonwo** [comment]
Case 2 actual for PostgreSQL mviews too 
![2020-10-23 18_58_53-DBeaver Enterprise 7 3 0 - NewView_1](https://user-images.githubusercontent.com/45152336/97026387-f9afef80-1561-11eb-9d09-fd44f3931a58.png)

**Comment by uslss** [comment]
verified
