### ISSUE TITLE
MSSQL -> MYSQL data import for mssql nvachar.

### ISSUE THREAD

**Issue by ralic** [dbeaver/dbeaver#10150]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
7.2.0 CE
- Additional extensions
NA

#### Connection specification:
- Database name and version
MSSQL 17 / MYSQL 8

MYSQL 8 
1. Charset --> utf8mb4 
2. Collation --> utf8mb4_0900_ai_ci

- Driver name
Standards
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
While I am trying to import data from MSSQL to MYSQL, I found the auto schema translation failed to convert MSSQL data type nvarchar with length 0 to MYSQL varchar. It is possible to use varchar(1111) at the first beginning and grow it up by adding 2000 at a time. On the other hand, smalldatetime type in MSSQLshall be automapping to date.
ex. 1111 -> 2111 -> 3111 -> ... -> 16380. Actually, MySQL shall allow varchar(16380) since utfmb4 takes 4 bytes for one Unicode char. Or just map it to text type. Please help check.

Related discussions 
1. 
https://stackoverflow.com/questions/332798/equivalent-of-varcharmax-in-mysql
2. utf8mb4 is for all Unicodes.
https://stackoverflow.com/questions/30074492/what-is-the-difference-between-utf8mb4-and-utf8-charsets-in-mysql#:~:text=As%20of%20MySQL%205.5.,%2C%20same%20encoding%2C%20same%20length.

#### Steps to reproduce, if exist:
failed data columns info for MSSQL to MYSQL
```
Column Name	#	Type	Length	Scale	Precision	Not Null	Identity	Default	Description
ShowMethodNotice	106	nvarchar	0	[NULL]	[NULL]	false	false	[NULL]	
Column Name	#	Type	Length	Scale	Precision	Not Null	Identity	Default	Description
Info	209	nvarchar	0	[NULL]	[NULL]	false	false	[NULL]	[NULL]

```
#### Include any warning/errors/backtraces from the logs

err-log
```
SQL Error [1074] [42000]: Column length too big for column 'Info' (max = 16383); use BLOB or TEXT instead
  Column length too big for column 'Info' (max = 16383); use BLOB or TEXT instead
  Column length too big for column 'Info' (max = 16383); use BLOB or TEXT instead
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. As a workaround you can set column type manually in Export wizard (Press **Columns** in Tables mapping step)
![DJHprePvPx](https://user-images.githubusercontent.com/51405061/96997850-387e7f00-153b-11eb-86d2-9c4bdf28771d.png)

**Comment by ralic** [comment]
Yep. I am already remapped it manually now. In addition to the original finding, smalldatetime shall be mapped to date from MSSQL to MYSQL.

**Comment by ralic** [comment]
One more error encountered, the data type ntext in MSSQL shall map to LONGTEXT in MYSQL.

**Comment by LonwoLonwo** [comment]
smalldatetime data type in Dbeaver 21.1.2 in the export case from SQLServer to MySQL already turns into a timestamp. https://docs.microsoft.com/en-us/sql/t-sql/data-types/smalldatetime-transact-sql?view=sql-server-ver15

A can't create a table with "nvarchar with length 0", so can't fix it.

And I added better support for data types mapping, containing "text" in these names.

![2021-07-14 18_14_41-Window](https://user-images.githubusercontent.com/45152336/125741336-6a411dcd-6321-47f3-8f27-da69427b07c1.png)

**Comment by Matvey16** [comment]
Verified
