### ISSUE TITLE
[MongoDB] Some tables can be opened in JSON view only in Data Editor

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10166]
#### System information:   
- DBeaver version 7.3.0 EE EA

#### Connection specification:
- Database name and version MongoDB

#### Steps to reproduce, if exist:
Open some table in MongoDB (e.g. test.actor or test.customer_interleaved)
Actual result: only tab JSON exists, no data in the table
![Screenshot 2020-10-26 at 12 14 32](https://user-images.githubusercontent.com/51405061/97154520-06f8f400-1785-11eb-896f-cbb66e1e0958.png)

**Comment by serge-rider** [comment]
It is not a bug. There is no table structure in empty collections.
