### ISSUE TITLE
Column Rows do not show up, until select all

### ISSUE THREAD

**Issue by Chrisfufu** [dbeaver/dbeaver#10162]
#### System information: 
- MacOS Big Sur 11.0 Beta
- DBeaver: Version 7.2.3.202010191702

#### Connection specification:
- MySQL database

#### Describe the problem you're observing:
The first time I open a table, the Columns text do not show up. Then, select all Column rows, all the rows will stay. 
![image](https://user-images.githubusercontent.com/21689797/97098119-12420780-163f-11eb-95b3-5b816c6d29e9.png)
![image](https://user-images.githubusercontent.com/21689797/97098123-1a01ac00-163f-11eb-99b1-b449bd7328bd.png)

**Comment by kseniiaguzeeva** [comment]
Could you please send log files?

**Comment by Chrisfufu** [comment]
> Could you please send log files?

Where is the log file? There is no error, it's just the rows are not showing up until I hit "command + A" or use the mouse to select them all.

**Comment by kseniiaguzeeva** [comment]
Maybe we manage to find something usefull here. Please see where logs are: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by Chrisfufu** [comment]
> Maybe we manage to find something usefull here. Please see where logs are: https://github.com/dbeaver/dbeaver/wiki/Log-files

ok. I will take a look later today. and give you a screenshot.

**Comment by kseniiaguzeeva** [comment]
Thank you! You can send files here or kseniia@jkiss.org

**Comment by Chrisfufu** [comment]
> Thank you! You can send files here or [kseniia@jkiss.org](mailto:kseniia@jkiss.org)

I opened the error log, however, I don't see anything related to this. here is the screenshot.
![Uploading image.png…]()

**Comment by Chrisfufu** [comment]
Then I select all, all the rows under "Columns" will stay there. 
![image](https://user-images.githubusercontent.com/21689797/97373343-705b2e80-187b-11eb-9293-e56b6c512f3a.png)

**Comment by Chrisfufu** [comment]
When I try to create a new column, on the left panel, it contains the new column, however, I cannot see it in the **properties**.
when I click on save, the **sql** does not show up properly as well: maybe needs to padding-top? because I only see the third new column (see screenshot 2). when I clicked on open editor on the second screenshot: it contains the sql data (see screenshot 3)

![image](https://user-images.githubusercontent.com/21689797/97666206-c4643f80-1a42-11eb-8f91-c9b0c6523d06.png)
![image](https://user-images.githubusercontent.com/21689797/97666376-2329b900-1a43-11eb-8eca-3946a60a1a1e.png)
![image](https://user-images.githubusercontent.com/21689797/97666429-49e7ef80-1a43-11eb-85b8-b0fed4a81388.png)

**Comment by Chrisfufu** [comment]
I did a test on another mac machine, not with the Big Sur system. I think maybe the Big Sur is the reason why it got displayed improperly.

**Comment by kseniiaguzeeva** [comment]
Thank you for the additional details. Could you please also send log files https://github.com/dbeaver/dbeaver/wiki/Log-files?

**Comment by Chrisfufu** [comment]
> Thank you for the additional details. Could you please also send log files https://github.com/dbeaver/dbeaver/wiki/Log-files?

I have downgraded my system from Big Sur to Catalina. I don't have the issue in the Catalina system anymore.

**Comment by Chrisfufu** [comment]
Here is the log file. But nothing is related to **view properties error**
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/5543113/dbeaver-debug.log)

**Comment by marcolopes** [comment]
https://github.com/forcedotcom/dataloader/issues/217

**This is an SWT related issue**, that has become "incompatible" with macOS **Big Sur**. For the sake of all eclipse developers, i hope Apple fixes this, because there are THOUSANDS of old eclipse apps that cannot be upgraded to the more recent SWT VERSIONS (when eclipse fix them, anyway...)

If you guys find a workaround for this that does not involve updating Eclipse SWT plugins, please post it!

**Comment by Chrisfufu** [comment]
ok. I see. thanks for letting me know.

**Comment by lechie** [comment]
I have the same question in macOS big sur, even if this OS version has been already released.
My table rows does not displayed until mouse moveover and click one row or select all.

**Comment by Chrisfufu** [comment]
> I have the same question in macOS big sur, even if this OS version has been already released.
> My table rows does not displayed until mouse moveover and click one row or select all.

yeah. wait for the fix now.

**Comment by kseniiaguzeeva** [comment]
Possibly it will be fixed when updating Eclipse (DBeaver release 7.3.1).

**Comment by akilovich** [comment]
Fixed the issue with invisible rows. All other UI bugs related to SWT will be fixed in one of our future releases when we upgrade our Eclipse version.

**Comment by akilovich** [comment]
Hi @marcolopes. At least in this situation, [the workaround](https://github.com/dbeaver/dbeaver/commit/38960edb58c9fdcf4669c11555b796778badc7db#diff-8dad9caaacf0ce9c8f306b3ee732b288e749b534f1c5b2f1ee5d8ec5b8979a5a) turns out to be quite simple.

**Comment by Chrisfufu** [comment]
thanks.

**Comment by kseniiaguzeeva** [comment]
Could you please test the fix on EA version https://dbeaver.io/files/ea/?

**Comment by marcolopes** [comment]
> Hi @marcolopes. At least in this situation, [the workaround](https://github.com/dbeaver/dbeaver/commit/38960edb58c9fdcf4669c11555b796778badc7db#diff-8dad9caaacf0ce9c8f306b3ee732b288e749b534f1c5b2f1ee5d8ec5b8979a5a) turns out to be quite simple.

Thanks! I got to that conclusion also... i had problems with the SWT TABLES, and a forced REDRAW resolves the issue!

Algo had other problems, and i had to "patch" the SWT LIB (Display class) to avoid a core runtime error (this was fixed on more recent versions of SWT that i can't use right now)

**Comment by Chrisfufu** [comment]
> Could you please test the fix on EA version https://dbeaver.io/files/ea/?

I've downgraded my system to catalina. maybe @lechie can help. thanks

**Comment by kseniiaguzeeva** [comment]
The fix was made and will be included to the next releaseю Please try early access https://dbeaver.io/files/ea/

**Comment by kseniiaguzeeva** [comment]
Fixed in 7.3.0. Could you please try EA https://dbeaver.io/files/ea/?

**Comment by dyorgio** [comment]
Hello @kseniiaguzeeva I'm using 7.3.0 but have same problem in "Execution Plan" Result table.
Only when I clicked it renders result.
Editor before 7.3.0 also have a lot of rendering issues, but 7.3.0 solves.

**Comment by kseniiaguzeeva** [comment]
Please tell your OS and send the screenshot

**Comment by dyorgio** [comment]
Sorry @kseniiaguzeeva, it is the same: macOS Big Sur 11.0.1 (20B29).

Before click:
<img width="481" alt="Captura de Tela 2020-12-08 às 11 29 59" src="https://user-images.githubusercontent.com/1438251/101496749-e659b780-3948-11eb-8070-563dc9b8f0f5.png">

After click:
<img width="345" alt="Captura de Tela 2020-12-08 às 11 30 04" src="https://user-images.githubusercontent.com/1438251/101496777-f07bb600-3948-11eb-8f73-d22887f3f648.png">

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. It is fixed in 7.3.1 EA version. You can try it https://dbeaver.io/files/ea/

**Comment by Chrisfufu** [comment]
> Thank you for the report. It is fixed in 7.3.1 EA version. You can try it https://dbeaver.io/files/ea/

thanks.
