### ISSUE TITLE
Option to change date format when importing CSV

### ISSUE THREAD

**Issue by guardiande** [dbeaver/dbeaver#10160]
#### IMPORTANT

Clone of #8669 due to not resolved in 7.2.3 as expected.

#### System information: 
- MacOS 10.15.4
- DBeaver 7.2.3

#### Connection specification:
- Database SQLite
- Driver SQLite
#### Describe the problem you're observing:

Importing CSV does not respect the date format specified in the import dialog.

**dates.csv**

```
format,value
yyyy-MM-dd,2025-12-31
dd.MM.yyyy,31.12.2025
```

**Import settings (note the German date format)**

<img width="391" alt="image" src="https://user-images.githubusercontent.com/4947715/81578570-471d1380-93ab-11ea-9666-0030aa9ee815.png">

**Check whether a valid date was imported**

```
SELECT format, value, JULIANDAY(value)
FROM dates;
```

**Output**

<img width="392" alt="image" src="https://user-images.githubusercontent.com/4947715/81579037-ec37ec00-93ab-11ea-8169-4c3cbc1c921d.png">

#### Steps to reproduce, if exist:

1. Create CSV file as shown above.
1. Create a new SQLite database.
1. Create a table
   ```
   CREATE TABLE dates (
	format TEXT,
	value DATE
    );
1. Refresh the database in the connection view so that the table appears.
1. Right click the table and select "Import data"
1. Select CSV, select the created csv table, set the date format to `dd.MM.yyyy'
1. Start the import.
1. Check the results (see above).

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by publicvirtualvoid** [comment]
I'm also experiencing this going from CSV to PG.
Source date format is `dd/MM/YY` but it appears to attempt to parse `MM/dd/YYYY` regardless of input.

**Comment by kseniiaguzeeva** [comment]
After additional clarification, the information is as follows: 
Date/time format line in Import settings shows date format from server side (you can see it in tooltip). 
![9LdeJAfEJk](https://user-images.githubusercontent.com/51405061/97165885-6f4fd180-1795-11eb-8a09-ac5d3e258395.png)

So, this option is not implemented yet and I will change the ticket on Feature request

**Comment by publicvirtualvoid** [comment]
@kseniiaguzeeva I don't follow. My understanding is that that field is used to define the date format used in the CSV file. This is necessary so that date strings in the CSV can be parsed to date objects in the SQL schema.
Is that not the case?

Could you explain what this field does instead?

**Comment by kseniiaguzeeva** [comment]
My apologies. Your understanding is correct. But please note that Date type is String type in SQLIte. The same issue is a bug for PostgreSQL.

**Comment by kseniiaguzeeva** [comment]
Can be reproduced for types date, time (timestamp works correctly). Please try to:

1. import to Postgres 12 Xeniia.dates CSV file with another date view (e.g. change on dd-MM-yyyy (or HH:mm:ss))
2. Set in Date/time format Importer setting date view according CSV file (e.g. change on dd-MM-yyyy (or HH:mm:ss))
3. Start import

Expected: the date view is parsed and imported successfully
Actual result: The import fails, error appears

**Comment by kseniiaguzeeva** [comment]
Verified. @publicvirtualvoid You can try EA version https://dbeaver.io/

**Comment by rachmadhartono8** [comment]
I have An Issue, if i import at DB ever format CSV, that make my date of file change from 2022-09-30 to 2022-09-29, how must i do to solve this case/problem ? please, thank you
