### ISSUE TITLE
Wrong autocomplete for 2nd row and INSERT INTO generated expression for PostgreSQL serial type

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10168]
#### System information:  
- DBeaver version 7.2.4 EA

#### Connection specification:
- Database name and version PostgreSQL 

#### Describe the problem you're observing:
1. An incorrect autocomplete of the serial cell in the second row in the table with two or more columns (autocomplete for the third and subsequent columns works correctly)
Precondition: a table with column of serial type and several others exists and only one row
**Steps**:
Duplicate the row and press Save
**Expected:** the next number in the sequence is inserted into the serial column
**Actual result**: a random number is inserted
![97098279-3f68d700-168c-11eb-9bbc-a8a1ad1fdcc8](https://user-images.githubusercontent.com/51405061/97160681-c2be2180-178d-11eb-8c97-5a7678a77501.gif)

2. Wrong SQL expression is generated via Data Editor context menu. 
**Steps**:
Select Generate SQL>Insert into
**Expected**:
```sql
INSERT INTO "Xeniia"."serial" (column1)
	VALUES ('q');
```
**Actual result**:
```sql
INSERT INTO "serial"
("serial", column1)
VALUES(NULL, 'q');
```

**Comment by LonwoLonwo** [comment]
Can't reproduce p.1
INSERT INTO statement in Query Manager correct and contains other columns values, not serial. 
And the value that appears in the serial cell after saving comes from the database. It may be incorrect if another person also works in the same table, for example.

**Comment by LonwoLonwo** [comment]
About 1 - This behaviour is normal for auto-generating columns.
new ticket for 2 - https://github.com/dbeaver/dbeaver/issues/10489
