### ISSUE TITLE
Parameter domain name lost in procedure source - Firebird

### ISSUE THREAD

**Issue by tarbul** [dbeaver/dbeaver#10164]
#### System information: 
- Operating system (distribution) and version Win7
- DBeaver version 7.2.3
- Additional extensions /

#### Connection specification:
- Database name and version Firebird 3.0.5
- Driver name Jaybird JCA/JDBC driver 4.0.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

Dbeaver replaces procedure parameters that are domains with their types in procedure's source code.

#### Steps to reproduce, if exist:

If I create a domain

`CREATE DOMAIN TMP_MOEDA NUMERIC(15,2)`

and a procedure is using it

```
CREATE OR ALTER PROCEDURE test_moeda (P_STOLPEC TMP_MOEDA)
RETURNS (
   P_ID INTEGER
)
AS
begin
  p_id = 123;
  suspend;
end
```

and I open this procedure in dbeaver the Source I get is somehow wrong

```
CREATE OR ALTER PROCEDURE TEST_MOEDA (P_STOLPEC NUMERIC(15,2))
RETURNS (
	P_ID INTEGER
)
AS
begin
  p_id = 123;
  suspend;
end
```

If open the same procedure in flamerobin, domain parameters are preserved
in procedure view

![slika](https://user-images.githubusercontent.com/58310674/97115482-45e06880-16f7-11eb-8f94-63de9380f192.png)

and in source view

![slika](https://user-images.githubusercontent.com/58310674/97115542-8344f600-16f7-11eb-8eda-796ca8308996.png)

**Comment by tarbul** [comment]
Hi @akilovich,

if you have to use Firebird's data dictionary then you should probably get procedure parameters data from RDB$PROCEDURE_PARAMETERS as mentioned in #5532

See https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref25/firebird-25-language-reference.html

Something like 

```
SELECT RPP.RDB$PARAMETER_NAME,RPP.RDB$FIELD_SOURCE -- domain
FROM RDB$PROCEDURE_PARAMETERS RPP
WHERE RDB$PROCEDURE_NAME = 'TEST_MOEDA'
```

It returns

```
P_STOLPEC   TMP_MOEDA
P_ID        RDB$162
```

RDB$FIELD_SOURCE is

> The name of the user-created domain, when a domain is referenced instead of a data type. If the name starts with the prefix 'RDB$', it is the name of the domain automatically generated by the system for the parameter.

Parameter types are further defined in RDB$FIELDS

> RDB$FIELDS stores definitions of columns and domains, both system and custom. This is where the detailed data attributes are stored for all columns.

```
SELECT * 
FROM RDB$FIELDS 
WHERE RDB$FIELD_NAME IN ('TMP_MOEDA', 'RDB$162')
```

**Comment by akilovich** [comment]
Fixed.

**Comment by uslss** [comment]
verified

**Comment by tarbul** [comment]
Works like a charm. Thanks!
