### ISSUE TITLE
Critical error with add text data with ENTER

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#10172]
WINDOWS 10
DBeaver 7.2.3
Postgresql 9.6, Postgresql 12

#1 Case:
1.CREATE TABLE gty_test.newtable_11 (
	id int4 NOT NULL,
	id_group text NOT NULL,
	CONSTRAINT newtable_11_pk PRIMARY KEY (id, id_group)
);

2. add new row "sssssss"
![изображение](https://user-images.githubusercontent.com/61137576/97174253-a59c4980-17b3-11eb-9d77-211b4e6204c8.png)
3. Ok. Row saved
4. add new row with ENTER after s symbol
"sssssss
dddd"

try to copy(Ctrl+c) this string to newtable_11.id_group column

past(Ctrl+v) 
![изображение](https://user-images.githubusercontent.com/61137576/97175082-c2854c80-17b4-11eb-9973-20296b96624e.png)

Where is part dddd before ENTER?? Symbol after ENTER is not pasted.

#2 Case2:
1.CREATE TABLE gty_test.newtable_11 (
	id int4 NOT NULL,
	id_group text NOT NULL,
	CONSTRAINT newtable_11_pk PRIMARY KEY (id, id_group)
);
2. added new row with ENTER from pgAdmin4 interface without problem
"sssssss
dddd"
![изображение](https://user-images.githubusercontent.com/61137576/97175458-5d7e2680-17b5-11eb-9ab8-da805bd520f9.png)

3. Go to Debeaver
And try to update newtable_11.id_group to string "v"
![изображение](https://user-images.githubusercontent.com/61137576/97175652-a930d000-17b5-11eb-8219-210ce29017f8.png)

![изображение](https://user-images.githubusercontent.com/61137576/97175752-cb2a5280-17b5-11eb-9855-f603d22a5185.png)

After that DBeaver is crashed

1.CREATE TABLE gty_test.newtable_33 (
	id int4 NOT NULL,
	id_group text NOT NULL,
	CONSTRAINT newtable_33_pk PRIMARY KEY (id, id_group)
);

2. Try to add any data to new table with error 

Object parameter [ttt] binding not supported
Object parameter [3333] binding not supported
Object parameter [ggggg] binding not supported

**Comment by detkliff** [comment]
version 7.1.4 without problem CASE2

**Comment by uslss** [comment]
@detkliff could you check if issue is reproducible for you against EA version? https://dbeaver.io/files/ea/
Thanks in advance

**Comment by detkliff** [comment]
> 
> 
> @detkliff could you check if issue is reproducible for you against EA version? https://dbeaver.io/files/ea/
> Thanks in advance

I can't check this file version because the download speed is 14kb\s from this repository

**Comment by hiperjp** [comment]
I'm having same behaviour in Versión 7.2.3.202010191702

![Captura de Pantalla 2020-10-28 a la(s) 13 04 24](https://user-images.githubusercontent.com/683139/97463387-76eeb200-191e-11eb-88ba-a95fe4733aac.png)

**Comment by detkliff** [comment]
> 
> 
> I'm having same behaviour in Versión 7.2.3.202010191702
> 
> ![Captura de Pantalla 2020-10-28 a la(s) 13 04 24](https://user-images.githubusercontent.com/683139/97463387-76eeb200-191e-11eb-88ba-a95fe4733aac.png)
I had not this error in 7.2.4 version. Updated today

**Comment by detkliff** [comment]
version 7.2.4 had #1 error. DBeaver cat my copyed  string.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. Case 1 is actual for different databases. 
_It can be reproduced in postgres.Xeniia.newtable_11 (try to enter  a value
"sssssss
dddd" 
(with Enter symbol between sssssss and dddd))_

**Comment by hiperjp** [comment]
I confirm that v7.3.4 is working for my use case.

**Comment by LonwoLonwo** [comment]
Can't reproduce on DBeaver 7.2.3 and 7.2.4, Windows 7 and 10, PostgreSQL 10 and 12. 
![2020-11-05 10_44_56-DBeaver Enterprise 7 3 0 - upsert_test](https://user-images.githubusercontent.com/45152336/98212258-5e048300-1f54-11eb-81d4-10265fc9b9c7.png)
@detkliff any [error logs](https://github.com/dbeaver/dbeaver/wiki/Log-files), perhaps?

**Comment by detkliff** [comment]
> 
> 
> Can't reproduce on DBeaver 7.2.3 and 7.2.4, Windows 7 and 10, PostgreSQL 10 and 12.
> ![2020-11-05 10_44_56-DBeaver Enterprise 7 3 0 - upsert_test](https://user-images.githubusercontent.com/45152336/98212258-5e048300-1f54-11eb-81d4-10265fc9b9c7.png)
> @detkliff any [error logs](https://github.com/dbeaver/dbeaver/wiki/Log-files), perhaps?

no Error in this case.


Version 7.2.5

1. In Dbeaver SQL Editor
CREATE TABLE test.nt (
key int4,
val text,
is_active bool
)
2. Open data tab of table test.nt

  a) I try to enter string 
     "sssssss
     dddd"
      from interface  sssssss 
     
![изображение](https://user-images.githubusercontent.com/61137576/98215086-281dc980-1f69-11eb-8324-5e705fcbbb4d.png)
end press ENTER.  Dbeaver saved "sssssss" only.

  b) I try to copy\paste 
     string 
     "sssssss
     dddd" from Dbeaver SQL Editor or any text editor
![изображение](https://user-images.githubusercontent.com/61137576/98215431-96fb2280-1f69-11eb-90f4-22996ad73dc4.png)

![изображение](https://user-images.githubusercontent.com/61137576/98215626-d88bcd80-1f69-11eb-992b-47341d463cb4.png)
![изображение](https://user-images.githubusercontent.com/61137576/98215987-4afcad80-1f6a-11eb-868a-b73d8311ae8e.png)


press CTRL+C or press right button and press Copy

Open data tab of table test.nt
Press right button on a cell and press Paste
![изображение](https://user-images.githubusercontent.com/61137576/98216068-65368b80-1f6a-11eb-87ad-e57daf36355a.png)

Dbeaver cut off string after "sssssss".


Example from pgAdmin4
![изображение](https://user-images.githubusercontent.com/61137576/98217091-cdd23800-1f6b-11eb-899b-645ace507c80.png)

press CTRL+C


![изображение](https://user-images.githubusercontent.com/61137576/98217064-c27f0c80-1f6b-11eb-8408-e074af401b8b.png)
press CTRL+V and Save

Open data tab of table test.nt in DBeaver
![изображение](https://user-images.githubusercontent.com/61137576/98217208-0114c700-1f6c-11eb-8ac6-f144e970698d.png)

Duble click on cell, copy text from cell and past before string
![изображение](https://user-images.githubusercontent.com/61137576/98217454-58b33280-1f6c-11eb-9c25-0f6ca55a13da.png)
Dbeaver cut off string after "sssssss" again.

**Comment by detkliff** [comment]
> 
> 
> Can't reproduce on DBeaver 7.2.3 and 7.2.4, Windows 7 and 10, PostgreSQL 10 and 12.
> ![2020-11-05 10_44_56-DBeaver Enterprise 7 3 0 - upsert_test](https://user-images.githubusercontent.com/45152336/98212258-5e048300-1f54-11eb-81d4-10265fc9b9c7.png)
> @detkliff any [error logs](https://github.com/dbeaver/dbeaver/wiki/Log-files), perhaps?

can you record a video of how could you enter your line into a cell with ENTER symbol?

**Comment by LonwoLonwo** [comment]
![2020-11-05_11h55_09](https://user-images.githubusercontent.com/45152336/98219264-d4f24980-1f5d-11eb-921c-c62521676b37.gif)
I don't use any special steps, unfortunately.
How about "Advanced paste" (ctrl + shift + v).  Doesn't work either? 

I can also suggest "Reset workspace", very, very rare, but it can helps

**Comment by detkliff** [comment]
> I don't use any special steps, unfortunately.

fantastic

**Comment by detkliff** [comment]
> 
> 
> ![2020-11-05_11h55_09](https://user-images.githubusercontent.com/45152336/98219264-d4f24980-1f5d-11eb-921c-c62521676b37.gif)
> I don't use any special steps, unfortunately.
> How about "Advanced paste" (ctrl + shift + v). Doesn't work either?
> 
> I can also suggest "Reset workspace", very, very rare, but it can helps

![pg](https://user-images.githubusercontent.com/61137576/98230672-3aa1fe00-1f7d-11eb-8b3f-c05d86be0650.gif)

**Comment by LonwoLonwo** [comment]
@detkliff i see, but so far I can not help in any way.
As a workaround paste data through value tab (в поле "Значение").

**Comment by detkliff** [comment]
> 
> 
> @detkliff i see, but so far I can not help in any way.
> As a workaround paste data through value tab (в поле "Значение").


Reset workspace - no effect =(

**Comment by detkliff** [comment]
> 
> 
> @detkliff i see, but so far I can not help in any way.
> As a workaround paste data through value tab (в поле "Значение").

what is your version of DBeaver?

**Comment by LonwoLonwo** [comment]
@detkliff 7.2.3, 7.2.4, 7.25 and 7.3 Enterprise edition. And two more testers looked without results.

**Comment by detkliff** [comment]
> 
> 
> @detkliff 7.2.3, 7.2.4, 7.25 and 7.3 Enterprise edition. And two more testers looked without results.

thank you very much, I understand what the problem is i am try to duble clicked on cell and past string. But if i click once on cell, this string pasted without problem

**Comment by LonwoLonwo** [comment]
@detkliff I'm glad the problem was solved, hurray)
