### ISSUE TITLE
Issue with Darktheme Revert | UI config is overwrited and unable to reset.

### ISSUE THREAD

**Issue by shankarThiyagaraajan** [dbeaver/dbeaver#10175]
#### System information: 
- Operating system (distribution) and version : Ubuntu 20.04
- DBeaver version : 7.2.3
- Additional extensions : Dark Theme

#### Connection specification:
- Database name and version: Postgres
- Driver name : PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No,

#### My Issue:
After switching to a dark theme, I just want back to normal, So I uninstalled the theme and restarted the app.
But still, i can see some of its footprints in my app and its affecting a lot. It completely destroyed my environment.
I cant see text in black background and black text color. I tried to change in apperance too, But not working.
I did "Reset UI Settings", "Reset Workspace State" but not working too. 
I tried to remove all files that are related to dbeaver and did fresh installation many times, But no luck.
Kindly let me know the way to clear all configurations and do fresh installation.

#### Steps to reproduce, if exist:
1. Install dark theme
2. Restart app
3. Uninstall theme
4. Restart

#### Include any warning/errors/backtraces from the logs

![Screenshot from 2020-10-26 20-34-32](https://user-images.githubusercontent.com/10199091/97189893-1a2eb280-17cb-11eb-9ffa-092ed74b5bf2.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. Please try Reset UI settings (via File in main menu or according this instruction https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
