### ISSUE TITLE
'Execute SQL script' runs statements in parallel if more than 2 results are present in Results panel

### ISSUE THREAD

**Issue by codrut20** [dbeaver/dbeaver#10177]
#### System information: 
- Operating system (distribution) and version : MacOS Catalina 10.15.7
- DBeaver version : 7.2.3
- Additional extensions

#### Connection specification:
- Database name and version DB2 9.5
- Driver name DB2 LUW
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Problem appears when trying to run a script with multiple lines using the 'Execute SQL script' button. If there are no results for that script already it run ok, all the statements in order. If there are more than 2 results present it runs all the statements in the script in parallel.
#### Steps to reproduce, if exist:
- Open/Create script with multiple statements.
- Run 2 statements, generating 2 results in the result panel
- Click on 'Execute SQL script' button.
- All the statements will be ran in parallel

**Comment by kseniiaguzeeva** [comment]
I try to reproduce the issue according your steps.
1. Execute a script to receive several result tabs with following statements: drop the table, create the table, select * from the table and from another table.
2. Execute the script again. 

The execution is succesfull: the table is dropped, then created and a data is displayed from the tables.
What does go wrong in your case?

**Comment by ceugenio** [comment]
I have a similar problem since I update my version from 7.2.1 to 7.2.5. 

Steps to reproduce:
1. Execute script (+100 statament) - **Run OK**
2. Move to other sql files execute singular statement - **Run OK**
3. Execute the first step again  - - **Run ERROR - statements in parallel**

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce. Here is the test statement:
```
SELECT * FROM QTEST2;
TRUNCATE QTEST2 immediate;
```

**Comment by ceugenio** [comment]
> Cannot reproduce. Here is the test statement:
> 
> ```
> SELECT * FROM QTEST2;
> TRUNCATE QTEST2 immediate;
> ```

Try with:

SELECT * FROM QTEMP1;

TRUNCATE QTEMP1;


INSERT INTO QTEMP1 VALUES ('Key1');


TRUNCATE QTEMP2;

INSERT INTO QTEMP2 VALUES ('Key1');


Actually the same happen with 'Execute SQL Statements' as described in thi issue 
https://github.com/dbeaver/dbeaver/issues/10425

**Comment by kseniiaguzeeva** [comment]
Works as expected in my case. Please see. What we do differently?
![VDyACQRJjC](https://user-images.githubusercontent.com/51405061/100255405-82042480-2f54-11eb-8418-40e55dfb31db.gif)
and
![bPFW0UD6Va](https://user-images.githubusercontent.com/51405061/100255575-b546b380-2f54-11eb-8218-f61f019976c0.gif)

**Comment by codrut20** [comment]
![issue](https://user-images.githubusercontent.com/13568044/100259225-a6f69880-2f50-11eb-87fa-88b7d3d2eb17.gif)

**Comment by codrut20** [comment]
When I click on 'Execute SQL Script' The queries should run in order, but the start all at once.

**Comment by kseniiaguzeeva** [comment]
Please write a video

**Comment by kseniiaguzeeva** [comment]
Should be fix as part of https://github.com/dbeaver/dbeaver/issues/10280. You can test EA version https://dbeaver.io/files/ea/

**Comment by codrut20** [comment]
Fixed in version 7.3.1
