### ISSUE TITLE
Add different ER-diagram notations

### ISSUE THREAD

**Issue by GiantCrocodile** [dbeaver/dbeaver#1017]
I would like to see other ER-diagram notations as I'm not familiar with the currently used one. Current one seems to be IDEF1x. I think there should be 3 - 4 to choose from as an user, see https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model#/media/File:ERD_Representation.svg . Maybe Crow's foot, Min/Max ISO and Chen would cover most wishes. I can't say how much popular every of these have in different countries and regions but I think no choice is a bit less.

**Comment by serge-rider** [comment]
Totally agree, although I can't say when I'll have time for that. 
Different notations rendering is a time consuming task.

**Comment by DDeathlonger** [comment]
I'm looking online, have you been able to do this yet?

**Comment by dawoodjee** [comment]
Is there a reference for the currently used ERD symbols?

**Comment by dawoodjee** [comment]
https://github.com/dbeaver/dbeaver/issues/1017#issue-192645947

@GiantCrocodile already stated this. Thanks!

**Comment by KrisPetkov** [comment]
Hello guys,
Is there any estimation for this option? This option will be really helpful indeed.
IDEF1X seems not so intuitive to me and any other alternative will be much easier to use.

**Comment by sschneider-ihre-pvs** [comment]
Just to revive this again, I stumbled on the ERD notation also a few times now.

**Comment by gytisrepecka** [comment]
> Totally agree, although I can't say when I'll have time for that. Different notations rendering is a time consuming task.

Perhaps you could give some pointers of what should be done to implement additional notations? That is obviously more than just replacing graphics for each type of cardinality - ideally we should be able to define a custom notation as plugin/extension.

I would be very interested helping out with adding Crow's Foot notation. Because that is something even JetBrains' [DataGrip doesn't have](https://youtrack.jetbrains.com/issue/DBE-5400/Support-relationship-type-in-diagrams).

**Comment by aryankarim** [comment]
Would love to see Crow's Foot notation on DBeaver. Would also love to help if anyone started working on this feature.

**Comment by federico-piazza** [comment]
In which version will this be available?

**Comment by arhayka** [comment]
@federico-piazza This feature will be available in the next release, 23.2.2

**Comment by Vernadskii** [comment]
People who have the same problem can find the way to change the notation on this link https://dbeaver.com/docs/dbeaver/ER-Diagrams/#setting-notation-and-routing-type

**Comment by loonaticx** [comment]
Can we consider implementing other ER diagram notations, including Chen, UML, and Min-Max?
