### ISSUE TITLE
[Derby] duplicate constraint objects

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#10181]
DBeaver 7.2.3

Driver: Apache Derby Embedded JDBC Driver 10.15.2.0 - (1873585)
 
List of table constraints contains duplicate constraint objects.
In the case of composite keys/constraints.

![2020-10-27 15_29_54-DBeaver Enterprise 7 3 0 - FLIGHTAVAILABILITY](https://user-images.githubusercontent.com/45152336/97301846-4d278380-1869-11eb-933c-889c282a286e.png)

**Comment by kseniiaguzeeva** [comment]
The composite constraints are not duplicated any more, but the columns included in the constraints are not displayed.
![KoshxLnArU](https://user-images.githubusercontent.com/51405061/97539254-b37be580-19d2-11eb-831d-a10adfeea27d.gif)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/5456785/dbeaver-debug.log)

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/issues/10206
