### ISSUE TITLE
macOS and navigator left-click / double-click behavior

### ISSUE THREAD

**Issue by neurogenesis** [dbeaver/dbeaver#10185]
#### System information: 
- Operating system (distribution) and version
macOS v10.15.6

- DBeaver version
7.2.2, 7.2.3

- Additional extensions
mysql

#### Connection specification:
- Database name and version
mysql 5.6

- Driver name
couldn't find this in preferences. it's just the default mysql driver.

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
ssh tunneling

#### Describe the problem you're observing:

There appears to be a problem with the UI, particularly noticeable with the navigation pane. It seems the left-click behavior changed so that there is no timer for double-click (almost like the mouse-up event didn't register correctly). This is to say that left-clicking on an item in the navigator, then subsequently left-clicking on a different item in the navigator, will effectively result in a double-click of the most recent element you left-clicked on.

The expected behavior is that left-clicking on a navigator element will simply select it in the navigator pane. Subsequent left-clicks that are seconds apart (but not a double-click), should select the element below the cursor and not act as a double-click on the most recently clicked navigator element.

This started with 7.2.2 and persisted through 7.2.3. Reverting to 7.2.1 fixes this behavior.

#### Steps to reproduce, if exist:

To reproduce you should at least have a few connections in the navigator. Left-click any of them, then - after a few seconds - click on a different one in the list.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. Please try to disable **Show action icons** in the the database context menu.
![dbeaver_JKMh5AkO5L](https://user-images.githubusercontent.com/51405061/98460730-e171de80-21b7-11eb-8c1f-51a6d9bcfa72.png)

If it doesn't help, please send more details about your system.

**Comment by uslss** [comment]
there are no updates on the issue for a long time.
If it is still actual for you - feel free to reopen the ticket with an additional info

**Comment by neurogenesis** [comment]
This was fixed with a subsequent update a few months later. Is behaving correctly on current releases.
