### ISSUE TITLE
no way to write comments on VIEW AND MATERIALIZED VIEW  columns from ide interface

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#10186]
DBeaver 7.2.3
Postgresql all versions

![изображение](https://user-images.githubusercontent.com/61137576/97399002-0b9ce400-190e-11eb-9531-a6e922158e34.png)

From sql editor with SQL command only 

COMMENT ON  VIEW v_tic IS 'История';
COMMENT ON COLUMN v_t.id IS 'идентификатор';

**Comment by kseniiaguzeeva** [comment]
Are you sure that you cannot add comment for a view too?
![WvOMZx6WaD](https://user-images.githubusercontent.com/51405061/97403315-40586d80-1905-11eb-903b-37a091cea6e1.gif)

I can reproduce with a view column only.

**Comment by detkliff** [comment]
> 
> 
> Are you sure that you cannot add comment for a view too?
> ![WvOMZx6WaD](https://user-images.githubusercontent.com/51405061/97403315-40586d80-1905-11eb-903b-37a091cea6e1.gif)
> 
> I can reproduce with a view column only.

Sorry. You are right. Problem for columns comment only

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
We have this ticket already https://github.com/dbeaver/dbeaver/issues/9921

**Comment by detkliff** [comment]
7.3.0 no ability to create comment on materialized view from interface

**Comment by LonwoLonwo** [comment]
@detkliff You can monitor the status of this issue in this ticket: https://github.com/dbeaver/dbeaver/issues/9921
