### ISSUE TITLE
MacOS: Results Grid View - Smooth (Pixel-by-Pixel) Scrolling?

### ISSUE THREAD

**Issue by ooobii** [dbeaver/dbeaver#10184]
Hello! Wonderful project, thank you in advance for all of the great work that's been put in to make DBeaver so awesome!

As a MacBook Pro user, scrolling through the results grid with the trackpad accurately is EXTREMELY difficult to do. Frequently do I find myself 20 columns to the right/left of where my scroll position originally began (when only wanting to scroll vertically), and my trackpad sensitivities are not set above default levels for the MacOS operating system. Microscopic gestures in the wrong direction of your desired scroll will send you *wildly* off track in large data sets.

If the option to disable scroll stops on column and row endings existed, it would be much easier to control my scrolling.

**Describe the solution you'd like**
I think it would be a great idea to have the option to enable pixel-by-pixel (precise) scrolling in the results grid view to both the vertical (row) and horizontal (column) axis. This feature should have the ability to be toggled on/off, since use cases exist for scroll stops being locked to row & column endings.

**Describe alternatives you've considered**
There are not any alternatives to this issue, as the ability to control scroll behavior exists only within DBeaver's backend.

**Additional context**
Trackpads that support advanced gestures are extremely handy, and as time goes on they are becoming more and more precise with the input they provide to the operating system. Utilizing these features would go a long way to the user experience within DBeaver.

If i'm alone in feeling this way, or a solution already exists that I missed in my original research before posting this, please let me know and I'll do my best with your advice :smile:

Thanks again!

**Comment by ooobii** [comment]
This option did not perform as expected:

**Comment by ooobii** [comment]
Related to bug report #6536 that confirmed newer versions of DBeaver on MacOS do not take advantage of the "Database Editors" > "Data Editor" > "Appearance" > "Grid" > "Smooth Scrolling" property.

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea. Smooth scrolling works when you move table view by scroll bar now.

**Comment by kseniiaguzeeva** [comment]
Шmproved smooth scrolling will be implemented in future releases

**Comment by jamesdh** [comment]
I'm using v7.3.0 and this is a brutally frustrating bug. The best way to describe it is "janky". It makes it incredibly difficult to maintain perspective as to what you're actually looking at.

**Comment by serge-rider** [comment]
@jamesdh please see answers in #7777 for hints how to make UI more responsive on MacOS.
In fact performance very depends on your MacOS and on UI settings.

**Comment by ooobii** [comment]
> Thank you for the idea. Smooth scrolling works when you move table view by scroll bar now.

@kseniiaguzeeva I know it was SO long ago, but I did confirm that this worked in that version, as well as the version currently released for MacOS. Smooth scrolling works when using the scrollbar manually, but is still not applied when scrolling is initiated with a trackpad gesture.

Looking forward to the feature in the new milestone.

**Comment by ooobii** [comment]
> @jamesdh please see answers in #7777 for hints how to make UI more responsive on MacOS.
> In fact performance very depends on your MacOS and on UI settings.

@tati-kru: @jamesdh 's complaints are not due to a slow UI; they are due to how DBeaver handles scrolling from trackpad gestures within the results grid on MacOS. Scrolling in one direction alone without wildly losing your place is near impossible - as this issue describes.

**Comment by tati-kru** [comment]
@ooobii thank you for details, it's really helpful. We'll try to improve it after 8.0.

**Comment by patrickkidd** [comment]
+1 For this issue. It is very difficult to use the data view without smooth scrolling with the trackpad. Thank you!

**Comment by ghost** [comment]
This is a major usability issue, as viewing result data is one of the main use cases.

**Comment by patrickkidd** [comment]
I am pinging back here again that this is indeed a major usability issue. Smooth scrolling is often not possible AT ALL on macOS because system scrollbars appear on scroll and then disappear and are very small. Even if you get the mouse over them fast enough they are very small and disappear very quickly so it is hard to grab them at all. You have to scroll with the trackpad to make them appear in order to grab one of them with the mouse so that you can smooth scroll and have accurate eyeball tracking in the results.

**Comment by antru** [comment]
> system scrollbars appear on scroll and then disappear

I recall Mac has a setting which enables the scrollbars to be shown at all times. Might help a little!

**Comment by patrickkidd** [comment]
> > system scrollbars appear on scroll and then disappear
> 
> I recall Mac has a setting which enables the scrollbars to be shown at all times. Might help a little!

That's correct, it could. Though it would disrupt desired behavior for all the other apps on the machine as well.

**Comment by tati-kru** [comment]
Hey all, just would like to let you know that we haven't forgotten about this issue. But it's quite complicated to fix. 
Couple recommendations to improve grid performance on Mac:
- Set monospaced font for data grid: Window -> Preferences -> User Interface -> Appearance -> Colors and Fonts -> Database Query results -> Resultset Data types -> Results grid font.
- Remove right-justify: Window -> Preferences -> Editors -> Data Editor -> Appearance -> Uncheck Right-justify numbers and Right-justify date/time values.

**Comment by EthanZeigler** [comment]
I'd like to add: This is an issue on windows as well. Exact same conditions. Scroll via trackpad only jumps by column. The scrollbar is smooth as expected.

**Comment by ooobii** [comment]
> > system scrollbars appear on scroll and then disappear
> 
> I recall Mac has a setting which enables the scrollbars to be shown at all times. Might help a little!

Great suggestion - this is the work around I will be using until trackpad horizontal scrolling is (possibly) improved. On Mac, DBeaver always shows scroll bars since the Eclipse UI always shows them. Not sure if I'm just a noob, but I don't remember setting that and I see them so long as scrollable data is there.

@tati-kru : I would like to note that using the horizontal scrollbar mimics the desired behavior with the trackpad horizontal scrolling. I know this probably doesn't present a programatic solution to the problem, but it will certainly help visualize the desired behavior for whoever ends up working on this 😄

**Comment by ooobii** [comment]
This was a part of the milestone 21.0.1, but it was never achieved / issue never closed.

Not trying to sound impatient... Any updates on this @tati-kru?

**Comment by tati-kru** [comment]
We are waiting for some improvements from the Eclipse platform. As far as I know, there are some movements of this ticket on the Eclipse board. As soon as we get the update we will add this to DBeaver.

**Comment by armant** [comment]
Just want to add that I am also waiting for this fix.

**Comment by skkevinperson** [comment]
+1, this should be embarrassing

**Comment by alwonder** [comment]
Joining this conversation. The scroll is very frustrating now. We really want it to be fixed.

Thanks for your work btw.

**Comment by ooobii** [comment]
Coming back to confirm that this issue has been fixed, and it's a genuine pleasure to use DBeaver to scroll through large data sets!!

Thank you to everyone involved - from the community providing work arounds to developers (both the Eclipse platform & from DBeaver contributors) who implemented the fix! 👍🏼 😄
