### ISSUE TITLE
Copy As TXT includes extraneous string padding

### ISSUE THREAD

**Issue by angusholder** [dbeaver/dbeaver#10189]
#### System information: 
- Windows 10
- DBeaver 7.2.3.202010191702

#### Connection specification:
- MariaDB 10.5.5
- MariaDB Connector/J 2.4.3
- Connected over SSH

#### Describe the problem you're observing:

Copying a small resultset like this:

![image](https://user-images.githubusercontent.com/7407345/97424567-cd50f600-1908-11eb-95fb-d726f024d936.png)

Results in a table with unnecessary padding in some columns like here under `name`:

    |country_code|name                                                                            |iso3|numcode|phonecode|
    |------------|--------------------------------------------------------------------------------|----|-------|---------|
    |AQ          |Antarctica                                                                      |    |       |0        |
    |AR          |Argentina                                                                       |ARG |32     |54       |
    |AS          |American Samoa                                                                  |ASM |16     |1684     |
    |AT          |Austria                                                                         |AUT |40     |43       |
    |AU          |Australia                                                                       |AUS |36     |61       |
    |AW          |Aruba                                                                           |ABW |533    |297      |
    |AZ          |Azerbaijan                                                                      |AZE |31     |994      |

I often use this feature to copy a small result set into a Telegram chat, so to make it readable I have to manually strip the padding by first pasting into Sublime Text.

#### Steps to reproduce, if exist:

Open this resultset in DBeaver

    WITH countries(country_code, name, iso3, numcode, phonecode) AS (
        VALUES
        ('AQ','Antarctica',NULL,NULL,'0'),
        ('AR','Argentina','ARG',32,'54'),
        ('AS','American Samoa','ASM',16,'1684'),
        ('AT','Austria','AUT',40,'43'),
        ('AU','Australia','AUS',36,'61'),
        ('AW','Aruba','ABW',533,'297'),
        ('AZ','Azerbaijan','AZE',31,'994')
    )
    SELECT * FROM countries

Select it, right-click, and press `Advanced Copy` -> `Copy As TXT`

The name column will have too much padding.

**Comment by uslss** [comment]
thanks for the report

**Comment by flambchap** [comment]
It's even worse on macOS.
![Screenshot 2021-01-11 at 17 23 23](https://user-images.githubusercontent.com/26031301/104193962-c169d000-5431-11eb-9031-702d83ed76cb.png)

**Comment by uslss** [comment]
verified

**Comment by angusholder** [comment]
Thanks for working on this!
