### ISSUE TITLE
Scheduler: Last Run and Last Result are not updated for cron

### ISSUE THREAD

**Issue by akilovich** [dbeaver/dbeaver#10188]
![2](https://user-images.githubusercontent.com/26031301/97423905-072df680-1921-11eb-9dfc-dcaf66a981ae.png)

**Comment by ShadelessFox** [comment]
I don't like the look of the <kbd>Next Run</kbd> column. Can we humanize it?

**Comment by flambchap** [comment]
@ShadelessFox 
![obama-yes-we-can](https://user-images.githubusercontent.com/26031301/118096849-950f9180-b3da-11eb-9487-15e1f1aa661b.jpg)

**Comment by ShadelessFox** [comment]
![image](https://user-images.githubusercontent.com/35821147/118097092-e0c23b00-b3da-11eb-81c2-e7bfa804bf8c.png)

**Comment by flambchap** [comment]
The issue is not specific for cron.

**Comment by Matvey16** [comment]
Verified
