### ISSUE TITLE
no way to insert or update data with array type from interface

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#10190]
Dbeaver 7.2.3
Postgresql 9-12 version

Case:
1.CREATE TABLE gty_test.ne333 (
	id int4 NULL,
	oc _int4 NULL
);

2. try to add or update array type column. Duble click on cell - no effect
![изображение](https://user-images.githubusercontent.com/61137576/97429611-7a436700-1939-11eb-9d09-4da18192e50a.png)

**Comment by uslss** [comment]
seems it is related to #9964 
could you check if it is reproducible for you against EA version? https://dbeaver.io/files/ea/
Thanks in advance

**Comment by detkliff** [comment]
> 
> 
> seems it is related to #9964
> could you check if it is reproducible for you against EA version? https://dbeaver.io/files/ea/
> Thanks in advance

this error on version from https://dbeaver.io/files/ea/

**Comment by detkliff** [comment]
#9964 it is another error

**Comment by uslss** [comment]
fixed in 7.2.5
