### ISSUE TITLE
Can not import from csv to Oracle temporary table and use together with preexisting data

### ISSUE THREAD

**Issue by uldics** [dbeaver/dbeaver#10205]
#### System information: 
- Windows 10 and Debian 10.6 (x86-64)
- DBeaver version 7.2.1 and 7.2.3 respectively

#### Connection specification:
- Database name and version: Oracle 19c.

#### Describe your question:

What I need: import a table from csv file without saving to database disk, so either to global temporary table or to private temporary table (https://www.oracletutorial.com/oracle-basics/oracle-private-temporary-table/). Then do some selects, and joins. Export results. No rests left in the database.

I have one SQL editor tab open, connected. From it it is not possible to import data. So I have to either open the table by CTRL+LMB on a table name in one of my queries or open it in Database Navigator on the left side.
DBeaver seems to use a different session for import (from left pane by rightclicking on a table, or from separate table tab) than the connected editor tab. Thus I can't import, perform inmemory join, export, disconnect without having to save the external data to database schema, disk etc.

Could it be possible to use same session in imports or add another import from the existing session, or choose to do a new session or through existing?

**Comment by kseniiaguzeeva** [comment]
Please try to disable **Open new connection** option in Import wizard. The same connection will be used for  import in this case.
![dbeaver_Fin6hkZ5Gq](https://user-images.githubusercontent.com/51405061/97847711-176b1a80-1d01-11eb-8c05-60034e646a62.png)

**Comment by uldics** [comment]
Does not help. Still no records with `SELECT * FROM MYGLOBALTEMPOTABLE;` after import.

**Comment by p91paul** [comment]
isn't it enough to issue a commit to wipe a temporary table?

**Comment by uldics** [comment]
Not sure what you mean by "commit to wipe", I do not wish to wipe anything. Anyway, neither before nor after commit, both by button and command I can get the data from my temp table. Only way to get to see that data is when the temptable is opened in a new tab. But there it is alone, I need to do some joins from other, preexisting non temp tables in database. That seems to be impossible.

**Comment by p91paul** [comment]
I mean that usually global temporary tables are wiped as soon as you commit. Data transfer most certainly does a commit at the end.
