### ISSUE TITLE
[Exasol] Index editor will open if an index is created via UI

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10208]
#### System information: 
- Operating system (distribution) and version Mac Catalina
- DBeaver version 7.2.4 EA

#### Connection specification:
- Database name and version Exasol

#### Steps to reproduce, if exist:
1. Go to index tab of table editor
2. Press Create new index button
3. Make necessary settings and press Ok

Expected: the new index appears in the indexes list
Actual result: Index editor opened

**Comment by LonwoLonwo** [comment]
and unique checkbox removed from Create Index dialogue

**Comment by kseniiaguzeeva** [comment]
Index Editor doesn't appear anymore after an index creation via UI
