### ISSUE TITLE
[Exasol] Decimal type is created with wrong syntax via UI

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10207]
#### System information: 
- Operating system (distribution) and version Mac Catalina
- DBeaver version 7.2.4 EA

#### Connection specification:
- Database name and version Exasol

#### Steps to reproduce, if exist:
Create a new column of Decimal type via Object Editor

Expected: DECIMAL(18,0) appears
Actual result: DECIMAL(50,0) appears
![Screenshot 2020-10-30 at 12 49 04](https://user-images.githubusercontent.com/51405061/97690940-be0bad00-1aae-11eb-8a42-0abb4ad755ed.png)

**Comment by LonwoLonwo** [comment]
Fixed in 7.3.0.

**Comment by kseniiaguzeeva** [comment]
verified
