### ISSUE TITLE
可以把数据库链接信息加到导入导出里嘛

### ISSUE THREAD

**Issue by flycatzly** [dbeaver/dbeaver#10203]
提个小建议，可以把数据库链接信息加到导入导出里嘛，这样每次换电脑装这个软件的话，什么的链接信息直接导进去就好了

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. Is it possible to send a screenshot with a place where you want to see it?
Could you please write comments in English?

**Comment by uslss** [comment]
there is no update on the issue for a long time, the issue is closed.
