### ISSUE TITLE
Oracle Foreign Keys with ON DELETE SET NULL displayed as NO ACTION

### ISSUE THREAD

**Issue by yremels** [dbeaver/dbeaver#10210]
**System information:** 
- Windows 10
- DBeaver 7.2.3 Community

**Connection specification:**
- Oracle11g/Oracle12c
- Driver com.oracle.database.jdbc:ojdbc8  (version 12.2.0.1)

**Problem description:**
Foreign Keys with ON DELETE SET NULL option display "No Action" in "On delete" column. 
However the generated DDL shows the correct On Delete set null

**Comment by kseniiaguzeeva** [comment]
Still can be reproduced in   DBeaver	7.2.5.202011071911.
Steps:
1. Create a foreign key and set set null or cascase in ON DELETE option (via UI or SQL Editor)
2. Press Save

Expected: the created FK appears in the list with the selected ON DELETE option
Actual result: the value is changed to No Action in ON DELETE column after saving changed
![x0NcTQf84T](https://user-images.githubusercontent.com/51405061/98459909-5ccf9200-21b0-11eb-907e-3230996eae7d.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
