### ISSUE TITLE
the font is Garbled.

### ISSUE THREAD

**Issue by sunknut** [dbeaver/dbeaver#10213]
#### System information: 
- Win10 2004
- DBeaver 7.2.3

#### Describe your question:
No matter how I change the font and themes, the font in the dialog  is still garbled like this.
![image](https://user-images.githubusercontent.com/11781491/97770207-413f0880-1b6c-11eb-8238-8d1a3b4e4ced.png)

**Comment by kseniiaguzeeva** [comment]
Please try to switch the view to classic mode. 
![97770207-413f0880-1b6c-11eb-8238-8d1a3b4e4ced](https://user-images.githubusercontent.com/51405061/98460779-60ffad80-21b8-11eb-8464-98949cd0f0ef.png)

**Comment by sunknut** [comment]
> Please try to switch the view to classic mode.
> ![97770207-413f0880-1b6c-11eb-8238-8d1a3b4e4ced](https://user-images.githubusercontent.com/51405061/98460779-60ffad80-21b8-11eb-8464-98949cd0f0ef.png)

Thanks ,it works.
Another question,
![屏幕截图 2020-11-09 115552](https://user-images.githubusercontent.com/11781491/98498763-a7214380-2282-11eb-9fec-88eb8586b1fa.png)

**Comment by uslss** [comment]
close this issue as solved.
If you have any other questions - please create a new ticket.
