### ISSUE TITLE
Refresh is needed to see correct compact DDL for a view with comments

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10219]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.2.4

#### Connection specification:
- Database name and version Oracle

#### Describe the problem you're observing:
Refresh is needed to see the correct compact DDL for a view with comments when the **compact form** DDL was selected in the view editor before closing
#### Steps to reproduce, if exist:
1. Open a view (e.g. HR.EMP_DETAILS_VIEW)
2. Select **compact form** DDL in the bottom toolbar
3. Close the view
4. Open it again.
**Expected**: DDL without comments is displayed
**Actual result**: comments are displayed in compact DDL view
5. Select No storage information
6. Then select compact form again
7. Then select No storage information again
**Expected**: DDL with comments is displayed with  No storage information option
**Actual result**: comments are not displayed 
![FKVbt3GASy](https://user-images.githubusercontent.com/51405061/97845496-af670500-1cfd-11eb-9f99-eb36c475bdb9.gif)

**Comment by LonwoLonwo** [comment]
Fixed in 7.2.5

**Comment by kseniiaguzeeva** [comment]
Still can be reproduced the first part of the issue:
1. Open a view (e.g. HR.EMP_DETAILS_VIEW)
2. Select compact form DDL in the bottom toolbar
3. Close the view
4. Open it again.

Expected: DDL without comments is displayed
Actual result: comments are displayed in compact DDL view

Workaround: Refresh the view
DBeaver	7.2.4.202011021435

**Comment by LonwoLonwo** [comment]
> 
> 
> Still can be reproduced the first part of the issue:
> 
>     1. Open a view (e.g. HR.EMP_DETAILS_VIEW)
> 
>     2. Select compact form DDL in the bottom toolbar
> 
>     3. Close the view
> 
>     4. Open it again.
> 
> 
> Expected: DDL without comments is displayed
> Actual result: comments are displayed in compact DDL view
> 
> Workaround: Refresh the view
> DBeaver 7.2.4.202011021435

Fixed

**Comment by kseniiaguzeeva** [comment]
verified
