### ISSUE TITLE
Can not connect after 7.1.2 version

### ISSUE THREAD

**Issue by Bakrain** [dbeaver/dbeaver#10211]
#### System information: 
- Windows 10 pro 2004
- Any dbeaver version after 7.1.2

#### Connection specification:
- oracle 8i database that working inside sco unix 7.1.3 virtual machine.

#### Describe your question:
I like using dbeaver tool and used to use it to connect to a virtual machine unix server that run oracle 8i database,but after I update to any version after dbeaver 7.1.2, i can not navigate the tables of the schema and its data although I was working fine with dbeaver 7.1.2 and below.

when I try to navigate the tables there is the error:
SQL Error [933] [42000]: ORA-00933: SQL command not properly ended

  ORA-00933: SQL command not properly ended

  ORA-00933: SQL command not properly ended

Did I make anything wrong?

When i test the connection
connected (16 ms)
Server:Oracle Oracle8i Release 8.1.7.0.0 - Production
JServer Release 8.1.7.0.0 - Production
Driver:Oracle JDBC driver 10.2.0.5.0

**Comment by LonwoLonwo** [comment]
@Bakrain it's a knowing issue. We just fix it. Fix will be available in DBeaver version 7.2.4, release on next  Monday.

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/issues/9904
