### ISSUE TITLE
Result Grid font color

### ISSUE THREAD

**Issue by CannibalCorpse9** [dbeaver/dbeaver#10224]
#### System information: 
- Operating system Windows 10
- DBeaver version 7.2.4

Since upgrading to 7.2.4, the ability to change the font color of the results grid seems to have disappeared.

**Comment by kseniiaguzeeva** [comment]
**Colorize data types** works correctly for me.

**Comment by CannibalCorpse9** [comment]
> **Colorize data types** works correctly for me.

I tried that, but I have no control over the color

**Comment by kseniiaguzeeva** [comment]
Could you please send a screenshot and steps how you set colors? Here my case
![Ek3fo1cGGy](https://user-images.githubusercontent.com/51405061/97890300-70a56f00-1d3e-11eb-97e9-de618f137c36.gif)

**Comment by CannibalCorpse9** [comment]
My apologies, I forgot to chance the resultset datatypes to the color I want. It's working fine now.

**Comment by kseniiaguzeeva** [comment]
Please ask if you have any other questions
