### ISSUE TITLE
UI please add empty space at last row

### ISSUE THREAD

**Issue by erlangparasu** [dbeaver/dbeaver#10228]
**Is your feature request related to a problem? Please describe.**
The last  row is hovered by scrollbar.

**Describe the solution you'd like**
Add 1 empty row at the bottom.

**Describe alternatives you've considered**
Add bottom margin to last row.

**Additional context**
Screenshot: https://imgur.com/a/J74zX5Q

Env: Ubuntu 18.04.5 LTS, DBeaver 7.2.3

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. I cannot reproduce. Probably it is Linux issue.

**Comment by uslss** [comment]
will be fixed in the scope of #10950
