### ISSUE TITLE
Cancel query blocks the environment unless user confirm the disconnect and when it does cancel all active queries to the same database

### ISSUE THREAD

**Issue by lucas75** [dbeaver/dbeaver#10227]
I am using dbeaver for two weeks now and I found the cancel query behavior strange. When I cancel query of a running script, all other scripts on the same connection gets cancelled. On pgadmin each query window has its own connection and what happens in one tab does not affect the others. On pgadmin, I work with dozens of queries at the same time and I am having a very hard time to replicate this workflow on dbeaver. 

Steps to reproduce the problem:
- Create a PostgreSQL connection;
- Revoke access to the pg_catalog.pg_cancel_backend(int4) and pg_catalog.pg_terminate_backend(int4) for the current user or simple rename them (alter function  rename to pg_cancel_backend2; alter function pg_catalog.pg_terminate_backend(int4) rename to pg_terminate_backend2);
- Create a "Sql Script 1" window with the query select pg_sleep(3600);
- Create a "Sql Script 2" window with the query select pg_sleep(3600);
- Execute both queries
- Wait a minute
- Press cancel on the "Sql Script 1" window.
- After a few seconds dbeaver will show message "the database driver is not responding" offering to disconnect:
       - Answering "no", dbeaver show the same dialog. In effect the whole workspace gets inaccessible until we answer yes. 
       - Answering "yes", the navigator, the "Sql Script 1" and the "Sql Script 2" gets disconnected. I understand that only the "Sql Script 1" should get disconnected. I am wrong?

I am using the Version 7.2.4.202011011603 installed from the snap store.

**Comment by kseniiaguzeeva** [comment]
Please check whether option **Open separate connection for each editor** is enabled for the database.
Click SQL Editor in Main menu and select this option or press Settings button on the bottom toolbar of ResultSet
![Screenshot 2020-11-03 at 10 40 28](https://user-images.githubusercontent.com/51405061/97959849-447f0200-1dc1-11eb-9c14-a16f0790ab65.png)

**Comment by lucas75** [comment]
The problem happens even with the "open separate connection for each editor" enabled. 
Also tried "connect on editor activation" and "connect on query execute". Same result. 

![Captura de tela de 2020-11-03 08-11-10](https://user-images.githubusercontent.com/9705307/97978415-4c807700-1dac-11eb-96b4-7910251a8264.png)

![Captura de tela de 2020-11-03 08-10-55](https://user-images.githubusercontent.com/9705307/97978422-4d190d80-1dac-11eb-93a9-0a840c8627e4.png)

**Comment by kseniiaguzeeva** [comment]
Please send log files

**Comment by kseniiaguzeeva** [comment]
I managed to reproduce it when the option **Open separate connection for each editor** was disabled in SQL Editor menu.
Please enable it and try to execute again.
![Screenshot 2020-11-03 at 16 48 56](https://user-images.githubusercontent.com/51405061/97993206-cc323400-1df4-11eb-929a-a6f0777cc6b2.png)

**Comment by lucas75** [comment]
Sorry for the delay... I was installing a controlled environment to test this and I found why you could not reproduce my problem. In the database in question I do not have access to cancel queries and this trigger the "driver not responding" dialog. To simulate my problem is necessary to revoke access to the pg_cancel_backend and pg_terminate_backend functions (or rename them).

**Comment by uslss** [comment]
@lucas75 sorry for the late response. Is the issue still reproducible?

**Comment by uslss** [comment]
there is no update for a long time.
If it is still actual - feel free to reopen the issue.
