### ISSUE TITLE
Login to SAP HANA using Kerberos

### ISSUE THREAD

**Issue by jkrempien** [dbeaver/dbeaver#10221]
#### System information: 
- SAP HANA 2.00.037.03.1566979009 (fa/hana2sp03)
- DBeaver version 6.2.1

#### Describe your question:
Hi folks,
we have a SAP HANA installation where the Kerberos login is enabled.
With SAP HANA STUDIO I can normaly login by "Authentification by operating user".

Now I am struggling to connect with dbeaver.
I can not login to the database. Has anyone ideas if I have to set certain parameters in dbeaver? Or something else?

In general I am able to connect from dbeaver to this SP HANA db. If I create a user in SAP HANA where Kerberos is disabled, the login works fine.

I am thankful for any ideas.

**Comment by kseniiaguzeeva** [comment]
We do not support it. It is going to be implemented it in Enterprise Edition in future.

**Comment by LonwoLonwo** [comment]
HANA + Kerberos working in our PRO products: https://github.com/dbeaver/dbeaver/wiki/Kerberos-Authentication
