### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by SimoPoloDL** [dbeaver/dbeaver#10232]
Please can you translate all the menù on the right click?
Now he is half Italian and half English, a bit annoying.

Thank you,
Simone
![dbeaver](https://user-images.githubusercontent.com/56964675/97964813-a8053180-1db9-11eb-8187-f5aa50d84248.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
@SimoPoloDL you can help us! You can [localized](https://github.com/dbeaver/dbeaver/wiki/Localization) it all by you self.
Or leave here the translation in the format
string in english = translation
so that we can use this for correct translation

**Comment by acoluzzi** [comment]
@LonwoLonwo can you please assign this to me? I think I can help with italian translations 😉

**Comment by LonwoLonwo** [comment]
Hello @coluzziandrea 

There is nothing special in assigning for our team. Just create PR ;) And we will look at it.

**Comment by acoluzzi** [comment]
Yeah it's just for me as reminder 😊
