### ISSUE TITLE
"Delete multiple objects" window gets cropped and the buttons are unreachable

### ISSUE THREAD

**Issue by the-ge** [dbeaver/dbeaver#10236]
#### System information: 
- Operating system (distribution) and version: Kubuntu 20.04.1
- DBeaver version: 7.2.3, 7.2.4, maybe previous versions
- Additional extensions: none

#### Connection specification:
- Database name and version: ps177x_r0 (in a Docker container)
- Driver name: MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

The "Delete multiple objects" window gets cropped, hiding the bottom buttons. The only way to reach the buttons is to Alt-drag the window.

#### Steps to reproduce, if exist:

1. Double-click on a database with more than 43 tables (1920x1080 screen with a 8px font) to open the tables view.
2. Select all tables (or at least 44 of them).
3. Right-click on the selection and choose delete.

#### Include any warning/errors/backtraces from the logs: ---

![screenshot_2020-11-04-090242](https://user-images.githubusercontent.com/6468893/98079786-4e117400-1e6c-11eb-9e7a-bb6f4bece32c.png)

**Comment by serge-rider** [comment]
Also delete dialog must be resizable

**Comment by akilovich** [comment]
Fixed.

**Comment by uslss** [comment]
verified
