### ISSUE TITLE
DBeaver dump column with json doesn't escape correctly

### ISSUE THREAD

**Issue by fraparisi** [dbeaver/dbeaver#10238]
#### System information: 
- Windows 10
- DBeaver version 7.24

#### Connection specification:
- MySql 5.7, MariaDB 10.5
- MariaDb
- SSH

#### Describe the problem you're observing:
Starting from version 7.2.1 i cannot dump and restore correctly row with json inside (column type is a longtext).
I observe that when there is some text inside taken from a WYSIWYG and so with some "\n", the text is not escaped correctly.
For example a json dumped with version higher than 7.2.0 has this result:
`{
"corporateBenefitsHealthTextTitle1":"ACCIDENT INSURANCE\n"
}`
and cannot be deserialized correctly.
The same taken with version 7.2.0 has this result:
`{
"corporateBenefitsHealthTextTitle1":"ACCIDENT INSURANCE\\n"
}`
and this works

#### Steps to reproduce, if exist:
Column long text with some json inside with "\n" character and next dump and restore.

**Comment by ShadelessFox** [comment]
Hello, @fraparisi, can you provide a more detailed description about how to reproduce your issue and the log file? 
I'm using `Tools -> Dump database` and `Tools -> Restore database` and it's not causing any problems for me.

**Comment by fraparisi** [comment]
Take this dump as example. You can restore this with 7.2.0 and then try to dump the same table with 7.21 or major. You can see the different escape behavior ("\\n" correct -> "\n" not correct and then the json_decode function cannot deserialize correctly).
If you need some other informations, please let me know.
[dump.txt](https://github.com/dbeaver/dbeaver/files/5547176/dump.txt)

**Comment by ShadelessFox** [comment]
Still OK for me. Are you using `Tools -> Dump database` and `Tools -> Restore database`?

**Comment by fraparisi** [comment]
Sorry, everytime i wrote "\\\n" I lose an "\\". Yes, I use "Dump database" with default options. Have u tried to restore dump with 7.20 in a database and dump another time with version 7.24 and compare the file with a text editor?

**Comment by ShadelessFox** [comment]
The `Dump database` is actually using native client (`mysqldump` in this case) for dumping, so there's nothing to do with DBeaver itself.
Anyways, can you provide log file?

**Comment by fraparisi** [comment]
I tried different native client (from mysql 5.6, mysql 5.7, mariadb) with same result. How can I generate a log file for the operations?

**Comment by ShadelessFox** [comment]
https://dbeaver.com/docs/wiki/Log-files/

**Comment by fraparisi** [comment]
No interesting log there but it seems that last version 7.2.5 resolved my issue. thanks a lot :)
