### ISSUE TITLE
Records with string GUIDs (UUID) are not inserted

### ISSUE THREAD

**Issue by greenpeas** [dbeaver/dbeaver#10230]
PG 10, db 7.2.4, Win 10 x64
Records with string GUIDs (UUID) are not inserted, probably because the identifier is not wrapped in quotes:
![insert_guid_fail](https://user-images.githubusercontent.com/3856344/97956251-3b8a3280-1db9-11eb-9e62-e3b9bef51c08.gif)

**Comment by kseniiaguzeeva** [comment]
While I cannot reproduce your issue. Please send me table DDL example and log files

**Comment by greenpeas** [comment]
DDL https://pastebin.com/1URRVwfd
No errors in logs of PG.
Triggers that are present do not affect the situation.

**Comment by greenpeas** [comment]
@uslss @kseniiaguzeeva  I don’t know what happened, but now the identifier is surrounded by quotes and the entry is saved successfully. Were you able to reproduce the problem?

**Comment by greenpeas** [comment]
I switched to test mode and there is no such problem. She is only in production mode.
So I tried it on another computer:
![dbInsertFail](https://user-images.githubusercontent.com/3856344/98215930-74610d80-1f59-11eb-8171-c40e31742d97.gif)

**Comment by kseniiaguzeeva** [comment]
Could you please test it in 7.2.5 release? I can't reproduce it in Production mode too now.

**Comment by martinzima** [comment]
I was able to reproduce this in 7.2.4 by explicitly right clicking a row and selecting Generate SQL->INSERT. Upgrading to version 7.2.5 fixed this for me.

**Comment by greenpeas** [comment]
@kseniiaguzeeva In version 7.2.5 the problem is not reproduced/
