### ISSUE TITLE
Can't enter large SMALLINT UNSIGNED numbers

### ISSUE THREAD

**Issue by dalen** [dbeaver/dbeaver#10239]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
7.2.3
- Additional extensions

#### Connection specification:
- Database name and version
MySQL
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Essentially I get the same issue as in https://github.com/dbeaver/dbeaver/issues/8786 but on SMALLINT UNSIGNED. So trying to enter a number above the signed threshold (~32k) results in a negative number instead.

**Comment by LonwoLonwo** [comment]
Can reproduce.
https://dev.mysql.com/doc/refman/8.0/en/integer-types.html

**Comment by LonwoLonwo** [comment]
Fixed in 7.3.0

**Comment by uslss** [comment]
verified
