### ISSUE TITLE
Copy the contents of the Execution  Plan tab

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#10243]
I wish there was a function to copy the entire contents of the Plain tab.

Only one cell can be copied right now, but I wish I could copy the entire contents to compare the plans that change according to the SQL modification.

![copy_plan_content](https://user-images.githubusercontent.com/59002295/98199299-2f93a180-1f6e-11eb-80a2-eb6eb43e4688.png)

Thank for reading.  :)

**Comment by uslss** [comment]
thanks for the suggestion!

**Comment by serge-rider** [comment]
Command "Advanced copy" was added to plan tree, session list and other complex lists.

**Comment by uslss** [comment]
data can be copied but looks messy and it is rather hard to read
![image](https://user-images.githubusercontent.com/31996417/104900338-04c1c280-598d-11eb-9513-a5a1526710d1.png)

**Comment by serge-rider** [comment]
Cell values are divided with tab character (\t). You can paste this text in Excel or other spreadsheet and format it properly.
We don't want to format it according to the actual length of cell values because it may produce even worse output.
