### ISSUE TITLE
Export button broken in 4 October Release

### ISSUE THREAD

**Issue by TimMurnaghan** [dbeaver/dbeaver#10246]
#### System information: 
- macOS Catalina 10.15.7
- DBeaver version 7.2.2.202010041557
- Additional extensions

#### Connection specification:
- Postgres 12.3
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
The query result export button does nothing

**Comment by uslss** [comment]
Hi @TimMurnaghan ,
could you check if it reproducible for you against recent release?
is there something in the logs?

**Comment by uslss** [comment]
there are no updates on the issue for a long time.
If it is still actual for you - feel free to reopen the ticket with an additional info
