### ISSUE TITLE
Wrong referenced folder in TNS Names Path

### ISSUE THREAD

**Issue by geuss** [dbeaver/dbeaver#10240]
System information: 
- Operating system (distribution) and version : Windows 10 1904
- DBeaver version: 7.2.4
- Additional extensions: None

#### Connection specification:
- Database name and version: Oracle 12.0
- Driver name: JDBC Oracle Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

When I click on the "open folder icon" in the "Oracle connection settings" (see the picture below)
![image](https://user-images.githubusercontent.com/26387091/98118598-c2b7d300-1eab-11eb-96a3-770c3042b09f.png)

... dbeaver does not open the correct folder:
![image](https://user-images.githubusercontent.com/26387091/98118757-f98de900-1eab-11eb-8e70-940ad788227b.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
path isn't saved in properties.
1. Set path and save it
2. Open Connection properties
3. Check path - it is empty
![2020-12-25_14h51_57](https://user-images.githubusercontent.com/31996417/103134231-eb489600-46c0-11eb-9f1a-1354f5be4237.gif)

**Comment by uslss** [comment]
verified
