### ISSUE TITLE
Can't use local Driver, Configuration information is difficult to save successfully.

### ISSUE THREAD

**Issue by liuanxin** [dbeaver/dbeaver#10249]
#### System information: 
- Operating system (distribution) and version  :  Debian GNU/Linux 10 (buster)   Linux debian 4.3.0-1-amd64
- DBeaver version  :  7.2.4
- Additional extensions

#### Connection specification:
- Database name and version  :  every
- Driver name  :  every
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
The resolution of my computer is 1366 * 768. When I want to use the local driver, I find that I can't operate it at all. I can only add it. If I want to delete the default one, I can't operate it at all. I'm not sure if there is one below. Delete button, can't use the `Del` keyboard to delete the first record? Doesn't even give a scroll bar? It was really desperate when operating here!
![no-scroll](https://user-images.githubusercontent.com/2647495/98243118-77cfb580-1fa8-11eb-8473-60efdb637a59.png)

In addition, why do I find that my configuration can’t take effect after saving? You save dbeaver by default under /usr/share/, but it still has need `root` privileges. Are you kidding me? Even `sudo chmod 777 -R /usr/share /dbeaver` still does not take effect. until, The configuration is saved after restarting several times

**Comment by kseniiaguzeeva** [comment]
Thank you for your report. I change the ticket on a feature request about resizing.

Regarding your second issue, seems it can be corrected on your side. Please see where configuration files should be https://github.com/dbeaver/dbeaver/wiki/Workspace-location

**Comment by serge-rider** [comment]
Driver edit dialog was redesigned (main props moved to the separate tab):
![image](https://user-images.githubusercontent.com/6398845/107222059-80131300-6a25-11eb-8823-b470fa1d2986.png)

**Comment by uslss** [comment]
verified
