### ISSUE TITLE
Is it possible to compare values from a column that are returned by a query?

### ISSUE THREAD

**Issue by schmitzkr** [dbeaver/dbeaver#10242]
#### System information: 
- Ubuntu 20.10 groovy
- dbeaver 7.2.4

#### Connection specification:
oracle

#### Describe your question:
I have a table that contains/logs request details.  One column value is a CLOB containing the JSON payload.  I want to be able to compare two of those clobs, to see what changed.  I need to see the differences between the two JSON payloads.
To do this right now I have to copy and paste each value to an external editor and then compare them there.  Each one is about 60~70 lines.
I feel like dbeaver may be able to do this already or maybe able to make this workflow less manual but I cant seem to figure it out.
![image](https://user-images.githubusercontent.com/10168621/98146698-9aff4580-1e80-11eb-8949-085e56ff5521.png)

**Comment by kseniiaguzeeva** [comment]
We do not have a specific tool for such compare. But you can click on a cell and press Shift+Enter (or **Edit cell value on separate dialogue** button in the bottom toolbar). The separate editor for each value will be opened and you can visually compare the data.
