### ISSUE TITLE
Extensions cannot be installed on Dbeaver in archive format

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10250]
#### System information: 
- Operating system (distribution) and version 
- DBeaver version 7.2.4 zip or tar.gz

#### Steps to reproduce, if exist:
1. Download, unzip and run DBeaver
2. Go to Install new software and enter any of DBeaver extensions in work with field (e.g. DBeaver Office integration - https://dbeaver.io/update/office/latest/)
3. Go through the wizard and press Restart at the end

Expected: Dbeaver opened again with the installed extension
Actual result: DBeaver tries to start but fails  (the application label just jumps at the bottom toolbar)

Note: if you cancel the restart, the extension will not be installed, even if you restart Dbeaver manually later

**Comment by serge-rider** [comment]
Can't reproduce.
However it is a known issue when DBeaver splash starts to blink after extension install + restart.
We need more precise steps to reproduce.

**Comment by kseniiaguzeeva** [comment]
Can be reproduced in 7.30 release Mac version (https://dbeaver.io/download/ Will try Windows later too) using steps above

**Comment by tati-kru** [comment]
Floating bug. We need more precise steps to reproduce.

**Comment by uslss** [comment]
#10852

**Comment by uslss** [comment]
closed as a duplicate of #10852
