### ISSUE TITLE
Merge Into MS-SQL database inserts only 200 records

### ISSUE THREAD

**Issue by Silver62** [dbeaver/dbeaver#10254]
#### System information: 
- Windows 10
- Version 7.2.4.202011011603

#### Connection specification:
- MS SQL ODBC

#### 
Hello,
I found the error below:

MERGE xxx.dbo.TimeLine AS SourceTbl 
USING (select x, y, z from  xxx.dbo.xxx_csv) AS TargetTbl 
 ON SourceTbl.gltimestamp = TargetTbl.timestamp and SourceTbl.gltype=trim(TargetTbl."Art des Eintrags")
WHEN MATCHED THEN 
     UPDATE SET 
	  SourceTbl.Glvalue = (isnull(z , 0))
WHEN NOT MATCHED THEN 
    INSERT VALUES(newid(), TargetTbl.x, trim(TargetTbl."y"), (isnull(z , 0)), 0 , 0, 0, 'new'  );;;;

Complains missing ";" if there is ony one. Adding some more ";" it inserts 200 (random?) records of more than 9000.

No warning or errors, nothing in joblog.

Running the unchange code in VS works with no issues. (9509 rows affected)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.
As a workaround please try to set fetch size "0" or "-"
![Uploading Screenshot 2020-11-17 at 10.07.49.png…]()

**Comment by serge-rider** [comment]
This happens only with SQL Server over ODBC. Classic JDBC driver works ok.

Fixed.
I've added support of MERGE queries in SQL execution routine.

**Comment by kseniiaguzeeva** [comment]
Could you please also fix the issue with semicolon?

**Comment by serge-rider** [comment]
Problem with trailing delimiter was fixed.

**Comment by kseniiaguzeeva** [comment]
verified
