### ISSUE TITLE
Missing generate SQL Button

### ISSUE THREAD

**Issue by ImMrShrike** [dbeaver/dbeaver#10267]
#### System information: 
- Operating system Windows 10 PRO
- DBeaver version  7.2.4.202011011603
- Additional extensions

#### Connection specification:
- Database name and version ORACLE
- Driver name JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
The button to generate SQL queries is missing
![image](https://user-images.githubusercontent.com/34406881/98360074-83af8c00-2029-11eb-8031-a6a258381916.png)

#### Steps to reproduce, if exist: 
make a select query, in the results field select some elements and right click on mouse.

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce. Could you please send DDL of the table?

**Comment by p91paul** [comment]
try to qualify your table with the schema, or to select the correct schema from the top dropdown. Dbeaver is unable to follow synonyms when it needs to determine target table.

**Comment by kseniiaguzeeva** [comment]
Please tell Oracle version and send logs https://github.com/dbeaver/dbeaver/wiki/Log-files
