### ISSUE TITLE
NullPointerException when kill waiting process (Lock Manager)

### ISSUE THREAD

**Issue by greenpeas** [dbeaver/dbeaver#10268]
dBeaver 7.2.4, PG 10, Windows 10
[dBeaver error stack trace.txt](https://github.com/dbeaver/dbeaver/files/5501043/dBeaver.stack.trace.txt)

![nullPointerException](https://user-images.githubusercontent.com/3856344/98361245-41437a80-203c-11eb-8469-2163236fbbb7.gif)

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
Fixed in 7.3.0

**Comment by uslss** [comment]
verified
