### ISSUE TITLE
Hana Public Schema should have a synonym node only, not tables, views etc

### ISSUE THREAD

**Issue by wernerdaehn** [dbeaver/dbeaver#10263]
#### System information: 
- Operating system (distribution) and version: Windows
- DBeaver version: 7.2.4
- Additional extensions: none

#### Connection specification:
- Database name and version: Hana
- Driver name:
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing:
In the advanced view of a connection in the database navigator, there is a node PUBLIC [manually added](https://github.com/dbeaver/dbeaver/blob/62f12b8003b600a3a856c659f1c762de4fac04f2/plugins/org.jkiss.dbeaver.ext.hana/src/org/jkiss/dbeaver/ext/hana/model/HANAMetaModel.java#L75).
This node is the container for all public synonyms. Yet it shows sub nodes for Tables, Views etc and these will be empty always.

My suggestion:
* As it is a special schema, move it as first item. This is also compatible with SAP Hana Studio.
* Show only the synonym-node as child or maybe the synonyms directly.

**Comment by uslss** [comment]
thanks for the report

**Comment by wernerdaehn** [comment]
May I ask if this is supported by the framework already and how? 
One approach I can think of is to add a folder to the plugin.xml, similar to the data types folder. But then auto completion would not work as this looks into the schema nodes only.
In that sense it would be a schema node but with less types. Any hint how the framework knows which type nodes to render underneath?
I haven't looked into that code segment yet, however in my last pull request (not merged yet) I created a special schema class for the PUBLIC schema. That's probably the one to add this information.

**Comment by Matvey16** [comment]
Verified
