### ISSUE TITLE
[Exasol] extra separator in tables DDL

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#10261]
DBeaver 7.2.5
EXASolution 6.1.2

![2020-11-06 11_29_05-DBeaver Enterprise 7 3 0 - TABLE_WITH_PARTITION](https://user-images.githubusercontent.com/45152336/98344059-c2dade80-2023-11eb-9e8b-868c926803c3.png)
![2020-11-06 11_29_44-DBeaver Enterprise 7 3 0 - NEWTABLE123](https://user-images.githubusercontent.com/45152336/98344061-c3737500-2023-11eb-8091-cb6d78c164ad.png)

Extra delimiter after Partition statement.

**Comment by LonwoLonwo** [comment]
Table DDL:
Extra delimiter fixed.
Some extra spaces fixed.
Column and schema names now wrapped in quotation marks only when needed.

**Comment by kseniiaguzeeva** [comment]
verified
