### ISSUE TITLE
Wrong display of rights

### ISSUE THREAD

**Issue by GAEREL** [dbeaver/dbeaver#10271]
DBeaver Version 7.2.4.202011011603

When viewing role this one has 3 rights :
![image](https://user-images.githubusercontent.com/43636651/98369333-14da2f00-2039-11eb-9aea-2b2fdcad7a1b.png)

After a simple refresh (F5 ou the right bottom button) the last right is displayed 3 times :
![image](https://user-images.githubusercontent.com/43636651/98369527-6387c900-2039-11eb-9b41-1f737057b543.png)

You need to completely disconnect from database to get the correct display

thanks for you good job !
Take care.
Fred.

**Comment by GAEREL** [comment]
Add-on : The target database is a PostgreSQL 9.6

**Comment by uslss** [comment]
thanks for the bug report

**Comment by LonwoLonwo** [comment]
Fixed in 7.3.0

**Comment by uslss** [comment]
verified
