### ISSUE TITLE
Wrong data type mapped when use Export Data

### ISSUE THREAD

**Issue by thomazs** [dbeaver/dbeaver#10274]
When I try to use the "Export Data" option to migrate a table from Oracle database to PostgreSQL database, fields with type "number(15,2)" was mapped to "int4", and the values was rounded. 

This is DDL - Oracle  11G:

CREATE TABLE "SYSTABLESPACE"."COUNTS" 
   (	"SEQID" NUMBER, 
	"TYPECT" NUMBER DEFAULT 0, 
	"REGISTER_ID" CHAR(8), 
	"LOCATION" VARCHAR2(17), 
	"VALUE" NUMBER(15,2), 
	"DATECREATION" DATE, 
	"IDDATA" DATE, 
	"SEQ_ORDER" NUMBER(10,0), 
	"ID_RESTRICT" NUMBER, 
	 CONSTRAINT "COUNT_PK" PRIMARY KEY ("SEQID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 60817408 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTABLESPACE_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 847249408 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTABLESPACE" ;

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
verified
