### ISSUE TITLE
Aflter upgrading all tabs are disappeared

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#10270]
![image](https://user-images.githubusercontent.com/799021/98369274-5b338c00-2041-11eb-9923-0dd97d20cd42.png)

After upgrading from 6.x to 7.2.4 I miss all tabs with my scripts =(

Linux Mint v19.3

**Comment by kseniiaguzeeva** [comment]
It happened just once? Can you reproduce it again?

**Comment by KES777** [comment]
Sorry, I can not downgrade/upgrade (experiment with this). I did not do system snapshot before upgrading

**Comment by uslss** [comment]
still cannot reproduce an issue.
If it reproduces for you again during upgrade - please reopen an issue
