### ISSUE TITLE
Use ROWID to identify rows not working anymore

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#10277]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.2.4.202011011603
- Additional extensions

#### Connection specification:
- Database name and version: Oracle 11
- Driver name: ojdbc 19
- Do you use tunnels or proxies (SSH, SOCKS, etc)? n/a

#### Describe the problem you're observing:

The below setting is having no effect since a few versions (I already checked, I did not override it in datasource settings):
![immagine](https://user-images.githubusercontent.com/2157006/98448430-39630380-212c-11eb-82db-06e5c2ce5ca2.png)

#### Steps to reproduce
Check the above setting, then try and edit a table without a primary key. Instead of updating by rowid like it used to do, DBeaver will ask to define a virtual key or to use all columns.

**Comment by serge-rider** [comment]
Thanks for the bug report!

**Comment by serge-rider** [comment]
This bug ws caused by fix in #8576 (search of unique constraints).
We have to add this use case in regression.

**Comment by kseniiaguzeeva** [comment]
verified
