### ISSUE TITLE
Linux: conversion language, display exception

### ISSUE THREAD

**Issue by Iatbzh** [dbeaver/dbeaver#10275]
When I am testing dbeaver, I use the Linux subsystem ubuntu20 to install. After changing the software language to Chinese, the display is abnormal. Please check the picture
![s](https://user-images.githubusercontent.com/28798107/98443778-a2587480-2148-11eb-9441-e427dba1f711.jpg)

**Comment by kseniiaguzeeva** [comment]
Most likely a problem with the local Ubuntu, which does not have fonts.
