### ISSUE TITLE
Avoid formatter join lines

### ISSUE THREAD

**Issue by oxk4r01** [dbeaver/dbeaver#10278]
Dbeaver CE 7.2.4
Every time I format code the formatter joins all the lines. 
For example:
![image](https://user-images.githubusercontent.com/1032224/98464488-880fac80-21c3-11eb-936e-1f064691e4a3.png)
Becomes:
![image](https://user-images.githubusercontent.com/1032224/98464496-99f14f80-21c3-11eb-8f5b-59fefa160a02.png)
How can I avoid this? I get same results with default and compact formatter.

**Comment by uslss** [comment]
verified
