### ISSUE TITLE
Unable to set option in unicode checkboxes in settings menus the first time

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10279]
#### System information: 
- Mac
- DBeaver version 7.2.4

#### Steps to reproduce, if exist:
1. Create a column via UI for a table
2. Press Not Null in the opened window

Expected: option is checked
Actual result: no visible changes
Workaround: press the needed checkbox one time, then another checkbox in the same window, and then the needed checkbox again
Note: the same issue e.g. in data transfer settings
![Screenshot 2020-11-14 at 13 07 03](https://user-images.githubusercontent.com/51405061/99145285-90159380-267e-11eb-8b82-0e01d62bf1aa.png)

**Comment by akilovich** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
Columns are verified.

**Comment by akilovich** [comment]
Fixed the problem with consecutive clicking on the same checkbox.

**Comment by kseniiaguzeeva** [comment]
closed
