### ISSUE TITLE
Add the ability to change the display of nesting levels of the relations

### ISSUE THREAD

**Issue by johny22** [dbeaver/dbeaver#10282]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the ER Diagram could have an options when clicking in an Entity to seek for relations to reach another Entity ou show that can't.  e.g. Aluno related with Pessoa related with Telefone. When I choose Aluno and then Telefone, it will arrange the diagram with all relations to reach Telefone. Showing the path... Aluno => Pessoa => Telefone. 

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/5040090/98496886-68a76c80-2221-11eb-9d40-73abcc516a1f.png)

**Comment by kseniiaguzeeva** [comment]
All relations between tables are displayed in ERD by default. Could you please clarify with more details what your feature request is about?

**Comment by johny22** [comment]
In my situation I have a database containing thousands of tables. Before I create a ERD I choose all tables, and I can view all relations between tables. That's nice! But even with all the optimization of DBeaver arranging the tables in the diagram, I get a very polluted view. So I think that is less complicated If I analyse a reduced number of tables. The feature showed above can help a little in some cases, because it shows all relations of a table I choosed. But my problem is when I'm making complex query that I know two table I need for that, but I don't know how these tables are linked with wich other. Let's say that my tables are Person and City. Then we have:

Person -> Address -> City (But I don't know it yet)

If I choose Person and click on View Diagram, I will realize that Person has a relation Address but City will don't appear. I confess that I can choose Person, Address and City when creating my diagram and problem solved. But I just know that I need Person and City, I don't know the relations between them. If we have a feature that we choose two tables and dBeaver try to show all the relations between these or inform that there is no relations, it will so helpful and productivy. 

This example above is quite simple but I see more complex structures in my case.

**Comment by kseniiaguzeeva** [comment]
Thank you for the clarification

**Comment by kseniiaguzeeva** [comment]
We can add an additional button to ERD toolbar to show connections from table to table? Other ways to implement look more complicated

**Comment by johny22** [comment]
Thanks for consider. It's seem nice.

**Comment by E1izabeth** [comment]
Connections are highlighted now, if you click on the table field or on the connection (dotted line).
Does it solve your issue?

**Comment by johny22** [comment]
Yes @E1izabeth solved! Thanks so much.
