### ISSUE TITLE
Broken autocompletion in data viewer filter bar

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#10281]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.2.4.202011011603
- Additional extensions

#### Connection specification:
- Database name and version: Oracle 12
- Driver name: ojdbc19
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Autocompleting in the filter bar after inserting a few letters, leaves the inserted letters and autocompletes afterwards. 

#### Steps to reproduce, if exist:
See gif:
![autocomplete](https://user-images.githubusercontent.com/2157006/98470922-1185a580-21e9-11eb-89b4-5b74d5597c73.gif)

**Comment by serge-rider** [comment]
Workaround: insert space before column name

**Comment by LonwoLonwo** [comment]
Fixed. for all parenthesis and other special characters

**Comment by uslss** [comment]
verified
