### ISSUE TITLE
Script execution overwrites pinned tabs

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#10280]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.2.4.202011011603
- Additional extensions

#### Connection specification:
- Database name and version: Oracle 12
- Driver name: ojdbc 19
- Do you use tunnels or proxies (SSH, SOCKS, etc)? n.a.

#### Describe the problem you're observing:
If I pin a tab, then execute a set of statement as script, the tab keeps the pinned status, but its content gets overwritten

#### Steps to reproduce, if exist:
1. Execute a single query
2. Pin the result
3. Execute 2 more queries in new tabs (do not pin those)
4. Execute a script. You will be presented with the prompt below.
5. Click yes
6. Instead of leaving the pinned tab alone, its content gets replaced with the first query of the script.

![immagine](https://user-images.githubusercontent.com/2157006/98470338-3d9f2780-21e5-11eb-8681-dd5dcf19f2b8.png)

The other tabs are properly removed and replaced, but the pinned one should have been untouched. Also the pinned icon remains on the new tab, but it can't be unpinned anymore

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
verified
