### ISSUE TITLE
[Hive] does not support NOT NULL constraint until 3.0 version

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#10285]
Steps to reproduce:
1. Open any table in Hive
2. Choose "Create new column"
3. Choose "Not null" constraint for column
![2020-11-09 15_43_24-DBeaver Enterprise 7 3 0 - olympic](https://user-images.githubusercontent.com/45152336/98543621-cf6d6a00-22a3-11eb-998e-cd87d47ea278.png)
4. Save
5. Error occurred 
![2020-11-09 15_44_08-Hive Index couldn't be created · Issue #7530 · dbeaver_dbeaver](https://user-images.githubusercontent.com/45152336/98543677-e3b16700-22a3-11eb-9a68-695a9e653619.png)

https://docs.cloudera.com/HDPDocuments/HDP3/HDP-3.0.1/using-hiveql/content/hive_constraints.html

**Comment by LonwoLonwo** [comment]
Fixed in scope with https://github.com/dbeaver/dbeaver/issues/12124

**Comment by uslss** [comment]
verified
