### ISSUE TITLE
Result set metadata tag error

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#10296]
![image](https://user-images.githubusercontent.com/26621087/98633465-6c8bd980-235c-11eb-9362-59478c23fe3e.png)

It has a literal identifier, but it's still a field name
#### System information: 
- Operating system (distribution) and version  
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. Please tell your database.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional details.
