### ISSUE TITLE
java.net.UnknownHostException: domain.net: Name or service not known

### ISSUE THREAD

**Issue by nuklea** [dbeaver/dbeaver#10291]
#### System information: 
- Ubuntu 18.04, kernerl 5.4.0-52-generic x86_64 GNU/Linux 
- DBeaver 7.2.4 from Sap

#### Connection specification:
- any_name (cannot connect)
- MySQL 5
- No tunnels or proxies 

#### Describe the problem you're observing:

Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
  domain.net: Name or service not known

#### Steps to reproduce, if exist:

Connect to IPv6-host:

± dig AAAA domain.net | grep 'ANSWER SEC' -A2
;; ANSWER SECTION:
domain.net. 8 IN CNAME sas-domain.net.
sas-domain.net. 46 IN AAAA  *:*:*:*:0:*:*:*

#### Include any warning/errors/backtraces from the logs
https://gist.github.com/nuklea/c6ccb9abd550cc981e2a6b839ff08322

**Comment by nuklea** [comment]
Try use brackets around server host like '[domain.net]' -- `JDBC4Connection` using

**Comment by kseniiaguzeeva** [comment]
Could please give more details what is your problem?

**Comment by nuklea** [comment]
Yes, I can. What do you need?

**Comment by kseniiaguzeeva** [comment]
Could you describe what is your problem? Does something go wrong during connection?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional details.
