### ISSUE TITLE
Upgrade to the newest version from inside the app

### ISSUE THREAD

**Issue by simundev** [dbeaver/dbeaver#10292]
**Is your feature request related to a problem? Please describe.**
There is no problem, upgrading to new versions works as expected. This feature request is for convenience enhancement. Whenever there is a new version, I need to download it, close the app, install it, reload the app.

**Describe the solution you'd like**
I'd like there to be a button within the app that says "Upgrade to latest version" which would download the latest version, install it and restart the app if needed.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. We already have such ticket https://github.com/dbeaver/dbeaver/issues/6558.
Closed as duplicate.
