### ISSUE TITLE
Database Navigator not displaying all columns

### ISSUE THREAD

**Issue by enduser1604** [dbeaver/dbeaver#10295]
Database Naviagator seems to only be showing integer fields in all of my views and tables.

I can confirm when running `select * ` on the table that there are 150+ columns total, including various different column types. There are no filters that have been enabled and this issue is across multiple devices.

![image](https://user-images.githubusercontent.com/74217273/98608875-fd9d7a80-22a0-11eb-8970-ba438b5b0646.png)

**Comment by uslss** [comment]
Hi @enduser1604 ,
what database do you use?
probably you could provide a DDL that could help to reproduce an issue?
Thanks in advance

**Comment by enduser1604** [comment]
Hi @uslss 

Using PostgreSQL Redshift database using jdbc driver: RedshiftJDBC42-no-awssdk-1.2.x.x found here: https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html 

Reproducing is tricky but I have narrowed the error down to whether the view scans s3 in the underlying engine. If the view scans s3, database navigator displays only integer columns. If the view/table is instantiated then the columns appear as expected, i.e. all columns are visible.


DBeaver version 7.2.3

**Comment by enduser1604** [comment]
Hi @uslss 

Went to the source of the view I was having issues with and realized that the columns were erroring out(not showing in database navigator) in the source table as well. 


![javalang](https://user-images.githubusercontent.com/74217273/99729140-57efc580-2a6f-11eb-903b-d38bb19a75f1.png)





You can notice that the columns actually appear blank here, which is why the view has issues with displaying the columns in Database Navigator.


![stacktrace](https://user-images.githubusercontent.com/74217273/99729295-8b325480-2a6f-11eb-8eb8-20d7c1313f21.png)

Attached is the stacktrace for one of the errors.

[stacktrace.txt](https://github.com/dbeaver/dbeaver/files/5569987/stacktrace.txt)


DBeaver Version 7.2.3

Using PostgreSQL Redshift database using jdbc driver: RedshiftJDBC42-no-awssdk-1.2.x.x found here: https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html

**Comment by enduser1604** [comment]
@uslss any ideas on what could be causing this?

**Comment by uslss** [comment]
will be fixed in the scope of #10703
