### ISSUE TITLE
Changing theme fails with java.lang.NullPointerException

### ISSUE THREAD

**Issue by rajmondburgaj** [dbeaver/dbeaver#10290]
I just installed the app and wanted to switch to dark mode but for some reason I get some null exceptions as you can see in the image. This happens when I click apply button. Thou the them is switched fine, but would be worth checking what is causing this null exception.

![image](https://user-images.githubusercontent.com/7545874/98559731-45bf9b80-22a7-11eb-8954-cd73bffc5924.png)

I am using windows 10:
App version can be found below: 

![image](https://user-images.githubusercontent.com/7545874/98559900-77d0fd80-22a7-11eb-8cc2-17408d0b71bd.png)

**Comment by kseniiaguzeeva** [comment]
It is Eclipse problem. The application will be updated to a new Eclipse version in release 7.3.1

**Comment by serge-rider** [comment]
Will be fixed in #10535

**Comment by serge-rider** [comment]
Done

**Comment by kseniiaguzeeva** [comment]
Closed
