### ISSUE TITLE
Installing debugger on windows

### ISSUE THREAD

**Issue by shraddhapol** [dbeaver/dbeaver#10293]
I am trying to install debugger for dbeaver in Windows..
Can anybody help me in proper steps please?

**Comment by kseniiaguzeeva** [comment]
Please see the instruction https://github.com/dbeaver/dbeaver/wiki/Optional-extensions

**Comment by shraddhapol** [comment]
Hi,
Sorry for the late reply.. I have installed plugin in dbeaver but still
getting the same error as debugger plugin is not found..can you help me
with this, please?

**Comment by kseniiaguzeeva** [comment]
Please send log files https://github.com/dbeaver/dbeaver/wiki/Log-files
What is your DBeaver version?

**Comment by shraddhapol** [comment]
My dbeaver version is 7.2.5 which I recently updated..
Is it possible that you provide me baby steps to install debugger in
dbeaver like from start what I have to do and what tools needed if any,
please?
It will be actually a great help for me..I want to make the best use of
dbeaver in our project and we are in desperate need of debugger like the
one you have shared on twitter..
Thanks..

**Comment by shraddhapol** [comment]
Waiting for your reply..
Thanks..

**Comment by uslss** [comment]
duplicates #10192 .
issue will be resolved in the scope of the mentioned ticket. Thanks for the report.
Best regards
