### ISSUE TITLE
Table export: exclude columns and apply white space trim to columns

### ISSUE THREAD

**Issue by jmccay-work** [dbeaver/dbeaver#10303]
I love this program.  Thank you for creating and maintaining this awesome program.

When exporting a table to a CSV file, it would be nice to be able to select columns to exclude from the export and apply a white space trim to columns.  Yes, I could write a select statement, and then I could export the results.  Unfortunately, some of the table I deal with have a "ton" of columns.

Keep up the great work people!

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea.

**Comment by ShadelessFox** [comment]
Hello @jmccay-work,

May I ask what do you mean by `whitespace trim`? You want to fully _exclude_ columns from result set or just trim the containing data in them?

Thank you in advance.

**Comment by jmccay-work** [comment]
Sorry for the confusion.  

These are two separate issues.  The first would be to exclude specific columns from a export.  I have to deal with legacy tables that I think date back to the 80s or 90s.  The design of them is not optimum.  

The second request is that it would be nice to apply a whitespace trim to a column.  Again, the tables are not optimally designed and they use char instead of varchar.
 
While it is possible to write a select statement that does both of these things, the size of the tables can make this a daunting task.  These really are just suggested improvements, and I want to thank you for the awesome work on this product!

**Comment by ShadelessFox** [comment]
I see, thanks for a neat explanation!

**Comment by ShadelessFox** [comment]
Columns configuration for stream exporters (files) is now implemented:

![java_piE4RTXw7S](https://user-images.githubusercontent.com/35821147/111754346-ee5eb700-88a8-11eb-9bd7-74d52706cbba.png)

This dialog can be found on the <kbd>Exporter settings</kbd> page under the <kbd>Configure Columns</kbd> button.

Currently trimming is not implemented, unfortunately. A separate feature request will be created later.

**Comment by jmccay-work** [comment]
Awesome!  Thank you.  You people do great work!

Also, great name for the auto notification system.  It threw me off for a
moment.

**Comment by kseniiaguzeeva** [comment]
Verified
