### ISSUE TITLE
Problems displaying some catalogs/schemas AS400/DB2 on Database Navigator

### ISSUE THREAD

**Issue by arielcarralbal** [dbeaver/dbeaver#10302]
#### System information: 
- Operating system (distribution) and version **MAC OS X 10.15.7**
- DBeaver version **7.2.4**
- Additional extensions 

#### Connection specification:
- Database name and version **DB2 UDB for AS/400 , version 07.03.0000 V7R3m0**
- Driver name **JT Open 10.4**
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  **NO**

#### Describe the problem you're observing:
Some catalogs/schemas are shown as NAME00001 (truncated name with 00001 at the end, for example ENTERPRISE_NEW is displayed as ENTER00001, first five letters + 00001). Its content is not browsable and shown empty (tables, SP, are empty)

**Comment by arielcarralbal** [comment]
It does not seam to be the JT Open 10.4 driver. Tried same driver with Squirrel and Razor and this problems is not happening.

**Comment by uslss** [comment]
Hi @arielcarralbal ,
can you try to add `-Ddbeaver.jdbc.trace=true` parameter for application launch and then provide logs generated?
Thanks in advance

**Comment by arielcarralbal** [comment]
[jdbc-api-trace.log](https://github.com/dbeaver/dbeaver/files/5599460/jdbc-api-trace.log)

After watching this log, I executed 

SELECT CURRENT_SCHEMA FROM SYSIBM.SYSDUMMY1

and each schema that in this log is also shown as xxxxx00001 is normal in the resultset with that select. I also noticed that in the dbeaver schema names in the toolbar drop down are also shown as xxxxx00001. I see that, in my case, all schemas longer than 10 characters are converter to xxxxx00001 and not browsable.

**Comment by serge-rider** [comment]
This looks like a weird driver behavior.
@arielcarralbal Could you try to downgrade driver version (10.1 or 9.x)? You can do this is driver download dialog.

**Comment by arielcarralbal** [comment]
Tried 9.x and 10.1 driver and the problem persists.

**Comment by arielcarralbal** [comment]
All JT Open jar drivers I used (9.7, 10.1, and 10.4) shows DB2 catalogs normally on Eclipse "Data Source Explorer" Perspective. So I think it is not the drivers

**Comment by arielcarralbal** [comment]
Is there anything else I can do to make this issue been solve? (some debug, more logging, etc)

As I said, many JTOpen AS400/DB2 drivers version were tested on different IDEs (Eclipse, Razor SQL, Squirrel) and schema names are shown correctly, but not in DBeaver.

**Comment by kseniiaguzeeva** [comment]
Yes, please send also logs https://github.com/dbeaver/dbeaver/wiki/Log-files. They should help us to find a reason.

**Comment by arielcarralbal** [comment]
Here are the logs.

Trying to access catalogs/schemas that are shown as NAME00001 on  "Database Navigator" does not generate any logging.

Using IBM Data Studio we realized that columns or other objects names differ when longer than 10 chars.
Example: 
Column name : ENTERPRISE_ID
Object name (for that column): ENTER00001

The same for catalogs/schemas. So we think that if "Database Navigator" or "Choose catalogs/schemas" on the toolbar both use catalogs/schemas name, and not its "object name" would fix that. Since via DBeaver sql query or scripts those catalogs/schemas are reached ok.

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/6069033/dbeaver-debug.log)

**Comment by arielcarralbal** [comment]
I edited previous comment. Also here adding .log file

[log.log](https://github.com/dbeaver/dbeaver/files/6069512/log.log)

**Comment by ajaygautam** [comment]
Trying to migrate from DBVisualizer to DBeaver for DB2.
JDBC driver version: 11.5.0.0 (works fine with DBVisualizer)
MacOS: 10.15.6 (office controlled, cannot upgrade)
DBeaver version: 21.0.1 CE

Description: Unable to select schema / expand list of schemas.
Error: when trying to expand the "Schemas" node:

THE DESCRIBE STATEMENT DOES NOT SPECIFY A PREPARED STATEMENT. SQLCODE=-516, SQLSTATE=26501, DRIVER=4.26.14

Any ideas?

**Comment by Matvey16** [comment]
@arielcarralbal Can you please look what queries appear in the query manager when you are trying to see the contents of such schema in navigator and see nothing? To see the queries you need to open query manager and enable metadata read option in preferences.

![2021-06-23_12h49_54](https://user-images.githubusercontent.com/82543000/123076898-3a7a4400-d422-11eb-980a-c06b8c25f604.png)

![2021-06-23_12h50_30](https://user-images.githubusercontent.com/82543000/123076913-3d753480-d422-11eb-9935-27a33d20057a.png)

**Comment by Matvey16** [comment]
@arielcarralbal Also it looks like at some point we changed the default value of "metadata source" property to 0 for AS400 driver and it can cause this problem. Can you try changing this property to either -1 or 1 and look if it helps?

![2021-06-23_14h38_55](https://user-images.githubusercontent.com/82543000/123090732-2984ff00-d431-11eb-9b79-c8e889111c2f.png)

**Comment by serge-rider** [comment]
`metadata source` property configuration removed. Default driver settings by be used. It can be changed manually for a particular connection.

**Comment by Matvey16** [comment]
Verified

**Comment by arielcarralbal** [comment]
@Matvey16 setting metadata source to 1 fixed the problem!!

Thanks!
