### ISSUE TITLE
Redshift: Geometry datatype is not saving or viewing

### ISSUE THREAD

**Issue by abdulraziqadvani** [dbeaver/dbeaver#10306]
#### System information: 
- Operating system (distribution) and version (Ubuntu 18.04)
- DBeaver version (7.2.4)
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I am trying to save geometry data in a table but dbeaver is throwing an error and if I try to save via insert query then the query gets succeeded but data doesn't get save or view correctly.

I try to run the below query just to check what dbeaver interprets but it returns null
`SELECT ST_GeomFromText('POLYGON((0 0,0 1,1 1,1 0,0 0))',4326);`

Expected result for this is:
`0103000020E61000000100000005000000000000000000000000000000000000000000000000000000000000000000F03F000000000000F03F000000000000F03F000000000000F03F000000000000000000000000000000000000000000000000`

**Comment by uslss** [comment]
thanks for the report

**Comment by akilovich** [comment]
Fixed the issue. Although functions that return GEOMETRY type return it in WKB format, we've decided that we will show geometries in WKT format.

**Comment by uslss** [comment]
verified
