### ISSUE TITLE
I have a view named EMP1 ,I need to update the from condition in that view how to do that in dbeaver?

### ISSUE THREAD

**Issue by savitharaju13** [dbeaver/dbeaver#10304]
#### System information: 
- Operating system (distribution) and version
- DBeaver version

#### Connection specification:
- Database name and version

**Comment by uslss** [comment]
What your database?

**Comment by uslss** [comment]
there is no update on the issue. If it is still actual - feel free to reopen it with additional info that can help to investigate the problem
