### ISSUE TITLE
Add option to separate "Results" tabs into separate Eclipse view

### ISSUE THREAD

**Issue by ross-cohen** [dbeaver/dbeaver#1031]
It is standard Eclipse practice to break editors and their results/outputs/outlines (etc) into separate Eclipse "views", while DBeaver crams both the editor and query results into a single editor view.   This not only clashes with Eclipse practices, but also my workspace layout, where I generally arrange the top 66% of the screen for the editor, and the bottom 33% for the console/output (etc).  In my experience, most eclipse developers seem to work this way, so it would be nice if the DBeaver results view could be placed amongst the other output views in the bottom 33% of the screen.

**Comment by serge-rider** [comment]
Basically I agreed. But:
- More than 90% of DBeaver users use standalone version, they are not Eclipse users.
- Currently each SQL editor has it's own results, you can switch between editors (e.g. dev and production versions of the same database) and compare results. You can't do this having just one results view.

But in some cases single results view is more convenient. I think this can be configurable.

**Comment by ross-cohen** [comment]
It would be great to have it as a configuration option.    Thanks!

**Comment by hugorn** [comment]
@serge-rider The detach option is possible? It would be great to use with dual monitor and very large sql scripts.

**Comment by kseniiaguzeeva** [comment]
It is already implemented in #3365. Closed as duplicate.
