### ISSUE TITLE
group tab query

### ISSUE THREAD

**Issue by dimRobinGroupeBRIAND** [dbeaver/dbeaver#10317]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dimRobinGroupeBRIAND** [comment]
Is it possible to have goup for tab from environment ? exemple : 
- master
- test
- dev

_Or possibility to open several dbeaver process without error. One process for each one._
_(Because I've done mistake : wrong environment update between dev and master...)_

**Comment by dimRobinGroupeBRIAND** [comment]
Exemple :
- master
    - query1   /    query4   /    query5
- dev
    - query2   /    query3

**Comment by p91paul** [comment]
are you already using connection types, with different colors?

**Comment by dimRobinGroupeBRIAND** [comment]
yes but only two : white and green because the orange one cause may difficulties to update tables and most of times I need to do it even if it's in master

**Comment by dimRobinGroupeBRIAND** [comment]
colors are not enough for me... cause many times I've got more than 30 tabs opened

**Comment by uslss** [comment]
Hi @dimRobinGroupeBRIAND ,
did you try to [create ](https://github.com/dbeaver/dbeaver/wiki/Connection-Types#create-connection-type)your own connection type? Doesn't it solve your issue?

**Comment by dimRobinGroupeBRIAND** [comment]
heu, no

**Comment by dimRobinGroupeBRIAND** [comment]
thx for all comments :)

**Comment by HarveyJay** [comment]
I also think it's necessary to group tabs by different connections.
I think it's good to show only tabs in current connection.
