### ISSUE TITLE
Include Charmap windows-1252

### ISSUE THREAD

**Issue by serk12** [dbeaver/dbeaver#10312]
MySQL treats latin-1 like cp-1252 which has some problems with ISO-8859-1. The problem is tedious, but dbeaver doesn't includes CP-1252 making this problem more trickier. 

A good option to help the user would be include the charmap CP-1252. 

A example of the problem:
![image](https://user-images.githubusercontent.com/10197352/98832804-8fda8580-243d-11eb-8bbd-636135ea8cd3.png)

**Comment by uslss** [comment]
Hi @serk12 ,
can you provide steps on how to open the mentioned dialog?
btw, probably, you could change encoding to needed manually, without choosing it from drop-down. Just fill-in Other field with needed encoding name.
Also, can you clarify, are you talking about encoding for sql editor or for resultset?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional details.
