### ISSUE TITLE
license JDBC-ODBC bridge

### ISSUE THREAD

**Issue by Sanikadze** [dbeaver/dbeaver#10315]
Please show me what license JDBC-ODBC bridge has (jdbc-odbc-bridge-jre7.jar)?
And is there a link from the developers of this driver?

Thanks!

**Comment by serge-rider** [comment]
JDBC-ODBC bridge driver is a part of Oracle JRE 1.7 (i.e. before Oracle JDK became commercial).
So, probably this license covers it: https://www.oracle.com/downloads/licenses/javase7-license.html

**Comment by Sanikadze** [comment]
Thanks
