### ISSUE TITLE
DBeaver and AD authentication to connect to AWS Redshift

### ISSUE THREAD

**Issue by PeterB-CSF** [dbeaver/dbeaver#10327]
#### System information: 
- Windows 10 Enterprise ver. 1809
-  DBeaver	6.1.2.201907061627	org.jkiss.dbeaver.core.product

#### Connection specification:
- AWS Redshift

#### Describe your question:
Can I configure DBeaver to use AD authentication to connect to AWS Redshift

**Comment by uslss** [comment]
Hi @PeterB-CSF ,
we don't support AD for Redshift, but Kerberos authentication is already implemented for the Redshift in EE version. You could try it [here](https://dbeaver.com/trial/).
Please write back if it resolves your issue or not
