### ISSUE TITLE
Add parenthesis around subquery

### ISSUE THREAD

**Issue by enriquezrene** [dbeaver/dbeaver#10328]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to add `()` around a subquery to use it as a where clause, the selected text gets deleted and replaced by `(` 

**Describe the solution you'd like**
Imagine this scenario, you have a query to get the department `id`:

```
select id from departments where name = 'IT'
```

Now, you want to know all the people working on this department so you go ahead and:
```
select * from employees where deparment_id in
```

Right here, you might want to select the first query with the cursor and press `(` right, It would be awesome if after that the query can get wrapped by parenthesis, Currently, when you do that, the query is deleted and removed by the parenthesis. 

**Describe alternatives you've considered**
Same as above

**Additional context**
The above-mentioned feature is part of PgAdmin. I only hate it after PgAdmin started to work only in the browser and then I switched to DBeaver and this seems a nice to have feature

**Comment by uslss** [comment]
thanks for the report.

Seems the feature is working but not in all cases
![2020-11-23_17h13_04](https://user-images.githubusercontent.com/31996417/99972161-3cf2bd80-2daf-11eb-805a-183f4e864a25.gif)

**Comment by LonwoLonwo** [comment]
Hello @enriquezrene 
Could you add more details in your feature request?  As mentioned above, the possibility of wrapping brackets already exists in SQL Editor in DBeaver.

**Comment by enriquezrene** [comment]
Hi @LonwoLonwo 
I'm sorry. I think I was not clear enough. Let's say you're selecting the id of the IT department
```
SELECT id FROM deparment WHERE name = 'IT'
```

Now, let's say you want to know all the employees working on the above-mentioned department. So you need the following query:
```
SELECT * FROM employee WHERE deparment_id IN (SELECT id FROM deparment WHERE name = 'IT')
```

In this case, I want to use the first query as subquery, which means, I need to wrap it between parenthesis like this:

```
(SELECT id FROM deparment WHERE name = 'IT')
```



So it would be awesome if I were able to select the first created query and press the `(` key, and all the query gets wrapped with parenthesis, as I shown before. Unfortunately, what actually happens it's that all the selected query is replaced by `(`

**Comment by LonwoLonwo** [comment]
So far, the only case when I see that the replacement does not work - this is when there is nothing after query in SQL Editor and when it is right in front of delimiter (";").
As a workaround, you can use space+delimiter at the end of the query (see video).
 
![2021-03-15_09h56_59](https://user-images.githubusercontent.com/45152336/111115108-34e4a680-8575-11eb-882b-cb7052089eea.gif)

**Comment by LonwoLonwo** [comment]
Unfortunately, those several cases that I discovered not to fix.
They are on the side of the Eclipse, on which our program is based. 
But you can use workaround, that I suggested.

**Comment by LonwoLonwo** [comment]
Now I close this ticket, because it seems that problem solved - the wrapping in the brackets is supported by DBeaver.

Feel free to reopen the ticket if you appear additions.
