### ISSUE TITLE
Is there a way to enumerate FK entries?

### ISSUE THREAD

**Issue by wilhil** [dbeaver/dbeaver#10322]
Hi,

I've come from another app which was slow and annoying... DBeaver is a HUGE step forward and I'm loving it... however, one feature that I miss from the previous program was that if a field is a FK, rather than just displaying the ID, it would enumerate the name (customisable) column from the FK table in a dropdown/searchable list.

I just wondered if there is anything similar in DBeaver?

**Comment by uslss** [comment]
Hi @wilhil ,
if I understand you right - you can use Panels (Ctrl+7) - Reference panel where you can see FK Table
![image](https://user-images.githubusercontent.com/31996417/98935271-544ec280-24f4-11eb-878e-1aaddc3bafee.png)

**Comment by wilhil** [comment]
I'm just amazed by the features I'm finding and this is pretty much the only feature from the old app I'm missing :( 

I've seen the reference panel and it's better than nothing, but, it isn't as good as having a selection box :( FYI - I was using HeidiSQL - here is a pic: 

![image](https://user-images.githubusercontent.com/2283808/98982072-b3bdca00-2516-11eb-832a-80e8851a4121.png)

But... I got it wrong - I thought you could search/filter, not just a dropdown.

Based on so many other advanced features, I just thought I missed this somewhere! It not being here isn't enough to make me go back!

Thanks

**Comment by uslss** [comment]
You could create a feature request with a description of the feature you want :)

Close this issue as resolved
