### ISSUE TITLE
Translations in weblate not updated

### ISSUE THREAD

**Issue by aseques** [dbeaver/dbeaver#10338]
#### Describe your question:

I found that there's a project in weblate (see [here](https://hosted.weblate.org/projects/dbeaver/#components)) to help with dbeaver translation, but there are only a few strings to be translated and there's a warning about the strings being quite behind.

Is that an official project?

**Comment by comradekingu** [comment]
@serge-rider Is listed as the admin, so I imagine it is.

**Comment by serge-rider** [comment]
We don't use Weblate anymore. We are in process of migration into Crowdin.
