### ISSUE TITLE
How do you delete a database column?

### ISSUE THREAD

**Issue by Ariane-B** [dbeaver/dbeaver#10331]
#### System information: 
- Operating system (distribution) and version: Windows 10 20H2
- DBeaver version: 7.2.4

#### Connection specification:
- Database name and version: PostgreSQL ?? (I don't know how to check that! We're running it inside Docker and I've never really been involved in that part of the process.)

#### Describe your question:

I need to delete a couple of columns in a table. But I can't find the command for that! I can't find a button or right-click menu option that seems like it would do that, be it in the table's properties, its diagram or the column's details.

![image](https://user-images.githubusercontent.com/6244273/98965840-83efd180-24d8-11eb-9f61-10216cd2fa57.png)

![image](https://user-images.githubusercontent.com/6244273/98965879-936f1a80-24d8-11eb-99f0-5ad94782cb96.png)

How can I delete columns in DBeaver?

**Comment by LonwoLonwo** [comment]
@Ariane-B It seems, you are using Simple mode. 
Simple mode restricts working with objects.
You need to change the mode. 
To do this, click on your connection in the tree, and change "Connection view" from simple to advanced. 
![2020-11-12 22_19_47-DBeaver Enterprise 7 3 0 - TestTable](https://user-images.githubusercontent.com/45152336/98986354-d7dcd380-2535-11eb-91b0-62f4d8dd9bb3.png)


after reconnecting, you should have the buttons necessary for operation. example in the picture.
![2020-11-12 22_20_07-DBeaver Enterprise 7 3 0 - TestTable](https://user-images.githubusercontent.com/45152336/98986365-da3f2d80-2535-11eb-8d53-5dc69d19dae7.png)

**Comment by Ariane-B** [comment]
Oh, thank you! I would've never guessed. :)
