### ISSUE TITLE
DBeaver for Mac connection to Huawei GaussDB(DWS) failed

### ISSUE THREAD

**Issue by Doooing** [dbeaver/dbeaver#10342]
#### System information: 
- Operating system (distribution) and version    macOS Catalina 10.15.6
- DBeaver version     7.2.4

#### Connection specification:
- Database name and version
Huawei    GaussDB(DWS)     1.5.201 

#### Describe your question:
连接基于PostgreSQL的华为GaussDB(DWS)数据库时报错:
![image](https://user-images.githubusercontent.com/58727869/99047772-a284c400-25cf-11eb-874b-a910570195be.png)

对应驱动文件已下载成功:
![image](https://user-images.githubusercontent.com/58727869/99048627-c4327b00-25d0-11eb-8c8d-e1accb5634fc.png)

连接 PostgreSQL old 驱动也显示同样报错, 同时摘录已下载的驱动文件
![image](https://user-images.githubusercontent.com/58727869/99048558-ae24ba80-25d0-11eb-914b-a3a49efbe801.png)

连接信息是准确的, 相同连接信息在 window 10 DBeaver 6.2.3 中连接是成功的.

请帮忙处理一下,谢谢!

**Comment by Doooing** [comment]
有人遇到同样问题吗? 帮帮忙啊

**Comment by uslss** [comment]
Can you provide logs?

**Comment by Doooing** [comment]
Where should I find the DBeaver for Mac log file?

**Comment by uslss** [comment]
Here you can find an instruction - https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by Doooing** [comment]
I haven't used Dbeaver for a while, and today I can reconnect. No connection information or configuration changes, just reconnect. thank you very much. My problem has been solved.

**Comment by Doooing** [comment]
I haven't used Dbeaver for a while, and today I can reconnect. No connection information or configuration changes, just reconnect. thank you very much. My problem has been solved.

**Comment by Doooing** [comment]
有一段时间没有使用Dbeaver，然后今天再次连接时成功了。 没有修改任何连接信息, 只是将驱动重置默认后下载更新(之前也多次进行过这种尝试未果), 然后就成功了。 非常感谢, 我的问题已经解决。

**Comment by Doooing** [comment]
有一段时间没有使用dbeaver, 然后今天再次连接时成功了. 没有修改任何连接信息，只是将驱动重置重置后下载更新（之前也多次进行过这种尝试未果), 然后就成功了。非常感谢 ，我的问题已经解决。
