### ISSUE TITLE
[Solved] DBeaver 6 vs. 7: errors reading date field in Oracle DB 8: the time is not displayed

### ISSUE THREAD

**Issue by acicchetti** [dbeaver/dbeaver#10347]
### System information: 
- Operating system Windows 7, Lubuntu 20.04
- DBeaver 7.2.4

#### Connection specification:
- Database name and version: Oracle 8.1.7.1.0
- Driver name: Oracle JDBC 10.2.0.4.0 file ojdbc14.10.0.0.4.jar driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
In the query result, date fields always display the time 00:00:00.

#### Steps to reproduce, if exist:
Version 7.2.4
![Cattura](https://user-images.githubusercontent.com/72074781/99059868-73565e80-259f-11eb-9059-07bcb17f97a9.PNG)
Version 6.0.0
![Cattura](https://user-images.githubusercontent.com/72074781/99059923-88cb8880-259f-11eb-88b0-f43134f644b4.PNG)

#### Include any warning/errors/backtraces from the logs
No error found

**Comment by LonwoLonwo** [comment]
Hello @acicchetti 
Can you please tell me
What is the DDL for your table? What data type have date columns?
It seems 8 oracle doesn't support the timestamp format which usually shows time values.

**Comment by acicchetti** [comment]
> 
> 
> Hello @acicchetti
> Can you please tell me
> What is the DDL for your table? What data type have date columns?
> It seems 8 oracle doesn't support the timestamp format which usually shows time values.

Hello @LonwoLonwo 
I see that my version of Oracle DB support the timestamp format.
The connection test of Dbeaver display this version:
![Cattura](https://user-images.githubusercontent.com/72074781/102762199-3e94ae80-4378-11eb-9a71-51992e82f1ae.PNG)
if I check the format in TOAD I see my field with DataType DATE
![Cattura1](https://user-images.githubusercontent.com/72074781/102762723-f6c25700-4378-11eb-8f40-1b42356a4a72.PNG)
and if I check the value in the same table I see a date-time
![Cattura2](https://user-images.githubusercontent.com/72074781/102762975-5a4c8480-4379-11eb-9aad-0601fe7146f3.PNG)
Regards
Alessandro

**Comment by acicchetti** [comment]
Hi @serge-rider 
today I have upgraded my version of DBeaver to 7.3.5 but the problem is still present.
Maybe it can be resolved?
Regards
Alessandro

**Comment by LonwoLonwo** [comment]
Can't reproduce. 

With this driver
![2021-02-24 17_37_40-Connection _oracle 8_ configuration](https://user-images.githubusercontent.com/45152336/109019781-5cf58e00-76ca-11eb-8a1c-2b787d38fe53.png)

![2021-02-24 18_02_39-DBeaver Enterprise 21 0 0 - _oracle 8_ Script-89](https://user-images.githubusercontent.com/45152336/109020003-9af2b200-76ca-11eb-8f5b-6df1086218c0.png)

May be you changed driver version?
What happens if you change the time in the date cells? Is it preserved?

**Comment by acicchetti** [comment]
Hi
I changed the drivers and now the time is displayed correctly.
I found the driver in this link:
[https://www.oracle.com/technetwork/jp/database/enterprise-edition/jdbc9201-083937-ja.html](url)
the file to download is:
classes111.jar
![Cattura1](https://user-images.githubusercontent.com/72074781/109136506-7cd39300-7758-11eb-87b5-07d5c3e7c706.PNG)

and now date-time are displayed correctly.
![Cattura2](https://user-images.githubusercontent.com/72074781/109136781-c91ed300-7758-11eb-9121-301f24562959.PNG)

Thank you very much
Regards
Alessandro

**Comment by LonwoLonwo** [comment]
Hurrah! The power of drivers! Good luck with your future work.
