### ISSUE TITLE
Data Editor Custom filter: criteria option doesn't work

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10346]
#### System information: 
- Operating system (distribution) and version Mac
DBeaver 7.2.5 EA

#### Steps to reproduce, if exist:
1. Open a table in Data Editor
2. Open a custom filter, set a valid criteria and apply the filter
![Screenshot 2020-11-13 at 12 43 12](https://user-images.githubusercontent.com/51405061/99058670-976d6c00-25ae-11eb-8336-e679c5544aba.png)

Expected: the filter is applied to a table data
Actual result: the whole table is displayed without filter applying

**Comment by serge-rider** [comment]
Perhaps related to #9712

**Comment by akilovich** [comment]
Duplicate of #10366.
