### ISSUE TITLE
error in SQL Editor current connect

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#10344]
DBeaver 7.2.4
Postgresql 9

the task is:

 to execute a query for db_m1 in sqlEditor1, open an object of another db_m2 and transfer something to sqlEditor1 and execute for db_m1.

CASE:
1. two database in objects tree
![изображение](https://user-images.githubusercontent.com/61137576/99054655-27191780-25bb-11eb-94ba-183c94ef07c2.png)
2. Open sqlEditor1 for db_m1
![изображение](https://user-images.githubusercontent.com/61137576/99056025-8d059f00-25bb-11eb-8f14-53e8e8385164.png)
3. Open any object from db_m2. Open db_m2.table
![изображение](https://user-images.githubusercontent.com/61137576/99056345-000f1580-25bc-11eb-849c-b77a390f4e05.png)
DBeaver change current connect for  sqlEditor1(Script48) to db_m2 without my participation.

It is wrong because I'm sure I'm still working with db_m1 in sqlEditor1(Script48) and i am messed up the data in db_m2.
I'm sure I'm still working with db_m1 in sqlEditor1(Script48). But in fact DBeaver change current connect for  sqlEditor1(Script48) to db_m2.

**Comment by detkliff** [comment]
on version 7.2.5 problem is actual

**Comment by uslss** [comment]
Hi @detkliff ,
probably you've got Auto-sync connection with navigator option enabled. Can you check?
![image](https://user-images.githubusercontent.com/31996417/99525825-6aa0c680-29ab-11eb-8d40-d05389fd0368.png)

**Comment by detkliff** [comment]
OK. It is wor for me. Thank you!
