### ISSUE TITLE
mac os bigsur can not run dbeaver

### ISSUE THREAD

**Issue by jzdayz** [dbeaver/dbeaver#10345]
#### System information: 
- Operating system (distribution) and version 
![image](https://user-images.githubusercontent.com/35563513/99058033-91d84c00-25d7-11eb-8c65-1514b48d8369.png)

- DBeaver version
![image](https://user-images.githubusercontent.com/35563513/99057991-838a3000-25d7-11eb-9559-427c5c1cbf13.png)

- Additional extensions

![image](https://user-images.githubusercontent.com/35563513/99057966-7a995e80-25d7-11eb-881e-43d5009fd824.png)

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by jzdayz** [comment]
![image](https://user-images.githubusercontent.com/35563513/99058276-f09dc580-25d7-11eb-83cb-345ec6c4bd92.png)

**Comment by magnum** [comment]
i solved temporarily re-installing JDK
https://www.oracle.com/java/technologies/javase-jdk15-downloads.html

**Comment by johanjvrens** [comment]
I'm experiencing the exact same issue as above with openjdk version 1.8.0.275 installed via homebrew. Any ideas on how to solve this?

**Comment by ebaynaud** [comment]
```
brew cask install adoptopenjdk15
jdk 15
```

**Comment by sadamtsevich** [comment]
Update Dbeaver with version 7.2.5
https://dbeaver.io/download/

**Comment by johanjvrens** [comment]
> Update Dbeaver with version 7.2.5
> https://dbeaver.io/download/

I'm running dbeaver-ce-7.2.5-macos. Still have this issue.

**Comment by gJMI** [comment]
What has helped me was as a workaround – in the file `/Applications/DBeaver.app/Contents/Info.plist` uncomment the Eclipse key section and point to the VM you have locally installed, e.g. `<string>-vm</string><string>/Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java</string>`.

**Comment by johanjvrens** [comment]
> /Library/Java/JavaVirtualMachines/

Thank you so much for this quick and helpfull feedback! This solution worked for me:
`<string>-vm</string><string>/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java</string>`

**Comment by thinkbigconsultancy** [comment]
Try out linking the below - this works irrespective of version of DBeaver (I have tested with 7.2.4 and 7.2.5)
`sudo ln -s -f /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/server/libjvm.dylib /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/libserver.dylib`

You need to change the jdk1.8.0_181.jdk to whatever JDK version you have.

**Comment by krilim** [comment]
Using path _/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/bin/java_ for latest version of Oracle JVM also works OK in BigSur

**Comment by krilim** [comment]
I encounter same error while opening DBeaver in Linux (debian) ... It resolved when I used OpenJDK instead of Oracle Java.

**Comment by uslss** [comment]
duplicates #9533

**Comment by akilovich** [comment]
Nope, it is not a duplicate of #9533.

The issue seems to lay somewhere in the interaction between Equinox launcher, Big Sur, and JDK 8. Thank you all for your suggestions on solving this issue. The easiest I've found so far is to use JDK 11+. I'd recommend sticking to this solution as we are planning to transition to the new Eclipse version, which means that DBeaver will require JDK 11+ soon anyway. Alternatively, you can use our pkg installer, which comes with JDK 11 already bundled.

**Comment by shanmugaTrimble** [comment]
> What has helped me was as a workaround – in the file `/Applications/DBeaver.app/Contents/Info.plist` uncomment the Eclipse key section and point to the VM you have locally installed, e.g. `<string>-vm</string><string>/Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java</string>`.
> 
> (the hidden error behind – `The JVM shared library "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/../lib/server/libjvm.dylib" does not contain the JNI_CreateJavaVM symbol.`)

It worked for me. 
Thank you so much gJMI

**Comment by ilhamAminuddin** [comment]
i have some issue and fixed with run this on terminal to update jdk
brew install --cask adoptopenjdk
