### ISSUE TITLE
Create connection dialog locks application in case it was started from Projects tab

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#10352]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.2.5 EA

#### Describe the problem you're observing:
Cannot interact with UI if Connection Creation was started from Projects Tab
#### Steps to reproduce, if exist:
1. Open projects tab
1. Choose some project in DB Navigator
1. Start connection creation from context menu - Connection dialog open
1. Try to open Some other connection properties - it is not possible - gif attached
![2020-11-13_14h51_52](https://user-images.githubusercontent.com/31996417/99069962-6ac25000-25c0-11eb-8790-ca0cd2837391.gif)

**Comment by kseniiaguzeeva** [comment]
works as expected
