### ISSUE TITLE
[Teradata] impossible to select schema for SQL Editor

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10356]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 7.2.5 EA
#### Connection specification:
- Database name and version Teradata

#### Steps to reproduce, if exist:
Open SQL Editor for Teradata and try to set schema in upper toolbar

Expected: the selected schema is displayed in upper toolbar
Actual result: N/A is displayed in the toolbar after schema selection

Note: the same if open SQL Editor by buttons or by reading data in SQL console

**Comment by LonwoLonwo** [comment]
Select default schema is now available.
And the default scheme at the beginning of work is also selected.
Also solved the problem of missing quotes for query, which selects the default scheme in Teradata and Snowflake.
Can be checked on the Teradata.All and Snowflake.ILIKE

**Comment by kseniiaguzeeva** [comment]
verified
