### ISSUE TITLE
[Teradata] Comments cannot be added to table, table column, view via UI

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10351]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 7.2.5 EA

#### Connection specification:
- Database name and version Teradata

#### Steps to reproduce, if exist:
Try to add a comment to a table, view, column via UI

Expected: the column is added and can be seen in comment field and in DDL
Actual result: letters cannot be typed in a comment field

**Comment by LonwoLonwo** [comment]
Implemented in 7.3.2

**Comment by LonwoLonwo** [comment]
Delete comments in table and columns fixed.
Tab "show comments" added to table DDL.
