### ISSUE TITLE
Can't create ER Diagram from table diagram

### ISSUE THREAD

**Issue by balintn22** [dbeaver/dbeaver#10350]
First of all: the tool is great, thank you!

#### System information: 
- Operating system (distribution) and version
  Windows 10
- DBeaver version
  7.2.4 Community
- Additional extensions

#### Connection specification:
- Database name and version
  MS SQL Express 2019
- Driver name
  MS SQL (Current, as opposed to ones marked with 'Old')
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
  No

#### Describe the problem you're observing:
Can't create or copy/paste ER Diagram from table diagram

#### Steps to reproduce, if exist:
- In Database Navigator right-click any table
- Click View diagram - the diagram appears
- Select all objects (either CTRL-A or right-click/Select all)
- Right click background / Copy
- Create new ER Diagram
- Paste
- ERROR:
  Entity collect error
  Error during diagram entities collect
  Details: Invalid thread access
- Expected: entites pasted into the diagram

#### Include any warning/errors/backtraces from the logs
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Fri Nov 13 10:43:26 GMT 2020
Invalid thread access

**Comment by serge-rider** [comment]
Thanks for the bug report.

Fixed

**Comment by kseniiaguzeeva** [comment]
verified
