### ISSUE TITLE
connecting to Oracle with 2FA via DBeaver

### ISSUE THREAD

**Issue by armyofda12mnkeys** [dbeaver/dbeaver#10358]
#### System information: 
- Operating system (distribution) and version: Windows 10 Enterprise
- DBeaver version: 7.2.4.202011011603
- Java version: JDK 1.8 (1.8.0_271) although error logs show DBeaver might use Java 11

#### Connection specification:
- Database name and version: Oracle client 12.2 (our company recommends 12.2 client for now with works with TOAD, non-2FA DBeaver connections, and SQL Plus)
- Driver name: Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

We use 2FA via the Duo Mobile phone app for allowing connecting to prod Oracle.
Connecting to dev/qa/stg instances is fine but prod I can never connect to (note: i have the same user+password for all 4 envs..
Usually a Duo Mobile popup should come up on my phone to connect to Prod... Once I click 'Accept' in the app's popup then the db client will connect to Oracle... It works for TOAD and command line SQLPlus.
But DBeaver immediately always gives back a "ORA-01017: invalid username/password; logon denied" error.
Since it works with SQLPlus and TOAD, i dont think this isn't really a Duo Mobile specific issue, but maybe a 'how to setup DBeaver to give it enough time to allow existing server-side 2FA processes to work' question.
I tried to increase any timeout/connection settings (as maybe DBeaver needs to give enough time for me to receive the 2FA popup) but that didn't work. I always get error immediately.
Here are those timeout settings below:

**Connection settings->Driver Properties tab:**

**Driver Properties:**
oracle.net.CONNECT_TIMEOUT 30000
oracle.net.OUTBOUND_CONNECT_TIMEOUT 30000
**User properties:**
  loginTimeout 20

**Errors and timesouts area**
Timesouts
Connection open (ms): 10000
Connection close (ms): 5000
Connection validation (ms): 10000

Any idea how to get DBeaver working with 2FA?

A quick update/note: So we were getting SQLPlus working for another user from scratch ... If SQLPlus specifically finds the sqlnet.ora file which has below settings, then SQLPlus+2FA will work): 

**SQLNET.AUTHENTICATION_SERVICES= (RADIUS,NTS)
NAMES.DIRECTORY_PATH= (TNSNAMES, EZCONNECT)**

SQLPlus can find those files by maybe respecting $TNS_ADMIN env var that finds the tnsnames.ora and more importantly the sqlnet.ora file for our 2FA.
**How do we make DBeaver to find sqlnet.ora or add the above settings into the Oracle Driver connection settings as I believe maybe thats the issue as those settings are needed for 2FA?**

#### Include any warning/errors/backtraces from the logs
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Nov 12 15:15:16 EST 2020
ORA-01017: invalid username/password; logon denied

**Comment by armyofda12mnkeys** [comment]
I think I got it!
I just added a new property callled **oracle.net.authentication_services** with a value of RADIUS
![image](https://user-images.githubusercontent.com/410112/100152174-43953980-2e70-11eb-8f4f-58585bfb33a0.png)
and now Im getting the 2FA popup on my phone, awewome :)

**Comment by dlbannerman** [comment]
armyofda12mnkeys - Also new to DBeaver and have to use two-factor.  Might you provide a bit more information on what you did to get such to work?

**Comment by ArianHojatAES** [comment]
> armyofda12mnkeys - Also new to DBeaver and have to use two-factor. Might you provide a bit more information on what you did to get such to work?

I put in my usual connection information on main connection setting popup, and just added the RADIUS property that I mentioned above in the Drivers Properties tab in that popup.

**Comment by armyofda12mnkeys** [comment]
> armyofda12mnkeys - Also new to DBeaver and have to use two-factor. Might you provide a bit more information on what you did to get such to work?

I put in my usual connection information on main connection setting popup, and just added the RADIUS property that I mentioned above in the Drivers Properties tab in that popup.
