### ISSUE TITLE
Improve SQL folding perfomance

### ISSUE THREAD

**Issue by akilovich** [dbeaver/dbeaver#10354]
As of DBeaver 7.2.5 EA, when a ton of SQL statements are folded, the overall typing experience in the SQL editor is severely compromised. We need to improve that.

**Comment by wmdeepsea** [comment]
SQL折叠，无法实现 if endif的对应，还有一些其他语法的对应，建议优化

**Comment by wmdeepsea** [comment]
SQL folding, unable to achieve if ENDIF correspondence, there are some other syntax corresponding, it is recommended to optimize

**Comment by wmdeepsea** [comment]
Read and debug stored procedures like the toad tool

**Comment by akilovich** [comment]
Performance on large scripts has been massively improved. The only weak spot left is the situations like opening a multiline comment in the middle of the file.

**Comment by uslss** [comment]
verified
