### ISSUE TITLE
Set variable on query MySQL

### ISSUE THREAD

**Issue by noorsyamiera92** [dbeaver/dbeaver#10369]
Hi Support,

Can help me on how to set variable for mysql?

sample as below:

set @a = 1;
select @a;

When I execute this , i will received error 1064.
Can please advise me on the steps?
Thank you.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. Which MySQL and DBeaver version do you use?

![Screenshot 2020-11-16 at 10 46 39](https://user-images.githubusercontent.com/51405061/99225389-0938f600-27f9-11eb-86d3-9be8043eb2b5.png)

**Comment by noorsyamiera92** [comment]
Hi there,

Im using mysql 5.7 and dbeaver 7.2.5

[image: Screenshot 2020-11-17 at 9.14.52 AM.png]


this is my setting

[image: Screenshot 2020-11-17 at 9.17.36 AM.png]


Please advise how to fix this.
Thank you.


Regards,
Noor Syamiera

**Comment by kseniiaguzeeva** [comment]
Could you please send screenshots one more time here or on ksenia@jkiss.org. By some reason they are not loaded correctly and I cannot see them.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional details.
