### ISSUE TITLE
Failed to create the Java Virtual Machine.

### ISSUE THREAD

**Issue by non-trace** [dbeaver/dbeaver#10360]
<img width="260" alt="图片" src="https://user-images.githubusercontent.com/7167108/99143000-1341e400-2695-11eb-87dc-e451794eaab7.png">
<img width="266" alt="图片" src="https://user-images.githubusercontent.com/7167108/99143008-281e7780-2695-11eb-8a36-1c4c32ebe2b0.png">

**Comment by JuwanXu** [comment]
#10345

**Comment by uslss** [comment]
duplicates #10345 

anyway thanks for the report

**Comment by linehammer** [comment]
If you having multiple Java versions installed on your system, then this can be happen. You can solve this by change the maximum memory allowed for the eclipse process (which is run in a [Java Virtual Machine](http://net-informations.com/java/intro/jvm.htm)). Open eclipse.ini (which is in the same directory as eclipse.exe)  in  Notepad or any other text-editor application, Find the line -Xmx256m (or -Xmx1024m). Then change the default value 256m (or 1024m) to 512m . You also need to give the exact java installed version (1.6 or 1.7 or other).

Like This:

```
-Xmx512m
-Dosgi.requiredJavaVersion=1.6
```

OR

```
-Xmx512m
-Dosgi.requiredJavaVersion=1.7
```

OR

```
-Xmx512m
-Dosgi.requiredJavaVersion=1.8
```

**Comment by xenel5** [comment]
how can get the directory as eclipse.exe? or how can i get my java version ?
