### ISSUE TITLE
No highlighting on IFNULL in SQL editor 

### ISSUE THREAD

**Issue by cd4d** [dbeaver/dbeaver#10367]
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04
- DBeaver version: 7.2.4 
- Driver for MySQL 8 and later

#### Steps to reproduce, if exist:
- Open a new SQL Editor  
- Write any SQL queries with IFNULL() 
- IFNULL() is not highlighted.

IFNULL is not highlighted, but the function itself works. Is this expected?

**Comment by LonwoLonwo** [comment]
This function is not on our list, so it is not highlighted. Thanks for noticing. I'll add it.

**Comment by cd4d** [comment]
Thanks!

**Comment by LonwoLonwo** [comment]
IFNULL(), ISNULL(), NULLIF() and more other functions added

**Comment by uslss** [comment]
verified

**Comment by gramadin** [comment]
same here

**Comment by LonwoLonwo** [comment]
Implemented in version 7.3.0
