### ISSUE TITLE
Export doesn't apply format settings except where checkboxes are used because of focus loss

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10366]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 7.2.5 EA

#### Steps to reproduce, if exist:
1. Open export wizard for a table and select SQL format
2. Change keyword case and Insert keyword settings only in format settings
3. Go to the last step of the wizard and check Target settings

Expected: the changes of SQL format are displayed
Actual result: the default settings are displayed and export happens with default settings too

Workaround: set an additional setting for SQL Format (e.g. Omit schema name) and all settings will be applied
![Screenshot 2020-11-15 at 10 21 40](https://user-images.githubusercontent.com/51405061/99179220-8f3b3b00-272c-11eb-9afa-ede8a4c5fdb5.png)

**Comment by kseniiaguzeeva** [comment]
Can have 1 reason with https://github.com/dbeaver/dbeaver/issues/10361

**Comment by kseniiaguzeeva** [comment]
Maybe relates also to https://github.com/dbeaver/dbeaver/issues/10279

**Comment by serge-rider** [comment]
Duplicate of #10361 (thye actual problem is that cell editor doesn't apply changes, not settings themselves).

**Comment by kseniiaguzeeva** [comment]
A way to reproduce was changes a little:

1. Open export wizard for a table and select SQL format
2. Change keyword case and Insert keyword settings only in format settings
3. Go to the last step of the wizard and check Target settings

Expected: the changes of SQL format are displayed
Actual result: only the first changed setting was applied. And the setting is not applied at all if it is the only one.

**Comment by akilovich** [comment]
It turns out that this is an old and well-known bug: 
https://github.com/dbeaver/dbeaver/issues/3553

**Comment by akilovich** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified
