### ISSUE TITLE
Cannot connect to MS SQL server

### ISSUE THREAD

**Issue by svhnl** [dbeaver/dbeaver#10364]
System information: 
- Windows 10
- Dbeaver version: 7.2.3.202010191702
I am new to dbeaver and am trying to switch from Microsoft SQL Server Managament Server. MS SQL SMS uses windows authentication but that doesn't work. After that I tried resetting the password of and using the "sa" account, but that didn't work either. I have also tried changing the databasename and changing the connection to my computer name but none work. Every time I get this error:
`The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection timed out: no further information.. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".`
I have also tried disabling the firewall but that doesn't do anything either.
This is what my connection screen looks like on MS SQL MSM:
![dbeaver 1](https://user-images.githubusercontent.com/20358521/99151459-ab42cc00-269b-11eb-8b95-c5333ec3da9a.png)
this is what the Dbeaver screen looks like:
![dbeaver 2](https://user-images.githubusercontent.com/20358521/99151480-c57caa00-269b-11eb-834a-780ebfac1c44.png)

P.S I am a Informatics student and thus not very fluent in SQL and the like. I probably have missed to include some things that seem very clear but aren't for me, please try to keep that in mind.

**Comment by uslss** [comment]
Hi @svhnl ,
seems tcp/ip is disabled. 
Can you check it?
https://www.ibm.com/support/knowledgecenter/en/SSETBF_3.1.1/com.ibm.siteprotector.doc/tasks/sp_t_enabling_msde_communication_over_tcpip.htm

**Comment by svhnl** [comment]
That did the trick. Thank you so much. I thought I was not filling in the right password or something similar.
