### ISSUE TITLE
Custom highlighting for functions

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#10374]
Currently built-in functions are highlighted the same way as types. We need to improve it and provide custom color highlighting for functions to easily distinguish between them.

![java_7nGanC1OSX](https://user-images.githubusercontent.com/35821147/99235941-92efc000-2807-11eb-84df-413b1820d986.png)

**Comment by kseniiaguzeeva** [comment]
Several functions are highlighted as keywords. Can this be changed?

**Comment by kseniiaguzeeva** [comment]
Some statements are not highlighted:
`SELECT USER(), UID FROM DUAL;`
```
SELECT TRANSLATE('SQL*Plus User''s Guide', ' */''', '___') FROM DUAL;
TRANSLATE('SQL*PLUSU
```
`SELECT LENGTH('CANDIDE') "Length in characters"  `
```
UPDATE translate_tab 
   SET char_col = TRANSLATE (nchar_col USING CHAR_CS);
```
```
SELECT customer_id, SET(cust_address_ntab) address
  FROM customers_demo;
```
```
SELECT VALUE(p) FROM persons p;
VALUE(P)(NAME, SSN) (edited) 
```
