### ISSUE TITLE
Metadata search on object description

### ISSUE THREAD

**Issue by wasd345** [dbeaver/dbeaver#10370]
Search is not very useful, you cannot search tables or fields based on table or column comments

**Comment by kseniiaguzeeva** [comment]
Metadata Search can be used for tables (search goes only in an active schema https://github.com/dbeaver/dbeaver/wiki/DB-Metadata-Search)

Search within table or table column comments is not implemented. I change the ticket on feature request.

**Comment by wasd345** [comment]
> Metadata Search can be used for tables (search goes only in an active schema https://github.com/dbeaver/dbeaver/wiki/DB-Metadata-Search)
> 
> Search within table or table column comments is not implemented. I change the ticket on feature request.


刚才试了一下按照数据库元数据搜索还是不行，我的意思是说不能按照表描述或者字段描述来搜索，我用的是达梦数据库
Just now I tried to search according to the database metadata, but it still can't. I mean that you can't search according to the table description or the field description，I use the Damon database

**Comment by flambchap** [comment]
Implemented for PostgreSQL, SQL Server, Oracle, Exasol, and MySQL.

**Comment by kseniiaguzeeva** [comment]
verified
