### ISSUE TITLE
DBeaver is not running on macOS Big Sur

### ISSUE THREAD

**Issue by Fernandosilvasc** [dbeaver/dbeaver#10388]
#### System information: 
- Operating system (distribution) and version : macOS Big Sur - version 11.0.1
- DBeaver version: dbeaver-ce-7.2.5

#### Describe the problem you're observing:

After I updated my macOS to the latest version, DBeaver starts showing the warn before launching the application as below:

![image](https://user-images.githubusercontent.com/58282921/99321267-4bc2f880-2822-11eb-806e-7c3f94e138d3.png)

I tried to reinstall the application but didn't work, still appears the warn.

**Comment by kerozo** [comment]
On my machine, I got the same problem with BigSur; however, updating jdk solve it. 
e.g. brew cask install adopptopenjdk

**Comment by Fernandosilvasc** [comment]
Thanks @kerozo it works for me too.
