### ISSUE TITLE
result in text mode

### ISSUE THREAD

**Issue by ramunozp** [dbeaver/dbeaver#10382]
#### System information: 
- Operating system (distribution) and version: MacOs Big Sur
- DBeaver version: 7.2.5

#### Connection specification:
- Database name and version: DB2 AS400

#### Describe your question:
with the latest version I lost the alignment of the text mode. How do I repair it?

![image](https://user-images.githubusercontent.com/24207310/99262062-4783e480-27fc-11eb-883b-f8f4f5845b4b.png)

help!

**Comment by uslss** [comment]
hi, can you provide table ddl?
thanks in advance

**Comment by ramunozp** [comment]
DDL of the table? or is it something else?
So that this could be useful? This happened to me when I changed the version of dbeaver.

I've looked through the options and can't find a property or reference that fixes this.

**Comment by ramunozp** [comment]
DDL of the table? or is it something else?
So that this could be useful? This happened to me when I changed the version of dbeaver.

I've looked through the options and can't find a property or reference that fixes this.

**Comment by uslss** [comment]
is issue reproducible in dark mode only?

**Comment by ramunozp** [comment]
in all modes

**Comment by kseniiaguzeeva** [comment]
It is Big Sur issue. Thank you for the report.

**Comment by flambchap** [comment]
Working on this issue. As a workaround, I may suggest you change the text font to some monospace font, e.g. Monaco.

**Comment by flambchap** [comment]
The problem is not related to the macOS or DBeaver version. It's about text editor fonts. It is imperative to use the monospaced font in order for the text view to work properly. Unfortunately, there is nothing we can do at this point.
