### ISSUE TITLE
Refresh button in projects view header does not refresh tables

### ISSUE THREAD

**Issue by guardiande** [dbeaver/dbeaver#10383]
#### System information: 
- Windows 10
- DBeaver 7.2.5

#### Connection specification:
- SQLite 3.1

#### Describe the problem you're observing:

The refresh button in the projects view header does not refresh the connection tree.

![image](https://user-images.githubusercontent.com/4947715/99263714-dfdf9080-281f-11eb-8746-d5c4951d5db2.png)

#### Steps to reproduce, if exist:

1. Create a new table.
1. Press the refresh button (see screenshot above)
1. Note that the newly created table does not show in the table tree under the connection.
1. Right click on the connection
1. Select refresh
1. The table shows up.

**Comment by kseniiaguzeeva** [comment]
Thank you for t he report.

**Comment by ShadelessFox** [comment]
Hello, @guardiande, this is expected behavior. This button refreshes projects from local file system, this is not supposed to refresh connections.
