### ISSUE TITLE
PostgreSQL: "permission denied for relation pg_tablespace" 

### ISSUE THREAD

**Issue by uwine-fr** [dbeaver/dbeaver#10396]
#### System information: 
- Operating system (distribution) and version; macOS 10.15.7
- DBeaver version: 7.1.1
- Additional extensions: -

#### Connection specification:
- Database name and version: PostgreSQL 
- Driver name: PostgreSQL JDC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

The user I am connecting with has no privileges on some system tables, such as pg_roles, pg_tablespace, etc. Each time I open a table in the database navigator, an error pops up with the following message:

  java.lang.reflect.InvocationTargetException
    Internal driver error
    Internal driver error
      SQL Error [42501]: ERROR: permission denied for relation pg_tablespace
      SQL Error [42501]: ERROR: permission denied for relation pg_tablespace
        ERROR: permission denied for relation pg_tablespace
        ERROR: permission denied for relation pg_tablespace

This is not blocking, I just have to close it, but it gets really annoying. 
I could not find a setting to tell DBeaver not to check the tablespace at all.
A proposed fix could be to:
- add a setting to disable checking for the tablespace
- fail silently
- pop an error the first time it fails for a given connection, then fail silently 

#### Steps to reproduce, if exist:

- Revoke the privileges (if any) of the current user on the pg_catalog.pg_tablespace table.
- Open a table in the DBeaver navigator.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by flambchap** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
Verified. The error only appears for tables with no permissions.

**Comment by kfnakam** [comment]
When I processed SQL sentence, the message "SQL Error [25P04]: FATAL: terminating connection due to idle-session timeout" appeared and I could not proceed further. 

[example for SQL.docx](https://github.com/dbeaver/dbeaver/files/11997528/example.for.SQL.docx)
