### ISSUE TITLE
Solarized light themes

### ISSUE THREAD

**Issue by edgar-koster** [dbeaver/dbeaver#10393]
Hello,

When I search in google for 'dbeaver solarized light' I can see that dbeaver had the theme but I can't find it anywhere, the link it should open is dead. Does this mean it doesn't exist anymore, or is it I just don't know where to look? I tried the eclipse preferences but that didn't work.

![image](https://user-images.githubusercontent.com/24190040/99370095-86c63a00-28bd-11eb-9f77-15faaacb186e.png)

**Comment by uslss** [comment]
Hi @edgar-koster ,
for now it is available in [Eclipse color theme plugin](http://www.eclipsecolorthemes.org/?view=plugin)

**Comment by DonDeWitt** [comment]
Eclipse color theme plugin hasn't been updated for 7 years, doesn't work.
