### ISSUE TITLE
DBeaver: Disable Auto SQL Assistant/Completion for table aliases 

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#10405]
DBeaver - **Version 7.2.5 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

The automatic **SQL Assistant/Completion** annoyingly suggest table names for table aliases, this should not be done.

**1**) Start to write "**SELECT * FROM MyTable MT**"
**2**) If you now stop typing (with our *DBeaver* configuration there is a 500ms delay),
&nbsp;&nbsp;&nbsp;&nbsp;the automatic **SQL Assistant** pops up and suggest  table names that start with "MT".

The automatic **SQL Assistant** should not suggest database tables when I start to write table aliases.

**PS**. This is a copy of the feature request issue #7847 that was supposed to have been fixed in version **7.0.1**, but was not.

**PPS**. The misbehaviour is still there in version **7.2.5**.

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
Hello @pdanie 
Unfortunately i can't reproduce it.
![2021-01-19 12_50_39-](https://user-images.githubusercontent.com/45152336/105017614-0c4c9e80-5a55-11eb-93d2-3c6a51a03a4e.png)

Can you please try new [DBeaver versions](https://dbeaver.io/)? May be somethings changed?

**Comment by LonwoLonwo** [comment]
Closed.
You can reopen issue, if the problem recurs.

**Comment by pdanie** [comment]
I have tried it in **DBeaver CE 7.3.2** and it stil a bug.

BUT... It shows up when you do a **JOIN**...

```
SELECT *
  FROM MyTable1 MT1
  JOIN MyTable2 M
```

**1**) Stop typing after "My" for the second table and auto assistant kick in. (**OK**)
**2**) Stop typing after "M" for the alias for the **MyTable2** the auto assistant kicks in. (**ERR**)

Seems the code that decide if I should get auto assistant or not has logic that does not cover more than a simple SELECT * FROM...

**PS**. This further explanation is copied/entered as new support case #11165 too.

**Comment by LonwoLonwo** [comment]
Yes, this is already a separate case.
