### ISSUE TITLE
 Firebird database connect is incompatible with Chinese characters

### ISSUE THREAD

**Issue by grassvalley** [dbeaver/dbeaver#10406]
#### System information: 
- Operating system (distribution) and version： ubuntu / Mint
- DBeaver version : 6.1 ~ 7.2
- Additional extensions

#### Connection specification:
- Database name and version firebird
- Driver name firebird
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Dbeaver report "Dynamic SQL Error; SQL error code = -104; Token unknown ", when firebird database table name, field name, view has chinese characters.

#### Steps to reproduce, if exist:
Create a firebird database and has a chinese characters table name, then connect to is using dbeaver.

**Comment by uslss** [comment]
still actual in 21.2.0

**Comment by E1izabeth** [comment]
Does it still reproducible in the latest DBeaver version?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
