### ISSUE TITLE
MariaDB TIME datatype loss of information

### ISSUE THREAD

**Issue by vmsh0** [dbeaver/dbeaver#10401]
#### System information: 
- Arch Linux
- 7.2.4

#### Connection specification:
- MariaDB 10.5.8-MariaDB
- MariaDB Connector/J 2.4.3

#### Describe the problem you're observing:
When visualizing data sets with _TIME_ columns, time values are wrapped at 24hrs, while MariaDB specifically supports time values in the range '-838:59:59.999999' to '838:59:59.999999'.

This is a limitation of the JDBC API, as explained by the MariaDB JDBC driver maintainer [here](https://jira.mariadb.org/browse/CONJ-823). However, there exists the workaround of getting the value out of JDBC as a string, so this limitation can definitely be addressed.

Note that the driver from MySQL exhibits the different behaviour of returning `null`.

#### Steps to reproduce, if exist:
Execute the following query using the standard MariaDB client and DBeaver, and observe the different results:
`SEC_TO_TIME(257394)`

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
