### ISSUE TITLE
Firebird 2.5 views cannot be saved if it was created using UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#10411]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 7.3.0 EA

#### Connection specification:
- Database name and version Firebird 2.5.

#### Steps to reproduce, if exist:
1. Create view
2. Save it
3. Refresh views node in db navigator - newly created view disappears
![2020-11-18_12h04_53](https://user-images.githubusercontent.com/31996417/99509308-aaa97e80-2996-11eb-978d-2960cf084b40.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
