### ISSUE TITLE
SQLScriptParser issues with new lines and comments

### ISSUE THREAD

**Issue by akilovich** [dbeaver/dbeaver#10416]
#### System information: 
- DBeaver 7.2.5

#### Connection specification:
- Database name and version: MySQL 5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

STR:
1. Connect to sakila.
2. Open SQL editor.
3. Paste the following script: 
```
-- comment

SELECT *
FROM sakila.albums;
```
The folding mechanism which uses SQLScriptParser will recognize it as one query.

4. Add additional new line: 
```
-- comment


SELECT *
FROM sakila.albums;
```
Now we have 2 statements, but the first one spans 2 lines (`-- comment\n`).

It results in two problems:
1. Folding does not work properly.
1. When executing statements via Ctrl + Enter, the executed statement does not correspond with the folding. It is quite counterintuitive.

**Comment by ShadelessFox** [comment]
Looks like it depends on underlying connection's dialect.

_Reproducible: MySQL, PostgreSQL_
_**Non**-reproducible: Oracle, SQL Server_

**Comment by uslss** [comment]
verified
