### ISSUE TITLE
Oracle: Only Sessions that execute SQL are shown

### ISSUE THREAD

**Issue by simasch** [dbeaver/dbeaver#10413]
Plugin: org.jkiss.dbeaver.ext.oracle
Code: OracleServerSessionManager
Line: 84

The outer join is missing
Wrong:
`sql.append(" AND s.sql_child_number = sq.child_number");`
Correct:
`sql.append(" AND s.sql_child_number = sq.child_number (+)");`

**Comment by serge-rider** [comment]
Thanks!

**Comment by serge-rider** [comment]
Fixed in #10413

**Comment by uslss** [comment]
verified
