### ISSUE TITLE
SQL Editor execution issues

### ISSUE THREAD

**Issue by sjzyc** [dbeaver/dbeaver#10428]
SQL editors often fail to execute statements, and clicking the execute button does not respond.
Re-opening an SQL editor is now available, after which the execute button is invalid
Current Version 7.2.5
This problem has existed since the upgrade to version 7

**Comment by uslss** [comment]
hi, what OS do you use? Is there something in logs? Maybe you could provide a video of the issue?
Thanks in advance

**Comment by sjzyc** [comment]
Windows 10
There is no prompt, clicking the execute button does not have any response

**Comment by uslss** [comment]
still cannot reproduce an issue.
Probably you should try to reset UI settings using Main Menu: File - Reset UI settings

**Comment by uslss** [comment]
there is no update on issue for a long time. 
if issue is still actual for you - feel free to reopen it
