### ISSUE TITLE
Foreign table as partition is not shown

### ISSUE THREAD

**Issue by StepanYankevych** [dbeaver/dbeaver#10426]
DBeaver Version 7.2.5.202011152110
PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit

We use foreign table as partition for range partitioned tables using native partitioning (not inheritance) 
Since 7.2.5 version I can't see that foreign table in partitions list 
Everything was good in older versions not sure what exact version was good, probably even 7.2.4 .

**Comment by LonwoLonwo** [comment]
Thanks for the bug report.

**Comment by serge-rider** [comment]
Last partiotion management refactoring in 7.2.5 broke this.

**Comment by serge-rider** [comment]
Fixed.

@StepanYankevych  Could you test the fix in the Early Access version? (https://dbeaver.io/files/ea)

**Comment by StepanYankevych** [comment]
Looking good. 
Thank you 
![image](https://user-images.githubusercontent.com/25589816/100075933-4892c280-2e49-11eb-9b3d-ebd39810297d.png)
