### ISSUE TITLE
mysql: unable to load authentication plugin ''.

### ISSUE THREAD

**Issue by amirtal** [dbeaver/dbeaver#1042]
cannot connect to mysql
error is returned:
unable to load authentication plugin ''.

**Comment by serge-rider** [comment]
Seems to be related to http://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=829
Please provide more details.
Do you know what auth plugin do you use?
Do this work in other UI/CLI clients?

**Comment by kid1412621** [comment]
According to this article(https://blog.gabriela.io/2018/02/22/how-to-use-mysql-8-0-4-with-a-gui/),that may caused by JDBC driver. The default MySql connection driver is mysql-connector-java-5.1.44 which downloads automatically from Maven.However the latest driver is mysql-connector-java-8.0.11.But I still cannot configure it out even I change the driver.

**Comment by kid1412621** [comment]
@serge-rider 
Hey there, I just installed MySql 8.0.11 and DBeaver 5.0.4;
And I can enable to connect the localhost db via MySQL WorkBench.
But I connected via DBeaver,it shows the same error as @amirtal proposed.

**Comment by kid1412621** [comment]
![snipaste_2018-05-04_15-23-27](https://user-images.githubusercontent.com/26278054/39616776-ab500ad4-4faf-11e8-886c-a8f32ca7076f.png)
It's relevant to this settings. After I altering to legacy,I can access with root user.But customized user is the same error.

**Comment by serge-rider** [comment]
Do you know what authentication plugin is used by the server?

**Comment by kid1412621** [comment]
@serge-rider sorry for the delay. I just installed the latest version on local PC.

**Comment by serge-rider** [comment]
I've reproduce that with latest MySQL server version.
We'll upgrade driver version in DBeaver in the next version, thanks for report.

**Comment by bizcontact** [comment]
Remove the driver by clicking delete. Add driver and choose LATEST you should be good.

**Comment by campos20** [comment]
I goodled to here, solved my issue with

https://github.com/dbeaver/dbeaver/issues/4691#issuecomment-442173584

**Comment by mateusconrad** [comment]
with me the issue was just the version. My server runs an old version of mysql. 
After selecting this 5 version it worked
![image](https://github.com/dbeaver/dbeaver/assets/34871931/40a832e9-5c89-4134-8031-8d904ae429e3)
