### ISSUE TITLE
A potential NPE bug

### ISSUE THREAD

**Issue by JulyChen728** [dbeaver/dbeaver#10427]
Hi all,
our bug scanner has reported a NPE bug.

Since the method [getSystemProperty()](https://github.com/alibaba/Sentinel/blob/eed77cafc28e68a291bc0adcd71ceeceffdc8db9/sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/EagleEyeCoreUtils.java#L157) may return null,  the variable [tmpPath](https://github.com/alibaba/Sentinel/blob/eed77cafc28e68a291bc0adcd71ceeceffdc8db9/sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/EagleEye.java#L99) may be null and a NPE bug may take place when the variable `tmpPath` invokes its method `endsWith()` at [here](https://github.com/alibaba/Sentinel/blob/eed77cafc28e68a291bc0adcd71ceeceffdc8db9/sentinel-core/src/main/java/com/alibaba/csp/sentinel/eagleeye/EagleEye.java#L101).

Thanks.

**Comment by serge-rider** [comment]
Wrong repository?
