### ISSUE TITLE
The button "Link with editor' doesn't work

### ISSUE THREAD

**Issue by Kaerol** [dbeaver/dbeaver#10429]
![image](https://user-images.githubusercontent.com/9872518/99639376-ce78cd00-2a47-11eb-951c-052cdf8a0ca2.png)

The button "Link with editor" doesn't work.

It used to work connecting open table in tab with connection tree (expand branches and select linked table).

Since few versions it's broken :(

**Comment by LonwoLonwo** [comment]
Can't reproduce.
Need more information.
What version of DBeaver you have? OS? May be, database.

**Comment by Kaerol** [comment]
Version 7.2.5.202011152110

Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

PostgreSQL

**Comment by Kaerol** [comment]
Strange :/

Before write this Issue I tested and not worked,
now after your comment I tested again and works :)

I close it....

**Comment by LonwoLonwo** [comment]
@Kaerol it's a magic!
