### ISSUE TITLE
Can't connect with embedded derby 

### ISSUE THREAD

**Issue by bborba** [dbeaver/dbeaver#10436]
#### System information: 
- Operating system (distribution) and version
  ubuntu 20.10
- DBeaver version
  7.2.5

#### Connection specification:
- Database name and version
  Java Derby embedded port 1527 created by Oracle SOA installation

#### JDK version
openjdk version "11.0.9.1" 2020-11-04

#### Describe your question:
Dbeaver works fine, I can connect with Oracle/Mariadb/SQlite without issues.

I need to connect with an embedded Derby DB created by Oracle SOA installation.
>     URL: jdbc:derby://localhost:1527/soainfra
>     ERROR: Bad URL: jdbc:derby://localhost:1527/soainfra

The URL is validated through ij command line
> ij version 10.14
> ij  CONNECT 'jdbc:derby://localhost:1527/soainfra';
> ij  show schemas;
> TABLE_SCHEM                   
> ------------------------------
> SOAINFRA                      
> 12 rows selected

Driver directory listing:
.local/share/DBeaverData/drivers/maven/maven-central/org.apache.derby# ls -ltra

> total 4572
> -rw-rw-r--  1 bborba bborba    2488 Nov 18 11:55 derby-10.15.2.0.pom
> -rw-rw-r--  1 bborba bborba    5975 Nov 18 11:55 derby-project-10.15.2.0.pom
> -rw-rw-r--  1 bborba bborba    2211 Nov 18 11:55 derbyshared-10.15.2.0.pom
> -rw-rw-r--  1 bborba bborba    2427 Nov 18 11:55 derbytools-10.15.2.0.pom
> -rw-rw-r--  1 bborba bborba 3683035 Nov 18 11:55 derby-10.15.2.0.jar
> -rw-rw-r--  1 bborba bborba   93688 Nov 18 11:55 derbyshared-10.15.2.0.jar
> -rw-rw-r--  1 bborba bborba  264445 Nov 18 11:55 derbytools-10.15.2.0.jar
> -rw-rw-r--  1 bborba bborba    2475 Nov 18 16:55 derbyclient-10.15.2.0.pom
> drwxrwxr-x  2 bborba bborba    4096 Nov 18 16:55 .
> -rw-rw-r--  1 bborba bborba  601103 Nov 18 16:55 derbyclient-10.15.2.0.jar

Kind of stuck as this is too basic for not working.
Thanks

**Comment by kseniiaguzeeva** [comment]
Sorry for the long response. I cannot reproduce it. Most probably a wrong driver was used.
Select Derby Embedded and fill the path to the database.

![Screenshot 2020-12-22 at 18 18 08](https://user-images.githubusercontent.com/51405061/102903995-28731500-4482-11eb-8fc5-9a34540907cf.png)
![Screenshot 2020-12-22 at 18 18 21](https://user-images.githubusercontent.com/51405061/102904000-29a44200-4482-11eb-965b-f91d16e236f4.png)

**Comment by uslss** [comment]
there is no update for more than a month.
If the issue is still actual for you - feel free to reopen it
