### ISSUE TITLE
Another potential NPE bug

### ISSUE THREAD

**Issue by JulyChen728** [dbeaver/dbeaver#10434]
Hi all,
our bug scanner has reported another NPE bug.

The variable `worksheets` is checked for whether being `null` at [DataExporterXLSX.java#L312](https://github.com/dbeaver/dbeaver/blob/8097d63f7c9a87d8525cfa2411e31187257042ce/plugins/org.jkiss.dbeaver.data.office/src/org/jkiss/dbeaver/data/office/export/DataExporterXLSX.java#L312), while not checked at [DataExporterXLSX.java#L317](https://github.com/dbeaver/dbeaver/blob/8097d63f7c9a87d8525cfa2411e31187257042ce/plugins/org.jkiss.dbeaver.data.office/src/org/jkiss/dbeaver/data/office/export/DataExporterXLSX.java#L317).

Thanks.

**Comment by uslss** [comment]
seems to be obsolete

**Comment by LonwoLonwo** [comment]
Nope, it is still actual, unfortunately.

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by uslss** [comment]
verified
