### ISSUE TITLE
[MSSQL]Invalid type 243 is shown when exists any User Defined Table Type in MSSQL

### ISSUE THREAD

**Issue by yyjdelete** [dbeaver/dbeaver#10433]
#### System information: 
- Operating system (distribution) and version
- DBeaver version: 7.2.5.202011152110 CE
- Additional extensions

#### Connection specification:
- Database name and version: MSSQL 2016
- Driver name: com.microsoft.sqlserver.jdbc.SQLServerDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
An extra invalid type 243 is shown when exists any User Defined Table Type in MSSQL

#### Steps to reproduce, if exist:
1.
```sql
CREATE TYPE Table_TVP_Item AS TABLE (
	Item int NOT NULL,
	PRIMARY KEY (Item)
)
```
2. F5, and create or edit an exist column in dbeaver

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/1819074/99651161-36073a80-2a91-11eb-8a91-2660b225895d.png)

**Comment by LonwoLonwo** [comment]
Thanks for bug report. 243 - System ID of user defined types. But it shouldn't be on that list.

**Comment by LonwoLonwo** [comment]
Fixed in 7.3.1

**Comment by LonwoLonwo** [comment]
Table data types removed from column types list.

**Comment by uslss** [comment]
verified
