### ISSUE TITLE
A potential NPE bug

### ISSUE THREAD

**Issue by JulyChen728** [dbeaver/dbeaver#10435]
Hi all.
Again, our bug scanner reports a NPE bug.

The variable `target` is checked for whether being null at [DatabaseMappingContainer.java#L126](https://github.com/dbeaver/dbeaver/blob/8097d63f7c9a87d8525cfa2411e31187257042ce/plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseMappingContainer.java#L126) while not checked at [DatabaseMappingContainer.java#L136](https://github.com/dbeaver/dbeaver/blob/8097d63f7c9a87d8525cfa2411e31187257042ce/plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseMappingContainer.java#L136).

Thanks.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report, but it is expected.
