### ISSUE TITLE
Problems executing process after exporting data

### ISSUE THREAD

**Issue by andrmo** [dbeaver/dbeaver#10442]
This concerns exporting multiple Postgres tables in SQL format, using the option "Write to the single file". If the "Execute process on finish"option is also selected , then

a) The process is executed once for every table exported. Given I'm exporting to a single output file, my expectation would be that the process is not finished until all tables are exported - ie the process should only be run once.

b) Including the ${table} variable in the process spec, always results in the name "export" being used for every table processed. (I was hoping to use this as a work-round in the process to know which process execution was related to the last table)

#### System information: 
- Windows 10
- 7.2.5
- Additional extensions: None

#### Connection specification:
- Postgres
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : SSH Tunnel

#### Describe the problem you're observing:
See above

#### Steps to reproduce, if exist:
See above

#### Include any warning/errors/backtraces from the logs
n/a

**Comment by kseniiaguzeeva** [comment]
Please tell what is written in **execute process on finish** option?

**Comment by andrmo** [comment]
Here's what I put:
C:\Dev\tmp\\cleanupGenerator.bat ${file} ${table}

**Comment by kseniiaguzeeva** [comment]
Sorry for the long response.
a) Does your process work when you write it as described above? Please try `cleanupGenerator.bat`
b) I can reproduce it. I receive "export"  in every filename with variable ${table}

**Comment by andrmo** [comment]
Seems like you can reproduce (b) so only need a response on (a).
a) The process does get executed, but once per table, which as I said seems wrong as I'm exporting to a single output file..

**Comment by kseniiaguzeeva** [comment]
Thank you for your report and additional details.

a) it is a bug and will be fixed in future releases
b) variable ${table} doesn't suite when export is performed to a single file

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
