### ISSUE TITLE
[UI] dropdown color (blue color) not take full width

### ISSUE THREAD

**Issue by erlangparasu** [dbeaver/dbeaver#10443]
#### System information: 
- Ubuntu 18
- DBeaver 7.2.5

#### Connection specification:
- Database MariaDB

#### Describe the problem you're observing:
dropdown color (blue color) not take full width
#### Steps to reproduce, if exist:
change ubuntu theme

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/20636828/99744334-722eaf80-2b12-11eb-8da9-20a8eff33859.png)

**Comment by uslss** [comment]
hi @erlangp ,
what theme do you use?

**Comment by erlangp** [comment]
sierra-light-solid

**Comment by uslss** [comment]
Hi @erlangp ,
can you check if it is still reproducible against 7.3.1?

**Comment by erlangparasu** [comment]
sorry but it is still on version 21

**Comment by E1izabeth** [comment]
Does this issue still reproducible on the latest DBeaver version?

**Comment by E1izabeth** [comment]
It's been a while since no update here, so I'm closing this issue.
