### ISSUE TITLE
CSV Connection resets extension used in driver properties after application restart

### ISSUE THREAD

**Issue by drewed** [dbeaver/dbeaver#10440]
#### System information: 
Property | Value
---|---
**OS**|macOS Catalina 10.15.7
**DBeaver version**|7.2.5.202011152110
**Extensions**|None

#### Connection specification:
Property | Value
--- | ---
**Database Name/Version**|N/A
**Driver Name**|Flat files/CSV

#### Describe the problem you're observing:
I have a CSV connection to my local filesystem where a third party application exports pipe-delimited flat files which I frequently need to ingest into our PostgreSQL database.  This third party application doesn't put an extension on the files it produces.  In order to be able read them, I need to set the connection's extension driver property to an empty string; however, when I restart the application the settings is "reset" with the default value for the driver.  This requires me to "fix" the driver properties every time I run the application.

#### Steps to reproduce, if exist:
1. Create a pipe-delimited flat file named "test" containing the sample data below (note the lack of extension on the file)
1. Create a CSV connection to the folder containing the file
    1. In the driver properties for the configuration, set the separator to a pipe (|) and the extension to an empty string
1. Open the connection and observe that the test file is listed
1. Exit DBeaver
1. Open the connection and observe that the test file is no longer listed
1. Open the connection settings, navigate to the driver properties and observe that the extension property has been reset to ".csv"

##### Sample Data
**one** | **two** | **three**
--- | --- | ---
a1|a2|a3
b1|b2|b3
c1|c2|c3

#### Include any warning/errors/backtraces from the logs
N/A

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer and thank you for the report.

**Comment by flambchap** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified
