### ISSUE TITLE
DBeaver is halted

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#10454]
![image](https://user-images.githubusercontent.com/799021/99831767-43dbbf00-2b68-11eb-8273-7f01a43a2340.png)

#### System information: 
- Linux Mint v19.3
- v7.2.4

#### Connection specification:
- PostgreSQL 11.5

#### Describe the problem you're observing:
When I run the infinite query DBeaver is halted. Despite on I click 'Cancel'
It is halted even when I stop database server.
It does not consume memory It just hangs up

#### Steps to reproduce, if exist:
Run infinite query

![image](https://user-images.githubusercontent.com/799021/99831989-92895900-2b68-11eb-966d-34181e153362.png)

The process java is take all process time.

hm.... while I am writing issue DBeaver is crashed. I do not see it at taskbar.

**Comment by kseniiaguzeeva** [comment]
Please give a query example.

**Comment by KES777** [comment]
The query example is on the screen

**Comment by kseniiaguzeeva** [comment]
Could you please give tables DDL to create the environment to run the query?

**Comment by KES777** [comment]
```
WITH RECURSIVE xx AS (
 SELECT 1
 UNION ALL
 SELECT * FROM xx 
 WHERE true


)
SELECT * FROM xx;
```

**Comment by kseniiaguzeeva** [comment]
Thank you. But I cannot reproduce the bug for the query from the comment in 7.3.0 version. Could you please send log files? https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by KES777** [comment]
I also can not reproduce =(
Now I wait untill java take 100% CPU and seconds stop to count, then press 'cancel', but after a min or two query is cancelled. Try to turn off database after `cancel` is pressed but before dbeaver cancels query

**Comment by kseniiaguzeeva** [comment]
please send log files https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by uslss** [comment]
there is no update on issue for a long time.
if it is still actual for you - feel free to reopen it
