### ISSUE TITLE
How to open dialog for new bookmark ?

### ISSUE THREAD

**Issue by sergeynilov** [dbeaver/dbeaver#10459]
Hello,
With DBeaver under kubuntu 18 I try to use bookmarks as it is written at
https://github.com/dbeaver/dbeaver/wiki/Bookmarks

But when some table is opened(I select 1st column and 1st row) : https://imgur.com/a/79W9217
I can not to open dialog to save this location as bookmark.
I press CTRL+d and nothing happened.

I found option to set hot key for bookmark dialog activating : https://imgur.com/a/jQ5aSXf
but setting CTRL+d  hot key did not help and no open dialog to save this location as bookmark.
I did not find any ( context ) menu options for this...

1) How can I do it?

2) If there is a way to freeze 1 column(id) at left part and always 
to have it visible while scrolling columns to right ?

Thanks!

**Comment by kseniiaguzeeva** [comment]
1 Please set focus on the table in DB Navigator tree and create bookmark via shortcut or Edit>Add bookmark
2 Yes: please right-click on the column header and select **Pin column** there
![Screenshot 2020-11-25 at 12 44 42](https://user-images.githubusercontent.com/51405061/100210437-0c7c6200-2f1c-11eb-9fe8-5cd240ada779.png)
If you what to keep the column pinned after closing the table, press Save filter settings button to the right of the top filter field of table Editor. The column will be pinned during current DBeaver session.
