### ISSUE TITLE
Pressing return between two lines of code temporarily deletes the next line

### ISSUE THREAD

**Issue by isak-kaz** [dbeaver/dbeaver#10450]
#### System information: 
- Operating system (distribution) and version: macOS 11.0.1 Big Sur
- DBeaver version: 7.2.5.
- Additional extensions: none

#### Connection specification:
- Database name and version: regardless of the database (issue on all connections)
- Driver name: N/A
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : NO

#### Describtion:
In SQL editor when trying to type new lines between two existing lines of code, temporarily deletes the last line. Sometimes its for couple of seconds, and sometimes its indefinitely until you type something. 

I have uploaded a yt video to demonstrate the issue: [YOUTUBE VIDEO LINK](https://youtu.be/F8tOEDYq5KU)

#### Steps to reproduce:

Open sql editor and type two lines of code, then try entering return(enter) key couple of times between the two. 

I have tried playing with the line numbers and folding  but nothing helped. 

![Screen Recording 2020-11-20 at 15 40 57](https://user-images.githubusercontent.com/60605981/99814847-d751c780-2b49-11eb-812e-aadb6d326c96.gif)

**Comment by Unknown-Guy** [comment]
Pretty sure it started happening after update to Big Sur

**Comment by PentKJ** [comment]
> Pretty sure it started happening after update to Big Sur

Definitely sarted after Big Sur update for me.

**Comment by isak-kaz** [comment]
> Pretty sure it started happening after update to Big Sur



> > Pretty sure it started happening after update to Big Sur
> 
> Definitely sarted after Big Sur update for me.

Yes, perhaps I did not emphasize this in my post, this is an issue only on Big Sur.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. Can be reproduced in Big Sur only

**Comment by wshoot** [comment]
Do we know when this fix is going to be released?  It is really bugging me

**Comment by isak-kaz** [comment]
> Do we know when this fix is going to be released? It is really bugging me

Yes we do, as you can see above it has been added to the version 7.3.1 milestone which is due December 21.

**Comment by akilovich** [comment]
As a Big Sur user myself, I feel your pain guys. DBeaver is built on top of the Eclipse platform, and Eclipse users on Big Sur experience [the same problem](https://bugs.eclipse.org/bugs/show_bug.cgi?id=569147). Eclipse developers already fixed the issue, and we expect that our next version 7.3.1 will contain the fix as well.

**Comment by rvwoens** [comment]
Not fixed in 7.3.1

**Comment by kseniiaguzeeva** [comment]
7.3.1 release will be 21.12.2020.

**Comment by rvwoens** [comment]
ok, so the early access is not the milestone release. 
![image](https://user-images.githubusercontent.com/97624/101892400-a04c6000-3ba3-11eb-9850-b596a94bdec5.png)

**Comment by akilovich** [comment]
Fixed in the scope of #10535. The fix is already available in the recent [EA build](https://dbeaver.io/files/ea/).

**Comment by PentKJ** [comment]
> Fixed in the scope of #10535. The fix is already available in the recent [EA build](https://dbeaver.io/files/ea/).

I'm happy again!

**Comment by akilovich** [comment]
Closed.

**Comment by isak-kaz** [comment]
> Closed.

Hey @akilovich thanks for this and while we are on the subject, do you know if dBeaver will work on the new M1 Macs?

**Comment by akilovich** [comment]
Hello @isak-kaz. I haven't tried it myself, but our users [reported](https://github.com/dbeaver/dbeaver/issues/10470) that it runs.

**Comment by koktszhozelca** [comment]
Hello, this issue is happening again.

DBeaver Version: 21.2.1.202109181446
Mac OS Version : Catalina 10.15.7

thanks

**Comment by sbreakey** [comment]
Also getting this on macOS Catalina. Raised a new ticket for it: https://github.com/dbeaver/dbeaver/issues/13966
