### ISSUE TITLE
Connection and filenames were being shown in some unknown format.

### ISSUE THREAD

**Issue by rrkjonnapalli** [dbeaver/dbeaver#10455]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.2.0
- Additional extensions

I tried following these:

https://dbeaver.com/docs/wiki/Reset-UI-settings/
https://dbeaver.com/docs/wiki/Reset-workspace/

I reinstalled many times, still it's same.

![image](https://user-images.githubusercontent.com/25339028/99836723-86af8e00-2b8c-11eb-9e30-45dec3524187.png)

![image](https://user-images.githubusercontent.com/25339028/99836632-68e22900-2b8c-11eb-94c5-b23c6f075a57.png)

**Comment by kseniiaguzeeva** [comment]
Please, tell what locale you use.

**Comment by rrkjonnapalli** [comment]
![image](https://user-images.githubusercontent.com/25339028/100216116-eb296f00-2f37-11eb-92f0-6bd8cfb9fce3.png)

**Comment by rrkjonnapalli** [comment]
Issue was solved for me.

I had to apply Theme as classic in the Appearance section restart once. For any other theme it's showing labels as mentioned above. Not sure if this is the problem only with my machine.

**Comment by kseniiaguzeeva** [comment]
I'm glad you have found the way to solve the issue!

**Comment by rrkjonnapalli** [comment]
New connection popup screen was not solved.
