### ISSUE TITLE
Problem creating a data base

### ISSUE THREAD

**Issue by MestreALMO** [dbeaver/dbeaver#10461]
I can't create a new data base, i keep getting a error message. 

I right click with the mouse and do the following:
![Screenshot_1](https://user-images.githubusercontent.com/29152190/99924356-bd1a1400-2d18-11eb-8d0e-695eac965560.png)
Then i get this error message:
_"Object create not available in simple view mode"_
![Screenshot_2](https://user-images.githubusercontent.com/29152190/99924365-c905d600-2d18-11eb-8479-a0e913d0d4b6.png)

What can I do to fix this? Searching around i not even found something about a "simple view mode".

**Comment by malthenpaur** [comment]
Hello I also had same problem.Just right click-edit connection-navigator view and change to advanced.

**Comment by uslss** [comment]
Thanks for the report.

**Comment by MestreALMO** [comment]
> Hello I also had same problem.Just right click-edit connection-navigator view and change to advanced.

Thank you, that helps a lot

**Comment by masoodaslami** [comment]
I am facing the same error in version 7.3.4

<img width="1437" alt="Screen Shot 2021-02-07 at 01 10 43" src="https://user-images.githubusercontent.com/24816479/107129225-87310880-68e1-11eb-8000-7c4eaf759733.png">

**Comment by Matheus8174** [comment]
> Hello I also had same problem.Just right click-edit connection-navigator view and change to advanced.

Tanks for the help

**Comment by gilbertttsubay** [comment]
Sorry i dont see the answer here @malthenpaur .
![image](https://user-images.githubusercontent.com/35297439/129209491-0cea3c26-70e7-4cdd-80df-82938d54d31f.png)
where is the navigatior view?

**Comment by jayampathim** [comment]
Please check this out.
<img width="1177" alt="Screen Shot 2021-10-13 at 12 17 03 AM" src="https://user-images.githubusercontent.com/3082942/136946580-7b29d3fa-3059-4e9e-ba57-e815da9bdca0.png">
