### ISSUE TITLE
F4 key not opening Package declaration code in Oracle DB (Dbeaver v 7.2.5

### ISSUE THREAD

**Issue by arunmuralik** [dbeaver/dbeaver#10468]
#### System information: 
- Windows 10
- 7.2.5
- Additional extensions

#### Connection specification:
- Oracle
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
While clicking F4 with a package in its owner schema, no action is happening

**Comment by uslss** [comment]
Cannot reproduce it. 
Could you provide a video that shows an issue?

**Comment by arunmuralik** [comment]
Issue seems to be present in a specific database instance for me. When I tried to describe the package in another Oracle database using F4 key, it just worked fine. I don't have any other editors to try the same object in that database itself. Guess it is ok to resolve the ticket.

Thanks,
Arun
________________________________
