### ISSUE TITLE
script create

### ISSUE THREAD

**Issue by gamarobert** [dbeaver/dbeaver#10469]
OS: MacOSx 10.15.16
DBeaver 7.2.5
Database: Sybase ASE 15.7

I am coming from sqlDBX and there is a feature I really miss. In sqldbx I was able to right click on the stored procedure or table and there would be a 'script create' function. This would open up the scripted sp or table along with a drop if exists added to the top of the script. Does anything like that exists in dbeaver. I notice the workflow right now seems like I have to view procedure and then open in sql console.

**Comment by kseniiaguzeeva** [comment]
I hope DBeaver meets all your needs!
Procedure: 
open a procedure in Object Editor (double click on it) and go to Source tab
![Screenshot 2020-11-24 at 11 02 57](https://user-images.githubusercontent.com/51405061/100065289-a96bcc00-2e44-11eb-83de-583025ca18f2.png)

Table:
a) select Generate SQL>DDL in a table context menu in DB Navigator
![Screenshot 2020-11-24 at 10 57 49](https://user-images.githubusercontent.com/51405061/100065075-64479a00-2e44-11eb-8255-351fe3394efb.png)
b) open table Properties in Object Editor and go to DDL tab.
![Screenshot 2020-11-24 at 10 58 05](https://user-images.githubusercontent.com/51405061/100065126-788b9700-2e44-11eb-9713-44c98bc3b5e0.png)

**Comment by gamarobert** [comment]
Hmm its going to take some getting used to but thank you!
I have one more question if thats okay. I have been looking around and couldnt find this exactly but is there anyway to show how many rows a table has right next to it in the navigation. I attached a screenshot to show what i mean. the numbers inside the parenthesis are the number of rows that table has.
<img width="207" alt="Screen Shot 2020-11-24 at 2 09 18 PM" src="https://user-images.githubusercontent.com/31262157/100157049-c90fee00-2e5e-11eb-9976-6b6f07efca18.png">

**Comment by kseniiaguzeeva** [comment]
We show it a little differently
1. At first enable it via Windows>Preferences>Metadata (It's an expensive property and we do not show it by default)
![Screenshot 2020-11-25 at 13 31 16](https://user-images.githubusercontent.com/51405061/100216796-c4613d80-2f23-11eb-8514-40da2d591ab1.png)

2. Then open Properties view via Windows>Show view
![Screenshot 2020-11-25 at 13 33 28](https://user-images.githubusercontent.com/51405061/100216611-87954680-2f23-11eb-8148-bc37e0b04619.png)

3. Clock on table name in DB Navigator and you will see its statistic in Properties window

P.S. Also you can see table sizes in DB Navigator tree near table names. Enable it:
![Screenshot 2020-11-25 at 13 32 26](https://user-images.githubusercontent.com/51405061/100216544-751b0d00-2f23-11eb-8049-4a73258c346b.png)

**Comment by gamarobert** [comment]
Thank you so much, I appreciate the help!
