### ISSUE TITLE
UI Component Reversed

### ISSUE THREAD

**Issue by iambudi** [dbeaver/dbeaver#10462]
#### System information: 
- MacOS Big Sur
- DBeaver version 7.3

#### Connection specification:
Not related

#### Describe the problem you're observing:
Text Editors Preferences displayed in reverse as the screenshoot below.
![image](https://user-images.githubusercontent.com/31809529/99929774-0605b300-2d81-11eb-94d8-4401400d9012.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by akilovich** [comment]
Fixed in the scope of #10535.

**Comment by iambudi** [comment]
@akilovich Confirm it works nicely on 7.3.1 EA
![image](https://user-images.githubusercontent.com/31809529/101910817-1081d280-3bf2-11eb-810a-0e5a2bc4bf94.png)
