### ISSUE TITLE
Jar files sign

### ISSUE THREAD

**Issue by CodingInvoker** [dbeaver/dbeaver#10472]
## Problem description

I am using macos 10.15.7. And my dbeaver version is the latest version by now(7.2.5)
When I try to install dbeaver extension for sshj from `Help` --> `Instanll new software`, it seems like there is an official plugin for it as shown in screenshot below:

![image](https://user-images.githubusercontent.com/71058225/100056911-69ffa880-2e61-11eb-972c-bc60e15ab062.png)

However when it gets to the final validation stage there is a security warning as shown below:

![image](https://user-images.githubusercontent.com/71058225/100055777-5b17f680-2e5f-11eb-8e7c-d11e34326848.png)

## Suggested Solution

I reckon this plugin is official, do you think it is better to remove this security warning for it? Or there is actually a security risk?

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. It will work differently in 8.0 DBeaver version

**Comment by serge-rider** [comment]
We need to sign all jar files in all DBeaver distributions.
One problem is that some of these jars are 3rd party artifacts, generally we can't sign them with out certificate..

**Comment by serge-rider** [comment]
In current versions we sign all jars but 3rd party jars (including Eclipse ones).
