### ISSUE TITLE
Force truncate checkbox not checking

### ISSUE THREAD

**Issue by brentlobbezoo** [dbeaver/dbeaver#10473]
### System information: 
**- Operating system (distribution) and version**
MacOS Catalina, version 10.15.7 (19H15)
**- DBeaver version**
7.2.5
**- Additional extensions**
_None_

#### Describe the problem you're observing:
The force truncate checkbox cannot be checked anymore

#### Steps to reproduce, if exist:
Select one or multiple tables. Right click, go to tools > truncate. In the settings menu on the opened pop-up, the checkbox next to force doesn't check.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. Cannot reproduce. It may have been fixed as part of ticket https://github.com/dbeaver/dbeaver/issues/10279. Please try EA version https://dbeaver.io/files/ea/

**Comment by brentlobbezoo** [comment]
@kseniiaguzeeva EA 7.3.0. seems to fix the issue!

**Comment by kseniiaguzeeva** [comment]
Great!
