### ISSUE TITLE
DBeaver support for M1

### ISSUE THREAD

**Issue by seabass9** [dbeaver/dbeaver#10470]
Just tested DBeaver 7.2.5 on a MacBook Air M1 with BigSur 11.0.1 and it doesn't start. Seems like the first time it ran Rosetta2 but doesn't produce any output. Open to helping out with testing to support this as a Universal app or a working Rosetta2 translation.

**Comment by p91paul** [comment]
Not a Dbeaver developer here, but did you try to report a bug to Apple as well? I don't know if they even accept bug reports. Given the fact that Rosetta 2 very point is to run unmodified x86 programs, they should be the one fixing it.

**Comment by akilovich** [comment]
Hello. Some of our users who updated their x86 macs to Big Sur experience [similar problems](https://github.com/dbeaver/dbeaver/issues/10345) as well. So I'm wondering, are you trying to run the dmg version of DBeaver? If so, I could suggest you install our pkg version to see if it helps.

**Comment by seabass9** [comment]
PKG version runs!
Yes, I had just tried the DMG version and was also wondering about that and the Java version, but just trying the pkg version worked, thanks!

**Comment by deblanco** [comment]
> PKG version runs! Yes, I had just tried the DMG version and was also wondering about that and the Java version, but just trying the pkg version worked, thanks!
> […](#)
> On Nov 24, 2020, 12:37 AM -0800, Nikita Akilov ***@***.***>, wrote: Hello. Some of our users who updated their x86 macs to Big Sur experience similar problems as well. So I'm wondering, are you trying to run the dmg version of DBeaver? If so, I could suggest you install our pkg version to see if it helps. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I can confirm it, it works in my MBP M1!

**Comment by akilovich** [comment]
That's actually fantastic news!

**Comment by scudluncher** [comment]
Thank you. I also tried with "pkg" version, and it worked!

**Comment by lutel** [comment]
Does DBeaver runs natively on M1?

**Comment by danielporto** [comment]
It seems that is crashing perhaps due to system update.
![image](https://user-images.githubusercontent.com/1652891/111471681-0dcad800-8721-11eb-8326-fb7ed307da0f.png)

Any timeline on a native version?

**Comment by flambchap** [comment]
Since DBeaver is an Eclipse RCP application, we need to wait for the SWT team at Eclipse to [provide support for Apple Silicon](https://bugs.eclipse.org/bugs/show_bug.cgi?id=565690). After that, we'll be able to provide a macOS/ARM version as well.

**Comment by JoelVenable** [comment]
The RCP paged linked now indicates there are early access builds available.  Is it a big lift to compile an alpha version?

**Comment by quicksnap** [comment]
I created a new ticket here https://github.com/dbeaver/dbeaver/issues/12441

**Comment by shaykr** [comment]
Can you post a link to the PKG version?

**Comment by flambchap** [comment]
@shaykr We don't build PKG versions anymore. However, the dmg version works ok with Rosetta 2.
