### ISSUE TITLE
Even if restrictions are added to the query statement, clicking the filter button next to the column name in the result set will still cause a full table scan

### ISSUE THREAD

**Issue by wmdeepsea** [dbeaver/dbeaver#10488]
#### System information: 
- Operating system (distribution) and version
    windows 7
- DBeaver version
  DBeaver 7.2.5

#### Connection specification:
- Database name and version
  oracle 11g
- Driver name
   oracle.jdbc.OracleDriver（ojdbc6.jar）

#### Describe the problem you're observing:
With restrictions added, the result set of the query is only one piece of data. If you click the filter button next to the column name in the result set, the SQL for the full table scan of the group by column will also be executed;

#### Steps to reproduce, if exist:
1.Select  * from table_name where column = 'ABCD';
2.Click the filter button next to the column name in the result set
3.In Oracle, an unrestricted full table scan sql will be generated;
   for example: Select column,count(*) from table_name Group by column

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by uslss** [comment]
will be implemented in the scope of #13020
