### ISSUE TITLE
Generate SQL INSERT dialog improvement

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#10489]
The INSERT INTO statement in the generated SQL, that we can select in the data viewer for the columns, contains values for all columns.

 But sometimes we want to exclude auto-generated columns from this statement.

![2020-11-24 15_51_51-Window](https://user-images.githubusercontent.com/45152336/100198781-57db4400-2f0d-11eb-9047-272084226746.png)

We need to add an option for this.

**Comment by LonwoLonwo** [comment]
Implemented for Generated SQL INSERT dialogue in table data viewer.
Also tabs "Show comments" and "Show permission" removed from all PostgreSQL dialog (like UPDATE, SELECT) except DDL dialogue. 
![2020-11-27 13_52_45-Window](https://user-images.githubusercontent.com/45152336/100588735-41fdc280-3303-11eb-8a63-7d8f2935db09.png)

**Comment by uslss** [comment]
verified
