### ISSUE TITLE
dbeaver server output tab seems to not support postgres raise notice with multiple-lines of output

### ISSUE THREAD

**Issue by ckottmyer** [dbeaver/dbeaver#10485]
OS: Mac
Postgres: 9
Dbeaver: Version 7.2.2.202010041557 (community edition)

I typically execute a lot of stored procs in postgresql.  These stored procs can use the equivalent of a print or echo statement via the raise notice command.  raise notice takes as an argument a string with single or multiple lines and outputs it to standard out.  This is all good in dbeaver when I have a single line of output it will output the entire string to server output tab, but when I have multi-line output it discards everything after the first line.  Let's say I have many lines of output, say a SQL insert statement generated dynamically.  A good example would be the below:

insert into table (values)
select *
from table2
where some conditions

It will show in the server output tab only the following:

insert into table(values)

and discards the entire select portion of the statement.  This makes logging significantly harder as the string in raised notice isn't pass through.  Therefore becomes significantly less meaningful.  Is there an option to show the entire raise notice string in the server output tab or is this a current limitation of dbeaver?

**Comment by kseniiaguzeeva** [comment]
Is it possible to give a full query to reproduce? Looks like an enhancement is needed

**Comment by ckottmyer** [comment]
This is a really dumb example, but it showcases the issue I think:

create function using this:
`
CREATE OR REPLACE FUNCTION example_with_random_sql()
RETURNS INTEGER
AS $$

declare 
	some_random_sql varchar;
	some_random_output varchar;
begin 
	
	some_random_sql := '
		select 1
		union
		select 2
		union
		select 3
		union
		select 4
		union
		select 5
	';

	raise notice 'I WILL FAIL TO PRINT SQL STATEMENT: %', some_random_sql;
	
	execute some_random_sql into some_random_output;

	raise notice 'I WILL FAIL TO PRINT THIS SQL OUTPUT: %', some_random_output;

	return 0;

END;
$$ LANGUAGE plpgsql;
`

run using this:
`
select example_with_random_sql()
`

output is:
`
I WILL FAIL TO PRINT SQL STATEMENT:
I WILL FAIL TO PRINT THIS SQL OUTPUT: 1
`

expected output is:
`
I WILL FAIL TO PRINT SQL STATEMENT:
select 1
		union
		select 2
		union
		select 3
		union
		select 4
		union
		select 5

I WILL FAIL TO PRINT THIS SQL OUTPUT: 1
2
3
4
`

Something of that nature, add or subtract some white space.  Not suggesting this is the common use case, but think it serves it's purpose well enough.

**Comment by kseniiaguzeeva** [comment]
Thank you for this example. My output shows:
I WILL FAIL TO PRINT SQL STATEMENT: 
select 1
union
select 2
union
select 3
union
select 4
union
select 5

I WILL FAIL TO PRINT THIS SQL OUTPUT: 3

**Comment by serge-rider** [comment]
Multiline output works ok.
Problem with multiple rows dump is not a bug, it is how PostgreSQL works:
> If multiple rows are returned, only the first will be assigned to the INTO variable.

https://www.postgresql.org/docs/9.1/plpgsql-statements.html

**Comment by ckottmyer** [comment]
Just cross validated with pgadmin4 to see the behavior.  You are correct, just gave a bad example for the second part.  For me specifically, the multi-line output doesn't work.  Maybe I have a bad settings or maybe it's specific to the Mac version.  I get the following still:

I WILL FAIL TO PRINT SQL STATEMENT:
I WILL FAIL TO PRINT THIS SQL OUTPUT: 1

Running the following dbbeaver: Version 7.3.3.202101161839
Running on MacOSX: MacPro 2015 - Catalina.

Here is a screen shot, the output tab shows the result:
<img width="841" alt="Screen Shot 2021-01-19 at 10 55 30 AM" src="https://user-images.githubusercontent.com/45637572/105059103-ef0fd400-5a44-11eb-93b6-28f27ae19bae.png">

**Comment by kseniiaguzeeva** [comment]
By some reason I cannot reproduce it in DBeaver 7.3.3, PostgreSQL 9. Could you please try the latest version too? https://dbeaver.io/download/

**Comment by uslss** [comment]
there is no update on issue for a long time.
if issue is still actual for you - feel free to reopen it
