### ISSUE TITLE
auto-complete when sub-select looks for wrong table's columns to offer

### ISSUE THREAD

**Issue by mbelvadi2** [dbeaver/dbeaver#10487]
#### System information: 
Windows 10
- DBeaver version 7.2.5
- Additional extensions - none

#### Connection specification:
- sqlite3 local db file in C drive

#### Describe the problem you're observing:
When typing a select query on one table, where one part of the query involved a nested select, after closing the parenthesis on the sub-select and continuing to type more WHERE conditions that refer back to the main table, dbeaver's auto complete is offering me column name choices based on the columns of the table in the sub-select, not the top level table.
I do a lot of work with a lot of sqlite files with multiple tables within each sqlite db, and this happens every time with every db, so this is just one example:

> select distinct oclc, callnumber, callnumber_050 from novanet_clean nc where callnumber not in (select distinct callnum from sort_good_nv_all sgna ) and callnu

what I'm typing at the end there is supposed to be the name of another column in novanet_clean, but dbeaver starts offering me matching column name choices from sort_good_nv_all instead. See screenshot.
![Screenshot 2020-11-24 185423](https://user-images.githubusercontent.com/28821980/100161282-81ea2300-2e87-11eb-9447-c24ae56e0e00.jpg)

#### Include any warning/errors/backtraces from the logs
There's no error message or warnings so nothing in the logs of relevance.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. The same situation with auto-complete in parenthesis (auto-complete offers objects from the table before parenthesis).

To reproduce please run in SQLite:
select distinct CustomerId , FirstName , LastName from Customer where LastName not in (select distinct _(press Ctrl+Space here)_ from Employee e) and _(press Ctrl+Space here)_

**Comment by LonwoLonwo** [comment]
Hello. 
Unfortunately, the problem has been known for a time. See link: https://github.com/dbeaver/dbeaver/issues/7768#issuecomment-591573519
Сurrent solutions to this problem will slow down the SQL Editor. But we will definitely solve this problem in the future.
For now I close this as duplicate.
https://github.com/dbeaver/dbeaver/issues/7768
