### ISSUE TITLE
Action icons do not work on Linux

### ISSUE THREAD

**Issue by akilovich** [dbeaver/dbeaver#10480]
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04, WSL2, gnome
- DBeaver version 7.3.0 EA

#### Describe the problem you're observing:

There are no action icons when the corresponding setting is on.

**Comment by akilovich** [comment]
The problem turns out to be a bit more interesting. There is no horizontal scrollbar in the database navigator tree no matter how you shrink the navigator area, but if try to find out programmatically if the scrollbar is visible, it always is. Quite strange.

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
