### ISSUE TITLE
When I use the dbeaver interface to give users batch authorization, the statements are executed one by one

### ISSUE THREAD

**Issue by ZhouJiaZhi** [dbeaver/dbeaver#10494]
#### System information: 
- DBeaver version ： 7.2.5.202011152110

#### Connection specification:
- Database name and version ： Mysql  5.7.31

### bug
When I use the dbeaver interface to assign authorization to users in batches, the statements are executed one by one. I think that these statements are either executed all successfully or rollback. They should be executed in one transaction. Otherwise, if there is a statement error in the middle, then there will be partial authorization.

<img width="906" alt="截屏2020-11-25 下午7 42 32" src="https://user-images.githubusercontent.com/20750357/100223360-5d10b100-2f56-11eb-8a96-931e26002175.png">

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea.
https://www.mysqltutorial.org/mysql-grant.aspx/

**Comment by serge-rider** [comment]
All DDL/grant statements are executed in the single transaction. Rollback is performed on any error and commit on success.

**Comment by kseniiaguzeeva** [comment]
verified
