### ISSUE TITLE
AS400: Tables with swedish characters does not display columns

### ISSUE THREAD

**Issue by reager** [dbeaver/dbeaver#10490]
#### System information: 
- Operating system (distribution) and version Win 10
- DBeaver version Version 7.2.5.202011152110
- Additional extensions None

#### Connection specification:
- Database name and version IBM AS/400
- Driver name com.ibm.as400.access.AS400JDBCDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Open properties on a table with special characters (å, ä, ö) for example, no columns are displayed in the Columns tab and all data is displayed as readonly with message "Readonly: No corresponding table column".

#### Steps to reproduce, if exist:
Connect to an AS/400 database
Open properties on a table with special characters as swedish å, ä, ö
Look at columns tab.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. Unfortunately we do not have environment to test. We will be glad if you can help us with this.

**Comment by reager** [comment]
Im not able to give you any test environment. 

But I can give you another example. The database and its tables seems to be defined with danish characters, so for example if a table is called FØRETAG, it is returned as FÖRETAG for me. I can query the FØRETAG table directy and see its tables and defintions from the qsys2.syscolumns table, but I guess that DBeaver is querying for FÖRETAG which doesnt match the actual name of the table and returns no tables in the properties view.

**Comment by kseniiaguzeeva** [comment]
Unfortunately cannot reproduce in my environment
![Screenshot 2020-12-14 at 10 36 14](https://user-images.githubusercontent.com/51405061/102053119-44c6e000-3df8-11eb-9db7-707a68ae76fa.png)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
if it is still actual for you - feel free to reopen it with an additional info
