### ISSUE TITLE
dbeaver will report an error when executing mysql prepared statement

### ISSUE THREAD

**Issue by ZhouJiaZhi** [dbeaver/dbeaver#10493]
<!--
#### System information: 
- Operating system (distribution) and version：macos 10.15.4
- DBeaver version ： 7.2.5.202011152110

#### Connection specification:
- Database name and version ： Mysql 5.7.31
- Driver name：
<img width="427" alt="截屏2020-11-25 下午7 24 32" src="https://user-images.githubusercontent.com/20750357/100221602-da86f200-2f53-11eb-99d0-4c9a8710eeca.png">
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
When I execute the MySQL prepared statement in dbeaver, an error will be reported. I execute the MySQL prepared statement through the mysql command line successfully.
#### Steps to reproduce, if exist:
1.Please see the steps in the picture below, an unknown prepared statement error will be reported when executed
![image](https://user-images.githubusercontent.com/20750357/100221231-5b91b980-2f53-11eb-9e0a-7af9806c7e23.png)
2.The same sql statement I use the command line to connect, is correct
![image](https://user-images.githubusercontent.com/20750357/100222189-b4158680-2f54-11eb-9076-4f54d3a11395.png)

**Comment by ZhouJiaZhi** [comment]
Please see the steps in the picture below, an unknown prepared statement error will be reported when executed
![image](https://user-images.githubusercontent.com/20750357/100222610-4e75ca00-2f55-11eb-94c6-fe931714abd4.png)

**Comment by ZhouJiaZhi** [comment]
The same statement can be executed normally when I use the mysql command line
![image](https://user-images.githubusercontent.com/20750357/100222743-8250ef80-2f55-11eb-80dd-79d935760f09.png)

**Comment by ZhouJiaZhi** [comment]
#### System information: 
- Operating system (distribution) and version：macos 10.15.4
- DBeaver version ： 7.2.5.202011152110

#### Connection specification:
- Database name and version : Mysql  5.7.31
- Driver name 
<img width="386" alt="截屏2020-11-25 下午7 38 49" src="https://user-images.githubusercontent.com/20750357/100222979-d956c480-2f55-11eb-8502-0a42d81a9bcb.png">

- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

**Comment by kseniiaguzeeva** [comment]
Could you please write a query as a text to reproduce? I receive another error when execute the statement from the screenshots

**Comment by ZhouJiaZhi** [comment]
@kseniiaguzeeva 
Hi, I can't reproduce this either.
But I found another bug. I want to execute the insert statement, but he executed the line of code I commented out
![image](https://user-images.githubusercontent.com/20750357/101471917-de1e6e00-3982-11eb-9d88-e27f97974b43.png)

**Comment by kseniiaguzeeva** [comment]
Most probably you put the cursor on the line with the comment. It is expected to show the comment in the ResultSet. Empty line is used as a delimiter. Put the cursor on the insert statement, above or under to execute.

Also you can disable the option to use blank lines as a delimiter. Go to SQL Editor>SQL Processing for it.
![Screenshot 2020-12-08 at 13 40 43](https://user-images.githubusercontent.com/51405061/101473821-60933780-395b-11eb-8ecd-bedb0a1bfd9e.png)
