### ISSUE TITLE
Add SQL Console button to the top toolbar

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10495]
The button on the upper toolbar will open the SQL Console, which works the same as the SQL Editor, but without ability to save it.

**Comment by serge-rider** [comment]
Done

**Comment by kseniiaguzeeva** [comment]
- Is it possible to remove submenu **file** from SQL Console context menu?
- Could you rename **Read data in SQL Console**? Because SQL Editor window opens.
- Should SQL Console be added to the main SQL Editor menu?
- SQL Console button is not active on the top toolbar when the focus is in SQL Editor/Console window.
- SQL Console window opens from DB Navigator for a default database only.

**Comment by serge-rider** [comment]
1.  File menu still makes sense (for export/import actions)
2-6 fixed.

**Comment by kseniiaguzeeva** [comment]
2-5 fixed.
6 - SQL Console opens for a selected database, but for a default schema (can be reproduced in PostgreSQL, Greenplum)

**Comment by kseniiaguzeeva** [comment]
Separate ticket will be created for 6.
