### ISSUE TITLE
'DBeaver' received an X Window System error

### ISSUE THREAD

**Issue by yang445786754** [dbeaver/dbeaver#10500]
#### System information: 
- Ubuntu / MAC OS
- 7.4.2 / 7.4.0

#### Connection specification:
- Mysql 8.0
- SSH

#### Describe the problem you're observing:
An error occurred when I exported. 
The console gets these error message. 

#### Steps to reproduce, if exist:
1.excute sql
2.export result data 
#### Include any warning/errors/backtraces from the logs

(DBeaver:67864): Gdk-ERROR **: 11:16:01.474: The program 'DBeaver' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 102710 error_code 11 request_code 131 (MIT-SHM) minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by kseniiaguzeeva** [comment]
Could you please send log files?

**Comment by uslss** [comment]
there is no update on issue for a long time. 
if issue is still actual for you - feel free to reopen it
