### ISSUE TITLE
error：unknown database

### ISSUE THREAD

**Issue by Wx-Code** [dbeaver/dbeaver#10508]
我的连接地址是通过vpn连接的，但是使用该软件就不可以，我使用Navicat可以正常连接。
我不知道这是不是bug
_My connection address is connected through vpn, but it is not possible to use this software. I can connect normally with Navicat.
I don't know if this is a bug_
![image](https://user-images.githubusercontent.com/42227277/100354101-9155a180-302a-11eb-814c-7d3739af2b0b.png)

**Comment by uslss** [comment]
Is mentioned address used as host? Could you try to use 'localhost' instead?
BTW, what db do you use?
Could you provide steps to reproduce an issue?

**Comment by uslss** [comment]
there is no update on the issue.
If it is still actual for you - feel free to reopen it with an additional info
