### ISSUE TITLE
Cannot write square brackets in the script editor -- MacOS

### ISSUE THREAD

**Issue by rebecaruiz** [dbeaver/dbeaver#10503]
Hi guys, I found a strange issue in DBeaver for mac and I cannot find documentation about it.

I am using a standard Spanish ISO mac keyboard. When trying to write square brackets in the script editor, a contextual menu prompts and I have to copy the square brackets [ and ] from a text editor and then paste them into the script.

You can find attached screenshot. Thank you.
<img width="573" alt="Screenshot 2020-11-26 at 10 35 55" src="https://user-images.githubusercontent.com/18902012/100334386-ffbb4500-2fd3-11eb-8316-ba68926d220b.png">

### System information: 
- Operating system (distribution) and version: MacOS Catalina 10.15.7 (19H15)
- DBeaver version Version 7.2.5.202011152110
- Additional extensions No additional extensions

#### Describe the problem you're observing:

I am using a standard Spanish ISO mac keyboard. When trying to write square brackets in the script editor, a contextual menu prompts and I have to copy the square brackets [ and ] from a text editor and then paste them into the script.

#### Steps to reproduce, if exist:

In DBeaver for macOS, open the script editor and try to write square brackets.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. As a workaround please try to remove context tool shortcut
Window>Preferences>User Interface>Keys
![Screenshot 2020-12-07 at 17 33 58](https://user-images.githubusercontent.com/51405061/101363500-887a9080-38b2-11eb-91bb-27e1c8fd6479.png)

**Comment by flambchap** [comment]
Fixed. The standard shortcut for _Context tools_ on macOS is `Ctrl+V` now.

**Comment by kseniiaguzeeva** [comment]
verified
