### ISSUE TITLE
[PostgreSQL] GRANT Statement for procedures generated by DBeaver is incorrect

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#10501]
When we manually set the permissions for functions, it works correctly. 
But the list of functions also contains procedures for which the PROCEDURE keyword is used. 
Now the DBeaver is using the word FUNCTION incorrectly when assigning roles and for procedures as well. 
Need to fix it on "GRANT EXECUTE ON PROCEDURE".

![2020-11-26 10_13_58-DBeaver Enterprise 7 3 0 - test_user](https://user-images.githubusercontent.com/45152336/100320559-6475a000-2fd2-11eb-8602-3795f928f0b2.png)

Steps:
1. Open the tab Roles, choose one.
2. Open "Permission" tab.
3. Select any schema with procedures, open the tab Functions.
4. Select any procedure and change the permissions, then press the save button.
5. Script is incorrect which results in an error.

**Comment by LonwoLonwo** [comment]
Also REVOKE statement for existing permissions uses a specific procedure/function names, not the usual one, which leads to a script execution error
![2020-11-27 00_42_57-DBeaver Enterprise 7 3 0 - test_user](https://user-images.githubusercontent.com/45152336/100393052-8c541a80-3049-11eb-9e66-a0872aff01ec.png)

**Comment by LonwoLonwo** [comment]
Fixed in 7.3.1

**Comment by uslss** [comment]
verified
