### ISSUE TITLE
How to expand and activate left part with current path of active object?

### ISSUE THREAD

**Issue by PetroGromovo** [dbeaver/dbeaver#10506]
Hello,
When I open DBeaver 7.2.1 by default tables from last session are visible, but Connection->Databases at 
left panel is closed. If there a way by current table to expand Connection->Databases->Tablename->tables 
at left panel? Or say by any currently opened item To expand and activate left part with current path
of active object?

Thanks!

**Comment by uslss** [comment]
Hi @PetroGromovo ,
if it is needed to find e.g. table that is opened in the editor in navigator you can use Link with editor button in Database navigator
![image](https://user-images.githubusercontent.com/31996417/100573317-93e51f00-32e8-11eb-89bf-95b100db9b82.png).
Also you can enable "Expand navigator tree on connect" in Preferences:
![image](https://user-images.githubusercontent.com/31996417/100573531-0fdf6700-32e9-11eb-9009-d70c5e5bc3a1.png)

If it doesn't resolve your issue, feel free to create a feature request about it.
Best regards :)
