### ISSUE TITLE
Empty .dbeaver folders created in eclipse projects

### ISSUE THREAD

**Issue by sebthom** [dbeaver/dbeaver#10507]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows [Version 10.0.18363.1139]
- DBeaver version: 7.2.5.202011160809
- Additional extensions

#### Describe the problem you're observing:
I installed dbeaver into Eclipse IDE for Java Developers 2020-09 (4.17.0). Now dbeaver generates empty .dbeaver folders in Java projects. When I delete them they get recreated.

#### Steps to reproduce, if exist:
Checkout https://github.com/OpenAPITools/openapi-generator as Maven project in Eclipse:
![image](https://user-images.githubusercontent.com/426959/100353494-dbb92d00-2fee-11eb-9e1a-6b220f3049f6.png)

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce. DBeaver creates the new .dbeaver folder with credentials and data source files. What does your project contain?

**Comment by sebthom** [comment]
I did not create any data sources or credentials yet. I just installed dbeaver plugin and the folders start appearing.

**Comment by kseniiaguzeeva** [comment]
Still cannot reproduce. Could you please tell exact steps to reproduce (1. create/import project 2. install DBeaver extension 3. Open a project via ...?)

**Comment by sebthom** [comment]
I have an existing workspace with maven projects that earlier where cloned from github within eclipse and then imported as maven project. 
I installed dbeaver in eclipse and opened this workspace. now in these existing projects the .dbeaver folders are generated. when I delete the .dbeaver folder in a project and press F5 in the project explorer to refresh. the .dbeaver folder is there again.

**Comment by sebthom** [comment]
I am also getting the .dbeaver folder in regular Eclipse projects (non-Maven). e.g. when I clone/import this https://github.com/vegardit/activemq-artemis-dynatrace-plugin/

![image](https://user-images.githubusercontent.com/426959/102396668-0dfdef00-3fdd-11eb-8caa-2d646dcf3b7a.png)

This is the content of the .project file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>activemq-artemis-dynatrace-plugin</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
	</buildSpec>
	<natures>
	</natures>
</projectDescription>

```

**Comment by sebthom** [comment]
I just upgraded from Eclipse 2020-09 to 2020-12 and dbeaver 7.2.5 to 7.3.0 and the issue persists.

**Comment by seaview1990** [comment]
I have a similar issue. .dbeaver folder is being created in projects I believe are not related to DBeaver. When I first launch Eclipse with no projects open in the Java perspective, and then switch to the DBeaver perspective, all of my Java and other Eclipse projects are opened although they do not all contain a .dbeaver folder. I can close those projects in the Java perspective and then DBeaver does not open them again. It only happens the first time I go into the DBeaver perspective. Does DBeaver automatically open any projects that contain files (e.g., .sql, .xml, .project) it is associated with? I use Eclipse 2020-03, DBeaver 7.3.3.

**Comment by sebthom** [comment]
I upgraded dbeaver to 7.3.3 and still have the same issue. The .dbeaver file is created in all projects no matter the project nature.

Again, the problem appears the moment I install dbeaver, without having done any dbeaver or database related configurations.

@serge-rider is there anything else we can do to figure out the cause?

**Comment by kseniiaguzeeva** [comment]
1. Could you send a video with steps to reproduce? 
2. Please also copy Eclipse configuration info (Eclipse>About eclipse>Installation details>Configuration)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info
