### ISSUE TITLE
the comments can't show in the entity relationship diagram(ER Diagram)

### ISSUE THREAD

**Issue by chengjf0526** [dbeaver/dbeaver#10502]
#### System information: 
- Microsoft Windows 10 1909
- DBeaver version 7.2.5.202011152110

#### Connection specification:
- Database name and version: Oracle 11.2.0.1
- Driver name oracle.jdbc.OracleDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
the command can't show in the ER图(实体关系图)

#### Steps to reproduce, if exist:
1.choose a schema or a table
2.open the ER图(实体关系图)
3.set “Attribute styles”, choose "Commands"
4.no command show in the ER图(实体关系图)
5.flush the ER图, some table can show the command in some time

#### Include any warning/errors/backtraces from the logs
no any log
![无标题](https://user-images.githubusercontent.com/6092176/100331775-8b03fd00-300b-11eb-9682-dade0eadabbc.png)

**Comment by uslss** [comment]
Hi @chengjf0526, can you clarify what do you mean by "commands"?

**Comment by chengjf0526** [comment]
@uslss Sorry, I made a mistake. It should be "Comments"

**Comment by uslss** [comment]
@chengjf0526 is issue still reproducible for you against the recent version(7.3.3)?

**Comment by chengjf0526** [comment]
@uslss is issue still reproducible in my against the recent version(7.3.3 and 7.3.4).
In the recent version, the 'Comments' of table is show now, but the 'Comments' of the column is not show.

**Comment by uslss** [comment]
thanks for clarification

**Comment by LonwoLonwo** [comment]
Hello @chengjf0526 
Unfortunately i can't reproduce with DBeaver 21.0.0 and Oracle 12.
Have you tried using refresh button?
![2021-03-02 17_39_30-DBeaver Enterprise 21 0 0 - TEST734](https://user-images.githubusercontent.com/45152336/109665072-dbe13f80-7b7e-11eb-9ec2-c170342dbb8a.png)

**Comment by LonwoLonwo** [comment]
There is no updates for long time.

Feel free to reopen the ticket, if the problem occurs again.
