### ISSUE TITLE
[Request] LiteDB connector

### ISSUE THREAD

**Issue by MostHated** [dbeaver/dbeaver#10518]
Hey there,
    I did a search through issues and noticed no one had ever mentioned LiteDB, so I would like to make a request and see if it would be possible to have this added as a compatible database? It's been around for 5-6 years and has nearly 5.5k stars

https://github.com/mbdavid/LiteDB

<details>
<summary>The current options for a graphical editor are extremely limited. The only working GUI tool is one created by the same creator as LiteDB.</summary>

 <img src="https://camo.githubusercontent.com/61465032cd9df0ccb7c0ff4a2d4f1cf772cdaa14/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f454f58564b7674583041412d6c64793f666f726d61743d6a7067266e616d653d6d656469756d" width="500">

</details>

Documentation and API are found here: http://www.litedb.org/docs/

I appreciate your time and consideration.
Have a great holiday!
-MH

**Comment by serge-rider** [comment]
Unfortunately we can't add LiteDB support in DBeaver, 

LiteDB is .NET embedded database, it doesn't have any API but C# .
DBeaver needs Java API or some sort of remote server connectivity (tcp/ip) in order to connect to databases.

**Comment by MostHated** [comment]
Ah, darn, I didn't think of that, my apologies. I appreciate you taking the time to look into it.
