### ISSUE TITLE
DBeaver 7.2.5 dosn't show all sections for table in PostgreSQL DB

### ISSUE THREAD

**Issue by tvgis** [dbeaver/dbeaver#10517]
Hello!
DBeaver 7.2.5 dosn't show all sections for table in PostgreSQL DB.

In my table there is 2 sections, but only one is shown. The first one.
In version 7.2.4 it's okey.

**Comment by LonwoLonwo** [comment]
Hello @tvgis 
Thank you for bug report!
The problem was fixed not so long ago in this ticket https://github.com/dbeaver/dbeaver/issues/10426
Fix will be available in release 7.3.0 at Monday (30.11)

**Comment by LonwoLonwo** [comment]
If the problem is still actual after downloading the new version, then you are free to create a new ticket then.
