### ISSUE TITLE
Mac OS Big sur SQL editor scrolling issue

### ISSUE THREAD

**Issue by rvwoens** [dbeaver/dbeaver#10523]
#### System information: 
- Operating system Mac OS Big Sur
- DBeaver version 7.2.5.202011152110

#### Describe the problem you're observing:
After updating to big sur, the editor window does not show the correct information after pressing enter or
inserting lines. The bottom part of the screen is not updated so it looks like the line below the current line is gone. But clicking on it reveals the original line.
This is probably related to eclipse issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=568813

#### Steps to reproduce, if exist:
position your cursor inside some text
![Screenshot 2020-11-27 at 10 19 39](https://user-images.githubusercontent.com/97624/100432598-19bf5b00-309a-11eb-9c88-267104b73f68.png)
now press enter
![Screenshot 2020-11-27 at 10 20 48](https://user-images.githubusercontent.com/97624/100432923-92beb280-309a-11eb-94b5-735dbf2d2530.png)
the 'where' line is gone.
![Screenshot 2020-11-27 at 10 21 28](https://user-images.githubusercontent.com/97624/100432781-5c813300-309a-11eb-8043-32f996a4c4b4.png)
after clicking on the text, the 'where' reappears

**Comment by akilovich** [comment]
Thank you for your report. We are going to fix this problem as a part of ticket #10450.
