### ISSUE TITLE
Pinned column unpins after removing top filter

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10521]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.0 EA

#### Steps to reproduce, if exist:
1. Open a table in Data Editor and pin column
2. Apply a filter
3. Remove the filter using the top filter field

Expected: the filter is removed

Actual result:
1. The filter is removed
2. The column is unpinned

**Comment by ShadelessFox** [comment]
Now column visibility is also not affected by cleaning filter.

**Comment by kseniiaguzeeva** [comment]
Verified. But a new issue was found: if the second table column is pinned, its row values appear in the column header filter list for the next column.
Steps:
1. Open a table in Data Editor (e.g. MySQL sakila.address)
2. Pin the second column
3. Press filter icon in the column which is the next to the pinned one

Expected: the column values appear in the filter list
Actual result: the values of the pinned column are in the filter list

**Comment by kseniiaguzeeva** [comment]
Separate ticket is created https://github.com/dbeaver/dbeaver/issues/10640
