### ISSUE TITLE
Working with different  databases I need separate saved session objects for any of them

### ISSUE THREAD

**Issue by sergeynilov** [dbeaver/dbeaver#10527]
Hi all,
Opening DBeaver 7.2 objects from last session are visible, but as I work with different 
databases I would like to have it own saved session objects...
Something like I set to linux menu items :
/usr/share/dbeaver/dbeaver “database 1”
/usr/share/dbeaver/dbeaver “database 2”
and clicking on any link only selected database will be opened(say with unique mysql user)
with its own last session  items...

  Have DBeaver similar functionality or to make what I want in some different way?
  
Thanks!

**Comment by uslss** [comment]
thanks for suggestion

**Comment by sergeynilov** [comment]
Does it mean that I have to waite for such functionality ?

**Comment by p91paul** [comment]
I think you can use file -> switch workspace; you select a folder that is going to be your new workspace. Each workspace has separate projects, datasources, and preferences.

There should be a command line parameter to open a specific workspace, if you don't find anything for dbeaver search eclipse workspaces on google (dbeaver is based on eclipse).

This way you can also have 2 dbeaver opened at the same time on different workspaces.

**Comment by kseniiaguzeeva** [comment]
@sergeynilov Could you try advice above?
If you want to use Command line, please try commands - con, -date https://github.com/dbeaver/dbeaver/wiki/Command-Line

**Comment by sergeynilov** [comment]
Thanks! 
As 

> This way you can also have 2 dbeaver opened at the same time on different workspaces.

Can I open more 1 instance of dbeaver with different workspaces ?
if yes, how ? mow looks like only 1 instance of dbeaver is reopened

**Comment by kseniiaguzeeva** [comment]
Yes, you can do it. Just make different workspaces for each of them.

**Comment by sergeynilov** [comment]
But how to reopen it without closing current workspace ?

**Comment by p91paul** [comment]
You can run dbeaver a first time with:

    /usr/share/dbeaver/dbeaver -data folder1

You can then run a new instance with this command:

    /usr/share/dbeaver/dbeaver -data folder2

without the -data parameter, dbeaver will run on the default workspace.
