### ISSUE TITLE
The strangest thing suddenly happened

### ISSUE THREAD

**Issue by Zbambus** [dbeaver/dbeaver#10529]
#### System information: 
- Operating system RHEL 7
- DBeaver 7.2.0/7.2.5

#### Connection specification:
- Oracle

#### Describe your question:

I was running version 7.2.0 when I suddenly discovered the following NEW strange behaviour started happening during the day and I can not get it to change back to how I have run dBeaver for many years now : 

I have several sessions (sql-editors) to different databases open, and when I went to the connection list on the left to open a new session, instead of leaving the current session intact and allowing me to create a new session with new SQL-scripts, the active session CHANGED to the chosen connection!

I did not see this immediately and in no time many of my open sessions were pointing to other databases than they did initially. I can not remeber that I have made any changes to the setup that would promote this behaviour.

I downloaded version 7.2.5, but same thing is happening there.

See this state ... first session is ES_PRODUCTION (ET4682RW)

![image](https://user-images.githubusercontent.com/47529756/100460198-1393a380-30c7-11eb-8118-636e792224b5.png)

Then I do nothing else than click on the connection RBS_PRODUCTION on the left (list of connections) and this happens : 

![image](https://user-images.githubusercontent.com/47529756/100460327-4473d880-30c7-11eb-9f2a-3624b23d8a07.png)

The content of the session does not change, but the "name" of the session changes to the new connection (and the active connection information in heading changes as well)

And if I try to run any of the SQL's in this session now, they will go towards the new active database.

This is a tremendous setback in the way I'm operating dBeaver and I have no idea what triggered this changed mode of behaviour.   Is there a configuration that I have accidentaly toggled?

Thank You for creating dBeaver!

**Comment by uslss** [comment]
Hi @Zbambus ,
it seems you've got Auto-sync connection with navigator option enabled.
![image](https://user-images.githubusercontent.com/31996417/100572527-bf670a00-32e6-11eb-9a0e-51eba4f70807.png)
Hope it will resolve your issue.

**Comment by Zbambus** [comment]
This resolved the issue nicely.
I had a suspicion that it was a configuration issue, but could not find which one and I must surely have toggled that switch by mistake and not been aware of the change at the time it happened.
I've also seen that this option could be very helpful if You have many instances of same database and shall do a quick (similar) investigation accross these instances.
Anyway, thanks for quick reply, and I learned something new, again!
