### ISSUE TITLE
Incorrect length (-1) for some column types 

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#10539]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 7.3.0

#### Connection specification:
- Database name and version SQLite
#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/31996417/100541402-d2c99500-3254-11eb-8652-611c7da03588.png)

**Comment by SubOptimal** [comment]
Based on this code it seems to be the way to indicate column types without a length information.

https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.sqlite/src/org/jkiss/dbeaver/ext/sqlite/model/SQLiteMetaModel.java#L175

**Comment by SubOptimal** [comment]
@uslss Just have seen you are project member. :-)

What solution would you propose in this case? Leave the information empty, display `n/a`?

**Comment by uslss** [comment]
verified
