### ISSUE TITLE
WMS servers for geometry viewer?

### ISSUE THREAD

**Issue by apiszcz** [dbeaver/dbeaver#10531]
The geometry viewer and WMS server feature is great.
Is it possible for one to configure their own WMS server endpoint?
Thank you.

**Comment by mkgrgis** [comment]
Now the list of WMS servers is not configurable, but You can see https://github.com/dbeaver/dbeaver/blob/3d33e9456b66aac8f8db0625cb49886b33044eec/plugins/org.jkiss.dbeaver.data.gis.view/plugin.xml and customize for Your WMS data source. If there is nice public WMS, You are welcome with pull request.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion

**Comment by flambchap** [comment]
Duplicate of #10573. Will be done soon.
