### ISSUE TITLE
Is there a way to list the Teradata databases (i.e., schemas) hierarchically

### ISSUE THREAD

**Issue by nghoffman** [dbeaver/dbeaver#10538]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows 10 Enterprise, 10.0.17763 Build 17763
- DBeaver version: 7.2.5 (latest version)

#### Connection specification:
- Database name and version: Teradata 16.20.53.11

#### Describe your question:
In teradata, databases (i.e., schemas) are defined hierarchically.  In Teradata Studio, they are listed hierarchically by default, but you can turn this off and list them alphabetically.  In DBeaver, the databases are listed alphabetically by default.  I'm wondering if there's a way in DBeaver to have the databases listed hierarchically.  Thanks!

**Comment by kseniiaguzeeva** [comment]
It looks like a feature request. Could you please give an example and/or link on how exactly the databases should be sorted?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info
