### ISSUE TITLE
EE Early Access files broken because of BOM

### ISSUE THREAD

**Issue by rscs** [dbeaver/dbeaver#10537]
For approximately the past two weeks, the 64-bit EE early access downloads are corrupt and will not install on Windows 10.  For example, https://dbeaver.com/files/ea/dbeaver-ee-7.3.0-x86_64-setup.exe

Upon trying to run the executable, the error is, "This app can't run on your PC".

Additionally, the ZIP files appear broken too.  Attempting to unarchive the https://dbeaver.com/files/ea/dbeaver-ee-7.3.0-win32.win32.x86_64.zip file results in the error, "The compressed folder is invalid", on Windows using both Windows unzip and 7-Zip.

Unzipping the file on Linux gives the following warnings, but proceeds with the unzip:
```

Archive:  dbeaver-ee-7.3.0-win32.win32.x86_64.zip
DBeaverEE ee 7.3.0 portable arch
caution:  zipfile comment truncated
warning [dbeaver-ee-7.3.0-win32.win32.x86_64.zip]:  3 extra bytes at beginning or within zipfile
  (attempting to process anyway)
```

After some testing, I determined that a BOM (Byte Order Mark) is being added to the beginning of each file, probably by your web server.  If I manually remove the BOM using a hex editor, I'm able to use the files like normal.

This seems to have started whenever you skinned the https://dbeaver.com/files/ea/ page to match the website design.

**Comment by serge-rider** [comment]
Thank your for the bug report and for the details!

Indeed, our latest web site update broke Early Access version. Will fix it ASAP.

**Comment by tati-kru** [comment]
Fixed
