### ISSUE TITLE
Shift+Ctrl+E breaks Ubuntu

### ISSUE THREAD

**Issue by fossildoc** [dbeaver/dbeaver#10545]
#### System information: 
- Operating system (distribution) and version
Ubuntu 20.04.1
- DBeaver version
7.2.4
- Java version 
1.8.0_275
#### Connection specification:
- Database name and version
postgres 12
- Driver name
postgres jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no
#### Describe the problem you're observing:
Shift+Ctrl+E breaks Ubuntu.
#### Steps to reproduce, if exist:
Open a db and view a table so that meaningful data will be displayed. Go to Window|Navigation and click on "Switch To Editor". It should work ok. Now attempt the same action by using the displayed accelerator, Shift+Ctrl+E. It will not work, and it will corrupt all other keystrokes on Ubuntu. The o.s. must be rebooted.
#### Include any warning/errors/backtraces from the logs
None found.

**Comment by uslss** [comment]
Hi @fossildoc ,
unfortunately, cannot reproduce it. is there something in the log? 

Could you check if it is still actual for you against 7.3.0?

**Comment by uslss** [comment]
there is no update on issue for a month.
feel free to reopen it with an additional info
