### ISSUE TITLE
Custom filter ordering doesn't work in ResultSet

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10542]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.0 EA

#### Steps to reproduce, if exist:
1. Open Custom filter for a table in the ResultSet
2. Set a criteria to order in _Custom>Order by_ and press Ok

![dbeaver_wZtSjlL1bT](https://user-images.githubusercontent.com/51405061/100543905-a701db80-3263-11eb-91fb-97d74675ef36.png)

**Expected**: the specified column is sorted ASC

**Actual result**: the sorting is not applied

_Workaround_: do it in the Data Editor

**Comment by LonwoLonwo** [comment]
Fixed in 21.0.2

**Comment by kseniiaguzeeva** [comment]
DESC  sorting doesn't work in the Custom filter:
1. Open Custom filter for a table in the ResultSet
2. Set a criteria to order in Custom>Order by _column_name_ DESC

**Expected**: the specified column is sorted DESC
**Actual result**: ASC sorting is applied

**Comment by LonwoLonwo** [comment]
Fixed for cases: "Column DESC", "Column1,Column2"

**Comment by kseniiaguzeeva** [comment]
verified
