### ISSUE TITLE
Exasol: incorrect data is displayed at the beginning when creating a new column

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10543]
#### System information: 
- DBeaver version 7.3.0 EA

#### Connection specification:
- Database name and version Exasol, DB2

#### Steps to reproduce, if exist:
Create a column Integer for a table

**Expected**: Column with correct type and length appears in the column list
**Actual result**: the column has length 50 at first and changes it on 36 only after saving
![AGBny8oyKf](https://user-images.githubusercontent.com/51405061/100544161-debd5300-3264-11eb-8c49-3954ed3b0a8a.gif)

**Comment by LonwoLonwo** [comment]
also DB2 problem

**Comment by LonwoLonwo** [comment]
https://www.ibm.com/docs/en/db2-for-zos/11?topic=columns-string-data-types DB2 types which support modifiers after data type name.

**Comment by LonwoLonwo** [comment]
Fixed for Exasol and DB2. Now length/precision of column are changing in case of column type (from text to numeric, from date to binary etc.) modification.

**Comment by uslss** [comment]
verified
