### ISSUE TITLE
Filtering the results of a conditional SQL query results in a full table scan

### ISSUE THREAD

**Issue by xinyuan5** [dbeaver/dbeaver#10549]
#### System information: 
- win 10 Enterprise Edition, 64-bit
- DBeaver 6.2.0 &  DBeaver 7.2.5

#### Connection specification:
- oracle 11.2.0.4
- OJDBC

#### Describe the problem you're observing:
Table Structure:  table  test(a varchar2(20), b varchar2(20), c date );

Execute SQL: select * from  test where a='test_a';

Filtering the c column in the result set causes the database to execute the following SQL

select c , count(*) from test group by c;

If the test table is very large, this will have a very serious impact on the database;

Above, thanks  very much!

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce in 7.3.0. Where do you see `select c , count(*) from test group by c`; instead of `select * from test where a='test_a';` ?
Query manager shows correct info:
![Screenshot 2020-11-30 at 11 59 07](https://user-images.githubusercontent.com/51405061/100589174-d10ada80-3303-11eb-82b7-90c4dbaf7e1d.png)

**Comment by xinyuan5** [comment]
First of all, thank you very much for your reply!
Connecting to the oracle database through DBeaver will generate 3 sessions(v$session):
DBeaver 7.2.5 - Main
DBeaver 7.2.5 - Metadata
DBeaver 7.2.5 - SQLEditor <Script.sql>

When I click to filter the column of the result set,
I used another tool to view the SQL executed by DBeaver and found this statement.
DBeaver 7.2.5 - Main Executed :  SELECT C, count(*) FROM F3602914.TEST GROUP BY C

**Comment by xinyuan5** [comment]
like this

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. The current implementation has to be changed. Do you have any ideas how it should work to reduce the impact?

**Comment by serge-rider** [comment]
We probably should add option to switch count calculation on/off.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/113403769-d9f1e280-93af-11eb-88be-1329f37fa66c.png)

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/113403807-e6763b00-93af-11eb-9625-447c7880fcbc.png)

**Comment by kseniiaguzeeva** [comment]
verified
