### ISSUE TITLE
Generate ALTER TABLE script from selected columns

### ISSUE THREAD

**Issue by kczereczon** [dbeaver/dbeaver#10553]
**Problem**
Sometimes I need to add new columns for the existing database eg. production. First of all I create this columns on my local environment, and copy ALTER TABLE query and store it somewere, after that when I want to update my production's database structure, I copy stored ALTER TABLE query and run it on production, but sometimes I forget to copy the query during local altering, and I have to write query for my own.

**Description**
When I right click on a column in the columns view, in the options list should be placed the "Generate ALTER TABLE script" button, it should work with a multiselect of  columns.

**Screens**
![image](https://user-images.githubusercontent.com/22079016/100614661-c0179480-3316-11eb-9c45-5e45453f0141.png)

**Comment by kseniiaguzeeva** [comment]
We already have such function implemented by following way:
Create columns in table properties and press Save button> Popup appears with the SQL statement. You can Open SQL Editor for it, copy, Cancel and Persist the changes.
![Screenshot 2020-12-07 at 18 44 16](https://user-images.githubusercontent.com/51405061/101371814-3dfe1180-38bc-11eb-8464-0272c9a79646.png)

Does it cover your needs?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still not solved for you - feel free to reopen it with an additional info

**Comment by erlangparasu** [comment]
any update?

**Comment by JoshDrentlaw** [comment]
It is useful to have the `ALTER TABLE` code appear after saving, but is that the only way to view it? You can't generate that code again at a later time?
If not, it would be helpful. Currently when were creating new columns locally we're saving the code to the ticket so that the db admin can add the columns in production. The only issue is if we forget to save them.

**Comment by ejazrasool** [comment]
> We already have such function implemented by following way: Create columns in table properties and press Save button> Popup appears with the SQL statement. You can Open SQL Editor for it, copy, Cancel and Persist the changes. ![Screenshot 2020-12-07 at 18 44 16](https://user-images.githubusercontent.com/51405061/101371814-3dfe1180-38bc-11eb-8464-0272c9a79646.png)
> 
> Does it cover your needs?

The author (and me, many times) forget to copy these alter statements while creating the column(s) so a way to view these statements after adding the column would be nice.

**Comment by sami-cha** [comment]
It's a feature that is missing and not covered by the work around. Would be great to have it.
