### ISSUE TITLE
Cannot delete project 

### ISSUE THREAD

**Issue by clabnet** [dbeaver/dbeaver#10551]
#### System information: 
- Operating system : WIN 10 PRO EN 64 10.0.18363
- DBeaver version: 7.3.0
- Additional extensions : NONE

#### Connection specification:
- Database name and version : SQLITE 
- Driver name : org.xerial:sqlite-jdbc:RELEASE
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NONE

#### Describe the problem you're observing:
The Delete command is not available
![dbbeaver-bug](https://user-images.githubusercontent.com/6067610/100598381-ef220c00-32fe-11eb-969d-5d2f2f5ac1d1.png)

**Comment by kseniiaguzeeva** [comment]
Most probably your project is in a default folder. Please
- enable **Delete project content from disc** option in delete popup (it appears after pressing delete) 
- or change the project directory and then delete with the enabled or disabled option.

The changes were implemented according https://github.com/dbeaver/dbeaver/issues/10463
