### ISSUE TITLE
Drop down menu for enum field in table editor not populating.

### ISSUE THREAD

**Issue by cbf305** [dbeaver/dbeaver#10561]
#### Client system info: 
- Linux (Arch - 5.9.9 Kernel)
- DBeaver version 7.2.5.202011152110
- Additional extensions - None

#### Server Info:
- Database MariaDB 10.5.8-1 (Remote server is running Ubuntu 18.04)
- Driver 2.4.3
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
This has been an issue for a long time, but I just thought it was because I was running herbstluftwm and not a full DE, but recently I had a need to use dbeaver on a system with KDE and a Windows 10 system and both also did the same thing.  Since I've tested this on several Arch and Ubuntu systems running, i3, KDE and herbstluftwm, as well as several different Windows 10 machines.  I've also tested both MariaDB and MySQl servers and no matter the combination, they all do the same thing.  When in the table editor and I click on a enum field to edit, it used to give a drop down list of the possible enum values.  Now it displays the down arrow, but it never shows the values.  If you use the scroll wheel on the mouse or two finger scrolling on a touch pad it will scroll through the values, but the menu won't display.

I am using the built-in Dark theme, but it exhibits the same behavior under any theme.

Screenshot showing the incomplete down down menu.  There are 5 values for this enum field.
![2020-11-30-115447_2560x1440_scrot](https://user-images.githubusercontent.com/2612500/100639855-b3d60c00-3303-11eb-8c74-b21a69b06a0c.png)

I am not sure if it is related to closed issue #2468 or not since there was not a description given.

#### Steps to reproduce, if exist:

1. Create fresh DB on MariaDB or MySQL server
2. Create fresh table with at least one field of type ENUM with more then one value
3. Open table editor and try to change the enum field value by double clicking on it

#### Include any warning/errors/backtraces from the logs
There are no log errors

Thanks!

**Comment by uslss** [comment]
Thanks for the report.
As a workaround, you can use Cell editor (Choose cell and then use Shift+Enter) or Value panel (Ctrl+7)

**Comment by cbf305** [comment]
Thanks for the tip.  I've been using the value panel as a workaround, but I didn't know about the cell editor.

**Comment by flambchap** [comment]
I found out that clicking on an inline editor on Linux triggers a FocusLost event. However, the reason for that is still a mystery to me. Needs more investigation.

**Comment by flambchap** [comment]
Fixed.

**Comment by cbf305** [comment]
Awesome, thank you!

**Comment by uslss** [comment]
verified
