### ISSUE TITLE
CSV connection Import or Export to database : treating empty fields as NULL like CSV file import

### ISSUE THREAD

**Issue by amoradell** [dbeaver/dbeaver#10566]
**CSV import or export from a CSV connection to database doesn't have option : Set empty strings to NULL**
When I import a csv file directly without connection, I have the option to set empty strings to NULL
It's very convenient with MS-SQL for example.

**Is it possible to add this option on CSV connection properties or Importer settings**

**Comment by kseniiaguzeeva** [comment]
It depends on CSV driver settings. We cannot do it from our side.
