### ISSUE TITLE
Delay occurs when using the Bind Parameter

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#10565]
#### System information: 
- Windows 10
- Dbeaver 7.3.0

#### Connection specification:
- Oracle 18C

When using the Bind Parameter after dbeaver is upgraded to 7.3.0, there is a delay of about 1 second after clicking the OK button.

Thank for Reading.

* Ver 7.2.5  
![7_2_5](https://user-images.githubusercontent.com/59002295/100707899-c2e5b880-33ee-11eb-9cd5-b66354cf648c.gif)

* Ver 7.3.0
![7_3_0](https://user-images.githubusercontent.com/59002295/100707905-c5481280-33ee-11eb-9e6d-270303d107ef.gif)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report

**Comment by kseniiaguzeeva** [comment]
https://github.com/dbeaver/dbeaver/issues/10686
