### ISSUE TITLE
Cannot persist any changes to database

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#10567]
#### System information: 
- Operating system: Windows 10
- DBeaver version: 7.3.1 EA
- Additional extensions: none

#### Connection specification:
- Database name and version: sqlite
- Driver name: SQLite
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Cannot persist any changes made to database:
![SKlv7WfMi2](https://user-images.githubusercontent.com/35821147/100717029-915af600-33ca-11eb-9c00-23d62119fa55.gif)

#### Steps to reproduce, if exist:
1. Create a new table
2. Try to save (persist changes)

Expected: changes were applied
Actual: nothing happens

#### Include any warning/errors/backtraces from the logs
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/5621266/dbeaver-debug.log)

**Comment by akilovich** [comment]
Fixed.

**Comment by uslss** [comment]
verified
