### ISSUE TITLE
sqlite: "create table" reports updated rows

### ISSUE THREAD

**Issue by mbelvadi2** [dbeaver/dbeaver#10562]
#### System information: 
- Operating system (distribution) and version- Windows 10 Pro
- DBeaver version 7.3.0
- Additional extensions-none

#### Connection specification:
- Database name and version - sqlite local file

#### Describe the problem you're observing:
First I had a table called fixed_callnums with about 17,000 rows in it.
Then I did: delete from fixed_callnums;
and confirmed the warning.
Then I had a change of heart and decided to delete the entire table and start a new one.
So I used right-click Delete on the table name in the Database Navigator and confirmed deleting it.
Then I ran the command in the screen shot to create a new table of the same name but with different column names/types from the first one.
How can dbeaver be reporting that Updated Rows number?  Where could that be coming from?  That isn't close to even the number of rows that had been in the old table, if somehow there was a trace of that still left.
I do have other tables in this same .db file that do have large numbers of rows on that scale, so I'm worried about what actually was "updated".
![image](https://user-images.githubusercontent.com/28821980/100645923-bf313380-3313-11eb-8bfb-85ca638ee9d5.png)

**Comment by kseniiaguzeeva** [comment]
Unfortunately cannot reproduce using your steps. I deleted and created a new table with the same name. 0 updated rows are displayed in the ResultSet.
![Screenshot 2020-12-08 at 11 31 25](https://user-images.githubusercontent.com/51405061/101459360-30db3400-3949-11eb-9f8d-34281ac1fc27.png)
Maybe your number was received from the driver. What SQLite version do you have?

**Comment by uslss** [comment]
there is no update on issue for a month.
feel free to reopen it with an additional info
