### ISSUE TITLE
CSV Export Different From Query Preview

### ISSUE THREAD

**Issue by starro02** [dbeaver/dbeaver#10560]
#### System information: 
- Mac OS 11.0.1
- DBeaver Version 7.2.5.202011152110
- Additional extensions

#### Connection specification:
- Database name and version
Microsoft SQL Server
- Driver name
Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No
#### Describe the problem you're observing:
I have a query that unions two results sets in the last step. The output in the query preview (expected) is 
2020-08-16	180. This result is reached from the first half of the union. 

After exporting to the CSV output, the output (incorrect and unexpected) is 
2020-08-16	75.  I've identified that this result lives in my data I'm comparing, but because of how the joins are written should be impossible to get to. 

I have commented out the second half of the union to see if that would resolve the issue. The query preview was still correct as expected, but the CSV export dropped all data relating to that date.

**Comment by kseniiaguzeeva** [comment]
Could you give a query example?

**Comment by starro02** [comment]
The query is constructed as such
with a as (select id, datepart(week,date) as AttendanceWeek, sum(minutes) as WeeklyAttendanceMinutes From Activity group by id, datepart(week,date)),
a1 as (select id, datepart(week,date) as AttendanceWeek, date, minutes as DailyAttendanceMinutes From Activity)
b as (select id, datepart(week,date) as AttendanceWeek, sum(minutes) as WeeklyAttendanceMinutes from attendances  group by id, datepart(week,date)),
b1 as (select id, datepart(week,date) as AttendanceWeek, date, minutes as DailyAttendanceMinutes from attendances),
allAggregateData aag as (select id, attendance week, WeeklyAttendanceMinutes from a union all select id, attendanceweek, WeeklyAttendanceMinutes from b)
c as (select id, AttendanceWeek, max(WeeklyAttendanceMinutes) 'MaxWeeklyMinutes' from aaG group by id, AttendanceWeek), 
finalData as (select c.id, a1.date, a1.attendanceminutes from c join a on c.id=a.id and c.AttendanceWeek=a.AttendanceWeek and c.MaxWeeklyMinutes=a.WeeklyMinutes join a1 on a.id=a1.id and a.attendanceweek=a1.attendanceweek union select c.id, b1.date, b1.attendanceMinutes from c join b on c.id=b.id and c.attendanceweek=b.attendanceweek and c.MaxWeeklyMinutes=b.weeklyAttendanceMinutes join b1 on b.id=b1.id and b.attendanceweek=b1.attendanceweek) 
select * from finalData

The query is aggregating attendance data from two different tables by week, unioning the two table aggregates, finding the max minutes by week, and then joining back to the source tables to return the day by day attendance.

**Comment by kseniiaguzeeva** [comment]
Sorry fo the late response. Is it possible to give me DDL for this example too? I have an SQL error in the middle of the query when try to reproduce.

**Comment by uslss** [comment]
there is no update on issue for a month.
feel free to reopen it with an additional info
