### ISSUE TITLE
New feature request - "Copy as DBUnit XML"

### ISSUE THREAD

**Issue by mbaricevic** [dbeaver/dbeaver#1057]
Hi,
in query Result tab, 
it would be great to have "Copy as DBUnit XML", on right click for selected rows.
http://dbunit.sourceforge.net/
After that is clicked, selected rows will be translated/exported as DBUnit XML files and moved to clipboard.
Some other tools/plugins have that functionality. (see attached image)
![screen shot 2016-12-13 at 09 55 40](https://cloud.githubusercontent.com/assets/6378682/21134094/7d9c25be-c11c-11e6-93bf-b2a913ca0e13.png)

Thanks, Marko Baricevic

**Comment by serge-rider** [comment]
This can be done as an additional data export format.

**Comment by uslss** [comment]
already implemented 
![image](https://user-images.githubusercontent.com/31996417/95181467-009dda80-07cc-11eb-8856-dfc5efa068be.png)
