### ISSUE TITLE
Have dbeaver auto update itself, instead of downloading a .pkg

### ISSUE THREAD

**Issue by richstokes** [dbeaver/dbeaver#10574]
**Is your feature request related to a problem? Please describe.**
It's kind of annoying to have to download a .pkg and go through the install process everytime there's an update

**Describe the solution you'd like**
Would be great if it could download and install the update itself, similar to how browsers auto update themselves with no user interaction needed

**Comment by kseniiaguzeeva** [comment]
Closed as duplicate https://github.com/dbeaver/dbeaver/issues/6558
