### ISSUE TITLE
GIS viewer support for PrestoSQL

### ISSUE THREAD

**Issue by samueltqx** [dbeaver/dbeaver#10570]
Is it possible to support Spatial Data viewer for PrestoSQL? 
The `H2GISGeometryValueHandler` can be reused for handling Geometry type from Presto. Since Presto is in the Generic plugins, can the GeometryValueHandler be added to it, or should it be a separate plugin?

**Comment by kseniiaguzeeva** [comment]
Yes, it is possible. We are going to implement it in 7.3.3 release.

**Comment by kseniiaguzeeva** [comment]
More tickets about gis support in this milestone:
https://github.com/dbeaver/dbeaver/issues/10661
https://github.com/dbeaver/dbeaver/issues/10660
https://github.com/dbeaver/dbeaver/issues/10573

**Comment by LonwoLonwo** [comment]
Hello @samueltqx 
What kind of column type are you using for spatial data?
I can add map support for binary data types.

**Comment by samueltqx** [comment]
Hi @LonwoLonwo 
I am using both text and binary for spatial data but can convert to Geometry object in Presto/Trino.

**Comment by LonwoLonwo** [comment]
@samueltqx Could you provide some examples for testing please? Table DDL with some data.

**Comment by LonwoLonwo** [comment]
@samueltqx also can you try change view/format settings for text columns like on the picture?

![2021-01-25 14_49_49-](https://user-images.githubusercontent.com/45152336/105702414-d019b200-5f1c-11eb-91a0-5a775a5fc0a1.png)

In theory, when switching to the "geometry" type, a "Spatial" tab should appear.

**Comment by samueltqx** [comment]
@LonwoLonwo yes I'm able to switch to geometry type from text column in Presto and the Spatial viewer works! Was this feature added recently? I was looking at the GenericValueHandlerProvider which is why I assumed there isn't support for Spatial yet.

**Comment by samueltqx** [comment]
However I did notice an odd bug where I was only able to switch to Geometry type when I alias the column name. 

Without alias, there's no option to set format.
![without alias](https://user-images.githubusercontent.com/12363062/105706616-aacf7880-5f09-11eb-88e9-d639caf8f630.png)

With alias, I am able to. 
![with alias](https://user-images.githubusercontent.com/12363062/105706784-e8cc9c80-5f09-11eb-82d2-4919bfebaf7a.png)

The metadata for both results shows the type as Varchar. But without aliasing, it seems to show the column as Unknown type in the Grid.

**Comment by LonwoLonwo** [comment]
@samueltqx We unfortunately have the same problem with the presto jdbc (0.245.1) driver. It returns only a small list of standard data types, and most of the list returns only just with names. 
What driver are you using?

The ability to switch strings to geometry has been with us for a while, but now we realized that it was time to write about it in the documentation.

**Comment by samueltqx** [comment]
@LonwoLonwo I am using PrestoSQL jdbc (340) and also tested on the latest Trino jdbc (351) with the same result. The data type id for most data types are shown as value 2000.

**Comment by LonwoLonwo** [comment]
@samueltqx Unfortunately, we cannot do anything about the driver and data types yet. You suggested a good workaround with aliases.

**Comment by LonwoLonwo** [comment]
So, I added the ability to view binary geodata using the same algorithm as string data.
Through right click on cell value -> View/Format -> Set "columnName" format -> Geometry

![2021-01-25 22_49_55-DBeaver Enterprise 7 3 3 - address_binar](https://user-images.githubusercontent.com/45152336/105758793-b7cb8680-5f60-11eb-876d-b973f040cb52.png)

![2021-01-25 22_50_31-DBeaver Enterprise 7 3 3 - address_binar](https://user-images.githubusercontent.com/45152336/105758797-b8641d00-5f60-11eb-9c0d-42f313a64f7d.png)


Tested on varbinary and blob column types.

**Comment by LonwoLonwo** [comment]
More information added here https://github.com/dbeaver/dbeaver/wiki/Working-with-Spatial-GIS-data

**Comment by samueltqx** [comment]
@LonwoLonwo Thanks! I guess the support for binary geometry will be in the next release? Tested on the latest devel branch but I'm getting this error: `org.locationtech.jts.io.ParseException: Unknown WKB type 256`, for the query `SELECT st_asbinary(st_point(-0.090508461, 51.511680));`

**Comment by LonwoLonwo** [comment]
@samueltqx yes, I see. Unfortunately, class WKBReader cannot handle reading this (from select) set of bytes. 
Do you have any other geodata in the binary columns? Have you tested for them?

**Comment by samueltqx** [comment]
@LonwoLonwo  Yes, geodata in binary column works well.

**Comment by LonwoLonwo** [comment]
@samueltqx thanks for testing!
You were right, the changes will be available in the new version 7.3.4
