### ISSUE TITLE
Allowing users to have custom Map Tile source

### ISSUE THREAD

**Issue by chungcf2006** [dbeaver/dbeaver#10573]
**Is your feature request related to a problem? Please describe.**
I got a project which I need to plot the spatial data on a specific map (not in the list shipped with DBeaver)

**Describe the solution you'd like**
Having a simple Map Tile Manager can solve the problem.
The manager should allow users to customize the tile source URL and the zoom level (as what the user can set in TileLayer under leaflet.js) 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by mkgrgis** [comment]
Duplicate https://github.com/dbeaver/dbeaver/issues/10531 ?

**Comment by flambchap** [comment]
Yes, it is. Thank you.

**Comment by flambchap** [comment]
Implemented.

**Comment by kseniiaguzeeva** [comment]
verified
