### ISSUE TITLE
scheduler error not implemented

### ISSUE THREAD

**Issue by mrhargro** [dbeaver/dbeaver#10583]
UI seems simple enough. Scheduled a task but I don't think it worked and got a message saying it was scheduled in my local cron. I see nothing in next run and it doesn't seem to run. What am i missing? 

If i open scheduler settings I see this: 

![image](https://user-images.githubusercontent.com/2421704/100940260-9cdf1780-34c5-11eb-8507-a4c0cc3c73b2.png)

eclipse.buildId=unknown
java.version=11.0.8
java.vendor=AdoptOpenJDK
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/xxxxx/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/xxxxxx/.eclipse_keyring

This is a continuation of log file /Users/xxxxx/Library/DBeaverData/workspace6/.metadata/.bak_0.log
Created Time: 2020-12-02 10:13:44.677

**Comment by akilovich** [comment]
Scheduling support for macOS is not implemented as of DBeaverEE 7.2. It is implemented in the next version which will be released next Monday.
