### ISSUE TITLE
DB Navigator: option Filter databases or schemas cannot find PostgreSQL, SQL Server schemas

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10581]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.0 EA

#### Connection specification:
- Database name and version PostgreSQL, SQL Server

#### Steps to reproduce, if exist:
1. Connect to a database and select option **FIlter databases or schemas** for DB Navigator Search field
3. Enter a schema name (e.g. dbo for SQL Server, public for PostgreSQL)
4. Expand a database in DB Navigator with such schema

**Expected**: the database is expanded and the schema is displayed
**Actual result**: the schema is not found

**Comment by serge-rider** [comment]
Fixed.

Now we filter only "leaf" containers. For PG and SQL Server it means schemas.

**Comment by GuillaumeDesforges** [comment]
How can I check when/in which version this fix is going to apply?

**Comment by kseniiaguzeeva** [comment]
Verified.
The fix is included in the next release 21.0.2
