### ISSUE TITLE
Mac: data transfer format setting can be changed only after pressing Next button

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10588]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 7.3.0 EA

#### Describe the problem you're observing:
Data transfer format settings are not applied if the Next button is not pressed right after the change has been made. Only checkboxes work correctly.
#### Steps to reproduce, if exist:
1. Open export/import wizard
2. Make a change in format settings
3. Click another format setting

Expected: the changed setting is visible
Actual result: the setting is reverted

Workaround:
1. Change a format setting
2. Click Next
3. Click Back
4. Change another setting and press Next again

**Comment by akilovich** [comment]
Fixed the issue. The applied fix potentially touches all format settings in data transfer, so I would ask for careful testing.

**Comment by kseniiaguzeeva** [comment]
verified
