### ISSUE TITLE
Copy of table is not created SQLite

### ISSUE THREAD

**Issue by ForumLiker** [dbeaver/dbeaver#10582]
There is no way to create a copy of the table structure. Instead, a new empty table is created.
https://recordit.co/No5cbr4e3T
DBeaver 7.3.0.202011291229 Windows 10x64
DBeaver 7.2.5 on Linux
sqlite-jdbc-3.32.3.2

**Comment by uslss** [comment]
Hi @ForumLiker ,
you can use data export for it. Just export table to table in the same database.
https://github.com/dbeaver/dbeaver/wiki/Data-transfer
Can you check if it solves your problem and write back?
Thanks in advance

**Comment by ForumLiker** [comment]
Hello @uslss! This is not a solution but only a temporary workaround

**Comment by ShadelessFox** [comment]
This is an intended behavior for all databases, so I'll close this issue.
