### ISSUE TITLE
Turkish character issue on DBEaver 7.3.0

### ISSUE THREAD

**Issue by mehmeet43** [dbeaver/dbeaver#10587]
Hello, although I changed the text file encoding as explained in the screenshot, I see the result set with Turkish characters incorrectly. How can we fix this problem, does anyone know?

![69729725-e5882600-1137-11ea-897a-185db2996b76](https://user-images.githubusercontent.com/7474020/100983070-dcefda00-3559-11eb-81f8-a64299b6964e.png)

<img width="745" alt="Screen Shot 2020-12-03 at 11 16 14" src="https://user-images.githubusercontent.com/7474020/100983095-e6794200-3559-11eb-92bf-a525f44a5397.png">

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce. Please tell DBeaver version and your OS

**Comment by uslss** [comment]
there is no update on issue for a month.
feel free to reopen it with an additional info

**Comment by officialmmt** [comment]
w11 dbeaver 23.0 has same problem
