### ISSUE TITLE
How to create or Edit a Oracle Database via data model (Er Diagram)

### ISSUE THREAD

**Issue by damgot** [dbeaver/dbeaver#10592]
#### System information: 
- Operating system  : Windows 10 10.0.19041
- DBeaver version : 7.2.2.202010041557

#### Connection specification:
- Database name and version : Oracle

#### Describe your question:
Hello,
Is there a way to edit or create a database via the data model view (ER Diagram ) ? Like creating PK, FK, add columns, remove columns, etc. Or the Er Diagram is only Read Only ? 
If not, is there another way in DBeaver for creating/editing Oracle DataBase from a data model view ?
If not, is it planned to be added in a future release ?

Thanks for your help,
Damgot

**Comment by uslss** [comment]
It is not implementer,
Mark your issue as feature request.
Thanks for the suggestion

**Comment by uslss** [comment]
[Feature](https://github.com/dbeaver/dbeaver/wiki/Edit-mode) is already available in Enterprise edition
