### ISSUE TITLE
Incorrect drag-n-drop of result set tabs

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#10593]
#### System information: 
- Operating system (distribution) and version: **Windows 10**
- DBeaver version: **7.3.1**
- Additional extensions: **none**

#### Connection specification:
- Database name and version: **any**
- Driver name: **any**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **none**

#### Describe the problem you're observing:
After drag-n-drop tabs are not _moved_ but swapped:
![0CszH4j1vZ](https://user-images.githubusercontent.com/35821147/101001424-2a774180-3570-11eb-95f5-60de61c9b371.gif)

#### Steps to reproduce, if exist:
1. Open multiple _(>2)_ result set tabs using `Ctrl+\`
2. Try to move tabs

After moving first tab over last tab the order must be...
* Expected: `[Tab 1] [Tab 2] [Tab 3]` -> `[Tab 2] [Tab 3] [Tab 1]`
* Actual: `[Tab 1] [Tab 2] [Tab 3]` -> `[Tab 3] [Tab 2] [Tab 1]`

**Comment by uslss** [comment]
verified
