### ISSUE TITLE
Dashboard name is not displayed in Delete popup

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10599]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 7.3.0
- Additional extensions

#### Steps to reproduce, if exist:
1. Create a dashboard
2. Click on it and press Delete

Expected: confirmation popup appears with the Dashboard name
Actual result: brackets with null are displayed in the popup message
![Screenshot 2020-12-03 at 16 19 39](https://user-images.githubusercontent.com/51405061/101024136-bdba7200-3584-11eb-9f37-63960daf2821.png)

**Comment by uslss** [comment]
verified
