### ISSUE TITLE
Mac focus issue in Connection driver properties

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10605]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 7.3.0 EA

#### Steps to reproduce, if exist:
1. Open Connection Settings e.g. for new MongoDB connection
2. Go to Driver properties
3. Change Server Select Timeout on 20000 and press Test Connection right after it

Expected: the change is applied, Test connection is successful
Actual result: Test connection failed because the change was not applied
Workaround: Click any checkbox after making the change
![Screenshot 2020-12-04 at 11 22 23](https://user-images.githubusercontent.com/51405061/101140066-79ca7a00-3623-11eb-8792-23bfda94cea0.png)

**Comment by akilovich** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified
