### ISSUE TITLE
Add ANTLR4 grammar support to Clickhouse

### ISSUE THREAD

**Issue by Slach** [dbeaver/dbeaver#10604]
clickhouse added ANTLR4 grammar parsers
https://github.com/ClickHouse/ClickHouse/pull/11298

look like dbeaver can try to get grammar from clickhouse project, for fast add new ClickHouse dialect SQL syntax features

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
I don't thin kthat we can do this. We don't use antlr or any sort of BNF-like grammar in SQL parser.

SQL parser is fuzzzy (recoverable) and can't rely on strict grammar.

**Comment by zhicwu** [comment]
@uslss / @serge-rider, quick question: are all keywords returned from [DatabaseMetaData.getSQLKeywords()](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getSQLKeywords--) considered for highlighting and auto-completion in DBeaver and CloudBeaver?
