### ISSUE TITLE
how to formate sql like PL/SQL beautifier in sql editor?

### ISSUE THREAD

**Issue by zhaodecang** [dbeaver/dbeaver#10603]
For example:
`   select * from TABLE1 t where a > 100 and b between 12 and 45;`
dbeaver formate above sql to this:
```
select
	*
from
	TABLE1 t
where
	a > 100
	and b between 12 and 45;
```
and PL/SQL beautifier formate above sql  to this:
```
select *
  from TABLE1 t
 where a > 100
   and b between 12 and 45;
```

**Comment by uslss** [comment]
Hi @zhaodecang ,
you could change formatting in preferences. Probably you can change formatter to Compact. Also, you can use External formatters.
![image](https://user-images.githubusercontent.com/31996417/101374141-dd240880-38be-11eb-8b96-7abef6383129.png)
Could you check if it resolves your issue?
Thanks in advance

**Comment by zhaodecang** [comment]
> Hi @zhaodecang ,
> you could change formatting in preferences. Probably you can change formatter to Compact. Also, you can use External formatters.
> ![image](https://user-images.githubusercontent.com/31996417/101374141-dd240880-38be-11eb-8b96-7abef6383129.png)
> Could you check if it resolves your issue?
> Thanks in advance

Okay,thank you!
