### ISSUE TITLE
Dark theme and disabled buttons

### ISSUE THREAD

**Issue by rodrigoguariento** [dbeaver/dbeaver#10612]
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04 LTS
- DBeaver version: Version 7.3.0.202011291229
- Additional extensions: none

#### Connection specification:
- Database name and version: N/A
- Driver name: N/A
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : N/A

#### Describe the problem you're observing:
Disabled buttons like this NEXT button that is disabled is equal to enabled buttons, not being possible to distinguish them.
![image](https://user-images.githubusercontent.com/25516653/101171962-471e8280-361f-11eb-8820-29684e47dbf4.png)

#### Steps to reproduce, if exist:
Set Dark Theme and try export some data using Next Next ... until last step. Check which buttons are enabled or disabled visually; confirm you deduction confirming which buttons have focus.

#### Include any warning/errors/backtraces from the logs
N/A

**Comment by uslss** [comment]
Hi @rodrigoguariento ,
seems the issue is fixed in EA version due to migration to Eclipse 2020-12. 
Could you check if this solution suits you?
https://dbeaver.io/files/ea

**Comment by rodrigoguariento** [comment]
I've updated to Version 7.3.1.202012201616 and now its possible to distinguish (despite very subtle). Thank you!
![image](https://user-images.githubusercontent.com/25516653/102772169-d341e100-4365-11eb-920f-f15714862fbc.png)
