### ISSUE TITLE
dbo schema is set always after changing SQL Server database in SQL Editor

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10610]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.0 EA

#### Connection specification:
- Database name and version SQL Server

#### Steps to reproduce, if exist:
1. Open SQL Editor for SQL Server
2. Press Ctrl+0
3. Select another database and any schema except dbo and double-click

Expected: selected database and schema are displayed in the top toolbar
Actual result: selected database and dbo schema is selected
![KfsQB5c6nc](https://user-images.githubusercontent.com/51405061/101164282-ea828e00-3645-11eb-94ae-eef8abed88e4.gif)

Workaround: Press Ctrl+0 again and select another schema again

**Comment by LonwoLonwo** [comment]
can't reproduce in DBeaver 7.3.3

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce too.
