### ISSUE TITLE
Disable Execute SQL Script in Preferences

### ISSUE THREAD

**Issue by dmocek** [dbeaver/dbeaver#10617]
Is there a way to disable the 'Execute SQL Script' feature?  This seems like a very dangerous feature to have on by default and to have it assigned to Alt+X (on Linux) by default, which can easily be accidentally triggered.  I never want this feature on unless I go out of my way to execute it.  I've set my production connections to read-only, confirm sql execution, confirm data changes, and I've removed the keyboard shortcut.  However, I would feel even safer if I could disable it completely in preferences and go out of my way to use it when I want.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by E1izabeth** [comment]
Now you can modify editor toolbar to remove these buttons
![image](https://github.com/dbeaver/dbeaver/assets/28875055/49e85e16-2c65-421c-8f74-ef08c65279c6)


Does it solve your issue along with shortcuts disabling?

**Comment by E1izabeth** [comment]
It's been a while since no update here, so I'm closing this issue.
