### ISSUE TITLE
Query formatting question : why the line breaks with `in` keyword ?

### ISSUE THREAD

**Issue by pc-robelbois** [dbeaver/dbeaver#10618]
#### System information: 
- Windows
- 7.2.5

#### Connection specification:
- Any

#### Describe your question:

Queries with the `in` keyword are automatically formatted with a line break after the list's commas. Is that expected ? 
This makes querries with multiple `in` and short lists hard to read..

![image](https://user-images.githubusercontent.com/50719398/101265427-416b8e80-373e-11eb-903a-ba18ae97e9f0.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
fixed in 7.3.3

**Comment by uslss** [comment]
verified

**Comment by pierrecorsini** [comment]
Verified on 7.3.3
