### ISSUE TITLE
Letters have different color in one word in Data Editor JSON view 

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10620]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 7.3.0 EA

#### Steps to reproduce, if exist:
Open a table JSON tab of Data Editor (e.g. Mongo)

Expected: the word has one color
Actual result: the letters are coloured in green and red in one word:
![Screenshot 2020-12-06 at 07 16 12](https://user-images.githubusercontent.com/51405061/101271417-8d94ee00-3793-11eb-8f7e-e2451e5f7df7.png)

**Comment by flambchap** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified
