### ISSUE TITLE
Navigator icons scaled up too much in 7.3.0

### ISSUE THREAD

**Issue by bauerp** [dbeaver/dbeaver#10633]
#### System information: 
- MacOS Catalina 10.15.7
- DBeaver 7.3.0

#### Describe the problem you're observing:

The database navigator icon's have increased in size after upgrading to 7.3.0

![1795D074-5810-4754-ACCA-421130B513A8](https://user-images.githubusercontent.com/10477798/101513282-ff169d00-3949-11eb-8d47-7500604f9216.png)

**Comment by kseniiaguzeeva** [comment]
Could you please try the latest EA? It should be fixed there https://dbeaver.io/files/ea/

**Comment by uslss** [comment]
there is no update on issue for a month.
feel free to reopen it with an additional info
