### ISSUE TITLE
"编辑模板"里的"名称"输入框太短了

### ISSUE THREAD

**Issue by bikthh** [dbeaver/dbeaver#10639]
#### System information: 
- Operating system  windows10
- DBeaver version 7.30
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
Hi @bikthh ,
can you provide steps to reproduce and screenshot with an issue?
thanks in advance

**Comment by uslss** [comment]
there is no update on issue for a month.
feel free to reopen it with an additional info
