### ISSUE TITLE
SELECT * from a table doesn't retrieve all records 

### ISSUE THREAD

**Issue by adi-lev** [dbeaver/dbeaver#10635]
****** This issue doesn't exist in version 6.0.0 *****

#### System information: 
- Operating system (distribution) and version - macOS 10.15.7
- DBeaver version - 7.3.0
- Additional extensions

#### Connection specification:
- Database name and version - Snowflake
- Driver name- JDBC 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - yes

#### Describe the problem you're observing:
SELECT * from a table doesn't retrieve all records. 
E.g select count(*) from table -- returns 68
select * from table -- returns 8 records only (the limit is 200)
This issue doesn't exist in version 6.0.0

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce it. The issue can be on the driver side.
Could you please try to create a connection with an older driver version (Connection Settings>Main tab>Edit driver settings>Download/Update)?

**Comment by adi-lev** [comment]
upgrading driver version to 3.12.16 solved the issue. Thanks

**Comment by kseniiaguzeeva** [comment]
Great!
