### ISSUE TITLE
Schema selection error in script with cyryllic name

### ISSUE THREAD

**Issue by Kazun3500** [dbeaver/dbeaver#10631]
#### System information: 
- Operating system (distribution) and version
Linux Ubuntu 20.04
- DBeaver version
7.3.0 (release 30.11.2020)

#### Connection specification:
- Database name and version
Oracle 11.2 

#### Describe the problem you're observing:
I can`t select database schema when i load script with cyryllic letters in  name. Postgres is ok, oracle - has error.

[Запись экрана от 08.12.2020 15_53_46.zip](https://github.com/dbeaver/dbeaver/files/5659588/08.12.2020.15_53_46.zip)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by kseniiaguzeeva** [comment]
Verified
