### ISSUE TITLE
Boolean view customisations should be configurable via Settings menu

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10645]
Feature request based on https://github.com/dbeaver/dbeaver/issues/9327

**Comment by serge-rider** [comment]
WE also need to configure NULL booleans representation (as NULL or as third boolean state).

**Comment by serge-rider** [comment]
Now booleans view can be configured.
However it is still "textual checkbox" by default.

![image](https://user-images.githubusercontent.com/6398845/103172297-824d5380-4863-11eb-84e7-7cd2b5651c8d.png)

![image](https://user-images.githubusercontent.com/6398845/103172308-9729e700-4863-11eb-92a0-75c42280d6cc.png)


![image](https://user-images.githubusercontent.com/6398845/103172352-e243fa00-4863-11eb-8996-3d55db391bd2.png)
![image](https://user-images.githubusercontent.com/6398845/103172364-f0921600-4863-11eb-82a8-d6b034a5663d.png)
![image](https://user-images.githubusercontent.com/6398845/103172368-fee03200-4863-11eb-9b30-4c531928d5ee.png)

**Comment by serge-rider** [comment]
Also, let's try to use ASCII chars instead of fancy Unicode boxes.
[X], [ ] and [NULL]

If you have any better idea please suggest. Maybe this also should be configurable?

**Comment by serge-rider** [comment]
Fixed. + textboxes view added (in addition to unicode characters)

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by ghYura** [comment]
Wow!
Thank you BIGGEST very much!
Thanks for work-through about
Gonna recommend DBeaver also for pathient customer intercommunications and feedback
___________
Just IMHO:
boolean [ X ] cell-depicted-value as true for me looks odd. 'X' - is crossing, like negate. [ V ] - for 'true' seems more fit (as so as column header shows): 
[v] column_name
COLOR differencing still highly desired as so as inner cell-different-value horizontal indentation
[https://user-images.githubusercontent.com/42974628/99234979-eeb54b80-27fd-11eb-8ea5-d3908f675b6f.jpg](https://user-images.githubusercontent.com/42974628/99234979-eeb54b80-27fd-11eb-8ea5-d3908f675b6f.jpg)
================
BEST regards!

**Comment by ejose19** [comment]
Agree with @ghYura regarding ```[X]``` being true is a bit off (especially because ```Booleans view: Checkboxes``` render a box with a cross for NULL values).
