### ISSUE TITLE
SQL Error [904] [42000]: ORA-00904: "WSESSION"."BLOCKING_SESSION": invalid identifier on Oracle 9.2.0.8 Database

### ISSUE THREAD

**Issue by luiscarlosbolanhos** [dbeaver/dbeaver#10647]
Hello there, 

I Just download the lastest EA 7.3.0 version, connect to a 9.2.0.8 Oracle database, try to monitor the Blocking Sessions and it show up:

SQL Error [904] [42000]: ORA-00904: "WSESSION"."BLOCKING_SESSION": invalid identifier
Error : 904, Position : 445, Sql = , Error Msg = ORA-00904: "WSESSION"."BLOCKING_SESSION": invalid identifier

SELECT
	wsession.sid waiting_session,
	wsession.serial# serial,
	wsession.logon_time,
	wsession.blocking_session_status,
	wsession.event,
	wsession.username waiting_user,
	wprocess.pid wait_pid,
	nvl(obj.object_name, '-') oname,
	nvl(obj.owner, '-') owner,
	wsession.row_wait_block# row_lock,
	wsession.blocking_session holding_session,
	hprocess.pid hold_pid,
	hsession.username holding_user
FROM
	v$session wsession
JOIN v$session hsession ON
	wsession.blocking_session = hsession.sid
JOIN v$process wprocess ON
	wprocess.addr = wsession.paddr
JOIN v$process hprocess ON
	hprocess.addr = hsession.paddr
LEFT JOIN dba_objects obj ON
	obj.object_id = wsession.row_wait_obj#
WHERE
	wsession.blocking_session IS NOT NULL
UNION
SELECT
	wsession.sid waiting_session,
	wsession.serial# serial,
	wsession.logon_time,
	wsession.blocking_session_status,
	wsession.event,
	wsession.username waiting_user,
	wprocess.pid wait_pid,
	nvl(obj.object_name, '-') oname,
	nvl(obj.owner, '-') owner,
	wsession.row_wait_block# row_lock,
	nvl(wsession.blocking_session, 0) holding_session,
	nvl(hprocess.pid, 0) hold_pid,
	nvl(hsession.username, '-') holding_user
FROM
	v$session wsession
LEFT JOIN v$session hsession ON
	wsession.blocking_session = hsession.sid
JOIN v$process wprocess ON
	wprocess.addr = wsession.paddr
LEFT JOIN v$process hprocess ON
	hprocess.addr = hsession.paddr
LEFT JOIN dba_objects obj ON
	obj.object_id = wsession.row_wait_obj#
WHERE
	wsession.sid IN (
	SELECT
		blocking_session
	FROM
		v$session)

ORA-00904: "WSESSION"."BLOCKING_SESSION": invalid identifier

**Comment by uslss** [comment]
thanks for the report

**Comment by luiscarlosbolanhos** [comment]
You are Really Welcome!

**Comment by luiscarlosbolanhos** [comment]
I suggest using GV$ view instead V$ becasuse to make it more RAC compatible, this is the description of the views on 9i:

Connected to:
Oracle9i Release 9.2.0.8.0 - Production
JServer Release 9.2.0.8.0 - Production

SQL> desc gv$session
 Name                                      Null?    Type
 ----------------------------------------- -------- -------------

 INST_ID                                            NUMBER
 SADDR                                              RAW(4)
 SID                                                NUMBER
 SERIAL#                                            NUMBER
 AUDSID                                             NUMBER
 PADDR                                              RAW(4)
 USER#                                              NUMBER
 USERNAME                                           VARCHAR2(30)
 COMMAND                                            NUMBER
 OWNERID                                            NUMBER
 TADDR                                              VARCHAR2(8)
 LOCKWAIT                                           VARCHAR2(8)
 STATUS                                             VARCHAR2(8)
 SERVER                                             VARCHAR2(9)
 SCHEMA#                                            NUMBER
 SCHEMANAME                                         VARCHAR2(30)
 OSUSER                                             VARCHAR2(30)
 PROCESS                                            VARCHAR2(12)
 MACHINE                                            VARCHAR2(64)
 TERMINAL                                           VARCHAR2(16)
 PROGRAM                                            VARCHAR2(64)
 TYPE                                               VARCHAR2(10)
 SQL_ADDRESS                                        RAW(4)
 SQL_HASH_VALUE                                     NUMBER
 PREV_SQL_ADDR                                      RAW(4)
 PREV_HASH_VALUE                                    NUMBER
 MODULE                                             VARCHAR2(48)
 MODULE_HASH                                        NUMBER
 ACTION                                             VARCHAR2(32)
 ACTION_HASH                                        NUMBER
 CLIENT_INFO                                        VARCHAR2(64)
 FIXED_TABLE_SEQUENCE                               NUMBER
 ROW_WAIT_OBJ#                                      NUMBER
 ROW_WAIT_FILE#                                     NUMBER
 ROW_WAIT_BLOCK#                                    NUMBER
 ROW_WAIT_ROW#                                      NUMBER
 LOGON_TIME                                         DATE
 LAST_CALL_ET                                       NUMBER
 PDML_ENABLED                                       VARCHAR2(3)
 FAILOVER_TYPE                                      VARCHAR2(13)
 FAILOVER_METHOD                                    VARCHAR2(10)
 FAILED_OVER                                        VARCHAR2(3)
 RESOURCE_CONSUMER_GROUP                            VARCHAR2(32)
 PDML_STATUS                                        VARCHAR2(8)
 PDDL_STATUS                                        VARCHAR2(8)
 PQ_STATUS                                          VARCHAR2(8)
 CURRENT_QUEUE_DURATION                             NUMBER
 CLIENT_IDENTIFIER                                  VARCHAR2(64)

SQL> DESC gv$process
 Name                                      Null?    Type
 ----------------------------------------- -------- -------------

 INST_ID                                            NUMBER
 ADDR                                               RAW(4)
 PID                                                NUMBER
 SPID                                               VARCHAR2(12)
 USERNAME                                           VARCHAR2(15)
 SERIAL#                                            NUMBER
 TERMINAL                                           VARCHAR2(16)
 PROGRAM                                            VARCHAR2(64)
 TRACEID                                            VARCHAR2(255)
 BACKGROUND                                         VARCHAR2(1)
 LATCHWAIT                                          VARCHAR2(8)
 LATCHSPIN                                          VARCHAR2(8)
 PGA_USED_MEM                                       NUMBER
 PGA_ALLOC_MEM                                      NUMBER
 PGA_FREEABLE_MEM                                   NUMBER
 PGA_MAX_MEM                                        NUMBER

Working with RAC the GV$ view are more useful than  with V$ ones. I hope it helps!

**Comment by luiscarlosbolanhos** [comment]
[https://www.oraclerecipes.com/monitoring/find-blocking-sessions](url)

Hope it helps, in 9i cant use bloquing_session, must use v$lock view instead.

**Comment by luiscarlosbolanhos** [comment]
This is an idea, its not perfect but maybe with a little work will work well:

        select wlsession.sid waiting_session,
               wsession.serial# serial,
               wsession.logon_time,
               wlsession.lmode,
               wlsession.type,
               wsession.username waiting_user,
               wprocess.pid wait_pid,
               nvl(obj.object_name, '-') oname,
               nvl(obj.owner, '-') owner,
               wsession.row_wait_block# row_lock,
               hlsession.sid holding_session,
               hprocess.pid hold_pid,
               hsession.username holding_user
          from v$session wsession, v$lock hlsession, v$lock wlsession
          join v$session hsession
            on wlsession.sid = hsession.sid
          join v$process wprocess
            on wprocess.addr = wlsession.addr
          join v$process hprocess
            on hprocess.addr = hsession.paddr
          left join dba_objects obj
            on obj.object_id = wlsession.id2
         where
              wlsession.block = 1
         	AND wlsession.request > 0
          AND hlsession.id1 = wlsession.id1
          AND hlsession.id2 = wlsession.id2
        union
        select wlsession.sid waiting_session,
               wsession.serial# serial,
               wsession.logon_time,
               wlsession.lmode,
               wlsession.type,
               wsession.username waiting_user,
               wprocess.pid wait_pid,
               nvl(obj.object_name, '-') oname,
               nvl(obj.owner, '-') owner,
               wsession.row_wait_block# row_lock,
               nvl(hlsession.sid, 0) holding_session,
               nvl(hprocess.pid, 0) hold_pid,
               nvl(hsession.username, '-') holding_user
          from v$session wsession, v$lock hlsession, v$lock wlsession
          left join v$session hsession
            on wlsession.sid = hsession.sid
          join v$process wprocess
            on wprocess.addr = wlsession.addr
          left join v$process hprocess
            on hprocess.addr = hsession.paddr
          left join dba_objects obj
            on obj.object_id = wlsession.id2
         where wsession.sid IN (SELECT
  (
  SELECT
    username
  FROM
    v$session
  WHERE
    sid = hlsession.sid) blocking_session
FROM
  v$lock hlsession,
  v$lock wlsession
WHERE
  wlsession.block = 1
  AND wlsession.request > 0
  AND hlsession.id1 = wlsession.id1
  AND hlsession.id2 = wlsession.id2
)

**Comment by luiscarlosbolanhos** [comment]
Based on your work and somo of this code:

[https://www.arunsankar.in/2013/03/locking-blocking-sessions-in-oracle.html](url)

**Comment by luiscarlosbolanhos** [comment]
This code works finding BLOCKING and BLOCKED objects/session in the database: I failed misserably trying to adapt it to your code, Sorry, I know you will succed, my mistake. There is the working piece of code who works on 9i. Best regards, hope it helps!

SELECT
	(
	SELECT
		username
	FROM
		v$session
	WHERE
		sid = hlsession.sid) blocker,
	hlsession.sid,
	' is blocking ',
	(
	SELECT
		username
	FROM
		v$session
	WHERE
		sid = wlsession.sid) blockee,
	wlsession.sid
FROM
	v$lock hlsession,
	v$lock wlsession
WHERE
	hlsession.block > 0
	AND wlsession.request > 0
	AND hlsession.id1 = wlsession.id1
	AND hlsession.id2 = wlsession.id2

**Comment by LonwoLonwo** [comment]
Hmm...
@luiscarlosbolanhos Unfortunately, I also cannot make a worthy replacement for our current script. The BLOCKING_SESSION column is important in it. 
How about this script? Does it return the result you want? Could you test it, please.

```
SELECT
	wsession.sid waiting_session,
	wsession.serial# serial,
	wsession.logon_time,
	wsession.username waiting_user,
	wprocess.pid wait_pid,
	nvl(obj.object_name, '-') oname,
	nvl(obj.owner, '-') owner,
	wsession.row_wait_block# row_lock,
	hprocess.pid hold_pid,
	hsession.username holding_user
FROM
	v$session wsession, v$session hsession, v$process wprocess, v$process hprocess, dba_objects obj 
WHERE wprocess.addr = wsession.paddr
	AND hprocess.addr = hsession.paddr
	AND obj.object_id(+) = wsession.row_wait_obj#
UNION
SELECT
	wsession.sid waiting_session,
	wsession.serial# serial,
	wsession.logon_time,
	wsession.username waiting_user,
	wprocess.pid wait_pid,
	nvl(obj.object_name, '-') oname,
	nvl(obj.owner, '-') owner,
	wsession.row_wait_block# row_lock,
	nvl(hprocess.pid, 0) hold_pid,
	nvl(hsession.username, '-') holding_user
FROM
	v$session wsession, v$session hsession, v$process wprocess, v$process hprocess, dba_objects obj
WHERE wprocess.addr = wsession.paddr
AND hprocess.addr(+) = hsession.paddr
AND obj.object_id(+) = wsession.row_wait_obj#;
```

**Comment by luiscarlosbolanhos** [comment]
[20201223-104441.xlsx](https://github.com/dbeaver/dbeaver/files/5736244/20201223-104441.xlsx)

Hi, the new script dont crash or anything, looks good for me, please check the file attached, it is the result for the query! I hope is ok for you too!

Thanks a lot and Merry Xmas!

**Comment by LonwoLonwo** [comment]
Nope.
@luiscarlosbolanhos We do not need all sessions, but only blocking sessions. Now i see the error. Let's try to change your version:

```sql
SELECT
	(
	SELECT
		username
	FROM
		v$session
	WHERE
		sid = hlsession.sid) blocker,
	(
	SELECT
		SERIAL#
	FROM
		v$session
	WHERE
		sid = hlsession.sid) serial,	
	hlsession.sid waiting_session,
	' is blocking ',
	(
	SELECT
		username
	FROM
		v$session
	WHERE
		sid = wlsession.sid) blockee,
	wlsession.sid holding_session
FROM
	v$lock hlsession,
	v$lock wlsession
WHERE
	hlsession.block > 0
	AND wlsession.request > 0
	AND hlsession.id1 = wlsession.id1
	AND hlsession.id2 = wlsession.id2;
```

**Comment by luiscarlosbolanhos** [comment]
![image](https://user-images.githubusercontent.com/39783091/103024123-d9c28b00-4514-11eb-9de0-e53e08105136.png)

It works wonderful! GREAT WORK!

![image](https://user-images.githubusercontent.com/39783091/103024223-0b3b5680-4515-11eb-9cd8-39481909facf.png)

**Comment by LonwoLonwo** [comment]
@luiscarlosbolanhos Thanks for help!

**Comment by luiscarlosbolanhos** [comment]
You are really welcome!

**Comment by LonwoLonwo** [comment]
arr. very difficult without a test environment.
@luiscarlosbolanhos Please check this query too. It contains more helpful columns, but I'm afraid I might be missing something.

```sql
SELECT (SELECT username
FROM v$session
WHERE 
sid = hlsession.sid) waiting_user,
(SELECT SERIAL#
FROM v$session
WHERE 
sid = hlsession.sid) serial,	
hlsession.sid waiting_session,
(SELECT username
FROM v$session
WHERE 
sid = wlsession.sid) holding_user,
wlsession.sid holding_session,
wsession.row_wait_block# row_lock,
nvl(obj.object_name, '-') oname,
nvl(obj.owner, '-') owner,
wsession.logon_time
FROM v$lock hlsession,
v$lock wlsession,
dba_objects obj,
v$session wsession
WHERE 
hlsession.block > 0
AND wlsession.request > 0
AND hlsession.id1 = wlsession.id1
AND hlsession.id2 = wlsession.id2
AND obj.object_id(+) = wsession.row_wait_obj#
```

**Comment by luiscarlosbolanhos** [comment]
[20201223-155710.xlsx](https://github.com/dbeaver/dbeaver/files/5737259/20201223-155710.xlsx)

**Comment by luiscarlosbolanhos** [comment]
There is the output ... There are only one blocked session and one bloquing session, the same enviroment as the first Query you posted, the new one have a lot of more rows and duplicated information. It takes longer to run to! 

Sorry If I dont have a enviroment to provide you, just my help!

**Comment by LonwoLonwo** [comment]
@luiscarlosbolanhos I understood. We will work with previous query that is above. Thank you again!

**Comment by luiscarlosbolanhos** [comment]
You are really welcome!

**Comment by luiscarlosbolanhos** [comment]
Maybe, there is a way of join both, and create a new one that works and have very useful information!

**Comment by LonwoLonwo** [comment]
@luiscarlosbolanhos Again, I want to ask you for a favour. I test on 8 oracle, and in 8 oracle, it seems, there is no DBA_LOCK. Does this request work correctly on Oracle 9? It is in the documentation, but suddenly not all columns have the correct name. This query helps resolve the blocking issue.

`select lock_type,mode_held,mode_requested,lock_id1,lock_id2,last_convert,blocking_others from DBA_LOCK`

**Comment by luiscarlosbolanhos** [comment]
[20201224-080527.xlsx](https://github.com/dbeaver/dbeaver/files/5739807/20201224-080527.xlsx)

Hi there, Whatever you need, If I can help, count with me. There is the output of the requested query!

Best regards

**Comment by luiscarlosbolanhos** [comment]
Hello Everybody, I just installed the 7.3.2 EA version, tested the Blocking Session feature on 9i, found it is very basic and simple to be useful. The following code are more useful, and is compatible with version 9i and newer... maybe can replease the current code for Blocking Session on all Oracle Versions. I have tested it successfuly from 9i to 18c and works great.

SELECT
	/*+ RULE */
	s.inst_id "DB INSTANCE",
	s.sid,
	s.serial#,
	p.spid "OS PID",
	s.sql_hash_value "HASH VALUE",
	s.username "ORACLE USER",
	s.lockwait,
	s.row_wait_block#,
	s.status,
	s.osuser "OS USER",
	s.machine,
	s.terminal,
	s.type,
	s.program,
	s.logon_time,
	s.last_call_et,
	s.module,
	l.id1,
	l.id2,
	decode(l.block, 0, 'WAITING', 1, 'BLOCKING') block,
	decode( l.LMODE, 1, 'No Lock', 2, 'Row Share', 3, 'Row Exclusive', 4, 'Share', 5, 'Share Row Exclusive', 6, 'Exclusive', NULL) lmode,
	decode( l.REQUEST, 1, 'No Lock', 2, 'Row Share', 3, 'Row Exclusive', 4, 'Share', 5, 'Share Row Exclusive', 6, 'Exclusive', NULL) request ,
	round(l.ctime / 60, 2) "MIN WAITING",
	l.type
FROM
	gv$process p,
	gv$session s,
	gv$Lock l
WHERE
	p.addr = s.paddr
	AND s.sid = l.sid
	AND (l.id1,
	l.id2,
	l.type) IN (
	SELECT
		l2.id1,
		l2.id2,
		l2.type
	FROM
		V$LOCK l2
	WHERE
		l2.request <> 0)
ORDER BY
	l.id1,
	l.id2,
	l.block DESC;

[20201229-084309.xlsx](https://github.com/dbeaver/dbeaver/files/5751081/20201229-084309.xlsx)
