### ISSUE TITLE
Support more distinct SQL Editor text colors

### ISSUE THREAD

**Issue by lukaseder** [dbeaver/dbeaver#10658]
#### System information: 
- Operating system (distribution) and version
Microsoft Windows [Version 10.0.18363.1198]

- DBeaver version
7.3.0.202011291229

- Java version 
OpenJDK Runtime Environment (build 14-ea+27-1339)

- Additional extensions
N/A

#### Connection specification:
N/A

#### Describe the problem you're observing:
As discussed here:
https://twitter.com/dbeaver_news/status/1336744981789364224

I accidentally renamed a column because of a missing comma:

```sql
SELECT
  col1 -- Missing comma here
  col2,
  col3
FROM t
```

It took me way longer than it should have to see my mistake. More sophisticated syntax highlighting as e.g. in IntelliJ could have helped spot the problem more quickly. An example can be seen here:
https://twitter.com/missingfaktor/status/1336734896908349443

![image](https://user-images.githubusercontent.com/734593/101748578-04e8bb80-3acd-11eb-8ab9-38673edc07ad.png)

I'm not sure if the colors should be so "aggressive" by default, but having the option would certainly be useful. Not just for aliases, but also for other things. Often, a column reference has the same name as a table reference, and it would be interesting to be able to visually distinguish between the two types of object.

**Comment by uslss** [comment]
Thanks for suggestion

**Comment by E1izabeth** [comment]
It's done in https://github.com/dbeaver/dbeaver/pull/21788 and will be available in the next release (DBeaver 23.2.5)
The feature is turned off by default, you can enable it here 

![image](https://github.com/dbeaver/dbeaver/assets/28875055/dca4fef3-3bd6-484b-a11b-21cf916d1423)

**Comment by E1izabeth** [comment]
Done in scope of this issue #10831
