### ISSUE TITLE
windows store version unable to switch languages

### ISSUE THREAD

**Issue by wangweiweiwei** [dbeaver/dbeaver#10654]
machine translation:

Dbeaver ce installed in windows store cannot switch language. the prompt file has no permission, and the error is as follows: "Can't switch language to zh"
Reason:
Can't save startup configuration - access denied.
You could try to change national locale manually in 'C:\Program Files\WindowsApps\DBeaverCorp.DBeaverCE_7.3.0.0_x64__1b7tdvn0p0f9y\ Dbeaver.ini'. refer to readme.txt file for details. "

I think this problem is widespread, and many people in the comment area have given feedback on this problem. You can also go to the windows store to install Dbeaver ce and then enter Window-> Preferences-> User Interface to switch languages to reproduce this problem.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. As a workaround please open properties of DBeaver label.
-nl -en should be written there. Delete it, open DBeaver and change the language in Window>Preferences>User interface

**Comment by wangweiweiwei** [comment]
> 谢谢你的报告。作为解决方法，请打开 DBeaver 标签的属性。
> - nl - en 应该写在那里。删除它，打开 DBeaver 并更改 Window>首选项>用户界面中的语言

```
C:\Program Files\WindowsApps\DBeaverCorp.DBeaverCE_7.3.0.0_x64__1b7tdvn0p0f9y\dbeaver.ini
```
I revised this file to warn me that I have no permission，So is the administrator.
I think I should switch languages on the interface instead of other methods,I don't need to solve it now.
I want you to fix it.
😘

**Comment by wangweiweiwei** [comment]
> Thank you for the report. As a workaround please open properties of DBeaver label.
> -nl -en should иу written there. Delete it, open DBeaver and change the language in Window>Preferences>User interface
```
C:\Program Files\WindowsApps\DBeaverCorp.DBeaverCE_7.3.0.0_x64__1b7tdvn0p0f9y\dbeaver.ini
```
I revised this file to warn me that I have no permission，So is the administrator.
I think I should switch languages on the interface instead of other methods,I don't need to solve it now.
I want you to fix it.
😘

**Comment by aisbergde** [comment]
It is hard to use dbeaver for new Windows users, if it is not possible to change some settings, for example the language. And the readme is poor about this. There is a bit about `-data` option, but this is doesn't work for the language settings.

I tried

> "C:\Program Files\DBeaver\dbeaver.exe" -data "C:\Users\ggoer\AppData\Roaming\DBeaverData\workspace6"

> "C:\Program Files\DBeaver\dbeaver.exe" -data D:\Users\ggoer

and it looks like different workspaces are used. There are also some folders `.metadata` created. But whenever I try to change the language I get the same error, no matter in which workspace I am:

```
Can't save startup configuration - access denied.
You could try to change national locale manually in 'C:\Program Files\DBeaver\dbeaver.ini'. Refer to readme.txt file for details.
  C:\Program Files\DBeaver\dbeaver.ini
  C:\Program Files\DBeaver\dbeaver.ini
```

`-nl en` works. OK.

But why not just write this in the readme:

> At the moment it is not (or not always) possible to change the language via the settings, as a workaround please use the following parameter.

A normal new user thinks: If I can't change the language setting, then I probably can't change the other settings either. How am I supposed to work with the program then?

**Comment by kseniiaguzeeva** [comment]
@aisbergde I agree that the option to change language has to work correctly and it is going to be fixed in 21.0.1 release. 
We gave preference to other tasks for some time, because there was the workaround

**Comment by serge-rider** [comment]
Unfortunately it is not possible to modify Store application start parameters. As well as modify any of its configuration files.
At the moment the only way to modify default language is thru app parameter or by changing dbeaver.ini. It is Eclipse platform limitation.

Probably we need to publish different version of DBeaver CE for different Windows languages.

**Comment by cryptedx** [comment]
Just run DBeaver as Adminstrator and you can change it. Easiest way my SQL Bros!

**Comment by IrinaYarova** [comment]
DBeaver Version 23.0.1.202303250535
Windows 10 22H2

Can't change the interface language, what I have done:
1) In the dbeaver.ini added "-nl en" before the line -vmargs;
2) Ran DBeaver as Adminstrator and tried to change the interface language to "en".

Please help me with it!)

**Comment by wangweiweiwei** [comment]
The new version can now switch languages, thank you for your contribution!

**Comment by assyrus-favolo** [comment]
On my installation (version `25.2.1.202509231142`) changing language still doesn't work
