### ISSUE TITLE
Opportunity to disable virtual PK creation for tables without PK

### ISSUE THREAD

**Issue by arnomoisan** [dbeaver/dbeaver#10657]
Hy,
I use Dbeaver since one month and I really love it. Clearly better than my old frog software.
I have on request for the data edit permission. Is it possible to restrict the data edit only if we declare the rowid id table. 
We have the alert message "No Unique key"  if we don't select all the primary key columns but if think it's dangerous because if we use the default option "Use All Columns", we can update others rows than selected.
Thanks for your Help

**Comment by kseniiaguzeeva** [comment]
It is really nice to hear you find DBeaver useful! I think we already have an option to help you without implementing the feature. Please:
1. Open Window>Preferences>Connections>Drivers>Oracle
2. Enable **Use ROWID to identify rows**
![Screenshot 2020-12-11 at 12 57 11](https://user-images.githubusercontent.com/51405061/101889675-bca2c980-3bb0-11eb-93b3-a9a2a4ff207e.png)

Rowid will be used as Primary key for tables without PK. DBeaver will not ask you to create virtual foreign keys for such tables

**Comment by arnomoisan** [comment]
Hi

Thanks for your quick answer.
I’ve already enable this option

 

cid:image005.jpg@01D6CFB0.D318A610

 

This is an example of how it works now :

 

My table TBL have the primary key (codsoc,codtbl,cletbl)

 

cid:image006.jpg@01D6CFB0.D318A610

 

I select 2 of 3 primary key columns.

When i change a data in the grid, i have the message but if I choose « Use All columns », it will update all my rows wich have the same value than the columns in the select . Also, the message never prompt again if i choose this option, even if i don’t check « Do not ask again … ». I have to drop/create the connexion for recover the alert.

 

cid:image010.jpg@01D6CFB0.D318A610

 

If i use the rowid in the select, it’s OK

 

cid:image009.png@01D6CFB0.34914E20

 

What i would like is to have a security for the grid editing. « Use all columns » seems to me a dangerous option.

 

My version of DBeaver is the 7.3.0.

**Comment by arnomoisan** [comment]
Hi
Thanks for your quick answer.

I’ve already enable this option


![image](https://user-images.githubusercontent.com/75778530/101893187-b73f8200-3ba4-11eb-9ad7-610ac26c1975.png)

This is an example of how it works now :

My table TBL have the primary key (codsoc,codtbl,cletbl)

![image](https://user-images.githubusercontent.com/75778530/101893244-c8888e80-3ba4-11eb-96f8-08cd682d6c3b.png)

I select 2 of 3 primary key columns.
When i change a data in the grid, i have the message but if I choose « Use All columns », it will update all my rows wich have the same value than the columns in the select . Also, the message never prompt again if i choose this option, even if i don’t check « Do not ask again … ». I have to drop/create the connexion for recover the alert.

![image](https://user-images.githubusercontent.com/75778530/101894303-48632880-3ba6-11eb-887d-acda66d6e3f3.png)

If i use the rowid in the select, it’s OK

![image](https://user-images.githubusercontent.com/75778530/101894361-5add6200-3ba6-11eb-849c-470bffcde047.png)

What i would like is to have a security for the grid editing. « Use all columns » seems to me a dangerous option.

My version of DBeaver is the 7.3.0.

Best regards

**Comment by kseniiaguzeeva** [comment]
It is a bug. Thank you for the clarifying.

To reproduce:
Precondition: Enable Use ROWID to identify rows
1. execute in Oracle `SELECT PK1, PK2, JUST_COLUMN FROM HR."10657" WHERE PK2 =3`
2. Change a cell value in ResultSet and press Save

**Comment by p91paul** [comment]
i believe selecting rowid **is** required. Table editor actually selects rowid under the hood. To do that for custom queries I think you would need to edit the query before sending it to Oracle, which isn't good practice.

**Comment by kseniiaguzeeva** [comment]
I had to do a little investigation. The primary key consisted of several columns cannot be recognized in the ResultSet if some of its columns were excluded from the query. That's why DBeaver asks you to create a virtual foreign key and it is not a bug.
ROWID is a common thing for Oracle tables. You can apply read-only option to make your database read-only to avoid tables editing. For this:
1. Select **Edit connection** in the database context menu in DB Navigator
2. Go to General>enable read-only connection and press Ok

Can it solve your request?

**Comment by arnomoisan** [comment]
Sorry but if i disable the grit edit option, i lose a very usefull option of Dbeaver. That is not a possibility.
I think that is really dangereous to autorise multiple rows modification.
If DBeaver is able to prompt a message when the condition of potential multiple row modification, it's a good start but the defaut option "Use All columns" should not existed or not be the default one.

![image](https://user-images.githubusercontent.com/75778530/102202612-d5202600-3ec7-11eb-99da-db7e74b8356a.png)


Moreover, if choose one time the option, the message is nerver prompted even if we don't check "Do not ask again ..."

**Comment by kseniiaguzeeva** [comment]
The opportunity to disable virtual foreign key creation  will be added for tables without primary key.

**Comment by arnomoisan** [comment]
Hi, Thanks for spending time on my problem.
I dont understand the solution you propose because in my case, my table have a primary key. 

![image](https://user-images.githubusercontent.com/75778530/102784598-ede37c80-439c-11eb-94bc-bea222b139fb.png)
What i need is to disable the option "Use all columns" wich is really dangerous .

**Comment by uslss** [comment]
verified
