### ISSUE TITLE
Hi, I would like to Know How Can I sort the column names , I am using Postgres and Deaver Enterprise 7.3.0.

### ISSUE THREAD

**Issue by jota2406** [dbeaver/dbeaver#10670]
#### System information: 
- Operating system (distribution) and version
- DBeaver version

#### Connection specification:
- Database name and version

**Comment by uslss** [comment]
Hi @jota2406 ,
if I understand you correct, column order could be changed by clicking at Name column title in Table Metadata Editor
![2020-12-11_18h21_13](https://user-images.githubusercontent.com/31996417/101921234-d1498680-3bdd-11eb-84fd-064d913fc4a1.gif)

**Comment by jota2406** [comment]
I'm sorry, it's not what I was looking for, if I have a Table with three column : #1 Data1, #2 Data2, #3 Data3 I would like change to #1 Data3, #2 Data2 , #3 Data1. Thank you

**Comment by lemon-juice** [comment]
You can't change column order in postgres because it is not supported by the database. You can reorder columns in DBeaver when you view table data and save it as a filter to be remembered but this will only affect your DBeaver view, it will not be saved in the database.
