### ISSUE TITLE
Square brackets are escaped incorrectly

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#10671]
#### System information: 
- Operating system: Windows 10
- DBeaver version: 7.3.1 EA
- Additional extensions: none

#### Connection specification:
- Database name and version: Microsoft SQL Server 15.00.2000
- Driver name: Microsoft JDBC Driver 8.2
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  SSH

#### Describe the problem you're observing:
Brackets are being escaped invalid when identifier already contains brackets.

#### Steps to reproduce, if exist:
1. Create table named 'Album'
2. Rename it to 'Album.Test'
3. Persist changes

This will generate following SQL statement:
```
EXEC master.sys.sp_rename N'master.dbo.Album' , N'[Album.Test]', 'OBJECT' GO
```
Which will rename 'Album' to '[Album.Test]' (with brackets)

4. Refresh schema to verify that table actually was renamed to '[Album.Test]'
5. Try to rename it again to 'Album'

This will generate another SQL statement:
```
EXEC master.sys.sp_rename N'master.dbo.[Album.Test]' , N'Album', 'OBJECT' GO
```
Which is incorrect. According to [this answer](https://stackoverflow.com/a/56575613) on stackoverflow, valid statement would be:
```
EXEC master.sys.sp_rename N'master.dbo.[[Album.Test]]]' , N'Album', 'OBJECT' GO
```

As a feature request I propose to add connection configuration flag to allow to use QUOTENAME function to properly quote identifiers.

**Comment by uslss** [comment]
not reproducible against 21.1.2

**Comment by uslss** [comment]
steps 4-5 are still reproducible

**Comment by ShadelessFox** [comment]
We've fixed only escaping behavior.

Edge quotes still escape invalidly because it's hard to determine whether they're part of the identifier itself or just unnecessary quotes.

**Comment by Matvey16** [comment]
Verified
