### ISSUE TITLE
SQL output tab must be visible along with results

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#10683]
Currently it is one of result tabs. Not very convenient when you need to see both for debugging.
Also includes #5998

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/104333243-107f3600-5502-11eb-9c34-d1f3d0da4425.png)

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/104336564-98b30a80-5505-11eb-91f8-7af1d2145704.png)

Auto-show option is enabled by default for now.

**Comment by kseniiaguzeeva** [comment]
verified
