### ISSUE TITLE
Virtual foreign keys lost when reopen project

### ISSUE THREAD

**Issue by rilyu** [dbeaver/dbeaver#10681]
I found the same issue as #6854 but I can not reopen it.

os: macOS 10.15.4
DBeaver: 7.3.0.202011291229
database: postgresql
steps: open one table -> click Virtual -> add one Virtual foreign key -> close the table tab -> right click the project and click refresh -> reopen the table, then the vfk lost, but found Virtual references

close DBeaver and reopen it will have the same issue.
data of file .dbeaver/data-sources.json is correct, it seems that it is not read correctly when opening the project.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
