### ISSUE TITLE
Edit Actions Error

### ISSUE THREAD

**Issue by WellskDBeaver** [dbeaver/dbeaver#10692]
I’m attempting to add  “Edit Actions” to my toolbar via Custom Perspective.  However; I get an error message ( see attached ).

How can I get around / resolve this error?

System information:
Windows 2012 R2
DBeaver 7.2.4

Connection specification:
Database Oracle 11g
![Edit Actions](https://user-images.githubusercontent.com/75385195/102141707-e6652600-3e26-11eb-96d2-98f689f8b6b6.png)
 

Thank you.

**Comment by kseniiaguzeeva** [comment]
It's a bug. Thank you for the report.

Note: can be fixed with https://github.com/dbeaver/dbeaver/issues/4885 and https://github.com/dbeaver/dbeaver/issues/10580

**Comment by serge-rider** [comment]
Edit toolbar was deprecated and removed from the configuration.
Additionally icons for standard Eclipse actions were updated and redundant icons removed from the main toolbar.

**Comment by uslss** [comment]
verified
