### ISSUE TITLE
export varchar field as insert sql not correct if it include backslash character "\" ,   must convert to double "\\"

### ISSUE THREAD

**Issue by dolt131943** [dbeaver/dbeaver#10697]
#### System information: 
- Operating system (distribution) and version: macOs 10.15.7
- DBeaver version: 7.3.0.202011291229
- Additional extensions : none(default)

#### Connection specification:
- Database name and version: mysql  8.0
- Driver name:   mysql:mysql-connector-java:8.0.17
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:

process backslash character "\\" error when export or copy as SQL ,
when use "export Data"/"export to SQL", or "Advanced Copy"/"Copy as SQL" 

export varchar ( 'abc\\" abc' ) as SQL value must be escape to 'abc\\\\" abc'。

#### Steps to reproduce, if exist:

1. create a table that include a varchar field, (e.g.) create table t1(f1 varchar(256));
2. this varchar field set a string that include a backslash "\\" , (e.g.) f1 = 'abc \\" abc';
3. use export data or advanced copy in row as SQL, the SQL's f1 value will same as 'abc\\" abc' (e.g.) : insert into t1(f1) values('abc\\" abc');
4. use this SQL to insert data  the result data will lost this backslash, because 'abc\\" abc'  will escape to 'abc" abc';

this result is not correct,  the backslash is a escape character,  this export / copy as SQL,  must export SQL like this: 
insert into t1(f1) values('abc\\\\" abc'); 
escape character must be escaped.

#### Include any warning/errors/backtraces from the logs
none

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by tekook** [comment]
@kseniiaguzeeva same goes for Searching and filtering in the data tables.
I have a table containing php-class-names (thus haveing a backslash in it) if you filter or search for it, all backslashes have to be escaped with a double backslash).
The filter suggests a single slash.
![image](https://user-images.githubusercontent.com/976407/105842587-b89eff80-5fd6-11eb-8e13-78dfee45073a.png)
![image](https://user-images.githubusercontent.com/976407/105842720-ebe18e80-5fd6-11eb-9ed2-70eaf620a1b5.png)
![image](https://user-images.githubusercontent.com/976407/105842740-f3a13300-5fd6-11eb-9559-1e728a328646.png)


Is it the same problem or shell I open another issue?

**Comment by kseniiaguzeeva** [comment]
Thank you for the report too. Let your issue remains here. I will create another ticket if different causes will be found.

**Comment by flambchap** [comment]
Hi @dolt131943. Forgive me if I'm mistaken, but it seems like everything works like expected here. The query
```sql
INSERT INTO t1 (f1) VALUES
    ('abc\"abc'),
    ('abc\\"abc');
```
inserts values `abc"abc` and `abc\"abc` since backslash is indeed an escape character and needs to be escaped.

**Comment by flambchap** [comment]
Ok, now I see what you meant there. That's indeed a bug. Working on that.

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified

**Comment by dolt131943** [comment]
> Ok, now I see what you meant there. That's indeed a bug. Working on that.

sorry for my poor english
