### ISSUE TITLE
[clickhouse] DBeaver produces incorrect query when altering table

### ISSUE THREAD

**Issue by borkor** [dbeaver/dbeaver#10699]
When ALTERING TABLE and adding new column cDBeaver produces following query

```sql
ALTER TABLE mytable ADD mynewcolumn UInt8 DEFAULT 0
```

It is obviously missing COLUMN keyword. It should be 
```sql
ALTER TABLE mytable ADD COLUMN mynewcolumn UInt8 DEFAULT 0
```

The produced error is 
```
SQL Error [62]: ClickHouse exception, code: 62, host: anp01.dc1.local, port: 8123; Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 34 ('mynewcolumn'): mynewcolumn UInt8 DEFAULT 0 NOT NULL. Expected one of: INDEX, CONSTRAINT, COLUMN (version 20.9.3.45 (official build))
```

I am using clickhouse-jdbc-0.2.4.jar

Is this an error in the driver itself?

**Comment by LonwoLonwo** [comment]
Thanks for bug report.
The standard syntax does not include the word COLUMN when the table is modified. We need to add it to Сlickhouse.

**Comment by uslss** [comment]
verified
