### ISSUE TITLE
Automatically detect data length from CSV when generating new columns

### ISSUE THREAD

**Issue by corkybeta** [dbeaver/dbeaver#10702]
I frequently import CSVs to tables created by the import wizard. DBeaver automatically sets each text column to varchar(1024) and then 30% of the time the import fails with a 'data will be truncated' error, which I fix by finding the offending columns and rows that need adjusting and redoing the import.

SSMS is able to detect the correct data length from scanning the CSV. Please can this be added? These tables are designed to be deleted soon after use, so being able to avoid setting every column to varchar(4096) or spending time curating the table would be greatly appreciated.

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by uslss** [comment]
verified
