### ISSUE TITLE
Support unix socket connections with junixsocket

### ISSUE THREAD

**Issue by jonjonw** [dbeaver/dbeaver#10701]
## Problem
dbeaver cannot connect to a local database over a unix socket.

## Proposed Solution
Use [junixsocket](https://github.com/kohlschutter/junixsocket) to connect to the local unix socket.

I know local socket connections are not implemented in JDBC but it looks like junixsocket adds [support](https://kohlschutter.github.io/junixsocket/dependency.html) for it. It would be great not to have to create a password and edit my database config files to connect to my local postgresql sever.

**Comment by kseniiaguzeeva** [comment]
Please tell your database

**Comment by uslss** [comment]
there is no update on the issue for a long time.
if it is still actual for you - feel free to reopen it with an additional info

**Comment by jonjonw** [comment]
Hi, I'm not sure why this ticket was closed. Were you waiting for a response from me? It sounded like you wanted feedback from your database team?

**Comment by jix** [comment]
This is already possible, but initially it wasn't clear to me either. Since I found this issue long before I found the solution, I'll post my solution here:

* Create a PostgreSQL connection, then in the "Main" tab of the connection settings:
  * Enter `/{database}?socketFactoryArg=/var/run/postgresql/.s.PGSQL.5432&socketFactory=org.newsclub.net.unix.socketfactory.PostgresqlAFUNIXSocketFactory&ignore=` as host (replacing `/var/run/postgresql/.s.PGSQL.5432` with whatever socket path you want to connect to)
    * This is a bit awkward, but the only way I found to specify this per connection
  * Click "Edit Driver Settings" at the bottom
    * In the "Libraries" tab
      * "Add Artifact" Group Id: `no.fiken.oss.junixsocket` Artifcat Id: `junixsocket-common`
      * "Add Artifact" Group Id: `no.fiken.oss.junixsocket` Artifcat Id: `junixsocket-native-common`
      * Click the "Download/Update" button to install these libraries

This uses an updated fork of junixsocket, following the official postgres jdbc documentation, see the "Unix sockets" section at https://jdbc.postgresql.org/documentation/head/connect.html

**Comment by umbe1987** [comment]
> This is already possible, but initially it wasn't clear to me either. Since I found this issue long before I found the solution, I'll post my solution here:
> 
>     * Create a PostgreSQL connection, then in the "Main" tab of the connection settings:
>       
>       * Enter `/{database}?socketFactoryArg=/var/run/postgresql/.s.PGSQL.5432&socketFactory=org.newsclub.net.unix.socketfactory.PostgresqlAFUNIXSocketFactory&ignore=` as host (replacing `/var/run/postgresql/.s.PGSQL.5432` with whatever socket path you want to connect to)
>         
>         * This is a bit awkward, but the only way I found to specify this per connection
>       * Click "Edit Driver Settings" at the bottom
>         
>         * In the "Libraries" tab
>           
>           * "Add Artifact" Group Id: `no.fiken.oss.junixsocket` Artifcat Id: `junixsocket-common`
>           * "Add Artifact" Group Id: `no.fiken.oss.junixsocket` Artifcat Id: `junixsocket-native-common`
>           * Click the "Download/Update" button to install these libraries
> 
> 
> This uses an updated fork of junixsocket, following the official postgres jdbc documentation, see the "Unix sockets" section at https://jdbc.postgresql.org/documentation/head/connect.html

You are my hero.... I cannot believe how hard it was for me to find this solution!...
thank you so much for posting this, I was banging my head to figure out what the hell I was supposed to put as password after creating my postgres username in Linux Mint with ` sudo -u postgres createuser --superuser $USER`!!!!
I mean, I barely knew that the postgres leveraged with apt package manager had this Unix-socket thing that drove me crazy ;)

**Comment by jonjonw** [comment]
> This is already possible, but initially it wasn't clear to me either. Since I found this issue long before I found the solution, I'll post my solution here:

Thanks @jix! I gave it a shot but I get "Cannot find method "setCreated" in java.net.Socket. Unsupported JVM?" When I try to test the connection.

**Comment by cizordj** [comment]
Thank you @jix, you made my day.

**Comment by kohlschuetter** [comment]
@jonjonw, @umbe1987: Newer versions of the original junixsocket support PostgreSQL and DBeaver out of the box, and the "setCreated" bug is also fixed.

See [the above junixsocket issue](https://github.com/kohlschutter/junixsocket/issues/120) for some instructions how to add com.kohlschutter.junixsocket jars as dependencies and how to configure them (the socket factory setup is slightly different).

**Comment by CristianCardosoA** [comment]
I expend like 3 hrs with this GUI utility trying to connect via socket ... which is not common supported by any DB viewer.
I tried everything like @jix said unfortunately does not work even with mysql connection.

At the end I moved to MySQL Workbench ... because of that.


Pretty simple just to specify socket path: /var/mysql.socket for example

![Screen Shot 2022-12-27 at 14 32 50](https://user-images.githubusercontent.com/18292956/209728840-86a03d6f-eaa7-4d46-a59a-9fe958b7cbbd.png)

**Comment by asfaltboy** [comment]
I had to slightly alter the steps from [Jix's comment above](https://github.com/dbeaver/dbeaver/issues/10701#issuecomment-913148861):

1. I needed to specify depdencies in the xml format to be able to install them, this is described in https://kohlschutter.github.io/junixsocket/dependency.html#bodyColumn . After clicking "Add artifact" I pasted in both dependencies like so:

  ```xml
  <dependencies>
    <dependency>
      <groupId>com.kohlschutter.junixsocket</groupId>
      <artifactId>junixsocket-common</artifactId>
      <version>2.7.2</version>
    </dependency>
    <dependency>
      <groupId>com.kohlschutter.junixsocket</groupId>
      <artifactId>junixsocket-native-common</artifactId>
      <version>2.7.2</version>
    </dependency>
  </dependencies>
  ```

2. Then I used the `org.newsclub.net.unix.AFUNIXSocketFactory$URIScheme` factory to specify a unix socket file path , after escaping symbols using urlencode:

   ```
   printf "file:///tmp/.s.PGSQL.5432" | jq -rR @uri | pbcopy
   ```

   Ref: https://kohlschutter.github.io/junixsocket/dependency.html#postgresql
