### ISSUE TITLE
a dialog which do not show the code

### ISSUE THREAD

**Issue by beiyinghu** [dbeaver/dbeaver#10705]
<img width="981" alt="截屏2020-12-16 下午5 43 39" src="https://user-images.githubusercontent.com/47131226/102332301-de43ec80-3fc6-11eb-8877-af0d4a8d1524.png">

#### System information: 
- Operating system (distribution) and version :macOS 11.0.1
- DBeaver version:7.3.0.202011291229
- Java version:JDK15
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
Hi @beiyinghu ,
can you provide some steps to reproduce it? 
Which database do you use?

**Comment by akilovich** [comment]
Fixed in the scope of #10535. The fix is already available in the recent [EA build](https://dbeaver.io/files/ea/).
