### ISSUE TITLE
Incorrect update/delete statement

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#10718]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.3.1

#### Connection specification:
- Database name and version Clickhouse

#### Describe the problem you're observing:
When trying to update cells value dbeaver generates:
```sql
-- Auto-generated SQL script #202012171458
UPDATE default.trip_data
	SET vendor_id='VTS1'
	WHERE medallion='C386A225E08B3D3E94DF7C058744604E';

```
that is incorrect.
It should be 
```sql
ALTER TABLE default.trip_data
UPDATE
	vendor_id = 'VTS1'
WHERE
	medallion = 'C386A225E08B3D3E94DF7C058744604E';
```
https://clickhouse.tech/docs/ru/sql-reference/statements/alter/update/

Delete:
Generated:
```sql
-- Auto-generated SQL script #202012171501
DELETE FROM default.trip_data
	WHERE medallion='C386A225E08B3D3E94DF7C058744604E';
```
should be accordingly to [this](https://clickhouse.tech/docs/ru/sql-reference/statements/alter/delete/)

**Comment by uslss** [comment]
#10699

**Comment by LonwoLonwo** [comment]
Fixed. But be careful. This is expensive operation, and therefore not all the usual cases are supported. I'm not sure, for example, that the update will work when chosen "Use all columns as key".

**Comment by uslss** [comment]
verified
