### ISSUE TITLE
Allow dbeaver git to use the ssh agent.

### ISSUE THREAD

**Issue by skotos** [dbeaver/dbeaver#10714]
**Is your feature request related to a problem? Please describe.**
Pulling and Pushing from a git remote is not possible with private key authentication with either JSch or Apache MINA sshd

**Describe the solution you'd like**
Could we have the option of requesting the OS SSH agent to handle the ssh connection for the DBeaver git module? Similar to the option we have for db connections over ssh tunnelling.

**Describe alternatives you've considered**
Git pushes and pulls happen in a terminal outside of the IDE.  (We cannot use password auth on our git server.)

**Additional context**
![dbauth](https://user-images.githubusercontent.com/1259908/102444944-781aa080-407e-11eb-84bd-ed03dfebd060.png)
![gitauth](https://user-images.githubusercontent.com/1259908/102444946-794bcd80-407e-11eb-8642-ba01deb93036.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the good idea!

**Comment by skotos** [comment]
Thanks!  And thanks for a great project.

**Comment by serge-rider** [comment]
DBeaver uses EGit for Git integration.
Generally it already supports SSH agents: https://stackoverflow.com/questions/13396405/eclipse-git-and-ssh-agent
There are known issues with different agents: https://bugs.eclipse.org/bugs/show_bug.cgi?id=179924

Anyhow we can't fix it from DBeaver side as we rely on EGit implementation.
