### ISSUE TITLE
Option to close connections when deleting database on Sql Server

### ISSUE THREAD

**Issue by majkinetor** [dbeaver/dbeaver#10712]
**Is your feature request related to a problem? Please describe.**

If you try to delete database that is in use, it will fail.

**Describe the solution you'd like**

Add option 

- [ ] close existing connections 

This is something that MS Managment Studio has:

![image](https://user-images.githubusercontent.com/85767/102390787-2833cf00-3fd5-11eb-9654-970d100ab8ee.png)

**Describe alternatives you've considered**
There are no alternatives except doing it manually which defeats the purpose of menu item and bulk delete

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea. 
As a workaround you can remove default status from the database (select another one as a default via database context menu) and delete it.

**Comment by majkinetor** [comment]
That is not workaround. Another systems are using the database, not dbeaver.

**Comment by ShadelessFox** [comment]
This option is enabled by default now.
After implementing #10958, we will add checkbox to toggle this option inside object delete dialog.

**Comment by uslss** [comment]
verified

**Comment by majkinetor** [comment]
Thank you for quick response. You are awesome.
