### ISSUE TITLE
Not displaying FK/PK on delete/on update conditions correct for mysql

### ISSUE THREAD

**Issue by martea** [dbeaver/dbeaver#10717]
Were trying to update constraint to no action, and always displayed Restricted, since i saw Cascade/Restricted that it diffed i thought it worked. but after execution i had to go to mysql workbench to verify this.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

To reproduce 

1. Open Foreign keys tab for table Xeniia.fk in Metadata Editor> Foreign key has Restrict action
2. execute in SQL Editor:

```
ALTER TABLE Xeniia.fk DROP FOREIGN KEY fk_FK;
ALTER TABLE Xeniia.fk ADD CONSTRAINT fk_FK FOREIGN KEY (fk) REFERENCES Xeniia.pk(pk) ON DELETE no action ON UPDATE no action;
```
3. Refresh Foreign keys tab for the table

Expected: the fields are changed on no action;
Actual result: the action is not changed .
![aPV6Umhimj](https://user-images.githubusercontent.com/51405061/102766472-3dbb4700-438f-11eb-976e-aa03d3b0daaf.gif)

**Comment by LonwoLonwo** [comment]
Hello @martea 
According [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html), "Restrict" and "No action" are the same.  

> 
> RESTRICT: Rejects the delete or update operation for the parent table. Specifying RESTRICT (or NO ACTION) is the same as omitting the ON DELETE or ON UPDATE clause.
> 
> NO ACTION: A keyword from standard SQL. In MySQL, equivalent to RESTRICT. The MySQL Server rejects the delete or update operation for the parent table if there is a related foreign key value in the referenced table. Some database systems have deferred checks, and NO ACTION is a deferred check. In MySQL, foreign key constraints are checked immediately, so NO ACTION is the same as RESTRICT.
