### ISSUE TITLE
The MySQL client still needs to be installed to import the. SQL file

### ISSUE THREAD

**Issue by iseesec** [dbeaver/dbeaver#10715]
#### System information: 
- Operating system (distribution) and version: macos big sur 11.1
- DBeaver version：版本7.3.0.202011291229

#### Connection specification:
- Database name and version: 8.0.19

#### Describe your question:The MySQL client still needs to be installed to import the. SQL file

Why do I still need to install MySQL client to import. SQL files? I don't need to use dbeaver to install MySQL client. Moreover, Navicat can import directly without installing the client.

It is recommended to be the same as the built-in jdbc driver

**Comment by kseniiaguzeeva** [comment]
Please try  the latest release 7.3.1. Native client was added to Mac https://github.com/dbeaver/dbeaver/issues/7976

**Comment by uslss** [comment]
there is no update on the issue for a long time.
if it is still actual for you - feel free to reopen it with an additional info
