### ISSUE TITLE
Missing color in session manager

### ISSUE THREAD

**Issue by Andrius77** [dbeaver/dbeaver#10724]
#### System information: 
- Operating system (distribution) and version - Windows 10 PRO 19042.685
- DBeaver version   - 7.3
- Additional extensions - no extensions

#### Connection specification:
- Database name and version - Mysql 8.17
- Driver name - Driver for MySQL 8 and later
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  - NO

#### Describe the problem you're observing:
All screens (SQL Editor, Object Tree, Screens under System info) has a background color depending on type of connection: Development(no color) , UAT(green) and Production (some Orange-brown). 
But it doesn't work in "Session manager". "Session manager" page looks like "Development" type page without and background color. It's easy to confuse and do some bad stuff in production.

#### Steps to reproduce, if exist:

Type of connection is set under "Connection settings">"General">> field "Connection type"

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
