### ISSUE TITLE
Index cannot be created

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#10728]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 7.3.1

#### Connection specification:
- Database name and version clickouse

#### Describe the problem you're observing:
Incorrect SQL is generated when trying to create index
`CREATE INDEX ontime_Quarter_IDX ON default.ontime (Quarter);`
should be
`ALTER TABLE [db].name ADD INDEX name expression TYPE type GRANULARITY value [AFTER name]`
https://clickhouse.tech/docs/ru/sql-reference/statements/alter/index/

**Comment by uslss** [comment]
#10726 
#10718 
#10699

**Comment by LonwoLonwo** [comment]
Indexes in Clickhouse are not the same as indexes in standard DB, like PG or Oracle. Their structure is more complicated.
And unfortunately, it does not fit into the standard index model in DBeaver.
Unfortunately, the current Clickhaus driver does not return the list of indexes.
Therefore, while we did not know how to get a list of all table indexes, we remove the index tab.
However, you can always see indexes in DDL table.

**Comment by uslss** [comment]
verified
