### ISSUE TITLE
Data Editor: multiple cell selection skips after opening cell context menu

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10725]
#### System information: 
- Operating system (distribution) and version MacBook Air
- DBeaver version 7.3.1 EA

#### Steps to reproduce, if exist:
1. Open a table in Data Editor
2. Select several cells
3. Press Ctrl+Click via touchpad

Expected: the context menu appears and the cells remain selected
Actual result: the context menu for the only cell appears, the selection disappears

**Comment by flambchap** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified
