### ISSUE TITLE
SQL editor disappearing code

### ISSUE THREAD

**Issue by imilos84** [dbeaver/dbeaver#10722]
#### System information: 
- MacOS Big Sur 11.1
- DBeaver version 7.3.0

#### Connection specification:
- Athena
- Driver name AthenaJDBC42_2.0.9.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When I try to edit existing code, e.g. press enter between lines in order to add a new line of code, existing code disappears for around 2 seconds.

#### Include any warning/errors/backtraces from the logs
No errors

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. It is a duplicate and should be fixed in https://github.com/dbeaver/dbeaver/issues/10450
Could please download the latest release https://dbeaver.io/download/?

**Comment by imilos84** [comment]
It is fixed, thanks.
