### ISSUE TITLE
Edit host in exist user

### ISSUE THREAD

**Issue by ZhouJiaZhi** [dbeaver/dbeaver#10737]
The host field can only be modified when creating a new user. After the user is successfully created, this field cannot be modified.
I hope this field can be modified, so that I don’t need to modify this field by deleting the user then create a new user.
![image](https://user-images.githubusercontent.com/20750357/102707574-481a0a00-42d7-11eb-8c4b-109c728954fa.png)

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by flambchap** [comment]
We've decided to add a possibility to rename the user from the navigator tree instead, which solves the original problem as well.

**Comment by uslss** [comment]
verified
