### ISSUE TITLE
The content of HEX Editor settings partly disappeared in Preferences on Mac

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10731]
#### System information: 
- Operating system (distribution) and version Mac Catalina
- DBeaver version 7.3.1 EA

#### Steps to reproduce, if exist:
Open Window>Preferences>Editors>Data Editor>Binary Editors>HEX Editor

Expected: all tab fields have a data
Actual result: the data is not visible in some fields:
![Screenshot 2020-12-19 at 12 33 01](https://user-images.githubusercontent.com/51405061/102686154-c652af80-41f6-11eb-853e-e51ef655cedd.png)

**Comment by flambchap** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified
