### ISSUE TITLE
Connection settings tab name is not clearly for macOS Community

### ISSUE THREAD

**Issue by JacobCN** [dbeaver/dbeaver#10735]
#### System information: 
- macOS Big Sur 11.1
- DBeaver Community Version 7.3.0.202011291229

#### Steps to reproduce, if exist:
1. Preferences > User Interface > Theme: Light types
2. Database navigator > Create/Edit Connection > select 'Connection settings',
3. Issue: Color of the right tab name is the same with background color. The tab name is not clearly.

#### Screenshots
![image](https://user-images.githubusercontent.com/18402491/102698600-9ac4d900-4279-11eb-9f53-b224a45a3874.png)

![image](https://user-images.githubusercontent.com/18402491/102698586-7ff26480-4279-11eb-8f5a-4f52f1e00e97.png)

**Comment by kseniiaguzeeva** [comment]
It should be fixed in the latest release. Please try it https://dbeaver.io/download/.

Feel free to ask to reopen the ticket if it is actual for you in DBeaver 7.3.1 too.

**Comment by cosmos-fly** [comment]
This feature of version 7.3.1.202012201616 works fine now on Mac Big Sur 11.1. Thanks all~!
