### ISSUE TITLE
Mac focus issues

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10740]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 7.3.1 EA 

#### Describe the problem you're observing:
The focus issues still appear here:
1. Preferences>Data Editor>Data formats
2. Preferences>User Interface>Confirmations
3. Table column properties tab

**Comment by flambchap** [comment]
The same issue is also present in the transformer dialog.

**Comment by flambchap** [comment]
As far as I can see, point number 3 is not related to focus and should be handled separately.

**Comment by flambchap** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified
