### ISSUE TITLE
Remove PgBouncer error when objects are edited

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10742]
#### System information: 
- DBeaver version 7.3.1 EA

#### Connection specification:
- Database name and version Greenplum

#### Description:
You hardly ever can create an object via Metadata Editor and do not receive error "Prepared statement ... already exists" 

#### Steps to reproduce, if exist:
Open a table and try to create a primary key or an index or a comment

Expected: the object is created
Actual result: 
- the object cannot be created,
- error appears "Prepared statement ... already exists"

Note: try to do the same with other tables several times if the issue cannot be reproduced from the first time

#### Include any warning/errors/backtraces from the logs
Maybe it can be useful http://www.pgbouncer.org/faq.html

**Comment by LonwoLonwo** [comment]
Implemented in 21.0.1

**Comment by LonwoLonwo** [comment]
Now, by default, we add an "prepareThreshold=0" parameter to the connection string for postgreSQL and GreenPlum. It helps to fight the problem of this ticket, but may worsen performance. Enabling this function in the settings will return everything back.

![2021-03-03 21_05_34-DBeaver Enterprise 21 0 0 - _EXT FDB_ Script-6](https://user-images.githubusercontent.com/45152336/109938442-12cf6680-7ce1-11eb-8ad0-08bed2c3b20e.png)

**Comment by kseniiaguzeeva** [comment]
verified
