### ISSUE TITLE
"Filter by column" option for a field defined as Array(LowCardinality(String)) produces wrong query 

### ISSUE THREAD

**Issue by borkor** [dbeaver/dbeaver#10743]
"Filter by column" option for a field defined as Array(LowCardinality(String)) produces wrong query.

wrong query generated
```sql
AND mycolumn IN (myvalue)
```
should be
```sql
AND mycolumn IN ['myvalue']
```

SQL Error [60]: ClickHouse exception, code: 60, host: anp01.dc1.local, port: 8123; Code: 60, e.displayText() = DB::Exception: Table default.myvalue doesn't exist. (version 20.9.3.45 (official build))

DBeaver version 7.3.0

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
Hello @borkor 
Can you please provide table DDL example query with data insert query for tests?

**Comment by uslss** [comment]
cannot reproduce it against 21.0.3
seems the issue is fixed
![image](https://user-images.githubusercontent.com/31996417/115386138-b1f0e480-a1e1-11eb-873b-6202001915c6.png)
If it is still actual for you - feel free to reopen it
