### ISSUE TITLE
error executing dbeaver zipped version in windows 10

### ISSUE THREAD

**Issue by verajosemanuel** [dbeaver/dbeaver#10741]
#### System information: 
- windows 10
- DBeaver version 7.3 (zip)

#### Describe the problem you're observing:
Dialog error: 
![dbeavererror](https://user-images.githubusercontent.com/15836677/102712883-8528d100-42c4-11eb-9fb9-913c6c4e5d21.png)

#### Steps to reproduce, if exist:

1. Uncompressed dbeaver zip version
2. double click dbeaver.exe
3.  error dialog

Tried to locate 32 bits version just in case....to no avail

**Comment by SubOptimal** [comment]
Based on the path `C:\Progam Files (x86)\` I assume you have a 32 bit Java installed.

- Could you install a 64 bit Java version to see if this would solve your issue.

- Which Java version do you have installed?
- Based on https://www.oracle.com/java/technologies/javase/javase9-archive-downloads.html the last 32 bit Java version from Oracle seems to be < Java 9. To run dbeaver you would need Java >= 11.

**Comment by verajosemanuel** [comment]
I have no privileges to install any software on this machine. I hoped I could use portable dbeaver. Java Version is 12

**Comment by kseniiaguzeeva** [comment]
@SubOptimal was right. DBeaver doesn't support 32-bit Java
