### ISSUE TITLE
Cannot update the field value of the result set

### ISSUE THREAD

**Issue by qiqingli** [dbeaver/dbeaver#10759]
Dbeaver:7.3.1
OS:macOS Big Sur
Java:OpenJDK Runtime Environment 18.9 (build 11+28)
Database:MySQL

When updating data in the result set, the automatically generated SQL statement always uses the fully qualified name, which causes the sharding database to not be updated normally. After removing the fully qualified name, it can be updated normally. How to set the fully qualified name not to be used automatically?

![image](https://user-images.githubusercontent.com/20805098/102860022-02407b80-4468-11eb-8453-8d076ea2ef1a.png)

**Comment by kseniiaguzeeva** [comment]
When you change a data, please open the table context menu and select Generate SQL>Update. You can disable fully qualified name there.
![Screenshot 2020-12-22 at 10 28 07](https://user-images.githubusercontent.com/51405061/102861260-6cddc100-4440-11eb-9223-307e9c0e4993.png)

**Comment by kseniiaguzeeva** [comment]
However, we will add the ability to disable **disable fully qualified name** from preview Script too.

**Comment by uslss** [comment]
verified
