### ISSUE TITLE
MS SQL Server Kerberos Authetication Failure 

### ISSUE THREAD

**Issue by khe35280** [dbeaver/dbeaver#10756]
#### System information: 
- Operating system: Ubuntu 20.04.1 LTS
- DBeaver version: 7.3.1

#### Connection specification:
- Database name and version: MS SQL Server
- Driver name: mssql-jdbc 8.2.0.jre8

#### Describe the problem you're observing:
Not able to connect to SQL server with Kerberos authentication, even though the same connection with the settings and credentials works fine after rolling back to version 7.3.0.  

#### Include any warning/errors/backtraces from the logs
![Screenshot from 2020-12-21 10-36-45](https://user-images.githubusercontent.com/76449135/102810497-afd46180-4378-11eb-9cbe-622dbbb437b3.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
This may be related to the new way of Java packaging. Now all dbeaver packages include their own Java so any config changes/certificates configured in system JDK won't be used. 
We have a feature request #10904 which will bring back packages without bundled Java.

**Comment by serge-rider** [comment]
Probably fixed by #10904 .
If you use Kerberos configuration in the local Java configuration then you need to install DBeaver without bundled JDK.
