### ISSUE TITLE
Add confirmation settings for the unpinned result tabs so it can be disabled

### ISSUE THREAD

**Issue by syedhassanshah** [dbeaver/dbeaver#10763]
**Is your feature request related to a problem? Please describe.**
This is a result of latest update. It is annoying to click on "Yes" every single time a new query needs to run. When Alt+X is pressed, following message shows up without a choice to permanently chose "Yes". Imagine if you have to run many queries on regular bases. The default behavior should allow the user to run any query with minimum number of clicks or presses of button and that is what majority of the DB tools do.

Message: There are "2" unpinned result tabs. Do you want to close these tabs before executing new query?

**Describe the solution you'd like**
There should be an option for this in the "Window > Preferences> User Interface > Confirmations" settings.

**Describe alternatives you've considered**
I could not find any alternative so far which is why I am submitting this request.

**Additional context**

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by ShadelessFox** [comment]
A checkbox was added to remember the choice.
![image](https://user-images.githubusercontent.com/35821147/103014314-a2250480-454f-11eb-9cbf-28fd24d0efc3.png)

**Comment by kseniiaguzeeva** [comment]
The option is back and can be configured in Window > Preferences> User Interface > Confirmations" settings
