### ISSUE TITLE
add "Without saving" button 

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#10769]
DBeaver 7.3.1
Postgresql 11

Case:

I had a several open SQL Editor tubs.
Right button click on tub and choose "Close all"

![изображение](https://user-images.githubusercontent.com/61137576/102959092-6878dd00-4500-11eb-9d31-d5ee7904215b.png)

it would be convenient to have a "Without saving" button. Instead of deselecting and click on "Save selected"

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by detkliff** [comment]
21.0.4 not changed

**Comment by uslss** [comment]
duplicates #5675
