### ISSUE TITLE
NUMERIC(18,0) 'rounding' to about 16 significant digits

### ISSUE THREAD

**Issue by duncankinnear** [dbeaver/dbeaver#10766]
We are using DBeaver to view data in a proprietary database called 'Vortex' (from Trifox.com).

When viewing the relevant column definition in the list of columns, it is listed as 'NUMERIC(18,0)'. It is essentially a 'Long', but the proprietary database engine only reports all numbers as 'NUMERIC(X,Y)'.

When displaying the data in this column, the 18 digits that are stored in it are being binary 'rounded' to a significant number of digits.

For instance, when the column contains the 'raw' value of 993322180250676232, it is being displayed as 993322180250676220.

I have tried playing around with various setting in the 'Data Formatting' section of the 'Edit Connection' dialog, but nothing seems to 'fix' it.

Any idea how I can get the column displaying all 18 digits of these numbers?

**Comment by kseniiaguzeeva** [comment]
Did you make settings in Connection settings>Data Editor>Data Formats? Please try to change Maximum fraction digits. If it doesn't help, try to disable numeric formatting on the same page
![Screenshot 2020-12-23 at 15 46 47](https://user-images.githubusercontent.com/51405061/102997477-5023b500-4536-11eb-8925-236704f3c77c.png)

**Comment by uslss** [comment]
there is no update on issue for a long time.
if it is still actual for you - feel free to reopen it

**Comment by duncankinnear** [comment]
Sorry, I have been very busy and I hadn't got back to this issue.
The 'Edit connection' dialog on the version of DBeaver that I am running (Version 7.1.1.202006281720) does not have the same fields that you are talking about:
![image](https://user-images.githubusercontent.com/58455447/106965335-54372980-67a8-11eb-8bfb-c5ddf522786f.png)

Also, I have tried setting the maximum fraction digits to both 18 and 19, and this has not fixed the issue.
