### ISSUE TITLE
Show default value for new rows

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#10761]
We can show default column values in data viewer for new rows. We mustn't use them on row insert but we can show default values which will be inserted if cell will be left empty.
We can use light grey color (the same which we use for NULL values) to show defaults.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/102886545-5c404180-4466-11eb-9e8c-a273e6e731c1.png)

**Comment by uslss** [comment]
verified
