### ISSUE TITLE
PostgreSql - dbeaver loses connection if the screen is idle.

### ISSUE THREAD

**Issue by amitdixit** [dbeaver/dbeaver#10762]
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version : 7.3.1
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version : PostgreSql
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Whenever the screen/ application is idle dbeaver loses connection ideally it should keep the connection.
This happens even while working with MS SQL Server.
I have to make Keep-Alive setting to 600 so as to keep it active for atleast 10 min and after 10 min I get the connection Invalidated pop-up. This is not an elegant approach.
Other tools like Sql Server Management Studio or for that matter Oracle Toad keep the connection alive in the background.

**Comment by kseniiaguzeeva** [comment]
The idea of keep-alive is to set a period to ping the database. Try to set it 60 and DBeaver will ping the database every 1 minute and the database remain connected.
It should help.

**Comment by amitdixit** [comment]
> The idea of keep-alive is to set a period to ping the database. Try to set it 60 and DBeaver will ping the database every 1 minute and the database will remain connected.
> It should help.

Thanks @kseniiaguzeeva .It helped.
