### ISSUE TITLE
Exasol transaction conflict handling

### ISSUE THREAD

**Issue by allipatev** [dbeaver/dbeaver#10775]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.3.0.202011291229
- Additional extensions: no

#### Connection specification:
- Database name and version: Exasol 7.0.4
- Driver name: Exasol JDBC driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Describe the problem you're observing:

In case of transaction conflict DBeaver raises no exception, but just re-runs the statement.
How can this behavior be controlled?

#### Steps to reproduce, if exist:
3 session test case: one session to see what is being run and two other sessions for conflict.

Session 1, autocommit **on**.
```
-- Step 0
create schema if not exists test;
open schema test;
create table if not exists test.jobs (c1 int);
create table if not exists test.products (c1 int);
-- Step 5
flush statistics;

select
	s.STMT_ID
	, s.SQL_TEXT
FROM
	EXA_STATISTICS.EXA_DBA_AUDIT_SQL s
where
	1=1
	and s.SESSION_ID in (<session id you got in session 2>)
	and s.SQL_TEXT not like '/*snapshot execution*/ %'
order BY
	s.STMT_ID DESC
limit 10
;
/*
For DBeaver you'll see something like
*/
STMT_ID|SQL_TEXT                               |
-------|---------------------------------------|
     33|insert into stg.jobs values(3)         |
     32|/*EXAConnection.rollback()*/ rollback; |
     31|ROLLBACK /* AUTO */                    |
     30|insert into stg.jobs values(3)         |
     27|insert  into stg.ETL_PRODUCTS values(2)|
     24|select * from stg.jobs                 |
     21|alter session set profile  ='ON'       |
     18|alter session set query_cache = 'OFF'  |
     17|COMMIT /* AUTO */                      |
     16|/*EXAConnection.commit()*/ commit;     |
/*
Statement 31 probably comes from the driver.
The question is who triggers statements 32 and 33?
*/
```

Session 2, autocommit **off**.
```
select 'transaction 2|' || current_timestamp ||'|'|| current_session  as 'TRANS       |  -------CURRENT DATE------  |--------SESSION-------';
-- Pin this tab.

alter session set query_cache = 'OFF'; 
alter session set profile  ='ON';
--
-- Step 1

select * from test.jobs;

--
-- Step 3
--
insert  into test.PRODUCTS values(2);

--
-- Step 4
-- 
insert into test.jobs values(3);
/* After the step 4 other tools return
[40001] GlobalTransactionRollback msg: Transaction collision: automatic transaction rollback. (Session: ...)
and this is expected behavior.
For DBeaver behavior see step 5.
*/
```

Session 3, autocommit **on**.
```
select 'transaction 3|' || current_timestamp ||'|'|| current_session  as 'TRANS       |  -------CURRENT DATE------  |--------SESSION-------';
-- Pin this tab.

--
-- Step 2
insert into test.jobs values(2);
```

#### Include any warning/errors/backtraces from the logs
There are no relevant log entries.

Transactions settings:
![image](https://user-images.githubusercontent.com/58830344/102998878-590d8a00-4528-11eb-9af1-1fca68334aaf.png)

**Comment by allipatev** [comment]
This settings block controls the mentioned behavior, right?
![image](https://user-images.githubusercontent.com/58830344/105830524-e2035f80-5fc5-11eb-9cfd-d471ec02a517.png)

**Comment by Sargul** [comment]
PR should enhance the reporting of the error. I tested with the provided script pre-fix and post-fix.

Post-fix the error is displayed in a prominent way but nevertheless the transaction is rolled back but DBeaver still shows 2 open statements

![image](https://user-images.githubusercontent.com/5595511/108112428-5b0e4800-7096-11eb-813b-27f7d9c5044a.png)
