### ISSUE TITLE
Click house query generation is incorrect for clickhouse Db

### ISSUE THREAD

**Issue by serak** [dbeaver/dbeaver#10783]
#### System information: 
- Operating system (distribution) and version Windows 10 20H2
- DBeaver version 7.3.1
- Additional extensions -

#### Connection specification:
- Database name and version - clickhouse
- Driver name - clickhouse
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  - No

#### Describe the problem you're observing:
on GUI table creations the generated DDL query is wrong and cannot be executed on ClickHouse
#### Steps to reproduce, if exist:
Under Tables > Right click and create  New table > On Colums Right click and select Create New Column > check the generated DDL
#### Include any warning/errors/backtraces from the logs

-not required

**Comment by uslss** [comment]
duplicates #10699 
will be fixed in 7.3.2
anyway, thanks for the report
