### ISSUE TITLE
Foreign key and Refresh button

### ISSUE THREAD

**Issue by Pitools** [dbeaver/dbeaver#10782]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.3.1.202012201616

#### Connection specification:
- Database name and version: SQLite 3.32.3
- Driver name: SQLite JDBC 3.32.3.1

#### Describe the problem you're observing:
When you click the refresh button, the foreign key changes the name.
![dbeaver_FK_02](https://user-images.githubusercontent.com/55897247/103035754-0a3c1080-4579-11eb-8c76-16bef4dbbe4b.jpg)
![dbeaver_FK_03](https://user-images.githubusercontent.com/55897247/103035764-11631e80-4579-11eb-8d1d-090f6d302d5c.jpg)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
This is side effect of https://github.com/dbeaver/dbeaver/issues/8286

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified
