### ISSUE TITLE
Copy as SQL for multiple row

### ISSUE THREAD

**Issue by arnomoisan** [dbeaver/dbeaver#10786]
Hi,
Since 7.3.0 version, the option "Copy as SQL" is not working properly if i select more than one row.

![image](https://user-images.githubusercontent.com/75778530/103077520-320a9300-45d0-11eb-98af-508a69043ec4.png)

![image](https://user-images.githubusercontent.com/75778530/103077382-f5d73280-45cf-11eb-8a1d-a5544e9bb1f0.png)

The result of the copy is 

INSERT INTO CEM (CODCEM,LIBCEM) VALUES
	 ('ZONE','Emplacement de zone'),
	 ('MAXQTE','Qté maximum');

This SQL command cannot be execute, at least in an oracle Bdd.
In version 7.2.5, the generated code was correct.

**Comment by LonwoLonwo** [comment]
@arnomoisan thanks for the bug report

as a workaround you can use "Export data", choose SQL format, use the settings from the picture below and "Copy to clipboard".

![2020-12-24 12_31_34-Window](https://user-images.githubusercontent.com/45152336/103078966-072a3a00-45e4-11eb-9ceb-37b92981afe9.png)

![2020-12-24 12_31_47-Window](https://user-images.githubusercontent.com/45152336/103078971-0a252a80-45e4-11eb-8ca0-df8671b8270b.png)

**Comment by arnomoisan** [comment]
Thank's for the quick answer and the fix to be comming.

For the moment, i use the bellow option

![image](https://user-images.githubusercontent.com/75778530/103080869-122a9d80-45d7-11eb-905f-33b5839b99e3.png)

**Comment by LonwoLonwo** [comment]
Fixed in 7.3.4 for Oracle and other DB that do not support multi-insertion
Will be available [here](https://dbeaver.io/) at 2021-02-01

**Comment by uslss** [comment]
verified
