### ISSUE TITLE
Rename shortcut (F2) not working for table columns

### ISSUE THREAD

**Issue by greenpeas** [dbeaver/dbeaver#10809]
dBeaver 7.3.1. PostreSQL.
In 7.3.0 F2 worked.
![image](https://user-images.githubusercontent.com/3856344/103191471-37285480-48e6-11eb-9955-7f23170d5a95.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by vicreal** [comment]
In DBeaver **7.3.2** (PostgreSQL) not working also.

**Comment by ShadelessFox** [comment]
Hello @greenpeas,

Try unbinding all conflicting shortcuts that use <kbd>F2</kbd> in <kbd>Preferences</kbd> &rArr; <kbd>User Interface</kbd> &rArr; <kbd>Keys</kbd>, so that only <kbd>Rename</kbd> remains:

![image](https://user-images.githubusercontent.com/35821147/116410557-91f29e00-a83d-11eb-9b17-6a0bf5424888.png)

**Comment by vicreal** [comment]
Checked **21.0.3**. Rename columns not working on F2.

> _Try unbinding all conflicting shortcuts that use F2 in Preferences ⇒ User Interface ⇒ Keys_

Yes. If unbind conflict command "Показывать описание подсказки" then renaming columns by F2 working.
But F2 should work "out of the box". That is, initially (when installing the program) there should be no conflict.

![F2 conflict](https://user-images.githubusercontent.com/72701351/116768339-81f5dc80-aa3e-11eb-97e1-791c76ec12ed.jpg)

**Comment by ShadelessFox** [comment]
Indeed, I agree that such fundamental feature should be working out of the box. 

I suggested a workaround to start from, at least for now. It needs further examination.

Thanks for response.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
