### ISSUE TITLE
create mysql table bug

### ISSUE THREAD

**Issue by bouyeijiang** [dbeaver/dbeaver#10807]
i need on the editor to edit sql to add primary key.

Another problem is that the connection to MySQL always shows the state of waiting for the link

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. Don't you have Constraints tab in Table Editor or an error appears? 
Please tell me DBeaver version, OS and send log files. 
Please check that Advanced Navigator view is on (select Connection view in the database context menu)
![Screenshot 2020-12-28 at 10 35 03](https://user-images.githubusercontent.com/51405061/103198269-f259e900-48f8-11eb-9574-22c1830f59d5.png)

**Comment by bouyeijiang** [comment]
Dbeaver is latest community version and running on linux mint os

**Comment by kseniiaguzeeva** [comment]
Please tell me also:
- Don't you have Constraints tab in Table Editor or an error appears?
- Please check that Advanced Navigator view is on (select Connection view in the database context menu)
- Could you also send me a video with the problem?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
if it is still actual for you - feel free to reopen it with an additional info

**Comment by bouyeijiang** [comment]
When I expand the database link, it always shows loading.Especially for the slow response of the database, the query status occasionally appears when executing the query
