### ISSUE TITLE
add a column(column comment) in record view

### ISSUE THREAD

**Issue by Ncamel-zz** [dbeaver/dbeaver#10814]
**Describe the solution you'd like** 
In record view,there are two column: column name、column value.
Can you add one more: column comment ?
Now,I can only see the comment by moving cursor to column name, it isn't convenient,especially when there are too many columns I'm not familiar with

Thanks a lot !

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
duplicates #5529

**Comment by Ncamel-zz** [comment]
they are not the same thing.  
if there is a independent field to display column  comment  (in record view)  , it is very intuitionistic for people who dont familiar with the columns.
when i use pl/sql developer,this feature is one of good features impressed me.

**Comment by pro9dan** [comment]
It would be great to have such a feature
