### ISSUE TITLE
Connection Configuration UI not loading properly when password is huge

### ISSUE THREAD

**Issue by dpacosta** [dbeaver/dbeaver#10824]
#### System information: 
- macOS Catalina 10.15.7
- DBeaver Community 7.3.1

#### Describe the problem you're observing:
DBeaver Community loads the "Connection Configuration" modal following the text length of its settings. This is particularly annoying when you use IAM tokens, that are 1000+ characters long, as password and you need to edit the connection from time to time because the tokens expire. The modal length being adjusted based on the texts that were loaded seems wrong.

#### Steps to reproduce, if exist:
Set up a connection with a 1000+ characters long password.
Load the "Connection Configuration" window

**After loading the modal**:
![Screen Shot 2020-12-28 at 9 51 03 PM](https://user-images.githubusercontent.com/6018933/103260686-cde32880-495b-11eb-92ed-48b2fdf2c34c.png)

**After dragging to edit the password**: 
![Screen Shot 2020-12-28 at 9 54 53 PM](https://user-images.githubusercontent.com/6018933/103260685-ccb1fb80-495b-11eb-849e-675936ee164b.png)

**Comment by serge-rider** [comment]
It was fixed in f864f62c7ab0e70e8457ff92a2873b72058cd155 I think

**Comment by kseniiaguzeeva** [comment]
Tested on PostgreSQL connection.

**Comment by dpacosta** [comment]
> It was fixed in [f864f62](https://github.com/dbeaver/dbeaver/commit/f864f62c7ab0e70e8457ff92a2873b72058cd155) I think

I just updated dbeaver and it's fixed. Thanks.
