### ISSUE TITLE
PostgreSQL Debugging

### ISSUE THREAD

**Issue by pkfox** [dbeaver/dbeaver#10829]
Hi there, despite installing the debugger extension to my Debian 11 PostgreSQL installation I see no menus or icons related to debugging in Dbeaver - Dbeaver is installed on Win 10 and is CE version 7.3

TIA
Pete Kane

BTW how do I create an account on your forum ?

**Comment by kseniiaguzeeva** [comment]
Debugger was removed from menu. You can find it on the upper toolbar now
![Screenshot 2021-01-06 at 08 27 46](https://user-images.githubusercontent.com/51405061/103732918-83b41400-4ff9-11eb-85ff-cd3449531a7d.png)
