### ISSUE TITLE
Stored Procedures being split (broken)

### ISSUE THREAD

**Issue by acrey1** [dbeaver/dbeaver#10821]
System information:

Operating system (distribution) and version: Windows Server 2019
DBeaver version: 7.3.x
Java version: 1.8.0_271
Additional extensions: None

Connection specification:
Database name and version: Informix IDS 12.x
Driver name: Informix 4.50.4.1
Do you use tunnels or proxies (SSH, SOCKS, etc)? No

Describe the problem you're observing:
When accessing stored procedures, Source for procedures is being split mid-line based on blocks of (?approx 265) characters.

Steps to reproduce, if exist:
F4 on Procedure name

Example:
![2020-12-29 08_57_25-Incorrect (Split) Stored Procedure](https://user-images.githubusercontent.com/69837156/103245574-b5532c80-49b4-11eb-879e-f181e983710a.png)

![2020-12-29 08_58_50-Correct (Unsplit) Stored Procedure](https://user-images.githubusercontent.com/69837156/103245587-c00dc180-49b4-11eb-8b89-631857fe1cf4.png)

**Comment by LonwoLonwo** [comment]
@acrey1 thanks for the bug report.
Problem will be fixed soon https://github.com/dbeaver/dbeaver/issues/10578 
Close as duplicate.
