### ISSUE TITLE
Feature's requests I miss

### ISSUE THREAD

**Issue by jviure** [dbeaver/dbeaver#10825]
Hi!  I don't know if it's possible but, for example sometimes I need to keep working with Navicat for something. I usually work with postgres. I work a lot with trigger's.. it's not possible to enable/disable a trigger without code? botton right to the trigger and enable or disable? or to  edit the trigger actions (add actions as insert, delete, update) without code? 

Or edit sequences without code? 

Or edit Data type's without code?

With Navicat I find very usefull the ability to compare databases structure. 

This are some features I miss in DBeaver, thanks a lot for the effort! keep working  :+1:

**Comment by kseniiaguzeeva** [comment]
You can enable/disable triggers via Tools in triggers context menu
![1](https://user-images.githubusercontent.com/51405061/103286001-92466e00-49f0-11eb-852c-ed859a1c3bbd.png)

Other actions are not available via UI. Which database do you use?

**Comment by uslss** [comment]
there is no update on issue for a long time.
if it is still actual for you - feel free to reopen it with an additional info
