### ISSUE TITLE
Filtering where "_" is in the View/Table/Column name

### ISSUE THREAD

**Issue by acrey1** [dbeaver/dbeaver#10820]
#### System information: [issue is cross-platform]
- Operating system (distribution) and version: Windows Server 2019
- DBeaver version: 7.3.x
- Java version: 1.8.0_271
- Additional extensions: None

#### Connection specification: [issue is cross-platform]
- Database name and version: Informix IDS 12.x
- Driver name: Informix 4.50.4.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
In the filter options, there is a requirement to use the "\_" character when filtering views/tables/columns (e.g. SAP utilises User fields in tables that commence "U\_", which may need to be included or excluded).  The "\_" is a valid character in tables, views and fields.  However, the "\_" character has been used as a special character in the Connection filter fields.

Possible solution - use regex for filters
Possible solution - allow shift-style character like "\" in filters (e.g. U\\_%)

#### Steps to reproduce, if exist:
F4 (Edit Connection) -> click on Filters/Tables or Filters/Columns -> click Enable -> Click on Include->Add or Exclude->Add

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
was implemented in #9719 before

**Comment by acrey1** [comment]
https://github.com/dbeaver/dbeaver/wiki/Configure-Filters ?

**Comment by acrey1** [comment]
Fixed in #9719 but also needs to be included in documentation...
