### ISSUE TITLE
[MariaDB/MySQL] export data from data editor in new table generate incorrect table DDL

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#10836]
DBeaver 7.3.1

Step to reproduce:
1. Open table data editor
2. Select "Export data" from data editor.
3. Choose as target MySQL/MariaDB database
4. Create new table name
5. See Target DDL 

Result: some types mapped incorrect and without attributes (column length)
![2020-12-29 15_43_04-DBeaver Enterprise 7 3 0 - film](https://user-images.githubusercontent.com/45152336/103359015-16b7f000-4ac8-11eb-9801-792a4280f656.png)
This syntax is incorrect for table creating.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
