### ISSUE TITLE
Create DB based on template

### ISSUE THREAD

**Issue by ebelloni** [dbeaver/dbeaver#10835]
Hi everyone,

I recently switched from PgAdmin to DBever to manage my PostgreSQL DB. I noticed something missing, which is important for me: when I create a DB (new database ...) with PgAdmin I have the possibility to use any DB of the server as a template (see attachment 1). This allows me to easily make a clone of the original DB and it's, for me, very useful. With DBever the same function (create-> database) allows me to use only the default templates (see attachment 2).

Is there any way I don't know from the interface?
Anyone have a solution?

Thanks in advance.
Greetings.
Alberto

![PgAdmin new DB (attachment 1)](https://user-images.githubusercontent.com/76780387/103355490-ae104980-4aae-11eb-9308-46bb27a8f4e3.png)
![DBever new DB (attachment 2)](https://user-images.githubusercontent.com/76780387/103355497-b23c6700-4aae-11eb-92e8-524d7a399ac9.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by ebelloni** [comment]
Great! Well done.

**Comment by uslss** [comment]
verified
