### ISSUE TITLE
Copy to Windows clipboard of MySQL/MariaDB text field value is truncated to 195 characters

### ISSUE THREAD

**Issue by mwittmann** [dbeaver/dbeaver#10833]
#### System information: 
- Windows 10 Pro build 19041.685
- DBeaver Version 7.3.0.202011291229
- Additional extensions: none

#### Connection specification:
- Database name and version: MariaDB 10.3.23-MariaDB-cll-lve
- Driver name: MariaDB (class org.mariadb.jdbc.Driver)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
In the SQL Editor Results grid, I have column that is a MySQL/MariaDB "text" field. When I highlight a single cell and press Shift+Enter, I get the Value Editor Dialog which shows the full value of the field (length: 4365 characters). However when I select all of the text (Ctrl+A) and copy it (Ctrl+C) only the first 195 characters are copied. I've verified this by pasting the clipboard value into the Notepad++ editor.

The same thing happens in the Value pane. The entire column value is shown in the Value pane, but if I highlight and copy the value, only the first 195 characters ends up in the Windows Clipboard. It's frustrating to only be able to copy a truncated value!

When I export the row as SQL to a file, the entire "text" field value is correctly exported.

#### Steps to reproduce, if exist:
Described above.

#### Include any warning/errors/backtraces from the logs
No log entries for anything at the time of running the query and viewing the "text" field value.

**Comment by kseniiaguzeeva** [comment]
Unfortunately I cannot reproduce. Could you give a value example?

**Comment by mwittmann** [comment]
Hmmm... tried to reproduce in a test table today and was unable to. The `text` field copied and pasted my text string of 500 characters. I'll see if I run across this again, and if so, try to narrow down the conditions or cause and provide a reproducible case.

**Comment by uslss** [comment]
Feel free to reopen an issue if it reproduces again
