### ISSUE TITLE
Export CSV to CSV Aggregate column empty

### ISSUE THREAD

**Issue by markr-metra-autosound-com** [dbeaver/dbeaver#10830]
**Is your feature request related to a problem? Please describe.**
When exporting a query result from a CSV to a CSV, the aggregate (SUM) column is empty

**Describe the solution you'd like**
The result of SUM to appear in the YTD column of the CSV

**Describe alternatives you've considered**
none

**Additional context**
This problem has been duplicated in version 7.3.0.202012062025 on Xubuntu Linux, version 7.3.1.202012201616 on Mac and Windows.

Running a report of YTD totals by customer. Using the CSV plugin to read a report from our bank, I am exporting the summarized results via the CSV plugin with this query:

```sql
SELECT
	"Customer Number" ,
	name,
	sum(amount) AS YTD
FROM
	Customer_YTD_Sales
WHERE (
	fail_name IS NULL 
	OR ltrim(rtrim(fail_name)) = ''
)
GROUP BY 
	"Customer Number",
	name
;
```

![Screenshot_2020-12-29_10-41-43](https://user-images.githubusercontent.com/10209842/103296014-2dc0ea00-49c3-11eb-8673-68c1e5c1f368.png)

![Screenshot_2020-12-29_10-43-39](https://user-images.githubusercontent.com/10209842/103296025-31ed0780-49c3-11eb-9016-496e964dd017.png)

**Comment by markr-metra-autosound-com** [comment]
I worked around this issue by loading the CSV to my local MySQL instance, export works correctly from MySQL -> CSV

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by ShadelessFox** [comment]
Hello @markr-metra-autosound-com,

It's a bug of CSV driver.

Workaround: set <kbd>Binaries</kbd> to <kbd>Inline</kbd> and their encoding to <kbd>Binary</kbd>:

![image](https://user-images.githubusercontent.com/35821147/137129985-5c504b80-ee2e-4028-be0d-b9cc9b824c44.png)

**Comment by ShadelessFox** [comment]
Now we inline binaries by default.

**Comment by Matvey16** [comment]
Verified
