### ISSUE TITLE
Color column and table names separately

### ISSUE THREAD

**Issue by rjake** [dbeaver/dbeaver#10831]
**Is your feature request related to a problem? Please describe.**
When I code review, I spend more energy than I want looking for the period separating columns from tables. Our standard is all lowercase and full table names. It makes the code easier to share but also makes the lines longer to read and more cumbersome to navigate.

**Describe the solution you'd like**
I'd like to specify the color of the table separately from the column name. By greying out the table name, I can treat it as context and not give it as much visual prominence.

![image](https://user-images.githubusercontent.com/14003618/103303235-72548180-49d3-11eb-82bf-950d20756015.png)

**Describe alternatives you've considered**
I use external text editors when code reviewing as I can control the colors of these two pieces. I have used both VS Code & Atom (shown above).

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea.

**Comment by E1izabeth** [comment]
Similar issues #4099 #20628 #5714

**Comment by E1izabeth** [comment]
It's done in https://github.com/dbeaver/dbeaver/pull/21788 and will be available in the next release (DBeaver 23.2.5)
The feature is turned off by default, you can enable it here 

![image](https://github.com/dbeaver/dbeaver/assets/28875055/dca4fef3-3bd6-484b-a11b-21cf916d1423)
