### ISSUE TITLE
Unable to open using 7.3.1 version

### ISSUE THREAD

**Issue by pokoli** [dbeaver/dbeaver#10842]
#### System information: 
- Operating system (distribution) and version: arch linux
- DBeaver version: 7.3.1
- Additional extensions:Nnone

#### Connection specification:
- Database name and version: Unrelated
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

The system crashes when opening the application. it only talks about opening a log with the details. 

#### Steps to reproduce, if exist:

Just try to open the application.

Using 7.3.0 version had no issue for me. 

#### Include any warning/errors/backtraces from the logs

Here is the content of the generated log file:  [1609392550114.log](https://github.com/dbeaver/dbeaver/files/5756539/1609392550114.log)

Here is my java version:
```
> java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```

Let me now if any additional details are requried

**Comment by p91paul** [comment]
see https://github.com/dbeaver/dbeaver/issues/10837
Archlinux is declaring the dependency wrong, dbeaver now requires jdk 11. It is a bug in the archlinux package.

**Comment by pokoli** [comment]
Thanks for the info i'm closing this now.  Sorry for the extra noise but I did not find the existing bug report
