### ISSUE TITLE
Notification wrong color theme

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#10841]
#### System information: 
- Operating system = MacOS Big Sur
- DBeaver version = 7.3.1

#### Connection specification:
- Database name and version = Postgres 13.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When the notification box appears, it doesn't follow my dark theme, it appears in light theme and even then is not readable.

<img width="1428" alt="Screenshot 2020-12-30 at 18 17 17" src="https://user-images.githubusercontent.com/49366783/103370358-e45cc180-4acc-11eb-9957-fafa64f6babe.png">

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. It is actual for Windows too.

**Comment by AdrianoBortoloto** [comment]
Is there a way to change the notification theme temporarily till the issue have been solved?

**Comment by kseniiaguzeeva** [comment]
Unfortunatelly we should wait for fix.

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
