### ISSUE TITLE
Triggers for Teradata

### ISSUE THREAD

**Issue by yan-hic** [dbeaver/dbeaver#10840]
Logging as feature request but could be a bug or a how-to question.

Triggers are listed for other dbms in the navigation pane but can't find (in 7.3.1) how to enable for Teradata.

**Comment by kseniiaguzeeva** [comment]
We are foing to implement it in next releases.

**Comment by LonwoLonwo** [comment]
Implemented in 21.0.1
Will be available [here](https://dbeaver.io/) at 2021-03-22

**Comment by uslss** [comment]
verified
