### ISSUE TITLE
PostgreSQL datatypes comments missing?

### ISSUE THREAD

**Issue by lodgmar** [dbeaver/dbeaver#10844]
Datatypes have a Description field,  but it seems to be read-only. If you set comment for a data type (COMMENT ON TYPE IS), nothing is showed in DBeaver.

That's the only thing I've found missing in DBeaver after 2 years of happy work with it! Congratulations!!!

**Comment by LonwoLonwo** [comment]
@lodgmar Thanks for the bug report!

**Comment by LonwoLonwo** [comment]
yeah, I caught the case when the comment does not appear. If you add it through SQL Editor, and then open the data type page and update it with the button in the lower right corner. 
But if you update the entire "Data types" tab or the entire schema tab, the comment appears. 
Is that so? Or are the type comments not read at all?

**Comment by lodgmar** [comment]
Yes, you're right. Now I see it in DBeaver.
That's good news, because it means it'll be easily fixable ;-)

**Comment by LonwoLonwo** [comment]
Ability to add comment to data type via UI added here https://github.com/dbeaver/dbeaver/issues/7079
Did this solve your problem?

**Comment by lodgmar** [comment]
Everything's working great! Great job!!!
