### ISSUE TITLE
dbeaver community version is installed without Icon.

### ISSUE THREAD

**Issue by landv** [dbeaver/dbeaver#10857]
English：
system version :Linux version 5.4.70-amd64-desktop (deepin@deepin-PC) (gcc version 8.3.0 (Uos 8.3.0.3-3+rebuild)) #1 SMP Wed Oct 14 15:24:23 CST 2020.
dbeaver community version is installed without Icon.
Modify  `/usr/share/applications/dbeaver.desktop`  File, remove WM_ Class
After modification
```text
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=DBeaver Community
GenericName=UniversaL Database Manager
Comment=Universal Database Manager and SQL Client.
Path=/usr/share/dbeaver/
Exec=/usr/share/dbeaver/dbeaver
Icon=/usr/share/dbeaver/dbeaver.png
Categories=IDE;Development
StartupWMClass=DBeaver
StartupNotify=true
Keywords=Database;SQL;IDE;JDBC;ODBC;MySQL;PostgreSQL;Oracle;DB2;MariaDB
MimeType=application/sql
```
中文：
操作系统版本 :Linux version 5.4.70-amd64-desktop (deepin@deepin-PC) (gcc version 8.3.0 (Uos 8.3.0.3-3+rebuild)) #1 SMP Wed Oct 14 15:24:23 CST 2020.
[deepin][linux][DBeaver]DBeaver社区版安装好没有图标
修改 /usr/share/applications/dbeaver.desktop 文件，去掉 WM_CLASS 一行
修改以后
```text
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=DBeaver Community
GenericName=UniversaL Database Manager
Comment=Universal Database Manager and SQL Client.
Path=/usr/share/dbeaver/
Exec=/usr/share/dbeaver/dbeaver
Icon=/usr/share/dbeaver/dbeaver.png
Categories=IDE;Development
StartupWMClass=DBeaver
StartupNotify=true
Keywords=Database;SQL;IDE;JDBC;ODBC;MySQL;PostgreSQL;Oracle;DB2;MariaDB
MimeType=application/sql
```

**Comment by kseniiaguzeeva** [comment]
Please try to uninstall and then install DBeaver again.

**Comment by landv** [comment]
> Please try to uninstall and then install DBeaver again.

You can try installing Ubuntu or deepin system.
uninstall and then install DBeaver again.
dbeaver community version is installed without Icon.
Need Modify /usr/share/applications/dbeaver.desktop File, remove WM_ Class,There will be icons.
This is a translator translation, not accurate enough, please understand。

**Comment by flambchap** [comment]
Hello @landv. I can't reproduce the issue against the current version (7.3.5). I want to ask you a few questions.

* Are you experiencing this issue with the current version at the moment?
* If so, did you install DBeaver with the deb package or using snap?
* Could you please show me the contents of the dbeaver.desktop file before the changes that seem to cure your problem?

Thank you.

**Comment by landv** [comment]
Hello @akilovich ,
You can try installing  deepin system.
This system is deepin (https://www.deepin.org/en/).
install DBeaver .
dbeaver community version is installed without Icon.
Need Modify /usr/share/applications/dbeaver.desktop File, remove WM_ Class,There will be icons.
This is a translator translation, not accurate enough, please understand。

**Comment by flambchap** [comment]
Okay, now I get it. It actually should be `WMCLASS` as defined in the [Startup notification protocol](https://specifications.freedesktop.org/startup-notification-spec/startup-notification-0.1.txt).

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
