### ISSUE TITLE
Filter on fully-loaded resultset issues a new query

### ISSUE THREAD

**Issue by yan-hic** [dbeaver/dbeaver#10854]
This must have been reported earlier - sorry if it was. 

In Data editor (7.3.1), when a resultset is fully-loaded in memory, any filter will run a new query on the RDBMS.
This is far from optimal since raw data is in the client's memory already, the filter could just be applied on that snapshot instead.

This is especially painful if the initial query took long to return already. Any filter would take as much time to run.

Also, once fixed, a single-key shortcut to filter by the selected cell value would be super useful !

**Comment by kseniiaguzeeva** [comment]
Thank you forthe report.

**Comment by kseniiaguzeeva** [comment]
A little investigation was needed. FIltering executes on server side. That's why all object's data is used. This is the expected behaviour
