### ISSUE TITLE
DBeaver Crashed when view large BLOB value

### ISSUE THREAD

**Issue by qiqingli** [dbeaver/dbeaver#10859]
#### System information: 
- Operating system (distribution) and version: MacOS Big Sur
- DBeaver version: 7.3.2
- Java version: OpenJDK Runtime Environment 18.9 (build 11+28)
- Additional extensions

#### Connection specification:
- Database name and version: Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
- Driver name: 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When viewing the value of a large BLOB field, it crashes and exits

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/20805098/103511391-f0b49600-4ea1-11eb-9933-1112f0f9ce7a.png)
![image](https://user-images.githubusercontent.com/20805098/103511458-0d50ce00-4ea2-11eb-8de4-d40483cd04e9.png)

**Comment by uslss** [comment]
Hi @qiqingli ,
could you provide ddl of the table and some data sample that can help us to reproduce an issue?
Thanks in advance

**Comment by qiqingli** [comment]
I have found the cause of the problem. If you open the metadata tab at the same time, DBeaver will crash. It is normal to close the metadata tab.
hope this can help locate the problem.

![image](https://user-images.githubusercontent.com/20805098/104676567-98438b00-5722-11eb-9f7f-95f612263630.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the additional details. Is it possible to give BLOB data example to reproduce?

**Comment by qiqingli** [comment]
@kseniiaguzeeva Some content involving personal privacy has been replaced with 'XXX' 

[sample.txt](https://github.com/dbeaver/dbeaver/files/6295640/sample.txt)

**Comment by qiqingli** [comment]
@kseniiaguzeeva This problem also appeared in DBeaver 21.0.2, hope it can be solved completely.

**Comment by kseniiaguzeeva** [comment]
Thank you for the additional details. We will try to fix it, but I cannot reproduce it in Mac Big Sur DBeaver 21.0.2.
Could you please also send log files https://github.com/dbeaver/dbeaver/wiki/Log-files?

_DBeaver command:
See table HR."blob" with BLOB value_

**Comment by qiqingli** [comment]
I think the problem is related to workspace configuration file, regenerate a new workspace, the problem disappeared.

**Comment by serge-rider** [comment]
@qiqingli Thanks for the update
