### ISSUE TITLE
Auto completion does not work if table name has space

### ISSUE THREAD

**Issue by NehalDamania** [dbeaver/dbeaver#10858]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.3.1

#### Connection specification:
- Database name and version: MariaDB
- Driver name - mariadb, mariadb-java-client
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
If the table name contains space, the auto completion does not work.
for example: if the table name is `file list` then
when we type the query 
```
select * from `file list` fl where fl.
-- here the autocompletion does not work after the dot
```
If the table name does not have any spaces, then autocompletion works perfectly.

#### Steps to reproduce, if exist:
Create any table in mariadb or mysql with space 
Try any query on the table and the autocompletion or suggestion of columns for that table won't work. Please check the gif below.
Autocompletion works perfectly for table `tabRole`, but doesn't work for table `tabHas Role`

![dbeaver_autocompletion_not_working](https://user-images.githubusercontent.com/1287731/103498318-56852b80-4e6a-11eb-9d97-16bcf17bc642.gif)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by kseniiaguzeeva** [comment]
Verified (the issue still exists for column name: will be added to #11977)

**Comment by tkorach** [comment]
Issue still exists for a table name with spaces: 

![image](https://user-images.githubusercontent.com/38960214/113763626-e21b8c00-96e7-11eb-8f61-20200c486da5.png)

![image](https://user-images.githubusercontent.com/38960214/113763670-f2336b80-96e7-11eb-8e6f-b930ab77d994.png)

**Comment by serge-rider** [comment]
The fix will be added in version 21.0.3 (see milestone info).
Or you can download the Early Access version.

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by tkorach** [comment]
Indeed the code completion works on 21.0.3 (build from source)

**Comment by NehalDamania** [comment]
The issue has reoccurred in latest build of dbeaver. It used to work fine
