### ISSUE TITLE
MySQL Event cannot be deleted via UI

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10853]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.3.2 EA
#### Connection specification:
- Database name and version MySQL
#### Steps to reproduce, if exist:
1. Select an event in DB Navigator or in Object Editor
2. Try to delete it

Expected: the event is delted
Actual result:
- error "no database selected" appears
- the event remains in the database

**Comment by LonwoLonwo** [comment]
Fixed in 21.0.0

**Comment by uslss** [comment]
verified
