### ISSUE TITLE
wiki/Develop-in-Eclipse step 13 (Switch to Hierarchical projects presentations)

### ISSUE THREAD

**Issue by kai-morich** [dbeaver/dbeaver#10861]
took me quit some time to figure out where to click. Please highlight where to click, like here

![dev-setup-step-13](https://user-images.githubusercontent.com/25850372/103536836-839a0400-4e93-11eb-8376-ffd08108fbe4.png)

**Comment by serge-rider** [comment]
Thanks for noticing that

**Comment by flambchap** [comment]
Done.

**Comment by kai-morich** [comment]
:+1:
