### ISSUE TITLE
AWS SSO support for IAM authentication (IAM profiles)

### ISSUE THREAD

**Issue by mitchellrj** [dbeaver/dbeaver#10862]
**Describe the solution you'd like**
#3270 introduced AWS IAM authentication for supported PostgreSQL and MySQL instances. Many organizations use AWS SSO to provide federated user access to AWS including for console and API use. The keys provided by the authentication system are time-sensitive and vary per AWS account, where an organization has many separate AWS accounts. The goal of this feature is to avoid users having to copy and paste new access key each time they want to connect the database.

This could be a rich, native interface, using [the Java SDK](https://docs.aws.amazon.com/en_us/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sso/AWSSSOClient.html), or it could be more minimal, calling out to command line tools or a browser to return credentials to the DBeaver application.

This would be an Enterprise-only feature, since AWS IAM authentication is also Enterprise-only.

**Describe alternatives you've considered**
* Manually pasting time-sensitive access keys and secret keys each time.
* Building a custom script to launch DBeaver which does the SSO authentication dance using CLI tools and uses command-line flags to update DBeaver connections in place.

**Additional context**
* [General documentation on AWS SSO](https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html)
* [Documentation for using AWS SSO with the CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html)

**Comment by serge-rider** [comment]
AWS IAM authenticatio is already supported by DBeaver Enterprise (https://dbeaver.com).

There are no plans to add it in the Community Edition as it is an enterprise feature.

**Comment by mitchellrj** [comment]
@serge-rider please re-read the request. This is an enhancement of that existing enterprise feature to add AWS SSO and I do not propose adding it to the community edition.

**Comment by serge-rider** [comment]
I see.
Well generally DBeaver EE supports IAM CLI authorization:
![image](https://user-images.githubusercontent.com/6398845/104181883-9460f180-5420-11eb-9f38-f2753732364c.png)

If you enable option "Use Default credentials" then DBeaver will load credentials from file `$USER_HOME/.aws/credentials` (according to https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html).
This works for simple IAM login thru CLI. But we don't support AWS profiles yet.

I've changed the subject. We'll try to implement it in version 8.0.

**Comment by struesda** [comment]
+1 to this request - we would benefit from it as well.   

@mitchellrj - in the meantime - have you found any good examples of scripts to do the CLI SSO LOGIN/GET TOKEN dance?  I am about to write my own and would love to avoid re-inventing the wheel.

**Comment by mitchellrj** [comment]
@uslss does changing this to closed mean this is now released, implemented but not released, won't implement, or some other reason?

**Comment by mitchellrj** [comment]
@uslss @serge-rider we have looked at this feature in the early access version of Enterprise Edition (build date 2021-02-19) and it does not allow a user to enter a session token. Temporary credentials such as those issued by AWS SSO or STS require three pieces of information to authenticate:
* Access key ID
* Secret access key
* Session token

Would you like some clearer test cases or user stories?

**Comment by uslss** [comment]
@mitchellrj thanks for the answer.
Could you provide how you configure DBeaver?
For now, we support token that is saved with aws cli only

**Comment by mitchellrj** [comment]
SSO credentials are time-limited, like STS credentials are. This authentication flow is supported in the AWS CLI v2 only, and the credentials are stored differently. Once you have these credentials to authenticate with AWS, getting a token for database access is the same process.

If you don't have access to AWS SSO, you can see the user experience in [this YouTube video](https://www.youtube.com/watch?v=Ga8n2P8Eepc).

## Option 1: implement the full authentication flow in DBeaver
This flow is based on OAuth 2 and OIDC standards and could be like other SSO login support, e.g. Snowflake. This is the most user-friendly option.

1. [Register client](https://docs.aws.amazon.com/en_us/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ssooidc/AWSSSOOIDCClient.html#registerClient-com.amazonaws.services.ssooidc.model.RegisterClientRequest-). Returns client ID, client secret, and an expiration time.
2. [Start device authorization](https://docs.aws.amazon.com/en_us/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ssooidc/AWSSSOOIDCClient.html#startDeviceAuthorization-com.amazonaws.services.ssooidc.model.StartDeviceAuthorizationRequest-). Returns a device code, authorization code, and a verification URL where the user can verify the authorization code in the browser.
3. User confirms authorization in the browser after logging in with their SSO credentials
4. [Create a token](https://docs.aws.amazon.com/en_us/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ssooidc/AWSSSOOIDCClient.html#createToken-com.amazonaws.services.ssooidc.model.CreateTokenRequest-). Returns values for [session credentials](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/BasicSessionCredentials.html) (access key ID, secret access key, and session token) for the user to access AWS services.

## Option 2: load credentials that have already been stored by the AWS CLI
Remember these credentials are time-limited, so may already be expired and you'll have to tell the user to go back to the CLI to log in again. This is probably the least user-friendly.

There is no Java SDK from this, so you'd have to reverse engineer [the source from the AWS CLI](https://github.com/boto/botocore/blob/v2/botocore/utils.py#L2319) to retrieve the access key ID, secret access key, and session token from the cache file.

## Option 3: allow users to enter an optional session token
Extend the interface to allow entering a session token as well as an access key ID and secret access key. This is the easiest to implement. [Users can fetch these details from the SSO portal after logging in](https://aws.amazon.com/blogs/security/aws-single-sign-on-now-enables-command-line-interface-access-for-aws-accounts-using-corporate-credentials/).

**Comment by mitchellrj** [comment]
[The AWS Toolkit for Jetbrains](https://github.com/aws/aws-toolkit-jetbrains) also [added support for this](https://github.com/aws/aws-toolkit-jetbrains/issues/1238) in version 1.18.

**Comment by serge-rider** [comment]
@mitchellrj 
7.3+ EA version IAM authentication already supports options 2 and 3.
![image](https://user-images.githubusercontent.com/6398845/108993643-eba6e280-76ab-11eb-9b0c-06365e0bb8b2.png)

Setting Credentials to `System default` will load CLI credentials file from `~/.aws/credentials`. It will also user session token.

Example of creds file:
```
[default]
aws_access_key_id = AKIF5ERX7FHQJD7QV7OZ
aws_secret_access_key = jfUIXt4mkeAsRhZiciAy7exrfhgU7QUgbnIoHBdH
aws_session_token = zzzz123123345rerwgfwegr
```

If it doesn't work in your case - please write more details: what exactly error do you see. Some logs may be also very helpful (https://dbeaver.com/docs/wiki/Log-files).

**Comment by uslss** [comment]
AWS SSO support was added in the scope of 21.1.0
