### ISSUE TITLE
UI is not refreshed at first

### ISSUE THREAD

**Issue by ffbh123456** [dbeaver/dbeaver#10864]
DBeaver version 7.3.0.202011291229
macos Big Sur 11.0.1

I am editing a mysql table. I added a field to this table. When I saved it, no characters were displayed in SQL preview. Then I switched to another software, and then switched back. At this time, SQL preview is displayed. There is a SQL statement to update the table. I guess it is a UI refresh problem. The UI did not refresh at the beginning. When I switch the software, the statement can be displayed after the UI refresh

![image](https://user-images.githubusercontent.com/20750357/103544887-b7008100-4edb-11eb-9a3b-50af879ed68b.png)

![image](https://user-images.githubusercontent.com/20750357/103545014-ed3e0080-4edb-11eb-92d2-b6f3100b2a69.png)

**Comment by flambchap** [comment]
Fixed in 7.3.1.
