### ISSUE TITLE
The result as spreadsheet is displaying different type

### ISSUE THREAD

**Issue by jhauradou** [dbeaver/dbeaver#10869]
#### System information: 
- Operating system : Windows 10 Pro 64
- DBeaver version: 7.3.2.202101032114
- Additional extensions : none

#### Connection specification:
- Database name and version: SQL Server 12
- Driver name:  SQL Server

#### Describe the problem you're observing:
When I run a simple query where result column is an int, for example *SELECT 28890 AS VALUE*. The result as spreadsheet show me a decimal number 28,890. But when I hit the result column I can see the correct number 28890 on result cell value view.

#### Steps to reproduce,

SELECT 28890 AS VALUE

#### Result

![issue_db](https://user-images.githubusercontent.com/23747095/103575012-56efe780-4ea7-11eb-811c-65d068d8332e.png)

**Comment by LonwoLonwo** [comment]
Hello @jhauradou 

You see in result not decimal, but a numerical grouping.
Grouping is used to make large numbers easier to read.

You can change the representation of numbers in the preferences. Just disabled "Use grouping" option.
![1345](https://user-images.githubusercontent.com/45152336/103671090-7fe9a880-4f8b-11eb-8faf-a234fd5835ea.png)

**Comment by jhauradou** [comment]
Hello @LonwoLonwo 

Thanks for help me, I am taking the first steps with dbeaver.  I am sorry about it.
