### ISSUE TITLE
The Office plugin disabled after upgrade

### ISSUE THREAD

**Issue by JiaOkay** [dbeaver/dbeaver#10871]
#### System information: 
- Windows10 Professional 20H2 build 19042.685
- DBeaver 7.3.2
- Additional extensions

#### Connection specification:
- All DataBases
- All Drivers
- Do you use tunnels or proxies (SSH, SOCKS, etc) ?  No 

#### Describe the problem you're observing:
- I had installed the office support plugin at version 7.3.0, but when I upgrade to 7.3.1, it's lost, Then I install it again.
- today I upgrade to 7.3.2,the plugin lost again, so I install it again.
- Please fix it, Thank You so much!
#### Picture :
![image](https://user-images.githubusercontent.com/38833358/103601046-ca473700-4f43-11eb-80ca-e1aa3cde1190.png)

**Comment by kseniiaguzeeva** [comment]
You should install extensions every time after upgrade. It is the expected behaviour.

**Comment by JiaOkay** [comment]
Ohh, thanks
