### ISSUE TITLE
Enhanced search function

### ISSUE THREAD

**Issue by mdks2010** [dbeaver/dbeaver#10879]
![search](https://user-images.githubusercontent.com/53963129/103656796-03af8f00-4fa4-11eb-807f-86c02134529a.png)

Expect search to increase support for comment columns

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea

**Comment by flambchap** [comment]
Implemented.

**Comment by kseniiaguzeeva** [comment]
Verified with nuances:
_ % * ? ^ + ( )  cannot be found via this search field.
