### ISSUE TITLE
DBA tools

### ISSUE THREAD

**Issue by Ferrox12** [dbeaver/dbeaver#10875]
Hello everyone,
this is a question not a bug report.
In DBeaver are there any DBA Tools as in SQLDeveloper?

**Comment by LonwoLonwo** [comment]
Hello @Ferrox12 
We have some tools/tasks in Database/Tools.

![2021-01-05_14h22_51](https://user-images.githubusercontent.com/45152336/103640754-a7c41680-4f61-11eb-9357-14327a0560c7.png)

![2021-01-05_14h22_40](https://user-images.githubusercontent.com/45152336/103640770-abf03400-4f61-11eb-9e9d-7f9cedd07d0a.png)

Or you can select tools for specific objects, for example, tables, triggers, materialized views, by right-clicking on the object in the tree.

![2021-01-05_14h27_35](https://user-images.githubusercontent.com/45152336/103641209-70a23500-4f62-11eb-8ca2-a6965187057c.png)

Or are you interested in specific tools?

**Comment by Ferrox12** [comment]
I am interested in specific tools such as view the previous backup of the database, status of database, performance of the database...

**Comment by p91paul** [comment]
There is a session browser in the administration folder of database navigator, and there should be the dashboard functionality although I don't remember if it's available for Oracle and how advanced it is. For those tasks, I fear sql developer is probably better, dbeaver excels more at data analysis and multi-database support.

**Comment by Ferrox12** [comment]
Thank You very much for your reply!!!
