### ISSUE TITLE
PostgreSQL:- Column Level Collation - Is not captured

### ISSUE THREAD

**Issue by DanielAdeniji** [dbeaver/dbeaver#10870]
#### System information: 
- Operating system (distribution) and version:- MS Windows 10
- DBeaver version Version 7.2.3.202010191702
- Additional extensions

#### Connection specification:
- Database name and version:- PostgreSQL 13.1
- Driver name:- PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
- Database Engine Version:- PostgreSQL 13.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5), 64-bit

#### Describe the problem you're observing:
When connected to a PostgreSQL Database instance, dbeaver does not show the table's column collation

#### Steps to reproduce, if exist:

1) Create a collation
2) Create a table
2a) One of the table's columns has a collation assigned
2b) Reviewed the same table in dbeaver does not show the table's collation in the "view columns" window
2c) The column's collation is also not shown when we script out the table

**Comment by DanielAdeniji** [comment]
Blogged about the issue here

1. PostgreSQL – Column – Collation
https://learningintheopen.org/2021/01/04/postgresql-column-collation/

Workshop towards issue recreation

1. DanielAdeniji/collation.ci.sql
https://gist.github.com/DanielAdeniji/55d93ea574560d89013e12aa4a481361

**Comment by kseniiaguzeeva** [comment]
Please reconnect to the database, The changes should become visible.

**Comment by DanielAdeniji** [comment]
Confirmed that change is indeed visible, once we reconnected to the database.

Thanks so much for such a quick and helpful reply.

**Comment by kseniiaguzeeva** [comment]
You are welcome!
