### ISSUE TITLE
Access Denied opening SQLite in /opt/....

### ISSUE THREAD

**Issue by mrspirytus** [dbeaver/dbeaver#10882]
#### System information: 
- Ubuntu Mate 20.04 x64
- 7.3.2
- SQLite

#### Connection specification:
- SQlite 3.31.1
- SQlite
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **No**

#### Describe the problem you're observing:
I just did fresh snap install or DBeaver. Next I am trying to open existing sqlite db located in /opt/databases/sqlite/db.db3
I select SQLite from DBeaver wizard, next I navigate to /opt and I get "permissions denied"
Everything including /opt is under my user and group id (recursive)
I can see that dbeaver is running under my user id as well. I can browse and open  /opt/databases/sqlite/db.db3 just fine with DB Browser for SQLite.
Here is /opt permissions

```
drwxr-xr-x  11 mrs mrs       4096 Dec 22 15:46 opt
```

My user ID
``` $ id
uid=1000(mrs) gid=1000(mrs) ... 
```

#### Steps to reproduce, if exist:
- Install DBrowser from Snap Store
- Open sqlite db in  /opt/databases/sqlite/db.db3

![ksnip_20210105-161654](https://user-images.githubusercontent.com/60390416/103706112-ea8dea80-4f71-11eb-9830-60361a34118d.png)

**Comment by mrspirytus** [comment]
Also you are not supporting softlinks. I did try to work around this issue but trying to open ~/project/databases/db.db3

``` ln -s /opt/databases/sqlite/  ~/project/databases```

When I try to open  ~/project/ using Open Dialog Box I see "databases" as a file not as a folder

**Comment by sergey-selivanov** [comment]
The same issue with opening a file in my own home subdirectory, I am trying to open H2 database file under /home/svs/.CookBook . Feel free to ask for any additional info.
DBeaver Version 7.3.2.202101032114 snap, Ubuntu 20.10

```
svs@zeppelin:~$ ps axu|grep dbeaver
svs         9380  0.2  0.0 189352 21868 ?        S    03:23   0:00 /snap/dbeaver-ce/97/usr/share/dbeaver/dbeaver
svs         9480 15.4  1.5 6833840 371624 ?      Sl   03:23   0:47 /snap/dbeaver-ce/97/usr/share/dbeaver/jre/bin/java -XX:+IgnoreUnrecognizedVMOptions -Xms64m -Xmx1024m -jar /snap/dbeaver-ce/97/usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar -os linux -ws gtk -arch x86_64 -showsplash -launcher /snap/dbeaver-ce/97/usr/share/dbeaver/dbeaver -name Dbeaver --launcher.library /snap/dbeaver-ce/97/usr/share/dbeaver//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.0.v20200915-1442/eclipse_11201.so -startup /snap/dbeaver-ce/97/usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar --launcher.overrideVmargs -exitdata 25 -vm /snap/dbeaver-ce/97/usr/share/dbeaver/jre/bin/java -vmargs -XX:+IgnoreUnrecognizedVMOptions -Xms64m -Xmx1024m -jar /snap/dbeaver-ce/97/usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar
svs         9741  0.0  0.0  11860   936 pts/3    S+   03:28   0:00 grep --color=auto dbeaver
svs@zeppelin:~$ ls -la |grep .CookBook
drwxrwxr-x  3 svs svs     4096 янв 15 05:48 .CookBook
drwxr-xr-x  3 svs svs     4096 янв 13 14:59 .CookBook3-devel-tmp
drwx------  3 svs svs     4096 апр  3  2020 .org.sergeys.cookbook.ui.CookBook
svs@zeppelin:~$ pwd
/home/svs
svs@zeppelin:~$ 

```
![Screenshot from 2021-01-16 03-37-44](https://user-images.githubusercontent.com/10028825/104793884-0df43900-57ad-11eb-946f-264bac83a99a.png)

**Comment by Matvey16** [comment]
It should have been fixed in the latest version of snap package where we changed the confinement.
Please reopen the issue if it is still actual for you
