### ISSUE TITLE
I'd like to be able to build an ERD diagram that will show relations between views

### ISSUE THREAD

**Issue by PAPutzback** [dbeaver/dbeaver#10881]
FYI, this is a Snowflake database. The problem is, all of our data is in JSON and it is loaded into a variant column named JSON_CONTENT, We then have a view for each table pulls out the columns from the variant data. 

I'd like to be able to create the relationship connectors between views so I can create a diagram as if the views were tables

The only alternative I have considered was Archimate and Visio. However, I'd prefer to keep the diagrams in the DBeaver toolset.

Here is a screenshot showing how one column in the table is extracted in the view. So the views are what in want to show related in the diagram
![image](https://user-images.githubusercontent.com/11459426/103701139-7e13eb00-4f73-11eb-80ee-8166ee054a58.png)

**Comment by kseniiaguzeeva** [comment]
Please try to use virtual keys for this. You can create virtual primary key and foreign key in Virtual tab of view properties or directly in ERD (press Connection in the ERD toolbar and create keys by clicking on views).
![Screenshot 2021-01-06 at 08 12 09](https://user-images.githubusercontent.com/51405061/103731863-3c2c8880-4ff7-11eb-8068-275ef9397932.png)

The created connections are saved in DBeaver only.

**Comment by PAPutzback** [comment]
My window is a bit different. I have a Data tab between Properties and ER Diagram. I also can't find the Palette menu, Are these differences between the "Free" and "Pro" versions?

**Comment by kseniiaguzeeva** [comment]
No, I opened the diagram for the schema (double click a schema name in DB Navigator and it will be opened in Object Editor with tabs Properties and ERD ), you - for the table.
You can also create custom diagrams. Please find more info in wiki https://github.com/dbeaver/dbeaver/wiki/ER-Diagrams and https://github.com/dbeaver/dbeaver/wiki/Custom-Diagrams
Feel free to ask to reopen the ticket if you have additional questions about diagrams.
