### ISSUE TITLE
How to create mysql foreign key

### ISSUE THREAD

**Issue by ffbh123456** [dbeaver/dbeaver#10885]
- Operating system (distribution) and version : maxosx
- DBeaver version : 7.3.2.202101032114

I am editing a mysql table and I want to add a foreign key to this table, but I find that the confirm button is grayed out, what's the matter?

![image](https://user-images.githubusercontent.com/20750357/103730182-2cc03600-501d-11eb-8aeb-25f9c90eb6ad.png)

**Comment by kseniiaguzeeva** [comment]
Please select a column for foreign key (left column on your photo). The button will become active after it.

**Comment by ffbh123456** [comment]
Great, I know how to use it

**Comment by Roshang2003** [comment]
> Great, I know how to use it

Can you please tell me how you resolved it, I am also facing the same issue.
Please reply as soon as possible.

**Comment by TechArtistG** [comment]
> > Great, I know how to use it
> 
> Can you please tell me how you resolved it, I am also facing the same issue. Please reply as soon as possible.

Maybe not a bug but definitely sub-optimal UI.  Once you've selected a table in "Referenced table" you then need to click in the "Column" column in the "Columns" table 😑
![image](https://github.com/dbeaver/dbeaver/assets/1031627/47e7f72f-7265-4dd0-9160-6ee188df7113)
