### ISSUE TITLE
Importing a csv file is very slow

### ISSUE THREAD

**Issue by binoculars88** [dbeaver/dbeaver#10897]
#### System information: 
- Windows 10
- DBeaver 7.3.2

#### Connection specification:
- MySQL 8.0.20
- MySQL 8.0.17
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I have a CSV file which consists of 18k rows, 5 columns. When I import this file using phpmyadmin, it takes around 8 seconds. If I import it via the DBeaver GUI, it takes almost 5 minutes. I tried changing the performance options (Open new connections, Use transactions) but none of that seems to improve the speed. Even disabling batches results in the same speed, around 100 rows per second. This setting, the 100 rows per second, is probably the reason why it's slow, but as far as I could see, you cannot change that (only the batch size, which is default set to 10k)

#### Steps to reproduce, if exist:
Import an CSV file with +10k rows. You'll notice it will do it per 100 rows.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

_MySQL table Kseniia.18k_rows can be used to reproduce._

**Comment by deepaksenthilkumar** [comment]
Hi Team, Importing into Redshift is also very slow. Are you planning to use the batch insert instead of single inserts to speed this up (will it speed it up for Redshift too)? 

Thanks,
Deepak

**Comment by serge-rider** [comment]
Fixed.

The problem was caused by poor batch processing performance in MySQL driver. Parameter `rewriteBatchedStatements` set to true solves the problem.
We will set it to true by default in the next version.

**Comment by Matvey16** [comment]
Verified

**Comment by deepaksenthilkumar** [comment]
Looks like this fix is only for the originally reported issue with MySQL. Should I open a new issue for Redshift slowness?

**Comment by Matvey16** [comment]
@deepaksenthilkumar  Yes, It can either be a similar or a different issue, so it needs to be in another issue

**Comment by zhaokunyao** [comment]
![image](https://user-images.githubusercontent.com/17042914/171598368-7620ba4a-0ef7-42d9-8862-fd684e21c5e1.png)


get hanged  while importing a 1M lines csv file.


![image](https://user-images.githubusercontent.com/17042914/171598565-730e1106-c913-427e-829b-bbcfd377b190.png)

file content:

![image](https://user-images.githubusercontent.com/17042914/171598623-8547b971-0a40-405f-9008-33bd4b09c123.png)

**Comment by Watin7** [comment]
Ponder this https://stackdev.space/questions/the-performance-of-mysqls-bulk-update-is-not-meeting-expectations-due-to-slow response
