### ISSUE TITLE
Cant start dbeaver after update to 7.3.1

### ISSUE THREAD

**Issue by volker-raschek** [dbeaver/dbeaver#10890]
#### System information: 
- Operating system (distribution): Arch Linux
- DBeaver version: 7.3.1-2
- Additional extensions: None

#### Describe the problem you're observing:

Can not start dbeaver after upgrade from 7.2.5-1 to 7.3.1-2. Get the following error message:

![error message](https://user-images.githubusercontent.com/18311012/103785953-1aa1c000-503c-11eb-8767-38dcd19e0f4b.png)

#### Include any warning/errors/backtraces from the logs

[1609946807363.log](https://github.com/dbeaver/dbeaver/files/5776591/1609946807363.log)

**Comment by serge-rider** [comment]
Since version 7.3.1 DBeaver requires Java 11. In fact all DBeaver packages (on dbeaver.io) include Java runtime already.
What type of installer did you use?

**Comment by volker-raschek** [comment]
Hi @serge-rider, 
I have installed java-14-openjdk and java-8-openjdk (default).

```bash
$ archlinux-java status
Available Java environments:
  java-14-openjdk
  java-8-openjdk (default)
```

I installed additionally `java-11-openjdk` and set it as default.

```bash
$ sudo archlinux-java set java-11-openjdk
$ Available Java environments:
  java-11-openjdk (default)
  java-14-openjdk
  java-8-openjdk
```
Now dbeaver starts again successfully. Maybe it make sense to change the error message if the wrong java version is defined. 

How can I define explicit the path to the the java 11 binaries for dbeaver? The setting, that java 11 is now the default can occur some problems with old legacy programs.   

> What type of installer did you use?

I used the official package from the Arch Linux distribution:
- https://archlinux.org/packages/community/x86_64/dbeaver/
- [PKGBUILD](https://github.com/archlinux/svntogit-community/tree/packages/dbeaver/trunk)

**Comment by allen-ziegenfus** [comment]
@volker-raschek 

I am able to do this on arch: 

```
dbeaver -vm /usr/lib/jvm/java-11-openjdk/bin
```

So as to not have to change my regular java settings

**Comment by bkqtnte10** [comment]
When starting, I get an error "Version ... of the JVM is not suitable ...". 
With the command by @allen-ziegenfus it worked. 

Why is this needed?

I have a fresh install of dbeaver (Version 21.2.0.202109041934). (I'm on Manjaro a 21.1.4)

**Comment by allen-ziegenfus** [comment]
@bkqtnte10  most likely you have a different default JVM on your system that is too old

**Comment by bkqtnte10** [comment]
Thank you for the clarification. 
The part I want to understand is: when JVM 11 or higher is needed (and already is available), why doesn't dbeaver pass this request by itself?

**Comment by allen-ziegenfus** [comment]
idk, probably because it doesn't want to be in the business of figuring out your java config
