### ISSUE TITLE
Add links from text editor to Google search

### ISSUE THREAD

**Issue by lacanoid** [dbeaver/dbeaver#1089]
This is a simple usability improvement suggestion;

In the context menu in the text editor, please add "Search Web with Google..." item, which would run google search with the selected text (in a default web browser). Xcode has this. It is quite handy for quickly finding documentation online. Now one has to copy/paste stuff around to do this, which is rather clunkier (1 click vs. about 4).

Perhaps this also applies well to the resultset, log & output, not only the text editor.

**Comment by GiantCrocodile** [comment]
I like this feature request but I suggest that we can configure which URL is queried per GET-request. I would set some SQL wiki and not Google.

**Comment by serge-rider** [comment]
I like this

**Comment by lacanoid** [comment]
One wouldn't want to overcomplicate it.

Perhaps an editable list of links, customizable somewhere in preferences. Or something similiar to macos services. Maybe there is a suitable eclipse plugin already.

**Comment by serge-rider** [comment]
As far as I know there is no such plugin available. There is a couple pretty old ones which are integrated with JDT but not with general text editor.

**Comment by lacanoid** [comment]
@GiantCrocodile Did you have a particular wiki/website in mind?

**Comment by GiantCrocodile** [comment]
I could imagine something like this @lacanoid: https://wiki.postgresql.org/wiki/Special:Search?search=Concat&go=Go. Problem is when you use non English versions of DBMS and you try to search for German error message in Google. That never works so I prefer that I can search for English keywords easily without having to look at Google's results but have one site like the wiki of my DBMS where I find it for sure and even with correct syntax etc for my specific DBMS.

**Comment by serge-rider** [comment]
Implemented in https://github.com/dbeaver/dbeaver/pull/9100

**Comment by uslss** [comment]
verified
