### ISSUE TITLE
View as "Epoch time"

### ISSUE THREAD

**Issue by CandicePatry** [dbeaver/dbeaver#10891]
Hello, 

I'm on Dbeaver 7.3.2 and when I want to change the view of a cell (right-click > View/format > Set {column} format), I can't choose Epoch Time et no other view option translate the data of my cell into date. 
My friend has Dbeaver 5.0.0 and she has "Epoch Time" option working very well. 
Please help !
Thank you !

**Comment by serge-rider** [comment]
Why can't you?
It is still there and works as before:
![image](https://user-images.githubusercontent.com/6398845/103799856-b7745580-505c-11eb-9643-6cc19cbfcd5c.png)

Please write more detaisl about the problem.

**Comment by CandicePatry** [comment]
I don't have it...

![image](https://user-images.githubusercontent.com/77069591/103803332-b5a49500-5050-11eb-96df-2b0c785c19b3.png)

**Comment by serge-rider** [comment]
Epoch time transformation is available only for numeric columns. What data type your column has?

**Comment by CandicePatry** [comment]
numeric

**Comment by CandicePatry** [comment]
Exemple : I took : 1585004400000

**Comment by serge-rider** [comment]
Could you write exact data type name? It is in the column header tooltip. Or in the Metadata panel. Or on the Properties/Columns tab.
Also what database do you use?

**Comment by CandicePatry** [comment]
I'm not sure that what you asked me
but I found that
![image](https://user-images.githubusercontent.com/77069591/103804432-665f6400-5052-11eb-8ab5-6c24c3c69d10.png)

**Comment by CandicePatry** [comment]
the database is sqlite

**Comment by CandicePatry** [comment]
I found what you met. 
Indeed my column is noted ABC instead of 123 as I wished it were.
How can I change that ?

**Comment by serge-rider** [comment]
Column data type:
![image](https://user-images.githubusercontent.com/6398845/103804575-69168500-5063-11eb-96c6-c85a70ef0356.png)

![image](https://user-images.githubusercontent.com/6398845/103804661-88adad80-5063-11eb-86e6-7fae08dbfb51.png)

**Comment by CandicePatry** [comment]
On my side, the colonne is "DATE" or "DATETIME" and date is not considered numeric so I can't change to epoch time....
Unfortunatly, I don't know how I can't change that... I'l ask a friend tomorrow...
Thanks for the explanation.

**Comment by serge-rider** [comment]
> Indeed my column is noted ABC instead of 123 as I wished it were.
> How can I change that ?

Unfortunatelly that's not easy: https://stackoverflow.com/questions/21199398/sqlite-alter-a-tables-column-type
Most likely you will need to recreate your table.
