### ISSUE TITLE
Is it possible to keep dbeaver JRE agnostic or is there a workaround for those stuck on version 1.8?

### ISSUE THREAD

**Issue by pybokeh** [dbeaver/dbeaver#10898]
Hello,
Unfortunately, at my company, I have to keep working with DB2 mainframe z/OS.  I have to use a specific JRE (Java 1.8) or I can't query my tables containing timestamps due to a well known legacy EDIC/CP1027 encoding issue.  Prior to recent versions of dbeaver, I could just drop my JRE folder into dbeaver's root folder and then I'm good to go.  Now however, that is not possible.  Are there some additional modifications I can do to continue using my existing JRE with recent versions of dbeaver or am I stuck with version 7.3.0?  If there is no way to get my local JRE version to work with current versions of dbeaver, that is fine, but just wanted to make sure there isn't some other workaround.  I appreciate all the work that has been put into dbeaver!

**Comment by p91paul** [comment]
I guess you could install an old enough eclipse version and Dbeaver 7.3.1 and newer as an eclipse plugin!

**Comment by pybokeh** [comment]
@p91paul Thanks, that's good to know.

**Comment by kseniiaguzeeva** [comment]
@pybokeh Please ask to reopen the ticket if the advice above hasn't helped to you.
