### ISSUE TITLE
Support json fields in virtual column definition

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#10900]
For example for JSONB data types.
Probably we need this for XML columns too.

**Comment by LonwoLonwo** [comment]
```json
{
  "glossary": {
    "title": "example glossary",
    "GlossDiv": {
      "title": "Story",
      "GlossList": {
        "GlossEntry": {
          "ID": "SGML",
          "Abbrev": "ISO 8879:1986",
          "SortAs": "SGML",
          "Acronym": "SGML",
          "GlossDef": {
            "para": "A meta-markup language, used to create markup languages such as DocBook.",
            "GlossSeeAlso": [
              "GML",
              "XML"
            ]
          },
          "GlossSee": "markup",
          "GlossTerm": "Standard Generalized Markup Language"
        }
      }
    }
  }
}
```

Expression for column (example) : content.json(column1)['glossary']['GlossDiv']['title']

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Employees>
    <Employee id="1">
        <age>29</age>
        <name>Pankaj</name>
        <gender>Male</gender>
        <role>Java Developer</role>
    </Employee>
    <Employee id="2">
        <age>35</age>
        <name>Lisa</name>
        <gender>Female</gender>
        <role>CEO</role>
    </Employee>
    <Employee id="3">
        <age>40</age>
        <name>Tom</name>
        <gender>Male</gender>
        <role>Manager</role>
    </Employee>
    <Employee id="4">
        <age>25</age>
        <name>Meghan</name>
        <gender>Female</gender>
        <role>Manager</role>
    </Employee>
</Employees>
```


Expression for column (example) : content.xml(xml_column, "nodeset", "/Employees/Employee[gender='Female']/name/text()")

![2021-10-25 19_23_58-DBeaver Ultimate 21 2 3 - json_virtual](https://user-images.githubusercontent.com/45152336/139086949-767983f8-8f5d-4f9a-90a3-033beeb1896c.png)

![2021-10-25 20_46_46-Add virtual column](https://user-images.githubusercontent.com/45152336/139086954-dfe3ecd4-1f12-4126-8acd-3756b4431ecb.png)

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/wiki/virtual-column-expressions

1. Support link on the page "Add virtual column" fixed
2. Preview in Property editor "Virtual" tab for virtual columns now can show parsing error message. (Worked for Data viewer)
3. One new namespace added - `content` with three methods: content.json(columnName), content.xml(columnName, "expression"(quotation is important)), content.xml(columnName, "returnType", "expression")

you can read about json parameters here https://commons.apache.org/proper/commons-jexl/reference/syntax.html
about xml: https://en.wikipedia.org/wiki/XPath
https://stackoverflow.com/questions/2811001/how-to-read-xml-using-xpath-in-java
https://howtodoinjava.com/java/xml/java-xpath-tutorial-example/
https://javadevblog.com/primer-raboty-s-xpath-v-java-poisk-v-xml-i-vy-borka-danny-h.html

xml expression can return types: `string, number, boolean, node, nodeset` - all these types can be used (!in quotes) for return data type clarification. `content.xml(columnName, "expression")` returns string by default

example: content.xml(column1, "nodeset", "/Employees/Employee[gender='Female']/name/text()")

**Comment by uslss** [comment]
verified
