### ISSUE TITLE
Option to disable TableCache loading while executing scripts

### ISSUE THREAD

**Issue by butlnor** [dbeaver/dbeaver#10908]
DBeaver Version 7.2.5.202011152110
Driver: MySQL (although it applies to any)

We have a database with ten thousands of tables. If I want to expand a list of the tables in the navigator, I can expect, that it will load for quite some time.

But if I am editing the SQL script or even if I paste it from somewhere else, and then move the cursor to some identifier, it starts loading this TableCache in the background and preventing me from working for about 10 minutes. This is UNEXCEPTABLE! I understand, that this cache helps with autocomplete, but I want to get rid of it in some cases. I can live without it.

There should be an option to disable loading this TableCache for certain connections.

**Comment by kseniiaguzeeva** [comment]
We already have such option. Please try to disable Auto-insert proposal (go to Window>Preferences>Editors>SQL Editor>Code completion)
![Screenshot 2021-01-09 at 08 52 19](https://user-images.githubusercontent.com/51405061/104084517-cf182d80-5258-11eb-882f-97edca5fefd2.png)

**Comment by butlnor** [comment]
I disabled the "auto insert proposal", but still, the TableCache is being loaded... I wrote the script manually, not copy-pasted. After changing this setting, I also restarted dBeaver, but it's all the same.

![dbeaver](https://user-images.githubusercontent.com/11555256/104165065-26ed9a80-53f9-11eb-9e1b-5116a4c6eddb.jpg)

**Comment by kseniiaguzeeva** [comment]
Please disable following options:
Enable auto-activation and activate on typing (SQL Editor>Code completion)
![Screenshot 2021-01-18 at 17 39 46](https://user-images.githubusercontent.com/51405061/104929080-7e20db80-59b4-11eb-96c3-9c8e9bafd119.png)

and 
Read table metadata and read table preferences
![Screenshot 2021-01-18 at 17 41 12](https://user-images.githubusercontent.com/51405061/104929094-8547e980-59b4-11eb-9497-a2c214b9a46f.png)

It should help now.

**Comment by Developer1510** [comment]
I tried disabling "Enable auto-activation", "activate on typing" and "Read table metadata" (while "Read table references" is not even enabled, when the "Read table metadata" is disabled). But when executing the manually written query I get "Search proposals..." and "Load TableCache". 

Unfortunatelly this doesn't help in my case.

**Comment by Developer1510** [comment]
Also: while this "Load TableCache" is in process, dBeaver cannot be properly exited. I can close the window, but the process is still running, and has to be manually killed with task manager or process explorer.

**Comment by kseniiaguzeeva** [comment]
It is a bug (e.g. Search proposals... bar shouldn't be displayed), but we have to figure out a reason.
Thank you for the report.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
