### ISSUE TITLE
Key Binding to Jump to First or Last Column

### ISSUE THREAD

**Issue by brileyd** [dbeaver/dbeaver#10902]
I would like to use something like Command+&#8592; and Command+&#8594; to jump to the first column and last column while in the results grid.

Thanks!

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by kseniiaguzeeva** [comment]
We already have such option and you can see and customize it in Preferences>User Interface>Keys
![Screenshot 2021-01-18 at 17 47 54](https://user-images.githubusercontent.com/51405061/104930077-baa10700-59b5-11eb-9bfd-bfad360520a9.png)

**Comment by brileyd** [comment]
Can this be reopened?  I was aware of the ability to jump to first and last row, but I would like the ability to jump to the first and last column.

Thanks!

**Comment by kseniiaguzeeva** [comment]
Please use HOME and END buttons to it.
