### ISSUE TITLE
Create DBeaver distribtuion without bundled Java

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#10904]
It may be helpful for users whi have some specific Java configuration (certificates, security policies, etc).
We need Linux distribtuion first.

**Comment by serge-rider** [comment]
- *-nojdk-* package added for Linux.
- In Windows installer new checkbox "Include Java" was added

**Comment by uslss** [comment]
verified

**Comment by howdev** [comment]
can't use deb file for nojdk? nojdk only available as tar.gz?
Java bundle is not necessary even for deb installer since Linux already has Java installed.

**Comment by 2019-05-10** [comment]
Uhm, can we get that as packages (deb, rpm) as well?
IMO expereinced Linux users are much more likely to use managed packages than just a TAR or ZIP archive.
After all, if anything those managed packages are predestined for this sort of thing, being able to manage dependencies -- a simple dependency on `default-jre`should work for both deb and rpm.
