### ISSUE TITLE
An question about create mysql with enum field

### ISSUE THREAD

**Issue by ffbh123456** [dbeaver/dbeaver#10913]
I am creating a MySQL table that contains an enum type. I want to give some initial values to the enum field, like size ENUM('x-small', 'small', 'medium', 'large in the following MySQL document ', 'x-large'), where can I set the initial value of the enum

![image](https://user-images.githubusercontent.com/20750357/104114974-47f4b380-5345-11eb-864d-a9fc6a5734a9.png)

![image](https://user-images.githubusercontent.com/20750357/104114957-209de680-5345-11eb-818f-91f89bb8962b.png)

![image](https://user-images.githubusercontent.com/20750357/104114945-006e2780-5345-11eb-98e9-29782f3117c5.png)

**Comment by kseniiaguzeeva** [comment]
UI doesn't have such option now. You can do it via SQL Editor.

**Comment by kseniiaguzeeva** [comment]
A little investigation was needed. You can create ENUM column type via UI. Type its values in brackets after the type name when create the column:
![Screenshot 2021-01-12 at 13 02 57](https://user-images.githubusercontent.com/51405061/104299824-ba48cd80-54d6-11eb-8f74-ec2b36c848ab.png)

**Comment by ffbh123456** [comment]
@kseniiaguzeeva 
Good idea, Thank you
