### ISSUE TITLE
text highlight on sql editor not same as mouse hover

### ISSUE THREAD

**Issue by ajikur2901** [dbeaver/dbeaver#10914]
#### System information: 
- linux mint 18
- DBeaver 7.3.2

#### Describe the problem you're observing:
when i use mouse pointer to highlight the text, the highlighted text did not same as my hover. it highlight from the topest view ( not line 1 but the topest line showing in that sql editor ) to start mouse pointer highlight

#### Steps to reproduce, if exist:
make a query and hover the text

thanks and sorry if my english is bad

https://user-images.githubusercontent.com/48973903/104141979-ff440580-53eb-11eb-839c-72986f97a9a3.mp4

**Comment by serge-rider** [comment]
This is Eclipse-specific issue.
We will try to upgrade Eclipse version to 2021-03.

**Comment by serge-rider** [comment]
Eclipse updated in #11994
