### ISSUE TITLE
Right to left languages issue in SQL editor

### ISSUE THREAD

**Issue by mlhtpete** [dbeaver/dbeaver#10911]
#### System information: 
- Operating system (distribution) and version: win 10 home edition build 1909 (18363.1256)
- DBeaver version: 7.3.2.202101032114
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Using microsofe chinese pinyin input method under chinese input mode, 
in the sqleditor tab, after selecting a line of characters:
![1 select aline of characters](https://user-images.githubusercontent.com/77197276/104092568-c575e080-52bf-11eb-911f-895ee647c32d.png)
then input number then found the number input is insert before the selected line of characters,but not replace the selected line characters.
![2 after input number 5](https://user-images.githubusercontent.com/77197276/104092575-cf97df00-52bf-11eb-8e14-2aa93c49d35c.png)

more info: if change  to  eng input mode, no problem.
and i try other txt editor, not finding this problem.

**Comment by kseniiaguzeeva** [comment]
Looks like an eclipse problem.

**Comment by uslss** [comment]
seems to be fixed in 21.2.0
