### ISSUE TITLE
Tables and views from another project could be added to ERD and saved, but after ERD reopening it is not shown

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#10918]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.3.3 EA

#### Describe the problem you're observing:
Tables and views from another project could be added to ERD and saved, but after ERD reopening they are not shown
#### Steps to reproduce, if exist:
1. Create ERD using File - New - ERD in Project 1
2. Add tables and/or views from Connection from Project 2 to created ERD and save it - No warnings that objects from another project will not be saved are shown
3. Close ERD and then open it - No previously added objects are visible.

**Comment by tati-kru** [comment]
We must restrict adding entities from other projects.

**Comment by ShadelessFox** [comment]
Implemented. Now you can't add objects for project that differs from diagram's project

**Comment by DariaMarkaryan** [comment]
Verified
