### ISSUE TITLE
seeing data in postgresql bytea column

### ISSUE THREAD

**Issue by mlybarger** [dbeaver/dbeaver#10917]
in the past, i could right click on a bytea column (containing xml) and select view or edit to see the data.  

now i have to copy and paste the data into another app for viewing.

**Comment by kseniiaguzeeva** [comment]
Please try to use Value panel for editing https://github.com/dbeaver/dbeaver/wiki/Panels#value-viewer

**Comment by uslss** [comment]
there is no update on the issue for a long time.
if it is still actual for you - feel free to reopen it with an additional info
