### ISSUE TITLE
Website: typo in MacOS Brew install command

### ISSUE THREAD

**Issue by jvspl** [dbeaver/dbeaver#10919]
On the website, the double dash "--" in the MacOS Brew install command is shown as one character, a large dash. This means users get an error message when they copy the command into their terminal. Instead of a large dash "–", there should be two small dashes "--".

Error message from Brew in terminal: Error: No available formula or cask with the name "–cask".

Currently shown on website:
 (brew install –cask dbeaver-community)

Should be:
 (brew install --cask dbeaver-community)

**Comment by serge-rider** [comment]
Ugh, wordpress converted double-dash into some unicode crap.
Fixed.
Thanks for noticing that.

**Comment by kseniiaguzeeva** [comment]
verified
