### ISSUE TITLE
version 7.3.1 PPA not available for ubuntu 20.10?

### ISSUE THREAD

**Issue by schmitzkr** [dbeaver/dbeaver#10916]
#### System information: 
- Ubuntu 20.10
- 7.3.0

#### Describe the problem you're observing:
I can't seem to update past 7.3.0 via apt even though the ppa archive shows version 7.3.1 exists.
https://launchpad.net/~serge-rider/+archive/ubuntu/dbeaver-ce
Also strange is that the 'version 7.3.2 available' prompt appears each time I start dbeaver, but it doesn't appear published on launchpad (only 7.3.1 is there for groovy https://launchpad.net/~serge-rider/+archive/ubuntu/dbeaver-ce?field.series_filter=groovy).

I am not sure if this is an issue/error with publishing or maybe launchpad is just slow?  seems 2 weeks is very slow though.  

#### Steps to reproduce, if exist:
sudo add-apt-repository ppa:serge-rider/dbeaver-ce
sudo apt-get update
All packages are up to date.

**Comment by dchekanov** [comment]
Same here. I had to switch to the Debian repo to get updates past 7.3.0.

**Comment by serge-rider** [comment]
Ubuntu PPA wasn't updated after the last two releases. We are in the download repositories transition period.
Planned to be fixed before 7.3.4 release.

**Comment by serge-rider** [comment]
7.3.4 was published as PPA

**Comment by schmitzkr** [comment]
Thanks very much :)
