### ISSUE TITLE
(DBeaver 7.3.2) MySQL geometry is not displayed on the map

### ISSUE THREAD

**Issue by vicreal** [dbeaver/dbeaver#10929]
- Operating system: Windows 10 (last update) / x64
- DBeaver version: 7.3.2 (last)
- Database name and version: MySQL 5.7.30 (last 5 version) / x64
- Do you use tunnels or proxies: no

After update DBeaver from 7.2.1 to **7.3.2** MySQL geometries are no longer displayed in OpenStreetMap in the window on the right (on the "value" tab). Instead of the geometry, a binary fragment displayed (for example, "[B@60e28d20").
PostgreSQL/PostGIS geometries are displayed correctly.

Example (MySQL):
`SELECT POINT(1,2);`
Instead of the geometry displayed "[B@60e28d20".

**Comment by agmckee** [comment]
I am also experiencing this.

* Operating system: Ubuntu Linux 20.04
* DBeaver version: 7.3.2.202101032114 installed as a snap
* Database name and version: MariaDB 10.2
* Do you use tunnels or proxies: no

**Comment by agmckee** [comment]
Just for extra information, I have installed dbeaver-ce 7.3.0 using the Deb package and it works correctly with MariaDB geometry fields so the issue appears to have been introduced after 7.3.0. Hope this helps.

**Comment by serge-rider** [comment]
It is a side effect of #10353 fix

**Comment by andriyor** [comment]
I have a similar problem with postgis geometry
dbeaver unexpectedly closes when i click on cell

**Comment by serge-rider** [comment]
@andriyor it is a different issue. See #9368

**Comment by vicreal** [comment]
Check version **7.3.3**.202101130717 ([https://dbeaver.io/files/ea/](https://dbeaver.io/files/ea/)) - bug not fixet yet.

**Comment by kseniiaguzeeva** [comment]
Verified.
@vicreal the fix is not available on EA yet. I'll let you know as soon as EA is updated
