### ISSUE TITLE
Explain Execution Plan return wrong data on Type column

### ISSUE THREAD

**Issue by noisydump** [dbeaver/dbeaver#10922]
#### System information: 
- MacOS 10.15
- DBeaver Enterprise Version 7.3.0.202012061950

#### Connection specification:
- MySQL 5.6
- Driver name mysql-connector-java-5.1.48.jar
- Using tunnels SSH

#### Describe the problem you're observing:
Running "Explain Execution Plan" on a query, the row values ​​of the _Type_ column appear wrong and equal 
to the _Select Type_ column.
Instead, running the explain query give correct results

### Command "Explain Execution Plan" result
![Screenshot 2021-01-11 at 12 54 14](https://user-images.githubusercontent.com/15326177/104181002-58bd2c00-540e-11eb-917f-0994cf169498.png)

### EXPLAIN QUERY result
![Screenshot 2021-01-11 at 13 08 28](https://user-images.githubusercontent.com/15326177/104181016-5ce94980-540e-11eb-9074-e88c28982f21.png)

**Comment by kseniiaguzeeva** [comment]
Please give me a query example

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.

**Comment by ddtuan99** [comment]
Hi @kseniiaguzeeva and @uslss, I can confirm this issue happend on Windows 10, DBeaver Community Edition Version 21.2.2.202110030714 too.

Appearently, the `TYPE` column is just a copy of `Select Type` column in the execution plain tab for MySQL query.

It's not a problem if I can just run `EXPLAIN` query directly while having read-only connection.

Steps to reproduce are: create a MySQL table, write a `SELECT` query with `WHERE` clause on one of the table indexed column then Ctrl Shift E (to Explain Execution Plan).
