### ISSUE TITLE
Views on Teradata are not shown

### ISSUE THREAD

**Issue by s-heins-cw** [dbeaver/dbeaver#10930]
#### System information: 
- Windows 10 Pro 20H2
- DBeaver 7.3.2
- Additional extensions

#### Connection specification:
- Database name and version: Teradata 15.00.03.01
- Driver name: com.teradata.jdbc.TeraDriver 16.20.00.10
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
In version 7.3.2 Views on Teradata are not shown any longer. They are neither shown in the navigator nor in the properties when I open the schema. Worked fine in 7.3.0 and also works fine on Oracle databases.

#### Include any warning/errors/backtraces from the logs
no error messages in the log files

**Comment by s-heins-cw** [comment]
It seems that the views are listed under "Tables".

**Comment by yan-hic** [comment]
Confirming issue still exists in 7.3.3. Latest working is 7.3.1

Also seeing the views under tables only "works" for data browsing, not to view/update the definition. 
The table equivalent, DDL, raises error: `SQL Error [3853] [HY000]: [Teradata Database] [TeraJDBC 16.20.00.06] [Error 3853] [SQLState HY000] 'MyView' is not a table.`

**Comment by EWingate7** [comment]
Also seeing this problem with 7.3.3. Had to revert back to 7.3.1

**Comment by sdavic** [comment]
still have same issue with version 7.3.4

**Comment by yan-hic** [comment]
Same on 7.3.5...

@serge-rider I am not sure if this is really being looked at. Should be easy to fix as it worked before 7.3.2. 
If identified, is there a planned release for the fix ? I am missing out a bunch of nice features since stuck with 7.3.1.

Thanks !!

**Comment by s-heins-cw** [comment]
Is there anyone looking into it? The bug is still existing in 21.0!

**Comment by LonwoLonwo** [comment]
For some reason, views were in the list of tables. We fixed it - now views are in the views folder.

Fixed in 21.0.1
Will be available [here](https://dbeaver.io/) at 2021-03-22

And soon here: https://dbeaver.io/files/ea/

**Comment by uslss** [comment]
verified
