### ISSUE TITLE
Emojis not supported for PostgreSQL

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#10946]
Hi all

It's not that important but I just found out that if you use emojis to create a table like this:

`create table 😉 (💩 text);`
`insert into 😉 values ('puh');`
`select count(*) from 😉  where 💩 = 'puh';`

You are not able to drop the table using the schema Browser in DBeaver. Although the table 😉  is shown in the table list, choosing 'delete' from the context menu just generates a 

`drop table public.`
instead of
`drop table public.😉`

As stated above, it's not important at all, but, well, it's a bug!
And, no, I don't use emojis as database object names on a regular base! 😉

**Comment by serge-rider** [comment]
Generally this ticket is not about emojis but about full Unicode support.

**Comment by ShadelessFox** [comment]
This fix affects how DDL names are generated. But it will allow identifiers such as '🙂' to present in DDL instead of empty name.

**Comment by uslss** [comment]
column named with emojis aren't visible at column tab
![image](https://user-images.githubusercontent.com/31996417/105091612-26b46580-5ab1-11eb-915c-a6036232ea65.png)

**Comment by uslss** [comment]
verified
