### ISSUE TITLE
Can I make Pin Column functionality for next sessions ?

### ISSUE THREAD

**Issue by sergeynilov** [dbeaver/dbeaver#10941]
Hello,
DBeaver 7.2.1 under kubuntu 18 has usefull functionality : setting Pin Column when having 
selected column in datagrid.

But looks like this functionality works only during 1 current session.

Can I select this functionality for next sessions too ?

Thanks!

**Comment by uslss** [comment]
Hi @sergeynilov ,
if I understand you correctly, you could using Save filter settings button
![image](https://user-images.githubusercontent.com/31996417/104445509-3d872380-55aa-11eb-9970-7d8ae453b561.png)
