### ISSUE TITLE
NPE appears after closing SQL Editor with ResultSet

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10949]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.2.202101122029

#### Steps to reproduce, if exist:
1. Open SQL Editor - **SQL Editor field is grey and the text is not visible**
2. Press Output tab - SQL Editor field becomes white and the text appears
3. Execute a Select query
4. Close SQL Editor - **NPE appears**

https://user-images.githubusercontent.com/51405061/104414126-c2f5de00-5580-11eb-9421-34c786a3c2b1.mp4
[.log](https://github.com/dbeaver/dbeaver/files/5806746/default.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
