### ISSUE TITLE
ODBC DRIVER   ISSUE : Unexpected driver error occurred while connecting to the database

### ISSUE THREAD

**Issue by pooher3** [dbeaver/dbeaver#10952]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version                                                    Latest 
- Java version                                                           Latest
- Additional extensions                                            None

#### Connection specification:
- Database name and version                                  Any database
- Driver name                                                           ODBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)?NO

#### Describe the problem you're observing:

While trying to connect to ODBC data sources we get the error **Unexpected driver error occurred while connecting to the database**

#### Steps to reproduce, if exist:
1) Create ODBC DSN thru windows OBDC manager for any database.
2) Open dbeaver and choose ODBC and provide DSN Name,username and password
3) Test connect and u get the error **Unexpected driver error occurred while connecting to the database**

**Comment by uslss** [comment]
Hi @pooher3 ,
sorry for the late response.
Unfortunately, cannot reproduce an issue. What ODBC platform do you use: x64 or x32?

**Comment by uslss** [comment]
There is no update on an issue for a long time.
If it is still actual for you - feel free to reopen an issue.
