### ISSUE TITLE
SQL Folding: save folding state on editor close

### ISSUE THREAD

**Issue by knwpsk** [dbeaver/dbeaver#10959]
Please enhance the "cold folding" functions.

- Allow user to fold any section of an SQL query (e.g. a CASE...END clause, or a SELECT (many fields) clause, or a Join, etc.
- Allow user to fold/expand within a fold (aka a "tree with branches" or "nodes and sub-nodes")
- Bonus: Keep the collapsed/expanded state of each fold section "sticky" -- even when the query or the app is closed, if possible! (I get it that this is tricky.)

Currently, the Folding feature only lets me collapse an entire SQL statement.  Limited usefulness.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by flambchap** [comment]
I'm going to subdivide this FR into two separate issues. The first two points will be covered in https://github.com/dbeaver/dbeaver/issues/11830. Here we will concentrate on sticky folding.

**Comment by flambchap** [comment]
Implemented.

**Comment by uslss** [comment]
Folding state doesn't save for script like ddl for pagila.public (full ddl with comment and grants)
![2021-03-31_12h21_50](https://user-images.githubusercontent.com/31996417/113121984-dfb6bf00-921b-11eb-805e-d8c0ac8f7ade.gif)

**Comment by flambchap** [comment]
The current solution uses Eclipse's persistent properties which can not be greater than 2KB in size. With too many folded annotations, we exceed this threshold which causes this behavior. We discussed that with Serge and decided that we'll address this issue in one of our future releases.

**Comment by uslss** [comment]
verified
