### ISSUE TITLE
Auto-complete offers objects from the current schema only

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10955]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.3 EA

#### Steps to reproduce, if exist:
1. Open SQL Editor for MySQL sakila
2. Type `select * from a`

**Actual result**: the list for auto-complete appears with objects from the current schema only
**Expected**:  the objects are offered from the whole database if they are suitable for auto-complete in the current statement.

_Note_: enabled **Use global search** option doesn't solve the issue

**Comment by kseniiaguzeeva** [comment]
The similar issue https://github.com/dbeaver/dbeaver/issues/10832

**Comment by LonwoLonwo** [comment]
Can't reproduce for 
-MySQL
![2021-09-30 13_43_56-](https://user-images.githubusercontent.com/45152336/135441176-8c8a2910-b6bd-4dce-b4eb-0003e91d8987.png)

-PostgreSQL
![2021-09-30 13_46_15-DBeaver 21 2 2 - _postgres_ Script-33](https://user-images.githubusercontent.com/45152336/135441626-d4f3bd7a-2e4a-4bb0-8258-053854377eea.png)

**Comment by LonwoLonwo** [comment]
SQL Server doesn't work

**Comment by LonwoLonwo** [comment]
Mssql global search fixed.

![2021-09-30 19_18_08-](https://user-images.githubusercontent.com/45152336/135522551-93899edc-ff6c-4000-84c8-ddc3f93b21a7.png)

**Comment by Matvey16** [comment]
Verified

**Comment by mmarsilli** [comment]
We have similar problem as Kseniiaguzeeva with **DBeaver Lite** (Version 22.3.0) connecting to a **Netezza DB with schema disabled**.

Writing:
`select * from art`
there is no auto-complete.

Instead by writing:
`select * from admin.art`
auto-complete works well.

Curiously, with DBeaver Community it works correctly.

_Note_: Setting "Use Short Object Names (omit schema/catalog)" does not change the behavior of Intellisense.

Having to write the schema name all the time to get autocomplete is very frustrating.
