### ISSUE TITLE
SQL Editor Longitudinal Copy Support

### ISSUE THREAD

**Issue by mingzijian** [dbeaver/dbeaver#10965]
SQL Editor Longitudinal Copy Support

**Comment by mingzijian** [comment]
Alt + MouseLeft to select text.

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea

**Comment by kseniiaguzeeva** [comment]
It turns out this function already exists (If I understand you correctly). Make triple click on a line in SQL Editor to highlight it.

https://user-images.githubusercontent.com/51405061/106032298-5979e180-60e1-11eb-9617-0385e0cf9177.mov

**Comment by uslss** [comment]
There is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it.
