### ISSUE TITLE
mysql:if procedure has recursion dbeaver's task progress bar is not end

### ISSUE THREAD

**Issue by doubcrick** [dbeaver/dbeaver#10967]
#### System information: 
- Operating system (distribution) and version  : win10
- DBeaver version : 7.3.0
- Additional extensions : no

#### Connection specification:
- Database name and version :mysql 5.6.39-83.1
- Driver name : mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Steps to reproduce, if exist:

CREATE DEFINER=`root`@`%` PROCEDURE `xxx`.`insert_resource`(IN newParentId int, IN oldParentId int)
BEGIN
  DECLARE resourceId int DEFAULT 0;
  DECLARE newResourceId int;
  DECLARE done boolean DEFAULT 0;
  DECLARE idCur CURSOR FOR
  SELECT
    id
  FROM xxx.sys_resource_xxx
  WHERE pid = oldParentId
    and del_flag = 0;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;

  SET @@max_sp_recursion_depth = 100;
  OPEN idCur;
  FETCH idCur INTO resourceId;
  WHILE done <> 1 DO
    INSERT INTO xxxx.sys_resource_yyy(provider_id,
    organization_id,
    name_cn,
    name_en,
    resource_url,
    remark,
    menu_icon,
    service_platform_prefix,
    resource_type,
    resource_sort,
    resource_status,
    resource_code,
    resource_menu_type,
    pid,
    pname,
    `level`,
    create_by,
    create_user_name,
    create_at,
    update_by,
    update_user_name,
    update_at,
    delete_flag)
      SELECT
        41,
        NULL,
        b.name,
        b.url,
        b.url,
        NULL,
        NULL,
        NULL,
        '2',
        0,
        0,
        NULL,
        NULL,
        newParentId,
        NULL,
        NULL,
        1612,
        NULL,
        '2021-01-12 09:54:33',
        NULL,
        NULL,
        NULL,
        0
      FROM xxx.sys_resource_xxx b
      WHERE b.id = resourceId;
    SELECT
      LAST_INSERT_ID() INTO newResourceId;

    CALL xxx.insert_resource(newResourceId, resourceId);

    FETCH idCur INTO resourceId;
  END WHILE;

  CLOSE idCur;
END

**Comment by kseniiaguzeeva** [comment]
I cannot run your example (an error appears in SQL syntax). Also I cannot reproduce it on some other examples I created myself.

Could you send some other query to reproduce?

**Comment by doubcrick** [comment]
I write a new case for this.  I'm sorry for found an error in my old procedure. When I repair that error dbeaver is not recurrence of the previous problem .

think you.

I have a suggestion,When I use dbeaver copy table in same database, I want copy structure and data in once operation. navicat is good for this.

**Comment by kseniiaguzeeva** [comment]
You can do it in DBeaver too. Please use export to database (it allows to export tables with data to the same and other databases) https://github.com/dbeaver/dbeaver/wiki/Data-migration
![dbeaver_1XvE6ap3UO](https://user-images.githubusercontent.com/51405061/106443411-80436980-648d-11eb-9b6b-066a6be61029.png)

Ok, wait for a new script example to reproduce the issue with the procedure.

**Comment by doubcrick** [comment]
I do it like you says. I get a new table ,but this table lost annotation. Is my operation wrong?

**Comment by kseniiaguzeeva** [comment]
The feature is more about data transfer than about full migration.
If you want to dump and restore objects, you can use these functions for MySQL and PostgreSQL https://github.com/dbeaver/dbeaver/wiki/Backup-Restore.

Is the issue about progress bar still actual? Can you give an example?
If you have any other question, please create a new ticket here or in Discussions https://github.com/dbeaver/dbeaver/discussions

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it.
