### ISSUE TITLE
When viewing a table, make row of currently-selected cell highlight a specific color

### ISSUE THREAD

**Issue by DeflateAwning** [dbeaver/dbeaver#10960]
**Is your feature request related to a problem? Please describe.**
It is a bit tough to track which row you're looking at when scrolling horizontally and/or vertically. I want to be able to quickly pick out which row I have a cell selected in.

**Describe the solution you'd like**
When I click on a cell (when viewing a table), I want that entire row to highlight a specific color, indicating that is the row selected. When multiple cells and selected, this highlighting should apply to all rows with selected cells.

**Describe alternatives you've considered**
N/A

**Additional context**
Screenshot of feature in HeidiSQL, a competing SQL database product.
![image](https://user-images.githubusercontent.com/11021263/104489602-0eae8480-558d-11eb-813f-806579c6ff2e.png)

**Comment by p91paul** [comment]
did you notice row and column headers of selected cells are highlighted?

**Comment by DeflateAwning** [comment]
I did notice that. I still find it a bit tough when I'm viewing large tables on a large screen though (especially for the right-most columns in the table, which are far away from the highlighted row header).

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion

**Comment by flambchap** [comment]
Added the corresponding option in preferences.

**Comment by kseniiaguzeeva** [comment]
Verified. Please enable it in Window>Preferences>Editors>Data Editor>Appearance>Grid
![dbeaver_v5xlm16kb6](https://user-images.githubusercontent.com/51405061/114686655-ad2cbc00-9d1b-11eb-8aae-4752629683b0.png)

**Comment by jkmajcen** [comment]
I'm on 24.0.1.202403241413 and this functionality no longer works. Was a cool feature.

**Comment by p91paul** [comment]
I suggest you open a new bug report if you are experiencing a regression, comments on closed issues are likely to be overlooked.

**Comment by DeflateAwning** [comment]
@jkmajcen I'm still seeing the highlighted rows. Can you please post a bug report if this is a regression for you?

My version: `Version 24.0.1.202403241413`
OS: Linux Mint
