### ISSUE TITLE
Add row counts to filter pane to see column's value distribution

### ISSUE THREAD

**Issue by DeflateAwning** [dbeaver/dbeaver#10961]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
When you click on the filter button for a specific column (while viewing a table), I want a button in the resulting filter window that gets the row counts for each value in the filter window. This is counting the number of rows with each distinct value in that column. It is useful for seeing the distribution of values in a column. See the mockup below.

**Describe alternatives you've considered**
Without this feature, one has to call the `SELECT DISTINCT colname, COUNT(*) FROM tablename` in a separate query to get this distribution. Having it in the filter dialog would be very helpful.

**Additional context**
Here is an awful mockup of what I'm envisioning:
![image](https://user-images.githubusercontent.com/11021263/104489114-8203c680-558c-11eb-888d-368493503f2a.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by ShadelessFox** [comment]
Implemented for columns with no foreign key.

**Comment by uslss** [comment]
verified
