### ISSUE TITLE
checkboxes in boolean type

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#10969]
Dbeaver 7.3.2
Postgresql 12

what happened to the wonderful checkboxes in value fields like boolean?

![изображение](https://user-images.githubusercontent.com/61137576/104586153-e5721f00-5686-11eb-88eb-4b1a3ee1a353.png)

[ ] and [x]  who could think of such a decision? I think that it is ARRAY in my fields.

absolutely inconvenient ugly decision.

in previous versions there were good, understandable checkboxes!

**Comment by kseniiaguzeeva** [comment]
Now you can customize it. Please open Preferences>Editors.

**Comment by detkliff** [comment]
> 
> 
> Now you can customize it. Please open Preferences>Editors.

Sorry. It is very well!

**Comment by kseniiaguzeeva** [comment]
I'm glad you like the decision :)
