### ISSUE TITLE
PostgreSQL new tables/columns are only in lower case

### ISSUE THREAD

**Issue by pauldaustin** [dbeaver/dbeaver#10979]
#### System information: 
- MAC OS X Big Sur
- 7.3.2 Community
- PostgreSQL driver

#### Connection specification:
- PostgreSQL 13
- PostgreSQL JDBC Driver
- No

#### Describe the problem you're observing:

When using the UI to create a new table or Column in PostgreSQL it replaces any non-lower case characters with lower case.

However if you save it, go into the properties for the table or column you can rename using upper or mixed case.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
@pauldaustin Hello!
It's not a bug - it's a PostgreSQL standard. 
You can find it in [PostgreSQL documentation](https://www.postgresql.org/docs/current/sql-syntax-lexical.html).

> Quoting an identifier also makes it case-sensitive, whereas unquoted names are always folded to lower case. For example, the identifiers FOO, foo, and "foo" are considered the same by PostgreSQL, but "Foo" and "FOO" are different from these three and each other. (The folding of unquoted names to lower case in PostgreSQL is incompatible with the SQL standard, which says that unquoted names should be folded to upper case. Thus, foo should be equivalent to "FOO" not "foo" according to the standard. If you want to write portable applications you are advised to always quote a particular name or never quote it.)

Use quotation marks to save tables in a mixed case or lower case.

**Comment by timbze** [comment]
DBeaver had this setting before: "Use case-sensitive names in DDL statements"

But I can not find it now, did it get removed?

This was the setting that would make DBeaver automatically add double quotes around DDL statement column names when there was an uppercase letter in it.

**Comment by LonwoLonwo** [comment]
Preferences -> Connections -> Metadata
![2021-01-25 19_21_48- metadata - DBeaver Enterprise 7 3 3 - NewTable](https://user-images.githubusercontent.com/45152336/105733449-a07da080-5f42-11eb-9977-a6acca993a27.png)

Seems to work correctly.

![2021-01-25 19_23_02-NewTable - Persist Changes](https://user-images.githubusercontent.com/45152336/105733661-d884e380-5f42-11eb-8016-aa4f25430b13.png)

**Comment by timbze** [comment]
Thank you! Wow can't believe I couldn't find it, looked for a long time, and filter was not helping.

I had this on previous computer and couldn't find on new one... Thanks again

**Comment by LonwoLonwo** [comment]
@timbze To be honest, I just learned about this setting thanks to you. so thanks!

**Comment by Download** [comment]
So if I write a script that includes double-quotes around the column name, does DBeaver actively remove the quotes?? Because what I am seeing after 

```sql
CREATE TABLE my_table (
  "ID" int
)
```

is that the column `ID` has been converted to Lowercase. Because DBeaver seems to consistently do this. if I later write 

```sql
INSERT INTO my_table ("ID") VALUES (1);
```

it actually 'works'... until I try to query from my app (using `"ID"` and it fails saying column `"ID"` does not exist...

Do I have to set this setting in order to prevent that? This was highly unexpected for me and the reason I am here in the issue tracker.

**Comment by LonwoLonwo** [comment]
> if I write a script

> does DBeaver actively remove the quotes?

DBeaver doesn't delete anything in the SQL Editor. 
In this topic, we are discussing UI table creation.
