### ISSUE TITLE
Column sort by value in "Record mode view"

### ISSUE THREAD

**Issue by ewmartinez** [dbeaver/dbeaver#10976]
When is needed to use the record view, and the table has many fields, is difficult analyze it whet there are many null values, in these cases will be usefull to have a sort function by value, in order it can be see only the not null data. (Now it can be sort only by field name, not by value)

Thanks, 
I hope it can be added at some time

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea

**Comment by ewmartinez** [comment]
Could be a check "Hide null values", and conserve the column fields order.. in any case, both solution will be useful

**Comment by ewmartinez** [comment]
Hi,
Is there any hope to have this feature? It's really important for people who work with big data structures.
Thanks

**Comment by E1izabeth** [comment]
In the latest DBeaver version you can hide all columns with NULL values with `Hide columns with no data` command
![image](https://github.com/dbeaver/dbeaver/assets/28875055/3a3e6f3c-a3af-4bec-9765-1f9e48dee14d)


After that you can return all columns back wia Reset button in Filter settings, or check columns visibility back manually there
![image](https://github.com/dbeaver/dbeaver/assets/28875055/5e6bcfe9-1f51-48eb-9e1b-1fd6801c18a1)

**Comment by ewmartinez** [comment]
Thanks.. 
In what versión it will be available? I've tested the 23.0.5 version, I didn't find the options.

**Comment by E1izabeth** [comment]
I tested with 23.0.5

**Comment by ewmartinez** [comment]
Hi I've tested this feature and in the test, it was hidden only two field of four null values.
![2023-06-22-17_48_34](https://github.com/dbeaver/dbeaver/assets/6951562/a7e2cb0d-142c-4ffb-a992-7d4d564362c3)
Here the result
close_on and parent_id had not been hide
![2023-06-22-17_51_20](https://github.com/dbeaver/dbeaver/assets/6951562/21a0b33f-ad10-4ef0-99c5-18e15e04c43f)
