### ISSUE TITLE
incorrect Infinity timestamp and float values display

### ISSUE THREAD

**Issue by vicreal** [dbeaver/dbeaver#10978]
- Operating system (distribution) and version: Windows 10 (last update) / x64
- DBeaver version: **7.3.3**.202101130717
- Database name and version: **PostgreSQL 13**

`SELECT 'Infinity'::timestamp, '-Infinity'::timestamp, 'Infinity'::timestamptz, '-Infinity'::timestamptz;`
```
Show: (292278994-08-17 02:00:00, 292269055-12-03 02:00:00, 292278994-08-17 02:00:00, 292269055-12-03 02:00:00)
Must be: (∞, -∞, ∞, -∞) or (+Infinity, -Infinity, +Infinity, -Infinity)
```

`SELECT 'Infinity'::float4, '-Infinity'::float4, 'Infinity'::float8, '-Infinity'::float8;`
```
Show: (∞, -∞, +Infinity, -Infinity)
Must be: (∞, -∞, ∞, -∞) or (+Infinity, -Infinity, +Infinity, -Infinity)
```

**Comment by kseniiaguzeeva** [comment]
Please enable date/time and numeric formatting (Edit connection>Data Editor>Data Formats) to see the correct result.
![dbeaver_8UIQfI6lrN](https://user-images.githubusercontent.com/51405061/104890903-451b4380-5981-11eb-8785-de87817d9da9.png)

**Comment by vicreal** [comment]
If you disable the formatting of date/time and numerics, we get the correct result:

```
SELECT 'Infinity'::float4, '-Infinity'::float4, 'Infinity'::float8, '-Infinity'::float8;
(+Infinity, -Infinity, +Infinity, -Infinity)

```
```
SELECT 'Infinity'::timestamp, '-Infinity'::timestamp, 'Infinity'::timestamptz, '-Infinity'::timestamptz;
(+Infinity, -Infinity, +Infinity, -Infinity)
```

That is, the **bug** manifests itself only when **formatting is enabled**.

---
I would like infinite values to be displayed correctly also when formatting is enabled.
As far as I understand, with **date/time and numerics formatting** enabled, the **correct result** should be like this:
```
SELECT 'Infinity'::timestamp, '-Infinity'::timestamp, 'Infinity'::timestamptz, '-Infinity'::timestamptz;
(∞, -∞, ∞, -∞)     -- now show: (292278994-08-17 02:00:00, 292269055-12-03 02:00:00, 292278994-08-17 02:00:00, 292269055-12-03 02:00:00)
```
```
SELECT 'Infinity'::float4, '-Infinity'::float4, 'Infinity'::float8, '-Infinity'::float8;
(∞, -∞, ∞, -∞)     -- now show: (∞, -∞, +Infinity, -Infinity)
```

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified

**Comment by kmdbds** [comment]
Was this bugfix ever released? I have the exact same problem in DBeaver 24.0.5.

EDIT: Just realised there is a slight difference: It seem to be fixed for timestamp and timestamptz, but not date.
