### ISSUE TITLE
Windows 7.3.2 comunity edition -- Invalid .project file -- quotes lost in xml

### ISSUE THREAD

**Issue by readytheory** [dbeaver/dbeaver#10975]
Today starting dbeaver, all my database connections were gone

There was a pretty clear diagnostic in the log

    org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 15; The value following "version" in the XML declaration must be a quoted string.

C:\Users\me\AppData\Roaming\DBeaverData\workspace6\General\.project file

had:

    <?xml version=1.0 encoding=UTF-8?>

Adding quotes on attributes fixed the problem.  

I don't remember any abnormal exits, and not aware of anything other than dbeaver that would be looking at that file

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it in the latest release 7.3.3. Could you please try it https://dbeaver.io/?

**Comment by readytheory** [comment]
I can't reproduce it either, and I guess the problem would be in whatever serializer library writes the file, unless some process local to my workplace removed the quotes.  So will close.

**Comment by kseniiaguzeeva** [comment]
Nice to hear!
