### ISSUE TITLE
Since 7.3.1 marketplace not install

### ISSUE THREAD

**Issue by ceinmart** [dbeaver/dbeaver#10987]
Since version 7.3.1 , I try to install the plugin "marketplace client" and fail with the error below .
Tried again with 7.3.2 and still fail.
With version 7.2.5 , the installation works fine.
There is something I can do to workaround?

> Cannot complete the install because of a conflicting dependency.
>   Software being installed: Marketplace Client 1.8.2.v20200309-0038 (org.eclipse.epp.mpc.feature.group 1.8.2.v20200309-0038)
>   Software currently installed: DBeaver 7.3.2.202101032114 (org.jkiss.dbeaver.core.product 7.3.2.202101032114)
>   Only one of the following can be installed at once: 
>     Equinox Provisioning Discovery UI 1.1.400.v20191213-1911 (org.eclipse.equinox.p2.ui.discovery 1.1.400.v20191213-1911)
>     Equinox Provisioning Discovery UI 1.2.0.v20200916-1234 (org.eclipse.equinox.p2.ui.discovery 1.2.0.v20200916-1234)
>   Cannot satisfy dependency:
>     From: Marketplace Client 1.8.2.v20200309-0038 (org.eclipse.epp.mpc.feature.group 1.8.2.v20200309-0038)
>     To: org.eclipse.equinox.p2.iu; org.eclipse.epp.mpc.ui [1.8.2.v20200309-0038,1.8.2.v20200309-0038]
>   Cannot satisfy dependency:
>     From: Marketplace Client 1.8.2.v20200309-0038 (org.eclipse.epp.mpc.ui 1.8.2.v20200309-0038)
>     To: osgi.bundle; org.eclipse.equinox.p2.ui.discovery [1.0.0,1.2.0)
>   Cannot satisfy dependency:
>     From: Equinox p2, Discovery UI support 1.2.800.v20200916-1234 (org.eclipse.equinox.p2.discovery.feature.feature.group 1.2.800.v20200916-1234)
>     To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.p2.ui.discovery [1.2.0.v20200916-1234,1.2.0.v20200916-1234]
>   Cannot satisfy dependency:
>     From: DBeaver Community Edition 7.3.2.202101032114 (org.jkiss.dbeaver.ce.feature.feature.group 7.3.2.202101032114)
>     To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [7.3.2.202101032114,7.3.2.202101032114]
>   Cannot satisfy dependency:
>     From: DBeaver 7.3.2.202101032114 (org.jkiss.dbeaver.core.product 7.3.2.202101032114)
>     To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [7.3.2.202101032114,7.3.2.202101032114]
>   Cannot satisfy dependency:
>     From: DBeaver Standalone 7.3.2.202101032114 (org.jkiss.dbeaver.standalone.feature.feature.group 7.3.2.202101032114)
>     To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.p2.discovery.feature.feature.group [1.2.800.v20200916-1234,1.2.800.v20200916-1234]

**Comment by serge-rider** [comment]
DBeaver 7.3.1+ is compible with the latest Marketplace only (1.9.+). Because it is based on Eclipse 2020-12.

Also there is a bug in DBeaver 7.3 which breaks recent Marketplace startup (because of lazy service IProxyService initialization). Fixed.

**Comment by uslss** [comment]
verified.
Tested against http://download.eclipse.org/mpc/releases/1.9.0

**Comment by ceinmart** [comment]
Hi, 
I just installed version 7.3.4 and tried to install the marketplace. 
They still shows version 1.8.2 for the market client.

The error persists: 
Is there something I should select different ? 
What I do  : 
help -> Install new software -> Work with all available sites -> search for market -> select it and try to install

> Cannot complete the install because of a conflicting dependency.
>   Software being installed: Marketplace Client 1.8.2.v20200309-0038 (org.eclipse.epp.mpc.feature.group 1.8.2.v20200309-0038)
>   Software currently installed: DBeaver 7.3.4.202101311042 (org.jkiss.dbeaver.core.product 7.3.4.202101311042)
>   Only one of the following can be installed at once: 
>     Equinox Provisioning Discovery UI 1.1.400.v20191213-1911 (org.eclipse.equinox.p2.ui.discovery 1.1.400.v20191213-1911)
>     Equinox Provisioning Discovery UI 1.2.0.v20200916-1234 (org.eclipse.equinox.p2.ui.discovery 1.2.0.v20200916-1234)
>   Cannot satisfy dependency:
>     From: Marketplace Client 1.8.2.v20200309-0038 (org.eclipse.epp.mpc.feature.group 1.8.2.v20200309-0038)
>     To: org.eclipse.equinox.p2.iu; org.eclipse.epp.mpc.ui [1.8.2.v20200309-0038,1.8.2.v20200309-0038]
>   Cannot satisfy dependency:
>     From: Marketplace Client 1.8.2.v20200309-0038 (org.eclipse.epp.mpc.ui 1.8.2.v20200309-0038)
>     To: osgi.bundle; org.eclipse.equinox.p2.ui.discovery [1.0.0,1.2.0)
>   Cannot satisfy dependency:
>     From: Equinox p2, Discovery UI support 1.2.800.v20200916-1234 (org.eclipse.equinox.p2.discovery.feature.feature.group 1.2.800.v20200916-1234)
>     To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.p2.ui.discovery [1.2.0.v20200916-1234,1.2.0.v20200916-1234]
>   Cannot satisfy dependency:
>     From: DBeaver Community Edition 7.3.4.202101311042 (org.jkiss.dbeaver.ce.feature.feature.group 7.3.4.202101311042)
>     To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [7.3.4.202101311042,7.3.4.202101311042]
>   Cannot satisfy dependency:
>     From: DBeaver 7.3.4.202101311042 (org.jkiss.dbeaver.core.product 7.3.4.202101311042)
>     To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [7.3.4.202101311042,7.3.4.202101311042]
>   Cannot satisfy dependency:
>     From: DBeaver Standalone 7.3.4.202101311042 (org.jkiss.dbeaver.standalone.feature.feature.group 7.3.4.202101311042)
>     To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.p2.discovery.feature.feature.group [1.2.800.v20200916-1234,1.2.800.v20200916-1234]

**Comment by ceinmart** [comment]
Hi @uslss  , please can you review this fix?

**Comment by ceinmart** [comment]
> Hi,
> I just installed version 7.3.4 and tried to install the marketplace.
> They still shows version 1.8.2 for the market client.
> 
> The error persists:
> Is there something I should select different ?
> What I do :
> help -> Install new software -> Work with all available sites -> search for market -> select it and try to install
> 
> > Cannot complete the install because of a conflicting dependency.
> > Software being installed: Marketplace Client 1.8.2.v20200309-0038 (org.eclipse.epp.mpc.feature.group 1.8.2.v20200309-0038)
> > Software currently installed: DBeaver 7.3.4.202101311042 (org.jkiss.dbeaver.core.product 7.3.4.202101311042)
> > Only one of the following can be installed at once:
> > Equinox Provisioning Discovery UI 1.1.400.v20191213-1911 (org.eclipse.equinox.p2.ui.discovery 1.1.400.v20191213-1911)
> > Equinox Provisioning Discovery UI 1.2.0.v20200916-1234 (org.eclipse.equinox.p2.ui.discovery 1.2.0.v20200916-1234)
> > Cannot satisfy dependency:
> > From: Marketplace Client 1.8.2.v20200309-0038 (org.eclipse.epp.mpc.feature.group 1.8.2.v20200309-0038)
> > To: org.eclipse.equinox.p2.iu; org.eclipse.epp.mpc.ui [1.8.2.v20200309-0038,1.8.2.v20200309-0038]
> > Cannot satisfy dependency:
> > From: Marketplace Client 1.8.2.v20200309-0038 (org.eclipse.epp.mpc.ui 1.8.2.v20200309-0038)
> > To: osgi.bundle; org.eclipse.equinox.p2.ui.discovery [1.0.0,1.2.0)
> > Cannot satisfy dependency:
> > From: Equinox p2, Discovery UI support 1.2.800.v20200916-1234 (org.eclipse.equinox.p2.discovery.feature.feature.group 1.2.800.v20200916-1234)
> > To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.p2.ui.discovery [1.2.0.v20200916-1234,1.2.0.v20200916-1234]
> > Cannot satisfy dependency:
> > From: DBeaver Community Edition 7.3.4.202101311042 (org.jkiss.dbeaver.ce.feature.feature.group 7.3.4.202101311042)
> > To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [7.3.4.202101311042,7.3.4.202101311042]
> > Cannot satisfy dependency:
> > From: DBeaver 7.3.4.202101311042 (org.jkiss.dbeaver.core.product 7.3.4.202101311042)
> > To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [7.3.4.202101311042,7.3.4.202101311042]
> > Cannot satisfy dependency:
> > From: DBeaver Standalone 7.3.4.202101311042 (org.jkiss.dbeaver.standalone.feature.feature.group 7.3.4.202101311042)
> > To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.p2.discovery.feature.feature.group [1.2.800.v20200916-1234,1.2.800.v20200916-1234]

Now I understand what I need to do.. .add the http://download.eclipse.org/mpc/releases/1.9.0 as source and get the marketclient from there...

**Comment by weiss-d** [comment]
> Now I understand what I need to do.. .add the http://download.eclipse.org/mpc/releases/1.9.0 as source and get the marketclient from there...

Got the following error trying this with Community Version 21.0.2.202104051733 . Maybe I've missed something?

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Marketplace Client 1.9.0.v20210108-0835 (org.eclipse.epp.mpc.feature.group 1.9.0.v20210108-0835)
  Missing requirement: Marketplace Client 1.9.0.v20210108-0835 (org.eclipse.epp.mpc.ui 1.9.0.v20210108-0835) requires 'osgi.bundle; org.eclipse.equinox.p2.ui 2.6.0' but it could not be found
  Cannot satisfy dependency:
    From: Marketplace Client 1.9.0.v20210108-0835 (org.eclipse.epp.mpc.feature.group 1.9.0.v20210108-0835)
    To: org.eclipse.equinox.p2.iu; org.eclipse.epp.mpc.ui [1.9.0.v20210108-0835,1.9.0.v20210108-0835]
```
