### ISSUE TITLE
Display column pin state in RSV filter settings

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#10984]
Currently we're not displaying pin state of columns in filter settings dialog, so pinning/unpinning multiple columns may be tedious.

**Comment by ShadelessFox** [comment]
Implemented (you are allowed to pin only top-level attributes):

![image](https://user-images.githubusercontent.com/35821147/128236774-b9eba187-165b-41f3-89bf-e4935bc7fcd1.png)

**Comment by uslss** [comment]
verified
