### ISSUE TITLE
Virtual column doesn't allow to create/remove a row

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10982]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.3 EA

#### Steps to reproduce, if exist:
1. Create a virtual column in a table
2. Delete or create a row in the table

Expected: the row is created and saved
Actual result: the row is not removed and the error appears: "Unknown column 'vcolumn' in 'field list'"

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
