### ISSUE TITLE
regex

### ISSUE THREAD

**Issue by MarcusR1** [dbeaver/dbeaver#10988]
#### System information: 
- Operating system (distribution) and version Digital Ocean 2 GB Memory / 50 GB Disk / LON1 - Ubuntu 18.04.3 (LTS) x64
- DBeaver version 7.3.0
- Java version n/a
- Additional extensions

#### Connection specification:
- Database name and version MariaDB 10.2
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? yes

#### Describe the problem you're observing:
I am trying to pick out urls that have certain known parameters but they can be in any order

example:
https://anyhostname.com/authorize?client_id=7NlWNUnEXgINzWBt&response_type=xyz&redirect_uri=https%3A%2F%2Fanyhost.com%2Findex%2Fcallback&auth0Client=987eyJuYW1lIjoiYXV0aDAuanMiLCJ
and I'm querying using:
WHERE resource_url RLIKE 
'^(?=.*\bclient_id\b)(?=.*\bresponse_type\b)(?=.*\bredirect_uri\b).*$'

which works perfectly in https://regex101.com/ and https://rubular.com/ but not in DBeaver. The MariaDB v10.2 specs https://mariadb.com/kb/en/pcre/ say that word boundaries (\b) are supported, but this query doesn't return any data.

#### Steps to reproduce, if exist:
go to regex101 and try it, then create a table with that URL in it and try my query, you'll see it doesn't work!

#### Include any warning/errors/backtraces from the logs
there aren't any logs because it doesn't produce an error, just no results!

**Comment by kseniiaguzeeva** [comment]
Please send a full query to reproduce. I receive no results in different clients when I run query:
```
select 1
WHERE 'https://anyhostname.com/authorize?client_id=7NlWNUnEXgINzWBt&response_type=xyz&redirect_uri=https%3A%2F%2Fanyhost.com%2Findex%2Fcallback&auth0Client=987eyJuYW1lIjoiYXV0aDAuanMiLCJ' 
rlike '^(?=.\bclient_id\b)(?=.\bresponse_type\b)(?=.\bredirect_uri\b).$'
```

**Comment by uslss** [comment]
There is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it.
