### ISSUE TITLE
improve dbeaver UX / reduce number of clicks needed to open a table

### ISSUE THREAD

**Issue by himat** [dbeaver/dbeaver#10997]
**Is your feature request related to a problem? Please describe.**

It takes far too many clicks to open up tables after I first open dbeaver.

Here's a screenshot of the dbeaver tree for a db connection I have open:
![image](https://user-images.githubusercontent.com/1156974/104796850-d45d0700-5787-11eb-9d90-aacc22473260.png)

When I first open the dbeaver program, the tree is completely closed, so it takes 5 clicks on the caret icons to expand to the actual tables finally, and then I have to double click on the table that I then want to open. This takes up far too much mental burden than necessary especially when I'm in a flow and open up dbeaver to inspect the data in a table, and I have to slow down just to navigate the tree to the tables.

Now, compare this to this other database browser called Postico: 
![image](https://user-images.githubusercontent.com/1156974/104796866-e2128c80-5787-11eb-926a-a7f1f6904d64.png)

In this application, there are no extra clicks! The program opens to this screen by default where all the tables are listed on the left side, and it only takes one click to open any table. This has literally reduced the number of clicks just to open a table from dbeaver's 7 to just 1!

I would just Postico all the time as it's far faster and simpler to use, but there are certain advanced features in dbeaver that I need to use sometimes as well so I'd rather make dbeaver work for me all the time.

**Describe the solution you'd like**
It would be great to make dbeaver as easy to use as postico is.
Possible ways to do this
- Add a setting to fully auto expand the db tree when dbeaver is started
- Add a setting to open a table with a single click instead of needing a double click
- Add a setting to show a simplified table browser that only shows the tables inside schemas>public>tables and doesn't show all the other many nodes like pg_catalog, views, indexes, functions, etc.

**Comment by himat** [comment]
This answer solved most of the issues https://stackoverflow.com/a/65746715/1807163

The only other nice to have feature would be - Add a setting to open a table with a single click instead of needing a double click

**Comment by kseniiaguzeeva** [comment]
Could you please create a separate feature request for it?
