### ISSUE TITLE
Shortcut to create index on column

### ISSUE THREAD

**Issue by haugs** [dbeaver/dbeaver#10990]
**Is your feature request related to a problem? Please describe.**
I often want to add a simple index (i.e. not composite) to an existing column in a table. This happens for example when I stumble upon inefficient queries during database tuning.
Of course DBeaver can already create indexes, but I need to go to the Indexes Tab, create a new Index and then find the correct column in the possibly long list of columns.

**Describe the solution you'd like**
I would love to be able to right-click on a row in the Columns tab and have an option "Create New Index for this column".
("a row in the Columns tab" is a column in the actual table :) )

**Describe alternatives you've considered**
The option could also be provided under the "Generate SQL" section of the right-click menu in the Columns tab.
Obviously there is still the way to go to the Index tab and start the workflow from there.

**Additional context**
I love DBeaver and use it everyday in a professional environment. I stumbled upon this topic several times now - that's why I finally considered suggesting this small shortcut.
We mainly (but not exclusively) work with PostgreSQL.

Additional information: PostgreSQL requires no index at the source of a foreign key and therefore does not automatically create one. But I encountered many situations where this is a bad idea. A further leading feature request could make DBeaver warn against such situations when displaying the foreign keys.

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea.

**Comment by flambchap** [comment]
Implemented. We also decided to go a bit further.

![Screenshot 2021-03-17 122217](https://user-images.githubusercontent.com/26031301/111444520-82027d00-871b-11eb-8a8b-22daa5b740f3.png)

**Comment by haugs** [comment]
The screenshot looks great and promising! :)
Maybe the new functionality is not "important" enough though to keep it at the top of the popup menu?

**Comment by uslss** [comment]
verified. Will be available in 21.0.1
