### ISSUE TITLE
Import data from a CSV with Byte Order Marker (BOM) messes up the name of the first column

### ISSUE THREAD

**Issue by antoniustefan** [dbeaver/dbeaver#10994]
This is similar to the issue #670 but that was about reading the file using a CSV JDBC connection driver (newer versions of that driver indeed fix that issue), this issue is about using DBeaver's own "Import Data" wizard to read from a CSV.

#### System information: 
- Windows 8.1
- DBeaver version 7.3.2

#### Describe the problem you're observing:
When using the "Import Data" wizard to import a CSV file that has a byte order marker, the name of the first column includes that byte order marker.
DBeaver will try to match this incorrect column name to the destination table and will create it even if the correct name exists.

#### Steps to reproduce, if exist:
1. Right click on any table from a connection (does not matter which connection you are using) and select "Export Data".
2. Select "Export to CSV file(s)"
3. Click Next twice
4. In the "Output" screen make sure that encoding is UTF-8 and "Insert BOM" is selected
5. Click Next and Start to export that table to a CSV file
6. Right click on the same table, and select "Import Data" (this is just for testing brevity, the same issue applies if you are importing to another connection, regardless of new or existing destination table)
7. Select "Import from CSV file(s)"
8. Click Next and then open the file that you just exported earlier
9. In the "Input file(s)" screen click Next again
10. In the "Table mappings" notice that the target table is identified as existing, but when you expand the table to see the columns, you will see that the first column is marked as non existing and DBeaver will attempt to created it
- If you manually map this to the existing column the import will then carry out just fine
- If you don't change the mapping manually, DBeaver will try to create this new column and depending on your destination database it will actually be able to create a new column with BOM in the name (I tested Postgres and MySQL) or the database will refuse the strange name (I tested MSSQL).

Thanks!

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by ShadelessFox** [comment]
Now the importer is BOM-unaware, but you still have to specify valid encoding during import.

**Comment by kseniiaguzeeva** [comment]
verified
