### ISSUE TITLE
Auto complete: list all column names from the source

### ISSUE THREAD

**Issue by bcm5645** [dbeaver/dbeaver#10995]
There is a request #10481 for selecting more columns at once, but can this be somehow combined and auto-complete all columns names from the source table/view. In sql developer it's achieved when you press Ctrl and hover the mouse over star in select * from some_view. I don't expect to work the same, such as a suggestion.
It would work the way if you type **Select from some_view.*** and when press Enter then it will auto-complete column names, e.g.
SELECT col1, col2, col3 from some_view

**Comment by LonwoLonwo** [comment]
@bcm5645 Hello
We have this option already.
![2021-01-17 22_26_53-DBeaver 7 3 2 - _DBeaver Sample Database (SQLite)_ Script-33](https://user-images.githubusercontent.com/45152336/104853718-bc19f300-5913-11eb-8b68-bd8cbb4d6005.png)

Just use ctrl+space after asterisk in query.
Example: "Select *[use it here] from some_view"

Is this what you were looking for?

**Comment by bcm5645** [comment]
Hi,
this is exactly what i was looking for.
Thank you.
