### ISSUE TITLE
Virtual tab is not visible in table properties in Custom view

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10998]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.3 EA

#### Connection specification:
- Database name and version MySQL

#### Steps to reproduce, if exist:
Select in MySQL context menu Connection view>Custom>Show system objects/Show utility objects

**Expected:** all properties tabs remain visible
**Actua result**: Virtual tab is not displayed
![dbeaver_nxPCowlcwY](https://user-images.githubusercontent.com/51405061/104798049-6e4aa100-57d4-11eb-9a8d-3e7f2398807f.png)

Additional question:.
Is it expected that  Connection view>Custom>Show only tables and Hide folders have different properties view?
Show only schemas and tables
![dbeaver_KipmPFHdqD](https://user-images.githubusercontent.com/51405061/104797982-d2b93080-57d3-11eb-81bb-12d8c11e00b8.png)

Hide folders
![dbeaver_TaQ9MUGRBB](https://user-images.githubusercontent.com/51405061/104797984-d8167b00-57d3-11eb-942f-e9e8dfb14204.png)

**Comment by LonwoLonwo** [comment]
About question - tool-tips are very helpful, I think

![2021-06-17 09_56_44-DBeaver Enterprise 21 1 1 - _localhost_ Script-39](https://user-images.githubusercontent.com/45152336/122347370-a22c1d00-cf52-11eb-8349-b184f7b0b5b4.png)

![2021-06-17 09_58_04-DBeaver Enterprise 21 1 1 - _localhost_ Script-39](https://user-images.githubusercontent.com/45152336/122347373-a2c4b380-cf52-11eb-9498-8142f9f9403f.png)

**Comment by uslss** [comment]
not reproducible anymore
