### ISSUE TITLE
Actual viewing of saved content/formatting of a procedure

### ISSUE THREAD

**Issue by JuniorVitor** [dbeaver/dbeaver#10992]
**Is your feature request related to a problem? Please describe.**
When viewing the contents of a procedure on the sql server with sp_helptext, the content comes with a double line break, a different format than the one created and others characters. Even when viewing the text, it does not return in the format created.

**Describe the solution you'd like**
The return of the sp_helptext view comes in the same way as the procedure is created or updated.

**Comment by kseniiaguzeeva** [comment]
Sorry for the long responce. I cannot reproduce it. As I see the result returns according procedure DDL.
![dbeaver_0quWB7wXlS](https://user-images.githubusercontent.com/51405061/106431947-0c9a6000-647f-11eb-8199-b11bc952b455.png)

Can you give additional details to reproduce?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info
