### ISSUE TITLE
Java version errors: show clear error

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#11004]
Currently Eclipse prints some weird and very unobvious errors in logs when local Java version is less than 11.
We need to show more clear error (like Java 11 is required)

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/104808015-5125ca80-57f4-11eb-9717-c39d58fb5c2a.png)

**Comment by uslss** [comment]
verified
