### ISSUE TITLE
Wrong foreign key DDL

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11007]
#### System information: 
- DBeaver version 7.3.3 EA

#### Connection specification:
- Database name and version Informix

#### Steps:
Open a table DDL with a foreign key

Expected: https://www.ibm.com/support/knowledgecenter/SSGU8G_14.1.0/com.ibm.sqls.doc/ids_sqs_0301.htm
Actual result:
```
CREATE TABLE stores_demo:informix.detail (
	col_one integer,
	col_twain char(1),
	FOREIGN KEY (col_one) REFERENCES stores_demo:informix.master(col_one) **ON DELETE CASCADE ON UPDATE RESTRICT** CONSTRAINT detail_fork1
);
CREATE INDEX 169_159 ON stores_demo:informix.detail (col_one);
```

**Comment by LonwoLonwo** [comment]
Fixed in 21.0.1

**Comment by LonwoLonwo** [comment]
Fixed. Finally.

**Comment by LonwoLonwo** [comment]
Also PK and UK DDL inside table fixed in EE version ("CONSTRAINT" word removed)

**Comment by kseniiaguzeeva** [comment]
verified
