### ISSUE TITLE
Persist column sorting

### ISSUE THREAD

**Issue by himat** [dbeaver/dbeaver#11009]
**Is your feature request related to a problem? Please describe.**

Is there a way to persist column sorting? I often sort by the primary key column on my tables but to do this I have to manually press the sorting icon on the ID column twice so that it shows me the most recent rows first.

**Describe the solution you'd like**

It would be far better if I didn't have to do this all the time and could set a default to sort by the primary column instead.

**Comment by p91paul** [comment]
near the filter bar on tables there's a save icon. That saves you orderings on that table.
