### ISSUE TITLE
Preferences search not working for "booleans"

### ISSUE THREAD

**Issue by g24swint** [dbeaver/dbeaver#11017]
#### System information: 
- Operating system (distribution) and version - Windows 10
- DBeaver version Enterprise 7.3.0
- Additional extensions

#### Connection specification:
- Database name and version - Postgresql 11
- Driver name 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

When searching for the preference to get booleans to display correctly, the preference feature is not showing up in a "search" of the preferences. 

For instance, in the searchbox below, I'd expect the search pane to display in bold Editors/Data Editor/Appearance/Grid when I type in "booleans" to fix booleans to display 
![image](https://user-images.githubusercontent.com/82784/104821797-eed4c600-5803-11eb-80bc-ee154df8de98.png)

In contrast, if I search for attribute, it correctly shows the correct location of the preference setting
![image](https://user-images.githubusercontent.com/82784/104821817-25124580-5804-11eb-816a-d47681b0df3f.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. Looks like the enhancement.

**Comment by g24swint** [comment]
@kseniiaguzeeva it looks like there's a similar problem when searching for "parameter" as well.

**Comment by kseniiaguzeeva** [comment]
Yes, the search works only for table of content. It hasn't been possible to implement text search in older Eclipse version, but we should try again (an autogenerating search index has to be created).

**Comment by E1izabeth** [comment]
Works for "boolean" in DBeaver 23.0.5

![image](https://github.com/dbeaver/dbeaver/assets/28875055/e07496fe-dedf-40d9-8b21-63b235154cd9)
