### ISSUE TITLE
doc: flatpak hub missing update command

### ISSUE THREAD

**Issue by rajinder-yadav** [dbeaver/dbeaver#11019]
On this page: https://flathub.org/apps/details/io.dbeaver.DBeaverCommunity

At the bottom, add missing "upgrade" command:

Update:
```sh
flatpak update io.dbeaver.DBeaverCommunity
```

**Comment by kseniiaguzeeva** [comment]
Unfortunately we cannot influence this. It's flathub issue.

**Comment by rajinder-yadav** [comment]
Actually you can and should, by opening a bug with them to correct the information. I only brought this to your attention to help your users. This is how improvements are done, when people take initiative.
