### ISSUE TITLE
'%(%' and long lines mess up statement separation

### ISSUE THREAD

**Issue by icyerasor** [dbeaver/dbeaver#11012]
#### System information: 
- Win10
- Version 7.3.2.202101032114
- Additional extensions: none

#### Connection specification:
- PostgreSQL

#### Describe the problem you're observing:
Having a '%(%' in my sql-statement seems to mess up statement-termination with ";" or blank lines. Instead of stopping to execute,  it just keeps going on, which is potentially very dangerous, as it might include modifying statments?

It only occurs though, when followed (potentially very much later in the file) by some looong lines

#### Example Statement:
Copy or open the following file in DBeaver. If you copy it into a new sql file, make sure to close it once and reopen it.
[overflow.txt](https://github.com/dbeaver/dbeaver/files/5824772/overflow.txt)
It has one (commented!) line that is over 2 million characters long - that seems to be *one* cause of the issue. Another is the presence of `'%(%'` - changing it to `'%)%'` makes it work okay again!

#### Expected behavior:
Grouped according to statements.
![grouped](https://user-images.githubusercontent.com/364161/104817708-243cdc00-5823-11eb-9698-1abff7deed57.PNG)

#### Actual behavior:
Ungrouped, when executing with Ctrl+Enter or the single-execute icon.. everything would execute!
![overflow](https://user-images.githubusercontent.com/364161/104817730-47678b80-5823-11eb-882b-71ba8125b366.PNG)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.
I can reproduce the issue with the brackets only (the comment length doesn't matter)

**Comment by kseniiaguzeeva** [comment]
Exact steps to reproduce:
1. Open SQL Editor, insert the script from the issue, save and close the script
2. Reopen the script, place focus on the first query and press **Execute SQL statement** button

Expected: the first query executes from the script only.
Actual result: the whole script executes

https://user-images.githubusercontent.com/51405061/105470543-bbce7e80-5caa-11eb-9a96-abb362bbaa9b.mp4

**Comment by kseniiaguzeeva** [comment]
verified
