### ISSUE TITLE
Partition picklist in table Oracle

### ISSUE THREAD

**Issue by mipi21** [dbeaver/dbeaver#11016]
Is it possible to add in the detail of the table the possibility to see only the data of a specific partition? Example :
Detail Table - select partition 20201231 and show only the data of that partition. A picklist of partitions ...

**Comment by kseniiaguzeeva** [comment]
Good idea! We are going to implement it.

**Comment by mipi21** [comment]
there is a problem for this issue?

**Comment by mipi21** [comment]
news?
