### ISSUE TITLE
Data transfer doesn't work with Truncate option

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11015]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.3 EA

#### Connection specification:
- Database name and version Informix

#### Steps to reproduce, if exist:
Perfom export/import to a table with enabled Truncate option

**Expected**: the old data is removed, the data from file/table is inserted
**Actual result:** 
1. The old data is removed, but no data is inserted
2. Error appears: SQL Error [IX000]: No operations allowed after truncate or online alter fragment in a transaction.

**Comment by LonwoLonwo** [comment]
“ In Informix, the behaviour of TRUNCATE is slightly different; you can use TRUNCATE in a transaction, but the only statements permissible after that are COMMIT and ROLLBACK.”

**Comment by LonwoLonwo** [comment]
Fixed. Now export works fine with truncate option (we added commit after executing truncate statement)

Works ONLY in [EE version](https://dbeaver.com/)!

**Comment by Matvey16** [comment]
Verified
