### ISSUE TITLE
Table triggers folder is opening for 2 minutes or more

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11013]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.3 EA
- Additional extensions

#### Connection specification:
- Database name and version Informix
#### Describe the problem you're observing:
I have the only trigger in Table Triggers folder and it takes more then 2 minutes to open the folder

**Comment by LonwoLonwo** [comment]
Fixed for: HSQL, Informix, Teradata, Firebird, Sybase, SQLite, Old PostgreSQL
More parameters for Informix Trigger and HANA Trigger added
HSQL view and trigger definitions improved
Implemented in DBeaver 21.1.2

**Comment by uslss** [comment]
verified
