### ISSUE TITLE
Spatial view tab of Data Editor doesn't show places on the map when some cells have wrong data

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11021]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.3 EA

#### Connection specification:
- Database name and version MySQL
#### Steps to reproduce, if exist:
Precondition: open a table with correct and incorrect data in cells of geometry type.

1. Select a cell with a geometry data in Data Editor
2. Check that the place is displayed in the Value panel (select a map to see theplace)
3. Open Spatial tab and select the same map

Expected: the place is displayed on the map
Actual result: empty map is displayed

https://user-images.githubusercontent.com/51405061/104836029-b4c6fb00-58bb-11eb-92e0-e7ddac3908ab.mov

**Comment by ShadelessFox** [comment]
Invalid geometry data example: `POINT (766456911 13.5639657)`

I don't see a nice solution for this problem except to ignore such invalid values when passing them for Leaflet.

**Comment by uslss** [comment]
seems issue is obsolete for now
