### ISSUE TITLE
More than one column can be pinned one-by-one only

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#11022]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.3.3

#### Describe the problem you're observing:
More than one column cannot be pinned. Also, Pinned column cannot be rearranged
Select more than one column and choose - pin column in the context menu - only the last chosen column is pinned. Column could p pinned|unpinned only one-by-one
![2021-01-17_14h04_11](https://user-images.githubusercontent.com/31996417/104838598-f613d680-58cc-11eb-9a4f-f549dfa8ae96.gif)

**Comment by ShadelessFox** [comment]
A separate ticket was created from second issue: #13447

**Comment by ShadelessFox** [comment]
Implemented:

https://user-images.githubusercontent.com/35821147/128324769-32ae1d01-8fd6-4084-bbc2-c7a7c89f3add.mp4

**Comment by uslss** [comment]
verified
