### ISSUE TITLE
Issue while connecting to Redshift using SAML

### ISSUE THREAD

**Issue by niraj8241** [dbeaver/dbeaver#11020]
I am having a strange issue using the DBeaver community edition.

# Problem
Setup connection to multiple redshift cluster using different SAML connection. Connect to connection 1 and after the connection is established. Connect to Connection 2 and it will fail. DBeaver will show the error information with details of Connection 1 in the error dialog box.

# Expected Behavior
DBeaver should be able to connect to both the cluster irrespective of the configuration.

# DBeaver Version
**Version 7.1.2.202007051953**

Please let me know if you need more information

**Comment by kseniiaguzeeva** [comment]
Please tell:
- which type of authentication do you use
- steps how do you connect

**Comment by niraj8241** [comment]
Sorry, I somehow lost track of this.

- which type of authentication do you use
  >> So I am using Redshift's SSO authentication using SAML. It's called the browser SAML plugin.
        [SSO Link](https://docs.aws.amazon.com/redshift/latest/mgmt/options-for-providing-iam-credentials.html)
        The plugin name is **com.amazon.redshift.plugin.BrowserSamlCredentialsProvider**


steps how do you connect
- Configure PingFederate to setup Redshift SSO (https://docs.aws.amazon.com/redshift/latest/mgmt/options-for-providing-iam-credentials.html#setup-pingfederate-identity-provider)
- Perform the above step for the second Redshift connection. ( We need multiple clusters )
- Setup your DBeaver connection to use Browser SAML plugin ( **com.amazon.redshift.plugin.BrowserSamlCredentialsProvider
**)
- Try to establish the connection with the First Redshift. Once the connection is established.
- Connect the second one. This should fail.

**Comment by kseniiaguzeeva** [comment]
How do you set the connection in DBeaver? Please send screenshots. DBeaver Enterprise supports AWS IAM authentication, you can see trial version, the problem shouldn't appear there https://dbeaver.com/trial/.

**Comment by uslss** [comment]
There is no update on an issue for a long time.
If it is still actual for you - feel free to reopen an issue.
