### ISSUE TITLE
I wonder if i can set one item to make the whole software interface enlarge some proportion?

### ISSUE THREAD

**Issue by bh1044501616** [dbeaver/dbeaver#11025]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kseniiaguzeeva** [comment]
Please try to add the setting to dbeaver.ini. [Here](https://github.com/dbeaver/dbeaver/issues/3141) you can find advices.

**Comment by uslss** [comment]
There is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it.

**Comment by b-hayes** [comment]
please re-open. Text is blurry on my 4k screen. If I manually set the UI scale in the ini file and tell windows to let the application manage the UI scale, then the application becomes ridiculously massive when I drag it off to a secondary display that isn't 4k.

The workaround is not a solution. It helps but it's not a solution. Most applications change scale to match windows settings when dragged from one screen to the other.

Additionally UI scales change on the fly in situations such as the user just increases decreases the scale to suit the current task, or when they RDP in from another device the UI scale change them to match the device being used by the remote user. In this instance, most other applications can respond to windows UI scale changes when the window is resized.
