### ISSUE TITLE
Support overloading of Snowflake stored procedure names

### ISSUE THREAD

**Issue by stanorama** [dbeaver/dbeaver#11028]
**Is your feature request related to a problem? Please describe.**
Snowflake stored procedure names can be overloaded.
The names are unique in combination with the parameter types.
So the following can both co-exist:
PUBLIC.SP_RUN(FLOAT);
PUBLIC.SP_RUN(VARCHAR);

**Describe the solution you'd like**
In the navigation explorer show Snowflake stored procedures with the their parameters.
When deleting stored procures concatenate the parameter data types as part of the DDL statement.
e.g. DROP PROCEDURE PUBLIC.SP_RUN(FLOAT);

**Describe alternatives you've considered**
Drops have to be performed manually in the SQL editor. The information schema is used to determine what the parameter data types are (procedure signature).

**Additional context**

`CREATE PROCEDURE PUBLIC.SP_RUN(A FLOAT)
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS $$

 //
$$;`

`CREATE PROCEDURE PUBLIC.SP_RUN(A VARCHAR)
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS $$

 //
$$;`

`SELECT * FROM INFORMATION_SCHEMA.PROCEDURES WHERE PROCEDURE_NAME = 'SP_RUN' AND PROCEDURE_SCHEMA = 'PUBLIC';`

![image](https://user-images.githubusercontent.com/51097996/104895388-b6e99200-596d-11eb-93f4-007c01eab534.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea.

**Comment by LonwoLonwo** [comment]
DROP statement fixed (now including procedure/function parameters)

**Comment by uslss** [comment]
verified
