### ISSUE TITLE
Tip of the Day overview

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#11026]
We need to make sure that currently available tips are relevant - e.g. don't contain any outdated shortcuts and etc.
Also we should provide new tips that will overview newly added features.

**Comment by kseniiaguzeeva** [comment]
Some misprint corrections are needed. 
Separate ticket will be created to show tips on startup.

**Comment by flambchap** [comment]
Spelling has been fixed.

**Comment by kseniiaguzeeva** [comment]
verified
