### ISSUE TITLE
TXT Exporter: 'max column length' property behavior is incorrect

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#11027]
Max column length property affects every column and pads them with spaces to desired length.
This is incorrect, because it should limit max column length and not affect padding.

### Expected:
```
|GenreId|Name      |
|-------|----------|
|1      |Rock      |
|2      |Jazz      |
|3      |Metal     |
|4      |Alternativ|
|5      |Rock And R|
|6      |Blues     |
|7      |Latin     |
|8      |Reggae    |
|9      |Pop       |
|10     |Soundtrack|
```
### Actual:
```
|GenreId   |Name      |
|----------|----------|
|1         |Rock      |
|2         |Jazz      |
|3         |Metal     |
|4         |Alternativ|
|5         |Rock And R|
|6         |Blues     |
|7         |Latin     |
|8         |Reggae    |
|9         |Pop       |
|10        |Soundtrack|
```
Max column length is set to `10` and it's padding columns instead of trimming them.

**Comment by ShadelessFox** [comment]
May be similar to #7401

**Comment by kseniiaguzeeva** [comment]
Also about txt export  https://github.com/dbeaver/dbeaver/issues/7345

**Comment by ShadelessFox** [comment]
Another issue: binary data is included as plain string, ignoring 'Binaries' option.

Moved to #11200

**Comment by ShadelessFox** [comment]
Changelog:
1. Max column length now controls max "fittable" data into column, not the column width itself
2. Added 'in-between separator' option to remove/add separators between columns

**Comment by uslss** [comment]
column headers become unreadable in case of disabling in-between separator
![image](https://user-images.githubusercontent.com/31996417/107016880-8304ce00-67af-11eb-86b7-42570bd223f2.png)

**Comment by uslss** [comment]
verified

**Comment by Pandi4239** [comment]
<img width="960" alt="image" src="https://github.com/dbeaver/dbeaver/assets/170426922/1caed141-36b0-4a71-b6fb-d6be60cb81e2">

during export data TXT extra space coming

**Comment by ShadelessFox** [comment]
Please create a new issue instead of commenting on a closed one.
