### ISSUE TITLE
Binaries set to 'NULL' are treated as 'Inline'

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#11030]
#### Describe the problem you're observing:
When trying to export, for example, a table to CSV, its binary contents are included if 'Binaries' option is set to 'NULL'

#### Steps to reproduce, if exist:
1. Open table, click 'Export Data'
2. Select CSV as a target
3. Make sure 'Binaries' is set to 'NULL'
4. Proceed

**Comment by ShadelessFox** [comment]
Another issue related to TXT exporter: binary data is included as plain string, ignoring 'Binaries' option.

**Comment by ShadelessFox** [comment]
Actually this is happening only if `Copy to clipboard` is set.

**Comment by kseniiaguzeeva** [comment]
Verified
