### ISSUE TITLE
Wrong tablespace available and used size

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#11038]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.3.2
- Java version: bundled
- Additional extensions: n/a

#### Connection specification:
- Database name and version: Oracle 11/12
- Driver name: ojdbc19
- Do you use tunnels or proxies (SSH, SOCKS, etc)? n/a

#### Describe the problem you're observing:

The following query is used to show available and used space for tablespaces:

```
SELECT TS.TABLESPACE_NAME,SUM(F.BYTES) AVAILABLE_SPACE,SUM(S.BYTES) USED_SPACE 
FROM SYS.DBA_TABLESPACES TS,DBA_DATA_FILES F,DBA_SEGMENTS S
WHERE F.TABLESPACE_NAME(+)=TS.TABLESPACE_NAME AND S.TABLESPACE_NAME(+)=TS.TABLESPACE_NAME
GROUP BY TS.TABLESPACE_NAME
```
This query first joins DBA_DATA_FILES and DBA_SEGMENTS, then groups and sums the result. So available space is multiplied for the number of data segments (and because of that is usually HUGE) and used is multiplied for the number of data files (so it can occasionally be correct if there is only a data file for that tablespace).

The correct query would be:
```
SELECT TS.TABLESPACE_NAME, F.AVAILABLE_SPACE, S.USED_SPACE 
FROM SYS.DBA_TABLESPACES TS, 
(SELECT TABLESPACE_NAME, SUM(BYTES) AVAILABLE_SPACE FROM DBA_DATA_FILES
GROUP BY TABLESPACE_NAME) F,
(SELECT TABLESPACE_NAME, SUM(BYTES) USED_SPACE FROM DBA_SEGMENTS
GROUP BY TABLESPACE_NAME) S
WHERE F.TABLESPACE_NAME(+)=TS.TABLESPACE_NAME AND S.TABLESPACE_NAME(+)=TS.TABLESPACE_NAME
```
Here the group by is done before joining, so no product is performed.

**Comment by uslss** [comment]
verified
