### ISSUE TITLE
Incorrect format of generated binary literals

### ISSUE THREAD

**Issue by alumni** [dbeaver/dbeaver#11036]
#### System information: 
- Operating system (distribution) and version: _any_
- DBeaver version: _7.2.3 and earlier_
- Java version: _any_
- Additional extensions: _none_

#### Connection specification:
- Database name and version: _HANA Cloud (4.0), also earlier_
- Driver name: _com.sap.db.jdbc.Driver, 2.7.9 and earlier_
- Do you use tunnels or proxies (SSH, SOCKS, etc)? _no_

#### Describe the problem you're observing:
In short: Binary literals are generated as `0x<value>` instead of `X'<value>'`, where `<value>` is the value in hexadecimal format.

Long: Generated binary literals use the non-standard format: `0xAABB`. However, the SQL standard specifies that  `X'AABB'` should be used instead. Some of the DBs (like MariaDB) still support the non-standard format probably for compatibility reasons, but others (like HANA) don't (HANA actually treats `0xAABB` as an hexadecimal integer value).

Snippet from the ANSI SQL '92 Standard:
```ebnf
         <hex string literal> ::=
              X <quote> [ <hexit>... ] <quote>
                [ { <separator>... <quote> [ <hexit>... ] <quote> }... ]
```
HANA 2.0.5 docs: https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.05/en-US/20a1569875191014b507cf392724b7eb.html

#### Steps to reproduce, if exist:
1. Create a table with a binary primary key.
2. Go to table data and try to delete a row. Save and refresh the data. The row is still there.
3. Alternatively, go to table data and right click a row, then generate delete query. Run the generated query to get the following error:

> SQL Error [266] [07006]: SAP DBTech JDBC: [266] (at 43): inconsistent datatype: INT type is not comparable with VARBINARY type.: line 2 col 12

**Comment by uslss** [comment]
verified
