### ISSUE TITLE
Everytime I open app I am welcomed with an error "Update Job"

### ISSUE THREAD

**Issue by sujeet-agrahari** [dbeaver/dbeaver#11046]
![image](https://user-images.githubusercontent.com/22151975/105031223-023d9680-5a7b-11eb-8282-3fa76c08f768.png)

Also, it just keeps connecting occasionally and never finishes connecting.
I have gone through an issue for the same, and my database doesn't have huge number of tables or data.
![image](https://user-images.githubusercontent.com/22151975/105031597-8859dd00-5a7b-11eb-8fc4-7317f21d9432.png)
![image](https://user-images.githubusercontent.com/22151975/105031626-94de3580-5a7b-11eb-8f3c-bc017f9edeae.png)

**Comment by uslss** [comment]
please try to reset workspace using File - Reset workspace state or using this [guide](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)

**Comment by AdamSr1949** [comment]
Hello All,
I have had the same problem every time I update and you have to install additional software
like Office or Git additions.
After you update and are suggested to "Re-Start" don't re-start just close dBeaver 
then Right click on the dBeaver Shortcut and Select "Run as Administrator"
and you shouldn't have that problem again. (It is a matter of getting used to right clicking the shortcut)

Regards.

**Comment by sujeet-agrahari** [comment]
Thanks, but I tried all the things mentioned, nothing helped.
1. Deleted `workbench.xmi`
2. Also, deleted `.metadata`
3.  Tried `Reset Workspace State` in file menu

Still pop up shows up after some time when app is launched and running.

**Comment by p91paul** [comment]
you could try entirely deleting the ~/.eclipse/org...dbeaver.product.xxx/ folder, it should be recreated on next startup

**Comment by sujeet-agrahari** [comment]
> you could try entirely deleting the ~/.eclipse/org...dbeaver.product.xxx/ folder, it should be recreated on next startup

What will happen to the saved connections? Will it be lost?

**Comment by UlrichDemlehner** [comment]
> you could try entirely deleting the ~/.eclipse/org...dbeaver.product.xxx/ folder, it should be recreated on next startup

Which one? After updating to v7.3.3, I have two such directories: .... \.eclipse\org.jkiss.dbeaver.product_7.3.2_1535670467_win32_win32_x86_64 and ...\.eclipse\org.jkiss.dbeaver.product_7.3.3_1535670467_win32_win32_x86_64. The error message mentions the 7.3.2 directory which is a bit confusing. Why should v7.3.3 look for a v7.3.2 directory?

Could it be that this causes the problem?

**Comment by p91paul** [comment]
I'm not sure, but that should be the folder where your plugins are installed, and sometimes it can get corrupted.
Anyway, all settings are saved in appdata/roaming/dbeaver, so you are not going to lose anything. To be sure, better rename than delete. 

I'd try just renaming the 7.3.2 folder, if not enough 7.3.3 as well.

**Comment by UlrichDemlehner** [comment]
Did not work. I renamed both directories. When DBeaver started, a new directory <...\org.jkiss.dbeaver.product_7.3.3_1535670467_win32_win32_x86_64> was created, but after a few seconds, the old Update Job error message appeared. At least it mentions now the correct version:

Während "Update Job" ist ein interner Fehler aufgetreten.
Registry Directory not available: C:\Users\...\.eclipse\org.jkiss.dbeaver.product_7.3.3_1535670467_win32_win32_x86_64.bak\p2\org.eclipse.equinox.p2.engine\profileRegistry.

Any other ideas to test?

**Comment by p91paul** [comment]
https://github.com/dbeaver/dbeaver/issues/10768 was also reopened after being closed with a similar solution. Looks like the workaround is no longer working...

**Comment by kseniiaguzeeva** [comment]
@UlrichDemlehner, @sujeet-agrahari please try to [Reset workspace](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace) and delete folder **.eclipse** (nothing will be lost)

**Comment by UlrichDemlehner** [comment]
Reset workspace had no effect but deleting .eclipse did the trick.

**Comment by kseniiaguzeeva** [comment]
Thank you. Will be fixed in #10768. Closed as duplicate.
