### ISSUE TITLE
Ubuntu ppa repository out of date

### ISSUE THREAD

**Issue by jarofromel** [dbeaver/dbeaver#11043]
#### System information: 
- Ubuntu 20.04.1 LTS (Xubuntu)
- DBeaver 7.3.0.202012062025

#### Describe the problem you're observing:
There is no updated version in the ppa repository (it started during December). When I start Dbeaver I see the message about the new version but there is no new version available in the ppa repo.

#### Steps to reproduce, if exist:
I install and update DBeaver over the apt ppa repository as described in https://dbeaver.io/download/.
apt source `deb http://ppa.launchpad.net/serge-rider/dbeaver-ce/ubuntu focal main`
There is no new versions available since December

#### Include any warning/errors/backtraces from the logs
No warning or error messages.

**Comment by jarofromel** [comment]
#7126 is probably the same problem experienced before.

**Comment by schmitzkr** [comment]
there is detail about this here https://github.com/dbeaver/dbeaver/issues/10916

**Comment by uslss** [comment]
closed as a duplicate of #10916 

anyway thanks for the report
