### ISSUE TITLE
Option to disable foreign key checks when importing data via Data Transfer tool

### ISSUE THREAD

**Issue by rlaunch** [dbeaver/dbeaver#11047]
**Is your feature request related to a problem? Please describe.**
When importing multiple tables with the Data transfer tool, multiple foreign key checks fail as the database has not been fully populated.

**Describe the solution you'd like**
A toggle option in the UI to disable foreign key checks, exactly like the one in the 'Restore Database' tool

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by flambchap** [comment]
Implemented. For now, this option is available for Oracle and Postgres only, but we'll add support for other databases somewhere in the future.

**Comment by uslss** [comment]
verified

**Comment by bratanon** [comment]
For MariaDB/MySQL

```
SET foreign_key_checks = 0;
SET foreign_key_checks = 1;
```

**Comment by ObjectAssign** [comment]
@n5a5 how is the implementation going? is this possibe for mysql?

**Comment by flambchap** [comment]
@ObjectAssign Implemented for MySQL and MariaDB in the scope of https://github.com/dbeaver/dbeaver/issues/11908

**Comment by ObjectAssign** [comment]
@n5a5 i come from heidisql, i were able to easily export datasets of 250mb to the clipboard, to copy into my dev db, however Dbeaver seem to get the java heap problem all the time, is there a way to avoid this?
