### ISSUE TITLE
Add column description field to metadata panel

### ISSUE THREAD

**Issue by DT2972** [dbeaver/dbeaver#11054]
![1611113113(1)](https://user-images.githubusercontent.com/30456949/105123017-4760d780-5b12-11eb-840f-50fc50020d47.png)

When there are many data fields, I don't know what a field is, so I want to add a description of the field in the metadata column.
It's like having a list of attributes in a table and a comment（describe） field in a column。

数据字段多的时候，不知道某个字段是什么，所以想在元数据栏里添加一个对字段的描述。
就像某个表里面有个属性列表，在列里有个注释字段。
@dansimpson @costin @rbellamy @zinking @jacekszymanski @

**Comment by uslss** [comment]
thanks for suggestion

**Comment by LonwoLonwo** [comment]
Implemented here: https://github.com/dbeaver/dbeaver/issues/18733
Available from the DBeaver version 23.1.3

**Comment by DT2972** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
