### ISSUE TITLE
Exporting SQL should have unicode prefix as "N" if DB is MS SQL

### ISSUE THREAD

**Issue by ichiro-uozu** [dbeaver/dbeaver#11058]
This is is related to the issue below.
https://github.com/dbeaver/dbeaver/issues/9664

I'm using MS SQL Server. Sometimes I have to use "import & export table data using SQL". These data has Japanese text, so its SQL should have unicode prefix. Because if it doesn't have "N", these data converted to "????".

- current exported SQL
INSERT INTO newtable (Column1,Column2,Column3) VALUES
	 ('1','山田','あああ'),
	 ('2','太郎','いいい'),

- Hope
INSERT INTO newtable (Column1,Column2,Column3) VALUES
	 ('1',N'山田',N'あああ'),
	 ('2',N'太郎',N'いいい'),

This condition is for MS SQL Server only. 

- Operating system (distribution) and version Windows10(2004)
- DBeaver version 7.3.3
- Database name and version Microsoft SQL Server ( Azure )
- Driver name Microsoft SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by uslss** [comment]
verified
