### ISSUE TITLE
A changed cell data disappears when you click on a different place in the table (focus issue)

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11065]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.4 EA

#### Steps to reproduce, if exist:
1. Open a table and change a cell value
2. Click a different place in the table

Expected: the change remains visible, the cell is in edit mode and colored in the appropriate color
Actual result: the change is reverted

https://user-images.githubusercontent.com/51405061/105186836-2795d780-5b43-11eb-950e-3a22fb038483.mp4

**Comment by serge-rider** [comment]
Side effect of #10561 fix. Reverted

**Comment by kseniiaguzeeva** [comment]
verified
