### ISSUE TITLE
Chose background color for editor tabs at Connection level

### ISSUE THREAD

**Issue by davideio87** [dbeaver/dbeaver#11066]
Hello
I'm using Version 7.2.0 and I would like to color my tab with different colors, in order to easily find which are for Dev and which are for Prod.

![d2](https://user-images.githubusercontent.com/64830100/105187645-50ae6c00-5b33-11eb-89a4-01e163cce9db.PNG)

I found the Connection type option, but it seems to work only in the connection list, the resultsets and so on, but not on the editor tabs
![d1](https://user-images.githubusercontent.com/64830100/105187772-73d91b80-5b33-11eb-91c2-9bb18c53cad3.PNG)

In the prefernces there is a Color section, but I can't find the option to set them in a different way to a specific connection.

![d3](https://user-images.githubusercontent.com/64830100/105187871-8f442680-5b33-11eb-95f9-e00934fcc746.PNG)

Is there any way to do it? If not by color, is there any other smart way to easily find the tab you are looking for, especially when you open 20 at the same time like I do? :smile: 

Thanks

**Comment by kseniiaguzeeva** [comment]
Add a connection type color to SQL Editor tabs sounds good. Thank you for the suggestion.

**Comment by kseniiaguzeeva** [comment]
Found that the ticket duplicates https://github.com/dbeaver/dbeaver/issues/8052. Let only one remains opened
