### ISSUE TITLE
Improve readibility of where block with multiple and nested and/or

### ISSUE THREAD

**Issue by pierrecorsini** [dbeaver/dbeaver#11063]
### Contexte

_Content before formatting:_
![image](https://user-images.githubusercontent.com/50719398/105171594-534e9880-5b16-11eb-82e9-59dd05227389.png)

_Content after formatting:_
![image](https://user-images.githubusercontent.com/50719398/105171655-69f4ef80-5b16-11eb-8b87-8028a5270b03.png)

As you can see in the images, formatting the querry has reduced it's readibility:
- `and ` and `or` have the same line break rules
- nested parenthesis are totally ignore in the formatting

### Describe the solution you'd like
I think the readibility would be better if nested parenthesis's elements are right indented +1, example:
![image](https://user-images.githubusercontent.com/50719398/105172998-5185d480-5b18-11eb-9470-53d9984781a7.png)

(The same indentation could be done between the `or` and `and` statement to visually identify the evaluation groups)

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by LonwoLonwo** [comment]
Implemented in DBeaver 21.0.2
DBeaver will add indents for OR, AND keywords, if they are first in brackets.

Example:
```
SELECT * FROM table_name
WHERE lname = ’Germy’
AND (fname = ’Ivan’ OR fname = ’Ron’ OR fname = ’Garry’ OR (1 = 1 AND 2 = 2));
```
Result will be:
![2021-04-01 11_51_40-DBeaver Enterprise 21 0 2 - _none_ Script-17](https://user-images.githubusercontent.com/45152336/113268973-a8f6ac80-92e0-11eb-93e1-bed5d197cfaa.png)

**Comment by pierrecorsini** [comment]
I love you guys, thanks.

**Comment by pierrecorsini** [comment]
@LonwoLonwo I tried to test it again on 21.0.2 but I do not get the same result as you do. Could you please give me the exact vesion where this is fixed ?
![image](https://user-images.githubusercontent.com/50719398/113281132-78fdd800-92e5-11eb-83ae-86cfb6417f60.png)

**Comment by LonwoLonwo** [comment]
Hello @pc-robelbois 
As you can see on your picture, the release with changes will be April 5th. 
Perhaps the changes will appear in early access https://dbeaver.io/files/ea/ (Focus on the date, it must be at least today)

**Comment by uslss** [comment]
verified
