### ISSUE TITLE
Sorting scripts by modification time while pressing F3

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#11073]
It would be very useful having option to sort by recent modification below window.
Thanks to that it  would be easier to find last script executed - especially with auto save mode = on

I dont think it is big deal to add sortable headers to below table

![image](https://user-images.githubusercontent.com/5410448/105248162-3944a280-5b76-11eb-9aeb-ed66a0e7902b.png)

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by flambchap** [comment]
Implemented.

**Comment by maciey** [comment]
> 
> 
> Implemented.

Cool. Thanks!

**Comment by kseniiaguzeeva** [comment]
verified
