### ISSUE TITLE
Request variable values before execution

### ISSUE THREAD

**Issue by spassignat** [dbeaver/dbeaver#11072]
When a task has defined variables, these variables has to be set in the task definition. It would be great, when launching a tasks with variables, to have a screen prompting to validate or change the values of these variables.

So when defining a variable, I would expect to have more parameter to a variable:
- readonly 
   - true: variable is set in the task definition
   - false: the variable is prompted in the screen before execution
- pattern: regex to validate the input. This can be improved with custom input field (date, number, ...) but that can also be a pain to convert later...
- help message: a brief description of the parameter to help the user to write the variable value

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by serge-rider** [comment]
WE also need to add possibility to define variables in CLI mode.
