### ISSUE TITLE
jvm argument  for each connection how to setting?

### ISSUE THREAD

**Issue by ccwxl** [dbeaver/dbeaver#11074]
Set a separate jvm parameter for each link. Different environments have different krb5.conf when using kerberos authentication, which needs to be specified with -Djava.security.krb5.conf

**Comment by kseniiaguzeeva** [comment]
Enterprise Edition http://dbeaver.com allows you to do it.
You have to open separate DBeaver instanses (with different workspaces) if you use Community Edition.
