### ISSUE TITLE
Display Sequences for MariaDB

### ISSUE THREAD

**Issue by Mosk915** [dbeaver/dbeaver#11081]
I believe this is similar to #2534 but for MariaDB databases.  Would it be possible to display sequences in the navigator pane? This is for the community edition of DBeaver.

**Comment by LonwoLonwo** [comment]
https://mariadb.com/kb/en/create-sequence/
https://mariadb.com/kb/en/sequence-overview/

**Comment by LonwoLonwo** [comment]
Implemented in DBeaver 7.3.5

**Comment by uslss** [comment]
verified
