### ISSUE TITLE
how can i correctly change result status of DBeaver?

### ISSUE THREAD

**Issue by qw12er34t** [dbeaver/dbeaver#11086]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Include any warning/errors/backtraces from the logs

![이미지 4](https://user-images.githubusercontent.com/77818269/105437557-a48c9280-5ca4-11eb-9ac1-c86ab4ea208f.png)

this is my result status of DBeaver
Why is error status in the lower right corner?
<br>
![이미지 5](https://user-images.githubusercontent.com/77818269/105437558-a5252900-5ca4-11eb-8ee1-2d6664d8381b.png)

this is what i want result status of DBeaver

i wanna change img 1 to img 2
how can i correctly show my result status?

i tried reset perspective but nothing changed

my DBeaver version is 7.3.2
please answer it
thanx

**Comment by kseniiaguzeeva** [comment]
Please write steps to reproduce how have you received it and send logs https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it
