### ISSUE TITLE
Merge Result Sets option

### ISSUE THREAD

**Issue by wattpuppy** [dbeaver/dbeaver#11082]
I often run 100+ queries where I need the consolidated output in a single text tab.  Having to switch to each tab and correlate the data manually requires a lot of wasted time.  DBVisualizer has a feature, which I'd like to see in DBeaver, called "Merge Result Sets".  It takes the output from each result set tab and copies it to a single text output window.  

The "perfect world" solution would be to have an additional output section for "All SQL statement output" instead of an individual tab per result set.  But the "Merge Result Sets" option could be an easier workaround.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by serge-rider** [comment]
I think it is very similar to #667 . Please correct me if I'm wrong.
