### ISSUE TITLE
`Duplicate current row` functionality with multiple non-adjacent rows duplicates the wrong rows

### ISSUE THREAD

**Issue by Woodz** [dbeaver/dbeaver#11087]
#### System information: 
- Operating system (distribution) and version: macOS v11.1 Intel
- DBeaver version: 7.2.2
- Additional extensions: None

#### Connection specification:
- Database name and version: PostGres 11.06.0000
- Driver name: PostgreSQL JDBC standard driver (42.2.5)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH tunnel

#### Describe the problem you're observing:

Duplicating multiple rows that are not adjacent to each other results in the wrong rows being duplicated

#### Steps to reproduce, if exist:

1. Create a sample table with 200 rows with a unique numeric ID column
2. Randomly select at least 3 rows that are not adjacent in the viewer, including one row at least row 10 or later
3. Click the "Duplicate current row" button

E.g. I select rows 1, 7 and 16. It actually duplicated rows 1, 4 and 16.

I have noticed that it inserts the duplicated rows at the row index that is one more than the number of rows selected (i.e. if you select 10 rows, it will insert the duplicated rows from row 11 onwards). I suspect that the bug is because it inserts the duplicate rows between row 3 and 4, thereby making the new row 7 the old row 4. Therefore I think that the bug is because blank rows are being inserted and then the data copied from the (now incorrect) old indexes. If that is the case, the fix may be either to read the data to be duplicated before inserting blank rows or adjusting the indexes selected after data has been inserted. I would also recommend changing the position of duplicated rows to always be above the existing rows rather than underneath the rows selected, which will make duplication behaviour more obvious as well as simplifying this bug fix.

This behaviour is 100% repeatable, so does not appear to be random or a race condition

#### Include any warning/errors/backtraces from the logs

No errors are shown in the logs

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by ShadelessFox** [comment]
Fixed. Now we group continuous rows into partitions, so we can process them individually.

Note for testers: make sure that duplication, insertion and copying (before and after current row) works fine in different databases, such as MongoDB, CouchDB, Cassandra and with complex data types in PostgreSQL.

https://user-images.githubusercontent.com/35821147/114702276-8b880080-9d2c-11eb-915a-0882b15dda8b.mp4

**Comment by kseniiaguzeeva** [comment]
verified (mentioned databases were tested)

**Comment by kseniiaguzeeva** [comment]
New row cannot be inserted to an empty table.

**Comment by ShadelessFox** [comment]
Whoops. Fixed:

https://user-images.githubusercontent.com/35821147/114892864-d0d42d00-9e15-11eb-933f-566e0f687b0e.mp4

**Comment by kseniiaguzeeva** [comment]
verified
