### ISSUE TITLE
Huge memory consumption on MacOS in some conditions

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#11089]
In some cases DBeaver starts to consume tons of memory in idle mode.
Possibly because of halted (broken) remote connections which produce series of deadlocks in UI.

Perhaps it started after migrating to the new Eclipse platform.

**Comment by serge-rider** [comment]
We need some steps to reproduce.
It happens rarely after dbeaver is working for a long-time (days)

**Comment by uslss** [comment]
fixed in the scope of #11368
