### ISSUE TITLE
 No Keys are shown on Amazon ElastiCache Redis

### ISSUE THREAD

**Issue by davizucon** [dbeaver/dbeaver#11097]
#### System information: 
- Operating system (MacOS) 10.15.6 (Catalina)
- DBeaver version 7.3.0

#### Connection specification:
- Redis [4.0.10 (Cluster , SSL) Amazon ElastiCache]
- Driver Redis/DBeaver default (Jedis)
- Do you use tunnels or proxies (SSH, SO (CKS, etc) ? No, direct connection. 

#### Describe the problem you're observing:
-  Connection looks fine. When testing connection, Server information show "Redis null". In Connection->Databases->cluster-> "Key list" are empty
- Tried without cluster and SSL ->skip host name validation , no luck.

#### Steps to reproduce, if exist:
- Create new connection using Redis Driver
- Set Host, (point to aws cluster URL), port, password
- SSL check option ,Use SSL 
- Test Connection

#### Include any warning/errors/backtraces from the logs

Additional information:
- RDM works fine.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by Broctune** [comment]
Still an issue with DBeaver Enterprise v21.2.0....

**Comment by huineng** [comment]
i had the same thing (Server information show "Redis null")  
I was using  (ibm cloud) but might be the same

I disabled cluster and checked "Use SSL" , i just provided my CA Certifcate and could connect

**Comment by kyleflan** [comment]
Seeing similar behavior with Amazon MemoryDB on latest DBeaver EE (21.3.0.202112052011). Connection is fine when "Cluster" mode is checked, but **Key list** and **Key hierarchy** are empty and trying to execute e.g. `GET <key>` returns

> Custom Redis commands not supported in cluster mode

**Comment by serge-rider** [comment]
https://github.com/dbeaver/dbeaver-ee/pull/1635

**Comment by IllusionaryX** [comment]
I am having theses same issues in DBeaver v22.1, only difference I see is that I get the error "No reachable node in cluster" vs the "Custom Redis commands not supported in cluster mode" when executing GET <key>. Connection shows as fine, but same issues as listed above:

**Describe the problem you're observing:**
- Connection looks fine. When testing connection, Server information show "Redis null". In Connection->Databases->cluster-> "Key list" are empty
- Tried without cluster and SSL ->skip host name validation , no luck.

I am using Laravel Homestead (Redis v6.0.6) as test platform with forwarded port, as I said connection is not a problem, at least no error thrown.

**Comment by Destrolaric** [comment]
@IllusionaryX Hi, it looks like a different issue. Is it possible to create a new issue with the mentioned information?

**Comment by IllusionaryX** [comment]
I had just updated to v22.1 when I got the error. After a system restart that error left the building with no other changes. So no issue. Thanks for the quick response.
