### ISSUE TITLE
On Linux Mint system, it is allowed to create columns with no response and stuck sometimes

### ISSUE THREAD

**Issue by bouyeijiang** [dbeaver/dbeaver#11098]
When creating column or join query in MySQL database

**Comment by kseniiaguzeeva** [comment]
Please try to use Auto-commit https://github.com/dbeaver/dbeaver/wiki/Auto-and-Manual-Commit-Modes.  If it doesn't help, write steps to reproduce.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it
