### ISSUE TITLE
MySQL/MariaDB: permissions WITH GRANT OPTION

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#11090]
We need to add a possibility to grant permissions with grant option.
Perhaps some addition checkbox and/or extra column in permission list.

**Comment by mkgrgis** [comment]
The same statement WITH GRANT OPTION is actual for PostgreSQL and Oracle.

**Comment by LonwoLonwo** [comment]
- Privileges table reorganized
- A new checkbox button "With GRANT option" added
- Privileges refresh improved

![2022-01-24 21_30_39-DBeaver Ultimate 21 3 3 - Вася Пупкин@%](https://user-images.githubusercontent.com/45152336/151070715-b89ee821-2be3-4cad-a838-98ca5d5d0317.png)

![2022-01-25 16_30_10-Event](https://user-images.githubusercontent.com/45152336/151070719-799ee48d-834c-4b8f-8eb6-7f73d25eb74c.png)

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
- "with grant option" extra column removed from the privileges table
- all logic moved to the "**grant option**" privilege button; 
- "other privileges" table is disabled now in some cases

![6OL4abo2Fz](https://user-images.githubusercontent.com/45152336/151882310-9e0a9d1a-86e3-4fec-84df-0e0e7e9c9010.gif)

![tx4W9stkFz](https://user-images.githubusercontent.com/45152336/151882327-2f79ca28-edaf-4a1f-b3ce-d506e2f1c9f8.gif)

**Comment by uslss** [comment]
verified
