### ISSUE TITLE
Excel export. You can make a setting to choose whether to trim to 32767 characters or not. 

### ISSUE THREAD

**Issue by igortank** [dbeaver/dbeaver#11106]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by igortank** [comment]
You can wrap characters in the cell below.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. The feature will be added.

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
Now default behavior for Excel import is to trim cells with a content of more than 32767 characters. Message about trimmed cells can be founded in DBeaver logs. Implemented in DBeaver 21.2.3

> You can wrap characters in the cell below.

You can create a new ticket as a feature request for this.
