### ISSUE TITLE
Formatting breaks query with hexadecimal constant values

### ISSUE THREAD

**Issue by tomershay** [dbeaver/dbeaver#11104]
#### System information: 
- Operating system (distribution) and version: MacOS Big Sur 11.1
- DBeaver version: 7.3.1.202012201616

#### Connection specification:
- Database name and version: MySQL 8.0.21
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When formatting a query with hexadecimal values, the formatting adds a space that breaks the query.

#### Steps to reproduce, if exist:
1. Write the following query in the editor: `SELECT 0x00 FROM tbl;`
2. Right click the query, select Format => Format SQL
3. The query now can't be executed, as a space was added after the character '0'.

The new query after formatting is:
```
SELECT
	0 x00
FROM
	tbl;
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by ShadelessFox** [comment]
Testers, please make sure that numeric literals like listed below still highlighted and formatted correctly:
```sql
-- Hexadecimal numeric literal
SELECT 0xDeadBeef;
-- Decimal numeric literal with signed scientific notation
SELECT 0.5e+17;
-- Decimal numeric literal
SELECT 123.456;
-- Integral numeric literal
SELECT 456;
```

**Comment by uslss** [comment]
verified
