### ISSUE TITLE
Leaflet Map "Streets" Base Layer Not Working

### ISSUE THREAD

**Issue by dhjacobson** [dbeaver/dbeaver#11109]
#### Specifications:
- Windows 10
- Dbeaver 7.3.3
- PostgreSQL 12.3 with PostGIS

#### Describe the problem you're observing:
The base layer is not showing up in the leaflet map that appears when I select a geometry or geography in a query output. A few notable details:
- SRID is 4326
- If I switch to the "Topography" base layer, it works fine. The issue is just with the "Streets" base layer
- The issue is new. Using the exact same tables, unaltered, this problem did not exist a few weeks ago. I experienced the issue on both 7.3.2 and 7.3.3. I'm not sure if the issue was present before 7.3.2.

![image](https://user-images.githubusercontent.com/8836999/105749223-ba9a8d00-5f08-11eb-93f7-b114d5a1eed1.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
Something is wrong with Mapbox tiles.
We probably should change default tiles to OSM.

**Comment by uslss** [comment]
verified
