### ISSUE TITLE
CouchDB - Error when trying to save a document

### ISSUE THREAD

**Issue by rdewolff** [dbeaver/dbeaver#11103]
#### System information: 
- Operating system (distribution) and version: macOS Cataline
- DBeaver version 7.3.0.202012061950
- Additional extensions: n/a

#### Connection specification:
- Database name and version: CouchDB 2.2
- Driver name: CouchDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:

When editing a field and hitting the save button, I get an error. Tried multiple collections. None works.

I get the following error message:

```
Error synchronizing data with database

Reason:
Error saving document

--
Error saving document
  Unsupported document value: [lastName; 3]
```

![Screenshot 2021-01-23 at 07 05 27](https://user-images.githubusercontent.com/130704/105570381-609f9900-5d49-11eb-9688-66f565d05485.png)

#### Steps to reproduce, if exist:
1. Connect to a CouchDB server
2. Edit a field
3. Save

#### Include any warning/errors/backtraces from the logs
n/a

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
Both new documents and existing documents editor were fixed.
Additionally complex structured attributes editor was added

**Comment by rdewolff** [comment]
Thanks @serge-rider for the update. Was this released in a new version already?

**Comment by uslss** [comment]
@rdewolff fix is available in EA version for now - https://dbeaver.com/files/ea/enterprise/
The new release will be available on March, 7

**Comment by uslss** [comment]
verifed

**Comment by rdewolff** [comment]
Thanks for the heads up
