### ISSUE TITLE
execute stored procedure -- when click REF CURSOR then shift+enter not work in 7.3 version

### ISSUE THREAD

**Issue by yongchulli** [dbeaver/dbeaver#11105]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by kseniiaguzeeva** [comment]
Please tell me your database and an example to reproduce.

**Comment by uslss** [comment]
There is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it.
