### ISSUE TITLE
GIS data is displayed without Z and M values

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11116]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 7.3.4 EA

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
GIS values are cut to show 2D data only.

#### Steps to reproduce, if exist:
Add to Geometry column:

- LINESTRING M (1 1 0, 1 2 0, 1 3 1, 2 2 0)
- POLYGON Z ((0 0 0, 0 1 0, 1 1 0, 1 0 0, 0 0 0))
- POINT Z (-8.6964351 40.3307427 1)
- POINT ZM (1 2 3 4)

Expected:
the values are displayed completely in cells, Value panel, during data transfer.

Actual result:
the values are cut:
- LINESTRING (1 1, 1 2, 1 3, 2 2)
- POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))
- POINT (-8.6964351 40.3307427)
- POINT (1 2)

**Comment by ShadelessFox** [comment]
By some reason, the geometry data like:
```
LINESTRING M (1 1 0, 1 2 0, 1 3 1, 2 2 0)
``` 
is rendered as 
```
LINESTRING (1 1, 1 2, 1 3, 2 2)
```
without zeroes. This may confuse user.

Also `POINT` lacks 3rd dimension if specified.

**Comment by ShadelessFox** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/35821147/113787497-ce9e0e80-9743-11eb-97d1-b08669cb4bfa.png)

**Comment by kseniiaguzeeva** [comment]
verified
