### ISSUE TITLE
Stuck in loop loading user/table cache

### ISSUE THREAD

**Issue by dariodjuric** [dbeaver/dbeaver#11114]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro 19042.746
- DBeaver version: 7.3.3
- Additional extensions: None

#### Connection specification:
- Database name and version: Oracle 11.2.0.4.0
- Driver name: ojdbc8-12.2.0.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

When connecting to one particular Oracle database, DBeaver is stuck in an infinite loop, being unable to make any queries. See below:

![dbeaver-problem](https://user-images.githubusercontent.com/5459296/105821956-ba0efe80-5fbb-11eb-817e-cc57af38dd11.gif)

#### Steps to reproduce, if exist:

This issue happens only on one Oracle database. The issue does not happen on any other Oracle database, so it's probably difficult for you to reproduce. Perhaps you'll see something useful in the logs. Otherwise let me know if I can do anything else to help you.

#### Include any warning/errors/backtraces from the logs

```
> Start DBeaver PostgreSQL Support UI [org.jkiss.dbeaver.ext.postgresql.ui 1.0.25.202101161839]
2021-01-26 09:37:54.553 - Connect with 'PI' (oracle_thin-176fb632a9d-6facb6165ce44655)
2021-01-26 09:37:54.554 - Execution context opened (PI; Main; 3)
2021-01-26 09:37:56.641 - Execution context opened (API; Metadata; 4)
2021-01-26 09:37:57.808 - Connected (oracle_thin-176fb632a9d-6facb6165ce44655, Oracle JDBC driver [12.2.0.1.0])
2021-01-26 09:38:21.290 - Execution context opened (PI; SQLEditor <Script-4.sql>; 5)
> Start GEF (MVC) [org.eclipse.gef 3.11.0.201606061308]
> Start Draw2d [org.eclipse.draw2d 3.10.100.201606061308]
2021-01-26 09:38:31.756 - Can't get column 'EXTERNAL_NAME': Invalid column name
2021-01-26 09:38:31.756 - Can't get column 'ACCOUNT_STATUS': Invalid column name
2021-01-26 09:38:31.756 - Can't get column 'LOCK_DATE': Invalid column name
2021-01-26 09:38:31.756 - Can't get column 'EXPIRY_DATE': Invalid column name
```

**Comment by kseniiaguzeeva** [comment]
Please try to disable **Show statistics info** and **Show system objects** (select **Connection view** in Oracle context menu in DB Navigator)
![Screenshot 2021-01-26 at 12 27 43](https://user-images.githubusercontent.com/51405061/105826764-27c62500-5fd2-11eb-8881-4c5908ffce1c.png)

**Comment by dariodjuric** [comment]
Hi, thanks, but sadly this doesn't help. It's still gets stuck on the same screen.

**Comment by kseniiaguzeeva** [comment]
1. Please open Query manager to see what query gives this issue (Window>Show view>Query manager). Please send the query to me.
2. Oracle has its own specific settings (Edit Connection>Oracle Properties). Could you try them?
![dbeaver_ndlF3h4iCT](https://user-images.githubusercontent.com/51405061/106002516-4b689880-60c2-11eb-99dc-15ef591c22de.png)

**Comment by dariodjuric** [comment]
Ok, I enabled the Query Manager, but it doesn't show any queries:

![dbeaver-problem](https://user-images.githubusercontent.com/5459296/106032787-35ae9f80-60d1-11eb-89eb-85bc5144c76f.gif)

In fact, the only activity can be shown in this window:

![dbeaver-problem2](https://user-images.githubusercontent.com/5459296/106032828-419a6180-60d1-11eb-8888-597713a0dfe8.gif)

I also tried enabling all of the Oracle-specific options, but it did not help.

Is there anything else I can do?

**Comment by kseniiaguzeeva** [comment]
Please set to show all query types in Query manager and try again.
![dbeaver_eOGBJYuapd](https://user-images.githubusercontent.com/51405061/106123000-6db5f100-616a-11eb-97f8-84d168de8aa3.png)

**Comment by dariodjuric** [comment]
Thanks for the tip. Here is the result:

![dbeaver-problem](https://user-images.githubusercontent.com/5459296/106127878-34c44f00-615f-11eb-9319-edf02cccf300.gif)

The full query is:

```sql
SELECT t.OWNER, t.TABLE_NAME AS OBJECT_NAME, 'TABLE' AS OBJECT_TYPE, 'VALID' AS STATUS,t.TABLE_TYPE_OWNER,t.TABLE_TYPE, t.TABLESPACE_NAME,
t.PARTITIONED, t.IOT_TYPE, t.IOT_NAME, t.TEMPORARY, t.SECONDARY, t.NESTED, t.NUM_ROWS
FROM SYS.ALL_ALL_TABLES t
WHERE t.OWNER ='PI'
AND NESTED = 'NO'
UNION ALL SELECT o.OWNER, o.OBJECT_NAME, 'VIEW' AS OBJECT_TYPE, o.STATUS, NULL, NULL, NULL, 'NO', NULL, NULL, o.TEMPORARY, o.SECONDARY, 'NO', 0
FROM SYS.ALL_OBJECTS o
WHERE o.OWNER ='PI'
AND o.OBJECT_TYPE = 'VIEW'
UNION ALL SELECT o.OWNER, o.OBJECT_NAME, 'MATERIALIZED VIEW' AS OBJECT_TYPE, o.STATUS, NULL, NULL, NULL, 'NO', NULL, NULL, o.TEMPORARY, o.SECONDARY, 'NO', 0
FROM SYS.ALL_OBJECTS o
WHERE o.OWNER ='PI'
AND o.OBJECT_TYPE = 'MATERIALIZED VIEW'
```

When I execute the above query using another SQL client, it gives around 800 results, most of which are partitions of one table. Could this causing problems?

**Comment by kseniiaguzeeva** [comment]
_DBeaver command: It is a table with partitions HR.Q1_SALES_BY_REGION. The issue still cannot be reproduced._

**Comment by uslss** [comment]
@dariodjuric could you try to update to recent version? If issue is still reproducible, please, provide [thread dump](https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump)

**Comment by dariodjuric** [comment]
Hi @uslss, it appears I cannot reproduce it anymore. Perhaps it was fixed in a newer release. I think we can close the issue.
