### ISSUE TITLE
An exception occurred in Advanced Paste 

### ISSUE THREAD

**Issue by qiqingli** [dbeaver/dbeaver#11113]
#### System information: 
- Operating system (distribution) and version：MacOS Big Sur 11.1
- DBeaver version: DBeaver 7.3.3

#### Steps to reproduce, if exist:
1. There is an Excel with the following data
![image](https://user-images.githubusercontent.com/20805098/105816313-1c352700-5fef-11eb-8a47-3401fadcbeb5.png)

2. An exception occurred when using advanced paste data to the table 
![image](https://user-images.githubusercontent.com/20805098/105815930-92855980-5fee-11eb-8fb0-066c45a8215b.png)
![image](https://user-images.githubusercontent.com/20805098/105815973-a4ff9300-5fee-11eb-94b1-ee5ef5e6ab79.png)
![image](https://user-images.githubusercontent.com/20805098/105816013-b183eb80-5fee-11eb-941c-81687b3bbdf2.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by elring** [comment]
Hi. Same issue here. 
Pasting new data (with creating new records) worked in DBeaver 7.3.2. Now I got same error (db PostgreSQL, OS Ubuntu 20.04, DBeaver 7.3.3 & 7.3.4).

**Comment by serge-rider** [comment]
Probably will be fixed in #11171

**Comment by kseniiaguzeeva** [comment]
verified
