### ISSUE TITLE
Output Tab reopens  on next execution

### ISSUE THREAD

**Issue by PeterAlva** [dbeaver/dbeaver#11120]
#### System information: 
OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	WIN-UFEK63BASEQ
System Manufacturer	HP
System Model	HP 255 G7 Notebook PC
System Type	x64-based PC
System SKU	1B7K2ES#ABU
Processor	AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx, 2100 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Insyde F.31, 01/07/2020
SMBIOS Version	3.1
Embedded Controller Version	51.24
BIOS Mode	UEFI
BaseBoard Manufacturer	HP
BaseBoard Product	85EA
BaseBoard Version	51.24
Platform Role	Mobile
Secure Boot State	Off
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United Kingdom
Hardware Abstraction Layer	Version = "10.0.19041.488"
Username	WIN-UFEK63BASEQ\PeterLibman
Time Zone	GMT Standard Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	29.9 GB
Available Physical Memory	22.7 GB
Total Virtual Memory	34.7 GB
Available Virtual Memory	25.8 GB
Page File Space	4.75 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualisation-based security	Not enabled
Device Encryption Support	Reasons for failed automatic device encryption: PCR7 binding is not supported, Hardware Security Test Interface failed and the device is not Modern Standby, Un-allowed DMA-capable bus/device(s) detected
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualisation Enabled in Firmware	No
Hyper-V - Data Execution Protection	Yes

- DBeaver version
-7.3.3.202101161839
- Additional extensions
- none

#### Connection specification:
- Postgres 12
- Driver name
- PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no
#### Describe the problem you're observing:
clicked on the Output button on the left hand side of an SQL Editor window. The Output tab appeared to the right of the SQL Editor window (This is new behaviour as it used to be a tab below the SQL which was preferable and I cannot find a way of moving it back there). 
Execute a query and output is correctly displayed in the Output window.
Clicked on the 'x' on the output window and the window closed.
Reran the query and the output window reappears without being requested.
Clear the contents of the output window and clicked 'x' to close the window.
The Output window closed.
Reran the query, and the output window magically reappears.
Click on the Output button on the left of the sql window and the output window closes.
Reran the query, and the output window magically reappears. 

Kind regards

Pete

**Comment by ShadelessFox** [comment]
Hello @PeterAlva, 

This is a feature and it is enabled by default (because a lot of users don't even know that some servers may send messages). 

You can change this behavior in `Preferences` -> `SQL Editor` -> `Open output viewer on new messages`.

**Comment by PeterAlva** [comment]
Thanks for a very speedy response.
