### ISSUE TITLE
Choco installer doesn’t work in non-interactive session

### ISSUE THREAD

**Issue by dkattan** [dbeaver/dbeaver#11123]
The NSIS exe doesn’t appear to support /AllUsers as is convention for NSIS.

When using standard deployment tools like SCCM that run as SYSTEM, the shortcuts are placed in SYSTEM’s user profile buried deep inside C:\Windows

To correct this, use the following guide:

https://nsis.sourceforge.io/Docs/MultiUser/Readme.html

**Comment by kseniiaguzeeva** [comment]
Looks like a bug. WHat's wrong with /AllUsers path? Is it possible to give more details?

**Comment by dkattan** [comment]
This is no longer an issue. It appears to have been fixed.
