### ISSUE TITLE
Variable include a variable in a srcipt

### ISSUE THREAD

**Issue by ddperso** [dbeaver/dbeaver#11125]
HI

I write:

@set cr = 'DUBOIS'
@set dd = :cr
select * from Notes where Note = :dd;

The result is:
select * from Notes where Note = :cr

I would like to have select * from Notes where Note = 'DUBOIS'

Where is my mistake?

Thanks

**Comment by ShadelessFox** [comment]
Hello @ddperso,

You can use `${variable}` to access other variables from a variable:
```
@set cr = 'DUBOIS'
@set dd = ${cr}
SELECT :dd;
```
Also make sure you've executed each `@set` separately or entire script block using `Alt+X`.
