### ISSUE TITLE
VARCHAR string in generated ALTER statement missing length

### ISSUE THREAD

**Issue by rotorboy** [dbeaver/dbeaver#11132]
#### System information: 
- Operating system (distribution) and version - MacOS 10.14 Mojave
- DBeaver version - 7.3.3.202101161839

#### Connection specification:
- Database name and version - MariaDB 10.3
- Driver name - Default
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:

When converting a field from one type to VARCHAR, the generated ALTER statement does not specify the required length parameter for VARCHAR e.g. VARCHAR(50):

ALTER TABLE `Foo` MODIFY COLUMN boo VARCHAR NOT NULL;

While the string in the dropdown is editable to add the length eg (50), without it being there as a placeholder hint, most will not realize the error when they try to save the change.

#### Steps to reproduce, if exist:

Go into table editor, change a non-VARCHAR field to VARCHAR, click "save", and see the statement that is generated

**Comment by LonwoLonwo** [comment]
Will be fixed in scope with https://github.com/dbeaver/dbeaver/issues/11309
