### ISSUE TITLE
Problem with DDL for spatial 3D data - Postgresql/PostGIS

### ISSUE THREAD

**Issue by rmarzocchi84** [dbeaver/dbeaver#11144]
#### System information: 
- Windows 10
- DBeaver version 7.3.3.

#### Connection specification:
- Postgresql with spatial extension PostGIS 

#### Describe the problem you're observing:

I have a table with a LINESTRINGZ geometry. 

CREATE TABLE public.elementi_stradali (
	id serial NOT NULL,
	geom geometry(LINESTRINGZ, 32632) NULL,
	da_nodo int4 NULL,
	a_nodo int4 NULL,
	data_ins timestamp NULL DEFAULT now()::timestamp(0) without time zone,
	lunghezza_m float8 NULL,
	d_composizione_elemento_stradale varchar(255) NULL,
	d_direzione_di_marcia_consentita varchar(255) NULL,
	d_tipo_elem varchar(255) NULL,
	prog_ini float8 NULL,
	prog_fin float8 NULL,
	cod_strada varchar(255) NULL,
	note_cessione varchar NULL,
	data_cessione date NULL,
	data_agg timestamp NULL DEFAULT now()::timestamp(0) without time zone,
	data_elimi timestamp NULL,
	login varchar NULL,
	note varchar NULL,
	prog_ini_reale numeric NULL,
	prog_fin_reale numeric NULL,
	flag_raccordo bool NULL,
	flag_rotonda bool NULL,
	cod_librone varchar NULL,
	CONSTRAINT elementi_stradali_pkey PRIMARY KEY (id)
);

When I create the DDL the geometry is not correctly exported (I see LINESTRING and not LINESTRINGZ

![image](https://user-images.githubusercontent.com/4061154/106198707-ac709900-61b4-11eb-9915-a3966ae0a59f.png)

**Comment by ShadelessFox** [comment]
Fixed.

![KZy78SWgWu](https://user-images.githubusercontent.com/35821147/113583938-ef2a7380-9632-11eb-8173-08e6531c971a.png)

**Comment by kseniiaguzeeva** [comment]
verified
