### ISSUE TITLE
Grouping panel works incorrectly

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11159]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.4 EA

#### Connection specification:
- Database name and version MySQL, PostgreSQL

#### Describe the problem you're observing:
PostgreSQL and MySQL do not display all column values when dnd it to the Grouping panel

#### Steps to reproduce, if exist:
Open table (e.g. language) and dnd any column to Grouping panel

Expected: all values are displayed
Actual result: no values are displayed
#### Include any warning/errors/backtraces from the logs
Query manager writes:
```
SELECT name, COUNT(*) FROM (
SELECT * FROM sakila.`language`) src
GROUP BY name
HAVING COUNT(*) > 1
LIMIT 0, 100
```

https://user-images.githubusercontent.com/51405061/106267253-71b14400-623a-11eb-8a25-008fea71257a.mp4

**Comment by serge-rider** [comment]
It is not a bug. You enabled option "Show duplicates only" which hides all results with count<2.
