### ISSUE TITLE
Wrong session info in Oracle.

### ISSUE THREAD

**Issue by a123z** [dbeaver/dbeaver#11154]
Hi!
When I open sessions window(with inactive sessions) - I see sessions list.
If click to session, one by one, must be change information about selected session (sql, plan etc.)
But show no sql and wrong plan - 
```
SELECT PLAN_TABLE_OUTPUT FROM TABLE(dbms_xplan.display_cursor(sql_id => :1 , cursor_child_no => :2 )).
```

Info about each session must be get in other session(which get sessions list or other). It seems to me that its exec in selected session.
May be I do something wrong.
Thanks.

#### System information: 
- OS Win10 
- dbeaver 7.3.3.202101161839
- oracle 19.3c (oracle.jdbc.OracleDriver)

**Comment by LonwoLonwo** [comment]
Hello @a123z 
Can you tell me more please about your issue?

Not sure I can reproduce it.
![lWPUe9O00j](https://user-images.githubusercontent.com/45152336/118680082-1c0fa000-b807-11eb-8881-a541b682f039.gif)

And what plan is correct?

**Comment by uslss** [comment]
there is no update on issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
