### ISSUE TITLE
Geometry values are displayed incorrectly if they are converted from binary type

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11153]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version  7.3.4 

#### Connection specification:
- Database name and version Presto

#### Describe the problem you're observing:
1. Only simple geometry values are displayed on the map (like `POINT (0 0)`. But you cannot see on the map values like `POINT (0 76846599344977030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)`  
2. Geometry values have extra zeros, if they consist of several digits
3. Different binary values can become identical after converting them to geometry format

#### Steps to reproduce, if exist:
Please see column **location** in table **address** to reproduce.
#### Include any warning/errors/backtraces from the logs

https://user-images.githubusercontent.com/51405061/106242449-c0e67d00-6218-11eb-937d-bb5fe51c0d20.mp4

**Comment by ShadelessFox** [comment]
This problem is only related to MySQL because it has specific binary geometry format.

Probably we should allow user to configure geometry transformer to use this specific format.

**Comment by ShadelessFox** [comment]
Implemented:
![java_jywDSVuvOA](https://user-images.githubusercontent.com/35821147/113695169-3e2ae400-96d9-11eb-8a65-f8e0dcbdc322.png)

**Comment by kseniiaguzeeva** [comment]
verified
