### ISSUE TITLE
Function Localization

### ISSUE THREAD

**Issue by RoeGross** [dbeaver/dbeaver#11151]
The existing function is not completely Chinese

**Comment by LonwoLonwo** [comment]
Hello @L-GROSS 

We do not have a native speaker on our team, however, you can help us with translation:
https://github.com/dbeaver/dbeaver/wiki/Localization

Or you can specify here in this ticket functions with translation, and we will add it to the project.

**Comment by E1izabeth** [comment]
I suppose it's much better now (thanks to DBeaver community), so we can close this issue.
