### ISSUE TITLE
Keywords are highlighted as hyperlinks in sql editor

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#11158]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 7.3.4

#### Connection specification:
- Database name and version oracle
#### Describe the problem you're observing:
Keywords are highlighted as hyperlinks in sql editor
#### Steps to reproduce, if exist:
1. Write some query like `SELECT * FROM Table`
2. Hover cursor on some keyword and press Ctrl - Keyword is highlighted as a hyperlink, table mentioned in query is opened on click
![2021-01-29_13h44_50](https://user-images.githubusercontent.com/31996417/106266179-2d717400-6239-11eb-9e2c-f5bce15cf7c1.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
