### ISSUE TITLE
Navigator tree contains too much objects in some dialogs

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#11167]
DBeaver 7.3.3

In Schema Compare Wizard Navigator tree contains too much objects, not all of them are suitable for comparison, and should not be mentioned in the list of objects at all.

![2021-01-29 17_19_52-Schema Compare](https://user-images.githubusercontent.com/45152336/106286437-b5b24200-6256-11eb-9eef-de8e78a6d670.png)

**Comment by kseniiaguzeeva** [comment]
The new tree view is:
![Screenshot 2021-02-02 at 13 59 55](https://user-images.githubusercontent.com/51405061/106591139-f49a0d80-655e-11eb-8e3e-1302d03e9bf9.png)
