### ISSUE TITLE
DBeaver: Disable Auto SQL Assistant/Completion for table aliases (part 2)

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#11165]
DBeaver - Version **7.3.2 CE**
DBeaver driver: **MS SQL Server** / **Microsoft Driver** (the new Microsoft Driver)
Operating System: **Windows 7** / **Windows 8.1** / **Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

**THIS IS A COPY OF ISSUE #10405**. But since I reported and answer on the issue too late (noticed your question first today) and now the issue is closed, I write another issue/copy.

The automatic **SQL Assistant/Completion** annoyingly suggest table names for table aliases, this should not be done.

**1**) Start to write "**SELECT * FROM MyTable MT**"
**2**) If you now stop typing (with our DBeaver configuration there is a 500ms delay),
    the automatic **SQL Assistant** pops up and suggest table names that start with "MT".

The automatic **SQL Assistant** should not suggest database tables when I start to write table aliases.

**PS**. This is a copy of the feature request issue #7847 that was supposed to have been fixed in version 7.0.1, but was not.

**PPS**. The misbehaviour is still there in version 7.2.5 (and still active in 7.3.2).

**EXTRA EXPLANATION (29th Jan 2021)**

The faulty behaviour seems not to be there any more when I do a simple SELECT. **BUT**... It shows up when you do a JOIN...

SELECT *
  FROM MyTable1 MT1
  JOIN MyTable2 M

**1**) Stop typing after "My" for the second table and auto assistant kick in. (**OK**)
**2**) Stop typing after "M" for the alias for the **MyTable2** the auto assistant kicks in. (**ERR**)

Seems the code that decide if I should get auto assistant or not has logic that does not cover more than a simple SELECT * FROM...

**PS**. Hope the fix for this can fit into *DBeaver CE 7.3.4*.

**Comment by LonwoLonwo** [comment]
Ok, I understand the case that you point out. It is a little more difficult and we can no longer do it in this sprint. I put it in one future sprint.

**Comment by LonwoLonwo** [comment]
Fixed in 21.0.2
Will be available [here](https://dbeaver.io/) at 2020-04-05

**Comment by uslss** [comment]
verified
