### ISSUE TITLE
Generated DDL is empty for Oracle data types

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#11161]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.3.4

#### Connection specification:
- Database name and version Oracle 12c

#### Steps to reproduce, if exist:
1. Open Global Metadata - Types
2. Choose any type then choose Generate DDL in its context menu - popup with generated DDL is empty

![image](https://user-images.githubusercontent.com/31996417/106271037-efc41980-623f-11eb-8faf-7c8cd65460a8.png)

**Comment by LonwoLonwo** [comment]
Fixed
![116369429-09123d00-a812-11eb-93d9-e838b4f2fb40](https://user-images.githubusercontent.com/45152336/116509667-5fdc4d00-a8cc-11eb-90d1-663458be09af.png)

**Comment by uslss** [comment]
verified
