### ISSUE TITLE
Compile type isn't working in Global metadata - Types

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#11160]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.3.4

#### Connection specification:
- Database name and version Oracle 12c

#### Describe the problem you're observing:
Compile type option triggers an error
#### Steps to reproduce, if exist:
1. Connect to oracle
2. Open Global metadata - Types
3. Choose some type - Choose Compile Type option in its context menu - Error appears
![image](https://user-images.githubusercontent.com/31996417/106270468-1b92cf80-623f-11eb-8cc3-d79833813205.png)

**Comment by LonwoLonwo** [comment]
Fixed. Button is still here, but error is more clear

**Comment by uslss** [comment]
verified
