### ISSUE TITLE
Creation date / modification date of tables, views and packages

### ISSUE THREAD

**Issue by Kaennchen80** [dbeaver/dbeaver#11179]
Hallo,
can I see the creation / modification date of tables, views and packages somewhere? Best directly with the properties of the table or package, ... . Unfortunately, I haven't found it anywhere. 
Best regards.

**Comment by ShadelessFox** [comment]
Hello @Kaennchen80,

What database are you talking about? Not every database offer such information, so we can't retrieve it and display somewhere.

**Comment by Kaennchen80** [comment]
Oracle

Von: Who cares [mailto:notifications@github.com]
Gesendet: Dienstag, 2. Februar 2021 14:48
An: dbeaver/dbeaver <dbeaver@noreply.github.com>
Cc: Grosse, Anne <a.grosse@ottoroth.de>; Mention <mention@noreply.github.com>
Betreff: Re: [dbeaver/dbeaver] Creation date / modification date of tables, views and packages (#11179)


Hello, @Kaennchen80<https://github.com/Kaennchen80>,

What database are you talking about? Not every database offer such information, so we can't retrieve it and display somewhere.

**Comment by ShadelessFox** [comment]
Thank you for insanely fast response!

Indeed, Oracle can provide such information. We can implement it in the future

**Comment by bingosvr** [comment]
Probably db community edition do not have interface to display the table created date, how the sql SSMS show. 
Here is a query I use in DBeaver 
SELECT CREATED, * FROM INFORMATION_SCHEMA."TABLES"  WHERE TABLE_NAME ='INTEGRATION_FOREIGN_KEY' 
BINGO_DWH_DEV.STAGING.INTEGRATION_FOREIGN_KEY

**Comment by LonwoLonwo** [comment]
Already implemented for tables/view/materialized views for Oracle in DBeaver 23.1

![2023-06-14 18_34_06-Window](https://github.com/dbeaver/dbeaver/assets/45152336/82a97a2e-49a6-4196-ad1a-c21e57b5d5be)

**Comment by Kaennchen80** [comment]
Thank you very much!

**Comment by LonwoLonwo** [comment]
For now, this ticket will be open for packages metadata enhancement. I'm working on it right now. We will close this ticket when the work will be finished :)
