### ISSUE TITLE
Add option to change Last Value in sequences

### ISSUE THREAD

**Issue by remoover** [dbeaver/dbeaver#11177]
Hello, 

in sequences are not possible to change Last Value.. after import new manually data to an import we need use pgadmin to change value... OR ideally if on import will user select truncate.. AUTO change seq for last value.. so it will be working automatically :)... or manually  thanks !:)

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by ShadelessFox** [comment]
Implemented ability to edit properties of sequences:

![image](https://user-images.githubusercontent.com/35821147/115394739-c33eee80-a1eb-11eb-90c1-01e06a0c0042.png)

**Comment by uslss** [comment]
verified
