### ISSUE TITLE
SQL syntax highlight bug

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#11173]
We don't support single quotes escape properly in case of `E` escape.

```sql
select E'[xxx\']'
```
http://www.postgresql.org/docs/9.0/static/sql-syntax-lexical.html

Workaround: use double dollar escape (`select $$[xxx\']$$`)

**Comment by ShadelessFox** [comment]
A support for `E'a\'b\'c'` escaped string literals was added. 

Also support for backslash escapes in regular string literals was added, but it requires `standard_conforming_strings` setting to be `off`. This is an uncommon case, but this can be achieved by executing following query and then reconnecting to the server:
```
alter user current_user set standard_conforming_strings to off;
```

As a bonus, now you can preview all server settings under `Database` -> `System Info` -> `Settings`. ✨
Please make sure that this folder works fine in various PG forks.

**Comment by kseniiaguzeeva** [comment]
- E escape is verified
- server settings are verified in all available PG forks where folder **system info** exists

**Comment by kseniiaguzeeva** [comment]
verified
