### ISSUE TITLE
Mac download broken

### ISSUE THREAD

**Issue by tsongas** [dbeaver/dbeaver#11178]
On this page https://dbeaver.io/download/ when I click on Mac OS X (dmg) I get the following error:

```
<Error>
<Code>AccessDenied</Code>
<BucketName>dbeaver</BucketName>
<RequestId>tx000000000000020a83e82-0060172002-868307d-nyc3b</RequestId>
<HostId>868307d-nyc3b-nyc-zg02</HostId>
</Error>
```

I downloaded the zip file but when I unzipped it and tried dragging it into my Applications I got a warning saying the file is corrupt and should be deleted.

**Comment by serge-rider** [comment]
Thank you for the bug report.
Something went wrong during release publishing.
Fixed.

**Comment by kseniiaguzeeva** [comment]
Verified
