### ISSUE TITLE
No permite editar en celdas o campos registros

### ISSUE THREAD

**Issue by JOSUEGOHN01** [dbeaver/dbeaver#11183]
Al momento de realizar una modificación en un campo no lo actualiza en la base de datos y en ocasiones no muestra nada y en otras muestra un error.

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by kseniiaguzeeva** [comment]
Please tell me (in English) steps to reproduce, DBeaver version and the database.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it.
