### ISSUE TITLE
7.3.4 release doesn't contain a *macos.dmg asset?

### ISSUE THREAD

**Issue by apizz** [dbeaver/dbeaver#11181]
Previous DBeaver releases included a .dmg file for macOS that was separate from the *macosx.cocoa.tar.gz asset.

We have some automation setup to auto download the macOS DMG asset when released, but since this asset doesn't exist in this release it failed.

Is there a reason this .dmg asset isn't included in this release?

**Comment by Endogen** [comment]
I'd also like to know - especially since i can't install the .tar.gz version. The website link exists: https://dbeaver.io/files/dbeaver-ce-latest-macos.dmg but there is nothing to be downloaded.

**Comment by serge-rider** [comment]
Duplicatre of #11178
Already fixed (download link was broken)

**Comment by apizz** [comment]
While I'm glad the download link is working from the main website, the macOS DMG is still not a listed asset under this GitHub repo's latest release, which differs from past releases.

v7.3.3
![Screen Shot 2021-02-01 at 3 25 02 PM](https://user-images.githubusercontent.com/11789931/106514057-c1de0f80-64a1-11eb-9d78-c5a94cb88f26.png)

v7.3.4
![Screen Shot 2021-02-01 at 3 24 24 PM](https://user-images.githubusercontent.com/11789931/106514068-c73b5a00-64a1-11eb-818a-c08f637f9d5b.png)

**Comment by serge-rider** [comment]
@apizz Yep. Forgot to update it on GitHub. Thanks for noticing.
Fixed too (https://github.com/dbeaver/dbeaver/releases/download/7.3.4/dbeaver-ce-7.3.4-macos.dmg)

**Comment by apizz** [comment]
TY for fixing!
