### ISSUE TITLE
right to left languages

### ISSUE THREAD

**Issue by Bakrain** [dbeaver/dbeaver#11180]
#### System information: 
- windows 10 pro 20H2
- 7.3.4
- java version "1.6.0_19" 
- Additional extensions

#### Connection specification:
- Oracle 8i
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Any sql editor statement with right to left language like Arabic language can not write it with the correct order,
it appeares in reverse order .
this problem appeared in 7.3.1 and above .
it used to be fine in previous versions.

**Comment by uslss** [comment]
thanks for the report.
duplicates #10911

**Comment by uslss** [comment]
reproducible in 21.2.0

**Comment by arhayka** [comment]
Verified in this ticket: https://github.com/dbeaver/dbeaver/issues/35352
