### ISSUE TITLE
Wrong type of column returned if alias name is same as an existing fieldname.

### ISSUE THREAD

**Issue by FluffyRotkat** [dbeaver/dbeaver#11194]
#### System information: 
- Linux
- DBeaver version: 7.3.4
- Additional extensions: no

#### Connection specification:
- Postgresql 13

#### Describe the problem you're observing:
If you use an alias with the same name as an existing column, it returns the type of the existing column and not of the referring column. In the following example the query returns a bool instead of varchar. 

#### Steps to reproduce, if exist:
CREATE TABLE public.database_company (
	id serial NOT NULL,
	"Company_name" varchar(100) NULL,
	transporter bool NULL, 
);
CREATE TABLE public.database_log_weight (
	id serial NOT NULL,
	weight int8 NULL,
	destination_id int4 NULL,
	transporter_id int4 NULL,
);

select c."Company_name" as transporter
from public.database_log_weight l
left join database_company c on l.transporter_id=c.id

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
It is a side effect of "bug" in PostgreSQL driver, see https://stackoverflow.com/questions/38404534/postgresql-getcolumnname-is-not-working-returning-alias-name

It is not possible to determine original name of a column in resultset.
We need some workaround.

**Comment by serge-rider** [comment]
We'll try to get real column name from the query itself

**Comment by kseniiaguzeeva** [comment]
Verified. Vertica case cannot be reproduced too.
`SELECT c.*, data_type_id as DATA_TYPE from v_catalog.columns c`

**Comment by ashf** [comment]
I am still seeing this issue:

DBeaver Version 21.3.2.202112271055
PostgreSQL 10.18 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit
