### ISSUE TITLE
ClickHouse : download driver fail

### ISSUE THREAD

**Issue by raphaelauv** [dbeaver/dbeaver#11195]
#### System information: 
- Operating system : 5.8.0-41-generic #46~20.04.1-Ubuntu 
- DBeaver version : Version 7.3.4.202101311042
- Additional extensions

#### Describe the problem you're observing:

When I setup a connection to clickhouse-server ( docker )

```
docker run --rm -e CLICKHOUSE_DB=my_database -e CLICKHOUSE_USER=username -e CLICKHOUSE_PASSWORD=password -p 9001:9000/tcp yandex/clickhouse-server
```

Dbeaver ask to download driver and fail :

```
Driver file download failed.
Do you want to retry?

Reason:
Can't open 'https://repo1.maven.org/maven2/ru/yandex/clickhouse/clickhouse-jdbc/${revision}/clickhouse-jdbc-${revision}.jar': Not Found
```

Thank you all :+1:

**Comment by raphaelauv** [comment]
![Screenshot from 2021-02-02 23-07-19](https://user-images.githubusercontent.com/10202690/106759325-ea494380-6632-11eb-8bbf-a206ac9cb1a0.png)

If I change the version of the driver to 0.2.4 it work

but 0.2.5 do not work

**Comment by zverev-iv** [comment]
Same problem for me today.

**Comment by uslss** [comment]
thanks for the report
![image](https://user-images.githubusercontent.com/31996417/106914622-420cab00-6716-11eb-814f-8d13ffbacc58.png)
![image](https://user-images.githubusercontent.com/31996417/106914734-5b155c00-6716-11eb-9b27-5775afaf2ef9.png)

**Comment by serge-rider** [comment]
It is a bug in Maven artifact version resolution. That's quite an unusual artifact definition.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by ghost** [comment]
> thanks for the report
> ![image](https://user-images.githubusercontent.com/31996417/106914622-420cab00-6716-11eb-814f-8d13ffbacc58.png)
> ![image](https://user-images.githubusercontent.com/31996417/106914734-5b155c00-6716-11eb-9b27-5775afaf2ef9.png)

Thanks, helped a lot.
