### ISSUE TITLE
Export Tasks as a Java application

### ISSUE THREAD

**Issue by spassignat** [dbeaver/dbeaver#11199]
Tasks are great but they would be even better without graphical interaction to run them.

I would like to export tasks as a java application in an archive file containing jdbc driver, the main, potentially dbeaver runtime jar files and bat or sh shell. That enables to schedule this application in the operation system (linux widows, ...)

This would be a quick win compare to an ETL solution.

**Comment by ShadelessFox** [comment]
Hello @spassignat,

DBeaver can be launched in "headless" mode without any graphical interaction to perform different commands: https://github.com/dbeaver/dbeaver/wiki/Command-Line

DBeaver also has task scheduler on any supported platform, but this is an Enterprise feature:
https://github.com/dbeaver/dbeaver/wiki/Task-Scheduler

Let me know if you still have any questions.

**Comment by spassignat** [comment]
That's an interesting work around. Need to give a deeper look at the EE edition.

Thanks

**Comment by ShadelessFox** [comment]
I will close this issue for now.
