### ISSUE TITLE
Replace [x] to [√] or [ok] would be better

### ISSUE THREAD

**Issue by tinelion** [dbeaver/dbeaver#11190]
![image](https://user-images.githubusercontent.com/22972600/106573752-fd95d980-6574-11eb-982d-86e06784eecd.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. The similar commens are here https://github.com/dbeaver/dbeaver/issues/10645#issuecomment-759094851 and https://github.com/dbeaver/dbeaver/issues/9327#issuecomment-763500502

**Comment by kai-morich** [comment]
👍

**Comment by serge-rider** [comment]
Let's try `[v]`

**Comment by uslss** [comment]
verified
