### ISSUE TITLE
SQL Error [XX000]: ERROR: ClickHouse does not support deletes

### ISSUE THREAD

**Issue by kolykhalov** [dbeaver/dbeaver#11203]
#### Describe the problem you're observing:

SQL Error [XX000]: ERROR: ClickHouse does not support deletes

#### Steps to reproduce, if exist:

query: delete from [clickhouse_fdw] where [expr] 

#### Solution

Clickhouse supports deletes as "Alter table [table] delete where [expr]"

Please update

**Comment by uslss** [comment]
thanks for the report

duplicates #10718
