### ISSUE TITLE
Broken selection in SQL Editor

### ISSUE THREAD

**Issue by reklatsmasters** [dbeaver/dbeaver#11205]
#### System information: 
- Ubuntu 16.04 LTS
- DBeaver version 7.3.4.202102011519
- Additional extensions NO

#### Describe the problem you're observing:

![ezgif-6-36870404b9c2](https://user-images.githubusercontent.com/2255752/106743160-d22bf100-663f-11eb-8e43-eba804b14f7d.gif)

#### Steps to reproduce, if exist:
I just want to copy-paste a part of sql.

**Comment by uslss** [comment]
hi @reklatsmasters ,
could you clarify what is wrong?
does the issue happens on double-click or any other steps are needed?
thanks in advance

**Comment by reklatsmasters** [comment]
No additional steps are need. I just open dbeaver and this happens when a trying to select something.

**Comment by serge-rider** [comment]
Is it still reproducible in the recent versions (21.0+)?

**Comment by Matvey16** [comment]
I was not able to reproduce it on Ubuntu 20.04 and Dbeaver 21.0.5. Have you tried using Shift+Left-click to highlight a portion of the text?

![2021-05-24_15h38_50](https://user-images.githubusercontent.com/82543000/119349278-a728e400-bca6-11eb-8a01-8f552b0f1099.gif)

**Comment by uslss** [comment]
there is no update on issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.

**Comment by rokopi-byte** [comment]
Hello, any update on this ? Version 2021.2.0 still have this issue for me on Ubuntu 16.04
