### ISSUE TITLE
Array types are removed from tree - PostgreSQL

### ISSUE THREAD

**Issue by akos2** [dbeaver/dbeaver#11216]
#### System information: 
- Linux (ANY)
- DBeaver version 7.3.4.202101311042

#### Connection specification:
- PostgreSQL 13.1
- JDBC Driver 42.2.18

#### Describe the problem you're observing:
Tree cleanup introduced in latest build (remove ob Array types) made hard to work with UDT declared as ARRAY. It is now impossible to find domain if it is an array. It is uncomfortable.
#### Steps to reproduce, if exist:
create domain aaa as int[]

It is not shown in Data types tree node.

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
To see all PostgreSQL data types (including array and table types) enable "Read all data types" setting in connection settings:
![2021-02-11 12_49_29-DBeaver Enterprise 7 3 5 - planet_osm_line](https://user-images.githubusercontent.com/45152336/107684071-625add80-6cb3-11eb-85ea-ffd258eec8ac.png)

Or for all connections in Preferences -> Connections -> PostgreSQL
![2021-02-11 12_49_46-DBeaver Enterprise 7 3 5 - planet_osm_line](https://user-images.githubusercontent.com/45152336/107684203-8cac9b00-6cb3-11eb-84d9-7af4324033f9.png)

Implemented in DBeaver version 7.3.5
