### ISSUE TITLE
Use variable in export path

### ISSUE THREAD

**Issue by spassignat** [dbeaver/dbeaver#11213]
I need to export data from several csv files using the select which only differs in their where clause by a value. For this, I uses a variable and have one task per organisation.
ex: SELECT * FROM CLIENT WHERE ORG='${organisation}'

I would like to export the files in a structure like this ~/Client/${organisation}/AllClient-${timestamp}.CSV

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by ShadelessFox** [comment]
Implemented. Now parameters defined inside SQL script can be used in data transfer.

Be aware that you can't redefine predefined variables in data transfer.

**Comment by Matvey16** [comment]
Verified
