### ISSUE TITLE
Jobs of the Oracle database are not shown 

### ISSUE THREAD

**Issue by qiqingli** [dbeaver/dbeaver#11218]
#### System information: 
- Operating system (distribution) and version：macOS Big Sur 11.2
- DBeaver version：7.3.4

#### Connection specification:
- Database name and version：Oralce 12c

#### Describe the problem you're observing:
Dbeaver failed to display the Jobs under the database user, but it can be displayed normally with other tools.

#### Steps to reproduce, if exist:
1、Other tools can display Jobs normally.
![image](https://user-images.githubusercontent.com/20805098/106835832-fd135500-66d2-11eb-9fc8-9f69fe23cea7.png)

2、Dbeaver can’t display Jobs normally.
![image](https://user-images.githubusercontent.com/20805098/106835682-ba517d00-66d2-11eb-9bc1-50ce1fc61fd6.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by ShadelessFox** [comment]
Hello @qiqingli,

DBeaver can display jobs in Oracle. Go to <kbd>Scheduler</kbd> &rArr; <kbd>Jobs</kbd>.

Let me know if it solves your issue.

**Comment by qiqingli** [comment]
DBeaver does not show Jobs correctly, Refer to the information shown in the screenshot.

![image](https://user-images.githubusercontent.com/20805098/115550476-7c7cf180-a2dc-11eb-89a3-c82ec3ec0740.png)


![image](https://user-images.githubusercontent.com/20805098/115549585-6458a280-a2db-11eb-8211-5072127d303c.png)

Other tools can show Jobs
![image](https://user-images.githubusercontent.com/20805098/115550117-0e382f00-a2dc-11eb-8ef0-da7a78dd2558.png)

**Comment by ShadelessFox** [comment]
I see, thanks!

**Comment by ShadelessFox** [comment]
Basic page for viewing these jobs was added:

![image](https://user-images.githubusercontent.com/35821147/115883689-bd007a80-a456-11eb-963c-1961000b52d4.png)

It is located inside schema, just above the <kbd>Scheduler</kbd>.

**Comment by uslss** [comment]
verified
