### ISSUE TITLE
default schema in Athena is ignored

### ISSUE THREAD

**Issue by chanansh** [dbeaver/dbeaver#11211]
#### System information: 
- Operating system (distribution) and version - MacOS 11.2
- DBeaver version -  7.3.4.202101310933
- Additional extensions -

#### Connection specification:
- Database name and version AWS Athena
- Driver name -  Athena 4.2 JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
Selecting a default schema via right-click "set as default" or from the top menu pulldown list has no effect on the query engine and default is used instead.

SQL Error [100071] [HY000]: [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. SYNTAX_ERROR: line 16:6: Table awsdatacatalog.*default*.table_name does not exist
#### Steps to reproduce, if exist:
1. connect to Athena https://www.cdata.com/kb/tech/athena-jdbc-dbvr.rst
2. select a default schema
3. run query
4. get the error of table_name does not exist (as the wrong schema/database_name is used)

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
duplicates #11196
