### ISSUE TITLE
Expand star * into all columns list

### ISSUE THREAD

**Issue by ADataGMan** [dbeaver/dbeaver#11220]
#### System information: 
- OS - Windows 10 1903
- Version - 7.34

#### Describe the problem you're observing:
I stumbled into a way to auto expand a * into a full column list and I'm unable to figure out how to do it again. I've found the documentation for SQL Assist but this does not describe what I previously did. I believe I had found it under a right click option in the SQL editor window. This may have been under 7.33.

https://github.com/dbeaver/dbeaver/wiki/SQL-Assist-and-Auto-Complete

**Comment by LonwoLonwo** [comment]
@ADataGMan press Ctrl+Space after asterisk in query like "SELECT * FROM tableName" or like "INSERT INTO tableName (*)" (brackets are important)  - the asterisk will be replaced with a list of all table columns.
I have updated the documentation, thanks

It works?

**Comment by ADataGMan** [comment]
That gives me a list like the documentation, but I have a thousand plus
column table, how do I get all column names at once? I swear I had clicked
on an expand names function before.

**Comment by LonwoLonwo** [comment]
@ADataGMan What does the query look like in which the list is not replaced? Do you press Ctrl+Space after the asterisk?

**Comment by ADataGMan** [comment]
@LonwoLonwo when I press ctrl+space on select tb.* from tb, I get a list of all of the fields I can choose from, but I have to select one to autocomplete it in 7.3.4. This is querying a Redshift view created WITH NO SCHEMA BINDING on version 1.0.22169

If I review the active hotkeys list, when I see Ctrl+Space, it says it is the Content Assist hotkey.

**Comment by LonwoLonwo** [comment]
@ADataGMan The standard behavior for an assistant after the table name (or alias) and dot is to suggest a list of columns.
And the replacement works if there is nothing in front of the asterisk (a space). In the case of SELECT.
`select *(ctrl+space) from tb`

**Comment by ADataGMan** [comment]
@LonwoLonwo That makes sense, but what I'm trying to do is expand a star into the entire list of fields. So go from select * from tb to select colA, colB, colC from tb. The expand all functionality does not show up in the right click menu, and in the Active Keybindings, the default Expand All function Ctrl + NumpadPlus does not work as well. 

I loved that I was able to run this expand all function before, but may be I did that in 7.3.3 rather than 7.3.4? How can I turn star into the entire list of  columns?

**Comment by p91paul** [comment]
you should use ctrl+space with your cursor placed after the asterisk, as proposed above. Expand all is a different action!

**Comment by ADataGMan** [comment]
@p91paul But what I'm saying is that in 7.3.4 on Redshift, all I get is a list of fields I can choose from. I get a chance to auto complete with 1 field, colA, colB, OR colC. Either ctrl+space does not work as expected in this version, or we're describing two different problems.

Current situation:
select * from tb

Desired situation:
select colA, colB, colC from tb

How do I get from here to there without hand typing each column? Is that assist? is that expand all?

**Comment by LonwoLonwo** [comment]
@ADataGMan Can you please make a video of error/wrong behavior?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info

**Comment by chkp-ayalalon** [comment]
@ADataGMan, i had similar problem. 
found out i had other key binding  shortcut for Ctrl+Space. (it could also be binding from the os so be sure to check that as well)
Changed the binding solved it for me.

**Comment by trenish** [comment]
@ADataGMan, the confusion seems to be based on whether the asterisk is highlighted vs. the cursor is simply resting to the immediate right of the asterisk and nothing highlighted.  If highlighted, ctrl+space causes a list to pop up for individual field selection.  

In the latter scenario in which the asterisk is *not* highlighted, my coworker and I have two different behaviors (no idea why).  For him, ctrl+space instantly replaces the asterisk with all fieldnames.  For me, it presents a popup box with all fieldnames on a single line.  Pressing enter will replace the asterisk with the full list, meaning we both end up with the same desired result.  In both cases, the list is populated without line feeds, so following this up with ctrl+shift+f will format it appropriately.

**Comment by wistlo** [comment]
Came here to write up a request, but found the solution already exists.  Typing alias.* and hitting control-space gives whole list with the alias prefix.   This is really useful when joining multiple tables with dozens of fields.  Thanks dbeaver!

**Comment by ufuk-ergin-carbon** [comment]
Hey folks, it looks like we lost this functionality, at least on Mac. Can somebody from Dbeaver team confirm please?

**Comment by E1izabeth** [comment]
@ufuk-ergin-carbon 
I'm not sure it depends on OS. It works for me for `select`. And here is an issue about `insert` #22164
If you have some other case, please provide your example.

**Comment by ufuk-ergin-carbon** [comment]
Hi @E1izabeth, I think it works. It did not work previously because it was conflicting with Mac's system shortcut for changing the input method (^ + Space). When I removed the system shortcut for the input method, it now works in Dbeaver.

**Comment by E1izabeth** [comment]
@ufuk-ergin-carbon thank you for update
