### ISSUE TITLE
Modify the mysql index type on the user interface

### ISSUE THREAD

**Issue by ffbh123456** [dbeaver/dbeaver#11223]
I am editing a MySQL table. I want to change the index type from BTree to Hash, but it seems that it cannot be modified on the interface, please add this function
![image](https://user-images.githubusercontent.com/20750357/106888513-9f5a2980-6721-11eb-8243-cc9df07d3aed.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.  The option will be added in future releases.

**Comment by ShadelessFox** [comment]
Hello @ZhouJiaZhi,

Unfortunately, MySQL does not allow to alter indexes, so it's not possible to change the type of an already created index.
