### ISSUE TITLE
When executing 2 queries in parallel, first does not print results until the second query finishes

### ISSUE THREAD

**Issue by mikkk3l** [dbeaver/dbeaver#11221]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 7.3.4
- Additional extensions

#### Connection specification:
- Database name and version Oracle Exadata
- Driver name ojdbc8.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When I execute multiple long queries, they are executed sequentially. That's OK. But the first tab remains in "Fetch result set" until last query ends. It would be nice to print as the first query returns, if not, one is blocked by the last query executed.

**Comment by mikkk3l** [comment]
I attach an image:
![imagen](https://user-images.githubusercontent.com/15341836/106870379-57131b00-66d1-11eb-815c-9a14bfdf6fba.png)

**Comment by kseniiaguzeeva** [comment]
Looks like some driver limitation. Please use 2 different SQL Editor windows for the query with enabled **Open separate connection for each editor** option.
![dbeaver_Xwk828I8a8](https://user-images.githubusercontent.com/51405061/107615398-2b59dd00-6c5d-11eb-993c-06bfab5d4650.png)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info
