### ISSUE TITLE
Projects pane doesn't refresh switching between branches (Git support)

### ISSUE THREAD

**Issue by hennie7863** [dbeaver/dbeaver#11227]
Hi There,

Question. I've installed the gitsupport add in (may be it's a bug of gitsupport add in) and when I switch between the branches in the Git repositories pane, the files do not change in the Projects pane. Is this a bug or am i doing somethnig wrong? Or is this by design?

It's a bit annoying that when I switch between branches and the files are not updated, errors appear when the file is not found because it's not in the branch.

Thank you
Hennie

**Comment by kseniiaguzeeva** [comment]
Looks like a bug. We are going to fix it. As a workaround please try to use manual refresh to see correct files.

**Comment by ShadelessFox** [comment]
Hello @hennie7863,

I cannot reproduce your issue:

https://user-images.githubusercontent.com/35821147/115411228-f6897980-a1fb-11eb-8a62-97597e2b627f.mp4

Can you try upgrading and testing against [newest version](https://dbeaver.io/download/)?

**Comment by hennie7863** [comment]
The file is committed to local branch.

In one branch : 

![image](https://user-images.githubusercontent.com/7771436/115689059-028c4d00-a35c-11eb-8409-36e7034e546c.png)

In the other branch

![image](https://user-images.githubusercontent.com/7771436/115689159-1df75800-a35c-11eb-9617-45ed7782a727.png)

What am I doing wrong?

**Comment by ShadelessFox** [comment]
What version are you using? Have you upgraded to [newest version](https://dbeaver.io/download/)?

Also, you can try reproducing this issue against a newly created project, just for the sake of sanity.

**Comment by hennie7863** [comment]
Yes newest version. but problem was in all versions of the last months. When I have time I will try it on a new project en repo. please have some patience for that.

**Comment by ShadelessFox** [comment]
No problem, thanks!

**Comment by uslss** [comment]
there is no update for a long time.
if the issue is still actual for you - feel free to reopen it
