### ISSUE TITLE
Import from csv cannot configure columns varying by case only.

### ISSUE THREAD

**Issue by andy-clapham** [dbeaver/dbeaver#11229]
#### System information: 
- OS Win10, 
- DBeaver Version 7.3.4.202101311042

#### Connection specification:
- Postgres 12.5 Azure flexible server
- PostgreSQL standard driver postgres-jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:
I'm attempting to create a csv import to an existing table with matching fields.
There are two columns in the target table varying only by casing ("Reference" and "reference")
Choosing "existing" mapping, and using the drop-down column selector, is not possible to select the second lower-case column.
While it is shown correctly in the list, selecting it selects the first entry, matching without case sensitivity.

#### Steps to reproduce, if exist:

Create a table
```sql
create table csvdemo("A" int, "a" int);
```

Create a csvdemo.csv
```csv
A,a
1,1
2,3
```

* Open the import data dialog
  * configure to import data into csvdemo from csvdemo.csv
  * Leave Importer settings as default.
* In tables mapping
  * Expand the table
  * Note that A is mapped to "A", and a is mapped to "A" too.
  * Drop down the list of target columns for a, note that both "A" and a are shown as options
  * Select a from the list and note that "A" is actually chosen.
  
Expected behaviour would be to differentiate between the columns from the table schema.
I would expect all column identifiers to be quoted, rather than assuming lowercase doesn't need quoting, then choosing the first matching quoted value. "A" unquoted is _a_ which is in this case is ambiguous.

#### Include any warning/errors/backtraces from the logs
Trying the import naturally fails with "ERROR: column "A" specified more than once, but no other info in the logs.

**Comment by uslss** [comment]
thanks for the report

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Incorrect mapping when switching back and forth for quoted target column

![zH0p5iaYic](https://user-images.githubusercontent.com/82543000/125274338-8aa84000-e316-11eb-921e-b75896d41745.gif)

**Comment by flambchap** [comment]
Fixed that as well.

**Comment by Matvey16** [comment]
Verified

**Comment by andy-clapham** [comment]
Great stuff!
Thanks for working on this - will save us effort manually renaming things when importing data.
