### ISSUE TITLE
Lost comments for a view and a columns of view in Oracle

### ISSUE THREAD

**Issue by mkgrgis** [dbeaver/dbeaver#11236]
#### System information: 
- Operating system (distribution) and version
Ubuntu 20
- DBeaver version
7.3.4 (the latest)
- Additional extensions
No

#### Connection specification:
- Database name and version
Oracle 10i
- Driver name
standard, from standard download dialogue
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No
#### Describe the problem you're observing:
Deleting of comments for view and view's columns if recompile the view.

#### Steps to reproduce, if exist:
1. Create a view with 1-2 columns
2. Comment the view
3. Comment the columns
4. Change the view declaration
5. No comments :-(

#### Include any warning/errors/backtraces from the logs
No problems in log

**Feature request:** add DDL for comments after recompile if there is comments for the view or for columns of the view.

**Comment by uslss** [comment]
unfortunately, cannot reproduce an issue. did you add comments using UI?

**Comment by mkgrgis** [comment]
Yes. I meant renaming or reordering of columns as view's declaration changing. Also deleting of column's line affected in `CREATE VIEW x (`**c1, c2 ...**` ) AS SELECT ....` and recompilation in some cases.

**Comment by mkgrgis** [comment]
This issue isn't about void comments in UI. It's about voiding comments in DB after some of changes of a view. You must press F5 anytime after some change of a view to see the DB, not UI, situation.

**Comment by LonwoLonwo** [comment]
Displaying objects with lazy initialization fixed in DBeaver 21.0.4

**Comment by uslss** [comment]
verified
