### ISSUE TITLE
[PostgreSQL] Incorrect generate INSERT statement for OID data types.

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#11254]
- DBeaver 7.3.4
- PostgreSQL 11.6
- 
![2021-02-08 10_59_29-Preview changes](https://user-images.githubusercontent.com/45152336/107191408-2991de80-69fd-11eb-8482-b53d48ee2030.png)

Incorrect SQL generated for all OID types - https://postgrespro.com/docs/postgrespro/13/datatype-oid

Steps:
1. Create table
CREATE TABLE public.test_table_reg (
	id int4 NOT NULL,
	proc regproc NOT NULL,
	oper regoper NOT NULL,
	"type" regtype NOT NULL,
	"namespace" regnamespace NOT NULL,
	CONSTRAINT test_table_reg_pkey PRIMARY KEY (id)
);
2. Open data viewer
3. Add some values in table 
4. Click on button "Script" or "Generate SQL" -> "INSERT"

**Comment by LonwoLonwo** [comment]
Related https://github.com/dbeaver/dbeaver/issues/9406

**Comment by Matvey16** [comment]
Verified

**Comment by LonwoLonwo** [comment]
Fixed in scope with https://github.com/dbeaver/dbeaver/issues/12812

**Comment by uslss** [comment]
verified
