### ISSUE TITLE
PostgreSQL connection settings advanced user role doesn't work as expected

### ISSUE THREAD

**Issue by giulio-quaresima** [dbeaver/dbeaver#11268]
#### System information: 
- Linux 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
- OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
- DBeaver Version 7.3.4.202101311042

#### Connection specification:
- PostgreSQL Server 9.3.25
- PostgreSQL JDBC 42.2.5
- sslmode=prefer

#### Describe the problem you're observing:
I have a user with GRANTS to query some views in a given schema. The grants are assigned to a role which I own, so to query the views I have to execute the command `SET ROLE 'MY_ROLE';` before querying the views.

When I configured the connection, I have put 'MY_ROLE' in the Connection settings > Advanced > User role field, expecting the `SET ROLE` command to be called immediately after the connection opening, but if I try to surf the views from the navigator, showing their content using the "View data" function, I get a "permission deneid" error. On the other hand, if in the SQL Editor I execute the `SET ROLE` command, then I can `SELECT` all the views without errors.

I'm not pretty sure whether this is a bug or I misinterpreted the use of the "User role" setting. If this is a "work as expected" case, how can I workaround the issue? For example, is there a way to configure an initialization SQL script to put the `SET ROLE` command in?

Thank you

**Comment by kseniiaguzeeva** [comment]
Thank you for your report.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce the issue in [the latest 21.1.3 version](http://dbeaver.io/)? Could I ask you to check the issue from your side?

**Comment by giulio-quaresima** [comment]
Just tried: same error for version 21.1.3.202107181810

**Comment by flambchap** [comment]
Does SET ROLE 'MY_ROLE' statement appear in the [query manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) when you connect to the database? Make sure to tick "Utility functions" before checking that. I also want to ask you to send [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files) which would be very helpful. Thank you.

**Comment by giulio-quaresima** [comment]
Dear Nikita,

following your suggestion, I carefully read the logs and I found the
solution: it is a quotation problem.

It happens that if one set a role in the "user role" field of the
connection properties, say MY_GREAT_ROLE, when DBeaver opens the connection,
it issues the command SET ROLE MY_GREAT_ROLE which results in:

> org.postgresql.util.PSQLException: ERROR: role "my_great_role" does not
> exist


The solution is to write the role in the user role field within quotes,
'MY_GREAT_ROLE', which results in the correct command SET ROLE
'MY_GREAT_ROLE'. I think that this aspect should be better documented,
perhaps also with an explanation note near the field.

I tried this solution in the very last 21.1.4 release, and it works well.

Thank you for your help.

Regards
Giulio--

**Comment by flambchap** [comment]
Hello Giulio, thank you for your investigation. I believe that DBeaver should use proper quotation automatically when executing `SET ROLE` statement, so that's what I'm going to do for the next release.

**Comment by flambchap** [comment]
Done.

**Comment by Matvey16** [comment]
Verified
