### ISSUE TITLE
firebird 2.5 comment still 

### ISSUE THREAD

**Issue by qqrate** [dbeaver/dbeaver#11266]
use jdbc jaybird 4.0.2,java jdk 8.0.connet firebird 2.5 ,everything is ok,but the comment for chinese is still gibberish,please tell how to  solve the problem？

**Comment by uslss** [comment]
hi @qqrate ,
can you add a screenshot that will show the problem? 
Thanks in advance

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it
