### ISSUE TITLE
MySQL Query results - filters on columns with spaces aren't escaped properly

### ISSUE THREAD

**Issue by DeflateAwning** [dbeaver/dbeaver#11265]
#### System information: 
- Windows 10
- DBeaver version: 7.3.1

#### Connection specification:
- MySQL connection (v5.x)
- No tunnels nor proxies

#### Describe the problem you're observing:
When filtering the results table of a query from the text editor, filters applied to columns with spaces in their names don't escape the column names correctly.

1. Run a query from a script in the text editor, where the result includes column names with spaces.
2. Apply a filter to a column using the filter box in the results table (by using the filter popup with distinct value selection) to a column with a space in its name.
3. Problem: The column name isn't properly escaped with backticks, making the resulting query invalid.

![image](https://user-images.githubusercontent.com/11021263/107318916-072eae00-6a5b-11eb-9fde-d7eee86bfc19.png)
![image](https://user-images.githubusercontent.com/11021263/107318867-f5e5a180-6a5a-11eb-95d6-7c3ade930b92.png)

#### Include any warning/errors/backtraces from the logs
N/A

**Comment by kseniiaguzeeva** [comment]
Please give me a query example to reproduce.

**Comment by DeflateAwning** [comment]
I can't reproduce this either anymore. It appears that once the picklist is cached, the issue has disappeared (or something). Will re-open if I can reproduce it more reliably

**Comment by kseniiaguzeeva** [comment]
Ok!
