### ISSUE TITLE
Switching windows with CTRL F6 or CTRL SHIFT F6 bug reappeared

### ISSUE THREAD

**Issue by jhauss** [dbeaver/dbeaver#11269]
#### System information: 
- Operating system Ubuntu 18.04
- DBeaver version 7.3.4
- Additional extensions

#### Connection specification:
- Database name and version : postgres, 11
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? YES, ssh

#### Describe the problem you're observing:
Every CTRL F6 opens a new list of windows. List will not close by typing ESC
(This problem already happened in the past)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. It is an eclipse bug, and we should wait for fix from its side.

**Comment by uslss** [comment]
cannot reproduce it against 21.3.2
