### ISSUE TITLE
Redshift connections randomly set to read-only after upgrade to 7.3.4

### ISSUE THREAD

**Issue by mgirard772** [dbeaver/dbeaver#11264]
#### System information: 
- **Operating system (distribution) and version:** MacOS Catalina 10.15.7
- **DBeaver version:** 7.3.4 CE

#### Connection specification:
- **Database name and version**: Amazon Redshift 1.0.23412
- **Driver name**: https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.51.1078/RedshiftJDBC42-1.2.51.1078.zip
- **Do you use tunnels or proxies (SSH, SOCKS, etc)?** No

#### Describe the problem you're observing:
Redshift connections being set to read-only without the setting being checked. 

![image](https://user-images.githubusercontent.com/24948365/107277291-2ceb9100-6a22-11eb-9119-568fb69ab889.png)

Toggling the `Read-only connection` box and saving does not fix the issue. There is no way to disable read-only mode.

![image](https://user-images.githubusercontent.com/24948365/107277373-48569c00-6a22-11eb-8bd1-0c81442d937d.png)

Resolved by downgrading DBeaver to 7.3.0. Upgrading and downgrading prompt a upgrading and downgrading of the Redshift driver respectively. 

As noted below, it seems this is tied to the Redshift driver and not DBeaver itself.

#### Steps to reproduce, if exist:
1. Create a connection in a version lower than 7.3.4, make sure `Read Only connection` is unchecked.
2. Confirm you can write using this connection.
2. Upgrade DBeaver to 7.3.4
3. Connect to above connection and attempt a write operation.

**Comment by serge-rider** [comment]
It seems to be a Redshift driver issue. At some moment it marks active connection as read-only. Reconnect helps.
I don't know how to resolve this from DBeaver side. 

Could you try another version of Redshift driver?
It can be downloaded here
https://docs.aws.amazon.com/redshift/latest/mgmt/jdbc20-download-driver.html
or here
https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html

**Comment by mgirard772** [comment]
That's interesting. 

Upgrading to 7.3.4 prompts for a download of the Redshift driver, and the option available is: https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.51.1078/RedshiftJDBC42-1.2.51.1078.zip

However, when you downgrade to 7.3.0, you're also prompted to download the Redshift driver, except the version available is now: https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.45.1069/RedshiftJDBC42-no-awssdk-1.2.45.1069.jar

Seems that 1.2.45.1069 works, but 1.2.51.1078 is broken. I can create an issue with Amazon and link them to this for reference.

Is there a way to prevent DBeaver from suggesting the broken driver, at least until Amazon publishes a fix for that version, or provides a new one? I'm sure other users either are experiencing or will experience a similar issue.

**Comment by mgirard772** [comment]
Also, do you happen to know the process for reporting driver bugs to Amazon?

**Comment by serge-rider** [comment]
Looks like driver version 1.2.45.1069 seems to be the last good one. I will revert default download location to it.

Unfortunately I'm not aware about the official process of bug reporting to Amazon. But probably creating a ticket at https://github.com/aws/amazon-redshift-jdbc-driver will work.

**Comment by uslss** [comment]
verified

**Comment by samdavey** [comment]
I've found a workaround that seems to fix it (temporarily). I'm using version RedshiftJDBC42-no-awssdk-1.2.55.1083.jar which seems to have the same issue. It is particularly prevalent on sessions you leave unattended for a bit, so might be related to a timeout setting.

Run the following SQL restore your session's ability to 'write' ...
`set readonly = 0;`
... then get on with your day (until you do it again an hour later).
