### ISSUE TITLE
Cannot download clickhouse driver

### ISSUE THREAD

**Issue by ramazanpolat** [dbeaver/dbeaver#11263]
#### System information: 
- Operating system (distribution) and version: Windows 10 x64
- DBeaver version: 7.3.3, 7.3.4
- Additional extensions

#### Connection specification:
- Database name and version: Clickhouse 20.8.7.15
- Driver name: automatically downloading driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When trying to connect to a Clickhouse database, I get this error:
```
Driver file download failed.
Do you want to retry?

Reason:
Can't open 'https://repo1.maven.org/maven2/ru/yandex/clickhouse/clickhouse-jdbc/${revision}/clickhouse-jdbc-${revision}.jar': Not Found
```

#### Steps to reproduce, if exist:
- Add new connection
- Clickhouse
- Edit Driver
- Download

**Comment by uslss** [comment]
thanks for the report.
duplicates #11195 
will be fixed in 7.3.5. Already available in [EA version](https://dbeaver.io/files/ea)
