### ISSUE TITLE
Redshift - show permissions issue

### ISSUE THREAD

**Issue by JParkACR** [dbeaver/dbeaver#11276]
#### System information: 
- Windows Server 2010
- DBeaver version : 7.3.4.202101311042

#### Connection specification:
- Amazon Redshift
- Driver name: com.amazon.redshift.jdbc42.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
On Table or View properties > DDL or Source
"Show Permissions" selected
Then the DDL script shows the table permission GRANT statement.

For Redshift, the GRANT statement shows wrong permission.
For example )
GRANT INSERT, SELECT, UPDATE, DELETE, UNKNOWN, REFERENCES, TRIGGER ON TABLE public.dummy TO myuser;

UNKNOWN, permission is a wrong permission. It supposed to be RULE such as:
GRANT INSERT, SELECT, UPDATE, DELETE, RULE, REFERENCES, TRIGGER ON TABLE public.dummy TO myuser;

#### Steps to reproduce, if exist:
Connect to AWS Redshift,
On Table or View properties > DDL  (or Source)
"Show Permissions" selected
Then the DDL script shows the table's permission GRANT statement which is wrong if RULE permission added.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
Fixed in 21.0.2
new ticket about Redshift permissions created https://github.com/dbeaver/dbeaver/issues/11912

**Comment by uslss** [comment]
verified
