### ISSUE TITLE
Clickhouse driver download error

### ISSUE THREAD

**Issue by beglex** [dbeaver/dbeaver#11273]
#### System information: 
- OS: Windows 10 1909
- DBeaver: 7.3.4.202101311042

#### Connection specification:
- Driver: Clickhouse
- Without tunnels or proxies

#### Describe the problem you're observing:

Error with downloading Clickhouse driver:
```
Driver file download failed.
Do you want to retry?

Reason:
Can't open 'https://repo1.maven.org/maven2/ru/yandex/clickhouse/clickhouse-jdbc/${revision}/clickhouse-jdbc-${revision}.jar': Not Found
```

#### Steps to reproduce, if exist:

1. Install DBeaver
2. Create a connection to Clickhouse DB
3. Open the connection
4. Click *Download* button in the popup window

**Comment by uslss** [comment]
thanks for the report.
duplicates #11195
will be fixed in 7.3.5. Already available in [EA version](https://dbeaver.io/files/ea)
