### ISSUE TITLE
SQL editor toolbar redesign

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#11279]
We have too many SQL buttons on the main toolbar.
Let'\s combine them in a single action with dropdown.

We also could improve behavior of "Open Recent Script" action so it will show script selector when recent script is already open and active.

**Comment by p91paul** [comment]
considering which button appear in the toolbar is already configurable through "customize perspective", what about adding a *new* button with dropdown, showing only that one by default, but allowing users to choose to reinstate the multiple buttons if they so desire?

**Comment by serge-rider** [comment]
The idea is to combine all SQL buttons in a single drop-down.
Perspective customization is great but is for advanced users. We want to make default perspective presentation lighter.

![image](https://user-images.githubusercontent.com/6398845/107506432-1f174680-6baf-11eb-9055-d9a0a36d927f.png)

**Comment by uslss** [comment]
verified

**Comment by p91paul** [comment]
Yeah what I meant is: put this new dropdown in the perspective by default, but leave the old ones in the perspective configuration, invisible by default, to be added if the advanced users prefer them.
