### ISSUE TITLE
Smart commit starts a transaction when executing explain

### ISSUE THREAD

**Issue by ionutursuleanu** [dbeaver/dbeaver#11289]
#### System information: 
- macOS Catalina 10.15.7
- dbeaver 7.3.4

#### Connection specification:
- PostgreSQL 11.9

#### Describe the problem you're observing:
Smart commit starts a transaction when executing explain
#### Steps to reproduce, if exist:
Run ```explain select 1;```

**Comment by uslss** [comment]
thanks for the report

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
