### ISSUE TITLE
Missing the enclosing quotation mark on JSON type field of MySQL

### ISSUE THREAD

**Issue by cytsunny** [dbeaver/dbeaver#11281]
#### System information: 
- **Operating system (distribution) and version**: Ubuntu 20.04, but I believe other OS should reproduce the error
- **DBeaver version**: DBeaver 7.3.4, but I believe other older version should be able to reproduce the error
- **Additional extensions**: none

#### Connection specification:
- **Database name**: MySQL
- **Driver name** InnoDB
- **Do you use tunnels or proxies (SSH, SOCKS, etc)?**  I am able to reproduce the error with or without SSH tunnel

#### Describe the problem you're observing:
When exporting data from table as INSERT SQL, the enclosing quotation mark is missing for JSON type field.
The same error also exists when choosing a row and choose "Generate SQL > INSERT".
"Advance copy > Copy as SQL" don't have this problem though.

#### Steps to reproduce, if exist:
Create a table with JSON type field and insert some fake data. Then, export the table as INSERT SQL

#### Include any warning/errors/backtraces from the logs
none

**Comment by LonwoLonwo** [comment]
Thanks for the bug report!

**Comment by LonwoLonwo** [comment]
Fixed in 7.3.5

**Comment by kseniiaguzeeva** [comment]
Single quotes are added.
