### ISSUE TITLE
Cannot enter a backslash in a query, instead a prompt to fetch all lines appears (German keyboard layout)

### ISSUE THREAD

**Issue by maffe** [dbeaver/dbeaver#11283]
#### System information: 
- Windows 10 64 Bit (German)
- DBeaver 7.3.4
- Keyboard layout: German/QWERTZ (Deutsch IBM)

#### Connection specification:
- Server: PostgreSQL 11.3
- Driver name: PostgreSQL JDBC Driver 42.2.8
- Access via SSH tunnel defined in DBeaver

#### Describe the problem you're observing:
When trying to enter a backslash, I’m asked to confirm fetching all lines. I have to enter the backslash in an external application and copy it from there. Entering a backslash is done via `Alt Gr` + `ß`, see https://en.wikipedia.org/wiki/German_keyboard_layout#/media/File:KB_Germany.svg, top line, third key from the right.

Note: In most cases (the exception being games and other programs with more direct keyboard access), Windows does not differentiate between `Alt Gr` and `Ctrl` + `Alt`.

#### Steps to reproduce, if exist:
- Select some data from table `invoice`: execute `SELECT * FROM invoice` (this step is required; the table exists and is not empty)
- Change query to `SELECT * FROM invoice WHERE address LIKE '%'` and try to enter a backslash (`\`) after the percent sign
- Backslash is not entered, instead a prompt appears: 
![grafik](https://user-images.githubusercontent.com/515302/107535832-67d7fb00-6bc1-11eb-8d6b-fbf700a183c8.png)

#### Include any warning/errors/backtraces from the logs
No log entries occur in this case

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by flambchap** [comment]
`Fetch all lines` shortcut has been changed to `CTRL+SHIFT+=`.

**Comment by kseniiaguzeeva** [comment]
verified
