### ISSUE TITLE
Task management UI improvements

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#11304]
- Turn task edit wizard into multi-page dialog (similar to the connection editor)
- Move "Save" button to the main buttons bar
- Show notification on task save
- Task name is optional on the first page of task wizard. If not specified then ask task name during save
- Show sub-tasks in the tree, support dnd and copy-paste
- Make last task wizard page the same for all tasks (log view).

**Comment by Matvey16** [comment]
1. Can't create import task in task creation wizard

![image](https://user-images.githubusercontent.com/82543000/137856261-6a4b4a65-329a-402a-9e18-6509c169353b.png)

2. Exporter settings can't be saved when task is edited

![j4GDwAHSc1](https://user-images.githubusercontent.com/82543000/137856659-a2a3d956-4525-40fb-8f1c-0e9fa3d9e174.gif)

3. Settings are not checked with green checkmarks when editing already working task 
4. Unnecessary checkmarks when editing connection

![dbeaver_1kNDLalpyU](https://user-images.githubusercontent.com/82543000/137857077-9679ed70-8bf6-4581-9824-4a8a5ff63b75.png)

**Comment by serge-rider** [comment]
1-4 Fixed

**Comment by DariaMarkaryan** [comment]
![image](https://user-images.githubusercontent.com/43252954/138064875-de320f34-b0af-4961-bfd0-d3782d77301b.png)
Bug: there should be an OK button in place of the Finish button

**Comment by Matvey16** [comment]
`Next` button in backup task is deactivated when it shouldn't be. Only reproducible if opened by right-clicking on database in PostgreSQL connection 

![ZYj631aFOP](https://user-images.githubusercontent.com/82543000/138105168-68342afc-13be-486b-a787-28f89f85814b.gif)

**Comment by serge-rider** [comment]
Fixed.

Additionally data insert performance was a bit improved + CSV read performance was significantly improved.

**Comment by Matvey16** [comment]
Verified
