### ISSUE TITLE
Create Varchar column has wrong default syntax in UI

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11309]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.5 EA

#### Connection specification:
- Database name and version MySQL

#### Steps to reproduce, if exist:
1. Open Columns tab in a table properties
2. Create a column of varchar type without adding anything to default settings.

Expected: SQL statement with full varchar definition appears and the new column is created
Actual result: 
- the column cannot be created, 
- the error about wrong SQL syntax appears. 
- Varchar definition is missed in the SQL statement:

ALTER TABLE test_review.test_copy ADD column1 **varchar NULL;** (has to be **varchar (some_numbers) NULL**)

**Comment by LonwoLonwo** [comment]
Varbinary type has to be also with parameters.

**Comment by LonwoLonwo** [comment]
Doesn't work since at least version 7.3.0

**Comment by LonwoLonwo** [comment]
Fixed in 21.0.0
Now the default type when creating a new column is varchar. Actual for Oracle also.

**Comment by kseniiaguzeeva** [comment]
verified
