### ISSUE TITLE
never allow to switch db connection for a tab with simple left-click or right-click on different connection in database navigator

### ISSUE THREAD

**Issue by mzatko** [dbeaver/dbeaver#11307]
#### System information: 
- Ubuntu 20.04
- DBeaver 7.3.4

#### Connection specification:
- Database name: oracle, mysql, mariadb, postgresql, ...  I think it doesn't depend on DB

#### Describe the problem you're observing:

simple click on any connection in database navigator associates it to actually opened tab. It even opens connection in database navigator if not already connected.
I find it as really dangerous behavior.

#### Steps to reproduce, if exist:

see ^

expected behaviour:
 No action on simple click at any connection in database navigator. On right click context menu, ofc.
 Double click needed to open new connection or action from context-menu. In case of double click, new connection will be assigned to new tab, never to already open tab.
No easy way to change connection for existing tab is needed. In fact it is unwanted.

**Comment by kseniiaguzeeva** [comment]
Most probably you have enabled option Auto-sync connection with Navigator. Try to disable it.
![Screenshot 2021-02-18 at 12 48 21](https://user-images.githubusercontent.com/51405061/108338785-b1d76700-71e7-11eb-8737-f9f4ccd048ca.png)

**Comment by mzatko** [comment]
Oops, I didn't change this setting as far as I remember. I didn't even notice it exist. However I cannot be perfectly sure, of course...
Thank you very much, Ksenia.
Closing the issue...
