### ISSUE TITLE
App hangs in case of starting export from DB to DB in data editor toolbar

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#11300]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.3.5

#### Describe the problem you're observing:
App hangs time to time in case of starting export from DB to DB in the data editor toolbar.
Probably side effect of #11118 .
#### Steps to reproduce, if exist:
1. Open any table
2. Start export to db from the toolbar in data editor

Actual result:
Application doesn't respond.

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
