### ISSUE TITLE
[Oracle] Enable/disable triggers from GUI

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#11312]
**Is your feature request related to a problem? Please describe.**
To enable or disable table triggers, I need to write the sql statement myself. E.g.

alter trigger MY_TRIGGER     enable;
alter trigger MY_TRIGGER     disable;

**Describe the solution you'd like**
To be able to do it from GUI with an easy button/checkbox.
As a plus, it would be nice to be able to enable multiple triggers at once by selecting them in Database navigator -> Table Triggers and right clicking, but that can become a separate FR if harder.

**Additional context**
This was already requested in #3374, but unfortunately that feature request for Oracle was hijacked by Postgres!

**Comment by LonwoLonwo** [comment]
We can do it! Thanks for suggestion

**Comment by LonwoLonwo** [comment]
Implemented in DBeaver 21.0.4
Will be available at 2021-05-03

You can find disable/enable trigger tool in Navigator Tree. 

![2021-04-27 09_57_12-DBeaver Enterprise 21 0 4 - customer_dimension](https://user-images.githubusercontent.com/45152336/116199352-b10b0600-a73f-11eb-86bb-6e95faacb3da.png)

Tool can be used for one or many triggers.

![2021-04-27 09_57_56-DBeaver Enterprise 21 0 4 - customer_dimension](https://user-images.githubusercontent.com/45152336/116199473-d4ce4c00-a73f-11eb-9a39-a54d74a23eb3.png)

You can also find tool in Database Task menu and it can be created as a task:
![2021-04-27 09_58_18-DBeaver Enterprise 21 0 4 - customer_dimension](https://user-images.githubusercontent.com/45152336/116199824-3abad380-a740-11eb-87b3-afc7ffa44b2e.png)

![2021-04-27 09_58_55-DBeaver Enterprise 21 0 4 - customer_dimension](https://user-images.githubusercontent.com/45152336/116199825-3b536a00-a740-11eb-8e6b-86444eb08d04.png)

**Comment by uslss** [comment]
verified
