### ISSUE TITLE
Improve objects and sessions tool filtering on client side

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#11314]
**Is your feature request related to a problem? Please describe.**
Currently the sessions tool uses a very custom table with limited options

**Describe the solution you'd like**
If the sessions tool used the standard table editor, we would get nice features, like per-column filtering, grouping panel, etc...

**Describe alternatives you've considered**
Just allowing per-column filters instead of a single filter applied to all columns would be a good improvement, a new FR can be opened for the rest of the features.

**Additional context**
I'm particularly interested about the Oracle version of this, don't know for other databases. Since for Oracle sessions are basically the result of a single query, presenting them with the default resultset viewer should be feasible.

**Comment by kseniiaguzeeva** [comment]
We will implement it, but most likely only at the end of the spring. Upcoming releases are overloaded.

**Comment by p91paul** [comment]
fair enough! keep with the good work!

**Comment by serge-rider** [comment]
I don't want to redesign session manager view. Moreover it alread ycontaisn simpel session filter (ctrl+f).
But we could make it easier - add a button which will open SQL query results for session read query. It will work only for those databases which use SQL to read sessions.

![image](https://user-images.githubusercontent.com/6398845/117543842-266fb400-b027-11eb-92ac-3413a955dcf7.png)
![image](https://user-images.githubusercontent.com/6398845/117543848-34253980-b027-11eb-88b9-353c138dfd23.png)

**Comment by p91paul** [comment]
I dunno, I wouldn't use that feature.
The query itself contains too much columns. Also, clicking on a row in the session manager shows details like execution plan, long ops, etc that wouldn't be available with your solution.
I'm mostly interested in a filter acting on each column separately instead of globally.

**Comment by serge-rider** [comment]
@p91paul You can configure visible columns in session manager by clicking on the table header->Configure columns.
Also by clicking on the search icon (ctrl+f) you activate table filter which searches in all columns.

However per-column filter is not available. Is it the only thing which you miss in the session manager?

**Comment by p91paul** [comment]
@serge-rider basically yes, per column filter is what I'm missing!

**Comment by serge-rider** [comment]
I think we should add per-column filters for all object lists (e.g. metadata editor).

**Comment by LonwoLonwo** [comment]
So, in conclusion.

When working with the session manager, you have some additional options.

1. You can disable (hide) any columns in the "Configure Columns" dialog.

![2021-12-24 00_04_02-DBeaver Ultimate 21 3 2 - Sessions - MySQL 8 0](https://user-images.githubusercontent.com/45152336/147291693-06d4eb90-3dcf-4c1b-974f-f1dcc7a819b6.png)

2. You can open data from the session manager in the SQL Editor as a table with the help of the "SQL" button.

![2021-12-24 00_04_41-DBeaver Ultimate 21 3 2 - Sessions - MySQL 8 0](https://user-images.githubusercontent.com/45152336/147291776-f3fbd425-0139-415a-8f64-beb46487bc48.png)

3. And our new feature - the ability to use column grouping. It will be available in the 21.3.2 DBeaver version.

![2021-12-20 17_23_49-DBeaver Ultimate 21 3 1 - airports_data](https://user-images.githubusercontent.com/45152336/146782286-e765528d-2290-493a-8dc4-4512bac3a73b.png)

![2021-12-20 17_24_15-DBeaver Ultimate 21 3 1 - Sessions - postgres 13 3](https://user-images.githubusercontent.com/45152336/146782289-b8d6ab14-cdda-466f-a23d-355b012ca38e.png)

I think that at this moment the ticket can be considered as solved. If you have new ideas, feel free to open a new ticket.
