### ISSUE TITLE
Saving a change when connection is marked as "production" doesn't persist

### ISSUE THREAD

**Issue by thomasmoors** [dbeaver/dbeaver#11311]
#### System information: 
- Windows 10 Pro 19042.804
- DBeaver 7.3.4.202101311042
- Additional extensions: none

#### Connection specification:
- Database name: mysql  Ver 14.14 Distrib 5.7.24, for Win64 (x86_64)
- Driver name: mariadb (yes small mistake)
- No tunnels 
I specified it as production

#### Describe the problem you're observing:
When saving the data I click "Save"
![image](https://user-images.githubusercontent.com/486765/107752848-94a22480-6d1f-11eb-8a23-cb2e3d8c1092.png)
The data looks changed in the "Data" tab, this is not true.

However queries and a secondary database client show the data as not updated

**Comment by p91paul** [comment]
after saving, did you also commit?

**Comment by thomasmoors** [comment]
> after saving, did you also commit?

Could it really be this simple? 🤦‍♂️

**Comment by p91paul** [comment]
I think across different databases and different clients, this might be the most common mistake of them all, everybody does that at least several times :stuck_out_tongue_winking_eye:
