### ISSUE TITLE
Grouping pane error if the query ends with a comment

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#11313]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.3.4.202101311042
- Additional extensions: n/a

#### Connection specification:
- Database name and version: Oracle
- Driver name: ojdbc 19
- Do you use tunnels or proxies (SSH, SOCKS, etc)? n/a

#### Describe the problem you're observing:
If the last line of the query is a comment, using the grouping panel will lead to an error

#### Steps to reproduce, if exist:

Run this query:
```
SELECT * FROM dual
-- comment
```

Drag the "DUMMY" column to the grouping panel; the following invalid query will be generated (closing parenthesis gets commented out):

```
SELECT DUMMY, COUNT(*) FROM (
SELECT * FROM dual
-- comment) src
GROUP BY DUMMY
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the report @p91paul

**Comment by flambchap** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified
