### ISSUE TITLE
PostgreSQL Task script shows Success status when its script file doesn't exist

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11324]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.5 EA
- PostgreSQL
#### Steps to reproduce, if exist:
1. Save a script file somewhere
2. Create a script task with this script file
3. Delete the file
4. Execute the task

**Expected**: an error appears
**Actual result**: no errors, success status is displayed

**Comment by ShadelessFox** [comment]
Cannot reproduce:

![image](https://user-images.githubusercontent.com/35821147/116552825-232b4880-a902-11eb-9c23-dbb97c1b1f6a.png)

**Comment by ShadelessFox** [comment]
Reproducible with external file.

**Comment by serge-rider** [comment]
How can I create task with external SQL file?

**Comment by ShadelessFox** [comment]
In case of PosgreSQL, you can create a task called <kbd>PostgreSQL script</kbd>. Here, you can specify path to external file.

To be quite honest, I don't see the point of having such task (it is also present for Oracle and some other DBs), since we have a task <kbd>Execute SQL script</kbd> which serves the same purpose.

**Comment by serge-rider** [comment]
PostgreSQL script is a very different task. It makes a lot of sense as it executes PostgreSQL-specific SQL scripts with pragmas and other stuff. DBeaver SQL parser doesn't support it (and probably never will).

So, I still can't reproduce the problem.
@kseniiaguzeeva please attach some screenshot or video.

**Comment by ShadelessFox** [comment]
https://user-images.githubusercontent.com/35821147/117549187-99862400-b041-11eb-8366-a53f7d3c2a91.mov

**Comment by Matvey16** [comment]
Verified
