### ISSUE TITLE
Statistics info is not displayed in DB Navigator with Custom view>Hide folders

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11322]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.5 EA

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
Connect to PostgreSQL and enable statistics info, Custom view>Hide folders

**Expected**: statistics info is displayed for tables
**Actual result**: statistics is not displayed.

**Comment by flambchap** [comment]
Statistics info is not shown when the navigator tree has a horizontal scrollbar, and the `Hide folders` option causes the navigator to be wider than usual, especially with Postgres.
