### ISSUE TITLE
Functional words are highlighted as hyperlinks in SQL Editor

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11323]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.5 EA

#### Steps  reproduce, if exist:
1. Open a script in SQL Editor (e.g. a table DDL)
2. Hold Ctrl and move the cursor from a table name along the text.

Expected: only tables and views are highlighted
Actual result: functional words are highlighted as hyperlinks when the cursor on them after highlighting a table

https://user-images.githubusercontent.com/51405061/107785053-2bd99d00-6d5d-11eb-830e-e7cedcc3cca6.mp4

**Comment by uslss** [comment]
duplicates #11158
