### ISSUE TITLE
[Oracle] Allow excluding synonyms from "Open database object"

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#11327]
**Is your feature request related to a problem? Please describe.**
Currently dbeaver issues the following query when searching with ctrl + D (the first letter I wrote is C):

```sql
SELECT  DISTINCT OWNER,OBJECT_NAME,OBJECT_TYPE FROM    (SELECT OWNER,OBJECT_NAME,OBJECT_TYPE FROM ALL_OBJECTS WHERE OBJECT_TYPE IN ('TABLE','PACKAGE','PROCEDURE','FUNCTION','SYNONYM','SYNONYM') AND UPPER(OBJECT_NAME) LIKE '%C%' UNION ALL
SELECT  O.OWNER,O.OBJECT_NAME,O.OBJECT_TYPE
FROM ALL_SYNONYMS S,ALL_OBJECTS O
WHERE O.OWNER=S.TABLE_OWNER AND O.OBJECT_NAME=S.TABLE_NAME AND S.OWNER='PUBLIC' AND UPPER(S.SYNONYM_NAME)  LIKE '%C%')
ORDER BY OBJECT_NAME
```
That query is terribly slow. On one of my production databases it takes more than 1 minute to complete

**Describe the solution you'd like**
Allow to exclude synonyms from that query with another checkbox. The query could then be rewritten as:
``` sql
SELECT OWNER,OBJECT_NAME,OBJECT_TYPE FROM ALL_OBJECTS 
WHERE OBJECT_TYPE IN ('TABLE','PACKAGE','PROCEDURE','FUNCTION') AND UPPER(OBJECT_NAME) LIKE '%C%'
```
This query takes some milliseconds to complete on the same system.

**Describe alternatives you've considered**
Using database navigator. Also, one of the problems is that the search starts as soon as I type the first letter; if I copy-paste an entire object name the result comes up much faster.

**Comment by kseniiaguzeeva** [comment]
We are going to implement it. While please try to change Oracle properties in connection settings as a workaround.
![Screenshot 2021-02-18 at 13 02 13](https://user-images.githubusercontent.com/51405061/108340388-966d5b80-71e9-11eb-9086-5c029cb4204f.png)

**Comment by flambchap** [comment]
DBeaver excludes the synonyms already, so I added an option to enable them back again. You can find the option on the connection properties page.

**Comment by Matvey16** [comment]
Verified

**Comment by p91paul** [comment]
Checked, performance is terrific when you have DBA views available (basically realtime), much improved when you don't (it heavily depends on which letter you type first and how many objects start with that letter).
Waiting a couple hundreds milliseconds before hitting the database to let the user type a few characters might be a further UX improvement.
Thank you, great job!!
