### ISSUE TITLE
Navigate filter buttons in Data Editor have to show full navigate/filter history

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11325]
Current behaviour: filter history removes if a user navigates a link and vise versa

**Comment by serge-rider** [comment]
Can't reproduce. Please attach some video.

**Comment by uslss** [comment]
not reproducible anymore
![image](https://user-images.githubusercontent.com/31996417/133094466-98b2cb73-4584-457b-b047-42126a2fa868.png)
