### ISSUE TITLE
Aliased field in results pane gets data type of field of same name in the table

### ISSUE THREAD

**Issue by ericflightaware** [dbeaver/dbeaver#11326]
#### System information: 
- Windows
- dbeaver 7.3.2.202101032114

#### Connection specification:
- PostgreSQL 11.6

#### Describe the problem you're observing:
This is admittedly a subtle edge case. If you do a SELECT query against a table and alias a field in the query to the same name as another field in the underlying table, the results pane viewer/editor UI seems to assume the field is of the data type of the underlying actual field (not the aliased field). This is noticeable, for example, when the actual underlying named field is an integer type but you are aliasing a varchar field to its name. Thus, the varchar field assumes the integer type in the editor which causes the value to display incorrectly and not be editable in the results pane grid.

#### Steps to reproduce, if exist:
Sample query:
```
CREATE TABLE my_table (
id int4 not null,
foo varchar not null
);
INSERT INTO my_table ( id, foo ) VALUES ( 1, 'test' );
SELECT foo as id 
FROM my_table;
```

**Comment by uslss** [comment]
thanks for the report
duplicates #11143
