### ISSUE TITLE
Toolbar is disabled in resultset after query execution

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#11332]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.3.5 EA

#### Describe the problem you're observing:
Resultset Toolbar is disabled after query run. It is needed to switch to another tab and back to enable it.
#### Steps to reproduce, if exist:
1. Connect to some DB
2. Choose some table and in it, context menu choose Read data in SQL Editor
3. Check resultset toolbar - all buttons are greyed out

Similar behavior appears in case of running query in SQL editor

![2021-02-13_16h39_26](https://user-images.githubusercontent.com/31996417/107851413-bb915100-6e1a-11eb-9bd4-6468bd954d3b.gif)
![image](https://user-images.githubusercontent.com/31996417/107851425-d5329880-6e1a-11eb-8b47-81d358f5ba36.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
