### ISSUE TITLE
Serial type has wrong data for insert in Data Editor

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11337]
#### Syste information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.5 EA

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
1. Open a table with serial column type and insert a row
Expected: the value is auto-assigned in serial column
Actual result: text appears:
![dbeaver_mOfN6uooFw](https://user-images.githubusercontent.com/51405061/107872425-5ccfe400-6ebb-11eb-861d-d2b09518f96b.png)
Note: also Generate SQL offers to insert Null

**Comment by LonwoLonwo** [comment]
A value in the field is correct - this is a sequence that will create a new value for this column.
But it's confusing, apparently.
Someday we will come up with something to replace it with.
