### ISSUE TITLE
"Detect unique identifiers" takes tens of seconds for each new query (Postgre).

### ISSUE THREAD

**Issue by gavenkoa** [dbeaver/dbeaver#11338]
When I start query execution DBeaver writes first __Detect unique identifiers__ and spend 10-15s, then actually executes query.

There is a button "Cancel" to interrupt that process. After pushing it and around 5s delay I see alert: __Database driver is not responding. Do you want to cancel request and close connection?__. I chose no and got response a bit later.

What feature "Detect unique identifiers" enables? Can I disable probing of "unique identifiers"?

I cannot find such option, similar option was mentioned here: https://github.com/dbeaver/dbeaver/issues/5633

My Postgre is `PostgreSQL 9.6.10 on x86_64-alpine-linux-musl, compiled by gcc (Alpine 6.3.0) 6.3.0, 64-bit` running inside VirtualBox (Vagrant).

I see similar tips (other messages appear, like "Load TableCache", etc) appear when I connect to Google Cloud Managed Postgre 11 but it takes fraction of seconds to finish.

I updated DBeaver Version 7.3.4.202101311042 from `scoop install dbeaver`. Same behavior is with old Version 6.2.2.201910072100

**Comment by gavenkoa** [comment]
Here is an example of total progress for fresh connection:

![image](https://user-images.githubusercontent.com/273770/107876459-c9081300-6ece-11eb-9b28-d851d18265b1.png)

Execution of the next query results in:

![image](https://user-images.githubusercontent.com/273770/107876482-edfc8600-6ece-11eb-96dd-0626d9c681ca.png)

**Comment by kseniiaguzeeva** [comment]
1. Could you please see which query gives so long execution time (Window>Show view>Query manager)?
![Screenshot 2021-02-18 at 13 11 46](https://user-images.githubusercontent.com/51405061/108341648-ec8ece80-71ea-11eb-89e0-ebf1f0d38e09.png)

2. Try to disable **Read table metadata** and **Read table preferences** in Preferences>Data Editor
![Screenshot 2021-02-18 at 13 13 34](https://user-images.githubusercontent.com/51405061/108341902-3a0b3b80-71eb-11eb-8e09-db08885779c1.png)

Even if disabling options helps, I will be glad to receive the query from Query manager and investigate it.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info

**Comment by gavenkoa** [comment]
Hi! 

> Read table metadata and Read table preferences in Preferences>Data Editor

Disabling above removed reported slowness.

> Window>Show view>Query manager

It wasn't obvious that I have to tick "Meta" option to display meta queries.

So I open the tab for table by double clicking on table and following query takes 10-11 sec:

```
SELECT i.*,i.indkey as keys,c.relname,c.relnamespace,c.relam,c.reltablespace,tc.relname as tabrelname,dsc.description,pg_catalog.pg_get_expr(i.indpred, i.indrelid) as pred_expr,pg_catalog.pg_get_expr(i.indexprs, i.indrelid, true) as expr,pg_catalog.pg_relation_size(i.indexrelid) as index_rel_size,pg_catalog.pg_stat_get_numscans(i.indexrelid) as index_num_scans
FROM pg_catalog.pg_index i
INNER JOIN pg_catalog.pg_class c ON c.oid=i.indexrelid
INNER JOIN pg_catalog.pg_class tc ON tc.oid=i.indrelid
LEFT OUTER JOIN pg_catalog.pg_description dsc ON i.indexrelid=dsc.objoid
WHERE  i.indrelid=270505 ORDER BY c.relname
```

The query is repeated for each opened table Data with same 10 sec delay.

**Comment by rodrigobahiense** [comment]
I'm having the same issue connecting to a localhost (127.0.0.1) database after installing a VPN.

Disabling the VPN or the config "Read table metadata" solves the issue; still, I'd rather have it working as intended.

I'm using the Community Edition on Linux (Fedora 35).

Is there any debug flag/option I can use to investigate further? It seems like flat 10 seconds are added to the queries, so it looks like a default timeout for some operation.

**Comment by elektro-wolle** [comment]
I've tried the statement directly on the database and can confirm the ten seconds. But without the `pg_stat_get_numscans` expression the execution is instant (50ms).

**Comment by skannan-maf** [comment]
Saved me tons of time. Been waiting for years to find a way to disable this. Thanks for showing the "screenshot" well!

**Comment by WinnerOK** [comment]
For newer DBeaver the setting was moved under `Preferences -> Connections -> Metadata -> Do not read tables information in SQL and data editors`

<img width="1974" height="818" alt="Image" src="https://github.com/user-attachments/assets/47841a94-214e-4fb3-b9de-6b3b2a6ab9c7" />

Also available as per datasource setting: `Edit Connection -> Metadata -> Do not read tables information in SQL and data editors`
