### ISSUE TITLE
Table cannot be created in non-default database, if the database is set as default in Initialization

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11336]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.5 EA

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
1. set a database as default in connection settings>Initialization
2. set another database as default in DB Navigator tree
3. try to create a table in the database (mentioned as default in connection settings>Initialization)

**Expected**: the table is created
**Actual result**: the cannot be created and error appears "schema doesn't exists"
**Workaround**: make the database default.

**Comment by kseniiaguzeeva** [comment]
Cannot be reproduced anymore

**Comment by akilovich** [comment]
It can be easily reproduced by using the steps you've provided above.

**Comment by flambchap** [comment]
The problem is reproducible. More than that, after steps 1 and 2 navigator tree starts to lie.

**Comment by kseniiaguzeeva** [comment]
verified
