### ISSUE TITLE
In table properties edit mode, I want to be able to move multiple columns up and down the list at once.

### ISSUE THREAD

**Issue by DeflateAwning** [dbeaver/dbeaver#11331]
**Is your feature request related to a problem? Please describe.**
When I am re-ordering columns in the Table Properties configuration, I want to be able to select multiple columns and move them all at once using the arrow keys in the bottom right corner.

**Describe the solution you'd like**
When multiple columns (shown as rows in this view) are selected, I want to be able to click the Up and Down arrows to move them.

**Alternatives**
The only way to accomplish this currently is to move them all one by one.

**Additional context**
![image](https://user-images.githubusercontent.com/11021263/107845262-72e48400-6d97-11eb-926c-dbfcfd7f35f4.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. We will implement it.

**Comment by ShadelessFox** [comment]
Implemented:

https://user-images.githubusercontent.com/35821147/115244137-5284cd00-a12c-11eb-8fd6-a575bcef8811.mp4

**Comment by DeflateAwning** [comment]
That's awesome, I'm very impressed!

How does this behave if you select multiple non-consecutive "columns" (shown as rows)? For example, you select Column1, Column3, and Column5, and then try to move them?

**Comment by ShadelessFox** [comment]
Like as you would expect, but I haven't tested that behavior when moving rows **down**, and it needs more tweaking, ha-ha 😅

https://user-images.githubusercontent.com/35821147/115670294-ed122580-a351-11eb-8430-85b864b191b1.mp4

**Comment by ShadelessFox** [comment]
Now it works as expected:

https://user-images.githubusercontent.com/35821147/115709833-560d9380-a37a-11eb-83be-42516bb511fa.mp4

**Comment by DeflateAwning** [comment]
Looks excellent, thank you!

**Comment by uslss** [comment]
verified
