### ISSUE TITLE
Highlighting support for [[..]] string literals in Lua scripts

### ISSUE THREAD

**Issue by allipatev** [dbeaver/dbeaver#11330]
**Is your feature request related to a problem? Please describe.**
Now for Exasol DBeaver does not highlight strings delimited by double square brackets [[...]].
It leads to strange effects:
![image](https://user-images.githubusercontent.com/58830344/107799937-698af580-6d5e-11eb-84aa-43e4e05de0ac.png)
Script in the text form for your convenience:
```lua
CREATE OR REPLACE SCRIPT TEST.TEST_SCRIPT() returns ROWCOUNT AS

table_name = 'SOME_TABLE'

query([[
select 'this is my long
multiline
query that is not properly highlighted' from schema_name."]]..table_name..[["]])
/
```
**Describe the solution you'd like**
Strings delimited by single quotes and double quotes are already highlighted.
So I believe it's worth adding highlighting of strings delimited by double square brackets [[...]] in the same way.
May be it's possible to assign another color to the [[..]] literals though.

**Describe alternatives you've considered**
[[..]] string literals are the part of the language grammar, so it needs to be done somehow.

**Additional context**
Notepad++ highlighting in this case:
![image](https://user-images.githubusercontent.com/58830344/107800478-19f8f980-6d5f-11eb-9f8b-cbb228a18ff9.png)

**Comment by Sargul** [comment]
added dialect implementation for double square brackets
pre dialect rule:
![image](https://user-images.githubusercontent.com/5595511/108115732-d3770800-709a-11eb-9000-d9175cdc19ff.png)
post dialect rule:
![image](https://user-images.githubusercontent.com/5595511/108115772-dffb6080-709a-11eb-8758-11d382654cb6.png)

**Comment by uslss** [comment]
verified
