### ISSUE TITLE
Database>Tasks menu doesn't update used task info in the list

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11335]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.5 EA

#### Steps to reproduce, if exist:
1. Create several tasks
2. Execute some of them
3. Create a task again and execute it.

**Expected**: the task list is refreshed in Database>Tasks menu
**Actual result**: the task list is not refreshed
![1](https://user-images.githubusercontent.com/51405061/107871896-d7e2cb80-6eb6-11eb-8309-3e2222368cb7.png)

**Comment by ShadelessFox** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/35821147/116681915-4283ad80-a9b6-11eb-9d68-20fcd2f6244e.png)

**Comment by kseniiaguzeeva** [comment]
Some action is needed with tasks to see the task list after relaunching DBeaver.

https://user-images.githubusercontent.com/51405061/117636855-e4ab4e80-b189-11eb-87ac-23b7128adccd.mp4

**Comment by ShadelessFox** [comment]
Can't reproduce. Perhaps tasks eventually will appear after some time?
