### ISSUE TITLE
Ver 7.3.5 issues

### ISSUE THREAD

**Issue by Shallyz** [dbeaver/dbeaver#11342]
Hi,

There are several issues that I would like to know if there's a way to solve them.

1. From time to time when you are updating the version, after the update all the open files are gone and I have to reopen them. Is is a bug on the installation that is not keeping the open files as they were before the upgrade? Because usually it works fine.
2. How to change the the default open and save will be a folder that i want and not what is selected on the Workspaces? I couldn't find a way to change it.
3. I've notice today that when I type Hebrew it's not working properly. Hebrew is a 'Right to Left' language, and when typing a word in Hebrew and then pressing space to type the next word, the editor put the next word to the right of the previous word and not to the left (like it's left to right typing). It used to work fine before.
4. One more issue with the Hebrew, when saving the file and doing search on the windows for words written in Hebrew in the sql file the windows doesn't recognizing the words (unlike if you save a text file with Hebrew words and search for those words the windows search tool find them).

In general I would like to say that this is an excellent software to work with databases, really amazing!

Keep on the great work.

Many Thanks,
Shally

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
Hi @Shallyz ,
1. Did you choose Reset UI in the installer during upgrading?
2. As I can see, the last used folder is used for file saving/opening. Or do you mean some special case?
3-4. #10911 issue is already created.

**Comment by Shallyz** [comment]
Hi,
1. No, I always make sure that the reset won't be checked. I think it happens if I do install and not closing the application, so the installation stopped and waiting for me to close the application and then continue (this is what happened last time when it happens). 2. Every time I open the application, at the first time it goes to C:\Users\shally.zarzar, how can I change that?
Thanks
    On Tuesday, February 16, 2021, 06:25:21 PM GMT+2, Dziyana <notifications@github.com> wrote:  
 
 


Hi @Shallyz ,
   
   - Did you choose Reset UI in the installer during upgrading?
   - As I can see, the last used folder is used for file saving/opening. Or do you mean some special case?   
3-4. #10911 issue is already created.

**Comment by uslss** [comment]
1. Cannot reproduce this against recent version - if the issue reproduces in the future, please open a new ticket related to it.
2. You can change the default workspace in Main menu: File - Switch workspace - Other
