### ISSUE TITLE
Error connecting AWS Redshift: Invalid operation: column t.typcategory does not exist;  

### ISSUE THREAD

**Issue by vmpaivin** [dbeaver/dbeaver#11348]
#### System information: 
Windows 10 64-bit
- DBeaver version 7.3.5.
- Additional extensions n/a

#### Connection specification:
- Database name and version AWS Redshift 
- Driver name https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.45.1069/RedshiftJDBC42-no-awssdk-1.2.45.1069.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
 this happens every time when logging in to aws redshift with dbeaver 7.3.5 on windows 10 64-bit.

SQL Error [500310] [42703]: [Amazon](500310) Invalid operation: column t.typcategory does not exist;
  [Amazon](500310) Invalid operation: column t.typcategory does not exist;
  [Amazon](500310) Invalid operation: column t.typcategory does not exist;

**Comment by uslss** [comment]
#11353

**Comment by LonwoLonwo** [comment]
We fix it.

As a workaround for now: 
Enable this checkbox
![2021-02-15 16_38_19-Connection _dev 2_ configuration](https://user-images.githubusercontent.com/45152336/107953516-4bb2d000-6fac-11eb-8a3d-38194eb7043f.png)

**Comment by vmpaivin** [comment]
Good tip, thanks!

**Comment by LonwoLonwo** [comment]
Fixed.
Version 7.3.5 was re-released (can be downloaded from dbeaver.io)
