### ISSUE TITLE
Enable nested comments support for ClickHouse

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/dbeaver#11347]
I didn't find a switch to turn on nested support in preference, so I guess ClickHouse plugin should be enhanced like [this one](https://github.com/dbeaver/dbeaver/blob/7.3.5/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreDialect.java#L840).

I use below SQL for testing, and the highlight is correct when connecting to PostgreSQL but not ClickHouse.
```sql
select /*0/*1*/2*/3
```

**Comment by uslss** [comment]
thanks for the suggestion.
Hope it will be implemented in the nearest future

**Comment by ShadelessFox** [comment]
Hello @zhicwu,

I don't think ClickHouse supports nested comments.

Also, I can't find any mentions about it in the documentation:
https://clickhouse.tech/docs/en/sql-reference/syntax/#comments

Can you provide more information, please?

**Comment by zhicwu** [comment]
@ShadelessFox, it does support nested comments. Taking latest LTS version as an example:
``` bash
$ docker run --rm -it yandex/clickhouse-server:21.3 bash
root@af378ffcfa30:/# /entrypoint.sh >/dev/null 2>&1 &
[1] 45
root@af378ffcfa30:/# clickhouse-client
ClickHouse client version 21.3.12.2 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.3.12 revision 54447.

af378ffcfa30 :) select /*0/*1*/2*/3

SELECT 3

Query id: 75ad2e5a-dbe8-4241-a168-d7af2ec084b1

┌─3─┐
│ 3 │
└───┘

1 rows in set. Elapsed: 0.002 sec.

af378ffcfa30 :)
```

**Comment by ShadelessFox** [comment]
Huh, perhaps our QA database is a bit outdated (ClickHouse 20.4.4.18).

Thanks for quick response!

**Comment by zhicwu** [comment]
Thanks @ShadelessFox, please consider to update database to 21.3. Also you guys may want to revisit ClickHouse support - there's a timezone issue but let me enhance its JDBC driver first :p

Update: the feature was introduced in ClickHouse/ClickHouse#14655.

**Comment by uslss** [comment]
verified
