### ISSUE TITLE
Recent Sql Script does not open with CTRL + Enter while focus on Database Navigator

### ISSUE THREAD

**Issue by moesio** [dbeaver/dbeaver#11349]
#### System information: 
- Linux Ubuntu 18.04
- DBeaver Version 7.3.5.202102141704
- No extra extensions

#### Connection specification:
- SQLServer 2016, Postgres 10 and MariaDB 10
- Driver name: Microsoft JDBC Driver for SQL Server, PostgreSQL JDBC Driver, MySQL/MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
While focus is on Database Navigator, short cut CTRL+ Enter to open **Recent Sql Script**. Using mouse and menu works well.

#### Steps to reproduce, if exist:
Focus on Database Navigator, press shortcut CTRL + Enter

#### Include any warning/errors/backtraces from the logs
Nothing else

**Comment by moesio** [comment]
I'll try give more details about how reproduce.

- Open DBeaver 
- Keep view **Database Navigator** focused
- Navigate to a connection 
- Keep focus on a connection
- Press **CTRL + Enter**

It should open a **Recent Sql Editor**, as context menu indicates, but opens tree in that connection instead. The behaviour is as I press only **Enter**
If focus is on a database inside a tree of opened connection, that shortcut opens properties, not **Recent Sql Editor**

If I use context menu over any of item of that tree, connection or database, **Recent Sql Editor** goes right.

**Comment by uslss** [comment]
Hi @moesio ,
cannot reproduce it. Can you check keybindings in preferences?
![image](https://user-images.githubusercontent.com/31996417/108871782-8c44c600-760a-11eb-9fc1-6decb416ffe3.png)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info
