### ISSUE TITLE
Up and Down buttons in Data transfer mapping dialog behave awkwardly

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#11346]
When there are too many items in the tree to display at once, the scrollbar activates. When this scrollbar is not at the top position, moving an item up or down resets the scrollbar to the top. Quite ugly.

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
Items list is blinking in case of using Up button
![2021-02-20_12h30_03](https://user-images.githubusercontent.com/31996417/108591007-82effb00-7377-11eb-98b8-8ceed7aee633.gif)

**Comment by flambchap** [comment]
Fixed this problem as well.

**Comment by uslss** [comment]
verified
