### ISSUE TITLE
Boolean column values view. Textboxes-mode field customisation and COLOR

### ISSUE THREAD

**Issue by ghYura** [dbeaver/dbeaver#11345]
Please, consider following proposition that allows comfortable boolean-values differentiation among thousands of DB records, but ordered by other (say, non-boolean) prioritized columns. At the attached picture you can see custom text-inside-cell-value INDENTATION with whitespaces made by user text input and custom COLOR pick for 'textboxes' depicture mode.

Cell itself should stay clickable (as it already implemented before) to be able to change value in general DB Editor

#7787
#9327 
#10645 
#11190 

All for user viewing comfort :)
Best regards for DBeaver dev-n-test team as so as users.
#HighUsability

![DBeaver Boolean indentation color text](https://user-images.githubusercontent.com/42974628/107922302-7daa3f00-6f78-11eb-9ee1-51a641bab948.jpg)

**Comment by kseniiaguzeeva** [comment]
We will implement the feature. Thank you for not forgetting it.

**Comment by ghYura** [comment]
in addition:
Bold text would be more contrast for the eye

**Comment by ghYura** [comment]
Also, please, implement text assertional limitations against intentional malicious delusion input such cases as:
actual KEY : text VALUE depicted in cell for this mode

> true != false
> true != NULL
> true != faIse
...
> (NULL) != not null
> (NULL) != false
> (NULL) != true
...
> false != true
> false != NULL
...

in case insensitive text and any similar characters from other non-english language alpabets or Latin extended/Latin-1 Supplement characters i.e. 'tяие', 'truè' and spaces/underscores/special (group or combination of) characters among/between/before/after them, and so on...
I believe, your advanced testers could generate different such negative scenarios input. There is a bunch of negative delusion scenarios
@kseniiaguzeeva please, pay attention
Powerful regexp comparator probably required

**Comment by ghYura** [comment]
@tati-kru why do you keep postponing this feature?

**Comment by tati-kru** [comment]
@ghYura we do our best to close as much issues as possible, sometimes we need to move some issues to other milestones to make process more efficient.

**Comment by ghYura** [comment]
> @ghYura we do our best to close as much issues as possible, sometimes we need to move some issues to other milestones to make process more efficient.

Thanks for your feedback

**Comment by ShadelessFox** [comment]
> Also, please, implement text assertional limitations against intentional malicious delusion input such cases as:
> actual KEY : text VALUE depicted in cell for this mode
> 
> > true != false
> > true != NULL
> > true != faIse
> > ...
> > (NULL) != not null
> > (NULL) != false
> > (NULL) != true
> > ...
> > false != true
> > false != NULL
> > ...
> 
> in case insensitive text and any similar characters from other non-english language alpabets or Latin extended/Latin-1 Supplement characters i.e. 'tяие', 'truè' and spaces/underscores/special (group or combination of) characters among/between/before/after them, and so on...
> I believe, your advanced testers could generate different such negative scenarios input. There is a bunch of negative delusion scenarios
> Powerful regexp comparator probably required

@ghYura why do we need to overcomplicate it in a such weird way? If user decided to make his live harder by swapping <kbd>true</kbd> and <kbd>false</kbd>, it's his choice.

It will only make sense if you want to share your DBeaver configuration with others. And some may not like the textual representation of booleans. For example, I prefer the image-based one.

**Comment by ghYura** [comment]
> @ghYura why do we need to overcomplicate it in a such weird way? If user decided to make his live harder by swapping true and false, it's his choice.
> 
> It will only make sense if you want to share your DBeaver configuration with others. And some may not like the textual representation of booleans. For example, I prefer the image-based one.

@ShadelessFox 
1). in case if former co-worker leaves old config for company but no time to figure out whats wrong with 3rd party soft (in this case DBeaver RDBMS), that this is only option, while CI/CD
2). constant imrovement of anything (perfect code - unachievable, but worth to be aspired)
3). I agree that you prefer image-based one, other - strict boolean meaning, other - decorated. If you take a look at linked closed issues you will see that I came to idea of a very custom way for its depicture (by user taste). That's why we got this Feature request (satisfy as much user/customers taste as possible). :) 

Anyway, this is additional "Wish for the best for many cases as possible" sub-issue IMO, 
but custom |_____**text**| indentation in cell (in bold contrast for the eye to differ)
and its **color** picking (also contrast for thousands DB records)
are the core for this issue and highly desirable

**Comment by ghYura** [comment]
>  And some may not like the textual representation of booleans. For example, I prefer the **image-based one**.

https://user-images.githubusercontent.com/42974628/99234979-eeb54b80-27fd-11eb-8ea5-d3908f675b6f.jpg
(You cannot indent pictograms/icons relatively to other opposite logical-bool-value inside single boolean column and colorize them while image-based, can you? Custom whitespaced **bold text** and color contrast mode DOES this for any eye while viewing thousands of them. Multiply it if you use it all day/week/month and multiple boolean columns i.e.. Poor user's eyes. Amount of any contrast adjusted by particular user by his/her input. THIS is the main idea. Delusion scenarios are a look ahead to improve/protection against absolute illogical-nonsense)
P.S.: all users that don't like it - switch back to other View mode(s) or propose yours (aka - constant improvement and customisation philosophy) :)

**Comment by ShadelessFox** [comment]
Okay, I get it now. We'll see what we can do. Unfortunately, it's impossible to handle every case (e.g. your team speaks in other language and words for `true` and `false` are different, we don't want to involve translation API for that, of course).

You can't colorize image-based checkboxes, it's true. As of now, it's true for text-based checkboxes too. It's possible to allow colorization for image-based checkboxes by allowing user to adjust their hue individually, but that's a different story :)

**Comment by ghYura** [comment]
> Okay, I get it now. We'll see what we can do. Unfortunately, it's impossible to handle every case (e.g. your team speaks in other language and words for `true` and `false` are different, we don't want to involve translation API for that, of course).
> 
> You can't colorize image-based checkboxes, it's true. As of now, it's true for text-based checkboxes too. It's possible to allow colorization for image-based checkboxes by allowing user to adjust their hue individually, but that's a different story :)

and INDENTATION!
Believe me, I want to improve DBeaver and make it better for everyone as for myself, not less than any of you, team!
Best regards! :)

**Comment by ghYura** [comment]
BTW, pictogram/icon could(?) be colorized from the start and not squared, but rectangled (stretched horizontally) as bool-depicture from the start where 'true'-sign situated more to one side of the rectangled pictogram, and 'false'-sign - to another, what satisfies each to other indentation and color. NULL-values somehow placed between their 'true-null-false' positions. But very own customization suffers in this case...
But I want to replace 'pass' - for 'true', and 'fail' - for 'false'... other user(s) substitute his/her own meaning, which only(?) text-mode does(?)
See, bunch of propositions, as you can realize.
Up to you, for the best and easy-to-implement variant(s)

**Comment by ShadelessFox** [comment]
Implemented custom definition of text labels, changing alignment and colors:

![image](https://user-images.githubusercontent.com/35821147/133472446-de5d25eb-8b23-4946-88dd-0c9b791c15ef.png)

Current implementation **does not** include following requests:
1. Image checkbox colorization support
2. Assertions against malicious input in text mode
3. Bold text font in text mode

Separate FRs should be created instead.

**Comment by ghYura** [comment]
Awaiting for release roll out to test

**Comment by uslss** [comment]
win: verified

**Comment by Matvey16** [comment]
Verified on Linux and Mac

**Comment by ghYura** [comment]
Additional sub-issue (not for now):
For very further improvement assertion against text/icon similar color with background color of the cell/row match against it become invisible/barely-visible or smth.
Writing this sub-comment to not forget in the future, keeping beared in my mind yet, sharing with all of you.

**Comment by ShadelessFox** [comment]
There's a way to use font color of your active theme. It will be the contrast color.

**Comment by ghYura** [comment]
> There's a way to use font color of your active theme. It will be the contrast color.

Up to you all, team! I have infected you with the main idea - rest for the best - up to you. Since I know we are "on the same wave" about this main feature idea - I trust you, your expirience and your choice for the best of any further details :)

**Comment by ghYura** [comment]
&lt;DELETEME&gt;One more issue/feature/bug/odd_behavior of **Github** detected. But that is a different story.
QA-teams will always(?) have a job :)
**Be mistaken - my credo**
_In Whom V trust?
The REST - V test._
Ad-hoc/free-form-search technique used
&lt;/DELETEME&gt;

**Comment by ghYura** [comment]
@ShadelessFox Now we have general-for-all booleans representation. Thanks! :) Can we associate custom adjustment for each boolean column boolean-view adjustments individually? How about each column individual representation binding (in terms of code - each bool-column object - own sub-object viewing adjustments), that overrides general? 
In such bool-column names (headers) probably special marking/notification required and button/context-menu access to adjust it smh.
'Reset-all-booleans-to-default-button' should be provided in general-boolean-view-settings-menu that causes reset all individual bool-columns adjustments to its default viewing state
#ImproveDBeaver2maximum

**Comment by ShadelessFox** [comment]
No, we can't.

You can create a separate FR and we'll discuss it in the future.

But I think it would be an overkill for such a small feature.

**Comment by ghYura** [comment]
FYI:
Switches example - everyone, feel free to copy-use it for this mode:
[ ✔ ]██
██[ ✘ ]
![boolSwithesText](https://user-images.githubusercontent.com/42974628/136099633-44a29b41-60d0-48bf-96fe-dd21b80bd0ab.jpg)
