### ISSUE TITLE
Oracle: error when editing trigger/package body/procedure/function and trying to persist it after creation

### ISSUE THREAD

**Issue by F0xD8rk** [dbeaver/dbeaver#11357]
- Operating system (distribution) and version: Windows 10 version 20H2 Build 19042.804
- DBeaver version: 7.3.5.202102141704

- Database name and version: Oracle database 12c
- Driver name: Oracle Client 12 - 12.2.0.1.0 - oracle.jdbc.OracleDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Description/Steps to reproduce the problem

First, I created a trigger by executing the corresponding code in the SQL editor as a SQL statement. (with the ";" character at the end). After creation, I needed to adjust the trigger, so I open the trigger by:
- Navigating to the corresponding table of the trigger using the navigator.
- I click on the triggers tab
- I right click on the the just created trigger and choose "View trigger"
- I perform an edit on the trigger
- I press ctrl-s to save the trigger
- In the next window, I click on "Persist" after which the compilation fails with the error:
_PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:
   ;
The symbol ";" was substituted for "end-of-file" to continue.
Compile error at line 69, column 0_

After you then edit the trigger again and also place the ";" ending character manually, the persist works fine. The next time you edit the trigger using the GUI again, the problem is gone. It seems the problem only occurs the first time you edit the trigger using the GUI after creation using a sql editor pane.

Not a big issue, but it would be nice if it was not needed to place the ";" character manually at the end of the trigger after first creation. Thanks!

**Comment by F0xD8rk** [comment]
In the meanwhile I also noticed this problem when creating a package.
When using the SQL editor:
- When creating a package using _CREATE OR REPLACE PACKAGE ..._, the delimiter is set correctly in the declaration when viewing the properties.
- When creating a package body using _CREATE OR REPLACE PACKAGE BODY_, the delimiter is _not_ set automatically (same problem as the described issue above) and you have to add it manually at the end before saving (and persisting) in tthe the _BODY_ tab of the properties.

**Comment by F0xD8rk** [comment]
I just noticed that the same problem occurs after creation of a procedure or a function. The delimiter is also not set automatically after creation of the procedure/function using the SQL editor. 
The problem does not occur anymore after:
- manually putting the delimiter at the end of the procedure/function using the GUI
- Persisting the changes

In short, the problem occurs only after first creation of the procedure/function.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.
**STR**:
1. Create a procedure via SQL Editor e.g. ```CREATE OR REPLACE PROCEDURE HR.add_job_history2
  (  p_emp_id          job_history2.employee_id%type
   , p_start_date      job_history2.start_date%type
   , p_end_date        job_history2.end_date%type
   , p_job_id          job_history2.job_id%type
   , p_department_id   job_history2.department_id%type
   )
IS
BEGIN
  INSERT INTO job_history2 (employee_id, start_date, end_date,
                           job_id, department_id)
    VALUES(p_emp_id, p_start_date, p_end_date, p_job_id, p_department_id);
END add_job_history2```

2. Refresh the connection, open the procedure, make any valid changed and press Save

**Expected**: the changes are saved.
**Actual result**: the changes are not applied and the  error appears "PLS-00113: END identifier 'ADD_JOB_HISTORY' must match 'ADD_JOB_HISTORY2' at line 1, column 14
Compile error at line 12, column 5"

**Comment by p91paul** [comment]
@kseniiaguzeeva in you STR, you are missing a ; in the end of the first statement already, which the OP instead claims is present!

**Comment by F0xD8rk** [comment]
@p91paul That is correct, the ; is present at the end of the statement when running it. I just noticed that it seems to work when you place the delimiter twice (so ;;) at the end of for example a package body. However, it would still be great if it would work with the one delimiter, because that is also the way it works for the other objects. It would also be a little bit of an annoyance if you have to put an extra delimiter every time you run these object creation statements.

**Comment by serge-rider** [comment]
@akilovich reverted (it breaks multi-statement queries)

**Comment by flambchap** [comment]
Fixed again.

**Comment by Matvey16** [comment]
Verified
