### ISSUE TITLE
Worse usability with combined SQL toolbar in 7.3.5 - bring back the old SQL Editor buttons

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#11352]
I'd like to ask to bring back the old SQL toolbar buttons from before 7.3.5 or at least add a new separate button for the "New SQL script" action. This is the most often used action (at least in my case) - then why was it hidden behind a drop-down? An important thing is to have a one-click button for a new empty SQL editor.

The current combined toolbar button doesn't make sense, just have a look at it and compare it to the SQL menu just above it:

![dbeaver-sql-toolbar](https://user-images.githubusercontent.com/11840364/107949392-7fcec680-6f95-11eb-9546-cf9e0902e9fd.png)

![dbeaver-sql-menu](https://user-images.githubusercontent.com/11840364/107949406-83624d80-6f95-11eb-985d-9d9758d3f8e3.png)

Almost all of the items are the same - then what's the point of having the combined SQL toolbar if the same items are under the normal SQL menu? There's still the Quick Search item but it's available under the  Search menu. I think the main goal of a toolbar is to add a faster way to access certain functions but this seems to only duplicate the main menu without making anything faster.

I suggest bringing back the previous SQL toolbar buttons. As I can see about 80% of the toolbar width is empty so is there a need to save space by removing buttons? If not, then please at least add a separate button for the new SQL script action.

**Comment by serge-rider** [comment]
We did this to reduce number of elements in the main toolbar. 
Multiple SQL editor opening commands confuse users, they don't know to action to use. We left only "Open recent/existing" as the most universal action.

In fact different users use different action to work with scripts. Some create new scripts all the time, others use just a couple of scripts, thirds never use toolbar at all and use shortcuts instead.

Anyway. I will add new main toolbar "SQL toolbar" with all SQL script action + several others. It will be  hidden by default. It can be configured in Window->Customize Perspective. I hope this will satisfy everyone.

**Comment by lemon-juice** [comment]
I've tried to find some options to customize toolbars and as a long time user I wasn't able to find it until you pointed me to Window > Customize Perspective!

Yes, a new SQL toolbar would be great, even a single new button for a new script under the Database Toolbar would be fine. But to tell you the truth, I like the new combined toolbar very much and it would be fantastic except one thing - if the default action was to start a new script. A large button for this action would be very convenient but alas "Open SQL script (existing or new)" is something very vague to me and I don't know why I would want to use that at all. I don't really know how most people use DBeaver but to me any SQL tool's most important button would be to start a new blank query editor (but I use the shortcut key, too).

But thanks for your understanding, whatever you do to have a button for opening a new script will be fine. If you are able to make the button a bit larger (wider) than those standard small square buttons it would be even better!

**Comment by Mizar01** [comment]
I can add that the default action on the toolbar is to open existing saved file if any. This in my opinion shuldn't be the default.

Most of the time I have to create brand new query and I have to delete all the text i find inside before (and this will overwrite my old script too) or remember to click on the drop down menu.

I had a weird problem the last day because the editor accidentally summoned an old query similar but not equal to what I had to do, but in the middle of other activities, I could'nt realize that I didn't overwrite the query with the right version, losing a lot of time figuring out what was wrong.

I would like that at least we can customize the default action of the new SQL toolbar button.

**Comment by mogzol** [comment]
I'd like to hear the reasoning behind having the default action be opening a recent script. For that to really be useful you'd have to (a) remember what your most recent script was, and (b), actually want to open that script. I don't know about anybody else, but there's very few circumstances where that's actually what I want to do. Most of the time I just want to write a quick one-off query, so I would much rather have the default action be to open the SQL console or open a new script.

**Comment by lemon-juice** [comment]
Good point. I think a button to open a new blank sql editor should be the default for everybody. Things like opening previous scripts can be useful but are more specialized operations for those who want them. I can see the devs are planning a fix for this, I hope they will implement the new blank script button in some form.

**Comment by serge-rider** [comment]
I think we can do the following: add default behavior selector right in the SQL dropdown. As a sub-menu with radio buttons selector.

Thus you can define "SQL" button behavior with two clicks.

**Comment by lemon-juice** [comment]
Sounds good to me!

**Comment by serge-rider** [comment]
Default action configuration:

![image](https://user-images.githubusercontent.com/6398845/112969532-fc88bf00-9155-11eb-99c7-1cb82f9a8f4f.png)

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by LeonardoDaMunici** [comment]
Please get the button "New SQL script" back on the main toolbar or give the users the option to configure the toolbar theirselves. If you want, google the german word "verschlimmbessern". That's, what it is.
Btw. the shortcut "Ctrl + ]" is terrible combination, when you use a german keyboard. -> "Ctrl + AltGr + 9"

**Comment by uslss** [comment]
Default command for button SQL could be changed in its menu
![image](https://user-images.githubusercontent.com/31996417/126452340-8ec0fafa-6d47-4c34-a49b-a9f4c3d5ee4a.png)

Keybindings also could be changed in preferences
![image](https://user-images.githubusercontent.com/31996417/126452541-6df49cfd-85cd-4d23-896d-26c186c2bfeb.png)
