### ISSUE TITLE
Tip of the day is not displayed on startup

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11361]
#### Steps to reproduce, if exist:
1. Be sure Show tip on startup is enabled
2. Relaunch DBeaver

Expected: tips are displayed
Actual result: tips are not shown and can be seen via Help menu

**Comment by flambchap** [comment]
It's a macOS-specific issue.

**Comment by flambchap** [comment]
Fixed. Now we do not attempt to show the TotD window if DBeaver is started for the very first time.

**Comment by kseniiaguzeeva** [comment]
verified
