### ISSUE TITLE
Create table from exisiting view

### ISSUE THREAD

**Issue by iwantmyway** [dbeaver/dbeaver#11366]
Is there any ways to create a new table from a existing view ?

**Comment by uslss** [comment]
Hi @iwantmyway ,
if I understand you correctly you could open view then choose Export data button in the Data viewer toolbar and choose Database tables as target type here
![image](https://user-images.githubusercontent.com/31996417/108088277-54c59f00-7089-11eb-8ca7-17af07c705ee.png)
Then you should choose target container you need and new table name.
![image](https://user-images.githubusercontent.com/31996417/108088533-a110df00-7089-11eb-9680-857795720a88.png)

Could you check if it fits your needs?

**Comment by iwantmyway** [comment]
Thank you so much. You are life saver.
It is exactly what I need.
