### ISSUE TITLE
Changes in sun.security.x509.AlgorithmId in JDK 15

### ISSUE THREAD

**Issue by A248** [dbeaver/dbeaver#11360]
#### System information: 
Mac OS X 10.14.6
JDK version OpenJDK 15.0.1+9

#### Connection specification:
n/a

#### Describe the problem you're observing:
* Building DbBeaver fails on JDK 15 because `sun.security.x509.AlgorithmId`, an internal JDK class, was changed.
* This also means that users cannot *run* DbBeaver or CloudBeaver on JDK 15, unless CertificateGenHelper is never called.

The field `md5WithRSAEncryption_oid` no longer exists, and as a result, CertificateGenHelper cannot compile.

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.0.0:compile (default-compile) on project org.jkiss.dbeaver.model: Compilation failure: Compilation failure:
[ERROR] /Users/anandbeh/git/SolarMC/dbeaver/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/app/CertificateGenHelper.java:[69]
[ERROR] 	AlgorithmId algo = new AlgorithmId(AlgorithmId.md5WithRSAEncryption_oid);
[ERROR] 	                                               ^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] md5WithRSAEncryption_oid cannot be resolved or is not a field
```

Downgrading to OpenJDK 11 is a temporary workaround.

#### Steps to reproduce, if exist:

I discovered this while trying to set up CloudBeaver.

1. Use JDK 11
2. Follow the CloudBeaver's [Build and Deploy](https://github.com/dbeaver/cloudbeaver/wiki/Build-and-deploy#build-and-deploy) after requirements are installed
3. Observe build failure

#### Include any warning/errors/backtraces from the logs

Full output of running CloudBeaver's `build.sh`, including maven build of DbBeaver:

https://pastebin.com/STkhURkE

#### See also
https://github.com/playframework/playframework/issues/10478
https://github.com/openjdk/jdk/commit/080b3b83ebffe5149fbc9ac48e921fb5

**Comment by kaelte** [comment]
Same happens with newer Mac OS X:
```
ProductName:	macOS
ProductVersion:	11.2.1
BuildVersion:	20D74

java 15.0.1 2020-10-20
```

**Comment by 7astro7** [comment]
Attempting to build dbeaver on arch Linux produces an error message similar to @A248 's. 
Operating system name:     Arch Linux
Operating system version:  Rolling release
Kernel version:            5.11.2
Hardware platform:         x86_64

openjdk 15.0.2 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7)
OpenJDK 64-Bit Server VM (build 15.0.2+7, mixed mode)

After cloning using 
    git clone https://github.com/dbeaver/dbeaver.git dbeaver
the full output of running 
    $ mvn package 
is at https://pastebin.com/w3E0ziUk
Love the beaver, thanks!

**Comment by serge-rider** [comment]
We need to get rid of explicit algorithm usage in self-signed certificate generation. 

We probably should use sun.security.tools.keytool.Main instead.

**Comment by dvaun** [comment]
Encountered the same bug.
```
❯ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H524
❯ java --version
openjdk 15.0.2 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7)
OpenJDK 64-Bit Server VM (build 15.0.2+7, mixed mode, sharing)
```
Replacing the offending statement with `AlgorithmId.get()` fixed the issue for me:
```java
AlgorithmId algo = AlgorithmId.get("SHA-256");
```
I referenced the function definition here https://github.com/openjdk-mirror/jdk7u-jdk/blob/f4d80957e89a19a29bb9f9807d2a28351ed7f7df/src/share/classes/sun/security/x509/AlgorithmId.java#L405-L420

**Comment by ShadelessFox** [comment]
Hello @dvaun,

Thanks for investigating.

Does it only solve compilation problem or self-signing mechanism still works under JDK15?

Actually, this statement could be replaced with `"MD5withRSA"` to match the previous version.

**Comment by dvaun** [comment]
Hi @ShadelessFox, it should self-sign successfully given that the `AlgorithmId.get()` returns an instance of `AlgorithmId`. I have not ran any tests, though.

I found similar fixes here:
* https://github.com/playframework/playframework/commit/4d8d84c560ae5cc2433cd7a0a9863bc6d88ea28a#diff-838d3843f266a91382fef49dedbae029c6202c88fb9e4e756e47dfe735ac1e15
* https://github.com/lightbend/ssl-config/commit/ae5881396305a031baf6d1604b745d5bfcca2659#diff-940851411d7c08c8379b33842421b7626a2d22ddabba1ca30fbdcadb5c8fbf9aR163

**Comment by ShadelessFox** [comment]
You see, besides that one constant, we use `sun.*` packages that aren't a part of Java's standard library. In JDK15 there were several security improvements, including the usage restriction on the internal APIs, including that one I mentioned before.

**Comment by dvaun** [comment]
Would using the bouncycastle package be acceptable? https://www.bouncycastle.org/documentation.html

**Comment by ShadelessFox** [comment]
We had some thoughts about that. But even using its lightweight API the binary size is still inappropriate :(

Currently we're looking towards using the `keytool` command-line utility which is bundled with Java.

**Comment by dvaun** [comment]
That's neat. I don't use Java day-to-day so I haven't worked with `keytool` before. 

After some brief searching it looks like it calls `sun.security.tools.keytool.Main.main()`: https://www.pixelstech.net/article/1452341855-Using-Java-keytool-programmatically

Seeing as `generateCertificate` passes the DN and keypair then this could be used to generate the certificate then be returned as `byte[]` 

Edit: Found an example of X.509 generation with `keytool`: https://lightbend.github.io/ssl-config/CertificateGeneration.html#generating-x-509-certificates

**Comment by ShadelessFox** [comment]
Thanks for your investigation, but unfortunately we can't use the first approach because it's internal API too.

**Comment by dvaun** [comment]
Okay, looking further then maybe you can check for existence of `keytool` in the path then create a process/runtime to execute it? Then you can pass the necessary parameters.

**Comment by ShadelessFox** [comment]
That's exactly what we want to do :)

**Comment by dvaun** [comment]
If you or the other developers don't have time to spare to work on this particular goal I'd be willing to spend some time this weekend playing with it.

**Comment by ShadelessFox** [comment]
Well, we are always open for contributions, so it would be really nice!

Do you need any help to get started on it?

**Comment by dvaun** [comment]
If I run into trouble I'll ping here. Is there a another issue or milestone I should reference if I make a commit?

**Comment by ShadelessFox** [comment]
There may be other issues related to the same problem, but they're mostly duplicates, so you can directly reference only this issue.

**Comment by wangpeng0824** [comment]
@ShadelessFox  encountered  similar problem with adoptopenjdk11,
1，The package sun.security.x509 is not accessible，
2，The type sun.security.util.DerInputStream is not accessible，
3，The type sun.security.util.DerValue is not accessible，
4，The package org.w3c.dom is accessible from more than one module: <unnamed>, java.xml
>>openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)


![image](https://user-images.githubusercontent.com/21004513/123355328-09238480-d598-11eb-8cbc-0b1ee2412a37.png)
-------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/21004513/123355437-425bf480-d598-11eb-9126-67f72710ad05.png)
--------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/21004513/123355487-57388800-d598-11eb-8ccd-d40e3f985a0e.png)

**Comment by ShadelessFox** [comment]
Hi @wangpeng0824,

I'd say that's a different issue.

In case of `sun.*` imports, you can modify access rules for your JRE.
To do so, open plugin with errors, in the context menu go to <kbd>Properties</kbd> &rArr; <kbd>Java Build Path</kbd>&rArr; <kbd>Libraries</kbd>&rArr; <kbd>JRE System Library</kbd>&rArr; <kbd>Access rules</kbd> and add a new one with value `sun/**` and resolution mode `Acessible`. This trick may work for `org.w3c`, but looks like you have multiple occurrences in your class path.

**Comment by wangpeng0824** [comment]
> Hi @wangpeng0824,
> 
> I'd say that's a different issue.
> 
> In case of `sun.*` imports, you can modify access rules for your JRE.
> To do so, open plugin with errors, in the context menu go to Properties ⇒ Java Build Path⇒ Libraries⇒ JRE System Library⇒ Access rules and add a new one with value `sun/**` and resolution mode `Acessible`. This trick may work for `org.w3c`, but looks like you have multiple occurrences in your class path.

thanks for your reply，i have resolved the problem ，it was caused by my wrong configuration of ‘Java Build Path’，i edit the JRE System Library to Excution environment, and it works；
![image](https://user-images.githubusercontent.com/21004513/123386087-dc3b9580-d5c8-11eb-92e5-a4b6f1688294.png)

**Comment by ShadelessFox** [comment]
Now we use Bouncy Castle for generating self-signed certificates and loading PKCS1 private keys.

Please make sure mentioned changes do not cause issues on Linux and macOS.

**Comment by serge-rider** [comment]
Test cases: SSL connectivity with PG, MySQL, Cassandra, Redis.
SSH tunnels with private-key authentications.
AWS and GCP connectivity.

**Comment by Matvey16** [comment]
Verified
