### ISSUE TITLE
DBeaver CPU usage goes up over time even w/o much interaction

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#11368]
#### System information: 
- Operating system: Debian/SID
- DBeaver version: Version 7.3.5.202102141704
- Additional extensions:

#### Connection specification:
- Database name and version: Postgres 12
- Driver name:  postgresql-42.2.5.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

After about one hour or even less, DBeaver's CPU usage starts to increase visibly until it reaches over 50% band begins to feel slugish. When it reaches about 75% it becomes more or less unusable and I have to exit and restart it.

It seems not to matter
- how many editors are open
- if I use table views instead of editors
- how many open connections 

I use Eclipse in parallel (currently Version: 2020-12 (4.18.0), Build id: 20201210-1552), but do not experience that same sluggishness.

So far, I haven't been able to figure out what part causes it, the logs do not show any information.

**Comment by uslss** [comment]
probably, could be related to #11089 
Can you make a [thread dump](https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump) in case the issue appears again?

**Comment by 2019-05-10** [comment]
ZIP with
thread-dump.txt 
dbeaver.ini

[foo.zip](https://github.com/dbeaver/dbeaver/files/5995777/foo.zip)

BTW: the thread dump site could use a clarification that the complex construct of ```ps ...awk``` is supposed to produce the PID of the JAVA process running DBeaver.

**Comment by 2019-05-10** [comment]
[thread-dump2.txt](https://github.com/dbeaver/dbeaver/files/6012188/thread-dump2.txt)
And another thread dump while freezing on paste

**Comment by 2019-05-10** [comment]
[thread-dump.txt](https://github.com/dbeaver/dbeaver/files/6023021/thread-dump.txt)
[thread-dump2.txt](https://github.com/dbeaver/dbeaver/files/6023022/thread-dump2.txt)

**Comment by 2019-05-10** [comment]
[thread-dump3.txt](https://github.com/dbeaver/dbeaver/files/6063370/thread-dump3.txt)
[thread-dump4.txt](https://github.com/dbeaver/dbeaver/files/6063371/thread-dump4.txt)

**Comment by serge-rider** [comment]
@2019-05-10 thank you for the details.

Unfortunately thread dumps don't contain real clues (something eats cpu in UI rendering thread).

- What if you close all open editors - does it still consume CPU?
- What if you collapse database navigator tree? 
- Or even close it?

**Comment by 2019-05-10** [comment]
I played around when time permitted and so far I've found tow things:
a) closing database navigator view does not change anything
b) closing all open editors _seems_ to make cpu usage drop, opening a bunch of editors again does not seem to cause the rise again

b) could indicate that either not actively closing old editors but keeping them open over a long time is at fault -- but I usually shutdown DBeaver every day and start it again the next.
Some of the editors where quite large with dozens of queries and several hundreds of lines. No idea what DBeaver makes of that.
I opened one of those large editors again, but w/o using it -- so far no cpu spikes related to that apparently.

Now, today I encountered something quite interesting:
Usually once a day I need to import a large CSV file to table. Today's file is about 8mb and has about 52000 rows.
While opening the file chooser to select the file, I remebered to file a bug redport about the initial sort order and left it open to take a screenshot -- cpu startet to jump to 16%-30%, just with the file chooser open!
Closing the file chooser and canceling the whole import, cpu still every second or two jumps to 13%-18%!

Over the last week I got the impression, that the cpu spikes started after the import of said csv file, part of which may well be attributed to the file chooser issue described above, but that's not enough.
Any idea how to confirm that suspicion?

**Comment by 2019-05-10** [comment]
Well. my be, it _is_ just the file chooser.
Have not yet imported nor done anything with DBeaver since about 45 minutes and the cpu usage already reaches 28% now.

**Comment by 2019-05-10** [comment]
After import cpu now reaches 38%.

**Comment by serge-rider** [comment]
Thank you for the investigation.

**Comment by kseniiaguzeeva** [comment]
verified
