### ISSUE TITLE
Disregarding of statements delimiter character

### ISSUE THREAD

**Issue by bcm5645** [dbeaver/dbeaver#11378]
#### System information: 
- Operating system Win10 20H1
- DBeaver version 7.3.3, but issue seems to be from 7+ versions
- Java version 8

#### Connection specification:
- Database name and version Oracle 12c

#### Describe the problem you're observing:
I'm working on daily basis with incremental SQL file, where i put my statements to work with.
Right now my file has 30k lines (average ~4 lines per statement).
I'm using semicolon ; as a statement delimiter, not using Blank line as a delimiter.
It's annoying behavior which started to come up somewhere from first 7+ versions, I have not noticed that in 6.2+ versions:
when I'm executing statement (by Ctrl + ENTER) sometimes it disregards previous semicolon delimiter, starting to parse some statements before current one (sometime it's 1 or 2 before, but sometimes it looks for coupe of hundreds before).
I don't find any pattern to this behavior, but it's really annoying, showing me Bind parameter window from above statements.
Pressing ESC then also take some unacceptable amount of time.

Is it so, that every time i execute the statement it started to analyze file from very beginning?

#### Steps to reproduce, if exist:
Executing statement can cause issue to appear, but repeating it as is makes execution running. Can't say how to reproduce it.
On average I'd say it fails in 1/10 statement executions.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. Please send an example. It is hardly possible to find a reason without it

**Comment by bcm5645** [comment]
Hello Kseenia

Please see enclosed screenshot video.
I kept executing a statement (Ctrl+Enter), editing the statement in the meantime (adding tab and remove).

It seems to be parsing issue.
Can parsing works like this, that it looks for closest delimiters before and after current cursor position and execute only such statement?

I have set a semicolon as delimiter.

https://user-images.githubusercontent.com/46082667/110787274-6f94c900-826d-11eb-9cc0-530c0d72dfe4.mp4

**Comment by kseniiaguzeeva** [comment]
Sorry for the long responce. Please send the video one more time (here or on kseniia@jkiss.org). This one doesn't work.

**Comment by bcm5645** [comment]
Hi Ksenia
I just sent the video by email to kseniia@jkiss.org.
Thank you for taking this issue.
I hope for solving it.
/Wiktor

**Comment by kseniiaguzeeva** [comment]
I see the behavior but cannot reproduce it. Is it possible to send a script example? special symbols can be a reason.

**Comment by bcm5645** [comment]
Hi Ksenia
I just sent you another email with script and responses i'm getting in dBeaver.
/Wiktor

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on issue for a long time. If it is still actual for you - feel free to reopen it
