### ISSUE TITLE
Lower case schema name had empty procedure folder

### ISSUE THREAD

**Issue by klausdietel** [dbeaver/dbeaver#11370]
Hello,
im Working with snowflake and in schema PUBLIC I can see my procedures. But in schema "lcase" i cannot see the procedures.
CREATE SCHEMA "lcase" CLONE  PUBLIC ;
procedure foldes is empty
CREATE SCHEMA UCASE CLONE  PUBLIC ;
procedure folder is filled.
![schema-Ohne-Proc](https://user-images.githubusercontent.com/64849460/108094194-d532d280-707e-11eb-93f9-69cdbced9ee2.png)

I can see the query and the resultset in the query history of snowflake. 

![schema-Ohne-Proc_lcase](https://user-images.githubusercontent.com/64849460/108095002-b123c100-707f-11eb-9b3b-4e1ffdf0928f.png)

#### System information: 
i installed latest Community Edition 7.3.5
windows 10 
snowflake database

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
In scope of this ticket we added table statistic info and new fields in table info, Sequence support (with ability to drop, rename and change increment value via UI) and now we read procedures and functions from database, not from driver. All this works only in [EE version](https://dbeaver.com/).

**Comment by Matvey16** [comment]
Problem is specific to snowflake and creating schemas with keyword names. As a workaround don't use Keywords in schema/database names.
