### ISSUE TITLE
"calculate column width by cell values" missing in Dbeaver 7.3.5

### ISSUE THREAD

**Issue by rokopi-byte** [dbeaver/dbeaver#11381]
#### System information: 
- Operating system (distribution) and version: Ubuntu 16.04
- DBeaver version: 7.3.5 CE

#### Describe the problem you're observing:
Hi, I cannot find the option "calculate column width by cell values" in my DBeaver, I need fit the result-set columns to their content. Is this option deprecated or only available in EE ? Thanks

**Comment by LonwoLonwo** [comment]
Hello @roccopietrini 
Are you looking for this setting?
![2021-02-17 13_28_11-DBeaver Enterprise 7 3 5 - language](https://user-images.githubusercontent.com/45152336/108191375-1b8e3d00-7124-11eb-8613-12ae55b060ba.png)

**Comment by rokopi-byte** [comment]
Yes exactly! Thank you!
Anyway I have a column that doesn't fit its content, it's a long url.. there is maybe a limit ?

**Comment by LonwoLonwo** [comment]
It can be limit of the column. Like varchar(100), which can contains only 100 symbols.
What data type does your column have?

**Comment by rokopi-byte** [comment]
Maybe I was misunderstood.. my data is fine, that column contains my data entirely (it's a varchar(512)).. but when I visualize the result-set, even with the above option enabled, I have to click on a single cell of that column to view entirely the content of that cell in tab "value", otherwise in tab "result" the column is truncated..

![Screenshot from 2021-02-17	14-24-10](https://user-images.githubusercontent.com/23717373/108210684-277dfd00-712c-11eb-8135-ba009d25381b.png)

**Comment by LonwoLonwo** [comment]
Hello @roccopietrini "calculate column width by cell values" setting not really about it.

![2021-04-04 19_56_07-Preferences](https://user-images.githubusercontent.com/45152336/113516163-73242300-9581-11eb-8835-dffa5d62b7a5.png)

But you can use "Columns width: fit values". Right click on column name in Data Viewer.

![2021-04-04 20_03_09-DBeaver Enterprise 21 0 2 - film](https://user-images.githubusercontent.com/45152336/113516226-c1392680-9581-11eb-984d-9379b358b670.png)

**Comment by rokopi-byte** [comment]
Hello, my context menu looks different, I don't have that entries. I have version 21.0.2 now.

![Screenshot from 2021-04-06 09-37-41](https://user-images.githubusercontent.com/23717373/113676219-77089000-96bc-11eb-9d37-f3c683c7c705.png)

**Comment by LonwoLonwo** [comment]
@roccopietrini you need to use right click on column name, not on the cell width data.

**Comment by rokopi-byte** [comment]
That's what I do. Right click on the column header automatically select first cell. Is that another issue?

**Comment by LonwoLonwo** [comment]
Seems to be Ubuntu problem. What protocol are you using? May be Wayland?

**Comment by rokopi-byte** [comment]
I'm using a bare Ubuntu 16.04.7, so it's Xorg

**Comment by LonwoLonwo** [comment]
@roccopietrini 
Hmm. Looks like a bug.
Can you please try right click on column data type icon, to the left of the title?
![2021-04-12 11_27_34-DBeaver Enterprise 21 0 3 - film](https://user-images.githubusercontent.com/45152336/114364623-3f00c180-9b82-11eb-9fda-c7692bf716cc.png)

**Comment by rokopi-byte** [comment]
Just tried, but nothing changed

**Comment by LonwoLonwo** [comment]
New option for long content value columns implemented.
You can manually choose the width of those columns - in percents.
Default value is 30% of monitor screen.
100% will set the length of the column on the full column content length (if it allows the monitor screen width).
Will be available in DBeaver 21.0.3
19.04.21

![114680499-efeb9580-9d15-11eb-9674-9dcd9ef42048](https://user-images.githubusercontent.com/45152336/114814516-03057080-9dbd-11eb-8e33-215d2e260b99.png)

**Comment by uslss** [comment]
verified
