### ISSUE TITLE
open SQL script in perspective

### ISSUE THREAD

**Issue by eliodamico** [dbeaver/dbeaver#11389]
I'm frustrated with the last update 7.3.5.202102141704 which substituted all the script icons with a drop down menu. The action that I perform the most is to open a new script on one of several DB I have to query. Now I have to do double action (open the menu and choose the action). I do not understand the rationale since no space was saved (the size of the drop down menu is equivalent with the row of icons). At least could you put a choice in customize perspective?

**Comment by uslss** [comment]
thanks for suggestion
it will be implemented in the scope of #11352
