### ISSUE TITLE
Wrong syntax highlighting for BigQuery string literals containing escaped characters

### ISSUE THREAD

**Issue by lukaseder** [dbeaver/dbeaver#11384]
#### System information: 
- **Operating system (distribution) and version:** Microsoft Windows [Version 10.0.19042.804]
- **DBeaver version:** 7.3.5.202102151746
- **Additional extensions:** N/A

#### Connection specification:
- **Database name and version:** BigQuery
- **Driver name:** Simba BigQuery driver
- **Do you use tunnels or proxies (SSH, SOCKS, etc)?** No

#### Describe the problem you're observing:

Syntax highlighting doesn't work for escaped characters in string literals

#### Steps to reproduce, if exist:

This is a valid SQL query in BigQuery:

```sql
select 'ab\'cd', 'xy\'za'
```

But DBeaver doesn't recognise the escaped apostrophe `\'` and thinks instead that the string literal has ended

This probably happens with all sorts of escaping, including escaping in other types of string literals, such as `"abc"`, `"""abc"""`, see: https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/734593/108212599-5e551280-712e-11eb-9e4c-e0a9e5fff091.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
Fixed:

![java_tCyHggnX3q](https://user-images.githubusercontent.com/35821147/116567374-3ba25f80-a910-11eb-8e27-8e13a38f6c42.png)

**Comment by uslss** [comment]
verified
