### ISSUE TITLE
Oracle: Table triggers section keeps loading forever

### ISSUE THREAD

**Issue by F0xD8rk** [dbeaver/dbeaver#11382]
**System information:** 
- Operating system (distribution) and version: Windows 10 version 20H2 Build 19042.804
- DBeaver version: 7.3.5.202102141704

**Connection specification:**
- Database name and version: Oracle database 12c
- Driver name: Oracle Client 12 - 12.2.0.1.0 - oracle.jdbc.OracleDriver library 21.1.0.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

**Describe the problem you're observing:**
After trying to open the _Table triggers_ section for a schema, the list keeps loading and seems to hang on _"Load items ...: Load TriggerCache"_. Even after 10 minutes, the list is still loading (and seems to load forever)
The problem also still occurs when using a filter for the Table triggers section.

![2021_02_17_11_45_09_DBeaver_7 3 5](https://user-images.githubusercontent.com/79097587/108193670-9d26a080-710d-11eb-8a40-eddfff0f0f9f.png)

**Comment by LonwoLonwo** [comment]
Hello @F0xD8rk 
On this tab, we read triggers for all tables in this schema. How many tables contains your schema?

**Comment by F0xD8rk** [comment]
Hello @LonwoLonwo 
We have around 6000 tables in that schema, however not every table contains triggers.
That is still a lot of course, so maybe this causes issues for Dbeaver because of the large amount?

**Comment by LonwoLonwo** [comment]
So, problem is clear(We must transfer the trigger cache to the schema), we will fix it in next releases.

**Comment by F0xD8rk** [comment]
@LonwoLonwo 
Ok, thank you!

**Comment by uslss** [comment]
verified
