### ISSUE TITLE
database crashing when used by a windows dbeaver client

### ISSUE THREAD

**Issue by rogeriao** [dbeaver/dbeaver#11394]
Hi 

I have a DB2 database that crashes every time someone connects from a Windows Dbeaver client. 

Some facts observed so far

1) The problem only happens with a particular database 
I can connect and do whatever needed in other databases from the same windows clients
2) I can reproduce the problem as needed 
3) It does not take much to crash the database: any query submitted or even expanding the left menu can bring the db down

=> DB2 version: 
DB2 V11.1.4.5 Special Build 40478

=> Dbeaver versions where the problem happens:
Dbeaver Community Edition 7.3.2  
Dbeaver Comminuty Edition Version 7.3.5.202102141704

=> Database Server OS version: 
NAME="SLES"
VERSION="12-SP5"
VERSION_ID="12.5"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP5"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp5"

=> Windows 
Windows 10

Anybody seen such behaviour before ? 

Thanks a lot,
Rogerio

**Comment by uslss** [comment]
hi @rogeriao ,
what db2 driver do you use? is there something in dbeaver logs?

**Comment by rogeriao** [comment]
hi @uslss 

DB2 driver:

IBM DB2 JDBC Universal Driver Architecture 3.62.56

Here is the log 
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/6002852/dbeaver-debug.log)

**Comment by uslss** [comment]
did you try to use some default driver from dbeaver?
![image](https://user-images.githubusercontent.com/31996417/110757884-ec6b7700-825c-11eb-9328-70b006535375.png)

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual for you - feel free to reopen it
