### ISSUE TITLE
Redis ACL, how to set username in Redis connection?

### ISSUE THREAD

**Issue by kentore82** [dbeaver/dbeaver#11398]
#### System information: 
- Operating system MacOS Big Sur
- DBeaver version EE 7.3.0

#### Connection specification:
- Redis server 6.0.7
- Redis
- Redis with username/password with SSL 

#### Describe the problem you're observing:
Unable to connect to Redis with ACL (username, password). There is no dialogue box to input username. Also the "Edit driver settings" seems read only. Is this supported?

#### Include any warning/errors/backtraces from the logs
Could not get a resource from the pool
WRONGPASS invalid username-password pair
WRONGPASS invalid username-password pair

**Comment by serge-rider** [comment]
This feature will be added in DBeaver EE 21 (the next version).
