### ISSUE TITLE
.ERD files won't be saved as UTF-8 encoding

### ISSUE THREAD

**Issue by yiding-he** [dbeaver/dbeaver#11399]
#### System information: 
- Operating System: Windows 10
- DBeaver version: 7.3.5
- Additional extensions: None

#### Connection specification:
(irrelevant)

#### Describe the problem you're observing:
My OS default charset is CP936. And ER Diagram files (*.erd) won't be saved as UTF-8 no matter how I change file type settings. The header of the .erd file is `<?xml version="1.0" encoding="UTF-8"?>` but actual encoding is CP936. As a result, DBeaver cannot open it again.

#### Steps to reproduce, if exist:
- Open DBeaver in a Windows 10 with CJK language.
- Create a .erd file with CJK character name (such as "你好.erd").
- Add a (any) table into the diagram.
- Save the diagram and close editor tab.
- Double click the diagram, it shows 0 objects.

**Comment by kseniiaguzeeva** [comment]
Unfortunatelly I cannot reproduce it. Please send a video, where you reproduce it.

**Comment by yiding-he** [comment]
@kseniiaguzeeva Sure, so this is my screen recording as a demonstration of this issue:

**Comment by kseniiaguzeeva** [comment]
Thank you! I reproduced it with EverEdit.

**Comment by ShadelessFox** [comment]
Hello @yiding-he,

Can you please try the [Early Access](https://dbeaver.io/files/ea/) version to see if the problem still persists?

We can't really verify the fix by ourselves :(

**Comment by yiding-he** [comment]
The problem is still there.

**Comment by ShadelessFox** [comment]
Thanks for the response. I will investigate further.

**Comment by ShadelessFox** [comment]
Looks like the fix was lost on the way to the Early Access version. Now it should be included. Can you try again, please?

**Comment by yiding-he** [comment]
@ShadelessFox 
I have confirmed that this bug has been fixed, and for privacy concerns I removed screen recordings uploaded previously.
