### ISSUE TITLE
Netezza - procedure source code from wrong schema

### ISSUE THREAD

**Issue by graczykdamian** [dbeaver/dbeaver#11403]
#### System information: 
- Operating system: MS Windows 10
- DBeaver version 7.3.4

#### Connection specification:
- Netezza
- nzjdbc

#### Describe the problem you're observing:
I have procedures in different schemas with same name but different bodies. For example: in schema ADMIN, I keep current version of procedure X, in schema OBSOLETE we keep previous X with earlier version of code for backup reason. 
After double click on procedure in ADMIN schema to enter properties and see the source code, I see definition of other procedure in schema OBSOLETE. After I click on the same procedure in schema OBSOLETE, it shows the same body which is correct. When I drop the procedure in schema OBSOLETE then ADMIN procedure shows correct body.

**Comment by LonwoLonwo** [comment]
Thanks for the bug report! We need to read procedure definitions more precisely.

**Comment by LonwoLonwo** [comment]
Fixed in 21.0.0
For procedure and view definitions with equal names.

**Comment by uslss** [comment]
verified
