### ISSUE TITLE
wrong documentation? cell editor doesn't work as described in the WIKI - it is not available and missing in context menu.

### ISSUE THREAD

**Issue by aisbergde** [dbeaver/dbeaver#11409]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version 7.3.5.202102141704
- Additional extensions
- 
#### Connection specification:
- Database name and version: SQL Server 2019
- Driver name: I don't know where to find this information. dbeaver installed something when I first time connected to an SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

The main reason why I wanted to try dbeaver was the feature "cell editor" which is described here:
https://github.com/dbeaver/dbeaver/wiki/Data-Viewing-and-Editing
I need this feature to enter multiline data into some text fields, but SSMS or Azure Data Studio have issues with multiline data input. And I prefer an open source project, so I could recommend to other users to use a working tool, when it will work for me.

**The cell editor is not available as described in the documentation.** There is no "edit cell" in the context menu and there is no "edit cell" button.
![image](https://user-images.githubusercontent.com/9020187/108404269-f121aa00-721f-11eb-9146-9ccc6b2f90a2.png)

#### Steps to reproduce, if exist:

In the tree, double-click on any table. The data grid will open.
![image](https://user-images.githubusercontent.com/9020187/108404543-49f14280-7220-11eb-8012-438bb4d70ddd.png)

I can't imagine that this feature was implemented is then removed. So I assume the feature is still there, but that it has been well hidden for new users.

Maybe the implementation has changed, but the documentation is wrong and describes an old way?
Even if it is possible - then it is not intuitive.

**Comment by uslss** [comment]
Hi @aisbergde ,
you can open the editor using Shift+Enter when the needed cell is chosen.
Also, you can change double-click behavior in preferences.
![image](https://user-images.githubusercontent.com/31996417/108873711-76380500-760c-11eb-927e-5be1d7eb72d5.png)
