### ISSUE TITLE
Cannot really change BigQuery driver version

### ISSUE THREAD

**Issue by lukaseder** [dbeaver/dbeaver#11404]
#### System information: 
- **Operating system (distribution) and version**: Microsoft Windows [Version 10.0.19042.804]
- **DBeaver version**: 7.3.5.202102151746

#### Connection specification:
- **Database name and version**: BigQuery
- **Driver name**: Simba
- **Do you use tunnels or proxies (SSH, SOCKS, etc)?**: No

#### Describe the problem you're observing:

I'd like to upgrade the Simba driver, but I can't except if I download it manually to the disk somewhere

#### Steps to reproduce, if exist:

- Enter the wizard to add a BigQuery connection.
- Choose "Edit Driver Settings"
- Go to the "Libraries" tab:

![image](https://user-images.githubusercontent.com/734593/108356455-71c6b300-71ec-11eb-819d-01935b0222f0.png)

I can only add files/folders from locally downloaded drivers, or a maven artifact. But given that this driver is not available from Maven Central, that doesn't make sense either. As you can see, the URL is hard coded to a specific driver version

I'd like to be able to update the URL, but that's not possible in the Download/Update dialog:

![image](https://user-images.githubusercontent.com/734593/108356622-a470ab80-71ec-11eb-83b7-dad909840432.png)

Neither can I do anything about it in the Information dialog, where everything is read only:

![image](https://user-images.githubusercontent.com/734593/108356691-bd795c80-71ec-11eb-866e-5159ca5228d8.png)

I can only manually download the latest driver from here:

- https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.2.13.1016.zip
- https://cloud.google.com/bigquery/providers/simba-drivers#current_jdbc_driver_releases_12131016

And then tell DBeaver about the local install

**Comment by serge-rider** [comment]
We'll upgrade driver version in the next DBeaver version.

**Comment by serge-rider** [comment]
Workaround: download driver manually, extract it somewhere and all *.jar files as DBeaver libraries.

**Comment by uslss** [comment]
verified
