### ISSUE TITLE
No difference in Procedures and functions in overview (oracle)

### ISSUE THREAD

**Issue by BytesBytes** [dbeaver/dbeaver#11408]
**Is your feature request related to a problem? Please describe.** 
At the moment there doesn't seem to be a difference between procedures and functions (working on Oracle databases) in the connection overview. We have about 1400 procedures and 2000 functions. Even when using the filter, finding the right function for example costs extra time because several procedures occur in the overview as well (especially because in de past there was no naming convention on the database and it's not always clear from the object-name that it is a procedure or a function).

**Describe the solution you'd like**
If possible split up functions and procedures.

**Describe alternatives you've considered**
I know it's all in procedures and I use the filter, but it would be nice to see only at functions when you know you need a function.

**Additional context**
Related to issues #9952, #8018, #7046...

**Comment by kseniiaguzeeva** [comment]
It makes sence and will be implemented.

**Comment by LonwoLonwo** [comment]
related https://github.com/dbeaver/dbeaver/issues/11631 https://github.com/dbeaver/dbeaver/issues/7058

**Comment by uslss** [comment]
verified
