### ISSUE TITLE
dbeaver 7.3.5 not running on Mac OS Big Sur 11.2.1

### ISSUE THREAD

**Issue by jfreidkes-CA** [dbeaver/dbeaver#11415]
Hey all!
Maybe this is related to this issue: [https://github.com/dbeaver/dbeaver/issues/10345](https://github.com/dbeaver/dbeaver/issues/10345), but involving different versions (both OS and dbeaver).

### System information: 
- macOS Big Sur 11.2.1
- DBeaver version 7.3.5

<img width="539" alt="Screen Shot 2021-02-19 at 01 21 48" src="https://user-images.githubusercontent.com/71668181/108457828-07485e00-7252-11eb-9321-8d8e340c33b4.png">

### Problem observed:
dbeaver not opening at all.

I tried updating jdk, proposed in the [mentioned issue](https://github.com/dbeaver/dbeaver/issues/10345), but did not work:
`brew install --cask adoptopenjdk15`
`brew reinstall --cask adoptopenjdk15`

Any ideas? Thanks a lot!!

**Comment by kseniiaguzeeva** [comment]
Please try Java 11. It should help.

**Comment by jfreidkes-CA** [comment]
Hey! Thanks for replying. Already tried that and still not working… any other thing I could check?
Thanks!!

**Comment by uslss** [comment]
@jfreidkes-CA Could you try to install dbeaver using dmg file?

**Comment by mcvincekova** [comment]
> Hey! Thanks for replying. Already tried that and still not working… any other thing I could check?
> Thanks!!

Hi, experienced the same problem, and for me the [downloading](https://dbeaver.io/download/) and using the newest DBeaver version helped.
This is my current working setup
- macOS: `Big Sur version 11.2.2`
- DBeaver: `dbeaver-ce-21.0.1-macos.dmg`
- Java: `openjdk 11.0.2 2019-01-15`

Note:
During installation of the new DBeaver version, you can select an option to migrate your current connection settings, so it's not too painful.

**Comment by jfreidkes-CA** [comment]
Hi! Thanks to both of you @uslss and @mcvincekova for your replies!
I've already tried both, and not working either 😢 
Thanks for the help!

**Comment by uslss** [comment]
@jfreidkes-CA sorry for the late response.
Is issue still actual for you against 21.0.3?

**Comment by jfreidkes-CA** [comment]
@uslss Just tried and same behavior as previous versions, not working 😿

**Comment by ausiddiqui** [comment]
Having the same problem. I have macOS Big Sur 11.4 and even with 11.2 and 11.3 had this issue. The only version that works for me is dbeaver-ce-21.0.0. I have tried all the other versions from 21.0.1 through 21.1.0 with no luck. The minute the app is started the CPU levels spike to 110-200 % of CPU and the program goes into Not Responding mode and stays that way unless force quit.

**Comment by serge-rider** [comment]
@ausiddiqui Do you install from DMG archive from dbeaver.io website or from brew?
Are there any logs? (https://github.com/dbeaver/dbeaver/wiki/Log-files)
If not - could you try to make a thread dump? (https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump)

**Comment by ausiddiqui** [comment]
Usually when I get a pop-up message saying I need to update it points me to the dbeaver.io and I download the DMG from there to run the update. For this last experiment, I downloaded all the DMG files from the GitHub releases archive and ran them one at a time from latest to older versions until I found one that worked. I don't have logs, but when I get downtime on the weekend I can do the same exercise and try to generate some logs.

**Comment by ausiddiqui** [comment]
Still the case with 21.1.5 the latest version. Here is the thread-dump.txt promised months ago. The CPU usage stays at 100% as the program becomes non responsive and the memory usage is about 550 MB. There is no way to get to logs as the program hangs on loading - I can see my last opened query editor and the code but can't click into the text editor to change anything, the cursor changes to a spinning beach ball when hovering over the application. 

[thread-dump3.txt](https://github.com/dbeaver/dbeaver/files/7068823/thread-dump3.txt)

**Comment by batirch** [comment]
I am experiencing the same issue. Will there be an update? 

> Still the case with 21.1.5 the latest version. Here is the thread-dump.txt promised months ago. The CPU usage stays at 100% as the program becomes non responsive and the memory usage is about 550 MB. There is no way to get to logs as the program hangs on loading - I can see my last opened query editor and the code but can't click into the text editor to change anything, the cursor changes to a spinning beach ball when hovering over the application.
> 
> [thread-dump3.txt](https://github.com/dbeaver/dbeaver/files/7068823/thread-dump3.txt)

**Comment by batirch** [comment]
Here is my error log. 

[dbeaver error.docx](https://github.com/dbeaver/dbeaver/files/7242424/dbeaver.error.docx)

**Comment by uslss** [comment]
@ausiddiqui could you check if it is still present against the 21.3.1 version? Thanks in advance

**Comment by uslss** [comment]
There has been no update on the issue for a long time.
If it is still present, feel free to reopen it.
