### ISSUE TITLE
How to work with many MySQL server versions?

### ISSUE THREAD

**Issue by Carlos-SS-PMI** [dbeaver/dbeaver#11417]
Hi!
DBeaver is an excellent tool for manage many databases, and I want to use as much as possible.

I work with many MySQL versions (from 5.1 to 8.0.22) and I found a great mistake in "Driver manager" section. As you knowns, MySQL jar drivers 8 can't connect to MySQL 5.1 databases, and viceversa.

Steps:
In "Driver manager" I added a new driver for MySQL 8 correctly.
I setup a new MySQL connection for a database version 8, and I can connect.

In "Driver manager" I setup a driver for MySQL 5+ correctly.
I setup a new MySQL connection for a database version 5.1, but connection fails due it's using MySQL 8 driver.

Main problem is that in a "MySQL Connection", on "Driver settings", I can oly select as "Driver Type" one MySQL driver, and I must work with many MySQL drivers I've setup in "Driver manager".

How we can solve this?

Thanks!

**Comment by uslss** [comment]
Hi @Carlos-SS-PMI ,
you can use MySQL connection for 8+ versions and MySQL 5 connection for 5+ version
![image](https://user-images.githubusercontent.com/31996417/108877154-0297f700-7610-11eb-9056-b24eca8b2b75.png)

**Comment by Carlos-SS-PMI** [comment]
Thanks! Works like a charm! :-)

**Comment by alexdawn** [comment]
Thank you for the above fix!

Using dbeaver 22.2.2 and I have the same issue with mysql drivers, however searching I only see "MySQL"

I then noticed the search had defaulted to "popular" and not "all", could it default to "all"?

**Comment by E1izabeth** [comment]
Hi, @alexdawn. Please, create a separate issue for that.
