### ISSUE TITLE
need altibase many function..

### ISSUE THREAD

**Issue by davidoff2500** [dbeaver/dbeaver#11419]
**Is your feature request related to a problem? Please describe.**

1. If  double-click a table in the altibase in UI,  add or delete columns in the UI, and wish the script will be automatically generated.

2. Column depiction is not displayed when table is clicked.
3. 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Thank you.

**Comment by kseniiaguzeeva** [comment]
Please write in details which support do you need for altibase.
DBeaver allows to create/delete columns via Data Editor, generate SQL scripts etc.

**Comment by uslss** [comment]
There is no update on an issue for a long time.
If it is still actual for you - feel free to reopen an issue with an additional info
