### ISSUE TITLE
Please allow to save (not export as image!) ER Diagrams in 

### ISSUE THREAD

**Issue by sdudnic** [dbeaver/dbeaver#11410]
When I created a ER diagram, arranged all the tables, is there a way to save that configuration? I would like to reopen the diagram and to refresh it, but I don't want to restart a new ER diagram from the beginning

**Comment by dextok** [comment]
What's your dbeaver version and platform? I think ER diagram is saved as **erd** format by default. You can press **Ctrl + S** or hit the save button to save your diagram in ER diagrams folder.

**Comment by sdudnic** [comment]
I use the latest version, just downloaded. at time asking.

As I told, there is no need to save the **picture**, but to save the diagram objects disposal. 

Because I want my diagram objects be disposed in a way, not auto arranged. When I update/reload the diagram from the database, I would like to keep my objects in the same place, not rearrange each time the tables are updated.

**Comment by sdudnic** [comment]
I use the latest version, just downloaded. at time asking.

**Comment by uslss** [comment]
@sdudnic do you try to use Save the current contents button?
![image](https://user-images.githubusercontent.com/31996417/108987138-feb5b480-76a3-11eb-9d1c-5f1583b62392.png)

**Comment by sdudnic** [comment]
> @sdudnic do you try to use Save the current contents button? 

is not really clear what the button does. Where do it saves, what mean "contents". 

Suppose the scenario. I do a diagram, move objects. At a moment I 
a) "save" the diagram 
b) close the **diagram**. 
c) close the **DBeaver**. 
d) **modify** tables. 
e) Open DBeaver...

Where should I search for my "saved" diagram to see the DB modifications?

**Comment by uslss** [comment]
Previously created diagrams could be found in ER diagram folder at Project tab if you talk about [Custom diagrams](https://github.com/dbeaver/dbeaver/wiki/Custom-Diagrams)
Also ER diagrams are available for objects like table or schema at ER Diagram tab - https://github.com/dbeaver/dbeaver/wiki/Database-Structure-Diagrams

**Comment by sdudnic** [comment]
> Previously created diagrams could be found in ER diagram folder at Project tab if you talk about [Custom diagrams](https://github.com/dbeaver/dbeaver/wiki/Custom-Diagrams)
> Also ER diagrams are available for objects like table or schema at ER Diagram tab - https://github.com/dbeaver/dbeaver/wiki/Database-Structure-Diagrams

When I open a database, go to Tables and ViewDiagram

![image](https://user-images.githubusercontent.com/35489219/108990051-a4622700-7696-11eb-852f-9a4b3b15ca41.png)

I obtain a "dbo" "ER Diagram". When I click on "Save" where is it saved to open it?

because I have any .erd file, and any entry in the "ER Diagrams" folder...

**Comment by icrescenti** [comment]
@akilovich Already done, waiting to merge [pull request](https://github.com/dbeaver/dbeaver/pull/13021)

**Comment by flambchap** [comment]
@icrescenti That's great! Serge merges PRs in our project. When you'll finish your work, I'll draw his attention to your PR.

**Comment by sdudnic** [comment]
my licence is gone, so I can't test anymore

**Comment by uslss** [comment]
verified
