### ISSUE TITLE
Oracle: Dependencies tab for procedures/functions

### ISSUE THREAD

**Issue by F0xD8rk** [dbeaver/dbeaver#11418]
**Describe the solution you'd like**
It would be nice to be able to view the dependencies (the objects it depends on, as well as other objects that depend on the procedure/function) of a procedure/function in the same way as for example a package. This helps us a lot for debugging/solving problems. 

**Additional context**
We now have to open each function/procedure seperately and navigate through it to find all objects used in it. If we want to adjust a procedure/function, we also don't know where it is being used and what objects depend on the procedure/function. This would help in a big way to know the impact of potential changes.

**Comment by ShadelessFox** [comment]
Implemented:

![java_tyn2omVmoF](https://user-images.githubusercontent.com/35821147/115261250-2113fd80-a13c-11eb-8308-2046cd780c7e.png)

**Comment by uslss** [comment]
verified
