### ISSUE TITLE
poor search functionality in the Github wiki

### ISSUE THREAD

**Issue by aisbergde** [dbeaver/dbeaver#11424]
#### Describe the problem you're observing:

There are a lot of features in dbeaver, and a lot of them are documented in the wiki, but the documentation is hard to find.

#### Steps to reproduce, if exist:

for example, I am looking for information about virtual columns and virtual references

The first place to search is here:

- https://dbeaver.com/docs/wiki/  
  There is a search button, I enter "virtual", but the results are only from release notes, not from Wiki content
- on https://dbeaver.com/docs/wiki/ I use the "download PDF", and in the PDF I search for "virtual"  
  and I get only one place about "Defining Virtual Keys"  
  so it looks like the Wiki doesn't contains any information about virtual columns. Or the PDF doesn't contain the whole Wiki
- now I search in google for "dbeaver virtual columns" and I also find this:  
  https://github.com/dbeaver/dbeaver/wiki/Virtual-column-expressions

So it looks like there is a documentation in the Wiki, but it is hard to find. And the export of the Wiki doesn't contain the whole Wiki, but only the "General usage guide"

I understand that this is an issue with GitHub Wiki functionality.

A workaround I could imagine would be to offer a second PDF Download containing the whole Wiki.

Or a user could clone the whole Wiki and search locally using a fulltext search.

Or are there any ideas how to easily find any content in the dbeaver wiki?

It looks like the dbeaver has so many features, I need. It is a tragedy that I have only now tried the program.

I had tried several other database managers before, and stopped at some point because it doesn't get any easier with most of them than with SSMS or Azure Data Studio. dbeaver convinces with its quite intuitive handling and such features as virtual keys, ER display, filtering and sorting data in the grid with simultaneous display of linked tables.

However, features are only as good as their documentation is easy to find. That's why I wanted to explicitly point out the problems with the wiki. After all, this will also affect other new users.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by m-ovs** [comment]
We improved search functionality on our website. Thank you for the report.
