### ISSUE TITLE
open with > web browser > missing line breaks in multi-line-strings

### ISSUE THREAD

**Issue by aisbergde** [dbeaver/dbeaver#11423]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.3.5.202102141704
- Additional extensions

#### Connection specification:
- Database name and version: SQL Server 2019
- Driver name: I don't know
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: no

#### Describe the problem you're observing:

- line breaks are removed in the "open with  > Web browser" result
- text is centered, this makes it hard to read. I would prefer left aligned or some logic depending on data type
  - text - left
  - numbers - right
  - but never centered
  - 
#### Steps to reproduce, if exist:

- use a field of type varchar or nvarchar (I have only nvarchar)
- enter content with line breaks
- have a look in dbeaver, it looks correctly
- use "open with > Web Browser"
- look at the result and you miss linebreaks

![image](https://user-images.githubusercontent.com/9020187/108481391-7052c480-7298-11eb-86a2-a06bec31ddfe.png)

![image](https://user-images.githubusercontent.com/9020187/108481475-8b253900-7298-11eb-8cb6-6aab61c5e681.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by aisbergde** [comment]
I think the missing linebreak could be fixed by adapting the used CSS and changing some white-space settings

**Comment by ShadelessFox** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/35821147/124131939-f70a8000-da88-11eb-8592-3f9fb7d9aa24.png)

**Comment by uslss** [comment]
verified
