### ISSUE TITLE
Context menu in ER diagram - add DELETE TABLE option

### ISSUE THREAD

**Issue by GiantCrocodile** [dbeaver/dbeaver#1143]
It would be nice to have an option to delete a table from ER diagram by just selecting it and then calling a delete statement from context menu. This is as like as #1019: ER diagram editor will be read only till 4.x release.

**Comment by uslss** [comment]
Issue isn't still actual on 6.2.0
Ticket closed

**Comment by GiantCrocodile** [comment]
So is this feature implemented nowadays in DBeaver @uslss?
