### ISSUE TITLE
Use getLargeUpdateCount() to retrieve update count for a query

### ISSUE THREAD

**Issue by findepi** [dbeaver/dbeaver#11439]
**Is your feature request related to a problem? Please describe.**

A user reported using DBeaver with Trino and being confused by the update count show as 2147483647 for a `CREATE TABLE AS ...` query that actually created more rows.
The value 2147483647 comes from https://github.com/trinodb/trino/blob/58e7a9643dca631b819dd440511b7b400b2821f2/client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoStatement.java#L309 
The JDBC spec doesn't seem to be explicit how the overflow should be handled, and JDBC drivers seem inconsistent about this (eg some will just throw an exception).

**Describe the solution you'd like**
There is `java.sql.Statement#getLargeUpdateCount` which can be used to retrieve the update count without being limited to `int` representation.
If a driver does not implement this API method, `UnsupportedOperationException` will be thrown (per the `default` implementation of the interface method). This can be handled by falling back to `getUpdateCount` which is used today.

**Comment by kseniiaguzeeva** [comment]
It is the interesting issue. Thank you for the report.

**Comment by ShadelessFox** [comment]
The model was updated to use `getLargeUpdateCount`, if available.

**Comment by kseniiaguzeeva** [comment]
@findepi unfortunately, I do not have so big table to test. Do you have a possibility to check the fix in EA version https://dbeaver.io/files/ea/?

**Comment by kseniiaguzeeva** [comment]
Please ask to reopen, if the issue is still actual.
