### ISSUE TITLE
Can not get the latest data

### ISSUE THREAD

**Issue by Singa-dev** [dbeaver/dbeaver#11438]
#### System information: 
- MacOS Big Sur Version 11.2(20D64)
- DBeaver EE Version 7.3.0.202012061950
- Additional extensions

#### Connection specification:
- MySQL 8
- 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
-- Yes use SSH tunnels

#### Describe the problem you're observing:
I am sure I have been inserted a new data, but I can not get this data by command select.
When i restart DBeaver, I can get it.

#### Include any warning/errors/backtraces from the logs
No

**Comment by uslss** [comment]
Hi @Singa-dev ,
unfortunately, cannot reproduce an issue.
Do you use sql editor or UI to insert new values? Can you provide more steps to reproduce an issue (probably video)?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen this issue with an additional info
