### ISSUE TITLE
Exporting data of Snowflake query does not work. Trying it several times and each time getting different/incorrect results. 

### ISSUE THREAD

**Issue by DKholev** [dbeaver/dbeaver#11431]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
Hi @DKholev ,
could you provide an error log and steps to reproduce an issue?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info
