### ISSUE TITLE
[Oracle] Wrong object type for partitioned tables synonyms

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#11455]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 7.3.5
- Additional extensions n/a

#### Connection specification:
- Database name and version Oracle 11
- Driver name ojdbc19
- Do you use tunnels or proxies (SSH, SOCKS, etc)? n/a

#### Describe the problem you're observing:
I have a synonym to a partitioned table; DBeaver joins ALL_SYNONYMS with ALL_OBJECTS, but that way many rows are returned: the table itself and all of his partitions. DBeaver then goes on to say my synonym points to a table partition (which AFAIK is impossible)
![immagine](https://user-images.githubusercontent.com/2157006/108835913-71556000-75d0-11eb-893c-6a5fe705fdc3.png)

The offending query should be this one (the MAX prefers TABLE PARTITION to just TABLE): 
```
SELECT OWNER, SYNONYM_NAME, MAX(TABLE_OWNER) as TABLE_OWNER, MAX(TABLE_NAME) as TABLE_NAME, MAX(DB_LINK) as DB_LINK, MAX(OBJECT_TYPE) as OBJECT_TYPE FROM (
SELECT S.*, NULL OBJECT_TYPE FROM ALL_SYNONYMS S WHERE S.OWNER = 'PUBLIC'
UNION ALL
SELECT S.*, o.*, O.OBJECT_TYPE FROM ALL_SYNONYMS S, ALL_OBJECTS O
WHERE S.OWNER = 'PUBLIC'
AND O.OWNER=S.TABLE_OWNER AND O.OBJECT_NAME=S.TABLE_NAME
)
GROUP BY OWNER, SYNONYM_NAME
ORDER BY SYNONYM_NAME
```

Possible workarounds: exclude the 'TABLE PARTITION', 'TABLE SUBPARTITION' types, or possibly better add this clause to the second part of the union all: `AND SUBOBJECT_NAME IS NULL` (SUBOBJECT_NAME is a column in ALL_OBJECTS).

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
