### ISSUE TITLE
Trigger code from Oracle db not viewable

### ISSUE THREAD

**Issue by bjkluft** [dbeaver/dbeaver#11454]
#### System information: 
- Windows 10 Pro
- DBeaver version 7.3.5.202102151746
- Java version 1.8.0_181-b13

#### Connection specification:
- Oracle jdbc driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I'm not able to view the trigger declarations, using a Oracle Instant Client with the same database and user I'm able to view the trigger code. Also when using another tool (Oracle SQL developer) with a jdbc driver I'm again able to view the code.

#### Include any warning/errors/backtraces from the logs
[20210223_dbeaver.log](https://github.com/dbeaver/dbeaver/files/6028349/20210223_dbeaver.log)

**Comment by uslss** [comment]
hi @bjkluft ,
cannot reproduce the issue. works ok for me,
![image](https://user-images.githubusercontent.com/31996417/108866934-bc3d9a80-7605-11eb-8097-21c697aa28ce.png)
Can you share how declaration tab looks for you? Thanks in advance

**Comment by bjkluft** [comment]
Hello uslss,

We managed to solve the issue ourselves. We had to explicitly allow the user (me) to view the trigger data.
Thank you for your reply.
