### ISSUE TITLE
DBeaver hangs with many templates

### ISSUE THREAD

**Issue by mikkk3l** [dbeaver/dbeaver#11452]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 7.3.5
- Java version 1.8
- Additional extensions

#### Connection specification:
- Database name and version DB2
- Driver name JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by mikkk3l** [comment]
I attach a video of the behaviour:

![2021-02-23_DBeaver_manyTemplatesHangs](https://user-images.githubusercontent.com/15341836/108822668-af965380-75bf-11eb-8295-260f8e08b36c.gif)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
