### ISSUE TITLE
saved svg images does not contain the whole diagram

### ISSUE THREAD

**Issue by sdudnic** [dbeaver/dbeaver#11467]
#### System information: 
- Operating system (distribution) and version: Windows 10 x64
- DBeaver Version 7.3.0.202012061950
- Additional extensions

#### Connection specification:
- Database name and version Sql Server
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
saving the diagram as svg file saves a document witch view does not contain all the diagram.

I think **by default** the program should save the SVG to include in view all the diagram objects. 
**An option** would be to propose to the user to save the current view (include only visible part), or (by default) the entire diagram.

#### Steps to reproduce, if exist:
 - create/open a ER diagram, 
 - zoom it at a certain level
 - save as svg
 - open the svg in Chrome 
 - observe the partial rendering.

![image](https://user-images.githubusercontent.com/35489219/108991617-9c0aeb80-7698-11eb-9149-ca233bb4247c.png)

![image](https://user-images.githubusercontent.com/35489219/108992774-f6f11280-7699-11eb-8137-f59e0f7cbda1.png)

#### Include any warning/errors/backtraces from the logs

The problem is that the document area does not cover all svg objects in the drawing, that can be seen opening the file in Inkscape

![image](https://user-images.githubusercontent.com/35489219/108993288-a6c68000-769a-11eb-87a9-02ed8bf974dd.png)

The solution would be to resize the svg view to the whole drawing: 

![image](https://user-images.githubusercontent.com/35489219/108994109-ad092c00-769b-11eb-980f-234621315a9c.png)

**Comment by knbknb** [comment]
I have the same problem, on Ubuntu Linux, 20.04, dbeaver 7.3.5,      DBeaver SVG Extension	1.0.87.202102141704

There was a [workaround from 2019](https://github.com/dbeaver/dbeaver/issues/3099#issuecomment-490088699) for the PNG file writer, but it does not work for me and the SVG writer.

**Comment by sdudnic** [comment]
> I have the same problem, on Ubuntu Linux, 20.04, dbeaver 7.3.5,      DBeaver SVG Extension	1.0.87.202102141704
> 
> There was a [workaround from 2019](https://github.com/dbeaver/dbeaver/issues/3099#issuecomment-490088699) for the PNG file writer, but it does not work for me and the SVG writer. 
> 
> 

Did you try my workaround with inkscape?

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by knbknb** [comment]
> > I have the same problem, on Ubuntu Linux, 20.04, dbeaver 7.3.5,      DBeaver SVG Extension	1.0.87.202102141704
> > There was a [workaround from 2019](https://github.com/dbeaver/dbeaver/issues/3099#issuecomment-490088699) for the PNG file writer, but it does not work for me and the SVG writer.
> 
> Did you try my workaround with inkscape?

No . I tried to open the image file with CHrome and Firefox. Both opened the cropped images instantly, but I didn't really check the SVG code. 

The cropped areas are not really findable with "Find in page" feature of the browser. 
I do not know much about svg, and the SVG code countless little  `<path>` elements because every table row starts with a little icon for the datatype. That makes the code very verbose. 

Then I gave up.

**Comment by uslss** [comment]
still reproducible
![2021-03-11_15h45_27](https://user-images.githubusercontent.com/31996417/110789418-e8515080-8280-11eb-9bbe-da62a98abd7d.gif)

**Comment by uslss** [comment]
verified
