### ISSUE TITLE
User interface language won't change

### ISSUE THREAD

**Issue by feeva** [dbeaver/dbeaver#11464]
#### System information: 
- Windows 10
- DBeaver 7.3.5

#### Describe the problem you're observing:
Changing user interface language from the preferences window has no effect. After restarting DBeaver, I don't see any change.

#### Include any warning/errors/backtraces from the logs
I couldn't find any relavant messages from logs.

**Comment by kseniiaguzeeva** [comment]
It will be fixed in ticket https://github.com/dbeaver/dbeaver/issues/10654.
As a workaround open properties of DBeaver label and delete (or set if you need in English)  `-nl en` from object line.  You will be able to change language in Preferences>User interface in DBeaver after this.

**Comment by cryptedx** [comment]
Just run DBeaver as Adminstrator and you can change it. Easiest way my SQL Bros!
