### ISSUE TITLE
Over 70s can not open a table even an empty table  

### ISSUE THREAD

**Issue by honey-yogurt** [dbeaver/dbeaver#11465]
os : macOs 10.15.7
dbeaver version : 7.3.5
java version: 8
drive：8.0.17
When I open one table  ,it always costs over 70s ,even an empty table. how can I solve it?

**Comment by honey-yogurt** [comment]
And it always notices :  DataSource was invalidated, live  connection count 2/2

**Comment by p91paul** [comment]
you failed to mention which database are you on, but you can try setting the connection keep-alive timeout on connection settings

**Comment by kseniiaguzeeva** [comment]
Could you please send the database and what query is running in Query Manager at this time (Window>Show view>Query manager). Enable all query types here:
![dbeaver_aakNPCHUia](https://user-images.githubusercontent.com/51405061/109002689-940e7400-76b7-11eb-9be8-9c48f2d18e0a.png)
