### ISSUE TITLE
[Google Cloud Sql] DBeaver 7.3.5 - Cannot connect to Postgres via Google Cloud SQL connection

### ISSUE THREAD

**Issue by vadim3004** [dbeaver/dbeaver#11462]
#### System information: 
- Operating system: Windows 7
- DBeaver version: 7.3.5
- Java version: 8 update 121 

#### Connection specification:
- Database: Postgres 13
- Not using tunnels/proxies 

When trying to connect with Google Cloud Sql driver, the following error is displayed:
```
Something unusual has occurred to cause the driver to fail. Please report this exception.
  [mot-cz:europe-west1:mot-dev-13] Failed to update metadata for Cloud SQL instance.
  [mot-cz:europe-west1:mot-dev-13] Failed to update metadata for Cloud SQL instance.
    400 Bad Request
POST https://oauth2.googleapis.com/token
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
    400 Bad Request
POST https://oauth2.googleapis.com/token
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```
The same database works fine with regular Postgres connection.

**Comment by uslss** [comment]
Unfortunately, we cannot investigate the issue for now due to the absence of the environment

**Comment by LonwoLonwo** [comment]
Google cloud support was added in LE/EE/UE products in DBeaver version 22.0.3
https://github.com/dbeaver/dbeaver/issues/12581
