### ISSUE TITLE
No OPTIONS data for columns of foreign table in DDL or UI

### ISSUE THREAD

**Issue by mkgrgis** [dbeaver/dbeaver#11477]
[x:postgres]

**Postgresql 9.6 +**

**Is your feature request related to a problem? Please describe.**
No `OPTIONS` (SQL lexema) data are displayed for columns of foreign table in UI or in DDL.

**Describe the solution you'd like**
New column for metadata for "Columns" display table for a foreign table
New textarea or area for key/value array for a column of a foreign table 

**Additional context**

Example for tests from README from https://github.com/ibarwick/firebird_fdw

```
CREATE FOREIGN TABLE fb_test_table(
  id SMALLINT OPTIONS (column_name 'test_id'),
  val VARCHAR(2048) OPTIONS (column_name 'test_val'),
  fl BOOL OPTIONS (implicit_bool_type 'true', column_name 'test_0_or_1')
)
SERVER firebird_server
OPTIONS(
  table_name 'fdw_test'
);
```
[A Notice about datasource for options of columns](https://www.postgrespro.ru/docs/postgresql/13/catalog-pg-attribute).

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by LonwoLonwo** [comment]
Hello @mkgrgis 
Which DBeaver version do you use?

As I can see, DBeaver shows column and table options in DDL. Only not quite in correct form.

![2021-04-14 10_36_02-Window](https://user-images.githubusercontent.com/45152336/114673764-37225800-9d0f-11eb-9943-cad7b9cb95d9.png)

**Comment by mkgrgis** [comment]
Hello, @LonwoLonwo !
There is problems in 7.3.5, but no problems in 21.0.3. Thanks!
In 21.0.3 there is only not beautiful formatting of column's options. Values of options usually are case sensetive quotes.

**Comment by LonwoLonwo** [comment]
@mkgrgis Thanks for the clarification.

**Comment by LonwoLonwo** [comment]
options DDL fixed. Now we show options without "="

**Comment by Matvey16** [comment]
Verified
