### ISSUE TITLE
Case sensitive option doesn't work in Full-Text search

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11471]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.5 EA

#### Connection specification:
- Database name and version SQL Server

#### Steps to reproduce, if exist:
1. Open full-text search and enter a word from a table in incorrect case
2. Enable Case sensitive search and begin the search

Expected: the value is not found because the wrong case were entered in Search
Actual result: the value is found
![dbeaver_AWpFfDss8m](https://user-images.githubusercontent.com/51405061/109018731-6af6df00-76c9-11eb-962f-db96b8735607.png)

**Comment by the-ge** [comment]
Same issue here on Kubuntu 22.04.1, DBeaver 22.3.0, MariaDB 10.3.37.

**Comment by E1izabeth** [comment]
Can't reproduce against DBeaver 23.0.5
