### ISSUE TITLE
Filter doens't work on synonyms in Oracle

### ISSUE THREAD

**Issue by BytesBytes** [dbeaver/dbeaver#11476]
#### System information: 
- Operating system (distribution) and version: Windows 10 version 20H2 Build 19042.804
- DBeaver version: 7.3.5.202102141704
- Additional extensions

#### Connection specification:
- Database name and version: Oracle database 12c
- Driver name: Oracle Client 12 - 12.2.0.1.0 - oracle.jdbc.OracleDriver library 21.1.0.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Filter doesn't work on Synonyms in Oracle
#### Steps to reproduce, if exist:
Open a database connection
Type (part of) an existing trigger in the  filter
Open synonyms => all synonyms visible, not only the ones matching the filter

![image](https://user-images.githubusercontent.com/79206887/109029703-63ccd280-76c3-11eb-81b7-535e5da17d17.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/35821147/114600984-a7909100-9c9d-11eb-92de-a7ef79b406c3.png)

**Comment by uslss** [comment]
verified
