### ISSUE TITLE
Wrong default length for numeric type

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11489]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.0 EA

#### Connection specification:
- Database name and version SQL Server

#### Steps to reproduce, if exist:
1. Create a numeric column
2. Save it

**Expected**: the column is created
**Actual resul**t: the column is not created and the error appears: 
`SQL Error [2750] [S0001]: Column or parameter #7: Specified column precision 100 is greater than the maximum precision of 38.`

**Comment by LonwoLonwo** [comment]
Fixed for numeric and decimal columns.

**Comment by uslss** [comment]
verified
