### ISSUE TITLE
invalidate ssh tunnel

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#11487]
Dbeaver 7.3.5
Postgresql 12

Добрый день. Работаю совсем с другой базой db_lite  и более того, сеть для БД на скрине db_prod  выключена и доступа к этой базе нет.

Тем не менее приложение раз в 2 секунды пытается достучаться до ssh тоннеля, который указан в настройках БД db_prod. Все начинает тормозить.

![изображение](https://user-images.githubusercontent.com/61137576/109113834-a98aa900-775e-11eb-8f85-3091f09d90b0.png)

Почему пытается достучаться именно до db_prod и зачем не понятно, никаких окон с этой бд не открыто. В Dbeaver настроена куча других баз на этом же хосте.

**Comment by uslss** [comment]
Probably, keep-alive values for connection or ssh-tunnel are not zero. Could you check them?
![image](https://user-images.githubusercontent.com/31996417/110764443-1ffdcf80-8264-11eb-9405-97b50a25e42d.png)
![image](https://user-images.githubusercontent.com/31996417/110764472-2a1fce00-8264-11eb-85eb-b2f03a0aa2dd.png)

**Comment by detkliff** [comment]
for database keep-alive not null in mz config, but it is true for available resourses. It is not true for unavalibale resourses.

**Comment by uslss** [comment]
Could you provide a debug-log?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info
