### ISSUE TITLE
A query must be executed before performing export if ResultSet was closed

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11488]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.5 EA

#### Steps to reproduce, if exist:
1. Open new SQL Editor and execute a query
2. Close ResultSet
3. Select Export from Query in the context menu

Expected: the export wizard appears
Actual result: ResultSet with grey background appears

https://user-images.githubusercontent.com/51405061/109116417-86a5c800-7751-11eb-9b12-0e33037d8161.mp4

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/6041093/dbeaver-debug.log)
[.log](https://github.com/dbeaver/dbeaver/files/6041094/default.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
