### ISSUE TITLE
Row coloring via like check against text

### ISSUE THREAD

**Issue by Actualization** [dbeaver/dbeaver#11486]
Row coloring currently supports = checks and between two values checks to color rows.

Right clicking a result set or table column -> View/Format option -> Row Colors... option
produces a menu that allows you to color rows based on = value

In addition to the = check and the checkbox to use gradients between two values
it would be useful if coloring via a like or ilike check against text in a column was supported.

["Rows Coloring" documentation under header "Rows Coloring"](https://dbeaver.com/docs/wiki/Data-View-and-Format/) leads me to assume this is not an existing feature.

![image](https://user-images.githubusercontent.com/32940000/109101457-ba063980-76f4-11eb-8298-b262316dde68.png)

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by ShadelessFox** [comment]
Now you can choose which operator to use:

![java_c1DvC1Qf7r](https://user-images.githubusercontent.com/35821147/122218166-d3570f80-ceb6-11eb-8411-e8094ad4d2ee.png)

**Comment by uslss** [comment]
verified
