### ISSUE TITLE
ctrl-f Find defaults to cell under cursor

### ISSUE THREAD

**Issue by fossildoc** [dbeaver/dbeaver#11480]
- Operating system (distribution) and version
- ubuntu 18.04
- DBeaver version
- 7.3.5
- Java version 
- 1.8.0_282

- Database name and version
- postgresql  12.6
- Driver name
- jdbc postgresql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no
#### Describe the problem you're observing:
ctrl+f (Find) search field defaults to the contents of the cell under the cursor. If the search fails and I switch to another table, the search field changes to whatever happens to fall under the cursor. Even if the dropdown list is used to restore the search field, or even if I retype it, the Find system continues to reference the original table. This requires that the Find window be closed and re-opened in order for it to reference the new, second, table. Instead of all this, the search field should have no default and should not change automatically for any reason, and Find should change its reference to whatever table the user switches to, without having to close and re-open it.

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
Fixed / Implemented:

https://user-images.githubusercontent.com/35821147/115051541-9afe7980-9ee5-11eb-9936-1b082654074b.mp4

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by fossildoc** [comment]
This bug has not been fixed. The system behaves exactly as it did when I made the o.p.

**Comment by ShadelessFox** [comment]
Can you please provide more information and demonstrate your issue by capturing a video?
