### ISSUE TITLE
option to disable annoying tooltips

### ISSUE THREAD

**Issue by fossildoc** [dbeaver/dbeaver#11483]
**Is your feature request related to a problem? Please describe.**
Tooltips are everywhere. It's hardly possible to move the cursor around without having annoying tooltips pop up. An experienced user doesn't need them anymore, but like Freddie Kruger, they keep rising and going forth.

**Describe the solution you'd like**
Give us an option to turn off all tooltips. And I mean all of them.

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by uslss** [comment]
duplicates #9472
