### ISSUE TITLE
Stop changing displayed columns hidden by custom filter

### ISSUE THREAD

**Issue by fossildoc** [dbeaver/dbeaver#11484]
**Is your feature request related to a problem? Please describe.**
Customize Filters allows me to turn off the display of columns which are not relevant to the context I'm working in. But everytime I do a DB Full-Text search, the system will turn on the display of all the columns of every table which has a search hit, even if there are no hits in those columns. This is extremely annoying. The "remove all filters/orderings" button does not fix it.

**Describe the solution you'd like**
When the search results window, which pops up after a DB Full-Text search, is closed, the system should restore the original state of column displays.

**Comment by kseniiaguzeeva** [comment]
Thank you for suggestion.

**Comment by defalt926** [comment]
Hi! Can you make pictures about how search filters work? I want to work on this issue, but i am a beginner dbeaver user and this is my first contribute.

**Comment by fossildoc** [comment]
![BeforeSearch](https://user-images.githubusercontent.com/17547612/111077057-7453ba00-84c5-11eb-99b5-7bb74aceffa3.png)
The picture above shows a part of the verb table. It shows the columns pres, decl, def.

![FilterWindow](https://user-images.githubusercontent.com/17547612/111077074-859cc680-84c5-11eb-877b-48a034eafccc.png)
![SearchWindow](https://user-images.githubusercontent.com/17547612/111077091-90575b80-84c5-11eb-9088-7fd57c5ca7aa.png)
The picture above shows what I get if I click DB Full-Text for that table, and set my search parameters.

![SearchResults](https://user-images.githubusercontent.com/17547612/111077102-98af9680-84c5-11eb-917b-9c35700fd4bc.png)
The picture above shows what I see after I click Search in the previous picture. Notice the results window at the bottom, which shows that a search hit has occurred in the verb table. The pres, decl, def columns are still displayed, which is correct.

![ClickedOnVerb](https://user-images.githubusercontent.com/17547612/111077111-a107d180-84c5-11eb-96a4-c5a650164b20.png)
The picture above shows what happens when I click on verb in the search results window. The p,w,s columns are now displayed; they have nothing to do with the search results. This is incorrect behavior. Notice also that there is a lot of stuff in the filters line just above the column headings.

![ClosedSearchResults](https://user-images.githubusercontent.com/17547612/111077118-a82edf80-84c5-11eb-9337-213065667a9b.png)
The picture above shows what I see after I close the search results window. No surprises here; it's the same view of the verb table as in the previous picture. Now comes the good part.

![RemoveAllFilters](https://user-images.githubusercontent.com/17547612/111077126-b11fb100-84c5-11eb-9db8-e0b8372a18a5.png)
The picture above shows what I get after I click on the Remove All Filters button. The original table, verb, is shown in all its glory, including p,w,s columns which were originally filtered out. Notice also that the def column has been severely shortened.
This is extremely annoying behavior. Every table which has a search hit will be left with previously hidden columns now revealed, and the last column of the table will be shortened.

**Comment by fossildoc** [comment]
I don't think cut & paste for images is working on this site, so I'm sending the images again by drag & drop.
![BeforeSearch](https://user-images.githubusercontent.com/17547612/111077057-7453ba00-84c5-11eb-99b5-7bb74aceffa3.png)
![FilterWindow](https://user-images.githubusercontent.com/17547612/111077074-859cc680-84c5-11eb-877b-48a034eafccc.png)
![SearchWindow](https://user-images.githubusercontent.com/17547612/111077091-90575b80-84c5-11eb-9088-7fd57c5ca7aa.png)
![SearchResults](https://user-images.githubusercontent.com/17547612/111077102-98af9680-84c5-11eb-917b-9c35700fd4bc.png)
![ClickedOnVerb](https://user-images.githubusercontent.com/17547612/111077111-a107d180-84c5-11eb-96a4-c5a650164b20.png)
![ClosedSearchResults](https://user-images.githubusercontent.com/17547612/111077118-a82edf80-84c5-11eb-9337-213065667a9b.png)
![RemoveAllFilters](https://user-images.githubusercontent.com/17547612/111077126-b11fb100-84c5-11eb-9db8-e0b8372a18a5.png)

**Comment by defalt926** [comment]
I see your problem. I do not have issue like shortened columns after clicking on remove all filters. But I am going to try fixing the displaying of unselected columns after search in full text.

**Comment by LonwoLonwo** [comment]
Implemented in DBeaver 21.3.0.

Now Dbeaver will try to find open data viewers with filters or saved tables filters and then add new search constraints for the table.

![iXhtZoZ2aM](https://user-images.githubusercontent.com/45152336/141426282-79b5f8c3-39e7-4823-8c25-79bb2606e8a4.gif)

**Comment by uslss** [comment]
verified
