### ISSUE TITLE
indexed search for ctrl-f Find

### ISSUE THREAD

**Issue by fossildoc** [dbeaver/dbeaver#11481]
**Is your feature request related to a problem? Please describe.**
DB Full-Text Search has a nice feature: indexed search. This means that only indexed columns, which are generally the most important, and searched, and not other columns which may be irrelevant. This feature is not available on ctrl-f Find, which causes unwanted search hits.

**Describe the solution you'd like**
Add indexed search to ctrl-f Find.

**Comment by uslss** [comment]
Could you clarify what search are you talking about? Probably screenshots can be very helpful

**Comment by fossildoc** [comment]
Thank you for your response. There is a typo in my OP which may have caused
some confusion: "and searched" should be "are searched".
To clarify, attached are two screenshots.
1. full.png shows the window that appears when "DB Full-Text search" is
clicked. You will see a checkbox labeled "Fast search (indexed)". That is a
very useful feature because it limits the search to only indexed columns,
which are the ones most often searched.
2. ctrl-f.png shows the window that appears when ctrl-f is pressed. There
is no "Fast search (indexed)" capability. My suggestion is to add that
capability to this window.

Also, ctrl-f.png has a "Regular expression" checkbox, which is also a very
useful feature. It is lacking in DB Full-text search; I would like to see
it added.

**Comment by uslss** [comment]
@fossildoc could you post pictures once again?
Unfortunately, I can't see it :( 
![image](https://user-images.githubusercontent.com/31996417/110937282-3464c980-8343-11eb-808a-fe9b9dca6ce1.png)

**Comment by fossildoc** [comment]
I do not see any way to upload images to my OP in github, so I have
attached both files to this email again. If you cannot see them, please
send me explicit instructions on how to add them to my OP.

**Comment by p91paul** [comment]
@fossildoc you have to upload them by posting your comment on the Github web interface. Github allows replies through emails, but does not understand email attachments.

**Comment by fossildoc** [comment]
x-special/nautilus-clipboard
copy
file:///home/richard/full.png
x-special/nautilus-clipboard
copy
file:///home/richard/ctrl-f.png

**Comment by fossildoc** [comment]
Cut & paste for images does not seem to be working on this site, so I am sending the images again by drag & drop.
![full](https://user-images.githubusercontent.com/17547612/111077306-90a42680-84c6-11eb-8681-61262a4264e7.png)
![ctrl-f](https://user-images.githubusercontent.com/17547612/111077310-9437ad80-84c6-11eb-9366-044dfc07ae17.png)

**Comment by fossildoc** [comment]
This request has been resubmitted as #13876.
