### ISSUE TITLE
Column labels disappear after sorting in create key dialogue

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11490]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.0 EA

#### Steps to reproduce, if exist:
1. Open Create unique key dialogue
2. Press Column header in the opened window several times

**Expected**: the columns are sorted ASC/DESC
**Actual result**: the columns are sorted and their labels dipsapear

https://user-images.githubusercontent.com/51405061/109123766-3df30c80-775b-11eb-8300-f8da48f1a382.mp4

**Comment by uslss** [comment]
verified
