### ISSUE TITLE
Check constraint is not displayed in table DDL

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11495]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.0

#### Connection specification:
- Database name and version SQL Server

#### Steps to reproduce, if exist:
Open DDL tab for a  table with check constraint, e.g. ```
CREATE TABLE Persons (
    ID int NOT NULL,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int CHECK (Age>=18)
);```

**Expected**: Check constraint is displayed in DDL
**Actual result**: Check constraint is not mentioned in table DDL
![dbeaver_sE2ZhS4oET](https://user-images.githubusercontent.com/51405061/109141959-5836e580-776f-11eb-9501-79bb6ea93e28.png)

**Comment by LonwoLonwo** [comment]
Fixed in 21.0.2

**Comment by uslss** [comment]
![image](https://user-images.githubusercontent.com/31996417/113110966-5c43a080-9210-11eb-8ece-7da37df96d0c.png)

**Comment by LonwoLonwo** [comment]
Definition and constraint names fixed.

**Comment by uslss** [comment]
verified
