### ISSUE TITLE
Shortcuts Ctrl+Alt+Enter, Ctrl+Enter do not work with focus in SQL Editor and Data Editor

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11493]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.0

#### Steps to reproduce, if exist:
1. Save an SQL and close it
2. Open Data Editor/New SQL Editor and press Ctrl+Alt+Enter/Ctrl+Enter

Expected: SQL Console/Recent SQL Editor window is opened
Actual result: no visible changes

**Comment by serge-rider** [comment]
It is not a bug. Ctrl+enter shortcut works only in database navigator.
