### ISSUE TITLE
System tables in firebird needs to be hidden in ERD

### ISSUE THREAD

**Issue by teson2000** [dbeaver/dbeaver#11496]
Firebird system tables needs to be hidden by default in the tables list.
Earlier discussion at https://github.com/dbeaver/dbeaver/pull/7223

Although it's possible to set a table filter as

RDB\$%
MON\$%
SEC\$%

they also mess up the ER-diagram.

It believe the list may be based on the version independent
SELECT RDB$RELATION_NAME FROM RDB$RELATIONS
WHERE RDB$SYSTEM_FLAG = 0

**Comment by kseniiaguzeeva** [comment]
You can hide them via connection context menu Connection view>Show system objects (disable them)
![dbeaver_xjWO9KLmtW](https://user-images.githubusercontent.com/51405061/109152449-9090f080-777c-11eb-8332-f1b8987b4093.png)

**Comment by teson2000** [comment]
Thanks, it works for the table list but ER-diagram is still populated with the (51) system tables.
  
![fb](https://user-images.githubusercontent.com/1379148/109162632-b7e5be80-7778-11eb-9d4d-8372042dce93.png)

**Comment by teson2000** [comment]
It seems to be implemented in the jdbc-driver jaybird, looking at:
https://www.firebirdsql.org/file/documentation/drivers_documentation/java/4.0.x/docs/org/firebirdsql/jdbc/FBDatabaseMetaData.html#getTables(java.lang.String,java.lang.String,java.lang.String,java.lang.String%5B%5D)

So connection on ER-view should probably be:

`tables = dbMetaData.getTables (null, null, "%", new String[] {"TABLE"});`

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
Fixed in 21.0.1
Will be available [here](https://dbeaver.io/) at 2021-03-22

**Comment by uslss** [comment]
verified
