### ISSUE TITLE
wrong table boundaries

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#11494]
Dbeaver 7.3.5
Postgresql 12

There are several columns with timestamp type one after another. Value of next column moved to previous column.

![изображение](https://user-images.githubusercontent.com/61137576/109139987-f3cf5280-777d-11eb-9903-8a4acf69cfaf.png)

![изображение](https://user-images.githubusercontent.com/61137576/109140039-03e73200-777e-11eb-9867-33490ba32ea3.png)

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it.
![dbeaver_8KSjAHijQR](https://user-images.githubusercontent.com/51405061/109419802-490a9e80-79e0-11eb-8461-80d8d86483fd.png)

- What OS do you use?
- Is it standalone DBeaver version?
- Please send DDL of your table.

**Comment by detkliff** [comment]
WINDOWS 10 64bit

standalone? - what is it?  Dbeaver 7.3.5 community

CREATE TABLE m_g.t_template (
	n_id int4 NOT NULL,
	s_name varchar(1000) NOT NULL
	d_active_from timestamptz NOT NULL,
	d_active_to timestamptz NULL,
	d_create timestamptz NULL
);

**Comment by uslss** [comment]
@detkliff is it reproducible for you for timestamp (not timestamptz) column?

**Comment by detkliff** [comment]
> 
> 
> @detkliff is it reproducible for you for timestamp (not timestamptz) column?

yes it is. today  version Dbeaver 21.0.0
![изображение](https://user-images.githubusercontent.com/61137576/110785119-6109da00-828c-11eb-8b52-47d2224e3aaa.png)

![изображение](https://user-images.githubusercontent.com/61137576/110785151-6bc46f00-828c-11eb-879d-2a6d69faa627.png)

**Comment by uslss** [comment]
Could you try to reset [wokspace state](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace) and [UI settings](https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings)?

**Comment by detkliff** [comment]
> 
> 
> Could you try to reset [wokspace state](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace) and [UI settings](https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings)?

yes, i could. No effect

**Comment by detkliff** [comment]
![изображение](https://user-images.githubusercontent.com/61137576/110938591-e86f5000-8355-11eb-9cee-15fadc084d22.png)
reset wokspace state and UI settings

**Comment by detkliff** [comment]
version 21.0.1

CREATE TABLE formula (
	id serial NOT NULL, 
	left_header_id int4 NULL,
	top_header_id int4 NULL, 
	formula json NOT NULL


RESULT:
![изображение](https://user-images.githubusercontent.com/61137576/113102888-096de700-9218-11eb-99d6-aabf2c8afb83.png)


![изображение](https://user-images.githubusercontent.com/61137576/113102959-1be82080-9218-11eb-93be-9e3e0e2c95a2.png)

**Comment by detkliff** [comment]
![изображение](https://user-images.githubusercontent.com/61137576/113103069-42a65700-9218-11eb-9b06-02b3b84eda1f.png)

**Comment by detkliff** [comment]
version 21.0.3 

timestamp column
![изображение](https://user-images.githubusercontent.com/61137576/115200673-e7c49900-a10d-11eb-8b1a-5fb0a749648b.png)

**Comment by uslss** [comment]
issue is reproducible for columns with foreign keys
![image](https://user-images.githubusercontent.com/31996417/117826662-03d4d980-b279-11eb-8f17-67e210ec3301.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
