### ISSUE TITLE
Remember last open tab (Data/Properties/ER Diagram) in object editor after application restart

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#11500]
**Is your feature request related to a problem? Please describe.**
For now, if we switch to Data/Properties/ER Diagram in the object editor, a new editor opens with the last chosen tab in the previous editor. But after application restart default tab resets.

**Describe the solution you'd like**
We should keep the same default tab for the object editor after the application restart.

**Comment by ShadelessFox** [comment]
Not reproducible anymore.
