### ISSUE TITLE
Icons do not respect colors in black theme

### ISSUE THREAD

**Issue by rajmondburgaj** [dbeaver/dbeaver#11506]
I enabled the black theme but seems there is a problem with the icons below.

![image](https://user-images.githubusercontent.com/7545874/109164670-fc725980-777a-11eb-89ee-115a20a97abf.png)

Would be nice if the icons respect the theme or to have a dedicated set of icons for black theme!

The same happens with scrollbars but not sure if this can be easily fixed 

![image](https://user-images.githubusercontent.com/7545874/109165241-9df9ab00-777b-11eb-91f4-621c211b4ca8.png)

Would be nice if they would have some dark colors.

**Comment by uslss** [comment]
thanks for the report.
will be fixed in the scope of #11647
