### ISSUE TITLE
[Bug] Projects/Project View - Folder name does not support UTF Characters.

### ISSUE THREAD

**Issue by martinandersen3d** [dbeaver/dbeaver#11509]
#### System information: 
- Operating system (distribution) and version: ubuntu/kubuntu 20.20
- DBeaver version: 7.3.5

#### Describe the problem you're observing:

If I use international letters like à, é, æ, ø, å, ß, in the folder filename, then it will NOT show up in Project/Projects view

Example:

![image](https://user-images.githubusercontent.com/19984581/109183286-10738680-778e-11eb-8168-882aae6d7218.png)

#### Steps to reproduce, if exist:
Create folders in your OS, then refresh in Project/Projects view to see changes. Here is some test names:
à la carte
gemütlich
heißen
Søren

**Expected behavior:**
Support for full utf-16

**Comment by martinandersen3d** [comment]
~~workaround (linux) - use folder symlink~~

~~ln -s "/réäl/path" "/linked/path"~~

~~The symlink will show up, as long as it only is az-0-9 chars~~

edit: the symlink folder will show up, but files in it will not open.

**Comment by uslss** [comment]
already implemented (21.3.2 - cannot reproduce)
