### ISSUE TITLE
 Broken autocompletion in grouping panel

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#11508]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.3.5
- Additional extensions: n/a

#### Connection specification:
- Database name and version: Oracle 11
- Driver name: ojdbc19
- Do you use tunnels or proxies (SSH, SOCKS, etc)? n/a

#### Describe the problem you're observing:
Short version: identical to https://github.com/dbeaver/dbeaver/issues/10281, only for grouping panel instead of filter bar
See gif (my DATA_ING field gets autocompleted to **DA**DATA_ING)

![autocomplete_group](https://user-images.githubusercontent.com/2157006/109175418-0f3e5b80-7786-11eb-9d8f-3e345d639924.gif)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.1.5

**Comment by Matvey16** [comment]
Verified
