### ISSUE TITLE
Function cannot be deleted via UI and its DDL is incomplete

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11515]
Win10
DBeaver 21.0
Vertica

1. Create a function e.g. CREATE FUNCTION myzeroifnull(x INT) RETURN INT AS BEGIN RETURN (CASE WHEN (x IS NOT NULL) THEN x ELSE 0 END); END;
2. Go to Source tab of the created function and see the statement.

**Expected**: the new function can be created using the statement
**Actual result**: thestatement contains only a part of the statement RETURN CASE WHEN (x IS NOT NULL) THEN x ELSE 0 END

3. Select the function and delete it.

**Expected**: the function is deleted
**Actual result**: the function cannot be deleted and error appears: SQL Error [4856] [42601]: [Vertica]VJDBC ERROR: Syntax error at or near "EOL"

**Note**: incorrect DDL is used to delete drop FUNCTION myzeroifnull; instead of drop FUNCTION myzeroifnull(x INT);

**Comment by LonwoLonwo** [comment]
drop statement fixed in scope with https://github.com/dbeaver/dbeaver/issues/11028 in CE version

**Comment by kseniiaguzeeva** [comment]
**EE version**:
Please add semicolon after return clause in function DDL.
**Now**: 
```
CREATE OR REPLACE FUNCTION dbeaver_schema.ff() RETURN varchar(20)
AS BEGIN
	RETURN ((('Hello, ' || "current_user"()) || '!'))::varchar(20)
END;
```
**Expected:**
```
CREATE OR REPLACE FUNCTION dbeaver_schema.ff() RETURN varchar(20)
AS BEGIN
	RETURN ((('Hello, ' || "current_user"()) || '!'))::varchar(20);
END;
```

**Comment by LonwoLonwo** [comment]
Delimiter added

**Comment by kseniiaguzeeva** [comment]
verified
