### ISSUE TITLE
strange chars (little cross) in result columns, SyBase jConnect driver

### ISSUE THREAD

**Issue by Henry-Jones** [dbeaver/dbeaver#11518]
Hello,

I use DBeaver for some different database drivers, but this only happens on a SQL Anywhere 12 server:

all fields which are part of the primary key and are of type nchar, are filled after their actual content with litte crosses "†" up to the maximum size.

It's mainly a cosmetic problem, but every now and then it happens that I update a row and the crosses get written for real back to the database, which causes all kind of problems.

If I open the database via ODBC (SQL Anywhere driver 17) the problem is not present.

I'd also try to open the Database via the jTDS driver but thats a problem on its own.

Has anyone a clue how I might get rid of them ?

#### System information (Client): 
- OS: Windows 10 20H2
- DBeaver: 7.3.4
- Extensions: none

#### Connection specification (Server):
- Windows Server 2012 R2 x64
- Database: SQL Anywhere 12
- jConnect (TM) for JDBC(TM)/16.0 SP03 PL02 (Build 27403)/P/EBF27518/JDK 1.6.0/jdbcmain/OPT/Mon Aug 28 18:41:14 PDT 2017
- Do you use tunnels or proxies (SSH, SOCKS, etc): no 

#### Describe the problem you're observing:
see above

#### Steps to reproduce, if exist:
open a table via doubleclick
execute any select which contains a column with the right properties

![image](https://user-images.githubusercontent.com/9108755/109295576-41f05e80-782f-11eb-8847-7ec593ffe449.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report, but I cannot reproduce it.
Could you send DDL example to reproduce? And what locale do you use (Editors>Data Editor>Data Formats)?

**Comment by Henry-Jones** [comment]
Hello, the following DDL will create the described situation:

CREATE TABLE tl130."DBA".NewTable (
	Column1 nchar(20) NOT NULL,
	CONSTRAINT NewTable_PK PRIMARY KEY (Column1)
) GO;

INSERT INTO tl130."DBA".NewTable (Column1) VALUES('Fritz');

if I use "generate SQL -> Insert" also the resulting text will contain the crosses.

![image](https://user-images.githubusercontent.com/9108755/109653663-919d9580-7b61-11eb-827d-e6f4b606f280.png)

**Comment by uslss** [comment]
Seems that it is server-side issue.
Types like nchar(20) are filled by default with spaces, probably it is changed to "†" symbol in the server config

**Comment by Henry-Jones** [comment]
Actually the documentation for version 11 and 12 describe nchar more or less as an alias to nvarchar. Both types are not filled with spaces, according to this docs.

[nchar data type in SAP documentation](http://dcx.sap.com/index.html#1201/en/dbreference/char-character-wsqltype.html)

If I extend the table from above with a second column as nvarchar(20) there a no fill chars in this second column. Also the first impression that it has something to do with the column being a (part of) primary key was wrong, that does not matter.

So maybe DBeaver treats the column as usually filled with blanks and somehow fills it up on its own.

If the field actually contains spaces after the initial content, they are correctly displayed, followed then by the little crosses.

The new DDL is as follows:

```
CREATE TABLE tl130."DBA".NewTable (
Column1 nchar(20) NOT NULL,
Column2 nchar(20) NOT NULL,
Column3 nvarchar(20) NOT NULL,
CONSTRAINT NewTable_PK PRIMARY KEY (Column1)
) GO;

INSERT INTO tl130."DBA".NewTable (Column1, Column2, Column3) VALUES('Fritz','Holler','hello');
INSERT INTO tl130."DBA".NewTable (Column1, Column2, Column3) VALUES('Frotz      ','Holler   ','hello');
```

with this result:

![image](https://user-images.githubusercontent.com/9108755/110850471-1ac67200-82b0-11eb-8e91-37a5560bbfcc.png)

**Comment by Henry-Jones** [comment]
> And what locale do you use (Editors>Data Editor>Data Formats)?

There is no "Data Editor" in the german version below "Editoren", only "SQL Editor" and "Text Editor". At least if you mean in the settings window. But even then, in neither is an option "local" (I guess it would be "Sprache" in German) to choose from.

**Comment by Henry-Jones** [comment]
Some more background:

- contrary to the documentation, the database is sending UTF8 spaces for the empty chars in the select. This is a log of the network traffic from the DDL yesterday.

![Screenshot 2021-03-12 082425](https://user-images.githubusercontent.com/9108755/110990772-12d00600-8374-11eb-8edd-abd95dc1d901.png)

- the UTF16 code 0x2020 indeed represents a small cross:

[UTF16 Chart of the 0x2xxx range](https://www.unicode.org/charts/PDF/U2000.pdf)

So the nchar is filled up with UTF8 spaces instead of UTF16 spaces, but real spaces are sent correct.

Is there something do be done about it ?

**Comment by uslss** [comment]
Seems it is driver-specific issue.
Could you try to set Charset as UTF-16 or USC2 in driver properties?
![image](https://user-images.githubusercontent.com/31996417/111489003-d1ac6d00-874a-11eb-8e6c-1a774fb6a8ae.png)

**Comment by Henry-Jones** [comment]
All three variants (incl. "UTF16") are replied with: "JZ0I5: Unbekannte CHARSET-Eigenschaft angegeben: "

![image](https://user-images.githubusercontent.com/9108755/111623812-2d2e3780-87eb-11eb-92d0-456ed4c79891.png)

**Comment by kseniiaguzeeva** [comment]
Looks like a driver issue. Please try to upgrade on another one from SAP source.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen an issue.
