### ISSUE TITLE
View cannot be created via UI

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11514]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.0

#### Connection specification:
- Database name and version Vertica

Press Create new view

Expected: the window to create new view appears
Actual result: error appears: Can't find node corresponding to new object
[default (1).log](https://github.com/dbeaver/dbeaver/files/6048588/default.1.log)

**Comment by LonwoLonwo** [comment]
Fixed. Also extra line breaks was removed from DDL view.

**Comment by uslss** [comment]
verified
