### ISSUE TITLE
issue while using aggregate functions...like max, distinct etc; query doesn't work...Tried in Version : 7.3.5; 7.3.4

### ISSUE THREAD

**Issue by sagarwal0303** [dbeaver/dbeaver#11512]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by ShadelessFox** [comment]
Hello @sagarwal0303,

Please update your issue with updated form - we can't guess details like what database are you using and etc.

**Comment by kseniiaguzeeva** [comment]
Please tell:
- your database, 
- DBeaver version,
- how do you apply the functions (via SQL Editor, Panel?..)

**Comment by sagarwal0303** [comment]
Hi,
Database: hive
Version:7.3.4
Used sql Eury in the dbeaver editor.
Please inform if you need any more information.

Thanks,
Shruti

**Comment by ShadelessFox** [comment]
Can you provide the query you've used and the error itself? Also [the log files](https://github.com/dbeaver/dbeaver/wiki/Log-files) would be useful.

**Comment by uslss** [comment]
There is no update on an issue for a long time.
If it is still actual for you - feel free to reopen an issue.
