### ISSUE TITLE
Create Projection and Sequence via UI

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11516]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.0 EA

#### Connection specification:
- Database name and version Vertica

Users should have possibility to create/drop Projection and Sequence via UI

**Comment by LonwoLonwo** [comment]
Ability to create, rename, delete and add comment to sequence added. Also sequence now have new parameters: cycle, cache and identity table link. These options can be changed via UI. (CE version)
 We added ability to drop and rename projection via UI only in [EE version](https://dbeaver.com/).

**Comment by LonwoLonwo** [comment]
Create sequence dialog added. DDL (Source) tab added for sequence. (CE version)

**Comment by kseniiaguzeeva** [comment]
Verified. Separate ticket with sequence enhancement will be created.
