### ISSUE TITLE
Created unique key is not visible in table properties

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11521]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0 EA

#### Connection specification:
- Database name and version Vertica

#### Steps to reproduce, if exist:
Open a table properties and create unique key

Expected: the key appears and remains in unique key list
Actual result: the key is not visible in unique keys tab, but exists in the table DDL

**Comment by LonwoLonwo** [comment]
https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/AdministratorsGuide/Constraints/ConstraintTypes/CheckConstraints.htm check constraints

https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/AdministratorsGuide/Constraints/ConstraintTypes/UniqueConstraints.htm unique constraints

**Comment by LonwoLonwo** [comment]
Implemented. You can view primary, unique and check constraints now. 
Also ability to create check constraint added. 
And ability to change disable/enable constraint status via UI.
And ability to view and create constraint comment.

**Comment by uslss** [comment]
check constraint creation isn't possible
![image](https://user-images.githubusercontent.com/31996417/115680944-b5f54180-a35c-11eb-8800-ac2c500fb8aa.png)

**Comment by LonwoLonwo** [comment]
Check constraint name added in create check constraint statement.

**Comment by uslss** [comment]
verified
