### ISSUE TITLE
Tables from different schemas are not colorized in ERD

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11520]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0

#### Steps to reproduce, if exist:
1. Open ERD
2. Dnd a table from another schema to the erd

Expected: the table is colorized by another color
Actual result: the table is not colorized

![dbeaver_Lnw1Ec4k0H](https://user-images.githubusercontent.com/51405061/109300772-04e49600-7848-11eb-9aaf-1662835f176e.png)

**Comment by flambchap** [comment]
Side effect of [this](https://github.com/dbeaver/dbeaver/issues/11309) fix.

**Comment by LonwoLonwo** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
