### ISSUE TITLE
Advantage Database Server via ODBC

### ISSUE THREAD

**Issue by lmaher007** [dbeaver/dbeaver#11525]
Not a feature request, but more of a question since I didn't find anywhere to ask simple quesitons.

I'm trying to use DBeaver on an ODBC connection to an Advantage Database Server (versions 8 or 9).

Simple question... Can it be done?

Thank you
Lynne

**Comment by uslss** [comment]
Hi @lmaher007 ,
did you try to use ODBC driver?
![image](https://user-images.githubusercontent.com/31996417/110532963-8aacef00-812e-11eb-98c1-2ea520f4ffa3.png)

**Comment by lmaher007** [comment]
Yes I did, but because our database is 32 bits, I had to install an older version of DBeaver in which I don't see functions and can't select tables on the left but I see stored procedures, but it seems to open the ODBC!!!

Oh and I cannot run a simple select on an existing table. One I know works. 

I guess DBeaver is a no go for me... sorry

**Comment by uslss** [comment]
Unfortunately, dbeaver supports x64 odbc driver only
