### ISSUE TITLE
Custom view doesn't show unique and foreign keys

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11522]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0 EA

#### Connection specification:
- Database name and version Vertica

#### Steps to reproduce, if exist:
Set connection view>HIde folders or show only schemas and tables

Expected: Unique keys and foreifn keys remain visible in table properties
Actual result: Columns and DDL tab is visible only, like in Simple view.

**Comment by flambchap** [comment]
I cannot reproduce it for the `Hide folders` option. As for the `Show only schemas and tables`, it is expected behavior.
