### ISSUE TITLE
SSH Tunnel--when selecting key file browser cannot browse to ~/.ssh

### ISSUE THREAD

**Issue by daveselinger** [dbeaver/dbeaver#1152]
The file browser cannot browse to ~/.ssh at all. All ".xxx" directories are hidden. To work, the path to the key must be entered manually.

Suggested easy fix is to start out in that directory...

Using LinuxMint 18.1, and assuming similar issues in ubuntu 16.04 -- if not, my apologies and ticket can be ignored.

**Comment by uslss** [comment]
cannot reproduce in issue.
if it is still actual for you - feel free to reopen the ticket

**Comment by averell-l3l** [comment]
I'm getting the same issue in MacOS.
DBeaver 23.3.2.202401072024
MacOS Sonoma 14.1.1

My key file is in ~/.ssh.
