### ISSUE TITLE
Edit columns via UI

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11523]
Can we support change column names via object editor? 

![dbeaver_DcC3W2Z8Dd](https://user-images.githubusercontent.com/51405061/109307237-5d6c6100-7851-11eb-8b67-8d71223bee48.png)

**Comment by LonwoLonwo** [comment]
+ add ability to change table description

**Comment by LonwoLonwo** [comment]
Implemented.

**Comment by uslss** [comment]
verified
