### ISSUE TITLE
MS SQL - when authenticationScheme is ntlm, DBeaver does not pass the required username and password properties to the driver

### ISSUE THREAD

**Issue by nmeachen** [dbeaver/dbeaver#11531]
#### System information: 
- Windows 10 20H2
- DBeaver 7.3.5

#### Connection specification:
- MS SQL Server
- MS SQL 8.2.0 JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No
- Connection string that works in IntelliJ and SQL Workbench/J:
- jdbc:sqlserver://{host}\{instanceName}:{port};encrypt=true;authenticationScheme=NTLM;domain=domain.com;trustServerCertificate=true;integratedSecurity=true;database={database}

#### Problem observed:
The following error is produced by the JDBC driver when the NTLM authentication scheme is selected

> "User" (or "UserName") and "Password" connection properties must be specified for NTLM authentication.

The Microsoft documentation ([https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-2016](url)) states the following

> When using **authenticationScheme=NTLM**, you must specify both the Windows domain to authenticate in using NTLM in **domain** or **domainName** property, and the Windows credentials in **user** or **userName** and **password** properties. Otherwise, an error occurs (connection properties must be specified).

The DBeaver plugin code for MS SQL bases the decision on whether to pass the username and password to the driver on the result of the function org.jkiss.dbeaver.ext.mssql.SQLServerUtils.isWindowsAuth. That function does not consider the setting in authenticationScheme and its impact on the requirement for username and password.

**Comment by kseniiaguzeeva** [comment]
How do you set NTLM:
on the main page of connection settings 
![dbeaver_dMbkJgY6p6](https://user-images.githubusercontent.com/51405061/109416512-c24dc580-79cf-11eb-9d9d-e218b4b06424.png)

or in Driver properties?
![dbeaver_vEXMGInGep](https://user-images.githubusercontent.com/51405061/109416516-c5e14c80-79cf-11eb-886e-2994f744cfbf.png)

If you use Driver properties, please try to set NTLM on the main page

**Comment by nmeachen** [comment]
It does not work either of your listed ways, the only way I get it to connect successfully using defined credentials and NTLM is to add user properties for user & password. And if you are not running a SQL Browser service, the only way to use the default port 1433 is to add a User property for port also.


<img width="431" alt="user-properties" src="https://user-images.githubusercontent.com/68712447/109427696-8f9cd080-79c1-11eb-8075-02ffe14a82a2.png">

**Comment by commentatorboy** [comment]
I can still confirm that this issue still exists and what [nmeachen](https://github.com/nmeachen) mentioned worked for me.

**Comment by negora** [comment]
I've a connection to a MS SQL server that uses NTLM authentication. In DBeaver 22.0.2 it works fine. However, something has changed in version 22.0.4, because it has stopped working. The displayed message is the one mentioned by @nmeachen in his/her original message.

**Comment by LxFx** [comment]
I can confirm negora's story. Worked in the previous release, but broken again in 22.0.4. Able to make it work again using the User Properties solution higher up.

**Comment by samaguire** [comment]
Yip, confirming this as well. I'm using the above user property workaround as well.

**Comment by KurtMar** [comment]
Can confirm the issue and that downgrading to 22.0.3 works https://dbeaver.io/files/22.0.3/

**Comment by E1izabeth** [comment]
Does it still reproducible on the latest DBeaver version?

**Comment by negora** [comment]
@E1izabeth I've tested DBeaver Community 23.0.5 against the following MS SQL servers:

* Microsoft SQL Server 2014 - 12.0.2000.8 (X64)
* Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64) 

And both have worked fine. Before testing, I've removed the user properties `user` and `password` that I had set in the past.

**Comment by E1izabeth** [comment]
Thank you for update!
