### ISSUE TITLE
Dump database feature potentially dangerous: easy to overwrite files without warning

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#11532]
Today I've become a victim of the dump database feature in DBeaver 7.3.5, which makes it too easy to overwrite a file without warning and as a consequence lose data. This is how the dump dialogue window looks for MySQL:

![dbeaver-dump](https://user-images.githubusercontent.com/11840364/109351671-ed260580-7879-11eb-80ab-34cfb2290488.png)

The problem is that pressing the Start button will invoke the dump with the last remembered path and filename and the dump process will overwrite the file if it exists without warning. Today, I opened the dump window by mistake (wanting to do Optimize Table) and I pressed Start without noticing this was not the tool I wanted to use and in a second a file with a dump I did a while ago got overwritten and I lost data in it that I needed.

Something would be needed to prevent the user from overwriting files so easily, I have two solutions in mind:

1. Implement a check before starting a dump if the target file exists and show warning.

2. Or remove the Start button (or make it disabled) in the window in the first step of the process and leave only the Next button active. This way at least the user will first see the next window with the dump settings. Personally, I would never want to press Start immediately, I always need to first see all the dump settings - they are very important to set right and it's impossible to remember what they were after a short while. I'd prefer this solution.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. As a wrokaround while you can use -${timestamp} in dump file name pattern. The file name will have current time in the name, and your situation can happen only if you make the dump at the same minute again.

**Comment by flambchap** [comment]
Implemented using the first approach. Now we show the prompt which asks for confirmation to delete the file. Despite the fact that `pg_dump` throws an error in this type of situations, I added the same prompt for PostgreSQL as well.

**Comment by lemon-juice** [comment]
Sounds good, thanks!

**Comment by Matvey16** [comment]
Verified
