### ISSUE TITLE
DevStyle selected menu items colors

### ISSUE THREAD

**Issue by qupear** [dbeaver/dbeaver#11535]
#### System information: 
- Operating system Windows 10 64bit 20H2 build 19042.804
- DBeaver version 7.3.5
- Additional extensions Office support and DevStyle (include darkest dark theme)
#### Connection specification:
It does not depend on type of connection.
#### Describe the problem you're observing:
In DevStyle (Darkest Dark theme) there is an issue when currently selected menu items are displayed with dark background and dark foreground so that you almost cannot read selected menu items. Two examples can be seen on attached screenshot.
#### Steps to reproduce, if exist:
1) Install latest DevStyle Features.
2) Restart Dbeaver.
![dbeaver-dark-issue](https://user-images.githubusercontent.com/8069685/109387873-c5d04680-7914-11eb-9a37-e624dbca313f.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by uslss** [comment]
duplicates #10887
