### ISSUE TITLE
It takes a long time to show table size.

### ISSUE THREAD

**Issue by jyoisamu** [dbeaver/dbeaver#11543]
#### System information: 
- Operating system (distribution) and version
WIndows１０ HOME
- DBeaver version
21.0.0
- Additional extensions
no one
#### Connection specification:
- Database name and version
Mysql5.5.56
- Driver name

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
NO

#### Describe the problem you're observing:
It takes a long time to show  table  size.

#### Include any warning/errors/backtraces from the logs

Warning: NLS unused message: OpenWorkspaceAction_errorTitle in: org.eclipse.ui.internal.ide.messages
Warning: NLS unused message: OpenWorkspaceAction_errorMessage in: org.eclipse.ui.internal.ide.messages
Warning: NLS unused message: IDEWorkspacePreference_workspaceLocation in: org.eclipse.ui.internal.ide.messages
Warning: NLS unused message: IDEApplication_workspaceInUse_Cancel in: org.eclipse.ui.internal.ide.messages
Warning: NLS unused message: QuickAccess_EnterSearch in: org.eclipse.ui.internal.quickaccess.messages
Warning: NLS unused message: QuickAccess_SelectedString in: org.eclipse.ui.internal.quickaccess.messages
Warning: NLS unused message: FileDocumentProvider_getPersistedEncoding in: org.eclipse.ui.editors.text.TextEditorMessages
Warning: NLS unused message: model_connection_events_wevent_before_disconnect in: org.jkiss.dbeaver.model.messages.ModelResources

**Comment by jyoisamu** [comment]
This problem has arisen since the size of the table can be displayed.
And only appear in individual MYSQL databases.

**Comment by uslss** [comment]
You could disable statistic info in Connection context menu
![image](https://user-images.githubusercontent.com/31996417/111466345-39a38900-8734-11eb-9409-26e44dca649d.png)

**Comment by jyoisamu** [comment]
> You could disable statistic info in Connection context menu

I abled statistic info in Connection context menu,but It taked about three minutes  to show。

**Comment by uslss** [comment]
@jyoisamu what driver do you use?

**Comment by jyoisamu** [comment]
> @jyoisamu what driver do you use?

It is Mysql5.

**Comment by jyoisamu** [comment]
@uslss 
The server specs are not high. 
So does this mean that it takes a long time to execute this function?

**Comment by uslss** [comment]
Sorry for the late response.
We get statistic info using `SHOW TABLE STATUS FROM database_name` query. Could you execute it and check how much time will it take?

**Comment by jyoisamu** [comment]
189ｓ

**Comment by uslss** [comment]
seems it is server-side issue
