### ISSUE TITLE
[Oracle] via UI columns creating problems

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#11542]
DBeaver 7.3.5
Oracle 12

Steps:
- Open existing Oracle table or create new one
- Create column via UI. Choose data type from the drop-down list and do not change anything after
- Try to save result

This type of data type of Oracle Columns generate incorrect alter statement:
BFILE
CFILE
CONTENT POINTER
DECIMAL
INTERVALs
LONG
LONG RAW
OID
OCTET

![2021-02-25 23_24_11-DBeaver Enterprise 21 0 0 - NEWTABLE](https://user-images.githubusercontent.com/45152336/109436457-a7f80400-7a30-11eb-8dbb-5cdda9a2ea9d.png)

![2021-02-25 23_25_21-DBeaver Enterprise 21 0 0 - NEWTABLE](https://user-images.githubusercontent.com/45152336/109436460-b0503f00-7a30-11eb-9826-f5608430a518.png)

![2021-02-25 23_26_52-DBeaver Enterprise 21 0 0 - NEWTABLE](https://user-images.githubusercontent.com/45152336/109436467-b47c5c80-7a30-11eb-9e7d-d9e851daec60.png)

**Comment by LonwoLonwo** [comment]
https://docs.oracle.com/database/121/SUTIL/GUID-169DE9FB-36A5-4087-9857-7F03DCF8D3C6.htm INTERVAL case

**Comment by LonwoLonwo** [comment]
Now BFILE, CFILE, CONTENT POINTER, LONG, LONG RAW,OCTET - do not have parameters on creation by default.
OID - is special case, I did not change anything.

DECIMAL - scale+precision bounds check added.
INTERVALs - alter statement fixed.

![2021-04-22_13h49_37](https://user-images.githubusercontent.com/45152336/115931170-59e10900-a493-11eb-8a49-fb4350dde658.gif)

**Comment by uslss** [comment]
**CFILE:**
ALTER/Create
![image](https://user-images.githubusercontent.com/31996417/116063717-f7a02800-a68d-11eb-9cfd-e0a2cdfb3d02.png)
**CONTENT POINTER**
CREATE TABLE HR.NEWTABLE1 (
	COLUMN1 CONTENT POINTER
);
![image](https://user-images.githubusercontent.com/31996417/116063905-2e763e00-a68e-11eb-82c0-27f8bca3b99b.png)
ALTER
![image](https://user-images.githubusercontent.com/31996417/116063999-4483fe80-a68e-11eb-8fc9-5e8943413d8a.png)
**OCTET**
ALTER/CREATE
![image](https://user-images.githubusercontent.com/31996417/116064536-c8d68180-a68e-11eb-9f0c-7864d3ae715f.png)

**Comment by LonwoLonwo** [comment]
CFILE, CONTENT PROVIDER AND OCTET are predefined Oracle data types ("SELECT * FROM ALL_TYPES"), but I can't find any documentation about them. So let them go further.

**Comment by uslss** [comment]
verified
