### ISSUE TITLE
Don't consider underscore a word separator

### ISSUE THREAD

**Issue by jk3us** [dbeaver/dbeaver#1155]
Right now, keys like Ctrl-Right that act on words consider underscore a word separator, but I pretty much always would rather it not (navigating through column names that are entirely_too_long_and_take_forever_to_scroll_through is currently pretty painful).  Is there a way change what it considers a word separator?  Or could an option for this be added?

**Comment by serge-rider** [comment]
Agreed, this may be annoying if you get used to work in editors where next/prev word actions ignore underscore.
Unfortunately it is the default behavior of all Eclipse text controls. It is hardcoded in the very internal code (note: Windows behavior differs from other OSes).
But fortunately it is possible to override this behavior (as it was done in Eclipse Java IDE). In a pretty verbose way - but still possible.
I'll mark this as feature request with lower priority.

**Comment by r-richmond** [comment]
If possible please make this a config option as I'm a fan of the current behavior

**Comment by sdpurohit** [comment]
Similarly, can the behavior for the period character be changed to consider it a word separator? 

When I have a table alias + column name separated by a period (select tab_alias.column_name from my_table tab_alias) I almost always want ctrl-right/left to select up to the period and not though it.

**Comment by sdpurohit** [comment]
The underscore character behaves as a word separator on my Mac.  Was this already implemented or was the original issue reported on an OS that doesn't behave like this?

**Comment by serge-rider** [comment]
No, it wasn't yet implemented. 
I'll move this to 4.1 for now.

**Comment by masebu** [comment]
Hi,

I vote for this change of behavior too. We use underscore a lot.
Currently word navigation with keys is not consistent with double-click selection which does select the whole word.
I read from [bug 324316](https://bugs.eclipse.org/bugs/show_bug.cgi?id=324316) that the change could come from Eclipse itself someday though that does not seem likely.

Thanks

**Comment by tati-kru** [comment]
Depends on the Eclipse platform

**Comment by serge-rider** [comment]
Actually this behavior is Windows-specific. On Mac and Linux underscore isn't a word separator.
I'll see what I can do (maybe even make the patch for SWT).

**Comment by vkirkpat** [comment]
Nice. One guy adds to 5.2.2 milestone and 2 months later, I'm sure with the 5.2.2 release date coming soon, another guy, tati-kru, removes this. C'mon guys, make this configurable. Very, very annoying to have an underscore be represented as a stop in Ctl-L / Ctl-R in a DATABASE APP.

Really?

**Comment by abayer85** [comment]
+1 for requesting this feature

**Comment by mediaseo** [comment]
+1 for this feature

**Comment by peter15914** [comment]
+1 for fixing this bug.

**Comment by nlindner** [comment]
+1. Please fix this. Your competitors have allowed this to be configured -- for example, Sublime Text's word_separators option, which presumably originated with TextMate.

**Comment by legolas108** [comment]
Would also much appreciate this to be configurable. There are already so many highly refined configuration options, this should definitely be included. Thanks!

**Comment by qupear** [comment]
I think there must be a separate command for navigating over underscores. Because sometimes underscores are useful but most of the times it is better to treat **_some_thing_with_underscores_** as a whole word. For example CTRL+LEFT will work as it does for now but there will be an option to add shortcut ALT+LEFT that will ignore underscores in words. This is probably limited to an Eclipse functionality not Dbeaver but anyway some option is needed to disable underscores as a word.

**Comment by serge-rider** [comment]
Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=324316

**Comment by joduhwan** [comment]
Have this problem been solved in DBeaver..? 
or just fixed in Eclipse..? (I've checked that Eclipse has fixed this bug)

**Comment by serge-rider** [comment]
This problem wasn't fixed in Eclipse.
It is not easy to fix. Eclipse determines word boundaries in OS-specific maner (i.e. differently for MacOS, GTK and Win32). It is very hard to provide some universal way to configure this behavior.

We could change Windows behavior (it is implemented in Java code while MacOS and GTK implementations use native API) but I doubt that Eclipse maintainers will approve such a change.

Once we will find a solution we create a PR in Eclipse SWT repository. Then the fix will come with the next Eclipse release.

**Comment by serge-rider** [comment]
Well, we will do it similarly to Eclipse Java editor (by replacing standard cursor command handlers with custom ones).

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/232769957-551cd026-ca4e-4b73-8ea2-a4ba60157828.png)
This option is enabled by default.
It considers underscores and dollar chars as identifier parts.

**Comment by tomnahum** [comment]
Hi thank you. I cannot find this setting in my dbeaver. I have the latest
version 23.0.2

**Comment by serge-rider** [comment]
It will be included in 23.0.3 (see the milestone)

**Comment by nickolay** [comment]
Does this work for everyone else? I just tried dbeaver community 23.3.2.202401072024 on Windows, turned the **"Editors -> SQL Editor -> Code Editor -> Smart caret positioning in SQL identifiers"** setting OFF, but CTRL+Right, CTRL+Left, and CTRL+Backspace still stop on every underscore.

**Comment by ahhmedbilal** [comment]
I have 23.2.5 and it works fine for me.

**Comment by nickolay** [comment]
> turned the "Editors -> SQL Editor -> Code Editor -> Smart caret positioning in SQL identifiers" setting OFF

The "smart positioning" option must be ON to have the desired effect of not stopping on every underscore, silly me!
