### ISSUE TITLE
dbeaver errors out redshift 

### ISSUE THREAD

**Issue by sravikrishna3** [dbeaver/dbeaver#11554]
#### System information: 
- Macos Big sur
- 7.3.5 and 21.0
- Additional extensions

#### Connection specification:
- Redshift 
- redshift-jdbc42-2.0.0.2.
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

After connecting to Redshift when I try to expand a schema and view table list, I get some weird error "portal not found".
Happens in both 7.3.5 and 21.
Attached screenshots and debug log
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/6062351/dbeaver-debug.log)
<img width="1280" alt="Screen Shot 2021-03-01 at 9 21 07 AM" src="https://user-images.githubusercontent.com/44801660/109512314-f974b300-7a71-11eb-8278-ef912c75f0e1.png">
<img width="1280" alt="Screen Shot 2021-03-01 at 9 22 53 AM" src="https://user-images.githubusercontent.com/44801660/109512315-fa0d4980-7a71-11eb-8df0-40c5e296d58a.png">

**Comment by sravikrishna3** [comment]
Seems to be a jdbc issue.  When I change the jdbc driver to 1.2.45.1069, everything works fine

**Comment by kseniiaguzeeva** [comment]
Thank you for the report and for the details. I cannot reproduce it with my settings.

**Comment by uslss** [comment]
we doesn't support 2.x driver for now.
Default Redshift driver was downgraded to 1.2.45.1069 in the scope of #11264
