### ISSUE TITLE
Cannot properly select text in the query panel

### ISSUE THREAD

**Issue by rokopi-byte** [dbeaver/dbeaver#11563]
#### System information: 
- Operating system (distribution) and version: Ubuntu 16.04
- DBeaver version: 21.0.0

#### Describe the problem you're observing:

I cannot properly select text in the query panel. Every time I try to select something with mouse, like a single word or the entire query.. everything above, from the beginning of the panel is selected. I have been experiencing this problem for the last years, so it's not related to latest version (which I'm using now)..

![Kazam_screencast_00012](https://user-images.githubusercontent.com/23717373/109622861-dd8a1380-7b3c-11eb-8d7f-753ec04780c1.gif)

**Comment by uslss** [comment]
duplicates #11205 

anyway, thanks for the report

**Comment by rokopi-byte** [comment]
Yes, exactly.. sorry for the duplicate! I didn't see, thanks

**Comment by rokopi-byte** [comment]
Hello.. problem still persist for me with version 21.1.2.. is there any update ?
