### ISSUE TITLE
Dbeaver Windows Install Issue

### ISSUE THREAD

**Issue by AzizHassan6** [dbeaver/dbeaver#11560]
Hello,

Earlier today I tried to set up Dbeaver on my pc. I was able to download the application and install the recommended drivers but was running into issues when running queries. 

I checked the error I could see on screen and it seemed like a generic error because it gave me a query error but nothing was wrong with my syntax. I did some digging and looked at the logs and found there were errors related to not reading the schema lists, catalog lists and fetching the database types.

I looked at this with a couple colleagues who agreed that my initial connection information was valid. That was the host, port, database/schema and username. If it helps I can attach a error log.

Please let me know about this if you may have a solution.

Thanks,
Aziz

**Comment by uslss** [comment]
Hi @AzizHassan6 ,
could you provide what database you use, more clear steps to reproduce, and an error log?
thanks in advance

**Comment by AzizHassan6** [comment]
Hi @uslss ,
The database I'm using is hive. I tried just looking up a table in the SQL editor and received the attached error log. 
[dbeaver_error_log.log](https://github.com/dbeaver/dbeaver/files/6064561/dbeaver_error_log.log)

**Comment by AzizHassan6** [comment]
@uslss Just curious if you had any advice as to how I can resolve this issue. Thanks!

**Comment by kseniiaguzeeva** [comment]
Please press **Test connection** in Connection settings and send a screenshot of a result. The pop up shows additional details about the connection.
![Screenshot 2021-04-08 at 10 25 09](https://user-images.githubusercontent.com/51405061/113985438-d1d4ef80-9854-11eb-93f8-ded0a031a877.png)

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual for you - feel free to reopen it.
