### ISSUE TITLE
All numeric types switches to varbit in case of import from csv to new table

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#11561]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.0.0

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
1. Start import from csv to non-existing table and check column types mapping - all numeric types columns are varbit in target table
![image](https://user-images.githubusercontent.com/31996417/109547953-14c8d800-7add-11eb-9930-be3f80fe3dba.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by tonytheodore** [comment]
This also happens with MS Access as the source and data type is "double".
