### ISSUE TITLE
Global search in code completion does not work

### ISSUE THREAD

**Issue by Edijus** [dbeaver/dbeaver#11565]
#### System information: 
- Operating system (distribution) and version: Win10 x64
- DBeaver version: 21.0.0
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 12

#### Describe the problem you're observing:
I have checked "Use global search (in all schemas)", but code completion works only in current schema.

**Comment by LonwoLonwo** [comment]
Hello @Edijus 
Could you please provide query examples, where global search doesn't work?

**Comment by Edijus** [comment]
![code_completion](https://user-images.githubusercontent.com/7039127/109649796-10e09880-7b65-11eb-8e30-18c8c30444d9.png)
Image is better than thousand words.

**Comment by LonwoLonwo** [comment]
duplicate of https://github.com/dbeaver/dbeaver/issues/10955
Will be fixed in scope with https://github.com/dbeaver/dbeaver/issues/10955
