### ISSUE TITLE
After update to 21.0: Unsupported mechanism type PLAIN

### ISSUE THREAD

**Issue by kaelte** [dbeaver/dbeaver#11571]
```
Windows 10
dbeaver-ce-21.0.0-x86_64-setup.exe
jdbc:hive2://hiveprod.x.ch:10000/abc
<HOME>\.dbeaver-drivers\hive-jdbc-uber-2.6.5.0-292.jar
```

I just have updated Dbeaver from 7.1? to 21.0 using the installer above. My previously defined connections were preserved but the driver needed to be installed. I added manually the old file to Apache Hive Bibliothek because the download timed out.

Since I need to authenticate with Kerberos I start Dbeaver with a BAT-script using the following commands:
```
:kinit
"%kinit_path%\kinit.exe" -p -f -A %LowerUser%@%realm%

call "%dbeaver_path%\Dbeaver.exe"
```

When I want to connect to the hive/cloudera I get the following error message:
```
Could not open client transport with JDBC Uri: jdbc:hive2://hiveprod.x.ch:10000/abc: Peer indicated failure: Unsupported mechanism type PLAIN
  Peer indicated failure: Unsupported mechanism type PLAIN
  Peer indicated failure: Unsupported mechanism type PLAIN
```

With the old DBeaver version I could connect without a problem.

**Can anyone give a hint were the problem may lie? How do I change the mechanism type?**

**Comment by kseniiaguzeeva** [comment]
Now DBeaver installer goes with Java, and it can be a reason of your issue (if you have installed Java separately with custom settings). What you can try:
- delete DBeaver Java (JRE) or
- delete and install DBeaver without Java (Remove Java checkbox in the installer)

DBeaver will use your Java in this case.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it.
