### ISSUE TITLE
DBeaver 100% CPU usage and crash

### ISSUE THREAD

**Issue by Edijus** [dbeaver/dbeaver#11573]
I am trying to run simple query that returns 549069 rows (and 49 columns) in 19 seconds when running in pgAdmin 4 v5.
Running same query on DBeaver 21.0.0 results in 100% CPU usage and DBeaver crash.
Win10 x64, 16GB RAM, intel i7-7700, PostgerSQL 12
![not_responding](https://user-images.githubusercontent.com/7039127/109671075-6d9b7d80-7b7c-11eb-9198-91089d315408.JPG)

**Comment by uslss** [comment]
hi @Edijus ,
is there something in logs?

**Comment by uslss** [comment]
There is no update on an issue for a long time.
If it is still actual for you - feel free to reopen an issue with an additional info
