### ISSUE TITLE
Filtering in Select Data Source is broken

### ISSUE THREAD

**Issue by bemigo** [dbeaver/dbeaver#11588]
#### System information: 
- Operating system (distribution) and version: Editie	Windows 10 Pro (20H2;19042.804)
- DBeaver version: 21.0.0.202102281712
- Java version: 
- Additional extensions: Office-extension

#### Connection specification:
- Database: PostgreSQL 11

#### Describe the problem you're observing:
In the select data-source diagram (Ctrl + 9-) I can only filter on the first letters. Not on the complete name.
I can filter e.g. on A- and keep all connection starting with A-, and connection starting with B- and C- disappear.
But if I filter on A-AN then i still have all my connections starting with A- and not the connections with A-AN.

#### Steps to reproduce, if exist:
1. Open the Select Data Source window
2. Check if you have multiple entries starting with the same character
3. Type something in the filter stating 'Enter a part table name here'
4. Try to time the name of the first entry
5. See that you keep multiple entries

![afbeelding](https://user-images.githubusercontent.com/9949263/109836253-41e3ca80-7c44-11eb-859b-df0308c77bfd.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
