### ISSUE TITLE
dbeaver crashes when trying to open spatial data view

### ISSUE THREAD

**Issue by mtravis** [dbeaver/dbeaver#11598]
#### System information: 
- Ubuntu 20.04.2 LTS
- DBeaver version 21.0.0.202102281712

#### Connection specification:
- postgres 10.9 / postgis 2.4.4
- PostgreSQL JDBC Driver
- No tunnels or proxies used 

#### Describe the problem you're observing:
When I try and use the spatial data view of a table dbeaver crashes. 

#### Steps to reproduce, if exist:
Open postgres connection > View Table > click on spatial 

#### Include any warning/errors/backtraces from the logs
eclipse.buildId=unknown
java.version=11.0.9.1
java.vendor=AdoptOpenJDK
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_GB
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.eclipse.core.resources
Warning
Thu Mar 04 10:48:15 GMT 2021
The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

**Comment by uslss** [comment]
Hi @mtravis ,
can you try to reset workspace using Main menu: File - Reset Workspace state or according to [the article ](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)?

**Comment by mtravis** [comment]
Hi @uslss 

Tried resetting the workspace and then followed the steps in that article. Still the same problem unfortunately.

**Comment by dragonxtek** [comment]
I'm working with spatial data in Ubuntu 20.10 and dbeaver 21. Some times dbeaver freezes and it crashes after some queries (I have not yet been able to replicate it). I readed the dbeaver log in ~/.local/share/DBeaverData/workspace6/.metadata/dbeaver-debug.log, but not appear info about the crashing, only issues caused by SQL sentences. This is an extract of the last lines from the file:

> Caused by: org.postgresql.util.PSQLException: ERROR: function st_intersects(geometry, double precision) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 60
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:327)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	... 12 more
> Start DBeaver Data GIS - view [org.jkiss.dbeaver.data.gis.view 1.0.47.202102281712]
2021-03-12 18:25:34.541 - A grid has been found.

The same information appears in the Error Log section from dbeaver:
![Selection_231](https://user-images.githubusercontent.com/10552658/111002863-e660bd80-8364-11eb-8c1b-efbb8aa3954e.png)

**Comment by lucamanga** [comment]
Happens to me too. It crashes BADLY when I click to an geometry. Too much unstable...

**Comment by uslss** [comment]
Thanks for the report.
Could you try to change web browser in preference to another (non-default) and check if it helps?
![image](https://user-images.githubusercontent.com/31996417/111604687-9fe8e400-87e6-11eb-9f27-4d1e4cf50d3a.png)

**Comment by lucamanga** [comment]
On Ubuntu 20.04, Dbeaver snap version, going to Preferences -> UI -> Web Browser crashes the program.

**Comment by mtravis** [comment]
Same for me.

**Comment by DariaMarkaryan** [comment]
Reproduced, error log:
[hs_err_pid8958.log](https://github.com/dbeaver/dbeaver/files/6513906/hs_err_pid8958.log)

**Comment by flambchap** [comment]
It is a snap-specific problem.

**Comment by baristahell** [comment]
I'm really not sure it's a snap-specific issue, I have the same problem and i installed dbeaver with the .deb installer. 
A mere click on a cell with a . I had a computer way less powerful before that handled hundreds of geometry cells selected at the same time with a map service behind...

**Comment by uslss** [comment]
fixed
