### ISSUE TITLE
Cannot connect postersql

### ISSUE THREAD

**Issue by Sybil997** [dbeaver/dbeaver#11592]
<img width="1078" alt="截屏2021-03-04 下午1 58 52" src="https://user-images.githubusercontent.com/80020687/109909522-f8ea4f80-7cf1-11eb-9055-027365ea9a1b.png">

**Comment by dG94Cg** [comment]
can you provide with JDBC Driver version and JDBC URL? so we can repeat the issue.
please follow the issue format, like [one issue example](https://github.com/dbeaver/dbeaver/issues/11577)

**Comment by Sybil997** [comment]
Good evening,

Thanks for email, sorry for my wrong format.
Form the detail, it says 'Please report this exception', I thought that posted is 'report'.

Kind regards,
Sybil[cid:83440a62-f2a4-407f-acb7-0d9659a75cbf]
________________________________

**Comment by Sybil997** [comment]
Hey guys,

I'm a new one to use it, after installing, I am experiencing one connect issues when creating connection.
![Screen Shot 2021-03-04 at 10 42 02 pm](https://user-images.githubusercontent.com/80020687/109965569-da5c7680-7d3a-11eb-8b3f-922fb85aea6f.png)

After I press test connection it shown that
![Screen Shot 2021-03-04 at 10 42 48 pm](https://user-images.githubusercontent.com/80020687/109965632-f5c78180-7d3a-11eb-9966-25c78194a3d7.png)

**Comment by uslss** [comment]
What Postgresql version do you use?

**Comment by Sybil997** [comment]
PostgreSQL 13

**Comment by uslss** [comment]
@Sybil997 is there something in the [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by Sybil997** [comment]
![Uploading Screen Shot 2021-03-10 at 11.58.59 am.png…]()

**Comment by Sybil997** [comment]
<img width="762" alt="Screen Shot 2021-03-10 at 11 58 59 am" src="https://user-images.githubusercontent.com/80020687/110572688-a7383e00-81a5-11eb-81f1-ae25b753218a.png">

**Comment by uslss** [comment]
@Sybil997 please, provide an error stacktrace https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info
