### ISSUE TITLE
Unable to enter local client path

### ISSUE THREAD

**Issue by glmarsh** [dbeaver/dbeaver#11591]
I am using DBeaver-ce version 21.0.0.202102281712  with MySQL Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
When attempting to find the Native Client path I am unable to select /usr/share/dbeaver  which was the location used by the previous version of DBeaver-ce version 7.3.5.  When I try to select this location I get a permissions error which does not happen with the older version(7.3.5).   The owner and group of /usr/share/dbeaver is root:root.

**Comment by uslss** [comment]
Hi @glmarsh ,
cannot reproduce it. Could you tell me how do you install dbeaver? snap or deb package?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it.

**Comment by glmarsh** [comment]
Hi Dziyana;It appears the program is able to work if I move mysqldump to the default directory.  Regards,Gary MarshSent from my Galaxy
-------- Original message --------From: Dziyana ***@***.***> Date: 4/20/21  4:24 AM  (GMT-08:00) To: dbeaver/dbeaver ***@***.***> Cc: glmarsh ***@***.***>, Mention ***@***.***> Subject: Re: [dbeaver/dbeaver] Unable to enter local client path (#11591) 
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it.
