### ISSUE TITLE
Backup tool - back button work not correctly if you reselect tables

### ISSUE THREAD

**Issue by 452** [dbeaver/dbeaver#11596]
#### System information: 
- Ubuntu 20.04.2 LTS, GNOME 3.36.8, X11
- DBeaver IDE	21.0.0.202103021012
- Additional extensions: Spring Tool Suite 4 Version: 4.9.0.RELEASE Build Id: 202012132054

#### Connection specification:
- PostgreSQL 9.6
- PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Steps to reproduce, if exist:
Go to Tool -> Backup -> select two tables
go forward, click start
click back
reselect to other tables
go forward, click start
**Actual result:**
Always the same firstly selected tables are exported again
Back button work not correctly, because after I select other tables and click start, as result I have exported previously selected tables, not new...
**Expected result:**
Newly selected tables are exported

**Comment by uslss** [comment]
Hi @452 ,
cannot reproduce it against 21.0.1,
is it still actual for you?

**Comment by 452** [comment]
Yes, actual
![image](https://user-images.githubusercontent.com/1583753/112867839-0bbf2c80-90c4-11eb-8c9a-e080262e91e2.png)
![image](https://user-images.githubusercontent.com/1583753/112867894-1b3e7580-90c4-11eb-9a1e-add189c30a18.png)
![image](https://user-images.githubusercontent.com/1583753/112868027-445f0600-90c4-11eb-8146-420b6f932bea.png)
![image](https://user-images.githubusercontent.com/1583753/112868317-9738bd80-90c4-11eb-8813-365f2a4813e1.png)

**Comment by uslss** [comment]
still cannot reproduce an issue. probably you could provide a video with an issue and backup log?
thanks in advance

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
