### ISSUE TITLE
Connections are created in Custom view with no selected options

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11606]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21. 0 

#### Steps to reproduce, if exist:
1. Create a new connection
2. Check its view in DB Navigator

Expected: Advanced view is displayed by default, if another type has not been set
Actual result: custom view with no options is selected
![dbeaver_IqKUbMRBk0](https://user-images.githubusercontent.com/51405061/109988026-2cd86b80-7d18-11eb-96cf-09e92e07ce53.png)

**Comment by serge-rider** [comment]
Default navigator settings can be configured in preferences (page Connections).
It works as expected in my env.

**Comment by Matvey16** [comment]
Verified
