### ISSUE TITLE
Indexes are not showing on table and schema level with Splicemachine jdbc driver

### ISSUE THREAD

**Issue by lightsailpro** [dbeaver/dbeaver#11607]
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version: 7.3.5
- Additional extensions

#### Connection specification:
- Database name and version: Splicemachine 3.0
- Driver name: Splicemachine jdbc driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Connection is set up using the splicemachine jdbc driver. Other meta data display correctly. But Indexes are not showing on table and schema level with Splicemachine jdbc driver. From which system view does DBeaver retrieve index info on table or schema level? Which source file contains the info? Maybe I can create a index view to workaround the issue. Thanks

#### Steps to reproduce, if exist:
Click the Indexes folder on schema and table level. It is always empty.

#### Include any warning/errors/backtraces from the logs

No any error.

**Comment by uslss** [comment]
Hi @lightsailpro ,
could you provide dbeaver [debug-log](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info
