### ISSUE TITLE
Mac OS keybindings ignored (~/Library/KeyBindings)

### ISSUE THREAD

**Issue by thnk2wn** [dbeaver/dbeaver#11605]
#### System information: 
- Operating system (distribution) and version - `OS Mac OS X(x86_64) v10.16`
- DBeaver version: `21.0.0.202103021012`
- Additional extensions: `None`

#### Connection specification:
- Database name and version: `N/A here but PostgreSQL 12.5`
- Driver name: `N/A here but PostgreSQL JDBC Driver`
- Do you use tunnels or proxies (SSH, SOCKS, etc)? `NA here but no`

#### Describe the problem you're observing:
On Mac I've remapped the home and end keys to work like they do on Windows:
https://www.cobus.io/osx/2017/02/09/OSX_Home_End_Keys.html

That works in most all Mac OS apps but not DBeaver (I thought it did work in DBeaver before). I'd expect any OS level keybinding change to take effect with DBeaver just like any other.

#### Steps to reproduce, if exist:

On Mac, edit or create `~/Library/KeyBindings/DefaultKeyBinding.dict` with:

```
{
  "\UF729"  = moveToBeginningOfParagraph:; // home
  "\UF72B"  = moveToEndOfParagraph:; // end
  "$\UF729" = moveToBeginningOfParagraphAndModifySelection:; // shift-home
  "$\UF72B" = moveToEndOfParagraphAndModifySelection:; // shift-end
  "^\UF729" = moveToBeginningOfDocument:; // ctrl-home
  "^\UF72B" = moveToEndOfDocument:; // ctrl-end
  "^$\UF729" = moveToBeginningOfDocumentAndModifySelection:; // ctrl-shift-home
  "^$\UF72B" = moveToEndOfDocumentAndModifySelection:; // ctrl-shift-end
}
```

Restart if needed. Observe key binding changes in other Mac apps but not DBeaver.

#### Include any warning/errors/backtraces from the logs
N/A

**Comment by uslss** [comment]
Seems it isn't implemented yet. Marked as feature request.

**Comment by uslss** [comment]
duplicates #9414
