### ISSUE TITLE
The JDBC URL is not editable for Apache Hive and customized drivers

### ISSUE THREAD

**Issue by GaryLiuTelus** [dbeaver/dbeaver#11614]
#### System information: 
- Operating system (distribution) and version 
- **Windows 10 Enterprise 10.0.17763 build 17763**
- DBeaver version
- **21.0**
- Additional extensions

#### Connection specification:
- Database name and version
- **Apache Hive 3.0**
- Driver name
- **Apache Hive, and customized drivers**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
**No.**
#### Steps to reproduce, if exist:
Create a new Hive connection, the JDBC URL is directly copied from the driver setting (URL template), and is not editable. Have to modify URL template for any changes, and in most cases, it won't work. So have to delete the connection, change the URL template, and re-create a new connection to reflect the changes. Also, it means I cannot create connections to different Hive database with the same driver, as they have to share exactly the same URL. It is the same for any customized drivers.

**Comment by uslss** [comment]
Hi @GaryLiuTelus ,
could you try to create connections accordingly to [guide](https://github.com/dbeaver/dbeaver/wiki/Create-Connection)?

**Comment by GaryLiuTelus** [comment]
Hi Dziyana,

I can create a connection and connected to the database, but the issue here is the JDBC URL is not editable, and the content inside is copied directly from driver settings. So you cannot connect 2 databases with the same driver.

For example, I cannot connect to 2 Hive database (with different JDBC URLs) using the same driver, as the JDBC URL is locked.

***@***.***D71BE9.CEFD5DC0]

Gary

**Comment by GaryLiuTelus** [comment]
![image](https://user-images.githubusercontent.com/39339422/111653927-a8d5b780-87de-11eb-930e-fff34db47414.png)

**Comment by GaryLiuTelus** [comment]
Any comments?

**Comment by GaryLiuTelus** [comment]
@uslss 
Any comments? Can you please advise what any further information I need to provide?

**Comment by uslss** [comment]
@GaryLiuTelus sorry for the long response. Database and host could be changed in connection settings, in case of connection creation using New connection button. It is not needed to set the values (e.g. host) you need in driver properties.
![image](https://user-images.githubusercontent.com/31996417/118490516-b0560600-b726-11eb-91be-cfbc32ba7a6c.png)

**Comment by GaryLiuGTA** [comment]
@uslss Thanks for your reply! My URL string contains more information like

> jdbc:hive2://{host}:{port}/default;**_ssl=true;sslTrustStore=C:/users/trust_store_path/truststore.jks;trustStorePassword=xxxxxxx;transportMode=http;httpPath=myHttpPath_**

Where should I put these information?

**Comment by GaryLiuTelus** [comment]
Any comments , @uslss ?
In Squirrel SQL, a JDBC URL template can be provided in the driver settings, and then for each connection, the URL can be edited independently, while in DBeaver, the URL template is not editable in each connection. The only thing can be modified are credentials. But JDBC URL can contains more than credentials. As what I showed above, the URL connection to Apache Hadoop contains host, url, if use SSL for authentication, truststore file etc. Different connections should be able to share the same driver with different host/port/SSL authentication.  Another example is JDBC connection to SAS, different connections can have different libnames in the URL, but share the same driver. It is doable in Squirrel. But in DBeaver, I have to created different server for different connections, as the URL is not editable. But DBeaver is still my preference due its lots of advantages over Squirrel. So hope this can be fixed. 

Thanks!

**Comment by sixdimensionalarray** [comment]
I ran into the same issue.  There is one workaround for this that has a small side effect (not having UI assistance to construct the JDBC URL), but is easy enough for this use case.

Use a Driver setup that does not have a URL template, and then when you create a connection using that driver, you can type whatever you want into the URL on the "Connect to a database" UI.

Remove the URL Template from the driver setup like this (see how mine is blank):
![image](https://user-images.githubusercontent.com/3506127/121274785-1ba37b80-c880-11eb-91c0-177eeafc6e86.png)

Create a connection with any JDBC URL you want:
![image](https://user-images.githubusercontent.com/3506127/121274966-7a68f500-c880-11eb-88d3-6529fbe88cfe.png)

It would be nice to be able to use the "User" driver properties in the URL templates though, but "nice to have".

Hope this helps!

**Comment by GaryLiuGTA** [comment]
@sixdimensionalarray 
Thanks for your advice, and it really works. 

But still it is better to have a template in place, so no need to input many information repeatedly for each connection.  But anyway, this workaround solved my problem.

Thanks!

**Comment by uslss** [comment]
Additional properties could be provided at Driver properties tab at Connection Settings dialog
![image](https://user-images.githubusercontent.com/31996417/121364921-e0b54c80-c940-11eb-8708-b20cd04bf9b2.png)

**Comment by sixdimensionalarray** [comment]
@uslss, I tried adding user properties but they were not passed to the driver in the JDBC url.

The docs are a little sparse on how to use the user properties, do you have to add user properties to the URL template somehow?  Can you explain how they are meant to work, I didn't see anything in the docs?

Thank you much!

**Comment by GaryLiuGTA** [comment]
I tried adding those user properties, and it's the same as @sixdimensionalarray, and it did not go through and build connections. 
![image](https://user-images.githubusercontent.com/57276664/121370293-9dd88200-c90a-11eb-9641-e3f20a6ee56e.png)

Is that possible to have the template in place, and also allow user tot edit it for each individual connection? 

Thanks!

**Comment by uslss** [comment]
seems it was fixed in #13654
