### ISSUE TITLE
DBeaver not showing tables in Database Navigator

### ISSUE THREAD

**Issue by johnwespinosa** [dbeaver/dbeaver#11610]
Hello,

DBeaver is not displaying any tables nor views in the Database Navigator. This has happened many times and my workaround has been to remove the connection/driver completely and add it again. This has been happening on version 7.2.2, so I just upgraded to version 21.0 and still no tables are showing.

I'm on OS Window 10 Enterprise. Connecting to data source in DB2.

Is this a known issue or bug?

Regards,

John

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
Hi @johnwespinosa ,
cannot reproduce it. What db2 version and what db2 driver do you use?

**Comment by uslss** [comment]
There is no update on an issue for a long time.
If it is still actual for you - feel free to reopen an issue.
