### ISSUE TITLE
Help buttons not working

### ISSUE THREAD

**Issue by aisbergde** [dbeaver/dbeaver#11618]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version Version 21.0.0.202102281712
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

When pressing help button then nothing happens.
![image](https://user-images.githubusercontent.com/9020187/110082294-6f885b00-7d8d-11eb-8eee-465f31007945.png)

#### Steps to reproduce, if exist:

see screenshot

**Comment by uslss** [comment]
Thanks for the report

**Comment by Xyenia** [comment]
**Version 21.0.2.202104042040**

I can confirm that Help Buttons on the various dialog boxes are not working. I have found lots of instances, but I will not post screenshots as I assume, it is an overall issue that will be eventually tackled. Thanks DBeaver team.
