### ISSUE TITLE
No scrollbar in error message display

### ISSUE THREAD

**Issue by lukaseder** [dbeaver/dbeaver#11621]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows [Version 10.0.19042.804]
- DBeaver version: Version 7.3.5.202102151746

#### Connection specification:
- Database name and version: CockroachDB CCL v21.1.0-alpha.3 (x86_64-unknown-linux-gnu, built 2021/02/08 20:04:30, go1.15.6) (get it from here: https://hub.docker.com/r/cockroachdb/cockroach-unstable/tags?page=1&ordering=last_updated)
- Driver name: org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

I ran into an internal error of the database, and the error message doesn't display fully. There's no scrollbar to show the bottom of it. As a workaround, I can use the mouse to put the caret inside of the error message and use the arrow keys

#### Steps to reproduce, if exist:

Run this statement on the above alpha:

```sql
create type t as enum('a');
drop type t;
```

The `DROP TYPE` fails with a long error message. You can probably produce any other long error message in any other RDBMS, though, it should always be the same.

See the below screenshot which is lacking a scrollbar

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/734593/110089468-736cab00-7d96-11eb-8c3d-cc70062300db.png)

**Comment by uslss** [comment]
Issue's stacktrace should be available by clicking on details button, could you check it?

**Comment by lukaseder** [comment]
Hmm, I can't say what changed. I'm still on the same version 7.3.5.202102151746, but now the layout of the button is correct:

![image](https://user-images.githubusercontent.com/734593/111608481-8d1be280-87d9-11eb-9414-35b590cb8e85.png)

It looks as though under certain conditions, the UI layout breaks, so this isn't a problem of having the scrollbar at all, but of not having it under certain conditions.

I cannot reproduce it right now. I'll try to provide more info should it happen again.
