### ISSUE TITLE
AS keyword for aliases

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#11625]
When inserting table names using autocomplete, DBeaver automatically generates an alias:
```
SELECT * FROM users.tab_users tu 
```
As you can see it lacks of AS keyword. Is there any option I missed to enable that? Or it's missing feature?

With regards

**Comment by ShadelessFox** [comment]
We don't include the `AS` clause for table aliases because it is not required and thus can be omitted.
