### ISSUE TITLE
Add context menu entry to hint about existing "shift-Enter" feature to allow multiline edit in a separate window

### ISSUE THREAD

**Issue by aisbergde** [dbeaver/dbeaver#11628]
**Is your feature request related to a problem? Please describe.**

I am working with related tables like
- TableA
  - A_id
  - A_name
- TableB
  - A_id
  - B_multiline

FK from TableB.A_id -> TableA.A_id

And I want to edit the **multiline content** of TableB.B_multiline 

When I just open TableB then I can edit the multiline content of B_multiline in the "Value" section:  
![image](https://user-images.githubusercontent.com/9020187/110110088-9e62f900-7dae-11eb-962c-ce2c6abb0fbd.png)

But now I want to use the reference section in TableA to easy select elements in TableA and to edit the related entries in TableB (and TableC and maybe in other related tables). The "Reference" section works great for "normal" columns. But there is no second "value" window for the referenced TableB. I can only use inline-editing, but this works only "inline". I can't edit the **multiline content** as required.

![image](https://user-images.githubusercontent.com/9020187/110110642-6dcf8f00-7daf-11eb-9bff-a2e23d278276.png)

**Describe the solution you'd like**

I want to request any way to edit the multiline content in this situation. For example in the context menu of the cell there could be a point "edit cell in separate window" and a new floating editor window could open where multiline edit is possible.

**Describe alternatives you've considered**

Often I use Microsoft Access to connect via ODBC to Microsoft SQL Server, then I can define lookup tables for some columns (in this case a lookup from TableB.A_id -> TableA.A_id) and I can show a different content (instead of TableB.A_id I can show TableA.A_name). I can also create forms in Access.

But Access is not every time available that's why I tried different alternative Tools. dbeaver is for now the best I found when I want to work with referenced tables and **multiline content**. I can show the TableA.A_name in TableB and I can use it as a filter, I have the "value" section. But it would even better if I could do what I described:
- Navigate in TableA to use TableA as Filter
- show the related and filtered context from TableB or TableC in the Referenced-section
- allow multiline edit of content in TableB or TableC

Another alternative would be to program some web form frontend or some native application to allow this. But I think dbeaver has a lot of required features, so it is better to request some new features in dbeaver and to suggest the usage of dbeaver then to program a completely separate application

**Additional context**

**Comment by uslss** [comment]
Hi @aisbergde , you could use shift+enter after cell choosing - then the editor will open.

**Comment by aisbergde** [comment]
@uslss This works perfectly and this was what I was looking for!

But features are only good if you can find them. I want to change my feature request so that there is an entry for this functionality in the context menu.

**Comment by ShadelessFox** [comment]
Implemented:
![java_ANeZtKJ2om](https://user-images.githubusercontent.com/35821147/113865493-d21dae00-97b4-11eb-947c-3c3bd4b4f4d4.png)

**Comment by uslss** [comment]
verified
