### ISSUE TITLE
Warning Msg 

### ISSUE THREAD

**Issue by hiiiys** [dbeaver/dbeaver#11623]
I tried to run a sql script but encounter error.
It shows SQL warning: Truncated incorrect Integer value.
An exception stack trace is not available

my sql script is

“select * from table_name where score  = ‘100’”

the data type for score is varchar(7)

**Comment by uslss** [comment]
Hi @hiiiys ,
what database and dbeaver version do you use?

**Comment by hiiiys** [comment]
Thanks for your reply. I’m using 6.2.1
Loading MariaDB

**Comment by uslss** [comment]
@hiiiys could you check issue is reproducible for you against [21.0.0](https://dbeaver.io/download/)?

**Comment by uslss** [comment]
There is no update on an issue for a long time.
If it is still actual for you - feel free to reopen an issue.
