### ISSUE TITLE
devide functions, procedure, trigger functions

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#11631]
it is very convenient to have separation when working with functions
such as in pgAdmin or in Oracle PLSQLDeveloper 

![изображение](https://user-images.githubusercontent.com/61137576/110117157-4c37cd00-7dda-11eb-9d21-1ea6212eaaf3.png)

all functions devided for functions, procedure, trigger functions.

In DBeaver 21 version
![изображение](https://user-images.githubusercontent.com/61137576/110117249-6c678c00-7dda-11eb-962e-b1590bdf0c75.png)

**Comment by LonwoLonwo** [comment]
Thanks for suggestion! 
We will try to do it in this ticket: https://github.com/dbeaver/dbeaver/issues/11408
