### ISSUE TITLE
BigQuery Geography type does not display the map

### ISSUE THREAD

**Issue by chapmanjacobd** [dbeaver/dbeaver#11635]
#### System information: 
- Operating system (distribution) Windows 10
- DBeaver version 7.3.0 EE
- Additional extensions

#### Describe the problem you're observing:

DBeaver only shows the text value of the cell

#### Steps to reproduce, if exist:

1 Add a geography column

2 Insert 

```
POLYGON((-1.865288805 48.309357018, -1.851787127 48.285452339, -1.843208216 48.284830668, -1.830982145 48.288464945, -1.825637169 48.292361941, -1.830838414 48.302210692, -1.824119016 48.315235853, -1.82706549 48.318127227, -1.841932608 48.321329053, -1.86322268 48.312392111, -1.865288805 48.309357018))
```

3 Select

**Comment by LonwoLonwo** [comment]
Hello @chapmanjacobd 
This is not a bug. Geographical types of columns in different bases contain specific data that we need to be able to correctly read.
Like we read data of the geographic columns in the PostGIS.
But not for BigQuery. So this is a feature request. And we will try to do it in next releases.

However, now in DBeaver we can [work with geographic data](https://github.com/dbeaver/dbeaver/wiki/Working-with-Spatial-GIS-data#viewing-string-or-binary-data-from-any-database-on-a-map) located in binary or string columns.
You can try to copy your data into similar columns to see the data on the map.

**Comment by ShadelessFox** [comment]
Implemented as the Enterprise Edition extension:
![image](https://user-images.githubusercontent.com/35821147/114159113-1e402e00-992e-11eb-9545-17b48ac5f96b.png)

**Comment by uslss** [comment]
verified
