### ISSUE TITLE
import / export BUG

### ISSUE THREAD

**Issue by lxkplus** [dbeaver/dbeaver#11636]
Hello, I have some BUGs that I want to submit.

When using the import and export function, the export encoding defaults to ANSI format.However, when importing, there will be garbled code.

If I open a file in ANSI format, it works fine.

When I open a file in UTF-8 format, it works fine.

But: when I imported SQL, he scrambled.

I changed the text to UTF-8 (I changed the default encoding format), and it worked.

I tried to locate BUG:

The encoding and decoding of the system are two different function modules with different key positions.When one party's code is modified, the other will not follow the update, so there will be some problems with import and export functionality.

Import and export modules and open files are similar but different modules.Developers add judgment rules to common modules, but ignore this less common feature.

Much of the uncommon BUG functionality is normal, isn't it?XD

There are no more BUGs.

Thank you!

**Comment by lxkplus** [comment]
sorry,i did not konw i can provide photos before.
![Snipaste_2021-03-10_15-22-52](https://user-images.githubusercontent.com/78188981/110591861-888d7380-81b4-11eb-8f3b-b84eaad29670.png)
and garbled code：
![Snipaste_2021-03-10_15-26-22](https://user-images.githubusercontent.com/78188981/110592287-0e112380-81b5-11eb-8b77-6fc840511c62.png)

**Comment by uslss** [comment]
Hi @lxkplus ,
could you provide more clear steps to reproduce? Screenshots or video can be very helpful
Thanks in advance

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info
