### ISSUE TITLE
Columns are not updating in metadata view pane

### ISSUE THREAD

**Issue by makarevs** [dbeaver/dbeaver#11639]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows 10 Enterprise 10.0.17763 Build 17763
- DBeaver version: 21.0.0.202102281712
- Java version: 1.8.0_261; Java(TM) SE Runtime Environment (build 1.8.0_261-b12); Java HotSpot(TM) Client VM (build 25.261-b12, mixed mode)
- Additional extensions: None for DBeaver

#### Connection specification:
- Database name and version: PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
- Driver name: PostgreSQL Binaries; psql (PostgreSQL) 12.2
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
The listing of the fields is not updated after the new query runs in the same window

#### Steps to reproduce, if exist:
Just try any two queries resulting in different columns
Step 1: Enter query: "select 1::bigint as one", and execute
Step 2: Observe column "one" showing in metadata pane or results
Step 3: Add/amend the query: "select 1::bigint as one, 2::numeric as two"
Step 4: Observe again only column "one" showing in metadata pane or results, where should be two columns now
NOTE: this happens regardless of how you execute -- complete window <Alt+X>, or just selected code by <Ctrl+Enter>
Step 5: If you switch to another pane in the group, like "Value" and then back to "Metadata" -- them column list IS refreshed. But the hope is that, like results themselves, metadata would update automatically.

#### Include any warning/errors/backtraces from the logs

Thanks for your great work at DBeaver!

**Comment by kseniiaguzeeva** [comment]
Please write any details

**Comment by makarevs** [comment]
Apologies, posting first time here, prematurely created the item, thinking I would search for title... Now posted details in edit. Unfortunately do not know if can edit the title -- would make it more informative, like "Columns are not updating in metadata view pane"

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce. Do you refresh the table after making changes? Please write steps to reproduce, DBeaver version, your database.

**Comment by makarevs** [comment]
Wrote steps. 

In them there is no attempt to refresh the Metadata pane. I expect the window with metadata to update after execution of new query just as results themselves are updated. I believe this is a reasonable expectation.

Thanks for such a quick reaction!
Great tool overall - keep enjoying it!

**Comment by makarevs** [comment]
Added, to main issue post, one action leading to update of columns (switch to "Value" and back), which is akin to refresh. I am using it currently, but this is a slow-down, and, occasionally, if I do not do it immediately -- throws me off when I try to look at which columns I have...

So, it is not a show-stopper, of course, but would be nice to make it a consistent and more efficient experience we are growing to expect from this great team.

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
