### ISSUE TITLE
it is not possible to create virtual FK between views

### ISSUE THREAD

**Issue by aisbergde** [dbeaver/dbeaver#11633]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 21.0.0.202102281712
- Additional extensions

#### Connection specification:
- Database name and version SQL Server 2019
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

I try to create virtual FK between views, but dbeaver doesn't accept them

#### Steps to reproduce, if exist:

1. define virtual PK on some views
2. try to define virtual FK between views

Here is an example:
Index_gross is a view. I can define a virtual PK and some virtual FK between this view and some tables

```json
":Index_gross": {
  "constraints": {
    "pk_Index_gross": {
      "type": "vpk",
      "attributes": [
        "index_guid"
      ]
    }
  },
  "foreign-keys": [
    {
      "entity": "database://microsoft-177b4c65f69-4b8d1d14f182fa5d/dhw_self/org.jkiss.dbeaver.ext.mssql.model.SQLServerSchema/repo/org.jkiss.dbeaver.ext.mssql.model.SQLServerTable/Index_Settings",
      "constraint": "PK_Index_Settings",
      "attributes": {
        "index_guid": "index_guid"
      }
    },
    {
      "entity": "database://microsoft-177b4c65f69-4b8d1d14f182fa5d/dhw_self/org.jkiss.dbeaver.ext.mssql.model.SQLServerSchema/repo/org.jkiss.dbeaver.ext.mssql.model.SQLServerTable/RepoObject",
      "constraint": "PK_RepoObject",
      "attributes": {
        "parent_RepoObject_guid": "RepoObject_guid"
      }
    }
  ]
},
```

Now I try to add one more virtual FK between the same column and another view, I can select them:

![image](https://user-images.githubusercontent.com/9020187/110146116-78ebe480-7dda-11eb-9524-1bf19a0b218c.png)

But when I press OK it will be transformed into "?"

![image](https://user-images.githubusercontent.com/9020187/110146237-a173de80-7dda-11eb-8dd4-6af7cdd75cb0.png)

And the same issue in the JSON file:

```json
":Index_gross": {
  "constraints": {
    "pk_Index_gross": {
      "type": "vpk",
      "attributes": [
        "index_guid"
      ]
    }
  },
  "foreign-keys": [
    {
      "entity": "database://microsoft-177b4c65f69-4b8d1d14f182fa5d/dhw_self/org.jkiss.dbeaver.ext.mssql.model.SQLServerSchema/repo/org.jkiss.dbeaver.ext.mssql.model.SQLServerTable/Index_Settings",
      "constraint": "PK_Index_Settings",
      "attributes": {
        "index_guid": "index_guid"
      }
    },
    {
      "entity": "database://microsoft-177b4c65f69-4b8d1d14f182fa5d/dhw_self/org.jkiss.dbeaver.ext.mssql.model.SQLServerSchema/repo/org.jkiss.dbeaver.ext.mssql.model.SQLServerTable/RepoObject",
      "constraint": "PK_RepoObject",
      "attributes": {
        "parent_RepoObject_guid": "RepoObject_guid"
      }
    },
    {
      "entity": null,
      "constraint": null,
      "attributes": {
        "parent_RepoObject_guid": "RepoObject_guid"
      }
    }
  ]
},
```

The first idea was, that I can't create virtual keys for the same column. But the issue is: I can't create any virtual FK between views.
If that is the case, then the virtual PF would be useless for me, because I want to use it primarily for views and for relationships between views.

**Comment by aisbergde** [comment]
Today it works. Maybe it was only necessary to restart dbeaver?

**Comment by LonwoLonwo** [comment]
Hello @aisbergde 
Did you update the version or simply restart DBeaver? Does the problem arise again?

**Comment by aisbergde** [comment]
@LonwoLonwo I did not update but just restarted. Currently, I can create them.

**Comment by LonwoLonwo** [comment]
Thank you for your update. It looks like the problem was solved. This issue will be closed.
Fell free to reopen this issue, if the problem appears again.
