### ISSUE TITLE
Roles permissions missing

### ISSUE THREAD

**Issue by AdrianoBortoloto** [dbeaver/dbeaver#11634]
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version: 7.3.5 and 21.0.0
- Additional extensions: None

#### Connection specification:
- Database name and version: PostgreSQL 10

#### Describe the problem you're observing:
Role properties Permissions didn't load the metadata.
#### Steps to reproduce, if exist:
Database Navigator > MyConnection > db > Roles > anyRole > (label Permissions)
#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/12927584/110173103-edc01e00-7ddc-11eb-8998-25990c174608.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
Fixed in 21.0.1
Will be available [here](https://dbeaver.io/) at 2021-03-22

**Comment by uslss** [comment]
verified
