### ISSUE TITLE
20.0: Error when Creating a new Connection.

### ISSUE THREAD

**Issue by Nemecsek** [dbeaver/dbeaver#11646]
#### System information: 
- Ubuntu 20.04
- DBeaver CE 21.0.0.202102281712 

#### Describe the problem you're observing:
Cannot create a new connection because of an error.
Old connections continue to work as before (when DBeaver 7.3 was installed).

#### Include any warning/errors/backtraces from the logs
When creating a new connection (Right click on `General/Connections/Create/Connection`) I get soon this error:

```
Internal error when opening new connection wizard

Reason:
class org.jkiss.dbeaver.ui.dialogs.driver.DriverTreeViewer cannot be cast to class org.jkiss.dbeaver.ui.dialogs.driver.DriverTabbedViewer (org.jkiss.dbeaver.ui.dialogs.driver.DriverTreeViewer and org.jkiss.dbeaver.ui.dialogs.driver.DriverTabbedViewer are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @430f0c63)
```

**Comment by serge-rider** [comment]
This bug is already fixed. We've released hotfix version right after 21.0 release. 
Just re-download it from dbeaver.io.
