### ISSUE TITLE
21.0.0 Dark Mode - Missing contrast

### ISSUE THREAD

**Issue by Peter-Kahlhoefer** [dbeaver/dbeaver#11645]
Hi.
Today I installed 21.0.0. I was using dark mode before. I never changed something in colors. But now the dark mode is no more usable. 
Selected projects are black font on nearly black background. 
All the > before expandable objects are also black on black -till you hover over it.

I tried to play with colors, but do not find a solution for the ">" signs.

May be it would be fine to get a correction pack for the dark mode?

Best regards, 
Peter

**Comment by Peter-Kahlhoefer** [comment]
Well. even the syntax highlighting in the SQL Editor is a nightmare in dark mode.
![08-03-_2021_11-25-59](https://user-images.githubusercontent.com/80254311/110310445-d9f60100-8002-11eb-8b3e-4010d8f9cb99.png)

**Comment by uslss** [comment]
thanks for the report
will be fixed in #11647
