### ISSUE TITLE
RedisJSON support

### ISSUE THREAD

**Issue by kentore82** [dbeaver/dbeaver#11644]
Currently Im unable to view values of RedisJSON type:
`WRONGTYPE Operation against a key holding the wrong kind of value` 

As a minimum, it would be great to at least have the possibility to view redisJSON datatype as string, but ideally in full json structure with edit possibilities.

https://oss.redislabs.com/redisjson/

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by serge-rider** [comment]
Implemented.
Also all JSON.XXX commands support was added. Redis commands processing was improved.
Now we support all Redis commands including publishing and subscriptions.

![image](https://user-images.githubusercontent.com/6398845/117542305-cf66e080-b020-11eb-82bc-f168a80976f4.png)

**Comment by uslss** [comment]
verified
