### ISSUE TITLE
Unreadable texts with dark theme

### ISSUE THREAD

**Issue by stratozero** [dbeaver/dbeaver#11647]
Using dark theme, some texts shows in a light grey shadowed of white, that is unreadable on popups (which have white background), and very difficult to read in menu.

OS: Windows 10
Database: PostgresSQL 11
Driver: JDBC

To reproduce popup: right click on a connection > Invalidate / reconnect
To reproduce menu: right click on a connection > Edit connection > select tab SSH, Proxy or SSL

![dbeaver-unreadable-popup](https://user-images.githubusercontent.com/16181266/110311069-9354d680-8003-11eb-9645-6be6c25d91ed.png)
![connecton-editor](https://user-images.githubusercontent.com/16181266/110311253-ceefa080-8003-11eb-966e-25fe6f931d01.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
Notifications issue #10841

**Comment by adamsolymos** [comment]
The same happened on MacOS 11.0.1 with DBeaver v 21.0.0.202102281712. Selected theme is Dark Theme

**Comment by uslss** [comment]
duplicates #10887
