### ISSUE TITLE
Object name hard to read when selecting an object in DB Navigator when in dark mode, name remains black.

### ISSUE THREAD

**Issue by ANTGOMEZ** [dbeaver/dbeaver#11665]
#### System information: 
Windows 10
DBeaver Version 21.0.0.202103021012

#### Describe the problem you're observing:
1: Set DBeaver Dark Mode
2: Open Database Navigator
3: Highlight any item in the Db hierarchies
4: See item name sets to black - is hard to read

The main reason for Dark Mode is better visibility through contrast.

I suggest keep text color white and perhaps change the highlight bar from dark blue to some other color which contrasts to make text better to read.

**Comment by uslss** [comment]
thanks for the report
duplicates #11647
