### ISSUE TITLE
Cannot edit cells in query result

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#11672]
#### System information: 
- CentOS 7
- DBeaver 21.0.0 (but happens on previous one as well)
- MySQL 10.3.28-MariaDB
- MariaDB connector/J 1.5.5

On Windows I cannot reproduce it.

Value is not editable in Panel:

![image](https://user-images.githubusercontent.com/4306334/110616368-8374f800-81a5-11eb-9023-8690577bf969.png)

But after double click it shows edit frame:

![image](https://user-images.githubusercontent.com/4306334/110616585-c040ef00-81a5-11eb-8710-5bb2155d9905.png)

Though readonly message displayed in the bottom. And I cannot accept text to save it.  
I do not know why it says anything about row Id - all rows have PK.  
And previously all worked well on the same data and on the same machine.

**Comment by ghost** [comment]
Normally working version is **7.0.5** (updated information, previously I specified 7.1.5 by mistake).

**Comment by kseniiaguzeeva** [comment]
Please hover over the lock in the column header and tell what is written in the tooltip. 
![110616585-c040ef00-81a5-11eb-8710-5bb2155d9905](https://user-images.githubusercontent.com/51405061/113263956-1a336100-92db-11eb-971c-8895d8ac6483.png)

Do you open the table in SQL Editor or Data Editor? If it is SQL Editor, please write a query which you execute.
Also you can try to upgrade DBeaver version.

**Comment by uslss** [comment]
there is no update on an issue for a long time. If it is still actual for you - feel free to reopen it.
