### ISSUE TITLE
full window value editor (Shift-Enter) opens content as read only in some cases (when called from a referenced table)

### ISSUE THREAD

**Issue by aisbergde** [dbeaver/dbeaver#11673]
related to #11628

The solution was to use Shift-Enter to open the full window value editor

But in this specific case the separate full window value editor opens the content read only.

It works fine when it will be opened for a normal table in the "main window", but when it is opened from a table in the referenced window then it is not possible to edit the content. It will open as read only

#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver Version 21.0.0.202102281712
- Additional extensions

#### Connection specification:
- Database name and version SQL Server 2019
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

it is not possible to edit the content

#### Steps to reproduce, if exist:

![image](https://user-images.githubusercontent.com/9020187/110625541-d946a180-819f-11eb-9368-5cffa75942fa.png)

1. open a table in the "main" window
2. open a related table on the right in the "References" window
3. select a cell you wish to edit and press "shift-Enter"
4. a separate windows will open
5. try to edit the content, this is not possible
6. open the same referenced table in a main window
7. use "shift-Enter"
8. now it is possible to edit the content

![image](https://user-images.githubusercontent.com/9020187/110626072-8e795980-81a0-11eb-9db8-a55cab01a8db.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
verified
