### ISSUE TITLE
Warn when closing editor with uncommitted transaction

### ISSUE THREAD

**Issue by JoelDKraft** [dbeaver/dbeaver#11683]
Several times I have accidentally closed the table editor when there was a pending transaction that had not been committed or rolled back.  Of course then everything starts locking up until you figure out you need to open it back up and deal with the transaction.

I think that you should be prompted to either commit or rollback the pending transaction before the window can be closed. I assume this would also apply to SQL editors (or now SQL consoles) that are being closed. It probably also makes sense when you are exiting the application entirely.

This obviously does not happen if you are in auto-commit mode, so that is technically a workaround, but that is not always a desirable setting. Another possibility would be to automatically commit or automatically rollback the transaction when you close the window.

**Comment by p91paul** [comment]
AFAIK this is already implemented for sql scripts, consoles, and exiting application. I don't think for table editor though.

**Comment by kseniiaguzeeva** [comment]
It makes sense. Do you have an idea what of the ways of implementation will be an optimal? How should the feature look like?

**Comment by E1izabeth** [comment]
Implemented
![image](https://github.com/dbeaver/dbeaver/assets/28875055/62c24e27-e9d6-4701-9422-930f2be79cb2)
