### ISSUE TITLE
Dbeaver will not list all the databases created for a connection

### ISSUE THREAD

**Issue by SteveSzumski** [dbeaver/dbeaver#11682]
#### System information: 
- macOS 10.15.7 
- DBeaver version Version 21.0.0.202103021012

#### Connection specification:
- Database name and version postgresql

#### Describe the problem you're observing:
I have created 2 new databases on a local connect 127.0.0.1
I restored a database backup for them and it successfully restored and Iw as able to use the databases for local development. 

When I close dbeaver or restart my computer, the newly created databases are not there in the browser. 
I cannot access the new databases or the tables in them, but if I try and create a new database of the same name, it throws and error and says the database by that name already exists. But there are no databases listed in that connection.

**Comment by ShadelessFox** [comment]
Hello @SteveSzumski,

Please make sure that <kbd>Show all databases</kbd> inside connection configuration is set:
![image](https://user-images.githubusercontent.com/35821147/110761862-43734b00-8261-11eb-9107-ac1e2c2df533.png)
