### ISSUE TITLE
How to view output of Ref Cursor in Dbeaver Version 7.3.3

### ISSUE THREAD

**Issue by rajaramanwork** [dbeaver/dbeaver#11686]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by rajaramanwork** [comment]
DECLARE 
  P_APPLICATION_KEYS VARCHAR2(32767);
  P_CURSOR SYS_REFCURSOR;

BEGIN 
  P_APPLICATION_KEYS := '1,3,5';
  P_CURSOR := NULL;

  AWP.PKG_WORKFLOW_AUTHORING_API.P_GET_WORKFLOW_VERSIONS_EXT ( P_APPLICATION_KEYS, :P_CURSOR );
  COMMIT; 
END;

**Comment by rajaramanwork** [comment]
DECLARE 
  P_APPLICATION_KEYS VARCHAR2(32767);
  P_CURSOR SYS_REFCURSOR;

BEGIN 
  P_APPLICATION_KEYS := '1,3,5';
  P_CURSOR := NULL;

  PKG_WORKFLOW_AUTHORING_API.P_GET_PROC ( P_APPLICATION_KEYS, :P_CURSOR );
  COMMIT; 
END;

**Comment by uslss** [comment]
what database do you use?
Could you check the issue against the recent version (21.0)?

**Comment by rajaramanwork** [comment]
Oracle 19

**Comment by uslss** [comment]
cannot reproduce it against 21.0.4.
If it is still actual for you - feel free to reopen it
