### ISSUE TITLE
InfluxDB 2 support in EE

### ISSUE THREAD

**Issue by mattfabina** [dbeaver/dbeaver#11684]
**Is your feature request related to a problem? Please describe.**
InfluxData is increasingly pushing their roll-out of InfluxDB 2, including, for example, having their primary Docker image point to an InfluxDB 2 version.

**Describe the solution you'd like**
It would be great if DBeaver EE would move to support InfluxDB 2. My layman's understanding is that only the authentication methods need to be updated; most of the underlying functionality remains the same.

**Describe alternatives you've considered**
The only alternative would be to explicitly state that DBeaver EE only supports InfluxDB < 2 (i.e. 1.8.4 or earlier).

**Additional context**
https://www.influxdata.com/blog/influxdb-2-0-open-source-is-generally-available/
https://docs.influxdata.com/influxdb/v2.0/upgrade/v1-to-v2/

**Comment by uslss** [comment]
Thanks for the info and suggestion. 
Hope, it will be implemented in the nearest future
