### ISSUE TITLE
Discover update wants dbeaver community 21.0.0 to upgrade to 7.3.1 

### ISSUE THREAD

**Issue by joekrukosky** [dbeaver/dbeaver#11698]
I'm running Pop!OS (ubuntu) with KDE and Discover keeps asking me to update dbeaver to 7.3.1 when I'm running 21.0.0.
Anyone else having this trouble or know what's going on?

**Comment by kseniiaguzeeva** [comment]
Please send log files https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by joekrukosky** [comment]
[Log-for-11698.txt](https://github.com/dbeaver/dbeaver/files/6205677/Log-for-11698.txt)

**Comment by kseniiaguzeeva** [comment]
Thank you, but it was not enoughю Please send also debug log completely https://github.com/dbeaver/dbeaver/wiki/Log-files.

**Comment by uslss** [comment]
there is no update on an issue for a long time. If it is still actual for you - feel free to reopen it.
