### ISSUE TITLE
Displaying C# GUID in Oracle

### ISSUE THREAD

**Issue by christopheblin** [dbeaver/dbeaver#11690]
Currently, when you use the Hex formatter for binary data, you can see something like :

![image](https://user-images.githubusercontent.com/11044877/110779651-12e0e080-8264-11eb-8664-2c11b83224de.png)

However, as explained in https://stackoverflow.com/a/7289991/1545567, in C#, the GUID generation is using FlipEndian

So basically, if I use Entity Framework Core and I do

var obj = new Obj { Id = Guid.NewGuid() }
db.Objs.Add(obj)
db.SaveChanges();

What I will see in DBeaver with the Hex formatter is not something I can use directly in C#

It is "trivial" to see the correct thing in DBeaver :

SELECT 
SUBSTR (HexV, 7, 2) || SUBSTR (HexV, 5, 2) || SUBSTR (HexV, 3, 2) || SUBSTR (HexV, 1, 2) || SUBSTR (HexV, 11, 2) || SUBSTR (HexV, 9, 2) || SUBSTR (HexV, 15, 2) || SUBSTR (HexV, 13, 2) || SUBSTR (HexV, 17, 16) AS MyNETVal
FROM (SELECT 'XXXX' HexV FROM Dual);

However, using a manual query instead of the data view is a bit tedious when you do that 100+ times a day ....

Is it possible to register somewhere in DBeaver that everytime there is a raw(16), I'd like to use this "sql function" instead of the "simple" Hex

**Comment by kseniiaguzeeva** [comment]
We should implement a correct GUID view in Oracle. Thank you for the report.

**Comment by ShadelessFox** [comment]
Hello @christopheblin,

You can use UUID formatter with <kbd>UUID type</kbd> &rArr; <kbd>Version2</kbd>:

![image](https://user-images.githubusercontent.com/35821147/127669313-1a1c831e-8ac2-4b1f-bc67-ea1dc3aec684.png)

https://dbeaver.com/docs/wiki/Data-View-and-Format#transforming-data-presentation

**Comment by christopheblin** [comment]
I am not working with oracle and c#, however I'm still using dbeaver for postgres :)

Currently, in the View format menu, I only have default / binary / geometry / URL

So maybe this is something only availble on a RAW column in oracle and I cannot see it wit postgres ?

**Comment by ShadelessFox** [comment]
What's the type of column you're trying to apply transformer to?

**Comment by ShadelessFox** [comment]
Hello @christopheblin,

Is there any updates? Please take look at https://github.com/dbeaver/dbeaver/issues/11690#issuecomment-890014845. Thanks!

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it
