### ISSUE TITLE
stuck on splash screen 

### ISSUE THREAD

**Issue by lateo-net** [dbeaver/dbeaver#11694]
#### System information: 
- win 10 1809
- DBeaver 21
- Additional extensions : broke DBeaver trying to install extensions/drivers offline

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Context : it broke after i tried everything i could think of to offline install stuff so that DBeaver is usable offline.
Finally found some "success" in installing a random feature. Well it asked me to restart DBeaver after installing the feature then Dbeaver would not start again (loop on splash screen).
Kill the forever respawning process, uninstall DBeaver, reinstall checking "reset config".
Start DBeaver : looping on splash screen.
Delete everything in %APPDATA%, restart DBeaver : loop on splash screen.

Priority : extra-low : since i just can't make DBeaver work offline wherever i put the jar files and however i try to add them to the library, i'm very probably going to forget about it to provide my users something they can actually use.

AKA i'm reporting this just in case it may help.

**Comment by alumni** [comment]
I get a restart loop when I'm online.

Reproduction steps: 
1. install 21.0.0
2. install excel export + svg export addons
3. upgrade to 21.0.1
4. migrate addons + restart

It will then go on a restart loop.

The versions are probably irrelevant, this has been happening for quite some time.

Logs are not created in `%APPDATA%`, the crash happens before they are written there.

I noticed that if I run DBeaver as admin once it's fine.

**Comment by kseniiaguzeeva** [comment]
Please try to delete _.eclipse_ folder (`${HOME}/.eclipse`). It should help.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it.
