### ISSUE TITLE
We don't include the `AS` clause for table aliases because it is not required and thus can be omitted.

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#11699]
We don't include the `AS` clause for table aliases because it is not required and thus can be omitted.

__Originally posted by @ShadelessFox in https://github.com/dbeaver/dbeaver/issues/11625#issuecomment-795344121__

TBH I don't understand why the original issue has been closed. I raised the issue as **feature request**. Didn't ask why DBeaver doesn't have this feature. Insted I've asked if can be added unless it has it already.

The AS keyword is not mandatory but it's part of SQL standard. I know a lot of teams are using AS keywords for sake of improving code readability and/or to be compliant with coding standards.

Adding this keyword (as option) would just be a time saver

**Comment by ShadelessFox** [comment]
Hello @michalk-k,

It was a rude statement of me, I'm sorry for that. I thought it was more a question than an actual feature request. The issue was converted into the discussion, if that still makes sense.

We will implement this as a feature, it would be a nice small addition.

**Comment by ShadelessFox** [comment]
Now you can choose between several flavors:
![java_GZBAlrUgvP](https://user-images.githubusercontent.com/35821147/111294712-a8f97a00-865b-11eb-96d5-7736ea39d373.png)

Note: actually this is a good feature since some SQL dialects can _theoretically_ lack or require the `AS` keyword for aliases.

**Comment by uslss** [comment]
verified

**Comment by michal-bartak** [comment]
Great thank you. 
Just comment on "in FROM clause": will it work also for tables referenced in JOINS? 
And tbh it must not be tables only. It could be views or functions which returns record(sets) etc.

**Comment by ShadelessFox** [comment]
Yes, it will work with `JOIN` clauses.

Also, you can create an additional FR to support function aliasing, but I'm not sure what you mean.

**Comment by michal-bartak** [comment]
Thanks for response.

I meant:
SELECT * FROM some_schema.some_function() AS ...
