### ISSUE TITLE
PostgreSQL 11 - Unable to edit JSON column

### ISSUE THREAD

**Issue by sharathr1** [dbeaver/dbeaver#11704]
Whenever we edit a json column or non-json column in the table which has json column is not supported.

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
Hello @sharathr1 
Can you provide example of table DDL and version of your PostgreSQL database? I can't reproduce.
Thanks in advance.

PS: More precisely, while it turned out to be reproduced only when the update occurs with all columns as key.

**Comment by sharathr1** [comment]
> Hello @sharathr1
> Can you provide example of table DDL and version of your PostgreSQL database? I can't reproduce.
> Thanks in advance.
> 
> PS: More precisely, while it turned out to be reproduced only when the update occurs with all columns as key.

CREATE TABLE "public"."AppConfig" (
	 id varchar(25) NULL,
	"type" varchar(100) NULL,
	jsonInfo json NULL
);

**Comment by LonwoLonwo** [comment]
@sharathr1 Yes, I see.
We will fix it
As workaround - use real or virtual keys in table, then update statement will use them.

**Comment by LonwoLonwo** [comment]
related https://github.com/dbeaver/dbeaver/issues/6779

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.3.0
Works for update/delete statements in the tables without keys and with JSON or XML columns.

**Comment by uslss** [comment]
verified
