### ISSUE TITLE
cannot execute query with db monitor

### ISSUE THREAD

**Issue by bdaboah** [dbeaver/dbeaver#11703]
hello

when we open the monitoring database (ctrl alt shit B), we cannot :

execute sql statement with ctrl-enter => new ligne instead of
delete character of the query with del button => nothing

sorry for my english ^^

![Screenshot_2021-03-12_10-40-51](https://user-images.githubusercontent.com/466506/110922360-e25e7c80-831f-11eb-8ba8-ed601d1f82b2.png)
 
dbeaver Version 21.0.0.202103021012

Linux xxx 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux

openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

**Comment by serge-rider** [comment]
Could you check error/debug log for any related errors? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual for you - feel free to reopen it
