### ISSUE TITLE
after save drop down again changed to NA

### ISSUE THREAD

**Issue by tharun-d** [dbeaver/dbeaver#11710]
#### System information: 
- Operating system (distribution) and version : ubuntu 16.04
- DBeaver version latest deb version
- Additional extensions no

#### Connection specification:
- Database name and version maria db
- Driver name maria

when ever I select host and db name from drop down

and writing script its working if I click ctrl+s drop down again changed to NA. again I have to select host and db

**Comment by uslss** [comment]
Hi @tharun-d ,
unfortunately, cannot reproduce it. Is there something in the logs? Could you provide a video of the issue?

**Comment by tharun-d** [comment]
Adding video @uslss 

https://user-images.githubusercontent.com/24644710/111581319-07029a80-87df-11eb-839d-12c8a9a0d01e.mp4

**Comment by tharun-d** [comment]
@uslss   just now updated to latest one the issue is still there please note only after change script and do ctrl + s or file save it happens

**Comment by uslss** [comment]
sorry for the late response.
Is the issue still actual? 
unfortunately, cannot reproduce it

**Comment by uslss** [comment]
there is no update for a long time.
If it is still actual - feel free to reopen the issue.
