### ISSUE TITLE
Table filters to be case-insensitive

### ISSUE THREAD

**Issue by psuplat** [dbeaver/dbeaver#11719]
This is mainly issue when working with Postgresql.
Filters are case-sensitive. Making them case-insensitive would be a really nice touch.
For example, in the below screen, typing in col, will find Nicola, but Colin will be omitted from the list.
![image](https://user-images.githubusercontent.com/14207860/111052768-e7254c80-8455-11eb-8fe2-8b4993de699d.png)

**Comment by noschang** [comment]
I upvote this!!

Also, I'm from Brazil and here we have values with accents.
If you're gonna have work to make this case insensitive it would be nice to also make it accent insensitive.
So, for example, if you search for ```sao```, you would find values like so: ```São Paulo```, ```Eles são muito espertos```

**Comment by ShadelessFox** [comment]
Hello @noschang,

Thanks for the suggestion!

Fortunately, we can implement that, it would be a nice feature.

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea. @psuplat As a workaround have you tried to use Full-text search (in the main menu or top toolbar)? You can modify case-sensitive option there.
![Screenshot 2021-03-23 at 13 32 20](https://user-images.githubusercontent.com/51405061/112133717-056d1400-8bdd-11eb-8428-966343b01e2f.png)

But it doesn't support accent case.

**Comment by ShadelessFox** [comment]
Hello @noschang,

After future investigation we concluded that it is not possible to implement, unfortunately. Accent-insensitivity is a tricky thing that depends on the collation settings which vary between databases.

It is better to create a separate FR from your request, so we can track it in the future.

**Comment by ShadelessFox** [comment]
Implemented for PostgreSQL, Oracle:
![image](https://user-images.githubusercontent.com/35821147/114153390-edf59100-9927-11eb-9431-910b2131bf9c.png)

**Comment by kseniiaguzeeva** [comment]
verified
