### ISSUE TITLE
Improve app icon

### ISSUE THREAD

**Issue by ravshansbox** [dbeaver/dbeaver#11718]
App icon doesn't look great in dock, looks bigger than other icons:
<img width="731" alt="image" src="https://user-images.githubusercontent.com/1499188/111037203-f3ed7480-8444-11eb-9339-72739e47d35e.png">

**Comment by serge-rider** [comment]
Agreed

**Comment by dextok** [comment]
[dbeaver.icns.zip](https://github.com/dbeaver/dbeaver/files/6176981/dbeaver.icns.zip)

<img width="781" alt="20210321145622" src="https://user-images.githubusercontent.com/25945825/111896596-ceb8c180-8a55-11eb-9102-98048330788e.png">
It looks much better after using the regenerated icns file.
however, same as #11557, it is overwritten by the original big and square icon when dbeaver is running and I don't know how to get rid of it.
<img width="783" alt="20210321150218" src="https://user-images.githubusercontent.com/25945825/111896717-7cc46b80-8a56-11eb-8895-2ef2c3f9486e.png">

**Comment by kseniiaguzeeva** [comment]
Icon is ok on Mac
![Screenshot 2021-03-30 at 09 37 01](https://user-images.githubusercontent.com/51405061/112948056-3cdd4280-9140-11eb-82a6-0bf133e0df1f.png)
but looks small on Win

**Comment by uslss** [comment]
win:
![image](https://user-images.githubusercontent.com/31996417/112961421-04dcfc00-914e-11eb-9156-99c9540557f0.png)

**Comment by serge-rider** [comment]
If icon doesn't change try icon cache reset or machine reboot.
