### ISSUE TITLE
DBMS_OUTPUT dbeaver position

### ISSUE THREAD

**Issue by robertos1232** [dbeaver/dbeaver#11712]
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04
- DBeaver version dbeaver 21
- Additional extensions None

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I have i problem with "output dbms."
Because i do not see the option to position it.
In previous version i can find him next too result of the bottom

Can i change his position in this version?

**Comment by kseniiaguzeeva** [comment]
Please send a picture and show where the option was before.

**Comment by robertos1232** [comment]
There is a version 7.0.
![image](https://user-images.githubusercontent.com/40420170/112495842-8dd9e900-8d84-11eb-9962-2c8ed48ce05e.png)

**Comment by robertos1232** [comment]
There is a version 21.
![image](https://user-images.githubusercontent.com/40420170/112496342-f45f0700-8d84-11eb-9d54-ad6b6ec3d881.png)

**Comment by kseniiaguzeeva** [comment]
It is not a bug, the Output panel was redesigned and changed its place. It couldn't be positioned in the old design too. You can resize it.

https://user-images.githubusercontent.com/51405061/113264285-78f8da80-92db-11eb-8a69-6f9d8cfdda21.mp4
