### ISSUE TITLE
Debbuging with mariadb

### ISSUE THREAD

**Issue by bfharreguy** [dbeaver/dbeaver#11711]
Hello!! i try to o a debugg with mariadb and i have the error "Driver mariadb no support debugging"
I try to ativate debuging in Driver mariadbconnector J
https://mariadb.com/kb/en/about-mariadb-connector-j/#debugging
The problems persinst!! if mysql works i think what in mariadb should be work, please help!1 i need a do a debug
Im using DBeaver last version of comunity
Mariab server 10.5.8
Mariadb connector J Last version 2.7.2
Windows 10 with all last updates
My server mariadb is locally and imnot using a vpn or ssl o wherever

**Comment by kseniiaguzeeva** [comment]
It is not implemented yet in DBeaver. We will be working on your ticket in 21.1.1 where we are going to improve debugger.

**Comment by ShadelessFox** [comment]
Hello @bfharreguy,

If you're talking about debugging stored routines, then it is not possible. MySQL and MariaDB don't provide any debugging API.

But you can debug the server itself:
https://dev.mysql.com/doc/refman/5.7/en/debugging-server.html
