### ISSUE TITLE
Only part of the file is imported and no error prompted

### ISSUE THREAD

**Issue by iwantmyway** [dbeaver/dbeaver#11721]
I use the import a csv to sqlite database. 
My file have around 500k row. When it run through about the first 360k, it close and report import success.
I also check my file at the row where it stop importing, no issue was found on that row. 

https://imgur.com/nccV1vo
https://imgur.com/N7vQytE
https://imgur.com/MqkIqrN

**Comment by kseniiaguzeeva** [comment]
Please tell DBeaver version. Do you use SSH, VPN etc? Also please send log and debug log https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it.
