### ISSUE TITLE
Show DB size of pg base in 21.0.0

### ISSUE THREAD

**Issue by eugenesotnikov** [dbeaver/dbeaver#11727]
#### System information: 
- Windows 10
- DBeaver version 21.0.0
- Additional extensions

#### Connection specification:
- PostgreSQL 11.8 
- PostgreSQL JDBC Driver 42.2.5

#### Describe the problem you're observing:

If have upgraded from 7.1.5 to 21.0.0 
And in 7.1.5 was size of db in postgres. But in 21.0.0. it is gone. On screen i showed where it was.
How to enable it?
![image](https://user-images.githubusercontent.com/60689184/111116129-9c4f2600-8576-11eb-870f-6034ae84be27.png)

**Comment by eugenesotnikov** [comment]
I downgraded to 7.1.5.  
It was as
![image](https://user-images.githubusercontent.com/60689184/111117149-306dbd00-8578-11eb-878c-3c38b65c4df7.png)
It was very comfortable for many database

**Comment by LonwoLonwo** [comment]
Hello @eugenesotnikov 
It was a test implementation of that FR in version 7.1.5
But, unfortunately, its introduction led to many problems (mainly because the databases of users are usually heavy), so we immediately turn it off.
However, we still can return PostgreSQL DB statistic as feature request in next releases. 
Thanks for idea.

**Comment by eugenesotnikov** [comment]
Must i create FR?
It's really very good feature

**Comment by LonwoLonwo** [comment]
Now. I marked this ticket as enhancement/feature request. Thanks.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/117197111-16ba5a80-adf0-11eb-87f3-f8f974f6fe21.png)

**Comment by eugenesotnikov** [comment]
i installed 21.0.4 and that check-box is absent.

**Comment by LonwoLonwo** [comment]
Hello @eugenesotnikov 
This is feature of DBeaver 21.0.5 release
Will be available [here](https://dbeaver.io/) at 2021-05-17

**Comment by eugenesotnikov** [comment]
Ouu. Ok. I will be waiting.

**Comment by LonwoLonwo** [comment]
@eugenesotnikov also you can check it here https://dbeaver.io/files/ea/ 
The version of May 5 does not contain these changes. However, EA is updated more often.

**Comment by uslss** [comment]
verified
