### ISSUE TITLE
"Import data": Filechosser does not order sensibly

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#11733]
I frequently need to importa CSV file into a table.
Opening the file chooser, it usually is hard to spot the file, since the order is rather un-helpful.
Default order seems to be by name, which has files and directories in a complete jumble.
A much more sensible initial order would be by type, so that files and directories are collected in two sections, and then by name and/or date.
Thus one immediatelly knows where to look instead of re-ordering or scrolling.

#### System information: 
- Operating system (distribution) and version Debian/SID
- DBeaver version Version 21.0.0.202102281712
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by ShadelessFox** [comment]
Hello @2019-05-10,

I'm not quite understand what you're talking about. DBeaver uses native system components, such as file chooser in your case.

Can you please provide screenshots?

**Comment by 2019-05-10** [comment]
I assume, when instantiating the file chooser, you can as well set the sorting, as you obviously do with the file type ("*.csv")?
 
![Screenshot_20210315_121405](https://user-images.githubusercontent.com/50481865/111181634-780f3b80-85ae-11eb-8c4d-0d6487714f94.png)

Order here should be
files
directories

not as is now a mix like

adirectory
afile
bdirectory
cdirectory
dfile
edirectory
...

**Comment by ShadelessFox** [comment]
Unfortunately, we can't specify the sorting order by ourselves for such platform-specific (and distro-specific) stuff.

Specifying the file filters is a fundamental and well-established feature, but changing sorting, well, rather the opposite.

You can try tweaking settings of your file manager.

**Comment by p91paul** [comment]
@2019-05-10 I think the way sorting works might depend on your default file manager application settings
