### ISSUE TITLE
Update standard Eclipse UI localization

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#11738]
We need yo update Babel to 2020-12

**Comment by serge-rider** [comment]
Done. 
This must be tested with Chinese, Russian, Korean, Japanese, German, French and Portuguese localizations (using -nl parameter)

**Comment by kseniiaguzeeva** [comment]
Chinese, Russian, Korean, Portuguese, Japanese, German, French localizations (using -nl parameter) tested on Mac and Win

Note: Portuguese locale shows wrong interface language.
![Screenshot 2021-03-21 at 16 47 51](https://user-images.githubusercontent.com/51405061/111907451-61615c80-8a66-11eb-8898-db34bd5f31ed.png)
