### ISSUE TITLE
CSV Datetime formats can't be converted

### ISSUE THREAD

**Issue by Robynishere1** [dbeaver/dbeaver#11737]
#### System information: 
- Operating system (distribution) and version
**Windows 10**
- DBeaver version
**21.0.0**
- Additional extensions

#### Connection specification:
- Database name and version 
**CSV File**

- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Hi there

I have a file folder that automatically imports CSV files saved in it, into DBeaver as tables. I am having trouble converting the date format. Automatically, all fields get imported as characters and my attempts to manually change the dates using the importer haven't work. 
In my syntax, I've tried the following:
- When datetime is in Epoch format:  **to_timestamp(TRUNC( CAST( "time" AS bigint ) / 1000 ) )**
- When datetime is human readable: **cast("timestamp" as date)**
- Convert(datetime, "timestamp)

It seems like the date conversion functions might not be recognized. In all examples my error looks like this:

**SQL Error: Syntax error: Encountered " "AS" "AS "" at line 3, column 34.
Was expecting:
    ")" ...**

**Comment by ShadelessFox** [comment]
Hello @Robynishere1,

Can you provide step-by-step tutorial on how to reproduce your issue?

To be honest, I'm a bit confused. Are you talking about "flat files" driver for CSV files? Or you're trying to perform data transfer from CSV file to the table in your database? Please provide more context.

**Comment by Robynishere1** [comment]
Hi there!


  1.  Save a CSV in a folder and refresh the CSV- downloads database
     *   CSV’s in the folder appear in the tables list
     *   Photo of DBeaver Tables:



***@***.***D71A41.C541A8D0]



     *   Photo of File location with CSV Files:



***@***.***D71A42.914DFCD0]



     *   Snapshot of select all statement:

***@***.***D71A43.743F8590]



     *   Snapshot of error message appears after each attempt to convert date from string:

***@***.***D71A43.743F8590]



  1.  All date fields are imported as characters/strings. And none of the syntax I have mentioned work.
  2.  Manually trying to import the CSV has resulted in duplicate tables, with date fields that seem to be a datetime format but they cannot be used in aggregations because the functions for formatting are not recognized still.

Hope this helps!

**Comment by ShadelessFox** [comment]
Unfortunately, I can't see any attachments nor images 😕

This may happen when you're answering through your mail, not github itself.

**Comment by Robynishere1** [comment]
The photos don't seem to be working in the github comments. They won't attach to my response.

**Comment by ShadelessFox** [comment]
If they're attached as a link, that's okay - if you enable <kbd>Preview</kbd> mode, they should be here.

Otherwise, you can use free image hosting like https://imgur.com/.

**Comment by Robynishere1** [comment]
Hi
I've attached the text and images via a word doc. Let me know if that helps!
Thanks!

[description of issue.docx](https://github.com/dbeaver/dbeaver/files/6152370/description.of.issue.docx)

**Comment by kseniiaguzeeva** [comment]
Unfortunately, it is not a bug, which can be fixed, but a limitation of CSV driver. As a workaround you can import the table into another database which support date/time format via DBeaver import/export tools.

**Comment by Robynishere1** [comment]
Thank you for confirming, can I leave this feedback as a feature request?

**Comment by kseniiaguzeeva** [comment]
You should ask CSV for this feature https://www.cdata.com/drivers/csv/. Also other CSV driver versions may support date format.
