### ISSUE TITLE
Filter by value when double clicking on a filter option

### ISSUE THREAD

**Issue by fabianMendez** [dbeaver/dbeaver#11742]
**Is your feature request related to a problem? Please describe.**
This would just be a QOL improvement, but it is annoying that when I double click on an item of the filter options it applies an "is null" filter:

![imagen](https://user-images.githubusercontent.com/32204060/111227336-67f85b80-85b0-11eb-935e-585d5ceae6f8.png)

![imagen](https://user-images.githubusercontent.com/32204060/111227368-747cb400-85b0-11eb-9744-7d415e77c429.png)

**Describe the solution you'd like**
I think it would be better if the filter was applied as if I've  checked the value and clicked on apply filter.

**Describe alternatives you've considered**
Checking the value and then clicking on apply filter. However it is a two step process and it is a little difficult to hit that checkbox.

**Comment by kseniiaguzeeva** [comment]
Please tell DBeaver version and your database. I cannot reproduce your case, but it looks like a bug.
I tested in PostgreSQL and SQLite:
1. Open a table
2. Open a filter in column header
3. Double click a value in the filter list,

**Actual result:**
- a first column value is applied to column with a primary key
- a filter is not applied for other columns

https://user-images.githubusercontent.com/51405061/112116892-cb474680-8bcb-11eb-89fe-58f155d23c44.mov

**Comment by ShadelessFox** [comment]
Note to a previous comment:

In both cases if any items are selected, then following double-click (no matter where) will close dialog and apply filter with previously selected items.

**Comment by fabianMendez** [comment]
@ShadelessFox thanks for your response.

I was testing on dbeaver 21.0.0 but now with dbeaver 21.0.1 it does not add the `is null` filter which is a great first step, however, as you've mentioned double clicking only submits the filter dialog. It would be great if double clicking on an item would apply it as a filter.

**Comment by uslss** [comment]
verified
