### ISSUE TITLE
An escape sequence in a SQL Query was malformed.

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#11749]
#### System information: 
- Operating system (distribution) and version: **_Microsoft Windows 10 Enterprise 10.0.17763 Build 17763_**
- DBeaver version: **_21.0.0.202103040430_**
- Additional extensions: **_n/a_**

#### Connection specification:
- Database name and version: **_Adaptive Server Enterprise/12.5.4_**
- Driver name: **_Sybase JConnect_**
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: **_No_**

#### Describe the problem you're observing:
My supervisor uses Vim and in order to determine where a statement block begins and ends he uses curly braces preceded by a single line comment (e.g. `--{ ` ). When I try to run code with this kind of markup in DBeaver although the editor marks it as a comment it does not ignore it causing the script to fail.

#### Steps to reproduce, if exist:
Just copy, paste and execute the below code in an SQl editor:

```
if (1=1)
begin--{
  select 1
end--}
```

#### Include any warning/errors/backtraces from the logs

```
SQL Error [JZ0S8]: JZ0S8: An escape sequence in a SQL Query was malformed: '{
  select 1
end--}'.
  JZ0S8: An escape sequence in a SQL Query was malformed: '{
  select 1
end--}'.
  JZ0S8: An escape sequence in a SQL Query was malformed: '{
  select 1
end--}'.
```

![Error](https://user-images.githubusercontent.com/60822998/111289827-346c0e80-864e-11eb-80de-12da4408b65d.png)

**Comment by ShadelessFox** [comment]
Hello @andreasnikiforosgeorgiadis,

This is a problem of the database you're using.

**Comment by ghost** [comment]
Hi,

If I execute the same code using a different DB client it works fine.

Could you please clarify?



Στις Τρί, 16 Μαρ 2021, 3:58 μ.μ. ο χρήστης Who cares <
***@***.***> έγραψε:

**Comment by ShadelessFox** [comment]
I believe the reason may be is that different DB client removes all the comments from the query before sending it to the server, but DBeaver don't do that (as described here https://github.com/dbeaver/dbeaver/issues/11661#issuecomment-795355779).

I can see this specific error mentioned in Sybase docs [here](http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc39001.0707100/doc/html/san1353998005849.html).

**Comment by ghost** [comment]
Thank you, I'll check the links and get back to you.

If you think the issue can be closed, then go ahead.


Στις Τρί, 16 Μαρ 2021, 6:15 μ.μ. ο χρήστης Who cares <
***@***.***> έγραψε:

**Comment by ShadelessFox** [comment]
Okay, I will close the issue, but you can still comment here.

**Comment by ghost** [comment]
Hello @ShadelessFox,

I read what you sent, saw your comment about the potential problem the database driver was causing and remembered that I had another option when creating a Sybase connection (jTDS). So, I created a new connection to the database using the latest version of **[jTDS](http://jtds.sourceforge.net/)** (instead of jConnect) and the same code worked fine.

I'll check if there is a setting for jConnect that I can tweak and post again. Thank you!

Best,

Andreas

![Solution](https://user-images.githubusercontent.com/60822998/111480341-9144f300-873a-11eb-87ee-26396c1b605c.png)

**Comment by ShadelessFox** [comment]
You are welcome!
