### ISSUE TITLE
Add File name pattern Variable in Data Transfer Output Wizard

### ISSUE THREAD

**Issue by georgethemarmot** [dbeaver/dbeaver#11748]
Hi, it would be really helpful to add the script file name variable ${fileName}  as usable into the data export wizard.
Thank you

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea

**Comment by kseniiaguzeeva** [comment]
Please tell which type of export do you mean (e.g. _export from query_ or another)?

**Comment by georgethemarmot** [comment]
Hi, export from query results.
Thanks

**Comment by ShadelessFox** [comment]
Implemented. Now you can use `scriptFilename` variable to access source script's filename (without extension).

**Comment by Matvey16** [comment]
Verified

**Comment by fa-novello** [comment]
I can see the scriptFilename variable, but I couldn't find any documentation about how to use it on my command list. How am I going to setup each file name?
