### ISSUE TITLE
Active tab or window view scaling. Ctrl + mouse scroll wheel

### ISSUE THREAD

**Issue by ghYura** [dbeaver/dbeaver#11746]
Add view/font scaling for any active tab or window for the DBeaver
Closest analog as expected is in your browser:
Press "Ctrl" + mouse scroll wheel
10% <... 100% ...< ?
Thank you.

**Comment by ShadelessFox** [comment]
Hello @ghYura,

You can change scale factor using <kbd>Ctrl</kbd>+<kbd>+/-</kbd>.
