### ISSUE TITLE
A bug was found when trying to use CTE

### ISSUE THREAD

**Issue by samgoularte** [dbeaver/dbeaver#11754]
#### System information: 
- Operating system (distribution) and version: **Microsoft Windows 10 Enterprise**
- DBeaver version: **21.0.0.202103021012**
- Additional extensions: **-/-**

#### Connection specification:
- Database name and version: **SQL Server 2019 Enterprise**
- Driver name: **MSSQL JDBC 8.2.0**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **no**

#### Describe the problem you're observing:
I've been working on rewriting a query that uses CTE, but a syntax error occurs all the time.
What we notice is that the editor does not find the beginning and end of a block defined by a semicolon.
_Note: This query respects the syntax presented in the MSSQL documentation_

#### Steps to reproduce, if exist:
I just pasted the section where the bug is detected

    DECLARE @DATA_INICIO DATE, @DATA_FIM DATE;
    SET @DATA_INICIO = '2017-01-01';
    SET @DATA_FIM = '2021-12-31';
    SET NOCOUNT OFF;
    ;WITH OS_COUNTER_CTE(ANO, MES, AT, QTD_OS_MES) AS 
    (SELECT
         X1.ano_dat         
        ,X1.num_mes         
        ,X0.TL_LOCAL        
        ,COUNT(X0.TL_ORDEM)
     FROM STL010 X0
     INNER JOIN EIS_DIMENSAO_DAT X1 ON (CAST(X0.TL_DTINICI AS DATE) = X1.dat_refer)
     WHERE CAST(X0.TL_DTINICI AS DATE) BETWEEN @DATA_INICIO AND @DATA_FIM AND X0.D_E_L_E_T_ != '*'
     GROUP BY X1.ano_dat, X1.num_mes, X0.TL_LOCAL)

#### Include any warning/errors/backtraces from the logs
Error occurred during SQL script execution

Reason:
SQL Error [102] [S0001]: Incorrect syntax near 'OFF'.

![image](https://user-images.githubusercontent.com/54247948/111323169-5febfa80-8648-11eb-8136-2f899fcca427.png)

**Comment by uslss** [comment]
verified
