### ISSUE TITLE
Open previous/next table

### ISSUE THREAD

**Issue by bjkluft** [dbeaver/dbeaver#11751]
**Is your feature request related to a problem? Please describe.**
Not a real problem, but I currently have a database with 266 tables which I have to identify and describe. I now use the "Table" button on the right to open the next table.
![image](https://user-images.githubusercontent.com/12735834/111316199-558b2a00-8663-11eb-97a2-595299f3a8e2.png)
However I have to scroll down to the current table (should be nice to have the current active table directly in view) to select the next.

**Describe the solution you'd like**
It would be very nice to have a shortcut to open the previous or next table. For example: Ctrl+Shift+< and Ctrl+Shift+>

**Describe alternatives you've considered**
As stated above, it would already help if the current table is in direct view of the pull-down, now it is greyed-out but the user needs to scroll down to see it.

**Comment by kseniiaguzeeva** [comment]
DBeaver has _Link with Editor_ option (`Ctrl+Shif+,`) which can cover your needs. It synchronizes the active editor with the element in the DB Navigator. Press it in DB Navigator (or use shortcut) when you have a table opened, and this table will be selected in DB Navigator tree. So, you can easily find next or previous table.

https://user-images.githubusercontent.com/51405061/112442730-37a57f80-8d5d-11eb-9a3f-ff123724d95f.mov

**Comment by bjkluft** [comment]
Thank you.
Not quite what I wanted but it did help.

**Comment by kseniiaguzeeva** [comment]
Please write, if you find it inconvenient.
