### ISSUE TITLE
Import CSV file do not work anymore 7.3.0+

### ISSUE THREAD

**Issue by Jrmy003** [dbeaver/dbeaver#11759]
Hello,

Since version 7.3.+, I'm not able to import CSV file anymore.
The max length for varchar fields was previously set to 50 or 1024, and is now auto detected (with random values)
and it seems everything was imported into varchar.

I'm working with big, dirty CSV files (50 columns, 10k+ raws, and malformed) the business gave to me, and I keep getting errors since I update from 7.3.0 to newer versions including the 21.0.0 one.

Data transfer failed during batch insert
(you can disable batch insert in order to skip particular rows).

Reason:
SQL Error [8115] [S0002]: Une erreur de dépassement arithmétique s'est produite lors de la conversion de expression en type de données int.

Data transfer failed during batch insert
(you can disable batch insert in order to skip particular rows).

Reason:
SQL Error [8152] [22001]: Les données de chaîne ou binaires seront tronquées.

Is there a was to get the old way to import csv (everything to varchar(1024)) without having to redefine mapping for each one of the 50 columns?

An option or something for dirty but working import, to me the import CSV functionality has not to be perfect, it has just to put temporary data quickly in database, and then we can extract, convert to import them properly.

**Comment by ShadelessFox** [comment]
Hello @Jrmy003,

You can specify minimal length for columns in the importer settings:
![image](https://user-images.githubusercontent.com/35821147/111453078-3ef8d780-8724-11eb-9f42-04b62afee269.png)

Does it solve your problem? Thanks.

**Comment by Jrmy003** [comment]
Hello @ShadelessFox

It partially fix the issue, I'm still having this one, while trying to convert, phone or bank account numbers to integer.

Data transfer failed during batch insert
(you can disable batch insert in order to skip particular rows).

Reason:
SQL Error [8115] [S0002]: Une erreur de dépassement arithmétique s'est produite lors de la conversion de expression en type de données int.

**Comment by ShadelessFox** [comment]
1. Are you expecting these account numbers to be converted into integers or not?
2. Can you provide sample data, so I can examine it?
3. Does changing value of <kbd>Columns samples count</kbd> affects the result or the error itself?

**Comment by uslss** [comment]
@Jrmy003 ,
please, uncheck highlighted option
![image](https://user-images.githubusercontent.com/31996417/111464465-dadd1000-8731-11eb-8e1a-d8088205bbec.png)

**Comment by Jrmy003** [comment]
@ShadelessFox

    Are you expecting these account numbers to be converted into integers or not?

No, everything in varchar is fine for me, I'm just looking to import a lot of data quickly into a temporary format does not matter as I am able to convert data into proper format using sql if I need it. And moreover I expect phone number, bank account numbers, even postal codes to be format as varchar not integer to avoid the loss of first 0 for exemple.
And having to manually check for target 

    Can you provide sample data, so I can examine it?
Quite hard I'm importing sensitive details of our customers

    Does changing value of Columns samples count affects the result or the error itself?
I just tried taking the whole file as example the mapping is the same as the previous one (with 1000 as Columns samples count)
And still got an error the error :

Data transfer failed during batch insert
(you can disable batch insert in order to skip particular rows).

Reason:
SQL Error [8115] [S0002]: Une erreur de dépassement arithmétique s'est produite lors de la conversion de expression en type de données int.

**Comment by ShadelessFox** [comment]
By the sample data I meant any data, I'm only interested in the format of it. Of course I'm not begging you to provide such sensitive data. You can replace digits, so original data would not be recognizable.

First of all, try to set <kbd>Columns samples count</kbd> to `0` this time, this should default all columns back to `varchar`.

**Comment by Jrmy003** [comment]
@uslss
Still got sql error, but it helped me finding the error data.

@ShadelessFox 
Can you provide sample data, so I can examine it?
You can reproduce the bug using the csv content attached as test.log file.

The integer size is set to 4

![image](https://user-images.githubusercontent.com/3603542/111473314-3526a280-872b-11eb-8a41-b0697b6528bb.png)

[test.log](https://github.com/dbeaver/dbeaver/files/6156641/test.log)

This columns are created
![image](https://user-images.githubusercontent.com/3603542/111474158-0b21b000-872c-11eb-99bb-7a8219fd70fb.png)

**Comment by ShadelessFox** [comment]
By using provided data and settings mentioned before, I don't have any problems and the created columns are fine:

![java_DlGP3bKP9b](https://user-images.githubusercontent.com/35821147/111475063-c43cb600-873d-11eb-8ac2-40440c116fa4.png)

The created columns:
![image](https://user-images.githubusercontent.com/35821147/111475088-cbfc5a80-873d-11eb-93d0-f1fc2e6a3694.png)

**Comment by Jrmy003** [comment]
> 
> 
> By the sample data I meant any data, I'm only interested in the format of it. Of course I'm not begging you to provide such sensitive data. You can replace digits, so original data would not be recognizable.
> 
> First of all, try to set Columns samples count to `0` this time, this should default all columns back to `varchar`.

@ShadelessFox Perfect that's all I needed (I'm able to import everything again as varchar by setting 0 in this field, and I can adjust the max size now :) )

And still remains the bug related to integer size detection, that do not matter to me. Should I close this ticket now as I can import CSV as full varchar?
Or keep it open until the integer detection is fixed?

**Comment by ShadelessFox** [comment]
Actually, we don't detect the maximum size for numeric columns.

I believe the `4` on your screenshot is the default length for `int` column in your database.

You can create a separate feature request, since this issue's title may be misleading for such small thing.

**Comment by Jrmy003** [comment]
Ok, thank you for the help!
Have a good day !

**Comment by ShadelessFox** [comment]
You are welcome!

**Comment by Jrmy003** [comment]
And btw I'm using SqlServer 2008 which is not supported any more by Microsoft, I'm not sure the issue related to integer exists on newer version of Sql Server. The bug maybe does not exist :/

**Comment by ShadelessFox** [comment]
It's still `4` by default using SQL Server 15 (2019) 🤔

As I said earlier, you can create a FR to support determining the length of numeric columns, too

**Comment by Jrmy003** [comment]
Ok then, will create a bug so, I got a concrete example.
