### ISSUE TITLE
Strange resizer button behavior

### ISSUE THREAD

**Issue by Wroud** [dbeaver/dbeaver#11762]
![image](https://user-images.githubusercontent.com/811729/111469145-67d69800-8737-11eb-98d7-b67590b603fd.png)

1. Maximize value panel
2. Hold mouse down on "right" arrow of resizer

Actual behavior: right after mouse down resizer jumps to right for some distance
Expected behavior: nothing happened

**Comment by ShadelessFox** [comment]
I think this is happening because the resizer supports dragging. But I doubt dragging should be active when user presses buttons.

![KMn0r37DUY](https://user-images.githubusercontent.com/35821147/111471081-905f9180-8739-11eb-8350-1bfee6a090d4.gif)

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce. Please give more details.

https://user-images.githubusercontent.com/51405061/113265056-5ca96d80-92dc-11eb-8b4c-d8a444469014.mp4

**Comment by kseniiaguzeeva** [comment]
Managed to reproduce.

https://user-images.githubusercontent.com/51405061/113265536-ed804900-92dc-11eb-836a-ca2a6f8a4e3f.mp4

**Comment by ShadelessFox** [comment]
This is the issue with the value panel (not related to gis)

**Comment by ShadelessFox** [comment]
Eclipse is trying to adjust the sash's width to a minimal width (which we can't change), causing it to "jump" several pixels away.

We can try to restrict dragging whilst sash is minimized, this will fix the issue.

**Comment by uslss** [comment]
obsolete (23.0.3)
