### ISSUE TITLE
Snowflake: set current schema the right way

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#11769]
We should do it properly, which is going to resolve various inconsistencies, such as not using bold font for the current schema in the navigator, etc. On top of that, we should respect [Snowflake's rules for escaping identifiers](https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html).

**Comment by flambchap** [comment]
Fixed the problems with setting the current database and the current schema. The issue regarding Swnoflake identifier rules will be transferred to a separate ticket.

**Comment by uslss** [comment]
verified
