### ISSUE TITLE
Show info message when database node is not deleted because of open editor

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#11760]
Currently, when we have a navigator node opened in some editor and we attempt to delete it via the navigator tree, we have to confirm deletion using the `save` button in the editor. This is somewhat confusing, so we should display a message box that informs the user about that.

**Comment by akilovich** [comment]
We already show the type of objects. Well, that's convinient.

**Comment by Matvey16** [comment]
Verified
