### ISSUE TITLE
FOREIGN KEY REFERENCES omits schema

### ISSUE THREAD

**Issue by jimbogithub** [dbeaver/dbeaver#11775]
#### System information: 
- Operating system (distribution) and version: macOS 11.1
- DBeaver version: 21.0.0.202103021012
- Java version: bundled 
- Additional extensions: n/a

#### Connection specification:
- Database name and version: PostgreSQL 12.6
- Driver name: PostgreSQL JDBC Driver 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
DDL generation is omitting the schema prefix on the target table, e.g.

CREATE TABLE abc.table1 (
id int
)
CREATE TABLE abc.table2 (
table1_id int
 CONSTRAINT fk_constraint_name FOREIGN KEY (table1_id) REFERENCES table1(id)
)

Should be

 CONSTRAINT fk_constraint_name FOREIGN KEY (table1_id) REFERENCES **abc**.table1(id)

**Comment by LonwoLonwo** [comment]
Hello @jimbogithub 
You can use "Generate SQL" -> "DDL" for you table. 
![2021-03-18 10_03_33-DBeaver Enterprise 21 0 1 - address](https://user-images.githubusercontent.com/45152336/111586493-f861b680-87d1-11eb-8262-79b55e4dfe0e.png)

This generator show fully qualified names as default, including for reference tables.
![2021-03-18 10_02_49-Generated SQL (dvdrental)](https://user-images.githubusercontent.com/45152336/111586513-ff88c480-87d1-11eb-891b-ec76ab4bc169.png)

**Comment by jimbogithub** [comment]
Thanks for your suggestion.  Unfortunately in the version I am running (noted at top of issue), the Table level DDL generation behaves the same as the Schema level DDL generation.  It does not include the schema prefix in the reference.

It would also be pretty inconvenient to generate the script one table at a time.

**Comment by LonwoLonwo** [comment]
Ok. Thanks for the bug report.

**Comment by LonwoLonwo** [comment]
![2021-04-30 00_43_39-emp - Persist Changes](https://user-images.githubusercontent.com/45152336/116623036-4e3b8980-a94e-11eb-93ee-47dcb0254b9e.png)

![2021-04-30 00_45_53-emp_2 - Persist Changes](https://user-images.githubusercontent.com/45152336/116623038-4ed42000-a94e-11eb-865c-a16dd4f88fa5.png)

![2021-04-30 00_47_03-DBeaver Enterprise 21 0 4 - emp_2](https://user-images.githubusercontent.com/45152336/116623040-4f6cb680-a94e-11eb-8bd4-8513c63c60bd.png)

Can't reproduce it in DBeaver 21.0.3
Can you clarify please those cases when the DDL is not correct?

**Comment by jimbogithub** [comment]
Try with this:

```
-- STEP 1: Create schema:

CREATE SCHEMA s_117755;

-- STEP2: Reconnect with currentSchema = s_117755

-- STEP 3: Create tables in default schema:

CREATE TABLE t_parent (
	id int4 NOT NULL,
	CONSTRAINT pkt_parent PRIMARY KEY (id)
);

CREATE TABLE t_child (
	id int4 NOT NULL,
	parent_id int4 NOT NULL,
	CONSTRAINT pkt_child PRIMARY KEY (id),
	CONSTRAINT fk_t_child_t_parent FOREIGN KEY (parent_id) REFERENCES t_parent(id)
);
```

Now the t_child DDL preview is not prefixed:

![image](https://user-images.githubusercontent.com/5095954/116637016-db1a2d80-a9b6-11eb-831a-111be7801be4.png)

The t_child generated DDL is prefixed:

![image](https://user-images.githubusercontent.com/5095954/116637053-f71dcf00-a9b6-11eb-894b-b6617f603c49.png)

Unfortunately the full schema generation is not working at all on this sample database:

![image](https://user-images.githubusercontent.com/5095954/116637132-30563f00-a9b7-11eb-8e0b-4a5e24025901.png)

However, for my real schema it does still work but generates without the schema prefix on FKs.  This is the one that matters for me, i.e. generating the full schema DDL.

So it looks like the issue may be related to whether the schema was explicitly specified when the FKs were created.

**Comment by jimbogithub** [comment]
Here's a redacted version of my real schema full DDL generation:

![image](https://user-images.githubusercontent.com/5095954/116637671-a4ddad80-a9b8-11eb-89c0-98c3683f3b6f.png)

**Comment by jimbogithub** [comment]
I can also duplicate the issue on a schema I know was created using explicit schema prefixes for the FKs but where the database connection used in DBeaver has that same schema set as the currentSchema (connection property).

**Comment by LonwoLonwo** [comment]
Found it. It depends on default_schema specified in the connection settings.

![2021-04-30 12_45_42-Window](https://user-images.githubusercontent.com/45152336/116680255-1f57fe80-a9b4-11eb-9f48-cb5416fa01d6.png)

![2021-04-30 12_46_00-Window](https://user-images.githubusercontent.com/45152336/116680261-1ff09500-a9b4-11eb-9bb0-9ebb4b9da561.png)

Without specified default schema
![2021-04-30 12_35_56-Window](https://user-images.githubusercontent.com/45152336/116680370-41ea1780-a9b4-11eb-868b-9b5e271303b4.png)

The problem is that we get part of foreign key expression from this request "SELECT pg_catalog.pg_get_constraintdef(fk_id)", which does not always return the full way to reference.

So workaround on this moment is - change default schema name. 
And we should think about other options.

**Comment by jimbogithub** [comment]
Thanks, that workaround is working for me.

**Comment by LonwoLonwo** [comment]
Ok. Now we stopped reading the value of the reference from database and generate it yourself. No longer will be binding to the default schema. Fixed for table and schema DDL tabs.

**Comment by uslss** [comment]
verified
