### ISSUE TITLE
All script text following an unclosed quotation mark should be highlighted as a string or object

### ISSUE THREAD

**Issue by jetzerb** [dbeaver/dbeaver#11773]
**Is your feature request related to a problem? Please describe.**
In a SQL editor, if you type in an opening quotation mark, either for a string literal (single quote) or a SQL object (double quote or square bracket), everything following that quote is highlighted as if it were _code_ rather than a string or object name until such time as the closing quote is entered.

**Describe the solution you'd like**
When an opening quote is typed, everything between that and the next closing quote (or the end of the script, if none exists) should be highlighted appropriately as either a string or object name.

**Describe alternatives you've considered**
This isn't normally problematic because the closing quotes can be auto-generated at the time the opening quote is entered via preferences.
![image](https://user-images.githubusercontent.com/36859020/111531598-bcc3df80-8732-11eb-834d-b02168b1b742.png)
I also have a strict policy of not including carriage returns or linefeeds in my object names 😃

**Additional context**
#### String Literal Examples
See comment thread on #11364 for background information.
This:
![image](https://user-images.githubusercontent.com/36859020/111532591-d285d480-8733-11eb-9a14-c26c55c40765.png)
_should_ look like this instead:
![image](https://user-images.githubusercontent.com/36859020/111532500-b84bf680-8733-11eb-9339-cd73691ada73.png)
(achieved by adding a closing quote one line below the snipped screenshot)

#### Object Names
The current behavior is a bit more complicated for object names.  Everything following an unclosed quote on a line will be highlighted as code.
![image](https://user-images.githubusercontent.com/36859020/111533852-41176200-8735-11eb-9ac5-f04931b48fae.png)
But after hitting `enter`, the text following the quote is highlighted as if it were an object name, though nothing on the following line is:
![image](https://user-images.githubusercontent.com/36859020/111534043-85a2fd80-8735-11eb-8125-f14e67b24731.png)
Once the closing quote is entered, the entire string is highlighted appropriately:
![image](https://user-images.githubusercontent.com/36859020/111534484-082bbd00-8736-11eb-9a97-921533d1fc48.png)

Same behavior with square brackets:
![image](https://user-images.githubusercontent.com/36859020/111534662-3dd0a600-8736-11eb-88d7-a7f233efb841.png)
![image](https://user-images.githubusercontent.com/36859020/111534731-517c0c80-8736-11eb-9d90-ec4419af64ba.png)

**Comment by ShadelessFox** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/35821147/112014723-38130000-8b3c-11eb-8f4f-8dda6cd4d35f.png)

**Comment by jetzerb** [comment]
Your change looks correct for string literals.

But note how line 2 has an opening quote (`[`) which is never closed.  All the following lines of code should be highlighted as if they are part of that object name.  Here are some screenshots from SSMS:

First, exactly your text.  Note how everything following the opening square bracket through the end of the script is assumed to be part of the object name.  Absurd, yes, but that's the way the server parses the query, and it provides a visual cue that the closing bracket was forgotten:
![image](https://user-images.githubusercontent.com/36859020/112035532-a391a900-8b0d-11eb-9152-4acdc4cfcef7.png)

Then, after the closing bracket is added but without the closing double-quote.  Now everything between the closing bracket and opening double-quote is correctly highlighted as code, while everything after the opening quote is assumed to be part of the object name.  Again, the highlighting reflects the way the server parses the query, and the lack of color on subsequent lines clues you in to the fact that something is wrong.
![image](https://user-images.githubusercontent.com/36859020/112036100-40ecdd00-8b0e-11eb-8da8-bb668258bb05.png)

After adding the closing double quote, everything between that and the opening single quote is highlighted as code, while everything following the opening single quote is correctly highlighted as a string literal.
![image](https://user-images.githubusercontent.com/36859020/112036327-827d8800-8b0e-11eb-849e-a5d7c7a4b682.png)

For reference:
- Queries entered within Visual Studio follow the same rules as SSMS.
- Microsoft's Electron-based products (Azure Data Studio, Visual Studio Code) follow the same rules as SSMS for string literals and object names _that are double-quoted_.  For objects quoted with square brackets, they highlight all following text as code, even on the same line as the opening bracket. That's almost certainly an issue/defect with the Language Server though, rather than anything specific to those products.

**Comment by ShadelessFox** [comment]
Unfortunately, I had to leave bracket and double quotes as-is.

First of all, they are the identifier quotations marks, so **they can't span across multiple lines**, and our lexical rules can't do something like "try to find your closing sibling on the current line, otherwise span towards the end of file and commit that". What if an opening quote will match closing quote on the other line?

I'd really like to implement this, but I'm not sure what would be the right way.

**Comment by ShadelessFox** [comment]
We decided to make them multiline too, despite the point I mentioned before. Maybe in some databases they can.

**Comment by jetzerb** [comment]
Indeed, MSSQL allows this:
![image](https://user-images.githubusercontent.com/36859020/112147045-40a21f80-8baa-11eb-8d39-b23b5197f703.png)

**Comment by uslss** [comment]
verified
