### ISSUE TITLE
Unable to create new table and new columns MariaDB

### ISSUE THREAD

**Issue by rotorboy** [dbeaver/dbeaver#11777]
#### System information: 
- Operating system (distribution) and version - macOS 10.14.6
- DBeaver version -  21.0.0.202103021012
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name - defualt
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

after selecting "create new table", unable to add columns to it, or save the table without columns

#### Steps to reproduce, if exist:

select "create table" and then try to add columns, or save table without column.

here is error when trying to create column:

class org.jkiss.dbeaver.tasks.ui.DataSourceToolsContributor$DataSourceEditorInput cannot be cast to class org.jkiss.dbeaver.ui.editors.IDatabaseEditorInput (org.jkiss.dbeaver.tasks.ui.DataSourceToolsContributor$DataSourceEditorInput is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @69759d04; org.jkiss.dbeaver.ui.editors.IDatabaseEditorInput is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @3d2eb7fa)

**Comment by uslss** [comment]
cannot reproduce it. Could you check it against 21.0.1?

**Comment by rotorboy** [comment]
21.0.1 seems to have fixed the issue. Thanks
