### ISSUE TITLE
[PostgreSQL] Serial types are broken in non-catalog schemas.

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#11779]
DBeaver 21.0.0

Serial types are continued to be read as serial for columns, but is not lacking in the list of data types to choose when creating new column. 
What is very uncomfortable. 
Need to return them to the list

![2021-03-18 12_36_28-DBeaver Enterprise 21 0 1 - aaa](https://user-images.githubusercontent.com/45152336/111604752-ae370000-87e6-11eb-8f13-417276970d58.png)

**Comment by LonwoLonwo** [comment]
Fixed in 21.0.2
Data type alias are again in drop down list in case of column create.

**Comment by kseniiaguzeeva** [comment]
verified
