### ISSUE TITLE
Cant scroll schema list to bottom

### ISSUE THREAD

**Issue by robert-niestroj** [dbeaver/dbeaver#11785]
#### System information: 
- Windows 10 20H2
- DBeaver 21

#### Connection specification:
- Postgres 12

#### Describe the problem you're observing:
![obraz](https://user-images.githubusercontent.com/9776384/111623483-bc871b00-87ea-11eb-8713-ab7b56af241b.png)

I have a lot of schemas in my DB. I Have the Windows Taskbar on top of the screen. I cant scroll the list of schemas down. I don't see that menu item with the arrow down. If the Windows Taskbar is at the bottom it works. 

#### Steps to reproduce, if exist:

Have so much schemas so that the don't fit on the screen. Put your Windows Taskbar on the top of the screen. Click the button to change the schema. You expect to see the arrow down button.

**Comment by uslss** [comment]
thanks for the report

**Comment by Matvey16** [comment]
Thank you for the report. Please specify when are you trying to change schema? While working in SQL Editor, correct?

**Comment by Matvey16** [comment]
Reproduced the issue. The problem is in the UI, where it is possible for the schema list to go beyond the window bottom border.

**Comment by Matvey16** [comment]
This list is an MS Windows native component. If you don't want to change your taskbar position, you can click on a schema to see a list in a separate window.

https://user-images.githubusercontent.com/82543000/118779785-10b68600-b894-11eb-816c-160f6999ddc3.mp4
