### ISSUE TITLE
disable/delay tooltips

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#11784]
Tooltips appear more or less immediatelly when hovering -- despite being most of the time either without adding anything (a tooltip with the table name when hovering over the table name), or are a hindrance (large tooltips with the complete query hiding parts a result view).

Additionally, I am using x2org to work remotely -- starting DBeaver over x2org and then having another window overlaying DBeaver, tooltips "puncture" the window above it.
![Screenshot_20210318_121743](https://user-images.githubusercontent.com/50481865/111618563-d02f8300-87e4-11eb-92f1-17bbb211b217.png)
While this is not a DBeaver issue, the uncontrollable tooltips exacerbate the problem.

With Eclipse itself I do not observe the issue.

I would prefer to have those tooltips delayed for a configurable amount of time, so that one will be able to indicate ones intention to see a tooltip, instead of being presented with them just because the mouse pointer happens to be at a sensitive position.
Alternatively I'd like to be able to either completely disable those tooltips.

**Comment by uslss** [comment]
thanks for the suggestion
duplicates #11483
