### ISSUE TITLE
Support for importing/including sql scripts in other sql scripts

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#11788]
**Is your feature request related to a problem? Please describe.**
I have a number of .sql scripts, and would like to create a single file that can be run to execute them all in the order they appear in the main file. 

**Describe the solution you'd like**
An ability to import/include external sql files using a filepath, which runs each script in the order it appears in the list.
e.g.
@script1.sql
@script2.sql
@script3.sql
Would cause script1 to run, then script2 and finally script 3.

**Describe alternatives you've considered**
I haven't been able to think of any alternatives, and have looked online, but been unable to find workarounds for it. The only approach I can see is to run each file individually.

**Additional context**
I'm using a postgresql database.

**Comment by ShadelessFox** [comment]
Hello @GDownAdviseInc,

That's an interesting feature request.

As a more general workaround I can suggest you to use <kbd>SQL Script</kbd> task - you can add multiple SQL files in it (and, optionally, multiple connections), and they will execute synchronously, one after the other.

**Comment by ghost** [comment]
Hi @ShadelessFox thanks for getting back so quickly! It might be related to me being new to sql stuff, and instead coming from a programming place, so probably trying to do the wrong things in the wrong ways. If I'm completely out in left field, please feel free to close and ignore, just couldn't see anywhere else to do it.

I can't find the SQL Script task I'm afraid. I've also tried searching online to see where it might be, but not having much luck. Please could you point me in the right direction?

**Comment by ShadelessFox** [comment]
You can find more information about tasks here: https://github.com/dbeaver/dbeaver/wiki/Task-Management

The <kbd>SQL Script</kbd> task can be found among other tasks, as shown in the article mentioned above:

![image](https://user-images.githubusercontent.com/35821147/111649847-cbcf8e00-8815-11eb-8be9-e9aa4a0226fa.png)
![image](https://user-images.githubusercontent.com/35821147/111649749-b8bcbe00-8815-11eb-92ec-1f64ac6d7dcb.png)

**Comment by ghost** [comment]
Fantastic! That is perfect - thank you.

**Comment by ShadelessFox** [comment]
You are welcome!

I will close this issue for now. If you have any questions left - feel free to ask them here.
