### ISSUE TITLE
"Open Database Object" omits Foreign Tables

### ISSUE THREAD

**Issue by fjf2002** [dbeaver/dbeaver#11783]
**Is your feature request related to a problem? Please describe.**
The Dialog "Open Database Object" omits Foreign Tables - at least with PostgreSQL.

**Describe the solution you'd like**
The Dialog "Open Database Object" should also take Foreign Tables into consideration.

**Describe alternatives you've considered**
None.

**Additional context**
Tested on a PostgreSQL database.

**Comment by fjf2002** [comment]
By the way, NOT listing foreign tables is inconsistent in my opinion, because in the DB Navigator, foreign tables ARE listed as tables.

Thank you for considering my issue.

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.0.5.
Now "Open Database Object" returns Foreign Tables.

**Comment by uslss** [comment]
verified
