### ISSUE TITLE
Geometries in GeoPackage files

### ISSUE THREAD

**Issue by heidivanparys** [dbeaver/dbeaver#11793]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows 10
- DBeaver version: 21.0.0
- Additional extensions: -

#### Connection specification:
- Database name and version: GeoPackage, v1.2
- Driver name: org.xerial:sqlite-jdbc:sqlite-jdbc-3.34.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no (as far as I know...)

#### Describe the problem you're observing:

I want to display the spatial data in a GeoPackage file on the map, but nothing is shown.

#### Steps to reproduce, if exist:

1. Connect to the GeoPackage file nl.gpkg that is in the [zip file](https://github.com/dbeaver/dbeaver/files/5070852/nl.zip) that was uploaded by @rduivenvoorde in #9526.
2. Open table provinces.
3. Go to the Data tab, open the Grid view
4. Right-click on the geom column, go to View/Format, Set "geom" format: Geometry cannot be chosen (which should be possible according to https://github.com/dbeaver/dbeaver/wiki/Working-with-Spatial-GIS-data#viewing-string-or-binary-data-from-any-database-on-a-map)
![image](https://user-images.githubusercontent.com/11427611/111774640-07b73180-88b0-11eb-808b-dc0d1a9d3d7c.png)
5. Open the Spatial view: nothing is shown. 
![image](https://user-images.githubusercontent.com/11427611/111774603-fec66000-88af-11eb-9e14-f1ee2afd6920.png)
6. Note: when clicking on "Open in Browser", the geometries are shown: 
![image](https://user-images.githubusercontent.com/11427611/111774566-ee15ea00-88af-11eb-8e87-66cb590a02fa.png)

#### Include any warning/errors/backtraces from the logs
No warning or errors in the logs.

**Comment by ShadelessFox** [comment]
Hello @heidivanparys,

Unfortunately, I cannot reproduce your issue:

![image](https://user-images.githubusercontent.com/35821147/111780281-3c36e780-88c8-11eb-9a93-79713629e70a.png)

Have you tried opening the <kbd>Value</kbd> panel on the right in the <kbd>Grid</kbd> view? You can select individual geometry values to be shown in this panel. Empty map may be caused by invalid values, as described in #11021.

Also, can you please provide [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

Thanks.

**Comment by heidivanparys** [comment]
@ShadelessFox 

Value panel (Text):

![image](https://user-images.githubusercontent.com/11427611/111791271-5ae6af80-88c3-11eb-8b18-3a9b6e075ee7.png)

Value panel (Map): empty canvas (I tried every geometry in provinces and also some geometries in places and rivers, without luck):

![image](https://user-images.githubusercontent.com/11427611/111791377-6e921600-88c3-11eb-8e36-e2c35ccf3544.png)

Bonusinfo: I also cannot see any of the base maps, not in the Spatial view and not in the Map when I select a specific value.

I deleted my workspace in %APPDATA%\DBeaverData\ and tried again, I have the same issue.

Log file:
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/6171679/dbeaver-debug.log)

**Comment by ShadelessFox** [comment]
My last guess is that you may have some some problems with OpenStreetMap tiles. Can you try changing it to something else?

![image](https://user-images.githubusercontent.com/35821147/111795784-9049c800-88d8-11eb-8a50-a6e91257b386.png)

The other guess is that the Internet Explorer is not accessible (which we're using to display Leaflet). Ask your sysadmin.

**Comment by heidivanparys** [comment]
@ShadelessFox This issue is fixed in the 21.0.1 release, there the map viewer shows the geometries and the background map as expected.

Bonus info: I didn't have this issue at all in the 21.0.0 release on my Mac. Tested from the same location (but without VPN, as opposed to on my work computer).
