### ISSUE TITLE
'Disable referential integrity...' checkbox must always be disabled when gray

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#11795]
Currently, we remember the last chosen option, and it may result in situations like this:

![Screenshot 2021-03-19 171757](https://user-images.githubusercontent.com/26031301/111794237-136a1e80-88d7-11eb-91e7-3f0beb9e7e68.png)

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
