### ISSUE TITLE
DBeaver Version 7.3.5.202102141704 Error executing tool mysql Dump database on macOS 11.1

### ISSUE THREAD

**Issue by aa-dxp168** [dbeaver/dbeaver#11794]
#### System information: 
- Operating system (distribution) and version: macOS 11.1
- DBeaver version: 7.3.5.202102141704
- Additional extensions

#### Connection specification:
- Database name and version: MySQL 8.0.21
- Driver name: MySQL 8.0.21
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:
<img width="449" alt="Screen Shot 2021-03-19 at 10 14 16 AM" src="https://user-images.githubusercontent.com/29785130/111793803-ffed9200-889b-11eb-8a1f-3945fd147a69.png">

#### Steps to reproduce, if exist:
<img width="403" alt="Screen Shot 2021-03-19 at 10 14 55 AM" src="https://user-images.githubusercontent.com/29785130/111793822-0419af80-889c-11eb-92aa-a795346d5e4d.png">

**Comment by ShadelessFox** [comment]
Hello @aa-dxp168,

Please provide the [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files).

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it.
