### ISSUE TITLE
Terminate DBeaver gracefully after starting updater

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#11796]
We've implemented automatic updates in #6558, but the termination routine may lead to the workbench corruption.

**Comment by ShadelessFox** [comment]
Please make sure that installer asks user to close all unsaved data.

**Comment by kseniiaguzeeva** [comment]
The installer doesn't ask it and changes are not saved (tested on Mac)

**Comment by kseniiaguzeeva** [comment]
veirified on Mac and Win10. Separate ticket is created https://github.com/dbeaver/dbeaver/issues/11859
