### ISSUE TITLE
Virtual foreign key cannot be deleted

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11803]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.1

#### Steps to reproduce, if exist:
1. Create a virtual foreign key
2. Delete it

Expected: the virtual foreign key and the virtual reference are deleted
Actual result: virtual reference remains and the connection exist in Reference panel and ERD.

**Comment by kseniiaguzeeva** [comment]
Cannot be reproduced anymore

**Comment by hrnkilic** [comment]
Version 22.2.0 resolves this issue.
