### ISSUE TITLE
DB2: extra embedded routines

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#11801]
DB2 LUW driver provides a very small number of embedded functions for syntax highlight.
We should extend it (with constants or by reading from SYSCAT.ROUTINES)

**Comment by serge-rider** [comment]
DB2 functions: https://www.ibm.com/support/producthub/db2/docs/content/SSEPGG_11.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0024845.html?pos=2

**Comment by uslss** [comment]
verified
