### ISSUE TITLE
Values are truncated during the export from csv to non-existing table

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#11808]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.0.1 EA

#### Connection specification:
- Database name and version Sybase
- Driver name jconnect

#### Steps to reproduce, if exist:
1. Start import to new table from CSV 
[actor_202103181130.csv.txt](https://github.com/dbeaver/dbeaver/files/6177021/actor_202103181130.csv.txt)
2. Check preview data dialog - data is fully shown
![image](https://user-images.githubusercontent.com/31996417/111897760-c8651e00-8a32-11eb-80f8-4fce2ee1dbbe.png)
![image](https://user-images.githubusercontent.com/31996417/111897786-f0ed1800-8a32-11eb-8077-9591204a9d9a.png)

3. Start data import and check created table
![image](https://user-images.githubusercontent.com/31996417/111897847-53deaf00-8a33-11eb-89a4-65a0edb3e4ac.png)

**Comment by LonwoLonwo** [comment]
That's because

```sql
CREATE TABLE textvarchar (
col1 varchar
)
```
The varchar type without modifiers in Sybase turn into varchar(1). So we need to set default value for new varchar columns.

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.2.4

**Comment by Matvey16** [comment]
Verified
