### ISSUE TITLE
Connection view>Hide folders does not show triggers

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11809]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.2 EA

#### Connection specification:
- Database name and version SQL Server

#### Steps to reproduce, if exist:
1. Set Connection view>Hide folders in the context menu
2. Expand the connection DB Navigator tree 

**Expected**: all object types are displayed in DB Navigator
**Actual result**: triggers are not displayed neither in DB Navigator nor in schema metadata editor

**Comment by akilovich** [comment]
Sequences, synonyms, and data types aren't shown as well.

**Comment by flambchap** [comment]
This behavior is expected since triggers 'live' inside tables.
