### ISSUE TITLE
NPE appears in case of connection disconnect while ERD is loading

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#11806]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.0.1 EA

#### Steps to reproduce, if exist:
1. Open some ERD that loads quite long.
2. Disconnect from DB

![2021-03-21_10h10_41](https://user-images.githubusercontent.com/31996417/111896988-6bffff80-8a2e-11eb-860e-0f02dc68b32f.gif)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/6176996/dbeaver-debug.log)

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by uslss** [comment]
verified
