### ISSUE TITLE
Unable to edit records in Data Editor

### ISSUE THREAD

**Issue by rotorboy** [dbeaver/dbeaver#11811]
#### System information: 
- Operating system (distribution) and version - MacOS 10.14.6
- DBeaver version - 21.0.0
- Additional extensions 

#### Connection specification:
- Database name and version 
- Driver name - Default MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:

In addition to being unable to use UI to create a DB table, Using DBeaver 21.0.0 connecting to MariaDB 10.3.23 on AWS RDS,  query-generated resultsets are unable to be edited in the resultset data editor. The error "Column foo is read-only: No corresponding table column"

**Comment by uslss** [comment]
Hi, @rotorboy ,
unfortunately cannot reproduce it.
Could you provide table DDL? It will be helpful for issue reproducing

**Comment by rotorboy** [comment]
21.0.1 seems to have fixed the issue. Thanks
