### ISSUE TITLE
Unable to download zip file: https://dbeaver.io/files/dbeaver-ce-latest-win32.win32.x86_64.zip

### ISSUE THREAD

**Issue by meriturva** [dbeaver/dbeaver#11817]
Just click on:

https://dbeaver.io/files/dbeaver-ce-latest-win32.win32.x86_64.zip

from:
https://dbeaver.io/download/

error:

```
<Error>
<Code>AccessDenied</Code>
<BucketName>dbeaver</BucketName>
<RequestId>tx00000000</RequestId>
<HostId>zzzz</HostId>
</Error>
```

**Comment by uslss** [comment]
unfortunately, cannot reproduce it. 
What browser do you use?

**Comment by meriturva** [comment]
Is not related to the browser but file permission.

Tested on two different networks and browsers.

Also a simple wget from an external vps doesn't work.

**Comment by meriturva** [comment]
test also file: https://download.dbeaver.com/community/21.0.1/dbeaver-ce-21.0.1-win32.win32.x86_64.zip

**Comment by meriturva** [comment]
Today works!
