### ISSUE TITLE
Edit procedure on GreenPlum

### ISSUE THREAD

**Issue by cryptonome** [dbeaver/dbeaver#1181]
Serge, 

Greenplum do not have pg_get_functiondef, and in we're not able to edit stored procedures with DBeaver.

A solution should be as stated on https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-users/xHafRmKNW78

From a GUI tool, get the function definition using pgAdmin III or Aginity Workbench for Pivotal Greenplum, which are the two main GUI tools for working with Greenplum.

From the command line, you can use psql, but as already said it won't give the full CREATE FUNCTION statement:
\a
\o <function name>.sql
\df+ <schema name>.<function name>
\o

To get the full CREATE FUNCTION statement from the command line you can use pg_dump and pg_restore:

- create a dump file containing all the objects of the schema containing your function(s):
pg_dump -h <host name> -U <user name> -n <schema name> -Fc -s <database name> > dump.dmp

- search the function definition including its argument list within the dump file:
pg_restore -l dump.dmp | grep <function name>

- extract the function definition from the dump file:
pg_restore -P '<function name>(arguments list)' dump.dmp > <function name>.sql

I do not know it should be interested to include on DBeaver, but sure should be and enhancer.
Many thanks

**Comment by serge-rider** [comment]
I think that making database dump just to get a procedure body is a bit too heavy solution. 
- Sometimes there is no local PostgreSQL client (psql, pg_dump) installed
- Export may take hours in case of big database. 
There should be some other way. As I understood they have a plan to merge with recent PostgreSQL codebase changes - this will give access to pg_get_functiondef.

**Comment by cryptonome** [comment]
Greenplum 4.3 do not support it and will not support in the near feature. A solution should be as in PGadminIII. It's has two method to retrieve the procedures one is for old versions and one for new ones. ( from pgFunctions.cpp) 
	if (obj->GetConnection()->GetIsGreenplum())
	{
		// the Open Source version of Greenplum already has the pg_get_function_result() function,
		// however the 4.3 stable release does not have this function
		functions = obj->GetDatabase()->ExecuteSet(
		                       wxT("SELECT pr.oid, pr.xmin, pr.*, format_type(TYP.oid, NULL) AS typname, typns.nspname AS typnsp, lanname, ") +
		                       argNamesCol  + argDefsCol + proConfigCol + proType +
		                       wxT("       pg_get_userbyid(proowner) as funcowner, description") + seclab + wxT("\n")
		                       wxT("  FROM pg_proc pr\n")
		                       wxT("  JOIN pg_type typ ON typ.oid=prorettype\n")
		                       wxT("  JOIN pg_namespace typns ON typns.oid=typ.typnamespace\n")
		                       wxT("  JOIN pg_language lng ON lng.oid=prolang\n")
		                       wxT("  LEFT OUTER JOIN pg_description des ON (des.objoid=pr.oid AND des.classoid='pg_proc'::regclass)\n")
		                       + restriction +
		                       wxT(" ORDER BY proname"));
	}
	else
	{
		// new code for !Greenplum
		functions = obj->GetDatabase()->ExecuteSet(
		                       wxT("SELECT pr.oid, pr.xmin, pr.*, pg_get_function_result(pr.oid) AS typname, typns.nspname AS typnsp, lanname, ") +
		                       argNamesCol  + argDefsCol + proConfigCol + proType +
		                       wxT("       pg_get_userbyid(proowner) as funcowner, description") + seclab + wxT("\n")
		                       wxT("  FROM pg_proc pr\n")
		                       wxT("  JOIN pg_type typ ON typ.oid=prorettype\n")
		                       wxT("  JOIN pg_namespace typns ON typns.oid=typ.typnamespace\n")
		                       wxT("  JOIN pg_language lng ON lng.oid=prolang\n")
		                       wxT("  LEFT OUTER JOIN pg_description des ON (des.objoid=pr.oid AND des.classoid='pg_proc'::regclass)\n")
		                       + restriction +
		                       wxT(" ORDER BY proname"));
	}

Best regards.

**Comment by serge-rider** [comment]
We have improved Greenplum support in last DBeaver versions.
Could you test how it works?

**Comment by serge-rider** [comment]
Eventually we'll add client-side function header generation in 5.2.4
