### ISSUE TITLE
Text in SQL editor is always selected from the start

### ISSUE THREAD

**Issue by F-l-a-m** [dbeaver/dbeaver#11816]
Is it some kind of toggle I've accidentally turned on?
The text in SQL editor is always selected from the start when I try to select anything using the mouse.
I have the same behavior as Ctrl+Shift+Home with any mouse movement.

**Comment by uslss** [comment]
Unfortunately, cannot reproduce it.
Could you provide a video of the issue?
What OS and DBeaver version do you use?

**Comment by F-l-a-m** [comment]
Kubuntu 16.04 (But It was not a problem for a long time) + DBeaver 21.0.1
The selection behavior can be reproduced by clicking somewhere in the middle of the text and using the Ctrl+Shift+Home shortcut. But using the shortcut - It's the desired effect. But in my case, I have the same effect just trying to select any amount of text using the mouse.

**Comment by uslss** [comment]
duplicates #10914

**Comment by F-l-a-m** [comment]
Issue still exists in 21.1.0

**Comment by toffick** [comment]
Faced with the same bug
Ubuntu 16.04
DBeaver 21.0.1
