### ISSUE TITLE
Pan in ER Diagram View

### ISSUE THREAD

**Issue by Pshemas** [dbeaver/dbeaver#11810]
I'm trying out Dbeaver and I can't find a pretty basic feature - panning (moving up/down, sideways) in ER diagram view. While zooming works nicely (ctrl+mousewheel) it's pretty much a major pita if you can't move the view with mouse action and you're forced to use bottom and sidebar.
Something like you have in almost any graphic app, for example space + left mouseclick and move to get the pan action would be very welcome.

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea, we should think about it.

**Comment by uslss** [comment]
already implemented
![image](https://user-images.githubusercontent.com/31996417/140042471-ccba82e1-a333-4ccc-8dde-d2001174d41c.png)
