### ISSUE TITLE
DB2: support begin/end blocks rules

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#11829]
We probably need to add more sophisticated rule for block parse. Currently we use just block begin/end literals which don't respect context.

**Comment by ShadelessFox** [comment]
Fixed:

![java_brSLGMGpS7](https://user-images.githubusercontent.com/35821147/117817776-9cb32700-b270-11eb-8aa2-700d7d1f6b5e.png)

Note that regular `BEGIN` and `END` keywords are colored using different color unlike `ROW BEGIN` and `ROW END`.

This example uses different highlighting color for the sake of visualization.

Which means that:
1. `ROW BEGIN` must not be treated as a valid block beginning
2. `BEGIN ... END` blocks are supported back again now (and folding should work with them)

Example query:
```sql
BEGIN
  CREATE TABLE policy_info
  (
   policy_id    CHAR(4) NOT NULL,
   coverage     INT NOT NULL,
   sys_start    TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW BEGIN,
   sys_end      TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW END,
   ts_id        TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS TRANSACTION START ID,
   PERIOD SYSTEM_TIME (sys_start, sys_end)
  ) IN policy_space;
END
```

**Comment by uslss** [comment]
Row begin/end are highlighted with the same color as BEGIN...END
![image](https://user-images.githubusercontent.com/31996417/117945348-e9513d80-b316-11eb-9e87-5d576c713066.png)

**Comment by uslss** [comment]
verified
