### ISSUE TITLE
DBeaver losts current schema.

### ISSUE THREAD

**Issue by vmalyutin** [dbeaver/dbeaver#11828]
System information: 
- Operating system: Win 10
- DBeaver version: Version 21.0.1.202103211229, 
- Additional extensions: No extensions
- PGbouncer: 1.12.0

Connection specification:
- Database name and version: PostgreSQL 10.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
- Driver name: PostgreSQL JDBC Driver 42.2.5
- Do you use tunnels or proxies: No, I don't 

Describe the problem you're observing:
There are multiples schemas in a DB. I connect to a specific scheme using a dropbox above sql query editor. It works perfect, but after a couple of executions an error appears - "SQL Error [42P01]: ERROR: relation "my_table" does not exist". And I see "public" in the dropbox. select current_scheme() returns "public" also.

Steps to reproduce, if exist: Connect to DB via pgbouncer, execute a query several times. At some point you will get an error.

#### Include any warning/errors/backtraces from the logs
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Mar 23 09:20:43 NOVT 2021
SQL Error [42P01]: ERROR: relation "my_table" does not exist
  Position: 16

**Comment by kseniiaguzeeva** [comment]
Please check whether **Open separate connection for each editor** option is enabled.
![Screenshot 2021-03-25 at 17 51 53](https://user-images.githubusercontent.com/51405061/112493038-dac4bc00-8d92-11eb-824a-798497fb9c48.png)

If it is disabled, a connection uses one schema for all SQL Editors and opens SQL Editor for a default schema.

**Comment by vmalyutin** [comment]
Kseniia, yes, it is enabled.
One note. When I execute my query with "set search_path"  it works fine always. But without that it fails as I shown above.

**Comment by kseniiaguzeeva** [comment]
Could you please send queries from Query manager (Window>Show view>Query manager). We should understand what DBeaver executes when you change a schema. Enable all query types in it filters.
![dbeaver_eEHMvXvuUj](https://user-images.githubusercontent.com/51405061/113268626-3ede0780-92e0-11eb-9703-305b359134d4.png)

**Comment by vmalyutin** [comment]
Kseniia, nothing specific. Just "**set search_path**" and then "**show search_path**". After some time (30 seconds or 1 minute) scheme is lost
![set scheme](https://user-images.githubusercontent.com/9856340/113400750-804be100-93cc-11eb-988e-ad8ea63841f1.png)
![scheme is here](https://user-images.githubusercontent.com/9856340/113400759-8641c200-93cc-11eb-8d5d-44f70bcf5295.png)
![no scheme](https://user-images.githubusercontent.com/9856340/113400766-8a6ddf80-93cc-11eb-83e6-7703d4e2db1c.png)

**Comment by flambchap** [comment]
Hi @vmalyutin. I want to ask a couple of questions.

- Is it still reproducible (against the latest version)?
- If it is, do you observe the same issue when connecting to Postgres without PgBouncer?

Thanks.

**Comment by uslss** [comment]
there is no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
