### ISSUE TITLE
Data changes are not applied after pressing persist data changes when we close DBeaver

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11834]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.0.1

#### Steps to reproduce, if exist:
1. Open a table in the RersultSet
2. Change a cell value (or add/delete a row)
3. Press the cross to close DBeaver
4. Press Yes in _persist data changes_ pop up to apply changes
5. Open DBeaver and open the table to check changes

**Expected**: the changes are applied
**Actual result**: the changes are not applied

Note: The issue can be reproduced in manual and auto-commit mode

**Comment by serge-rider** [comment]
1.  Changes weren't saved during shutdown process because all monitors were in state "canceled"
2. Transaction commit was forced BEFORE data save

Now fixed.

**Comment by kseniiaguzeeva** [comment]
verified
