### ISSUE TITLE
Dbeaver won't open anymore

### ISSUE THREAD

**Issue by iSpeeX** [dbeaver/dbeaver#11835]
Hello,

I was using Dbeaver for a couple weeks now without any problems. Yesterday I shutdown my laptop and this morning tried to launch Dbeaver as usual and it's not working anymore.
It says that an error has occurs and show the path to a log file.
What's in the log file is kinda mysterious (and it's always the same) : 
!SESSION !SESSION !SESSION !SESSION !SESSION !SESSION !SESSION !SESSION !SESSION 

That's it ! I tried to reboot my computer but still, not working....

#### System information: 
- W10
- DBeaver version : 21.0.1
- Java version : 1.8

Can anyone help me ? Stuck here...

Best regards.

**Comment by uslss** [comment]
Hi @iSpeeX ,
can you try to [reset workspace](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)?
