### ISSUE TITLE
Could DBeaver please stay focused???

### ISSUE THREAD

**Issue by mnott** [dbeaver/dbeaver#11839]
**Is your feature request related to a problem? Please describe.**
When using the session manager, selecting a PID and activating auto-refresh, DBeaver loses the focus on the selected line.

This is frustrating, as in the SQL pane below it would nicely show which statement is currently run, and would allow for observing at a distance what a current session is currently at. Since it loses focus on refresh, that SQL pane gets emptied on refresh, and you've to click again on the pid.

**Describe the solution you'd like**

With a PID selected, on refresh, keep focus on that PID as long as that PID is there.

**Describe alternatives you've considered**

None.

**Additional context**
![Screen Shot 2021-03-23 at 10 10 36](https://user-images.githubusercontent.com/2168313/112130594-ecf2fe80-8bc8-11eb-9dd9-00641057ecb7.png)

**Comment by p91paul** [comment]
Automatically reselect the current row after a refresh would indeed be nice. It probably requires a per-database support. On Oracle, for example, you would need SID+serial# (+ instanceid when in RAC mode) to identify the row.

**Comment by Matvey16** [comment]
Verified

**Comment by flambchap** [comment]
This fix breaks in the situation when querying sessions takes a somewhat significant time and we change the selection after the query has started.

**Comment by flambchap** [comment]
Fixed once again.

**Comment by Matvey16** [comment]
Verified
