### ISSUE TITLE
Export E/R diagram from CLI

### ISSUE THREAD

**Issue by literakl** [dbeaver/dbeaver#11831]
**Is your feature request related to a problem? Please describe.**

I am able to use Dbeaver GUI and generate E/R diagrams. That is cool. But I would love to be able to generate the same output from CLI in a headless environment. This would be a cool pipeline in Gitlab to document the current state.

**Describe the solution you'd like**
Project has been configured and stored at correct location. Run a request from command line. It will store diagrams in the specified location. No GUI will be started. Program will exit after completion.

**Describe alternatives you've considered**
Implement HTML/PlantUML output. Buy a commercial tool.

**Additional context**
Thanks for a consideration.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by LonwoLonwo** [comment]
Closed as a duplicate of https://github.com/dbeaver/dbeaver/issues/6215
