### ISSUE TITLE
Errors getting count on SQL server with queries that have repeated columns (and SQLite)

### ISSUE THREAD

**Issue by majkinetor** [dbeaver/dbeaver#11842]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro  10.0.19042 N/A Build 19042
- DBeaver version: 21.0.1
- Additional extensions: none

#### Connection specification:
- Database name and version: Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64) ¶ Aug 22 2017
- Driver name: Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:

```
Select Version, *
from table
```

Error when clicking _Calculate Total Row Count_ column:

```
Error executing row count
  SQL Error [8156] [S0001]: The column 'Version' was specified multiple times for 'dbvrcnt'.
  SQL Error [8156] [S0001]: The column 'Version' was specified multiple times for 'dbvrcnt'.
    The column 'Version' was specified multiple times for 'dbvrcnt'.
    The column 'Version' was specified multiple times for 'dbvrcnt'.
```

**Comment by uslss** [comment]
thanks for the bug report

**Comment by majkinetor** [comment]
This also happens with sqlite 3.32.3 with query like this:

```sql
select distinct col1, col2 from table 
```

```
Error executing row count
  SQL Error [1]: [SQLITE_ERROR] SQL error or missing database (wrong number of arguments to function count())
  SQL Error [1]: [SQLITE_ERROR] SQL error or missing database (wrong number of arguments to function count())
    [SQLITE_ERROR] SQL error or missing database (wrong number of arguments to function count())
    [SQLITE_ERROR] SQL error or missing database (wrong number of arguments to function count())
```

**Comment by Matvey16** [comment]
This problem is specific to SQLite and SQL Server syntax and how DBeaver processes row count for this databases. Unfortunately we don't have a solution for this so far. For the time being, as a workaround, you can count rows (if you need to know exact number) by doing minor adjustments to your query to not include duplicate columns.
