### ISSUE TITLE
Export Excel

### ISSUE THREAD

**Issue by WGALVAO2020** [dbeaver/dbeaver#11849]
Boa tarde,
          Gostaria de saber se existe alguma opção export no formato de arquivo do Excel *.xls ou *.xlsx?

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
Hi @WGALVAO2020 ,
with CE version you can use [Office extension](https://github.com/dbeaver/dbeaver/wiki/Optional-extensions#office-integration).
Also, export to excel is available in [Enterprise edition](https://dbeaver.com/) by default
