### ISSUE TITLE
PostgreSQL - unable to edit table column default value

### ISSUE THREAD

**Issue by elring** [dbeaver/dbeaver#11847]
OS: Linux Mint 20
DBeaver version: CE 21.0.1
Database: PostgreSQL 12

Table editor doesn't save default values for column.

Reproduce: create any table like 
```
CREATE TABLE public.testtable (
	aint int4 NULL
);
```
Try to edit column default value - in column list - entered value 123 immediately "disappears" - saving table results in DDL `ALTER TABLE public.testtable ALTER COLUMN aint DROP DEFAULT;`.

Editing in column details allows to "enter" default value, but saving also results in DDL `ALTER TABLE public.testtable ALTER COLUMN aint DROP DEFAULT;`.

Editing default values works after downgrade to 21.0.0 (proper DDL is `ALTER TABLE public.testtable ALTER COLUMN aint SET DEFAULT 123;`).

**Comment by LonwoLonwo** [comment]
Thanks for the bug report!

**Comment by LonwoLonwo** [comment]
Fixed in 21.0.2

**Comment by uslss** [comment]
verified
