### ISSUE TITLE
Hiding columns makes export to any format invalid

### ISSUE THREAD

**Issue by majkinetor** [dbeaver/dbeaver#11843]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro  10.0.19042 N/A Build 19042
- DBeaver version: 21.0.1
- Additional extensions: none

#### Connection specification:
- Database name and version: Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64) ¶ Aug 22 2017
- Driver name: Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:

All formats I tried (Markdown, CSV, HTML etc.) produce wrong export where certain columns are mixed or not shown.

Here is a screenshot where selected rows are exported with option _Selected Rows only_. In editor is shown markdown export:

![image](https://user-images.githubusercontent.com/85767/112139481-1a44aa00-8bd3-11eb-9e3c-cb30bff384f5.png)

Attribute `Trezor` has 3 chars and export shows 4 chars in that columns, which is from _hidden_ column. Also, notice that attribute `MB_deo` shows the `Naziv` attribute in export and that `Naziv` is empty in export.

This is the relevant column arrangement:

![image](https://user-images.githubusercontent.com/85767/112139338-eec1bf80-8bd2-11eb-86c5-38c1b2f08b33.png)

Enabling column `JBBK` there makes export correct again

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Export just ignored columns visibility configuration.
Fixed

**Comment by uslss** [comment]
verified
