### ISSUE TITLE
DBeaver does not answer for 1-2 minutes before click on  not available resource

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#11845]
DBeaver vers 21.0.1
Postgresql 9.5, 12.2
![изображение](https://user-images.githubusercontent.com/61137576/112156118-c4d6c000-8c07-11eb-8053-706fbe43f23e.png)

I do not know that the server SERVER_MAIN is already off or available.

1. Open objects tree  of SERVER_MAIN  in left part of the interface.
2. Duble click on a stored procedure 
 
![изображение](https://user-images.githubusercontent.com/61137576/112155197-e4211d80-8c06-11eb-9f5d-47ecf1138350.png)

and DBeaver absolutly locked for 1-3minutes with this picture in the down part 
![изображение](https://user-images.githubusercontent.com/61137576/112155534-36fad500-8c07-11eb-9a15-d451e8a95fd7.png)
All DBeaver buttons are not available for this time. After that DBeaver  open the empty procedure edit window.

**Comment by kseniiaguzeeva** [comment]
We need in Thread dump to understand the reason https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump.

**Comment by detkliff** [comment]
resource for formula tab is not available, click for this tab 
![изображение](https://user-images.githubusercontent.com/61137576/113384256-1537e580-939f-11eb-9d80-d070c50e57c1.png)

and DBeaver is freeze with this procedure

![изображение](https://user-images.githubusercontent.com/61137576/113384071-b3777b80-939e-11eb-85ec-1944e15349f5.png)

no effect when i click to this button when she red color

![изображение](https://user-images.githubusercontent.com/61137576/113384458-8081b780-939f-11eb-8aa0-e174185fbaf7.png)


Dbeaver version 21.0.1 it became impossible to work.

**Comment by detkliff** [comment]
run jstack 8264 > thead-dump.txt in windows 10 task manager


![изображение](https://user-images.githubusercontent.com/61137576/113385560-d0fa1480-93a1-11eb-97ff-ecebb04df93f.png)

**Comment by kseniiaguzeeva** [comment]
Sorry, my advice was incomplete. Embedded DBeaver Java cannot do it. Can I ask you to install Java manually and get Thread dump https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump?

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual for you - feel free to reopen it.
