### ISSUE TITLE
SQL Editor: the numbers inside arrays don't use the color for numbers

### ISSUE THREAD

**Issue by ggregoire** [dbeaver/dbeaver#11853]
Hi! First of all, thanks for that amazing database client!

**Is your feature request related to a problem? Please describe.**

In the SQL Editor, the numbers inside arrays don't use the color for numbers.

It makes it hard to read the numbers. For example, in this screenshot:

<img width="191" alt="Screen Shot 2021-03-23 at 2 38 31 PM" src="https://user-images.githubusercontent.com/591804/112215454-022a5600-8be6-11eb-97b1-da966612eb8b.png">

Is it

* [5, 876, 948, 3, 350, 305]
* [5876, 948, 3350, 305]
* [5, 876948, 3, 350305]
* [5876948, 3350305]

?

**Describe the solution you'd like**

Use the color for numbers. Here is a mockup:

<img width="191" alt="112215454-022a5600-8be6-11eb-97b1-da966612eb8b" src="https://user-images.githubusercontent.com/591804/112217062-d9a35b80-8be7-11eb-9d7a-4745911f8843.png">

**Comment by serge-rider** [comment]
Thanks for the bug report.

Fixed

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by ggregoire** [comment]
@serge-rider @kseniiaguzeeva Hi! Thanks for the fix! Do I need to check an option in the settings? 

I see the fix was added to the 21.0.2 but on my 21.1.1 (postgresql, macOS) numbers are not blue in the arrays:

<img width="976" alt="Screen Shot 2021-07-02 at 12 57 56 PM" src="https://user-images.githubusercontent.com/591804/124312591-28408a00-db35-11eb-8d87-501ee8dee097.png">
