### ISSUE TITLE
MySQL function round is not work in script `insert into my_price(price) select round('42.0asd',2) as price

### ISSUE THREAD

**Issue by lauliu** [dbeaver/dbeaver#11858]
In MySQL database, I want to transform data from string to decimal(18,2),as follower,

1.  `select round('42.0asd',2) as price;` this script result is ok;
2. ` create table my_price( price decimal(18,2) );`,this script  to create a table;
3. `insert into my_price(price) select round('42.0asd',2) as price;` ,but this script is except,it's report “SQL 错误 [1292] [22001]: Data truncation: Truncated incorrect DOUBLE value: '42.0asd'”，the function round is not work,the same script in SQLyog is ok,and the script itself is not error,please debug soon,best wishes!

**Comment by lauliu** [comment]
can adjust it to a warning ? not a exception!

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
looks like it is not dbeaver issue

**Comment by E1izabeth** [comment]
It doesn't look like a valid query.
