### ISSUE TITLE
Issue with Ctrl+ArrowKey hotkey around underscores in SQL Editor

### ISSUE THREAD

**Issue by DeflateAwning** [dbeaver/dbeaver#11854]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.2.3 and 7.3.4

#### Connection specification:
- Database name and version: N/A
- Driver name: N/A
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Good Behaviour: In the SQL text editor, using Ctrl+LeftArrowKey or Ctrl+RightArrowKey to jump forward/backwards by one word at a time works. However, when you try to jump forwards and backwards with a word with underscores (like "word1_word2_word3"), it jumps forwards/backwards to the underscores, which makes sense for SQL (but is non-standard in normal word processors and text editors).

The Problem: Start at the start of the string "word1_word2_word3". Press Ctrl+RightArrow twice. You would expect to be at the start of word3, but instead the second keypress only takes you to the right side of the first underscore. Pressing Ctrl+ArrowKey should never just bring you to the other side of an underscore.

#### Steps to reproduce, if exist:
See above.

**Comment by uslss** [comment]
thanks for the report
duplicates #1155
