### ISSUE TITLE
When we close DBeaver with unsaved changes in Data Editor and refuse to save them in the pop up, it appears twice

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11859]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.2 EA

#### Steps to reproduce, if exist:
1. Open a table in the Data Editor and make any change
2. Press the cross to close DBeaver
3. Refuse to save changes in the pop up

**Expected**: DBeaver is closed, and the changes are not applied
**Actual result**: the  pop up appears the second time, DBeaver is closed after pressing yes or no, and the changes are not applied
#### Include any warning/errors/backtraces from the logs

https://user-images.githubusercontent.com/51405061/112281952-ab7d5480-8c97-11eb-829c-052198e805a7.mp4

**Comment by serge-rider** [comment]
Duplicate of #11929
