### ISSUE TITLE
Password doesn't meet requirements

### ISSUE THREAD

**Issue by staze** [dbeaver/dbeaver#11850]
Just ran into this issue: https://github.com/dbeaver/dbeaver/issues/5175

Found the issue is dbeaver is trying to create the user with a blank password, then alter the user to add the password as two separate operations. The first one fails because the of password complexity rules. 

Removing the alter piece, and tying into the create fixes the issue. This is on MySQL 8, and current dbeaver (Version 21.0.1.202103211229).

**Comment by uslss** [comment]
Hi @staze ,
did you try to use Mysql(not Mysql 5) driver and check if it helps?
![image](https://user-images.githubusercontent.com/31996417/112297301-c60afa00-8ca6-11eb-9c79-0cb3aaeac129.png)
for me works ok:
![image](https://user-images.githubusercontent.com/31996417/112297244-b5f31a80-8ca6-11eb-91db-f620a62af5c4.png)

**Comment by staze** [comment]
It is using that driver. 

I'm connecting to an MySQL 8 Community server over SSH. This is how it generates the create user strings. 

![image](https://user-images.githubusercontent.com/1100483/112551899-0d64b980-8d7f-11eb-9fc3-601537bb3fee.png)

**Comment by ShayArtzi** [comment]
I faced this issue as well with MySql 8 over SSH. As a workaround, I manually added the `IDENTIFIED BY` clause to the `CREATE USER` statement.

**Comment by uslss** [comment]
verified
