### ISSUE TITLE
Unable to get Snowflake connection to work

### ISSUE THREAD

**Issue by william-demasi** [dbeaver/dbeaver#11852]
I am not able to get the connection to Snowflake works. None of the documentation I've seen addresses what I am experiencing.

Snowflake version: 5.8.2

![image](https://user-images.githubusercontent.com/81262576/112210799-87ffce80-8bf1-11eb-97b4-03b1ed9cc2a7.png)

![image](https://user-images.githubusercontent.com/81262576/112211514-5f2c0900-8bf2-11eb-90b2-053cff7adbb8.png)
But I've loaded the .jar file!
![image](https://user-images.githubusercontent.com/81262576/112212294-2d677200-8bf3-11eb-8e48-b42fb1d1818d.png)

**Comment by LonwoLonwo** [comment]
Hello @william-demasi 
Have you tried to use "Reset to Defaults"?
Also https://stackoverflow.com/questions/54371447/what-are-the-differences-between-javadoc-jar-sources-jar-and-jar

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it.
