### ISSUE TITLE
lost the ability to point defaul column value

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#11860]
DBeaver 21.0.1
Postgresql 9.6,  12.2

CASE1
1.Create table
CREATE TABLE gty_test.newtable_2 (
	column1 bool NOT NULL
);
2.Open table edit window and edit value
![изображение](https://user-images.githubusercontent.com/61137576/112299065-40dd1080-8cb9-11eb-8102-43acd060f4f8.png)
3.Click on save button. DBeaver open alter table window with the script
"ALTER TABLE gty_test.newtable_2 ALTER COLUMN column1 DROP DEFAULT;"

It is wrong script for point default "false" value.

CASE2
1.Create table
CREATE TABLE gty_test.newtable_2 (
	column1 bool NOT NULL
);
2.Open table edit window and edit value
![изображение](https://user-images.githubusercontent.com/61137576/112299065-40dd1080-8cb9-11eb-8102-43acd060f4f8.png)
3. Click to another cell 
![изображение](https://user-images.githubusercontent.com/61137576/112299763-eee8ba80-8cb9-11eb-8b66-19564a6a9b45.png)

DBeaver clear cell with "false" value. It is wrong event.

**Comment by uslss** [comment]
thanks for the report
fixed in the scope of #11847
