### ISSUE TITLE
there is no update for more than a month.

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#11869]
there is no update for more than a month.
If the issue is still actual for you - feel free to reopen it

_Originally posted by @uslss in https://github.com/dbeaver/dbeaver/issues/10259#issuecomment-760439159_

DBeaver 21.0.1 It now highlights the first error (which is an improvement).  The bottom of the window now lists the current cursor position as Line: character along line: character from beginning of statement.  Unfortunately only indication it gives of the location of the error is still just a position (which I am assuming is in characters from the beginning of the statement) ex: Position: 162.  It would be very helpful if it could provide the location of the error in a format that matches that in the bottom of the window.  Additionally, when parsing a statement and there is a syntax error, it would be helpful if it listed all of the errors encountered, not just the first one.

Thanks.

**Comment by uslss** [comment]
#10259 reopened. Thanks for the clarification, move your comment to #10259
