### ISSUE TITLE
Inconsistent behavior on "Results" tab

### ISSUE THREAD

**Issue by noschang** [dbeaver/dbeaver#11863]
#### System information: 
- Ubuntu 20.04 LTS
- DBeaver 21.0.1.202103211229
- Additional extensions: None installed

#### Connection specification:
- Oracle 11g
- JDBC8
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

After running a query I try to press ```Shift+Ctrl+\``` in the results tab to fetch the entire dataset. However, DBeaver seems inconsistent because sometimes the shortcut works and sometimes don't. And the problem is not just with the shortcut, the button ```Fetch all rows``` in the bottom bar of the result tab is also disabled. I have to rerun the query to make it work.

The behavior seems to be random, I could not identify a pattern. It happens on small datasets and on large datasets, with and without joins, with and without where clauses.

**Comment by kseniiaguzeeva** [comment]
Could you please send a video with the bug and log files https://github.com/dbeaver/dbeaver/wiki/Log-files?

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual for you - feel free to reopen an issue.
