### ISSUE TITLE
Unable to connect to jdbc repository

### ISSUE THREAD

**Issue by TeoZ73** [dbeaver/dbeaver#11862]
#### System information: 
- Operating system win10 2004 19041.329
- DBeaver version 21
- Additional extensions None

After a new istallation is impossible downloading jdbc driver from site https://dbeaver.io/files/jdbc

tnk

**Comment by uslss** [comment]
Hi @TeoZ73 ,
Drivers will automatically download when you start to create a new connection

**Comment by TeoZ73** [comment]
when i try to connect/download...

Can't create driver instance
  Error creating driver 'DB2 iSeries/AS 400' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.ibm.as400.access.AS400JDBCDriver'
  Error creating driver 'DB2 iSeries/AS 400' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.ibm.as400.access.AS400JDBCDriver'
    com.ibm.as400.access.AS400JDBCDriver
    com.ibm.as400.access.AS400JDBCDriver

and if i try to go in website...

https://dbeaver.io/files/jdbc

This is the error... 

![immagine](https://user-images.githubusercontent.com/81308199/112326453-d2964f00-8cb4-11eb-8811-1034c4b9d675.png)

**Comment by uslss** [comment]
Cannot reproduce it.
Could you try to reset driver settings to default and then download the driver once again?
![2021-03-25_10h50_09](https://user-images.githubusercontent.com/31996417/112437502-12fad900-8d58-11eb-841d-d4d3d31469c2.gif)

**Comment by TeoZ73** [comment]
tnk now it work fine
