### ISSUE TITLE
Disconnect all databases when it's categorized

### ISSUE THREAD

**Issue by zarpelon** [dbeaver/dbeaver#11873]
I am organizing my connections by separate project directories. What happens is that over the course of the day I may have several open connections and currently there is no way to "close all connections"

![new_feature](https://user-images.githubusercontent.com/264762/112416029-a48c2b80-8d03-11eb-87be-aecb85980bf4.png)

**Comment by kseniiaguzeeva** [comment]
You can do it using **Disconnect all** in Database menu.

https://user-images.githubusercontent.com/51405061/112480447-19ed1000-8d87-11eb-9e90-130d8c3a9f63.mov

**Comment by zarpelon** [comment]
nice! works fine.
