### ISSUE TITLE
conexao com ODBC ja instalado no windows

### ISSUE THREAD

**Issue by sisazim** [dbeaver/dbeaver#11870]
configuracao para selecionar o driver instalado no windows

**Comment by uslss** [comment]
Hi @sisazim ,
could you provide more information about your problem in English with clear steps?

**Comment by sisazim** [comment]
good morning, grateful for the help.

 

a step by step configuration to include an existing ODBC connection on windows.

 

there is an ODBC drive installed on windows and I want to use that drive, how to view to configure access?

 

 

 



 

I want to configure here my drive already installed in the window

 



 



 

 

De: Dziyana ***@***.***> 
Enviada em: quinta-feira, 25 de março de 2021 04:54
Para: dbeaver/dbeaver ***@***.***>
Cc: sisazim ***@***.***>; Mention ***@***.***>
Assunto: Re: [dbeaver/dbeaver] conexao com ODBC ja instalado no windows (#11870)

 

Hi @sisazim <https://github.com/sisazim>  ,
could you provide more information about your problem in English with clear steps?

**Comment by uslss** [comment]
You could try to use the default odbc driver in DBeaver
![image](https://user-images.githubusercontent.com/31996417/112808520-bc580c80-9081-11eb-8f8c-ece6bd9cbb2c.png)
