### ISSUE TITLE
Closing the open editor tab will freeze dbeaver for a little while

### ISSUE THREAD

**Issue by Mizar01** [dbeaver/dbeaver#11876]
- Linux Mint 19 
- DBeaver version : 21.0.1

Context: Postgres connection through tunnelling

I open multiple editor tabs. Sometimes i have to clean up tabs so I close all of them. Trying to close the last left open tab: dbeaver freeze for 20 seconds or more without responding.
Never noticed this bug before.

**Comment by kseniiaguzeeva** [comment]
Could you please send a video with the bug and [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files)?
Does it depend on quantity of tabs?

**Comment by Mizar01** [comment]
Hi. 
I tried, but I can't reproduce it anymore.
It happened yesterday and this morning twice. 
The number of open tabs was less than 5.

Lately I was cleaning all my saved scripts, deleting them both from the software and from the file system, but in any case I'm not saving those tabs.

I will try to reproduce in the next days to see if there is some pattern.

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual for you - feel free to reopen an issue.
