### ISSUE TITLE
[SQL Console] Formatting adds a delimiter in the unsuitable part of the query

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#11875]
- DBeaver 21.0.1
- MySQL 8.0/PostgreSQL 10 and other

Formatting in SQL Console (but not in SQL Editor) with setting "Insert delimiters in empty lines" adds a delimiter on the end of every row.

Steps:
- Open any table and add any filter
- Use ctrl+click on the table name in the left angle to open query in SQL Console
- Use ctrl+schift+F on the query with enable setting in Preferences "Insert delimiters in empty lines"

![2021-03-25 11_56_48-DBeaver Enterprise 21 0 1 - actor](https://user-images.githubusercontent.com/45152336/112446807-a71d6e00-8d61-11eb-9095-d1edb656c24f.png)

![2021-03-25 11_47_42-DBeaver Enterprise 21 0 1 - _dvdrental_ actor](https://user-images.githubusercontent.com/45152336/112446829-ab498b80-8d61-11eb-8c39-efaa854446f9.png)

![2021-03-25 11_52_05-DBeaver Enterprise 21 0 1 - _dvdrental_ actor](https://user-images.githubusercontent.com/45152336/112446853-b2709980-8d61-11eb-8d7a-e22ae7754da0.png)

![2021-03-25 11_53_56-DBeaver Enterprise 21 0 1 - _dvdrental_ actor](https://user-images.githubusercontent.com/45152336/112446857-b3093000-8d61-11eb-84e6-fc673e4d6556.png)

**Comment by LonwoLonwo** [comment]
Also this behaviour reproduce in SQL Editor with MacOS and Linux systems with enable setting "Insert delimiters in empty lines" in preference.

**Comment by LonwoLonwo** [comment]
Fixed in 21.0.2

**Comment by kseniiaguzeeva** [comment]
Verified (Win and Mac were tested)
