### ISSUE TITLE
In filters pane, Counts don't sort properly

### ISSUE THREAD

**Issue by DeflateAwning** [dbeaver/dbeaver#11871]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.0.1
- Additional extensions

#### Connection specification:
- Database name and version: MySQL
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When you sort by the "Count" column added in Issue #10961 (i.e. click on the column name), it sorts like a string/text column instead of numerically. 

![image](https://user-images.githubusercontent.com/11021263/112407765-4d269500-8cdc-11eb-9c99-2a7e4b115729.png)

Also, please add locale-specific thousands separators. 

#### Steps to reproduce, if exist:
1. Click the Filter button on a column
2. In the resulting filter pane, click the "Count" column to sort by that column

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
Fixed and implemented:

![image](https://user-images.githubusercontent.com/35821147/118246698-ff900280-b4aa-11eb-8b45-1334c7a5192a.png)

**Comment by DeflateAwning** [comment]
The screenshot shown there always worked fine. Can you do a test with numbers of varying orders of magnitude (like 9. 14, 115, etc.)? Thanks!

**Comment by ShadelessFox** [comment]
Oh, sure, I wanted to show formatting :)

![image](https://user-images.githubusercontent.com/35821147/118287004-b906cc00-b4db-11eb-9924-a8bf238f867e.png)

**Comment by DeflateAwning** [comment]
This looks perfect, thank you!

**Comment by uslss** [comment]
verified
