### ISSUE TITLE
Foreign key dictionary doesn't work with connexion in read only mode

### ISSUE THREAD

**Issue by benjdv** [dbeaver/dbeaver#11886]
Hi,
The "dictionary" functionnality that show foreign key value when navigate into data is a great capacity of dbeaver.
Unfortunatly this functionnality doesn't work with the security mode "read only"
I don't know why there is this limitation.
Please consider, if it's possible, to allow dictionary to work with connection in read only mode.
Regards,

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by ShadelessFox** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/35821147/114601145-d9095c80-9c9d-11eb-9cd8-a245b23f2e49.png)

**Comment by kseniiaguzeeva** [comment]
verified
