### ISSUE TITLE
Schema not visible in navigator when Schema filter used

### ISSUE THREAD

**Issue by rstaylor** [dbeaver/dbeaver#11883]
#### System information: 
- Operating system: Ubuntu 18.04
- DBeaver version: 21.0.1.202103211229
- Additional extensions

#### Connection specification:
- Database name and version: InterSystems IRIS v2021.1
- Driver name: InterSystems IRIS
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
When I apply an exclusion filter to the Schemas shown in the connection the navigator will no longer organize the tree structure by schema.  In fact all tables are lumped together in one table list with no schema information provided at all

#### Steps to reproduce, if exist:
Connect to a database with multiple schemas.  Try to exclude one using a wild card.  In my case I had schema that began with a '%' which are system related and I didn't want to see.

**Comment by uslss** [comment]
Hi @rstaylor .
did you try to escape '%' with backslash?

**Comment by rstaylor** [comment]
Yes, to be clear the filter works.  However the results in the navigator does not organize the tree by schema.  All the tables are mixed together under tables with no schema.  Then when I try to look at one of the table's data it tries to use a generic default schema which fails.


If I use an inclusion filter it all works correctly.  The schema selected each have their own branch in the navigation tree.


Richard (Rich) Taylor
Senior Sales Engineer | InterSystems
Direct: +1.443.340.8614
InterSystems.com<http://www.intersystems.com/>

[1605287844147]


________________________________

**Comment by uslss** [comment]
thanks for the report and clarification

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
