### ISSUE TITLE
ADD support for color themes (like GapStyle) 

### ISSUE THREAD

**Issue by allanlaal** [dbeaver/dbeaver#11889]
**Is your feature request related to a problem? Please describe.**
I'm editing code (including SQL) on different IDE's and Editors, so I'm using the GapStyle color scheme to unify everything - now every editor feels like home™ :)

**Describe the solution you'd like**
Implement support for color schemes using the same mechanism that [GapStyle uses](https://github.com/gaplo917/GapStyle/blob/c8cb069b32cb273160e5dc185ccde542f86a589b/intellij/GapStyle/colors/GapStyle.xml#L3028)

**Describe alternatives you've considered**
editing the color scheme manually every time I install DBeaver somewhere

**Comment by kseniiaguzeeva** [comment]
You can add Eclipse plugin for color themes https://marketplace.eclipse.org/content/eclipse-color-theme via Help>Install new software. Please try it.

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual for you - feel free to reopen it.
