### ISSUE TITLE
Export geometry doesn't include SRID

### ISSUE THREAD

**Issue by FirKys** [dbeaver/dbeaver#11895]
#### System information: 
- Operating system (distribution) and version:  **Win 10**
- DBeaver version:  **21.0.1.202103211229**
- Java version: **Java 9**

====

#### Connection specification:
- Database name and version: !!**PostGIS**!! 2.5.2
- Driver name: postgres
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **no**

====

#### Describe the problem you're observing:
During exporting data to CSV from a table the geometry does not include the SRID.
In the case of .sql the srid is saved correctly.

**example.csv**
```
"id","geometry"
"e264678c-36a1-4058-a68b-073b2c335052", "POINT (60.0138529412013 69.7804254384701)"
```

**example.sql**
```
INSERT INTO test (id,geometry) VALUES
	 ('e264678c-36a1-4058-a68b-073b2c335052'::uuid, 'SRID=4326;POINT (60.0138529412013 69.7804254384701)'::geometry);
	 
```
====

#### Steps to reproduce, if exist:
1. Create a table,

```
CREATE TABLE test(
	id uuid NOT NULL DEFAULT uuid_generate_v4(),
	geometry geometry NULL
);
```
2. Save a data including SRID.
3. Export to .csv

#### Include any warning/errors/backtraces from the logs
No errors or warnings

**Comment by flambchap** [comment]
Thank you for the report.

**Comment by flambchap** [comment]
The best solution I came up with is to add a new data transfer setting called 'Value format'. In this particular case, this setting should be set to 'Database native'.

![Screenshot 2021-04-12 145814](https://user-images.githubusercontent.com/26031301/114390961-8f3a4c80-9b9f-11eb-8f48-c30e066bd140.png)

**Comment by uslss** [comment]
verified
