### ISSUE TITLE
IntersSystems Caché - GlobalCharacterStream shows as [CacheInputStream]

### ISSUE THREAD

**Issue by douglasdtc** [dbeaver/dbeaver#11899]
#### System information
- Operating System: Windows 10 Enterprise
- DBeaver Version: 21.0.1.202103211229
- Additional Extensions: None

#### Connection specification
- Database: InterSystems Caché 2018
- Driver: Caché
- Tunnels or Proxies: No

#### Problem
When we have a datatype of `GlobalCharacterStream` on a table, instead of showing the values, it's presenting the value `[CacheInputStream]`. I was using version 7.0.0 of DBeaver and this was working fine, after upgrading to this version I can't seem to find a way to obtain the value.

#### Steps to Reproduce
Run a query that returns any `GlobalCharacterStream` with a non null value. The column will show [CacheInputStream] instead of the value.
This is a Caché class definition that contains the field:

```
Class EXAMPLE.DBeaverStream Extends %Persistent
{
  Property Objeto As %GlobalCharacterStream;
}
```

Then run this `INSERT`:
`INSERT INTO EXAMPLE.DBeaverStream(Objeto) VALUES ('This value should be presented')`

And finally, run this `SELECT`:
`SELECT * FROM EXAMPLE.DBeaverStream`

This is the result on version 21 (the ID is 103 because of another tests on this table):
![image](https://user-images.githubusercontent.com/19532943/112676362-1751ef80-8e47-11eb-8f2b-5d18dc567c71.png)

This is the result on version 7:
![image](https://user-images.githubusercontent.com/19532943/112676451-35b7eb00-8e47-11eb-9708-6938c6323a47.png)

#### Additional Info
In the past, there was another bug regarding this same datatype, don't know if it helps, but this was the issue: https://github.com/dbeaver/dbeaver/issues/469

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
Unfortunately we don't have Cache server in our test env

**Comment by douglasdtc** [comment]
@serge-rider  , as suggested in the other issue (https://github.com/dbeaver/dbeaver/issues/5353), we can provide a test enviroment with a Cache Server with the minimum setup to reproduce this behaviour if you would like to.

**Comment by tati-kru** [comment]
@douglasdtc it would be great! Could you please send all details to support@dbeaver.com?

**Comment by LonwoLonwo** [comment]
Hello @douglasdtc 

I see that in Dbeaver we are using the old driver version.

Could you please check your issue with the latest driver version? 
https://www.cachemonitor.de/intersystems-documentation-cache-jdbc-driver/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
