### ISSUE TITLE
mssql - it is not possible to insert new lines into tables containing calculated columns

### ISSUE THREAD

**Issue by aisbergde** [dbeaver/dbeaver#11900]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver Version 21.0.1.202103211229
- Additional extensions

#### Connection specification:
- Database name and version, SQL Server 2019
- Driver name default
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

it is not possible to duplicate / insert new lines into tables containing calculated columns
dbeaver tries to insert data into these columns, but of course this is not possible, because they are calculated

#### Steps to reproduce, if exist:

create a table containing calculated columns. for example:

```sql
CREATE TABLE [repo].[GeneratorUsp](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[usp_schema] [nvarchar](128) NOT NULL,
	[usp_name] [nvarchar](128) NOT NULL,
	[has_logging] [tinyint] NOT NULL,
	[usp_Description] [nvarchar](4000) NULL,
	[usp_fullname]  AS (concat('[',[usp_schema],'].[',[usp_name],']')) PERSISTED NOT NULL,
 CONSTRAINT [PK_GeneratorUsp] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_GeneratorUsp_Schema_Name] UNIQUE NONCLUSTERED 
(
	[usp_schema] ASC,
	[usp_name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [repo].[GeneratorUsp] ADD  CONSTRAINT [DF_GeneratorUsp_has_logging]  DEFAULT ((1)) FOR [has_logging]
GO
```

- Try to duplicate an existing entry and change the content of the column [usp_name]
- try to save changes

SQL Error [271] [S0001]: The column "usp_fullname" cannot be modified because it is either a computed column or is the result of a UNION operator.
  The column "usp_fullname" cannot be modified because it is either a computed column or is the result of a UNION operator.
  The column "usp_fullname" cannot be modified because it is either a computed column or is the result of a UNION operator.

**Comment by uslss** [comment]
thanks for the report

**Comment by Matvey16** [comment]
Verified
