### ISSUE TITLE
Fetch Size value is zero, the whole table is fetched

### ISSUE THREAD

**Issue by baliramaswamy** [dbeaver/dbeaver#11902]
Hi,

I see DBeaver sends a cancellation request based on the "Resultset Fetch Size", default is 200 on the version I have. If I change it to 100, query cancels at 100. If I change it to zero it does not send a cancellation request. Is that the exepcted behavior of the product?

Thanks
Balaji

**Comment by uslss** [comment]
Hi @baliramaswamy ,
if I catch you right, it is expected behavior. In case fetch size value is set to 0, the whole table should be fetched.
