### ISSUE TITLE
Extend support for disabling referential integrity checks in data transfer

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#11908]
In https://github.com/dbeaver/dbeaver/issues/11047, we added support for disabling foreign key checks for Oracle and PostgreSQL. Now we need to extend this option on other databases. MySQL, SQL Server, DB2, and Exasol are in priority.

**Comment by flambchap** [comment]
It turns out that DB2 is kind of tricky in that department, so I'm not implementing DB2 support in this ticket.

**Comment by Matvey16** [comment]
Can't start export in SQL Server because of an error

![dbeaver_3uXM6w4vVl](https://user-images.githubusercontent.com/82543000/125061980-939ad680-e0b6-11eb-8d6b-8e1ab7130eb4.png)

**Comment by flambchap** [comment]
Fixed that one.

**Comment by Matvey16** [comment]
Verified
