### ISSUE TITLE
support for Firebase Cloud Firestore

### ISSUE THREAD

**Issue by allanlaal** [dbeaver/dbeaver#11909]
Cloud Firestore is Firebase's newest database for mobile app development. It builds on the successes of the Realtime Database with a new, more intuitive data model. Cloud Firestore also features richer, faster queries and scales further than the Realtime Database.

https://firebase.google.com/docs/database/rtdb-vs-firestore

**Comment by serge-rider** [comment]
I didn't find any Java drivers for Firebase.
Potentially we could use REST API but it will require quite a lot of effort.

**Comment by KurtMar** [comment]
Looks like there is a 3rd party JDBC driver available: https://github.com/shiveshnavin/firestore-jdbc-driver

**Comment by E1izabeth** [comment]
We have added Firestore support in 23.2.4. It will be available in DBeaver PRO version 23.3.0 (early access version https://dbeaver.com/files/ea/). And we are working on improvements right now.

**Comment by KurtMar** [comment]
If you are not seeing many Firestore users jumping on the Enterprise or Ultimate wagon, consider including it in Lite. ;)
