### ISSUE TITLE
support for Firebase Realtime Database

### ISSUE THREAD

**Issue by allanlaal** [dbeaver/dbeaver#11910]
Realtime Database is Firebase's original database. It's an efficient, low-latency solution for mobile apps that require synced states across clients in realtime.

its still in use in many Firebase applications, but not as important as #11909 

https://firebase.google.com/docs/database/rtdb-vs-firestore

**Comment by PierceSDS** [comment]
Has there been any reconsideration of support for Firebase/Firestore, it looks like Google has made progress on their Java SDK.

**Comment by KurtMar** [comment]
Looks like there is a 3rd party JDBC driver available: https://github.com/shiveshnavin/firestore-jdbc-driver

**Comment by E1izabeth** [comment]
We have added Firestore support in 23.2.4. It will be available in DBeaver PRO version 23.3.0 (early access version https://dbeaver.com/files/ea/). And we are working on improvements right now.
