### ISSUE TITLE
Copy table & column rename creates wrong DDL

### ISSUE THREAD

**Issue by elring** [dbeaver/dbeaver#11917]
OS: Linux Mint 20
Dbeaver: 21.0.2 EA (and 21.0.0)
DB: PostgreSQL 12

After table copy (for example Ctrl+C and Ctrl+V in table list) new table is "pre-created". When I immediately rename some column in this table (without previous saving), the result DDL is wrong. The table is created with new column name, that's ok. But then follows wrong additional rename SQL clause. This rename SQL should not be created at all.

See the table DDL (original column was testchar, new column name is testchar_newname).

```
CREATE TABLE public.testtable_1 (
	id serial NOT NULL,
	testchar_newname varchar NULL,
	CONSTRAINT testtable_pkey_1 PRIMARY KEY (id)
);
ALTER TABLE public.testtable_1 RENAME COLUMN testchar TO testchar_newname;
```

**Comment by uslss** [comment]
thanks for the report

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
#13358 New related issue opened
