### ISSUE TITLE
[Redshift] Support for users and permissions.

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#11912]
Now in DBeaver 21.0.1 we have only permissions button in table DDL.

![2021-03-29 14_33_28-Window](https://user-images.githubusercontent.com/45152336/112830835-c4bd4100-909b-11eb-983c-619158863ee1.png)

![2021-03-26 19_36_40-DBeaver Enterprise 21 0 2 - venue](https://user-images.githubusercontent.com/45152336/112830895-d999d480-909b-11eb-92c3-964bd6ed37b7.png)

We need to add more information about Permissions as in PostgreSQL

![2021-03-29 15_57_31-Window](https://user-images.githubusercontent.com/45152336/112840354-e3293980-90a7-11eb-8890-1a8b02fa8cbf.png)

**Comment by ShadelessFox** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/35821147/119174362-2a60f480-ba71-11eb-8483-94ab674e045a.png)

**Comment by kseniiaguzeeva** [comment]
Verified
