### ISSUE TITLE
Slowness going between tabs/look ahead feature/writing result

### ISSUE THREAD

**Issue by CraigFNMA** [dbeaver/dbeaver#11919]
#### System information: 
- Windows 10
- DBeaver version 7.10
- Additional extensions - none

#### Connection specification:
- Database name and version - Netezza 7.2.1.7 / Redshift 
- Driver name - nzjdbc.jar / RedshiftJDBC42-no-awssdk-1.2.45.1069.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NA

#### Describe the problem you're observing:

Slow response when navigating between tabs, using the auto fill on tables/views/attributes

#### Steps to reproduce, if exist:
NA
#### Include any warning/errors/backtraces from the logs

NA

**Comment by uslss** [comment]
Hi @CraigFNMA ,
could you check if it is reproducible for you against the recent version(21.0.1)?

**Comment by uslss** [comment]
there is no update on an issue for a long time. If it is still actual for you - feel free to reopen it.
