### ISSUE TITLE
add ability to change foreign key parameters from the interface for Postgresql

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#11922]
DBeaver 21.0.1

![изображение](https://user-images.githubusercontent.com/61137576/112971725-f0f2c380-9168-11eb-9d90-896b7af160bf.png)

**Comment by kseniiaguzeeva** [comment]
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/3400. We are going to implement it after 21.1.0 release.

**Comment by LonwoLonwo** [comment]
Ability to change update/delete rule for existing foreign key implemented in DBeaver 21.2.5

**Comment by Matvey16** [comment]
Verified
