### ISSUE TITLE
msSQL.. query IS NULL for at DATETIME field, does not error but does not display 1 record that is there

### ISSUE THREAD

**Issue by SherlockSoftware** [dbeaver/dbeaver#11923]
Windows 10
DBbeaver21.0.1.202103211229
Java Ver 8 Update 281 . (build 1.8.0_281-b09)
??
msSQL and "mifn2021"  export table "ChequesOut"
- Driver name
![image](https://user-images.githubusercontent.com/64625961/112986538-57013a00-91ad-11eb-9b93-85945f6d2db4.png)

- Do you use tunnels or proxies (SSH, SOCKS, etc)?   [ NO ]

#### Describe the problem you're observing:
Exported a table but how to attach a ZIP file

#### Steps to reproduce, if exist:
SELECT * FROM chequesout WHERE presented IS NULL;

This query should find 1 record as presented date is a NULL
In the right filter IS NULL  etc works but a QUERy does not return the record
Try simpler query SELECT * FROM chequesout WHERE reserved IS NULL;
Works fine.. I am not a SQL or dBbeaver expert and 2 others looked and said the syntax correct.
I use other classes of MSSQL studio and I get a result.

**Comment by kseniiaguzeeva** [comment]
Please tell does your query return a result when you do not use WHERE (SELECT * FROM chequesout)?

**Comment by uslss** [comment]
cannot reproduce it.
![image](https://user-images.githubusercontent.com/31996417/117827786-f66c1f00-b279-11eb-8f30-581ec141376a.png)

also, there is no update on an issue for a long time. 
If it is still actual for you - feel free to reopen it with an additional info
