### ISSUE TITLE
Test tunnel configuration button cut off

### ISSUE THREAD

**Issue by AaronWiora** [dbeaver/dbeaver#11921]
#### System information: 
- Ubuntu 20.10 64-bit Gnome 3.38.3 X11
- DBeaver 21.0.1

#### Describe the problem you're observing:
When creating a MariaDB connection using SSH Tunnel the button **Test tunnel configuration** is not visible because the default height of the window is to small. You can resize the window but that isn't obvious for the user and the window should have a different height by default.

![Screenshot from 2021-03-30 11-29-42](https://user-images.githubusercontent.com/17088412/112967492-9dbe4800-914b-11eb-8b4a-7e94f00e4871.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
Can't reproduce on Windows (dialog resizes  automatically to fit all controls)
