### ISSUE TITLE
UI flickers and is torn apart

### ISSUE THREAD

**Issue by drivertx** [dbeaver/dbeaver#11932]
#### System information: 
- Debian 10 (on Chrome OS 89.0.4389.95)
- DBeaver 21.0.1.202103211229

#### Describe the problem you're observing:
The UI flickers and looks weird.

#### Steps to reproduce, if exist:
Download, install and start.

![DBEaver](https://user-images.githubusercontent.com/81619982/113121865-5e5b2e80-9213-11eb-81d4-0daa08dcf664.png)

**Comment by kseniiaguzeeva** [comment]
Unfortunately we do not support this platform.

**Comment by Dowwie** [comment]
I'm using Debian 9 (stretch).  I also experienced the flickering problem.  It seems to be related to GTK. I resolved the issue with the following steps:

1. added to ~/.profile:  `export GTK_IM_MODULE=ibus`
2. installed the following libraries:  `sudo apt install ibus-gtk ibus-gtk3 ibus-clutter ibus-qt4 -y`
