### ISSUE TITLE
Export as new table DDL issue with SELECT NULL, MySQL

### ISSUE THREAD

**Issue by Montgomeryz** [dbeaver/dbeaver#11946]
#### System information: 
- Win 10
- 21.0.1.202103211229
- Additional extensions

#### Connection specification:
- MySQL 8
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Select NULL as "abc" generates DDL of CREATE.. "abc VARCHAR NULL," which won't parse. Need VARCHAR(n).

Whilst that's understandable, it is not clear to the user where the issue is. Suggest default to VARCHAR(10).

**Comment by kseniiaguzeeva** [comment]
Please write steps to reproduce and full query you use.

**Comment by Montgomeryz** [comment]
select 10 'id', null 'abc';
Executue > Export From Query > Database
Mapping = Create, generates DDL of:

> CREATE TABLE gos.fred (
> 	id BIGINT NOT NULL,
> 	abc NULL NULL
> )
> ENGINE=InnoDB
> DEFAULT CHARSET=utf8mb4
> COLLATE=utf8mb4_0900_ai_ci;

The DDL handling NULL value is not valid MySQL, generating:

> 
> Error occurred during Apply schema changes
> 
> Reason:
> SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL NULL

)

I was using 21.0.2.202104042040 for this query.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by flambchap** [comment]
Now we inference VARCHAR type in the situation when we transfer from MySQL to MySQL. The length still needs to be added by hand.

**Comment by uslss** [comment]
verified
