### ISSUE TITLE
Toolbar dropdown arrow click area too small

### ISSUE THREAD

**Issue by rgranadino** [dbeaver/dbeaver#11947]
#### System information: 
- Operating system (distribution) and version: MacOS 11.2.1
- DBeaver version: 21.0.1.202103211229
- Additional extensions

#### Describe the problem you're observing:
The "click area" of the drop down arrow is small causing me to accidentally click on the button instead of the drop down.

Here the menu is triggered:

<img width="344" alt="Dbeaver_menu_action" src="https://user-images.githubusercontent.com/327608/113246256-80819a80-926d-11eb-8e96-2fa5fadc73e5.png">

And here, the Open SQL script dialog is triggered:

<img width="318" alt="Dbeaver_script_open_action" src="https://user-images.githubusercontent.com/327608/113246318-a9099480-926d-11eb-9c89-4ea32a774f90.png">

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
It is a standard Eclipse control. Unfortunately we can't affect it's look and feel.
