### ISSUE TITLE
Custom application icon overriden by default on MacOS

### ISSUE THREAD

**Issue by zkvvoob** [dbeaver/dbeaver#11951]
#### System information: 
- Operating system (distribution) and version: MacOS 11.2.3
- DBeaver version: CE Version 21.0.1.202103211229
- Additional extensions: No

#### Describe the problem you're observing:
When you set a custom icon using the Get Info dialogue box, it is applied; but once DBeaver starts, it overrides the custom icon with its own, which stands out and doesn't match neither the shape, nor the size of all the icons on the dock.

#### Steps to reproduce, if exist:
Right-click on DBeaver in /Applications, choose Get Info, drag and drop a new icon, start DBeaver

**Comment by uslss** [comment]
thanks for the report
closed as duplicate #11557
