### ISSUE TITLE
Select count query fails

### ISSUE THREAD

**Issue by pgodfrin-nov** [dbeaver/dbeaver#11959]
#### System information: 
- Windows 10
- DBeaver v21.0.1.202103211229

#### Connection specification:
- Postgres 12.6
- Driver name: org.postgresql.Driver

#### Describe the problem you're observing:
This query is failing:
```
explain (analyze, verbose,buffers)
select to_char(count(*),'FM999,999,999,999') from timeseries.raw_large;
```
with:
SQL Error [57014]: ERROR: canceling statement due to user request

Except there is no user request to cancel the statement. The table has over
a billion rows. this is in the log, once for each parallel worker:
```
select /*BIG SELECT COUNT*/to_char(count(*),'FM999,999,999,999') from timeseries.raw_large
2021-04-01 12:40:31 UTC [131]: ()@,app= [00000] LOG:  background worker "parallel worker" (PID 22673) exited with exit code 1

```

**Comment by pgodfrin-nov** [comment]
I'm not convinced this is an issue with DBeaver. Iget the same error from this:

```
create index pgix1_large_ttf on timeseries.raw_large(tag_id, timestamp_utc, float_val);
```

**Comment by kseniiaguzeeva** [comment]
I can execute both statements. Please try the same with another table. Maybe something useful can be found in log files https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by pgodfrin-nov** [comment]
Hi – Yeah it’s a 1.5 billion row table. Is there a way to run on verbose debugging to get a better error message?

**Comment by kseniiaguzeeva** [comment]
Log files will help us to do it. Could you send them https://github.com/dbeaver/dbeaver/wiki/Log-files?

**Comment by pgodfrin-nov** [comment]
See attached. FYI: this is a 1.5 billion row table. The database is a docker container running in a pod in EKS.

pg

From: Kseniia ***@***.***>
Sent: Thursday, April 8, 2021 3:42 AM
To: ***@***.***
Cc: Godfrin, Philippe E ***@***.***>; ***@***.***
Subject: [EXTERNAL] Re: [dbeaver/dbeaver] Select count query fails (#11959)

Use caution when interacting with this [EXTERNAL] email!

Log files will help us to do it. Could you send them https://github.com/dbeaver/dbeaver/wiki/Log-files?

**Comment by pgodfrin-nov** [comment]
Did you get the files?

From: Kseniia ***@***.***>
Sent: Thursday, April 8, 2021 3:42 AM
To: ***@***.***
Cc: Godfrin, Philippe E ***@***.***>; ***@***.***
Subject: [EXTERNAL] Re: [dbeaver/dbeaver] Select count query fails (#11959)

Use caution when interacting with this [EXTERNAL] email!

Log files will help us to do it. Could you send them https://github.com/dbeaver/dbeaver/wiki/Log-files?

**Comment by p91paul** [comment]
@pgodfrin-nov github allows replying to issues via email, but it doesn't support email attachments. To upload stuff you need to reply through the web interface.

**Comment by uslss** [comment]
@pgodfrin-nov is the issue still actual for you? if it is, could you provide logs?

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual for you - feel free to reopen it with additional info
