### ISSUE TITLE
wrong information about error in pgsql code

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#11957]
DBeaver version 21.0.1
Postgresql 12

code:

![изображение](https://user-images.githubusercontent.com/61137576/113289078-2b936200-9309-11eb-85b2-5530cc2f0b27.png)

What is it POSITION 3233? How i can find this position in ma code? Absolutly unusable information.

For example pgAdmin show part of code, when he found the error.

**Comment by ShadelessFox** [comment]
Hello @detkliff,

This is an offset of the error inside your query. This information is provided by the server, we don't modify this error message. Please refer to #11907 for more information.

When the error appears, editor should move the caret to that position.

**Comment by ShadelessFox** [comment]
If you have any questions left, feel free to ask them here.
