### ISSUE TITLE
Cannot add data to empty table 

### ISSUE THREAD

**Issue by qiqingli** [dbeaver/dbeaver#11961]
#### System information: 
- Operating system (distribution) and version: macOS Big Sur 11.2.3
- DBeaver version: 21.0.1
- Java version: AdoptOpenJDK (build 11.0.10+9)

#### Connection specification:
- Database name and version: Oracle 12c

#### Steps to reproduce, if exist:
Create an empty table, the buttons at the bottom of the result set cannot be operated to add data manually !

![image](https://user-images.githubusercontent.com/20805098/113296368-f3e9e180-932b-11eb-9f5e-ef8894aee31b.png)

**Comment by qiqingli** [comment]
Is there any plan to fix this problem？ @uslss

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce it. 
1. Hover over a lock on a column header and tell what is written in the pop up message (it explains, why it is read-only).
![Screenshot 2021-04-06 at 12 26 57](https://user-images.githubusercontent.com/51405061/113689856-6fa0b100-96d3-11eb-917f-4ec3d99ecb8b.png)
2. Do you have permissions to edit tables?
![Screenshot 2021-04-06 at 12 25 18](https://user-images.githubusercontent.com/51405061/113689688-441dc680-96d3-11eb-9e2c-51689c97412f.png)
3. Do you create a new table or edit an existed one; how do open the table etc.?

**Comment by qiqingli** [comment]
1. I have permissions to edit tables.
2. I created a new table and opened it with select * from table.
3. I found the source of the problem, the newly created table needs to be refreshed before adding data.
4. After creating a new table, can dbeaver automatically refresh the data? 
![image](https://user-images.githubusercontent.com/20805098/113691535-18b0d100-96ff-11eb-89fa-771cf22390b0.png)

**Comment by kseniiaguzeeva** [comment]
We are going to implement auto-refresh in 21.1.1 release in https://github.com/dbeaver/dbeaver/issues/6398

**Comment by uslss** [comment]
seems to be outdated for now
