### ISSUE TITLE
Hana: create table sql should not contain the CS_... datatypes

### ISSUE THREAD

**Issue by wernerdaehn** [dbeaver/dbeaver#11963]
#### System information: 
- DBeaver version: 21.0.0

#### Connection specification:
- Database name and version: SAP HANA

#### Describe the problem you're observing:
When you rightclick a table and say "generate ddl" the result looks like this:

```
CREATE COLUMN TABLE "TRACKS" (
  "FILENAME" NVARCHAR(1000),
  "STARTTS" LONGDATE CS_LONGDATE,
  "PERSONID" INTEGER CS_INT)
```

I don't think the CS_LONGDATE and CS_INT should be included in the SQL. The internal column store engine datatype is derived from the database datatype, there is no value in adding this to the create table statement, it actually confuses people and might break something in future.

This is sufficient:
```
CREATE COLUMN TABLE "TRACKS" (
  "FILENAME" NVARCHAR(1000),
  "STARTTS" LONGDATE,
  "PERSONID" INTEGER)
```

**Comment by wernerdaehn** [comment]
@kai-morich @LarsBr May I get your point of view, please? Do I overlook something?

**Comment by kai-morich** [comment]
this is not a dbeaver bug.

This info is returned as column definition by the server, so it is ok that dbeaver shows it.
The CS_... types have been removed with HANA Cloud, so there you wont get these any more.

**Comment by LonwoLonwo** [comment]
Hello @wernerdaehn 
This is result of "CALL get_object_definition(container_name,table_name)" statement.

https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.hana/src/org/jkiss/dbeaver/ext/hana/model/HANAMetaModel.java#L183

We can't change it manually.

**Comment by wernerdaehn** [comment]
Thanks.
