### ISSUE TITLE
Meta refresh broken for non admin users

### ISSUE THREAD

**Issue by ceesvl** [dbeaver/dbeaver#11960]
Non admin users get a null pointer error when trying to do meta data refresh on Exasol database in any menu/F5 option.

It seems to me  that plugins/org.jkiss.dbeaver.ext.exasol/src/org/jkiss/dbeaver/ext/exasol/model/ExasolDataSource.java. the logic to retrieve a user has getUserHasDictionaryAccess return a non authorize error. A normal user cannot access this SYS table. Maybe it is better to do a:
SELECT PRIVILEGE
FROM SYS.EXA_SESSION_PRIVS
WHERE PRIVILEGE = 'SELECT ANY DICTIONARY';

This is a user table and when a result is retrieved it means that the user has DICTIONARY access to the SYS level tables.

Maybe it helps...

#### System information: 
- Windows server 2016 datacentre
- DBeaver version 21.0.1.202103211229
- All the standard one plus devstyle

#### Connection specification:
- Exasol 7.0.3 db driver 7.0.7
- Driver com.exasol.jdbc.EXADriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Steps to reproduce, if exist:
Default behavior

#### Include any warning/errors/backtraces from the logs
From meta query log
Error occurred during SQL script execution

Reason:
SQL Error [42500]: insufficient privileges for accessing view EXA_DBA_CONNECTIONS (Session: 1695571314942083073)

**Comment by LonwoLonwo** [comment]
Thanks for the bug report. 
We fixed this problem in scope with https://github.com/dbeaver/dbeaver/issues/12379
Fix will be available on 2021-05-31 in DBeaver 21.1.0
