### ISSUE TITLE
DBeaver tries to insert null to autogenerated column in data editor when row is empty

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#11971]
PostgreSQL 12, DBeaver EE 21.0.2-devel.

Suppose we have a table 

```sql
CREATE TABLE public.autogenerated_column (
    id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
    txt text NULL
);
```
Open the data editor and add a row that consists of two nulls. Insert fails with an error. But if we provide some not null value for `text` column, insertion proceed as normal.

**Comment by tati-kru** [comment]
Works as expected
