### ISSUE TITLE
Focus issues with custom enum editor in data editor

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#11975]
PostgreSQL 12, DBeaver EE 21.0.0, macOS 11.2.3.

Suppose we have a enum type and a table: 

```sql
CREATE TYPE "mood" AS ENUM (
    'sad',
    'ok',
    'happy'
);

CREATE TABLE mood_data (
    id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
    "time" timestamp NULL,
    "mood" "mood" NULL,
    CONSTRAINT mood_data_pkey PRIMARY KEY (id)
);
```

1. It's almost impossible to set a value of the `mood` column to the first value (`sad`).
2. When choosing a value in the enum combo, the focus stays on the combo even if we click on some other parts of the grid.

Those 2 things make it quite difficult to use enum combos on a grid.

**Comment by flambchap** [comment]
I need to clarify the nature of the problems.

StR.
1. Open data editor for the table above.
2. Add a new row. The row with 3 `null` values appears on the grid.
3. Double-click on the `mood` cell. Enum cell editor opens. The default value (`sad`) is set.

Issue 1: Click on some other cell on the grid. The cell editor closes, but the cell still has the value `null`.
Issue 2: Click on some part of the grid, but not on a cell. The cell editor does not close.

**Comment by flambchap** [comment]
Fixed the first issue. The second one needs to be extracted into a separate ticket with `xp:minor` label.

**Comment by Matvey16** [comment]
Verified
