### ISSUE TITLE
Tile layer definition saves without line delimeters

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#11976]
Add a tile layer with some fake definition like 
```
Invalid layer definition, line 0 
line 1 
line 2 
line 3
```
Save it, restart DBeaver and reopen the definition. Now it looks like this: 

```
Invalid layer definition, line 0 line 1 line 2 line 3
```

We need to save it with line delimeters, but also provide backward compatibility with already entered definitions.

**Comment by kseniiaguzeeva** [comment]
verified
