### ISSUE TITLE
Filters don't work for enum types 

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#11973]
PostgreSQL 12, DBeaver EE 21.0.0, macOS 11.2.3.

Suppose we have a enum type and a table: 

```sql
CREATE TYPE "mood" AS ENUM (
    'sad',
    'ok',
    'happy'
);

CREATE TABLE mood_data (
    id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
    "time" timestamp NULL,
    "mood" "mood" NULL,
    CONSTRAINT mood_data_pkey PRIMARY KEY (id)
);
```
Fill the table with data. Open the data editor and try to apply a filter on the `mood` column. Possible values for filtering will be duplicated, the data editor will be closed with an error when applying the filter.

**Comment by flambchap** [comment]
The bug is specific to PostgreSQL.

**Comment by flambchap** [comment]
It also seems that the only way to reproduce the bug is when this enum type is created in some non-public schema and this exact schema is set as default schema in the bootstrap settings. Everything points to a bug in PostgreExecutionContext.

**Comment by Matvey16** [comment]
Verified
