### ISSUE TITLE
Teradata: Trigger and procedure created with extra break lines

### ISSUE THREAD

**Issue by yan-hic** [dbeaver/dbeaver#11985]
Using 21.0.1

For instance, for a trigger created from a clean SQL in SQL Editor (I have enabled the whitespace view to highlight the line delimiters) as:
![image](https://user-images.githubusercontent.com/25224265/113523250-a7ddad80-9574-11eb-8a6c-066c0b41ab05.png)

shows in the table properties, under Triggers like so:
![image](https://user-images.githubusercontent.com/25224265/113522773-541d9500-9571-11eb-9bdb-4c78843ca280.png)

Querying `select requesttext FROM DBC.TriggersV where triggername = 'FillTxGrp'` shows indeed that the trigger was created with the extra lines.

As the default delimiter in `SQL Editor` is CRLF (configurable ?), it seems Teradata treats CRLF as 2 distinct line delimiters which creates an extra-line.
 
Resolution: DBeaver should replace CRLF's with LF's before sending to the driver. Or better, in case other DBMS are affected, make a new parameter in Preferences, Editors>SQL Editor>SQL Processing, Delimiters section e.g. "Replace CRLF with LF". I could not find anything in the JDBC driver to do the conversion.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by LonwoLonwo** [comment]
Fixed for views, procedures, triggers etc. in DBeaver 21.1.1

**Comment by DariaMarkaryan** [comment]
Verified
