### ISSUE TITLE
[Informix] Data viewer do not show data for tables in system DB.

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#11986]
DBeaver 21.0.2

After this fix https://github.com/dbeaver/dbeaver/issues/11590#issuecomment-810044898 https://github.com/dbeaver/dbeaver/commit/5d7ec5c96af2f281c0fd6462224da15946d91091 system databases in Informix do not show data for tables, because to read data from these tables, we need to use the name of the database on the path to the table. 
We need a better solution.

**Comment by LonwoLonwo** [comment]
Fixed for CE and EE version. Now "Omit catalog name" setting is false by default, but could be turned on in Driver settings.

![2021-04-06 13_06_01-Connection _stores_demo_ configuration](https://user-images.githubusercontent.com/45152336/113694862-f0ae7700-96d8-11eb-9c89-1820f28541af.png)

**Comment by uslss** [comment]
verified
