### ISSUE TITLE
Add new section "Format" in Edit menu.

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#11987]
![2021-04-05 11_43_56-Window](https://user-images.githubusercontent.com/45152336/113559247-b32ee880-9609-11eb-9201-d45c7397dc23.png)

**Comment by LonwoLonwo** [comment]
New section in Edit menu added.

![113588878-58ad8080-9639-11eb-9092-40c6bcf6dc50](https://user-images.githubusercontent.com/45152336/113685228-b213bf00-96ce-11eb-9406-4bb6fa630fdd.png)

Also with "Trim spaces" and "Morph to delimited list"

**Comment by uslss** [comment]
verified
