### ISSUE TITLE
Long running query finishes on the database and repeats by DBeaver 

### ISSUE THREAD

**Issue by dimkas78** [dbeaver/dbeaver#11992]
#### System information: 
- Operating system (distribution) and version - MS Windows 10 Pro 64 bit
- DBeaver version -  21.0.0.202102281712

#### Connection specification:
- Database name and version - Greenplum 6.14
- Driver name - PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I have a problem, which looks like  #7759, but not exactly same - 
in my case long running query finishes on then database and starts again by DBeaver.

I run a query with execution time over 2 hours - it's simple query "INSERT INTO... SELECT FROM ..."
All this time i'm looking to monitoring tool and after 7440 seconds of high level load on my cluster, I see that cluster's load drops. It means the query is finished and after few second DBeaver show me notification "Query is done".

But when I open DBeaver's window, I see that query time still ticking and after 2-3 seconds my cluster's load starts to grow again. So I press "Cancel" button and DBeaver immediatly(!) cancels the query.

After that I execute query "select count(*) from target_table_name" and receive exactly right number of rows, as expected.

In case of query's execution with no control, i had x3 and x4 result -  result data set multiply in 3 or even 4 times. Of course it takes x3-x4 time.

**Comment by p91paul** [comment]
Something similar happened to me as well. However, it was just once and I never reproduced it, but it was exactly as described. 
For me, it was on Oracle.

**Comment by kseniiaguzeeva** [comment]
Do you insert data using query in SQL Editor?
Could you please give me table DDL example and a query to reproduce.
Please send also log files https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by dimkas78** [comment]
Actually, I insert data from external table through PXF protocol, which is specific to Greenplum DB.
My query looks exactly like this:

`INSERT INTO target_table_name SELECT * FROM external_pxf_table;`

Maybe you can reproduce this problem using some another very slow (or big) data source.
I think it is only one special condition - query should run at least 30 minutes.

Part of DBeaver's log submitted below:
it's un-edited part of log file at time period from 2021-04-05 16:07:38 till 2021-04-05 18:33:45 - [part_of.log](https://github.com/dbeaver/dbeaver/files/6265561/part_of.log)

My comment to log timeline:
2021-04-05 16:07:38          - last typo error in previous query, left in file for completeness only.
2021-04-05 16:32 (est.)      - query executed - nothing special in log file - time mark given by monitoring tool chart.

... 1/2 hour passed ...

2021-04-05 17:00:18          - some troubles with connection in DBeaver GUI, nothing special in database load.

... 1/2 hour passed ...

2021-04-05 17:32:15 (est.) - query finished in DB, database load drops, DBeaver show notification "Query completed" (here i'm not sure about text of notification, maybe it was some error message, i missed it)
2021-04-05 17:32:30 (est.) - due to database load - query started again(?)

... 1 hour passed ...

2021-04-05 18:32:30 (est.) - query finished in DB, cluster load drops, DBeaver show notification "Query completed" (here i'm sure)
2021-04-05 18:33:00 (est) - database load grows again, I open DBeaver window and see that query's clock still ticking, and after some time press "Cancel" button 
2021-04-05 18:33:45.441 - in log - "canceling statement due to user request"

Picture from cluster monitoring tool: 
![GP_load_PFX_troubles](https://user-images.githubusercontent.com/61900705/113735200-b064ee00-9704-11eb-845d-14ca579f0dc7.png)

**Comment by uslss** [comment]
@dimkas78 you could try to disable Connection auto-recover enabled option in Preferences
![image](https://user-images.githubusercontent.com/31996417/116537126-7abfb900-a8ee-11eb-9aad-18ffe502aa99.png)

**Comment by dimkas78** [comment]
Thank you, @uslss!  I will try it certainly.

**Comment by tati-kru** [comment]
We shouldn't re-execute DML statements (insert, delete, update)

**Comment by serge-rider** [comment]
Fixed.
Queries INSERT, DELETE, UPDATE, SELECT INTO now won't be re-executed after connection errors.

**Comment by uslss** [comment]
verified
