### ISSUE TITLE
postgresql Unable to create array

### ISSUE THREAD

**Issue by acodervic** [dbeaver/dbeaver#11995]
postgresql Unable to create array 

#### System information: 
- ubuntu 20
![深度截图_选择区域_20210406104506](https://user-images.githubusercontent.com/57204004/113652003-9b1c9f00-96c5-11eb-891a-9e19fb9ca3cf.png)

- untimate 21.0.0.0
 
When I try to create a new table or modify the original table fields, an error occurs

**Comment by LonwoLonwo** [comment]
Hello @YU5Z8X2CvH1fv4ep 
Thanks for the bug report. We will fix it.

As workaround, you can turn on setting for reading all PostgreSQL data types, including array types.
In connection settings -> PostgreSQL tab -> "Read all data types"

![2021-04-06 11_29_28-DBeaver Enterprise 21 0 2 - NewTable](https://user-images.githubusercontent.com/45152336/113682347-b9859900-96cb-11eb-97d4-8c13168d721d.png)

![2021-04-06 11_30_05-Connection _dvdrental_ configuration](https://user-images.githubusercontent.com/45152336/113682351-ba1e2f80-96cb-11eb-84a3-c8ff6954e73d.png)

**Comment by acodervic** [comment]
> 您好@ YU5Z8X2CvH1fv4ep
> 感谢您的错误报告。我们将修复它。
> 
> 解决方法是，您可以打开设置以读取所有PostgreSQL数据类型，包括数组类型。
> 在连接设置-> PostgreSQL选项卡->“读取所有数据类型”
> 
> ![2021-04-06 11_29_28-DBeaver Enterprise 21 0 2-新表](https://user-images.githubusercontent.com/45152336/113682347-b9859900-96cb-11eb-97d4-8c13168d721d.png)
> 
> ![2021-04-06 11_30_05-连接dvdrental配置](https://user-images.githubusercontent.com/45152336/113682351-ba1e2f80-96cb-11eb-84a3-c8ff6954e73d.png)

it  works! thanks!
