### ISSUE TITLE
Field Mapping Dialog: Field Order

### ISSUE THREAD

**Issue by jimrandell** [dbeaver/dbeaver#12001]
_Hello and thanks for your time. I don't know if this is a Bug or a Feature Request.  I hope this isn't a duplicate issue, I have searched the docs and issues boards but could not find an answer._

#### System information: 
- Operating system Microsoft Windows [Version 10.0.19041.867]
- DBeaver version  21.0.0.202103102007
- Java version 11.0.5
- No Additional extensions

#### Connection specification:
- MariaDB 10.5.8-MariaDB
- Driver mariadb-java-client-2.7.1

#### Describe the problem you're observing:
 - Import Field Mapping Dialog only displays fields in order created, not alpha-sorted
   - in the Map Columns Dialog, I see no way to sort the columns.
   - I have tables with Hundreds of Fields and Target Tables with just a dozen or so. 
   - I am having a very hard time finding the source columns for which I want to select a target
#### Steps to reproduce, if exist:
 - ### I right click on a Table in the Database Browser, and select Import Data
 ![image](https://user-images.githubusercontent.com/3543506/113688114-e8e2d880-96c0-11eb-8566-2cb1515c6cd8.png)
- ### I select Source Type (database tables)
![image](https://user-images.githubusercontent.com/3543506/113688500-4545f800-96c1-11eb-8e62-d985e06aa511.png)
- ### I select the input source  
![image](https://user-images.githubusercontent.com/3543506/113688816-91913800-96c1-11eb-9c9f-1b197a8fb003.png)
- ###  I click the Columns Button in the Data Transfer dialog 
![image](https://user-images.githubusercontent.com/3543506/113689069-d1f0b600-96c1-11eb-94c4-1152513912af.png)
- ### in the Map Columns Dialog...I need the Source Columns alpha sorted, I see no way to do that. I have tables with Hundreds of Fields and Target Tables with just a dozen or so. I am having a very hard time finding the source columns for which I want to select a target
![image](https://user-images.githubusercontent.com/3543506/113689952-c782ec00-96c2-11eb-8e88-91c6a9ef744d.png)

**Comment by uslss** [comment]
thank you for suggestion

**Comment by ShadelessFox** [comment]
Implemented:

![image](https://user-images.githubusercontent.com/35821147/124252915-2922ed00-db30-11eb-83c7-641f456ed6d2.png)

Now you can click on the column's header to change its ordering.

**Comment by uslss** [comment]
verified
