### ISSUE TITLE
Can not edit result cell.

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#12008]
#### System information: 
- Windows 10.
- Dbeaver 21.0.2

#### Connection specification:
- Oracle 18c
- Jdbc

There is a problem when modifying the data result grid after Dbeaver 21.0.2 update.
If a column is specified in the SELECT statement, it cannot be modified. If the entire column is specified (*), it can be modified.
It was a problem that didn't exist in previous versions.

Please refer to the attached file.

Thank you for reading.  :)
## Dbeaver 21.0.2
![cannt_edit_21_0_2](https://user-images.githubusercontent.com/59002295/113792038-ec896480-977f-11eb-834d-067c1d27ff38.gif)

## Dbeaver 21.0.1
![can_edit_21_0_1](https://user-images.githubusercontent.com/59002295/113791967-c8c61e80-977f-11eb-85e3-6eff409f5003.gif)

**Comment by serge-rider** [comment]
Seems to be a side effect of #11194

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
