### ISSUE TITLE
Check for update option is throwing  as "Perhaps the network connection is down?" in DBeaver Community 21.0.2 & 21.1.2

### ISSUE THREAD

**Issue by Pranithaevana** [dbeaver/dbeaver#12016]
We are trying to deploy DBeaver Community 21.0.2 firm wide.  I could see the attached error when i click on "Help" -> "check for updates" 

![error for DBeaver](https://user-images.githubusercontent.com/82090197/113847686-56703100-97b5-11eb-8549-f1359aaa98a0.JPG)

It should ideally say that there are no updates when we click on check for updates. 
![DBeaver previous verion](https://user-images.githubusercontent.com/82090197/113848329-faf27300-97b5-11eb-909d-bc31ec5ccdc4.JPG)
 Attaching the screenshot of previous version, 

Could you please check and suggest us.

**Comment by uslss** [comment]
@Pranithaevana could you provide [debug log](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by uslss** [comment]
there is no update on an issue for a long time. 
if it is still actual for you - feel free to reopen it with additional info.
