### ISSUE TITLE
Time selection plugin for the field in the time format

### ISSUE THREAD

**Issue by lzb-libra** [dbeaver/dbeaver#12010]
Hello, developers of dbeaver, I am a loyal user of dbeaver, but recently I found some places that are not very traversed during the process of using it. I will list two for the time being
1. The data exported by dbeaver is not exported to excel, or the function is hidden too deeply, I haven't found it.
2. I hope to add a time selection plug-in to the field in the time format. I always feel that it is much more convenient to select the time through the plug-in than to enter it manually.

**Comment by p91paul** [comment]
for 1, you need to install office plugin. 
https://github.com/dbeaver/dbeaver/wiki/Optional-extensions

The EE version also includes it by default.

**Comment by lzb-libra** [comment]
Thanks for your answer, my first question has been perfectly solved

**Comment by scruel** [comment]
For 2, I really need this function, and hope it to build in rather than plugin.

**Comment by lzb-libra** [comment]
For 1 function, I followed your suggestion and installed the office plug-in. It works well, but every time I update DBeaver, the installed office plug-in is gone. I need to reinstall it. I hope every time I can keep the plug-ins I installed when updating DBeaver, thank you.

**Comment by Matvey16** [comment]
Value panel presentations work independently from each other, It can be very confusing and lead to mistakes in user cases.

![dbeaver_wAMwyU122E](https://user-images.githubusercontent.com/82543000/149350642-0ef81d01-c7ff-439f-a755-c4d85e3a1323.gif)

**Comment by lzb-libra** [comment]
I hope I can use the plug-in directly in the form instead of opening a panel to operate, which undoubtedly increases my operation steps, and I hardly use this panel

**Comment by Destrolaric** [comment]
@lzb-libra Hi, you can use time editor in inline mode, or by hitting ctrl+enter combination, you summon dialog in which you are able to edit variables.

**Comment by lzb-libra** [comment]
@Destrolaric Hi, In my dbeaver version, the community does not respond to pressing Ctrl + enter. Does this version not have this function

**Comment by Destrolaric** [comment]
@lzb-libra Sorry got a typo, shift+enter is the correct combination

**Comment by lzb-libra** [comment]
@Destrolaric Thanks, but I only use this panel when there are a lot of contents in the field. After entering this panel, I still can't find the time selection plug-in. The time selection plug-in I said is similar to this

**Comment by lzb-libra** [comment]
@Destrolaric Thank you, but I only use this panel when viewing the contents of large fields. There is still no time plug-in I need in this panel. The plug-in I want is like the one shown in the picture. Won't community provide it in this version
![QQ截图20220114163945](https://user-images.githubusercontent.com/63389341/149483623-dc0a1bb1-cf6e-40d6-a654-2248c4d694a7.png)
![QQ图片20220114164056](https://user-images.githubusercontent.com/63389341/149483634-5e8a212f-e838-4063-8c7a-938c2422f638.jpg)

**Comment by lzb-libra** [comment]
In fact, this function is not particularly needed. The main thing is that dbeaver has to download the plug-in again after each update

**Comment by uslss** [comment]
feature request accordingly to plugin could be tracked here #5317

**Comment by lzb-libra** [comment]
Thanks for your advice

**Comment by Matvey16** [comment]
Value synchronizes when changing from calendsr to text. but not the other way around

**Comment by serge-rider** [comment]
Calendar presentation doesn't work in case of native date/time formatting (depends on native format of course). It is expected behavior.
Error dialog must be shown if date format can't be parsed.

**Comment by Matvey16** [comment]
Verified
New ticket opened to include a warning #15224
