### ISSUE TITLE
It will be great not to clean /usr/share/dbeaver/dbeaver.ini after update

### ISSUE THREAD

**Issue by p0m1d0rka** [dbeaver/dbeaver#12018]
Hello!
I ussually add in **/usr/share/dbeaver/dbeaver.ini**  line **-Duser.timezone=UTC**
It works fine, but after every update I should again add this like because this file resets to default state = (
Can you merge or save old dbeaver.ini after update?

My update path:
- download dep package 
- sudo dpkg -i dep_package

TY

**Comment by uslss** [comment]
duplicates #7727
