### ISSUE TITLE
Procedures with multiple result tables - Very important for SAP Hana

### ISSUE THREAD

**Issue by wernerdaehn** [dbeaver/dbeaver#12012]
#### System information: 
- Win 10
- DBeaver 21.0.0

#### Connection specification:
- SAP Hana

#### Describe the problem you're observing:
In SAP Hana almost all procedures have multiple output parameters of type table. When I call such like this one

```
CALL "PUBLIC"."GET_REMOTE_SOURCE_OBJECT_TREE" ('DATALAKE_RTDI','',?,?);
```

in DBeaver, the first table parameter is shown but the second is not.

While less common in other databases, it can happen there as well!

For reference, Hana Studio shows all.

![image](https://user-images.githubusercontent.com/13607767/113825473-4b031280-9781-11eb-92ba-00622b2a3e17.png)

My guess is, the getMoreResults() JDBC call is not used.

```
CallableStatement stmt = connection.prepareCall("{CALL GET_REMOTE_SOURCE_OBJECT_TREE" ('DATALAKE_RTDI','',?,?)}"); 
boolean moreResults = stmt.execute();
while (moreResults) {
    ResultSet rs = stmt.getResultSet();
    // do something
    rs.close();
    moreResults = stmt.getMoreResults();
} 
stmt.close();   
```

**Comment by kai-morich** [comment]
_FYI:_ works with multiple implicit results, so looks only like an issue with multiple out parameters

![grafik](https://user-images.githubusercontent.com/25850372/114142081-bc25ff80-9912-11eb-864c-887261c41df4.png)

**Comment by kai-morich** [comment]
for reproduction here a simpler test case:

    CREATE OR replace PROCEDURE proc1 (OUT tab1 sys.dummy, OUT tab2 sys.dummy) AS BEGIN
        tab1 = SELECT 'A' AS dummy FROM dummy;
        tab2 = SELECT 'B' AS dummy FROM dummy;
    END;

    CALL proc1(?,?)

**Comment by uslss** [comment]
cannot reproduce it against 21.0.4 EA
![image](https://user-images.githubusercontent.com/31996417/116540429-cd02d900-a8f2-11eb-9de9-0f640a7b58b4.png)

**Comment by kai-morich** [comment]
I also couldn't reproduce it any more. looks like it somehow has been fixed

**Comment by wernerdaehn** [comment]
Summary: "How can I output scalar output variables for Hana?" Please execute the following command on our test server: 
`CALL "PUBLIC"."GET_REMOTE_SOURCE_OBJECT_TREE" ('FILESOURCE','',?,?);`



Detail:

Interesting. I just tried with `call proc1(?,?)` as well and it worked as well, even I have not upgraded the DBeaver installation.
The variant with implicit result sets worked as well, I have created a proc2 procedure in our Hana test server in addition.

Still, the `CALL "PUBLIC"."GET_REMOTE_SOURCE_OBJECT_TREE" ('DATALAKE_RTDI','',?,?);` does not. So there must be another difference between our test cases.

To make it easier for you, I have installed SDI on our test server and just executed as dbeaver_normal user the command.

```
CALL "PUBLIC"."GET_REMOTE_SOURCE_OBJECT_TREE" ('FILESOURCE','',?,?);
```


<br>

Result is a single table.

![image](https://user-images.githubusercontent.com/13607767/116549121-68954900-a8f5-11eb-8669-760955a942d3.png)



<br>

In Hana Studio it shows two tabs:

![image](https://user-images.githubusercontent.com/13607767/116549672-10ab1200-a8f6-11eb-91c3-8b9ada194650.png)


When I look at the procedure definition:

```
CREATE PROCEDURE GET_REMOTE_SOURCE_OBJECT_TREE
(IN REMOTE_SOURCE_NAME NVARCHAR(256), 
IN UNIQUE_NAME NVARCHAR(5000), 
OUT IS_STATEFUL TINYINT, 
OUT IS_PARTIAL TINYINT) AS BUILTIN
```

So as you see, the second tab is showing the scalar values, it is not a second out table as such!

Hence the issue text is wrong and should rather be "How can I output scalar output variables for Hana?"

**Comment by kai-morich** [comment]
here a simple testcase

    CREATE OR replace PROCEDURE proc1 (OUT tab1 sys.dummy, OUT tab2 sys.dummy, OUT val1 int, OUT val2 int) AS BEGIN
        tab1 = SELECT 'A' AS dummy FROM dummy;
        tab2 = SELECT 'B' AS dummy FROM dummy;
        val1 = 42;
        val2 = 43;
    END;
    
    CREATE OR replace PROCEDURE proc2 (OUT val1 int, OUT val2 int) AS BEGIN
        val1 = 42;
        val2 = 43;
    END;
    
    CALL proc1(?,?,?,?);
    CALL proc2(?,?);

scalar results are shown at proc2 but not at proc1

**Comment by ShadelessFox** [comment]
Fixed:
![idea64_j4KWmKplHV](https://user-images.githubusercontent.com/35821147/123423132-d42f2600-d5c7-11eb-95ff-fc071e8523cd.png)

As a bonus, fixed for DB2 (same problem):
![image](https://user-images.githubusercontent.com/35821147/123792136-f63ae800-d8e8-11eb-8b67-b7fef3bdf079.png)

**Comment by uslss** [comment]
verified
