### ISSUE TITLE
Code Completion Incorrectly Suggests SQL Objects Within String Literals

### ISSUE THREAD

**Issue by jetzerb** [dbeaver/dbeaver#12028]
#### System information: 
- Windows 10
- DBeaver version 21.0.2.202104042040
- No additional extensions

#### Connection specification:
- Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)
- SQL Server
- No tunnels or proxies (SSH, SOCKS, etc)

#### Describe the problem you're observing:
When typing a string literal, code completion offers column names and functions/procs as suggestions. This is almost never helpful.
There is one situation where code completion is appropriate though.  I hadn't even known DBeaver could do this, but it does offer string literal values under certain circumstances, and should continue to do so.

#### Steps to reproduce, if exist:
Example queries below.  Any tables/views will do; I'm just using INFORMATION_SCHEMA views because they exist in many RDBMSs:
```sql
select * from INFORMATION_SCHEMA.CHECK_CONSTRAINTS where CHECK_CLAUSE = 'TYPE SOMETHING HERE';
select 'TYPE SOMETHING HERE' from INFORMATION_SCHEMA.CHECK_CONSTRAINTS;

-- Sometimes it's appropriate to offer suggestions
-- Here, TABLE_TYPE can be either "BASE TABLE" or "VIEW"
select * from INFORMATION_SCHEMA.TABLES where TABLE_TYPE = 'vi'
```
![image](https://user-images.githubusercontent.com/36859020/113898031-17c87f80-9791-11eb-9eda-cfe3a63b026f.png)
![image](https://user-images.githubusercontent.com/36859020/113898040-1bf49d00-9791-11eb-9f63-68f4c2e1f69f.png)
![image](https://user-images.githubusercontent.com/36859020/113898988-f9af4f00-9791-11eb-8417-cd78dd46421b.png)

**Comment by serge-rider** [comment]
Thanks for the bug report. It is a side effect of #11379 fix

**Comment by kseniiaguzeeva** [comment]
verified
