### ISSUE TITLE
[PostgreSQL] return main array types in data types list.

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#12036]
PostgreSQL is a special database that has a huge list of data types. 
Now we read standard data types (int4, varchar, time etc.), add aliases (like serial) and user data types.
Yo can enable reading of all data types in connection settings.

Now we need to return to the main list of types - basic array data types (_int4, _varchar, _time etc.).

**Comment by LonwoLonwo** [comment]
Implemented. Also array types is now in the end of possible data types list for the column.

**Comment by kseniiaguzeeva** [comment]
verified
