### ISSUE TITLE
Syntax highlighting for local variables in SAP ASE and SAP IQ

### ISSUE THREAD

**Issue by zolovey** [dbeaver/dbeaver#12037]
Please implement highlighting of local variables for SAP ASE and SAP IQ

Local variables have @ (at) sign in the front of the variable name

[SAP documentation on local variabes](https://help.sap.com/viewer/a898e08b84f21015969fa437e89860c8/LATEST/en-US/a50dbfab84f21015b2e4da36a3467308.html)

Example:
```sql
BEGIN
	DECLARE @local_var INT ;
	SET @local_var = 10 ;
	SELECT @local_var;
END
```

**Comment by LonwoLonwo** [comment]
Thanks for suggestion!

**Comment by ShadelessFox** [comment]
Implemented:

![java_LZylyPFhP2](https://user-images.githubusercontent.com/35821147/123285162-7b9f5080-d515-11eb-8083-c8d22fe5e644.png)

**Comment by Matvey16** [comment]
Using `#` symbol in the name breaks the highlighting

![2021-06-30_09h21_39](https://user-images.githubusercontent.com/82543000/123911973-246e0580-d985-11eb-9a0f-10ac6a682c3c.png)

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
Verified
