### ISSUE TITLE
Wrong formatting if there are comments in the SQL statement

### ISSUE THREAD

**Issue by qiqingli** [dbeaver/dbeaver#12032]
#### System information: 
- Operating system (distribution) and version：macOS Big Sur 11.2.3
- DBeaver version: 21.0.2
- Java version: AdoptOpenJDK (build 11.0.10+9)

#### Connection specification:
- Database name and version：Oracle 12c
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/20805098/113951362-05f4e400-9846-11eb-8a73-6b0ea6b8a38c.png)

![image](https://user-images.githubusercontent.com/20805098/113952441-3e95bd00-9848-11eb-93cd-64e80ebf14cd.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by flambchap** [comment]
Hi @qiqingli. Could you please tell me how to achieve the effect on the second picture? Thanks.

**Comment by qiqingli** [comment]
> Hi @qiqingli. Could you please tell me how to achieve the effect on the second picture? Thanks.
No spaces between SELECT and * reproduces the problem

**Comment by flambchap** [comment]
As far as I understand, this is a syntactic error, and I am not convinced that SQL formatter should fix them.

**Comment by qiqingli** [comment]
But the SQL statement can be executed correctly, and it is not considered a syntax error

**Comment by flambchap** [comment]
Ok, I agree, will fix that as well.

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
First column after comment is not aligned
![2021-06-29_15h33_56](https://user-images.githubusercontent.com/82543000/123798428-d5c25c00-d8ef-11eb-82f5-7ce985390223.gif)

**Comment by Matvey16** [comment]
Verified
