### ISSUE TITLE
Allow MFA

### ISSUE THREAD

**Issue by N1GHTR4NG3R** [dbeaver/dbeaver#12049]
**Describe the solution you'd like**
When I tried to connect to my database, through SSH, I was unable to connect due to an extra layer of security, mainly google authenticator, even with a user that has google authenticator disabled, due to the server still "Checking" and matching the user to permissions.

It would be really good if dbeaver allowed for MFA, checking for keyboard_interactive AFTER the SSH keys have been accepted. This way, It could allow the user to input the code and then connect to the database.

**Describe alternatives you've considered**
None available without reconfiguring my server security and dropping the google_authenticator.so PAM module. Unfortunately, currently tied into paid closed source alternatives.

**Comment by uslss** [comment]
seems it is implemented in the scope of #5754 .
will be available in 21.0.3
does it fit your needs?
