### ISSUE TITLE
Hyperlink doesn't appear for table names with spaces

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12043]
#### System information: 
- Operating system (distribution) and version Mac Big Sur
- DBeaver version DBeaver 21.0.2

#### Steps to reproduce, if exist:
1. Write a select query in SQL Editor for table with a space in its name e.g. PostgreSQL.postgres.test_review
`SELECT * FROM "test_ fk";`
2. Hold Ctrl/Cmd and hover over the table name

**Expected:** the table hyperlink appears and table can be opened by pressing on it
**Actual result:** hyperlink doesn't appear

https://user-images.githubusercontent.com/51405061/114002538-a0b0eb00-9865-11eb-9911-132659c1f16f.mov

**Comment by dizzygit** [comment]
Few more problems with table (and column) names containing spaces:
- double clicking on one word at "TEST TABLE" selects only this word, not whole table name
- F4 (Open declaration) on selected table name in editor searches only by first word: F4 on selected "TEST TABLE" will open declaration of table named TEST (if it exists)
This applies to table names with double quote: "TEST TABLE" as well as square brackets: [TEST TABLE] (MS SQL Server)

**Comment by flambchap** [comment]
Unfortunately, I haven't found an easy solution. Currently, when we place the cursor on some name in the editor and press CTRL, we go to the left until we find a 'non-word character', and then to the right, again, until we find another 'non-word character'. After that, we try to resolve the object which name is contained between those two chars. (see `SQLIdentifierDetector.detectIdentifier())`.

We can't extend this algorithm, though. Space is a valid identifier character if an identifier is quoted. However, consider the following situation: `"some db"."some sch|ema"."some table"` (where | is the current cursor position). To resolve this identifier, we need something more elaborate, like the techniques we use in autocomplete.

**Comment by E1izabeth** [comment]
Implemented in scope of #15886
