### ISSUE TITLE
Auto-completion doesn't work for column names with spaces

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12044]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.0.2

#### Steps to reproduce, if exist:
Write a query with a space in a column name and try to auto-complete a column value. E.g. in PostgreSQL postgres.test_review `SELECT * FROM sal s where "test space" =;`

**Expected**: column values appear in auto-suggestion list
**Actual result**: table columns appear in auto-suggestion list

https://user-images.githubusercontent.com/51405061/114003691-a0fdb600-9866-11eb-8f6c-77dfa50f1b88.mov

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
