### ISSUE TITLE
Empty .dbeaver folders created in eclipse projects

### ISSUE THREAD

**Issue by sebthom** [dbeaver/dbeaver#12059]
This is a followup issue to #10507

System information:
- Operating system (distribution) and version: Microsoft Windows [Version 10.0.19042.870]
- DBeaver IDE	21.0.2.202104042040
 
Describe the problem you're observing:
- I installed dbeaver into Eclipse IDE for Java Developers eclipse-java-2021-03-R-win32-x86_64.zip
- now dbeaver generates empty .dbeaver folders in all projects no matter. When I delete them they get recreated and press F5 (refresh) the folder gets automatically recreated.

Steps to reproduce, if exist:
- download latest Eclipse IDE for Java Developers [eclipse-java-2021-03-R-win32-x86_64.zip](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2021-03/R/eclipse-java-2021-03-R-win32-x86_64.zip)
- install DBeaver IDE via market place
- clone e.g. this project into the workspace https://github.com/vegardit/await.sh

![image](https://user-images.githubusercontent.com/426959/114164098-34002400-992b-11eb-87fb-a88bc796b09c.png)

The project has no natures configured:
![image](https://user-images.githubusercontent.com/426959/114164274-63169580-992b-11eb-96a9-594d0f68b9ae.png)

![image](https://user-images.githubusercontent.com/426959/114164193-4ed29880-992b-11eb-9126-fa3e3b7d658b.png)

Eclipse Log:
[eclipse.log](https://github.com/dbeaver/dbeaver/files/6284897/eclipse.log)

**Comment by uslss** [comment]
@sebthom could you provide [dbeaver debug log](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by sebthom** [comment]
@serge-rider @uslss
So I debugged DBeaver. The problem is that DBeaver creates a `ProjectMetadata$ProjectSyncJob` for all projects in the Eclipse workspace. When a file in any project is deleted that job is triggered.

![image](https://user-images.githubusercontent.com/426959/117725257-2ddcbc00-b1e5-11eb-9bdb-11880ef12c32.png)

Which will result in the execution of:
![image](https://user-images.githubusercontent.com/426959/117725472-7ac09280-b1e5-11eb-8a04-a8415522efb5.png)

which in turn will create the `.dbeaver` folder:

![image](https://user-images.githubusercontent.com/426959/117725544-8f9d2600-b1e5-11eb-9176-37751c26751c.png)

So if you can change
```java
ContentUtils.makeFileBackup(new File(getMetadataFolder(true), METADATA_STORAGE_FILE));
```
to
```java
ContentUtils.makeFileBackup(new File(getMetadataFolder(false), METADATA_STORAGE_FILE));
```
that should solve the issue.

**Comment by serge-rider** [comment]
@sebthom Thank you for the investigation 👍 
Now I can reproduce it.
You are right, we should't create metadata folder there.
Also this fliushMetadata function mustnt't be called for every file delete in every project.
