### ISSUE TITLE
MySQL shows duplicate table

### ISSUE THREAD

**Issue by geforce2k3** [dbeaver/dbeaver#12057]
#### System information: 
- Operating system (distribution) and version : Windows 10 Pro 20H2(19042.867)
- DBeaver version : 21.0.2.202104042040
- Java version : 
openjdk version "1.8.0_212-1-ojdkbuild"
OpenJDK Runtime Environment (build 1.8.0_212-1-ojdkbuild-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
- Additional extensions: No

#### Connection specification:
- Database name and version: MySQL 5.7.32
- Driver name: com.mysql.cj.jdbc.Driver 8.0.17
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Some of database's table shows duplicate table

#### Steps to reproduce, if exist:
expand any database from mysql, some of db's table will show duplicate.
![error](https://user-images.githubusercontent.com/46662953/114159757-b9e69400-9958-11eb-8748-d4bfac9628fb.png)

**Comment by LonwoLonwo** [comment]
Hello @geforce2k3 
Can you please try to execute this query for your database:
`SHOW FULL TABLES FROM koloko50th`
Are there duplicates in the list received?

**Comment by geforce2k3** [comment]
OK, seems like it's Azure mySQL bug, the following link for reference. In the last section, there is a MS guy said is a bug.
Need to reboot server
https://docs.microsoft.com/en-us/answers/questions/322028/duplicate-tables-being-created-in-azure-mysql-data.html

But my coworker use Heidisql is ok without this issue, it's bit of weird.

**Comment by LonwoLonwo** [comment]
Will you help reboot server? The problem disappeared?

**Comment by geforce2k3** [comment]
Unfortunately, as I am not the DBA or SYSAdmin, so I can't do that, have to wait maintenance.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
