### ISSUE TITLE
Changing a user's password does not correctly escape all characters

### ISSUE THREAD

**Issue by sig-steve** [dbeaver/dbeaver#12053]
#### System information: 
- Ubuntu 20.10
- DBeaver: 21.0.1.202103211229
- Additional extensions: None as far as I'm aware

#### Connection specification:
- MariaDB 10.1
- MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:

Changing the password on a user does not correctly escape all characters.

#### Steps to reproduce, if exist:

Connect to a database and view a user.
Change the password to something containing a '\' character, e.g. 'a\b'
Persist changes
Try to log in as that user with the password 'a\b' - it fails.

#### Include any warning/errors/backtraces from the logs

The Persist Changes SQL preview box shows the query as:
```sql
SET PASSWORD FOR 'user'@'%' = PASSWORD('a\b');
```
The query should be
```sql
SET PASSWORD FOR 'aqa'@'%' = PASSWORD('a\\b');
```

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
verified
