### ISSUE TITLE
Add option to hide DBeaver menu entries from non-DBeaver perspectives

### ISSUE THREAD

**Issue by sebthom** [dbeaver/dbeaver#12061]
**Is your feature request related to a problem? Please describe.**
DBeaver adds two Top Level menu (Database, SQL Editor) entries to all perspectives.
This clutters the UI unnecessarily esp. if other plugins are installed that contribute menu items to specific perspectives.

**Describe the solution you'd like**
There should be an option that makes menu contributions perspective aware, meaning they are only added to the DBeaver perspective.

**Describe alternatives you've considered**
I cannot see any alternative.

**Additional context**
![image](https://user-images.githubusercontent.com/426959/114166087-935f3380-992d-11eb-8374-c8e83951654d.png)

**Comment by serge-rider** [comment]
Yep. We had to do this long time ago
