### ISSUE TITLE
Error with special characters in "Open Database Object"

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#12063]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 21.0.1.202103211229
- Additional extensions n/a

#### Connection specification:
- Database name and version: Oracle 11
- Driver name: ojdbc19
- Do you use tunnels or proxies (SSH, SOCKS, etc)? n/a

#### Describe the problem you're observing:
If I, by mistake, insert a ( or ) symbol in my search string for Ctrl+Shift+D, I get the error in the screenshot
![immagine](https://user-images.githubusercontent.com/2157006/114178486-14262b80-993e-11eb-86c4-2fac8aeed4f5.png)

I'm aware looking for parenthesis in object names is a bad idea (in most databases at least), but in my keyboard (US) ( and ) are next to * and _, which are quite legitimate, and a small typo results in this modal error which is quite annoying.
Same applies to [ and {

Something funny happens with |... if I write "bxufbadifjdj|", the result is the same as if I had written "b" only

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
verified
