### ISSUE TITLE
Upgrade Java to 11.0.11

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#12067]
We need to upgrade Java bundle to the latest compatible version (11.0.9) + include jdk.httpserver module.
Already done for Windows, need to update MacOS and Linux bundles.

**Comment by serge-rider** [comment]
All JDK bundles upgraded to AdopOpenJDK 11.0.11.
Nashorn module removed (deprecated). Root CA updated.

Must be tested on Windows, Linux and MacOS

**Comment by Matvey16** [comment]
Verified on Windows and Linux

**Comment by kseniiaguzeeva** [comment]
Verified on Mac
