### ISSUE TITLE
[mysql] incorrect handling of stored procedure and function with the same name

### ISSUE THREAD

**Issue by buttha** [dbeaver/dbeaver#12070]
- Operating system (distribution) and version: Debian 10
- DBeaver version: 21.0.2
- Database name and version: mysql 8.0.23
- Driver name: MySQL

If there are one stored procedure and one function with the same name, you could loose function while editing the procedure.

1) create "test" PROCEDURE

```
DELIMITER $$
$$
CREATE PROCEDURE testdb.test()
BEGIN
END$$
DELIMITER ;
```

2) create "test" FUNCTION

```
DELIMITER $$
$$
CREATE FUNCTION testdb.test()
RETURNS INT
DETERMINISTIC
BEGIN
	RETURN 0;
END$$
DELIMITER ;
```

3) open the procedure, edit and save. CTRL+S generates the correct code:

```
DROP PROCEDURE IF EXISTS testdb.test;

DELIMITER $$
$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `testdb`.`test`()
BEGIN
	# test
END$$
DELIMITER ;
```

4) edit the procedure again and press CTRL+S.... boom:

DROP **FUNCTION** IF EXISTS testdb.test;

DELIMITER $$
$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `testdb`.`test`()
BEGIN
	# test 1
END$$
DELIMITER ;

As you can see the second time you save, there is a DROP FUNCTION and CREATE PROCEDURE, so "test" function is deleted.

**Comment by uslss** [comment]
thanks for the report

**Comment by Matvey16** [comment]
Verified
