### ISSUE TITLE
DBeaver: Execute SQL text generate error if the ";" delimiter together with "GO" separator is used with BEGIN/END

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#12078]
DBeaver - **Version 21.0.2 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

When I execute SQL Text containing both "**;**", "**GO**" and BEGIN/END, I get an error.

Seems that _DBeaver_ do not consider **BEGIN**/**END** statements that contain statement(s) that each contain a trailing ";" charater. See **TEST 6** below for an example (also read comment for **TEST 3** in the importance of seperate batches when "GO" is used).

**PS**. The practise to place a trailing ";" character to mark end-of-statement is now something that Microsoft recommends.

**My _DBeaver_ settings** (Editors -> SQL Editor -> SQL Processing -> Delimiters)
```
Statement delimiter: ;
  Ignore native delimiter
X Blank line i statement delimiter
X Remove Trailing query delimiter
```
**TEST SETUP - OK (if run as script)**
```
IF OBJECT_ID('dbo.TestTableOne', 'U') IS NOT NULL
  DROP TABLE dbo.TestTableOne;
IF OBJECT_ID('dbo.TestTableTwo', 'U') IS NOT NULL
  DROP TABLE dbo.TestTableTwo;
GO
CREATE TABLE TestTableOne(Id INTEGER, Value VARCHAR(40));
GO
INSERT INTO TestTableOne VALUES (1, 'A');
GO
CREATE TABLE TestTableTwo(Id INTEGER, Value VARCHAR(40));
GO
INSERT INTO TestTableTwo VALUES (2, 'B');
GO
```
**TEST 1 - OK (if executed as script or statement)**
Here _DBeaver_ work ok in noticing the ";" character as statement separator. So if I place the cursor on the first line and execute, only the first line is executed. If I select all lines and execute I also correctly get two tabs (ie two result sets).
```
SELECT * FROM TestTableOne;
SELECT * FROM TestTableTwo;
```
**TEST 2 - OK (if executed as script or statement)** 
Here _DBeaver_ work ok in noticing the empty line as statement separator. So if I place the cursor on the first line and execute, only the first line is executed. If I select all lines and execute I also correctly get two tabs (ie two result sets).
```
SELECT * FROM TestTableOne

SELECT * FROM TestTableTwo
```
**TEST 3 - OK (if executed as script), SQL ERROR (if executed as statement)**
That I get an error if I try to execute these lines as a statement,  is ok I guess, since this is more like a script.

Here _DBeaver_ should first send "**SELECT * FROM TestTableOne;**" to the SQL Server as one batch, then send the "**SELECT * FROM TestTableTwo;**" as the second batch to the SQL Server.

It is important that _DBeaver_ don't send all the text to the SQL Server in one batch. This have no effect here, but if I have script with batch 1 creating a table and batch 2 inserting values into the table the two batches **must** be sent as two different batches.
```
SELECT * FROM TestTableOne;
GO
SELECT * FROM TestTableTwo;
GO
```
**TEST 4 - OK (if executed as statement), SQL ERROR (if executed as script),**
That I get an error if I try to execute these lines as a script,  is ok I guess, since this is more like a statement.
```
DECLARE @TestVal INTEGER = 1;

IF @TestVal = 1
BEGIN
  SELECT * FROM TestTableOne;
END;
```
**TEST 5 - OK (if executed as script)**
Here I have not put any ";" training characters on the statements in the BEGIN/END section.
```
IF OBJECT_ID('dbo.OnTestTableOneUpdate', 'TR') IS NOT NULL
  DROP TRIGGER dbo.OnTestTableOneUpdate;
GO
CREATE TRIGGER dbo.OnTestTableOneUpdate
  ON dbo.TestTableOne
  AFTER UPDATE
AS
BEGIN
  SET NOCOUNT ON
 
  -- TODO Do something...
END;
GO
```
**TEST 6 - SQL ERROR [102] [S0001]: Incorrect syntax near 'ON' (if executed as script)**
Here only differens with test (5) above, is that I have placed a trailing ";" on the SET NOCOUNT ON line.
```
IF OBJECT_ID('dbo.OnTestTableOneUpdate', 'TR') IS NOT NULL
  DROP TRIGGER dbo.OnTestTableOneUpdate;
GO
CREATE TRIGGER dbo.OnTestTableOneUpdate
  ON dbo.TestTableOne
  AFTER UPDATE
AS
BEGIN
  -- The use of a ";" to mark end of statement below generate an error
  SET NOCOUNT ON;
  
  -- TODO Do something...
END;
GO
```

**Comment by LonwoLonwo** [comment]
Hello @pdanie 
Yep, this is bug. A can execute the last example in mssql management studio, but not as script in DBeaver.
But I could execute this script рighlighting all the text and using ctrl+enter 
```sql
CREATE TRIGGER dbo.OnTestTableOneUpdate
  ON dbo.TestTableOne
  AFTER UPDATE
AS
BEGIN
  -- The use of a ";" to mark end of statement below generate an error
  SET NOCOUNT ON;
  
  -- TODO Do something...
END;
GO
```

And I have a question about point 3.
As I can see in [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) DBeaver send `SELECT TOP 100 * FROM TestTableOne` and `SELECT TOP 100 * FROM TestTableTwo` after.

He combined
```sql
SELECT * FROM TestTableOne

SELECT * FROM TestTableTwo
```
yes.

Why do you think, that point 3 is sent as a batch?

**Comment by pdanie** [comment]
**1**) You should execute the whole **TEST 6** SQL text.

In real life we have SQL files that contain many batches separated with "GO" (mostly drops followed by creates). Its  really irritating to have to select and execute each batch "by hand".

**2**) When I execute **TEST 3** (ie select all 4 rows and choose **Execute SQL Script**) in _DBeaver_ I got this in the **Execution Log**:

```
Time             Type             Text                        Duration (ms) Rows
Apr-12 17:45:00  SQL/User script  SELECT * FROM TestTableOne  2             1
Apr-12 17:45:01  SQL/User script  SELECT * FROM TestTableTwo  2             1
```
To me it looks like it have generated **2** batches that it sent to the SQL Server.

The thing about the "GO" is that is nothing that the SQL server understand nor anything that is supported by the SQL language. It is a directive to the SQL IDE (like _DBeaver_, _Microsoft SSMS_, etc.) to chop down a SQL text in smaller chunks/batches and send each chunk/batch one after another to the SQL server.

**Summary**

For SQL Server the ";" is a SQL statement terminator and "GO" is a SQL batch separator. Both are needed to be handled by _DBeaver_ and none could be ignored. Since SQL Server support the use of BEGIN/END that is something that _DBeaver_ need to take into consideration when it decide where a statement ends.

**PS**. I have never seen the use of "GO" in other IDE:s than for _SQL Server_ and _Sybase ASE_ (nowdays I think it is named SAP ASE), but it could be used for all database brands since the "GO" is never sent to the database server.

**Comment by LonwoLonwo** [comment]
And again, you said:

> Here DBeaver should first send "SELECT * FROM TestTableOne;" to the SQL Server as one batch, then send the "SELECT * FROM TestTableTwo;" as the second batch to the SQL Server.

And we do it. DBeaver recognize GO as batch separator. As you can see in Query Manager.

Do we close the discussion about test case 3? Or tell me, please, more about how it should look like.

**Comment by pdanie** [comment]
Sorry if I have been unclear.

The ONLY thing that is something bad, is for TEST 6 use case above. ALL other test cases are OK.

The reason I have written TEST 1 .. 6 is that I wanted to have all use cases using ";" and "GO" separators for SQL Server in one and the same support issue. So that if you adjust _DBeaver_ for TEST 6, that all the other test cases still work ok.

**Comment by jetzerb** [comment]
@pdanie : FYI - if you change the SQL Processing Delimiters such that
- `Statements delimiter` = "go"
- `Ignore native delimiter` is checked

then your Test 6 runs successfully
![image](https://user-images.githubusercontent.com/36859020/115450336-5f172d00-a1e1-11eb-86ee-c11e1e8b8588.png)
![image](https://user-images.githubusercontent.com/36859020/115450428-7b1ace80-a1e1-11eb-8ed3-d3160156cf7c.png)

Apparently, as of release 21.0.0, [DBeaver considers the semicolon to be a "native delimiter" for MSSQL](https://github.com/dbeaver/dbeaver/issues/11675#issuecomment-809936266) ([in addition to `go`](https://github.com/dbeaver/dbeaver/commit/fbfe1d4e44f604c18aec6031e6e55ab2e768658f#diff-8c4c7ed3b3924fbd09ca8e562d12991f15d2ad0df0528cbb3289e8bf6b8a5580)), which is different from [past behavior](https://github.com/dbeaver/dbeaver/issues/1482#issuecomment-726322295).
I've found that for MSSQL connections on the most recent DBeaver versions, I need the settings configured as above:
- If you don't `Ignore native delimiter`, it will send everything between semicolons as separate batches.  So, you can't do things such as declare variables and then reference them later.
- If you `ignore native delimiter` but don't set the `Statements delimiter` to "go", you'll get "incorrect syntax near 'go'" errors.

**Comment by uslss** [comment]
seems the issue is fixed.
Test 6 is successfully executed as a script in 21.2.1
