### ISSUE TITLE
PostgreSQL timestamp precision parameter confused with scale parameter

### ISSUE THREAD

**Issue by lvanderlaat** [dbeaver/dbeaver#12082]
#### System information: 
- Operating system: macOS Catalina 10.15.7
- DBeaver version: 21.0.1

#### Connection specification:
- Database name and version: PostgresSQL 12
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes, SSH

#### Describe the problem you're observing:
As per the [PostgreSQL documentation](https://www.postgresql.org/docs/current/datatype-datetime.html), time and timestamp have precision parameter (and not scale parameter). 

When creating a timestamp column, if I declare a precision of lets say 5, my column ends up with a 0 precision. 

Instead, if I declare a "Scale" of 5, my column will have precision 5. 

#### Steps to reproduce, if exist:

Create a new timestamp column and then declare its precision.

**Comment by uslss** [comment]
thanks for the report

**Comment by lvanderlaat** [comment]
> thanks for the report

My pleasure, thank you for this amazing software.

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.1.1. Now datetime columns precision is in precision field

**Comment by Matvey16** [comment]
Verified
