### ISSUE TITLE
Unexpected SQL executed like SELECT DISTINCT from, 1 FROM db.t1 WHERE from LIKE ? ORDER BY 1

### ISSUE THREAD

**Issue by myron934** [dbeaver/dbeaver#12087]
#### System information: 
- Operating system (distribution) and version:  win10
- DBeaver version: 21.0.2.202104042040
- Additional extensions

#### Connection specification:
- Database name and version: MySQL 5.7
- Driver name: MySQL 5
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  use SSH

#### Describe the problem you're observing:
SQL: 
select * from t1 where nfrom ='something'
and nto='abc'
order by timetag desc

press Ctrl+Enter to exucte this SQL

but real executed is :
SELECT DISTINCT nfrom, 1
FROM db.t1
WHERE nfrom LIKE '%something%'
ORDER BY 1

#### Steps to reproduce, if exist:
I Can not reproduce now.

#### Include any warning/errors/backtraces from the logs

There are many WARN trace logs like this and application is blocked: 

Statement 875 (SELECT DISTINCT nfrom, 1
FROM db.t1
WHERE nfrom LIKE ?
ORDER BY 1) is not closed

Statement 883 (SELECT ROUTINE_SCHEMA,ROUTINE_NAME FROM information_schema.ROUTINES WHERE ROUTINE_NAME LIKE ?  ORDER BY ROUTINE_NAME LIMIT 1) is not closed

**Comment by LonwoLonwo** [comment]
Hello @myron934
Can you please open and check [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) at that moment, when you execute your query?

Usually we use this type of queries for filter panel, to find out the possible values for a specific column.
```sql
SELECT DISTINCT columnName, 1
FROM table
ORDER BY 1
```

![2021-04-13 10_52_30-DBeaver Enterprise 21 0 3 - _none_ Script-19](https://user-images.githubusercontent.com/45152336/114517010-95cfcf00-9c46-11eb-978d-9b9331140f19.png)

**Comment by oudent** [comment]
This looks to be an attempt at adding new functionality to the auto completion system. It works great on small tables, and optimized databases from what I'm seeing, but essentially it won't run your desired query until it has finished filling the auto complete suggestions list. 

Previously (correct me if I'm wrong) auto complete would suggest table names/DB objects, but not suggest things within a string. 

So the query: 
SELECT DISTINCT nfrom, 1
FROM db.t1
WHERE nfrom LIKE '%something%'
ORDER BY 1

is still trying to fill in suggestions for when you were typing the string 'something' as part of this statement "nfrom ='something'".
If you pause while typing 'something' it sometimes runs multiple queries in sequence (waiting for each to finish before allowing you to run your query). 

I've verified this functionality with my co-worker, and it makes version 21.0.2 virtually unusable.

My setup is a MariaDB 10.2 (I'd have to double check) server.

I can't find a way to disable auto-complete by querying the table values without full disabling auto-complete. Hoping this information helps.

**Comment by myron934** [comment]
> Hello @myron934
> Can you please open and check [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) at that moment, when you execute your query?
> 
> Usually we use this type of queries for filter panel, to find out the possible values for a specific column.
> 
> ```sql
> SELECT DISTINCT columnName, 1
> FROM table
> ORDER BY 1
> ```
> 
> ![2021-04-13 10_52_30-DBeaver Enterprise 21 0 3 - none Script-19](https://user-images.githubusercontent.com/45152336/114517010-95cfcf00-9c46-11eb-978d-9b9331140f19.png)

Oh, I'm sure it's a serious bug. 

**Steps to reproduce** :
1. close the application and then reopen it.
2. use the recent SQL Editor to execute SQL like    select * from t1 where nfrom ='something' and nto='abc'
3. you'll find the sql like SELECT DISTINCT nfrom, 1 FROM db.t1 WHERE nfrom LIKE '%something%' is executed.
4. It is very dangerous if there is no index on column nfrom. 
This bug It caused a serious accident on my online database. 
T,T

**Comment by LonwoLonwo** [comment]
Ok, this is side effect of https://github.com/dbeaver/dbeaver/issues/11379 (Auto-complete inside strings (inside single quotes))
But autocomplete for string literals must be working _only_ with Ctrl+Space and inside single quotes.
Is this behavior different in your case?

**Comment by myron934** [comment]
> Ok, this is side effect of #11379 (Auto-complete inside strings (inside single quotes))
> But autocomplete for string literals must be working _only_ with Ctrl+Space and inside single quotes.
> Is this behavior different in your case?

I didn't use Ctrl + Space. 
Just When I typing SQL in the SQL Editor:
select * from table where nto='abc'

![image](https://user-images.githubusercontent.com/7500959/114837977-d37b5600-9e06-11eb-8d0d-f58325a50ed7.png)

you can see a background task is running:

SELECT DISTINCT nto, 1
FROM table
WHERE nto LIKE '%ab%'
ORDER BY 1

**Comment by LonwoLonwo** [comment]
We can add new setting for this case "Autocomplete for string literals", which can be disabled. Such a solution will be suitable for you?

**Comment by myron934** [comment]
> We can add new setting for this case "Autocomplete for string literals", which can be disabled. Such a solution will be suitable for you?

Of course yes. Thank you!

But I won't use this feature. I'll turn off this option all the way because it's dangerous. 

By the way, I installed a new version 21.0.3.202104151511. It seems that this bug is fixed in this version

**Comment by antonj19** [comment]
I'm using the new version 23.1.5.202308201919 (21 August 2023) and there is still this strange behaviour available!

I totally agree with the previous comments: THIS IS VERY DANGEROUS!

Steps to reproduce:

1. Connect to MySQL/MariaDB database
2. Run a SELECT query with WHERE condition. I.e. `SELECT * FROM file WHERE path = "files/%"`
3. The database process list actually shows up this query: `SELECT DISTINCT path FROM file `

This causes in some cases very long query times, because the desired query would be much faster!

*Edit: To disable this "feature" uncheck the following setting: _Preferences > Editors > SQL-Editor > SQL-Autocomplete > Show values_

![grafik](https://github.com/dbeaver/dbeaver/assets/232415/916efee8-4ec6-4b69-af9c-b17db3f7a020)

**Comment by myron934** [comment]
已收到,myron934
