### ISSUE TITLE
Stuck in "Open connection to DB2" 

### ISSUE THREAD

**Issue by fabriziop98** [dbeaver/dbeaver#12085]
#### System information: 
- Operating system (distribution) and version - MACOS Big Sur 11.2.3
- DBeaver version - 7.2.4
- Additional extensions

#### Connection specification:
- Database name and version - DESARROLLO
- Driver name - DB2 iSeries/ AS 400
- Do you use tunnels or proxies (SSH, SOCKS, etc) - no

#### Describe the problem you're observing:
When I open dbeaver, the connection to the database is stablished, but after stablishing the connection, dbeaver gets stuck showing the process 'Open connection to DESARROLLO' in 0%. If I shut down this process, I can execute scripts of type SELECT, but nothing else, (DROP, CREATE, ALTER) doesn't work.

I never had this problem before, and i have re installed dbeaver countless times, with the most recent version and the problem is still there.

#### Include any warning/errors/backtraces from the logs
Logs: 

[Logs.txt](https://github.com/dbeaver/dbeaver/files/6298298/Logs.txt)

**Comment by uslss** [comment]
@fabriziop98 could you check if it reproducible for you against 21.0.3?

**Comment by fabriziop98** [comment]
problem still occurs in 21.0.3

**Comment by uslss** [comment]
unfortunately, we've got no environment to reproduce an issue. could you check if it is still actual against 21.1.0?
Thanks in advance and sorry for the late response

**Comment by uslss** [comment]
there is no update on the issue for a long time.
if it is still actual - feel free to reopen it with additional info
