### ISSUE TITLE
View Table and View View opens last changed object tab instead of defaulting to properties tab

### ISSUE THREAD

**Issue by overlind** [dbeaver/dbeaver#12093]
#### System information: 
- Windows 10 Enterprise 20H2
- DBeaver Enterprise 21.0.0

#### Connection specification:
- MySQL 8

#### Describe the problem you're observing:
When I double-click (or press F4) on a table or view in the Database Navigator, the editor opens to the last changed tab (Properties, Data, or ER Diagram).  When I change the Default editor page in the screenshot below, the Data and ER Diagram options stick and double-clicking a table/view follows that preference, but the Default option saves as a blank and does not define a specific default tab.  Maybe a solution (formulated as a feature request) would be to add the Properties tab to the Default editor page drop-down list.  In this case, the "Default" option in the list might be better called "Last changed" or "Last used".  My goal is to be able to consistently open the properties of a table or view when I double click on it rather than opening the data tab.  Similar to issue #7151, I have a few columns that are rather large JSON types that the default SELECT * query on the data tab, even with the limit of 200 rows, returns very slowly over a VPN connection.  Defaulting to the properties tab would help catch this before executing a large query.

![Screenshot 2021-04-13 132812](https://user-images.githubusercontent.com/25406920/114616852-38df1380-9c5c-11eb-9623-4d24fec2f835.png)

#### Steps to reproduce:
1. Set Preferences -> User Interface -> Navigator -> Default editor page set to "Default"
2. Double-click (or press F4) on a table or view in the Database Navigator
3. Change Editor tabs (Properties / Data / ER Diagram)
4. Double-click (or press F4) on a different table / view in the Database Navigator
5. Editor tab for this table / view will be the same as selected in step 3.

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
Implemented:

![image](https://user-images.githubusercontent.com/35821147/120206487-ec638d80-c233-11eb-8c2b-6b3ade9a7cc4.png)

**Comment by DariaMarkaryan** [comment]
Verified
