### ISSUE TITLE
Booleans stopped displaying as checkboxes

### ISSUE THREAD

**Issue by jpodpro** [dbeaver/dbeaver#12092]
#### System information: 
- Operating system (distribution) and version: Windows 10 20H2 19042.867
- DBeaver version: latest (21.0.2)

#### Connection specification:
- Database name and version: PGSQL

#### Describe the problem you're observing:
Before upgrading to dbeaver 21 booleans displayed as checkboxes just fine. ever since upgrading they simply show as [ ] or [v]. i have confirmed that the setting to show as checkboxes is enabled in the global and connection-specific settings.

**Comment by uslss** [comment]
@jpodpro Cannot reproduce it against 21.0.2.
![image](https://user-images.githubusercontent.com/31996417/114676384-ebbd7900-9d11-11eb-86cd-37db7023069b.png)

Could you show how does it look for you? Is there something in the logs?

**Comment by jpodpro** [comment]
this was the setting i needed. i was sure i had found another setting that seemed similar but wasn't changing anything. however i cannot find it anywhere...of course. 

anyway thanks :)
