### ISSUE TITLE
'Disable referential integrity' checkbox is disabled for new tables

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12095]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.2

#### Steps to reproduce, if exist:
1. Open export wizard table>database
2. Select new table as a target in Tables mapping step and press **Next**

**Expected**: 'Disable referential integrity' checkbox is active on Settings step of datatransfer
**Actual result**: 'Disable referential integrity' checkbox is disabled on Settings step of datatransfer
**Workaround**: Select an existed table  in Tables mapping step  at first, press Next, then go back and select a new table

https://user-images.githubusercontent.com/51405061/114680649-10b3eb00-9d16-11eb-9ef4-1249cf761279.mp4

**Comment by p91paul** [comment]
which kind of referential integrity can you disable on new tables?

**Comment by kseniiaguzeeva** [comment]
The ticket name doesn't refer the issue correctly. It is about equal behaviour: you should have the option disabled or enabled in both cases: when you perform export to a new table and when you select an existed table and then change it on a new one.

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
