### ISSUE TITLE
Missing tables in "References" section (different schema issue)

### ISSUE THREAD

**Issue by tonyfarney** [dbeaver/dbeaver#12090]
#### System information: 
- Operating system (distribution) and version
Linux Mint 20.1 Cinnamon

- DBeaver version
21.0.2.202104042040

- Java version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

- Additional extensions
None

#### Connection specification:
- Database name and version
PostgreSQL 12.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

- Driver name
PostgreSQL JDBC Driver

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
In the table details, "Properties" tab, "References" section as well as in the "ER Diagram" tab, the tables that belongs to another schema than the parent table one are missing.

#### Steps to reproduce, if exist:
1 - Create a test database:
CREATE DATABASE test;

2 - After connecting to the "test" database, create the test schemas and tables:
CREATE SCHEMA a;
CREATE SCHEMA b;
CREATE TABLE a.parent (
	id INTEGER NOT NULL,
	CONSTRAINT pk_parent PRIMARY KEY (id)
);
CREATE TABLE a.child_a (
	id INTEGER NOT NULL,
	parent_id INTEGER NOT NULL,
	CONSTRAINT pk_child_a PRIMARY KEY (id),
	CONSTRAINT fk_child_a FOREIGN KEY (parent_id) REFERENCES a.parent (id)
);
CREATE TABLE b.child_b (
	id INTEGER NOT NULL,
	parent_id INTEGER NOT NULL,
	CONSTRAINT pk_child_b PRIMARY KEY (id),
	CONSTRAINT fk_child_b FOREIGN KEY (parent_id) REFERENCES a.parent (id)
);

#### Evidences:
![Selection_198](https://user-images.githubusercontent.com/5487349/114575465-92414580-9c50-11eb-826a-d8c1120aa85e.png)
![Selection_199](https://user-images.githubusercontent.com/5487349/114575488-98372680-9c50-11eb-86b2-c5dc3a40b38b.png)
![Selection_200](https://user-images.githubusercontent.com/5487349/114575525-a38a5200-9c50-11eb-9ff5-eadfcbd72b11.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/35821147/120328100-2c3d7a00-c2f3-11eb-9e2c-8d79269f5ab1.png)

![image](https://user-images.githubusercontent.com/35821147/120328127-33fd1e80-c2f3-11eb-92be-34cd741c74b7.png)

**Comment by DariaMarkaryan** [comment]
Verified
