### ISSUE TITLE
SAP IQ. In 21.0.2 autocomplete does not work for tables

### ISSUE THREAD

**Issue by zolovey** [dbeaver/dbeaver#12108]
After upgrading to 21.0.2 autocomplete for tables does not work. (but works for schemas and fields).

Seems that the cause is in GenericObjectContainer.java after it was updated in scope of issue #9710 

if changing back `public Collection<? extends DBSObject> getChildren(@NotNull DBRProgressMonitor monitor)` to 21.0.1 version, then autocomplete works fine

#### System information: 
- Windows 10 1909
- DBeaver version: 21.0.2

#### Connection specification:
- SAP IQ/16.1.040.1549
- jConnect

**Comment by LonwoLonwo** [comment]
Hello @zolovey 
Can you please test [early access](https://dbeaver.io/files/ea/) version? some autocomplete problems were fixed in this version.

**Comment by zolovey** [comment]
@LonwoLonwo in EA version autocomplete works as expected
