### ISSUE TITLE
Comments on table lead to duplicates in table list

### ISSUE THREAD

**Issue by klyusba** [dbeaver/dbeaver#12110]
#### System information: 
- Windows 10
- DBeaver version 21.0.2
- Additional extensions - none

#### Connection specification:
- Vertica 9.3.1-11
- jdbc 9.2.1

#### Describe the problem you're observing:
Each column with comment make duplicate table in table list
![изображение](https://user-images.githubusercontent.com/24367455/114981274-63b4ac00-9e96-11eb-9715-7f4e1fedadd8.png)

#### Steps to reproduce, if exist:
COMMENT ON COLUMN tst.A IS 'A';
COMMENT ON COLUMN tst.B IS 'B';

**Comment by LonwoLonwo** [comment]
Thanks for the bug report!

Note: Duplication of columns is not always happening, but only in some cases.

**Comment by LonwoLonwo** [comment]
Fixed. The problem was with columns with equal names in different tables.

So steps were:
```sql
CREATE TABLE test1(Integer A, Integer B);
COMMENT ON COLUMN test1.A IS 'A';
COMMENT ON COLUMN test1.B IS 'B';
```

```sql
CREATE TABLE test2(Integer A, Integer B);
COMMENT ON COLUMN test2.A IS 'A';
COMMENT ON COLUMN test2.B IS 'B';
```

**Comment by kseniiaguzeeva** [comment]
verified (Vertica was tested)
