### ISSUE TITLE
Table/View cannot be created/dropped using UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#12115]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.0.3 EA

#### Connection specification:
- Database name and version PrestoDB
- Driver name PrestoSQL - Presto JDBC 350, PrestoDB - PrestoJDBC 0.250

#### Describe the problem you're observing:
The table/view cannot be created using UI - an error appears, but it is successfully created in case of copying a generated script and executing it manually.
![2021-04-16_14h10_36](https://user-images.githubusercontent.com/31996417/115016382-9faf3780-9ebd-11eb-8b86-283ea9f9e8ed.gif)

**Comment by ShadelessFox** [comment]
As mentioned in the error itself, Presto supports creating tables in auto-commit mode. Now Presto uses current transaction mode.

**Comment by uslss** [comment]
verified
