### ISSUE TITLE
Data cannot be updated using UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#12116]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.0.3 EA

#### Connection specification:
- Database name and version PrestoDB
- Driver name PrestoSQL - Presto JDBC 350, PrestoDB - PrestoJDBC 0.250

#### Describe the problem you're observing:
Error appears when trying to save cell value changes:
![image](https://user-images.githubusercontent.com/31996417/115020095-bc9a3980-9ec2-11eb-9184-c34e54826992.png)
Error in case of generating script (script button)
![image](https://user-images.githubusercontent.com/31996417/115020152-d89ddb00-9ec2-11eb-99ab-d1f88a8b22ca.png)

**Comment by ShadelessFox** [comment]
Presto does not support data updating.

**Comment by ShadelessFox** [comment]
Presto driver is now read-only by default. Make sure this is only true for Presto.

**Comment by uslss** [comment]
verified
