### ISSUE TITLE
Export from ResultSet doesn't work for uncommitted delete with returning clause

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12111]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.2

#### Describe the problem you're observing:
Based on https://github.com/dbeaver/dbeaver/issues/11095
#### Steps to reproduce, if exist:
1. Execute for PostgreSQL in Manual Commit:
```
drop table if exists my_test_table;
create table my_test_table as select * from generate_series(1,10) as my_data;
-- You should now see that the table has 10 records
select * from my_test_table;
```
2. Commit transactions
3. Execute `delete from my_test_table returning *;` and press XLS button in the bottom toolbar

**Expected**: the table data is exported to XLS  from the Resultset
**Actual result**: 
- the file is empty
- DBeaver hungs when we use Export from the ResultSet wizard instead of XLS button
![Screenshot 2021-04-16 at 10 32 55](https://user-images.githubusercontent.com/51405061/114988573-27397e00-9e9f-11eb-936f-d35d61b7fe88.png)

**Comment by uslss** [comment]
verified
