### ISSUE TITLE
Remove selection when switch text view to record

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12129]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.2

#### Steps to reproduce, if exist:
1. Open a table in text view in Data Editor
2. Select some cells
3. Switch to Record view

**Expected**: the selection is removed
**Actual result**: the selection frame remains visible
https://user-images.githubusercontent.com/51405061/115106822-81a20f80-9f6f-11eb-8206-7973adbfdf0d.mp4

**Comment by Matvey16** [comment]
Verified
