### ISSUE TITLE
Exporting table to .sql script for Postgres with NaN values

### ISSUE THREAD

**Issue by dustincrockett** [dbeaver/dbeaver#12128]
#### System information: 
- Windows 10
- 21.0.0.

#### Connection specification:
- Postgres 12

#### Describe the problem you're observing:
When using the export table to .sql script I have a column of type numeric which has multiple rows with the value NaN.  The export script generated creates an output like:
INSERT INTO public.loads(interval_timestamp,load_id,forecast_timestamp,status,fixed_value,value) VALUES
	 ('2022-04-02 07:00:00-07',9971,'2021-04-01 07:00:00-07',false,false,NaN);
the script above will provide an error at NaN.  If the script is modified to below:
INSERT INTO public.loads(interval_timestamp,load_id,forecast_timestamp,status,fixed_value,value) VALUES
	 ('2022-04-02 07:00:00-07',9971,'2021-04-01 07:00:00-07',false,false,'NaN');
it will insert as expected.

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
Fixed for PostgreSQL:
```sql
select 'NaN'::float4, '-Infinity'::float4, '+Infinity'::float4;
```

Produced SQL script:
```sql
INSERT INTO "select 'NaN'::float4, '-Infinity'::float4, '+Infinity'::float4" ("float4","float4","float4") VALUES
	 ('NaN','-Infinity','Infinity');
```

And for Oracle:
```sql
SELECT BINARY_DOUBLE_NAN, -BINARY_DOUBLE_INFINITY, BINARY_DOUBLE_INFINITY FROM DUAL;
```

Produced SQL script:
```sql
INSERT INTO DUAL (BINARY_DOUBLE_NAN,"-BINARY_DOUBLE_INFINITY",BINARY_DOUBLE_INFINITY) VALUES
	 ('NaN','-Infinity','Infinity');
```

**Comment by uslss** [comment]
verified
