### ISSUE TITLE
Regression in 21.0.2: Vertica DB fails to read schema

### ISSUE THREAD

**Issue by ophers** [dbeaver/dbeaver#12127]
#### System information: 
- Operating system
  Edition	Windows 10 Enterprise
  Version	20H2
  OS build	19042.928
  Experience	Windows Feature Experience Pack 120.2212.551.0

- DBeaver version
  Version 21.0.2.202104042040
  
- Additional extensions
  DBeaver	21.0.2.202104042040	org.jkiss.dbeaver.core.product	null
  DBeaver Debug	6.1.44.202104042040	org.jkiss.dbeaver.debug.feature.feature.group	JKISS
  DBeaver Git support	1.0.42.202104042040	org.jkiss.dbeaver.git.feature.feature.group	DBeaver Corp
  DBeaver Office Support	1.1.91.202104042040	org.jkiss.dbeaver.ext.office.feature.feature.group	JKISS
  DBeaver SSHJ	1.0.75.202104042040	org.jkiss.dbeaver.net.sshj.feature.feature.group	JKISS
  DBeaver SVG Extension	1.0.90.202104042040	org.jkiss.dbeaver.ext.ui.svg.feature.feature.group	DBeaver Corp

#### Connection specification:
- Database name and version
  Server: Vertica Database 09.02.0105
  Client: vertica.jar 09.02.0100
- Driver name
  com.vertica.jdbc.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
  No

#### Describe the problem you're observing:
Autocompletion for DB entities (e.g. table names, column names) no longer works.
Double-clicking a table in the tree gives the attached error:
![image](https://user-images.githubusercontent.com/11839190/115075398-ac567e80-9f03-11eb-8b47-9661224fa9bb.png)

#### Steps to reproduce, if exist:
**This works fine in version 21.0.1.**

#### Include any warning/errors/backtraces from the logs

[DBeaver-configuration.txt](https://github.com/dbeaver/dbeaver/files/6327516/DBeaver-configuration.txt)
[DBeaver-log.txt](https://github.com/dbeaver/dbeaver/files/6327544/DBeaver-log.txt)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/6327572/dbeaver-debug.log)

**Comment by LonwoLonwo** [comment]
Hello @ophers 
Can you please check new version of [DBeaver](https://dbeaver.io/)? We fixed some problems with autocomplete in this Release.

**Comment by ophers** [comment]
Hello @LonwoLonwo 
I've downloaded and installed version `21.0.3.202104181339` (plus extensions).
It still faulty with the same error messages.

**Comment by LonwoLonwo** [comment]
Thanks for testing @ophers 
Can you provide more examples? Screens or video of incorrect autocomplete behaviour.

**Comment by LonwoLonwo** [comment]
We fixed column reading for early Vertica versions in DBeaver version 21.0.4

**Comment by ophers** [comment]
Thanks for the quick response and resolution.

**Comment by LonwoLonwo** [comment]
Now support column comments in DBeaver starts from Vertica 9.3 version

**Comment by uslss** [comment]
verified
