### ISSUE TITLE
DBeaver still has open port for listening wide open

### ISSUE THREAD

**Issue by holdfenytolvaj** [dbeaver/dbeaver#12120]
I understand that 
https://github.com/dbeaver/dbeaver/issues/10944
https://github.com/dbeaver/dbeaver/issues/7154
was opened because of this as well, but there is still an open port. 
Previously there were two wide open ports, one has been addressed (the RMI), but what's the purpose of the other?

My version is 21.0.2.202104042040 (April)
and it still has a wide open port:
```
tcp        0      0 0.0.0.0:40369           0.0.0.0:*               LISTEN      257772/java      (???)
tcp        0      0 127.0.0.1:21324         0.0.0.0:*               LISTEN      257772/java    (This is the RMI)     
```

#### System information: 
- Operating system (distribution) and version: Linux
- DBeaver version 21.0.2.202104042040

#### Connection specification:
generall use postgres, but if I close all connection, I still have as above.

**Comment by serge-rider** [comment]
Thanks for noticing that (again 😥  )

Yes. In fact RMI listens two different ports. One for RMI registry and another for actual TCP connections.
We must limit the second one with local income connections as well.

Generally I'd love to get rid of RMI and replace it with something more reliable, like rest service. 
However it will require time for development.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by wiwwo** [comment]
MacOsX... every time I open DBeaver... At least, annoying :D 
Version 21.1.2.202107041908

<img width="254" alt="image" src="https://user-images.githubusercontent.com/3930671/127449223-dda76bec-bf41-4870-8659-329b2025dc94.png">

**Comment by yoonghm** [comment]
Can the RMI be disabled if I do not wish to have remote clients?

**Comment by bartekbrak** [comment]
The community version still open up the port.
```
sudo lsof -Pan -i tcp | grep dbeaver
dbeaver   17873 b?????????   58u  IPv6 0xb0d5f89c750f6cdd      0t0  TCP *:51913 (LISTEN)
```
Version 23.1.3.202307231901
