### ISSUE TITLE
Create table statement is wrongly generated and data transfer isn't possible to a new table

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12124]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.3 EA

#### Connection specification:
- Database name and version Clickhouse

#### Steps to reproduce, if exist:
Perform export/import to new table

**Expected**: the data is exported/imported
**Actual result**: new table cannot be created

**Comment by LonwoLonwo** [comment]
Fixed in Dbeaver 21.1.2

**Comment by Matvey16** [comment]
Generated DDL includes `NOT NULL` for columns which leads to syntax error.

![2021-06-23_10h43_53](https://user-images.githubusercontent.com/82543000/123057298-6c82aa80-d410-11eb-8794-7d404618816d.png)

**Comment by LonwoLonwo** [comment]
Support of NULL and NOT NULL modifiers removed from Clickhouse and Hive < 3.0 version

**Comment by Matvey16** [comment]
Verified
