### ISSUE TITLE
"Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost."

### ISSUE THREAD

**Issue by happycoffeebean** [dbeaver/dbeaver#12138]
#### System information: 
- Operating system (distribution) and version: Pop_OS! (Debian 20.10)
- DBeaver version:  21.0.2
- Additional extensions: None

#### Connection specification:
- Database name and version:  mysql 8.0.22
- Driver name: MySQL , com.mysql.cj.jdbc.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  SSH (connection tests fine)

#### Include any warning/errors/backtraces from the logs
This error is displayed in an alert box, and also in the DBeaver logs. 

Server log shows a successful login via SSH, but nothing further:
Apr 18 21:14:14 cliffs-wordpress systemd[1]: Started Session 32 of user root.
Apr 18 21:14:15 cliffs-wordpress systemd[1]: session-32.scope: Succeeded.

**Comment by uslss** [comment]
@happycoffeebean could you provide error and debug logs?

**Comment by happycoffeebean** [comment]
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/6352787/dbeaver.log)
I'm not clear on where to find a pertinent debug log.  In the documentation, searching for debug logs seem to pertain to debugging a language-specific script.

**Comment by uslss** [comment]
@happycoffeebean did you try to connect using any other client?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.

**Comment by roma2341** [comment]
In my case this error happened because I connected to the wrong database, we have RDS on prod and local MySQL on dev servers and I tried to connect to the prod server local MySQL instead of RDS... Night coding..
