### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#12132]
#### System information: 
- Linux Mint 19.3
- DBeaver version 7.2.4
#### Describe the problem you're observing:
![_3](https://user-images.githubusercontent.com/799021/115121211-16315f80-9fba-11eb-984b-040663783cce.jpg)

Expected numbers are: 27453, 27452, 27449
excess coma is thousand delimeter

**Comment by uslss** [comment]
@KES777 unfortunately, cannot reproduce it.
Could you check if it is reproducible for you against 21.0.3?

**Comment by KES777** [comment]
It is OK on 21.0.3
