### ISSUE TITLE
Add loader when when big data is filtered via column header

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12135]
We should add a loader when we apply a column header filter and some time is needed to show results

**Comment by ShadelessFox** [comment]
Other highlights:
1. All options are now moved into their own group
2. Added delay after changing filter text before refreshing values to avoid spamming DB with queries


https://user-images.githubusercontent.com/35821147/128370049-baecfcff-ccb8-4ad4-b4f8-f06b63fe17aa.mp4

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
Verified
