### ISSUE TITLE
Save SRID custom settings

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12147]
SRID settings are returned back to default after DBeaver reopening. We should keep user SRID settings saved.

**Comment by ShadelessFox** [comment]
Fixed. Please make sure column formatting still works.

**Comment by kseniiaguzeeva** [comment]
- SRID cannot be saved in spatial tab
- SRID cannot be set in column formatting (3395 is used by default)

**Comment by kseniiaguzeeva** [comment]
implemented.
