### ISSUE TITLE
uncomfortable table column hints

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#12140]
DBeaver 21.0.3
Postgresql 12

my table DDL
CREATE TABLE form.d_condition (
	id serial NOT NULL, -- ИД
	code text NULL, -- Код
	name text NOT NULL, -- Имя
	CONSTRAINT relation_type_pk PRIMARY KEY (id)
);

But DBeaver hints are:
![изображение](https://user-images.githubusercontent.com/61137576/115183733-d96a8300-a0f5-11eb-81b1-771df1050210.png)

Very uncomfortable when DBeaver change real columns sort. Especially for tables with 10 or more columns, finding the right column is very difficult. In a real table i create columns in comfortable sequence.

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
Fixed for column proposals:

![image](https://user-images.githubusercontent.com/35821147/123094563-af0aae00-d435-11eb-8f44-f47fcd2b4b52.png)

**Comment by Matvey16** [comment]
Verified
