### ISSUE TITLE
Metadata search doesn't work for rdbms' with databases and schemas

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#12143]
DBeaver 21.0.3. The bug is present at least on PostgreSQL and SQL Server, I suspect it can be found on any RDBMS with databases and schemas.

STR:
1. Connect to a database server. Let's say that the default database is called A and the default schema is B.
2. Open metadata search and try to find something which is not in the database A schema B. You won't find anything.

Workaround: if you need to find an object in the database C schema D, set it as default in the bootstrap settings.

**Comment by flambchap** [comment]
FIxed.

**Comment by flambchap** [comment]
Still doesn't work on PostgreSQL.

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
