### ISSUE TITLE
Selected row is not highlighted in value panel with dark theme

### ISSUE THREAD

**Issue by avdotius** [dbeaver/dbeaver#12141]
#### System information: 
- Windows 10 Pro 20H2 19042.928
- Version 21.0.3.202104181339

#### Connection specification:
- Postgresql

#### Describe the problem you're observing:
With standard dark theme applied in the value panel the selected row is not highlighted.

![dbe-1](https://user-images.githubusercontent.com/1001060/115189174-c0120880-a0ee-11eb-8b98-340262b35076.png)

![dbe-2](https://user-images.githubusercontent.com/1001060/115189196-c86a4380-a0ee-11eb-98d7-543314c87dc4.png)

**Comment by LonwoLonwo** [comment]
Hello @Alterant-zz 
Unfortunately, could not reproduce.

![2021-04-20 11_01_28-DBeaver 21 0 3 - Album](https://user-images.githubusercontent.com/45152336/115360225-1bfc9000-a1c8-11eb-867f-8e721f0ac105.png)

May be "Reset UI settings"/"Reset workspace state" can help

![2021-04-20 11_00_58-DBeaver 21 0 3 - Album](https://user-images.githubusercontent.com/45152336/115360355-39315e80-a1c8-11eb-8fa4-e40ce8589dc5.png)

Or you can try enable this setting:

![2021-04-20 11_01_58-Preferences](https://user-images.githubusercontent.com/45152336/115360453-4e0df200-a1c8-11eb-9461-661e97a372ba.png)

**Comment by avdotius** [comment]
Made a reset of UI settings and workspace state.
Enabled option "Highlight rows with ..."

Nothing changed.

Switched Windows theme to Bright.

Also with no luck :(

**Comment by uslss** [comment]
thanks for the report

**Comment by flambchap** [comment]
Fixed.

**Comment by DariaMarkaryan** [comment]
Verified

**Comment by avdotius** [comment]
I can confirm that in release 21.1.1.202106210824 everything works like a charm. Thanks a lot!
