### ISSUE TITLE
No autocomplete for tables after schema - Apache Ignite SQL

### ISSUE THREAD

**Issue by tmarex** [dbeaver/dbeaver#12159]
#### System information: 
- Windows 10 
- DBeaver version 21.0.3.202104181339
- Additional extensions

#### Connection specification:
- Apache Ignite
- Driver name: ignite-core-2.7.5.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No.

#### Describe the problem you're observing:

For Apache Ignite SQL there is no autocomplete anymore for tables after schema.

#### Steps to reproduce, if exist:

![image](https://user-images.githubusercontent.com/82822542/115260471-1143eb80-a133-11eb-9637-389c9c5e8580.png)
![image](https://user-images.githubusercontent.com/82822542/115260575-2caef680-a133-11eb-85b6-8d6661959ed6.png)

It was OK in 21.0.1 version
![image](https://user-images.githubusercontent.com/82822542/115261509-f8880580-a133-11eb-8a9d-857a72b4ac8c.png)

**Comment by LonwoLonwo** [comment]
Thanks for the bug report! 

Can reproduce in PostgreSQL with schema in quotes.
![2021-04-20 11_18_27-](https://user-images.githubusercontent.com/45152336/115362414-2d469c00-a1ca-11eb-945d-5bcf870cb510.png)

**Comment by twillstw** [comment]
For what it's worth, I'll add that I'm having the exact same issue with my Amazon Athena connection. I recently updated from windows version 7.1 to 21.0.3, and this issue has newly cropped up. 

Once I set the table name, the autocomplete seems to work fine for column names in the SELECT clause, not so much the WHERE clause. 

When working with Oracle, I don't seem to experience any such issues.

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.1.2

**Comment by Matvey16** [comment]
Verified
