### ISSUE TITLE
Workspace directory reset after each update

### ISSUE THREAD

**Issue by poebel** [dbeaver/dbeaver#12150]
#### System information: 
- OS: Windows 10 20H2 (Build 19042.928)
- DBeaver version: 21.0.3
- Additional extensions: None

#### Describe the problem you're observing:
I'm using a custom workspace located in my Dropbox directory ("D:\Dropbox\Work\DBeaver\workspace").  
The dropbox directory is fully synchronized and available locally.  

After each DBeaver update the workspace gets reset to the default location "%appdata%\DBeaverData\workspace6" and my custom workspace is removed from the list.  
This is quite annoying as I've need to manually locate the workspace after each update (which happen quiet frequently).  

#### Steps to reproduce, if exist:
- Change to custom workspace directory
- Update DBeaver

**Comment by uslss** [comment]
thanks for the report

**Comment by flambchap** [comment]
Implemented. Now DBeaver backups list of recent workspaces to DBeaverData. But since this backup will be introduced in the 21.1.1 version, the previous workspace will be restored only when upgrading to 21.1.2.

**Comment by Matvey16** [comment]
Verified
