### ISSUE TITLE
Autocomplete should show all valid options

### ISSUE THREAD

**Issue by wernerdaehn** [dbeaver/dbeaver#12153]
As a follow up on this https://github.com/dbeaver/dbeaver/issues/9710 issue, let me try to be more precise.

This select statement `select * from tables;` (Hana) or `select * from all_tables;` (Oracle) is valid for all users. If those object names are valid, then autocomplete should offer them. Even more so as data dictionary tables are among the most often used objects in queries, at least for use SQL savvy users with DBeaver.

Hence the request, that autocomplete (without a schema) should show all objects that can be used without a schema qualifier, which is private views, tables, synonyms but also public synonyms.

More precise, when I start typing `select * from tab...` the object `tables` should be among the proposed objects.

![Screenshot](https://user-images.githubusercontent.com/13607767/115214884-3e78a580-a103-11eb-9303-257a4a3b0695.png)

**Comment by LonwoLonwo** [comment]
Thanks.

**Comment by E1izabeth** [comment]
In the latest DBeaver version you can turn on this option 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/57f36aeb-2b12-42ee-82e0-ae182ec7dc10)

Works and see such autocompletions
![image](https://github.com/dbeaver/dbeaver/assets/28875055/15280e07-dbac-41d3-aedd-b677d86489ac)
