### ISSUE TITLE
21.0.3 and PostgreSQL: completion somewhat broken

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#12168]
#### System information: 
- Operating system (distribution) and version Debian/SID
- DBeaver version 21.0.3.202104181339
- Java version 15.0.2
- Additional extensions

#### Connection specification:
- Database name and version PostgreSQL 12
- Driver name pgjdbc 1.1.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Completion has always been a bit awkward, but since yesterday's update in a query like
``
SELECT *
FROM table_a, table_b
``
colum names of `table_b` are not proposed anymore, neither in `SELECT` nor in `WHERE`
Log shows nothing.

Additionally, in simple queries with just one table in
`SELECT` 
for some, not all, letters the table name appears as top proposal, although the name does not contain that letter, nor does the table name make much sense in the `SELECT` clause

**Comment by LonwoLonwo** [comment]
Hello @2019-05-10 
Can you provide more examples, please?
Screens will be very helpful.

**Comment by 2019-05-10** [comment]
> Hello @2019-05-10
> Can you provide more examples, please?
> Screens will be very helpful.

Uhm, what?
Not sure what exactly you expect.

The query I gave very concisely displays the behaviour in a minimal working examply, suggesting an issue with the position of the second table.
If you have gotten another theory I need more specific information as to what examples to create.

**Comment by LonwoLonwo** [comment]
Autocompletion depends on the conditions: in which part of statement it is used, whether there are aliases of the table, whether fully qualified names or short, etc.

Examples:
![2021-04-21 12_00_44-](https://user-images.githubusercontent.com/45152336/115527683-f5a72500-a299-11eb-9a39-7b34bd55dcac.png)

![2021-04-21 12_00_58-](https://user-images.githubusercontent.com/45152336/115527685-f5a72500-a299-11eb-8542-1396f3724b61.png)

**Comment by 2019-05-10** [comment]
Seems to be a timing issue.
Yesterday under heavy load completion ceased to work completely, even in previously working queries the completion returned nothing or at least not with start character like
`SELECT c[CTRL+SPACE]`
no proposals (although several columns exist), but
`SELECT [CTRL+SPACE]`
proposed several fields with starting with or containing `c`

Once the load went back to to normal, completion started to work again as limited as previously.
The trouble seems to be mostly with tables that have many columns (>30).

Given the complete breakdown under heavy load, I assume the gathering of column names takes too long and thus is cancelled.
I've got the impression that those column names are collected over and over again instead of being cached somewhere -- caching may be a bit complex given that tables may change in the background, but maybe some kind of change detection is possible.

**Comment by LonwoLonwo** [comment]
Ok. Thanks for testing @2019-05-10

**Comment by JamesInform** [comment]
I experience the same issue on DBeaver 21.0.3 using PostgreSQL 13. On 21.0.2. everything is fine.

When I simply type

`select * from mytab where `

then no autocompletion is available after the "where" keyword. No field from the table is listed. Wether automatically nor hitting ctrl+space.

if give an alias to the table like

`select * from mytab m where m.`

then everything works fine.

**Comment by renezito** [comment]
The problem is in Oracle too.  In version 21.0.2 everything is fine, like @JamesInform indicated.  But in 21.0.3 doesn't work.
I maked a video with the evidence:

https://drive.google.com/file/d/1SbxPmU9hg13AeN-OrVXFJYTGekG9-tZk/view?usp=sharing

https://user-images.githubusercontent.com/37661233/116725410-dd2cbe00-a9af-11eb-9772-0c3b30f36a32.mp4

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified. @2019-05-10 please use aliases to see column names for the second table etc.
![dbeaver_XuvWJiHwG7](https://user-images.githubusercontent.com/51405061/117567428-01ca1980-b0c5-11eb-99d9-5ff3296ba361.png)

**Comment by 2019-05-10** [comment]
> Verified. @2019-05-10 please use aliases to see column names for the second table etc.

Uhm, is that supposed to be the fix or only a workaround until the fix is released?

**Comment by kseniiaguzeeva** [comment]
Looks like it wasn't implemented before. But we are going to do it in future releases. It will be a separate feature request.
