### ISSUE TITLE
PostgreSQL: Table Backup creates .sql file in custom format by default

### ISSUE THREAD

**Issue by Chealer** [dbeaver/dbeaver#12164]
#### System information: 
- Windows 10
- DBeaver 21.0.3

#### Connection specification:
- PostgreSQL 11
- PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
By default, when using Tools->Backup on a PostgreSQL table, DBeaver uses the _Custom_ format, which creates a file in a PostgreSQL-specific binary format. Yet, by default, the file is named with a ".sql" extension, even though its content is not SQL, due to the _File name pattern_, which defaults to "dump-${database}-${timestamp}.sql".

The proper fix would be to make _File name pattern_ dependent on the format, or to exclude the extension from the pattern.

#### Steps to reproduce, if exist:

1. Bring up the context menu on a PostgreSQL table
2. Open _Tools_
3. Select _Backup_
4. Activate the _Start_ button

The problem will not happen if a backup was already done and the last one was in SQL format.

**Comment by uslss** [comment]
thanks for the report

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
