### ISSUE TITLE
Copy as SQL create an invalid insert statement

### ISSUE THREAD

**Issue by abolognino** [dbeaver/dbeaver#12167]
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04.2 LTS
- DBeaver version: 21.0.3
- Additional extensions: Vrapper

#### Connection specification:
- Database name and version: Oracle 19
- Driver name: ojdbc8-12.2.0.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
Copy as SQL produces an insert statement where the name of the table is wrong:

#### Steps to reproduce, if exist:

    create table zztest (id number, x varchar2(100)); 
    insert into zztest(id, x) values (1, 'x');
    select * from zztest;
    /* select the row then use Advanced Copy -> Copy as SQL */
    
dbeaver generates: 

    INSERT INTO "zztest" (ID,X) VALUES (1,'x');

valid name for the table in Oracle are: zztest, ZZTEST, "ZZTEST", but NOT "zztest"
This is because non quoted names are by default turned into uppercase name, but when quoted the case is respected by Oracle.

#### Include any warning/errors/backtraces from the logs
none

**Comment by LonwoLonwo** [comment]
Hello @abolognino 
Yes, this is tricky case.
If you try first
"select * from ZZTEST;"
and than "Advanced Copy -> Copy as SQL"
Result query will be normal. Without quotes in table name and table name will be in upper case. 

We will think about how the problem can be solved. Thanks for the bug report.

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
