### ISSUE TITLE
MSSQL CLR Table-Valued Function Returns Columns But Not Data Values

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#12163]
#### System information: 
- Windows 10
- DBeaver Community Version 21.0.3.202104181339
- Standard installation

#### Connection specification:
- Microsoft SQL Server 2016
- SQL Server -- class name com.microsoft.sqlserver.jdbc.SQLServerDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Have run a query from a CLR Table-Valued function

#### Steps to reproduce, if exist:
Create a CLR assembly in SQL Server, create a table-valued function.  Run a query
The query returns the column names, but not any values.
Not sure if it is limited to CLR table-valued functions, or if this is all table-valued functions

**Comment by LonwoLonwo** [comment]
Hello @lunarquaker 
Can you provide more details? Video of incorrect behavior or screens?
Also DDL of function will be very helpful.
Thanks in advance.

**Comment by ghost** [comment]
Hi @LonwoLonwo 

I am attaching two screen shots.   This is an internal company data set, so the data itself will not make sense to you.   But the behavior is not correct in dbeaver.   It returns columns, but no data.   SSMS returns fine.

This is a CLR table-valued function written in C# and deployed via assembly to SQL Server.
![ssms_tvf](https://user-images.githubusercontent.com/38664858/115589835-f1790880-a295-11eb-8feb-8eb7f8dbc028.GIF)
![dbeaver_tvf](https://user-images.githubusercontent.com/38664858/115589849-f63dbc80-a295-11eb-9456-df76da33a4ce.GIF)

**Comment by ghost** [comment]
@LonwoLonwo 

Another thing I found is that when I click on the row count refresh button, at the bottom, the correct number of rows can be shown, which in my case is 1024.   But again, no data shows  up.
![dbeaver_rowcount](https://user-images.githubusercontent.com/38664858/115591580-db6c4780-a297-11eb-9097-5a0c646e49b8.GIF)

**Comment by LonwoLonwo** [comment]
![115589849-f63dbc80-a295-11eb-9456-df76da33a4ce](https://user-images.githubusercontent.com/45152336/115670166-c94edf80-a351-11eb-98c2-c6464c8c6f81.GIF)

Text presentation is also incorrect?

May be you can provide DDL of function and simple data for testing?

**Comment by ghost** [comment]
@LonwoLonwo 

The text presentation is also incorrect.   I have seen your request for a DDL but am having trouble reproducing it in a simple manner for debugging.   The function in the screen shots has a lot of dependencies on our internal data.  I will let you know if I come up with something.   Is there anything you can do to investigate without this?

**Comment by ghost** [comment]
@LonwoLonwo 

Here's another data point.   It worked fine when I ran the "Export from Query" option and saved the results to a file.   It is just not working in the viewer.

![export_from_query](https://user-images.githubusercontent.com/38664858/115746294-d5d73600-a359-11eb-9285-7797856da65b.png)

**Comment by LonwoLonwo** [comment]
ok, thanks for investigation!

**Comment by ShadelessFox** [comment]
Hello @lunarquaker,

I cannot reproduce your issue. The results are present in the result set view:
![image](https://user-images.githubusercontent.com/35821147/120305864-ede79100-c2d9-11eb-8c14-0be071cfeaf1.png)

The assembly was made by following this manual:
https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration-database-objects-user-defined-functions/clr-table-valued-functions

Can you try upgrading to newer version of DBeaver?

**Comment by ShadelessFox** [comment]
If the issue is still relevant to you - feel free to reopen
