### ISSUE TITLE
Easy collection of bug metadata

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#12169]
Just now I had to struggle again, to find out what driver the PostgreSQL connection uses -- in fact, I didn't find out, I just guessed from the available JARs in the `drivers` folder.

It seems unnecessary hard to gather that kind of information.
I propose an entry similar to 
`Help -> Installation information -> [Tab] Configuration`
that lists all information possibly required (operating system, version, dbeaver version, java version, configured databases with drivers) and upon a button click copies that stuff to the clipboard.

After pasting, one may easily remove the parts not perataining to the current reports (mostly other databases, I guess), but without need to wander through several UIs hoping to gather everything together.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by ShadelessFox** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/35821147/121375068-1bbb7e00-c949-11eb-8e3f-d7831784376c.png)

It can be opened by clicking <kbd>Details</kbd> in the connection test dialog.
For now, we decided to display only basic information about connection here, nothing more.
Other information (like Java version, etc.) you can find in the <kbd>Installation Information</kbd> mentioned earlier.

**Comment by Matvey16** [comment]
Verified
