### ISSUE TITLE
Dbeaver无法正常启动，报错Path must include project and resource name: /General

### ISSUE THREAD

**Issue by adonis-kun** [dbeaver/dbeaver#12171]
Dbeaver无法正常启动，报错Path must include project and resource name: /General.
原因为在DBeaver配置中，将Navigator bookmarks、ER diagrams置空，现无法正常启动。看过之前也有人遇到过，issues中无解决方案，所以再次提问。

**Comment by uslss** [comment]
@adonis-kun could you provide more clear steps to reproduce an issue in english?

**Comment by adonis-kun** [comment]
I click the configure button next to Project-General, and then choose DBeaver Settings. In the window on the right, shows Navigator bookmarks, ER diagrams and SQL scripts. I double click the bookmarks, and choose General, the Navigator bookmarks folder is empty. And then choose apply and close.  When I restart the program, it keeps reporting errors. Thanks for your reply.

**Comment by adonis-kun** [comment]
I attampt to reset the workspace, but it has no sence. report error again and again.

**Comment by adonis-kun** [comment]
As a workaround you could open %APPDATA%\DBeaverData\workspace6\General.settings\org.jkiss.dbeaver.project.resources.prefs e.g. in notepad and delete resourceRootFolder/bookmarks= from file and than save it
