### ISSUE TITLE
Cannot add/update arrays using UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#12179]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.0.3

#### Connection specification:
- Database name and version Clickhouse
- Driver name clickhouse-jdbc 0.2.6

#### Describe the problem you're observing:
Cannot add LowCardinality(string) value using UI
![image](https://user-images.githubusercontent.com/31996417/115386628-4d825500-a1e2-11eb-8df6-f1a2a1d8e249.png)
Generated script:
-- Auto-generated SQL script #202104201410
INSERT INTO default.array_type (id,strings)
	VALUES (3,test);

The value could be added in case of generated script is executed manually in SQL editor

**Comment by ShadelessFox** [comment]
Looks like an issue of the ClickHouse JDBC driver. We should create a ticket on their board referring this issue as a source.

**Comment by ShadelessFox** [comment]
Fixed adding and altering.

**Comment by Matvey16** [comment]
Verified
