### ISSUE TITLE
Multiple query in single tab

### ISSUE THREAD

**Issue by ujjwal-innocirc** [dbeaver/dbeaver#12189]
Hi team,
Please provide a feature where more than one result can be viewed in single tab

**Comment by uslss** [comment]
@ujjwal-innocirc please, provide more info about what you're talking about and how you think it should look like. Screenshots will be very helpful too

**Comment by ujjwal-innocirc** [comment]
Hi Team,
Its a feature request where i can execute two query in one go. Right now it is possible but the result set is coming in two different tabs. My request is to bring these results in one tab one above the another.


Kumar Ujjwal

Software Engineer, MyHealthcare (a digital health ecosystem)

Email: ***@***.******@***.***> I Mobile: +91 9555695547

Website: http://www.myhealthcare.co

Delhi  I Bangalore  I Kuala Lumpur  I Jakarta  I Hong Kong

________________________________

**Comment by uslss** [comment]
duplicates #6328

**Comment by ujjwal-innocirc** [comment]
Hi Team,
It will be very useful if you incorporate my request. Although you have marked it as Closed.


Kumar Ujjwal

Software Engineer, MyHealthcare (a digital health ecosystem)

Email: ***@***.******@***.***> I Mobile: +91 9555695547

Website: http://www.myhealthcare.co

Delhi  I Bangalore  I Kuala Lumpur  I Jakarta  I Hong Kong

________________________________
