### ISSUE TITLE
Hana - field autocompletion does not work

### ISSUE THREAD

**Issue by maritogaleano** [dbeaver/dbeaver#12185]
After the update from version 21.0.1 to version 21.0.3 it no longer suggests the name of the table fields

![image](https://user-images.githubusercontent.com/57814047/115451120-c9809b00-a1ea-11eb-8ddd-454012ecdbce.png)
**Version 21.0.3**

![image](https://user-images.githubusercontent.com/57814047/115451362-182e3500-a1eb-11eb-9e7b-074e7fd58837.png)

**Version 21.0.1**

**Comment by LonwoLonwo** [comment]
Hello @maritogaleano 
Thanks for the bug report.
We are getting to fix it soon.

As a workaround for now - you can use table aliases. It can works, if you add any alias after table name.
As example:
"SELECT * FROM ORDR o
WHERE docn"

**Comment by maritogaleano** [comment]
> Hello @maritogaleano
> Thanks for the bug report.
> We are getting to fix it soon.
> 
> As a workaround for now - you can use table aliases. It can works, if you add any alias after table name.
> As example:
> "SELECT * FROM ORDR o
> WHERE docn"

Thank you very much for your answer @LonwoLonwo

**Comment by maritogaleano** [comment]
Update to version 21.0.4 and the bug persists 
![image](https://user-images.githubusercontent.com/57814047/116898674-ad2a2880-ac04-11eb-8068-f3f77c49cedb.png)

**Comment by LonwoLonwo** [comment]
Fixed in scope with https://github.com/dbeaver/dbeaver/issues/12289
Will be available in DBeaver 21.0.5

**Comment by uslss** [comment]
verified
