### ISSUE TITLE
mssql - missing extended properties

### ISSUE THREAD

**Issue by aisbergde** [dbeaver/dbeaver#12196]
Maybe this is not a bug, but a feature request

#### System information:
- Operating system (distribution) and version: Windows 10
- DBeaver Version 21.0.3.202104181339
- Additional extensions

#### Connection specification:
- Database name and version: SQL Server 2017, 2019
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Missing support for extended properties in dbeaver

#### Steps to reproduce, if exist:

Create a table (or view or other objects) containing extended properties
- for the object
- for columns

```sql
Create Table [dbo].[zzz](
	[aaa] [Int] Null
) On [PRIMARY]
Go

Exec sys.sp_addextendedproperty @name=N'RepoObjectColumn_guid', @value=N'8198f068-ca9d-eb11-84f6-a81e8446d5b0' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'zzz', @level2type=N'COLUMN',@level2name=N'aaa'
Go

Exec sys.sp_addextendedproperty @name=N'RepoObject_guid', @value=N'8098f068-ca9d-eb11-84f6-a81e8446d5b0' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'zzz'
Go
```

check the object in dbeaver DDL

```sql
-- Drop table

-- DROP TABLE dhw_self.dbo.zzz;

CREATE TABLE dhw_self.dbo.zzz (
	aaa int NULL
);
```

extended properties are missing

**Comment by ShadelessFox** [comment]
Implemented (for tables and their columns only):

![java_lLWOQ9n4KM](https://user-images.githubusercontent.com/35821147/119346789-56fc5280-bca3-11eb-98a2-6cd65d377fef.png)
![java_PtnztU0Zo7](https://user-images.githubusercontent.com/35821147/119346792-582d7f80-bca3-11eb-9a8f-0754e8853973.png)

**Comment by Matvey16** [comment]
Verified
