### ISSUE TITLE
leading zeroes in VARBIT truncated

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#12199]
#### System information: 
- Kubuntu 20.04
- DBeaver version: 21.0.3

#### Connection specification:
- Postgresql
- PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:

If VARBIT value contains leading-zeroes, those are truncated in DBeaver views. This way the user lost information about size of the varbit. 

For example:

![image](https://user-images.githubusercontent.com/7868445/115566086-3dd63f80-a2ba-11eb-8748-56834b7a7147.png)

Expected behavior (screenshot taken from psql):

![image](https://user-images.githubusercontent.com/7868445/115565522-bbe61680-a2b9-11eb-803c-9238870211f0.png)

#### Steps to reproduce, if exist:

See above

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
verified
