### ISSUE TITLE
Some columns do not show in View - Redshift

### ISSUE THREAD

**Issue by ARod001** [dbeaver/dbeaver#12204]
View columns do not show when expanding columns - however they do show on query result

**Comment by uslss** [comment]
@ARod001 could you provide a table and view DDLs that will help to reproduce an issue?
also, which dbeaver version do you use?
Is the issue reproducible for all the views or only with some special?

**Comment by ARod001** [comment]
Thanks Dziyana

1)  I don’t think so – I can provide a screenshot though (below).
2)  Version 21.0.2.202104042040
3)  All views

It seems like the columns missing are DATE data types.

***@***.***D73765.6FF4AE90]






Alberto Rodriguez
Business Analyst
Commercial Services - USNG
desk: 832-320-5393  mobile: 281-382-4767
TC Energy.com<https://www.tcenergy.com/>

From: Dziyana ***@***.***>
Sent: Thursday, April 22, 2021 3:51 AM
To: dbeaver/dbeaver ***@***.***>
Cc: Alberto Rodriguez ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [dbeaver/dbeaver] Some columns do not show in View - Redshift (#12204)


@ARod001<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ARod001&d=DwMCaQ&c=Q5SXlsxPryShfyrkNJViwkWBHuTWASXd1LyNpDogBFY&r=5FaM3O5EoFL10otWsbciM-wmUiowDpzvuuWxuZ8JLsQ&m=vToe7LV98xbIH0JFVkXH1nekexVuFAaIrpv70E5cMxg&s=Nluep_SCZVV7f3n01Soc_iLGcwm_6jJ65KspCQNBNp8&e=> could you provide a table and view DDLs that will help to reproduce an issue?
also, which dbeaver version do you use?
Is the issue reproducible for all the views or only with some special?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dbeaver_dbeaver_issues_12204-23issuecomment-2D824662886&d=DwMCaQ&c=Q5SXlsxPryShfyrkNJViwkWBHuTWASXd1LyNpDogBFY&r=5FaM3O5EoFL10otWsbciM-wmUiowDpzvuuWxuZ8JLsQ&m=vToe7LV98xbIH0JFVkXH1nekexVuFAaIrpv70E5cMxg&s=DmbNFsvdYbbEOPsyQ4sYO6kZaVPE08bjBck2_WmUUZI&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ATZCYCJIV3ZA3HJZ5TNUUE3TJ7PP3ANCNFSM43LGF7OA&d=DwMCaQ&c=Q5SXlsxPryShfyrkNJViwkWBHuTWASXd1LyNpDogBFY&r=5FaM3O5EoFL10otWsbciM-wmUiowDpzvuuWxuZ8JLsQ&m=vToe7LV98xbIH0JFVkXH1nekexVuFAaIrpv70E5cMxg&s=zu5vgX5PCjYWc4Zd1azt02c_Zair2_yQw0cv2bgh1kc&e=>.

----------------------------------------------------------------------






We respect your right to choose which electronic messages you receive. To stop receiving this and similar communications from TC Energy please Click here to unsubscribe.



If you are unable to click the request link, please reply to this email and change subject line to "UNSUBSCRIBE".
 
This electronic message and any attached documents are intended only for the named addressee(s). This communication from TC Energy may contain information that is privileged, confidential or otherwise protected from disclosure and it must not be disclosed, copied, forwarded or distributed without authorization. If you have received this message in error, please notify the sender immediately and delete the original message. 

Thank you

**Comment by LonwoLonwo** [comment]
May be some connection is with this ticket https://github.com/dbeaver/dbeaver/issues/10703

**Comment by ARod001** [comment]
I saw that but it was closed and resolved and it did not seem to apply.  Issue is still happening as described

Alberto Rodriguez
Business Analyst
Commercial Services - USNG
desk: 832-320-5393  mobile: 281-382-4767
TC Energy.com<https://www.tcenergy.com/>

From: Anastasiya ***@***.***>
Sent: Friday, April 23, 2021 9:27 AM
To: dbeaver/dbeaver ***@***.***>
Cc: Alberto Rodriguez ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [dbeaver/dbeaver] Some columns do not show in View - Redshift (#12204)


May be some connection is with this ticket #10703<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dbeaver_dbeaver_issues_10703&d=DwMCaQ&c=Q5SXlsxPryShfyrkNJViwkWBHuTWASXd1LyNpDogBFY&r=5FaM3O5EoFL10otWsbciM-wmUiowDpzvuuWxuZ8JLsQ&m=CcVOapXctABc3xf7moX35oy0cGbf-OBXLsfjFsQNElQ&s=Yy7OosAzLrRBtWhU_o_LwAXUGk8oaaH4MwXaLNVVeGc&e=>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dbeaver_dbeaver_issues_12204-23issuecomment-2D825696625&d=DwMCaQ&c=Q5SXlsxPryShfyrkNJViwkWBHuTWASXd1LyNpDogBFY&r=5FaM3O5EoFL10otWsbciM-wmUiowDpzvuuWxuZ8JLsQ&m=CcVOapXctABc3xf7moX35oy0cGbf-OBXLsfjFsQNElQ&s=6o9N22ZdtSbgZXcwY9XlKDTlg6F2CaFLOsoNl9F4pN4&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ATZCYCIK3JIIHRV2NNCFR33TKF7SXANCNFSM43LGF7OA&d=DwMCaQ&c=Q5SXlsxPryShfyrkNJViwkWBHuTWASXd1LyNpDogBFY&r=5FaM3O5EoFL10otWsbciM-wmUiowDpzvuuWxuZ8JLsQ&m=CcVOapXctABc3xf7moX35oy0cGbf-OBXLsfjFsQNElQ&s=lCOcgz-1zQrDl_FrE0QnypW2OA053RMJZLhFLl19hu0&e=>.

----------------------------------------------------------------------






We respect your right to choose which electronic messages you receive. To stop receiving this and similar communications from TC Energy please Click here to unsubscribe.



If you are unable to click the request link, please reply to this email and change subject line to "UNSUBSCRIBE".
 
This electronic message and any attached documents are intended only for the named addressee(s). This communication from TC Energy may contain information that is privileged, confidential or otherwise protected from disclosure and it must not be disclosed, copied, forwarded or distributed without authorization. If you have received this message in error, please notify the sender immediately and delete the original message. 

Thank you

**Comment by LonwoLonwo** [comment]
Can't reproduce with date type column.

![2021-04-29 15_58_18-DBeaver Enterprise 21 0 4 - test_date](https://user-images.githubusercontent.com/45152336/116554554-fe37d500-a903-11eb-9ff2-f0c173fb094e.png)

@ARod001 
Can you attach here (in Github) your screenshot manually please? I can't see it in your email-version answer.

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual for you, feel free to reopen an issue
