### ISSUE TITLE
DBeaver keeps using high CPU

### ISSUE THREAD

**Issue by qiqingli** [dbeaver/dbeaver#12209]
#### System information: 
- Operating system (distribution) and version：macOS Big Sur 11.2.3
- DBeaver version：21.0.3
- Additional extensions

#### Describe the problem you're observing:
DBeaver is using too much CPU and keeps using high CPU even though it is not doing any operation.

![image](https://user-images.githubusercontent.com/20805098/115689666-e2c24c80-a38e-11eb-9940-ee12eca90588.png)

**Comment by kseniiaguzeeva** [comment]
Sorry for the long response. Could you give more details? 
- Does it happen right after launching DBeaver or after some time?
- What do you do in DBeaver before it happens?
- Do you work with remote or local database?
- [Error logs](https://github.com/dbeaver/dbeaver/wiki/Log-files) also can be helpful.

**Comment by qiqingli** [comment]
- Does it happen right after launching DBeaver or after some time?
   It happened after some time.
- What do you do in DBeaver before it happens?
  No special operations are performed.
- Do you work with remote or local database?
  Work with remote database.
- Error logs also can be helpful.
  Cannot reproduce, cannot get logs

**Comment by kseniiaguzeeva** [comment]
Some CPU issues were fixed in https://github.com/dbeaver/dbeaver/issues/11368. You can try [EA](https://dbeaver.io/files/ea/) or wait for the next release 21.0.0 (release date 31.05.21)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info.

**Comment by jacekgajek** [comment]
I have this issue too, DBeaver keeps using more and more CPU overtime, even if I just launch it. It uses about 30% of each core after startup.
![image](https://user-images.githubusercontent.com/68021034/205631702-5b01f995-c885-4627-bfcf-ff03875626d9.png)

![image](https://user-images.githubusercontent.com/68021034/205631781-ea075012-f766-4895-a9cf-c9a93639a021.png)

I use DBeaver mostly to browse ER diagrams. **Closing diagrams does resolve issue** – usage drops down to around 0% which is expected if don't interact with the app.

**Comment by jacekgajek** [comment]
Since this one is very old and probably unrelated, I've create a new post for the issue:
https://github.com/dbeaver/dbeaver/issues/18433
