### ISSUE TITLE
Snippets/CheatSheet/Template for database specific DDL SQL statements

### ISSUE THREAD

**Issue by wernerdaehn** [dbeaver/dbeaver#12205]
**Is your feature request related to a problem? Please describe.**

What was the exact statement to create a new user in SAP Hana via SQL again? I executed it last month and can't remember!
So I must open the browser, go to the database help page, find the command, scroll through the syntax page to find the relevant parts and then write it again crosschecking multiple times until I have:

```
CREATE USER <username> password "<pwd>" NO FORCE_FIRST_PASSWORD_CHANGE ;
```

Same with 100s of other rarely used commands.

Eclipse has multiple ways to support us here: 
- Code Snippet View
- CheatSheet View
- Code Template View
- Help system View
- Documentation View

If I am not mistaken the Cheat Sheet View would be a good place to collect these statements. Or maybe Code Templates as it is integrated with the auto complete? Not sure.

**Describe the solution you'd like**
What I do remember in such a case is the start of the statement: "create user ....", just the details I forgot. As soon as I start typing I would like to see all relevant commands as reminder how the complete command looks like.
One option is to show the relevant list of commands in an additional view on the right hand side.
The other option to use the autocomplete semantic.
Whatever works better. My fear with autocomplete is that it might get crowded by such secondary information.

**Alternate approach considered**
In the help system link to the official product documentation. These links are not always stable and we are at the mercy of the vendors. Also I do not care about all the 100 of options of the CREATE USER statement, the most often used examples count.

**Additional context**
The request is to create a mechanism for that, not to come up with all commands yourself. The list of commands we can collect in one external file for each database and slowly role into the product installer.

**Comment by uslss** [comment]
@wernerdaehn we've got such feature as SQL Templates - [here](https://github.com/dbeaver/dbeaver/wiki/SQL-Templates) you can learn more about it.
Could you check if it resolves your problem?

**Comment by wernerdaehn** [comment]
Yes, that is exactly what I was looking for!
