### ISSUE TITLE
Login with SSH to Azure DevOps seems not working anymore.

### ISSUE THREAD

**Issue by hennie7863** [dbeaver/dbeaver#12207]
It seems that after the update Deaver laest version I cannot pull code from my Git repo anymore.

The URI is now ssh://hennie.denxxijer%252525252540xxxx.nl@ssh.dev.azure.com:22
hennie.denxxijer%2525252540xxxxxx.nl

The strings %252525252540 seems awkward to me.

Git pull is working properly. SSH works right.

---- Here the window to set connection right. Configure Fetch and then Change.
![image](https://user-images.githubusercontent.com/7771436/115684607-c656ed80-a357-11eb-84bb-5ddf1940e957.png)

And here the window to fetch the code 👍 
![image](https://user-images.githubusercontent.com/7771436/115684749-eb4b6080-a357-11eb-974d-c39eb40db131.png)

Am I doing something wrong ?

**Comment by kseniiaguzeeva** [comment]
Could you please send [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by uslss** [comment]
there is no update on issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
