### ISSUE TITLE
Grouping panel does not allow grouping by expression anymore

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#12200]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 21.0.3.202104181339 (but was there in 21.0.2 as well)
- Additional extensions n/a

#### Connection specification:
- Database name and version Oracle 11
- Driver name ojdbc19
- Do you use tunnels or proxies (SSH, SOCKS, etc)? n/a

#### Describe the problem you're observing:
In grouping panel, expressions in the Columns section are surrounded by `"`, which leads to an error.
This once worked, altough I'm unable to pinpoint the exact version where it broke.

#### Steps to reproduce, if exist:
![immagine](https://user-images.githubusercontent.com/2157006/115568049-3152e680-a2bc-11eb-8b0c-4f994f8c4483.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
Ok, we will try to recognize the expression from "Columns" and add quotes only for column names, which must be quoted.
Fixed in DBeaver 21.2.2

**Comment by uslss** [comment]
verified
