### ISSUE TITLE
DB2 Query Result - display field description metadata in column when declaration contains join

### ISSUE THREAD

**Issue by ceugenio** [dbeaver/dbeaver#12219]
**WITHOUT JOIN** 

![image](https://user-images.githubusercontent.com/15365719/115832735-87866d80-a413-11eb-91aa-d8e56f6ec769.png)

**WITH JOIN**

![image](https://user-images.githubusercontent.com/15365719/115832900-b7ce0c00-a413-11eb-81b9-8df8ba639e3c.png)

Thank you,
Eugenio

**Comment by kseniiaguzeeva** [comment]
Sorry for the long response. I cannot reproduce it in DBeaver 21.0.5 EA. 

![dbeaver_ytkoDDAxhY](https://user-images.githubusercontent.com/51405061/118405750-daa1b800-b681-11eb-9d89-1af750be4442.png)

Some SQL fixes were made for release 21.0.5. Could you please try [EA](https://dbeaver.io/files/ea/) or new 21.0.5 release tomorrow?

If the issue still can be reproduced, please tell me the driver version (Press **Test connection** in Connection Properties for it)
![dbeaver_uYXeZXr9oe](https://user-images.githubusercontent.com/51405061/118405789-0f157400-b682-11eb-899e-6d0902303ec7.png)

**Comment by ceugenio** [comment]
Hi @kseniiaguzeeva,

I try with release 21.0.5 but the problem persists.


The driver that I use is below. 
![image](https://user-images.githubusercontent.com/15365719/118961690-e41e6f00-b964-11eb-8af0-2d74300d643b.png)



I try to use your driver but my AS400 refuse de connection on the port 50000 and I don't know why but the port is mandatory to confirm the connection settings 
![image](https://user-images.githubusercontent.com/15365719/118963042-53e12980-b966-11eb-95fc-3ea9a1153bb3.png)

**Comment by kseniiaguzeeva** [comment]
Seems to be a driver issue. DB2 LUW doesn't have such bug.

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update for a long time.
If it is still actual - feel free to reopen the issue.
