### ISSUE TITLE
DB2 CSV Export - header with field description metadata

### ISSUE THREAD

**Issue by ceugenio** [dbeaver/dbeaver#12220]
![image](https://user-images.githubusercontent.com/15365719/115833652-97528180-a414-11eb-82cd-3605c1e54c96.png)

![image](https://user-images.githubusercontent.com/15365719/115833801-c2d56c00-a414-11eb-81ec-e9d4ddce6872.png)

![image](https://user-images.githubusercontent.com/15365719/115834136-29f32080-a415-11eb-8803-c82e8b399586.png)

Thank you,
Eugenio

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/136671274-e8e6f4e8-7cf4-4567-a257-1da1e7c9eb2c.png)

CSV can't have two header lines (according to the CSV standard).
But we can change header format: show labels, description (comment) or both

**Comment by uslss** [comment]
verified

**Comment by ceugenio** [comment]
@serge-rider thank you a lot.
