### ISSUE TITLE
Excess parantheses 

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#12233]
### System information: 
- Linux Mint 19.3
- DBeaver version 7.2.4

#### Describe the problem you're observing:

type `SELECT date_trunc|()` then type `(` and you get `SELECT date_trunc(|()`

expected: `SELECT date_trunc(|)`

`|` is where cursor is

**Comment by kseniiaguzeeva** [comment]
Could you describe some use cases where it should work by this way?

**Comment by KES777** [comment]
Every editor when auto add characters does not double them when user input them manually


https://user-images.githubusercontent.com/799021/118136995-5cd57680-b40d-11eb-808c-5b6ef40e499d.mp4

**Comment by KES777** [comment]
[Kazam_screencast_00059.mp4.zip](https://github.com/dbeaver/dbeaver/files/6472901/Kazam_screencast_00059.mp4.zip)

**Comment by kseniiaguzeeva** [comment]
We will implement it. Thank you for the suggestion.

**Comment by uslss** [comment]
not actual for 23.0.3
