### ISSUE TITLE
After query execution results stays hidden

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#12237]
How to reproduce:
1. Hide query results
2. Edit query
3. Run query

expected: results should be displayed
actual: I need to press button to display result
![image](https://user-images.githubusercontent.com/799021/115965370-9f541380-a531-11eb-857d-c721a70dae2c.png)

here is two cases: when area is minimized is should stay same, but if it was hidden by button then results area should be restored automatically (as shown on picture above)

version is 21.0.3

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
