### ISSUE TITLE
wrong server timezone

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#12239]
dbeaver 21.0.3
Postgres 12

in my table timestamptz type column.

Select from this column give me date in wrong timezone.

For example pdAdmin give me date with server timezone by default.

What the timezone used in dbeaver i am do not understand. I see that this timezone is wrong, and dbeaver returned wrong date.

pgAdmin it is real data
![изображение](https://user-images.githubusercontent.com/61137576/115980683-0dd3b880-a5a8-11eb-9932-b607ddf728bf.png)

dbeaver 
![изображение](https://user-images.githubusercontent.com/61137576/115980713-36f44900-a5a8-11eb-801a-28207259ef6b.png)

**Comment by ShadelessFox** [comment]
Hello @detkliff,

Please take look at the timezone offset: `+05`.

* pgAdmin shows `14:30:00` with timezone of `GMT+3`, so `GMT+0` would be `11:30:00`.
* DBeaver shows `16:30:00` with timezone of `GMT+5`, so, `GMT+0` would be `11:30:00`.

As you can see, the time is valid, the only thing is differ is the timezone.

Actually, it may depend on the date/time settings of your OS.

**Comment by detkliff** [comment]
> 
> 
> Hello @detkliff,
> 
> Please take look at the timezone offset: `+05`.
> 
>     * pgAdmin shows `14:30:00` with timezone of `GMT+3`, so `GMT+0` would be `11:30:00`.
> 
>     * DBeaver shows `16:30:00` with timezone of `GMT+5`, so, `GMT+0` would be `11:30:00`.
> 
> 
> As you can see, the time is valid, the only thing is differ is the timezone.
> 
> Actually, it may depend on the date/time settings of your OS.

in other words I cannot see real data in database from dbeaver. I had 10 servers in different timezone, i should change date/time settings of my OS ten times for ever server and see data.
It is very bad and uncomfortable.

How i can set timezone for everyone connection individua?

**Comment by ShadelessFox** [comment]
Can you provide more information about your server? What does <kbd>Connection configuration</kbd> &rArr; <kbd>Test connection</kbd> shows to you?

**Comment by detkliff** [comment]
> 
> 
> Can you provide more information about your server? What does Connection configuration ⇒ Test connection shows to you?

i do not see this function in the interface.

**Comment by ShadelessFox** [comment]
![SQ0plKBNkJ](https://user-images.githubusercontent.com/35821147/116062323-75633400-a68c-11eb-9ee9-a3d7bcda1ad1.png)

**Comment by detkliff** [comment]
> 
> 
> ![SQ0plKBNkJ](https://user-images.githubusercontent.com/35821147/116062323-75633400-a68c-11eb-9ee9-a3d7bcda1ad1.png)

![изображение](https://user-images.githubusercontent.com/61137576/116071814-c6345600-a6a7-11eb-9f71-dd65e34ce314.png)

**Comment by ShadelessFox** [comment]
Now you can specify timezone for date/time formatters:
![image](https://user-images.githubusercontent.com/35821147/126294834-dfd58029-78fe-4c97-8a33-a96de79147ee.png)

**Comment by Matvey16** [comment]
Verified
