### ISSUE TITLE
Interface blinking

### ISSUE THREAD

**Issue by luiseduardo** [dbeaver/dbeaver#12232]
#### System information: 
- Operating system: Linux Mint 19.03 (Kernel Linux 5.4.0-72-generic x86_64 - MATE 1.22.2)
- DBeaver version: 21.0.3.202104181339
- Additional extensions: none

#### Connection specification:
- Driver name: org.mariadb.jdbc:mariadb-java-client:RELEASE - Version  2.4.3

#### Describe the problem you're observing:
Interface blinking when:
   - mouse hover tabs and toolbars
   - navigate in data grid with keyboard
   - while restore connection of the open tabs

**Comment by serge-rider** [comment]
It is Eclipse/GTK specific issue.
See comments in https://bugs.eclipse.org/bugs/show_bug.cgi?id=517671 and https://forums.linuxmint.com/viewtopic.php?t=316929 for a workaround.

**Comment by luiseduardo** [comment]
Its works, thanks ;-)
