### ISSUE TITLE
Copy and paste Geometry => Geometry SRID (0) does not match column 

### ISSUE THREAD

**Issue by chapmanjacobd** [dbeaver/dbeaver#12238]
#### System information: 
Windows 10
DBeaver version 21.0.3
POSTGIS="3.0.3 6660953" [EXTENSION] PGSQL="120" GEOS="3.9.1-CAPI-1.14.2" PROJ="7.2.1" LIBXML="2.9.1" LIBJSON="0.11" LIBPROTOBUF="1.0.2" WAGYU="0.4.3 (Internal)"

#### Connection specification:
- psql (PostgreSQL) 12.2

![image](https://user-images.githubusercontent.com/7908073/115974133-d1f11280-a517-11eb-9d79-f95177a25a3d.png)

#### Describe the problem you're observing:

SQL Error [22023]: ERROR: Geometry SRID (0) does not match column SRID (3395)
  ERROR: Geometry SRID (0) does not match column SRID (3395)
  ERROR: Geometry SRID (0) does not match column SRID (3395)

#### Steps to reproduce, if exist:

When copy-pasting from the right-column in the screenshot above to the left column. 

Dbeaver recognizes both column types correctly (Geometry(POINT,3395)).

It saves correctly if I copy to vs-code and append SRID=3395; to the front of the wkt, paste into the left column, and Ctrl+S.

Similar tickets:

https://github.com/dbeaver/dbeaver/issues/5881
https://github.com/dbeaver/dbeaver/issues/4461

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by uslss** [comment]
verified
