### ISSUE TITLE
Handle default emoju symbols at .sql files by default during saving

### ISSUE THREAD

**Issue by wvolkov** [dbeaver/dbeaver#12235]
Current version of DBeaver doesn't support emojis in sql code, it raises error:

![image](https://user-images.githubusercontent.com/49549154/115954477-f5a56000-a4f9-11eb-9521-69896d858b23.png)

It would be great to enable it by default

**Comment by serge-rider** [comment]
It is not an error but a sort of a warning. Just click on "Save as UTF-8".
I don't think that we should save in utf-8 by default. Some non ASCII symbol may be typed by mistake.

BTW default file encoding depends on your OS settings. Also you can change it in Preferences->General->Workspace.

**Comment by wvolkov** [comment]
ok, got it, thx for clarification
