### ISSUE TITLE
Add clikchouse functions to auto-complete feature

### ISSUE THREAD

**Issue by p0m1d0rka** [dbeaver/dbeaver#12241]
**Is your feature request related to a problem? Please describe.**
There are no autocomplection to clickhouse function

**Describe the solution you'd like**
I want to autocomplection like "toStartOf..."

list of finctions - https://clickhouse.tech/docs/en/sql-reference/functions/

I can pr some, but tell me plz, where i should wtite it.

TY

**Comment by LonwoLonwo** [comment]
Hello @p0m1d0rka 
Thanks for idea.
Unfortunately, we cannot add al the functions mentioned in the documentation - they are too much.
Can you make a list of the most commonly used features? It would be very helpful for us.

**Comment by p0m1d0rka** [comment]
ty for reply.
For me most frequently used functions are:

1. **aggregation functions**
 - sum()
 - min()
 - max()
 - count()
 - quantile()()
 - quantileExact()()
 - uniq
2. **string functions:**
 - concat()
 - substring()
 - match()
 - replaceOne()
 - replaceAll()
3. **time functions:**
 - toStartOfFifteenMinutes()
 - toStartOfFiveMinute()
 - toStartOfInterval()
 - now()
 4. **common**
  - if()
  - multiIf()
 
Also add engines into ddl will be very helpful.

**Comment by LonwoLonwo** [comment]
@p0m1d0rka 
Thanks for the list.

What about engines? 
We have engine info in table DDL

![2021-05-04 22_52_03-DBeaver Enterprise 21 0 4 - array_type](https://user-images.githubusercontent.com/45152336/117061925-70a51c80-ad2b-11eb-9619-6d4c55505856.png)

**Comment by p0m1d0rka** [comment]
I told about time when you create a table:
- no type helper
- no engine helper

but it's not very important 

![image](https://user-images.githubusercontent.com/15802963/117099760-b806c980-ad7a-11eb-9155-fd5f6eade5c2.png)

**Comment by LonwoLonwo** [comment]
More Clickhouse functions added in DBeaver 21.2.4

You can see the list here: https://github.com/dbeaver/dbeaver/commit/9d9c7f5e4085312c7d2856d57e82406d4771923b

**Comment by uslss** [comment]
verified
