### ISSUE TITLE
Can't start the program DBeaver, and shows the error Path must include project and resource name: /General

### ISSUE THREAD

**Issue by adonis-kun** [dbeaver/dbeaver#12248]
I click the configure button next to Project-General, and then choose DBeaver Settings. In the window on the right, shows Navigator bookmarks, ER diagrams and SQL scripts. I double click the bookmarks, and choose General, the Navigator bookmarks folder is empty. And then choose apply and close. When I restart the program, it keeps reporting errors. I attampt to reset the workspace, but it has no sence. report error again and again.

**Comment by uslss** [comment]
thanks for the report
As a workaround you could open %APPDATA%\DBeaverData\workspace6\General\.settings\org.jkiss.dbeaver.project.resources.prefs e.g. in notepad and delete `resourceRootFolder/bookmarks=` from file and than save it

**Comment by adonis-kun** [comment]
Thank you very much. It solved my problem perfectly.

**Comment by flambchap** [comment]
Fixed the issue. Now it's impossible to map a resource path to the project root. I also added a mechanism that automatically does what @uslss has suggested.

**Comment by Matvey16** [comment]
Verified
