### ISSUE TITLE
Refactor subsystem of leaflet.js tilelayers (only switching logic)

### ISSUE THREAD

**Issue by mkgrgis** [dbeaver/dbeaver#12247]
**Is your feature request related to a problem? Please describe.**
1. 
1.1 Select a point
![изображение](https://user-images.githubusercontent.com/41448637/116072761-30dd9580-a698-11eb-8528-b62f7e8f4918.png)
1.2 Change tilelayer to other => World map, no object 
Example - Result of OpenTopoMap => ArcGis cosmo
![изображение](https://user-images.githubusercontent.com/41448637/116073012-8154f300-a698-11eb-8b62-8be98301f797.png)

2. Very strange names for leaflet Tilelayers.
![изображение](https://user-images.githubusercontent.com/41448637/116072233-82395500-a697-11eb-84b3-df32df85c4b2.png)
In my configuration this layers has defined as

```
let baseLayersObj = {
                'Street': L.tileLayer('https://tile-{s}.opentopomap.ru/{z}/{x}/{y}.png', {minZoom: 1, maxZoom: 18, attribution: 'Map data: &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap</a> contributors, <a href="http://viewfinderpanoramas.org">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a>, <a href="https://opentopomap.ru">OpenTopoMap.ru</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)'}),
                'Topography': L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
                  {
                    maxZoom: 17,
                    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a>,' +
                      ' &copy; <a href="http://viewfinderpanoramas.org" target="_blank">SRTM</a>,' +
                      ' &copy; <a href="https://opentopomap.org" target="_blank">OpenTopoMap</a>',
                  }),
            };
```

**Describe the solution you'd like**
Maybe, in all cases add all of layers with current CRS (ESPG code) to web application and switch through a signal to JavaScript in WebKit?
`Tilelayer` isn't hard calculated object for `leaflet.js` in opposite to wkx geometry.

**Comment by kseniiaguzeeva** [comment]
Unfortunately I cannot reproduce it.  Could you please send table/column DDL and a cell value to reproduce it?
Which DBeaver version do you use?

**Comment by mkgrgis** [comment]
In 21.0.5 this problem still actual. I make switching by this button in centre 
![изображение](https://user-images.githubusercontent.com/41448637/118527400-f07ab000-b749-11eb-8cf7-99bfd885e349.png)

A cell value POINT (30.4723975 59.6924162) , but it seems the issue depends on value not.

**Comment by kseniiaguzeeva** [comment]
Still cannot reproduce. Could please send a video how it happened?

**Comment by mkgrgis** [comment]
In a moment of changing map provider zoom switches to 0 (full planetary map) and a point clears (no point on map). Hmm... to make video will be a problem. I'll to study a programs for video catching.

**Comment by mkgrgis** [comment]
There is live demonstration, @kseniiaguzeeva 
![gis problem](https://user-images.githubusercontent.com/41448637/119931765-ab951b80-bf8a-11eb-8fe5-b612c3044e5f.gif)

**Comment by kseniiaguzeeva** [comment]
Could you please also provide me with information about your OS. Does it happen with any geometry types? Could you please tell what database driver do you use?

**Comment by mkgrgis** [comment]
PostGIS 3.0, Postgres 13, standard JDBC for postgresql, Ubuntu 20.
This problem is about all of geometry types.
![изображение](https://user-images.githubusercontent.com/41448637/121039977-36abb800-c7ba-11eb-8db5-29f4bd3b7e38.png)

I think the problem is inside of https://github.com/dbeaver/dbeaver/tree/devel/plugins/org.jkiss.dbeaver.data.gis.view

**Comment by Matvey16** [comment]
Already fixed. Feel free to reopen if the issue is still actual for you

**Comment by mkgrgis** [comment]
@Matvey16,
21.1.5 still actual. Maybe, I need resetting of a cache? Where is it?
