### ISSUE TITLE
Ctrl+F Search cannot find formatted numbers

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12257]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.0.4 EA

#### Steps to reproduce, if exist:

1. Open a table where a formatted number exists (e.g. 9,898) and press Ctrl+F
2. Enter an unformatted number (e.g. 9898) into Search field and begin the search

**Expected**: the number is found
**Actual result**: the number is not found

**Comment by ShadelessFox** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/35821147/117760381-36a5b000-b22e-11eb-8720-948effdcd745.png)

**Comment by kseniiaguzeeva** [comment]
verified
