### ISSUE TITLE
Beautiful check box is not displayed

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#12254]
After upgrading from 7.2.24 to 21.0.3 beautiful check box is not displayed:

![image](https://user-images.githubusercontent.com/799021/116118229-c0e60400-a6c5-11eb-8c6e-167c262934bd.png)

**Comment by uslss** [comment]
@KES777 You could change Booleans view in Preferences
![image](https://user-images.githubusercontent.com/31996417/116206593-a3f21500-a747-11eb-8d2b-0838e0229a31.png)

**Comment by mkgrgis** [comment]
"True/false" is SQL constants, but why "Yes/No" isn't NLS strings?

**Comment by KES777** [comment]
restored view. Thank you
![image](https://user-images.githubusercontent.com/799021/116261803-ad4ba380-a780-11eb-978e-3ca57574580d.png)

**Comment by KES777** [comment]
Would be nice if upgrading apply current behavior instead of providing new configurations
