### ISSUE TITLE
PPA does not work with Ubuntu 21.04

### ISSUE THREAD

**Issue by chrisvdb** [dbeaver/dbeaver#12267]
The instructions on [https://launchpad.net/~serge-rider/+archive/ubuntu/dbeaver-ce](https://launchpad.net/~serge-rider/+archive/ubuntu/dbeaver-ce) do not work on Ubuntu 21.04.

E: The repository 'http://ppa.launchpad.net/serge-rider/dbeaver-ce/ubuntu hirsute Release' does not have a Release file.

**Comment by schmitzkr** [comment]
This also was not working in groovy for the latest version of dbeaver.  
Launch pad only has version 21.0.2
https://launchpad.net/~serge-rider/+archive/ubuntu/dbeaver-ce

**Comment by schmitzkr** [comment]
This appears to be resolved now.  Than you!

**Comment by chrisvdb** [comment]
Thank you for the prompt action on this!
