### ISSUE TITLE
Oracle Function-based indexes shows columns with duplicate position and wrong expression

### ISSUE THREAD

**Issue by Bart-De-Pauw** [dbeaver/dbeaver#12261]
#### System information: 
- Operating system: Windows Server 2016 Version 1607
- DBeaver version: 21.0.3 ce
- Additional extensions: not applicable

#### Connection specification:
- Database name and version: Oracle 12.1.0.2.0
- Driver name: ojdbc8 19.3.0.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? not applicable

#### Describe the problem you're observing:
When viewing function-based indexes in oracle, it shows duplicate position and wrong expression
Only visible after expanding the index name by pressing the '>' symbol in front of the index name.
Sorting the columns does not help.

![image](https://user-images.githubusercontent.com/83295607/116267931-1fba8480-a77d-11eb-8561-6b9bcd99ad7b.png)

#### Steps to reproduce, if exist:
```
CREATE TABLE DEPT2 (DEPTNO NUMBER(2,0), DNAME VARCHAR2(14), LOC VARCHAR2(13));

CREATE INDEX dept2_idx1    ON dept2(dname);                    --correctly displayed
CREATE INDEX dept2_idx2    ON dept2(dname,loc);                --correctly displayed
CREATE INDEX dept2_fb_idx1 ON dept2(lower(dname));             --correctly displayed
CREATE INDEX dept2_fb_idx2 ON dept2(lower(dname),lower(loc));  --displays duplicate position, expression is correct
CREATE INDEX dept2_fb_idx3 ON dept2(lower(loc));               --correctly displayed
CREATE INDEX dept2_fb_idx4 ON dept2(lower(loc),lower(dname));  --displays duplicate POSITION, expression is wrong

```

**Comment by LonwoLonwo** [comment]
Thanks for the bug report.

**Comment by ShadelessFox** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/35821147/120327551-8c7fec00-c2f2-11eb-84ce-706bd0810fc6.png)

**Comment by Matvey16** [comment]
Verified

**Comment by Bart-De-Pauw** [comment]
Thank you for the swift resolution! Keep up the good work.
