### ISSUE TITLE
cannot connect to database 

### ISSUE THREAD

**Issue by wiebereu** [dbeaver/dbeaver#12263]
This week I run into Dbeaver which from what I see till now is the right tool for me to manage databases. 
Before I start I want to say that I'm not sure if this a bug report that I have to make because I don't know what is the cause of my problem. 
As I said I installed the Dbeaver 21.0.3 and wanted to connect to a MySQL database running on Unbuntu 20.10. To be complete, I installed Unbuntu and after that, I Installed MySQL version 8.0.23. Everything goes fine except for connecting to the database with Dbeaver. If I test the tunnel configuration I work well, but if I try to test the connection I get an error that said:
Communications link failure

**The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
  Connection refused: connect
  Connection refused: connect**

I searched on the Internet and saw a lot of stuff related to my problem and I tried almost every one of the so-called solutions but to no avail. Till now I can't get the database connected I am not an experienced Linux user, I just started to work on that and that is partly the reason that I'm doing this.  

In trying to search for the cause of the problem I installed Dbeaver on a Linux machine but the result was exactly the same as on the Windows Machine, no connection possible with the message that the connection refused. 
I hope I can solve the problem with your help. 
Thank you

**Comment by wiebereu** [comment]
How long i have to wait for a review? Forgive for asking but i don't understand why my issue has to take 2 days for review

**Comment by mkgrgis** [comment]
Try to find out the status of the MySQL / MariaDB port. Will it accept connections? If so, try connecting with a regular MySQL / MariaDB command line client with the same username. If it works, then the problem is in DBeaver or in the driver. But this is rarely case.

**Comment by wiebereu** [comment]
I solve it. The problem was in the default configuration of MySQL. 
By default, you cannot log in remotely to the database. Especially not as root. 
To change that you will have to edit your mysqld.cnf file in the /etc/mysql/mysql/conf.d/ folder
There you can add a line that said **bind-address = 0.0.0.0** meaning from any IP or put in a specific Ip that can connect to the database. 
Then you log in directly to the database (not remotely since that is not possible) 
You log in to MySQL and give the user account you want to access the database all privileges. If the user is not root which is a good idea in terms of security, you will have to create the user first. After that, you Grant the User privilege access from a specific IP or from any IP. 
It cost me a week to figure out. I hope this will help others
