### ISSUE TITLE
database > set as default not working as expected

### ISSUE THREAD

**Issue by philmassie** [dbeaver/dbeaver#12272]
#### System information: 
- Windows 10
- DBeaver Version 21.0.3.202104181339
- Athena driver

#### Connection specification:
- AthenaJDBC42.jar ver: SimbaAthenaJDBC-2.0.16.1000
- AthenaJDBC42.jar
- No 

#### Describe the problem you're observing:
Right click database name > set as default 
- leads to every query addressing a database called "default"

#### Steps to reproduce, if exist:
eg right click on database named "mydatabase" > set as default 
- querying a table names "mytable" with something like:
```
SELECT mycolumn FROM mytable limit 5;
```
results in the following error:
```
SQL Error [100071] [HY000]: [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. SYNTAX_ERROR: line 2:6: Table myawsdatacatalogue.default.mytable does not exist [Execution ID: 029c6161-8ac7-4cb4-8802-3d0087b8fdd2]
```

SO I suppose instead of:
```
SELECT mycolumn FROM mydatabase.mytable limit 5;
```
The query being built is:
```
SELECT mycolumn FROM default.mytable limit 5;
```

**This might be important***
We do have a database named `default` and I'm wondering if this might be causing issues? We cant delete this unfortunately.

#### Include any warning/errors/backtraces from the logs
```
SQL Error [100071] [HY000]: [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. SYNTAX_ERROR: line 2:6: Table myawsdatacatalogue.default.mytable does not exist [Execution ID: 029c6161-8ac7-4cb4-8802-3d0087b8fdd2]
```

**Comment by uslss** [comment]
thanks for the report
duplicates #11196

**Comment by philmassie** [comment]
Right Sorry about that - missed it.
