### ISSUE TITLE
Composite type columns cannot be exported with enabled Show complex data structure

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#12279]
#### System information: 
- DBeaver version 21.0.3

#### Connection specification:
- Database name and version: Postgres 13.1

#### Describe the problem you're observing:
```sql
select 1 as x, t as torder from table t;
```

#### Steps to reproduce, if exist:
1. Select column `x`
2. Select some columns from composite type `torder`

![image](https://user-images.githubusercontent.com/799021/116434921-87430380-a853-11eb-9bd9-8d44c12d2bd1.png)

3. Export as csv

Actual: Everything selected at composite is not exported
Expected: All selected columns should be exported

**Comment by kseniiaguzeeva** [comment]
Unfortunately I cannot reproduce it. Could you please send table DDL and query example to reproduce?

**Comment by KES777** [comment]
I send everything you need to reproduce it.

See additionally video:
[Kazam_screencast_00060.mp4.zip](https://github.com/dbeaver/dbeaver/files/6495009/Kazam_screencast_00060.mp4.zip)

**Comment by kseniiaguzeeva** [comment]
This file doesn't work on my computer. Could you please send it to kseniia@jkiss.org?

**Comment by KES777** [comment]
done

**Comment by KES777** [comment]
![image](https://user-images.githubusercontent.com/799021/119107716-2a88d200-ba28-11eb-88f0-3cbc3576bc71.png)

1. run this query (pay attention that whole-row value is selected) :
`select p from period p`;
2. select few columns (on screen that are: interval, trunc_iterval )
3. export as csv

actual: you get empty columns
expected: data for selected columns

**Comment by kseniiaguzeeva** [comment]
Reproduced. It's actual, when you try to export a composite type column in any format with enabled Show complex data structure. Thank you for the bug report.

**Comment by KES777** [comment]
Can I ask you put notices about what was wrong/was unclear at my first post? So next time I describe problem more clear.
Thank you.

**Comment by kseniiaguzeeva** [comment]
It was misunderstanding from my side.

**Comment by KES777** [comment]
Glad to hear that I do right thing. 

Thank you for you and your team.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
