### ISSUE TITLE
Explain Execution Plan not working with MySQL for query that uses CTE

### ISSUE THREAD

**Issue by OldrichDlouhy** [dbeaver/dbeaver#12274]
#### System information: 
- Windows 10 64bit (
- DBeaver version 2.1.03

#### Connection specification:
- MySQL 8.18
- Driver name MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When the MySQL query uses the CTE (common table expression), attempt to explain the query ends with error "Only SELECT statements could produce execution plan".

MySQL Workbench can explain the query without issues.

#### Steps to reproduce, if exist:

1. Have a simple query with CTE:
``` MySQL
WITH CTE AS (SELECT * FROM MyTable)
SELECT * FROM CTE;
```

2. Execute "Explain Execution Plan" by pressing `CTRL+SHIFT+E`
3. Error "Only SELECT statements could produce execution plan" shows up.

4. Modify the query to run EXPLAIN directly:
``` MySQL
EXPLAIN
WITH CTE AS (SELECT * FROM MyTable)
SELECT * FROM CTE;
```
5. Execute the query - it runs and returns result
```
id|select_type|table  |partitions|type|possible_keys|key|key_len|ref|rows|filtered|Extra|
--+-----------+-------+----------+----+-------------+---+-------+---+----+--------+-----+
 1|SIMPLE     |MyTable|          |ALL |             |   |       |   |  60|   100.0|     |
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by Matvey16** [comment]
Verified
