### ISSUE TITLE
SCRAM authentication is not supported by this driver.

### ISSUE THREAD

**Issue by securit** [dbeaver/dbeaver#12284]
#### System information: 
- MacOS Big Sur v11.3
- DBeaver Version 21.0.3.202104181339
- Additional extensions

#### Connection specification:
- PostgreSQL with PostGIS
- PostgreSQL 13.2 (postgresql-42.2.3.jre7.jar, postgis-jdbc-2.2.1.jar, postgis-geometry-2.5.0.jar)
- No 

#### Describe the problem you're observing:
SCRAM authentication is not supported by this driver. You need JDK >= 8 and pgjdbc >= 42.2.0 (not ".jre" versions)

#### Steps to reproduce, if exist:
Attempting to connect to a PostgreSQL 13.1 database on a docker instance with TLSv1.2 installed, I get the error

#### Include any warning/errors/backtraces from the logs
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/6395321/dbeaver-debug.log)

dbeaver-instance.properties contains
```
#DBeaver instance server properties
#Thu Apr 29 10:47:50 NZST 2021
port=55324
```

dbeaver-workspace.properties contains
```
#DBeaver workspace version
#Thu Apr 29 10:47:45 NZST 2021
product-version=21.0.3.202104181339
workspace-id=D13781O419EFGO
product-name=DBeaver
```

**Comment by kseniiaguzeeva** [comment]
Sorry for the long response. Could you please try another driver?

**Comment by securit** [comment]
I manually updated the drivers as below and they worked. I wonder why the most recent drivers were not part of the standard install?
<img width="755" alt="Screen Shot 2021-05-20 at 9 31 17 AM" src="https://user-images.githubusercontent.com/168565/118887285-40c25f80-b94e-11eb-8422-58ad507c4716.png">

**Comment by serge-rider** [comment]
We need to upgrade default driver version to a more recent one.

**Comment by serge-rider** [comment]
PostgreSQL driver updated to 42.2.20, Postgis to 2.5.0

**Comment by Matvey16** [comment]
Verified

**Comment by CaselIT** [comment]
I have the same problem and the only driver it offers me is 42.2.0

![image](https://user-images.githubusercontent.com/16175304/135587642-c0eb6a3a-92c0-4a25-a60a-6b5af4a1e7ff.png)

I'm on the latest version
![image](https://user-images.githubusercontent.com/16175304/135587695-0062948a-93c7-4ea4-b811-b540ac1c1dc2.png)

**Comment by CaselIT** [comment]
Nevermind, the version column is actually the world most user unfriendly drop down..... it gives no clue it's a drop down

It would be nice it was ordered from the newest to oldest, so the newest one is always selected
