### ISSUE TITLE
Highlight rows with selected cells  Bug.

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#12286]
#### System information: 
- Windows 10
- DBeaver 21.0.3
- 
#### Connection specification:
- Oracle 18C

After sorting in the Result Set, the "Highlight rows with selected cells" option works incorrectly.
Rows not selected become highlights.

It seems that the row before sorting becomes the highlight.
![sort_selectrow](https://user-images.githubusercontent.com/59002295/116520105-3db6ef00-a90d-11eb-94c9-0ca6f3eedd96.gif)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
