### ISSUE TITLE
[Feature Request] Option to display trailing whitespaces in row/column data

### ISSUE THREAD

**Issue by Lautenschlager-id** [dbeaver/dbeaver#12283]
I would like to be able to see trailing whitespaces in data fields in my SQL tables.

For example, assume the value `test ` in the following query:
``insert into `player` ( `name` ) values ( "test " )``

This way I currently can't see the whitespace in "test", leading me to face some bugs in my application. It would be easier for me if DBeaver displayed the whitespace somehow.

It could be enabled in the settings menu, preferably.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. We already have such option. You can enable it in Preferences>Editors>Text Editors
![dbeaver_mlKav90dEB](https://user-images.githubusercontent.com/51405061/118404532-00c45980-b67c-11eb-9336-43513313f9bb.png)
