### ISSUE TITLE
Not possible to expand Databases under host

### ISSUE THREAD

**Issue by g3blv** [dbeaver/dbeaver#12288]
#### System information: 
- Fedora 33
- 21.0.3 Flatpak
- MariaDB Client

#### Connection specification:
- MariaDB [10.3.23-MariaDB-log]
- MariaDB Connector/J [2.4.3]
- AWS RDS SSH

#### Describe the problem you're observing:

I have to click the expand arrow on each level a few times for the next level to expand. Sometimes I'm not able to get it to expand at all.

![image](https://user-images.githubusercontent.com/45568043/116525047-6a044880-a8d8-11eb-9831-0de8a7a7b3ac.png)

**Comment by uslss** [comment]
cannot reproduce it against 21.1.2. If it is still actual for you - feel free to reopen it
