### ISSUE TITLE
Auto suggest function not working

### ISSUE THREAD

**Issue by g3blv** [dbeaver/dbeaver#12289]
#### System information: 
- Fedora 33
- 21.0.3 Flatpak
- MariaDB Client

#### Connection specification:
- MariaDB [10.3.23-MariaDB-log]
- MariaDB Connector/J [2.4.3]
- AWS RDS SSH

#### Describe the problem you're observing:

There are no suggestions for table names when typing SQL statements.

When selecting `FROM` after typing `F` it comes out as `FFROM`

Pressing TAB after entering the first couple of letters for field name makes the cursor move rather than returning the right field name.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Can reproduce (DBeaver 21.0.5.20210508204)

https://user-images.githubusercontent.com/51405061/117561579-b43bb580-b0a0-11eb-81ba-7243467308bf.mp4

**Comment by serge-rider** [comment]
Fixed again

**Comment by kseniiaguzeeva** [comment]
verified
