### ISSUE TITLE
Column descriptions aren't shown in resultset

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#12298]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.0.4

#### Connection specification:
- Database name and version redshift

#### Describe the problem you're observing:
Column descriptions aren't shown in resultset, but they are shown in data editor.
![image](https://user-images.githubusercontent.com/31996417/116575086-00575f00-a917-11eb-92bb-72f014e8bd66.png)

**Comment by serge-rider** [comment]
This must be fixed along with column resolution in Redshift.

**Comment by uslss** [comment]
verified
