### ISSUE TITLE
Reopening of #6103: dbeaver restore of pg_dump with custom format fails with "could not find block-id"

### ISSUE THREAD

**Issue by apolyton** [dbeaver/dbeaver#12293]
#### System information: 
- Windows 10 2004
- DBeaver version 21.0.3.202104181339

#### Connection specification:
- Postgresql 12.6
- postgres JDBC 42.2.20
- tried native Postgresql from DBeaver as well Postgresql 12 Binaries from Postgres 
- no tunnel

#### Describe the problem you're observing:
Any backup made with pg_dump in custom format (--format=c) which was not made with dbeaver and has tables with filled rows can't be restored inside dbeaver.

```
C:\Users\apo\.dbeaver-drivers\clients\postgresql\win\12\pg_restore.exe --verbose --host=localhost --port=5433 ****** --clean --format=c --dbname=foo
Task 'PostgreSQL restore' started at Thu Apr 29 15:09:20 CEST 2021
pg_restore: connecting to database for restore

pg_restore: dropping TABLE DATA foo

pg_restore: dropping TABLE foo

pg_restore: creating TABLE "public.foo"

pg_restore: processing data for table "public.foo"

pg_restore: error: could not find block ID 2897 in archive -- possibly corrupt archive

Task 'PostgreSQL restore' finished at Thu Apr 29 15:09:20 CEST 2021
```

While table definition is restored no rows are inserted. pg_restore outside dbeaver works fine with same backup.

**Comment by sknextcode** [comment]
This is also described in https://github.com/dbeaver/dbeaver/issues/7813 and also affecting backup files made with dbeaver.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. I can reproduce it with an example from #7813. I'll close this ticket as a duplicate and add #7813 to 21.1.3 milestone where we are going to fix data transfer issues.
