### ISSUE TITLE
Database Navigator filter does not filter databases

### ISSUE THREAD

**Issue by taz-7er** [dbeaver/dbeaver#12294]
#### System information: 
- Operating system (distribution) and version - windows 10
- DBeaver version 21.0.3.202104181339
- Additional extensions

#### Connection specification:
- Database name and version - sql server 

#### Describe the problem you're observing: 
When using the filter in the Database Navigator the option to "filter databases or schemas" only filters schemas.  The list of Databases are not filter at all.  

#### Steps to reproduce, if exist:  In the filter options select "filter databases or schemas".  Enter a search term and the database list does not change
 
![dbeaver](https://user-images.githubusercontent.com/83409999/116559770-c19db680-a8ce-11eb-811e-29faa388abe6.png)

**Comment by ShadelessFox** [comment]
Thanks for the report!

**Comment by ShadelessFox** [comment]
Actually, this is a correct behavior. The "databases or schemas" filter means "containers with tables inside". Some databases may not have schemas, so tables are located inside database(-s).

Added clarification (names and hints were updated to better reflect their purpose) to filter modes.

![image](https://user-images.githubusercontent.com/35821147/116946280-62e78c80-ac82-11eb-8a31-7ad9fd79a970.png)

**Comment by kseniiaguzeeva** [comment]
verified
