### ISSUE TITLE
Oracle - Navigate further to other objects when viewing the declaration of a function,  a package body, ...

### ISSUE THREAD

**Issue by F0xD8rk** [dbeaver/dbeaver#12290]
#### Connection specification:
- Database name and version: Oracle 12

#### Describe the problem you're observing:
It would be nice if you could navigate further to other objects if you are viewing f.e. the declaration of a function, the package body, ...
Now you can only directly navigate (F4 or rightclick and _Open Declaration_) to the respective objects if you copy f.e. the name of an object and paste it in a SQL script window. This would save a lot of time if you need to edit f.e. a package function that is being called from a function.

![afbeelding](https://user-images.githubusercontent.com/79097587/116534968-7c37b400-a8e3-11eb-8111-b17d2a385f88.png)

**Comment by kseniiaguzeeva** [comment]
Seems we've lost this option. Thank you for the report.

**Comment by LonwoLonwo** [comment]
Can't reproduce in DBeaver 21.2.5

Ctrl+click works for tables, procedures, and packages names in the first place.

![OsMI0Xnm9n](https://user-images.githubusercontent.com/45152336/141011960-5d9ff11a-94cd-44ce-97df-41a54190718c.gif)

**Comment by Matvey16** [comment]
Verified
