### ISSUE TITLE
Import/Export/Table copy SQL generation issue with multiple columns ON DUPLICATE

### ISSUE THREAD

**Issue by Hemmels** [dbeaver/dbeaver#12300]
#### System information: 
- Operating system (distribution) and version
Windows 10 64-bit
- DBeaver version 21.0.3

#### Describe the problem you're observing:
Copying any table or using the "export to CSV" function with "ON CONFLICT DO UPDATE SET" setting generates poor SQL..
i.e. ON CONFLICT (col1col2,) instead of ON CONFLICT (col1, col2)

#### Steps to reproduce, if exist:
See above. Both methods fail for the same reason.

**Comment by LonwoLonwo** [comment]
Yep, you are totally right. Thanks for the bug report. 

(But this is only import issue, because "ON CONFLICT DO UPDATE SET" is import setting in PG)

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.0.5
Can be tested on tables with PK on 2 or more columns.

**Comment by uslss** [comment]
verified
