### ISSUE TITLE
New objects created in mixed case by default

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#12301]
For some databases we create new objects in mixed case (e.g. `NewTable`). But actually object names are stored in lower/upper case and thus we can't find the new object in database metadata after save. This leads to weird behavior like columns disappear.

The bug seems to be in SQLDialect.supportsUnquotedMixedCase value detection.

**Comment by mkgrgis** [comment]
Most of relational databases can store mixed case if there is SQL quoting. In DBeaver also there is quoting mode: option "case sensitive DDL".

**Comment by uslss** [comment]
Still reproducible for columns in newly created tables. Works ok for already existing tables.
![2021-05-11_10h52_59](https://user-images.githubusercontent.com/31996417/117779225-264dff00-b247-11eb-9519-f332c69479ab.gif)

**Comment by uslss** [comment]
also table and column name are quoted always e.g. in PostgreSQL, Oracle, even if Use case-sensetive names option is disabled
![image](https://user-images.githubusercontent.com/31996417/117803120-ef83e300-b25e-11eb-9cbc-6c55cc31d63c.png)

![image](https://user-images.githubusercontent.com/31996417/117803066-e135c700-b25e-11eb-9f6e-83d1b6f30e7b.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
