### ISSUE TITLE
[MSSQL] Show more trigger fields

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12314]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver 21.0.4

#### Connection specification:
- Database name and version SQL Server

#### Describe the problem you're observing:
We should show more trigger fields in Metadata Editor.

**Comment by LonwoLonwo** [comment]
Implemented in DBeaver 21.1.1

![2021-06-16 13_14_48-Window](https://user-images.githubusercontent.com/45152336/122246782-86336780-cecf-11eb-9507-e82f08be56f9.png)

**Comment by uslss** [comment]
verified
