### ISSUE TITLE
Grouping panel support for Hive

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12317]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.4

#### Connection specification:
- Database name and version Hive

#### Description:
1. JDBC program has to be added to execute group by clause https://www.tutorialspoint.com/hive/hiveql_group_by.htm.
2. Also SQL expression has to be modified for Hive Grouping panel:
**Expected**: `SELECT Dept,count(*) FROM employee GROUP BY DEPT;`
**Now**: `SELECT * FROM employee GROUP BY DEPT;`

**Comment by LonwoLonwo** [comment]
Can't reproduce against DBeaver 23.0.5

![2023-05-26 13_30_54-DBeaver Ultimate 23 1 0 - artist](https://github.com/dbeaver/dbeaver/assets/45152336/cda90a82-676a-4c99-af67-19e101478d4b)
