### ISSUE TITLE
Expanding the column width hides the next cell content 

### ISSUE THREAD

**Issue by rajmondburgaj** [dbeaver/dbeaver#12319]
When I run a select query and I have some JSON values in the given cells, I want to see all the content therefore I click the column border line in order to auto-expand it, but this leads to hiding the next cell content. For more it can be seen in the image below.

I am using the latest version: Version 21.0.3.202104181339, Windows 10

![Animation](https://user-images.githubusercontent.com/7545874/116710375-f9d9ed80-a9d1-11eb-86bd-6ee51b5977b3.gif)

**Comment by LonwoLonwo** [comment]
As workaround you can use "columns width: fit values"
![2021-04-30 18_04_26-Window](https://user-images.githubusercontent.com/45152336/116718388-93a99680-a9e2-11eb-8b2b-6b6a260a7f7d.png)

**Comment by rajmondburgaj** [comment]
This solution does not work either, I click at the header of the column, then i click the option as described in the picture and the stills the cells as not wide enough to show the whole content of it.

**Comment by ShadelessFox** [comment]
The problem is that scrollbars are not updated accordingly. It can be seen upon resizing SQL editor panel.

**Comment by uslss** [comment]
verified
