### ISSUE TITLE
Column value auto-suggestion doesn't work

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12313]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.4

#### Connection specification:
- Database name and version Hive

#### Steps to reproduce, if exist:
Write a select query like SELECT * FROM table_name where column_name = and press Ctrl+Space

**Expected**: a list of column values appears
**Actual result**: no results pop up appears
#### Include any warning/errors/backtraces from the logs

![t0QpbNYidR](https://user-images.githubusercontent.com/51405061/116687869-85e21a00-a9be-11eb-87b4-e15c38fe6b7f.gif)
[.log](https://github.com/dbeaver/dbeaver/files/6404886/default.log)

**Comment by serge-rider** [comment]
May be a Hive limitation

**Comment by serge-rider** [comment]
It works but slowly (check progress monitor in the bottom-right corner)
