### ISSUE TITLE
Sorting doesn't work for fetched rows, in custom filter, after saving filter settings

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12318]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.4

#### Connection specification:
- Database name and version Hive

#### Steps to reproduce, if exist:
**Case 1**
Open a table where rows have to be fetched and sort a column via column header

**Case 2**
Open Custom filter and try to order data in Columns or Custom tab

**Case 3**
1. Apply column ordering in Data Editor and press Save filter settings
2. Reopen the table

**Expected**: the data is sorted
**Actual result**: an error appears instead of table view
![NaV4NLcDaS](https://user-images.githubusercontent.com/51405061/116706336-3576b680-a9d6-11eb-9fc3-c5db2c020696.gif)
[.log](https://github.com/dbeaver/dbeaver/files/6405868/default.log)

**Comment by ShadelessFox** [comment]
Works fine against Hive 2.3.2

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce anymore too.
