### ISSUE TITLE
Object Editor refresh leads to an error

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12310]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.4 EA
- Additional extensions
#### Connection specification:
- Database name and version Hive

#### Steps to reproduce, if exist:
Open a table properties and press Refresh

**Expected**: the table properties are refreshed
**Actual result**: an error appears: "Connection is closed"
**Note**: the same error appears when References tab is opened
#### Include any warning/errors/backtraces from the logs

![xWGQhn4Uvp](https://user-images.githubusercontent.com/51405061/116684433-a065c480-a9b9-11eb-8813-0932d666d60a.gif)

[.log](https://github.com/dbeaver/dbeaver/files/6404728/default.log)

**Comment by serge-rider** [comment]
Added Hive connection recovery

**Comment by Matvey16** [comment]
Verified
