### ISSUE TITLE
DBeaver connection hangs when connecting to dolt

### ISSUE THREAD

**Issue by KOLANICH** [dbeaver/dbeaver#12324]
#### System information: 
- Operating system (distribution) and version: Ubuntu Hirsute
- DBeaver version 21.0.3

#### Connection specification:
- Database name and version: [dolt](https://github.com/dolthub/dolt)
- Driver name mariadb-java-client, mysql-connector-java
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

`Test connection` works, working - doesn't. When connection is open through the panel, it hangs untill I kill the server.

#### Steps to reproduce, if exist:
1. create a dir
2. init a dolt repo
3. start a dolt server
4. add connection  to DBeaver
5. open the connection.

#### Include any warning/errors/backtraces from the logs
All the errors appear after killing the server.

**Comment by kseniiaguzeeva** [comment]
Please send log files https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by KOLANICH** [comment]
Really nothing especially valuable there, just a privacy risk of leaking some sensitive info like local paths to products and `~`. It seems to debug it properly you would still have to use `dolt` locally. But if you really need **my** log, I can provide it (with some edits, of course).

**Comment by kseniiaguzeeva** [comment]
Sorry for the long response. I'm trying to reproduce the issue. Could you please send me the connection settings (e.g. screenshot)?

**Comment by KOLANICH** [comment]
I have figured that out. It was my fault, dolt by default allows 1 connection, and additional connections are just hanged. It is documented in the FAQ. It seems DBeaver uses more than 1 connection. When I have set them to 4 it was enough.
