### ISSUE TITLE
A warning message with NPE appears when a new table is created

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12326]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.4 EA

#### Connection specification:
- Database name and version Oracle

#### Steps to reproduce, if exist:

1. Open Error log
2. Create a new table via UI 

**Expected**: the table is created without any message in Error log
**Actual result**: the table is created and a warning message appears after creating the first column
#### Include any warning/errors/backtraces from the logs

[.log](https://github.com/dbeaver/dbeaver/files/6409503/default.log)
![Y32Y4XJRNM](https://user-images.githubusercontent.com/51405061/116781646-f0618b80-aa8c-11eb-9d81-db25290c8f4d.gif)

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.0.5

**Comment by kseniiaguzeeva** [comment]
verified
