### ISSUE TITLE
Resultset doesn't appear in case of whole script execution

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12327]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.4 EA

#### Steps to reproduce, if exist:
1. Write at least 2 queries in SQL Editor
2. Press Execute SQL Script or Execute SQL Script in separate tabs

**Expected**: the queries are executed and ResultSet appears with results
**Actual result**: the queries are executed, results do not appear in ResultSet, an error appears in Error log
![1](https://user-images.githubusercontent.com/51405061/116782261-b3979380-aa90-11eb-85fd-0ce3b651fa8d.gif)

**Workaround**: highlight the script and press Execute SQL statement or Execute SQL in new tabs
![U6KWyzNi67](https://user-images.githubusercontent.com/51405061/116782253-a7abd180-aa90-11eb-928b-875511a58369.gif)

#### Include any warning/errors/backtraces from the logs

[.log](https://github.com/dbeaver/dbeaver/files/6409534/default.log)

**Comment by flambchap** [comment]
This is a side-effect of [this](https://github.com/dbeaver/dbeaver/issues/12237) bugfix.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
