### ISSUE TITLE
Column auto fill not working when not using JOIN syntax

### ISSUE THREAD

**Issue by eperrone-kercher** [dbeaver/dbeaver#12332]
#### System information: 
- Win10 Version	10.0.19042 Build 19042
- DBeaver version 21.0.4.202105021514
- Additional extensions Darkest Theme SQL Debugger

#### Connection specification:
- PostgreSQL 9.6.20 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit
- JDBC
- no

#### Describe the problem you're observing:
when writing a query like this:

select w.pms_section_id, m.section_name from pms_eco_scal_wp w, pms_spr_pm_sect_inv m
where w.pms_section_id =m.pms_section_id

column autocomplete works for the **W** table but not for the **M** table.

Column autocomplete does work if you change syntax to use JOIN syntax.

This behavior is new in the last 2 updates best I can tell.

#### Steps to reproduce, if exist:
just type

select *  from table1 w, table2 m
where w.some_column =m.   once you type "." no column list for table m appears

**Comment by eperrone-kercher** [comment]
Might be related to issue #12313 I am not sure.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by ademaio-crown** [comment]
I am experiencing the same thing. Oddly, mine is intermittent. Sometimes the auto complete doesn't even work on a single table select, sometimes it is just slow, sometimes it works on much more complex queries. 

I also agree this started with the last two updates.

**Comment by LonwoLonwo** [comment]
This case also here: https://github.com/dbeaver/dbeaver/issues/12168
May be, duplicate.

**Comment by kseniiaguzeeva** [comment]
verified
