### ISSUE TITLE
Table column changes are immediately semi-discarded after Refresh

### ISSUE THREAD

**Issue by elring** [dbeaver/dbeaver#12331]
**System information:**

    OS: Linux Mint 20
    DBeaver version: 21.0.4

**Connection specification:**

    Database: Postgresql 12

**Describe the problem you're observing:**

After editing table columns (rename or create) the Refresh function semi-discards those changes - regardless the confirmation. The changes are still valid (can be saved) but the column list is restored to original state.

**Steps to reproduce**

Use any existing table, create some column, press F5. The column list is reset behind the the "Revert changes" confirmation window. After denying the "Revert changes", the column list is still reset, but pressing Ctrl+S still creates SQL for now missing column.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
