### ISSUE TITLE
Table Data tab filter expression filter results datetime column ordering improper

### ISSUE THREAD

**Issue by givihuda** [dbeaver/dbeaver#12337]
#### System information: 
- Operating system (distribution) and version: macOS Catalina 10.15.7
- DBeaver version: Version 21.0.3.202104181339
- Additional extensions

#### Connection specification:
- Database name and version: MySQL 5.7
- Driver name: Whatever DBeaver prompted me to install during connect, the typical/normal/default I guess.
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No, it's a local database.

#### Describe the problem you're observing:

In the schema table's Data tab, a datetime column's results do not order properly after clicking the Sort by buttons (up or down). 

![image](https://user-images.githubusercontent.com/74785256/116907436-ca5bf880-abfe-11eb-9213-b7af86e0dae5.png)

![image](https://user-images.githubusercontent.com/74785256/116907450-cf20ac80-abfe-11eb-90a4-bb87d0a992e4.png)

![image](https://user-images.githubusercontent.com/74785256/116907827-5a01a700-abff-11eb-9e84-fe853a7be4b4.png)

#### Steps to reproduce, if exist:

Open the Data tab on a table, type `datetime_column_name <= 'YYYY-MM-DD'` in the expression filter, then order the results of the column (which would be a datetime column), then click the column's sort button for up or down (ascending or descending).

#### Include any warning/errors/backtraces from the logs

There are no relevant warning/errors/backtraces from the logs that I'm aware of.

Additional info:

If I instead open a new SQL tab (from the schema name right-click) then type out my own SQL, the datetimes order properly:

```
SELECT received_date FROM file 
WHERE received_date <= '2020-05-03'
ORDER BY received_date DESC 
```

![image](https://user-images.githubusercontent.com/74785256/116907692-26bf1800-abff-11eb-9b30-8e1f73061861.png)

**Comment by ShadelessFox** [comment]
Hello @givihuda,

Cannot reproduce your issue:
![image](https://user-images.githubusercontent.com/35821147/117761819-b3398e00-b230-11eb-9465-b58eb8c016a6.png)

What ordering mode are you using? <kbd>Preferences</kbd> &rArr; <kbd>Editors</kbd> &rArr; <kbd>Data Editor</kbd> &rArr; <kbd>Results ordering mode</kbd>

**Comment by givihuda** [comment]
Results ordering mode was set to Smart (Adaptive).

What was yours set to?

**Comment by ShadelessFox** [comment]
Mine was set to Adaptive too.
I noticed that I mixed up the labels, but after further investigation I'm still not able to reproduce your issue using MySQL and MariaDB drivers.

**Comment by givihuda** [comment]
I stumbled on what the issue is...

I had another column ordered by its tab click, like this:

![image](https://user-images.githubusercontent.com/74785256/122091392-f9e94d80-cdc5-11eb-9de7-3d2bdc4ee04d.png)

I wasn't aware (accidental click) or had forgotten, so it screwed with what I expected from the `received_date` column filter order.

Sorry about that! I was not aware that the Data tab allowed multi-column click sorting... but that's a very nice feature that I can use effectively now.

**Comment by ShadelessFox** [comment]
That's okay. I'm glad your issue was solved!
