### ISSUE TITLE
SQL Editor: show output log configation improvement

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#12333]
In some databases output log is used to print all error messages (e.g. MySQL). This may be annoying. 
We need to add a way to disable auto-show option more easyly, e.g. directly in the output log toolbar.

**Comment by serge-rider** [comment]
Preferences explicit save was added

**Comment by kseniiaguzeeva** [comment]
verified, another ticket is created https://github.com/dbeaver/dbeaver/issues/12434
