### ISSUE TITLE
Generic Generate SQL Feature/Idea (SQL templates for Generate SQL and Export to SQL)

### ISSUE THREAD

**Issue by CMCDragonkai** [dbeaver/dbeaver#1233]
The generate sql feature is similar the export as sql feature in Heidisql. One thing I've used in the past is export as sql and choose `REPLACE INTO` as the command.

Is it possible to export all of the result set of a sql query as `REPLACE INTO` queries? It seems like the generate sql feature only works on visible result sets, and I need all of it.

Now adding every sql extension is probably not scalable. So perhaps there can be a way of designing a expression template so that the values will slot into the template. And then the generate as sql feature can be added to the export feature allowing the export of the entire query, and not just selected parts. These 2 features seem like they overlap. One should be able to select which rows/columns to take out or select all of them.

**Comment by MatyCZ** [comment]
+1

**Comment by serge-rider** [comment]
Do you mean "Generate SQL" command or Export Table Data (in SQL format)?

BTW there is already UPSERT statement support (instead of INSERT) for some databases.

**Comment by CMCDragonkai** [comment]
I was looking at what was available in the mysql driver. Is generate sql
just a shorter more selective version of the export results feature?

**Comment by serge-rider** [comment]
For now generate SQL and data export uses different functions for code generation. Data export is designed for bulk export of huge resultsets while "Generate SQL" is for manipulation of small number of table rows.
But it is possible to use some common features.

Back to topic: please provide some examples of REPLACE queries. And some examples of code templates (as you see it).

**Comment by CMCDragonkai** [comment]
Well imagine if we had sql templates for the current generate sql feature:

```
DELETE FROM ${database}.${table}
WHERE ${col}=${val};
```

```
INSERT INTO ${database}.${table} ${cols}
VALUES ${vals};
```

Then we could create our own queries beyond the current 3 supported in generate sql, and the 1 supported in export results. We could create a `REPLACE` version as well. Note that the export results currently only has `INSERT` as the command prefix.

**Comment by zejji** [comment]
Another +1 from me.

@serge-rider:

As an example of a use case for 'REPLACE INTO' queries - I often use the 'Export resultset' option in the right-click context menu to take backups of certain rows of data before running queries which modify them. If I need to revert the rows to their original state at a later date, all I would need to do is run the 'REPLACE INTO' query. (Obviously you could also use 'INSERT INTO ON DUPLICATE KEY UPDATE'.)

HeidiSQL supports this output option by default. With DBeaver I generally achieve the same aim by modifying the outputted SQL by hand.

**Comment by foal** [comment]
+1 from me. Please. INSERT INTO  VALUES  ON CONFLICT DO UPDATE SET for PostgreSQL :)

**Comment by LonwoLonwo** [comment]
So, at this moment (DBeaver 7.2.3) we have some new options in Exporter settings

![2020-10-28 13_08_41-Generic Generate SQL Feature_Idea (SQL templates for Generate SQL and Export to ](https://user-images.githubusercontent.com/45152336/97422442-dd73d000-191e-11eb-95d0-5e0d31ca892f.png)

 You can choose a different insert keyword and expand the insert into to "ON DUPLICATE KEY UPDATE"/"ON CONFLICT" option. The 'On conflict expression' field, however, is limited to the number of entered characters. Perhaps we will expand it, a similar request will arise.

A can add REPLACE INTO into list of INSERT expressions.

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
REPLACE INTO into list of INSERT expressions added
