### ISSUE TITLE
Connect to System.Data.SQLite with RC4 Cipher

### ISSUE THREAD

**Issue by shawnsheridan** [dbeaver/dbeaver#12342]
Deleted

**Comment by shawnsheridan** [comment]
Solved using sqlite-jdbc-3.35.5.1.jar Driver.

**Comment by flambchap** [comment]
Hi @shawnsheridan. Can you please share your solution with me?

**Comment by shawnsheridan** [comment]
> Hi @shawnsheridan. Can you please share your solution with me?

Hi.  As I wrote above, it worked when I swiched to sqlite-jdbc-3.35.5.1.jar Driver.

**Comment by flambchap** [comment]
@shawnsheridan What DBeaver version and SQLite driver did you use? I've tried the standard SQLite driver and SQLite Crypt with Custom cipher from DBeaver PRO. On all occasions, I used the following properties:

Property|Value
-----|-----
cipher|rc4
legacy|1
legacy_page_size|0

(I found these values [here](https://utelle.github.io/SQLite3MultipleCiphers/docs/ciphers/cipher_sds_rc4/) and [here](https://github.com/Willena/sqlite-jdbc-crypt/blob/master/src/main/java/org/sqlite/mc/SQLiteMCRC4Config.java))

Nothing helped :(

**Comment by flambchap** [comment]
I think we need dedicated support for `System.Data.SQLite: RC4` cipher in SQLite Crypt.

**Comment by shawnsheridan** [comment]
> @shawnsheridan What DBeaver version and SQLite driver did you use? I've tried the standard SQLite driver and SQLite Crypt with Custom cipher from DBeaver PRO. On all occasions, I used the following properties:
> 
> Property	Value
> cipher	rc4
> legacy	1
> legacy_page_size	0
> (I found these values [here](https://utelle.github.io/SQLite3MultipleCiphers/docs/ciphers/cipher_sds_rc4/) and [here](https://github.com/Willena/sqlite-jdbc-crypt/blob/master/src/main/java/org/sqlite/mc/SQLiteMCRC4Config.java))
> 
> Nothing helped :(

I am using latets DBeaver 22.1.1 and the following:

Driver Library = sqlite-jdbc-3.35.5.1.jar
Driver Class org.sqlite.JDBC
Driver Properties:
	cipher = RC4
	Key = The DB Password

**Comment by flambchap** [comment]
That didn't help either :( Thanks for the reply anyway

**Comment by shawnsheridan** [comment]
> That didn't help either :( Thanks for the reply anyway

Sorry, I wish I had an answer for you but I do not.  I did email Guillaume Villena and he emailed me back with some help.

**Comment by LonwoLonwo** [comment]
PR https://github.com/dbeaver/dbeaver-ee/pull/1816

**Comment by LonwoLonwo** [comment]
Related ticket: https://github.com/dbeaver/dbeaver/issues/16482

**Comment by oghenez** [comment]
@shawnsheridan 
> Solved using sqlite-jdbc-3.35.5.1.jar Driver.

Pls can you share tutorial on how you added this driver and configured it?

**Comment by puppet-ops** [comment]
jdbc:sqlite:C:\Users\admin\Desktop\file.db?key=yourkeyword
Driver Properties:
cipher=RC4
