### ISSUE TITLE
minimize function parameters window

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#12343]
DBeaver version 21.0.3
Postgresql 12

very big place for main procedure information. It reduces code editor area - it is uncomfortable.

it would be nice to minimize this information to Main information tab.
![изображение](https://user-images.githubusercontent.com/61137576/116974998-5c83ff80-acd8-11eb-833c-24164f49866c.png)

**Comment by detkliff** [comment]
very big place by vertical form technic information and very litle editor area

![изображение](https://user-images.githubusercontent.com/61137576/116975432-14b1a800-acd9-11eb-920c-a9946df52b80.png)

**Comment by uslss** [comment]
@detkliff you could use highlighted buttons to minimize it(picture attached). Does it fit your needs?
![image](https://user-images.githubusercontent.com/31996417/117192127-0a330380-adea-11eb-9d85-de8b54c024f4.png)

**Comment by detkliff** [comment]
thank you! It is true!
