### ISSUE TITLE
"Compare database objects": tries to "Open in Browser" despite "Save to File" being selected

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#12346]
See #12345 for details
#### System information: 
- Operating system (distribution) and version: Debian/SID
- DBeaver version: 21.0.4.202105021514
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Comparing two databases (Compare/Migrate -> Simple Structure Compare)
Output Type: Save to File
Directory: /foo/bar
![Screenshot_20210504_121440](https://user-images.githubusercontent.com/50481865/116990603-a28a9480-acd3-11eb-8479-16813357450e.png)

I expect the comparison to simply credate one or more files in the given directory and that's it -- after all, selected entry is just that: "Save to File"
Instead DBeaver tries to open the created HTML file.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
@smk-dev20 thanks for the PR 👍 
But after all I've fixed it a bit differently.

**Comment by uslss** [comment]
verified
