### ISSUE TITLE
Commit on select statements?

### ISSUE THREAD

**Issue by bjorntj** [dbeaver/dbeaver#12344]
Hi.

Coming from Datagrip but using DBeaver now for DB2 (since DBeaver supports DB2 better than Datagrip), I have one question.
I always set up connections against prod servers using manual transactions instead of autocommit. But I see that, for some reasons, I have "hanging" transactions when just using selects. Why do I need to commit or rollback select statements? (this is just handled when using Datagrip).
Am I missing some settings I can change or is this by design? If this is by design, why has it been designed this way? Seems very strange to me....

**Comment by p91paul** [comment]
I don't know about db2, but in many DBMS select could, in theory, call stored functions that could, in turn, edit data.
Datagrip might be trying to be smart and guessing your select is just a select. Dbeaver doesn't.

Actually, most likely Datagrip does open a transaction (to run any SQL you must do that) and immediately closes it if you run a SELECT only.

**Comment by bjorntj** [comment]
Yes, I guess that might be what Datagrip does.. What I do not understand, is why doesn't DBeaver do the same..? Having to commit/rollback selects is just weird....

**Comment by p91paul** [comment]
I'm guessing because Dbeaver doesn't actually parse your statement so it's not aware about what's in it

**Comment by bjorntj** [comment]
Just had a quick look at Datagrip again and I see that they also creates a transaction that I can commit or rollback. But somehow I am more aware about this in DBeaver than Datagrip, apparently, not sure why......

**Comment by kseniiaguzeeva** [comment]
Please try Smart-Commit https://github.com/dbeaver/dbeaver/wiki/Auto-and-Manual-Commit-Modes#smart-commit-mode. I hope it will cover your needs

**Comment by bjorntj** [comment]
I tried that but don't think I noticed any difference but will try it again...

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info
