### ISSUE TITLE
Tool tip for "execute sql statement" does not show correct key  binding

### ISSUE THREAD

**Issue by chuckh1958** [dbeaver/dbeaver#12352]
#### System information: 
- Operating system (distribution) and version - Windows 10
- DBeaver version - 21.0.4.202105021514
- Additional extensions - Snowflake

#### Connection specification:
- Database name and version - Snowflake
- Driver name - snowflake
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
The tool-tip that pops up when you hover the mouse over the "execute sql statement" icon shows the default binding of ctrl+enter but I have changed the binding in preferences to F5. It should show "F5".

#### Steps to reproduce, if exist:
In preferences, change the key bindind for "execute sql statement" to F5. 
Go into SQL editor
Hover mouse over the execute sql statement icon.

#### Include any warning/errors/backtraces from the logs
n/a

![preferences](https://user-images.githubusercontent.com/83663568/117041439-eb911780-acd8-11eb-89ef-e8c7f84bf8e3.png)
![tooltip](https://user-images.githubusercontent.com/83663568/117041479-f186f880-acd8-11eb-98e0-11a2d00cd3df.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by Matvey16** [comment]
Verified
