### ISSUE TITLE
ctrl + enter doesn't work if gaps between CTEs

### ISSUE THREAD

**Issue by rjake** [dbeaver/dbeaver#12350]
**Is your feature request related to a problem? Please describe.**
It seems I can either get code folding by putting spaces between each CTE or I can get the `ctrl + enter` functionality by not putting spaces between each CTE but cannot have both. Is it possible to get `ctrl + enter` to look further up when running.

### Scenario 1: Space between each CTE:
✔️ code folding  ❌ ctrl + enter
![image](https://user-images.githubusercontent.com/14003618/117015805-115df280-acc0-11eb-9792-3d3a511f5153.png)

### Scenario 2: No Space between each CTE
❌ code folding  ✔️ ctrl + enter
![image](https://user-images.githubusercontent.com/14003618/117016095-5eda5f80-acc0-11eb-9ab6-f21e314ca796.png)
 If my mouse is in the middle of the `cte_2` section, it seems it only tries to run these contiguous lines rather than running the code above and below.
 ```sql
, cte_2 as (
    select *
    from department
)
```

**Describe the solution you'd like**
I'd like `ctrl + enter` to look for statement delimiters and run all code in-between otherwise run the entire script
and
I'd like code folding to work at each set of parentheses, otherwise, it doesn't provide much use.

**Describe alternatives you've considered**
Highlighting all of the code each time (frustrating) or using a different IDE.

**Comment by LonwoLonwo** [comment]
Hello @rjake 

Can you disable "Blank line is statement delimiter" setting and then test again, please?

![2021-05-04 23_05_08-DBeaver Enterprise 21 0 4 - array_type](https://user-images.githubusercontent.com/45152336/117063350-5d934c00-ad2d-11eb-9162-41487d071be9.png)

Test CTEs DDL will be very helpful also.

**Comment by rjake** [comment]
Oh, I had looked all over! That did the trick. I'm curious why it didn't show up in the search:

![image](https://user-images.githubusercontent.com/14003618/117497847-ffda4c00-af46-11eb-9889-5d272560463e.png)

**Comment by LonwoLonwo** [comment]
Ok. I added more keywords to search in Preferences, including "delimiter" in DBeaver 21.0.5 (will be available on 2021-05-17) 
![2021-05-09 01_37_16-Preferences](https://user-images.githubusercontent.com/45152336/117642869-7b7b0980-b190-11eb-9c50-7e2fdb2fe982.png)

**Comment by rjake** [comment]
I see it now. Should I close the issue or will you?

**Comment by LonwoLonwo** [comment]
@rjake 
Thanks for feedback. I close.
