### ISSUE TITLE
Option to make boolean value change with double click instead of single click.

### ISSUE THREAD

**Issue by Mizar01** [dbeaver/dbeaver#12361]
The default behaviour is error-prone, when clicking on a boolean cell for the sake of hilighting it, dbeaver will toggle the boolean value, but you can miss the change and clicking save (because you were editing something else) lead to unwanted changes.

**Comment by serge-rider** [comment]
Good point

**Comment by serge-rider** [comment]
I also think we should mark modified object properties in editor (like in the data editor).

**Comment by serge-rider** [comment]
We changed the behavior in the metadata/object editor but kept old behavior for data editor.

@Mizar01 was you ticket about data?

**Comment by Mizar01** [comment]
@serge-rider Actually yes: I mean the grid with editable results of a query. Often we show data from data editor, we click or drag mouse to hilight values. It's inconvenient to have a value changed with a single click, and the change is barely noticeable. I find myself always re-read modified rows before submitting any change with 'save button' to check if a boolean was changed in an undesired position.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/117996555-ea9c5d80-b34a-11eb-9d1c-788389fc1bf5.png)

**Comment by kseniiaguzeeva** [comment]
Metadata Editor:
1 Save button is inactive until the focus remains in an edited cell
2 Cell highlighting is not removed after saving changes

https://user-images.githubusercontent.com/51405061/118100439-1ec15e00-b3df-11eb-86c9-2e395cc33377.mov

Separate ticket will be created for other improvements.

**Comment by kseniiaguzeeva** [comment]
Highlighting issue can be reproduced on Mac. Separate ticket will be created.
