### ISSUE TITLE
CTRL+Space does not replace asterisk with all columns

### ISSUE THREAD

**Issue by fujiokae** [dbeaver/dbeaver#12365]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: Community 21.0.3 & 21.0.4
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 9.1 & 9.6
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
In a SQL console or script, when I press CTRL+Space after "&#42;", it used to replace "&#42;" with all the column names of the table.
This assist no longer works when I upgraded DBeaver to 21.0.3 and 21.0.4.
As I use this assist quite often, I had to roll it back to 21.0.1 where this assist works fine.

#### Steps to reproduce, if exist:
Open a SQL console or a SQL Script tab.
Enter the following SQL:
SELECT &#42; FROM tablename
Move the cursor after the "&#42;".
Press CTRL+Space.
Instead of replacing "&#42;" with the column names, "FROM" is inserted. So, the SQL would look like:
SELECT &#42;FROM FROM tablename

This issue happens on two Windows 10 PCs (a desktop and a laptop). CTRL+Space is bound with "Content Assist" in User Interface - Keys and I have never changed it.

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
Fixed

**Comment by serge-rider** [comment]
Query parser has been fixed

**Comment by kseniiaguzeeva** [comment]
verified
