### ISSUE TITLE
(PostgreSQL 13) uint array is displayed as float array

### ISSUE THREAD

**Issue by vicreal** [dbeaver/dbeaver#12363]
The bug that appeared after fixing [these 4 artifacts with uint types](https://github.com/dbeaver/dbeaver/issues/10818)
Tested on version **21.0.4**.

`SELECT '{12812,15920}'::int4[], '{12,15}'::int1[], '{12,15}'::uint1[], '{12812,15920}'::uint2[], '{12812,15920}'::uint4[], '{12812,15920}'::uint8[];`

![Bug 5](https://user-images.githubusercontent.com/72701351/117158078-c62f0700-adc7-11eb-8ac5-614d90f1f513.jpg)

**Here are the following problems:**
**1)** As part of the array literals, all unsigned types from the **uint extension** (_int1_, _uint1_, _uint2_, _uint4_, _uint8_) are displayed as floating-point real numbers. I.e., **uint[]** is displayed as **float[]**.
**2)** As part of the array literals, numbers view as strings, not as numbers (black color instead blue and without space between triads).

**3)** As a result, it is not possible to edit the previously saved **uint[]** array, because when **saving changes**, DBeaver tries to save the **float[]**:

![Bug 5_02](https://user-images.githubusercontent.com/72701351/117163680-90405180-adcc-11eb-9716-c7e1b4177781.jpg)
![Bug 5_03](https://user-images.githubusercontent.com/72701351/117163690-920a1500-adcc-11eb-991f-c5f94aeafbf2.jpg)
![Bug 5_01](https://user-images.githubusercontent.com/72701351/117163704-93d3d880-adcc-11eb-8d9a-61dd982e7dc0.jpg)

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.1.1

**Comment by DariaMarkaryan** [comment]
Verified
