### ISSUE TITLE
Filter doesn't work on table triggers in Oracle

### ISSUE THREAD

**Issue by BytesBytes** [dbeaver/dbeaver#12362]
#### System information: 
- Operating system (distribution) and version: Windows 10 version 20H2 Build 19042.804
- DBeaver version: Version 21.0.4.202105021514
- Additional extensions

#### Connection specification:
- Database name and version: Oracle database 12c
- Driver name: : Oracle Client 12 - 12.2.0.1.0 - oracle.jdbc.OracleDriver library 21.1.0.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Filter doesn't work on table triggers in Oracle

#### Steps to reproduce, if exist:
- Enter a part of an existing table trigger in de filtebox on top of the Database navigator
- Watch result for table triggers -> all table triggers visible (also those who doesn't match the filter)

![image](https://user-images.githubusercontent.com/79206887/117142752-5bbe9c80-adb0-11eb-8eab-8afb303acdc7.png)

**Comment by serge-rider** [comment]
Good point.
That's easy to fix.

**Comment by uslss** [comment]
verified
