### ISSUE TITLE
View columns not visible with 'NO SCHEMA BINDING' views on Redshift connection

### ISSUE THREAD

**Issue by mkosater** [dbeaver/dbeaver#12372]
#### System information: 
- Windows
- DBeaver version: 21.0.3.202104181339

#### Connection specification:
- Amazon Redshift 
- com.amazon.redshift.jdbc42.Driver 

#### Describe the problem you're observing:
When dbeaver displays columns for redshift views that have been defined with 'NO SCHEMA BINDING', it does not display the columns in all cases.  

#### Steps to reproduce, if exist:
Define a redshift view using  'NO SCHEMA BINDING' columns will not show. 

create or replace view public.tst_no_binding_uc
as 
select 'testc1' c1, 999 c2
WITH NO SCHEMA BINDING
;

Define a view using  'no schema binding' and the columns will show.

create or replace view public.tst_no_binding_lc
as 
select 'testc1' c1, 999 c2
with no schema binding
;

appears that the check done for this condition is using case sensitive compare.

#### Include any warning/errors/backtraces from the logs
no error are thrown.

**Comment by LonwoLonwo** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
