### ISSUE TITLE
search_path expanding to infinity

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#12378]
#### System information: 
- Ubuntu 20
- DBeaver version: 21.0.4

#### Connection specification:
- Database name and version: postgres 12
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

When changing schema it is expected that new schema is added to search_path in a way that final search_path is a result of concatenation of default search_path set during connection initialization and current schema name.

This is how it is described by @serge-rider in this post: https://github.com/dbeaver/dbeaver/issues/11453#issuecomment-832536182

Current implementation adds every subsequently selected schema to most recent search_path, escalating number of schemas in search_path.

#### Steps to reproduce, if exist:
From animated gif below, you can see that new schema is not added to original search_path established during connection initialization but it's added to current seach_patch which results all used schemas ending up in seach_path

![dbeaver_search_path_bug](https://user-images.githubusercontent.com/7868445/117425135-cd1e5c80-af22-11eb-9450-7c7983aa7a99.gif)

**Comment by mkgrgis** [comment]
Some autocompletion bugs can be based on this behaviour.

**Comment by serge-rider** [comment]
Thanks for the bug report,
Fixed

**Comment by kseniiaguzeeva** [comment]
Now public schema cannot be selected in SQL Editor upper toolbar. Steps:
1. Open SQL Editor with non-public schema
2. Change schema on `public`
3. Execute a statement

**Actual result**: the statement is executed for non-public schema and the schema name is reverted to non-public in upper toolbar

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified. Another issue is created https://github.com/dbeaver/dbeaver/issues/12433

**Comment by michal-bartak** [comment]
Just a reminder, this part of DBeaver is borked for years.

https://youtu.be/zjqth8PY6Go

see also: https://github.com/dbeaver/dbeaver/issues/11453
