### ISSUE TITLE
Materialized view for Greenplum

### ISSUE THREAD

**Issue by tati-kru** [dbeaver/dbeaver#12374]
Support Materialized Views in Greenplum.
It is possible to specify a distribution key for the Materialized View. But DBeaver doesn't show the distribution key in the DDL of the materialized view.

**Comment by lintzc** [comment]
The storage options are not displayed too.
You can take the DDL example below:
```
create table t1 (a int, b text, c timestamp) distributed by (a);
create materialized view mv_t1_dk_a with (appendonly=true, compresstype=zstd) as select * from t1 with no data distributed by (a);
```

**Comment by LonwoLonwo** [comment]
Distribution info added for Materialized View in Greenplum, and extra options info added for views and Materialized views for Greenplum and PostgreSQL in DBeaver 21.1.1

![2021-06-07 12_46_04-Window](https://user-images.githubusercontent.com/45152336/121173394-711c6000-c861-11eb-9ec6-639fc3e19def.png)

**Comment by uslss** [comment]
verified
