### ISSUE TITLE
DB dump Export: custom date/timestamp format variables (like ${Y}, ${d}, ${m} etc)

### ISSUE THREAD

**Issue by allanlaal** [dbeaver/dbeaver#12389]
**Is your feature request related to a problem? Please describe.**

currently `${timestamp}` produces `202105091341` and `${date}` produces `20210509`
neither of which is very human (read: non-sysadmin) readable

**Describe the solution you'd like**

I propose adding custom date format variables that produce a single part of the timestamp.

**Additional context**

lets use [C-like](https://www.php.net/manual/en/datetime.format.php) [date format variables](https://zetcode.com/articles/cdatetime/)

they would be formatted as `${c_like_date_format_letter}` i.e. `${Y}`, `${d}`, `${m}` etc

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. We are going to implement it in one of future releases.

**Comment by ShadelessFox** [comment]
Hello @allanlaal,

Do you aware that you can edit timestamp format in Data Transfer? What's your use case?

![image](https://user-images.githubusercontent.com/35821147/135456460-844dc4d3-4a38-4b9f-95a1-c51926100631.png)

I'm not sure whether we want to have several specific to date/time variables or not.

**Comment by allanlaal** [comment]
I meant dumping the entire db: Connection X → Databases → Database Y: right click → Tools → Dump Database

**Comment by ShadelessFox** [comment]
Whoops. Thanks for clarification.

**Comment by ShadelessFox** [comment]
Added new pattern variables for tools and data transfer: `${year}`, `${month}`, `${day}`, `${hour}`, and `${minute}`.

**Comment by Matvey16** [comment]
Verified
