### ISSUE TITLE
Export data in SQL format file split into files of max size

### ISSUE THREAD

**Issue by Softsuit** [dbeaver/dbeaver#12391]
We have some big tables to migrate from oracle to postgresql.  The export to SQL 'INSERT INTO' format seems the best way to do.  However I ran into JDBC problems of the file being too large.  So I used the split option.  However, seems that the first file end without ';' and the following file starts with a comma.  Running these sql files to upload the data gives errors.  If we need to join these files again, we run into the problem of having too large files.  Better would be to structure every file with a starting insert into and ending with a ;

**Comment by LonwoLonwo** [comment]
Hello @Softsuit 
Can you tell me more about how you use DBeaver export?

As example - standard DBeaver SQL export:

1. Choose table for export
![2021-05-10 19_09_43-DBeaver Enterprise 21 0 5 - address](https://user-images.githubusercontent.com/45152336/117690620-b9455580-b1c3-11eb-8a48-b8e369f0672f.png)

2. Choose "Export as SQL"
![2021-05-10 19_10_11-Data Transfer](https://user-images.githubusercontent.com/45152336/117690669-c5311780-b1c3-11eb-969b-63910844d54d.png)

3. Export settings. Use "Insert" as "Insert keyword" (default value). 
You can change row count in statement in setting "Data rows per statement"
![2021-05-10 19_10_19-Data Transfer](https://user-images.githubusercontent.com/45152336/117691051-23f69100-b1c4-11eb-91cc-eb1ae768bb9d.png)

4. And this is result of this export. It has 'INSERT INTO' at the beginning of statement and delimiter at the end.
![2021-05-10 19_11_04-DBeaver Enterprise 21 0 5 - _localhost_ Script-24](https://user-images.githubusercontent.com/45152336/117691334-746dee80-b1c4-11eb-873e-601e4b9a70b7.png)

**Comment by Softsuit** [comment]
imho you forget the 3B screen (configure export output parameters)
![image](https://user-images.githubusercontent.com/69981590/117725683-c83cff80-b1e5-11eb-984c-d1e466de7e5d.png)
There you can split the output file with a maximum file size + compress option selected.  this leads to files named table.sql.zip, table_1.sql.zip, table_2.sql.zip etc....  Only the first file's last line contains a list of values without a ';' while the second file starts with the first line only containing a ',' (comma).  Seperately you can't run the sql files.  Only when you glue them all together again it'l be a correct syntax.  Now for an (oracle) extract to be loaded into a PostgreSQL database, I wan't to avoid the unecessary action of trying to glue them into one big file, while I could run in a loop all the small files, if they were properly ended.

**Comment by Softsuit** [comment]
Sorry I didn't mean to close this.  I expected a send button.

**Comment by LonwoLonwo** [comment]
Ok, now much clearer.

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 22.0.3

**Comment by Matvey16** [comment]
Verified
