### ISSUE TITLE
No autocompletion for object names with spaces.

### ISSUE THREAD

**Issue by mkgrgis** [dbeaver/dbeaver#12399]
#### System information: 
- Operating system (distribution) and version
Linux Mint
- DBeaver version
The last
- Additional extensions
No

#### Connection specification:
- Database name and version
Postgres 13 + PostGIS (it seems, this issue doesn't depends on DB)
- Driver name
standard
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
No autocompletion for schema names with space.
![изображение](https://user-images.githubusercontent.com/41448637/117696445-f90f3b80-b1c9-11eb-9dc0-f4fba1f36717.png)

A source of information for this bug is https://github.com/dbeaver/dbeaver/issues/12330#issuecomment-835243745

#### Steps to reproduce, if exist:
1. Create a PostGIS schema with space in name
2. Ensure global autocompletion is on
3. Try to begin a name of object in a query

**Comment by LonwoLonwo** [comment]
related to https://github.com/dbeaver/dbeaver/issues/12159

**Comment by LonwoLonwo** [comment]
Thanks for the bug report

**Comment by tati-kru** [comment]
Duplicat
