### ISSUE TITLE
UI broken on Gnome 40.1 when using with two monitors (100%, 125% zoom)

### ISSUE THREAD

**Issue by schmunk42** [dbeaver/dbeaver#12392]
#### System information: 
- Operating system (distribution) and version: Arch Linux (latest)
- DBeaver version 21.0.4.202105081620
- Additional extensions none

#### Connection specification:
UI only issue

#### Describe the problem you're observing:
I am running `gnome-shell 40.1` with two monitors, the external one on 125% zoom.

#### Steps to reproduce, if exist:

Open dbeaver (usually opens on large external screen), looks like this:
![Bildschirmfoto von 2021-05-10 13-48-54](https://user-images.githubusercontent.com/649031/117657037-622a8b00-b199-11eb-9e80-4f211792f89d.png)

Resize dbeaver window:
![Bildschirmfoto von 2021-05-10 13-49-16](https://user-images.githubusercontent.com/649031/117657705-2b08a980-b19a-11eb-88c8-ae4133b27ae4.png)

Move to laptop screen (100% zoom) and move back to external monitor:
![Bildschirmfoto von 2021-05-10 13-49-33](https://user-images.githubusercontent.com/649031/117657604-0ca2ae00-b19a-11eb-97b7-dc0a3cf0956d.png)

After **Restart Now** the process starts again, if I answer "no" I can use dbeaver, but with very small icons.
![Bildschirmfoto von 2021-05-10 14-15-57](https://user-images.githubusercontent.com/649031/117657800-4b386880-b19a-11eb-8a0b-74780796af2b.png)

Only on the native screen it looks OK.

**Comment by kseniiaguzeeva** [comment]
I'm afraid, it is a third party issue and we have to wait for a fix. Closed as a duplicate https://github.com/dbeaver/dbeaver/issues/6581
