### ISSUE TITLE
Data types are rearranged after Data Types node refresh

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#12400]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.0.5 EA

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
Data types are rearranged  after Data Types node refresh (option is disabled in settings)
![2021-05-10_20h12_22](https://user-images.githubusercontent.com/31996417/117698531-818edb80-b1cc-11eb-9271-85dd22f0f2fd.gif)

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.1.1

**Comment by uslss** [comment]
verified
