### ISSUE TITLE
dbeaver update bug

### ISSUE THREAD

**Issue by lzb-libra** [dbeaver/dbeaver#12409]
Some time ago, I installed a plug-in so that dbeaver could export data to Excel. Recently, I opened the dbeaver prompt to upgrade. After upgrading, I found that the plug-in I installed was gone, gone, gone. And every time I start dbeaver it pops up and says "Empty Command Specified"
Before the update
![image](https://user-images.githubusercontent.com/63389341/117777684-6c1ebd80-b26f-11eb-948d-e58c534d88f8.png)
After the update
![image](https://user-images.githubusercontent.com/63389341/117775960-9a030280-b26d-11eb-923e-0388932381a6.png)

**Comment by ShadelessFox** [comment]
Hello @lzb-libra,

Please refer to https://github.com/dbeaver/dbeaver/wiki/Extension-Office

Let me know if your issue was solved.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
