### ISSUE TITLE
Can not copy whole value

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#12417]
#### System information: 
- Linux Mint v19.3
- DBeaver version 21.0.3

#### Describe the problem you're observing:
When I want to copy plan I can not. All value is not displayed (plan is 1.6Mb in size)

#### Steps to reproduce, if exist:

    EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) SELECT * FROM ....

2. Try to copy value.

![image](https://user-images.githubusercontent.com/799021/117855655-5d4a0200-b293-11eb-8be9-2ca320c697f7.png)

I am at the `end` of string, but as you can see this is not complete JSON

7.xx version have not such problem

**Comment by uslss** [comment]
is it possible to copy it using Ctrl+C or from the value panel?
![image](https://user-images.githubusercontent.com/31996417/117946902-5fa26f80-b318-11eb-9260-60bc4e5fa129.png)

**Comment by KES777** [comment]
At your case it is "Yes", but please do double click to enter edit mode for cell.
Then you can not CTRL+C whole value, even if CTRL+A, because value is not displayed fully

**Comment by KES777** [comment]
Probably another case:

![image](https://user-images.githubusercontent.com/799021/119695489-e39b4200-be56-11eb-92de-b4a0a13eae3c.png)

Here I switch to text and value is truncated. But this case seems belongs to this one

**Comment by ShadelessFox** [comment]
Hello @KES777,

Can you provide minimal, environment-independent example to reproduce against?

I tried generating really long `EXPLAIN` output, but I was unable to reproduce your issue.

Also, what is the database version?

**Comment by KES777** [comment]
@ShadelessFox : 
>very long

How many megabytes?

> is the database version?

PostgreSQL v13.1

**Comment by ShadelessFox** [comment]
It was around 10 MiB. I was testing on PostgreSQL 12.0

**Comment by LonwoLonwo** [comment]
> Here I switch to text and value is truncated. But this case seems belongs to this one

A text field has a limit, this is expected behavior. You can change it in Preferences:

![2021-07-28 10_53_46-Window](https://user-images.githubusercontent.com/45152336/127285699-8aee6b2c-a294-41b2-9b70-f4aeaef81263.png)

**Comment by LonwoLonwo** [comment]
If the value panel works fine and the problem is just in the cell capacity, so maybe you can track the line number on which the copied value is broken? 

![2021-07-28 10_57_07-Window](https://user-images.githubusercontent.com/45152336/127286265-e206a65c-4fa1-4ef5-a7fb-d473bb07e6c9.png)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual - feel free to reopen it with additional info that will help to reproduce an issue
