### ISSUE TITLE
Column name Autocompletion does not work with join queries on mssql

### ISSUE THREAD

**Issue by bender270** [dbeaver/dbeaver#12415]
#### System information: 
- Windows 2010 64 bits
- DBeaver version 21.0.4
- Additional extensions

#### Connection specification:
- Database Microsoft SQL Server 2014 (SP3-GDR) (KB4583463) - 12.0.6164.21 (X64) 
	Nov  1 2020 04:25:14 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)
- Driver name Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

I can not use autocomplete for tables columns after write the table name and a dot and press CTRL+SPACE, on queries which use joins.
It happens since version 21.0.3, on 21.0.2 It works fine

#### Steps to reproduce, if exist:

Create the example database that I attach

create a new script for this database and paste this:

> USE test_database;
> 
> select * from regions;
> 
> SELECT
> 	countries.country_name, regions.             _--put your cursor after the dot and press CTRL+SPACE the columns that It suggests are from countries table, no from regions_
> FROM
> 	countries
> JOIN regions ON
> 	countries.region_id = regions.region_id
> WHERE
> 	country_id = 'DE';

![2021-05-11 18_12_54-Window](https://user-images.githubusercontent.com/7341240/117849481-a6df2080-b284-11eb-83bb-31fb98c4612d.png)

[exampleDB.zip](https://github.com/dbeaver/dbeaver/files/6460573/exampleDB.zip)

**Comment by Matvey16** [comment]
Thank you for the report. Unfortunately I couldn't reproduce this issue. Can you try this on version 21.0.5 ?

![2021-05-20_16h46_40](https://user-images.githubusercontent.com/82543000/118989760-f6130880-b98a-11eb-8422-5a10cbfc55c2.png)

**Comment by bender270** [comment]
It seems to be fixed in 21.0.5 version. Thanks!
