### ISSUE TITLE
DBeaver - Error when setting option Show Whitespace Characters via the preferences

### ISSUE THREAD

**Issue by F0xD8rk** [dbeaver/dbeaver#12427]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.0.4.202105021514

#### Describe the problem you're observing:

When you select the **Show whitespace characters** option via the preferences, an error is shown.

#### Steps to reproduce, if exist:

1. Select the option **Show whitespace characters** in the settings
2. Click button **Apply**
3. An error window is shown

![afbeelding](https://user-images.githubusercontent.com/79097587/117944820-f3227300-b30d-11eb-95cd-926c1e6b2e55.png)

In the details pane of the first error, the following text is shown:

_Error notifying a preference change listener. Check the log for details.
Argument cannot be null_

In the **Error logs** pane, I see the following error information:

![afbeelding](https://user-images.githubusercontent.com/79097587/117945524-b1de9300-b30e-11eb-871a-8e14ed87ec27.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
Hello @F0xD8rk,

I cannot reproduce your issue. Is the problem occurs every time you're trying to toggle that option?

Also, consider upgrading to newer version to see if the problem was solved: https://dbeaver.io/files/ea

**Comment by F0xD8rk** [comment]
Hi @ShadelessFox 

I had the error every time I selected the checbox and clicked on Apply.
After installation of het newest version today (21.1.0.202106012023), the problem seems to be solved.
I also can't reproduce it anymore now.

**Comment by ShadelessFox** [comment]
I'm glad your problem was solved!
