### ISSUE TITLE
See only objects from connected schema - e.g. via separate section 

### ISSUE THREAD

**Issue by wa-pretzels** [dbeaver/dbeaver#12424]
#### System information: 
- Operating system (distribution) and version - Windwos 10
- DBeaver version - DBeaver IDE	21.0.4.202105021514
- Java version - openjdk version "1.8.0_282"
- Additional extensions 

#### Connection specification:
- Database name and version - Oracle 19c
- Driver name - ojdbc8
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing: 
Our database has hundreds of schemas and I have several connections to connect to specific schemas.
I want to see only the database objects in the schema which I'm connected to but I don't want set manually always a filter on this one schema. 
An separate section to see all objects from the connection would solve the problem.

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea. We will implement it for different databases.

**Comment by Skydiveroid** [comment]
We can add option "Show all schemas" in Oracle connection dialog

**Comment by wa-pretzels** [comment]
The option "Show all schemas" is currently the default. The option should be more like see only objects of the connected schema. Currently i would have to add manualy a filter for the schema I'm using in the connection.

**Comment by LonwoLonwo** [comment]
Ability to download and show only current user schema (system or not) implemented for Oracle in DBeaver 21.2.5.
Setting for that you can be found in the Oracle connection settings page (Oracle properties tab).

![2021-11-03 14_45_00-DBeaver Ultimate 21 2 4 - _orcl_Script-42](https://user-images.githubusercontent.com/45152336/140076262-b9f1f04d-4ca9-4217-8a44-c36461b806ff.png)

**Comment by uslss** [comment]
verified
