### ISSUE TITLE
Highlighting incorrect row when selecting while sorted

### ISSUE THREAD

**Issue by ralius18** [dbeaver/dbeaver#12423]
#### System information: 
- Windows 10 version 20H2, build 19042.928
- DBeaver version: 21.0.4.202105021514

#### Connection specification:
- Database name and version: MySQL 5.1.44
- Driver name: MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH Tunnel

#### Describe the problem you're observing:
When selecting rows while script results are sorted, the associated data row is highlighted instead of the expected/selected cell's row

#### Steps to reproduce, if exist:
Run script to output some results
Select a cell in the result panel, observe the full row is highlighted
Sort the results on a column
Select another cell, observe that the row data highlighted is the row that would be in the selected location without the sorting

![image](https://user-images.githubusercontent.com/16752252/117916176-bc168680-b33a-11eb-92e3-de161b1bbe16.png)

In this instance, AIins01 is the first row without sorting, so when the sorting is active, selecting a cell on the first row, the AIins01 row is highlighted

Also observed in regular table browsing, but noticed initially in Script results.

**Comment by LonwoLonwo** [comment]
Hello @ralius18 
Thanks for the bug report.
We fixed this problem here: https://github.com/dbeaver/dbeaver/issues/12286
Fix will be available in DBeaver 21.0.5 on 2021-05-17
or you can test it in Early Access version https://dbeaver.io/files/ea/
