### ISSUE TITLE
Output log configation stop working in Preferences after using the button in Output log window

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12434]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.5

#### Steps to reproduce, if exist:
1. Open Output log
2. Change Open output viewer on new mennages parameter
3. Go to Preferences

**Expected:** the setting is updated in Preferences
**Actual result**: 
- the setting is not updated
- if you try to change the parameter in Preferences after that, the changes will not be applied

https://user-images.githubusercontent.com/51405061/117975368-478e1880-b337-11eb-9a94-7edf909283c8.mp4

**Comment by ShadelessFox** [comment]
The configuration is changed for the current data source only, not globally.
