### ISSUE TITLE
text to hex converting problem

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12438]
#### System information: 
- widows 10
- DBeaver 21.0.5

#### Connection specification:
- SQLite, default driver

#### Describe the problem you're observing:
Click on the text type data : view / format -> set table format -> binary. If just choose Binary hex and then OK, then only troubles with some letters happen:
![text](https://www.linkpicture.com/q/Screenshot_3_38.png)
![text](https://www.linkpicture.com/q/Screenshot_1_64.png)
![text](https://www.linkpicture.com/q/Screenshot_2_47.png)
 But If choose hex from expanding list then correct hex format would be presented:
![](https://www.linkpicture.com/q/Screenshot_4_24.png)
![](https://www.linkpicture.com/q/Screenshot_5_18.png)

**Comment by uslss** [comment]
verified
