### ISSUE TITLE
"Auto assign" button when importing DB-DB table seems to have no useful behavior

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12439]
widows 10, SQLite
Open two sqlite databases in Database Navigator. In one of them right click on table -> import data -> choose table exporting format - > next. And at that step, if click choose auto assign button
![Screenshot_6](https://user-images.githubusercontent.com/43252954/117993284-41ecfe80-b348-11eb-932a-81190169676d.png)
and then choose DB for export the table "Source" is still "none". Even if both DBs have exactly the same tables and even if there multiple tables for importing were chosen nothing happens

**Comment by tati-kru** [comment]
We need to disable or hide Auto-assign button for import tasks.

**Comment by flambchap** [comment]
Added message when auto-assign failed. Also fixed the handling of databases without catalogs and schemas such as SQLite.

**Comment by Matvey16** [comment]
Verified
