### ISSUE TITLE
SQL Console can be opened for public schema only

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12433]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.5

#### Connection specification:
- Database name and version PostgreSQL, Greenplum, other PostgreSQL forks?
#### Steps to reproduce, if exist:
Open SQL Console for a non-public schema

**Expected**: SQL Console is opened for the selected schema
**Actual result**: SQL Console is opened for public schema
**Workaround**: open SQL Editor

https://user-images.githubusercontent.com/51405061/117973721-67244180-b335-11eb-9bf2-cfaf3cc62eda.mp4

**Comment by flambchap** [comment]
I've reproduced this bug on Snowflake, which suggests that this problem is relevant for all DBMS' with catalogs and schemas.

**Comment by flambchap** [comment]
Actually, the problem is also relevant for databases with schemas only.

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
