### ISSUE TITLE
Session properties cannot be overridden once a transaction is active

### ISSUE THREAD

**Issue by wandajuan-houzz** [dbeaver/dbeaver#12445]
#### System information: 
- Operating system: MacOS
- DBeaver version: Version 21.0.4.202105021514
- DB: Presto

#### Describe the problem you're observing:
Hi, 

I had been using right click -> Execute -> Export from Query -> Copy to Clipboard to paste query results into local.
But since yesterday when I tried to import a huge .csv file and failed multiple times, this copy to clipboard thing does not work anymore with this error message. 
Task execution failed

Reason:
SQL Error [65536]: Query failed (#20210513_071843_02069_7amz6): Session properties cannot be overridden once a transaction is active

![image](https://user-images.githubusercontent.com/79892668/118092081-34924b80-b3fe-11eb-9e8e-0f6ab091af06.png)

I tried restart, reinstall to make sure there is no action transaction, but this error is not resolved. 
Please help. Thank you very much!

**Comment by uslss** [comment]
@wandajuan-houzz do you use manual commit or auto-commit?

**Comment by wandajuan-houzz** [comment]
Both. But I just realized when switching to auto-commit, the same error also showed up.
![image](https://user-images.githubusercontent.com/79892668/118202043-94830380-b48b-11eb-89fa-3557b2d5e411.png)

**Comment by danialmirza** [comment]
Also experiencing the same issue as OP when using "Export from Query" after trying to import a csv. Option was working fine until recently.

**Comment by uslss** [comment]
is it still actual against 21.1.0?

**Comment by danialmirza** [comment]
Yes - I recently updated to 21.1.0 from a (much) older release and still hitting a similar error
![Screen Shot 2021-06-11 at 10 51 14 AM](https://user-images.githubusercontent.com/26485450/121705772-fb9fd200-caa2-11eb-895f-fe5e0d0184e5.png)

**Comment by Matvey16** [comment]
Can you show how your transactions options are configured

![2021-06-17_10h31_15](https://user-images.githubusercontent.com/82543000/122351966-56c83d80-cf57-11eb-8f88-3823f138de6d.png)

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual - feel free to reopen it with additional info to reproduce the issue.
