### ISSUE TITLE
Incorrect request generated when saving changes on vertica 10.1 database

### ISSUE THREAD

**Issue by darkag** [dbeaver/dbeaver#12440]
Hello,

when updating a table without primary key on vertica 10.1, auto-generated request doesn't take all columns in where conditions.

more on that, the request send when saving is not the same that the one shown on script preview.

for exemple:

request send to database :
UPDATE schema.TABLE SET COLUMN1='VALUE' WHERE COLUMN1 IS NULL AND COLUMN10='VALUE10';

request shown in script :
UPDATE schema.TABLE SET COLUMN1='VALUE' WHERE COLUMN1 IS NULL AND COLUMN10=NULL;

I don't know why column10 is selected and not the others, and I don't understand how a column10=null could appear in a where condition since it will always return false

request send to database on same table on vertica 9
UPDATE schema.TABLE
	SET COLUMN1='VALUE'
	WHERE COLUMN1  IS NULL AND COLUMN2='VALUE2' AND ... COLUMN10='VALUE10' AND ... COLUMN20='VALUE20';

I'm using last version of dbeaver (21.0.4) and last version of vertica driver 10.1

**Comment by darkag** [comment]
ok I've found that I had an incorrect virtual primary defined. By the way I had to edit the config file since I can't find a way to do it with the GUI.

And there is still the problem of inconsistant query with column=null in where close

**Comment by Matvey16** [comment]
> And there is still the problem of inconsistant query with column=null in where close

Sorry, I can't really understand the exact issue you are having. Can you describe the steps that lead to this issue?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info
