### ISSUE TITLE
row selection focus is wrong

### ISSUE THREAD

**Issue by LuiFerPereira** [dbeaver/dbeaver#12442]
#### System information: 
- Operating system (distribution) and version: MacOS 11.3.1
- DBeaver version: Version 21.0.4.202105021514
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

row selection focus is wrong. Using keyboard arrows to move between rows, the row selection focus don't stay in the corrected row

**Comment by uslss** [comment]
@LuiFerPereira could you provide a video with an issue or more clear steps to reproduce?
thanks in advance

**Comment by ShadelessFox** [comment]
Looks like that the issue was fixed in #12286.

Can you try upgrading to the early access version to see if the problem was resolved? https://dbeaver.io/files/ea/

**Comment by LuiFerPereira** [comment]
solved
