### ISSUE TITLE
Native support for macOS/ARM (Apple Silicon M1)

### ISSUE THREAD

**Issue by quicksnap** [dbeaver/dbeaver#12441]
This is essentially a continuation of #10470. If this is inappropriate as a new ticket, feel free to close!

The current build runs on Rosetta 2, which functions, albeit somewhat sluggishly with UI drawing.

A [previous comment](https://github.com/dbeaver/dbeaver/issues/10470#issuecomment-801070802) linked to a now-fixed upstream issue with Ecipse here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=565690

If there isn't already a tracking ticket for this work, could this serve as it? I'd just like somewhere to watch progress.

Thanks for the amazing tool!

**Comment by supervate** [comment]
Ummm,its very slowly in Apple silicon M1. Really expecte the new version that compability with M1.

**Comment by kseniiaguzeeva** [comment]
We are waiting for Java 17 (the release is going to be in September) and [Eclipse](https://bugs.eclipse.org/bugs/show_bug.cgi?id=565690) to support it.

**Comment by ahsandev2019** [comment]
> We are waiting for Java 17 (the release is going to be in September) and [Eclipse](https://bugs.eclipse.org/bugs/show_bug.cgi?id=565690) to support it.

so the native version will be waiting java 17?  
i want to move to m1 mac, but maybe i will delay it due dbviewer not supported at native apps

**Comment by supervate** [comment]
What a pity :(



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月28日(星期五) 下午2:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dbeaver/dbeaver] Native support for macOS/ARM (Apple Silicon M1) (#12441)





  
We are waiting for Java 17 (the release is going to be in September) and Eclipse to support it.
  
so the native version will be waiting java 17?
 i want to move to m1 mac, but maybe i will delay it due dbviewer not supported at native apps

**Comment by quicksnap** [comment]
@ahsandev2019 While the UI in DBeaver on M1 is sluggish, it is definitely still usable. I've found my M1 to be great overall.. much nicer than the x86 laptops I've had, even recently.

If you're not doing serious native x86-based work, I highly recommend considering an M1!

**Comment by bozhidarc** [comment]
The Eclipse issue for supporting Apple Silicon is now resolved [#565690](https://bugs.eclipse.org/bugs/show_bug.cgi?id=565690#c59). There is a RC which can be download, and 4.20 will be released on June 16 😃 .
I hope with the next release of DB will be based on this Eclipse version. 

P.S
I'm using it on my M1, it's a little slugish, but is is bearable.

**Comment by supervate** [comment]
I expect it so much.

**Comment by ahsandev2019** [comment]
> @ahsandev2019 While the UI in DBeaver on M1 is sluggish, it is definitely still usable. I've found my M1 to be great overall.. much nicer than the x86 laptops I've had, even recently.
> 
> If you're not doing serious native x86-based work, I highly recommend considering an M1!

now im use M1, i tried dbviewer everything is working but sometimes got some bugs and reinstall it using rosetta, but the UI so ugly, the text can't be focus, im use sequel ace right now, i hope dbviewer can release the M1 native or maybe the ui text not focus can be fixed 
this is dbviewer text https://i.imgur.com/KzR0WRB.png
and this is sequel ace (native) https://i.imgur.com/axhLHli.png

i dont know the problem, but if the ui can be fixed im very happy to back use dbviewer, and i have plan to buy the premium to use at mongo client too

**Comment by louis-hoang21** [comment]
I don’t know how much time I have to wait. DBeaver via rosetta IS working on M1 very badly. I hope the next released BD will work well on M1

**Comment by hpyperry** [comment]
eclipse already support m1
[https://download.eclipse.org/eclipse/downloads/](url)

**Comment by aminta** [comment]
Following...

**Comment by owiofwm2i** [comment]
Is there a specific update date? I haven't opened this software for 7 months and I feel bad when I see the structure of intel

**Comment by quicksnap** [comment]
@n0thing2speak did you read above?

> We are waiting for Java 17 (the release is going to be in September) and [Eclipse](https://bugs.eclipse.org/bugs/show_bug.cgi?id=565690) to support it.

**Comment by yaoguoba** [comment]
- MacOS X M1 installer was added (beta)

dbeaver-ce-21.2.1-macos-aarch64.dmg
dbeaver-ce-21.2.1-macos-x86_64.dmg
dbeaver-ce-21.2.1-macosx.cocoa.aarch64.tar.gz
dbeaver-ce-21.2.1-macosx.cocoa.x86_64.tar.gz

which link is for M1 version?

**Comment by ngohungphuc** [comment]
@yaoguoba dbeaver-ce-21.2.1-macos-aarch64.dmg

**Comment by yaoguoba** [comment]
![image](https://user-images.githubusercontent.com/18393410/133951447-e363457e-95a7-4dec-ab02-8ee3157d5125.png)

@ngohungphuc but why it's still intel app.

**Comment by louis-hoang21** [comment]
> * MacOS X M1 installer was added (beta)
> 
> dbeaver-ce-21.2.1-macos-aarch64.dmg
> dbeaver-ce-21.2.1-macos-x86_64.dmg
> dbeaver-ce-21.2.1-macosx.cocoa.aarch64.tar.gz
> dbeaver-ce-21.2.1-macosx.cocoa.x86_64.tar.gz
> 
> which link is for the M1 version?

[Here is it](https://dbeaver.io/files/ea/). But I tested it but it's not working on the m1. Currently, it is still running via rosetta 2
<img width="946" alt="Screen Shot 2021-09-20 at 09 42 10" src="https://user-images.githubusercontent.com/35162077/133952622-81ce11c4-8d80-4ff5-bd36-cff21ea57a1e.png">

**Comment by ngohungphuc** [comment]
@yaoguoba No idea :D You need to ask the contributor

**Comment by yaoguoba** [comment]
@serge-rider is the file wrong?

**Comment by quicksnap** [comment]
Yesssssssssssssssss I love you all thank you so much! I will test soon.

**Comment by supervate** [comment]
the aarch still running in intel archtecture,and still slow and laggy...

**Comment by 2nal2** [comment]
I also downloaded the dbeaver-ce-21.2.1-macos-aarch64.dmg and run as intel for me too

**Comment by flambchap** [comment]
Replaced packaged JRE for x86_64 with a JRE for Aarch64, everything seems to work just fine.

**Comment by yaoguoba** [comment]
![image](https://user-images.githubusercontent.com/18393410/134767423-127de510-1266-45ae-af7e-871e5e73d2dd.png)

Hi @akilovich, I updated my JRE to zulu-17.jre (arm64), but it still run as intel.
Could you please share your JRE version?

**Comment by supervate** [comment]
![image](https://user-images.githubusercontent.com/30173876/134769127-bd883833-0109-4ef9-ac57-8c17fac26de2.png)
![image](https://user-images.githubusercontent.com/30173876/134769180-3f3fc60e-3aab-4085-9244-4cffce250f73.png)

I replace the default jdk to zulu-17 then it is crash :( , I tried jdk11 too.

**Comment by hpyperry** [comment]
> Replaced packaged JRE for x86_64 with a JRE for Aarch64, everything seems to work just fine.

Can you give a tutorial? I tried to replace jre, but all it does is prompt Contents/Home/bin... /jre/lib/server/libjvm.dylib" does not contain the JNI_CreateJavaVM symbol

**Comment by flambchap** [comment]
@yaoguoba @suopovate @beichenhpy We're planning to release a properly packaged AArch64 build soon, stay tuned.

**Comment by hpyperry** [comment]
> @yaoguoba @suopovate @beichenhpy We're planning to release a properly packaged AArch64 build soon, stay tuned.

Thank you very much for your reply, I am looking forward to the new version

**Comment by Matvey16** [comment]
Verified

**Comment by ingcrengifo** [comment]
@akilovich any possible date?

**Comment by flambchap** [comment]
@INGCRENGIFO Next Monday.

**Comment by 2nal2** [comment]
Thank you!, now appears as an apple process!
