### ISSUE TITLE
DB Navigator global filter doesn't work for tables

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12460]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.5 EA

#### Connection specification:
- Database name and version Vertica
#### Steps to reproduce, if exist:
1. Expand Tables folder in DB Navigator and select **Filter** in a table context menu
2. Click **Configure filter**
3. Select **Show global filter** in the opened dialog
4. Enter a valid table name and apply the filter

**Expected**: the tables are filtered in all Vertica schemas according the criteria
**Actual result**: all tables remain visible in DB Navigator
![aB1qKCQS0L](https://user-images.githubusercontent.com/51405061/118242967-93ab9b00-b4a6-11eb-8949-7d1926dafb2c.gif)

**Comment by Matvey16** [comment]
Verified
