### ISSUE TITLE
Full-text and Metadata search do not work in Vertica

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12467]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.5

#### Connection specification:
- Database name and version Vertica

#### Steps to reproduce, if exist:
1. Open metadata search, select Vertica, enter a valid value and begin the search

**Expected:** suitable objects are found
**Actual result:** objects are not found and an error appears: `SQL Error [100161] [HY000]: [Vertica][VJDBC](100161) The connection is closed.`

2. Open Full-text search, select Vertica, enter a valid value and begin the search

**Expected:** suitable objects are found
**Actual result:** objects are not found

**Comment by uslss** [comment]
verified
