### ISSUE TITLE
The last table only opens in case of export more than one table

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#12462]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.0.5
- 
#### Describe the problem you're observing:
In case of export more than one table to database (Open table editor on finish option is enabled) only the last table opens in editor.

**Comment by flambchap** [comment]
The problem is present only if we create new tables during the export.

**Comment by Matvey16** [comment]
Verified
