### ISSUE TITLE
Incorrect types for columns are chosen during the export to new table from another table

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#12461]
#### System information: 
- Operating system (distribution) and version win10 
- DBeaver version 21.0.5

#### Connection specification:
- Database name and version CockroachDB 20.1.5
- 
#### Describe the problem you're observing:
Export SQLite - Cockroach
Integer type is mapped to varbit
BLOB - to bytea
Datetime - to varchar
Numeric - to varbit
![image](https://user-images.githubusercontent.com/31996417/118242617-344d8b00-b4a6-11eb-9a58-aecd980b1148.png)
![image](https://user-images.githubusercontent.com/31996417/118243256-e8e7ac80-b4a6-11eb-8d64-ebf938cac8b7.png)
![image](https://user-images.githubusercontent.com/31996417/118243443-21878600-b4a7-11eb-9c0f-a377e5cd6ce6.png)

**Comment by ShadelessFox** [comment]
The `BLOB` &rArr; `bytea` conversion looks fine to me

**Comment by LonwoLonwo** [comment]
Fixed for NUMERIC, NUMERIC(10,2) (ore another modifiers), INTEGER, INT. 
Search data types in PG/PG forks bases generally improved.
Search for types with modifiers improved.
Datetime is string type in SQLite -  https://www.sqlite.org/datatype3.html

**Comment by kseniiaguzeeva** [comment]
verified
