### ISSUE TITLE
Two tabs are opened in case of explaining execution plan without any resultset open

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#12464]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.0.5

#### Connection specification:
- Database name and version PostgreSQL, Oracle, Cockroach

#### Steps to reproduce, if exist:
1. Open SQL editor and write some query (e.g. `Select 1;`)
2. Perform Explain execution plan.

**Actual result**
Two tabs open. First tab - Result 1 is empty, the second tab contains the execution plan.

![2021-05-14_12h44_27](https://user-images.githubusercontent.com/31996417/118253165-40d7e080-b4b2-11eb-86e1-6958f96677a9.gif)

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified

**Comment by serge-rider** [comment]
See #13636
