### ISSUE TITLE
Generate mock data falls with SQL error [30000]

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12468]
#### System information: 
- Windows 10, DBeaver EE 21.0.5
-  Derby DB, Derby Server driver, SSH

#### Describe the problem you're observing:
Wen I try to "Generate Mock Data" in that simple table (without any data in it):
![image](https://user-images.githubusercontent.com/43252954/118269164-0c225400-b4c7-11eb-86a4-3ea578361c89.png)
CREATE TABLE TEST.NEWTABLE (
	COLUMN1 INTEGER NOT NULL,
	COLUMN2 VARCHAR(100),
	CONSTRAINT NEWTABLE_PK PRIMARY KEY (COLUMN1)
);
it falls with "Error generating mock data: SQL Error [30000] [42X01]: Syntax error: Encountered "NULL" at line 1, column 26."
![image](https://user-images.githubusercontent.com/43252954/118269326-47248780-b4c7-11eb-9df7-21b8295fd03c.png)

Generators properties screensots:
![image](https://user-images.githubusercontent.com/43252954/118269574-98347b80-b4c7-11eb-8b5f-ba832eae9351.png)
![image](https://user-images.githubusercontent.com/43252954/118269648-aa161e80-b4c7-11eb-8019-7c84970b8d7b.png)

**Comment by LonwoLonwo** [comment]
Cn not reproduce in the latest DBeaver version
