### ISSUE TITLE
[macOS] Row manipulation buttons from spreadsheet toolbar don't disable when inline editor is opened

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12473]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.0.5 EA
#### Describe the problem you're observing:
~~1. True/false and yes/no format Boolean moves to the cell center after clicking on it. If you click the next Boolean right after that, it will jump to the cell center and back to the left cell border.
https://user-images.githubusercontent.com/51405061/118278325-902e0900-b4d2-11eb-891e-f85129b31a22.mov~~
~~2. An error appears when you double-click boolean and then press some of edit or navigation buttons on the bottom toolbar. The buttons do not work in this case~~
https://user-images.githubusercontent.com/51405061/118278029-2ada1800-b4d2-11eb-98fa-4d4d306f28d6.mov
~~3. Checkbox to edit boolean is not removed when you click somewhere out of table field (e.g. to filter field)
https://user-images.githubusercontent.com/51405061/118278624-dd11df80-b4d2-11eb-8c0a-0457cb5e7748.mov~~
~~4. SQLite: Checkbox to edit boolean doesn't appear after double-clicking a boolean: the cell turns to inline edit mode
https://user-images.githubusercontent.com/51405061/118278912-30842d80-b4d3-11eb-8728-f846747f065e.mov~~

**Comment by flambchap** [comment]
Problem 3 can be reproduced with Postgres' enums as well.

**Comment by flambchap** [comment]
There is an additional problem in scenario 1. If we click on a boolean cell and then press escape, the cell's value disappears. It is not mac-specific.

**Comment by flambchap** [comment]
Scenario 1 is a feature, not a bug. It helps to distinguish the normal state from the edit state. Also, it's not mac-specific.

**Comment by flambchap** [comment]
Just like with problem number 3, problem 2 can be reproduced with Postgres' enums.

**Comment by flambchap** [comment]
Okay. At this point, it's impossible to handle those 4 problems in one ticket since it's clear that they have different nature. Separate tickets will be created shortly.

**Comment by flambchap** [comment]
Scenario 4 is not a bug since there is no boolean type in SQLite.

**Comment by E1izabeth** [comment]
Both #13910 and #13912 (cases 2 and 3) was solved.
