### ISSUE TITLE
When importing data, ask to trim data that is too long for a column.

### ISSUE THREAD

**Issue by ctreadw6** [dbeaver/dbeaver#12474]
**Is your feature request related to a problem? Please describe.**
When importing data, if a value is too long for a column, the import fails. 
![image](https://user-images.githubusercontent.com/10664464/118300179-a5de0700-b4af-11eb-9d91-0f0de034925e.png)

**Describe the solution you'd like**
It would be nice to have the options to:
Skip Row
Skip Row (and don't ask again)
Trim
Trim (and don't ask again)
A report of some sort would generate at the end of the import to show which rows were skipped or trimmed.

This is how TOAD handles it:
![image](https://user-images.githubusercontent.com/10664464/118301450-0de11d00-b4b1-11eb-9378-cf97c776d2d1.png)

**Describe alternatives you've considered**
Current alternatives are to use a different db client, or trim the data before importing.

**Comment by kseniiaguzeeva** [comment]
We will add an option to convert data types during data transfer in https://github.com/dbeaver/dbeaver/issues/12608.
I close this ticket, because your issue should be solved after implementing it.
