### ISSUE TITLE
Wrong flex table syntax

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12477]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.5 EA
#### Connection specification:
- Database name and version Vertica

**Two cases exist**: wrong syntax is used when a flex table is created  via UI and flex table appears in Tables folder when you create it via SQL Editor

#### Steps to reproduce, if exist:
**Case 1**:
Create flex table via UI
**Expected**: the flex table is created https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/SQLReferenceManual/Statements/CREATEFLEXTABLE.htm
**Acual result**: a usual table is created

**Case 2**:
Create flex table via SQL Editor (e.g. https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/FlexTables/CreatingFlexTables.htm)
**Expected**: the flex table appears in Flex tables folder
**Acual result**: objects with the table name appear in Tables, Views, Projections folders

**Comment by LonwoLonwo** [comment]
So, the reading of flex tables, simple tables, and views was changed.
More table fields added.
Statement for flex tables fixed.
Please test creating flex tables, tables, and views.

**Comment by LonwoLonwo** [comment]
System tables reading and view also was changed

![2021-06-25 12_34_48-DBeaver Enterprise 21 1 1 - all_tables](https://user-images.githubusercontent.com/45152336/123412402-397c1a80-d5ba-11eb-9b57-f225d3977953.png)

**Comment by uslss** [comment]
verified
