### ISSUE TITLE
Highlighting is not removed in Metadata Editor after moving focus and saving changes 

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12472]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.0.5 EA

_2 Mac specific cases exist:_

**Case 1**
#### Steps to reproduce, if exist:
1. Open an editable object in Metadata Editor
2. Make some inline edit
3. Click to inactive Save button after that
4. Click to the field with the object and then click on Save button again (it is active now)

**Expected**: the changes are saved, the highlighting is removed
**Actual result**: the changes are saved, the highlighting remains visible

https://user-images.githubusercontent.com/51405061/118277517-8a83f380-b4d1-11eb-847b-76d4954868a5.mov

**Case 2**
Also Boolean checkbox jumps in Metadata Editor/Data transfer dialog

https://user-images.githubusercontent.com/51405061/118293313-32a1b880-b4e2-11eb-9d02-5ecee4615932.mov

**Comment by flambchap** [comment]
There is a bigger usability problem in the entity editor. If you double-click on the boolean editor in case 1, the table column editor opens.

**Comment by flambchap** [comment]
The issue with the coloring can only be reproduced on the light theme using the default color scheme (and still not 100% of the time).

**Comment by flambchap** [comment]
Case 1 is fixed. Case 2 deserves its own ticket. The issue I mentioned above seems to be particularly my problem with double-clicks. As of now, I believe it needs to be addressed only if other users will complain.

**Comment by kseniiaguzeeva** [comment]
Case 1 is verified, separate ticket is created for case 2 https://github.com/dbeaver/dbeaver/issues/12566
