### ISSUE TITLE
Restore Default button doesn't work in some places

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12480]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.5 EA

We have to fix **Restore default** buttons which are broken on DBeaver side. See attached screenshots with places where the buttons don't work.
[restore_default.zip](https://github.com/dbeaver/dbeaver/files/6493695/restore_default.zip)

**Comment by Matvey16** [comment]
Note: "Restore Default" button returns properties to the state they were in, when the window was opened.

**Comment by LonwoLonwo** [comment]
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/19928
