### ISSUE TITLE
Set column format > Epoche time: Remember last used unit

### ISSUE THREAD

**Issue by swbr** [dbeaver/dbeaver#12484]
I have lots of databases with lots of tables, which contain integer fields with unix epoche values.
One of the features of dbeaver I really like is its ability to display such integer fields as human readable  timestamp.

However, dbeaver assumes the unix epoche is given in milliseconds, and I have to switch to seconds every time.
It would be great if dbeaver would remember the last used unit and use it as default for the next time.

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by flambchap** [comment]
Done.

**Comment by uslss** [comment]
verified
