### ISSUE TITLE
Create a column directly, the comment can’t be saved?

### ISSUE THREAD

**Issue by Ohhh12** [dbeaver/dbeaver#12486]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
@luoye003 please, provide more info: which db do you use? dbeaver version?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
