### ISSUE TITLE
Read-only: No Corresponding table column

### ISSUE THREAD

**Issue by shaoyu0102** [dbeaver/dbeaver#12485]
I want to edit value from UI But show Read-only: No Corresponding table column , 
can't edit Value in UI , Upgrate 21.0.4 after ..

![image](https://user-images.githubusercontent.com/84300411/118427000-d667b000-b6fe-11eb-8e22-d732af17b309.png)

![image](https://user-images.githubusercontent.com/84300411/118426934-bdf79580-b6fe-11eb-82a9-befd369c3cbc.png)

**Comment by Matvey16** [comment]
Can you specify what database and driver you are using?

**Comment by shaoyu0102** [comment]
> Can you specify what database and driver you are using?

Oracle

**Comment by LonwoLonwo** [comment]
Hello @shaoyu0102 
Table DDL and SQL Query are important, like here https://github.com/dbeaver/dbeaver/issues/11891
Can you provide them with us?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info that will help to reproduce an issue

**Comment by ricsajr** [comment]
you must refresh the left tab by right clicking on the table in question

**Comment by cumanacr** [comment]
@ricsajr I was having the same issue today, that does the trick, thanks!

**Comment by pupi1985** [comment]
I faced this situation with a simple `select * from table` query. Indeed, refreshing the table as explained here solved the issue https://github.com/dbeaver/dbeaver/issues/12485#issuecomment-954104923

However, I can add why I believe the issue raised. I modified the table structure (basically, added the read-only column) programatically from the application I'm developing. So it seems DBeaver caches the table structure and doesn't refresh it automatically.

@uslss Is the **Refresh active schema after SQL execution** setting the solution to this issue?

**Comment by LonwoLonwo** [comment]
Hello @pupi1985 

Yes, DBeaver doesn't refresh tables periodically. Only after specific events or pressing the button "Refresh" on schema/catalog/data source etc., in the Database Navigator tree.

"Refresh active schema after SQL execution" setting helps control the current default schema. This setting is not about table refresh.
