### ISSUE TITLE
Error when transferring big numbers in columns with DECIMAL data type

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#12488]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.05.

#### Connection specification:
- Database name and version DB2 LUW
- Do you use tunnels or proxies: SSH

#### Steps to reproduce, if exist:
1. Create a table with DECIMAL column(s)
2. Fill it with numbers to have a sum of at least 1000000
3. Begin an export of this table.

**Expected result:** Table is exported

**Actual result:** Error pops up and table is exported only with metadata.
![2021-05-17_11h11_51](https://user-images.githubusercontent.com/82543000/118459790-c0f58480-b704-11eb-84ab-42a53b9cc28b.png)

**Comment by ShadelessFox** [comment]
Similar issue: #12474

**Comment by uslss** [comment]
closed as a duplicate.
probably was fixed in the scope of #12889
