### ISSUE TITLE
Can't chose default option for "quote always" in CSV Export

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#12490]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.5

#### Connection specification:
- Database name and version DB2, Oracle

#### Steps to reproduce, if exist:
1. Select **Export** from table context menu
2. Select Export to CSV format
3. Change "quote always" option to any other than default.
4. Try to change this option again

**Expected result:** Drop down menu includes "default" option

**Actual result:** "Default" option disappears.

![2021-05-17_14h15_01](https://user-images.githubusercontent.com/82543000/118480273-afb77280-b71a-11eb-92d1-ea1f245366ae.png)

**Comment by LonwoLonwo** [comment]
Fixed. Now "disabled" - is default value.

**Comment by Matvey16** [comment]
Verified
