### ISSUE TITLE
DBeaver doesn't work with the param "-reuseWorkspace"

### ISSUE THREAD

**Issue by AdrianoBortoloto** [dbeaver/dbeaver#12507]
#### System information: 
- Windows 10
- DBeaver 21.0.5

#### Issue:
DBeaver doesn't work with the param "-reuseWorkspace". When I removed that parameter, Dbeaver open sucessfully.

#### Steps to reproduce:
1. Create a windows shortcut with the command: "C:\path\to\install\dbeaver.exe -reuseWorkspace"
DBeaver open the starter dialog and close it in a few seconds.

2. Remove the param reuseWorkspace from the shortcut: "C:\path\to\install\dbeaver.exe"
DBeaver open normally.

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
Fixed (it was broken when we started to use the same parameter for exclusive workspace mode mark)

**Comment by uslss** [comment]
verified
