### ISSUE TITLE
Can't see function parameters

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#12518]
DBeaver 21.0.5

Informix problem + Sybase problem

![2021-05-18 13_24_09-DBeaver Enterprise 21 0 5 - addtoset2_combine](https://user-images.githubusercontent.com/45152336/118636308-392f7900-b7dd-11eb-834e-4d57804337be.png)
 
Function parameters list is empty.

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
