### ISSUE TITLE
Error on subtracting datetimes in PostgreSQL database

### ISSUE THREAD

**Issue by luccasmf** [dbeaver/dbeaver#12512]
When I try to subtract two DateTimes to get a TimeSpan as result in dBeaver I get a wrong result as you can see below

![image](https://user-images.githubusercontent.com/5990448/118578785-2aa47b80-b763-11eb-9129-6cdbf412f63c.png)

For comparison purposes, I'm sending a pgAdmin screenshot as well:

![image](https://user-images.githubusercontent.com/5990448/118578848-4c9dfe00-b763-11eb-939c-b707af7c1ab6.png)

I have made the same query from excel and from my sourcecode (.Net), in both cases the answer is just like in pgAdmin.

Can someone check it ?

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
3.10 is shown instead of 0.10
![image](https://user-images.githubusercontent.com/31996417/126695475-a4837a34-27db-49b2-a7d7-1a1b5156bf8c.png)

**Comment by uslss** [comment]
verified
