### ISSUE TITLE
Version  21.0.5.202105160657 table field name auto completion not working

### ISSUE THREAD

**Issue by ayan84** [dbeaver/dbeaver#12513]
I am using dbeaver for almost 6 month and its a beautiful utility. Yesterday it updated to version 21.0.5.202105160657 and after that it stop suggestion after table alias name. It keeps suggesting after schema name, but after table it shows no proposal when I expect field name. The database is a remote one. I attach here one screenshot for  clearing the situation.
![Screenshot 2021-05-18 104951](https://user-images.githubusercontent.com/48835769/118592145-4b9eb800-b7c7-11eb-95e2-efe044675655.png)

**Comment by LonwoLonwo** [comment]
Hello @ayan84 
Thanks for the bug report!

I see that the problem is with schema name - this is special word.
![2021-05-18 10_18_25-](https://user-images.githubusercontent.com/45152336/118608618-8e11c600-b7c2-11eb-94db-3cc39d58b133.png)

As workaround for now you can quoted schema name:
![2021-05-18 10_18_09-](https://user-images.githubusercontent.com/45152336/118608844-d29d6180-b7c2-11eb-8c04-c9d5df2c0d93.png)

**Comment by ayan84** [comment]
Thanks, it actually solves the issue.

**Comment by hrushikesh-shrikrishna-joshi** [comment]
Hey @ayan84, hope it solved your issue. If it did, please mark it as closed.

**Comment by LonwoLonwo** [comment]
Nope, sorry @hrushi8888 

I gave workaround, not fixed the problem. Using special schema name without quotes in statement - it works for PostgreSQL. So autocomplete must work in this case either.

**Comment by hrushikesh-shrikrishna-joshi** [comment]
> Nope, sorry @hrushi8888 
> 
> I gave workaround, not fixed the problem. Using special schema name without quotes in statement - it works for PostgreSQL. So autocomplete must work in this case either. 

Ohh. Ok. I didnt get that. 
I'm new here, just trying to start from somewhere.

**Comment by LonwoLonwo** [comment]
@hrushi8888 we have many unanswered discussions https://github.com/dbeaver/dbeaver/discussions :grin:

**Comment by ayan84** [comment]
Well, though adding a qoute around admin works, it has some problems also. For schema name with quotes stop giving suggestion on table name, like this,
![Screenshot 2021-05-24 112604](https://user-images.githubusercontent.com/48835769/119300654-f3fac380-bc82-11eb-96dc-0f0e3ea87767.png)
If I use it without quotes, then table name suggestion appears but field suggestion stops,
![Screenshot 2021-05-24 112748](https://user-images.githubusercontent.com/48835769/119300771-22789e80-bc83-11eb-98ac-2333506f032a.png)
I urge Dbeaver Dev team to fix these in next update.

**Comment by LonwoLonwo** [comment]
this case already here https://github.com/dbeaver/dbeaver/issues/12159

**Comment by Matvey16** [comment]
Verified
