### ISSUE TITLE
DB2 - XML Column only showing some Java Object

### ISSUE THREAD

**Issue by Magublafix** [dbeaver/dbeaver#12524]
#### System information: 
- Windows 10
- DBeaver 7.2.5

#### Connection specification:
- DB2 v11
- jdbcc4

#### Describe the problem you're observing:
XML Data is not shown correctly. Instead a Error :"Error loading text value" is shown.

#### Steps to reproduce, if exist:
Execute Query on XML column (e.g. SELECT XMLDATEN  FROM xxx.SMXML FETCH FIRST 10 ROWS ONLY )
![grafik](https://user-images.githubusercontent.com/4953529/118684503-8ffb7980-b802-11eb-9ef2-d726ae298159.png)

**Comment by kseniiaguzeeva** [comment]
Unfortunately I cannot reproduce it. 
![Screenshot 2021-05-26 at 20 30 45](https://user-images.githubusercontent.com/51405061/119705806-e0598380-be61-11eb-9922-aebf45861a9b.png)

Can you send a video, [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files) and a value example?

Please also try the latest DBeaver version https://dbeaver.io/download/.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info
