### ISSUE TITLE
Creation of a export task cannot continue if if you decide to click "Back" on transfer target type step

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12525]
#### System information: 
- Windows 10, DBeaver 21.0.5 CE, Derby Server (reproduces in postqres, sqlite too)

#### Steps to reproduce, if exist:
Open create new task -> type = export -> add table -> next -> back -> next again -> on the transfer target type step target types are disabled
![image](https://user-images.githubusercontent.com/43252954/118779102-66d6f980-b893-11eb-9605-db68c2c20925.png)
![image](https://user-images.githubusercontent.com/43252954/118779143-70606180-b893-11eb-963c-10ef3766000a.png)
![image](https://user-images.githubusercontent.com/43252954/118779388-a7cf0e00-b893-11eb-959a-cdc67e79b3fc.png)
Then you can see this 
![image](https://user-images.githubusercontent.com/43252954/118779237-866e2200-b893-11eb-9073-0c0381b2c406.png)

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
