### ISSUE TITLE
Automatic double quotes are added when importing data to the name of the new table

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12526]
#### System information: 
- Windows 10, DBeaver 21.0.5 CE, Derby Server (reproduces in Postgres)

#### Steps to reproduce, if exist:
![image](https://user-images.githubusercontent.com/43252954/118774791-e1514a80-b88e-11eb-9555-9de7802e305c.png)
And when you disactivate table name field there double quotes are added:
![image](https://user-images.githubusercontent.com/43252954/118774964-13fb4300-b88f-11eb-95d7-1a6c4c6fae48.png)
The DDL:
![image](https://user-images.githubusercontent.com/43252954/118774998-1eb5d800-b88f-11eb-8f11-02f0ac0d65fa.png)
And then it looks ugly in sql console, because you must do it in that way:
![image](https://user-images.githubusercontent.com/43252954/118775592-c29f8380-b88f-11eb-8ee1-3c6659043159.png)
It occurs even if new table nave is in uppercase
![image](https://user-images.githubusercontent.com/43252954/118780092-5f642000-b894-11eb-8e64-83af9ee720bb.png)

**Comment by ShadelessFox** [comment]
It depends on the database you're transferring to. It may be upper-case database, so the table name in lower-case is quoted to keep the case intact. Also, quoting may happen when you use keywords as an identifier.
