### ISSUE TITLE
Retrieving data from Oracle seems really slow

### ISSUE THREAD

**Issue by bobf32** [dbeaver/dbeaver#12521]
#### System information: 
- Windows 10 Enterprise 20H2
- 21.0.4
- None

#### Connection specification:
- Oracle 
- Default drivers
- No tunnels or proxies 

#### Steps to reproduce, if exist:

1. Open a SQL editor and run a SELECT query that returns at least several hundred rows. 
The first hundred rows are populated in the data grid. 

2. Scroll down in the data grid to the bottom of the results and then page down to retrieve the next hundred rows. 
The next hundred rows are returned in about 5 seconds. 

3. Repeat step 2.
Each additional 100 rows fetched adds at least a couple of seconds to the retrieval time.

I repeated the query from 1. and then issued a Fetch all rows. It took nearly 21 seconds to retrieve all 873 rows of a two column table.

Essentially retrieving rows from Oracle seems really slow.

Just tried this on a MariaDB database and each additional 100 rows fetched seems to take just over 1 second consistently.

**Comment by uslss** [comment]
@bobf32 you can try to change some settings related to performance in Connection configuration and check if it helps or not.
![image](https://user-images.githubusercontent.com/31996417/118641240-92e67200-b7e2-11eb-9ee0-f0f1b2362643.png)

**Comment by bobf32** [comment]
@uslss I tried enabling each of the four options individually and none made any difference.

**Comment by p91paul** [comment]
is it a simple select * from table or a more complex query? 
Also, does the table contain CLOB columns?

**Comment by bobf32** [comment]
@p91paul Is straight select *. No clobs.

**Comment by p91paul** [comment]
@bobf32 are your oracle and mariadb instances on the same network?
I constantly use Oracle and never noticed anything like this.

**Comment by bobf32** [comment]
@p91paul Not my area of expertise, but I would say ultimately yes, although the two databases are in different countries. Oracle is UK, MariaDB mainland Europe.

**Comment by p91paul** [comment]
What I was suggesting is that maybe your connection to Oracle has an higher network latency than the one to MariaDb. However seeing they are both remote that might not be the case.

**Comment by kseniiaguzeeva** [comment]
Seems to be a network configuration specific issue. Please check it with your system administrator.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info
