### ISSUE TITLE
output window cannot be moved to lower half of screen

### ISSUE THREAD

**Issue by WellspringCS** [dbeaver/dbeaver#12534]
#### System information: 
- Linux Ubuntu 18.04
- 21.0.5

#### Describe the problem you're observing:
Output tab used to open in lower half of screen. As of upgrade it opens to right and cannot be moved to lower half, where it used to be.
![image](https://user-images.githubusercontent.com/34347780/118879540-761b6e80-b8b6-11eb-8c1f-f80ba3949833.png)

**Comment by kseniiaguzeeva** [comment]
In one of the previous releases, we moved it to the right side. You can minimize it and turn off auto-open when new messages appear.
![Screenshot 2021-05-20 at 11 28 51](https://user-images.githubusercontent.com/51405061/118945938-9c94e480-b95e-11eb-962d-1d6c293b17b5.png)

**Comment by WellspringCS** [comment]
I love your tool, and appreciate your taking time to answer. However, I want the output. I want it visible. But I liked it in the bottom half, where it was before.

I gather the current state is intended behavior (obviously) and also (less obviously) that there's no functionality provided for users to return it to where it was in earlier releases. Thanks for the info.

My vote is to make that dialog movable. I very much prefer the old way, where this functionality is concerned.

**Comment by kseniiaguzeeva** [comment]
We will add an option to place Output under SQL Editor field as before. It will be disabled by default. I'm glad you find the application useful, thank you)

**Comment by WellspringCS** [comment]
I think others will
appreciate this, too.
The benefit to it being
in the bottom half is
that longer comments
are not wrapped tightly
as I have done in
exaggerated fashion here.
(It's obviously not that
bad, but json objects can
be huge, and reading them
in the right panel can feel
like this. :)

**Comment by jmccay-work** [comment]
I would like to also request this feature.  I work with large tables in an old schema on Informix, and there is not enough room having the tab on the side.  There is just more room where it was before.

BTW,  great product and keep up the great work!  I couldn't work with Informix without using this program most of the time!

**Comment by uslss** [comment]
implemented in the scope of #11533 .
Will be available in 21.1.3
