### ISSUE TITLE
SQL editor - navigating through tabs breaks in rightmost tab

### ISSUE THREAD

**Issue by taf1-cornell-edu** [dbeaver/dbeaver#12532]
#### System information: 
- Operating system (distribution) and version  
      Windows 10 Enterprise version 1909
- DBeaver version
      DBeaver Community Version 21.0.5.202105160657
- Java version 
- Additional extensions

#### Describe the problem you're observing:
While navigating through open tabs using ctrl+tab to go right  and ctrl+shift+tab to go left,
if the rightmost tab is a SQL editor, and you type ctrl+tab, ctrl+shift+tab no longer goes left and the user remains stuck on the rightmost tab.

#### Steps to reproduce, if exist:
Connect to a db and open 3 new SQL editors.  
-->active is rightmost
ctrl+shift+tab to go left
--> active is center
ctrl+shift+tab to go left
--> active is leftmost
ctrl+tab to go right
--> active is center
ctrl+tab to go right
--> active is right
ctrl+tab to go right (although there are no tabs further to the right)
--> active is still right
ctrl+shift+tab to go left
--> no longer works.

o  Issue does not happen on at least some other types of tabs like a tab for a table 

#### Include any warning/errors/backtraces from the logs

!ENTRY org.eclipse.jface 2 0 2021-05-19 11:27:01.190
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2021-05-19 11:27:01.190
!MESSAGE A conflict occurred for CTRL+BS:
Binding(CTRL+BS,
	ParameterizedCommand(Command(org.eclipse.ui.edit.text.deletePreviousWord,Delete Previous Word,
		Delete the previous word,
		Category(org.eclipse.ui.category.textEditor,Text Editing,Text Editing Commands,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@1f40bb80,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(CTRL+BS,
	ParameterizedCommand(Command(org.jkiss.dbeaver.core.resultset.cell.setDefault,Set to default,
		Set cell to default value,
		Category(org.jkiss.dbeaver.core.rs,Result Set,Result Set Commands,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@c42ee90,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.jkiss.dbeaver.ui.context.resultset.focused,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2021-05-19 11:27:01.190
!MESSAGE A conflict occurred for SHIFT+CR:
Binding(SHIFT+CR,
	ParameterizedCommand(Command(org.eclipse.ui.edit.text.smartEnter,Insert Line Below Current Line,
		Adds a new line below the current line,
		Category(org.eclipse.ui.category.textEditor,Text Editing,Text Editing Commands,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@70c2a046,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(SHIFT+CR,
	ParameterizedCommand(Command(org.jkiss.dbeaver.core.resultset.row.edit,Edit cell,
		Edit cell value in separate dialog/editor,
		Category(org.jkiss.dbeaver.core.rs,Result Set,Result Set Commands,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3803bc1a,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.jkiss.dbeaver.ui.context.resultset.focused,,,system)

**Comment by Matvey16** [comment]
Thank you for the report. I reproduced this issue and we will look into it.

**Comment by Matvey16** [comment]
Verified
Additional enhancement ticket opened #13486
