### ISSUE TITLE
Change codepage in sql editor - no cp1251 in "project explorer view->Resource->Text file encoding"

### ISSUE THREAD

**Issue by Delaland** [dbeaver/dbeaver#12538]
#### System information: 
- MacOS Big Sur 11.3.1
- DBeaver 21.0.5

#### Describe the problem you're observing:
There is no cp1251 in "project explorer view->Resource->Text file encoding"
![image](https://user-images.githubusercontent.com/84506209/118973703-9f9dce00-b97a-11eb-94ec-ac88a4132a1a.png)

Can't open Win-1251 sql-files (in Windows there is no problem).

**Comment by Matvey16** [comment]
Have you tried to type the encoding yourself? In this field instead of picking one of the options you can type encoding yourself.

**Comment by uslss** [comment]
there is no update for a long time.
if the issue is still actual for you - feel free to reopen it
