### ISSUE TITLE
The result tab is collapsed after the query execution

### ISSUE THREAD

**Issue by tati-kru** [dbeaver/dbeaver#12533]
1. Open any script in the SQL-editor or create a new one.
2. Execute query
3. Collapse the Results area by arrows
4. Close the script
5. Open SQL editor once again and execute query.

The Results are hidden and cannot be expanded in one click.

**Comment by serge-rider** [comment]
Fixed.
Now we will restore original sash size if one of sash controls is too narrow.

**Comment by Matvey16** [comment]
Verified
