### ISSUE TITLE
Oracle MView refresh does not work: class org.jkiss.dbeaver.ext.oracle.model.OracleTable cannot be cast to class org.jkiss.dbeaver.ext.oracle.model.OracleMaterializedView

### ISSUE THREAD

**Issue by gavvvr** [dbeaver/dbeaver#12537]
#### System information: 
- Operating system (distribution) and version: Mac OS Catalina 10.15.7
- DBeaver version: 21.0.5.202105160657 (Runtime: 11.0.8+10)
- Additional extensions: None, pure installation

#### Connection specification:
- Database name and version: Oracle 12.1.0.2.0
- Driver name: ojdbc8:12.2.0.1 (I guess this version was bundled or downloaded from MVN central by default)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

The following error on attempt to refresh a view:

![image](https://user-images.githubusercontent.com/1719646/118962499-1e403e80-b96e-11eb-8246-5cca647c9296.png)

#### Steps to reproduce, if exist:

Right-click materialized view -> Tools -> Refresh Materialized view -> click 'Start'

#### Include any warning/errors/backtraces from the logs

Pasting error details from the screenshot:

```
Execute tool 'Refresh materialized view'
	Process [SCHEMA_NAME.MVIEW_NAME]
Process error
class org.jkiss.dbeaver.ext.oracle.model.OracleTable cannot be cast to class org.jkiss.dbeaver.ext.oracle.model.OracleMaterializedView (org.jkiss.dbeaver.ext.oracle.model.OracleTable and org.jkiss.dbeaver.ext.oracle.model.OracleMaterializedView are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @419ece7a)
Tool execution finished
```

I also found this problem in comments to other issues, but those issues are already resolved:

- https://github.com/dbeaver/dbeaver/issues/9431#issuecomment-669954813
- https://github.com/dbeaver/dbeaver/issues/8920#issuecomment-645282848

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. Could you please send mview DDL example and logs completely https://github.com/dbeaver/dbeaver/wiki/Log-files?

**Comment by gavvvr** [comment]
@kseniiaguzeeva I was able to reproduce it with the following minimal setup:

#### 1. Get Oracle db

- get this code: https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/dockerfiles
- Download [Oracle 11 xe zip](https://www.oracle.com/database/technologies/xe-prior-releases.html)
- put downloaded zip to `dockerfiles/11.2.0.2` folder
- build the image with `chmod +x buildContainerImage.sh && ./buildContainerImage.sh -v 11.2.0.2 -x`
- run it `docker run --rm -it --name oracle --shm-size="2g" -p9090:8080 -p1521:1521 -e ORACLE_PWD=oracle oracle/database:11.2.0.2-xe`

#### 2. Create a new dbeaver connection

- Database: xe
- Password: the one specified in `$ORACLE_PWD`
- General -> Customize -> Show system objects

#### 3. Create MView

```sql
CREATE MATERIALIZED VIEW MV_DBEAVER_PROBLEM(BANNER)
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND USING TRUSTED CONSTRAINTS
DISABLE QUERY REWRITE
AS
select BANNER from v$version;
```

#### 4. Reproduce the problem

Right-click just created view -> Tools -> Refresh Materialized view -> click 'Start'

**Comment by kseniiaguzeeva** [comment]
Thank you! But I also need logs https://github.com/dbeaver/dbeaver/wiki/Log-files. Is it possible to send them?

**Comment by gavvvr** [comment]
Reproduced again with my instructions above (on a Linux Mint machine this time to get clear logs).
There was only a single log-file in **~/.local/share/DBeaverData/workspace6/.metadata**: 
- [dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/6555469/dbeaver-debug.log)

**Comment by kseniiaguzeeva** [comment]
Thank you for the details. We will try to reproduce it and fix.

**Comment by uslss** [comment]
@gavvvr still cannot reproduce an issue.
Could you check if it is still actual for you against the recent version?

**Comment by gavvvr** [comment]
@uslss 
DBeaver: Version 21.1.3.202107181810
Oracle 11 XE in Docker containerized with my recipe [above](https://github.com/dbeaver/dbeaver/issues/12537#issuecomment-845522372)

Still the same problem

**Comment by flambchap** [comment]
Hi @gavvvr. I've tried to reproduce the issue using the official Oracle container for 12c EE, with no success. I suspect that the issue is 11c-specific. Unfortunately, the link to Oracle 11 XE in your recipe above is broken, and I didn't find anything useful on the Oracle website. I'm wondering if could provide some assistance with that. Thank you.

**Comment by gavvvr** [comment]
Hi @akilovich,
Yes, unfortunately Oracle website does not provide Oracle 11 XE rpm anymore.
But you can take Oracle 11 rpm from here: https://stackoverflow.com/a/61069731/3581539

**Comment by flambchap** [comment]
Thank you, Kirill. I've managed to get up and running an 11g instance, but still haven't found success in reproducing the issue. The only idea I have in mind at the moment is that it is somehow a mac-specific issue, although I find it to be very unlikely :(. I'll try to figure something out and will keep you updated.

**Comment by gavvvr** [comment]
@akilovich , I already reported above, that the problem was also reproducible on Linux. So far I only did not cover Windows :)

**Comment by flambchap** [comment]
Have you tried to reset UI settings and worspace state? If now, please do that to see if it helps.
![Screenshot 2021-08-11 095327](https://user-images.githubusercontent.com/26031301/128983085-695a521a-1f51-49e2-a001-41a320d3e5ce.png)
(the options you need are at the very bottom).

If that doesn't help, then I believe there's a small but crutial detail missing in your recipe above. So I want you to record a screencast where you reproduce the issue, starting from point number 2. Thanks a lot.

**Comment by gavvvr** [comment]
No, resetting of both did not help.
I will also try a Windows version soon and will make a screencast.

Btw I noticed you use the Ultimate version, I use the Community one

**Comment by gavvvr** [comment]
Same on Windows (fresh Dbeaver CE 21.1.4 + Oracle 11 build with my instructions above):
![image](https://user-images.githubusercontent.com/1719646/129014965-5f12d264-a793-40e5-9dc1-22057e2dd02f.png)

Will record and attach a short screencast later

**Comment by flambchap** [comment]
Successfully reproduced the issue on Oracle 12c EE.

**Comment by flambchap** [comment]
The issue is caused by the fact that there is a duplicate table in the navigator with the same name. This table doesn't exist in the database though.

**Comment by ghiki** [comment]
Hello, any advancements on this? I have the same problem when refreshing MVIEW from GUI (and yes, I have mview with same name as a table). If I "CALL" directly to "DBMS_MVIEW.REFRESH" from SQL it works ok

**Comment by flambchap** [comment]
Hello @ghiki. Unfortunately, there have been no advancements so far. I've brought our PM's attention to this ticket.
