### ISSUE TITLE
Strange gibberish in tabs

### ISSUE THREAD

**Issue by root237** [dbeaver/dbeaver#12540]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro 19042.985
- DBeaver version: 21.0.5.202105160657
- Java version: JDK 14 and JRE 1.8.0_231
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

There are certain UI elements, namely the tabs in the sql viewer and above the database browser, that appear to be displaying gibberish with inconsistent letter spacing. Any insight into this? It's not feature breaking but it can sometimes cause a slip trying to remember which tab I need.

**Comment by kseniiaguzeeva** [comment]
Could you please send a screenshot or video?

**Comment by uslss** [comment]
there is no update on issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
