### ISSUE TITLE
UI not updated after table rename

### ISSUE THREAD

**Issue by meglio** [dbeaver/dbeaver#12547]
<img width="368" alt="table_rename_no_ui_updates" src="https://user-images.githubusercontent.com/282177/119084489-0ab1d800-ba41-11eb-8e11-419271eea81d.png">

#### System information: 
- Operating system (distribution) and version Mac OS Big Sur
- DBeaver version Version 21.0.5.202105160657

#### Connection specification:
- Database name and version PostgreSQL 13 

#### Steps to reproduce

1. Create a few tables with a few columns
2. Close all windows / tabs / editors
3. Open one of the tables you just created.
4. Rename  the table, click Save, click Commit
5. Now the "Table Name" input contains the updated table name, but the tab title AND the corresponding item in the tables tree stays non-updated.
6. Not only does UI becomes in an inconsistent state, it also won't you continue editing table schema. The only workaround is to 1) close the tab, 2) refresh the schema in the tree (F5), and 3) reopen the table schema editor tab.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. Could you please send a video?

**Comment by uslss** [comment]
there is no update for a long time.
if the issue is still actual for you - feel free to reopen it
