### ISSUE TITLE
DB Full-Text search hangs when selecting schema with many tables

### ISSUE THREAD

**Issue by dkornacki-cutco** [dbeaver/dbeaver#12544]
#### System information: 
- Windows 10 Pro 20H2
- DBeaver Version 21.0.5.202105160657

#### Connection specification:
- Database: DB2 for IBM i release 7.3
- Driver name: DB2 iSeries/AS 400

#### Describe the problem you're observing:
DBeaver hangs indefinitely when setting up DB Full-Text search. A cancel prompt displays with "Progress Information (Not Responding)", "Load sources tree." I've noticed this only happens when selecting certain schemas.

#### Steps to reproduce, if exist:
1. Search -> DB Full-Text
2. Expand schemas
3. Select a problem schema (checkbox selection)

#### Include any warning/errors/backtraces from the logs
There is nothing in log.

**Comment by kseniiaguzeeva** [comment]
Could you please provide me with more details: do schemas haму a spesific size, data?
Could you please also look at [Query manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager)? What quieries are executed?

**Comment by dkornacki-cutco** [comment]
I looked more into this. I let it process for 5-10 minutes and it went through. The schema has > 7000 tables so it's relatively large.

The UI is locked up the whole time, so pressing cancel does nothing.

There is nothing in Query manager related to this.

**Comment by kseniiaguzeeva** [comment]
It definitely has to work faster. Thank you for the bug report.

**Comment by LonwoLonwo** [comment]
Hello @dkornacki-cutco 

Can you please check the newest DBeaver version? We added some support for better DB2i schemas and table loading.

If it didn't help, please change the number of fetch elements in the Preferences -> User Interface -> Navigator.

![2022-05-25 18_41_31-DBeaver Ultimate 22 0 3 - TABLES_S](https://user-images.githubusercontent.com/45152336/170302991-ad68baf0-f475-4540-b711-48b3c20327e4.png)

Maybe this can help?

Also, did this issue only appears in the "Full-text search"? What about Navigator Tree? It hangs too on expand?

**Comment by dkornacki-cutco** [comment]
I tried it again with 22.0.5 but it still goes unresponsive for several minutes. Just to clarify, expanding the schema works fine and it's very quick. It's only when I select the checkbox (of the schema) for search that the problem happens.

Navigator Tree also expands quickly with no issues. It's just that checkbox for search that's an issue.

**Comment by LonwoLonwo** [comment]
Ok, thanks for the quick answer.

**Comment by LonwoLonwo** [comment]
Also, this is not db2i specific issue.
