### ISSUE TITLE
Questions about setting binding parameters

### ISSUE THREAD

**Issue by xiaozhute** [dbeaver/dbeaver#12550]
#### System information: 
- macOS 10.15.7
- DBeaver version : 21.0.4.202105021514
- Additional extensions

#### Connection specification:
- MySQL 5.7.32
- do not use tunnels or proxies (SSH, SOCKS, etc)

#### Steps to reproduce, if exist:
create table ta(id int auto_increment primary key ,va varchar(20));
insert into ta(va) values('aaa${aa}');
insert into ta(va) values('bbb${bb}');

The binding parameters window will pop up every time，How can I set it so that it doesn't pop up ？

**Comment by FedorovaDarya** [comment]
Do you talk about "hints for next word" pop ups? In this case if it interferes you can go Window -> preferences -> and uncheck that    option
![image](https://user-images.githubusercontent.com/43252954/119127985-b9ecb000-ba3d-11eb-82b2-f49fe7a51300.png)

**Comment by LonwoLonwo** [comment]
You can read more about parameter bindings here: https://github.com/dbeaver/dbeaver/wiki/SQL-Execution#dynamic-parameter-bindings

You can disable it in Preferences:
![2021-05-21 14_57_03-Preferences](https://user-images.githubusercontent.com/45152336/119133684-d9d3a200-ba44-11eb-9ac4-4984a63d75f5.png)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info
