### ISSUE TITLE
Show alert before loading column possible values in data filter

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#12554]
We need to shows warning about potentially expensive operation.

We use  `SELECT DISTINCT/GROUP BY` query to read values. It may be super-expensive in case of big table and unindexed column.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/121541039-9cdd4880-ca0f-11eb-8dcd-1f6e6dd9308a.png)

**Comment by uslss** [comment]
verified
