### ISSUE TITLE
Database Restore failed in Windows 10 64 bit

### ISSUE THREAD

**Issue by tomnguyen0811** [dbeaver/dbeaver#12565]
#### System information: 
- Operating system (distribution) and version: Windows 10 64 bit (version: 20H2)
- DBeaver version: 21.0.5.202105160657
- Java version: JDK 11
- Additional extensions

#### Connection specification:
- Database name and version: MariaDB 10.5.10
- Driver name: MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Restore database always has errors.
```
Error executing process
  Cannot run program "C:\Users\Tom\AppData\Roaming\DBeaverData\drivers\clients\mysql\win\mysql.exe" (in directory "C:\Users\Tom\AppData\Roaming\DBeaverData\drivers\clients\mysql\win"): CreateProcess error=193, %1 is not a valid Win32 application
  Cannot run program "C:\Users\Tom\AppData\Roaming\DBeaverData\drivers\clients\mysql\win\mysql.exe" (in directory "C:\Users\Tom\AppData\Roaming\DBeaverData\drivers\clients\mysql\win"): CreateProcess error=193, %1 is not a valid Win32 application
    CreateProcess error=193, %1 is not a valid Win32 application
    CreateProcess error=193, %1 is not a valid Win32 application
```

#### Steps to reproduce, if exist:
1. Backup a database by tools dump: Right-click on the database → Tools → Dump Database → example.sql
2. Restore another database by tools restore: Right-click on the database → Tools → Restore Database → Choose the example.sql script
3. A window to show errors

#### Include any warning/errors/backtraces from the logs
![dbeaver-restore-error](https://user-images.githubusercontent.com/66505105/119252361-fe12b880-bbd5-11eb-822a-234f7fcc4c60.PNG)

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. Please try to select Local client before performing Restore procedure.
![dbeaver_vxWQqJysLz](https://user-images.githubusercontent.com/51405061/119305298-3a472700-bc71-11eb-902a-e9b5c653f38d.png)

Could you also send file example to restore and log files completely https://github.com/dbeaver/dbeaver/wiki/Log-files?

**Comment by tomnguyen0811** [comment]
Hi @kseniiaguzeeva, this is the log file which is created after restore failed: [test_restore_error_2021-05-26.log](https://github.com/dbeaver/dbeaver/files/6545752/test_restore_error_2021-05-26.log)

I can't upload the example SQL file. So I paste it in right here:
```
-- MySQL dump 10.13  Distrib 5.5.62, for Win64 (AMD64)
--
-- Host: localhost    Database: test_backup
-- ------------------------------------------------------
-- Server version	5.5.5-10.5.10-MariaDB

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `user`
--

DROP TABLE IF EXISTS `user`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  `age` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `user`
--

LOCK TABLES `user` WRITE;
/*!40000 ALTER TABLE `user` DISABLE KEYS */;
INSERT INTO `user` VALUES (1,'David',30),(2,'John',28);
/*!40000 ALTER TABLE `user` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping routines for database 'test_backup'
--
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2021-05-26 16:50:39
```
If you need any information, please let me know. Thanks for your support.

**Comment by kseniiaguzeeva** [comment]
Seems files were not downloaded properly. Could you delete them (you can see the way to the files in your error message) and then perform backup/restore? The files will be downloaded again by DBeaver.

Security policy in your company can be another reason. It can restrict to run some .exe files. Could you go to the file directory and try to run .exe file manually?

**Comment by tomnguyen0811** [comment]
> Seems files were not downloaded properly. Could you delete them (you can see the way to the files in your error message) and then perform backup/restore? The files will be downloaded again by DBeaver.
> 
> Security policy in your company can be another reason. It can restrict to run some .exe files. Could you go to the file directory and try to run .exe file manually?

Hi @kseniiaguzeeva, you are right.
I went to the file directory and try to run .exe file manually, it can't run.
I was deleted the `C:\Users\Tom\AppData\Roaming\DBeaverData\drivers\clients\mysql\win\mysql.exe` file and ran restore again.
It's working.
Thanks for your support.

**Comment by kseniiaguzeeva** [comment]
Nice to hear)

**Comment by renneresser** [comment]
> Não consigo reproduzi-lo. Tente selecionar Cliente local antes de executar o procedimento de restauração. ![dbeaver_vxWQqJysLz](https://user-images.githubusercontent.com/51405061/119305298-3a472700-bc71-11eb-902a-e9b5c653f38d.png)
> 
> Você também poderia enviar um exemplo de arquivo para restaurar e registrar arquivos completamente https://github.com/dbeaver/dbeaver/wiki/Log-files ?

Esta solução resolveu o meu caso .. de escolhendo o cliente escolhendo o Binário MySql 5 Binari

**Comment by TheRakeshMishra** [comment]
> I cannot reproduce it. Please try to select Local client before performing Restore procedure. ![dbeaver_vxWQqJysLz](https://user-images.githubusercontent.com/51405061/119305298-3a472700-bc71-11eb-902a-e9b5c653f38d.png)
> 
> Could you also send file example to restore and log files completely https://github.com/dbeaver/dbeaver/wiki/Log-files?

That worked for me, I dont have local client before. Thanks

**Comment by Kiyotaka327** [comment]
> #### System information:
> * Operating system (distribution) and version: Windows 10 64 bit (version: 20H2)
> * DBeaver version: 21.0.5.202105160657
> * Java version: JDK 11
> * Additional extensions
> 
> #### Connection specification:
> * Database name and version: MariaDB 10.5.10
> * Driver name: MariaDB
> * Do you use tunnels or proxies (SSH, SOCKS, etc)? No
> 
> #### Describe the problem you're observing:
> Restore database always has errors.
> 
> ```
> Error executing process
>   Cannot run program "C:\Users\Tom\AppData\Roaming\DBeaverData\drivers\clients\mysql\win\mysql.exe" (in directory "C:\Users\Tom\AppData\Roaming\DBeaverData\drivers\clients\mysql\win"): CreateProcess error=193, %1 is not a valid Win32 application
>   Cannot run program "C:\Users\Tom\AppData\Roaming\DBeaverData\drivers\clients\mysql\win\mysql.exe" (in directory "C:\Users\Tom\AppData\Roaming\DBeaverData\drivers\clients\mysql\win"): CreateProcess error=193, %1 is not a valid Win32 application
>     CreateProcess error=193, %1 is not a valid Win32 application
>     CreateProcess error=193, %1 is not a valid Win32 application
> ```
> 
> #### Steps to reproduce, if exist:
> 1. Backup a database by tools dump: Right-click on the database → Tools → Dump Database → example.sql
> 2. Restore another database by tools restore: Right-click on the database → Tools → Restore Database → Choose the example.sql script
> 3. A window to show errors
> 
> #### Include any warning/errors/backtraces from the logs
> ![dbeaver-restore-error](https://user-images.githubusercontent.com/66505105/119252361-fe12b880-bbd5-11eb-822a-234f7fcc4c60.PNG)

I fixed this error by following this step . Unistall Dbeaver . Go to C:\Users\(your computer username)\AppData\Roaming\    delete dbever folder here . Now Install again Dbeaver but this time before you connect to mysql test your connection first. This will dowload some jdk . or java file something to your dbeaver . After you test the connection and its ok . Connect your mysql now to dbeaver. After this step you should fine in restoring and dumping mysql database.
