### ISSUE TITLE
Every time I open dbeaver, macOS will ask me if I accept the incoming network connection?

### ISSUE THREAD

**Issue by ykqmain** [dbeaver/dbeaver#12563]
#### System information: 
- Operating system (distribution) and version: macOS 11.3.1, MacBook Pro (13-inch, **M1**, 2020)
- DBeaver version: 21.0.5.202105160657
- Additional extensions: Nothing

#### Connection specification:
- Database name and version: **mysql-8.0.25-macos11-x86_64**
- Driver name: The default of MySQL8.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **No**

#### Describe the problem you're observing:
Every time I open dbeaver, macOS will ask me if I accept the incoming network connection?

macOS prompt panel display:
Clicking `reject` may limit the behavior of the application. This setting can be changed in `the firewall panel` of `the security and privacy preferences`.

But I click `allow` every time, there will still be this prompt box every time I start dbeaver.

#### Steps to reproduce, if exist:
Nothing to do, just click dbeaver to start it, 100% reproduction.

#### Include any warning/errors/backtraces from the logs
Nothing

**Comment by kseniiaguzeeva** [comment]
We are waiting for September to support M1. Your issue can be solved after it. The similar ticket https://github.com/dbeaver/dbeaver/issues/12441

**Comment by uslss** [comment]
There has been no update on the issue for a long time. 
If it is still actual - feel free to reopen it.
