### ISSUE TITLE
Tooltip does not show all info

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#12562]
v21.0.3

![image](https://user-images.githubusercontent.com/799021/119218374-903c9300-bae8-11eb-8ec1-bd55f56849ad.png)

**Comment by Matvey16** [comment]
Hello. Thank you for the report. What OS do you use? It looks like the bottom of the text is hidden because of the small size of the window. You can try to resize it by dragging its borders up/down and left/right. This parameter will also be saved for all your next sessions.

**Comment by KES777** [comment]
Linux Mint v19.3, Cinnamon

**Comment by Matvey16** [comment]
Have you tried resizing this window?

**Comment by KES777** [comment]
resizing works

**Comment by KES777** [comment]
This is not common that tips need to resize. This should be a short message to read it quick.

So I even do not try it
