### ISSUE TITLE
Boolean values are trimmed and shifted in Metadata Editor/Data transfer dialog

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12566]
#### System information: 
- Operating system (distribution) and version: **any**
- DBeaver version 21.0.5
#### Steps to reproduce, if exist:
Open a column editor or a data transfer dialog and click a checkbox

**Expected**: the checkbox remains on its place
**Actual result**: the checkbox "jumps" to the right

1. Set focus on boolean property, observe that text is shifted while focused:
<kbd><img src="https://user-images.githubusercontent.com/35821147/136658240-ab9e3851-712b-4b2c-be95-2c328164ecc4.gif"></kbd>
1. Change value of textual boolean property, observe that text is trimmed:
<kbd><img src="https://user-images.githubusercontent.com/35821147/136658260-3d210d25-a31c-4f91-b0b7-2c7c1617f502.gif"></kbd>

**Comment by Matvey16** [comment]
Verified
