### ISSUE TITLE
How to choose non-continuous multi-select scripts to execute

### ISSUE THREAD

**Issue by tianmingxing** [dbeaver/dbeaver#12568]
At present, only single-line SQL execution can be selected, but if you want to select multiple non-contiguous rows for execution, is there a way to achieve this requirement?

**Comment by Matvey16** [comment]
Hello. Are you talking about execution of multiple statements from SQL Editor? There is a separate button for this

![2021-05-24_11h34_26](https://user-images.githubusercontent.com/82543000/119320818-a67f5600-bc84-11eb-9989-4cee20d83de2.png)

**Comment by tianmingxing** [comment]
I want to select discontinuous sql statements in the code editor, and then get multiple query result windows, so that it is convenient to compare query results. Currently I need to execute them one by one.

**Comment by Matvey16** [comment]
Thank you for this feature request. We will look if it can be done.

**Comment by Matvey16** [comment]
Hello again. There is no way for now to implement execution of more than one statement , but not all of them. In the SQL editor there are 4 execution buttons. First two are for single statement, third and forth are for the whole script. If your script has multiple select queries, you can click a button to execute all of them and they will be opened in separate tabs.

![2021-06-03_15h13_08](https://user-images.githubusercontent.com/82543000/120643223-8f0f4c80-c47e-11eb-960d-2a1392ede52b.gif)

Please ask to reopen if you would like to offer another solution.
