### ISSUE TITLE
App startup time reduce

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#12564]
We need to reduce application startup time.
Especially the first launch after version upgrade.

Currently it spends a lot of time extracting resources from OSGI bundles. This is super slow on Windows with its antivirus policy.
We need to extract resources on demand (whenever it is possible).

**Comment by serge-rider** [comment]
Icons are now extracted on demand. Redundant jar files removed.

**Comment by Matvey16** [comment]
Verified

**Comment by BIGNIKi** [comment]
Startup time still is insanely slow on windows😭
(It took 52 seconds last time)

**Comment by serge-rider** [comment]
Most likely it is because of Windows Defender.

You can add DBeaver to inclusions here: 

<img width="1297" height="639" alt="Image" src="https://github.com/user-attachments/assets/05d5268d-eac5-498a-89d6-8f945a8ad47b" />

Also the first launch is usually significantly longer than consequent ones.

Generally Community version should launch in 3-5 seconds on average Windows machine.
For PRO versions it is 5-10 seconds.

**Comment by BIGNIKi** [comment]
@serge-rider Thank you for the answer.
Microsoft defender is off on my computer.
<img width="526" height="157" alt="Image" src="https://github.com/user-attachments/assets/1da39933-b577-4d04-92ba-e06c97894db7" />

<img width="472" height="105" alt="Image" src="https://github.com/user-attachments/assets/c6bacc99-17a8-4602-814e-bd29d59c9bca" />

Could other anti-virus application affect on it? I am using kaspersky.
