### ISSUE TITLE
Probable regression, Postgresql sequence DDL uses Cache 0 and this is not a valid value

### ISSUE THREAD

**Issue by igorbga** [dbeaver/dbeaver#12569]
#### System information: 
- Ubuntu 18.04
- DBeaver CE 21.0.5
- Additional extensions: Non AFAIK

#### Connection specification:
- Database name and version: PostgreSQL 9.6
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
The DDL suggested for a sequence sets optional attribute CACHE to 0 which is not valid in PostgreSQL.
This was reported and supposedly fixed a couple of years ago in #5156 .

#### Steps to reproduce, if exist:
Create a sequence in a PostgreSQL DB and check the DDL that DBeaver shows.

**Comment by ShadelessFox** [comment]
Hello @igorbga,

Thanks for the report. The problem was occurred in #11177.

**Comment by ShadelessFox** [comment]
The issue will be fixed in the scope of this ticket. Keep it opened for now.

**Comment by igorbga** [comment]
A ok, sorry, thought your commit already solved it. Thanks

**Comment by ShadelessFox** [comment]
The fix should be tested first in order to be closed :)

**Comment by kseniiaguzeeva** [comment]
verified
