### ISSUE TITLE
refresh of screen

### ISSUE THREAD

**Issue by icegood** [dbeaver/dbeaver#12573]
#### System information: 
- Operating system (distribution) and version : 5.11.0-17-generic #18-Ubuntu SMP Thu May 6 20:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- DBeaver version:  21.0.5.202105160657
- Additional extensions

#### Connection specification:
- Database name and version: sqlite3
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no 

#### Describe the problem you're observing:

Screen is blinking while moving cursor. See video.
https://drive.google.com/file/d/1xvHvPouTxuQCdCJHp2qqGetpg49_VN7D/view?usp=sharing

**Comment by kseniiaguzeeva** [comment]
Could you please try ibus? Here is the similar ticket https://github.com/dbeaver/dbeaver/issues/8694. Feel free to ask to reopen the ticket if the issue still persists.
