### ISSUE TITLE
Inconsistent behavior of some checkboxes on the PostgreSQL connection configuration page

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#12576]
On the aforementioned page, we have 3 checkboxes: a) Show all databases; b) Show template databases; c) Show databases not available for connection. If the first one is not set, the latter two are not applicable. However, if we check one of them, e.g. the second one, and then we uncheck the first one, checkbox b is still set (but grayed). We also have the same checkboxes in the global preferences, and there we can even apply checkboxes b and c without checking button a.

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
