### ISSUE TITLE
Google Cloud support

### ISSUE THREAD

**Issue by anborg** [dbeaver/dbeaver#12581]
GOOGLE_APPLICATION_CREDENTIALS - must not be in environment variable.  Reason: Users may be working on many different "gcp projects".

![image](https://user-images.githubusercontent.com/56970398/119435937-32c36480-bce9-11eb-8df3-10c4d4e7f04b.png)

Adding that property in driver-properties did not help. 

![image](https://user-images.githubusercontent.com/56970398/119436090-8930a300-bce9-11eb-9968-7f86afd4ee20.png)

Short term: Perhaps could be added in driver props

Long term:

Perhaps the cloud-creds, cloud-ssl-certs  for all/different cloud projects could be in one config screen, or  tab(s) for each cloud provider?

 and then specific-creds can be referenced in a  drop down in  db-connection, for aws-oracle/gcp-postgres/gcp-mysql/gcp-mssql/azure-mssql etc.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. We will implement Google Cloud Support in Enterprise Edition.

**Comment by morgan-zylotech** [comment]
A potential workaround using the GCP Cloud SQL Proxy

1. Right click in the Database Navigator panel. Click Create then select Connection


1. Select the PostgreSQL icon and click the Next button


1. Enter the database, username and password for the database you are working with
![dbeaver_1](https://user-images.githubusercontent.com/70210123/135903026-42bff48c-2494-4102-a9e7-04413dff4ebb.png)


1. As we will be taking advantage of Cloud SQL Proxy, we can choose any port we would like to work with locally and Cloud SQL Proxy will create proxy the connection to the correct port in the cloud.
![dbeaver_3](https://user-images.githubusercontent.com/70210123/135903228-d2725966-b1ff-46f6-b9b9-d22169ab0518.png)


1. Reserve the default PostgreSQL port (5432) for your local PostgreSQL instance

1. Click the Connection details (name, type, …) button. Edit the name of the connection to represent the database you are working with. Add select the correct Connection type for the environment you are working in


1. Click the Shell Commands link, then check the Before Connect checkbox

1. Paste the following script into the Command text area
      ```shell
      /usr/bin/bash -c "${home}/./cloud_sql_proxy -instances=<YOUR_INSTACE_NAME>=tcp:${port}"
      ```

1. Check the Wait for process to finish (ms) checkbox. Add 10000 to the input

1. Click the Ok button

1. Click the Back button

1. Select the PostgreSQL tab and Click Show all databases checkbox
![dbeaver_2](https://user-images.githubusercontent.com/70210123/135903503-e7102e4d-3f1d-444a-91c6-390aba27d416.png)


1. Click Test Connection button
![dbeaver_5](https://user-images.githubusercontent.com/70210123/135903548-9af3d569-5801-4232-87b4-4dd059adbf31.png)

1. Make adjustments as necessary

1. Click Finish button when connection test is successful



In whatever UI you use to work with you connect to the DB with the following connection info:

Host: localhost
Port: <LOCAL_PORT_YOU_WANT_TO_LISTEN_ON>
User: postgres
Password: <PASSWORD>

**Comment by serge-rider** [comment]
Google cloud support was added in LE/EE/UE products.
Initially we support only SQL databases (MySQL, PostgreSQL and SQL Server).

![image](https://user-images.githubusercontent.com/6398845/162199061-c006255b-f1b8-4ec1-b04d-b26cc3a33723.png)

![image](https://user-images.githubusercontent.com/6398845/162198928-309ca169-ed28-4cb9-854c-969b9ea3ea7e.png)
![image](https://user-images.githubusercontent.com/6398845/162198963-3ab98a78-d832-46c5-8158-d1efbdef77ee.png)

**Comment by Matvey16** [comment]
Host name template is incorrect for MySQL and PostgreSQL. SQL Server doesn't have GCP authentication method
![dbeaver_tWj03fV7g7](https://user-images.githubusercontent.com/82543000/162744388-18a0f31b-5018-44f9-a598-18c64f594b9f.png)
![dbeaver_7D38vjUjzR](https://user-images.githubusercontent.com/82543000/162744400-c926a8f5-baae-47e3-bedb-5f0b1b481614.png)
![dbeaver_PypVxYOcgX](https://user-images.githubusercontent.com/82543000/162744583-bfc8e73a-19ae-46e8-a8b7-8ba75ac389d3.png)

**Comment by serge-rider** [comment]
Host names and configuration save were fixed.
SQL Server auth models configuration will be added in following GCP tickets

**Comment by Matvey16** [comment]
Verified
