### ISSUE TITLE
Update snap package to latest version

### ISSUE THREAD

**Issue by gasdia73** [dbeaver/dbeaver#12586]
It's been 3 weeks now that dbeaver pops up the new version notification (2.0.5 is out) but when you do
snap refresh
nothing is picked up about dbeaver.
Would you consider updating the snap package?

**Comment by eshirvana** [comment]
but the question is why snap is not getting that update yet?

**Comment by michal-bartak** [comment]
I just get to github to ask the same question. 
I have a feeling in the past there were no such delays. Never noticed significant delay, let's say greater than several days.
But not this time.

**Comment by eshirvana** [comment]
finally snap package got updated to 21.1 today .

![image](https://user-images.githubusercontent.com/72626662/120209425-ab9c5200-c1fc-11eb-9d78-27dcfe146928.png)

**Comment by riednyko** [comment]
Snap package already updated to latest version.
