### ISSUE TITLE
Incorrect Linux package manager detection (deb/rpm)

### ISSUE THREAD

**Issue by rmcouat** [dbeaver/dbeaver#12583]
#### System information: 
- Ubuntu Desktop 64 20.04
- DBeaver 21.0.4
- Additional extensions - none

#### Connection specification:
- Postgres 12
- standard install
- No tunnels

#### Describe the problem you're observing:
Version 21.0.4 offers an update to 21.0.5. If I take the update from the dialog, the process offers me the 21.0.5 .rpm file but it should be a .deb for a Ubuntu system
I download the .deb file and install but the old version is still around, Finally I discover the old version is a snap install.
I remove the snap install and then use the 21.0.5 install but all the database connections and configurations are gone. As well all the SQL scripts and ER diagrams are gone.
Looked in $HOME/.local/share/DBeaverData and sure enough the folders are empty.

I would not expect package removal in order to get a failing upgrade to function would have a side effect of removing user work spaces.

#### Steps to reproduce, if exist:
Described above

**Comment by Matvey16** [comment]
> Version 21.0.4 offers an update to 21.0.5. If I take the update from the dialog, the process offers me the 21.0.5 .rpm file but it should be a .deb for a Ubuntu system

Hello. I tried reproducing this also on Ubuntu 20.04 and I was prompted to download a .deb package. What browser are you using? Is it possible for you to provide an URI that a browser opens. Like this `https://dbeaver.io/download/?start&os=linux&arch=x86_64&dist=deb`

Also can you provide a command that you used to remove 21.0.4 version.

**Comment by rmcouat** [comment]
The browser I use is Firefox version 88.0.1, here is the download URL
https://dbeaver.io/download/?start&os=linux&arch=x86_64&dist=rpm
This comes up after pushing the Upgrade button on the new version dialog when dbeaver opens.

To remove the 21.0.4 version I used the command
sudo snap remove dbeaver-ce
After the re-install of the snap package it too was devoid of all configuration and it was still version 21.0.4 so now I am not sure whether it was the remove or the re-install that cleared the area - see next for the different location for the .local directory when a snap install is used. The sudo snap refresh dbeaver-ce command says there is no update available for 21.0.4.

Looking through my backup I found the $HOME/.local/DBeaverData did not exist which caused me to search for something else and turned up the files are under $HOME/snap/dbeaver-ce/nnn/.local where nnn is a snap assigned number with a symlink current pointing to nnn in the same directory.
My bad the backup was older than I would like but I wasn't thinking about this area for daily backup. At least I got some of it back. In the future I will export scripts to another area in my home directory away from the reach of installers.

Off topic, I wonder about the multiple competing package management systems in Linux. Before there was .rpm or .deb determined by the distro, now snap is on both system types causing confusion. I think I will remove the snap install and just use apt install going forward.

Hmm, ok I see licensing has changed with a new Lite layer and the CE version has moved to github.

Thanks for your consideration.

**Comment by p91paul** [comment]
Probably, dbeaver installed through snap should disable the upgrade dialog by default, since snap upgrades are handled differently. The loss of configuration is because of how snap works, but this all originates from the fact the user was confused into thinking it was a good idea to download a rpm/deb package while using a snap install.

**Comment by rmcouat** [comment]
I can confirm the snap remove command removed the .local files including the work area. Live and learn.
There were features I needed in the Enterprise version so I purchased that and  removed the CE version that was snap installed and moved forward with the .deb file download. For me the issue is closed.

**Comment by kseniiaguzeeva** [comment]
Seems, .rpm and .deb are wrongly indicated. We will fix it.

**Comment by Skydiveroid** [comment]
Perhaps we need to save information about DBeaver packaging in dbeaver.ini file

**Comment by Matvey16** [comment]
Verified
