### ISSUE TITLE
Save button is still active after reverting changes through refresh

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#12599]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.0
- Additional extensions

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
1. Create a new column through UI, but don't commit changes.
2. Click refresh or press F5
3. Agree to revert changes.

**Expected result:** Changes are reverted and save button is deactivated.
**Actual result:** Changes are reverted, but save button is still clickable though it doesn't do anything.

![2021-05-25_15h22_41](https://user-images.githubusercontent.com/82543000/119549449-e5ee9500-bd9f-11eb-97b2-28203116c6fa.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
