### ISSUE TITLE
Shell commands don't accept anything after space

### ISSUE THREAD

**Issue by morgan-zylotech** [dbeaver/dbeaver#12600]
#### System information: 
- Ubuntu 20
- DBeaver Community - Version 21.0.5.202105160657

#### Connection specification:
- Postgres
- Attempting to run a script file while passing parameters

#### Describe the problem you're observing:

GCP has set up a binary file you can use to set up a secure SSH tunnel with your DB instances

https://cloud.google.com/sql/docs/mysql/sql-proxy

Using the following command, nothing happens after the space following the bash

`/usr/bin/bash ./cloud_sql_proxy -instances=<MY-INSTANCE>:us-central1:<DATABASE>=tcp:5432`

or 

`./cloud_sql_proxy -instances=<MY-INSTANCE>:us-central1:<DATABASE>=tcp:5432`

or

`${home}/./cloud_sql_proxy -instances=<MY-INSTANCE>:us-central1:<DATABASE>=tcp:5432`

nothing after the space before `-instances` is picked up

Regardless of the technologies above, it appears anything after a space may or may not work as expected

#### Steps to reproduce, if exist:

Some test cases

Works as expected:

Input:
`echo foo`

Output:
`foo`

Doesn't work as expected:

Input:
`echo foo && echo bar`

Output:

`foo && echo bar`

Input:
```
echo foo && \
echo bar
```

Output:
`foo && \ echo bar`

input:
`/usr/bin/bash echo foo && echo bar`

Output: 
No Output

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
Hello @morgan-zylotech,

It's not bash, so you can't use `&&` and other operators.

Instead, you can use following approach:

```
/bin/bash -c 'echo hello && echo world'
```

**Comment by morgan-zylotech** [comment]
I've tried multiple iterations of the above without any luck (bash, shell etc). It's possible that my expectations are off but I would expect that with the command pasted above, the window would echo `hello world` and it does not where as the non bash version does. 

![bash-test-2](https://user-images.githubusercontent.com/70210123/127327011-b34392f4-af27-4397-b56a-368fb1778fe1.png)

![bash-response-2](https://user-images.githubusercontent.com/70210123/127327021-77888484-56bd-4b9a-85fc-900947fc707d.png)

![bash-test-1](https://user-images.githubusercontent.com/70210123/127327047-b537e9e3-80d6-471e-98e9-2632c0cc904a.png)

![bast-response-1](https://user-images.githubusercontent.com/70210123/127327070-1626e01d-aea3-4f14-9b33-3b7e947134d4.png)

**Comment by ShadelessFox** [comment]
My solution works for me (at least on Windows using WSL):

![image](https://user-images.githubusercontent.com/35821147/127329813-3361ffbb-3a46-4d31-9540-d07632f34da4.png)

Can you try executing the same command in your terminal to see if it even works?

You can also try enabling <kbd>Wait For Process To Finish</kbd>.

**Comment by morgan-zylotech** [comment]
Here is my OS info

```shell
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

No dice via dBeaver, even with `wait for process to finish` checked and 10000ms added for the timeout. 
I've also added 10000ms to the `pause after execute` to no avail.

`/usr/bin/sh -c 'echo hello && echo world'` in a terminal does indeed work as expected as does `/usr/bin/bash -c 'echo hello && echo world'`

As I am not familiar with the code, I am just hazarding a guess. Is it possible that the exception might be interfering with the command output redirection?

**Comment by ShadelessFox** [comment]
Nope, the exception is not interfering the command output.

We will need to test this behavior on Linux, maybe there's OS-dependent issue.

**Comment by Matvey16** [comment]
Verified
