### ISSUE TITLE
CSV Import incorrectly escaping field ending in backslash

### ISSUE THREAD

**Issue by vdurante** [dbeaver/dbeaver#12609]
#### System information: 
- Operating system (distribution) and version - Windows 10
- DBeaver version - 21.0.5 Community
- Additional extensions  - None

#### Connection specification:
- Database name and version - SQLite
- Driver name - xerial 3.34.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - No

#### Describe the problem you're observing:

Importing data from CSV incorrectly escaping field ending in backslash

#### Steps to reproduce, if exist:

Attempt to import the following CSV into a SQLite database

```
"Name","Country","Age"
"Peter","USA","25",
"Marco","Brazil\","20"
"Maria","Mexico","45"
```

**Comment by Matvey16** [comment]
Can you please provide your expected and actual result. I tried to reproduce this issue but it looks like everything is working as intended.
When importing from CSV you have an option to choose a character to use as an escape symbol

![2021-05-31_11h26_02](https://user-images.githubusercontent.com/82543000/120164380-31230080-c203-11eb-88cf-524df46a5dd9.png)

By default it is a backslash, so in your example it breaks the structure of your csv file (by basically deleting the double quote after it). What is the expected result of your import of this CSV file?
If you need to import this field `Brasil\` you need to change escape char to something that is not used in this file like $ or %

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info
