### ISSUE TITLE
Hana autocomplete failed

### ISSUE THREAD

**Issue by maritogaleano** [dbeaver/dbeaver#12601]
![image](https://user-images.githubusercontent.com/57814047/119565648-3651fc80-bd78-11eb-8797-52e61483e4bf.png)
Only the first time it autocompletes, but when I keep typing the sql query it no longer suggests the other fields

**Comment by LonwoLonwo** [comment]
Hello @maritogaleano 
Sorry, can't reproduce

![2021-06-02 17_47_00-](https://user-images.githubusercontent.com/45152336/120501969-b60c4680-c3ca-11eb-988c-4e138bf8d08d.png)

![2021-06-02 17_47_45-DBeaver Enterprise 21 1 0 - _spserver rtdi io_ Script-29](https://user-images.githubusercontent.com/45152336/120501978-b6a4dd00-c3ca-11eb-9550-ff211cd4ff6f.png)

Video of incorrect behaviour will be very helpful!

Also - Have you tried to use Ctrl + Space for auto-complete?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen an issue.
