### ISSUE TITLE
Save/Cancel buttons aren't activated after changing cell's value in Editor

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#12614]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 21.1.0

#### Connection specification:
- Database name and version SQLite

#### Describe the problem you're observing:
Save/Cancel buttons in Data Editor toolbar aren't activated after changing cell's value in Editor(Shift+Enter or Shift+Enter -> Open editor).

#### Steps to reproduce, if exist:
1. Open non-empty table and start to edit cell in Editor (eg., varchar or BLOB).
2. Make some changes and press Ctrl+S

**Actual result**
Edited cell is highlighted as a changed cell. Save and Cancel button aren't active. It is prompted to save changes in case of attempt of the refresh
![2021-05-27_10h50_40](https://user-images.githubusercontent.com/31996417/119787082-7ed4fb80-bed9-11eb-9a49-43be2bb35b8c.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
