### ISSUE TITLE
Provide an option to configure timestamptz (PostgreSQL)

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#12619]
**Is your feature request related to a problem? Please describe.**
I want to provide format for timestamptz at Preferences>Data Editor>Data Formats,  
but it is not possible there is no such menu option

**Describe the solution you'd like**
Provide menu option and update documentation [here](https://dbeaver.com/docs/wiki/Managing-Data-Formats/)

Also some details are here:
https://github.com/dbeaver/dbeaver/issues/12280

**Comment by Matvey16** [comment]
Timestamptz format copies the configuration from timestamp format. Are you asking to add additional option to configure them separately?

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual for you - feel free to reopen it with additional info

**Comment by KES777** [comment]
yes, I was asking about it. 
But this feature is very minor, so it is ok to close
