### ISSUE TITLE
How to move a ER diagram from one connection datagbase to another ?

### ISSUE THREAD

**Issue by codeRemark** [dbeaver/dbeaver#12648]
I draw ER diagram on a database connection which is remote . 

then I want works on offline like local host database . but even I dump the database of remote and restore on local . all ER diagram was lost 

I am confuse how to save or export the ER diagram  from one database then import to new ?

many thanks for your help!

**Comment by uslss** [comment]
seems to be a duplicate of #10886 - the feature will be implemented in the mentioned ticket.
[Here](https://github.com/dbeaver/dbeaver/issues/10886#issuecomment-776704611) you can find a workaround, but seems it is not needed to use git in your case.
