### ISSUE TITLE
Web Site Certificate Issues

### ISSUE THREAD

**Issue by bike4life** [dbeaver/dbeaver#12640]
When visiting your website being redirect by ISP as "dangerous site".

![Screen Shot 2021-05-27 at 5 29 41 PM](https://user-images.githubusercontent.com/13258915/119927685-bfab2f80-bf2e-11eb-8b4e-d28809a19932.png)

**Comment by serge-rider** [comment]
Thanks for the report.

I've re-checked SSL reports on Qualys (https://www.ssllabs.com/)  and SSLShopper (https://www.sslshopper.com/) and everything seems to be valid and trusted. The only issue is lack of some TLS 1.2  protcools support on the server-side. Even though Qualys rates it as B which means good enough (for plain binary content). Unfortunately we can't control this as download.dbeaver.com is a world-wide CDN (DigitalOcean), i.e. we can't control server settings. But we could talk with our VHP.

Could you say where are you from (country)? It may affect what particular CDN server serves your region.

Also is it possible to get any information about particular issues with server security?

**Comment by uslss** [comment]
there is no update on issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
