### ISSUE TITLE
Fill Class name automatically in Driver Properties

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12646]
DBeaver 21.1.0 EA
Mac

When we create a new driver manually, we look for its class by pressing **Find Class** button in **Libraries** tab. We should set its value to **Class name** in **Settings** tab as soon as it is found and selected.

![dbeaver_1gSN1WtzUt](https://user-images.githubusercontent.com/51405061/119994101-f20f6800-bfd4-11eb-8488-5dfbd7df9f57.png)

**Comment by ShadelessFox** [comment]
Already implemented:

https://user-images.githubusercontent.com/35821147/128372007-e1d90c7e-0e68-4577-9208-5a45c005e28e.mp4
