### ISSUE TITLE
Ability to find table by name across the whole database server

### ISSUE THREAD

**Issue by Dreamescaper** [dbeaver/dbeaver#12647]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I remember the table name, but not the database or namespace it's located in.
I've tried to use Navigate -> Open Database Object, but it seems to be working only for active database, not server.
I've also tried Search -> DB Metadata, but it simply returns 0 results.

**Describe the solution you'd like**
I would prefer Open Database Object to support to search across the whole server.

**Comment by uslss** [comment]
@Dreamescaper what database and dbeaver version do you use?

**Comment by Dreamescaper** [comment]
Database: SQL Server, 
DBeaver Community Edition 21.0.5

**Comment by uslss** [comment]
thank you for the suggestion

**Comment by flambchap** [comment]
Implemented.

**Comment by Matvey16** [comment]
Filtering fails if access is denied to at least one of the databases

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Search doesn't work

![fCsOwV139t](https://user-images.githubusercontent.com/82543000/132825651-045ee4bc-9741-449c-8188-99ae57cb4403.gif)

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
