### ISSUE TITLE
The automatic update prompt is not turned on, it will still prompt 

### ISSUE THREAD

**Issue by git10135405** [dbeaver/dbeaver#12642]
The automatic update prompt is not turned on, but when I start dbeaver, it still prompts？Is it a bug? 

![image](https://user-images.githubusercontent.com/35558611/119961305-7ca59680-bfd8-11eb-936b-72b03275011b.png)

**Comment by uslss** [comment]
please, uncheck higlighted option
![image](https://user-images.githubusercontent.com/31996417/120167512-801e6500-c206-11eb-9744-5f3573241229.png)
