### ISSUE TITLE
[dbeaver.io website] Incomplete view of files (see description)

### ISSUE THREAD

**Issue by mdziczkowski** [dbeaver/dbeaver#12653]
#### System information: 
- System: Ubuntu 20.04
- DBeaver version: 21.05
- Java version: supplied with application 
- Additional extensions: MariaDB driver

#### Describe the problem you're observing:

Under the URL: [dbeaver.io/files](https://dbeaver.io/files) not all content is visible (needed for the application repository)

#### Steps to reproduce, if exist:

Open the mentioned URL thru a web browser and check if you find (given as an example): jdbc folder or file

#### Include any warning/errors/backtraces from the logs

n/a

**Comment by serge-rider** [comment]
Could you write example of exact URL which doesn't work?

**Comment by mdziczkowski** [comment]
> Could you write example of exact URL which doesn't work?

https://dbeaver.io/files

Not that it does not work, but not everything is shown on the listing. For example, in the dbeaver application's configuration, there is a given URL to `https://dbeaver.io/files/jdbc`, but when opening the `https://dbeaver.io/files/` in the web browser, there is no `jdbc` folder listed

**Comment by E1izabeth** [comment]
The provided url points to the default file repository on dbeaver.io which is accessible only via DBeaver. You're not supposed to explore it through the web browser.
