### ISSUE TITLE
"Select from" from complex columns with NULLs and data wrong syntax 

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12658]
#### System information: 
- Windows 10, DBeaver 21.1.0 CE, Oracle 12

#### Steps to reproduce, if exist:
Click "Filter by column value" in complex column with NULL and other values in it (e.g. PM.ONLINE_MEDIA table, WIDTH column)
![image](https://user-images.githubusercontent.com/43252954/120159832-4a757e00-c1fe-11eb-9b62-cf664d41da50.png)
Select all values and click "Apply filter criteria"
![image](https://user-images.githubusercontent.com/43252954/120159950-6a0ca680-c1fe-11eb-812d-dacc89353135.png)
SQL Error occurs:
![image](https://user-images.githubusercontent.com/43252954/120160009-77c22c00-c1fe-11eb-97d6-1e91b99db83b.png)
And we can see generated query
![image](https://user-images.githubusercontent.com/43252954/120160562-0d5dbb80-c1ff-11eb-8f6e-979eb0b548ad.png)
In place of the highlight there should be "x."

#### Include any warning/errors/backtraces from the logs
![image](https://user-images.githubusercontent.com/43252954/120160009-77c22c00-c1fe-11eb-97d6-1e91b99db83b.png)

**Comment by ShadelessFox** [comment]
Fixed in scope of #13295
