### ISSUE TITLE
MySQL DATETIME(3) values displayed with ns precision instead of ms

### ISSUE THREAD

**Issue by CComparon** [dbeaver/dbeaver#12654]
Hello

Despite trying all the advice I found on issue #7268 and continuously upgrading DBeaver to latest version, I've always been facing this issue, both with Mysql5 and Mysql8.
Many thanks for any advice or possible fix.

#### System information: 
- OS: Windows 10 x64 19043
- DBeaver version: 21.0.5
- Additional extensions: none

#### Connection specification:
- Database name: MySQL community server 8 Windows x64
- Driver name: MySQL 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Columns of type DATETIME(0) are displayed fine (second-level precision), whereas columns of type DATETIME(3) are rendered with an obnoxious nanosecond-level precision with 6 trailing zeroes instead of millisecond-level precision.
*table properties:*
![image](https://user-images.githubusercontent.com/12992190/120119828-b00a3180-c14e-11eb-801c-d180b23c49f8.png)
*table data:*
![image](https://user-images.githubusercontent.com/12992190/120119839-bf897a80-c14e-11eb-8ec8-9ef20b17eda1.png)

#### Steps to reproduce, if exist:
Create a table such as the one I used in the section above.

#### Include any warning/errors/backtraces from the logs
none

**Comment by Matvey16** [comment]
Thank you for the report. We are already working on it.
