### ISSUE TITLE
Unnecessary quotes are displayed in task query

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12650]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.1.0 EA

#### Connection specification:
- Database name and version PostgreSQL
#### Steps to reproduce, if exist:
1. Create a task from query where a word is quoted 
2. Close _Add query_ dialog and look how the query looks in _Configure Data export settings_ page

**Expected**: the statement is displayed like it was written
**Actual result**: extra quotes are added to the quoted word
![Screenshot 2021-05-29 at 12 57 54](https://user-images.githubusercontent.com/51405061/120066103-8c2aeb00-c07d-11eb-9e29-fe90a2b50941.png)

**Comment by LonwoLonwo** [comment]
Fixed. Now we do not quote queries and do not generate extra quotes as a result of this.

![136989009-55288fc5-3e72-436d-81bd-63e474081255](https://user-images.githubusercontent.com/45152336/137021908-9adfdba9-a491-4183-8980-23d1a1d598cf.png)

**Comment by LonwoLonwo** [comment]
Export from query and export from query result set - two different cases for checking.

**Comment by Matvey16** [comment]
Verified
