### ISSUE TITLE
Small size of create trigger dialog disables trigger function field

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12651]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.1.0

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
Open DBeaver with screen resolution 1440x900 and try to create a trigger via a table properties

**Expected**: the trigger is created
**Actual result**: trigger function field is disabled in create trigger dialog

https://user-images.githubusercontent.com/51405061/120073724-459bb780-c0a2-11eb-8d94-78723c0bc319.mov

**Workaround**: expand the dialog to activate the field

**Comment by flambchap** [comment]
Reproduced on 1920x1200 resolution.

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
