### ISSUE TITLE
Ability to Export Query which populated the results into the same workbook but different sheet.

### ISSUE THREAD

**Issue by nmadham** [dbeaver/dbeaver#1266]
1.Ability to export data in Excel.
2.Ability to Export Query which populated the results into the same workbook but different sheet.
![image](https://cloud.githubusercontent.com/assets/16705400/22949696/24aea7a6-f2d1-11e6-9c46-35342abd5aa2.png)

**Comment by p91paul** [comment]
The issue is old, but for people coming from google request 1 is covered by https://github.com/dbeaver/dbeaver/wiki/Extension-Office

**Comment by E1izabeth** [comment]
Is this feature request still relevant? It seems that it has already been implemented.

**Comment by uslss** [comment]
Already implemented in PRO version 
![image](https://user-images.githubusercontent.com/31996417/208428858-050bf2aa-a974-48a3-a106-17e20c41d43f.png)
