### ISSUE TITLE
Zero date '0000-00-00 00:00:00' is displayed as NULL

### ISSUE THREAD

**Issue by igorlash** [dbeaver/dbeaver#12667]
#### System information: 
- Operating system (distribution) and version : Linux Mint 20.1 Cinnamon
- DBeaver version 21.1.0.202105300349
- Additional extensions

#### Connection specification:
- Database name and version MySQL 5.6.35-1+deb.sury.org~xenial+0.1
- Driver name MySQL 5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

When a datetime field is  set to "0000-00-00 00:00:00", DBeaver displays it as NULL.
![image](https://user-images.githubusercontent.com/31065075/120193113-af43cf00-c224-11eb-9142-4770ec0ec2ab.png)
But if you check using mysql (command line client) the result will be different.
![image](https://user-images.githubusercontent.com/31065075/120193286-e619e500-c224-11eb-85b5-df95d933b36c.png)

**Comment by flambchap** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
Date `0000-00-00 00:00:00` is a special MySQL hack, it is not a valid date. It is converted to NULL by default.
You can change this behavior by disabling date formatting in the preferences:
![image](https://user-images.githubusercontent.com/6398845/120210086-0dc67880-c238-11eb-8b7c-f0fb9b2b18e4.png)

**Comment by igorlash** [comment]
I disabled date formatting in the preferences
![image](https://user-images.githubusercontent.com/31065075/120213048-72cf9d80-c23b-11eb-8146-d6b142cd8a6b.png)
but the result is still the same 
![image](https://user-images.githubusercontent.com/31065075/120213155-8f6bd580-c23b-11eb-805c-1dad661c2faa.png)
![image](https://user-images.githubusercontent.com/31065075/120213198-9b579780-c23b-11eb-8e50-5a91eb21838e.png)

**Comment by serge-rider** [comment]
That's odd. 
Check connection settings, this parameter can be redefined for a particular connection:
![image](https://user-images.githubusercontent.com/6398845/120231420-0e700680-c25a-11eb-8acc-2588d19a5fa5.png)

Also what driver version do you use? You can get it from Test Connection dialog.

**Comment by igorlash** [comment]
I have updated the connection properties 
![image](https://user-images.githubusercontent.com/31065075/120277844-4197b180-c2bd-11eb-9211-ece0c8860dce.png)
The problem still exists
![image](https://user-images.githubusercontent.com/31065075/120277896-507e6400-c2bd-11eb-85ea-bbfc85d76186.png)
My connection information is 
![image](https://user-images.githubusercontent.com/31065075/120277973-668c2480-c2bd-11eb-8cb4-25627d479915.png)

Server : MySQL 5.6.35-1+deb.sury.org~xenial+0.1
Driver : MySQL Connector Java mysql-connector-java-5.1.40 ( Revision: 402933ef52cad9aa82624e80acbea46e3a701ce6 )

**Comment by serge-rider** [comment]
Could you try to use MySQL 8 driver (or MariaDB driver)?

Earlier version of MySQL JDBC driver couldn't evaluate zero dates properly.

**Comment by igorlash** [comment]
I have checked with MySQL 8 driver and MariaDB driver.
I works correctly with both of them 

![image](https://user-images.githubusercontent.com/31065075/120322753-6e63bd00-c2ed-11eb-822e-e9f23eafc83e.png)

Thanks :)
