### ISSUE TITLE
Export Data - Export to SQL insert Statements interface bug

### ISSUE THREAD

**Issue by plvnv** [dbeaver/dbeaver#12663]
Dbeaver CE 21.0.5 macos

"Export table row to SQL Insert"  interface BUG

1) right mouse click -> select "export  data..." -> "Export to SQL insert Statements"
![image](https://user-images.githubusercontent.com/52536610/120185379-c8e01900-c21a-11eb-9987-1d7819fe6782.png)

2) Set checkbox "Include Generated Columns" and then get this
![image](https://user-images.githubusercontent.com/52536610/120185504-f6c55d80-c21a-11eb-82f2-3ac39c3f18cb.png)

**Comment by uslss** [comment]
seems to be duplicate of the #12566 
anyway, thanks for the report
