### ISSUE TITLE
New modal window must be activated

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#12674]
#### System information: 
- Linux Mint 19.3 Cinnamon
- DBeaver version 21.0.3

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/799021/120224276-d5309a00-c24b-11eb-9d7c-f880b8a3fd83.png)

Can not click on close button (2), because there modal window (1) about updates

This new modal window must be active, so I can understand which buttons to press =)

**Comment by ShadelessFox** [comment]
Hello @KES777,

On my machine the <kbd>Tip of the day</kbd> window is opened **BEFORE** <kbd>Version update</kbd>, so behavior is correct. Both windows are modal, I don't think we want to make them both non-modal.

Are you sure you haven't changed focus to another window by accident?

**Comment by KES777** [comment]
If I remember correct, on my machine the `tip` is also opened first.

Notice, `tip of the day` is marked as active. After this second `version update` modal window is opened.
so first windows become unclickable, but still is on foreground.

I mean focus should be moved to this second window (it must become active instead of `tip of the day`)

**Comment by ShadelessFox** [comment]
In my case <kbd>Version update</kbd> is the active window, and since it is opened last, it can be closed.

Can you record a video? You can use debug options to override DBeaver's version, so the update dialog can be seen every time.

https://github.com/dbeaver/dbeaver/wiki/Debug-options

**Comment by KES777** [comment]
ok, I will try

**Comment by uslss** [comment]
Issue is reproducible, e.g., with mysqldump. (#13913)
> #### System information:
> * Operating system (distribution) and version: Ubuntu 18.04
> * DBeaver version 21.2.0
> * Additional extensions None
> 
> #### Connection specification:
> * Database name and version
> * Driver name Mysql
> * Do you use tunnels or proxies (SSH, SOCKS, etc)?  Yes, SSH tunnel
> 
> #### Describe the problem you're observing:
> Mysqldump window can't be closed after succesfull DB dump via SSH but it shows that it was finished. Window freezes and DBeaver can't be used. Can kill only with xkill
> ![alt text](https://camo.githubusercontent.com/ee0be4f7bec7874e982f4768a3755cc539ac2651a87c04bc10cc6f7cbe90e605/687474703a2f2f692e696d6775722e636f6d2f6e7133394754542e706e67)
>

**Comment by ShadelessFox** [comment]
@uslss see https://github.com/dbeaver/dbeaver/issues/12674#issuecomment-905362594

**Comment by uslss** [comment]
in this case, a notification message appears behind the export dialog and it is not visible to the user. So the export dialog cannot be closed and it looks like the application is frozen.
works ok on win
![image](https://user-images.githubusercontent.com/31996417/133432669-43249e0a-79eb-42c0-956b-a2c2cc69fcf1.png)

**Comment by Destrolaric** [comment]
The issue is reproducible in XFCE and Gnome DE. 
I tried to reproduce it on KDE Plasma mysqldump is working correctly
![VirtualBoxVM_OWMirxDl6r](https://user-images.githubusercontent.com/20579256/149772599-d61c424a-eba6-4cef-993d-f75f5605ada1.png)

**Comment by Matvey16** [comment]
Verified
