### ISSUE TITLE
Pinned columns don't unpin after clearing filters

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#12678]
#### System information: 
- Operating system (distribution) and version Ubuntu 20.04 and Win10
- DBeaver version 21.1.0

#### Describe the problem you're observing:
The button "Remove all filters/ordering" doesn't work with pinned columns. It is inactive if no other filtering is applied and when it is active, it removes everything but not pinned columns.

#### Steps to reproduce, if exist:
1. Pin a column.
2. Click `Remove all filters/ordering`

**Expected:** Column is unpinned
**Actual:** Column is still pinned

![2021-06-01_10h21_14](https://user-images.githubusercontent.com/82543000/120283813-457b0200-c2c4-11eb-8296-86bb35ed5d69.gif)

**Comment by kseniiaguzeeva** [comment]
Works as expected.
