### ISSUE TITLE
Saving MySQL execution plan results in NPE and blank file.

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#12680]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.0

#### Connection specification:
- Database name and version MariaDB
- SSH

#### Describe the problem you're observing:
When trying to save execution plan for MariaDB it is saved as blank file and NPE is thrown.

#### Steps to reproduce, if exist:
1. Run any SELECT in SQL Editor.
2. Click `explain execution plan`
3. Click `Save plan` and chose any folder and name.

**Expexted:** Execution plan is saved
**Actual:** NPE is thrown and Execution plan save file is saved, but is blank.

#### Include any warning/errors/backtraces from the logs

> java.lang.NullPointerException
> 	at com.google.gson.internal.$Gson$Preconditions.checkNotNull($Gson$Preconditions.java:39)
> 	at com.google.gson.JsonPrimitive.<init>(JsonPrimitive.java:61)
> 	at org.jkiss.dbeaver.ext.mysql.model.plan.MySQLPlanAnalyser$1.addNodeProperties(MySQLPlanAnalyser.java:106)
> 	at org.jkiss.dbeaver.model.impl.plan.AbstractExecutionPlanSerializer.serializeNode(AbstractExecutionPlanSerializer.java:67)
> 	at org.jkiss.dbeaver.model.impl.plan.AbstractExecutionPlanSerializer.serializeJson(AbstractExecutionPlanSerializer.java:95)
> 	at org.jkiss.dbeaver.ext.mysql.model.plan.MySQLPlanAnalyser.serialize(MySQLPlanAnalyser.java:89)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLPlanSaveProvider.doSave(SQLPlanSaveProvider.java:60)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLPlanSaveProvider$SaveAction.run(SQLPlanSaveProvider.java:106)
> 	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
> 	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
> 	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:453)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
> 	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:260)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.1.4

**Comment by Matvey16** [comment]
Verified
