### ISSUE TITLE
Custom connection to cloud Oracle

### ISSUE THREAD

**Issue by liemoli** [dbeaver/dbeaver#12689]
#### System information: 
- Operating system (distribution) and version Windows Server 2012R2
- DBeaver version 21.1
- Additional extensions NO

#### Connection specification:
- Database name and version kwflqv4gxisozun_autotorinodwh_high.adwc.oraclecloud.com
- Driver name Oracle 12.1.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
After updating the software we can no longer connect to oracle databse (in the cloud) due to error that I report below:
Invalid connection string format, a valid format is: "host:port:sid" 
![error](https://user-images.githubusercontent.com/85170770/120322919-3ce6f380-c2e5-11eb-84b5-20c3aa39c380.PNG)

**Comment by uslss** [comment]
hi @liemoli ,
did you try to re-create the connection? which jdbc URL is used in your case?

**Comment by liemoli** [comment]
Hi,

in the previous version I used a custom connection similar to this one:

jdbc:oracle:thin:@(name database)?TNS_ADMIN=(path file)

Thanks



LucaIemoli
Ufficio Sistemi e Networking
+39 0342634298
+39 3485420605
***@***.***

Cosio Valtellino (SO)|Via Stazione, 4–
23013|0342 634211
SEDE LEGALE Milano (MI) Via Ansperto, 7 – 20123  |  SEDE AMMINISTRATIVA Cosio V.no (SO) Via Stazione, 4 – 23013  |  Cod. Fiscale e P. IVA 10024610155  |  COD. UNIVOCO M5UXCR1


Rispetta l’ambiente. Hai davvero bisogno di stampare questa mail?
Le informazioni, i dati e le notizie contenute nella presente comunicazione e i relativi allegati sono di natura riservata e sono destinate esclusivamente ai destinatari. La diffusione, distribuzione e/o la copiatura da parte di qualsiasi soggetto diverso dal destinatario è proibita. Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo e di darcene immediata comunicazione anche inviando un messaggio di ritorno all’indirizzo e-mail del mittente.

**Comment by uslss** [comment]
sorry for the late response. is it still actual?

**Comment by liemoli** [comment]
yes the problem is still current.



LucaIemoli
Ufficio Sistemi e Networking
+39 0342634298
+39 3485420605
***@***.***

Cosio Valtellino (SO)|Via Stazione, 4–
23013|0342 634211
SEDE LEGALE Milano (MI) Via Ansperto, 7 – 20123  |  SEDE AMMINISTRATIVA Cosio V.no (SO) Via Stazione, 4 – 23013  |  Cod. Fiscale e P. IVA 10024610155  |  COD. UNIVOCO M5UXCR1


Rispetta l’ambiente. Hai davvero bisogno di stampare questa mail?
Le informazioni, i dati e le notizie contenute nella presente comunicazione e i relativi allegati sono di natura riservata e sono destinate esclusivamente ai destinatari. La diffusione, distribuzione e/o la copiatura da parte di qualsiasi soggetto diverso dal destinatario è proibita. Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo e di darcene immediata comunicazione anche inviando un messaggio di ritorno all’indirizzo e-mail del mittente.

**Comment by uslss** [comment]
please, check if it is still actual against 21.1.4.
Unfortunately, we've got no environment to test it.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual - feel free to reopen it with additional info
