### ISSUE TITLE
sha256 mismatch when installing version 21.1.0 with brew

### ISSUE THREAD

**Issue by MetalArend** [dbeaver/dbeaver#12699]
#### System information: 
- Operating system (distribution) and version: macOS Catalina 10.15.7
- DBeaver version: 21.1.0

#### Describe the problem you're observing:
Could not install dbeaver using brew, because of sha256 mismatch.

#### Steps to reproduce, if exist:
`brew reinstall --cask dbeaver-community`

#### Include any warning/errors/backtraces from the logs
```
Error: SHA256 mismatch
Expected: d8500c45917480c2532db584e0470b9c015abd25a09ce68beafd7a70dba3c3ff
  Actual: dec806a96ea9609e45357ca31685e39495973d22ee1612099b73756cfe740573
    File: /Users/user/Library/Caches/Homebrew/downloads/b32ade3e2b41e43fddc587ddbcc5fc48e23b6be7de2b69297b4e0b8e17c66134--dbeaver-ce-21.1.0-macos.dmg
To retry an incomplete download, remove the file above.
```

**Comment by serge-rider** [comment]
We republished 21.1 release version because of multiple issues with Java 11.0.11 and TLS1/1.1 support.
Brew package has to be rebuild as well. 
Currently you can download new version from dbeaver.io.

**Comment by xlogix** [comment]
I faced the same issue. Downloaded the file from the website.

**Comment by tracure1337** [comment]
same here

**Comment by flambchap** [comment]
Fixed with the PR linked above. Thank you, @nicerloop.
