### ISSUE TITLE
Active schema selection shows wrong options for SQL Server

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#12708]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.0
- 
#### Connection specification:
- Database name and version SQL Server
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Active schema button (Ctrl + 0) in SQL Editor gives an option to choose Database and Schema, but choosing any schema does nothing, active schema will always be `dbo` regardless of user's choice.

**Steps to reproduce:**
1. Open SQL Editor and choose any active schema other than `dbo`
2. Execute `SELECT SCHEMA_NAME();`

**Expexted:** Rusultset shows chosen schema name
**Actual:** Shows `dbo`

![2021-06-02_16h53_19](https://user-images.githubusercontent.com/82543000/120492912-28792880-c3c3-11eb-9c74-829fa138b860.gif)

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
