### ISSUE TITLE
Column renaming in view shows revert confirmation dialog

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#12707]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.1.0

#### Connection specification:
- Database name and version postgres
#### Describe the problem you're observing:
1. Open properties tab for view
2. Try to rename view's column using f2
3. Change name and press ok
NOTE: issue is actual for renaming from db navigator
**Actual result** 
Revert Confirmation dialog appears.
![image](https://user-images.githubusercontent.com/31996417/120486352-a20e1800-c3bd-11eb-8aae-793f3d3bb3f7.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by DariaMarkaryan** [comment]
Verified
