### ISSUE TITLE
Want to change order of columns

### ISSUE THREAD

**Issue by MrApollo** [dbeaver/dbeaver#12701]
Okay, so this might be an easy one that I'm just not seeing but I was wondering if it was possible to change the order that columns come in when viewing a table.

<img width="205" alt="Properties" src="https://user-images.githubusercontent.com/85119190/120467102-b8a17880-c397-11eb-8f21-def83fbe3a21.png">
<img width="252" alt="Data" src="https://user-images.githubusercontent.com/85119190/120467109-b93a0f00-c397-11eb-98a4-4b507c0daa80.png">

So instead of it going this order I want to have ID come first.
Any help would be great, Thanks!

**Comment by p91paul** [comment]
You can drag and drop columns in the Data tab. The drag point is the column type icon!

**Comment by MrApollo** [comment]
> You can drag and drop columns in the Data tab. The drag point is the column type icon!

Perfect mate, Cheers for that.

**Comment by MrApollo** [comment]
> > You can drag and drop columns in the Data tab. The drag point is the column type icon!
> 
> Perfect mate, Cheers for that.

Just realised it seems to not save when I do it like this, any idea why?

**Comment by ShadelessFox** [comment]
Hello @MrApollo,

To save columns position you need to press <kbd>Save filter settings</kbd>:

![image](https://user-images.githubusercontent.com/35821147/120491701-21054f80-c3c2-11eb-864e-b89d7bf9efaf.png)

**Comment by MrApollo** [comment]
> Hello @MrApollo,
> 
> To save columns position you need to press Save filter settings:
> 
> ![image](https://user-images.githubusercontent.com/35821147/120491701-21054f80-c3c2-11eb-864e-b89d7bf9efaf.png)

Is there a way to save this filter setting for anyone accessing the database, not just myself.

**Comment by ShadelessFox** [comment]
No, you can't. 

If you're using MySQL, you can change the order using arrows shown below and persist it across the database:
![image](https://user-images.githubusercontent.com/35821147/120496786-88bd9980-c3c6-11eb-876b-4208ef3bec86.png)

**Comment by MrApollo** [comment]
> No, you can't.
> 
> If you're using MySQL, you can change the order using arrows shown below and persist it across the database:
> ![image](https://user-images.githubusercontent.com/35821147/120496786-88bd9980-c3c6-11eb-876b-4208ef3bec86.png)

My friend, you are truly a hero
