### ISSUE TITLE
Refresh in ER Diagram reverts all changes without asking

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#12703]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.0

#### Steps to reproduce, if exist:
1. Make some changes in ER diagram (Drag new tables, change their positioning, create/delete connections)
2. Change view style in context menu or press F5

**Expected:** Pop-up window appears asking if you want to revert changes.
**Actual:** All changes are reverted without asking.

![2021-06-02_13h59_33](https://user-images.githubusercontent.com/82543000/120474076-691b7680-c3b0-11eb-8d66-8135a8c0bfdc.gif)

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
