### ISSUE TITLE
Unique keys are not displayed in the Keys tab of table properties

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12725]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.1 EA EE
#### Connection specification:
- Database name and version Snowflake
#### Steps to reproduce, if exist:
1. Create a table unique key
2. Refresh the table and open the Keys tab
**Expected**: Unique keys are displayed
**Actual result**: Only a primary key is visible, but PK and UK are displayed in a table DDL

https://user-images.githubusercontent.com/51405061/120681072-a9a7ec80-c4a3-11eb-80a9-06434cf6e829.mov

**Comment by LonwoLonwo** [comment]
duplicate of https://github.com/dbeaver/dbeaver/issues/7820
