### ISSUE TITLE
Columns in newly created tables are not visible until schema refresh

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#12723]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.1.0

#### Connection specification:
- Database name and version Redshift

#### Describe the problem you're observing:
Columns aren't shown after table create/copy and saving.
#### Steps to reproduce, if exist:
1. Create table with several columns OR Copy existing table
2. Save it

**Actual result**
Columns aren't visible until schema refresh.
![2021-06-03_16h40_00](https://user-images.githubusercontent.com/31996417/120656638-727a1100-c48c-11eb-9976-b8c32b247f30.gif)
![2021-06-03_15h00_20](https://user-images.githubusercontent.com/31996417/120656644-73ab3e00-c48c-11eb-9ba4-ed74c1759c03.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
