### ISSUE TITLE
[Oracle] Changes in package not visible after refresh in declaration tab of package

### ISSUE THREAD

**Issue by F0xD8rk** [dbeaver/dbeaver#12729]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.1.0.202106012023

#### Connection specification:
- Database name and version: Oracle 12

#### Describe the problem you're observing:
Steps to follow:
1. Edit an Oracle package using another editor (f.e. Visual Studio Code) and add a function (or procedure) to the package
2. Run the create package SQL code in the SQL editor
3. If you now navigate to the package using _Open declaration_, the new function/procedure is not visible, even after using the refresh button in the _Body/Declaration_ tab of the package. This now only works when going to the schema manually on the left side and then perform a manual refresh there. 

However, in the past this worked fine using the refresh button in the _Body/Declaration_ tab of the package. Would it be possible to change this again, because it takes more time now to make changes to packages etc.

**Edit:**
After some further testing, it appears the package declaration/body are adjusted the first time creating the package with the changes using the SQL editor of DBeaver. However, if you then add another function to the package (in another editor) and create it again using the SQL editor of DBeaver, the second added function is not visible in the declaration/body.

**Comment by uslss** [comment]
probably will be resolved in the scope of #6398

**Comment by uslss** [comment]
#8922
