### ISSUE TITLE
Persist history of SQL Expressions on filter result

### ISSUE THREAD

**Issue by dyorgio** [dbeaver/dbeaver#12737]
**Is your feature request related to a problem? Please describe.**
No, it is a improvement.
When you restart/open DBeaver previous opened tables are opened again, but not filtered, in fact no filter history is available.

**Describe the solution you'd like**
DBeaver should save filter history and open tables with last filter used.

**Describe alternatives you've considered**
Maybe it can start without filter, but with history available (the list of previous filter maybe contains search field and buttons to manage it: remove/clean all).

**Additional context**
Today I need to rewrite filters every time that I open DBeaver, this feature will save me a lot of time :angel:.

**Comment by uslss** [comment]
Filter history after restart is available in EE version.
Did you try to use "Save filter settings" button?
![image](https://user-images.githubusercontent.com/31996417/132680430-959625f7-2b7a-4cb6-84c9-36c559678bb1.png)
Sorry for the late response

**Comment by uslss** [comment]
there is no update for a long time.
If it is still actual - feel free to reopen the issue.
