### ISSUE TITLE
Image preview flickering

### ISSUE THREAD

**Issue by Wroud** [dbeaver/dbeaver#12732]
#### Describe the problem you're observing:
Image flickering on scroll after resize

#### Steps to reproduce, if exist:
1. Open image preview panel
2. Press "Fit window"
3. Downscale preview panel
4. Scroll fast

![image](https://user-images.githubusercontent.com/811729/120782535-c7706280-c532-11eb-8a0e-6a1f96ac9860.png)

**Comment by uslss** [comment]
verified
