### ISSUE TITLE
Grid lines in Properties are invisible in dark theme

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12730]
#### System information: 
- Windows 10, DBeaver 21.1.0 (CE, UE..), all databases

#### Steps to reproduce, if exist:
Change them on the Dark mode -> restart DBeaver. Now you cant see grid guidelines in properties of tables
![image](https://user-images.githubusercontent.com/43252954/120769195-8b82d080-c525-11eb-9a5e-b8613d54c7ff.png)

**Comment by serge-rider** [comment]
It is a feature. Grid lines are ugly in dark theme.
