### ISSUE TITLE
Same SQL multiple database servers

### ISSUE THREAD

**Issue by adrianocunha3000** [dbeaver/dbeaver#1273]
It would great to be able to submit the same SQL query to multiple database servers and view the returned messages/results - like Yohz SQL Multi Select [1], Datanamic MultiRun for PostgreSQL [2], and TOAD Script Manager [3].

Links
[1] http://www.yohz.com/sms_details.htm
[2] http://www.datanamic.com/multirun-for-postgresql/
[3] http://www.toadworld.com/products/toad-for-oracle/b/weblog/archive/2009/12/06/execute-toad-scripts-on-multiple-databases

**Comment by yonisade** [comment]
*Like Toad Group Execute in Toad for MySQL/SQL Server

**Comment by uslss** [comment]
The feature is already implemented as Composite task in EE version

**Comment by michaelkarpenko-ship-it** [comment]
> The feature is already implemented as Composite task in EE version

no it is not
selects a re not returning result, unless you want to parse logs
