### ISSUE TITLE
Invalid precision for Number column type

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12739]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.1 EA

#### Connection specification:
- Database name and version Snowflake

#### Steps to reproduce, if exist:
Perform db export of a table with Number column type to a new table

**Expected**: the export is successful
**Actual result**: the export fails because of wrong Number column precision (100 is set instead of 38)

**Comment by LonwoLonwo** [comment]
duplicate of https://github.com/dbeaver/dbeaver/issues/13389
