### ISSUE TITLE
Hide password during a user creation

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12738]
#### System information: 
- DBeaver version 21.1 EA

#### Connection specification:
- Database name and version Redshift, PostgreSQL etc

We have to hide a password when we create it for a user (Metadata Editor, maybe SQL Editor)

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.1.5

**Comment by Matvey16** [comment]
Verified
New ticket for password in SQL Editor #13479
