### ISSUE TITLE
User permissions: revoke/grant all buttons bloat the script

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#12740]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.1

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
When changing permissions clickng `Grant all` buttons and then unchecking every permission still offer to save changes and the script have a lot of annecessary statements. And the same in the opposite situation when first revoking all and granting back.

#### Steps to reproduce, if exist:
1. Open role permissions for a role that has none.
2. Click `Grant all`
3. Continiously uncheck all permissions.
4. Try to click save

**Expected:** Save button is inactive, because no changes were made.

**Actual:** Promted to execute a script with a lot of unnecesary satatements. 

![2021-06-04_17h25_48](https://user-images.githubusercontent.com/82543000/120839575-c9a5e180-c571-11eb-9c21-afa940d15ca0.gif)

**Comment by ShadelessFox** [comment]
Fixed:

https://user-images.githubusercontent.com/35821147/144040497-77c57956-4d78-4241-9782-7f268a4d9f96.mp4

**Comment by Matvey16** [comment]
Wrong script when granting some of the permissions and then revoking all

![adB5eH3AEo](https://user-images.githubusercontent.com/82543000/144811184-74a1fe04-479c-49fc-ba50-be15cde48565.gif)

**Comment by Matvey16** [comment]
Verified
