### ISSUE TITLE
Wrong variable parsing in kerberos keytab file path

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12749]
#### System information: 
- Windows 10, DBeaver ultimate 21.1.0
#### Steps to reproduce, if exist:
Go to db connection settings (e.g. for mariaDB) -> Authentication profile - manage profiles: 
![image](https://user-images.githubusercontent.com/43252954/120934575-7a91b500-c707-11eb-8289-7ee74f9a4ac5.png) ->
In kerberos auth check **use keytab** and input valid path with using a variable then connect
![image](https://user-images.githubusercontent.com/43252954/120934568-74033d80-c707-11eb-91d4-46444a561f4d.png)

Result : "${...}" doesn't expire after parsing 
![image](https://user-images.githubusercontent.com/43252954/120931647-35678600-c6fb-11eb-9040-6e0dc21b0c73.png)

This is even not the project.path variable value but app path/name 
![image](https://user-images.githubusercontent.com/43252954/120934617-b7f64280-c707-11eb-8385-22e16e7ba4cc.png)

**Comment by ShadelessFox** [comment]
I don't see a hint saying that you can use variables in this situation, I suggest it's just not implemented.
So it's more an improvement rather than bug.

**Comment by serge-rider** [comment]
It doesn't work for auth profiles because most variables (like datasource properties) are not available for profiles.

**Comment by LonwoLonwo** [comment]
Implemented in DBeaver 21.2.5

![2021-10-27 21_04_46-DBeaver Ultimate 21 2 4 - xml_data](https://user-images.githubusercontent.com/45152336/139130836-f29ab3fc-7f8e-4eb9-9431-338b12a45912.png)

![2021-10-27 21_06_45-Properties for General](https://user-images.githubusercontent.com/45152336/139130842-4b4c7e85-7609-4500-b56b-6cfac457c70a.png)

**Comment by Matvey16** [comment]
Verified
