### ISSUE TITLE
Map: button to copy the position of the center of the viewport

### ISSUE THREAD

**Issue by chapmanjacobd** [dbeaver/dbeaver#12746]
Sometimes I need to update point geometry in the database. The Map viewer is very helpful but it doesn't allow me to copy the correct coordinate so that I can update it. I have to open a browser and go to an online map, pan to the correct location and copy the latlng.

**Describe the solution you'd like**
I would like to have a button which inserts the centroid of the map viewport (in the current coordinate system) into the clipboard.

**Describe alternatives you've considered**
Maybe that is a little hacky but I can't think of a better way other than to make the geometry movable (direct manipulation) to update the geometry within the results panel (but that seems like a lot more work without much additional benefit).

**Additional context**

**Comment by ShadelessFox** [comment]
Hello @chapmanjacobd,

Thanks for the suggestion!

**Comment by ShadelessFox** [comment]
Implemented basic functionality:

![xgXwX2R1fI](https://user-images.githubusercontent.com/35821147/121094062-adff3d00-c7f6-11eb-803c-9c0c45de1a3e.png)

It copies the coordinates formatted as `latitude, longitude` to the clipboard.

Please note that it intentionally works only when viewed inside DBeaver.

**Comment by Matvey16** [comment]
Wrong coordinates are copied, may always be from EPSG:3857

**Comment by Matvey16** [comment]
Verified.
Please note that the coordinates are copied according to EPSG:4326 CRS and are just raw numbers. You may need to remove comma and switch latitude and longitude places to correctly insert it into a database.
