### ISSUE TITLE
Oracle: Slow query on "Loading package cache"

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#12747]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 21.1.0.202105300349
- Additional extensions n/a

#### Connection specification:
- Database name and version Oracle 11
- Driver name ojbc19
- Do you use tunnels or proxies (SSH, SOCKS, etc)? n/a

#### Describe the problem you're observing:
While "Loading package cache" or "Searching proposals" for autocompletion in sql editor is running on Oracle, the following query is issued:
```
SELECT  * FROM ALL_OBJECTS WHERE OBJECT_TYPE='PACKAGE' AND OWNER='MY_OWNER'  ORDER BY OBJECT_NAME
```

On my database that query is insanely slow. But the really absurd thing is that the following query performs much better:

```
SELECT  OWNER, OBJECT_NAME, SUBOBJECT_NAME, OBJECT_ID, DATA_OBJECT_ID, 'PACKAGE' OBJECT_TYPE, CREATED, LAST_DDL_TIME, TIMESTAMP, STATUS, TEMPORARY, GENERATED, SECONDARY, NAMESPACE, EDITION_NAME
FROM ALL_OBJECTS WHERE OBJECT_TYPE='PACKAGE' AND OWNER='MY_OWNER'  ORDER BY OBJECT_NAME 
```

The listed fields are exactly the same (I just expanded * to the full list of fields returned by that query), **except for OBJECT_TYPE which is forced to 'PACKAGE'** (which is bound to be true because of the WHERE clause).

Execution times of the 2 queries on my system: 30 seconds for the first one, some hundred milliseconds for the second.

#### Steps to reproduce, if exist:
Open a new connection, new sql editor, then ask for autocompletion proposals.

**Comment by ShadelessFox** [comment]
Hello @p91paul,

That's interesting, thanks for the suggestion!

**Comment by Matvey16** [comment]
Verified
