### ISSUE TITLE
Teradata: Show Procedure fetches partial results

### ISSUE THREAD

**Issue by lalato** [dbeaver/dbeaver#12745]
#### System information: 
- MacOS 11.3.1
- DBeaver 21.1.10

#### Connection specification:
- Teradata 16.20

#### Describe the problem you're observing:
When using the SHOW PROCEDURE query some large stored procs (greater than 1000 rows) only return a partial/incomplete DDL.  Running the same query using the menu options for fetching the DDL from the Navigator has the same partial result. 

Teradata Studio which is also based on Eclipse does appear to be able to pull the full DDL.  So not sure what the difference might be in DBeaver.

#### Steps to reproduce, if exist:

SHOW PROCEDURE schema.procedure;

**Comment by lalato** [comment]
I wonder if there is a setting for max record size that I might have missed?

**Comment by uslss** [comment]
thanks for the report

**Comment by lalato** [comment]
Just upgraded to Version 21.1.1.202106210813.  Issue appears to be resolved.  I see in the release notes that changes were made to trigger and procedure DDLs, I assume this change is what fixed the problem.  Thanks!

**Comment by LonwoLonwo** [comment]
Hello @lalato 
We solved this problem https://github.com/dbeaver/dbeaver/issues/11985
It can be related to this ticket or not.
Can you please test again with big procedures?

**Comment by lalato** [comment]
@LonwoLonwo I tested on a procedure that was only giving partial DDL when I first logged this issue.  It is now showing the full DDL.  So it appears that the changes made to fix #11985 also fixed this issue.

**Comment by LonwoLonwo** [comment]
Fantastic! Thanks for testing.
Can I close this ticket?
