### ISSUE TITLE
Data loss after Mac OS updates

### ISSUE THREAD

**Issue by anjee10** [dbeaver/dbeaver#12750]
#### System information: 
- Operating system (distribution) and version: 11.2.3 (20D91)
- DBeaver version: 21.0.0 (community, installed from dmg file)
- Additional extensions

#### Describe the problem you're observing:
- Whenever I do update Mac OS, it removes some rows from my all tables those recently added (in last one or couple of months)

#### Steps to reproduce, if exist:
- I am not sure if this is reproducible, but I have witnessed this two times so far
- keep open DBeaver and update Mac OS to next available version
- also DBeaver is due to update to it's latest available version while updating Mac OS version
- when Mac OS updated, look for recent entries in any table. In my case, they got removed, and database is in state of some previous date (this date might be the same date last time I updated DBeaver or Mac OS version)

**Comment by kseniiaguzeeva** [comment]
Could you please provide me with more details:
- Do you use manual or auto-commit mode?
- What database do you use?
- Is your database local?
It will help me to assess the issue.

**Comment by anjee10** [comment]
@kseniiaguzeeva 
- Do you use manual or auto-commit mode?
  - auto-commit mode
- What database do you use?
  - PostgreSQL
- Is your database local?
  - yes, in local only

**Comment by kseniiaguzeeva** [comment]
DBeaver is a database tool and database data is saved on a server side after you save it in DBeaver. Could you please check whether unsaved changes were in a table, when you closed DBeaver? When DBeaver is going to be closed, Save changes confirmation pop up appears and you can select save or not to save the changes.

![Screenshot 2021-06-08 at 15 35 24](https://user-images.githubusercontent.com/51405061/121185945-3e796400-c86f-11eb-930a-00f52a44f67c.png)

**Comment by anjee10** [comment]
@kseniiaguzeeva thanks for looking into this!

I checked every time if data persisted in database or not, every time I tend to save it if I do manual edits.

First I doubted on DBeaver upgrades doing this, but i just updated once after using DBeaver before ~4 months, last I updated DBeaver is right after recent data loss (before couple of days), so no updates to DBeaver in between when data loss happened.

I should have added my usage of DBeaver as local database server before:
- I installed DBeaver in my local as local database server, to use PostgreSQL
- I setup one local database
- I keep this DBeaver instance open for long time with other applications
- I do not interact with DBeaver much, no frequent manual inserts or updates, if I do manual edits, I make sure to persist them in DB
- Most interaction to DBeaver is through my local development application, who talks to PostgreSQL and persists all data
- When Mac OS alerts me on new version available to install, I generally tend to ignore it as I need to boot all again
- Sometime I do manually update Mac OS, and it seemed fine with DBeaver, having no loss of data, but I noticed when Mac OS updates by itself overnight, next morning I see data loss in my PostgreSQL database. And I can confirm this happened more than one time in last 6 months.
- I generally keep open my 
  - VS code
  - DBeaver with no extra extensions
  - terminal having multiple tabs, having some background process running (my work's application)
  - chrome browser having multiple tabs
  - chrome browser in incognito mode
  - Microsoft Teams
  - postman app
  - notes app
  - finder app

As I said before, this is hard to reproduce, but I elaborated my way of working with Mac OS and DBeaver as above if it gives any clue.

**Comment by kseniiaguzeeva** [comment]
Could you please give me more details about tables, where data is lost: 
-  its DDL
- data example
- do you add rows via Data Editor or use another way?

**Comment by anjee10** [comment]
@kseniiaguzeeva 
- I can't share exact DDL, but  it's simple one, having few foreign key constraints, few create index things, fields having default values, nothing else
- you can take any data. For my case, it's not having any special char thing or any other encoding
- 99.99% I do not add any rows via Data Editor, it's always through angular/NodeJS application I am developing

I can make sure on data integrity, it's always persisted, in good state.

One more thing, last 

Other thing I can add to this, whenever table grows to some rows (not sure on size and not sure on how many rows), but just my assumption only), this happens may be, as recent overnight update of mac on Thursday night, didn't cause any data loss in DBeaver as DB size is already truncated by previous overnight mac os update!

**Comment by kseniiaguzeeva** [comment]
Thank you for the details. Looks like an issue on another side. DBeaver sends all changes to a database after commiting them. Could you please look for a reason on Mac, database or your application side?

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on issue for a long time. If it is still actual for you - feel free to reopen it
