### ISSUE TITLE
SqlServer FK between two schemas doesn't show on UI

### ISSUE THREAD

**Issue by m4ss1m0g** [dbeaver/dbeaver#12765]
#### System information: 
- Operating system: **Windows 10 Version 21H1 Build 19043.1023**
- DBeaver version **21.1.0.202105300349** Community
- Additional extensions 
  DBeaver Git support	1.0.46.202106012023	org.jkiss.dbeaver.git.feature.feature.group	DBeaver Corp
  DevStyle (includes Darkest Dark Theme)	1.11.0.202105260439	com.genuitec.eclipse.theming.core.feature.feature.group	Genuitec, LLC

#### Connection specification:
- Database name and version: **SqlServer Express Microsoft SQL Server 2017 (RTM-GDR) (KB4583456) - 14.0.2037.2 (X64)   Nov  2 2020 19:19:59   Copyright (C) 2017 Microsoft Corporation  Express Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19043: ) (Hypervisor)**
- Driver name **SQL Server**
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  **No**

#### Describe the problem you're observing:
Creating foreign keys between two tables on two different schemas via UI or SQL Script does not show it on Foreign Keys Tab/SubGroup neither on the DDL source tab.

#### Steps to reproduce, if exist:
1. Create a SQL Server database 
2. Create two schemas
3. Create TableOne on schema1
4. Create TableTwo on schema2
5. Create FK from TableTwo to TableOne
6. If you create FK with UI from the Foreign Keys tab when click persist the FK disappear (but is still present on DB)
7. Execute the query `select * from sys.objects` to verify that the object is successfully created

**Comment by ShadelessFox** [comment]
Thanks for the report.

**Comment by uslss** [comment]
verified
