### ISSUE TITLE
too hard to find this control element 

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#12768]
v21.0.3

![image](https://user-images.githubusercontent.com/799021/121095553-2f57cf00-c7f9-11eb-984f-e119be9300b3.png)

I occasionally press this button and it was too hard to find what was clicked and get interface back to this view:

![image](https://user-images.githubusercontent.com/799021/121095706-8067c300-c7f9-11eb-8b82-3ae57c62f604.png)

**Comment by kseniiaguzeeva** [comment]
We will try to improve the controls in future milestones. As a workaround could you please double-click a Resultset tab? It will collapse/expand it.

**Comment by KES777** [comment]
nope, it hides event those points )
