### ISSUE TITLE
Multiple Titles for multiple tabs not working

### ISSUE THREAD

**Issue by Glooomster** [dbeaver/dbeaver#12778]
I'm sorry if this is in wrong place but could only found similar issue with closed status but this feature seems to still have issues. 
#### System information: 
- Windows 10 Enterprise /2004 version
- DBeaver version: Version 21.1.0.202106012023

#### Describe the problem you're observing:
I'm trying to use multiple results on single query script.  Using **Title** to differentiate between the result tabs. 
Title or Name work fine if you have just one result. Once we have multiple results this feature always pickup the first title and all subsequent query result are called the same. 

Example:
-- title: First Script 
select '1' as name;
-- title: Second Script
select '2' as name;

When this is executed you would expect to see 2 tabs as result. 

- First result tab called First Script with result name / 1
- Second result tab called Second Script with result name / 2

But the result tabs come back with tabs named : 

- First Script 1
- First Script 1(2) 

Any additional script will be just adding extra +1 to the bracket (Example 3 result would be First Script 1(3) )
See attached files.
![result1](https://user-images.githubusercontent.com/85561057/121187961-85ac2880-c860-11eb-83a5-f2ac67b161f5.png)
![result2](https://user-images.githubusercontent.com/85561057/121187975-8a70dc80-c860-11eb-9bc9-f625fe1256fc.png)

#### Steps to reproduce, if exist:
Create new script against SQL server instance
`
-- title: First Script 
select '1' as name;

-- title: Second Script
select '2' as name;
`
Execute script

#### Closed related bugs
Setting result panel title in query script #3151
#3151

**Comment by kseniiaguzeeva** [comment]
You describe the expected behaviour. DBeaver names ResultSet tabs Results (1), Results (1) etc. when you execute expressions as a [script](https://github.com/dbeaver/dbeaver/wiki/SQL-Execution) (Alt+X). It helps to understand that they belong to one script.
When you execute expressions separately (Ctrl+Enter), they appear in tabs with different names. 
The feature was implemented several releases before.

**Comment by Glooomster** [comment]
Hi @kseniiaguzeeva ,
Thanks for the quick response. 
It seems that when I execute Ctrl+Enter (Execute SQL Statement) they are all showing as Result 1 , result 1(2)
But when execute with ALT+X (Execute SQL Script) they are showing with each different name. 

I will just start using ALT+X going forward thank you for your help.
