### ISSUE TITLE
Column not Updated on Properties Tab

### ISSUE THREAD

**Issue by RedTailedHawk** [dbeaver/dbeaver#12779]
I originally thought this was specific to column defaults, but looks like adding a new column to the table is not refreshed on the Properties tab either.

Running MacOS v11.2.3, DBeaver Version 21.1.0.202106012023, using Postgres.

```
CREATE TABLE test (
    id SERIAL NOT NULL,
    name VARCHAR(30) NULL,
    PRIMARY KEY (id)
);
```

![image](https://user-images.githubusercontent.com/8505928/121194269-98ad0180-c83c-11eb-9cea-245b1d1cff24.png)

Now I run this:

```
ALTER TABLE test 
  ADD COLUMN test CHAR(1) NOT NULL DEFAULT 'x'
```

And if I close down the `test` table tab and reopen, the new column is not shown.

![image](https://user-images.githubusercontent.com/8505928/121194504-c98d3680-c83c-11eb-9f18-6ccc4c410822.png)

The `Invalidate/Reconnect` context menu option does not work around this, but exiting out of DBeaver and coming back in does.

![image](https://user-images.githubusercontent.com/8505928/121195064-49b39c00-c83d-11eb-940d-6b16837409ea.png)

Same problem with editing the default.

```
ALTER TABLE lparker_test ALTER COLUMN test SET DEFAULT 'y';
```

Still shows default value of 'x' for the 'test' column.

![image](https://user-images.githubusercontent.com/8505928/121195299-7b2c6780-c83d-11eb-8cc7-dd188555293b.png)

**Comment by Matvey16** [comment]
Thank you for the bug report. We will look into it.

**Comment by Matvey16** [comment]
Related to #12547

**Comment by Matvey16** [comment]
For now you can use a workaround to refresh (F5) Navigator tree or click Disconnect and then Connect in menu.
