### ISSUE TITLE
Let us Stop Queries in 1 click!

### ISSUE THREAD

**Issue by robarwebservices** [dbeaver/dbeaver#12782]
The default workflow to stop a running query is insane. 3 clicks. 

1. click this: 
 ![image](https://user-images.githubusercontent.com/334314/121206705-137f1800-c84f-11eb-9f24-6f4a702961b4.png)
2. click this:
 ![image](https://user-images.githubusercontent.com/334314/121206838-2bef3280-c84f-11eb-91b7-901b2418e2f6.png)
3. Wait for the Execution Error pop-up???  WHY!  Close it (either ESC or click X)
 ![image](https://user-images.githubusercontent.com/334314/121207010-50e3a580-c84f-11eb-8648-e95f76516dc2.png)

The friction here is INSANE!

Look at SQL Server management studio. Just show a "stop" button somewhere in the header nav bars, let me click it, and when I do, just let it stop the query. NO POP UP! Please!

**Comment by kseniiaguzeeva** [comment]
Could you please disable option **Always run in background** in Preferences>General?
![dbeaver_igXtbxLszN](https://user-images.githubusercontent.com/51405061/122224773-1c11c700-cebd-11eb-8569-64f7b81c1599.png)

![dbeaver_YO25Vdja1T](https://user-images.githubusercontent.com/51405061/122225108-701cab80-cebd-11eb-84c6-8d97c93de6c2.png)
