### ISSUE TITLE
Metadata tab not refreshing after second query execution

### ISSUE THREAD

**Issue by velteyn** [dbeaver/dbeaver#12790]
#### System information: 
- Operating system (distribution) and version
- Edizione	Windows 10 Pro
Versione	20H2
Data installazione:	‎15/‎03/‎2021
Build sistema operativo	19042.985
Esperienza	Windows Feature Experience Pack 120.2212.2020.0

- DBeaver version  21.1.0
- Additional extensions

#### Connection specification:
- Database name and version
-DB" AS/400
- Driver name com.ibm.as400.access.AS400JDBCDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
Metadata tab not refreshing after second query execution
#### Steps to reproduce, if exist:
1) Execute a Query A --> the metadata is displayed
2) Execute a query B --> The metadata remains fixed with the data from Query A (Step1)
3) After executing query B again the metadata is refreshed
I think this is  a REGRESSION because older versions of DBeaver where working as I expect. (Metadta refreshed for any query)

**Comment by uslss** [comment]
thanks for the report.
Issue will be fixed in 21.1.1 in the scope of #11639 ,
