### ISSUE TITLE
Interval type is wrongly mapped during data transfer

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12791]
#### System information: 
- DBeaver version Win10

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
Export a table with an interval data type to a new table

**Expected**: the data types are identical in the new table
**Actual result**: interval types are mapped as Varchar

![dbeaver_X4EWpf5Hb6](https://user-images.githubusercontent.com/51405061/121354380-7fd54680-c937-11eb-98c4-bbab7c6ef3d3.png)

**Comment by uslss** [comment]
fixed in the scope of #12142
