### ISSUE TITLE
Cannot refresh table metadata

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#12795]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 21.1.0
- Additional extensions n/a

#### Connection specification:
- Database name and version Oracle 11, sql server 2016
- Driver name ojdbc 19, ms driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? n.a.

#### Describe the problem you're observing:
In the table editor, while visiting any tab different from the data tab (e.g. Columns, Constraints, etc), the refresh button at the bottom is useless (i cannot see edits I made outside dbeaver). Same effect if I use F5 while in those tabs.

Looking at query browser, the only query I see when I click refresh is a query on the table *data* (e.g. select * from table).
Metadata queries are run when I first open the table, but never repeated.

The only way to actually refresh metadata is by using F5 on the database navigator. As far as I can see, this happens on all object types and all databases (tested Oracle and Sql Server)

#### Steps to reproduce, if exist:

1. Open a table with the table editor
2. Go to Properties -> Columns
3. Add a column with sql editor (e.g. running manually a script like ALTER TABLE X ADD Y NUMBER;)
4. refresh with the button at the bottom left or with f5 -> nothing changes
5. refresh the table in the database navigator -> the new y column appears in both navigator and table editor.

**Comment by Matvey16** [comment]
Probably related to #12779 and #12547

**Comment by LonwoLonwo** [comment]
Was fixed here: https://github.com/dbeaver/dbeaver/issues/12899
