### ISSUE TITLE
There is no color-scheme chooser

### ISSUE THREAD

**Issue by MikePryadko** [dbeaver/dbeaver#12805]
![image](https://user-images.githubusercontent.com/31248040/121512396-56c5bc00-c9f2-11eb-8ff7-4a581b911b69.png)

![image](https://user-images.githubusercontent.com/31248040/121512440-634a1480-c9f2-11eb-95c3-4446924e63cd.png)

There is no opportunity to choose/select any color-scheme:
![image](https://user-images.githubusercontent.com/31248040/121512705-ab693700-c9f2-11eb-9889-3eebaa2659ea.png)

Here in issues I see many screenshot with another menu structure and with "dark theme" chooser :neutral_face: Is it joke..?
Hey, it's 21th century - nobody will adjust colors by manual :dizzy_face:

**Comment by uslss** [comment]
Hi @MikePryadko ,
Color scheme could be changed in Preferences
![image](https://user-images.githubusercontent.com/31996417/121515482-e6b93500-c9f5-11eb-9425-f5e1043cc3b5.png)

**Comment by MikePryadko** [comment]
@uslss thank!
I was needed color schemes for editor, not for interface, so I've done following:
1. Check `Enable theming`
2. Restart DBeaver (because after enabling theming a list with themes doesn't appeared)
3. Install "_DevStyle (includes Darkest Dark Theme)_" (to get any themes)
4. Go `Preferences` -> `User Interface `-> `Appearance` and select `DevStyle Theme`
5. Go to `Preferences` -> `DevStyle` -> `Color Themes` and select `IntelliJ IDEA Dark`
6. Final restart

![image](https://user-images.githubusercontent.com/31248040/121520715-e885f700-c9fb-11eb-8f2a-113274d27748.png)

**P.S.** I'd like to use "system" color scheme for toolbar/menus/etc., but in that case a DevStyle theming isn't available :disappointed:
