### ISSUE TITLE
Unable to Use Dbeaver variables

### ISSUE THREAD

**Issue by boyapcha** [dbeaver/dbeaver#12806]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

@set schema_environment = 'development'

select  international_exchange, cusip_number from ${schema_environment}_raw_pershing.isca_j where
international_exchange = 'TOR'

I defined a variable as shown above. I want to modify the variable value as and when I switch different connections and populate the correct environment. But When I use this variable as part of schemaname/table name I am getting below error. I only want to pass variable into partial value of my table/schema name as above. Please help.
Dbeaver Version : 21.0.5

ERROR:
SQL Error [100071] [HY000]: [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. line 1:51: mismatched input ''development''. Expecting: '(', 'LATERAL', 'UNNEST', <identifier> [Execution ID not available]

#### Steps to reproduce, if exist:
As explained above

**Comment by Matvey16** [comment]
Hello. Thank you for the report. I reproduced this issue, although I got a different error. Please try executing this script but with `schema_name.${variable}rest_of_table_name`

**Comment by boyapcha** [comment]
Hi Matvey16,

Thanks for the response. For me the problem is my schema name itself has partly variable name. Table name is same.
Only part of schema name comes from variable like below.

@set schema_environment = 'development'

from ${schema_environment}_raw_pershing.isca_j

I am getting below error:
SQL Error [100071] [HY000]: [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. line 1:51: mismatched input ''development''. Expecting: '(', 'LATERAL', 'UNNEST', <identifier> [Execution ID not available]

**Comment by Matvey16** [comment]
Ok. I will ask you to first try using `@set schema_environment = development` please note there are no quotes and no Semicolon at the end.

If this workaround doesn't work please post the execution log of the query that is causing the error.

![2021-06-11_09h36_09](https://user-images.githubusercontent.com/82543000/121642519-4ddbf580-ca99-11eb-8414-a17f2cce6436.png)

**Comment by boyapcha** [comment]
This is working. Thank you so much

**Comment by mathmul** [comment]
### Immediate edit

Sorry, I'll leave this here for future reference, but my issue is due to my own stupidity.

I clicked the "Execute SQL query" button, which only ran the select statement. I should have instead clicked the "Execute SQL script" button, which runs all lines including `@set` statements which fill up "Variables" panel.

### Original question

Is this way of setting variables no longer supported?

In my testing database connection I created this script:
```sql
@set tenant = ok2me
@set transaction_id = d5843a46-3710-4eba-905e-c5b205ef5422

select ${tenant}.ep_merchant_pointofsale.company
from
	${tenant}.ep_transaction_transaction inner join
	${tenant}.ep_merchant_device on ${tenant}.ep_transaction_transaction.device = ${tenant}.ep_merchant_device.id inner join
	${tenant}.ep_merchant_pointofsale on ${tenant}.ep_merchant_device.point_of_sale = ${tenant}.ep_merchant_pointofsale.id
where
	${tenant}.ep_transaction_transaction.id = ${transaction_id};
```

When I try to run it it ignores the `@set` variables and opens a popup for me to use dynamic variables:

<img width="1188" alt="Image" src="https://github.com/user-attachments/assets/5bcffbb5-4b17-449c-bfa0-2d72ba1edb59" />
