### ISSUE TITLE
Athena: SQL Editor disregards selected active schema when executing query

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#12807]
#### System information: 
- Operating system (distribution) and version Ubuntu 20.04
- DBeaver version 21.1.0
- Additional extensions

#### Connection specification:
- Database name and version Athena

#### Describe the problem you're observing:
SQL Editor runs script with default schema name despite choosing another as active

#### Steps to reproduce, if exist:
1. Chose a not default schema as active in SQL Editor
2. Run an SQL script without defining schema name `select * from Table_name` for table from active schema.

**Expected:** Result is shown in ResultSet.

**Actual:** Error is thrown.

![ksnip_20210610-174548](https://user-images.githubusercontent.com/82543000/121546356-e6c82d80-ca13-11eb-9f4a-7b220637cdf3.png)

![ksnip_20210610-174654](https://user-images.githubusercontent.com/82543000/121546374-e9c31e00-ca13-11eb-96d1-9fa3544fe543.png)

**Comment by Matvey16** [comment]
Can be related to #12806

**Comment by uslss** [comment]
Duplicates #11196
