### ISSUE TITLE
passing variable in s3 location while connecting to Athena using Dbeaver

### ISSUE THREAD

**Issue by boyapcha** [dbeaver/dbeaver#12816]
#### System information: 
- Operating system (distribution) and version
- DBeaver version -- 21.0.5
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
S3 location :  s3://aws-athena-query-results-us-east-1/dbeaver/chandra_boyapati/${date}/

is it possible to provide current date in s3 path dynamically while connecting to dbeaver ?
${date} is not working as I tried above

**Comment by LonwoLonwo** [comment]
Implemented in DBeaver 21.2.5

![2021-10-27 19_07_44-DBeaver Ultimate 21 2 4 - xml_data](https://user-images.githubusercontent.com/45152336/139834944-3bc3c923-b6ec-41d9-a20c-bbcfc034983c.png)

**Comment by uslss** [comment]
verified
