### ISSUE TITLE
DBeaver title isn't update on script opening

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#12818]
#### System information: 
- Operating system (distribution) and version win10x64
- DBeaver version 21.1.0

#### Describe the problem you're observing:
<none> connection is shown in application title in case of opening script associated with some connection
#### Steps to reproduce, if exist:
1. Link an sql file
2. Associate the file with a connection
3. Double-click the file to open it
 What does happen: the sql tab shows the connection ("MSDW2 PROD Lea … ") but and the DBeaver window does not ("<none>")
 What should happen: both the sql tab and DBeaver window should show the connection, in this case "MSDW2 PROD Lea … "
![image](https://user-images.githubusercontent.com/31996417/121657455-170ddb80-caa9-11eb-84ef-1bd59f990d7e.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
