### ISSUE TITLE
Incorrect query generated by dbeaver prevents saving an edit through datagrid

### ISSUE THREAD

**Issue by vincent-ng-sgn** [dbeaver/dbeaver#12812]
#### System information: 
- macOS 10.14.3
- DBeaver 21.1.0

#### Connection specification:
- Postgresql 12.5

#### Describe the problem you're observing:

Incorrect query generated by dbeaver when editing through datagrid when using non-public schema enum as primary key in table. Generated query isn't schema qualified.

#### Steps to reproduce, if exist:

1) create sample data: 

CREATE SCHEMA my_schema

CREATE TYPE my_schema.colors AS ENUM (
	'black',
	'blue',
	'brown');

CREATE TABLE my_schema.test_table (
	color my_schema.colors NOT NULL,
	color_name varchar NULL,
	CONSTRAINT test_table_pk PRIMARY KEY (color)
);

INSERT INTO my_schema.test_table (color,color_name)
	VALUES ('black','Black')

2) open table in dbeaver and edit color_name:

![image](https://user-images.githubusercontent.com/17283132/121614037-afa54c80-ca12-11eb-9d1a-0aac1aa8e4a3.png)

3) click Save; get Data error

![image](https://user-images.githubusercontent.com/17283132/121614072-cb105780-ca12-11eb-8b76-68fb8c151458.png)

Notes:
- issue is the generated query isn't schema qualified (i.e. with 'my-schema'); dbeaver generated query: UPDATE my_schema.test_table
	SET color_name='Black2'
	WHERE color='black'::colors
- both these modified queries work in sql editor: 
   a) UPDATE my_schema.test_table
	SET color_name='Black2'
	WHERE color='black'::my_schema.colors
   b) UPDATE my_schema.test_table
	SET color_name='Black2'
	WHERE color='black'

**Comment by uslss** [comment]
thank you for the report
as a workaround you can set your schema as default. In this case it will work ok
![image](https://user-images.githubusercontent.com/31996417/121658993-89cb8680-caaa-11eb-8dbc-c49b9dcbfcf8.png)

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.1.4
Now we add schema name to custom data type name in the statement.

**Comment by Matvey16** [comment]
Double cast is shown if opening a generated script before saving

![dbeaver_HMQTwSK2DA](https://user-images.githubusercontent.com/82543000/126306645-a801e8c1-e781-41cc-94e2-a09ca409eea2.png)

**Comment by Matvey16** [comment]
Verified
