### ISSUE TITLE
postgresql udf parameter use VARIADIC anyarray have some problem 

### ISSUE THREAD

**Issue by cooltnt** [dbeaver/dbeaver#12813]
#### System information: 
- Operating system (distribution) and version
- win10
- DBeaver version
- 21.1.0.202106012023
- Additional extensions

#### Connection specification:
- Database name and version
- postgresql 9.6
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
1 . use this code to create function, create success ,  can running, can modify,  but can't drop,  Prompt function not found.
    user is the owner

code: 
CREATE OR REPLACE FUNCTION public.andl(VARIADIC anyarray)
 RETURNS boolean
 LANGUAGE sql
AS $function$
.............
.............
$function$
;

Prompt：
![image](https://user-images.githubusercontent.com/41370387/121621275-72869c00-ca9e-11eb-9469-1f52a777bba2.png)

2.  I experimented and found:
(1)  use Navicat to connect to database, can drop this function( same user )
(2)  if create without keyword  VARIADIC ,   can drop function
      CREATE OR REPLACE FUNCTION public.andl(anyarray)

(3) in function tree , parameter is blank, if have VARIADIC
![image](https://user-images.githubusercontent.com/41370387/121622015-ca71d280-ca9f-11eb-9b0e-296443685a18.png)

So I guess， VARIADIC  make some mistake

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
verified
