### ISSUE TITLE
flatpak doesn't have crypto require for SSL 

### ISSUE THREAD

**Issue by Goddard** [dbeaver/dbeaver#12823]
I am on ubuntu and using the flatpak I get a cryptographic error.  I know it is a problem with flatpak because if I installed the DEB that comes in my repo it works fine.

I think maybe some library isn't included that's required.

I'm trying to connect to a MySQL database version 5.7 that requires SSL just for reference.

Thanks

**Comment by Matvey16** [comment]
Can you please provide more information. Like what DBeaver version you are using and when exactly this error occurs? Also please provide logs that you get after this error. It will help to narrow down the search.

**Comment by Goddard** [comment]
Sorry I moved on from the original format that the app was causing the issue.  I installed the deb.

But at the time of writing that post it was the latest flatpak that was released.  Sorry I can't be more helpful.

**Comment by LonwoLonwo** [comment]
Hello @Goddard 

Does this issue still actual for you in the last DBeaver release? DBeaver had many changes since 2021.

**Comment by E1izabeth** [comment]
It's been a while since no update here. Let me know if this issue is still actual.
