### ISSUE TITLE
Navigating table columns with up/down arrow key skips random columns

### ISSUE THREAD

**Issue by Mikajel** [dbeaver/dbeaver#12824]
#### System information: 
- Ubuntu Linux 21.04
- Version 21.1.0.202106012023
- uuid-ossp; plpgsql;

#### Connection specification:
- PostgreSQL 12
- Postgres
- Local database

#### Describe the problem you're observing:
Navigating table columns with up/down arrow key skips random columns.
I could not discover a pattern in the "jumps", neither types nor length name.
Jumps are stable.

#### Steps to reproduce, if exist:
1. Create a table with reasonable amount of columns with various names/types.
2. Open ER Diagram of table.
3. Select random column with mouse click.
4. Traverse up and down through column names with arrow keys.

**Comment by Matvey16** [comment]
Thank you for the report. This is reproduceble, so we will see if anything can be done.
Not database specific. Reproduceble in Oracle too

![2021-06-11_18h26_57](https://user-images.githubusercontent.com/82543000/121710859-aaafce00-cae2-11eb-8b8a-6291e6d2ab9e.gif) ![2021-06-11_18h33_54](https://user-images.githubusercontent.com/82543000/121711894-c23b8680-cae3-11eb-8749-1d62ed9d1865.gif)

**Comment by Matvey16** [comment]
Verified
