### ISSUE TITLE
DB-Full-Text search on PL-SQL code of function e procedure for ORACLE

### ISSUE THREAD

**Issue by amancini** [dbeaver/dbeaver#12838]
Hello,

please add supporto for search text on function and procedure by DB-Full-Text tools for ORACLE database

This function for example is present in software like DBArtisan by Embarcadero

best regards

**Comment by flambchap** [comment]
Hello @amancini. This functionality is already implemented in the _DB Metadata_ search. Please use _Search in definitions_ option to do that. 

![image](https://user-images.githubusercontent.com/26031301/139230108-bb9ecc4d-9db9-4ace-b3f0-08a50bf4c496.png)
