### ISSUE TITLE
FIlter field on top of data editor loses focus when data has been loaded.

### ISSUE THREAD

**Issue by lsieben97** [dbeaver/dbeaver#12837]
#### System information: 
- Windows 10 20H2 Build 1052
- DBeaver 21.0.4
- No additional extensions

#### Connection specification:
- Mysql 5 on internal (company) database.
- No tunnels or proxies. 

#### Describe the problem you're observing:
When I open a new data editor (by double-clicking on a table in the Database Navigator) the new data editor opens. when I start typing in the filter field at the top I notice when the data has been loaded (usually takes a few seconds) focus transfers to the first cell of the first row. when I don;t notice this I need to click the filter field to continue typing. This is very annoying.

Also, if you don;t notice that you've changed the first cell of the first row there's a good chance it might break something in the system using the database.

#### Steps to reproduce, if exist:
1.  Open a data editor
2.  Start typing immediately in the filter field on the top.
3.  when the data loads focus will shift to the first cell of the first row.
4. continue to type, all tet will end up in the first cell of the first row.

#### Include any warning/errors/backtraces from the logs
I don't have any warnings or errors in the error log panel.

**Comment by uslss** [comment]
thank you for the report

**Comment by flambchap** [comment]
Hi @lsieben97. Unfortunately, I can not reproduce your problem since we explicitly make the filter text field uneditable during the data load. I have a feeling that I don't understand the issue correctly. Could you please a screencast with the problem? That would be very helpful. Thank you.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual - feel free to reopen it with additional info
