### ISSUE TITLE
Cell value "set to default" not working if column default is NULL and many cells are selected

### ISSUE THREAD

**Issue by Thomas-1985** [dbeaver/dbeaver#12833]
#### System information: 
- Operating system (distribution) and version: Mac OS 11.3.1
- DBeaver version: 21.1.0.202106012023
- Additional extensions: none

#### Connection specification:
- Database name and version: MariaDB
- Driver name: MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: no

#### Describe the problem you're observing:
-I have a table where the default value of some columns is NULL. However, when i  right click on many cells in that column and select "edit", the only option i have is "set to default (empty string)". This makes no sense and it should be like "set to default (NULL)" since its the default

#### Steps to reproduce, if exist:
-Create a table with some columns which have the default value of NULL
-Populate the table with some data
-Click on a range of columns, right click and select "edit"

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
@Thomas-1985 ,
unfortunately, cannot reproduce it for now.
Could you provide a video of the issue? Table DDL also could be very helpful

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual - feel free to reopen it with additional info to reproduce the issue.
