### ISSUE TITLE
Error after using Find and Replace on Blob column, Firebird DB

### ISSUE THREAD

**Issue by timbered** [dbeaver/dbeaver#12832]
#### System information: 
- Operating system (distribution) and version: Win10 x65
- DBeaver version: Version 21.0.0.202103021012
- Java version: 1.8.0_261
- Additional extensions: None

#### Connection specification:
- Database name and version: Firebird 2.5
- Driver name: DBeaver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
I have an existing customer-supplied Firebird database. One column is data type BLOB SUB_TYPE TEXT. If I do any type of Find & Replace within the column, I can no longer save the changed records - I receive an Unsupported value type error

#### Steps to reproduce, if exist:
Open existing Firebird DB local file. Use Find & Replace to change text within a BLOB column. Click Save. Error will show Unsupported Value Type

**Comment by ShadelessFox** [comment]
Hello @timbered,

I cannot reproduce your issue.

Can you please provide more information and steps to reproduce? A video sample would be nice.

**Comment by Matvey16** [comment]
I reproduced it on column BLOB SUB_TYPE BINARY. Was not able to reproduce on sub_type text

![2021-06-15_13h48_03](https://user-images.githubusercontent.com/82543000/122040888-07f89780-cde1-11eb-95ec-6e25daccb9da.gif)

> org.jkiss.dbeaver.model.exec.DBCException: Unsupported value type: BBBBB
> 	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCContentValueHandler.bindParameter(JDBCContentValueHandler.java:121)
> 	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.bindValueObject(JDBCAbstractValueHandler.java:64)
> 	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable$2.bindStatement(JDBCTable.java:483)
> 	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:164)
> 	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.generatePersistActions(ExecuteBatchImpl.java:87)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:809)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.lambda$1(ResultSetPersister.java:697)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:696)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:634)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister.execute(ResultSetPersister.java:450)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister.applyChanges(ResultSetPersister.java:174)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.generateChangesScript(ResultSetViewer.java:3953)
> 	at org.jkiss.dbeaver.ui.controls.resultset.handler.SaveScriptDialog.lambda$1(SaveScriptDialog.java:209)
> 	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
> 	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by timbered** [comment]
Thank you for the response. My apologies for taking so long to respond. I've been swamped with client work this week.

It's quite possible it's something to do with the specific file I have. It's from a fairly old version of Firebird. When I open it, DBeaver shows the column as BLOB SUB_TYPE TEXT, but the icon shows for a regular BLOB.

I am able to share the file (it's from a US Federal software app that is publicly available) but in it's present state, it's just over 9MB.

What's the size limit here?

**Comment by ShadelessFox** [comment]
Hello again,

I believe in the past we had similar issues with specifically old versions of Firebird, so maybe in this case the problem has the same origin.

GitHub allows attachments up to 100MB, so you have a lot of room here :)

**Comment by timbered** [comment]
Attached is the gdb file. Zipped. it's only 1.3MB...

Specifically, the table I was working on is VIOLUS, and the blob column is DESCRIPTN. Some of the rows have CR LF within the text. I searched / replaced the CR LF in DBeaver (using [\r\n]+ as a regular expression.) Then, click Save, I get the Unsupported Value Type error. Manually editing the text is OK.

[Capriibdata.zip](https://github.com/dbeaver/dbeaver/files/6674281/Capriibdata.zip)

**Comment by ShadelessFox** [comment]
Thanks! I will take a look on it later.

**Comment by Matvey16** [comment]
Verified
