### ISSUE TITLE
[Oracle] Unnecessary comment on column syntax in alter table case. 

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#12846]
Steps:
Open persisted table with the column, which has at least one comment on the column.
Add a comment on the table or change tablespace
Click save
Expected script: ALTER TABLE...;
Actual script: ALTER TABLE...; COMMENT ON COLUMN IS...

![2021-06-15 17_40_55-ALBUM - Persist Changes](https://user-images.githubusercontent.com/45152336/122073261-f6bf8300-ce00-11eb-8df8-17d44845dbe5.png)

Generic table creation issue.
Steps:
Start to create table action via UI in DBeaver.
Add column
Add a comment on the column
Click to save

Expected SQL: create table + comment on the column is ...
Actual: only create table statement.

![2021-06-15 17_39_57-DBeaver Enterprise 21 1 0 - NewTable](https://user-images.githubusercontent.com/45152336/122073276-f9ba7380-ce00-11eb-9063-fbaa7e499023.png)

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.1.1

**Comment by uslss** [comment]
verified
