### ISSUE TITLE
CTRL+Enter switch language

### ISSUE THREAD

**Issue by eyallibarak** [dbeaver/dbeaver#12855]
With DBeaver Version 7.2.3.202010191702
and also with latest Version 21.1.0.202106012023
Windows 10 Pro

Whenever I hit CTRL+Enter to execute a query - the system (keyboard) language is changed from English to Hebrew.
Quite annoying.

**Comment by Matvey16** [comment]
Are your Windows settings configured to change language on CTRL+Enter or do you have a utility that does so? If yes, than you can change the shortcut either in your system or in DBeaver.
![2021-06-16_10h05_44](https://user-images.githubusercontent.com/82543000/122173560-852c1700-ce8a-11eb-89fc-4438b0c2be58.png)

**Comment by eyallibarak** [comment]
Nah, it only happens when I'm in DBeaver and focus is in the editor

**Comment by Matvey16** [comment]
I can't reproduce it on my Win10. Can you provide more information about your environment? Do you have any utilities running in the background that can operate with text input or keyboard? Maybe some special utility from keyboard manufacturer?

**Comment by eyallibarak** [comment]
I've now changed the shortcut to something completely different, CTRL+SHIFT+D and it still changes the language when I hit it. So it's surely not anything outside of DBeaver that's catching the key combination.

**Comment by Matvey16** [comment]
Thank you, we will look into it.

**Comment by Matvey16** [comment]
@eyallibarak Did you change it to CTRL+SHIFT+D  in Dbeaver or in Windows? Are you sure you don't have some keyboard layout or shortcut control utilities like Punto Switcher, Mahou, Key Switcher and such? Or special utility from your keyboard manufacturer?

**Comment by eyallibarak** [comment]
I changed to CTRL+SHIFT+D in DBeaver. 
I just tested turning the windows hot key off for input/keyboard layout, and DBeaver still changes the input language.

**Comment by Matvey16** [comment]
And what about other utilities? Are you sure there is nothing hidden in your tray that you may have forgotten was even there?

**Comment by eyallibarak** [comment]
Yeah I'm sure. Also, the change of hot key in DBeaver eliminated this possibility.

**Comment by Matvey16** [comment]
@eyallibarak Sorry for the late response. If a simple mouse click to execute query doesn't change the keyboard layout than it is very unusual that this happens with a use of a shortcut because it's only use is to run the same command as a ui button.
Unfortunately we can't fix it without an exact environment to reproduce it.

**Comment by eyallibarak** [comment]
Then how do you explain it happening even when I change the key combination?

Here's another finding from today - the problem stopped happening for 2 days, so today I did alt+shift to change to Hebrew while focused on the editor, then the problem started happening again. If I'm in English it switched to Hebrew. If I'm in Hebrew it switches twice fast to En and back to He.

Also - if I disable the hotkeys completely in windows settings - this still happens.

Pressing ctrl+enter in any other window won't trigger a change to He.

**Comment by eyallibarak** [comment]
Wow! I found the problem!

This happens only if the query has a string with Hebrew text (i.e. where name like '%אורי%')

**Comment by uslss** [comment]
unfortunately, still cannot reproduce an issue. Could you provide a video of an issue?

sorry for the late response

**Comment by eyallibarak** [comment]
Now with version 21.1.5.202108160727 the issue is gone.

Noticed something new maybe (good new functionality?) - given a select like this:
select * from interest i where interestType like "%ניסיון%"
 - when the carret is on the Hebrew word,  the input language is changed to Hebrew, and when moved elsewhere (or in other application windows) changes back to English.
