### ISSUE TITLE
Advanced copy - Copy as JSON - timestamps are not copied as is

### ISSUE THREAD

**Issue by selalerercapitolis** [dbeaver/dbeaver#12858]
#### System information: 
- Operating system (distribution) and version - Ubuntu 20
- DBeaver version - 21.1.0
- Additional extensions - no

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
After copying row as JSON and pasting somewhere the timestamp fields are not as in the DB (maybe adjusted to timezone or something of that sort)

#### Steps to reproduce, if exist:
Right click on a row in the table data view and select Advanced Copy then select Copy as JSON

Then paste the data somewhere (e.g. gedit)

**Comment by Matvey16** [comment]
Hello and thank you for the report. Can you please provide an example of how a timestamp looks in data tab and how it looks in text editor after copying as JSON so the difference would be visible?

**Comment by selalerercapitolis** [comment]
@Matvey16 Thank you for the quick response. Here is a record copied to XML (which works without this problem):
```
<scheduled_events>
  <DATA_RECORD>
    <id>f36781b3-f0d6-4b56-a470-9f9b9e3577cb</id>
    <created_at>2021-06-16 07:19:11</created_at>
    <updated_at>2021-06-16 08:10:58</updated_at>
    <from_time>2021-06-16 06:30:00</from_time>
    <to_time>2021-06-16 07:00:00</to_time>
    <timezone>Europe/London</timezone>
    <from_utc>2021-06-16 05:30:00</from_utc>
    <to_utc>2021-06-16 06:00:00</to_utc>
    <type>COMPRESSION</type>
    <created_by_party_id>20,056</created_by_party_id>
    <created_by_user_id>1,771</created_by_user_id>
    <comment></comment>
    <deleted>true</deleted>
    <event_happened>false</event_happened>
    <linked_entity_id></linked_entity_id>
  </DATA_RECORD>
</scheduled_events>

```
And here it is copied as JSON:
```
{
"scheduled_events": [
	{
		"id" : "f36781b3-f0d6-4b56-a470-9f9b9e3577cb",
		"created_at" : "2021-06-16T04:19:11.114Z",
		"updated_at" : "2021-06-16T05:10:58.823Z",
		"from_time" : "2021-06-16T03:30:00.000Z",
		"to_time" : "2021-06-16T04:00:00.000Z",
		"timezone" : "Europe\/London",
		"from_utc" : "2021-06-16T02:30:00.000Z",
		"to_utc" : "2021-06-16T03:00:00.000Z",
		"type" : "COMPRESSION",
		"created_by_party_id" : 20056,
		"created_by_user_id" : 1771,
		"comment" : null,
		"deleted" : true,
		"event_happened" : false,
		"linked_entity_id" : null
	}
]}
```
As you can see there is a 3 hours difference. 
It is probably not a coincidence that my machine timezone is +03 (IDT):
```
$ timedatectl | grep "Time zone"
                Time zone: Asia/Jerusalem (IDT, +0300)

```

**Comment by Matvey16** [comment]
Also can you please add what database are you using?

**Comment by selalerercapitolis** [comment]
> Also can you please add what database are you using?

Sure, I use PostgreSQL and this is the result of select version():
`PostgreSQL 11.4 (Debian 11.4-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit`

**Comment by Matvey16** [comment]
Is the timezone on your Database server the same as on your machine?

**Comment by selalerercapitolis** [comment]
> Is the timezone on your Database server the same as on your machine?

Yes:
```
"SELECT * FROM pg_timezone_names WHERE name = current_setting('TIMEZONE')": [
	{
		"name" : "Asia\/Jerusalem",
		"abbrev" : "IDT",
		"utc_offset" : "03:00:00",
		"is_dst" : true
	}
]}
```
(I used the Copy As JSON feature :-) )

**Comment by Matvey16** [comment]
Ok, so judging by the code returned in JSON `2021-06-16T04:19:11.114Z` where `Z` stands for UTC, so it is actually the correct time (you were right, it's not a coincidence that your time zone is +3. Are those timestamps generated by functions? If so, that may be the case. They are inserted into a database in this format, but Dbeaver UI shows them adjusted to your time zone in readable form.

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If the issue is still actual - feel free to reopen it
