### ISSUE TITLE
When DDL is generated, comments doesn't have a semicolong at the end

### ISSUE THREAD

**Issue by renezito** [dbeaver/dbeaver#12850]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro 21H1
- DBeaver version: 21.1.0
- Additional extensions: ¿Extensions in dbeaver? If that then none.

#### Connection specification:
- Database name and version: Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
- Driver name: Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When DDL is generated, the comments doesn't include the ";" (semicolon) at the end of each comment.
#### Include any warning/errors/backtraces from the logs

![20210615 dbeaver comentarios sin punto y coma al final](https://user-images.githubusercontent.com/37661233/122118448-07b6c700-cdf6-11eb-9e84-6bc8e74390cd.jpg)

**Comment by Matvey16** [comment]
Thank you for the report

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.1.1

**Comment by Matvey16** [comment]
Verified

**Comment by renezito** [comment]
Thanks!!!
