### ISSUE TITLE
Github Wiki has a different version as dbeaver.com

### ISSUE THREAD

**Issue by Falke-Design** [dbeaver/dbeaver#12857]
For Example the Point 4 has a different Url on Github as the Wiki on dbeaver.com:

GitHub:
https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse

dbeaver.com:
https://dbeaver.com/docs/wiki/Develop-in-Eclipse/

The Github Version `http://eclipse-color-theme.github.io/update` with `...github.io` is correct

**Comment by LonwoLonwo** [comment]
Hello @Falke-Design 
Thank you for your attention. Usually, the site is updated with a small delay after a change in GitHub. We updated the website today.
Now, https://dbeaver.com/docs/wiki/Develop-in-Eclipse/ is with the correct link.
