### ISSUE TITLE
"dbeaver-ce" has bad plugs or slots: dbus in ubuntu 20.04

### ISSUE THREAD

**Issue by rafiahmad16** [dbeaver/dbeaver#12859]
#### System information: 
- Operating system (distribution) and version
- `cat /etc/*-release`
- `DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal`
- DBeaver version
- `21.1.0.202106012023`
- Java version 
- `java -version`
- `openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
`

#### Steps to reproduce, if exist:
`snap warnings`
`warning: |
  snap "dbeaver-ce" has bad plugs or slots: dbus (cannot find attribute 'bus')`

**Comment by riednyko** [comment]
Fixed. Try to update dbeaver-ce snap package.
