### ISSUE TITLE
Snowflake Token Caching Requires new jna dependencies

### ISSUE THREAD

**Issue by py-prash** [dbeaver/dbeaver#12869]
Sometime back snowflake released a feature for SSO browser authentication, which would minimize the number of browser pops, wherein the token was cached locally. Everything was working fine until snowflake jdbc version 3.12.17. Till then, they used to package the JNA classes in the jar file. From 3.13.x onwards, Snowflake no longer package the JNA classes(https://mvnrepository.com/artifact/net.java.dev.jna/jna-platform) in the jar file. This requires users to manually add those artifacts in dbeaver. This could get cumbersome for non-tech savvy users.
Is there a way that these JNA dependencies can be added by default going forward?

dbeaver version: 21.1.0
snowflake jdbc: 3.13.0 and later

**Comment by Matvey16** [comment]
We will implement it

**Comment by serge-rider** [comment]
JNA added to driver dependencies

**Comment by Matvey16** [comment]
@py-prash Hello, we don't have the appropriate environment to test it entirely. Can you try our latest early access version and verify if the issue is resolved
https://dbeaver.io/files/ea/

**Comment by Matvey16** [comment]
@py-prash Please reopen this ticket if your issue will persist.
