### ISSUE TITLE
Typing text does not delete selected

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#12860]
### System information: 
- Linux mint 19.3
- 21.0.3

#### Describe the problem you're observing:
When I select text and start typing then selected text is not deleted.

#### Steps to reproduce, if exist:
1. Type `abcd`
2. Select `abcd`
3. Type `'x`
Expected: `'x'`
Actual: `'xabcd'

**Comment by Matvey16** [comment]
It is working as intended. When you select text and type either `'` or `"` it wraps the selected text in quotes. If you select text and start typing other text it will be deleted.

**Comment by Matvey16** [comment]
You can disable this option in preferences

![2021-06-16_16h47_05](https://user-images.githubusercontent.com/82543000/122230717-909b3480-cec2-11eb-8ee3-edcdc97f746a.png)

**Comment by KES777** [comment]
this is inconsistent, at lease as other editors work.

If you change behavior for quotes then why you do not change it for other quotes? `, [, (, { etc.

Is there a way to disable this behavior?

Also notice, I still want to use autoclose feature, I just blame how it works with selection
