### ISSUE TITLE
Hide length column for postgres attributes

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#12878]
Since #12142 we no longer display precision and scale since they're embedded in the type name itself.
The same is applied to the length, but in order to to be consistent we should hide <kbd>Max Length</kbd> column too.

**Comment by ShadelessFox** [comment]
Implemented. The length is displayed within type name for character types (e.g. `varchar(50)`), as in #12142

**Comment by Matvey16** [comment]
Verified
