### ISSUE TITLE
DB2 error message not descriptive enough

### ISSUE THREAD

**Issue by devscheffer** [dbeaver/dbeaver#12879]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
Version 21.1.0.202105300349
- Additional extensions
None

#### Connection specification:
- Database name and version
IBM DB2 11.5.5
- Driver name
db2jcc4
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I'm trying to get a better error explanation for my scripts but I'm only getting the code number instead of a description and line number where the error occur.
#### Steps to reproduce, if exist:
```sql
SELECT
	*
	,
FROM
	(
	VALUES(1)
	) t(test)
```

Return message:
```
Query execution failed

Reason:
SQL Error [42601]: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=(;	(

	VALUES(1)

	) t;,, DRIVER=4.26.14
```
I was expecting something like error line 3

I don't know if the problem is with the jdbc or dbeaver software

**Comment by ShadelessFox** [comment]
Hello @devscheffer,

Thanks for the report.

The problem is with the JDBC driver, unfortunately.
There's a chance we can retrieve it and move the cursor in the editor, but there's no guarantee whether it is possible or not.

**Comment by ShadelessFox** [comment]
After future investigation, it seems to be impossible to retrieve such information :(
We can't really do anything here.
