### ISSUE TITLE
when i import maven project，some m2e errors can’t be resloved

### ISSUE THREAD

**Issue by wangpeng0824** [dbeaver/dbeaver#12875]
![image](https://user-images.githubusercontent.com/21004513/122350129-84c17800-cf7f-11eb-8622-50cad0574917.png)
maven version is 3.8.1 ,eclipse version is 2021-03 for RCP developers

**Comment by wangpeng0824** [comment]
![image](https://user-images.githubusercontent.com/21004513/122351494-c3a3fd80-cf80-11eb-88e0-55179cb3f7d2.png)

**Comment by wangpeng0824** [comment]
if these errors need to be corrected？

**Comment by LonwoLonwo** [comment]
Hello @wangpeng0824 
You show pictures from Eclipse. DBeaver based on the Eclipse platform, but we can not fix anything, unfortunately.

This are my maven settings
![2021-06-17 11_03_25-eclipse-workspace2021 - com dbeaver cloud aws_src_com_dbeaver_cloud_aws_AWSCloud](https://user-images.githubusercontent.com/45152336/122357404-65652380-cf5c-11eb-88ca-fdba8a80e46c.png)

I hope, they help to find your problem.

**Comment by wangpeng0824** [comment]
I'm sorry I didn't describe the problem clearly，Have you noticed the article ‘Develop-in-Eclipse’， i  do everything follow the article step by step，the article shows  there are no mistakes like above，however，i do it again and again，always get the same results，i just want to know which version of eclipse and maven  that you are using？@LonwoLonwo

**Comment by LonwoLonwo** [comment]
I am using Eclipse version 2021-03 for RCP and RAP Developers and maven 3.6.3

Please check your plugin dependencies
![2021-06-17 11_41_28-eclipse-workspace2021 - com dbeaver cloud aws_src_com_dbeaver_cloud_aws_AWSCloud](https://user-images.githubusercontent.com/45152336/122362844-24234280-cf61-11eb-8945-64b36be3e4ea.png)

![2021-06-17 11_42_01-Debug Configurations](https://user-images.githubusercontent.com/45152336/122362846-24234280-cf61-11eb-83e5-aae06c7d1f3e.png)

**Comment by LonwoLonwo** [comment]
Perhaps you should try to reinstall Maven, and then reinstall Eclipse.
