### ISSUE TITLE
Data transfer: support column value transformers

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#12889]
It is API development task.
We need to add possibility to transform column values during data transfer.
Such as:
- Type transformation (e.g. int to string, string to geometry)
- Set to NULL/constants value
- Column skip
- Custom transformations

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/125443719-02655106-9901-44c7-b332-5c3e7d213607.png)

**Comment by Matvey16** [comment]
Verified
