### ISSUE TITLE
Found a typo (Simplified Chinese) in config of exporting table to sql

### ISSUE THREAD

**Issue by bianyun1981** [dbeaver/dbeaver#12888]
#### System information: 
- Operating system (distribution) and version:  Windows 10 Enterprise Edition (Simplified Chinese), 20H2
- DBeaver version:  21.0.0.202103021012
- Additional extensions

#### Describe the problem you're observing:
The typo (Simplified Chinese) is found in a config item of exporting table to sql, called "省区模式名". This config item is used for omiting scheme name when exporting table data to sql, but the Simplified Chinese translation of this config item is definitely not the meaning of 'OMIT', and it's a typo for sure. The typo has been around for a long time. The right Simplified Chinese translation of this config item should be "省去模式名" or "省略模式名".
![2021-06-18_143831](https://user-images.githubusercontent.com/17854699/122519965-a84ef600-d045-11eb-858b-ad602cbe51c8.jpg)

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
@bianyun1981 Maybe you can help us to translate other settings from this setting page? You can write it right here, in the comments, and I will add them to our localization properties file. It will be very helpful!

**Comment by bianyun1981** [comment]
> @bianyun1981 Maybe you can help us to translate other settings from this setting page? You can write it right here, in the comments, and I will add them to our localization properties file. It will be very helpful!

Sorry for the late reply. Sure, I am so happy to help. Dbeaver is really a good software, and this is my honor.

**Comment by bianyun1981** [comment]
@LonwoLonwo I do my best to do the translation, and I hope this helps.

![2021-08-05_082414](https://user-images.githubusercontent.com/17854699/128277120-85c3e2fb-0858-4130-9e75-039a73911cb4.png)

<pre>
(1) Set data transfer settings  ==> 数据传输设置
(2) Extraction settings         ==> 抽取设置
(3) Format settings             ==> 格式设置

(4) Include generated columns   ==> 包含生成的列
        tooltip[Include auto-generated columns (e.g. auto-increment) in SQL INSERT]
                                ==> 在 INSERT语句中包含自动生成的列（比如: 自增列）
                                
(5) Native date/time format     ==> 本地日期/时间
        tooltip[Use native date/time format in INSERT statements]
                                ==> 在 INSERT语句中使用本地的日期时间格式
                                
(6) Formatting                  ==> 格式化

      Insert line before rows   ==> 在每行数据前加换行
        tooltip[Insert line feed before values(for multi-row inserts)]
                                ==> 在 values从句中的每行数据前加上换行符（适用于单条语句插入多行数据）
                                
      Keyword case              ==> 关键字大小写
        tooltip[You can choose lower or upper keyword case]
                                ==> 你可以选择小写或大写关键字
                                
      Insert keyword            ==> Insert语句的关键字
        tooltip[You can choose different insert keywords]
                                ==> 你可以选择不同的 Insert关键字
                                
      On conflict expression    ==> ON CONFLICT 表达式
        tooltip[Expression for the end of the statement. Enter the required value in this field. This is database specific setting]
                                ==> 语句末尾的表达式。此为数据库特定设置，请按照数据库的要求输入相应的值
                                
(7) upper / lower               ==> 大写 / 小写
</pre>

**Comment by bianyun1981** [comment]
@LonwoLonwo  I found a misuse of Chinese quantifier '个', '条' may be better.

![2021-08-05_094448](https://user-images.githubusercontent.com/17854699/128278434-17d9a798-3c10-477b-9c8e-2166423c853c.png)

**Comment by LonwoLonwo** [comment]
Thanks a lot @bianyun1981!

**Comment by LonwoLonwo** [comment]
Implemented in DBeaver 21.2.0
Except "upper, lower". Not so easy to localize settings parameters, unfortunately.

**Comment by Matvey16** [comment]
Typo "Upsert" instead of "Insert"

![dbeaver_m1gTm87E6Z](https://user-images.githubusercontent.com/82543000/129695788-3f0b779d-79d9-44f5-824d-313bed7953b1.png)

**Comment by Matvey16** [comment]
Expected for newer versions
