### ISSUE TITLE
Refresh of table definition 

### ISSUE THREAD

**Issue by majkyyx** [dbeaver/dbeaver#12899]
#### System information: 
  OS: KDE neon User Edition 5.22 x86_64  (same on Windows 10)

#### Connection specification:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
- Driver name: ojdbc7.jar

#### Describe the problem you're observing:
Changes of columns aren't showing in table definition.

#### Steps to reproduce, if exist:
1. create table
```sql
CREATE TABLE my_table (A NUMBER (10));
```
2. open table from object inspector (there is number 10):
![image](https://user-images.githubusercontent.com/14957734/122574140-a5590300-d04f-11eb-8bdb-e36f68c3c214.png)
3. change the table:
```sql
ALTER TABLE my_table MODIFY A NUMBER (12,2)
```
4. after that, in table definition is still number 10,0 but has to be number 12,2
![image](https://user-images.githubusercontent.com/14957734/122574459-f5d06080-d04f-11eb-9677-1f12b40f7f91.png)

5. refresh button don't work,

**Comment by uslss** [comment]
thank you for the report

**Comment by serge-rider** [comment]
Fixed

**Comment by majkyyx** [comment]
thx a lot, it was fast.. ;-)

**Comment by Matvey16** [comment]
Verified
