### ISSUE TITLE
Set to NULL for binaries doesn't work in export to source code or JSON

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#12892]
#### System information: 
- DBeaver version 21.1.1

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
1. Start data export to source code or JSON for a table with `bytea` column
2. Select **Set to NULL** for Binaries
3. Perform an export

**Expected:** Binaries are exported as NULLs
**Actual:** Binaries are exported in Hex

![2021-06-18_13h50_23](https://user-images.githubusercontent.com/82543000/122554704-011c8f80-d042-11eb-85ce-69ddb74ef477.png)
![2021-06-18_13h51_07](https://user-images.githubusercontent.com/82543000/122554825-23161200-d042-11eb-986c-3c6976843bf4.png)

**Comment by Matvey16** [comment]
Can be related to
#11200
#10643

**Comment by uslss** [comment]
verified
