### ISSUE TITLE
Drag-n-Drop in Grouping panel doesn't work on Linux

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#12890]
#### System information: 
- Operating system (distribution) and version Ubuntu 20.04
- DBeaver version 21.1.1

#### Steps to reproduce, if exist:
1. Open grouping panel for a table
2. Drag and drop a column to a panel

**Expected:** Column is added
**Actual result:** Nothing happens

**Comment by uslss** [comment]
duplicates #7890
