### ISSUE TITLE
SSH Tunnel--when selecting key file browser cannot browse to ~/.ssh

### ISSUE THREAD

**Issue by hrabkin** [dbeaver/dbeaver#12896]
SSH Tunnel--when selecting key file browser cannot browse to ~/.ssh

on OS-X

**Comment by ShadelessFox** [comment]
Please refactor your issue using our [issue template](https://github.com/dbeaver/dbeaver/issues/new?assignees=&labels=bug%2C+wait+for+review&template=bug_report.md).

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual - feel free to reopen it with additional info to reproduce the issue.
