### ISSUE TITLE
Cloudera Hive JDBC driver based connection does not show MAP and ARRAY type columns

### ISSUE THREAD

**Issue by jpastuszek** [dbeaver/dbeaver#129]
I can't see MAP and ARRAY type columns in navigation view and in table properties/columns view.
I can see them with DESCRIBE and I can use them no problem.

![properties](https://cloud.githubusercontent.com/assets/20052/11927409/473e1d64-a7c4-11e5-831a-ed9e9cf9333c.png)
![navigation](https://cloud.githubusercontent.com/assets/20052/11927408/473a74fc-a7c4-11e5-9395-d8bc5f558eb8.png)
![describe](https://cloud.githubusercontent.com/assets/20052/11927410/473f3a96-a7c4-11e5-93c5-3a6cb21f5d58.png)

An chance to get them visible even if the type would be unknown?

**Comment by serge-rider** [comment]
Please check error log (main menu Window->Error Log). If there are any suspicious errors - post them here (with stacktrace). 
Also there is the debug log ($HOME/.dbeaver/.metadata/.dbeaver-debug.log).

**Comment by jpastuszek** [comment]
When I clear the error log, close all windows, restart DBeaver and open column list I have nothing in the error log.

Nothing interesting in the debug log:
https://gist.github.com/jpastuszek/f7ae77dbeeb55f0ca0cf

**Comment by serge-rider** [comment]
What Hive driver do you use? Exact version?

**Comment by jpastuszek** [comment]
![version](https://cloud.githubusercontent.com/assets/20052/11952955/478a00d2-a894-11e5-909c-ff38372946e8.png)

Class name:
com.cloudera.hive.jdbc41.HS2Driver

I am on Java 1.7.0_79.

The driver version is 2.5.15 and can be download from:
http://www.cloudera.com/content/www/en-us/downloads/connectors/hive/jdbc/2-5-15.html

The server is using HiveServer2 1.1.0 from CDH 5.4.4.

**Comment by serge-rider** [comment]
This looks way to old. Both Hive driver and DBeaver changed since then. 
If this problem still persists - please reopen or create a new ticket.

**Comment by jpastuszek** [comment]
Hi, I have checked this again and this is still the case. I am on one of the latest driver and DBeaver version. Basically columns with complex data types are not visible in DBeaver UI. I can still query them no problem (knowing they exist).

**Comment by serge-rider** [comment]
Could you post sample DDL to reproduce this

**Comment by jpastuszek** [comment]
```sql
use default;

create table test (
	ok1 STRING,
	bar STRUCT<type:STRING>,
	baz ARRAY<STRING>,
	ok2 BIGINT
);
```

<img width="217" alt="screen shot 2018-08-30 at 11 32 45" src="https://user-images.githubusercontent.com/20052/44846514-75df6e80-ac48-11e8-9064-e4ff118f5fee.png">
<img width="712" alt="screen shot 2018-08-30 at 11 32 32" src="https://user-images.githubusercontent.com/20052/44846519-7aa42280-ac48-11e8-995c-397ba8c64e24.png">

**Comment by serge-rider** [comment]
Can't reproduce this - at least with the recent driver (jdbc uber jar 1.0-2.2.4)

![image](https://user-images.githubusercontent.com/6398845/46582527-e1d7a280-ca50-11e8-93ec-63ff0899d7ec.png)

**Comment by uslss** [comment]
verified
