### ISSUE TITLE
Incomplete script execution with no errors shown

### ISSUE THREAD

**Issue by PauloPontes** [dbeaver/dbeaver#12905]
#### System information: 
- Operating system (distribution) and version 
Windows 10
- DBeaver version
Version 21.0.4.202105021514
- Additional extensions
No extensions added

#### Connection specification:
- Database name and version
- Oracle
- Driver name
- dbeaver downloaded automatically for me
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:
Hi,
I am trying to execute a big insert sql script with almost 200k lines on an Oracle database,
I click on the "execute script" button and everything goes fine, dbeaber says that completed the work instering x lines where x is something between 700 and 2k lines. Less than 1% of the entire script.
No errors, no warnings, the UI shows as if he completed what he was supposed to do.

#### Steps to reproduce, if exist:
write a script with 200k lines with one insert per line
execute script

#### Include any warning/errors/backtraces from the logs
No errors, just "X lines executed"

**Comment by uslss** [comment]
could you provide a video of the issue?

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual - feel free to reopen it with additional info to reproduce the issue.
