### ISSUE TITLE
Username can not be set in connection to clickhouse

### ISSUE THREAD

**Issue by rchlin** [dbeaver/dbeaver#12906]
This problem is found in 21.1.0 version. When I try an old version of 7.5.6, it can be set

**Comment by uslss** [comment]
@rchlin could you provide more info to reproduce an issue? Logs, screenshots or screencasts, steps to reproduce in issue will be helpful for the issue's investigation

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual - feel free to reopen it with additional info to reproduce the issue.
