### ISSUE TITLE
Ability to rename a column in an Sqlite database table

### ISSUE THREAD

**Issue by sprintel** [dbeaver/dbeaver#1290]
Sqlite currently does not support column rename but there is a workaround by creating a new table with new column names and then copy the data from the old table to the new table. I would like to submit a request that will allow DBeaver to generate automatically such script when column rename is needed. This will reduce time needed to write the sql from scratch.

Thanks Serge-rider!!!

**Comment by serge-rider** [comment]
Wow, so old ticket.
And quite uneasy to implement. Any assistance would be appreciated (e.g. SQL snippets for table copy).

**Comment by tuffnatty** [comment]
Sqlite supports column renaming since 3.25.0: https://www.sqlite.org/releaselog/3_25_0.html

**Comment by serge-rider** [comment]
@tuffnatty Thanks for the info!
We'll add SQLite column rename support in the next version.

**Comment by kseniiaguzeeva** [comment]
verified
