### ISSUE TITLE
session update stopped working

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#12902]
DBeaver 21.1.0
Postgresql 12

![изображение](https://user-images.githubusercontent.com/61137576/122597104-58dbea80-d084-11eb-8e7a-cb7ef9bb5bdb.png)

By click on button or by setting time, start any process, but session monitor do not refresh. Only close session window and reopen.

**Comment by uslss** [comment]
cannot reproduce it. Is there some error in the logs?

**Comment by detkliff** [comment]
no data in error log
![изображение](https://user-images.githubusercontent.com/61137576/123360460-cc02c680-d586-11eb-86f3-5a781fbfea6f.png)

**Comment by uslss** [comment]
will be fixed in the scope of #13154
