### ISSUE TITLE
Provide DDL statement export of the whole library

### ISSUE THREAD

**Issue by zhbdesign** [dbeaver/dbeaver#12916]
Provide DDL statement export of the whole library

**Comment by uslss** [comment]
please provide more info accordingly to the [template](https://github.com/dbeaver/dbeaver/issues/new?assignees=&labels=feature+request%2C+wait+for+review&template=feature_request.md&title=)

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual - feel free to reopen it with additional info to reproduce the issue.
