### ISSUE TITLE
PostgreSQL Can't navigate with composite foreign key referencing unique constraint

### ISSUE THREAD

**Issue by Seregy** [dbeaver/dbeaver#12910]
#### System information: 
- Operating system (distribution) and version: macOS 11.2.3
- DBeaver version: 21.1.0.202106012023

#### Connection specification:
- Database name and version: PostgreSQL 11.7
- Driver name: PostgreSQL 42.2.22

#### Describe the problem you're observing:

Trying to navigate with foreign key to the record in another table fails with an error:
```
'Navigate association' has encountered a problem.

Entity [relation_test.parent] association [child_fk] columns differs from referenced constraint [parent_pk] (2<>1)
```
Table from which I'm trying to navigate contains a composite foreign key that references unique constraint on two columns, but it looks like the navigate association tries to use primary key instead. Error occurs when I'm trying to navigate from the first table into a second one using:
 - navigate link icon next to the value in one of the columns with foreign key
 - Navigate -> Navigate link from context menu
 - Navigate -> References -> %foreign key reference name%

#### Steps to reproduce, if exist:

Create a parent table with a primary key and a unique constraint on two other columns, insert a record into it.
Create a child table with a composite foreign key on the parent using two columns that reference parent's columns that are part of unique constraint, insert a record into it.
Try to navigate from child table into a parent one with a foreign key.

Tested with the following structure and data:
1) Root `grandparent` table, that will be referenced from two other tables:
```sql
CREATE TABLE grandparent (
	id int8 NOT NULL,
	"name" varchar NULL,
	CONSTRAINT grandparent_pk PRIMARY KEY (id)
);

INSERT INTO grandparent (id, "name") VALUES(1, 'Grandparent record');
```

2) `parent` table that contains a unique constraint on two columns and will be referenced via composite foreign key:
```sql
CREATE TABLE parent (
	id int8 NOT NULL,
	grandparent_id int8 NOT NULL,
	"name" varchar NULL,
	CONSTRAINT parent_pk PRIMARY KEY (id),
	CONSTRAINT uq_parent_id_grandparent_id UNIQUE (id, grandparent_id)
);

ALTER TABLE parent ADD CONSTRAINT parent_fk FOREIGN KEY (grandparent_id) REFERENCES grandparent(id);

INSERT INTO parent (id, grandparent_id, "name") VALUES(10, 1, 'Parent record');
```

3) `child` table that contains composite foreign key on `parent`:
```sql
CREATE TABLE child (
	id int8 NOT NULL,
	parent_id int8 NOT NULL,
	grandparent_id int8 NOT NULL,
	"name" varchar NULL,
	CONSTRAINT child_pk PRIMARY KEY (id)
);

ALTER TABLE child ADD CONSTRAINT child_fk FOREIGN KEY (parent_id,grandparent_id) REFERENCES parent(id,grandparent_id);

INSERT INTO child (id, parent_id, grandparent_id, "name") VALUES(100, 10, 1, 'Child record');
```

#### Include any warning/errors/backtraces from the logs
```
2021-06-20 17:48:47.133 - Error during job 'Navigate association' execution
org.jkiss.dbeaver.DBException: Entity [relation_test.parent] association [child_fk] columns differs from referenced constraint [parent_pk] (2<>1)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.navigateAssociation(ResultSetViewer.java:3109)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$6.run(SpreadsheetPresentation.java:1188)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
