### ISSUE TITLE
DB not showing despite Show all databases enabled.

### ISSUE THREAD

**Issue by dredshep** [dbeaver/dbeaver#12911]
![image](https://user-images.githubusercontent.com/78047001/122684284-89319f00-d1d2-11eb-85d3-2f8b6acf5799.png)

Am I doing something wrong or is this a problem with DBeaver? Dunno how to read the contents of my new db.

(I created the DB before opening the connection so it's not an old cache problem I reckon.)

**Comment by ShadelessFox** [comment]
Hello @dredshep,

Can you check [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) and show the queries in it? Make sure the queries are fully visible (there should not be any sensitive data).

Do avoid including unrelated queries, simply clear everything, then connect to your DB and expand very top folder to see all the databases.

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual - feel free to reopen it with additional info to reproduce the issue.
