### ISSUE TITLE
Clear color for one value disable coloring for other already colored

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12912]
#### System information: 
- Windows 10
- DBeaver CE 21.1.1
- SQLite, Pestgres ...

#### Describe the problem you're observing:
Data editor context menu of one value -> View/format -> set row color for "value_in_selected_item"
Go to another cell and in contex menu -> View/format -> clear row color for "second_value_in_selected_item"
possibly there is inaccuracy in the writing of the context menu items. Because if we don't have any colored row, the "Clear ..." item is absent in the context menu, but if one or more colored items is present, then it says that we can to clear the color only for the current value:
![image](https://user-images.githubusercontent.com/43252954/122685037-ce28f600-d211-11eb-8671-485721042b61.png)
#### Steps to reproduce, if exist:
https://user-images.githubusercontent.com/43252954/122685167-750d9200-d212-11eb-94c6-ba2e9d047201.mp4

**Comment by ShadelessFox** [comment]
With #11486, it would be harder to detect actual setting for a given row value.

We can try evaluating expression first to see if the value matches.

**Comment by ShadelessFox** [comment]
Also, it would be nice to refactor model, so we can replace `DBVColorOverride#isRange` with `DBCLogicalOperator#BETWEEN`. 

By doing so, we will be able to display <kbd>Clear color for ... </kbd> action for ranges too. We also can support operators beside just <kbd>=</kbd>.

But I don't think major changes like that are related to the issue itself. A separate feature request may be created.

**Comment by uslss** [comment]
verified
