### ISSUE TITLE
import looping on malformed CSV. need log for current line being read, in order to troubleshoot accordingly

### ISSUE THREAD

**Issue by AlexandreHGuerra** [dbeaver/dbeaver#12913]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
@alexhguerra can you provide more info about your issue accodingly to the template in the first message?

**Comment by AlexandreHGuerra** [comment]
System information:
Operating system (distribution) and version
    Ubuntu 21.04
DBeaver version
    21.1.0
Java version
    Bundled with DBeaver? 
Additional extensions
    none
Connection specification:
    SQL Server
Database name and version
Driver name
Do you use tunnels or proxies (SSH, SOCKS, etc)?
   No
Describe the problem you're observing:
Steps to reproduce, if exist:
   import looping on malformed CSV. need log for current line being read, in order to troubleshoot accordingly
   Detected that a double quote in a string column was the issue. checking to ignore it as a separator was able to proceed
   It would be nice if a watchdog timer for the string interpreter in the import module would be implemented. this way in case of
    loop , it would fail faster
   Also, it should dump the lines effectively read by that batch
Include any warning/errors/backtraces from the logs
   There is none.

**Comment by uslss** [comment]
@AlexandreHGuerra is it still actual against 22.0.5?

**Comment by uslss** [comment]
there has been no update on the issue for a long time.
If it is still actual - feel free to reopen it.
