### ISSUE TITLE
No task types in create a task window in eclipse extension

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12924]
#### System information: 
- Windows 10
- DBeaver 21.1.1 CE, Eclipse extension
#### Describe the problem you're observing:
In Create a task window there are no proposed types and you cannot create tasks in that way
![image](https://user-images.githubusercontent.com/43252954/122765438-2d861500-d2a9-11eb-8108-6d56c1a02ff7.png)

**Comment by serge-rider** [comment]
It is another tasks dialog (Eclipse-specific)
