### ISSUE TITLE
Only one entity highlighted when search items by name part in ERD

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12926]
#### System information: 
- Windows 10
- DBeaver 21.1.1 CE
#### Steps to reproduce:
 -Go to ERD with many tables in it
 -Click on the magnifier btn in the bottom ERD menu 
![image](https://user-images.githubusercontent.com/43252954/122768945-c4080580-d2ac-11eb-8475-b02a3602ddab.png)
 -Type in letters that contains in several items in the opened ERD and press Enter

 ##### Expected:
All elements that contains entered letters highlighted 
 ##### Actual:
Only one item highlighted 
![image](https://user-images.githubusercontent.com/43252954/122768394-39270b00-d2ac-11eb-864d-a9324a579171.png)

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
