### ISSUE TITLE
Empty file created in addition to exported data in CSV if split output file selected

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12927]
#### System information: 
- Windows 10
- DBeaver 21.1.1 CE

#### Steps to reproduce, if exist:
- Open Export data dialog
- Select CSV data transfer type
- In the output settings select Split output size, set small maximum file size (e.g. 1 - 20) 
![image](https://user-images.githubusercontent.com/43252954/122770309-ff570400-d2ad-11eb-96dd-7a09980069e3.png)
- Start exporting

As a result, you will get several CSV files of the exported data, and the last one will be an empty file. No data loss occurs

**Comment by Matvey16** [comment]
Verified
