### ISSUE TITLE
Proxy setting is ignored when connecting to SAP HANA

### ISSUE THREAD

**Issue by goldbach** [dbeaver/dbeaver#12934]
#### System information: 
- Operating system (distribution) and version: macOS big sur 11.4
- DBeaver version: 21.1.1.202106210813
- Additional extensions: none

#### Connection specification:
- Database name and version: SAP HANA Generic
- Driver name: SAP/HANA
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  : trying to !

#### Describe the problem you're observing:

DBeaver seems to ignore SOCKS proxy setting when connecting to HANA db, instead it connects directly to HANA host.
This has also been verified with tcpdump. 

Also, when I wrap Dbeaver with proxychains (DLL inject of network libraries) my connection works thru the proxy so I know
proxy setup and connection settings in dbeaver is good.

#### Steps to reproduce, if exist:

Setup connection to SAP HANA og use socks5 proxy

#### Include any warning/errors/backtraces from the logs
2021-06-22 08:53:05.715 - DBeaver 21.1.1.202106210813 is starting
2021-06-22 08:53:05.716 - OS: Mac OS X 11.2 (x86_64)
2021-06-22 08:53:05.716 - Java version: 11.0.11 by AdoptOpenJDK (64bit)
...
> Start Internet Connection Management UI [org.eclipse.ui.net 1.3.800.v20200422-1935]
> Start Internet Connection Management [org.eclipse.core.net 1.3.1000.v20200715-0827]
2021-06-22 08:53:08.964 - Loading user drivers configuration from '/Users/jakob/Library/DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.core/drivers.xml'
2021-06-22 08:53:08.970 - Total database drivers: 90 (90)
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.59.202106210813]
> Start Default Text Editor [org.eclipse.ui.editors 3.14.0.v20210215-0846]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.96.202106210813]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.65.202106210813]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.19.202106210813]
2021-06-22 08:54:01.485 - Connect with 'my-container' (sap_hana-177d86bc193-xxxxxxx9d71a0dcad)
2021-06-22 08:54:01.490 - Proxy service 'org.eclipse.core.net.proxy.IProxyService' loaded
> Start DBeaver Generic Plug-in [org.jkiss.dbeaver.ext.generic 2.3.145.202106210813]
> Start DBeaver SAP HANA Support [org.jkiss.dbeaver.ext.hana 1.2.37.202106210813]
> Start DBeaver GIS Support [org.jkiss.dbeaver.data.gis 1.0.83.202106210813]
2021-06-22 08:54:01.558 - Execution context opened (my-container; Main; 0)
2021-06-22 08:54:01.889 - Connection failed (sap_hana-177d86bc193-xxxxxx9d71a0dcad)
org.jkiss.dbeaver.model.exec.DBCConnectException: SAP DBTech JDBC: Cannot connect to jdbc:sap://337bxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.hana.prod-eu10.hanacloud.ondemand.com:443 [Object is closed: com.sap.db.jdbc.SecureChannelSession@43f08321 337bxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.hana.prod-eu10.hanacloud.ondemand.com:443 ConnectionID:0 SessionID:0 on sun.nio.ch.UnixAsynchronousSocketChannelImpl[connected local=/192.168.82.249:54620 remote=337bxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.hana.prod-eu10.hanacloud.ondemand.com/3.64.xx.xx:443]].

**Comment by uslss** [comment]
sorry for the long response.
thanks for the report

**Comment by uslss** [comment]
note: infinite loop appears in the special case.
1. Connect to hana - db is connected.
2. Try to connect to another connection (snowflake, postgresql) - authentication dialog appears.
3. Connection is not possible, authentication dialog appears both if valid credentials were entered or Cancel was pressed
![2021-07-07_14h31_14](https://user-images.githubusercontent.com/31996417/124752485-966bbf00-df30-11eb-8bc3-9eafc09903ac.gif)

**Comment by serge-rider** [comment]
SAP HANA JDBC driver uses NIO sockets which don't support standard Java proxy.
They have their own proxy configuration in the driver properties: `proxyHostname` and `proxyPort`.

![image](https://user-images.githubusercontent.com/6398845/133764418-3a7c0181-52e5-4f84-a8b3-6fa904c32f64.png)

See documentation here:
https://help.sap.com/viewer/f1b440ded6144a54ada97ff95dac7adf/LATEST/en-US/109397c2206a4ab2a5386d494f4cf75e.html

**Comment by uslss** [comment]
verified
