### ISSUE TITLE
Improved link file opening

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#12933]
Thank you for making such a good program usable.

There is a function that I would like to see improved in relation to opening Lnk files

When opening a link file in the Scripts folder, I want the file pointed to by the link file to be opened.

If it is an lnk file by reading the file extension as if it works like the Create -> Link File menu, it would be nice if the file pointed to by the link file was opened.

![image](https://user-images.githubusercontent.com/59002295/122864244-39cca980-d35f-11eb-9ba5-dfeb6440218d.png)

Thank for Reading.

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by ShadelessFox** [comment]
Implemented. Now shortcuts (`.lnk`) added to the <kbd>Scripts</kbd> folder should open the filter they point to.

What to test:
 - Shortcuts to file/folder
 - Deleting target file and trying to open shortcut
 - Absolute/Relative shortcuts (e.g. within the same drive and on separate drives)
 - ASCII/Unicode paths (e.g. folder named 🔥)

**Comment by uslss** [comment]
shortcut associated with deleted target file is deleted even if user choose no in confirmation dialog
![r5G8PqnUtt](https://user-images.githubusercontent.com/31996417/132476521-c71644e3-82e9-456b-a72c-7ae56b5e8793.gif)

**Comment by ShadelessFox** [comment]
This is a side-effect of dbeaver/pro#714.

**Comment by uslss** [comment]
verified
