### ISSUE TITLE
DBeaver 21.1.1 fails to determine geometry type of spatial table in PostgreSQL

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#12948]
#### System information: 
- Operating system (distribution) and version: Windows 10, build 19043.1081
- DBeaver version 21.1.1
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 13.3 / PostGIS 3.1.2
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Describe the problem you're observing:

DBeaver 21.1.1 fails to determine geometry type of a spatial table in PostgreSQL, and as a consequence also doesn't show the geometry column in the navigator (notice empty space between 'osm_id' and 'tags' column). This used to work fine in previous versions (before upgrade, my latest version was 21.1.0):

![afbeelding](https://user-images.githubusercontent.com/7635726/123060028-a650b280-d40a-11eb-82b0-8b808d18ea5e.png)

#### Steps to reproduce, if exist:

Upgrade to 21.1.1, navigate to a spatial table in PostgreSQL and open the 'Columns' view.

#### Include any warning/errors/backtraces from the logs

![afbeelding](https://user-images.githubusercontent.com/7635726/123060895-6ccc7700-d40b-11eb-8a78-3be47ba2f4d8.png)

**Comment by uslss** [comment]
@mboeringa , unfortunately cannot reproduce it.
Could you provide error log and table ddl, if possible?

**Comment by uslss** [comment]
I'm managed to reproduce the issue.

thanks for the report

_reproducible at db2.gis.public.planet_osm_polygon_

**Comment by ShadelessFox** [comment]
It turns out, PostGIS supports geometry types with specified SRID but without specifying actual type.

For example, `geometry(geometry, 4326)` will allow values of any type (`POINT`, `POLYGON`, etc.) with SRID 4326.

Also, `geometry(geometry)` is also supported, but it does not make any sense AFAIK.

**Comment by ShadelessFox** [comment]
Fixed.

![java_6fWTKnVVat](https://user-images.githubusercontent.com/35821147/123075039-83c99400-d420-11eb-8f32-7f2fe23ffe72.png)

**Comment by uslss** [comment]
verified
