### ISSUE TITLE
MariaDB create user with password check plugin

### ISSUE THREAD

**Issue by ivolvicente** [dbeaver/dbeaver#12945]
#### System information: 
- Windows 10 remote access to Ubuntu 20.04
- DBeaver 21.1.1.202106210824
- Java 1.8.0_241

#### Connection specification:
- MariaDB 10.3.27
- MariaDB
- No (SSH, SOCKS, etc)? 
- Additional plugin [Simple Password Check ](https://mariadb.com/kb/en/simple-password-check-plugin/)

#### Describe the problem you're observing:
When this plugin is active, its not possible to create a new user.

This happens, because the SQL generated create the user on the first line and then alter it adding the secure password.

```sql
-- Return error on persist
CREATE USER 'secure_user'@'%';
ALTER USER 'secure_user'@'%' IDENTIFIED BY 'MegaHyperSafePassword!123$' ;
...
```
If I copy the SQL statement and change the first line to

```sql
-- Create user with success
CREATE USER 'secure_user'@'%' IDENTIFIED BY 'MegaHyperSafePassword!123$' ;
...
```

The user is created

#### Steps to reproduce, if exist:

Activate this additional plugin
Restart MariaDB
Try to create a new user

**Comment by Matvey16** [comment]
Will be implemented in future updates.

**Comment by ShadelessFox** [comment]
Generated DDL when plugin is **enabled**:
![image](https://user-images.githubusercontent.com/35821147/126162988-c6719da3-42ff-47fc-975b-7892f94ccba2.png)

Generated DDL when plugin is **disabled**:
![image](https://user-images.githubusercontent.com/35821147/126163110-bd80c796-e733-486c-8d31-193ed34c3853.png)

As a bonus, added plugin information in UI:
![image](https://user-images.githubusercontent.com/35821147/126162844-e35fe645-32fd-4a1e-8f9f-51311775c682.png)

**Comment by uslss** [comment]
verified
