### ISSUE TITLE
Database Navigator "Show Connected Only", "Show All" toggle no longer works

### ISSUE THREAD

**Issue by taf1-cornell-edu** [dbeaver/dbeaver#12943]
#### System information: 
- Operating system (distribution) and version  Windows 10 Enterprise version 1909
- DBeaver version  Community 21.1.1.202106210824
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version  postgres 13.*
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
[Database Navigator], top right side, button to toggle between showing all connections and showing connected only stopped working with yesterday's upgrade to Community 21.1.1.202106210824
#### Include any warning/errors/backtraces from the logs
<none>  Functionality has not worked today and there are no errors in the logs from today.

**Comment by LonwoLonwo** [comment]
Thanks for the bug report!

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.1.2

**Comment by taf1-cornell-edu** [comment]
Super.  Thanks for resolving this so quickly.
I have seen one other new database navigator bug, which I'll report if I
can get some good reproducible steps.
Roughly, in the navigation tree, under connection, under the database
name,  the 'Schemas, Roles, Administer, Extensions, Storage, System Info'
layer is missing and the list of schemas is shown instead.  I'll send along
more info if I encounter it again.    -- Tom

**Comment by uslss** [comment]
verified
