### ISSUE TITLE
Explain ER Diagram Notation in docs please

### ISSUE THREAD

**Issue by SMUsamaShah** [dbeaver/dbeaver#12959]
Please explain what the symbols mean somewhere in the docs.
What does a line, dashed line, filled circle and square mean in context with one-to-one and one-to-many etc.

I understand that this is IDEF1X but this is still not enough.

**Comment by Matvey16** [comment]
https://github.com/dbeaver/dbeaver/wiki/Database-Structure-Diagrams#relationship-notation

**Comment by SMUsamaShah** [comment]
> If the relationship between two tables is other than one-to-one, the lines will start at the same point and also end at the same point

I have trouble understanding this. What does it mean by starting and ending at the same point? It sounds like line will be like a loop and table will point to itself which does not make sense.

**Comment by Matvey16** [comment]
@SMUsamaShah Thank you, I'll try to rephrase that. That basically means that you won't see familiar forks at the ends of one line, but instead there will be multiple lines that all start at the same point attached to first table, continue separately from each other, and then end all at the same point attached to the second table.
