### ISSUE TITLE
datetime2(0) in MSSQL can not be handled properly  in dbeaver

### ISSUE THREAD

**Issue by yyjdelete** [dbeaver/dbeaver#12965]
Maybe related to #3555, but I already use the Microsoft driver instead of the old jTDS

#### System information: 
- Operating system (distribution) and version: Win10
- DBeaver version: 21.1.1
- Additional extensions

#### Connection specification:
- Database name and version: MSSQL2016
- Driver name: `com.microsoft.sqlserver.jdbc.SQLServerDriver`
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
Seems dbeaver think the default scale of datetime2 is `0`, but in fact is `7` instead; or dbeaver think `0` is an invalid scale for datetime2

#### Steps to reproduce, if exist:
1. create an new table with sql
```sql
CREATE TABLE NewTable (
	dt0 datetime2(0) NOT NULL,
	dt7 datetime2(7) NOT NULL,
	dt_def datetime2 NOT NULL,
);
```
2. It's display as the below in DDL, and the dt0 changed from `datetime2(0)` to `datetime2`(scale=7)
```sql
CREATE TABLE DB_Index.dbo.NewTable (
	dt0 datetime2 NOT NULL,
	dt7 datetime2(7) NOT NULL,
	dt_def datetime2(7) NOT NULL
);
```
3. Also, it's unable to create in column with `datetime2(0)` from UI, when you set scale to `0`, it will be removed auto and finally get `datetime2`(scale=7).

**Comment by Matvey16** [comment]
@yyjdelete  Thank you for the report.

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.1.2

Now displayed table DDL will be
```sql
CREATE TABLE NewTable (
	dt0 datetime2(0) NOT NULL,
	dt7 datetime2 NOT NULL,
	dt_def datetime2 NOT NULL,
);
```

7 is the default value for datetime2, time, and datetimeoffset columns. Scale numbers from 0 to 6 will be shown for column date type in parenthesis.

**Comment by yyjdelete** [comment]
Is this one also get fixed? Set scale to 0 is impossible here.
![image](https://user-images.githubusercontent.com/1819074/123262655-b5c71d00-d52a-11eb-9e52-e8eac1727928.png)

**Comment by Matvey16** [comment]
@yyjdelete Yes, it is also fixed
![2021-06-24_17h26_12](https://user-images.githubusercontent.com/82543000/123280284-56a8de80-d511-11eb-82c4-d94bf2cc3a32.gif)

**Comment by uslss** [comment]
verified
