### ISSUE TITLE
Unable to edit calculated(expression) field in firebird

### ISSUE THREAD

**Issue by ZGabrovski** [dbeaver/dbeaver#12966]
#### System information: 
- Operating system (distribution) and version -All
- DBeaver version Last
- Additional extensions

#### Connection specification:
- Database name and version Firebird 3.07
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
A have a table with calculated (expression) field I can not see /edit expression value
And expression even it is not exists in table DDL 
#### Steps to reproduce, if exist:
Create a simple table with two fields one regular and one expression in another firebird tool you can not see expression field in dbeaver

**Comment by uslss** [comment]
thank you for the report

**Comment by ShadelessFox** [comment]
Implemented:

![image](https://user-images.githubusercontent.com/35821147/131660018-0d7f47f2-fdac-4ac6-9685-d4c8a95a3154.png)

![image](https://user-images.githubusercontent.com/35821147/131855361-9f9f47b8-3394-40a9-b1d0-58b34d116c65.png)

**Comment by uslss** [comment]
verified
