### ISSUE TITLE
Unable to upgrade to latest version using apt-get

### ISSUE THREAD

**Issue by tcampbPPU** [dbeaver/dbeaver#12978]
#### System information: 
- On: Ubuntu 20.10
- DBeaver version: 21.0.2 

I am unable to upgrade to the latest version of DBeaver-CE. I have originally installed with `apt-get`. Now each time I open DBeaver I get prompted about upgrading the latest version.
![image](https://user-images.githubusercontent.com/25044744/123277559-373f9080-d4d4-11eb-9242-d82e42392a2f.png)

Since I installed with `apt` I run 
```bash
sudo apt-get update && sudo apt-get upgrade
```
Nothing for DBeaver gets listed, so when I again try to just install it still says at latest version
```bash
dbeaver-ce is already the newest version (21.0.2).
```

Is this something with my local package lists, since I have been any to update several version in the past, but after version 21.0.2  I've been stuck on this version?

**Comment by p91paul** [comment]
how did you install it in the first place? Perhaps you just downloaded the deb file? from what I can see, both the ppa and the Dbeaver debian repository are up to date.
Do your /etc/apt/sources.list or any of the files in /etc/apt/sources.list.d/ mention dbeaver?

**Comment by tcampbPPU** [comment]
I installed like [this](https://github.com/dbeaver/dbeaver/issues/988#issuecomment-699534165) 
```bash
wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -
echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list
sudo apt update
sudo apt -y install dbeaver-ce
```

**Comment by tcampbPPU** [comment]
When I cat out `cat /etc/apt/sources.list.d/dbeaver.list`
I get the following:
```bash
# deb https://dbeaver.io/debs/dbeaver-ce / # disabled on upgrade to groovy
```
