### ISSUE TITLE
dump and restore issue with GENERATED columns

### ISSUE THREAD

**Issue by arnovanoordt** [dbeaver/dbeaver#12972]
#### System information: 
- Operating system (distribution) and version: win 10
- DBeaver version: 21.1.1
- Additional extensions: None

#### Connection specification:
- Database name and version? NA
- Driver name: MySQL Binaries - MySQL/MariaDB 5.5.62
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NA

#### Describe the problem you're observing:
When making a database dump it correctly creates GENERATED STORED columns, but it also creates the INSERT INTO statement where it wants to insert the concrete values in the generated columns (which leads to errors since the generated columns can't have data inserted into them)

Here is an example of what's being dumped:

```
--
-- Table structure for table `invoice_lines`
--

DROP TABLE IF EXISTS `invoice_lines`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `invoice_lines` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `invoice_id` int unsigned DEFAULT NULL,
  `price_per_unit` double(8,2) unsigned NOT NULL,
  `qty` int unsigned NOT NULL DEFAULT '1',
  `vat_percentage` double(8,2) unsigned NOT NULL,
  `sub_total` double(8,2) unsigned GENERATED ALWAYS AS (round((`price_per_unit` * `qty`),2)) STORED,
  `vat_amount` double(8,2) unsigned GENERATED ALWAYS AS (round(((`sub_total` / 100) * `vat_percentage`),2)) STORED,
  `total` double(8,2) unsigned GENERATED ALWAYS AS (round((`sub_total` + `vat_amount`),2)) STORED,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `invoice_lines_invoice_id_foreign` (`invoice_id`),
  CONSTRAINT `invoice_lines_invoice_id_foreign` FOREIGN KEY (`invoice_id`) REFERENCES `invoices` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `invoice_lines`
--

LOCK TABLES `invoice_lines` WRITE;
/*!40000 ALTER TABLE `invoice_lines` DISABLE KEYS */;
INSERT INTO `invoice_lines` VALUES (1,1,9.95,1,0.00,9.95,0.00,9.95,'2021-05-24 12:00:00','2021-05-24 12:00:00');
/*!40000 ALTER TABLE `invoice_lines` ENABLE KEYS */;
UNLOCK TABLES;
```

#### Steps to reproduce, if exist:
Create table with a GENERATED column
Insert values
Dump database
Restore databes (this won't work because the dumped sql is already incorrect)

#### Include any warning/errors/backtraces from the logs
`SQL Error [3105] [HY000]: (conn=1119) The value specified for generated column 'sub_total' in table 'invoice_lines' is not allowed.`

**Comment by uslss** [comment]
thank you for the report
could you try to use an up-to-date local Mysql client? Probably MySQL client in dbeaver is outdated

**Comment by arnovanoordt** [comment]
> could you try to use an up-to-date local Mysql client? Probably MySQL client in dbeaver is outdated

Same with eg MariaDB 10.4

**Comment by LonwoLonwo** [comment]
Hello @arnovanoordt 

It seems that this is a well-known problem: https://stackoverflow.com/a/68407184/14220989

Unfortunately, I did not find any options that would help ignore the generated columns in the INSERT: https://mariadb.com/kb/en/mysqldump/#options

So I tried to create a dump with MySQL 8.0 server and it helped (no GENERATED columns in the INSERT statement):

```
DROP TABLE IF EXISTS `invoice_lines`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `invoice_lines` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `invoice_id` int unsigned DEFAULT NULL,
  `price_per_unit` double(8,2) unsigned NOT NULL,
  `qty` int unsigned NOT NULL DEFAULT '1',
  `vat_percentage` double(8,2) unsigned NOT NULL,
  `sub_total` double(8,2) unsigned GENERATED ALWAYS AS (round((`price_per_unit` * `qty`),2)) STORED,
  `vat_amount` double(8,2) unsigned GENERATED ALWAYS AS (round(((`sub_total` / 100) * `vat_percentage`),2)) STORED,
  `total` double(8,2) unsigned GENERATED ALWAYS AS (round((`sub_total` + `vat_amount`),2)) STORED,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `invoice_lines_invoice_id_foreign` (`invoice_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `invoice_lines`
--

LOCK TABLES `invoice_lines` WRITE;
/*!40000 ALTER TABLE `invoice_lines` DISABLE KEYS */;
INSERT INTO `invoice_lines` (`id`, `invoice_id`, `price_per_unit`, `qty`, `vat_percentage`, `created_at`, `updated_at`) VALUES (4,1,123.00,1,12.00,'2021-10-11 05:47:15','2021-10-11 05:47:17');
/*!40000 ALTER TABLE `invoice_lines` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
```

So, my advice - please, use MySQL dump, not Maria dump for these tables with generated columns.
