### ISSUE TITLE
cannot open procedure inside package in oracle database

### ISSUE THREAD

**Issue by faroukelabady** [dbeaver/dbeaver#12974]
#### System information: 
-  kDE Neon 5.22.2
- DBeaver 21.1.1
- Additional extensions

#### Connection specification:
- oracle
- oracle jdbc12.2.0.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
When trying to open procedure in oracle in the latest dbeaver it gives the following error
There is no handler to execute for command org.jkiss.dbeaver.ext.oracle.code.package.navigate
#### Steps to reproduce, if exist:
Install the latest dbeaver version
Try to open a procedure in existing oracle connection.

**Comment by uslss** [comment]
@faroukelabady ,
unfortunately, cannot reproduce it.
could you provide a video with the issue?

**Comment by faroukelabady** [comment]
Okay, after reinstalling, seems the issue is gone now, thanks a lot for your support.
