### ISSUE TITLE
User option Event missing and Grant options not working

### ISSUE THREAD

**Issue by ivolvicente** [dbeaver/dbeaver#12977]
#### System information: 
- Windows 10 remote access to Ubuntu 20.04
- DBeaver 21.1.1.202106210824
- Java 1.8.0_241

#### Connection specification:
- MariaDB 10.3.27
- Driver for MariaDB
- No (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I was creating users in new server, checking previleges from old servers to the new one, and then some users complain with errors on there work. After searching a bit some previleges are missing, I found them using other DB manager application.

Errors I have checked

- EVENT  - Not listed on Table Previleges
- GRANT - Can be checked on DBeaver list, but if active on another application will be showed unchecked

#### Steps to reproduce, if exist:

1. Create a new user, add all previleges list by DBeaver, then check again user previleges in another DB application
2. Uncheck Grant on DBeaver, save, Check in another application, save and recheck on DBeaver

![heidisql_kF0tUivtz5](https://user-images.githubusercontent.com/11926387/123276032-bcd73680-d4fc-11eb-893a-8a05c53b9b37.png)

**Comment by uslss** [comment]
thank you for the report

**Comment by LonwoLonwo** [comment]
Hello @ivolvicente 

You can find the "Event" privilege in the main (admin) privileges list.

![2021-08-30 10_18_36-DBeaver Ultimate 21 2 0 - test@%](https://user-images.githubusercontent.com/45152336/131301105-50dfc7b9-112e-4e85-8e60-0caf0dde8444.png)

**Comment by LonwoLonwo** [comment]
Also, I've added a grant option via DBeaver for my user and it appears in the MySQL Workbench privileges list.

![2021-08-30 10_29_19-DBeaver Ultimate 21 2 0 - test@%](https://user-images.githubusercontent.com/45152336/131302688-7e3c24c6-bff4-45a0-9e2d-ebf3ae277c63.png)

Statement for "Grant option" in DBeaver is

`GRANT Grant option ON schemaName.* TO 'userName'@'%';`

And what expression creates your other application for this "GRANT" privilege?

**Comment by ivolvicente** [comment]
> Hello @ivolvicente
> 
> You can find the "Event" privilege in the main (admin) privileges list.
> 
> ![2021-08-30 10_18_36-DBeaver Ultimate 21 2 0 - test@%](https://user-images.githubusercontent.com/45152336/131301105-50dfc7b9-112e-4e85-8e60-0caf0dde8444.png)

Hi @LonwoLonwo , thanks for your clarification, there is indeed the Event privilege on user Properties tab.

**Comment by ivolvicente** [comment]
> Also, I've added a grant option via DBeaver for my user and it appears in the MySQL Workbench privileges list.
> 
> ![2021-08-30 10_29_19-DBeaver Ultimate 21 2 0 - test@%](https://user-images.githubusercontent.com/45152336/131302688-7e3c24c6-bff4-45a0-9e2d-ebf3ae277c63.png)
> 
> Statement for "Grant option" in DBeaver is
> 
> `GRANT Grant option ON schemaName.* TO 'userName'@'%';`
> 
> And what expression creates your other application for this "GRANT" privilege?

By the way, the other application I tested is HeidiSQL.

I created a new user and set the GRANT privilege on HeidiSQL and the SQL execution will set user privilege USAGE

![heidisql_CbUYDhMgZ2](https://user-images.githubusercontent.com/11926387/131747955-679ae470-8773-4ad4-acf1-ba98c6e9bb96.png)

After all, this looks more an error on HeidiSQL than on DBeaver.

**Comment by LonwoLonwo** [comment]
Thanks for the feedback! 

It seems that all problems are solved, so I close the ticket. If you have some questions or problems associated with this ticket, you can reopen it or create a new one.
