### ISSUE TITLE
close windows left 

### ISSUE THREAD

**Issue by mortifia** [dbeaver/dbeaver#12989]
**Is your feature request related to a problem? Please describe.**
add an option to have close windows to left 
![image](https://user-images.githubusercontent.com/22671054/123400650-48f16880-d5a6-11eb-9b0c-1a5db6dce66c.png)

**Comment by uslss** [comment]
it is already implemented in tab context menu. Does it solve your issue?
![image](https://user-images.githubusercontent.com/31996417/123610052-e6e46d80-d808-11eb-9ad4-43c6f63fe634.png)
