### ISSUE TITLE
 I need your help

### ISSUE THREAD

**Issue by lzb-libra** [dbeaver/dbeaver#12987]
When I set dbeaver recently, I don't know what causes me not to display the result set when I execute multiple SQL statements at the same time。When I execute a SQL statement, the result set is normally displayed, but when I execute multiple SQL statements at the same time, I only have this page
![image](https://user-images.githubusercontent.com/63389341/123391645-d052d200-d5ce-11eb-95c8-992606b71a4b.png)
What settings should I modify to execute multiple SQL, and multiple SQL will display the result set

**Comment by ShadelessFox** [comment]
Hello @lzb-libra,

Your database may not support that feature.

Instead, you can use `Execute SQL Script` (<kbd>Alt+X</kbd>) to execute multiple SQL scripts.

More information you can find on our wiki: https://github.com/dbeaver/dbeaver/wiki/SQL-Execution
