### ISSUE TITLE
Setting active schema from navigator doesn't work for Sybase and MS SQL Server if it changes databases

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#12998]
#### System information: 
- DBeaver version 21.1.2
- Additional extensions

#### Connection specification:
- Database name and version SQL Server, Sybase
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
If the focus in Navigator is on any object lower than the database (e.g. Schema, table, column etc.) can't set active schema for SQL Editor from navigator if it is from a different database than a current one.

#### Steps to reproduce, if exist:
1. Try setting active schema from navigator by highlighting a schema in different database.

**Expected:** Active schema is set.
**Actual:** For MS SQL nothing changes.
For Sybase there is also an error
`SQL Error [911] [ZZZZZ]: Attempt to locate entry in sysdatabases for database 'dbo' by name failed - no entry found under that name. Make sure that name is entered properly.`

![2021-06-25_15h21_04](https://user-images.githubusercontent.com/82543000/123424850-10fc1c80-d5ca-11eb-9f0b-9e891895b4f2.gif)
![2021-06-25_15h28_02](https://user-images.githubusercontent.com/82543000/123424852-122d4980-d5ca-11eb-83a9-7d87fb3eff8b.gif)

**Comment by serge-rider** [comment]
Active schema can't be changed in SQL Server and Sybase. It is database system limitation.
