### ISSUE TITLE
Need to reinstall extension 

### ISSUE THREAD

**Issue by I33Buckler** [dbeaver/dbeaver#12990]
- Debian 10.10 - x86_64 GNU/Linux
- DBeaver version 21.1.1.202106210824
- SSHJ

#### Connection specification:
- PostgreSQL 11
- PostgreSQL
- SSH connection to database
#### Describe the problem you're observing:
SSHJ extension has to be reinstalled often
#### Steps to reproduce, if exist:
On restarting DBeaver after a while the SSH connection to the server fails. On reviewing the connection the SSHJ extension has disappeared from the Implementation list in the SSH tunnel window.
Subsequently SSHJ is reinstalled and connection reestablished.
For a while the extension remains available in subsequent restarts of DBeaver. However, at some stage with no apparent message the SSHJ extension disappears.
This appears to happen after the computer has been suspended.
Unable to find mention of SSH or Extension in the log files.

**Comment by uslss** [comment]
unfortunately, cannot reproduce it. How do you install dbeaver?

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If the issue is still actual - feel free to reopen it
