### ISSUE TITLE
Show statistics info for Sybase connections

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#12992]
We need to add statistics info for Sybase. Right now it doesn't show anything even if this option is enabled for the connection.

**Comment by LonwoLonwo** [comment]
http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc00976.1502/html/statistics/statistics33.htm 
systabstats can be very helpful for this

**Comment by LonwoLonwo** [comment]
`EXEC sp_spaceused N'TableName'`

**Comment by LonwoLonwo** [comment]
Implemented for Sybase versions >= 15.

**Comment by uslss** [comment]
verified for sybase and sql server
