### ISSUE TITLE
Cannot Import Databases

### ISSUE THREAD

**Issue by Wepz** [dbeaver/dbeaver#12993]
#### System information: 
- Windows 10
- Community Edition 21.1.1

#### Describe the problem you're observing:

I just installed dbeaver community, I'm trying to import a new database and the following error appears:

Error executing process
  Cannot run program "{user}\AppData\Roaming\DBeaverData\drivers\clients\mysql\win\mysql.exe" (in directory "{user}\AppData\Roaming\DBeaverData\drivers\clients\mysql\win"): CreateProcess error=193, %1 is not an Win32 valid aplication
  
Cannot run program "{user}\AppData\Roaming\DBeaverData\drivers\clients\mysql\win\mysql.exe" (in directory "{user}\AppData\Roaming\DBeaverData\drivers\clients\mysql\win"): CreateProcess error=193, %1 is not an Win32 valid aplication
    
CreateProcess error=193, %1 is not an Win32 valid aplication
    CreateProcess error=193, %1 is not an Win32 valid aplication

**Comment by uslss** [comment]
@Wepz could you provide steps to reproduce an issue?

**Comment by Wepz** [comment]
@uslss Hi, I just tryed to import a database from a colegue, and it works fine, its well exported by his side, when I go to dBeaver and I try to "restore database" to import the data and that error appears.

**Comment by uslss** [comment]
seems something going wrong with mysql client. could you try to manually delete files from {user}\AppData\Roaming\DBeaverData\drivers\clients\mysql\win and try to start restore once again?

**Comment by Wepz** [comment]
@uslss 
Thanks for the information,
I deleted that folder and reinstalled dBeaver and the error persists, I'm using now MySQL Workbench.
Don't know why dBeaver didm't work for me

**Comment by Matvey16** [comment]
@Wepz If you have MySQL Workbench installed, you can try changing path to it's mysql.exe in DBeaver.

![dbeaver_yUzZdELgft](https://user-images.githubusercontent.com/82543000/125289132-8cc6ca80-e327-11eb-8ff4-3ffff21f6a11.png)

![dbeaver_gDTQOlUggF](https://user-images.githubusercontent.com/82543000/125289145-918b7e80-e327-11eb-83de-6d2624e2e874.png)

**Comment by uslss** [comment]
there is no update on issue for a long time.
If it is still actual - feel free to reopen it with an additional info that will help to reproduce an issue.
