### ISSUE TITLE
Import data from CSV

### ISSUE THREAD

**Issue by r-richmond** [dbeaver/dbeaver#130]
Currently if you right-click on a table and select import data you are presented with a dialog asking for the source container which is a list of data sources.

Requesting that you add a flat file option. (without having to create a csv data source)

edit: [step-by-step guide](https://justnumbersandthings.com/post/2018-06-12-dbeaver-import-csv/) to import data from a CSV using the data source option

**Comment by deragon** [comment]
This is a basic feature missing.  As a new user, it was the first thing I wanted to perform and could not.  Also, loading from an SQL file containing insert statements should also be provided.  Not sure if this should be a separate feature request or not.

**Comment by r-richmond** [comment]
After playing around with the CSV data source option I feel like this priority of this request is very low.

The CSV Data Source gives incredible flexibility. Great Tool @serge-rider

**Comment by fancywriter** [comment]
I am signing that this feature would be very useful.

**Comment by vcsekhar** [comment]
With ref - [Managing Connections](https://github.com/serge-rider/dbeaver/wiki/Admin-Manage-Connections) to the steps to import datasources from a csv file, I tried and couldn't get them to work.

Ref: 
![image](https://cloud.githubusercontent.com/assets/1406424/21688714/e7a5f5e4-d33b-11e6-9dc1-b3bbc6cd11b8.png)

Am I missing something in getting this to work. Please advise.

Thanks in advance.

**Comment by serge-rider** [comment]
This is a completely different issue (not related to data import).
Please create another issue and attach sample CSV (or XML) file you are trying to import.

**Comment by huygir** [comment]
Creating a connection just to be able to import a CSV as data into a database is fraught with problems and is frankly a total pain in the butt.  No other DB or CRM management tool in the world requires that much work to simply load a CSV.  This is a deal breaker feature for me because the process of creating a connection for flat files always fails and is not portable (have to do it everywhere I use the tool and it's unique to the machine since the source is local).

**Comment by tdgroot** [comment]
@huygir please feel free to create a pull request or move on.

**Comment by serge-rider** [comment]
@tdgroot in fact this ticket is feature request, there is no need to create another one :)

@huygir making a connection for CSV is a kind of workaround. Generally importing from CSV is a complicated task which requires complicated UI with lots of config options. That's why it is still not implemented. Hopefully we'll find resources for it after 5.1 release.

**Comment by kactetus** [comment]
holy f*ck  this issues opened on 21 Dec 2015 and no import from csv to database ( (3 years gone)

**Comment by r-richmond** [comment]
After reading @kactetus 's post I feel like the title of this issue is misleading; I blame the OP. Importing CSVs using DBeaver is possible and I have probably imported hundreds. That said new users can face a little bit of confusion when first trying to import a CSV. DBeaver's requirement that a CSV connection be setup first is a little unusual but not a deal-breaker and is actually quite beneficial as you can use the connection to query your CSVs as well.

For those just looking for a step-by-step guide on importing data from a CSV here is a quick [write-up](https://justnumbersandthings.com/post/2018-06-12-dbeaver-import-csv/)

p.s. @serge-rider I'd just like to reiterate again that you've made a great tool; thanks for all of your hard work

**Comment by vishal786btc** [comment]
it does imports csv/flat files but the issue is one csv connection can handle only one type delimiter. It should be able to custom define the delimiter before the import of each table.

**Comment by serge-rider** [comment]
Direct CSV import will be added in the next version.
Further improvements of file->database import should be tracked in separate tickets.

![image](https://user-images.githubusercontent.com/6398845/43958286-80ff5568-9cb3-11e8-966f-8468cc14f5e0.png)

![image](https://user-images.githubusercontent.com/6398845/43958235-6081d158-9cb3-11e8-8583-a8b558b4a16b.png)

**Comment by serge-rider** [comment]
@sudila Please crate a separate ticket for that. This seems to be Impala-specific.
