### ISSUE TITLE
-infinity is out of order

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#13008]
#### System information: 
- Operating system LinuxMint 19.3
- DBeaver version 21.0.3

#### Connection specification:
- Database name and version: PG v13.1

#### Describe the problem you're observing:
When I try to order data I get wrong order

#### Steps to reproduce, if exist:
Click to sort data

Actual:
![image](https://user-images.githubusercontent.com/799021/123522700-a3ceb100-d6c7-11eb-86c0-7fdda3a92323.png)

expected:
![image](https://user-images.githubusercontent.com/799021/123522711-b5b05400-d6c7-11eb-97dd-5c5c275377f9.png)

Notice how database sorts data (expected) and how sorts DBeaver (actual)

**Comment by Matvey16** [comment]
Hello @KES777 Thank you for the report. Can you specify where you see this kind of sorting. I was not able to reproduce it.
If it is like that in Data Viewer, can you make sure that you don't have sorting on another column as well as the one with infinity ranges.

![2021-06-28_11h13_03](https://user-images.githubusercontent.com/82543000/123602952-03c97280-d802-11eb-8659-299ad22ec5bd.gif)

**Comment by uslss** [comment]
there is no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
