### ISSUE TITLE
Results upload button not enabled

### ISSUE THREAD

**Issue by artgoldberg** [dbeaver/dbeaver#13009]
Thank you for making DBeaver, it's great. But it still has a few problems. Here's one.
#### System information: 
- Operating system: MacOS Big Sur: 11.2.3 (20D91)
- DBeaver version: DBeaver Enterprise Edition: Version 7.3.0.202012061950

#### Connection specification:
- Database name and version: Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64) 
	Sep 24 2019 13:48:23 
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)
- Driver name: don't know
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: Yes, F5 Big-Ip

#### Describe the problem you're observing:
Quite often, after DBeaver executes a query, the results upload button is not enabled. I find that clicking on other tabs and then returning to the tab that the results upload button suddenly becomes enabled. See [a video which documents the problem](https://www.youtube.com/watch?v=hu9WlOMNnjs). At [this time](https://youtu.be/hu9WlOMNnjs?t=7) you see the problem; after clicking on a couple of tabs, the [upload link becomes enabled](https://youtu.be/hu9WlOMNnjs?t=16).

#### Steps to reproduce, if exist:
This occurs on many queries I run.

**Comment by Matvey16** [comment]
Hello @artgoldberg Thank you for the report. Does this issue reproduce on the latest 21.1 version?
Also maybe you have noticed if there is some similiarity in queries that lead to this or are they completely different?

**Comment by artgoldberg** [comment]
Hi @Matvey16 
This problem does not occur for me in version 21.1
