### ISSUE TITLE
Autocomplete works incorrectly for table names in quotes

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13004]
#### System information: 
- DBeaver version 21.1.2

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
Autocomplete doesn't propose or proposes columns from a different table if a table name is fully qualified and in quotes, but current active schema is a different from the one that contains the table.

#### Steps to reproduce, if exist:
1. Set any schema as active in SQL Editor
2. Type any statement.
3. Start typing full name of the column for the table from another schema with quotes e. g. `schema_name."table.name".`
4. Press `Ctrl + Space`

**Expected:** Column names from the correct table are proposed.
**Actual:** Either `no proposals` or columns from a different table.

![2021-06-25_13h55_40](https://user-images.githubusercontent.com/82543000/123439746-b61ef100-d5da-11eb-99c8-dc84bc679f62.png)

**Comment by ayan84** [comment]
I am also searching for such a problem's solution, but where you find version 21.1.2? I currently found version 21.1.1 in download section.

**Comment by KES777** [comment]
@ayan84 It seems he is a developer (or tester). Notice `member` badge ;-)

**Comment by ayan84** [comment]
@KES777 , Got it. Anyway, happy to know the problem resolved. I am being fond of this ide, and I ready to abandon Navicat and even SSMS for query purposes.

**Comment by Matvey16** [comment]
@ayan84 Hello. You can download the latest early access version from https://dbeaver.io/files/ea/ It is currently still 21.1.1 but has a lot of bugs fixed and new features added.
This particular issue is palnned to be fixed in 21.2.0

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.2.0

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
