### ISSUE TITLE
Generate elements aligned to grid

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#13003]
![image](https://user-images.githubusercontent.com/799021/123439738-b4552d80-d5da-11eb-86e3-39e075078b02.png)

Align elements to grid. Because without that if I move something then I can not put it back. It become aligned to different grid.

Notice, I have moved `pg_inherits` and it aligned to grid, but it is not in sync with `enabled_roles` which was generated and aligned by DBeaver

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by ShadelessFox** [comment]
Implemented. Works only if you had grid enabled previously (also snaps to grid's size):

![image](https://user-images.githubusercontent.com/35821147/127684960-939646c9-c563-46db-9fec-3652ad4010e6.png)

**Comment by uslss** [comment]
verified
