### ISSUE TITLE
ERROR WHEN OPEN DBEAVER

### ISSUE THREAD

**Issue by straninho1** [dbeaver/dbeaver#13018]
!ENTRY org.eclipse.equinox.p2.repository.tools 4 0 2021-06-28 14:35:01.523
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.p2.repository.tools [111]
  Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.artifact.processors.checksum
    -> Export-Package: org.eclipse.equinox.internal.p2.artifact.processors.checksum; bundle-symbolic-name="org.eclipse.equinox.p2.artifact.repository"; bundle-version="1.4.0.v20210129-2007"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.publisher"
       org.eclipse.equinox.p2.artifact.repository [92]
         Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.persistence
           -> Export-Package: org.eclipse.equinox.internal.p2.persistence; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.ui.importexport,  org.eclipse.equinox.p2.repository.tools"
              org.eclipse.equinox.p2.repository [110]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
         Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.repository
           -> Export-Package: org.eclipse.equinox.internal.p2.repository; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.updatesite,  org.eclipse.equinox.p2.repository.tools,  org.eclipse.equinox.p2.transport.ecf,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.discovery.compatibility,  org.eclipse.equinox.p2.publisher"
  Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.artifact.repository
    -> Export-Package: org.eclipse.equinox.internal.p2.artifact.repository; bundle-symbolic-name="org.eclipse.equinox.p2.artifact.repository"; bundle-version="1.4.0.v20210129-2007"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.publisher,  org.eclipse.equinox.p2.reconciler.dropins,  org.eclipse.equinox.p2.ui,  org.eclipse.equinox.p2.directorywatcher,  org.eclipse.equinox.p2.repository.tools,  org.eclipse.equinox.p2.publisher.eclipse"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.equinox.p2.touchpoint.eclipse 4 0 2021-06-28 14:35:01.524
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.p2.touchpoint.eclipse [112]
  Unresolved requirement: Import-Package: org.eclipse.equinox.internal.provisional.p2.repository
    -> Export-Package: org.eclipse.equinox.internal.provisional.p2.repository; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"
       org.eclipse.equinox.p2.repository [110]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
  Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.garbagecollector
    -> Export-Package: org.eclipse.equinox.internal.p2.garbagecollector; bundle-symbolic-name="org.eclipse.equinox.p2.garbagecollector"; bundle-version="1.1.400.v20200221-1022"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.touchpoint.eclipse,org.eclipse.pde.core,org.eclipse.equinox.p2.ui.sdk.scheduler"
       org.eclipse.equinox.p2.garbagecollector [102]
         Unresolved requirement: Import-Package: org.eclipse.equinox.p2.repository; version="[2.0.0,3.0.0)"
           -> Export-Package: org.eclipse.equinox.p2.repository; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="2.0.0"
  Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.engine
    -> Export-Package: org.eclipse.equinox.internal.p2.engine; bundle-symbolic-name="org.eclipse.equinox.p2.engine"; bundle-version="2.6.700.v20200511-1530"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.garbagecollector,  org.eclipse.equinox.p2.repository.tools,  org.eclipse.equinox.p2.touchpoint.eclipse,  org.eclipse.equinox.p2.touchpoint.natives,  org.eclipse.equinox.p2.ui.sdk.scheduler,  org.eclipse.pde.build,  org.eclipse.equinox.p2.director.app"
       org.eclipse.equinox.p2.engine [100]
         Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.persistence
           -> Export-Package: org.eclipse.equinox.internal.p2.persistence; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.ui.importexport,  org.eclipse.equinox.p2.repository.tools"
         Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.metadata.repository.io
           -> Export-Package: org.eclipse.equinox.internal.p2.metadata.repository.io; bundle-symbolic-name="org.eclipse.equinox.p2.metadata.repository"; bundle-version="1.3.500.v20210108-0738"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.engine"
              org.eclipse.equinox.p2.metadata.repository [105]
                Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.repository
                  -> Export-Package: org.eclipse.equinox.internal.p2.repository; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.updatesite,  org.eclipse.equinox.p2.repository.tools,  org.eclipse.equinox.p2.transport.ecf,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.discovery.compatibility,  org.eclipse.equinox.p2.publisher"
                Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.persistence
                  -> Export-Package: org.eclipse.equinox.internal.p2.persistence; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.ui.importexport,  org.eclipse.equinox.p2.repository.tools"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.equinox.p2.touchpoint.natives 4 0 2021-06-28 14:35:01.529
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.p2.touchpoint.natives [113]
  Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.engine
    -> Export-Package: org.eclipse.equinox.internal.p2.engine; bundle-symbolic-name="org.eclipse.equinox.p2.engine"; bundle-version="2.6.700.v20200511-1530"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.garbagecollector,  org.eclipse.equinox.p2.repository.tools,  org.eclipse.equinox.p2.touchpoint.eclipse,  org.eclipse.equinox.p2.touchpoint.natives,  org.eclipse.equinox.p2.ui.sdk.scheduler,  org.eclipse.pde.build,  org.eclipse.equinox.p2.director.app"
       org.eclipse.equinox.p2.engine [100]
         Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.persistence
           -> Export-Package: org.eclipse.equinox.internal.p2.persistence; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.ui.importexport,  org.eclipse.equinox.p2.repository.tools"
              org.eclipse.equinox.p2.repository [110]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
         Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.metadata.repository.io
           -> Export-Package: org.eclipse.equinox.internal.p2.metadata.repository.io; bundle-symbolic-name="org.eclipse.equinox.p2.metadata.repository"; bundle-version="1.3.500.v20210108-0738"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.engine"
              org.eclipse.equinox.p2.metadata.repository [105]
                Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.repository
                  -> Export-Package: org.eclipse.equinox.internal.p2.repository; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.updatesite,  org.eclipse.equinox.p2.repository.tools,  org.eclipse.equinox.p2.transport.ecf,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.discovery.compatibility,  org.eclipse.equinox.p2.publisher"
                Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.persistence
                  -> Export-Package: org.eclipse.equinox.internal.p2.persistence; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.ui.importexport,  org.eclipse.equinox.p2.repository.tools"
  Unresolved requirement: Import-Package: org.eclipse.equinox.p2.engine; version="[2.0.0,3.0.0)"
    -> Export-Package: org.eclipse.equinox.p2.engine; bundle-symbolic-name="org.eclipse.equinox.p2.engine"; bundle-version="2.6.700.v20200511-1530"; version="2.2.0"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.equinox.p2.transport.ecf 4 0 2021-06-28 14:35:01.531
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.p2.transport.ecf [114]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
  Unresolved requirement: Require-Bundle: org.eclipse.equinox.p2.repository; bundle-version="2.1.0"
    -> Bundle-SymbolicName: org.eclipse.equinox.p2.repository; bundle-version="2.5.0.v20201013-0853"; singleton:="true"
       org.eclipse.equinox.p2.repository [110]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.equinox.p2.ui 4 0 2021-06-28 14:35:01.533
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.p2.ui [115]
  Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.metadata.repository
    -> Export-Package: org.eclipse.equinox.internal.p2.metadata.repository; bundle-symbolic-name="org.eclipse.equinox.p2.metadata.repository"; bundle-version="1.3.500.v20210108-0738"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.publisher,  org.eclipse.equinox.p2.reconciler.dropins,  org.eclipse.equinox.p2.ui,  org.eclipse.equinox.p2.updatesite,  org.eclipse.equinox.p2.extensionlocation,  org.eclipse.equinox.p2.repository.tools,  org.eclipse.equinox.p2.publisher.eclipse"
       org.eclipse.equinox.p2.metadata.repository [105]
         Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.persistence
           -> Export-Package: org.eclipse.equinox.internal.p2.persistence; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.ui.importexport,  org.eclipse.equinox.p2.repository.tools"
              org.eclipse.equinox.p2.repository [110]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
  Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.artifact.repository
    -> Export-Package: org.eclipse.equinox.internal.p2.artifact.repository; bundle-symbolic-name="org.eclipse.equinox.p2.artifact.repository"; bundle-version="1.4.0.v20210129-2007"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.publisher,  org.eclipse.equinox.p2.reconciler.dropins,  org.eclipse.equinox.p2.ui,  org.eclipse.equinox.p2.directorywatcher,  org.eclipse.equinox.p2.repository.tools,  org.eclipse.equinox.p2.publisher.eclipse"
       org.eclipse.equinox.p2.artifact.repository [92]
         Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.persistence
           -> Export-Package: org.eclipse.equinox.internal.p2.persistence; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.ui.importexport,  org.eclipse.equinox.p2.repository.tools"
         Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.repository
           -> Export-Package: org.eclipse.equinox.internal.p2.repository; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.updatesite,  org.eclipse.equinox.p2.repository.tools,  org.eclipse.equinox.p2.transport.ecf,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.discovery.compatibility,  org.eclipse.equinox.p2.publisher"
  Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.director
    -> Export-Package: org.eclipse.equinox.internal.p2.director; bundle-symbolic-name="org.eclipse.equinox.p2.director"; bundle-version="2.4.700.v20200511-1530"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.operations,  org.eclipse.equinox.p2.repository.tools,  org.eclipse.pde.core,  org.eclipse.equinox.p2.reconciler.dropins,  org.eclipse.equinox.p2.ui,  org.eclipse.equinox.p2.director.app"
       org.eclipse.equinox.p2.director [95]
         Unresolved requirement: Import-Package: org.eclipse.equinox.p2.engine; version="[2.0.0,3.0.0)"
           -> Export-Package: org.eclipse.equinox.p2.engine; bundle-symbolic-name="org.eclipse.equinox.p2.engine"; bundle-version="2.6.700.v20200511-1530"; version="2.2.0"
              org.eclipse.equinox.p2.engine [100]
                Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.persistence
                  -> Export-Package: org.eclipse.equinox.internal.p2.persistence; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.ui.importexport,  org.eclipse.equinox.p2.repository.tools"
                Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.metadata.repository.io
                  -> Export-Package: org.eclipse.equinox.internal.p2.metadata.repository.io; bundle-symbolic-name="org.eclipse.equinox.p2.metadata.repository"; bundle-version="1.3.500.v20210108-0738"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.engine"
         Unresolved requirement: Import-Package: org.eclipse.equinox.p2.engine.query; version="[2.0.0,3.0.0)"
           -> Export-Package: org.eclipse.equinox.p2.engine.query; bundle-symbolic-name="org.eclipse.equinox.p2.engine"; bundle-version="2.6.700.v20200511-1530"; version="2.0.0"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.equinox.p2.ui.importexport 4 0 2021-06-28 14:35:01.537
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.p2.ui.importexport [117]
  Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.metadata.repository.io
    -> Export-Package: org.eclipse.equinox.internal.p2.metadata.repository.io; bundle-symbolic-name="org.eclipse.equinox.p2.metadata.repository"; bundle-version="1.3.500.v20210108-0738"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.engine"
       org.eclipse.equinox.p2.metadata.repository [105]
         Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.repository
           -> Export-Package: org.eclipse.equinox.internal.p2.repository; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.updatesite,  org.eclipse.equinox.p2.repository.tools,  org.eclipse.equinox.p2.transport.ecf,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.discovery.compatibility,  org.eclipse.equinox.p2.publisher"
              org.eclipse.equinox.p2.repository [110]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
         Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.persistence
           -> Export-Package: org.eclipse.equinox.internal.p2.persistence; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.ui.importexport,  org.eclipse.equinox.p2.repository.tools"
  Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.persistence
    -> Export-Package: org.eclipse.equinox.internal.p2.persistence; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20201013-0853"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.ui.importexport,  org.eclipse.equinox.p2.repository.tools"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

**Comment by uslss** [comment]
there is not enough info to investigate an issue.
please, report an issue accordingly to [template](https://github.com/dbeaver/dbeaver/issues/new?assignees=&labels=bug%2C+wait+for+review&template=bug_report.md&title=)

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If the issue is still actual - feel free to reopen it
