### ISSUE TITLE
Autocommit should always be disabled by default

### ISSUE THREAD

**Issue by heyciao** [dbeaver/dbeaver#13010]
Hi

Current situation:
autocommit is enabled for all connections tagged as non-"Production".

Problem nbr1:
the "connection type" is often ignored by users during the setup of the connection (e.g. no warning stating that "autocommit" will be on), thinking that it's just a "label" or something similar (I personally didn't even notice that categorization).

Problem nbr2:
different behaviour for people that transition between DEV and Prod Support roles.

Proposed fix:
have autocommit always disabled.

Details:
I initially tried to push the company that I'm working for to use DBeaver, but having "autocommit" switched on by default is suicide (even for me).
I'm permanently super-stressed, same for my colleagues, so paying attention to the association to the connection type (Development/Test/Production) for the hundreds of DBs that we have, when the connection is set up, is unrealistic.
Even for development/test I would personally not like any default-autocommit-behaviour.

Personal opinion:
- autocommit-by-default was maybe ok in your early days to keep support effort low by avoiding stupid questions (e.g. "my data is not being stored", etc...).
- if you want to be accepted as a serious tool, having autocommit switched on by default (for any environment) is like shooting yourself in the foot.

Thank you

**Comment by p91paul** [comment]
you can also change default autocommit setting for all connection types in global preferences

**Comment by ShadelessFox** [comment]
Also, you can switch connection type to `Production`.

https://github.com/dbeaver/dbeaver/wiki/Connection-Types
