### ISSUE TITLE
Fetched rows aren't visible in Record mode

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#13038]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.1.2 EA
related to #7014 
#### Describe the problem you're observing:
Fetch buttons are available, after switching to record view dbeaver automatically fetch next rows, but newly fetched rows are shown only after switching to table mode and then back to the record mode. Multi record view switches to single record view after table refresh.
![2021-06-25_15h43_16](https://user-images.githubusercontent.com/31996417/123426521-2ffbae00-d5cc-11eb-92cb-df81064d5047.gif)

**Comment by serge-rider** [comment]
It is not a bug. In order to scroll rows in record mode you need to use navigation buttons in the toolbar (prev, next, home, end).
Records are not populated automatically on Fetch All action (it works as expected).
