### ISSUE TITLE
Can't extract field 'xxxx' error

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#13037]
#### System information: 
- Linux Mint v19.3
- DBeaver version 21.0.3

#### Connection specification:
- PG v13.1

#### Describe the problem you're observing:
when composite value is null DBeaver tries to extract field value and get error. 
This error I never see at earlier versions, but latest one has.
You can see if I expand composite field by server I get correct NULL values, but when this do DBeaver I get the error

#### Steps to reproduce, if exist:
Try to select composite value which evaluates to NULL
Notice `sp` and `sp.*`

![image](https://user-images.githubusercontent.com/799021/123922826-1920d700-d991-11eb-957c-03cb94bc5e14.png)

**Comment by Matvey16** [comment]
Doesn't reproduce in my database. Can you please provide full query that leads to this error and a DDL for the table and composite data type you are using in this example?

**Comment by KES777** [comment]
https://github.com/dbeaver/dbeaver/issues/6228

**Comment by KES777** [comment]
notice, at DBeaver v6 I did not meet such error, It appear after upgrading to v21

**Comment by Matvey16** [comment]
@KES777 There are a lot of information in #6228 and it is not clear which of it is connected to this issue.
If you can, please look at my example below and say what may be different there that leads to issue not reproducing.


![dbeaver_etrYU1Qi0o](https://user-images.githubusercontent.com/82543000/124747816-0aa36400-df2b-11eb-90c3-dba86a36b690.png)

**Comment by Matvey16** [comment]
Also please attach a log that accompanies this issue

**Comment by uslss** [comment]
there is no update on issue for a long time.
If it is still actual - feel free to reopen it with an additional info that will help to reproduce an issue.
