### ISSUE TITLE
nvarchar fields (unicode) are displayed as NULL

### ISSUE THREAD

**Issue by ayuksekdag** [dbeaver/dbeaver#13035]
#### System information: 
- Windows 10 
- Dbeaver Version 21.1.1.202106210824
- 

#### Connection specification:
- SQL Server azure 
- JDBC bridge to MS ODBC driver 17 for SQL server  and using MFA auth from ODBC

#### Describe the problem you're observing:

SQL selection of any database object that has nvarchar fields. Only those fields are displayed as NULL. 
To display the nvarchar I need to cast it to display

#### Steps to reproduce, if exist:

SELECT getdate();
result as expected

select cast(getdate() as nvarchar)
null

**Comment by ShadelessFox** [comment]
Hello @ayuksekdag,

The issue is probably with the driver itself. Using `mssql-jdbc` the provided query works just fine:

![image](https://user-images.githubusercontent.com/35821147/123935299-c4835900-d99c-11eb-87cb-0ee5a55a7ca5.png)

Can you try using this driver instead? It's just listed as `SQL Server` in the driver manager.

**Comment by ayuksekdag** [comment]
I've tried that driver. It doesnt work with MFA.  it gives error 
'Failed to load MSAL4J Java library for performing ActiveDirectoryInteractive authentication'

Then I add the jar MSAL4J msal4j-1.10.1.jar to the path. It continues with errors 
'com.nimbusds.oauth2.sdk.auth.ClientAuthentication'

The lastest version of dbeaver says it supports Multi factor auth (MFA) .

Smehow I am mixing up java version or something
See pcicture for my settings

![image](https://user-images.githubusercontent.com/32957368/123942738-bb45bc80-d99b-11eb-8546-7fc6fb05417a.png)

**Comment by serge-rider** [comment]
You should use `Azure SQL Server` driver in order to use MFA authentication. It contains all required dependencies.

**Comment by ayuksekdag** [comment]
Hi Serge, 
This is the solution I was looking for. I can lnow ogin and unicode nvarchars are visible.
The only problem I have now is the browser popups everytime I open a new sqleditor (because of MFA). but this is luxery problem :)

Thanks for the fast reply

**Comment by ayuksekdag** [comment]
see above
