### ISSUE TITLE
SqlServer: INCLUDE index column are shown as they were index column

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#13034]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.1.0.202105300349
- Additional extensions: n/a

#### Connection specification:
- Database name and version: Sql Server 2016
- Driver name: Microsoft
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  n/a

#### Describe the problem you're observing:

Sql Server supports creating indexes with some column composing the index plus some "INCLUDE" columns, which are stored within the index for fast retrieval but are not, in fact, indexed.
The following index:

```
CREATE NONCLUSTERED INDEX [test_idx]
    ON dbo.[test] ([x1],[x2])
    INCLUDE ([x3])
```

is shown as if it was created with this (very different) instruction:

```
CREATE NONCLUSTERED INDEX [test_idx]
    ON dbo.[test] ([x3],[x1],[x2])
```

![immagine](https://user-images.githubusercontent.com/2157006/123862930-3e79fa80-d929-11eb-86d7-ad7e9c47af78.png)

This is how SMSS displays this index instead, with a clear distinction between key columns and include columns (of course DBeaver interface is much different so you cannot take ideas from this):

![immagine](https://user-images.githubusercontent.com/2157006/123863422-ded01f00-d929-11eb-84a8-b5e0a5923c53.png)
![immagine](https://user-images.githubusercontent.com/2157006/123863449-e8598700-d929-11eb-9588-f921c57302d9.png)

#### Steps to reproduce, if exist:
```
create table dbo.test (
    x1 integer,
    x2 integer,
    x3 integer
)
go

CREATE NONCLUSTERED INDEX [test_idx]
    ON dbo.[test] ([x1],[x2])
    INCLUDE ([x3])
go
```

**Comment by uslss** [comment]
thank you for the report

**Comment by ShadelessFox** [comment]
Done:

![java_yShr92tHTw](https://user-images.githubusercontent.com/35821147/130430220-a582d0b8-42f3-4f24-b530-575e962095b3.png)

![image](https://user-images.githubusercontent.com/35821147/130430148-e43d8488-36bb-4815-adde-2ecee5827597.png)

**Comment by uslss** [comment]
verified
