### ISSUE TITLE
How to configure options for plan?

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#13030]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/799021/123799596-0d7dd380-d8f1-11eb-9df4-f7d83441bc34.png)

But there could be different `explain` queries:
```sql
explain (analyze, format json, verbose, costs ) etc
```

**Describe the solution you'd like**
A window where I can configure options for `explain`

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by uslss** [comment]
Analyze option is already available for PostgreSQL. 
![image](https://user-images.githubusercontent.com/31996417/133097193-59b8c843-4228-41d1-bd10-19506caf54ac.png)

Which else options should be implemented?

**Comment by KES777** [comment]
full list of options:
https://www.postgresql.org/docs/current/sql-explain.html

**Comment by uslss** [comment]
implemented in #16684
