### ISSUE TITLE
Object's header in spatial view changes to the value of the column named "id"

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13044]
#### System information: 
- DBeaver version 21.1.1

#### Steps to reproduce, if exist:
1. Create a table with a geometry column and a varchar or numeric column named "id"
2. In spatial view click on one of the objects

**Expected: ** Column name is in the header of description
**Actual:** Value from a column "id" is in the header

![2021-06-30_14h44_54](https://user-images.githubusercontent.com/82543000/123955119-ecc98280-d9b1-11eb-8ca8-1d71e64f3e53.gif)

**Comment by ShadelessFox** [comment]
Fixed:
1. Attributes with name like `id` and `color` would override layer's color and title
1. Different attributes would have the same color in value panel
1. An empty layer would display if no description columns are present
  
![idea64_Mnv9istCWE](https://user-images.githubusercontent.com/35821147/138698626-7ed9b9a9-4f1f-451c-a640-8c8429bd0fa1.png)

![idea64_0HmxFx0tfq](https://user-images.githubusercontent.com/35821147/138698621-f7030237-4ef7-44b0-826b-5440c61dcec5.png)

**Comment by uslss** [comment]
verified
