### ISSUE TITLE
Top combo schema selected not working

### ISSUE THREAD

**Issue by mikkk3l** [dbeaver/dbeaver#13042]
#### System information: 
- Operating system (distribution) and version Windows 10 64 bit
- DBeaver version 21.1.0
- Additional extensions

#### Connection specification:
- Database name and version DB2 z/OS
- Driver name ojdb8.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

It only fails with DB2 z/OS connection (with Oracle, for instance, it works). It worked OK even with DB2 previously up to DBeaver version 7.0.0. After that, it fails.

Initialization schema configured, you execute a query and it works the first time. Then you wait 30 minutes and when you come back, then execute a query with the same schema selected (you have not touched the dropdown select) and it does not propagate to the query so it fails with (Table <table> does not exist, because you are not in that schema.) If you reselect the same schema in the top combo, then it works again until you wait some minutes and back again to the same failure.

#### Steps to reproduce, if exist:

1. Configure DB2 z/OS connection
2. Configure a schema initialization different than the default one of the DB user
3. write a select of a table which is in the initialization schema. Execute it. It shoud run OK.
4. Wait for 30 minutes or so.
5. Try to reexecute again the query. It will fail
6. Deploy top schema combo to reselect the same schema that was selected.
7. Reexecute again the query. It will work.

#### Include any warning/errors/backtraces from the logs

![2021-06-30_DBeaver_schemaNotSelected](https://user-images.githubusercontent.com/15341836/123933368-9ac53480-d992-11eb-8ee6-7ba3a6c32593.gif)

**Comment by mikkk3l** [comment]
¿Any news? Thanks!!!

**Comment by Matvey16** [comment]
@mikkk3l Can you try it on the newest 21.2.3 version? It looks like this could have been fixed.

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still actual - feel free to reopen it

**Comment by mikkk3l** [comment]
Thanks! It is solved in version 21.2.4. Best regards.
