### ISSUE TITLE
Refresh switсhes multi-record view to single

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#13041]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.1.2 EA
- related to #7014 
#### Steps to reproduce, if exist:
1. Select some rows and switch to record view
2. Refresh table
Actual result: table switches from multi-view to single
![2021-06-30_11h49_01](https://user-images.githubusercontent.com/31996417/123931474-36f23a00-d999-11eb-9dc4-3b5e981022af.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
