### ISSUE TITLE
Column name is not displayed for a geometry object in Value panel

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13056]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.2

#### Steps to reproduce, if exist:
1. Select a gometry data in a table and open the Value panel
2. Click the object in the Value panel

**Expected**: the column name and data from other columns are displayed in the object info pop up
**Actual result**: the column name is not displayed

**Comment by Matvey16** [comment]
Not reproducible in 22.0.3
