### ISSUE TITLE
Remember Value Panel "Content viewer settings"

### ISSUE THREAD

**Issue by malammar** [dbeaver/dbeaver#13050]
**Is your feature request related to a problem? Please describe.**
There are many JSON-text fields in my databases and I LOVE the auto-format feature in the Value Panel/Content Viewer Settings. However, I wish that the panel remembered which columns I marked as JSON or guessed that the content of the column is JSON text. When I close the table and reopen it, the formatting persists. But when I close DBeaver completely and reopen it, the formatting is gone and I have to reapply JSON formatting again.

**Describe the solution you'd like**
When I click one of the formats in the Content viewer settings dropdown, it should remain selected for that connection/table/column across a program restart.

**Additional context**
![image](https://user-images.githubusercontent.com/839157/124015343-686b0580-d999-11eb-8deb-236705635d4e.png)

**Comment by uslss** [comment]
#10149
