### ISSUE TITLE
Not correct working with views

### ISSUE THREAD

**Issue by gr-sid** [dbeaver/dbeaver#13052]
#### System information: 
- Operating system (distribution) and version 
Linux Mint, Windows 10
- DBeaver version
21.0.2.202104042040
- Additional extensions
No

#### Connection specification:
- Database name and version
Oracle 10 (maybe the same in Postgres 13)
- Driver name
Standard (from maven)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
1) If there is a view with comments (for the main object and columns), there is not correct working due "Save view".
2) There is no saving.
3) Sometimes comments will be lost.

#### Steps to reproduce, if exist:
1) Create a view
2) Add comments to a view and its columns.
3) Try to change a view.
 
![image](https://user-images.githubusercontent.com/82018746/124088558-b8120580-da5b-11eb-804a-a7ec6599a0e1.png)

**Comment by uslss** [comment]
could you check if it reproducible for you against 21.1.1?

**Comment by uslss** [comment]
there is no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
