### ISSUE TITLE
firebird connection

### ISSUE THREAD

**Issue by WellingtonBS** [dbeaver/dbeaver#13051]
How to change the dialect of a connection. 

I'm with the error

SQL Error [335544793] [42000]: Dynamic SQL Error; SQL error code = -817; Metadata update statement is not allowed by the current database SQL dialect 1 [SQLState:42000, ISC error code:335544793]

**Comment by uslss** [comment]
probably, you could find more info here https://www.firebirdsql.org/pdfmanual/html/gfix-dialect.html

**Comment by WellingtonBS** [comment]
thank you very much, THE DB is in the correct dialect, I use with other tools, I believe it is some config of DBeaver in the format of connection dialect, has to change the format?
