### ISSUE TITLE
Extend 'Search in comments' functionality to other databases

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#13066]
Currently, we only support PostgreSQL, MySQL, Oracle, MSSQL, and Exasol.  

In this ticket, we are implementing this functionality for:
- [x] Cassandra

**Comment by flambchap** [comment]
Implemented for Cassandra.

**Comment by uslss** [comment]
Cassandra - verified

**Comment by flambchap** [comment]
We'll only do Cassandra in this ticket.
