### ISSUE TITLE
Metadata search doesn't work for procedures or functions in DB2

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13063]
#### System information: 
- DBeaver version 21.1.2

#### Connection specification:
- Database name and version DB2
- Driver name DB2 LUW

#### Describe the problem you're observing:
Metadata search doesn't find procedures and functions.

#### Steps to reproduce, if exist:
1. Open Metadata Search and try to find an existing function.

**Expected:** Object is found
**Actual:** Nothing is found

![MxfCyuhUTj](https://user-images.githubusercontent.com/82543000/124131652-af83f400-da88-11eb-9206-8129db467a17.gif)

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
