### ISSUE TITLE
Auto-complete appears after a table alias

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13073]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.2

#### Steps to reproduce, if exist:
Write in SQL Editor `select * from table_name tn`|--press ctrl+space after table alias

**Expected**: no proposals
**Actual result**: the table name appears in the auto-complete list.
![dbeaver_mRU2TEBBGw](https://user-images.githubusercontent.com/51405061/124242671-ab59e400-db25-11eb-9b43-d9390b01fa77.png)

**Comment by LonwoLonwo** [comment]
Fixed

**Comment by DariaMarkaryan** [comment]
Verified
