### ISSUE TITLE
Open in foreground from command line

### ISSUE THREAD

**Issue by ilmagowalter** [dbeaver/dbeaver#13075]
#### System information: 
- Windows 10
- DBeaver Standalone - 21.1.1.202106210824

#### Describe the problem you're observing:
When open dbeaver connection from command line and i have dbeaver already opened, the software do not go in the foreground automatically

**Comment by Matvey16** [comment]
Can you please provide steps to reproduce this issue. It is very unclear what exactly are you doing and in what order in this case.

**Comment by ilmagowalter** [comment]
steps:

1) open dbeaver
2) minimize dbeaver window
3) open cmd prompt
4) run "C:\Program Files\dbeaver\dbeaver.exe" -nl it -con "name=TEST|openConsole=true"

the issue is that the dbeaver windows remains minimized

maybe is possible create a parameter to choose to maximize the window or not

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
Using this argument on Linux when DBeaver is maximized leads to it getting minimized
