### ISSUE TITLE
Auto-complete replaces asteriks

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13071]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.2 EA 
#### Steps to reproduce, if exist:
Write in SQL Editor `select *|`--press ctrl+space

**Expected**: `from` is suggested after asteriks
**Actual result**: `from` replaces asteriks

https://user-images.githubusercontent.com/51405061/124241925-e3145c00-db24-11eb-82bb-8a1dfaac5156.mp4

**Comment by Matvey16** [comment]
Verified
