### ISSUE TITLE
command-line -con name do not work when exist two connection with same name but different folder

### ISSUE THREAD

**Issue by ilmagowalter** [dbeaver/dbeaver#13074]
#### System information: 
- Windows 10
- DBeaver Standalone - 21.1.1.202106210824

#### Describe the problem you're observing:
command-line -con name do not work when exist two connection with same name but different folder
Example
if i have in navigator 3 connections
FOLDER1\PROD
FOLDER2\PROD
FOLDER3\PROD

i use this command
"C:\Program Files\dbeaver\dbeaver.exe" -con "name=PROD|openConsole=true" the system open one of connection

i tried 
"C:\Program Files\dbeaver\dbeaver.exe" -con "name=PROD|openConsole=true|folder=FOLDER1" but, like i read in wiki folder parameter is useful only during creation

is possibile add a parameter where specifiy the connection folder or reuse folder parameter ?

**Comment by uslss** [comment]
You could use connection ID instead.
It could be found in connection properties (Main Menu: Window - Show View - Other - Properties)
![image](https://user-images.githubusercontent.com/31996417/124888103-77c40180-dfde-11eb-8628-960893202046.png)

**Comment by ilmagowalter** [comment]
> You could use connection ID instead.
> It could be found in connection properties (Main Menu: Window - Show View - Other - Properties)
> ![image](https://user-images.githubusercontent.com/31996417/124888103-77c40180-dfde-11eb-8628-960893202046.png)

Thank you... this work!

example:

"C:\Program Files\dbeaver\dbeaver.exe" -nl it -con "id=oracle_thin-178639d9c76-a87d30287a0a007|openConsole=true"
