### ISSUE TITLE
Grouping panel drag-n-drop breaks after adding columns starting from the first continuously

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13072]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 21.1.2

#### Describe the problem you're observing:
If you drag columns to grouping panel continuously (e.g first then second then third etc) after clearing the panel you won't be able to add them to grouping panel again until you add the column that was not added previously. 

#### Steps to reproduce, if exist:
1. Add a few of the columns at the beginning of the table (or even only the first) into grouping panel continuously starting from the first.
2. Clear it.
3. Try to add any of those columns again.

**Expected:** Column is added
**Actual:** Nothing happens

![Xoa5SwSpn1](https://user-images.githubusercontent.com/82543000/124241710-ac3e4600-db24-11eb-869d-01bf632f0f1f.gif)

**Comment by DariaMarkaryan** [comment]
no longer reproduced
