### ISSUE TITLE
Advanced paste escape for NULL values

### ISSUE THREAD

**Issue by radek-vytiska** [dbeaver/dbeaver#13076]
**Is your feature request related to a problem? Please describe.**
We are often using Excel to prepare data and after that we use advanced paste to transfer them into DBeaver. We are using this method on testing env. where its fast and siple this way. But there is ne huge problem with this workflow, when we paste empty cells randomly spread in the data sheet and we want these to be NULL valuse. I didnt find any escape symbol to make DBeaver recognise these cells as NULLS. I have described this problem in the discussion here as well: https://github.com/dbeaver/dbeaver/discussions/11427

**Describe the solution you'd like**
It would be a great help, if there would be any possibility to escape advance pasted data from Excel with NULL values (instead of empty strings).

**Describe alternatives you've considered**
It could be part of the settings, it could be special value or basicaly any way to make Excel data include NULL values that can be correctly pasted into DBeaver.

**Additional context**
Just the link to original topic: https://github.com/dbeaver/dbeaver/discussions/11427

Thank you

**Comment by Matvey16** [comment]
We need to add a configuration options for advanced paste feature

**Comment by ShadelessFox** [comment]
Now you can configure how nulls should be proceeded:

![image](https://user-images.githubusercontent.com/35821147/132125945-806df482-7286-441f-a8a3-b9ab075d53a2.png)

**Comment by uslss** [comment]
verified
