### ISSUE TITLE
Wrong DDL for creating a table with unique key via UI

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13080]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.1.2 EA

#### Connection specification:
- Database name and version Greenplum 

#### Steps to reproduce, if exist:
Create a new table with a unique key via UI and save it

**Expected**: the table is created
**Actual result**: the table cannot be created because of incompatible DDL. An error appears: `UNIQUE and DISTRIBUTED RANDOMLY are incompatible`

Generated DDL:
```
CREATE TABLE public.test_unique (
	id int NULL,
	uk varchar NULL,
	CONSTRAINT test_unique_un UNIQUE (uk)
)
DISTRIBUTED RANDOMLY;
```
Distributed randomly clause doesn't allow to create the unique key

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by uslss** [comment]
verified
