### ISSUE TITLE
Regression: can't edit bits anymore

### ISSUE THREAD

**Issue by ggregoire** [dbeaver/dbeaver#13087]
#### System information: 
- Operating system (distribution) and version: macOS mojave
- DBeaver version: Version 21.1.1.202106210813

#### Connection specification:
- Database name and version: postgresql

#### Describe the problem you're observing:

Can't edit bits anymore. I've been doing it for years on this table so it's probably a regression.

<img width="221" alt="Screen Shot 2021-07-02 at 12 15 02 PM" src="https://user-images.githubusercontent.com/591804/124310804-58d2f480-db32-11eb-84b3-77a070be0dca.png">

When editing (inline or opening the edit modal), it displays the wrong value and I can't add more than one 0 or 1:

<img width="211" alt="Screen Shot 2021-07-02 at 12 15 12 PM" src="https://user-images.githubusercontent.com/591804/124310898-7c963a80-db32-11eb-9d09-121035d7abb5.png">

DDL:

```sql
CREATE TABLE public.foo (
	id serial PRIMARY KEY,
	verb bit(5)
);
```

It works when doing it with a query:

```sql
UPDATE public.foo
SET verb = '10000'
WHERE id = 657;
```

**Comment by uslss** [comment]
verified
