### ISSUE TITLE
Allow changing prefix for client commands

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#13083]
Currently, the default prefix for such commands is `@` and you can't change it. It would be nice to have, since some databases have designated syntax for other things with heavy usage of `@` as a prefix (e.g. local variables in SQL Server)

https://github.com/dbeaver/dbeaver/wiki/Client-Side-Scripting

**Comment by ShadelessFox** [comment]
Implemented:

![pJ5VpC1wss](https://user-images.githubusercontent.com/35821147/124293332-37d4c880-db5f-11eb-8326-ac5e9d035f97.png)

**Comment by uslss** [comment]
verified
