### ISSUE TITLE
SELECT statement still increasing modifying statement count and starting an unneeded transaction

### ISSUE THREAD

**Issue by nbros** [dbeaver/dbeaver#13088]
Hello,

I only executed the same SELECT 3 times after connecting to my database and I see "3 modifying statements".

![image](https://user-images.githubusercontent.com/141089/124346913-cc800a80-dbe1-11eb-9de7-cd8ca313e2e9.png)

#### System information: 
- Operating system : Windows 10
- DBeaver version : 21.1.1.202106210824
- Additional extensions : none

#### Connection specification:
- Database name and version : DB2 v11.5
- Driver name : DBeaver DB2 Support
- Do you use tunnels or proxies (SSH, SOCKS, etc)? yes, but not to this database

[error.log](https://github.com/dbeaver/dbeaver/files/6758028/error.log)

**Comment by nbros** [comment]
![image](https://user-images.githubusercontent.com/141089/124347134-3e0c8880-dbe3-11eb-9bc4-53ecf6a1321a.png)

**Comment by flambchap** [comment]
Duplicates https://github.com/dbeaver/dbeaver/issues/11841. Thank you for the report, anyway.
