### ISSUE TITLE
Create column button is absent in some cases for SQLite 

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13095]
#### System information: 
- DBeaver version 21.1.2

#### Connection specification:
- Database name and version SQLite

#### Describe the problem you're observing:
Create a column button is hidden in some places, when it should not be.

![dbeaver_jFMJ8YXcXA](https://user-images.githubusercontent.com/82543000/124431216-c5d7cb80-dd78-11eb-933d-94f2219f2acf.png)
![TgKTlWhiEj](https://user-images.githubusercontent.com/82543000/124431410-fcade180-dd78-11eb-9dba-a0d9828f1262.gif)

**Comment by LonwoLonwo** [comment]
Fixed. Also, the connection filter changed.
Pictures are here https://github.com/dbeaver/dbeaver/pull/13590

**Comment by Matvey16** [comment]
Verified
