### ISSUE TITLE
Eclipse Plug-in table data tab UI display is not organized

### ISSUE THREAD

**Issue by lyh061619** [dbeaver/dbeaver#13090]
System information:

    Operating system (distribution) and version Win10
    DBeaver version 21.1.2
    4K screen 3840 x 2160
Steps to reproduce, if exist:

Eclipse Plug-in table data tab UI display is not organized

Expected: Adjust to end display
![图片](https://user-images.githubusercontent.com/15118571/124406582-565fdd00-dd74-11eb-9457-a541cd339ceb.png)

**Comment by Matvey16** [comment]
Can't reproduce on FullHD display with any resolution setting.

**Comment by Matvey16** [comment]
@lyh061619 I see that the font in those broken fields appear to be unusually bold. Did you change any font settings? Also please can you verify the zoom options in your display settings?

**Comment by uslss** [comment]
there is no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
