### ISSUE TITLE
Ctrl+h search result only show name column,

### ISSUE THREAD

**Issue by doitsexy** [dbeaver/dbeaver#13093]
#### System information: 
- Operating system (distribution) and version: windows 10
- DBeaver version 21.1.1 community
- Additional extensions

#### Connection specification:
- Database name and version:  oracle11
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
when search (Ctrl+H) , the result only shows the name column, other columns do not show . I must customize to add a column then all columns will show. But next time ,it resets again.

**Comment by uslss** [comment]
@doitsexy Could you provide a video of the issue?

**Comment by uslss** [comment]
there is no update on issue for a long time.
If it is still actual - feel free to reopen it with additional info that will help to reproduce an issue.
