### ISSUE TITLE
Firebird: columns metadata editor

### ISSUE THREAD

**Issue by danieleteti** [dbeaver/dbeaver#131]
The "Modify Column" form is read only and is not possibile to change the column metadata. This is the only big thing that block me to switch to dbeaver for my databases management.

**Comment by serge-rider** [comment]
For now DBeaver supports metadata edit only for MySQL and Oracle. PostgreSQL support planned in 3.6.
What database do you mean here?

**Comment by danieleteti** [comment]
FirebirdSQL

**Comment by redbaty** [comment]
Up 👍

**Comment by ronaldosjr** [comment]
Up

**Comment by iambudi** [comment]
Renaming/Changing column and Type are basic features in any Database GUI Tool.
Up for Firebird 😀.

**Comment by serge-rider** [comment]
Now FB extensions can:
- Rename table column
- Change table column data type
- Change table column default value
- Change table column comment
- Change table column position

I think this is pretty much everything this ticket was about.
Yahoo, it took less than 3 years :)

**Comment by iambudi** [comment]
Hi @serge-rider thanks for pointing that. Both works good now. Regarding UI, yes agree it should be improved. For reodering column, using drag and drop should be nice since dragging is already there but disabled.

Any reason the column is not editable in property tab (double click column name)?

**Comment by iambudi** [comment]
On dbeaver 6, Change table column position seems missing. 
![image](https://user-images.githubusercontent.com/31809529/57512585-3d934280-7336-11e9-86da-2c9baee0150f.png)

**Comment by iambudi** [comment]
Table can not also be renamed. The textbox is readonly. 
![image](https://user-images.githubusercontent.com/31809529/57512811-ee014680-7336-11e9-84e9-8cf82cfa992d.png)
