### ISSUE TITLE
Incorrect syntax when Generate SQL > Insert/Update is used for composite type columns

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13102]
#### System information: 
- DBeaver version 21.1.2

#### Connection specification:
- Database name and version Yugabyte SQL, PostgreSQL

#### Describe the problem you're observing:
1. When generating SQL Insert/Update statement for table with composite type, wrong type of brackets is generated.
2. Also value from `text` type sub column is not quoted.

#### Steps to reproduce, if exist:
1. Create a table with composite type column
2. Generate SQL Insert statement
3. Try to execute in SQL Editor

**Expected:** Query is executed
**Actual:** Error because `[ ]` should be replaced with `( )` and String is not quoted.

![NeW1TOSWqS](https://user-images.githubusercontent.com/82543000/124481793-5a5e2000-ddb1-11eb-9148-b3d9fd176b6e.gif)

**Comment by Matvey16** [comment]
The same error in syntax when exporting composite columns as SQL script

**Comment by LonwoLonwo** [comment]
Closed as duplicate https://github.com/dbeaver/dbeaver/issues/14314
