### ISSUE TITLE
auto completion for with clause (CTE) with alias

### ISSUE THREAD

**Issue by gthbusr0** [dbeaver/dbeaver#13108]
System information:
Operating system (distribution) and version: windows 10 enterprise 10.0.18363
DBeaver version: DBeaver 21.1.1
Additional extensions: NONE
Connection specification:
Database name and version : oracle 11gr2
Driver name : default oracle driver bundled with s/w
Do you use tunnels or proxies (SSH, SOCKS, etc)? : no tunnels/proxies

#### Describe the problem you're observing:
Hello again SMEs, auto completion for with clause (Common Table Expressions) with alias isn't currently available i.e. <cte_alias>.<ctl+space> doesn't show any proposals.

P.S. Coming from SQL Developer to DBeaver for performance reasons and such features already available in SQL Developer will further boost the productivity. Really like the performance for the tasks I perform so far, happy convert/camper.

#### Steps to reproduce, if exist:
spawn a new session, write a CTE (with possible col aliases within this CTE) , in a subsequent select SQL alias this cte as cte_alias try to select column / join this CTE with another table via cte_alias.<ctl+space> & "no proposals' pops up instead of columns within the CTE.

**Comment by Matvey16** [comment]
@iDeepMind Thank you for the report

**Comment by E1izabeth** [comment]
Let's keep one issue for this #8949
