### ISSUE TITLE
Extract SQL from source code - OS inconsistency

### ISSUE THREAD

**Issue by alesc2000** [dbeaver/dbeaver#13116]
#### System information: 
- Operating system (distribution) and version Linux Mint vs. Windows 10
- DBeaver version 21.1.2
- Additional extensions Office extention

#### Connection specification:
- Database name and version - PG 12
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When pasting SQL from source code, it behaves different in Windows vs. Linux environment.

#### Steps to reproduce, if exist:
Source code to paste:
        "SELECT * \n" + 
        "FROM table t \n" + 
        "ORDER BY id DESC \n"

Under Windows it inserts two newline characters, resulting an empty line between each sql line. My guess is that it replaces both new lines and "\n" characters found in string. Under Linux it works fine. I attached images.
![image](https://user-images.githubusercontent.com/19900533/124570961-05251b80-de50-11eb-9af0-45461e4ab13a.png)
![image](https://user-images.githubusercontent.com/19900533/124570985-0bb39300-de50-11eb-96ac-ecc1cf4d1ab3.png)

Thanks

**Comment by Matvey16** [comment]
@alesc2000  Thank you for the report, we will fix it.

**Comment by alesc2000** [comment]
Hi, I found a workaround. There is a setting in General / Workspace: "New text file line delimiter" which can be set to Unix for Win environment. A general fix for removing multiple empty lines when pasting from source code would be great though.
Thanks.

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
