### ISSUE TITLE
Switch Input Language in sql script program not response

### ISSUE THREAD

**Issue by jerateep** [dbeaver/dbeaver#13113]
I use DBeaver 21.1.2 (Last version) found issue
use ~ switch language Thai to English in sql script program not response  (windows 10)
Now I downgrade use Version 21.0.1.202103211229 it works normally.

**Comment by uslss** [comment]
@jerateep 
unfortunately, cannot reproduce an issue. could you provide a video of it? Did you switch language using shortcut?

**Comment by uslss** [comment]
there is no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
