### ISSUE TITLE
[ERD] Highlight selected FK and referenced tables with distinctive color on FK selection

### ISSUE THREAD

**Issue by poltpolt** [dbeaver/dbeaver#13118]
For the diagram to be more useful please add color marking for the highlighted foreign key
This way all connecting lines and all instances of the same key would be highlighted/(marked with color) and it would be  visible on the diagram.

**Comment by Matvey16** [comment]
@polus Thanks for the suggestion, it seems interesting and useful, but can you please add more detail for how you see it? What should be highlighted (columns or connections) and when (clicking on connections or always etc.)

**Comment by poltpolt** [comment]
As soon as you click on a foreign key
all tables that refer to this key

all lines linking those tables (connections)

should be highlighted with some distinctive color.

In a perfect world : also a button to hide all other (the ones are not using this key) connections/tables
