### ISSUE TITLE
mysqldump doesnt work for snap installation

### ISSUE THREAD

**Issue by luboA** [dbeaver/dbeaver#13114]
I have snap version of DBeaver 21.1.1 and when I want to create dump from mariaDB (local or remote) I get a error:

Utility 'mysqldump' not found in client home '/usr' (/usr)

I have also problem with installation on ubuntu through discover. You should to improve installation documenation for non skilled users or just update normal ubuntu repository (there is still version 7.x.x). I was able to install new version only through dpkg -i xxx.deb command after manual download version from your web.

After installation from deb package I can create dump without problems.

**Comment by luanmateuz** [comment]
I guess DBeaver has this bug in snap version. Change to .deb version that will work. To find the driver run in the terminal

```bash
which 'database'
```

This worked for me, good luck!

**Comment by rickdevops** [comment]
same bug around 1 year now

**Comment by uslss** [comment]
closed as a duplicate of #10845

**Comment by rustyx** [comment]
Why is a `snap` bug closed as a dupe of a `flatpak` bug? It's not the same thing and the resolution can be different. The comments with workarounds in the dupe are all specific to Flatpak.
