### ISSUE TITLE
I hope to integrate our own database into dbeaver. What should I pay attention to

### ISSUE THREAD

**Issue by LuckyPickleZZ** [dbeaver/dbeaver#13115]
Hello author, now we hope to integrate into dbeaver like mysql, Clickhouse and other databases. What I need to pay attention to, such as coding style, etc. At present, I am developing the source code, but the development progress is slow, I hope to get some guidance.
And will you accept my pull request?
This is our official website link: https://www.oceanbase.com

**Comment by Matvey16** [comment]
@LuckyPickleZZ Hello. Don't be afraid of pull request. You can read advices for development in our wiki. Also to get some ideas you can review code in files for other databases e.g. `org.jkiss.dbeaver.ext.test` or `org.jkiss.dbeaver.ext.clickhouse`

**Comment by LuckyPickleZZ** [comment]
@Matvey16 I'm very appreciate for your reply. Next week I'm going to launch a discussion and upload our plan document.
