### ISSUE TITLE
r-click results grid->filter ->customize filters--ability to select multiple columns at once to move up/down instead of selecting one-by-one & clicking move-up/-down

### ISSUE THREAD

**Issue by gthbusr0** [dbeaver/dbeaver#13112]
**Is your feature request related to a problem? Please describe.**
it's time consuming to move columns one-by-one clicking move-up multiple times once for each col we'd like to move up to show these cols first in the results grid
**Describe the solution you'd like**
it saves time to enable multiple column selection to move fields up in the results grid ..shift-select-all-cols we'd like to move & just click move-up/move-down once
**Describe alternatives you've considered**
selecting in SQL is considered but for tables with 100s of cols it's timeconsuming
**Additional context**

**Comment by Matvey16** [comment]
@iDeepMind  Thank for the suggestion, we will implement it.

**Comment by Matvey16** [comment]
Verified
