### ISSUE TITLE
Execute in SQL*Plus fails

### ISSUE THREAD

**Issue by merlyn383** [dbeaver/dbeaver#13125]
#### System information: 
- Operating system (distribution) and version macOS 10.15.7
- DBeaver version DBeaver EE  21.1.0.202106090921
- Additional extensions

#### Connection specification:
- Database name and version Oracle Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
- Driver name Oracle JDBC driver 12.2.0.1.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
When attempting to execute a script file via Tools -> Execute in SQL*Plus the execution fails because the host is null. Connection is defined in TNS file stored locally. I can successfully execute the script if I do it entirely locally in Terminal (manually run the command: sqlplus [username]/[password]@advdev @sqlfile.sql)

#### Steps to reproduce, if exist:
- Right click on connection -> Tools -> Execute in SQL*Plus
- Choose sql file
- Hit Start

#### Include any warning/errors/backtraces from the logs

Entry from Error Log:
eclipse.buildId=unknown
java.version=11.0.11
java.vendor=AdoptOpenJDK
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/merlyn383/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/merlyn383/.eclipse_keyring

This is a continuation of log file /Users/merlyn383/Library/DBeaverData/workspace6/.metadata/.bak_0.log
Created Time: 2021-07-06 10:19:35.100

org.jkiss.dbeaver.model
Error
Tue Jul 06 15:36:42 EDT 2021
Process failed (exit code = 1). See error log.

java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:214)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:194)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:254)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:60)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

Error from Task window:
/Users/merlyn383/Documents/instantclient_19_8/sqlplus [username redacted]/[password redacted]@null
Task 'Oracle SQL*Plus script' started at Tue Jul 06 15:36:42 EDT 2021

SQL*Plus: Release 19.0.0.0.0 - Production on Tue Jul 6 15:36:42 2021

Version 19.8.0.0.0

Copyright (c) 1982, 2020, Oracle.  All rights reserved.

ERROR:

ORA-12154: TNS:could not resolve the connect identifier specified

Enter user-name: SP2-0306: Invalid option.

**Comment by Matvey16** [comment]
This bug is in the process of fixing right now.
https://github.com/dbeaver/dbeaver/pull/12854

**Comment by uslss** [comment]
@merlyn383 could you check if issue is fixed in [EA version](https://dbeaver.io/files/ea/)?

**Comment by merlyn383** [comment]
Current EA version (2021-07-06 09:56:28) for macOS fails to open. OS claims it is damaged.

**Comment by Matvey16** [comment]
@merlyn383 You can try now, the latest version has been rebuilt

**Comment by merlyn383** [comment]
Confirmed working in EA version!

(Side note in case anyone trying to run the EA version finds this thread: trying to just run the EA version normally fails in macOS. You need to disable GateKeeper for the downloaded app: 
`xattr -dr com.apple.quarantine ~/Downloads/DBeaver.app` (Replace path with your own if needed, but odds are it's just sitting in your Downloads folder.)
