### ISSUE TITLE
change default connection name to hostname

### ISSUE THREAD

**Issue by cloud-66** [dbeaver/dbeaver#13127]
When we create a new connection to the database server, the default connection name is database name
So, let's say in Oracle it is like SID it doesn't mean anything, doesn't do understanding on which server i connect. Or in postgresql i usually connect to postgres database.
Having many database server i connect on each server once, then I choose a specific database from top menu
**Describe the solution you'd like**
it would be more convenient to set default connection name to hostname of database server

**Comment by Matvey16** [comment]
@cloud-66 Thank you for the suggestion, we will look if it can be implemented in future updates. For now you can enable showing of host name in the connection's context menu.

![dbeaver_o8PXKNnhNr](https://user-images.githubusercontent.com/82543000/125737604-71ab8309-284b-4121-81fa-8ee9ea1b3d0a.png)

**Comment by Destrolaric** [comment]
![image](https://user-images.githubusercontent.com/20579256/171193577-04815411-e5ba-464e-a69c-c5ad80d5d47a.png)
