### ISSUE TITLE
calculate total row count 

### ISSUE THREAD

**Issue by ComputingFroggy** [dbeaver/dbeaver#13123]
#### System information: 
- Windows 10
- DBeaver version : 21.1.2
- Additional extensions : none

#### Connection specification:
- MySQL 5.5.40
- JDBC
- no proxies

#### Describe the problem you're observing:
When clicking on the double green arrow ("calculate total row count ") nothing happens. We don't get the total row count.
This used to work in older versions.
In the previous version, the button click generated a SQL error. So I've juste upgraded. Now, no error messages but no row count either !

#### Steps to reproduce, if exist:
Click on the button.

**Comment by uslss** [comment]
@ComputingFroggy is there something in the [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by ComputingFroggy** [comment]
some requests (that runs OK) generates an error ... others not.

**Comment by uslss** [comment]
could you tell what request fails? Error logs also will be helpful
it is needed for us to reproduce the issue to fix it.
thanks in advance

**Comment by ComputingFroggy** [comment]
I will try and get a request that fails ... that you can reproduce (I can not send you my tables ;-) ! )

**Comment by uslss** [comment]
still cannot reproduce an issue.
If it is still actual, feel free to reopen it with additional info that could help to reproduce an issue
