### ISSUE TITLE
After upgrade to 21.1.2.202107041908 the dash icon disappears and it's nowhere to be found except directly calling dbeaver-ce from the cli

### ISSUE THREAD

**Issue by petr-hybler** [dbeaver/dbeaver#13138]
#### System information: 
- Ubuntu 20.04.2 LTS 64-bit, GNOME 3.36.8
- 21.1.2.202107041908
- no extensions

#### Connection specification:
- there is no problem with any DB connection

#### Describe the problem you're observing:
After an overnight update in snap tonight the icon in the dash disappeared and I can't seem to find it in the applications list neither. The only way I can run it is via cli calling "dbeaver-ce" but I cannot even pin it to the dash

#### Steps to reproduce, if exist:
every time I run the software ... 

#### Include any warning/errors/backtraces from the logs

I can see a few suspicious things in the stdout when running it via cli

`SWT SessionManagerDBus: Failed to RegisterClient: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.121" (uid=1000 pid=21015 comm="/snap/dbeaver-ce/136/share/dbeaver/jre/bin/java -X" label="snap.dbeaver-ce.dbeaver-ce (enforce)") interface="org.gnome.SessionManager" member="RegisterClient" error name="(unset)" requested_reply="0" destination=":1.23" (uid=1000 pid=1887 comm="/usr/libexec/gnome-session-binary --systemd-servic" label="unconfined")`

`(DBeaver:21015): Gtk-CRITICAL **: 06:27:27.431: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar`

there was nothing else in the logs (`/home/*****/snap/dbeaver-ce/136/.local/share/DBeaverData/workspace6/.metadata`)

**Comment by uslss** [comment]
thank you for the report

**Comment by riednyko** [comment]
Fixed. Try to update dbeaver-ce snap package.

**Comment by petr-hybler** [comment]
nice, it works great now again :) awesome support guys !!! thank you
