### ISSUE TITLE
Parser is slow when parsing H2 query

### ISSUE THREAD

**Issue by lukaseder** [dbeaver/dbeaver#13141]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows [Version 10.0.19042.1052]
- DBeaver version: Version 21.1.1.202106210824

#### Connection specification:
- Database name and version: H2 1.4.200
- Driver name: org.h2.Driver

#### Describe the problem you're observing:

The UI freezes for a short time when running a query.

#### Steps to reproduce, if exist:

Run this query:

```sql
select 
  cast((
    select coalesce(
      json_arrayagg(json_array("v0") order by "t"."v0"),
      json_array(null on null)
    )
    from (
      select 2 "v0"
      union
      select 4 "ID"
    ) "t"
  ) as text);
```

A profiling session shows that a lot of time is spent in DBeaver's parser:

![image](https://user-images.githubusercontent.com/734593/124885423-8822af00-dfd3-11eb-9136-a0c65ce6f16e.png)

There's a single hotspot:

![image](https://user-images.githubusercontent.com/734593/124885521-a4265080-dfd3-11eb-8aef-d9794e1c63ef.png)

Here's a [VisualVM](https://visualvm.github.io/) snapshot with more details:

[snapshot-1625731372916.zip](https://github.com/dbeaver/dbeaver/files/6782753/snapshot-1625731372916.zip)

**Comment by lukaseder** [comment]
The problem doesn't appear if I remove the `COALESCE()` expression:

```sql
select 
  cast((
    select 
      json_arrayagg(json_array("v0") order by "t"."v0")
    from (
      select 2 "v0"
      union
      select 4 "ID"
    ) "t"
  ) as text);
```

**Comment by flambchap** [comment]
Hi Lukas. This looks like a performance issue in the @JSQLParser library. I'll create a ticket on their issue tracker. Thanks for the report.

**Comment by manticore-projects** [comment]
Hi Lukas and DBeaver Team.

The problem is not about the `Coalesce`, but about the Aggregate Function Parameters `json_array("v0") order by "t"."v0"`.
It triggers a deep nested Lookahead in the generated parser, which amplifies itself.

I will take your example and try to find a way to limit the Lookahead.

Cheers

**Comment by manticore-projects** [comment]
Apologies for asking: How slow is *too slow*?
I have tested Lukas' particular query and it gets parsed and de-parsed within 0.14 seconds (using the latest JSQLParser 4.2-Snapshot):

![image](https://user-images.githubusercontent.com/18080123/125009709-47886b80-e08f-11eb-9fde-06ae396bc7a8.png)

**Comment by manticore-projects** [comment]
The problem is the `null on null` which is simply not support by JSQLParser. Right now JSQLParser supports only a limited set of Aggregate Functions with focus on Oracle. I actually opened issue [1183 Parser fails on H2 Ordered Aggregate Functions](https://github.com/JSQLParser/JSqlParser/issues/1183) in April.

Without this unsupported clause, the query parses just fine:
![image](https://user-images.githubusercontent.com/18080123/125011398-9388df80-e092-11eb-8bcc-fe930129e28e.png)


With the unsupported clause, the query will throw a parser error -- but only after 5 seconds:
![image](https://user-images.githubusercontent.com/18080123/125011510-ccc14f80-e092-11eb-9976-216156392679.png)

**Comment by manticore-projects** [comment]
Suggested To-Do's:

1) JSQLParser team will look into better support of H2 ORDERED AGGREGATES
2) DBeaver team: maybe wrap your calls to JSQLParser into a separate thread, monitored by a timer task which will stop the thread after an acceptable timeout (e. g. 2 seconds). I have done a similar thing with JSQLFormatter.

**Comment by lukaseder** [comment]
> Right now JSQLParser supports only a limited set of Aggregate Functions with focus on Oracle

This is standard SQL syntax, also implemented by Oracle, of course, there are always subtle differences...

In a deleted (edited?) comment, you asked how slow it is for me. The profiling session measured 3 executions. One execution takes about 4 seconds on my machine.

**Comment by manticore-projects** [comment]
> > Right now JSQLParser supports only a limited set of Aggregate Functions with focus on Oracle
> 
> This is standard SQL syntax, also implemented by Oracle, of course, there are always subtle differences...

Seems to be supported by Oracle since 12 (my mind is still stuck with Oracle 11).
Although the main issue is: not supported in JSQLParser yet, but I will implement it for you.

> 
> In a deleted (edited?) comment, you asked how slow it is for me. The profiling session measured 3 executions. One execution takes about 4 seconds on my machine.

Apologies for that, I was confused between the 2 reported issues and the 4 provided queries.
Since then the issue is clear: `null on null` is not supported and leads the parser onto a wrong trail, which takes very long (5 seconds) to fail.

**Comment by lukaseder** [comment]
For the record, the motivation for using this particular syntax is:

1. It works
2. The much preferrable alternative doesn't work: https://github.com/h2database/h2database/issues/2496

**Comment by manticore-projects** [comment]
No worries, am almost done. Will send you a version for testing tomorrow.

**Comment by manticore-projects** [comment]
@lukaseder Please checkout the [Unit Tests](https://github.com/JSQLParser/JSqlParser/pull/1263/files#diff-995aab0104f5544409a817da445a9e75296924cbd9e124fae4c6d61d7af20da1) and let me know if anything was missing.

I do not use such syntax myself and have no practical experience with these functions.

**Comment by manticore-projects** [comment]
@lukaseder Sorry, more questions:
```sql
select json_array();
select json_array(null on null); 
```
would both result in an empty array `[]`

But
```sql
select json_array(null null on null);
```
would result in an array `[null]`

Does that match your expectation? If so, why 
```sql
select coalesce(
      json_arrayagg(json_array("v0") order by "t"."v0"),
      json_array(null on null)
    )
```

**Comment by lukaseder** [comment]
> would both result in an empty array `[]`

Yes, but `json_array()` does not yet work in 1.4.200 because of https://github.com/h2database/h2database/issues/2496. The issue has been fixed, but the fix has not yet been released.

`json_array(null)` would also produce an empty array, because `absent on null` is implied, and so would `json_array(null absent on null)`

> Does that match your expectation? If so, why

I'm not sure what the question is, here...

**Comment by manticore-projects** [comment]
Thank you for the explanation, I did not comprehend that you were bound to H2-1.4.200 which did not support `json_array()` without an argument yet. I think I got it now and the PR supports all these use cases.

**Comment by lukaseder** [comment]
Another case of slow SQL parsing is when running this query in Db2:

```sql
select (
  select coalesce(
    cast(('[' || listagg(
      json_object(key 'v0' value "v0"),
      ','
    ) || ']') as varchar(32672)),
    json_array()
  )
  from (
    select cast(null as timestamp) "v0"
    from SYSIBM.DUAL
    union all
    select timestamp '2000-03-15 10:15:00.0' "a"
    from SYSIBM.DUAL
  ) "t"
)
from SYSIBM.DUAL
```

**Comment by manticore-projects** [comment]
Hi Lukas,

it is literally the same case. The syntax of JSON_OBJECT and JSON_ARRAY lead JSQLParser on a wrong trail.
The provided PR fixes these issues.

**Comment by lukaseder** [comment]
Good to know it's the same case, thanks!

**Comment by manticore-projects** [comment]
Anything "new SQL stuff" which contains named parameters like `NULL`, `ON` or other keywords can easily create trouble for the parser. For example: `NULL` is usually a value expression, but for `JSON_ARRAY` it suddenly became something completely different.

Which means, we need to teach JSQLParser to check first if the `NULL` is suddenly part of the `JSON_ARRAY` function before we can accept it as value expression.

(Irrelevant side note: There is a reason why I complained about syntax like `JSON_ARRAY(NULL, NULL NULL ON NULL)` -- from a parser point of view this is insane.)

**Comment by manticore-projects** [comment]
Your test-case can be reduced to
```java
TestUtils.assertExpressionCanBeParsedAndDeparsed("listagg( json_object(key 'v0' value \"v0\"), ',' )", true);
```
and of course it fails to parse (just to show me), but at least with the PR it fails promptly and without the delay.

I will need to check the Syntax for `LISTAGG` and add the necessary H2 support. Please bear with me.

**Comment by lukaseder** [comment]
> but at least with the PR it fails promptly and without the delay.

As a user of the *editor* (not the parser), that's the good news here :)

**Comment by manticore-projects** [comment]
Ok, fixed it, your test case parses correctly now and fast.
Maybe you would like to replace the DBeavers JSQLParser.jar with the attached one, it should improve the situation immediately (although it may eat all your cats).

[jsqlparser-4.2-SNAPSHOT.zip](https://github.com/dbeaver/dbeaver/files/6809499/jsqlparser-4.2-SNAPSHOT.zip)

**Comment by manticore-projects** [comment]
And please keep your test cases coming, they are good because you are fluent with syntax I have never used before in practice.

**Comment by lukaseder** [comment]
> Maybe you would like to replace the DBeavers JSQLParser.jar with the attached one

I'll wait until Dbeaver releases an update, thanks.

> And please keep your test cases coming, they are good because you are fluent with syntax I have never used before in practice.

Well, I wrote a SQL parser too, you know ;-)

**Comment by serge-rider** [comment]
We will upgrade JSQLPArser in the next version of DBeaver.

@manticore-projects @lukaseder thank you for the investigation 👍

**Comment by uslss** [comment]
verified
