### ISSUE TITLE
Restore Database

### ISSUE THREAD

**Issue by seelipraneeth** [dbeaver/dbeaver#13147]
I have taken Production (Postgres)backup using DBeaver Version 7.3.5.202102151746. and restore using my Local DBeaver (same version). after that im not able to save any data in any table.

**Comment by Matvey16** [comment]
Do you get any error when trying to save data? Please post error log to see what happens when you try to save data.

**Comment by uslss** [comment]
there is no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
