### ISSUE TITLE
Metadata Editor objects remain in English after switching language to Italian, French, Korean

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13146]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.1.2

#### Steps to reproduce, if exist:
Switch User interface on Italian, French or Korean

**Expected:** whole application is translated
**Actual result:** metadata editor objects remain in English
![Screenshot 2021-07-08 at 16 58 30](https://user-images.githubusercontent.com/51405061/124935002-ea98a100-e00d-11eb-9ea3-eb79ba84a301.png)

**Comment by flambchap** [comment]
Unfortunately, this is somewhat expected since we don't have translations for those objects into the aforementioned languages. There is nothing we can do at the moment. We'll fix that when we'll change our approach to localization.
