### ISSUE TITLE
Lock Manager table layout on Linux

### ISSUE THREAD

**Issue by alesc2000** [dbeaver/dbeaver#13142]
#### System information: 
- Operating system (distribution) and version Linux mint
- DBeaver version 21.1.2
- Additional extensions Office

#### Connection specification:
- Database name and version PG12
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
On Lock manager table, the rows height is expanded when the statements contain new line characters. This makes it hard to scroll the table and follow the PIDs. On Windows this doesn't happen, each row has the same height showing first line of text.

![image](https://user-images.githubusercontent.com/19900533/124895955-b0b3a480-dfe5-11eb-9dac-b55f7e463908.png)

**Comment by Matvey16** [comment]
@alesc2000 Thank you for the report

**Comment by flambchap** [comment]
The same problem can be observed in other places.  

Session manager:
![image](https://user-images.githubusercontent.com/26031301/132993128-3337c872-8007-478d-a73b-ee8876af1bc4.png)

Session details:
![image](https://user-images.githubusercontent.com/26031301/132993179-a908ac3f-43f2-4242-b9f0-59a638899838.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
