### ISSUE TITLE
Code folding!

### ISSUE THREAD

**Issue by YuriDude** [dbeaver/dbeaver#13149]
Can you please add "Code folding" functionality when DB stored procedures are viewed/created?
It seems have become a standard for any modern code editor ;-)

Version in-use: 21.1.0
Missing feature checked against: MS SQL , Oracle.

**Comment by flambchap** [comment]
Hi. Thank you for your idea. We are going to implement that in the scope of https://github.com/dbeaver/dbeaver/issues/13152.
