### ISSUE TITLE
Degree of Connectivity 

### ISSUE THREAD

**Issue by YuriDude** [dbeaver/dbeaver#13148]
Can you please add an option to "increase" degree of connectivity when ERD is generated for a table?
Currently I see only nearest "neighbors" are generated in ERD when a table is viewed (1st degree of relationship).
It would be very helpful to see tables that are further on the ERD graph (e.g 2nd degree, 3rd degree).
However, please leave default behavior as it is now, and have an option of extra connections only as needed.

**Comment by Matvey16** [comment]
@YuriDude Thank you for the suggestion

**Comment by uslss** [comment]
closed as a duplicate of #10282
