### ISSUE TITLE
Support for Snowflake PARSE_JSON() function

### ISSUE THREAD

**Issue by ddumas30** [dbeaver/dbeaver#13158]
The PARSE_JSON() function in Snowflake is a pretty basic requirement.  When I run code that uses it, dbeaver pops up a window to enter data.   When I choose to ignore, it does not return any data.  The regular snowflake (web ui tool) works fine with this.

Dave

**Comment by LonwoLonwo** [comment]
Hello @ddumas30 
Can you please write a query example with PARSE_JSON() function?

More information about function using will be very helpful also.

For me, it's working fine.

![2021-07-13 12_15_20-Window](https://user-images.githubusercontent.com/45152336/125426360-eef906ba-6669-4310-9dba-ba82f14e9995.png)

**Comment by ddumas30** [comment]
Here is an example>  JSON is the column name in this example.  It has a data type of variant, and contains valid json data.

Dave

SELECT DISTINCT
  --  JSON,
     PARSE_JSON(JSON[0]):data.AutoInterview.Dealership.Id::STRING DEALERSHIP_ID
  ,   PARSE_JSON(JSON[0]):data.AutoInterview.Dealership.Request.AutoInterviewRequestId::STRING AUTO_INTERVIEW_REQUEST_ID
  ,   PARSE_JSON(JSON[0]):data.AutoInterview.InterviewId::STRING AUTO_INTERVIEW_ID

**Comment by LonwoLonwo** [comment]
Please try to disable the setting "Enable SQL Parameters" in Preferences->Editors->SQL Editor->SQL Processing
to disable [parameter binding](https://github.com/dbeaver/dbeaver/wiki/SQL-Execution#dynamic-parameter-bindings)

**Comment by LonwoLonwo** [comment]
![2021-07-21 10_14_01-DBeaver Enterprise 21 1 3 - _none_ Script-29](https://user-images.githubusercontent.com/45152336/126447727-162c11e1-d231-47ae-926f-8298c935d897.png)

**Comment by ddumas30** [comment]
I do not see a “Preferences ” anywhere in the navigation.  I only see File=>Properties

There, that setting you suggest is grayed out.

Dave


***@***.***D77E07.BE8C1000]

**Comment by ddumas30** [comment]
I found out how to un-gray it out.  I will let you know…
Dave

**Comment by ddumas30** [comment]
That worked, and parse_json worked – thanks!
