### ISSUE TITLE
Choose SQL Script for ALL Datasources

### ISSUE THREAD

**Issue by xunxky** [dbeaver/dbeaver#13157]
#### **Is your feature request related to a problem? Please describe.**
I am quite frustrated when i want to open a script in one datasource and can't because it was "associated" with another datasource. 
This feature is highly unintuitive and it only poses a disadvantage to me. 

#### **Describe the solution you'd like**
However to NOT have to interfere too much with the inner workings of  DBeaver it would be great if something like  "Open SQL Script" or "Recent SQL script" (there is no difference i can see!)  could be added there. 
For example _"Open SQL Script (ALL)"_.
**Meaning**: it would **not pre-select** available scripts based on the datasource BUT **allways** show the _"Choose SQL Script"-Dialoge_ with all available scripts. 
It would be best if the **currently selected datasource** would be used/associated when opening the script no matter which datasource was associated with the script before.

#### **Describe alternatives you've considered**
I currently select the required SQL-Script from the project pane. 
However this renders the convenience given by the sql button and the "Choose SQL Script"-Dialoge void(which includes date and sorting options) 

#### **Additional context**
As this is a quite common sense feature which is not available yet, I am fairly certain that there is some individual who opposes this. It would be great if YOU could please give reasoning  or why you do not think that wouldn't be a good _additional_ feature. 
Thank You

PS: 
**Alternative solution**
one script could have more associations ... (ultimately that's a special case from the previously given ALL case)

**Comment by Matvey16** [comment]
@xunxky You suggest adding another button in this tab, correct? It will open a list of all saved scripts and ignore data source association?

![dbeaver_oLC7PzKSpy](https://user-images.githubusercontent.com/82543000/125739886-4f308133-a2a8-4cc5-9e20-7644fe62bf3e.png)

**Comment by xunxky** [comment]
> @xunxky You suggest adding another button in this tab, correct? It will open a list of all saved scripts and ignore data source association?
> 
> ![dbeaver_oLC7PzKSpy](https://user-images.githubusercontent.com/82543000/125739886-4f308133-a2a8-4cc5-9e20-7644fe62bf3e.png)

exactly!

PS: 
and as pointed out I am well aware that the data source resolution will be tricky because some people might expect that scripts will use the current data source while others might expect the data source associated with the script to be true.

**Comment by Matvey16** [comment]
@xunxky Why do you think that opening a script from Project explorer (where scripts can be saved without associated data source) is not enough?

**Comment by xunxky** [comment]
> @xunxky Why do you think that opening a script from Project explorer (where scripts can be saved without associated data source) is not enough?

@Matvey16 That is quite a loaded question, because  mysql cli is actually "enough", isn't it?  
But I can repeat my first reasoning. 

> I currently select the required SQL-Script from the project pane.
> However this renders the convenience given by the sql button and the "Choose SQL Script"-Dialoge void(**which includes date and sorting options**) 

My request simply takes note that the SQL button is probably intended for convenience reasons,
 and I explain that it is inconvenient for users with multiple data sources of the same layout. 
(having multiple data sources of the same layout is not unusual in my opinion)

However you are right it is not pressing enough for me to check the project out and implement it myself.

**Comment by Matvey16** [comment]
We have a very different understanding of this feature between our team. Can you please provide a simple and clear use case step by step, so we can be sure that we understood you correctly.

**Comment by xunxky** [comment]
it is **common practice to most companies** (that I know) to abide by the following process : 

1. in order to **properly separate all stages of development** each of them hold a **copy** (at least in structure) of the relevant **database(s)**. 
2. this means there are at least data-sources for the usual stages: **production, testing, development.** (and possibly more) 
3. when a particular **query** is required to be executed it is **executed in the development database first** and modified until all kinks are worked out (iterative upward through the stages development, testing, production).
4. this query can be tied to a somewhat recurring task or something else that makes reuse required. meaning the query is not only used once, but **saved and later executed again** (with slight modifications, abiding the process shown in 3. starting in the development phase)
5. when you replicate this with a set of query-files interrupting in different stages you will see that they **end up randomly tied to one of these data-sources** 
    - if not properly set back to the development datasource in the end << _humans!_   
    - even when properly set back the  issue for testing and development still remains 
    - please assume switching of task, closing of the application or even shutting down of the workstation between work

6. **this results** in the real world issue that **only a subset of files are shown in 'open sql script' dialog** based on the data source they were left of at 
     - e.g. to find out which of these many scripts was the most(second/third...) recent file independent of the data source is a quite a hassle
      - or to just open up the desired file through the dialog while still  having another data source selected

in this work mode the strong association between data sources becomes obstructive. 

what **I am calling for** is a weaker association to the datasource or for **simplicity sake a quick way of listing all the files association independent** (including the possibility to sort by recency)

PS:
please do not suggest renaming the files or any of such mitigative actions. 
please assume that this is what people are already doing to relive their "pain".  
this is **not a bug report but a feature request** to increase ease of use and **improve the product**

PPS: the **bold text is intended for ease of reading** and does not indicate a different emotional state (being dyslexic finding such things helpful)

**Comment by tati-kru** [comment]
Possible solution: add preference option which will disable scripts-to-datasource association.

**Comment by Matvey16** [comment]
Default setting for SQL button stopped working, now it will always open new script regardless of selected setting

![dbeaver_pvNq2zcRuI](https://user-images.githubusercontent.com/82543000/152165931-25009a73-c37e-4db1-9f45-9410ea14f4ab.png)

**Comment by Matvey16** [comment]
This is not a regression, confirmed in older version, but needs investigation to reliably reproduce

Verified

**Comment by Matvey16** [comment]
NPE is thrown if a script is located outside of the project and is connected to a data source

**Comment by Matvey16** [comment]
Verified
