### ISSUE TITLE
Check for update option is throwing as "Perhaps the network connection is down?" in DBeaver Community 21.0.2 & 21.1.2

### ISSUE THREAD

**Issue by Pranithaevana** [dbeaver/dbeaver#13150]
We are trying to deploy DBeaver Community 21.1,2  firm wide. I could see the attached error when i click on "Help" -> "check for updates"

error for DBeaver

It should ideally say that there are no updates when we click on check for updates as it displays for DBeaver 21.
DBeaver previous verion
Attaching the screenshots of all the 3 versions 
![Dbeaver 21 1 2](https://user-images.githubusercontent.com/82090197/124973150-d1f9ac80-e048-11eb-9e86-12a01f70660d.JPG)
![DBeaver 21 (previous verion)](https://user-images.githubusercontent.com/82090197/124973157-d32ad980-e048-11eb-9713-2df46f8a8a35.JPG)
![error for DBeaver 21 0 1](https://user-images.githubusercontent.com/82090197/124973159-d32ad980-e048-11eb-91e4-3fa179e4acf6.JPG)

Could you please check and suggest us.

**Comment by Matvey16** [comment]
@Pranithaevana Hello. Can you specify some details about your network? Particularly if you use proxy.

**Comment by Pranithaevana** [comment]
Thanks for responding.

We will check on the below and let you know.

Could you also confirm if DBeaver uses the host's cert store, or if it comes with its own set of trusted root certs?

Thanks,
Pranitha

**Comment by Matvey16** [comment]
@Pranithaevana Dbeaver comes with its own set of trusted root certs that are included in Java 11.

**Comment by Pranithaevana** [comment]
Thanks for the response.

Could you provide more details on this. Does it uses JRE?

Thanks,
Pranitha

**Comment by Matvey16** [comment]
@Pranithaevana Yes. But you still haven't answered if you use proxy, because it looks like it is a main issue here and you will need to adjust your preferences

**Comment by uslss** [comment]
there is no update on issue for a long time. if it is still actual for you - feel free to reopen an issue
