### ISSUE TITLE
Auto-complete doesn't work for table aliases in some cases 

### ISSUE THREAD

**Issue by skotlex** [dbeaver/dbeaver#13151]
#### System information: 
- Operating system (distribution) and version `Windows10`
- DBeaver version `21.1.2.20210706094`
- Additional extensions

#### Connection specification:
- Database name and version `Oracle Enterprise Edition 11.2.0.4.0`
- Driver name `Oracle`
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Include any warning/errors/backtraces from the logs

Simple queries work well, but auto-complete functionality does not work in some situations.
Ex,
= work well query
SELECT *
FROM TB.TEST_TABLE TT 
WHERE TT. `--> Press the ctrl+space key to activate auto-complete.`

= not work query
SELECT *
FROM (
    SELECT *
    FROM TB.TEST_TABLE TT 
    WHERE TT. `--> auto-completion not work (If press the ctrl+space key, message popup 'no proposals'`
) T2
, TB.TEST2_TABLE `--> Insert table aliases(in FROM clause) function don't work (my_table mt)`
WHERE 1=1
AND T2. `--> auto-completion not work (If press the ctrl+space key, message popup 'no proposals'`

**Comment by Matvey16** [comment]
Thank you for the report. We will look into it. This issue is not specific to Oracle.

**Comment by uslss** [comment]
#7768

**Comment by LonwoLonwo** [comment]
Still not working in DBeaver 23.0.5

Closing as duplicate of #7768
