### ISSUE TITLE
update to version 21.1.2 means DB/2 AS400 tables "description" column is empty

### ISSUE THREAD

**Issue by medvejonok79** [dbeaver/dbeaver#13153]
Hi there,

I upgraded from version 21.1.0 to 21.1.2 yesterday (running on Windows 10 Professional version 21H1).
I have been using the DB2 AS400 connector. A very useful feature is the "description" column when you are looking at database or table structures. This gives more information on particular columns or table names.
Following the upgrade, the "description" columns became empty. It looks like a regression.
I reinstalled version 21.1.0 and the problem went away, descriptions appearing properly again.

Thanks & best wishes

**Comment by Matvey16** [comment]
@medvejonok79 Hello. Regarding DB2 AS 400 connector, we changed one of the properties to default value in 21.1.2. Can you check the value of `metadata source` property. It was set as `0` in 21.1.0 and changed to `-1` in 21.1.2. You can try manually adjusting it to `0` and see if it helps.

![dbeaver_9maCVJF3m2](https://user-images.githubusercontent.com/82543000/125044026-3ac24280-e0a4-11eb-81c8-66d7ec95b53e.png)

**Comment by medvejonok79** [comment]
Hi - thank you very much; 
I will test and report back but this will have to be later in the summer as I am currently not in the place where I can access the database & do the test

**Comment by velteyn** [comment]
Hello, I think that I have a similar problem so I write it here.
I put the "Metadata source" to 0 as you suggested but if I do a normal query with AS400 like this:
![immagine](https://user-images.githubusercontent.com/1019294/128333768-0b3687e4-f8e4-44bd-9e9b-4f07beb5f6b5.png)

I obtain the column Labels like this:
![immagine](https://user-images.githubusercontent.com/1019294/128333918-269b7ead-14e0-4628-8d73-aa9ac38100f4.png)

But if I run the same query to DBeaver I obtain this:

![immagine](https://user-images.githubusercontent.com/1019294/128334185-c8b5b6a5-e825-466e-bfb7-7c4ffa0df127.png)

I think that the metadata column here should show the column labels in place of the column names..
Thank you

**Comment by velteyn** [comment]
My DBeaver CE version is  

[ DBeaver	21.1.4.202108020335	]

**Comment by Matvey16** [comment]
@velteyn Hello. How does it look with default metadata source property?

**Comment by velteyn** [comment]
It looks exactly the same (-1)

**Comment by Matvey16** [comment]
Can be related to #13335
We will look into it

**Comment by medvejonok79** [comment]
Hello, I've at last been able to test metadata source = 0 and can confirm it works, the descriptions are visible again with this fix.

Thank you very much for your replies. The bug can be closed in my view.
