### ISSUE TITLE
program get crash when type statement in other keyboard layout

### ISSUE THREAD

**Issue by PisitsunT** [dbeaver/dbeaver#13162]
#### System information: 
- Windows 11 x64
- DBeaver 21.1.2
- Additional extensions SSHJ

#### Connection specification:
- Database name and version : PostgreSQL 12, Oracle 11
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : SSL

#### Describe the problem you're observing:
When i use thai keyboard layout (forgot to change to US) and hit ALT+8 for * then the program get crash (no message) and need to close and reopen again (my statement gone)

**Comment by flambchap** [comment]
Hi @PisitsunT. Thank you for the report.

**Comment by flambchap** [comment]
@ShadelessFox I'm assigning you since my short investigation shows that the problem lies somewhere around our SQLRuleScanner. It consumes 100% CPU and blocks UI thread.

**Comment by uslss** [comment]
cannot reproduce it against 21.2.0.
@PisitsunT could you check if it is still reproducible for you?

**Comment by PisitsunT** [comment]
program is working fine now, it's didn't crash anymore.

**Comment by flambchap** [comment]
Hey, that's great news!
