### ISSUE TITLE
Cannot drag tab to existing window

### ISSUE THREAD

**Issue by artgoldberg** [dbeaver/dbeaver#13167]
#### System information: 
- Operating system: MacOS Big Sur: 11.2.3 (20D91)
- DBeaver version: 21.1.0.202106090921

#### Connection specification:
- Database name and version: Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)
Sep 24 2019 13:48:23
Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 (Build 17763: ) (Hypervisor)
- Driver name: don't know
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: Yes, F5 Big-Ip 

#### Describe the problem you're observing:
I cannot drag a log or output tab from one window to another, as [shown](https://www.youtube.com/watch?v=1TLr1vTylwc) in this video.

#### Steps to reproduce, if exist:
Try to drag a log or output tab from one window to another.

**Comment by uslss** [comment]
thank you for the report. will be implemented in the scope of #11533

**Comment by artgoldberg** [comment]
Thanks @uslss 
I do not think that the problem I am reporting is related to #11533 . I just want to move a tab from one DBeaver window to another, which I think I have done in the past. I am sure that in the past I have been able to have all the tabs for results, statistics, log, output in the window pane below the sql query.

This seems like an Eclipse tab and window management problem, and is certainly not a "using results from existing queries as a source for future queries" issue.

Arthur

**Comment by Matvey16** [comment]
@artgoldberg Hello. #11533 is a separate feature, but while implementing it we also added the possibility to move all tabs from the right side (Output log, variables etc) to the bottom with resultset

**Comment by artgoldberg** [comment]
Thank you @Matvey16 
When do you expect #11533 to be released? 
In the meantime, how can I "have all the tabs for results, statistics, log, output in the window pane below the sql query" as I did with the previous version of DBeaver?

**Comment by Matvey16** [comment]
@artgoldberg You can't move them from the right side for now. But the new version with an option to do so is scheduled to be released between 18th and 19th of July depending on your time zone, but that is for Community edition. New Enterprise version is scheduled for late August

**Comment by artgoldberg** [comment]
Thanks @Matvey16 , that sounds good. Let's leave this issue open until I test it in the new version.
