### ISSUE TITLE
How to force close DBeaver in linux?

### ISSUE THREAD

**Issue by algo-se** [dbeaver/dbeaver#13174]
DBeaver client gui is hanged in a Ubuntu machine, is there any command to force close it? In windows I´d just use task manager, but here it does not even appear in system manager.

![image](https://user-images.githubusercontent.com/72490678/125398601-cfcc8080-e3af-11eb-80f0-5ea2eb98a8ef.png)

#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04 LTS
- DBeaver version: 21.1.0
- Java version: openjdk version "11.0.11"
- Additional extensions: nope

#### Connection specification:
- Database name and version: MySQL hosted in AWS, don´t know the version
- Driver name: mysql  Ver 14.14 Distrib 5.7.34,
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: Nope

#### Describe the problem you're observing:
Hanged while dumping

**Comment by algo-se** [comment]
I found it:

`sudo apt install x11-utils`
`xkill`

**Comment by petr-hybler-ofti** [comment]
ps -aux | grep dbeaver
kill -9 PID

**Comment by kAsky53** [comment]
pkill -f dbeaver
