### ISSUE TITLE
Option to stop infinite scripts repetition

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13177]
#### Describe the problem you're observing:
We need to add an option to stop infinite opening of new Scripts if a mistake was made by including the same script in it's own body with `@include` command

#### Steps to reproduce, if exist:
1. Create a script and add the same script itself in the body with `@include` command
2. Run the script

**Actual:** New scripts will be opened infinitely until DBeaver process is killed.

**Expected:** Have an option to stop the loop without closing DBeaver.

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
