### ISSUE TITLE
dbeaver-ce  21.1.2.202107041908  137 snap displays 'boxes' instead of font chars; known issue @ snapcraft?

### ISSUE THREAD

**Issue by pgnd** [dbeaver/dbeaver#13171]
on
```
	lsb_release -rd
		Description:    Fedora release 34 (Thirty Four)
		Release:        34

	snap --version
		snap    2.51-1.fc34
		snapd   2.51-1.fc34
		series  16
		fedora  34
		kernel  5.12.14-300.fc34.x86_64
```

I've installed Dbeaver snap
```
	snap list dbeaver-ce
		Name        Version              Rev  Tracking       Publisher     Notes
		dbeaver-ce  21.1.2.202107041908  137  latest/stable  dbeaver-corp  -
```

It launches with 'squares' instead of font characters:

	https://i.imgur.com/l7RRMNg.png

The issue is raised here:

	https://forum.snapcraft.io/t/snaps-show-squares-instead-of-fonts/18073/5

The suggested cache clear + rebuild:
```
	rm -rf ~/.cache/fontconfig && sudo fc-cache -r -v
```

fails to cure.

@ https://forum.snapcraft.io/t/snaps-show-squares-instead-of-fonts/18073/7

	"I’m being told the problem is fixed in recent snapcraft releases, provided snaps use the right extensions. (cc @sergiusens).

	The other side of the problem is that whoever published a given snap must sufficiently care about their work to basically rebuild the snap using the latest version of snapcraft."

checking, dbeaver's snap doesn't bundle "manifest/yaml"
```
	find /var/lib/snapd | grep -i yaml$ | grep -i beaver | grep 137
		/var/lib/snapd/snap/dbeaver-ce/137/meta/snap.yaml
```

so not clear what
```
	snapcraft-version: ???
```
has been use to build dbeaver

**Comment by pgnd** [comment]
Directly installing DL'd rpm,

https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm

provides a bin without these snap-related font issues.

Is dbeaver-ce snap planned to be updated/maintained?
Or should we be instead switching to rpm, and managing updates ourselves?

**Comment by pgnd** [comment]
deleted the snap.  no longer in use.
close @ your discretion.

**Comment by der-eismann** [comment]
Would be awesome if someone could take care of this, a snap is just so much easier to install and use.
I have the same issue on Fedora 35 and found this additional forum post:
https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/106
