### ISSUE TITLE
Trailing NULL during the DDL generation 

### ISSUE THREAD

**Issue by YuriDude** [dbeaver/dbeaver#13184]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: CE - Version 21.1.0.202106032102
- Additional extensions: None

#### Connection specification:
- Database name and version: Microsoft SQL Server 2012 (SP2-GDR) (KB3194719) - 11.0.5388.0 (X64) 
- Driver name: not sure
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: NO

#### Describe the problem you're observing:
During the DDL generation there is a trailing "null" generated in syntax. So, resulting ALTER statement looks like:

**ALTER TABLE <DB.SCHEMA.TABLE> WITH NOCHECK ADD CONSTRAINT <CONSTRAINT_NAME> CHECK _null_;**

#### Steps to reproduce, if exist:
Reverse engineering a table.

#### Include any warning/errors/backtraces from the logs

Not sure of logs are needed and/or relevant.

I 've researched MSDN for syntax template: it doesn't seems that trailing null should be a part of the syntax.
Bug was/is discovered as part of ERD generation and dealt with by manual deletion of null.

**Comment by Matvey16** [comment]
Can you please provide steps to reproduce the issue? What exact DDL generation are you talking about?

**Comment by YuriDude** [comment]
See attached.
![2021-07-14 09_36_42-DBeaver 21 1 0 - TurnScheduleItem](https://user-images.githubusercontent.com/5156159/125632670-5cceecf7-7ea3-4fdd-95e5-c288f4ae8d83.jpg)

**Comment by LonwoLonwo** [comment]
Hello @YuriDude 
How did you do these check constraints? On null place must be check constraint condition.
Original table DDL will be very helpful.
Also can you please check the result of this query:
`SELECT * FROM master.sys.check_constraints WHERE parent_object_id=929542495`
I used table id from your picture.

**Comment by YuriDude** [comment]
@LonwoLonwo ,
thanks for expeditious reply!
I obviously  did not do these constraints ;-) . They are generated by tool.

Steps to reproduce:
1. In tables browser: either F4 (view table) option or right-mouse-click .
2. On Table components  tab set (tab pages: Properties, Data, ER Diagram): click on DDL.
3. Resulting script will have ALTER statement(s) with trailing null.

Also: the same behavior if/when **multiple** tables selected in the schema browser and options "Generate SQL -> DDL " are chosen from context menu (right-mouse-click)

In reference to your SQL statement:  No Data is returned by the query.

Original DDL has/had only set of the columns with datatypes and Primary Key constraint. 

If you are using internally some templates, you might want to look into them.

**Comment by LonwoLonwo** [comment]
Strange. 

1. Ok, can you please tell me - do you have check constraints in your table or not? In TurnScheduleItem, as an example.

2. if you manually create table like this:
```sql
CREATE TABLE Persons (
    ID int NOT NULL,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int CHECK (Age>=18)
); 
```
Will she have the correct syntax (with the right check condition), as in the picture?

![2021-07-14 17_49_05-Window](https://user-images.githubusercontent.com/45152336/125642853-ab816f2b-6a7a-436d-9162-99ca133f4db0.png)

**Comment by YuriDude** [comment]
Hi again!
So:
1.  SELECT * FROM master.sys.check_constraints WHERE parent_object_id=929542495 has no data.  
2. select * from INFORMATION_SCHEMA.CHECK_CONSTRAINTS - does have data and one of the constraint name is indeed constraint with trailing null.
![2021-07-14 11_48_52-DBeaver 21 1 0 - _ESR_ Console](https://user-images.githubusercontent.com/5156159/125652472-cf9a02c3-4ef1-4703-a340-a94886dfe8c2.jpg)
3. Unfortunately,  I can't run  your simple diagnostics for table creation: my DB account is READ-ONLY.
4. Database character set: SQL_Latin1_General_CP1_CI_AS

_Broader context: Database is replicated instance_

**Comment by LonwoLonwo** [comment]
Hmm. Maybe you can tell me - what permission do you have? Looks like the problem is in the check_clause column reading, so I need to reproduce it to find a solution.

**Comment by YuriDude** [comment]
Hi @LonwoLonwo ,
See attached...
![1](https://user-images.githubusercontent.com/5156159/125806852-897524dc-0f17-4703-a378-0ef0eeb54747.jpg)
All other options for function call return 0 (zero) data

**Comment by Matvey16** [comment]
Can you attach a DDL in text form so we can try reproducing this issue?

**Comment by YuriDude** [comment]
@Matvey16 
As you may (or may not ;-) ) recall from our other conversation, I had other problem and it was resolved by my system (my "_local machine"_) updates with latest patches by Microsoft. Today , I double checked on this issue (problem at-hand we are discussing... ) and it seems that it got resolved too. Which made me thinking that originally problems were related to the SQL Server driver since all got resolved by updates to the "local infrastructure".
Anyways - feel free to close this bug!
![2021-07-21 11_22_58-DBeaver 21 1 0](https://user-images.githubusercontent.com/5156159/126515831-0f463f58-ff89-4dd7-8ac2-69b96f5bdc15.jpg)
