### ISSUE TITLE
Oracle DDL generation fails

### ISSUE THREAD

**Issue by RamonCar66** [dbeaver/dbeaver#13187]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.1.2.202107041908
- Additional extensions: none (known)

#### Connection specification:
- Database name and version:
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
PL/SQL Release 11.2.0.4.0 - Production
"CORE	11.2.0.4.0	Production"
TNS for Linux: Version 11.2.0.4.0 - Production
NLSRTL Version 11.2.0.4.0 - Production

- Driver name: ODAC112040_64
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
When I click an existing table in the tree, and I ask DBeaver to generate the DDL, I receive the following error:

SQL Error [1417] [72000]: ORA-01417: a table may be outer joined to at most one other table

  Error : 1417, Position : 397, Sql = SELECT  i.OWNER,i.INDEX_NAME,i.INDEX_TYPE,i.TABLE_OWNER,i.TABLE_NAME,i.UNIQUENESS,i.TABLESPACE_NAME,i.STATUS,i.NUM_ROWS,i.SAMPLE_SIZE,
ic.COLUMN_NAME,ic.COLUMN_POSITION,ic.COLUMN_LENGTH,ic.DESCEND,iex.COLUMN_EXPRESSION
FROM ALL_INDEXES i
, ALL_IND_COLUMNS ic, ALL_IND_EXPRESSIONS iex WHERE ic.INDEX_OWNER=i.OWNER AND ic.INDEX_NAME=i.INDEX_NAME 
AND iex.INDEX_OWNER(+)=i.OWNER AND iex.INDEX_NAME(+)=i.INDEX_NAME AND iex.COLUMN_POSITION(+)=ic.COLUMN_POSITION
AND i.TABLE_OWNER=:1  AND i.TABLE_NAME=:2 
ORDER BY i.INDEX_NAME,ic.COLUMN_POSITION, OriginalSql = SELECT  i.OWNER,i.INDEX_NAME,i.INDEX_TYPE,i.TABLE_OWNER,i.TABLE_NAME,i.UNIQUENESS,i.TABLESPACE_NAME,i.STATUS,i.NUM_ROWS,i.SAMPLE_SIZE,
ic.COLUMN_NAME,ic.COLUMN_POSITION,ic.COLUMN_LENGTH,ic.DESCEND,iex.COLUMN_EXPRESSION
FROM ALL_INDEXES i
, ALL_IND_COLUMNS ic, ALL_IND_EXPRESSIONS iex WHERE ic.INDEX_OWNER=i.OWNER AND ic.INDEX_NAME=i.INDEX_NAME 
AND iex.INDEX_OWNER(+)=i.OWNER AND iex.INDEX_NAME(+)=i.INDEX_NAME AND iex.COLUMN_POSITION(+)=ic.COLUMN_POSITION
AND i.TABLE_OWNER=? AND i.TABLE_NAME=?
ORDER BY i.INDEX_NAME,ic.COLUMN_POSITION, Error Msg = ORA-01417: a table may be outer joined to at most one other table

  ORA-01417: a table may be outer joined to at most one other table

#### Steps to reproduce, if exist:
1. select a table o the tree
2. right click on "Generate SQL" / DDL

**Comment by uslss** [comment]
thank you for the report.
Issue was fixed in #13025 .
Fix will be available in 21.1.3 and already available in [EA version](https://dbeaver.io/files/ea/)
