### ISSUE TITLE
Script is not executed if called from another script

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13180]
#### System information: 
- DBeaver version 21.1.3

#### Describe the problem you're observing:
Using `@include` command doesn't execute the script called with it if you have and option "Open separate connection for each editor" enabled in preferences.  

#### Steps to reproduce, if exist:
1. Enable  "Open separate connection for each editor" option in preferences
2. Use `@include` command to call a any script in SQL console

**Expected:** Script is executed
**Actual:** Script is opened and closed without execution

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
