### ISSUE TITLE
Download of the installation version doesn't work

### ISSUE THREAD

**Issue by Fiance1** [dbeaver/dbeaver#13189]
#### System information: 
- System: MS Windows 10 Pro 10.0.17134 Build 17134
- DBeaver version: 21.1.0.202106012023

#### Describe the problem you're observing:

I can't download installation version for several days.

![image](https://user-images.githubusercontent.com/2932385/125586151-8fb2bdce-910d-496d-b9e7-2b3adf1ea5a1.png)

![image](https://user-images.githubusercontent.com/2932385/125586572-785656ce-d89f-4767-8c47-6354905dabdc.png)

**Comment by Matvey16** [comment]
It seems to be something with your network. I can download it directly from that link. Do you have any specific proxy or firewall settings?

**Comment by Fiance1** [comment]
You're right. I switched to another hotspot and everything went OK.
Thanks.
