### ISSUE TITLE
FIX Table structure Diagram: draw foreign key link lines from field to field

### ISSUE THREAD

**Issue by allanlaal** [dbeaver/dbeaver#1319]
right now the foreign key relation lines are drawn between different table boxes from random positions

it would be better UX if the relations would be drawn from the field itself

**Comment by serge-rider** [comment]
I see at least two problems:
- Quite often relations are multi-column
- Relations layout will become much more messy (lines will cross all the time)

Currently you can click on a relations and see what actual columns are used.

**Comment by allanlaal** [comment]
I would gladly accept messyness to get all the information at a glance rather than clicking on all of the 10..N foreign key lines to see what they are about ;)

**Comment by uslss** [comment]
will be tracked in #7257
