### ISSUE TITLE
Menu Bar: Open File item disappeared

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13191]
#### System information: 
- Win10, DBeaver CE 21.1.3

#### Describe the problem:
There has no **Open File...** item in File dropdown list, but it was in the previous versions  
![image](https://user-images.githubusercontent.com/43252954/125601500-c7531b0a-2736-4b03-be42-52bacbeea85b.png)
![image](https://user-images.githubusercontent.com/43252954/125601490-30fc213c-25c4-4e17-a17a-62bee4c17adf.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by DariaMarkaryan** [comment]
Verified
