### ISSUE TITLE
dbeaver 官网进不去了

### ISSUE THREAD

**Issue by ocean-zhc** [dbeaver/dbeaver#13190]
dbeaver官网是挂了吗？进不去了
![image](https://user-images.githubusercontent.com/46189785/125594280-5e407382-12a7-4ed2-a0fd-3d57d6baa010.png)

**Comment by Matvey16** [comment]
Please check your internet connection. The site loads fine for me.

**Comment by ocean-zhc** [comment]
Tks!
It's our company network problem, sorry！
