### ISSUE TITLE
set active connection on a file script that's opened from command line

### ISSUE THREAD

**Issue by drc-ykim** [dbeaver/dbeaver#13196]
**Is your feature request related to a problem? Please describe.**
There is another request (#2095) which is similar in context but I don't want to execute the script (this, I'm guessing will have a connection established to do it) as requested in #2095.  

**Describe the solution you'd like**
I'd like to open a file but just connect to the connection info specified in '-con' w/o executing it since the .sql could be parameterized and not executable. *Maybe an execution can be another option to add to '-con' or '-f'.

**Describe alternatives you've considered**
It'd be similar to 'openConsole' in the '-con' but attach it to the file opened w/ '-f'.

**Additional context**
"C:\Program Files\DBeaver\dbeaver.exe" -f "%userprofile%\Documents\DBeaver\Script.sql" -con "name=..|host=..." to establish connection on "open" based on information specified in'-con'.

**Comment by Matvey16** [comment]
Doesn't work if the script was already opened for another connection

**Comment by Matvey16** [comment]
Verified
