### ISSUE TITLE
BigQuery Auto-Completion

### ISSUE THREAD

**Issue by pandasnew** [dbeaver/dbeaver#13199]
Hi,
I‘m using Dbeaver for a long time and I‘m a big fan. Currently I‘m using Google BigQuery. Is a possibility to use auto-completion? In other databases, for example DB2 and SQL Server auto-completion works fine. 

I‘m using the standard database-connector for bigquery. 

Thanks!

**Comment by uslss** [comment]
@pandasnew cannot reproduce the issue.
Does auto-completion for big query not work for you at all? is there something in the logs?
![image](https://user-images.githubusercontent.com/31996417/126130405-2cc438e2-57dd-41c3-afc9-f3b6fd7f54ac.png)

**Comment by uslss** [comment]
there is no update on issue for a long time.
If it is still actual - feel free to reopen it with additional info that will help to reproduce an issue.
