### ISSUE TITLE
DBeaver CE and Microsoft Store: syncing versions & dates

### ISSUE THREAD

**Issue by YuriDude** [dbeaver/dbeaver#13209]
DBeaver Team,

First: **_EXCELLENT TOOL_** to work in heterogeneous environments where multiple types of DB **Vendors** and **versions** are used! 
And that matrix of usage would be huge !

Next: 
In somewhat strict environments where software installations are limited and controlled by SysAdmins/NetworkAdmins and others that new method of using Microsoft Store is viable alternative to "local" bureaucracy. However, it would be helpful that versions, dates , release and other all would match.
I have DBeaver version   Version 21.1.0.202106032102 that was released May 31, 2021 however, Microsoft Store signature says otherwise... (see attached). Not sure if it is in your "control" or Microsoft "control", but it has to be in sync.
![DBeaver-Store](https://user-images.githubusercontent.com/5156159/125820848-8518ce4f-2285-44f0-9187-f02a4644c1cb.JPG)

**Comment by Matvey16** [comment]
@YuriDude Thank you for the suggestion. This date is in Microsoft control and it states the day when an app was added to the Microsoft Store and is irrelevant to the last update date.
