### ISSUE TITLE
Incorrect array data shows in record mode

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13206]
#### System information: 
- Win10, DBeaver CE 21.1.3 

#### Connection specification:
Non specific
#### Describe the problem you're observing:
there is a table with array data type:
![](https://i.imgur.com/fkAOazx.png)
Select multiple rows and switch to record mode
Value of arrary for al columns set as the value of the first row:
![](https://i.imgur.com/ABXmbNp.png)
if select two last rows:
![](https://i.imgur.com/iL2u0KG.png)
i.e. the number of values is highlighted based on the topmost in the selected rows, as well as the value from the top row is set for all rows
one more example
![](https://i.imgur.com/yC8uATl.png)
![](https://i.imgur.com/0FeHC3y.png)

In PostgreSQL:
![image](https://user-images.githubusercontent.com/43252954/129553769-954de17d-9d9b-48ab-8c6f-4d160b6019c7.png)
![image](https://user-images.githubusercontent.com/43252954/129553723-b23c574f-9cd6-472e-8dc6-122d86e82460.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by DariaMarkaryan** [comment]
Bug is still reproduced in ClickHouse

**Comment by LonwoLonwo** [comment]
Can't reproduce it against DBeaver 23.2.3 with the non-legacy driver.

![2023-10-31 16_11_10-DBeaver Ultimate 23 2 3 - array_test](https://github.com/dbeaver/dbeaver/assets/45152336/00ae077f-334f-4a25-9323-42c49e22f0c7)

Is it still reproducible @DariaMarkaryan ?

**Comment by DariaMarkaryan** [comment]
no longer reproduceable
