### ISSUE TITLE
All rows with the same values are deleted when one of them was deleted

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13207]
#### System information: 
- Win10, Dbeaver CE 21.1.3
#### Connection specification:
- Clickhouse

#### Steps to reproduce, if exist:
If there are multiple rows with the same values and we delete one of them, all these rows will be deleted
Steps:
select one row, multiply it and save. Then delete one of them and refresh. As the result, all rows with the same values will be deleted

https://user-images.githubusercontent.com/43252954/125811952-5eede0d2-b645-465e-9f51-4b84b6352406.mp4

DDL:
```
CREATE TABLE default.array_type
(

    `id` UInt16,
 
    `strings` Array(LowCardinality(String)),
 
    `Column1` String
)
ENGINE = MergeTree()
ORDER BY id
SETTINGS index_granularity = 8192
```

**Comment by LonwoLonwo** [comment]
And what's in the delete script? What do you use as a delete key?

**Comment by DariaMarkaryan** [comment]
query for deleting. only use delete key + save. Is the order by works like the primary key?
ALTER TABLE default.array_type DELETE 
	WHERE id=3 AND strings=DATA(ClickHouseArray) AND Column1=''

**Comment by DariaMarkaryan** [comment]
Seems that there is no way to delete only one non-unique row in clkickhouse
