### ISSUE TITLE
Oracle schema DDL

### ISSUE THREAD

**Issue by YuriDude** [dbeaver/dbeaver#13208]
#### System information: 
- Operating system (distribution) and version: Windows 10 [Version 10.0.19042.985]
- DBeaver version: Version 21.1.0.202106032102
- Additional extensions: None .

#### Connection specification:
- Database name and version: Generic: ORACLE & MS SQL
- Driver name: not sure
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: NO

#### Steps to reproduce, if exist:
Images are attached.
#### Describe the problem you're observing:
For schemas: 
In Oracle missing option "Generate SQL" from context menu (right-mouse-click) at **schema** level.
MS SQL versus Oracle image for comparison is attached.
![Ora_VS_MSSQL](https://user-images.githubusercontent.com/5156159/125817930-be4679ce-83ef-4b66-b3e5-03b92d569e79.jpg)
If it is by design ;-) , then why when **block** of tables is selected option does present? 
![ORA-SET_OF_TABLES](https://user-images.githubusercontent.com/5156159/125817985-f5b1166e-c735-4df1-bccc-33b45a8e82db.jpg)

**Comment by Matvey16** [comment]
@YuriDude Hello. This is expected behavior, because schemas in Oracle are more akin to user's personal folder. To create a schema you need to create new user, while in MS SQL Server Schemas don't need to be associated with a specific user.
Do yo have a specific task that requires a generation of DDL for an Oracle Schema and what do you want to se there?

**Comment by YuriDude** [comment]
Not sure if i would agree with "...schemas in Oracle are more akin to user's personal folder...". There are indeed schemas in Oracle that are **user** and "tableless". 
However, my expectations for more-or-less similar structured RDBMS' (Oracle/MS SQL/Postgres, etc...) that they will have same end-user interface on DBeaver. If, "something is missing" in case of "tableless" schema  (a user in Oracle) then a message maybe generated **post-factum**.
I do have a task to generate DDL for the whole schema in both Oracle & MS SQL thus was the request.

**Comment by Matvey16** [comment]
@YuriDude What do you want to see in that DDL? To generate a DDL for a schema it would require to include user's password in it, which is bad for security.

**Comment by Matvey16** [comment]
@YuriDude Thank you, we will look how it can be implemented
