### ISSUE TITLE
Decimal is incorrectly displayed in MS SQL

### ISSUE THREAD

**Issue by YuriDude** [dbeaver/dbeaver#13211]
#### System information: 
- Operating system (distribution) and version: Windows 10 - Microsoft Windows [Version 10.0.19042.985]
- DBeaver version: Version 21.1.0.202106032102
- Additional extensions: none

#### Connection specification:
- Database name and version: Microsoft SQL Server 2012 (SP2-GDR) (KB3194719) - 11.0.5388.0 (X64) Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)
- Driver name: not sure
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Describe the problem you're observing:
Decimals are not correctly displayed.
See attached...
Also - icon was strange , I don't think I saw it anywhere else within the DBeaver Tool.

![decimal](https://user-images.githubusercontent.com/5156159/125835479-1b1d1ffe-70a6-4266-8cba-88bb8288c27f.jpg)
Using available for me other tools (Azure DataStudio) I was able to determine that erroneously displayed datatype is decimal.
See attached...
![Azure-DataStudio](https://user-images.githubusercontent.com/5156159/125835516-4a731b8d-af48-456f-8f83-c7cb348de6c2.jpg)

#### Include any warning/errors/backtraces from the logs

ps.
This is low priority bug. It is **nuisance**, but not the show-stopper (no impact on development/modeling, etc...)

**Comment by uslss** [comment]
@YuriDude ,
unfortunately cannot reproduce the issue against 21.1.3. Could you provide ddl example to reproduce it?

**Comment by YuriDude** [comment]
You should be able to use any generic DDL with Decimal datatype and don't really need DDL from _me_.
I am using  **21.1.0** as stated above; if it is known bug and has been address in 21.1.3 then it is irrelevant.

**Comment by Matvey16** [comment]
@YuriDude I was not able to reproduce it on 21.1.0 Is it displayed like this for every table with decimal column? Also can you at least show how this column looks in Source (DDL) tab?

![dbeaver_pDip0JEW8R](https://user-images.githubusercontent.com/82543000/126164132-b947163d-394a-4ea2-9dbc-00dd12151126.png)

![dbeaver_XbgG6M6Ye4](https://user-images.githubusercontent.com/82543000/126164146-a144e9c4-fcd3-45ef-8ff3-dba995613b26.png)

**Comment by YuriDude** [comment]
Well...
My "local machine" has been patched by Microsoft with latest updates over the weekend. Seems that problem was related to my local "image": I **have decimals** now 👍 . 
My local image: Microsoft Windows [Version 10.0.19042.**1052**]  _.... see above to the state before..._

**Comment by Matvey16** [comment]
@YuriDude Glad it was resolved
