### ISSUE TITLE
Wrong script generated to create table with bpchar column when exporting a table

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13218]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 21.1.3

#### Connection specification:
- Database name and version Redshift
- Driver name JDBC

#### Describe the problem you're observing:
When transfering tables to another schema with `create` mapping, the generated SQL script to create table uses column data type as `bpchar` with length in parenthesis. This leads to an error, it needs to either generate `bpchar` without length or use `char(256)` like when generating DDL in table's properties tab.

#### Steps to reproduce, if exist:
1. Create table `CREATE TABLE IF NOT EXISTS testzz(Column1 BPCHAR ENCODE lzo)DISTSTYLE AUTO;`
2. Try to export it to another schema.

**Expected:** Table is exported
**Actual:** Error in syntax

#### Include any warning/errors/backtraces from the logs
`SQL Error [500310] [42601]: [Amazon](500310) Invalid operation: syntax error at or near "(" 
Position: 49;
  [Amazon](500310) Invalid operation: syntax error at or near "(" 
Position: 49;
  [Amazon](500310) Invalid operation: syntax error at or near "(" 
Position: 49;
`  

Query that is executed
`CREATE TABLE public.testzz (
	venuestate bpchar(256) NULL
))`

**Comment by LonwoLonwo** [comment]
Fixed. Now we read bpchar data type as char in Redshift according to [documentation](https://docs.aws.amazon.com/redshift/latest/dg/r_Character_types.html).

**Comment by Matvey16** [comment]
Verified
