### ISSUE TITLE
Generated SQL expression is not valid for geometry type

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13215]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.3 EA

#### Connection specification:
- Database name and version MySQL

#### Steps to reproduce, if exist:

1. Open a table with geometry type
2. Generate insert or update  expression and execute in in SQL Editor

**Expected:** the statement is successfully executed
**Actual result:** the execution fails because the generated expression
```
INSERT INTO sakila.address
(address_id, address, address2, district, city_id, postal_code, phone, location, last_update)
VALUES(605, '757 Rustenburg Avenues', '', 'Haryana', 582, '28396', '465887807014', 'POINT (1 2)', '2021-06-16 11:06:05');
```
gives an SQL error:
`SQL Error [1416] [22001]: Data truncation: Cannot get geometry object from data you send to the GEOMETRY field
`

**Note:** Query managers shows another SQL expression when geometry type is edited in the Data Editor
```
INSERT INTO sakila.address (address_id,address,address2,district,city_id,postal_code,phone,location,last_update)
	VALUES (605,'757 Rustenburg Avenues','','Vaud',296,'28396вв','145308717464',0x000000000101000000CE273CB203881A40205734E72A424740,'2020-03-15 20:12:05')
```

**Comment by Matvey16** [comment]
Verified
