### ISSUE TITLE
Auto-complete doesn't insert pattern schema_name.table_name

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13216]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.3 EA

#### Connection specification:
- Database name and version MySQL

#### Steps to reproduce, if exist:
1. Click MySQL connection in DB Navigator and open SQL Editor 
2. Write select * from table_name
3. Open auto-complete a select the table with the schema

**Expected:** the table name is inserted with the sxhema name (e.g. sakila.address) and the SQL expression can be executed
**Actual result:** only the table name is inserted and execution fails.

https://user-images.githubusercontent.com/51405061/125892334-5221364b-1b8d-44ca-805c-c15cf8dccf3f.mp4

**Comment by LonwoLonwo** [comment]
![jfc7xRr1D7](https://user-images.githubusercontent.com/45152336/150692840-1d5e5642-7145-4fb5-85a5-a9adea9e0712.gif)

Can't reproduce against in DBeaver 21.3.3
