### ISSUE TITLE
It is suggested to add a function of importing data from pasteboard.

### ISSUE THREAD

**Issue by grassvalley** [dbeaver/dbeaver#13214]
Many times, you need to import data from the spreadsheet to the database, the amount of data is not large, but if you first export as a CSV file, and then import the database, the operation is more troublesome. If only you could import data directly from the pasteboard, just like libreoffice base.

**Comment by uslss** [comment]
@grassvalley could you provide more info on how do you want to see it? 
Do you want to paste data to the table that already exists?

**Comment by uslss** [comment]
there is no any update on ticket for a long time.
if it is still actual for you, feel free to reopen it with additional info
