### ISSUE TITLE
Copy selected columns as a comma-delimited list

### ISSUE THREAD

**Issue by taf1-cornell-edu** [dbeaver/dbeaver#13223]
When copying selected columns on a table or view tab, and in the database navigator, they are copied as an undelimited list of the column names with each column name on a separate line.  When I paste that list, I then have to manually add comma delimiters and usually manually combine them into 1 line to use them in a SELECT for example.

An option to copy selected columns as a comma-delimited list of column names (single line would be best, multiple lines would be usable,) would save all the manual steps.  I could then paste them into the select list in a sql statement as-is.
E.g. if I select and copy columns c1, c2, c3 and then paste them in a SQL editor, they show up like this:

c1
c2
c3

It would be very useful to have them show up as this:
c1, c2, c3

**Comment by p91paul** [comment]
try advanced copy (right click menu or ctrl+shift+c). You can choose what delimiter to use.

Also, if you copied the unseparated list, in sql editor you can select values, right click and use format -> morph to delimited list.

**Comment by taf1-cornell-edu** [comment]
My right click menu looks like this:  
![image](https://user-images.githubusercontent.com/3789051/125995362-e6e0abdf-b4a4-49ba-9ab0-314d95e9a4cd.png)

'advanced copy' isn't included.  'Copy Advanced Info' (Ctrl+Shift_C) copies the column names with 

Column Name	#	Data type	Identity	Collation	Not Null	Default	Comment
e.g.:
Column Name	#	Data type	Identity	Collation	Not Null	Default	Comment
species_code	1	varchar(10)	[NULL]	default	true	[NULL]	[NULL]
locale_code	2	varchar(10)	[NULL]	default	true	[NULL]	[NULL]
com_name	3	varchar(128)	[NULL]	default	true	[NULL]	[NULL]
indexed_com_name	4	varchar(128)	[NULL]	default	false	[NULL]	[NULL]

I'm using Community Version 21.1.2.202107041908.

--I wasn't aware of the 'right click and use format -> morph to delimited list.' in the SQL editor.
That will work.  Thanks!
