### ISSUE TITLE
Windows shortcut is to "dbeaver.exe -nl en"

### ISSUE THREAD

**Issue by gregid** [dbeaver/dbeaver#13221]
#### System information: 
- Windows 10
- DBeaver version: Version 21.1.2.202107041908

#### Describe the problem you're observing:
The windows installer creates a shortcut to `dbeaver` and hardcodes the locale to English `dbeaver.exe -nl en` (or possibly the language set during installation - but English will be used when a user can't find his own language in the installer).

The manual and info window in dbeaver suggests that change of the locale should be done in `dbeaver.ini` but no change in ini file will help if the user clicks on the shortcut afterwards, since it overwrites ini setting.

I suggest the shortcut should be without the locale parameter

**Comment by gregid** [comment]
One more argument for the change: dbeaver update overwrites the shortcut files again forcing `en` localization.
I would still consider it a bug (though a minor one)

**Comment by uslss** [comment]
duplicates #12771
