### ISSUE TITLE
Created Unique key dissapears after creation

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13229]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.3 EA

#### Connection specification:
- Database name and version H2 embedded 

#### Steps to reproduce, if exist:
1. Create a Unique ket via Metadata Editor
2. Refresh Keys tab

**Expected**: the unique key is displayed in the tab
**Actual result:** the key disappears from the tab but it it included in the table DDL

**Comment by LonwoLonwo** [comment]
All support added here: https://github.com/dbeaver/dbeaver/issues/14496

**Comment by uslss** [comment]
verified
