### ISSUE TITLE
Navigation view can't be changed to Custom without its change

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13225]
### System information: 
- Won10, DBeaver CE 21.1.3
- Non-specific for connection (tested for sqlite and clickhouse)
#### Describe the problem you're observing:
If you try to change navigation view to Custom without any changes in custom settings, reconnect dialog won't be shown and the type won't change
#### Steps to reproduce, if exist:
F4 when connection selected -> General tab  -> simple/advance type is selected -> select Custom and click OK.
Expected: Dialog for reconnection was shown and after confirmation you can see changes. In connection configuration selected Custom type 
Actual: the reconnect dialog box didn't appear and when you reopen the settings, you can see that we've rolled back to the previous type

https://user-images.githubusercontent.com/43252954/129552574-72c548a5-ee7b-40e2-8627-39e012cca4b6.mp4

**Comment by ShadelessFox** [comment]
So, the solution would be to display that reconnect confirmation popup.

**Comment by ShadelessFox** [comment]
Actually, it works as expected - the <kbd>Custom</kbd> profile is just an indicator that custom view preset was configured.
