### ISSUE TITLE
Can't truncate Redshift table using DBeaver tools

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13220]
#### System information: 
- DBeaver version 21.1.3

#### Connection specification:
- Database name and version Redshift
- Driver name 1.2.45.1069/RedshiftJDBC42-no-awssdk-1.2.45.1069

#### Describe the problem you're observing:
When trying to truncate a table with context menu `Tools > Truncate` incorrect query will be executed which leads to SQL error.

#### Steps to reproduce, if exist:
1. Try to truncate a table with `Tools > Truncate`

**Expected:** Table is truncated
**Actual:** `TRUNCATE TABLE table_name CONTINUE IDENTITY RESTRICT` is executed which leads to error

#### Include any warning/errors/backtraces from the logs
`[500310] [Amazon](500310) Invalid operation: syntax error at or near "CONTINUE" 
Position: 29;`

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.2.2

Truncate settings now depend on the database.

![134922254-c467399a-5417-4156-b749-ec01753e6522](https://user-images.githubusercontent.com/45152336/135235833-d62048f0-2542-4369-8b1d-b6c43773d20a.png)
r

**Comment by Matvey16** [comment]
Verified
