### ISSUE TITLE
Edit task resets destination folder

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13222]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 21.1.3

#### Describe the problem you're observing:
When trying to edit export task the destination folder for resulting file is automatically reset to default

#### Steps to reproduce, if exist:
1. Create a task to export table into a file and select any non-default destination folder
2. Start editing task

**Expected:** Every setting is the same as was saved until it is changed.
**Actual:** Destination folder changes on it's own, so if you want to change other settings and save task, the destination folder can be changed without your knowledge.

![glx3NHFhz5](https://user-images.githubusercontent.com/82543000/125941601-96fab952-6e07-4c14-ac0e-ff061adba9a2.gif)

**Comment by serge-rider** [comment]
Duplicate of #13589

**Comment by Matvey16** [comment]
Verified
