### ISSUE TITLE
Variable search bar exceeds window border

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13230]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 21.1.3

#### Describe the problem you're observing:
Need to adjust search bar so it does not go over border

![dbeaver_qxqQyL3nXi](https://user-images.githubusercontent.com/82543000/125957435-9274ab1f-b974-4aa8-9966-7f28b05a9a21.png)

**Comment by LonwoLonwo** [comment]
![2021-08-20 12_43_24-Window](https://user-images.githubusercontent.com/45152336/130256046-107918ad-5de8-4077-b0a3-241a98d5b711.png)

Fixed. Few more pixels on top were added.

**Comment by Matvey16** [comment]
Verified
