### ISSUE TITLE
Don't create new columns when executing the same task more than once

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13235]
#### Describe the problem you're observing:
When creating export task with a mapping to create new columns it still tries to create columns when executing it for the second time.

#### Steps to reproduce, if exist:
1. Create a task for data export with mapping to create new columns
2. Execute a task
3. Execute a task for the second time

**Expected:** Export is successful and only data is exported
**Actual:** DBeaver tries to create columns that already exist which leads to an error

**Comment by serge-rider** [comment]
Can't reproduce anymore.
Seems to be fixed in one of previous releases.

**Comment by Matvey16** [comment]
Verified
