### ISSUE TITLE
Create table: DDL does not include primary key

### ISSUE THREAD

**Issue by maffe** [dbeaver/dbeaver#13238]
#### System information: 
- Windows 10 64 Bit
- DBeaver 21.1.2

#### Connection specification:
- PostgreSQL server 10.13
- PostgreSQL driver 42.2.8
- Not using tunnels or proxies

#### Describe the problem you're observing:
Primary key is not included in the DDL

#### Steps to reproduce, if exist:
- Right-click on tables, choose Create table
- Add column1
- Switch to constraints, add primary key over column1
- Switch back to columns, add column2
- DDL contains both columns, but not the key

**Comment by uslss** [comment]
@maffe thanks for the report.
unfortunately, cannot reproduce the issue. Probably some special steps are needed?
![2021-07-18_19h44_23](https://user-images.githubusercontent.com/31996417/126075375-92fb2892-c381-492c-9175-2660642f1b69.gif)

**Comment by maffe** [comment]
After creating the second column, do not press save, but click on the DDL tab.
![grafik](https://user-images.githubusercontent.com/515302/126979390-a1294020-1340-49bf-8846-b00755204e33.png)

**Comment by LonwoLonwo** [comment]
Still relevant in DBeaver 22.0.2

**Comment by LonwoLonwo** [comment]
Still relevant in DBeaver 22.1.2
