### ISSUE TITLE
Auto assign remembers the case of the previous container

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#13236]
StR:

1. Open SQLite version of Chinook.
2. Select Album -> Export data -> Database
3. Change the name of the target database to Album2. Mapping type changes to create.
4. Change target container to a DB with upper case or lower case names.
5. Hit auto-assign. The names change their case.
6. Change container back to SQLite, hit auto-assign. The case did not change. However, the case should be exactly as in the step 3.

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
