### ISSUE TITLE
Edit import task window shows '?' instead of  destination table

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13232]
#### System information: 
- Win10, DBeaver CE 21.1.3

#### Describe the problem you're observing:
Wen you open created task there is problems with displaying target table
But you still can successfully run this task

https://user-images.githubusercontent.com/43252954/125957916-e7c43b52-055b-4178-b8c6-fb819d6afdb4.mp4

**Comment by LonwoLonwo** [comment]
Can't reproduce anymore. May be fixed in scope of https://github.com/dbeaver/dbeaver/issues/11304

**Comment by Matvey16** [comment]
Verified
