### ISSUE TITLE
Create table: DDL is not updated after viewing it once

### ISSUE THREAD

**Issue by maffe** [dbeaver/dbeaver#13237]
#### System information: 
- Windows 10 64 Bit
- DBeaver 21.1.2

#### Connection specification:
- PostgreSQL server 10.13
- PostgreSQL driver 42.2.8
- Not using tunnels or proxies

#### Describe the problem you're observing:
When creating a table via the GUI, the DDL is not updated after viewing it once.

#### Steps to reproduce, if exist:
- Right-click on tables, choose Create table
- Add column1
- View DDL, see table definition with column1
- Add column2
- View DDL, column2 is not included

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
verified
