### ISSUE TITLE
Select JSON display format by default in Value panel's for JSON columns

### ISSUE THREAD

**Issue by CComparon** [dbeaver/dbeaver#13243]
**Is your feature request related to a problem? Please describe.**
I use DBeaver with a MySQL database that has many JSON table columns. This is a native column type in MySQL.
However when selecting a value in such a column and viewing it in the "Value" side panel, I still have to go ahead and change the display format to "JSON" manually instead of "Text" in the "Content viewer settings" drop-down, every time, on every table.

**Describe the solution you'd like**
Please select the JSON display format in the "Value" panel by default for JSON columns (at least for MySQL databases) in the "Content viewer settings" drop-down.

**Describe alternatives you've considered**
Manually changing the display format in the drop-down every time in the "Content viewer settings" drop-down.

**Comment by uslss** [comment]
thanks for the suggestion.
seems to be related with #10149
