### ISSUE TITLE
Color cell only if cell match text

### ISSUE THREAD

**Issue by lecriquet38** [dbeaver/dbeaver#13251]
**Problem description**
I use the color feature quite often. It works great with cells that are equal to a certain value or cells that fits a range of 2 values.

But if i want to colorize cells that begins with some letters or that contains a number for example, i can not.

**Describe the solution you'd like**
I would like to be able to use the **LIKE** operator :  **LIKE '%my_number_here%'** instead of the equal (=) .
Regex might also be an alternative but not necessary.

Thanks for your help and have a nice day

**Comment by Matvey16** [comment]
We already have this feature. In `Row colors...` menu you can configure a lot of colors including gradient coloring, using different operators e. g. `=, LIKE, REGEX` and other

![mjLFulfmbm](https://user-images.githubusercontent.com/82543000/126168293-9aa67a6e-129b-4b99-bdfd-f70aaa47dc18.gif)

**Comment by lecriquet38** [comment]
I had version 7.2 which does not have this.
I updated to 21.1.3 and now I have it !
Thanks a lot for your answer !
