### ISSUE TITLE
Issue while opening Eclipse with DBeaver Perspective 

### ISSUE THREAD

**Issue by rjbhayani** [dbeaver/dbeaver#13253]
![image](https://user-images.githubusercontent.com/19501487/126164961-56232436-98bb-42bc-b992-46e31974740b.png)

-->

#### System information: 
- Operating system (distribution) and version
- Windows 11
- DBeaver version - Latest
- Additional extensions
- SAP ADT

#### Connection specification:
Not used yet

**Comment by Matvey16** [comment]
@rjbhayani Hello. I see that you are using Windows 11. Does this issue appear only on this OS, or was it also appearing in Win10?
Also looks like it can be an issue with Eclipse. Have you tried creating a Project in Eclipse without DBeaver plugin?

**Comment by rjbhayani** [comment]
Hi Team,
I am not sure since I have not tried in windows 10 but its appearing for Windows 11 and somehow I don't think so its related to windows 11.
Is it not compatible with SAP ADT addins ? 
    On Monday, 19 July, 2021, 07:24:53 pm IST, Matvey16 ***@***.***> wrote:  
 
 


@rjbhayani Hello. I see that you are using Windows 11. Does this issue appear only on this OS, or was it also appearing in Win10?

**Comment by Matvey16** [comment]
@rjbhayani can you attach a .log file? Also what version of eclipse do you use?

**Comment by Matvey16** [comment]
@rjbhayani Have you tried creating a Project in Eclipse without DBeaver plugin? What version of eclipse do you use?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual - feel free to reopen it with additional info
