### ISSUE TITLE
Copying from Results Grid and Pasting into Excel results in multiple columns in one cell

### ISSUE THREAD

**Issue by sars2sars2** [dbeaver/dbeaver#13267]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.1.3.202107181810

#### Connection specification:
- Database name and version Yellowbrick
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When copying the query results from the result grid (Ctrl-A, Ctrl-C), pasting into Excel results in all of the values from a row being put into one cell with a space separating the values. In the past, it would past into individual cells.

#### Steps to reproduce, if exist:
Run a query with multiple columns, select cells (Ctrl-A for all), Copy (Ctrl-C). Open Excel, select a cell, Paste (Ctrl-V)

**Comment by uslss** [comment]
@sars2sars2 unfortunately, cannot reproduce it.
Could you try to Reset UI settings? (Main menu: File - Reset UI Settings)

**Comment by sars2sars2** [comment]
I tried resetting the UI settings as described. I'm still getting the same results.

**Comment by uslss** [comment]
still cannot reproduce an issue. is it still actual against the recent dbeaver version?

**Comment by sars2sars2** [comment]
The issue is now fixed. Not sure what fixed the issue.
