### ISSUE TITLE
Db2 table new property table organization row or column organized.

### ISSUE THREAD

**Issue by gerhard81** [dbeaver/dbeaver#13284]
Hello everybody,

on Table Properties->Statistics there should be added a new property "Table Organization" which indicates if it's a row or column organized table.

The table organization can be found in the catalog view SYSCAT.TABLES.TABLEORG

- C = Column-organized table
- R = Row-organized table

Currently is only possible to determine the kind of organization when look into the DDL.

Regards,
Gerhard

**Comment by tati-kru** [comment]
Thanks for the idea!

**Comment by ShadelessFox** [comment]
Implemented (In general tab, not in statistics):

![java_Ny9oT2B5ad](https://user-images.githubusercontent.com/35821147/143599266-ad11a4ed-aba2-4c92-b4d3-6bb57135c503.png)

**Comment by uslss** [comment]
verified
