### ISSUE TITLE
Constraint generation during DDL as **separate** "ALTER...." statements

### ISSUE THREAD

**Issue by YuriDude** [dbeaver/dbeaver#13287]
**Is your feature request related to a problem? Please describe.**
I would like to have an option that is set as a configuration setting or other global that during the DDL generation of a table **all** constraints are generated as _**separate**_ ALTER statement(s)  and **not** in-line (meaning within "create table ..." statement) as it is current behavior now!

**Rationale**
I think that separate ALTER statement(s) for constraint(s) should in-fact be default behavior and "in-line" should be an option, but I am ok either way.
"THE WHY": during the DB cloning/installation for another environment (test, 2nd/3rd DEV, etc...) having separate DDLs for CREATE & ALTER provide more **flexibility**: tables can be "installed" in **any** order and then constraints can be added/enabled separately. Having constraint(s) in-line , as it is currently, implies that "some" **order must be followed**; e.g. parent table must be "installed"/be present before a child to be implemented. 
 

**Describe alternatives you've considered**
None

**Additional context**
Please also follow this pattern when DLL generated for a **schema**: CREATE TABLE's first , and ALTER on the "bottom".

**Comment by Matvey16** [comment]
@YuriDude DDL generation depends on the database, which one do you have in mind?

**Comment by YuriDude** [comment]
This behavior is the same on Oracle & MS SQL Server currently. 
Suggestion (feature request) is also relevant to these RDBMS'.
I did not check Postgres , MySQL DB2 and other "classical" RDBMS' due to the lack of access, but to my mind - feature should be applicable "across the board": 
- just like you are developing Universal DB Tool -> all shops/enterprises would have almost the same activities related to the Data Sources/Data Stores.

Also, just to clarify:
In original posting I neglected to mention that it related to FK  (foreign key)  constraints - they are the "culprits" ;-) of connections and thus somewhat elevated complexity. All others constraints (PK, not null, check, unique) don't need "special treatment" .

**Comment by Matvey16** [comment]
@YuriDude We will look if it can be implemented

**Comment by gabrielrra** [comment]
![image](https://user-images.githubusercontent.com/39421688/144238943-ae249eab-0d21-4415-915b-1a61306565c3.png)
When generating DLL now the Unique constraint is generated twice.
I can confirm that other constraints such as Foreign Keys, Primary Keys and other non clustered indexes are not duplicated, only Unique Constraints.

**Comment by E1izabeth** [comment]
@gabrielrra, please, specify, which database do you use?

**Comment by Matvey16** [comment]
Verified

Separate ticket opened for duplicate index #15635
