### ISSUE TITLE
DBeaver-CE crashes on Mac OS 12 when trying to change editor fonts

### ISSUE THREAD

**Issue by Sbudaland** [dbeaver/dbeaver#13282]
#### System information: 
- Operating system: Mac OS 12 Beta 3
- DBeaver version:  21.1.2.202107041908
- Additional extensions

#### Describe the problem you're observing:
DBeaver-CE crashes on Mac OS 12 when trying to change editor fonts
#### Steps to reproduce, if exist:
Preferences -> Editors -> Text Editor -> 'Colors and Fonts' -> Text Fonts
#### Include any warning/errors/backtraces from the logs
Dbeaver crashes

**Comment by Matvey16** [comment]
Can you attach a .log file so we can see an error that leads to this crash?

**Comment by Matvey16** [comment]
@Sbudaland Can you attach a .log file so we can see an error that leads to this crash?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual - feel free to reopen it with additional info
