### ISSUE TITLE
Error obtaining geometry type from typmod: fff7f

### ISSUE THREAD

**Issue by gtorinsd** [dbeaver/dbeaver#13283]
Hello Everybody,
I can't view GEOMERTY column in DBeaver (Redshift)
There is a error:

**Error obtaining geometry type from typmod: fff7f** 

OS: Winddows 10
DBeaver v 21.1.3.202107181810, community
Database: Amazon redshift, no ssh, socks etc.

I can select records, view geomerty objects as a line etc, but I can't view the column in columns list,
The same situation was in a previos versions of DBeaver.

![image](https://user-images.githubusercontent.com/11867927/126501514-4bdcc01c-4646-4450-baf2-170dd67dd409.png)
[bak_0.log](https://github.com/dbeaver/dbeaver/files/6856246/bak_0.log)
To reproduce the issue, just open columns list.

Script to create table is:

**drop table public.some_table_name;
CREATE TABLE IF NOT EXISTS public.some_table_name
(
	id BIGINT  DEFAULT "identity"(1285223, 0, ('1,1'::character varying)::text) ENCODE az64
	,field1 GEOMETRY   ENCODE RAW
	,name VARCHAR(150)   ENCODE lzo
	,value DOUBLE PRECISION   ENCODE RAW
	,created_at timestamp default CURRENT_TIMESTAMP
)
DISTSTYLE AUTO
;
ALTER TABLE public.some_table_nameowner to kuku;**

Thanks!
Best wishes,
Torin.

**Comment by ShadelessFox** [comment]
Hello @gtorinsd,

Thanks for the report.

May I ask you to execute following query and provide the result:
```sql
select * from pg_catalog.pg_attribute where attrelid = <table_oid_here>;
```

It does not contain any sensitive data, only metadata. `Object ID` can be found under <kbd>Properties</kbd> tab of the problematic table.

**Comment by ShadelessFox** [comment]
I did some research and it seems that it's invalid value. 

Also, pgAdmin4 was unable to display the value too:

![](https://i.imgur.com/58OcFi9.png)

**Comment by ShadelessFox** [comment]
Hello @gtorinsd,

Is the issue still relevant to you? Please take look at https://github.com/dbeaver/dbeaver/issues/13283#issuecomment-884228194

**Comment by ShadelessFox** [comment]
My guess is that this specific column has type `geometry(geometrycollection)`, but I need more information.

**Comment by deepaksenthilkumar** [comment]
CREATE TABLE test_geom (c1_geometry geometry)

select * from pg_catalog.pg_attribute where attname = 'c1_geometry';

This is the output
{
"select * from pg_catalog.pg_attribute where attname = 'c1_geometry'": [
	{
		"attrelid" : 835925,
		"attname" : "c1_geometry",
		"atttypid" : 3000,
		"attstattarget" : -1,
		"attlen" : -1,
		"attnum" : 1,
		"attndims" : 0,
		"attcacheoff" : -1,
		"atttypmod" : 1048447,
		"attbyval" : false,
		"attstorage" : "x",
		"attalign" : "d",
		"attnotnull" : false,
		"atthasdef" : false,
		"attisdropped" : false,
		"attislocal" : true,
		"attinhcount" : 0,
		"attisdistkey" : false,
		"attispreloaded" : false,
		"attsortkeyord" : 0,
		"attencodingtype" : 128,
		"attencrypttype" : 0
	}
]}

**Comment by ShadelessFox** [comment]
Thanks @deepaksenthilkumar! May I ask you to do the same thing but using following queries:

```sql
CREATE TABLE test_geom (c1_geometry geometry(geometrycollection))
```

```sql
CREATE TABLE test_geom (c1_geometry geometry(geometryzm, 4326))
```

**Comment by deepaksenthilkumar** [comment]
It errors. We can’t specify geometry type in redshift during create

**Comment by ShadelessFox** [comment]
Oh, that's unfortunate. Thanks for the information!

**Comment by uslss** [comment]
verified
