### ISSUE TITLE
filter on NULL and some other value using GUI generates wrong sql code

### ISSUE THREAD

**Issue by JeroenNienhuis** [dbeaver/dbeaver#13295]
#### System information: 
- Operating system (distribution) and version: Windows
- DBeaver version: 21.1.3

#### Describe the problem you're observing:
When filtering on a table using the GUI you can select from all values entered for that field. If NULL and some other values are selected like in
![clip1](https://user-images.githubusercontent.com/51078213/126644434-6cd54478-d70f-4ede-a8ba-ddb7f4c6772d.jpg)
it generates a WHERE clause as
![afbeelding](https://user-images.githubusercontent.com/51078213/126645143-edd28b32-c3e0-47a3-b7d2-fb6f51b57ea6.png)
So far no problem.
After selecting some more fields the new selection is AND-ed to the rest resulting in e.g.:
![afbeelding](https://user-images.githubusercontent.com/51078213/126646181-96a6de4c-5f4d-4146-8b90-2c3b906ad716.png)
This gives wrong results because the selection with the OR should be between parentheses.
The total WHERE clause shoud be 
habitat IN (4,11) AND **(** quality IS NULL OR quality IN (1.0,2.0) **)**

**Comment by Matvey16** [comment]
@JeroenNienhuis Thank you for the report

**Comment by Matvey16** [comment]
Verified
