### ISSUE TITLE
New SQL script template

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#13297]
It is convenient to have a template for new SQL scripts.
It may contain some header with comments, current time, current user name, etc.

**Comment by Matvey16** [comment]
Verified

**Comment by ShadelessFox** [comment]
Template for new SQL scripts can be configured here:

![image-1](https://user-images.githubusercontent.com/35821147/139104560-d3d7a206-75a6-4cde-80eb-ae209a68b60e.png)
