### ISSUE TITLE
Azure SQL certificate issue: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by saumyasuhagiya** [dbeaver/dbeaver#13298]
#### System information: 
- Operating system (distribution) and version : macos big sure (11.4)
- DBeaver version Version 21.1.3.202107181810
- Additional extensions: no extensions

#### Connection specification:
- Database name and version : 
- Driver name : Azure SQL Server
-  mssql-jdbc-9.2.0.jre8.jar
- msal4j:RELEASE:1.9.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  : SSH

#### Describe the problem you're observing:
unable to find valid certification path to requested target

#### Steps to reproduce, if exist:
Add connection details, and click test connection

#### Include any warning/errors/backtraces from the logs

The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:10a9e34e-01c1-4c53-bf49-5bbfdef9c8ca
  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    unable to find valid certification path to requested target
    unable to find valid certification path to requested target

**Comment by Matvey16** [comment]
@saumyasuhagiya Can you please post a screenshot of your connection settings. Particularly Driver properties and SSL tabs.

**Comment by saumyasuhagiya** [comment]
<img width="694" alt="Screenshot 2021-08-05 at 6 34 41 PM" src="https://user-images.githubusercontent.com/2899428/128354639-ee360898-4efc-46d5-ae41-3b95fb5a8ddf.png">

<img width="663" alt="Screenshot 2021-08-05 at 6 29 55 PM" src="https://user-images.githubusercontent.com/2899428/128354397-cd4293f2-d87c-4348-b1a4-3bb6dec79966.png">
<img width="654" alt="Screenshot 2021-08-05 at 6 30 03 PM" src="https://user-images.githubusercontent.com/2899428/128354405-3097b9df-8850-4c7c-a4e9-ede0cfaa4a71.png">

**Comment by Matvey16** [comment]
@saumyasuhagiya Can you try changing trustServerCertificate to true and see if it helps?

**Comment by saumyasuhagiya** [comment]
thanks worked.
