### ISSUE TITLE
Syntax error in DDL when exporting varchar column to MySQL/DB2 form another DB

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13290]
#### System information: 
- DBeaver version 21.1.3

#### Connection specification:
- Database name and version MySQL 5.5/DB2 + PostgreSQL 12

#### Describe the problem you're observing:
Exporting a table from PostgreSQL with a varchar column leads to syntax error because generated DDL reads `CREATE TABLE Table_name ( column1 varchar NULL, column2 numeric NULL)` , but it can't be created without a varchar column length in parenthesis. The same issue with export to DB2

#### Steps to reproduce, if exist:
1. Create a table in PostgreSQL with a varchar column
2. Perform an export to MySQL database with a **create** mapping for this table

**Expected:** Table is exported
**Actual:** Syntax error in DDL

#### Include any warning/errors/backtraces from the logs

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL, column2 numeric NULL`

**Comment by Matvey16** [comment]
Same problem with export to Hive

**Comment by LonwoLonwo** [comment]
Implemented.

Now in the case of table migration from those databases that may have varchar data type without modifiers DBever will choose other data types for long strings. Like `longtext`, `clob` or `string`.

![2022-04-13 13_05_21-Map columns of VARCHAR_COLUMNS](https://user-images.githubusercontent.com/45152336/163155882-d16aff5f-b050-437b-8db8-ab32308f7131.png)

![2022-04-13 13_00_48-Map columns of varchar_columns](https://user-images.githubusercontent.com/45152336/163155879-db40dc5d-592b-408c-bc28-b793af4840e7.png)

Tested on Hive, Oracle, DB2, MySQL, SQLite.

**Comment by Matvey16** [comment]
Verified
