### ISSUE TITLE
Read Data in SQL editor isn't working from context menu in Metadata editor

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#13301]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.1.3

#### Describe the problem you're observing:
1. Open any table in Metadata editor
2. Choose Read data in SQL editor

Actual result:
SQL editor opens, but it is empty.
Expected:
Should working similar to Read data in SQL editor chosen in the context menu in DB navigator

![2021-07-22_21h57_02](https://user-images.githubusercontent.com/31996417/126694283-32811c5e-0928-40d8-bd89-cda50a2b3a38.gif)

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.2.0

**Comment by uslss** [comment]
verified
