### ISSUE TITLE
我的DBearver 的解析执行计划按钮是灰色的 无法使用

### ISSUE THREAD

**Issue by onedriver3** [dbeaver/dbeaver#13304]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by uslss** [comment]
@onedriver3 please add more info about your issue (dbeaver version, database you use, what's going wrong).
Also, please, write in English.
Thanks in advance.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info
