### ISSUE TITLE
Numbers formatting: fractional digits limits don't work

### ISSUE THREAD

**Issue by 2-5** [dbeaver/dbeaver#13309]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.1.3

#### Connection specification:
- Database name and version: PostgreSQL 13.3
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:

There is a regression after upgrading from a previous version. I don't know the exact version, but somewhere in the last 6 months. 

float8 columns are now rounded to just 3 fractional digits, irrespective of Data Formats/Number settings.

The only way to fix this is to "Disable numeric formatting", but that has it's own issues, numbers digits are not grouped, and it renders integral values as 10.0 instead of 10.

Settings on Data Formats page:
- Language: "en - English"
- Country: "US - United States"
- Variant: empty
- Locale: "en_US" (disabled, can't be changed).
- Formats/Numbers: default ones

#### Steps to reproduce, if exist:

Just open a Data editor of a table containing float8 columns which have values with more than 3 decimal digits (0.1234567).

This was reported before in #13131, but that issue is locked so I opened a new one.

**Comment by Matvey16** [comment]
@2-5 Thank you for the report. We will look into it.

**Comment by 2-5** [comment]
Screenshots:

![2021-07-27_140054](https://user-images.githubusercontent.com/3753822/127143595-a3a999e5-4969-4d1d-b08e-b2c5464ba68e.png)

![2021-07-27_140107](https://user-images.githubusercontent.com/3753822/127143616-28581674-a05b-42fc-85db-05e29d967c25.png)

**Comment by 2-5** [comment]
@serge-rider Possible relevant, my Windows regional settings are different from the ones in DBeaver, so maybe DBeaver uses a mix of the two.

![1](https://user-images.githubusercontent.com/3753822/130062454-7bf569d4-9e7c-46fe-a6a9-f6c19d62f361.png)

![2](https://user-images.githubusercontent.com/3753822/130062464-cf8a189b-c32d-4b52-a8b7-df01504c8e06.png)

![3](https://user-images.githubusercontent.com/3753822/130062474-ffa976d7-619b-4c22-bf1f-9418d5681869.png)

**Comment by jayDee-fit** [comment]
I'm having the same issue, but my colleague isn't.  
I'm using Version 21.1.5.202108160727 and he's using Version 7.2.0.202008302047 (unfortunately that's probably not all that helpful, as that's quite a lot of difference in versions).  
It's only in the presentation of the numbers on screen, they show to 3 decimal places even though they're stored to 5 decimal places in the database.  No amount of playing with the formatting settings seems to help. 
This then causes issues when copying and pasting (but not exporting) from the Database.

**Comment by Matvey16** [comment]
I can reproduce it
![Elc0aSEEXm](https://user-images.githubusercontent.com/82543000/130455675-f288770e-265a-4ba6-95a7-b17553138783.gif)

**Comment by LonwoLonwo** [comment]
Fixed for float8, floa4, and for numeric types without parameters.

**Comment by uslss** [comment]
verified
