### ISSUE TITLE
Data grid color does not change after DB (type) change

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#13317]
If you run a query in a "Production" DB (Connection settings, General, Connection Type), the datagrid db color gets red.
Great.
If you change connection (using the toolbar), select a "normal" DB, and execute the query again, the datagrid db color keeps being red.

MacOsX 11.4 (20F71)
DBeaver Version 21.1.2.202107041908

**Comment by wiwwo** [comment]
As a quick note:
* It does work if you start the new connection by selecting the combo box
* It does change if you click on the combo box without changing anything.

Still, by just switching the connection and running the query, the color does not change

**Comment by Matvey16** [comment]
@wiwwo Hello, thank you for the report. Can you clarify what do you mean when saying "changing the connection"
I understood it as picking another connection from this list in a tollbar. Did you mean something else?

![dbeaver_9qANMUKW6s](https://user-images.githubusercontent.com/82543000/127107361-d55d51b3-ba1f-4f9b-8fd2-d6ebb69a3256.png)

**Comment by wiwwo** [comment]
Hi!
Yes, that is what I mean.
Not sure it helps, I am connection to PG DBs.

**Comment by uslss** [comment]
#8081
