### ISSUE TITLE
Double casting when saving custom types through data editor in PostgreSQL

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13315]
As described in issue [#12812](https://github.com/dbeaver/dbeaver/issues/12812#issuecomment-883272630) SQL query preview shows a double cast for custom data types.

**Comment by LonwoLonwo** [comment]
Can't reproduce against DBeaver 23.2.0

![2023-09-12 14_13_33-Window](https://github.com/dbeaver/dbeaver/assets/45152336/2e863f61-4b1c-4fb4-96f7-a7603af84edf)
