### ISSUE TITLE
IBMi DB2 / AS400 - Auto Generated / Auto Increment not correctly showing

### ISSUE THREAD

**Issue by xantari** [dbeaver/dbeaver#13322]
#### System information: 
- Operating system (distribution) and version: 
Windows 10 / 64bit
- DBeaver version: 
21.0.1 and 21.0.2. Also verified issue in 6.0.0
- Additional extensions: 
None

#### Connection specification:
- Database name and version: 
com.ibm.as400.access.AS400JDBCDriver, jt400-10.5.jar (10.5)
- Driver name: 
JT400 / com.ibm.as400.access.AS400JDBCDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?
No

#### Describe the problem you're observing:

When viewing the column properties on the table it is not identifying identity columns on the table properly and showing us they auto-increment.

Example:

![image](https://user-images.githubusercontent.com/6610039/127043463-2994c386-7768-4602-90f4-5d487b2800c8.png)

You can see the fields are not marked as auto incrementing, even though it is an identity column which if I use the native ACS viewer from IBM I see this:

![image](https://user-images.githubusercontent.com/6610039/127043559-5b9f2c8f-9c91-46de-98b8-9e8fefbeee0d.png)

![image](https://user-images.githubusercontent.com/6610039/127043583-4c4995c1-8ad7-46cc-ae85-f90b2d0d9f12.png)

#### Steps to reproduce, if exist:

Double click a table with an identity column in DBeaver to bring up that tables property window.

#### Include any warning/errors/backtraces from the logs

No warnings.

**Comment by LonwoLonwo** [comment]
Hello @xantari 
Please add table DDL info for tests. I can't reproduce it for now for DB2 LUW.

**Comment by xantari** [comment]
This is for DB2 for IBMi, which is a different DB2 dialect then LUW and uses a different JDBC driver then the LUW version.

Here is the DDL:

```sql
CREATE TABLE ARRTFLIB.CEACTIVITYAPIUSERS FOR SYSTEM NAME CEACTAPIU ( 
	IDSPROVIDERID FOR COLUMN IDSPROID   INTEGER GENERATED ALWAYS AS IDENTITY ( 
	START WITH 1 INCREMENT BY 1 
	NO MINVALUE NO MAXVALUE 
	NO CYCLE NO ORDER 
	NO CACHE ) 
	, 
	CLIENTID VARCHAR(200) CCSID 37 NOT NULL , 
	ALLSPONSORACCESS FOR COLUMN ALLSPAXS   SMALLINT NOT NULL DEFAULT 0 , 
	CONSTRAINT ARRTFLIB.Q_ARRTFLIB_CEACTAPIU_IDSPROID_00001 PRIMARY KEY( IDSPROVIDERID ) )   
	  
	RCDFMT CEACTAPIU  ; 
  
LABEL ON TABLE ARRTFLIB.CEACTIVITYAPIUSERS 
	IS '-CEACTIVITYAPIUSERS' ; 
  
LABEL ON COLUMN ARRTFLIB.CEACTIVITYAPIUSERS 
( IDSPROVIDERID TEXT IS 'Identity Server PoviderID' , 
	CLIENTID TEXT IS 'Client ID' , 
	ALLSPONSORACCESS TEXT IS 'All sponsor access flag' ) ;
```

**Comment by LonwoLonwo** [comment]
Ok, thanks for the bug report.

For AS400 DBeaver shows only what the driver gives. So maybe this is a driver issue.  
We don't have a DB2 AS400 test environment for testing, unfortunately. Therefore we can't fix it now. Maybe someday.

**Comment by Matvey16** [comment]
@xantari This driver can be very sensitive to it's properties and changing their default values can fix some issues for some people, but break something for others. So my advice to you for now is to try carefully tweaking them (or first looking in the [documentation](https://www.ibm.com/docs/en/i/7.3?topic=ssw_ibm_i_73/rzahh/javadoc/com/ibm/as400/access/doc-files/JDBCProperties.html) for a needed property) to test if it can be changed

**Comment by xantari** [comment]
@Matvey16 Thanks, I did some experimentation and found a result that does show the auto increment properties properly. But then it messes up the column retrieval information.

Here is what I had:
1. metadata source: 0
2. translate binary: true
3. date format: iso
4. time format: iso
5. extended metadata: false

With the above settings you get the column names in addition to the column text underneath the column as follows when you do a select * from table:

![image](https://user-images.githubusercontent.com/6610039/127163471-3a110122-92c9-43d3-bedc-6dca078c52ba.png)

To fix the identity column information issue I then changed it to the following:

1. metadata source: 1
2. translate binary: true
3. date format: iso
4. time format: iso
5. extended metadata: true

So lines 1 and 5 above were changed. You can not leave metadata source: 0 and just leave "extended metadata" to true. As that still doesn't allow you to view the identity column information, even though the documentation says it should.

The problem now though, is with 1 and 5 above changed I now get this when viewing that same table as above:

![image](https://user-images.githubusercontent.com/6610039/127163851-f1e4af47-50e3-4a0e-aded-196357d958d3.png)

As you can see in the above image, though I've fixed the issue with the identity column property info now being displayed in DBeaver, I have completely lost the column names on the result sets.

I think I might need an elder wand to find out the magic set of property combinations to get the auto increment properties to display AND show the column name along with the column text below the column name.

UPDATE:

I tried some more and this variation doesn't show the column text at all, but does restore the visibility of the column name:

1. metadata source: 1
2. translate binary: true
3. date format: iso
4. time format: iso
5. extended metadata: false

![image](https://user-images.githubusercontent.com/6610039/127164557-ff16dc4f-3dc0-44f5-b831-4243855e915e.png)

The property changed was line 5. Interestingly the auto increment properties are still displayed properly with "extended metadata" to false, even though the documentation that was linked says it shouldn't return autoincrement information when it is false.

**Comment by xantari** [comment]
So a bit more experimentation.  

Used the following driver properties:

metadata source: 1
translate binary: true
date format: iso
time format: iso
extended metadata: true

When I have this unmarked:

![image](https://user-images.githubusercontent.com/6610039/127168527-361c6e8e-b3d9-4205-b22d-685a480d7051.png)

I get this:

![image](https://user-images.githubusercontent.com/6610039/127168448-40f38c86-ff0a-4dff-bc02-9205279aa428.png)

When marking it:

![image](https://user-images.githubusercontent.com/6610039/127168575-70b2a8b4-594d-4b87-84c0-767ece1aa135.png)

I get the column names back:

![image](https://user-images.githubusercontent.com/6610039/127168610-81c8f582-dfbe-49c2-aec2-2c8085d55039.png)

Now, I figured how do I get the column headers back. And I noticed this property in DBeavber:

![image](https://user-images.githubusercontent.com/6610039/127168720-cc115182-bfbe-4f6e-9833-820e5a74d827.png)

It was already marked. and should show the column description/labels in the header right? Kinda wondering if this is now a DBeaver bug.

**Comment by xantari** [comment]
Closing this in favor of #13335 since the original issue this report is about is fixed, but a separate issue has now cropped up.

**Comment by bdietz400** [comment]
> Ok, thanks for the bug report.
> 
> For AS400 DBeaver shows only what the driver gives. So maybe this is a driver issue.
> We don't have a DB2 AS400 test environment for testing, unfortunately. Therefore we can't fix it now. Maybe someday.

You may be able to get a free IBM i account at https://pub400.com/.
