### ISSUE TITLE
Truncate option tool for table in context menu for Exasol

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13325]
We need to add a truncate option for tools in context menu. Right now it is missing for Exasol connections.

**Comment by LonwoLonwo** [comment]
Implemented in DBeaver 21.2.4

![137303952-ff8c238f-1416-4b68-984d-6a859b868ba2](https://user-images.githubusercontent.com/45152336/137693178-10ab1d5f-e96c-4cbd-9f08-8377c5f4064d.png)

![137303954-3a9221b5-9755-4069-9fb9-85e86b335bea](https://user-images.githubusercontent.com/45152336/137693182-16644f23-5b7f-4fc0-89a2-f8b263b94cea.png)

![137303957-fbb99926-2488-4b8c-9c18-d396b312e9bd](https://user-images.githubusercontent.com/45152336/137693184-c6a92481-b850-497a-83c1-5b7592817321.png)

![137303958-12644d3d-2c43-4ab8-9692-76bc15a06542](https://user-images.githubusercontent.com/45152336/137693185-047cce4e-a36f-45cb-815a-aec7e26e795a.png)

**Comment by Matvey16** [comment]
Verified
