### ISSUE TITLE
"Execute SQL Statement" on vertical/block selected text executes code outside the selection

### ISSUE THREAD

**Issue by jetzerb** [dbeaver/dbeaver#13339]
#### System information: 
- Windows 10
- DBeaver 21.1.3
- No additional extensions

#### Connection specification:
- N/A

#### Describe the problem you're observing:
When I make a vertical/columnar/block selection in the SQL Editor (via `Ctrl+Shift+A`), and then "Execute SQL Statement" (via `Ctrl+Enter`) to execute that block of text, DBeaver fails to exclude text outside the selected region except to the left of the top line and the right of the bottom line.  It _should_ only execute the SQL statements within the selected area.

#### Steps to reproduce, if exist:
```sql
select * from (values (1),(2)) t(val)     where t.val < 2
union
select * from (values (3),(4)) t(val)     where t.val < 4
union
select * from (values (5),(6)) t(val)     where t.val < 6
-- select a block from start to here --
-- (without the where clauses)       --
```
I would expect the result set to be all values from 1-6.  However, it actually includes the where clauses from the first two queries, and does not return the values 2 and 4.

![image](https://user-images.githubusercontent.com/36859020/127204104-bf6ace65-2d6d-49a1-be47-c1e379a62f38.png)

A few more illustrations using the following as the base text:
```sql
Line1front excluded     select * from (values (1),(2)) t(val)     where t.val < 2  Line1back included
Line2front included     union
Line3front included     select * from (values (3),(4)) t(val)     where t.val < 4  Line3back included
Line4front included     union
Line5front included     select * from (values (5),(6)) t(val)                      Line5back excluded
```
![image](https://user-images.githubusercontent.com/36859020/127207313-7f7edf83-3ba6-4377-949f-569a278cbaed.png)

![image](https://user-images.githubusercontent.com/36859020/127207425-106748fa-7cfe-41c8-a479-8e57e9aadbf6.png)

![image](https://user-images.githubusercontent.com/36859020/127207612-c1024a7e-769b-4058-b5df-1ef3f719426c.png)

![image](https://user-images.githubusercontent.com/36859020/127207800-42236473-a1e8-4ada-8a14-86f896a5e69f.png)

**Comment by Matvey16** [comment]
@jetzerb Hello, thank you for the report.

**Comment by Matvey16** [comment]
Verified
