### ISSUE TITLE
Error "Invalid method name: 'OpenSession' " when connecting to HIVE

### ISSUE THREAD

**Issue by VladimirVarnakov** [dbeaver/dbeaver#13334]
Error "Invalid method name: 'OpenSession' " when connecting to HIVE(impala) server.
Automatically downloaded driver is used for the connection. Also, I tried to use a standalone apache hive driver 3.1.2 but had the same error.
![image](https://user-images.githubusercontent.com/18036078/127176326-024ef724-90ff-4c98-8d1f-4bd7fc8c3ba1.png)
Connection settings:
![image](https://user-images.githubusercontent.com/18036078/127174309-26a426a3-6ab5-495c-8b0a-2e2d073cd571.png)
properties:
![image](https://user-images.githubusercontent.com/18036078/127174417-4e2544a8-3c1a-4734-b0d0-d3bb0f51e285.png)
Driver settings:
![image](https://user-images.githubusercontent.com/18036078/127174495-c5481ed8-3602-4642-b554-54cabeeee0eb.png)
![image](https://user-images.githubusercontent.com/18036078/127174752-4dce68a5-42d4-44b5-8e84-d87433670471.png)

**Comment by Matvey16** [comment]
@VladimirVarnakov Hello, can you post an error log?

**Comment by VladimirVarnakov** [comment]
Hi @Matvey16, the logs are attached here.
[dbeaver_logs_1.zip](https://github.com/dbeaver/dbeaver/files/6915596/dbeaver_logs_1.zip)

**Comment by Matvey16** [comment]
@VladimirVarnakov Have you tried using Impala jdbc driver? Because it looks like the Hive driver is not suitable for your database.

**Comment by VladimirVarnakov** [comment]
Hi @Matvey16, I have successfully connected to this database by other applications with apache hive driver(default driver for this DB) and hive-jdbc-uber. But our test app was fixed by developers due to the same error as described in this issue. So these jdbc drivers are suitable for this DB.

**Comment by Matvey16** [comment]
@VladimirVarnakov Thank you for the report. We will look into it

**Comment by Matvey16** [comment]
@VladimirVarnakov Can you try renaming the property `auth` to `authMode`

**Comment by uslss** [comment]
There has been no update on the issue for a long time. if it is still actual - feel free to reopen it
