### ISSUE TITLE
Crash when entering multibyte numbers into the query editor.

### ISSUE THREAD

**Issue by sumibio** [dbeaver/dbeaver#13343]
If you enter characters such as "０" and "１", it will crash, so I will report it.

- Operating system (distribution) and version
macOS Big Sur 11.5
- DBeaver version
21.1.3

DBeaver 21.0.0 doesn't seem to have any issues

Google Translate.

**Comment by uslss** [comment]
@mizukamiyuta what database do you use? please provide query you use. Table DDL also will be helpful

**Comment by sumibio** [comment]
@uslss 
The database mainly uses Postgresql and Redshift, but I think it happens regardless of this.
The application freezes the moment you enter "０" in the editor.
I think it can be reproduced by copying and pasting.

**Comment by Matvey16** [comment]
@mizukamiyuta thank you for the report. I preproduced it in the latest version.

**Comment by Matvey16** [comment]
@mizukamiyuta Can you add what encoding is used for this characters

**Comment by sumibio** [comment]
@Matvey16 
UTF8 in my settings.

**Comment by ShadelessFox** [comment]
Fixed. The bug was caused by non-ASCII digits that were treated as valid input. We restricted number highlighting just for ASCII 0-9 characters.

Testers, please see https://github.com/dbeaver/dbeaver/issues/11104#issuecomment-790755537 for other test cases

**Comment by Matvey16** [comment]
Verified
