### ISSUE TITLE
NULL fields in varchar or text sub columns of composite types are shown as empty strings

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13349]
#### System information: 
- Operating system (distribution) and version Win 10
- DBeaver version 21.1.4

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:

```sql

--Create a composite data type
CREATE TYPE zzz AS (
	id int4,
	"name" text);

--create a table with that data type
CREATE TABLE aaa (
	id numeric NULL,
	composite zzz NULL,
	CONSTRAINT aaa_pk PRIMARY KEY (id)
);

--fill the data
INSERT INTO aaa (id,composite)
	VALUES (1, (20, NULL)),
	(2, (30, 'John')),
	(3, (40, NULL)),
	(4, (50, 'Jack'));

-- look at the result
SELECT * FROM aaa;

```
**Expected:** NULLs in empty fields
**Actual:** Empty Strings in empty fields

![dbeaver_hHmbtEYXLP](https://user-images.githubusercontent.com/82543000/127319564-d651ddd5-cb4c-47b0-a10f-6d71a83a844a.png)

**Comment by ShadelessFox** [comment]
https://www.postgresql.org/docs/current/rowtypes.html#id-1.5.7.24.6

**Comment by ShadelessFox** [comment]
Depends on #13352

**Comment by ShadelessFox** [comment]
We need to update our CSV library.

**Comment by Matvey16** [comment]
Verified
