### ISSUE TITLE
In data-grid: copy value from cell above

### ISSUE THREAD

**Issue by JeroenNienhuis** [dbeaver/dbeaver#13347]
When editing data in a grid, it would be handy if it is possible to copy the value from the cell above (e.g. like Ctrl-D in some spreadsheets). 
The alternative is moving cursor and use Ctrl-C and Ctrl-V (4 keystrokes instead of 1)

**Comment by ShadelessFox** [comment]
Implemented:

https://user-images.githubusercontent.com/35821147/138078009-440beeb0-d931-48ad-adce-d13d3a864fe8.mp4

**Comment by JeroenNienhuis** [comment]
Thanks for improving, but this was nog what I asked. The new feature copies data from an entire line and not just the single cell above (or below).
The request was for editing something like this:
![afbeelding](https://user-images.githubusercontent.com/51078213/138075753-f5b2ad0e-5ae3-4bf0-b543-c8130b6d1de3.png)
![afbeelding](https://user-images.githubusercontent.com/51078213/138075797-47958aa3-ab49-49db-8fe0-b9ddda39cf42.png)
(just like e.g. Ctrl-D in spreadsheets)

**Comment by ShadelessFox** [comment]
Please watch attached video - it copies values in selected columns.

Update: I've updated attached video since it was outdated.

**Comment by JeroenNienhuis** [comment]
Sorry, I did whatch the outdated video that I received by email about an hour ago sent by GitHub. I assumed this was the same one as the current video.
Thanks for improving.

**Comment by uslss** [comment]
verified
