### ISSUE TITLE
A display issue with the character "{". 

### ISSUE THREAD

**Issue by Rangorca** [dbeaver/dbeaver#13357]
There is a display issue with the character "{". 

Please see 
select regexp_split_to_array('ab,c', ',')
![image](https://user-images.githubusercontent.com/25958217/127467328-36d517a7-eb00-4bb0-b2f6-6a8897892ae4.png)

select regexp_split_to_array('a{b,c', ',')
![image](https://user-images.githubusercontent.com/25958217/127467267-bbf009ed-b5bd-4d45-8b51-58edfebc3068.png)
The array shows that it will have an extra dimension, but it doesn't.

**Comment by uslss** [comment]
thank you for the report

**Comment by Matvey16** [comment]
Verified
