### ISSUE TITLE
[CLARIFICATION] PG locked with only selects executed

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#13355]
Opening a PG connection (NO autocommit, read committed mode) and just issuing a select locks a DDL in a psql session.
Maybe not  bug, but for sure a very strong behavior.

Also, and I highlighted this before, setting a connection to "Development" database, which implies "AUTO-COMMIT" (it is set so, no custom change), still connects with manual commit/read committed (in the combo box).

What am I doing wrong?

**Comment by wiwwo** [comment]
Correction.
Isolation level is taken by "How you set it last time", which is even more confusing since If I work on DEV DB, than close DBeaver, than open it again and work on prod, if I don't remember to switch i am in autocommit mode. Disaster...

**Comment by Matvey16** [comment]
@wiwwo I'm not sure I understood the situation with switching from dev to prod connection. Am I doing something differently in my example? Isolation level is supposed to depend on connection type by default.

![pUE2akcYql](https://user-images.githubusercontent.com/82543000/127832678-ea19051a-1df1-4963-b479-b59d5cf7b6b8.gif)

**Comment by wiwwo** [comment]
@Matvey16 I might have done something wrong there. So, problem like "Wrong isolation level at startup" might be something stupid I did.

Still, opening a connection with DBeaver blocks DDL (drop table etc), which is the bigger problem 9and the subject of this ticket, sorry for confusion... I might need vacation :D )

**Comment by Matvey16** [comment]
@wiwwo Yeah, it looks like an expected behavior, you have a pending transaction, so it locks the table, it is expected when using manual commit mode.
