### ISSUE TITLE
[Enhancement] Code editor extra tab space when performing reverse tabs to text selection

### ISSUE THREAD

**Issue by yevon** [dbeaver/dbeaver#1336]
When you perform inverse tab (shift + tab) to a text selection, when one of the lines is not aligned with others, it keeps their initial spacing even when you continue pressing (shift + tab).

See line 504:
Current result:
![image](https://cloud.githubusercontent.com/assets/121157/23251282/08e06aa4-f9ad-11e6-85b8-c3cb74b54c24.png)

It would be nice to align all text to left margin after you continue performing tabs to text selection, erasing initial spacing of lines:

![image](https://cloud.githubusercontent.com/assets/121157/23251414/7d33b9c4-f9ad-11e6-9ee9-e3342c2f8d78.png)

**Comment by uslss** [comment]
Already implemented
