### ISSUE TITLE
Fetch limit not used for Databricks (simba-spark driver)

### ISSUE THREAD

**Issue by abij** [dbeaver/dbeaver#13374]
#### System information: 
- Windows 10
- DBeaver CE 21.1.3
- [Databricks driver](https://docs.microsoft.com/en-us/azure/databricks/dev-tools/dbeaver)

#### Connection specification:
- Databricks Cluster (Runtime 8.4)
- New driver added: Databricks. Tried 2 driver types: Generic/Hive
- No tunnels / proxies

#### Describe the problem you're observing:

The Fetch Size limit is not used (appended to the query) when using the Data Editor for this (custom) Driver. Filters and order by are added the the queries.
The problem is that the complete dataset is downloaded to the client, for large tables this exceeding the limit (4Gb) and fails.

![image](https://user-images.githubusercontent.com/1022013/127617546-630adb9f-2957-4bc1-8b67-acf6f9c1b455.png)

The Query Manager shows that the select * is send to Spark.

Note: 
- Red is databricks using the Databricks driver (simba-spark) (Both Generic and Hive driver-type)
- Yellow is a complete different connection using Hive (jdbc:hive2://some-hdinsight-cluster:10000), this is working as intended

![image](https://user-images.githubusercontent.com/1022013/127621737-2c8d6a9e-ef5c-416b-a4f8-aeb88fbb2117.png)

#### Steps to reproduce, if exist:

Follow the guide to setup Databricks connection, create a table with

**Comment by abij** [comment]
I noticed a difference between Hive SQL and Spark SQL:
- Hive has limit, offset: https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Select#LanguageManualSelect-LIMITClause
- Spark only has limit: https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select.html
  - Suggestions & PRs are made to add offset feature: https://issues.apache.org/jira/browse/SPARK-28330 but it;s suspended for now

So, paging through resultset is a bit different, at least limit should be added to queries

**Comment by LonwoLonwo** [comment]
Hello @abij 

You can return the fetch size limit in the Driver Settings.

![2021-11-01 13_37_39-DBeaver Ultimate 21 2 4 - _postgres_ Script-8](https://user-images.githubusercontent.com/45152336/139659312-3a33bdde-2a4b-4453-8442-df223cf71f8f.png)

![2021-11-01 12_28_48-Edit Driver 'Apache Hive'](https://user-images.githubusercontent.com/45152336/139659327-0bf282fc-c858-40e1-8d17-4a33f40a5a32.png)

The "Driver supports result set limit" setting is disabled by default for Hive.

I hope, it will help!

**Comment by abij** [comment]
I tried with and without, no luck.
Note it's not Hive but Spark: **jdbc:spark://**

![image](https://user-images.githubusercontent.com/1022013/139702022-8a458cdc-c661-4f65-946b-a8db159c232e.png)

**Comment by LonwoLonwo** [comment]
Hmm...
Unfortunately, we do not have a test environment. 
Can you please check the [Error logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info

**Comment by stegus64** [comment]
I have exactly the same problem. I am using DBeaver 21.3.3

Please note that it is very easy to create a free test environment in Azure Databricks: https://azure.microsoft.com/en-us/free/

There are no entries in the DBEaver error logs.

**Comment by abij** [comment]
Nice, I'm not alone! 
@LonwoLonwo I can show you the setting and the problem in a short session.

Do you think it's required to implement a custom implementation for Spark like Hive?

And add things like this:
https://github.com/dbeaver/dbeaver/blob/5ef67b3ecb8420dafef78caad4929a40b19014ba/plugins/org.jkiss.dbeaver.ext.hive/src/org/jkiss/dbeaver/ext/hive/model/HiveDataSource.java#L76:

Minimal implementation is already a lot of work. I tried to setup the development environment (for Eclipse extensions) but it's not so straight forward.

**Comment by E1izabeth** [comment]
Hi, @abij! Maybe one of our wiki pages about setting up [Eclipse](https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse) or [IDEA](https://github.com/dbeaver/dbeaver/wiki/Develop-in-IDEA) development environment will help you.

**Comment by LonwoLonwo** [comment]
Databricks driver added to the driver's list. Along with the ability to use the setting "Use SQL to limit fetch size" (Preferences -> Editors -> Data Editor). The enhancement will available in DBeaver version 22.0.2

![2022-03-24 10_58_06-DBeaver Ultimate 22 0 1 - _postgres 13 3_Script-81](https://user-images.githubusercontent.com/45152336/159946700-655142b2-6128-41b3-8df7-aadea9a3679d.png)

![2022-03-24 11_27_25-DBeaver Ultimate 22 0 1 - _postgres_ Script-10](https://user-images.githubusercontent.com/45152336/159946728-a02ba9ac-bf11-44d4-a095-d217166a0b4f.png)

![2022-03-23 13_11_20-Connect to a database](https://user-images.githubusercontent.com/45152336/159946762-db359c67-c5e4-4268-b75a-44b1a3418b37.png)

![2022-03-24 12_43_32-DBeaver Ultimate 22 0 1 - trips](https://user-images.githubusercontent.com/45152336/159946820-7f5c73e5-2056-467d-b6e3-08bbb06fc7cc.png)
