### ISSUE TITLE
Wrong formatting for CASE WHEN statement

### ISSUE THREAD

**Issue by qiqingli** [dbeaver/dbeaver#13375]
#### System information: 
- Operating system (distribution) and version：macOS Big Sur 11.5
- DBeaver version: 21.1.3

#### Connection specification:
- Database name and version: MySQL 5.7.36
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/20805098/127627974-96e8c55f-eaf0-43aa-8ba0-d9dabc364855.png)

**Comment by uslss** [comment]
@qiqingli could you provide an example how it should look like in your opinion? thanks in advance

**Comment by qiqingli** [comment]
I think it should be formatted like this.
![image](https://user-images.githubusercontent.com/20805098/127831265-3c1e8dca-686b-4de9-9a70-98473199a869.png)

**Comment by qiqingli** [comment]
@uslss After upgrading to 21.1.4, the formatting style is a bit odd

![image](https://user-images.githubusercontent.com/20805098/128151100-7ee4b724-c873-4f76-ab99-e38c042e3e28.png)

**Comment by LonwoLonwo** [comment]
Hello @qiqingli 
Thanks for the bug report!

**Comment by LonwoLonwo** [comment]
Better CASE/END block formatting added. With the function inside this block.
Also, 'REPLACE' was added to the MySQL functions list.

**Comment by Matvey16** [comment]
Verified
