### ISSUE TITLE
triggers not shown in view explorer

### ISSUE THREAD

**Issue by tatod** [dbeaver/dbeaver#13379]
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04.2 LTS
- DBeaver version: Version 21.1.3.202107181810
- Additional extensions : n/a

#### Connection specification:
- Database name and version: Oracle Oracle Database 12c EE Extreme Perf Release 12.1.0.2.0 - 64bit Production
- Driver name: Oracle JDBC driver 19.6.0.0.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : n/a

#### Describe the problem you're observing:
when there is view on which there triggers exists then this trigger is shown in dependencies but not in triggers for that table. Table and triggers are each of different owner: for example view FND_FLEX_VALUES_TL# is in APPLSYS and its trigger XXGL_COA_AUDIT_TRG_02 is in APPS. Screenshots attached. I am using APPS user to login to database.

#### Steps to reproduce, if exist:
- login with one db user which has rights to see and alter any DB object
- filter view in corresponding schema with trigger which is owner by other DB user
- trigger not shown in triggers but it is visible in dependancies
![2021-07-30_14-46_1](https://user-images.githubusercontent.com/48986378/127655269-424578ae-70ad-4ab1-b544-71891c957df9.png)
![2021-07-30_14-46](https://user-images.githubusercontent.com/48986378/127655273-f323574b-3507-4802-9bc0-4f027579014d.png)

**Comment by LonwoLonwo** [comment]
Thanks for the bug report!

**Comment by LonwoLonwo** [comment]
Support of view triggers for Oracle implemented in DBeaver 21.1.5

**Comment by Matvey16** [comment]
Verified
