### ISSUE TITLE
Unable to log into snowflake on version 21.1.3 with AD group with spaces

### ISSUE THREAD

**Issue by KramericaInc** [dbeaver/dbeaver#13384]
#### System information: 
- Operating system (distribution) and version
- DBeaver version" 21.1.3
- Additional extensions

#### Connection specification:
- Database name and version:   Snowflake 
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Unable to log into snowflake using and AD group with spaces. It worked in previous versions with quotes but not it no longer works. We get Null connection returned when we attempt to connect with it.

#### Steps to reproduce, if exist:

Create a connection to snowflake and enter an active directory group with spaced in it.

**Comment by uslss** [comment]
@KramericaInc unfortunately, we've got no environment to test it. Could you provide [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual - feel free to reopen it with additional info that will help to reproduce an issue
