### ISSUE TITLE
Default fields a shown as NULL until manual refresh

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13382]
#### System information: 
- Operating system (distribution) and version WIn10
- DBeaver version 21.1.4

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
If a column has default value, inserting new row in data grid shows that field as NULL until the grid is refreshed manually.

#### Steps to reproduce, if exist:
1. Create a table with a column that has a default value
2. Insert new row in data grid
3. Save changes

**Expected:** Defauld value is shown in the new field
**Actual:** NULL is shown

![Jz1eLQDnSH](https://user-images.githubusercontent.com/82543000/127677223-114036ba-414a-4efb-a472-679b389d40c2.gif)

**Comment by ShadelessFox** [comment]
We refresh only inserted columns by performing query with primary keys as a constraint for optimization purposes.

We can't do the same with default values, since they are expressions and thus may contain function calls and other things that have **side-effects**. Nobody expects DBeaver to launch a rocket upon inserting a new row.

The easiest solution in this situation would be to detect whether the default value is a function call or a simple expression.

**Comment by LonwoLonwo** [comment]
We can't do it for tables without keys. 

It works fine for tables with PK.
![V2oCfXnXJ8](https://user-images.githubusercontent.com/45152336/129565313-e10429b4-bf60-46d1-b383-f5eb9d7b176e.gif)

**Comment by p91paul** [comment]
did you try using jdbc getGeneratedKeys to get values after insert? https://stackoverflow.com/questions/13205031/jdbc-getgeneratedkeys
You should be able to specify which columns you want to get back. It might not work for all drivers, but in theory it's more reliable than a subsequent select by primary key. I use it to get columns generated by triggers on Oracle.

**Comment by LonwoLonwo** [comment]
Yep, we use getGeneratedKeys already, thanks. And it works fine. But the table from the topic example has no keys at all. 
So I was not entirely correct was in my statement. Not only a PK can be used for the refresh, of course.

**Comment by p91paul** [comment]
If I understand correctly, you use getGeneratedKeys to get the value of ID and then a primary key select to get Column3, is that right?
What I'm telling is that some jdbc drivers might return Column3 value as well with getGeneratedKeys, if you ask them to. So for those drivers you are fine even without primary key, and the primary key refresh can be used as a fallback only for others.
