### ISSUE TITLE
Incorrect precision for number type is set in case of export to new table

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#13389]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.1.4

#### Connection specification:
- Database name and version Snowflake
#### Describe the problem you're observing:
Incorrect precision (100) for number type is set in case of export to new table. So data transfer cannot be performed due to error.
![image](https://user-images.githubusercontent.com/31996417/127775577-6de03362-1961-4316-bdd7-920b4bf2d5f4.png)

#### Steps to reproduce, if exist:
1. Start table export to db (table should contain numeric columns)
2. Perform export to the new table and check generated ddl - precision for numeric type is automatically set to 100.

**Comment by LonwoLonwo** [comment]
NUMBER type returned to Snowflake and NUMERIC type returned to Netezza. It will help with data types mapping.

**Comment by uslss** [comment]
verified
