### ISSUE TITLE
Data Formats: Verify its properties before saving

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#13380]
We should verify properties of data formatter before allowing to save it, otherwise it may lead to some unexpected errors.

#### Steps to reproduce, if exist:
1. Go to <kbd>Preferences</kbd> &rArr; <kbd>Editors</kbd> &rArr; <kbd>Data Editor</kbd> &rArr; <kbd>Data Formats</kbd>
2. Choose  <kbd>Timestamp</kbd>
3. Try changing <kbd>Timezone</kbd> property to some invalid value

**Expected**:
Some kind of dialog pops up telling us that we made an error, then reverts changes made to the edited property

**Actual**:
An error is shown in <kbd>Error Log</kbd>

**Comment by DariaMarkaryan** [comment]
Verified
