### ISSUE TITLE
Save button is missing for execution plan in Exasol connection

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13394]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.4

#### Connection specification:
- Database name and version: Exasol

#### Steps to reproduce, if exist:
1. Open execution plan for a query
2. Try to save it

**Expected:** Save button is present
**Actual:** Save button is missing.

![dbeaver_y3yEDh7JCj](https://user-images.githubusercontent.com/82543000/127813169-2bdc2710-8fc5-48c6-b989-854f11f116b4.png)

**Comment by LonwoLonwo** [comment]
![2022-01-18 22_43_41-DBeaver Ultimate 21 3 3 - _db2 dev dbeaver com_Script-110](https://user-images.githubusercontent.com/45152336/150009392-61069307-17c0-4035-ae6d-55b17861a022.png)

![2022-01-18 22_57_57-DBeaver Ultimate 21 3 3 - exaPlan2 dbplan](https://user-images.githubusercontent.com/45152336/150009674-5b45dcc5-020b-422c-8131-5d2a60e23150.png)

Ability to save and load execution plan added for the Exasol database.

**Comment by Matvey16** [comment]
Verified
