### ISSUE TITLE
MSSQL Stored procedure can't view result set

### ISSUE THREAD

**Issue by leezm** [dbeaver/dbeaver#13391]
#### System information: 
- win10
-21.1.4.202107231409
- Additional extensions

#### Connection specification:
- MSSQL2014
- JDBC&JTDS
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Include any warning/errors/backtraces from the logs
Stored procedure Return result set,but can't view it in this version.It's just return a query message......

**Comment by uslss** [comment]
@leezm could you provide a procedure example to reproduce an issue?

**Comment by leezm** [comment]
> @leezm could you provide a procedure example to reproduce an issue?

In old version it's OK...

example: "......select @SQL......" just use select sql syntax at sp end to return record set in MSSQL

**Comment by ShadelessFox** [comment]
Hello @leezm,

Please provide a complete example, so we can be sure that the issue can be reproduced on both sides.

**Comment by leezm** [comment]
> Hello @leezm,
> 
> Please provide a complete example, so we can be sure that the issue can be reproduced on both sides.

I can't provide the Production environment content to you...
![1](https://user-images.githubusercontent.com/24444492/127831420-fa5c3f58-ffe0-4251-90ad-4a3e23eed111.png)
It's just return this message in this pic...
Maybe it's a feature...

**Comment by ShadelessFox** [comment]
You can create your own reproducible example.

**Comment by leezm** [comment]
> You can create your own reproducible example.

Unfortunately, this SP is very complicated. The cursor loop was used to piece together SQL, and finally executed.
I can't reproduce it in a simple environment，because I tried simple cases are all successful...

**Comment by uslss** [comment]
@leezm is it still actual for you?
unfortunately, the issue cannot be fixed if it isn't reproducible

**Comment by leezm** [comment]
> @leezm is it still actual for you?
> unfortunately, the issue cannot be fixed if it isn't reproducible

YES,other SP is OK...I think something went wrong in the SP then return -1,but in other tools it's can return record set...Maybe ignore wrong in this sp can return record set...

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info
