### ISSUE TITLE
Oracle DBMS_OUTPUT not always shows the printed messages

### ISSUE THREAD

**Issue by RamonCar66** [dbeaver/dbeaver#13390]
#### System information: 
- Windows 10
- DBeaver 21.1.3
- Additional extensions

#### Connection specification:
- Database name and version
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
PL/SQL Release 11.2.0.4.0 - Production
"CORE	11.2.0.4.0	Production"
TNS for Linux: Version 11.2.0.4.0 - Production
NLSRTL Version 11.2.0.4.0 - Production

- Driver name : oracle.jdbc.OracleDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? --> NO

#### Describe the problem you're observing:
Afte upgrading to version 21.1.3, the Output log does not always show the printed messages from the execution of the stored procedures. The procedure is executed, because the expected effects are reflected on the tables, but the DBMS_OUTPUT.PUT_LINE messages are not shown in the Output log.

Hint: Normally, when this happens, if you perform Invalidate/Reconnect on the DB connection, it restart to work again... but you've lost the trace from the previous execution...

#### Steps to reproduce, if exist:
begin
	DBMS_OUTPUT.PUT_LINE('Test');
end;

**Comment by uslss** [comment]
@RamonCar66 , cannot reproduce it against 21.1.4.
![image](https://user-images.githubusercontent.com/31996417/127827989-3443a51c-e247-4aa2-84bb-ad0bf8f0b652.png)
Could you check if it is reproducible for you against the recent version?

**Comment by RamonCar66** [comment]
Thanks for the quick response,
I see today has released version 21.1.4, I will retest as soon as I install
it.

Kind regards
--------------------------------------------------------
Carlos RAMON
Mov: +34.649.53.06.19
***@***.***
--------------------------------------------------------

**Comment by RamonCar66** [comment]
Hello,
After upgrading to 21.1.4, **the issue persists**.

It does not happens always, you're working for a while, and a given point in time you call a PL/SQL and do not see the expected trace. Then, if you invalidate / reconnect, it starts to work again. 

I did not notice this problem in version 21.1.2 and earlier.

Kind regards

**Comment by ShadowNev** [comment]
Hello, 
for 21.1.4 with DB2
not working at all too

for example DELETE correctly fill  output tab with messages

**Comment by LonwoLonwo** [comment]
Would you please check against the newest DBeaver release?
Examples for issue reproducing for Oracle and DB2 also will be very helpful.

**Comment by uslss** [comment]
still cannot reproduce it against 21.3.2.
@RamonCar66 is it still actual for you? please provide a video of an issue if it is

**Comment by ShadowNev** [comment]
at this moment, in the recent version I cannot reproduce the issue on Oracle
but on DB2 still no output
![output](https://user-images.githubusercontent.com/42059626/148747102-331d6e64-014a-4c4c-8672-08d21f2f2c0f.gif)

**Comment by LonwoLonwo** [comment]
Hello @ShadowNev 

DBeaver doesn't support output panel messages in DB2 yet. You can create another issue as a feature request for this.
