### ISSUE TITLE
Incorrect syntax (excessive quotes) when updating Exasol geometry data

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13392]
#### System information: 
- DBeaver version 21.1.4

#### Connection specification:
- Database name and version Exasol
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

#### Describe the problem you're observing:
Excessive quotes are added for a script when trying to save changes to geometry column. 

#### Steps to reproduce, if exist:
1. Create a table with a geometry column.
2. Edit a data in it or add one more row with not null field in this column
3. Try to save changes

**Expected:** Changes are saved
**Actual:** Script is not executable because additional quotes are generated

![dbeaver_NnJcraZbn5](https://user-images.githubusercontent.com/82543000/127810101-8966495c-5474-4eb3-b2a1-9727b4759583.png)

**Comment by LonwoLonwo** [comment]
Some useful references:
https://docs.exasol.com/sql_references/geospatialdata/import_geospatial_data_from_csv.htm
https://docs.exasol.com/sql_references/geospatialdata/geospatialdata_overview.htm

**Comment by LonwoLonwo** [comment]
Quotation fixed in UPDATE statement.

Also, the ability to update geometry columns in the table with the primary key (sic!) was added.

**Comment by Matvey16** [comment]
Verified
