### ISSUE TITLE
DBeaver won't start

### ISSUE THREAD

**Issue by Mark531** [dbeaver/dbeaver#13407]
#### System information: 
- Operating system (distribution) and version Windows 10 version 1909
- DBeaver version 21.1.2
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
DBeaver won't start.

#### Steps to reproduce, if exist:
Run dbeaver.exe.

#### Include any warning/errors/backtraces from the logs
No logs are generated at the root of DBeaver directory and in %APPDATA%\DBeaverData\workspace6\.metadata.

**Comment by Matvey16** [comment]
@Mark531 Can you add more information? For example what happens after you run the .exe, at which point it stops executing? At a meantime I would recommend uninstalling and reinstalling DBeaver and if that doesn't change anything, as a second solution you can backup your %APPDATA%\DBeaverData\ folder in other directory and delete it to see if some corruption in a workspace is causing the issue.

**Comment by Mark531** [comment]
As I said, it stops straightaway, without any error message nor log. Ok, I will try your solutions.

**Comment by Mark531** [comment]
As I told you, nothing was displayed and no log was generated.
I had to reinstall DBeaver to have it work again.
