### ISSUE TITLE
[Data transfer] Support tables order when generating SQL

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#13403]
We need to extend the functionality added in https://github.com/dbeaver/dbeaver/issues/11118 into the cases of transfer to SQL and DDL generation.

**Comment by LonwoLonwo** [comment]
Won't fix.
No reason to change the export order for SQL export, because the tables are exported to different files, and not in one.

![2021-10-18 11_13_58-Window](https://user-images.githubusercontent.com/45152336/137699656-94e42601-acfd-4099-9638-9f3248aa95c4.png)
