### ISSUE TITLE
Bookmarks working?

### ISSUE THREAD

**Issue by rrousselot** [dbeaver/dbeaver#13408]
#### System information: 
- Operating system (distribution) and version - Windows 10 
- DBeaver version - 21.1.4
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I cannot for the life of me make a Bookmark.  Is it me or is there something wrong.  

#### Steps to reproduce, if exist:
I simply cannot make a bookmark.

**Comment by Matvey16** [comment]
@rrousselot Thank you for the report. Our wiki page had outdated information. The default shortcut changed somewhen to <kbd>CTRL+ALT+SHIFT+D</kbd>  
If it is not really convenient for you, you can change any shortcut in preferences. Also if you forgot your shortcuts you can open `Help > Show Active Keybindings` to see the list of shortcuts.

**Comment by rrousselot** [comment]
It is also that way in the Documentation PDF. 

Thank you!
