### ISSUE TITLE
Cannot add comment to foreign table in Postgres

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#13406]
Hi!
I have foreign table:

CREATE FOREIGN TABLE XXX (
	id_ varchar(64) NOT NULL,
	rev_ numeric(38) NOT NULL,
	resource_type_ varchar(255) NOT NULL,
	name_ varchar(255) NOT NULL,
	owner_ varchar(255) NULL,
	query_ bytea NULL,
	properties_ bytea NULL
)
SERVER YYY
OPTIONS (schema 'ZZZ', table 'KKK');

Then I try to add comment and the SQL is generated as "COMMENT ON TABLE XXX" but this doesnt work, we need "COMMENT ON foreign TABLE" instead.
When I added comment manually, the metadata still shows "COMMENT ON TABLE XXX" - it is still incorrect, but comment is displayed

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.2.1

**Comment by Matvey16** [comment]
Can't delete a comment for a foreign table

![aXUuyouxp8](https://user-images.githubusercontent.com/82543000/132187774-f0df80c0-eed9-47d8-93b3-02d77968848f.gif)

**Comment by Matvey16** [comment]
Verified
