### ISSUE TITLE
PK column shows the wrong icon in "Columns" tab

### ISSUE THREAD

**Issue by www-uu** [dbeaver/dbeaver#13410]
#### System information: 
- Operating system (distribution) and version: Windows 10 Home
- DBeaver version: 21.1.4.202108020335
- Additional extensions: TimescaleDB

#### Connection specification:
- Database name and version: PostgreSQL 12.6 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 64-bit

#### Describe the problem you're observing:
In pgAdmin4 v5.2, the "Primary key" show Yes.
In DBeaver, the "Identity" show blank.

![图片](https://user-images.githubusercontent.com/7844108/127944952-12e97552-f19f-4a6f-89de-bbbd30503502.png)

![图片](https://user-images.githubusercontent.com/7844108/127945542-48aa41a3-6f13-4aec-b3aa-b3d33b67648b.png)

**Comment by p91paul** [comment]
I suppose "identity" refers to this feature https://www.postgresqltutorial.com/postgresql-identity-column/
Primary keys are shown under constraints!

**Comment by Matvey16** [comment]
@p91paul Thank you, you are correct. This field doesn't refer to PK.

@JH-D Hello, as mentioned above this field doesn't refer to PK. To see if the column is a primary key, you either can look at Constraints tab in table metadata, or refer to a key icon in the Columns tab.

![dbeaver_RSUlX1hEVd](https://user-images.githubusercontent.com/82543000/127981662-a65d0698-6a8b-4212-bdc2-4e5d82d3cd65.png)

![dbeaver_Bqj1dAZ2vo](https://user-images.githubusercontent.com/82543000/127981677-13f841ec-7a85-4286-aa57-2ec4be1bdff5.png)

**Comment by www-uu** [comment]
@Matvey16 
In Columns tab, the key icon not see.
In Constraints, yes can see.

![图片](https://user-images.githubusercontent.com/7844108/127988445-291342d9-2c1c-4e86-a8d4-7e232a729d94.png)

![图片](https://user-images.githubusercontent.com/7844108/127987758-0fc6cbfa-75f8-43a8-979f-c44d75df5008.png)

**Comment by Matvey16** [comment]
@JH-D This seems strange. Can you provide a DDL for this table?

**Comment by www-uu** [comment]
> 
> 
> @JH-D This seems strange. Can you provide a DDL for this table?

I only replace the table name.


```
-- Drop table

-- DROP TABLE public.demo_t;

CREATE TABLE public.demo_t (
	id bigserial NOT NULL,
	"time" date NOT NULL,
	name text NOT NULL,
	value float8 NULL,
	CONSTRAINT demo_t_pkey PRIMARY KEY (id)
);
CREATE INDEX demo_t_time_idx ON public.demo_t USING btree ("time" DESC);

-- Table Triggers

create trigger ts_insert_blocker before
insert
    on
    public.demo_t for each row execute function _timescaledb_internal.insert_blocker();
```

**Comment by Matvey16** [comment]
@JH-D I wasn't able to reproduce it. Do you see key icon on other PK columns in other tables?

![dbeaver_T1G4Q8oNw7](https://user-images.githubusercontent.com/82543000/128177237-ff1aa8ca-9152-47d7-bfc0-32d2a3767aa4.png)

**Comment by www-uu** [comment]
> 
> 
> @JH-D I wasn't able to reproduce it. Do you see key icon on other PK columns in other tables?
> 

I find how to reproduce, in any table with primary key, in every time.

1. Open DBeaver.
![图片](https://user-images.githubusercontent.com/7844108/128279723-7f1340eb-1825-4744-bf8c-fc79f967e7b5.png)

2. Open database, open table.  Right now, the key icon is not see.
![图片](https://user-images.githubusercontent.com/7844108/128279298-d24f6d3c-5ed4-4aad-b130-da92a93f9275.png)

3. **Click the "Constraints" tab.**
![图片](https://user-images.githubusercontent.com/7844108/128279413-20f33d26-8a73-421a-a735-18ff4d25ff14.png)

4. **Click "Columns" tab.**
![图片](https://user-images.githubusercontent.com/7844108/128279547-5d22b480-c3c0-4034-927f-8b1c369a19cf.png)

5. **Click “Refresh” button** in bottom right-hand corner.
![图片](https://user-images.githubusercontent.com/7844108/128279523-6818e2b1-3bed-4016-92d1-d98f988568a1.png)

6. Now, the key icon can seen.
![图片](https://user-images.githubusercontent.com/7844108/128279682-ac04dcbf-143c-4730-bacb-b89c7ff42f2d.png)

**Comment by Matvey16** [comment]
@JH-D Thank you, we will work on that

**Comment by LonwoLonwo** [comment]
This feature for PostgreSQL has added some time ago: https://github.com/dbeaver/dbeaver/issues/6383
with the comment: 

> We will read this info in lazy mode (icon will appear only if table constraints were already read - this is always true for table data viewer).

So it's not a bug.

But we understand that this situation can be confusing sometimes. 
For now, the problem is in constraint cache reading. It's not cheap to read it on the table column reading step. 
We need to find a better solution for this problem in the next releases.

**Comment by LonwoLonwo** [comment]
Related issue created: https://github.com/dbeaver/dbeaver/issues/14544

This ticket will be closed.
