### ISSUE TITLE
Failed to upgrade dbeaver from v.7.2.5 to v.21.1.4

### ISSUE THREAD

**Issue by SupervisionT** [dbeaver/dbeaver#13418]
#### System information: 
- Operating system (distribution) and version: Fedora linux 27
- DBeaver version: current: Community Edition 7.2.5, update to ==>  21.1.4

#### Describe the problem you're observing:
When attempt to update from v. 7.2.5 to v. 21.1.4
``` sudo dpkg -i --force-overwrite dbeaver-ce_21.1.4_amd64.deb ```

I'm having this error:
```(Reading database ... 0 files and directories currently installed.)
Preparing to unpack dbeaver-ce_21.1.4_amd64.deb ...
dpkg (subprocess): cannot set security execution context for maintainer script: Invalid argument
dpkg: error processing archive dbeaver-ce_21.1.4_amd64.deb (--install):
 subprocess new pre-installation script returned error exit status 2
Errors were encountered while processing:
 dbeaver-ce_21.1.4_amd64.deb
```

This may be related to this [issue 47](https://github.com/dbeaver/dbeaver/issues/47)

**Comment by Matvey16** [comment]
@SupervisionT This can be related to the fact that 7.2.5 is pretty old and has different dependencies on top of other differences. Have you tried uninstalling current version and then clean installing the new one?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen an issue.
