### ISSUE TITLE
Schema loss after executing a failing sql script

### ISSUE THREAD

**Issue by vincendep** [dbeaver/dbeaver#13415]
#### System information: 
- Windows 10 Pro
- DBeaver 21.1.4

#### Connection specification:
- Postgres 9.4
- PostgreSQL

#### Describe the problem you're observing:

After executing an sql script, if an error occur the selected schema is lost and I'm able to reexecute the script only opening a new script tab.

#### Steps to reproduce, if exist:

1. Editor SQL -> New SQL script
2. Select a database and a schema though the dropdown
3. Execute a failing script
4. Fix the script and run it again to get the error

Errore SQL [42P01]: ERROR: relation "tank_mix" does not exist
  Posizione: 15", but it does exist

5. And if I try to change the schema another error is showing: 

Error changing default database
Error setting search path
Error setting search path
ERROR: current transaction is aborted, commands ignored until end of transaction block
ERROR: current transaction is aborted, commands ignored until end of transaction block
ERROR: relation "tank_mix" does not exist
  Posizione: 15
ERROR: relation "tank_mix" does not exist
  Posizione: 15"

This errors seems to appear only selecting the database and the schema after opening the sql script tab.
If I select in advance the default database and schema through the Database Navigator, nothing happens after executing a failing script

**Comment by uslss** [comment]
@vincendep unfortunately, cannot reproduce it. could you provide a video of an issue?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual - feel free to reopen it with additional info that will help to reproduce an issue
