### ISSUE TITLE
Replace with lookahead regexp in needle won't work

### ISSUE THREAD

**Issue by AnrDaemon** [dbeaver/dbeaver#13414]
#### System information: 
- Windows/any
- DBeaver 24.1.4
- No additional extensions

#### Connection specification:
- Irrelevant (editor issue)

#### Describe the problem you're observing:
Replacement not performed if needle contains lookahead expression. See image.
![image](https://user-images.githubusercontent.com/6532485/127995572-30791cf4-8337-4e9a-8e87-d65f0076f756.png)

#### Steps to reproduce, if exist:
Text:
```
SELECT test.TEST_NAME
--     , test.TEST_FIELD AS GUI_STATUS
     , ext.EXT_CODE
     , test.TEST_ENTRYNUMBER
FROM XXX test
LEFT JOIN EXXXXT ext ON ext.TEST_ID = test.TEST_ID
;
```
Find: `test(?=\W)`
Replace: `tst`
[x] Regexp
[ Replace All ]

The subject matching is correct, the status reporting successful replacements, but nothing is actually replaced.

#### Include any warning/errors/backtraces from the logs
No errors reported, this is a functional misbehavior.

**Comment by uslss** [comment]
thank you for the report

**Comment by serge-rider** [comment]
Eclipse-specific behavior.

**Comment by AnrDaemon** [comment]
Can you please point me to the relevant issue tracker then?

**Comment by Matvey16** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=109481

Closed by Eclipse as `Won't fix`

**Comment by AnrDaemon** [comment]
Closed by timeout, as I can see. Thanks for the pointer.
