### ISSUE TITLE
copy sql as source code for delphi and single quote

### ISSUE THREAD

**Issue by nicolanicoletti** [dbeaver/dbeaver#13436]
#### System information: 
- Windows 10
- DBeaver version 21.1.4.202108020335
- dark theme and office 

#### Describe the problem you're observing:

when i use "copy  sql as source code" and i don't select use string builder option the code generated have half cicle ")" in end of  code. Delphi require string inside single quote at begin and end.  Another problem is when i use single quote inside sql and generation of code. Single quote is in delphi a reserved charater for defining string . If i want use single quote in a string is necessary repeat single quote.
 

#### Example code generate from dbaver
            'SELECT COD_AGE_ID,STATO FROM mytable aa  ' + 
            'where COD_AGE_ID = '00125' ');

   correct version in delphi

            'SELECT COD_AGE_ID,STATO FROM mytable aa  ' + 
            'where COD_AGE_ID = ''00125'' ';

**Comment by uslss** [comment]
thank you for the report

**Comment by uslss** [comment]
verified

**Comment by nicolanicoletti** [comment]
Hi 
dbaver 21.3.2 has same issue.
Have you integrate patch ?

**Comment by Destrolaric** [comment]
@nicolanicoletti Hi, this fix will be released in version 21.3.3
