### ISSUE TITLE
Can't edit Athena AWS Simba Driver Properties

### ISSUE THREAD

**Issue by ntmeade** [dbeaver/dbeaver#13441]
#### System information: 
- Operating system (distribution) and version - Mac OS Big Sur 11.4
- DBeaver CE version 21.1.4.202108020335
- Additional extensions

#### Connection specification:
- Database name and version AWS Athena
- Driver name AWS/Athena
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When attempting to edit values in Driver Properties, a drop-down validation field is given with the only available selection being "?". Previous versions of DBeaver allowed for a text based value to be included such as "com.simba.athena.amazonaws.auth.profile.ProfileCredentialsProvider"
#### Steps to reproduce, if exist:
AWS/Athena Driver Connection Settings
Driver Properties
Select value field for any named properties

**Comment by uslss** [comment]
thank you for the report

**Comment by LonwoLonwo** [comment]
Fixed. Didn't work in BigQuery and Vertica drivers also (which have combo boxes in driver properties).

**Comment by RodSM** [comment]
> Fixed. Didn't work in BigQuery and Vertica drivers also (which have combo boxes in driver properties).

Thank you @LonwoLonwo for the fix! Could you please give an estimation when it will be released?

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.2.0
Will be available [here](https://dbeaver.io/) on 2021-08-30

**Comment by Matvey16** [comment]
Verified
