### ISSUE TITLE
Pinned columns cannot be rearranged

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#13447]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.1.5

#### Describe the problem you're observing:
Pin more than one column, try to rearrange pinned columns at data grid - columns order remains the same, but it changes in Customize filters pop-up
![2021-01-17_14h08_27](https://user-images.githubusercontent.com/31996417/104838659-8a7e3900-58cd-11eb-8f1a-a09afae81832.gif)

**Comment by ShadelessFox** [comment]
Implemented:

https://user-images.githubusercontent.com/35821147/128344503-d5f3833e-6667-4a15-8493-3d10918b0072.mp4

**Comment by Matvey16** [comment]
Verified
