### ISSUE TITLE
Can't change interaface language to english

### ISSUE THREAD

**Issue by inliquid** [dbeaver/dbeaver#13450]
Dbeaver CE 21.1.4 / Win10

My OS language is Russian. Added "-nl en" as instructed by documentation:
```
-startup
plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.100.v20210209-1541
-nl
en
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m

```

However interface seems to switch only partly. Most of it is still in Russian:
![изображение](https://user-images.githubusercontent.com/6797881/128343450-bd3137c1-4665-47fe-84ec-88dedae0a5a0.png)

Before that I installed it using Windows installer and selecting "English" TWICE during installation. It worked for a while, but eventually DBeaver switched to Russian, in just a couple of days. I didn't update it, or even touched it, just restarted at some point.

**Comment by inliquid** [comment]
Just to add to the last point - after it switched to native OS language, I did complete reinstall with all defaults during installation process. This was just a note.

**Comment by Matvey16** [comment]
@inliquid Hello. The issue you encountered is related to a shortcut that is created during install. It has a ` -nl en` property where `en` is the language that you picked during install. When it switched back to russian, did you start it from .exe file or from the same desktop shortcut?

**Comment by inliquid** [comment]
I can't tell actually, because reinstalled portable version which seems to not have this issue. What I usually do is open start menu, then type program name such as "dbea,,,", and then select from the search result, after that I just pin it on the bottom panel. I expect it to be either binary or a shortcut to the binary. I also expect that running `*.exe` file have the same effect as shortcut. 

Another point is that after I added `-nl` option to vm args, does it really matter?

I think what actually needs to be fixed is the possibility to change it through settings, like with portable version.

**Comment by Matvey16** [comment]
@inliquid You can change language in properties, but it is impossible if you install DBeaver into a read-only directory like a default Program Files.
If you change a language after installation and want it to persist, you need to create a new shortcut, or start DBeaver from .exe file and repin it to taskbar.

**Comment by inliquid** [comment]
Thanks. As I said, I already found a workaround with using portable version only. 

Here is quick recap for a language related problems of DBeaver:

0. Just a note: `Program Files` dir is not read-only
1. To make it easier to work with config files from the OS security perspective, it is possible to save configs in `%APPDATA%` as many other programs do
2. Language selection should not be implied by shortcut created by installer
3. It should not be possible for shortcut to override JVM args set in system config file
4. DBeaver should not ask user twice for a language during installation
5. It's not clear when installer asks for a language, is it a language for installer and installation process, or for a program operation

**Comment by scruel** [comment]
Same problem on Windows 10 20H2, DBeaver 21.2.1.202109181446.

**Comment by emironovDB** [comment]
The language already can be changed in the preferences.

The problem is that the shortcut contains the language itself, overriding the one set in the preferences.

Depends on #16187
