### ISSUE TITLE
Option to turn off Code Completion case and white spaces sensitivity

### ISSUE THREAD

**Issue by MebsSystem** [dbeaver/dbeaver#13476]
**Is your feature request related to a problem? Please describe.**

Now Code Completion works like this:
select * from TABLE T where t. --will NOT trigger code completion (cases of aliases don't match)
select * from TABLE T where T. --will trigger code completion (cases match)

Some databases are case sensitive so it's ok. 
But sometimes this feature is disabled in database and it will be nice to have an option to disable it in dbeaver SQL Editor.

And other problem:
select
	*
from
	table t
where
	t. -- will trigger code completion

select
	*
from
	table t
(EMPTY LINE)
where
	t. -- will NOT trigger code completion

select
	*
from
	table t
where
	t.id = '1'
(EMPTY LINE)
	and t. -- will NOT trigger code completion

Code Completion should ignore empty lines.
Sometimes to make SQL Query more human readable DB developers use empty lines to visually separate some parts of query.

**Describe the solution you'd like**
A checkbox in Preferences/SQL Editor/Code Completion to turn on/off case sensitivity.

**Describe alternatives you've considered**
Remove case sensitivity at all?

**Comment by tati-kru** [comment]
Thanks for the report

**Comment by uslss** [comment]
@MebsSystem Uncheck Blank line is statement delimiter option in Preferences, so blank lines will be ignored
![image](https://user-images.githubusercontent.com/31996417/147465016-afc62f9a-0dc9-42c1-85a0-7e3e7135f187.png)
