### ISSUE TITLE
Importing CSV in Postgresql is too slow.

### ISSUE THREAD

**Issue by hoi82** [dbeaver/dbeaver#13474]
#### System information: 
- Operating system (distribution) and version
- Windows 10
- DBeaver version
- 21.1.4.202108020335
- Additional extensions

#### Connection specification:
- Database name and version
- Postgresql 11.8 (Ubuntu 11.8-1.pgdg20.04+1)
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
- No

#### Describe the problem you're observing:

 When I import using CSV file consists of 18k rows, 11 columns it takes about 20 minutes since upgrade to the lastest version DBeaver.
 Are there any changes on import?

#### Steps to reproduce, if exist:

 Import CSV file consists of 18k rows, 11 column to postgreSQL table.

**Comment by Matvey16** [comment]
@hoi82 Can you show me your import settings? I tried reproducing it, and imported 20k rows of 11 columns in 20 seconds

**Comment by EdgHidden** [comment]
Hello,

I'm having the same issue with data import into postgresql.

OS - Windows 10
Connection - PostgreSQL 13.1, compiled by Visual C++ build 1914, 64-bit (on the same device)

Issue is reproducible for both DBeaver CE and EE.

DBeaver version 21.0.0.202103080721 - OK
DBeaver version 21.1x and above - NOK

File .csv with 242k rows import times:

version 21.0.0.202103080721 - 4.8 sec
version 21.2.0.202108310918 - 4 min 32 sec

Import settings in DBeaver interface:

**21.0.0**:

![image](https://user-images.githubusercontent.com/87520872/132317545-ad5bf7fe-fef1-4ec6-b87c-0c50bb3e1aa2.png)

**21.2.0**:

![image](https://user-images.githubusercontent.com/87520872/132317677-11590f05-becd-4094-b154-a188b70cee66.png)

In 21.2.0 This section seems to take ~10-15sec to finish "updating":

![image](https://user-images.githubusercontent.com/87520872/132317822-af44beb8-6565-45e9-9776-663e8a338cbb.png)

And at the end, import is processing 1000 rows at a time, unlike in the 21.0.0 version.

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
