### ISSUE TITLE
Firebird - Parameter type change from numeric to bigint

### ISSUE THREAD

**Issue by MebsSystem** [dbeaver/dbeaver#13471]
#### System information: 
- Operating system (distribution) and version: OSX 11.3
- DBeaver version: 21.1.4
- Additional extensions: null :)

#### Connection specification:
- Database name and version: Firebird 2.5
- Driver name: org.firebirdsql.jdbc.FBDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : null

#### Describe the problem you're observing:
After double clicking to edit procedures sources params types are changed from numeric to bigint.

#### Steps to reproduce, if exist:

Create procedure:
```sql
CREATE PROCEDURE ms_test (par_id integer) 
RETURNS (
	num numeric(15,4) --DECIMALS ALLOWED
) 
AS
BEGIN
	--body
end
```

Click on it in DatabaseNavigator to view source:
```sql
CREATE OR ALTER PROCEDURE MS_TEST (PAR_ID INTEGER)
RETURNS (
	NUM BIGINT --CHANGED TO BIGINT, NOT ALLOWED DECIMALS
)
AS
BEGIN
	--body
end
```

**Comment by LonwoLonwo** [comment]
Fixed for numeric and decimal types.

**Comment by Matvey16** [comment]
Verified
