### ISSUE TITLE
Tooltips change in strange ways

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13487]
#### System information: 
- Win10
- DBeaver CE 21.1.4

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/43252954/128722166-29dcce4b-476e-48c4-adef-6f5bbc32ef25.png)
![image](https://user-images.githubusercontent.com/43252954/128722549-dd9f334f-3abd-4ce8-8d92-e159dcb974eb.png)
There are two type of tooltip for the same buttons - with and without a tooltip. They replace each other when the user does actions with other toolbar buttons. For example, steps to reproduce:
1. in table data grid press enter when one of the cells is selected. Then press enter. 
2. Look at the delete button - it's tooltip displayed without shortcut
3. in table data grid press enter once more
4. Press Cancel toolbar button
5. Delete button tooltip contains shortcut now!

https://user-images.githubusercontent.com/43252954/128724074-8e976d24-8308-4c94-8dbe-ac92e1a7ba9c.mp4

**Comment by E1izabeth** [comment]
Can't reproduce against DBeaver 23.0.5
