### ISSUE TITLE
Wrong syntax for connection limit in Role DDL

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13495]
#### System information: 
- DBeaver version 21.1.4

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
Open a role DDL

**Expected**:  no limit is written as `-1` https://www.postgresql.org/docs/8.1/sql-createrole.html
**Actual result**: no limit is written as `UNLIMITED`

**Comment by LonwoLonwo** [comment]
https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_USER.html yep, redshift syntax

**Comment by LonwoLonwo** [comment]
Fixed. For PostgreSQL and Redshift (EE version - only there we have roles).

![2021-12-27 15_27_28-DBeaver Ultimate 21 3 1 - miriam](https://user-images.githubusercontent.com/45152336/147471775-dae61372-4154-4ba4-848f-b7d446f75adf.png)

**Comment by uslss** [comment]
verified
