### ISSUE TITLE
Column length cannot be less then 3 symbols in txt export

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13491]
#### System information: 
- Operating system (distribution) and version Win
- DBeaver version 21.1.4

#### Steps to reproduce, if exist:
1. Export a table in txt format and set min/max column length 1/2
2. Perform the export
![dbeaver_IBRTYWjUSY](https://user-images.githubusercontent.com/51405061/128988041-5eb0fc10-6a01-4ae3-96b2-b6b53a55dd26.png)

**Expected**: max 2 symbols are displayed in the column cell
**Actual result**: column length has 3 symbols

**Comment by Matvey16** [comment]
Verified
