### ISSUE TITLE
select records using spatial viewer

### ISSUE THREAD

**Issue by JeroenNienhuis** [dbeaver/dbeaver#13501]
When one of more cells with spatial data are selected the spatial data are shown on a map. This is a very useful feature. It would be even more useful if it could also be used the other way around: selecting records with spatial data graphically.

When I have a table data frame opened (with or without a filtered selection) and click the spatial column, all records are selected and shown on a map. I can zoom and pan the map and click on items, but it is not possible to select a number of features by using for example Ctrl-mouse. Maybe a bit like Shift-mouse (used for zooming), but then add the selected area to the filtered selection.
An optional empty map could opened from the context menu after right-clicking the spatial column.

**Comment by tati-kru** [comment]
We can implement navigation to selected GIS objects thru the context menu.

**Comment by JeroenNienhuis** [comment]
What do you mean? Selected GIS objects on the map (using the context menu of the map) and add the result to the datagrid selection? 
I think there are a few basic solutions: 
- selecing items on the map by clicking on items and build a collection of selected items and after that pick "add selection to filter" from the map context menu. This would need some kind of onClick event for items on the map. The result is probably a list of id's which can be added to the filter like " id in (......)". The number of items that someone wants to select can be large and clicking all of them might not be the best solution. And there might be multiple locations on the map with the same geometries so you can select only the one on top.
- selecting items by drawing a rectangle or some other shape and after that pick "add selection to filter" from the map context menu. This would need some kind of onDraw events for the map. The result could be a list of id's which can be added to the filter like " id in (......)". This would need selection of GIS objects based on the drawn geometry within Leaflet(?)
- selecting items by drawing a rectangle or some other shape and after that pick "add selection to filter" from the map context menu. This would need some kind of onDraw events for the map. The drawn geometry can be added to the filter like " ST_contains ( [drawn polygon], [geom-field] )". Instead of ST_contains there are multiple other GIS functions that can be used. This option could be used on a map without geometries.

**Comment by ShadelessFox** [comment]
Implemented in the value viewer panel:

https://user-images.githubusercontent.com/35821147/165108424-f43956d0-ecbd-42cf-a01a-7227c4445b15.mp4

Features:
- Map features can be selected by clicking on them
- By holding CTRL, the selection will be extended
- Pressing ESC or clicking outside features will clear the selection

**Comment by JeroenNienhuis** [comment]
Nice! This helps.
But when I have something like this
![afbeelding](https://user-images.githubusercontent.com/51078213/165970326-ea22fde3-a37e-4201-b88a-9c4f6b1184f5.png)
and want to select part of the geometries graphically? Is it possible to create a filter like e.g.
_**st_contains((ST_MakeEnvelope(123456, 456789, 133456, 466789, 28992)), the_geom);**_

**Comment by ShadelessFox** [comment]
I don't quite follow your use case. Can please you provide more information? What do you mean by `select graphically`?

**Comment by JeroenNienhuis** [comment]
Selecting geometries not by clicking on each them, but e.g. by drawing a rectangle like on the middle of the map below and select everything inside the selected area.
![afbeelding](https://user-images.githubusercontent.com/51078213/165987287-bc5c0054-751b-44e4-be19-8e6974a66c46.png)
The boundary of the drawn area can be used in a gis function that is added to the filter clause (see the example in the previous mail), but I do not know if the gis-functions that are needed are universal  (I only use postgres). An alternative could be getting the id's of the selected records (if a table has a primary key) and add these id's to the filter.

**Comment by ShadelessFox** [comment]
Sorry for the late response.

Oh, so you're talking about another way of selecting features on the map. We could either add a lasso or a rectangular selection tool.

Since this issue is now closed, can you please create a separate FR just for that? Thanks.
