### ISSUE TITLE
PostGIS: special geometry types are not supported

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#13500]
#### Connection specification:
- Database name and version **PostgreSQL 12**

#### Describe the problem you're observing:
The following types are not supported and cause error to display in UI:
 - geometrycollection
 - circularstring
 - compoundcurve
 - curvepolygon
 - multicurve
 - multisurface
 - polyhedralsurface
 - triangle
 - tin

**Comment by ShadelessFox** [comment]
Fixed:

![java_fCLMmnwDTy](https://user-images.githubusercontent.com/35821147/129060546-654f11dd-6ef1-4d27-9616-2b961e9d8862.png)

**Comment by DariaMarkaryan** [comment]
Verified
