### ISSUE TITLE
Case-insensitive search in column filter has inconsistent behavior

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13507]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.5

#### Describe the problem you're observing:
1. When searching for value with unchecked option `Read from server` the search is always case-insensitive even when this option is disabled.
2. The option for case-insensitive search is greyed out if filter window was closed with disabled `read from server` and will stay inactive until window is closed with enabled `read from server` and then reopened

#### Steps to reproduce, if exist:
![6Ns1M9DSw8](https://user-images.githubusercontent.com/82543000/129172855-930da9c8-84d9-49bf-808f-0db63e9c6131.gif)
![cAfegqychs](https://user-images.githubusercontent.com/82543000/129172875-0625a698-d989-474e-8780-f866f4231212.gif)

**Comment by ShadelessFox** [comment]
The first issue is database-specific. Some databases perform a case-insensitive search by default. In offline search, we always perform a case-insensitive search. So won't fix.

**Comment by Matvey16** [comment]
Verified
