### ISSUE TITLE
Error on Update

### ISSUE THREAD

**Issue by acrey1** [dbeaver/dbeaver#13518]
#### System information: 
- Operating system (distribution) and version: Win10
- DBeaver version: 21.1.4.202107231409
- Additional extensions: N/A

#### Connection specification:
- Database name and version: N/A
- Driver name: N/A
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
**Error message:**   Missing requirement: DBeaver PostgreSQL Support UI 1.0.39.202108120648 (org.jkiss.dbeaver.ext.postgresql.ui 1.0.39.202108120648) requires 'osgi.bundle; org.eclipse.gef3 0.0.0' but it could not be found

#### Steps to reproduce, if exist:
> Check for Updates

#### Include any warning/errors/backtraces from the logs
As above

**Comment by LonwoLonwo** [comment]
Hello @acrey1 
Which version to which version did you want to update? 
org.eclipse.gef3 bundle require for PostgreSQL UI plugin only in DBeaver 21.1.5 version, these are fresh changes.

**Comment by acrey1** [comment]
Hi Anastasiya,

I am running the EA version of EE (https://dbeaver.com/files/ea/enterprise/update/dbeaver/).

I am just doing a normal weekly update and getting the error message.

Do I need to install an additional plug-in?

Adam.

**Comment by serge-rider** [comment]
It was a corrupted update site.
Now fixed.

Thank you for the bug report 👍
