### ISSUE TITLE
Radix Number Formatter: `Bits` parameter doesn't do anything

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#13510]
#### Describe the problem you're observing:
There's some problems and improvements related to radix formatter:
1. <kbd>Bits</kbd> parameter does not affect the result. I suspect it should trim LSB bits when radix is set to `2`.
2. Negative numbers are displayed with minus sign in a weird place (`0x-1`), more convenient alternative would be `-0x1`
3. In addition to the previous point, I suggest adding a new parameter to use unsigned formatting (e.g. `0xFFFFFFFF` instead of `-0x1`)

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
Verified
