### ISSUE TITLE
Column Selection and Editing

### ISSUE THREAD

**Issue by rrousselot** [dbeaver/dbeaver#13516]
Please implement the following in the editor.  Notepad++ used as example.

Column Mode & Column Editor
Using Alt + Mouse dragging or Alt + Shift + Arrow keys to switch to column mode:

![image](https://npp-user-manual.org/docs/images/columnMode.gif)

**Comment by ShadelessFox** [comment]
It's already implemented: <kbd>Alt+Shift+A</kbd>
