### ISSUE TITLE
SQL Server: Source tab is empty in the index properties

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13529]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.5 EA

#### Connection specification:
- Database name and version: SQL Server Azure
#### Steps to reproduce, if exist:
Open a table clustered index in Metadata Editor

**Expected**: Source tab has Index DDL
**Actual result**: the Source tab is empty.
![dbeaver_wuaK5Era1S](https://user-images.githubusercontent.com/51405061/129363781-762710d8-d78d-4606-9fb8-e0825b4c9592.png)

**Comment by willturcios1** [comment]
@LonwoLonwo thanks for updating the one I opened, I looked around and did not find this one, but yes this is the same behavior.

**Comment by willturcios1** [comment]
Also want to point out it does work for non-clustered indexes so perhaps is just a filter issue when extracting.

**Comment by LonwoLonwo** [comment]
> Also want to point out it does work for non-clustered indexes so perhaps is just a filter issue when extracting.

Thanks, I fixed the name of this issue.

**Comment by Nrj27** [comment]
is this issue still open?

**Comment by LonwoLonwo** [comment]
Hello @Nrj27 

Yes, it is.

The problem here is in the SQLServerTableIndex#readIndexDefinition
The query there is not for unique/primary indexes.

**Comment by Nrj27** [comment]
@LonwoLonwo can you please share complete problem query along with complete screenshot.
please share the system requirements.

**Comment by LonwoLonwo** [comment]
You can find the query in SQLServerTableIndex#readIndexDefinition. No special system requirements

**Comment by SaumilP** [comment]
Is this issue still available for fix?

**Comment by HansenChristoffer** [comment]
I added PR with fix. Would need couple of eyes on it.
