### ISSUE TITLE
Redshift generete full DDL: Unsupported vector type: com.amazon.redshift.util.RedshiftObject

### ISSUE THREAD

**Issue by archenroot** [dbeaver/dbeaver#13523]
#### System information: 
- Operating system (distribution) and version: Gentoo
- DBeaver version - 
- Additional extensions

#### Connection specification:
- Database name and version: AWS Redshift
- Driver name: redshift
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: ssh

#### Describe the problem you're observing:
When using generate DDL for Schema in redshift database when I click button complete DDL i get the following message:
![image](https://user-images.githubusercontent.com/553512/129329442-7c669f86-642d-41dd-9acd-4653da961c78.png)

#### Steps to reproduce, if exist:
right-click on schema and generate ddl, use complete ddl option checkbox.
NOTE: some schemas doesn't fail
#### Include any warning/errors/backtraces from the logs
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/6981113/dbeaver.log)

**Comment by LonwoLonwo** [comment]
Hello @archenroot 
When DBeaver generates schema DDL it uses DDL from all tables. So the problem is with specific tables. 
Can you please find this specific table for example? Its DDL will be very helpful for issue reproducing.

**Comment by deepaksenthilkumar** [comment]
@LonwoLonwo -I have noticed this error earlier. It occurs when the 2.x Redshift JDBC Driver is used instead of 1.x driver as 2.x expects RedshiftObject instead of PostgreObject
@archenroot-What's the JDBC driver used?

**Comment by uslss** [comment]
thanks for the report. Reproducible against 2.0.0.7 driver.

**Comment by deepaksenthilkumar** [comment]
AFAIK-DBeaver doesn’t work on Redshift 2.x drivers.--
SD

**Comment by deepaksenthilkumar** [comment]
I checked further on this and the issue is for tables with unique key

CREATE TABLE public.temp_unique_key (col1 varchar(10),unique(col1)) 

Then try to get the DDL for this. It won't work.

**Comment by serge-rider** [comment]
Fixed. Now we support RedshiftObject values.

@kseniiaguzeeva please test it with geometry data types.

**Comment by deepaksenthilkumar** [comment]
Thanks for fixing this team! It works very well with 2.x driver compared to 1.x driver.

**Comment by Matvey16** [comment]
Verified
