### ISSUE TITLE
Copy to clipboard doesn't work for xls format

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13538]
#### System information: 
- Operating system (distribution) and version Win 10
- DBeaver version 21.1.5

#### Steps to reproduce, if exist:
1. Install office extension
2. Export a table in xls format to clipboard

**Expected**: the data is xopied to clipboard in xls format
**Acual result**: copy to clipboard option is disabled
![dbeaver_QCYidJMIFI](https://user-images.githubusercontent.com/51405061/129476584-469281a4-0db0-40c7-8ac8-004baa66042d.png)

**Comment by ShadelessFox** [comment]
It's disabled because XLSX is a binary format. AFAIK excel and other tools accept only text data when pasting from clipboard.
