### ISSUE TITLE
Redshift: No Schema Binding views column datatypes are inconsistent and length are missing in the navigator

### ISSUE THREAD

**Issue by deepaksenthilkumar** [dbeaver/dbeaver#13536]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.1.4

#### Connection specification:
- Database name and version: Redshift 1.0.29551 
- Driver name: https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.45.1069/RedshiftJDBC42-no-awssdk-1.2.45.1069.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc) SSH

#### Describe the problem you're observing:
Table and Normal View have the right column data types/length
![image](https://user-images.githubusercontent.com/36084950/129468718-d09009df-c129-4ca2-b6e5-2c167b0a24b5.png)
![image](https://user-images.githubusercontent.com/36084950/129468726-4c639ff9-750c-4614-89ee-50f588706696.png)

No schema binding View has a different data type (variant) and column length (precision/scale) are missing/different
![image](https://user-images.githubusercontent.com/36084950/129468764-bcab7092-f584-45a6-987e-9a6168616048.png)

#### Steps to reproduce, if exist:

Create the following table, views, and check the output.

Table:
CREATE TABLE IF NOT EXISTS test_all_types
(
	c1 SMALLINT   ENCODE az64
	,c2 INTEGER   ENCODE az64
	,c3 BIGINT   ENCODE az64
	,c4 NUMERIC(18,0)   ENCODE az64
	,c5 REAL   ENCODE RAW
	,c6 DOUBLE PRECISION   ENCODE RAW
	,c7 BOOLEAN   ENCODE RAW
	,c8 CHAR(1)   ENCODE lzo
	,c9 VARCHAR(256)   ENCODE lzo
	,c10 DATE   ENCODE az64
	,c11 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,c12 TIMESTAMP WITH TIME ZONE   ENCODE az64
	,c15 TIME WITHOUT TIME ZONE   ENCODE az64
	,c16 TIME WITH TIME ZONE   ENCODE az64
)
DISTSTYLE AUTO
;

No Schema Binding View:
CREATE VIEW v_test_all_types_nb AS
SELECT a.c1, a.c2, a.c3, a.c4, a.c5, a.c6, a.c7, a.c8, a.c9, a.c10, a.c11, a.c12, a.c15, a.c16 FROM test_all_types a
WITH NO SCHEMA binding;

Binding View:
CREATE VIEW v_test_all_types_b AS
SELECT a.c1, a.c2, a.c3, a.c4, a.c5, a.c6, a.c7, a.c8, a.c9, a.c10, a.c11, a.c12, a.c15, a.c16 FROM test_all_types a;

**Comment by serge-rider** [comment]
Fixed in #13541

@deepaksenthilkumar Thank you 👍

**Comment by uslss** [comment]
verified
