### ISSUE TITLE
Copy as SQL adds N to uniqueidentifier value

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13537]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.5 EA

#### Connection specification:
- Database name and version SQL Server Azure

#### Steps to reproduce, if exist:
Open a table with a uniqueidentifier column and copy its value in SQL format

**Expected**: the cell value is copied
**Actual result**: N is added to the copied value

![dbeaver_ocxSMV7o2v](https://user-images.githubusercontent.com/51405061/129476083-69e083d3-5943-4b67-9854-3219689b983a.png)

**Comment by ShadelessFox** [comment]
It's a feature. `N` prefix stands for Unicode string literal.

https://docs.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql
