### ISSUE TITLE
Sybase JTDS / jConnect Problems

### ISSUE THREAD

**Issue by hufersil** [dbeaver/dbeaver#13532]
Hi,

Using the version 6 or above of DBeaver  (including the one released on 2021-08-02), I'm unable to connect to Sybase database using jConnect. Using the JTDS driver, I was able to connect, but I faced the problem of this ticket: https://github.com/dbeaver/dbeaver/issues/3528

I tried using jConnect, but in my case I must use the parameter APPLICATIONNAME, but it seems to me that this version is not passing the value to the connection string. Using DBeaver 5.1.6 with jConnect driver works fine.

In summary:

Current Version of DBeaver (released on 2021-08-02)
With JTDS:
- Create the connection with APPNAME 
- It connects
- If I specify the column names, I'm able to execute queries. If I use * or joins, it crashes
- Tables, users and other objects are not listed

With jConnect
- Create the connection with APPLICATIONNAME (the parameter name is different from JTDS)
- It doesn't connect, because it's like I'm not sending this parameter value (although it's filled)

DBeaver 5.1.6
With jConnect
- Create the connection with APPLICATIONNAME 
- It connects
- Everything works fine

#### System information: 
- Windows 10 Pro x64 (Brazilian Portuguese)
- DBeaver version - 21.1.4.202108020335
- No Additional extensions

#### Include any warning/errors/backtraces from the logs
Error log's of DBeaver version - 21.1.4.202108020335

*JTDS Driver*
```
Can't read schema list

java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.mssql.model.generic.SQLServerMetaModel.loadSchemas(SQLServerMetaModel.java:349)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:550)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:926)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

*jConnect Driver*
```
RAISERROR executed:  Acesso negado. Usuário deve possuir uma credencial válida ou específica para esse usuário (Access denied. User must have a valid or specific credential for that user)

eclipse.buildId=unknown
java.version=11.0.11
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=pt_BR
Command-line arguments:  -os win32 -ws win32 -arch x86_64
```
In the case of jConnect driver, as mentioned before, it's like the value of APPLICATIONNAME its not being appended to the connection string

For the time being, I'm reverting to 5.1.6

Thanks in advance

**Comment by serge-rider** [comment]
Could you say what Sybase server version do you use?

**Comment by hufersil** [comment]
Thanks for replying!

This image is from DBeaver 5.1.6 using Sybase jConnect, which works fine as mentioned before.

![image](https://user-images.githubusercontent.com/2363112/129903108-792d9342-e8c5-413a-af06-dcad3570e7de.png)

**Comment by uslss** [comment]
unfortunately, still cannot reproduce. Is it still actual for you?

**Comment by hufersil** [comment]
Hi!

I didn't tested with the newest version.
I'll test it and make a video, and if it is still happening, I'll send the video it to you.

thanks in advance!

**Comment by hufersil** [comment]
It is still happening. I made a video, but I'm not good at video editing. I have to hide the credentials / ip etc, then I'll post it here.

**Comment by uslss** [comment]
There has been no update on the issue for a long time.
If it is still present, feel free to reopen it.

**Comment by hufersil** [comment]
Hello there!

This still being a issue.

Seems that this parameter is not being passed when connecting to database.
 
![Captura de Tela 2022-05-19 às 15 06 09](https://user-images.githubusercontent.com/2363112/169369920-822c520e-73a9-4e38-aa7e-4d4412c7b5d9.png)

This is the version where this error occurs:

![Captura de Tela 2022-05-19 às 15 09 20](https://user-images.githubusercontent.com/2363112/169370823-00be92b8-5cdb-4d0a-90a9-f54896418f83.png)

This is the version that works fine

![f5adebe4-7720-4467-97e3-c1d5bad754b8](https://user-images.githubusercontent.com/2363112/169371230-4ed09d61-5db2-4c7d-a773-4093ff53f2e0.jpeg)

**Comment by hufersil** [comment]
I got it working, but I think this is a bug

The client identification panel is overriding that driver parameter.
When I put the value in this pane, it works fine.

![Captura de Tela 2022-05-19 às 15 32 05](https://user-images.githubusercontent.com/2363112/169375589-b4e5bcba-f656-4b8c-a038-2029fcfbdec3.png)

In other words 
- if I set the value driver properties, like in 5.1.6 version, the connection does not work
- if I set the value in this panel, it works
