### ISSUE TITLE
DBeaver won't open Windows 10 

### ISSUE THREAD

**Issue by mantinnne** [dbeaver/dbeaver#13533]
Hello!
Can you please tell me what is the problem with running dbveawer on windows 10?
I use the installer dbeaver-ce-21.1.4-x86_64-setup.exe but also tried the archive.

Installed java 11 on the system.

Problem: During the first installation, everything starts up, but if you close the application and start it again, the program does not open, but hangs in the system.

Found a problem in the plugin along the path: D: \ Users \ Mantinne \ AppData \ Roaming \ DBeaverData \ workspace6 \ .metadata \ .plugins \ org.eclipse.e4.workbench
If you delete the workbench.xmi file there, the program will start successfully 1 time

I attach the log file

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/6984761/dbeaver-debug.log)
[.log](https://github.com/dbeaver/dbeaver/files/6984682/default.log)

**Comment by Matvey16** [comment]
@mantinnne Hello, thank you for the report. If it is possible can you try to delete DBeaverData folder entirely and reinstall DBever?

**Comment by mantinnne** [comment]
@Matvey16  Hello, Of course, I tried deleting and reinstalling, and DBeaverData try delete

Windows 10 20h2 oc 19042.746

**Comment by ayan84** [comment]
WIndows denfender has a feature called Controlled Folder Access. Turn it off from Defender or allow dbeaver to see if your problem gone.

**Comment by mantinnne** [comment]
@ayan84 
Thanks a lot, it worked
