### ISSUE TITLE
Can't see connection type until it would be chosen manually

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13548]
#### System information: 
- Win10, DBeaver CE 21.1.5 

#### Connection specification:
 Seen in the SQLite, Vertica, Postgres...

#### Steps to reproduce:
Create new DB connection, click on edit connection in the connection context menu (or press F4). Go to the General tab.
Expected: You can see Development connection type selection in the combo box by default
Actual: The combo box is empty until you choose it explicitly, no matter if you connected to the DB or not

https://user-images.githubusercontent.com/43252954/129523190-55d123f9-0111-4105-bfd6-5b84f90c2575.mp4

**Comment by Matvey16** [comment]
Verified
