### ISSUE TITLE
Redshift Data Editor-Editing of Date/Timestamp columns fails

### ISSUE THREAD

**Issue by deepaksenthilkumar** [dbeaver/dbeaver#13544]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.1.4

#### Connection specification:
- Database name and version: Redshift 1.0.29551 
- Driver name: https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.45.1069/RedshiftJDBC42-no-awssdk-1.2.45.1069.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc) SSH

#### Describe the problem you're observing:
Data Editor doesn't work for insert or Update of Date/Timestamp columns in Redshift

#### Steps to reproduce, if exist:

Create below table
CREATE TABLE IF NOT EXISTS test_all_types
(
	c1 SMALLINT   ENCODE az64
	,c2 INTEGER   ENCODE az64
	,c3 BIGINT   ENCODE az64
	,c4 NUMERIC(18,0)   ENCODE az64
	,c5 REAL   ENCODE RAW
	,c6 DOUBLE PRECISION   ENCODE RAW
	,c7 BOOLEAN   ENCODE RAW
	,c8 CHAR(1)   ENCODE lzo
	,c9 VARCHAR(256)   ENCODE lzo
	,c10 DATE   ENCODE az64
	,c11 TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,c12 TIMESTAMP WITH TIME ZONE   ENCODE az64
	,c15 TIME WITHOUT TIME ZONE   ENCODE az64
	,c16 TIME WITH TIME ZONE   ENCODE az64
	,"-c10" VARCHAR(10)   ENCODE lzo
)
DISTSTYLE AUTO
;

Open Data Editor, try to add date/timestamp data. Following error occurs

![image](https://user-images.githubusercontent.com/36084950/129505756-3dc605b8-891f-486e-8041-bff7ae8b21a9.png)

**Comment by deepaksenthilkumar** [comment]
I was fixing the PostgreDateTimeValueHandler but noticed the Redshift JDBC driver 1.x doesn't work for bind variables with timestamptz. It works for Date, Timestamp but not for timestamptz. 

Probably we should have a skip bind value option for data editor too. 
@ShadelessFox @serge-rider @LonwoLonwo Thoughts?

Probably just fix date, timestamp at this point...

**Comment by serge-rider** [comment]
I've fixed it in a bit different fashion.

@deepaksenthilkumar Thank you for the bug report and bug fix 👍

**Comment by deepaksenthilkumar** [comment]
Thanks.
-- 
SD

**Comment by uslss** [comment]
verified
