### ISSUE TITLE
ERD search works only for table names

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13545]
#### System information: 
- DBeaver version 21.1.5
- Additional extensions

#### Describe the problem you're observing:
Search function in ER diagrams works only for table/view names and doesn't work for column names.

**Comment by LonwoLonwo** [comment]
Implemented

![2021-11-08 22_43_58-DBeaver Ultimate 21 2 4 - postgres](https://user-images.githubusercontent.com/45152336/140815482-d23d076e-ffeb-48d3-95a8-6798446e8d3a.png)

**Comment by Matvey16** [comment]
Verified
New issue created for improvement #14511
