### ISSUE TITLE
Security Definer is missing for a Redshift procedure in the Generate SQL>DDL statement

### ISSUE THREAD

**Issue by deepaksenthilkumar** [dbeaver/dbeaver#13559]
Create a procedure with a security definer option.

For example below is the code to create a procedure with security definer

CREATE OR REPLACE PROCEDURE sp_truncate_table(in_table_name character varying(256))
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $$
DECLARE
    v_table varchar ;
BEGIN
    v_table:=lower(trim(in_table_name)) ;
    RAISE INFO 'User % truncating table %', v_table ;
    EXECUTE 'truncate table '|| v_table;
END ;
$$

Below is what Generate SQL>DDL statement returns. (SECURITY DEFINER is missing)

CREATE OR REPLACE PROCEDURE sp_truncate_table(in_table_name varchar)
	LANGUAGE plpgsql
AS $$
	
DECLARE
    v_table varchar ;
BEGIN
    v_table:=lower(trim(in_table_name)) ;
    RAISE INFO 'User % truncating table %', v_table ;
    EXECUTE 'truncate table '|| v_table;
END ;

$$
;

**Comment by Matvey16** [comment]
Verified
