### ISSUE TITLE
DBEAVER with access

### ISSUE THREAD

**Issue by selster** [dbeaver/dbeaver#13552]
I have the lastest dBeaver, created a simple table in microsoft access, created a new microsoft access connection in dBeaver, it downloaded the lastest driver, I chose my latest database4.accdb file.  (In microsoft access, my table is named "sheet2.")  The test for the connection is 4ms.  The database shows in the dBeaver tree.  But under Tables, when I click on it, no individual tables show.  Therefore I cannot do a select * from anyTable of any kind, let alone from sheet2 or from database2.sheet2??? Thanks, Steve

**Comment by Matvey16** [comment]
Hello, @selster Sorry, I was not able to reproduce this issue. Is there a chance for you to provide a file that has this issue, so I can try looking what is wrong with it.

**Comment by selster** [comment]
First let me clarify my question. If you click on the name of a stash, either left click or right click, I assume it would be a right click. Can you get a URL for that stash, something that I can then paste into OneNote. So that when I go to OneNote, I can click on that URL, and it will take me back to that particular stash? Or maybe it will open all of the web pages inside of that stash? This is the kind of thing I mean. I'm not sure it's even possible. Thanks, Steve

⁣Get BlueMail for Android ​

**Comment by Matvey16** [comment]
@selster sorry, I can't quite understand what leads to your issue. For me to reproduce it and then decide on the solution, we need you to describe clear steps that lead to this, or at least send a video with those steps. Also it would be good to know your OS and DBeaver version

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info
