### ISSUE TITLE
Debian 21.1.5 wont start

### ISSUE THREAD

**Issue by b90g** [dbeaver/dbeaver#13555]
#### System information: 
- Operating system (distribution) and version Debian 11 latest
- DBeaver version 21.1.5
- Additional extensions  mariadb

#### Connection specification:
- Database name and version - not applicable

#### Steps to reproduce, if exist:

Updating from 21.1.4 to 21.1.5

trying to execute binary.

Binary seem to be lost.

dbeaver doesnt start.

**Comment by b90g** [comment]
(downgrading to 21.1.4, dbeaver starts again..)

maybe something packaged wrong.

**Comment by serge-rider** [comment]
Executable `dbeaver` was renamed to `dbeaver-ce` (because of multipel different dbeaver products).

We probably should return `dbeaver` alias for Community version (at least for backward compatibility)

**Comment by b90g** [comment]
Thenks but when entering `db` and pressing the tab button for autocomplete all debian knew was dbus, searched in /bin, /sbin, /usr/bin, /usr/sbin.

also: is it  a use case to have the community version and the directors cut on the same os installed?

**Comment by ThaDaVos** [comment]
Same issue here - after install latest version, any executables are gone... no `dbeaver` and no `dbeaver-ce` on my side

**Comment by ThaDaVos** [comment]
@b90g how did you downgrade? I tried `sudo apt-get install dbeaver-ce=21.1.4` but it tells me no version like it exists...

**Comment by CSharpRon** [comment]
@ThaDaVos I was able to downgrade by apt removing dbeaver-ce followed by manually downloading and then installing the .deb for 21.1.4 here 
[https://github.com/dbeaver/dbeaver/releases](https://github.com/dbeaver/dbeaver/releases).

**Comment by joanbm** [comment]
Same here, I used to launch DBeaver by running `dbeaver` from a terminal but there is no longer any binary with this or a similar name in my `PATH`.

I can launch DBeaver by running `/usr/share/dbeaver-ce/dbeaver` directly.

**Comment by serge-rider** [comment]
Fixed.
Version 21.2 was re-published

**Comment by Matvey16** [comment]
Verified for .deb packages

**Comment by Matvey16** [comment]
Verified
