### ISSUE TITLE
Error with xp_cmdshell

### ISSUE THREAD

**Issue by resquej** [dbeaver/dbeaver#13563]
Hi,

After install new version 21.1.5 I get this error, before it works fine.

Error occurred during SQL query execution
Reason:
SQL Error [229] [S0005]: The EXECUTE permission was denied on the object 'xp_cmdshell', database 'mssqlsystemresource', schema 'sys'.

when running:

exec xp_cmdshell 'net use'

thank you

#### System information: 
- Windows 10
- 21.1.5

**Comment by Matvey16** [comment]
@resquej Hello, can you be more specific, when this happens? Also please attach a log file.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it
