### ISSUE TITLE
Exasol SQL syntax highlighting

### ISSUE THREAD

**Issue by allipatev** [dbeaver/dbeaver#13568]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.1.3.202107181810
- Additional extensions: no

#### Connection specification:
- Database name and version: Exasol 7.0
- Driver name: EXASolution JDBC Driver 7.0.4
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: no

#### Describe the problem you're observing:

May I ask how DBeaver decides which words to highlight for Exasol?

Maybe EXA_SQL_KEYWORDS is used for that purpose.
But I still see functions in the docs (https://docs.exasol.com/sql_references/functions/all_functions.htm, written down below for your convenience), mentioned in EXA_SQL_KEYWORDS but not highlighted.

|Function name|
|-|
|ABS|
|ACOS|
|ADD_DAYS|
|ADD_HOURS|
|ADD_MINUTES|
|ADD_MONTHS|
|ADD_SECONDS|
|ADD_WEEKS|
|ADD_YEARS|
|ANY|
|APPROXIMATE_COUNT_DISTINCT|
|ASCII|
|ASIN|
|ATAN|
|ATAN2|
|AVG|
|BIT_AND|
|BIT_CHECK|
|BIT_LENGTH|
|BIT_LROTATE|
|BIT_LSHIFT|
|BIT_NOT|
|BIT_OR|
|BIT_RROTATE|
|BIT_RSHIFT|
|BIT_SET|
|BIT_TO_NUM|
|BIT_XOR|
|CASE|
|CAST|
|CEIL|
|CEILING|
|CHR|
|CHAR|
|CHARACTER_LENGTH|
|COALESCE|
|COLOGNE_PHONETIC|
|CONCAT|
|CONNECT_BY_ISCYCLE|
|CONNECT_BY_ISLEAF|
|CONVERT|
|CONVERT_TZ|
|CORR|
|COS|
|COSH|
|COT|
|COUNT|
|COVAR_POP|
|COVAR_SAMP|
|CUME_DIST|
|CURDATE|
|CURRENT_DATE|
|CURRENT_SCHEMA|
|CURRENT_SESSION|
|CURRENT_STATEMENT|
|CURRENT_TIMESTAMP|
|CURRENT_USER|
|DATE_TRUNC|
|DAY|
|DAYS_BETWEEN|
|DBTIMEZONE|
|DECODE|
|DEGREES|
|DENSE_RANK|
|DIV|
|DUMP|
|EDIT_DISTANCE|
|EVERY|
|EXP|
|EXTRACT|
|FIRST_VALUE|
|FLOOR|
|FROM_POSIX_TIME|
|GREATEST|
|GROUP_CONCAT|
|GROUPING|
|GROUPING_ID|
|HASH_MD5|
|HASH_SHA|
|HASH_SHA1|
|HASH_SHA256|
|HASH_SHA512|
|HASH_TIGER|
|HASHTYPE_MD5|
|HASHTYPE_SHA|
|HASHTYPE_SHA1|
|HASHTYPE_SHA256|
|HASHTYPE_SHA512|
|HASHTYPE_TIGER|
|HOUR|
|HOURS_BETWEEN|
|IF|
|INITCAP|
|INSERT|
|INSTR|
|IPROC|
|IS_NUMBER|
|IS_DATE|
|IS_TIMESTAMP|
|IS_BOOLEAN|
|IS_DSINTERVAL|
|IS_YMINTERVAL|
|JSON_EXTRACT|
|JSON_VALUE|
|LAG|
|LAST_VALUE|
|LCASE|
|LEAD|
|LEAST|
|LEFT|
|LENGTH|
|LEVEL|
|LISTAGG|
|LN|
|LOCALTIMESTAMP|
|LOCATE|
|LOG|
|LOG2|
|LOG10|
|LOWER|
|LPAD|
|LTRIM|
|MAX|
|MEDIAN|
|MID|
|MIN|
|MINUTE|
|MINUTES_BETWEEN|
|MOD|
|MONTH|
|MONTHS_BETWEEN|
|MUL|
|NOW|
|NPROC|
|NTH_VALUE|
|NTILE|
|NULLIF|
|NULLIFZERO|
|NUMTODSINTERVAL|
|NUMTOYMINTERVAL|
|NVL|
|NVL2|
|OCTET_LENGTH|
|PERCENT_RANK|
|PERCENTILE_CONT|
|PERCENTILE_DISC|
|PI|
|POSITION|
|POSIX_TIME|
|POWER|
|RADIANS|
|RAND|
|RANDOM|
|RANK|
|RATIO_TO_REPORT|
|REGEXP_INSTR|
|REGEXP_REPLACE|
|REGEXP_SUBSTR|
|REGR_FUNCTIONS|
|REPEAT|
|REPLACE|
|REVERSE|
|RIGHT|
|ROUND|
|ROWNUM|
|ROW_NUMBER|
|ROWID|
|RPAD|
|RTRIM|
|SCOPE_USER|
|SECOND|
|SECONDS_BETWEEN|
|SESSION_PARAMETER|
|SESSIONTIMEZONE|
|SIGN|
|SIN|
|SINH|
|SOME|
|SOUNDEX|
|SPACE|
|SQRT|
|ST_AREA|
|ST_BOUNDARY|
|ST_BUFFER|
|ST_CENTROID|
|ST_CONTAINS|
|ST_CONVEXHULL|
|ST_CROSSES|
|ST_DIFFERENCE|
|ST_DIMENSION|
|ST_DISJOINT|
|ST_DISTANCE|
|ST_ENDPOINT|
|ST_ENVELOPE|
|ST_EQUALS|
|ST_EXTERIORRING|
|ST_FORCE2D|
|ST_GEOMETRYN|
|ST_GEOMETRYTYPE|
|ST_INTERIORRINGN|
|ST_INTERSECTION|
|ST_INTERSECTS|
|ST_ISCLOSED|
|ST_ISEMPTY|
|ST_ISRING|
|ST_ISSIMPLE|
|ST_LENGTH|
|ST_MAX_DECIMAL_DIGITS|
|ST_NUMGEOMETRIES|
|ST_NUMINTERIORRINGS|
|ST_NUMPOINTS|
|ST_OVERLAPS|
|ST_POINTN|
|ST_SETSRID|
|ST_STARTPOINT|
|ST_SYMDIFFERENCE|
|ST_TOUCHES|
|ST_TRANSFORM|
|ST_UNION|
|ST_WITHIN|
|ST_X|
|ST_Y|
|STDDEV|
|STDDEV_POP|
|STDDEV_SAMP|
|SUBSTR|
|SUBSTRING|
|SUM|
|SYS_CONNECT_BY_PATH|
|SYS_GUID|
|SYSDATE|
|SYSTIMESTAMP|
|TAN|
|TANH|
|TO_CHAR|
|TO_DATE|
|TO_DSINTERVAL|
|TO_NUMBER|
|TO_TIMESTAMP|
|TO_YMINTERVAL|
|TRANSLATE|
|TRIM|
|TRUNC|
|TRUNCATE|
|UCASE|
|UNICODE|
|UNICODECHR|
|UPPER|
|USER|
|VALUE2PROC|
|VAR_POP|
|VAR_SAMP|
|VARIANCE|
|WEEK|
|YEAR|
|YEARS_BETWEEN|
|ZEROIFNULL|

**Comment by LonwoLonwo** [comment]
Hello @allipatev 
DBeaver gets information about keywords and functions words from the driver directly.

![2021-08-17 20_46_38-DBeaver Ultimate 21 1 5 - _none_Script-54](https://user-images.githubusercontent.com/45152336/129775805-0e3cd942-e228-4b78-bb7b-082606ec5974.png)

But this list can be not so correct, as you can see in the picture. Some words are recognized as functions (blue), some as keywords (red), and some words are steel without special coloring.

So we will add functions word in ExasolDialect class directly as functions. Thanks.

**Comment by allipatev** [comment]
Hi @LonwoLonwo .
Thanks for your response!
Could you please also tell which driver method is used for that purpose?

**Comment by LonwoLonwo** [comment]
Hello @allipatev 
I used EXASolution JDBC Driver 7.0.3

**Comment by allipatev** [comment]
Hi @LonwoLonwo ,
I mean: does DBeaver call a particular JDBC driver method like java.sql.ResultSet.getMetaData() for that purpose?

**Comment by LonwoLonwo** [comment]
DBeaver load functions here https://github.com/dbeaver/dbeaver/blob/47a069fccfea6d041f5ba287c168fc50496ba0fc/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/jdbc/JDBCSQLDialect.java#L382
from DatabaseMetaData

**Comment by allipatev** [comment]
Thanks your response @LonwoLonwo.
Maybe Exasol will also add the functions into JDBCDatabaseMetaData methods output.

**Comment by LonwoLonwo** [comment]
Oh, I was wrong. We read reserved keywords from EXA_SQL_KEYWORDS
and functions from 
`SELECT "VALUE" FROM "$ODBCJDBC".DB_METADATA WHERE name = 'aggregateFunctions'`

**Comment by LonwoLonwo** [comment]
I added most of the functions from the list. In DBeaver 21.2.2

**Comment by uslss** [comment]
verified

**Comment by allipatev** [comment]
For unknown reason some functions (e.g. BIT_LROTATE) were not added to cee337a3f711342c899bf819574f9b9756e06cbe => they aren't still highlighted.
Exasol might fix the whole issue in version 8.0.
