### ISSUE TITLE
Athena: changing schema in SQL Editor does nothing

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13569]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.5
- Additional extensions

#### Connection specification:
- Database name and version Athena

#### Describe the problem you're observing:
Queries are always executed on default schema even if it is changed in SQL editor

#### Steps to reproduce, if exist:
1. Change schema in SQL editor to any other than default
2. Run select form a table from selected schema

**Expected:** Query is executed from correct schma
**Actual:** Query is executed form default schema

![N4n7JPXljZ](https://user-images.githubusercontent.com/82543000/129735714-c72f80c8-9b0f-437d-9c48-3727b57bdb6a.gif)

**Comment by DavidBraslow** [comment]
I think this relates to https://github.com/dbeaver/dbeaver/issues/11196
