### ISSUE TITLE
Remember tree hierarchy even when there are tabs to restore

### ISSUE THREAD

**Issue by JGKle** [dbeaver/dbeaver#13561]
Per [this issue](https://github.com/dbeaver/dbeaver/issues/6345), I've found that dbeaver is supposed to restore the expansion state of the navigator tree. However, I've found that it doesn't do so if there are also any tabs to restore. In other words, if I close all tabs before exiting, then the next time I launch, it will properly expand the tree - but if I leave any tabs opened, then I have to manually expand the tree. The option "Expand navigator tree on connect" partially alleviates this, but only partially - I always have to manually expand the last level in the tree. I've also tried setting "Restore navigator state up to depth"=10, but it seems to have no effect.

Using Beaver 21.1.5 on Linux (Kubuntu).

**Comment by Matvey16** [comment]
@metal450 Thank you for the report. It seems more like a bug to me. The tree doesn't expand if at least one tab is opened, and also generates a lot of errors.
Steps to reproduce;
1. Allow auto-expand for navigator in preferences
2. Open at least on editor tab and expend a tree to at least table level
3. Close and reopen Dbeaver

The tree is expected to be expanded (if the depth is chosen correctly in preferences), but it expands only one level and logs a lot of errors.


```java
!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:53.822
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:54.010
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:54.197
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:54.197
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:54.197
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:54.197
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:54.197
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:54.197
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:54.197
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:54.197
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:54.197
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:54.197
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:54.197
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:54.197
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:54.197
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-26 11:33:54.197
!MESSAGE 
```

**Comment by Matvey16** [comment]
The bug still persists

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
The issue is reproducible again

**Comment by Matvey16** [comment]
It looks like if the fix somehow got reverted

**Comment by Matvey16** [comment]
Verified
