### ISSUE TITLE
Can't edit Athena AWS Driver Properties

### ISSUE THREAD

**Issue by RodSM** [dbeaver/dbeaver#13562]
**System information:**
Operating system (distribution) and version - Mac OS Big Sur 11.5.2
DBeaver CE version 21.1.5
Additional extensions

**Connection specification:**
Database name and version AWS Athena
Driver name AWS/Athena
Do you use tunnels or proxies (SSH, SOCKS, etc)? No

**Describe the problem you're observing:**
When attempting to edit values in Driver Properties, a drop-down validation field is given with the only available selection being "?". Previous versions of DBeaver allowed for a text based value to be included such as "AwsCredentialsProviderArguments"

Steps to reproduce, if exist:
AWS/Athena Driver Connection Settings
Driver Properties
Select value field for any named properties

Include any warning/errors/backtraces from the logs

**Comment by Matvey16** [comment]
Duplicates #13441
