### ISSUE TITLE
Dbeaver automatically dump database with "--no-data" option

### ISSUE THREAD

**Issue by slade991** [dbeaver/dbeaver#13566]
#### System information: 
- Operating system (distribution) and version : Linux arch 5.10.56-1-lts 
- DBeaver version : 21.1.4.202108022028

#### Connection specification:
- Database name and version : mysql  Ver 15.1 Distrib 10.3.25-MariaDB
- Driver name ( i'm not sur but it shouldn't be relevant)
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No but it's not a local database remote server is : Ubuntu Server 20.04

#### Describe the problem you're observing:

When trying to dump a database the option "--no-data" is automatically added to mysqldump. There is no extra args specified in the dump windows. 

#### Steps to reproduce, if exist:

I am not sure it just automatically do that. A normal mysqldump comment connecting to the remote database is able to dump the database correctly.

**Comment by LonwoLonwo** [comment]
Hello @slade991 
Can you please show your Export configuration window?
Can't reproduce it for now. 
DBeaver add "--no-data" option only in case then setting "Structure only" enabled.

**Comment by slade991** [comment]
Alright,
i must have been utterly blind, i checked the export window 10 times and somehow i missed the "structure only" checkbox.
Sorry to have wasted your time!
Thank you.
