### ISSUE TITLE
Tooltips for connection types settings

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13575]
These two checkboxes in properties for connection types have no tooltips. We need to add them
![image](https://user-images.githubusercontent.com/43252954/129905375-e48a5f31-c4fe-49cf-a48d-57be09fce5a6.png)

**Comment by ShadelessFox** [comment]
What should these tooltips look like?

**Comment by DariaMarkaryan** [comment]
Something about functionality of these options i guess. There is no confirmation for running regular SQL queries. Perhaps this is a bug and you need to add confirmation when this option is enabled, or its purpose is not clear from its name.

**Comment by Destrolaric** [comment]
@FedorovaDarya I think I need some ideas about description text

**Comment by uslss** [comment]
Probably, non-select should be written as non-SELECT, sql executions - SQL executions
![image](https://user-images.githubusercontent.com/31996417/141985018-2470a282-0dc2-497c-97d9-83c6183e97b3.png)
