### ISSUE TITLE
One-click to turn on/off READ-ONLY setting

### ISSUE THREAD

**Issue by achangs** [dbeaver/dbeaver#13570]
**Is your feature request related to a problem? Please describe.**

I often need to turn this setting on/off, to prevent my clobbering a database by mistake.   Currently, to do this, I need to click several times to "Edit Connection", which is inconvenient.

**Describe the solution you'd like**

Make turning on/off of READ-ONLY into a simple one-click from the right-button pull-down menu.

Admittedly, this is only a minor issue, but I thought I'd ask to make this great tool even BETTER!    Thank you!

**Describe alternatives you've considered**

**Additional context**

**Comment by uslss** [comment]
in case the connection read-only setting is switched on/off when data viewer is opened and another connection is chosen at db navigator, focus on connection is lost.
![dbeaver_Xf6STGeJRR](https://user-images.githubusercontent.com/31996417/158589596-33042ce9-3319-4669-b73a-45e1a35f1a87.gif)

**Comment by uslss** [comment]
verified
