### ISSUE TITLE
mysql DEFAULT_GENERATED on update CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by 250846434** [dbeaver/dbeaver#13577]
#### System information: 
- windows 10
- DBeaver version : 21.1.5

#### Connection specification:
- mysql 8
- com.mysql.cj.jdbc.Driver 8.0.17
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
- no.

#### Describe the problem you're observing:

ALTER TABLE `dbName`.`tableName` MODIFY COLUMN update_time timestamp DEFAULT CURRENT_TIMESTAMP DEFAULT_GENERATED on update CURRENT_TIMESTAMP NULL;
#### Steps to reproduce, if exist:
modify date/datetime/timestamp column ,when column has ' on update CURRENT_TIMESTAMP' and column default is 'CURRENT_TIMESTAMP' then 
auto generate DDL is 'DEFAULT_GENERATED on update CURRENT_TIMESTAMP'.
but Should not exist 'DEFAULT_GENERATED '

**Comment by 250846434** [comment]
see the #10797
maybe modify this code?
plugins/org.jkiss.dbeaver.ext.mysql/src/org/jkiss/dbeaver/ext/mysql/edit/MySQLTableColumnManager.java 
like this?
```
private final ColumnModifier<MySQLTableColumn> ExtraInfoModifier = (monitor, column, sql, command) -> {
        String extraInfo = column.getExtraInfo();
        if (!CommonUtils.isEmpty(extraInfo)) {
            if (extraInfo.contains(MySQLConstants.EXTRA_INFO_DEFAULT_GENERATED)) {
                // remove "DEFAULT_GENERATED" See #13577
                extraInfo = extraInfo.replaceAll(MySQLConstants.EXTRA_INFO_DEFAULT_GENERATED,"");
            }
            if (!CommonUtils.isEmpty(extraInfo) &&
MySQLConstants.EXTRA_INFO_VIRTUAL_GENERATED.equalsIgnoreCase(extraInfo)) {
                if (!CommonUtils.isEmpty(column.getGenExpression())) {
                    sql.append(" GENERATED ALWAYS AS (").append(column.getGenExpression()).append(") VIRTUAL"); //$NON-NLS-1$ //$NON-NLS-2$
                } else {
                    log.debug("No virtual column generate expression found for " + column.getName());
                }
            } 
//             else if (MySQLConstants.EXTRA_INFO_DEFAULT_GENERATED.equals(extraInfo)) {
//                // Do not add "DEFAULT_GENERATED" to the statement. It caused MySQLSyntaxErrorException. See #10797
//            }
            else {
                sql.append(" ").append(extraInfo); //$NON-NLS-1$
            }
        }
    };
```

**Comment by LonwoLonwo** [comment]
Hello @250846434 
Please provide table DDL and clear steps to reproduce.
I can't reproduce it for now.

![2021-08-19 10_01_28-DBeaver Ultimate 21 1 5 - timestamp_default](https://user-images.githubusercontent.com/45152336/130023040-6fecbbf0-f80a-456b-9470-2ffb2a04483c.png)

**Comment by 250846434** [comment]
1.create column
```
ALTER TABLE `lix-demo`.demo ADD edit_time DATETIME DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NULL;
```
2.modify this column. like this image.
![update ddl error](https://user-images.githubusercontent.com/25220333/130029453-b6ed4410-ad91-405c-bee9-a8a488968f3e.png)

3. got it.
```
ALTER TABLE `lix-demo`.demo MODIFY COLUMN edit_time datetime DEFAULT CURRENT_TIMESTAMP DEFAULT_GENERATED on update CURRENT_TIMESTAMP NOT NULL COMMENT 'readonly';
```

i submited a PR,I'm not sure if this is correct, I just changed the corresponding method by referring to #10797.

**Comment by 250846434** [comment]
@LonwoLonwo 回复见上方,谢谢!

**Comment by LonwoLonwo** [comment]
Yes, thanks @250846434

**Comment by uslss** [comment]
verified
