### ISSUE TITLE
Bad package for Ubuntu: can't install update

### ISSUE THREAD

**Issue by MikePryadko** [dbeaver/dbeaver#13576]
**OS**: `Ubuntu 20.04.2 LTS x86_64`
**DE**: `Xfce 4.14`
**WM**: `Xfwm4 version 4.14.1 (revision 44809c49)`
At the moment I've:
![image](https://user-images.githubusercontent.com/31248040/129913155-f8520ead-fa65-4940-ba7d-89214babf6f5.png)
Today it offered me to download update (as many times before): I was redirected to browser and automatically started downloading of `dbeaver-ce_21.1.5_amd64.deb` file. I've run that file and get this (only _Remove_):
![image](https://user-images.githubusercontent.com/31248040/129913807-040ead80-ef1b-495d-94c2-398713432418.png)
But if I look at the installed version, I see this (no version at all):
![image](https://user-images.githubusercontent.com/31248040/129914361-3336cb62-a508-4d6f-8661-16870ab9357a.png)
What happened? Why can't I anymore install newer just via `*.deb`-file from [site](https://dbeaver.io/download/?start&os=linux&arch=x86_64&dist=deb)? How should I update dbeaver?

**Comment by Matvey16** [comment]
@MikePryadko Hello. Have you updated DBeaver by executing a *.deb file before? It can be related to our latest fix that let's you have multiple editions of Dbeaver on one machine.

**Comment by MikePryadko** [comment]
Hi @Matvey16 ! Yes, I've used that method few times and all was Ok.

**Comment by Matvey16** [comment]
Ok, we will look into that. In the meantime you can update either by removing and reinstalling DBEaver with latest deb package or just use `sudo dpkg -i dbeaver-ce_21.1.5_amd64.deb` to update your current version

**Comment by MikePryadko** [comment]
@Matvey16 thanks for the advice, but my current version works fine so I prefer to wait yours fix and then test it :sunglasses: I think it's right: I've got the problem and I'll report it fixed. :relieved:

**Comment by serge-rider** [comment]
Seems to be a problem with outdated PPA. Must be fixed by now.

**Comment by Matvey16** [comment]
@MikePryadko Are you sure you were able to just execute the .deb file and click an update button earlier. I can't remember if it was ever possible and everyone on our team who uses linux don't remember it either. I also tried installing old version 21.0.0 and update it with .deb file of 21.0.1 version, but it still had only remove.
Can you update any other app like this? Maybe this behavior was changed on OS level in some of the Ubuntu updates.

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info

**Comment by MikePryadko** [comment]
@Matvey16 yes, I'm sure. And yes - right now I've updated Zoom exactly by this way :relieved:

[![Watch the video](https://img.youtube.com/vi/LltpSm14eY8/hqdefault.jpg)](https://youtu.be/LltpSm14eY8)
(Click image to go to youtube)
