### ISSUE TITLE
after updating to 21.1.5, It's gone from menu system

### ISSUE THREAD

**Issue by eshirvana** [dbeaver/dbeaver#13587]
#### System information: 
- Linux m Ubuntu 21.04.2
- DBeaver version: 21.1.5.202108160727

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
after updating the snap package , I can't see the application in the menu system.
I only can open the app using terminal.

#### Steps to reproduce, if exist:
1)  refresh dbeaver package 
2) try to look it up in the system

**Comment by danielreis58** [comment]
Same problem here, Ubuntu 20.04.3

**Comment by Stollie** [comment]
Same issue as described here #13138 

Log message with this version:
```
SWT SessionManagerDBus: Failed to RegisterClient: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.259" (uid=1000 pid=250551 comm="/snap/dbeaver-ce/139/usr/share/dbeaver-ce/jre/bin/" label="snap.dbeaver-ce.dbeaver-ce (enforce)") interface="org.gnome.SessionManager" member="RegisterClient" error name="(unset)" requested_reply="0" destination=":1.35" (uid=1000 pid=2379 comm="/usr/libexec/gnome-session-binary --systemd-servic" label="unconfined")
```

**Comment by narasimhajupally** [comment]
facing same issue. using terminal to launch the application

**Comment by perbergstrand** [comment]
Same issue, on Ubuntu 21.04.
DBeaver .desktop file missing in /var/lib/snapd/desktop/applications

**Comment by riednyko** [comment]
Thank you for the bug report.
We just updated Snap package, please test it

**Comment by eshirvana** [comment]
worked for , have to remove and install it again.

**Comment by drees** [comment]
> worked for , have to remove and install it again.

Same here, also had to remove/install again. I ended up losing my workspace settings, had to restore from backup.

**Comment by eshirvana** [comment]
Closing this issue ,, since it's been fixed
