### ISSUE TITLE
Data Export Task:  lost output settings

### ISSUE THREAD

**Issue by flachtiago** [dbeaver/dbeaver#13589]
#### System information: 
- Windows 10 Pro
- DBeaver 21.1.3

#### Describe the problem you're observing:
Some configuration items, when editing my Data export task, specifically in Output screen such as Directory, "File name pattern" and "Open output folder at end" are always reset to its default values, even though the values for "outputFolder",  "outputFilePattern" and "openFolderOnFinish" are correctly stored in the tasks.json file.

#### Steps to reproduce, if exist:
- In DataBase Task Window right-click a previously created Data export task.
- Choose Edit task.
- In Output screen, General area, specify a different Directory and "File name pattern" and even in Results, try to uncheck "Open output folder at end".
- Click Next and save your settings.
- Click start to run your task.
- Next time you edit this task those item will be reset to its original values.
So, every modification in the related task queries requires aditional and repeated steps.

**Comment by uslss** [comment]
thanks for the report

**Comment by Matvey16** [comment]
Related #13222

**Comment by Matvey16** [comment]
Verified

**Comment by chrisv5** [comment]
There are more settings lost:

- file name pattern
- column configuration

**Comment by LonwoLonwo** [comment]
Hello @chrisv5 
The problem was fixed and the fix will be available in version 21.2.1
Or you can test it in the [Early Access](https://dbeaver.io/files/ea/) version now.

**Comment by chrisv5** [comment]
I can confirm that this bug has been fixed. As a side notice, numbers are now stored as floating point numbers in tasks.json, while they were integers previously. (I have a rather complex tasks.json versioned, thus I could easily verify/compare)

**Comment by LonwoLonwo** [comment]
Hmm, I see this point about float numbers in my tasks.json.
Please @chrisv5 tell me, does the replacement of integers in floating-point numbers interfere with you work?
