### ISSUE TITLE
Global data formatting: changes are visible only in one of the connections

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13585]
#### System information: 
- Win10, DBeaver CE 21.1.5

#### Steps to reproduce, if exist:
Find or create 2 cells with numeric(>1000)/time etc. in two connections. Make sure that local formatting is disabled for both of them. 
Go to the global formatting settings and change the locale so that it visually differs from the previous one. Apply changes.
Refresh the data in the table that was active when you made changes - data formatting is changed.
Go to the second connection. Refresh data.
Expected: Data in the second table is formatted according to the new Global settings
Actual: New data formatting wasn't applied, and refresh/reopening the table/reconnect/disconnect doesn't fix it

https://user-images.githubusercontent.com/43252954/130079874-aadade54-e46e-47a1-9974-c792a54f4445.mp4

**Comment by uslss** [comment]
verified
