### ISSUE TITLE
Postgres CSV import fails if CSV contains SQL key words (like Date) 

### ISSUE THREAD

**Issue by gsliskov** [dbeaver/dbeaver#13583]
Trying to import:
https://github.com/OxCGRT/covid-policy-tracker/blob/master/data/OxCGRT_latest.csv
fails with error "Can't find target attribute [Date]". Checked with other data, also fails (eg. OWID).

Worked in previous major version. Database table is created as it should.

**Comment by LonwoLonwo** [comment]
Hello @gsliskov 
Thanks for the bug report!
The problem was solved here https://github.com/dbeaver/dbeaver/issues/13542
Changes will be available in the new version DBeaver 21.2.0 on 2020-08-30.
