### ISSUE TITLE
Quotation doesn't change in export wizard

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13582]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.1.5

#### Describe the problem you're observing:
Quotation is remembered for initial target database even after it is changed in export wizard

#### Steps to reproduce, if exist:
1. Perform a successful export into a database that uses double quotes for quotations (e.g. PostgreSQL)
2. Start export and change target to another database that uses other symbol for quotation (e.g. MariaDB)
3. Review the appearance of target columns

Result:
There are double quotes instead of backticks in the generated script. Export cannot be performed.
![image](https://user-images.githubusercontent.com/31996417/128353165-6d3354b5-90ac-4776-95df-f6dcf682bc25.png)

Note:
The quotation is changed to correct after column mapping changing 
![Z55WGcoLsu](https://user-images.githubusercontent.com/31996417/128353507-189c4419-8a65-4249-a91e-46f47eb6cd32.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
