### ISSUE TITLE
TOP cannot be used as an OFFSET

### ISSUE THREAD

**Issue by GitHubAFeng** [dbeaver/dbeaver#13594]
#### System information: 
- Operating system (distribution) and version
- win10-64
- DBeaver version
- 21.1.5.202108160727
- Additional extensions
- none

#### Connection specification:
- Database name and version
- MS SQL Server 2017
- Driver name
- MS SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
- none

#### Describe the problem you're observing:

run the sql:

SELECT * FROM sys.messages WITH(NOLOCK) ORDER BY id DESC OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY

error: SQLServerException: TOP cannot be used as an OFFSET in the same query or subquery

Is that the reason?
![image](https://user-images.githubusercontent.com/17705357/130173841-9c986759-c900-4f2c-bd05-f13a4784bc03.png)

**Comment by uslss** [comment]
thank you for the report

**Comment by uslss** [comment]
verified
