### ISSUE TITLE
Oceanbase plugin development

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#13596]
Most job was done by  @LuckyLeoZZ in https://github.com/dbeaver/dbeaver/pull/13449

**Comment by serge-rider** [comment]
@LuckyLeoZZ new plugin merged in devel. It is ready to be inbcluded in release cycle. However there are several issues with it:
- No driver jars specified. It is not clear where to get them. Perfect solution would be to specify some Maven artifact in driver config. Or some https download link at least. We usually do not add new database extensions without drivers because for end users it is hard to use them.
- Please add icons for high res monitors. I mean ob_icon and ob_icon_big. Just add ob_icon@2x.png and ob_icon_big@2x.png with resolution 32x32 and 128x128
- On the connection page pre-fill default database port, host (localhost?) and database name

**Comment by LuckyPickleZZ** [comment]
@serge-rider Thank you very much. For these questions you said, I 'll make improvements in the near future.
And I would like to tell you that I maybe request for a PR for OB oracle mode. Sorry for increasing the workload of review for you.

**Comment by LuckyLeoZZ** [comment]
@serge-rider Thank you very much. For these questions you said, I 'll make improvements in the near future.
And I would like to tell you that I maybe request for a PR for OB oracle mode. Sorry for increasing the workload of review for you.

**Comment by LuckyPickleZZ** [comment]
@serge-rider Hello,  our team discussed it and decided to give up the PR of Oracle mode for the time being. Could you please add our plugin to the next release and let our users use it first?

**Comment by LuckyPickleZZ** [comment]
@tati-kru Hello, our team discussed it and decided to give up the PR of Oracle mode for the time being. Could you please add our plugin to the next release and let our users use it first?

**Comment by tati-kru** [comment]
@LuckyLeoZZ we cannot include your plugin to the release without the fixes mentioned above. Please, fix them and we can move forward.

**Comment by LuckyPickleZZ** [comment]
> @LuckyLeoZZ we cannot include your plugin to the release without the fixes mentioned above. Please, fix them and we can move forward.

Thanks al lot. I see what you mean. We'll fix these soon.

**Comment by LuckyPickleZZ** [comment]
> @LuckyLeoZZ we cannot include your plugin to the release without the fixes mentioned above. Please, fix them and we can move forward.

https://github.com/dbeaver/dbeaver/pull/14607
Please check this. I've made some impovements.

**Comment by serge-rider** [comment]
@LuckyLeoZZ is there any cloud service where we can test the driver? Or maybe a standalone version of OceanBase?

**Comment by serge-rider** [comment]
Extension was included in CE build

**Comment by uslss** [comment]
closed without testing

**Comment by LuckyPickleZZ** [comment]
> @LuckyLeoZZ is there any cloud service where we can test the driver? Or maybe a standalone version of OceanBase?

Sorry for the late reply. If you want to test the driver, please see [this](https://github.com/oceanbase/oceanbase/blob/master/docs/docs/docs-en/quick-start-en.md). It's our quick-start introduction.
