### ISSUE TITLE
INSERT and UPDATE with DEFAULT in Oracle and some other DBs.

### ISSUE THREAD

**Issue by plmmihail** [dbeaver/dbeaver#13598]
**Is your feature request related to a problem? Please describe.**
No support for INSERT INTO ... (...) VALUES (v1, DEFAULT, v2, v3, DEFAULT, v4 ... ) in Oracle
See context in https://github.com/dbeaver/dbeaver/issues/13493#issuecomment-902500177

**Describe the solution you'd like**
Behavior by SQL standard.

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by LonwoLonwo** [comment]
The feature is implemented for ORACLE and other Databases, which do not support INSERT INTO DEFAULT VALUES for the Insert all empty values in the row. In DBeaver 22.0.0.

**Comment by Matvey16** [comment]
Verified
