### ISSUE TITLE
Blob field content view Chinese garbled characters.(blob内容查看中文乱码)

### ISSUE THREAD

**Issue by PDMoFan** [dbeaver/dbeaver#13593]
Database encoding format（数据库编码格式）:
![image](https://user-images.githubusercontent.com/40638512/130171634-ec01355d-0a06-4dbe-a6d8-8ec48d0a6579.png)
Blob field content view（Blob内容查看）：
![image](https://user-images.githubusercontent.com/40638512/130171921-e9bbc13d-e11c-4a5f-988e-66eab182ddf3.png)

**Comment by PDMoFan** [comment]
表的字符集和字段的类型：
![image](https://user-images.githubusercontent.com/40638512/130172556-e62e9821-b20d-47ad-ad0b-ebba4554577c.png)

**Comment by PDMoFan** [comment]
The character set and field type of the table（表的字符集和字段的类型）：
![表字符集](https://user-images.githubusercontent.com/40638512/130172678-a74dd0dd-59ca-41d1-8378-a572630caa9b.png)

**Comment by PDMoFan** [comment]
The database above is Mariadb. This is the Oracle database. Is the same Chinese garbled code.（上面的数据库是mariadb。下面这个是oracle数据库。也是一样的中文乱码。）
![image](https://user-images.githubusercontent.com/40638512/130173820-107b99bb-a49b-4196-9117-050659aed11a.png)
Table Spaces and field types（表空间和字段类型）：
![image](https://user-images.githubusercontent.com/40638512/130173653-065dfaa1-b1a8-4d8e-b6b4-6c0ac1cba51d.png)

**Comment by ShadelessFox** [comment]
@PDMoFan thanks for bug report, but please translate your comments to English.

**Comment by PDMoFan** [comment]
@ShadelessFox 
The contents have been translated into English, and the contents in parentheses are Chinese translations.

**Comment by ShadelessFox** [comment]
Thanks!

**Comment by ShadelessFox** [comment]
Now you can change encoding for text editor. Will be available in DBeaver 21.2.4.

![java_Fm0h4vArGQ](https://user-images.githubusercontent.com/35821147/138310936-3951b4a6-95e3-47ca-a313-aea20708434c.png)

**Comment by Matvey16** [comment]
Verified
