### ISSUE TITLE
Shortcut for activation of pattern editing in Data Formatting

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13599]
This editable field activates only by double click. It would be great to have a shortcut for such of fields
![image](https://user-images.githubusercontent.com/43252954/130229094-06feb2db-10c9-46e5-a2b8-56b1230838d5.png)

**Comment by serge-rider** [comment]
<kbd>Enter</kbd> key must work now

**Comment by Matvey16** [comment]
Verified
