### ISSUE TITLE
Native Client missing - 

### ISSUE THREAD

**Issue by glmarsh** [dbeaver/dbeaver#13608]
#### System information: 
- Operating system : Ubuntu 21.04
- DBeaver version  :  21.1.5.202108160727
- Java version        :  1.8.0_221
- Additional extensions

#### Connection specification:
- Database name and version  :  MySQL community version 8.0.26
- Driver name                           :  mysql connector/J8.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When right clicking the database and right clicking Tools->Restore database the database import dialog shows the message "Native client is not specified for connection".  When selecting the "Local Client" button I am presented with a dialog that expects me to navigate or browse to the directory holding the client programs. The client programs are located in /usr/bin but the dialog browser doesn't allow you to input that location.

**Comment by uslss** [comment]
#10320

**Comment by Matvey16** [comment]
@glmarsh What type of Dbeaver package are you using?

**Comment by glmarsh** [comment]
Community version 21.1.5 on Ubuntu 21.04.Sent from my Galaxy
-------- Original message --------From: Matvey16 ***@***.***> Date: 8/26/21  3:59 AM  (GMT-08:00) To: dbeaver/dbeaver ***@***.***> Cc: glmarsh ***@***.***>, Mention ***@***.***> Subject: Re: [dbeaver/dbeaver] Native Client missing -  (#13608) 
@glmarsh What type of Dbeaver package are you using?

**Comment by Matvey16** [comment]
@glmarsh 
I was not able to reproduce this issue. Can you tell me if you doing it as I am.
1. Click "Local client"
2. Select "Browse"
3. Click "Add home"
4. Navigate to /usr/bin and click "Open"

**Comment by uslss** [comment]
there is no update for a long time.
If it is still actual - feel free to reopen the issue.

**Comment by appsol** [comment]
@uslss @Matvey16 +1 this issue
Ubuntu 20.04LTS
DBeaver Version 21.2.2.202110030714

1. Click "Local Client"
2. Select "Browse"
3. Click "Add Home"
4. Navigate to /usr/bin
When I navigate to /usr, I get the message:
"Could not read the contents of usr. Error opening directory '/usr': Permission denied"

**Comment by Matvey16** [comment]
@appsol And do you have permission to open /usr directory?

If you installed DBeaver from Ubuntu software you won't be able to gain access to that directory, because it is snap restriction and we can't do anything about it. To use your local MySQL client you need to manually install DBeaver with deb package or from launchpad with apt-get

**Comment by appsol** [comment]
@Matvey16 Yes I can access it, but that makes total sense. I'll reinstall using apt and try again. Thanks.

**Comment by glmarsh** [comment]
I failed to mention that I had installed DBeaver through snap.  After removing the snap installation and installing using apt I was able to add the client home.  Snap and it's DBeaver installation was the problem.

**Comment by appsol** [comment]
I have now re-installed DBeaver using apt and can confirm I can access the client home without issue now.

**Comment by kylemanleydev** [comment]
Confirmed removing snap fixed this issue

**Comment by mrtampan** [comment]
### Check Locate native client
- Install mysql
- Open terminal, then type `which mysql`
result: "/usr/bin/mysql"

### Fix native client is not specified for connection
- Click "Local client"
- Select "Browse"
- Click "Add home"
- Navigate to locate mysql (default: `/usr/bin`) and click "Open"

**Comment by allanlaal** [comment]
@dbeaver-devops  could you make it automatically add every linux `$PATH` there?

**Comment by bertalanimre** [comment]
How is this still an issue with this after so many years with the SNAP installed version?
