### ISSUE TITLE
Redshift specific functions and keywords aren't highlighted in a different color

### ISSUE THREAD

**Issue by deepaksenthilkumar** [dbeaver/dbeaver#13606]
**Is your feature request related to a problem? Please describe.**
Some of the Redshift-specific functions, keywords are not indicated in a different color in the SQL editor.

Some of the examples are:
"SYSDATE"
"COPY",
"DATASHARE",
"LIBRARY",
"MATERIALIZED",
"MODEL",
"REFRESH",
"UNLOAD",
"VACUUM"
"NVL",
"NVL2"
**Describe the solution you'd like**
We can add PostgreDialect to support Redshift-specific keywords and functions.

Current Behavior:
![image](https://user-images.githubusercontent.com/36084950/130331409-1346a09c-4260-416b-a3a3-f1694d12358b.png)

Expected Behavior:
![image](https://user-images.githubusercontent.com/36084950/130331422-c1216d0b-4297-43f2-998a-4a59a518f2f2.png)

Initially, we can add the keywords/functions listed here and eventually cover all the keywords/reserved words/functions in
https://docs.aws.amazon.com/redshift/latest/dg/cm_chap_SQLCommandRef.html

**Comment by uslss** [comment]
verified
