### ISSUE TITLE
Mock data generation NPE

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13601]
#### Steps to reproduce, if exist:
Start mock data generation

**Actual result:** NPE is thrown and data can't be generated

![dbeaver_HCFQbiC8c2](https://user-images.githubusercontent.com/82543000/130242113-7557462d-3443-47e0-b9a9-d1ca390430ae.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
