### ISSUE TITLE
erroneous sql when first part of a record filter is entered manually and the second part graphically

### ISSUE THREAD

**Issue by JeroenNienhuis** [dbeaver/dbeaver#13616]
#### System information: 
- Operating system Windows
- DBeaver version 21.1.4

#### Describe the problem you're observing:
Records in the datagrid can be filtered. The filter settings can be entered by using the graphical interface and through manual input. When a filter is based on 2 fields the total filter string is a concatenation with " AND " as a separator, e.g.
(project_id IN (29)) AND (year IN (2020))
When I want to select on 2 fields and enter the first manually, e.g.
project_id in (29)  
and  use the graphical interface for further selection the result is e.g.
age_ringing_id IN (2)project_id in (29)
The result gives an error, because the " AND " between both parts of the filter is missing.

**Comment by ShadelessFox** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
