### ISSUE TITLE
"Client home is not specified for connection"

### ISSUE THREAD

**Issue by MrBrax** [dbeaver/dbeaver#1361]
You really gotta specify what this means in the export database window, i have no idea what to set, and no idea what it's about either.

I can't export it because of this (i think).

**Comment by serge-rider** [comment]
Native client home can be set in connection properties (first page).

**Comment by MrBrax** [comment]
@serge-rider hmm?

![1488283202295](https://cloud.githubusercontent.com/assets/1517911/23404557/e4bee17a-fdb5-11e6-9083-a22bdc223795.png)
![1488283191881](https://cloud.githubusercontent.com/assets/1517911/23404556/e4b344be-fdb5-11e6-9428-e40b875927a8.png)

**Comment by serge-rider** [comment]
"Local client" combo. It is empty if there is no native client installed on your machine (or DBeaver can't find it). 
You can specify path where mysqldump resides manually (Browse->Add home).

**Comment by serge-rider** [comment]
Because this is native mysql tool. It is different for every MySQL version and every platform.
And this is extended functionality. 

If you don't have MySQL client (or you don't want to bother with this stuff) then you can use data export (which doesn't require any native tools).

**Comment by MrBrax** [comment]
I guess I'm too used to other MySQL tools then, which have it built in.

This IS my MySQL client, I can change data and create databases etc. The only way to get that mysqldump.exe as far as i can see, is downloading a 350MB zip file from oracle.

**Comment by serge-rider** [comment]
Some MySQL UI clients may have builtin mysqldump, mysqlrestore, mysql.exe + set of libraries of some particular MySQL client version.
But DBeaver definitely not one of such clients.

On Windows you can install MySQL Workbench (it includes all command line tools). DBeaver will find it automatically.
On Linux you can use something like `apt-get install mysql-client`

**Comment by MrBrax** [comment]
...i'll just use one of the other tools for exporting

**Comment by serge-rider** [comment]
Sure.
DBeaver dump/restore functions are for lazy people who want to use one client for all tasks. And who don't like MySQL Workbench.

**Comment by javirebu** [comment]
i use phpmyadmin on xampp from the beggining and now dbeaver for mongo mysql...etc, so XAMPP/mysql/bin has all mysql command line executables. And i like to import a 400mb sql dump, and update my development copy... it is very usefull to import a sql dump,,, maybe dbeaver should include this command line files....

Im using xampp/mysql  and is working perfectly


![dbeaverxampp](https://cloud.githubusercontent.com/assets/27858260/25279429/ba5a3a78-26a6-11e7-80c4-7320bdc79dc6.png)

**Comment by serge-rider** [comment]
Well, this looks wrong.
1. You should set home to `c:\xampp\mysql` - not to bin folder.
2. When you click on home in the left panel there should be some information about it in the right panel. Otherwise this is some bug and I'll need error/debug logs (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by javirebu** [comment]
Welll... wrong are you. It Is working fine... and of course...
xampp/mysql/bin... were mysql.exe and mysqldump.exe are

**Comment by javirebu** [comment]
Serge c:\xampp\mysql works fine too. Intead of this folder does not contain mysql executables  :+1:

**Comment by paulbrzeski** [comment]
This issue is still valid - I found this thread because of the error.

Can you guys please fix the error message? Just put something useful in there like "error: mysqldump missing, please fix in config"

**Comment by serge-rider** [comment]
Yep, there was a bug in MySQL binaries location detection. See fix in the next version

**Comment by vveettil** [comment]
downloaded MySQL 5.6.37 macos version and attached to dbeaver (3.8.4) db connection local client path. mysqldump is working fine.

**Comment by sandorspruit** [comment]
I just installed DBeaver 4.2.3 and I still see this issue. Must be something I am missing, but what?

**Comment by javirebu** [comment]
for me c:\xampp\mysql and c:\xampp\mysql\bin both work fine

2017-10-26 12:42 GMT+02:00 sandorspruit <notifications@github.com>:

**Comment by alesanfer** [comment]
I followed this steps on the Mac: 

1- find the mysql path install
```
MacBook-Pro:~ root# find /usr/ -iname "mysql"
/usr//local/mysql
/usr//local/mysql-5.7.17-macos10.12-x86_64/bin/mysql
```
2 - Open Edit connection settings and click on Browse on Local Client

<img width="726" alt="captura de tela 2017-10-28 as 20 58 53" src="https://user-images.githubusercontent.com/2980646/32139278-0a404b38-bc23-11e7-8caa-92dcc8df0bea.png">

3 - After that click in add home button then use the `Command+Shift+G` for open the prompt for input the Mysql path location.

<img width="699" alt="captura de tela 2017-10-28 as 20 59 24" src="https://user-images.githubusercontent.com/2980646/32139279-0a6f12c4-bc23-11e7-8af3-8a1580875e3d.png">

Done, its works fine for me!

**Comment by BornToDrink** [comment]
A local mysql client is needed and by default is not selected in connection properties.
So on Linux Mint I did the same as @alesanfer said: just selected "/usr" in "Local Client" row and it works good.

**Comment by ztl8702** [comment]
Can confirm that on Windows installing MySQL Workbench works.

**Comment by chriszrc** [comment]
Yeah, similarly for postgres, you hit "Browse" for local client, and put in the path where the pgdump/restore executables live on your system. If you're using Postgres.app, it's:

`/Applications/Postgres.app/Contents/Versions/latest/bin`

**Comment by GeeeCoin** [comment]
Why is a local client necessary? I'm connected to my database remotely and just need a path to store my dump file. Is there a reason I need one locally?

**Comment by chriszrc** [comment]
@GeeeCoin afaik, you could of course ssh to your remote db server and use the export tools on that machine, but typically, if the goal is to create the backup file on your local machine, then you would use the tools on your own machine and point it at the remote db. 

Even though you're "connected" to your remote db, the import/export tools are usually separate from what's exposed directly over the db connection-

**Comment by serge-rider** [comment]
After all I'm thinking about inclusion of native tools (pg_dump/pg_restore and mysql/mysqldump) into DBeaver distribution. Some DB clients do this, we also could try. Thus we won't need this native client configurations at all.
However this will require to include at least 3 versions of these binaries (Windows/Linux/MacOS).

**Comment by serge-rider** [comment]
And this is more than 10Mb of binaries just for one OS. 
Combined it is close to full DBeaver CE distribution size :(
But can be solved with automatic binaries download from DBeaver website. While EE may include them by default. Need to think about that.

Please vote if you think this makes sense..

**Comment by p91paul** [comment]
automatic download (more or less what happens with db drivers) seems a good way. Power users should be left the option to don't download them and just use the ones they already have installed.

**Comment by jesstelford** [comment]
To get dbeaver data export working on OSX with PostgreSQL, I followed these steps:

## Find the PostgreSQL install path

If you used homebrew to install postgresql:

```
$ brew info postgresql
...
/usr/local/Cellar/postgresql/10.3 (3,383 files, 39.2MB) *
...
```

If you installed via the installer package, the location is:

```
/Applications/Postgres.app/Contents/Versions/latest/bin
```

## Add the location to the database config

![dbeaver-config](https://user-images.githubusercontent.com/612020/39845701-b1e2dd60-543a-11e8-90ed-62f424f0b31f.gif)

Right click the top-level connection in the "Database Navi" pane (on the left), and select "Edit Connection"

<img width="335" alt="screenshot of right-clicking top-level database" src="https://user-images.githubusercontent.com/612020/39845563-ec68a560-5439-11e8-8254-22aea82953a8.png">

Click the empty drop-down next to "Local Client", then click "Browse" from within the dropdown.

In the popup, click "Add Home", which will show a file-selector prompt.

Press `Command+Shift+G`, then paste in the PostgreSQL install path.

Hi Ok, Ok, Ok.

## Export / Backup

Expand the top-level connection in the "Database Navi" pane (on the left), then right click on the database name you want to export/backup.

Select Tools > Backup.

In the popup, select at least one item from the "Objects" section, then the individual items you want to export from the second section.

Click "Next" (not "Start") to select the directory to save to, by editing the "Output folder" option.

Click "Start" to generate the export.

**Comment by erlangp** [comment]
@jesstelford thanks sir

**Comment by maphew** [comment]
To anyone confused by this process and message on first encounter like me: 

- Edit connection settings
- On first screen there is [Local Client] drop down, choose 'MySQL Binaries' and save connection. 

Nothing happens at this point, it's ok. 

- Navigate to a db then _"Tools >> Dump"_. Select as you like and [Next] through the wizard. When you [Start] _now_ dbeaver will download and install the binaries. It's pretty quick and painless from here.

**Comment by ridhoashari** [comment]
In ubuntu make sure you install local client
- apt install mysql-client

In dbeaver when you browse local client choose this folder
- /usr/bin/

**Comment by hagabaka** [comment]
I think rather than including the native tools or providing automatic downloads for them, DBeaver just needs to explain clearly what "Client Home" means in the dump database wizard, and provide a quick way to configure it from there.

**Comment by serge-rider** [comment]
@hagabaka Totally agree about better explanation and easier config. However I still think we should keep providing auto-download of client files.
#5716

**Comment by brooke-heaton** [comment]
This functionality is utterly stupid.

**Comment by brooke-heaton** [comment]
Wow. I really really really miss SequelPro. Ugh.

**Comment by brooke-heaton** [comment]
Please stop this madness and make this user friendly.

**Comment by seugenev** [comment]
ok guys, im using Docker for mysql ....
and how should i specify mysqldump file location ?
even if you find a way to specify path ( dont say me it will be "docker exec" ...) i should change it all the time for the every container ?

**Comment by serge-rider** [comment]
Now we provide automatic client download for Windows (for PostgreSQL and MySQL). But not for MacOS yet (as it is a bit more complicated to use raw binaries there).
Anyway, if you think this makes sense - please create a feature request.

@seugenev  And I agreed that we need global configuration for this. Just made a FR (#5779).

**Comment by MrBrax** [comment]
Application has been improved a lot. Since i made this question I've set it up properly and it works great!

Completely stopped using SQLYog since then.

**Comment by Nosherwan** [comment]
@seugenev did you figure out how to solve your issue.
I am having the exact same issue.
I have specified client home correctly for `mairadb`, however the instance I connect to is inside docker.
For my local instance the `dump database` option works fine. However for the docker instance it gives the following error:
<img width="662" alt="Screen Shot 2019-05-01 at 3 51 17 pm" src="https://user-images.githubusercontent.com/138489/57007132-9aea0e00-6c29-11e9-8a9b-132959ec666d.png">
I would appreciate any help thanks. :)

**Comment by seugenev** [comment]
> @seugenev did you figure out how to solve your issue.
> I am having the exact same issue.
> I have specified client home correctly for `mairadb`, however the instance I connect to is inside docker.
> For my local instance the `dump database` option works fine. However for the docker instance it gives the following error:
> <img alt="Screen Shot 2019-05-01 at 3 51 17 pm" width="662" src="https://user-images.githubusercontent.com/138489/57007132-9aea0e00-6c29-11e9-8a9b-132959ec666d.png">
> I would appreciate any help thanks. :)

hello, yes, i found how to solve the issue.
i'm using phpMyAdmin when i need dump of course as a docker container :D

**Comment by Nosherwan** [comment]
Ok thanks. I am on mac and I used sequel pro, easiest tool to backup mysql/mariadb.

**Comment by Sanal567** [comment]
For Postgres SQL installed using Enterprise DB installer on Mac OS, pg_restore will be located in "/Library/PostgreSQL/10/bin".. So select this location in DBeaver, it worked for me..

**Comment by carlosedof** [comment]
If you are using postgre installed with brew on mac, just add native client url: /usr/local/bin and it will locate the postgre binary. Worked fine for me.

**Comment by tpoxa** [comment]
removed this PoS

**Comment by visualex** [comment]
I know this has been explained before, and I'm fine using the tools that are available elsewhere. 
I think that this use-case can be useful to the developers. 
I have a remote db server, and i have a local one where i want to import a dump. 

However, 
the local server is in a docker container (you can only access the filesystem on a linux docker host). 
It would be great to be able to use the remote mysqldump if the connection is over ssh. 
just 2c.

**Comment by mayank-kapoor** [comment]
@serge-rider any solution for postgres running in docker. how can we provide native client path for pg_dump/pg_restore  while restoring the data. it is not mac but linux distribution and does not automatically downloads the libs as quoted [here](https://github.com/dbeaver/dbeaver/issues/1361#issuecomment-485921685l)

**Comment by firanto** [comment]
In MacOS, we need to point mysql installation to `/usr/local/mysql-5.7.15-osx10.11-x86_64`. The problem is, when we browse it, the `/usr` directory is not visible. Either we have to make it visible to Mac UI, or we create symbolic link to that directory, i.e. `ln -s /usr/local/mysql-5.7.15-osx10.11-x86_64/ mysql-5.7.15-osx10.11-x86_64` to any location we like (mine is `~/UserLib`).

**Comment by toastyghost** [comment]
> Sure.
> DBeaver dump/restore functions are for lazy people who want to use one client for all tasks. And who don't like MySQL Workbench.

Dev of database UI app: "You are lazy for using a database UI app"

k

**Comment by medioseureka** [comment]
This is nonsense, what about if I don't want to install MySQL locally because I have docker installed

**Comment by u007** [comment]
i have the same problem on popos even thou my /bin/mysqldump exists and even /usr/bin/mysqldump exists

**Comment by teol** [comment]
Same here. I can't even write the custom path myself, I need to select a folder that exists but it doesn't as the MySQL server is in a container...

**Comment by serge-rider** [comment]
Unfortunately it is not possible to use remote version of dump/restore utilities.
They are just binaries, they must be invoked directly.
It is also not possible to access them from docker container (as container file system is isolated).

So the only solution is to have them locally. On Windows we download them on demand. On MacOS it is not really possible (because of MacOS security policy).

You can install local client via brew (`brew install mysql-client`). 
More details: https://stackoverflow.com/questions/47380458/is-it-possible-to-install-only-mysqldump-on-macos

**Comment by serge-rider** [comment]
> Dev of database UI app: "You are lazy for using a database UI app"

Yep. At least I'm quite a lazy person and I love UI :)

**Comment by yanike** [comment]
On Ubuntu 20.04 LTS using MySQL:
- Make sure mysql-client is installed and mysql-server (always good to have both for local development).
- You can install them using terminal `sudo apt-get install mysql-client` and `sudo apt-get install mysql-server`
- Open DBeaver. If you are reading this and don't have DBeaver installed, you can get it using software manager. I recommend Flatpak ( https://flatpak.org/setup/Ubuntu/ ) over Snap, but that's my preference.
- Create New (File > New > DBeaver > Database Connection > MySQL) or Edit MySQL Database Connection.
- Go to Local Client > Browse.. > Add Home
- Add folder "/usr/bin" (Computer > usr > bin) [mysqldump will be found here]
- Click the folder you just added in the list to the left to populate the fields to the right.
- Enjoy!

**Comment by KevinBarbier2** [comment]
Version 21.2.0.202108291732

```
[root@fedora]# which mysqldump
/usr/bin/mysqldump
```

- When trying to edit local client config, browsing to /usr/bin to select mysqldump shows a blank.
- Trying to fill in path also doesn't work, doesn't register anything i type into it.

**Comment by tyoc213** [comment]
for postgres

`find / -name "pg_dump" 2>/dev/null` and set the path to the local client

**Comment by goul4rt** [comment]
> I followed this steps on the Mac:
> 
> 1- find the mysql path install
> 
> ```
> MacBook-Pro:~ root# find /usr/ -iname "mysql"
> /usr//local/mysql
> /usr//local/mysql-5.7.17-macos10.12-x86_64/bin/mysql
> ```
> 
> 2 - Open Edit connection settings and click on Browse on Local Client
> 
> <img alt="captura de tela 2017-10-28 as 20 58 53" width="726" src="https://user-images.githubusercontent.com/2980646/32139278-0a404b38-bc23-11e7-8caa-92dcc8df0bea.png">
> 
> 3 - After that click in add home button then use the `Command+Shift+G` for open the prompt for input the Mysql path location.
> 
> <img alt="captura de tela 2017-10-28 as 20 59 24" width="699" src="https://user-images.githubusercontent.com/2980646/32139279-0a6f12c4-bc23-11e7-8af3-8a1580875e3d.png">
> 
> Done, its works fine for me!

This is working fine 19/02/2022
Just need install mysql before start the process in your comment.
`brew install mysql`

**Comment by githubcdr** [comment]
What a sad world, having to spend 20 minutes to get the local client defined in MacOS using some shady shortcut. Overall we the people, lost, computers won.

**Comment by u007** [comment]
same here, i couldnt get backup n restore to work, i abandon this

**Comment by flambchap** [comment]
Hi @u007 @githubcdr. We believe that we can improve the backup/restore experience. Could you please share what obstacles you've met? We would like to use your input in designing a new UI/UX.

**Comment by u007** [comment]
i think recent changes is that the binary is no longer a single binary, its sort of a link to somewhere in my popos 21.10
no matter what i set in the binary path, it can never work

i just found this issue, havent manage to get it working yet
https://github.com/dbeaver/dbeaver/issues/5008

iam using flatpak

**Comment by maoschanz** [comment]
![Capture d’écran de 2022-05-05 15-12-23](https://user-images.githubusercontent.com/19996113/166930635-fd31d3d6-ad8f-4e62-8f31-f3a0ea6ad71c.png)

aside of the insanely convoluted workflow (4 levels of modal dialog windows ??), maybe you could address the fact that we can't select any binary at all

edit: nevermind, this dialog is to select a "home" which is a directory. ~~The binary path has to be written manually, without any filepicker to help, in the level 3 dialog. Which is bugged too, i can't write anything in any of those inputs.~~ edit2: ok i made it work. So this is about finding binaries, but we're not supposed to provide binaries at all. Very intuitive.

Next time, you may look up what the $PATH env variable is for

**Comment by LuisPortanel** [comment]
I managed to solve this in Ubuntu. You only need to install the mysql-client and add the installation path in DBeaver:

1. `sudo apt install mysql-client`
2. Run `which mysql` to find the installation path. For me it was `/usr/bin/mysql`
3. Add the installation path as a Client Home. You need to click "Add Home", then add `/usr/bin` and that's it. DBeaver will autofill all the inputs.
![image](https://user-images.githubusercontent.com/6484603/212520839-b5905de6-d69e-4034-a84a-33e678bc7569.png)

Hope anyone finds this useful.

**Comment by RamonGiovane** [comment]
> It is also not possible to access them from docker container (as container file system is isolated).

What if we had an option to specify the container name instead of referencing the local client path, and DBeaver just runs `docker exec` internally? Is it even possible?

**Comment by flambchap** [comment]
@RamonGiovane It would be cool, but it's unclear how to access the results of this command as they'll be inside the container.
