### ISSUE TITLE
“连接名称” 放在 常规配置

### ISSUE THREAD

**Issue by SSSDNSY** [dbeaver/dbeaver#13619]
![image](https://user-images.githubusercontent.com/15624361/130409226-9037fce7-2a6e-4539-a0ca-faea08508a69.png)
**Describe the solution you'd like**
配置“连接名称” 这个配置应该放在常规配置里面，而不是点开菜单。对于其他的客户端软件，这个是跟数据库url,用户，密码 在同一个窗口的，dbeaver还得多点一下。期待优化这个。

**Comment by SSSDNSY** [comment]
Configure Connection Name This configuration should be placed in the general configuration, not in the open menu.For other client software, this is in the same window as the database url, user, password, dbeaver a little more.Look forward to optimizing this.

**Comment by uslss** [comment]
will be implemented in the scope of #13127 
thanks for the suggestion

**Comment by SSSDNSY** [comment]
ok
