### ISSUE TITLE
Data formatting settings from db context menu and from table settings aren't synchronized 

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13618]
#### System information: 
- Win10, DBeaver 21.1.5

#### Describe the problem you're observing:
Can't change formatting though context menu
#### Steps to reproduce:
Open table with float numbers
Set local language settings through settings button 
Change local language settings through database menu. Select language, for which format of numbers will look different
Reconnect
Check how the numbers and settings look in two different places
Expected: settings are the same in two places and number formatting displayed accordingly
Actual: settings are different, data formatting hasn't changed

https://user-images.githubusercontent.com/43252954/130406220-aa2347fe-066e-4522-8618-05af178cbe0b.mp4

**Comment by LonwoLonwo** [comment]
Can't reproduce against in DBeaver 21.3.5. Probably fixed in the scope of this ticket: https://github.com/dbeaver/dbeaver/issues/13585

**Comment by DariaMarkaryan** [comment]
no longer reproduced
