### ISSUE TITLE
Menu bar in SQL script results not clickable after upgrade to 21.1.5

### ISSUE THREAD

**Issue by perry-mitchell** [dbeaver/dbeaver#13617]
#### System information: 
- Ubuntu 21.04
- DBeaver 21.1.5
- No additional extensions

#### Connection specification:
- MySQL
- No tunnels or proxies (local database)

#### Describe the problem you're observing:

After upgrading to 21.1.5 from 21.0.4, the menu bar below the results pane when entering custom SQL queries doesn't accept mouse clicks. Hints still appear when hovering, but the buttons do not activate when clicked. I am not able to save changes made in this pane, whereas I was able to in the previous version.

![image](https://user-images.githubusercontent.com/3869469/130399843-a6c8a76e-9904-4717-81cd-46a14e2dfc92.png)

Additionally, the [log file instructions](https://github.com/dbeaver/dbeaver/wiki/Log-files) are incorrect for Ubuntu 21.04 - I have no log files at the location specified. I did find the directory `/home/user/.eclipse/org.jkiss.dbeaver.product_21.1.5_302967072_linux_gtk_x86_64/configuration`, but there were no logs recorded here (according to the naming in the instructions).

**EDIT**: I did close/re-open the app, and try resizing the window in case it was a graphical glitch.. both to no avail.

**Comment by uslss** [comment]
thanks for the report
duplicates #13636
