### ISSUE TITLE
Error during saving changes in view with comments (Oracle)

### ISSUE THREAD

**Issue by plmmihail** [dbeaver/dbeaver#13627]
#### System information: 
- Operating system (distribution) and version
Linux Mint, Fedora
- DBeaver version
2.1.5
- Additional extensions
No
#### Connection specification:
- Database name and version
Oracle 10i
- Driver name
Maven artifact from DBeaver's collection
![изображение](https://user-images.githubusercontent.com/75296351/130436022-5e592e48-34ba-44c2-bfba-03c2c4cd8cd2.png)

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No
#### Describe the problem you're observing:
For a view with comments
![изображение](https://user-images.githubusercontent.com/75296351/130436103-b1d851a2-2667-4a52-a8e8-bd1eaea55423.png)
...
![изображение](https://user-images.githubusercontent.com/75296351/130436374-0e6a6389-ed66-4f86-b600-bd446913e0ca.png)
During changing the main DDL of a view
![изображение](https://user-images.githubusercontent.com/75296351/130436548-3f14b292-2e4f-4eb8-879e-03268583dd4a.png)
because DBeaver use single-command mode where not allowed `;`
#### Steps to reproduce, if exist:
1. Create a view like `SELECT 'a' f1, 1 f2 FROM DUAL;`
2. Comment a view
3. Comment a columns of a view
4. See Declaration DDL for a view (must be main DDL and comments)
5. Change the declarartion
6. Try to save

**Comment by LonwoLonwo** [comment]
Thanks for the bug report.

**Comment by LonwoLonwo** [comment]
We need to execute this type of statement as a script in databases, whose do not support multi-statement execution.

**Comment by LonwoLonwo** [comment]
@plmmihail
As a workaround, you can change the DDL form to compact and then change the view declarartion.

![2021-08-23 18_14_03-DBeaver Enterprise 21 1 5 - TESTCOMMENT](https://user-images.githubusercontent.com/45152336/130472471-abd993e0-da5e-4687-a8ba-8e333beb75ed.png)

**Comment by plmmihail** [comment]
Thanks, @LonwoLonwo ! Comments are lost during using "Compact form" mode.

**Comment by LonwoLonwo** [comment]
Fixed.

![2022-04-05 12_19_30-DBeaver Ultimate 22 0 2 - TEST_SCRIPT](https://user-images.githubusercontent.com/45152336/161726074-9fae4ff3-af21-44ec-8484-5e88305f9169.png)

Now you can change the view definition with comments correctly.

**Comment by uslss** [comment]
verified
