### ISSUE TITLE
GNOME 3.38 runtime no longer supported

### ISSUE THREAD

**Issue by isantolin** [dbeaver/dbeaver#13626]
#### System information: 
- Operating system (distribution) and version: Fedora 34
- DBeaver version: 21.1.4 (Flatpak)
- Additional extensions: No

#### Connection specification:
- Database name and version: No related
- Driver name: No related
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No related

#### Describe the problem you're observing:
I tried to update using flatpak and the following error appears

``
Looking for updates…
Info: org.gnome.Platform//3.38 is end-of-life, with reason:
   The GNOME 3.38 runtime is no longer supported as of August 19, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   io.dbeaver.DBeaverCommunity
``

#### Steps to reproduce, if exist:
- sudo flatpak install flathub io.dbeaver.DBeaverCommunity -y
- sudo flatpak update -y
(That error will appear)

**Comment by atmouse-** [comment]
gnome 3.38 dependency has been removed now.

```
% flatpak update
Looking for updates…
Info: org.gnome.Platform//3.38 is end-of-life, with reason:
   The GNOME 3.38 runtime is no longer supported as of August 19, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   io.dbeaver.DBeaverCommunity


        ID                                    Branch           Op          Remote           Download
 1. [✓] io.dbeaver.DBeaverCommunity           stable           u           flathub          66.8 MB / 155.2 MB
 2. [-] org.gnome.Platform.Locale             3.38             r
 3. [-] org.gnome.Platform                    3.38             r

Changes complete.
```

checked
```
% flatpak list | grep dbeav
DBeaver Community       io.dbeaver.DBeaverCommunity     21.1.5  stable  system
% flatpak list | grep gnome
GNOME Application Platform version 40   org.gnome.Platform              40      system
```
