### ISSUE TITLE
Enablement of Fetch all rows button is broken in 21.1.5, It works in 21.1.4

### ISSUE THREAD

**Issue by deepaksenthilkumar** [dbeaver/dbeaver#13636]
Create a table temp_test_1 with 1 column col1 and 2000 rows, all the records have data as 1 for testing purposes. 

Open a new editor and run select * from temp_test_1.

Data Editor preferences (in case you need)
![image](https://user-images.githubusercontent.com/36084950/130503805-320dc191-36d5-4da0-8b5a-1e5b1cf02fa3.png)

21.1.4
Fetch all rows is enabled
![image](https://user-images.githubusercontent.com/36084950/130502034-e1c51c08-34bc-4238-9d89-609d2daaa956.png)

21.1.5
Fetch all rows is enabled
![image](https://user-images.githubusercontent.com/36084950/130504095-6019c6cf-af52-4405-92bf-698f2e69391c.png)

After doing some operations (querying other tables importing data etc.), it becomes enabled for the same query.

**Comment by LonwoLonwo** [comment]
Thanks for the bug report!
As I can see, buttons will be available if you click on the object in the Navigator Tree, for example.

**Comment by serge-rider** [comment]
It is side effect of #12532 fix. Reverted.

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
