### ISSUE TITLE
Can't open entity 'xxx' Reason：472718807

### ISSUE THREAD

**Issue by yenaikafei** [dbeaver/dbeaver#13637]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.4.4
- Additional extensions

#### Connection specification:
- Database name and version aliyun-mysql select @@version:5.7.30-log
- Driver name mysql:mysql-connector-java:RELEASE[8.0.17]
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
double click datebase table view Procedures will alert the same error

**Comment by uslss** [comment]
@yenaikafei please, provide [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by uslss** [comment]
also, please try to[ reset workspace](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info
