### ISSUE TITLE
Issue during import from .csv

### ISSUE THREAD

**Issue by TsunamiHandia** [dbeaver/dbeaver#13643]
Since version 21.1.4, during import from .csv, an error occurs, the application informs that it can't access to a field in the table, but that field is skipped. I test this in 21.1.4 and 21.1.5. Now I reinstalled version 21.1.3, here the import functionality works fine.

**Comment by LonwoLonwo** [comment]
Hello @TsunamiHandia 

Maybe here is one of your cases? 
https://github.com/dbeaver/dbeaver/issues/13402
https://github.com/dbeaver/dbeaver/issues/13542

**Comment by LonwoLonwo** [comment]
If not - please, tell us more about your OS, data transfer settings, file example, and table DDL example. Screens will be also very helpful.

**Comment by TsunamiHandia** [comment]
When I have time, I prepare a more detailed example.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info
