### ISSUE TITLE
Keyboard re-mapping randomly stops working

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#13659]
DBeaver Community Edition 21.1.5.202108160727
MacOs BigSur 11.4 (20F71)

I use a MAC with external keyboard.

I remapped the "Home" and "End" key to go to the beginning and end OF LINE.
It works.
After some time, something happens, and Home maps to start of FILE, and end to END of files.

Only solution, restart DBeaver. 

This is driving me freaking nuts.
WTH

**Comment by wiwwo** [comment]
Just to be clear: behavior changes without any configuration change, I restart and apply no configuration change. Just good old "turn it off and on again".
I am using a external editor to edit files now.
This is extremely disappointing and just crazy.

PLEASE do not reply with "works in my machine".

**Comment by uslss** [comment]
thanks for the report.
duplicates #9414

**Comment by wiwwo** [comment]
Guys, this is reeeeeeally annoyng :-)
Any plan to fix it? :-)
