### ISSUE TITLE
SSH tunnels configuration wiki

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#13652]
We need page which describes SSH configuration in details.
Somewhere under "Database connections".
There is a very brief description in https://github.com/dbeaver/dbeaver/wiki/Create-Connection , it must contain link to this new page

**Comment by ShadelessFox** [comment]
https://github.com/dbeaver/dbeaver/wiki/SSH-Configuration

**Comment by p91paul** [comment]
my 2 cents: while it looks quite well explained, it might help if you added a few practical examples with IP addresses (fictional of course) that users can relate to. And maybe put a link to the wiki page in the SSH tunnel configuration page of connection settings in DBeaver. It can be quite hard to get it right.

**Comment by ShadelessFox** [comment]
Hello @p91paul,

Thanks for suggestion! I'm not sure about _practical examples with IP addresses_, what exactly do you mean?

**Comment by p91paul** [comment]
@ShadelessFox something along the lines of "Imagine you have your database on IP x.x.x.x on port aaaa and your ssh jump host on y.y.y.y. Then you should set _this_  on ssh settings and _that_  on connection settings"

**Comment by ShadelessFox** [comment]
Interesting. I've written a small paragraph based on your suggestion:
https://github.com/dbeaver/dbeaver/wiki/SSH-Configuration#practical-use

**Comment by p91paul** [comment]
Yeah that should help people stumbling on complicated setups. :smile:

**Comment by uslss** [comment]
verified
