### ISSUE TITLE
Allow changing the URL Template in the Driver Manager only for drivers which support this

### ISSUE THREAD

**Issue by spassignat** [dbeaver/dbeaver#13654]
I use a custom jdbc driver to connect to mysql. Unfortunately, when I setup this driver in the driver manager as Generic, I don't have the support of some MySQL keywords (ex: DELIMITER).

So I tried to setup this driver as a MySQL driver, guessing there are database plugins ;-), but it's impossible to choose the url pattern for these drivers, which makes impossible to connect to the database (obvious).

If this makes sens, could it be possible to choose the url pattern for a driver, to support specific keywords (DELIMITER) ?  Any other solution is welcome.

**Comment by Matvey16** [comment]
@spassignat What do you mean it's impossible to choose the url pattern? It's locked from editing if you try to edit an existing MySQL driver. But if you create a new one, and choose Driver type as MySQL you can change url template however you want.

![dbeaver_t7kEmaRCAS](https://user-images.githubusercontent.com/82543000/130950178-f8b2a2cd-becc-4f4e-af46-fd7a4fa894ac.png)

**Comment by spassignat** [comment]
Ok, you're right, I can set the URL pattern. I was not accurate enough in the case description, but there is still maybe an issue. If we manage to make it work, do you think my strategy will enable mysql features on this custom driver ? 

So I can set the pattern:
![image](https://user-images.githubusercontent.com/6451374/130979160-9f4d4317-7526-494c-b0d1-e20182af8e43.png)

I can also setup a connection using this driver:
![image](https://user-images.githubusercontent.com/6451374/130979452-7a220222-53ae-445c-b6b3-9fd98e39fc5a.png)

When I connect, I have this screen:
![image](https://user-images.githubusercontent.com/6451374/130979958-d0a53c4f-ab6b-4e12-b53c-c879455dff3f.png)

If I look in dbeaver log file, I obtain this: (the url pattern is just skipped and the default url of mysql driver is used)
```2021-08-26 16:18:24.382 - Connect with 'jdbc:mysql://Mint-Precision-M6500:8190/tesjdbc' (09AE85EE-C7DF-AC10-DA0F-C867EB2EB954-17b82d380ef-5eca0cb14b9eb73d)
2021-08-26 16:18:24.382 - Execution context opened (jdbc:mysql://Mint-Precision-M6500:8190/tesjdbc; Main; 10)
2021-08-26 16:18:24.383 - Bad URL: jdbc:mysql://Mint-Precision-M6500:8190/tesjdbc
2021-08-26 16:18:24.383 - Connection failed (09AE85EE-C7DF-AC10-DA0F-C867EB2EB954-17b82d380ef-5eca0cb14b9eb73d)
org.jkiss.dbeaver.model.exec.DBCException: Null connection returned
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:210)

**Comment by uslss** [comment]
@spassignat usually this error appears if URL is incorrect.
https://docs.progress.com/bundle/datadirect-connect-jdbc-51/page/Connection-URL_9.html

**Comment by spassignat** [comment]
Please have a look at the first screen shot.
The url template specified is jdbc:datadirect: ... the one dbeaver uses is jdbc:mysql:

**Comment by spassignat** [comment]
hello, 

are there any progress on this request ?

thanks

**Comment by flambchap** [comment]
Hello @spassignat. Under the hood, DBeaver intentionally ignores custom _URL Templates_ for most of our drivers. We should disable this field for such drivers.

I suggest setting up a Generic or MySQL (Old) driver.

**Comment by serge-rider** [comment]
Now DBeaver will use custom URL whenever it is specified.
Note: you need to create a new driver based on MySQL/PostgreSQL/etc provider to be able to edit URL template.

**Comment by spassignat** [comment]
Hello, that looks great ! thanks.

Will this be available in the next update ?

**Comment by Matvey16** [comment]
Can't edit URL for MySQL and SQL Server drivers, even if they are copies

![JPZ7xbL078](https://user-images.githubusercontent.com/82543000/142813380-0ffa0d60-8a0b-4e19-96a6-9261f5734711.gif)

**Comment by serge-rider** [comment]
@Matvey16 This is not a bug (I think). Copy copies all settings including restriction to edit URL.
Create new driver using MySQL or SQL Server provider and then you can edit URL.

**Comment by Matvey16** [comment]
Verified
