### ISSUE TITLE
table name tab not showing correct name

### ISSUE THREAD

**Issue by alfathard** [dbeaver/dbeaver#13666]
the table tab doesn't display the correct name, instead it displays something like an obscure code or encryption
![Screenshot (147)](https://user-images.githubusercontent.com/71913516/130789532-157effd6-0cd8-47a3-a1ff-5ac1126384de.png)

**Comment by uslss** [comment]
@alfath3724 sorry for the late response.
which locale and language are used in your OS?

**Comment by uslss** [comment]
will be investigated in #13821
