### ISSUE TITLE
Results panel buttons disabled in 21.1.5

### ISSUE THREAD

**Issue by DamijanD** [dbeaver/dbeaver#13662]
In version 21.1.5 buttons on results panel are always disabled. Tested on multiple computers (win10 &  2012R2).

![image](https://user-images.githubusercontent.com/44526436/130767065-41f1f503-0057-40fe-9df0-5f82a4a38bf3.png)

I believe that Save button was already disabled in 21.1.4

**Comment by LonwoLonwo** [comment]
Hello @DamijanD 
Thanks for the bug report.

We already fixed this issue here: https://github.com/dbeaver/dbeaver/issues/13636

Fix will be available in DBeaver version 21.2.0 on 2021-08-30.
