### ISSUE TITLE
Language problem: half English, half Brazilian Portuguese

### ISSUE THREAD

**Issue by murilowippel** [dbeaver/dbeaver#13667]
#### System information: 
- Windows 10
- DBeaver version: 21.1.5.202108160727

#### Describe the problem you're observing:
After updating the software (not exactly to the described version above), some of the menus, buttons and etc were translated to Brazilian Portuguese, although I didn't change the language setting. I tried changing the language to Brazilian Portuguese and then back to English, but when I set to Portuguese, apply and restart the application, it is set to English again, and still half translated.

#### Steps to reproduce, if exist:
Window menu -> Preferência (Preferences) -> User Interface -> Language -> Change to Brazilian Portuguese -> Apply and Restart.

![bug dbeaver](https://user-images.githubusercontent.com/7537602/130789542-a2edec38-0755-47f3-a1a9-056587321cfc.PNG)

**Comment by yennor** [comment]
propably my problem is related. At once dbeaver shows everything in german. not english anymore. (I'm not sure with what update it happened).
I'm using debian testing, with kde.
my locale is:

> LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=de_CH.UTF-8
LC_TIME=de_CH.UTF-8
LC_COLLATE=de_CH.UTF-8
LC_MONETARY=de_CH.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT=de_CH.UTF-8
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

All other programs show the proper languge which should be english. 

in dbeaver.ini no language is set:
> cat /usr/share/dbeaver-ce/dbeaver.ini 
-startup
plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.100.v20210209-1541
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m

**Comment by uslss** [comment]
Unfortunately, translation to non-English languages can be not full, they were made by our contributors.
UI language issue will be resolved in the scope of #12771 .
Close this issue as a duplicate

**Comment by thiagoaf19** [comment]
I have the same problem, can someone help me?
Grateful

**Comment by murilowippel** [comment]
> I have the same problem, can someone help me? Grateful

Thiago, the only solution I've found since I opened this issue is to reinstall DBeaver. You can do this without loosing your personal settings btw. I'm still having this issue sometimes, even after a clean install or updating the existing one.
