### ISSUE TITLE
SQL Format add line if query starts with line comment

### ISSUE THREAD

**Issue by flachtiago** [dbeaver/dbeaver#13671]
#### System information: 
- Win 10 Pro
- DBeaver version: 21.1.3

#### Describe the problem you're observing:
If a query starts with a line comment everytime I press Ctrl+Shift+F (or using the equivalent option from the menus)  the whole query is moved one line down. It doesn't happen if the query starts with a block comment, though.

#### Steps to reproduce, if exist:
- Paste this query in the editor.
```
-- comment
SELECT
	*
FROM
	TABLE;
```
- Press Ctrl+Shift+F and it will be moved one line down.

**Comment by uslss** [comment]
thank you for the report

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.3.3

![MLUSP8eXnr](https://user-images.githubusercontent.com/45152336/148968491-59cb3284-4841-41f6-8c26-3141e1f680c2.gif)

**Comment by Matvey16** [comment]
Verified
