### ISSUE TITLE
Firebird in dbeaver does not hold auto-increment of the table and does not let you edit "nothing"

### ISSUE THREAD

**Issue by EdvanBatist** [dbeaver/dbeaver#13674]
Boa Tarde...

Não consigo criar tabela com auto incremento no Dbeaver... o mesmo permite marcar a opção na coluna ID, porem ao persistir(Guardar), ele desmarca... e também não permite edição das opções mencionadas acima... já com sql server, tudo funciona. O PROBLEMA É SÓ COM O FIREBIRD.
```
Good afternoon...

I can't create table with auto increment in Dbeaver... it allows to mark the option in the column ID, however when persisting(Save), it unmarks... and also does not allow editing of the options mentioned above... already with sql server , everything works. THE PROBLEM IS WITH THE FIREBIRD ONLY.
```

![TELA 1](https://user-images.githubusercontent.com/68394751/130850359-e0ee5e4b-0ff3-4d91-ba0f-d5e42c9d6ee6.png)
![TELA 2](https://user-images.githubusercontent.com/68394751/130850365-edabfdb2-7a8d-4885-b6d1-66a87419ce3c.png)
![TELA 3](https://user-images.githubusercontent.com/68394751/130850369-bad0811d-2806-403d-8f5a-aa9a7265f37a.png)
![TELA 4](https://user-images.githubusercontent.com/68394751/130850375-7cc47bd7-1745-4616-a657-e468b4e79f52.png)

**Comment by uslss** [comment]
thank you for the suggestion

**Comment by LonwoLonwo** [comment]
Support for auto-increment columns field implemented for Firebird (version >= 3) and Vertica databases.

Important note: Vertica supports only one column in the table with the IDENTITY annotation: https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/AdministratorsGuide/Sequences/AutoIncrementIdentitySequences.htm

![2022-02-10 22_50_46-NewTable_3 - Persist Changes](https://user-images.githubusercontent.com/45152336/153551847-27b6631b-8b04-4dc3-bf13-4feda34ccfb0.png)

**Comment by uslss** [comment]
verified
