### ISSUE TITLE
Inactive buttons after data grid at first opening sql editor

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#13673]
#### System information: 
- Windows 10 Pro x64
- DBeaver 21.1.5
- No additional extensions

#### Connection specification:
- PostgreSQL 9.5
- Default postgres driver
- No tunnels or proxies

#### Describe the problem you're observing:
At first opening sql editor and executing sql - buttons after result grid are inactive. Need to move between editors to activate buttons.

#### Steps to reproduce, if exist:
Open new sql editor, execute one or more queries. Try to read new part of data, or edit cell by button.

#### Include any warning/errors/backtraces from the logs
https://user-images.githubusercontent.com/22142845/130828627-bbd787ba-f600-482d-bd0a-388470469c89.mp4

**Comment by ShadelessFox** [comment]
Duplicate of #13636
