### ISSUE TITLE
Netezza DDL statements with COMMENT ON statements

### ISSUE THREAD

**Issue by tapijo** [dbeaver/dbeaver#13680]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a new feature.

**Describe the solution you'd like**
I'd like to see COMMENT ON -statements with database objects DDL statements in Netezza.

**Describe alternatives you've considered**
At the moment you can't see comment on statements with for example in create table statement generated using gui. You have to generate them by you self using Netezza data dictionary.

**Additional context**
Description/Comments Data is stored in Netezza data dictionary at least in next views (and of course in underlying table : DEFINITION_SCHEMA."_T_DESCRIPTION") 
-- table description 
SELECT tablename, description FROM _v_table WHERE tablename ='any tablename';

-- view description
SELECT viewname, description FROM _v_view WHERE viewname  = 'any viewname';
 
-- column descriptions of tables and views colums
SELECT name, attnum, attname, description 
 FROM _v_relation_column WHERE NAME IN ('any tablename', 'any view name') 
 ORDER BY name, attnum
 
It would be very helpful to get that information with object DDLs in Netezza comment statement format.
 
COMMENT ON [ object_type object_name | COLUMN table.col ] IS 'text'
 
COMMENT ON - IBM Documentation:
https://www.ibm.com/docs/en/psfa/7.2.1?topic=reference-comment

We are using dbeaver CE 21.1.4 with 7.2.1.11 Netezza jdbc drivers

**Comment by LonwoLonwo** [comment]
Hello @tapijo 

Ability to change tables, views, table columns, view columns descriptions for Netezza implemented in DBeaver EE version.
Along with the support of synonyms, sequences, unique keys, etc.
You can try it with the trial license version: https://dbeaver.com/

![2021-08-26 14_54_07-NEWVIEW - Persist Changes](https://user-images.githubusercontent.com/45152336/130958638-116241f2-3510-48e1-8dd8-636a8a369f90.png)

**Comment by tapijo** [comment]
Thanks for answer, if the feature will not be available in CE we just have to live without it.
