### ISSUE TITLE
Filter tables doesn't work if table name contain $ or _

### ISSUE THREAD

**Issue by nk54** [dbeaver/dbeaver#13689]
#### System information: 
- Operating system : Windows 10
- DBeaver version : 21.1.5.202108160727
- Additional extensions : none 

#### Describe the problem you're observing:
Filtering the list of tables in the database navigator doesn't work well.
If you work on a database with several hundreds of tables, it's very hard to use it with the current filter.

#### Steps to reproduce, if exist:
Have a database with table named such as :
- SOME$TABLE
- SOME_TABLE1
- SOME_TABLE2
- SOME_$TABLE
- SOMETABLE
- SOME_TABLE$SOME%THING

Try to exclude tables which contains a $ or that start with SOME_
If you try to filter a table by its full name and the name contains a $ or a _, it doesn't work.

Exemple or exclude filter :
*$* (everything gets excluded)
SOME_*
SOME_TABLE$SOME%THING (doesn't filter the table)

Expectations :
either support REGEX format
or fix the compare method

**Comment by Matvey16** [comment]
@Nk54 Thank you for the report, we will work on it.

**Comment by LonwoLonwo** [comment]
Hello @Nk54 
What database do you use?

**Comment by Matvey16** [comment]
@LonwoLonwo Reproducible in PostgreSQL

**Comment by Destrolaric** [comment]
Probably will be fixed with #14648

**Comment by uslss** [comment]
Reopened: include filter is case-insensitive, but exlude filter is case-sensitive

**Comment by uslss** [comment]
verified

**Comment by nk54** [comment]
Hi, the problem occured on Oracle DB but I think it's a bug of the compare method, not the DB provider because the filter works well on Oracle SQL Developper studio.
