### ISSUE TITLE
Redshift connection can't be accessed in CE if it was opened in EE 

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13690]
#### System information: 
- DBeaver version 21.2.0

#### Connection specification:
- Database name and version Redshift, Netezza
- Driver name AWS Redshift jdbc Driver

#### Describe the problem you're observing:
If the connection was created in DBeaver CE and then later opened in DBeaver EE, the driver for the connection will be changed to the one for EE and the connection becomes inaccessible for DBeaver CE.

#### Steps to reproduce, if exist:
1. Create a redshift connection in CE and close Dbeaver
2. Open DBeaver EE and connect to Redshift through this connection
3. Close EE and open CE

**Expected:** The connection is accessible and working like it was before opening EE
**Actual:** The connection can't be opened

![dbeaver_7f2Rq8JPJY](https://user-images.githubusercontent.com/82543000/130977182-b8414656-1e0f-483e-9de0-b142809660de.png)

**Comment by serge-rider** [comment]
It is not a bug. EE version uses different database drivers which are not present in CE version.
Technically it is not possible to use these drivers configuration in CE.
