### ISSUE TITLE
Connection window should be modal dialog

### ISSUE THREAD

**Issue by spassignat** [dbeaver/dbeaver#13691]
When you test your database connection, and change window (ex: with Alt+TAB), the focus is lost on the connection result.

When you're back on dbeaver (ex: Alt+Tab), if you arrive on the connection settings, you can't close the window until the connection window is opened, but this windows is behind the connection settings.

In this screen shot, I moved the connection window to see it:
![image](https://user-images.githubusercontent.com/6451374/130983200-fffccd4a-606a-4560-b4e7-f649310b472d.png)

If you make the connection result window a modal dialog with the connection setting as parent, then it will always be in front. (java swing and awt behaviour. I guess the same exist on eclipse platform)

**Comment by uslss** [comment]
thank you for the report

**Comment by serge-rider** [comment]
We don't want to make these dialogs modeless. Because it is convenient to have multiple connection dialogs open (e.g. for settings copy-paste).
The problem is Linux-specific. We must somehow fix the problem with overlapped popups.
