### ISSUE TITLE
Check All for Database Dump Ignores Tables - Manual Check Works Fine

### ISSUE THREAD

**Issue by teamayu** [dbeaver/dbeaver#13699]
Operating system (distribution) and version: Win 10, 64 Bit
DBeaver version: 21.1.5
Database: MySQL, 5.7.29

Right Click a table in DBeaver and select 'Tools > Dump Database'. The dialog opens with the selected table highlighted. 

![27-08-2021_104822](https://user-images.githubusercontent.com/10624092/131064106-44e81f48-602d-4856-a66b-21b333b22f56.jpg)

If you select 'All' and then 'Start', it only backs up the table that was initially selected, regardless of the selections. If you check the boxes manually without using 'All', it works fine.

**Comment by LonwoLonwo** [comment]
Thanks for the bug report!

Doesn't work with PostgreSQL dump too.

As a workaround - right-click on tables container and choose Tools->Dump.

![2021-08-27 10_41_52-DBeaver Ultimate 21 2 0 - _dvdrental_ Script-2](https://user-images.githubusercontent.com/45152336/131091420-cd49080c-f150-4045-8c6c-2e6bc957612b.png)

**Comment by teamayu** [comment]
Great, thank you.

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.2.1

**Comment by uslss** [comment]
verified
