### ISSUE TITLE
The exporting table data function cut the clob content into too-long pieces which caused ora-1704 during importing

### ISSUE THREAD

**Issue by zhaopinglu** [dbeaver/dbeaver#13698]
#### System information: 
- Operating system (distribution) and version
-  windows 10
- 
- DBeaver version
- 21.1.2
- 
- Additional extensions

#### Connection specification:
- Database name and version
- oracle 19.3
- 
- Driver name
- oracle.jdbc.OracleDriver
- 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
- No

#### Describe the problem you're observing:
When exporting data for table which has clob column, dbeaver used the wrong length to cut the clob into pieces.
Currently, dbeaver cut the clob into pieces by the length value defined in dbeaver/plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/data/OracleCLOBValueHandler.java:
public static final int MAX_PART_SIZE = 4000;

This is not correct, due to:
1. The following code actually measure the length as char, not bytes,
2.  The maximum length of to_clob function is 4000 bytes.
3.  Clob accept multiple-bytes char, i.e. the char-wise length of ‘国’ is 1, but it occupied 3 bytes.

#### Solution:
Change the above hard code value to 1000, like:
public static final int MAX_PART_SIZE = 1000;

#### Why is 1000:
-- One Unicode character can be 1 byte, 2 bytes, 3 bytes, or 4 bytes in UTF-8 encoding.

#### Steps to reproduce, if exist:
DROP TABLE test18;
CREATE TABLE test18 (id NUMBER, name clob);
INSERT INTO test18 values(1, rpad('中国', 4000, '强'));
UPDATE test18 SET name = name || name;

SELECT length(name) FROM test18;
LENGTH(NAME)|
------------+
        2668|

-- The sql generated by exporting data function:
INSERT INTO TEST.TEST18 (ID,NAME) VALUES
	 (1,TO_CLOB('中国强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强 中国强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强强 '));
	 
	

#### Include any warning/errors/backtraces from the logs
SELECT * FROM "V$NLS_PARAMETERS";	
PARAMETER              |VALUE                       |CON_ID|
-----------------------+----------------------------+------+
NLS_LANGUAGE           |SIMPLIFIED CHINESE          |     0|
NLS_TERRITORY          |CHINA                       |     0|
NLS_CURRENCY           |￥                           |     0|
NLS_ISO_CURRENCY       |CHINA                       |     0|
NLS_NUMERIC_CHARACTERS |.,                          |     0|
NLS_CALENDAR           |GREGORIAN                   |     0|
NLS_DATE_FORMAT        |DD-MON-RR                   |     0|
NLS_DATE_LANGUAGE      |SIMPLIFIED CHINESE          |     0|
NLS_CHARACTERSET       |AL32UTF8                    |     0|
NLS_SORT               |BINARY                      |     0|
NLS_TIME_FORMAT        |HH.MI.SSXFF AM              |     0|
NLS_TIMESTAMP_FORMAT   |DD-MON-RR HH.MI.SSXFF AM    |     0|
NLS_TIME_TZ_FORMAT     |HH.MI.SSXFF AM TZR          |     0|
NLS_TIMESTAMP_TZ_FORMAT|DD-MON-RR HH.MI.SSXFF AM TZR|     0|
NLS_DUAL_CURRENCY      |￥                           |     0|
NLS_NCHAR_CHARACTERSET |AL16UTF16                   |     0|
NLS_COMP               |BINARY                      |     0|
NLS_LENGTH_SEMANTICS   |BYTE                        |     0|
NLS_NCHAR_CONV_EXCP    |FALSE                       |     0|

**Comment by zhaopinglu** [comment]
FYI:

UTF-8 Encoding
UTF-8 is the 8-bit encoding of Unicode. It is a variable-width encoding and a strict superset of ASCII. This means that each and every character in the ASCII character set is available in UTF-8 with the same code point values. 

**One Unicode character can be 1 byte, 2 bytes, 3 bytes, or 4 bytes in UTF-8 encoding.** 

Characters from the European scripts are represented in either 1 or 2 bytes. Characters from most Asian scripts are represented in 3 bytes. Supplementary characters are represented in 4 bytes.

https://docs.oracle.com/cd/E24693_01/server.11203/e10729/ch2charset.htm

**Comment by Matvey16** [comment]
@zhaopinglu Can you specify what is the issue here. I was able to successfully export this table to sql script and then inserted exact same clob into a table.

**Comment by uslss** [comment]
there is no update for a long time.
If it is still actual - feel free to reopen the issue.
