### ISSUE TITLE
Redshift For Timedout Sessions-Doesn't reconnect on query execute

### ISSUE THREAD

**Issue by deepaksenthilkumar** [dbeaver/dbeaver#13695]
In DBeaver 21.1.5 (Aug 16 build)

ALTER USER testuser SESSION TIMEOUT 60; -- In reality this is 1 hour, but setting to 60 seconds for quicker test.

After 60 seconds of idle time, when we run the query, we get the below error. 

![image](https://user-images.githubusercontent.com/36084950/131000097-4f219a6d-8f2c-4d8e-a8bb-9ce5a27cb410.png)

Invalidate/Reconnect works. But is there a way to automatically connect upon a specific type of error, for a better user experience?

**Comment by gururagavan2008** [comment]
In case it helps, this works with other databases. The issue seems to be only with Redshift.

**Comment by deepaksenthilkumar** [comment]
Thanks @gururagavan2008 
Yeah. It works for Teradata/Oracle. But doesn't work for Redshift.

**Comment by serge-rider** [comment]
This is easy to implement (PostgreDataSource.discoverErrorType)

**Comment by deepaksenthilkumar** [comment]
Thanks, @serge-rider for the suggestion. Fixed!

**Comment by Matvey16** [comment]
Verified
