### ISSUE TITLE
Report problem, app freeze after use wrongful query with CLOB type.

### ISSUE THREAD

**Issue by noom073** [dbeaver/dbeaver#13693]
#### System information: 
- Operating system Windows 10
- DBeaver version 21.1.5.202108160727

#### Connection specification:
- Database ORACLE10g

Report problem, app freeze after use wrongful query with CLOB type.
#### Describe the problem you're observing:
In ORACLE, after use group by with CLOB column it freeze and can't do anything.
Yes, it's the wrongful to query group by with CLOB. I just say it make me annoying to close and reopen the app.

![1629994159331](https://user-images.githubusercontent.com/54969096/130997880-13adfc9f-3eb1-41aa-a19d-b912f5ba72b3.jpg)

**Comment by uslss** [comment]
@noom073 could you provide table ddl and query example to reproduce an issue? thanks in advance

**Comment by noom073** [comment]
Thank you very much for your response.
Now it work normally, I am sorry you all for my issue. I think my problem it maybe because the connection is lose.
I’m really sorry for my mistake. Thank you very much again for your response.
![1630503752887](https://user-images.githubusercontent.com/54969096/131683568-a6223b9c-e51a-4e9a-8ae0-024ed73e2207.jpg)

**Comment by uslss** [comment]
@noom073 thank you for your response.
So the issue could be closed as resolved?

**Comment by noom073** [comment]
Yes, all right.
