### ISSUE TITLE
Choice of upper or lower case for data export

### ISSUE THREAD

**Issue by Philippe-M** [dbeaver/dbeaver#13704]
Would it be possible to have an option, when exporting data, to choose if the name of the tables / fields must be in upper case, lower case or respect the format of the source database?

For example this query

```
SELECT s.sdhnum_0, s.bpcord_0, s.bpaadd_0, s.stofcy_0, s.cfmflg_0, s.pjt_0, s.tsccod_0, s.tsccod_1, s.tsccod_2, TO_CHAR(s.shidat_0, 'yyyy-mm-dd') shidat_0, TO_CHAR(s.xexpdat_0, 'yyyy-mm-dd') xexpdat_0 FROM SDELIVERY s 
WHERE s.credat_0 >= TO_DATE('2018-01-01', 'yyyy-mm-dd') AND s.STOFCY_0 = 'FIN';
```

When exported to sql format gives

```
insert into SDELIVERY (SDHNUM_0,BPCORD_0,BPAADD_0,STOFCY_0,CFMFLG_0,PJT_0,TSCCOD_0,TSCCOD_1,TSCCOD_2,SHIDAT_0,XEXPDAT_0) values
         ('LIVHIL21040001','DIVERS','C01','FIN',1,' ','DIV','DIV',' ','2021-04-01','2021-04-01'),
[...]
```

while i wish it looked like this
```
insert into sdelivery (sdhnum_0,bpcord_0,bpaadd_0,stofcy_0,cfmflg_0,pjt_0,tsccod_0,tsccod_1,tsccod_2,shidat_0,xexpdat_0) values
         ('LIVHIL21040001','DIVERS','C01','FIN',1,' ','DIV','DIV',' ','2021-04-01','2021-04-01'),
[...]
```

**Comment by Matvey16** [comment]
Not sure about a use case when it must be neccessary. Can you provide some kind of example?

**Comment by Philippe-M** [comment]
For example when I export data from an Oracle database to import them into a Mariadb database.

In Oracle the field names are in upper case while in Mariadb they are in upper case. This is just to avoid going through intermediate processing to convert upper case to lower case.

**Comment by Matvey16** [comment]
@Philippe-M Thank you for a suggestion

It will be a good idea to add this option to export settings

**Comment by uslss** [comment]
verified
