### ISSUE TITLE
Redshift: references are not shown

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13707]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.2.0

#### Connection specification:
- Database name and version Redshift

#### Describe the problem you're observing:
References are not show in table metadata

#### Steps to reproduce, if exist:
1. Create a parent table
2. Create a child table with foreign key referencing a parent table
3. Open References panel in data viewer or references tab in properties view

**Expected:** Referencing table is shown
**Actual:** It is not shown

![S8IrpCfH7W](https://user-images.githubusercontent.com/82543000/131120375-4da28618-bc10-47fa-b28e-c5502fe95d9e.gif)

**Comment by kseniiaguzeeva** [comment]
Cannot be reproduced any more (  DBeaver	21.2.1.202109170940)
