### ISSUE TITLE
Filter db objects by name

### ISSUE THREAD

**Issue by ptarant** [dbeaver/dbeaver#13702]
#### System information: 
- Operating system (distribution) and version: MacOS 11.5.2
- DBeaver version: Version 21.1.5.202108160727
- Additional extensions: none

#### Connection specification:
- Database name and version: Percona DB cluster 5
- Driver name: MySQL from DBeaver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : SSH proxy

#### Describe the problem you're observing:
the text field where the object filter string is to be entered cannot be emptied by pressing "x" button on its right side. The functionality in Windows version works.

#### Steps to reproduce, if exist:
Open any database connection
Select the schema and display list of tables
Enter the filter string
Try to erase the filter string by pressing the x button
The filter string remains intact

<img width="375" alt="image" src="https://user-images.githubusercontent.com/17988931/131095574-f5b418c3-73a4-4529-97ff-6dc2f17cc93f.png">

**Comment by uslss** [comment]
thanks for the report
duplicates #10590
