### ISSUE TITLE
Import SQL Script - Allow selection of multiple files

### ISSUE THREAD

**Issue by binodkalathil** [dbeaver/dbeaver#13700]
**Is your feature request related to a problem? Please describe.**
The **Import SQL Script** option in **SQL Editor** Menu allows the selection of only one file. I am trying to run scripts in multiple files and I will need to do the manual selection of files for all the files available. Some of the other SQL clients have this feature already.

**Describe the solution you'd like**
We want to be able to select all the files so that  we do not want to do this for every file available.

**Describe alternatives you've considered**
Merging all the available files into a single file is an option but that is not relevant here, right?

**Additional context**
One problem I saw with other SQL clients providing the same feature is that they include all the files' contents without any line breaks between the contents of different files. This causes another problem in some cases which makes this feature unusable.

Suppose one file's end is like: `DELIMITER ;` and if there is another file the resulting SQL will be `DELIMITER ;<the first line of SQL in the next file>` which is clearly not something we want.

**Comment by uslss** [comment]
@binodkalathil you could use file - open file (Ctrl+O).
Does it solve your issue?

**Comment by binodkalathil** [comment]
@uslss That allows opening multiple files, however it opens each file in a separate tab needing the user to execute each script. If the user have 10 scripts then this is going to be too much manual work.

**Comment by Matvey16** [comment]
@binodkalathil Thank you for the suggestion

**Comment by uslss** [comment]
verified
