### ISSUE TITLE
Pop up window remains visible after opening a table in SQL Editor from the top filter field

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13701]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.2.0 EA
#### Steps to reproduce, if exist:
1. Open a table in the Data Editor
2. Double click the table name, which is placed before the top filter field

**Expected**: the SQL Editor is opened with the select query
**Actual result**:  the SQL Editor is opened with the select query and pop up window with the same query (it appears when we click one time to the table name in the Data Editor)

https://user-images.githubusercontent.com/51405061/131094057-82823866-694f-4c01-92f7-e58112e25618.mp4

**Comment by uslss** [comment]
verified
