### ISSUE TITLE
Edits to cells do not save

### ISSUE THREAD

**Issue by mataski** [dbeaver/dbeaver#13715]
v21.1.5

Can't save any edit made to a cell

E.g. change 14 to 0014 and clicking Save does not do anything.

![gif](https://user-images.githubusercontent.com/62036912/131168977-b079f085-d92b-4c20-853b-bd30469860dd.gif)

![image](https://user-images.githubusercontent.com/62036912/131169133-51d91d45-db40-4741-a1f5-3d7eb2195f1d.png)

**Comment by ShadelessFox** [comment]
Hello @mataski,

Leading zeroes are often trimmed because they make no sense. What's your use case?

**Comment by mataski** [comment]
That's the goal, need leading zeroes? On the website they will increment 0014, 0015, 0016, etc. with every new entity creation.

(website runs on PHP CMS called Drupal)

And you're right, it does save if I change it to just 15.

**Comment by ShadelessFox** [comment]
I still don't understand your use case.

If you want to select IDs from your database padded with zeroes, you can use builtin database functions, or just store IDs as `char(4)`. It's not DBeaver-related.
