### ISSUE TITLE
Update OpenJDK JRE in installer from 11.0.11 to 11.0.12

### ISSUE THREAD

**Issue by Hex052** [dbeaver/dbeaver#13716]
**Is your feature request related to a problem? Please describe.**
The version of OpenJDK 11 bundled with the installer or the zip files is out of date. OpenJDK JRE 11.0.11 is bundled while 11.0.12 is the most recent, which fixes [these issues](https://openjdk.java.net/groups/vulnerability/advisories/2021-07-20)

**Describe the solution you'd like**
OpenJDK JRE 11 should be updated to 11.0.12

**Describe alternatives you've considered**
Install Java separately and deselect the option to use the bundled version of Java, but many people will not do this and will be using a version with known flaws.

**Comment by AnrDaemon** [comment]
Many people would just use standalone zip and avoid this issue.

**Comment by flambchap** [comment]
Done.

**Comment by Matvey16** [comment]
Verified
