### ISSUE TITLE
Can't execute set,unset,echo commands if carriage is placed after last letter

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13727]
#### System information: 
- Win10, DBeaver 21.2.0

#### Steps to reproduce, if exist:
Type @set var=somevalue and press ctrl+enter
Expected: variable value is set
Actual: nothing happened. You need to move the carriage from the end of the line to anywhere in the middle and then if you pressed ctrl+enter the variable will be created

https://user-images.githubusercontent.com/43252954/131304644-08501fc7-1829-4c34-9744-6cb14bb3a919.mp4

**Comment by uslss** [comment]
verified

**Comment by uslss** [comment]
verified

**Comment by DariaMarkaryan** [comment]
Reproduceable again. For **Alt+X** it works well, but for **Ctrl+Enter** exist the problem is described in the ticket
