### ISSUE TITLE
Redshift: Permissions are shown incorrectly in DDL for new tables

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13724]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.2.0

#### Connection specification:
- Database name and version Redshift

#### Steps to reproduce, if exist:
1. Create new table
2. Open DDL for the table and enable permissions display

**Expected:** Correct grants are shown
**Actual:** Grant DDL is missing user name

**Note:** Manually adding already existing permissions fixes the issue and DDL starts to be shown correctly.

![4iT9WVnlMP](https://user-images.githubusercontent.com/82543000/131294335-b7012ca0-fc84-4cd1-989c-9aa2b179e522.gif)

![JSWABBoqr5](https://user-images.githubusercontent.com/82543000/131294346-b8c5c38b-6d36-4511-afa9-395be412ca61.gif)

**Comment by aparrott-bgsa** [comment]
Can confirm, I'm experiencing crashes of the client when trying to generate sql - ddl

**Comment by E1izabeth** [comment]
Not reproducible anymore

https://user-images.githubusercontent.com/28875055/179218818-cfd89e43-a37e-476f-b274-67aaa8796636.mp4
