### ISSUE TITLE
Highlighted results are not cleared for simple search when next search can't find any results

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13725]
#### System information: 
- Win10, DBeaver 21.2.0

If we've already perform search without "search by whole word" checkbox activated, and then we checked it, the selection of founded previously data isn't cleared

#### Steps to reproduce, if exist:
https://user-images.githubusercontent.com/43252954/131299086-ac368ef2-0763-4005-92b3-2e0e8b0267e2.mp4

**Comment by Matvey16** [comment]
Happens regardless of `whole word` option. When string is not found, results of the last successful search would be highlighted. But maybe it is expected behavior?

**Comment by uslss** [comment]
verified
