### ISSUE TITLE
Open multiple same table records

### ISSUE THREAD

**Issue by rajeshisnepali** [dbeaver/dbeaver#13739]
**Is your feature request related to a problem? Please describe.**
So hard to view records side by side. You can't open duplicate records. 

**Describe the solution you'd like**
Add a feature to view the same table records multiple times. 

**Describe alternatives you've considered**
Had to open a new window for this small issue which obviously takes huge system resource.

**Comment by uslss** [comment]
@rajeshisnepali Multiple record view is already implemented. Does it solve your issue?
![cGd5pio0Wl](https://user-images.githubusercontent.com/31996417/131459813-06e57478-a9a7-40b3-be66-7472f2840063.gif)

**Comment by rajeshisnepali** [comment]
Unfortunately, it's very hard to see how you get those records (cropped gif). Also, I need to open two tables instead of opening few (selected) rows.

**Comment by uslss** [comment]
@rajeshisnepali could you clarify your use case step by step?

**Comment by rajeshisnepali** [comment]
![image](https://user-images.githubusercontent.com/23610013/133470762-02a807b5-4386-40a1-ac38-c82d2d512444.png)
It should be clear now. @uslss 

Please don't hesitate to ask if it's still unclear.

**Comment by Matvey16** [comment]
@rajeshisnepali Hello, you can open the same table in a split editor by enabling it in Window menu. Do you think that feature is enough for your use case?

![o24Q3KUI4a](https://user-images.githubusercontent.com/82543000/134466253-b09c1ad0-041c-453d-a38b-d9ee1c650d8b.gif)

**Comment by rajeshisnepali** [comment]
@Matvey16 
> Do you think that feature is enough for your use case?

That is a quite nice feature but this is not what I wanted. When I switch to another table, the existing split tables are gone. 

Maybe my question is different but I wanted to visualize (compare) two different tables (which the above steps are helpful but not satisfactory)

![image](https://user-images.githubusercontent.com/23610013/134614899-d6fbb5bf-c8f8-4c58-819e-ff0df760b096.png)

**Comment by Matvey16** [comment]
@rajeshisnepali 
If you want to compare two (or more) different tables in one window you can drag tabs almost however you want.

![EOqFjrGpsv](https://user-images.githubusercontent.com/82543000/135278883-2b22c8fb-b891-48e7-9c0a-70ea7bbc21bf.gif)

Maybe we are talking about different things? If I again misunderstood you, please add some list steps of your use case (how it would have been like if the needed feature was added)

**Comment by rajeshisnepali** [comment]
@Matvey16 
It's getting confusing 😀

Yes, I always do that (that's a very handy feature). But can we compare the same table in a different pane (same window)? That's the feature, I really wanted. 

![2021-10-04_21-40](https://user-images.githubusercontent.com/23610013/135884006-5e7a013d-3f79-454b-a020-f4800b9461c7.png)

![image](https://user-images.githubusercontent.com/23610013/135884584-329a7017-8051-4505-949c-d924304ddfa7.png)

Please let me know if you don't understand. I'll now make a screencast for you.

**Comment by Matvey16** [comment]
@rajeshisnepali I think we are pretty close to finally understanding each other. So the way I see it, you want to simultaneously look at two windows of the same table and also another table. I attached a gif that shows how it is possible. Please look at it and add what you think can be done to make it more usable and if I was wrong, correct me how it is different from your use case.

![Mk4rkkrblC](https://user-images.githubusercontent.com/82543000/136179159-376faa06-c37c-4bfd-a3b9-d4c60c9cc428.gif)

**Comment by rajeshisnepali** [comment]
@Matvey16 yes, that's kind of impressive. But again it's not that what I wanted. For now, this might do the task but if you see, the `Artist` table is not independent. You'll get to see two (split) tables whenever you click that `Artist` table. 

It's already done in most of the popular IDEs. I'll show you the screenshot & gif of PhpStorm.
![image](https://user-images.githubusercontent.com/23610013/136645739-f833a788-7c06-4b34-b080-b8543e332750.png)

GIF
![dbeaver-split-table-0](https://user-images.githubusercontent.com/23610013/136645884-9318f631-143f-41e9-8b62-1effcbb57c28.gif)

**Comment by flambchap** [comment]
Hello @rajeshisnepali. Is this the behavior you're trying to achieve?

![split](https://user-images.githubusercontent.com/26031301/138059848-654cf145-32df-4634-a7f8-d63a7a984ce9.gif)

**Comment by rajeshisnepali** [comment]
Oh yes... Finally, Thanks @akilovich
