### ISSUE TITLE
Uncomment line strip indentation

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#13744]
#### System information: 
- Linux Mint v19.3
- DBeaver version 21.0.3

#### Connection specification:
- Database name and version Postgres

#### Describe the problem you're observing:
When I uncomment line CTRL+/ then indentation is removed too

#### Steps to reproduce, if exist:

1. type: tab, tab, --, some text
2. press CTRL+/

```
            --some text
     actual:
     some text
     expected:
            some text
```

**Comment by uslss** [comment]
thank you for the report

**Comment by uslss** [comment]
verified
