### ISSUE TITLE
Timezones are not displayed with disabled date/time formatting

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13751]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.2 EE

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
1. Disable date/time formatting in PostgreSQL connection settings
2. Open a table with a timezone column type (e.g. _postgres.test_review.date_test_)

**Expected**: timezones are displayed in cell values
**Actual result**: timezones are not displayed

**Comment by serge-rider** [comment]
Fixed.
Note: new timestamp formatting types were added: `Timestamp with timezone` and  `Time with timezone`.

**Comment by Matvey16** [comment]
Verified
