### ISSUE TITLE
Closing tags not auto completed

### ISSUE THREAD

**Issue by BERRELION** [dbeaver/dbeaver#13756]
`IF ... THEN / END IF` are not automatically added when typing in SQL editor. Same for ` CASE / END [CASE]` and `LOOP / END LOOP`.

The only clause I am aware of that gets auto-completed is the `BEGIN / END` clause.

It would be a time saver if that's added in new features 👌😉!

As of now, I set up templates for all those clauses but I often time forget then keyword... but having feature native on editor would be best.

**Comment by Matvey16** [comment]
Verified
