### ISSUE TITLE
NULL strings in CSV export aren't quoted

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13755]
#### System information: 
- Win10, DBeaver EE 21.2.0

#### Connection specification:
- Reproduced in Mongo, Vertica..

#### Describe the problem you're observing:
Strings that replaces NULL values when you perform CSV export can't be quoted

#### Steps to reproduce, if exist:
1. Open table with NULL values 
2. Start CSV export
3. Set string for NULL values and set Quote always as "all"
![image](https://user-images.githubusercontent.com/43252954/131690959-3b5743b5-ee0b-4634-8f8c-9a7794dc1392.png)

**Expected:**
All data are quoted
**Actual:**
NULL-strings aren't quoted
![image](https://user-images.githubusercontent.com/43252954/131692511-4465e1d7-5d5e-4dbc-973b-b7a25d0ef20b.png)

**Comment by ShadelessFox** [comment]
Quotes in CSV files are non-mandanory. Why do we need to quote them?

Moreover, how e.g. `"NULL"` should be interpreted as? As a `NULL` value or as a `"NULL"` string?

**Comment by DariaMarkaryan** [comment]
There were suggestions that it is important for someone to be able to quote absolutely everything that is in the exported data. I thought that for a reason this value itself is called null-STRING and there is an option to quote ALL (absolutely all?)

**Comment by ShadelessFox** [comment]
Now `all` quote mode will quote NULLs too. Added additional `all but nulls` mode that preserves old behavior.

**Comment by Matvey16** [comment]
New bugs for tables with NULLs, newlines and delimiters are lost during an export
![Qo6GWJgfGr](https://user-images.githubusercontent.com/82543000/135616325-8c08b680-9794-4130-ad12-34c09ee92138.gif)

**Comment by Matvey16** [comment]
Verified
