### ISSUE TITLE
ResultSet fetch size can't be set to lower than 100

### ISSUE THREAD

**Issue by halilim** [dbeaver/dbeaver#13758]
#### System information: 
- Operating system (distribution) and version: macOS Big Sur 11.5.2 (20G95)
- DBeaver version: 21.2.0.202108291732

#### Connection specification:
- Database name and version: PostgreSQL 13.3
- Driver name: PostgreSQL JDBC Driver 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
ResultSet fetch size can't be set to lower than 100 in the Data Editor settings

#### Steps to reproduce, if exist:
1. Open Preferences or the connection configuration
2. Navigate to Data Editor
3. Set "ResultSet fetch size" to a value smaller than 100
4. Apply and Close
5. Reopen Preferences/Connection > Data Editor

**Actual:** It's still 100
**Expected:** It retains the value set in step 3

#### Include any warning/errors/backtraces from the logs
None seems related

#### Notes
This might be related to https://github.com/dbeaver/dbeaver/issues/10083

**Comment by ShadelessFox** [comment]
Hello @halilim,

It's a feature. Why would you need to fetch less than 100 rows in one go?

**Comment by halilim** [comment]
@ShadelessFox we have tables with `jsonb` columns. Some of them take 10-20 seconds to load 100 rows.

**Comment by ShadelessFox** [comment]
I see. Thanks for the explanation!

**Comment by Matvey16** [comment]
We can add this as an option, but it should work in conjunction with disabled auto-fetch property
![dbeaver_aquAhkHZhJ](https://user-images.githubusercontent.com/82543000/133446731-5d244659-4b29-42b7-b905-baef8536ea0b.png)

@halilim Thank you for a suggestion

**Comment by halilim** [comment]
@Matvey16 Could you expand on that? I thought it could auto-fetch the given size.

**Comment by Matvey16** [comment]
@halilim The main point is: We made 100 rows a minimum value, because DBeaver by default auto-fetches more rows if you scroll to the end of already fetched rows. It means that if you set it to 1, it will auto-fetch the next one until they fill the whole screen.

We plan to add an option to lift the restriction on minimum fetch size, but it won't work if auto-fetch is enabled.

**Comment by halilim** [comment]
@Matvey16 oh right, sorry, completely forgot about the fact that it wouldn't fill the screen that way. I guess I thought that it's purely activated by the mouse and is not connected to the scrollbar. For those cases, can it be modified/would it make sense to work only on mouse scroll, rather than automatically?

**Comment by cyberbeat** [comment]
@Matvey16 Must that be both the same configuration-variable? I mean the minimum fetch-size and the auto-fetch-size? And in case of deactivation of auto-fetch, it would be nice to have another button or mouse-wheel-action (like comment above) to do that manually.

**Comment by Matvey16** [comment]
@cyberbeat There is actually a button for manual fetch already with a shortcut of <kbd>Ctrl+Alt+;</kbd>

![image](https://user-images.githubusercontent.com/82543000/140720536-6eba8781-2b5d-4f53-be08-eacf014ad4ef.png)

**Comment by Matvey16** [comment]
Verified
