### ISSUE TITLE
Variables (parameters) are not changed during export from query

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13761]
#### System information: 
- DBeaver version 21.2.0

#### Describe the problem you're observing:
Changes to variables during export from query are not saved and are ignored

#### Steps to reproduce, if exist:
1. Start an export from query with a variable
2. At the last step of export settings change a variable value
3. Start export

**Expected:** Exported data is from query with a changed variable value
**Actual:** Initial variable value is used

![FufvHZ2N36](https://user-images.githubusercontent.com/82543000/131794076-1b7b33e7-93fb-43f1-9bf2-b791ff51f0cd.gif)

**Comment by kseniiaguzeeva** [comment]
Also when:
1. a statement with variable is executed
2. export is performed from the ResultSet and saved as the task
No table data is exported, because the variable value hasn't been applied

https://user-images.githubusercontent.com/51405061/139404859-4d1066b7-7e2a-42a0-a47f-f3fa874c4543.mp4

**Comment by Skydiveroid** [comment]
We need to disable variable editor for non-task exports

**Comment by Matvey16** [comment]
Verified
