### ISSUE TITLE
Wrong sorting of tasks with upper case letters

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13763]
Sorting database tasks right now mixes folders with other tasks. It would be more user friendly if folders are always shown on top.

![x5t1kYY5ca](https://user-images.githubusercontent.com/82543000/131800782-82a58ab0-c6bc-485f-9fc0-1e3b92a80ac7.gif)

**Comment by LonwoLonwo** [comment]
> DBeaver has a weird alphabetizing method, putting items not capitalized after capitalized letters that come after.  In fact I was surprised that the names of tasks are case sensitive as once I saw this, I copied the tasks and renamed using capitals and it did not say duplicate.

**Comment by Matvey16** [comment]
Verified
