### ISSUE TITLE
Incorrect tab is shown instead of Statistic tab after Explain execution plan

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#13767]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.2.0

#### Connection specification:
- Database name and version Azure SQL Server

#### Describe the problem you're observing:
Incorrect tab is shown instead of Statistic tab after Explain plan execution for Create/Update/Insert queries
#### Steps to reproduce, if exist:
1. Connect to db and perform Explain execution plan
2. Than execute e.g. Update query

Actual result:
![image](https://user-images.githubusercontent.com/31996417/131828408-4b8a3a74-96a8-4854-a548-28dd4e61fee2.png)
Expected:
![image](https://user-images.githubusercontent.com/31996417/131828634-b94ee734-b90c-4f7a-91ea-6a76141289c5.png)

**Comment by E1izabeth** [comment]
Can't reproduce against DBeaver 23.0.5
