### ISSUE TITLE
Test tunnel isn't work if environment variable is used in SSH Tunnel configuration

### ISSUE THREAD

**Issue by tran-huynh-minh-ngoc** [dbeaver/dbeaver#13775]
#### System information: 
- Windows 10 (21H1)
- DBeaver 21.2.0.202108310918
- Additional extensions: None

#### Connection specification:
- Database name and version: MySQL Server 8.0
- Driver name: MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc): I use SSH

#### Describe the problem you're observing:
I set my environment variables but I can't use them in SSH Tunnel configuration in DBeaver connection.

I checked the "Use environment variables in connection parameters" option.

#### Steps to reproduce, if exist:
My user variables:
![image](https://user-images.githubusercontent.com/85098658/131876487-a3662e3f-81b5-4b77-90bf-f94cd8560022.png)

The "Use environment variables in connection parameters" option is checked:
![image](https://user-images.githubusercontent.com/85098658/131876636-3475dd5c-cbb7-4f57-afd5-c23b12742df8.png)

SSH Tunnel configuration:
![image](https://user-images.githubusercontent.com/85098658/131876783-5297c3e0-5218-4e29-b4c3-65b30a8b5bc3.png)

But DBeaver doesn't resolve my variables:
![image](https://user-images.githubusercontent.com/85098658/131876890-3e122d9b-9dd7-4bd6-8fe0-4b4ab306b22d.png)

#### Include any warning/errors/backtraces from the logs
```
2021-09-02 22:55:05.788 - Private key file '${UBUNTU_VM_PRIVATE_KEY_PATH}' does not exist
org.jkiss.dbeaver.DBException: Private key file '${UBUNTU_VM_PRIVATE_KEY_PATH}' does not exist
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.loadConfiguration(SSHImplementationAbstract.java:217)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:98)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI.lambda$0(SSHTunnelConfiguratorUI.java:218)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$14(UIUtils.java:1682)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by uslss** [comment]
@tran-huynh-minh-ngoc Did you try to restart dbeaver after you set environment variables?

**Comment by tran-huynh-minh-ngoc** [comment]
I even restarted my computer but the problem still there.

**Comment by uslss** [comment]
@tran-huynh-minh-ngoc Could you try to use created SSH profile (even if Test Tunnel fails) to connect to db?

**Comment by tran-huynh-minh-ngoc** [comment]
@uslss It works, Thank you! It's strange that the test functionality fails.

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
Test tunnel call from profiles fixed.

**Comment by Matvey16** [comment]
Verified
