### ISSUE TITLE
PostgresQL special column name conversion issues

### ISSUE THREAD

**Issue by sergynet** [dbeaver/dbeaver#13773]
#### System information: 
- Mac OS 11.3.1
- DBeaver 21.1.5 CE
- Java 8 

#### Connection specification:
- Oracle 12.3 to Postgres 12.6
- JDBC, standard

#### Describe the problem you're observing:

1. It appears that the tool treats NAME/TYPE/ACTION/DATA attribute as keywords and puts quotes around it which makes it think the the target database does not have these fields, so data export/import process would try to create these and fails.
**org.jkiss.dbeaver.model.exec.DBCException: Can't find target attribute [TYPE/NAME/ACTION/DATA]**

2. If the source columnd is CLOB and the target column is TEXT, we'd get another error (probably related to type conversion?)
**org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42601]: ERROR: type modifier is not allowed for type "bytea"**

#### Steps to reproduce, if exist:
**ORACLE:**
CREATE TABLE TEST
(
NAME VARCHAR2(1024 BYTE),
TYPE VARCHAR2(1024 BYTE),
ACTION VARCHAR2(1024 BYTE),
DATA VARCHAR2(1024 BYTE),
JSON CLOB
);    
INSERT INTO TEST (NAME,TYPE,ACTION,DATA,JSON) VALUES ('name', 'type', 'action', 'data', 'json');
  

**POSTGRES:**
CREATE TABLE test(
name CHARACTER VARYING(1024) ,
type CHARACTER VARYING(1024),
action CHARACTER VARYING(1024),
data CHARACTER VARYING(1024),
json TEXT
)
WITH (
OIDS=FALSE
);

####Log files and screenshots
[run_202108261303_1.log](https://github.com/dbeaver/dbeaver/files/7099922/run_202108261303_1.log)
<img width="691" alt="Screen Shot 2021-08-26 at 13 03 14" src="https://user-images.githubusercontent.com/4033151/131868103-39c06c22-da2f-42bd-a00c-5ff0aeb1fbaf.png">
<img width="685" alt="Screen Shot 2021-08-26 at 13 03 30" src="https://user-images.githubusercontent.com/4033151/131868108-99f93848-1ca5-4df9-9f56-bfff69b4282f.png">
<img width="691" alt="Screen Shot 2021-08-26 at 13 03 46" src="https://user-images.githubusercontent.com/4033151/131868111-35527f89-c175-41ee-8d53-bf3a39cf27b0.png">
<img width="529" alt="Screen Shot 2021-08-26 at 13 04 12" src="https://user-images.githubusercontent.com/4033151/131868112-40212741-b68e-4e07-bfc4-4c1ac95be73b.png">

**Comment by ShadelessFox** [comment]
Hello @sergynet,

I believe the issue was already solved. Please try upgrading to DBeaver 21.2.0.

**Comment by uslss** [comment]
there is no update for a long time.
If it is still actual - feel free to reopen the issue.
