### ISSUE TITLE
Displaying only connected databases when PostgreSQL is connected leads to expanding all its databases

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13772]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.2 EE EA

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:

1. Connect to PostgreSQL
2. Open db-db data transfer for a table
3. Open a dialog to find source container and enable showing only connected databases

**Expected**: only connected databases are displayed.
**Actual result**: all PostgreSQL databases are expanded

https://user-images.githubusercontent.com/51405061/131856894-8f374fed-f59f-44b0-868b-205c7dabcea5.mov

**Comment by ShadelessFox** [comment]
1. Tree expansion limit was reduced to just first children
2. Button <kbd>Show connected databases</kbd> was removed for non-database containers

**Comment by Matvey16** [comment]
Verified
