### ISSUE TITLE
Don't sort xml attribute with auto format functionality.

### ISSUE THREAD

**Issue by mhandoko-fff** [dbeaver/dbeaver#13778]
Right now when working on xml string (xml data type) either through Value Panel using Auto Format or on editor (Shift + Enter) -> choose xml -> Ctrl-Shift-F for auto formatting, the xml attributes is also sorted alphabetically. 

Need a way to preserve the actual data when auto formatting as there is a reason where the attribute is located in the string.

Thank you.

**Comment by Matvey16** [comment]
@mhandoko-fff Hello. Can you provide more details? What DB are you using. It will be great if could provide an example to more specifically see what and when is being sorted.

**Comment by mhandoko-fff** [comment]
The DB is MS SQL 2017 with xml type column. The xml stored in the table/column is basically a one long string.
 
![Screen Shot 2021-09-08 at 9 20 11 AM](https://user-images.githubusercontent.com/89548200/132547058-dab5021c-36e6-4e31-8be2-cf78fa630711.png)

If I format the string outside DBeaver, it will look like below (please notice the attribute next to container that it will go from containerid - depth - width - height - etc)

![Screen Shot 2021-09-08 at 9 22 24 AM](https://user-images.githubusercontent.com/89548200/132547310-f5ffaec1-0389-408e-b13a-b8082b31b40b.png)

If I format the same sting either through value panel or xml editor, it will look like below as the xml attributes were sorted alphabetically

![Screen Shot 2021-09-08 at 9 24 04 AM](https://user-images.githubusercontent.com/89548200/132547642-b638af05-333c-4e78-b3b0-e199d680256f.png)

**Comment by Matvey16** [comment]
@mhandoko-fff Thank you for the report

**Comment by mhandoko-fff** [comment]
Thank you for the getting it in for the next release.

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
