### ISSUE TITLE
Group results by a column

### ISSUE THREAD

**Issue by creage** [dbeaver/dbeaver#1378]
I have a new feature request/suggestion.

It would be nice if we could group results by columns, to have better overview of the records.

So, whenever we group our results by some column - results are grouped by the value of that column, presented as a collapsible lists, all are collapsed by default.

**Comment by uslss** [comment]
Hi @creage ,
if I understand you right, feature you need is already implemented as a Grouping panel (https://github.com/dbeaver/dbeaver/wiki/Panels#grouping-panel).
Ticket is closed. 
If ticket is still actual for you, feel free to reopen ticket or create a new one.
