### ISSUE TITLE
Using path with backslashes break

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#13786]
#### System information: 
- Operating system (distribution) and version: **Windows 10**

#### Describe the problem you're observing:
On Windows, path is separated using backslashes. Our shell parser treats backslash as escape. Probably we should disable this behavior on Windows.

#### Steps to reproduce:
1. Add shell command containing backslashes: `C:\Windows\notepad.exe`
2. Trigger it

![image](https://user-images.githubusercontent.com/35821147/131976187-71069800-1f65-4a61-876c-3eb500cf7a59.png)

**Comment by DariaMarkaryan** [comment]
Verified
