### ISSUE TITLE
Issue installing Dbeaver plugins

### ISSUE THREAD

**Issue by danielbornt** [dbeaver/dbeaver#13792]
System: Windows 10  - 1909
Machine: ThinkPad P54 w/ 32g of Ram

Dbeaver Version: Dbeaver Community Version 21.2.0.202108310918

Issue: Just installed the Darkest Dark Theme plugin fine but when I try to install any theme from dbeaver.io I get this error message:

Unable to read repository at http://dbeaver.io/update/office/latest/content.xml.
Unable to read repository at http://dbeaver.io/update/office/latest/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

this is happening when I go to any of the dbeaver.io plugin sites. Darkest Dark and Eclipse come up fine.

![2021-09-03 07_04_23-Clipboard](https://user-images.githubusercontent.com/8417449/131995743-a0ce942f-857c-4b73-8282-cdae4c9d39bf.png)

**Comment by serge-rider** [comment]
Try https prefix (http protocol is no longer supported).

**Comment by danielbornt** [comment]
Made the change  and got the same thing.
![2021-09-03 07_22_07-DBeaver 21 2 0](https://user-images.githubusercontent.com/8417449/131997766-9e6b8bc4-f29f-407c-819b-2be5cba2904a.png)

**Comment by uslss** [comment]
cannot reproduce it. Are you using proxy?
![image](https://user-images.githubusercontent.com/31996417/135813927-571d5cb6-7f8c-4213-8df1-fdb5915502eb.png)

**Comment by uslss** [comment]
there is no update on the issue for a long time. if it is still actual for you - feel free to reopen it with additional info.
