### ISSUE TITLE
Show task folders always on top

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13795]
Reopening for #13763 since it was closed for other fixes

Sorting database tasks right now mixes folders with other tasks. It would be more user friendly if folders are always shown on top.

![x5t1kYY5ca](https://user-images.githubusercontent.com/82543000/131800782-82a58ab0-c6bc-485f-9fc0-1e3b92a80ac7.gif)

**Comment by ShadelessFox** [comment]
Implemented:

![java_mwrTpxaB1O](https://user-images.githubusercontent.com/35821147/155542118-7b95c5e9-26f9-4d74-85dc-f75e4cffc917.gif)

**Comment by Matvey16** [comment]
Verified
