### ISSUE TITLE
Unable to view stored procs in snowflake

### ISSUE THREAD

**Issue by BlessingZondi** [dbeaver/dbeaver#13798]
#### System information: 
- Operating system (distribution) and version : Windows 10 Pro version 20H2
- DBeaver version: 21.2.0.202108310918
- Additional extensions:

#### Connection specification:
- Database name and version: Snowflake
- Driver name: Snowflake
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
-I am unable to view stored procs when connected to snowflake 
-Views are listed together with tables, there are no folders that separate DB objects i.e. tables, view, procs

#### Steps to reproduce, if exist:
N/A because it's the ability to view stored procs and alter them when required

**Comment by LonwoLonwo** [comment]
Hello @BlessingZondi 

Please check your connection settings:

![2021-09-04 23_37_00-DBeaver 21 1 0 - _PostgreSQL - dvdrental_ Script-33](https://user-images.githubusercontent.com/45152336/132107447-cd774537-5faf-40cf-97cd-93f40e9bca51.png)

Snowflake dataSource (connection) must have Databases with schemas in Tree Viewer. 
Especially in the Advanced connection view. 
The custom view can have some unifying entities settings.

![2021-09-04 23_37_49-DBeaver 21 1 0 - _PostgreSQL - dvdrental_ Script-33](https://user-images.githubusercontent.com/45152336/132107525-44c885d5-5f7f-43b9-bf7b-25932b459f07.png)

**Comment by BlessingZondi** [comment]
Good day @LonwoLonwo 

Thank you for your prompted response and assisting by pointing to the right direction.
It is sorted now, thank you.

Regards,

**Comment by BlessingZondi** [comment]
Issure has been resolved.
