### ISSUE TITLE
Metadata search in comments does not work the first time you open the corresponding dialog

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#13811]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 21.2.0 UE

#### Steps to reproduce, if exist:
1. Open Search -> DB Metadata dialog
2. Set 'Search in comments' checkbox
3. Search for something. Search in comments won't be performed.

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
