### ISSUE TITLE
Number of rows is not updated after querying an empty table if a non-empty table was queried before it

### ISSUE THREAD

**Issue by deepaksenthilkumar** [dbeaver/dbeaver#13816]
Database: Redshift 

DBeaver version: Version 21.2.0.202108291732

Run the following queries and check the rows.
SELECT 1
![image](https://user-images.githubusercontent.com/36084950/132266413-2b64904c-9bcf-4ee1-a93e-236425470f06.png)

SELECT 1 WHERE false
![image](https://user-images.githubusercontent.com/36084950/132266475-a0422bd9-e7e7-40cc-aec8-600587dc0bfc.png)

**Comment by Matvey16** [comment]
Incorrect row number when all rows are deleted in data editor

![dbeaver_BALyDuM5bz](https://user-images.githubusercontent.com/82543000/158354310-54ff3699-c977-473b-bfcb-14aa94dc9f14.gif)

**Comment by Matvey16** [comment]
Verified
