### ISSUE TITLE
DynamoDB: Table name with special symbols is not quoted when filter is applied in data editor

### ISSUE THREAD

**Issue by analogstar** [dbeaver/dbeaver#13818]
#### System information: 
- Operating system (distribution) and version: macOS Big Sur 11.5.2
- DBeaver version: 21.2.0.202109061154
- Additional extensions

#### Connection specification:
- Database name and version: Amazon DynamoDB
- Driver name: DynamoDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

"Encountered unexpected token" Error when trying to get data using SQL query with hyphenated table name.

Message:
Encountered unexpected token: "-" "-"¶    at line 1, column 19.¶¶Was expecting one of:¶¶    ","¶    ";"¶    "ACTION"¶    "ALGORITHM"¶    "ANY"¶    "APPLY"¶    "ARRAY"¶    "AS"¶    "BYTE"¶    "CASCADE"¶    "CASE"¶    "CAST"¶    "CHANGE"¶    "CHAR"¶    "CHARACTER"¶    "COLUMN"¶    "COLUMNS"¶    "COMMENT"¶    "COMMIT"¶    "CONNECT"¶    "COSTS"¶    "CROSS"¶    "CYCLE"¶    "DESC"¶    "DESCRIBE"¶    "DISABLE"¶    "DIV"¶    "DO"¶    "DUPLICATE"¶    "ENABLE"¶    "END"¶    "EXCLUDE"¶    "EXTRACT"¶    "FALSE"¶    "FIRST"¶    "FN"¶    "FOLLOWING"¶    "FOR"¶    "FORMAT"¶    "FULL"¶    "GROUP"¶    "HAVING"¶    "INDEX"¶    "INNER"¶    "INSERT"¶    "INTERVAL"¶    "ISNULL"¶    "JOIN"¶    "JSON"¶    "KEY"¶    "LAST"¶    "LEADING"¶    "LEFT"¶    "LOCAL"¶    "MATERIALIZED"¶    "NATURAL"¶    "NO"¶    "NOLOCK"¶    "NULLS"¶    "OF"¶    "OPEN"¶    "ORDER"¶    "OUTER"¶    "OVER"¶    "PARALLEL"¶    "PARTITION"¶    "PATH"¶    "PERCENT"¶    "PIVOT"¶    "PRECISION"¶    "PRIMARY"¶    "PRIOR"¶    "RANGE"¶    "READ"¶    "REPLACE"¶    "RIGHT"¶    "ROW"¶    "ROWS"¶    "SCHEMA"¶    "SEPARATOR"¶    "SEQUENCE"¶    "SESSION"¶    "SIBLINGS"¶    "SIGNED"¶    "SIZE"¶    "SKIP"¶    "START"¶    "STRAIGHT_JOIN"¶    "SYNONYM"¶    "TABLE"¶    "TEMP"¶    "TEMPORARY"¶    "TIMEOUT"¶    "TO"¶    "TOP"¶    "TRUE"¶    "TRUNCATE"¶    "TYPE"¶    "UNSIGNED"¶    "VALIDATE"¶    "VALUE"¶    "VALUES"¶    "VIEW"¶    "WHERE"¶    "WINDOW"¶    "XML"¶    "ZONE"¶    <EOF>¶    <K_DATETIMELITERAL>¶    <K_DATE_LITERAL>¶    <K_NEXTVAL>¶    <S_CHAR_LITERAL>¶    <S_IDENTIFIER>¶    <S_QUOTED_IDENTIFIER>¶

#### Steps to reproduce, if exist:

![image](https://user-images.githubusercontent.com/3433187/132300375-eebbb0a4-e961-4167-b760-ade01b7558bc.png)

**Comment by Matvey16** [comment]
@analogstar Was the name of your table quoted in your query? I mean was it `user-info` or `"user-info"`

**Comment by Matvey16** [comment]
@analogstar Thank you for the report. We will work on that

**Comment by uslss** [comment]
verified
