### ISSUE TITLE
altibase for query plan.

### ISSUE THREAD

**Issue by davidoff2500** [dbeaver/dbeaver#13828]
**Is your feature request related to a problem? Please describe.**
The company is required to submit an associated query execution plan when adding columns and creating tables.
Altibase has the hassle of entering the server directly and performing it, and I hope this tool shows it through the plan window.

**Describe the solution you'd like**
When running like an orange tool, I hope that the plan window will also appear on the tab next to the result window.

**Additional context**
thank you for everything.

**Comment by Matvey16** [comment]
@davidoff2500 Sorry, i'm not sure I unerstood this right.
Correct me if i'm wrong here. You want an option to execute a query and execution plan at the same time with one click?

**Comment by davidoff2500** [comment]
> @davidoff2500 Sorry, i'm not sure I unerstood this right.
> Correct me if i'm wrong here. You want an option to execute a query and execution plan at the same time with one click?

similar...
display query plan next to query result tab.
so when i execute query, it show result and plan( plan can be located next to result tab...)

Please understand that misunderstanding can occur due to poor English.

thank you.

**Comment by LonwoLonwo** [comment]
Altibase, with support of the execution plan, was added in the latest DBeaver version.
Please check it: https://dbeaver.io/download/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
