### ISSUE TITLE
UI font in tab titles issue in Windows

### ISSUE THREAD

**Issue by sandnima** [dbeaver/dbeaver#13821]
#### System information: 
- Operating system (distribution) and version: Windows x64
- DBeaver version: 21.2.0.202108310918

#### I just faced this corrupted tab title fonts when I installed DBeaver for the first time
![tempsnip](https://user-images.githubusercontent.com/46921550/132321580-c4cc2d9d-dcc0-4402-91d2-3c7a35522ed2.jpg)

**Comment by uslss** [comment]
duplicates #13666

**Comment by uslss** [comment]
@sandnima what locale and language are used in your OS?

**Comment by sandnima** [comment]
> @sandnima what locale and language are used in your OS?

Windows display language is English (US)
System locale is English (US)
Region was Iran when installed, I changed to US (not fixed)
Also my msn feed language is set to German (if it matters)

**Comment by uslss** [comment]
Did you try to reset UI settings and workspace state? (Main menu: File - Reset UI settings / Reset Workspace State)
Does this issue appear after the update to 21.2.0 only?

**Comment by sandnima** [comment]
> Did you try to reset UI settings and workspace state? (Main menu: File - Reset UI settings / Reset Workspace State)
> Does this issue appear after the update to 21.2.0 only?

I reinstalled version 21.2.0 and didnt fixed
I installed version 21.1.5 and 21.0.5 too, they have the same issue

**Comment by Matvey16** [comment]
@sandnima How are you starting DBeaver? With a desktop shortcut created during install?

**Comment by sandnima** [comment]
> @sandnima How are you starting DBeaver? With a desktop shortcut created during install?

From Start Menu>Recently added
I also run it from program files
No difference

**Comment by Matvey16** [comment]
Can you check what language packs are installed on your system? You can check it in windows settings > language

**Comment by sandnima** [comment]
> Can you check what language packs are installed on your system? You can check it in windows settings > language

English (United States) and Persian

**Comment by Matvey16** [comment]
@sandnima And you chose English language during installation, correct?

**Comment by sandnima** [comment]
> @sandnima And you chose English language during installation, correct?

Of course yes
And I would point it asks me twice about language during installation. Normal?

**Comment by Matvey16** [comment]
Can you post a screenshot of your language window in Windows time a and language settings? And copy a text from installation information of DBeaver

![kPSTClOstn](https://user-images.githubusercontent.com/82543000/134468983-8115990a-1f03-43e2-a857-1d5e0bfe1e85.gif)

**Comment by sandnima** [comment]
@Matvey16 
## Screenshots:
![sc-1](https://user-images.githubusercontent.com/46921550/134472103-1871c9b7-ad17-4851-bfb5-b8f548741bef.JPG)
![sc-2](https://user-images.githubusercontent.com/46921550/134472117-86e12458-67b3-460e-a0ec-6a3ca64fec4c.JPG)

## Installation information (in this txt file):
[installation-conf.txt](https://github.com/dbeaver/dbeaver/files/7215820/installation-conf.txt)

**Comment by Matvey16** [comment]
@sandnima That is a known eclipse bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=551965 , that we can't fix unfortunately. It is connected to fonts installed on your machine and a workaround as described on Eclipse board is to change theme to classic or manually change fonts.

**Comment by flambchap** [comment]
We have a customer with the same issue.

**Comment by Matvey16** [comment]
@akilovich The workaround can be found in Eclipse ticket above. I'm not sure if we can fix it ourselves.

**Comment by flambchap** [comment]
We definitely cannot fix it from our side. However, the ticket you mentioned is closed for some reason with the status CLOSED NOT_ECLIPSE. This **is** an Eclipse issue, IMHO. I assume they don't want to fix this. Unfortunately, we need to wait for a miracle at this point :(

**Comment by bimantara679** [comment]
> #### System information:
> * Operating system (distribution) and version: Windows x64
> * DBeaver version: 21.2.0.202108310918
> 
> #### I just faced this corrupted tab title fonts when I installed DBeaver for the first time
> ![tempsnip](https://user-images.githubusercontent.com/46921550/132321580-c4cc2d9d-dcc0-4402-91d2-3c7a35522ed2.jpg)

![tab title error dbeaver](https://github.com/dbeaver/dbeaver/assets/55911545/78a26fd2-f1ba-4c2d-b017-3db24bce59ff)

i fixed it when i change the main font in preference
