### ISSUE TITLE
Redshift drivers: upgrade driver to 2.x and switch to Maven repository

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#13820]
Also we need to be able to force optional Maven dependencies load. Redshift driver has all AWS SDK deps as optional.

**Comment by uslss** [comment]
verified

**Comment by deepaksenthilkumar** [comment]
@serge-rider 
@ShadelessFox @akilovich @Matvey16 
This breaks a number of functionalities within Redshift as DBeaver relies on the Postgres flavor of the driver. It should use 1.x driver not 2.x driver

**Comment by ShadelessFox** [comment]
Hello again @deepaksenthilkumar,

What kind of functionality is broken?

**Comment by deepaksenthilkumar** [comment]
One thing on top of my head is
>>>>Right click and get DDL.

It won’t return Postgre object. Using 2.x means we can’t take advantage of
all the Postgre extensions in the code, it has to be 1.x driver for that.
-- 
SD

**Comment by ShadelessFox** [comment]
There's an issue for this problem: #13523. We should investigate and it fix.
