### ISSUE TITLE
select query was garbled.

### ISSUE THREAD

**Issue by gksmfqorcjs** [dbeaver/dbeaver#13825]
#### System information: 
- Operating system (distribution) and version
- windows10
- 
- DBeaver version
- dbeaver-ce-21.0.2-win32.win32.x86_64
- dbeaver.ini file add line
- Dfile.encoding=UTF-8

- Additional extensions

#### Connection specification:
- Database name and version
- mariadb 10.1.13
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Steps to reproduce, if exist:

When I search by query, it doesn't come out in the language I want, but in another language.
The same goes for changing the character set.
The first 200row(default Result-set fetch size) are correct, but if you scroll and want a lot of data, it doesn't come out in the desired language.

![image](https://user-images.githubusercontent.com/43075551/132355823-a407a94e-7682-4df2-bdd0-36823ea37f1d.png)
this first select data(200 row)

![image](https://user-images.githubusercontent.com/43075551/132356195-5896dbf5-593e-4fcb-bdf6-4def710ecad5.png)
this data selected after scrolling to the bottom

**Comment by ShadelessFox** [comment]
Hello @gksmfqorcjs,

Please provide more information. 

* What happens when you change max fetch size?
* Does it happen when you manually perform select?

It's not encoding problem, by some reason strings turned into hexadecimal representation.

**Comment by gksmfqorcjs** [comment]
What happens when you change max fetch size?
 -> If you change the petch size, the changed row is output correctly, but if you scroll down and output the data after that, the same phenomenon occurs.

Does it happen when you manually perform select?
 -> It doesn't happen when you do it passively. 
For example, if you set the fetch size to 300 and scroll down to row 300, data is normally output, but when rows 301 and later are selected, the result that exposes existing 1~300+ rows is also changed.

Data comes out normally in other databases, but strangely in the database I want.

Is there anything I need to change settings?

**Comment by gksmfqorcjs** [comment]
> Hello @gksmfqorcjs,
> 
> Please provide more information.
> 
> * What happens when you change max fetch size?
> * Does it happen when you manually perform select?
> 
> It's not encoding problem, by some reason strings turned into hexadecimal representation.

What happens when you change max fetch size?
-> If you change the petch size, the changed row is output correctly, but if you scroll down and output the data after that, the same phenomenon occurs.

Does it happen when you manually perform select?
-> It doesn't happen when you do it passively.
For example, if you set the fetch size to 300 and scroll down to row 300, data is normally output, but when rows 301 and later are selected, the result that exposes existing 1~300+ rows is also changed.

Data comes out normally in other databases, but strangely in the database I want.

Is there anything I need to change settings?

**Comment by ShadelessFox** [comment]
Thanks for response.

Does this happen with any other MariaDB database?

**Comment by gksmfqorcjs** [comment]
> Thanks for response.
> 
> Does this happen with any other MariaDB database?


Local mariadb worked fine. I haven't tested it other than the local mariadb.
I verified that mysql is working properly.

**Comment by Matvey16** [comment]
Hello @gksmfqorcjs . Can you please give me a DDL for this table to try to reproduce it and understand what is actually special about it.

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info that will help to reproduce an issue
