### ISSUE TITLE
Cannot find client home ???

### ISSUE THREAD

**Issue by THLCX** [dbeaver/dbeaver#13836]
#### System information: 
- Ubuntu 20
- DBeaver version 21.2.0

#### Connection specification:
- Database name and version : MariaDb locally

#### Describe the problem you're observing:

I have a fresh install of Ubuntu 20, nothing special.
I installed mariadb (works).
When I try to use DBeaver to connect to mariadb, in localhost, local client is "not present".
I can't understand how such a basic simple use does not work.
When I try to navigate to /usr using dbeaver I got permission denied... But never got any problem accessing /usr with any file explorer...
what can I do ?

#### Steps to reproduce, if exist:

Install Ubuntu.
Install MariaDb.
Install DBeaver-ce.
Juste use it and the bug is here...

**Comment by THLCX** [comment]
Okay, solution found :
When installing from Ubuntu software manager, Ubuntu installs a snap that restrict access to /usr folder... Where client mysql is located.
Solution is a manual install.

**Comment by uslss** [comment]
#13608
