### ISSUE TITLE
Metadata search doesn't work for table columns in DB2

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#13831]
#### System information: 
- DBeaver version 21.2.0 UE

#### Connection specification:
- Database name and version DB2 Express
- Driver name DB2 LUW

#### Describe the problem you're observing:
Metadata search doesn't find table columns.

#### Steps to reproduce, if exist:
1. Open Metadata Search and try to find an existing column.

**Expected:** Object is found
**Actual:** Nothing is found

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
