### ISSUE TITLE
select query was garbled. (#13825)

### ISSUE THREAD

**Issue by gksmfqorcjs** [dbeaver/dbeaver#13835]
System information:
Operating system (distribution) and version

windows10

DBeaver version

dbeaver-ce-21.0.2-win32.win32.x86_64

dbeaver.ini file add line

Dfile.encoding=UTF-8

Additional extensions

Connection specification:
Database name and version
mariadb 10.1.13
Driver name
Do you use tunnels or proxies (SSH, SOCKS, etc)?
Describe the problem you're observing:
Steps to reproduce, if exist:
When I search by query, it doesn't come out in the language I want, but in another language.
The same goes for changing the character set.
The first 200row(default Result-set fetch size) are correct, but if you scroll and want a lot of data, it doesn't come out in the desired language.

---

Sorry to my mistake closed an issue
issue : #13825

What happens when you change max fetch size?
-> If you change the petch size, the changed row is output correctly, but if you scroll down and output the data after that, the same phenomenon occurs.

Does it happen when you manually perform select?
-> It doesn't happen when you do it passively.
For example, if you set the fetch size to 300 and scroll down to row 300, data is normally output, but when rows 301 and later are selected, the result that exposes existing 1~300+ rows is also changed.

Data comes out normally in other databases, but strangely in the database I want.

Is there anything I need to change settings?

**Comment by ShadelessFox** [comment]
I will reopen an original issue.
