### ISSUE TITLE
Code Folding disappears after a script is saved

### ISSUE THREAD

**Issue by mwon-mercato** [dbeaver/dbeaver#13860]
Apologies if this is a known issue, I checked existing tickets and did a bunch of searches... 

#### System information: 
- Operating system: Windows 10 Pro Version 10.0.19043 Build 19043
- DBeaver version: 21.2.0.202108310918
- Additional extensions: None

#### Connection specification:
- Database name and version: Redshift
- Driver name: Apologies, I am not sure what this is.
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  Yes,  I use SSH.

#### Describe the problem you're observing:
I have enabled Code Folding by right clicking and selecting 'Foldings Enabled'.  When writing a new SQL script code folding works as expected.  However, after I rename the script, while code folding is still enabled the the code folding arrows disappear and I am no longer able to fold.

#### Steps to reproduce, if exist:
1. With code folding enabled, create a new sql script.
2. Write a SQL query.  You will notice code folding available.
3. Rename the script.  After renaming, you should see the code folding disappear.

#### Include any warning/errors/backtraces from the logs
- There are no errors.

**Comment by uslss** [comment]
thank you for the report

**Comment by uslss** [comment]
verified
