### ISSUE TITLE
current_time PostgreSQL bug

### ISSUE THREAD

**Issue by gordubal** [dbeaver/dbeaver#13866]
Hello all!
#### System information: 
- Operating system (distribution) and version:  Windows 7 x 64
- DBeaver version :        21.2.0.202108291732

#### Connection specification:
- Database name and version POSTGRESQL
- Driver name Postgresql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I write query
select current_time
and get a result on 1 hour more than its real time

Example
On local computer - 14:45:00
On db comp 14:45:00
If I run "select current_time" with pgAdmin 4 v4 - 14:45:00
If i run "select current_time" with DBeaver (version 21.2.0.202108291732) I get 15:45:00

By the way current_timestamp  works correct
It means that "select current_timestamp" with DBeaver (version 21.2.0.202108291732) I get 2021-09-10 14:45:55

What problem?

#### Include any warning/errors/backtraces from the logs
no data in error log

Sorry, I'm newby

**Comment by Matvey16** [comment]
@gordubal did you change anything in Data format settings? Also can you try running this query with time formatting disabled?
![dbeaver_NHg8AJmjK4](https://user-images.githubusercontent.com/82543000/132852971-bbad17fb-6ae4-405a-a529-489e3bc86296.png)

**Comment by gordubal** [comment]
Thank you, it helps
