### ISSUE TITLE
Ubuntu ppa not updated since version 21.1.3

### ISSUE THREAD

**Issue by rproserpio** [dbeaver/dbeaver#13868]
The last version on https://launchpad.net/~serge-rider/+archive/ubuntu/dbeaver-ce was last updated on 2021-07-19.
Is this a problem or the ppa is not maintained? The website still links to it.
Thank you

**Comment by tati-kru** [comment]
We will update PPA package after version 21.2.1 release.

**Comment by serge-rider** [comment]
Done

**Comment by rproserpio** [comment]
Thanks!

**Comment by obarbachan** [comment]
Hi! This issue seems to be happening again.
