### ISSUE TITLE
Oracle package (PLSQL) functions autocomplete not working, missing or new feature?

### ISSUE THREAD

**Issue by yevon** [dbeaver/dbeaver#13861]
#### System information: 
- Operating system: Windows 10
- DBeaver version: 21.2.0
- Additional extensions: Git

#### Connection specification:
- Database name and version: Oracle 19c
- Driver name: Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
Autocomplete for package functions and their parameters is not working, it just works for queries.

#### Steps to reproduce, if exist:
Open an oracle package and try to autocomplete anything, functon name, local variables etc not working, just if you start typing select * from you get autocomplete suggestions. Maybe I'm missing something or I don't know how to do it.

**Comment by Matvey16** [comment]
@yevon I'm not quite sure about steps to reproduce this. If you type a name of the package then dot like `schema_name.package_name.` and press <kbd>Ctrl + Space</kbd> you will get proposal with package contents, even without a <kbd>Ctrl + Space</kbd> shortcut, proposed autocomplete should appear, it just can take some time to find metadata. Are you doing something differently

![SvtsIbcueJ](https://user-images.githubusercontent.com/82543000/132855929-1d3dbe60-6421-426e-ad40-3daa3b4f67ea.gif)

**Comment by yevon** [comment]
From sql editor it just works fine, I mean in package editor, when you try to perform any autocompletion it doesn't work as it wants you to write anything in the form "Select * from", if you try to call directly to the procedure name it doesn't work. It would be nice also to autocomplete any text in current package, for local variable names etc.

![image](https://user-images.githubusercontent.com/121157/132856885-46056cfe-18d1-464b-8e8c-549e579704bb.png)

**Comment by yevon** [comment]
A simple begin end in sql editor doesn't work also:

![image](https://user-images.githubusercontent.com/121157/132857053-e4465eec-326d-4736-bb25-da3843890022.png)

**Comment by yevon** [comment]
Also you don't get any prompt if you don't write the schema name prior to the package name. It works in the from clause, but it doesn't work in the select clause:

![image](https://user-images.githubusercontent.com/121157/132857389-c82fe561-aefa-4a5e-8435-71e4786db17c.png)

![image](https://user-images.githubusercontent.com/121157/132857442-978f6b3b-1163-44f0-b054-17aa15d1416b.png)

![image](https://user-images.githubusercontent.com/121157/132857496-3a51356e-454e-43c6-a53f-bb5968fb83ff.png)

**Comment by Destrolaric** [comment]
Added HippieCompletion to check for in-script variables and suggest them based on similarity. Turned off by default, can be added via preferences. Needs to be tested on performance problems on large scripts. 
![image](https://user-images.githubusercontent.com/20579256/146345445-5ae4ff20-af37-4f63-b2e1-8a7569c490a4.png)
![image](https://user-images.githubusercontent.com/20579256/146345606-1b4867a1-f8d2-43c2-a820-d9fd66cce9ad.png)

**Comment by Destrolaric** [comment]
@yevon, thank you for your request. We added in-text autocompletion concerning the first part of the issue. The second part, related to BEGIN-END, is working as expected.

**Comment by yevon** [comment]
Perfect, thanks! I will have a look at it, looks promising. Will it be available in 21.3.2 or it is already on 21.3.1?

**Comment by Destrolaric** [comment]
@yevon It will be available in 21.3.2  :)

**Comment by uslss** [comment]
verified
