### ISSUE TITLE
Remove where keyword suggestion on insert into statement

### ISSUE THREAD

**Issue by orimarko** [dbeaver/dbeaver#13879]
#### System information: 
- Windows 10 Pro
- DBeaver version Version 21.1.4.202108020335

#### Connection specification:
- Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

#### Describe the problem you're observing:
 where keyword suggestion on insert into statement is wrong
INSERT INTO TABLEA WHERE isn't a valid syntax
https://docs.oracle.com/cd/B12037_01/appdev.101/b10807/13_elems025.htm
#### Steps to reproduce, if exist:
INSERT INTO TABLEA 
Click auto complete (Ctrl + Space)

A similar case in INSERT INTO is when choosing column names, 'WHERE' shouldn't be suggested, steps:
INSERT INTO TABLEA (
Click auto complete (Ctrl + Space)

#### Include any warning/errors/backtraces from the logs
NA

**Comment by Matvey16** [comment]
@orimarko Thank you for the report

**Comment by Matvey16** [comment]
Verified
