### ISSUE TITLE
Table column changes are immediately semi-discarded after Refresh (part 2)

### ISSUE THREAD

**Issue by elring** [dbeaver/dbeaver#13878]
#### System information: 
OS: Linux Mint 20
DBeaver version: 21.2.0

#### Connection specification:
Database: Postgresql 12

#### Describe the problem you're observing:
This issue is related to #12331 - the problem is not 100% solved.

#### Steps to reproduce, if exist:
Open any table, add any column. Do NOT save the table, do NOT close it. Open another table. Use refresh function in database navigator. The confirmation window opens, after denying the revert changes switch back to first table. The list of columns is reverted (created column is missing), but you can still save the changes witch Ctrl+S.

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
![OVQaqczvo5](https://user-images.githubusercontent.com/31996417/140711565-48f10748-64b0-4f7a-aa4b-f54bf124cb02.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
