### ISSUE TITLE
Cannot save result set without pointless clicking outside and inside

### ISSUE THREAD

**Issue by th** [dbeaver/dbeaver#13875]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
2.1.2.0
- Additional extensions
None

#### Connection specification:
- Database name and version
SQLite 3
- Driver name
SQLite
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
I have an open DB connection. I also have an SQL file with a simple select statement. On Executing it (Ctrl-Enter) the result set appears in a split window below.

When I now edit a field value in a row in the result set the shortcut Ctrl-s (Save) doesn't work, the edited value keeps a  yellowish background.

I need to click focus into somewhere else (in my case the Database Navigator) and back into the result set, and then saving works.

#### Steps to reproduce, if exist:
Edit a value in result set. Save.

**Comment by uslss** [comment]
@th unfortunately cannot reproduce it.
Could you provide a video of the issue?

**Comment by th** [comment]
Sure.

The keypresses aren't shown unfortunately, but I press Ctrl-S after I have edited the value (and the value is shown yellow), but before I execute the query again.

Then I click in the left pane, back into the result set, and Ctrl-S works, the yellow background is gone.

(Selecting File -->Save also works, but probably because in doing so I'm clicking away from the result set pane.)

![dbeaver](https://user-images.githubusercontent.com/153996/133414808-d366e2d7-2be9-4379-8f04-53408c488968.gif)

**Comment by uslss** [comment]
Unfortunately, it is hard to understand what is going wrong :( Could you provide video once again with Show keybinding when command is invoked through keyboard option enabled? Also it will be helpful if bottom toolbar with save/cancel/script button will be visible. Thanks in advance
![image](https://user-images.githubusercontent.com/31996417/133937791-72d3a8a1-53c4-4177-9e1a-f129c4dccb93.png)

**Comment by th** [comment]
![dbeaver](https://user-images.githubusercontent.com/153996/133983997-137b13a9-647c-482c-85eb-e9b45f516f1c.gif)

**Comment by uslss** [comment]
Unfortunately, still cannot reproduce (gif attached). Is it reproducible for you against the recent version?
![8YQaUZKHsO](https://user-images.githubusercontent.com/31996417/134405040-7fbf95ac-db29-45f4-9ab9-f86c1c9156c5.gif)

**Comment by th** [comment]
Yes, using the current release I still see my probklem. I don't know, I guess you can mark it non-reproducible.

**Comment by uslss** [comment]
@th unfortunately, still cannot reproduce it. is it still present for you against the recent(21.3.1) version?

**Comment by uslss** [comment]
There has been no update on the issue for a long time.
If it is still actual for you against the recent version, please reopen it.
