### ISSUE TITLE
[macOS] The SQL script is cropped in the persist changes dialog

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#13882]
#### System information: 
- Operating system (distribution) and version: macOS 11.4
- DBeaver version DBeaver UE 21.2
- Additional extensions: None

#### Describe the problem you're observing:
The SQL script is cropped in the persist changes dialog.

#### Steps to reproduce, if exist:
1. Open entity editor for a table.
2. Add a column.
3. Clock 'save'

The 'Persist Changes' dialog opens. It will look something like this: 
![Screenshot 2021-09-09 at 18 42 22](https://user-images.githubusercontent.com/26031301/133079329-3e910e72-4e6d-45e1-8342-8d53d973130b.png)

Workaround:
Resize the dialog in any direction.

![Screenshot 2021-09-09 at 18 42 52](https://user-images.githubusercontent.com/26031301/133079456-a1a29dc0-bfb4-4ecb-aab2-409861c90b70.png)

**Comment by flambchap** [comment]
It potentially can be fixed in a similar fashion to [this](https://github.com/dbeaver/dbeaver/issues/11526) ticket.

**Comment by kseniiaguzeeva** [comment]
verified
