### ISSUE TITLE
Nested task folders support.

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#13887]
Need to add the ability to create nested task folders.
(As connections nested folders)

![2021-09-13 18_24_46-DBeaver 21 2 1](https://user-images.githubusercontent.com/45152336/133111914-4e7f0aa2-9427-4c01-b111-c3f93f19a34c.png)

**Comment by ShadelessFox** [comment]
Please don't use currently focused folder when creating new tasks and instead use event source.

https://user-images.githubusercontent.com/35821147/135605933-2b49b291-0b8d-43ad-9e06-3bfa0f02b2f8.mp4
