### ISSUE TITLE
Change default foreign key dictionary settings

### ISSUE THREAD

**Issue by fjf2002** [dbeaver/dbeaver#13885]
**Is your feature request related to a problem? Please describe.**
From https://dbeaver.io/forum/viewtopic.php?f=2&t=668 I learnt that 
* The foreign dictionary uses by default "any column which name contains one of next strings: title, name, label, display, description, comment or remark. If no such column found then first varchar column is used.". 
* As far as I understand, I can override this behaviour on a per-table basis. This can be tedious: I have many tables with similar columns, but the column names do not match the default strings as described above.

**Describe the solution you'd like**
I would be more productive if I could change the default strings as mentioned above, for example in window->preferences (instead of configuring it for each table separately).

**Comment by ShadelessFox** [comment]
Implemented:

![image](https://user-images.githubusercontent.com/35821147/153191029-4d24afb0-e7c7-4993-aad9-34d15b180f8d.png)

This preferences page can also be accessed via link in the <kbd>Define Description</kbd> dialog.

**Comment by uslss** [comment]
verified

**Comment by fjf2002** [comment]
Thank You.
