### ISSUE TITLE
SSH jump server: Can't change destination host port (always uses `22`)

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#13883]
> I just tried the new "jump server" option in the connections settings and hit a bug. The client always tries to connect to port 22 on the final server, regardless what I try to set as Port.
The connection to the jump server uses the correct IP/Port combination, which I enter in the settings page, but the next hop always tries to connect to Port 22. Or do I have to enter the changed port of the final destination server in another configuration field?

**Comment by Matvey16** [comment]
Verified
