### ISSUE TITLE
Incorrect localization name

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13898]
Based on https://github.com/dbeaver/cloudbeaver/issues/475.

Could you please change  中国人 (Taiwan in English) on ‘中文-简体’ or '中文-繁體’ in localisation settings?
![Screenshot 2021-09-14 at 11 38 24](https://user-images.githubusercontent.com/51405061/133224986-0c3efa6e-7eee-4cdb-9b8f-ac5742e4f7c9.png)

**Comment by serge-rider** [comment]
It comes from Eclipse Babel localization

**Comment by serge-rider** [comment]
Please test in EA version of CE.

**Comment by uslss** [comment]
verified
