### ISSUE TITLE
forced disconnect

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#13896]
Windows 10 64
DBeaver 21.2.0
Postgres 12

This error started in 21.2.0 version.

CASE:
I have three dababase in veriable servers.

1. I worked with database1 on server1 and close all window because work was ended.
2. Disconnect from database1 on server1 and connect to database2 on server2 and work on it. and close all window because work was ended

I see error on database1
![image](https://user-images.githubusercontent.com/61137576/133198201-a2ad3a1a-1f91-4fce-9060-3ee3b2238df1.png)

Perhaps this is due to the fact that I recently installed this option on all bases

![image](https://user-images.githubusercontent.com/61137576/133198423-8187df57-91ed-4cd6-8bed-582763ee4ef2.png)

**Comment by uslss** [comment]
@detkliff could you provide [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by detkliff** [comment]
![image](https://user-images.githubusercontent.com/61137576/133747459-300d3ffc-c39d-475d-9c02-59b718cde002.png)

**Comment by detkliff** [comment]
from log file
![image](https://user-images.githubusercontent.com/61137576/133747928-11182593-dccc-4e4b-b8ad-642724a31abb.png)

**Comment by uslss** [comment]
@detkliff , sorry for the late response. Is the issue persist in 21.3.1?

**Comment by uslss** [comment]
There has been no update on the issue for a long time.
If it is still present, feel free to reopen it.
