### ISSUE TITLE
MySQL Use SSL Defaults cause cert error.  Wonder if a low priority feature req to add some user instruction might save frustration.

### ISSUE THREAD

**Issue by makingglitches** [dbeaver/dbeaver#13900]
With a standard localhost setup of MySQL 8.0 Community edition.

Following error occurs with the ssl defaults checked, once Use SSL is enabled.

Could not load trustJKS keystore from _file:/home/_{user}_/.local/share/DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.core/security/mysql8-17bdc0e09b2-d25dddb891738b4-ssl.jks_
  java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
  java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
    the trustAnchors parameter must be non-empty
    the trustAnchors parameter must be non-empty

This occurs when the only option under ssl that has been checked is "Verify server certifcate" when "Use SSL" has been checked.

Even if this gets marked as "User Error" makes me wonder, maybe some explanation being added to that screen is a good idea ?  Little tip that says "Not necessary for localhost installations" Or "Uncheck this for localhost connections. Unless testing cert store ?"

If I wasn't used to experimenting I'd have likely grown frustrated and used a different product :P not that MySql doesn't seem to be attempting to do that very thing with some of its nuisances.

I'm reporting this becomes it was a tad frustrating, and it also threw differing errors such as "Unable to to Retrieve Public Key" after a fresh reboot each time (Which was of course overcome with the available "Enable Public Key Retrieval" option enabled.)

I guess the question is why is this enabled by default ? I can see it if you're connecting to a remote server, but a local installation doesn't make much sense.

![Screenshot from 2021-09-14 07-28-37](https://user-images.githubusercontent.com/53788764/133249919-08b93fc4-bff6-4319-a2b8-a127a56e3a86.png)

**Comment by makingglitches** [comment]
I'm sorry for the jumbled mass of repeat edits. The behavior of the project seems to have changed right before my eyes, without me changing backend settings.

**Comment by makingglitches** [comment]
Perhaps however because this is a java exception related to what looks like a cert store, there be a catch-block added at the very least with a more user friendly message, since this is not an exception that should lead to a process exit ?

**Comment by makingglitches** [comment]
On restart of the server/client machine the following error shows back up on the connections not using ssl, with the verify server certificate option selected:

> Public Key Retrieval is not allowed

**Comment by makingglitches** [comment]
Checking the allow public key retrieval option gets rid of this.

**Comment by makingglitches** [comment]
@uslss apparently this is a bug. the stored connections settings for ssl reset themselves, and the logins even without ssl fail after a system reboot.

**Comment by uslss** [comment]
@makingglitches could you clarify your issue step by step? as for me, ssl isn't enabled by default on connection creation

**Comment by makingglitches** [comment]
Yeah install mysql, use the default configuration, install dbeaver, follow the steps above.

**Comment by uslss** [comment]
@makingglitches sorry for the late response. What OS do you use?

**Comment by makingglitches** [comment]
> @makingglitches sorry for the late response. What OS do you use?

Fedora

**Comment by makingglitches** [comment]
> @makingglitches sorry for the late response. What OS do you use?

Oh additionally I can't quite place where but I've seen this error before with software that uses Java regarding some strange cert store issue

**Comment by uslss** [comment]
is it still reproducible against the recent version?

**Comment by uslss** [comment]
There has been no update on the issue for a long time.
If it is still present, feel free to reopen it.

**Comment by mohd-akram** [comment]
I'm getting this same error when enabling SSL:

```
Could not load trustJKS keystore from file:/home/user/.local/share/DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.core/security/mysql8-1828c2f4134-172d11ec20859971-ssl.jks
  java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
  java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
    the trustAnchors parameter must be non-empty
    the trustAnchors parameter must be non-empty
```

I'm not sure how to fix this (I've already verified that the server is fine using `mysql --ssl`).

EDIT: I've verified that the CA cert that the server uses (ISRG Root X1) is in DBeaver's CA certs via:

```shell
keytool -list -keystore /usr/share/dbeaver-ce/jre/lib/security/cacerts | grep -i isrg
```

Not sure why it isn't using it.
