### ISSUE TITLE
Escaping in Configure Filters

### ISSUE THREAD

**Issue by tSpiny** [dbeaver/dbeaver#13909]
It doesn't work at all. I have 2 schemas in my db:  
- `dwh2xyz`  
- `dwh_xyz`

I tried to filter only `dwh_xyz` with `dwh\_*` . And it didn't work.

_Originally posted by @zSpiny in https://github.com/dbeaver/dbeaver/discussions/8767#discussioncomment-1331759_

**Comment by uslss** [comment]
@zSpiny did you try to include or exclude mentioned schema? thanks in advance for the response

**Comment by uslss** [comment]
Also, what database do you use?

**Comment by tSpiny** [comment]
@uslss I'm trying to only **include** this schemas. I use Oracle. Dbeaver version is 21.1.5

**Comment by tSpiny** [comment]
I mean, when I filter with `dwh\_*`, I don't see any schemas at all. And when I use `dwh_*`, I see both schemes, cause `_` is a mask symbol

**Comment by uslss** [comment]
thanks for the clarification and report

**Comment by Destrolaric** [comment]
Oracle needs ESCAPE notation to be added to properly parse any character after \ probably it is not only oracle which needs it.

**Comment by p91paul** [comment]
yep, \ isn't an escape symbol unless you explicitly tell oracle it is in the exclude clause for like, so I think this is expected.
What happens if you include them both, then use the exclusion filter to remove the dwh2xyz?

**Comment by Destrolaric** [comment]
Added fix for Oracle, probably need to check other db's for same problem.

**Comment by uslss** [comment]
Include filter are case sensitive, but exclude is case-insensitive.
Exclude `TEST\_*` mask:
![image](https://user-images.githubusercontent.com/31996417/144486199-a5b34619-a655-4abb-8ae4-793043e1f595.png)
Include:
![image](https://user-images.githubusercontent.com/31996417/144486270-42eace16-5e0e-4d0b-87ee-6683cd5b2188.png)
So the highlighted database are excluded, but not included:
![image](https://user-images.githubusercontent.com/31996417/144486493-a9851fa6-b3de-4d24-93e9-749924b4760e.png)

**Comment by uslss** [comment]
still reproducible
![image](https://user-images.githubusercontent.com/31996417/144807107-72fb60dd-e901-40b6-a836-392a5ecd3482.png)
![image](https://user-images.githubusercontent.com/31996417/144807157-eb48ce3e-44f8-46ec-818b-c273ffe90635.png)

**Comment by uslss** [comment]
created issue #14810 
verified
