### ISSUE TITLE
Redesign dictionary panel UI

### ISSUE THREAD

**Issue by nan0tube** [dbeaver/dbeaver#13907]
**Is your feature request related to a problem? Please describe.**
When the dictionary tab is opened, not all rows of the referenced table are loaded. There is no ability to load the next page of dictionary results. 

When the referenced table is of a certain size (say 1000 rows), not all rows will be loaded in the dictionary tab, and the missing rows are not available for selection.

**Describe the solution you'd like**
Enable pagination in dictionary tab, so that a user is able to browse for the desired row.

**Describe alternatives you've considered**
Search bar that lookup certain columns in the referenced table. However, pagination may still be required as there may be a large number of results.

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by nan0tube** [comment]
In the meantime, can the number of rows fetched for the dictionary tab be configured?
