### ISSUE TITLE
Oracle schema not shown

### ISSUE THREAD

**Issue by afimuc** [dbeaver/dbeaver#13901]
#### System information: 
- Windows 10 Build 19043.1165
- DBeaver version 21.2.0.202108310918

#### Connection specification:
- Oracle XE 11g
- Driver name: ojdbc11 version 21.1.0.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Some schemas are not shown in the schema list.
A newly created schema disappears on refresh, and never appears again, even after disconnect/reconnect.
No schema filters are set.
The schema appears in `SELECT * FROM all_users`.
Checking "Show system object", "Show utility objects" in "Navigator view" settings shows some additional schemas, but not the missing one.

#### Steps to reproduce, if exist:
See https://pasteboard.co/IXzopYxWvE2Y.gif

#### Include any warning/errors/backtraces from the logs
No errors in the logfile

**Comment by uslss** [comment]
@afimuc could you check if Hide empty schemas is disabled in Connection properties?
![image](https://user-images.githubusercontent.com/31996417/133264304-66bf352b-6953-4cb7-8a33-f9695ebcee3a.png)

**Comment by afimuc** [comment]
@uslss That was the reason, thank you!
