### ISSUE TITLE
Option to disable long-lived connections

### ISSUE THREAD

**Issue by kpconnell** [dbeaver/dbeaver#13902]
**Is your feature request related to a problem? Please describe.**
If you have intermittent network connectivity, the amount of time for a query to decide the connection is no longer viable is off the charts.

**Describe the solution you'd like**
Consider all operations to be book ended by a connection open and close.  This is how most modern software works.  Connections even with mobile networks typically only take 10-200ms, and for anyone who is using a query tool this is completely inconsequential.  If you can't get your libraries to make connections this fast then there is your problem. 

**Describe alternatives you've considered**
I could spend years of my life waiting for dbeaver to figure out the connection needs to be re-connected I suppose.

**Additional context**

**Comment by uslss** [comment]
@kpconnell did you try to change timeouts values in connection properties? probably, it'll resolve your issue
![image](https://user-images.githubusercontent.com/31996417/133287755-cf603c7f-9643-4f4e-8042-c24b1ded4197.png)

**Comment by kpconnell** [comment]
The feature request is to eliminate the concept of long lived connections - Not be able to adjust timeouts for long lived connections.  It is a fundamental flaw.

**Comment by Matvey16** [comment]
Getting rid of long-lived connections is disastrous if we are working with transactions. But it will be good to add an option in the connection settings so user can choose if he wants to use them or not.

**Comment by serge-rider** [comment]
We can't open new connection for every operation.
For many drivers connection time is very long (up to several minutes). Also network configuration (including tunnels, VPNs, etc) may slow down connection time even in modern drivers.

I've added a config option "Close idle connections". It helps to reduce big number of idle connections from UI clients.
Let's see how it works.

![image](https://user-images.githubusercontent.com/6398845/151976773-468597c2-9b9f-4584-aef8-ed277a94f8b9.png)

**Comment by Matvey16** [comment]
Value is not saved after closing, it resets to zero after restart, but if `Keep-Alive` have some value it will be copied to `Close idle` after restart.

![dbeaver_8L6ScKAkhJ](https://user-images.githubusercontent.com/82543000/152017300-0a8fb1e1-4ea9-447a-84dd-97b5acd9f4d2.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
