### ISSUE TITLE
Cannot switch Catalog/Schema when DBeaver connects to InterSystem Cache

### ISSUE THREAD

**Issue by jpg1024** [dbeaver/dbeaver#13919]
#### System information: 
- Operating system (distribution) and version

Windows 10

- DBeaver version

21.2.0.202108291732

- DataBase version

Cache' Studio Client  2016.2.0 Build 736
Server Cache for Windows (x86-64) 2016.2 (Build 736_0_16871U)

#### Connection specification:
- Database name and version

Cache' Studio Client  2016.2.0 Build 736
Server Cache for Windows (x86-64) 2016.2 (Build 736_0_16871U)

- Driver name

com.intersys.jdbc.CacheDriver

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

no

#### Describe the problem you're observing:

I use Windows 10 and the latest version of DBeaver to connect to the InterSystem Cache database. After the connection is successful, I select Schema in the Choose Catalog/Schema pop-up window, but I cannot switch successfully. What do I need to do? Thank you.

![20210916094521](https://user-images.githubusercontent.com/13309008/133537506-cd869c43-4f57-4ef3-94ac-bb8ae1ba31c0.png)

**Comment by uslss** [comment]
thanks for the report
Unfortunately, we don't have Cache server to test for now

**Comment by jpg1024** [comment]
> thanks for the report
> Unfortunately, we don't have Cache server to test for now

OK, thanks.

I configured the default schema in front of the statement through Preferences->Editors->SQL Editor->Template.

For example (SQLUser is my default Schema):

Name: sf
Mode: select * from SQLUser.${table};

In this way, the Schema can be automatically brought out when entering sf. The problem caused by the inability to switch the Schema is temporarily handled.
