### ISSUE TITLE
Connect to mutliple projects using google BigQuery service account

### ISSUE THREAD

**Issue by r1evan** [dbeaver/dbeaver#13916]
Hi,

I'm trying to access multiple projects available in the provided google bigquery service account.

I'm able to access only the project we can see in bold. I can select the other available projects from the dropdown but still the query gets executed against the project that we see in bold.

Need help.

Thanks is advance.

Regards,
Revan
![image](https://user-images.githubusercontent.com/90771330/133432911-0786fd1e-fc1d-4e0d-985c-58b38977e973.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by Destrolaric** [comment]
@r1evan Hi, I tried to reproduce this issue, with a select query and it worked correctly when the full path to schema was written. Could you describe your issue in more detail?

**Comment by r1evan** [comment]
Hi George,

But it does not work when we select the required database from the database list as shown in the below screenshot.

***@***.***

It still queries the default database given while defining the connection. See the below screenshot:

***@***.***

Can you help me a way of passing all the available projects.

Regards,
Revan

**Comment by Destrolaric** [comment]
@r1evan, I think screenshots have failed to load correctly. I think you need to resend them.

**Comment by r1evan** [comment]
Attached the screenshots as images

**Comment by Destrolaric** [comment]
@r1evan, I think the Github email reply doesn't support attachments. At least I couldn't find a way to see them.

**Comment by Destrolaric** [comment]
@r1evan If possible, can you send screenshots directly via Github?

**Comment by r1evan** [comment]
![pic1](https://user-images.githubusercontent.com/90771330/150084961-79939903-ab11-4e4b-bd96-dbc2eca580e2.png)
![pic2](https://user-images.githubusercontent.com/90771330/150084968-1727b000-bf39-4a63-8aec-97e3e7ad2505.png)

Attached the images. Can you confirm if you're able to view them.

**Comment by Destrolaric** [comment]
Yes, everything is good

**Comment by Destrolaric** [comment]
@r1evan Can you tell, are you writing the full path to the schema in a query?

**Comment by r1evan** [comment]
No, I'm just selecting the required schema from the dropdown.

**Comment by Destrolaric** [comment]
@r1evan As I see, you have projects which are not added as additional projects and are still shown. I will look into it.

**Comment by Destrolaric** [comment]
@r1evan I think if you pass needed projects as additional projects you will be able to query them.

**Comment by r1evan** [comment]
I did it that way as well, but it's not working. Can you check and send me of how to add multiple projects??

**Comment by Destrolaric** [comment]
@r1evan Sorry for waiting. Can you send your connection settings and driver properties?

**Comment by r1evan** [comment]
Any location from where I can send you these?

**Comment by LonwoLonwo** [comment]
Hello @r1evan 

>  Can you check and send me of how to add multiple projects??

Additional projects can be added as a "Coma-separated list" to the Connection Settings.

Could you tell us more about your issue? You are trying to make requests to objects from a project that does not default, but they do not work? 
And if you specify in a separate connection with the desired project as default - then requests to the project from another SQL Editor will work?

Also, have you tried to change the default project in the Database Navigator tree?
![2022-01-24 19_10_50-](https://user-images.githubusercontent.com/45152336/150820336-4c32a9fb-b6c7-4a28-85e8-89f7bba1913c.png)

**Comment by LonwoLonwo** [comment]
And one more question. Have you tried to use the full table name in the SELECT statement? With project name + schema name + table name?
```sql
SELECT * FROM `bigquery-public-data`.austin_311.`311_service_requests`
```

 works in my case.

**Comment by r1evan** [comment]
It does work in that case. But it's quite tedious to give fully qualified name for each table every time rite?

**Comment by r1evan** [comment]
Not sure if there is any way we can connect over a call and I can show you the exact issue / requirement which I'm looking for.

**Comment by Destrolaric** [comment]
@r1evan Sorry, you need to write full path to schema, here is information from driver documentation

> For queries, tables in the projection list must be fully qualified, in the format of
catalog.schema.table. If the catalog is not specified, the driver will assume the
project specified by the projectId connection option

**Comment by r1evan** [comment]
Great thanks!

**Comment by r1evan** [comment]
But, when it provided the list of schemas available, there should be a way to run the queries by just selecting the schema from the dropdown. Should be taken as an enhancement. It really tough to give the fully qualified name for table every time.

**Comment by Destrolaric** [comment]
@r1evan The only way to do this is by modifying the user query. This is bad practice due to the possibility of incorrect queries being formed.

**Comment by uslss** [comment]
verified
