### ISSUE TITLE
Boolean value in entity editor dissapears when inline editor is closed via ESC button

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#13910]
#### System information: 
- DBeaver version 21.2 UE

Originally reported [here](https://github.com/dbeaver/dbeaver/issues/12473). See https://github.com/dbeaver/dbeaver/issues/12473#issuecomment-918161913

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
