### ISSUE TITLE
Filter result set on aliased column

### ISSUE THREAD

**Issue by igorzhilin** [dbeaver/dbeaver#13924]
When filtering the result set on a calculated column (with alias), I receive an error: 
`Column "calculated_column_name" does not exist. Hint: Perhaps you meant to reference the column "source_column_name".`

I would like to be able to filter on calculated column without referencing the source column.

To be able to filter on a calculated column, I have to provide the source column name in the filter. Then it works.

Example:
Query with calculated columns in PostgreSQL
```
select
	datname				as db_name,
	pg_database_size(datname)	as db_size_bytes
from
	pg_catalog.pg_database
```
![image](https://user-images.githubusercontent.com/9438635/133609815-1a10eba1-9ed1-4e84-9dfb-215139a0edba.png)

Filter
![image](https://user-images.githubusercontent.com/9438635/133609869-904d6934-dd0f-4c52-8913-438aae76e598.png)

Error
![image](https://user-images.githubusercontent.com/9438635/133609887-8e3e4d2b-18a0-4d33-842f-3556db6230af.png)

**Comment by tati-kru** [comment]
This is a bug, thank you for the report.

**Comment by Skydiveroid** [comment]
This can be fixed by using nested selects for query filtering

**Comment by Matvey16** [comment]
Doesn't work for some columns

![j3kzu3pfyX](https://user-images.githubusercontent.com/82543000/146885089-4c6ff703-b97b-42f4-b1c1-8f31ab96a065.gif)

**Comment by Matvey16** [comment]
Doesn't work if aliased column is array type

![lOsrj8iJzH](https://user-images.githubusercontent.com/82543000/147132445-b8384126-9222-46ad-9da9-5537be9c62a9.gif)

**Comment by Matvey16** [comment]
New ticket #15011 created for array columns. Verified for other types
