### ISSUE TITLE
Unicode symbol for false value shifted up in data editor

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13927]
#### System information: 
- Operating system: Linux
- DBeaver 21.2.1

#### Describe the problem you're observing:
![Screenshot 2021-09-16 at 16 35 23](https://user-images.githubusercontent.com/43252954/133621898-02c42f3d-00b3-416a-a7ef-49dc6a014cf8.png)

**Comment by tati-kru** [comment]
Not a bug. Thius is how this symbol looks in this font.
