### ISSUE TITLE
Boolean text representation: Bold font option

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#13923]
Continuation of #11345:
> Bold text would be more contrast for the eye

Need to add an option for enabling bold font for boolean values.

**Comment by ShadelessFox** [comment]
Now it's possible to choose style for each boolean variant:

![image](https://user-images.githubusercontent.com/35821147/135875960-e49c9a61-7739-46ea-b8a2-66a707ec03af.png)

**Comment by uslss** [comment]
verified

**Comment by ghYura** [comment]
FYI:
Unfortunately "whitespaces", made by use input, before and after any most margin to the left or right character(s) are eaten and no custom(!) indentation, despite general align-option (I know, this is working, but not whitespaces before-after).

**Comment by ghYura** [comment]
Still think that would be nice to have extended **each individual** boolean column has **its own** display-mode sub-adjustments
Details: originated issue https://github.com/dbeaver/dbeaver/issues/11345

**Comment by ShadelessFox** [comment]
@ghYura please create a separate issue containing all required information about your feature request.

This ticket is closed, so it's hard to track.
