### ISSUE TITLE
Boolean text representation: Wiki page about its features

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#13926]
For more information see #11345

**Comment by ShadelessFox** [comment]
https://github.com/dbeaver/dbeaver/wiki/Data-View-and-Format#configuring-boolean-presentation

**Comment by ghYura** [comment]
FYI:
Switches example - everyone, feel free to copy-use it for this mode:
[ ✔ ]██
██[ ✘ ]
![boolSwithesText](https://user-images.githubusercontent.com/42974628/136099633-44a29b41-60d0-48bf-96fe-dd21b80bd0ab.jpg)
