### ISSUE TITLE
Boolean alignment changes during new row creation 

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13935]
#### Describe the problem you're observing:
If boolean values alignment is set differently the value will jump in the field every time it is changed. This happens only for new rows.

#### Steps to reproduce, if exist:
1. Set different alignment for different boolean values
2. Create a table with a boolean column
3. Create a new row, but don't persist the changes
4. Try to change the value in a boolean column

**Expected:** Value can be changed many times with only mouse clicks and without moving a cursor
**Actual:** The value jumps to different sides of the field. 

![RadxSWo2od](https://user-images.githubusercontent.com/82543000/133777267-b092f57c-6778-4fe9-8270-3d367ea6ec71.gif)

**Comment by ShadelessFox** [comment]
Alignment can be either fixed to the center or according to nullable flag / default value of the column.

**Comment by uslss** [comment]
verified
