### ISSUE TITLE
New object/folder can't be created in root folder in project explorer

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13932]
- DBeaver version 21.2.1

#### Describe the problem you're observing:
Focus in project explorer can't be changed to root folder so context menu is always opened for one of the folders.

#### Steps to reproduce, if exist:
1. Right-click on blank space in project explorer
2. Select create new folder
3. Observe the path for folder that is being created

**Expected:** Folder is created in root folder of the project
**Actual:** Folder is created in the folder that is currently focused

![rtqmUQyV88](https://user-images.githubusercontent.com/82543000/133744728-69e02b75-2d0c-420e-9375-97e72a5f2998.gif)

**Comment by uslss** [comment]
duplicates #6818
