### ISSUE TITLE
[HANA] wrong alter table add column syntax

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13948]
#### System information: 
- DBeaver 21.2.1 CE
- Sap Hana

#### Describe the problem you're observing:
If you perform import/export into table and it require column creation you'll catch SQL error.
Correct syntax: ALTER TABLE SCHEMA.TABLE ADD **(COLUMNNAME INTEGER)** 
Actual query: 
![image](https://user-images.githubusercontent.com/43252954/133956889-0546f044-c967-4c99-afbe-244a5fbf36f3.png)

#### Include any warning/errors/backtraces from the logs
```
Error occurred during Create target metadata
Reason:
SQL Error [257] [HY000]: SAP DBTech JDBC: [257] (at 37): sql syntax error: incorrect syntax near "COLUMN5": line 1 col 37 (at pos 37)
```

**Comment by uslss** [comment]
verified
