### ISSUE TITLE
If a table has two or more references, they are doubled

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13940]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.2.1 EA

#### Connection specification:
- Database name and version Redshift

#### Steps to reproduce, if exist:
1. Create a source table with a primary key
2. Create 2 tables with foreign keys to the source table
3. Reconnect to the database and open References tab of the source table

**Expected**: 2 references are displayed
**Actual result**: 4 references are displayed (references are doubled)
**Note**: test tables are created in dev.public: `pk`, f`k` and `fk2`

![Screenshot 2021-09-17 at 17 01 59](https://user-images.githubusercontent.com/51405061/133795840-f63aba6c-e6a7-4d78-a08d-c5318e701044.png)

**Comment by ShadelessFox** [comment]
I can't reproduce the issue. It seems like it already was fixed.

![image](https://user-images.githubusercontent.com/35821147/153410966-8d1e0180-d9f2-4e92-be5a-2b29cb226d1b.png)
