### ISSUE TITLE
[HANA] hyperlink in sql console for table doesn't work without specifying the scheme

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13949]
#### System information: 
- Win 10
- DBeaver CE 21.2.1

#### Connection specification:
- SAP HANA

#### Describe the problem you're observing:
1. Open SQL editor for HANA connection. 
2. Select active scheme
3. write a simple script (like this : SELECT * FROM NEWTABLE;) with the name of the table, but without specifying the schema.
Expected: you can navigate to the table with ctrl pressed and mouse click
Actual: you can't do this without using fully qualified name

**Comment by LonwoLonwo** [comment]
Fixed ![OaxMpHUahM](https://user-images.githubusercontent.com/45152336/147537715-0dca8050-eaf3-4039-af4e-fa73fa7c51f2.gif)

**Comment by uslss** [comment]
verified
