### ISSUE TITLE
SQL Editor tear off and tear off add to previous tearoff

### ISSUE THREAD

**Issue by higgsja** [dbeaver/dbeaver#13946]
#### System information: 
- Operating system (distribution) and version Linux Mint 12
- DBeaver version 20
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When you tear off an SQL editor from the main window, the cursor becomes the circle with slash, indicating the operation cannot happen. But it does.

After having one editor torn off, tearing off another and adding to the previous (put 2 tabs in that window), same cursor behavior.

**Comment by uslss** [comment]
@higgsja could you provide a video with the issue?

**Comment by uslss** [comment]
there is no update on issue for a long time. If it is still actual for you - feel free to reopen it with additional info
