### ISSUE TITLE
Geometry values cannot be edited via UI

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#13947]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver	21.2.1.202109181243
#### Connection specification:
- Database name and version Redshift

#### Steps to reproduce, if exist:
Try to add a geometry value via UI

**Expected**: the value is inserted and displayed correctly
**Actual result**: the value cannot be saved and the error appears:

![dbeaver_velSQVNAAI](https://user-images.githubusercontent.com/51405061/133889982-71c60ca9-efe3-4390-bde8-f8be607eca18.png)
[geom_insert.log](https://github.com/dbeaver/dbeaver/files/7189932/geom_insert.log)

**Comment by Matvey16** [comment]
Verified
