### ISSUE TITLE
Search in data editor by Ctrl+F starts by formatted numbers and therefore can't find anything

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13950]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Describe the problem you're observing:
1. Set data formatting for integer that contains any formatting symbols
2. Find  or create a value where you will see the formatting in action
3. Select this cell and press Ctrl+F
Actual: You can see that search window contains formatted integer. Because of that it can't find your integer value
Expected: Search should be performed by value without any formatting symbols (dots, spaces, commas etc.) 
![image](https://user-images.githubusercontent.com/43252954/133958919-35f37bd4-0eb2-4591-b23a-08819dbc5c37.png)

**Comment by Matvey16** [comment]
Verified
