### ISSUE TITLE
Add a shortcut for `Set to NULL` action

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#13955]
#### System information: 
- Operating system (distribution) and version: **Windows 10**
- DBeaver version: DBeaver 21.2.2
- Additional extensions

#### Describe the problem you're observing:
There's undocumented behavior of cutting-out cell's value using <kbd>Shift+Delete</kbd>. It would be more convenient to assign this shortcut to <kbd>Edit</kbd> &rArr; <kbd>Set to NULL</kbd> action instead because <kbd>Ctrl+X</kbd> can be used to cut value from cell.

**Comment by tati-kru** [comment]
It is possible to set this shortcut from the Preferences.
