### ISSUE TITLE
 Oracle: show error position in SQL query

### ISSUE THREAD

**Issue by ppruchnicki** [dbeaver/dbeaver#13964]
Unfortunately error persist in the 18.3.0.0 driver version, I'm unable to use 12.2.0.1 due to wallet configuration. Using @kiravi example the obtainable error is still displaying cursor position not the error line like it's done in SQL Developer:
`SQL Error [904] [42000]: ORA-00904: "T": invalid identifier`

_Originally posted by @ppruchnicki in https://github.com/dbeaver/dbeaver/issues/915#issuecomment-923737870_

**Comment by tati-kru** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
Can't reproduce against in the latest DBeaver version with the Oracle 18.3.0.0 driver version

![a6qN6Fppv4](https://user-images.githubusercontent.com/45152336/160417065-5b9ff710-b657-4ea7-86d0-0eb21eabd246.gif)

![2022-03-28 17_10_14-Connection _orcl_ configuration](https://user-images.githubusercontent.com/45152336/160417126-c23af487-1d24-4267-957d-1e7f644922fc.png)

**Comment by ppruchnicki** [comment]
I think you are missing the point of this feature request :) in SQL Developer error message points to a specific line where the error occurs, and this is the stuff that is missing. Try to run the same code in SQL Developer and see how the output differs.

**Comment by LonwoLonwo** [comment]
Please tell me more about the "specific line where the error occurs"

In my gif file above, you can see that the error line is highlighted after query execution.

![2022-03-28 18_28_48-Oracle_ show error position in SQL query · Issue #13964 · dbeaver_dbeaver — Mozi](https://user-images.githubusercontent.com/45152336/160433430-cf2b2612-5246-4896-8196-72902b513c27.png)

Also, from DBeaver 22.0.1 query will be selected from the error part to the end of the query.

![2022-03-28 18_28_14-Preferences](https://user-images.githubusercontent.com/45152336/160434219-68227f93-d060-4531-bb93-ae64284aa8fd.png)

**Comment by ppruchnicki** [comment]
I get it, but still I'm talking about the error message it's good that dbeaver will be able to better point to the error but still error message is not as accurate as it can be:
![image](https://user-images.githubusercontent.com/54060486/160435153-cd1b6d7b-6c18-4bc9-8334-d6fcfffd5ddc.png)
this is how it's displayed in SQL Developer.

**Comment by LonwoLonwo** [comment]
Ok. You can open the "Details" section to see more info about the error. Position can be in this message - depending on the error. 

![2022-03-29 10_01_36-DBeaver 22 0 2 - _orcl_ Script-9](https://user-images.githubusercontent.com/45152336/160553180-71186ff9-0337-4575-a4a3-d609d841686e.png)

**Comment by ppruchnicki** [comment]
Great! This is exactly what I was looking for, amazing job :) is there a way to change this position to Line and Column as it is in SQL Developer?

**Comment by LonwoLonwo** [comment]
Implemented.

![2022-04-11 10_54_48-DBeaver Ultimate 22 0 2 - _orcl_Script-140](https://user-images.githubusercontent.com/45152336/162691491-5e440575-7754-4215-a2c6-f822a87b121d.png)

Also, "Go to Error" button added for error presentation.

**Comment by Matvey16** [comment]
Verified
