### ISSUE TITLE
UI on MacOS not displaying correctly on system dark theme

### ISSUE THREAD

**Issue by cxgillis** [dbeaver/dbeaver#13968]
When upgrading from 21.2.0 to 21.2.1 on MacOS Big Sur (11.5.2) the UI display is non-longer usable e.g. fonts are incorrect, text does not appear, menus are invisible, etc. This appears to be the same issue as [13962](https://github.com/dbeaver/dbeaver/issues/13962) ; which was marked as closed as a work-around is to disable theming (which also worked for me) but it seems like that is not actually addressing the underlying defect. Removing the current version by moving from the Applications folder to the trash and then re-installing 21.2.0 appears to resolve the issue, so it would seem the issue is some change in 21.2.1 that has broken the previous theming support.

Let me know if there is any additional information I can provide.

**Comment by priyesh86** [comment]
I am having the same issue on MacOS Mojave (10.14.6).

**Comment by flambchap** [comment]
Hi @cxgillis. That's not good at all. We will investigate this issue. Thank you for the report.

**Comment by Matvey16** [comment]
Steps to reproduce:
1. Set OS theme to Dark
2. Set DBeaver theme to Ligh

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
The issue still persists, unfortunately.

**Comment by A-CiKe** [comment]
修改主题为Dark可以正常使用

**Comment by A-CiKe** [comment]
Modifying the theme to Dark can be used normally.

**Comment by PowerToThePeople111** [comment]
A-CiKe's recommendation worked for me. 
Thanks a lot!

**Comment by axialistatfore2** [comment]
I'm having this same issue on macOS Catalina 10.15.7.

I'm expecting to have to scrape and re-install (22.2.0 this time).
I had lots of connections defined and would like to preserve those if possible.

@serge-rider ,
After the total re-install, would restoring these files recover my connection definitions?
~/Library/DBeaverData/workspace6/General/.dbeaver/data-sources.json
~/Library/DBeaverData/workspace6/General/.dbeaver-data-sources.xml

Pesky side question:
In this ordeal, I also found a lot of apparent debris from long, long, ago in 
~/.dbeaver4/        and
~/.eclipse/org.jkiss.dbeaver.product_4.0.5_291865505_macosx_cocoa_x86_64/ .
Can I safely delete those directory trees?

**Comment by piero** [comment]
Same issue on MacOS BigSur 11.5.2.
Either setting theme to Light or disabling themes leave the editor with a dark (almost illegible) background.
Also, disabling themes sets DBeaver to have a Dark UI but with data displayed within Light tables.
Thanks.

**Comment by JesperWe** [comment]
Best part is you have to navigate in the dark (although in this case the dark is white ;-) ) to set the theme to dark...

<img width="659" alt="image" src="https://user-images.githubusercontent.com/1643015/140615438-e2677924-1822-40d8-b287-e096f56cf264.png">

**Comment by agails** [comment]
I still have this problem today, we can really change the theme but as all applications follow the system theme, I would like to leave DBeaver with this feature as well. There is no workaround to fix this without patch? Macbook Pro 2020 M1 MacOS Monterey

**Comment by Matvey16** [comment]
@agails Unfortunately without a patch the only workaround is to change the properties manually

**Comment by Matvey16** [comment]
Verified. Will be fixed in 21.3.0

**Comment by RamonGiovane** [comment]
Still having this on version 22 :confused: (Linux Mint 20)
![image](https://user-images.githubusercontent.com/40267373/177868617-0da00e6a-679b-4bf6-8be6-bf8337bf3e0b.png)

**Comment by ShadelessFox** [comment]
Hello @RamonGiovane,

This issue is about macOS, and it has been resolved. Please find an existing issue or create a new one.
