### ISSUE TITLE
IBM DB2 AS 400 Database table description not show after version 12.0.1

### ISSUE THREAD

**Issue by beckrion** [dbeaver/dbeaver#13965]
Hello,

The new version of DBeaver will show Table Description empty at IBM DB2 As 400

It happens at the version after 12.0.1

**Comment by Matvey16** [comment]
Hello @beckrion . Somwhere between 21.0.1 and current version we changed the default property of AS 400 driver. As I mentioned [here](https://github.com/dbeaver/dbeaver/issues/13322#issuecomment-887416794), those settings can serriously affect different databases in different ways. I recommend you to look closely at driver properties, especially `metadata source` (because it was changed from 0 to a default 1) and see if changing it will help you.

**Comment by beckrion** [comment]
Thanks @Matvey16 I tried the setting seems does not work, I update some screens shot for you, hopefully it will help you to solve this issue

This is version 7.3.5, which works fine with the table description


![WechatIMG14359](https://user-images.githubusercontent.com/16887531/134567801-66e29be7-c63b-4be9-92d2-b383589b7466.jpeg)

after I upgrade to 21.0
![WechatIMG14356](https://user-images.githubusercontent.com/16887531/134571235-7a838f12-b66a-4b58-b237-192650f4c908.jpeg)

Also table's Description disappeared  

![WechatIMG14355](https://user-images.githubusercontent.com/16887531/134571264-79808409-5104-4d40-88df-22c17cf541e7.jpeg)

**Comment by Matvey16** [comment]
@beckrion Can you try changing "remarks" property to see if it will help 
Also other property that can cause this is "extended metadata"

**Comment by beckrion** [comment]
@Matvey16 
![image](https://user-images.githubusercontent.com/16887531/134691120-d382ecf0-fd20-46f5-91be-227f34707741.png)

it is seems stuck at load table cache

**Comment by beckrion** [comment]
@Matvey16 Maybe beacuse I have too many table, finally it is finished, but still not work

**Comment by Matvey16** [comment]
#10302 Can be related

@beckrion AS400 driver is very tricky, so it will be great if you can add screenshot of driver properties in different version (where description works and where it is not)
Are you sure you changed the `metadata source` property to 0? In this ticket #4568 the user was having the same issue and changing it worked. Also it is exactly the thing that was changed for AS400 driver between 7.3 and 21+ versions.

**Comment by beckrion** [comment]
@Matvey16 Sorry for the late response, I will add more screenshots when I back to my office!

Thanks

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info

**Comment by olivernight** [comment]
Hi,
Did you try to set the "Describe Option" with the value "labels" in your Driver properties ?
