### ISSUE TITLE
Queries against Redshift very slow

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [dbeaver/dbeaver#13963]
#### System information: 
- macOSX 11.6 (Big Sur)
- DBeaver 21.2.1

#### Connection specification:
- Connecting to a Redshift cluster

#### Describe the problem you're observing:

I'm querying an external schema with a simple select; it seems like the rows are fetched quite quickly but then the client sites there for several minutes doing _something_. For example, in the results shown below, I don't see the results materialized for several minutes (~2 min) although it tells me it fetched rows very quickly
![image](https://user-images.githubusercontent.com/8518288/134059756-7d83cf1f-be3c-4ab0-a58d-455800f8ee4e.png)

Running a similar query in table plus, against the same table, almost instantly returns results.

I'm noticing the same thing for "standard" Redshift table as well (i.e. they are not Glue tables mounted as an external schema).

**Comment by Matvey16** [comment]
@ConstantinoSchillebeeckx Hello, can you look what background process is happening until the table is displayed? You can enable background tasks window with `Window > Show view > Other > Background tasks`
Also queries from the query manager can be useful too

**Comment by ConstantinoSchillebeeckx** [comment]
[Here's a gif](https://drive.google.com/file/d/1jBxrmcomojwMEU0eterVu4WuOcKAKWRZ/view?usp=sharing) of the behavior showing both `Background tasks` and the `Query manage`

**Comment by Matvey16** [comment]
@ConstantinoSchillebeeckx Do you see the same behavior when opening tables from Database Navigator?

**Comment by ConstantinoSchillebeeckx** [comment]
that's how I'm opening them in the GIF (e.g. "Read data in SQL editor")

**Comment by Matvey16** [comment]
@ConstantinoSchillebeeckx Sorry, I meant does it take that long to open in data editor too (double-click on the table or selecting a table and pressing F4)

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info.
