### ISSUE TITLE
Something went wrong on latest update 21.2.1

### ISSUE THREAD

**Issue by mauro-palumbo** [dbeaver/dbeaver#13962]
After latest update on my MacOS 11.6 I'm unable to see any description (connections, tables, scripts....)
![Snip20210920_1](https://user-images.githubusercontent.com/8257804/134048858-17ee0497-9d68-4364-a75e-43e56283b4f6.png)

**Comment by clavarreda** [comment]
Try disabling themes in `Preferences > User Interface > Appearance > Enable theming`

**Comment by mauro-palumbo** [comment]
Thank you. This works for me. Now it seems DBeaver matches the OS appearance (light, dark).

**Comment by clavarreda** [comment]
In my case theme support is broken. SQL Editor colors didn't match the selected theme and I had to make some adjustments in order to use DBeaver. There should be an option to return to the exact pre-update behavior until theme support could be fixed

**Comment by Matvey16** [comment]
Steps to reproduce:
1. Set OS theme to Dark
2. Set DBeaver theme to Light

**Comment by piero** [comment]
I second this issue.
Either setting theme to Light or disabling themes leave the editor with a dark (almost illegible) background.
Also, disabling themes sets DBeaver to have a Dark UI but with data displayed within Light tables.
