### ISSUE TITLE
chose the timezone in dbeaver option

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#13960]
Dbeaver 21.2.0

For all version DBeaver, i put timezone parameter to dbeaver ini file
I aded string
-Duser.timezone=Europe/Moscow

But it is very uncomfortable because this operation needs to be performed every DBeaver upgrade.

**Comment by ShadelessFox** [comment]
Hello @detkliff,

Timezone can be configured in time/timestamp formatters:

![image](https://user-images.githubusercontent.com/35821147/134031330-6b2b109d-c30f-4a3b-899b-72eaddfd1f62.png)

**Comment by detkliff** [comment]
this parameter pointed in global settings but no effect

![image](https://user-images.githubusercontent.com/61137576/134034447-d25f5b14-bbaa-401f-a352-9e9de700183b.png)

**Comment by ShadelessFox** [comment]
Looks like your column has type of `timestamp with timezone`.

Currently, the only way to set local timezone is to use your hack described earlier.

Probably we should allow to define a timezone offset for zoned time types.

**Comment by detkliff** [comment]
very good! This option very relevant for many developers, this query for DBeaver i sow in github meny years ago.
We are waiting this option. Thank you.

**Comment by bandikota** [comment]
21.3.4 wooow (

**Comment by alex88** [comment]
This would be awesome, there's no way to just set the user.timezone and setting it manually is lost on every update and it's even harder on flatpak

**Comment by detkliff** [comment]
22.0.5 =((  bad, looking forward to it

**Comment by Destrolaric** [comment]
Now timezone can be selected in the Timezone field in the User interface tab. The selected timezone will be applied to JVM and will affect the whole app. Every timezone supported by JVM can be selected. Autocompletion is also supported.
![image](https://user-images.githubusercontent.com/20579256/170230052-a534d61c-b502-4318-aca6-f18d9384e8f2.png)

**Comment by detkliff** [comment]
> Now timezone can be selected in the Timezone field in the User interface tab. The selected timezone will be applied to JVM and will affect the whole app. Every timezone supported by JVM can be selected. Autocompletion is also supported. ![image](https://user-images.githubusercontent.com/20579256/170230052-a534d61c-b502-4318-aca6-f18d9384e8f2.png)

what version is this?

**Comment by Destrolaric** [comment]
@detkliff It will be available on 22.1.0 version of DBeaver
