### ISSUE TITLE
Exports from Trino to MSSQL fail on timestamp columns with dates

### ISSUE THREAD

**Issue by luisds95** [dbeaver/dbeaver#13961]
#### System information: 
- OS: Windows 10 Pro 64-bit
- DBeaver version: 21.2.1.202109181446
- Additional extensions: None

#### Connection specification:
- Database name and version: Trino 359
- Driver name: Trino JDBC Driver 359
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH Tunnel

#### Describe the problem you're observing:
When exporting data, reading from Trino 359 to Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64), timestamp columns casted to date and that contain nulls are filled with the next column's information.

For example, given the table A:
name: foo, bar
insert_date: 2021-09-20 15:50:00.000, NULL

This query fails to be exported to MSSQL:
`SELECT DATE(insert_date) AS insert_date, name FROM A`

And this query produces an unexpected result
`SELECT CAST(DATE(insert_date) AS VARCHAR) AS insert_date, name FROM A`
Instead of inserting NULL in insert_date when name is "bar", it also inserts "bar" in insert_date

#### Steps to reproduce, if exist:
* Install MSSQL and Trino
* Create a table in Trino as above
* Export the table to MSSQL as above

#### Include any warning/errors/backtraces from the logs

The query that fails produces:
![image](https://user-images.githubusercontent.com/40841942/134025223-f874b08f-1d3e-4d96-8189-2c4f88afed16.png)

**Comment by Matvey16** [comment]
@luisds95 Can you specify what actuall database you are using behind Trino and add DDLs for tables that are used in this export?

**Comment by luisds95** [comment]
Hi @Matvey16 This is coming from Delta Lake saved in S3. 

DDL for example table A:
```
CREATE TABLE delta."dev-emis-web".appointment_slothistory (
   insert_date timestamp(3) with time zone,
   name varchar
)
WITH (
   location = 's3://YOUR-BUCKET/A/'
)
```

**Comment by luisds95** [comment]
Hi @Matvey16 This is coming from Delta Lake saved in S3.

DDL for example table A:
```
CREATE TABLE A (
   insert_date timestamp(3) with time zone,
   name varchar
)
WITH (
   location = 's3://YOUR-BUCKET/A/'
)
```

Also, it's worth mentioning that the bug only happens when exporting to MSSQL. CSV, TXT and Inserts work fine

**Comment by Matvey16** [comment]
@luisds95 Are you using export from query or first executing the select statement and then exporting from resultset?

**Comment by luisds95** [comment]
@Matvey16 both approaches generated the same issue

**Comment by Matvey16** [comment]
@luisds95 Can you give me a DDL for a table in MSSQL into which you are exporting the data?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info
