### ISSUE TITLE
Generated SQL Preview Window Not Showing First Two Lines

### ISSUE THREAD

**Issue by Xylandor** [dbeaver/dbeaver#13970]
#### System information: 
- Operating system (distribution) and version: MacOS Big Sur 11.4
- DBeaver version: Community 21.2.1.202109181446
- Additional extensions: None

#### Connection specification:
- Database name and version: MySQL 5.7
- Driver name: MySQL 5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When generating SQL (insert/Update/etc), the preview window only shows lines three and beyond and there's no way to scroll up, neither by scroll bar, trackpad nor mouse wheel. If you only have two or less lines generated, they do not show. However, you can still copy them just fine. 
![Screen Shot 2021-09-21 at 11 24 44 AM](https://user-images.githubusercontent.com/24617679/134212593-1ddc1306-9b73-49e6-abfa-a499518f9a94.png)

#### Steps to reproduce, if exist:
1. Query a table with data.
2. Select all results, right-click and select Generate SQL > INSERT (or any other option)
3. The preview window displays and you can see that the first two lines are hidden. If enough entries exist to display the vertical scroll bar, you can see that the top portion of the scroll bar is behind the "SQL Preview" header object.

**Comment by flambchap** [comment]
Hi. This is [a known issue](https://github.com/dbeaver/dbeaver/issues/13882), we're going to fix it in one of our future updates. Thank you for the report.

As a workaround, you can resize the window, and the script will appear just fine.
