### ISSUE TITLE
Space character lost when importing text[] array from CSV to Postgres

### ISSUE THREAD

**Issue by jonabend-uptake** [dbeaver/dbeaver#13972]
#### System information: 
- OS: MacOS 11.6
- DBeaver version: 21.2.0.202108291732
- Additional extensions: None

#### Connection specification:
- Postges 13.4
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No...local DB

#### Describe the problem you're observing:
When importing CSV with a text array, any spaces in array values are lost during import.

To fully test that the issue was with importing, and not the formatting of the CSV, I manually created array entries in DBeaver and then exported them to a CSV file using DBeaver.

Upon importing the CSV, spaces in array elements that contain spaces between words are lost.

Example:
`New York` is imported as `NewYork`.

The loss of spaces can be seen when previewing the data in the DBeaver Import toolset.

sample.csv
```
"text_array","varchar_array"
"{Eastern,New York}","{Eastern,New York}"
```
produced by exporting this table data to CSV:
![image](https://user-images.githubusercontent.com/85365266/134264870-8ade5ef0-ba4b-422a-b971-42e1c70f9a65.png)

When then when previewing the data to import:

![image](https://user-images.githubusercontent.com/85365266/134264560-a3ad5e98-55d4-48cb-9da8-f27074b55a28.png)

The space character is lost in the Array Value for "New York"

Table DDL
```
CREATE TABLE public.newtable (
	text_array _text NULL,
	varchar_array _varchar NULL
);
```

#### Steps to reproduce, if exist:

1) Create table using DDL above
2) Create sample.svc file using data above
3) Import data -> CSV into table, observe the data in "Preview data"

**Comment by tati-kru** [comment]
Thank you for the report.

**Comment by uslss** [comment]
verified
