### ISSUE TITLE
Mark occurrences in column of selected result cell value

### ISSUE THREAD

**Issue by nikiromagnoli** [dbeaver/dbeaver#13976]
**Is your feature request related to a problem? Please describe.**
Not a real problem, almost the same could be accomplished by entering a filter, but it's more for a quick-sight user-experience.
I didn't spot a previous issue about this.

**Describe the solution you'd like**
Sort of #222 but in results:
- when you select a cell in result grid
- highlight cells in same column that match selected cell's value.

**Describe alternatives you've considered**
None. I don't know if it's anyway possible either.

**Additional context**
It's a feature that I spotted on a "competitor" client yesterday, I thought could be useful actually.
Look at this mock:
![immagine](https://user-images.githubusercontent.com/5136855/134324292-8476d557-9afb-4815-a293-258fbaa4c23b.png)
Selected cell has 18, all 18s on the same column get highlighted.

**Comment by tati-kru** [comment]
Thank you for the idea.

**Comment by ShadelessFox** [comment]
Implemented:

![java_dUcLmUjylk](https://user-images.githubusercontent.com/35821147/150242476-6bb1e2c4-0336-4a15-b075-67b4a9c160b8.gif)

It can be enabled in the preferences:

![java_aNfuTnW7OX](https://user-images.githubusercontent.com/35821147/150518374-0b617854-1687-467c-8dab-98cdff368530.png)

**Comment by nikiromagnoli** [comment]
That's great news! Thank you.

**Comment by uslss** [comment]
verified

**Comment by nikiromagnoli** [comment]
**Hint for users**: customize highlight color in usual color's settings, as "Matched (find/replace) row background" 
![immagine](https://user-images.githubusercontent.com/5136855/156355808-0d6d5617-5493-46d8-9ea2-23f841bdb965.png)

Color code of request mock picture: **#FFFF00** (transparency feature seems not accepted)
My favorite color tone: **#F8F99F**

**Comment by nikiromagnoli** [comment]
Also, this will not cross-check datatypes, so for example numeric "1" won't highlight string "1" and viceversa.
![immagine](https://user-images.githubusercontent.com/5136855/158618698-5c47cd28-56ef-4dda-b770-a8e3e20a1a06.png)

**Comment by ShadelessFox** [comment]
Yes, it is type-aware. An enhancement can be created to highlight any occurrences of the value.

**Comment by nikiromagnoli** [comment]
Maybe as a sub-option?

Also, I noticed that color alpha is ignored. Don't know if expected or not, just a side note.

**Comment by ShadelessFox** [comment]
Yes, exactly.

Color transparency is not supported, unfortunately, so it is expected.
