### ISSUE TITLE
Loading Proposals Takes Very Long - mac mysql

### ISSUE THREAD

**Issue by noorsyamiera92** [dbeaver/dbeaver#13974]
#### System information: 
- macOS 11.6
- DBeaver 21.2.1
- Additional extensions

#### Connection specification:
- MySQL 5.7
- MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes

#### Describe the problem you're observing:
Before update to new version , the proposal does look ok , and load fast. After update to 21.2.1 , it loads very slow.
Its like a minute , then only come out the proposal

![Screenshot 2021-09-22 at 11 44 29 AM](https://user-images.githubusercontent.com/40814112/134280570-51d6161d-dd19-4b85-81fe-eaa76784f1f1.png)

**Comment by ems2811** [comment]
The same problem on PostgreSQL:

PG SQL 11.11 via SSH DBeaver 21.2.1 "Search proposals...." 3 min. 20 sec.
PG SQL 11.11 via SSH DBeaver 21.2.0 "Search proposals...." 3 sec. (same searching, same DB load)

PG SQL 9.5 DBeaver 21.2.1 "Search proposals...." 22 sec.
PG SQL 9.5 DBeaver 21.2.0 "Search proposals...." 2 sec. (same searching, same DB load)

Search query in statistic executes fast, but "Search proposals...." is too long

**Comment by noorsyamiera92** [comment]
Yea. Im downgrading to lower version coz i dont wanna waste my working time to wait for it to load.

**Comment by wsjlamoureaux** [comment]
Same problem on MacOS Catalina (10.15.7) after upgrading to 21.2.1

**Comment by Matvey16** [comment]
@noorsyamiera92 Can you show what queries are run in query manager?

**Comment by mrgtt** [comment]
Same problem here (PostgreSQL 11/Windows).

I think this could be related to the new feature in 21.1.2 "Metadata search now supports search in procedures/views definition": searching through tables is fast but if you have many functions definitions in your database and a not so fast connection, the search can take several minutes.

It would be nice if the search proposal could be customized (i.e. disable search in procedures). I'm disabling entirely the search proposal for the time being.

**Comment by matneves** [comment]
Same problem here with Mac OS (Apple M1) and DBeaver 21.2.1, using mysql 5.6 or 5.7.

**Comment by Matvey16** [comment]
This was probably fixed in recent version. You can test it on EA version https://dbeaver.io/files/ea/ or wait for a release on Monday

**Comment by noorsyamiera92** [comment]
I just installed the latest version.
Its working fine now.
Thanks for your help.
