### ISSUE TITLE
Start button not automatically enabled in PostgreSQL backup when using "All" button for selecting schemas

### ISSUE THREAD

**Issue by Lewiszz** [dbeaver/dbeaver#13977]
#### System information: 
- Windows 10 Pro
- DBeaver 21.2.1

#### Connection specification:
- PostgreSQL 10.16
- PostgreSQL

#### Describe the problem you're observing:
In the pop-up window that opens when creating a backup, the "Next" and "Start" buttons remain disabled even when all objects are selected for export using the "All" button.

![afbeelding](https://user-images.githubusercontent.com/38034937/134336869-6017817c-b4c5-424c-bfe8-ad0caa4663ce.png)

#### Workaround: 
Clicking on one of the schemas does enable the buttons. Once you know this it's not a big issue anymore :)

#### Steps to reproduce, if exist:
1. Upgrade to DBeaver v21.2.1
2. Right-click a database and select "Tools" and then "Backup"
3. Select "All" schemas to export

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @Lewiszz !

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.2.3

**Comment by LonwoLonwo** [comment]
Will be available [here](https://dbeaver.io/) on 2021-10-18

**Comment by Matvey16** [comment]
Verified
