### ISSUE TITLE
Incorrect fractional second handling in DBeaver

### ISSUE THREAD

**Issue by mihalyr** [dbeaver/dbeaver#13987]
#### System information: 
- Operating system (distribution) and version: Fedora 34, 5.13.16-200.fc34.x86_64
- DBeaver version: 21.1.2.202107041908
- Additional extensions: No

#### Connection specification:
- Database name and version: PostgreSQL 11.12 (RDS)
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

But I was able to reproduce this locally in my Docker container `postgres:11.8` as well

#### Describe the problem you're observing:

Invalid fractional seconds shown in DBeaver.

#### Steps to reproduce, if exist:

```
create table test_dbeaver_millis (id text, created timestamp);

insert into test_dbeaver_millis values ('last-3-only', '2021-09-22 21:58:28.000123');
insert into test_dbeaver_millis values ('first-3-only', '2021-09-22 21:58:28.123000');

select 
	id,
	created, 
	extract('epoch' from created) "epoch",
	date_part('milliseconds', created) "millis",
	to_char(created, 'YYYY-MM-DD HH24:MI:SS.MS') "millis_char"
from test_dbeaver_millis;
```

DBeaver results show invalid values in the `created` column. 

![image](https://user-images.githubusercontent.com/26523902/134414804-23c41af9-d2e2-412b-b642-c06674e20fdb.png)

Here are the correct results as returned by PSQL:

```
      id      |          created           |      epoch       |  millis   |       millis_char       
--------------+----------------------------+------------------+-----------+-------------------------
 last-3-only  | 2021-09-22 21:58:28.000123 | 1632347908.00012 | 28000.123 | 2021-09-22 21:58:28.000
 first-3-only | 2021-09-22 21:58:28.123    |   1632347908.123 |     28123 | 2021-09-22 21:58:28.123
(2 rows)
```

#### Include any warning/errors/backtraces from the logs

No errors, no warnings.

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
Hello @mihalyr 

We found, that this is the issue of the SimpleDateFormat.format java method.

Here are 2 workarounds from Preferences -> Editors -> Data Editor - > Data Formats page:

1. Check "Disable date/time formatting" and use server-side data view

2. Change the Timestamp pattern to the `yyyy-MM-dd HH:mm:ss.ffffff`

![2022-03-11 17_05_22-DBeaver Ultimate 22 0 0 - _PartPub80DB_ Script-195](https://user-images.githubusercontent.com/45152336/157886414-c53d3622-fc6f-436b-91ef-06d4345c7450.png)

**Comment by mihalyr** [comment]
Hello @LonwoLonwo, thank you, indeed, I think I had `.SSSSSS` configured and not `.ffffff`, both `.SSS` or `.ffffff` should work, but `.SSSSSS` is incorrect. Thank you. I'll close this one as it is resolved.

**Comment by LonwoLonwo** [comment]
Thanks for the answer @mihalyr 

I will reopen this issue to fix the SSS handling case.

**Comment by LonwoLonwo** [comment]
SSSSSS case fixed

**Comment by uslss** [comment]
verified
