### ISSUE TITLE
Light Theme not working properly on MacOs after update

### ISSUE THREAD

**Issue by sharadrsoni** [dbeaver/dbeaver#13989]
#### System information: 
- Operating system (distribution) and version - MacOS BigSur 11.6
- DBeaver version - Version 21.2.1.202109181446
- Java version - OpenJDK 11
- Additional extensions

#### Connection specification:
- Database name and version - Oracle 19
- Driver name - Oracle 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
After Update to latest version, the theme is not looking correct, I have light theme enabled but, the editor is black, and the text is white.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5358435/134497600-cce44a6b-2647-46a5-82f8-8b11b220bbfe.png">

**Comment by uslss** [comment]
thanks for the report. Issue is fixed in the scope of #13968

**Comment by sharadrsoni** [comment]
Thanks,
Could you please let us know the expected date for next update?
