### ISSUE TITLE
light theme error

### ISSUE THREAD

**Issue by hoanbv128** [dbeaver/dbeaver#13980]
<img width="1064" alt="Screen Shot 2021-09-22 at 19 36 29" src="https://user-images.githubusercontent.com/73464019/134344618-0488f73b-e868-4e08-84d5-d4f6eabe9b9b.png">

**Comment by flambchap** [comment]
This a duplicate of https://github.com/dbeaver/dbeaver/issues/13968. Thank you for the report.
