### ISSUE TITLE
Can not import connections from a csv file into Dbeaver

### ISSUE THREAD

**Issue by shirishkale** [dbeaver/dbeaver#13982]
Hi,

    Even after formatting the columns as mentioned in the documentation, I am still not able to import connections from a csv file into DBeaver.

Shirish

**Comment by uslss** [comment]
@shirishkale could you provide steps to reproduce an issue? is there something in the [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by shirishkale** [comment]
The database connections are never imported from the xml / csv files.
Please find attached csv, xml as well as process screenshot

[conn_import_test.csv](https://github.com/dbeaver/dbeaver/files/7219891/conn_import_test.csv)
s
[dbeaver import screenshots.docx](https://github.com/dbeaver/dbeaver/files/7219893/dbeaver.import.screenshots.docx)
.

**Comment by uslss** [comment]
@shirishkale
i was able to import connections from your example. But i was need to change column header to lowercase and switch file encoding to UTF-8 from UTF-8-BOM. Could you check if it works for you?
[new2.csv](https://github.com/dbeaver/dbeaver/files/7220037/new2.csv)
![image](https://user-images.githubusercontent.com/31996417/134564691-1a7ae819-f973-4dbd-95b7-52a45b0d8b01.png)

**Comment by shirishkale** [comment]
Yes it works
Thanks
