### ISSUE TITLE
role is no longer being double-quoted when adding permissions

### ISSUE THREAD

**Issue by getta-mike** [dbeaver/dbeaver#13993]
As of recent version or two, when granting permissions on a table (and this could be the case with other objects) the role isn't being properly double-qouted, causing an error.  This error is due to having caps or dashes, etc. in the role name.  Furthermore, this new behavior is observable only when the role doesn't have any permissions to start, i.e., revoking permissions or granting additional permissions works fine (with quoting). 
Current version: Version 21.2.1.202109181446
![image](https://user-images.githubusercontent.com/72145576/134532792-941f9e3b-a987-4e19-8353-655901c19bd0.png)

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by getta-mike** [comment]
**Further info:**
Driver: Postgres
Versions:

> 21.2.1.202109181446 (windows)
> 21.2.0 (windows)
> 2.1.2.0 MacOS
> 2.1.2.1 (macOS)

**Comment by uslss** [comment]
thanks for the report

**Comment by Matvey16** [comment]
@getta-mike thank you for the report, we will work on that

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.2.5

**Comment by Matvey16** [comment]
Verified

**Comment by getta-mike** [comment]
bravo. spasibo!

**Comment by getta-mike** [comment]
I have a few more; should I send in a batch or each separately?

**Comment by Matvey16** [comment]
Better to create separate issue for each of the problems
