### ISSUE TITLE
Error when opening SQL Editor - Database Sybase

### ISSUE THREAD

**Issue by raquelliszet** [dbeaver/dbeaver#13995]
#### System information: 
- MacOS Big Sur
- DBeaver version: Versión7.2.5.202011152110

Error:
Can't open editor connection

Message:
JZ006: Se ha detectado IOException: java.io.IOException: JZ0TS: Error de truncamiento al intentar enviar DBeaver 7.2.5 - SQLEditor <Script-7.sql>.

**Comment by uslss** [comment]
@raquelliszet could you check if it is reproducible for you against 21.2.1?

**Comment by uslss** [comment]
there is no update on issue for a long time. If it is still actual, feel free to reopen it with additional info
