### ISSUE TITLE
Driver Manager: Can't open driver file by double-clicking on it

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#13992]
#### System information: 
- Operating system (distribution) and version: **Windows 10**
- DBeaver version: **DBeaver 21.2.2**
- Additional extensions: **none**

#### Describe the problem you're observing:
In Driver Manager, if there's any custom jar files added, you can't open them in explorer by double-clicking on them.

#### Include any warning/errors/backtraces from the logs
```
Command 'org.eclipse.ui.ide.showInSystemExplorer' is disabled
```

**Comment by Matvey16** [comment]
Verified
