### ISSUE TITLE
Owner of a function/Procedure is not returned for Redshift

### ISSUE THREAD

**Issue by deepaksenthilkumar** [dbeaver/dbeaver#13997]
The owner of a function/Procedure is not returned for Redshift in the properties tab

![image](https://user-images.githubusercontent.com/36084950/134598248-944c53b9-3019-4578-b4a2-14e17ab837cf.png)

**Comment by LonwoLonwo** [comment]
Hello @deepaksenthilkumar 
What version of DBeaver do you use?

**Comment by deepaksenthilkumar** [comment]
21.2.1
-- 
SD

**Comment by LonwoLonwo** [comment]
In this case, the owner meant the user, and the support of users in DBeaver is present only in the EE version.
