### ISSUE TITLE
ODBC connection Error.

### ISSUE THREAD

**Issue by andregalvez79** [dbeaver/dbeaver#14005]
I already checked issue [#8732](https://github.com/dbeaver/dbeaver/issues/8732) and worked through the recommended steps and still have the issue.

#### System information: 
- Windows 10 Enterprise version 1909
- DBeaver Version 21.1.3.202107181810

- VPN to test connection to servers.

#### Describe the problem you're observing:
Trying to create an ODBC connection through DBeaver and I get the following message:
I've tried downloading the files directly adding them to the library. and the possible fix mentioned in issue [#8732](https://github.com/dbeaver/dbeaver/issues/8732) regarding the _.xml_ file. It's already updated i didn't had to modify anything.

Can't create driver instance
  Error creating driver 'ODBC' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'sun.jdbc.odbc.JdbcOdbcDriver'
  Error creating driver 'ODBC' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'sun.jdbc.odbc.JdbcOdbcDriver'
    sun.jdbc.odbc.JdbcOdbcDriver
    sun.jdbc.odbc.JdbcOdbcDriver

When I try to download the drivers (with and without VPN) I get the following message:

Driver file download failed.
Do you want to retry?

Reason:
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by uslss** [comment]
@andregalvez79 could you check if the issue is reproducible for you against 21.2.1 version?

**Comment by uslss** [comment]
the issue cannot be reproduced.
If it is still actual for you - feel free to reopen it.

**Comment by 70milan** [comment]
> the issue cannot be reproduced. If it is still actual for you - feel free to reopen it.

Issue still persists on dbeaver 21.2.5

**Comment by serge-rider** [comment]
Perhaps it is the same issue as in #5704. You may need to add corporate certificate in Java (the one which is bundled in DBeaver).
