### ISSUE TITLE
Backup options for "drop if exists" and "create database"

### ISSUE THREAD

**Issue by CheyenneForbes** [dbeaver/dbeaver#14008]
**Is your feature request related to a problem? Please describe.**
Adding options to add "drop if exists" and "create database" statements when backing up a database would make workflows a bit better.

**Describe the solution you'd like**
Just as we have the "Use sql insert instead of copy for rows", it would be good to have options for "drop if exists" and "create database"
![image](https://user-images.githubusercontent.com/8251976/134779656-f4ec9d6f-618b-49b6-b628-060d0d26528c.png)

**Describe alternatives you've considered**
So far when using dbeaver, we manually add the statements. We'd love to stick with dbeaver since its UX is better.

**Additional context**
Here's what we get in pgAdmin:
![image](https://user-images.githubusercontent.com/8251976/134779570-f0916fd3-a78f-4ae0-a0f3-409762901460.png)

**Comment by Matvey16** [comment]
@CheyenneForbes Thank you for the suggestion

**Comment by CheyenneForbes** [comment]
Any idea when it would be added?

**Comment by Matvey16** [comment]
@CheyenneForbes Currently scheduled for 21.3.3 release

**Comment by LonwoLonwo** [comment]
![2022-01-24 09_05_57-Restore](https://user-images.githubusercontent.com/45152336/150736911-452e0bfd-781b-4247-a566-aa3736b088fd.png)

![2022-01-24 09_23_05-Backup](https://user-images.githubusercontent.com/45152336/150736915-f951b74d-c4ac-434c-aa37-2a43c3691c18.png)

Implemented. In the backup and restore settings.
Also, a new warning was added to the "Clean objects" settings button in the Restore Database dialog.

**Comment by LonwoLonwo** [comment]
A --create argument added to restore settings.

**Comment by Matvey16** [comment]
Verified
