### ISSUE TITLE
Tab names from Athena Queries have random alphanumeric text 

### ISSUE THREAD

**Issue by timchan96** [dbeaver/dbeaver#14009]
#### System information: 
- Windows 10 Enterprise
- 21.2.1
- No Additional extensions

#### Connection specification:
- Amazon Redshift 
- redshift-jdbc42
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  Yes
#### Describe the problem you're observing:
When a qurey on an Amazon Athena table is executed, Dbeaver creates a tab with the table name along with some random alphanumeric text. Ie. See below image (table_name_was_here_5ccda2e896f99(+) 1)
![image](https://user-images.githubusercontent.com/80280027/134788609-16629c3b-b84e-4671-9baf-7c719102d641.png)
#### Steps to reproduce, if exist:

1. Create a Amazon Redshift connection
2. Create an Amazon Athena table
3. Query the Athena table
4. Look at the tab name

**Comment by Matvey16** [comment]
@timchan96 Hello, can you provide a DDL for the table and a query that leads to this issue?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info
