### ISSUE TITLE
MSSQL: Can't find metadata object, cannot open declarations from editor

### ISSUE THREAD

**Issue by rgobo** [dbeaver/dbeaver#14001]
#### System information: 
- Windows 10, DBeaver 21.2.1 (20.09.2021)

#### Connection specification:
MSSQL server, driver version 8.2.0.jre8

#### Describe the problem you're observing:
Unable to open table/view declarations from the text editor. Either right click -> open declaration, or the F4 shortcut, result in the error message "can't find metadata for name '...'". If I do it from the database navigator it works fine however. 

I also discovered that the declaration can be opened if the schema is also specified ( db.tableName rather than just tableName), but that wasn't necessary so far.

Possibly related is also the fact that the Ctrl+Shift+D (Open Database Object) doesn't list any tables or views at all, no matter what is typed. Seems like an issue loading metadata in general.

#### Steps to reproduce, if exist:
As above, type "SELECT * FROM tableName", click on tableName (or select it) and press F4, error "cant find metadata object" is thrown in the status bar.

I tried specifying / filtering just one schema in the connection settings and this didn't help. This happens on various connections that worked fine until the last update.

**Comment by LonwoLonwo** [comment]
Thanks for the bug report!

**Comment by uslss** [comment]
verified
