### ISSUE TITLE
File extension is not appended when saving file from DBeaver

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14013]
#### System information: 
- Operating system (distribution) and version Win10 Pro 20H2 19042.1237
- DBeaver version 21.2.1

#### Describe the problem you're observing:
In some cases for example when saving Execution plan or custom ERD, the file is created without extension

#### Steps to reproduce, if exist:
1. Open execution plan for a query
2. Click `Save plan`
3. Type a name without an extension
4. Save file

**Expected:** New file has .dbplan extension
**Actual:** File is saved without extension

![8GpzySvspf](https://user-images.githubusercontent.com/82543000/134894400-ac63e9b5-ab8b-4ae3-9420-b5fd0799c1ff.gif)

**Comment by i-Niki** [comment]
i have the same issue, and i am not able to save my er as png as well, did someone come across this problem?

**Comment by ShadelessFox** [comment]
Hello @i-Niki,

As a workaround you can append file extension manually.

**Comment by LarryLoveIV** [comment]
This is happening to me when simply trying to save .sql scripts. The workaround does work, however, pretty inconvenient to have to do that each time you want to save a file.

**Comment by glen-weatherhead** [comment]
Can confirm this happens for me as well. If I save as the default name it keeps the .sql file extension but if I change the name to anything else it sets is without any file extension.

**Steps to Reproduce:**
1) Save File As .sql type (with a name as anything except for default)

**Expected result:** file type is saved as sql type
**Actual result:** file type is set to 'file' type

**Workaround**: Save file with .sql in the name and/or rename the file on computer to end in .sql

Default name
![image](https://user-images.githubusercontent.com/88672467/136999011-11d74351-bc93-4122-85dc-27443697888e.png)
![image](https://user-images.githubusercontent.com/88672467/136999025-d57ba650-153c-4391-aa0d-d7c71713f8df.png)

Custom name
![image](https://user-images.githubusercontent.com/88672467/136999044-1651d9ae-d19e-4353-8e44-fa19c87e3d44.png)
![image](https://user-images.githubusercontent.com/88672467/136999053-ea2ed924-2cf0-4172-98ee-d5a8d784f5f0.png)

Workaround
![image](https://user-images.githubusercontent.com/88672467/136999468-00086934-b36b-4899-98bf-bb47bb8d189a.png)

**Comment by Matvey16** [comment]
Verified
