### ISSUE TITLE
Cannot create connection to Athena

### ISSUE THREAD

**Issue by thefox1977** [dbeaver/dbeaver#14015]
Hello, 

i think this is same bug [3941.](https://github.com/dbeaver/dbeaver/issues/3941)

Connection Manager does not display the correct fields no AWS Access Key and Aws Private Key, but i see username and pwd.

DBeaver Community Edition: 21.2.1.202109181446

THX so much.

**Comment by Matvey16** [comment]
@thefox1977 Hello, Athena connection looks like this in the Community Edition. You need to enter Access Key as Username and Private Key as Password

**Comment by thefox1977** [comment]
> @thefox1977 Hello, Athena connection looks like this in the Community Edition. You need to enter Access Key as Username and Private Key as Password

Hello @Matvey16,

thx for the answer!!!

Yes, I tried to insert and my driver is com.simba.athena.jdbc.Driver but for now nothing.

**Comment by Matvey16** [comment]
@thefox1977 Can you provide the error that you get?

**Comment by kylephillips1987** [comment]
I am having the same issue. The JDBC url looks off. Nothing for AWS Secret Key.

**Comment by kylephillips1987** [comment]
Default Athena JDBC URL:jdbc:athena://AWSRegion={region};

**Comment by uslss** [comment]
@kylephillips1987 did you try to create the connection using [New Database Connection Wizard](https://github.com/dbeaver/dbeaver/wiki/Create-Connection) or any other way? Could you provide steps to reproduce an issue?
it is possible to connect to Athena for me in CE.
![image](https://user-images.githubusercontent.com/31996417/135811854-1d0a005e-a6d3-4e4a-bc2b-e826e170ec57.png)

**Comment by uslss** [comment]
there is no update on the issue for a long time. if it is still actual for you - feel free to reopen it with additional info.
