### ISSUE TITLE
postgresql: New deferrable foreign key is not deferrable

### ISSUE THREAD

**Issue by fjf2002** [dbeaver/dbeaver#14021]
#### System information: 
- Operating system (distribution) and version: **WSL2**
- DBeaver version **21.2.1**

#### Connection specification:
- Database name and version: **PostgreSQL 13.4**
- Driver name **pgJDBC 42**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **no**

#### Describe the problem you're observing:
When I add a new foreign key to a table, I can select "deferrable" ("aufschiebbar" in german version), but the resulting SQL does not contain the DEFERRABLE keyword.

#### Steps to reproduce, if exist:
Add a new foreign key to a table, select "deferrable", save.

**Comment by uslss** [comment]
thanks for the report
![image](https://user-images.githubusercontent.com/31996417/134958254-e2965906-2241-4288-a3d6-de69416039a4.png)

**Comment by ShadelessFox** [comment]
Fixed.

**Comment by uslss** [comment]
verified
