### ISSUE TITLE
"Insert space after table/column name" does not respect existing spaces after the cursor.

### ISSUE THREAD

**Issue by dstj** [dbeaver/dbeaver#14031]
More of an annoyance that a bug about the "Insert space after table/column name" feature.

![image](https://user-images.githubusercontent.com/467692/135099877-58739be0-c2ab-4493-b8d9-14eaf53dc4f0.png)

When editing an existing SQL query to add an extra column in the SELECT for example, when hitting ENTER to accept the suggestion, the cursor moves to the left of the next word (e.g. FROM) instead of just pushing everything "forward".

This causes a problem with auto-completion when trying to add multiple columns (see gif) as the auto-complete doesn't work because the cursor is now on the next word.

![dbeaver](https://user-images.githubusercontent.com/467692/135102499-cb16fdb4-b33a-4fce-bd8a-f3ce40eb0939.gif)

Unchecking the option fixes that but also introduces other annoyances.

#### System information: 
- Operating system: Windows 10 Pro, v10.0.19042 Build 19042
- DBeaver version: Version 21.2.1.202109181446
- DB Connection: PostgreSQL

**Comment by uslss** [comment]
thanks for the report

**Comment by Matvey16** [comment]
Verified

**Comment by Destrolaric** [comment]
Reopened due to found bug with selection of line break characters

**Comment by Matvey16** [comment]
Verified
