### ISSUE TITLE
Changing connection in SQL Console doesn't change schema

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14045]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.2.2

#### Steps to reproduce, if exist:
1. Open SQL Console for any connection
2. Pick another connection from the navigator

**Expected:** Connection and schema is changed for current SQL Editor
**Actual:** Connection is changed, but the schema from first connection  doesn't change

![chragqrQrQ](https://user-images.githubusercontent.com/82543000/135217889-6fa96e19-a4a3-4ba8-8e54-f94971a70109.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
