### ISSUE TITLE
Preferences filter text does not work for all settings

### ISSUE THREAD

**Issue by timbze** [dbeaver/dbeaver#14042]
#### System information: 
- Ubuntu 21.04
- DBeaver 21.2.1.202109181446
- Additional extensions: none

#### Describe the problem you're observing:
Preferences "type filter text" field does not work for filter settings. #10979 may have been related

#### Steps to reproduce, if exist:
1. Go to Window > Preferences
2. In "type filter text" field on top left, enter "DDL", or "case", or "case-sensitive", etc
3. Some results may come up, but
4. Under Connections > Metadata is a setting "Use case-sensitive names in DDL statements", and
5. This setting never shows up, regardless of which words you put in the filter test

#### Include any warning/errors/backtraces from the logs
There is nothing in the error log

**Comment by Matvey16** [comment]
@timbze Thank you for the suggestion. It is a really good feature, but it is actually pretty huge to implement. So it is planned, but actual release for it can't be estimated for now.
