### ISSUE TITLE
Wiki -> Develop in Eclipse -> Running and Debugging

### ISSUE THREAD

**Issue by kai-morich** [dbeaver/dbeaver#14044]
Hi

The last step  `Run -> Run Configurations -> Add Required Plug-ins` [here](https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse#running-and-debugging-in-eclipse) could be enhanced.

For whatever reason some plugins where not selected in my dev environment:
![grafik](https://user-images.githubusercontent.com/25850372/135213263-78ee40f5-1ba1-41bf-b6c1-983bc25e49ac.png)

I recommend you also mention _missing database specific UI_ as reason for this step

**Comment by kai-morich** [comment]
note: looks like DBeaver.product.launch file is outdated. there hana.ui plugin is not mentioned

**Comment by LonwoLonwo** [comment]
Thanks for the idea @kai-morich!

https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse updated :)

**Comment by LonwoLonwo** [comment]
DBeaver.product.launch also updated.
