### ISSUE TITLE
Mac Downloads Broken

### ISSUE THREAD

**Issue by willselby** [dbeaver/dbeaver#14051]
Good morning,

The download links for MacOS .dmg files for previous versions at https://dbeaver.io/files appear to be broken.

The most recent 21.2.1 seems to work, but for others I'm getting a 403 response e.g. https://dbeaver.io/files/21.2.0/dbeaver-ce-21.2.0-macos.dmg

Thanks!

**Comment by LonwoLonwo** [comment]
Thanks for the bug report!
Fixed for versions 21+
