### ISSUE TITLE
[CE] Existing foreign key aren't visible

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#14059]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.2.2

#### Connection specification:
- Database name and version Netezza

#### Describe the problem you're observing:
Existing foreign keys aren't shown for the tables
![image](https://user-images.githubusercontent.com/31996417/135356172-f467cc15-fa26-4579-b7ee-5119f7d1b375.png)
![image](https://user-images.githubusercontent.com/31996417/135356270-118ee75e-c720-4f81-85ea-37bc7754879e.png)

**Comment by LonwoLonwo** [comment]
Implemented in EE version.
