### ISSUE TITLE
Support for CouchDB

### ISSUE THREAD

**Issue by stefanrehm** [dbeaver/dbeaver#1406]
Hi Serge!
I have been using DBeaver for a number of years and have been converting all my colleagurs to be faithful DBeaver users. Congrats for a great product!

Now, I was wondering whether it is feasible to support CouchDB and whether you plan to incorporate it in the near future?

Thanks!

**Comment by serge-rider** [comment]
Agreed, this is interesting. Can be added in EE version - it seems to be similar to MongoDB.

**Comment by brunowego** [comment]
I'm look exactly for this support 👍

**Comment by brajesh-mehra** [comment]
I have waiting for this update since a long. Currently I am using version 6.3.202001051908. 

I am hoping if you can publish a date for 7.0.0 release, much appreciated!

Thank you in advance.

**Comment by Johnniestang** [comment]
Is there a possible release date for CouchDB support? Also, will this be made available in community edition at some point?

**Comment by tati-kru** [comment]
CouchDB support will be added to DBeaver EE 7.0.

**Comment by Johnniestang** [comment]
> CouchDB support will be added to DBeaver EE 7.0.

Thanks for the update. Any plans for Community edition?

**Comment by tati-kru** [comment]
@Johnniestang we are not planning to add CouchDB support to DBeaver CE near future.

**Comment by rdewolff** [comment]
Whats the ETA of 7.0?

**Comment by tati-kru** [comment]
@rdewolff Release date for DBeaver EE 7.0 is on March 9. The EA version is already available for test.

**Comment by uslss** [comment]
verified

**Comment by rdewolff** [comment]
I have downloaded and instlalled early DBeaver EE 7.0, cannot see any CouchDB drivers in there. Am I missing something? I see Couchbase tho.

**Comment by serge-rider** [comment]
This is funny.
This ticket was mixed up with #3540 (Couchbase support).

**Comment by rdewolff** [comment]
Oh no 🤦‍♂ !

**Comment by nkev** [comment]
So is there an ETA on CouchDB (not Couchbase) support?

**Comment by tati-kru** [comment]
@nkev we are planning to implement it before 7.2 (release early September).

**Comment by serge-rider** [comment]
CouchDB extension is ready for testing in the Early Access version (https://dbeaver.com/files/ea)

**Comment by zmartell** [comment]
Hi Serge, 

I am using CouchDB as my main DB, I moved away from MSSQL. I was looking to do trial version but it doesnt seem to let me as the license server when I opened the app and requested for license gave me a license for 7.1 while this is 7.2.0, and wont let me further into the app.

I was looking to buy the EE if this is suitable for one of my coworkers, as they aren't very database-friendly, and the CouchDB official Fauxton isn't enough. 

Is there any way to obtain a 7.2.0 trial license key, or should I wait until production? I would of loved to provide feedback as well. 

Thanks.

**Comment by rdewolff** [comment]
Same issue as Serge, I can get in by dismissing the trial license but then as soon as I try to do anything the app crashes.

**Comment by nkev** [comment]
I already have the Enterprise license and this early access version 7.2.0 is running well for me. I downloaded the windows zip file version (with no installer exe) and just ran dbeaver.exe from the downloaded and unzipped dbeaver folder. So you may require a EE license to get it working.

My first impressions are good. It's similar to the Mongo DB experience. The JSON editor in the right side-panel works well. The SQL filter in Grid view doesn't seem to work yet. I cannot see any CouchDB specific functionality, like replication/user/config management, but this is a good start.

**Comment by uslss** [comment]
verified.
Issues about read-only grid and non-working filters are created

**Comment by rdewolff** [comment]
Issue closed - does that mean we can now test this version with the trial version?

**Comment by uslss** [comment]
Now it is available in Early Access version (https://dbeaver.com/files/ea/)
7.2 version, that will include this feature will be released at 7 Sep

**Comment by rdewolff** [comment]
Is there any way to test this 7.2 version with a trial key? The key generated are only valid for 7.1.
