### ISSUE TITLE
javaw.exe is not included in dbeaver.exe

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#14066]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.2 EA

#### Steps to reproduce, if exist:
Install EA version and try to open DBeaver

**Expected**: DBeaver is opened
**Actual result**: DBeaver cannot be opened because file `javaw.exe` hasn't been found 
![dbeaver_EbVV0chnNN](https://user-images.githubusercontent.com/51405061/135416662-5863e716-697e-47c1-b64c-2f13c56a5d03.png)

**Comment by flambchap** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by carlos-garcia** [comment]
this is happening to me today.. i noticed that DBeaver was updated today from the microsoft store...

last friday my dbeaver installation was fine

**Comment by kshitij-bartoula** [comment]
Dbeaver
---------------------------
A Java Runtime Environment (JRE) or Java Development Kit (JDK)
must be available in order to run Dbeaver. No Java virtual machine
was found after searching the following locations:
C:\Program Files\WindowsApps\DBeaverCorp.DBeaverCE_22.3.4.0_x64__1b7tdvn0p0f9y\jre\bin\javaw.exe

is occurring for dbeaver downloaded form microsoft store (community edition on my case)

**Comment by flambchap** [comment]
@carlos-garcia @kshitij-bartoula Will be fixed in the scope of https://github.com/dbeaver/dbeaver/issues/18960

**Comment by BennyAlex** [comment]
I got this error today, yesterday the app worked just fine. I got mine from windows store. Reinstalling doesnt help either.

**Comment by carlos-garcia** [comment]
im getting this error again today in a update of the microsoft store app.. here's the ticket with workarounds https://github.com/dbeaver/dbeaver/issues/18960#issuecomment-1422646908

**Comment by flambchap** [comment]
Hi @BennyAlex @carlos-garcia Here is an issue for this case: https://github.com/dbeaver/dbeaver/issues/20211

**Comment by treysis** [comment]
> here's the ticket with workarounds [#18960 (comment)](https://github.com/dbeaver/dbeaver/issues/18960#issuecomment-1422646908)

**Attention**: Workaround requires admin rights‼

**Comment by YasminRamos** [comment]
I got this error today, yesterday the app worked just fine. I got mine from windows store. Reinstalling doesnt help either.
