### ISSUE TITLE
Incorrect auto-suggestion behaviour in Grouping Panel Configuration

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#14060]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.2.2

#### Describe the problem you're observing:
Incorrect auto-suggestion behaviour in Grouping Panel Configuration in case function is added for already added column (gif attached
![s2qQBQtMtb](https://user-images.githubusercontent.com/31996417/135357355-7c4b0173-93bd-49d1-8696-8c7b4f1226df.gif)
)

**Comment by LonwoLonwo** [comment]
Works as expected.
