### ISSUE TITLE
It is necessary to press Save to see table object deletion in the Metadata Editor

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#14072]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.1.2 EA

#### Steps to reproduce, if exist:
1. Open a table, delete a column/key/index and save the changes
2. Delete another object in the table

**Expected**: the deleted object disappears after pressing delete
**Actual result**: the deleted object disappears after pressing Save

https://user-images.githubusercontent.com/51405061/135474418-808fc9e1-2573-46e1-bfc3-4095834f2cb4.mp4

**Comment by Matvey16** [comment]
No longer reproducible in 21.3.0
