### ISSUE TITLE
Exception in the table from the Export to CSV File Progress dialog

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#14074]
#### System information: 
- Operating system (distribution) and version
- DBeaver version DBeaver 21.2.2 UE devel
- Additional extensions

#### Connection specification:
- Database name and version Exasol
- Driver name 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
![oaNVxLAn8X](https://user-images.githubusercontent.com/26031301/135485372-e602f38e-a493-4859-be32-0b561cc454c5.gif)

**Comment by flambchap** [comment]
We've decided that having this kind of message is fine. However, we should log the underlying exception.

**Comment by Matvey16** [comment]
Verified
