### ISSUE TITLE
Two identical buttons on the statistics tab in metadata editor

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14082]
#### System information: 
-  Win 10, DBeaver CE 21.2.2

#### Describe the problem you're observing:

https://user-images.githubusercontent.com/43252954/135571820-c37a12f4-c86e-4f80-b731-8376c4ba65a4.mp4

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
