### ISSUE TITLE
Allow to add shared lib for all drivers

### ISSUE THREAD

**Issue by qrkourier** [dbeaver/dbeaver#14080]
**Is your feature request related to a problem? Please describe.**
My custom JDBC driver library depends on yet another jar (an SDK) that can only be loaded once, not per driver, and so I need to load it in a parent class loader, not as a driver-specific lib in drivers manager

**Describe the solution you'd like**
A command-line option to prepend the parent class loader's classpath

**Describe alternatives you've considered**
I tried `dbeaver -vmargs -classpath /path/to/sdk/jar` and `CLASSPATH=/path/to/sdk/jar dbeaver` but the SDK's class that's needed by the custom JDBC driver still can not be found.

**Additional context**
Everything works if I load the SDK as a driver library, but this approach has unacceptable limitations including
* only one driver may be used concurrently because the SDK employs static variables
* some drivers can not be used at all because the SDK is not loaded by the parent class loader

**Comment by ShadelessFox** [comment]
Hello @qrkourier,

Thanks for feature request.

We can provide a way to specify global libraries that will be shared between all drivers.

**Comment by qrkourier** [comment]
Yay! Thanks so much.

Context: I'm using a [Ziti JDBC driver](https://github.com/openziti-incubator/zdbc) which depends on [the Ziti SDK](https://github.com/openziti/ziti-sdk-jvm), and there can only be one Ziti SDK loaded in the JVM.

**Comment by ShadelessFox** [comment]
Implemented and will be available in DBeaver 21.2.4.

You can specify any amount of JAR files you want to use "globally".

![java_vuLJgub4fF](https://user-images.githubusercontent.com/35821147/137350346-96f1167b-2813-4505-bae4-a2022fa78095.png)

**Comment by uslss** [comment]
verified

**Comment by ShadelessFox** [comment]
We need to preserve old behavior. There are several cases when we pass callback objects defined in a particular model bundle to the driver whose classloader does not know about the bundle who defined it.

**Comment by uslss** [comment]
verified
