### ISSUE TITLE
Reset perspective should cancel toolbar hiding 

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14083]
#### System information: 
- Win 10, DBeaver CE 21.2.2 

#### The problem and steps to reproduce
1. Hide toolbar (Window -> Appearance -> Hide toolbar)
2. Reset perspective (Window -> Reset Perspective)
Expected: Toolbar is visible after reset
Actual: UI changes canceled except toolbar hiding

**Comment by Matvey16** [comment]
Fixed in scope of #18474
