### ISSUE TITLE
Date, time values cannoot be exported in JSON, source code formats

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#14081]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.2.2 EA

#### Connection specification:
- Database name and version PostgreSQL

**Precondition**: 
![dbeaver_PhVCgBpLaa](https://user-images.githubusercontent.com/51405061/135562930-1862af2e-75ae-4e82-9432-74444ee4af8c.png)

#### Steps to reproduce, if exist:
Export a table with `date` or `time` values in JSON, source code formats

**Expected**: the table is exported
**Actual result**: the export of date/time fails with an error (note: timestamp column is exported correctly)
**Workaround**: Set Disable date/time formatting

https://user-images.githubusercontent.com/51405061/135563607-c398671c-6a2f-4900-b755-9180a9f8d05d.mp4

[.log](https://github.com/dbeaver/dbeaver/files/7264020/default.log)

**Comment by LonwoLonwo** [comment]
Closed as duplicate: https://github.com/dbeaver/dbeaver/issues/12503
