### ISSUE TITLE
Can't set varchar column of composite type to NULL with disabled "Show complex columns structure"

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#14088]
#### System information: 
- Operating system (distribution) and version: **Windows 10**
- DBeaver version: **21.2.3**

#### Connection specification:
- Database name and version: **PostgreSQL 12**

#### Steps to reproduce, if exist:
1. Use DDL from #13349
2. Disable <kbd>Show complex columns structure</kbd> in Data Editor
3. There's no option to set value to NULL (you can empty it)

**Comment by ShadelessFox** [comment]
Implemented:

![image](https://user-images.githubusercontent.com/35821147/138280870-9cc83187-aa07-4799-9f81-4b5c359e7ed3.png)

**Comment by uslss** [comment]
verified
