### ISSUE TITLE
CLI commands are not proceeded if no DBeaver instance is running

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14085]
#### System information: 
- Win 10, DBeaver CE 21.2.2

DBeaver fails to detect running instance if caller's instance product differs from target's instance product.

It results in a weird behavior when DBeaver instead of closing itself because it can't detect running instance continues running itself.

#### Steps to reproduce, if exist:
1. Close all running instances of DBeaver
1. open cmd
1. execute **cd folder-where-your-dbeaver-is-placed**
1. execute **dbeaver-cli -stop** (or -quit)

Expected: All DBeaver instances are closed
Actual: One more DBeaver instance were opened

**Comment by ShadelessFox** [comment]
Please ask me for testing details.

**Comment by Matvey16** [comment]
The file with instances is not created on Linux

**Comment by Matvey16** [comment]
Verified
