### ISSUE TITLE
DOCUMENT highlighted as special for postgres. Why?

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#14090]
![image](https://user-images.githubusercontent.com/799021/135599796-f1be5157-bc4b-4865-b589-efb0bc99ddc5.png)

#### System information: 
- Linux Mint v19.3
- 21.0.3

#### Connection specification:
- PostgreSQL v13.3

#### Describe the problem you're observing:
`document` is not special`

#### Steps to reproduce, if exist:
see screenshot above

**Comment by ShadelessFox** [comment]
Hello @KES777,

The `document` is a reserved word. 

You can prove it by executing following query:
```sql
select 1 document;
```

It will fail. You need to quote it:
```sql
select 1 "document";
```

I believe it's also contextual, because you can do following:
```sql
select 1 as document;
```
