### ISSUE TITLE
Problem occured, internal error

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#14098]
![image](https://user-images.githubusercontent.com/799021/135630417-d823621b-6f07-42be-a3b0-1b99c1d0a6ef.png)

![image](https://user-images.githubusercontent.com/799021/135630472-ff320828-aa9c-48e4-a1b1-953ca9256c3e.png)

My query just return 50000 lines.

PS. Which `.log` file I should look into?

#### System information: 
- Linux Mint 19.3
- 21.0.3
- Additional extensions

#### Connection specification:
- PostgreSQL 13.3

**Comment by Matvey16** [comment]
@KES777 By default the .log file should be located at `/home/user_name/.local/share/DBeaverData/workspace6/.metadata`

**Comment by KES777** [comment]
It could be more informative to include full path at dialog. Thank you

**Comment by KES777** [comment]
[x.log.txt](https://github.com/dbeaver/dbeaver/files/7293441/x.log.txt)

**Comment by Matvey16** [comment]
@KES777 Does this happen on latest DBeaver version? Also can you give more information about tables used in query and the query itself?

**Comment by KES777** [comment]
I do not have database with this data already =(
It would be nice when you output absolute path to `.log` file, so next time I can find it
Thank you

**Comment by E1izabeth** [comment]
Does this issue still actual?

**Comment by KES777** [comment]
I do not have that environment at the moment, so I can not test it.

**Comment by E1izabeth** [comment]
Please let me know if you find that it's still actual. For now I'm closing it as we can't reproduce the issue.
