### ISSUE TITLE
Functions defined in Oracle WITH clause

### ISSUE THREAD

**Issue by bobf32** [dbeaver/dbeaver#14096]
If Execute SQL Statement is run with the cursor at an arbitrary point in the following statement either of the errors ORA-00904 or ORA-00905 is returned.

```
WITH
  FUNCTION with_function(p_id IN NUMBER) RETURN NUMBER IS
  BEGIN
    RETURN p_id + p_id;
  END;
SELECT with_function(rownum)
FROM   dual
WHERE  rownum = 1;
```

Workaround: In order for DBeaver to successfully execute this query using Execute SQL Statement, the whole thing has to be selected in advance.

**Comment by tati-kru** [comment]
Thank you for the report.

**Comment by E1izabeth** [comment]
Done in scope of #13581

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
This fix created another minor bug. If we have an option `Blank line is statement delimiter` it will be ignored in WITH clause, which is counterintuitive.

**Comment by p91paul** [comment]
@Matvey16 I disagree with this last statement.
For with functions this might be less important, but if I understand correctly the fix should handle also packages and possibly procedures, and in a package body is fairly common to have blank lines.
So I believe the "Blank line is statement delimiter" setting SHOULD be ignored for this kind of complex statement.

**Comment by Matvey16** [comment]
@p91paul Yes, we discussed it and came to a conclusion that it should be working like that
