### ISSUE TITLE
Move 'Create Sample Database' action to more appropriate place 

### ISSUE THREAD

**Issue by NerdishShah** [dbeaver/dbeaver#14108]
On end of DBeaver installation, the prompt displayed to create a sample database. If the prompt is declined, there is no option to create a sample database within the tool.

![image](https://user-images.githubusercontent.com/31189986/135708536-a232d70c-3c5d-4441-984a-1b9fb4c3e801.png)

It could have an option to create a sample database either in new database connection menu/wizard or under help menu

Also, the documentation does not have any information about the sample database

**Comment by flambchap** [comment]
Hello @NerdishShah. To restore the _Sample Database_, click _Help_  --> _Create Sample Database_. Could you please describe what kind of information you want to see in the documentation?

**Comment by NerdishShah** [comment]
@akilovich Please confirm or point in the documentation where the this information is present. Had it been there, this conversations would have not arisen.

I don't see any such option under help for the version **7.2.2.202010041557** 

![image](https://user-images.githubusercontent.com/31189986/135783313-d214a616-7929-4e69-8db2-7fd607d58e6c.png)

![image](https://user-images.githubusercontent.com/31189986/135783389-f7c1b75a-0eeb-4cd9-9b64-4c61ac81df07.png)

**Comment by flambchap** [comment]
This feature was added in 7.2.4

**Comment by flambchap** [comment]
We need to move _Create Database Option_ to _New Database Connection_ dropdown and to the _Database_ menu. We also need to add info about the _Sample Database_ to the bottom of [this](https://github.com/dbeaver/dbeaver/wiki/Installation) page.

**Comment by Matvey16** [comment]
Verified
