### ISSUE TITLE
Apply filter criteria is not visible

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#14102]
![image](https://user-images.githubusercontent.com/799021/135635408-39e18fab-af3e-4393-941f-cdbff982b116.png)

#### System information: 
- Linux Mint 19.3
- 21.0.3
- Additional extensions

#### Connection specification:
- PostgreSQL 13.3

**Comment by uslss** [comment]
seems the issue is fixed already.
Could you check if it is reproducible for you against 21.2.2?
