### ISSUE TITLE
SQL Editor Broken in DBeaver 21.2.1 and 21.2.2 (early access)

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#14114]
This error was introduced in DBeaver 21.2.1.
I am using DBeaver on Mac Catalina

To reproduce simply
1. Open a new empty sql editor on a PostgreSQL database
2. Enter these lines like below with a line feed also after the 3rd line
```
line1
line2
line3

```
3. Position the cursor at the end of the first line (don't use the mouse, just use the keyboard)
4. Hit "enter" key => A new line is inserted but the line after is not going one line down. It just seem to disappear.
5. Hit "enter" key => A new line is inserted but the line after is not going one line down. It just seem to disappear.
6. Hit "backspace" key => The current line is deleted and the two lines that have vanished now reapear.

I have an animated gif attached. Not sure if Github displays it correctly. So you might need to download it.
![SQL_Editor_Broken](https://user-images.githubusercontent.com/38714600/135750844-25e99b56-67bd-4ee0-a29d-7dfb93383481.gif)

**Comment by ShadelessFox** [comment]
Hello @JamesInform,

Thanks for reaching out.

Actually, the same issue was already described in #13966, so I'll have to close this ticket as a duplicate.

**Comment by JamesInform** [comment]
Thanks.

To clarify: This issue still exists in current early access.
