### ISSUE TITLE
unable to locate its companion shared library

### ISSUE THREAD

**Issue by pvidalis** [dbeaver/dbeaver#14122]
- Kubuntu 21.04
- 21.2.2

After upgrading to new version 21.2.2, I can not start the application from menu or from bash. 

The error message says:
**_The Dbeaver executable launcher was unable to locate its companion shared library._**

Unfortunately, I can not find any log related to this problem.

**Comment by alessandrodolci** [comment]
I can confirm, the same is happening to me on Ubuntu 20.04, using `serge-rider` PPA.

**Comment by Matvey16** [comment]
@pvidalis Hello, can you specify how did you upgrade your current version? I tried reproducing it by removing the old an then installing the new version, but it works for me.

**Comment by Matvey16** [comment]
Reproduced this on launchpad version. We are working on it. As a temporary workaround you can use deb package from https://dbeaver.io/download/

**Comment by pvidalis** [comment]
Using serge-rider PPA. Sory for the delay

**Comment by srbetasign** [comment]
Hello, I have the same issue and I'm using serge-rider PPA too to install DBeaver.
I have checked the ini file to be sure the path to the launcher plugin is good and it is.

I have also tried to install it from the DEB file but i'm facing the same issue.
I would suggest to download the zip and extract it as it works for me.

Thank you

**Comment by serge-rider** [comment]
Something went wrong during Java packaging. Looking into it.

Workaround (poor): delete folder `/usr/share/dbeaver-ce/jre` - in this case dbeaver will search for Java on local machine.

**Comment by ramundomario** [comment]
> Something went wrong during Java packaging. Looking into it.
> 
> Workaround (poor): delete folder `/usr/share/dbeaver-ce/jre` - in this case dbeaver will search for Java on local machine.

Unfortunately for me the workaround didn't work (JRE installed on the system)

**Comment by TiS** [comment]
I have investigated the issue.

DEB file is missing all *.so files (maybe more, but they are most important here).

After copying *.so files from dbeaver ZIP to /usr/share/dbeaver-ce (of course, respecting folder structure of so files) it works.

My copy command (invoked from inside of unpacked dbeaver ZIP folder - **WARN** this involves sudo, so use with caution):

```sh
sudo find . -name '*.so' -exec cp -R '{}' '/usr/share/dbeaver-ce/{}' \;
```

@ramundomario

Workaround did not probably work because one of the so files is specific to Eclipse (launcher GTK)

`/usr/share/dbeaver-ce/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.200.v20210429-1609/eclipse_11401.so`

**Comment by cprn** [comment]
I can confirm copying Shared Object files from archive works. Dummy script below - either copy in a file and do `chmod u+x file` then run it or copy each line in terminal (omitting 1st one):
```sh
#/bin/sh
cd /tmp
wget https://dbeaver.io/files/dbeaver-ce-latest-linux.gtk.x86_64.tar.gz
tar xf dbeaver-ce-latest-linux.gtk.x86_64.tar.gz
cd dbeaver
find -name '*.so' -exec sudo cp {} /usr/share/dbeaver-ce/{} \;
cd ..
rm -rf dbeaver dbeaver-ce-latest-linux.gtk.x86_64.tar.gz
```

**Comment by serge-rider** [comment]
PPA package was fixed and re-uploaded

**Comment by ramundomario** [comment]
> PPA package was fixed and re-uploaded

I confirm that it's fixed :+1:

**Comment by TiS** [comment]
Yes, it works ok.

**Comment by Matvey16** [comment]
Verified
