### ISSUE TITLE
Auto-complete offers columns from default schema in when table name is written before column name

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#14121]
#### System information: 
- Operating system (distribution) and version Win 10
- DBeaver version 21.2.0

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
Write in SQL Editor for default schema (pagila.public) `select t_history. from logging.t_history th` and try to use auto-complete after `t_history.`
or
`select * from logging.t_history th where t_history.`

**Expected**: the table columns are displayed
**Actual resul**t: no proposals, because the table doesn't exist in public schema (if a table with the same name exists in public, columns will be offered from it.
**Workaround**: delete table name before dot or write a table alias instead of that.

https://user-images.githubusercontent.com/51405061/135815186-79c32c50-aa98-46c6-949f-8264b3523b99.mov

**Comment by LonwoLonwo** [comment]
It works as expected.

We can't use this type of statement like `select t_history.column_name from logging.t_history th` from not `logging` schema.

We must use the fully qualified names for the SELECT in this case.

![2022-03-11 11_01_13-DBeaver Ultimate 22 0 0 - _postgres12local_ Script-170](https://user-images.githubusercontent.com/45152336/157827402-8aebc95b-886a-4c59-bac1-8dc685261533.png)

![2022-03-11 11_01_46-DBeaver Ultimate 22 0 0 - _postgres12local_ Script-170](https://user-images.githubusercontent.com/45152336/157827405-eaf8f943-145f-476b-b14d-49a4500f3114.png)

![2022-03-11 11_05_09-](https://user-images.githubusercontent.com/45152336/157827407-a96e8468-a57b-4aa3-a5a0-ab43b1d3ea65.png)
