### ISSUE TITLE
Value panel not showing dictionary values when both identifier and description columns are the same

### ISSUE THREAD

**Issue by sparrowek** [dbeaver/dbeaver#14134]
#### System information: 
- Windows 10 (64 bit)
- Version 21.2.2.202110030714

#### Connection specification:
- SQL Server
- VPN connection

#### Describe the problem you're observing:
Value panel is not showing values despite foreign keys being defined
Dictionary name is being shown, however.

#### Steps to reproduce, if exist:
![image](https://user-images.githubusercontent.com/1598273/135980132-8649277e-0604-4ea9-8a28-4fded7a16a83.png)

**Comment by uslss** [comment]
@sparrowek could you check if there is something in the [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)? 
unfortunately, cannot reproduce it

**Comment by sparrowek** [comment]
![image](https://user-images.githubusercontent.com/1598273/135996310-2cbdd39f-fcd2-4b5f-af0f-d41ebe116c92.png)

**Comment by sparrowek** [comment]
![image](https://user-images.githubusercontent.com/1598273/135996434-8a7e7ed8-5b55-4c85-9204-fec5d01aa38c.png)

**Comment by sparrowek** [comment]
![image](https://user-images.githubusercontent.com/1598273/135996610-b25683a5-c967-4de5-bfe3-fb4a446e1926.png)

**Comment by LonwoLonwo** [comment]
"Value" and "PeriodParts" tables DDL will be also very helpful.

**Comment by sparrowek** [comment]
-- Drop table

-- DROP TABLE CRM.Budget.Value;

CREATE TABLE CRM.Budget.Value (
	Id int IDENTITY(1,1) NOT NULL,
	AveragePrice decimal(18,2) DEFAULT 0.0 NOT NULL,
	Tm2 decimal(18,2) DEFAULT 0.0 NOT NULL,
	PeriodPartId int DEFAULT 0 NOT NULL,
	ValueDataTypeId int DEFAULT 0 NOT NULL,
	CreatedAt datetime2 DEFAULT '1970-01-01T00:00:00.0000000+01:00' NOT NULL,
	CreatedByUserId int DEFAULT 1 NOT NULL,
	ModifiedAt datetime2 DEFAULT '1970-01-01T00:00:00.0000000+01:00' NOT NULL,
	ModifiedByUserId int DEFAULT 1 NOT NULL,
	BudgetCustomerDetailId int NULL,
	IsFrozen bit DEFAULT CONVERT([bit],(0)) NULL,
	CONSTRAINT PK_Value PRIMARY KEY (Id),
	CONSTRAINT FK_Value_BudgetCustomerDetail_BudgetCustomerDetailId FOREIGN KEY (BudgetCustomerDetailId) REFERENCES CRM.Budget.BudgetCustomerDetail(Id) ON DELETE CASCADE,
	CONSTRAINT FK_Value_PeriodPart_PeriodPartId FOREIGN KEY (PeriodPartId) REFERENCES CRM.Budget.PeriodPart(Id),
	CONSTRAINT FK_Value_User_CreatedByUserId FOREIGN KEY (CreatedByUserId) REFERENCES CRM.[User].[User](ID_DW),
	CONSTRAINT FK_Value_User_ModifiedByUserId FOREIGN KEY (ModifiedByUserId) REFERENCES CRM.[User].[User](ID_DW),
	CONSTRAINT FK_Value_ValueDataType_ValueDataTypeId FOREIGN KEY (ValueDataTypeId) REFERENCES CRM.Budget.ValueDataType(Id)
);
 CREATE NONCLUSTERED INDEX IX_Value_BudgetCustomerDetailId ON Budget.Value (  BudgetCustomerDetailId ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_Value_CreatedByUserId ON Budget.Value (  CreatedByUserId ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_Value_ModifiedByUserId ON Budget.Value (  ModifiedByUserId ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_Value_PeriodPartId ON Budget.Value (  PeriodPartId ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_Value_ValueDataTypeId ON Budget.Value (  ValueDataTypeId ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;

-- Drop table

-- DROP TABLE CRM.Budget.PeriodPart;

CREATE TABLE CRM.Budget.PeriodPart (
	Id int IDENTITY(1,1) NOT NULL,
	Value int NOT NULL,
	PeriodId int NULL,
	CreatedAt datetime2 DEFAULT '1970-01-01T00:00:00.0000000+01:00' NOT NULL,
	CreatedByUserId int DEFAULT 1 NOT NULL,
	ModifiedAt datetime2 DEFAULT '1970-01-01T00:00:00.0000000+01:00' NOT NULL,
	ModifiedByUserId int DEFAULT 1 NOT NULL,
	SequenceId int DEFAULT NEXT VALUE FOR [Budget].[SEQ_PeriodPart_SequenceId] NOT NULL,
	CONSTRAINT PK_PeriodPart PRIMARY KEY (Id),
	CONSTRAINT FK_PeriodPart_Period_PeriodId FOREIGN KEY (PeriodId) REFERENCES CRM.Budget.Period(Id) ON DELETE CASCADE,
	CONSTRAINT FK_PeriodPart_User_CreatedByUserId FOREIGN KEY (CreatedByUserId) REFERENCES CRM.[User].[User](ID_DW),
	CONSTRAINT FK_PeriodPart_User_ModifiedByUserId FOREIGN KEY (ModifiedByUserId) REFERENCES CRM.[User].[User](ID_DW)
);
 CREATE NONCLUSTERED INDEX IX_PeriodPart_CreatedByUserId ON Budget.PeriodPart (  CreatedByUserId ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_PeriodPart_ModifiedByUserId ON Budget.PeriodPart (  ModifiedByUserId ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_PeriodPart_PeriodId ON Budget.PeriodPart (  PeriodId ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;

**Comment by ShadelessFox** [comment]
Hello @sparrowek,

Value panel failed to determine column that can be used as description. 

Please go to <kbd>Define Description</kbd>, uncheck `Id` column and specify any other meaningful column:

![image](https://user-images.githubusercontent.com/35821147/136022790-2ef72f6c-dfb4-4fd5-ac09-ba062b461baf.png)

**Comment by sparrowek** [comment]
It works now :) So it seems the problem arises when you select the column that is referenced from the foreign key.

![image](https://user-images.githubusercontent.com/1598273/136024877-a47c732e-cde5-46d2-9453-abb047dcd47d.png)
Selecting the id column causes an issue.

**Comment by sparrowek** [comment]
Why not to present this column anyway? I mean the value and the description column should be the same now. The problem is that probably the constructed SQL generates the ambiguity because it does not use aliases. If so the problem will appear anytime the dictionary table has a column with the same name as the referenced table and such columns is selected by the user.

**Comment by sparrowek** [comment]
There is another bug probably related:
![image](https://user-images.githubusercontent.com/1598273/136025725-697c0637-ba75-4056-ba23-6c3652b981dc.png)
The value is highlighted in the unrelated row simply because it has the matching description.

**Comment by ShadelessFox** [comment]
The possible solution would be to use aliases to avoid name conflicts.

**Comment by uslss** [comment]
verified
