### ISSUE TITLE
Refresh selected tab of a result set

### ISSUE THREAD

**Issue by gleimar-botelho** [dbeaver/dbeaver#14132]
Hi,

After I changed from version 21.1.5 to 21.2.2.202110030714 that situation happen:

- When I execute a sql file whith 4 query, then the result grid has four tab

But, If I want do refresh only the tab four, then I click in refresh action of tab four, but he go to select the tab one.

Then, I need do click again in the tab four do look de result of the refresh.

In short: After click refresh in the result of tab four, the focus is changed to the tab one.

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
issue is reproducible in case of script execution using alt+x
![q3goioIr8F](https://user-images.githubusercontent.com/31996417/145794287-c45e12a9-9f74-403d-b422-e3c18819a8c9.gif)

**Comment by uslss** [comment]
verified
