### ISSUE TITLE
App is crashed when trying to open some database from ODBC SQL Server connection

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#14137]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.2.3 EA

#### Connection specification:
- Database name and version SQL Server
- Driver name ODBC 64

#### Describe the problem you're observing:
App is crashed when trying to open some database from ODBC SQL Server connection
[hs_err_pid30596.log](https://github.com/dbeaver/dbeaver/files/7284310/hs_err_pid30596.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
