### ISSUE TITLE
Flatpak version doesn't update on Linux Mint

### ISSUE THREAD

**Issue by damiaojr91** [dbeaver/dbeaver#14131]
#### System information: 
- Linux Mint 20.2 Cinnamon
- DBeaver 21.1.4 - Flatpak
- No additional extensions

#### Describe the problem you're observing:
Dbeaver is a very useful tool, but neither me nor my co-workers have problems with its updates to the flatpak version... We were never able to update the flatpak version through the Linux Mint or Debian application manager...

**Comment by Matvey16** [comment]
@damiaojr91 Hello, can you clarify how are you updating? And what error stops your update?

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still actual - feel free to reopen it

**Comment by sebaschi** [comment]
The LM Software Manager has a setting to "show unverified Flatpaks", which for me was _off_ (i.e. DO NOT SHOW) by default (LM xia). On flathub you can see that the DBeaver Community Edition is marked as "unverified".
