### ISSUE TITLE
Lost connections after clearing password and unchecking encrypt configuration and clicking cancel in the dialog box asking for password

### ISSUE THREAD

**Issue by StephanoGeorge** [dbeaver/dbeaver#14133]
#### System information: 
- Operating system (distribution) and version
  Operating System: Arch Linux
  Kernel: Linux 5.14.7-arch1-1
  Architecture: x86-64
- DBeaver version
  Enterprise 21.1.0.202106090921
- Additional extensions
  None

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Lost connections after clearing password and unchecking encrypt configuration and clicking cancel in the dialog box asking for password

#### Steps to reproduce, if exist:

1. Add new connection
2. File -> Project security, set password and check encrypt configuration
3. Restart DBeaver
4. Click cancel in the dialog box asking for password
5. Open connections, it is empty
6. File -> Project security, clear password and uncheck encrypt configuration
7. Restart DBeaver
8. Open connections, it is empty

#### Include any warning/errors/backtraces from the logs

And, how to recover my connections data?

**Comment by LonwoLonwo** [comment]
Hello @StephanoGeorge 
And what database and driver do you use?

**Comment by Matvey16** [comment]
@LonwoLonwo It doesn't matter, the problem is that after going by the steps described in the issue, file `data-sources.json` gets deleted so all of the connections to any database disappear completely.

**Comment by serge-rider** [comment]
There was an error in project security preference page. If project node wasn't expanded before settings change then connection settings will be lost after encryption enable + password change.

Fixed.

**Comment by Matvey16** [comment]
Verified
