### ISSUE TITLE
Configurators i18n

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#14138]
We still have several metaobjects configurators which use hardcoded strings instead of E i18n.

**Comment by LonwoLonwo** [comment]
These objects localized to English and Russian:
- DB2 create schema dialog
- Exasol Main Connection Page (password, URL, etc.)
- Exasol create Role Dialog
- Mysql create a database dialog
- Oracle create schema dialog
- Oracle sessions - Show background/Show inactive actions with tooltips

**Comment by uslss** [comment]
verified
