### ISSUE TITLE
Error after launch on macOS: "The JVM shared library ... does not contain the JNI_CreateJavaVM symbol"

### ISSUE THREAD

**Issue by judaew** [dbeaver/dbeaver#14141]
#### System information: 
- Operating system (distribution) and version: MacOS BigSur 11.6 x86_64
- DBeaver version: [dbeaver-ce-21.2.2-macosx.cocoa.x86_66](https://github.com/dbeaver/dbeaver/releases/tag/21.2.2)

#### Describe the problem you're observing:

After starting the program, the following error appears:

```
The JVM shared library "/Users/judaew/Downloads/DBeaver.app/Contents/Eclipse/jre/Contents/Home/bin/../lib/server/libjvm.dylib"does not contain the JNI_CreateJavaVM symbol
```

<img width="372" alt="Screen Shot 2021-10-05 at 13 40 14" src="https://user-images.githubusercontent.com/41125715/136008026-822f5464-00a5-4db6-8145-bdb4469b46e3.png">

The previous version works without problems. If in this release inside `Contents/Info.plist` substitute the path to Java 17 (for example Eclipse Temurin), that program starts working. Lower Java versions do not work.

**Comment by flambchap** [comment]
Hello @judaew. Unfortunately, I cannot reproduce the issue. Could you please execute the following commands in the terminal and paste the results here? Thanks. 

~~~zsh
% cat /Users/judaew/Downloads/DBeaver.app/Contents/Eclipse/dbeaver.ini
% ls -1 /Users/nikita/Desktop/DBeaver.app/Contents/Eclipse/plugins | grep "cocoa"
~~~

**Comment by judaew** [comment]
@akilovich

```console
$ cat /Users/judaew/Downloads/DBeaver.app/Contents/Eclipse/dbeaver.ini
-startup
../Eclipse/plugins/org.eclipse.equinox.launcher_1.6.200.v20210416-2027.jar
--launcher.library
../Eclipse/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.200.v20210527-0259
-vm
../Eclipse/jre/Contents/Home/bin/java
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-XstartOnFirstThread
```

```console
$ ls -1 /Users/judaew/Downloads/DBeaver.app/Contents/Eclipse/plugins | grep "cocoa"
org.eclipse.e4.ui.workbench.renderers.swt.cocoa.nls_0.12.600.v20200416-0656.jar
org.eclipse.e4.ui.workbench.renderers.swt.cocoa_0.12.600.v20200416-0656.jar
org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.200.v20210527-0259
org.eclipse.swt.cocoa.macosx.x86_64_3.116.100.v20210602-2209.jar
org.eclipse.ui.cocoa.nls_1.2.400.v20191217-1850.jar
org.eclipse.ui.cocoa_1.2.400.v20191217-1850.jar
```

**Comment by judaew** [comment]
Do you have any ideas for solving this problem?

**Comment by judaew** [comment]
This issue is relevant for 21.2.3. Due to this issue, I cannot to update the [port in MacPorts](https://ports.macports.org/port/dbeaver-community/details/). This is what I get when run from terminal:

```console
$ /Users/judaew/Downloads/DBeaver.app/Contents/MacOS/dbeaver
2021-10-18 02:28:03.464 dbeaver[8609:296959] Error loading /Users/judaew/Downloads/DBeaver.app/Contents/Eclipse/jre/Contents/MacOS/libjli.dylib:  dlopen(/Users/judaew/Downloads/DBeaver.app/Contents/Eclipse/jre/Contents/MacOS/libjli.dylib, 265): no suitable image found.  Did find:
	/Users/judaew/Downloads/DBeaver.app/Contents/Eclipse/jre/Contents/MacOS/libjli.dylib: code signature invalid for '/Users/judaew/Downloads/DBeaver.app/Contents/Eclipse/jre/Contents/MacOS/libjli.dylib'
```

**Comment by judaew** [comment]
@akilovich If you try replace `libjli.dylib` from `openjdk11`, then `dbeaver` starts working correctly. It looks like `libjli.dylib` is broken.

**Comment by rishindramani** [comment]
> @akilovich If you try replace `libjli.dylib` from `openjdk11`, then `dbeaver` starts working correctly. It looks like `libjli.dylib` is broken.

Worked like a charm. Thanks for the quick fix!

**Comment by rishindramani** [comment]
> #### System information:
> * Operating system (distribution) and version: MacOS BigSur 11.6 x86_64
> * DBeaver version: [dbeaver-ce-21.2.2-macosx.cocoa.x86_66](https://github.com/dbeaver/dbeaver/releases/tag/21.2.2)
> 
> #### Describe the problem you're observing:
> After starting the program, the following error appears:
> 
> ```
> The JVM shared library "/Users/judaew/Downloads/DBeaver.app/Contents/Eclipse/jre/Contents/Home/bin/../lib/server/libjvm.dylib"does not contain the JNI_CreateJavaVM symbol
> ```
> 
> <img alt="Screen Shot 2021-10-05 at 13 40 14" width="372" src="https://user-images.githubusercontent.com/41125715/136008026-822f5464-00a5-4db6-8145-bdb4469b46e3.png">
> 
> The previous version works without problems. If in this release inside `Contents/Info.plist` substitute the path to Java 17 (for example Eclipse Temurin), that program starts working. Lower Java versions do not work.

Replace libjli.dylib with openjdk11. Works like a charm!

**Comment by flambchap** [comment]
I'm closing the ticket due to the lack of activity. Please feel free to reopen it if you think it needs to be resolved.
