### ISSUE TITLE
DB2 trigger Internal driver error

### ISSUE THREAD

**Issue by apdma** [dbeaver/dbeaver#14144]
#### System information: 
- Windows 10
- DBeaver version: 21.2.2.202110030714

#### Connection specification:
- DB2/LINUXX8664 11.1.4.6
- IBM DB2 JDBC Universal Driver Architecture 3.53.70
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No.

#### Describe the problem you're observing:
Can't expand "Triggers" on server.
I have a few copies with "same"(i hope) DB and there Triggers open fine.

#### Steps to reproduce, if exist:
1) Connect to database
2) Expand Schema
3) Try to expand Triggers

#### Include any warning/errors/backtraces from the logs
https://pastebin.com/qY2RJ3e7

[FOR THE SEARCH PURPOSE]
org.jkiss.dbeaver.DBException: Internal driver error
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getObject(JDBCObjectCache.java:83)...

**Comment by LonwoLonwo** [comment]
Hello @apdma 

As I can see, when reading triggers, the name of the triggers tables was lost somewhere.

Can you please show me the result of this statement 
`SELECT * FROM SYSCAT.TRIGGERS WHERE TRIGSCHEMA = <TRIGGER.SCHEMA.NAME> ORDER BY TRIGNAME WITH UR`

Especially the "TABNAME".

Trigger DLL example can be very helpful also.

**Comment by apdma** [comment]
Thanks, i get it after read your message.
I check the triggers with this statement
`SELECT * FROM SYSCAT.TRIGGERS WHERE TRIGSCHEMA = <SCHEMA.NAME> AND TABNAME NOT IN (SELECT TABNAME FROM syscat.TABLES WHERE TABSCHEMA =<SCHEMA.NAME>);`
And found 10 triggers what look on deleted tables. I drop triggers and all works.
