### ISSUE TITLE
Expanding data source navigator node while connection is in progress breaks Trino tree

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#14154]
#### System information: 
- Operating system (distribution) and version: Win 10
- DBeaver version: 21.2.2 UE devel
- Additional extensions: none

#### Connection specification:
- Database name and version: Trino 362
- Driver name Trino JDBC Driver 359
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Steps to reproduce, if exist:
1. Set simple mode for the Trino connection
2. Click the Connect button.
3. While a connection is being established, try to open the navigator node with Trino datasource.
4. Observe that the subtree is empty.
5. Set advanced mode.
6. Repeat steps 2 and 3.
7. Observe that the subtree does not contain catalogs nor schemas.

![folders](https://user-images.githubusercontent.com/26031301/136201988-39ef6cc4-833a-4639-adbb-7d6170fa6844.gif)

**Comment by ShadelessFox** [comment]
It works as expected since every subfolder has no children.

![image](https://user-images.githubusercontent.com/35821147/152988247-4e6837c9-f954-4fb8-822d-210414d1b1db.png)

**Comment by uslss** [comment]
verified
