### ISSUE TITLE
ERD: themization support

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#14155]
We need to patch GEF 3 library to support modern E4 themization.
Currently palette, tools, sashes, grid and some other diagram elements have hardly readable colors in dark theme.

**Comment by serge-rider** [comment]
+ Palette icon is hardcoded

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/136239392-acd63239-4bbd-4d74-a9ba-47796acc157b.png)

**Comment by Matvey16** [comment]
Verified
