### ISSUE TITLE
Unable to GRANT ALL permissions to a role which name should be quoted

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#14151]
#### System information: 
- Operating system (distribution) and version: unknown
- DBeaver version: unknown
- Additional extensions: unknown

#### Connection specification:
- Database name and version: PostgreSQL
- Driver name: unknown
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: unknown

#### Describe the problem you're observing:

We've received a message from our user. He claims that it's impossible to `GRANT ALL` permissions to some schema in PostgreSQL to a role which should be quoted in SQL statements. As an example, the user suggested roles "muddy-hills" and "Nikita Akilov".

**Comment by ShadelessFox** [comment]
Fixed by #13477
