### ISSUE TITLE
Network unavailable: 

### ISSUE THREAD

**Issue by shrivsksavit** [dbeaver/dbeaver#14162]
Getting below error i..e 
Network error

Reason:
Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

`Driver class 'org.postgresql.Driver' not found
  Error creating driver 'PostgreSQL' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.postgresql.Driver'
  Error creating driver 'PostgreSQL' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.postgresql.Driver'
    org.postgresql.Driver
    org.postgresql.Driver
`
Using Community: Version 21.2.2.202110030714

had tried to uninstall, install the driver several time but was still not able to resolved this issue

**Comment by uslss** [comment]
@shrivsksavit 
please provide more clear steps to reproduce an issue. video of the issue also will be very helpful

**Comment by Matvey16** [comment]
@shrivsksavit Are you getting network error when downloading driver?

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info.
