### ISSUE TITLE
Unable to use existing MySQL connection after update to 21.2.2.202110030714

### ISSUE THREAD

**Issue by tompinnacle** [dbeaver/dbeaver#14160]
#### System information: 
- Windows 10
- 21.2.2.202110030714
- None

#### Connection specification:
- MySQL 5.7.18
- Whatever the default is
- None

Since updating this morning I am unable to connect to any MySQL DB, the error is always the same...

Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

**Comment by tompinnacle** [comment]
The DBs are fine as I am able to connect with TablePlus - I just don't like it!

**Comment by uslss** [comment]
@tompinnacle is issue reproducible with newly created connections?
could you provide [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)?
unfortunately, cannot reproduce an issue for now

**Comment by tompinnacle** [comment]
@uslss 

I'm afraid at the moment I have had to revert to an earlier version as I needed it working ASAP.

I installed 21.2.0.202108310918 and that works fine

**Comment by uslss** [comment]
unfortunately, still cannot reproduce it. It is needed more info to reproduce and investigate the issue

**Comment by uslss** [comment]
is it still actual against the recent version?

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still actual - feel free to reopen it with additional info.
