### ISSUE TITLE
metadata editor flickers after activating the toolbar button 'Count the number of lines and other expensive functions'

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14161]
#### System information: 
- Win10, DBeaver 21.2.2

#### Describe the problem you're observing:
Some widgets in metadata editor are flicker after clicking the toolbar button 'Count the number of lines and other expensive functions'

https://user-images.githubusercontent.com/43252954/136336151-75478b6e-010d-42a9-a656-7019e634ab6b.mp4

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
