### ISSUE TITLE
copy table name from context menu

### ISSUE THREAD

**Issue by JeroenNienhuis** [dbeaver/dbeaver#14163]
In the database navigator is is possible to right click e.g. a column or table name and select "Copy" to select its name. The same can be done in the table data grid. In would be convenient if the table name can be selected from the context menu from the table tabsheet.
![afbeelding](https://user-images.githubusercontent.com/51078213/136404556-af2d7816-eb1a-4b04-acc6-fd83cf270952.png)

**Comment by Matvey16** [comment]
@JeroenNienhuis You can copy table name in the properties tab of the table

![image](https://user-images.githubusercontent.com/82543000/136792718-76cad331-5d7d-4939-9acc-d1c5a544725e.png)

**Comment by ShadelessFox** [comment]
Hello @JeroenNienhuis,

Thanks for feature request.

We can allow to copy FQN or simple name of entity via context menu of a tab.
