### ISSUE TITLE
dbeaver 21.2.2 no longer display the modified value after refresh properties of table

### ISSUE THREAD

**Issue by yyjdelete** [dbeaver/dbeaver#14168]
#### System information: 
- Operating system (distribution) and version: win10
- DBeaver version: 21.2.2 (***The same thing works well in 21.2.1***)
- Additional extensions

#### Connection specification:(It's not database related, I can also reproduce with other database)
- Database name and version: postgres 13
- Driver name: org.postgresql:postgresql:42.2.23
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Steps to reproduce, if exist:
1. Open properties of any db table;
2. Edit any field, and the field will be mark as orange and show the modified value;
3. Press `F5` to refresh the table, and click `OK`;
4. Edit any field as step 2 does again;
In step 4, I expected the field will be mark as orange and show the modified value as step 2 does, but it still display the old value(unless you enter edit mode) and no background color is set;

#### Include any warning/errors/backtraces from the logs

No error in logs

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by Matvey16** [comment]
Verified
