### ISSUE TITLE
Auto-save result sets to filesystem

### ISSUE THREAD

**Issue by anonimitoraf** [dbeaver/dbeaver#14179]
**Is your feature request related to a problem? Please describe.**
I sometimes have to run very long running queries (> 5 minutes) and then accidentally overwrite the results tab by running another query.

**Describe the solution you'd like**
It'd be great if there was an option to automatically save every result set to file. Disk space is cheap, even moreso in contrast to the execution time of long running queries.

**Describe alternatives you've considered**
I thought of making a plugin to do this, but I don't know enough about Eclipse's plugin API to know whether it's feasible.

**Comment by Matvey16** [comment]
That seems like a needlessly to complicated option. Perhaps we can add an option to always execute queries in new tab, so previous resultset can still be accessible.

**Comment by anonimitoraf** [comment]
Hi! Yes, that would be great too, if it's much easier to implement.

Question: Is there a hook of some sort, that allows running arbitrary code on a returned result set?

**Comment by Matvey16** [comment]
@anonimitoraf right now you can use <kbd>Ctrl + \\</kbd> or <kbd>Ctrl + Alt + Shift + X</kbd> to execute query or script in additional tab.

What do you mean by arbitrary code?

**Comment by anonimitoraf** [comment]
Oh, I didn't know that. Thanks!

And by arbitrary code I mean being able to run a function or something which gets the result set as the input/argument.
