### ISSUE TITLE
SQL filter column issue

### ISSUE THREAD

**Issue by budsz** [dbeaver/dbeaver#14178]
Hi,

Need someone else to elaborate about vertical align and font size which one too big (PATH).
I runned on OS `Debian 11.1 (Bullseye)` and `DBeaver` version `21.2.2.202110030714` 

For more clearly, I'll attach image
![Screenshot_2021-10-10_11-53-55](https://user-images.githubusercontent.com/4977494/136683010-d0332a83-b60c-4d0a-acc7-593282971ecd.png)

Thank you

**Comment by Matvey16** [comment]
@budsz Do you have some specific OS settings for text size or display scaling?

**Comment by budsz** [comment]
> @budsz Do you have some specific OS settings for text size or display scaling?

Yes, first I use GTK-3.0 environment setting:
`$ grep 'gtk-font-name' .config/gtk-3.0/settings.ini` 
`gtk-font-name = FreeSans 9`

This's not resolving my problem, after that I tried to switch to XFCE but problem still exist.
2 days ago this problem was seen when I ran `apt update` for updating DBeaver, even though before that there was no problem.

**Comment by Matvey16** [comment]
@budsz Can you try changing font to another and check if it is still aligned incorrectly?

**Comment by uslss** [comment]
there is no update on the issue. If it is still actual - feel free to reopen it with additional info
