### ISSUE TITLE
Close Result Tabs to the Right or Left.

### ISSUE THREAD

**Issue by gtdegamo** [dbeaver/dbeaver#14195]
**Is your feature request related to a problem? Please describe.**

Often I need to close result tabs that I don't need anymore.  If I have several open, this can be tedious.  

**Describe the solution you'd like**
Just as the sql script/console tab has a Close All Tabs to the Right or Left.  It would be nice if the Results tab had the same feature.

**Describe alternatives you've considered**

I close results tab by hand.

**Additional context**

None.  Keep up the great work!

**Comment by ShadelessFox** [comment]
Hello @gtdegamo,

Thanks for suggestion!

**Comment by ShadelessFox** [comment]
Implemented:

![java_wOzxgDDjgg](https://user-images.githubusercontent.com/35821147/145843156-9f3a0ace-ef32-45b1-930e-24c791d540a2.png)

**Comment by uslss** [comment]
verified
