### ISSUE TITLE
Postgresql function list omits "out type" parameters 

### ISSUE THREAD

**Issue by elring** [dbeaver/dbeaver#14196]
#### System information: 
OS: Linux Mint 20
DBeaver version: 21.2.2

#### Connection specification:
- Database: Postgresql 12

#### Describe the problem you're observing:
Functions in function list have only _in_ and _inout_ parameters (it omits the _out_ type).
Function list and function detail:
![obrazek](https://user-images.githubusercontent.com/24586123/136846360-7ed8747b-a3f1-4172-9ea3-868a81e13e52.png)

#### Steps to reproduce, if exist:
Step 1. Create test function:
```
CREATE OR REPLACE FUNCTION public.aaaa_test4(ainpar integer, OUT oout1 numeric, INOUT oout2 character varying)
 RETURNS record
 LANGUAGE plpgsql
AS $function$
begin	  
  return;
END
$function$
;
```
Step 2. Reload and see the function list.

**Comment by ShadelessFox** [comment]
Hello @elring,

That's feature. We display signature containing only input parameters for procedures in the navigator view.

Maybe we can display it like so: `aaaa_test4(int4, varchar) -> (numeric, varchar)` (let's pretend it has several `out` parameters)

**Comment by elring** [comment]
OK, my mistake then. It makes sense - this way it shows calling parameters.
But sometimes it can be useful to show all params. May be make it configurable? Something like "Out parameters display": None (default)/All in one group/Separated (what you suggest).
(I personally would like another possibility - optionally show parameters name, but that's for another issue ;-) ).

**Comment by ShadelessFox** [comment]
In the case of PostgreSQL, we should display the complete signature of the procedure.

Also, since we are skipping `out` parameters (and aren't specifying these modifiers at all), the generated DDL for `DROP` is invalid.

**Comment by ShadelessFox** [comment]
We specify only `in` parameters in DDL, and it's enough for PostgreSQL to understand us, so it's not a bug.

Now we display full type signature including parameter modes (and omit them if all parameters are `in` because they are implicit).

![image](https://user-images.githubusercontent.com/35821147/153004688-796fc350-732f-4d21-aebb-e177e3bf7951.png)

**Comment by uslss** [comment]
verified
