### ISSUE TITLE
Right Click Select Query

### ISSUE THREAD

**Issue by gtdegamo** [dbeaver/dbeaver#14192]
**Is your feature request related to a problem? Please describe.**

I use dbeaver alot for investigative work with queries.  This often means copying queries in my console tab and modifying them.

To copy the query, I have to select it first.  Many of the queries I use are longer than a page.  Scroll / selecting can be a pain at times.

**Describe the solution you'd like**

Currently dbeaver is smart enough to run a query and know the start and beginning of the query (I think it just searches for blank lines).  It would be nice if you use the same logic to select a query for copying.

**Describe alternatives you've considered**

Just selecting by hand and leaving plenty of blank lines between queries.

**Additional context**

None.  Keep up the great work.

**Comment by ShadelessFox** [comment]
Hello @gtdegamo,

That's a nice feature to have, thanks for suggestion.

We can implement it as an alternative to regular <kbd>Copy</kbd>, along with <kbd>Copy SQL as source code</kbd>.

**Comment by uslss** [comment]
verified
