### ISSUE TITLE
Can't open connection editor

### ISSUE THREAD

**Issue by Cyberbob64** [dbeaver/dbeaver#14205]
![grafik](https://user-images.githubusercontent.com/92361539/136955578-6c86e0e8-3866-4ea6-8fc0-77ccb9577dfc.png)
After Update to newest Beaver i get that message. If i use another tool to access the database via the same connection, it works

**Comment by LonwoLonwo** [comment]
Hello @Cyberbob64 
Can you please provide more clear steps to reproduce this issue?
And what driver do you use?

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info.
