### ISSUE TITLE
CSV Import

### ISSUE THREAD

**Issue by hvq-drojas** [dbeaver/dbeaver#14214]
I updated dbeaver to the last version but when I try to import data from a csv file (700k records) only import 1445 records. I used another computer with a lower version and a copy of csv file and import all records, so I return to the first computer and uninstalled last update to a previous version and this fixed the problem.

**Comment by LonwoLonwo** [comment]
Hello @hvq-drojas 

What database do you use?
Did you do import to the new table or to the existing one?
Maybe some special settings in CSV import settings? Screens from these pages will be very helpful.

**Comment by hvq-drojas** [comment]
Hello @LonwoLonwo 

I use Oracle 12c SE. 
I imported data to an existing table.
I compared CSV settings on both computers and was the same.
When import is done no show any error , when done only import 1445 records.
One month ago I worked in the same computer before update DBeaver (I updated today) with the same csv file and it worked fine but now after update I cant import all data.

**Comment by LonwoLonwo** [comment]
Thanks for the bug report. I can reproduce for SQLite table and import file with 20k columns (only 2,5k was imported).
(Can't reproduce in DBeaver 21.2.0)

**Comment by Matvey16** [comment]
Verified
