### ISSUE TITLE
Could not see Exasol users list while connected via not privileged user

### ISSUE THREAD

**Issue by allipatev** [dbeaver/dbeaver#14221]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.2.2.202110030714
- Additional extensions: no

#### Connection specification:
- Database name and version: Exasol 7.0
- Driver name: EXASolution JDBC Driver 7.1.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: no

#### Describe the problem you're observing:
When user that is not very privileged tries to list users (Exasol Connection -> Users) it gets error

`SQL Error [42000]: object KERBEROS_PRINCIPAL not found [line 4, column 2] (Session: 1713499306320134145)`

From audit it looks like for a user with many privileges (SELECT ANY DICTIONARY?) DBeaver queries EXA_DBA_USERS, while it queries EXA_USER_USERS when the user is lacking required privileges. The problem is that EXA_USER_USERS is lacking some columns, KERBEROS_PRINCIPAL for example.

Probably, the SQL statement to get users in non-privileged mode needs to be modified.

**Comment by tati-kru** [comment]
Thank you for the report.

**Comment by allipatev** [comment]
Hi @ShadelessFox @tati-kru @serge-rider @uslss 
Do you know how is change log shown in DBeaver application (community edition) is generated?
Say, this particular issue is seemingly included into this week's release.
If one moves this issue to Milestone 22.2.3 right now, will it be visible in DBeaver UI as a result of Check for Update?

**Comment by allipatev** [comment]
Or it is just a static text in release notes for https://github.com/dbeaver/dbeaver/releases/tag/22.2.3?
