### ISSUE TITLE
Import from CSV not getting all rows

### ISSUE THREAD

**Issue by kresaux** [dbeaver/dbeaver#14227]
System information:
- Operating system (distribution) and version: Windows 10 Enterprise 21H1
- DBeaver version: 21.2.2

Connection specification:
- Database name and version: Oracle DWH
- Driver name (class): oracle.jdbc.driver.OracleDriver

Describe the problem you're observing:
- When importing CSV to my user schema on tablespace 'USERS', the number of rows imported is smaller than in source CSV

Steps to reproduce, if exist:
- Importing any CSV/TXT with more than cca 10.000 rows using Import data wizard

Notes:
- There is no error message, import completes with no issues
- The number of imported rows seems random, but always the same when re-trying
- Worked normally when trying previously on DBeaver version 21.2.0, didn't try downgrading yet
- Works normally when importing a smaller number of rows, tried with 3.000
- Tablespace is not an issue, all rows get imported by using a different client like Squirrel

**Comment by uslss** [comment]
thanks for the report.
Fixed in the scope of #14214.
Fix will be available in 21.2.3

**Comment by scchess** [comment]
I'm also getting the same error. Please add a software assert to prevent the bug.

**Comment by dizmaRider** [comment]
I have Version 22.3.3.202301211053 and I am having the same problem.

**Comment by nelsonym** [comment]
I have similar problem which was not happening before. My version is Version 22.3.5.202302171528. I have 22,003 rows of csv file with 30 columns. It is always getting this error: SQL Error [1406] [22001]: Data truncation: Data too long for column 'sy2022_schname' at row xx
  Data truncation: Data too long for column 'sy2022_schname' at row xx

I tried changing the number of batch rows to insert and commit but I'm always having the same problem. If I skip the issue it only imports 2,500 rows and then repeat it repeats the previously 2,500 rows 3x.

not all columns would have values, some are blanks, some are numeric, some are date and some are strings
