### ISSUE TITLE
Return key deletes subsequent line (CE 2.1.2.22)

### ISSUE THREAD

**Issue by simonhaven** [dbeaver/dbeaver#14230]
#### System information: 
OS: MacOS Big Sur 11.6
DBeaver version: CE 21.2.22
Additional extensions: none

#### Connection specification:
Postgresql 11.9 
Using SSH tunnel to AWS instance

#### Describe the problem you're observing:
In SQL Editor pane, hitting the Return key deletes the subsequent line instead of moving it down one 
This behaviour didn't exist in CE 21.2.20

#### Steps to reproduce, if exist:
Write a query in the SQL Editor
Position the cursor somewhere with a non-blank following line
Hit Return key

#### Include any warning/errors/backtraces from the logs
Nothing significant in error or debug logs

**Comment by ShadelessFox** [comment]
Hello @simonhaven,

Thanks for reaching out.

Actually, the same issue was already described in #13966, so I'll have to close this ticket as a duplicate.
