### ISSUE TITLE
CSV import to PostgreSQL in 21.2.2 CE does not import all rows and returns no errors

### ISSUE THREAD

**Issue by DCTech2k** [dbeaver/dbeaver#14237]
#### System information: 
- macOS 11.6 (x86_64)
- DBeaver CE 21.2.2

#### Connection specification:
- PostgreSQL 12.7
- JDBC 42.2.5
- No tunnel

#### Describe the problem you're observing:

In CE 21.2.2 when trying to import from CSV in to existing table while mapping to existing columns the import only loads 37406 rows from CSV no matter how many columns are marked to be skipped. I inspected the source file at the last row it imports and there is no unusual data (or control characters) in the file being imported. Interesting thing is that when I revert to CE 21.2.1 it imports ALL rows just fine from the same file and in to the same table/columns. I've tried closing and reopening DBeaver while retrying the below steps and had same results each time on 21.2.2. Installed 21.2.1 over 21.2.2 and problem was resolved, but then installed 21.2.2 again and problem returned. Seams like a nasty silent bug in 21.2.2.

#### Steps to reproduce, if exist:
1) trunk destination table and commit
2) attempt to import a CSV file with 40k+ rows, tried skipping all columns except for the first which is numeric (5 characters) with the same result
3) select count(*) from table 

#### Include any warning/errors/backtraces from the logs
No warning or errors are returned. Data transfer wizard simply closes like if it finished importing all data.

**Comment by LonwoLonwo** [comment]
Hello @DCTech2k 
Thanks for the bug report.
This problem was fixed in the scope of #14214.
Fix will be available in the 21.2.3 release.

**Comment by JGFMK** [comment]
I tracked it down as an embedded double quote issue in data.
https://stackoverflow.com/questions/17808511/properly-escape-a-double-quote-in-csv
All double quotes in data have to be doubled " -> ""
There's some other edge cases 
If it starts or ends you triple quote
To embed a single double quote as data in a column use four consecutive double quotes.
I had lots of cases of this. In my case it was easier to repeatedly use psql \copy command until i got rid of all the errors.
That way I didn't have to keep dropping the table
The same rule would also apply for single quotes as it does for double too. Doubling up quotes.
