### ISSUE TITLE
CSV: Wrong mapping for varchar columns during export to DB

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14243]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.2.3

#### Connection specification:
- Database name and version CSV

#### Describe the problem you're observing:
Export from table opened with the CSV plugin to a database always sets legth of varchar columns to 20.

#### Steps to reproduce, if exist:
1. Open a CSV file with string column that has values longer than 20
2. Start export to any database and to a new table

**Expected:** Data is trasfered
**Actual:** Data can't be transfered because the table is created with `varchar(20)` column

![GmehRfax80](https://user-images.githubusercontent.com/82543000/137300104-b6e3af6d-82d6-4978-873c-342fb1af04f9.gif)

**Comment by LonwoLonwo** [comment]
Can't reproduce against DBeaver 23.2.0

![2023-09-12 11_54_44-Window](https://github.com/dbeaver/dbeaver/assets/45152336/8da5317e-cadc-48cc-8036-5baeebb51f43)

![2023-09-12 11_55_05-Window](https://github.com/dbeaver/dbeaver/assets/45152336/6a4f2091-dd0a-47d2-84fd-bd5f63e85cfd)
