### ISSUE TITLE
The compare / migrate simple structure compare tool does not seem to compare datatypes

### ISSUE THREAD

**Issue by tabdoelhafiezkhan** [dbeaver/dbeaver#14248]
When I compare a table in two databases and for example the structure is the same except for one column being datatype date and the same column in the other database is of datatype timestamp. The compare tool does not see this

Please could you have the compare tool also compare differences in datatypes 

Regards,
Tim

**Comment by uslss** [comment]
@tabdoelhafiezkhan cannot reproduce. What database and dbeaver version do you use?
![image](https://user-images.githubusercontent.com/31996417/137450370-728b5060-ddda-4503-ab27-453d7b2fc8f2.png)

**Comment by tabdoelhafiezkhan** [comment]
Hello,

We use dbeaver Version 21.2.2.202110030714
And I compare two tables, one in postgres 11 and another in postgresql 12.
Same column name but different datetypes: *date* and the other *timestamp*

See attached screenrecording of the compare.

These are the table definitions:


:::  psql -e -h 127.0.0.1 -p5436 -U postgres

tim=# \d tab1
              Table "public.tab1"
 Column | Type | Collation | Nullable | Default
--------+------+-----------+----------+---------
 col1   | date |           |          |


:::  psql -e -h 127.0.0.1 -p5434 -U postgres

tim=# \d tab1
                          Table "public.tab1"
 Column |            Type             | Collation | Nullable | Default
--------+-----------------------------+-----------+----------+---------
 col1   | timestamp without time zone |           |          |



Op vr 15 okt. 2021 om 09:39 schreef Dziyana ***@***.***>:

**Comment by uslss** [comment]
@tabdoelhafiezkhan unfortunately, still cannot reproduce.
![image](https://user-images.githubusercontent.com/31996417/141750732-f33ee17b-3d2b-4ef9-aa2a-f405102be88a.png)
could you provide tables ddl to reproduce the issue?

**Comment by tabdoelhafiezkhan** [comment]
Hello Dziyana,

See attached screencapture of the compare steps I executed.
As you can see the compare report does not show any differences.

These are the tables created:

-- In PostgreSQL 12

CREATE TABLE public.tab1 (
col1 timestamp NULL
);

-- In PostgreSQL 11

CREATE TABLE public.tab1 (
col1 date NULL
);

This is the latest DBeaver Version 21.2.5.202111141807

[image: image.png]

regards,
Tim



Op ma 15 nov. 2021 om 09:49 schreef Dziyana ***@***.***>:

**Comment by uslss** [comment]
Probably, you've got Compare only structure option checked
![image](https://user-images.githubusercontent.com/31996417/144838765-940dec74-dbc7-4b8c-85c1-baab1a737ad3.png)
in this case difference between datatypes isn't shown
![image](https://user-images.githubusercontent.com/31996417/144838852-0ec1a5f4-a68a-42d6-9ef7-b94e7a831030.png)

In case mentioned option is unchecked the result looks like:
![image](https://user-images.githubusercontent.com/31996417/144838970-6541bdde-72c8-4539-96ac-532f6ac7421a.png)

**Comment by tabdoelhafiezkhan** [comment]
Hello,

Yes you are right. Thanks a lot for the help.

regards,
Tim


Op ma 6 dec. 2021 om 12:33 schreef Dziyana ***@***.***>:
