### ISSUE TITLE
CSV: Data is read only, but data editor allows editing which will lead to an error

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14240]
CSV plugin doesn't allow data editing, but UI still allows it. It would be better to make data editor for CSV plugin read-only to avoid confusing a user.

**Comment by LonwoLonwo** [comment]
Fixed in scope of this ticket: https://github.com/dbeaver/pro/issues/750

**Comment by Matvey16** [comment]
Verified
