### ISSUE TITLE
Postgresql: paste table in Indexes view error

### ISSUE THREAD

**Issue by GiantCrocodile** [dbeaver/dbeaver#1425]
1. press copy in tables view
2. press paste in indexes view

You get an error about a problem in creating object in PostgreIndexManager and wrong container type PostgreSchema.
If you try to do pasting this into table view, views view, materialized views view, etc. it doesn't error but opens create dialogue or just informs about unsupported clipboard data.

**Comment by serge-rider** [comment]
This is expected behavior. You can't copy/paste table into index.
At the moment real table copy was implemented only for MySQL. PostgreSQL is next.

**Comment by GiantCrocodile** [comment]
This is obviously true but I would expect that you get an error like on ither cases about unsupported clipboard data? To me it looked like something else throw an exception because it was tried to be pasted with wrong data.

**Comment by serge-rider** [comment]
Agreed. This is a little confusing.

**Comment by uslss** [comment]
Cannot reproduce on 6.0.2
