### ISSUE TITLE
Column name is not displayed

### ISSUE THREAD

**Issue by ly351204778** [dbeaver/dbeaver#14257]
当列名以‘“set_”开头时，字段不显示出来

When the column name starts with 'set_', the field is not displayed

**Comment by ly351204778** [comment]
当列名以‘“set_”开头时，字段不显示出来

When the column name starts with 'set_', the field is not displayed

**Comment by uslss** [comment]
@ly351204778 please provide dbeaver version, database you use and steps to reproduce an issue

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info.
