### ISSUE TITLE
db-metadata search in 'like' mode behaves like 'like'+'startswith' mode

### ISSUE THREAD

**Issue by kai-morich** [dbeaver/dbeaver#14265]
When doing a 'like' db-metada query, the result contains more data than expected. Looks as if it internally appends a % and so searches not only objects that exactly match the pattern, but also object that start with the given pattern.

doesn't look like a database specific issues, as I could reproduce with different databases (e.g. sqlite, mysql, hana).
I used recent dbeaver 21.2.2

**Comment by Matvey16** [comment]
@kai-morich Thank you for the report

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 22.0.0

**Comment by Matvey16** [comment]
Verified
