### ISSUE TITLE
IBM i DB2 - "Show column description in header" not working on default *LIBL schema

### ISSUE THREAD

**Issue by dkornacki-cutco** [dbeaver/dbeaver#14269]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro 21H1
- DBeaver version: 21.2.2

#### Connection specification:
- Database name and version: DB2 for IBM i release 7.3
- Driver name: DB2 iSeries/AS 400
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
"Show column description in header" in Data Editor -> Appearance does not work if schema is set to default on a library list (*LIBL) schema.

By default I mean using `set schema default`.

**Comment by LonwoLonwo** [comment]
Hello @dkornacki-cutco 
And how about columns descriptions in Table Properties View? Are they working there?

![2021-10-20 16_16_43-DBeaver Ultimate 21 2 3 - people](https://user-images.githubusercontent.com/45152336/138100424-c389ff6d-4096-4532-8189-dad88a28bc85.png)

**Comment by dkornacki-cutco** [comment]
Yes, they show there. But by using this method, I select the table from a single schema/library, not a library list.

Similarly, if I use `set schema a_single_schema` in the editor and run a select statement, descriptions are shown correctly in the result view.

If I do `set schema default` with Database/Schema under Connection settings set to `*LIBL, lib1, lib2,...`, descriptions are not shown.

**Comment by xantari** [comment]
@dkornacki-cutco Try use the following driver values for IBMi:

metadata source: 0
translate binary: true
date format: iso
time format: iso
extended metadata: false

And these UI settings:
![image](https://user-images.githubusercontent.com/6610039/154818748-4ff97396-8436-4fe4-8238-f9fcb9afde74.png)

![image](https://user-images.githubusercontent.com/6610039/154818746-66481802-5713-4bd6-b890-200a3f0dcec7.png)

Does that fix your issue?

**Comment by uslss** [comment]
There has been no update on the issue for a long time.  If it is still reproducible - feel free to reopen it
