### ISSUE TITLE
Support for DynamoDB

### ISSUE THREAD

**Issue by shivan** [dbeaver/dbeaver#1426]
Currently the NoSQL-DB "DynamoDB" is not supported.

Support would be nice.

See here:
https://aws.amazon.com/de/dynamodb/

and an offline version:
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html

**Comment by serge-rider** [comment]
As there is no JDBC driver we'll need to develop brand new extension.

**Comment by MohamedAmineB** [comment]
Until it's done, you could use this one https://www.cdata.com/kb/tech/dynamodb-jdbc-dbvr.rst (trial for 30 days, no idea of what happens after)

**Comment by aljones15** [comment]
just wanted to say this looks like a good idea. having to download that not from driver right now.

**Comment by thirstyfish** [comment]
This would be an awesome feature!

**Comment by jamesscaur** [comment]
Bump!

**Comment by beginrescueend** [comment]
+1

**Comment by SZubarev** [comment]
+1

**Comment by serge-rider** [comment]
Most likely we'll add Dynamo DB support after 6.1.

We have several other candidates like Google BigTable or Couchbase. Need to decide what do do first..

**Comment by serge-rider** [comment]
Beta version of DynamoDB support is in Early Access (https://dbeaver.com/files/ea)

**Comment by uslss** [comment]
verified.
Read-only access is available at the moment.

**Comment by dvdtth** [comment]
Will dynamodb be supported in the community version as well?

**Comment by tati-kru** [comment]
@dvdtth most likely it won't be included in CE. Besides other reasons it requires Amazon SDK that is too huge.

**Comment by dinmukhamed09** [comment]
Could you take a look again to support AWS DynamoDB in DbeaverCE, please

**Comment by tati-kru** [comment]
@dinmukhamed09 I'm afraid there are no such plans at this moment. DBeaver connects to DynamoDB through a special extension, not a JDBC driver. This extension can work with various specific DynamoDB objects that are not available for JDBC. This is not an open-source plugin. I don't think that it will become open-source in the near future.

**Comment by dinmukhamed09** [comment]
Hi, 

As I understand that feature supports in EE plan. 

What the difference between DbeaverEE and DbeaverCE?

**Comment by tati-kru** [comment]
@dinmukhamed09 you can find the whole list of differences here: https://dbeaver.com/edition/.

**Comment by mims92** [comment]
I know that is doesn't provide a reliable solution for DBeaver but: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/workbench.settingup.html

**Comment by pabloiarriola** [comment]
@tati-kru  any plans to support it in the lite edition? 
According to this documentation it does not say anything about lite, just enterprise,ultimate and team 

https://dbeaver.com/docs/dbeaver/AWS-DynamoDB/
