### ISSUE TITLE
Command line cannot be filled with roles

### ISSUE THREAD

**Issue by GG668** [dbeaver/dbeaver#14261]
### Discussed in https://github.com/dbeaver/dbeaver/discussions/14218

<div type='discussions-op-text'>

<sup>Originally posted by **GG668** October 13, 2021</sup>
I want to fill the oracle roles via command line, what should I do</div>

**Comment by Skydiveroid** [comment]
Thank you for the idea.

**Comment by chamcyl** [comment]
add  `prop.internal_logon=xxxrole`  to connection parameters
