### ISSUE TITLE
Changing connection navigation settings affects table properties

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#14276]
When I set "Simple" or "Custom"+Hide folders in "Connection configuration/Common/Navigation view" I found that some table properties (Constraints, Foreign keys and others) disappear too. In my case it is not necessary.
We need one more option for hiding table properties.

**Comment by uslss** [comment]
what database do you use?
table properties are visible for me, in case Custom - Hide folders view is chosen.
![image](https://user-images.githubusercontent.com/31996417/138054377-6b3b95a6-4bfa-4a44-b342-45bf79110d8e.png)

**Comment by offstate** [comment]
MariaDB
![image](https://user-images.githubusercontent.com/16996529/138071828-992fce09-c082-48e3-9acc-fa2403302ed0.png)
This is like Simple mode:
![image](https://user-images.githubusercontent.com/16996529/138072992-deda96e5-18ff-42d9-a88a-d19e175694bc.png)
With 'Hide folders' only doesn't work at all:
![image](https://user-images.githubusercontent.com/16996529/138073395-cd586434-22e5-407d-a81f-f2d952482f63.png)

PostgreSQL
Advanced mode:
![image](https://user-images.githubusercontent.com/16996529/138073943-879c9ab4-a743-41bb-b812-2c76a7f123b2.png)

Simple
![image](https://user-images.githubusercontent.com/16996529/138074169-ee61dc5e-fc96-4a72-ae49-fc22948dcaad.png)

Hide filders
![image](https://user-images.githubusercontent.com/16996529/138074537-ecaf99dd-af31-4bfe-aab7-39f2a50132a7.png)
In this last mode all DB objects are in one long list in navigation tree that is not good


I made tabs for most used connections and set them Simple mode. Also I used object filter so I could made several tabs for one connection and different schemas inside each for the needs of a specific project. But I still need  the full functionality of the table properties

**Comment by offstate** [comment]
I also found that some menu items become inactive/invisible in Simple mode (Drop, Rename a table..)
I switched to Simple mode to get faster access to DB objects in the Navigation tree and in my case limited functionality is not required.
Could you add more options in the Navigator settings to divide functional and interface limitations?

**Comment by uslss** [comment]
If you have any proposals, please, create a separate ticket with your vision of how Simple view should work and look like.
