### ISSUE TITLE
Autocomplete functions with blank brackets or without parameters 

### ISSUE THREAD

**Issue by gaginsgagins** [dbeaver/dbeaver#14275]
Now Dbeaver autocomplete functions like this schema.myfunc(int4,int4)(:$1,:$2).
It would be nice if the autocomplete looked like schema.myfunc() or schema.myfunc(int4,int4)

**Comment by LonwoLonwo** [comment]
Hello @gaginsgagins 
What database do you use?

And query examples will be also helpful.

**Comment by gaginsgagins** [comment]
postgesql. This is not query depend. This is result autocomplete behaviour. when i type "myfunc" and press enter on autocomlete hint, Dbeaver type schema.myfunc(int4,int4)(:$1,:$2). How to change this behaviour 
![step1](https://user-images.githubusercontent.com/25243076/138107012-7a6eaaea-fc79-4ea2-85c9-46cf79ec76da.png)
![step2](https://user-images.githubusercontent.com/25243076/138107010-f629c3b5-fdec-42e6-9214-0aeb227c8f65.png)

**Comment by LonwoLonwo** [comment]
And what DBeaver version do you use?

**Comment by gaginsgagins** [comment]
> And what DBeaver version do you use?

latest - 21.2.3.202110151816 DBeaver - CE

**Comment by LonwoLonwo** [comment]
Sorry, can't reproduce for now.

![T6QVKRUm4S](https://user-images.githubusercontent.com/45152336/138272800-3cdaed41-8420-4023-9c99-deaaca95a1a0.gif)

How about this setting

![2021-10-21 15_00_34-DBeaver Ultimate 21 2 3 - _postgres_ Script-8](https://user-images.githubusercontent.com/45152336/138273030-64882e76-e3e5-4247-b1ff-e8d60613633f.png)

Is it enabled in your preferences?

Also, maybe function DDL can help me.
Video or screenshots of the problem can be very helpful also.

**Comment by gaginsgagins** [comment]
![record](https://user-images.githubusercontent.com/25243076/138275139-c44553a5-3d94-4d4c-8671-b947d24073ab.gif)
why DBeaver append (:$1) ?

show stored procedures in column list is enabled.

`CREATE OR REPLACE FUNCTION "accounts"."account_is_active"(int4)
  RETURNS "pg_catalog"."bool" AS $BODY$
begin
  return (select status not in ('removed', 'offline') from db.users where account_id = $1);
end
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100`

**Comment by LonwoLonwo** [comment]
Ok, thanks. Now I caught it.

For me, it works only for not fully qualified function names from another schema. 
It works fine with [not] fully qualified function name from current schema.

**Comment by uslss** [comment]
verified
