### ISSUE TITLE
how the dbeaver to load the image

### ISSUE THREAD

**Issue by janiu-001** [dbeaver/dbeaver#14271]
there are two kind of images for dbeaver, xxx.png and xxx@2x.png, in which case dbeaver use xxx.png, and in which case dbeaver use xxx@2x.png

**Comment by janiu-001** [comment]
Here i means the icons,. i find that the icon is different when i connected to different screen

**Comment by ShadelessFox** [comment]
Hello @janiu-001,

The `xxx.png` icons are used for FHD monitors and below.
The `xxx@2x.png` icons are used from HiDPI monitors and above.

In code we explicitly don't specify which version of icon to load, it's determined automatically.

**Comment by janiu-001** [comment]
@ShadelessFox is it an eclipse mechanism ? anyway we have a method to determine the icon

**Comment by ShadelessFox** [comment]
It is indeed an Eclipse mechanism. See `org.eclipse.jface.resource.ImageDescriptor#createFromURL`.
