### ISSUE TITLE
Local variable cannot be set after semicolon

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#14274]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.2.3.202110141045

#### Steps to reproduce, if exist:
1. Write a query with semicolon at the end
2. Write @set variable (e.g. @set var=actor;) and execute it

**Expected**: the query with the variable is executed.
**Actual result**: no visible changes

https://user-images.githubusercontent.com/51405061/137589876-14ca0266-6ea9-4be8-a128-cb684f5f0b38.mp4

**Comment by Matvey16** [comment]
Can't be reproduce anymore
