### ISSUE TITLE
Accessing PostgreSQL on wsl2 from DBeaver on Windows is refused

### ISSUE THREAD

**Issue by Hiroki111** [dbeaver/dbeaver#14289]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.2.3
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 13.4
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I'm trying to access Postgres from DBeaver. 

As the title suggests:

- Postgres is installed into wsl2 (Ubuntu 20)
- DBeaver is installed into Windows 10

![Capture](https://user-images.githubusercontent.com/9676341/137853762-d09c3800-f5e3-4297-93c5-4d8be5200f9f.PNG)

I don't know what this error message means: "Connection refused: connect".
It says "connect" while the connection was refused.

If I check the details:
```
Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
  Connection refused: connect
```

The hostname should be fine, because according to [wsl2's documentation](https://docs.microsoft.com/en-us/windows/wsl/networking#accessing-linux-networking-apps-from-windows-localhost), this is supposed to be `localhost`.
Regarding the TCP/IP connection setting on wsl2 (Ubuntu), I ran the following command.
```
sudo ufw allow 5432/tcp
```
... still the error persists.

Does anyone see what went wrong?

**Comment by Hiroki111** [comment]
Solved.
I just needed to `sudo service postgresql restart`...

**Comment by AnweshGangula** [comment]
reference to Stack-Overflow for this issue:
https://stackoverflow.com/q/69625823/6908282
