### ISSUE TITLE
Do not remove installed plugins after upgrade

### ISSUE THREAD

**Issue by krilim** [dbeaver/dbeaver#14280]
Hello, I use SSHJ extension and every time I update the app I need to reinstall that plugin.

Is it possible to keep installed plugins after an upgrade so we do not need to reinstall them afterwards ?

Thanks.

**Comment by ShadelessFox** [comment]
Hello @krilim,

Please provide information about your OS and installation method you're using (e.g. exe installer, zip archive, etc.)

**Comment by krilim** [comment]
The computer is **Mac Mini i7**, **MacOS 11.6**

The method is download new package from web and replace existing one in Applications.

**Comment by ShadelessFox** [comment]
By replacing application package, you erase everything, including installed plugins.

Probably we should backup previously installed plugins.

**Comment by krilim** [comment]
I do not know any other way 😅

**Comment by uslss** [comment]
duplicates #5317
