### ISSUE TITLE
Database name not proposed by autocompletion

### ISSUE THREAD

**Issue by Jrmy003** [dbeaver/dbeaver#14285]
Hello DBeaver teams,

I got trouble with autocompletion, I juste upgraded from 21.0.1 to 21.2.3.

Before I was able to specify database name prefix with autocompletion, in 3-4 characters :
![image](https://user-images.githubusercontent.com/3603542/137758072-03966dd5-970b-4072-871c-17b0257973ef.png)

Since 21.2.3 I have to write it manually, autocompletion seems to not complete words using database name :/

**Comment by uslss** [comment]
@Jrmy003 what database do you use?

**Comment by Jrmy003** [comment]
@uslss I'm using SqlServer

**Comment by Jrmy003** [comment]
Maybe the problem occurs when database name begins with numbers?

**Comment by Jrmy003** [comment]
![image](https://user-images.githubusercontent.com/3603542/141131002-f614ef1a-9cb7-4297-bc99-ae4c6d263ab3.png)

**Comment by Jrmy003** [comment]
![image](https://user-images.githubusercontent.com/3603542/141131110-3c0b2fc0-0984-443f-88e8-3af6cdd2f97e.png)

**Comment by Jrmy003** [comment]
And it finally works with 6 caracters, while 3 was enough in 21.0.1.

The last screenshots was made with 21.2.4.

The problem may comes from numbers or special characters (- or _)

![image](https://user-images.githubusercontent.com/3603542/141131263-c74ed021-45fe-4af8-a932-d7e7a7694763.png)

**Comment by uslss** [comment]
thanks for the report and clarification
