### ISSUE TITLE
DBeaver doesn't work with the param "-reuseWorkspace"

### ISSUE THREAD

**Issue by AdrianoBortoloto** [dbeaver/dbeaver#14284]
#### System information: 
Windows 10
DBeaver 21.2.3

#### Issue:
DBeaver doesn't work with the param "-reuseWorkspace".
When I removed that parameter, Dbeaver open sucessfully.

There is a fixed issue (https://github.com/dbeaver/dbeaver/issues/12507) about it already reported in 21.0.5 and fixed in 21.1.0.
It seems that the issue has returned.

#### Steps to reproduce:
1. Create a windows shortcut with the command: "C:\path\to\install\dbeaver.exe -reuseWorkspace"
DBeaver open the starter dialog and close it in a few seconds.
2. Remove the param reuseWorkspace from the shortcut: "C:\path\to\install\dbeaver.exe"
DBeaver open normally.

**Comment by ShadelessFox** [comment]
Hello @AdrianoBortoloto,

I cannot reproduce your issue.

Please attach [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files).

**Comment by ghost** [comment]
I've noticed the same issue for -closeTabs and -disconnectAll. Maybe it's a more general thing?

I'm using the portable windows 64-bit version. I've gone back to 21.2.2

**Comment by ShadelessFox** [comment]
Hello @johnriksten,

Help us fix this issue instead of ignoring it.

Please attach [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files).

**Comment by ShadelessFox** [comment]
DBeaver will not launch a new instance if it can't find an existing one. This behavior was changed in #14085.

**Comment by uslss** [comment]
verified
