### ISSUE TITLE
influxdb can't add tz('Asia/Shanghai') at the end of the query

### ISSUE THREAD

**Issue by flykarry** [dbeaver/dbeaver#14288]
#### System information: 
- Operating system (distribution) and version
- win10
- DBeaver version
- 21.2.0.202109061154
- Additional extensions

#### Connection specification:
- Database name and version
- infludb 1.7
- Driver name
- InfluxDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
- no

#### Describe the problem you're observing:
influxdb can't add tz('Asia/Shanghai') at the end of the query

SELECT * FROM "basedata" WHERE paramId = '7a_84625' tz('Asia/Shanghai')

like this can't not be executed

**Comment by Matvey16** [comment]
@flykarry Thank you for the report. Until we fix it, as a temporary workaround you need to include limit clause before tz()

Dbeaver adds limit clause at the end of the query if it is not included manually. But influxDB syntax demands that limit clause should go before tz().

![VyNBoOIDJt](https://user-images.githubusercontent.com/82543000/138080582-ea4c1f3d-0174-449f-853a-52c4648e0dbf.gif)

**Comment by flykarry** [comment]
ok，wish you fix it as soon as possible

**Comment by Matvey16** [comment]
Verified
