### ISSUE TITLE
Write a wiki page about connecting to Oracle via OCI driver

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#14292]
It's quite a tricky process. We also need to somehow rearrange our major topics so this page can fit well.

**Comment by flambchap** [comment]
https://github.com/dbeaver/dbeaver/wiki/Connect-to-Oracle-Database-using-JDBC-OCI-driver

**Comment by uslss** [comment]
https://github.com/dbeaver/dbeaver/wiki/How-to-connect-to-Oracle-Database-using-JDBC-OCI-driver
