### ISSUE TITLE
redis edit the json value and save the data value will be mutil Line

### ISSUE THREAD

**Issue by flykarry** [dbeaver/dbeaver#14298]
#### System information: 
- Operating system (distribution) and version
- win10
- DBeaver version
- 21.2.0.202109061154
- Additional extensions

#### Connection specification:
- Database name and version
- 5.0.4
- Driver name
- redis
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
- no

#### Describe the problem you're observing:
redis edit the json value and save the data value will be mutil Line

**Comment by uslss** [comment]
@flykarry could you provide steps to reproduce the issue? video with the issue also will be very helpful for its investigation

**Comment by flykarry** [comment]
![动画](https://user-images.githubusercontent.com/14309127/138374622-31526482-db71-4684-9a68-74d207fe2911.gif)
@uslss check it out

**Comment by uslss** [comment]
thanks for the report and clarification

sorry for the late response

**Comment by Destrolaric** [comment]
@flykarry Hi, are this JSON is from JSON.SET command?

**Comment by uslss** [comment]
verified
