### ISSUE TITLE
it's can't show any key if the redis just use one db

### ISSUE THREAD

**Issue by flykarry** [dbeaver/dbeaver#14299]
#### System information: 
- Operating system (distribution) and version
- win10
- DBeaver version
- 21.2.0.202109061154
- Additional extensions

#### Connection specification:
- Database name and version
- 5.0.4
- Driver name
- redis
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
- no

#### Describe the problem you're observing:
it's can't show any key if the redis just use one db
![image](https://user-images.githubusercontent.com/14309127/138021309-4d3c81c4-d070-477e-b206-db4e699e2d1c.png)

**Comment by uslss** [comment]
@flykarry did you try to refresh the database? is there some value in db navigator search field(pic below)?
![image](https://user-images.githubusercontent.com/31996417/138052762-e5a8fd66-f59f-4dc1-ac3a-b68acfd5c694.png)

**Comment by flykarry** [comment]
> @flykarry did you try to refresh the database? is there some value in db navigator search field(pic below)? ![image](https://user-images.githubusercontent.com/31996417/138052762-e5a8fd66-f59f-4dc1-ac3a-b68acfd5c694.png)

![image](https://user-images.githubusercontent.com/14309127/138201718-ad05d5dd-b08e-4d83-bd39-aab5a7df22bc.png)
there is nothing

**Comment by uslss** [comment]
@flykarry unfortunately, still cannot reproduce. Is it still actual?

**Comment by flykarry** [comment]
yes ,it is actual, I insert a value to other db then the db5 show keys

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
