### ISSUE TITLE
[Teradata] Generate SQL Function does not work

### ISSUE THREAD

**Issue by geuss** [dbeaver/dbeaver#1429]
Hello, I'm using Dbeaver over Datawarehouse my company .... I realized that the "Generate SQL" function in the contextual menu, does not work ... When I position the mouse pointer on the function, it has turned gray (deactivated).

Thanks.... and good work!

**Comment by serge-rider** [comment]
Generate SQL is not available if DBeaver can't detect source table. E.g. in case of custom SQL queries with joins.
If you think it should resolve source table - post debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by geuss** [comment]
I think that it should resolve table (the problem happens also in queries that references a single table..)
Here's the log and a bitmap that shows (better of me!) the issue.

Thanks and good work!! 

![generate sql issue](https://cloud.githubusercontent.com/assets/26387091/24003914/1736b8ce-0a65-11e7-8f87-aea81c8828e2.png)
[dbeaver-debug.zip](https://github.com/serge-rider/dbeaver/files/848189/dbeaver-debug.zip)

**Comment by geuss** [comment]
Hi serge, I'll try to post a new log... maybe it's more useful than older.

Thanks!!
[Issue#429.zip](https://github.com/serge-rider/dbeaver/files/1095226/Issue.429.zip)

**Comment by serge-rider** [comment]
What Teradata JDBC driver (exact version) do you use?

**Comment by geuss** [comment]
Hi Serge,
here the driver version:

Teradata JDBC Driver 16.00.00.23

Thanks

**Comment by geuss** [comment]
But I alredy tried to change driver version (older or newest), but the issue was still present.

**Comment by uslss** [comment]
Ticked has no apdates more than a year. Ticket closed.
If issue is still actual for you - feel free to reopen the ticket or create a new one.
