### ISSUE TITLE
DBeaver displays incorrect script number (script name)

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#14293]
#### System information: 
- Win10 Pro x64
- DBeaver 21.2.3
- No additional extensions

#### Connection specification:
- PostgreSQL 9.5
- Default driver
- No tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
If i open more than 1 new script - script number displays incorrect
#### Steps to reproduce, if exist:
https://user-images.githubusercontent.com/22142845/137923230-f25d73dc-0d82-436c-b2d8-897fbf7c491f.mp4

**Comment by LonwoLonwo** [comment]
Hello @ems2811 

What default command do you have on the "SQL" button?

![2021-10-19 17_59_37-Window](https://user-images.githubusercontent.com/45152336/137937605-d70a1587-3e1f-4ac8-bd0a-2a73d6423fde.png)

**Comment by ems2811** [comment]
Hello @LonwoLonwo 
Default command is "New SQL script"
![изображение](https://user-images.githubusercontent.com/22142845/137957225-c956bc7e-7d92-4bf8-8d04-c494bf196504.png)

**Comment by LonwoLonwo** [comment]
Hm. And what are the numbers of second and third scripts? You can check it with the "Save as" command. Maybe the numbers are just cropped?

**Comment by ems2811** [comment]
Yes. In "Save as" and in hint numbers are correct. most likely numbers are cropped.

**Comment by ShadelessFox** [comment]
Hello @ems2811,

Looks like that's the issue of "Classic" theme.

Try changing it to any other in <kbd>Preferences</kbd> &rArr; <kbd>User Interface</kbd> &rArr; <kbd>Appearance</kbd> &rArr; <kbd>Theme</kbd>.

**Comment by ems2811** [comment]
Yes. Problem only in classic theme

classic
![classic](https://user-images.githubusercontent.com/22142845/138154536-654318a0-36e9-4517-9cdf-a64cafff514f.JPG)

others
![system](https://user-images.githubusercontent.com/22142845/138154589-d3d646cc-2a6b-42ed-be48-96af04920b5e.JPG)
![light](https://user-images.githubusercontent.com/22142845/138154617-e9fad57c-ddb3-4278-aae3-4804dcecb11e.JPG)
![dark](https://user-images.githubusercontent.com/22142845/138154631-5419cf44-39b3-4b51-9685-551f308eec50.JPG)

**Comment by ShadelessFox** [comment]
I believe this problem is also related to Windows 10.

**Comment by ems2811** [comment]
Now I have no opportunity to check on another OS, but in the previous version (21.2.2) everything worked correctly.

**Comment by ShadelessFox** [comment]
We've updated Eclipse to newer version. Looks like it caused this bug.

**Comment by ems2811** [comment]
Still reproduces in DBeaver 21.3.0

**Comment by ShadelessFox** [comment]
Thanks for information. That's unfortunate.

**Comment by ems2811** [comment]
Doesn't reproduces in DBeaver 21.3.3
