### ISSUE TITLE
Intellisense does not work with Synonyms for SQL Server Connections

### ISSUE THREAD

**Issue by rubenalaez** [dbeaver/dbeaver#14315]
#### System information: 
- Windows 10
- DBeaver 21.2.3

#### Connection specification:
- Microsoft SQL Server 2017
- Microsoft JDBC Driver for SQL Server

#### Describe the problem you're observing:
The intellisense does not work with synonyms. For instance, in a query like this:

"select * from mySynonym s where s."

The fields are not shown in the intellisense.

#### Steps to reproduce, if exist:

Write a query FROM a synonym and the intellisense won't display the synonym's fields

**Comment by LonwoLonwo** [comment]
Hello @rubenalaez 
Thanks for the bug report.

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.2.4

**Comment by uslss** [comment]
verified
