### ISSUE TITLE
Add support for using an Oracle Wallet file for connecting to an Autonomous Database in Oracle Cloud

### ISSUE THREAD

**Issue by wattpuppy** [dbeaver/dbeaver#14318]
Currently to connect to an ADB in Oracle Cloud you would need to download the Wallet file zip file, extract the contents then create the custom jdbc connection string to point to the wallet directory.  SQL Developer allows you to select a wallet ZIP file then provides the contents of the embedded tnsnames.ora file.  Would it be possible to add a new driver type that could allow connections the same way?

**Comment by Matvey16** [comment]
@wattpuppy We have Oracle authentication with Wallet file in Enterprise Edition. Currently not scheduled to be added in Community Edition
