### ISSUE TITLE
Support for Snowflake GEOGRAPHY Data Type

### ISSUE THREAD

**Issue by Schniddy** [dbeaver/dbeaver#14317]
#### System information: 
- MacOS
- DBeaver version 21.2.3

#### Connection specification:
- Snowflake
- 3.13.9

#### Describe the problem you're observing:
When looking at table info if a Table was created with a Column of Type Geography the following error is thrown
No enum constant net.snowflake.client.jdbc.SnowflakeType.GEOGRAPHY

Can you add support for this Snowflake data type?

**Comment by Matvey16** [comment]
@AnthonySchneider84 Can you specify where and at what moment you are getting this error? Add a screenshot if it is possible and table DDL.
I was not able to reproduce this error.

![RcS8zWGq1t](https://user-images.githubusercontent.com/82543000/138826834-1bb7ba2f-afaf-4c49-b924-de0df7d96bb6.gif)

**Comment by uslss** [comment]
There has been no update on the issue for a long time.
If it is still present, feel free to reopen it.
