### ISSUE TITLE
Netezza username in lowercase

### ISSUE THREAD

**Issue by KrzysztofDusko** [dbeaver/dbeaver#14326]
#### System information: 
- Operating system (distribution) and version Windows 10, 1909
- DBeaver version Version 21.2.3.202110151816

#### Connection specification:
- Database name and version Netezza
- Driver name nzjdbc3.jar

#### Describe the problem you're observing:
trying to login with user name with dot example "a.user" causes
```
Error setting default catalog/schema for new connection

Reason:
SQL Error [1114] [08001]: LDAP authentication failed for user 'A.USER'
```
(DBeaver tries to use a.user (default names on netezza are uppercase), "a.user" should by used to force original spelling)

**Comment by LonwoLonwo** [comment]
Hello @KrzysztofDusko 

Can you connect with the "a.user" (in quotes) name? 

![2021-10-21 19_40_01-DBeaver Ultimate 21 2 3 - _postgres_ Script-8](https://user-images.githubusercontent.com/45152336/138320804-0917c805-3bbe-4119-b032-803f957c65ff.png)

**Comment by KrzysztofDusko** [comment]
yes. 
More info : Sql queries works fine .. window with error appears on ending of "shema refresh"

**Comment by LonwoLonwo** [comment]
Ok, thanks for the bug report.

**Comment by LonwoLonwo** [comment]
I can reproduce for Oracle too.

![2022-01-31 23_33_26-DBeaver Ultimate 21 3 3 - _orcl_Script-42](https://user-images.githubusercontent.com/45152336/151937834-119d5dd1-d523-414f-a830-41af577675ff.png)

**Comment by Matvey16** [comment]
The problem is not with the dot, but with user name is lower case. It is reproducible

**Comment by LonwoLonwo** [comment]
So. Usually users use users names in the Connection Page in the lower case and then database recognize it from server-side and uppercase it. And I'm not sure, that it can be a good decision from our side - to quote lower case user names from the connection page. This is the side case.

Please use quotes for your lower case user name in the Connection Page.

**Comment by KrzysztofDusko** [comment]
_Please use quotes for your lower case user name in the Connection Page._
login is quoted .. without it I wont be able to connect to database at all.. 
![image](https://user-images.githubusercontent.com/69449360/168083451-c76dd646-4c5e-4171-9082-60d5f10c684a.png)

and error (quotes disappeared + uppercase)
Error setting default catalog/schema for new connection
_Reason:
SQL Error [1114] [08001]: LDAP authentication failed for user 'A.USER'_

**Also important to note - "a.user" is working OK (sql works) at begining. Error appears when new tab is opened.**

To reproduce you can login to "a.user" at this point everything is OK (SQL works), add new tab - you will see connection error (LDAP authentication failed).
