### ISSUE TITLE
Can't edit nested array value via value editor in PostgreSQL

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#14327]
#### System information: 
- Operating system (distribution) and version: **Windows 10**
- DBeaver version: **DBeaver 21.2.4**

#### Connection specification:
- Database name and version: PostgreSQL 12

#### Describe the problem you're observing:
Nested array values can't be edited. Only root leaves can be edited.

https://user-images.githubusercontent.com/35821147/138280105-05f958d4-5d82-4b9d-825b-638e0f81057b.mp4

#### Steps to reproduce, if exist:
```sql
CREATE TABLE arrays (
	value int[][] NULL
);

INSERT INTO arrays (value) VALUES ('{{1,2,3},{4,5,6},{7,8,9}}');
```

**Comment by uslss** [comment]
it is not possible to change value for array and nested array for now
![image](https://user-images.githubusercontent.com/31996417/152978956-3b52125a-f541-4358-9603-ad0f3658f999.png)

column1 _int4:
![image](https://user-images.githubusercontent.com/31996417/152979070-9cc7bda5-4213-4876-bd0e-af5d002d0fc5.png)

**Comment by uslss** [comment]
verified.
created #15429
