### ISSUE TITLE
Is there any way to insert redis data by clicking like RDM ?

### ISSUE THREAD

**Issue by flykarry** [dbeaver/dbeaver#14339]
**Is your feature request related to a problem? Please describe.**
 do not write any command of redis and insert some value like the redis desktop manager

**Describe the solution you'd like**
for example, right click the db, show the insert dialog and insert

**Describe alternatives you've considered**

**Additional context**

**Comment by Matvey16** [comment]
@flykarry Can you please add a screencast or some screenshots of how that works in redis desktop?

**Comment by flykarry** [comment]
![动画](https://user-images.githubusercontent.com/14309127/138979916-9284f391-ebbc-4e43-9445-47230d5e6261.gif)
@Matvey16 here it is

**Comment by Skydiveroid** [comment]
Thank you for the idea. We should add an ability to create new KV entries.

**Comment by Destrolaric** [comment]
https://github.com/dbeaver/dbeaver-ee/pull/1413 PR
