### ISSUE TITLE
Cannot see column names within tables/views or console

### ISSUE THREAD

**Issue by kkoehleranalyst** [dbeaver/dbeaver#14331]
Hello,

I am new to DBeaver and have came across issue:  cannot view column names of tables or views.  Have tried various options to visualize them with no luck.  Is there a setting within the environment that will correct this; or a particular version of DBeaver?  I had the current version with this issue and did an uninstall and reinstall of prior version that an associate was using and was able to see the column names.  Both the current version and 21.1.5 did not correct my issues.  Please advise.

#### System information: 
- Edition	Windows 10 Enterprise
Version	21H1
Installed on	‎10/‎5/‎2021
OS build	19043.928
Experience	Windows Feature Experience Pack 120.2212.551.0

- DBeaver tried both current version and 21.1.5 (another user had this previous version and column names were available)
- using Redshift AWS

**Comment by LonwoLonwo** [comment]
Hello @kkoehleranalyst
The screen can be very helpful for investigation.
Are these tables/views in standard or spectrum schema?
Also can you please check navigation settings?

![2021-10-21 19_45_33-Connection _postgres_ configuration](https://user-images.githubusercontent.com/45152336/138321670-426582a8-d6c5-4f7f-b010-c0b5c8b02011.png)

Can be connected with https://github.com/dbeaver/dbeaver/issues/14039

**Comment by kkoehleranalyst** [comment]
What are the recommended navigator settings?
I'm not sure what is meant by tables/views in standard or spectrum schema.
I have noticed I can see the column names of some tables, but not the views
from those tables. These schemas and views were not developed by me.

Thanks,
Kimberly

**Comment by LonwoLonwo** [comment]
I can recommend an Advanced connection view.

![2021-10-21 20_30_16-DBeaver Ultimate 21 2 3 - _TEST 4_Script-62](https://user-images.githubusercontent.com/45152336/138327923-2b5917c8-c812-448a-a607-e3763d560855.png)

And again - screenshots can help us.

**Comment by kkoehleranalyst** [comment]
Thanks.  I have it set to show all system objects and still unable to see
columns.  I've also met with our technical staff to see if it has to do
with any permission settings.  There are several in our organization that
are having this same issue.  Can you think of anything else I could try or
ask the DB Admins to check?

**Comment by p91paul** [comment]
I'm not sure of what you're looking for, but when you open a table from the database navigator you default to a "Data" tab where you see the content of the table. However, next to it at the top there is a "Properties" tab; if you navigate to it, you'll see many subtabs, one of them is "Columns". Is that what you want?

**Comment by LonwoLonwo** [comment]
@kkoehleranalyst 

An example of table/view DDL (without columns) will be helpful. And info - is the table in external schema or not.

**Comment by kkoehleranalyst** [comment]
Hi Paolo,

I've used that method to view the column names and cannot see them.  I've
also used the drop down option from the navigation tab and not able to see
them there either.....I will get a quick notification that it is 'loading'
but then nothing shows up.

thanks
Kimberly

**Comment by kkoehleranalyst** [comment]
This would be an example of the script that is used creates a copy of
another schema/view and would be similar to:

'create or replace view CopyView.v_tableA as select * from
SourceView.tableA' with no schema binding'.

Does that make sense?

**Comment by LonwoLonwo** [comment]
SourceView.tableA DDL will also be useful.

**Comment by uslss** [comment]
there is no update on the issue for a long time. if it is still actual for you - feel free to reopen it with additional info
