### ISSUE TITLE
Variables in Reporting Service

### ISSUE THREAD

**Issue by ronaldorey** [dbeaver/dbeaver#14336]
Hello,
I have just started programming in Dbeaver and I have encountered a problem when declaring variables and then uploading the query to Reporting Service (through Report builder)

I have managed to declare variables with the sign of?
For instance:

where id_portfolio in (?)

In this way, when I upload the query to Report Builder, it executes it without problems as long as I only choose a portfolio.
The moment I make a multiple selection, the report no longer runs and it gives me an error.

Does anyone know how to do it?

**Comment by uslss** [comment]
@ronaldorey could you provide a video with an issue?

**Comment by ronaldorey** [comment]
Hi, I can't make a video because I can't show the confidential data.

**Comment by uslss** [comment]
please, provide steps to reproduce with screenshots or with some sample date that could help us to reproduce an issue.

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still actual - feel free to reopen it with additional info.
