### ISSUE TITLE
Question for GP connection, nodeSeqscan_hdw:27

### ISSUE THREAD

**Issue by ghy-forever** [dbeaver/dbeaver#14340]
I need to connect to a greenplum, this database has less permission for normal user, so when I press test connection, it shows a error info, ERROR:Sequence scan on catalog is disabled (nodeSeqscan_hdw:27), so how could I duel with this question?

**Comment by Matvey16** [comment]
@ghy-forever Please specify what priviliges the user that get this error have. Have you tried connecting as a user with more priveleges and was it successful?

**Comment by ghy-forever** [comment]
Our dba forbids the permission to pg_tables for normal users, but I could connect to this database with navicat; and I can use dbeaver to connect to oracle as normal user.
This picture shows what happend when I select * from pg_tables, dba create a new schema (catalog_tmp) to instead of it.
![error](https://user-images.githubusercontent.com/4074318/139819908-5f9f6f7d-fa0d-4985-aebf-2082cd834604.jpg)

**Comment by ghy-forever** [comment]
> @ghy-forever Please specify what priviliges the user that get this error have. Have you tried connecting as a user with more priveleges and was it successful?

Please check the comments upside, thanks

**Comment by Matvey16** [comment]
@ghy-forever Does your dba forbid the permissions to only pg_tables view or the whole pg_catalog schema?

**Comment by ghy-forever** [comment]
@Matvey16 I've tried other pg_catalog's talbles, most of them could be accessed in this database, so I think only pg_tables is forbidden

**Comment by Matvey16** [comment]
@ghy-forever I was not able to reproduce it, restricting access to pg_tables still don't forbid the connection (because that table is not used in initial metadata read)
I have to ask you to check your user permissions on these tables
```
pg_namespace
pg_description
pg_settings
pg_attribute
pg_class
pg_type
pg_description
```

Also if it is possible I would like to know how did your dba disable sequence scan on catalog. This is the first time I saw this error and can't find anything related to it neither in Postgres or Greenplum documentation nor in the whole internet.

**Comment by ghy-forever** [comment]
@Matvey16 I do not have user permission on these three tables
pg_attribute
pg_class
pg_type

I'm sorry about that I can't connect to my dba, so I don't know what did he or she do

**Comment by Matvey16** [comment]
@ghy-forever Ok, we will see if something can be done with those tables, thank you.

**Comment by ghy-forever** [comment]
@Matvey16 thank you, but I don't know why pgadmin and navicat could login this database, they don't use these permissions？

**Comment by Matvey16** [comment]
@ghy-forever Please attach a [log](https://github.com/dbeaver/dbeaver/wiki/Log-files) file preferably right after reproducing this bug, so we can analyze the stack trace.

**Comment by ghy-forever** [comment]
@Matvey16 How could I attach the log file? Will it be created after reproducing this bug automatic?

**Comment by Matvey16** [comment]
Yes, all errors are written to log automatically. The file is named .log and is located in `C:\Users\user_name\AppData\Roaming\DBeaverData\workspace6\.metadata`

**Comment by ghy-forever** [comment]
![1](https://user-images.githubusercontent.com/4074318/142369734-1bc267db-ea9d-419e-9f2d-db4c50bf1130.png)
![2](https://user-images.githubusercontent.com/4074318/142369760-fca0341b-670a-4001-a475-074fb261e4a7.png)
![3](https://user-images.githubusercontent.com/4074318/142369783-3dddb26a-49ef-4311-a186-7741bfe95e8f.png)
![4](https://user-images.githubusercontent.com/4074318/142369794-8bf04c1a-8afd-4392-bd5e-19110c41ca9f.png)
@Matvey16 Sorry for that I could only paste then screenshot here

**Comment by Matvey16** [comment]
@ghy-forever Unfortunately that is how Greenplum driver works (to read metadata you need those tables). I suspect that it works in Navicat because it is using generic drivers, so it can probably work in DBeaver if you create a connection with PostgreSQL (Old) driver.

![image](https://user-images.githubusercontent.com/82543000/145571612-e4666b83-517a-4526-b6db-2910a3772e8d.png)

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still present - feel free to reopen it.

**Comment by series-of-sign** [comment]
> @ghy-forever不幸的是，Greenplum 驱动程序就是这样工作的（要读取元数据，您需要这些表）。我怀疑它在 Navicat 中可以工作，因为它使用的是通用驱动程序，因此如果您与 PostgreSQL（旧版）驱动程序创建连接，它可能可以在 DBeaver 中工作。
> 
> ![图像](https://user-images.githubusercontent.com/82543000/145571612-e4666b83-517a-4526-b6db-2910a3772e8d.png)

This solution can be solved
