### ISSUE TITLE
The save task function in the import data function cannot save configuration information

### ISSUE THREAD

**Issue by oicq1699** [dbeaver/dbeaver#14341]
#### System information: 
- windows 10
- DBeaver 21.2.3
- Additional extensions

#### Connection specification:
- oracle 11.2
- Driver name:oracle.jdbc.OracleDriver(ojdbc8)
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
The save task function in the import data function cannot save configuration information
#### Steps to reproduce, if exist:
1. Select a table, select the [Import Data] menu item in the context menu
2. In the Source type and format window, select the table and database table, and click the Next button.
3. In the Select input objects window, select the corresponding source table, and click the Next button.
4. In the Tables mapping window, make no changes, and click the Next button.
5. In the Settings (Table to Database) window, make no changes and click the Next button.
6. In the Confirmation window, click the Save Task button to save the task.
When you open the saved task again, you will find that the task does not save the configuration information from the previous steps.
![image](https://user-images.githubusercontent.com/5867998/138394939-60d40842-98f5-4da0-8be6-b4f7d51e431d.png)
Translated with www.DeepL.com/Translator (free version)

**Comment by LonwoLonwo** [comment]
Hello @oicq1699 
Thanks for the bug report.

This bug is already fixed in this ticket https://github.com/dbeaver/dbeaver/issues/13232
And will be available in DBeaver version 21.2.4 on 2021-11-01
