### ISSUE TITLE
Dbeaver stops responding and overloads CPU for big tables

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14346]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version Dbeaver 21.2.4

#### Connection specification:
- Database name and version CockroachDB 21.1
- Driver name PostgreSQL JDBC Driver 42.2.20

#### Describe the problem you're observing:
If a table has a lot of rows (5 millions in my case) opening it in data editor will lead to infinite data fetching and after some time Dbeaver will stop responding and overload the CPU. Reproducible only if `Use SQL to limit fetch size` is disabled.

#### Steps to reproduce, if exist:
1. Create a table with millions of rows (postgres.public.newtable_2 in our test database)
2. Disable `Use SQL to limit fetch size` in data editor preferences
3. Open that table from navigator
4. Wait a few minutes

![dbeaver_C3hln7Ga5t](https://user-images.githubusercontent.com/82543000/138420371-be46f8eb-43d2-4d85-bc2b-7c9e29c3f187.png)
![dbeaver_oQArk81Jd9](https://user-images.githubusercontent.com/82543000/138420393-b0e83dae-db84-4749-b627-506fae5d3326.png)
![XLP2pyPKWV](https://user-images.githubusercontent.com/82543000/138420416-806a8062-9815-4a9e-92cd-a0d832ff16ea.png)

**Comment by serge-rider** [comment]
Fixed.
Results limit was disabled for CockroachDB by some reason (probably early driver version didn't support it)

**Comment by Matvey16** [comment]
Verified
