### ISSUE TITLE
"Generate SQL" option in context pop-up missing for dependences

### ISSUE THREAD

**Issue by JeroenNienhuis** [dbeaver/dbeaver#14354]
In the Database Navigator it is possible to open a Table. A Table has an option "Dependencies". In the pop-up menu of a dependency "Generate SQL" is missing (as is "Create new dependency").
![afbeelding](https://user-images.githubusercontent.com/51078213/138471003-af913c1a-2041-41e7-9c19-12e4f281d27c.png)

**Comment by Matvey16** [comment]
@JeroenNienhuis It looks like expected behavior to me. You can generate a DDL by right-clicking on constraints, foreign keys, or indexes (because they create dependencies). Are you suggesting adding an option of generating DDL for a corresponding key by right-clicking on a dependency?

**Comment by JeroenNienhuis** [comment]
I added  a column by selecting and updating a DDL from another column (with in my case a foreign key). There is no foreign key section in the DDL. It would be good to add this or add the possibility to create a DDL for dependecies from the contect menu.

**Comment by uslss** [comment]
It is not possible to generate SQL for dependency. DDL could be found in depended constraints
