### ISSUE TITLE
After exporting the data, the comma decimal separator becomes a dot

### ISSUE THREAD

**Issue by gaginsgagins** [dbeaver/dbeaver#14359]
DBeaver 21.2.3.202110151816 DBeaver - CE
System Ubuntu 20.04
Postgresql

my format data options give me to see example like this
![изображение](https://user-images.githubusercontent.com/25243076/138501323-fd85d1af-cd69-4888-9d72-4d73e586fa67.png)
But after export In result file, separator is dot.
this bug appears in all types of exports like html, csv...
Format numbers option is on.

**Comment by uslss** [comment]
thanks for the report

**Comment by DariaMarkaryan** [comment]
Verified
