### ISSUE TITLE
Unable to add foreign key to existing table

### ISSUE THREAD

**Issue by Sod-Almighty** [dbeaver/dbeaver#14351]
#### System information:
Windows 10 64-bit
DBeaver 21.2.3.xxxxx

#### Connection specification:
SQLite

#### Describe the problem you're observing:

Unable to add a foreign key to a table after the table has been committed to the database.

#### Steps to reproduce, if exist:

1. Create a table
2. Save (persist) the table to the database
3. Try to create a foreign key
4. Notice that the button to add foreign keys is missing

**Comment by ShadelessFox** [comment]
Hello @Sod-Almighty,

First of all, it's impossible. SQLite does not support adding foreign to an existing table.

In fact, we have a workaround for removing columns by recreating the table. Perhaps we can do the same for foreign keys.

So thanks for report.

**Comment by Sod-Almighty** [comment]
I'd say it was pretty much a requirement. Wouldn't you? Having to manually delete and recreate the table whenever you want to make changes is a massive pain in the rear.

**Comment by ShadelessFox** [comment]
Yes, it's a requirement caused by a limitation, unfortunately. I agree that we can improve UX by automating this tedious process.

**Comment by ShadelessFox** [comment]
Implemented creation, deletion, and altering.

**Comment by uslss** [comment]
verified
