### ISSUE TITLE
Unable to create SQLite database using file browser dialog

### ISSUE THREAD

**Issue by Sod-Almighty** [dbeaver/dbeaver#14350]
#### System information: 
- Windows 10 64-bit
- DBeaver 21.2.3.xxxxx

#### Connection specification:
- SQLite

#### Describe the problem you're observing:

I am unable to create a new SQLite database by browsing for the path and filename of the new database. I have to type the path by hand into the box.

#### Steps to reproduce, if exist:

1. Click New Database Connection
2. Choose SQLite
3. For Path, click Browse
4. Navigate to your desired directory
5. Enter the desired filename (which does not yet exist)

I get the following error:

![Prism  Microsoft Remote Desktop, Today at 12 40 42 pm](https://user-images.githubusercontent.com/4511095/138447834-f2eb10b8-8c8a-4d57-a406-4cef3fdfe617.png)

I am amazed that nobody seems to have noticed this bug before. Surely people should run into it all the time when creating new databases?

Anyhow....the solution is simply to avoid specifying "selected file must exist" when calling the OpenFileDialog API. A very easy fix.

**Comment by ShadelessFox** [comment]
Hello @Sod-Almighty,

It's not a really common thing to create database from scratch. As a workaround you can first create empty file and then choose it.

There's no way to tell this dialog to allow selecting non-existing files, it also depends on the platform. The only way is to make it "saveable", but by doing so user may start thinking that this action may overwrite selected file.

**Comment by Sod-Almighty** [comment]
The Windows API OpenFileDialog most definitely _does_ allow selection of non-existing files.

If platform agnosticism is the problem here, then why not enable the _greyed out_ Create button, and have it perform the browse-for-a-new-file operation?

**Comment by ShadelessFox** [comment]
We don't use system API directly, in our case it lays behind SWT.

The <kbd>Create</kbd> button is used by several drivers (like H2 embedded) for creating basic database setup. So it performs not what you may expect.

We indeed can make the <kbd>Browse</kbd> button, as described above, saveable, but also add a hint saying that it will not overwrite any files.

**Comment by uslss** [comment]
verfified
