### ISSUE TITLE
[21.2.3]UI frozen forever with `Database object is not associated with any execution context` shown in Error Log View

### ISSUE THREAD

**Issue by yyjdelete** [dbeaver/dbeaver#14363]
#### System information: 
- Operating system (distribution) and version: win10-x64
- DBeaver version: 21.2.3
- Additional extensions

#### Connection specification:
- Database name and version: postgres 13
- Driver name: org.postgresql:postgresql:42.2.23
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
After I upgrade dbeaver from 21.2.2 to 21.2.3, I see `Database object is not associated with any execution context` is shown in Error Log View, and then the whole program UI frozen forever.

#### Steps to reproduce, if exist:
1. Create an postgres connection, edit Settings and set `Show all databases`=`true`;
2. Open the default database `postgres`;
3. Open any other non-default database in the conn(create an new one if not exists);
4. Keep the 2 tabs open, and close dbeaver;
5. Reopen dbeaver, and wait all tabs to init;

***NOTICE***: 
There is about 50% chance it will happen for me for the first time. If it not happen, try step 4 and 5 again for the 2rd time. 
And sometimes the 2rd tab will lost when you restart for the 2rd time, you should reopen the database in step 3 again, and restart dbeaver for the 3rd time.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
