### ISSUE TITLE
could we support to start two dbeaver on the same server?

### ISSUE THREAD

**Issue by janiu-001** [dbeaver/dbeaver#14364]
Hi Expert,

could you help to answer two questions? very appreciated.

1. could we support to start two dbeavers on the same server?
I try to start two dbeavers on my mac book, below error is reported. " Can not lock the same workspace". 
Can we specify the workspace when we start the dbeaver like we start the eclipse.

![image](https://user-images.githubusercontent.com/19970581/138574737-0804d9e1-3819-49c0-b217-49e1a93696d3.png)

2. why do we have two connection when we connect to posgres?

Please check the code below , one for main context ,one for metacontext

    void checkInstanceConnection(@NotNull DBRProgressMonitor monitor, boolean cacheMetadata) throws DBException {
        if (!isSharedDatabase() && executionContext == null) {
            initializeMainContext(monitor);
            initializeMetaContext(monitor);
            if (cacheMetadata)
                cacheDataTypes(monitor, true);
        }
    }

**Comment by janiu-001** [comment]
For the first question , i tried two ways on my mc book
add the below params in the dbeaver.init, it can not work 

-data /Users/niubaoke/Library/DBeaverData/workspace1

but it can work with command line params

./dbeaver -data "/Users/niubaoke/Library/DBeaverData/workspace1"

**Comment by janiu-001** [comment]
For the second issue, i copy the connection picture here 

![image](https://user-images.githubusercontent.com/19970581/138587992-397dec96-6b00-46cc-b0c3-9feba513df5b.png)

**Comment by andrelinslima** [comment]
About the 2nd question: by default dbeaver uses a separate connection for Metadata retrieval.
You can control this behavior globally using Preferences -> Common -> Metadata -> "Open separate connection for metadata reads"
This is also overridable by connection

**Comment by janiu-001** [comment]
can we close the connection with your provided setting? there are many code using openMetaSession to query the database

**Comment by andrelinslima** [comment]
The idea of the setting is that both MainContext and MetaContext will use the same underlying connection to the database. so only one will be open.
I'm guessing If that doesn't work for a specific connector, verify and open a bug about it ;)

**Comment by janiu-001** [comment]
thanks, manually setting the "Preferences -> Common -> Metadata -> " is the only way? do we have another way to enable this feature?

could you also help on another question?

the execute log of the sql editor, how to Compatible with Linux？ for example 

select * 
from 
tablexxx

it is Garbled code on linux because  of the Newline character（\n, LF..., ), it is different from the windows system

**Comment by andrelinslima** [comment]
This option is also overridable in the connection settings, under Metadata, as I said before.

Regarding execution log, please open a bug report with the required information like OS, version, screenshots, etc.
Working correctly for me. When viewed as a column value a new line is indicated by the same symbol both on windows and linux.
![image](https://user-images.githubusercontent.com/33740641/139098577-f2055fbe-2b5a-4b36-a92b-ede22269c645.png)

**Comment by janiu-001** [comment]
Please check the screenshot below , 

![image](https://user-images.githubusercontent.com/19970581/139198325-ebe035ce-a997-48fc-a16a-8c5615ba7feb.png)

my pc info, it should also be reproduced on linux:

![image](https://user-images.githubusercontent.com/19970581/139198417-e40b5965-7454-4fa9-9f58-4da6721386be.png)

**Comment by janiu-001** [comment]
the different handle on newline character should be the root cause

**Comment by andrelinslima** [comment]
That symbol has nothing to do with different new line between platforms. like I said, that symbol is used on windows, linux, and macos when viewing the compact form (as a table column). 
You can double click on that line to show the actual query properly.

I'm guessing that's because the table doesn't support multi line for fields. But if you feel that's a problem, open a bug report for it. don't reuse the same issue. This one is tracking your suggestion for multiple workspaces.

**Comment by flambchap** [comment]
I think we should add an option to choose the workspace as Eclipse does.

**Comment by Matvey16** [comment]
@janiu-001 To answer your question about adding required workspace in dbeaver.ini you need to add this argument at the beginning of the file and also include newline after `-data` so it looks kind of like this
```
-data
/Users/niubaoke/Library/DBeaverData/workspace1
-startup
plugins/org.eclipse.equinox.launcher_1.6.300.v20210813-1054.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.300.v20210828-0802
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Xms128m
-Xmx2048m
```

**Comment by E1izabeth** [comment]
Also workspace could be changed in the main menu File->Switch workspace

Does this issue still actual for the latest DBeaver version?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
