### ISSUE TITLE
behaviour of enter-key when inline editing a table cell

### ISSUE THREAD

**Issue by JeroenNienhuis** [dbeaver/dbeaver#14360]
When editing a table cell inline
![afbeelding](https://user-images.githubusercontent.com/51078213/138506203-e0284d9f-1d8b-43e4-8e9d-daf36334fc57.png)
pressing the enter-key ends editing, and highlights the current cell
![afbeelding](https://user-images.githubusercontent.com/51078213/138506505-19a470e2-679a-442f-b6d8-c1ce9d1d198a.png)
Personally I rarely want to stay in the current cell after a cell-edit. Most of the time I want to go down 1 cell or go 1 cell to the right. Please consider pressing "enter" with a cell in edit mode moves a cell down after closing edit (e.g. like in Excel) or even better: pressing enter on the typewriter-pad and on the numeric pad show different behaviour (one moves down and other moves right) e.g. like in the old pgadmin III. Perhaps adding a few "commands" to the user interfase keyboard preferences like "close edit and down" and "close edit and right".

**Comment by Skydiveroid** [comment]
Thanks for the feature request.
