### ISSUE TITLE
Quick switch between databases or connections

### ISSUE THREAD

**Issue by MarceloZapatta** [dbeaver/dbeaver#14361]
Hi!

I have a featured request for quick switching between databases or connections... The ideia is like similar the project switch of VSCode or Sublime...

I think of two shortcuts:

CMD + ALT + C: Open a filtrable prompt with a list of all CONNECTIONS, it can be navigated by arrows keys and selected by enter

CTRL + ALT + D: Open a filtrable prompt with a list of all DATABASES, it can be navigated by arrows keys and selected by enter

It make sense?

Thanks

**Comment by Matvey16** [comment]
@MarceloZapatta Hello? Can you describe a use case for this feature? Like in what context you want to use it (while doing what?) and what needs to happen when you select a connection from this list?

**Comment by uslss** [comment]
there is no update on ticket for a long time.
If it is still actual for you - feel free to reopen it with additional info
