### ISSUE TITLE
SSH Tunneling issue in CentOS

### ISSUE THREAD

**Issue by VirgileCole** [dbeaver/dbeaver#14362]
Hello all,

I've been experiencing a weird behavior of DBeaver-ce when I tried to set it up on my CentOS 7 dual boot.
I need it to connect to a remote server by ssh. So I create a new connection and start to fill SSH tunnel parameters with correct IP, port and credentials. Finally I always got the same error:
```Cannot establish tunnel
    java.net.UnknowHostException: http://mydomain:sshport
    java.net.UnknowHostException: http://mydomain:sshport
      http://mydomain:sshport
```

I tried with credentials and ssh keys, bot the same error this means it cannot even find this IP address.
The thing is I have a dual boot Windows 10/ CentOS 7 on my computer and the same setup on DBeaver Windows work perfectly fine on first try.

DBeaver on centOS 7 version: 21.1.3.202107181810 and 21.2.3
Java on CentOS 7 version: 1.8.0_202
DBeaver on Windows 10 version : 21.1.3.2010781810
Java on Windows 10 version: JDK 8

I am really confused, is there some parameters or configurations I missed for a linux DBeaver?

Thanks a lot for your help.

**Comment by andrelinslima** [comment]
SSH doesn't use the http procotol. Remove http:// from the Host/IP field and it should work fine

**Comment by VirgileCole** [comment]
That was it, I feel stupid but I will remember for sure next time...
Thanks a lot for your answer it did help.
