### ISSUE TITLE
Result Set Viewer: Filter icons overlap column's name

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14372]
#### System information: 
- DBeaver version 21.2.3

#### Describe the problem you're observing:
If column name is longer than column width it will merge with icon

![dbeaver_np4bHo8hdQ](https://user-images.githubusercontent.com/82543000/138681318-2fad378d-d891-4506-a5fd-6dfce0b1c8e4.png)

**Comment by uslss** [comment]
verified
