### ISSUE TITLE
Ability to assign terminator within script (DB2)

### ISSUE THREAD

**Issue by jeff-bowles** [dbeaver/dbeaver#14384]
I need to be able to change the default terminator from within a DB2 script.

This issue was raised previously, with a workaround (use the DBeaver menu to change the terminator character) accepted by the OP.

The workaround will not work in my production environment.  I'm expected to hand working scripts to our DBA who runs them from the DB2 command line.

I'm requesting you support the command-line version of changing the terminator character, namely the "--#SET TERMINATOR [char]" syntax.

Thanks!

**Comment by Matvey16** [comment]
@jeff-bowles Can you provide a step by step use case for this feature? It's not really clear what you are asking.

**Comment by jeff-bowles** [comment]
Hi - thanks for the reply.

The use-case for adding "--#SET TERMINATOR" syntax to the DBeaver IDE is convenience and automation.  If I write a script that can create/drop stored procedures, for example, I need that script to be able to run successfully by an automated process.  Using DBeaver menus to change a terminator character is not (easily) automatable.

I can certainly write and run an automatable script using a text editor and the DB2 command-line.  It supports the "--#SET TERMINATOR" syntax.  However, I cannot really develop and test the final version of that script inside a nice IDE like DBeaver unless it also supports the "--#SET TERMINATOR" syntax.

Here's a trivial example of a valid DB2 script (from the DB2 command line) that won't run inside the DBeaver IDE.  Real-world scripts are bigger and more complex, of course.  I'm not able to write and test the entire, final script using DBeaver, but must use a text editor to finish it (add the terminator pseudo-commands) and then test that at the DB2 command line.

```
--#SET TERMINATOR @
CREATE OR replace FUNCTION myschema.DT_RANGE(BegDT timestamp, EndDT timestamp)
RETURNS TABLE (
  rowid integer,
  somevalue integer
)
RETURN
  SELECT ROWID, someValue from myschema.sometable where datea between BegDt and EndDt@

grant execute on function myschema.DT_RANGE to GROUP MYGROUP@

--#SET TERMINATOR ;

```

**Comment by LonwoLonwo** [comment]
Hello @jeff-bowles 

Maybe you can try to change your script delimiters in Preferences?

![2021-11-02 18_16_05-DBeaver Ultimate 21 2 4 - json_test_json](https://user-images.githubusercontent.com/45152336/139875783-de700eab-96ef-45c7-b13f-0e2b16aaa224.png)

You can write your delimiter end enable the "Ignore native delimiter" setting.

**Comment by Matvey16** [comment]
@jeff-bowles Thank you for the suggestion

**Comment by acfarrer** [comment]
Would this help with embedding connection strings in a script?

Like @jeff-bowles , I need to provide unambiguous scripts to other users and I need to ensure the connections are defined. Not sure what the SQL syntax would be though. In my scripts, I use 'db2 connect to dbname' after specifying the db2profile

**Comment by Matvey16** [comment]
Verified
