### ISSUE TITLE
Could not change the index type to unique

### ISSUE THREAD

**Issue by scruel** [dbeaver/dbeaver#14380]
#### System information: 
- Operating system (distribution) and version Windows 10 20H2
- DBeaver version 21.2.1.202109181446
- Additional extensions

#### Connection specification:
- Database name and version Mysql 5.7
- Driver name mysql-connector-java
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Nope

#### Describe the problem you're observing:
If you already have an index on a table, sometimes you may want to change the index type to unique.
But Can't change index type via UI, click the unique column '[ ]' , nothing will change, even the UI.
Then double click key which you want to change the index type, but the "unique" checkbox button is disabled, you can't click to change the status.

#### Steps to reproduce, if exist:
Open a table -> Left side select 'Index' -> Create New Index.
Click the unique column('[ ]' or '[v]') -> the column value is still '[ ]', but except to '[v]'.
Double click the key, "unique" checkbox button is disabled, but except to changeable.

**Comment by LonwoLonwo** [comment]
Hello @scruel 

Yes, for now, you can only change the unique field only when creating an index, not when changing it.

![2021-10-25 19_37_10-all_1 - Persist Changes](https://user-images.githubusercontent.com/45152336/138735802-cca582e2-cc42-4561-8b1d-c45a2a4b0a5b.png)

We can implement this feature in the next releases, so thanks for the idea.

**Comment by scruel** [comment]
> Yes, for now, you can only change the unique field

Glad to know, thanks for your work!

**Comment by LonwoLonwo** [comment]
Ability to change unique and index types via UI implemented.

![2022-03-16 17_41_53-DBeaver Ultimate 22 0 0 - customer](https://user-images.githubusercontent.com/45152336/158621535-8fcd984d-dbe0-4d82-9899-036e5b60366c.png)

**Comment by uslss** [comment]
verified
