### ISSUE TITLE
Commands line doesn't work in version 21.2.3

### ISSUE THREAD

**Issue by rvleustaquio** [dbeaver/dbeaver#14385]
#### System information: 
- Operating system (distribution) and version
Linux Mint 20.2
- DBeaver version
Community Edition 21.2.3
- Java version
openjdk 11.0.11 2021-04-20
- Additional extensions
Dark Theme Only

#### Connection specification:
Anyone

#### Describe the problem you're observing:
I usually use commands line (-closeTabs and -disconnectAll) on shortcut in version 21.2.2 like:
Exec=/usr/share/dbeaver-ce/dbeaver -closeTabs -disconnectAll
After update to version 21.2.3, DBeaver won't open anymore, I had to down version 21.2.2.

#### Steps to reproduce, if exist:
Just add command line -closeTabs or -disconnectAll

#### Include any warning/errors/backtraces from the logs
Does not generate logs

**Comment by ShadelessFox** [comment]
Hello @rvleustaquio,

This issue was fixed in scope of #14284.

You can download an early access version: https://dbeaver.io/files/ea/
