### ISSUE TITLE
Wrong date constructed in Snowflake

### ISSUE THREAD

**Issue by bobf32** [dbeaver/dbeaver#14394]
#### System information: 
- Windows 10 Enterprise 21H1
- DBeaver version 21.2.3
- Additional extensions: None

#### Connection specification:
- Snowflake

#### Describe the problem you're observing:

Select certain dates in Snowflake returns an incorrect date.

#### Steps to reproduce, if exist:

`SELECT to_date('2021-03-01');` returns the correct date

`SELECT to_date('2021-06-01');` returns 2021-05-31

`SELECT to_date('2021-09-01');` returns 2021-08-31

`SELECT to_date('2021-12-01');` returns the correct date

**Comment by Matvey16** [comment]
@bobf32 Can add a screenshot of resultset? I was not able to reproduce it.

![dbeaver_qi8PXofHOo](https://user-images.githubusercontent.com/82543000/138865833-db6c4115-e659-4eb2-aa2c-05768a0d02d6.png)

![dbeaver_zKxoJAuBG3](https://user-images.githubusercontent.com/82543000/138865845-96ac25d4-5a47-4580-946b-ae2708392845.png)

**Comment by bobf32** [comment]
Sure @Matvey16 : 

![2021-10-26 12_08_28-DBeaver 21 2 3 - _Sandpit_ Script-1654](https://user-images.githubusercontent.com/6544564/138866248-48677eca-bc75-4b09-baf0-b55653f52b86.png)

**Comment by bobf32** [comment]
More info: I get the incorrect behaviour with Disable date/time formatting checked. With that setting unchecked I get the correct date:

![2021-10-26 12_13_50-DBeaver 21 2 3 - _Sandpit_ Script-1654](https://user-images.githubusercontent.com/6544564/138866910-f7790e67-a0ed-4055-9c2b-bc37b43f9bbf.png)

**Comment by Matvey16** [comment]
@bobf32 That's even more strange, because now you have timestamp in date column

**Comment by bobf32** [comment]
@Matvey16 Maybe not so strange. In addition to Snowflake I use Oracle, so my date format normally includes HH:mm:ss (which is does right now). If I remove that then the time portion of the previous screenshot disappears. So a red herring I think.

**Comment by Matvey16** [comment]
@bobf32 Can you run `SHOW PARAMETERS LIKE '%date%';` query and show me what you get?

**Comment by bobf32** [comment]
![2021-10-26 12_56_59-DBeaver 21 2 3 - _Sandpit_ Script-1654](https://user-images.githubusercontent.com/6544564/138872873-0ca31f77-d4c8-4411-b4a1-b7fd27dc7916.png)

**Comment by Matvey16** [comment]
@bobf32 Please check if you would get the same error if you change that parameter `ALTER SESSION SET JDBC_FORMAT_DATE_WITH_TIMEZONE = FALSE`

**Comment by Matvey16** [comment]
You can also try setting JDBC_USE_SESSION_TIMEZONE to false or `ALTER SESSION SET TIMEZONE = UTC` and if it doesn't help too, it seems to me like a snowflake driver bug. We will look further into this, but as a temporary workaround you can use date-time formatting for snowflake connection

**Comment by bobf32** [comment]
Thanks @Matvey16. Changing `JDBC_USE_SESSION_TIMEZONE` doesn't help, ditto the `TIMEZONE` session parameter . As advised I will enable the DBeaver date/time formatting for now.

**Comment by Matvey16** [comment]
@bobf32 We are trying to investigate this issue further to maybe fix it. Could you please try to execute this queries and test if it will return incorrect date: 
`SELECT to_date('2021-06-01 19:00:00');` 
`SELECT to_date('2021-09-01 19:00:00');`
`SELECT '2021-06-01'::date`  
`SELECT '2021-09-01'::date`

 without Dbeaver date/time formatting

Also it would be very useful to know your database and driver version

![image](https://user-images.githubusercontent.com/82543000/141746337-6fb3cc5e-0cff-43bd-881d-b65ee5e50b6c.png)

**Comment by AndrewGabelliTR** [comment]
@Matvey16  The first and third queries in your list both return 2021-05-31. The second and fourth return 2021-08-31.

![2021-11-15 09_17_09-Clipboard](https://user-images.githubusercontent.com/60180393/141755078-f827eac2-92fe-4641-b799-460ae2cda471.png)

**Comment by bobf32** [comment]
@Matvey16 The first and third of your queries return 2021-05-31. The second and fourth, 2021-08-31.

![2021-11-15 09_28_11-DBeaver 21 2 3 - _Sandpit_ Script-1577](https://user-images.githubusercontent.com/6544564/141756819-f1033d96-e90e-4805-8286-99f4833e75e1.png)
![2021-11-15 09_28_23-DBeaver 21 2 3 - _Sandpit_ Script-1577](https://user-images.githubusercontent.com/6544564/141756826-17095edc-47ec-40b9-a8df-983693bed8ca.png)
![2021-11-15 09_28_37-DBeaver 21 2 3 - _Sandpit_ Script-1577](https://user-images.githubusercontent.com/6544564/141756822-4dab8584-444f-4e14-8018-b7d3f9b9f0d0.png)
![2021-11-15 09_28_49-DBeaver 21 2 3 - _Sandpit_ Script-1577](https://user-images.githubusercontent.com/6544564/141756821-641e6673-87a5-48e4-ab24-a1fc9cd0ef15.png)

![2021-11-15 09_17_09-Clipboard](https://user-images.githubusercontent.com/6544564/141756477-3a81261c-0757-486f-a5da-89f710b735e7.png)

**Comment by Matvey16** [comment]
Thank you.
It seems to actually be a problem with snowflake JDBC. Temporary workaround is to either use our date formatting or to downgrade the driver version.

Issues on snowflake repo:
https://github.com/snowflakedb/snowflake-jdbc/issues/513
https://github.com/snowflakedb/snowflake-jdbc/issues/477
https://github.com/snowflakedb/snowflake-jdbc/issues/457

**Comment by bobf32** [comment]
Thanks @Matvey16. Have rolled back to an older jdbc version.
