### ISSUE TITLE
wrong column types, when calculated result named like existing column

### ISSUE THREAD

**Issue by kai-morich** [dbeaver/dbeaver#14414]
tested with latest version

    create table t1 (port integer);
    insert into t1 values (1);
    select cast(port as varchar) as port, port||'' AS port, port||'x' AS port, port||'x' AS port2 from t1;

Metadata view shows correct types, but result set column header shows wrong types when result column is renamed with AS like an existing column:
Sqlite:
![image](https://user-images.githubusercontent.com/25850372/139084735-3f795a0d-418c-4487-8da3-2c5e30a100d2.png)
Hana also with wrong values as the 'x' is stripped of when converting to integer:
![image](https://user-images.githubusercontent.com/25850372/139084560-0d929d80-dd1c-48ad-bec0-d66518f1b7cd.png)

issue only shows up, when metadata is cached in dbeaver.
As the 'no corresponding table column' message comes from `DBExecUtils.bindAttributes` probably the error is also there.

**Comment by Matvey16** [comment]
@kai-morich Thank you for the report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
