### ISSUE TITLE
Declaration (F4) in DB2 tables don't show column comments/description

### ISSUE THREAD

**Issue by renezito** [dbeaver/dbeaver#14416]
Hi! I'm using DBeaver 21.2.3.  In this version the comments/description is not showed when I press F4 or via Database Navigator:
This is the evidence:

It could be great if u add it.
![DBeaver comentarios campos tablas db2](https://user-images.githubusercontent.com/37661233/139088238-d606517c-5a70-4fb9-a9f2-619367cf240c.jpg)

**Comment by Matvey16** [comment]
@renezito Hello. Can you add what driver you are using? Also which of DB2 databases is it?

**Comment by renezito** [comment]
Hi @Matvey16 , thanks fo ur answer.  As u can see, in early versions the comments are displayed Ok (see left side of the image), but in this last version it doesn't happen.  Today I update dbeaver to 21.2.5 and has the same error and the driver is the same:
![image](https://user-images.githubusercontent.com/37661233/142010216-0a2b9e1b-2bbf-4b6e-b7b4-9adc43619bed.png)

**Comment by Matvey16** [comment]
@renezito  DB2 for I/AS400 metadata heavily depends on driver properties and what works for one database may break everything on the other. Some of the default properties were changed for this driver, so you can try to change `metadata source` property to 0, or if it doesn't help, compare the properties of the driver in different versions and modify them in the new one to match those that worked.

**Comment by renezito** [comment]
Thanks!  It worked!  I use both dbeaver (one of them in my house and other in the office), but I have never change any of these properties.
Thanks again for ur quick answer.

![image](https://user-images.githubusercontent.com/37661233/142220321-5290b05b-28c6-4eb0-abce-1bd352eaef95.png)

**Comment by renezito** [comment]
I updated to 22.0.1 and again comments are not showed.  Please, don't change this value in future updates.  Every time I update dbeaver I have to change this value.  I think everyone that use DB2 driver has this problem.
