### ISSUE TITLE
Preference to not show connection in every editor tab

### ISSUE THREAD

**Issue by bobromeo** [dbeaver/dbeaver#14415]
When editing multiple (external) scripts, every tab has the script name and in front of the name, the connection between < and >. I use a project prefix for most of my scripts and there for I see little of the script name. Now I do a lot of mouse hovering to search for a particular script.

It would be nice to have a Preference which controls the display of the connection on the editor tab, with maybe an exception for connection <none>.

**Comment by p91paul** [comment]
See Preferences - Editors - SQL Editor - Scripts, there is a script title pattern. However it's not per connection, but global.

**Comment by bobromeo** [comment]
Learned something new :)
