### ISSUE TITLE
 Error resolving dependencies

### ISSUE THREAD

**Issue by baidoufuxuchangqing** [dbeaver/dbeaver#14410]
#### System information: 
- Windows 11 64bit
- DBeaver 21.2.3
- Additional extensions default extensions 

#### Connection specification:
- Database name and version no database 
- Driver name mariadb
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:

Error downloading driver libraries

原因：
 Error resolving dependencies

#### Steps to reproduce, if exist:

Error resolving dependencies
  Maven artifact 'maven:/org.mariadb.jdbc:mariadb-java-client:RELEASE' not found
  Maven artifact 'maven:/org.mariadb.jdbc:mariadb-java-client:RELEASE' not found

**Comment by LonwoLonwo** [comment]
Usually, this problem appears when DBeaver can't connect to the vendor website.
You can do it manually - load the driver .jar from the site and add it as a library for your connection. 

![2021-11-01 14_08_00-DBeaver Ultimate 21 2 4 - _postgres_ Script-8](https://user-images.githubusercontent.com/45152336/139662957-ec945b73-ab94-4293-97e2-887ae0000c5a.png)
