### ISSUE TITLE
DBeaver Crash when clicking on geometry column/entry

### ISSUE THREAD

**Issue by ismailsunni** [dbeaver/dbeaver#14413]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04
- DBeaver version: 21.22
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL with Postgis v13
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

When I did a query that has a geometry column in the result, it's fine. But, when I click on the geometry column, DBeaver crash.

I also found if I run a query that give only geometry column as a result, it also crash

**Comment by andrelinslima** [comment]
You should probably post the crash log. might indicate some missing dependency or at least a hint for the cause.
working fine for me on Ubuntu 21.04 / postgres 14 / postgis 3.1
![image](https://user-images.githubusercontent.com/33740641/139104666-7059b8f8-3782-4ee2-b6a4-3a820a5afec7.png)

**Comment by ismailsunni** [comment]
hi @andrelinslima thanks for the reply. I just installed the newer version 21.2.3 from here, and it works fine like yours.

The previous Dbeaver is installed from the snap, and 21.2.2 is the latest version. I will not use the snap version for now.

Thanks!

**Comment by jbernardes** [comment]
I also have this crash on Ubuntu 20.04 with the snap version 21.2.5

**Comment by ghost** [comment]
@jbernardes @ismailsunni; I use Ubuntu 20.04 with Debian Package 21.3.1

I solve this problem installing Postgres and PostGis **BEFORE** DBeaver, this will grant the instalation of two plugins and anothers drivers:

![image](https://user-images.githubusercontent.com/26460729/146548378-341dd8cd-9975-47a1-ab2a-8fa4b9fb1fdd.png)

But you can install manually that.

Hope this help you!
