### ISSUE TITLE
DDL Feature Addition for DB2 LUW

### ISSUE THREAD

**Issue by rajeevmenon11** [dbeaver/dbeaver#14429]
**Is your feature request related to a problem? Please describe.**
DDL feature is not working for DB2 databases in DBeaver. We've tried both 21.0.2 as well as the latest 21.2.3.

- List of errors notified when tried to pull DB object DDLs and Grants
SQL Error [38553]: Routine "DB2LK_GENERATE_DDL" (specific name "*ATE_DDL") has returned an error SQLSTATE with diagnostic text "SQL0031 Reason code or token: /db2lksp.bnd".. SQLCODE=-443, SQLSTATE=38553, DRIVER=4.26.14
SQL Error [38553]: Routine "*RATE_DDL" (specific name "") has returned an error SQLSTATE with diagnostic text "SQL0551 Reason code or token: xxxx,USAGE,SYSTOOLS.DB2LOO".. SQLCODE=-443, SQLSTATE=38553, DRIVER=4.26.14
SQL Error [38553]: Routine "*RATE_DDL" (specific name "") has returned an error SQLSTATE with diagnostic text "SQL0443 Reason code or token: *AN_TABLE,,SQL0551 Reason cod".. SQLCODE=-443, SQLSTATE=38553, DRIVER=4.26.14
SQL Error [38553]: Routine "*RATE_DDL" (specific name "") has returned an error SQLSTATE with diagnostic text "SQL0551 Reason code or token: xxxx,SELECT,SYSCAT.TABAUTH".. SQLCODE=-443, SQLSTATE=38553, DRIVER=4.26.14
SQL Error [38553]: Routine "DB2LK_GENERATE_DDL" (specific name "*ATE_DDL") has returned an error SQLSTATE with diagnostic text "SQL0031 Reason code or token: /db2lksp.bnd".. SQLCODE=-443, SQLSTATE=38553, DRIVER=4.26.14
Routine "*RATE_DDL" (specific name "") has returned an error SQLSTATE with diagnostic text "SQL0552 Reason code or token: xxxxx,BIND                ".. SQLCODE=-443, SQLSTATE=38553, DRIVER=4.26.14
Routine "*RATE_DDL" (specific name "") has returned an error SQLSTATE with diagnostic text "SQL0551 Reason code or token: xxxxx,SELECT,SYSCAT.INDEXA".. SQLCODE=-443, SQLSTATE=38553, DRIVER=4.26.14

**Describe the solution you'd like**
DB2 team of the organization is using a temporary fix to address this issue by providing additional privileges to user:
db2 -v "GRANT SELECT ON TABLE SYSCAT.INDEXAUTH TO group xxxx";
db2 -v "GRANT SELECT ON SYSTOOLS.DB2LOOK_INFO_V to group xxxx";
db2 -v "GRANT EXECUTE ON PROCEDURE SYSPROC.DB2LK_GENERATE_DDL TO group xxxx";
db2 -v "GRANT EXECUTE ON PROCEDURE SYSPROC.DB2LK_CLEAN_TABLE TO group xxxx";
db2 -v "GRANT USAGE ON SEQUENCE SYSTOOLS.DB2LOOK_TOKEN TO group xxxx"; 
db2 -v "GRANT SELECT,update,delete,insert  on table SYSTOOLS.DB2LOOK_INFO to group xxxx";
db2 -v "GRANT SELECT ON TABLE SYSCAT.TABAUTH TO group xxxx";

We would like to get the DDL feature to be working without providing any additional privileges to user.

**Comment by jeff-bowles** [comment]
I believe this is a DB2 LUW 11 bug and not a problem with DBeaver.  There is a problem with the DB2LK_GENERATE_DDL stored procedure.  A fix is available in [fp 5.](https://www.ibm.com/support/pages/node/1115973)

**Comment by jeff-bowles** [comment]
Forgot a link to the article about the fix.  [IT29789](https://www.ibm.com/support/pages/apar/IT29789)

**Comment by Matvey16** [comment]
@rajeevmenon11 I was not able to reproduce this issue. DDLs are generated as expected for me. What driver and database version are you using?

**Comment by rajeevmenon11** [comment]
> @rajeevmenon11 I was not able to reproduce this issue. DDLs are generated as expected for me. What driver and database version are you using?

Our DB2 team mentioned that its "V 10.5 FP11 DB2 version" that they're using and is seeing the same issue with all DB2 DB's

**Comment by rajeevmenon11** [comment]
> Forgot a link to the article about the fix. [IT29789](https://www.ibm.com/support/pages/apar/IT29789)

Thank you for this. DB2 team wants to know whether V 10.5 FP11 DB2 version has any bugs or not as they're using this.

**Comment by jeff-bowles** [comment]
I am on version 11.1 (no fixpack) and using the IBM JDBC driver.  I have the problem with DB2LK_GENERATE_DDL stored procedure.  I don't recall having problems with 10.5 FP11, but can't say with certainty.

**Comment by rajeevmenon11** [comment]
> I am on version 11.1 (no fixpack) and using the IBM JDBC driver. I have the problem with DB2LK_GENERATE_DDL stored procedure. I don't recall having problems with 10.5 FP11, but can't say with certainty.

Hi,
Our DB2 Team Admin tested and provided the below update:

"We tested DBeaver V 21.2.3  to extract DDLs and Privileges by connecting to DB2LUW databases V 10.5 FP 11A and V 11.1.4 FP6. We are able to pull just DDLs (not grants) for only Views and Store procedures.  When we tried to pull DDLs for tables Dbeaver  reported following error :
Routine "*RATE_DDL" (specific name "") has returned an error SQLSTATE with diagnostic text "SQL0551 Reason code or token: “User_id”,USAGE,SYSTOOLS.DB2LO".. SQLCODE=-443, SQLSTATE=38553, DRIVER=4.26.14"

**Comment by rajeevmenon11** [comment]
@jeff-bowles 
Could you please check the last update that I've posted on the issue faced by our DB2 team?

**Comment by rajeevmenon11** [comment]
@jeff-bowles could you or someone please provide an ETA on this because our DB2 team needs to know and they're asking for updates

**Comment by Matvey16** [comment]
@rajeevmenon11 Could you please try changing the driver to an older version (4.25.1301) and see if the behavior will change

It seems to be DB2 specific behavior known from #492 there is a chance that it can't be fixed

**Comment by rajeevmenon11** [comment]
> @rajeevmenon11 Could you please try changing the driver to an older version (4.25.1301) and see if the behavior will change
> 
> It seems to be DB2 specific behavior known from #492 there is a chance that it can't be fixed

Okay, let me check with our DB2 Team

**Comment by rajeevmenon11** [comment]
Our DB2 team would like to know the below info on this DDL issue:
•	If there’s no fix for this, then they need to get a confirmation email from DBeaver support stating there’s no fix for this and that they need to grant elevated access for meta tables
•	Would like to get list of Grants that needs to be granted to fix this
 
-       DB2 Team is currently using the below list of GRANTS as a temporary workaround to fix the issue:

       db2 -v "GRANT SELECT ON TABLE SYSCAT.INDEXAUTH TO group xxxx";
       db2 -v "GRANT SELECT ON SYSTOOLS.DB2LOOK_INFO_V to group xxxx";
       db2 -v "GRANT EXECUTE ON PROCEDURE SYSPROC.DB2LK_GENERATE_DDL TO group xxxx";
       db2 -v "GRANT EXECUTE ON PROCEDURE SYSPROC.DB2LK_CLEAN_TABLE TO group xxxx";
       db2 -v "GRANT USAGE ON SEQUENCE SYSTOOLS.DB2LOOK_TOKEN TO group xxxx"; 
       db2 -v "GRANT SELECT,update,delete,insert  on table SYSTOOLS.DB2LOOK_INFO to group xxxx";
       db2 -v "GRANT SELECT ON TABLE SYSCAT.TABAUTH TO group xxxx";
They would like to get confirmation from DBeaver support, if these could be used or not.

**Comment by flambchap** [comment]
Hi @rajeevmenon11. AFAIK, Tatiana has answered your request by email. We can continue the conversation here.

**Comment by flambchap** [comment]
I'm closing the ticket due to the lack of activity. Please feel free to reopen it if you think it needs to be resolved.
