### ISSUE TITLE
SQL Server: Wrong DDL of column types creation

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14427]
#### System information: 
- Win10, DBeaver CE 21.2.4

#### Connection specification:
- MS SQL Server (from AWS RDS)

#### Describe the problem you're observing:
When you create some of the column types (when editing table or creating the new one) length is set to default because of the wrong DDL.
It should contain length of the type in round brackets like "(1000)"
Below is the DDL for creating columns. some of them don't have these brackets, since such types as int, bigint, float, etc. have a fixed length. However, for example, for binary type it should be possible to change the length
![image](https://user-images.githubusercontent.com/43252954/139414435-4adc3d05-b491-4799-a68a-31ddb128a506.png)

#### Steps to reproduce, if exist:

https://user-images.githubusercontent.com/43252954/139252289-290c96d9-947a-4910-ab20-607e70617271.mp4

**Comment by LonwoLonwo** [comment]
- binary type handled (uses length as a parameter)
- datetimeoffset type handled (uses scale as a parameter)

**Comment by uslss** [comment]
verified
