### ISSUE TITLE
Manual submission

### ISSUE THREAD

**Issue by lanfeng23** [dbeaver/dbeaver#14434]
When you open the manual submission edit table in the SQL editor, such as deleting the table, execute but do not submit. At this time, if you open the table edit to be deleted from the left navigation tree, the program will get stuck

**Comment by Matvey16** [comment]
@lanfeng23 can you clarify what do you mean by deleteng table in SQL editor? Executing `DROP TABLE` statement?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info
