### ISSUE TITLE
[Clickhouse] Table size is lost in navigator after refresh

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14433]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.2.4

#### Connection specification:
- Database name and version Clickhouse 20.4.4.18
- Driver name ru.yandex.clickhouse-jdbc 0.2.6
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH tunnel

#### Steps to reproduce, if exist:
1. Connect to clickhouse database
2. Expand tables folder in navigator and observe tables' sizes
3. Click refresh on schema or tables folder

**Expected:** Size statistic is refreshed
**Actual:** Size statistic disappear

![Hc2Pss6qx9](https://user-images.githubusercontent.com/82543000/139390006-6edf4834-a2ad-4dcc-9d77-94bb18071c78.gif)

**Comment by Destrolaric** [comment]
Reproducible in Oracle and Dynamo.

https://user-images.githubusercontent.com/20579256/153021257-d8c4f817-2965-4f4e-b601-582d5ef98d58.mp4

**Comment by uslss** [comment]
still reproducible in case table is refreshed
![dbeaver_4YHaFxrFqP](https://user-images.githubusercontent.com/31996417/153564430-49cbcfdb-f16f-428b-9264-5ecf014b0db3.gif)

**Comment by Destrolaric** [comment]
Implemented fix for Redshift, Informix, Oracle, Clickhouse, Dynamo, Vertica.

**Comment by uslss** [comment]
Vertica, Informix:
![dbeaver_JjvOAwZbCl](https://user-images.githubusercontent.com/31996417/154225206-a99491eb-73bf-4e73-9cd2-d752b8129db4.gif)
DynamoDB:
![dbeaver_i1pwa0SDGC](https://user-images.githubusercontent.com/31996417/154225297-45b1336b-2e5c-418d-9097-b2f8e71f5c61.gif)
