### ISSUE TITLE
Text field truncates while previewing in Dbeaver

### ISSUE THREAD

**Issue by ak-hp** [dbeaver/dbeaver#14440]
#### System information: 
- Operating system (distribution) and version: Windows 10 
- DBeaver version: 21.1.1
- Java version : 1.8.0_171
- Additional extensions: None

#### Connection specification:
- Database name and version: SQL Server
- Driver name: MS JDBC Driver for SQL Sevver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Dbeaver seems to truncate the beginning of text columns in the preview field. The output though is intact when downloaded externally.

#### Include any warning/errors/backtraces from the logs
![dbeaver_issue1](https://user-images.githubusercontent.com/25395614/139429679-8d3e3b62-0619-4268-89f5-26d87b08ee9c.PNG)

>

**Comment by LonwoLonwo** [comment]
Hello @ak-hp 
Can you please provide table DDL and sample data for the investigation?

**Comment by uslss** [comment]
there is no update on ticket for a long time.
If it is still actual for you - feel free to reopen it with additional info
