### ISSUE TITLE
diy hot key

### ISSUE THREAD

**Issue by snowxuyu** [dbeaver/dbeaver#14447]
I hope to customize the shortcut, such as the speed of executing the SQL statement in the Mac system is Command + ENTER, not Control + Enter.

**Comment by andrelinslima** [comment]
Shortcuts are customizable using the builtin eclipse functionality:
Window -> Preference -> User Interface -> Keys
You can search for Execute SQL Statement for example and change the keys for that

**Comment by snowxuyu** [comment]
I found it. Thank you！
