### ISSUE TITLE
UI improvements for backup wizard

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14443]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.2.4

#### Describe the problem you're observing:

1. On "Backup settings" step the `next` button is disabled but next step is shown to the left. It is confusing and unintuitive.
2. After backup is done, switching to one of the other tabs disables the tab with backup log.
3. All buttons are enabled during dump progress.

![dbeaver_fovSZUzlT4](https://user-images.githubusercontent.com/82543000/139454955-662982ea-d6a8-4654-92b8-b881cef970e3.png)

![iJtI4AUkqB](https://user-images.githubusercontent.com/82543000/139454982-da1b04c3-fe69-426b-9fe4-c929f1542da6.gif)

![KyPrvgiyXm](https://user-images.githubusercontent.com/82543000/139454995-3e6dbfd9-5b0c-4ec1-9310-bfb0e6e118f7.gif)

**Comment by LonwoLonwo** [comment]
Mock Data dialog has the same problem.

**Comment by ShadelessFox** [comment]
Log is a special page that is not supposed to be accessed manually since it does not show anything until tool is executed.

Perhaps we should hide this page in the navigator.

**Comment by LonwoLonwo** [comment]
`Back`, `Start`, and `Cancel` buttons now will be disabled during the execution of the logging process

![2021-11-08 15_46_12-DBeaver Ultimate 21 2 4 - _orcl_Script-42](https://user-images.githubusercontent.com/45152336/140744978-5bc4ab62-2d34-4d99-b449-2566eb35a6e5.png)

**Comment by uslss** [comment]
Native Client and Save Task buttons should be inactive
![hSBooiToCV](https://user-images.githubusercontent.com/31996417/140904031-8fee036d-7eea-4a11-8604-82d79bfeecab.gif)

**Comment by LonwoLonwo** [comment]
Other buttons are disabled.

![2021-11-10 00_45_52-DBeaver Ultimate 21 2 5 - tbl](https://user-images.githubusercontent.com/45152336/141010090-075253e2-921e-43c9-b797-1d8cd0a18bdd.png)

**Comment by uslss** [comment]
verified
