### ISSUE TITLE
version 21.2.4  cannot  get function source on postgresql database

### ISSUE THREAD

**Issue by gidor** [dbeaver/dbeaver#14467]
#### System information: 
- Operating system (distribution) and version Ubunto 20.04
- DBeaver version : 21.2.4
- Additional extensions  NO

#### Connection specification:
- Database name and version PostgreSQL 11.7 on x86_64-pc-linux-gnu, 
- Driver name  org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
 The source tab for stored Function do not open
on 21.2.3 it iìs fine.

**Comment by Matvey16** [comment]
@gidor Hello. Please execute this query `SELECT pg_get_functiondef(Object_ID)` and check what will be returned.

Object Id can be found in function properties tab

![dbeaver_WgdLUoreIR](https://user-images.githubusercontent.com/82543000/139835371-65b5c8b3-8453-4a48-bad2-60e8e07c7153.png)

**Comment by gidor** [comment]
Sorry maybe it was my mistake installing  21.2.4, After i reinstalled  the deb file it works fine.
