### ISSUE TITLE
Checkboxes for permissions disappear in table properties

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14474]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.2.4

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
When checking permissions for different roles all checkmarks except select disappear when switching back and forth between the roles. Generated script is still correct.

#### Steps to reproduce, if exist:
1. Open permission tab in table properties
2. Check some of the permissions for one role
3. Click on another role and check some permissions
4. Click back on the first role

**Expected:** Checkmarks for checked permissions are present
**Actual:** All checkmarks except select disappear

![hHJaxBUHaE](https://user-images.githubusercontent.com/82543000/139867490-a99e337b-2fd3-4f35-baae-61e823262258.gif)

**Comment by Lkledu** [comment]
i guess this could be a good first issue that i'll try to resolve

**Comment by Lkledu** [comment]
I finished to resolve it.
