### ISSUE TITLE
DBeaver: Open Database Object (Ctrl+Shift+D) does not work when editing SQL script

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#14478]
DBeaver - **Version 21.2.4 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017, 2019**

If I am connected to a database and open a SQL script editor and try to search for a database object  using shortcut Ctrl+Shift+D the dialog pop up, but when searching for a table nothing happens.

**o** Connect to a SQL Server.
**o** Set the database you choose as active. 
**o** Open the dialog **Open Database Object** (by pressing Ctrl+Shift+D).
**o** Search for a table. This works **OK** and the table you are looking for is shown.
**o** Now open a **New SQL Script** (shortcut Ctrl+]).
**o** Set focus to the SQL Script editor.
**o** Try open the dialog **Open Database Object** again.
**o** Search for a table. Noting happens. Feel like this is an **ERROR/BUG**.

Any thoughts about this?

**Comment by LonwoLonwo** [comment]
Hello @pdanie 

Thanks for the bug report.
We will fix the problem soon. 
Closed as duplicate https://github.com/dbeaver/dbeaver/issues/14001
