### ISSUE TITLE
Selection of columns to display not working correctly

### ISSUE THREAD

**Issue by wynandcoetzer** [dbeaver/dbeaver#14471]
#### System information: 
- OSX Mojave
- DBeaver version 21.2.4
- Java version 8
- Additional extensions None

#### Connection specification:
- Database name and version MariaDB 10.5
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:

When I open a table and click on the 
"Resultset/Order filter settings" to select the columns to view, some of the fields, usually close to the last columns, refuse to be shown. When I try again, the selection is still unticked, even though I definitely ticked it. I can repeat this many times but it refuses to stick and the column does not show.

Also, the new way of ticking is incredibly frustrating. Why was it changed? The old way worker very well. The new way needs at least 3 clicks before the tick registers - sometimes a lot more. I wish I never upgarded DBeaver and I am beginnign to seriously look at alternatives.

**Comment by Matvey16** [comment]
@wynandcoetzer Could you please provide some screenshots of the issue for a more clear understanding? Also a DDL of the table would be great to reproduce it.

**Comment by wynandcoetzer** [comment]
The problem I have is purely with the UI of DBeaver. It is a problem for every table on every database. My issue is that when I want to select a set of columns to display, it has become extremely difficult. It worked very well until this last release. For the last release the tick boxes in selecting the columns to display have been changed. I experience the following problems:
1. I have to click from 3 to more than 10 times before I manage to get a tick mark. 
2. The last tick is always ignored - I have to add an extra tick mark anywhere to actually display the columns I want
3. Previous selections display as if still selected but it ignores any change in selection

Let me reiterate - until the last vserion of DBeaver this worked so well and then for no rhyme ort reason it was changed. Why change a perfectly working piece of code? And then to utterly destroy usability in the process? It is horrible!

To confirm my utter frustration with a feature that I loved in DBeaver to a totally unusable feature, I am now evaluating TablePlus and I am willing to pay for the license becauase I cannot live with the current abortion. 

Please, please change it back to the way it ws and through this piece of junk code away.

**Comment by Matvey16** [comment]
@wynandcoetzer Thank you for the report. We will work on that.

Reproducible only on MacOS
