### ISSUE TITLE
dbeaver executable launcher was unable to locate its companion launcher 21.2.4

### ISSUE THREAD

**Issue by gatrm** [dbeaver/dbeaver#14476]
#### System information: 
- Operating system - Windows 10
- DBeaver version 21.1.4

#### Describe the problem you're observing:
 problem with launcher

#### Steps to reproduce, if exist:
After instalation I launched dBbeaver and it was working
1. I added Kerberos support by adding some rows in editing dbeaver.ini
_-Djavax.security.auth.useSubjectCredsOnly=false
-Dsun.security.krb5.debug=true
-Djava.security.krb5.conf=C:\Users\xxxx.yyyy\zzzzzz\krb5.ini__

2. launching again caused error which is in issue subject
3. when I downgraded version to 21.2.3 it works fine (after changing dbeaver.ini)

**Comment by Matvey16** [comment]
@gatrm Where exactly in dbeaver.ini did you add those lines? They need to be at the end of the file. I wasn't able to reproduce your issue that way.

**Comment by gatrm** [comment]
Hi, 
My fault. It was last version 21.2.4 not as I wrote 21.1.4.
I attach my dbeaver.ini/txt file (I changed name of my user profile).
[dbeaver.ini.txt](https://github.com/dbeaver/dbeaver/files/7497595/dbeaver.ini.txt)

**Comment by Matvey16** [comment]
@gatrm So you can launch DBeaver with this ini file on version 21.2.3 and with default ini file on version 21.2.4, but after adding those 3 lines at the end of the file, version 21.2.4 stops launching?

If so, please attach your .log file located in `C:\Users\username\AppData\Roaming\DBeaverData\workspace6\.metadata`

**Comment by gatrm** [comment]
Correct.
That behaviour was occured in two cases
1. Install 21.2.4 version -> it was launching, after adding kerberos support it stopped
2. Installl 21.2.3 and uprgrade. Rest of test case was the same as 1.

I will upload log file after retest.

regards

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info
