### ISSUE TITLE
Show time SQL completed?

### ISSUE THREAD

**Issue by rdp** [dbeaver/dbeaver#14477]
Sometimes when I turn to DBeaver in the morning, connections will have been lossed.
Then when I execute a query, it "pauses" for awhile, then reconnects, then issues the query.  In the meantime I've gone off to do something else instead of staring intently at the DBeaver app to see "when it will come back."
When I get back to DBeaver, it's not clear if the query results were from "yesterday" or from "today"

What I'd like is for the "query status" short bar to say "7 row(s) fetched - 116ms, 1 min ago" or "7 row(s) fetch - Nov 2 10:50 AM"

**Describe alternatives you've considered**
I can rerun the query, but it's confusing.

Thanks!

**Comment by Matvey16** [comment]
@rdp Thank you for the suggestion

**Comment by ShadelessFox** [comment]
Implemented:

![image](https://user-images.githubusercontent.com/35821147/149334519-0de16110-1148-4247-abb7-ee760ec658d4.png)

**Comment by rdp** [comment]
Thanks!

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
Verified
