### ISSUE TITLE
MariaDB: Views-Folder is empty

### ISSUE THREAD

**Issue by zongo811** [dbeaver/dbeaver#14481]
#### System information: 
- Operating system (distribution) and version: Debian Buster
- DBeaver version: 21.2.3
- Additional extensions: None

#### Connection specification:
- Database name and version: 10.5.12-MariaDB-1:10.5.12+maria~buster-log
- Driver name: Don't know, the default driver DBeaver loads automagically
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I created a view named "v_schluessel_historie" but it is not displayed in the Views-Node in the Database Navigator. I can find the view by issuing a SQL-command or by right-clicking on "Views" and choose "Browse from here".
![grafik](https://user-images.githubusercontent.com/77285389/140039383-52118f87-aa1b-43e9-82d0-9a4e47ca88ca.png)

#### Steps to reproduce, if exist:
Connect to a MariaDB.
Create any view.
Try to locate the view in the Views-Node in the Database Navigator.

#### Include any warning/errors/backtraces from the logs

None

By the way thank you for providing this fine tool. It's very helpful and well done.

**Comment by uslss** [comment]
@zongo811 it seems from your screenshot, you have a filter applied in DB Navigator. Try to clear the filter field, so the view should become visible

**Comment by zongo811** [comment]
Silly me, thanks for the quick response.
