### ISSUE TITLE
Trying to view table triggers throws an error

### ISSUE THREAD

**Issue by JanellePhalen12** [dbeaver/dbeaver#14485]
#### System information: 
- Operating system (distribution) and version  **Windows 10,** 
- DBeaver version  **21.2.X**

#### Connection specification:
- Database name and version   **Sybase Version 16**
- Driver name  **All Drivers - Sybase jTDS and Sybase jConnect** 

#### Describe the problem you're observing:
When trying to view Table Triggers an error is thrown.
![image](https://user-images.githubusercontent.com/23363195/140066930-ce54ad17-6428-4364-ae16-49bad07077b8.png)

It says that access is denied to the audflags column in sysobjects.  This column, by default is not public.  Viewing the Triggers does work in much older versions or if the user is alias_to_dbo.   It also works if we change audflags to public, something we do not want to do.  

#### Steps to reproduce, if exist:
1. Set up Sybase Connection using jTDS or jConnect.
2. log in with an inquiry only userid.
3. Open the database and click on Table Triggers.  

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/23363195/140066930-ce54ad17-6428-4364-ae16-49bad07077b8.png)

**Comment by LonwoLonwo** [comment]
Hello @JanellePhalen12 

Ok. Driver does not return triggers to us, so we can't use the driver. I do not see alternatives except "grant all on sysobjects to public" right now. Any ideas?

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still actual - feel free to reopen it with additional info.
