### ISSUE TITLE
mssql scalar variable issue

### ISSUE THREAD

**Issue by adgwytc** [dbeaver/dbeaver#14489]
Hi,

I have searched for a solution to the below problem but cannot find the right resolution. Any help would be greatly appreciated.

I am utilisng mssql as a backend DB for Freeradius on Ubuntu and am attempting to get replication to work. This requires a distributor and publisher. I am following the mssql guides to create what we require and have got a `Must delacre the scaler variable "@distributor"` when attempting to run the following code:

```
2> DECLARE @distributor AS sysname
3> DECLARE @distributorlogin AS sysname
4> DECLARE @distributorpassword AS sysname
5> SET @distributor = N'xxxxx'
6> SET @distributorlogin = N'xxxxx'
7> SET @distributorpassword = N'xxxxx'
8> use master
9> exec sp_adddistributor @distributor = @distributor
10> , @log_file_size = 2, @deletebatchsize_xact = 5000, @deletebatchsize_cmd = 2000, @security_mode = 0, @login = @distributorlogin, @password = @distributorpassword
11> go
Msg 137, Level 15, State 2, Server xxxxx, Line 1
Must declare the scalar variable "@distributor".
```

The variable `@distributor` is declared and set and there is no "go" before the errored line. So, can anyone note what is wrong here please?

**Comment by adgwytc** [comment]
Just for information.... I seem to have found a resolution, albeit a strange one....

Leave a space between the DECLARE statements and the SET statements.

**Comment by ShadelessFox** [comment]
Hello @adgwytc,

Is your issue related to DBeaver?

Please use our issue template and provide more information.

**Comment by adgwytc** [comment]
No. Apologies if this is in the wrong area. Please remove as the issue is resolved.

Thanks
