### ISSUE TITLE
Support Check constraints for H2

### ISSUE THREAD

**Issue by ndiaz-addepar** [dbeaver/dbeaver#14496]
**System information:**
Operating system (distribution) and version macOS 10.15.7
DBeaver version 21.2.2

**Connection specification:**
Database name and version H2 1.4.200

**Describe your question:**
Does DBeaver Community support CHECK Constraints for H2 databases?

**Comment by LonwoLonwo** [comment]
Hello @ndiaz-addepar 
Thanks for the idea!

Support of Unique keys also can be implemented in this ticket.

Helpful link for the future: https://github.com/h2database/h2database/issues/2286

**Comment by LonwoLonwo** [comment]
- H2 version 2 Support added (sequences and routines reading fixed) 
 - table DDL reading added for H2 version < 2
 - Ability to create Check constraint, comment on constraint implemented
 - Ability to rename table via UI implemented
 - Ability to DROP and add COMMENT to sequence via UI implemented

![2022-02-16 11_33_45-DBeaver Ultimate 21 3 5 - EMPLOYEE](https://user-images.githubusercontent.com/45152336/154328226-0650e7e9-e73a-43fc-b49c-b207e0c2b364.png)

![2022-02-16 14_49_13-DBeaver Ultimate 21 3 5 - TEST](https://user-images.githubusercontent.com/45152336/154328229-2c2abef5-b276-497d-87e6-2256da006888.png)

![2022-02-16 14_51_31-TEST_COMPLEX_UNIQUE_PK - Persist Changes](https://user-images.githubusercontent.com/45152336/154328234-8a17fed5-c38c-44cd-a9c6-8adebf825d04.png)

![2022-02-16 17_56_42-USERS - Persist Changes](https://user-images.githubusercontent.com/45152336/154328237-00683518-f158-4b92-a83f-f44c92eb57a3.png)

**Comment by uslss** [comment]
verified
