### ISSUE TITLE
Generating DDL for Redshift procedures is incorrect

### ISSUE THREAD

**Issue by match-gabeflores** [dbeaver/dbeaver#14507]
Using **Single-signon SSO Connection (Okta)**

1. I created a proc on Redshift. 
2. in the sidebar, the procedure appears in the function folder (is that expected?). Right click the proc/function to Generate the DDL.
3. DDL is incorrect - it incorrectly shows Create function and the syntax is incorrect for a proc (include Volatile keyword, parameters don't have INOUT keyword, etc)

![image](https://user-images.githubusercontent.com/286903/148007159-054de833-a1e7-4f9e-9a4c-9dedb8dd74f1.png)

It must be related to SSO, because this does not happen on our other redshift cluster which is _not_ SSO. SSO appears to be causing this bug as well as the bug affecting Spectrum tables (#14039).

DBeaver 21.2.3, latest Redshift driver

**Comment by appleoddity** [comment]
@match-gabeflores Did you copy the "Redshift" driver or create a new driver configuration for Redshift? 

What happens if you use the original "Redshift" driver provided with DBeaver, as seen in Driver Manager?
![image](https://user-images.githubusercontent.com/29755504/140826530-28113580-ba59-4163-88d4-3b02069b4d1f.png)

**Comment by match-gabeflores** [comment]
@appleoddity - yes, this was a copy of the RS driver. I'll have to try using the original driver when I get some free time. 

@Matvey16 - I assume this will get fixed when #14039 is resolved?

**Comment by Matvey16** [comment]
@match-gabeflores Probably yes, If you were using the copy of redshift driver the reason for this bug may be the same. We will investigate both issues together

**Comment by LonwoLonwo** [comment]
Redshift/Cockroach drivers copy management fixed. Now copied driver must work and recognize PG server type correctly after DBeaver reopening.

**Comment by Matvey16** [comment]
Verified

**Comment by match-gabeflores** [comment]
Can confirm this is fixed now. Thank you!
