### ISSUE TITLE
DBeaver login issues, does it takes LDAP password for login?

### ISSUE THREAD

**Issue by atharbny** [dbeaver/dbeaver#14508]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
@atharbny please, add more info accordingly to the issue template. This info is needed to investigate an issue

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still actual - feel free to reopen it with additional info.
