### ISSUE TITLE
Postgresql : Cannot create new Indexes

### ISSUE THREAD

**Issue by wangqian-49** [dbeaver/dbeaver#14500]
#### System information: 
- Operating system (distribution) and version : Centos7
- DBeaver version  : 21.2.4
- Java version  : 11.0.2
- Additional extensions  :

#### Connection specification:
- Database name and version : postgresql 12.3
- Driver name : PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Error creating new index.

#### Steps to reproduce, if exist:

Click the left navigation bar : postgres-->postgres-->Schemas-->public-->Indexes, right click on the Indexes, and Create new Index, Pop up error prompt box.

#### Include any warning/errors/backtraces from the logs

![lQLPDhrZN_MS65TNAcLNAxGwTE1BjGzssc0BkSI4sgAHAA_785_450](https://user-images.githubusercontent.com/52651443/140691579-7be1ffa0-c817-4626-b66a-760fce95d48e.png)

![1636347885314_E367DA7F-1589-43bd-8844-F81C7F4B12DF](https://user-images.githubusercontent.com/52651443/140691634-86a4e580-4622-44e0-a25a-dacd18cf72e2.png)

**Comment by LonwoLonwo** [comment]
Thanks for the bug report!

The problem is relevant for Oracle and SQL Server too.

**Comment by wangqian-49** [comment]
Thank you for such a quick reply!

**Comment by LonwoLonwo** [comment]
Fixed for PG, Oracle, SQL Server

![2021-11-08 09_41_17-](https://user-images.githubusercontent.com/45152336/140695641-78ab5637-8e97-4200-a52f-d890c6ddd110.png)

**Comment by uslss** [comment]
verified
