### ISSUE TITLE
PostgreSQL schema filtering excluding all schemas

### ISSUE THREAD

**Issue by rasputino** [dbeaver/dbeaver#14517]
#### System information: 
- Windows 10 21H1 19043.1288
- DBeaver 21.2.4.202111011413

#### Connection specification:
- PostgreSQL 10.18 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
- org.postgresql.Driver
- Direct connection

#### Problem:
Schema filtering excluding all schemas

#### Steps to reproduce:
1- Create a new connection.
2- Edit connection. Open "General" -> "Filters" -> "Schemas/Users"
3- Add "pg_temp_%", "%temp%" or "temp" to "Exclude" list. Like in https://dbeaver.com/docs/wiki/Configure-Filters/
4- Save and reconnect.
5- Explore in navigation panel.

#### Screenshots
With filter
![imagen](https://user-images.githubusercontent.com/2887216/141082449-7195a473-76c7-4393-8a14-210a81ee4a22.png)
![imagen](https://user-images.githubusercontent.com/2887216/141082550-3cc04244-2cfd-40eb-82da-e950f752fe4b.png)
Without filter
![imagen](https://user-images.githubusercontent.com/2887216/141082853-c07e3d77-a90e-4db5-a81c-d2bcaec155cb.png)
![imagen](https://user-images.githubusercontent.com/2887216/141082908-a0ca968d-2dfa-410d-84e0-ca0dd71982ab.png)

#### Logs
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/7511277/dbeaver-debug.log)

**Comment by Skydiveroid** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.3.0

**Comment by uslss** [comment]
verified
