### ISSUE TITLE
Error installing DBeaver IDE plugin from Eclipse Marketplace manager

### ISSUE THREAD

**Issue by olivier-novalend** [dbeaver/dbeaver#14510]
Cannot complete the install because some dependencies are not satisfiable
  Software being installed: a.jre.javase 9.0.0
  Software being installed: DBeaver IDE 21.2.4.202111011413 (org.jkiss.dbeaver.ide.feature.feature.group 21.2.4.202111011413)
  Cannot satisfy dependency:
    From: DBeaver Databases 1.0.59.202111011413 (org.jkiss.dbeaver.db.feature.feature.group 1.0.59.202111011413)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ext.postgresql [2.1.141.202111011413,2.1.141.202111011413]
  Cannot satisfy dependency:
    From: DBeaver PostgreSQL Support 2.1.141.202111011413 (org.jkiss.dbeaver.ext.postgresql 2.1.141.202111011413)
    To: osgi.ee; (&(osgi.ee=JavaSE)(version=11))
  Cannot satisfy dependency:
    From: DBeaver IDE 21.2.4.202111011413 (org.jkiss.dbeaver.ide.feature.feature.group 21.2.4.202111011413)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.db.feature.feature.group [1.0.59.202111011413,1.0.59.202111011413]

Eclipse Version : 
Version: 2020-06 (4.16.0)
Build id: 20200615-1200

OS : Windows 10 Pro version 20H2

**Comment by Matvey16** [comment]
@olivier-novalend Can you describe steps to reproduce it? It's installing ok for me.

**Comment by olivier-novalend** [comment]
In Eclipse, I go to Help > Eclipse Marketplace. In Find field, I type "dbeaver" then Enter.
I click on the "Install" button for DBeaver 21.2.5, then click "Confirm" without changing any checked param (only DBeaver IDE is checked).
The installer downloads the packages an dependencies.
I then have the following error "Cannot complete the provisioning operation.  Please change your selection and try again. See below for details." with the followig stack 

```
Cannot complete the install because some dependencies are not satisfiable
  Software being installed: a.jre.javase 9.0.0
  Software being installed: DBeaver IDE 21.2.5.202111141807 (org.jkiss.dbeaver.ide.feature.feature.group 21.2.5.202111141807)
  Cannot satisfy dependency:
    From: DBeaver Databases 1.0.60.202111141807 (org.jkiss.dbeaver.db.feature.feature.group 1.0.60.202111141807)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ext.postgresql [2.1.142.202111141807,2.1.142.202111141807]
  Cannot satisfy dependency:
    From: DBeaver PostgreSQL Support 2.1.142.202111141807 (org.jkiss.dbeaver.ext.postgresql 2.1.142.202111141807)
    To: osgi.ee; (&(osgi.ee=JavaSE)(version=11))
  Cannot satisfy dependency:
    From: DBeaver IDE 21.2.5.202111141807 (org.jkiss.dbeaver.ide.feature.feature.group 21.2.5.202111141807)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.db.feature.feature.group [1.0.60.202111141807,1.0.60.202111141807]
```

**Comment by Matvey16** [comment]
@olivier-novalend Could you please open `Help -> About Eclipse IDE -> Installation details` and on configuration tab copy everything under `*** System properties:` and before `*** System environment variables:`

**Comment by olivier-novalend** [comment]
Sure,
<details>
*** System properties:
applicationXMI=org.eclipse.ui.workbench/LegacyIDE.e4xmi
awt.toolkit=sun.awt.windows.WToolkit
ds.delayed.keepInstances=true
ds.delayed.keepInstances.default=true
eclipse.application=org.eclipse.ui.ide.workbench
eclipse.buildId=4.16.0.I20200604-0540
eclipse.commands=-os
win32
-ws
win32
-arch
x86_64
-showsplash
C:\Program Files\Eclipse\\plugins\org.eclipse.epp.package.common_4.16.0.20200615-1200\splash.bmp
-launcher
C:\Program Files\Eclipse\eclipse.exe
-name
Eclipse
--launcher.library
C:\Program Files\Eclipse\\plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.1200.v20200508-1552\eclipse_11000.dll
-startup
C:\Program Files\Eclipse\\plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar
--launcher.appendVmargs
-product
org.eclipse.epp.package.php.product
-vm
C:\Program Files\Java\jre1.8.0_311\bin\server\jvm.dll
eclipse.home.location=file:/C:/Program Files/Eclipse/
eclipse.launcher=C:\Program Files\Eclipse\eclipse.exe
eclipse.launcher.name=Eclipse
eclipse.p2.data.area=@config.dir/../p2
eclipse.p2.profile=epp.package.php
eclipse.product=org.eclipse.epp.package.php.product
eclipse.startTime=1636963535323
eclipse.stateSaveDelayInterval=30000
eclipse.vm=C:\Program Files\Java\jre1.8.0_311\bin\server\jvm.dll
eclipse.vmargs=-Dosgi.requiredJavaVersion=1.8
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-XX:+UseG1GC
-XX:+UseStringDeduplication
-Dosgi.requiredJavaVersion=1.8
-Dosgi.dataAreaRequiresExplicitInit=true
-Xms256m
-Xmx2048m
-Djava.class.path=C:\Program Files\Eclipse\\plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar
equinox.init.uuid=true
file.encoding=Cp1252
file.encoding.pkg=sun.io
file.separator=\
gosh.args=--nointeractive
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.awt.printerjob=sun.awt.windows.WPrinterJob
java.class.path=C:\Program Files\Eclipse\\plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar
java.class.version=52.0
java.endorsed.dirs=C:\Program Files\Java\jre1.8.0_311\lib\endorsed
java.ext.dirs=C:\Program Files\Java\jre1.8.0_311\lib\ext;C:\windows\Sun\Java\lib\ext
java.home=C:\Program Files\Java\jre1.8.0_311
java.io.tmpdir=C:\Users\MYNAM~1\AppData\Local\Temp\
java.library.path=C:\Program Files\Eclipse;C:\windows\Sun\Java\bin;C:\windows\system32;C:\windows;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\MYNAME\AppData\Local\Microsoft\WindowsApps;;.
java.runtime.name=Java(TM) SE Runtime Environment
java.runtime.version=1.8.0_311-b11
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=1.8
java.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
java.version=1.8.0_311
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Oracle Corporation
java.vm.version=25.311-b11
line.separator=

org.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog
org.eclipse.debug.ui.breakpoints.toggleFactoriesUsed=true
org.eclipse.equinox.launcher.splash.location=C:\Program Files\Eclipse\\plugins\org.eclipse.epp.package.common_4.16.0.20200615-1200\splash.bmp
org.eclipse.equinox.simpleconfigurator.configUrl=file:org.eclipse.equinox.simpleconfigurator/bundles.info
org.eclipse.swt.internal.deviceZoom=100
org.osgi.framework.executionenvironment=OSGi/Minimum-1.0,OSGi/Minimum-1.1,OSGi/Minimum-1.2,JavaSE/compact1-1.8,JavaSE/compact2-1.8,JavaSE/compact3-1.8,JRE-1.1,J2SE-1.2,J2SE-1.3,J2SE-1.4,J2SE-1.5,JavaSE-1.6,JavaSE-1.7,JavaSE-1.8
org.osgi.framework.language=fr
org.osgi.framework.os.name=Windows10
org.osgi.framework.os.version=10.0.0
org.osgi.framework.processor=x86-64
org.osgi.framework.storage=C:\Program Files\Eclipse\configuration
org.osgi.framework.system.capabilities=osgi.ee; osgi.ee="OSGi/Minimum"; version:List<Version>="1.0, 1.1, 1.2",osgi.ee; osgi.ee="JRE"; version:List<Version>="1.0, 1.1",osgi.ee; osgi.ee="JavaSE"; version:List<Version>="1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8",osgi.ee; osgi.ee="JavaSE/compact1"; version:List<Version>="1.8",osgi.ee; osgi.ee="JavaSE/compact2"; version:List<Version>="1.8",osgi.ee; osgi.ee="JavaSE/compact3"; version:List<Version>="1.8"
org.osgi.framework.system.packages=java.applet,java.awt,java.awt.color,java.awt.datatransfer,java.awt.dnd,java.awt.event,java.awt.font,java.awt.geom,java.awt.im,java.awt.im.spi,java.awt.image,java.awt.image.renderable,java.awt.print,java.beans,java.beans.beancontext,java.io,java.lang,java.lang.annotation,java.lang.instrument,java.lang.invoke,java.lang.management,java.lang.ref,java.lang.reflect,java.math,java.net,java.nio,java.nio.channels,java.nio.channels.spi,java.nio.charset,java.nio.charset.spi,java.nio.file,java.nio.file.attribute,java.nio.file.spi,java.rmi,java.rmi.activation,java.rmi.dgc,java.rmi.registry,java.rmi.server,java.security,java.security.acl,java.security.cert,java.security.interfaces,java.security.spec,java.sql,java.text,java.text.spi,java.time,java.time.chrono,java.time.format,java.time.temporal,java.time.zone,java.util,java.util.concurrent,java.util.concurrent.atomic,java.util.concurrent.locks,java.util.function,java.util.jar,java.util.logging,java.util.prefs,java.util.regex,java.util.spi,java.util.stream,java.util.zip,javax.accessibility,javax.activation,javax.activity,javax.annotation,javax.annotation.processing,javax.crypto,javax.crypto.interfaces,javax.crypto.spec,javax.imageio,javax.imageio.event,javax.imageio.metadata,javax.imageio.plugins.bmp,javax.imageio.plugins.jpeg,javax.imageio.spi,javax.imageio.stream,javax.jws,javax.jws.soap,javax.lang.model,javax.lang.model.element,javax.lang.model.type,javax.lang.model.util,javax.management,javax.management.loading,javax.management.modelmbean,javax.management.monitor,javax.management.openmbean,javax.management.relation,javax.management.remote,javax.management.remote.rmi,javax.management.timer,javax.naming,javax.naming.directory,javax.naming.event,javax.naming.ldap,javax.naming.spi,javax.net,javax.net.ssl,javax.print,javax.print.attribute,javax.print.attribute.standard,javax.print.event,javax.rmi,javax.rmi.CORBA,javax.rmi.ssl,javax.script,javax.security.auth,javax.security.auth.callback,javax.security.auth.kerberos,javax.security.auth.login,javax.security.auth.spi,javax.security.auth.x500,javax.security.cert,javax.security.sasl,javax.sound.midi,javax.sound.midi.spi,javax.sound.sampled,javax.sound.sampled.spi,javax.sql,javax.sql.rowset,javax.sql.rowset.serial,javax.sql.rowset.spi,javax.swing,javax.swing.border,javax.swing.colorchooser,javax.swing.event,javax.swing.filechooser,javax.swing.plaf,javax.swing.plaf.basic,javax.swing.plaf.metal,javax.swing.plaf.multi,javax.swing.plaf.nimbus,javax.swing.plaf.synth,javax.swing.table,javax.swing.text,javax.swing.text.html,javax.swing.text.html.parser,javax.swing.text.rtf,javax.swing.tree,javax.swing.undo,javax.tools,javax.transaction,javax.transaction.xa,javax.xml,javax.xml.bind,javax.xml.bind.annotation,javax.xml.bind.annotation.adapters,javax.xml.bind.attachment,javax.xml.bind.helpers,javax.xml.bind.util,javax.xml.crypto,javax.xml.crypto.dom,javax.xml.crypto.dsig,javax.xml.crypto.dsig.dom,javax.xml.crypto.dsig.keyinfo,javax.xml.crypto.dsig.spec,javax.xml.datatype,javax.xml.namespace,javax.xml.parsers,javax.xml.soap,javax.xml.stream,javax.xml.stream.events,javax.xml.stream.util,javax.xml.transform,javax.xml.transform.dom,javax.xml.transform.sax,javax.xml.transform.stax,javax.xml.transform.stream,javax.xml.validation,javax.xml.ws,javax.xml.ws.handler,javax.xml.ws.handler.soap,javax.xml.ws.http,javax.xml.ws.soap,javax.xml.ws.spi,javax.xml.ws.spi.http,javax.xml.ws.wsaddressing,javax.xml.xpath,org.ietf.jgss,org.omg.CORBA,org.omg.CORBA_2_3,org.omg.CORBA_2_3.portable,org.omg.CORBA.DynAnyPackage,org.omg.CORBA.ORBPackage,org.omg.CORBA.portable,org.omg.CORBA.TypeCodePackage,org.omg.CosNaming,org.omg.CosNaming.NamingContextExtPackage,org.omg.CosNaming.NamingContextPackage,org.omg.Dynamic,org.omg.DynamicAny,org.omg.DynamicAny.DynAnyFactoryPackage,org.omg.DynamicAny.DynAnyPackage,org.omg.IOP,org.omg.IOP.CodecFactoryPackage,org.omg.IOP.CodecPackage,org.omg.Messaging,org.omg.PortableInterceptor,org.omg.PortableInterceptor.ORBInitInfoPackage,org.omg.PortableServer,org.omg.PortableServer.CurrentPackage,org.omg.PortableServer.POAManagerPackage,org.omg.PortableServer.POAPackage,org.omg.PortableServer.portable,org.omg.PortableServer.ServantLocatorPackage,org.omg.SendingContext,org.omg.stub.java.rmi,org.w3c.dom,org.w3c.dom.bootstrap,org.w3c.dom.css,org.w3c.dom.events,org.w3c.dom.html,org.w3c.dom.ls,org.w3c.dom.ranges,org.w3c.dom.stylesheets,org.w3c.dom.traversal,org.w3c.dom.views,org.w3c.dom.xpath,org.xml.sax,org.xml.sax.ext,org.xml.sax.helpers
org.osgi.framework.uuid=fb1cc4ec-6f5b-41b2-9031-0c109c790ed0
org.osgi.framework.vendor=Eclipse
org.osgi.framework.version=1.9.0
org.osgi.supports.framework.extension=true
org.osgi.supports.framework.fragment=true
org.osgi.supports.framework.requirebundle=true
os.arch=amd64
os.name=Windows 10
os.version=10.0
osgi.arch=x86_64
osgi.bundles=reference:file:org.eclipse.osgi.compatibility.state_1.1.800.v20200511-1223.jar,reference:file:org.eclipse.equinox.simpleconfigurator_1.3.500.v20200211-1505.jar@1:start
osgi.bundles.defaultStartLevel=4
osgi.compatibility.bootdelegation=true
osgi.compatibility.bootdelegation.default=true
osgi.configuration.area=file:/C:/Program Files/Eclipse/configuration/
osgi.dataAreaRequiresExplicitInit=true
osgi.framework=file:/c:/Program Files/Eclipse/plugins/org.eclipse.osgi_3.15.300.v20200520-1959.jar
osgi.framework.extensions=reference:file:org.eclipse.osgi.compatibility.state_1.1.800.v20200511-1223.jar
osgi.framework.shape=jar
osgi.framework.useSystemProperties=true
osgi.frameworkClassPath=., file:c:/Program Files/Eclipse/plugins/org.eclipse.osgi.compatibility.state_1.1.800.v20200511-1223.jar
osgi.install.area=file:/C:/Program Files/Eclipse/
osgi.instance.area=file:/C:/Users/MYNAME/eclipse-workspace/
osgi.instance.area.default=file:/C:/Users/MYNAME/eclipse-workspace/
osgi.logfile=C:\Users\MYNAME\eclipse-workspace\.metadata\.log
osgi.nl=fr_FR
osgi.os=win32
osgi.requiredJavaVersion=1.8
osgi.splashLocation=C:\Program Files\Eclipse\\plugins\org.eclipse.epp.package.common_4.16.0.20200615-1200\splash.bmp
osgi.splashPath=platform:/base/plugins/org.eclipse.platform
osgi.syspath=c:\Program Files\Eclipse\plugins
osgi.tracefile=C:\Users\MYNAME\eclipse-workspace\.metadata\trace.log
osgi.ws=win32
path.separator=;
sun.arch.data.model=64
sun.boot.class.path=C:\Program Files\Java\jre1.8.0_311\lib\resources.jar;C:\Program Files\Java\jre1.8.0_311\lib\rt.jar;C:\Program Files\Java\jre1.8.0_311\lib\sunrsasign.jar;C:\Program Files\Java\jre1.8.0_311\lib\jsse.jar;C:\Program Files\Java\jre1.8.0_311\lib\jce.jar;C:\Program Files\Java\jre1.8.0_311\lib\charsets.jar;C:\Program Files\Java\jre1.8.0_311\lib\jfr.jar;C:\Program Files\Java\jre1.8.0_311\classes
sun.boot.library.path=C:\Program Files\Java\jre1.8.0_311\bin
sun.cpu.endian=little
sun.cpu.isalist=amd64
sun.desktop=windows
sun.io.unicode.encoding=UnicodeLittle
sun.jnu.encoding=Cp1252
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
sun.os.patch.level=
user.country=FR
user.dir=C:\Program Files\Eclipse
user.home=C:\Users\MYNAME
user.language=fr
user.name=MYNAME
user.script=
user.timezone=Europe/Paris
user.variant=
</details>

**Comment by Matvey16** [comment]
@olivier-novalend  I see that you are using Java 8. It probably is the reason that leads to an error. DBeaver standalone comes with needed JRE packaged so it won't face that problem. But to install it for Eclipse you need to try using Java 11

**Comment by olivier-novalend** [comment]
So instead of using the default JRE which is version 8 (https://www.java.com/fr/download/help/windows_manual_download.html), I’ll try and install Java JDK 17 (https://www.oracle.com/java/technologies/downloads/), and see if it fixes something.
I’ll let you know.

**Comment by olivier-novalend** [comment]
Install complete with Java’s last JDK. Thank you
