### ISSUE TITLE
Open dbeaver with connection in command line

### ISSUE THREAD

**Issue by nilawafer** [dbeaver/dbeaver#14512]
Opening dbeaver from the command line on mac does not work from version 21.2.3-21.2.4. There [was a claim](https://github.com/dbeaver/dbeaver/issues/14270#issuecomment-947493090) that this would be fixed in v21.2.4 but it was not fixed (at least not for me on mac).

**Comment by nilawafer** [comment]
@ShadelessFox fyi this is still broken

**Comment by ShadelessFox** [comment]
Hello @nilawafer,

What command line options do you use?

Also [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files) would be very useful.

**Comment by nilawafer** [comment]
Thanks for your help
```
dbeaver -con "name=data-lake|driver=PostgreSQL|host=$HOST|port=5439|database=dev|user=$PGUSER|password=$PGPASSWORD"
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 21.2.4.202111011351]
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.4.100.v20210506-1050]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.12.0.v20210723-1034]
Commands processed. Exit DBeaver.
```

**Comment by ShadelessFox** [comment]
Are you sure there's no other instances of DBeaver running in the background?

**Comment by nilawafer** [comment]
That could be it. I’ll check when I’m back at my laptop

**Comment by nilawafer** [comment]
Yeah that was the issue

**Comment by christianledermann-arch** [comment]
On MacOS this command line works fine (for me, DBeaver installed via brew)
`open -a "DBeaver.app" --args -con="driver=mysql|database=my_test_db|user=root|password=root|save=true|host=127.0.0.1|port=3306"`

calling the `dbeaver` executable directly does not work though.

Just leaving this here as it was the first search result popping up, when someone runs into the same problem.
