### ISSUE TITLE
Don't move the ER diagram until search is complete

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14511]
Right now search function in ERD works like this: After any symbol input focus starts moving rapidly from table to table until the search is complete, this looks strange and maybe even scary.
It would be better to move a diagram to target table only after search is finished. Also I suggest adding a delay before search to allow inputting other symbols before search starts.

**Comment by cassis163** [comment]
It looks as if DBeaver is having spasms
