### ISSUE TITLE
Make it possible to add one or multiple Maven artifacts in the Driver Manager using Maven and Gradle dependency syntax

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#14527]
The most popular way to add artifacts from Maven Central is to go to `mvnrepository` and copy-paste snippets from the artifact's page. Our current dialog has 3 different fields (_GroupId_, _ArtifactId_, _Version_) in our _Add Artifact_ dialog. Because of that, the user needs to parse these snippets by hand and divide them into these 3 fields. It would be nice if we could do that for the user.

**Comment by Matvey16** [comment]
Making changes to URL creates additional artifacts

![aVp10RjSP5](https://user-images.githubusercontent.com/82543000/142826946-748c7446-4bd3-4279-85dc-3e9ddcae0d76.gif)

**Comment by Matvey16** [comment]
Verified

**Comment by Destrolaric** [comment]
Found text dissapperance after switching tabs + npa in edit mode. Added two bugfixes to fix this issues

**Comment by Matvey16** [comment]
Verified
