### ISSUE TITLE
Unable to cancel tunnel configuration test which causes UI block

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#14522]
#### System information: 
- Operating system (distribution) and version Win 11
- DBeaver version 21.2.5 UE devel
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Steps to reproduce, if exist:
1. Open the new connection dialog for a non-embedded database.
2. Open the SSH tab.
3. Provide some invalid SSH tunnel parameters. I used IP `1.1.1.1`, user `dbeaver`, password `dbeaver`. Click _Test tunnel configuration_
4. Click _Cancel_ on the _Progress Information_ window. It won't do anything, you need to wait for the test to fail.

The worst thing about this situation is that UI is blocked.

**Comment by ShadelessFox** [comment]
Perhaps we want to do something like this to the entire connection (not only during test).

There may be some problems with proxies (proxy is per thread).

**Comment by Matvey16** [comment]
Verified
