### ISSUE TITLE
Display duplicated title name on database navigator panel when click refresh (F5) some title name.

### ISSUE THREAD

**Issue by Bkingkam** [dbeaver/dbeaver#14525]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
@Bkingkam please, add more info accordingly to the issue template. It is needed for the issue investigation.

**Comment by Bkingkam** [comment]
[image: image.png]
as picture 'yan222' procedure has displayed many rows
Thank you so much for your responsed

**Comment by uslss** [comment]
unfortunately, pictures that are sent from email are not visible. Could you add pic once again? thanks in advance
![image](https://user-images.githubusercontent.com/31996417/142592739-f508e2fb-84d7-47e2-9637-1ebdcc92980d.png)

**Comment by Bkingkam** [comment]
[image: image.png]

**Comment by uslss** [comment]
unfortunately, picture uploaded using email aren't visible. Please, upload picture through github UI

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info

**Comment by Bkingkam** [comment]
Thank you.
