### ISSUE TITLE
Customize filters options with checkboxes have a focus issue

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#14526]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.2.5 EA

#### Steps to reproduce, if exist:
1. Open customize filters.. dialog for a table
2. Try to change a condition with checkbox for a column

**Expected**: the change is applied
**Actual result**: the value isn't changed and applied
**Note**: the issue doesn't exist in table properties, data transfer dialog

https://user-images.githubusercontent.com/51405061/141266511-59c85068-7271-4362-9fcb-39c601499e80.mov

**Comment by ShadelessFox** [comment]
Can't reproduce against DBeaver 21.2.5 on macOS 12.0.1

https://user-images.githubusercontent.com/35821147/142634103-21120d9e-b387-459d-91fb-aee9c07d0f86.mov

**Comment by kseniiaguzeeva** [comment]
The issue is in focus. When I 
1. click on a checkbox and press Ok, the option isn't applied
2. click on a checkbox, press on field of the dialog and press Ok, the option is applied

https://user-images.githubusercontent.com/51405061/142873009-b009c84b-acb2-4ca9-a215-256b191bb4c3.mov

**Comment by Matvey16** [comment]
Verified
