### ISSUE TITLE
Columns with upper case must be quoted to apply a filter

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#14520]
#### System information: 
- DBeaver version 21.2.4

#### Connection specification:
- Database name and version Greenplum

#### Steps to reproduce, if exist:
Write a column name with an uppercase letter in its name in the top filter fieild and apply a filter

**Expected**: the filter is applied
**Actual result**: filter request uses lower case only for column name and filter cannot find such column
**Workaround**: use quotes or autocomplete (the column name is quoted in this case)

https://user-images.githubusercontent.com/51405061/141115276-be05c964-59a7-4c28-947f-bf3a1939ac7e.mp4

**Comment by E1izabeth** [comment]
It's an expected behavior.
