### ISSUE TITLE
The bulk load checkbox can be checked and disabled when target container doesn't support such option

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#14534]
#### System information: 
- Operating system (distribution) and version Win 11
- DBeaver version 21.2.5 UE devel
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Steps to reproduce, if exist:
1. Export data to `PostgreSQL` using the _bulk load_ option.
1. Attempt to export data to SQLite.
1. On the corresponding page, the _bulk load_ checkbox will be checked and disabled.

**Comment by uslss** [comment]
verified
