### ISSUE TITLE
[Hive] Change key creation through UI

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14531]
Different versions of Hive can either support constraints or not. Hive started supprting constraints from version 2.1.0
Right now Dbeaver has strange and incorrect creation and presentation of keys.

1. Table metadata window has a tab for keys, but it is always blank, even if the table actually has keys. Also generated table DDL doesn't include any keys as well.
2. When new table is being created through UI there is a button to create new key, regardless of database version. But if new key is created with that button the resulting script won't work anyway. Even if the database version is 2.1.0+, the sytax for key creation is differen from what we are generating
```
constraint_specification:
  : [, PRIMARY KEY (col_name, ...) DISABLE NOVALIDATE RELY/NORELY ]
    [, PRIMARY KEY (col_name, ...) DISABLE NOVALIDATE RELY/NORELY ]
    [, CONSTRAINT constraint_name FOREIGN KEY (col_name, ...) REFERENCES table_name(col_name, ...) DISABLE NOVALIDATE 
    [, CONSTRAINT constraint_name UNIQUE (col_name, ...) DISABLE NOVALIDATE RELY/NORELY ]
    [, CONSTRAINT constraint_name CHECK [check_expression] ENABLE|DISABLE NOVALIDATE RELY/NORELY ]
```
3. If the table is already created the button to create new constraint is disabled regardles of database version, even though 2.1.0+ versions support
```
ALTER TABLE table_name ADD CONSTRAINT constraint_name PRIMARY KEY (column, ...) DISABLE NOVALIDATE;
ALTER TABLE table_name ADD CONSTRAINT constraint_name FOREIGN KEY (column, ...) REFERENCES table_name(column, ...) DISABLE NOVALIDATE RELY;
```

**Comment by uslss** [comment]
duplicates #10330
