### ISSUE TITLE
The SQL Editor is opened for a default schema from the Data Editor

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#14533]
#### System information: 
- DBeaver version 21.2.5 EA

#### Steps to reproduce, if exist:
1. Set a default schema for a database
2. Open a table from a non-default schema in the Data Editor
3. Place focus in the Data Editor and open the SQL Editor

**Expected**: the schema for the current table is selected in the SQL Editor top toolbar
**Actual result**: the top toolbar shows the default schema in the Data Editor and shows and uses the default schema in the SQL Editor

https://user-images.githubusercontent.com/51405061/141312653-3e0bea2c-1efa-4a27-9a78-4660027e8cc1.mov

**Comment by LonwoLonwo** [comment]
Fixed only for the topic case.

![83RveKchiD](https://user-images.githubusercontent.com/45152336/143057807-f751f6fe-86ce-45e5-95b9-339cff8c9e12.gif)

**Comment by Matvey16** [comment]
Verified
