### ISSUE TITLE
Export in table "Only selected columns" has wrong mapping

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14537]
#### System information: 
- Win10
- DBeaver CE 21.2.5

#### Connection specification:
- Not specific

#### Describe the problem you're observing:
Because of all columns are created if you check "only selected columns" 

#### Steps to reproduce, if exist:
1. Create table with two columns: the first is varchar and the second is Date type.
2. insert data in row
![image](https://user-images.githubusercontent.com/43252954/155016848-d9ec8273-abc9-45ba-b887-39e3305df2e4.png)
3. select only date value cell
![image](https://user-images.githubusercontent.com/43252954/155016941-3d192acf-ff96-46a3-a801-4dd0c278906b.png)
4. activate "only selected columns" 
![image](https://user-images.githubusercontent.com/43252954/155017041-e3f5367d-eb83-4610-8b6b-8860d200e982.png)
5. Start export. Then you can see that value from the first column try to insert in the exporting column (so we get an error that says 'abc' is wrong format for date column )
![image](https://user-images.githubusercontent.com/43252954/155017088-97ca4ca6-6099-4641-a155-cbd2e13fc944.png)

**Comment by Matvey16** [comment]
Still reproducible
