### ISSUE TITLE
Query result set column filter on numeric values

### ISSUE THREAD

**Issue by db2zosuser** [dbeaver/dbeaver#14545]
Looks like query result set column filter on numeric values behavior did change between V21.0.0 and V21.1.2. 

Up until V21.0.0 column filter on numeric values did show **exact match** (=)
https://user-images.githubusercontent.com/61581747/141457451-9a54e1f2-75ac-4d75-913e-659dfcaa3d1b.mp4

In V21.1.2 and also most recent version V21.2.4 filter does work as greater than (>)
https://user-images.githubusercontent.com/61581747/141457511-11dba37c-2ec8-4578-a212-d821c196bda0.mp4

Is that a new feature or a defect?

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
verified
