### ISSUE TITLE
Working with Date Datatypes

### ISSUE THREAD

**Issue by keithschaller79** [dbeaver/dbeaver#14540]
This is likely closer to an enhancement than bug, but when I open Preferences and go to Data Formats and update the Date field format to yyyy-MM-dd HH:mi:ss the time is always truncated to 00:00:00 in the Results panel.

Is there a way I can see a JDBC date datatype as a JDBC timestamp in DBeaver? Is there no interpretation from Date to Timestamp (SQL 91 to SQL 93)?
I have to use another tool like SQuirreL to see the time format of the date datatype, so it is not the custom JDBC driver.
So whenever I have to work with dates, I can't use DBeaver.

Yet, if I try to query for a date field, the timestamp must be included.

# No Results
SELECT * FROM table WHERE table_uid in (598818, 598819) and add_date = '2018-12-10';
# Results
SELECT * FROM table WHERE table_uid in (598818, 598819) and add_date = '2018-12-10 14:50:33';

This is inconsistent that you can't see the timestamp but require a timestamp in the SQL where clause for a date datatype.
Hopefully there is a way to do this in DBeaver that I've missed.

DBeaver Version 21.2.1.202109181446
Custom JDBC Driver (Non-Commercial)
JDK 1.7.0_80
Windows 10 Build 19043

**Comment by uslss** [comment]
@keithschaller79 what driver and database do you use?

**Comment by keithschaller79** [comment]
It is a custom built JDBC driver (not commercially available) and the
database is Ingres 10.2

**Comment by LonwoLonwo** [comment]
Hello @keithschaller79 

Please, provide more info.
Can you provide a table DDL, please?
Also, table data screenshots from DBeaver vs SQuirreL too.

**Comment by uslss** [comment]
There has been no update on the issue for a long time.
If it is still present, feel free to reopen it.
