### ISSUE TITLE
MariaDB: can't find native client in dump task

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14555]
#### System information: 
- Win10
- DBeaver CE 21.2.5
- 
#### Connection specification:
- MariaDB (Driver version 2.7.1)

#### Describe the problem you're observing:
When creating a task for Maria dump, the native client cannot be found

#### Include any warning/errors/backtraces from the logs
![image](https://user-images.githubusercontent.com/43252954/141743225-ee7f1cf9-13db-4b7a-98ef-2e364cfac352.png)
But at the previous page MySQL Binaries client is selected:
![image](https://user-images.githubusercontent.com/43252954/141743305-45f7e6ec-6e09-4b3a-bde3-208a227ca85d.png)

**Comment by Matvey16** [comment]
Can't reproduce anymore, needs more specific steps to reproduce.

**Comment by uslss** [comment]
can't reproduce in 21.3.2
