### ISSUE TITLE
Unable to Upgrade to Latest Version with APT on Ubuntu 20.10

### ISSUE THREAD

**Issue by tcampbPPU** [dbeaver/dbeaver#14551]
#### System information: 
- Operating system (distribution) and version: **Ubuntu 20.10 x86_64 5.11.0-7620-generic**
- DBeaver version: **21.0.2**
- Additional extensions

#### Describe the problem you're observing:
Each time I open DBeaver I get prompted to install the latest version (at time is `21.2.4`) but running
```bash
sudo apt-get --only-upgrade install dbeaver-ce/now
```
Gives me the following message:
```
dbeaver-ce is already the newest version (21.0.2).
Selected version '21.0.2' ( [amd64]) for 'dbeaver-ce'
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```
So my issue is I cannot upgrade to latest release version using apt package manager on Ubuntu 20.10

#### Steps to reproduce, if exist:

* Install DBeaver 21.0.2 on Ubuntu 20.10 
* Try to upgrade to latest version using apt package manager

**Comment by tcampbPPU** [comment]
Creating a new issue since [#12978](https://github.com/dbeaver/dbeaver/issues/12978) was not receiving any more feedback

**Comment by Matvey16** [comment]
@tcampbPPU Thank you for the report. There is a mistake in dbeaver.io repository that leads to this bug, we will investigate it. As a workaround you can either use [launchpad](https://launchpad.net/~serge-rider/+archive/ubuntu/dbeaver-ce) repository or manual install with .deb file from https://dbeaver.io/download/

**Comment by tcampbPPU** [comment]
Thanks for the update! @Matvey16

**Comment by Matvey16** [comment]
@tcampbPPU Repository has been updated, you can try to update Dbeaver version
![66751818-8009-4477-b4c6-6e63b1f125f9](https://user-images.githubusercontent.com/82543000/142620221-67be2840-76ea-4db3-a3af-a1e99708e516.png)

**Comment by tcampbPPU** [comment]
Hi @Matvey16 this is still what I am seeing
![image](https://user-images.githubusercontent.com/25044744/142631232-d013c565-4469-415f-8606-853a16b03f95.png)
![image](https://user-images.githubusercontent.com/25044744/142631347-08d2a662-f32e-4f1d-864e-fed7c8b05fba.png)

If I manual install from .deb file, will I loose all my connection presets I currently have saved?

**Comment by Matvey16** [comment]
@tcampbPPU Strange, we will look into that.

No, all your project and workspace metadata is stored in separate directory, so it will not change if you reinstall from .deb file. Note that the above rule is not applicable for snap version, because snap forces apps to save everything in the same directory.

**Comment by Skydiveroid** [comment]
Hi there, @tcampbPPU.

_wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -
echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list_

Please add a repository shown above and this should solve the problem

**Comment by Matvey16** [comment]
I had the same problem while testing. To solve it you need to first add repository like mentioned above
```
wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -
echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list
```
Then restart your machine and upgrade with `sudo apt-get --only-upgrade install dbeaver-ce`

**Comment by tcampbPPU** [comment]
> I had the same problem while testing. To solve it you need to first add repository like mentioned above
> 
> ```
> wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -
> echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list
> ```
> 
> Then restart your machine and upgrade with `sudo apt-get --only-upgrade install dbeaver-ce`

Thank you both very much @Skydiveroid & @Matvey16!
![image](https://user-images.githubusercontent.com/25044744/142900436-ea4459a8-bf5e-494b-b57f-7798704eb1e4.png)
![image](https://user-images.githubusercontent.com/25044744/142900242-51dfa16e-6390-4266-86d6-5b3c623b31ab.png)
