### ISSUE TITLE
Backward History fails on foreign keys 

### ISSUE THREAD

**Issue by bender270** [dbeaver/dbeaver#14565]
#### System information: 
- Windows 10 x64 pro
- DBeaver 21.2.5

#### Connection specification:
- SQL Server Database
- Microsoft JDBC Driver for SQL Server

When jump to a foreign key record

![image 1](https://user-images.githubusercontent.com/7341240/141800320-b92d35ed-1c87-42bd-a20f-291f98668fc3.png)

Backward history does not work. either shortcut (ALT+left) or menu (it seems disabled)

![image 2](https://user-images.githubusercontent.com/7341240/141800752-a502740d-58a0-4aaa-a58e-38db44f9a995.png)

#### Steps to reproduce, if exist:

1) execute a select from a table that has a foreign key to another table

2) Click on foreign key column icon (as Shows image 1)

3) Try to go backward to the original select, using the shortcut (ALT+left) or the menu (Image 2)

This worked fine on 21.2.4 version

Thank you

**Comment by uslss** [comment]
thanks for the report

**Comment by Matvey16** [comment]
Probably a side effect of that ticket #13318

**Comment by serge-rider** [comment]
Fixed

**Comment by bender270** [comment]
Thanks. 

Congratulations for the good work you do with this great software

**Comment by uslss** [comment]
verified.
Fix will be available in 21.3.0
