### ISSUE TITLE
Enabling "Show all databases" hides the template database even if it configured as default

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14563]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.2.5

#### Connection specification:
- Database name and version Greenplum Database 4.3.7.1 build 1
- Driver name PostgreSQL JDBC Driver 42.2.20

#### Describe the problem you're observing:
If a template database is configured as default it will be the only visible db in navigator. Enabling "Show all databases" in preferences, will instead show other database and not the default.  

#### Steps to reproduce, if exist:
1. Connect to a server with at least one template database
2. Enter that database as default in connection configuration
3. Enable "Show all databases"

**Expected:** Default db is shown alongside other databases
**Actual:** Default database is not shown until an option "show template databases" is enabled

![HYxCCffGUg](https://user-images.githubusercontent.com/82543000/141786934-82e1cf7e-27bf-46da-bb04-feac42cae0e8.gif)

**Comment by LonwoLonwo** [comment]
Fixed.

Will work only for the field "Database" in PG connection settings.

**Comment by Matvey16** [comment]
Verified
