### ISSUE TITLE
"Event triggers"-Tab for PostgreSQL

### ISSUE THREAD

**Issue by ridicolos** [dbeaver/dbeaver#14566]
There is no tab in DBeaver to show event-triggers of a PostgreSQL-Database.

It would be nice if you could check your event-triggers of a PostgreSQL-Database inside the DBeaver-UI.

**Comment by LonwoLonwo** [comment]
pg_catalog.pg_event_trigger can be helpful in this case

**Comment by LonwoLonwo** [comment]
@ridicolos 
Thanks for the idea!

**Comment by LonwoLonwo** [comment]
Event triggers support implemented for PostgreSQL, Greenplum and EnterpriseDB (versions > 9.3)

![2022-02-10 03_26_08-DBeaver Ultimate 21 3 4 - log_ddl_info](https://user-images.githubusercontent.com/45152336/153316748-2c426407-482a-4760-b124-87341ac7c8b6.png)

![2022-02-10 03_55_04-Disable trigger -  Disable trigger](https://user-images.githubusercontent.com/45152336/153316754-2b2fb276-e22a-404e-bcbe-bfde6a05c443.png)

![2022-02-10 03_56_26-DBeaver Ultimate 21 3 4 - last_updated](https://user-images.githubusercontent.com/45152336/153316757-08beb4e6-ab47-4dc2-9fe5-5d49a02dc717.png)

**Comment by LonwoLonwo** [comment]
You can 
- create Event Triggers via UI (as ordinary triggers)
- Rename event triggers via UI
- Comment event trigger via UI
- Drop event trigger via UI
- Change trigger body and save

**Comment by uslss** [comment]
1. it is impossible to rename event trigger and trigger in metadata viewer: new name is used as old name 
![image](https://user-images.githubusercontent.com/31996417/153570000-31b425ba-a13d-4ed6-8242-eb396b9d2ff5.png)
2. DDL isn't correctly updated after rename in navigator - event trigger and usual trigger name remains old in trigger source until manual refresh
![dbeaver_W56ZEUNxSn](https://user-images.githubusercontent.com/31996417/153570114-8536de55-d41b-4b20-acb0-000914e25c02.gif)
3. event type isn't taken into account in case default event type is used.
![dbeaver_qCLRW36D9k](https://user-images.githubusercontent.com/31996417/153570698-69e4efa4-efed-4f28-9240-b1d743caf2a0.gif)
4. if more than one ticket is created at the moment - all triggers disappear if one of them was saved (except saved trigger)
![dbeaver_jMWQ4TY6JI](https://user-images.githubusercontent.com/31996417/153571064-1d45c0dd-d835-442d-914d-7f1d9a1980e8.gif)
5. The strange highlight of the trigger function field after choosing trigger function - gif below - happens without holding the mouse button
![dbeaver_P9bA1OUojq](https://user-images.githubusercontent.com/31996417/153572329-63aa44c9-7670-4da9-b596-3d58144359db.gif)
6. Changed comment refreshes in the source only after disable-enable show comments option
![dbeaver_lJeJWRgzrU](https://user-images.githubusercontent.com/31996417/153572857-c3c0a7ab-6729-4b9e-a206-18abe05eb01e.gif)

**Comment by LonwoLonwo** [comment]
1,2,3,4,6 Fixed.

**Comment by uslss** [comment]
verified

**Comment by sofiarosati** [comment]
Thank you! :heart:

**Comment by LonwoLonwo** [comment]
Thanks for the feedback @sofiarosati
