### ISSUE TITLE
Table name truncated on "SQL Editor / Tables Tab List"

### ISSUE THREAD

**Issue by Nope7** [dbeaver/dbeaver#14567]
#### System information: 
- Operating system (distribution) and version: W10 
- DBeaver version:   21.2.5.202111141807	
- Additional extensions: Office Support

#### Connection specification:
- Database name and version: DB2 iSeries
- Driver name: DB2 iSeries/AS400
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Table names are truncated In the main perspective - top tab list.

In the example attached table name is ANWEB00F and the name showed is ANWEB00...
![image](https://user-images.githubusercontent.com/32847237/141825403-bdb9d3bf-d562-4cad-9c19-04bad9417acd.png)

It should not be related to drivers, because table names are correct in all the other perspective / section, as you can see in the screenshot attached.

The issue occurred since version 21.2.4. 

#### Steps to reproduce, if exist:
Open a table --> Here it is...

**Comment by ShadelessFox** [comment]
Hello @Nope7,

This is a problem of Classic theme, please see #14293.

Closed as duplicate
