### ISSUE TITLE
JDBC template URL cannot work if containing variables for Custom Connection Type

### ISSUE THREAD

**Issue by Fang3s** [dbeaver/dbeaver#14572]
#### System information: 
- Windows 10.0.18362.900
- DBeaver 21.2.5.202111141807 (Release date: 2021-11-15)
- Additional extensions  
  C:\Users\ssfang\AppData\Roaming\DBeaverData\drivers\maven\maven-central\com.oracle.database.jdbc\ojdbc8-12.2.0.1.jar

#### Connection specification:
- Database name and version: Oracle Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
- Driver name: Oracle JDBC driver 12.2.0.1.0 (ojdbc8-12.2.0.1.jar)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No.

#### Describe the problem you're observing:

1. Inputs in Basic tab are reset to empty after configuring in Custom tab of the Edit Connection dialog
2. DBeaver directly uses the user input configured from JDBC URL Template without variable substitution for Test Connection or Open Connection
    ![IDEA debugging screenshot](https://user-images.githubusercontent.com/6383616/141936656-3c956917-01e2-401e-a0f2-0ae3e5890b4f.png)

BTW, make DBeaver debuggable in dbeaver.ini (-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8888 after `-vmargs`),

```
-startup
plugins/org.eclipse.equinox.launcher_1.6.300.v20210813-1054.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.300.v20210828-0802
-vm
C:\Users\ssfang\Desktop\jdk-17\bin
-vmargs
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8888
-XX:+ShowCodeDetailsInExceptionMessages
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
```

C:\Users\ssfang\AppData\Roaming\DBeaverData\workspace6\General\Scripts
C:\Users\ssfang\Desktop\git\.metadata\.plugins\org.eclipse.pde.core\DBeaver.product

See also
- [OracleDataSourceProvider#getConnectionURL](https://github.com/dbeaver/dbeaver/blob/202ccc4d6dea869cb5ba50f7038af23659434d24/plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/OracleDataSourceProvider.java#L65)
- [class OracleDataSource](https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/model/OracleDataSource.java)
- [JDBCURL#generateUrlByTemplate](https://github.com/dbeaver/dbeaver/blob/202ccc4d6dea869cb5ba50f7038af23659434d24/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/jdbc/JDBCURL.java#L50)

#### Steps to reproduce, if exist:

Input a custom URL with `{variable-name}` (e.g. `jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = {host})(PORT = {port}))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = {database})))`) for JDBC URL Template in Edit Connection dialog

It worked if using `
jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.23.57.7)(PORT=1522))(CONNECT_DATA=(SERVICE_NAME=orclcdb)))` without built-in basic variables.

**Comment by Matvey16** [comment]
@Fang3s Thank you for the report.

**Comment by Destrolaric** [comment]
@Fang3s Hi, can you look if the issue is still reproducible. A similar ticket was fixed https://github.com/dbeaver/dbeaver/issues/13654.
So the issue might be already solved.
P.S. We looked more into the issue, and it is still actual

**Comment by Matvey16** [comment]
Verified
