### ISSUE TITLE
Cancel current query shortcut

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#14579]
It would be very helpful and productive to have a keyboard shortcut for cancelling a current running query.

**Comment by Matvey16** [comment]
@yonisade Thank you for the suggestion

**Comment by ShadelessFox** [comment]
Implemented (no shortcut is assigned by default, but you can do it yourself):

![image](https://user-images.githubusercontent.com/35821147/159974737-c4eb60b6-f710-485c-8e3e-8d324456905a.png)

This action will terminate query running inside the active tab.

**Comment by uslss** [comment]
verified
