### ISSUE TITLE
Error "Object parameter [...] binding not supported" with IPv4 data type in ClickHouse

### ISSUE THREAD

**Issue by MAH69IK** [dbeaver/dbeaver#14576]
#### System information: 
- Linux Elementary
- DBeaver version 21.2.5

#### Connection specification:
- Driver name: ClickHouse
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
When try to delete row with IPv4 I receive error `Object parameter [<IP>] binding not supported`.

#### Steps to reproduce, if exist:
1. Create table: `CREATE TABLE dbeaver_IPv4_test (IP_address IPv4) ENGINE = MergeTree() ORDER BY IP_address;`;
2. Insert few values: `INSERT INTO dbeaver_IPv4_test (IP_address) VALUES ('127.0.0.1'), ('127.0.0.2'), ('8.8.8.8'), ('1.1.1.1');`;
3. Check:

```
SELECT * FROM dbeaver_IPv4_test;

SELECT *
FROM dbeaver_IPv4_test

Query id: dffd48f4-599f-46b6-b67e-c731ab87789d

┌─IP_address─┐
│ 1.1.1.1    │
│ 8.8.8.8    │
│ 127.0.0.1  │
│ 127.0.0.2  │
└────────────┘

4 rows in set. Elapsed: 0.002 sec.
```
4. Try to delete via dbeaver. Receive `Object parameter [8.8.8.8] binding not supported`;
5. Try via clickhouse console: `ALTER TABLE dbeaver_IPv4_test DELETE WHERE IP_address == IPv4StringToNum('8.8.8.8');`;
6. Check:

```
SELECT * FROM dbeaver_IPv4_test;

SELECT *
FROM dbeaver_IPv4_test

Query id: 5e45ccea-fb4e-4f70-9540-a3c7e7914fd3

┌─IP_address─┐
│ 1.1.1.1    │
│ 127.0.0.1  │
│ 127.0.0.2  │
└────────────┘

3 rows in set. Elapsed: 0.002 sec.
```

When I generate DELETE SQL for this table via dbeaver I receive this code:

```
ALTER TABLE dbeaver_IPv4_test DELETE 
WHERE IP_address=?;
```

Try to put value:

```
ALTER TABLE disworks.dbeaver_IPv4_test DELETE 
WHERE IP_address=IPv4StringToNum('127.0.0.2');
```

And this work. So maybe DBeaver don't use `IPv4StringToNum`?

---

IPv4 is new type based on UInt32 and maybe problem because values need convert from string to IPv4.

Describe of IPv4 type: https://clickhouse.com/docs/en/sql-reference/data-types/domains/ipv4/
Describe of function for working with IPv4: https://clickhouse.com/docs/en/sql-reference/functions/ip-address-functions/

**Comment by uslss** [comment]
thanks for the report

**Comment by zhicwu** [comment]
It works if you're using new driver(com.clickhouse.jdbc.ClickHouseDriver) in clickhouse-jdbc 0.3.2 or above. FYI, below query works as well:
```sql
-- below query will be translated to:
-- ALTER TABLE dbeaver_IPv4_test DELETE WHERE IP_address = IPv4StringToNum('8.8.8.8') settings mutations_sync=1 
delete from dbeaver_IPv4_test where IP_address = IPv4StringToNum('8.8.8.8')
```
