### ISSUE TITLE
Line Numbers for Text Results

### ISSUE THREAD

**Issue by jetzerb** [dbeaver/dbeaver#14589]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the results pane, the Grid-based presentation includes line numbers.  I'd like the option to include line numbers in the Text-based presentation as well:
![image](https://user-images.githubusercontent.com/36859020/142208502-940eb7a8-8950-4526-a56c-3d924648bb1e.png)

The text-presentation results would then look something like this:
![image](https://user-images.githubusercontent.com/36859020/142207122-0991d318-6a1a-4a1f-9f37-46675281d667.png)

**Describe alternatives you've considered**
Switching back and forth between grid & text presentation via ``CTRL+` `` to see the line number for a given row works for the first few rows in the result set, but not for later results since switching presentations jumps back to the top of the results.
Adding a `row_number()` column to each query is tedious and requires me to keep the `order by`s sync'd between the overall query and the window function.

**Additional context**
Grid presentation shows line numbers:
![image](https://user-images.githubusercontent.com/36859020/142206739-26aa5406-aca5-460e-a5e0-a8c1557e76b3.png)

Text presentation currently does not:
![image](https://user-images.githubusercontent.com/36859020/142206843-6a352cdb-b6ca-4984-8f73-cb8e18f0b356.png)

**Comment by LonwoLonwo** [comment]
@jetzerb 

Thanks for the idea!

**Comment by uslss** [comment]
line number values could be shown in the Value panel and incorrect values are shown in this case
![dbeaver_lhwiaoBXJo](https://user-images.githubusercontent.com/31996417/158559901-3c2d70e4-3f55-4438-b88e-dbf04b846efd.gif)

**Comment by uslss** [comment]
verified
