### ISSUE TITLE
[PostgreSQL] - Array incorrectly shown in record view

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#14594]
DBeaver 21.2.5 on Mac (PostgreSQL 13.5)

From the following screenshot you can see, that the first field (an array with null value) is not displayed correctly. It is displayed like an empty array showing length 0. But thats incorrect.

![image](https://user-images.githubusercontent.com/38714600/142280865-dd306972-6882-4e0d-a725-3f063a130a34.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/35821147/146011876-ade2fce7-4d23-4464-bc02-5507f8e099db.png)

**Comment by Matvey16** [comment]
Verified

New bug found in array presentation #14926

**Comment by krishnak-de** [comment]
<img width="854" alt="Screen Shot 2024-11-17 at 9 29 23 PM" src="https://github.com/user-attachments/assets/696ef680-bf24-4d14-a93f-61c2a54e6f17">

I'm using PostgreSQL DB in dbeaver editor. After executing the query, the output shows the array structure but without any data in the array. Is there any configurations to be done in dbeaver or a PostgreSQL issue as 11/17/24?

**Comment by ShadelessFox** [comment]
@krishnak-de please fill in a new bug report
