### ISSUE TITLE
Can't see text in dbeaver after last upgrade, mac pro 2019, bigsur 

### ISSUE THREAD

**Issue by nachum-shmilovitz** [dbeaver/dbeaver#14603]
See what happened after the last upgrade
i am working with mac, Big sur OS in dark mode 
moving to light mode , make things better when removing the using theme oprion 

![image](https://user-images.githubusercontent.com/45429821/142400657-a183f572-362f-4e9f-b74e-cbbf07b51375.png)

![image](https://user-images.githubusercontent.com/45429821/142400784-4e0108c6-2902-4fa2-88fe-18b641b82b54.png)

**Comment by Matvey16** [comment]
It is a known issue. We are working on it, but the workarounds can found in original ticket #13968
