### ISSUE TITLE
Update status icons

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#14608]
We need to replace legacy Eclipse status icons with new ones.

New icons: SMALL_ERROR, SMALL_WARNING, SMALL_QUESTION and SMALL_INFO

**Comment by Mazino-Urek** [comment]
Hello, I would like help with icons of `dbeaver`, if required. I have some experience in this field.

**Comment by ShadelessFox** [comment]
Hello @nowshed-imran,

Thanks for reaching out! In fact, we do have required icons already, we just need to make use of them. See bb26dc2

**Comment by Matvey16** [comment]
Old icon in export task
![image](https://user-images.githubusercontent.com/82543000/143236832-b3a79d2c-c1d1-4162-901c-ce07ba5d1bb2.png)

**Comment by Destrolaric** [comment]
I am not sure what changing icons in MultiPageWizard errors is possible without significant amount of code, it is inherited directly from eclipse jface dialogs, where icon images are hardcoded and work with . 
P.S. Well this probably will look bad but reflection allows to change icons

**Comment by Destrolaric** [comment]
@Matvey16 This change will be another issue ticket due to different solution used to add icons

**Comment by Matvey16** [comment]
Verified
