### ISSUE TITLE
Attribute quoting error in filter

### ISSUE THREAD

**Issue by plmmihail** [dbeaver/dbeaver#14618]
#### System information: 
- Operating system (distribution) and version
Linux. The same on Fedora, Mint, Ubuntu

- DBeaver version
21.2.4

- Additional extensions
 No

#### Connection specification:
- Database name and version
Oracle 10 **_Maybe other DBs affected._**

- Driver name
Standard, artifact  from maven

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
DBeaver doesn't quote attribute name by filtering.

![изображение](https://user-images.githubusercontent.com/75296351/142610911-3bc28f47-091a-49c4-b21e-2f8e1f493970.png)

#### Steps to reproduce, if exist:

There is a table with fields (attributes) "КодДСЕ" and "Вариант" (multicase). Try to filter from header with some value.

**Comment by LonwoLonwo** [comment]
Hello @plmmihail 

Thanks for the bug report.

As I can see, it works fine to apply filter criteria in the table data editor.

![2021-11-19 17_21_25-DBeaver Ultimate 21 2 5 - TEST_QUOTES](https://user-images.githubusercontent.com/45152336/142638274-09225174-0a2c-48ab-bb0c-4e65349527fd.png)

And also works fine if I use select * from, not specific column names in a query in the SQL Editor.

But it fails with specific column names.
Another question.
Is data marked as read-only in your Resalt Set as in mine? (yellow lock in the left corner)

![2021-11-19 17_22_02-DBeaver Ultimate 21 2 5 - _orcl_Script-89](https://user-images.githubusercontent.com/45152336/142638458-4a0f094d-7f7e-4ed1-b1de-1cff550fa274.png)

**Comment by plmmihail** [comment]
Thanks for examples and review, @LonwoLonwo!
1. In my case there is no filtering from table as object of the main object tree. I have filtered a result of query.
There is difference between something like
`SELECT '*', SYSDATE ,k.*  FROM t1 k `
(**correct quoting**)
and
```
SELECT '*', SYSDATE ,k.*  FROM t1 k 
UNION ALL 
SELECT * FROM t2
```
I think, there is a problem in DBeaver's query analytic functions.
2. Yes, ResultSet have a lock sign in my case
![изображение](https://user-images.githubusercontent.com/75296351/142870371-33bc7357-1684-42d8-bc7a-397a8ca6d1b0.png)

**Comment by LonwoLonwo** [comment]
Fixed.

![2021-12-28 18_39_39-DBeaver Ultimate 21 3 2 - _orcl_ Script-42](https://user-images.githubusercontent.com/45152336/147582715-538f3cfe-f1e0-44dc-940c-73723ed15582.png)

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
NPE when column is filtered while being selected using aliased table name

![image](https://user-images.githubusercontent.com/82543000/147743602-b15504d4-cd56-4916-a83f-588e27ae9173.png)

**Comment by LonwoLonwo** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
