### ISSUE TITLE
Version upgrade on M1 (aarch64) beta build installs Intel version instead of arm

### ISSUE THREAD

**Issue by stogdan** [dbeaver/dbeaver#14613]
#### System information: 
- Operating system (distribution) and version: macOS 12.0.1 Monterey
- DBeaver version: 21.2.4 (aarch64) M1 Beta
- Additional extensions: none

#### Connection specification:
- Database name and version: Not relevant
- Driver name: Not relevant
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Steps to reproduce, if exist:

1. Install DBeaver 21.2.4 aarch64 M1 beta
2. Start DBeaver
3. From file menu -> Help -> Check for Updates
4. 21.2.5 is available as of Nov 18 2021. Choose Upgrade.
5. Close DBeaver and install update
6. Get Info on Downloaded file show Intel application:
![image](https://user-images.githubusercontent.com/10165294/142500195-48ff385e-f3f7-4027-beb9-fee60fcfe094.png)

DBeaver download the latest-macos.dmg package. I dont know if you will someday make the application Universal or not, but I guess it will need to download a similar latest-macos.dmg for aarch64 if they are to be maintained separately.

**Comment by ShadelessFox** [comment]
Hello @stogdan,

Thanks for report.

**Comment by Matvey16** [comment]
Verified
