### ISSUE TITLE
Add option to omit object comments when retrieving object metadata for Vertica database objects

### ISSUE THREAD

**Issue by bitadmiral** [dbeaver/dbeaver#14625]
Hi, I recently upgraded from DBeaver 4 to 21.2.4.202111011413, and find the UI to be very slow and even unresponsive compared to the older version.  I believe it has to do with the fact that the modern DBeaver gathers much more metadata on the database objects (which is nice).  I've traced the problem to background queries that retrieve object metadata, specifically any query that involves Vertica's **comments** system view.   In our databases, any query on the **comments** view takes a number of minutes to complete.  Such queries are executed in the background by DBeaver often, including for autocompletion or exploring objects in the Database Navigator.

We actually don't use object comments at all.  But even a query that attempts to retrieve a single row from the **comments** view takes many minutes.  It is because that system view is extremely complex, with many joins, unions, subqueries on other views, etc.  This causes strange behaviors in DBeaver, such as popup dialogs popping up at seemingly random times, long waits for auto-completion, and temporary freezes in the UI.

The problem is detailed in my post in the Vertica forum here:  [Querying v_catalog.comments is very slow even with no results](https://forum.vertica.com/discussion/242480/querying-v-catalog-comments-is-very-slow-even-with-no-results)

I'm wondering if there is a way to disable retrieval of object comments from the Vertica database completely.  Or, maybe it would be possible to add an option to disable retrieval of object comments, and eliminate all references to the **comments** view in all background queries.

BTW, this is somewhat related to an old issue:  #3474

_Originally posted by @verticauser810 in https://github.com/dbeaver/dbeaver/discussions/14611_

**Comment by LonwoLonwo** [comment]
Vertica tables, views, columns comments will be cached lazy. Start the DBeaver version 22.0.1

This means that reading comments in tables/views and columns will only take place when opening specific tables, and not when reading the list of tables, as it was before. So we could remove expensive JOIN on the `v_catalog.comments` table.
We have already done this for the Oracle database.

On our test databases, such a solution has already shown performance improvement. We will hope that for other users, performance will also increase enormously.

![EcRexICmjl](https://user-images.githubusercontent.com/45152336/157721446-a79149e4-d28c-4a32-8f22-9587c1924199.gif)

**Comment by LonwoLonwo** [comment]
For testers: please, check tables, views, system tables, and flex tables. You can not comment views columns in Vertica (check it also).

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
Hello @verticauser810 

Please test Vertica table loading perfomance in our [Early Access](https://dbeaver.io/files/ea/) version if you are using Windows. It will be very helpfull for us.

**Comment by bitadmiral** [comment]
Hi Dbeaver Team,

I tested DBeaver EA version 22.0.1 and I'm very pleased with the results.

In the new version, it took under 5 seconds to expand the Tables node in the schema explorer.  In older version 21.2.4, the exact same operation (identically configured connection, expanding Tables node under the same schema, it took 5 minutes!  This is a vast improvement.

Thank you very much!  I really like the way you solved this problem.
Sincerely,
--Joe

**Comment by bitadmiral** [comment]
I also tested auto-completion in the SQL editor...

The DB user I'm testing with has access to a large number of schemas.  I tried performing auto-completion in the SQL editor on a table without qualifying it with the schema name, and it returned proposals within a few seconds in the new 22.0.1 version.  The exact same operation in older DBeaver took well over three minutes.

`SELECT * FROM TrxLine` [Ctrl-Space]

**Comment by bitadmiral** [comment]
One small thing I've noticed is some strange behavior with auto-completion.  Sometimes it interpolates the selected proposal incorrectly.  For example, here are the proposals:

![image](https://user-images.githubusercontent.com/94631506/158885723-09e7e344-346d-4727-a444-a3f1b4af1d90.png)

Result after hitting Enter:
`SELECT * FROM prodarch3_stage.TrxLine ne`

In this case it added the wrong alias.  I have seen other times where it interpolates the selected proposal in a way that makes the resulting SQL invalid, for example:

![image](https://user-images.githubusercontent.com/94631506/158886539-7adc5e6a-e278-4081-9cf6-804024bbcb45.png)

Result after double-clicking on first selection:
`SELECT * FROM prodarch3_stage.TrxLine ne.`

**Comment by LonwoLonwo** [comment]
Thanks for the investigation and the answer @verticauser810 

I will look into the `strange behavior with the auto-completion` issue.

**Comment by dabocla** [comment]
I am on a mac, but I am excited to see the new version that's released.  I love the idea of pulling comments until requested.  All I care a bout is a quick list of tables / columns so that auto complete will work more effectively.  Your change looks promising.

**Comment by alattke-chwy** [comment]
This query is being executed for Vertica:
```
select object_type, "comment", child_object from v_catalog.comments where object_schema ='MYSCHEMA' and object_name ='MYTABLE'
```
We don't use comments at all, and just running this query takes 14s in our (non-busy) test env. In production it can take more than 60s, and puts quite a bit of stress on the cluster. Can you please introduce a way to disable comments altogether?
