### ISSUE TITLE
"DataSourceEditorInput cannot be cast to class" error when trying to rename an object

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#14626]
#### System information: 
- Operating system (distribution) and version: Windows 10 64 bit
- DBeaver version: 21.2.4.202111011413
- Java version: 1.8

#### Connection specification:
- Database name and version: MySQL v8.0.27
- Driver name: MySQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Sometimes when I try to rename a table in Database navigator I get this error:

`
Can't rename object 'my_table'

Reason:
class org.jkiss.dbeaver.tasks.ui.DataSourceToolsContributor$DataSourceEditorInput cannot be cast to class org.jkiss.dbeaver.ui.editors.IDatabaseEditorInput (org.jkiss.dbeaver.tasks.ui.DataSourceToolsContributor$DataSourceEditorInput is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @e56b588; org.jkiss.dbeaver.ui.editors.IDatabaseEditorInput is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @33b2ba25)
`

It happens after keeping DBeaver open for a long idle time.

## Workround:
Restart DBeaver and do the action again.

**Comment by uslss** [comment]
@yonisade sorry for the late response. unfortunately, cannot reproduce an issue. 
Could you provide a [full error log](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by uslss** [comment]
There has been no update on the issue for a long time.
If it is still present, feel free to reopen it.

**Comment by bilik** [comment]
I have the same problem. When rename:

Reason:
class org.jkiss.dbeaver.tasks.ui.DataSourceToolsContributor$DataSourceEditorInput cannot be cast to class org.jkiss.dbeaver.ui.editors.IDatabaseEditorInput (org.jkiss.dbeaver.tasks.ui.DataSourceToolsContributor$DataSourceEditorInput is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1dfa40f8; org.jkiss.dbeaver.ui.editors.IDatabaseEditorInput is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6e5fba90)
