### ISSUE TITLE
Find local clients on Linux & macOS under AArch64

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#14620]
We already do that on Windows and [macOS on x86_64](https://github.com/dbeaver/dbeaver/issues/7976). Now it's time to do the same on Linux and on macOS under AArch64.

It's a standard practice to add a symlink to `/usr/bin/` for pretty much all the binaries that we need to find. Using such symlinks, we can discover the location of local clients. We can also try to locate something in such folders as `/etc/alternatives/`.

**Comment by ianchanning** [comment]
Useful relevant comment from the Mac native client thread: https://github.com/dbeaver/dbeaver/issues/7976#issuecomment-725436879

**Comment by sekroots** [comment]
Hello. I am trying to use dbeaver to backup a postgres 12 but I cannot use it.

I configured local client to /usr/bin and it automatic loaded it ( /run/user/1000/doc/6f337d65/bin ) but It failed to use it.

HOW CAN I  SOLVE THIS MESS PLEASE?

**Comment by flambchap** [comment]
Hello @sekroots. I'm sorry to hear that. Could you provide a little bit more information about your issue?

- What distro do you use? What version?
- What packaging of DBeaver do you use?

**Comment by sekroots** [comment]
Sure @n5a5 , here it is:

My server runs postgres 12.3 ( docker image: postgres:12.3 )

My computer:

- Ubuntu 22.04.3 LTS;
- Version 23.2.5.202311191730
- ricardo@ikigai:/run/user/1000/doc/6f337d65/bin$ dpkg  --list|grep postgres
ii  postgresql                                 14+238                                  all          object-relational SQL database (supported version)
ii  postgresql-14                              14.9-0ubuntu0.22.04.1                   amd64        The World's Most Advanced Open Source Relational Database
ii  postgresql-client-12                       12.17-1.pgdg22.04+1                     amd64        front-end programs for PostgreSQL 12
ii  postgresql-client-14                       14.9-0ubuntu0.22.04.1                   amd64        front-end programs for PostgreSQL 14
ii  postgresql-client-common                   238                                     all          manager for multiple PostgreSQL client versions
ii  postgresql-common                          238                                     all          PostgreSQL database-cluster manager
ricardo@ikigai:/run/user/1000/doc/6f337d65/bin$

**Comment by flambchap** [comment]
@sekroots How did you install DBeaver (deb, snap, tar.gz, etc)?

**Comment by flambchap** [comment]
Also, can you please run the following command on your Ubuntu?

```shell
find / -name "pg_dump" 2> /dev/null
```

**Comment by sekroots** [comment]
Sure. It's from snap, long time ago.

ricardo@ikigai:/run/user/1000/doc/6f337d65/bin$ find / -name "pg_dump" 2> /dev/null
/run/user/1000/doc/by-app/snap.dbeaver-ce/6f337d65/bin/pg_dump
/run/user/1000/doc/by-app/snap.dbeaver-ce/f9dbdc5b/bin/pg_dump
/run/user/1000/doc/6f337d65/bin/pg_dump
/run/user/1000/doc/f9dbdc5b/bin/pg_dump
/snap/dbeaver-ce/268/usr/bin/pg_dump
/snap/dbeaver-ce/270/usr/bin/pg_dump
/usr/lib/postgresql/12/bin/pg_dump
/usr/lib/postgresql/14/bin/pg_dump
/usr/bin/pg_dump
ricardo@ikigai:/run/user/1000/doc/6f337d65/bin$ 

My last try was install postgres-client-12, I configured  dbeaver native client to /usr/lib/postgres/12/bin but when I try to perform backup this happens: 

```
2023-11-24 13:29:46.425 - IO error: Cannot run program "/run/user/1000/doc/4a676630/bin/pg_dump" (in directory "/run/user/1000/doc/4a676630/bin"): error=13, Permission denied
2023-11-24 13:29:46.425 - java.io.IOException: Cannot run program "/run/user/1000/doc/4a676630/bin/pg_dump" (in directory "/run/user/1000/doc/4a676630/bin"): error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:226)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 7 more
```

ricardo@ikigai:/run/user/1000/doc/4a676630/bin$ ./pg_dump -V
pg_dump (PostgreSQL) 12.17 (Ubuntu 12.17-1.pgdg22.04+1)
ricardo@ikigai:/run/user/1000/doc/4a676630/bin$ pwd
/run/user/1000/doc/4a676630/bin
ricardo@ikigai:/run/user/1000/doc/4a676630/bin$

**Comment by sekroots** [comment]
Hello.
 Can anyone help me to fix it to perfom a  backup/dump please?

**Comment by sekroots** [comment]
?

**Comment by flambchap** [comment]
@sekroots I'm sorry, I was sidetracked by other issues. Unfortunately, it's a problem with the snap package. I suggest trying a deb/rpm/tarball/flatpak and see if it helps.

**Comment by ianchanning** [comment]
Yep the https://flathub.org/en-GB/apps/io.dbeaver.DBeaverCommunity works great
