### ISSUE TITLE
Crash when query result include binary data

### ISSUE THREAD

**Issue by lkebin** [dbeaver/dbeaver#14628]
#### System information: 
- Operating system (distribution) and version
   macOS 12.0.1 (21A559) Apple M1
- DBeaver version
   Version 21.2.5.202111141807
- Additional extensions
   No

#### Connection specification:
- Database name and version
   MySQL 8.0.25
- Driver name
   MySQL Connector/J [mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec)])
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
   No

#### Describe the problem you're observing:

Application crash when query result include binary data

#### Steps to reproduce, if exist:

```sql
create table if not exists test_bin(
	id binary(16) not null,
	primary key(id)
);

insert into test_bin(id) values(uuid_to_bin(uuid(), true));

select id from test_bin;
```

#### Include any warning/errors/backtraces from the logs

dbeaver-debug.log
....
2021-11-22 13:05:55.366 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
> Start DBeaver UI Editors - Hex [org.jkiss.dbeaver.ui.editors.hex 1.0.69.202111141807]
> Start DBeaver UI Editors - image [org.jkiss.dbeaver.ui.editors.image 1.0.69.202111141807]
2021-11-22 13:07:23.955 - Can't detect image type: Unsupported or unrecognized format
> Start DBeaver UI Editors - JSON [org.jkiss.dbeaver.ui.editors.json 1.0.53.202111141807]
> Start DBeaver UI Editors - XML [org.jkiss.dbeaver.ui.editors.xml 1.0.69.202111141807]

**Comment by uslss** [comment]
@lkebin unfortunately, cannot reproduce it. does dbeaver crash on select execution? Could you provide [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files)? Video with the issue also will be very helpful
![image](https://user-images.githubusercontent.com/31996417/142828443-b4f52d57-6878-4aa3-b004-1ced7ef6c09b.png)

**Comment by lkebin** [comment]
Seems it's working with no crash now. 

I didn't find anymore logs when crash, will capture a video when crash appears again.

Thanks
