### ISSUE TITLE
Name of the General project doesn't change in the bottom toolbar

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#14634]
#### System information: 
- Operating system (distribution) and version Win 11
- DBeaver version 21.2.5 CE

#### Steps to reproduce, if exist:
1. Rename the General project
2. In the Projects tab, select this project
3. Take a look at the left bottom corner of DBeaver window

![image](https://user-images.githubusercontent.com/26031301/142837652-1219e7d6-0e8c-4b97-8859-f4f92bab8473.png)

**Comment by ShadelessFox** [comment]
Project rename is broken for the active project.
