### ISSUE TITLE
[PostgreSQL 14] Support of multirange data types.

### ISSUE THREAD

**Issue by Destrolaric** [dbeaver/dbeaver#14639]
#### System information: 
- Windows 10 
- Devel Branch(last commit 14548 SQL Server data types read fix)

#### Connection specification:
- PostgreSQL 14
- PostgreSQL JDBC Driver
- SSH
#### Describe the problem you're observing:
When trying to connect we get this error in debug log.
`No enum constant org.jkiss.dbeaver.ext.postgresql.model.PostgreTypeType.m`

#### Steps to reproduce, if exist:
Open our PostgreSQL 14 and see error in debug mode

**Comment by LonwoLonwo** [comment]
https://www.postgresql.org/docs/current/catalog-pg-type.html

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by LonwoLonwo** [comment]
New Multirange type can be tested with multirange types.

![2021-11-23 19_19_11-Window](https://user-images.githubusercontent.com/45152336/143062798-a537483c-00b5-46fb-846c-b0116de30676.png)

![2021-11-23 19_19_30-Window](https://user-images.githubusercontent.com/45152336/143062801-934fa66e-30fa-4d0e-9d88-80b8dc76cbf4.png)

**Comment by uslss** [comment]
verified
