### ISSUE TITLE
Tables within ER Diagram can not be rearranged by hand

### ISSUE THREAD

**Issue by glw** [dbeaver/dbeaver#14647]
#### System information: 
- Operating system (distribution) and version - Ubuntu Xenial
- DBeaver version -   DBeaver	21.2.5.202111141807
- Additional extensions

#### Connection specification:
- Database name and version - Postgresql 10
- Driver name - Java - org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Within an ER Diagram you are unable to manually move the tables around within the window. Additionally resizing the window are which presents the table info does not work.

#### Steps to reproduce, if exist:
Open Schema, Switch to ER Diagram tab, select a table and attempt to re-arrange manually

**Comment by ShadelessFox** [comment]
Hello @glw,

Thanks for report. 

It looks like it's Linux-specific problem. Can you send a video showing the problem?

**Comment by glw** [comment]
Here you go. Let me know if you need any more details.

![dbeaver_erdiagram_bug](https://user-images.githubusercontent.com/556205/143655574-ba7372e6-6a37-4b04-8038-e858bdea2f3a.gif)

**Comment by ShadelessFox** [comment]
I see, thanks!

**Comment by Destrolaric** [comment]
@glw Hi, are this issue still active in the new versions of DBeaver?

**Comment by glw** [comment]
Sorry just saw this. I will check right now.

**Comment by glw** [comment]
Testing version: Version 22.0.5.202205220912

Unfortunately, the dragging/moving of table objects on the ERD is still not working.  I am able to select and open the table properties or a columns properties from the ERD.

**Comment by Destrolaric** [comment]
Hi, can you send the log file? Instructions can be found here https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by glw** [comment]
Actually when I try to export a log it gives me this error.

```
Unhandled event loop exception
No more handles 
```

![image](https://user-images.githubusercontent.com/556205/170143855-f940acbb-30b7-4594-9bc1-e84984daaee6.png)


Ill try to find the log files on my computer

**Comment by glw** [comment]
Here's my log file.

[log.txt](https://github.com/dbeaver/dbeaver/files/8929591/log.txt)

**Comment by emironovDB** [comment]
Hi, @glw !

Did you try to install the last version of [DBeaver 22.1.0](https://dbeaver.io/2022/06/05/dbeaver-22-1/)?

**Comment by glw** [comment]
@emironovDB I am currently at DBeaver 22.1.0.202206051253

**Comment by Destrolaric** [comment]
@glw Hi, sorry for waiting. Are you sure that logs are the actual ones? By the shown date, it looks like they were written in 2019.

**Comment by glw** [comment]
@Destrolaric oh sorry i didnt notice that. If i recall correctly I believe I found the ```.dbeaver``` folder in my home directory - and just assumed it must be the correct log since I was unable to find other directories.

When I went here https://github.com/dbeaver/dbeaver/wiki/Log-files I had no directories in the suggested location for linux

I will do a triple check for other dbeaver related directories.

If i dont find anything, would you recommend just doing a complete uninstall and reinstall at this point?

**Comment by Destrolaric** [comment]
@glw Yes, this may help to resolve the issue.

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If the issue is still actual for you, feel free to reopen it.
