### ISSUE TITLE
How to connect to the database using mycat2

### ISSUE THREAD

**Issue by EarthXuan** [dbeaver/dbeaver#14646]
System information:
Operating system (distribution) and version: Win10
DBeaver version: 21.2.4 by Community
Connection specification:
Database name and version: MySQL8 by using myact2
Describe your question:
use mysql driver to connect,but it doesn't work.
return this err:
**No enum constant org.jkiss.dbeaver.ext.mysql.model.MySQLEngine.Support.DRFAULT**

So,i want to know how to connect to mycat by using dbeaver.

**Comment by LonwoLonwo** [comment]
Hello @EarthXuan 

Can you show the result of "SHOW ENGINES" for your MySQL mycat2, please? If you can use another tool for it.

**Comment by LonwoLonwo** [comment]
Oh, I see the problem.
Do you use this MyCat2 https://github.com/MyCATApache/Mycat2 ?

**Comment by EarthXuan** [comment]
> Oh, I see the problem. Do you use this MyCat2 https://github.com/MyCATApache/Mycat2 ?

yes

**Comment by LonwoLonwo** [comment]
So then this is the MyCat2 problem, unfortunately. 
You can see the list of acceptable answers on the "SHOW ENGINES" query: https://dev.mysql.com/doc/refman/8.0/en/show-engines.html
There is a `DEFAULT` answer, but not `DRFAULT`.

**Comment by LonwoLonwo** [comment]
I created the issue on the Mycat2 board: https://github.com/MyCATApache/Mycat2/issues/606
Let's hope that it will help.

**Comment by EarthXuan** [comment]
> I created the issue on the Mycat2 board: [MyCATApache/Mycat2#606](https://github.com/MyCATApache/Mycat2/issues/606) Let's hope that it will help.

ok,thanks for your help~

> I created the issue on the Mycat2 board: [MyCATApache/Mycat2#606](https://github.com/MyCATApache/Mycat2/issues/606) Let's hope that it will help.

ok,thanks for your help~
