### ISSUE TITLE
Switch Tabs 

### ISSUE THREAD

**Issue by JuanLH** [dbeaver/dbeaver#14660]
**Is your feature request related to a problem? Please describe.**
I am used to changing tabs with Ctrl + Tab or Ctrl + Shift + Tab to switch to previous tab.

**Describe the solution you'd like**
Set a shortcut to change open tabs. 
[Ctrl + Tab] for switch fordward
[Ctrl + Shift + Tab] for switch backward

**Comment by ShadelessFox** [comment]
Hello @JuanLH,

We do have shortcuts for that: <kbd>Ctrl</kbd>+<kbd>PageDown</kbd> and <kbd>Ctrl</kbd>+<kbd>PageUp</kbd>. 

You can rebind them to any other shortcuts in <kbd>Preferences</kbd> &rArr; <kbd>User Interface</kbd> &rArr; <kbd>Keys</kbd>.
