### ISSUE TITLE
Jump server private key path not retained

### ISSUE THREAD

**Issue by amchurchill** [dbeaver/dbeaver#14663]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro, build 19043
- DBeaver version: 21.2.3.202110151816
- Java version: 11.0.12+7
- Additional extensions: none

#### Connection specification:
- Database name and version
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes, SSH with multiple hops

#### Describe the problem you're observing:
The "Private Key" field in the "Jump server settings" does not retain its value when the "Edit Connection" window is reopened. If the paths are set correctly, the connection will work, but as soon as the connection is edited again, the path for the jump key is reset to that of the tunnel key.

#### Steps to reproduce, if exist:
1. Right click on an existing connection, selecting "Edit Connection"
2. Set path to private keys for the tunnel and the jump server to different values.
3. Press "OK" to exit the "Edit Connection" window.
4. Right click on an existing connection, selecting "Edit Connection" again. The private key path under the jump server settings now has the same value as the tunnel

**Comment by Matvey16** [comment]
@amchurchill Thank you for the report

**Comment by Matvey16** [comment]
Verified
