### ISSUE TITLE
Declare display error when view contains comments

### ISSUE THREAD

**Issue by ReconditenessPerson** [dbeaver/dbeaver#14664]
System information: 
Operating system (distribution) and version : Windows 11 pro 21H2  22000.348
DBeaver version 21.2.5.202111141807
Additional extensions  NO
Connection specification: routine service Name
Database name and version Oracle 11G
Driver name  oracle.jdbc.OracleDriver
Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO
Describe the problem you're observing:
When comments appear in the sub query in the view, the display will make an error when viewing the view
As shown in the figure, the red box indicates the desired Navicat effect on the right
![image](https://user-images.githubusercontent.com/46001036/143182432-1b6ffc3a-0de7-4e08-8beb-c144f5d19886.png)

Steps to reproduce, if exist:
Include any warning/errors/backtraces from the logs

**Comment by Matvey16** [comment]
@ReconditenessPerson  I was not able to reproduce it, can you please provide a basic DDL of a view for which this issue appears

**Comment by ReconditenessPerson** [comment]
> @ReconditenessPerson I was not able to reproduce it, can you please provide a basic DDL of a view for which this issue appears

CREATE OR REPLACE FORCE VIEW "oracle"."V_PM_IN_CONTRACTRECEIVABLE" ("FID", "VERSION", "FYEAR", "FMONTH", "FREPORTPERIOD", "FBILLDATE", "FPROJECTID", "FPROJECTNAME", "FPROJECTCODE", "FREFORGFID", "FCONTRACTCODE", "FCONTRACTID", "FCONTRACTNAME", "FCONTRACTRECNO", "FPAYMENTTYPE", "FGUARANTEERATIO", "FLASTRECEIVEDATE", "FCONTRACTAGREERATIO", "FBUILDPROGRESS", "FREMARK", "FATTACHMENT", "FSETTLEMENTID", "FBIZSTATE", "FBIZSTATENAME", "FCREATETIME", "FCREATEPSNFID", "FCREATEPSNFNAME", "FTS", "FRECORDNO", "FRECORDDATE", "FVALUEADDEDTAXRATE", "FREPORTMODE", "FTITLE", "FLATESTCOLLECTIONTIME", "FCONTRACTAGREEPERIOD", "FREPORTNUMBER", "FPERIODID", "FPAYMENTMETHOD", "FISPAYMENTNODE", "FCONTRACTAGREEDAMOUNT", "FREPORTINGTYPE", "FAPPLYDATE", "FAPPROVEDATE", "FTEMPLATENAME", "FSTATE", "FATTACHMENTCN", "FCREATEDEPTID", "FSPLITCONTRACTID", "FTABLETYPE", "FCURRENTREPORTINGAMOUNT", "FADDUPREPORTINGAMOUNT", "FCURRENTAPPROVALNOTAXAMOUNT", "FCURRENTAPPROVALTAXVALUEAMOUNT", "FCURRENTAPPROVALTAXAMOUNT", "FADDUPAPPROVALNOTAXAMOUNT", "FADDUPAPPROVALTAXVALUEAMOUNT", "FADDUPAPPROVALTAXAMOUNT", "FCLOSINGUPPERIODTOTALTAX", "FCURRENTPERIODTAX", "FDEADLINETOTALTAX", "FDEADLINETOTALTAXYS") AS 
<details>
SELECT
	PM_IN_ContractReceivable.FID,
	PM_IN_ContractReceivable.VERSION,
	PM_IN_ContractReceivable.FYEAR,
	PM_IN_ContractReceivable.FMONTH,
	PM_IN_ContractReceivable.FREPORTPERIOD,
	PM_IN_ContractReceivable.FBILLDATE,
	PM_IN_ContractReceivable.FPROJECTID,
	PM_IN_ContractReceivable.FPROJECTNAME,
	PM_IN_ContractReceivable.FPROJECTCODE,
	PR.fRefOrgFID,
	PM_IN_ContractReceivable.FCONTRACTCODE,
	PM_IN_ContractReceivable.FCONTRACTID,
	PM_IN_ContractReceivable.FCONTRACTNAME,
	PM_IN_ContractReceivable.FCONTRACTRECNO,
	PM_IN_ContractReceivable.FPAYMENTTYPE,
	PM_IN_ContractReceivable.FGUARANTEERATIO,
	PM_IN_ContractReceivable.FLASTRECEIVEDATE,
	PM_IN_ContractReceivable.FCONTRACTAGREERATIO,
	PM_IN_ContractReceivable.fBuildProgress,
	PM_IN_ContractReceivable.FREMARK,
	PM_IN_ContractReceivable.FATTACHMENT,
	PM_IN_ContractReceivable.FSETTLEMENTID,
	PM_IN_ContractReceivable.FBIZSTATE,
	PM_IN_ContractReceivable.FBIZSTATENAME,
	PM_IN_ContractReceivable.FCREATETIME,
	PM_IN_ContractReceivable.FCREATEPSNFID,
	PM_IN_ContractReceivable.FCREATEPSNFNAME,
	PM_IN_ContractReceivable.FTS,
	PM_IN_ContractReceivable.fRecordNo,
	PM_IN_ContractReceivable.fRecordDate,
	PM_IN_ContractReceivable.fValueaddedTaxRate,
	PM_IN_ContractReceivable.fReportMode,
	PM_IN_ContractReceivable.fTitle,
	PM_IN_ContractReceivable.fLatestCollectionTime,
	PM_IN_ContractReceivable.fContractAgreePeriod,
	PM_IN_ContractReceivable.fReportNumber,
	PM_IN_ContractReceivable.fPeriodID,
	PM_IN_ContractReceivable.fPaymentMethod,
	PM_IN_ContractReceivable.fISPaymentNode,
	PM_IN_ContractReceivable.fContractAgreedAmount,
	PM_IN_ContractReceivable.fReportingType,
	PM_IN_ContractReceivable.fApplyDate,
	PM_IN_ContractReceivable.fApproveDate,
	PM_IN_ContractReceivable.fTemplateName,
	PM_IN_ContractReceivable.fState,
	PM_IN_ContractReceivable.fAttachmentCN,
	PM_IN_ContractReceivable.FCREATEDEPTID,
	PM_IN_ContractReceivable.fSplitContractID,
	PM_IN_ContractReceivable.fTableType,
	--当期申报额
	PM_IN_ContractReceivable.fCurrentReportingAmount,
	--累计申报额（含税）
	PM_IN_ContractReceivable.fAddUpReportingAmount,
	--当期-审批总金额（不含税）
	PM_IN_ContractReceivable.fCurrentApprovalNoTaxAmount,
	--当期-增值税额
	PM_IN_ContractReceivable.fCurrentApprovalTaxValueAmount,
	--当期-审批总金额（含税）
	PM_IN_ContractReceivable.fCurrentApprovalTaxAmount,
	--累计-审批总金额（不含税）
	PM_IN_ContractReceivable.fAddUpApprovalNoTaxAmount,
	--累计-增值税额
	PM_IN_ContractReceivable.fAddUpApprovalTaxValueAmount,
	--累计-审批总金额（含税）
	PM_IN_ContractReceivable.fAddUpApprovalTaxAmount,
	--应收-截止上期含税总金额                   
	PM_IN_CONTRACTRECEIVABLEDETAIL.FCLOSINGUPPERIODTOTALTAX,
	--应收-本期含税总金额
	PM_IN_CONTRACTRECEIVABLEDETAIL.FCURRENTPERIODTAX,
	--应收-截止本期含税总金额
	PM_IN_CONTRACTRECEIVABLEDETAIL.FDEADLINETOTALTAX,
	--合同约定收款比例
	PM_IN_CONTRACTRECEIVABLEDETAIL.FDEADLINETOTALTAXYS
FROM
	(
SELECT
	fid,
--版本
	version,
--年份
	fYear,
--月份
	case when length(fMonth) = 1 then '0' || fMonth else fMonth end as fMonth,
--报量期间
	fReportPeriod,
--单据日期
	fBillDate,
--项目ID
	fProjectID,
--项目名称
	fProjectName,
--项目编码
	fProjectCode,
--合同编号
	fContractCode,
--合同ID
	fContractID,
--合同名称
	fContractName,
--合同应收款单编号
	fContractRecNo,
	--收款方式
	fPaymentType,
--保修金比例
	fGuaranteeRatio,
--合同最晚收款时间
	fLastReceiveDate,
--合同约定收款比例
	fContractAgreeRatio,
	--施工进度
	fBuildProgress,
--备注
	fRemark,
--附件
	fAttachment,
--结算ID
	fSettlementID,
--流程状态名称
	fBizState,
	fBizStateName,
--创建时间
	fCreateTime,
--提交人员FullID
	fCreatePsnFID,
--提交人员FullName
	fCreatePsnFName,
--修改时间戳（最后修改时间）
	fTS,
	--单据编号
	'' as fRecordNo,
	--单据日期
	null as fRecordDate,
	--增值税率
	null as fValueaddedTaxRate,
	--报量方式
	'' as fReportMode,
	--单据名称
	'' as fTitle,
	--合同最晚收款时间
	null as fLatestCollectionTime,
	--合同约定收款期限（日历天）
	null as fContractAgreePeriod,
	--报量编号
	'' as fReportNumber,
	--月度报量ID
	'' as fPeriodID,
	--付款方式
	'' as fPaymentMethod,
	--是否付款节点
	'' as fISPaymentNode,
	--合同约定当期应收款金额
	null as fContractAgreedAmount,
	--报量类型
	'' as fReportingType,
	--申报日期
	null as fApplyDate,
	--审批日期
	null as fApproveDate,
	--模板名称
	'' as fTemplateName,
	--状态
	fBizStateName as fState,
	--合同收款单附件
	null as fAttachmentCN,
	--提交部门ID
	'' as FCREATEDEPTID,
	--拆分合同ID
	'' as fSplitContractID,
	--当期申报额
	0 as fCurrentReportingAmount,
	--累计申报额（含税）
	(select sum(MM.fCurrentReportingAmount) from (select M.fProjectID,D.fCurrentReportingAmount from PM_IN_QuantitiesConfirm M left join PM_IN_QuantitiesConfirmDetail D on M.fID = D.fMasterID  where D.FSUBITEMNAME = '合计') MM where MM.fProjectID = PM_IN_ContractReceivable.fProjectID) as fAddUpReportingAmount,
	--当期-审批总金额（不含税）
	0 as fCurrentApprovalNoTaxAmount,
	--当期-增值税额
	0 as fCurrentApprovalTaxValueAmount,
	--当期-审批总金额（含税）
	0 as fCurrentApprovalTaxAmount,
	--累计-审批总金额（不含税）
	(select sum(MM.fCurrentApprovalNoTaxAmount) from (select M.fProjectID,D.fCurrentApprovalNoTaxAmount from PM_IN_QuantitiesConfirm M left join PM_IN_QuantitiesConfirmDetail D on M.fID = D.fMasterID  where D.FSUBITEMNAME = '合计') MM where MM.fProjectID = PM_IN_ContractReceivable.fProjectID) as fAddUpApprovalNoTaxAmount,
	--累计-增值税额
	(select sum(MM.fCurrentApprovalTaxValueAmount) from (select M.fProjectID,D.fCurrentApprovalTaxValueAmount from PM_IN_QuantitiesConfirm M left join PM_IN_QuantitiesConfirmDetail D on M.fID = D.fMasterID  where D.FSUBITEMNAME = '合计') MM where MM.fProjectID = PM_IN_ContractReceivable.fProjectID) as fAddUpApprovalTaxValueAmount,
	--累计-审批总金额（含税）
	(select sum(MM.fCurrentApprovalTaxAmount) from (select M.fProjectID,D.fCurrentApprovalTaxAmount from PM_IN_QuantitiesConfirm M left join PM_IN_QuantitiesConfirmDetail D on M.fID = D.fMasterID  where D.FSUBITEMNAME = '合计') MM where MM.fProjectID = PM_IN_ContractReceivable.fProjectID) as fAddUpApprovalTaxAmount,
--表类型
	fTableType 
FROM
	PM_IN_ContractReceivable UNION ALL
SELECT
	fid,
--版本
	version,
--年份
	fYear,
--月份
	fMonth,
--报量期间
	fReportPeriod,
--单据日期
	fRecordDate AS fBillDate,
--项目ID
	fProjectID,
--项目名称
	fProjectName,
--项目编码
	fProjectCode,
--合同编号
	fContractCode,
--合同ID
	fContractID,
--合同名称
	fContractName,
--合同应收款单编号
	fContractRecNo,
--收款方式
	fPaymentType,
--保修金比例
	fGuaranteeRatio,
--合同最晚收款时间
	fLastReceiveDate,
--合同约定收款比例
	fContractAgreeRatio,
	--施工进度
	'' as fBuildProgress,
--备注
	fRemark,
--附件
	fAttachment,
--结算ID
	fSettlementID,
--流程状态名称
	'' AS fBizState,
	fState AS fBizStateName,
--创建时间
	fCreateTime,
--提交人员FullID
	fCreatePsnFID,
--提交人员FullName
	fCreatePsnFName,
--修改时间戳（最后修改时间）
	fTS,
	--单据编号
	fRecordNo,
	--单据日期
	fRecordDate,
	--增值税率
	fValueaddedTaxRate,
	--报量方式
	fReportMode,
	--单据名称
	fTitle,
	--合同最晚收款时间
	fLatestCollectionTime,
	--合同约定收款期限（日历天）
	fContractAgreePeriod,
	--报量编号
	fReportNumber,
	--月度报量ID
	fPeriodID,
	--付款方式
	fPaymentMethod,
	--是否付款节点
	fISPaymentNode,
	--合同约定当期应收款金额
	fContractAgreedAmount,
	--报量类型
	fReportingType,
	--申报日期
	fApplyDate,
	--审批日期
	fApproveDate,
	--模板名称
	fTemplateName,
	--状态
	fState,
	--合同收款单附件
	fAttachmentCN,
	--提交部门ID
	FCREATEDEPTID,
	--拆分合同ID
	fSplitContractID,
	--当期申报额
	(select fCurrentReportingAmount from PM_IN_QuantitiesConfirmDetail where fMasterID = PM_IN_QuantitiesConfirm.fid and FSUBITEMNAME = '合计' ) as fCurrentReportingAmount,
	--累计申报额（含税）
	(select fAddUpReportingAmount from PM_IN_QuantitiesConfirmDetail where fMasterID = PM_IN_QuantitiesConfirm.fid and FSUBITEMNAME = '合计' ) as fAddUpReportingAmount,
	--当期-审批总金额（不含税）
	(select fCurrentApprovalNoTaxAmount from PM_IN_QuantitiesConfirmDetail where fMasterID = PM_IN_QuantitiesConfirm.fid and FSUBITEMNAME = '合计' ) as fCurrentApprovalNoTaxAmount,
	--当期-增值税额
	(select fCurrentApprovalTaxValueAmount from PM_IN_QuantitiesConfirmDetail where fMasterID = PM_IN_QuantitiesConfirm.fid and FSUBITEMNAME = '合计' ) as fCurrentApprovalTaxValueAmount,
	--当期-审批总金额（含税）
	(select fCurrentApprovalTaxAmount from PM_IN_QuantitiesConfirmDetail where fMasterID = PM_IN_QuantitiesConfirm.fid and FSUBITEMNAME = '合计' ) as fCurrentApprovalTaxAmount,
	--累计-审批总金额（不含税）
	(select fAddUpApprovalNoTaxAmount from PM_IN_QuantitiesConfirmDetail where fMasterID = PM_IN_QuantitiesConfirm.fid and FSUBITEMNAME = '合计' ) as fAddUpApprovalNoTaxAmount,
	--累计-增值税额
	(select fAddUpApprovalTaxValueAmount from PM_IN_QuantitiesConfirmDetail where fMasterID = PM_IN_QuantitiesConfirm.fid and FSUBITEMNAME = '合计' ) as fAddUpApprovalTaxValueAmount,
	--累计-审批总金额（含税）
	(select fAddUpApprovalTaxAmount from PM_IN_QuantitiesConfirmDetail where fMasterID = PM_IN_QuantitiesConfirm.fid and FSUBITEMNAME = '合计' ) as fAddUpApprovalTaxAmount,
--表类型
	fTableType
FROM
	PM_IN_QuantitiesConfirm
	) PM_IN_ContractReceivable 
	LEFT JOIN (SELECT 
		FMAINID FMAINID, 
		FORDERNO FORDERNO, 
		FCLOSINGUPPERIODTOTALTAX FCLOSINGUPPERIODTOTALTAX, 
		FCURRENTPERIODTAX FCURRENTPERIODTAX, 
		FDEADLINETOTALTAX FDEADLINETOTALTAX 
	FROM PM_IN_CONTRACTRECEIVABLEDETAIL WHERE FORDERNO = '9' ) 
	PM_IN_CONTRACTRECEIVABLEDETAIL ON PM_IN_ContractReceivable.FID = PM_IN_CONTRACTRECEIVABLEDETAIL.FMAINID 
	LEFT JOIN ( SELECT 
		FMAINID FMAINID, 
		FORDERNO FORDERNO, 
		FDEADLINETOTALTAX FDEADLINETOTALTAXYS 
	FROM PM_IN_CONTRACTRECEIVABLEDETAIL WHERE FORDERNO = '3' ) 
	PM_IN_CONTRACTRECEIVABLEDETAIL ON PM_IN_ContractReceivable.FID = PM_IN_CONTRACTRECEIVABLEDETAIL.FMAINID
	LEFT JOIN MA_PR_AccountObject PR ON PM_IN_ContractReceivable.FPROJECTID = PR.FID
</details>

**Comment by Matvey16** [comment]
@ReconditenessPerson Where do you see this bug? I tried to reproduce it and the comments are formatted correctly in view declaration

![image](https://user-images.githubusercontent.com/82543000/145176320-df07d75e-424f-4c8c-97ef-68634bbb5fbc.png)

**Comment by ReconditenessPerson** [comment]
> @ReconditenessPerson Where do you see this bug? I tried to reproduce it and the comments are formatted correctly in view declaration
> 
> ![image](https://user-images.githubusercontent.com/82543000/145176320-df07d75e-424f-4c8c-97ef-68634bbb5fbc.png)

Find the view object and open the declaration  , There are many other views as well .
I've reinstalled the software. It's still the same.
Every time an error occurs, it is annotated.
Operating the system character set   is  GBK 
Dbeaver language is simplified Chinese 
It is normal to open the same view on my other computer (the operating system is the same as the dbeaver version)

**Comment by Matvey16** [comment]
Can you please attach a file with script? Github may have erased some of the newline or other symbols.

**Comment by ReconditenessPerson** [comment]
> Can you please attach a file with script? Github may have erased some of the newline or other symbols.
[sql.txt](https://github.com/dbeaver/dbeaver/files/7778004/sql.txt)

I updated the latest version of 21.3 Version 2, the problem still occurs

**Comment by ReconditenessPerson** [comment]
> Can you please attach a file with script? Github may have erased some of the newline or other symbols.

I don't think it's a script problem, because the same script is displayed normally on the dbeaver on my other computer, and the operating system is consistent with the dbeaver version.

**Comment by uslss** [comment]
@ReconditenessPerson is it still actual for you?
unfortunately, still can not reproduce it. If it is still actual against the recent version, could you try to reset workspace and UI settings?
![image](https://user-images.githubusercontent.com/31996417/151400610-c084821e-c1b4-42d1-a1d5-436233a9324d.png)
