### ISSUE TITLE
Babelfish issues

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#14669]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.3.0

#### Connection specification:
- Database name and version Babelfish

#### Describe the problem you're observing:
Case 1:
Objects created in non-default database aren't visible after refresh
**STR**
1. Connect to database (database in preferences = master)
2. Create table in another non-default db (e.g. demo2)
3. Save table and refresh node
Actual result:
Created object aren't visible.

Case 2:
Synonyms, Sequences, Triggers and Database Triggers folders cannot by open due to error
#14808
Case 3:
Objects are always created in the default database
![image](https://user-images.githubusercontent.com/31996417/143225984-6b0c7395-db37-45cc-b3ce-59fb2bb87282.png)

Case 4:
Data import from csv isn't possible
![image](https://user-images.githubusercontent.com/31996417/143229678-bcdebc4b-b5cf-45b6-b16a-0acb69bf3e00.png)

**Comment by Destrolaric** [comment]
For Case 2 new issue is opened #14808

**Comment by E1izabeth** [comment]
To avoid switching between databases with `use dbname;` before and after every user action, only default database is shown for now.

**Comment by uslss** [comment]
verified
