### ISSUE TITLE
Postgres, ERD show pseudo columns

### ISSUE THREAD

**Issue by yoletx** [dbeaver/dbeaver#14667]
Hi,
In my ERD, i don't know why but i see pseudos columns for one table :
![DBeaver 21 2 4 - authent](https://user-images.githubusercontent.com/32055492/143219686-584664f4-4487-4425-be94-982debe0f269.jpg)
Dbeaver Version 21.2.4.202111011413 / windows 10
This is a very simple table, no PK/FK only 2 varchar fields.
I have 6 tables, and only one show his pseudo columns.
Tried :
- closing/reopening erd
- removing / re-adding table in ERD
- closeing/reopening dbeaver

**Comment by LonwoLonwo** [comment]
Hello @yoletx 
What PostgreSQL version do you use?

**Comment by LonwoLonwo** [comment]
`auth_para` table DDL will be also very helpful.

**Comment by yoletx** [comment]
```
-- Drop table

-- DROP TABLE authent.auth_para;

CREATE TABLE authent.auth_para (
	para_jwt_private_key varchar NULL,
	para_jwt_public_key varchar NULL
);
```

PostgreSQL 12.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit

**Comment by LonwoLonwo** [comment]
Is this problem in the Schema ERD?
And what about table ERD? Also incorrect?

![2021-11-24 14_54_28-Window](https://user-images.githubusercontent.com/45152336/143233845-19a206ae-2329-4bb1-a490-8e40813c8777.png)

I can't reproduce it for now, unfortunately.

**Comment by yoletx** [comment]
It is the same in the ERD table as in the ERD schema.
I duplicated the ddl to make a new table named auth_para2, this one is ok in ERD.
If i open this schema on another computer, i don't have the bug on the ERD. So maybe it's in the cache of my dbeaver but : 
I have deleted the table (drop table), refreshed table list, then the table disappear in the ERD, then recreated the table, then the table appear in the ERD but again with his pseudo columns.
(updated to Version 21.2.5.202111141807, same)

**Comment by Skydiveroid** [comment]
@yoletx, can I ask you to check it on the newest version, which is 21.3.0?

**Comment by yoletx** [comment]
> @yoletx, can I ask you to check it on the newest version, which is 21.3.0?

Ok, just checked, after installing 21.3.0 issue still persist. (tried deleting the table only in the ERD, refresh the ERD, and table came back with his pseudo columns.).
I can't tell you exact steps to produce this bug, but the thing is that i have 2 tables out of 12 with this bug now (this second table appeared before this new Dbeaver version).
And if i remember well (not 100% sure) the second table was ok at the begining, but after  modifing his structure, the bug appear, (i renamed column and deleted others columns to recreat them again, same name, in a new order).
If i have new clues i will post them there.

**Comment by yoletx** [comment]
I got it ! here are the steps to reproduce the bug (dbeaver community Version 21.3.0.202111281534)
I don't use keyboard shortcut in this demo, so everything can be seen.
![dbeaver erd issue](https://user-images.githubusercontent.com/32055492/145785237-14fbe8bc-f629-4405-8fe6-61b34e21de7c.gif)

**Comment by LonwoLonwo** [comment]
@yoletx Thanks for the investigation!
