### ISSUE TITLE
Error creating driver 'Oracle' instance. 

### ISSUE THREAD

**Issue by labeldevops** [dbeaver/dbeaver#14683]
This software looks very promising. I liked the connection wizard - but it fails, unfortunately. 

I can not create an oracle driver connection: 

```
Can't create driver instance
  Error creating driver 'Oracle' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'oracle.jdbc.OracleDriver'
  Error creating driver 'Oracle' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'oracle.jdbc.OracleDriver'
    oracle.jdbc.OracleDriver
    oracle.jdbc.OracleDriver

```

Network is ok.

**Comment by uslss** [comment]
@labeldevops did you try to reset to defaults driver in driver settings dialog?
![image](https://user-images.githubusercontent.com/31996417/143422704-422ac9d3-1f75-485d-a9f0-ff49e2de4f53.png)

**Comment by labeldevops** [comment]
Hmm, I checked that again, and now it works - I am not clear why that happened, seems to be ok now, sorry for the error report.

**Comment by labeldevops** [comment]
BTW I see in your screenshot that you too have these bad fonts... this is the old Java problem and it still seems to persist... sigh... I will search in this issue tracker for a solution...
