### ISSUE TITLE
Bad Fonts on Windows 10

### ISSUE THREAD

**Issue by labeldevops** [dbeaver/dbeaver#14686]
GUI has very bad fonts on Windows 10 - not usable. Fonts look garbled and unsharp.

**Comment by flambchap** [comment]
Hi @labeldevops. Could you please clarify a little bit what you mean? A screenshot or two would be helpful as well.

**Comment by uslss** [comment]
There has been no update on the issue for a long time.
If it is still present, feel free to reopen it.
