### ISSUE TITLE
New driver cannot be loaded for new connection

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#14681]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.3.0.202111242132

#### Connection specification:
- Database name and version tested Derby, Snowflake
- 
#### Steps to reproduce, if exist:
Create new connection 

**Expected**: the driver is loaded and the connectionis created
**Actual result**: the driver loading fails with error
```
Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by hitoroki** [comment]
I am experiencing this same problem on Windows 10 (dbeaver version 21.3.5 and 21.3.2). It's affecting all database types and versions after a fresh installation of dbeaver.

Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by edsonlima** [comment]
Hi,
I am experiencing it in Windows 7, also.

> I am experiencing this same problem on Windows 10 (dbeaver version 21.3.5 and 21.3.2). It's affecting all database types and versions after a fresh installation of dbeaver.
> 
> Network unavailable: javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target Network unavailable: javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by kosta709** [comment]
Why it is closed?
same on newest Version 22.0.1.202203181646 and fresh installed Windows-19 on GCP

**Comment by apausepi** [comment]
I have the same issue. on Microsoft 10 from VirtualMachine (Gnome Machines) from Linux.

**Comment by chrisschmitz** [comment]
I encountered the same issue on Windows 10. The solution was to remove the trust store type from the configuration.
I just removed the line `-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT` from dbeaver.ini and restarted DBeaver

**Comment by FredFrederik** [comment]
> I encountered the same issue on Windows 10. The solution was to remove the trust store type from the configuration. I just removed the line `-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT` from dbeaver.ini and restarted DBeaver

can confirm this worked

**Comment by OksiBlack** [comment]
the same on mac

Version 23.2.2.202310081633
