### ISSUE TITLE
Add variables support to the Export Wizard Output Folder field.

### ISSUE THREAD

**Issue by FeIix** [dbeaver/dbeaver#14680]
The patterns available for the filename when dumping data would also be useful in the folder name / path.

For example, we are backupping our projects each name in a folder named ${year}-${month}-${day}

I'd love to be able to automate this task, but I need to set the folder manually each time.

**Comment by LonwoLonwo** [comment]
Are you talking about this field?

![2021-12-01 15_39_08-Export](https://user-images.githubusercontent.com/45152336/144236298-99a54e76-69ef-4c5f-b75e-ee6792df610a.png)

**Comment by FeIix** [comment]
Yes, exactly !

**Comment by LonwoLonwo** [comment]
@FeIix Ok, Thanks for the idea.

**Comment by frailefeijoo** [comment]
I have the same problem with command's attributes of `@export`. 
Solve this will be very usefull for dynamically **myFolder** creation in a complex maintenance of database context.

Versión Comunnity 23.0.0.202303040621

For example:

`@set   myFolder = "export_folder"`
`@export   { "type": "_any_", "consumer": { "outputFolder": "${myFolder}", "outputFilePattern": "user_tables" } }`

Special attention to outputFolder value, where **${myFolder}** is prev declared variable.

Thanks!

**Comment by frailefeijoo** [comment]
I sugguest also must will study the viability of introduce an fiveth param to `@export`  general command as boolean, to determine if the exportation's display assistant turn show/hidde state on runtime.

The purpouse of this is hidde the exportation's assistant when use include script with much data.
By default dbeaver show this panel ever.
