### ISSUE TITLE
"Go to line" window is not resizable and the text is cropped

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14698]
### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.3.0

#### Steps to reproduce, if exist:
1. Open data editor for a table
2. Press <kbd>Ctrl + G</kbd>

**Expected:** Text is visible
**Actual:** Text is cropped and the window can't be resized

![dbeaver_z9bGfyzrDU](https://user-images.githubusercontent.com/82543000/143563927-57d3db2f-1779-4bfa-8624-ab3a84c6bd0f.png)

**Comment by E1izabeth** [comment]
Can't reproduce on Windows 10 with DBeaver 23.0.5
