### ISSUE TITLE
[Trino] ERD tab for databases doesn't always appear and doesn't contain objects

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14692]
#### System information: 
- Win10
- DBeaver CE 21.3.0

#### Connection specification:
- Trino

#### Describe the problem you're observing:
The tab isn't displayed when before double-clicking on the database, we expand this node. If we expand the node, then we'll see ERD tab, but there are no objects displayed in this ERD tab.

#### Steps to reproduce, if exist: 

https://user-images.githubusercontent.com/43252954/143475528-c83de38c-d6ea-495b-89d6-da0b2e4a5038.mp4

**Comment by uslss** [comment]
not actual at 22.0.5
no erd tab dor catalog
![image](https://user-images.githubusercontent.com/31996417/169344379-8d63df36-45ae-4b2f-8253-f8d3a7529ec7.png)
