### ISSUE TITLE
Maven artifacts added with a uri have classifier and version switched

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14705]
#### System information: 
- DBeaver version 21.3.0

#### Describe the problem you're observing:
We actually have three problems here:

- [x]  Wrong classifier and version
- [x]  Raw as a name of the tab is confusing
- [x]  Manual as a name of the tab is confusing
- [x]  We need an info label on how it can be used

![image](https://user-images.githubusercontent.com/82543000/143591707-71e0bb1b-e7be-40e4-9b84-9281e01b13b9.png)

**Comment by flambchap** [comment]
I want this in 21.3 versions of commercial products badly.

**Comment by Matvey16** [comment]
Can't add more than one artifact with maven declaration
![dbeaver_c9qAeBZJc7](https://user-images.githubusercontent.com/82543000/143783859-72ec8121-2553-4fb3-af07-41dcb21881c3.png)
![dbeaver_RI2XCQ5liY](https://user-images.githubusercontent.com/82543000/143783864-2b671cab-fb7d-4a82-b8bb-6cf855c57d9d.png)

**Comment by Matvey16** [comment]
Also now artifacts can't be edited

**Comment by Matvey16** [comment]
Verified
