### ISSUE TITLE
ERD foreign keys referencing the same table are shown incorrectly

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14704]
### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.3.0
- Additional extensions

#### Steps to reproduce, if exist:
1. Create a table with a foreign key referencing the same table (Sample SQLite db, table employee)
2. Open a diagram

![eclipse_QkmslU4tsc](https://user-images.githubusercontent.com/82543000/143590512-ce050433-c681-4a6b-b041-d0955d43716e.png)

**Comment by serge-rider** [comment]
Fixed (the fix was included in 21.3.0)

**Comment by Matvey16** [comment]
Verified
Minor issue created based on this one
#14724
