### ISSUE TITLE
Driver property cannot be set to null (causes Redshift IAM failure)

### ISSUE THREAD

**Issue by hlascelles** [dbeaver/dbeaver#14700]
#### System information: 
- Operating system (distribution) and version: Mint Linux 20.1
- DBeaver version: 21.2.5.202111141807
- Additional extensions: None

#### Connection specification:
- Database name and version: Any, but can try with postgres
- Driver name: : Any, but can try with postgres
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:

1. It is not possible to connect to Redshift using IAM *repeatedly*. It is possible to connect once.
2. This is because when saving a connection with no `ssl` value it does "work". But then restarting DBeaver (or reopening the Edit Connection window) the value is set back to `true`.

#### Steps to reproduce, if exist:

1. Create any postgres Driver.
2. Set `ssl` to nothing (blank value)
3. Save
4. Reopen, it will have been set back to `true`.

This is a problem as when connecting to Redshift, then `ssl` must be `null`. Note, this is not a User defined property so it is always present. Setting it to `false` / 0 etc is not enough. As the screenshot shows, it must be `null`.

The fix would be that "no value" is stored as `null` persistently.

The workaround is to open DBeaver, then navigate to the connection and to blank out the `ssl` value every time the application is launched.

NB, This doesn't disable SSL when connecting to Redshift, as the `sslmode` can be set.

![image](https://user-images.githubusercontent.com/299102/143570917-beba50f5-4b81-4900-8a2c-31b4a5f3ef40.png)

![image](https://user-images.githubusercontent.com/299102/143573018-b546a2ec-d0e1-4f93-81f7-8c0359f4c061.png)

Immediate message when restarting DBeaver:

![image](https://user-images.githubusercontent.com/299102/143571497-6f04daba-97cc-4a74-8355-0fdf05378120.png)

**Comment by Skydiveroid** [comment]
@hlascelles sorry for the late response. 
Could you provide a [full error log](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by hlascelles** [comment]
There isn't much in it I'm afraid, just confirmation that the "resetted settings" are not valid. 

![image](https://user-images.githubusercontent.com/299102/145070290-23f98bf4-1218-47f4-88e0-a3b7647b0cc7.png)

**Comment by hlascelles** [comment]
So just to simplify:

1) The "error" is that two settings are in conflict 
2) The "cause" is that one of the settings must be `null`, but DBeaver changes the `null` setting back to `true` on restart.
3) If DBeaver could leave a user-blanked out setting as blank, then everything would work.

**Comment by Skydiveroid** [comment]
We need to investigate that.

**Comment by Matvey16** [comment]
@hlascelles Thank you for the report. I reproduced it and we will work on that.

**Comment by owst** [comment]
@Matvey16 do you have any update on a possible fix for this issue? Thanks

**Comment by chuanzgh** [comment]
I await with bated breath... thanks for putting this back on a milestone!
