### ISSUE TITLE
lockPassword property does not lock connection edition

### ISSUE THREAD

**Issue by fcarton** [dbeaver/dbeaver#14702]
#### System information: 
- Operating system (distribution) and version : Windows 10 Pro
- DBeaver version : Version 21.2.5.202111141807
- Additional extensions : Git Support / Office Support / DevStyle

#### Connection specification:
- Database name and version : Any type of database has the same problem
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I'm trying to add a lockPassword property in my .data-sources.json but the editing connection is not lock.
by example
...
"folder": "DB2 for i/dev - Release Maintenance",
			"lockPassword": "e4a51326ea0c5da710b9f4cd2773e3db",
			"configuration": {
...

#### Include any warning/errors/backtraces from the logs
No error log

Thank you

**Comment by Skydiveroid** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
Can't reproduce.  When lockPassword  property is set then DBeaver asks for password before configuration change.

It allows to open connection edit dialog though.

![image](https://user-images.githubusercontent.com/6398845/145222289-7a072fad-de34-475c-85ec-bbe9ce983235.png)

**Comment by fcarton** [comment]
HEllo,

I test with a new fresh "zip" windows 64 bit version and i reproduce. In the dbeaver-debug log i've got this message

**Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found**

Is it linked to my issue ?

Thank you

**Comment by serge-rider** [comment]
Fixed

**Comment by fcarton** [comment]
Thank you very much !

**Comment by Matvey16** [comment]
Verified
