### ISSUE TITLE
Sample database creation tutorial

### ISSUE THREAD

**Issue by Destrolaric** [dbeaver/dbeaver#14723]
We need to add a wiki page about creating the Sample Database.

**Comment by Lkledu** [comment]
it's a request or you did it? If you go to `help->Create Sample Database`, dbeaver will create a sample SQLite database. Also while coding, I create a docker container running postgres, i can add it in wiki.

**Comment by Destrolaric** [comment]
@Lkledu It's issue ticket to add for completed task. I think you need to open it as an additional ticket for this, i think we need to gather opinions about this before adding it.

**Comment by Destrolaric** [comment]
https://github.com/dbeaver/dbeaver/wiki/Sample-Database

**Comment by Skydiveroid** [comment]
verified
