### ISSUE TITLE
Dbeaver will show wrong data with column datatype "decimal(4,0) unsigned zerofill" (MariaDB)

### ISSUE THREAD

**Issue by kaaga1** [dbeaver/dbeaver#14731]
Dbeaver (21.3.0) will show wrong data with column DataType ; "decimal(4,0) unsigned zerofill" with default value of  "0101"

It should show the value 

0101 

DBbeaver shows value as:
00000000000000000000000000000000000000000000101

PHP Myadmin and other tools are showing the value corectly

**Comment by LonwoLonwo** [comment]
@kaaga1 Thanks for the bug report!

**Comment by LonwoLonwo** [comment]
Related: https://github.com/dbeaver/dbeaver/issues/5457

**Comment by Matvey16** [comment]
Incorrect formatting for decimals with more than zero digits after decimal point. The first number in decimal for example 5,3 is total digits, but zeroes are added ignoring digits after decimal point

![dbeaver_6LTIiA25zG](https://user-images.githubusercontent.com/82543000/164412400-edcadcda-4ed0-4fd9-b724-fcd558bfa52f.png)
![dbeaver_B2QbnaG4gq](https://user-images.githubusercontent.com/82543000/164412425-969476bf-1c8a-4dc0-941d-bbfe52ea0af1.png)
