### ISSUE TITLE
Column Search in the result set - Feature request

### ISSUE THREAD

**Issue by techlock77** [dbeaver/dbeaver#14742]
Problem Description
  On a daily basis, I deal with tables having columns more than 200-250. And, if I need to look for a certain column, I have to pull the DDL or Transpose the result set and search for the column names that I am looking for and pull those column names to the editor.
  
  The above steps are a bit time-consuming.

Solution
  I would like to have a column search feature in the Metadata section, in the result set.( see below pic)
<img width="202" alt="image" src="https://user-images.githubusercontent.com/66756251/144096179-55232ce5-b6e4-4670-8293-c0d2e7ea8657.png">

Alternative
  Alternatively, I would like to have a column search feature from the result set. We have this kind of feature in the Aginity tool.

**Additional context**
  For now, a filter feature in the Metadata section would suffice.
  In the future, we can plan for a dedicated section for column search.

**Comment by Matvey16** [comment]
@techlock77 Thank you for the suggestion

**Comment by E1izabeth** [comment]
Implemented in scope of #3052
