### ISSUE TITLE
When too many tabs are opened, popup filter can be fuzzy matching

### ISSUE THREAD

**Issue by imzhi** [dbeaver/dbeaver#14748]
![image](https://user-images.githubusercontent.com/2304019/144154842-ded14d0a-1307-4bdb-ba35-d0c5da0d674b.png)

![image](https://user-images.githubusercontent.com/2304019/144154881-66bd47f8-8125-4b78-9002-81a7801c4598.png)

**Is your feature request related to a problem? Please describe.**
When too many tabs are opened, can the input filter text in the pop-up list box be changed from prefix matching to fuzzy matching?

**Describe the solution you'd like**
When you enter the ``meal`` text, you can not only match the ``meal_table``. You can also match ``member_meal_table``.

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by GuenterSch** [comment]
Please consider also https://github.com/dbeaver/dbeaver/issues/16730#issue-1263155480
Thanks
Günter
