### ISSUE TITLE
Import from csv needs option 'trim whitespase' for cells

### ISSUE THREAD

**Issue by Cergoo** [dbeaver/dbeaver#14758]
Сan't import .csv file, I get a message:
Can't parse numeric value [ 150275] using formatter
For input string: " 150275"

This often happens due to the presence of whitespace characters.
SQLyog does an excellent job of this because it has an option to remove whitespace characters.

**Comment by uslss** [comment]
please provide more info about feature accordingly to the [template ](https://github.com/dbeaver/dbeaver/issues/new?assignees=&labels=feature+request%2C+wait+for+review&template=feature_request.md&title=)

**Comment by Cergoo** [comment]
Сan't import .csv file, I get a message:
Can't parse numeric value [  150275] using formatter
  For input string: "  150275"

This often happens due to the presence of whitespace characters.
SQLyog does an excellent job of this because it has an option to remove whitespace characters.

**Comment by uslss** [comment]
@Cergoo what database do you use? could you provide csv sample to reproduce the issue?

**Comment by Cergoo** [comment]
@uslss I have MySql 8.0.27 and try to import https://www.cftc.gov/files/dea/history/fut_fin_txt_2021.zip

**Comment by uslss** [comment]
Thanks for the suggestion and clarification

**Comment by Matvey16** [comment]
Verified
