### ISSUE TITLE
Export data sql missing quote of values

### ISSUE THREAD

**Issue by miky2184** [dbeaver/dbeaver#14755]
#### System information: 
- Operating system (distribution) and version --> macOs BigSur 11.6.1
- DBeaver version --> 21.3.0
- Additional extensions --> NO

#### Connection specification:
- Database name and version --> PostgresSQL 
- Driver name 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When export data in sql insert format, missing the quotes stored inside a value.

Value like this:
![image](https://user-images.githubusercontent.com/53818183/144246484-c2de359e-ed22-4353-8c40-6925095d3bdb.png)

are so exported:

insert into blabla (field1, field2) values ('FlussoMisure/DatiPdr/DatiLettura','DatiPdR');

with version 7.3.5 (i made a downgrade) the export is correct in this format:

insert into blablabla (field1, field2) values ('''FlussoMisure/DatiPdr/DatiLettura''','''DatiPdR''');

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.3.1
