### ISSUE TITLE
Open Database Object is not filtering on currently active database

### ISSUE THREAD

**Issue by rgobo** [dbeaver/dbeaver#14766]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.3.0.202111291534 (november 29)

#### Connection specification:
MSSQL server, driver version 9.2.0.jre8

#### Describe the problem you're observing:
Searching with Ctrl+Shift+D (Open Database Object) and typing a table name displays every potential table on any existing database on the active server instead of only showing the tables on the currently active database. I'm guessing this is not intentional since there is no way to tell _which_ database I'd be selecting in the popup - I just get a list of dozens of identically named tables and as I open each one, it gets opened with a different database.

As a workaround I added a database filter to my connection so it only loads a single database. I'm guessing this issue appeared as a result of the fix for https://github.com/dbeaver/dbeaver/issues/14001 when no tables whatsoever would get loaded in the search popup. I guess getting everything is better than getting nothing but it's a bit annoying having to setup a db filter for every connection while having a separate configurations for databases on the same server.

**Comment by uslss** [comment]
Thanks for the report. 
At the moment:
- Search is performed **within chosen schema** in case it was in focus when Ctrl+Shift+D was opened.
- Search is performed **within chosen database** in case it was in focus when Ctrl+Shift+D was opened.
- Search isn't performed at all in case some table was in focus when Ctrl+Shift+D was opened.
![F8uLU7r21S](https://user-images.githubusercontent.com/31996417/144821151-bb45f920-2ead-41c2-931d-a685bd9a1034.gif)

**Comment by rgobo** [comment]
Thanks for the clarification, I assumed it always uses the database/schema specified in the connection settings, not that I'd have to focus it in the navigator. I have it collapsed often so I'm guessing my search defaults to all available databases on the server instead, but if I select a specific database then it works fine. 

Basically, if you also had a table named "Department" in the "2019test" database, and no specific database was focused, it would display two options "Department" if you try to search for it, with no way to tell which one it is you want.

**Comment by LonwoLonwo** [comment]
Ctrl+Shift+D search fixed for objects in the Navigator tree: tables, views, etc.

I can't reproduce the issue with the search in other databases. I advise you to use the focus when activating the dialog box at the database objects that interest you. I hope it will help.

Note: This setting in the preferences may influence the search:

![2022-02-22 10_56_27-DBeaver Enterprise 21 3 5 - language](https://user-images.githubusercontent.com/45152336/155088160-e0a26ae0-fdb9-44d8-b4c2-c1647b7e08dd.png)

**Comment by Matvey16** [comment]
Verified
