### ISSUE TITLE
dbeaver quit unexpectedly

### ISSUE THREAD

**Issue by bupy7** [dbeaver/dbeaver#14770]
#### System information: 
- macOS Monterey 12.0.1
- DBeaver version: dbeaver-ce-21.3.0-macos-x86_64

#### Describe the problem you're observing:

![image](https://user-images.githubusercontent.com/5145037/144451964-9f804cc6-f30b-4d9a-b99d-eb5a15edf19e.png)

#### Steps to reproduce, if exist:

1. Install DBeaver
2. Open DBeaver
3. Work in DBeaver
4. Close DBeaver
5. Restart your mac
6. Open DBeaver with fatal error above

#### Include any warning/errors/backtraces from the logs

From the problem report log:

```
"exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL (Code Signature Invalid)"}
```

i have not any logs.

**Comment by Matvey16** [comment]
@bupy Please add more information to reproduce. Will DBeaver launch if you reinstall it? And more importantly will this error appear if you start it, do nothing, close and restart your machine?

**Comment by bupy7** [comment]
> Will DBeaver launch if you reinstall it

Yes.

> will this error appear if you start it, do nothing, close and restart your machine

Yes, it's very important thing - the restart. Before restart, just closing/opening, has no error effect.

**Comment by mcheremnov** [comment]
I have the same issue. I install dbeaver from brew. Attaching full report below.
[dbeaver_report.txt](https://github.com/dbeaver/dbeaver/files/7786075/dbeaver_report.txt)

**Comment by Matvey16** [comment]
@bupy What processor does your Mac have?

**Comment by bupy7** [comment]
@Matvey16 Intel Core i5

**Comment by Matvey16** [comment]
@bupy7 This could have been fixed with a recent update of the Eclipse platform. Can you check the early access version https://dbeaver.io/files/ea/ and verify if it was fixed for you?

**Comment by bupy7** [comment]
@Matvey16 I've installed 21.3.2.202112271055, now it's work.

**Comment by flambchap** [comment]
@mcheremnov Does the new version of DBeaver solves the issue for you?

**Comment by mcheremnov** [comment]
@akilovich Yes, my issue resolved with new update. Thank you

**Comment by flambchap** [comment]
Great!
