### ISSUE TITLE
please support GraphQL query,thanks

### ISSUE THREAD

**Issue by hktalent** [dbeaver/dbeaver#14783]
please support GraphQL query,thanks

**Comment by ShadelessFox** [comment]
Hello @hktalent,

Please provide more details about your request.

Thanks.

**Comment by hktalent** [comment]
like https://graphql.org tools, thanks @ShadelessFox

**Comment by ShadelessFox** [comment]
I'm not sure what exactly do you want us to support.

AFAIK GraphQL is a language for API queries. It has nothing to do with databases.

Can you elaborate?
