### ISSUE TITLE
show comment in left element tree

### ISSUE THREAD

**Issue by LinWanCen** [dbeaver/dbeaver#14780]
**Is your feature request related to a problem? Please describe.**
We are always frustrated when I read the table and column comment need open a tab.

**Describe the solution you'd like**
We hope show comment in left element tree, like DataGrip open Viev -> Appearance -> Details in Tree View.

https://intellij-support.jetbrains.com/hc/requests/2827972

**Comment by ShadelessFox** [comment]
Hello @LinWanCen,

Please post screenshots or text instead of attaching external links.

**Comment by LinWanCen** [comment]
![image](https://user-images.githubusercontent.com/14926671/149669514-bb013bc5-4f3d-4a91-a276-48b114d4106b.png)

> Please post screenshots or text instead of attaching external links.

**Comment by ShadelessFox** [comment]
I see, thanks. It would be handy.

Currently, the description is displayed in a tooltip.

**Comment by ShadelessFox** [comment]
Implemented:

![java_Kfdf54HkIC](https://user-images.githubusercontent.com/35821147/150457442-1382bba2-95d0-4eb1-a0b8-c0b67e0b9597.png)

Can be toggled in several ways:
* In Preferences, <kbd>User Interface</kbd> &rArr; <kbd>Navigator</kbd> &rArr; <kbd>Show objects description</kbd>
* In connection's context menu, <kbd>Connection view</kbd> &rArr; <kbd>Show objects description</kbd>

**Comment by LinWanCen** [comment]
Is the column comment also show?
Expectation!

**Comment by ShadelessFox** [comment]
Yes.

**Comment by uslss** [comment]
verified

**Comment by LinWanCen** [comment]
It looks like it's loaded asynchronously,
and most of the time we don't see all the comments.
Can there be an option to load all of them and cache them.
