### ISSUE TITLE
Generate SQL: problem with DB2 timestamps 

### ISSUE THREAD

**Issue by p0c07o** [dbeaver/dbeaver#1479]
When executing a query, DB2 timestamps are displayed with all 6 decimal positions. I assume toString() is used to display the Timestamp object.

When selecting a row with a timestamp and calling Generate SQL > INSERT, the timestamp precision is truncated, certainly because a data format is used. As Java only allows 3 milliseconds (SSS in format pattern), we lose the last 3 microseconds.

Under the preferences, Java format patterns can be defined. I guess these formats are used in the output of Generate SQL. In that case, it would be an acceptable workaround, if one could define, for a certain data type, whether a pattern or toString() should be used.

**Comment by serge-rider** [comment]
To see microseconds in results view you need to change data format for timestamps (set pattern to `yyyy-MM-dd HH:mm:ss.ffffff`).
Native DB2 timestamp representation (which us used in Generate SQL) was incorrect in DBeaver, see fix in the next version.

**Comment by mibrunet** [comment]
I'm running version 4.1.3 64 bits.
Connected to DB2
Steps to reproduce the bug:
1) CREATE TABLE XXX.DBEAVER_DB2_TMST_TEST (TMST TIMESTAMP) IN DBXXX.TSXXX
2) INSERT INTO TSXXX.DBEAVER_DB2_TMST_TEST VALUES(CURRENT TIMESTAMP)
3) SELECT * FROM TSXXX.DBEAVER_DB2_TMST_TEST
--> 
**2017-08-24 14:03:19.869326**
4) Right click timestamp + Generate SQL + INSERT
-->
**INSERT INTO TSXXX.DBEAVER_DB2_TMST_TEST
(TMST)
VALUES('2017-08-24 14:03:19.869');**

The insert statement is missing the last 3 digits of the timestamp.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce the bug in 7.0.2. Is it still actual for you?

**Comment by uslss** [comment]
there is no update on issue for a long time. if issue is still actual for you - feel free to reopen the ticket
