### ISSUE TITLE
Turn off SQL Tranformation

### ISSUE THREAD

**Issue by Jnb2387** [dbeaver/dbeaver#14799]
**Is your feature request related to a problem? Please describe.**

When copying and pasting column names with quotes, the text is extracted and loses the quotes.
Hitting CTRL + C to copy the column name and then hitting CTRL + V pastes the column name but removes the quotes and a popup appears stating 'SQL Transformation, SQL Query was extracted from the source code.'

**Describe the solution you'd like**
Add an option to remove this behavior.

**Describe alternatives you've considered**
Hitting CTRL + Z will add the quotes back to the column name, but this is an extra step to paste what was copied.

**Comment by uslss** [comment]
@Jnb2387 Could you try to uncheck Extract SQL from the source code option in Preferences and check if it helps?
![image](https://user-images.githubusercontent.com/31996417/144816023-053d6dcf-21c7-4cb4-9d51-0a23bea7afc1.png)

**Comment by Jnb2387** [comment]
Perfect, thank you!
