### ISSUE TITLE
[Data transfer] Apply target table mapping chosen in "Browse" to all selected items in the list

### ISSUE THREAD

**Issue by Hermholtz** [dbeaver/dbeaver#14790]
I'm trying to copy individual partitions to a single target table using "Export Data". In the "Tables mapping" I'm selecting all items in the grid and clicking "Browse" to select an existing target table. Unfortunately this choice is only applied to the first item. I'd like this to be applied to all selected items. Please see the screenshot.

I considered copying the entire master partitioned table, but due to the size the data transfer is crashing DBeaver with "Event loop exception" - "Java heap space". Copying partition by partition is very efficient. But having to manually map more than a dozen partitions is a very tedious task.

Thank you in advance.

![image](https://user-images.githubusercontent.com/4431298/144724908-873be7fd-d6df-4036-aece-711743eef9f7.png)

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by uslss** [comment]
verified
