### ISSUE TITLE
create mysql table failed 

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#14792]
successful：
create table if not exists `students`(`stu_id` int,
`name` varchar(10));

failed：
create table if not exists "students"("stu_id" int
"name" varchar(10));
create table if not exists 'students'('stu_id' int
'name' varchar(10));

finded the  english quotation marks(‘or ") using error,copy 菜鸟教程 succeed

**Comment by ShadelessFox** [comment]
Hello @Fred-Laiu,

I'm not sure what you're trying to achieve.

Are you trying to execute mentioned statements via SQL editor?

**Comment by ghost** [comment]
yes,I am only trying for  creating a table .then ,finding this

**Comment by ghost** [comment]
![图片](https://user-images.githubusercontent.com/50812743/144746823-c013e45f-af91-4575-9347-3d7c5ea951b2.png)

**Comment by ShadelessFox** [comment]
You need to use backticks: `` ` ``:
https://dev.mysql.com/doc/refman/8.0/en/identifiers.html

Both `"` and `'` are used for defining string literals:
https://dev.mysql.com/doc/refman/8.0/en/string-literals.html
