### ISSUE TITLE
Make config file location configurable under windows

### ISSUE THREAD

**Issue by nagylzs** [dbeaver/dbeaver#14793]
This request is related to #2755. In https://github.com/dbeaver/dbeaver/issues/2755#issuecomment-513260791 the default config file location for linux was placed under `${XDG_DATA_HOME}/DBeaverData` but for windows, it is still a (somewhat) fixed directory `%AppData%/DBeaverData`.

Here is the use case:

* I have multiple Windows computers, and I work on all of them. 
* I have a common config directory that is synchronized between all of them
* I use many programs that are able to use custom config directories, and their configurations are always synchronized between all computers that I use
* DBeaver cannot do this, because its config dir is not configurable.

Of course, I could setup a separate directory synchronization just for this single config directory, but that is very clumsy.

I know that this is a very narrow use case, but I think it would be a small change to use something like `$DBEAVER_CONFIG_DIR` env instead of `%AppData%/DBeaverData` (when set).

**Comment by flambchap** [comment]
Hi @nagylzs. I synchronize DBeaver workspaces between my Windows machines using Dropbox. To do that, I created a different workspace under the directory I share between my devices. You can do that by clicking File -> Switch Workspace -> Other. Does this solution work for you?

**Comment by nagylzs** [comment]
I just moved my workspace folder inside a synchronized folder, and I could switch to it. Everything seems to be working. I'm not sure what will happen if I leave open DBeaver on one computer and open it on another one at the same time. But So far so good.
