### ISSUE TITLE
Show default-privileges in PostgreSQL

### ISSUE THREAD

**Issue by ridicolos** [dbeaver/dbeaver#14804]
There is no tab or menu in DBeaver to show default-privileges in a PostgreSQL-Database.

Currently to do this I use this sql-script to show me the information:

```sql
SELECT 
  nspname,         -- schema name
  defaclobjtype,   -- object type
  defaclacl        -- default access privileges
FROM pg_default_acl a JOIN pg_namespace b ON a.defaclnamespace=b.oid;
```

or do it simply with psql

```
postgres=# \ddp
```

It would be nice if you could check your default-privileges of a PostgreSQL-Database inside the DBeaver-UI.

**Comment by Skydiveroid** [comment]
Thank you for the idea.

**Comment by rbovard** [comment]
Thanks a lot, it works perfectly!

**Comment by LonwoLonwo** [comment]
Yes, forgot to write here.

Starting DBeaver 23.2.4, you can see and manage default privileges for PostgreSQL (and some forks).

![2023-10-17 12_48_00-DBeaver Ultimate 23 2 2 - miriam](https://github.com/dbeaver/dbeaver/assets/45152336/62f5cca6-dfe0-48f9-807e-d4a53c2135d1)

![2023-10-17 12_55_40-DBeaver Ultimate 23 2 2 - miriam](https://github.com/dbeaver/dbeaver/assets/45152336/aa68d3c4-3c6e-41bb-ae74-9db83ea14c1f)

![2023-10-17 13_37_11-DBeaver Ultimate 23 2 2 - test4](https://github.com/dbeaver/dbeaver/assets/45152336/6a062d24-0587-4154-9e93-dbf7a98d073e)

**Comment by ridicolos** [comment]
Sorry for the late reply here. First of all really happy to see this implemented. Thanks for the work!

Unfortunately I found a issue with that implementation. I don't know if I should create bug for this? Maybe we can also reopen this issue? @LonwoLonwo @uslss 

---

The grantor of these default-privileges is missing. In PostgreSQL the grantor of these default-privileges (the role which was used while creating the default-privileges) is essential for them. These default-privileges will **only be used on new Objects which will be created by the grantor** and will not be global on the complete schema.

A mapping consists of the grantor, grantee and the schema. 
For example (we have default-privileges set by the grantor to the grantee on a schema): if a table is created inside the schema by another role than the grantor, default-privileges for the grantee will not be assigned. This will only work if the grantor creates a table in the schema.

So if you habe multiple default-privileges in on one Schema, DBeaver will show them as duplicates and you don't really know, whats the difference between them and when they will be used.

```sql
ALTER DEFAULT PRIVILEGES IN SCHEMA test GRANT SELECT ON TABLES TO test_select;
ALTER DEFAULT PRIVILEGES IN SCHEMA test GRANT SELECT ON TABLES TO test_select;
```

This also causes a little inconvenience when you're using the privileges menu inside DBeaver. You can only see if the role (you are logged in with) assigned default-privileges to a role you are inspecting. But you cannot see if there are other default-privileges already assigned to this role.

If you inspect the source of a role with the option to show permissions, you cannot see the default-privileges that were assigned to this role. You can only see this on schemas. Maybe it would make sense to have it on both places, because they are related.

**Comment by E1izabeth** [comment]
Hi, @ridicolos 
Please create a new bug report
