### ISSUE TITLE
Drop table generates sql statement without schema information! 

### ISSUE THREAD

**Issue by JueShanCoder** [dbeaver/dbeaver#14818]
#### System information: 
- MacOS
- DBeaver version : 21.0.5.202105160657

#### Connection specification:
- Database name and version: Custom jdbc driver

#### Describe the problem you're observing:
When I select the database and schema and click on the table to drop the table, check that the generated SQL script for drop the table has no schema information

![image](https://user-images.githubusercontent.com/67142106/144989649-0089b511-9e09-4482-b9f4-5d473e2b5cc9.png)

**Comment by ShadelessFox** [comment]
Hello @JueShanCoder,

What database is it?

**Comment by JueShanCoder** [comment]
Hi, This is our internal database, a custom jdbc driver. As you can see in the picture, DBeaver can get the corresponding database and schema but when building the sql, it finds that there is no schema. @ShadelessFox

**Comment by ShadelessFox** [comment]
I see. My suggestion is to try tweaking driver properties, especially this one:

![java_wGak08uypG](https://user-images.githubusercontent.com/35821147/145007049-2e757667-db03-4cfa-b80a-1e69a14780e9.png)

Please let me know if it helps.

**Comment by JueShanCoder** [comment]
Unfortunately, it doesn't work and the generated sql still doesn't contain schema information. @ShadelessFox

**Comment by JueShanCoder** [comment]
I have the same problem when I double click on the table to view the data, there is no schema in the generated sql. @ShadelessFox

**Comment by JueShanCoder** [comment]
![image](https://user-images.githubusercontent.com/67142106/145018195-587c2316-a577-45bc-bc0f-f3fd6224cbb7.png)

The database is missing

**Comment by ShadelessFox** [comment]
Unfortunately, we can't do much without any environment we can use for testing.

**Comment by JueShanCoder** [comment]
Fixed it, Tks for your help. I will close this issue.
