### ISSUE TITLE
How to clear Bind Parameter(Variable) ?

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#14817]
The method I know is to delete the Bind Parameter panel one by one or manually edit the file(sql-variables-driver-oracle_oracle_thin.json) and restart the deaver.
Is there a way to delete all at once by selecting an area in the Bind Parameter panel?

**Comment by Skydiveroid** [comment]
Thank you for the idea.

**Comment by Matvey16** [comment]
Parameters are not actually deleted, they just disappear from the list until the new one is created or the editor is reopened

![explorer_OAvIDwQta0](https://user-images.githubusercontent.com/82543000/148911863-6e76848d-1b79-49e6-bf64-609a5db38302.gif)

**Comment by Matvey16** [comment]
Parameters are still remaining in variable panel (even thogh they are actually deleted) if they were created before current editor was opened 

![dbeaver_jo5szXooRX](https://user-images.githubusercontent.com/82543000/150157282-8ae3c079-afa5-411b-a1e7-b4f233608765.gif)

**Comment by Matvey16** [comment]
Verified
