### ISSUE TITLE
Date format in SQL SELECT is inverted when connecting to a SQL SERVER 14. SQL SERVER 12 it's ok

### ISSUE THREAD

**Issue by fgalvani70** [dbeaver/dbeaver#14814]
#### System information: 
- Operating system (distribution) and version:
System:    Kernel: 5.4.0-91-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 5.0.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 
- DBeaver version 21.3.0
- Additional extensions: no extensions

#### Connection specification:
- Database name and version: **DTMREMOTO**
- Driver name: **Microsoft JDBC Driver for SQL Server**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **No**

#### Describe the problem you're observing:
When I use this command:
SELECT * FROM tb_fechamento_venda WHERE [data] = 'yyyy-mm-DD' 
The result data field is yyyy-DD-mm

I have changed in Global Settings and in Connection Setting using this instructions:
https://github.com/dbeaver/dbeaver/issues/5479

But the result is the same

**Comment by Matvey16** [comment]
@fgalvani70 Hello. Have you tried disabling date/time formatting entirely?

**Comment by fgalvani70** [comment]
Hi Matvey16!!!!

Yes. I do!
I tried to enable and disable globally and also specifically on MS SQL
connection.

Flávio Galvani
+551197637-6817


Em qua., 15 de dez. de 2021 às 09:02, Matvey16 ***@***.***>
escreveu:

**Comment by Matvey16** [comment]
@fgalvani70 Can you elaborate some more about a database you use? Does it have an english documentation?

**Comment by fgalvani70** [comment]
I will send you some screenshots.

Flávio Galvani
+5511 97637-6817

Em sex., 17 de dez. de 2021 10:57, Matvey16 ***@***.***>
escreveu:

**Comment by uslss** [comment]
There has been no update on the issue for a long time.
if it is still actual for you - feel free to reopen it with additional info for its investigation
