### ISSUE TITLE
Does cloud dbeaver support Command line to pass parameters? Can parameters be passed in using Command line like windows when starting the dbeaver container? For example: https://github.com/dbeaver/dbeaver/wiki/Command-Line

### ISSUE THREAD

**Issue by lichaoge** [dbeaver/dbeaver#14824]
Does cloud dbeaver support Command line to pass parameters? Can parameters be passed in using Command line like windows when starting the dbeaver container? For example: https://github.com/dbeaver/dbeaver/wiki/Command-Line

**Comment by ShadelessFox** [comment]
Hello @lichaoge,

Please refer to the CloudBeaver issue board:
https://github.com/dbeaver/cloudbeaver/issues
