### ISSUE TITLE
MS SQL Semicolon on declaring variables

### ISSUE THREAD

**Issue by nelfer** [dbeaver/dbeaver#1482]
Hi,
Fist at all, great work with DBeaver. Love it as I can connect to multiple servers and types of databases from one single place.

However, I have found a problem. If I have this:
```
DECLARE @sc_CountryOfExport nvarchar(13)='United States';
SELECT * FROM dbo.Country WHERE [Name] = @sc_CountryOfExport;
```
And execute the script (not execute the statement) I get an error that I need to declare scalar `@sc_countryOfExport`.
If I remove the semicolon then it works OK.

The semicolon is a 'statement terminator' but I don't think that means that the next statement gets a different context (like the keyword `GO`).
The reason why I say this is because in the Microsoft tools, both forms (with and without semicolon) work exactly the same.

However in Microsoft tools, if I insert a `GO` in between the 2 lines, then it behaves like in DBeaver.
As per the documentation, `GO` is a "batch" terminator (https://msdn.microsoft.com/en-us/library/ms188037.aspx)

So it seems like DBeaver is treating a statement terminator as a batch terminator. This could be very problematic, because very soon semicolon will be mandatory and MS tools will behave differently (we'll have to go back to those, instead of using awesome DBeaver)
https://msdn.microsoft.com/en-us/library/ms177563(v=sql.110).aspx

Notice that `DECLARE` is considered a statement and it serves to declare variables in the "batch". So `DECLARE` will have a semicolon and DBeaver will not work under this scenario.
https://msdn.microsoft.com/en-us/library/ms188927(v=sql.110).aspx
(The example in the above page does not run DBeaver due to the semicolon in the `DECLARE` lines)

I'm using DBeaver 3.8.0

Thanks!

**Comment by serge-rider** [comment]
Yes, SQL Server is special.

When you execute in script mode (alt+x) then DBeaver splits script text on statements (using `;` and `GO`) and then executes statements one by one. In opposite to MySQL each statement is executed as a batch and variables context is lost after every statement execution.
For DBeaver there is no difference between `;` and `GO` in script mode - they are just delimiters.

If you need to execute your script as a single batch - use query execution (CTRL+Enter). You can select whole script (CTRL+A) and then run it.

So far I don't see how I can improve this.

**Comment by nelfer** [comment]
OK thanks for the reply.
Selecting all the text and using Query Execution everything works. Great!

So perhaps, just simply add a new option "Execute SQL Script as Batch" or "Execute SQL Script as Statement" to combine getting all of the script content and running it as one statement. That way I can bind that action to F5 (for example, which is what MS uses) and I can quickly execute entire scripts.

Although I noticed that if I have a "GO" in between, it fails.

**Comment by jestal** [comment]
Is this the same problem as when I execute this:
DECLARE @int1 AS INT;
SET @int1 = 100000;

but it thinks it's this:
DECLARE NULL AS INT
SET NULL = 100000;

**Comment by cbrunnkvist** [comment]
`DECLARE @sc_CountryOfExport nvarchar(13)='United States';`

<img width="570" alt="Screen Shot 2019-07-26 at 13 28 34" src="https://user-images.githubusercontent.com/34006/61930962-88be0880-afa9-11e9-87da-837616a47279.png">

Any mention of `@something` makes the Bind Parameters dialog pop up. How is this supposed to work? I'm declaring a local variable, replacing its name with a value at this stage would be a catch-22 situation.

**Comment by jetzerb** [comment]
As a consequence of the way [DBeaver splits script text on statements (using ; and GO) and then executes statements one by one](https://github.com/dbeaver/dbeaver/issues/1482#issuecomment-289197383) (per Serge's comment above on 2017-03-25), the only way to execute a `merge` command on MSSQL is to highlight it and hit CTRL-Enter.

Sample Test Script:
```sql
drop table if exists #test;
create table #test (id int, name varchar(10));

merge into #test tgt
using (values
	 (1,'Alice')
	,(2,'Bob')
) src(id,name)
on tgt.id = src.id
when matched then
	update
	set name = src.name
when not matched then
	insert (    id,    name)
	values (src.id,src.name)
; -- <<--- Note the presence of the semi-colon
```
If you run the _script_ (ALT-X) you get
>Error occurred during SQL query execution
>
>Reason:
>SQL Error [10713] [S0001]: A MERGE statement must be terminated by a semi-colon (;).

because evidently the text _between but not including_ the semi-colon is executed.

Error? | Highlighting | Scenario
--- | --- | ---
Yes | None | Run script (ALT-X)
Yes | Entire Script | Run script (ALT-X)
Yes | None | Run statement (CTRL-Enter) when cursor is positioned within the statement
No | Entire Statement | Run statement (CTRL-Enter)
No | Entire Script | Run statement (CTRL-Enter)--But this runs the entire script (all highlighted statements)

This is still true as of version 6.2.5.

A (probably easy) fix for the `merge` problem is to append a semi-colon to each block of text that DBeaver executes.  MSSQL commands will _always_ work with a semi-colon terminator, but _sometimes_ not work without one.

But the larger issue could be fixed if DBeaver keeps its current script parsing logic, except for MSSQL, use _only_ `go` (on a line by itself) as the delimiter between blocks of text to execute, ignoring semicolons completely.  Then DBeaver would treat MSSQL scripts the same way as SSMS, Azure Data Studio. SQLCMD, etc.

**Comment by Eddie-Hartman** [comment]
@serge-rider I ran into this today.
The above suggestion of ignoring the `;` for executing scripts in script while using SQL Server seems valid. Is this something that can be done?

**Comment by norton64** [comment]
I also have this issue in the Community version 7.2.4.202011011603 (on Windows 10).  Irrespective of the combination of checkboxes in the SQL Processing settings, the only way I can get DBeaver to run is to remove all of the semicolons except for the final **end catch;** 

I'm using a transaction on an insert statement:

```
begin try
   begin tran
      insert to target_table (column list)
         select from source_table where not exists (select 1 from target_table)
   commit tran
end try
begin catch
   rollback tran
   throw
end catch;
```

**Comment by jetzerb** [comment]
@norton64: Did you try [my solution above (edit 2)](https://github.com/dbeaver/dbeaver/issues/1482#issuecomment-555557327)?

I'm currently running the same 7.2.4 version as you.  When I clear out the statement delimiter and uncheck the three boxes beneath it, I can execute your code (slightly altered to illustrate the use of `go` in addition to semicolon line endings):
```sql
--
-- Highlight everything or nothing and hit ALT-X or select "run script" to execute both blocks below
-- Highlight any portion of this script, with or without the "go" and hit ALT-X to execute whatever is highlighted.
-- Highlight any portion of the block above or below the "go" and hit CTRL-ENTER to execute whatever is highlighted.
--
declare @somevar int = 5;
select @somevar;
-- Place your cursor above the "go" and hit CTRL-ENTER or select "run statement" to execute the block above
go
-- Place your cursor below the "go" and hit CTRL-ENTER or select "run statement" to execute the block below
create table #target_table (id int, nm varchar(10));

begin try
   begin tran;
      insert into #target_table (id,nm) values (1,'test');
   commit tran;
end try
begin catch
   rollback tran;
   throw;
end catch;

select * from #target_table;
drop table #target_table;
```

Things to keep in mind:
- `ALT-X` (run script) executes
   - Whatever is highlighted (and can span `go`s)
   - or _everything_ in the script window, if nothing is highlighted
- `CTRL-ENTER` (run script) executes
   - Whatever is highlighted, but has to be a single batch so can't include `go`
   - or everything in the script window between the SQL Server native delimiter `go` above your cursor (or the first line) down to the next `go` below your cursor (or the last line)

**Comment by norton64** [comment]
Thank you @jetzerb !  I don't know what I did differently, but it is working after running through your script.

**Comment by ghost** [comment]
I followed @jetzerb's comment about removing the statement delimiter and unchecking all of the boxes under the "Delimiters" section, but I am still not able to execute the file without highlighting it all.

However if ticked the "Ignore native delimiter" checkbox, I was able to run "Execute SQL script" without highlighting.
![image](https://user-images.githubusercontent.com/54722267/119185290-75f0af80-ba2b-11eb-8624-cd293d9aacc2.png)

DBeaver version:
![image](https://user-images.githubusercontent.com/54722267/119185382-91f45100-ba2b-11eb-9c65-0f4590eef18f.png)

OS: PopOS 20.10 64bit

**Comment by jetzerb** [comment]
@picarro-msimpson :
A recent release of DBeaver changed the MSSQL native delimiters from just "go" to both "go" and ";".  [My comment](https://github.com/dbeaver/dbeaver/issues/12078#issuecomment-823571729) on issue #12078 explains that now to obtain the same settings as in my comment above (the only delimiter is `go`), you should
- Set the Statements Delimiter to `go`
- Check the "Ignore native delimiter" box

That allows the use of `Ctrl+Enter` to run everything between `go`s (which may include multiple statements terminated by a `;`).

**Comment by ghost** [comment]
@jetzerb

Thanks for the update. I hadn't looked into that thread, but your solution is exactly what I was looking for!
