### ISSUE TITLE
Cross-project connections drag-n-drop problem

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14837]
#### System information: 
- DBeaver version 21.3.0

#### Describe the problem you're observing:
Connection moved from or into a project created from git doesn't appear until the project is manually refreshed or DBeaver restart

#### Steps to reproduce, if exist:
1. Create a project from git that has a connection inside a folder
2. Drag the connection to another project that exists only on local machine

**Expected:** Connection appears in the new project
**Actual:** Connection disappears from everywhere until restart

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
