### ISSUE TITLE
New task type: shell commands

### ISSUE THREAD

**Issue by mbissinger** [dbeaver/dbeaver#14835]
I was wondering whether it is possible to have a new task type (Database -> Tasks -> Create new task) for executing shell commands (see screenshots below for an illustration). Executing shell commands is already possible before/after connecting/disconnecting to a database (Edit connection wizard -> Connection settings -> Shell Commands). Like there it would be nice if variables (e.g. ${database}) could be used in the command definition.

Thanks a lot for consideration!

![image](https://user-images.githubusercontent.com/26654668/145177405-dbdc3aa2-2122-4a41-977c-9ccd4400eb2f.png)

![image](https://user-images.githubusercontent.com/26654668/145177911-23a1fe86-eb29-4170-b3e9-3058ba598d8d.png)

**Comment by Skydiveroid** [comment]
Thank you for the idea.

**Comment by mbissinger** [comment]
Hi,
again thank you for considering my feature request!

If I may add a further detail: would it be possible to have variables, which correspond to the currently selected table or even row (passed by e.g. primary keys)? In order to be consistent to already existing variables these could be named ${database.table} or ${database.table.row}.

**Comment by ShadelessFox** [comment]
In order to support such variables, this task must be associated with data source, which is not ideal for most use cases of this task.

As an initial implementation, we could just add basic support for shell commands.

After that, a separate issue may be created to support data source-specific variables.

**Comment by ShadelessFox** [comment]
Feature was implemented in Enterprise, Ultimate, and Lite editions:

![java_VrMCv1inSy](https://user-images.githubusercontent.com/35821147/161794896-95a94f51-8b65-4c54-ab37-6e26d7cc2fb8.png)

**Comment by Matvey16** [comment]
Working directory property is ignored

**Comment by Matvey16** [comment]
Verified
