### ISSUE TITLE
Retrieve DDL for temporary indexes (or table)

### ISSUE THREAD

**Issue by adidiot** [dbeaver/dbeaver#14838]
Hello,

On a Oracle DB I received this error message when trying to retrieve DDL for temporary index ?
Is that a bug or is it not possible to retrieve DDLs for this type of objetcs ?

  SQL-Fehler [31603] [99999]: ORA-31603: Objekt "TMP_KALENDER_IX_END1" vom Typ INDEX  in Schema "PPS_STD" nicht gefunden
  ORA-06512: in "SYS.DBMS_METADATA", Zeile 6069
  ORA-06512: in "SYS.DBMS_METADATA", Zeile 8666
  ORA-06512: in Zeile 1
  
    Error : 31603, Position : 7, Sql = SELECT DBMS_METADATA.GET_DDL('INDEX', :1 , :2 ) TXT FROM DUAL, OriginalSql = SELECT DBMS_METADATA.GET_DDL('INDEX', ?, ?) TXT FROM DUAL, Error Msg = ORA-31603: Objekt "TMP_KALENDER_IX_END1" vom Typ INDEX  in Schema "PPS_STD" nicht gefunden
  ORA-06512: in "SYS.DBMS_METADATA", Zeile 6069
  ORA-06512: in "SYS.DBMS_METADATA", Zeile 8666
  ORA-06512: in Zeile 1
  
    ORA-31603: Objekt "TMP_KALENDER_IX_END1" vom Typ INDEX  in Schema "PPS_STD" nicht gefunden
  ORA-06512: in "SYS.DBMS_METADATA", Zeile 6069
  ORA-06512: in "SYS.DBMS_METADATA", Zeile 8666
  ORA-06512: in Zeile 1

Best Regards
Alex

**Comment by Skydiveroid** [comment]
@adidiot, thank you for the report. We will look into that.

**Comment by E1izabeth** [comment]
Does this issue still actual for the latest DBeaver version?

**Comment by Axidi** [comment]
Seems to wotk with the current DBever version (Version 23.0.1.202303201052)

**Comment by E1izabeth** [comment]
Thank you for checking
