### ISSUE TITLE
[Database] [Tools] menu incorrect when either Session Manager or Locks Manager is open

### ISSUE THREAD

**Issue by taf1-cornell-edu** [dbeaver/dbeaver#14830]
#### System information: 
- Operating system: Windows 10 Enterprose Ver 1909
- DBeaver version:  21.3.0.2021111281534

#### Connection specification:
- Database name and version:  Postgres 13.x

#### Describe the problem you're observing:
From the main menu, under [Database], [Tools], the submenu items are ([Session Manager] [Lock Manager] [Create new task ...] .)   Once either Session Manager or Lock Manager is running, the submenu contains only [Create new task ...].   The [Session Manager] and [Lock Manager] menu items disappear.   Once the running tool (either Session Manager or Lock Manager) is closed, the 2 menu items reappear.  There is currently no way to run both Session Manager and Lock Manager at the same time.  If there is a 'one-tool-at-a-time' restriction, the 2 menu items should remain and only be greyed out.

**Comment by Skydiveroid** [comment]
@taf1-cornell-edu, could you please provide more information on this issue? Video or gif will be perfect. Thx

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still present - feel free to reopen it with additional info.
