### ISSUE TITLE
export sql data lost the ‘’ single quotes

### ISSUE THREAD

**Issue by moshimowang326** [dbeaver/dbeaver#14849]
#### System information: 
- Operating system (distribution) and version: windows 10
- DBeaver version: 21.2.5.202111141807

#### Describe the problem you're observing:

<img width="467" alt="企业微信截图_16390155068263" src="https://user-images.githubusercontent.com/54019970/145321109-f9652723-39a7-4904-bda1-fce5d54c6c94.png">

when I exorpt the data ,  ‘I’  lost the  single quotes.
<img width="376" alt="企业微信截图_163901669354" src="https://user-images.githubusercontent.com/54019970/145323000-d7cfc946-c959-47d3-a26c-9a729cb01383.png">

**Comment by zhangheng0027** [comment]
I found the same thing

**Comment by LonwoLonwo** [comment]
Thanks for the bug report. 

This bug has already been fixed https://github.com/dbeaver/dbeaver/issues/14755
and the fix will be available in DBeaver 21.3.1 version
