### ISSUE TITLE
Can't show chinese simplified(简体中文) correctly while drag a .sql files into sql editor

### ISSUE THREAD

**Issue by Oceanboy-free** [dbeaver/dbeaver#14862]
hello,

I found that my dbeaver can't show chinese simplified(简体中文) correctly while I try to drag a .sql files into sql editor.

But if I try to import it in a sql editor use the right import button,the chinese  simplified(简体中文) could be shown perfect

#### System information: 
- Operating system (distribution) and version:Windows 11 21H2
- DBeaver version:21.3.0.202111281534
- Additional extensions

#### Connection specification:
- Database name and version:oracle 11g R2
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

hello,
I found that my dbeaver can't show chinese simplified(简体中文) correctly while I try to drag a .sql files into sql editor.

But if I try to import it in a sql editor use the right import button,the chinese  simplified(简体中文) could be shown perfect

#### Steps to reproduce, if exist:
just drap the .sql file into sql editor
#### Include any warning/errors/backtraces from the logs

[Dbeaver  Error and files.zip](https://github.com/dbeaver/dbeaver/files/7691350/Dbeaver.Error.and.files.zip)

**Comment by ShadelessFox** [comment]
Hello @Daniel-W7,

Would you please record a video showing your issue?

**Comment by Oceanboy-free** [comment]
Of course!
You can follow this step to reproduce the situation
[dbeaver.sql.zip](https://github.com/dbeaver/dbeaver/files/7700663/dbeaver.sql.zip)
n

**Comment by ShadelessFox** [comment]
I see, thank you. We're going to review it soon.

**Comment by Matvey16** [comment]
@Daniel-W7 Thank you for the report. That issue happens because different encoding is used in different options of opening the script. We will work on that. As a workaround you can change the default encoding in workspace

![dbeaver_9PLIYnF8QN](https://user-images.githubusercontent.com/82543000/145820057-24ddeb70-023c-4b06-a48a-a86d237ae49e.png)

**Comment by Oceanboy-free** [comment]
Wow，Thank you very much.

This fix my problem!!!

**Comment by LonwoLonwo** [comment]
Hello @Daniel-W7 

We enhanced work with encodings till our last answer.
Could you please check your issue using the latest DBeaver version?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
