### ISSUE TITLE
Menu/FE option to disable SQL code editor parse & beautification

### ISSUE THREAD

**Issue by surpavan** [dbeaver/dbeaver#14866]
**Is your feature request related to a problem? Please describe.**
When we use sql statement with large list of ids, it hangs or slows down the editor; so a shortcut or questionaccess to option to disable and enable SQL statement coloring/beautification, paring etc.

**Describe the solution you'd like**
Button on toolbar to quick enable & disable SQL editor parse and beautification - as it is an overhead.

**Describe alternatives you've considered**
Many options have to tweaked in settings to disable each one - formatting, code completion etc.

**Additional context**
Only when query is large or there are many queries in a single file or when keeping 1000s of ids in query.

**Comment by Skydiveroid** [comment]
Thank you for the request

**Comment by surpavan** [comment]
back to review board :(

**Comment by surpavan** [comment]
Thank you.
