### ISSUE TITLE
Default the proxy setting for Drivers.

### ISSUE THREAD

**Issue by RickSaavedra** [dbeaver/dbeaver#14860]
#### System information: 
- Windows 10
- 21.3.0
- 11.0.12+7

#### Describe the problem you're observing:

We are trying to default the install to include default proxy information for drivers to download. Can this be setup somehow using i.e. (ini file, command line options)?

**Comment by ShadelessFox** [comment]
Hello @RickSaavedra,

Proxy settings, among others, are stored within the workspace folder.

Take a look at https://github.com/dbeaver/dbeaver/wiki/Workspace-Location.
