### ISSUE TITLE
Data Transfer wizard does not persist finalizers configuration between runs when exporting to file

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14881]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.3.1

#### Steps to reproduce, if exist:
1. Open export wizard for any table
2. In output settings under execute process type something like `notepad ${file}`
3. Perform export
4. Start new export and try to start it without changing any settings

**Expected:** Export is executed with the same settings as the previous one
**Actual:** Export can't be started because `Configuration for 'Execute process' is incomplete`

![4iJKTyTEHc](https://user-images.githubusercontent.com/82543000/145777677-a8633c64-bac5-49dc-b3eb-c047805e1656.gif)

**Comment by ShadelessFox** [comment]
Currently, we don't save finalizers' settings between wizard runs. Perhaps we should do it.

**Comment by ShadelessFox** [comment]
This issue may have been fixed in other places too.

**Comment by Matvey16** [comment]
Verified
