### ISSUE TITLE
Astra DB Wiki Page

### ISSUE THREAD

**Issue by alexleventer** [dbeaver/dbeaver#14891]
I'd like to add a page to your wiki with instructions on how to connect to Astra DB. What is the process to propose content changes to your wiki?

**Comment by flambchap** [comment]
Hello. We don't have a process on that at the moment. I suggest writing a page as a comment here. We'll add it to our wiki. Thank your contribution.

**Comment by melienherrera** [comment]
# Astra DB
## Connecting to Astra DB

### Prerequisites
**Astra DB** is a serverless, database-as-a-service (DaaS) built on Apache Cassandra. Before connecting, we must create and configure Astra DB as a custom driver in DBeaver. 

With these instructions, it is assumed that you have already created a database in Astra DB (make sure it is in the "Active" state!), generated an[ application token](https://docs.datastax.com/en/astra/docs/manage-application-tokens.html), and downloaded your [secure connect bundle](https://docs.datastax.com/en/astra/docs/obtaining-database-credentials.html) from Astra DB. 

### Procedure
**JDBC DRIVER**
Download the JDBC driver from the DataStax website:
1. Go to https://downloads.datastax.com/#odbc-jdbc-drivers
2. Select **Simba JDBC Driver for Apache Cassandra.**
3. Select **JDBC 4.2**
4. Read the license terms and accept it by clicking the checkbox.
5. Hit the blue **Download** button
6. Once the download completes, unzip the downloaded file.

**IMPORT DRIVER**
Create a new driver for Astra DB in DBeaver:
1. Navigate to **Database** on the top of your screen then select **Driver Manager.**
<img width="293" alt="Screen Shot 2021-12-21 at 2 34 07 PM" src="https://user-images.githubusercontent.com/85907755/147006326-6a8b7f50-9267-4e2c-b48a-511ec357351d.png">

2. Click the **New** button.
3. In the **Libraries** tab, click the **Add File** button.
4. Locate the directory where you unzipped the driver download and add the` CassandraJDBC42.jar` file.
5. Click the **Find Class** button which should identify the driver class as `com.simba.cassandra.jdbc42.Driver.`
6. In the Settings tab, set the following:

- Driver Name: `Astra DB`
- Driver Type: `Generic`
- Class Name: `com.simba.cassandra.jdbc42.Driver`
![](https://community.datastax.com/storage/attachments/2385-dbeaver-01-create-driver.png)
7. Click the **OK** button to save the driver.

At this point, you should see **Astra DB** as one of the drivers in the list:
![](https://community.datastax.com/storage/attachments/2373-dbeaver-02-driver-manager.png)

**NEW CONNECTION**
Connect to your Astra DB in DBeaver:
1. Open the **New Database Connection** dialog box.
2. Select **Astra DB** from the list of drivers.
3. in the **Main** tab, set the **JDBC URL** to: `jdbc:cassandra://;AuthMech=2;TunableConsistency=6;SecureConnectionBundlePath=/path/to/secure-connect-bundle.zip`

**Note:** Make sure you replace **/path/to/secure-connect-bundle.zip** and specify the full path to your own secure bundle.

4. In the **Username** field, enter the string `token`.
5. In the **Password** field, paste the value of the token that you created in the **Prerequisites** section above. The token looks something like: `AstraCS:AbC...XYz:123...efg`
![](https://community.datastax.com/storage/attachments/2374-dbeaver-03-new-connection.png)
6. Click on the **Connection details (name, type, ...)** button
7. In the **Connection name** field, give your DB connection a name: 
![](https://community.datastax.com/storage/attachments/2402-dbeaver-04-connection-details.png)
8. Click on the **Test Connection** button to confirm that your driver configuration is working:
![](https://community.datastax.com/storage/attachments/2395-dbeaver-05-test-connection.png)
 9. Click on the **Finish** button to save the connection settings.

### Final Test
Connect to your Astra DB. If the connection was successful, you should be able to explore the keyspaces and tables in your DB on the left-hand side of the UI. 

Here's an example output:
![](https://community.datastax.com/storage/attachments/2396-dbeaver-06-explore.png)

**Comment by melienherrera** [comment]
> Hello. We don't have a process on that at the moment. I suggest writing a page as a comment here. We'll add it to our wiki. Thank your contribution.

Hi there! Just added the page as a comment. Let us know if you have any questions/changes, thanks!

**Comment by Skydiveroid** [comment]
Thank you for your conribution!

**Comment by tati-kru** [comment]
@melienherrera thank you for your comment and article. I'm afraid we do not add articles about connection to some database if this connection is based on a generic driver. We have a special article about generic connections in our wiki: https://github.com/dbeaver/dbeaver/wiki/Database-drivers. 
If you want to make a connection page for AstraDB in DBeaver you can send us a pull request as it's described in the article above.

**Comment by melienherrera** [comment]
@tati-kru Hi there! Thanks for the suggestion! Created the issue here: #15006
