### ISSUE TITLE
h2 database no error, no tables

### ISSUE THREAD

**Issue by hktalent** [dbeaver/dbeaver#14896]
jdbc:h2:/Users/51pwn/MyWork/for_hacker_md/config/dependency-check/odc.mv.db;AUTOCOMMIT=ON;CACHE_SIZE=65536;RETENTION_TIME=1000;MAX_COMPACT_TIME=10000;
<img width="688" alt="image" src="https://user-images.githubusercontent.com/18223385/145943128-5a52cd6b-d602-41b2-92c1-c0c3f7207090.png">
<img width="337" alt="image" src="https://user-images.githubusercontent.com/18223385/145943257-95a609d7-a96f-4f88-9ab2-cbc5b05152be.png">

$ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-bre_2021_10_20_23_15-b00)
OpenJDK 64-Bit Server VM (build 25.312-b00, mixed mode)
<img width="443" alt="image" src="https://user-images.githubusercontent.com/18223385/145944063-3bfa318c-b433-4756-8c84-3ae00b74f6a5.png">

**Comment by LonwoLonwo** [comment]
Hello @hktalent 

What H2 database version do you use? And what driver version?

Also, please check your connection settings. "Show system objects" setting must be enabled for INFORMATION SCHEMA content.

![2021-12-14 09_46_36-DBeaver Ultimate 21 3 1 - Sessions - postgres 13 3](https://user-images.githubusercontent.com/45152336/145947377-5872519d-f13b-453a-ae8f-e5978edbe701.png)

**Comment by hktalent** [comment]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/18223385/145949921-c317aa4b-218b-4e40-95cf-a764eb0d3a3b.png">
<img width="790" alt="image" src="https://user-images.githubusercontent.com/18223385/145950435-dfcdb414-94ed-4e90-8aa7-0e8f690ec6bc.png">

**Comment by hktalent** [comment]
<img width="436" alt="image" src="https://user-images.githubusercontent.com/18223385/145950789-58342198-15ae-4a41-9c25-0cba3e22bca7.png">
@LonwoLonwo

**Comment by hktalent** [comment]
in Mac OS,you can try:
@LonwoLonwo
```bash
brew  install dependency-check
dependency-check --updateonly
```

now ,you can found db file

```bash
cd /usr/local/var/dependencycheck
ls   /usr/local/var/dependencycheck/odc.mv.db
```

**Comment by hktalent** [comment]
data.connection_string=jdbc:h2:file:%s;AUTOCOMMIT=ON;CACHE_SIZE=65536;RETENTION_TIME=1000;MAX_COMPACT_TIME=10000;
data.user=dcuser
data.password=DC-Pass1337!
data.driver_name=org.h2.Driver

**Comment by LonwoLonwo** [comment]
Can you see objects in Information Schema now?

**Comment by hktalent** [comment]
> Can you see objects in Information Schema now?

yes @LonwoLonwo but,
<img width="252" alt="image" src="https://user-images.githubusercontent.com/18223385/145976584-9e1b6054-e279-42ba-a9a7-42e88dd376c7.png">

**Comment by hktalent** [comment]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/18223385/145976752-314dc56f-792c-471f-93f3-6f332490d4f3.png">
<img width="461" alt="image" src="https://user-images.githubusercontent.com/18223385/145976926-8f4d5065-674a-455c-ab04-ee023941bed0.png">

**Comment by LonwoLonwo** [comment]
We use H2 drivers info to get the tables list. So what can we do if the "TABLES" table in INFIRMATION_SCHEMA does not return any rows to you? Do you have any tables in the PUBLIC schema?

**Comment by rockflo** [comment]
I am experiencing exactly the same problem today.
And from a web h2 console I could check that I do indeed have tables in my schema (which I assume to be the PUBLIC one)
DBeaver 25.1.5
H2 Driver 2.1.210
