### ISSUE TITLE
Postgresql: error when counting records in queries with jsonb ? operator

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#14895]
Here is an example of the query with '?' operator. It executes correctly
![изображение](https://user-images.githubusercontent.com/16996529/145931419-437be910-908b-4f04-9f14-cc7bed19c368.png)

When trying to count records (the button in the toolbar) I get an error.
![изображение](https://user-images.githubusercontent.com/16996529/145931750-6292df9c-8b80-42ee-869d-8e9e073dc115.png)
![изображение](https://user-images.githubusercontent.com/16996529/145931775-5214cea2-3f05-4d18-b320-b3c525a986ae.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
Interesting. Looks like that the driver thinks that `?` is an unbound procedure parameter.

We'll see if we can do anything about it.

**Comment by Matvey16** [comment]
Verified
