### ISSUE TITLE
Release page for 21.3.1 has dbeaver-ce-21.3.0-macos-aarch64.dmg as first entry

### ISSUE THREAD

**Issue by gerardkok** [dbeaver/dbeaver#14898]
#### System information: 
- Operating system (distribution) and version: macos 11.6.1, Intel + M1
- DBeaver version: 21.3.1
- Additional extensions: aarch64

#### Connection specification:
- Database name and version: n/a
- Driver name: n/a
- Do you use tunnels or proxies (SSH, SOCKS, etc)? n/a

#### Describe the problem you're observing:

The release page for 21.3.1 (https://github.com/dbeaver/dbeaver/releases/tag/21.3.1) has dbeaver-ce-21.3.0-macos-aarch64.dmg as first entry, and this misguides our [autopkg](https://github.com/autopkg/autopkg) recipe for DBeaverCE for arm64; it will not 'see' the correct dbeaver-ce-21.3.1-macos-aarch64.dmg download. In the grand scheme of things not important, but on the other hand I assume it can also be easily fixed.

#### Include any warning/errors/backtraces from the logs
n/a

**Comment by ShadelessFox** [comment]
Hello @gerardkok,

Thanks for the report.

We've removed the `dbeaver-ce-21.3.0-macos-aarch64.dmg` entry.

It should work now.

**Comment by gerardkok** [comment]
Thanks for the quick fix! Our autopkg recipe works again now.
