### ISSUE TITLE
Disable Numeric Formatting option doesn't affect array contents

### ISSUE THREAD

**Issue by lukaseder** [dbeaver/dbeaver#14904]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows [Version 10.0.22000.318]
- DBeaver version: 21.2.4.202111011413
- Java version: 17+35-2724

#### Connection specification:
- Database name and version: Oracle 21c
- Driver name: ojdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

When working with Oracle's nested collection types, I find it hard to read numbers because of conflicting element spearators and decimal separators.

#### Steps to reproduce, if exist:

Run this query:

```sql
create type n as table of number;
select n(1234, 5678) from dual;
```

The result is:

```
|N(1234,5678)|
|------------|
|[1234,5678] |
```

But Dbeaver displays it like this:

![image](https://user-images.githubusercontent.com/734593/146018888-332513b0-f224-4d09-8d31-e9a920d3c2b8.png)

It's very confusing. I couldn't find any setting where I can turn off decimal separators, is there? If not, I'd love to request:

- A setting to configure decimal separators
- This display should be fixed somehow to visually distinguish between the element separator and the decimal separator if any. But in my opinion, numbers within lists should never have any separators...

**Comment by uslss** [comment]
@lukaseder , you could disable numeric formatting in preferences
![image](https://user-images.githubusercontent.com/31996417/146150577-34c023f7-cd91-4902-aaad-5aee1151d3bb.png)

**Comment by lukaseder** [comment]
That doesn't affect array contents, see:

![image](https://user-images.githubusercontent.com/734593/146154268-69b40511-53a4-40d9-bde1-e53ebf8958ad.png)

Compared to enabling it:

![image](https://user-images.githubusercontent.com/734593/146154226-dbbb58b5-ec34-47ec-8173-0d6c0884f34d.png)

**Comment by uslss** [comment]
thanks for the investigation and report

**Comment by uslss** [comment]
verified
