### ISSUE TITLE
Connection settings window is not resized when additional tab is opened

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14915]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.3.1

#### Steps to reproduce, if exist:
1. Open connection settings window
2. Open SSH tab
3. Click on advanced settings

**Expected:** Window is resized or scroll bar appears
**Actual:** Can't change settings until window is manually resized

![vzaMNyhRiX](https://user-images.githubusercontent.com/82543000/146184211-f4e77cd2-e08b-4316-905b-3b8dedbf1c8b.gif)

**Comment by E1izabeth** [comment]
The issue is not reproducible on DBeaver 23.1.3.
