### ISSUE TITLE
Views with comments won't be saved.

### ISSUE THREAD

**Issue by mmdext** [dbeaver/dbeaver#14910]
#### System information: 
- OS:Windows 10
- DBeaver version:21.3.1.202112130652

#### Connection specification:
- Oracle
- Driver name: oracle.jdbc.OracleDriver
- No proxy

#### Describe the problem you're observing:
1.View DDL with comment will cause an error when saving.
2."Compact form" will cause comments or something else lost when saving.

#### Steps to reproduce, if exist:
Open and edit a view and add comment to it by editing the comment box for the first time , save it and it works.
Then close and open the view again, edit something in the declaration tab and save it, this will cause an error because the comment ddl is in the edit box and probably the script is not executed in "script mode".
Let's toggle the form from "Full DDL" to "Compact form" by selecting the combox below, this will clear the comment dll so the change will be saved, but it causes the comment lost .

**Comment by uslss** [comment]
thanks for the report

duplicates #13627.
