### ISSUE TITLE
Please add support for the error line number to the error message for DB2

### ISSUE THREAD

**Issue by LexxaRRioo** [dbeaver/dbeaver#14929]
When using DB2 with DBeaver, it is difficult to debug sql queries without specific line number in the error message.
If possible for the DB2 engine, add support for the error line number to the error message.

Similar FR for sql server: 
https://github.com/dbeaver/dbeaver/issues/4816

**Comment by Skydiveroid** [comment]
Thank you for the idea.

**Comment by Matvey16** [comment]
Seems like it won't be possible for DB2 as the database doesn't return the number of the line with error, it only sends the error for the entire query regardless if it is written in a single or multiple lines. We already have the functionality to highlight the problematic query in a script, but I don't think more detailed message is possible.
