### ISSUE TITLE
Violation of Сp1251 encoding when opening an existing script

### ISSUE THREAD

**Issue by Sergey-V-R** [dbeaver/dbeaver#14935]
System information: 
- Operating system (distribution) and version: Windows 10 Pro x64.
- DBeaver version:  21.2.5.202111141807
- Additional extensions: N/A

I am creating a script with comments in Russian. The script is saved in Сp1251 encoding.
![01_Script on creation](https://user-images.githubusercontent.com/96280439/146525408-1d1001b2-4d75-4963-a244-5aa1287fcfa7.PNG)
![06_Script in the FAR editor](https://user-images.githubusercontent.com/96280439/146525437-252731ae-6346-437f-beb1-c47ad4ad2c2f.PNG)

If the script is closed and opened again, then it opens in a different encoding, comments in Russian are not readable.
![08_Script after opening](https://user-images.githubusercontent.com/96280439/146525739-6c322e2a-af86-43f8-9972-05bc2c75b161.PNG)

The workspace settings are set to Cp1251 encoding.
![05_Workspace properties](https://user-images.githubusercontent.com/96280439/146526154-65ed2b7f-69b8-473b-97c8-dad9d45abc5d.png)

How to make DBeaver open scripts in Сp1251 encoding?

**Comment by LonwoLonwo** [comment]
Hello @Sergey-V-R 

Can you please check the workaround (about option in the -ini file) from this ticket: https://github.com/dbeaver/dbeaver/discussions/12193?

**Comment by Sergey-V-R** [comment]
Thanks @LonwoLonwo, I'll check.

**Comment by Sergey-V-R** [comment]
Didn't help (closed DBeaver, changed DBeaver.ini, opened DBeaver, opened the script).

-startup
plugins/org.eclipse.equinox.launcher_1.6.300.v20210813-1054.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.300.v20210828-0802
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-DFile.encoding=Cp1251

**Comment by Matvey16** [comment]
@Sergey-V-R Can you please attach this file, so we can replicate this issue in our environment?

**Comment by Sergey-V-R** [comment]
Addition.
The problem is different. Dbeaver on my computer cannot correctly open a file whose name is typed in Cyrillic. Dbeaver can save such a file, 
![20_Script on creation, UTF-8](https://user-images.githubusercontent.com/96280439/147732702-b8ebf67f-1ec6-4405-a6d3-857c1a2e5609.PNG)

and upon opening it gives the file a new default name.
![22_Script after opening, UTF-8](https://user-images.githubusercontent.com/96280439/147732710-fbcd0782-295a-4189-adce-18ab79e0a246.PNG)

Perhaps because of this, there is a problem with the CP-1251 encoding in the text of the script.

The script is in CP-1251 encoding:
[Список параметров CP-1251.txt](https://github.com/dbeaver/dbeaver/files/7792000/CP-1251.txt)

The script is in UTF-8 encoding.
[Список параметров UTF-8.txt](https://github.com/dbeaver/dbeaver/files/7792001/UTF-8.txt)

**Comment by Matvey16** [comment]
@Sergey-V-R Have you tried picking the default encoding in workspace settings?

**Comment by Sergey-V-R** [comment]
Set the default encoding (cp251). Conducted several tests on creating and opening scripts. It turned out the following:
1. If the file is opened from the list of scripts using F3, then the file name and text in Cyrillic are displayed correctly;
2. If there is no file in the list using F3, then I open it using Ctrl + Alt + Shift + O. In this case, everything that is typed in Cyrillic is displayed incorrectly. The Cyrillic text in the script is replaced with symbols, and the Cyrillic file name is replaced with the default name.

**Comment by Matvey16** [comment]
@Sergey-V-R Thank you for the report

**Comment by LonwoLonwo** [comment]
Hello @Sergey-V-R 

Now, in DBeaver, we use UTF-8 encoding by default.
Could you please check if your issue is solved?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
