### ISSUE TITLE
Export button is greyed out in result panel in version 21.3.1

### ISSUE THREAD

**Issue by leonbloy** [dbeaver/dbeaver#14930]
Buttons in the low icons bar in the result panel behave strangely, I think this started happening after upgrading to 21.3.1

Steps: 
 
- Start DBeaver, connect, open SQL script window,  reset perspective 
- Reveal the QueryManager view, and click inside it (select some row)
- Run some SELECT query from the script window (preferably that returns more rows than the page size) 

First result: inside the Result panel, the export icon in the lower bar should be enabled. Often (not always), it's not.
When it's disabled (greyed out), it can be enabled by the trick of right clicking in the result panel (the context menu shows the Export option enabled) 

Similar things happen to the icons on the left of the export button (fetch all rows...) , they display as disabled (greyed out) when the Result panel loses focus, by clicking inside the QueryManager (I don't think this is intended/desired - other icons as "Configure" and "Calculate total row count" are always enabled)

Suing Version 21.3.1, Windows 10

**Comment by uslss** [comment]
@leonbloy , unfortunately, cannot reproduce it. Could you provide a video of the issue? Also, is there something in the [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still present - feel free to reopen it.

**Comment by rccc** [comment]
same for me in Version 22.0.3.202204170718, icon is grey, not active. Sometimes it works.

**Comment by yeozhenqiang** [comment]
Same here, in Version 22.0.2.202204041542, I occasionally encounter the greyed out export button. However, the **right-click workaround** suggested by the OP works well for me to continue with the data export.

**Comment by diegogurpegui** [comment]
Same issue here. As soon as I right-click, the button magically enables itself.

DBeaver Version 22.0.4.202205011839

**Comment by sergeypolevich** [comment]
same issue on MacOS just after update to 22.1.1.202206261508.
(With a right-click, the button does not enables itself)

**Comment by poltpolt** [comment]
bug still present in 22.1.2 Linux RPM build

**Comment by mastachaos** [comment]
I just started encountering this issue on 22.2.0 (Windows 11 x64)

**Comment by AapoTammisto** [comment]
> I just started encountering this issue on 22.2.0 (Windows 11 x64)

Me too, same version. RMB workaround still works though.

**Comment by reginakwon** [comment]
Also have this issue once I upgraded to 22.2.0 (Win 10 x64). Also able to work around with right-click (thanks diegogurpegui!).

**Comment by robsimpson** [comment]
Confirming this bug on MacOS Version 22.2.4.202211061524 (Ventura 13.0, M1), just updated this morning. I didn't experience it in the previous version of DBeaver CE

**Comment by capriceZ** [comment]
same issue and resolved by right click. Version 22.2.3.202210231354
