### ISSUE TITLE
Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.

### ISSUE THREAD

**Issue by aion1998** [dbeaver/dbeaver#14934]
I think this works well
But when I open a table, an error message occurred

errorMsg:` Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.`

**Comment by uslss** [comment]
please, describe the issue accordingly to the [template](https://github.com/dbeaver/dbeaver/issues/new?assignees=&labels=bug%2C+wait+for+review&template=bug_report.md&title=)
