### ISSUE TITLE
Unable to connect to Google Cloud Spanner emulator

### ISSUE THREAD

**Issue by ilyafrank2021** [dbeaver/dbeaver#14942]
I am unable to connect to Google Cloud Spanner emulator (non-emulator works fine). I followed the instructions here

https://medium.com/google-cloud/cloud-spanner-in-dbeaver-853998faa0ba

When I connect, it looks like it worked but when I try to expand the tables, I get this error.
I am able to connect from DbVisualizer, so I don't think it's an issue with the emulator.

SQL Error [3]: INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE; Did you mean TABLE_NAME? [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^ - Statement: 'SELECT TABLE_CATALOG AS TABLE_CAT, TABLE_SCHEMA AS TABLE_SCHEM, TABLE_NAME,
       CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END AS TABLE_TYPE,
       NULL AS REMARKS, NULL AS TYPE_CAT, NULL AS TYPE_SCHEM, NULL AS TYPE_NAME,
       NULL AS SELF_REFERENCING_COL_NAME, NULL AS REF_GENERATION
FROM INFORMATION_SCHEMA.TABLES AS T
WHERE UPPER(TABLE_CATALOG) LIKE @p1
  AND UPPER(TABLE_SCHEMA) LIKE @p2
  AND UPPER(TABLE_NAME) LIKE @p3
  AND (
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p4
        OR
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p5
    )
ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME'
  INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE; Did you mean TABLE_NAME? [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^ - Statement: 'SELECT TABLE_CATALOG AS TABLE_CAT, TABLE_SCHEMA AS TABLE_SCHEM, TABLE_NAME,
       CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END AS TABLE_TYPE,
       NULL AS REMARKS, NULL AS TYPE_CAT, NULL AS TYPE_SCHEM, NULL AS TYPE_NAME,
       NULL AS SELF_REFERENCING_COL_NAME, NULL AS REF_GENERATION
FROM INFORMATION_SCHEMA.TABLES AS T
WHERE UPPER(TABLE_CATALOG) LIKE @p1
  AND UPPER(TABLE_SCHEMA) LIKE @p2
  AND UPPER(TABLE_NAME) LIKE @p3
  AND (
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p4
        OR
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p5
    )
ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME'
  INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE; Did you mean TABLE_NAME? [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^ - Statement: 'SELECT TABLE_CATALOG AS TABLE_CAT, TABLE_SCHEMA AS TABLE_SCHEM, TABLE_NAME,
       CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END AS TABLE_TYPE,
       NULL AS REMARKS, NULL AS TYPE_CAT, NULL AS TYPE_SCHEM, NULL AS TYPE_NAME,
       NULL AS SELF_REFERENCING_COL_NAME, NULL AS REF_GENERATION
FROM INFORMATION_SCHEMA.TABLES AS T
WHERE UPPER(TABLE_CATALOG) LIKE @p1
  AND UPPER(TABLE_SCHEMA) LIKE @p2
  AND UPPER(TABLE_NAME) LIKE @p3
  AND (
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p4
        OR
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p5
    )
ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME'
    INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE; Did you mean TABLE_NAME? [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^
    INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE; Did you mean TABLE_NAME? [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^
      INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE; Did you mean TABLE_NAME? [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^
      INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE; Did you mean TABLE_NAME? [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^

#### System information: 
- Mac OS
- DBeaver version: 21.3.1.202112130652

#### Connection specification:
- Database name and version: Google Cloud Spanner emulator
- Driver name: Whatever came with DBeaver, looks like google-cloud-spanner-jdbc-2.5.5.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
See above
#### Include any warning/errors/backtraces from the logs

!ENTRY org.jkiss.dbeaver.model 4 0 2021-12-09 12:44:37.211
!MESSAGE INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE; Did you mean TABLE_NAME? [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-12-09 12:44:37.211
!MESSAGE INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE; Did you mean TABLE_NAME? [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^
!STACK 0
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE; Did you mean TABLE_NAME? [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onClose(GrpcDirectStreamController.java:149)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at com.google.cloud.spanner.spi.v1.SpannerErrorInterceptor$1$1.onClose(SpannerErrorInterceptor.java:100)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by flambchap** [comment]
Hello @ilyafrank2021. Unfortunately, I cannot reproduce your issue. Could you please tell me what DBeaver version you use?

**Comment by ilyafrank2021** [comment]
Version 21.3.1.202112130652

**Comment by ilyafrank2021** [comment]
> Hello @ilyafrank2021. Unfortunately, I cannot reproduce your issue. Could you please tell me what DBeaver version you use?

21.3.1.202112130652

**Comment by uslss** [comment]
@ilyafrank2021 sorry for the late response. Is the issue still reproducible for you against 21.3.4?

**Comment by ilyafrank2021** [comment]
> @ilyafrank2021 sorry for the late response. Is the issue still reproducible for you against 21.3.4?

It's better! I can actually connect and run queries.
But there is another issue. If I shut down DBeaver and then open it again, the previously working connection fails to reconnect, showing me a NullPointerException.
I found a workaround - right click on the connection, Edit Connection, then immediately press OK, then right click again and Connect. It's able to connect again. But if I shut it down and restart - same issue, NPE, again.

**Comment by ilyafrank2021** [comment]
> @ilyafrank2021 sorry for the late response. Is the issue still reproducible for you against 21.3.4?

Here's the more complete NPE

Caused by: java.lang.NullPointerException
        at java.base/java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
        at java.base/java.util.concurrent.ConcurrentHashMap.putAll(Unknown Source)
        at java.base/java.util.Properties.putAll(Unknown Source)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getAllConnectionProperties(JDBCDataSource.java:265)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:138)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:136)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:111)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:108)
        at org.jkiss.dbeaver.ext.spanner.model.SpannerDataSource.<init>(SpannerDataSource.java:37)
        at org.jkiss.dbeaver.ext.spanner.SpannerDataSourceProvider.openDataSource(SpannerDataSourceProvider.java:51)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:904)

**Comment by ilyafrank2021** [comment]
Any updates on this?

**Comment by adi-pedro** [comment]
Hi.

I had the exactly issue and updating the version of the emulator to cloud-sdk:368.0.0 solved the problem.

**Comment by ilyafrank2021** [comment]
> Hi.
> 
> I had the exactly issue and updating the version of the emulator to cloud-sdk:368.0.0 solved the problem.

Thanks, I tried this but it did not fix the issue for me

**Comment by LonwoLonwo** [comment]
Hello @ilyafrank2021 
Because we can't reproduce this issue, I would like to ask you again.
Is the issue still reproducible for you against 22.3.5?

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it.

**Comment by shyuen** [comment]
I'm getting the same TABLE_TYPE issue on both DBeaver(22.2.2.202309132212) and Liquibase (4.23.1) when attempting to do any operations against the Spanner emulator.

Weird thing is that DBeaver appears to be connected to the Spanner emulator, but I will get the `TABLE_TYPE` error dialog pop up on when I try to expand the `tables` drop down.
![image](https://github.com/dbeaver/dbeaver/assets/12534005/e05d3732-43da-4a26-8f9d-edc0ae294bce)
```
SQL Error [3]: INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^ - Statement: 'SELECT TABLE_CATALOG AS TABLE_CAT, TABLE_SCHEMA AS TABLE_SCHEM, TABLE_NAME,
       CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END AS TABLE_TYPE,
       NULL AS REMARKS, NULL AS TYPE_CAT, NULL AS TYPE_SCHEM, NULL AS TYPE_NAME,
       NULL AS SELF_REFERENCING_COL_NAME, NULL AS REF_GENERATION
FROM INFORMATION_SCHEMA.TABLES AS T
WHERE UPPER(TABLE_CATALOG) LIKE @p1
  AND UPPER(TABLE_SCHEMA) LIKE @p2
  AND UPPER(TABLE_NAME) LIKE @p3
  AND (
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p4
        OR
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p5
    )
ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME'
  INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^ - Statement: 'SELECT TABLE_CATALOG AS TABLE_CAT, TABLE_SCHEMA AS TABLE_SCHEM, TABLE_NAME,
       CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END AS TABLE_TYPE,
       NULL AS REMARKS, NULL AS TYPE_CAT, NULL AS TYPE_SCHEM, NULL AS TYPE_NAME,
       NULL AS SELF_REFERENCING_COL_NAME, NULL AS REF_GENERATION
FROM INFORMATION_SCHEMA.TABLES AS T
WHERE UPPER(TABLE_CATALOG) LIKE @p1
  AND UPPER(TABLE_SCHEMA) LIKE @p2
  AND UPPER(TABLE_NAME) LIKE @p3
  AND (
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p4
        OR
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p5
    )
ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME'
  INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^ - Statement: 'SELECT TABLE_CATALOG AS TABLE_CAT, TABLE_SCHEMA AS TABLE_SCHEM, TABLE_NAME,
       CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END AS TABLE_TYPE,
       NULL AS REMARKS, NULL AS TYPE_CAT, NULL AS TYPE_SCHEM, NULL AS TYPE_NAME,
       NULL AS SELF_REFERENCING_COL_NAME, NULL AS REF_GENERATION
FROM INFORMATION_SCHEMA.TABLES AS T
WHERE UPPER(TABLE_CATALOG) LIKE @p1
  AND UPPER(TABLE_SCHEMA) LIKE @p2
  AND UPPER(TABLE_NAME) LIKE @p3
  AND (
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p4
        OR
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p5
    )
ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME'
    INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^
    INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^
      INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^
      INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE [at 10:24]
            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
                       ^

```
 

My gCloud version is as follows:
```
Google Cloud SDK 433.0.1
bq 2.0.93
bundled-python3-unix 3.9.16
core 2023.06.01
gcloud-crc32c 1.0.0
gsutil 5.24
```

**Comment by LonwoLonwo** [comment]
Hello @shyuen

What driver version do you use? You can check it in your connection settings -> the Test Connection Button or in Driver Settings -> Libraries

**Comment by LonwoLonwo** [comment]
You also can check this query, which driver is using to read all tables:

```sql
SELECT TABLE_CATALOG AS "TABLE_CAT", TABLE_SCHEMA AS "TABLE_SCHEM", TABLE_NAME AS "TABLE_NAME",
       CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END AS "TABLE_TYPE",
       NULL AS "REMARKS", NULL AS "TYPE_CAT", NULL AS "TYPE_SCHEM", NULL AS "TYPE_NAME",
       NULL AS "SELF_REFERENCING_COL_NAME", NULL AS "REF_GENERATION"
FROM INFORMATION_SCHEMA.TABLES AS T
```

Could you execute it in your SQL Editor?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by archanarj** [comment]
Hi,
I have this issue while using liquibase v4.25.0 

liquibase.exception.DatabaseException: com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlExceptionImpl: INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unsupported concurrency mode in query using INFORMATION_SCHEMA. - Statement: 'SELECT TABLE_CATALOG AS TABLE_CAT, TABLE_SCHEMA AS TABLE_SCHEM, TABLE_NAME,\n       CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END AS TABLE_TYPE,\n       NULL AS REMARKS, NULL AS TYPE_CAT, NULL AS TYPE_SCHEM, NULL AS TYPE_NAME,\n       NULL AS SELF_REFERENCING_COL_NAME, NULL AS REF_GENERATION\nFROM INFORMATION_SCHEMA.TABLES AS T\nWHERE UPPER(TABLE_CATALOG) LIKE @p1\n  AND UPPER(TABLE_SCHEMA) LIKE @p2\n  AND UPPER(TABLE_NAME) LIKE @p3\n  AND (\n            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p4\n        OR\n            (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p5\n    )\nORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME'\n\tat liquibase.snapshot.ResultSetCache.get(ResultSetCache.java:98)\n\tat liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData.getTables(JdbcDatabaseSnapshot.java:1135)\n\tat liquibase.snapshot.jvm.TableSnapshotGenerator.snapshotObject(TableSnapshotGenerator.java:34)\n\tat liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:65)\n\tat liquibase.snapshot

**Comment by archanarj** [comment]
> ```sql
> SELECT TABLE_CATALOG AS "TABLE_CAT", TABLE_SCHEMA AS "TABLE_SCHEM", TABLE_NAME AS "TABLE_NAME",
>        CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END AS "TABLE_TYPE",
>        NULL AS "REMARKS", NULL AS "TYPE_CAT", NULL AS "TYPE_SCHEM", NULL AS "TYPE_NAME",
>        NULL AS "SELF_REFERENCING_COL_NAME", NULL AS "REF_GENERATION"
> FROM INFORMATION_SCHEMA.TABLES AS T
> ```



> I'm getting the same TABLE_TYPE issue on both DBeaver(22.2.2.202309132212) and Liquibase (4.23.1) when attempting to do any operations against the Spanner emulator.
> 
> Weird thing is that DBeaver appears to be connected to the Spanner emulator, but I will get the `TABLE_TYPE` error dialog pop up on when I try to expand the `tables` drop down. ![image](https://private-user-images.githubusercontent.com/12534005/269998605-e05d3732-43da-4a26-8f9d-edc0ae294bce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMDY1ODAsIm5iZiI6MTcyNTMwNjI4MCwicGF0aCI6Ii8xMjUzNDAwNS8yNjk5OTg2MDUtZTA1ZDM3MzItNDNkYS00YTI2LThmOWQtZWRjMGFlMjk0YmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDE5NDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZDEzMjhlMzBkNWEyYWQ1YzVjM2YwNWNjOWVkYTZhNTdlZDRjMmFjOGVhYWNjZmRjNzYxMjc2ODY2NjYzZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TA32n_ghH5WVW3VNjuDFTkjvKHAuVuqbSqXAYlV8kjY)
> 
> ```
> SQL Error [3]: INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE [at 10:24]
>             (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
>                        ^ - Statement: 'SELECT TABLE_CATALOG AS TABLE_CAT, TABLE_SCHEMA AS TABLE_SCHEM, TABLE_NAME,
>        CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END AS TABLE_TYPE,
>        NULL AS REMARKS, NULL AS TYPE_CAT, NULL AS TYPE_SCHEM, NULL AS TYPE_NAME,
>        NULL AS SELF_REFERENCING_COL_NAME, NULL AS REF_GENERATION
> FROM INFORMATION_SCHEMA.TABLES AS T
> WHERE UPPER(TABLE_CATALOG) LIKE @p1
>   AND UPPER(TABLE_SCHEMA) LIKE @p2
>   AND UPPER(TABLE_NAME) LIKE @p3
>   AND (
>             (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p4
>         OR
>             (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p5
>     )
> ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME'
>   INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE [at 10:24]
>             (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
>                        ^ - Statement: 'SELECT TABLE_CATALOG AS TABLE_CAT, TABLE_SCHEMA AS TABLE_SCHEM, TABLE_NAME,
>        CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END AS TABLE_TYPE,
>        NULL AS REMARKS, NULL AS TYPE_CAT, NULL AS TYPE_SCHEM, NULL AS TYPE_NAME,
>        NULL AS SELF_REFERENCING_COL_NAME, NULL AS REF_GENERATION
> FROM INFORMATION_SCHEMA.TABLES AS T
> WHERE UPPER(TABLE_CATALOG) LIKE @p1
>   AND UPPER(TABLE_SCHEMA) LIKE @p2
>   AND UPPER(TABLE_NAME) LIKE @p3
>   AND (
>             (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p4
>         OR
>             (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p5
>     )
> ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME'
>   INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE [at 10:24]
>             (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
>                        ^ - Statement: 'SELECT TABLE_CATALOG AS TABLE_CAT, TABLE_SCHEMA AS TABLE_SCHEM, TABLE_NAME,
>        CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END AS TABLE_TYPE,
>        NULL AS REMARKS, NULL AS TYPE_CAT, NULL AS TYPE_SCHEM, NULL AS TYPE_NAME,
>        NULL AS SELF_REFERENCING_COL_NAME, NULL AS REF_GENERATION
> FROM INFORMATION_SCHEMA.TABLES AS T
> WHERE UPPER(TABLE_CATALOG) LIKE @p1
>   AND UPPER(TABLE_SCHEMA) LIKE @p2
>   AND UPPER(TABLE_NAME) LIKE @p3
>   AND (
>             (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p4
>         OR
>             (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE END) LIKE @p5
>     )
> ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME'
>     INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE [at 10:24]
>             (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
>                        ^
>     INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE [at 10:24]
>             (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
>                        ^
>       INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE [at 10:24]
>             (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
>                        ^
>       INVALID_ARGUMENT: Unrecognized name: TABLE_TYPE [at 10:24]
>             (CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE' ELSE TABLE_TYPE...
>                        ^
> ```
> 
> My gCloud version is as follows:
> 
> ```
> Google Cloud SDK 433.0.1
> bq 2.0.93
> bundled-python3-unix 3.9.16
> core 2023.06.01
> gcloud-crc32c 1.0.0
> gsutil 5.24
> ```

@shyuen how did you resolve this issue?
