### ISSUE TITLE
What is configuration to connect to sql server localdb -> (LocalDB)\MSSQLLocalDB

### ISSUE THREAD

**Issue by omerkocadere** [dbeaver/dbeaver#14946]
I could not achieve to connect. Could you please show how to connect?

It is working when trying to connect using sql server
![Ssms_KYiJDjFd9o](https://user-images.githubusercontent.com/9765632/146677919-53d0ebcc-481c-442c-857e-a0a46281b146.png)
?

But gives an error when trying with dbeaver
![dbeaver_JjbE6OKBzQ](https://user-images.githubusercontent.com/9765632/146677989-93a46263-5e60-44da-a116-94aa0ac93cdb.png)
![dbeaver_i4KnXSJ9Am](https://user-images.githubusercontent.com/9765632/146678002-1786f055-c6c9-4b46-96fb-bf34b547ae10.png)

**Comment by ShadelessFox** [comment]
Hello @zormaxx,

You should specify `localhost` as a hostname.
