### ISSUE TITLE
Cannot connect to Snowflake after upgrade from 21.2.5.202111141807 to 21.3.1.202112130652

### ISSUE THREAD

**Issue by daffyduck25** [dbeaver/dbeaver#14941]
#### System information: 
- Windows 10
- DBeaver version: 21.3.1.202112130652
- Additional extensions

#### Connection specification:
- Database: Snowflake
- Driver name: JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No 
- Plugin:  org.jkiss.dbeaver.model

#### Describe the problem you're observing:
Cannot connect to Snowflake database using the same connection settings that are successful for DBeaver Version 21.2.5.202111141807.  Upgraded to 21.3.1.202112130652 and cannot connect to Database with error:  Invalide JDBC URL
#### Steps to reproduce, if exist:
Upgrade to 21.3.1.202112130652

**Comment by Matvey16** [comment]
@daffyduck25 Please check how URL template is configured for snowflake driver. If it is not like on the picture, try resetting it to default

![image](https://user-images.githubusercontent.com/82543000/146765495-149587c2-677b-4644-81f1-7e0028aacb8b.png)

**Comment by daffyduck25** [comment]
Thanks that worked.  There was a "spelling" error for the URL template.  jdbc was spelled jbcd.  I assume it was that way as default when installed.
