### ISSUE TITLE
calling BigQuery stored procedures from Dbeaver

### ISSUE THREAD

**Issue by suhailmemon** [dbeaver/dbeaver#14944]
#### System information: 
- Operating system (distribution) and version: MACos catalina 10.15.7
- DBeaver version: Version 7.0.2.202004051509
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version: Google BigQuery
- Driver name: Google BigQuery driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing: when i try to call bigquery stored procedures. they fail with error: 
"SQL Error [100078] [HY000]: [Simba][BigQueryJDBCDriver](100078) Error initializing column metadata: Could not retrieve table schema information. "

sample call: CALL `myproject`.mydataset.mytestproc();

if you call this stored procedure using the bq console UI, it runs fine.

**Comment by Matvey16** [comment]
@suhailmemon BigQuery often sends a more specific error message with response code etc. Can you show the full error message?

**Comment by suhailmemon** [comment]
@Matvey16, that's about the only error i could see in the dbeaver UI: 

SQL Error [100078] [HY000]: [Simba][BigQueryJDBCDriver](100078) Error initializing column metadata: Could not retrieve table schema information.

**Comment by suhailmemon** [comment]
![image](https://user-images.githubusercontent.com/36083983/146797684-d850b7d2-39e9-451d-83e4-1250e0269be3.png)

**Comment by suhailmemon** [comment]
![image](https://user-images.githubusercontent.com/36083983/146797790-8360a7ce-ba90-482d-86c8-f24ee297f569.png)

**Comment by suhailmemon** [comment]
@Matvey16 screenshot above.

**Comment by suhailmemon** [comment]
also if i copy the exact call command and run it in the google cloud console bigquery UI, it runs successfully

**Comment by suhailmemon** [comment]
any updates here?

**Comment by Matvey16** [comment]
@suhailmemon Can you copy a full stack trace from the error view? Or attach the .log file?

**Comment by uslss** [comment]
There have been no updates on the issue for a long time. If the issue is still present - feel free to reopen it.

**Comment by suhailmemon** [comment]
This is still an outstanding issue. please reopen it. i'm not able to find any option to reopen this issue. -Suhail

**Comment by Matvey16** [comment]
@suhailmemon Can you open this procedure from database navigator?

**Comment by suhailmemon** [comment]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/36083983/157359818-1a3cd7ad-4060-4100-94d8-0b6d113ae0d5.png">

**Comment by suhailmemon** [comment]
yes as shown in the screenshot above i can see mytestproc in the database navigator but can't run it

**Comment by suhailmemon** [comment]
if you want to have a zoom call or google meeting about this, i'm happy to share my screen and demo you the issue as well

**Comment by Matvey16** [comment]
@suhailmemon Hello, sorry for the late reasponse. Could you please provide a log file https://dbeaver.com/docs/wiki/Log-files/
and also show the query manager with every query type enabled

![dbeaver_zKdqx2dekc](https://user-images.githubusercontent.com/82543000/160803842-7deba3f0-d12b-4c25-bdf2-767f16de166b.png)

**Comment by emironovDB** [comment]
Hello @suhailmemon,

Is the issue still actual for you?

**Comment by suhailmemon** [comment]
yes same issue.

**Comment by suhailmemon** [comment]
let me check on the above request and get back to you

**Comment by suhailmemon** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/8864564/dbeaver-debug.log)
<img width="759" alt="2022-06-08_13-33-44" src="https://user-images.githubusercontent.com/36083983/172702719-8a0f9144-ddd9-4c46-b4b5-4b5b92d5852b.png">

**Comment by suhailmemon** [comment]
please find attached the log file above with the query manager snapshot

**Comment by suhailmemon** [comment]
also this time when i run the store proc i don't get an error but at the same time i don't get any results back. in the gcp web ui when i run the stored proc i get results back

**Comment by Matvey16** [comment]
@suhailmemon Thank you, but I also need rhe queries from query manager itself like so

![image](https://user-images.githubusercontent.com/82543000/173780520-63fcf410-8451-42ce-acc8-4236f41ca128.png)

**Comment by suhailmemon** [comment]
how do i export the queries out of the query manager?

**Comment by suhailmemon** [comment]
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/36083983/173940045-9a80df0b-e421-4766-8e8e-47244c16fd84.png">

**Comment by suhailmemon** [comment]
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/36083983/173940175-807a610f-a735-410e-af52-8663d5563646.png">

**Comment by suhailmemon** [comment]
if it helps i have uploaded the query manager screenshot above as shown above

**Comment by Matvey16** [comment]
@suhailmemon It looks like this is a bug with jdbc driver. Please open connection settings and click `Test connection`. I need to know what driver version do you have.

**Comment by suhailmemon** [comment]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/36083983/175094748-8749f7b3-f0c4-42a5-a519-c4d487fe88aa.png">

**Comment by Matvey16** [comment]
It looks like a bug in JDBC driver when running multiple statements, similiar bug in another IDE (https://youtrack.jetbrains.com/issue/DBE-12377). We need to look into this further

**Comment by suhailmemon** [comment]
sounds good. let me know when you have an update on this issue.

**Comment by emironovDB** [comment]
Hello @suhailmemon,

Can you please provide a minimal reproducible example of such failing query?

**Comment by suhailmemon** [comment]
this is what my test proc looks like you can do some replacements and make one on your own 

`BEGIN
CREATE TEMPORARY TABLE tmp1
  AS some SELECT statement
;
CREATE TEMPORARY TABLE tmp2
  AS some SELECT statement

;
SELECT 'blablabla some hardcode value'
;
END`

**Comment by Destrolaric** [comment]
@suhailmemon Hi, sorry for waiting. I looked into your logs. Unfortunately, they don't contain the required information. Please could you try to reproduce this error and send logs once again?

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
