### ISSUE TITLE
[DB2] Exclude views from generated table DDL

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#14959]
### Discussed in https://github.com/dbeaver/dbeaver/discussions/14955

<div type='discussions-op-text'>

<sup>Originally posted by **twielens** December 20, 2021</sup>
Hello,

We've been using DBeaver for quite a while and now we finally obtained the rights to use the generate DDL function (DB2LOOK) which is working but the problem is that when I try to get the DDL for a table I also get a lot of views, even views from different schema's. Is there a way to add the -noview option to the db2look command that is used by dbeaver?

I can't put my finger on which specific views it generates the DDL, but it's a whole lot.

Kind regards,

Tim</div>

We can add DDL options for DB2 tables. Like in the Oracle table tab.

![2021-12-20 16_40_29-](https://user-images.githubusercontent.com/45152336/146776269-2be3a873-5784-4be2-82b2-062639727aec.png)

**Comment by LonwoLonwo** [comment]
Options: https://www.ibm.com/docs/en/db2/11.5?topic=commands-db2look-db2-statistics-ddl-extraction-tool

**Comment by twielens** [comment]
I think the -noview option could be standard, but maybe add other options (grants, indexes, etc.).
