### ISSUE TITLE
Additional excessive auto-complete window in table properties

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14953]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.3.2

#### Describe the problem you're observing:
Pressing autocomplete shortcut in data type window leads to another window opening on top of already existing one.

#### Steps to reproduce, if exist:
1. Open columns tab in table properties
2. Expand the data type list
3. Press <kbd>Ctrl + Space</kbd>

**Expected:** Only one window with options is shown
**Actual:** There are to windows on top of each other and the autocomplete window stays on screen even after changing app windows.

![GtUk7Rjt7i](https://user-images.githubusercontent.com/82543000/146752783-5ee71dbc-6a5b-4839-9297-1f7f99ac3807.gif)

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
We need to fix it without disabling autocomplete

**Comment by E1izabeth** [comment]
Autocomplete in drop-down lists is available by hotkey now.

**Comment by Matvey16** [comment]
Verified
