### ISSUE TITLE
export ERD to graphml loses edges with duplicated ids

### ISSUE THREAD

**Issue by andribas404** [dbeaver/dbeaver#14956]
#### System information: 
- Operating system (distribution) and version Ununtu 20.04.3 LTS
- DBeaver version 21.3.1.202112111946
- Additional extensions no

#### Connection specification:
- Database name and version soup
- Driver name PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

When exporting ERD to graphml edges from entity get the same id as the node.

#### Include any warning/errors/backtraces from the logs

```
		<edge id="edge76" source="entity76" target="entity38">
			<data key="edgegraph">
				<y:PolyLineEdge>
					<y:Path sx="0.0" sy="0.0" tx="0.0" ty="0.0">
						<y:Point x="2272" y="7018"/>
						<y:Point x="3285" y="7018"/>
					</y:Path>
					<y:LineStyle color="#000000" type="dashed" width="1.0"/>
					<y:Arrows source="white_diamond" target="circle"/>
					<y:BendStyle smoothed="false"/>
				</y:PolyLineEdge>
			</data>
		</edge>
		<edge id="edge76" source="entity76" target="entity40">
			<data key="edgegraph">
				<y:PolyLineEdge>
					<y:Path sx="0.0" sy="0.0" tx="0.0" ty="0.0"/>
					<y:LineStyle color="#000000" type="dashed" width="1.0"/>
					<y:Arrows source="white_diamond" target="circle"/>
					<y:BendStyle smoothed="false"/>
				</y:PolyLineEdge>
			</data>
		</edge>
```

**Comment by SevC10** [comment]
Same issue here

**System information:**

- _Operating system:_ Windows 10 Pro (20H2), build 19042.1415
- _DBeaver version:_   21.1.5.202108160727

**Connection specification:**

- _Database:_ MySQL Community on AWS RDS
- _Driver name:_ mysql:mysql-connector-java:RELEASE, version 8.0.17
- _Do you use tunnels or proxies:_ no

Describe the problem you're observing:
When exporting ERD to .graphml, if there are multiple relations associated to one table, the exported edges have the same id.

Below a sample of the .graphml output: the two (or more) edge/relations start from the same table (source entity 0), but they have same edge id, so only the first edge will be visualized.

    ...
    <edge id="edge0" source="entity0" target="entity7">
        <data key="edgegraph">
        
         ...
        
        </data>
    </edge>
    
    <edge id="edge0" source="entity0" target="entity12">
        <data key="edgegraph">
        
         ...
        
        </data>
    </edge>
    ...


Thank you and happy holidays!
Severino
