### ISSUE TITLE
Buttons aren't disabled while data export processing

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#14968]
#### Describe the problem you're observing:
Buttons Process, Back and Cancel aren't disabled while task is running in data export wizard

#### Steps to reproduce, if exist:
1. Take a big result set
2. Run data export
![image](https://user-images.githubusercontent.com/28875055/146889821-e8180b24-ca46-4538-8635-284476ae515f.png)
3. If to push Process button while task is processed, got an error
![image](https://user-images.githubusercontent.com/28875055/146889936-32b6b888-f412-4225-a3b1-b8460bb860ce.png)

**Comment by Matvey16** [comment]
Verified
