### ISSUE TITLE
can't download driver files

### ISSUE THREAD

**Issue by knwpsk** [dbeaver/dbeaver#14960]
On startup > reconnect, dBeaver popup says it needs to download PostgreSql driver files. 
I click Download button
It pops up error saying the Maven artifact is not found.

I click Abort and keep working as normal.
This happens every time I start DBeaver.

Sorry, I don't know much about Maven but am happy to further troubleshoot if someone guides me.

Screenshots attached.

![image](https://user-images.githubusercontent.com/30087322/146778339-68ce5e0e-1286-4f42-9c6a-e0d2301715e6.png)

![image](https://user-images.githubusercontent.com/30087322/146778388-d7046b29-999e-43e1-ba9b-0b4c860254c8.png)

![image](https://user-images.githubusercontent.com/30087322/146778679-d8e4a496-e14a-414e-8a07-fa07d48d37c0.png)

#### System information: 
- windows 10
- DBeaver version 21.0.2.202...
- Additional extensions: n/a

#### Connection specification:
- Database name and version: Postgres 9.4.1
- Driver name: posgresql native driver postgresql 9.4.1212.jre7
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Include any warning/errors/backtraces from the logs
"File missing in net.postgis:postgis-geometry"
"Error resolving artifact version"
"Maven artifact 'maven:/net.postgis:postgis-geometry:RELEASE' not found"
"Invalid input url:platform:/plugin/org.jkiss.dbeaver.core.application/icons/progress_view.png"
"Unable to resolve plug-in "org.jkiss.dbeaver.core.application"."
"Invalid input url:platform:/plugin/org.jkiss.dbeaver.core.application/icons/progress_view.png"

![image](https://user-images.githubusercontent.com/30087322/146779307-d7cc4c99-dffd-412b-b039-ba4a6f9024e9.png)

**Comment by Destrolaric** [comment]
@knwpsk Thank you for your ticket, probably related to a known bug with MavenArtifactEditor. You can temporarily add the preferred version inside the artifact editor. Here is the guide https://github.com/dbeaver/dbeaver/wiki/How-to-add-additional-artifacts-to-the-driver

**Comment by knwpsk** [comment]
@Destrolaric thanks for your quick reply. 
Can you possibly guide me just a bit farther? How can I identify what version of what artifact dbv thinks it needs? 
Or can I just happily ignore this til the bug you mentioned is fixed? I'm not having any noticeable issues in my work, just seeing this dbv popup.

**Comment by Destrolaric** [comment]
@knwpsk Bug is related to using RELEASE without the preferred version, so it will probably start working if you write any existing version that is sufficient.

**Comment by knwpsk** [comment]
I'm pretty confused.

When I edit the connection > libraries, I see this:

![image](https://user-images.githubusercontent.com/30087322/146961469-3ecae642-0943-4d25-8df0-c7ef95105c64.png)

When I try to download, I get the error about Maven geometry file "release" not found.

When I double-click that file, I see:

![image](https://user-images.githubusercontent.com/30087322/146961649-90017cae-0e39-42b6-a2ac-3d2eddacfdb1.png)
and I click OK.

Now the Libraries dialog has resolved the file to a particular version:

![image](https://user-images.githubusercontent.com/30087322/146961776-ed7efd69-641c-4634-9e09-2fd0a48484cd.png)

But when I click OK, I get a different error:

![image](https://user-images.githubusercontent.com/30087322/146961872-183f33a6-8179-4426-80fb-84dab91bb8de.png)

I just don't know where to go from here, and I could spend all day trying to research this stuff without further guidance.

**Comment by knwpsk** [comment]
I updated dbv to latest release.
This fixed the problem.

**Comment by Destrolaric** [comment]
@knwpsk  I am glad what update fixed the issue. Thank you for your research. I am closing the ticket.
