### ISSUE TITLE
schtasks.exe not found in schedule task

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#14965]
#### System information: 
OS : Windows 10 Pro 20H2

USE : DBeaver Enterprise 21.3.0

#### Connection specification:
Postgresql -> MSSQL 
Database Tasks

#### Describe the problem you're observing:
1. Database Tasks success

2. schedule task save

3. "has been scheduled in local windows task scheduler" notifications

3. open scheduler setting

4. DBeaver folder open

5. nothing is registered

#### Include any warning/errors/backtraces from the logs

- %APPDATA%\DBeaverData\workspace6\.metadata.\dbeaver-debug.log

2021-12-21 10:29:04.526 - Run Windows scheduler with parameters [/Create /SC DAILY /MO 1 /SD 21/12/2021 /ST 10:29 /TN DBeaver\GW -> ERP /TR \"C:\Program Files\DBeaverEE\dbeaver.exe\" -runTask \"@General:GW -> ERP\" -nosplash]
2021-12-21 10:29:04.542 - schtasks.exe: 지정된 경로를 찾을 수 없습니다.
2021-12-21 10:29:04.573 - Run Windows scheduler with parameters [/Query /FO CSV]

**Comment by ghost** [comment]
-vmargs
-Ddbeaver.scheduler.windows.legacy=true

**Comment by ShadelessFox** [comment]
Hello @al8bright,

I believe your task contains Korean characters in its name. Fortunately, a modern scheduler handles them well.

Is there any particular reason to use the legacy scheduler? I would suggest you disable this option and try again.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/4089920/147726742-185010ed-57da-4980-ab2e-5f7b40af9b95.png)

**Comment by ghost** [comment]
"-Ddbeaver.scheduler.windows.legacy=true"

Deleting from the line throws an error

**Comment by ShadelessFox** [comment]
Can you please post a full log?

It can be found according to this wiki page: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by ghost** [comment]
[sch.log](https://github.com/dbeaver/dbeaver/files/7804718/sch.log)
log

**Comment by ghost** [comment]
[sch_dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/7804720/sch_dbeaver-debug.log)
debug

**Comment by ShadelessFox** [comment]
Thank you.

Could you please also provide Windows version information? I'm interested in particular numbers.

In can be found in <kbd>Settings</kbd> &rArr; <kbd>System</kbd> &rArr; <kbd>About</kbd>.

**Comment by ghost** [comment]
![화면 캡처 2022-01-10 164628](https://user-images.githubusercontent.com/4089920/148732598-1de10177-ebb6-410c-a814-35a70c7f3988.png)

**Comment by ShadelessFox** [comment]
That would be enough for now, thanks again.

We are going to review the issue in near future. As of now, we are unable to reproduce it.

**Comment by ShadelessFox** [comment]
Hello @al8bright,

Sorry for the late reply.

After further investigation, it seems like your Windows installation is incomplete and lacks the scheduler entirely. In such a case, neither the legacy scheduler support nor the new one will work. We can't do anything about that, unfortunately.

I suggest you reinstall Windows if you're still having troubles with the scheduler in DBeaver.
