### ISSUE TITLE
Fallback version is not working correctly in Maven Artifact Editor

### ISSUE THREAD

**Issue by Destrolaric** [dbeaver/dbeaver#14972]
The fallback version is not working correctly right now. When we create an artifact with the empty version and filled fallback version, it will fail to download

**Comment by Destrolaric** [comment]
The fallback version did not work properly when the artifact was created/edited from manual edit mode. It was related to the preferred version being an empty string which caused it to think it has the preferred version and to try to download it.

**Comment by uslss** [comment]
verified
