### ISSUE TITLE
Can't authenticate to Azure SQL Databases - STS Throttling Issue

### ISSUE THREAD

**Issue by andydkelly-ig** [dbeaver/dbeaver#14976]
#### System information: 
- Mac OSX Big Sur 11.6
- 21.3.1.202112130652

#### Connection specification:
- Azure SQL Server
- MSQL JDBC driver

#### Describe the problem you're observing:

Can't authenticate to Azure SQL Servers using AD with Password. Receive the error `Request was throttled according to instructions from STS`. Tried this using every combination available of JDBC driver and MS Authentication Library and <=8 gives missing ADAL error, and >9 gives the issue

#### Steps to reproduce, if exist:

Try to connect to Azure SQL Server DB using AD Authentication with Password.

#### Include any warning/errors/backtraces from the logs

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Framework arguments:  -keyring /Users/andy/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/andy/.eclipse_keyring

org.jkiss.dbeaver.model
Error
Tue Dec 21 14:53:59 GMT 2021
Request was throttled according to instructions from STS. Retry in 116665 ms.

**Comment by andydkelly-ig** [comment]
This started working again so presuming it was Azure issue

**Comment by laddana-github** [comment]
I get a similar error with Dbeaver 7.0.3 and on Windows. Cannot get Dbeaver to connect to Azure Synapse Analytics over JDBC.
