### ISSUE TITLE
Data editor doesn't enclose pre-existing filters in parentheses when adding new conditions, messing precedence

### ISSUE THREAD

**Issue by ivanlonel** [dbeaver/dbeaver#14980]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro 21H1
- DBeaver version: 21.3.1
- Additional extensions: Office support, git support, SSHJ, Debug and SVG

#### Connection specification:
- Database name and version: Postgresql 14.1
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
If I use the filter bar of the data editor to manually enter a condition that contains an OR, then click on the filter icon of a column to filter by selected values of that column, the resulting filter fails to enclose the initial OR condition in parentheses, which might return an unexpected result set.

For example, if my initial filter is `a > 50 OR b > 50`, I click on the filter icon of column `c` and select only value 10, the resulting predicate in the filter bar becomes something like `c IN (10) AND a > 50 OR b > 50`, which evaluates the AND before the OR. The expected filter would be `c IN (10) AND (a > 50 OR b > 50)`.

#### Steps to reproduce, if exist:

1. Create testing set:
```pgsql
CREATE TABLE test (
	a integer,
	b integer,
	c integer
);

INSERT INTO test
	SELECT
		random() * 100,
		random() * 100,
		random() * 100
	FROM generate_series(1, 1000) as n;
```

2. With table `test` open in data editor, manually enter `a > 50 OR b > 50` into the filter bar and press Enter

3. Now click on the funnel icon of column `c` and select any value(s) to filter by.

4. Check the filter bar to confirm the resulting filter is now wrong (or rather different than one would expect). 

#### Include any warning/errors/backtraces from the logs

No erros raised, just a logical bug.

**Comment by Matvey16** [comment]
@ivanlonel Thank you for the report. We will fix it.

**Comment by Matvey16** [comment]
Verified
