### ISSUE TITLE
Connection settings can't be saved after connection test

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14991]
#### System information: 
- Operating system (distribution) and version
- DBeaver version 21.3.2

#### Steps to reproduce, if exist:
1. Right-click a connection and click `Edit connection`
2. Click `Test connection`

**Expected:** OK and Cancel buttons can be clicked
**Actual:** Buttons are disabled

![DXL4UZGELc](https://user-images.githubusercontent.com/82543000/147110625-19bb711c-6861-454e-b0cb-1996f9809744.gif)

**Comment by uslss** [comment]
verified
