### ISSUE TITLE
Query results showing value of wrong columns having similar names

### ISSUE THREAD

**Issue by okerstent** [dbeaver/dbeaver#14990]
#### System information: 
- Ubuntu 20.04.2 LTS
- DBeaver 21.3.1.202112130652
- Additional extensions: -

#### Connection specification:
- Oracle Database 18c Express Edition Release 18.0.0.0.0
- Driver name ojdbc8 release 12.2.0.1
- Do you use tunnels or proxies (SSH, SOCKS, etc): no, local db in docker

#### Describe the problem you're observing:
Having two columns with a longer identical prefix (RESIDUAL_VALUE_PERCENTAGE and RESIDUAL_VALUE_PERCENTAGE_MANUAL), a query result shows the same value for both columns, though they contain different values (verified by query in SQLPlus). The value shown is taken from the column with the shorter name.

**Comment by ShadelessFox** [comment]
Hello @okerstent,

Can you please provide a screenshot showing your issue?

**Comment by okerstent** [comment]
Issue resolved, sorry for false alarm ...
