### ISSUE TITLE
EPSG button in spatial view is disabled in some tables

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14999]
#### System information: 
- Win10, DBeaver CE 21.3.2

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/43252954/147218867-daada9c0-43dd-4795-a8f3-bde280364b25.png)
![image](https://user-images.githubusercontent.com/43252954/147218901-af850978-9aaa-45b9-a463-84bb07a6cc61.png)
In some tables EPSG button is disabled. At first glance, I don't see any notable differences in these tables
#### Steps to reproduce, if exist:
It can be reproduced in all data sources where you can find GIS data. For example, you can test this in Postgres 11.6 GIS on these tables:
![image](https://user-images.githubusercontent.com/43252954/147219426-8f17a68b-62fc-48c7-adb1-7bd2c06b384a.png)
![image](https://user-images.githubusercontent.com/43252954/147219473-b6153ab4-7409-4055-b26a-928e8ff3ccb3.png)

**Comment by uslss** [comment]
verified
