### ISSUE TITLE
DB2 10.5 Explain plan

### ISSUE THREAD

**Issue by apdma** [dbeaver/dbeaver#15002]
#### System information: 
- Windows 10
- DBeaver version 21.3.1.202112111946

#### Connection specification:
- DB2 10.5
- com.ibm.db2.jcc.DB2Driver
- VPN

#### Describe the problem you're observing:
Explain plan not showing in window

#### Steps to reproduce, if exist:
Try execute explain plan on any query, for example
SELECT sysdate FROM DUMMY_TABLE;

#### Include any warning/errors/backtraces from the logs
I have two database, one of this re-created a couple times and maybe we lost rights. On second explain is work.
But other had, whan i try get explain as instance owner, i get same result.
I can execute plan from a console or procedure, but can't get it in GUI
![image](https://user-images.githubusercontent.com/91953047/147255978-96792c69-5ac2-45df-8d55-d4ef5714263a.png)
![image](https://user-images.githubusercontent.com/91953047/147255685-3453ca3c-a67d-4a8b-9c4e-9acce0433167.png)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
UPDATE:
I found in dbeaver-debug.log
https://pastebin.com/U3wZ0A4k

**Comment by apdma** [comment]
So, I checked EXPLAIN_* tables and find out, what they all is empty.
On second DB the EXPLAIN_* tables has some rows. 
So for some reason I can't trigger insert in explain tables and dbeaver read nulls

**Comment by apdma** [comment]
Ok, so not so simple how i think.
1) When I start explain with "Ctrl+Shift+E" it not fill any EXPLAIN_* tables
2) When I start explain with "explain ALL FOR SELECT 1 FROM dual;" it create rows
3) If I for the giggles start explain "Ctrl+Shift+E" on query "explain ALL FOR SELECT 1 FROM dual;" I get the error
```
SQL Error [42601]: An unexpected token "FOR explain ALL" was found following "SET QUERYNO = 164054".  Expected tokens may include:  "<space>".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.25.25
  An unexpected token "FOR explain ALL" was found following "SET QUERYNO = 164054".  Expected tokens may include:  "<space>".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.25.25
  An unexpected token "FOR explain ALL" was found following "SET QUERYNO = 164054".  Expected tokens may include:  "<space>".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.25.25
    An error occurred during implicit system action type "2". Information returned for the error includes SQLCODE "-104", SQLSTATE "42601" and message tokens "FOR explain ALL|SET QUERYNO = 164054|<space>".. SQLCODE=-727, SQLSTATE=56098, DRIVER=4.25.25
    An error occurred during implicit system action type "2". Information returned for the error includes SQLCODE "-104", SQLSTATE "42601" and message tokens "FOR explain ALL|SET QUERYNO = 164054|<space>".. SQLCODE=-727, SQLSTATE=56098, DRIVER=4.25.25
```
So I don't fully undestand what dbeaver do if the "Ctrl+Shift+E" was started

**Comment by Matvey16** [comment]
@apdma 
It looks like expected behavior because pressing "Ctrl+Shift+E" leads to DBeaver sending this query `EXPLAIN PLAN SET QUERYNO = 164088 FOR explain ALL FOR SELECT 1 FROM dual;` and it is invalid.
So basically "Ctrl+Shift+E" wraps you query into explain and is intended to be used on queries that can be explained
