### ISSUE TITLE
dbeaver shows null-value as result whereas mariadb itself returns a real value 

### ISSUE THREAD

**Issue by 4ndr3453rk3n5** [dbeaver/dbeaver#15007]
**system information**
- MacOS 11.6
- dbeaver Version 21.1.4.202108020335

**connection**
- mariadb 10.5.8

**problem description:**
dbeaver shows a result which is different from the real result of the sql - query. 
The following query: select STR_TO_DATE('', '%d.%m.%Y'); executed on mariadb results a real date:  0000-00-00  whereas dbeaver shows [NULL] as result, which is obviously wrong. 

![image](https://user-images.githubusercontent.com/81389835/147278719-b7714725-ea13-419f-babc-27e06dbb8f92.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
Hello @4ndr3453rk3n5,

The driver itself treats an empty date as null. It is the correct behavior.
