### ISSUE TITLE
Incorrect column name in grouping panel

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#15009]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.3.2

#### Connection specification:
- Database name and version Derby 10.15.1.3
- Driver name Apache Derby Network Client JDBC Driver 10.15.2.0
- SSH

#### Describe the problem you're observing:
The `Count(*)` column in grouping panel have the wrong name

#### Steps to reproduce, if exist:
1. Open a table in data editor and open grouping panel
2. Drag some columns into grouping panel

**Expected:** Count(*) column have the correct name
**Actual:** The column will have its name as a number of other columns + 1

**Comment by LonwoLonwo** [comment]
Can't reproduce against DBeaver 22.1.5

![2022-08-31 11_31_50-Event](https://user-images.githubusercontent.com/45152336/187635116-28be12db-16a7-4f4d-a403-e339499e7441.png)

Was:

![2022-08-31 11_36_59-DBeaver Lite 21 3 0 - _toursdb_ Script-39](https://user-images.githubusercontent.com/45152336/187635143-344379f7-cfd3-4a6f-b613-c1058bd3d550.png)
