### ISSUE TITLE
Batch indent or  Batch align

### ISSUE THREAD

**Issue by moshimowang326** [dbeaver/dbeaver#15010]
I hope the dbeaver will add Batch indentation or  Batch alignment for sql editor . I have used the datagrip application has these features!  

Having  these  features  would  make   dbeaver  even  more  useful .

**Comment by ShadelessFox** [comment]
Hello @moshimowang326,

I'm not sure what you are talking about.

Would you please provide more information (including screenshots) of the feature you want?

**Comment by moshimowang326** [comment]
sorry! It's bothering you. the features like this:
![image](https://user-images.githubusercontent.com/54019970/147337575-c893fb0b-4536-4814-bcc8-c6c3546576dd.png)
![image](https://user-images.githubusercontent.com/54019970/147337657-ad25de40-fcc0-42a6-b7c6-61b8cad7dd73.png)

**Comment by moshimowang326** [comment]
sorry! It's bothering you. You can check the attached video!

**Comment by ShadelessFox** [comment]
So you're talking about multi cursor feature.

We do have that already, you can enable it using <kbd>Alt+Shift+A</kbd>, or by using <kbd>Edit</kbd> &rArr; <kbd>Enable Block Selection</kbd>.

**Comment by moshimowang326** [comment]
YSE!
I find this feature thank you very much!
