### ISSUE TITLE
Table view flashes, impossible to work 21.3.1

### ISSUE THREAD

**Issue by andriusign** [dbeaver/dbeaver#15018]
Open Dbeaver 21.3. 
Table view flashes on each mouse move event, impossible to work at all. Glitches start randomly, sometimes on maximize window, sometimes just when program opens.

![Untitled](https://user-images.githubusercontent.com/14263959/147383920-fa70d0c2-25db-4bcf-9185-60639131c91b.png)

OS: Linux

**Comment by ShadelessFox** [comment]
Hello @andriusign,

Thanks for the report.

Duplicate of #14751.
