### ISSUE TITLE
pg sql generation error

### ISSUE THREAD

**Issue by zane-rl** [dbeaver/dbeaver#15037]
#### System information: 
- OS: win10
- DBeaver version：21.3.2.202112261636

#### Describe the problem you're observing:
when a table column type is jsonb, pg generate insert sql error
#### Steps to reproduce, if exist:
open table, and then generate insert sql, the jsonb column content include redundant quotation mark
![jsonColumn_insert_20211227104051](https://user-images.githubusercontent.com/10266095/147430168-4647cc60-dade-40c9-94f4-eb47fe8ccddc.png)

**Comment by LonwoLonwo** [comment]
Hello @rboleynl 

Thanks for the bug report.

As I can see, this issue is only for "Generated insert/update" queries, not in the actual insert/update script.

![2021-12-27 15_10_14-Event](https://user-images.githubusercontent.com/45152336/147470734-d6291efc-3438-4660-84fb-d4c855b24593.png)

**Comment by zane-rl** [comment]
@LonwoLonwo you are right，just only for "Generated insert/update" queries，plsql execute this generate insert sql will result in sql query not match.
