### ISSUE TITLE
Can not open CLOB in external editor

### ISSUE THREAD

**Issue by Haikson** [dbeaver/dbeaver#15038]
#### System information: 
- Operating system (distribution) and version: macOS Monterey 12.1
- DBeaver version: 21.3.2
- Additional extensions: -

#### Connection specification:

- Database name and version: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
- Driver name: Oracle JDBC driver 12.2.0.1.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no tunnels

#### Describe the problem you're observing:

Exception at "Open in external editor" in MacOs.

Project imported from DBeaver for Windows

#### Steps to reproduce, if exist:

- execute query
- click "Open in external editor"
- Get an exception

#### Include any warning/errors/backtraces from the logs

File exception while opening

Failed to open, edit or print /var/folders/9l/wtsf9g5s6md2l1n0bh3xpdkw0000gq/T/dbtmp1653569136757077542.octet-stream. Error code: -10814

**Comment by Haikson** [comment]
The problem is solved by assigning a file assotiation

**Comment by quocvan1311** [comment]
Hi @Haikson , I still got this issue on DBeaver 22.0.4 when try to open the json field in external editor.
It throws this error
```
File exception while opening

Reason:
Failed to open, edit or print /var/folders/3f/xl_n65zd0ds32yjk7v9532vc0000gn/T/dbtmp10169212175961119803.octet-stream. Error code: -10814
```
I also assigned the editor for *.octet-stream type in File Association setting
