### ISSUE TITLE
Notes are duplicated after refresh

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#15030]
#### System information: 
- Win10, DBeaver CE 21.3.2

#### Steps to reproduce, if exist:
Create a note in ERD, refresh it and try to drag-n-drop the note. Or create note, drag-n-drop and refresh -> the duplicate appears where the note was moved from

#### Include any warning/errors/backtraces from the logs

https://user-images.githubusercontent.com/43252954/147412642-a7084177-c3ad-432c-8876-42c920e80481.mp4

**Comment by Matvey16** [comment]
Only happens when `keep layout` is anabled
