### ISSUE TITLE
Disable `Append to the file` option for binary file formats

### ISSUE THREAD

**Issue by Destrolaric** [dbeaver/dbeaver#15042]
XLSX files are binary. Appending to them will cause files to be unreadable. We need to turn off this functionality when the XLSX file is selected.

**Comment by uslss** [comment]
The option should be unchecked in case it is greyed out
![image](https://user-images.githubusercontent.com/31996417/147730767-1a7e33cb-4087-4973-8b86-65691ca66e42.png)

**Comment by uslss** [comment]
verified
