### ISSUE TITLE
SHA 256 mismatch when installing dbeaver using Homebrew

### ISSUE THREAD

**Issue by mayank4all** [dbeaver/dbeaver#15054]
System information:
Operating system (distribution) and version: macOS Big Sur 11.2.3
DBeaver version: 21.3.2
Describe the problem you're observing:
Could not install dbeaver using brew, because of sha256 mismatch.

Steps to reproduce, if exist:
brew install --cask dbeaver-community

Include any warning/errors/backtraces from the logs
Running `brew update --preinstall`...
==> Downloading https://dbeaver.io/files/21.3.2/dbeaver-ce-21.3.2-macos-x86_64.dmg
Already downloaded: /Users/ma/Library/Caches/Homebrew/downloads/0dd23c49ae5dcdd4661b576ce3ccd4d239957ebbbd85d419ed737cefb3136286--dbeaver-ce-21.3.2-macos-x86_64.dmg
Error: SHA256 mismatch
Expected: eb42fd96c8d013a9962464e481758868b03ad906d7a07d5d32c74f9f828804bb
  Actual: 8278253d121e1c74645ed302263dd340f61fadd075c9d676732c248b47011f26
    File: /Users/ma/Library/Caches/Homebrew/downloads/0dd23c49ae5dcdd4661b576ce3ccd4d239957ebbbd85d419ed737cefb3136286--dbeaver-ce-21.3.2-macos-x86_64.dmg
To retry an incomplete download, remove the file above.

Tried updating brew using the following commands:
- brew upgrade
- brew update-reset   
- brew cleanup && brew update
- brew edit 8278253d121e1c74645ed302263dd340f61fadd075c9d676732c248b47011f26

**Comment by ayharano** [comment]
This commit should have solved that issue: https://github.com/Homebrew/homebrew-cask/commit/e38ba101a6883a8617a3ed71e694842fc583e815

**Comment by mayank4all** [comment]
Yes, this issue is resolved now. Thanks @ayharano 
Closing the issue.
