### ISSUE TITLE
Don't change case for quoted identifiers

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#15059]
There is an option to change case of column and table names in SQL export wizard (Identifier case). When column or table name is quoted it transforms too. We don't need to change case for quoted identifiers.

**Comment by uslss** [comment]
verified

**Comment by Matvey16** [comment]
Table name changes case to upper in Advanced copy

![dbeaver_or6EwuwOs9](https://user-images.githubusercontent.com/82543000/149884268-97cc6dff-55fa-48a0-8cc1-4bde3bd98220.gif)

**Comment by uslss** [comment]
verified
