### ISSUE TITLE
[XLSX] Allow to append new data to existing file in Data-transfer

### ISSUE THREAD

**Issue by Destrolaric** [dbeaver/dbeaver#15067]
Currently, we cannot append any information towards the XLSX format. If something is appended file becomes unreadable.

**Describe the solution you'd like**
If the XLSX format is selected, we need to append the required information correctly.

**Comment by ShadelessFox** [comment]
Duplicates #15042

**Comment by ShadelessFox** [comment]
Implemented for XLSX, CSV, and TXT exporters.

Regression: it's now impossible to enable append for file formats that are not listed above.

**Comment by Matvey16** [comment]
Verified
