### ISSUE TITLE
Search a number as a whole word works like "contains"

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#15064]
#### System information: 
- win10, DBeaver CE 21.3.2 

#### Describe the problem you're observing:
If you search word in data editor with checked "Whole word" option, it works properly, but if you try to find, for example, number "5" all cells that contain it will be highlighted 
![image](https://user-images.githubusercontent.com/43252954/147542389-f405193b-7385-437b-a11a-4c64e644ad31.png)

**Comment by Matvey16** [comment]
Verified
