### ISSUE TITLE
Absent Refresh button in Custom Diagrams

### ISSUE THREAD

**Issue by zuzzz** [dbeaver/dbeaver#15062]
Why did remove the Update and Save buttons on the toolbar, in the custom diagram window?
Hotkeys (ctrl+s, f5) still work, but this is not always convenient.

This is somehow related to problem issue [/dbeaver-ee/issues/587](https://github.com/dbeaver/dbeaver-ee/issues/587). I have no access to this issue.

#### System information: 
- Operating system: Windows 10
- DBeaver version: 21.3.2

**Comment by Matvey16** [comment]
@zuzzz Thank you for the report, it is indeed a bug, that occured during new feature implementation, we will fwork on that.

**Comment by E1izabeth** [comment]
Please, track this issue here https://github.com/dbeaver/dbeaver/issues/13461. I'll close it as a duplicate.
