### ISSUE TITLE
[clickhouse] Use SQL to limit fetch size is not working

### ISSUE THREAD

**Issue by DoS174** [dbeaver/dbeaver#15069]
I select "Use SQL to limit fetch size" for DB in clickhouse and the query does not change. In the end, LIMIT does not appear.
Checked in postgresql. Everything works there

**Comment by Matvey16** [comment]
@DoS174 Thank you for the report, we will work on that.

**Comment by uslss** [comment]
verified

**Comment by DoS174** [comment]
The "Use SQL to limit fetch size" item started adding a LIMIT 100 row to the query, but I still get an error

`_SQL Error [1002]: ClickHouse exception, code: 1002, host: ***, port: ***; Code: 164. DB::Exception: Cannot modify 'max_result_rows' setting in readonly mode. (READONLY) (version 21.10.5.3 (official build))_
`

If I turn off the LIMIT in the settings, and add the LIMIT to the request manually, then everything works

dbeaver version 21.3.4

**Comment by uslss** [comment]
verified
