### ISSUE TITLE
Tools/Restore database Must confirm before [start]

### ISSUE THREAD

**Issue by trydofor** [dbeaver/dbeaver#15068]
#### System information: 
- Operating system (distribution) and version: Mac 
- DBeaver version: 21 CE

#### Connection specification:
- Database name and version : Mysql 5.7
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

i have a friend, and 
he click [start] of Tools/Restore,
he lost his job, 
he restore wrong data.

he just dump database as usual,
but he get wrong menu, get wrong [start].

**he want** 
* any dangerous Action Must have confirmed.
* and dangerous input Must have no-previous value.

it's a sad story.

#### Steps to reproduce, if exist:

right click any database, click Tools/Restore, and click start

#### Include any warning/errors/backtraces from the logs

No Warning

**Comment by LonwoLonwo** [comment]
Hello @trydofor 

Sad story.

Maybe we must add more confirmation dialogs for these dangerous operations like Restore or Truncate.
Maybe we must add some new double confirmation for DELETE operation and others.

**Comment by trydofor** [comment]
thanks 👍
