### ISSUE TITLE
Data Transfer wiki update

### ISSUE THREAD

**Issue by Destrolaric** [dbeaver/dbeaver#15066]
New functionality was implemented in data transfer. We need to update the wiki with information about new features. Also, the wiki lacks basic features description.
- Add information about append to end feature
- Information about settings

**Comment by LonwoLonwo** [comment]
Implemented:
https://github.com/dbeaver/dbeaver/wiki/Data-transfer
https://github.com/dbeaver/dbeaver/wiki/Data-migration
