### ISSUE TITLE
Execute same SQL code on other DB or other connections

### ISSUE THREAD

**Issue by paoloholzl** [dbeaver/dbeaver#15074]
One of the best things of dBeaver is if you have a sql command to execute one more then one DB, you can open more than one SQL editor for each connection and than copy and correct istruction and execute again.

For example you have two or connections using one or more DB with same structure.
I have connection to production server and an other connection to test server.
ALTER TABLE (test connection).production.table_name  DROP COLUMN column_name;
ALTER TABLE (test connection).developers.table_name  DROP COLUMN column_name;
ALTER TABLE (production connection).production.table_name  DROP COLUMN column_name;
ALTER TABLE (production connection).developers.table_name  DROP COLUMN column_name;

My be more simply write the first command ALTER TABLE (test connection).production.table_name  DROP COLUMN column_name;
And than press 'execute in other DB/connection' and than select into a combo box '(test connection).developers'.
So change automatically SQL command, referred connection, and execute new command.

**Comment by Matvey16** [comment]
@paoloholzl There is an option in Enterprise edition to create composite tasks. They allow you to execute the same script on many different connections. Are you proposing something more specific?

**Comment by uslss** [comment]
There has been no update on the issue for a long time.
If it is still actual for you against the recent version, please reopen it.
