### ISSUE TITLE
Schema ER lines

### ISSUE THREAD

**Issue by paoloholzl** [dbeaver/dbeaver#15076]
Schema ER is better if you can request to start line left or right of fields connected in foreign keys (and not only to table box).
An other semplification my be permit to transform (for example using double click), relation line orientation to vertical or horizontal.

**Comment by paoloholzl** [comment]
![Example](https://user-images.githubusercontent.com/96785200/147647802-ce697b87-423f-4656-a60c-726c5aa95b21.png)

**Comment by Skydiveroid** [comment]
Thanks for the idea!

**Comment by dbeaver-pm** [comment]
Duplicate of #15755
