### ISSUE TITLE
[Data Editor] Update table is executed N times if you press the Save button N times in a row

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#15071]
#### System information: 
- Operating system (distribution) and version Win 11
- DBeaver version 21.3.2 devel

#### Connection specification:
- Database name and version Hive 2.3 (although I believe it's not important)

#### Steps to reproduce, if exist:
1. Create a table in Hive with varchar of a float column (I think that DBMS, data types, and the number of columns are not important, though)
2. In the data editor, add a new row.
3. Press the Save button once.
4. While the update table is still in progress, press the Save button again.
5. After the update is finished, press F5 and see that the row was inserted twice.

![hive](https://user-images.githubusercontent.com/26031301/147568286-b0440c87-cf84-428b-8be4-af2cba5ffe30.gif)

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by uslss** [comment]
verfied
