### ISSUE TITLE
task to dump database for all objects

### ISSUE THREAD

**Issue by mshakurov** [dbeaver/dbeaver#15086]
How do I set up a task that will back up all schemas and all objects? Why do I have to choose schemes every time? Maybe I don’t see any special settings? Or should I manually write a script? Is there a setting through the DBeaver interface?
I mean, if a new scheme is added, then it will not be reserved by the same task, and I need to configure the task.

**Comment by Skydiveroid** [comment]
@mshakurov 

Thanks for the idea.

**Comment by LonwoLonwo** [comment]
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/17494
