### ISSUE TITLE
How the sqlite driver manually

### ISSUE THREAD

**Issue by Trid-collab** [dbeaver/dbeaver#15084]
I am new to dbeaver. I have installed in my WIN10 machine, but the moment I am trying to connect to my SQLITE db its trying to download the SQLITE connection driver which is failing because of some SSL certificate error - maybe due to the security packages on my laptop. 

Is it possible to download the said driver manually and install it. If so how - it nice if someone could direct me to the right path.

Error message:

`Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`

**Comment by flambchap** [comment]
Hi. Please refer to this article. Do the actions described there help? https://github.com/dbeaver/dbeaver/wiki/Importing-CA-Certificates-into-DBeaver

**Comment by Trid-collab** [comment]
Hi, Thank for the suggestion. I have tried the same as per the inputs, but it doesn't seem to work

**Comment by uslss** [comment]
@Trid-collab is it still actual for you against the recent version?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. if it is still actual - feel free to reopen it

**Comment by connectluole** [comment]
![sqlite_driver_setup](https://github.com/dbeaver/dbeaver/assets/16472308/ff3da847-14f2-429f-adc1-e4dc89c22aab)
