### ISSUE TITLE
Bad results due to DBeaver trying to be clever with my queries

### ISSUE THREAD

**Issue by Scoppio** [dbeaver/dbeaver#15099]
#### System information: 
- MacOS BigSur 11.6
- DBeaver version 21.3.1

#### Connection specification:
- Postgresql 12.8 and 9.5.23
- SSH Tunnel

#### Describe the problem you're observing:

Whenver I make a query that selects data with a date column which has a value that is bigger than `now() - interval '4 hours'` (or any amount of hours to be clear), aka.: I want to select all rows that were created in the last 4 hours, the result often contains lines with fields that are clearly older than 4 hours, actually it contains all rows that were created today!
If I run the same query in psql, this does not happen.
DBeaver seens to be arbitrarily changing values or updating the value of `now() - interval '4 hours'` to a `date` instead of a `datetime`. 

#### Steps to reproduce, if exist:

```
select * from my_table mt where mt.created_at between now() - interval '4 hours' and now();
```

I managed to make it "work" on DBeaver my including the following:

```
select * from my_table mt where  created_at between (now() AT TIME ZONE 'UTC') - interval '4 hours' and now();
```

**Comment by Matvey16** [comment]
@Scoppio I was not able to reproduce it. Can you provide a DDL of this table with a few rows of sample data to test it on our database? Also would be useful to see the query that is being sent (can be seen in query manager)

**Comment by Scoppio** [comment]
Have you tried running on a local postgres or a remote one at a different timezone? Because when running with a postgres on localhost everything works perfectly, but as soon as I point to a remote database at AWS the queries become unreliable.

I cannot provide you with sample data or artificial data, sorry. But I can say that using remote databases in different timezones break the query.

**Comment by Matvey16** [comment]
@Scoppio It looks like an expected behavior to me. The function `now()` is executed on the server therefore it uses the server timezone. What type of timestamp column do you have? timestamp or timestamptz?

**Comment by Scoppio** [comment]
No... not by far, what I said originally was:
`select * from my_table mt where mt.created_at between now() - interval '4 hours' and now();` (retconning, I originally used between but got stuck in my head that I was using greater than)

considering `now()` = `2022-01-14 14:37:00.000Z`

## Expected
Expected to return only objects created between `2022-01-14 14:37:00.000Z` and the `2022-01-14 10:37:00.000Z`

## Result
|ID|created_at|
|--|----------------|
|1001|2022-01-14 00:00:15.000Z|
|1002|2022-01-14 03:28:18.000Z|
|1003|2022-01-14 7:15:00.000Z|
|1004|2022-01-14 9:14:00.000Z|
|1005|2022-01-14 11:49:55.000Z|
|1006|2022-01-14 11:02:12.000Z|
|1007|2022-01-14 13:18:55.000Z|

## Double checking
than to make sure I was receiving "wrong" time windows I run

```SQL
select 
    (max(created_at) - min(created_at)) as timespan 
from 
    my_table mt 
where
   mt.created_at between now() - interval '4 hours' and now();
```
### Result
Considering "now" = 14:30:00
|timespan|
|--|
|14 hours and 30 minutes|

### Expected 
|timespan|
|--|
|4 hours*|

Maximum value expected is 4 hours. but most likely to show something lower than that.

## Discussion

The way I received the result was as if I had run `select * from my_table mt where mt.created_at > '2022-01-14'`;

The column `created_at` is `timestamp`

If the problem were "it was returning in a different timezone than I expected" this is something I would have caught easily because I am very used to having timezone errors, but the behavior we saw was as if I had never sent any time information in my where statement, only the date, no time.

**Comment by Scoppio** [comment]
I am closing this issue because I cannot replicate this error anymore since the last update in DBeaver.
