### ISSUE TITLE
Change UI for local clients settings

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#15092]
We need to change the UI that is used when a user seys buck up or restore tasks. Currently the UI doesn't provide enough information for user to understend what is needed to start a task, this is especially confusing on Linux and Mac where MySQL and PostreSQL binaries are not downloaded automatically and nothing in the UI points to the fact that user needs to install them manually. The main confusing points of the UI are:
1. User doesn't understand what is a native/local client
2. If no client is installed on a machine, user doesn't get any tips that he needs to do that manually outside of DBeaver
3. While adding a directory with binaries in DBeaver, there is no tips to what directory user needs to poin to

**Comment by arhayka** [comment]
What we want to do:
- write in the documentation about local clients with sections for different OS and links on Oracle, PostgreSQL & MySQL documentation
- add the link to the convenient documentation near the **Local client** button and in the dialogue
- choose one name — **Local clients**/**Native clients** on buttons and in messages
