### ISSUE TITLE
Dbeaver asks for bind parameter values when query uses PostgreSQL dollar quoted string literal syntax

### ISSUE THREAD

**Issue by lukaseder** [dbeaver/dbeaver#15106]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows [Version 10.0.22000.376]
- DBeaver version: Version 21.3.2.202112271055
- Java version: 11.0.9.1+1

#### Connection specification:
- Database name and version: PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
- Driver name: pgjdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Dbeaver asks for bind parameter values for a query that doesn't have any bind parameters

#### Steps to reproduce, if exist:

Run this:

```sql
select $$ $a $$
```

It doesn't have any bind parameters, but uses the PostgreSQL dollar quoted string literal syntax. But Dbeaver asks for a value for the "parameter" `$a`. It doesn't happen for ordinary string literals:

```sql
select ' $a '
```

**Comment by ShadelessFox** [comment]
Thanks for the bug report.

**Comment by ShadelessFox** [comment]
Sorry for the confusion. It is intended behavior for <kbd>Code block</kbd> display style and can be changed in the preferences:

![image](https://user-images.githubusercontent.com/35821147/148225326-cc773657-c6de-432f-bba3-5af095aa9aa5.png)

Does it solve your issue?

**Comment by lukaseder** [comment]
Thanks, it's nice to be able to switch the display behaviour of dollar quoted string literals.

However, that's just a setting governing the UI *display* behaviour. `$$ $a $$` is interpreted as a string literal by the PostgreSQL server, hence, it never contains a bind variable.

In my opinion, that's a bug, not a question. By consequence, changing that setting didn't have any effect on my query...

**Comment by ShadelessFox** [comment]
I see. Thanks for the explanation.

By the way, to see the changes, you have to re-connect to the database.

**Comment by E1izabeth** [comment]
Hi, @lukaseder! 
`$$ .. $$` is a code block for DBeaver and `$a` inside code block is a binding parameter for DBeaver by default. I suppose we might not use binding parameters inside code blocks. What do you think?

**Comment by lukaseder** [comment]
`$$ .. $$` isn't a code block. It's just a dollar quoted string literal, like any other string literal. The use-case is to avoid having to escape apostrophes all over the place. See:
https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING

E.g. you can write `SELECT $$ a $$` to see what I mean

**Comment by lukaseder** [comment]
And, as such, there's no such thing as a bind parameter within a string literal.

**Comment by ShadelessFox** [comment]
The code block mode is just a view mode. It doesn't affect how this literal is interpreted. By treating it as a string literal, there's no way to access most of features that SQL editor provides (such as autocompete, code navigation, formatting, etc.).

Variable binding dialog is just one of such features. We can restrict a set of actions inside dollar strings if they are configured to be shown as code blocks.

**Comment by lukaseder** [comment]
Ah, I see. I thought the reference was PostgreSQL specific, sorry for the confusion. Thanks for clarifying it (again) 😅

I agree with both of you @E1izabeth and @ShadelessFox. Thanks for looking into this.

**Comment by Matvey16** [comment]
Verified
