### ISSUE TITLE
Unable to save connections made from CLI using connection parameters

### ISSUE THREAD

**Issue by deeco** [dbeaver/dbeaver#15100]
**Is your feature request related to a problem? Please describe.**
When creating a connection using the cli as per https://github.com/dbeaver/dbeaver/wiki/Command-Line#connection-parameters. 
The connections do no persist once the dbeaver client is closed. Can see manual creations from ui in the data-sources.json are persistent 

tried with create = true even though its default but connections never save in ui unless manually created

`dbeaver -con "name=${NAME}|driver=Test|host=${HOST}|port=${PORT}|database=${DATABASE}|user=${MSID}|${SSL}|${SSL_PASSW}|folder=Test|connect=false|create=true"`

**Describe the solution you'd like**
option to save the cli connection string in the data-spurces.json file with the manual created in ui

**Describe alternatives you've considered**
reference alternative saved file which opens for each client open

**Additional context**

**Comment by E1izabeth** [comment]
Hi again, @deeco! We added a new connection parameter to declare whether you want to save connection or let it stay temporary. To save new connection between launches you need to use `save=true` (please, see https://github.com/dbeaver/dbeaver/wiki/Command-Line#connection-parameters). By default `save` is set to `false`. It will be available in the next release.
