### ISSUE TITLE
Mysql/MariaDB can't see sessions detail

### ISSUE THREAD

**Issue by jppo** [dbeaver/dbeaver#15107]
When I want to see sessions I get the following message : 
Le plug-in org.jkiss.dbeaver.ext.oceanbase.ui n’a pas réussi à charger la classe org.jkiss.dbeaver.ext.mysql.ui.editors.MySQLSessionEditor.
Version : 21.3.2.202112271055
System Linux
Database MariaDB on Azure (PAAS), 
same problem with On Prem MariaDB and MySQL databases
Regards
JP P

**Comment by jppo** [comment]
Addendum : 
Sessions access is OK with Postgresql and MSSL databases.

**Comment by LonwoLonwo** [comment]
Hello @jppo 
Thanks for the bug report.

This issue was fixed in this ticket: https://github.com/dbeaver/dbeaver/issues/14958.

The New DBeaver version with the fix will be available 24.01.2022.
