### ISSUE TITLE
SQL 错误 [1105] [HY000]: Unknown system variable 'transaction_read_only'

### ISSUE THREAD

**Issue by tianmingxing** [dbeaver/dbeaver#15101]
#### System information: 
- Operating system (distribution) and version: MacBook Pro M1
- DBeaver version: 21.3.0.202112040536

#### Connection specification:
- Database name and version: [mycat](https://github.com/MyCATApache/Mycat-Server) （mysql proxy software）
- Driver name: mysql
- Do you use tunnels or proxies: SSH

#### Describe the problem you're observing:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/5615719/147811524-8c169716-30ee-4da5-9370-51942f902958.png">

#### Steps to reproduce, if exist:

I hope this error can be ignored to facilitate SQL execution and get the response results.

**Comment by LonwoLonwo** [comment]
Hi @tianmingxing 

Can you please tell me more about your issue? When did this issue appear? Also, a full [error log](https://github.com/dbeaver/dbeaver/wiki/Log-files) will be very helpful.

**Comment by tianmingxing** [comment]
There is another situation to report. When I connect to the database with Navicat, it works normally, and it seems to do better

log file: [归档.zip](https://github.com/dbeaver/dbeaver/files/7804916/default.zip)

**Comment by Matvey16** [comment]
@tianmingxing Can you try creating a connection with MySQL 5 driver?

**Comment by tianmingxing** [comment]
> @tianmingxing Can you try creating a connection with MySQL 5 driver?

<img width="500" alt="image" src="https://user-images.githubusercontent.com/5615719/149278667-5ebc4d44-4643-4dcb-9cc0-a286f4536fbb.png">



SQL 错误 [S1000]: Could not retrieve transaction read-only status from server
Could not retrieve transaction read-only status from server
Could not retrieve transaction read-only status from server
Unknown system variable 'transaction_read_only'
Unknown system variable 'transaction_read_only'

**Comment by Matvey16** [comment]
@tianmingxing I meant using this driver when creating a connection

![image](https://user-images.githubusercontent.com/82543000/149339556-a316b3cc-2af4-44c4-8f8c-160d68c6ab3b.png)

Or if you are using a custom copy, to copy it from this one.

**Comment by tianmingxing** [comment]
@Matvey16 @LonwoLonwo  The solution you mentioned has no effect。

<img width="651" alt="image" src="https://user-images.githubusercontent.com/5615719/149441811-0fce6b4e-f83c-400c-beb4-71937d594a01.png">

<img width="449" alt="image" src="https://user-images.githubusercontent.com/5615719/149441749-28095714-f84e-416c-917d-1767fe918231.png">

**Comment by tianmingxing** [comment]
If only unrecognized variables appear, can this situation be ignored? Do not interrupt the current operation, or the problem may be solved.

**Comment by Matvey16** [comment]
@tianmingxing For now it can't be ignored, but the last possible workaround is to use MySQL (Old) driver to create a connection. It works as a generic type, so would probably ignore this error. Please tell if it worked, otherwise we will need to dig deeper.

**Comment by tianmingxing** [comment]
use MySQL (Old) drive success! tks!
