### ISSUE TITLE
result break

### ISSUE THREAD

**Issue by Teiemo** [dbeaver/dbeaver#15109]
Hi. The values is Korean in grid is broken. 
Another db tools is okay but dbeaver has problem

I think encoding setting problem. but I don't find way to set

Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
NLS_LANGUAGE	AMERICAN
NLS_TERRITORY	AMERICA
NLS_CHARACTERSET	US7ASCII
NLS_NCHAR_CHARACTERSET	AL16UTF16

thank you

**Comment by ShadelessFox** [comment]
Hello @Teiemo,

Could you please provide a screenshot of the issue?

**Comment by Teiemo** [comment]
Hi. @ShadelessFox 

![캡처](https://user-images.githubusercontent.com/97074123/148142522-54814a00-8689-4be0-a264-56e8cbaca513.PNG)

Like this... haha
Korean word is broken

**Comment by uslss** [comment]
@Teiemo , what DBeaver version do you use?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. if it is still actual - feel free to reopen it

**Comment by MABOODAHMAD** [comment]
refer this link : https://github.com/dbeaver/dbeaver/assets/45058948/ce392a2c-10d0-4d6d-add8-b8ea132df1a9
