### ISSUE TITLE
where can I get the spark jar for Dbaever?

### ISSUE THREAD

**Issue by Poojalaxman** [dbeaver/dbeaver#15114]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by ShadelessFox** [comment]
Hello @Poojalaxman,

I'm not sure if your issue is related to DBeaver.

Please create a new discussion if your issue is not resolved.
