### ISSUE TITLE
PostgreSQL Function Dependencies (Trigger)

### ISSUE THREAD

**Issue by GnsCy** [dbeaver/dbeaver#15112]
#### System information: 
- Operating system  = Windows 10
- DBeaver version = 21.3.1

#### Connection specification:
- Database name and version = PostgreSQL 13

#### Describe the problem you're observing:
On initial startup of the application the dependency list of a function that is used by multiple triggers is correct.
Once you refresh the list then all the entries display the same table/schema as shown in the screenshot.

You need to restart the application to see the correct list again but if the list is refreshed once more, the same problem occurs.
![image](https://user-images.githubusercontent.com/92713743/148185972-f74cf801-ba09-412b-b685-befe9acdce43.png)

#### Steps to reproduce, if exist:

1. Create schema
2. Create a function that returns trigger
3. Create 2 tables each one having a trigger that uses the function created above
4. Check the dependency list of the function (It will show 2 records each one referencing the trigger/table/schema combination created above)
5. Refresh the list (Now it will show 2 records but the table/schema combination is wrong)

DDL:
```
CREATE SCHEMA test1;

CREATE OR REPLACE FUNCTION test1.trigger_set_timestamp()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN

    NEW.created_date = CURRENT_TIMESTAMP;
   
   	RETURN NEW;
	
END;
$function$;

CREATE TABLE test1.test1 (
id int,
created_date timestamp
);

CREATE TRIGGER trigger_set_timestamp 
BEFORE INSERT OR UPDATE ON test1.test1
FOR EACH ROW 
EXECUTE FUNCTION test1.trigger_set_timestamp();

CREATE TABLE test1.test2 (
id int,
created_date timestamp
);

CREATE TRIGGER trigger_set_timestamp 
BEFORE INSERT OR UPDATE ON test1.test2
FOR EACH ROW 
EXECUTE FUNCTION test1.trigger_set_timestamp();
```

Simple query showing the correct results:
```
SELECT 
pp.proname AS function_name , pc.relname AS table_name, pc.relnamespace::regnamespace::TEXT AS schema_name, pt.tgname AS trigger_name
FROM pg_catalog.pg_proc pp
JOIN pg_catalog.pg_depend pd 
	ON pp.oid = pd.refobjid 
JOIN pg_catalog.pg_trigger pt 
	ON pd.objid = pt."oid" 
JOIN pg_catalog.pg_class pc 
	ON pt.tgrelid = pc.oid
WHERE pp."oid" = <function object ID>
AND pc.relkind = 'r'
```

**Comment by LonwoLonwo** [comment]
Hello @GnsCy 

Thanks for the bug report.
Please provide test DDLs for steps 1 and 2 (trigger function and tables).

**Comment by GnsCy** [comment]
> Hello @GnsCy
> 
> Thanks for the bug report. Please provide test DDLs for steps 1 and 2 (trigger function and tables).

Hello @LonwoLonwo 

I have updated the bug report with more detailed explanation of the issue and added some test DDLs as well.
Please let me know if you need any additional information in order to reproduce the issue

**Comment by LonwoLonwo** [comment]
Unfortunately, I can't reproduce.

![bdgxxqqxGd](https://user-images.githubusercontent.com/45152336/148749423-47c92da9-8a24-4f44-954d-75949a78981d.gif)

Can you please make a video of the issue? Maybe it helps to reproduce.

**Comment by GnsCy** [comment]
I test it with the latest version (21.3.2) and indeed I couldn't reproduce the issue.
With previous versions (21.3.1, 21.3.0) though I could reproduce it.
![Media1](https://user-images.githubusercontent.com/92713743/149092470-7db23220-14fe-41de-b7f1-8340d18fb29b.gif)

So I guess we can close the issue as resolved ?

**Comment by LonwoLonwo** [comment]
> So I guess we can close the issue as resolved ?

yes. Thanks for the investigation!
