### ISSUE TITLE
dBEAVER 21.3.2 not loading

### ISSUE THREAD

**Issue by aravindhansps** [dbeaver/dbeaver#15113]
Application not loading at startup itself.

!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.equinox.preferences".

**Comment by ShadelessFox** [comment]
Hello @aravindhansps,

Please a [new issue using our issue template](https://github.com/dbeaver/dbeaver/issues/new?assignees=&labels=bug%2C+wait+for+review&template=bug_report.md&title=) and provide all required information.
