### ISSUE TITLE
Bump ClickHouse JDBC driver dependency

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/dbeaver#15118]
**Is your feature request related to a problem? Please describe.**
Before clickhouse-jdbc 0.3.2, the official JDBC driver relies on text-based data format for exchanging data between client and server, so it's inefficient, memory hungry, and does not working properly with datetime values and time zone. More importantly, starting from 0.3.2, its maven group id was changed from `ru.yandex.clickhouse` to `com.clickhouse`, and driver class was changed from `ru.yandex.clickhouse.ClickHouseDriver` to `com.clickhouse.jdbc.ClickHouseDriver`.
Note: the old group id and driver class will co-exist with the new ones until 0.4.0.

**Describe the solution you'd like**
Update ClickHouse JDBC driver in both DBeaver and CloudBeaver to 0.3.2 by:
1. change maven dependency to
  ```xml
  <dependency>
      <groupId>com.clickhouse</groupId>
      <artifactId>clickhouse-jdbc</artifactId>
      <version>0.3.2</version>
      <!--
        IMO, it's better to use shaded jar.
        You can change classifier to http if you prefer smaller package size(~800KB vs ~18MB)
      -->
      <classifier>all</classifier>
      <exclusions>
          <exclusion>
              <groupId>*</groupId>
              <artifactId>*</artifactId>
          </exclusion>
      </exclusions>
  </dependency>
  ```
2. update driver class to `com.clickhouse.jdbc.ClickHouseDriver`

**Describe alternatives you've considered**
Simply bump dependency version to 0.3.2 and change driver class to `com.clickhouse.jdbc.ClickHouseDriver`, and then update group id after 0.4.0 released.

**Additional context**
N/A.

**Comment by Skydiveroid** [comment]
Thank you for the future request!

**Comment by serge-rider** [comment]
New Clickhouse driver doesn't support older server versions (it fails with error `Sorry this driver only supports ClickHouse server 20.7 or above`).
Thus we can't just replace old driver with the new one. But we can add second driver configuration.
However I'm not sure that we need two Clickhouse drivers. What benefits the new driver provides?

**Comment by zhicwu** [comment]
Sorry I didn't make it clear. Sounds good to have two drivers if that's not too much trouble at your end.

> New Clickhouse driver doesn't support older server versions

The minimum supported version of ClickHouse is 21.3(see list at [here](https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease)).

> What benefits the new driver provides?

As you probably knew, ClickHouse spinout from Yandex was announced in late September 2021(details at [here](https://clickhouse.com/blog/en/2021/clickhouse-inc/)), and the official website was changed from https://clickhouse.tech to https://clickhouse.com. I hope this explained why we need a new driver with different maven group id and package name.

Apart from that, 0.3.2 is a planned release for refactoring and legacy driver will be gone in 0.4.0. As to benefits of the new driver from technical point of view:
1) layered APIs(light async client + JDBC)
2) complex data type support(e.g. array of tuples)
3) multi-protocol support(http and grpc for now)
4) better JDBC compliance(e.g. meta data, fake transactions, and standard synchronous update/delete etc.)
5) switched to binary data format resulting better performance and less memory footprints according to [benchmarks](https://github.com/ClickHouse/clickhouse-jdbc/issues/768)

**Comment by serge-rider** [comment]
Ok, this makes sense.
But how should we name this new driver to avoid confusing users? 
Should we leave the same icon for new driver?

**Comment by zhicwu** [comment]
> But how should we name this new driver to avoid confusing users?

Perhaps `ClickHouse` for the new driver, and `ClickHouse (Deprecated)` for the old one?

> Should we leave the same icon for new driver?

Yes.

**Comment by serge-rider** [comment]
Done

**Comment by uslss** [comment]
verified
