### ISSUE TITLE
"Window -  Preferences - User Interface - Confirmations - Close extra result tabs"     not working

### ISSUE THREAD

**Issue by KaseiHaku** [dbeaver/dbeaver#15126]
#### System information: 
- Operating system (distribution) and version: Win 10
- DBeaver version: 21.3.2.202112271055
- Additional extensions

#### Connection specification:
- Database name and version: MySQL 8
- Driver name: mysql-connector-java-8.0.17.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
When there are multiple result tabs in the view, then i use shortcut "Ctrl+Enter" to execute sql
the extra result tabs not closed

**Comment by uslss** [comment]
thanks for the report
