### ISSUE TITLE
Automate data export

### ISSUE THREAD

**Issue by devismu** [dbeaver/dbeaver#15128]
Is there a way to automate data export? I am looking for Query IN and Excel OUT, or something similar which is 100% automated. Or an interface that can be operated by someone to extract data with almost no technical knowledge of data engineering. Or could you built a connector for MS PowerAutomate?

![image](https://user-images.githubusercontent.com/13745525/148508988-7944e61d-876e-4a3c-88f3-ddebe61801c7.png)

Context:
Business users often do not know SQL and to use dbeaver they have to install drivers. This is not user friendly. I am looking forwad to design a front-end interface where people can submit data requests and then I can automate those SQL statements and generate an excel file and send it back to them. Most of the part can be handled in MS PowerAutomate, but there is no connector for dBeaver so can't automate the data export part.

**Comment by uslss** [comment]
@devismu Probably Tasks will be helpful in this case.
You can read more about them [here](https://github.com/dbeaver/dbeaver/wiki/Task-Management)
Could you check if it resolves your issue?

**Comment by uslss** [comment]
There have been no updates on the issue for a long time. If the issue is still present - feel free to reopen it.
