### ISSUE TITLE
CREATE OR REPLACE VIEW, But it does not automatically refresh the local view code

### ISSUE THREAD

**Issue by hktalent** [dbeaver/dbeaver#15129]
CREATE OR REPLACE VIEW, But it does not automatically refresh the local view code
<img width="347" alt="image" src="https://user-images.githubusercontent.com/18223385/148509231-80a12636-7c0c-4906-a32c-58f2a9a8d3b3.png">

<img width="739" alt="image" src="https://user-images.githubusercontent.com/18223385/148509304-531818c3-ff50-4bac-9c6f-15cb7b8b3c7c.png">

<img width="452" alt="image" src="https://user-images.githubusercontent.com/18223385/148509328-0e1cc4df-a2ac-4a12-ad41-aac249da6e99.png">
so is ok
Please support, but after modifying the table or view structure and attributes, it will be refreshed automatically

**Comment by Skydiveroid** [comment]
Thank you for the enhancement!

**Comment by uslss** [comment]
looks like it should be fixed in scope of #6398
