### ISSUE TITLE
the same sql return different result when i connect to mysql database or h2 database

### ISSUE THREAD

**Issue by baizhi1989** [dbeaver/dbeaver#15138]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.3.0.202111281534
- Additional extensions

#### Connection specification:
- Database name and version mysql  mysql-8.0.23
- Driver name mysql 5
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no
- Database name and version h2 database h2-1.4.199
- Driver name h2-1.4.199
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
 the same sql  return different result when i connect to mysql database or h2 database
#### Steps to reproduce, if exist:
CREATE TABLE `a` (
  `c1` varchar(100) DEFAULT NULL,
  `c2` varchar(100) DEFAULT NULL,
  `c3` varchar(100) DEFAULT NULL
) ;

INSERT INTO a (c1,c2,c3) VALUES  ('1','a\\b','c');

-- return nothing when connect to mySql database,  press \ onece
select * from a where c2 like '%a\b%';
-- return nothing when connect to mySql database,  press \ twice
select * from a where c2 like '%a\\\\b%';

-- return nothing when connect to H2 database, press \ onece
select * from  a where c2 like '%a\b%';
-- **return record** in when connect to database,  press \ twice
select * from  a where c2 like '%a\\\\b%';

**Comment by ShadelessFox** [comment]
Hello @baizhi1989,

As you mentioned, it depends on the database you're connected to.

We do not process SQL in any way, but the database may process your query differently.
