### ISSUE TITLE
Generate UPDATE SQL w/ Specific Columns

### ISSUE THREAD

**Issue by dalexander-trc** [dbeaver/dbeaver#15130]
**Is your feature request related to a problem? Please describe.**
There are situations when I want to update records on a specific environment based on another. In this situation, only one or two columns have changed value and those are the ones I want to update. Currently the generate SQL function will update all columns, which is fine, but not as concise when saving those statements off for source control/history reasons.

**Describe the solution you'd like**
The ability to select any or all columns when generating an UPDATE statement,

**Describe alternatives you've considered**
Currently, I will go through and manually delete the unchanged columns from the statements before saving them in source control or deployment history.

**Comment by Skydiveroid** [comment]
Thank you for the future request!

**Comment by ShadelessFox** [comment]
Similar to #13344, #14193

**Comment by ShadelessFox** [comment]
We should display a dialog for configuring the primary key and visible columns.

**Comment by ShadelessFox** [comment]
Hello @dalexander-trc,

We have several features that fall under your description, so I'm unsure what feature you are referring to.

Are you talking about the <kbd>Generate SQL</kbd> feature?

**Comment by dalexander-trc** [comment]
@ShadelessFox Yes, sorry if that was not clear. I am referring to the option provided on the right click menu for table rows.

Generate SQL -> UPDATE

**Comment by ShadelessFox** [comment]
Okay, thank you.

So it is indeed a duplicate. Please see #14193
