### ISSUE TITLE
Redshift - Import CSV slowness

### ISSUE THREAD

**Issue by helder-mattos** [dbeaver/dbeaver#15146]
#### System information: 
- Operating system: Windows 10
- DBeaver version : Version 21.3.2.202112271055
- Additional extensions : None

#### Connection specification:
- Database name and version: Redshift 
- Driver name : AWS / Redshift 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

I'm trying to import by using the Data transfer wizard a small CSV 70k rows and 10 columns. A new table is correctly created in redshift but the data load process is extremely slow. I've tried multiple types of data load and still I have a load time of several minutes. Same data loaded through S3 bucket + AWS import is executed within a few seconds.

#### Steps to reproduce, if exist:
Data import to Redshift

#### Include any warning/errors/backtraces from the logs
N/A

Others reported same at #10897 but I couldn't find any issue specific to redshift

**Comment by LonwoLonwo** [comment]
Hello @helder-mattos 

Have you tried "multi-row insert" or "skip bind values" settings?

![2022-01-11 15_28_25-Data Transfer](https://user-images.githubusercontent.com/45152336/148942644-500ff9f2-7679-4687-a427-fc48b491f2b7.png)

**Comment by deepaksenthilkumar** [comment]
Yeah. This should make it fast, we import millions of rows extremely fast with these 2 options!

**Comment by helder-mattos** [comment]
Well, the issue is gone. I still don't know the cause but it was solved
when I've changed the "commit after row insert" setting.
