### ISSUE TITLE
Focus isn't at the resultset in SQL when trying to add the row

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#15147]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.3.2

#### Describe the problem you're observing:
Focus still remains in SQL editor when trying to add a row in the resultset
#### Steps to reproduce, if exist:
1. Execute some Select query or Open table using Read in SQL editor
2. Create a new row in the resultset using Add new row button (hotkey is not working until user click to any place in the resultset)
3. Start to type something to the highlighted cell

**Actual result**
The entered test is shown in SQL editor, not in the highlighted cell in the resultset
![dbeaver_UxSRJazsWH](https://user-images.githubusercontent.com/31996417/148936108-287b3ddf-0ad3-4095-ac24-b0fd23090f2b.gif)

**Comment by Matvey16** [comment]
Verified
