### ISSUE TITLE
Tools and Tasks in Lite Edition broken

### ISSUE THREAD

**Issue by bechtold** [dbeaver/dbeaver#15142]
#### System information: 
- macOS Montery 12.0.1 (M1 Max)
- DBeaver Lite Edition 21.3.0

#### Connection specification:
- PostgreSQL

#### Describe the problem you're observing:
I used the Community Edition 21.3.2 to create a truncate task that I saved. Now, while using the trial of the Lite Edition I get an error `Could not create the view: org.jkiss.dbeaver.tasks` and I can't create a truncate task as tasks and tools are not even available.

#### Steps to reproduce, if exist:
Use Community Edition to create a task and open the tasks view. Close Community Edition and open the Lite Edition.

Community Edition:
<img width="556" alt="Screenshot 2022-01-10 at 22 57 00" src="https://user-images.githubusercontent.com/1275950/148846647-19af0c3f-2032-4e35-b85b-957f29772b93.png">
<img width="374" alt="Screenshot 2022-01-10 at 23 03 56" src="https://user-images.githubusercontent.com/1275950/148846662-9f16931b-6c15-412f-a1c0-9d3a44e696c5.png">

Lite Edition:
<img width="513" alt="Screenshot 2022-01-10 at 22 57 15" src="https://user-images.githubusercontent.com/1275950/148846717-375ee6d9-8684-4fab-a6b8-96b29833a5e6.png">
<img width="369" alt="Screenshot 2022-01-10 at 22 57 11" src="https://user-images.githubusercontent.com/1275950/148846709-a2902477-f5b8-4839-ace6-8ebed614eebe.png">

**Comment by flambchap** [comment]
Hi @bechtold. Thank you for your interest in our products. Unfortunately, DBeaver LE doesn't support tasks. I also want to tell you that you can ask such questions using our ticket system on dbeaver.com.

**Comment by bechtold** [comment]
Hi @akilovich, thx for your answer. It looked like a bug, so I didn't think it was a question. I guess DBeaver LE is not an option then.
