### ISSUE TITLE
Advanced Copy as SQL doesn't copy table name as case sensitive

### ISSUE THREAD

**Issue by alesito85** [dbeaver/dbeaver#15158]
#### System information: 
- Operating system (distribution) and version: MacOS Monterey
- DBeaver version: 21.3.2 Community

#### Connection specification:
- Database name and version: Postgres 12
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When copying result row in order to get an insert SQL statement the table name is not copied with double quotes and proper (case sensitive) table name.

Example table name "investmentRounds" is copied as "investmentrounds" and without quotes. This kind of statement doesn't work and the name of the table must be corrected.

#### Steps to reproduce, if exist:
1. Select some data
2. Highlight a row in the results tab
3. Right click -> Advanced Copy -> Copy as SQL
4. Paste in editor and notice the table name to be all lower case

**Comment by LonwoLonwo** [comment]
Hello @alesito85 

Have you tried to change Copy settings?

![2022-01-12 12_56_58-DBeaver Ultimate 21 3 2 - LargeTable2](https://user-images.githubusercontent.com/45152336/149118201-6f1b67e5-b2d6-4b2b-97be-0913614ef13e.png)


![2022-01-12 12_58_06-DBeaver Ultimate 21 3 2 - LargeTable2](https://user-images.githubusercontent.com/45152336/149118207-0c9623da-00e8-4d69-8076-d982d899e7e8.png)

**Comment by alesito85** [comment]
@LonwoLonwo identifier case setting is set to "mixed" on my instance. "as is" is not available, only mixed, upper and lower.

**Comment by LonwoLonwo** [comment]
Ok. Can you please test the Early Access version? https://dbeaver.io/files/ea/

Maybe it was fixed here - https://github.com/dbeaver/dbeaver/issues/15059

**Comment by alesito85** [comment]
I've tried, but dmg file seems incomplete (using MacBook Air M1) and .tar.gz doesn't appear to work either. I've tried downloading same arch.

**Comment by LonwoLonwo** [comment]
@alesito85 
Maybe this advice can help with EA: https://github.com/dbeaver/dbeaver/issues/13125#issuecomment-876418323

> (Side note in case anyone trying to run the EA version finds this thread: trying to just run the EA version normally fails in macOS. You need to disable GateKeeper for the downloaded app:
> xattr -dr com.apple.quarantine ~/Downloads/DBeaver.app (Replace path with your own if needed, but odds are it's just sitting in your Downloads folder.)

**Comment by alesito85** [comment]
@LonwoLonwo I've tried it using this method and it worked (I was able to launch this version of DBeaver - verified in about, build number). However the issue with advance copy persists, I've verified that case is set to "as is".

**Comment by LonwoLonwo** [comment]
Can you please provide a screen of your Export SQL settings?

I can't reproduce, unfortunately.

**Comment by alesito85** [comment]
Here you have.

![image](https://user-images.githubusercontent.com/4399118/149461416-a84ec865-30bd-4cc5-a131-80bc29be3673.png)

**Comment by LonwoLonwo** [comment]
Hmm... Ok. And what about table DDL?

**Comment by alesito85** [comment]
Here's the DDL:

```-- public."walletTrackingAddresses" definition

-- Drop table

-- DROP TABLE public."walletTrackingAddresses";

CREATE TABLE public."walletTrackingAddresses" (
	id serial4 NOT NULL,
	"name" varchar(255) NOT NULL,
	address varchar(255) NOT NULL,
	"lastEntryDate" timestamptz NOT NULL,
	"createdAt" timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	"updatedAt" timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "walletTrackingAddresses_pkey" PRIMARY KEY (id)
);

**Comment by uslss** [comment]
thanks for the report and clarification

**Comment by Matvey16** [comment]
When identifier case is set to lower, it doen't work. Upper case works only for table name, but not for table names

![dbeaver_XbzCiHvPxW](https://user-images.githubusercontent.com/82543000/149882143-75a91282-ce6e-4c61-98bf-033c60848141.gif)

**Comment by alesito85** [comment]
Identifier was set to "as is".

**Comment by Matvey16** [comment]
Verified
