### ISSUE TITLE
Issue with opening of SQL editor

### ISSUE THREAD

**Issue by tati-kru** [dbeaver/dbeaver#15152]
There is some issue with the SQL editor opening. 
The stack trace is available here:
![FIwuNwbVQAQ1wTv](https://user-images.githubusercontent.com/30336552/148976111-be85611b-9f96-48ba-a653-008135dd2ae0.jpeg)
We need to handle this error in a better way.

**Comment by ShadelessFox** [comment]
It looks like you have force-closed DBeaver while having a SQL console opened.

Not sure if we should fix this.

**Comment by tati-kru** [comment]
It is a user comment: "I was trying to add a foreign key for about 20 minutes and I couldn't get DBeaver to either accept it or delete it.  Then my computer crashed, and when DBeaver restarted, it displayed this."

**Comment by ShadelessFox** [comment]
Fixed.

Steps to reproduce:
1. Open an SQL console
2. Cause workbench to persist its state without actually shutting down the application (e.g. using auto-save feature)
3. Forcely terminate the application (via task manager, etc.), so the persisted state of the workspace is not overridden
4. Start application

**Comment by Matvey16** [comment]
Verified
