### ISSUE TITLE
Oracle Driver is not getting loaded...getting NPE

### ISSUE THREAD

**Issue by YuriDude** [dbeaver/dbeaver#15150]
#### System information: 
- Operating system (distribution) and version: Windows 10 (Version 10.0.19042.1415)
- DBeaver version: Version 21.3.0.202112091630
- Additional extensions: None

#### Connection specification:
- Database name and version: Oracle
- Driver name: --
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No
- Java Runtime: java.runtime.version=11.0.12+7 (_from configs_)

#### Describe the problem you're observing:
Oracle driver is not getting loaded...

#### Steps to reproduce, if exist:
Connect To Database... > Choose Oracle (in selection pane either "All"or "Popular" tabs.. > click "Next"  and nothing happens
#### Include any warning/errors/backtraces from the logs

![Ora-Driver-NPE](https://user-images.githubusercontent.com/5156159/148970459-81ff4db7-af05-446e-aab3-5beaf3d39543.JPG)

**Comment by LonwoLonwo** [comment]
Hello @YuriDude 

Sorry, I can't reproduce this issue.

Maybe ["Reset workspace"](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace) can help you.
Or you can download the latest [DBeaver version](https://dbeaver.io/).

If nothing of the proposed will help, please provide a [log file](https://dbeaver.io/) of the issue.

**Comment by uslss** [comment]
@YuriDude did you install DBeaver from MS Store?

**Comment by uslss** [comment]
seems to be related to #14882

**Comment by YuriDude** [comment]
> @YuriDude did you install DBeaver from MS Store?

Yes , it was installed from MS Store.
Context: I work at organization with fairly strict policies and I am not an admin of local machine, thus installation of any software requires approvals and help desk ticket. Installation from MS Store circumvents it.

**Comment by YuriDude** [comment]
> seems to be related to #14882

Not sure -  I **definitely** do not get what is displayed at 14882.

**Comment by YuriDude** [comment]
DBeaver Team I have no problems to submit error logs, I just don't feel comfortable to post them **"for the rest of world"**. As it would be "invitation" for troubles even though I would be able to obfuscate "_what needs to be obfuscated_"

**Comment by uslss** [comment]
@YuriDude could you check if the issue persists in the current MS Store version? (21.3.4)

**Comment by uslss** [comment]
There has been no update on the issue for a long time. if it is still actual - feel free to reopen it
