### ISSUE TITLE
BigQuery JDBC Connection Error

### ISSUE THREAD

**Issue by krishna4ldw** [dbeaver/dbeaver#15153]
#### System information: 
- Operating system (distribution) and version : Windows 10 10.0.19041 Build 19041
- DBeaver version : Version 21.3.2.202112271055
- Java version : java version "11.0.11" 2021-04-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)
- Additional extensions

#### Connection specification:
- Database name and version : Google BigQuery
- Driver name : Google BigQuery
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
When connecting to BigQuery through oauth type : User-Based
Key path contains client id and client secret 
test connection is working 
But when we expand connection it is asking for authorization code 
![image](https://user-images.githubusercontent.com/35433878/149026745-657a00e6-bd70-40cb-9475-117b83292127.png)
But when paste the code it error 
400 Bad Request
POST https://oauth2.googleapis.com/token

{

  "error" : "invalid_grant",

  "error_description" : "Bad Request"

}

**Comment by Matvey16** [comment]
@krishna4ldw Are you sure your key file is valid? I tried reproducing this issue but the uri works for me and opens google authentication page.

Can you copy the URI that DBeaver suggests you? (without user ID of course) Like so:
`https://accounts.google.com/o/oauth2/auth?client_id=____________.apps.googleusercontent.com&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&scope=https://www.googleapis.com/auth/bigquery`

**Comment by krishna4ldw** [comment]
Yes uri link works and opens google authentication page. Are you able to browse datasets in database explorer?

**Comment by Matvey16** [comment]
@krishna4ldw Does it ask for authorization code when you click test connection?

**Comment by krishna4ldw** [comment]
Yes it prompts. As i mentioned earlier test connection works but after that when we try to expand connection to view datasets then it fails.

**Comment by krishna4ldw** [comment]
It keeps prompting please obtain an authorization code from the following URL

**Comment by Joel92** [comment]
I have a similar issue. I have been able to query BQ through DBeaver but the authorization window keeps prompting all the time.

**Comment by DenverKirrane** [comment]
Mine is doing this, any updates?

**Comment by DenverKirrane** [comment]
@Joel92 @krishna4ldw - It may be OKTA, are you using that? If so see the instructions on this page for OAUTH

https://docs.starburst.io/data-consumer/clients/dbeaver.html

**Comment by josepaul1988** [comment]
I have a similar problem. When connecting to Big Query database using User-Based Authentication i have been prompted to obtain authorization code exactly "two times". Once i provide the auth code two times it will login successfully. It would also ask for new code for each SQL Query editor we open, but i have by-passed it by changing settings at "SQL Editor-->Open Separate Connection for each editor".

I will get bad request error if i copy paste the same Auth code for the two prompts (the prompt request url is same in both auth prompt windows).

Example Request Url: https://accounts.google.com/o/oauth2/auth?client_id=0123456.apps.googleusercontent.com&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&scope=https://www.googleapis.com/auth/bigquery

**Comment by josepaul1988** [comment]
> changing settings at "SQL Editor-->Open Separate Connection for each editor".

Can you please try changing settings at "SQL Editor-->Open Separate Connection for each editor".

**Comment by Matvey16** [comment]
As said in @josepaul1988 comment, you can disable this prompt for separate editors by disabling separate connection for each SQL Editor. As for other prompts, it looks like separate connection for metadata read, it can also be disabled in connection settings
![image](https://user-images.githubusercontent.com/82543000/172837929-503d1123-b286-4643-8bf3-f3cabca29dcd.png)
