### ISSUE TITLE
Querying nested function SQL will cause the interface to be unresponsive and abnormally slow

### ISSUE THREAD

**Issue by wrck** [dbeaver/dbeaver#15155]
#### System information: 
- Operating system (distribution) and version : win10
- DBeaver version : 21.3.2
- Additional extensions : DBeaver Office Support

#### Connection specification:
- Database name and version : MySQL 5.7.26
- Driver name : MySQL Connector/J mysql-connector-java-8.0.27
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When I query SQL like the example, the UI will be stuck and unresponsive, and the query time of the SQL is abnormally long. The non response time of the interface is usually the execution time of the query results；
The execution time often multiplies with the number of nested functions;
However, in other query tools, or using the same driver to run directly in the code, the results will be returned in 1 millisecond
> SELECT 
    replace(replace(replace(replace(
    replace(replace(replace(replace(
    replace(replace(replace(replace(
        replace(concat(columnsWithAlias, ",$"), concat(tableAlias, ".a,"), ''), 
        concat(tableAlias, ".b,"), ''),
        concat(tableAlias, ".c,"), ''),
        concat(tableAlias, ".d,"), ''),
        concat(tableAlias, ".e,"), ''),
        concat(tableAlias, ".f,"), ''),
        concat(tableAlias, ".g,"), ''),
        concat(tableAlias, ".h,"), ''),
        concat(tableAlias, ".i,"), ''),
        concat(tableAlias, ".j,"), ''),
        concat(tableAlias, ".k,"), ''),
        concat(tableAlias, ".l,"), ''), 
        ",$", ""
    ) AS columns
FROM 
(SELECT 'ppm.a,ppm.b,ppm.b,ppm.d,ppm.e,ppm.f,ppm.g,ppm.h,ppm.i,ppm.j,ppm.k,ppm.l,ppm.m,ppm.n ' AS columnsWithAlias, 'ppm' AS tableAlias) t;

#### Steps to reproduce, if exist:
Query the example SQL
#### Include any warning/errors/backtraces from the logs

There are no exceptions

**Comment by uslss** [comment]
#14053

**Comment by uslss** [comment]
#14735

**Comment by uslss** [comment]
We use a JSQLParser library for the correct queries highlighting, folding adding, and auto-completion support.
But sometimes it takes too long to process the query.
It is needed to add a special editor's setting with the ability to turn off query parsing. So queries will be processed much faster, but some DBeaver features will be disabled for the editor.

**Comment by wrck** [comment]
@uslss Thank you for your reply. If there is a temporary solution to this problem, how can I prevent it

**Comment by serge-rider** [comment]
Fixed.
The problem was caused by JSQLParser. It has an issue with deep nested parameters parsing.
The library version was upgraded to 4.3 and deep parser feature was disabled (it doesn't break parser but makes it less precise).

**Comment by uslss** [comment]
verified
