### ISSUE TITLE
you can't select item 'org.jkiss.dbeaver.ext.oracle.model error in  Schema Compare in Dbeaver EE

### ISSUE THREAD

**Issue by antonyraj05** [dbeaver/dbeaver#15157]
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version : Version 21.3.0.202112052011 (Enterprise edition)
- Additional extensions 

#### Connection specification:
- Database name and version: Oracle 11g
- Driver name: NA
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : NA

#### Describe the problem you're observing:
While comparing the 2 different Schema's, I'm not able to select the packages to compare.
getting screenshot error
#### Steps to reproduce, if exist:
![image](https://user-images.githubusercontent.com/97591906/149091797-8d4ff3e7-cdb4-48ab-8780-3094f4307dd3.png)

**Comment by antonyraj05** [comment]
I'm new to use Dbeaver, my target is to try this for Azure CICD, please help

**Comment by LonwoLonwo** [comment]
Hello @antonyraj05 

You can read about Schema Compare here - https://github.com/dbeaver/dbeaver/wiki/Schema-compare

Unfortunately, packages are not in the list of the simple schema compare. You can compare schemas with packages (in Oracle) only with the Liquibase PRO key - https://github.com/dbeaver/dbeaver/wiki/Schema-compare#using-schema-compare-with-liquibase-pro-key 

But maybe we must add the ability to choose specific packages from the list for the Oracle database.

**Comment by antonyraj05** [comment]
Hello @LonwoLonwo 
Thanks for sharing, I do have a liquibase pro trail key & which is applied to Dbeaver too.
I tried to create Liquibase change log too same

**Comment by LonwoLonwo** [comment]
> I tried to create Liquibase change log too same

And it worked? Or was some problems?

**Comment by LonwoLonwo** [comment]
Also - did the schema compare with all packages correct? 
The main issue is only with picking only some packages, not all?

**Comment by antonyraj05** [comment]
Hi yes 
I've pro key but still while comparing the same issue happening,
I tried to compare overall schemas comparison not comparing the Packages & procedures inside that

I use Dbeaver EE

![image](https://user-images.githubusercontent.com/97591906/150074063-f4586e8e-dd0a-46ca-83ce-489a4262cf55.png)

**Comment by LonwoLonwo** [comment]
Ok. Few questions.

https://github.com/dbeaver/dbeaver/wiki/Schema-compare#using-schema-compare-with-liquibase-pro-key

Did you import your PRO Liquibase key into DBeaver? If yes - did you restart DBeaver after what?

In the " Objects types " dialog, do you see Procedures And Packages in the compare objects list in the "Objects types" dialog? Are their buttons checked?

**Comment by uslss** [comment]
There have been no updates on the issue for a long time. If the issue is still present - feel free to reopen it with additional info.
