### ISSUE TITLE
Extended character set characters are not being displayed/treated appropriately by DBeaver

### ISSUE THREAD

**Issue by rhanton** [dbeaver/dbeaver#15154]
#### System information: 
- OSX 11.6
- DBeaver version 21.2.3.202110151816

#### Connection specification:
- MySQL 5.7
- mysql-connector 5.1.39
- SSH Tunnel thru Centos 7

#### Describe the problem you're observing:
When I use the application to store data including the special character values described further in this article - https://stackoverflow.com/questions/2826191/converting-ms-word-curly-quotes-and-apostrophes - into a JSON MySQL 5.7 column, the data character is stored correctly, but when I attempt to view it in DBeaver, it does not render correctly, but even worse, when I attempt to duplicate the column it becomes even mangled more as the stand-in characters DBeaver is using get translated into the database. So for instance, a u2019 character (right single quotation mark) becomes â in DBeaver's result-set view, but is then translated into Ã¢ÂÂ when you copy that row and insert back to the DB.

#### Steps to reproduce, if exist:

1. Store characters outside of the simple latin character set area into a MySQL database with another tool or application.
2. Connect to that database and view the row of data with that character in DBeaver. Ideally the row is displayed with the desired characters, not some type of replacement characters due to lack of characters in a character set.
3. Attempt to clone that row, with the expectation that at-worst, the new row is equal to the original. We shouldn't see new un-desired characters in that row.

**Comment by uslss** [comment]
@rhanton could you check if issue is actual for you against 21.3.2 version?

**Comment by rhanton** [comment]
@uslss Upgraded to 21.3.2 and it operates exactly the same as 21.2.3.x (as described above).

**Comment by uslss** [comment]
@rhanton thanks for testing. Could you provide some sample data to reproduce an issue? Thanks in advance

**Comment by uslss** [comment]
There have been no updates on the issue for a long time. If the issue is still present - feel free to reopen it with additional info.
