### ISSUE TITLE
Showing "Data" on a CockroachDB never completes (hangs) on a very large table with a stacked primary key

### ISSUE THREAD

**Issue by StevenWooding** [dbeaver/dbeaver#15165]
To fix the issue you simply have to add "order by primary key <tablename>" to the backend query. So it should be an easy fix.

#### System information: 
- OS: Ubuntu 20.04
- Dbeaver Version 21.1.2
- Additional extensions: None

#### Connection specification:
- Database: CockrochDB 21.2
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc): No

#### Describe the problem you're observing:
Clicking the "Data" tab on a very large table (millions of records) that has a stacked primary key, the result never loads.

You can replicate the problem by doing a simple select like so through the console:
`select * from "zone" limit 100;`
Then it will also load forever.

But you can fix that query to work properly like so:
`select * from "zone" order by primary key "zone" limit 100;`

#### Steps to reproduce, if exist:
Click the "Data" tab on a very large CockroachDB table with a stacked (multi) primary key.

**Comment by LonwoLonwo** [comment]
Hello @StevenWooding 

Can you provide table DDL with a stacked (multi) primary key, please?

**Comment by uslss** [comment]
There have been no updates on the issue for a long time. If the issue is still present - feel free to reopen it.
