### ISSUE TITLE
I'm getting an error Connection timed out: connect when it try to connect to an data base. What should I do

### ISSUE THREAD

**Issue by dhekum** [dbeaver/dbeaver#15162]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by uslss** [comment]
please, provide info accordingly to the [template ](https://github.com/dbeaver/dbeaver/issues/new?assignees=&labels=bug%2C+wait+for+review&template=bug_report.md&title=)

**Comment by uslss** [comment]
There have been no updates on the issue for a long time. If the issue is still present - feel free to reopen it.
