### ISSUE TITLE
Add "Reacreate table" option in datatransfer.

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#15167]
We need to add the "Reacreate table" option in the data transfer import options.

With the ability to recreate existing tables (DROP and CREATE).

It can help users with CSV files that have changed (The number of columns in the file may differ from the original table, for example).

**Comment by LonwoLonwo** [comment]
![Sbawi1iUws](https://user-images.githubusercontent.com/45152336/154058981-6406761d-fbfc-4648-b6b0-8a8fd477deab.gif)

![35xatnOQHE](https://user-images.githubusercontent.com/45152336/154059012-3cff6a81-7b43-4e0c-b05a-2614306978c9.gif)

![2022-02-15 23_32_17-Data Transfer](https://user-images.githubusercontent.com/45152336/154145042-5ef691b9-fa40-41b0-95bb-635930447a93.png)

**Comment by LonwoLonwo** [comment]
Implemented.

**Comment by uslss** [comment]
verified
