### ISSUE TITLE
Can we add a new database connection please to Apache Druid. 

### ISSUE THREAD

**Issue by veerappans** [dbeaver/dbeaver#15172]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Skydiveroid** [comment]
Thank you for the future request!

**Comment by serge-rider** [comment]
Apache Calcite Avatica driver configuration was added. This driver supports Apache Druid as well.

**Comment by veerappans** [comment]
I dont see Apache Calcite Avatica. I only see these following options:

[image: image.png]
Can you please help.

**Comment by uslss** [comment]
@veerappans it will be available in 21.3.4
![image](https://user-images.githubusercontent.com/31996417/151127016-a1f9ec96-b842-453e-bd5b-d24ed1ebd561.png)

**Comment by veerappans** [comment]
Thank you. Looking forward to it. Any approx release date?
