### ISSUE TITLE
Installing sp_WhoIsActive procedure with DBeaver

### ISSUE THREAD

**Issue by Leopold702** [dbeaver/dbeaver#15178]
#### System information: 
- Operating system (distribution) and version: Windows Server 2019
- DBeaver version: 21.3.2.202112271055 (CE)
- Java version: 11.0.12
- sp_WhoIsActive: 11.32
- Additional extensions: none

#### Connection specification:
- Database name and version: SQL Server 2019
- Driver name: MS SQL Server / SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:

[sp_WhoIsActive](http://whoisactive.com/) is a well-known stored procedure for SQL Server activity monitoring. Installing it with SSMS is very easy: you just open the **.sql** file and click **Execute** (F5).

In DBeaver there is no **Execute** option. Instead, there are two separate options: **Execute SQL Statement** and **Execute SQL Script**. Apparently **Execute SQL Script** should be the equivalent of the SSMS's **Execute**. However, if I open the sp_WhoIsActive's **.sql** file and click **Execute SQL script**, DBeaver reports multiple execution errors,  for example:

`SQL Error [102] [S0001]: Incorrect syntax near ';'.`
`SQL Error [137] [S0002]: Must declare the scalar variable "@filter".`
`SQL Error [50000] [S0001]: Input parameters cannot be NULL`
`SQL Error [102] [S0001]: Incorrect syntax near 'END'.`
`SQL Error [137] [S0002]: Must declare the scalar variable "@filter_type".`

etc.

If I click **Skip all**, script execution continues for a long time and doesn't seem to ever complete.

If I check the procedures list afterward, **sp_WhoIsActive** is present there. However, if I check the source code, it shows only one line.

So I wonder if this is a bug of DBeaver, or it doesn't support the installation of procedures this way? If so, what is the proper way to install them?

#### Steps to reproduce, if exist:

1. Download [sp_WhoIsActive v11.32](http://whoisactive.com/downloads/who_is_active_v11_32.zip)
2. Open the file **who_is_active_v11_32.sql** in DBeaver
3. Click **Execute SQL Script**

**Comment by LonwoLonwo** [comment]
Hello @Leopold702 

Please, can you highlight all your script in SQL Editor and use Alt+X?

**Comment by Leopold702** [comment]
Hi @LonwoLonwo,

I'm still getting the same problem. Here is a demo.

https://user-images.githubusercontent.com/64221830/149513921-572417fc-3c44-4bcb-97be-e241628c94a3.mp4

**Comment by LonwoLonwo** [comment]
And highlighting + Ctrl+Enter?

**Comment by Leopold702** [comment]
> And highlighting + Ctrl+Enter?

Then it fails like this:

![image](https://user-images.githubusercontent.com/64221830/149516016-3bede7f0-0eea-4efe-8378-751da31caf54.png)
Here is also [error log](https://github.com/dbeaver/dbeaver/files/7870330/sp_whoisactive.log).

**Comment by LonwoLonwo** [comment]
You can try to change standard script delimiters in Preferences:

![2022-04-04 10_39_29-DBeaver Ultimate 22 0 2 - _orcl_Script-140](https://user-images.githubusercontent.com/45152336/161496617-c9c232ab-bcae-4ed4-9285-a5445b48a53d.png)

**Comment by Leopold702** [comment]
This did the trick. Thank you very much!

**Comment by LonwoLonwo** [comment]
Thanks for the answer @Leopold702
