### ISSUE TITLE
Firebird procedure/function overloads aren't displayed correctly in schema tree

### ISSUE THREAD

**Issue by lukaseder** [dbeaver/dbeaver#15176]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows [Version 10.0.22000.434]
- DBeaver version: Version 21.3.2.202112271055
- Java version: OpenJDK build 17+35-2724

#### Connection specification:
- Database name and version: 4.0.0
- Driver name: `org.firebirdsql.jdbc:jaybird:4.0.0.java8`
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

I've created an overloaded procedure and function, and only one of the two displays in the schema overview:

<img width="167" alt="image" src="https://user-images.githubusercontent.com/734593/149491293-2f2cdbe9-7981-4844-aff6-3318788301d0.png">

#### Steps to reproduce, if exist:

Create these objects:

```sql
CREATE PROCEDURE p_overload (i INTEGER)
AS
BEGIN
END;

CREATE FUNCTION p_overload (j INTEGER)
RETURNS INTEGER
AS
BEGIN
  RETURN 1;
END;
```

Now only the function is visible:

<img width="167" alt="image" src="https://user-images.githubusercontent.com/734593/149491293-2f2cdbe9-7981-4844-aff6-3318788301d0.png">

Now, delete the function in the tree, refresh the tree, and now the procedure is visible:

<img width="179" alt="image" src="https://user-images.githubusercontent.com/734593/149491460-85ff5f79-d5f6-4649-bc56-9ce93a228f82.png">

**Comment by uslss** [comment]
thanks for the report
