### ISSUE TITLE
Display Bug: Bottom line of SQL Editor pane is obscured by horizontal scroll bar

### ISSUE THREAD

**Issue by david-a-hillman** [dbeaver/dbeaver#15174]
#### System information: 
- Kubuntu 20.04.3 LTS
- DBeaver version Version 21.3.2.202112271055

#### Describe the problem you're observing:
The bottom line of any SQL Editor pane is obscured by the horizontal scrollbar when the mouse pointer is hovered over that region ( which causes the scrollbar to be rendered ).  See attached screenshot.

#### Steps to reproduce, if exist:
Create an SQL Editor pane.  Enter sufficient lines of text to reach the bottom line of the pane.  Hover your pointer over that line.  At this point, a horizontal scrollbar will be rendered on top of, and obscuring, the final line of text in the Editor pane.

![DBeaver-bug](https://user-images.githubusercontent.com/34042329/149462916-48ab76c4-b98c-4cfb-86d7-5e4676801f95.png)

**Comment by uslss** [comment]
thanks for the report
duplicates #10950
