### ISSUE TITLE
Password plaintext visible when using -con parameter with password included. Shown in 'Installation Information' screen.

### ISSUE THREAD

**Issue by 0luc** [dbeaver/dbeaver#15175]
#### System information: 
- Windows Server 2016 x64
- DBeaver CE	21.3.2.202112271055
- No extensions

#### Connection specification:
- Oracle 19c
- Oracle
- No proxy or tunnels

#### Describe the problem you're observing:
When using -con parameter with password included. The password is plaintext shown in: Help -> Installation Information -> Tab 'Configuration' as shown below.

-con
name=**$name**|create=true|connect=true|driver=Oracle|host=**$host**|port=**$port**|database=**$database**|user=**$username**|password=**$passwordinplaintext**

#### Steps to reproduce, if exist:
The password is plaintext shown in: Help -> Installation Information -> Tab 'Configuration' as shown above.

I cannot find a fysical location for this information in the workspace folder. So am not able to remove it programatically.

**Comment by Matvey16** [comment]
@LucvandenBerg Thank you for the report. We will look what can be done about it

**Comment by Matvey16** [comment]
Verified
