### ISSUE TITLE
Apache kylin support 

### ISSUE THREAD

**Issue by barbyware** [dbeaver/dbeaver#15189]
I could use the generic JDBC for apache kylin. 
But it is possible to provide an apache kilyn connector,

**Comment by Skydiveroid** [comment]
Thank you for the future request!

**Comment by LonwoLonwo** [comment]
https://mvnrepository.com/artifact/org.apache.kylin/kylin-jdbc

**Comment by serge-rider** [comment]
Apache Kylin driver was added. Besides Kylin JDBC artifact it also requires XML Bind library (which is no longer a part of JDK)
