### ISSUE TITLE
Lost connection every time

### ISSUE THREAD

**Issue by 3DRaven** [dbeaver/dbeaver#15186]
#### System information: 
- Ubuntu 20.04
- DBeaver 21.2.2.202110030714 installed as deb

#### Connection specification:
- Postgres 12
- org.postgresql.Driver
- VPN only

#### Describe the problem you're observing:

After few minutes I can't execute SQL on connection. Every time I need to use "check connection" in context menu for connection and invalidate it. As consequence do not work "rescans" of tables metadata and other by pressing F5 and deleted tables showed in db tree.

#### Steps to reproduce, if exist:

1. Connect to PG db
2. execute SQL
3. Wait ~5min
4. try to execute another
5. You will wait to timeout or need to invalidate connection

May be in settings I can set autoreconnect time?

**Comment by uslss** [comment]
@3DRaven Connection validation time could be changed in Connection Settings
![image](https://user-images.githubusercontent.com/31996417/149728704-d6b2ef7a-4c56-4f70-aba7-23f75167ad20.png)
Also, you can change Keep-alive to non-null
![image](https://user-images.githubusercontent.com/31996417/149728764-49918522-e207-49d4-b764-0af19b637798.png)
Could you check if changing these settings resolves your issue?

**Comment by 3DRaven** [comment]
I will try use this and will write later about results

**Comment by 3DRaven** [comment]
It works for me. I set keep alive to 1s and connection validation to 1000. Thank you. It is strange why keep alive is 0 by default. But ok.

**Comment by 3DRaven** [comment]
It works for me. I set keep alive to 1s and connection validation to 1000. Thank you. It is strange why keep alive is 0 by default. But ok.
