### ISSUE TITLE
Please support TIBERO.

### ISSUE THREAD

**Issue by younjunsu** [dbeaver/dbeaver#15192]
Hello. I am an engineer working as a DBA in Korea.
Please support Tibero(RDBMS) products, made in Korea.

Please support TIBERO.
------------------------------
**DBeaver**
- Version : COMMNUNITY EDITION 21.3.2.202112271055
- OS : Windows 10 64bit

**TIBERO**

- VERSION : 6
- TYPE : RDBMS
- JDBC Connection URL : jdbc:tibero:thin:@{host}:{port}:{database}
- JDBC Driver FILE : You need to pull it out of the tibero database and use it.
-- PATH : tibero6/client/lib/jar/tibero6-jdbc.jar
- TIBERO JDBC usage manual
-- https://technet.tmaxsoft.com/upload/download/online/tibero/pver-20150504-000002/tibero_jdbc/chapter_usage.html

**※ If you need JDBC demo file and tibero test connection information, I will send it to you by e-mail.**

**Example**
![a1](https://user-images.githubusercontent.com/27267460/149721152-c68dfc14-98c1-4ca1-b139-96d0ebb01e4c.png)
![a2](https://user-images.githubusercontent.com/27267460/149721155-723c226e-05b8-42fb-b58f-152c4b068da4.png)
![a3](https://user-images.githubusercontent.com/27267460/149721158-a70f3c91-ca82-4c94-8382-049acc224bf0.png)
![a4](https://user-images.githubusercontent.com/27267460/149721160-a22befde-adb1-4959-aa68-80859ba4cf26.png)
![a5](https://user-images.githubusercontent.com/27267460/149721163-b8e0d848-9746-4fdb-8c80-1f1f86fd4fe5.png)
![a6](https://user-images.githubusercontent.com/27267460/149721164-964233d1-c54b-4aae-b387-72a6f600e7ec.png)

**Comment by Skydiveroid** [comment]
Thank you for the future request!

**Comment by Skydiveroid** [comment]
Sorry, but there is no available public driver.
