### ISSUE TITLE
Now a day if you forget your local password, Dbeaver has is no more usefull.Please, create a recovery password feature.

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#15191]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by uslss** [comment]
@scubaDevs please, provide more info about your issue. Clear steps to reproduce will be helpful. Which DBeaver version do you use?

**Comment by ghost** [comment]
https://stackoverflow.com/questions/39928401/recover-db-password-stored-in-my-dbeaver-connection

**Comment by ghost** [comment]
Dbeaver 21.3.2

**Comment by uslss** [comment]
Unfortunately, it is not planned for CE version.
For now, the database password could be shown as plain text in Connection settings:
![image](https://user-images.githubusercontent.com/31996417/151169460-adf0ee08-05ab-48f6-9726-7a9fb4958ef7.png)

Note: [Master Password for the project](https://github.com/dbeaver/dbeaver/wiki/Project-security#project-password) should be set.
![image](https://user-images.githubusercontent.com/31996417/151169210-3ac08c23-acfc-47b1-b330-a3c8c9c7b8dd.png)

**Comment by ghost** [comment]
Thank you!
