### ISSUE TITLE
Countless issues after upgrading from (very) old version #1 - Metadata

### ISSUE THREAD

**Issue by GreatEMU** [dbeaver/dbeaver#15198]
Because of problems on an older version I skipped upgrading for many years. Now after upgrading to the current version I can't count the issues anymore. What happend to this usefull tool?

This is issue #1:
Metadata only work in places when formatin SQL-Script with comment characters

Example:
```sql
Select *
  from TabA a
--
join TabB b
  on b.Field1 = a.Field2
```
In this example, FileB's metadata does not appear. If I delete the comment characters, the data is displayed. With another join table (with comment characters), the metadata would be displayed again.

#### System information: 
- Operating system: Win 10
- DBeaver: 21.3.2
- Additional extensions

#### Connection specification:
- Database name: DB2 iSeries
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by LonwoLonwo** [comment]
Hello @GreatEMU 

Unfortunately can't reproduce your issue.

![2022-01-17 18_43_58-DBeaver Ultimate 21 3 3 - _postgres 13 3_Script-81](https://user-images.githubusercontent.com/45152336/149801159-7a824264-e178-4345-adcb-f4dc84fd9eff.png)

![2022-01-17 18_44_26-DBeaver Ultimate 21 3 3 - _postgres 13 3_Script-81](https://user-images.githubusercontent.com/45152336/149801162-2fd26056-5dee-4d14-8299-265ec23b3478.png)

Can you provide more details, please?

The screen of your "Code completion" settings page will also be helpful.

![2022-01-17 18_51_38-Preferences](https://user-images.githubusercontent.com/45152336/149801487-6cdd3af0-16e4-495f-bd80-2ce578ed4772.png)

**Comment by serge-rider** [comment]
@GreatEMU 
Are you sure you upgraded DBeaver version correctly?  
Do you use zip archive or Windows installer?   
Is there anything in the Error Log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by GreatEMU** [comment]
Hello,

I did the installation by using the windows installer.
Shoul I try another complete new installation?

![image](https://user-images.githubusercontent.com/75827076/150126942-49e14dd5-8329-4999-8c61-773a4383acae.png)

[.log](https://github.com/dbeaver/dbeaver/files/7896959/default.log)

**Comment by uslss** [comment]
@GreatEMU , sorry for the late response.
Is it still actual for you?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. if it is still actual - feel free to reopen it
