### ISSUE TITLE
Wrong row count passed to NLS.bind() method in ResultSetViewer.java

### ISSUE THREAD

**Issue by bianyun1981** [dbeaver/dbeaver#15194]
#### System information: 
- Operating system (distribution) and version: Windows 10 Enterprise Edition (Simplified Chinese), 21H1
- DBeaver version: 21.3.3-SNAPSHOT (The latest development version at the time of posting)
- Additional extensions: none

#### Describe the problem you're observing:
I found an accidentally caused bug that didn't exist in the last release (21.3.2). The buggy code is at line 2065 of plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetViewer.java, as shown in the screenshot below:
![01](https://user-images.githubusercontent.com/17854699/149724002-66d39eab-f896-47af-8c38-7166f0c81f1e.jpg)

**In version 21.3.2, these codes are still like this:**
![02](https://user-images.githubusercontent.com/17854699/149724376-302b3b92-16d4-4b2b-b715-73fec47f7c77.jpg)

**Comment by ShadelessFox** [comment]
Hello @bianyun1981,

Thanks for the report.

That was an unintended typo.

**Comment by Matvey16** [comment]
Verified
