### ISSUE TITLE
Countless issues after upgrading from (very) old version #4 - Script names are truncated on tabs

### ISSUE THREAD

**Issue by GreatEMU** [dbeaver/dbeaver#15201]
Because of problems on an older version I skipped upgrading for many years. Now after upgrading to the current version I can't count the issues anymore. What happend to this usefull tool?

This is issue #4:
The scipt names are sometimes truncated on the tabs.

System information:
Operating system: Win 10
DBeaver: 21.3.2
Additional extensions
Connection specification:
Database name: DB2 iSeries
Driver name
Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by ShadelessFox** [comment]
Hello @GreatEMU,

Thanks for the report.

Please see https://github.com/dbeaver/dbeaver/issues/14293#issuecomment-947443011.
