### ISSUE TITLE
Dbeaver generates timely GET_TABLES tasks when executing a simple select for hadoop tables (Impala engine)

### ISSUE THREAD

**Issue by andrey-orderby** [dbeaver/dbeaver#15216]
#### System information: 
- Windows 10 Version 20H2
- DBeaver version 7.2.3.202010191702

#### Connection specification:
- Impala 3.2.0-cdh6.2.1
- com.cloudera.impala.jdbc41.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - No

#### Describe the problem you're observing:
Simple select query generates GET_TABLES task which takes > 40 seconds to execute. I would rather it did not generate it at all.
I have thousands of tables in my storage in about 20 different schemas. Therefore, I would like to be able to control, when Dbeaver reloads the whole metadata. I can reload it just for the tables I need myself. Is there a way to turn off this queries behind the scenes, that I did not even ask for? I've been struggling with the settings, but could not find any checkbox that would change that behaviour.

I have found a checkbox that should be un-checked 'Reload table metadata'. It seemed to help to avoid similar background queries 'show database' (in case of a select .. from <some table> limit 100) but did not affect the issue in question. Though I am not completely sure it helps. I do not yet understand the logic of when Dbeaver send those background queries.

#### Steps to reproduce, if exist:
select to_timestamp('5999-12-31', 'yyyy-MM-dd') as ttt

#### Include any warning/errors/backtraces from the logs
Impalad shows 
|  Statement  |  Query type  |  Start time  | End time  |  Duration  |
|  -----------  |  ------------  |  -----------  |  ---------  |  ----------  |
|  select to_timestamp('5999-12-31', 'yyyy-MM-dd') as ttt  |  QUERY  |  2022-01-18 16:56:11.496071000  |  2022-01-18 16:56:11.514144000  |  18.073ms  |
|  GET_TABLES  |  QUERY  |  2022-01-18 16:55:18.879816000  |  2022-01-18 16:56:11.510215000  |  52s630ms  |

**Comment by andrey-orderby** [comment]
Anybody? Something? Anything?

**Comment by Matvey16** [comment]
@andrey-orderby I can't reproduce it on the latest version. 7.2.3 is pretty old, can you test it on the latest DBeaver 21.3.3?

**Comment by andrey-orderby** [comment]
I've upgrated my dbeaver to 21.3.0.202111281534. Still see the same long GET_TABLES queries in the impala daemon
![Screenshot_285](https://user-images.githubusercontent.com/97964871/151138509-0c8a637e-253f-4d1c-9762-9e552b54dcb3.jpg)
![Screenshot_286](https://user-images.githubusercontent.com/97964871/151138513-c6f8eedc-711b-467b-ba42-62a6a6b0aefc.jpg)
.

**Comment by Matvey16** [comment]
@andrey-orderby Do you see this query in DBeaver query manager?

**Comment by andrey-orderby** [comment]
This effect pops up from time to time. I do not know what triggers it. But when I call this particular select, that I have written of, or just a simple select * from <table> limit 100, I sometimes get this long task. 
I have checked my settings, set all checkboxes to check in query manager. I have not used it ever before, only used Execution log. But now that I have opened it, I saw this strange tasks, which according to query manager took 0 ms, while simple select 100 rows took 40 sec.
Whereas in impalad, as soon as I started my query I saw this GET_TABLES task running.
![Screenshot_287](https://user-images.githubusercontent.com/97964871/151170046-84c110d9-c759-4f73-adeb-cdb0a44df54b.jpg)
![Screenshot_290](https://user-images.githubusercontent.com/97964871/151170053-01af1344-e08d-450b-b4b3-891198877cee.jpg)
![Screenshot_291](https://user-images.githubusercontent.com/97964871/151170057-7944b914-bd7e-46bf-90b1-572c2d3c5f18.jpg)
![Screenshot_292](https://user-images.githubusercontent.com/97964871/151170059-c7e60b06-9b92-498f-ab75-d3ad5bd2498c.jpg)

**Comment by Matvey16** [comment]
@andrey-orderby Thank you for the investigation. I searched through different impala documentation and it looks like an expected behavior of impala JDBC driver that uses this method to retrieve metadata. As a temporary workaround I can recommend disabling local catalog mode on your server (this should stop the driver from using this method). Please say if this helps. We will investigate this issue to find a way to disable this if possible.

**Comment by andrey-orderby** [comment]
Thanks for your answer! I have directed that piece of advice to my colleagues from IT (I personally do not have acces to server settings). It may take a while before they respond.

**Comment by uslss** [comment]
There has been no update on the issue for a long time. if it is still actual - feel free to reopen it
