### ISSUE TITLE
Incompatible JVM error on startup.

### ISSUE THREAD

**Issue by OttoDelphia** [dbeaver/dbeaver#15213]
An Incompatible JVM error appears as follows:
"Version 1.8.0_211 of the JVM is not suitable for this product.  Version: 11 or greater is required.
A quick check of the console reveals that the system is running  java version 17.0.1 however.

**Comment by Matvey16** [comment]
@OttoDelphia Hello, can you specify how did you install DBeaver?

**Comment by OttoDelphia** [comment]
This was installed using the downloads from the DBeaver site some time ago.
This is a company managed machine, so it is possible that something has changed outside of DBeaver.  I will attempt to re-install.
Thank you for your reply.

**Comment by Matvey16** [comment]
@OttoDelphia If it doesn't work after reinstall, I would suggest checking your `path` and `javahome` environment variables. Also the fact that DBeaver used a different Java than the one it come packaged with suggests that it is started in some nonregular way. Did you start it from default desktop shortcut/.exe file?

**Comment by OttoDelphia** [comment]
Yes, this was started from the same shortcut.  However, now that you mention the path, I do recall the path variables being reset this past week in relation to some other applications.  Let’s chalk this one up to user error.
Thank you for the reply.  I’m on my way to getting back up again.

**Comment by evanlesmez** [comment]
Have the same problem. Installed on archlinux with pacman.

**Comment by sohzm** [comment]
Same issue on archlinux with pacman

**Comment by geekyBoogiepop** [comment]
I still have this issue. Does anyone know a fix for this?

**Comment by sohzm** [comment]
Hey, I got the fix. (for arch-linux only I think)
```sh
~ $ archlinux-java status                             # this will show the available java versions
Available Java environments:
  java-11-openjdk
  java-17-openjdk
  java-18-openjdk (default)
  java-8-openjdk
~ $ sudo archlinux-java set java-18-openjdk    # this will set the java version to the one needed :)
```
(a reboot is needed after this (maybe))

**Comment by knotman90** [comment]
> ```shell
> sudo archlinux-java set
> ```
works! 
No reboot needed

**Comment by twielens** [comment]
I've got the JVM message now as well. I've installed and used DBeaver from the microsoft store and it updated to 22.3.4 and since then it stopped working and I'm getting the error. It seems it stopped using its own JVM and is trying to use the JVM version installed on my PC. I have no control over that JVM (company laptop, can't install unpackaged software).

**Comment by inittree** [comment]
> 

the same problem here

**Comment by inittree** [comment]
> I've got the JVM message now as well. I've installed and used DBeaver from the microsoft store and it updated to 22.3.4 and since then it stopped working and I'm getting the error. It seems it stopped using its own JVM and is trying to use the JVM version installed on my PC. I have no control over that JVM (company laptop, can't install unpackaged software).

The same issue here

**Comment by ahmetkarakoc** [comment]
> > I've got the JVM message now as well. I've installed and used DBeaver from the microsoft store and it updated to 22.3.4 and since then it stopped working and I'm getting the error. It seems it stopped using its own JVM and is trying to use the JVM version installed on my PC. I have no control over that JVM (company laptop, can't install unpackaged software).
> 
> The same issue here


+1

**Comment by ahmetkarakoc** [comment]
I found a solution for myself.
For windows users, try removing the shortcut from the start bar and running the application from the application file in the C:\Users\username\AppData\Local\DBeaver path.
@twielens @inittree

**Comment by inittree** [comment]
@ahmetkarakoc, thank you, but a have DBeaver installation from Microsoft Store (application location in the C:\Program Files\WindowsApps path). This path unavailable for me (and for admin users).

**Comment by ahmetkarakoc** [comment]
> @ahmetkarakoc, thank you, but a have DBeaver installation from Microsoft Store (application location in the C:\Program Files\WindowsApps path). This path unavailable for me (and for admin users).

if this didn't work for you. You can download and install the application again from the original site without uninstalling the old application. When you run the application again from the file path you have installed, i hope it will work without any problems.

**Note:** I'm not entirely sure, but I think there is a problem with the shortcut icon changing.

**Comment by justin-tomlinson** [comment]
broken from windows store for me too

**Comment by MalkMcJorma** [comment]
I have the Windows Store version. It's broken with Oracle's JRE 8, but does work with e.g. Microsoft's OpenJDK 17.

**Comment by fkesheh** [comment]
Windows Store version doesn`t work for me either, regular installer worked fine

**Comment by pculka** [comment]
Aaand same here. Windows Store version throws this error. Worked before, doesn't now ...
Direct installed DBeaver EE works (but I ran out of license...)

**Comment by anatoly-kireev** [comment]
Same here Windows store version just broke up. I even don't have java 8 installed.

**Comment by anatoly-kireev** [comment]
For some strange reason the directory structure got messed up with the lastest update
![image](https://user-images.githubusercontent.com/23073361/217596866-716a59b7-6782-4773-8250-8d47ef76fe83.png)
please note the jre/jre path in the screenshot

**Comment by kimtiago** [comment]
> I've got the JVM message now as well. I've installed and used DBeaver from the microsoft store and it updated to 22.3.4 and since then it stopped working and I'm getting the error. It seems it stopped using its own JVM and is trying to use the JVM version installed on my PC. I have no control over that JVM (company laptop, can't install unpackaged software).

same here

**Comment by cdcanasg** [comment]
a temporal solution: https://superuser.com/questions/1219494/how-to-point-to-jre-home-in-dbeaver-ini

create a shortcut for dbeaver and modify its target property to run with properly vm 
![image](https://user-images.githubusercontent.com/18086765/217625243-df05cb66-62fe-43b2-a408-9ef99ed5029c.png)

**Comment by ryabca** [comment]
> a temporal solution: https://superuser.com/questions/1219494/how-to-point-to-jre-home-in-dbeaver-ini
> 
> create a shortcut for dbeaver and modify its target property to run with properly vm ![image](https://user-images.githubusercontent.com/18086765/217625243-df05cb66-62fe-43b2-a408-9ef99ed5029c.png)

Hi, just for me, it is not working for windows store version((. the reason is - it needs to have have access to windows apps directory. In my case i canot get access there becuase my user rights restricted. So, i can create shortcut, but it runs with error - can not get access to the file or path.

**Comment by pculka** [comment]
FYI guys> 
![image](https://user-images.githubusercontent.com/4672645/220282669-afd14916-23e5-4515-98c5-c3b38b48c903.png)

It's so very nice and polite, that this issue was closed without any of the staff mentioning this. Makes me so really want go and pay for Enterprise Edition with a great vision of such awesome support...

not.

DataGrip says hi.

**Comment by Piokaz** [comment]
> Hey, I got the fix. (for arch-linux only I think)
> 
> ```shell
> ~ $ archlinux-java status                             # this will show the available java versions
> Available Java environments:
>   java-11-openjdk
>   java-17-openjdk
>   java-18-openjdk (default)
>   java-8-openjdk
> ~ $ sudo archlinux-java set java-18-openjdk    # this will set the java version to the one needed :)
> ```
> 
> (a reboot is needed after this (maybe))

Got the same issue as everyone and this resolved it, thanks !
(I'm on EndeavourOS, based on Arch).


```
$ archlinux-java status
Available Java environments:
  java-11-openjdk (default)
  java-20-openjdk

$ sudo archlinux-java set java-20-openjdk
```

**Comment by ammfat** [comment]
> Hey, I got the fix. (for arch-linux only I think)
> 
> ```shell
> ~ $ archlinux-java status                             # this will show the available java versions
> Available Java environments:
>   java-11-openjdk
>   java-17-openjdk
>   java-18-openjdk (default)
>   java-8-openjdk
> ~ $ sudo archlinux-java set java-18-openjdk    # this will set the java version to the one needed :)
> ```
> 
> (a reboot is needed after this (maybe))

I have same issue in Manjaro (arch-based). It resolved the issue as-well, thank you!

**Comment by dgknyl** [comment]
Hello, I had this problem today. As a solution; Make sure "Included Java" is selected during installation/re-install.
![image](https://github.com/dbeaver/dbeaver/assets/33714761/965aec86-449b-4f16-a4be-0ebc1772d9b0)

**Comment by gohstgohst** [comment]
> Hello, I had this problem today. As a solution; Make sure "Included Java" is selected during installation/re-install. ![image](https://user-images.githubusercontent.com/33714761/259967869-965aec86-449b-4f16-a4be-0ebc1772d9b0.png)

It's just for me, DBeaver needs openjdk 17 or greater, not Oracle JRE 1.8.0_xxx.
