### ISSUE TITLE
how to edit value in the resultset after execute a select ?

### ISSUE THREAD

**Issue by woxiangbo** [dbeaver/dbeaver#15229]
after execute a select qurey, there is "yellow lock" symbol, and can not edit the data, how to resolve it ?

![image](https://user-images.githubusercontent.com/3446874/150304380-d65651af-a0bd-40bb-8c0e-feb50d112b4d.png)

**Comment by uslss** [comment]
@woxiangbo  unfortunately, cannot reproduce an issue. What DBeaver version do you use? What database do you use?

**Comment by woxiangbo** [comment]
> @woxiangbo unfortunately, cannot reproduce an issue. What DBeaver version do you use? What database do you use?

DBeaver: 21.1.5.202108160727
database: mysql

thanks for your answer， actually, the symbol "yellow lock" appears irregular,  can't reproduce each time.
do you know when will the "yellow lock“ appears ? in other words, what conditons make it appear?

**Comment by uslss** [comment]
@woxiangbo , sorry for the late response. Could you check if it is still present for you against 22.0.1?

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still reproducible against the recent version - feel free to reopen it.
