### ISSUE TITLE
stored procedure

### ISSUE THREAD

**Issue by oneforever** [dbeaver/dbeaver#15227]
Is it possible to add a feature, for example, to execute stored procedures in the same way as PLSQL, by filling out tables and clicking execute.

**Comment by Skydiveroid** [comment]
Thank you for the feature request!

**Comment by LonwoLonwo** [comment]
Hello @oneforever 
Please provide more info about your request.
Examples will be helpful.

You can now choose the "Execute procedure" option in the navigator tree. And it will create a query with parameters. In the execution step, you need just replace these parameters, and the query will be executed.

![2023-09-11 19_11_48-Window](https://github.com/dbeaver/dbeaver/assets/45152336/705991cc-8556-418f-90c8-8c248711f980)

![2023-09-11 19_11_34-Window](https://github.com/dbeaver/dbeaver/assets/45152336/04ae9fad-bf22-4b90-b6df-3765d6c2fa40)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
