### ISSUE TITLE
Scroll down can execute irreversible INSERT/UPDATES after rollback

### ISSUE THREAD

**Issue by piaste** [dbeaver/dbeaver#15220]
#### System information: 
- Operating system (distribution) and version
Windows 10 x64
- DBeaver version
21.3.2
- Additional extensions
none

#### Connection specification:
- Database name and version
PostgreSQL 12
- Driver name
JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
Yes (SSH)

#### Describe the problem you're observing:

When a results table has a limited fetch size and the user scrolls down, DBeaver runs the query again, presumably with an OFFSET ... LIMIT parameter. 

However, it does so even when 

 (a) the query is not a SELECT but e.g. an UPDATE ... RETURNING command
 (b) the original query happened inside a transaction that's no longer active

Either of these conditions should prevent DBeaver from running data modification queries after a simple scrolling.

#### Steps to reproduce, if exist:

- Create a table `t` with a large number of rows (greater than the current result fetch size), e.g.:
```sql
select  *
into t
from generate_series(1, 1000) num;
```
- Run the query:
```sql
begin;

update t set num = 2 * num returning *;

rollback;
```

- Go to the results tab and scroll down past 200. DBeaver will re-run the UPDATE every time you scroll, without a transaction wrapper, quickly multiplying the contents of table t several times.

- Check the state of the table:
```sql

select max(num) from t
-- result: 32000 or some other power of 2 * 1000, depending how long you scrolled
```

**Comment by uslss** [comment]
thanks for the report

**Comment by Matvey16** [comment]
Verified
