### ISSUE TITLE
not able to use the ssh tunnel to connect to a remote database

### ISSUE THREAD

**Issue by mrajancsr** [dbeaver/dbeaver#15236]
#### System information: 
- Operating system (distribution) and version - Mac M1 2021 Montery Macbook pro
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version - Postgresql
- Driver name - org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? ssh

#### Describe the problem you're observing:
I'm having trouble connecting to my remote amazon aws instance.  When i use my terminal: 
ssh -i "timescale.pem" ubuntu@secret.amazonaws.com, i am able to connect via my terminal. 

In dbeaver, i am getting connection issues
#### Steps to reproduce, if exist:
Went to SSH and clicked on Use SSH tunnel
Then typed my host/ip: secret.amazonaws.com
Username: ubuntu
Authentication Method: Public Key
Private Key: /Users/me/timescale.pem
Advanced settings: SSHJ.  
Test tunnel configuration says its connected.  

Then i go to Main tab and put host: localhost, database: example, authentication: database native, username: postgres, password: ******, test connection gives me error "FATAL error, could not write init file"

**Comment by ShadelessFox** [comment]
Hello @mrajancsr,

Thanks for the detailed description.

Could you please attach debug logs? Please see [Log files](https://github.com/dbeaver/dbeaver/wiki/Log-files).

**Comment by uslss** [comment]
There have been no updates on the issue for a long time. If the issue is still present - feel free to reopen it with additional info.
