### ISSUE TITLE
.NET data provider 

### ISSUE THREAD

**Issue by ClodoaldoPinto** [dbeaver/dbeaver#15238]
Is is possible to use a dot net data provider in Dbeaver? What I need now is the Teradata one which is already installed in Windows 10 and works in Visual Studio.
There is a certain network configuration, a VPN connection, in which the jdbc driver connection is blocked but allows the dot net data provider to connect (in Visual Studio)

**Comment by Skydiveroid** [comment]
Thank you for the feature request!

**Comment by flambchap** [comment]
Hi @ClodoaldoPinto. DBeaver primarily uses JDBC drivers. To make this kind of setup work, we need some kind of JDBC-.NET  bridge. AFAIK, they do not exist. I'm sorry, but it seems like there is nothing we can do.
