### ISSUE TITLE
Syntax error in the PostgreSQL data transfer replace insert method.

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#15230]
DBeaver 21.3.2

This issue occurred in the case of data import in the PostgreSQL table and enabled setting "Replace method" - "On conflict do update set."

Steps to reproduce:

- Create to tables:

```sql
CREATE TABLE Employee (
	"Rid" int4 NOT NULL,
	last_name varchar(40) NOT NULL,
	CONSTRAINT employee_pk PRIMARY KEY ("Rid")
);

CREATE TABLE Employee2 (
	"Rid" int4 NOT NULL,
	last_name varchar(40) NOT NULL,
	CONSTRAINT employee2_pk PRIMARY KEY ("Rid")
);
```

- Insert some data in the Employee2 table.
- Use right-click on the table Employee2 in the navigator tree and choose "Export data."
- Choose "Database" export, select Employee table as a target.
- On the Import setting page, choose "Replace method" - "On conflict do update set."
- Click on "Proceed"

![2022-01-20 11_52_49-Data Transfer](https://user-images.githubusercontent.com/45152336/150306443-162c85f7-cf7c-4dc5-b505-876d66c5bf48.png)

Expected behavior: Successful export.

Actual: An error appears

![2022-01-20 11_49_17-DBeaver Lite 21 3 0 - employee](https://user-images.githubusercontent.com/45152336/150309743-b8a2e28d-f61e-4e22-8dff-e04ed56d9c1c.png)

**Comment by Matvey16** [comment]
Verified
