### ISSUE TITLE
close jdbc connection hangs (multiplatform)

### ISSUE THREAD

**Issue by kpconnell** [dbeaver/dbeaver#15239]
I am not providing any details because this is a systemic issue across multiple platforms and drivers.

Connection management in a slow and or unstable network environment is absolutely atrocious. 

THROW AWAY CONNECTIONS THAT ARE NOT RESPONDING!!!   DO NOT CHECK THEM, DO NOT "CLEAN UP".   CREATE A LIGHTWEIGHT METHOD FOR CONNECTING....

**Comment by Matvey16** [comment]
@kpconnell Can you add more details about your use case. You are talking about slow/unstable network on server side or client side? What do you mean by "throw away connections"?

**Comment by kpconnell** [comment]
@Matvey16  I'm not sure how to respond to the question about "side" - Network paths do not really have "sides" they have segments.   Any segment can be slow or drop packets.      By throw away I mean:  "Stop trying to utilize existing connections if they aren't responding within.. say.. 500ms.  Just create a new connection, and make sure new connections are lightweight (simply the connection, no metadata traffic).  

Here's the basics of a reproduction:
1) Have the client create a connection to remote database server (remote = 500+ miles and 10+ routers away)
2) write a simple query like "select column_name from information_schema.columns limit 1"
3) Run the query
4) disconnect the client computer from the network, and connect to a different network( the client to a different IP address)
4) run the query again


Current Result: Query 5) takes several minutes to finish due to poor assumptions and unnecessary ceremony within the tool's networking design.

Desired Result:  Query results 5) return in no more than double the time of 3)

**Comment by Matvey16** [comment]
@kpconnell Thank you for clarification, now I see what you meant.

**Comment by Matvey16** [comment]
@kpconnell Can you say how it is different from #13902 ?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. if it is still actual - feel free to reopen it
