### ISSUE TITLE
Better support for accessing databases in Kubernetes

### ISSUE THREAD

**Issue by nostradani** [dbeaver/dbeaver#15242]
Accessing database in Kubernetes currently requires manual work upfront. If the database isn't exposed from the cluster (which is usually the case), you have to expose it locally using 'kubectl port-forward': 

https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/

Since DBeaver already offers access to databases using ssh port forwarding, it would be really nice, if a similar option would be available for Kubernetes port forwarding.

The required settings would need to include:
- The kubectl context
- The resource name
- The Kubernetes namesapce

**Comment by Skydiveroid** [comment]
Thank you for your proposal.

**Comment by Floeig** [comment]
Hello, I love the idea indeed!

**Comment by maxvisser** [comment]
I saw this feature request in a stackoverflow post mentioned by I guess @Floeig 
https://stackoverflow.com/questions/73383192/how-do-i-connect-to-mysql-on-kubernetes-with-dbeaver-directly-instead-of-using-k/75899887#75899887

@Nican @Lotykun @kwongtn98 @dpenas @Destrolaric @khwj @barjola @misimpso @phpwutz 
I thought I would post my workaround here aswell:
https://stackoverflow.com/a/75899887/13981027

**Comment by arhayka** [comment]
Depends on https://github.com/dbeaver/dbeaver/issues/20347
We want to improve the UI of the connection dialog and then add Kubernetes to it.

**Comment by bekicot** [comment]
@serge-rider I checked the code, no instance of kubernetes. Also i checked the the docs in here https://github.com/dbeaver/dbeaver/wiki/Kubernetes-configuration i found no kubernetes settings in the 23.1.5 builds

Is it enterprise only?

**Comment by serge-rider** [comment]
@bekicot yes, it is enterprise only, t was initially marked as EE/PRO feature. It will be included in version 23.2 release.

In future we may move this feature in the Community version but not this year.
