### ISSUE TITLE
No error is thrown when executing erroneous postgres script task

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#15244]
#### System information: 
- Win10
- DBeaver CE 21.3.3

#### Connection specification:
- Database name and version: PostgreSQL(14, 12...)

#### Describe the problem you're observing:
The script runs without problems, but we 

#### Steps to reproduce, if exist:
1. Create SQL script with mistakes and save it to your computer
2. Check that it doesn't works when executing from SQL editor
3. Create a task with type "PostgreSQL Script task" with the created file
4. Start this task
**Expected**:we expect an error to be thrown
**Actual**: no data was inserted, but we see "success message"
![image](https://user-images.githubusercontent.com/43252954/150507655-34637be4-f611-4c09-bc9b-3c1a25a73436.png)

**Comment by Matvey16** [comment]
Verified
