### ISSUE TITLE
Update pg_dump version

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#15243]
Current version pg_dump is 13.3. This version is incompatible with PostgreSQL 14

**Comment by LonwoLonwo** [comment]
Pg_dump/pg_restore tools updated to version 14.

**Comment by uslss** [comment]
CE:
![image](https://user-images.githubusercontent.com/31996417/162201334-6f0a6ea2-4794-4831-9341-f933cdb428ba.png)

**Comment by Matvey16** [comment]
Verified
