### ISSUE TITLE
Missing last character of table name in Editors View

### ISSUE THREAD

**Issue by 0red** [dbeaver/dbeaver#15257]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
- DBeaver version 21.3.2.202112271055
- Additional extensions: standard installation 

#### Connection specification:
- Database name and version: PostgreSQL 10.6 on x86_64-pc-mingw64, compiled by gcc.exe (Rev5, Built by MSYS2 project) 4.9.2, 64-bit
- Driver name : org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?   no - connection to localhost:5432

#### Describe the problem you're observing:
On the editor views tab on some tables (red on picture) the last character of table name is missing.
For the some (green) is working correctly.

![2022-01-23_13h26_19](https://user-images.githubusercontent.com/11916804/150678660-4ed1e699-f654-4e67-ba67-f58564824274.png)

#### Steps to reproduce, if exist:
It's hard to find any corellation because i.e. regulamin, bsou(t) and ne(t) are the schemas tabs  --> here for short one (even enaaught space is visible for placing last char)
and other are table's data tab (for vmax working correctly for field d29 - last 9 is missing

**Comment by LonwoLonwo** [comment]
Hello @0red 

Can you please check the new DBeaver version 21.3.3? https://dbeaver.io/
Eclipse version updated in the next release. Maybe it will help with this issue too.

**Comment by 0red** [comment]
it's helped. Thx.
