### ISSUE TITLE
Unexpected driver error occurred while connecting to the database      java.lang.NullPointerException

### ISSUE THREAD

**Issue by elinazelentsova** [dbeaver/dbeaver#15256]
**System information:**
Windows 10 (64)
DBeaver CE version
21.3.2
Java Version 8 Update 321
Connection specification:
Database name and version:
**Snowflake** 
Driver name:
net.snowflake:snowflake-jdbc:RELEASE
mssql-jdbc-9.4.1.jre16.jar
Do you use tunnels or proxies (SSH, SOCKS, etc)?
No, I don't use it

I'm trying to connect to the Snowflake database. DBeaver offers to download and update the driver. I do it. Then he offers to do it again. By default, it offers to install the file version 3.13.6, but I tried to install both it and the latest version. I also tried to download the drivers manually and add them, but the error repeats. The Java version is the latest. I tried reinstalling Java, but the error persists.

![2](https://user-images.githubusercontent.com/93977965/150673003-a1bac11b-8843-4ad9-8998-7e7b4630bea8.PNG)
![3](https://user-images.githubusercontent.com/93977965/150673004-73046e08-0d5e-40ea-bc32-e89a0350873b.PNG)

**Comment by SubOptimal** [comment]
> mssql-jdbc-9.4.1.**jre16**.jar

This driver is for use with Java 16.

Could you try again with [mssql-jdbc-9.4.1.jre8.jar](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc/9.4.1.jre8)?

**Comment by SubOptimal** [comment]
> mssql-jdbc-9.4.1.**jre16**.jar

That's the driver for Java 16 runtime.

DBeaver Community Edition 21.3.2 (https://dbeaver.io/files/21.3.2/dbeaver-ce-21.3.2-win32.win32.x86_64.zip) is bundled with Java 11 runtime.

It might be worth trying again with [mssql-jdbc-9.4.1.jre8.jar](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc/9.4.1.jre11). (**edit:** only in case you run DBeaver not with the embedded Java runtime because you mention that you use Java 8)

**Comment by elinazelentsova** [comment]
I've tried with mssql-jdbc-9.4.1.jre8.jar . The error is the same. Also I tried other versions of dbeaver, but the error is the same.

**Comment by LonwoLonwo** [comment]
Hello @elinazelentsova 

The whole [error log](https://github.com/dbeaver/dbeaver/wiki/Log-files) will be beneficial.

And what is the purpose of `mssql-jdbc` driver? This is the driver for SQL Server.
It's ok to use only the` net.snowflake:snowflake-jdbc:RELEASE` driver for the Snowflake connection. Unnecessary libraries in the list of drivers libraries can lead to errors in connection.

**Comment by uslss** [comment]
There has been no update on the issue for a long time. if it is still actual - feel free to reopen it

**Comment by shihabmridha** [comment]
This happened to me due to the wrong `host` URL. Dbeaver expects the `host` to be in the following format:
```
accountId.region.cloud.snowflakecomputing.com

Example: accId.west-us-2.azure.snowflakecomputing.com
```

**Comment by LonwoLonwo** [comment]
Not sure about the error. 
I used something like

`accountId.region.cloud.snowflakecomputing.com/`

today, and I had another issue like "incorrect URL", but not like the main topic of this issue.
