### ISSUE TITLE
About setting custom workspace location configuration in config file availability.

### ISSUE THREAD

**Issue by Kambaa** [dbeaver/dbeaver#15251]
Hello, 

Instead of giving it as an argument of the dbeaver.exe, is there a possible way to set the [custom location](https://github.com/dbeaver/dbeaver/wiki/Workspace-Location#custom-location) setting in a configuration file?( in dbeaver.ini or configuration/configuration.ini) 

Installing and setting up an application is problem for me (You can imagine the cases, using work computers, a.d./exchange limitations/restrictions, disappearance of folders in %appdata% at regular intervals, in short, portable usage is more comfortable for me, portable'em all the way!)

Thank you.

**Comment by Matvey16** [comment]
@Kambaa Hello, thank you for a suggestion. Unfortunately the .ini file is read only after the workspace has already been initialized and that process is a part of eclipse platform, so we don't have means to change that.
