### ISSUE TITLE
Dbeaver does not save data. The attribute was changed but it hasn't associated unique key

### ISSUE THREAD

**Issue by dmitrygribenchuk** [dbeaver/dbeaver#15269]
#### System information: 
- Ubuntu 20.04.3 LTS
- DBeaver CE 21.3.3

#### Connection specification:
- Postgresql server 13.5 (Ubuntu 13.5-2.pgdg20.04+1)
- Local database

#### Describe the problem you're observing:

Hello. I'm creating a table with a few records like:

`CREATE TABLE admins (
        id         text primary key,
        active     bool default true
); `

When I try to change field active via DBeaver I'm getting error: "Attribute active was changed but it hasn't associated unique key
Attribute active was changed but it hasn't associated unique key" but via psql I can update this field without any errors and warnings.

![Selection_1701](https://user-images.githubusercontent.com/15670247/150757940-f2ab105d-9c0d-4f7f-8e2f-a558bcd23197.png)

**Comment by LonwoLonwo** [comment]
Hello @dmitrygribenchuk 

Unfortunately can't reproduce your issue.

![2022-01-24 14_24_52-DBeaver Ultimate 21 3 3 - _postgres_ Script-10](https://user-images.githubusercontent.com/45152336/150774621-1f5ad7df-211c-4289-a4c3-01a43fd5add1.png)

Did you create the "admins" table via UI and Navigator tree? Or do you execute this create statement in SQL Editor? Have you tried to refresh your table schema in the Database Navigator tree?

**Comment by dmitrygribenchuk** [comment]
`insert into admins (id, active) values ('220100', true);
update admins set active = false where id = '220100';
update admins set active = true where id = '220100';`

re-checked now, from text console I can update, but from UI - error still reproduces.

**Comment by dmitrygribenchuk** [comment]
I create a table via executing SQL from the editor.
I re-checked now, from the text console I can update, but from UI - the error still reproduces.

```
insert into admins (id, active) values ('220100', true); 

update admins set active = false where id = '220100'; 

update admins set active = true where id = '220100';
```

**Comment by LonwoLonwo** [comment]
Ok. And what about schema refresh? Or reconnect? Didn't help?

**Comment by dmitrygribenchuk** [comment]
Hmmm, I restarted the app and the error is gone
After that I dropped and recreated my admins table - error was gone.

**Comment by Seblor** [comment]
Happened to me just now and found this issue through Google, it was an issue of the schema not being synced. A simple F5 on the schema in the Database Navigator panel fixed it.

**Comment by homedirectory** [comment]
I have experienced the same issue in 25.2.1. Simply refreshing the schema, as suggested by @Seblor, did not help. I had to close the tab with the table and open it again.
