### ISSUE TITLE
[Autocompletion] Select issues

### ISSUE THREAD

**Issue by Destrolaric** [dbeaver/dbeaver#15267]
Part of #15103
1. Autocompletion now works in sql editor for select statements specifying current schema name in the form "**select * from current_schema.*** ", but if you do "**select * from other_schema.*** " it doesn't work even when you have the option to search in other schemas (whenever possible, because current schema has grants to do so).

**Comment by E1izabeth** [comment]
Seems it has already been fixed.

**Comment by Matvey16** [comment]
Verified
