### ISSUE TITLE
Autoselect Name field at opening of the Add New Column dialog window

### ISSUE THREAD

**Issue by donicom** [dbeaver/dbeaver#15279]
Would it be possible to auto select the Name field at opening of the Add New Column dialog window so it would be possible to write directly the name of the field instead of manually select the whole field or delete manually the the default text "Column1"?

**Comment by ShadelessFox** [comment]
Hello @donicom,

It seems like an excellent minor enhancement to have.

Thank you.

**Comment by ShadelessFox** [comment]
Fixed for new attribute and constraint creation dialogs.

**Comment by uslss** [comment]
verified
