### ISSUE TITLE
SQL Server: Table index DDL is empty

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#15270]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.3.2

#### Connection specification:
- Database name and version SQL Server
#### Steps to reproduce, if exist:
Open a table index DDL in the Metadata Editor

**Expected**: the DDL tab has content or doesn't exist
**Actual result**: the DDL tab is empty

**Comment by LonwoLonwo** [comment]
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/15270
