### ISSUE TITLE
Change Create/Browse buttons behavior for embedded databases connection creation

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#15271]
#### System information: 
- DBeaver version 21.3.3

#### Describe the problem you're observing:
The settings in connection creation for embedded databases are misleading. The `Create` button is almost always disabled, but new database can be created by entering a path to nonexistent database. We need to rethink how those two buttons work and make it more intuitive for users.

![dbeaver_66SJstmWZy](https://user-images.githubusercontent.com/82543000/150776154-0e127e32-456e-486e-b781-229a878b7a45.png)

**Comment by ShadelessFox** [comment]
Fixed in #15827
