### ISSUE TITLE
Missing quotes in PostgreSQL tables sections DDL

### ISSUE THREAD

**Issue by greenpeas** [dbeaver/dbeaver#15272]
Missing quotes in PostgreSQL tables sections DDL.
DBeaver 21.3.3, Windows 10

![image](https://user-images.githubusercontent.com/3856344/150783249-5215aa24-c59b-47ff-8618-10db310cec24.png)

**Comment by LonwoLonwo** [comment]
Thanks for the bug report!

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.3.4

**Comment by Matvey16** [comment]
Verified
