### ISSUE TITLE
Use infered word splitting to make names in camel case

### ISSUE THREAD

**Issue by PMLP-novo** [dbeaver/dbeaver#15274]
**Is your feature request related to a problem? Please describe.**
Many languages are using the camel case naming convention. The problem being that SQL is not case sensitive. So they is placed with the dilema of making there long names unreadable or to use snake case and be inconsistent.

**Describe the solution you'd like**
Users should be allowed an option to view names in camel case and then the camel case names should be created by a name infer algorithm, like the one described here https://stackoverflow.com/questions/8870261/how-to-split-text-without-spaces-into-list-of-words 
This would make it much easier to read.

**Comment by LonwoLonwo** [comment]
Hello @PMLP-novo 

Camel's case is cool. We totally agree.
But I do not quite understand what you offer. 
You can use camel's case in your tables names. Or for other objects.

You can enable the "Use case-sensitive names in DDL statements" setting in the Preferences, and the camel's case will be saved in quotes - no transformation into lower or upper case.

![2022-01-25 15_46_03-Preferences](https://user-images.githubusercontent.com/45152336/150979746-998a5ba2-b88c-408c-8b02-5c3fa86b4607.png)

**Comment by uslss** [comment]
There has been no update for a long time. If your issue isn't resolved - feel free to reopen this one with additional information

**Comment by jeffshumphreys** [comment]
I thought he meant "convert TheBigHouse to the_big_house", but it's hard to tell.  I wrote a similar converter in PowerShell to allow variables named "$HowManyRowsInserted" to be an output label "How many rows inserted               2,000", a humanizer.
