### ISSUE TITLE
SQL execution with Inline double-dash comment

### ISSUE THREAD

**Issue by WildLlama** [dbeaver/dbeaver#15282]
DBeaver 21.3.3, Windows 10

Working with SQLServer database, the execution of a query with a double-dash comment results in an execution error, while with MySQL, using the same query, the execution ends correclty
By opening the executed query tab, it looks like that for the SQLServer version the new lines are not kept

**MySQL**
![image](https://user-images.githubusercontent.com/61920578/150960277-1d291d71-c341-4308-9bdc-364e61441469.png)

**SQLServer**
![image](https://user-images.githubusercontent.com/61920578/150960110-2e374e61-66ee-4b90-a17f-55110193c8f0.png)

**Comment by uslss** [comment]
@WildLlama please, provide more info accordingly to the issue template

**Comment by WildLlama** [comment]
@uslss I've updated the bug report, I've released without details by mistake

**Comment by LonwoLonwo** [comment]
Hello @WildLlama 
Can you please execute your query in the SQL Server without a double-dash comment? Because I think that the main reason for this issue is the incorrect statement. 
Some queries can be executed in MySQL and can not be executed in SQL Server. These are different databases.

**Comment by WildLlama** [comment]
Hello @LonwoLonwo,
Here is the correct execution without the comment for SQLServer
![image](https://user-images.githubusercontent.com/61920578/150982618-36eba405-f636-4f30-95bb-389669abc45f.png)

**Comment by vmoraru** [comment]
The issue is the way DBeaver interprets the query, it executes it inline so everything after that is commented. As a temporary workaround, you could surround your commented fields with /* */ and it should work.

For example:
![image](https://user-images.githubusercontent.com/6881881/152492577-596b7fb4-a29f-46f8-ab17-3583db1a34c0.png)

The error text would be misleading, saying that "field" is missing in the group by clause.

**Comment by LonwoLonwo** [comment]
![2022-02-04 13_51_08-Event](https://user-images.githubusercontent.com/45152336/152516671-803a4d05-b8cb-4863-b082-48c9935f1606.png)

I can't reproduce again, sorry.

Can you please take a screenshot of your preferences? Preferences -> Editors -> SQL Editor -> "SQL Processing" and "Formatting" tabs.

**Comment by vmoraru** [comment]
Of course, here is "SQL Processing":
![image](https://user-images.githubusercontent.com/6881881/152526624-c7303bac-c557-4d19-8e94-5ebc4417f7a1.png)

And "Formatting":
![image](https://user-images.githubusercontent.com/6881881/152526678-45d4c30e-aef3-4d7c-a4fc-89eb05831b79.png)

I don't think it is an editor issue, it must be in the interpreter somewhere, because if I try to format the query, it will detect and format properly. If it helps, version and build number are 21.3.3.202201221033.

**Comment by LonwoLonwo** [comment]
Maybe you can take a video of the error? The execution process in SQL Editor and result in the [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager)? 
It will be beneficial.

**Comment by WildLlama** [comment]
@LonwoLonwo I think that I've found the issue, or at least an hint to better identify it
I've tried to replicate the error with query provided by @vmoraru but without success, so I've enabled the hidden characters (Spaces, Line Feed, etc.) and I've found this 
![image](https://user-images.githubusercontent.com/61920578/152551313-d28ca7ea-f6ef-48a3-949a-8f4b9845a843.png)

The first query is hand-written and it works fine, the second one is copied over from Visual Studio and misses the Line Feed charcter, and, by not creating a new line,  comments out everything after the "--"
![image](https://user-images.githubusercontent.com/61920578/152551588-e50434d2-ae74-4118-b45f-218c940e44f7.png)

**Comment by vmoraru** [comment]
How do I enable displaying special characters?
I did just try it in a new window and it worked, but in the old tab it fails, both queries were typed and not copied from anywhere.
![DBeaver_exeuction](https://user-images.githubusercontent.com/6881881/152751765-f398937e-e7e3-4969-b54f-ebdf7ab5290a.gif)

**Comment by WildLlama** [comment]
@vmoraru They can be enable here
![image](https://user-images.githubusercontent.com/61920578/152759868-f76f4223-2cdb-4b48-8fe0-0286c13e08e4.png)

**Comment by vmoraru** [comment]
Thanks! 
These are the characters in the old tab, the one that fails the query:
![image](https://user-images.githubusercontent.com/6881881/152826314-88376668-82be-4df5-8db4-327d896ce0ce.png)

This is in the new tab, the one that succeeds:
![image](https://user-images.githubusercontent.com/6881881/152826405-bdc3b2eb-f00b-48b6-a504-507d679c35d1.png)

They were both hand written, the first is a tab in which I keep writing queries for a while now, the second was created after the most recent update (today).

_Edit:_ I am not sure what is happening, checked other older tabs and they seem to have the same end character as the second screenshot and commenting a line works fine there, even if I copy the query from the "broken" tab. So for anyone having this issues, you could first simply try to create a new SQL window and edit there.

**Comment by WildLlama** [comment]
What I've observed is that when you a tab is "broken" it keeps the missing return character, but when you create a new tab, even if you copy a query from a "broken" tab it uses the correct OS ending line delimites

https://user-images.githubusercontent.com/61920578/153456057-7cbd5a01-4913-473b-a1d5-f39e29911afa.mp4

**Comment by LonwoLonwo** [comment]
Maybe this tip about Preferences can be beneficial? https://github.com/dbeaver/dbeaver/issues/11278

**Comment by vmoraru** [comment]
> Maybe this tip about Preferences can be beneficial? #11278

Does look like a useful tip, I do, however, have it checked and I did type the query, did not copy it from anywhere. Not sure how that tab got "broken", but, as @WildLlama already mentioned, copied queries from one tab to the other either add or remove the LF character depending on which way you copy, so it still remains broken in the old tab. 

I did manage to "fix" that tab though by editing it in Notepad++ and replacing all \r with \r\n after which copying, typing and executing anything works as expected.

**Comment by Matvey16** [comment]
I was not able to reproduce it by copying text from different other editors and even other OSs. If you happen to get this bug with missing line feeds again, it would be great if you could save this script and share it so I can open it on my machine and maybe find a way to reproduce this.

**Comment by WildLlama** [comment]
@Matvey16 If this error happens to me again, I'll share the script file to better analyze it.
As stated in a comment before, I was able to generate this bug by using the souce code extraction of the queries from Visual Studio (the version I work with is the 2012)
Is it possible that, by running the extraction utility, it defaults to the Linux end-of-line syntax on the script file

**Comment by WildLlama** [comment]
@Matvey16 I've managed to re-create the issue using the latest DBeaver update (v. 22.1.4.202208051447) 
In the zip attached you can find the script with the wrong ending line characters.

As stated before, it was achieved by coping the query from VS2012 to a new script file.
What I've copied are these line of code, starting from ```"SELECT``` because otherwise the code extraction doesn't work
```
            StrSql = "SELECT * FROM dt_maga_list WHERE (STATO IS NULL OR STATO='') AND (DITTA IS NULL OR DITTA='' OR DITTA='" & Login.Azienda & "')"
            StrSql &= " AND LISTAORIGINE = " & Chiave
            StrSql &= " ORDER BY DESCRIZIONE,NUMERO"
```

[Script-443.zip](https://github.com/dbeaver/dbeaver/files/9281924/Script-443.zip)

**Comment by Matvey16** [comment]
@WildLlama Thank you for this sample. There indeed is a bug in code extraction. We will see what can be done
