### ISSUE TITLE
Version 21.3.3.202201221033 don't show selected database in toolbar "Active Datasource"

### ISSUE THREAD

**Issue by mauriliolima** [dbeaver/dbeaver#15302]
#### System information: 
- Operating system (distribution) and version
Microsoft Windows [versão 10.0.19044.1466]
- DBeaver version
Version 21.3.3.202201221033
- Additional extensions
none

#### Connection specification:
- Database name and version
Oracle Oracle Database 19c EE Extreme Perf Release 19.0.0.0.0 - Production

- Driver name
Oracle JDBC driver 12.2.0.1.0

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
NONE

#### Describe the problem you're observing:
After install new version 21.3.3.202201221033, I ran the app and tryed select database, as always do, but this time, the combobox doesn't show active datasource, like prior versions. Restart app, same issue. 
although combobox doesn't show active database is use, queries run normaly, what sugests just an exibition problem. It just show <N/A>

#### Steps to reproduce, if exist:
just open the app and try select datasource in toolbar

**Comment by mauriliolima** [comment]
Additionally, log doesn't show any error, warning, nothing.

**Comment by uslss** [comment]
@mauriliolima unfortunately, cannot reproduce it.
Is the issue reproducible both for data and SQL editor? screenshots or video with the issue also could be very useful
![image](https://user-images.githubusercontent.com/31996417/151796935-7d2f8491-8d56-47c0-a03c-0d9bf5942904.png)

**Comment by uslss** [comment]
There has been no update on the issue for a long time. if it is still actual - feel free to reopen it
