### ISSUE TITLE
AutoUpdate feature inconvience

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#15303]
Hi!
When I am under Ubuntu and I set up snap version of DBeaver and there becomes newer version - DBE show the dialog, saying "there is newer version etc...". But! Is it correct that I should not go to download and install freshest deb? Instead I am to wait when snap will be updated in appropriated way too, I think (doing sudo snap refresh - manually or automatically).
Could we, somehow, check that situations and not recommend to update if we are under the snap (or make some notices about it) ?

**Comment by uslss** [comment]
thanks for the suggestion
closed as a duplicate of #12597
