### ISSUE TITLE
Newest Results Tab Not Receiving Focus

### ISSUE THREAD

**Issue by Xylandor** [dbeaver/dbeaver#15301]
#### System information: 
- OS:  MacOS Big Sur v11.4
- DBeaver version:  21.3.3.202201221033
- Additional extensions:  None

#### Connection specification:
- Local installation of MariaDb
- Driver name: MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Since the release of the DBeaver version 21.3.3.202201221033, when executing SQL in a new results tab, instead of the new tab keeping focus, the previous tab that was manually selected gets the focus returned to it. What I mean by "manually selected" is you have to literally click on a result tab. If you just execute a query in a new tab several times without ever manually selecting a results tab, the focusing works as expected, with the newest tab receiving focus. But once you select a tab, that tab will get focus set back to it and instead of the newest tab that is created. The video provided will demonstrate the behavior.

#### Steps to reproduce, if exist:

1. Ensure all result tabs are closed.
2. Execute a query in a new tab two or more times. (Eg. `SELECT UTC_TIMESTAMP();` )
3. Notice how the newest tab gets focus, which is the desired result. Now click any results tab.
4. Execute the query again in a new tab and notice that it flashes focus on the new tab, but then quickly resets the focus on the tab you manually clicked on earlier.

Here's the video to demonstrate the problem:

https://user-images.githubusercontent.com/24617679/151189559-4c941daf-bfe4-4f04-aa1a-087dc44e4904.mov

#### Include any warning/errors/backtraces from the logs
No errors produced.

**Comment by CathyBreslow** [comment]
I see this behavior too!

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
verified
