### ISSUE TITLE
clarify what true looks like in output

### ISSUE THREAD

**Issue by rdp** [dbeaver/dbeaver#15304]
**Is your feature request related to a problem? Please describe.**

DBeaver display of boolean is slightly confusing.

**Describe the solution you'd like**

If I have a boolean column, I'd like it more obvious.

ex: postgres

```
select true;
```

It shows a [v] for the output pane.  
A "v"?  What type is that?  What am I seeing?

Suggestion/feature request for UI:

[true] and [false] or possibly show a "real-er" checkmark...

Cheers!

**Comment by scmehle** [comment]
This feature does exist, but you have to dig through the preferences a bit.

Click on the "Window" menu and choose "Preferences". Navigate to the editors section, and there is a section to set how Booleans display. Screenshot attached for reference.
![image](https://user-images.githubusercontent.com/9370225/151252583-30d2579a-2f03-4a0a-a1ac-064a72d0fd5a.png)

**Comment by rdp** [comment]
That's interesting, mine on OS X just shows up as a "v" like [v]"...

**Comment by LonwoLonwo** [comment]
And you can change it in the Preferences.

![2022-01-27 11_07_10-Preferences](https://user-images.githubusercontent.com/45152336/151317222-0a7c9915-5b92-4741-addf-d6a3d9ff9c2a.png)
