### ISSUE TITLE
Automatically browse default schema in the tree view when connecting to database

### ISSUE THREAD

**Issue by fikusz01** [dbeaver/dbeaver#15313]
It would be very nice, if the program could automatically jump/browse to the given default schema in the left hand side tree view.
It could save so much time when working with multiple databases and connections at the same time, and have to click-click all the way down just to view data in a table.

The solution could be a new checkbox in connection settings: "automatically open schema in navigation tree when connecting"
Or a hotkey or toolbar button would be nice for this feature.

**Comment by uslss** [comment]
@fikusz01 you could use Link with editor button in DB Navigator
![image](https://user-images.githubusercontent.com/31996417/151343065-d3dbc379-37d0-42fb-b68e-af28fc5d1806.png)
does it fit you?

**Comment by fikusz01** [comment]
Thanks! It's a cool feature if you already have opened something and want to jump to the db object. But my idea is about the case when you are just connecting to a db in the Database Navigator panel.

**Comment by uslss** [comment]
did you try to enable Expand navigator tree on connect option in preferences?
![image](https://user-images.githubusercontent.com/31996417/151349496-ebf6e2fe-4b3c-44fd-bd76-2a1919fb04ed.png)

**Comment by fikusz01** [comment]
@uslss thanks for the quick reply! Didn't notice this settings, thanks! It's almost what I imagined. This feature could be enhanced to handle the given default schema too (attached screenshot). Now it's not opening schema, only goes for database - witch is very cool, half the clicks are saved this way.

![image](https://user-images.githubusercontent.com/10757989/151353146-e8704a5b-cd7f-422b-a85a-9392be45f99e.png)

**Comment by Skydiveroid** [comment]
Thank you for the idea.

**Comment by ShadelessFox** [comment]
Implemented.

**Comment by fikusz01** [comment]
Cheers! Thank you very much!

**Comment by uslss** [comment]
verified

**Comment by abhi40308** [comment]
@ShadelessFox  @uslss @Skydiveroid  hi, new user here! can you please lmk how to do this in cloudbeaver, i am not able to figure out
