### ISSUE TITLE
HANA: CREATE PROCEDURE syntax error on DBeaver, works on HANA Studio

### ISSUE THREAD

**Issue by jsveiga-sps** [dbeaver/dbeaver#15315]
#### System information: 
- Operating system: Windows 10
- DBeaver version 21.3.3

#### Connection specification:
- Database name and version : HANA 2.0
- Driver name: SAP / HANA ; com.sap.db.jdbc.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Creating a procedure in DBeaver with this:
```
CREATE PROCEDURE TESTPROC
AS
TESTVAR INT;
BEGIN
TESTVAR = 1;
SELECT :TESTVAR FROM DUMMY;
END;
```

Results in 
```
Error occurred during SQL script execution

Reason:
SQL Error [257] [HY000]: SAP DBTech JDBC: [257] (at 40): sql syntax error: line 3 col 9 (at pos 40)
```

But the same works in HANA Studio
```
Statement 'CREATE PROCEDURE TESTPROC AS TESTVAR INT; BEGIN TESTVAR = 1; SELECT :TESTVAR FROM DUMMY; END;' 
successfully executed in 24 ms 926 µs  (server processing time: 6 ms 109 µs) - Rows Affected: 0 
```

Maybe DBeaver is using an older version of SAP JDBC?

I noticed that SAP's own documentation of CREATE PROCEDURE does not offer the option of that syntax for variable declaration (between AS and BEGIN, without DECLARE), but it is extensively used by SAP itself (for example in BusinessOne Transaction Notifications), which makes it often necessary to edit them. Then we have to go back to HANA Studio for that.

#### Steps to reproduce, if exist:

Create a procedure in DBeaver with this:
```
CREATE PROCEDURE TESTPROC
AS
TESTVAR INT;
BEGIN
TESTVAR = 1;
SELECT :TESTVAR FROM DUMMY;
END;
```

#### Include any warning/errors/backtraces from the logs
```
Error occurred during SQL script execution

Reason:
SQL Error [257] [HY000]: SAP DBTech JDBC: [257] (at 40): sql syntax error: line 3 col 9 (at pos 40)
```

**Comment by kai-morich** [comment]
Dbeaver end-of-statement detection stumbles over the first ;
As workaround you can select the full procedure text befor execution, 

But declaring variables between AS and BEGIN is not official syntax, you you better use this syntax, where the workaround is not required:

    CREATE PROCEDURE TESTPROC AS
    BEGIN
      DECLARE TESTVAR INT;
      TESTVAR = 1;
      SELECT :TESTVAR FROM DUMMY;
    END;

**Comment by jsveiga-sps** [comment]
Thank you!
Selecting all and executing as a statement (instead of as a script) works!
It would be nice though if DBeaver accepted it, since SAP themselves use it - but I agree, the HANA SQL documentation does not mention it.
DBeaver is a wonderful tool by the way - thanks!
