### ISSUE TITLE
Code Completion is NOT working in Eclipse IDE with DBeaver Plugin for Oracle?

### ISSUE THREAD

**Issue by aluva** [dbeaver/dbeaver#15327]
I am using **_Eclipse IDE_** (2021-12 for Enterprise Java & Web Development) with **_DBeaver_** Perspectives (Plugin: 21.3.3) for **_Oracle_** (21c Xe Full) in **_macOS Catalina_**:

Automatic (without using Ctrl+SPC or Ctrl+Shift+SPC) **Code Completion** is **not** working for SQL and PL/SQL?

(_**Note**: I added '.@(abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ' to Auto Activation Triggers for SQL, but still Code Auto Completion is NOT working_)

**Comment by uslss** [comment]
@aluva could you check if there is something in the logs?

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still present, feel free to reopen it.
