### ISSUE TITLE
DBeaver Voluntary Product Accessibility Template (VPAT)

### ISSUE THREAD

**Issue by ben-mur** [dbeaver/dbeaver#15326]
US Government Agencies are requesting that software and tools, like DBeaver, complete and publish a Voluntary Product Accessibility Template (VPAT). The presence of a VPAT for a tool, like DBeaver, makes it easier for the tool to be approved for use and distributed internally. 

More info for regarding the Voluntary Product Accessibility Template (VPAT) here: https://www.section508.gov/sell/vpat/

My ask/idea is that the DBeaver community produce a Voluntary Product Accessibility Template (VPAT) and publish it!

**Comment by uslss** [comment]
Thanks for the suggestion.
It has already been done for Enterprise products. And it is not planned for the Community edition.
