### ISSUE TITLE
new installation - can not open firebird connections

### ISSUE THREAD

**Issue by rdenniss** [dbeaver/dbeaver#15330]
#### System information: 
- win7sp1  clean install (after vs2019 so it has .net 4.8)
- DBeaver Community 21 (.2.0 and .3.3)
- Additional extensions

#### Connection specification:
- Firebird 1.5.6
- that is the problem
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  nope, local file

#### Describe the problem you're observing:
Adding connection to Firebird database
Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

#### Steps to reproduce, if exist:
adding new FB connection

Yeah, super informative messages for a non java person,
don't even know where to begin
 - googling problem (based on message keywords) all sorts of lovely "copy this from that java and do blah blah"

Hey I know not many people using firebird, particularly older versions, but:
used to be simple, dbeaver would download the javas or whatever but now it just throws up a mess of unintelligible (basically useless) messages that provide absolutely no use as to what to do.

as a side note on another (older installation) seems every week it announces a new version
please slow down releases, leave us a bit of time to actually get work done instead of doing and waiting on updates.
it's not a race to see who can update faster than microsoft, time to be rational.

**Comment by uslss** [comment]
@rdenniss Hi. Please refer to this [article](https://github.com/dbeaver/dbeaver/wiki/Importing-CA-Certificates-into-DBeaver). Do the actions described there help?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. if it is still actual - feel free to reopen it
