### ISSUE TITLE
Table Truncation Throws Exception

### ISSUE THREAD

**Issue by teamayu** [dbeaver/dbeaver#15335]
Windows 11, 64 Bit
Maria DB: 10.6.5
DBeaver: 21.3.3

If I right click a database table select 'Tools > Truncate', on 'Proceed' I get the following:

![31-01-2022_174923](https://user-images.githubusercontent.com/10624092/151772139-86599975-949b-4823-95fe-c739c95c38f2.png)

It was working ok before. Thank you.

**Comment by LonwoLonwo** [comment]
Hello @teamayu 

Did you click on "Proceed" on the first step:

![2022-01-31 13_05_27-DBeaver Ultimate 21 3 3 - newtable](https://user-images.githubusercontent.com/45152336/151774705-829ae694-b713-4cdb-af0f-69622fb5bbb2.png)

Or on the second?

![2022-01-31 13_06_19-DBeaver Ultimate 21 3 3 - newtable](https://user-images.githubusercontent.com/45152336/151774719-fdd77bd9-c74c-49bb-a7b1-2820d6124dc5.png)

I can reproduce only for the first case.

**Comment by teamayu** [comment]
Sorry, yes, just on the first.

**Comment by LonwoLonwo** [comment]
Ok, thanks for the bug report.
If you click on "Next" on the first page and then on "Procced," - it will work.
But we must fix the NPE bug, of course.

**Comment by teamayu** [comment]
Great, thank you. And you are welcome about the report. Your software is really amazing.

**Comment by uslss** [comment]
verified
