### ISSUE TITLE
Skip TLS verification

### ISSUE THREAD

**Issue by ValentinKaisermayer** [dbeaver/dbeaver#15338]
I would like to connect to an InfluxDB but it has no valid certificate. In Grafana I simply enabled the option "Skip TLS verification". How would this be possible with DBeaver?

**Comment by ValentinKaisermayer** [comment]
Sry, to post this here but I did not find a forum or something where I could ask.

**Comment by Skydiveroid** [comment]
Thank you for the idea.

**Comment by Matvey16** [comment]
Host and db fields are misplaced

![image](https://user-images.githubusercontent.com/82543000/162966908-bceeecaf-0eaf-4ceb-906d-c19c8f3b6ef7.png)

**Comment by Matvey16** [comment]
Verified
