### ISSUE TITLE
Boolean icons are not grayscaled when control is disabled

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#15346]
When booleans are set to be displayed as icons, in some controls they are not grayscaled when disabled, which looks unnatural:

![image](https://user-images.githubusercontent.com/35821147/151948896-e9a5f3e2-5b0b-47f7-803b-893bea07fb1b.png)

**Comment by ShadelessFox** [comment]
Fixed. Can be seen in #11090

**Comment by uslss** [comment]
verified
