### ISSUE TITLE
Newly created view source switch to Not a view until reconnect

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#15345]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.3.3

#### Connection specification:
- Database name and version Redshift

#### Describe the problem you're observing:
Newly created view source switch to Not a view until reconnect
![image](https://user-images.githubusercontent.com/31996417/151944104-c70ba7b9-37c7-4ced-ae1d-e6b5b753a394.png)

#### Steps to reproduce, if exist:
1. Create view via UI (e.g. Select 1 as a)
2. Save it

**Actual result**
View source switch from

```sql
CREATE OR REPLACE VIEW public.newview_4
AS select 1 as a;
```

to 

```sql
CREATE OR REPLACE VIEW public.newview_4
AS Not a view;
```

Incorrect DDL is shown until reconnect

Log:
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Feb 01 12:35:19 MSK 2022
Can't make object copy: src class org.jkiss.dbeaver.ext.postgresql.model.impls.redshift.RedshiftView' != dest class 'org.jkiss.dbeaver.ext.postgresql.model.PostgreView'
```

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
