### ISSUE TITLE
BigQuery: after login stuck at "Extract Catalogs"

### ISSUE THREAD

**Issue by giordyb** [dbeaver/dbeaver#15354]
#### System information: 
- Operating system (distribution) and version
MacOS 11.6.1 on Intel
DBeaver version
- 21.3.3.202201221033

#### Connection specification:
- Database name and version
BigQuery
- Driver name
BigQuery
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
I can connect fine to BigQuery using a service account, when I try to login with the "User-based" authentication I get past the  the Authorization code request and I am able to receive a code and paste it into the box but then it gets stuck at "Extract Catalogs"

#### Include any warning/errors/backtraces from the logs
in the logs i get the following:

2022-02-01 17:44:52.879 - Connect with 'connectionname (google_bigquery_jdbc_simba-17eb6288e1b-1cf0070ea012da80)
2022-02-01 17:44:52.879 - Execution context opened (connectionname; Main; 3)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-02-01 17:45:17.374 - Error setting client application name: [Simba][JDSI](20100) Property ApplicationName not supported.
2022-02-01 17:45:17.375 - Execution context opened (connectionname; Metadata; 4)
2022-02-01 17:45:43.683 - Error setting client application name: [Simba][JDSI](20100) Property ApplicationName not supported.

**Comment by Matvey16** [comment]
@giordyb Can you check if the user that you are using to connect has needed permissions to use extract catalogs query?

**Comment by giordyb** [comment]
Hi @Matvey16 , the service account that I am using to connect via the "service-based" oauth type has the "BigQuery Data Owner" and "BigQuery Metadata Viewer" role at the Dataset level and works fine.
The user that I am using to connect via the "user-based" oauth type is mine and have both the  "BigQuery Editor" role at the project level and the "BigQuery Owner" role at the Dataset Level (I've created that dataset).

So I don't think it's a permission issue.

would the error `"Error setting client application name: [Simba][JDSI](https://github.com/dbeaver/dbeaver/issues/20100) Property ApplicationName not supported."` that I see in the logs would have anything to do with it?

**Comment by flambchap** [comment]
It seems like this error has nothing to do with this issue. Could you please make a screenshot of the Query Manager when DBeaver is stuck at "Extract Catalogs"?

**Comment by giordyb** [comment]
@akilovich 
here you go, this happens after I go through the oauth authentication and stays that way indefinitely.


<img width="500" alt="DBeaver_21_3_3_and_Success_code_4_1AX4XfWhyEa8Z4dkPomzby_rzup5UuzBSpoGJC3LjwZ3m1Hyb0dejAnnxVMY_scope_https___www_googleapis_com_auth_bigquery" src="https://user-images.githubusercontent.com/13320961/155326599-811befcf-1a0d-4948-8362-fd9824d1bcc4.png">

**Comment by Matvey16** [comment]
@giordyb I think he meant this query manager to look at what query this task is stuck
![image](https://user-images.githubusercontent.com/82543000/158135319-134f5613-c736-4347-ba0e-4ff0dd98257d.png)

**Comment by giordyb** [comment]
@Matvey16 @akilovich  I'm not getting anything in query manager
<img width="1915" alt="Screenshot 2022-03-14 at 09 48 28" src="https://user-images.githubusercontent.com/13320961/158136922-d858120a-d790-4225-bc6a-6b714ed61a39.png">
.

**Comment by Matvey16** [comment]
@giordyb Please turn all types of queries on in query manager settings. Maybe you have metadata queries disabled
![dbeaver_ymf4wUjJI7](https://user-images.githubusercontent.com/82543000/159691868-aa6c19df-8956-4ee9-a630-5e2d0725f448.png)
![dbeaver_njXkpxPs12](https://user-images.githubusercontent.com/82543000/159691877-14ea1342-9b8a-4292-b0a3-7b71e43c7aa9.png)

**Comment by giordyb** [comment]
Thank you @Matvey16 , I've configured the filter as you suggested, here are the results:

<img width="1821" alt="DBeaver_21_3_3" src="https://user-images.githubusercontent.com/13320961/160108232-bb485f8d-b41c-4636-b113-412ea98d89d8.png">
.

**Comment by flambchap** [comment]
It seems like the database driver executes a non-optimal query. I am curious if we can substitute it with something better.

**Comment by flambchap** [comment]
@Matvey16 Have you managed to reproduce the issue? I think we need to schedule this ticket in some milestone if you know how to replicate the issue.

**Comment by LonwoLonwo** [comment]
Could you please retry with the latest driver and DBeaver version? 
You can download driver here: https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.3.3.1004.zip

Then you need to open your connections settings.
Click on the "Driver settings"
Choose "Libraries"
Delete old jar file
Download a new jar file
Reconnect

![2023-05-17 12_15_09-Window](https://github.com/dbeaver/dbeaver/assets/45152336/a423c921-3bcb-44b4-8ecc-d4052b13f994)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
