### ISSUE TITLE
Incorrect autocomplete for variables in data export file name

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#15363]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.3.4

#### Describe the problem you're observing:
Autocomplete in file name field of data transfer wizard doesn't replace already typed symbols, but instead appends the whole variable to them.

#### Steps to reproduce, if exist:
1. Open Data export wizard and proceed output settings
2. Start typing a variable name e.g. `${ti`
3. Select the proposed variable and press enter

**Expected:** The variable is pasted instead of already typed part of it's name
**Actual:** The variable is appended after already typed symbols

![dbeaver_ZS518fSPFV](https://user-images.githubusercontent.com/82543000/152122042-3921823c-4a41-4eb3-b9c4-475d761a4a09.gif)

**Comment by ShadelessFox** [comment]
Would be cool to also test: #11508

**Comment by Matvey16** [comment]
Verified
