### ISSUE TITLE
ORACLE: request INDEX and UNIQUE and FOREIGN KEY

### ISSUE THREAD

**Issue by amancini** [dbeaver/dbeaver#1536]
Hi,

In the list of objects you can insert INDEX UNIQUE and FOREIGN KEY for ORACLE dabase

Thanks for your work

**Comment by uslss** [comment]
is it still actual?
could you clarify your issue?

**Comment by uslss** [comment]
there is no update for a long time.
ticket closed.
if issue still actual for you - feel free to reopen the ticket
