### ISSUE TITLE
There is a problem that the comment column cannot be backed up.

### ISSUE THREAD

**Issue by homerose** [dbeaver/dbeaver#15373]
#### System information: 
- Operating system (distribution) and version 
- DBeaver version : 21.3.3
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I copied and pasted the working database.
However, the column 'comment' are blank.
This bug exists when backing up and restoring.
please fix it

**Comment by uslss** [comment]
@homerose what database do you use?

**Comment by homerose** [comment]
This is mariadb-10.5.9-winx64.

**Comment by uslss** [comment]
@homerose Unfortunately, cannot reproduce. Did you try to check Additional Comments option?
![image](https://user-images.githubusercontent.com/31996417/152312810-83945567-d992-4415-9987-4adc4e045758.png)

**Comment by uslss** [comment]
There has been no update on the issue for a long time. if it is still actual - feel free to reopen it
