### ISSUE TITLE
New Results Tab Not Selected Automatically

### ISSUE THREAD

**Issue by ksteckert** [dbeaver/dbeaver#15371]
#### System information: 
- Windows 11 (21H2 22000.438)
- 21.3.3.202201221033

#### Connection specification:
- PostgreSQL v12
- PostgreSQL JDBC Driver

#### Describe the problem you're observing:
When I run a query using CTRL+\ (execute in new tab), a new tab is created which contains the results.  The issue is I have to manually switch to this new tab.  My computer recently crashed and I had to reinstall DBeaver from scratch, and on my prior installation, the new results tab was automatically selected.  I have looked through the settings to see if this a feature that can be disabled.  I have also read the instructions/wiki and searched the web extensively about this issue but I haven't been able to find any related results.  I believe it is a bug, and it may only be affecting new/fresh installations, and it may possibly have something to do with Windows 11 (I was previously on Win10 on the old installation where I didn't have this issue).

#### Steps to reproduce, if exist:
1. run any query so you have a results tab open
1. run any any query so it executes in a new tab (choose menu option, click icon, or press CTRL+\)
3. the new tab is created, but you are left looking at an old results tab from a different query/resultset

**Comment by E1izabeth** [comment]
Hi, @ksteckert ! Thank you for the report!
This bug was already reported in https://github.com/dbeaver/dbeaver/issues/15301. It was fixed and will work in DBeaver 21.3.4.

**Comment by ksteckert** [comment]
Excellent, thanks.  I searched the issues but I didn't find that one, thanks, I look forward to the next release!
