### ISSUE TITLE
Uncommenting Multiple Lines Causes Highlighted Lines to Switch Lines

### ISSUE THREAD

**Issue by Xylandor** [dbeaver/dbeaver#15377]
#### System information: 
- OS:  MacOS Big Sur v11.4
- DBeaver version:  21.3.3.202201221033
- Additional extensions:  None

#### Connection specification:
- Local installation of MariaDb
- Driver name: MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Since the release of version 21.3.3.202201221033, uncommenting multiple lines in the script editor auto-selects the lines below the original selected lines. Selecting just one line to comment works as expected, but when involving two or more lines, this is where the problem occurs. Best to explain this behavior through the attached video. I'm using the hotkeys `CONTROL+/ `to do the line comment/uncomment.

https://user-images.githubusercontent.com/24617679/152363859-cda95298-0b07-4a3a-9832-b2091c2e653a.mov

#### Steps to reproduce, if exist:
1. Create a multiple line script of code or whatever.
2. Select just one line of code and comment it out using hotkey.
3. Uncomment it with the same hotkey and the same line remains highlighted, which is expected. 
4. Now highlight multiple lines (two or more) and comment them out.
5. Uncomment them and the highlighted area now moves downward the same number of lines that you had originally selected. 

The expected behavior is for the same lines you had highlighted before performing the uncomment action, remain highlighted after uncommenting.

#### Include any warning/errors/backtraces from the logs
No errors.

**Comment by uslss** [comment]
thanks for the report

**Comment by Xylandor** [comment]
I can confirm that this has now been fixed in version 22.0.4.202205011839. Thank you for fixing this.

**Comment by E1izabeth** [comment]
Hi, @Xylandor! Thank you for informing us. I'll close this issue as it's not reproducible anymore.
