### ISSUE TITLE
Add Astra DB to list of driver configurations

### ISSUE THREAD

**Issue by melienherrera** [dbeaver/dbeaver#15372]
**Is your feature request related to a problem? Please describe.**
Wanted to add Astra DB as one of the options of driver configurations built into DBeaver.

**Describe the solution you'd like**
Below is the driver description for Astra DB. 

**DRIVER DESCRIPTION:**
- Driver Name: `Astra DB`
- Driver Type: `Generic`
- Class Name: `com.simba.cassandra.jdbc42.Driver`
  - Library:   [SimbaCassandraJDBC42-2.0.12.1013.zip](https://github.com/dbeaver/dbeaver/files/7770786/SimbaCassandraJDBC42-2.0.12.1013.zip)

**URL TEMPLATE:**

`jdbc:cassandra://;AuthMech=2;TunableConsistency=6;SecureConnectionBundlePath=/path/to/secure-connect-bundle.zip`
Note: User has to specify the exact path to their secure connect bundle. \

Goal is to be added on this screen:
![Screen Shot 2022-02-02 at 9 20 02 AM](https://user-images.githubusercontent.com/85907755/152204321-2198dfb3-1078-413f-83f3-b23b617423b4.png)

Note: Came from issue #14891 and #15006

**Comment by Destrolaric** [comment]
@melienherrera Hi, It's better to reopen the previous issue.  I will reopen the last issue and close this one.
