### ISSUE TITLE
Update H2GIS to 2.0.0

### ISSUE THREAD

**Issue by ebocher** [dbeaver/dbeaver#15376]
H2GIS 2.0.0 is out on Maven Central.
We have updated it on your plugin repo https://github.com/orbisgis/orbisrcp/tree/master/plugins/org.orbisgis.h2gis
But we have an issue to detect a Geometry data type.
DBeaver set the type name from a plugin.xml file, here https://github.com/orbisgis/orbisrcp/tree/master/plugins/org.orbisgis.h2gis
Since H2 2.X version the string type representation for a geometry has changed. See my issue to the H2 community https://github.com/h2database/h2database/issues/3419
Is there a way to set the type name to DBeaver from code and not from a static value in a file ?
Best regards

**Comment by ShadelessFox** [comment]
Hello @ebocher,

If I understand you correctly, you can use `<type name="*"/>` instead of specifying a concrete type name.
