### ISSUE TITLE
Firebird Computed Columns

### ISSUE THREAD

**Issue by johntom** [dbeaver/dbeaver#1538]
Hi,
First thanks for the first product that I've tried where I've succesfully converted a Firebird 2.X charset from none to utf8! That is no small accomplishment.  At any rate I think there should be an option to exclude computed columns on export and the import will fail for readonly coulmns.
Thanks again as I dreaded the thought of writiing an app to convert all non utf8 characters wherever they might live in the database.
John

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer. Is it still actual for you? Do you mean opportunity including/excluding generated columns? It is possible to do in Export as SQL 
![dbeaver_GK9lgd5Rcw](https://user-images.githubusercontent.com/51405061/89403014-60223000-d720-11ea-8e80-3a1ea2be783b.png)
Or please give me more detailed description what you want to see.

**Comment by uslss** [comment]
seems this issue is obsolete.
If it is still actual for you - feel free to reopen it with an additional info
