### ISSUE TITLE
filtering result set in grid by unnamed column fails / and there is an inefficient subquery

### ISSUE THREAD

**Issue by igorzhilin** [dbeaver/dbeaver#15388]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.3.3

#### Connection specification:
- Database name and version: SQL Server 2016

#### Describe the problem you're observing:
When I have a grid with unnamed columns and try filtering on those columns, it fails.
![ezgif-6-969eb532c8](https://user-images.githubusercontent.com/9438635/152527295-f0dec702-2ca8-4dc0-8d82-150a25b8208e.gif)
And the reason it fails is that the grid dataset is filtered using a subquery! This is not efficient. 

I want to filter an already retrieved dataset without re-running the original query as subquery.

Please look at Toad for SQL Server as example: as soon as data is loaded, you can filter it like an Excel table, and there are no additional queries sent to the server.

#### Steps to reproduce, if exist:
I use SQL server but I guess it will fail in other DB types.
Run any query that returns unnamed columns. E.g.
```
select object_schema_name(object_id), object_name(object_id) from sys.all_objects;
```
Try filtering on the column.

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
Can't reproduce anymore.

**Comment by igorzhilin** [comment]
Still reproducible in 22.0.0.202203060510.
1. Run this query: `select object_schema_name(object_id), object_name(object_id) from sys.all_objects;` in any DB in SQL Server.
2. Filter any column with any value.
![image](https://user-images.githubusercontent.com/9438635/158408291-14d0b6b1-2532-4d54-92b7-bb96245bd1cb.png)

**Comment by uslss** [comment]
still reproducible

**Comment by serge-rider** [comment]
Unfortunately it is not possible to filter by columns with empty name. Generally SQL restricts columns with empty names, it is SQL Server-specific issue.

Workaround: add column aliases: 
```sql
select object_schema_name(object_id) schema_name, object_name(object_id) object_name from sys.all_objects
```
