### ISSUE TITLE
Looses script editor title formatting on restart

### ISSUE THREAD

**Issue by ClodoaldoPinto** [dbeaver/dbeaver#15389]
I want use the `${fileName}.${fileExt}`  script title format

![image](https://user-images.githubusercontent.com/1433209/152531336-dc8c3e7e-90f6-4b8d-b8c5-8027b95f6daa.png)

And it works when applied.

![image](https://user-images.githubusercontent.com/1433209/152530047-d4c8c945-f132-4800-852c-53debe1aca0a.png)

But on restart the only retained part is the dot:

![image](https://user-images.githubusercontent.com/1433209/152530466-309244c4-31fc-4de2-80b5-a1aa33b18bda.png)

I'm on Dbeaver portable 21.3.2 on Windows Server 2016 Standard

**Comment by uslss** [comment]
@ClodoaldoPinto Unfortunately, cannot reproduce it. Is there something in the [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)? Could you check if it is reproducible for you against 21.3.4?

**Comment by ClodoaldoPinto** [comment]
The portable version is still at 21.3.2. Nothing in the log catches my eyes. What am I looking for in the log?
