### ISSUE TITLE
pinned result tab grabs focus

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#15385]
#### System information: 
- Operating system (distribution) and version: Debian/Sid
- DBeaver version Version 21.3.3.202201221033
- Additional extensions

#### Connection specification:
- Database name and version: Postgres 11
- Driver name 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
a) execute SQL query
b) pin result tab
c) execute another SQL query
d) new result tab shortly gains focus, but focus immediatelly switches back to previously pinned tab

e) if the new (not pinned) tab is manually put in the foreground, it stays there even for subsequent SQL queries.
f) if c) returns an error, the new result tab keeps focus

**Comment by johandrenth** [comment]
This is quite frustrating. I'm also affected by this.

**Comment by a-locatelli** [comment]
I've the same problem

running on ubuntu 20.04
database: mariadb

**Comment by LonwoLonwo** [comment]
Hello.
Thanks for the bug report.

I think we fixed this behavior in this ticket: https://github.com/dbeaver/dbeaver/issues/15301
Fix will be available in DBeaver 21.3.4 at 07-02-2022

**Comment by LonwoLonwo** [comment]
Hello!

A new release of [DBeaver](https://dbeaver.io/) is available.
It would be handy to check whether the bug is still reproducible.

**Comment by johandrenth** [comment]
I've updated and definitely looks better. Thanks!
