### ISSUE TITLE
SQL server variable name autocompletion removes @

### ISSUE THREAD

**Issue by igorzhilin** [dbeaver/dbeaver#15387]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.3.3
- Additional extensions: none

#### Connection specification:
- Database name and version: SQL Server 2016

#### Describe the problem you're observing:
When I have a declared variable in the script text, and then I type @ and start typing variable name, it appears in autocompletion. Then I select the suggested value from the autocompletion and press Enter. The suggested value is inserted into the editor but the @ at the beginning of the variable is removed.
![ezgif-6-dd11933442](https://user-images.githubusercontent.com/9438635/152525424-ee87f8c0-26f7-45e7-8bc6-085da03eff53.gif)

#### Steps to reproduce, if exist:
```
declare @variable nvarchar(255)
-- then type @ and start typing variable name
-- then select it from autocompletion and hit Enter
```

**Comment by LonwoLonwo** [comment]
Hello @igorzhilin 
Thanks for the bug report.

Note: This issue appears if Hippie Engine is enabled.

**Comment by igorzhilin** [comment]
I noted that the autocompletion also removes the # prefix (SQL server temp tables)

**Comment by LonwoLonwo** [comment]
Hello @igorzhilin 

Thanks for the note.
