### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by FritzBlaskowsky** [dbeaver/dbeaver#15383]
#### System information: 
- Windows 10 Pro (20H2)
- DBeaver 21.3.3

#### Describe the problem you're observing:
DBeaver crashes on startup. The latest working version for me is 21.3.0. 
My computer is in a corporate environment an my profile folder is on a network location. Maybe this is part of the problem.

I already tried deleting the DBeaverData folder, which made no difference.

#### Include any warning/errors/backtraces from the logs
![error](https://user-images.githubusercontent.com/27015666/152492355-3b20a9cd-17e0-4de1-9e36-fb1be89dd718.png)

[.log](https://github.com/dbeaver/dbeaver/files/8001061/default.log)

java.lang.IllegalArgumentException: URI has an authority component

**Comment by DodgeDeBoulet** [comment]
I'm experiencing the same issue on a similar configuration; a Citrix VDI with Windows 10 x64 version 20H2, OS build 19042.1415 and Windows Feature Experience Pack 120.2212.3920.0.

Stack trace attached.

[dbeaverCitrix.log](https://github.com/dbeaver/dbeaver/files/8003373/dbeaverCitrix.log)

I can also confirm that 21.3.0 works on the same system.

**Comment by uslss** [comment]
duplicates #15117
