### ISSUE TITLE
[Oracle] Rowid is not used when table is opened in SQL Editor

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#15397]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.3.4
- Additional extensions

#### Connection specification:
- Database name and version Oracle 

#### Describe the problem you're observing:
Persisting changes to a table without primary key is possible in data editor with the usage of Oracle rowid column, but it won't be used if the table is opened in SQL Editor, the user will be prompted to create virtual keys.

#### Steps to reproduce, if exist:
1. Create a table without a PK
2. Opene it with a basic SELECT in SQL Editor
3. Update or delete a row using UI
4. Click `Save`

**Expected:** Changes are saved

**Actual:** Prompt to create virtual key appers.

**Comment by emironovDB** [comment]
Works as expected
