### ISSUE TITLE
Object description overlaps object size in Navigator

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#15392]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.3.4

#### Steps to reproduce, if exist:
1. Enable object description and object size in connection view
2. Resize navigator's width so that it is smaller than object description

**Expected:** The description is hidden behind size background
**Actual:** Characters overlap each other

![image](https://user-images.githubusercontent.com/82543000/152547066-f1dc2afe-b15e-4af9-84c5-4187c1d38f4f.png)

**Comment by uslss** [comment]
verified
