### ISSUE TITLE
MacOS: Starting DBeaver prompts for permission to accept incoming connections

### ISSUE THREAD

**Issue by acharseth** [dbeaver/dbeaver#15396]
Sorry if this is wrong procedure but I found no way to re-open #11260
I am getting the same message as described in #11260:
Do you want the application "DBeaver.app" to accept incoming network connections?

#### System information: 
- MacOS 12.1 on M1
- DBeaver version 21.3.3

#### Connection specification:
- MariaDB
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I am getting the same message as described in #11260:
Do you want the application "DBeaver.app" to accept incoming network connections?

#### Steps to reproduce, if exist:
Happens every time I start DBeaver.

**Comment by uslss** [comment]
thanks for the report. #11260 reopened
