### ISSUE TITLE
Something weird happened when create column 'dept' and saved it.

### ISSUE THREAD

**Issue by ronnifadhlillah** [dbeaver/dbeaver#15398]
Hallo dbeaver team.

I found something weird when i create column named 'dept' with varchar(100) datatype in dbp_user table. it's taking too long respond when click saved and maybe not responding. The video url and dbeaver version is attached.

Dbeaver Version : ![image](https://user-images.githubusercontent.com/33772449/152689209-55a0944d-f1fe-4d90-adf1-8656fc5c836d.png)
Video URL : [https://drive.google.com/file/d/1xcQ_wShZwkv7K2f8Jjti5L4P34HaL6ab/view?usp=sharing](url)

Thank you.
RF

**Comment by uslss** [comment]
@ronnifadhlillah what database do you use? could you provide table DDL? is there is something in the [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by ronnifadhlillah** [comment]
hallo @uslss i use mysql. ALTER TABLE ccsi_por.dbp_users ADD dept varchar(100) NOT NULL; . and this is the log 
![image](https://user-images.githubusercontent.com/33772449/152773947-1ba2a0b4-8336-412b-bd06-5caf7d3edc14.png)

**Comment by uslss** [comment]
It seems something is going wrong with query syntax. Do you use UI or SQL editor for column creation?

**Comment by ronnifadhlillah** [comment]
hallo ,, i use UI.

**Comment by uslss** [comment]
and what database do you use?

**Comment by uslss** [comment]
There has been no update on the issue for a long time.  If it is still reproducible - feel free to reopen it
