### ISSUE TITLE
With two monitors the csv export displays an extended window

### ISSUE THREAD

**Issue by nitto75** [dbeaver/dbeaver#15407]
#### System information: 
- Operating system Windows 11 pro
- DBeaver version 21.3.4.202202051448

#### Connection specification:
- Database name and version No info
- Driver name DB2 iSeries/AS 400

#### Describe the problem you're observing:
When execute an export cvs with Driver DB2/AS400 the windows wizard for export extends to both monitors.
Meanwhile if click right mouse button on query and export from query, the windows it's right!

It's a bug?
#### Steps to reproduce, if exist:
1 - Execute a query.
2 - Click on button below:
![export](https://user-images.githubusercontent.com/58047165/152820822-58a0819b-128c-4c7a-8096-99cc91475222.jpg)
3 - Select CSV type and click next
4 - View windows extended...
![IMG_9208](https://user-images.githubusercontent.com/58047165/152820844-9d82fdf1-bc41-4eee-bac2-5cff11ebba03.jpg)

If make export from query, the window it's right...
![export_from_query](https://user-images.githubusercontent.com/58047165/152821488-3922bb43-99d1-47f8-b6c3-c2a29bcf6d81.jpg)

**Comment by uslss** [comment]
@nitto75 could you try to reset UI settings (File - Reset UI settings) and check if it helps?

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still present, feel free to reopen it.
