### ISSUE TITLE
Fraction digits not shown in result pane

### ISSUE THREAD

**Issue by GiuseppeMusso-Laser** [dbeaver/dbeaver#15401]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.3.4.202202051448
- Java version: 1.8.0_192
- Additional extensions: -

#### Connection specification:
- Database name and version: Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
- Driver name: Oracle Thin Driver 8
- Do you use tunnels or proxies (SSH, SOCKS, etc)? FortiClient VPN 

#### Describe the problem you're observing:
When showing decimal numbers that have some fraction digits, no fraction digit is shown in result pane as if a trunc was applied.
I am using default settings for Numbers Data Formats. 

#### Steps to reproduce, if exist:
select 1.7, trunc(1.7) from dual;

**Comment by LonwoLonwo** [comment]
Hello @GiuseppeMusso-Laser 

Can you please provide screenshots of SQL Editor with the result + query and Preference Data Formatting Page?

**Comment by GiuseppeMusso-Laser** [comment]
Hello, here is a screenshot showing my problem.
My datasource settings are the same as global settings.
If you need more infos please let me know.

![dbeaver_decimals_showing_problem](https://user-images.githubusercontent.com/20069725/152792759-ee4432f5-8c12-47dc-ae25-1cb067ed77da.png)

**Comment by LonwoLonwo** [comment]
Ok, thanks.

And what about 
`select trunc(1.7, 1) from dual;`
the result is also incorrect?

Also, can you tell me more about your driver? You can get more info about the driver with the "Test connection" button in the "Connection settings" dialog.

**Comment by GiuseppeMusso-Laser** [comment]
The result of:
select trunc(1.7, 1) from dual;
is the same (1): 
![image](https://user-images.githubusercontent.com/20069725/152968370-95149a72-6847-4128-bec8-8b426d924429.png)

From "Test connection" I get:
![image](https://user-images.githubusercontent.com/20069725/152967608-73d6b22d-3557-43e8-9825-5bc416501b12.png)

So my driver version is: Oracle JDBC driver 19.3.0.0.0.

**Comment by uslss** [comment]
Unfortunately, still cannot reproduce it. Is the issue still present in 22.0.1?
![image](https://user-images.githubusercontent.com/31996417/159469067-ed2ef21c-07cc-4558-8d88-061533fe5de4.png)

**Comment by GiuseppeMusso-Laser** [comment]
Yes, it is but I created a new connection using the out-of-the-box Oracle Driver of DBeaver.
It works fine so it is no more a big problem for me.

**Comment by LonwoLonwo** [comment]
Thanks for the answer and investigation @GiuseppeMusso-Laser
