### ISSUE TITLE
Separate color configuration for grid header foreground and grid header border

### ISSUE THREAD

**Issue by darko1979** [dbeaver/dbeaver#15402]
Currently "grid header foreground" color is used for drawing grid header foreground text and the cell border.

![Screenshot_3](https://user-images.githubusercontent.com/23734311/152779687-42917c2b-d336-4836-979c-cebd3b0af4c8.png)

I would like to have two separate color options for text and border.
I know this is not a big issue but for me having the same bright color for text and border is distracting to me. I would like to have a white header text and a dark gray for cell border.

PS: I'm unable to find which option defines color for the input above grid with placeholder text "Enter a SQL expression to filter results"? I would also like to change this to darker color.

**Comment by Skydiveroid** [comment]
Thank you for your request.

**Comment by ShadelessFox** [comment]
Hello @darko1979,

In the case of placeholder text, we use predefined system color. It can't be changed via preferences.

**Comment by ShadelessFox** [comment]
The additional color definition was added under the `Database Query Results` folder called `Grid header border color`.

|Before|After|
|---|---|
|![lre8zmsT5J](https://user-images.githubusercontent.com/35821147/172162412-0b1d0272-eaec-4ea8-a93e-d47fd17c2bb5.png)|![UPAxVgp5po](https://user-images.githubusercontent.com/35821147/172162442-1aff9604-5391-4910-bdc7-18a57d055c4c.png)|
|![java_mqjzymNIAH](https://user-images.githubusercontent.com/35821147/172162507-420dbcc4-a14d-48d4-9b9b-ef9b3f555e0c.png)|![6zYOaZoF50](https://user-images.githubusercontent.com/35821147/172162892-1176d902-e5ed-492e-b6bf-2ef9c06f478c.png)|

You'll probably have to use a magnifier to see the differences.

**Comment by Matvey16** [comment]
Verified
