### ISSUE TITLE
"Move to top" swaps fields instead of move and shift down

### ISSUE THREAD

**Issue by gm-lunatix** [dbeaver/dbeaver#15411]
#### System information: 
- Operating system (distribution) and version: win11
- DBeaver version: 21.3.4 community edition
- Additional extensions: n/a

#### Connection specification:
- Database name and version: PostgreSQL v11
- Driver name: n/a
- Do you use tunnels or proxies (SSH, SOCKS, etc)? n/a

#### Describe the problem you're observing:
Similar to the bug https://github.com/dbeaver/dbeaver/issues/2158 back in 2017, when I use "Customize filters..." and click on "Move to top" the field is moved to the top but also swaps the top field instead of shifting all fields down.

#### Steps to reproduce, if exist:
1. open any table data view
2. click on "Customize filters ..." icon
3. select any field not at the top
4. click on "Move to top" icon
5. notice that the top field is now swapped with the selected field

Before:
![image](https://user-images.githubusercontent.com/73477545/152859063-b94a7476-c90d-4fdc-b8e1-df9c103ebaa7.png)

After:
![image](https://user-images.githubusercontent.com/73477545/152859107-aea39f41-286b-4660-8f05-e80b30973b9a.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
verified
