### ISSUE TITLE
PostgreSQL: Multi-database support without automatic lookup

### ISSUE THREAD

**Issue by nicchristeller** [dbeaver/dbeaver#15413]
As described in [PostgreSQL: Multi-database model support](https://github.com/dbeaver/dbeaver/issues/34), we can turn on the option "Show all databases" to allow a single connection to a server to show multiple databases.

My one problem with this is when I connect to a server for which I don't have permissions to the `postgres` database. With "Show all databases", I obviously then get an error when DBeaver attempts to connect to the `postgres` database.

Ideally instead of a lookup, I could specify which databases I want to connect to. Or the automatic lookup could use a specified database other than `postgres` for lookup (if this is possible).

I can workaround this by just creating several connections in the database navigator, but it'd be nice to leave the databases on each server grouped.

**Comment by LonwoLonwo** [comment]
Hello @nicchristeller 

If I understand you correctly, you can't read the `postgres` database.

Maybe filters can help you?

You can find connection filters in the "Connection settings" -> "General"

![2022-02-09 00_07_39-DBeaver Ultimate 21 3 4 - _postgres 13 3_Script-81](https://user-images.githubusercontent.com/45152336/153076296-3abe22a3-0db8-4dd8-ba6a-995eef8a5c65.png)

![2022-02-09 00_08_04-Connection _postgres 13 3_ configuration](https://user-images.githubusercontent.com/45152336/153076304-92b1c4c8-cc4e-4f0e-929f-64b439f24799.png)

**Comment by nicchristeller** [comment]
That looks promising, although I'm not quite sure what to make of the behaviour.

With these settings: "Show all databases" checked, "Databases/Catalogs" filtering enabled, and all of "database1", "database2" and "database3" added to the "include" list.

If database1 is the connection target (i.e. the specified database in Connection Settings -> Main -> Server), then database1 and database3 show up in the list of databases. 
If database2 is the connection target, I get an error "No databases found on server". 
If database2 is the connection target and "Show all databases" is unchecked, then it alone shows in the list of databases.

Any thoughts, or is this sounding too situation-specific to go much deeper?

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.
