### ISSUE TITLE
Export result set from temp tables error

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#15420]
#### System information: 
- Win10 Pro
- DBeaver 21.3.4 (same problem in 21.3.3)
- No additional extensions

#### Connection specification:
- PostgreSQL 9.5
- Default postgresql driver
- No tunnels or proxies

#### Describe the problem you're observing:
Error on export result set from temp table

#### Steps to reproduce, if exist:
Execute query below and try export to SQL or TXT format
```
create temp table tt as
select 1 as id;

select *
from tt;
```
![01](https://user-images.githubusercontent.com/22142845/152980971-04d0d3ca-81f9-4d98-8414-7e3868c3f675.jpg)

#### Include any warning/errors/backtraces from the logs
[log](https://github.com/dbeaver/dbeaver/files/8023482/log.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/8023485/dbeaver-debug.log)

**Comment by uslss** [comment]
@ems2811 probably, you've got Open new connection(s) enabled in properties?
![image](https://user-images.githubusercontent.com/31996417/153060775-1091bbfd-1b3a-4d50-86fe-1a2cc12d0934.png)
In this case the temporary table doesn't exist in the newly opened connection

**Comment by ems2811** [comment]
Really. I didn't think about that. Thank you.
