### ISSUE TITLE
errors when reading large HANA lobs

### ISSUE THREAD

**Issue by kai-morich** [dbeaver/dbeaver#15427]
with default settings, lob behavior changes on 10k and 1MB
![image](https://user-images.githubusercontent.com/25850372/153037302-c4eb14af-5089-4265-9828-0a11529bd5f3.png)

this testcase 
```
DROP TABLE l1;
CREATE TABLE l1(i int, c nclob);
INSERT INTO l1 values (1, 'x');

UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1); 
SELECT LENGTH(c), * FROM l1;  -- 8kB, shown in result table cell
UPDATE l1 SET c = (SELECT c||c FROM l1);
SELECT LENGTH(c), * FROM l1;  -- 16kB, shown in value window
UPDATE l1 SET c = (SELECT c||c FROM l1);
SELECT LENGTH(c), * FROM l1;  -- 32kB, empty value window, no error
UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1);
UPDATE l1 SET c = (SELECT c||c FROM l1);
SELECT LENGTH(c), * FROM l1;  -- 1MB, fails when opening value window: Error loading text value, IO error while copying content, SAP DBTech JDBC: [1033]: error while parsing protocol: invalid lob locator id (piecewise lob reading)
```
shows no value starting with 32KB and errors starting with 1MB
![image](https://user-images.githubusercontent.com/25850372/153036654-c0831d56-9273-480a-b294-195e3493168e.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
Hello @kai-morich 

So, I used your example - and I had an error from the issue.
But after that, I increased the cache size value - and now I can see data in Binary presentation and Text presentation.

![2022-08-30 18_42_30-Window](https://user-images.githubusercontent.com/45152336/187483445-ac6caad7-2a6f-4613-bbae-38b5696289bb.png)

![2022-08-30 18_43_16-Window](https://user-images.githubusercontent.com/45152336/187483449-10f1b1d7-e1ea-414c-b6fd-011857599762.png)

So what can I do for you else?

**Comment by kai-morich** [comment]
I would have expected that a 'lob cache size' option improves performance when reading same lobs again, but I did not expect that this limits the maximum single lob size. Single lob reading should be without limit or the option should be named more clearly and a dbeaver error instead of no error or DB specific error should be shown when limit exceeded, so users can figure out, which option they have to change.

**Comment by LonwoLonwo** [comment]
Ok, thanks for the answer @kai-morich 

As I can see - this is a general issue for different databases - reading LOBs from the driver's side. It can be solved by switching from Auto-commit mode to manual. I will add a message about it for Exceptions.

**Comment by kai-morich** [comment]
👍
