### ISSUE TITLE
CIDR data type support in map marker - Spatial view (Postgresql)

### ISSUE THREAD

**Issue by sid6mathur** [dbeaver/dbeaver#15433]
**Is your feature request related to a problem? Please describe.**
Postgresql-native CIDR data type is not shown as a string when showing result row in the Spatial view

**Describe the solution you'd like**
the native CIDR data type should be rendered as "192.168.1.0/24" and not has [object Object]

**Describe alternatives you've considered**
None

**Additional context**
The `subnet` column (Postgresl native `cidr` type) is not shown here in human-readable form
![image](https://user-images.githubusercontent.com/5669765/153154634-b235a800-13a9-4daf-8345-a1ebfc6c0ca0.png)

![image](https://user-images.githubusercontent.com/5669765/153154833-c4389f15-686a-423f-847d-ffbfe8b114ec.png)

**Simple test case**
```sql
CREATE EXTENSION IF NOT EXISTS postgis;
SELECT cidr('192.168.1.0/24') AS mycidr, 'Is this CIDR looking human readable?' AS mylabel, ST_SetSRID(ST_MakePoint(-71.1043443253471, 42.3150676015829),4326) AS myloc
```
Click on the blue dot in the `Spatial` view of the results tab to see marker view showing [object Object]

**Comment by sid6mathur** [comment]
Added simple test case: 
```sql 
CREATE EXTENSION IF NOT EXISTS postgis;
SELECT cidr('192.168.1.0/24') AS mycidr, 'Is this CIDR looking human readable?' AS mylabel, ST_SetSRID(ST_MakePoint(-71.1043443253471, 42.3150676015829),4326) AS myloc;
```
Click on the blue dot in the Spatial view of the results tab to see marker view showing [object Object]

**Comment by Skydiveroid** [comment]
Thanks for the report.

**Comment by sid6mathur** [comment]
Both `inet` and `cidr` types aren't shown in the marker. Updated repro case below with `inet` added. Thanks for the quick triage 💯 
```sql
CREATE EXTENSION IF NOT EXISTS postgis;
SELECT cidr('192.168.1.0/24') AS mycidr, inet('1.1.1.1') AS myinet,  'Is this CIDR looking human readable?' AS mylabel, ST_SetSRID(ST_MakePoint(-71.1043443253471, 42.3150676015829),4326) AS myloc;
```

**Comment by ShadelessFox** [comment]
It looks like these types are treated as binary data of some kind. Thus, they can't be normally converted to a string representation.

**Comment by sid6mathur** [comment]
How amazing are you folks! Thanks for the user love.

**Comment by uslss** [comment]
verified
