### ISSUE TITLE
Cloud SQL for Postgres: Could not initialize class com.google.cloud.sql.postgres.SocketFactory

### ISSUE THREAD

**Issue by kurtisvg** [dbeaver/dbeaver#15459]
#### System information: 
- Operating system (distribution) and version: MacOs Monterey v12.2
- DBeaver version: CE 21.3.4
- Additional extensions: N/A

#### Connection specification:
- Database name and version: PG 12
- Driver name: Cloud SQL for Postgres
- Do you use tunnels or proxies (SSH, SOCKS, etc)? N/A

#### Describe the problem you're observing:
```
Something unusual has occurred to cause the driver to fail. Please report this exception.
  com/google/cloud/sql/core/CoreSocketFactory
  com/google/cloud/sql/core/CoreSocketFactory
    com.google.cloud.sql.core.CoreSocketFactory
    com.google.cloud.sql.core.CoreSocketFactory
```

#### Steps to reproduce, if exist:
1. Download and install DBeaver
2. Select "Connect to a database" and choose "Google Cloud SQL - PostgreSQL" 
3. Enter the INSTANCE_CONNECTION_NAME in the host/instances box (looks like it really doesn't matter if you put one in)
4. Click "Finish" 
5. Try using the datasource

#### Include any warning/errors/backtraces from the logs

```
java.lang.NoClassDefFoundError: Could not initialize class com.google.cloud.sql.postgres.SocketFactory
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.postgresql.util.ObjectFactory.instantiate(ObjectFactory.java:46)
	at org.postgresql.core.SocketFactoryFactory.getSocketFactory(SocketFactoryFactory.java:39)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:182)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
	at org.postgresql.Driver.makeConnection(Driver.java:465)
	at org.postgresql.Driver.access$100(Driver.java:62)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:375)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by ShadelessFox** [comment]
Hello @kurtisvg,

The driver is missing one extra dependency. It is caused by dependency having a templated version. DBeaver can't resolve it, so it is ignored.

As a workaround, you can add the missing dependency manually:

```xml
<dependency>
    <groupId>com.google.cloud.sql</groupId>
    <artifactId>jdbc-socket-factory-core</artifactId>
    <version>1.4.3</version>
</dependency>
```

You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/How-to-add-additional-artifacts-to-the-driver.

**Comment by kurtisvg** [comment]
Thanks @ShadelessFox, that did the trick. 

Can you help me understand what "It is caused by dependency having a templated version." refers to? Is it the dependency in the POM [here](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/dd186886ede59350b3f0a66bc47a103dec86653e/jdbc/postgres/pom.xml#L101), or is it something else? Is there a way to fix this so other folks don't run into this issue?

**Comment by ShadelessFox** [comment]
Yes, I'm talking about that line.

The semantics of the properties are well-described here in the [POM Reference](https://maven.apache.org/pom.html#Properties). We can try to resolve them.

**Comment by kurtisvg** [comment]
That would be great - otherwise the built in "Cloud SQL" driver configs set don't seem particularly useful.

**Comment by ravi-k1** [comment]
I like it, it's simple to use and for the last year that we use it, I didn't experience any unreliability. We only use MySQL in CloudSQL.

There are snapshots, it has scheduled downtimes and you can choose when you want to have the downtime. Scheduled downtime usually takes a minute, scaling maybe two minutes. You could add replicas, and either switch the master or just use reads.

It's simple to set up slow query logging to Google Logs.

I can't say much on the price. We used to host our own DBs, so now we don't do that anymore. And while it costs more now than the pure instance costs, we don't need to self implement backups, etc.

I had experience with Azure MySQL hosting and Google is definitely better. Apparently the high latency on Azure was an issue with the PHP developers who had several roundtrips to the database per HTTP request.

**Comment by FzzyBnny** [comment]
DBeaver version: CE 21.3.4.202202051448
Operating system (distribution) and version: Microsoft Windows [Version 10.0.22489.1000]

I tried manually adding the dependency via the "Add Artifact" as suggested, but when I would attempt to Download/Update, then DBeaver would throw this error:
```
Error resolving dependencies
  Maven artifact 'maven:/com.google.cloud.sql:jdbc-socket-factory-core:RELEASE' not found
```

I was able to get this to work by manually editing the version tag in the `postgres-socket-factory-1.4.3.pom` file from `<version>${project.parent.version}</version>` to `<version>1.4.3</version>`. With that in place, then the DBeaver Driver Manager was able to resolve the dependency successfully.

In Windows 11 (and presumably 7, 8, 8.1, and 10) this specific POM is located here (adjust <<username>> accordingly):

`C:\Users\<<username>>\AppData\Roaming\DBeaverData\drivers\maven\maven-central\com.google.cloud.sql\postgres-socket-factory-1.4.3.pom`

Try at your own risk and mileage may vary. I cannot guarantee this will always work and won't introduce issues on down the road.

**Comment by e-compagno** [comment]
> DBeaver version: CE 21.3.4.202202051448 Operating system (distribution) and version: Microsoft Windows [Version 10.0.22489.1000]
> 
> I tried manually adding the dependency via the "Add Artifact" as suggested, but when I would attempt to Download/Update, then DBeaver would throw this error:
> 
> ```
> Error resolving dependencies
>   Maven artifact 'maven:/com.google.cloud.sql:jdbc-socket-factory-core:RELEASE' not found
> ```
> 
> I was able to get this to work by manually editing the version tag in the `postgres-socket-factory-1.4.3.pom` file from `<version>${project.parent.version}</version>` to `<version>1.4.3</version>`. With that in place, then the DBeaver Driver Manager was able to resolve the dependency successfully.
> 
> In Windows 11 (and presumably 7, 8, 8.1, and 10) this specific POM is located here (adjust <> accordingly):
> 
> `C:\Users\<<username>>\AppData\Roaming\DBeaverData\drivers\maven\maven-central\com.google.cloud.sql\postgres-socket-factory-1.4.3.pom`
> 
> Try at your own risk and mileage may vary. I cannot guarantee this will always work and won't introduce issues on down the road.

I haven't been able to implement your solution. Could you please explain more in details on how to solve the `Maven artifact 'maven:/com.google.cloud.sql:jdbc-socket-factory-core:RELEASE' not found` problem and install the library in DBeaver?

**Comment by e-compagno** [comment]
I've been able to let it work

https://github.com/dbeaver/dbeaver/issues/15526#issuecomment-1042905088

**Comment by nanoflow** [comment]
Still cannot get it working on Ubuntu and will stick to my current work around: downgrade to version 1.4.1 in the following steps:

in 'Edit Driver Settings' / 'Libraries' click on Download/Update
select Version 1.2.0 (or something very old) for the com.google.cloud.sql:postgres-socket-factory driver, check 'Force download / overwrite' and click Download
restart dBeaver
redo the above steps but with version 1.4.1
But still it would be nice, if the newest version could be a working one again

**Comment by ShadelessFox** [comment]
As a workaround we've explicitly added the missing dependency.

The fix will be available in DBeaver 21.3.5.

**Comment by FzzyBnny** [comment]
> As a workaround we've explicitly added the missing dependency.
> 
> The fix will be available in DBeaver 21.3.5.

Thank you for looking into this @ShadelessFox

**Comment by uslss** [comment]
verified

**Comment by ShadelessFox** [comment]
I've created a separate ticket about resolving POM properties: #15556
