### ISSUE TITLE
Vertica - Discover Owner Entity is very slow

### ISSUE THREAD

**Issue by dabocla** [dbeaver/dbeaver#15458]
Reference:
https://github.com/dbeaver/dbeaver/issues/4193

#### System information: 
![image](https://user-images.githubusercontent.com/1686584/153455261-22b8a298-98cf-4b40-8f52-713dec79da52.png)
![image](https://user-images.githubusercontent.com/1686584/153455467-4ce95900-4f8b-4034-bfd1-915158533723.png)

No additional extensions

#### Connection specification:
- Database name and version
Vertica Analytic Database v10.0.0-3
- Driver name
vertica-jdbc-10.0.1-0.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
For some reason, the discovering owner entity query takes a long time to run.  I can see in the query manager that my query comes back in usually under 7 seconds, then the screen transitions to discover owner entity and that query doesn't appear to end.

![image](https://user-images.githubusercontent.com/1686584/153457049-df84db46-0293-492c-aeca-dac7b849e26f.png)

#### Steps to reproduce, if exist:
It appears that all I need to do is execute a query.  I've used dbeaver in the past and it's been an excellent experience.  I'm not sure why this is an issue now.  I did switch from windows to mac, so perhaps there's something there?

#### Include any warning/errors/backtraces from the logs

The query it's hung up on is the following:
SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type, com."comment" as remarks
FROM v_catalog.tables t LEFT JOIN v_catalog.comments com ON com.object_type = 'TABLE'
AND com.object_id = t.table_id
WHERE t.table_schema='SCHEMA' and t.table_name = 'EXAMPLE_TABLE'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type, com."comment" as remarks
FROM v_catalog.views v LEFT JOIN v_catalog.comments com ON com.object_type = 'VIEW'
AND com.object_id = v.table_id
WHERE v.table_schema='SCHEMA' and v.table_name = 'EXAMPLE_TABLE'

**Comment by LonwoLonwo** [comment]
Hello @dabocla 

Maybe your issue is related to this issue: https://github.com/dbeaver/dbeaver/issues/14625

Can you please check with the [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) execution time of these 2 queries:

```sql
SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type, com."comment" as remarks
FROM v_catalog.tables t LEFT JOIN v_catalog.comments com ON com.object_type = 'TABLE'
AND com.object_id = t.table_id
WHERE t.table_schema='Your_Schema_Name'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type, com."comment" as remarks
FROM v_catalog.views v LEFT JOIN v_catalog.comments com ON com.object_type = 'VIEW'
AND com.object_id = v.table_id
WHERE v.table_schema='Your_Schema_Name'
```

VS

```sql
SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type
FROM v_catalog.tables t
WHERE t.table_schema='Your_Schema_Name'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type
FROM v_catalog.views v
WHERE v.table_schema='Your_Schema_Name'
```

**Comment by dabocla** [comment]
Output from the query manager.

Neither query returned a resultset.  For the tests I used a proper schema,
then changed it to something else prior to responding.

Feb-11 11:58:12 SQL / User SELECT t.table_schema as table_schem,
t.table_name, t.create_time, t.is_temp_table, t.is_system_table,
t.has_aggregate_projection, t.partition_expression, case when is_flextable
= true THEN 'FLEX TABLE' else 'TABLE' end as table_type
FROM v_catalog.tables t
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time,
v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table,
false as has_aggregate_projection, null as partition_expression, 'VIEW' as
table_type
FROM v_catalog.views v
WHERE v.table_schema='our_schema'
63,806 Success cerner SQLEditor <Script.sql>
Feb-11 11:56:53 SQL / User SELECT t.table_schema as table_schem,
t.table_name, t.create_time, t.is_temp_table, t.is_system_table,
t.has_aggregate_projection, t.partition_expression, case when is_flextable
= true THEN 'FLEX TABLE' else 'TABLE' end as table_type, com."comment" as
remarks
FROM v_catalog.tables t LEFT JOIN v_catalog.comments com ON com.object_type
= 'TABLE'
AND com.object_id = t.table_id
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time,
v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table,
false as has_aggregate_projection, null as partition_expression, 'VIEW' as
table_type, com."comment" as remarks
FROM v_catalog.views v LEFT JOIN v_catalog.comments com ON com.object_type
= 'VIEW'
AND com.object_id = v.table_id
WHERE v.table_schema='our_schema' 46,004 Success cerner SQLEditor
<Script.sql>
Feb-11 11:57:46 SQL / Meta SELECT t.table_schema as table_schem,
t.table_name, t.create_time, t.is_temp_table, t.is_system_table,
t.has_aggregate_projection, t.partition_expression, case when is_flextable
= true THEN 'FLEX TABLE' else 'TABLE' end as table_type, com."comment" as
remarks
FROM v_catalog.tables t LEFT JOIN v_catalog.comments com ON com.object_type
= 'TABLE'
AND com.object_id = t.table_id
WHERE t.table_schema='public' and t.table_name = 'v_catalog'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time,
v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table,
false as has_aggregate_projection, null as partition_expression, 'VIEW' as
table_type, com."comment" as remarks
FROM v_catalog.views v LEFT JOIN v_catalog.comments com ON com.object_type
= 'VIEW'
AND com.object_id = v.table_id
WHERE v.table_schema='public' and v.table_name = 'v_catalog' 1,226,613
Success cerner Metadata
Feb-11 11:59:20 SQL / User SELECT t.table_schema as table_schem,
t.table_name, t.create_time, t.is_temp_table, t.is_system_table,
t.has_aggregate_projection, t.partition_expression, case when is_flextable
= true THEN 'FLEX TABLE' else 'TABLE' end as table_type
FROM v_catalog.tables t
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time,
v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table,
false as has_aggregate_projection, null as partition_expression, 'VIEW' as
table_type
FROM v_catalog.views v
WHERE v.table_schema='our_schema' 1,230,057 Success cerner SQLEditor
<Script.sql>
Feb-11 11:07:58 SQL / User SELECT t.table_schema as table_schem,
t.table_name, t.create_time, t.is_temp_table, t.is_system_table,
t.has_aggregate_projection, t.partition_expression, case when is_flextable
= true THEN 'FLEX TABLE' else 'TABLE' end as table_type, com."comment" as
remarks
FROM v_catalog.tables t LEFT JOIN v_catalog.comments com ON com.object_type
= 'TABLE'
AND com.object_id = t.table_id
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time,
v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table,
false as has_aggregate_projection, null as partition_expression, 'VIEW' as
table_type, com."comment" as remarks
FROM v_catalog.views v LEFT JOIN v_catalog.comments com ON com.object_type
= 'VIEW'
AND com.object_id = v.table_id
WHERE v.table_schema='our_schema'
1,420,566 Success cerner SQLEditor <Script.sql>
Feb-11 11:07:51 Transaction Rollback 1,426,943 cerner SQLEditor <Script.sql>
Feb-11 12:37:16 SQL / User SELECT t.table_schema as table_schem,
t.table_name, t.create_time, t.is_temp_table, t.is_system_table,
t.has_aggregate_projection, t.partition_expression, case when is_flextable
= true THEN 'FLEX TABLE' else 'TABLE' end as table_type, com."comment" as
remarks
FROM v_catalog.tables t LEFT JOIN v_catalog.comments com ON com.object_type
= 'TABLE'
AND com.object_id = t.table_id
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time,
v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table,
false as has_aggregate_projection, null as partition_expression, 'VIEW' as
table_type, com."comment" as remarks
FROM v_catalog.views v LEFT JOIN v_catalog.comments com ON com.object_type
= 'VIEW'
AND com.object_id = v.table_id
WHERE v.table_schema='our_schema' 1,445,230 Success cerner SQLEditor
<Script.sql>
Feb-11 11:56:20 SQL / User SELECT t.table_schema as table_schem,
t.table_name, t.create_time, t.is_temp_table, t.is_system_table,
t.has_aggregate_projection, t.partition_expression, case when is_flextable
= true THEN 'FLEX TABLE' else 'TABLE' end as table_type
FROM v_catalog.tables t
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time,
v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table,
false as has_aggregate_projection, null as partition_expression, 'VIEW' as
table_type
FROM v_catalog.views v
WHERE v.table_schema='our_schema'
10,798 Success cerner SQLEditor <Script.sql>
Feb-11 11:33:30 SQL / User SELECT t.table_schema as table_schem,
t.table_name, t.create_time, t.is_temp_table, t.is_system_table,
t.has_aggregate_projection, t.partition_expression, case when is_flextable
= true THEN 'FLEX TABLE' else 'TABLE' end as table_type
FROM v_catalog.tables t
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time,
v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table,
false as has_aggregate_projection, null as partition_expression, 'VIEW' as
table_type
FROM v_catalog.views v
WHERE v.table_schema='our_schema'
12,635 Success cerner SQLEditor <Script.sql>
Feb-11 13:01:21 SQL / Meta select current_schema() 188 1 Success cerner
SQLEditor <Script.sql>
Feb-11 12:37:12 SQL / User SELECT t.table_schema as table_schem,
t.table_name, t.create_time, t.is_temp_table, t.is_system_table,
t.has_aggregate_projection, t.partition_expression, case when is_flextable
= true THEN 'FLEX TABLE' else 'TABLE' end as table_type
FROM v_catalog.tables t
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time,
v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table,
false as has_aggregate_projection, null as partition_expression, 'VIEW' as
table_type
FROM v_catalog.views v
WHERE v.table_schema='our_schema'
2,869,551 Success cerner SQLEditor <Script.sql>
Feb-11 11:31:38 SQL / Meta select current_schema() 40 1 Success cerner
SQLEditor <Script.sql>
Feb-11 12:19:50 SQL / Meta select current_schema() 44 1 Success cerner
SQLEditor <Script.sql>
Feb-11 11:56:31 SQL / Meta select current_schema() 48 1 Success cerner
SQLEditor <Script.sql>
Feb-11 11:49:38 SQL / Meta select current_schema() 53 1 Success cerner
SQLEditor <Script.sql>
Feb-11 11:33:07 SQL / Meta SELECT st.table_schema as table_schem,
st.table_description as remarks, 'SYSTEM TABLE' as table_type, st.*
from v_catalog.system_tables st where st.table_schema ='v_catalog' 136 1
Success cerner Metadata
Feb-11 13:01:21 SQL / Meta select current_schema() 248 1 Success cerner
SQLEditor <Script.sql>
Feb-11 11:33:43 SQL / Meta select current_schema() 679 1 Success cerner
SQLEditor <Script.sql>
Feb-11 11:34:21 SQL / User SELECT t.table_schema as table_schem,
t.table_name, t.create_time, t.is_temp_table, t.is_system_table,
t.has_aggregate_projection, t.partition_expression, case when is_flextable
= true THEN 'FLEX TABLE' else 'TABLE' end as table_type, com."comment" as
remarks
FROM v_catalog.tables t LEFT JOIN v_catalog.comments com ON com.object_type
= 'TABLE'
AND com.object_id = t.table_id
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time,
v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table,
false as has_aggregate_projection, null as partition_expression, 'VIEW' as
table_type, com."comment" as remarks
FROM v_catalog.views v LEFT JOIN v_catalog.comments com ON com.object_type
= 'VIEW'
AND com.object_id = v.table_id
WHERE v.table_schema='our_schema' 917,225 Success cerner SQLEditor
<Script.sql>

**Comment by LonwoLonwo** [comment]
Did requests without JOIN on v_catalog.comments work faster? With the real schema names as t.table_schema.

**Comment by dabocla** [comment]
Sorry for the late response - the times are in the screenshot that I shared above.  It's not the cleanest presentation, but the data is all there.

**Comment by LonwoLonwo** [comment]
Hello @dabocla 

Unfortunately, I do not see any screenshots. Please can you provide them one more time? But here in GitHub, not via e-mail.

**Comment by dabocla** [comment]
Sorry, I thought they pasted as screenshots, but they pasted as text.  Below is the output from the query manager.  The number right before Success is the number of millis that the query took to execute.

Does this help?

```sql
Feb-11 11:58:12 SQL / User  SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type
FROM v_catalog.tables t
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type
FROM v_catalog.views v
WHERE v.table_schema='our_schema'
    63,806      Success cerner  SQLEditor <Script.sql>
Feb-11 11:56:53 SQL / User  SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type, com."comment" as remarks
FROM v_catalog.tables t LEFT JOIN v_catalog.comments com ON com.object_type = 'TABLE'
AND com.object_id = t.table_id
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type, com."comment" as remarks
FROM v_catalog.views v LEFT JOIN v_catalog.comments com ON com.object_type = 'VIEW'
AND com.object_id = v.table_id
WHERE v.table_schema='our_schema'   46,004      Success cerner  SQLEditor <Script.sql>
Feb-11 11:57:46 SQL / Meta  SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type, com."comment" as remarks
FROM v_catalog.tables t LEFT JOIN v_catalog.comments com ON com.object_type = 'TABLE'
AND com.object_id = t.table_id
WHERE t.table_schema='public' and t.table_name = 'v_catalog'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type, com."comment" as remarks
FROM v_catalog.views v LEFT JOIN v_catalog.comments com ON com.object_type = 'VIEW'
AND com.object_id = v.table_id
WHERE v.table_schema='public' and v.table_name = 'v_catalog'    1,226,613       Success cerner  Metadata
Feb-11 11:59:20 SQL / User  SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type
FROM v_catalog.tables t
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type
FROM v_catalog.views v
WHERE v.table_schema='our_schema'   1,230,057       Success cerner  SQLEditor <Script.sql>
Feb-11 11:07:58 SQL / User  SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type, com."comment" as remarks
FROM v_catalog.tables t LEFT JOIN v_catalog.comments com ON com.object_type = 'TABLE'
AND com.object_id = t.table_id
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type, com."comment" as remarks
FROM v_catalog.views v LEFT JOIN v_catalog.comments com ON com.object_type = 'VIEW'
AND com.object_id = v.table_id
WHERE v.table_schema='our_schema'
    1,420,566       Success cerner  SQLEditor <Script.sql>
Feb-11 11:07:51 Transaction Rollback    1,426,943           cerner  SQLEditor <Script.sql>
Feb-11 12:37:16 SQL / User  SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type, com."comment" as remarks
FROM v_catalog.tables t LEFT JOIN v_catalog.comments com ON com.object_type = 'TABLE'
AND com.object_id = t.table_id
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type, com."comment" as remarks
FROM v_catalog.views v LEFT JOIN v_catalog.comments com ON com.object_type = 'VIEW'
AND com.object_id = v.table_id
WHERE v.table_schema='our_schema'   1,445,230       Success cerner  SQLEditor <Script.sql>
Feb-11 11:56:20 SQL / User  SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type
FROM v_catalog.tables t
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type
FROM v_catalog.views v
WHERE v.table_schema='our_schema'
    10,798      Success cerner  SQLEditor <Script.sql>
Feb-11 11:33:30 SQL / User  SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type
FROM v_catalog.tables t
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type
FROM v_catalog.views v
WHERE v.table_schema='our_schema'
    12,635      Success cerner  SQLEditor <Script.sql>
Feb-11 13:01:21 SQL / Meta  select current_schema() 188 1   Success cerner  SQLEditor <Script.sql>
Feb-11 12:37:12 SQL / User  SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type
FROM v_catalog.tables t
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type
FROM v_catalog.views v
WHERE v.table_schema='our_schema'
    2,869,551       Success cerner  SQLEditor <Script.sql>
Feb-11 11:31:38 SQL / Meta  select current_schema() 40  1   Success cerner  SQLEditor <Script.sql>
Feb-11 12:19:50 SQL / Meta  select current_schema() 44  1   Success cerner  SQLEditor <Script.sql>
Feb-11 11:56:31 SQL / Meta  select current_schema() 48  1   Success cerner  SQLEditor <Script.sql>
Feb-11 11:49:38 SQL / Meta  select current_schema() 53  1   Success cerner  SQLEditor <Script.sql>
Feb-11 11:33:07 SQL / Meta  SELECT st.table_schema as table_schem, st.table_description as remarks, 'SYSTEM TABLE' as table_type, st.*
from v_catalog.system_tables st where st.table_schema ='v_catalog'  136 1   Success cerner  Metadata
Feb-11 13:01:21 SQL / Meta  select current_schema() 248 1   Success cerner  SQLEditor <Script.sql>
Feb-11 11:33:43 SQL / Meta  select current_schema() 679 1   Success cerner  SQLEditor <Script.sql>
Feb-11 11:34:21 SQL / User  SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type, com."comment" as remarks
FROM v_catalog.tables t LEFT JOIN v_catalog.comments com ON com.object_type = 'TABLE'
AND com.object_id = t.table_id
WHERE t.table_schema='our_schema'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type, com."comment" as remarks
FROM v_catalog.views v LEFT JOIN v_catalog.comments com ON com.object_type = 'VIEW'
AND com.object_id = v.table_id
WHERE v.table_schema='our_schema'   917,225     Success cerner  SQLEditor <Script.sql>
```

**Comment by LonwoLonwo** [comment]
Thanks for the investigation!

Please, can you compare the duration of these two queries?

```sql
SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type
FROM v_catalog.tables t
WHERE t.table_schema='Your_Schema_Name'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type
FROM v_catalog.views v
WHERE v.table_schema='Your_Schema_Name'
```

vs

```sql
select * from v_catalog.all_tables al where al.schema_name = 'Your_Schema_Name'
```

**Comment by amazzucco48** [comment]
Query performance with Join: 80,000ms 
Query performance without join: 300ms
all_tables select *: 1,600ms

**Comment by LonwoLonwo** [comment]
with JOIN is

```sql
SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type, com."comment" as remarks
FROM v_catalog.tables t LEFT JOIN v_catalog.comments com ON com.object_type = 'TABLE'
AND com.object_id = t.table_id
WHERE t.table_schema='Your_Schema_Name'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type, com."comment" as remarks
FROM v_catalog.views v LEFT JOIN v_catalog.comments com ON com.object_type = 'VIEW'
AND com.object_id = v.table_id
WHERE v.table_schema='Your_Schema_Name'
```

- 80,000ms

And without - 

```sql
SELECT t.table_schema as table_schem, t.table_name, t.create_time, t.is_temp_table, t.is_system_table, t.has_aggregate_projection, t.partition_expression, case when is_flextable = true THEN 'FLEX TABLE' else 'TABLE' end as table_type
FROM v_catalog.tables t
WHERE t.table_schema='Your_Schema_Name'
UNION ALL
SELECT v.table_schema as table_schem, v.table_name, v.create_time, v.is_local_temp_view as is_temp_table, v.is_system_view as is_system_table, false as has_aggregate_projection, null as partition_expression, 'VIEW' as table_type
FROM v_catalog.views v
WHERE v.table_schema='Your_Schema_Name'
```

- 300ms

Am I right?

**Comment by amazzucco48** [comment]
Correct. 

This is also another long running query (60,000ms): 
```
SELECT
	com.comment AS REMARKS,
	col.*,
	col.sql_type_id AS SOURCE_DATA_TYPE,
	col.data_type_name AS TYPE_NAME,
	col.column_default AS COLUMN_DEF
FROM
	v_catalog.odbc_columns col
LEFT JOIN v_catalog.comments com ON
	com.object_type = 'COLUMN'
	AND com.object_schema = col.schema_name
	AND com.object_name = col.table_name
	AND com.child_object = col.column_name
WHERE
	col.schema_name = 'X'
	AND col.table_name = 'X'
```

**Comment by dabocla** [comment]
I'll run your queries now.

**Comment by dabocla** [comment]
I have been running your queries.  The bottom one without the joins consistently takes under 20 seconds, which is much more reasonable.  The top ones with the joins, my patience usually runs out around 600 seconds.  The most recent time I allowed it to finish, it took 772 seconds.

Out of curiosity, I did a select count(1) from v_catalog.comments and it took 632 seconds to tell me that there were no comments.

We do have nearly 1k tables in our primary schema, for what it's worth.

**Comment by LonwoLonwo** [comment]
Hello @dabocla 

Please test Vertica table loading performance in our [Early Access](https://dbeaver.io/files/ea/) version. It will be beneficial for us. Table loading performance was improved in this ticket https://github.com/dbeaver/dbeaver/issues/14625

**Comment by LonwoLonwo** [comment]
[Early Access](https://dbeaver.io/files/ea/) version is now available for Mac users.

**Comment by amazzucco48** [comment]
@LonwoLonwo much better! Running somewhere between 250-1500ms. Thanks!

**Comment by LonwoLonwo** [comment]
Sounds awesome!
Thanks for the answer @amazzucco48
