### ISSUE TITLE
Dbeaver UI feature request

### ISSUE THREAD

**Issue by rachelj90** [dbeaver/dbeaver#15453]
Hi...

Am using DBeaver 21.3.2 version,  I'm just looking for column count in the result panel when we query a table which means the dynamically show the result of the below query somewhere in the results panel.

select count(*) from user_tab_columns where table_name = 'tablename';
Am using Oracle DB.
 
Please guide if we already have any settings for such feature.

**Comment by LonwoLonwo** [comment]
Hello @rachelj90 

I'm sorry for not getting back to you sooner.

You can probably use Metadata panel. You can see columns order then and the number of the last column. It starts from 0, so add one more for the correct result.

![2023-02-23 18_03_10-Параметры](https://user-images.githubusercontent.com/45152336/220945648-904d71c3-e005-42d6-8273-3056385c22b4.png)

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it.
