### ISSUE TITLE
DBeaver: Update function/procedure or triggers generate NullPointerException

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#15461]
DBeaver - **Version 21.3.4 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver**
Operating System: **Windows 8.1, Windows 10 Pro**
Database Server: **Microsoft SQL Express 2014, 2016, 2017, 2019**

If you try to update an already stored Function/Procedure or Trigger, a **java.lang.NullPointerException** is generated.

o Open _DBeaver_.
o In the Database Navigator selecte a database function/procedure or trigger.
o View the object source code.
o Make a small change in the vied object source.
o Press **CTRL+S** to save the change.
o An **java.lang.NullPointerException** is generated.

**Comment by ShadelessFox** [comment]
Hello @pdanie,

I can't reproduce your issue against triggers.

Could you please send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by pdanie** [comment]
After further testing, it seems to have to do that I had old _DBeaver_ configuration files.

When I erase the **...\AppData\Roaming\DBeaverData** directory and restarted _DBeaver_, everything worked as expected.

You can close this issue.
