### ISSUE TITLE
regression introduced with: d0740bad01441fe6d0ceb7079bfa0e48fac06d42 (#13916 Add big query catalog change limitation (#15362))

### ISSUE THREAD

**Issue by kai-morich** [dbeaver/dbeaver#15467]
while trying to add a HANA feature, based on latest devel branch, I got this error while executing statements:

      class org.jkiss.dbeaver.ext.hana.model.HANADataSourceInfo cannot be cast to class org.jkiss.dbeaver.ext.generic.model.GenericDataSourceInfo (org.jkiss.dbeaver.ext.hana.model.HANADataSourceInfo is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @23986b98; org.jkiss.dbeaver.ext.generic.model.GenericDataSourceInfo is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @761334e0)
      
with d0740bad01441fe6d0ceb7079bfa0e48fac06d42 a cast was added to GenericExecutionContext.java:

    public boolean supportsSchemaChange() {
        GenericDataSource dataSource = getDataSource();
        final GenericDataSourceInfo info = (GenericDataSourceInfo) dataSource.getInfo(); <<<

but not all plugins derive from GenericDataSourceInfo, some derive from JDBCDataSourceInfo

**Comment by serge-rider** [comment]
Thanks for the bug report and for the investigation 👍

**Comment by uslss** [comment]
verified
