### ISSUE TITLE
Grid - Status Bar - Information of fetched rows

### ISSUE THREAD

**Issue by GuenterSch** [dbeaver/dbeaver#15471]
Hello,

in the Status Bar it is possible to get the following information since Version 21.3.3:
**1 row(s) fetched - 9ms, on 2022-02-12 at 11:25:07**

With Version 21.3.4 the format has changed to a not persistent storable format (Year is missing, Date is not sortable):
1 row(s) fetched - 9ms, on Feb 02 at 11:25:07

I hope you change the date format again to YYYY-MM-DD, or it is possible to set it in the preferences. I use this in my analyse code.

Furthermore, in the dialog "Status details" there should be a button with "Copy" like in the "Persist Changes" dialog.
And it would be very helpful, if there exists a shortcut to insert this information as comment in the "SQL editor".
(Alternatively, there exists a shortcut to copy this information to the clipboard - but the solution above is more helpful).

Thanks to implement this important feature.

BR
Günter
![2022-02-12_DBeaver - Grid Bar](https://user-images.githubusercontent.com/99535516/153708933-b1211a06-dde5-423b-bfca-44063cb7d687.png)

**Comment by GuenterSch** [comment]
Is it possible to change the date format already in one of the next milestones? Would be very nice!

**Comment by ShadelessFox** [comment]
Hello @GuenterSch,

Currently, it's not possible.

We'll add a new preference to change the date format used in the status bar.

**Comment by dbeaver-pm** [comment]
Let's write more verbose info in tooltip. In status bar we need in a short form

**Comment by GuenterSch** [comment]
The date format **2022-07-25 12:48:56** (YYYY-MM-DD) has near the same size like **Jul 25, 12:48:56**.
But we have also the year and we have a standard output format (sortable).
In version 21.3.3 this format was already available.

Bug:
Since Version 22.1.1 it is not possible to open the Status Details. Therefore, I cannot copy this information any longer!
