### ISSUE TITLE
[Feature request] Postgresql : edit roles properties

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#1547]
Hi,

Except if I missed something, for the moment, roles informations in DBeaver are not editable.
It would be nice if we could edit properties, modify values, which would produce and execute the "ALTER ROLE..." SQL command corresponding to what has changed.

Thanks in advance.

Regards,

Cedric

**Comment by linxpatrick** [comment]
Related to this post, I created a new login role but found no way to add the login role to a group role. I added the login role to the group role using a sql command. After doing that, I could see the role was added in the properties of the group role but the Role (name) column was empty for the new role until closing out of DBeaver and opening it again.

**Comment by SIGISLV** [comment]
Is there any plan on this Feature request ?

**Comment by ygoe** [comment]
I see the role I created earlier, but I cannot set a password for it. There's no UI for that. Need to look up the SQL command for that.

**Comment by uslss** [comment]
will be implemented in the scope of #8133
