### ISSUE TITLE
sql error not show while "execute sql in new tab" 

### ISSUE THREAD

**Issue by metalbreeze** [dbeaver/dbeaver#15480]
#### System information: 
- Win10
 

#### Describe the problem you're observing:
when run some sql in new tab, it won't show the error msg. 
 
#### Steps to reproduce, if exist:
1.  connect a database (eg. mysql) ,open an editor.
2.  run `select 1 from dual;`  with  "execute sql in new tab" twice.  now it shows 2 tabs in result panel .
3.  run `select 1 from dualxx;`  with  "execute sql in new tab"  twice, first it show error msg in output correctly , but seceond try, it shows Result 2, no error msg .

**Comment by LonwoLonwo** [comment]
@metalbreeze Hello

What DBeaver version do you use?

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still present, feel free to reopen it.
