### ISSUE TITLE
When viewing PostgreSQL table and want to filter by status (have enum) there's an error

### ISSUE THREAD

**Issue by arthurlomakin11** [dbeaver/dbeaver#15514]
#### System information: 
- Operating system Windows 10
- DBeaver version 21.3.4.202202051448
#### Connection specification:
- Database PostgreSQL

#### The problem:
When viewing PostgreSQL table and want to filter by status (have enum) there's an error
![image](https://user-images.githubusercontent.com/82650905/154279574-d2375198-5838-468c-badf-43a1ea8359ee.png)

#### Steps to reproduce:
Create enum with letters not only lowercase and try to filter by one value in table
#### How to solve this
DBeaver needs to preserve case of letters.
And if enum is `ReceiptStatus`, it needs to be `ReceiptStatus`, but not `receiptstatus `in query.
It needs to be `"` symbol at the start and at the end of enum name, like this: `status IN ('Done'::"ReceiptStatus")`

**Comment by LonwoLonwo** [comment]
Hello @arthurlomakin11 

Thanks for the bug report.
Is your table in the public schema?

**Comment by arthurlomakin11** [comment]
> Hello @arthurlomakin11
> 
> Thanks for the bug report. Is your table in the public schema?

Yes, I have only public schema.

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver version 22.0.0

**Comment by LonwoLonwo** [comment]
Ticket created for another founded issue: https://github.com/dbeaver/dbeaver/issues/15626

**Comment by LonwoLonwo** [comment]
The filter works fine now for public data types in quotes for Data Viewer. DBeaver 22.0.0
