### ISSUE TITLE
SQL Consoles do not honor "Open separate connection for each editor"

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#15519]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.3.4
- Java version: bundled
- Additional extensions: n/a

#### Connection specification:
- Database name and version: Oracle 11
- Driver name: odjbc21
- Do you use tunnels or proxies (SSH, SOCKS, etc)? n/a

#### Describe the problem you're observing:
I started using SQL Consoles for quick queries in place of SQL Scripts a while ago. However I just recently noticed that they do not honor the "Open separate connection for each editor", all consoles run on the "main" connection. Which means that opening multiple consoles to launch long-running query results in them running sequentially instead of parallely.
I cannot say for sure if this is a regression from some previous version or they always worked this way.

**Comment by uslss** [comment]
thanks for the report

**Comment by Matvey16** [comment]
Hello @p91paul maybe you have some specific settings. I was not able to reproduce it

![image](https://user-images.githubusercontent.com/82543000/164424900-ffd239e8-8820-4331-8a06-dc02887c9907.png)

**Comment by p91paul** [comment]
It depends on how you create the sql console.
If you click on the connection on database navigator then open a sql console, it will generate a new connection for that console.

If you open a sql console while you already are on a sql console, or a script, or a table editor, it will use the existing connection of the editor you were in instead of creating a new one.

**Comment by E1izabeth** [comment]
Thank you for explanation.

**Comment by p91paul** [comment]
is this planned for some future release?
