### ISSUE TITLE
Can't resize columns

### ISSUE THREAD

**Issue by jppo** [dbeaver/dbeaver#15516]
Hello,

#### System information: 
- Linux Debian 10.11
- DBeaver version : 21.3.4.202202051448
- Additional extensions : None

#### Connection specification:
- MariaDB 10.4.18
- MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
I can't resize the columns while modifying users, I enclose a screenshot
#### Steps to reproduce, if exist:
Try to modify à user
#### Include any warning/errors/backtraces from the logs
No logs or Backtrace, the program is working, but not showing some useful informations.
![dbeaver_pb_2022-02-16_16-36-23](https://user-images.githubusercontent.com/6616235/154302156-cf906688-a179-46e5-9d54-7e234e721271.png)
Regards
JP P

**Comment by ShadelessFox** [comment]
Hello @jppo,

These columns can't be resized. Perhaps we should make them resizeable.

**Comment by jppo** [comment]
Hello, 
As I maintain some users lists on many machines I need to see all database and tables to give "good" (and sufficient rights to users (batch or tp). 
I had to revert to the precedent release to have my work done. 
So resizable columns are a must for me. 
Regards 
JP P

**Comment by richard-bridgeman** [comment]
Has this been addressed? I cannot make any changes to database without seeing these columns - they are way to small.  How can I work when I dont know which data I am changing?

**Comment by jppo** [comment]
Hello,
The issue is always present in version 22.1.0.
The columns are way too small and I can't resize them.
Regards
JP P
PS : The screen is always like in the image attached to the first message : 
Too small and not resizable.

**Comment by aavileli** [comment]
for me the bottom scrollbar also do not appear. Time to search a non jvm based client

**Comment by iliesh** [comment]
Having the same issue, this is really very annoying when you're trying to adjust some user's permissions.

**Comment by roelandg** [comment]
Same issue, as I'm administering db users couple times a day, this is really frustrating. Using 22.1.1

**Comment by roelandg** [comment]
@ShadelessFox  I see this is now labeled as a feature request. However, this is actually a bug. After my update to 22.1.1, this issue occurred for me. It could be that I skipped some releases, so can't recall which was the latest version this was not in issue.
