### ISSUE TITLE
Connection to database problem (TCP/IP error)

### ISSUE THREAD

**Issue by LucasAvril** [dbeaver/dbeaver#15527]
**System Information:**
- Operating system : Linux, Ubuntu 20.04.3 LTS Hosted on VMWare
- DBeaver 21.3.4
- Main System Windows 10 (Windows Server 2019)

**Connection Specification:**
- Database on SQL Server

**The problem:**

![image](https://user-images.githubusercontent.com/77778239/154441598-6bdd3617-ad4f-454d-a108-b16b21cd9908.png)

**Description:**

When I'm trying to connect DBeaver on my virtual machine to my SQL Server I get an error.

**Comment by uslss** [comment]
Did you enable TCP/IP protocol for your MSSQL instance?
https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-or-disable-a-server-network-protocol?view=sql-server-ver15
https://support.smartbear.com/collaborator/faq/how-to-enable-tcp-ip-in-sql-server-configuration-m/

**Comment by LucasAvril** [comment]
Yes, it is ON in SQL Server Configuration Manager.
![image](https://user-images.githubusercontent.com/77778239/154487779-e4a8a70d-e63d-42bc-8a2d-48fc5630d9d0.png)
