### ISSUE TITLE
[Feature Request] Function or Procedure parameters' auto-completion  feature on package editor

### ISSUE THREAD

**Issue by ceyhunnabiyev** [dbeaver/dbeaver#1552]

**Comment by ceyhunnabiyev** [comment]
This feature exists  in PLSQL developer for Oracle. Any answer for this?

**Comment by serge-rider** [comment]
We are working on SQL editor enhancements (semantic SQL parser). Till then this feature won't be implemented.

**Comment by p91paul** [comment]
@serge-rider did you do some of this in 5.1? I noticed parameters being added as bind variables when I autocompleted a procedure today...thanks!

**Comment by serge-rider** [comment]
Yep.
Now if you complete some procedure then all parameters will be pre-generated.
