### ISSUE TITLE
Optimize Oracle metadata read

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#15538]
Oracle metadata (especially constraints and foreign keys) performance is awful on some Oracle version.
We need to optimize it.

**Comment by serge-rider** [comment]
We will enable metadata read optimization. It consists of the following session parameters:
```sql
ALTER SESSION SET "_optimizer_push_pred_cost_based" = FALSE;
ALTER SESSION SET "_optimizer_squ_bottomup" = FALSE;
ALTER SESSION SET "_optimizer_cost_based_transformation" = 'OFF';
```

For Oracle 10.2 + we will enable optimizer feature
```sql
ALTER SESSION SET OPTIMIZER_FEATURES_ENABLE='10.2.0.5'
```

Query optimization parameters are set for metadata connection only. In case it is disabled optimization will be enabled for  the Main connection (which is used for data read queries).

You can disable these optimizations in connection settings or in preferences:
![image](https://user-images.githubusercontent.com/6398845/154645814-a6fb7150-431c-4b4e-88f2-dfcc9662a1c9.png)

You can enable metadata connection here:
![image](https://user-images.githubusercontent.com/6398845/154645905-1dc1c582-9553-4ca9-8111-47fb21446dae.png)

**Comment by Matvey16** [comment]
Verified
