### ISSUE TITLE
Is there a keyboard shortcut to focus Filter in Database Navigator?

### ISSUE THREAD

**Issue by binodkalathil** [dbeaver/dbeaver#15536]
**Is your feature request related to a problem? Please describe.**
Folks using keyboard heavily will prefer to focus this filter to type in the table name and other things. While it is currently smooth after focusing this filter but we really need to use mouse to get the cursor in the filter textbox. I checked if there are any keyboard shortcuts available but couldn't find any.

**Describe the solution you'd like**
A keyboard shortcut taking the user right into the above filter so that they can start typing. If there is an existing text the keyboard shortcut must select all the text automatically for convenience(for adding to the text with `end/home` key and all).

**Describe alternatives you've considered**
Using mouse

**Additional context**
Nothing

**Comment by uslss** [comment]
@binodkalathil probably, you could use Ctrl+Alt+Shift+T shortcut. Does it resolve your issue?
![image](https://user-images.githubusercontent.com/31996417/154916472-d8513971-7deb-4081-b96f-801227485352.png)

**Comment by binodkalathil** [comment]
@uslss That focuses data editor filter not the Database Navigator Filter. However I was able to get what I need from here `Ctrl + Shift + D`:

![image](https://user-images.githubusercontent.com/4425339/155950457-2a038045-45fe-4e96-a816-64ab6bdf6280.png)


It allows us to select Database Objects in the current connection only and uses '<searchText>%' instead of '%<searchText>%' for filtering. This window seem to have all the required keyboard navigations 👍 

However, adding a keyboard shortcut to Database Navigator Filter still seems like a good thing to me as that will be showing results from all the connections and that will be the default place users will be looking at when they have that sidebar activated.

**Comment by uslss** [comment]
If I understand you correctly, an object filter shortcut also could be assigned In Preferences. You could bind needed shortcut and change when condition to DB navigator context in preference
![image](https://user-images.githubusercontent.com/31996417/159472331-fa58e3af-c2d5-4b95-bf88-d8e13e8c9c64.png)

**Comment by binodkalathil** [comment]
@uslss That doesn't seem to work 🤔 

What I am saying is that we need to focus on this text box with a keyboard shortcut

![image](https://user-images.githubusercontent.com/4425339/159475872-17a26737-fa98-44ea-914f-fed16fef3d91.png)

**Comment by blandong** [comment]
@binodkalathil Did you figure it out? I was looking for the same.

**Comment by DKhalil** [comment]
@uslss as @binodkalathil mentioned, the shortcut in question is for the database filter, which would be really useful to have.

**Comment by ay4t** [comment]
I really hope there is a shortcut feature that automatically focuses on the filter textarea, similar to other database clients that can easily search for tables/views with a shortcut or by typing in the navigator.
