### ISSUE TITLE
SQLite. An error occurs when open Sequences tab for predefined SQLite connection

### ISSUE THREAD

**Issue by vermilion2020** [dbeaver/dbeaver#15537]
#### System information: 
- Operating system: Windows 10
- DBeaver version: 21.3.4

#### Connection specification:
- SQLite default predefined connection

#### Describe the problem you're observing:
An error occurs when opening Sequences tab in Metadata editor or trying to expand it in DB navigator

Steps to reproduce:
1. Expand SQLite default connection in DB navigator
2. double click on Sequences node / expand Sequences node

Actual: An error toast message appears and an error message is displayed in metadata editor tab, an error icon is shown in DB navigator near Sequences node 
![image](https://user-images.githubusercontent.com/75521323/154638995-ef980919-b09a-4e37-b0c5-c6ede8b9c837.png)

Expected: folder is opened without an error and there is no content inside

**Comment by ShadelessFox** [comment]
Hello @vermilion2020,

Is your issue reproducible against DBeaver? The attached screenshot features CloudBeaver.

**Comment by kseniiaguzeeva** [comment]
Please see the video

https://user-images.githubusercontent.com/51405061/154654239-df980535-1359-4a6c-9dde-4d86869efe25.mp4

**Comment by ShadelessFox** [comment]
It's not a bug. The internal table we're reading sequences from is not created until we use `AUTOINCREMENT` for the first time.

The message describes what went wrong. Perhaps we could suppress it, but do we really want to?

**Comment by kseniiaguzeeva** [comment]
The error didn't appear in earlier versions.

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by uslss** [comment]
verified
