### ISSUE TITLE
[Exasol] CSV Import - simple varchar string wrongly mapped as geometry column

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#15540]
#### System information: 
- Win10 
- DBeaver CE 21.3.5

#### Connection specification:
- Exasol

#### Describe the problem you're observing:

Wrong data type mapping for varchar value when iport from CSV to a new table.

DDL of table that csv data is exported from:
```sql
CREATE TABLE TESTAS.NEWTABLE_1 (
		COLUMN1 VARCHAR(50) UTF8,
		COLUMN2 BOOLEAN,
		COLUMN3 DOUBLE NOT NULL,
		COLUMN4 DECIMAL(18,0),
		COLUMN5 DATE
);
```

CSV data:
```csv
"COLUMN1","COLUMN2","COLUMN3","COLUMN4","COLUMN5"
qlwk wdf,false,12.3,,2022-02-17
sdk,,3.14,13345,2022-02-17
,true,0.01,1,
sefg lf,false,17.0,7,2022-02-17
```

Target DDL when import from CSV:
![image](https://user-images.githubusercontent.com/43252954/154657020-82feb738-347c-4822-9683-07de1bb3cfcb.png)

#### Steps to reproduce, if exist:
In context menu of tables node click Import data
Select CSV file format
Try to import in new table CSV mentioned above
Then you can see wrong target DDL and if you try to import data you get this error
#### Include any warning/errors/backtraces from the logs
![image](https://user-images.githubusercontent.com/43252954/154657091-f716e3eb-5391-4144-a0a3-f696097e4973.png)

**Comment by emironovDB** [comment]
Works as expected (we restore column mappings from previous dt run)
