### ISSUE TITLE
Columns with aliases cannot be edited in the ResultSet

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#15544]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.3.5 EA

#### Steps to reproduce, if exist:
Execute a select statement with a column alias (e.g. in SQLite `select ArtistId as abc from Artist`)

**Expected**: the columns can ve edited
**Actual result**: the columns with aliases canot be edited.

![dbeaver_J37s4BVAdi](https://user-images.githubusercontent.com/51405061/154684710-6c203944-3163-4eb3-9151-6db28cbc7dc5.png)

**Comment by LonwoLonwo** [comment]
Can't reproduce against in DBeaver 22.3.1

![2022-12-26 12_52_17-Window](https://user-images.githubusercontent.com/45152336/209534722-27b64d84-2a9d-4e32-8f8a-37cfced52ce5.png)
