### ISSUE TITLE
Data Transfer: Recreate mapping is reset at mapping step in case user move backward than forward

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#15546]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.3.5

#### Steps to reproduce, if exist:
1. Start import to table
2. At mapping step choose Recreate mapping option. 
3. Press Back button
4. Press Next button

Actual result: mapping is reset:
![dbeaver_KG4eJO1fv3](https://user-images.githubusercontent.com/31996417/154693984-820075c2-8026-4ab7-8dd5-2328751068a9.gif)

**Comment by DariaMarkaryan** [comment]
Verified

**Comment by DariaMarkaryan** [comment]
Verified
