### ISSUE TITLE
DDL not include default value type sequence: nextval ('sequence_name':regclass) OR DBeaver bad identify datatype ? real datatype is integer, but DBeaver identify serial4

### ISSUE THREAD

**Issue by peterprvy** [dbeaver/dbeaver#15559]
#### System information: 
- Windows 10 64 Bit
- DBeaver 21.3.4

#### Connection specification:
- PostgreSQL
- Server: PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1)
- Driver: PostgreSQL JDBC Driver 42.2.20
- Not using tunnels or proxies

#### Describe the problem you're observing:

Generated DDL not include default value type sequence: nextval ('sequence_name':regclass)

#### Steps to reproduce, if exist:

Databases -> Tables -> <table_name> -> Properties -> DDL
Databases -> Tables -> <table_name> -> right click -> Generate SQL -> DDL

Columns:

![image](https://user-images.githubusercontent.com/36068077/154811408-582a386c-d604-48ab-bde5-7801fbf3961b.png)

DDL:

![image](https://user-images.githubusercontent.com/36068077/154811422-dea4b54a-4629-4ab3-8c8b-4e0640b1f8c5.png)

**Comment by ShadelessFox** [comment]
Hello @peterprvy,

The `SERIAL` types are implicitly autoincremented by default. The default value may not be specified for such attributes.

**Comment by peterprvy** [comment]
@ShadelessFox 

Intellij Idea identify column as integer, not serial:

![image](https://user-images.githubusercontent.com/36068077/154856380-04376bf3-245e-415b-a7e7-2c379d381754.png)

DDL:

![image](https://user-images.githubusercontent.com/36068077/154856335-aabc8036-56f3-4155-a605-2264d97aed4f.png)

**Comment by ShadelessFox** [comment]
Integers do require the `nextval` expression as their default values.

**Comment by peterprvy** [comment]
@ShadelessFox 

pgAdmin identify columns as integer, not serial

![image](https://user-images.githubusercontent.com/36068077/154856512-5d84da47-f5b6-4bff-b0f7-16d677e8b361.png)


please reopen issue

**Comment by peterprvy** [comment]
@ShadelessFox 

Dbeaver badly found data type, Pleasr reopen issue

**Comment by ShadelessFox** [comment]
It's a feature. The original type is indeed an integer.

If the attribute contains the `nextval` expression as its default value, DBeaver changes its type to `serial`.

**Comment by peterprvy** [comment]
@ShadelessFox 
But there is no mention of this in DDL and when creating a table in another database I forget to create a seqeunce.

**Comment by ShadelessFox** [comment]
The `SERIAL` type is a sugar that PostgreSQL provides.

You can try creating a new database containing an attribute of type `SERIAL`, and it will erase it down to `int` with `nextval` as its default value. A sequence is created automatically.
