### ISSUE TITLE
Order transaction isolation levels in the transaction manager from least to most strict

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#15551]
Currently, the list looks like this:
![Screenshot 2022-02-18 183324](https://user-images.githubusercontent.com/26031301/154713032-cf9c8018-4072-4cf9-bf82-f87bdcb647e9.png)

It is strange because Read committed is more strict than Read uncommitted.

**Comment by flambchap** [comment]
Reordered.

**Comment by DariaMarkaryan** [comment]
Verified
