### ISSUE TITLE
Feature Request: customize cancel button colour

### ISSUE THREAD

**Issue by mikebridge** [dbeaver/dbeaver#15558]
**Is your feature request related to a problem? Please describe.**

The cancel button is bright green---this is the international colour for "GO", not "CANCEL".  As a result I keep accidentally clicking on the wrong button.

**Describe the solution you'd like**

The Cancel button should be a neutral colour

![green_button](https://user-images.githubusercontent.com/213273/154774144-fac2fce7-0d6d-43b8-a0af-feee12fe53e3.png)

**Comment by ShadelessFox** [comment]
Hello @mikebridge,

It's an operating system's default color for **default** dialog buttons. We can't change its color.
