### ISSUE TITLE
DBeaver disconnects from DB automatically after some time.

### ISSUE THREAD

**Issue by kumaran-IV0IV** [dbeaver/dbeaver#15554]
#### System information: 
- Windows 10
DBeaver Version - 21.3.4
- Java 8
- Additional extensions :  None

#### Connection specification:
- MySQL 5
- JDBC 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No 

#### Describe the problem you're observing:
DBeaver disconnects from DB automatically after some time.
when I try to execute a query after some time of inactivity like 5 minutes, the application disconnects itself.
So, I have to invalidate the db everytime before executing a query. or else, The query takes much time to respond

#### Steps to reproduce, if exist:

Open DBeaver. execute a query. wait for like 5 - 10 mins. just run the same query again

#### Include any warning/errors/backtraces from the logs

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/8098477/dbeaver-debug.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/8098480/dbeaver-debug.log)

**Comment by michal-bartak** [comment]
Check DB logs for disconnects issued by database (idle connection, idle transaction whatever)

**Comment by uslss** [comment]
@michalk-k Could you try to change the keep-alive value in connection properties to non-null and check if it fixes your issue?
![image](https://user-images.githubusercontent.com/31996417/154914754-15aaf7ac-b08e-4834-8c25-16d3dce2a158.png)

**Comment by michal-bartak** [comment]
@kumaran-IV0IV the advice from @uslss is directed to you rather than me.

**Comment by kumaran-IV0IV** [comment]
> @michalk-k Could you try to change the keep-alive value in connection properties to non-null and check if it fixes your issue? ![image](https://user-images.githubusercontent.com/31996417/154914754-15aaf7ac-b08e-4834-8c25-16d3dce2a158.png)

Thanks for ur response.
This is worked, Even though I tried this many times, Now only it worked out.. I've no idea

**Comment by jeffshumphreys** [comment]
Not working for me. A regression? 
![image](https://github.com/dbeaver/dbeaver/assets/47931319/7b6daf3b-8a1e-43ee-8b48-14641e5e39a5)
![image](https://github.com/dbeaver/dbeaver/assets/47931319/62de1b9e-7cd4-4900-bd7d-482723f53fe0)

Version: Community Edition 23.3.4.202402041841.  This behavior only started recently.

**Comment by zeornelas** [comment]
> Not working for me. A regression? ![image](https://private-user-images.githubusercontent.com/47931319/304536313-7b6daf3b-8a1e-43ee-8b48-14641e5e39a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTcwMTEsIm5iZiI6MTcwODAxNjcxMSwicGF0aCI6Ii80NzkzMTMxOS8zMDQ1MzYzMTMtN2I2ZGFmM2ItOGExZS00M2VlLThiNDgtMTQ2NDFlNWUzOWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE3MDUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOGY4MDQyNTk5ZTY1ZTUyMGZhNmJmNmFjODU5ZDMwYWNkODc0NGQ3NGRjZGI0MTUxZDY0YWI0NGU5NzAwNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-oDYhsoReKuwD36hy7Wyf5UQfQyqe3imj9hEMKgkyxs) ![image](https://private-user-images.githubusercontent.com/47931319/304536446-62de1b9e-7cd4-4900-bd7d-482723f53fe0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTcwMTEsIm5iZiI6MTcwODAxNjcxMSwicGF0aCI6Ii80NzkzMTMxOS8zMDQ1MzY0NDYtNjJkZTFiOWUtN2NkNC00OTAwLWJkN2QtNDgyNzIzZjUzZmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE3MDUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZTUxNjNkOGUxNzQ0M2NlOTExMjNjZmNhZDhjZjMzMTkyNzRhMWVjMTE5NDYyZmQ1OGE3ZmZjNmRjNDRhNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w372tBXWH6OrKs-jC3CdHdJkDksrgT8aybZneLjxLQw)
> 
> Version: Community Edition 23.3.4.202402041841. This behavior only started recently.

I'm having the same issue. On a MariaDB development database. It closes automatically even though the Keep-Alive is set to 0. This started to happen recently for me too. I've Community Edition Version 23.3.4.202402041841.

**Comment by pjmeier** [comment]
Started happening to me too recently on Postgres connections. Same version (23.3.4.202402041841).

**Comment by budsz** [comment]
Connection issue on `Version 23.3.4.202402060628` running on `Debian 12.5`, suddenly disconnected from the server when the computer is idle. All SQL expression filter gone. How to keep alive connection & keep history SQL Exp filter? -- Thanks

**Comment by dlroy88osu** [comment]
Windows 11 pro -   DBeaver	23.3.4.202402041841 

I have not changed anything in my settings and now it is killing my connections when idle... No other versions have had that issue before.

**Comment by avnp16** [comment]
I have not changed anything in my settings and now it is killing my connections when idle... No other versions have had that issue before.

**Comment by zeornelas** [comment]
@serge-rider Can you please have a look into this thread and maybe reopen it? I'm afraid this hasn't been noticed given that this issue is closed. Or should we open a new issue for the problem we have been facing?

EDIT: nevermind, I just realised this is also being addressed here: https://github.com/dbeaver/dbeaver/issues/22776.
