### ISSUE TITLE
Column description not included in csv export

### ISSUE THREAD

**Issue by mquqi** [dbeaver/dbeaver#15552]
System information: 
- DBeaver version 21.3.4

Connection specification:
- infor-compass-jdbc-2020-09.jar

Problem:
Column description is not exported csv file
- bpid is exported to csv
- Business Partner is not exported to csv

![Column description](https://user-images.githubusercontent.com/99980113/154713706-bdd7285e-c7e5-4085-a648-ce8a1522200b.JPG)

**Comment by ShadelessFox** [comment]
Hello @mquqi,

You have to enable it in the data transfer wizard:

![image](https://user-images.githubusercontent.com/35821147/154746181-53cddad7-b609-4662-ae84-73986d73285c.png)

Let me know if you have additional questions.

**Comment by mquqi** [comment]
Thanks for the quick response!
Unfortunately already tried that, description never comes to csv, only label.

**Comment by ShadelessFox** [comment]
Unfortunately, I can't reproduce your issue.

Table:
![java_FjPPcs0mn4](https://user-images.githubusercontent.com/35821147/154769518-0b76e323-d091-4f4e-a48c-48daf89db375.png)

CSV:
![notepad++_X8TyGuZxec](https://user-images.githubusercontent.com/35821147/154769529-c776c53c-fefa-49ad-9de4-d8e1a0abe2cf.png)

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still present, feel free to reopen it.
