### ISSUE TITLE
Error when exporting function

### ISSUE THREAD

**Issue by ArchDemons** [dbeaver/dbeaver#15563]
#### System information: 
- Operating system Windows 10
- DBeaver version 21.3.5.202202200327

#### Connection specification:
- Database Postgres 11

#### Describe the problem you're observing:
There is a problem when we generate script for a schema with a function that returns a table. ALTER FUNCTION and GRANT ALL strings are formed incorrectly (returned table fields including into function arguments list). An error occurs while running the script there is no such functions.

e. g.
```
CREATE OR REPLACE FUNCTION orderapi.getfqtycolor_tbl(idpgds numeric DEFAULT NULL::numeric,
         dpbegin date DEFAULT CURRENT_DATE, dpend date DEFAULT CURRENT_DATE)
     RETURNS TABLE(id numeric, scolor text, fqty_plan numeric, fqty_fromsap numeric, fqty_fact numeric,
          fqty_brak numeric, fqty_fromzadel numeric, fqty_tozadel numeric)

ALTER FUNCTION orderapi.getfqtycolor_tbl(in numeric, in date, in date, numeric, text, numeric,
     numeric, numeric, numeric, numeric, numeric) OWNER TO postgres; -- wrong function signature
GRANT ALL ON FUNCTION orderapi.getfqtycolor_tbl(in numeric, in date, in date, numeric, text,
     numeric, numeric, numeric, numeric, numeric, numeric) TO postgres; -- wrong function signature
```
#### Steps to reproduce, if exist:
 - create fucntion with arguments and TABLE as return value
 - export schema with created function into sql file
 - check lines with ALTER FUNCTION and GRANT ALL commands

**Comment by LonwoLonwo** [comment]
Hello @ArchDemons 

Thanks for the bug report

**Comment by brankoradovanovic-mcom** [comment]
This affects DB Navigator right click -> Delete too, it won't work as the generated DDL is incorrect. (Or, if it works, it will drop the wrong function.)

**Comment by mopsik10** [comment]
actual in DBeaver version  22.0.0.202203060510 also

**Comment by ShadelessFox** [comment]
Fixed.

**Comment by uslss** [comment]
verified
