### ISSUE TITLE
When press "Ctrl+S" the texteditor go to the  end

### ISSUE THREAD

**Issue by JiaOkay** [dbeaver/dbeaver#15562]
#### System information: 
- System infomation
- Deepin linux 20.4 base on debian 10 , kernel:  5.15.6-amd64-desktop
- DBeaver version
- DBeaver 21.3.5.202202200327
- Additional extensions 
- null

#### Connection specification:
- Database name and version
- Oracle 11g R2
- Driver name
- JDBC Thin Client
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
- NO

#### Describe the problem you're observing:
When the line number of text exceeds the display area, I modified old lines data,and press ctrl+s,the textedit window will go to the last line.  it appears only after  update Dbeaver to 21.3.5.202202200327,It was normal before.
#### Steps to reproduce, if exist:

just look this gif
The key is displayed at the bottom of the picture

![录屏_DBeaver_20220221121742](https://user-images.githubusercontent.com/38833358/154888429-5688b61a-b8a0-451e-aaaa-0c9426e7548c.gif)

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
verified

**Comment by rlunaro** [comment]
It had happened to me also, with the latest available version (21.3.5.2022022200327).
