### ISSUE TITLE
Snowflake authenticator option is not available 21.3.5 but worked fine 21.3.4

### ISSUE THREAD

**Issue by brvaland** [dbeaver/dbeaver#15567]
System information: 
- MacOS 11.6.4
- DBeaver 21.3.5

Connection specification:
- Snowflake 

#### Describe the problem you're observing:
I have upgraded to DBeaver 21.3.5 from 21.3.4 and noticed snowflake authenticator free text field is changed to drop down menu which does not allow is to enter our identity provider url and forces us to use external browser - SSO. 

In version 21.3.4 it allowed us to enter identity provider example https://xxx.okta.com and username and password in the field, this automatically fetched token without opening browser window but it is not working 21.3.5

Can someone advise if this will be fixed in next patch version ?

**Comment by serge-rider** [comment]
Fixed (custom authenticators config now available)

**Comment by brvaland** [comment]
Hi @serge-rider, Thanks for your help.

**Comment by Matvey16** [comment]
Verified
