### ISSUE TITLE
Table input filter in data tab is blocked if DBeaver fetches data

### ISSUE THREAD

**Issue by BuZZ-dEE** [dbeaver/dbeaver#15576]
I can not enter a filter value in input field on the data tab, if DBeaver fetches data.

**Comment by ShadelessFox** [comment]
Hello @BuZZ-dEE,

Are you talking about this exact input field?

![image](https://user-images.githubusercontent.com/35821147/155331079-ebdff0eb-ea79-4b6a-a274-3a761e34cdaf.png)

**Comment by BuZZ-dEE** [comment]
@ShadelessFox yes

**Comment by ShadelessFox** [comment]
I see, okay. Thanks.

**Comment by ShadelessFox** [comment]
Will be fixed in #19272

**Comment by BuZZ-dEE** [comment]
@ShadelessFox this is already fixed and is different to #19272. Why did you tag it as duplicate?

**Comment by ShadelessFox** [comment]
These issues can't be resolved separately, so it's better to link them and close one as a duplicate.

**Comment by BuZZ-dEE** [comment]
@ShadelessFox this doesn't needs to be resolved it is already resolved. I just linked it to the other issue, because of the input field image.

**Comment by ShadelessFox** [comment]
Then I don't see any issues with closing it.
