### ISSUE TITLE
[Exasol] Can't see schema and table names in metadata panel 

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#15577]
#### System information: 
- Win11
- DBeaver CE 21.3.5

#### Connection specification:
- Exasol

#### Describe the problem you're observing:
Catalog, schema and table names aren't visible in panel metadata
![image](https://user-images.githubusercontent.com/43252954/155019286-de500fbe-192f-4bdf-a384-f98bbf1421cc.png)

**Comment by emironovDB** [comment]
Work as expected
