### ISSUE TITLE
Changes to Bind Parameter Window Broke Value Tabbing Capabilities

### ISSUE THREAD

**Issue by Xylandor** [dbeaver/dbeaver#15572]
#### System information: 
- OS:  MacOS Big Sur v11.4
- DBeaver version:  21.3.5.202202200327
- Additional extensions:  None

#### Connection specification:
- Local installation of MariaDb
- Driver name: MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
The latest release (21.3.5.202202200327) added the multi-line value editor to the Bind Parameter(s) window, but by doing so, it broke the ability to tab to the next parameter's value for editing. In previous versions, I could enter a value, press tab and it would set focus on the next parameter's value field (highlighting all text). Now I have to manually use the mouse to set focus on the next value. I use bind parameters all the time and many of my queries have several of them, so this can become very time consuming when having to switch back and forth between keyboard and mouse. 

#### Steps to reproduce, if exist:
1. Create a query with more than one bind parameter.
2. Enter the first parameter's value and try using TAB to set focus on the next parameter's value field. You can't. 

#### Include any warning/errors/backtraces from the logs
No errors produced.

**Comment by Matvey16** [comment]
Verified
