### ISSUE TITLE
DBeaver数据库怎么设置字体大小？具体位置*****客户端工具如何设置数据库-下面的属性-列那字体字体的大小怎么变大？

### ISSUE THREAD

**Issue by zhyanjuncn** [dbeaver/dbeaver#15583]
客户端工具怎么设置 数据库-下面的属性-列那一行字体的大小？

**Comment by ShadelessFox** [comment]
Hello @zhyanjuncn,

Please describe your issue in English according to our issue templates.

**Comment by flambchap** [comment]
Hello @zhyanjuncn. I tried to translate your message using Google Translator, but unfortunately, the translation is incomprehensible. Can you please rephrase it? Additional pictures would be great as well.

**Comment by nathanielongyiitak** [comment]
DBeaver数据库怎么设置字体大小？具体位置*****客户端工具如何设置数据库-下面的属性-列那字体字体的大小怎么变大？

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still present, feel free to reopen it.
