### ISSUE TITLE
DBeaver not in Launch Menu

### ISSUE THREAD

**Issue by william-mason** [dbeaver/dbeaver#15585]
#### System information: 
- Operating system (distribution) and version
  ```
  Distributor ID:	Ubuntu
  Description:	Ubuntu 20.04.4 LTS
  Release:	20.04
  Codename:	focal
  ```
- DBeaver version
  `DBeaver Community                             io.dbeaver.DBeaverCommunity                           21.3.5           stable`
- Additional extensions
  none

#### Connection specification:

> not applicable

#### Describe the problem you're observing:

* After installing `dbeaver` using flatpak
  `flatpak  install flathub dbeaver`
* DBeaver does Not show in the Ubuntu desktop launch menu
* I am alomst certain I installed this on another Ubuntu computer and dbeaver  is in the menu.

I would appreciate a link to show me how to add dbeaver to the launch menu.

* I expect a GUI tool to be added to the launch menu
  * I have attempted a number of variations on the install
  * Nothing so far has resulted in a menu entry on the main launch menu

#### Steps to reproduce, if exist:

1. install dbeaver flatpak:  `flatpak  install flathub dbeaver`
   * Select: `app/io.dbeaver.DBeaverCommunity/x86_64/stable` 
2. Press menu/start button
3. No menu entry for DBeaver

#### Include any warning/errors/backtraces from the logs

none

**Comment by flambchap** [comment]
Hi @william-mason. Unfortunately, I cannot reproduce the issue. Could you please try reinstating the application (and upgrading to the latest version simultaneously)?

**Comment by william-mason** [comment]
* seems to work OK after latest install
