### ISSUE TITLE
Failed to export CSV, last screen freezes and cannot be closed nor canceled

### ISSUE THREAD

**Issue by terremoth** [dbeaver/dbeaver#15582]
#### System information: 
- Operating system Lubuntu 20.04 LTS
- DBeaver version: 21.3.5
- Additional extensions: none, just downloaded DBeaver from website

#### Connection specification:
- Database name and version  
$ mysql --version
> mysql  Ver 15.1 Distrib 10.5.15-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- Using through SSH

#### Describe the problem you're observing:
The EXPORT to CSV is not working: not finishing or finish loading to the file (the csv file is not even being created)
![image](https://user-images.githubusercontent.com/11032344/155032568-470d3a2a-c285-4ada-94a5-947c585d223b.png)

In this screen if you try to cancel the operation, the red square button just disables and nothing happens also

I made this query (which has 45 results only)
```sql

select o.user_id, f.user_name, f.last_order, o.created_at, o.order_status, o.order_payment_methods_id as payment_method
from orders o 
join (
	select 
		-- o.id as orderId, 
		max(o.id) as last_order
		-- ,o.user_id 
		, CONCAT(users.name, ' ', users.last_name) as user_name  
		from orders o 
		join users on users.id = o.user_id 
		group by o.user_id
	) f 
on o.id = f.last_order 
-- join users u on users.id = o.user_id
where o.order_payment_methods_id = 8
and (o.created_at BETWEEN '2022-02-06 00:00:00' and '2022-02-21 00:00:00') 
and o.order_status in (2,3,5,7,8,9,10)
;
```
#### Steps to reproduce, if exist:
Just executing this query, select all items on the little list (with ctrl+a), right click on the whole selected list and then click on Export menu option, then it freezes in the last part

#### Include any warning/errors/backtraces from the logs
No related logs were generated

## UPDATE:
it worked after I reconnect and re-made the process!  
Maybe the error needs to be fixed with an algortihm, something like: "try to reconnect first if not connected before try to export".
Also, despite being only 45 results, I decrease the maximum results from 10000 to 1000, Idk if this helps anyway.

**Comment by ShadelessFox** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.

Also, it would be handy if you managed to reproduce the issue again so it would appear in logs.

Thank you.

**Comment by terremoth** [comment]
> No related logs were generated

If it happens again, I will see if it generates some log, then I paste here

**Comment by ShadelessFox** [comment]
Thanks.

**Comment by terremoth** [comment]
The only info I remember was previous messages reconnecting to the ssh server.

I will try to see in this dir: $XDG_DATA_HOME/DBeaverData/workspace6/.metadata
and I will try to reproduce again this friday

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still present, feel free to reopen it.
