### ISSUE TITLE
DB Full-Text Search limited at 5000 tables, unable to search/load more in the tree

### ISSUE THREAD

**Issue by scrignar** [dbeaver/dbeaver#15584]
#### System information: 
- Windows 10 Pro 64bit
- DBeaver version 21.3.4.202202051448

#### Connection specification:
- PostgreSQL 11.9
- PostgreSQL JDBC Driver [42.2.5]

#### Describe the problem you're observing:
When attempting to conduct a full-text search in a DB that has ~10000 tables, the tree in the databases field truncates at 5000 tables. When clicking the checkbox for the Tables node, it will not return with a full check-mark, but rather a square indicating that only partial of all the child nodes are selected. 

![image](https://user-images.githubusercontent.com/100178235/155058661-d34f01f3-b9c2-4b10-ba2d-7e17f0580091.png)

This is despite that when scrolling down the tree, all nodes are selected, including the overflow/roll-up "More" node representing the remaining 5000 tables.

![image](https://user-images.githubusercontent.com/100178235/155058933-4ae5619b-526c-44b7-8d9c-61653bf8d71f.png)

Clicking/Double-clicking on the "More" node will not load the remaining tables into the tree (in contrast to the DB Navigator, which will do that).  Nothing occurs, the tree remains static.

Completing a Full-Text Search in this state will result in only the 5000 visible nodes being searched, the remaining 5000 tables are not searched.

Deselecting the initial 5000 nodes, and selecting only the "More" node results in the Search button remaining inactive, so searching only those tables is not possible.

![image](https://user-images.githubusercontent.com/100178235/155059296-731a9e1e-96b1-4423-a65f-9f3e89c8e021.png)

#### Include any warning/errors/backtraces from the logs
Inspected all logs, no relevant entries present in them.  (None of the timestamps correlate to when attempting this)

**Comment by LonwoLonwo** [comment]
Hello @scrignar 

Thanks for the bug report.

As a workaround, you can change the acceptable number of fetched elements in the Preferences -> User Interface -> Navigator.

Note for future development: Schema compare didn't work also. (No DoubleClickListener?)

![2022-02-22 08_49_08-DBeaver Ultimate 21 3 5 - language](https://user-images.githubusercontent.com/45152336/155071796-7a35a370-d99a-4d60-8e6e-a5a093071b00.png)

**Comment by scrignar** [comment]
@LonwoLonwo thank you for the workaround, much appreciated!
