### ISSUE TITLE
21.3.5 -- New scripts now position cursor to the end of script BUG?

### ISSUE THREAD

**Issue by luiscarlosbolanhos** [dbeaver/dbeaver#15598]
#### System information: 
- Operating system (distribution) and version : Windows 11 64 Bits
- DBeaver version : DBeaver 21.3.5
- Additional extensions: None

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Include any warning/errors/backtraces from the logs

Hello there,

When I UPDATE my current script, not a new one, the current one, and save the script because I have made some changes, it goes to the end of the script. So I lost my current file position!

It is very unconfortable, I generaly use big scripts... so it is not nice, after saving any change, have to look for the old position to run the script or made another correction.

If you want to make this new change or feature, please make it an option, I want to disable it, but I havent found where!

Thanks for the help and correction!

**Comment by nicchristeller** [comment]
I'm experiencing the same. A (slightly painful) workaround is to use the "Previous edit location" action after each save, which moves the cursor back to your last change.

**Comment by luiscarlosbolanhos** [comment]
> Previous edit location

Thank you very much, it is a great idea, I don´t know about this feature, Control-Q save my day... 

I hope this bug will be fixed in the next realease.

Thanks a lot!

**Comment by ShadelessFox** [comment]
Hello @luiscarlosbolanhos @nicchristeller,

The issue was fixed in #15562 and will be available in the next version (22.0.0).
