### ISSUE TITLE
Can't import large CSV into Windows

### ISSUE THREAD

**Issue by stumbi** [dbeaver/dbeaver#15594]
Using Windows 10 (Home)
DBeaver 21.3.5
PostgreSQL 14

I try to import csv Files of ~1GB or above into a table, but it crashes after 150.000 rows. 
The import window remains open, but nothing appears to happen. After restarting DBeaver imported
said rows, but nothing else.

Thanks in advance

**Comment by ShadelessFox** [comment]
Hello @stumbi,

Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.

Thank you.

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still present, feel free to reopen it.
