### ISSUE TITLE
Filtering by tablename in datasource dialog no longer works

### ISSUE THREAD

**Issue by Khartir** [dbeaver/dbeaver#15591]
#### System information: 
- Linux Mint 19.3
- DBeaver version 21.3.5

#### Describe the problem you're observing:
The last update broke the filter function in the source container selection window when importing data from a different database. Previously the filter would work on the tables inside of databases/connections (like it still does in the main window). Now it works on connections instead. Filtering connections might also be useful but it is now completely impossible to filter tables.

#### Steps to reproduce, if exist:
- right click on a table
- select "import data"
- select table as data source
- open select source container window
- try searching for table

**Comment by LonwoLonwo** [comment]
Hello @Khartir 

Thanks for the bug report.

**Comment by serge-rider** [comment]
Fixed.
Now it is possible to use filter settings in dialogs too

**Comment by Matvey16** [comment]
Filter is not applied to data sources that were disconnected prior to the opening of the dialog.

![dbeaver_O8Csce7pei](https://user-images.githubusercontent.com/82543000/155501957-cbd995cd-2914-4a8b-a248-f948ab5eb43e.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
