### ISSUE TITLE
DBeaver ignores fragments in links

### ISSUE THREAD

**Issue by marlarius** [dbeaver/dbeaver#15599]
#### System information: 

Manjaro Linux
DBeaver version 21.3.3.202201242151

#### Connection specification:
SQL Lite

#### Describe the problem you're observing:
DBeaver automatically shows a small url arrow in columns containing urls. This is a nice feature that makes links clickable and open them in the default browser.

However, the fragment part (after the hash #) is ignored. So the link https://example.com/test#123 will open https://example.com/test in the browser. Since many single page applications (SPA) rely on fragment links, these might not work when opened from DBeaver.

#### Steps to reproduce, if exist:
Insert https://example.com/test#123 in any text column and click on the little url arrow.

**Comment by ShadelessFox** [comment]
Hello @marlarius,

I can't reproduce your issue. The fragment is present after opening the URL in the browser.

Could you please download the latest version and see if the issue is gone there?

**Comment by marlarius** [comment]
Hi @ShadelessFox,

I have found that the problem only applies to file links (file://). I just used the example domain because it was easier to reproduce and I didn't realize it would make a difference.

So, to reproduce:

Make a file called example.html and open the file in your browser. Add a fragment like #123. Copy the full url from the address bar. In my case I get file:///home/marlar/Desktop/example.html#123.

Insert the url in a record in a table and save it. Now click on the url arrow. The browser will open the file without the fragment.

Note that the file must exist in order for DBeaver to open it at all. That's why I used the example.com domain.

I cannot easily install a newer version as DBeaver is installed via the repository. But now knowing that the problem only exists for file links, I think you will see it too.

My use case is that I have a database of thousands of local html files which I want to open when clicking. I use Chrome's text fragments to highlight certain points of interest on the pages. Since fragments are not sent to the browser, I have to copy-paste the urls instead.

**Comment by flambchap** [comment]
I've successfully reproduced it on the latest CE version.

**Comment by ShadelessFox** [comment]
After some investigation, it looks like the URI scheme does not even define the term _segment_.

I guess that browsers ignore the scheme and use the general URI format, but OSes follow the specification.

Therefore, we can't do anything about that, unfortunately.

See https://en.wikipedia.org/wiki/File_URI_scheme#Format

**Comment by marlarius** [comment]
> I guess that browsers ignore the scheme and use the general URI format, but OSes follow the specification.

I am not so sure about that. If I run the command line 

`xdg-open "file:///home/marlar/Desktop/example.html#123"`

it opens just fine in my default browser including the fragment. So if DBeaver uses a system call, it should work where the OS supports it. And it seems that at least my Linux distro supports it.

Well, I might take a look in the source code. Do you by chance know where I should look?

**Comment by ShadelessFox** [comment]
We use `org.eclipse.swt.program.Program#launch(java.lang.String)` for launching external programs.

We don't specify which application it should use to open it. It lowers down to an OS-specific logic which we can't affect.
