### ISSUE TITLE
Issue on to Format SQL option

### ISSUE THREAD

**Issue by carmelocarrillo** [dbeaver/dbeaver#15605]
At Edit menu, Format SQL option (CTRL + Shift + F):
When the table names that contains digits + letters, the formatter SQL converts them to table name with space.

`SELECT * FROM 2021data;`
converts to

```
select
	*
from
	2021 data;
``` 
<<<< MISTAKE (space)

thanks.

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by ShadelessFox** [comment]
Hello @carmelocarrillo,

The identifier `2021data` is invalid. SQL requires identifiers to begin with a letter, not a digit, so we don't handle this case.

What database are you using?

**Comment by carmelocarrillo** [comment]
MySQL allows these identifiers for table names. Our business have multiples
projects with them since years.

**Comment by ShadelessFox** [comment]
I see. Thank you for the response.

As a workaround, you can surround it with `` ` `` like so: `` `2021data` ``.
