### ISSUE TITLE
Reoccurrence of undesired auto-scrolling of SQL editor to bottom upon query execution

### ISSUE THREAD

**Issue by rotorboy** [dbeaver/dbeaver#15607]
#### System information: 
- Operating system (distribution) and version - MacOS 12.1
- DBeaver version - 21.3.5.202202200327
- Additional extensions

#### Connection specification:
- Database name and version - MariaDB
- Driver name - MariaDB connector
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:

when I "Ctrl-enter" a query, the SQL editor auto-scrolls to the bottom, rather than staying on the line of SQL just executed.

#### Steps to reproduce, if exist:

create SQL editor with enough text in it to require scrolling. Select a query to run that is far enough up the text that will result in scrolling. "Ctrl-enter" a query, and the SQL editor will auto-scroll to the bottom, rather than staying on the line of SQL just executed.

**Comment by ShadelessFox** [comment]
Hello @rotorboy,

This issue was fixed in #15562 and the fix will be available in the next version (22.0.0).

**Comment by rotorboy** [comment]
Thanks.

Any ETA on 22.0.0?

**Comment by ShadelessFox** [comment]
The 22.0.0 version is postponed to March 7.

We also have an early access version, and we are going to republish it tomorrow.
