### ISSUE TITLE
Error thrown by "Calculate total row count" following MySQL SELECT query

### ISSUE THREAD

**Issue by owendw1** [dbeaver/dbeaver#15600]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04.6 LTS
- DBeaver version: 21.3.5.202202200327
- Java version: SE Runtime Environment (build 1.8.0_231-b11)
- Additional extensions: None

#### Connection specification:
- Database name and version: All MySQL databases
- Driver name: MySQL JDBC Type 4 driver for MySQL 8.0.28
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing
After issuing a SELECT query to a MySQL database, pressing the "Calculate total row count" button causes a "Load row count" error to be thrown. This has only started occurring since updating to DBeaver 21.3.5.202202200327. It only occurs with MySQL databases (whether local or remote) and not PostgreSQL or SQLite databases.

#### Steps to reproduce, if exist:
Issue a SELECT query to any MySQL database and once the result set is returned click the "Calculate total row count" button.

#### Include any warning/errors/backtraces from the logs
Error message:
![image](https://user-images.githubusercontent.com/11296160/155234229-30e00a65-a572-4954-b164-dfb373c60fa7.png)

Error log:
[DBeaver Calculate total row count error.log](https://github.com/dbeaver/dbeaver/files/8120714/DBeaver.Calculate.total.row.count.error.log)

**Comment by Matvey16** [comment]
@owendw1 Thank you for the report, we will work on that.
The button to count rows in resultset of sql editor sends incorrect query `SELECT count() FROM table` if the connection is to MySQL or MariaDB

**Comment by LonwoLonwo** [comment]
Fixed for MySQL, MariaDB, and VQB.

**Comment by Matvey16** [comment]
Verified

**Comment by Nanzitos** [comment]
This fix is available ?

**Comment by LonwoLonwo** [comment]
Hello @Teasercry 

This fix will be available in DBeaver version 22.0.0.  The release is planned for March 3.
