### ISSUE TITLE
Dbeaver UI not displaying the latest constraint details

### ISSUE THREAD

**Issue by nathanielongyiitak** [dbeaver/dbeaver#15602]
#### System information: 
- Operating system (distribution) and version: Windows 10 Home Single Language
- DBeaver version: Dbeaver 21.3.5

#### Connection specification:
- Database name and version: MySQL 8
- Driver name: MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
Ran a laravel php migration to set a foreign key from "cascade on delete" to "set null on delete", after running the migration, UI still displays cascade while the actual data queried shows set null (modified).

#### Steps to reproduce, if exist:
1. Have a table with foreign key "on update cascade" and "on delete cascade".
2. Open dbeaver to verify the database foreign keys section is showing cascade for on update/delete.
2. Create and migration to drop foreign key and readd foreign key (modified with "on update set null" and "on delete set null".

#### Include any warning/errors/backtraces from the logs

![Actual_data_showing_set_null](https://user-images.githubusercontent.com/44321176/155295946-56ba1380-9987-4e18-977c-aa047853e250.png)
![Uploading Still_showing_cascade.png…]()

**Comment by ShadelessFox** [comment]
Hello @nathanielongyiitak,

Have you tried reconnecting to your database?

Thanks.

**Comment by nathanielongyiitak** [comment]
@ShadelessFox Yea tried closing dbeaver and reopening it, disconnected database and reconnected, still showing cascade instead of set null.

Thanks for the reply.

**Comment by LonwoLonwo** [comment]
Hello @nathanielongyiitak 

What driver version do you use?
You can check it in the Connection Settings -> Test Connection

**Comment by nathanielongyiitak** [comment]
![image](https://user-images.githubusercontent.com/44321176/155479831-9ea6f424-b913-4d4c-813a-06d1f3930b52.png)
Not sure if I'm finding it right but here's a screenshot of my driver manager, MySQL 5 probably.

**Comment by LonwoLonwo** [comment]
Please check it in the Connection Settings -> Test Connection

![2022-02-24 10_43_00-DBeaver Ultimate 21 3 5 - _localhost_ Script-26](https://user-images.githubusercontent.com/45152336/155480249-735ecca9-f523-4e2e-9584-ecd5c7814bb5.png)

![2022-02-24 10_43_18-DBeaver Ultimate 21 3 5 - _localhost_ Script-26](https://user-images.githubusercontent.com/45152336/155480251-21a0c8dd-cfd4-4b87-8f24-9672f5117e69.png)

**Comment by nathanielongyiitak** [comment]
Hey sorry something came along and I forgot to update, here's a screenshot of it
![image](https://user-images.githubusercontent.com/44321176/155664722-8faaa007-3d06-4b12-b69a-5471ce7baa00.png)
Thanks

**Comment by LonwoLonwo** [comment]
Thanks for the answer @nathanielongyiitak 

The issue you described has already been discussed here: https://github.com/dbeaver/dbeaver/issues/14107

I close this ticket as a duplicate and put an original ticket in the development queue.
