### ISSUE TITLE
Allow password change on login if forced

### ISSUE THREAD

**Issue by hski-github** [dbeaver/dbeaver#15617]
#### System information: 
- Windows
- DBeaver Community Version 21.3.4.202202051448

#### Connection specification:
- SAP HANA 2
- JDBC

#### Describe the problem you're observing:
If password is required to be reset due to password expire, this cannot be done by DBeaver because initial login is not possible .

#### Steps to reproduce, if exist:
As an admin, reset the password for a certain user. When the user now tries to login, he is required to reset the password. This cannot be done via DBeaver. I have to log in via SAP HANA Studio.

**Comment by Skydiveroid** [comment]
Thank you for the idea.

**Comment by kai-morich** [comment]
might have similar rootcause as #14064

**Comment by hski-github** [comment]
Here is the original error message. Is forced password reset possible for other database types like Oracle or MS SQL? 

`SQL-Fehler [414] [HY000]: SAP DBTech JDBC: [414]: user is forced to change password: alter password required for user`

![image](https://user-images.githubusercontent.com/1921015/165039094-531cf42b-30f4-474a-b328-f8785fb81eb9.png)

**Comment by LonwoLonwo** [comment]
Changing the forced password works for Oracle in DBeaver.

And for some other databases: https://github.com/dbeaver/dbeaver/wiki/Change-current-user-password

**Comment by kai-morich** [comment]
same as #22206

**Comment by kai-morich** [comment]
I am working on this feature
