### ISSUE TITLE
Scrollbar moves to bottom

### ISSUE THREAD

**Issue by vivekpaytail** [dbeaver/dbeaver#15619]
Hi Team

After the latest update, whenever I save SQL file by pressing ctrl+S the Scrollbar moves to the bottom automatically which a but annoying.

**Comment by ShadelessFox** [comment]
Hello @vivekpaytail,

This issue was fixed in #15562 and the fix will be available in the next version (22.0.0).

**Comment by vivekpaytail** [comment]
Thanks for the information
