### ISSUE TITLE
Cursor of editor window jumping after saving

### ISSUE THREAD

**Issue by de-sgen** [dbeaver/dbeaver#15611]
#### System information: 
- MacOS 11.6
- DBeaver version 21.3.5.202202200327

#### Connection specification:
- PostgreSQL 14
- postgresql-42.2.20
- No tunnels, proxies.

#### Describe the problem you're observing:
In the editor, after saving the changes to a .sql file (e.g. updating a query or the code of a stored procedure), the cursor jumps automatically to the end of file without any reason.
The jump was detected only after explicitly saving and never during the typing process.

#### Steps to reproduce, if exist:
1. Open a SQL script connected with a data source (e.g. selecting a connection -> SQL Editor -> New SQL script).
2. Add a block of code that does not fit completely the vertical margin of the editor window.
3. Move the cursor to the top of the editor window.
4. Save (e.g. File -> Save/Save As).
5. The cursor is moved to the end of the block of code.

#### Include any warning/errors/backtraces from the logs
No exception reported in .log.

**Comment by ShadelessFox** [comment]
Hello @de-sgen,

This issue was fixed in https://github.com/dbeaver/dbeaver/issues/15562 and the fix will be available in the next version (22.0.0).

**Comment by de-sgen** [comment]
Thanks @ShadelessFox.
