### ISSUE TITLE
Certificate Issue GlobalSign

### ISSUE THREAD

**Issue by rwalke** [dbeaver/dbeaver#15612]
**Is your feature request related to a problem? Please describe.**
A fresh installation of DBeaver 21.3.5 on Windows 10 works but gives strange Java errors opening the example database.

**Describe the solution you'd like**
Open https://valid.r3.roots.globalsign.com/ and https://dbeaver.io in Edge browser helps to get the missing certificates.
I think this is not the optimal solution.

**Comment by andrelinslima** [comment]
Can you post the log for the "strange java errors"?

I could not reproduce the issue. Example database is local to the client, so SSL certificate should not be an issue. 
I'm imagining that you are talking not talking about https://dbeaver.io either (as they don't use google certificates), but actually about some message from maven about maven central website.

Their SSL certificate was renewed in September 7, 2021 already. Dbeaver isn't supposed to ignore certificate errors or add extra ca root authorities on behalf of the user. This defeats the purpose of SSL.

If you are in an enterprise, your company should provide you with root CAs to trust, and if you are an individual, either windows updates or your browser maker should update their root CA when needed. and each website is responsible to keep their own certificate valid

![image](https://user-images.githubusercontent.com/33740641/156182747-e6c1692d-b687-41f8-aaac-ad276adb5426.png)

**Comment by rwalke** [comment]
Attached is an example picture with the error.

It happens when I test it on a very fresh system.
The system did not know the root certificate GlobalSign Root CA - R3 Serial 04000000000121585308a2 by default.

I don't know if my browser should do this by default.


--
This mail has been sent through the MPI for Demographic Research.  Should you receive a mail that is apparently from a MPI user without this text displayed, then the address has most likely been faked. If you are uncertain about the validity of this message, please check the mail header or ask your system administrator for assistance.

**Comment by andrelinslima** [comment]
The message didn't come with any attachments (or the attachments via email are not supported for github issues).
Root CAs usually come with windows and can be updated with new patches. Some browsers and softwares (like java) have their own list, which needs to be updated by the manufacturer. Others will use the system list, like chrome and IE. I'm running windows 10 and had no problem with maven.
You should check if you have pending windows updates. and then assuming the errors you are having is coming from maven certificate, try accessing https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc11/ and check if the ssl works after updating

**Comment by rwalke** [comment]
Sorry for the missing messages.
Error messages:
1 (open the example database):
“Network error
Reason:
Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target” and
“Can't create driver instance
  Error creating driver 'SQLite' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.sqlite.JDBC'
  Error creating driver 'SQLite' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.sqlite.JDBC'
    org.sqlite.JDBC
    org.sqlite.JDBC”

Solution: Click once on https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc11/ to get ssl work.

2 (Check for updates)
“Cannot obtain version information. Perhaps the network connection is down?
Reason:
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target”

Solution: Click once on https://dbeaver.io/ to get ssl work.


I think it is has been solved. Thank you.

--
This mail has been sent through the MPI for Demographic Research.  Should you receive a mail that is apparently from a MPI user without this text displayed, then the address has most likely been faked. If you are uncertain about the validity of this message, please check the mail header or ask your system administrator for assistance.
