### ISSUE TITLE
Unable to suppress Upgrade Prompt

### ISSUE THREAD

**Issue by anique9999** [dbeaver/dbeaver#15616]
Hi, 

#### Describe the problem you're observing:
To disable the upgrade prompt, I placed the file "org.jkiss.dbeaver.core.prefs" in specified location 
[ %HOME%\.dbeaver4\.metadata\.plugins\org.eclipse.core.runtime\.settings] after installation. But after opening the application, I'm still getting the update prompt. 

Can you please tell why I'm receiving the upgrade prompt even after placing that file?

![image](https://user-images.githubusercontent.com/90675448/155523130-5f7404fc-4f00-4a48-a193-98a958ccee9b.png)

**Comment by andrelinslima** [comment]
That's the wrong location for the dbeaver workspace. Use:
%userprofile%\AppData\Roaming\DBeaverData\workspace6\.metadata\.plugins\org.eclipse.core.runtime\.settings\org.jkiss.dbeaver.core.prefs

**Comment by anique9999** [comment]
Hi @andrelinslima,
I was following the same path for Dbeaver community that was mentioned in https://github.com/dbeaver/dbeaver/issues/3299, `%HOMEPATH%.dbeaver4\.metadata\.plugins\org.eclipse.core.runtime\.settings\` and I tried using the path you mentioned, but I could still the update prompt.

**Comment by uslss** [comment]
Did you try to disable Automatic updates check in preferences?
![image](https://user-images.githubusercontent.com/31996417/161497919-8ae097ac-4a70-4ff1-a04d-8171054dd723.png)
