### ISSUE TITLE
Unaccurate value saving

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#15620]
When editing (adding) column - there is such dialog. 
Type text to column comment and do not press enter, but click on another grid element (e.g. datatype). Text will disappear. This is ugly behaviour, value must be saved not only by enter but by focus loss too.

OS: Any
DBeaver version: 21.3.5

![Снимок экрана от 2022-02-24 19-21-32](https://user-images.githubusercontent.com/11477081/155564972-59ea330c-683e-425e-9a70-f4cf08bd090e.png)
g

**Comment by LonwoLonwo** [comment]
Hello @plotn 

Thanks for the bug report. 

Interesting thing - click under the description field or on the Column name field works correctly.
