### ISSUE TITLE
[SQL Server] DDL has duplicate statements for unique constraint creation

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#15635]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 22.0.0

#### Connection specification:
- Database name and version Microsoft SQL Server 2019

#### Describe the problem you're observing:
Generated DDL includes the creation of the index twice

#### Steps to reproduce, if exist:
1. Create a table with a unique constraint
2. Open DDL tab in table properties

**Expected:** Generated DDL can be copied and executed in a script

**Actual:** DDL includes a separate statement to create an index as well as a parameter inside the create statement

```sql
-- BikeStores.dbo.sysdiagrams definition

-- Drop table

-- DROP TABLE BikeStores.dbo.sysdiagrams;

CREATE TABLE BikeStores.dbo.sysdiagrams (
	name sysname COLLATE Cyrillic_General_CI_AS NOT NULL,
	principal_id int NOT NULL,
	diagram_id int IDENTITY(1,1) NOT NULL,
	version int NULL,
	definition varbinary(MAX) NULL,
	CONSTRAINT PK__sysdiagr__C2B05B619C2E2514 PRIMARY KEY (diagram_id),
	CONSTRAINT UK_principal_name UNIQUE (principal_id,name)
);
CREATE UNIQUE NONCLUSTERED INDEX UK_principal_name ON BikeStores.dbo.sysdiagrams (principal_id, name);
```

**Comment by LonwoLonwo** [comment]
Related to https://github.com/dbeaver/dbeaver/issues/14754
