### ISSUE TITLE
Incorrect handling of UTF8 in databricks

### ISSUE THREAD

**Issue by stegus64** [dbeaver/dbeaver#15630]
#### System information: 
- Windows 10
- DBeaver Version 21.3.3.202201221033

#### Connection specification:
- Databricks SQL Endpoint
- SimbaSparkJDBC42-2.6.22.1040

You can download the driver here:
https://docs.databricks.com/dev-tools/dbeaver.html

#### Describe the problem you're observing:

Incorrect display of utf8-encoded strings

#### Steps to reproduce, if exist:

create or replace table test1 as 
select 'Tärning', 'Övrigt'
;

select * from test1
;

![image](https://user-images.githubusercontent.com/51655419/155679942-77d5b256-2358-485f-8da3-92139e1b6491.png)

As you can see the strings are displayed with incorrect encoding. It seems like the strings are incorrectly utf8-encoded twice.

Please note that it is very easy to create a free test environment for databricks

https://databricks.com/try-databricks

**Comment by ShadelessFox** [comment]
Hello @stegus64,

It looks like the driver determines the default encoding from the `file.encoding` Java property.

You might try setting it explicitly to `UTF-8` in the `config.ini` file after `-vmargs` line, like so:

```
...
-vmargs
-Dfile.encoding=UTF-8
...
```

Please let me know if the issue persists.

**Comment by stegus64** [comment]
Yes, setting file.encoding to UTF-8 helps with this issue. Now it works as expected.

However, changing file.encoding in config.ini also affects how any sql scripts containing non-ascii characters are interpreted. Before the change sql scripts were assumed to be in ISO-8859-1, after the change they are assumed to be in UTF-8.

It is a little bit unfortunate that to display data correctly you need to make a change that affects the whole program.

As far as I know the encoding used in parquet files is always UTF8. It seems that when interpreting the data from databricks you should always interpret it as UTF8. 

In an ideal world you should always interpret this data correctly regardless of the setting of file.encoding.

But anyway, your suggested workaround is good enough for me at the moment.

Thanks

**Comment by ShadelessFox** [comment]
Although the database itself may handle UTF-8 very well, its JDBC driver does not explicitly specify an encoding for strings when constructing them from the byte sequence the database sent and, therefore, the encoding defined by the `file.encoding` property is used instead.

Unfortunately, I don't think we can do anything about it.

**Comment by stegus64** [comment]
ok, I understand.
The workaround is good enough for me.

I close this issue now.

**Comment by G-Ziradov** [comment]
Hello, I have a problem with loaded Data Base (MariaDB) which includes Cyrillic letters. I have Macbook Pro 13' 2017 with MacOS Ventura and Dbeaver Version 22.3.4
<img width="651" alt="Screenshot 2023-04-06 at 18 00 20" src="https://user-images.githubusercontent.com/94197202/230419315-c221f6cf-d212-482e-ab95-74ee6521029a.png">

So far, I already tried to edit DB connection and inserted "characterEncoding [UTF-8]" and checked Preferences/General/Workspace but without results.
Would you advise me how to display correctly Cyrillic value from Data Base.

<img width="719" alt="Screenshot 2023-04-06 at 17 53 17" src="https://user-images.githubusercontent.com/94197202/230417351-09b7322e-5b00-4497-a498-c8e67ddf318b.png">
<img width="845" alt="Screenshot 2023-04-06 at 17 57 37" src="https://user-images.githubusercontent.com/94197202/230418796-2a8b5175-ba57-43cd-8adf-cd02880c19b4.png">
