### ISSUE TITLE
Column with alias is read-only and doesn't have read-only label in the ResultSet

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#15632]
#### System information: 
- DBeaver version  21.3.5.202202181141

#### Connection specification:
- Database name and version PostgreSQL
#### Steps to reproduce, if exist:
1. Execute a select statement with a column alias (e.g. for PostgreSQL db1. pagila.public: `select address_id, district as bcd from public.address a`)
2. Try to edit a column with an alias

**Expected**: the column with the alias can be edited or read-only label is displayed on the column.
**Actual result** : the column editing isn’t possible and the column doesn't have the read-only label.

https://user-images.githubusercontent.com/51405061/155683058-8ac859ff-8408-4609-918e-75be261bd873.mp4

**Comment by serge-rider** [comment]
The problem w2as in editing of columns wth alias. Edit failed during save (`column not found`).

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
This breaks the filtering for Oracle resultset
![explorer_aTX8hTeLwj](https://user-images.githubusercontent.com/82543000/155773820-259263ad-87c3-4d53-97ed-824f0af21916.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
