### ISSUE TITLE
Numeric field inside custom type displayed as numeric(1000,999)

### ISSUE THREAD

**Issue by radudh** [dbeaver/dbeaver#15644]
#### System information: 
- Windows 10
- DBeaver 21.3.5.202202200327

#### Connection specification:
- Postgres 10
- Driver name: PostgreSQL
- no SSH or tunnels

#### Describe the problem you're observing:
A custom type created with SQL and that contains a numeric field (without precision or scale) it is displayed in the source part of the type as numeric(1000,999) 

#### Steps to reproduce, if exist:
Open SQL editor and run:

```
create type core.xxx_test_type as (
	numix numeric
);
```

Then open the newly created type, go to the source tab and look at the numeric field:

![image_2022-02-25_175757](https://user-images.githubusercontent.com/10977587/155746610-304b7b53-6c01-46b4-ab7c-86a44e9f4662.png)

**Comment by LonwoLonwo** [comment]
Hello @radudh 

This is a side effect of this issue: https://github.com/dbeaver/dbeaver/issues/13309
For the better fractional digits limits definition, we must know numeric bounds. 
[The documentation](https://www.postgresql.org/docs/current/datatype-numeric.html) says that 1000 - is the maximum numeric precision. And data type scale must be less than precision.

**Comment by neilnsmith** [comment]
Note that it's the same behavior for "decimal" as "numeric".

**Comment by samuelguesnier** [comment]
I have this issue.
Version 22.1.0.202206051253
 
it cause this error : PostgreSQL: SQLstate: 22003 numeric overflow

Solved this issue by altering the type afterward

**Comment by neilnsmith** [comment]
> I have this issue. Version 22.1.0.202206051253
> 
> it cause this error : PostgreSQL: SQLstate: 22003 numeric overflow
> 
> Solved this issue by altering the type afterward

Yes, choosing (1000,999) as the scale and precision is ridiculous.  It means that if you recreate your types from the code generated by dbeaver, you won't be able to subsequently store any value >= 10.  If they were going to set some arbitrary values (which it shouldn't), then something like (1000,500) would have at least been better
