### ISSUE TITLE
Issue Connecting to Oracle 

### ISSUE THREAD

**Issue by chrisanu922** [dbeaver/dbeaver#15647]
#### System information: 
- MacBook Pro (2016) Intel Core i7 - macOS Monterey Version 12.1
- DBeaver version 21.3.5
- Java: 
17.0.2 (x86_64) "Oracle Corporation" - "Java SE 17.0.2" /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home
1.8.321.07 (x86_64) "Oracle Corporation" - "Java" /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

#### Connection specification:
- Database: Oracle 
- Driver name: ojdbc8.jar
- Behind corporate network (Zscaler) – already imported certificates (cacerts) from local Java

#### Describe the problem you're observing:

Trying to connect to Oracle databases – after inputting credentials continue to receive this error:

> Network error
> Reason:
> Network unavailable:
> javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

And also this:

> oracle.jdbc.OracleDriver

I've downloaded and installed Apache Maven 3.8.4:
```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /Users/christophersanurccl.com/Documents/apache-maven-3.8.4
Java version: 17.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.1", arch: "x86_64", family: "mac"
```

<img width="745" alt="Cursor_and_Edit_Driver__Oracle_" src="https://user-images.githubusercontent.com/27229033/155772888-1898663e-b114-44c0-854a-6d5abd252303.png">

**Comment by andrelinslima** [comment]
The error you are having is not when connecting to oracle, it is from maven trying to download the driver and receiving a ssl certificate error.

You don't need to download maven, eclipse (and dbeaver) has a version of maven embeeded. The JRE used by dbeaver is the one OpenJDK 11 provided in the jre folder of dbeaver, you can import the certificate there for it to be trusted or like mentioned in the README.md, replace this folder contents with your own jre.

Assuming you have configured the proxy under Windows -> Preferences, it should work properly then.

As you already have the ojdbc8.jar locally, and even edited the driver definition, you can also delete the blue lines (which are the maven references) and dbeaver will stop trying to download it from maven, and should use your local copy. 

Even though the basic functionality is on ojdbc8.jar, some features might not be available without the additional jars referenced.
