### ISSUE TITLE
Cursor is moved to the end of editor after save (Ctrl +S) and execute (Ctrl + Enter)

### ISSUE THREAD

**Issue by carlosspohr** [dbeaver/dbeaver#15645]
#### System information: 
- Operating system: Windows 10 64 bits
- DBeaver version: 21.3.5.202202200327
- Additional extensions: no extensions or plugins installed.

#### Connection specification:
- Database: MySQL 5.7 in localhost
- Driver name: Mysql connector 8.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no, just a direct connection to localhost MySQL server.

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/637767/155753314-c2901fc9-5336-4317-8965-ac84aecb90d1.png)
**Red set:** current cursor position.
**Blue set:** where cursor will be moved.

When you are editing in higher section of editor and you edit (red set in image) your SQL command, save it and after execute it, the cursor will be moved at end of your editor, as marked by blue set at image above.

#### Steps to reproduce, if exist:

Add some empty lines or some sql commands in editor...go higher area (not last line), edit it, save it and execute it...the cursor will be moved to the end.

This bug doesn't occurs with you only save or execute sql command repeatedly.

**Comment by ShadelessFox** [comment]
Hello @carlosspohr,

This issue was fixed in https://github.com/dbeaver/dbeaver/issues/15562 and the fix will be available in the next version (22.0.0).

**Comment by carlosspohr** [comment]
I looked for opened issue and didn't found this one.

Thanks @ShadelessFox!
