### ISSUE TITLE
Possible memory leak / excessive thread count

### ISSUE THREAD

**Issue by rotorboy** [dbeaver/dbeaver#15643]
#### System information: 
- Operating system (distribution) and version - MacOS 12.1
- DBeaver version - Version 21.3.5.202202200327
- Additional extensions 

#### Connection specification:
- Database name and version - MariaDB
- Driver name - MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - SSH

#### Describe the problem you're observing:

When dbeaver starts, it is using approximately 500MB of RAM and 56 threads. Within a couple of hours of running with intermittent use, memory consumption grows to about 1GB and 101 threads. 

Four SQL editor tabs open, only two of which are actively being used (ie executing SQL and retrieving recordsets). 
Two DB connections, one through SSH, the other local. 

Recordsets retrieved are small (approximately 300 or so records)

**Comment by Skydiveroid** [comment]
Hello @rotorboy,

Could you please send me the thread dump? 

You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump.

**Comment by rotorboy** [comment]
Not sure what you mean by thread dump or where to find how to do that. 

-Avi

**Comment by Matvey16** [comment]
As stated in the link above (https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump) it creates a file with more information about threads, I recorded a simple gif on how it can be done. The file will be created in current cmd directory
![dbeaver_CuyvEN8Ujc](https://user-images.githubusercontent.com/82543000/157431031-1d2d8560-6547-41dc-8486-f292c1967ab4.gif)

**Comment by rotorboy** [comment]
How long should I leave jstack running, and how do i terminate the app? eg kill -SIGHUP, other?

-Avi

**Comment by Matvey16** [comment]
You don't need to it will terminate itself in a few seconds

**Comment by uslss** [comment]
There has been no update on the issue for a long time.  If it is still reproducible - feel free to reopen it
