### ISSUE TITLE
In the filter-per-column pane, show the total number of distinct values

### ISSUE THREAD

**Issue by BoxingLaunch** [dbeaver/dbeaver#15656]
**Is your feature request related to a problem? Please describe.**
When I open the filters pane on a column from the table view page, I want to see how many distinct values there are in that column. That is to say, I want to see how many rows appear in the aforementioned filter pane.

**Describe the solution you'd like**
At the bottom of the aforementioned filter pane, I want to see a comment like "5 distinct values".

**Describe alternatives you've considered**
Could try to match Power BI's distribution-per-column charts. They're really good.

**Additional context**
Example screenshot: 
![image](https://user-images.githubusercontent.com/94591609/155920437-5038625d-aee2-4442-b84a-4753933fff0e.png)

**Comment by ShadelessFox** [comment]
Hello @BoxingLaunch,

Thank you for the idea. It might be handy.

**Comment by ShadelessFox** [comment]
Implemented:

![image](https://user-images.githubusercontent.com/35821147/164269579-a114c1b6-6be5-4e52-aa67-ac06c5cbe54f.png)

**Comment by BoxingLaunch** [comment]
Looks great, thanks!
