### ISSUE TITLE
Background color for editor tabs

### ISSUE THREAD

**Issue by cemccccc** [dbeaver/dbeaver#15657]
Is there any way to change the color of an active tab in dbeaver? 

![image](https://user-images.githubusercontent.com/83164656/155934465-641aeb1d-14d4-47fd-a421-4569982fa462.png)

**Comment by Skydiveroid** [comment]
Could you please try resetting the workspace? You can find the instructions here: 
https://dbeaver.com/docs/wiki/Reset-workspace/
