### ISSUE TITLE
Error when trying to save view, after modifying it in sql

### ISSUE THREAD

**Issue by dbojan** [dbeaver/dbeaver#15653]
#### System information: 
- Operating system (distribution) and version windows 10
- DBeaver version 21.3.5
- Additional extensions

#### Connection specification:
- Database name and version sqlite
- Driver name odbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
After modifying view in sql, and clicking on 'preview changes and save', then click on 'persist', error message appears:
Cannot save v_name: [SQLITE_ERROR] SQL error or missing database (table v_name already exists)

Expected is to save modifications to the view, like in other programs such as Sqlite studio.
#### Steps to reproduce, if exist:
-right click on view
-select 'view view'
-click on definition
-modify sql code
-click on 'preview changes and save',  then click on 'persist'
-error message appears:
-Cannot save v_name: [SQLITE_ERROR] SQL error or missing database (table v_name already exists)
-view is not saved.

Tried Alter view, also displays the message:
[SQLITE_ERROR] SQL error or missing database (near "VIEW": syntax error)

possible workaround:
change create view to save to temp view: CREATE VIEW v_name2
right click on views, refresh.
delete v_name,
rename v_name2 to v_name.

**Comment by LonwoLonwo** [comment]
Hello @dbojan 

Thanks for the bug report.

We can add "recreate actions" for generic views or remove the ability to change views definition.

**Comment by dbojan** [comment]
> We can add "recreate actions" for generic views

I am sorry, I do not understand what "recreate actions" means.

Great, if it can help to save the edited view.

**Comment by uslss** [comment]
verified
