### ISSUE TITLE
Can not change dictory/schema.

### ISSUE THREAD

**Issue by SSSDNSY** [dbeaver/dbeaver#15654]
#### System information: 
- Operating system (distribution) and version
  win10
- DBeaver version
  
![image](https://user-images.githubusercontent.com/15624361/155910288-7294f105-2b7e-4ded-aa30-4642a0a526d7.png)

- Additional extensions

#### Connection specification:
- Database name and version
 
![image](https://user-images.githubusercontent.com/15624361/155910328-9718a411-ed80-45d7-bdfe-14a478a4509e.png)

#### Describe the problem you're observing:

![image](https://user-images.githubusercontent.com/15624361/155910356-9072f92c-8b48-4948-b7b9-9b5a717f959b.png)
![image](https://user-images.githubusercontent.com/15624361/155910387-f747a934-9715-4c79-86d2-41d76736ff3b.png)
![image](https://user-images.githubusercontent.com/15624361/155910400-b2a0f712-36e5-4fc4-a042-2a70dd9c2c49.png)

can not change the schema ?

#### Steps to reproduce, if exist:

- connect postgresql14
- new script file 
- change the schema but just the default schema choiced after changed .

**Comment by Matvey16** [comment]
@SSSDNSY Can you please provide more specific steps to reproduce the issue? Am I doing something differently on the attached video?

![dbeaver_8xAX6k2NUX](https://user-images.githubusercontent.com/82543000/157431583-460e15dd-c7cd-48c8-bf8f-b36df1d83139.gif)

**Comment by SSSDNSY** [comment]
In your video,  you can change schema with the pop  window, but I only can change it with the mouse right click on DB name ( set as default ),just like below picture
![image](https://user-images.githubusercontent.com/15624361/158499428-d7d99903-4678-4500-941f-4caf4d6c2adf.png)

because, as I said before, I can't change the schema with the  pop window in below picture . whatever I user mouse left click or right.
![image](https://user-images.githubusercontent.com/15624361/158499965-08c14541-4777-4a21-8ac3-130ba862c677.png)

emmm ... may be it my mistake or some operation , but I can not know、 find and show it to you...sorry 。

**Comment by SSSDNSY** [comment]
@Matvey16

**Comment by SSSDNSY** [comment]
The dbeaver is very useful software for everyone. addtionally,how to contribute code for dbeaver or solve some problem for community ，would you give me some suggestion ? (emm... ignore my poor English level  )
thanks ~

**Comment by Destrolaric** [comment]
@SSSDNSY Sorry, for the long waiting, this dialog allows you to select the default schema by clicking firstly to catalog, and when double-clicking on the schema. Please reply if it helped.

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual, feel free to reopen it.
