### ISSUE TITLE
[PostgreSQL] Error in the view source comment when creating a new one

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#15660]
#### System information: 
- Win11
- DBeaver CE 22.0.0

#### Connection specification:
- PostgreSQL, Cockroach..

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/43252954/155955325-edafd505-07fe-4530-bc73-cbdb93276dc2.png)

#### Steps to reproduce, if exist:
Start creation of view and open **Source** tab in metadata

**Comment by serge-rider** [comment]
Also new view DDL was broken in MySQL.

Fixed.

**Comment by uslss** [comment]
Incorrect ddl is generated for postgresql
![image](https://user-images.githubusercontent.com/31996417/158158920-fce3eaa1-e4f2-4cb8-ad60-2f7c2211e115.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
