### ISSUE TITLE
Can't connect to Phoenix

### ISSUE THREAD

**Issue by pine-scamper** [dbeaver/dbeaver#15676]
hbase-2.2.4
phoenix-hbase-2.1-5.1.2-bin
DBeaver 21.3.5

I used phoenix to connect to hbase in centos successfully.
as follows：
[xxx]$ ./sqlline.py 192.168.xx.xx:2181:/hbase
Setting property: [incremental, false]
Setting property: [isolation, TRANSACTION_READ_COMMITTED]
issuing: !connect -p driver org.apache.phoenix.jdbc.PhoenixDriver -p user "none" -p password "none" "jdbc:phoenix:192.168.6.47:2181:/hbase"
Connecting to jdbc:phoenix:192.168.6.47:2181:/hbase
Connected to: Phoenix (version 5.1)
Driver: PhoenixEmbeddedDriver (version 5.1)
Autocommit status: true
Transaction isolation: TRANSACTION_READ_COMMITTED
sqlline version 1.9.0
0: jdbc:phoenix:192.168.xx.xx:2181:/hbase>

But int windows10 and DBeaver 21.3.5
When I finished editing the driver settings to phoenix-client-hbase-2.1-5.1.2.jar. 
Press the test connection, as follows：
Unexpected driver error occurred while connecting to the database
  java.lang.RuntimeException: class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider
  java.lang.RuntimeException: class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider
    class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider
    class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider

Then Restart DBeaver and connect:
Always  loading : connect to jdbc:phoenix:192.168.xx.xx:2181:/hbase : Connecting Main (0%)

**Comment by serge-rider** [comment]
It works with predefined driver but not the latest version (latest version doesn't work in Java 11)
Try version 4.14.1-HBase-1.4 :
![image](https://user-images.githubusercontent.com/6398845/162221548-7c1e0290-1d0b-4fd9-abe3-53a6bda786fd.png)

I will set this driver version as default in the next DBeaver version

**Comment by uslss** [comment]
verified
