### ISSUE TITLE
[SQLite] Can't add aliased columns to grouping panel

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#15677]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 22.0.0

#### Describe the problem you're observing:
If the column has an alias for a name in SQL Editor resultset dragging it into grouping panel will cause an error

#### Steps to reproduce, if exist:
1. Execute a select query with alias for any column
2. Drag an aliased column to grouping panel

**Expected:** Column is added to grouping

**Actual:** `SQL Error [1]: [SQLITE_ERROR] SQL error or missing database (no such column: "alias name")` is shown

**Comment by serge-rider** [comment]
The problem was in SQLite dialect config (subqueries support was disabled).

**Comment by uslss** [comment]
verified
