### ISSUE TITLE
Alias is used instead of real PK column name when saving changes

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#15671]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 22.0.0

#### Describe the problem you're observing:
Alias is used instead of actual PK column name if changes are made to resultset in SQL Editor

#### Steps to reproduce, if exist:
1. Execute a select query with alias for PK column (e.g select `f.film_id as id , f.title  from film f`)
2. Change something in resultset
3. Click save

**Expected:** Changes are saved

**Actual:** `SQL Error [42703]: ERROR: column "id" does not exist` is shown

**Comment by serge-rider** [comment]
Fixed in #16669
