### ISSUE TITLE
Receiving 'Datasource was invalidated' notification

### ISSUE THREAD

**Issue by alanneese** [dbeaver/dbeaver#15686]
#### System information: 
- Windows 10
- DBeaver 21.3.5.202202200327

#### Connection specification:
- Database name : jhj7bqbh_menudb
- Driver name : MySQL 5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I keep getting the notification from DBeaver 'Datasource was invalidated'  Live connection count: 2/2
#### Steps to reproduce, if exist:
Just access my database and run a query.
#### Include any warning/errors/backtraces from the logs

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Mar 01 15:11:21 CST 2022
Cannot determine transaction isolation level due to connection hanging. Setting to NONE.

**Comment by Matvey16** [comment]
@alanneese Hello, thank you for the report. Do you have any settings that may be disconnecting you because of the timeouts? This message should appear if the connection for editor was lost

**Comment by alanneese** [comment]
No, not that I am aware of.  I have been fighting this error for a while.
