### ISSUE TITLE
Bug with connection loosing

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#15691]
- Operating system (distribution) and version: Win10
- DBeaver version:  21.3.5.202202200327
- Database name and version: Postgres 14

The old bug with connection loosing exists. Synopsys is as follows:

1. I do common work (connection with database is via internet, via vpn);
2. I hibernate windows machine via power menu - not exiting from DBeaver, not turning off vpn;
3. I restore workstation (at the same state). Vpn says it must be reconnected, so I reconnect;
4. I press "refresh" in the tree in DBeaver (refrsh connection), so the connection refreshes normally;
5. I have OLD tab with SQL editor (from yesterday) and a NEW tab - just opened. Connection is 100% the same in both;
6. Trying to make query in NEW tab - all OK;
7. Trying in OLD - notification "Datasource was invalidated" blinks several times. Then "connection was already closed" is written in result tab;
8. Try again - exacltly same behaviour.

This is very very old bug. Logs ar
[LostConn1.txt](https://github.com/dbeaver/dbeaver/files/8168222/LostConn1.txt)
[LostConn2.txt](https://github.com/dbeaver/dbeaver/files/8168224/LostConn2.txt)
e attached.

**Comment by flambchap** [comment]
Hi @plotn. It's expected behavior. The connection is not the same. DBeaver opens a new connection for every new SQL Editor tab by default. You can turn off this in the preferences.
