### ISSUE TITLE
Error exporting to sql format

### ISSUE THREAD

**Issue by Philippe-M** [dbeaver/dbeaver#15695]
Hello,

I have this request

```
SELECT s.num_0 AS num, s.sdhnum_0 AS sdhnum, s.itmref_0 AS itmref, s.REP1_0 AS rep1, tsicod_0 AS tsicod0, tsicod_1 AS tsicod1, tsicod_2 AS tsicod2, tsicod_3 AS tsicod3, tsicod_4 AS tsicod4
FROM SINVOICED s 
INNER JOIN SINVOICE s1 ON s1.num_0 = s.NUM_0 
WHERE s.CREDAT_0 >= TO_DATE('2018-01-01', 'yyyy-mm-dd') AND s.SALFCY_0 = 'FIN' AND s1.INVTYP_0 < 3;
```

I am trying to export the result to a sql file. I right click on the results and select "Export Results".
![image](https://user-images.githubusercontent.com/4558101/156363465-7b05e905-4528-4ccb-91b5-2af8b9a3c12a.png)

![image](https://user-images.githubusercontent.com/4558101/156363519-db729528-54da-407c-b55c-2db84716723e.png)

![image](https://user-images.githubusercontent.com/4558101/156363576-9e84a2e3-18cb-4bd5-ae4e-bcd2deee4d61.png)

![image](https://user-images.githubusercontent.com/4558101/156363670-b2f31e01-415e-440a-8710-0d8afbb0886b.png)

![image](https://user-images.githubusercontent.com/4558101/156363808-97ec7edd-0990-41dd-8968-45a018e46357.png)

1st problem with the file name, I use the variable ${table} but instead the start of the query is used.

![image](https://user-images.githubusercontent.com/4558101/156364015-a719ff8e-41d5-4b3f-9c22-c8f873c87fd8.png)

2nd problem, once the export is finished the sql file contains the select query in the middle of the insert.
![image](https://user-images.githubusercontent.com/4558101/156364238-57afd37c-fa8c-485a-a944-f4c7539d92f4.png)

By removing the INNER JOIN everything works normally. Exporting to CSV only has the output file name problem.

#### System information: 
- Operating system (distribution) and version : Fedora 35
- DBeaver version : 21.3.5
- Additional extensions : no

#### Connection specification:
- Database name and version : Oracle, 10g
- Driver name : oracle.jdbc.OracleDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Include any warning/errors/backtraces from the logs
No error

**Comment by Skydiveroid** [comment]
Thank you for your report.
