### ISSUE TITLE
Password rest

### ISSUE THREAD

**Issue by Ipsita503178922** [dbeaver/dbeaver#15692]
#### System information: 
- Operating system (distribution) and version
- DBeaver version :21.2.5
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by Skydiveroid** [comment]
Hello @Ipsita503178922,

Can you please provide more information about your issue? Thanks.

**Comment by Ipsita503178922** [comment]
I need to reset my password . how do i do that?

**Comment by LonwoLonwo** [comment]
Hello @Ipsita503178922 

Please tell me, what kind of password are you want to restore? Database connection password? DBeaver master-password? Or something else?

**Comment by Ipsita503178922** [comment]
database  connection password.

**Comment by LonwoLonwo** [comment]
What database do you use?

**Comment by uslss** [comment]
There have been no updates for a long time. If it is still actual - feel free to reopen the issue
