### ISSUE TITLE
Empty strings in PostgreSQL arrays are recognized as NULL

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#15698]
#### System information: 
- Operating system (distribution) and version
- DBeaver version 22.0.0 devel branch
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 11,6
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Steps to reproduce, if exist:
1. Execute the following:
```sql
select
  array[''],
  array[]::text[],
  row('', 'NULL'),
  row(null, 'NULL'), 
  array[null, 'NULL'], 
  row(array[null]),
  row(array[null, 'NULL']), 
  array[row(null), row('NULL')];
```
The results are displayed like this:
![image](https://user-images.githubusercontent.com/26031301/156398662-67f4c6d2-7a73-493a-ab11-7010c602cd66.png)

But this is not correct:
![image](https://user-images.githubusercontent.com/26031301/156398744-4b899d8f-df4c-42db-b2f9-65a50829d502.png)

#### Include any warning/errors/backtraces from the logs

Credit to @lukaseder for discovering this bug.

**Comment by ShadelessFox** [comment]
Structs are now messed up in case of disabled complex structures:

![image](https://user-images.githubusercontent.com/35821147/172775614-e8b3aecd-b45f-4168-b0dd-7c46e211c21d.png)

**Comment by Remi-C** [comment]
Hey folks, does your fix also work on:
```SELECT '{NULL}'::text[] , '{}'::text[]```
(these array appear as the same thing in DBeaver, but they are not the same thing ! )

<img width="456" alt="image" src="https://user-images.githubusercontent.com/4725794/173131230-58bd04cd-b091-4d76-b1ed-07fc2119446d.png">

**Comment by ShadelessFox** [comment]
Hello @Remi-C,

Yes, it was fixed within this issue:

![image](https://user-images.githubusercontent.com/35821147/173158989-fb275ec4-af32-4db2-9658-ed26195b5a18.png)

P.S: I had no idea you can get a `psql`-compatible textual representation of any value just by casting it to `text`. Noted!

**Comment by Remi-C** [comment]
Thanks @ShadelessFox , awesome news !
