### ISSUE TITLE
SQL Error [500618] [HY000]: Integrating DBeaver with Azure Databricks

### ISSUE THREAD

**Issue by sayakc027** [dbeaver/dbeaver#15700]
#### System information: 
- Operating system (distribution) and version: MAC OS Version 12.2.1
- DBeaver version: https://dbeaver.io/download/
- Additional extensions

#### Connection specification:
- Database name and version: Azure Databricks (Client Confidential)
- Driver name: https://databricks.com/spark/jdbc-drivers-download
- Do you use tunnels or proxies (SSH, SOCKS, etc)? -- No

#### Describe the problem you're observing:

<img width="767" alt="image" src="https://user-images.githubusercontent.com/54745869/156451440-60e59a2e-8c8e-43db-a140-1f3eb5924a05.png">

## Issue:
Trying to integrate DBeaver to access database on Azure Databricks. Whenever I am writing a SQL Query I am getting the above mentioned error as shown in the pic.

SQL Error [500618] [HY000]: [Simba][SparkJDBCDriver](500618) Error occured while deserializing arrow data: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available

Tried all resources but could not find a solution.

Reference Link: https://docs.microsoft.com/en-us/azure/databricks/dev-tools/dbeaver

#### Steps to reproduce, if exist:

After completing Step 4, while writing query over here: https://docs.microsoft.com/en-us/azure/databricks/dev-tools/dbeaver

**Comment by abij** [comment]
I'm using DBeaver with Azure Databricks (Runtime 10.1). 
Can you specify your Databricks cluster Runtime?

In the error I can see "arrow" as part of the problem. You can try to disable this:
`spark.sql.execution.arrow.pyspark.enabled false` in the Spark Conf

**Comment by sayakc027** [comment]
Databricks Cluster Runtime is  7.3 LTS (includes Apache Spark 3.0.1, Scala 2.12)

**Comment by sayakc027** [comment]
Databricks Cluster Runtime is 7.3 LTS (includes Apache Spark 3.0.1, Scala 2.12)

**Comment by sayakc027** [comment]
Can you please help me with this step as this is my first time?
In the error, I can see "arrow" as part of the problem. You can try to disable this:
spark.sql.execution.arrow.pyspark.enabled false in the Spark Conf

**Comment by uslss** [comment]
Databricks driver is already included in Driver List since 22.0.2
![image](https://user-images.githubusercontent.com/31996417/161506353-9e519fa5-8faf-4623-85f3-9546eba80f50.png)
