### ISSUE TITLE
Mac upgrade resets dbeaver.ini

### ISSUE THREAD

**Issue by thnk2wn** [dbeaver/dbeaver#15706]
#### System information: 
- Operating system (distribution) and version: Mac OS 12.2.1 (21D62)
- DBeaver version: 21.3.5.202202200327
- Additional extensions

#### Connection specification:
- Database name and version: NA
- Driver name: NA
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NA

#### Describe the problem you're observing:
I edited `/Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini`, added `-Duser.timezone=UTC`.

Later there's an upgrade so I let it install. The edit is lost and I have to keep updating on each upgrade.

**Comment by Matvey16** [comment]
@thnk2wn Thank you for the report. Unfortunately for now this is how apple installation works. We will try to change it so those settings that are commonly modified will be stored in other files

**Comment by SourceNode** [comment]
I keep losing my custom dbeaver.ini settings due to this issue. DBeaver settings and configuration should be separate from the application binary to prevent it being replaced with every update.

**Comment by rumbin** [comment]
I second that

**Comment by thnk2wn** [comment]
This seems to have been fixed with 22.1 https://dbeaver.io/2022/06/05/dbeaver-22-1/
