### ISSUE TITLE
On Save editor jumps to last line

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#15709]
#### System information: 
- Operating system Linuy, Debian/SID
- DBeaver version Version 21.3.5.202202200327
- Additional extensions -

#### Connection specification:
- Database name and version PostgreSQL 12
- Driver name 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Use an editor with several queries, so that you need to scroll to get to the bottom (or top).
Edit something at the top.
Save.
Editor will jump to the bottom -- but the cursor still stays at the edit position.
Editor should stay where it is.

**Comment by ShadelessFox** [comment]
Hello @2019-05-10,

This issue was fixed in https://github.com/dbeaver/dbeaver/issues/15562 and the fix will be available in the next version (22.0.0).
