### ISSUE TITLE
Opening SQLITE database connection wants to overwrite file.

### ISSUE THREAD

**Issue by mark-hyde** [dbeaver/dbeaver#15711]
#### System information: 
- Operating system (distribution) and version
$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.5 (Ootpa)

- DBeaver version
DBeaver Community                                   io.dbeaver.DBeaverCommunity                                      21.3.5                            stable              system
(Also checked 21.3.4)

- Additional extensions

#### Connection specification:
- Database name and version
SQLite version 3.26.0 2018-12-01 12:34:55
- Driver name
Sqlite
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No
#### Describe the problem you're observing:
I am not able to easily open a new connection to an existing sqlite database file.

#### Steps to reproduce, if exist:
In flatpak DBeaver Community versions 21.2.5, (which works!) I am able to open an existing sqlite db by creating a connection:
(new connection icon->sqlite->"Browse"->use the 'Choose database file' dialog to select the database-> Click 'Open')

However in the latest flatpak version 21.3.5 (and at least one other previous 21.3.x ) this is not possible because the 'Choose database file' dialog has a 'Save' button rather than an 'Open' button. 
If you click 'Save' then it asks if you want to overwrite the existing file (which we don't!!)

Workarounds are: 
A - change the name of the file in the dialog from 'dummy.db' to 'dummy.dbx', save the  connection, and then edit the connection to point at the original file.
B - Rollback the version to 21.2.5

**Comment by ShadelessFox** [comment]
Hello @mark-hyde,

Pressing `Save` does not overwrite the existing file.

We had to make this dialog saveable to allow specifying non-existing files so that the database could create one.
