### ISSUE TITLE
Redshift - can't search Database Metadata in definitions (column pp.oid does not exist)

### ISSUE THREAD

**Issue by match-gabeflores** [dbeaver/dbeaver#15729]
When trying to search _in definitions_ for Redshift, I receive the below error message. 

If I remove the option for "in definition", the search succeeds. 

`SQL Error [42703]: ERROR: column pp.oid does not exist`

Search options
![image](https://user-images.githubusercontent.com/286903/156800560-83c4be00-ba34-4405-8031-a3a354da7a71.png)

Error
![image](https://user-images.githubusercontent.com/286903/156800621-e949ac33-02e7-4592-844b-2c59c3970693.png)

dbeaver Version 21.3.5.202202200327
Windows 10

**Comment by LonwoLonwo** [comment]
Hello @match-gabeflores 

Thanks for the bug report.

What Redshift version do you use?

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 22.0.1

**Comment by uslss** [comment]
verified
