### ISSUE TITLE
MariaDB: Missing * in the query when counting records on the toolbar

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#15732]
When I count records in simple query (select id from clients)
![image](https://user-images.githubusercontent.com/16996529/156866177-026bb3b5-68ba-490d-9b9f-bd6cdcbe2620.png)
The query should be of course 'select  count(*) from clients'

In another case, when the query is more complex 'select id from clients group by id' - it works fine.
![image](https://user-images.githubusercontent.com/16996529/156866365-43de57f1-d9bd-47b8-b678-fcb93031b5e6.png)

**Comment by LonwoLonwo** [comment]
Hello @offstate 

Thanks for the bug report!

This bug was fixed https://github.com/dbeaver/dbeaver/issues/15600.

DBeaver version 22.0.0 with the fix will be available at 07-03-2022
