### ISSUE TITLE
Compact formatter doesn't put column elements in one line

### ISSUE THREAD

**Issue by TheMechanist902** [dbeaver/dbeaver#15739]
#### System information: 
- Operating system (distribution) and version: Win 10
- DBeaver version: 2.1.3.5
- Additional extensions: None

#### Connection specification:
- Database name and version: Postgres
- Driver name: Standard drivers delivered by dBeaver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
The "compact formatter" is supposed to put column elements in one line. But it is not doing that.

#### Steps to reproduce, if exist:
1. Create a new script with an arbitrary SELECT Query like: 
```sql
SELECT 
t.*, 
j1.x, 
j2.y
FROM TABLE1 t
```
2. Go to Preferences - Editors -> SQL Editor -> Formatting and choose "Compact formatter" as formatter.
3. Expected result after applying the autoformater to code (as shown in the preview):
```sql
SELECT t.*, j1.x, j2.y
FROM TABLE1 t
```
Actual result: Nothing changes

#### Include any warning/errors/backtraces from the logs
No errors were given

**Comment by LonwoLonwo** [comment]
Hello @TheMechanist902 

Thanks for the bug report!
