### ISSUE TITLE
[Datatransfer] keep "recreate" status for task editing.

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#15733]
DBeaver 22.0.0

"Recreate" status changes for "existing" in the case of task editing.

Steps:

1. Click on the table in the Database Navigator tree and choose "Import."
2. Choose CSV format and add the path to the import file
3. Change the "existing" mapping status of the table to "recreate"
4. Save the task
5. Close the data transfer dialog.
6. Click on the task in the Database Tasks view and choose "Edit task"

Expected behavior: the "recreate" mapping status saved
Actual behavior: the "recreate" mapping status changed to the "existing"

Recreate action works fine if we want to run the tusk, not edit.

Also, we must add the "recreate" mapping type to the list of possible types for tables if the table doesn't exist.

**Comment by serge-rider** [comment]
We need to do full regression of Data Transfer wizard. From/to files, from/to tables, all different mapping types.

**Comment by LonwoLonwo** [comment]
![udAw8B2Ikp](https://user-images.githubusercontent.com/45152336/158975521-f22d63eb-a846-4ae6-838c-eb31e299f973.gif)

fixed

**Comment by uslss** [comment]
![dbeaver_2Jz534Av36](https://user-images.githubusercontent.com/31996417/160790690-d28a6c11-c4f5-4fc4-823b-a8a80252e361.gif)

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by uslss** [comment]
verified
