### ISSUE TITLE
Attribute binding is broken

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#15735]
It happens when asterisk is before column names.
In this case DBeaver binds incorrect table column to resulset column.

Query to reproduce (SQLite):
```sql
select *,AlbumId,Title  from Album a;
```
When your open column filter for the first "Title" column it shows dictionary for "AlbumId" column.

Also it may break data editor (save incorrect column).

**Comment by Matvey16** [comment]
Verified
