### ISSUE TITLE
Include file in sql editor

### ISSUE THREAD

**Issue by ClodoaldoPinto** [dbeaver/dbeaver#15746]
Is there a way to include a text file in a sql file in the sql editor? My use case is that I have a very long static CTE (a virtual table) that will be incorporated in many scripts. I have no create permission in the database so my only solution is the CTE.

**Comment by ShadelessFox** [comment]
Hello @ClodoaldoPinto,

This feature is already present in DBeaver.

You can use `@include filename` statement.

Please refer to our documentation for more information: https://dbeaver.com/docs/wiki/Client-Side-Scripting
