### ISSUE TITLE
Auto-complete DB2 does not work from 21.4 on

### ISSUE THREAD

**Issue by mikkk3l** [dbeaver/dbeaver#15742]
#### System information: 
- Operating system (distribution) and version windows 10
- DBeaver version 21.4
- Additional extensions

#### Connection specification:
- Database name and version DB2 DSN12015
- Driver name jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

In 21.3 version autocomplete table name with ctrl+space works but from 21.4 on it reamins in "search proposals" forever.

![image](https://user-images.githubusercontent.com/15341836/157029344-4562a594-7514-4cca-ab8f-ebf9889bccb7.png)

**Comment by LonwoLonwo** [comment]
Hello @mikkk3l 

What DB2 version do you use?
Can you provide please the example of a query? Video or screenshots of the issue will be also very helpful.

**Comment by serge-rider** [comment]
You also could check what SQL query DBeaver executes to read database metadata (see https://github.com/dbeaver/dbeaver/wiki/Query-Manager)

**Comment by mikkk3l** [comment]
DSN12015, updated.
There is no query in query manager for me to retrieve metadata (maybe the driver does it at init)

**Comment by mikkk3l** [comment]
Video (in previous version it retrieves ir almost inmediately)

https://user-images.githubusercontent.com/15341836/157210869-0038b343-0b89-4923-a5a3-98058784f47e.mp4

Finnally the metadata is gathered, after aprox several minutes. But next query to metadata takes again the same amount.

Besides, when you close DBeaver, it remains in background and you have to kill the task via tasks admin in Windows.
![image](https://user-images.githubusercontent.com/15341836/157212224-d8e80e96-3ba7-465f-99b5-fc40c79e3677.png)

**Comment by mikkk3l** [comment]
This is the correct behaviour in 21.3:

https://user-images.githubusercontent.com/15341836/157212811-b9819907-18f4-4675-9658-104c38204d8f.mp4

**Comment by Matvey16** [comment]
@mikkk3l Thank you for the report, it probably depends on driver properties. We will move the most important ones into connection settings

**Comment by LonwoLonwo** [comment]
Hello @mikkk3l 

Can you please check this ("metadata source") setting in your Connection setting?

If "metadata source" = -1, can you please change it to 0 and tell me - does it increase performance of metadata reading?

**Comment by LonwoLonwo** [comment]
![2022-04-01 11_20_47-DBeaver Ultimate 22 0 2 - _PUB400 COM_Script-143](https://user-images.githubusercontent.com/45152336/161225760-12134b41-1b6a-4dcb-b9ed-d2773888475c.png)

**Comment by mikkk3l** [comment]
I have updated to 22.0.2 and it works again.

This is the config:
![image](https://user-images.githubusercontent.com/15341836/161938989-c9c1e0dd-25b2-4fe1-b982-db4fbfe4ad50.png)

Thank you.

**Comment by LonwoLonwo** [comment]
Thanks for the answer and for the investigation @mikkk3l
