### ISSUE TITLE
Cannot "select all" in columns of type "date"

### ISSUE THREAD

**Issue by danydev** [dbeaver/dbeaver#15745]
#### System information: 
- macos Monterey 12.2.1
- DBeaver Version 22.0.0.202203060510

#### Connection specification:
- Postgresql 11

#### Describe the problem you're observing:
When trying to select all text, inside a column of type dates, the focus moves to the sql script, selecting all the text inside that area (i.e. where you write the query)

#### Steps to reproduce, if exist:
- Do a query in a table with a "date" column (timestamptz, date, etc...)
- Double click in the date column of one of the row returned (to enable text editing on such column)
- ctrl+A to select all the text
- observe that the date column text is NOT selected, instead it selects all the text of your query

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @danydev 

![ROAQjaMzI3](https://user-images.githubusercontent.com/45152336/157443954-63708215-6f4f-49c5-a86d-eac457243a10.gif)

I can reproduce it.

**Comment by Matvey16** [comment]
Not fixed for value panel

![dbeaver_5YywOMMman](https://user-images.githubusercontent.com/82543000/158419738-b452dde4-44f0-4736-b740-86ff9be9bb64.gif)

**Comment by Matvey16** [comment]
Something broke after this fix.

In Data editor:
Can't select all with ctrl+A in value panel for varchar column

In SQL Editor:
Can't select all with ctrl+A in value panel for both varchar and date/time columns

**Comment by Matvey16** [comment]
This happens due to unusual keybind settings, works as expected on default binds (I probably forgot how I changed them and that lead to them not working)
