### ISSUE TITLE
Firebird: CREATE PROCEDURE has no effect

### ISSUE THREAD

**Issue by tautf** [dbeaver/dbeaver#15753]
#### System information: 
- Operating system (distribution) and version: Mac OS
- DBeaver version: 22.0.0
- Additional extensions

#### Connection specification:
- Database name and version: Firebird 3.0.7
- Driver name: Firebird
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
Running a script with `CREATE OR ALTER PROCEDURE` is running successfully but is not really creating a procedure.
#### Steps to reproduce, if exist:
Try to create a procedure by script with DBeaver 22.0.0 and Firebird 3 database;

#### Include any warning/errors/backtraces from the logs

Nothing. Works with older Versions than 22.0.0 fine.

**Comment by LonwoLonwo** [comment]
Hello @TautFlorian 

Can you provide more info please?

I can't reproduce for now.

![2022-03-08 16_13_45-DBeaver Ultimate 22 0 0 - _EXT FDB_Script-134](https://user-images.githubusercontent.com/45152336/157245150-e839d105-5ea7-4938-8867-783bde7a3cf2.png)

Do you execute a create procedure script in DBeaver SQL Editor?

What does it mean - the procedure is not created? Does it appear in the Database navigator? If so, did you try to refresh the Database navigator tree?

**Comment by LonwoLonwo** [comment]
Also is any extra info in the [Error log](Also is any extra info in the Error log?)?

**Comment by tautf** [comment]
So i did the following:

`DROP PROCEDURE GET_EXTRATREATMENTS;`
Procedure was dropped successfully.

Then i did:

```sql
SET TERM ^;
CREATE OR ALTER PROCEDURE GET_EXTRATREATMENTS (ORDERITEM_ID ID, LANGUAGE_CODE VARCHAR(10))
...
END
SET TERM ;^
```

Output in console is the following:
![Bildschirmfoto 2022-03-08 um 14 28 05 PM](https://user-images.githubusercontent.com/18403881/157247469-81f51df1-68c6-450f-b50f-d4e6d1e747d5.png)


Refresh and reconnect of procedures in the ui still does not show the procedure and call of it is not possible.

I tried on my windows machine with DBeaver 21.0.4, there the exact same statement works perfectly fine. With earlier versions of DBeaver i never had issues on my Mac as well with creating and altering procedures.

**Comment by tautf** [comment]
Addition, even if i grant permissions afterwards, it works fine:
```sql
GRANT EXECUTE ON PROCEDURE GET_EXTRATREATMENTS TO USER;
```

But 
```sql
EXECUTE PROCEDURE GET_EXTRATREATMENTS (1111, 'de');
```

Returns:
```
SQL-Fehler [335544581] [42000]: Dynamic SQL Error; SQL error code = -204; Procedure unknown; GET_EXTRATREATMENTS [SQLState:42000, ISC error code:335544581]
```

**Comment by LonwoLonwo** [comment]
Hello @TautFlorian 

DBeaver uses the Firebird driver to read the procedures/functions list.
Can you provide more info about your driver, please?

You can check the version of the driver in the Connection Settings -> Test Connection.

![2022-03-09 09_44_03-DBeaver 22 0 0 - _PostgreSQL - postgres_ Script-10](https://user-images.githubusercontent.com/45152336/157387223-774b8e3d-2415-42da-a803-7a4b913f53bd.png)

Also, can you provide an example of the creation procedure query which doesn't work?

**Comment by tautf** [comment]
Sorry about the delay. Unfortunately i'm not able to provide you the exact procedure as it contains internals.
It does not do something very special.

Contains multiple ```FOR ... BEGIN ... END``` and thats basically it.

Here is the screenshot:
![Bildschirmfoto 2022-03-14 um 10 07 40 AM](https://user-images.githubusercontent.com/18403881/158140547-028d03e1-cee3-4b1c-baeb-56b9d1efa32a.png)

**Comment by LonwoLonwo** [comment]
Is there something in the error logs? https://github.com/dbeaver/dbeaver/wiki/Log-files

And what commit mode do you have?

![2022-03-15 15_36_40-DBeaver Ultimate 22 0 0 - _postgres12local_ Script-170](https://user-images.githubusercontent.com/45152336/158379118-3b119990-4728-4cc1-8d0a-7d3312f4bbe5.png)

**Comment by tautf** [comment]
No logs unfortunately.

Commit mode, same as you have:
![Bildschirmfoto 2022-03-23 um 10 44 57 AM](https://user-images.githubusercontent.com/18403881/159670538-3511ac01-3323-4b01-a1d0-dd8c0f0fb31d.png)

**Comment by LonwoLonwo** [comment]
Does this error with other procedures repeat for you? Or was this issue just once for one specific procedure?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual - feel free to reopen it with additional info.

**Comment by tautf** [comment]
Ping @LonwoLonwo 

So i'm reopening this as i found out the issue because i was facing it again and the fact that dbeaver is not complaining may be discussed to have it as an error.

As you can see in my comment above, i have been running the following:

```sql
SET TERM ^;
CREATE OR ALTER PROCEDURE GET_EXTRATREATMENTS (ORDERITEM_ID ID, LANGUAGE_CODE VARCHAR(10))
...
END
SET TERM ;^
```

The cause of this issue is a missing `^` at the last `END` statement.

If youre missing it, the statement runs fine, but has no effect to the database. Adding it, brings the same result, but is actually doing the changes.

So the correct statement is:

```sql
SET TERM ^;
CREATE OR ALTER PROCEDURE GET_EXTRATREATMENTS (ORDERITEM_ID ID, LANGUAGE_CODE VARCHAR(10))
...
END^
SET TERM ;^
```
