### ISSUE TITLE
Selecting `timestamptz` field "modifies" the cell, rather than highlighting.

### ISSUE THREAD

**Issue by Seanld** [dbeaver/dbeaver#15759]
#### System information: 
- OS: Arch Linux
- DBeaver: 22
- Additional extensions: none

#### Connection specification:
- Postgres
- Default driver
- No proxies or tunnels

#### Describe the problem you're observing:

When clicking any `timestamptz` field, it automatically highlights in orange (the default "cell modified" color). However, it does not seem to actually change the content of the cell. I do not want this behaviour. After applying a filter, it will also automatically select the top-left-most cell, which since on this particular table of mine happens to be a `timestamptz` field, this then automatically "modifies" it. This is really annoying. If I start to scroll, and hit the bottom, it'll ask me if I want to apply my modifications before loading the next page.

Is there a setting I cannot find that disables this? It definitely seems like a bug. I don't know what scenario this "auto-modify-but-don't-actually-modify" behaviour is useful in.

#### Steps to reproduce, if exist:

Single click any `timestamptz` field. It should simply highlight the field, not "modify" it.

**Comment by Matvey16** [comment]
@Seanld Hello. I was not able to reproduce this. Can you provide some screenshots or a video if it possible? Also does it trigger the appearance of asterisk in the tab name and activation of save/cancel buttons?

**Comment by Seanld** [comment]
It _does_ trigger the asterisk and save/cancel buttons, yes. I noticed this on my work computer, so I'd have to set up a fake DB to demonstrate.

**Comment by Seanld** [comment]
I was changing the font size to cut off the important columns, so that I could screenshot, and it stopped doing it. Now it works normally. Hmm. I'll provide a screenshot if I can replicate it again.

**Comment by uslss** [comment]
There has been no update for a long time. If the issue reproduces again - feel free to reopen it
