### ISSUE TITLE
Order by column ASC or DESC is case-sensetive, switch to case-insensetive

### ISSUE THREAD

**Issue by ystenberge** [dbeaver/dbeaver#15756]
Hey,

I just upgraded to the newest version and noticed when I use the dbeaver function to order a table or view column, which contains text, the result is case-sensitive like ABCabc, before it was case-insensitive like AaBbCc. When I use a SQL query instead to Order By the column the result is case-insensitive. I couldn't find any information about this. Is there a setting in preferences to chose what dbeaver is using? Thanks a lot!

System information: 
- Windows 10
- Version 22.0.0.202203060510
- Postgres 9.6

**Comment by LonwoLonwo** [comment]
Hello @ystenberge 

DBeaver uses filters from the client's side by default for already loaded a small amount of data. Or reads from the server-side if data isn't fully loaded. Case-insensitive/case-sensitive behavior may be different in these cases.

You can change it in Preferences -> Editors -> Data Editor -> "Results ordering mode"

![2022-03-11 10_10_03-Preferences](https://user-images.githubusercontent.com/45152336/157819554-b0c1dece-be59-40ee-9eb9-a17133c7d8c8.png)

**Comment by ystenberge** [comment]
Hey @LonwoLonwo,

thank you for your help! I changed the settings to 'Always on server'. That worked.

Cheers!

**Comment by LonwoLonwo** [comment]
Thanks for the answer @ystenberge
