### ISSUE TITLE
[ER Diagrams] Better routing 

### ISSUE THREAD

**Issue by Destrolaric** [dbeaver/dbeaver#15755]
## Problem
Sometimes our current routing method creates incorrect pathways to entities, leading to relations interloping with entities. Also connections only lead to the entity itself, not the foreign key. That is confusing for users and requires polishing.
## Solution
Pathfinding algorithms and graphics require improvement to prevent the mentioned issue. Relationships should be shown key -> foreign key columns.

**Comment by uslss** [comment]
verified
