### ISSUE TITLE
 [Oracle] Bug:  MV changes are not saved.

### ISSUE THREAD

**Issue by Bitros** [dbeaver/dbeaver#15763]
Any changes in Oracle MV can not be saved when switch to DDL Compact Format. But it works well when switch to Full DDL Format.

DBeaver CE  V22.0

**CREATE MATERIALIZED VIEW MVTEST AS SELECT 1 FROM dual;**

![image](https://user-images.githubusercontent.com/9913942/157391673-fd2c4081-f886-4ea3-a24c-507e059454e1.png)
![image](https://user-images.githubusercontent.com/9913942/157391697-30fc4b86-9e7a-4116-8cfa-760118e349a0.png)

**Comment by LonwoLonwo** [comment]
Hello @Bitros 

Thanks for the bug report.

**Comment by LonwoLonwo** [comment]
This is not good also:

![2022-03-09 14_05_18- Oracle  Bug_ MV changes are not saved  · Issue #15763 · dbeaver_dbeaver — Mozil](https://user-images.githubusercontent.com/45152336/157440504-2117f15f-7dcd-4c25-99b3-df9f2ea69594.png)

**Comment by uslss** [comment]
verified
