### ISSUE TITLE
Extend Connection Type color coding to Tabs

### ISSUE THREAD

**Issue by groobo** [dbeaver/dbeaver#15760]
The Connection type setting with a color choice is an excellent solution to quickly identify between production, test and development databases. I am often working on multiple connections of the 'same' database so it comes handy and prevented many accidents in the past.  
I see a room for improvement here – I would like to extend this feature so that the Parent tabs (the one with actual Table names) are also color coded. That way I could quickly identify which tab is associated with which connection:

![Screen Shot 2022-03-08 at 5 37 49 PM](https://user-images.githubusercontent.com/10777274/157337992-23783379-1da9-4759-bf9c-5ae54e65fb35.jpg)

**Comment by ShadelessFox** [comment]
Thanks for the feature request. That would be a nice enhancement.

**Comment by serge-rider** [comment]
#16607

**Comment by jahlbornG** [comment]
@serge-rider i just updated to 22.1.0 and i'm not seeing any difference in the tab color?

**Comment by svonjoi** [comment]
same - no difference and no settings to enable this

**Comment by jahlbornG** [comment]
i re-filed this feature request as #16827
