### ISSUE TITLE
Issue comparing between Tables Oracle and Tables Db2

### ISSUE THREAD

**Issue by leozanon94** [dbeaver/dbeaver#1576]
Good morning,
i tried to compare the Tables folder from oracle connection and a Tables folder in db2.
but i get this error: "Objects of different types were selected. You may compare only objects of the same type".
db2 Driver Name: DB2 / DB2 LUW 8.x  db2jcc4.jar
ora Driver name: Oracle   ojdbc6.jar

How can i do that? Its a dbeaver issue or my fault?

Thanks
Leonardo

**Comment by leozanon94** [comment]
> Good morning,
> i tried to compare the Tables folder from oracle connection and a Tables folder in db2.
> but i get this error: "Objects of different types were selected. You may compare only objects of the same type".
> db2 Driver Name: DB2 / DB2 LUW 8.x db2jcc4.jar
> ora Driver name: Oracle ojdbc6.jar
> 
> How can i do that? Its a dbeaver issue or my fault?
> 
> Thanks
> Leonardo



Good evening, i found this problem between oracle and sql-server too. 
I'm using version 6.1.5

Leonardo

**Comment by serge-rider** [comment]
Simple structure compare can't compare objects of different types/structure.
If you need deep table analysis / structured diff / DDL generation then you should use Schema compare tool in DBeaver Enterprise.
