### ISSUE TITLE
presto MAP‘s results panel is blank

### ISSUE THREAD

**Issue by pengwanli** [dbeaver/dbeaver#15761]
system: win10
dbeaverVersion: 22.0

presto map‘s results panel is blank. but It work in Dbeave 21.2.5;

**Comment by LonwoLonwo** [comment]
Hello @pengwanli 

Can you provide more info, please?

What Presto database version do you use? What driver do you use?

Can you provide screenshots or a video of this issue?

Maybe you can find some helpful info on our wiki page: https://github.com/dbeaver/dbeaver/wiki/Working-with-Spatial-GIS-data

**Comment by pengwanli** [comment]
![image](https://user-images.githubusercontent.com/21196591/157443810-3a18e321-4693-46ac-b879-53ef9e8f9938.png)
this

Presto Version:  presto-jdbc-0.270.jar
DBversion: 22.0.0
The panel cannot parse the map structure data of presto.

**Comment by LonwoLonwo** [comment]
Could you please send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info
