### ISSUE TITLE
Import process stopped if last symbol of text field has backslash

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [dbeaver/dbeaver#15777]
original string = ABC "Z" MTK
export string is csv-file as (for example 3 field)
123,"ABC ""Z"" MTK",456
and cannot import second field, write cannot format "Z" to digit.

ver.22.0.0

**Comment by LonwoLonwo** [comment]
Hello @aleksandr-shevchenko 

Unfortunately, I can't reproduce.

So, please, provide more info.

What database do you use? What data type has a column with this String value?
Do you use import in an existing table or create a new one?

Can you provide a screen of your CSV import settings? What type of "Quote char" is there?

![2022-03-09 17_14_33-Data Transfer](https://user-images.githubusercontent.com/45152336/157459470-ccd1356c-d896-4687-87ef-badb3a104eca.png)

**Comment by LonwoLonwo** [comment]
Also, if any additional info is in your [Log files](https://github.com/dbeaver/dbeaver/wiki/Log-files) - please share it here.

**Comment by aleksandr-shevchenko** [comment]
![ss_2022_03_09__18_37_50](https://user-images.githubusercontent.com/25248634/157463643-1f09be4d-479b-4de1-8ae4-216bf06d8fb4.png)

**Comment by aleksandr-shevchenko** [comment]
![ss_2022_03_09__18_36_38](https://user-images.githubusercontent.com/25248634/157464322-e0419c82-d880-4a10-803e-372eeb259246.png)

**Comment by LonwoLonwo** [comment]
Ok, I see.

Can you check the data type of your target String column?

![2022-03-09 18_11_39-DBeaver Ultimate 22 0 0 - MVTEST](https://user-images.githubusercontent.com/45152336/157470472-26cb2276-f5d0-478f-9b73-4986dcb7c261.png)

The `Can't parse numeric value` message usually appears if you add a string value in the numeric column.

**Comment by aleksandr-shevchenko** [comment]
I found!
original string = ABC "Z" MTK\     (last symbol in varchar - backslash)
export string is csv-file as (for example 3 field)
123,"ABC ""Z"" MTK\\",456
and cannot import second and rest fields with various error depending from next field with "not null" or no.

**Comment by LonwoLonwo** [comment]
I do not see the error with this bakslash line, but I can see, that import is broken after this line - import process stopped.

![2022-03-10 00_51_18-line_with_quotes csv — H__asya_special_dbeaver_backup — Atom](https://user-images.githubusercontent.com/45152336/157542449-69fff704-c980-4909-b750-babe7e74b2dd.png)

**Comment by aleksandr-shevchenko** [comment]
It would be great if the program indicated the line number and the line itself, which it could not import. Instead of writing misleading messages about the string "Z".

**Comment by E1izabeth** [comment]
@aleksandr-shevchenko, your `\` in the second line is assumed as an escape character by DBeaver. Please, change this preference in the import wizard to another character. It leads to successful import.

Let me know if that helps.

![image](https://user-images.githubusercontent.com/28875055/178335114-f38cec96-5274-43ca-9f1e-591792854e18.png)
