### ISSUE TITLE
Advanced copy convert Database name and Table name to upper case

### ISSUE THREAD

**Issue by enboig** [dbeaver/dbeaver#15775]
#### System information: 
- Operating system (distribution) and version Ubuntu 20.04
- DBeaver version 22.0.0
- Additional extensions

#### Connection specification:
- Database name and version MariaDB

#### Describe the problem you're observing:
When using 'Advanced copy -> SQL', to get `INSERT INTO ...` database name and table name is converted to uppercase:
`INSERT INTO MyDatabaseName.MyTableName (...)` -> `INSERT INTO MYDATABASENAME.MYTABLENAME (...)`

#### Steps to reproduce, if exist:
Go to data tab of a mariadb table, and try to copy one row data as sql.

It looks similar to #15183, but in my case is uppercased. I checked and `Keyword case` is set to `upper`, but `Identifier case` is set to `as is`.

EDIT: setting `Keyword case` to `lower` return _camelcase_ database and table names, but all the keywords in lower case. It solve my problem but I think it isn't the expected behavior.

**Comment by LonwoLonwo** [comment]
Hello @enboig 

I can't reproduce this issue, unfortunately.
This issue repeats for you again, or was it once?

Can you share your advanced copy SQL settings?

![2022-03-23 10_37_55-DBeaver Ultimate 22 0 1 - playlist](https://user-images.githubusercontent.com/45152336/159647678-a523a0e7-6c66-4f85-9abd-f3c08f530e89.png)

![2022-03-23 10_38_12-DBeaver Ultimate 22 0 1 - playlist](https://user-images.githubusercontent.com/45152336/159647681-0c5074d8-ff77-4196-958d-eb12f0641a39.png)

**Comment by enboig** [comment]
I tried to reprodue it again (after updating the app to the last version) and I cannot reproduce it anymore, so it may have been fixed:
```sql
/* UPPER CASE */
INSERT INTO CamelCaseDB.CamelCaseTable (CamelCaseField1,CamelCaseField2) VALUES
	 (1,'aaa'),
	 (2,'bbb');

/* lower case */
insert into CamelCaseDB.CamelCaseTable (CamelCaseField1,CamelCaseField2) values
	 (1,'aaa'),
	 (2,'bbb');

```
Thanks for looking into it.

**Comment by LonwoLonwo** [comment]
Thanks for the answer and for the investigation @enboig
