### ISSUE TITLE
Launch Terminal Session from DBeaver

### ISSUE THREAD

**Issue by paid-geek** [dbeaver/dbeaver#15780]
In other SQL IDEs, there is the ability to access the target database system via a terminal session. The feature I would like DBeaver to have is the ability to launch a terminal session so server-side files can be edited from within the tool.

The solution I am looking for is the ability to right-click on the connection and have an open to "Open via Terminal" and it would leverage that connection's information to spawn a putty session.

My current working alternative is to have DBeaver and a Putty open at the same time and connected to the same system, but I'd like to use DBeaver for both activities.

**Comment by ShadelessFox** [comment]
Hello @paid-geek,

You can install an extension that provides terminal support inside Eclipse:

https://marketplace.eclipse.org/content/tm-terminal

Although we don't have any integration to sync hosts, you can add them manually.

Please let me know if that solves your issue.

**Comment by Karlodun** [comment]
@ShadelessFox - This is great! Probably not what paid-geek wants, but still quite great!

**Comment by paid-geek** [comment]
Sorry for the long delay, installing the extension fits the bill. I agree that this issue can be closed.
