### ISSUE TITLE
Use `SSHJ` implementation by default to support ed25519 keys

### ISSUE THREAD

**Issue by NikolayS** [dbeaver/dbeaver#15783]
#### System information: 
- Operating system (distribution) and version – doesn't matter (in my case, latest macOS)
- DBeaver version ersion 22.0.0.202203060510)
- Additional extensions 

#### Connection specification:
- Database name and version Postgres, doesn't matter
- Driver name Postgres driver (default one)
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  SSH port forwarding – it works well but only with RSA or .pem keys. If I use ed25519, it fails

#### Describe the problem you're observing:
`invalid privatekey: [B@3e17e4ee` – see screenshot:
<img width="783" alt="Screen Shot 2022-03-09 at 12 01 54 PM" src="https://user-images.githubusercontent.com/1345402/157524305-a09c362b-7a7f-4c3e-84f3-a63fbb93568a.png">

#### Steps to reproduce, if exist:
Straightforward – just use an ed25519 key

#### Include any warning/errors/backtraces from the logs

N/A

#### Additional info
https://mkyong.com/java/jsch-invalid-privatekey-exception/ and https://github.com/dbeaver/dbeaver/search?q=JSch&type= tell that the problem is most likely in the lib JSch that doesn't support ed25519. At the same time, this format is becoming more and more popular, and our (Database Lab) users start to complain about the inability to work with Postgres thin clones from DBeavier when SSH port forwarding is a requirement. Please fix it.

**Comment by E1izabeth** [comment]
Hello, @NikolayS! Have you tried to switch to another ssh library used to establish connection tunnel? It can be done in Advanced settings:
![image](https://user-images.githubusercontent.com/28875055/157525938-db37a64a-509a-4049-8952-ee0f1d0ab7be.png)

**Comment by NikolayS** [comment]
@E1izabeth thanks! It works well (however, without you, I wouldn't go there – so the problem will remain for the majority of users)

**Comment by NikolayS** [comment]
Maybe SSHJ could become the default?

**Comment by ShadelessFox** [comment]
Hello @NikolayS,

Since this implementation is now bundled with DBeaver, we are free to make it the default one.

**Comment by flambchap** [comment]
Done in the scope of https://github.com/dbeaver/dbeaver/issues/16852.
