### ISSUE TITLE
A fresh install of DBeaver crashes moments after being launched

### ISSUE THREAD

**Issue by salimfadhleyhtp** [dbeaver/dbeaver#15791]
#### System information: 
- Windows 10
- Latest
- Additional extensions: None

#### Describe the problem you're observing:

Debeaver crashes shortly after launching.

Error dialog says:

"An error has occurred. See the log file"

#### Steps to reproduce, if exist:

Launch the app, wait for the banner to go away. Observe the crash.

#### Include any warning/errors/backtraces from the logs

[dbeaver.log](https://github.com/dbeaver/dbeaver/files/8222580/dbeaver.log)

**Comment by andrelinslima** [comment]
Is your user profile in a network share?
The error seems to be saying that your workspace folder ( %APPDATA%\DBeaverData\workspace6 ) is not a local file

**Comment by Destrolaric** [comment]
Could you please try resetting the workspace? You can find the instructions here: 
https://dbeaver.com/docs/wiki/Reset-workspace/

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual - feel free to reopen it with additional info.
