### ISSUE TITLE
only blank line before @SET will make the command work

### ISSUE THREAD

**Issue by alessiojorlandi** [dbeaver/dbeaver#15794]
#### System information: 
- Operating system (distribution) and version: MS Windows 10 Enterprise
- DBeaver version: 21.1.3 
- Additional extensions

#### Connection specification:
- Database name and version: Postgres
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
When using the @SET command to define a variable, it won't work if the preceding line is not blank.

Working example (assume execution line-by-line, not whole script)
```
select 'Hello world'

--comment line

@set var1 = 123

select :var1
```
this will correctly display "Hello world" when executing the first SELECT, then "123" when executing the last SELECT

Now let's try this
Non-working example (assume execution line-by-line, not whole script)
```
select 'Hello world'

--comment line
@set var1 = 999

select :var1
```

In this case @SET won't assign any value to var1, and it will keep being "123"
If we just introduce a blank line before @SET, it will work and assign "999"
The problem holds also when @SET is preceded by other SQL commands, not just comments.

My SQL Processing settings are:
![image](https://user-images.githubusercontent.com/101331738/157658347-5861bc65-829b-4c50-952a-6be7f95f6d42.png)

This issue caused me severe problems. In fact I need to parametrize my scripts and change these parameters every months. But I found out that the parameters haven't changed because the SET commands were all preceded by explanatory comment lines.

Thanks everyone.

PS: This is my first post here, I hope I was compliant enough for the community standards.

**Comment by LonwoLonwo** [comment]
Hello @alessiojorlandi 

Thanks for the bug report.

Can you please test this behaviour in the newest [DBeaver version](https://dbeaver.io/download/)?

**Comment by alessiojorlandi** [comment]
Yes, with DBeaver 22.0.0 this problem seems to be fixed. I'll do some more checks but it looks ok by now.
Thanks a lot.

**Comment by LonwoLonwo** [comment]
Thanks for the investigation @alessiojorlandi 

If the issue appears again - then you can reopen this ticket.
