### ISSUE TITLE
Show NULLs option can't be disabled in TXT export

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#15800]
#### System information: 
- Win11
- DBeaver 22.0.0

#### Describe the problem you're observing:
When you export a table in TXT format with NULL and the **Show nulls option** is disabled, you still get [NULL] in exported file

#### Steps to reproduce:
1. Find or create a table containing zeros
2. Start data export of this table
3. Select the TXT format for the exported data
4. Make sure that **Show NULLs** option is disabled and start the export
![image](https://user-images.githubusercontent.com/43252954/157757157-46f3b859-7bcc-427b-b9bb-d9de393d9753.png)

Expected: nothing is written in place of null values
Actual: even if this option is disabled, you still get "[NULL]" words in place of null values in the exported txt file

**Comment by uslss** [comment]
verified
