### ISSUE TITLE
Question: Define description columns using Custom Criteria

### ISSUE THREAD

**Issue by asishm** [dbeaver/dbeaver#15805]
In the Data tab of a MySQL table I opened the Value viewer panel. In this panel it shows me a dictionary if I select a foreign key value in the Data tab. By clicking Define Description I open the Dictionary structure dialog.

I see there is a Custom criteria text box available. What can I type in there? for example if I type in `select 'foo'` then the output in the Value viewer becomes completely blank. I can type in two or more columns from the existing table like `col1, col2` and that seems to work - but that's just the same as selecting those columns using the checkboxes provided above.

So the question is : what can I use the custom criteria for? if there's already a section in the user guide - I'd be happy to get pointed to that as well

![image](https://user-images.githubusercontent.com/1978117/157879439-41450ec5-66d4-48c1-a019-6f147bd2f2af.png)

![image](https://user-images.githubusercontent.com/1978117/157879505-11e6519b-19b4-4c98-8d32-758b143246f7.png)

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by ShadelessFox** [comment]
We need to clarify the meaning of this obscure `Custom criteria` field.

**Comment by adrianbienias** [comment]
I'm also would be happy to understand how this `Custom criteria` field works.
