### ISSUE TITLE
dbeaver stopped working with Athena

### ISSUE THREAD

**Issue by sravikrishna3** [dbeaver/dbeaver#15804]
#### System information: 
- Operating system (distribution) and version  : Windows 10 Pro
- DBeaver version Any version from 21.3.0 onwards
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version  Athena
- Driver name AthenaJDBC42_2.0.27.1001
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

Problem

dbeaver connecting to Athena via JDBC driver no longer working *only on windows*.  It works fine on Linux.
A simple select * from a table generates this error (attached file)

**Comment by sravikrishna3** [comment]
[](url
[athena_error.log](https://github.com/dbeaver/dbeaver/files/8232197/athena_error.log)
)

**Comment by LonwoLonwo** [comment]
Can be related to https://github.com/dbeaver/dbeaver/issues/5704

**Comment by sravikrishna3** [comment]
Not sure. It shows the catalog of Athena correctly, like the database list and the tables inside each tables. It is only when you run any sql it fails.
Also it is working fine on Linux.
I am 100% certain this was working on windows in 2020.

**Comment by serge-rider** [comment]
Error says `Unable to execute HTTP request: Connection reset`. It usually means that there are some problems with network connection. Athena connects directly to aws (e.g. to `athena.us-east-2.amazonaws.com`).

Are you behind a corporate firewall? Maybe some network settings were changed on your Windows machine.

**Comment by sravikrishna3** [comment]
Thanks serge.

1.  I tried ping to athena.us-east-2.amazonaws.com on both windows (where the problem is) and Linux machine (where I don't see this problem with dbeaver).  it failed on both.  Actually ping just blocks forever without returning anything.
As far as I know , athena is a serverless service and hence there is no concept of a server or ip address.
We may have to try some other option.
2. before I switched my office laptop to Windows, I had Mac.  There dbeaver was working great with Athena, within corporate firewall.
3. We are AWS customers and as such our firewall does take AWS into account.

thanks

**Comment by sravikrishna3** [comment]
Here is one more proof that from my corporate laptop is not behind any firewall to stop me from connecting to Athena.
![nc_to_athena](https://user-images.githubusercontent.com/44801660/159015052-554807b4-af46-4fd7-a941-c5c242bffdbf.png)

**Comment by sravikrishna3** [comment]
I ran the above command from the bash shell of my Windows laptop.

**Comment by sravikrishna3** [comment]
There is one more proof that my laptop-behind-corporate-firewall is a red-herring.
Check the screenhot.  I can query Athena to list out the databases , the list of tables in each and the cols of each table.  How is it possible if firewall is blocking access to Athena
![Screenshot 2022-03-29 085434](https://user-images.githubusercontent.com/44801660/160616092-b10e92d7-24ff-4a53-946c-4692e7b7c108.png)
.

**Comment by sravikrishna3** [comment]
Some more debugging.

When I run a query on dbeaver, I see that it gets executed on Athena and the result stored on the configured S3 bucket. However the next step of downloading the results from the S3 to be shown on dbeaver is failing.

**Comment by sravikrishna3** [comment]
Further testing.  I wrote a program using pyathena (which does not use Simba driver) and that works fine. So we can rule out any Firewall issue.  This is also not a dbeaver issue.  This is a Simba driver issue.
How do I open a case for Simba driver ?

**Comment by sravikrishna3** [comment]
Confirmed.  This is a AWS Athena driver error.  I flipped back to old drivers and dbeaver works.  I will open a case with AWS.

**Comment by LonwoLonwo** [comment]
Thanks for the investigation @sravikrishna3
