### ISSUE TITLE
add color coding to tabs (or some other way to distinguish the related connection)

### ISSUE THREAD

**Issue by jahlbornG** [dbeaver/dbeaver#15808]
**Is your feature request related to a problem? Please describe.**
I typically have tables open from multiple databases at the same time (qa and prod).  i have the connections for these databases color coded (yellow for qa and red for prod).  however, that coloring only shows up in the connection info at the top for the tab (table) that you are currently looking at.  when i have multiple "user" table tabs, i don't know which is qa and which is prod without clicking on each one.

**Describe the solution you'd like**
it would be fantastic if the connection coloring were somehow incorporated into the individual tabs (maybe a border, maybe a dot in the tab, maybe something else?).

**Describe alternatives you've considered**
There are various ways that the color could be included (mentioned above), but maybe there's some other way to distinguish the tabs/tables that i haven't thought up (tab groups per connection)?

**Additional context**

**Comment by ShadelessFox** [comment]
Hello @jahlbornG,

Your request looks pretty similar to this one: #15760.

Are you talking about the same thing?

**Comment by jahlbornG** [comment]
> Hello @jahlbornG,
> 
> Your request looks pretty similar to this one: #15760.
> 
> Are you talking about the same thing?

yep, definitely looks like the same feature request.

**Comment by ShadelessFox** [comment]
Okay, I'll close this issue, then.

You can track the linked issue.

**Comment by xavt** [comment]
This issue https://github.com/dbeaver/dbeaver/issues/16827 is the new one to follow for the connection colored tabs.
