### ISSUE TITLE
PostgreSQL: The bold highlighting of the current scheme disappears after executing the "Update" menu item

### ISSUE THREAD

**Issue by sharapov** [dbeaver/dbeaver#15816]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version:  22.0.0.202203060510

#### Connection specification:
- Database name and version: PostgreSQL 14.2 (Windows 10)
- Driver name: postgresql 42.2.20
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
The bold highlighting of the current scheme disappears after executing the "Update" menu item
#### Steps to reproduce, if exist:
There is a "MYSCHEMA" scheme. 
1. Run the command ALTER DATABASE postgres SET SEARCH_PATH="MYSCHEMA".;
2. I run beaver. I see the MYSCHEMA schema highlighted in bold
3. Right-click on the Schemes and select UPDATE
4. The selection disappears.

P.S. If I run the SET SCHEMA MYSCHEMA command, the selection will not appear either.

**Comment by LonwoLonwo** [comment]
Hello @sharapov 

Thanks for the bug report. I can reproduce it.

![ERBT26uRyJ](https://user-images.githubusercontent.com/45152336/158206780-1d604e13-0112-4fd4-b41a-c8184e578cee.gif)

Also, a refresh of a Database removes default schema selection too.
