### ISSUE TITLE
Can't scroll past already fetched rows after cancelling "persist changes" dialog

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#15812]
#### Describe the problem you're observing:
This is a side-effect of the feature implemented in #14187.

Having changes in the table while fetching next rows and pressing `Cancel` in the persist confirmation dialog you can't really load new rows even after manually saving or canceling changes.

The only solution is to refresh the editor.

#### Steps to reproduce, if exist:
1. Open a table
2. Edit something in it, so the editor becomes dirty
3. Scroll to the bottom, causing new data to load
4. Observe the confirmation dialog and press `Cancel`
5. Manually either save or cancel changes
6. Observe that you are still unable to load new rows

https://user-images.githubusercontent.com/35821147/158034806-d3a5d911-157a-4b5f-a5ea-1b3fd35b2943.mp4

**Comment by ShadelessFox** [comment]
This part of the code looks hacky:

https://github.com/dbeaver/dbeaver/blob/e937808170bdfcc603e1740f71f2db9dd0335acd/plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetViewer.java#L3575-L3578

**Comment by Matvey16** [comment]
Verified
