### ISSUE TITLE
[Hippie Engine] very slow SQL completion in sql script > 350kb

### ISSUE THREAD

**Issue by herbinator** [dbeaver/dbeaver#15820]
#### System information: 
- Operating system (distribution) and version Windows 10 21H2 19044.1586
- DBeaver version  22.0.0.202203060510
- Additional extensions

#### Connection specification:
- Database name and version      Postgress 11.7
- Driver name   maven:/org.postgresql:postgresql:LATEST
- Do you use tunnels or proxies (SSH, SOCKS, etc)? vpn

#### Describe the problem you're observing:
very slow SQL completion in sql script > 350kb and have to stop the background task

#### Steps to reproduce, if exist:
start typing select * from c
Then background task not completing: Search proposals, Seeking for SQL completion proposals: Find proposals

If seen it it first when upgrading to 21.3.4 and moved then back to dbeaver-ce-21.3.2-x86_64-setup. Skipped a few versions and see it now also in 22.0. Just foudn out it seems to have to do with the file size.

**Comment by Destrolaric** [comment]
@herbinator Hi, you can try to disable Hippie Engine autocompletion. It may cause lags with large scripts. If this will not solve the issue, please write back.
Window -> Preferences -> Editors -> SQL Editor -> Code Completion
![image](https://user-images.githubusercontent.com/20579256/158609076-d6b9c11d-af92-4e23-bee6-56297b5d9c32.png)
![image](https://user-images.githubusercontent.com/20579256/158608911-eb9685e8-06cf-456b-a4b8-687a82d7f8d1.png)

**Comment by herbinator** [comment]
yes disabling 'Hippie Engine autocompletion'  works very well

**Comment by Destrolaric** [comment]
We will look at how performance can be improved.

**Comment by jiangjihui** [comment]
Oracle also has this problem，when I disabling 'Hippie Engine autocompletion' works very well
![image](https://user-images.githubusercontent.com/18020779/159833982-8003e00c-c617-4630-ae4c-68cf849af93c.png)

DBeaver version 22.0.1.202203181646

**Comment by uslss** [comment]
verified
