### ISSUE TITLE
Unable to open SQLite database for new connection after upgrading to DBeaver 22.

### ISSUE THREAD

**Issue by davidhooey** [dbeaver/dbeaver#15827]
#### System information: 
- Operating system (distribution) and version
  -  MacOS 12.2.1  (Monterery).
- DBeaver version
  - DBeaver 22.0.0.202203060510
- Additional extensions
  - VRapper

#### Connection specification:
- Database name and version
  - SQLite 3.34.0
- Driver name
  - sqlite-jdbc-3.36.0.3
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
  - No

#### Describe the problem you're observing:

DBeaver 22 does not open SQLite database files. Worked in DBeaver 21.

#### Include any warning/errors/backtraces from the logs

1. In Projects - General right-click on Connections and select Create - Connection.

![image](https://user-images.githubusercontent.com/88926/158194375-aa17ef03-e90d-478e-beff-d66decef6f40.png)

2. Select SQLite and select Next.

![image](https://user-images.githubusercontent.com/88926/158194543-02265328-4fce-47ed-ad9b-797d9280b8be.png)

3. Select Browse and select an existing SQLite database file. The file dialog if a Save dialog as opposed to an Open dialog. If a database file is selected, DBeaver will prompt to replace the file as opposed to opening the file.

![image](https://user-images.githubusercontent.com/88926/158195404-4ecc81bf-a240-48c6-9c6a-d6ab2ad3a6b6.png)

![image](https://user-images.githubusercontent.com/88926/158195589-c1140a0a-d692-49df-9800-5e2865391ca2.png)

**Comment by ShadelessFox** [comment]
Hello @davidhooey,

This dialog is misleading. It **will not** overwrite nor replace your database file.

Please see discussion #15715.

We need to improve the UX because it confuses users.

**Comment by davidhooey** [comment]
The dialog changed in version 22. In version 22 the button is Save, where version 21 the button is Open.

![image](https://user-images.githubusercontent.com/88926/158223046-bbdba291-908a-4110-8cb0-5b74fdab2d43.png)

**Comment by ShadelessFox** [comment]
Yes, it was introduced in #14350.

**Comment by ShadelessFox** [comment]
Now buttons are separated:

https://user-images.githubusercontent.com/35821147/164457189-6a4cb9d4-f918-4ee1-8c69-93fc05addce4.mp4
