### ISSUE TITLE
Dbeaver still display functions that are deleted.

### ISSUE THREAD

**Issue by Gros-Jambon-Fr** [dbeaver/dbeaver#15826]
#### System information: 
- Operating system (distribution) and version : Debian 11
- DBeaver version : Version 22.0.0.202203060510
- Additional extensions

#### Connection specification:
- Database name and version PostgreSQL 13
- Driver name : php pgsql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

Hello, 

I'm working on some functions in my pgsql database. I've deleted some functions that i've created but dbeaver still display them in the functions sub-menu. if i right click and then delete, a pop up show up and says that "the function does not exist" so i can't delete it.
Even if i use DROP FUNCTION, same message regarding the not existing functon.

But the more annoying is that if i try to create another function with the name of the "supposed" deleted function, it says that i can't create it because the function already exists... so i'm kinda stuck in a loop.

the function i'm playing with are returning TABLE.

thanks for your help

**Comment by LonwoLonwo** [comment]
Hello @MattRGX 

Have you tried to refresh the "Functions" tab in the Database Navigator Editor? After function deleting.

![2022-03-14 18_23_44-DBeaver Ultimate 22 0 0 - playlist](https://user-images.githubusercontent.com/45152336/158204838-4353dcec-ba9f-4da9-a488-c88ac123ff23.png)

**Comment by Gros-Jambon-Fr** [comment]
> Hello @MattRGX
> 
> Have you tried to refresh the "Functions" tab in the Database Navigator Editor? After function deleting.
> 
> ![2022-03-14 18_23_44-DBeaver Ultimate 22 0 0 - playlist](https://user-images.githubusercontent.com/45152336/158204838-4353dcec-ba9f-4da9-a488-c88ac123ff23.png)

Yes i refreshed it many times.
I even deleted my connection and start from a fresh one. After connecting to my fresh new connection, the functions are still here and can't delete them.

**Comment by LonwoLonwo** [comment]
How do you delete your functions? Via DBeaver UI or in SQL Editor with the DROP statement?

**Comment by Gros-Jambon-Fr** [comment]
> How do you delete your functions? Via DBeaver UI or in SQL Editor with the DROP statement?

99.99% of the time, i do it via DBeaver UI.

**Comment by Gros-Jambon-Fr** [comment]
Another strange things just happened, still related to function that return TABLE.
I've created another function, the function is in the Functions menu in th UI. The function work well, it returns the rowset i ask for. Now i want to give EXECUTE permission on this function to a user. When i try to do that with the UI, i tick the box EXECUTE like that
![image](https://user-images.githubusercontent.com/58740578/158223600-ce17aff8-b092-470f-a610-7ab06096cf56.png)
 and when i try to persist my modification, DBeaver says that this function does not exists....
![image](https://user-images.githubusercontent.com/58740578/158223785-37c0b106-2ee6-4a9e-92b0-251db71372a6.png)

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**EDIT** : is [this issue](https://github.com/dbeaver/dbeaver/issues/2301) from oct 2017 related to mine ?

**Comment by LonwoLonwo** [comment]
About permissions - maybe the issue related to this https://github.com/dbeaver/dbeaver/issues/15563

Can you provide an example of your function DDL?

**Comment by Gros-Jambon-Fr** [comment]
> About permissions - maybe the issue related to this #15563
> 
> Can you provide an example of your function DDL?

`CREATE OR REPLACE FUNCTION declaration.get_crypto_symbol()
RETURNS TABLE(crypto_symbol character varying)
 LANGUAGE plpgsql
AS $function$
begin
	return query 
		select
			currency_name
		from
			declaration.declare_currencies
		where
			is_crypto
		order by id asc;
end;$function$
;
`

**Comment by Gros-Jambon-Fr** [comment]
So i managed to delete the persistent functions with DROP command.

in the UI sub_menu the function was displayed like this 

`get_crypto_symbol(varchar)`

but to delete it i had to use

`DROP FUNCTION get_crypto_symbol()`

without specifying the parameter between the parenthesis.

The thing is if i try to detele via the UI, the code generated is 

`DROP FUNCTION get_crypto_symbol(varchar)`

so i guess it's a bug from DBeaver.

If you want me to do more test, just let me know

**Comment by LonwoLonwo** [comment]
Yes, I see the issue with the incorrect DROP statement. And it is  related to https://github.com/dbeaver/dbeaver/issues/15563

We will fix it in the next release, I hope.

**Comment by LonwoLonwo** [comment]
Is there something in the error logs? https://github.com/dbeaver/dbeaver/wiki/Log-files
I am talking about the original issue, "DBeaver still displays functions that are deleted".

Also, what commit mode do you have?

![2022-03-15 15_36_40-DBeaver Ultimate 22 0 0 - _postgres12local_ Script-170](https://user-images.githubusercontent.com/45152336/158379118-3b119990-4728-4cc1-8d0a-7d3312f4bbe5.png)

**Comment by Gros-Jambon-Fr** [comment]
> Is there something in the error logs? https://github.com/dbeaver/dbeaver/wiki/Log-files I am talking about the original issue, "DBeaver still displays functions that are deleted".
> 
> Also, what commit mode do you have?
> 
> ![2022-03-15 15_36_40-DBeaver Ultimate 22 0 0 - postgres12local Script-170](https://user-images.githubusercontent.com/45152336/158379118-3b119990-4728-4cc1-8d0a-7d3312f4bbe5.png)

i couldn't find anything in the logs.

i have the same commits mode as the picture you shared.

**Comment by LonwoLonwo** [comment]
Does this error with other functions repeat for you? Or was this issue just once for one specific function?
Is this problem still persist?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual - feel free to reopen it with additional info.
