### ISSUE TITLE
DDL copy produces extra / invisible characters

### ISSUE THREAD

**Issue by dpsspatial** [dbeaver/dbeaver#15831]
#### System information: 
- Linux Mint 20.3
- DBeaver version: 22.0.0.202203060510
- Additional extensions: None

#### Describe the problem you're observing:

When copying the DDL from a view, the text contains extra blocks of blank/invisible characters. When formatting this pasted code, it won't format correctly and takes up several more lines than necessary. 

Here is pasted DDL from a view as seen in LibreOffice Writer with 'toggle formatting marks' turned on: 
![image](https://user-images.githubusercontent.com/12851723/158222943-dcf1159a-9f11-4cbc-8571-93909102ba4c.png)

And here is the SQL as DBeaver is trying to format it, but is out of line because of the extra characters: 

![image](https://user-images.githubusercontent.com/12851723/158223041-6ed061a5-4112-4fc9-87d4-5c4cbb8c7d77.png)

#### Steps to reproduce, if exist:
- with an existing view / materialized view, copy the DDL using the standard method (right click > generate SQL > DDL)
- past into a new DBeaver SQL editor window
- use the code formatter

**Comment by ShadelessFox** [comment]
Hello @dpsspatial,

Your text editor displays these invisible characters. I can see only paragraph symbols out there. They shouldn't cause any formatting problems.

Can you please provide your formatting settings? They can be found in the preferences: <kbd>Editors</kbd> &rArr; <kbd>SQL Editor</kbd> &rArr; <kbd>Formatting</kbd>.

**Comment by dpsspatial** [comment]
Hi @ShadelessFox,

Here's my SQL formatting settings, which otherwise work just fine - the extra spaces I'm reporting seem to conflict with these settings producing the result above: 

![image](https://user-images.githubusercontent.com/12851723/158421721-3d7eef11-dd3e-42c7-9ac8-4225d763e378.png)

Thanks!

**Comment by ShadelessFox** [comment]
Thanks.

It looks that this behavior was caused by the <kbd>Insert line feed before commas</kbd> option.

Can you try disabling it to see if it solves your issue? Thanks.

**Comment by dpsspatial** [comment]
Same result. 

Here is what the 'block' of invisible text is showing up as in DBeaver:

![image](https://user-images.githubusercontent.com/12851723/158423050-c8069ce8-a8e2-4f85-8095-80c62083b888.png)

**Comment by ShadelessFox** [comment]
The result is the same because your query was already formatted.

Don't be confused by this selection. It's typical behavior for all text editors. The paragraph (line break) symbol does not have any length, but visually it "breaks" the line. That's why you see this weird selection.

**Comment by dpsspatial** [comment]
This kind of block of text doesn't show up in SQL that I've created from scratch or loaded from a saved file. It only shows up when I copy the DDL of a view/materialized view and paste it into an editor. Normal SQL formats just fine, with the settings I have in the formatter. The pasted DDL SQL is the issue.

**Comment by ShadelessFox** [comment]
Let's make sure that we are talking about the same thing.

Is that the block of text you have mentioned earlier?

https://user-images.githubusercontent.com/35821147/158586740-be750287-ebaa-4bf9-b47c-b3d08e35be63.mp4

**Comment by ShadelessFox** [comment]
Can you please send me a screenshot of the <kbd>General</kbd> &rArr; <kbd>Workspace</kbd> preference page and a file containing the exported view definition if it doesn't contain any sensitive data? Please note that It must be a file. Pasting it here will not work. To achieve this, you can use <kbd>Export SQL script</kbd> action found in the context menu.

**Comment by dpsspatial** [comment]
Thanks for your patience...!

In your animation, while you're selecting lines that are empty and likely a single ' '... hopefully the script I attached can demonstrate the issue. Keep in mind that if you aren't formatting with the 'insert line feed before comma' option checked, you won't notice the issue... my default formatting method is this way so I never have to look for a comma at the end of a line in a select, etc.

[GitHub_Issue_Sample.sql.zip](https://github.com/dbeaver/dbeaver/files/8264345/GitHub_Issue_Sample.sql.zip)

And here's the Workspace window: 

![image](https://user-images.githubusercontent.com/12851723/158626494-ddfe4ca1-6412-4f85-9c27-bc66bb38d7e5.png)

**Comment by ShadelessFox** [comment]
I wanted to ensure that line delimiters are the same as shown in preferences, and they indeed are the same.

Let's go the other way. Are you sure that formatting any other snippet results in a different output? Something like this should do the trick:
```sql
select
    1,
    2,
    3,
    4;
```

If not, maybe the behavior was changed in the previous versions of DBeaver?

**Comment by dpsspatial** [comment]
That formatting works, but is basically just hiding the block behind the comma so you don't realize its there; 


select
    1, ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
    2, ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
    3, ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
    4; 


With 'insert line feed before comma' is doing this:


select
	1
	, ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
    2 
	, ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
    3
	, ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
    4;

**Comment by ShadelessFox** [comment]
Hello @dpsspatial,

Sorry for the very late response.

To get rid of excess lines just disable the `insert line feed before comma` option.

This is expected behavior, so I'm not sure what the issue is. Please let me know if you have any questions left.

**Comment by dpsspatial** [comment]
Well thanks for digging into this - much appreciated - I guess I'll have to deal with the issue as I live by my commas at the front of the line!!! Thank you again!!!
