### ISSUE TITLE
SQL Server does not display data selected from table variable or #temp table

### ISSUE THREAD

**Issue by igorzhilin** [dbeaver/dbeaver#15844]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 22.0.0.202203060510

#### Connection specification:
- Database name and version: SQL Server 2016
- Driver name: MS SQL Server / SQL Server

#### Describe the problem you're observing:
When selecting from table variable or temp table (`#temp` preceded by hash), dbeaver does not display data in the grid. It only shows execution statistics.
Table variable:
![image](https://user-images.githubusercontent.com/9438635/158406165-97223906-ccac-4d04-9912-e909da2fc584.png)
Temp table:
![image](https://user-images.githubusercontent.com/9438635/158407066-09fa4872-6446-4007-b60c-11c8676e06b3.png)

Running the select from the insert part still works.
![image](https://user-images.githubusercontent.com/9438635/158406451-1e1da8f3-6285-4446-b947-d0e93cede7e5.png)

In SSMS, this works out of the box.
![image](https://user-images.githubusercontent.com/9438635/158405856-573c698c-a04a-4716-8de9-246064fa5ba2.png)
![image](https://user-images.githubusercontent.com/9438635/158407319-db1998ef-0aa1-4037-88be-c091e7d231d1.png)

#### Steps to reproduce, if exist:
```
declare @dbNames table (dbName nvarchar(255));
insert @dbNames 
select [name] from sys.databases where database_id < 5;
select * from @dbNames;
```
You will not see grid, you will only see the stats.

**Comment by ShadelessFox** [comment]
Hello @igorzhilin,

I cannot reproduce your issue. It executes just fine by selecting everything and hitting <kbd>Ctrl+Enter</kbd> afterwards:

![image](https://user-images.githubusercontent.com/35821147/158418313-c7d4a66d-19f0-40dc-aaeb-4231f85bbd6d.png)

Can you please provide more details or record a video? Thanks.

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info
