### ISSUE TITLE
error in priviliges describe. Priviliges on procedure

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#15858]
Postgresql 12
Dbeaver 22.0.0

1. added any symbols 

_209868
_29481
...
to the end of procedure name

![image](https://user-images.githubusercontent.com/61137576/158567001-f822646e-6848-4c80-a322-80863156aecb.png)

2.
dbeaver generated this priviliges script

![image](https://user-images.githubusercontent.com/61137576/158569615-29c5c7c1-d74a-487d-afa2-666fd65fd531.png)

but 'backups.del_proc_get_notice_statistics' it is not a function!!
![image](https://user-images.githubusercontent.com/61137576/158569811-8ec1bc11-21da-4946-88e1-4b6e0b35535b.png)

it is procedure. Script is wrong.

**Comment by LonwoLonwo** [comment]
I see functions names are incorrect in the role source tab. And their names are correct in the functions source tab.

![2022-03-16 14_06_40-DBeaver Enterprise 21 3 3 - employee_insert_trigger_fnc()](https://user-images.githubusercontent.com/45152336/158604387-05892efe-81ec-4e4f-89d7-ac3c923b6a7c.png)

![2022-03-16 14_07_08-DBeaver Enterprise 21 3 3 - test_as](https://user-images.githubusercontent.com/45152336/158604394-57632ac1-1a9f-475f-b90b-c1757ad6e7ce.png)

Thanks for the bug report @detkliff
