### ISSUE TITLE
SQL Error : internal jdbc driver error

### ISSUE THREAD

**Issue by Jaiswalakshat20** [dbeaver/dbeaver#15853]
DBeaver 21.1.3
Class  ame : com.amazon.redshift.jdbc42.Driver
Lib RedshiftJDBC42.jar
Port 5439

Getting error -- SQL Error : internal jdbc driver error

No issue seems with code. I conclude this because when I remove a when condition among other within a query , I am able to compile the procedure.

**Comment by uslss** [comment]
@Jaiswalakshat20 please provide clear steps to reproduce an issue. also, error logs and screenshots will be helpful

**Comment by Jaiswalakshat20** [comment]
Issue is with my DBeaver session only as I am able to compile.with other team members but not sure how to resolve this as I have reinstall but issue persist.

**Comment by Jaiswalakshat20** [comment]
> 
![Uploading IMG_20220317_152759.jpg…]()

**Comment by uslss** [comment]
@Jaiswalakshat20, unfortunately, the picture isn't available. Could you provide more info? E.g,. logs, video with the issue

**Comment by uslss** [comment]
There has been no update on the issue for a long time.  If it is still reproducible - feel free to reopen it
