### ISSUE TITLE
Missing schema list for catalog/schema pop up

### ISSUE THREAD

**Issue by NikolaCoder** [dbeaver/dbeaver#15869]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
21.1.3
- Additional extensions

#### Connection specification:
- Database name and version Sybase ASE
- Driver name
Jconnect
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No
#### Describe the problem you're observing:
Since this version the Catalog/Schema pop up shows the database list but nothing in the right schema pane, not even the heading. 
#### Steps to reproduce, if exist:
Connect to a Sybase server and press Ctrl 0.

**Comment by nickali2** [comment]
the issue still available in version 22

**Comment by LonwoLonwo** [comment]
Hello.

Can the scheme be made default in Sybase? If not, why should schemas be shown if they cannot be chosen as default?

**Comment by NikolaCoder** [comment]
Yes - the schema can be made default. The issue is this popup is used to select database and because it's expecting to see a schema in the right pane, it is impossible to select a database. The popup dialog is broken for Sybase connections from this version forward ( incl V22 )
