### ISSUE TITLE
BEGIN TRANSACTION; does not get parsed correctly in SQL Editor

### ISSUE THREAD

**Issue by bobf32** [dbeaver/dbeaver#15868]
#### System information: 
- Windows 10 Pro build 19044.1586
- DBeaver version 21.1.4
- Additional extensions: No

#### Connection specification:
- Snowflake
- Driver name: Standard
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

```BEGIN TRANSACTION;``` statement does not appear to get parsed correctly in a SQL editor in certain circumstances.

#### Steps to reproduce, if exist:

Open a Snowflake database connection.

Open a SQL Editor.

Enter the following in the editor:

```
BEGIN TRANSACTION;

SELECT 1 FROM DUAL;
```

With the cursor on the ```BEGIN TRANSACTION;``` hit Ctrl-Enter. Briefly, blue arrows are shown against all lines in the SQL editor, including the ```SELECT 1 FROM DUAL;``` and then an error is produced:

```
SQL Error [8] [0A000]: Actual statement count 2 did not match the desired statement count 1.
```

NB: If the entire line ```BEGIN TRANSACTION;``` is selected before pressing Ctrl-Enter the statement completes successfully.

**Comment by E1izabeth** [comment]
Thank you for the bug report!

**Comment by bobf32** [comment]
@E1izabeth You're very welcome. Thanks for addressing it :)
