### ISSUE TITLE
Using a task to import a csv file fails if columns are case sensitive

### ISSUE THREAD

**Issue by gregoryforel** [dbeaver/dbeaver#15860]
#### System information: 
- Linux Mint 20.3 Cinnamon
- DBeaver 22.0.0.202203060510 Community Edition

#### Connection specification:
- PostgreSQL 13
- Drivers: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I have an existing table with those columns:
`id: text`
`organizationKey: text`

I can't import a CSV file **using a task** because columns are case sensitive. `organizationKey` has a non null clause, and since DBeaver ignores case-sensitive columns, it creates a new `organizationkey` column instead of mapping to the right one.

**csv file:**
```csv
"id","organizationKey"
edlund,"680456df-8330-4c09-8cfe-33daf0bd3f0f"
```
**Note that doing the exact same steps manually work**. If I save this as a task and run it, it fails for the reason mentioned above.

#### Steps to reproduce, if exist:
- Create a db with 1 case-sensitive column, eg `Key`
- Create a csv file
- Start the steps to import it, save a task
- Run the task: fails.

#### Include any warning/errors/backtraces from the logs
```
SQL Error [23502]: Batch entry 0 INSERT INTO public."processModel" (id,organizationkey)
	VALUES ('edlund','680456df-8330-4c09-8cfe-33daf0bd3f0f') was aborted: ERROR: null value in column "organizationKey" of relation "processModel" violates not-null constraint
```

**Comment by Matvey16** [comment]
@gregoryforel Thank you for the report

**Comment by ShadelessFox** [comment]
I believe that this is an expected result (the case depends on the target database).

Column mappings can be configured in the data transfer wizard.
