### ISSUE TITLE
[MSSQL] Refreshing triggers causes hang

### ISSUE THREAD

**Issue by anophelesgreyhoe** [dbeaver/dbeaver#1587]
I am working with triggers on Microsoft SQL Server 2008, and after creating a trigger in the SQL Editor, if I go to the DB navigator -> Table -> Triggers view (which I already had open) and press F5 to refresh, DBeaver hangs and then eventually displays an error like the attached image.

Note: I am using DBeaver CE 4.0.5, and I have the same result on multiple different computers connecting to multiple databases.

![error_refreshing_node_mssql_triggers](https://cloud.githubusercontent.com/assets/11037075/25167129/5b290356-2532-11e7-9643-50a26a413ca6.png)

**Comment by serge-rider** [comment]
Can't reproduce. Do you see this problem with all tables?
Note: when you refresh triggers view all table properties are refreshed. Maybe some queries are conflicting/lead to dead-lock or something.
Could you check Query Manager view (with metadata queries enabled) to see what is DBeaver actually tries to do?
