### ISSUE TITLE
Top filter doesn't work when an alias is used for column name in the ResultSet

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#15885]
#### System information: 
- DBeaver version 22.0.0

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:

1. Execute a select statement with a column alias (e.g. for pagila `select t1.acc_code as acc, t2.customer_id as cus from public.account t1, public.customer t2 where t1.acc_id = t2.customer_id`)
2. Apply a filter in the top filter field

**Expected**: the filter is applied and the result is displayed
**Actual result**: the error appears "column .. doesn't exist"

https://user-images.githubusercontent.com/51405061/158961481-32606c46-b143-429a-a135-6fdbda9800bc.mov

**Comment by LonwoLonwo** [comment]
Works as expected.

You can write anything if you want in this manual filter panel. And DBeaver just put it in your original statement with WHERE condition. So it means, that proper behavior is - to enter the correct name of the column in this place.

![2022-03-30 11_33_27-Top filter doesn't work when an alias is used for column name in the ResultSet ·](https://user-images.githubusercontent.com/45152336/160792657-cb67d610-ac71-4393-a26d-9c08fe068794.png)
