### ISSUE TITLE
Preferences - some tabs has incorrect font size (very small)

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [dbeaver/dbeaver#15887]
preferences - general - install/update - trust
preferences - general - workspace - build
preferences - connections - connection types
preferences - connections - drivers
preferences - connections - drivers - classpath
preferences - connections - drivers - maven
preferences - connections - drivers - postgresql
preferences - editors
preferences - editors - data editor - binaryl editor - hex editor
preferences - editors - data editor - gis viewer
preferences - editors - sql editor - code editor

and other
![ss_2022_03_18__12_53_06](https://user-images.githubusercontent.com/25248634/158971815-eb6e514d-3e4d-4293-9c2e-ff98f0d38f06.png)

**Comment by uslss** [comment]
@aleksandr-shevchenko what dbeaver version and OS do you use?

**Comment by aleksandr-shevchenko** [comment]
Win10, latest version of DBeaver.
preferences - user interface - appearance - colors and fonts - I set "dialog font" to "Dejavu Sans Mono 14", but not all tabs changes own font.

**Comment by aleksandr-shevchenko** [comment]
> @aleksandr-shevchenko what dbeaver version and OS do you use?

Win10, latest version of DBeaver.
preferences - user interface - appearance - colors and fonts - I set "dialog font" to "Dejavu Sans Mono 14", but not all tabs changes own font.

**Comment by ShadelessFox** [comment]
https://github.com/dbeaver/dbeaver-ee/pull/1645

**Comment by Matvey16** [comment]
Preference page shows everithing correct, but we need to update other dialogs #16552 16552

**Comment by aleksandr-shevchenko** [comment]
![ss_2022_05_23__08_46_11](https://user-images.githubusercontent.com/25248634/169745675-8dc67baf-61d3-4a5f-b171-95d15512f2f4.png)
![ss_2022_05_23__08_46_43](https://user-images.githubusercontent.com/25248634/169745687-90d8cc30-1eb7-49dc-93e4-f76401e92774.png)
![ss_2022_05_23__08_47_21](https://user-images.githubusercontent.com/25248634/169745691-7a47cc42-b9f4-4c43-8b31-e85890ce57f6.png)

And other dialog in 22.0.5...

**Comment by ShadelessFox** [comment]
Fix is postponed for the next release.

**Comment by aleksandr-shevchenko** [comment]
ver.22.1.1
Is this the next release? Or should we wait another year?
<img width="935" alt="ss_2022_07_08__09_54_44" src="https://user-images.githubusercontent.com/25248634/177926523-b5428eab-b389-48e1-86e1-b17e25a18856.png">

**Comment by ShadelessFox** [comment]
Hello @aleksandr-shevchenko,

We can't fix font issues on that particular page. It comes from Eclipse.
