### ISSUE TITLE
Hyphen in table name doesn't allow to use a hyperlink in SQL Editor

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#15886]
#### System information: 
- DBeaver version 22.0.1

#### Steps to reproduce, if exist:
1. Create a table with a hyphen in it's name. e.g. `new-table`
2. Type a select with a table's name in SQL Editor
4. Press Ctrl on a keyboard and hover mouse cursor above the table name

**Expected:** The name becomes a hyperlink and can be clicked
**Actual:** The name can't be clicked 

![dbeaver_YQ4MfvDhGO](https://user-images.githubusercontent.com/82543000/158969101-2ab78fba-104f-493d-8dc8-b721f5ef8a05.gif)

**Comment by ShadelessFox** [comment]
Seems similar to #12043
