### ISSUE TITLE
Labels "Description" and "Settings" overlapping in Edit Driver Panel

### ISSUE THREAD

**Issue by eric-daitan** [dbeaver/dbeaver#15889]
#### System information: 
- Operating system (distribution) and version: Linux 5.14.0-1027-oem 30-Ubuntu SMP Mon Mar 7 15:00:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- DBeaver version: 22.0.0.202203060510
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : Yes

#### Describe the problem you're observing:
Labels "Description" and "Settings" overlapping in Edit Driver Panel as follow:
![image](https://user-images.githubusercontent.com/97167381/159013530-9c848b80-3765-4300-ab39-f3cf14429cd4.png)

#### Steps to reproduce, if exist:
Download PostgreSQL driver and edit it

#### Include any warning/errors/backtraces from the logs

Don't apply

**Comment by ShadelessFox** [comment]
Hello @eric-daitan,

That's weird because there's no such label `Description` on this page whatsoever (as on other pages).

![java_86PKJOhonW](https://user-images.githubusercontent.com/35821147/159028512-3b57395c-63a1-49a4-a8ad-46db84c7aa36.png)

Does reopening this dialog solve the issue?

**Comment by ShadelessFox** [comment]
As it turned out, there was a hidden group underneath:

![image](https://user-images.githubusercontent.com/35821147/159138224-8df9caea-604b-4888-94ad-6245001747fd.png)

**Comment by Matvey16** [comment]
Verified
