### ISSUE TITLE
wrong describe and permission in create function script

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#15893]
postgresql 12
DBeaver 22.0.0

![image](https://user-images.githubusercontent.com/61137576/159108849-e1591fd7-e7c8-4e37-86c2-06cabc9b2dd3.png)
in this example only one function parameter.
"in" and "out" parameter together in function parameters it is wrong, it is error!

**Comment by uslss** [comment]
thanks for the report
probably related with #14196

**Comment by ShadelessFox** [comment]
Hello @detkliff,

Can you please provide a sample DDL of such a function?

**Comment by uslss** [comment]
there has been no update on the issue for a long time.
If it is still actual - feel free to reopen it.
