### ISSUE TITLE
Folder drag issue with navigation window 导航窗口的文件夹拖动问题

### ISSUE THREAD

**Issue by java2job** [dbeaver/dbeaver#15892]
当导航界面都只有文件夹时，无法将二级文件夹拖出来变成一级文件夹。 例如下图，“test”文件夹没办法拖出来和“boc”同级。
When there are only folders in the navigation interface, the second-level folder cannot be dragged out to become the first-level folder. For example, in the figure below, the "test" folder cannot be dragged out and is at the same level as "boc".
![image](https://user-images.githubusercontent.com/37571203/159041851-43596353-36b7-4439-9c85-cec98de4a9bb.png)

当存在一个连接时，就可以实现拖动
When a connection exists, dragging is possible
![image](https://user-images.githubusercontent.com/37571203/159042146-fa6d7410-98f5-407e-967b-216d4ba13444.png)

![image](https://user-images.githubusercontent.com/37571203/159042178-776e61b4-979a-4072-bbd2-f9e34fe50506.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by mxmlnglt** [comment]
Hello, just also have this problem for a few days now.

Workaround is: move any connection to the root, then drag folders to root, then move back again the connection where it belongs.
