### ISSUE TITLE
SSH key password is not asked, auth fail

### ISSUE THREAD

**Issue by AqlaSolutions** [dbeaver/dbeaver#15899]
Version: 22.0.0.

I have a posgtresql connection with ssh tunnel. No password is stored neither for SSH key nor for db. When I try to connect there I'm asked for a db username (which is stored and pre-filled) and one password.

If I input DB password there I see "Can't initialize tunnel: Auth fail" error.

If I input SSH key password there instead then I see an error: "The server requested password-based authentication, but no password was provided."

There is only one password prompt.

If I set db password in the settings so it's saved then I'm correctly asked for SSH key password and everything works fine.

Mind that SSH key password and db password are different.

Expected behavior:
The app should ask both for db password and SSH key password.

**Comment by uslss** [comment]
@AqlaSolutions , unfortunately cannot reproduce the issue. Did you uncheck Save password option both at connection and SSH tabs?
![image](https://user-images.githubusercontent.com/31996417/159242343-83276351-0a8a-4890-8a4d-3c59a7fad53b.png)
![image](https://user-images.githubusercontent.com/31996417/159242414-2b82611d-c28a-4ce1-89fc-18540fda0bb9.png)

**Comment by AqlaSolutions** [comment]
Yes, they are both unchecked.

In SSH tab you need to specify host, port, user, auth method: public key, private key file path.

**Comment by uslss** [comment]
thanks for the report and clarification

**Comment by sgargel** [comment]
I have a similar issue. SSH save password is unchecked and the field is empty but I'm not asked for SSH passphrase and connection is failing.

![image](https://user-images.githubusercontent.com/24651376/175251176-a33f433f-8c61-4412-8df1-d41d0194ab39.png)

I think that when the SSH save password box is unchecked the field should be grayed out.

**Comment by cloutierjo** [comment]
I also have that issue. a bit more info, 
I'm using the sshj implementation
I'm using the network profile feature ( I have 3 different database going true the same ssh host)
If I set the password without checking the save password box, it does work well until I restart the software (which is expected) but next the only way to reconnect is to reopen the network profiles page to set the password again (I'd expect a password prompt when connecting to a db using that profile)
I'm running archlinux uptodate and dbeaver 22.1.2

detailed config (sorry for the french ui:
![Screenshot_20220803_113624](https://user-images.githubusercontent.com/3165230/182649522-54281a33-448c-47e5-9b11-46584458c614.png)

**Comment by knnat** [comment]
Version 22.2.5
Still not ask for the SSH key passphrase and instead getting connection failed dialog.

**Comment by knnat** [comment]
> Version 22.2.5 Still not ask for the SSH key passphrase and instead getting connection failed dialog.

It turns out dbeaver has good support only for rsa encrypted key but isnt good for pkcs8. When the ssh key encrypted using e.g. openssl rsa -aes256 -in ssh.key -out enc.key (with Save Password/Passphrase unchecked) there is prompt for passphrase when connecting as it should.

**Comment by ccatterina** [comment]
I've the same problem with version 22.3.5.202302180832
