### ISSUE TITLE
Performance issue with table data preview during import/export

### ISSUE THREAD

**Issue by ThadeusAnand** [dbeaver/dbeaver#15895]
In the data transfer wizard, in the Tables Mapping screen, we have a Preview Data button.

When we click on this button, the preview is supposed to fetch only 100 rows.

But if the table is huge, the preview takes too long. Looks like it is trying to scan the entire table before fetching 100 rows.

Sometimes we accidentally click the preview button and end up waiting for a long time. 

I once cancelled the operation in the middle, but it did not cancel out immediately and I had to terminate the application. Later I found that if I cancel the operation, it does cancel, but does not let us know in any way that the operation has been cancelled, and we simply end up waiting for something to happen.

**Comment by uslss** [comment]
@ThadeusAnand what database do you use?

sorry for the late response

**Comment by ThadeusAnand** [comment]
Postgresql 14 on CentOS 7

**Comment by uslss** [comment]
is it still reproducible against 22.0.4?

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual - feel free to reopen it with additional info
