### ISSUE TITLE
Wiki article "Develop in Eclipse" misses information about workspace

### ISSUE THREAD

**Issue by stollr** [dbeaver/dbeaver#15890]
I am not sure if this is the correct place to report issues in the Wiki. But I will try anyway :-)

I am a complete newbie in things of Java development. But I want to debug an issue that seem to exist only on my machine.
I followed this guide https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse to setup Eclipse and run DBeaver.

When it comes to step 6 ("Check out the DBeaver repository somewhere with the git clone https://github.com/dbeaver/dbeaver.git command.") I cloned dbeaver somewhere in my home directory.
But after completing step 14, Eclipse complained about many "cannot resolve ..." issues. After some research I found [this article](https://github.com/dbeaver/dbeaver/discussions/12783#discussioncomment-908680) saying, that dbeaver has to be cloned into the Eclipse workspace.

After doing that, all the errors disappeared.

Maybe someone could change the sentence in the wiki to something like that:

"Check out the DBeaver repository in your *Eclipse workspace* with the git clone https://github.com/dbeaver/dbeaver.git command."

**Comment by E1izabeth** [comment]
I'd prefer to not clone the repo into Eclipse workspace. You may want to clean eclipse workspace or use several eclipse workspaces at once, but have the one source repo. Thae cause of the issues you experienced with development environment configuration can't be the location of the repo. That's definetely not a good idea to add it to the wiki.

**Comment by stollr** [comment]
Okay, thank you for clarification.
