### ISSUE TITLE
Cannot load .sql file "input length = 3"

### ISSUE THREAD

**Issue by Zabbah** [dbeaver/dbeaver#15906]
#### System information: 
- Operating system (distribution) and version: Windows 10 
- DBeaver version: 22.0.1
- Additional extensions

#### Connection specification:
- Database name and version: Oracle 11g
- Driver name: Thin
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

I cannot import some SQL scripts, some work some don't. When they don't, I've got the message: _"Can't load file 'C:\Users\...\script.sql' - Input length = 3"_

I have this issue since Dbeaver versión 21.3.3. With 21.3.2, all of my SQL script work like a charm.

#### Steps to reproduce, if exist:

Connect to DB using "SQL Editor" - "Open SQL script". 
In editor, right click and go to "File" - "Import SQL script". Select a .sql file. If it works, it will load your file, if not, you've got "input file = 3" error.

#### Include any warning/errors/backtraces from the logs

!ENTRY org.jkiss.dbeaver.model 4 0 2022-03-21 13:27:11.247
!MESSAGE Can't load file 'C:\Users\XXXXXXXX\Script.sql' - Input length = 3

**Comment by uslss** [comment]
@Zabbah unfortunately, cannot reproduce it. Probably you could provide some sample SQL file that doesn't open?

**Comment by Zabbah** [comment]
@uslss I think I have found the cause: If the sql file has a character with accent mark, like á, é, í, ó, ú, it gives an error.
This didn't happen in version 21.3.2 and olders.

[Samples.zip](https://github.com/dbeaver/dbeaver/files/8323938/Samples.zip)

**Comment by Zabbah** [comment]
I think I have found the cause: If the sql file has a character with accent mark, like á, é, í, ó, ú, it gives an error.
This didn't happen in version 21.3.2 and olders.

**Comment by eliezerjrs** [comment]
> 

hey Zabbah, I couldn't spot any difference between the two .sql :

-- this works

select *
from lala.names
where surname is "SMITH";

-- this does not works because it has a character with accent mark

select *
from lala.names
where surname is "SMITH";

I'm having the same problem loading .sql files into the script executive tool since versions 22.0, but the error message is slightly different:

"Can't load file 'C:\Users\Testes\Desktop\itens.sql' - Input length = 1"

**Comment by Zabbah** [comment]
> > 
> 
> hey Zabbah, I couldn't spot any difference between the two .sql :
> 
> -- this works
> 
> select * from lala.names where surname is "SMITH";
> 
> -- this does not works because it has a character with accent mark
> 
> select * from lala.names where surname is "SMITH";
> 
> I'm having the same problem loading .sql files into the script executive tool since versions 22.0, but the error message is slightly different:
> 
> "Can't load file 'C:\Users\Testes\Desktop\itens.sql' - Input length = 1"

Oh sorry, yes they are the same query 😂

Query working: select * from lala.employees where surname="Garcia"
Query not working: select * from lala.employees where surname="Gárcia"

Note the letter "a" with accent mark "á"

**Comment by siberiun** [comment]
hey zabbah

Thanks. Here solved my problem.
