### ISSUE TITLE
Less obtrusive Problems-window

### ISSUE THREAD

**Issue by timxsarus** [dbeaver/dbeaver#15904]
**Is your feature request related to a problem? Please describe.**
Since installing version 22.0.1.202203181646 the Problems-windows behaves differently.
- It opens over the sql-editor window once the user executes a query with a syntax error (or any other problem) partly obscuring the query.
- It claims focus.
- It displays the errors in a collapseable list and leaves it collapsed.

This behaviour makes it a pain to use. If the query contains any errors I now need to expand the list of error which will often contain one message. After that I need to click the sql-editor to change Dbeavers focus before I can make the corrections. 

**Describe the solution you'd like**
I would like to have Dbeaver retain the focus on the sql-editor so I can quickly make corrections without having to touch my mouse.
I would like to see the error instantly without having to expand a list. Perhaps in a flash-message like manner.

**Describe alternatives you've considered**
I've considered moving the Problems window to the lower part of the screen, so that at least it is not displayed over my query. But this resets to the right side once I minimise the Problem window.

**Additional context**
Version: 22.0.1.202203181646

**Comment by uslss** [comment]
@timxsarus unfortunately, cannot reproduce it. Could you provide a video with the issue?

**Comment by timxsarus** [comment]
I've made a short video which will hopefully make it a bit more clear: https://www.youtube.com/watch?v=W7xyT6Bxw2A

**Comment by mo3ul** [comment]
I agree, very annoying functionality! I rollback upgrade and wait until it fixes!

**Comment by uslss** [comment]
Since 22.0.2 this feature could be disabled in preferences (#15961)
![image](https://user-images.githubusercontent.com/31996417/161509328-15fd6205-faff-4113-a480-1d9a8fc505c9.png)

**Comment by KostyaTretyak** [comment]
This is realy obtrusive window. I think by default it should be disabled.
