### ISSUE TITLE
DDL for partitions for partitioned tables on postgresql 10+

### ISSUE THREAD

**Issue by esmin** [dbeaver/dbeaver#15905]
#### System information: 
- Operating system: any

#### Connection specification:
- PostgreSQL 10+ (partition support)

#### Describe the problem you're observing:
DDL for partitioned table does not include partitions DDL. PostgreSQL does not create partitions automatically
![image](https://user-images.githubusercontent.com/6398941/159259060-58008461-b9d3-4da3-b1b0-e5e8506b0663.png)
Expected: DDL settings to have partitions checkbox to (not) include partitions DDL for partitioned tables

**Comment by LonwoLonwo** [comment]
Thanks for the idea @esmin
