### ISSUE TITLE
Can not connect to MSSQL server and Postgres after upgrade to 22.0.1

### ISSUE THREAD

**Issue by maptile** [dbeaver/dbeaver#15903]
#### System information: 
- Operating system (distribution) and version: Ubuntu 21.10
- DBeaver version: 22.0.1.202203181646
- Additional extensions: no

#### Connection specification:
- Database name and version: Don't know
- Driver name: MSSQL and Postgres
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Describe the problem you're observing:

I'm using 22.0.0 snap, this version is perfectly fine, it can connect to my MSSQL server and Postgres.

When DBeaver auto upgraded to 22.0.1 by snap, I found it can not connect these DB anymore.

The following dialog appears when I connect to my DB.
![image](https://user-images.githubusercontent.com/28569363/159237547-d163e247-07b9-4f00-a465-b0561d4580b5.png)

Click "OK" to close the dialog. And this dialog appears.
![image](https://user-images.githubusercontent.com/28569363/159237674-68fd8e9e-7e3d-4687-9617-8e9155bf9e6a.png)

When click "Download" button, it says:
![image](https://user-images.githubusercontent.com/28569363/159237729-364b7353-94e4-4f31-b508-d0366d88f0c7.png)

When connect to Postgres, it says:
![image](https://user-images.githubusercontent.com/28569363/159237765-17775959-7346-4b62-9adb-541a2678ff09.png)

#### Steps to reproduce, if exist:

Just connect to DB.

**Comment by maptile** [comment]
It seems works now without any change and DBeaver version is still 22.0.1. I don't know what's the real problem.

**Comment by LonwoLonwo** [comment]
Maybe some problems with the connection.
