### ISSUE TITLE
Feature request: automatic download last version

### ISSUE THREAD

**Issue by jba31** [dbeaver/dbeaver#1590]
Hi,
There have been many versions recently and 
I'd like to be able to automatic download last version and launching exe file (if a new version is available) 
when I click on check update button

![image](https://cloud.githubusercontent.com/assets/12907635/25223525/e5073e06-25bb-11e7-869d-eb78920cbb54.png)

Thanks for you reply

**Comment by serge-rider** [comment]
Yes, this makes sense.

**Comment by jbatmall** [comment]
Hi,
Could you add proxy settings (host/port) ?
Thanks

**Comment by kseniiaguzeeva** [comment]
Duplicates https://github.com/dbeaver/dbeaver/issues/6558. I close this ticket because #6558 has more detailed description.
