### ISSUE TITLE
[H2] DDL can't be generated for system views

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#15918]
#### System information: 
- Win11
- DBeaver CE 21.0.1

#### Connection specification:
- H2 v2 Embedded

#### Describe the problem you're observing:
In default views in H2 you can see an error:
![image](https://user-images.githubusercontent.com/43252954/159370257-2eb4ab44-2f1d-475d-bebc-d9e780cc9ec7.png)
(In the new created views you can see a DDL correctly)

#### Steps to reproduce, if exist:
Open metadata tab for a system view:
![image](https://user-images.githubusercontent.com/43252954/159370197-85148314-8416-4d30-879a-d2c38a1a0f5b.png)
and then select the Definition tab.
There you can see an error showed in the view DDL comment

#### Error message
```
Can't generate DDL: table editor not found for org.jkiss.dbeaver.ext.generic.model.GenericView;
```

**Comment by LonwoLonwo** [comment]
![2022-03-22 11_49_53-DBeaver 22 0 1 - CHECK_CONSTRAINTS](https://user-images.githubusercontent.com/45152336/159443638-45ad03a4-1548-4547-bd68-52fdfe910829.png)

VIEW_DEFINITION field is empty for system views in the INFORMATION_SCHEMA.VIEWS, therefore, no more system views definitions reading.

**Comment by uslss** [comment]
verified
