### ISSUE TITLE
Cannot connect to ORCL database 

### ISSUE THREAD

**Issue by KornelPudlo** [dbeaver/dbeaver#15917]
Hi,

I just downloaded DBeaver and I'm trying to connect to ORCL database. 

Basically...not sure what to do. It seems that all drivers are fine. 

Any suggestions?

 
![image](https://user-images.githubusercontent.com/102041440/159369807-3a000e6e-88ca-49af-80d7-1f4761568d65.png)

FYI : I am just beginning my journey with databases and DBeaver so please be understanding. 

Thx, 
Geo

#Dbeaver

**Comment by uslss** [comment]
probably, something helpful could be found here https://community.oracle.com/tech/developers/discussion/4339528/io-error-the-network-adapter-could-not-establish-the-connection-in-sql-developer

**Comment by KornelPudlo** [comment]
Seems to be fixed. 
Closing the case
