### ISSUE TITLE
Foreign key relationship for some tables are lost in graphml export

### ISSUE THREAD

**Issue by cyriac-george** [dbeaver/dbeaver#15914]
#### System information: 
- Operating system (distribution) and version: macOS Monterey 12.2.1 (21D62)
- DBeaver version: Version 22.0.1.202203181646
- Additional extensions: None

#### Connection specification:
- Database name and version: Oracle 21c
- Driver name: 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
A few foreign key relationships in a schema are lost when an ER Diagram is exported in the graphml format.

I use the graphml diagrams to create a DB model diagram for offline reference. I then use [yEd](https://www.yworks.com/products/yed) to auto-arrange it into a more sensible (read as graphical) way for human consumption. I noticed that the diagram generated with the aforementioned version is missing a few foreign key relationships. Since foreign key relationships are an integral part of DB models missing them is a big deal!

#### Steps to reproduce, if exist:
1. Open DBeaver (v22.0.1) and connect to the DB
2. On Database Navigator right-click on the connected DB -> Open Schemas -> Selected the schema that I'm working with
3. Double click on the schema name to open it on the right pane
4. Open the ER Diagram tab and click on the `Save diagram in external format` icon and save it as a graphml file
<img width="976" alt="Screen Shot 2022-03-21 at 11 13 14 AM" src="https://user-images.githubusercontent.com/102067078/159338725-da1f2aae-7dca-4e72-84b8-e18f664cf963.png">

5. Install & open DBeaver ([v21.1.4](https://dbeaver.io/files/21.1.4/)) and follow the same steps as above
6. Compare the two graphml files and observed that foreign key relationships for a few tables (not all) are missing

#### My observations
I went to https://dbeaver.io/files/ and installed various DBeaver versions starting from v7.3.5 to check if this is an issue with my DB or DBeaver. I observed that the issue didn't exist with v7.3.5 which eliminated the DB and external params as a cause for the issue. I then installed a bunch of versions to narrow down the release that has introduced the problem. Through trial-n-error I found that the diagram works as expected in v21.1.4 and it broke in v21.1.5.

Comparing the graphml outputs of these two versions I noted the following.
1. The id <node> has changed from a one-based index to a zero-based index. Not saying this is an issue, just sharing an observation from the diff. One example is shown below.
<img width="1468" alt="Screen Shot 2022-03-21 at 11 03 07 AM" src="https://user-images.githubusercontent.com/102067078/159338631-8daa7368-20ee-4ed6-98a0-53a45e325e04.png">

2. `<Point>` tags are missing in a few places in the v21.1.5 graphml file. One example is shown below.
<img width="1475" alt="Screen Shot 2022-03-21 at 11 02 27 AM" src="https://user-images.githubusercontent.com/102067078/159338672-e74b1baa-d200-4557-8d77-e0badf9c5c15.png">

I realize that it might be easier to investigate this issue if the data setup to reproduce the issue can also be given, but unfortunately, I cannot create sample data that could do that. I'm hoping that the code of v21.1.4 and v21.1.5 can be compared and the problem can be identified.
I went through the code differences using https://github.com/dbeaver/dbeaver/compare/21.1.4...21.1.5 and I spotted that https://github.com/dbeaver/dbeaver/issues/9754 has introduced some changes to this area. Could there be a bug in that PR?

**Comment by ShadelessFox** [comment]
Hello @cyriac-george,

Could you please also send log files? Thanks.

https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by cyriac-george** [comment]
Hi @ShadelessFox 

I opened the Error Log view and deleted all existing logs. Then I exported the ERD in graphml. The issue still exists yet there were no errors on the Error Log view. 
<img width="1083" alt="no_errors_in_error_log" src="https://user-images.githubusercontent.com/102067078/161354731-a79d4462-b399-4b62-941b-a92460bd3cbf.png">


I then went to the log folder and could only see [dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/8401343/dbeaver-debug.log) in it.

I hope this is useful.

**Comment by CousinItt1313** [comment]
Hello all,

I have the similar case in my ERD export. For me it seems that yED has problems when there are identical IDs - which should not happen in my case. :)
BR
ROMAN
![image](https://user-images.githubusercontent.com/102952668/161506828-fa006b5d-d189-4154-9ee8-a57b8d9da87f.png)

**Comment by ShadelessFox** [comment]
The issue was fixed in #14956.
