### ISSUE TITLE
Import wizard ignores existing data types while DDL is generated

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#15921]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 22.0.1

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
Import wizard automaps table to be created even if another relation (e.g. data type) with that name already exists

#### Steps to reproduce, if exist:
1. Create a CSV file with a name of one of custom data types in your schema
2. In the context menu of your schema start data import
3. Leave all settings by default

**Expected:** Data is imported
**Actual:** Table can't be created

![dbeaver_s9r8zPIMD8](https://user-images.githubusercontent.com/82543000/159414901-ed80be77-608b-415b-aa66-a176a399837b.png)

![dbeaver_nHZqJXY6cw](https://user-images.githubusercontent.com/82543000/159414912-2f950e41-12e0-4ede-824c-f0893444b858.png)

**Comment by emironovDB** [comment]
We need to add concept of namespaces which contain objects of different types (tables, views ,sequences, etc).
By default all schemas are namespaces which contain tables and views.

**Comment by serge-rider** [comment]
Fixed.
PR contains many improvements, please check data transfer for import and export in different combinations.

![image](https://user-images.githubusercontent.com/6398845/174480091-5067acb6-77bf-413f-a382-7fe879a6b565.png)
