### ISSUE TITLE
eclipse 2022-03 compatibility

### ISSUE THREAD

**Issue by LBeaulaton** [dbeaver/dbeaver#15941]
So that means that dbeaver plugin doesn't work with latest eclipse 2022-03? I'm using windows 10 I tried installing it from Marketplace and I get a 
Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver IDE 22.0.0.202203060510 (org.jkiss.dbeaver.ide.feature.feature.group 22.0.0.202203060510)
  Missing requirement: Bouncy Castle PKIX, CMS, EAC, TSP, PKCS, OCSP, CMP, and CRMF APIs 1.69.0.v20210713-1924 (org.bouncycastle.bcpkix 1.69.0.v20210713-1924) requires 'java.package; org.bouncycastle.asn1.bsi [1.69.0,1.70.0)' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver IDE 22.0.0.202203060510 (org.jkiss.dbeaver.ide.feature.feature.group 22.0.0.202203060510)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.runtime.feature.feature.group [22.0.0.202203060510,22.0.0.202203060510]
  Cannot satisfy dependency:
    From: DBeaver Runtime 22.0.0.202203060510 (org.jkiss.dbeaver.runtime.feature.feature.group 22.0.0.202203060510)
    To: org.eclipse.equinox.p2.iu; org.bouncycastle.bcpkix [1.69.0.v20210713-1924,1.69.0.v20210713-1924]

. Trying to install the dbeaver bouncy castle package on its own doesn't help, gives the same error.

_Originally posted by @CristiFS in https://github.com/dbeaver/dbeaver/issues/15880#issuecomment-1071079176_

**Comment by LBeaulaton** [comment]
I have the exactly same issue with the latest eclipse release on a ubuntu 20.04 computer

**Comment by sylepole** [comment]
Hi,
I have the same error with eclipse 2021.12 on windows 10
![image](https://user-images.githubusercontent.com/79159239/159692117-81ef4093-46cc-4d74-9cab-7485c1180dc3.png)

**Comment by x4os-iso** [comment]
Same error here with Eclipse 2022-03 on Linux

**Comment by vincenzocaselli** [comment]
I have the same error with eclipse 2022.03 on Arch Linux

**Comment by LonwoLonwo** [comment]
Hello!

Can you please test the latest version of DBeaver? https://dbeaver.io/download/

**Comment by LBeaulaton** [comment]
Hi,
fix the problem for me.

**Comment by LonwoLonwo** [comment]
Thanks for the answer and for the investigation @LBeaulaton

**Comment by 3rdey3** [comment]
The plugin is working for me on windows 11.

**Comment by LonwoLonwo** [comment]
Thanks @3rdey3

**Comment by ssttaarr** [comment]
The problem can be reproduced with latest Eclipse release 2022-12:
- fresh Eclipse JDT installation
- try to install DBeaver 22.3.0 from the marketplace

It complains about missing Bouncycastle dependency
