### ISSUE TITLE
Confirm dangerous query execution doesn't work when there's a RETURNING clause in a DELETE statement

### ISSUE THREAD

**Issue by lukaseder** [dbeaver/dbeaver#15946]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows [Version 10.0.22000.556]
- DBeaver version: 22.0.1.202203181646
- Java version: openjdk version "17.0.2" 2022-01-18

#### Connection specification:
- Database name and version: PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
- Driver name: org.postgresql:postgresql:42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

The dangerous query execution confirmation doesn't work when a `DELETE` statement has a `RETURNING` clause

#### Steps to reproduce, if exist:

Turn on the "Confirm dangerous query execution" feature:

![image](https://user-images.githubusercontent.com/734593/159666879-b67ec549-aa6a-4ee9-81f9-9424c49a6dfa.png)

Then create a table like this:

```sql
create table t (id int, a int);
```

Then run this statement:

```sql
delete from t returning *;
```

It executes without a prompt. The problem doesn't affect `UPDATE` statements. The following statement produces a prompt:

```sql
update t set a = 1 returning *;
```

The prompt being:

![image](https://user-images.githubusercontent.com/734593/159667113-3688bd5d-d2ec-4eb9-b19f-6247316a938e.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
Hello @lukaseder 

For now we can't fix this problem unfortunately. 

`delete from t returning *;`

This statement can't be parsed by JSQLParser library, wich we use for parsing now.

I created a ticket for this case: https://github.com/JSQLParser/JSqlParser/issues/1527

**Comment by lukaseder** [comment]
Sure, no worries. Thanks for addressing this!

**Comment by manticore-projects** [comment]
Greetings.

Currently, JSQLParser does not support the `RETURNING` for `DELETE` statements, although I will see what I can do about.

For future reference, the recent SQL Syntax Diagrams of JSQLParser: http://217.160.215.75:8080/jsqlformatter/_static/JSqlParserCC.xhtml#Delete

I keep that up-to-Date.

**Comment by manticore-projects** [comment]
@lukaseder: Are there more statements using a `RETURNING` expressing? (Sorry, I never used those before and am not aware of it.)

According to Postgresql https://www.postgresql.org/docs/current/dml-returning.html it would be `INSERT`, `DELETE`, `UPDATE`.  

`UPDATE` is supported yet, but not `DELETE` or `INSERT`.

What about `MERGE` statement?

**Comment by manticore-projects** [comment]
Should be fixed by PR https://github.com/JSQLParser/JSqlParser/pull/1528
I have attached JSQLParser 4.4 + PR 1528, it should be sufficient to just replace the JAR file.
[jsqlparser-4.5-SNAPSHOT.zip](https://github.com/dbeaver/dbeaver/files/8639498/jsqlparser-4.5-SNAPSHOT.zip)

**Comment by E1izabeth** [comment]
Thank you, @manticore-projects!

**Comment by lukaseder** [comment]
> @lukaseder: Are there more statements using a `RETURNING` expressing? (Sorry, I never used those before and am not aware of it.)

`INSERT`, `UPDATE`, and `DELETE` have it. Speaking of which, these Transact-SQL syntaxes are also not covered by Dbeaver's protection:

```sql
delete from t output deleted.i;
update t set i = 1 output deleted.i;
```

**Comment by lukaseder** [comment]
> What about `MERGE` statement?

PostgreSQL doesn't support `MERGE` yet. The standard SQL way to return values from `MERGE` would be `{ OLD | NEW | FINAL } TABLE` (as supported by Db2 and H2), e.g.

```sql
SELECT * FROM FINAL TABLE (
  MERGE ...
) t;
```

**Comment by lukaseder** [comment]
`RETURNING` is supported by at least:

- Firebird
- MariaDB
- Oracle PL/SQL
- PostgreSQL (and related, including CockroachDB, YugabyteDB)

**Comment by manticore-projects** [comment]
> > @lukaseder: Are there more statements using a `RETURNING` expressing? (Sorry, I never used those before and am not aware of it.)
> 
> `INSERT`, `UPDATE`, and `DELETE` have it. Speaking of which, these Transact-SQL syntaxes are also not covered by Dbeaver's protection:
> 
> ```sql
> delete from t output deleted.i;
> update t set i = 1 output deleted.i;
> ```

Same problem: JSQLParser does not understand/support it (yet).
I am no big fan of MS Anything, but when this was relevant I would try to implement it (with a second PR).

**Comment by manticore-projects** [comment]
@lukaseder : Thanks for the feedback.

My current assessment:

1) We need to support `RETURNING` for `INSERT`, `UPDATE` and `DELETE` (has been implemented now)
2) We may implement T-SQL equivalent `OUTPUT DELETED,i`  (I need to research the syntax though, it looks weird)
3) Nothing to be done for `MERGE` as it does not support `RETURNING`

Anything else please?

**Comment by lukaseder** [comment]
> 2\. We may implement T-SQL equivalent `OUTPUT DELETED,i`  (I need to research the syntax though, it looks weird)

https://docs.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql?view=sql-server-ver15

> 3\. Nothing to be done for `MERGE` as it does not support `RETURNING`

Yeah, I think `MERGE` doesn't need any protection. This particular accident is more unlikely with `MERGE`

**Comment by manticore-projects** [comment]
Thank you @lukaseder .
I have added support for the `OUTPUT` clause to the `INSERT`, `DELETE` and `UPDATE` statement.  This should make those statements parsable and help to trigger the warning in DBeaver.

@E1izabeth: Please do let me know, when anything else was needed. I have attached a Snapshot JAR including the PR again. Unfortunately I can not merge the PR myself, but I would write an e-mail to the Project Owner @wumpz.

[jsqlparser-4.5-SNAPSHOT.zip](https://github.com/dbeaver/dbeaver/files/8645157/jsqlparser-4.5-SNAPSHOT.zip)

**Comment by uslss** [comment]
verified
