### ISSUE TITLE
Blank columns in output when using 'Export Resultset' option

### ISSUE THREAD

**Issue by zejji** [dbeaver/dbeaver#1595]
If I run certain MySQL queries which give correct results in DBeaver's results window, and then use the 'Export Resultset' option, certain columns are missing from the exported output (i.e. the relevant fields are always blank). This is the case for all of the outputted file types (CSV, HTML, JSON, XML).

Unfortunately, I have not yet been unable to create a trivial query and dataset to give you which reproduces this error - it only occurs with a relatively complex query on a confidential dataset. (I have compared the outputs produced by HeidiSQL and these are all correct i.e. with no missing columns). What I can, however, say is that there are no unusual characters in the missing fields - they all take the very simple format described by the regexes `S[0-9]{1,6}` and `M[0-9]{1,6}`.

Is there any way I can debug this locally? Can you think of any reason for data not being written to the output file?

If it is necessary, I could try to produce a redacted version of the confidential query (with changes to column names and table data), but this is likely to take a *significant* amount of time.

FYI, I am running the latest version of DBeaver (4.0.5) on Windows 10.

**Comment by serge-rider** [comment]
First of all - check error/debug logs: https://github.com/serge-rider/dbeaver/wiki/Log-files
You can send them to me on serge@jkiss.org (after cutting any non-public info).

I have no clues so far. Maybe this is somehow related to column (expression) types or names.
Maybe missing columns are BLOBs/CLOBs? In that case there is a special export config option ("Binaries" combo).
Have no other clues so far.

**Comment by zejji** [comment]
Hi - I've (finally!) managed to create a reproducible test case. I've sent you an email referencing this issue.

**Comment by zejji** [comment]
Just to add that I've also recently experienced further issues where VARCHAR fields are not entirely missing, but are being truncated in the CSV output. In particular, it seems that everything from and including certain special characters, e.g. the ampersand (&) symbol is disappearing.

Again, this is occurring on a server running Centos 6.9 (centos-release-6-9.el6.12.3.x86_64) and MySQL 5.1 MySQL 5.1 (Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1).

**Comment by aagha** [comment]
I'm seeing the same issue.  When running a query that references values in a JSON object and uses the 'as' to represent the value as a column, the output is showing up blank (though the column name appears).

**Comment by hereticaneue** [comment]
Yep, I'm having the same issue with my query that references values in a JSON object. I've tried it with and without using 'as' to represent the column.

**Comment by TimTinkers** [comment]
This issue is still affecting me and I believe it has to do with pulling values out of JSON objects. This is the only issue that is preventing me from abandoning MySQL Workbench entirely.

I've created a [$15 bounty](https://www.bountysource.com/issues/44382587-blank-columns-in-output-when-using-export-resultset-option) for this issue.

**Comment by Prajna-Ty** [comment]
When exporting the data, in “format setting”, try setting binaries to “inline”, and select “binary” for encoding. That's how I resolved the issue.
