### ISSUE TITLE
Toogle line comment changes selection

### ISSUE THREAD

**Issue by GuenterSch** [dbeaver/dbeaver#15950]
#### System information: 
- Operating system (distribution) and version: Windows 10 21H1
- DBeaver version: 22.0.1
- Additional extensions: No

#### Connection specification:
- Database name and version: Snowflake, MS SQL Server, Oracle
- Driver name: Not relevant
- Yes

#### Describe the problem you're observing:
The problem happens in the SQL editor. It is independend of the database connection.
If you mark some lines and press Ctrl+B (Toogle line comment), the lines will be commented and the position of the begin selection changes (but not correct).
If you press Ctrl+B again, the lines will be uncommented, and the selection will move to a complete different possition (for begin and end).
In earlier versions, it worked fine!

#### Steps to reproduce, if exist:
Mark some lines
Ctrl+B
Ctrl+B

**Comment by ShadelessFox** [comment]
Hello @GuenterSch ,

Thanks for the bug report.

**Comment by GuenterSch** [comment]
Thanks Serge, it works fine!
