### ISSUE TITLE
Requesting a hotkey to activate the Filter Results textbox in Table Data view

### ISSUE THREAD

**Issue by ffalcon31415** [dbeaver/dbeaver#15952]
I try to use keyboard only without mouse as much as possible due to RSI. I can't find a keyboard hotkey to activate the main Filter Results textbox in Table Data view (which I frequently need to access).

**Describe the solution you'd like**
User is in Table Data view. User presses the keyboard hotkey (Ctrl+Alt+f, for intance). The Filter Results textbox is activated and the user can then type in their filter of choice.

**Describe alternatives you've considered**
Ctrl+F11 brings up filters for the active column, but I want the general Filter Results where I can enter any SQL expression to filter.

**Additional context**
This is the Filter Results textbox I am referring to.
![Untitled](https://user-images.githubusercontent.com/77492177/159780546-92a82063-05da-4cbe-bde6-5d75454c441d.png)

**Comment by uslss** [comment]
By default Ctrl+Alt+Shift+T set for this action. You could change shortcut to another in preferences.

![image](https://user-images.githubusercontent.com/31996417/159868542-a4edfea3-ad02-456b-9168-550a2a4ec833.png)

**Comment by ffalcon31415** [comment]
Thanks. Sorry I failed to find that.
