### ISSUE TITLE
Athena Data Catalog Connection Setting Issue - Specifying another catalog option doesn't work

### ISSUE THREAD

**Issue by scottmatt1** [dbeaver/dbeaver#15953]
#### System information: 
- Operating system (distribution) and version: windows 10
- DBeaver version - 22.0.1
- Additional extensions - Simba JDBC Driver

#### Connection specification:
- Database name and version: Athena Simba JDBC
- Driver name: 1.1.2
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
AWS a glue catalog option so instead of the default catalog "AwsDataCatalog" being used, I'd like to specify the optional other one. When specifying the other catalog, it still defaults to the default AwsDataCatalog. Leaving the value empty also uses account default. There is no way it seems, through the connection settings, it taking the other catalog I specify.

#### Steps to reproduce, if exist:
1) Create an Athena Connection
2) on Driver properties, specify for name "Catalog" a value of "yourcatalog"
** for which "yourcatalog" is the catalog name you are trying to reference instead
Note: this is the same additional catalog that you choose within Athena Console next to Data Sources
3) Upon re-connecting, it still stays with the default and doesn't bring the other catalog databases.

![DBeaverCapture](https://user-images.githubusercontent.com/102261501/159803003-81e36f51-3365-4dd1-b174-8f2e5eca336a.JPG)

**Comment by uslss** [comment]
thanks for the report. 

duplicates #11196
