### ISSUE TITLE
Pin Column in data view awesome.. need same PIn from Properties view

### ISSUE THREAD

**Issue by SherlockSoftware** [dbeaver/dbeaver#15954]
I believe every release does not have this other view PIN feature.
Using Dbeaver 22.1

When you have say 120 columns and want to PIN 1 or 2 from middle, you navigate sideways, click column header and PIN that column.

But what would be faster, even better is the Properties list of fields, vertical list.
It shows same columns vertically and faster to get to the fields you want.

Great to have the same PIN COLUMN functionality.

Also is there, could there be a saved PINNED option..  
so if pinned 4 columns and want to do again later..

Thank you........ Awesome product.

Phil

**Comment by LonwoLonwo** [comment]
Thank you for the idea @SherlockSoftware

**Comment by E1izabeth** [comment]
I'll close this issue as it's duplicate #18686 were created, but there is more discussion with explanation of use case in the new one.
