### ISSUE TITLE
Add a preference to disable new marker-based problem highlighting

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#15961]
We need a way to enable the old behavior which involved selecting the problematic segment of a query in the editor.

**Comment by ShadelessFox** [comment]
Implemented:

![image](https://user-images.githubusercontent.com/35821147/159919687-8df7d259-dc9a-4f04-9b42-8f0874b94b1e.png)

**Comment by Matvey16** [comment]
Verified
