### ISSUE TITLE
Style SQL Console relatively to connection type

### ISSUE THREAD

**Issue by IdrissaD** [dbeaver/dbeaver#15971]
**Is your feature request related to a problem? Please describe.**
Connection type changes the style of connection tree at the window's left, and the style of table visualizer. That is a cool feature, however I believe that the most error-prone place is the SQL console, where it's easy to truncate and drop tables and full databases.  

**Describe the solution you'd like**
I would like the SQL console to be styled accordingly to the connection type, e.g. with a pale red background for productions connections or something like that.

**Comment by LonwoLonwo** [comment]
Thank you for the idea @IdrissaD

**Comment by rotorboy** [comment]
with all the customization that is possible within dbeaver, it is surprising and disappointing that it is not possible to set the sql editor window pane AND background color to be the connection color. As noted, it is way too easy to be in the wrong editor and execute a command that can create devastating consequences. 

While there are other visual cues that indicate what connection the editor is attached to, they are relatively small and out of normal field of view; having the background color of the whole window being the connection color will make it very clear instantly which connection it is.

**Comment by emironovDB** [comment]
Close by this ticket https://github.com/dbeaver/dbeaver/issues/15971

**Comment by IdrissaD** [comment]
@emironovDB I don't understand your closing comment, as the ticket number you provide is this actual ticket we're commenting.

**Comment by emironovDB** [comment]
@IdrissaD 
Sorry, attached the wrong ticket. This is correct one: https://github.com/dbeaver/dbeaver/issues/15760 
We already add the functionality what you have asked. You can try [the latest DBeaver version](https://dbeaver.io/download/) and let us know if it is resolving your request. 
If it is not, then reopen this issue and add comment to clarify details

**Comment by IdrissaD** [comment]
Thanks, indeed it works!
There's just a behavior that I dont' know if it's intended or not:

Style when I open a new console for a production connection:
<img width="1070" alt="Capture d’écran 2022-07-12 à 11 46 36" src="https://user-images.githubusercontent.com/73114156/178462524-57d255af-3501-4a09-8a17-4eea5893082a.png">

Style of this same console after I click anywhere outside of the console:
<img width="1068" alt="Capture d’écran 2022-07-12 à 11 47 14" src="https://user-images.githubusercontent.com/73114156/178462542-e3f07304-4dbb-4b93-8d99-a6d091144ffc.png">

**Comment by uslss** [comment]
@IdrissaD what OS do you use?

**Comment by IdrissaD** [comment]
MacOS Big Sur 11.6.7
