### ISSUE TITLE
[MS SQL] Not identifying unique key

### ISSUE THREAD

**Issue by hauntingEcho** [dbeaver/dbeaver#15975]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 22.0.1.202203181646
- Additional extensions: none

#### Connection specification:
- Database name and version: MS SQL Server
- Driver name: MS SQL Server / SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Describe the problem you're observing:

This unique key is not being identified as such:

![image](https://user-images.githubusercontent.com/1661988/160207599-b449204d-1d57-401c-9307-b59bdeb361e6.png)

#### Include any warning/errors/backtraces from the logs

nothing logged

**Comment by LonwoLonwo** [comment]
Hello @hauntingEcho 

Can you provide a table DDL? 
Could you please tell me more about your issue with the key? Or index?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual - feel free to reopen it with additional info.
