### ISSUE TITLE
Script window: after save the window is scrolled to the end of the script

### ISSUE THREAD

**Issue by vicreal** [dbeaver/dbeaver#15979]
**Windows 10 / DBeaver 21.3.5 / PostgreSQL 13**

In SQL-script window: after change script and save (Ctrl+S or File-Save) the window is scrolled to the end of the script.
At the same time, the cursor remains in the same place where the script was changed.

How it should be: when saving, the window should not scroll to the end of the script.

**Comment by LonwoLonwo** [comment]
Hello @vicreal 

Thanks for the bug report.

This problem was fixed earlier: https://github.com/dbeaver/dbeaver/issues/15562
You can check it in the latest DBeaver version: https://dbeaver.io/download/
