### ISSUE TITLE
Wrong DROP function DDL script generated from UI

### ISSUE THREAD

**Issue by samtech09** [dbeaver/dbeaver#15974]
#### System information: 
- Operating system (distribution) and version : Arch Linux 5.16.14-arch1-1
- DBeaver version : 22.0.1.202203212220
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 13.6
- Driver name : PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes

#### Describe the problem you're observing:
The generated DROP DDL for function with return type TABLE is wrong. Return type is being included as parameter in SQL.

#### Steps to reproduce, if exist:
Here is simple function i created
```
CREATE OR REPLACE FUNCTION public.addition(d1 integer, d2 integer)
 RETURNS TABLE(id integer)
 LANGUAGE plpgsql
AS $function$
DECLARE     
BEGIN
	return query Select d1 + d2;
END;
$function$
;
```

Try to delete it from UI, it should give following error
```
ERROR: function public.addition(integer, integer, integer) does not exist
```

`View Script` option is giving following SQL for that
```
DROP FUNCTION public.addition(in int4, in int4, int4);
```

But it should be
```
DROP FUNCTION public.addition(in int4, in int4);
```

**Comment by LonwoLonwo** [comment]
Hello @samtech09 

Thanks for the bug report.

This issue was fixed: https://github.com/dbeaver/dbeaver/issues/15563
Fix will be available in the next DBeaver release 22.0.2 at 04-04-2022
