### ISSUE TITLE
DBeaver 22/Rel march 7: Cannot change target container for export of table in cassandra aws keyspaces

### ISSUE THREAD

**Issue by rajarshi-mukherjee4volvo** [dbeaver/dbeaver#15973]
pre-requisite: 
1. multiple cassandra connections to aws keyspaces A, B, C mounted in DbeaverEE v22 Rel March7.
2. successfully performed table export from table T1 of keyspace A to table T1 of keyspace B with export target=database.

Steps to reproduce bug for export:
1. Attempt another export table T1 of keyspace A with export target=database by right clicking on the table and selecting "Export Data".
2. In table mapping section, "choose" to change target container to keyspace C.
3. An error is shown as: 
    "Node 'C' cannot be selected as table container
     Reason:
     Error determining container elements type"

**Comment by LonwoLonwo** [comment]
Hello @rajarshi-mukherjee4volvo 

Can you please provide some screenshots?
Also please check [error logs](https://github.com/dbeaver/dbeaver/wiki/Log-files).

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still reproducible against the recent version - feel free to reopen it.
