### ISSUE TITLE
How to set the default time zone of influxdb ?

### ISSUE THREAD

**Issue by flykarry** [dbeaver/dbeaver#15981]
**Is your feature request related to a problem? Please describe.**
I can't get the correct time zone using the interface operations, and I have to add the time zone function manually with all sql statement, 

**Describe the solution you'd like**
I want to set a default time zone with all my query or a quick method to set it to my sql in right button

**Comment by LonwoLonwo** [comment]
Hello @flykarry 

Have you tried to change your timezone in the Preferences?

![2022-03-31 10_45_29-DBeaver Ultimate 22 0 2 - _Chinook db_Script-142](https://user-images.githubusercontent.com/45152336/161004446-2799df8f-4248-4324-bda0-f02eca46adb8.png)

You can try it in Preferences -> Editors -> Data Editor -> Data Formats

Also, sometimes enabling the "Disable date/time formatting" helps with data/time formatting.

**Comment by flykarry** [comment]
Sorry, this doesn't work, the result I want is like adding tz('Asia/Shanghai') to the end of the sql statement

**Comment by Matvey16** [comment]
@flykarry Hello. If you are talking about SELECT queries, you can configure resultset to convert all date/time data into specific timezone (it won't affect any query, but will convert recived data on the client to show you the time in needed timezone). Will that solve your issue?

![dbeaver_jycMUMCyDC](https://user-images.githubusercontent.com/82543000/161489914-d7fa05fd-2980-4228-ae58-2814313b5b6c.png)

**Comment by flykarry** [comment]
Sorry, this doesn't work.

**Comment by Matvey16** [comment]
@flykarry Thank you, it looks like influx returns timestamps in a way that we can't transform them with current methods, we will look at this some more.

**Comment by Destrolaric** [comment]
Linked pr: https://github.com/dbeaver/dbeaver-ee/pull/1737
