### ISSUE TITLE
connect timed out ，but Navicat can

### ISSUE THREAD

**Issue by foxerz098** [dbeaver/dbeaver#15984]
Fail to connect a Mysql database with:
```
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
  connect timed out
  connect timed out
```
The problem is that Navicat can connect it at the same time.

![image](https://user-images.githubusercontent.com/51819524/160372787-711c52de-bedd-432a-91ae-286a1303de1b.png)

**Comment by LonwoLonwo** [comment]
Hello @foxerz098 

Is this issue still actual?
This error looks like a general network error (e.g. firewall timeout). Maybe you need to use different server IP address/host name.

Also, maybe this discussion can help you? https://stackoverflow.com/questions/6865538/solving-a-communications-link-failure-with-jdbc-and-mysql

**Comment by LonwoLonwo** [comment]
Or this: https://github.com/dbeaver/dbeaver/issues/12263#issuecomment-830007510

**Comment by uslss** [comment]
There has been no update on the issue for a long time.  If it is still reproducible - feel free to reopen it

**Comment by foxerz098** [comment]
it's a problem about ipv6 ,Adding this config in dbeaver.ini is a solution:
-Djava.net.preferIPv4Stack=true
