### ISSUE TITLE
Nothing is changed after setting connection timeout in Connection SSH tab

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#15994]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version   22.0.0.202203090812

#### Steps to reproduce, if exist:
1. Create an SSH connection and set tunnel connection timeout 1 ms in Advanced settings of SSH tab
2. Press Test Tunnel

**Expected**: the test is failed, because the time 1 ms isn't enough to test tunnel
**Actual result**: test is successful

**Comment by uslss** [comment]
verified
