### ISSUE TITLE
Fill table with mock data to test it

### ISSUE THREAD

**Issue by GiantCrocodile** [dbeaver/dbeaver#1599]
I would like to have a feature to generate mock data to test my database/tables. It would be nice to have an inbuilt feature of DBeaver for this. For example as an option in context menu on a table where you can choose to generate data. Then a window opens where you can generate data with help of https://www.mockaroo.com/ with the same options provided as there. The generated data should be inserted automatically after confirming.

**Comment by serge-rider** [comment]
This is a big task. Will require lots of efforts.

**Comment by GiantCrocodile** [comment]
I know this and I know it won't be easy for you but I think this could be a big bonus for DBeaver :). Maybe it is possible to add the context menu and open a browser window inframe and when the user is done he can copy the data and press a DBeaver button so copied data is used to generate SQL statement and to execute it.

**Comment by godtree94** [comment]
I also need this function...

**Comment by efradkin** [comment]
Good place to start: https://stackoverflow.com/questions/591892/tools-for-generating-mock-data

**Comment by efradkin** [comment]
@GiantCrocodile @godtree94 beta version of the feature is included into the latest DBeaver version.

**Comment by GiantCrocodile** [comment]
@efradkin Thanks for your info/engagement! I just tested it quickly: When I try to generate text and sequences as mock data for a table with < 5 columns, my mock data window freezes while he generates the data. Generating the data takes quite long. I'm not sure if it just froze or crashed/bugged.

Is it possible to change the generated data types for my columns? For example rather than generating text for my email address column, I want to generate email addresses.

**Comment by efradkin** [comment]
@GiantCrocodile Is there anything related in error/debug logs? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

What DB do you use? What column types are? It it standalone table or it has relations with other tables?

More different generators will be implemented in the future.

Thank you!

**Comment by GiantCrocodile** [comment]
I had to cancel it as it did result in nothing except a window with endless progress. No errors or warnings logged. This is my table:

![grafik](https://user-images.githubusercontent.com/6271057/35915194-3879721c-0c06-11e8-9b72-7d86da58f029.png)
![grafik](https://user-images.githubusercontent.com/6271057/35915199-4120d3f6-0c06-11e8-8381-5c241a0d51b8.png)

No foreign keys, there are just other tables which reference to this `user` table.

**Comment by efradkin** [comment]
@GiantCrocodile it's constraints handling bug. The fix will be in the next version. Thank you!

**Comment by efradkin** [comment]
[Mock Data Generation article](https://github.com/dbeaver/dbeaver/wiki/Mock-Data-Generation)

**Comment by GiantCrocodile** [comment]
I'm proud of everyone who was involved! Thanks that this feature became so big and is so feature rich!
