### ISSUE TITLE
SQL Editor: in case of errors, the "Problems" window always opens

### ISSUE THREAD

**Issue by vicreal** [dbeaver/dbeaver#15992]
**Windows 10 / PostgreSQL 13 / DBeaver 21.0.1**
SQL Editor: in case of errors, the "Problems" window always opens (along with the window with error text)
In previous DBeaver versions opens only one window - with error text.

![2022-03-29_123515](https://user-images.githubusercontent.com/72701351/160582819-82c2bcce-1740-4e6d-942b-6addea11cdf4.jpg)

How can I prevent this window from opening in case of errors ?

**Comment by ghost** [comment]
This was reported by JamesInform and myself a few days ago. We were given link to the early access version although I don't think it's my place to provide that link. The reply from Anastasiya said " a [new option](https://github.com/dbeaver/dbeaver/issues/15961) was added a few days ago and will be available in the next DBeaver release 04-04-2022". I can confirm that this fixes the problem as described. The problem number was 15977.

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @vicreal

**Comment by ShadelessFox** [comment]
Fixed in #15961

**Comment by ems2811** [comment]
Still reproduces in 22.0.4
