### ISSUE TITLE
SQL Errror underlining/highlighting/... exceeds actual error

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#16007]
#### System information: 
- Operating system Linux, Debian/SID
- DBeaver Version 22.0.1.202203181646
- Additional extensions none

#### Connection specification:
- Database name and version Postgres 12
- Driver name org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
SQL Error underlining/highlighting/... goes from the error position until the end of the query. Severely limits the usefulness of the marking, since the default red and underlining rather blurs instead of highlighting the actual issue.

#### Steps to reproduce, if exist:
```
SELECT foo, bar, MAX(baz) FROM xyz ORDER BY bar
```
will cause an error like 
`SQL Error [42803]: ERROR: column "foo" must appear in the GROUP BY clause or be used in an aggregate function. Position: ...`
and the underlining/highlighting/... will start at that position and reach until the end.
Since the position and the offending field (in this case) is known, the marking should really only be on "foo".

**Comment by ShadelessFox** [comment]
Hello @2019-05-10,

Thanks for the bug report.

**Comment by ShadelessFox** [comment]
Additionally, we need to position the cursor at the start of an error in case of executing a single query.
