### ISSUE TITLE
SQL Error: unknown escape sequence 

### ISSUE THREAD

**Issue by iesportada** [dbeaver/dbeaver#16002]
#### System information: 
- Operating system (distribution) and version: Linux Mint 20.3
- DBeaver version: 22.0.1 installed from Serge Rider's ppa
- Additional extensions

#### Connection specification:
- Database name and version: MariaDB 10.3
- Driver name: org.mariadb.jdbc.Driver 2.7.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
Trying to execute next simple FUNCTION:

_CREATE FUNCTION myDB.printDate(myDate DATE)
RETURNS char(50)
BEGIN
	return concat("The date is: ", myDate);
END_

The **output** is:
Error occurred during SQL query execution
Razón:
 SQL Error: (conn=30) unknown escape sequence {SELECT myDB.printDate('2022-03-30') }

#### Steps to reproduce, if exist:
Everything works fine when invoking from system console

**Comment by LonwoLonwo** [comment]
Ok, I see the problem

Thanks for the bug report @iesportada 

![2022-03-30 17_00_13-DBeaver Ultimate 22 0 2 - _MariaDB 10 1_Script-141](https://user-images.githubusercontent.com/45152336/160853564-a9f75ea7-17e3-41b7-9138-e171e4260c83.png)

**Comment by LonwoLonwo** [comment]
{} brackets are working good for procedures, but not for functions. 
Brackets removed from SELECT statement for functions from "Execute stored procedure" command for MySQL/MariaDB

**Comment by iesportada** [comment]
Thanks!

**Comment by Matvey16** [comment]
Verified
