### ISSUE TITLE
Clickhouse array support enhancement

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#16010]
As a follow-up of #14255 we need to further impruv the presentation of complex arrays, particularily when complex column structure view is disabled

**Comment by LonwoLonwo** [comment]
Implemented

![2022-03-30 17_33_45-DBeaver Ultimate 22 0 2 - _ClickHouse LOGS_Script-138](https://user-images.githubusercontent.com/45152336/160861296-507443a9-23e3-42d2-85bc-bb762802fc3c.png)

![2022-03-30 17_23_08-](https://user-images.githubusercontent.com/45152336/160861441-a24a30b8-1486-4779-b39a-f8b0f5fb8796.png)

`SELECT CAST('[(''a'',''b'')]' AS Array(Tuple(String, String))), ('a', 'b')`
    
`SELECT arrayZip(['a', 'b', 'c'], [5, 2, 1]);`

`SELECT arrayMap((x, y) -> (x, y), [1, 2, 3], [4, 5, 6]) AS res`

**Comment by Matvey16** [comment]
Verified
