### ISSUE TITLE
M1 MAX When the field value is modified, the field cannot be changed to NULL by using the delete key

### ISSUE THREAD

**Issue by liuzhe101** [dbeaver/dbeaver#16020]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by liuzhe101** [comment]
macOS Monterey 12.3

**Comment by LonwoLonwo** [comment]
Hello @liuzhe101 

Please translate your issue into English.

And provide more details about the issue. Screenshots, [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files), videos are welcome.

**Comment by liuzhe101** [comment]
Hi,Thank you for your reply, I am using M1 MAX, when I modify a field value in a row to be empty, I cannot make it NULL. Using backspare delete on windows can become NULL, but using backspare on mac book pro does not become NULL, but becomes empty;

**Comment by liuzhe101** [comment]
Hi,Thank you for your reply, I am using M1 MAX, when I modify a field value in a row to be empty, I cannot make it NULL. Using backspare delete on windows can become NULL, but using backspare on mac book pro does not become NULL, but becomes empty;

> Hello @liuzhe101
> 
> Please translate your issue into English.
> 
> And provide more details about the issue. Screenshots, [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files), videos are welcome.

Hi,Thank you for your reply, I am using M1 MAX, when I modify a field value in a row to be empty, I cannot make it NULL. Using backspare delete on windows can become NULL, but using backspare on mac book pro does not become NULL, but becomes empty;

**Comment by LonwoLonwo** [comment]
Hello @liuzhe101 
Sometimes returning to NULL value depends on the column data type. What data type has your column?

Also, as a workaround, you can set field data to NULL with the context menu:

![2022-03-31 14_49_19-DBeaver Ultimate 22 0 2 - aliases](https://user-images.githubusercontent.com/45152336/161048455-c9566b90-4b5b-4124-ad73-b426cea8d41a.png)

**Comment by liuzhe101** [comment]
> 你好@liuzhe101 有时返回NULL值取决于列数据类型？您的列有什么数据类型？
> 
> 此外，作为一种解决方法，您可以使用上下文菜单将字段数据设置为 NULL：
> 
> ![2022-03-31 14_49_19-DBeaver Ultimate 22 0 2 - 别名](https://user-images.githubusercontent.com/45152336/161048455-c9566b90-4b5b-4124-ad73-b426cea8d41a.png)

Thank you so much, your reply solved my problem. I'm starting to think it's an M1 MAX bug. good luck every day

**Comment by LonwoLonwo** [comment]
Thanks for the answer @liuzhe101
