### ISSUE TITLE
Readonly connection still allows restore

### ISSUE THREAD

**Issue by omlnaut** [dbeaver/dbeaver#16023]
#### System information: 
- Operating system: Windows 10 Pro 20H2
- DBeaver version: 22.0.1.202203181646

#### Connection specification:
- Database name and version
- Driver name: MariaDB JDBC driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
Setting a connection as read-only (connection -> edit connection -> general) prevents sql scripts from changing data, but does not prevent restore.

#### Steps to reproduce, if exist:
- Set connection to read-only
- Execute Tools -> Restore database

Expected behaviour:
A read-only connection should not be able to overwrite the whole database by performing a restore.

**Comment by Matvey16** [comment]
@omlnaut Thank you for the report
