### ISSUE TITLE
Tweak Tip of the Day content

### ISSUE THREAD

**Issue by mdahlman** [dbeaver/dbeaver#16029]
**This Tip of the Day is understandable, but it's not standard English**
If you are not much familiar with SQL scripting, use <a href="https://github.com/dbeaver/dbeaver/wiki/Visual-Query-Builder">Visual Query Builder</a> tool.

Proposed change:
If you are not very familiar with SQL scripting, use <a href="https://github.com/dbeaver/dbeaver/wiki/Visual-Query-Builder">Visual Query Builder</a> tool.

3 Tips start "If you want to".
They would be easier to read--and they would match other tips better in style--if they simply removed the first 3 words. For example:
current: 
If you want to open foreign keys menu in <a href="https://github.com/dbeaver/dbeaver/wiki/Data-Editor">Data Editor</a>, use the following shortcut: <b>Ctrl+1</b>.
proposed: 
To open foreign keys menu in <a href="https://github.com/dbeaver/dbeaver/wiki/Data-Editor">Data Editor</a>, use the following shortcut: <b>Ctrl+1</b>.

For context, the tips are here:
dbeaver/plugins/org.jkiss.dbeaver.ext.ui.tipoftheday/nl/en/tips.xml

**Comment by ShadelessFox** [comment]
Hello @mdahlman,

Thanks for noting!
