### ISSUE TITLE
[Hive] Wrong query of PK creation

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#16032]
#### System information: 
- Win11
- DBeaver CE 22.0.2

#### Connection specification:
- Apache Hive

#### Describe the problem you're observing:
When you create a new table with a PK, the DDL for it is wrong:
Actual:
![image](https://user-images.githubusercontent.com/43252954/161162423-e3713c62-ec44-4fec-8dbc-3454e9804947.png)

But should be:
```sql
CREATE TABLE default.2a (
	Column2 INT,
	primary key(Column2) disable novalidate
)
```

They are also not displayed in Keys even if you has created a table with PK through SQL Editor

#### Steps to reproduce, if exist:
- Start creation of a new table
- Create one column
- Open Keys folder and create PK
- Try to save the table
#### Include any warning/errors/backtraces from the logs
```
SQL Error [40000] [42000]: Error while compiling statement: FAILED: ParseException line 4:0 cannot recognize input near ')' '<EOF>' '<EOF>' in enable specification
  Error while compiling statement: FAILED: ParseException line 4:0 cannot recognize input near ')' '<EOF>' '<EOF>' in enable specification
  Error while compiling statement: FAILED: ParseException line 4:0 cannot recognize input near ')' '<EOF>' '<EOF>' in enable specification
    org.apache.hadoop.hive.ql.parse.ParseException:line 4:0 cannot recognize input near ')' '<EOF>' '<EOF>' in enable specification
    org.apache.hadoop.hive.ql.parse.ParseException:line 4:0 cannot recognize input near ')' '<EOF>' '<EOF>' in enable specification

```

**Comment by Matvey16** [comment]
Duplicates #14531 #10330
