### ISSUE TITLE
Manage dbeaver in Windows taskbar

### ISSUE THREAD

**Issue by herve3d** [dbeaver/dbeaver#16039]
Hello my dear beaver,
I use dbeaver very often, so I pinned it to the Windows 10 taskbar. But when I launch it the icon appears twice in the bar. If I'm not careful and I click on the first icon then dbeaver tries to launch a second time but with a failure, it's frustrating and wastes time.
It would be cool if there was only one icon like for other software.
Have a good spring,
herve3d
![image](https://user-images.githubusercontent.com/2345817/161263720-bb96bc55-10a9-4bfd-897b-a5b3d6d256a5.png)

**Comment by p91paul** [comment]
unpin it, then pin it again only when the program window is fully loaded.
This happens if you pin it by dragging a shortcut or during the splash screen

**Comment by herve3d** [comment]
It works ! I thought I did this... Thanks
