### ISSUE TITLE
No shortcut to open a table from the References panel

### ISSUE THREAD

**Issue by Chealer** [dbeaver/dbeaver#16049]
**Is your feature request related to a problem? Please describe.**
When following references between multiple tables, the _References_ panel comes useful to go from table A to table B. However, if table C has a foreign key refering to table B, it is then inconvenient to get to C.

I see no way to do that with DBeaver 22.0.1.

**Describe the solution you'd like**
A simple way would be to allow opening the References panel in its own full tab, so that we can then use References again.

**Describe alternatives you've considered**
Perhaps a more elaborate solution like Toad's Master-Detail Browser would be even better.

**Comment by ShadelessFox** [comment]
Hello @Chealer,

Sorry for the late response.

I'm unsure if I understand you correctly. Can you please describe (or show using a video) a use case for your feature request?

**Comment by Chealer** [comment]
Nothing to be sorry about @ShadelessFox 

~A use case would involve 2 entities indirected linked with foreign keys, through a third entity.
For example, an organization can have members, and a member can have skills. If a table for skills has a foreign key to a table for members, and the members table has a foreign key to an ORGANIZATION table, it would be great to be able to quickly go from SKILL to ORGANIZATION through MEMBER, by selecting SKILL's foreign key, then MEMBER's foreign key.~

**Comment by ShadelessFox** [comment]
So, basically, you want this combo menu to show references from the table that is currently shown in that panel?

![image](https://user-images.githubusercontent.com/35821147/165740753-d2e05f92-1177-4688-81da-4d9ae737bd7b.png)

I'm not sure what data that panel should display in such case. Should it result in query that looks something like this?

```sql
SELECT * FROM skills WHERE member_id IN (SELECT member_id FROM members WHERE organization_id = <selected row>);
```

Thanks.

**Comment by Chealer** [comment]
That is not really what I wanted @ShadelessFox , but please excuse me and disregard my previous comment. I haven't used DBeaver in a while and was confused. I retested, and here is the actual use case which is problematic:
For example, an organization can have members, and a member can have skills. If a table for skills has a foreign key to a table for members, and the members table has a foreign key to an ORGANIZATION table, it would be great to be able to quickly go from ORGANIZATION to SKILL through MEMBER, by selecting MEMBER's reverse foreign key from ORGANIZATION, then SKILL's reverse foreign key. This would allow to quickly find skills found in an organization.

I don't know the best way to do this, but one way would be to add a button in the _References_ panel allowing to make it a full-fledged tab (rather than a sub-tab). There could be some "Separate into new tab" button. To achieve the above, I would go to ORGANIZATION, select a row, open the _References_ panel, select a member in the _References_ panel, use the new "Separate into new tab" button, and from there open the _References_ panel again.

By the way, while Toad's Master Detail can serve as inspiration, its design is not that intuitive, so I would not advise to replicate it exactly.

**Comment by ShadelessFox** [comment]
The provided solution is actually pretty useful, so we can stick with it.

I was unable to take a glance of Toad's Master Detail. Can you please, if possible, provide a footage that shows its functionality?

There is a workaround that involves using the `References` tab in the metadata editor (it's not the same as the `References` panel):

![image](https://user-images.githubusercontent.com/35821147/165923716-e525b962-3384-4cfe-813a-d9e00b04e0c7.png)
