### ISSUE TITLE
procedure out parameters are broken

### ISSUE THREAD

**Issue by kai-morich** [dbeaver/dbeaver#16057]
Hi

example from #12012 does not work any more for HANA

```sql
CREATE OR replace PROCEDURE proc1 (OUT tab1 sys.dummy, OUT tab2 sys.dummy, OUT val1 int, OUT val2 int) AS BEGIN
    tab1 = SELECT 'A' AS dummy FROM dummy;
    tab2 = SELECT 'B' AS dummy FROM dummy;
    val1 = 42;
    val2 = 43;
END;

CREATE OR replace PROCEDURE proc2 (OUT val1 int, OUT val2 int) AS BEGIN
    val1 = 42;
    val2 = 43;
END;

CALL proc1(?,?,?,?);
CALL proc2(?,?);
```

with dbeaver 22.0.2 now ends with
![image](https://user-images.githubusercontent.com/25850372/161490340-f87451e7-b51c-4394-9e1c-ba3879c61153.png)
![image](https://user-images.githubusercontent.com/25850372/161490376-9b00351f-5f44-4db4-8923-a19697d18fb7.png)
I haven't checked since when it is broken

**Comment by LonwoLonwo** [comment]
What DBeaver version do you use?

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @kai-morich
