### ISSUE TITLE
[SQLEditor] Error icons can be overlapped

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#16061]
DBeaver 22.0.2

![2022-04-04 10_03_58-DBeaver Ultimate 22 0 2 - _orcl_Script-140](https://user-images.githubusercontent.com/45152336/161501084-79aa7e8e-80ed-440d-ad58-99729aa48fe4.png)

Script error icon can overlap query error icon.

Steps:

1. Execute a query with some error as a query.
2. Execute the same query as a script.

![VXAvmLBoda](https://user-images.githubusercontent.com/45152336/161501480-e77ec804-04c2-4ff0-9bad-a542e765253f.gif)

**Comment by ShadelessFox** [comment]
Fixed in #16270
