### ISSUE TITLE
Embedded SQL editors do not show errors

### ISSUE THREAD

**Issue by reinaldofox** [dbeaver/dbeaver#16069]
SQL Editor does not mark lines with errors and does not point out what the error is when typing or editing code.
This drives me crazy, because when I try to code a procedure, for example, the program just stops saving it and just says that there are errors.
In MySQL Workbench it marks the line with error and displays a red dot which when clicked shows the error description.
What if this also happened with Dbeaver?

**Comment by LonwoLonwo** [comment]
Hello @reinaldofox 

What DBeaver version do you use?
What database and driver do you use?

**Comment by reinaldofox** [comment]
Database MySQL 8.0.28-0ubuntu0.21.10.3
DBeaver Version 22.0.1.202203181646

**Comment by ShadelessFox** [comment]
Hello @reinaldofox,

Are you talking about the SQL editor or the DDL viewer of a procedure?

Can you please record a video showing the issue?

**Comment by reinaldofox** [comment]
> Hello @reinaldofox,
> 
> Are you talking about the SQL editor or the DDL viewer of a procedure?
> 
> Can you please record a video showing the issue?


https://user-images.githubusercontent.com/1627337/162006858-28661194-c592-4c29-9d7f-6b6c5b484412.mp4

**Comment by ShadelessFox** [comment]
I see, thanks.

Error highlighting is not supported in embedded SQL editors.

**Comment by ShadelessFox** [comment]
Hello @reinaldofox,

After further investigation, it seems that you're using the MySQL driver that doesn't report error positions.

Consider using the MariaDB driver.

Please let me know if it solves your issue.

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If the issue is still actual for you, feel free to reopen it.
