### ISSUE TITLE
Cassandra: Cannot handle user defined types with case sensitive fields

### ISSUE THREAD

**Issue by marcelvillet** [dbeaver/dbeaver#1606]
If you create a user-defined type in Cassandra such as the following:

```
CREATE TYPE "file_info3"
(
	"FileId"		UUID,
	"Name"			TEXT,
	"Size"			INT
);
```

The following error is received when the list of tables is refreshed:

```
Can't read userTypes
  java.lang.IllegalArgumentException: FileId is not a field defined in this definition
```

Also, querying a table no longer shows the grid.

**Comment by ccazette** [comment]
This issue is pretty annoying indeed... CamelCase is accepted in CQL.

**Comment by vakbrain** [comment]
I bought DBeaver Enterprise precisely for its Cassandra database support but this issue very annoying! Is there a workaround other than to use the Text mode instead of Grid mode?

**Comment by serge-rider** [comment]
Fixed.
We will publish hotfix version of DBeaver EE  this week.

**Comment by uslss** [comment]
verified
