### ISSUE TITLE
DB2i Enhancements

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#16060]
DBeaver 22.0.2

We need better support of DB2 iSeries/A400 driver

- Sequences support
- Unique keys and check constraints

**Comment by LonwoLonwo** [comment]
Implemented:

- sequences support (without DDL for now); 
- view definition reading support (system and custom);
- unique key and check constraints reading and adding support; 
- ability to rename tables via UI
- ability to add table and column comments via UI


![2022-04-01 01_28_05-DBeaver Ultimate 22 0 2 - NEWTABLE](https://user-images.githubusercontent.com/45152336/161163453-5ef42767-99c3-491e-b1f3-cf0236024788.png)

![2022-04-01 01_47_59-DBeaver Ultimate 22 0 2 - T1](https://user-images.githubusercontent.com/45152336/161163454-9e3e6054-0b09-4f69-b751-38311e270935.png)

![2022-04-01 01_48_40-T1 - Persist Changes](https://user-images.githubusercontent.com/45152336/161163455-a5215b4f-8b41-45e8-a2d3-ee245c2652f5.png)

![2022-04-01 01_51_23-DBeaver Ultimate 22 0 2 - TEST_VIEW](https://user-images.githubusercontent.com/45152336/161163456-d955aca2-ba15-4700-89b4-9f4036e1abce.png)

![2022-03-31 17_55_23-DBeaver Ultimate 22 0 2 - _PUB400 COM_Script-143](https://user-images.githubusercontent.com/45152336/161163449-045f7c33-ba7c-47db-8533-cb4ee3d1beb1.png)

**Comment by LonwoLonwo** [comment]
Related links:

https://www.ibm.com/docs/en/i/7.2?topic=constraints-adding-using-check
https://www.ibm.com/docs/en/i/7.2?topic=statements-rename

**Comment by uslss** [comment]
verified
