### ISSUE TITLE
The release date is showing ahead of one month.

### ISSUE THREAD

**Issue by sandofvega** [dbeaver/dbeaver#16065]
#### System information: 
- Operating system: Ubuntu 20.04
- DBeaver version: 22.0.2.202204021640

#### Describe the problem you're observing:
Today is April 4, 2022. The release date is showing ahead of one month.

#### Steps to reproduce, if exist:
Help -> About

![screenshot-nimbusweb me-2022 04 04-17_23_40](https://user-images.githubusercontent.com/34006175/161534040-283b96f6-c5a1-4f04-a1ba-d47f46096bdc.png)

**Comment by serge-rider** [comment]
Thanks you for the bug report.
It is a bug in release description. We will fix it in the next version.
