### ISSUE TITLE
Mapping "VARCHAR" during export from MySQL to Oracle 

### ISSUE THREAD

**Issue by mandreato** [dbeaver/dbeaver#16079]
Oracle VARCHAR datatype is a synonym to VARCHAR2 but should not be used --> [https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Data-Types.html#GUID-DF7E10FC-A461-4325-A295-3FD4D150809E](url)

So during export/import from MySQL to Oracle, VARCHAR columns should be mapped to VARCHAR2.

**Comment by uslss** [comment]
thanks for the suggestion
