### ISSUE TITLE
Broken selection in SQL Editor

### ISSUE THREAD

**Issue by artukn** [dbeaver/dbeaver#16071]
Reopening closed issue [#11205](https://github.com/dbeaver/dbeaver/issues/11205) as it is not fixed till this day.

#### System information: 
- Ubuntu 16.04 LTS
- DBeaver version 7.3.1-22.0.2.202204021640
- No additional extensions

#### Connection specification:
- Not relevant

#### Describe the problem you're observing:
In SQL editor (or any text file really) trying to select some text with your mouse always selects from top of the screen to caret position and instantly copies selected text. Selection is done from the top of visible text (if scrolled down), not from the top of the document.

#### Steps to reproduce, if exist:
- Be on Ubuntu 16.04 LTS (might be relevant as all users previously reporting this issue in #11205 were on this version)
- Open any file editor
- Try selecting text with your mouse

**Comment by artukn** [comment]
I've checked old DBeaver versions on a clean Ubuntu 16.04 install and found that version 7.3.0 works correctly, while 7.3.1 no longer does.

**Comment by artukn** [comment]
Also happens in table data filter field. Possibly all fields with autocomplete functionality are affected

**Comment by Destrolaric** [comment]
@artukn Hi found some info regarding your issue. It impacts Ubuntu 16, so I think library update should solve it.

> FIX1: you need "export SWT_GTK3=0"

> FIX2: libgtk-3-0 should be version 3.20.x instead of 3.18 . Ubuntu16 provides only the older version. I upgraded to ubuntu18, and don't hit the issue anymore. The issue exists since Eclipse 2020.3 or earlier. I had been using FIX1 for a long time (since I use KDE), so I'm not sure when it regressed.

Could you try it?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.
