### ISSUE TITLE
More definition for text boxes in dark theme

### ISSUE THREAD

**Issue by rjake** [dbeaver/dbeaver#16073]
**Is your feature request related to a problem? Please describe.**
When I use the dark theme, I find it hard to see where there is text I can edit or fields that need to be filled in. It's easy to miss a field. 

In this example, I find it difficult to see how to change the name of the file or the timestamp format. 

> ![image](https://user-images.githubusercontent.com/14003618/161563424-ea587319-22c5-4e5f-babf-c4e4451205c0.png)

In this one, it's easy to miss the port
> ![image](https://user-images.githubusercontent.com/14003618/161564330-bbc50396-8437-4859-8949-b1a6a8b5ac15.png)

I didn't see anything about this when searching online and I reset my colors in case there was something I did on my end.

**Describe the solution you'd like**
Can you make these fields have a different color or have a border that makes it easier to discern that the field is editable?

**Comment by ShadelessFox** [comment]
Hello @rjake,

Sorry for the late response.

Unfortunately, I believe that it's the issue of Eclipse.

Have you tried the Darkest Dark theme? https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual - feel free to reopen it with additional info

**Comment by rjake** [comment]
For the record, the Darkest Dark Theme worked! Thank you
