### ISSUE TITLE
How do I turn off the red squiggly lines when error is encountered?

### ISSUE THREAD

**Issue by Enphynity** [dbeaver/dbeaver#16070]
How can I turn off the red squiggly lines that show up when an error is encountered?  Sometimes they don't go away when the query executes successfully and can be quite annoying to look at.

![image](https://user-images.githubusercontent.com/102975271/161563309-d92f127a-1d74-4032-a62e-2a09f1485b21.png)

Thank you

**Comment by LonwoLonwo** [comment]
Hello @Enphynity 

Starts DBeaver 22.0.2 version you can disable this behavior in Preferences -> Editors -> SQL Editor -> Code Editor ("Show problem markers").

![image](https://user-images.githubusercontent.com/35821147/159919687-8df7d259-dc9a-4f04-9b42-8f0874b94b1e.png)

**Comment by Enphynity** [comment]
Thanks so much!
