### ISSUE TITLE
com.sun.jna.LastErrorException when connecting to Postgres

### ISSUE THREAD

**Issue by Ellebjerg** [dbeaver/dbeaver#16086]
When I try to connect to Postgres from DBeaver 22.0.2, I get the error message in the attached screenshot.

Best regards,

Lars Ellebjerg

**Comment by E1izabeth** [comment]
Hi, @Ellebjerg! Unfortunately, your screenshot seems to have failed to load. Please, reattach it.

**Comment by Ellebjerg** [comment]
![Screenshot 2022-04-05 161112](https://user-images.githubusercontent.com/10741426/161776225-9d60957c-deee-49f8-be6c-f37fb07e4bad.png)

**Comment by E1izabeth** [comment]
Could you, please, also specify your Postgres version?
Has the connection been established or it was failed with this error?

**Comment by Ellebjerg** [comment]
It is a PG11 with postgis-extention

**Comment by Ellebjerg** [comment]
DBeaver 22.0.2.202204041542.
There is no connection

**Comment by LonwoLonwo** [comment]
Hello @Ellebjerg 

Can you please attach the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

Also, what Operating system do you use? And what driver version do you use? And how did you install DBeaver (installer, Eclipse etc.)?

**Comment by Ellebjerg** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/8426303/dbeaver-debug.log)
[log.log](https://github.com/dbeaver/dbeaver/files/8426310/log.log) - renamed hidden file

I use Windows 10 and installed DBeaver using the installer from https://dbeaver.io/download/.

Which driver do you ask for the version of?

**Comment by LonwoLonwo** [comment]
You can send this picture with drivers versions from the PG connection settings page

![2022-04-06 15_14_23-Window](https://user-images.githubusercontent.com/45152336/161972339-e5aeae69-dad1-47d1-9123-5aaedd78bed0.png)

**Comment by LonwoLonwo** [comment]
Also, I see many wornings in your logs like

> Couldn't get password from PGPASS file

If this important? Error from this issue is associated with PGPASS authentication?

**Comment by Ellebjerg** [comment]
Don't bother with the PGPASS part of the log. We don't use it. I just tried to see what would happen with that setting on.

![pg_driver_settings](https://user-images.githubusercontent.com/10741426/161976206-6b2639b3-ae55-4ba6-baa6-7192f66c7756.png)

**Comment by flambchap** [comment]
SSPI auth does not work for some reason.

**Comment by flambchap** [comment]
Classloader cannot find JNA. We need to include it as a dependency.

**Comment by flambchap** [comment]
@Ellebjerg As a workaround, I suggest loading optional dependencies for the driver. Please double-click on the `org.postgresql:postgresql` entry, click on the 'Load additional dependencies' checkbox.

**Comment by Ellebjerg** [comment]
> @Ellebjerg As a workaround, I suggest loading optional dependencies for the driver. Please double-click on the `org.postgresql:postgresql` entry, click on the 'Load additional dependencies' checkbox.

I have just tried this. I have tried refreshing the connection, and I have restartet DBeaver, but I still get com.sun.jna.LastErrorException, when I try to access the server.

**Comment by serge-rider** [comment]
The problem was in conflicting JNA dependencies.

It was fixed (now it is possible to simply add Waffle dependency to PostgreSQL driver libraries).

Also PostgreSQL SSPI authentication will be added in DBeaver 22.1. IT will trigger Waffle libraries download automatically.
Early Access version will be published later this week.

**Comment by serge-rider** [comment]
Linked issue: #8247

**Comment by uslss** [comment]
verified
