### ISSUE TITLE
Is create mysql table by sql support in DBeaver ? 

### ISSUE THREAD

**Issue by milkeasd** [dbeaver/dbeaver#16085]
Is create mysql table by sql support in DBeaver ?

**Comment by E1izabeth** [comment]
HI, @milkeasd! You can write sql queries in SQL Editor https://dbeaver.com/docs/wiki/SQL-Editor/ , including "create table", "insert into" queries. Is that what you mean?

**Comment by uslss** [comment]
There has been no update on the issue for a long time.  If it is still actual - feel free to reopen it
