### ISSUE TITLE
DB2/400 semicolumn terminator in last line

### ISSUE THREAD

**Issue by garetjax76** [dbeaver/dbeaver#16084]
- Operating system: Win10 Pro
- DBeaver version: 22.0.2.202204041542
- Database name and version: DB2/400
- Driver name: DB2 iSeries/AS 400

I usually write my queries like this:

> select * from 
> file a
> join file b on a.x = b.y
> where z=''
> ;

(with the single semicolumn as the last line), and executing the query with CTRL+Enter on any line always worked.
Starting with 22.0.2 this throws an error:

> Updated Rows	-1
> Query	;
> Finish time	Tue Apr 05 14:57:45 CEST 2022

This happens no matter the cursor position.

If I move the semicolumn on the previous line like this
> select * from 
> file a
> join file b on a.x = b.y
> where z='';

it works.

In the error log there's no indication at all about this.

**Comment by E1izabeth** [comment]
Thank you for bug report. This bug was already fixed https://github.com/dbeaver/dbeaver/issues/16077. Hotfix patch was applied to version 22.0.2, you can re-download it from [dbeaver.io](http://dbeaver.io/) website or from GitHub.
