### ISSUE TITLE
alt + lbm for vertical selection

### ISSUE THREAD

**Issue by Lewonna** [dbeaver/dbeaver#16093]
**Is your feature request related to a problem? Please describe.**
Is there a vertical selection option like MS SQL? 
![image](https://user-images.githubusercontent.com/43236226/161911393-6dbae62a-9e12-4e79-89e2-d7ebff0ac530.png)

If there is such a possibility, please tell me how to do it.

**Comment by uslss** [comment]
@Lewonna , if I understand you correctly, it could be done using Alt+Shift+A. Does it resolve your issue?
![image](https://user-images.githubusercontent.com/31996417/161919812-8f8a3a1d-0770-4761-bd8a-5e4368c53436.png)

**Comment by Lewonna** [comment]
that's what I need, thank you :)
