### ISSUE TITLE
Please add the line number when the SQL returns the error information, and the error prompt is detailed to each line

### ISSUE THREAD

**Issue by zhaozhilong999** [dbeaver/dbeaver#16096]
When executing SQL, if there is an error message, please print and mark the wrong line number. If there is no line number, it is very troublesome to find the problem.

**Comment by LonwoLonwo** [comment]
Hello @zhaozhilong999 

What DBeaver version do you use?
And what database do you use?

**Comment by Lewonna** [comment]
Excuse me, can I join this issue please? I have the same problem. 

**What DBeaver version do you use?**
Community edition, version 22.0.1.202203181646

**And what database do you use?**
PostgreSQL

**Comment by zhaozhilong999** [comment]
> 你好@zhaozhilong999
> 
> 您使用的是哪个 DBeaver 版本？您使用什么数据库？

个 DBeaver Version   22.0.2.202204041542


> Hello @zhaozhilong999
> 
> What DBeaver version do you use? And what database do you use?
DBeaver version 22.0.2.202204041542
database is Oracle

Display line number when there is an error message
