### ISSUE TITLE
Receiving 'Datasource was invalidated' notification

### ISSUE THREAD

**Issue by alanneese** [dbeaver/dbeaver#16092]
### Discussed in https://github.com/dbeaver/dbeaver/discussions/15936

<div type='discussions-op-text'>

<sup>Originally posted by **alanneese** March  1, 2022</sup>

#### System information: 
- Windows 10
- DBeaver 21.3.5.202202200327

#### Connection specification:
- Database name : jhj7bqbh_menudb
- Driver name : MySQL 5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I keep getting the notification from DBeaver 'Datasource was invalidated'  Live connection count: 2/2
#### Steps to reproduce, if exist:
Just access my database and run a query.
#### Include any warning/errors/backtraces from the logs

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Mar 01 15:11:21 CST 2022
Cannot determine transaction isolation level due to connection hanging. Setting to NONE.
</div>

**Comment by uslss** [comment]
@alanneese could you provide a video with the issue? is it reproducible against 22.0.2?

**Comment by uslss** [comment]
There has been no update on the issue for a long time.  If it is still reproducible - feel free to reopen it

**Comment by alanneese** [comment]
Please click on this link <https://screenrec.com/share/ZY9Vuq5F0g>.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
