### ISSUE TITLE
The ''Normal' execution method locks tables for MySQL dumps 

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#16100]
#### System information: 
- Operating system (distribution) and version RHEL 8.5
- DBeaver version 22.0.0 UE
- Additional extensions

#### Connection specification:
- Database name and version MariaDB 10.3.23
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Steps to reproduce, if exist:
1. Create a dump task
2. Choose the 'Normal (no locks)' Execution Method
3. Execute the task. Observe that all tables are locked.

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
