### ISSUE TITLE
Can not create a new SQL Script

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#16105]
#### System information: 
- Operating system (distribution) and version: Windows 10 Enterprise Version 21H2 OS Build 19044.1586 
- DBeaver version: Version 22.0.2.202204041542
- Java version: 8 update 321 (build 1.8.0_321-b07)
- Additional extensions: DBeaver Office integration

#### Connection specification:
- Database name and version: ALL
- Driver name: ALL
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  None

#### Describe the problem you're observing: when i click on a new SQL script it errors out
![image](https://user-images.githubusercontent.com/27461740/162029243-172a5275-9835-4d9b-8f9f-76f917b1e8cc.png)

**Comment by ShadelessFox** [comment]
Hello @Adamkrein,

Could you please send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.

**Comment by ghost** [comment]
You can close the ticket. After a reboot of my system it started to work.

**Comment by LonwoLonwo** [comment]
Thanks for the answer @Adamkrein
