### ISSUE TITLE
SQL Editor Templates don't filter based on context

### ISSUE THREAD

**Issue by jetzerb** [dbeaver/dbeaver#16121]
#### System information: 
- Windows 10
- DBeaver 22.0.2.202204041542

#### Describe the problem you're observing:
In a SQL editor, when I hit `CTRL+ALT+SPACE` to generate the list of Templates to choose from, _all_ templates are shown, rather than just templates that apply to my current connection.

#### Steps to reproduce, if exist:
1. Create two templates, each with "context" set to a specific DB engine:
![image](https://user-images.githubusercontent.com/36859020/162261991-80b95878-ee68-4868-914c-9c45ce4a08d5.png)

1. Open a new SQL Editor tab of _any_ connection

1. Hit `CTRL+ALT+SPACE` and note that all templates are shown, even if the context does not match the current connection.  Also note that the context is not listed next to the template, so if two templates have the same name, you must look through the (unformatted) preview to determine which is the correct one for your current connection.
![image](https://user-images.githubusercontent.com/36859020/162261830-1f5ac4b2-03d9-4b8a-bff8-c45a5db267a7.png)

**Comment by LonwoLonwo** [comment]
Thanks for report @jetzerb
