### ISSUE TITLE
Import Connection String in "Connect to a database" screen

### ISSUE THREAD

**Issue by janpio** [dbeaver/dbeaver#16129]
I have to add databases to my DBeaver a lot, multiple times a day. I get the connection details of these databases as a connection string of the form `postgresql://user:password@hostname:port/database`. Every time I paste that into the `Host` input field, then copy the database to the `Database` field, the port to `Port` and finally `Username` and `Password` as well. Then I remove the protocol and leftover `:@/` from `Host` and can test the connection - and then continue.
 
It would be super neat if there was an "Import connection string" button where I get a windows with a text field where I can paste the connection string, then click "Parse and Import" (or similar) and the window closes and the parse parts of the connection string are filled in.

(Even more advanced (and less UI clutter) would be if one could just paste a connection string into the `Host` input field, it would detect that this is a connection string and not just a hostname and parse it and move the data into the appropriate fields automatically.)

Any other alternative I could think of would not actually be much faster than my current workflow (E.g. external tool that splits the connection string into its segments to copy paste or similar) unfortunately.

**Comment by ShadelessFox** [comment]
Hello @janpio,

There is a feature you might like:

![image](https://user-images.githubusercontent.com/35821147/162565420-ffab284b-4fcd-4ff7-9b04-43dd1ff4b2ec.png)

Although it doesn't handle the credentials part, it recognizes most other fields according to the URL template of the driver.

Please let me know if it solves your issue.

**Comment by janpio** [comment]
Wow, I always ignored that because I know nothing about JDBC.

It is indeed pretty close already: I have to type `jdbc:`, remove the credentials `user:password@` and then it indeed detects the details of my URLs correctly 🥳 

Seems like this could probably be expanded into a "New Connection from database URL" - and in the window that opens the input field could for example detect JDBC URLs based on `jdbc:` at the beginning, otherwise apply the existing splitting directly and also support username and password. (Or a checkbox that is by default on `JDBC URL` but has a second option `connection URL`)

(Having typed this, I of course realized that non of that might be easy or obviousy - a quick look at the code confirms that of course, the patterns come from the drivers it seems: https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/dialogs/connection/NewConnectionFromUrlDialog.java)

Update: On the other hand, the system at least seems to be capable of also parsing usernames and passwords: https://github.com/dbeaver/dbeaver/blob/5c2e5ff507f8c5a50d4414738f82d49a5c371d6b/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/jdbc/JDBCURL.java#L219

**Comment by ShadelessFox** [comment]
Implemented:

![image](https://user-images.githubusercontent.com/35821147/168122507-99d0a6c6-b95c-47c1-8adf-914f38e58a6c.png)

A small lamp-like overlay is shown on drivers matched by a non-genuine URL. Somewhat useless, but looks cool.
