### ISSUE TITLE
GIS map viewer not displayed, prompted with a save file dialog instead

### ISSUE THREAD

**Issue by ar-jan** [dbeaver/dbeaver#16125]
#### System information: 
- Void Linux
- 22.0.1 and 22.0.2
- Additional extensions: none

#### Connection specification:
- PostgreSQL 14.1 with PostGIS 3.1.5
- Driver: PostgreSQL JDBC Driver 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

When selecting a geometry column (with points in my case), instead of displaying a map in the results panel, I get a popup with a save dialog for filenames like `view9632421655832820860gis.html`. After canceling the same save dialog appears a second time.

#### Steps to reproduce, if exist:

I think this problem was introduced in version 22.0.1.

**Comment by LonwoLonwo** [comment]
Hello @ar-jan 

Can you provide table DDL and some test data for the investigation?

**Comment by ar-jan** [comment]
Sure, here is a simplified example:

```
CREATE TABLE public.mapviewtest (
	id serial4 NOT NULL,
	wkb_geometry public.geometry(point, 4326) NULL,
	"name" varchar NULL,
	CONSTRAINT mapviewtest_pk PRIMARY KEY (id)
);

CREATE INDEX mapviewtest_wkb_geometry_geom_idx ON public.mapviewtest USING gist (wkb_geometry);

INSERT INTO public.mapviewtest (wkb_geometry,"name") VALUES
	 ('SRID=4326;POINT (-71.94773 -43.384105)','Paso de Oro'),
	 ('SRID=4326;POINT (-72.172656 -43.229429)','Lago de Los Cedros'),
	 ('SRID=4326;POINT (-72.201494 -43.225528)','Laguna Alpargata'),
	 ('SRID=4326;POINT (-72.55766 -43.223564)','Río Avalanchas'),
	 ('SRID=4326;POINT (-72.988635 -43.573211)','Cerro Campanario');
```

**Comment by flambchap** [comment]
Hi @ar-jan. What kind of packaging do you use?

**Comment by ar-jan** [comment]
It's built with `mvn package -P all-platforms`, as in [this template](https://github.com/void-linux/void-packages/blob/master/srcpkgs/dbeaver/template). The method of packaging has not changed recently though, while this issue did not occur with previous versions (I'm not certain which version last worked correctly for me).

**Comment by ar-jan** [comment]
I tried several earlier versions and they now all show this behavior, even though I am certain they didn't use to before. This suggests it's some other configuration that is interfering, and not the DBeaver version itself.

I couldn't find any relevant DBeaver configuration, except maybe `Use external/internal web browser`. I had this set to external (the default?) and the GIS viewer used to work correctly wit this setting. I tried internal, and it didn't make a difference.

Is there any OS configuration that could interfere? It seems like there shouldn't be, DBeaver should be in control of displaying everything right? I'm also not aware of any OS or system configuration change that could have caused this.

**Comment by iomihai** [comment]
I experience this too
OS: Archlinux 
GNOME: 42
DBeaver: Version 22.0.1
Postgres: PostgreSQL 10.19
Postgis: 2.4

Query: `SELECT 'SRID=4326;POINT (-71.94773 -43.384105)'::geometry;`

Result map panel is grey and I get a save as prompt to save the html file, if I  click `Open in a browser` the map is correct.
I have `Use internal web browser` in `User Interface/Web Browser` selected (tried toggling it on and off).

journal log when I run this query is 
```
Apr 13 11:08:52 nothostname java[4120]: Negative content width -8 (allocation 5, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)
Apr 13 11:08:52 nothostname java[4120]: Negative content width -8 (allocation 5, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)
Apr 13 11:08:52 nothostname java[4120]: Negative content width -8 (allocation 5, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)
Apr 13 11:08:52 nothostname java[4120]: Negative content width -8 (allocation 5, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)
Apr 13 11:08:52 nothostname java[4120]: Negative content width -8 (allocation 5, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)
Apr 13 11:08:52 nothostname java[4120]: Negative content width -8 (allocation 5, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)
```
I do not know how relevant it is but I also get some warning from Realtimekit daemon
```
Apr 13 11:08:52 nothostname rtkit-daemon[848]: Supervising 10 threads of 7 processes of 1 users.
Apr 13 11:08:52 nothostname rtkit-daemon[848]: Successfully made thread 12339 of process 12331 owned by '1000' RT at priority 5.
Apr 13 11:08:52 nothostname rtkit-daemon[848]: Supervising 11 threads of 8 processes of 1 users.
Apr 13 11:08:52 nothostname rtkit-daemon[848]: Supervising 11 threads of 8 processes of 1 users.
Apr 13 11:08:52 nothostname rtkit-daemon[848]: Successfully made thread 12362 of process 12331 owned by '1000' RT at priority 5.
Apr 13 11:08:52 nothostname rtkit-daemon[848]: Supervising 12 threads of 8 processes of 1 users.
Apr 13 11:08:54 nothostname rtkit-daemon[848]: Supervising 12 threads of 8 processes of 1 users.
Apr 13 11:08:54 nothostname rtkit-daemon[848]: Supervising 12 threads of 8 processes of 1 users.
```

**Comment by ShadelessFox** [comment]
Hello @iomihai @ar-jan,

Can you please send a screenshot of the <kbd>User Interface</kbd> &rArr; <kbd>Web Browser</kbd> preferences page?

Thanks.

**Comment by ar-jan** [comment]
![image](https://user-images.githubusercontent.com/1176293/163189923-5b9fbcb2-4915-4922-b366-9d772dcee970.png)

Here's my current settings. I've also tried `Use external web browser` with both `Default system web browser` or `Firefox` selected.

**Comment by ShadelessFox** [comment]
Can you please record a video showing the issue, including a footage after you close the save file dialog?

**Comment by ar-jan** [comment]
![2022-04-13_DBeaver-mapviewtest2](https://user-images.githubusercontent.com/1176293/163250457-de439a1b-3b10-437f-911c-3633285d611d.gif)

**Comment by ShadelessFox** [comment]
It looks like a bug in the browser implementation in the Eclipse platform under Linux.

After some additional research, I came up with the following solution:
```sh
rm ~/.local/share/mime/packages/user-extension-html.xml
update-mime-database ~/.local/share/mime
```

Please let me know if it helps.

**Comment by ar-jan** [comment]
Yes, this fixes it, thanks!

Any idea what change caused this? Because up until some 2-3 weeks ago this didn't happen.

**Comment by ShadelessFox** [comment]
It has something to do with GNOME.

I don't have any other information about this issue, unfortunately. It's barely mentioned anywhere.
