### ISSUE TITLE
Export CVS is not the selected data

### ISSUE THREAD

**Issue by BYNepenthe** [dbeaver/dbeaver#16126]
#### System information: 
- Operating system (distribution) and version：MacOS Catalina 10.15.7
- DBeaver version：22.0.0.202203060510

#### Connection specification:
- Database name and version：oracle

#### Describe the problem you're observing:
Select the data row, export the result set, select CVS, check "Select row, select column", the exported data is often not the selected row data

**Comment by LonwoLonwo** [comment]
Please provide more steps about your issue. Screens can be helpful.

**Comment by uslss** [comment]
There has been no update on the issue for a long time.  If it is still reproducible - feel free to reopen it
