### ISSUE TITLE
Missing highlighting for lot of datatypes (how to add Custom Data Types)

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#16131]
#### System information: 
- Operating system (distribution) and version: Fedora 35
- DBeaver version: 22.0.2.202204041542
- Additional extensions: N/A

#### Connection specification:
- Database name and version: Postgres 12, Postgres 13
- Driver name: Postgres
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
A lot of data types are not highlighted. Incl so common ones like: RECORD, HSTORE, INET, DATERANGE etc.

I quickly wrote a query to generate a list of available data types...
```
SELECT format ('var%s %s;', oid, UPPER(format_type(oid, NULL))) FROM pg_catalog.pg_type WHERE typrelid = 0
AND typname !~ '^_'
ORDER BY typname
```
It shows a huge number of them are not recognized as keywords.

Is there any way to add them to the local dictionary?

```
 ACLITEM
 ANYARRAY
 ANYCOMPATIBLE
 ANYCOMPATIBLEARRAY
 ANYCOMPATIBLENONARRAY
 ANYCOMPATIBLERANGE
 ANYELEMENT
 ANYENUM
 ANYNONARRAY
 ANYRANGE
 CID
 CIDR
 CSTRING
 DATERANGE
 EVENT_TRIGGER
 FDW_HANDLER
  GHSTORE
 GTSVECTOR
  HSTORE
 INDEX_AM_HANDLER
 INET
 INT2VECTOR
 INT4RANGE
 INT8RANGE
 INT8RANGE
 INTERNAL
 JSONPATH
 LANGUAGE_HANDLER
 MACADDR
 MACADDR8
 NUMRANGE
 OIDVECTOR
 PG_DDL_COMMAND
 PG_LSN
 PG_SNAPSHOT
 POINT
 RECORD
 REFCURSOR
 TABLE_AM_HANDLER
 TID
 TSM_HANDLER
 TSQUERY
 TSRANGE
 TSTZRANGE
 TSVECTOR
 TXID_SNAPSHOT
 UUID
 XID
 XID8
```
![image](https://user-images.githubusercontent.com/7868445/162439816-3f71bbf1-525a-4458-b4da-f424a9e12b50.png)

#### Steps to reproduce, if exist:
Run the query posted above, and put the result into SQL editor connected to PostgreSQL database.
#### Include any warning/errors/backtraces from the logs
N/A

**Comment by michal-bartak** [comment]
Is there a way to add data types or keywords by a user?

**Comment by LonwoLonwo** [comment]
Ok, thanks for the idea.
Wi will add custom functions/keywords support in this ticket:
https://github.com/dbeaver/dbeaver/issues/6528
