### ISSUE TITLE
Export option "Selected columns only" doesn't work

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#16148]
#### System information: 
- Win11
- DBeaver version CE 22.0.3

#### Describe the problem you're observing:
Export option "Selected columns only" doesn't work

#### Steps to reproduce, if exist:
1. Open table and select some rows
![image](https://user-images.githubusercontent.com/43252954/162763498-04b2f126-44dd-46ab-9e5a-008d37408398.png)
2. Right click -> Export data
3. Enable option "Selected columns only" and start export
![image](https://user-images.githubusercontent.com/43252954/162763196-393c3416-1ec9-49a3-9906-103f28a3fedd.png)
As a result, all of columns are exported, no matter which you choose

**Comment by serge-rider** [comment]
Side effect of #15097 fix
Will be tracked in the original ticket
