### ISSUE TITLE
When closing tab with currently running, unsaved query, two modals interfere with each other

### ISSUE THREAD

**Issue by quassy** [dbeaver/dbeaver#16143]
#### System information: 
- macOS Montery 12.3.1
- DBeaver 22.0.2
- Additional extensions: None

#### Connection specification:
- PostgreSQL 10
- PostgreSQL JDBC Driver
- No tunnels or proxies, just VPN

#### Describe the problem you're observing:
Modal dialogue windows overlap and have to be dealt with in non-intuitive order, making you think at first DBeaver has crashed (as the visually prominent modal is not responsive), when you close a tab with currently running, unsaved query.

#### Steps to reproduce, if exist:
1. Start a long running query in a new sql editor tab
2. Click to close said tab long before query has finished
3. (Confirm cancel running queries)
4. DBeaver will ask you to _Save 'Script-123.sql'?_ and everything in the background is dimmed (modal 1)
5. DBeaver will then display an Execution Error _SQL Error [57014]: ERROR: canceling statement due to user request_ (modal 2)
6. Even though modal 1 looks like the active modal displayed on top of everything else, actually only modal 2 is active and has to be dismissed first before one can interact with modal 1

#### Include any warning/errors/backtraces from the logs
Screenshot
<img width="688" alt="image" src="https://user-images.githubusercontent.com/369996/162737529-24f5a810-a073-432d-940b-19f62e79d825.png">

**Comment by Destrolaric** [comment]
Confirmed, will be done in the scope of #13691
