### ISSUE TITLE
Wrong value reported in selected columns under some query conditions

### ISSUE THREAD

**Issue by george-a-g** [dbeaver/dbeaver#16149]
#### System information: 
- Operating system:  (distribution) and version:
     Edition: Windows 10 Enterprise
     Version: 21H2
     OS Build: 19044.1586
     Windows Feature Experience Pack 120.2212.4170.0
- DBeaver version:Version 22.0.2.202204041542
- Additional extensions:-

#### Connection specification:
- Database name and version:PostgreSQL 13.4 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-6), 64-bit
- Driver name: PostgreSQL JDBC Driver 42.2.20
- Do you use tunnels or proxies (SSH, SOCKS, etc)? -

#### Describe the problem you're observing:
If  we have two tables A and B in a join 
and one of the selected columns of table A is given the name of another column of table A as an alias 
and the columns of the other table are included with the "*" operator in the selected columns
then 
 the column of table A having the name of another column of table A as an alias is:
   * reported as null, even though it has a value, IF it is included AFTER  the "*" operator in the selectd columns
   * reported correctly,                           IF it is included BEFORE the "*" operator in the selected columns

#### Steps to reproduce:

create table scratch.test2 
    (id         bigint, 
     col_bigint bigint, 
     col_uuid   uuid, 
     col_a      bigint); 
     
insert into scratch.test2 
    (id, col_bigint, col_uuid, col_a) 
  values 
    (10, 1, '9dd49536-1784-4c67-bfc1-20d4c9d9aede'::uuid, 14);

create table scratch.test3 
  (id bigint, 
   col_b bigint
  ); 
  
insert into scratch.test3 
    (id, col_b) 
  values 
    (33, 14);

--Correct behavior
select test2.id, 
       col_uuid col_bigint,  --  reported as 9dd49536-1784-4c67-bfc1-20d4c9d9aede
       test3.*, 
       col_uuid another_alias --  reported as 9dd49536-1784-4c67-bfc1-20d4c9d9aede
  from scratch.test2,
       scratch.test3
 where test2.col_a = test3.col_b

-- Correct behavior
select test2.id, 
       col_uuid col_bigint,   --  reported as 9dd49536-1784-4c67-bfc1-20d4c9d9aede
    -- test3.*, 
       col_uuid col_bigint    --  reported as 9dd49536-1784-4c67-bfc1-20d4c9d9aede
  from scratch.test2,
       scratch.test3
 where test2.col_a = test3.col_b 

-- Bug manifestation
select test2.id, 
       col_uuid col_bigint,  --  reported as 9dd49536-1784-4c67-bfc1-20d4c9d9aede
       test3.*, 
       col_uuid col_bigint   --  reported as null
  from scratch.test2,
       scratch.test3
 where test2.col_a = test3.col_b

-- Bug manifestation
select test2.id, 
    -- col_uuid col_bigint, 
       test3.*, 
       col_uuid col_bigint    --  reported as null    
  from scratch.test2,
       scratch.test3
 where test2.col_a = test3.col_b

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @george-a-g

**Comment by PILINING** [comment]
Hello. @LonwoLonwo I"d like to work on this issue.

**Comment by E1izabeth** [comment]
I can't reproduce this bug anymore. It seems that the issue has been solved.
Please, feel free to inform us if the bug is still exists for you.
