### ISSUE TITLE
sets cursor/selection on error position in the query

### ISSUE THREAD

**Issue by Lewonna** [dbeaver/dbeaver#16154]
**Is your feature request related to a problem? Please describe.**
Hello everyone. I use dbeaver community edition, version 22.0.2.202204041542, postgresql db.
PostgreSQL driver:
![image](https://user-images.githubusercontent.com/43236226/162882407-f8cb93c4-b6c1-4e11-b730-a8b2cbbc5fd3.png)

Initially my problem is that postgreSQL only shows me the position of error, not a line. And dont sets cursor.
![image](https://user-images.githubusercontent.com/43236226/162880967-684c2fef-06d4-48ea-a79b-71f8fafebb7d.png)
This makes it harder to debug the code.

After researching the previous tasks, I found the tasks: https://github.com/dbeaver/dbeaver/issues/1411.
And there, one of the development members says that this option has been around for a long time. 
https://github.com/dbeaver/dbeaver/issues/1411#issuecomment-408762972

But I can't find an option that will highlight line of error and sets cursor on error in scripts.
Could you help me find it, please?

**Describe the solution you'd like**
So, by analogy with MS SQL server, I'd like..
1: tooltip with error details
2: line of error in message 
3: double click on error message sets cursor on error position in the query.
![image](https://user-images.githubusercontent.com/43236226/162882058-9e2be2a5-8cdc-43bf-bff0-3b901fd40da5.png)

**Comment by LonwoLonwo** [comment]
Hello @Lewonna 

This feature request will be available in the next DBeaver release 22.0.3, 18-04-2022.

https://github.com/dbeaver/dbeaver/issues/13964#issuecomment-1094874512

**Comment by Lewonna** [comment]
Hello, I updated the app but it doesn't work.

I deliberately created three errors.
Result window is empty (Although according to the task #13964 it should have an error with the "Go to Error" button).

![image](https://user-images.githubusercontent.com/43236226/164615690-ae46d9e9-8ff2-479a-b40e-981b3d41a986.png)

**Comment by LonwoLonwo** [comment]
Can you please check the newest DBeaver version please? We fixed some problems in the SQL Editor view.
https://dbeaver.io/download/

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual, feel free to reopen it.
