### ISSUE TITLE
WinGet - Failed to install (Hash mismatch)

### ISSUE THREAD

**Issue by daviian** [dbeaver/dbeaver#16169]
#### System information: 
- Operating system (distribution) and version Windows 10 Build 19044
- DBeaver version 22.0.2
- Additional extensions N/A

#### Connection specification:
- Database name and version N/A
- Driver name N/A
- Do you use tunnels or proxies (SSH, SOCKS, etc)? N/A

#### Describe the problem you're observing:
When attempting to install / update DBeaver using winget command line utility, an error is encountered. The downloaded installer hash does not match the hash provided in DBeaver's winget repository entry.

#### Steps to reproduce, if exist:
1. Launch PowerShell / Windows Terminal.
2. Execute winget install --id "dbeaver.dbeaver"
3. winget downloads the installer successfully.
4. Installation is skipped because the installer hash did not match.

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/5477981/163111268-7f7cbf80-184c-4324-8710-ec5d5ad780e7.png)

Same issue already happened in January https://github.com/dbeaver/dbeaver/issues/15132

**Comment by LonwoLonwo** [comment]
Yes, DBeaver 22.0.3 was rereleased because of hotfix.
Could you please download the latest [DBeaver version](https://dbeaver.io/download/) and see if the issue is gone there?

**Comment by daviian** [comment]
Thank you very much. It' working now. 

Is there a possibility to prevent these issues in the future?

**Comment by LonwoLonwo** [comment]
We are working on it.
