### ISSUE TITLE
UI doesn't display FK for PSQL

### ISSUE THREAD

**Issue by RobinFrcd** [dbeaver/dbeaver#16164]
#### System information: 
- Linux, PopOS Kernel 5.16.15
- DBeaver Community: Version 22.0.2.202204041542 (Release date: 4 May 2022?)

#### Connection specification:
- Database name and version: PSQL 14.2
- Driver name: PostgreSQL JDBC Driver
- Plugging directly on a dockerized PSQL DB

#### Describe the problem you're observing:
I created two tables with a Foreign key linked them, the FK doesn't show in DBeaver.

![image](https://user-images.githubusercontent.com/29704178/162950902-e398bfbd-5c73-4bd1-b8f7-c19c582437e2.png)
But it exists if I request the DB or use another tool:
![image](https://user-images.githubusercontent.com/29704178/162951008-e6690d21-c815-4520-94dc-84c87d48f7ac.png)
![image](https://user-images.githubusercontent.com/29704178/162951062-3bc30d47-22b4-4ba4-9177-f1024fcc852b.png)

Looks like this [old issue](https://github.com/dbeaver/dbeaver/issues/4575)

**Comment by LonwoLonwo** [comment]
Did you refresh the database navigator after key creation? Maybe connect/disconnect can help?

**Comment by LonwoLonwo** [comment]
If not - please provide your tables DDL

**Comment by RobinFrcd** [comment]
Indeed, the connect/disconnect seems to work but no the refresh button.

here's the schema I used for my tests:

```sql
drop table if exists labels cascade;
CREATE TABLE labels (
    id serial primary key,
    en text,
    fr text,
    de text
);

drop table if exists schools cascade;
CREATE TABLE schools (
    id serial primary key,
    school_label int references labels(id)
);

drop table if exists class_rooms cascade;
CREATE TABLE class_rooms (
    id serial primary key,
    class_label int references labels(id),
    school_id int references schools(id)
);

drop table if exists students cascade;
CREATE TABLE students (
    id serial primary key,
    std_label int references labels(id),
    class_id int references class_rooms(id)
);

INSERT INTO public.labels (en,fr,de) VALUES
	 ('school_1','ecole_1',NULL),
	 ('school_2','ecole_2',NULL),
	 ('class_1','classe_1',NULL),
	 ('class_2','classe_2',NULL),
	 ('class_3','classe_3',NULL),
	 ('std_1','eleve_1',NULL),
	 ('std_2','eleve_2',NULL),
	 ('std_3','eleve_3',NULL),
	 ('std_4','eleve_4',NULL),
	 ('std_5','eleve_5',NULL);
	
INSERT INTO public.schools (school_label) VALUES
	 (1),
	 (2);
	
INSERT INTO public.class_rooms (class_label,school_id) VALUES
	 (3,1),
	 (4,1),
	 (5,2);
	 
INSERT INTO public.students (std_label,class_id) VALUES
	 (6,1),
	 (7,1),
	 (8,2),
	 (9,3),
	 (10,3);	
```

**Comment by LonwoLonwo** [comment]
So now you can see your FK?
Did you try to refresh your table? Your schema? Your database? Or what kind of object and where?

**Comment by RobinFrcd** [comment]
Yes, now I can see it !
I went into the properties tab of my table, and hit refresh, the FK wouldn't pop. Same if I went to the ER diagram.

**Comment by ShadelessFox** [comment]
Hello @RobinFrcd,

I cannot reproduce your issue. The foreign key appears just fine after refreshing the `Foreign Keys` node in the navigator tree.

Can you please provide a minimal reproducible example?

Also, what's your database version?

**Comment by RobinFrcd** [comment]
I was running PSQL 14.2, but I didn't manage to reproduce the issue.
I remember I was messing with the schema from directly from the PSQL cli and the refresh button on DBeaver didn't work correctly. Sadly, I can't provide anything else to reproduce it for now. So I guess we can close the issue :man_shrugging:

**Comment by ShadelessFox** [comment]
I see. Thanks for the feedback.
