### ISSUE TITLE
Can't change database in connection dialog

### ISSUE THREAD

**Issue by OlegKustol** [dbeaver/dbeaver#16163]
Hi Team,

2 days ago I faced with a problem and it still drive me mad. I can't change postgres database name in "choose catalog/schema dialog" window. When I try to change it I can see next window:
![image](https://user-images.githubusercontent.com/103504435/162950104-0aea21e9-cb93-4d77-adef-3bfc963f61e1.png)

**Comment by LonwoLonwo** [comment]
Hello @OlegKustol 

What DBeaver version do you use?
What Postgres server and driver versions do you use?

Also, please provide an [error log](https://github.com/dbeaver/dbeaver/wiki/Log-files). I can't reproduce your issue for now.

**Comment by OlegKustol** [comment]
Dbeaver version is Version 21.2.0.202109061154
JDBC driver  for postgresql version 13
PostgreSQL server: AWS RDS PostgreSQL server version 13.

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/8472520/dbeaver-debug.log)
[ - Copy.log](https://github.com/dbeaver/dbeaver/files/8472522/-.Copy.log)

**Comment by LonwoLonwo** [comment]
I can offer you to update the DBeaver version to check the condition of your issue. We do not create patches for previous versions.

**Comment by OlegKustol** [comment]
Got it. But I updated DBeaver today. I don't know why the version is old. I'll update app and let you know if some issues with change database name are there.

**Comment by LonwoLonwo** [comment]
Ok, thnaks for the answer @OlegKustol

**Comment by OlegKustol** [comment]
I updated DBeaver, but I still have the same issues.
![image](https://user-images.githubusercontent.com/103504435/162967686-ad9f51c5-b0ad-4f8f-b9e3-6b0c668c28b9.png)
![image](https://user-images.githubusercontent.com/103504435/162967731-a8449850-cd27-43d5-90d5-afae4adddbde.png)

**Comment by LonwoLonwo** [comment]
Maybe your log changed?

**Comment by OlegKustol** [comment]
Hello,
please find my logs in attachment. Today I still have this issues.

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/8482564/dbeaver-debug.log)
[ - Copy.log](https://github.com/dbeaver/dbeaver/files/8482567/-.Copy.log)

**Comment by LonwoLonwo** [comment]
Ok. what do you mean about "can't change postgres database name"?

Did you try to select another database in the "choose catalog/schema dialog"? Or something else?

![Mp2stXJIVC](https://user-images.githubusercontent.com/45152336/163226871-ed6ec65a-1955-415d-bb2e-79abf16a97d6.gif)

**Comment by OlegKustol** [comment]
I can't select database in the way you show me)
When I open this windows I have an error and database list is empty

**Comment by OlegKustol** [comment]
Hi,
After 3rd time rebooting PC it works again)

**Comment by LonwoLonwo** [comment]
Oh, great!

As a workaround in the feature, you can change the default database/schema in the database navigator tree.

![2022-04-15 10_48_13-Window](https://user-images.githubusercontent.com/45152336/163548400-d1884775-6f21-45a9-8a94-a68bbb2ed5c1.png)

![2022-04-15 10_47_51-Window](https://user-images.githubusercontent.com/45152336/163548398-35d2e3b2-3552-4d6d-bf93-0291b876c1c7.png)

**Comment by LonwoLonwo** [comment]
The error message for this situation was changed.

![2022-04-15 12_42_27-Window](https://user-images.githubusercontent.com/45152336/163555752-901b59f9-2f7f-439b-bdf8-c9a575642105.png)

**Comment by OlegKustol** [comment]
In general it's not comfortable to change default database, because we should work with multiple database simultaniously

**Comment by Matvey16** [comment]
Verified
