### ISSUE TITLE
Can't Disable Red Highlighting For Query Error In SQL Editor

### ISSUE THREAD

**Issue by jthemenace** [dbeaver/dbeaver#16179]
#### System information: 
- Operating system -- Mac Monterey 12.3.1, running in a Macbook pro 14-inch M1
- DBeaver version -- Version 22.0.2.202204041542
- Additional extensions - DBeaver Office Support

#### Connection specification:
- Database name and version MariaDB 10.5.15
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  SSH

#### Describe the problem you're observing:
After a somewhat recent update, in the built in query editor there is a very extreme dotted red underline under my entire query when an error occurs.   It's making it very difficult to read my query and debug it.   I desperately want to turn off this setting, but cannot figure out any way to turn it off.

See attached screenshot.
<img width="1017" alt="Screen Shot 2022-04-13 at 9 00 15 AM" src="https://user-images.githubusercontent.com/9721406/163187903-223aad66-a05b-44fe-897b-5bcaf421b244.png">

**Comment by E1izabeth** [comment]
Hi, @jthemenace! You can disable error highlighting in Preferences -> Editors -> SQL Editor -> Code Editor ("Show problem markers").
![image](https://user-images.githubusercontent.com/28875055/163197163-ae2aaef1-3e6f-4ddd-89c0-85b189beeb91.png)

**Comment by jthemenace** [comment]
Thank you so much!!!! That's exactly what I needed!!!  Hopefully this post will help someone else in the future (myself included if I forget)
