### ISSUE TITLE
[Feat. Req.] Disable trigger from table detais, trigger list

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#16171]
I found no way to disable a trigger in table details (both selecting a trigger an looking at options downunder, or by right-click) or in trigger detail

**Comment by LonwoLonwo** [comment]
Hello @wiwwo 

What DBeaver version do you use?
What database version do you use?

Are you talking about this kind of operations? https://docs.microsoft.com/en-us/sql/t-sql/statements/disable-trigger-transact-sql?view=sql-server-ver15

**Comment by wiwwo** [comment]
Wow,
sorry :-P

DB: PG 13
DBEaver: Version 21.3.0.202111281534

No way to disable trigger in red sport
![image](https://user-images.githubusercontent.com/3930671/163140165-e793caa4-c01f-4ac0-998d-87086b783926.png)

or, after double click on trigger name in pic above:
![image](https://user-images.githubusercontent.com/3930671/163140431-ee0a5586-89d0-404c-809f-c32ef085395f.png)

**Comment by LonwoLonwo** [comment]
Yeah, this is a little bit tricky:

![2022-04-13 12_03_11-DBeaver Ultimate 22 0 3 - _dvdrental_Script-146](https://user-images.githubusercontent.com/45152336/163140989-9cf90848-fb13-4dca-a847-e62cd834259b.png)
