### ISSUE TITLE
ClickHouse Enum value display issue

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/dbeaver#16178]
#### System information: 
- macOS 12.3.1
- DBeaver Version 22.0.2.202204021640

#### Connection specification:
- ClickHouse 22.3
- clickhouse-jdbc 0.3.2-patch8 (not released yet)
- No tunnels or proxies in between

#### Describe the problem you're observing:

Enum8 / Enum16 is mapped to VARCHAR in JDBC driver, but it seems DBeaver called ResultSet.getObject() instead of getString() to retrieve the value.

![image](https://user-images.githubusercontent.com/4270380/163177974-4d891143-3364-4021-8dad-4374650deaa8.png)

#### Steps to reproduce, if exist:

Issue query `select 'a'::Enum('a'=2,'b'=1) e` using clickhouse-jdbc 0.3.2-patch8 :cry:

#### Include any warning/errors/backtraces from the logs

N/A

**Comment by zhicwu** [comment]
FYI, I had to roll back part of the change to ensure `ResultSet.getObject` will return String instead of number. It would be great if this can be fixed in DBeaver.

**Comment by LonwoLonwo** [comment]
Yes, by default, DBeaver is reading objects, not strings.

We can change this behavior for Enum data types for Clickhouse.
For old drivers too or just for new?

https://github.com/dbeaver/dbeaver/blob/2ca59afe719512741480e1f2fad8cb902fd9dc03/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/jdbc/data/handlers/JDBCStringValueHandler.java#L43-L53

**Comment by zhicwu** [comment]
Thanks @LonwoLonwo, it's only needed for new driver. As long as it's VARCHAR, it should be safe to use getString IMO.

>  because sometimes CHAR/VARCHAR holds something specific. E.g. FOR BIT DATA 

java.sql.Types does have BIT and BINARY, so I guess it was an issue in driver implementation.

**Comment by flambchap** [comment]
We cannot edit any data other than enums anymore :(
