### ISSUE TITLE
Vertica query return updated rows = -1

### ISSUE THREAD

**Issue by MarioGarbelli** [dbeaver/dbeaver#16183]
#### System information: 
- Windows 11 
- DBeaver 22.0.2 CE (last release available)
- Additional extensions: No

#### Connection specification:
- Vertica 9.1.1-6
- vertica-jdbc-9.1.1-0.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
All queries (e.g. SELECT 1;) return "updated rows = -1". 
The same query works smoothly with DBeaver 22.0.1.202203181646 CE.

#### Steps to reproduce, if exist:
SELECT 1;

**Comment by LonwoLonwo** [comment]
Hello @MarioGarbelli 

Maybe it was?:

```sql
SELECT 1
;
```

In this case, we have the same issue: https://github.com/dbeaver/dbeaver/issues/16077

**Comment by MarioGarbelli** [comment]
hi @LonwoLonwo , I've tried dozen of different queries. All of them fail.

SELECT 1; works in current dbeaver 22.0.1.202203181646 CE.

**Comment by LonwoLonwo** [comment]
Ok. For now we will waiting for the next (22.0.3) release. Maybe it helps.

**Comment by LonwoLonwo** [comment]
Please check the "Script delimiter redefiner" connection setting in the "Advanced parameters".
Set it to empty if it's not.
I hope it helps.

![2022-04-15 12_21_54-Window](https://user-images.githubusercontent.com/45152336/163553341-658f1395-9d7a-40a4-bc4f-08724c559e99.png)

**Comment by MarioGarbelli** [comment]
I've changed the  "Script delimiter redefiner" as suggesteed. 
I'm able to run all the test queries with success! Thank you!
