### ISSUE TITLE
Personalized column ordering in Data view

### ISSUE THREAD

**Issue by spassignat** [dbeaver/dbeaver#16181]
Most of the time when viewing table data, some users focus on the same columns and others on other columns. Actually, the columns seem displayed in their database order.

Could it be possible to let user order the columns in that view, the way he wants and save this in a file but not in the data-sources.json ?

Then when re-editing the table data, the user will find the previous layout he used.

**Comment by ShadelessFox** [comment]
Hello @spassignat,

Sorry for the late response.

Filters are saved in a separate file called `saved-data-filter.xml` located in the workspace.

Can you please provide more information about your request? Are you talking about saving filters on a per-account basis?

**Comment by spassignat** [comment]
Hello,

When viewing table data, I would like to change the display order of columns and save this order for the next time I "View Data" on this table.

ex: 
If the TableA is created with these columns in this order (Column1, Column2, Column3, Column4)
When viewing the data, the grid displays columns in the same order. (fine)

Then I wish to change this order to (Column3, Column4, Column2, Column1), because I'm more interested in Column3 and Column4. In some version of dBeaver I can easily do it dragging columns in the grid. (fine)

The next day when I click on View Data on this same table, I wish to view the columns in the same order (Column4, Column3, Column2, Column1).


Sure I can do a select, but View Data is really more convenient when there is no filter (where clause).

**Comment by ShadelessFox** [comment]
So you just want to save filters? This can be achieved by pressing this button:

![image](https://user-images.githubusercontent.com/35821147/165743976-83ee7b72-7401-4205-8726-9aa5265e3741.png)

**Comment by spassignat** [comment]
Ok I got it. That's part of the filter ! 

great Thanks !

**Comment by ShadelessFox** [comment]
You're welcome!

I assume that the issue may be closed now.

**Comment by spassignat** [comment]
Just one more question about that. 

I can save the column ordering, but the custom filters (where clause) is not saved. Is it a expected behavior ?

thanks

**Comment by spassignat** [comment]
my version is 
![image](https://user-images.githubusercontent.com/6451374/165751705-bb2538c9-b280-4e23-907c-cc4dea198bb9.png)

**Comment by E1izabeth** [comment]
@spassignat thank you for noticing. It's a bug and we have already fixed it. Fix will be available in 22.0.4
