### ISSUE TITLE
Feature wish: Option to disable automatic "source" comment on views

### ISSUE THREAD

**Issue by HerrB92** [dbeaver/dbeaver#16188]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows [Version 10.0.19043.1052]
- DBeaver version: Community 22.0.2
- Java version: As provided 
- Additional extensions: None

#### Describe the problem you're observing:
With some of the latest versions of DBeaver a feature was introduced, that the source editor window gets an additional "source" comment line automatically, like:
`-- SCHEMA.VIEW_NAME source`

We would like to be able to disable that, because working on that view duplicates that line over and over (or you have to remove that line manually, again and again).

While it was surely a nice idea, it does not help you much, if the view source looks like that:
```
-- SCHEMA.VIEW_NAME source

-- SCHEMA.VIEW_NAME source

CREATE OR REPLACE VIEW SCHEMA.VIEW_NAME AS 
...
```

#### Steps to reproduce, if exist:
Open "Source" tab of a view.

Thank you!

**Comment by LonwoLonwo** [comment]
Ok, thanks for the report @HerrB92

**Comment by HerrB92** [comment]
Hi everyone! I know, you have more pressing issues to do, but this feature is still there and a "fixing" option to disable it seems to be a little abandoned since 10/2022.

As the function is rather not helpful we would still *love* to see an option to disable the function (so that we do not have to remove the auto-comment over & over again).

Thank you! :-)

**Comment by LonwoLonwo** [comment]
Ok, we can take a look at this ticket. And we can add a special option in Preferences -> Connections -> Metadata page.
