### ISSUE TITLE
Font size too small in script interface

### ISSUE THREAD

**Issue by amisano** [dbeaver/dbeaver#16192]
Hi to all
I need a solution to this problem 
I have a very strange situation on font size on sql script input, because the characters on the screen have reduced in size and become unreadable.
I probably used some buttons or settings by mistake.
I couldn't find any option to set the font size.
Can you help me ?
thank you
Version 22.0.2
eamisano@guala.net

**Comment by ShadelessFox** [comment]
Hello @amisano,

Are you talking about the font size in the SQL Editor?

You can adjust its size using <kbd>Ctrl+-</kbd> and <kbd>Ctrl+=</kbd> keyboard shortcuts.
