### ISSUE TITLE
tooltip list of columns when selecting table

### ISSUE THREAD

**Issue by Lewonna** [dbeaver/dbeaver#16197]
DBeaver version: 22.0.2.202204041542
Database: Postgres

**Is your feature request related to a problem? Please describe.**

I would like to see a list of columns in a table when I typing table name in SQL-query.

for example, as in MS SQL:
![image](https://user-images.githubusercontent.com/43236226/163523708-8e6ffd99-8a3c-487c-b3a6-b1a1bb353087.png)

Is there such an feature already? If so, could you help me find it? If not, could you please add it?

**Comment by ShadelessFox** [comment]
Hello @Lewonna,

Thanks for the feature request.

We will include columns information in the auto-completion popup.

**Comment by Destrolaric** [comment]
### -- Acceptance criteria --
- [ ] Shows new additional information popup when selecting the JDBC table
- [ ] Shows information about columns if the JDBC table is selected
- [ ] Shows keyword information(if supported for database)
- [ ] Shows metadata information about schemas similarly to old dialog.
