### ISSUE TITLE
Improve xlsx files export

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#16205]
The feature added in #15067 allows the user to append exported data to existing file by adding a new sheet into file. We need to add a setting that would allow appending data to the existing sheet instead.
Another improvement is to allow changing default sheet names with templates/variables like we have for file names.

**Comment by maphstay** [comment]
I totally agree with @Matvey16, i was need this today and was searching about until found this request, it's really necessary for improve the new feature "adding new sheet".
