### ISSUE TITLE
Generate UUID command needs to grayed out if it cannot be worked

### ISSUE THREAD

**Issue by PzaThief** [dbeaver/dbeaver#16208]
when nothing in main window, uuid command(ctrl+alt+shift+u) in edit panel is activated looks like it can be used. but if I command it, there are noting action after command. So I think I need to be grayed out when it cannot be worked.

**Comment by LonwoLonwo** [comment]
Ok, thanks for the bug report @PzaThief 

The button is really always active.

![2022-04-18 09_12_59-DBeaver Ultimate 22 0 3 - Album](https://user-images.githubusercontent.com/45152336/163763861-96685e0b-c394-4e9e-be69-07c1d9e6930c.png)
