### ISSUE TITLE
22.0.3 asks to "accept" an OSS license

### ISSUE THREAD

**Issue by Foorack** [dbeaver/dbeaver#16217]
Latest version (22.0.3) introduces an EULA confirmation dialog via https://github.com/dbeaver/dbeaver/pull/16063 and https://github.com/dbeaver/dbeaver/pull/16160. @serge-rider @Destrolaric 

OSS licenses are **not** EULA's. Under no circumstance does the user have to "accept" an OSS license. By declaring a license you state under what permission your work is being released under. This is never something someone else has to "accept" nor can "decline". The license states under what conditions must be followed if the source code is used in other pieces of software. "Accepting" an OSS license has no legal basis whatsoever, and "declining" also has no impact, the terms still apply and it would be illegal to include that piece of code without following the conditions and requirements stipulated in the license.

By introducing these meaningless dialogs it sets a dangerous precedent that OSS needs "consent" and that it can be withdrawn or declined. Additionally it is also a severe embarrassment the software! Therefore please immediately revert these PR's introducing this mandatory popup. Licensing information should be available under the Help menu, never an obligatory question where answering "No" kills the software.

---

From EULA page on WP: [link](https://en.wikipedia.org/wiki/End-user_license_agreement#Comparison_with_free_software_licenses) (emphasis mine)

> Unlike EULAs, free software licenses **do not** work as contractual extensions to existing legislation. **No agreement** between parties is ever held, because a copyright license is simply a **declaration** of permissions on something that otherwise would be disallowed by default under copyright law.

From `gnu.org` on license enforcement: [link](https://web.archive.org/web/20130426151337/http://www.gnu.org/philosophy/enforcing-gpl.html) (emphasis mine)

>  But it is sometimes said that the GPL can't be enforced because users haven't “accepted” it.
> 
> This claim is based on a misunderstanding. **The license does not require anyone to accept it** in order to acquire, install, use, inspect, or even experimentally modify GPL'd software. All of those activities are either forbidden or controlled by proprietary software firms, so they require you to accept a license, including contractual provisions outside the reach of copyright, before you can use their works. The free software movement thinks all those activities are rights, which all users ought to have; we don't even want to cover those activities by license. Almost everyone who uses GPL'd software from day to day needs no license, and accepts none. The GPL only obliges you if you distribute software made from GPL'd code, and only needs to be accepted when redistribution occurs. And because no one can ever redistribute without a license, we can safely presume that anyone redistributing GPL'd software intended to accept the GPL. After all, the GPL requires each copy of covered software to include the license text, so everyone is fully informed.

---

### DBeaver Screenshot:
![bild](https://user-images.githubusercontent.com/5008081/163803271-64026990-4969-44f1-880b-73c424890502.png)

**Comment by serge-rider** [comment]
Agreed. We will remove EULA from OSS product.
