### ISSUE TITLE
General network proxy settings are reset after the application is updated

### ISSUE THREAD

**Issue by dvalchev** [dbeaver/dbeaver#16215]
#### System information: 
- Operating system (distribution) and version - **Windows 10 21H2**
- DBeaver version - **22.0.3 but persists in earlier versions as well**
- Additional extensions - **N/A**

#### Connection specification:
- Database name and version - **N/A**
- Driver name - **N/A**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **Yes**

#### Describe the problem you're observing:
Proxy server settings (HTTP/HTTPS) configured in the Network Connection General application preferences are removed when DBeaver is updated to a newer version.

#### Steps to reproduce, if exist:
1. Configure HTTP/HTTPS proxy server in application preferences General->Network Connections. Set the Active Provider to Manual   
![image](https://user-images.githubusercontent.com/30269223/163792123-81027a7f-8c06-4d90-a750-9ad2e970735d.png)

3. Update DBeaver to a newer version from within the application
4. After installation is complete, the proxy settings are reset to default: Active Provider set to Direct and proxy entries - removed
![image](https://user-images.githubusercontent.com/30269223/163793155-b010ffa8-dbc2-4e96-9f98-2e2c7ff75cc9.png)

**Comment by ShadelessFox** [comment]
Hello @dvalchev,

Thanks for the bug report.

**Comment by E1izabeth** [comment]
Eclipse stores this settings in the DBeaver installation folder: `/configuration/.settings/org.eclipse.core.net.prefs`. Currently we override these files on update. This issue will be resolved along with #5317

**Comment by E1izabeth** [comment]
We need to fix our installer to not delete configuration directory on Windows.

**Comment by Matvey16** [comment]
The fix will work only for DBeaver installed for single user. Installation for all users works slightly different by eclipse's design, so it will still reset those settings.
As a workaround the settings file `org.eclipse.core.net.prefs` can be copied from `C:\Users\username\.eclipse\org.jkiss.dbeaver.product_last.used.version_xxxxxxxx_win32_win32_x86_64\configuration\.settings` to `C:\Users\username\.eclipse\org.jkiss.dbeaver.product_new.updated.version_xxxxxxxx_win32_win32_x86_64\configuration\.settings`
