### ISSUE TITLE
displayed wrong content when connected to oracle

### ISSUE THREAD

**Issue by anhdbbt** [dbeaver/dbeaver#16210]
#### System information: 
client system：manjaro linux 
kernel： 5.15.32-1-MANJARO
dbeaver verion：22.0.2.202204041542

#### Connection specification:
- Database name and version：Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
- Driver name ：ojdbc8-19,3.0.0.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)?：No

#### Describe the problem you're observing:
like this, the schem name was wrong, and the table or view in the schema displayed none
![image](https://user-images.githubusercontent.com/13217339/163749677-e757a5b4-e13b-452a-ad83-8c5705201cea.png)

ps: the database worked well, i can connect it with my navicat easily.

**Comment by LonwoLonwo** [comment]
Hello @anhdbbt 

It can be the driver issue.

Can you please try this solution: https://github.com/dbeaver/dbeaver/issues/15144#issuecomment-1011636822 ?

**Comment by anhdbbt** [comment]
thanks, it works!

**Comment by LonwoLonwo** [comment]
Thanks for the answer @anhdbbt
