### ISSUE TITLE
Exported SQL INSERT statement isn't proper if a table has JSONB column in it

### ISSUE THREAD

**Issue by urosctd** [dbeaver/dbeaver#16214]
#### System information: 
- Operating system (distribution) and version : Mac Monterey 12.2.1
- DBeaver version: 22.0.2

#### Describe the problem you're observing:
- When exporting table (as SQL INSERT statement) which has JSONB type columns in it, I get an invalid SQL INSERT statement.
- When exporting data into INSERT statement that statement ought to be without errors...

#### Steps to reproduce, if exist:
`CREATE TABLE try_table (json_arr JSONB[] null)`
`INSERT INTO try_table (json_arr) VALUES (ARRAY['{"foo":1}','{"bar":2}']::json[])`
export the data from try_table as SQL INSERT statement which looks like
`INSERT INTO try_table (json_arr) VALUES ('{{"foo": 1},{"bar": 2}}');`
run that query, and you will get:
`SQL Error [22P02]: ERROR: malformed array literal: "{{"foo": 1},{"bar": 2}}"
  Detail: Unexpected array element.`

#### Connection specification:
- Postgres 14 (doesn't work for 11 either)

**Comment by LonwoLonwo** [comment]
Hello @urosctd 

What database do you use?

**Comment by urosctd** [comment]
> Hello @urosctd
> 
> What database do you use?

Postgres 11 and 14
Sorry I didn't put that in the issue. Updating now

**Comment by LonwoLonwo** [comment]
Ok, thanks for the report @urosctd

**Comment by LonwoLonwo** [comment]
Can't reproduce against in DBeaver 22.2.5

![2022-11-21 12_21_51-DBeaver Enterprise 22 2 5 - _postgres_ Script-34](https://user-images.githubusercontent.com/45152336/203013176-1daa9490-c339-44db-bcef-cff688354285.png)

**Comment by uslss** [comment]
Also cannot reproduce in 22.2.5
