### ISSUE TITLE
[Vertica] Can't execute a query if semicolon is on a new line

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#16212]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 22.0.3

#### Steps to reproduce, if exist:
1. Open SQL Editor
2. Input a query with a semicolon on the next line
3. Try to execute a query

**Expected:** Query is executed 
**Actual:** Query is ignored

![dbeaver_yc3Itj1kIv](https://user-images.githubusercontent.com/82543000/163770639-330732f9-d726-4ba6-868f-fedf45ab1925.gif)

**Comment by nicchristeller** [comment]
Seeing this issue too for queries against Snowflake, but not when using Postgres. 

I think this started in 22.0.1 or 22.0.2 - can try older version to verify if needed.

**Comment by Matvey16** [comment]
Verified
