### ISSUE TITLE
Foreign Keys are also showing under Keys section.

### ISSUE THREAD

**Issue by gncoke** [dbeaver/dbeaver#16226]
#### System information: 
- Operating system (distribution) and version -- Windows-10 Pro - 19044.1586
- DBeaver version - Version 22.0.3.202204170718
- Additional extensions

#### Connection specification:
- Database name and version  - DB2 / AS400
- Driver name  - DB2 iSeries/AS 400
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
The latest update shows table Foreign Keys ALSO under the "Keys" section as Primary Keys.   The Foreign Keys are showing up first in the list of key, and this is causing erroneous SQL to be generated, and executed, when making table updates from a query-result Grid.

#### Steps to reproduce, if exist:
Create a DB2 table with a Key, and a Foreign Key.     Update a record from a result-set Grid view.   Review the SQL that is generated via the "Script" button at the bottom of the screen.   The 'Where' clause is using the Foreign-Key, instead of the Primary Key.

#### Include any warning/errors/backtraces from the logs

![Screenshot_1](https://user-images.githubusercontent.com/103947291/163831256-90822146-1607-4784-9844-b5a5f5891456.png)

![Screenshot_2](https://user-images.githubusercontent.com/103947291/163831292-55695160-83fd-47aa-bd13-f1cd1021a482.png)

**Comment by LonwoLonwo** [comment]
Yeah, incorrect query. Thanks for the bug report!

**Comment by Matvey16** [comment]
Verified
