### ISSUE TITLE
Export SQL without DB Prefix

### ISSUE THREAD

**Issue by mvenghaus** [dbeaver/dbeaver#16239]
Hello,

is there a possibility to export sql without db prefix?

Regards
Marcus

**Comment by LonwoLonwo** [comment]
Hello @mvenghaus 
If I understood you right, you need to enable this data transfer setting:

![2022-04-19 15_36_56-DBeaver Ultimate 22 0 3 - actor](https://user-images.githubusercontent.com/45152336/164005896-66972f24-1291-4acb-b274-77f572a11fde.png)
