### ISSUE TITLE
"Datasource was invalidated" causes zombie connections in Postgres when trying to reconnect after VPN reconnection

### ISSUE THREAD

**Issue by CraigMusser** [dbeaver/dbeaver#16230]
#### System information: 
- OS: 
  -   Edition	Windows 10 Enterprise
  -   Version	21H2
  -   Installed on	‎8/‎4/‎2021
  -   OS build	19044.1645
  -   Experience	Windows Feature Experience Pack 120.2212.4170.0
- DBeaver Version 22.0.0.202203131528 (Enterprise)

#### Connection specification:
- Connecting to a Postgres database: PostgreSQL 13.3 on x86_64-suse-linux-gnu, compiled by gcc (SUSE Linux) 7.5.0, 64-bit
- Database Driver: PostgreSQL JDBC Driver
- Using a corporate VPN. No proxies.

#### Describe the problem you're observing:
I've had this issue happen several times. 

I'll be connected to a Postgres database - multiple connections over several tabs. Something happens where I lose connection to my org's VPN. After re-establishing the VPN connection, Beaver tries to re-connect. But the reconnections fail with the dreaded "Datasource was invalidated". I would be fine with that, but it seems to keep re-trying to connect with the same result. Eventually, it ends up using my database user's connection allotment.  My dev user is capped at 30 connections. If I attempt to open a new script window and connect via that user, I get a "too many connections for role '<username>'" type error
![image](https://user-images.githubusercontent.com/20080148/163876401-34542c89-68dd-467a-b033-4f9372dd0a5b.png)

If I connect via another user to the same DB and query pg_stat_activity , I can see all of the dead connections. 
![image](https://user-images.githubusercontent.com/20080148/163876539-5775b619-05c3-45b2-9789-0ef35ad86b60.png)
Notice how there are more than one connection for the same scripts and all of the "query" values are "<insufficient privilege>".

What I don't understand is why a new connection is created but not deleted when it fails.

#### Steps to reproduce, if exist:
I will try to obtain more detailed steps to reproduce. But, the process is described above.

#### Include any warning/errors/backtraces from the logs
I will be obtaining logs when trying to reproduce this.

**Comment by Destrolaric** [comment]
This looks similar to the issue described in [12559](https://github.com/dbeaver/dbeaver/issues/12559)

**Comment by arhayka** [comment]
I'm closing this ticket as a duplicate: [12559](https://github.com/dbeaver/dbeaver/issues/12559)
