### ISSUE TITLE
Pre-select the correct SSH tunnel profile when entering the edit window

### ISSUE THREAD

**Issue by foobar13372** [dbeaver/dbeaver#16238]
Have at least two SSH profiles.
Have a connection using a profile that is not listed as the first one.
Click the "edit" button on profile selection in a Database connection setting window.

Expected (would be nice to have): the profile to be edited gets also pre-selected in the profile edit window.
Actual bahviour: the first profile in the list is selected.

(It happened to me that I changed the wrong profile because I wasn't aware that not the profile was pre-selected for which I opened the profile edit window)

**Comment by ShadelessFox** [comment]
Hello @foobar13372,

Thanks for the feature request. Such small details are always cool 🙂

**Comment by ShadelessFox** [comment]
Additionally, I'd like to propose adding ability to reorder configurations and create copies of existing ones.
