### ISSUE TITLE
Can't insert/update boolean data.

### ISSUE THREAD

**Issue by hunsakerbn** [dbeaver/dbeaver#1624]
In PostgreSQL, given the following table:
create table btest (
  id integer not null,
  bflag boolean
);

I should be able to insert a new row with the bflag column set to either null, true or false.
However a new row value defaults to false, but null in inserted.  Selecting true still inserts a null.
When trying to modify the column after insert DBeaver thinks nothing has modified, as the 'save' buttom remains greyed out, unless I also modify the 'id' column.  Howver, the boolean column is still unmodified after the save and remains null.  If I try to modify an existing row that has  either a true or false value already set, Again, the save button remains greyed out and I cannot save the change. Also there is no way to select null as an option to replace the exiting value.

This is in DBeaver enterprise Version 4.0.5 on MacOS Sierra.

**Comment by serge-rider** [comment]
Probably this is some MacOS specific issue. Can't yet reproduce that.

To set any column value to null: right click->Set to NULL

**Comment by hunsakerbn** [comment]
On 02 May 17 11 46, Serge Rider wrote:
> Probably this is some MacOS specific issue. Can't yet reproduce that.
> To set any column value to null: right click->Set to NULL

Thanks for the right-click hint.  I can set the boolean value by
selecting 'edit cell' from the menu, but that is the only way I can get it
to work.  Set to Null from the menu also works as you described.


-- 
Bruce Hunsaker

**Comment by serge-rider** [comment]
You can also try to use panel editor (press F7 or click on panels->Value viewer in results toolbar)

**Comment by hunsakerbn** [comment]
Yes. The panel editor works.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.

**Comment by ZhengshuaiPENG** [comment]
I can confirm the same situation.
MacOS 10.12 with dbeaver 4.0.5, Postgresql

I can modify the bool value by right click "edit cell" or in Value viewer, but I can not edit it(a dropbox with true or false to choose) directly in tab panels.

**Comment by tati-kru** [comment]
thank you @ZhengshuaiPENG. Reopen.

**Comment by frutality** [comment]
On Ubuntu 16.04, DBeaver 5.1.0, same problem.

When I enter "edit mode" in cell, cell becomes "disabled". This happens only with boolean columns as I can see.

**Comment by vstruhar** [comment]
Same problem, can't edit boolean columns.

MacOS 10.13.5
DBeaver 5.1.0

![dbeaver 5 1 0 - users 2018-06-20 09-00-03](https://user-images.githubusercontent.com/6599021/41642424-94611056-7468-11e8-8438-f81bf20b2535.jpg)

**Comment by ufon** [comment]
same situation +1

**Comment by Dzenly** [comment]
The same problem. But I can not edit it even by Edit -> Edit cell.
I had to write sql script %)
Version is also read only in "about" menu %) so can not just copy/paste it. The newest version though.

**Comment by serge-rider** [comment]
@Dzenly is this problem happens only with boolean columns? Or whole data is read only?

**Comment by Dzenly** [comment]
@serge-rider I only tested on text and boolean values. Text can be changed, - boolean - can not.

**Comment by VasLem** [comment]
I do not know if my problem is of the same nature as yours, but, using dbeaver 5.3.5 and Ubuntu 16.04, I cannot change a boolean value by double clicking on it, I get a gray box instead and dbeaver hangs, I am forced thereafter to force close the program. This is what I get:
![image](https://user-images.githubusercontent.com/18720200/53232035-e6fd5d00-3692-11e9-91f4-7191f0f97b73.png)

**Comment by fjlozanoacosta** [comment]
Happens to me also.

Windows 10 Pro x64
DBeaver 5.3.5

**Comment by uslss** [comment]
Value couldn't be changed inline. Also rather strange view of dropdown on Edit cell pop-up
![Kazam_screencast_00000 (2)](https://user-images.githubusercontent.com/31996417/55280767-d055c000-533a-11e9-839d-a5adde8d21b0.gif)

**Comment by uslss** [comment]
Verified.
Note: Dropdown list still works incorrectly on Grid view on Ubuntu 18.04.2. Probably, system issue.

**Comment by a-salimkhanov** [comment]
DBeaver 22.1,2 on Linux Mint (Ubuntu).
Still the same issue
![image](https://user-images.githubusercontent.com/61108267/180130189-d72659eb-0575-4c32-b6aa-8ad191739b4c.png)

**Comment by dbuhonov** [comment]
The problem is still relevant...

UPD: https://github.com/dbeaver/dbeaver/issues/21277#issuecomment-1729670359

**Comment by etniqa** [comment]
I've just reopened DBeaver and it works now !

**Comment by viveknimbolkar** [comment]
Thank you, @etniqa, for your help! It took me a whole hour to troubleshoot that issue, but your support made all the difference.

**Comment by shleecloud** [comment]
I had same issue but I solved!
1. cell right click -> View/Format -> set "column name" transform -> Boolean click 
2. restart dbeaver app
3. click checkbox for edit 
4. save! 

from version 24.3.0.202412011650
