### ISSUE TITLE
UI not displaying databases even though they are connected 

### ISSUE THREAD

**Issue by MMillett123** [dbeaver/dbeaver#16248]
#### System information: 
- Operating system (distribution) and version DELL Inc. Latitude 5420
- DBeaver version - 7.3.3
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

I installed it on my computer but there are no databases showing up after I have connected-  although they are definitely connected. 

The configuration is the same as my colleagues, also there is no filter applied - Please Help!! it has been 5 weeks of installing and uninstalling. 

Please help!!!

**Comment by ShadelessFox** [comment]
Hello @MMillett123,

Could you please send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.

Thank you.

**Comment by ShadelessFox** [comment]
I just noticed that your DBeaver version is quite old.

Could you please download the latest version instead and see if the issue is gone there? https://dbeaver.io/download/

**Comment by MMillett123** [comment]
Hi there - thanks for your help!!
I unfortunately can't upload my Log file becuase it has source code, but I can send one small part. 

"The project description file (.project) for 'General' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored." 

It says this - along with a lot more but they look like script, this is the error message at the top. Is this a helpful clue?

**Comment by ShadelessFox** [comment]
It's a clue, but we need to see the whole picture.

I believe what you refer to as "source code" is a stack trace. Since you are, presumably, using the community edition of DBeaver, it's free and open-source, you can browse its source code right here, on GitHub, by opening the `Code` tab.

So don't worry about sharing any sensitive data - debug logs don't contain such.
