### ISSUE TITLE
ERROR: relation "pg_temp.session_vars" does not exist

### ISSUE THREAD

**Issue by eric-g-97477** [dbeaver/dbeaver#16245]
I am using Version 22.0.2.202204041542

I can successfully connect to a PostgreSQL database, view the tables and the data they contain, and execute queries against the database. 

However, when I try to execute an UPDATE, I get the following error:
```
SQL Error [42P01]: ERROR: relation "pg_temp.session_vars" does not exist
  Where: SQL function "get_current_user" during inlining
SQL statement "SELECT get_current_user()"
PL/pgSQL function update_lastmodified() line 60 at assignment
```
I believe this is related to issues:

https://github.com/dbeaver/dbeaver/issues/2845
https://github.com/dbeaver/dbeaver/issues/1330

but neither of them have definitive solutions. 

One of the suggestions found there was:

```
On connection properties page "General" turn on "Show utility objects" checkbox. 
```

However, I am having difficulty locating where that option is, assuming it would help resolve this problem.

I was wondering what, if anything, I might be able to do to resolve this issue.

(I can connect to the database directly via the shell and issue UPDATE's without any problems.)

**Comment by LonwoLonwo** [comment]
Can you please tell me more about your PG database and driver? Versions in the first place.

Also, you can find "Show utility objects" checkbox in your connection settings:

![2022-04-20 11_03_28-DBeaver Ultimate 22 0 3 - reason](https://user-images.githubusercontent.com/45152336/164181254-5ae578d3-4b47-4d12-9d9e-29f21bd59aec.png)

**Comment by eric-g-97477** [comment]
Trying to track down the driver information.

```
=> SHOW server_version;
 server_version
----------------
 13.6
```

**Comment by eric-g-97477** [comment]
I believe this is the driver information you are looking for.

![image](https://user-images.githubusercontent.com/98830008/164240257-b74eb45d-386c-4528-aea8-949bbae09c33.png)

**Comment by LonwoLonwo** [comment]
Ok. Is your update connected to any temp tables? 

Did enabling of "Show utility objects" help?

**Comment by eric-g-97477** [comment]
No, "Show Utility Objects" didn't help.

My UPDATE is just something like:

`UPDATE the_table SET a_column = 'Dramatic' WHERE another_column = '42d'`

My current line of thought is that this is outside the scope of DBeaver and had more to do with how the Postgres DB is configured...

**Comment by LonwoLonwo** [comment]
Can you try to disable this setting? Preferences ->Editors -> SQL Editor -> SQL Processing -> "Refresh active schema after SQL execution"

This setting works with the "SHOW search_path" statement, which can trigger your error.

![2022-04-27 23_33_56-Preferences](https://user-images.githubusercontent.com/45152336/165626737-3dcdb6af-d239-4b16-8504-6bbb769df4b4.png)

**Comment by eric-g-97477** [comment]
The behavior remains unchanged. I still get the error.

I believe it is a combination of how the Postgres server is configured and either not understanding how or being unable to configure DBeaver to avoid the error.

**Comment by LonwoLonwo** [comment]
Maybe you have some UPDATE trigger in your database? Event trigger or table trigger.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual - feel free to reopen it with additional info
