### ISSUE TITLE
Enable multi-row value insert for Trino JDBC connector

### ISSUE THREAD

**Issue by echan888** [dbeaver/dbeaver#16246]
Import Data from CSV is slow and is performed as multiple single row insert statements.

The need for multi-row value value insert is addressed in [https://github.com/dbeaver/dbeaver/issues/11425](url) but the fix enables the feature only for

- PostgreSQL
- Redshift
- Greenplum
- Cockroach
- MySQL/MariaDB
- SQLServer
- SQLite
- DB2
- Exasol

Please add multi-row value insert for Trino JDBC connector as well.

**Comment by LonwoLonwo** [comment]
Can you please specify what Trino connector you use?

**Comment by LonwoLonwo** [comment]
And ok, I see that multi-insert is supported by Trino: https://trino.io/docs/current/sql/values.html

**Comment by echan888** [comment]
> Can you please specify what Trino connector you use?

Hello @LonwoLonwo, I use the one with the cute bunny. Thank you.

![image](https://user-images.githubusercontent.com/83606824/164267836-9b23791f-db72-407c-9c9d-f1d0d5f0e850.png)

**Comment by LonwoLonwo** [comment]
Thanks for the answer @echan888

**Comment by echan888** [comment]
Hello @LonwoLonwo,

I also noticed that during Import Data from CSV, the SQL insert statements generated are missing the quotes. So for example:

Here's what the CSV file looks like:

"dx_id","dx_name"
"1201","TYPHOID FEVER"
"1202","SALMONELLA GASTROENTERITIS"

Here's the target table definition:
CREATE TABLE catalog_name.schema_name.table_name
(
  dx_id VARCHAR,
  dx_name VARCHAR
)...

During Import Data, the SQL issued to Trino looks like this:

INSERT INTO catalog_name.schema_name.table_name (dx_id,dx_name)
	VALUES (1201,TYPHOID FEVER)

The quotes around the string are missing resulting in the following DBeaver error:

SQL Error [1]: Query failed (#20220420_160419_00351_z3iaz): line 2:23: mismatched input 'FEVER'. Expecting: ')', ','

Thank you.

**Comment by LonwoLonwo** [comment]
What DBeaver version do you use?

Can you provide a screen of your table with columns in DBeaver?

**Comment by echan888** [comment]
> What DBeaver version do you use?
 
![image](https://user-images.githubusercontent.com/83606824/164292727-a96127e6-a3b4-4174-a43c-0226a3eb40ae.png)


> Can you provide a screen of your table with columns in DBeaver?
Here's the target table @LonwoLonwo 

![image](https://user-images.githubusercontent.com/83606824/164293866-ef00bf88-fe55-4c62-849d-e07f8ce1b301.png)

**Comment by echan888** [comment]
Hello @LonwoLonwo,

Here's some additional information. If the target table column is defined with a length, e.g. VARCHAR(100), instead of just VARCHAR, the Import Data works correctly and includes the quotes in the INSERT statement.

Here's the INSERT statement generated by DBeaver:

 INSERT INTO catalog_name.schema_name.table_name (dx_id,dx_name)
	VALUES ('1201','TYPHOID FEVER')

Here's the target table definition with length specified for the character columns:

![image](https://user-images.githubusercontent.com/83606824/164306531-d2aceee4-2c74-4736-923c-0ba94ab8f388.png)

Thank you.

**Comment by LonwoLonwo** [comment]
![2022-04-21 00_07_23-(1) Enable multi-row value insert for Trino JDBC connector · Issue #16246 · dbea](https://user-images.githubusercontent.com/45152336/164324294-35a6bb43-7b31-44b8-807c-54644f3ea11e.png)

Yes, the question mark means that the datatype didn't recognize.

**Comment by LonwoLonwo** [comment]
Milti-insert added for these databases in DBeaver 21.1.1:

- Trino
- Vertica, 
- H2, 
- Derby, 
- Databricks and 
- DB2i
- Snowflake

![2022-06-07 15_49_21-DBeaver Ultimate 22 1 0 - _postgres_ Script-34](https://user-images.githubusercontent.com/45152336/172383658-4eb99e56-3401-4080-a67e-071baacdf535.png)

**Comment by echan888** [comment]
Awesome. Thank you @LonwoLonwo, et al.

**Comment by echan888** [comment]
hello @LonwoLonwo,

I tested out the multi-row value insert for the Trino database connector and it works if I set the value to a small number like 140. Setting it to larger values would result in the following error. Is there a setting that would allow me to specify higher values for better performance?

SQL Error: Error executing query
  Error executing query
  Error executing query
    Error fetching next at https://trinocoordinator.azure.xx.org/v1/statement/executing/20220706_142947_00395_s47eb/yfb17438d9aac83542584e6ce13e1d696dadaa043/0 returned an invalid response: JsonResponse{statusCode=502, statusMessage=Bad Gateway, headers={connection=[keep-alive], content-length=[122], content-type=[text/html], date=[Wed, 06 Jul 2022 14:29:47 GMT]}, hasValue=false} [Error: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
]
    Error fetching next at https://trinocoordinator.azure.xx.org/v1/statement/executing/20220706_142947_00395_s47eb/yfb17438d9aac83542584e6ce13e1d696dadaa043/0 returned an invalid response: JsonResponse{statusCode=502, statusMessage=Bad Gateway, headers={connection=[keep-alive], content-length=[122], content-type=[text/html], date=[Wed, 06 Jul 2022 14:29:47 GMT]}, hasValue=false} [Error: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
]

**Comment by LonwoLonwo** [comment]
Seems to be some Trino restriction here. I can't help here, unfortunately.

But thanks for testing!
