### ISSUE TITLE
DBeaver Mac Connection Settings Does Not Show SSH Tab

### ISSUE THREAD

**Issue by Kunthera** [dbeaver/dbeaver#16257]
#### System information: 
- Operating system (distribution) and version:  MacOS Monterey 12.3.1 (21E258)
- DBeaver version: 22.0.3.202204170718
- Additional extensions

#### Connection specification:
- Database name and version: Postgres 14
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  SSH with private key file

#### Describe the problem you're observing:
On creation of connection, SSH tab is there for setup. But once saved, there is no way to modify the SSH settings as the tab no longer shows in the Connection Settings. Only Main/PostgreSQL/Driver Properties are available.

#### Steps to reproduce, if exist:
Just try to edit any Postgres connection.

**Comment by ShadelessFox** [comment]
Hello @Kunthera,

Does resizing the connection dialog help?

Could you please send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual - feel free to reopen it with additional info
