### ISSUE TITLE
Support displaying sequences for CockroachDB

### ISSUE THREAD

**Issue by jhatcher9999** [dbeaver/dbeaver#16255]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When you use DBeaver to connect to CockroachDB, you can see the tables, views, etc. in the "explorer" view, but you don't see a list of sequences.  I'd love to be able to interact with CockroachDB sequences in the same way that I can interact with tables, etc.

**Describe alternatives you've considered**
You can get a list of sequences using the query window to query CockroachDB system tables.

**Additional context**
I've tested this on DBeaver Community Version 22.0.3.202204170718 and CockroachDB v21.2.9

**Comment by LonwoLonwo** [comment]
Thanks for the idea @jhatcher9999
