### ISSUE TITLE
m1 max   cannot see new fields

### ISSUE THREAD

**Issue by liuzhe101** [dbeaver/dbeaver#16251]
#### System information:   12.3.1
- Operating system (distribution) and version
- DBeaver version。22
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Include any warning/errors/backtraces from the logs

m1 max runs dbeaver 22. When I add a new field, I use Command+left mouse button to view the table fields, but the newly added field is not displayed. I need to exit qpp every time, and use Command+left mouse button to open it again to see it. The newly added fields can be seen immediately after I have used the PL/SQL tool.

**Comment by ShadelessFox** [comment]
Hello @liuzhe101,

Can you please record a video showing the issue?

Thank you.

**Comment by liuzhe101** [comment]
ok, thanks you for your reply ,  this is the recorded video

https://user-images.githubusercontent.com/61652514/164256274-1c6ffb44-220f-40a9-89f0-acbcd5648dd8.mp4

**Comment by liuzhe101** [comment]
> 你好@liuzhe101,
> 
> 你能录制一段视频来显示这个问题吗？
> 
> 谢谢你。

please,watch

**Comment by ShadelessFox** [comment]
DBeaver cannot detect metadata modifications via DDL.

You need to manually refresh the metadata editor to see any changes made in the SQL editor.

**Comment by liuzhe101** [comment]
> DBeaver cannot detect metadata modifications via DDL.
> 
> You need to manually refresh the metadata editor to see any changes made in the SQL editor.

esides closing the app, how should I refresh，How to do it? I think this aspect can be optimized. I have used PL/SQL developer before and can do this without refreshing.

**Comment by ShadelessFox** [comment]
You can refresh the editor by right-clicking in it and selecting `Refresh` action:

![image](https://user-images.githubusercontent.com/35821147/164266295-9c34ebc9-b4ab-4a6e-b989-c88cd0ccdf4c.png)

PL/SQL Developer, by design, only supports Oracle database. DBeaver is a universal tool, so it may lack some specific features.

**Comment by liuzhe101** [comment]
> 

Thank you very much, this may be the current solution, whether it can be refreshed when Command+click is completed after executing DDL, which will make the experience better

**Comment by liuzhe101** [comment]
Thanks

**Comment by liuzhe101** [comment]
> You can refresh the editor by right-clicking in it and selecting `Refresh` action:
> 
> ![image](https://user-images.githubusercontent.com/35821147/164266295-9c34ebc9-b4ab-4a6e-b989-c88cd0ccdf4c.png)
> 
> PL/SQL Developer, by design, only supports Oracle database. DBeaver is a universal tool, so it may lack some specific features.

When I add a new table, click to report an error, how can I refresh it, reconnecting the database will not work, and refreshing will not work, I need to close dbeaver22 and open it again

**Comment by ShadelessFox** [comment]
To refresh tables, you need to refresh the scheme or any top-level using the same shortcut or context menu action:

![image](https://user-images.githubusercontent.com/35821147/164373060-29b9eab1-00e7-42eb-a115-cb190c6202f6.png)
