### ISSUE TITLE
Eclipse Dbeaver plug-in and SAP Hana development plug-in right click conflict

### ISSUE THREAD

**Issue by usoa** [dbeaver/dbeaver#16262]
**Eclipse Platform**
Version: 2021-12 (4.22)
Build id: I20211124-1800

**SAP Development Tools for Eclipse 2021-12**
SAP Development Tools for Eclipse 2021-12 - https://tools.hana.ondemand.com/2021-12

**DBeaver CE Repository 22.0.3.202204170718**
DBeaver CE Repository - https://dbeaver.io/update/latest/

When I install Dbeaver plug-in and SAP Hana development plug-in in the Eclipse platform at the same time, all right-click menus in the dbaver database navigation window cannot pop up. After uninstalling plug-in B, the fault is eliminated

**Comment by E1izabeth** [comment]
Hi, @usoa! Unfortunately, I can't reproduce your issue. How did you install these plugins: with Install new software.. or from Eclipse marketplace? Did you install DBeaver or SAP Hana plugin first?

**Comment by qilinsanshao** [comment]
Hi:
I face the same issue, after I installed SAP HANA plugin,all right-click menus in the dbaver database navigation window cannot pop up.

**Comment by serge-rider** [comment]
Please attach the error log (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by uslss** [comment]
The issue is also reproducible in case of Hana plugin installation on standalone dbeaver
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/9112024/dbeaver-debug.log)

**Comment by uslss** [comment]
@usoa unfortunately, cannot reproduce you issue for now. Could you check if it is reproducible for you against the new dbeaver version?

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
