### ISSUE TITLE
Results missing on search query

### ISSUE THREAD

**Issue by dancodedev** [dbeaver/dbeaver#16266]
#### System information: 
- Operating system: **windows 11**
- DBeaver version: **22.03**

#### Connection specification:
- Database name: **laravel_performance mysql 5.7.33**
- Driver name: ** I don´t know**

#### Describe the problem you're observing:

**Table Structure**
```
CREATE TABLE `performance_data` (
  `marca` varchar(100) DEFAULT NULL,
  `marca_slug` varchar(100) DEFAULT NULL,
  `modelo` varchar(100) DEFAULT NULL,
  `modelo_slug` varchar(100) DEFAULT NULL,
  `year` varchar(100) DEFAULT NULL,
  `year_slug` varchar(100) DEFAULT NULL,
  `motor_tipo` varchar(100) DEFAULT NULL,
  `motor_tipo_slug` varchar(100) DEFAULT NULL,
  `motor` varchar(100) DEFAULT NULL,
  `motor_slug` varchar(100) DEFAULT NULL,
  `stage` varchar(100) DEFAULT NULL,
  `stage_slug` varchar(100) DEFAULT NULL,
  `stage_price` varchar(100) DEFAULT NULL,
  `stage_price_slug` varchar(100) DEFAULT NULL,
  `original_potencia` varchar(100) DEFAULT NULL,
  `original_potencia_slug` varchar(100) DEFAULT NULL,
  `modificado_potencia` varchar(100) DEFAULT NULL,
  `modificado_potencia_slug` varchar(100) DEFAULT NULL,
  `diferencia_potencia` varchar(100) DEFAULT NULL,
  `diferencia_potencia_slug` varchar(100) DEFAULT NULL,
  `original_par` varchar(100) DEFAULT NULL,
  `original_par_slug` varchar(100) DEFAULT NULL,
  `modificado_par` varchar(100) DEFAULT NULL,
  `modificado_par_slug` varchar(100) DEFAULT NULL,
  `diferencia_par` varchar(100) DEFAULT NULL,
  `diferencia_par_slug` varchar(100) DEFAULT NULL,
  `ahorro` varchar(100) DEFAULT NULL,
  `ahorro_slug` varchar(100) DEFAULT NULL,
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16420 DEFAULT CHARSET=latin1;
```

You try to search for duplicates and with this query they do not appear. But using another program if they appear.
```
select
	marca_slug,
	modelo_slug,
	year_slug,
	motor_tipo_slug,
	motor_slug,
	stage_slug,
	original_potencia_slug,
	count(*)
from
	performance_data
group by
	marca_slug,
	modelo_slug,
	year_slug,
	motor_tipo_slug,
	motor_slug,
	stage_slug,
	original_potencia_slug
having
	count(*) > 1
```

Even when searching directly for the values, 1 result still appears, but with other programs several result.
```
SELECT * FROM performance_data WHERE marca_slug='bmw' 
AND modelo_slug='serie-1' 
AND year_slug='2015-2019' 
AND motor_tipo_slug='gasolina' 
AND motor_slug='120i-20t' 
AND stage_slug='stage1' 
AND original_potencia_slug='184-cv';
```

**Comment by ShadelessFox** [comment]
Hello @dancodedev,

Unfortunately, I cannot reproduce the issue.

Can you please screenshots showing the output from third-party software and from DBeaver?

**Comment by dancodedev** [comment]
@ShadelessFox  hi

**HeidiSQL 11.2.0.6.2.13**
![image](https://user-images.githubusercontent.com/45150122/165541766-b37d69ae-be1d-46c6-82db-2f1efef3aefd.png)

**Dbeaver 22.03**
![image](https://user-images.githubusercontent.com/45150122/165541839-4f0dd92f-9b50-42e7-802d-8c19c49bbabe.png)

**DB**
[https://we.tl/t-zTLyfwjTLk](https://we.tl/t-zTLyfwjTLk)

**Comment by ShadelessFox** [comment]
By using the query against the provided dump, I get two rows:

![image](https://user-images.githubusercontent.com/35821147/165552639-850afbdc-57bf-4e56-aad4-8a46c0828c68.png)

Can you please provide the driver version? Open connection settings, hit <kbd>Test Connection</kbd> and there will be the `Driver` field.

**Comment by dancodedev** [comment]
![image](https://user-images.githubusercontent.com/45150122/165580230-0c5fab9d-11ba-4770-b35d-07a31d3af2d4.png)
![image](https://user-images.githubusercontent.com/45150122/165580254-a0d18f11-6180-4291-85b3-667abbc60eca.png)
I'm sorry, I don't know if it's there

**Comment by ShadelessFox** [comment]
In my case, I'm using MySQL driver. Can you try it instead?

**Comment by dancodedev** [comment]
With MySQL yes it works :)

**Comment by ShadelessFox** [comment]
So I assume that this issue can be closed now?

**Comment by dancodedev** [comment]
Yes, for me you can close it now. Thank you.

I hope someone knows how to repair the MariaDb drive
