### ISSUE TITLE
error etl oracle to postgres

### ISSUE THREAD

**Issue by fburelli** [dbeaver/dbeaver#16263]
#### System information: 
- Operating system windows 10
- DBeaver version 21.x and 22.x

#### Connection FROM specification:
- Database Oracle spatial
- version 12c (enterprise release 12.2.0.1.0 64 bit)
- Driver name: oracle.jdbc.OracleDriver (com.oracle.database.jdbc:ojdbc8:RELEASE[12.2.0.1])
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Connection TO specification:
- Database PostgreSQl 13.6 on Ubuntu 64 bit
- extension PostGIS 3.x 
- Driver name: org.postgresql.Driver (org.postgrsql:postgresql:RELEASE[42.2.3.jre7]
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:

Exporting spatial table from Oracle to PostgreSQL, geometry column ON Postgres DB are invalid. 
Export is OK with DBeaver version 7.x

**Comment by LonwoLonwo** [comment]
Hello @fburelli 

Can you provide a source table DDL?
And screen of Columns mapping dialog?

![2022-04-21 11_48_34-DBeaver Ultimate 22 0 3 - TEST_GEOMETRY](https://user-images.githubusercontent.com/45152336/164417615-aadffe1b-f0f9-405d-82a6-d5d5b670794d.png)

 Also, what do you mean about "geometry column ON Postgres DB are invalid"?

Please check [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files).

**Comment by fburelli** [comment]
Column table source and destination are the same. Field mapping is one 2 one for completed data export.
Geometry format on destination table, appear with list of coordinates but not correctly formatted.
I'm sorry but don't have screenshot becouse i have downgrade software without save screen.

Table layout
![table-layout](https://user-images.githubusercontent.com/104130770/164444718-0e75b549-0a16-4875-b2b8-4d07f885c480.png)

Table ddl
![table-ddl](https://user-images.githubusercontent.com/104130770/164444700-f5f85005-61f3-486a-b2dd-47c6a906c43a.png)

DDL text:
CREATE TABLE "SIVEP"."SVP_ZONA" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DESCRIZIONE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"GEOM" "SDO_GEOMETRY", 
	"RECAPITO" VARCHAR2(50 CHAR), 
	"REFERENTE" VARCHAR2(50 CHAR), 
	"DATA_INIZIO" TIMESTAMP (6) DEFAULT SYSDATE, 
	"DATA_FINE" TIMESTAMP (6) DEFAULT TO_DATE('2999-12-31 00:00:00', 'yyyy-mm-dd hh24:mi:ss'), 
	"ULTIMA_VERSIONE" NUMBER(1,0) DEFAULT 0, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TB_SIVEP"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TB_SIVEP" 
 VARRAY "GEOM"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
  ( TABLESPACE "TB_SIVEP" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 VARRAY "GEOM"."SDO_ORDINATES" STORE AS SECUREFILE LOB 
  ( TABLESPACE "TB_SIVEP" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

**Comment by LonwoLonwo** [comment]
Ok. Can you provide a sample of data your "GEOM" "SDO_GEOMETRY" column?
Example of incorrect data will be also helpfull.

**Comment by fburelli** [comment]
this is error from the screen.
![image](https://user-images.githubusercontent.com/104130770/164485949-52feb13d-fd5b-4d95-ae6f-ee90caccb244.png)

**Comment by fburelli** [comment]
this is the csv export with erro
[SVP_ZONA_202204211659.csv](https://github.com/dbeaver/dbeaver/files/8532142/SVP_ZONA_202204211659.csv)
r

**Comment by ShadelessFox** [comment]
Hello @fburelli,

The attached CSV file seems to be weirdly formatted.

Can you please attach a screenshot of the `Preview Data` dialog showing the data you're trying to export? There's a button called `Preview Data` that can be used to access this dialog on the mappings page during data transfer.

**Comment by uslss** [comment]
There has been no update on the issue for a long time.
If it is still actual - feel free to reopen it with additional info.
