### ISSUE TITLE
Querying more that 6 columns returns an error

### ISSUE THREAD

**Issue by DylanBranch** [dbeaver/dbeaver#16276]
#### System information: 
- Operating system (distribution) and version: MacOs Montery 12.1 (m1 chip) 
- DBeaver version Version 22.0.3.202204170718
- Additional extensions no 

#### Connection specification:
- Database name and version prestoDB 0.272
- Driver name prestoDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Hey there, 
anytime I try to query more than 6 columns, the query will fail, "select *" will always fail. Error log is below
I have tried to install every version of DBeaver available for my CPU architecture without success. 
A coworker has had the same issue in the past, their fix was to retrograding to an older version of DBeaver, which did not work for me. 
I have tested my connection & queries with my Network admin and different coworkers, all have confirmed that the connection was right and that the queries were working on their side.  

#### Steps to reproduce, if exist:
Any query returning more than 6 columns will fail (that number can vary, sometimes 8 is fine, but 6 has been the most common) 

#### Include any warning/errors/backtraces from the logs
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/8533619/dbeaver-debug.log)

**Comment by ShadelessFox** [comment]
Hello @DylanBranch,

I suspect that the issue is on the driver's side.

Can you please provide the database version and the driver version? I think you mixed them up. (0.272 is the latest driver version)

What happens if you use Trino driver instead?

**Comment by DylanBranch** [comment]
Hi @ShadelessFox, 

Switching to Trino has fixed my issue, thanks a lot!
