### ISSUE TITLE
查看表时如果能平滑滚动就好了

### ISSUE THREAD

**Issue by maxs-marcel** [dbeaver/dbeaver#16280]
您好, 我是mac用户, 非常喜欢这款数据库管理工具, 但仍然希望能做到查看表数据时能够像DataGrip一样平滑滚动, 这样对我们查看较多字段的数据表时有很大帮助. 期待改进

**Comment by E1izabeth** [comment]
Hi, @maxs-marcel! Thank you for reporting.
I hope the conversation in these tickets https://github.com/dbeaver/dbeaver/issues/6536 , https://github.com/dbeaver/dbeaver/issues/10184 will help you. 
I'll close this ticket as it dublicates https://github.com/dbeaver/dbeaver/issues/10184.
