### ISSUE TITLE
Can't switch off the "Save/restore active schema" option

### ISSUE THREAD

**Issue by ajperez81** [dbeaver/dbeaver#16282]
#### System information: 
- Operating system: Windows 10 Pro 2004
- DBeaver version: 22.0.3 community edition
- Additional extensions: none

#### Describe the problem you're observing:
The "save/restore active schema" preference can't be switched off.

#### Steps to reproduce, if exist:
1. Open the "Window > Preferences" dialog and select the "Editors > SQL Editor" pane.
2. Uncheck the "Auto-save > Save/restore active schema" checkbox.
3. Click on "Apply and close".
4. Open "Window > Preferences > Editors > SQL Editor" again. The "Save/restore active schema" option should be disabled, but it's back to its default enabled state.

Not a big deal, but it would be nice if you could fix it :)

**Comment by E1izabeth** [comment]
Hi, @ajperez81! Thank you for bug report!
