### ISSUE TITLE
Dbeaver column data filter function

### ISSUE THREAD

**Issue by tianlongJ** [dbeaver/dbeaver#16289]
Dbeaver列数据筛选功能能否做成navicat那样，现在的搜索太难用了，要来回拖动

Can the Dbeaver column data filtering function be made like navicat? The current search is too difficult to use, and it has to be dragged back and forth

**Comment by uslss** [comment]
@tianlongJ could you provide some examples of the feature you need?

**Comment by tianlongJ** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月25日(星期一) 下午4:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dbeaver/dbeaver] Dbeaver列数据筛选功能 (Issue #16289)





 
@tianlongJ could you provide some examples of the feature you need?

**Comment by tianlongJ** [comment]
> @tianlongJ could you provide some examples of the feature you need?

![图片](https://user-images.githubusercontent.com/50390874/165200301-6a433539-f1bb-4e3e-927b-50a293b53e51.png)
navicat这种的，筛选会更方便，不用拖动数据列也不用手动输入like这种以及引号

**Comment by LonwoLonwo** [comment]
Please use English language.

**Comment by tianlongJ** [comment]
like navicat


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dbeaver/dbeaver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 中午1:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dbeaver/dbeaver] Dbeaver列数据筛选功能 (Issue #16289)





 
Please use English language.

**Comment by E1izabeth** [comment]
DBeaver has data filtering.

You can write custom filtering queries here

![image](https://user-images.githubusercontent.com/28875055/165257331-ff94dd7b-f440-4ea0-9007-0e0057632562.png)

Or you can set up filter for each column. In this case column name with filter will be bold. And you will see filter expression aggregating all your filters in the top of data.

![image](https://user-images.githubusercontent.com/28875055/165258079-ab1e7886-a699-45df-8ad3-cdf92506a8aa.png)


Maybe it fits your needs? If no, it would be beneficial, if you could explain or even better show what exactly do you mean.

**Comment by Xylandor** [comment]
@E1izabeth 
I believe what @tianlongJ is requesting is that the filtering be more of a point-and-click, graphical type of functionality. In the attached video, I show an example of how NaviCat's filtering works. Personally, it's too slow for me to filter like this. I'm more of a query writer, but some people may not be able to write queries as well, so they need more of a graphical approach. 

Video is slightly over a minute, but wanted to give you a good idea of how it works.

https://user-images.githubusercontent.com/24617679/167912674-7e3c9334-4035-438b-bcec-cb50e6c3a02d.mov

**Comment by E1izabeth** [comment]
Thank you for explanation, @Xylandor!

**Comment by E1izabeth** [comment]
> DBeaver has data filtering.
> 
> You can write custom filtering queries here
> 
> ![image](https://user-images.githubusercontent.com/28875055/165257331-ff94dd7b-f440-4ea0-9007-0e0057632562.png)
> 
> Or you can set up filter for each column. In this case column name with filter will be bold. And you will see filter expression aggregating all your filters in the top of data.
> 
> ![image](https://user-images.githubusercontent.com/28875055/165258079-ab1e7886-a699-45df-8ad3-cdf92506a8aa.png)
> 
> Maybe it fits your needs? If no, it would be beneficial, if you could explain or even better show what exactly do you mean.

@tianlongJ, does it cover your needs?

**Comment by uslss** [comment]
There has been no update for a long time.
If it is still actual - feel free to reopen the issue

**Comment by tianlongJ** [comment]
navicat这种的，很方便

------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月25日(星期一) 下午4:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dbeaver/dbeaver] Dbeaver列数据筛选功能 (Issue #16289)





 
@tianlongJ could you provide some examples of the feature you need?
