### ISSUE TITLE
Rows misplaced when exporting to .txt file 

### ISSUE THREAD

**Issue by CalmaKarma** [dbeaver/dbeaver#16295]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 22.0.4

#### Describe the problem you're observing:
The export wizard is not performing correctly when exporting to TXT files with "write to the single file" enabled.
For the latter files exported(or appended) to the single file, their column names are replaced with the first row.
![image](https://user-images.githubusercontent.com/54739936/165025023-b7c42933-5d6d-4b5c-9a3c-5ede908fc62a.png)
Exporting to seperate files works perfectly fine:
![image](https://user-images.githubusercontent.com/54739936/165025097-def77223-0f81-4ba5-b3a3-63c4453e659e.png)

#### Steps to reproduce, if exist:
Export two or more tables or views to TXT format, with "write to the single file" option enabled and other settings as default.

**Comment by CalmaKarma** [comment]
And I'd like to work on this issue if review is passed!

**Comment by ShadelessFox** [comment]
Hello @CalmaKarma,

You can start working on this issue independently from its review state.

As a hint, take a look at [`IAppendableDataExporter.java`](https://github.com/dbeaver/dbeaver/blob/2853dea503/plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/IAppendableDataExporter.java).

**Comment by CalmaKarma** [comment]
Hi, @ShadelessFox .

The bug is cause by a line of code at [DataExporterTXT.java, line 123](https://github.com/dbeaver/dbeaver/blob/2853dea50323f794421cb268938a64f99c84ffe6/plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/exporter/DataExporterTXT.java#:~:text=set%20of%20attributes-,showHeader%20%3D%20false%3B,-%7D)

**In short, a feature planned to be implemented feature caused this bug.**

The `showHeader` variable, **It intends** to append latter tables without repeating the attributes(or headers) if they are the same, which I suppose is a feature not yet implemented.

The line of code **now leads to skipping exporting latter headers** regardless of whether they have the same attributes or not.

Further concerns:
- The feature should be optional to users, and will require more work to determine and show a warning dialog if the attributes are the not same.
- This feature should also be consistantly designed for all appendable data exporters, which also requires more work. 

Other IAppendableDataExporters current status:
- The XLSX exporter has no such bug, since it exports different tables to different sheets and does not have such feature.
- The CSV exporter has the same bug. It only exports the header of the first table. Furthermore, `headerPosition` is only refering to the first table, instead of the whole concatenated table.

Hence, I think this feature should be regularized and implemented consistantly for all appendable exporters.

**For this issue, commenting out the line of code will fix it.**

If that is acceptable, I will try solve all existing bugs like this for all appendable exporters in this way, and post feature issue, since there are plans for making all exporters(SQL [#16204](https://github.com/dbeaver/dbeaver/issues/16204) ) appendable.

Or should I go and try to implement the feature and keep this issue open?

Thanks.

**Comment by ShadelessFox** [comment]
I don't think there should be any popups.

We can keep appending the header as an easy fix even if all attributes are the same. We might not know that in case of appending to the existing file, so it seems acceptable.

I believe you should keep this issue open. The described behavior is invalid. Meanwhile, #16204 is about a feature request.
