### ISSUE TITLE
Don't Synchronized data structures!!!

### ISSUE THREAD

**Issue by qq5411123** [dbeaver/dbeaver#16294]
Navicat has this feature！But dbeaver haven't! It's very needed at work！

**Comment by ShadelessFox** [comment]
Hello @qq5411123,

It's not entirely clear what feature you are referring to.

Can you please provide more information? Screenshots/Recording may help. Thank you.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual - feel free to reopen it with additional info
