### ISSUE TITLE
Struggling to run DBeaver on RaspPi400

### ISSUE THREAD

**Issue by DavidAJack83** [dbeaver/dbeaver#16317]
I'm running Raspbian GNU/Linux 11 (bullseye) on my RaspPi400

I have tried various different ways to try and run DBeaver on the raspberry pi 400, but none have worked so far. 

Can someone give me advice on how to do this? I have tried installers from the website as  well as archives. I have also tried to install via snap. None look to have been successful and I cannot run the application.

**Comment by LonwoLonwo** [comment]
Maybe you can find something helpful here: https://github.com/dbeaver/dbeaver/issues/7606

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual - feel free to reopen it with additional info
