### ISSUE TITLE
Can not set client to null for oralce connection setting if i has instatlled oracle server on local

### ISSUE THREAD

**Issue by yiiven** [dbeaver/dbeaver#16328]
I can't set the client to null for oralce connection setting if i has instatlled oracle server on local.
But the default local client cannot connect to another Oracle server.

**Comment by ShadelessFox** [comment]
Hello @vancevol,

Are you talking about this client?

![image](https://user-images.githubusercontent.com/35821147/165545869-c7b29843-ba14-4750-8056-46cf34330859.png)

This is a local client used in native database-specific tasks, such as dump and restore.

Why would you need to set it to `null`?

**Comment by yiiven** [comment]
Yes, that's what I'm talking about.

Because if this is not empty, Dbeaver may report the following errors：ORA-12514, TNS:listener does not currently know of service requested in connect descriptor.


But just yesterday!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dbeaver/dbeaver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月27日(星期三) 晚上10:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dbeaver/dbeaver] Can not set client to null for oralce connection setting if i has instatlled oracle server on local (Issue #16328)





 
Hello @vancevol,
 
Are you talking about this client?
 

 
This is a local client used in native database-specific tasks, such as dump and restore.
 
Why would you need to set it to null?

**Comment by ShadelessFox** [comment]
I assume that you're using TNS. When the client is present, a TNS names path is resolved (if not specified) using that client. 

Perhaps you should specify this path manually?

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual - feel free to reopen it with additional info
