### ISSUE TITLE
BabelFish Connection Driver only displays master database

### ISSUE THREAD

**Issue by TCorwinKRS** [dbeaver/dbeaver#16325]
Windows 10 & 11
AWS RDS Aurora Postgres with Babelfish

DBeaver Version 21.3.0 Properly displays all databases:
![image](https://user-images.githubusercontent.com/97609365/165395332-bc235e4e-4acf-4fa2-9728-b0180e72ac0b.png)

DBeaver Version 22.0.3 Only shows master database
![image](https://user-images.githubusercontent.com/97609365/165395604-f738fb6e-54f2-41c9-9037-b946d30d8141.png)

Both a colleague (Windows 10) and I (Windows 11) suffered from the issue. Moving back to the older version fixed it.

**Comment by ShadelessFox** [comment]
Hello @TCorwinKRS,

This change was intentional, we show only the default database.

The issue is caused by the fact that Babelfish does not support cross-database queries, so you can't do anything with any non-default database (including viewing the data).

**Comment by TCorwinKRS** [comment]
I believe that the AWS Aurora implementation of Babelfish does support the cross-database queries. 

From AWS Documents:
When you connect to the TDS port, the session is placed in the babelfish_db database. From T-SQL, the structure looks similar to being connected to a SQL Server instance. You can see the master and tempdb databases and the sys.databases catalog. You can create additional user databases and switch between databases with the USE statement. When you create a SQL Server user database, it's flattened into the babelfish_db PostgreSQL database. Your database retains cross-database syntax and semantics equal to or similar to those provided by SQL Server.

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish.html


Would it be possible to make it an option?

**Comment by LonwoLonwo** [comment]
Hello @TCorwinKRS 
 Option to choose the ability to see all databases added in this ticket: https://github.com/dbeaver/dbeaver/issues/5258
It will be available on Monday's next DBeaver release, 22.1.4.

![2022-08-01 18_45_49-DBeaver  C__Users_anvolka_work_DbeaverP_dbeaver-workspace-idea  - C__Users_anvol](https://user-images.githubusercontent.com/45152336/182202867-67b5b856-d996-43c8-bfe2-ce4d52141655.png)
