### ISSUE TITLE
PostgreSQL - inner join lateral

### ISSUE THREAD

**Issue by jrkw1971** [dbeaver/dbeaver#16321]
**Is your feature request related to a problem? Please describe.**

Problema al ejecutar sentencias SQL PostgreSQL - con *LATERAL* 

Ejemplo:
Select 
  cl.nombre
  , ve.saldo_primera_compra
from clientes cl
cross lateral (
   Select
      ve.saldo as saldo_primera_venta
  from ventas ve
  where
    ve.cliente_id = cl.id
  order by
     ve.fecha_venta desc
  limit 1
) ve on true;

**Describe the solution you'd like**

Actualizar controladores para que sea mas estándar a las sentencias psql

**Describe alternatives you've considered**

ninguna

**Additional context**

ninguna

**Comment by ShadelessFox** [comment]
Hello @jrkw1971,

What database version are you using?

**Comment by uslss** [comment]
there has been no updates on issue for a long time.
If it is still actual for you - feel free to reopen it with additional info
