### ISSUE TITLE
Running import tasks fails with "Target not specified for ..."

### ISSUE THREAD

**Issue by guardiande** [dbeaver/dbeaver#16322]
#### System information: 
- Windows 10
- 22.0.3

#### Connection specification:
- Postgres 13

#### Describe the problem you're observing:
Running saved database tasks to import from CSV results in "Target not specified for <NAME>.csv".

![image](https://user-images.githubusercontent.com/4947715/165353372-8ba4330f-b387-4836-99b1-a1e17f29c691.png)

Reassigning file and target table forgets previous column mappings. This also happens for freshly created tasks.

Reverting to 22.0.2 solves the problem.

#### Steps to reproduce, if exist:
* Import manually into a table from a CSV file.
* Save the task when importing.
* Rerun the saved task.
* Observe the error.

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
Fixed.
