### ISSUE TITLE
Cannot edit views' column comments

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#16337]
DB: PostgreSQL
Versions (DBEaver, PG) - maximally fresh.

Description - I cannot edit views' columns comment (tables' columns - work fine). See attached pics.

![dbeaver_view_comments](https://user-images.githubusercontent.com/11477081/165541895-b2b3d1e3-9c8c-471a-8005-6fac9ca12d4f.png)

**Comment by LonwoLonwo** [comment]
Hello @plotn 

This feature is not implemented.
Thanks for the report.

**Comment by Matvey16** [comment]
Verified

**Comment by LonwoLonwo** [comment]
Implemented in DBeaver 22.04

![2022-04-27 19_25_52-DBeaver Ultimate 22 0 4 - mv_t1_dk_a3](https://user-images.githubusercontent.com/45152336/165568392-d152ead0-8dd4-4a99-8628-f1b1ecabcc11.png)
