### ISSUE TITLE
DBeaver hangs on Windows 10.

### ISSUE THREAD

**Issue by diqipib** [dbeaver/dbeaver#16345]
![image](https://user-images.githubusercontent.com/30756317/165581139-45e7d487-d916-4f91-82fc-35faa5d053cd.png)

Программа dbeaver.exe версии 0.0.0.0 прекратила взаимодействие с Windows и была закрыта. Чтобы узнать, имеются ли дополнительные сведения о проблеме, просмотрите журнал проблем в разделе "Безопасность и обслуживание" в панели управления.
 Идентификатор процесса: 566c
 Время запуска: 01d85a528f99ea3d
 Время завершения: 21
 Путь к приложению: C:\Distr\dbeaver-ce-22.0.3-win32.win32.x86_64\dbeaver\dbeaver.exe
 Идентификатор отчета: 3fe174ee-ce2f-4140-96cc-2566ff63f619
 Полное имя пакета сбоя: 
 Код приложения, связанного со сбойным пакетом: 
 Тип зависания: Unknown

**Comment by ShadelessFox** [comment]
Hello @diqipib,

Please provide more information about your issue.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual - feel free to reopen it with additional info
