### ISSUE TITLE
SQL Editor does not honor the "resultset fetch size" for Teradata

### ISSUE THREAD

**Issue by ahhmedbilal** [dbeaver/dbeaver#16350]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 22.0.3
- Additional extensions

#### Connection specification:
- Database name and version: Teradata 17.10
- Driver name: Teradata JDBC 17.10
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

In Global setting for "Data Editor" I have following settings. 
"Resultset Fetch Size" is set to 6000. 
"auto fetch next segment" and "refresh data on next page read" and "use fetch size" is ticked. 

when i run following query is "SQL Editor"
select * from table; 
where table is having million of rows e.g 30 million rows. 
then resultset panel shows first 6000 rows, that is ok but the bottom right corner of the DBeaver window keep on showing the query progress, the "Background Tasks" also shows that query is running, where as it should have stopped after fetching 6000 rows. 

Now if i run any other small query e.g row count query from a small table, then it keeps on running as well and is added to "Background Tasks" but dont return any result unless the first query is ended. And the first query takes a long time to complete and first query keeps fetching the data and DBeaver memory size in Windows task manager grows to more than 1.2 GB and keeps growing. 

Above scenario is also true even after setting OFF following settings. 
"auto fetch next segment" and "refresh data on next page read" 

Above scenario is related to SQL Editor. 

Now below scenario is related to "View Data" on right click context menu of a table or view. 

When i right click a table or view and click "view Data", then the table/view window shows 6000 rows only and query stops after it i.e there is no background query running and the bottom right corner of DBeaver window does not show any progress, so every thing is OK in this case. 

Can you please fix the "Resultset Fetch Size" issue for SQL Editor, i.e query should end after fetching 6000 rows and there should not be any background task running after fetching 6000 rows. 

Thanks....

**Comment by ahhmedbilal** [comment]
This driver i am using: Teradata JDBC Driver 17.10.00.27
from : https://downloads.teradata.com/download/connectivity/jdbc-driver

**Comment by ahhmedbilal** [comment]
![image](https://user-images.githubusercontent.com/46369037/165725349-6875755d-dcbc-489a-9e07-d53976e844fe.png)
This data editor setting (global setting) i am using.

**Comment by ahhmedbilal** [comment]
it was closed mistakenly.

**Comment by Matvey16** [comment]
@ahhmedbilal Hello. Thank you for your report

**Comment by LonwoLonwo** [comment]
Hello @ahhmedbilal 

Can you please uncheck the "Use fetch-size" setting?

![2022-05-30 16_24_26-DBeaver Ultimate 22 1 0 - _DBC_ Script-29](https://user-images.githubusercontent.com/45152336/171001698-d01387eb-c850-4f1a-a7e9-7765c6869cc0.png)

It helped me:

![Wxpe4Nc7Ma](https://user-images.githubusercontent.com/45152336/171001738-fabeddf6-c22f-4844-8fdd-8933da6d5c76.gif)

**Comment by ahhmedbilal** [comment]
Hi,

100,000 rows for dbeaver is nothing. the scenario that i mentioned, you can
observe that if you have millions of rows e.g 20 millions or so with 20 to
30 columns, then you will see the long progress on the lower right corner
and in background tasks..

Regards

**Comment by LonwoLonwo** [comment]
But did you uncheck the "Use fetch-size" button in the preferences?

**Comment by ahhmedbilal** [comment]
Yes, I did. These are the settings I am using.

![image](https://user-images.githubusercontent.com/46369037/171109415-258fa0ab-1cc3-4415-92de-0e2045d7e1c1.png)

I have 102464655 (102 millions) rows in a table and 30 columns. The select
* on this table does fetch 6000 rows but here is the status of lower right
corner.

![image](https://user-images.githubusercontent.com/46369037/171109540-a5aba218-88e8-465d-add1-c18b153c078b.png)


Background task still running:

Regards

**Comment by LonwoLonwo** [comment]
Sorry, I do not see inages. You can't add images via e-mail, you should do it on this GitHub page.

**Comment by ahhmedbilal** [comment]
Bg task still running. 

![image](https://user-images.githubusercontent.com/46369037/171109302-c5641a0a-e3e4-4a10-a65e-d59351654346.png)

I will edit prev comment to add images now.

**Comment by ahhmedbilal** [comment]
> Sorry, I do not see inages. You can't add images via e-mail, you should do it on this GitHub page.

You should be able to see now.

**Comment by ahhmedbilal** [comment]
about 37 minutes have passed and bg task still running.

**Comment by LonwoLonwo** [comment]
Hello @ahhmedbilal 

I've added ability to use Teradata TOP limit syntax. 
Please test it in our Early Access version: https://dbeaver.io/files/ea/
You should enable the "Use SQL to limit fetch size" setting for it.

![2022-05-30 17_56_51-DBeaver Ultimate 22 1 0 - _DBC_ Script-29](https://user-images.githubusercontent.com/45152336/171019212-c74c5a14-c656-48e8-b357-923857601e7c.png)

**Comment by ahhmedbilal** [comment]
> 

Thanks Lonwo for the build, its working perfectly now. at least now i dont hv to use "top N" in select and dont have to kill the long running queries. 

one more thing: i can not see the excel icon on the status bar of resultset panel. i can see in the video that u shared. is it coming in some other build? 
![image](https://user-images.githubusercontent.com/46369037/171346719-8ec1741c-02c3-4b90-a734-82b1040892ae.png)

**Comment by LonwoLonwo** [comment]
I use DBeaver Ultimate. It includes Office extension by default.

DBeaver community users can add Office extension manually. Here you can find the instruction: https://github.com/dbeaver/dbeaver/wiki/Optional-extensions

**Comment by LonwoLonwo** [comment]
And thanks for the quick answer @ahhmedbilal

**Comment by ahhmedbilal** [comment]
and now i am getting following error when i drag a col to "Group" panel...

![image](https://user-images.githubusercontent.com/46369037/171427364-5b987ab0-2873-43b4-b1fc-c882d5736f77.png)

**Comment by LonwoLonwo** [comment]
Now - does it means in the last DBeaver version?
Can you provide some steps and query with syntax error? 
You can find it in the [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager).

**Comment by ahhmedbilal** [comment]
> Now - does it means in the last DBeaver version? Can you provide some steps and query with syntax error? You can find it in the [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager).

Yes in latest ver i.e 22.1.0 (the one in EA). 

Step: 
1. run "select * from table"
2. in resultset, drag any column to "Group" panel to take column values and count of each value. 

Query: 
SELECT TOP 9000 colName, COUNT(*) AS **_count_** FROM (SELECT * FROM tableName) src GROUP BY colName ORDER BY count DESC; 

Issue: the word "count" after "count(*) AS" and "ORDER BY" is causing problem. It can be changed to col_count...

**Comment by LonwoLonwo** [comment]
Yes! I see. Thanks for the bug report!
It will be fixed in this ticket #16628 in the DBeaver 22.1.0

**Comment by ahhmedbilal** [comment]
I downloaded 22.1.0 today from EA. Now grouping works as it should. 
![image](https://user-images.githubusercontent.com/46369037/171584436-5ad7ce3e-f0e7-4ec2-94bf-081de14c9fee.png)

but, when i click "Calc" or "Metadata" tab and then come back to "Grouping" tab, its empty. 

![image](https://user-images.githubusercontent.com/46369037/171584613-e3765fb3-83e3-48dd-bb76-428e1f78a9a8.png)

**Comment by LonwoLonwo** [comment]
Thanks for the report @ahhmedbilal 
I will create ticket for this.

**Comment by ahhmedbilal** [comment]
Hi again, 
sometime i notices DBeaver is not applying top N to long queries. here is screen shot. 

![image](https://user-images.githubusercontent.com/46369037/171822170-d4a74198-389d-4910-96d4-f048a88cf2f6.png)

could not get the reason why its not putting Top after select. 

In Teradata we can use the word "sel" instead of "select". i am using "sel" in both queries. here are the queries....

query 1: 
SEL 1,
	SP.TEKN_SOPIMUS_ID		AS SRC_TECH_AGMT_ID
	, case 
..... its very long query

screen shot: 
![image](https://user-images.githubusercontent.com/46369037/171823364-955a0cb9-775a-463a-b852-5ba82fecf1fc.png)

query 2: 
sel 
/*--  abc*/ 
	sp.TEKN_SOPIMUS_ID
	, SP.TILANNEPVM 
	, 1
	, 2
	, 3
FROM
	table1 SP
left outer join table2 sk
	ON SP.TEKN_SOPIMUS_ID= SK.TEKN_SOPIMUS_ID
screen shot: 
![image](https://user-images.githubusercontent.com/46369037/171823483-2068d502-081e-43ac-8a7a-cc3e480265bd.png)


so, for 2nd query, top is being used, but not for first one. 
also "sel" is being changed to "select" automatically by dbearver, but not for 1st query. 

also plz note, there is some character appearing in query manager for first query between 1 and "SP.TEKN_SOPIMUS_ID" and after "case" word as well.....

**Comment by LonwoLonwo** [comment]
Can you provide the full SQL for the first case? Wich without TOP.
I can't reproduce the:

```sql
SEL 1,
SP.TEKN_SOPIMUS_ID AS SRC_TECH_AGMT_ID
, case
```

**Comment by LonwoLonwo** [comment]
And I have a counter-question. What do you think about data import in DBeaver for Teradata? Is it fast enough for you, or do you use other tools for data import? Thanks for the answer.

**Comment by ahhmedbilal** [comment]
> -- abc

Here is the long sql. 

SEL 1,
	SP.tech_sp_id		AS SRC_TECH_AGMT_ID
	, case 
		when day_type='029' 
			then SPA.days 
		else null 
	  end              AS BD_ISSU_DT
	, case 
		when day_type='026' 
			then SPA.days 
		else null 
	  end              AS MATURTY_DT
	, SK.koko          AS CPN_TYPE
	, CASE
		WHEN CPN_TYPE ='fixed' and koko IN (10,11,12)
			then SK.interest_rate
		else null
	  end as BOND_COUPN_RATE
	, CASE
		WHEN CPN_TYPE <> 'floating'and koko IN (10,11,12)
			then SK.interest_rate
		else null
	  end as TM_PRD_CD
	, CASE
		WHEN CPN_TYPE = 'floating'and koko IN (28,42)
			then SK.interest_rate
		else null
	  end as FLOATNG_NOTE_RATE
	, CASE
		WHEN CPN_TYPE = 'floating'and koko IN (28,42)
			then SK.mar_pro
		else null
	  end as FLOATNG_SPRD_RATE
	, SP.ssn               AS GTR_ID
	, case
		when SP.ssn is not null or SP.ssn <> ''
			then 'NBE'
		else null
	  end  AS GU_ID_TYPE
FROM
	db1.sp_base SP
LEFT OUTER JOIN
(
	sel
		  days
		, day_type
		, tech_sp_id
	from db1.sp_days_KK
	where
		(sel add_months (business_date - extract (day from business_date), 0) from db2.Stream_Id where stream_Key = 1510) BETWEEN days_start AND days_ends
	 	AND repdate 	= (sel add_months (business_date - extract (day from business_date), 0) from db2.Stream_Id where stream_Key = 1510)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY tech_sp_id ORDER BY days_start desc) = 1
) SPA
	ON SP.tech_sp_id=SPA.tech_sp_id
LEFT OUTER JOIN
(
	sel
		  koko
		, interest_rate
		, mar_pro
		, tech_sp_id
	from db1.sp_interest_KK
	where
		(sel add_months (business_date - extract (day from business_date), 0) from db2.Stream_Id where stream_Key = 1510) BETWEEN interest_start AND interest_ends
		AND repdate 	= (sel add_months (business_date - extract (day from business_date), 0) from db2.Stream_Id where stream_Key = 1510)
	QUALIFY ROW_NUMBER() OVER (PARTITION BY tech_sp_id ORDER BY interest_start desc) = 1
) SK
	ON SP.tech_sp_id= SK.tech_sp_id
WHERE 1=1
	and SP.repdate 	= (sel add_months (business_date - extract (day from business_date), 0) from db2.Stream_Id where stream_Key = 1510)

**Comment by ahhmedbilal** [comment]
> And I have a counter-question. What do you think about data import in DBeaver for Teradata? Is it fast enough for you, or do you use other tools for data import? Thanks for the answer.

I don't often use DBeaver for data load. I just tried it now with a small table. DBeaver is using jdbc insert i think to insert data to Teradata table, if so, it will be slow for large files. To load data super fast to Teradata e.g 28 Million rows in about 5 to 6 min (my personal experience :) ), we use TPT utility (Teradata Parallel Transporter and it has multiple operator e.g fastload operator, multiload operator, export operator). In order to use this utility TPT needs to be installed on client system, so this will not be the option to use with DBeaver. TPT is free to use and can be down loaded from Teradata site. 

However, there is another option to load even faster i/e JDBC fastload. It will be much more faster than jdbc insert, but slower than TPT fastload operator. you may check for this option in TD docs. 

some code example: 
https://downloads.teradata.com/connectivity/articles/speed-up-your-jdbcodbc-applications
The nice thing is that your Java code doesn't need to change in order to use JDBC FastLoad. Your application uses the exact same Prepared Statement batches as in the previous example. Just add TYPE=FASTLOAD to your connection parameters, and the Teradata JDBC Driver will use JDBC FastLoad for particular SQL requests.   

some useful links: 
https://teradata-docs.s3.amazonaws.com/doc/connectivity/jdbc/reference/current/jdbcug_chapter_2.html#BABFGFAF

**Comment by LonwoLonwo** [comment]
Thanks for the quick and informative answer!

Yes, I read about the FastLoad and I tried it. But it's to many restrictions with it. Empty target table, batch size, table and columns names, data types. Too hard to implement it in our universal tool, unfortunately...

**Comment by ahhmedbilal** [comment]
Instead of fastload, try multiload utility. Empty table restriction is not there with multi load. 
But jdbc multiload is not supported. 

from the link: https://downloads.teradata.com/connectivity/articles/speed-up-your-jdbcodbc-applications 

**JDBC FastLoad can only insert data into an empty table, and JDBC FastLoad is only recommended for loading large amounts of data -- at least 100,000 rows total.**

But to me, above figure is just a number. we hv been loading in TD with Fastload utility even less amount of rows. 

Multiload example: https://docs.teradata.com/r/utmttCBNdC6kDW8061XWDQ/lTdTBjXrWnjlN2sAEgn5Og

**Comment by ahhmedbilal** [comment]
Now Teradata is using TPT utility for all load/export operations. TPT is using fastload and mload (multiload) internally, but TPT is has consistent syntax. So would suggest to use TPT UPDATE operator (which multiload operator). 

TPT has many operators 
1. Producer Operators
2. Consumer operators 
3. Standalone operator. 

more info about operators: https://downloads.teradata.com/tools/articles/introduction-to-the-teradata-parallel-transporter-operators

**Comment by ahhmedbilal** [comment]
Instead of fastload, try multiload utility. Empty table restriction is not there with multi load. But jdbc multiload is not supported. Is it so that with jdbc fast load, table needs to be empty?-- from phone
-------- Original message --------From: Anastasiya ***@***.***> Date: 6/7/22  14:41  (GMT+02:00) To: dbeaver/dbeaver ***@***.***> Cc: ahhmedbilal ***@***.***>, Mention ***@***.***> Subject: Re: [dbeaver/dbeaver] SQL Editor does not honor the "resultset fetch size" for Teradata (Issue #16350) 
Thanks for the quick and informative answer!
Yes, I read about the FastLoad and I tried it. But it's to many restrictions with it. Empty target table, batch size, table and columns names, data types. Too hard to implement it in our universal tool, unfortunately...

**Comment by ahhmedbilal** [comment]
Background task still running. unless it completes, i can not execute any
other qry in dbeaver for that connections.
will send another email once bg task is completed.
