### ISSUE TITLE
Cannot open DBeaver. Error Message: An Error Has Occurred. See the log file

### ISSUE THREAD

**Issue by amandaaa1** [dbeaver/dbeaver#16356]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by 2019-05-10** [comment]
Without at least your Operating System, the DBeaver version and how you did install, nobody will be able to help you.

**Comment by Matvey16** [comment]
@amandaaa1 Hello. Do you use some kind of remote workspace like citrix etc. If so, please try our latest version, this bug shuold have been fixed in it.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual - feel free to reopen it with additional info
