### ISSUE TITLE
PostgreSQL: better function calling

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#16352]
Hi! There is well known PostgreSQL feature (when calling functions) - we must strictly use specified types.
E.g. function:

CREATE OR REPLACE FUNCTION test_function(
	p_task_id		int8,
	p_item_title 	varchar(2000),
	p_item_author	int8,
	p_create_ts		timestamp,
	p_update_ts		timestamp
)

cannot be called via:
select test_function(
	p_task_id => 1,
	p_item_title => 'тестовый элемент 3',
	p_item_author => 406,
	p_create_ts => current_timestamp,
	p_update_ts => null
)

The error is - "function does not exist. No function matches the given name and argument types."

When we "right click" onto function we see "Generate SQL (CALL)" and "Execute procedure", The SQL generated is:
SELECT test_function(:p_task_id,:p_item_title,:p_item_author,:p_create_ts,:p_update_ts,:p_closed_by,:p_close_ts,:p_close_comment,:p_before_id);

And this does not solve our problem, the only way to call function is:
select test_function(
	p_task_id => 1::int8,
	p_item_title => 'тестовый элемент 3'::varchar,
	p_item_author => 406::int8,
	p_create_ts => current_timestamp::timestamp,
	p_update_ts => null::timestamp
)

The idea is: 
1. Generate "fully qualified call sql" - with type casting via :: or (maybe better) cast(x as ...)
2. Add column "data type" to params binding dialog and use it in an appropriate way (add casts "underneath"). 

I think both ideas should be realized.

**Comment by ShadelessFox** [comment]
Hello @plotn,

Thanks for the feature request.
