### ISSUE TITLE
[ERD] Raltions of a table to itself ignore any collision

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#16367]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 22.0.4

#### Steps to reproduce, if exist:
1. Open a diagram for a schema that has a table with reference to itself
2. Drag another table to overlap a line of this relation

**Expected:** Line is redrawn to not touch another table
**Actual:** Line always stays the same

![dbeaver_EcGOUQ1SUp](https://user-images.githubusercontent.com/82543000/165916659-34812358-6784-49fa-9b41-07497c6288ff.gif)

**Comment by serge-rider** [comment]
Fixed in another issue

**Comment by Matvey16** [comment]
Relation ignores the collision if it happens at one of the corners, but works if the line goes through another table.
![dbeaver_D3jYlFuSnp](https://user-images.githubusercontent.com/82543000/169036602-109e0924-1ca6-4c8b-b596-59f15fe5b75d.gif)

**Comment by ShadelessFox** [comment]
Duplicate of #14724
