### ISSUE TITLE
Background color for even/odd rows

### ISSUE THREAD

**Issue by hoppfrosch** [dbeaver/dbeaver#16364]
#### System information: 
- Win 10 Ultimate
- DBeaver 22.0.3

#### Describe the problem you're observing:
After trying out "dark theme" and switching back to "classic" or "light" theme, the background color of the odd rows in result view remained black. Also the basic background color of the result view remained dark.

**Expected behaviour**
As I want true "light" colors again within the result grid,  the themes should be able to set the alternating colors for odd/even rows. Or at least there should be a possibility for users to define the colors of odd/even rows in result grid.

**What I tried, to solve the problem**
* Searched within configuration dialog for setting the color manually, but failed.
* Switching theme from "dark" to "light" (or "classic")(and vice versa) does not change the color from dark to light again for odd
rows ...

Is there a solution for setting the bg color for odd rows? Or have I overseen somnething?

**Comment by LonwoLonwo** [comment]
Hello @hoppfrosch 

Did you restart DBeaver after the thema switching?

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual - feel free to reopen it with additional info

**Comment by hoppfrosch** [comment]
Sorry - Problem still exists.

For sure I restarted DBeaver after switching - bg color of odd rows is still black, which is annoying (I use dbeaver frequently - and in 2 months I restarted it quite often ;-))

Dont know, which additional info to give beside above info that would help you

**Comment by LonwoLonwo** [comment]
Maybe you can provide a video of this issue?
We can't reproduce your issue for now.

**Comment by hoppfrosch** [comment]
Sorrry for coming back too late - just for information: 

DBeaver 22.2.3 does NOT show this behaviour anymore - after frist tests, switching between  dark-light-default colorscheme works correctly.  :thumbsup:
