### ISSUE TITLE
After execution with error some keys doesnt work SQL SERVER

### ISSUE THREAD

**Issue by manguicho** [dbeaver/dbeaver#16371]
#### System information: 
- Operating system WINDOWS 11
- DBeaver version 22.0.3 COMUNITY
- Additional extensions

#### Connection specification:
- Database name and version 
- Driver name Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? f5 vpn client

#### Describe the problem you're observing:

Before executing somethign with ctrl+enter when an error is raised, seems like certain control+<key> combinations doesnt work
for example: if control+enter is pressed only de enter (without control) occurs. If you switch tab and return all works good.

#### Steps to reproduce, if exist:

1 - connect to sql database with jdbc
2 - wirhte something to get an execution error
3 - execute

**Comment by ShadelessFox** [comment]
Hello @manguicho,

Can you please record a video showing the issue? Thanks.

**Comment by manguicho** [comment]
Reseting perspective solved the issue. I had to somehow hide the error popup because it is very invasive for me.

**Comment by ShadelessFox** [comment]
I see. If so, I'll close this issue for now.
