### ISSUE TITLE
Multi Line Tab in SQL Editor

### ISSUE THREAD

**Issue by ahhmedbilal** [dbeaver/dbeaver#16377]
**Is your feature request related to a problem? Please describe.**

In Notepad++ we can enable multiline Tab bar with following setting..

![image](https://user-images.githubusercontent.com/46369037/166098779-cb5b5ac9-4e67-4552-ab76-412a35607167.png)

in same way, DBeaver should also add this config setting to allow multiline tab bar. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ShadelessFox** [comment]
Hello @ahhmedbilal,

This issue is a duplicate of #16050.

Please track the progress there.
