### ISSUE TITLE
xml export errror in new version 22.0.4 

### ISSUE THREAD

**Issue by marcos76hd** [dbeaver/dbeaver#16384]
#### System information: 
- Operating system: Win Server 2019
- DBeaver version: 22.0.4
- Additional extensions

#### Connection specification:
- Database name and version: SAP Hana
- Driver name: SAP / HANA
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Since installing the new dbeaver version 22.0.4 I get an error message while trying to export sql results as csv.  In the dialogue I get to step 4 (Output). After clicking on Next I get the error message attached

#### Include any warning/errors/backtraces from the logs
See attachment

![dbeaver error](https://user-images.githubusercontent.com/104759159/166208828-cfcebce0-2421-45fd-9027-44eb253e0b35.JPG)

**Comment by LonwoLonwo** [comment]
Hello @marcos76hd 
Could you please attach the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by marcos76hd** [comment]
Hello,

please find attached the error log and the .log file (renamed). The dbeaver-debug.log is empty

[error log.log](https://github.com/dbeaver/dbeaver/files/8602041/error.log.log).
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/8602047/dbeaver.log)

**Comment by LonwoLonwo** [comment]
Ok, can you tell me more please about you steps?

Did you try to export result from query? Or from table?

**Comment by marcos76hd** [comment]
Hi,

I try to export results from a query.
I have the result, click on “export result”. Then the transfer dialogue opens.

-       Window Export Target: Selected export as CSV; clicked on Next

-       Extraction Configuration:

***@***.***

Clicked on Next

-       Format settings:
***@***.***

Clicked on Next


-       Output:

***@***.***



After clicking on Next the error occurs:

***@***.***



I did that one thousand times before the update without any issues.



<https://kluthe.com/nachhaltigkeit>[cid:MoreThanClimateNeutral_EN_0ac0b3a2-f611-4df7-8997-913fec5ba70a.png]<https://www.kluthe.com/en/sustainability>

[cid:Kluthe_Logo_3D_2018_claim_RGB_a027911c-5af9-4d16-bc62-615e84fae980.jpg]

Chemische Werke Kluthe GmbH
Gottlieb Daimler Straße 12 | D-69115 Heidelberg
Geschäftsführung: Martin Kluthe, Robert Kluthe

Handelsreg. Nr.: HRB 330556 | Registeramt: Mannheim
Ust-Id Nr.: DE 143261732 | Sitz der Gesellschaft: Heidelberg

DISCLAIMER: This e-mail is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of Chemische Werke Kluthe GmbH. If you are not the intended recipient, be advised that you have received this e-mail in error and that any use, dissemination, forwarding, printing or copying of this e-mail is strictly prohibited. If you have received this e-mail in error please notify Chemische Werke Kluthe GmbH.

E-mail: ***@***.******@***.***> or telephone: +49 (0) 6221 - 5301-0 or telefax: +49 (0) 6221 - 5301-176






Von: Anastasiya ***@***.***>
Gesendet: Montag, 2. Mai 2022 12:20
An: dbeaver/dbeaver ***@***.***>
Cc: Singer, Marco - CWK ***@***.***>; Mention ***@***.***>
Betreff: Re: [dbeaver/dbeaver] xml export errror in new version 22.0.4 (Issue #16384)


Ok, can you tell me more please about you steps?

Did you try to export result from query? Or from table?

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @marcos76hd
