### ISSUE TITLE
SSHJ installation: Cannot complete the install because one or more required items could not be found.

### ISSUE THREAD

**Issue by 41v4** [dbeaver/dbeaver#16386]
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04
- DBeaver version: 22.0.4
- Additional extensions: no additional extensions.

#### Describe the problem you're observing:
Unable to install SSHJ using Help -> Install New Software -> https://dbeaver.io/update/sshj/latest/

> Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver SSHJ 1.0.93.202112211454 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.93.202112211454)
  Missing requirement: Bouncy Castle PKIX, CMS, EAC, TSP, PKCS, OCSP, CMP, and CRMF APIs 1.69.0.v20210713-1924 (org.bouncycastle.bcpkix 1.69.0.v20210713-1924) requires 'java.package; org.bouncycastle.asn1.bsi [1.69.0,1.70.0)' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver SSHJ 1.0.93.202112211454 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.93.202112211454)
    To: org.eclipse.equinox.p2.iu; org.bouncycastle.bcpkix [1.69.0.v20210713-1924,1.69.0.v20210713-1924]

**Comment by Matvey16** [comment]
@41v4 Hello, you don't need to install SSHJ manually, it is now included in the base installation
