### ISSUE TITLE
[Trino] Can't select database/schema in SQL Editor

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#16382]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 22.0.4

#### Steps to reproduce, if exist:
1. Create a Trino connection without a default database/schema
2. Open SQL Editor for the connection
3. Click on schema selection button in top toolbar
4. Select any databse

**Expected:** Database is selected
**Actual:** Current schema still says "N/A"

**Comment by uslss** [comment]
#14693
