### ISSUE TITLE
Vertica - Please include option to disable comments altogether

### ISSUE THREAD

**Issue by alattke-chwy** [dbeaver/dbeaver#16397]
This is related to issue #14625 . 
Reading from comments system table (even though it is not populated in our DB) takes a long time and is I/O intensive.
I am on version 22.0.4.202205011839. 
Please provide an option to disable comments altogether as it takes 14s in test env and over a min in a busy prod cluster.

**Comment by LonwoLonwo** [comment]
Ok, thanks for the idea.

**Comment by alattke-chwy** [comment]
Hi @LonwoLonwo . We are in the process of reviewing DBeaver vs DBVisualizer. Could you let me know if this bug fix is on the roadmap?

**Comment by LonwoLonwo** [comment]
We added lazy comments loading in #16396

Now tables loading should be faster in DBeaver.

**Comment by LonwoLonwo** [comment]
So for now it is interesting to know - what type of comments prepare you disable now?

**Comment by alattke-chwy** [comment]
Thanks for replying. I updated to Version 22.1.0.202206051253. I no longer see this in the Navigation panel, but the Object Properties tab/panel it still happens.

When an object (ex. Table) is opened, this query that is being executed is:
```
request | select object_type, "comment", child_object from v_catalog.comments where object_schema ='${OBJECT_SCHEMA}' and object_name ='${OBJECT_NAME}'
min_duration_ms     | 11660
max_duration_ms     | 12533
sum_duration_ms     | 24193
count   | 2
```
So, 2 identical queries, each taking ~12s are running consecutively when building object and tapping into `comments` system table. (Also, 12s is in an idle system, on a busy system like our prod cluster this takes more than 30s).
If there's an option to disable this in the settings, I am not seeing it.

Thank you!

**Comment by LonwoLonwo** [comment]
There is no option for now. But it is in our plans.

**Comment by alattke-chwy** [comment]
Thank you!

**Comment by alattke-chwy** [comment]
> 

Hi! Can anyone provide an update on this please?

**Comment by LonwoLonwo** [comment]
Hello @alattke-chwy 

You can see more data about this ticket in the "Milestone" section.

**Comment by alattke-chwy** [comment]
Hi. Can someone provide an update to this ticket please?

**Comment by alattke-chwy** [comment]
@LonwoLonwo could you please provide an update on this?

**Comment by LonwoLonwo** [comment]
![2023-01-07 11_06_56-Vertica - Please include option to disable comments altogether · Issue #16397 · ](https://user-images.githubusercontent.com/45152336/211140698-0367c03d-f333-499e-9ba8-221d2fc236da.png)

**Comment by LonwoLonwo** [comment]
Implemented.

![2023-01-18 14_29_02-DBeaver 22 3 2 - _master_ Script-29](https://user-images.githubusercontent.com/45152336/213162773-abd3b9cd-5c5e-40c6-bf61-328b04cc37a4.png)

Available in the last DBeaver release.
