### ISSUE TITLE
DBeaver 22.0.4 breaks NTLM mssql authentication

### ISSUE THREAD

**Issue by robertz** [dbeaver/dbeaver#16390]
OS: MacOS 11.6.5 (Big Sur)
- DBeaver 22.0.4
- Ndditional extensions

- MS SQL
- mssql-jdbc 9.2.0x64
- Connection is not proxied

Problem Observed:

"User" (or "UserName") and "Password" connection properties must be specified for NTLM authentication.

DBeaver 22.0.4 Gets an error when trying to connect to a database using NTLM authentication. Rolling back to DBeaver 22.0.3 resolves the issue

**Comment by serge-rider** [comment]
Thank you for the bug report.
It is a result of SQL Server authentication redesign.

**Comment by serge-rider** [comment]
Could you check the fix in the Early Access version? https://dbeaver.io/files/ea/

**Comment by Mauro-Michelotti** [comment]
Hi Serge.
Same issue for me; fortunately, the E.A. version solved the problem.
Thanks a lot

**Comment by robertz** [comment]
E.A. version does resolve the issue. Thank you!

**Comment by Matvey16** [comment]
Verified
