### ISSUE TITLE
When you put a column name that's a keyword in backticks, it still uppercases

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#16391]
#### System information: 
Mysql M1 mac
Version 22.0.3.202204170718

#### Describe the problem you're observing:
ALTER TABLE stuff ADD COLUMN `USER`  <-- It always capitalizes user as I finish typing it even though it's in backticks

**Comment by Matvey16** [comment]
@turbobuilt Hello. Can you specify when it happens? I wasn't able to reproduce it in SQL Editor
![dbeaver_G8YmeZr2kU](https://user-images.githubusercontent.com/82543000/166414030-8bd9fd4a-a85f-4fbc-b134-34cdd8d90d15.gif)

**Comment by ghost** [comment]
![weird column](https://user-images.githubusercontent.com/7775272/166457004-ebcfdcd6-1030-4ad2-a6e8-20df00e1449d.gif)

Mysql localhost:3306 Version 22.0.3.202204170718, April 18 2022

I don't know what other information there is!

**Comment by LonwoLonwo** [comment]
Hello @turbobuilt 

Can you please check this setting?

Preferences -> Editors -> SQL Editor -> Code Completion -> "Insert case"

![2022-05-03 16_43_39-Preferences](https://user-images.githubusercontent.com/45152336/166464580-394c3fc8-544a-41b7-b3a7-2fe6ba01748b.png)

**Comment by ghost** [comment]
<img width="913" alt="Screen Shot 2022-05-03 at 14 46 07" src="https://user-images.githubusercontent.com/7775272/166476381-af0d945a-b266-4647-88af-b0b3e8afa547.png">

I have it set to default!

**Comment by LonwoLonwo** [comment]
Can you please change the "Inser case" setting to the "lower case"? 
Default case for the MySQL/MariaDB is mixed.

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual, feel free to reopen it.
