### ISSUE TITLE
DBeaver as Eclipse plugin missing Keys Schema

### ISSUE THREAD

**Issue by xchray** [dbeaver/dbeaver#16392]
Dear team, 

Not sure if this is a missing feature or a bug. 

in Eclipse plug-in (including 22.0.4), there is no DBeaver specific Keys-Schema. The Dbeaver Key-Schema however can be found in Zip or Installer version. 

Is that something can be added to Plug-in version as well? 
Thanks,
Xin

![image](https://user-images.githubusercontent.com/81406963/166417495-1161cf1a-f90a-4990-963f-06987f641b42.png)

**Comment by ShadelessFox** [comment]
Hello @xchray,

Thanks for the bug report.

**Comment by xchray** [comment]
did you drop this?
