### ISSUE TITLE
Call Stored Procedure from DBeaver to DB2 not working

### ISSUE THREAD

**Issue by atarox** [dbeaver/dbeaver#16409]
#### System information: 
- Operating system (distribution) and version: Windows 10 Enterprise
- DBeaver version Version 21.3.3.202201221033
- Java version  java.version=11.0.12
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name: DB2 for z/OS
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I'm trying to call STP from DBeaver or Jmeter with the following command example:

@call SCHEMA.STPNAME(
  ${var_in1||AKTIVIER||String||dir=in noshow}$
, ${var_in2||AP||String||dir=in noshow}$
, ${var_in3||XXX||String||dir=in noshow}$
, ${var_out1||(null)||Integer||dir=out noshow}$
, ${var_out2||(null)||String||dir=out noshow}$
, ${var_out3||(null)||String||dir=out noshow}$
);
The strange thing is that in DBVisualizer it's working. I'm using the same jar drivers for all the applications.
#### Include any warning/errors/backtraces from the logs

Unrecognized keyword in escape clause: var_in1||AKTIVIER||String||dir=in noshow. ERRORCODE: -4463, SQLSTATE:42601.

**Comment by LonwoLonwo** [comment]
Hello @atarox 

Please provide error logs: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual - feel free to reopen it with additional info
