### ISSUE TITLE
Result -Set fetch size textbox bug

### ISSUE THREAD

**Issue by phasedephase** [dbeaver/dbeaver#16400]
#### System information: 
- Windows 10 Pro Version: 21H2 OS build: 19044.1586 Experience: Windows Feature Experience Pack 120.2212.4170.0
- 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz   3.60 GHz
- 64 GB of ram
- 3 SSDs, 1 TB each

- DBeaver  22.0.4.202205030312

#### Connection specification:
- Microsoft SQL Server 2016 (SP2-CU15-GDR) (KB4583461) - 13.0.5865.1 (X64) 
	Oct 31 2020 02:43:57 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor)
 EngineEditon: 2 

and 

Microsoft SQL Server 2017 (RTM-CU27) (KB5006944) - 14.0.3421.10 (X64) 
	Oct 14 2021 00:47:52 
	Copyright (C) 2017 Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)
 EngineEditon: 2

- Driver name: Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  Yes: VPN

#### Describe the problem you're observing:

Out-of-mem and/or Java heap space unhandled error. 
Happens with both DB servers.

#### Steps to reproduce, if exist:

1_double click on a table.
2_by default, the value in the Result - Set fetch size textbox is == 200;  change that to 500000 and click Calculate total row count button, which is next to the textbox, on the right.
3_DBeaver starts reloading the data and eventually stalls with either out-of-mem error or Java heap space unhandled error EVEN THOUGH the table contains < 500K rows.

**Comment by ShadelessFox** [comment]
Hello @phasedephase,

Can you please record a video showing the issue? Thanks.

**Comment by phasedephase** [comment]
> Hello @phasedephase,
> 
> Can you please record a video showing the issue? Thanks.

This vid shows me opening the table after having set the fetch size to 500K--it results in a Java Heap Space exception (no out of mem exception this time) after reaching 83K loaded rows:
https://user-images.githubusercontent.com/8108706/166815971-b31bc2ee-5f3e-465d-8f8f-75cbaec9bd6a.mp4

I added this vid because while I was screwing around with the recorder app and stopping/restarting DBeaver I got a Class loader exception... I guess I restarted the app too fast maybe while it hadn't released the lock yet?  But this is an exception that does also occur once in a blue moon under normal use, ie just after launching DBeaver for the first time BUT also already having SSMS running.  It seems as if SSMS and DBeaver are not good neighbors when running at the same time.
https://user-images.githubusercontent.com/8108706/166815996-fffd30b4-633f-472b-968f-9e705bd1aa16.mp4

SSMS info:

SQL Server Management Studio						15.0.18410.0
SQL Server Management Objects (SMO)					16.100.47008.0+9f71e8549924d85d66afcca2b9f45a33061faa1b
Microsoft Analysis Services Client Tools			15.0.19750.0
Microsoft Data Access Components (MDAC)				10.0.19041.1
Microsoft MSXML										3.0 6.0 
Microsoft .NET Framework							4.0.30319.42000
Operating System									10.0.19044

**Comment by phasedephase** [comment]
> Hello @phasedephase,
> 
> Can you please record a video showing the issue? Thanks.

This vid shows me opening the table after having set the fetch size to 500K--it results in a Java Heap Space exception (no out of mem exception this time) after reaching 83K loaded rows--I ran this twice and got 2 diff behaviors:

https://user-images.githubusercontent.com/8108706/166819393-96389090-678b-4bfe-b2ad-5149c814a7a1.mp4
https://user-images.githubusercontent.com/8108706/166819380-46bd2db9-7751-47be-b75d-073f8258db6b.mp4

I added this vid because while I was screwing around with the recorder app and stopping/restarting DBeaver I got a Class loader exception... I guess I restarted the app too fast maybe while it hadn't released the lock yet?  But this is an exception that does also occur once in a blue moon under normal use, ie just after launching DBeaver for the first time BUT also already having SSMS running.  It seems as if SSMS and DBeaver are not good neighbors when running at the same time.
https://user-images.githubusercontent.com/8108706/166819676-97593b81-260a-442a-ac1c-061387a0e216.mp4

SSMS info:

SQL Server Management Studio						15.0.18410.0
SQL Server Management Objects (SMO)					16.100.47008.0+9f71e8549924d85d66afcca2b9f45a33061faa1b
Microsoft Analysis Services Client Tools			15.0.19750.0
Microsoft Data Access Components (MDAC)				10.0.19041.1
Microsoft MSXML										3.0 6.0 
Microsoft .NET Framework							4.0.30319.42000
Operating System									10.0.19044

**Comment by ShadelessFox** [comment]
Thanks for the footage, but it doesn't show how you trigger the data load.

You see, counting the total row count should not cause the viewer to be refreshed, so I assumed you clicked on the blue `Refresh` button rather than the green one located next to the fetch size field.

I did some tests with fetching tables with 100k rows without any success of out-of-memory-ing. Can you please provide the DDL of the problematic table? Maybe it contains BLOBs, CLOBs, and other big chunks of data?

**Comment by phasedephase** [comment]
@ShadelessFox First, my mistake--I made a typo: the table has a total of about 250K rows. 
 Let me now briefly explain how I trigger the load as I am not allowed to show the various DBs and tables.  Basically, after launching DBeaver:

1_  I double click a table, which opens up with the default 200 in the Result -Set fetch size textbox.  
2_  I then change 200 to 500000 and close the tab.
3_  I double click again on the table in the explorer. Everything you see in the vid happens after this. 

As regards the DDL: no BLOBS, CLOBS, or big chunks of data. There is a varbinary(max) column to store screenshots BUT each screenshot (due to format) never exceeds 40KB, so not large by any means.  At time 0:04 of the 2nd vid you can see the column names and data types of each.

In fact I have experienced this issue for quite some time now, so with previous versions as well. Because of this, I always remember to set the fetch size no higher than 450 000 to avoid triggering the exception.  But the other day I forgot and input 500 000 and finally decided to report the bug. ;-)

**Comment by ShadelessFox** [comment]
Thanks for explaining.

This option affects how many rows are loaded into the memory at a time.

In the worst case, it would require up to 3GiB of memory to load 83k rows (assuming each row contains a screenshot, thus ~40KiB/row). Due to boxing and state-keeping overhead, it may take up to 4GiB or even more.

I don't think that fetching THAT amount of rows is necessary. You can always scroll down to see more. Despite the memory problems, it may also affect the performance of the database itself by sending so much data over the network.

I may suggest you increase the `-Xmx` parameter, so DBeaver can consume as much memory as it wants.

**Comment by phasedephase** [comment]
Fair point.  Thanks.

**Comment by ShadelessFox** [comment]
If you have any questions left, feel free to ask them here.
