### ISSUE TITLE
Execute SQL queries always open new result tabs after executing a query in a new tab

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#16402]
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04
- DBeaver version: 22.0.4

#### Connection specification:
- Database name and version: PostgreSQL 13.6
- Driver name: PostgreSQL JDBC driver (version 42.3.4)
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
When I execute a query in a new result tab, all query executions after that always open an new result tab, even if I don't choose the "Execute SQL in a new tab".

#### Steps to reproduce, if exist:
1. Execute a SQL query => the result appears in a single tab.
2. Execute a new query in a new tab => a new result tab appears with the new query
3. Execute a SQL query (not in a new tab) => the result systematically displayed in a new tab.

What I expect is that the last query result appears in the last focused result tab.

I did not find any preference to custom this behavior (but perhaps didn't I find it...).

Kind regards,
Cedric

**Comment by ShadelessFox** [comment]
Hello @ced75,

This behavior was changed in #15126.

Now the confirmation `Close extra result tabs` also affects the execution of a single query.

You can configure it to prompt every time in the <kbd>Preferences</kbd> &rArr; <kbd>User Interface</kbd> &rArr; <kbd>Confirmations</kbd>.

**Comment by ced75** [comment]
Thanks for the answer.
But the behaviour is a little bit different now: you have the choice between close all previous tabs or add a new tab.
Now, it is no more possible to replace the focused tab results with the new query results, as it did before by default.

Is it possible to reintroduce this feature?

**Comment by Xylandor** [comment]
I'd have to agree with @ced75 on this one. There's not a way to execute a query to replace the current tab in focus when multiple tabs already exists. The only options are to replace all tabs or open in new one. An annoying issue is when you run a query in a new tab and something is wrong with the query, the result tab displays the error message. Once you fix the query problem, you can't rerun the query in the same result tab that's displaying the error. You have to run in new tab and close out the tab that previously displayed the error. 

I would suggest that if the setting mentioned by @ShadelessFox is set to Prompt, the question part of the prompt needs to be changed to something like, "What action would you like to perform?" The choices could be:  Close All Tabs, Use Current Tab, Open New Tab, and Cancel.

**Comment by raags** [comment]
Same here - the ability to use the `current` tab is an important part of my workflow when running queries. There is already Ctrl + \ which opens the results in a new tab. Can this be brought back with a configuration option please?

**Comment by E1izabeth** [comment]
We will work on it. Thank you for suggestions.

**Comment by serge-rider** [comment]
Please test that default behavior is the same as before 22.04.
