### ISSUE TITLE
Preset by default automatic order on my tables

### ISSUE THREAD

**Issue by biggio78** [dbeaver/dbeaver#16417]
hi, is possible preset automatic order by column (primary key) for all table on my schema (db postgres) ?

I use dbeaver edition community - Version 22.0.4.202205011839

**Comment by LonwoLonwo** [comment]
Hello @biggio78 

This feature is not implemented yet.
But we have a ticket for this: https://github.com/dbeaver/dbeaver/issues/11140
You can vote there.

I'm closing this ticket as a duplicate.
