### ISSUE TITLE
Additional column info while editing data

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#16412]
as shown...

![dbeaver_table_data_edit](https://user-images.githubusercontent.com/11477081/166721113-ca2608f3-64db-4bb7-969b-dcac2256b814.png)

**Comment by uslss** [comment]
[Metadata panel](https://github.com/dbeaver/dbeaver/wiki/Panels#metadata-panel) could be used in this case. Does it resolve your issue?
![image](https://user-images.githubusercontent.com/31996417/166896306-2adbc6ec-e7b8-43e9-bfb6-adfeb24e74c6.png)

**Comment by plotn** [comment]
yes, patially yes, I missed it, thank you. "Column comment" is missing there. And not so convient, as it could be "in compact mode"

**Comment by uslss** [comment]
Feature request about adding column description: #11054

Also, you can enable Show column description in header option in Preferences
![image](https://user-images.githubusercontent.com/31996417/166941513-992c86ae-9d6a-4567-b18e-8a9166135f07.png)

**Comment by plotn** [comment]
Great!!! Thank you very much!
