### ISSUE TITLE
Dbeaver hangs while trying to edit connection types

### ISSUE THREAD

**Issue by aranapatona** [dbeaver/dbeaver#16415]
#### System information: 
-Windows 10 x64, Version 1709 Build 16299.1087
- DBeaver version 22.0.4
- DevStyle
-  Office  Support

#### Connection specification:
ANY

#### Describe the problem you're observing:
Dbeaver HANGS wjem Trying to change de connection types (DVLP, PROD etc)

#### Steps to reproduce, if exist:
From Window->Preferences Menu
Click Connection Types
![image](https://user-images.githubusercontent.com/19786351/166807602-dbbedd5a-f90b-40f8-8671-bef70821d349.png)

#### Include any warning/errors/backtraces from the logs

I didn't find any useful information in the logs
but while I was writing this I found the cause of the problem
I just used some theme not from Devstyler and I can select connection type without problems
once I choose darkest dark or any other from devstyler, the problem returns
by the way, where should I look for if I wanted to see any log of the crash? (In fact it just hanged and I had to terminate it, naybe no logs that way?)

**Comment by ShadelessFox** [comment]
Hello @aranapatona,

Can you please send a thread dump?

Please follow the instructions here: https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump

**Comment by aranapatona** [comment]
Sure, but as mentioned it happens only when using a them/style from devstyler
[thread-dump.txt](https://github.com/dbeaver/dbeaver/files/8636600/thread-dump.txt)

**Comment by ShadelessFox** [comment]
It looks like the table control is being resized infinitely.

I assume it may happen in multiple places, so I doubt we can easily fix that.

In any case, it's abnormal behavior, but it indeed can be "fixed" by turning off theming. If it doesn't seem critical, let's keep this issue open to see if anybody also has the same problem.

**Comment by uslss** [comment]
verified
