### ISSUE TITLE
run script Not support oracle / syntax

### ISSUE THREAD

**Issue by travelliu** [dbeaver/dbeaver#16429]
#### System information: 
- Operating system: macOS 12.3.1 x86_64
- DBeaver version:  22.0.4 
- Additional extensions

#### Connection specification:

![2022-05-07 at 00 13](https://user-images.githubusercontent.com/7792329/167171646-e8187692-41fa-4415-82ee-9e4fc8ef3bf4.png)

#### Describe the problem you're observing:
![2022-05-07 at 00 13](https://user-images.githubusercontent.com/7792329/167171712-d137349d-f24e-4162-ac5f-62ff574c47ef.png)

![2022-05-07 at 00 12](https://user-images.githubusercontent.com/7792329/167171562-2d98c7f4-d952-40fe-bfc0-1ce8b60933b8.png)

#### Steps to reproduce, if exist:

```sql
CREATE VIEW a1 AS SELECT * FROM dual
/
CREATE VIEW a2 AS SELECT * FROM dual
/
```

**Comment by E1izabeth** [comment]
Hi, @travelliu! DBeaver use `;` as a statement delimiter by default, but you can redefine it in settings:

![image](https://user-images.githubusercontent.com/28875055/167701201-44b8793f-8827-4045-8b4e-f17cc806bfe5.png)

Does it resolve the issue?

**Comment by travelliu** [comment]
tks.
```
CREATE VIEW a11 AS SELECT * FROM dual;
/
CREATE VIEW a12 AS SELECT * FROM dual;
/

CREATE OR REPLACE PACKAGE ORA_MTK.TTTTTT1
AS
-- Package header
FUNCTION testfunc4(var NUMBER) return number;
FUNCTION testfunc5(var NUMBER) return number;
END TTTTTT1;
/

CREATE OR REPLACE PACKAGE BODY ORA_MTK.TTTTTT1
AS
-- Package body
FUNCTION testfunc4(var NUMBER) return NUMBER
IS
BEGIN
    RETURN var;
END testfunc4;
END TTTTTT1;
/
```
Run the above script normally after modification
