### ISSUE TITLE
Find In Data View

### ISSUE THREAD

**Issue by LinWanCen** [dbeaver/dbeaver#16424]
Because input json Is very long, we hope it can use Ctrl + F to find text in this:
![image](https://user-images.githubusercontent.com/14926671/166979084-ea980f9c-4e1e-48d6-b1c8-6805bf80e9bc.png)

**Comment by LonwoLonwo** [comment]
Hello @LinWanCen 

Please try to use right-click on the view area.

![2022-05-05 22_38_34-DBeaver Ultimate 22 0 4 - json_test_json_without_pk](https://user-images.githubusercontent.com/45152336/167012839-2d9ca579-87cc-4d34-bbed-5fd0c2b89fb5.png)

**Comment by LinWanCen** [comment]
Thanks, then this issue is changed to add shortcut keys for find and replace in Value View Area?

**Comment by ShadelessFox** [comment]
Will be implemented in #20336.
