### ISSUE TITLE
Show Column Comment In Record View

### ISSUE THREAD

**Issue by LinWanCen** [dbeaver/dbeaver#16422]
Show comment in this view:
![image](https://user-images.githubusercontent.com/14926671/166978069-4d566582-0bba-46a9-a6ef-ee90868f57a2.png)

This view can show:
![image](https://user-images.githubusercontent.com/14926671/166977928-65b6e988-2afe-4061-bf97-d2189c56d812.png)

**Comment by uslss** [comment]
thanks for the suggestion
duplicates #5529
