### ISSUE TITLE
Save SQL console as script

### ISSUE THREAD

**Issue by kai-morich** [dbeaver/dbeaver#16427]
I changed default 'SQL' command to 'SQL console' instead of 'SQL script', to avoid creating a lot of useless scripts.
If I now have a statement worth saving, I have to create a script and copy from console to script. 
Would be good if the 'SQL console' window header would have a 'Save as Script' to save in 'Project/Scripts' folder. 
Save as real file is already possible.

**Comment by ShadelessFox** [comment]
Hello @kai-morich,

Thanks for the feature request.

The suggested workflow is pretty straightforward. I like it :)
