### ISSUE TITLE
MS SQL autocomplete fails when table-name contains a dot

### ISSUE THREAD

**Issue by Lathoudero** [dbeaver/dbeaver#1642]
MS SQL autocomplete fails when table-name contains a dot.

I know it's unconventional to use a "." in an table-name, but somehow it's permitted by Microsoft, and even autocomplete for table-names works if it contains a dot in the table-name, properly encapsulating the table-name within quotes.
BUT! 
When you want to use autocomplete on column-names, auto-completion fails. 

Example:
database: mydb
table: testtable1[id,name,age], test.table2[id,name,age]

SELECT *
FROM mydb.**_<ctrl+space> autocomplete displays [testtable1,  test.table2], works properly_**

SELECT t.**_<ctrl+space> autocomplete displays [id,name,age]_**
FROM mydb."testtable1" as t

SELECT t.**_<ctrl+space> autocomplete doesn't work_**
FROM mydb."test.table2" as t

**Comment by uslss** [comment]
issue isn't reproducible anymore.
ticket closed.
if issue still actual for you - feel free to reopen the ticket
