### ISSUE TITLE
Dbeaver is throwing error virtual_pk is missing for commented comma

### ISSUE THREAD

**Issue by jaypan13** [dbeaver/dbeaver#16425]
First of all thanks for great software. It helps a lot!

#### System information: 
- Operating system (distribution) and version - Mac Big Sur 
- DBeaver version - 22.0.3.202204170718
- Additional extensions - None

#### Connection specification:
- Database - AWS Aurora
- Driver name - MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No proxies/tunnels

#### Describe the problem you're observing:
Having comment with "," breaks functionality while deleting rows and it shows below error "Attributes of unique key 'VIRTUAL_PK' are missing in result set" 
![image](https://user-images.githubusercontent.com/31636584/167010563-d0f60e20-8ffe-49b3-a0c1-af8f53e5471e.png)
 
#### Steps to reproduce, if exist:
- Use below script to create required test table
- `CREATE TABLE employee_test (
  employee_id int(11) NOT NULL AUTO_INCREMENT,
  employee_name varchar(255) NOT NULL,
  PRIMARY KEY (employee_id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
insert into employee_test(employee_name) values ('test1');
insert into employee_test(employee_name) values ('test2');
`
- Important step - Invalidate/Reconnect connection to your database.
- Run below query as exactly typed with "#," appended on first line 
- `select #,
o.* from employee_test o;`
- Try to delete the rows by selecting all rows in the result panel, clicking on delete rows from status bar and then save.
- 

https://user-images.githubusercontent.com/31636584/167017613-5b1c788b-07bb-4730-9deb-2d8aa9cb593f.mov

Note that this is happening only with Mac version and Windows version works correctly. Although I mentioned latest dbeaver version, it was happening with earlier versions as well.

**Comment by ShadelessFox** [comment]
Hello @Jay1305,

Thanks for the bug report.

Note: I was able to reproduce it on Windows.

**Comment by LiveGood** [comment]
Hi. I have this problem as well:
DBeaver: 22.1.2.202207091909
Mac version: MacOS Monterey 12.1

**Comment by novecentonove** [comment]
I believe it happens when you make a new migration, i believe.
Aniway closing and restarting dbeaver solves the problem.
