### ISSUE TITLE
Separarate message logs with log level.

### ISSUE THREAD

**Issue by carlosromel** [dbeaver/dbeaver#16433]
It would be wonderful if DBEeaver were able to separate log messages into their own tabs, according to their declared levels.

"raise debug     format;" will filter messages into "debug" tab;
"raise log       format;" will filter messages into "log" tab;
"raise info      format;" will filter messages into "info" tab;
"raise notice    format;" will filter messages into "notice" tab;
"raise warning   format;" will filter messages into "warning" tab;
"raise exception format;" will filter messages into "error/output/exception" tab; (current exit guide).

**Comment by ShadelessFox** [comment]
Hello @carlosromel,

Thanks for the feature request.

Just to make things clear: what's your database?

**Comment by ShadelessFox** [comment]
Implemented:

![image](https://user-images.githubusercontent.com/35821147/212953675-1412e307-0a2e-49e3-9e8f-d9f40e4e2b3d.png)

Affected by the `client_min_messages` server option. Effective only after reconnecting.
