### ISSUE TITLE
use variables in connection's driver properties won't work

### ISSUE THREAD

**Issue by braindevices** [dbeaver/dbeaver#16431]
#### System information: 
- Ubuntu20.04
- DBeaver version 22.04

#### Connection specification:
- Mariadb
- mariadb jdbc
- socks 

#### Describe the problem you're observing:
If I use full path in the driver properties it works, but neither ${home} nor ${HOME} work as path.

**Comment by ShadelessFox** [comment]
Hello @braindevices,

Variable resolution is not supported in driver properties.

**Comment by serge-rider** [comment]
We must resolve variables during connect only, see DBPConnectionConfiguration.resolveDynamicVariables

**Comment by Destrolaric** [comment]
I have looked into the issue, and we actually have a variable resolution. It happens when we start connecting to the data source. Fill free to reopen it if you think the issue is still actual.
