### ISSUE TITLE
link phoenix fail

### ISSUE THREAD

**Issue by Felix0209** [dbeaver/dbeaver#16438]
Unexpected driver error occurred while connecting to the database
  java.lang.RuntimeException: class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider
  java.lang.RuntimeException: class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider
    class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider
    class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider

**Comment by LonwoLonwo** [comment]
I'm closing this issue as duplicate of https://github.com/dbeaver/dbeaver/issues/15676

You can read more info about your problem there.
