### ISSUE TITLE
Read Metadata Oracle not properly working (constraints or indexes)

### ISSUE THREAD

**Issue by xtof13** [dbeaver/dbeaver#16442]
#### System information: 
- Operating system : Windows 10 
- DBeaver version : 22.0.4

#### Connection specification:
- Driver name : jdbc8 or TNS

#### Describe the problem you're observing:
`select * from user_indexes;` 
`select * from dba_indexes;`

Both queries are not returning the schema on which I'm connected on.

**Comment by LonwoLonwo** [comment]
Hello @xtof13 

https://docs.oracle.com/cd/B19306_01/server.102/b14237/statviews_1069.htm#i1578369

> USER_INDEXES describes the indexes owned by the current user. This view does not display the OWNER column.

So, what do you mean about "not returning the schema on which I'm connected on"?
Please tell me more about your issue.

**Comment by xtof13** [comment]
Hi LonwoLonwo,

Thanks for your reply.
You're right USER_INDEXES is dedicated for the current user. 
I am connected to an user named 'A'. Column TABLE_OWNER should return the name of current user 'A'. But actually, this column is fullfilled with schema named 'B'.

Then I tried an alternative solution which was to select my indexes with another view : dba_indexes. DBA_INDEXES has duly a column named OWNER within I am supposed to retrieve the right schema.

`SELECT * FROM DBA_INDEXES WHERE OWNER = 'A'`

But there is no results.
I tried to change the connection type to use TNS or jdbc. I tried to select directly the user in the connection parameter but failed also.

**Comment by LonwoLonwo** [comment]
Does you user 'A' have any indexes? Have you tried to connect with user 'B'?
Can you please check other development tools? I'm not sure, that this is DBeaver problem.

**Comment by xtof13** [comment]
Actually user 'A' is a datapump migration of 'B' with EXCLUDE statistics parameter.
I have within 'A' user 56 indexes with ENABLED status.
DBeaver has been my favorite tool since 2018. I've been surprised of the result here. Of course I have double checked with Toad & SQL Developer.
Finally I've restart the computer and guess what, this is working now for trigger, indexes and constraints.
Many Thanks for your support

**Comment by LonwoLonwo** [comment]
Thanks for your reply and investigation @xtof13
