### ISSUE TITLE
Generate DDL from a result set

### ISSUE THREAD

**Issue by ceinmart** [dbeaver/dbeaver#16443]
Hi, 

My suggestion is add an option to generate da simple DDL (create table) based on the data types of the result set. 
This can be very useful when we need to work with data movement and data manipulation where we need to include some result into a new table.
Where the DDL generated already match with the result set in use.

**Comment by ShadelessFox** [comment]
Hello @ceinmart,

Thanks for the feature request. It seems useful.

As a workaround, during Data Transfer, you can use the `Target DDL` button to view the generated DDL. Note that the target must be `Database`.
