### ISSUE TITLE
Export column description in XLSX

### ISSUE THREAD

**Issue by leezm** [dbeaver/dbeaver#16440]
**Is your feature request related to a problem? Please describe.**

I want export data with database column comment replace dafault header.Such as export excel header,show database column comment not the colum name.

**Describe the solution you'd like**

Export data show database column comment.

**Comment by LonwoLonwo** [comment]
Hello @leezm 

You can choose description instead of column name in the format settings of CSV data export in the current DBeaver version.

![2022-05-10 14_07_00-Data Transfer](https://user-images.githubusercontent.com/45152336/167615404-3b0a992d-d021-4c3b-a017-24b30678335a.png)

**Comment by leezm** [comment]
> Hello @leezm
> 
> You can choose description instead of column name in the format settings of CSV data export in the current DBeaver version.
> 
> ![2022-05-10 14_07_00-Data Transfer](https://user-images.githubusercontent.com/45152336/167615404-3b0a992d-d021-4c3b-a017-24b30678335a.png)

It's CSV,how about excel...

**Comment by LonwoLonwo** [comment]
Ok. Thanks for the report.

**Comment by leezm** [comment]
> Ok. Thanks for the report.
Well, another question，when data editor datetime cloumn view as yyyy-mm-dd hh:mm:ss,export xls view is yyyy-mm-dd.I must set then format by my self,is there any other way?
