### ISSUE TITLE
MariaDB: Foreign key "cross reference" of UUID needs to be quoted

### ISSUE THREAD

**Issue by tgross35** [dbeaver/dbeaver#16445]
#### System information: 
- OS: MacOS 12.3.1
- DBeaver version: 22.0.0.202203131528
- Additional extensions: none

#### Connection specification:
- Database name and version: MariaDB 10.7.3
- Driver name: mariadb-java-client-2.7.1.jar / local client MySQL 8.0.28
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH tunnel

#### Describe the problem you're observing:
Clicking the cross reference button <img width="77" alt="image" src="https://user-images.githubusercontent.com/13724985/167527082-3e266141-3cef-4d44-a324-864f1f8e7c6c.png"> opens up a new view, which appears as a SELECT statement. However, the UUID is unquoted which causes an error. Ensuring the UUID is quoted would fix the issue.

<img width="852" alt="image" src="https://user-images.githubusercontent.com/13724985/167512658-b3ec9097-7c0e-45ac-b6d1-c00636e05bca.png">

**Comment by LonwoLonwo** [comment]
Thnaks for the report @tgross35
