### ISSUE TITLE
Ubuntu 22.04 deprecates apt-key

### ISSUE THREAD

**Issue by otbutz** [dbeaver/dbeaver#16457]
Running `apt update` on Ubuntu 22.04 yields the following warning:

```
W: https://dbeaver.io/debs/dbeaver-ce/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

The keyring should be placed in `/usr/share/keyrings/` and the list file updated with the `signed-by` option:

```
deb [signed-by=/usr/share/keyrings/dbeaver.gpg] https://dbeaver.io/debs/dbeaver-ce /
```

**Comment by otbutz** [comment]
This would also follow the Debian guidelines: https://wiki.debian.org/DebianRepository/UseThirdParty#OpenPGP_Key_distribution

> The key MUST be downloaded over a secure mechanism like HTTPS to a location only writable by root, which SHOULD be `/usr/share/keyrings`. The key MUST NOT be placed in `/etc/apt/trusted.gpg.d` or loaded by `apt-key add`.

> A `sources.list` entry SHOULD have the `signed-by` option set.

**Comment by kenhys** [comment]
For the record:

1. download https://dbeaver.io/debs/dbeaver.gpg.key
2. convert it to keyring

```
% apt-key --keyring ./dbeaver-keyring.gpg add dbeaver.gpg.key
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
```

3. setup .list as /etc/apt/sources.list.d/dbeaver-ce.list

```
% sudo cat /etc/apt/sources.list.d/dbeaver-ce.list
deb [signed-by=/usr/share/keyrings/dbeaver-keyring.gpg] http://dbeaver.io/debs/dbeaver-ce  /
```

**Comment by E1izabeth** [comment]
Wiki was corrected.
