### ISSUE TITLE
DBeaver CSV to Table import. How to do scripted without import Wizard?

### ISSUE THREAD

**Issue by JGFMK** [dbeaver/dbeaver#16453]
I have a table I routinely want to drop, then re-import and add a primary key constraint for.
The thing is I don't want to step thru the wizard each time.
How can I script this as a command so I don't need to interact with a GUI/wizard?
If it is of significance I am using PostgreSQL on a Mac
(Also your authentication mechanism with bastard re-captcha is broken at https://dbeaver.com/signin/ )
1) I tried to sign up
    It said I have an account
2) I tried forgot password option
    Sent not activated.
3) I go to email, and click activate link
    Says invalid activation
4) I try to login with my Google account... takes me back to step 3.. infinite loop.. infinite recaptcha crap with increasiningly time consuming clicks. I gave up in frustration.

**Comment by LenaVu** [comment]
Hello @JGFMK 

Your account has been activated. Now you can reset a password https://dbeaver.com/forgot/.

**Comment by ShadelessFox** [comment]
Hello @JGFMK,

You can use the `SQL Script` task to drop and create a unique key constraint in pair with the `Data Import` task.

To combine them, you can use [composite tasks](https://github.com/dbeaver/dbeaver/wiki/Composite-Tasks).

Please let me know if it solves your issue.

**Comment by JGFMK** [comment]
https://stackoverflow.com/questions/72198931/dbeaver-csv-to-table-import-how-to-do-scripted-without-import-wizard
A comment someone posted here gave me the info I needed. Haven't used PostreSQL for ages. But comment I posted under question meant I could solve problem. Happy for you to close this item now.
