### ISSUE TITLE
crash on editding connection settings

### ISSUE THREAD

**Issue by palytoxin** [dbeaver/dbeaver#16455]
#### System information: 
- Linux nuc 5.15.32-1-MANJARO SMP PREEMPT Mon Mar 28 09:16:36 UTC 2022 x86_64 GNU/Linux
- Version 22.0.4.202205011839

#### Connection specification:
Mysql / PostgreSQL / oracle and so on...
sometimes has HTTP proxy

#### Describe the problem you're observing:
on any connection, right click, edit connection and nothing to do, then press ESC or click cancel or click OK.
the app is crash. 
Error stacks sometimes report errors differently.

#### Include any warning/errors/backtraces from the logs

[hs_err_pid53954.log](https://github.com/dbeaver/dbeaver/files/8670315/hs_err_pid53954.log)
[hs_err_pid54424.log](https://github.com/dbeaver/dbeaver/files/8670316/hs_err_pid54424.log)
[hs_err_pid59965.log](https://github.com/dbeaver/dbeaver/files/8670317/hs_err_pid59965.log)
[hs_err_pid61415.log](https://github.com/dbeaver/dbeaver/files/8670318/hs_err_pid61415.log)

and the video shows what happene

https://user-images.githubusercontent.com/1829328/167861417-bae37929-7b13-4aa9-8790-0032e305565e.mp4

**Comment by palytoxin** [comment]
It's print log has  `Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found` everytime.

1. I checked #7296 , then rm `rm ~/.local/share/.DBeaverData/workspace6/<project name>/.dbeaver/.data-sources.json.bak`
2. I try to remove all dbeaver config files, and try to reinstall dbeaver / install from official tar.gz / install from archlinux pacman source / change zulu,OpenJDK, oraclejdk.

the bug is still there.

**Comment by ShadelessFox** [comment]
Hello @palytoxin,

Thanks for the bug report.

Which distribution of DBeaver are you using?

Note: It looks like a duplicate of #12422.

**Comment by palytoxin** [comment]
hi @ShadelessFox 
I'm using Community Edition 22.0.4 (Version 22.0.4.202205011839)
It's downloaded from `https://dbeaver.io/download/`

but I'm using Manjaro 21.2.6 + i3wm not Gnome, gtk3:3.24.33-3.0 / gtk2 2.24.33-2

And it is a duplicate of https://github.com/dbeaver/dbeaver/issues/12422
sorry for I didn't find that issue

**Comment by ShadelessFox** [comment]
There are various types of distributions (RPM, DEB, Snap, Flatpack). Which one did you install?

**Comment by palytoxin** [comment]
[Linux (zip)](https://dbeaver.io/files/dbeaver-ce-latest-linux.gtk.x86_64.tar.gz)

untar and exec it @ShadelessFox

**Comment by palytoxin** [comment]
Is there any update, please?

after updated Version 22.1.2.202207091909
I got some new log at this issue
```
2022-07-12 13:25:33.555 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
**
GLib-GObject:ERROR:../glib/gobject/gsignal.c:750:handler_unref_R: assertion failed: (hlist->tail_before == handler)
Bail out! GLib-GObject:ERROR:../glib/gobject/gsignal.c:750:handler_unref_R: assertion failed: (hlist->tail_before == handler)
```

**Comment by palytoxin** [comment]
the bug has been fixed, after upgrade manjaro new glibc
