### ISSUE TITLE
Export from view needs to split outfiles into multiple <=1GB size. 

### ISSUE THREAD

**Issue by ricksrose** [dbeaver/dbeaver#1646]
I have 3.1 M records to output into CSV format files for ingest into another system.
I've had to create multiple views to limit the rows for each file.
When the files are split, it must be on a row boundary such that a row is never split between files.

Thanks,
Rick Rose

**Comment by uslss** [comment]
verified

**Comment by mikkk3l** [comment]
Thank you, Serge. You're great.
For the record, file size is in Bytes. A literal or even a selector to choose between KB, MB or GB will be awesome!
