### ISSUE TITLE
Close all button

### ISSUE THREAD

**Issue by MiiChielHD** [dbeaver/dbeaver#16464]
I have too many table windows open

I woulde like to close them all once

I am able to clicking them one by one, or mashing ctrl-w;

**Comment by ShadelessFox** [comment]
Hello @MiiChielHD,

Are you talking about editor tabs or result tabs?

**Comment by MiiChielHD** [comment]
![afbeelding](https://user-images.githubusercontent.com/105423552/168070556-e138eb1c-3d2a-4ea7-9a58-1d946dab0ef3.png)
I mean the tabs that correspond to a table, a query etc,

**Comment by ShadelessFox** [comment]
I'm a little bit confused since there's such an action:

![java_FCMNtBQ5Jp](https://user-images.githubusercontent.com/35821147/168077463-314c7d2e-de70-408d-bb1b-6158606d34c7.png)

**Comment by MiiChielHD** [comment]
Ah! I was searching for it at File, Close... Okay then you can close the this topic :)
