### ISSUE TITLE
Pause After Execute (ms) Input Box Not Saving Changes

### ISSUE THREAD

**Issue by ggrant005** [dbeaver/dbeaver#16463]
#### System information: 
- Operating system (distribution) and version: **MacOS Monterey Version 12.3.1**
- DBeaver version: **22.0.4.202205011839**
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Changes to the `Pause After Execute (ms)` value in Shell Commands often does not get saved on exit from the menu.  I have successfully made changes stick after many attempts by changing other items around the menu, though none were obviously reproducible.

<img width="721" alt="Screen Shot 2022-05-11 at 3 16 38 PM" src="https://user-images.githubusercontent.com/12126752/167956988-7cfe888a-aa5e-4999-8216-74b94f7716b2.png">

#### Steps to reproduce, if exist:
1. Edit Connection on a preexisting DB connection
2. Connection Settings > Shell Commands > Before Connect
3. Modify or enter a value in `Pause After Execute (ms)` entry box
4. Press OK
5. Repeat Steps 1-2
6. 9/10 times the value has returned back to before the changes in Step 3

**Comment by ggrant005** [comment]
Reproduced: Modifying the Command string (removing a letter, etc.) and changing the Pause value will result in a saved change to the Pause value

**Comment by uslss** [comment]
thanks for the report
