### ISSUE TITLE
Connection Properties in inconsistent state after cancelling an operation from within the "edit connection" dialog

### ISSUE THREAD

**Issue by csiberlin** [dbeaver/dbeaver#16477]
I found a bug:
 
1.	Create a read-only-connection
2.	Open SQL-Editor and type something.
3.	Edit the connection, and uncheck the read-only checkbox
4.	When the question pops up, click “Cancel”
![image](https://user-images.githubusercontent.com/5721129/168249498-65f7a545-df4f-4414-8b11-bceba7e52cc6.png)
5.	The connection is still read-only. However, if you open the connection tab using “edit connection” again, the checkbox is unchecked (but we are still using the read/only connection)

In general this happens whenever you cancel the pending “reconnect with changed settings” process.

**Comment by E1izabeth** [comment]
Thank you for bug report. It happens because we can't change connection type without reconnect, but checkbox state should be synchronized with the actual connection state.
