### ISSUE TITLE
网络不稳定（不确定一定是）时，数据库下的表展示不出来

### ISSUE THREAD

**Issue by ShisanXing** [dbeaver/dbeaver#16475]
网络不稳定时百分百复现，网络稳定时有几率复现，经常性的表没了，这个问题也存在了N年，就不想着好好修复下？难用的要死
![image](https://user-images.githubusercontent.com/18689511/168226293-0a88ced6-61a8-4729-9313-343bcd6283fd.png)

**Comment by E1izabeth** [comment]
Hi, @ShisanXing! Which DBeaver version do you use?

**Comment by TA961215** [comment]
@E1izabeth  hello,我也遇到相同的情况，DBeaver版本22.0.0.202203131528，，，
![image](https://user-images.githubusercontent.com/48305781/168566290-309bd77b-e38a-400d-9c4a-31dca837562d.png)

**Comment by LonwoLonwo** [comment]
Did you try to use refresh button on the schema/database/tables?

![2022-05-17 23_29_39-DBeaver Ultimate 22 0 5](https://user-images.githubusercontent.com/45152336/168904746-a4da9e9f-9261-4304-9d70-72c41dc8738c.png)

**Comment by E1izabeth** [comment]
@TA961215, could you, please, send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.
Thank you.

**Comment by TA961215** [comment]
> @TA961215, could you, please, send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.
我在这边解决了。DBeaver  version：22.0.0，Clickhouse version：20.8.18.32，连接时默认下载驱动clickhouse-jdbc版本是0.3.2，把驱动版本手动降为0.2.6就好了，感谢

**Comment by E1izabeth** [comment]
Please, attach the log file. To know how to find it, see https://dbeaver.com/docs/wiki/Log-files/

**Comment by uslss** [comment]
there has been no update on the issue for a long time.
If it is still actual - feel free to reopen it.
