### ISSUE TITLE
Add Ukrainian language

### ISSUE THREAD

**Issue by zvlad** [dbeaver/dbeaver#16473]
Add the Ukrainian language! I can help with translation.

**Comment by HTML-Jeday** [comment]
Add Ukrainian language!

**Comment by codeprowess** [comment]
Commenting to cast my support.

**Comment by uslss** [comment]
Thanks for the suggestion! We are always glad to have new contributors. You can find the localization guide [here](https://github.com/dbeaver/dbeaver/wiki/Localization).

**Comment by CrazyTapok-bit** [comment]
I support Ukrainian language is required

**Comment by CrazyTapok-bit** [comment]
@uslss I'm trying to follow the instructions you linked to, but I'm stuck at a point [eclipse-ide](https://github.com/dbeaver/dbeaver/wiki/Localization#eclipse-ide)

![image](https://github.com/dbeaver/dbeaver/assets/61122611/2f79ea80-0526-4010-94e3-d92e009cac83)


Maybe something has changed? I want to contribute, how do I do it?

**Comment by CrazyTapok-bit** [comment]
I'll leave it here, maybe someone will find it useful

At first I couldn't deploy the project to contribute, but then the instructions [here](https://dbeaver.com/docs/dbeaver/Develop-in-Eclipse/) helped me. It is more detailed and should be done before the steps described [here](https://github.com/dbeaver/dbeaver/wiki/Localization#eclipse-ide)

@zvlad, @codeprowess join)

**Comment by LonwoLonwo** [comment]
Hello @zvlad 

Work still needs to be done. So, I reopen this issue.

**Comment by volodymyrchernyshev** [comment]
I would like to help. 
Слава Україні

**Comment by CrazyTapok-bit** [comment]
> Слава Україні

Героям слава!

**Comment by volodymyrchernyshev** [comment]
Half way done. I'm planning to finish it during this weekend.

**Comment by volodymyrchernyshev** [comment]
Please review https://github.com/dbeaver/dbeaver/pull/21824

**Comment by zvlad** [comment]
There is no Ukrainian language in version 23.2.5 yet?

**Comment by LonwoLonwo** [comment]
Hello @zvlad 
We are always glad to have new contributors. 
Or you can help with translation here: https://github.com/dbeaver/dbeaver/pull/21768
You can find the localization guide [here](https://github.com/dbeaver/dbeaver/wiki/Localization).

**Comment by zvlad** [comment]
Пройшов майже рік з дня запиту і так не додали переклад.
За цей час перейшов на antares які додали українську мову відразу (прийняли мій переклад).
І ця програма (antares) безкоштовна.
Все, цей запит щодо українізації не актуальний більше.
Дякую, що протягом року щось відповіли :)
Можете не додавати українську мову.

**Comment by CrazyTapok-bit** [comment]
> Можете не додавати українську мову.

Треба слідкувати за змінами, а ще краще допомогати з перекладом, який вже майже завершений [в цьому запиті](https://github.com/dbeaver/dbeaver/pull/21768). Ви кажете ніхто нічого не зробив, хоч ви просили. Я теж вас просив допомогти мені з перекладом. Ви допомогли? Ні!

@LonwoLonwo також писала вам що робити ведуться, і запрошувала вас допомогти. А ви тупо проігнорили. Зате закрити запит і поскаржитись то це ви перший

Менше говоріть, більше робіть!!!!

**Comment by LonwoLonwo** [comment]
Thank you for your attention to our product @zvlad. We grow and try to be better for everyone. 
We quickly cope with some improvement tasks, but some tasks require more time. This is one of them.

Thanks to @CrazyTapok-bit, work on localization is underway right now, and this work still needs to be completed. Therefore, I will reopen this ticket.

Please be patient, and then we can implement this improvement soon.

**Comment by zvlad** [comment]
> > Можете не додавати українську мову.
> 
> Треба слідкувати за змінами, а ще краще допомогати з перекладом, який вже майже завершений [в цьому запиті](https://github.com/dbeaver/dbeaver/pull/21768). Ви кажете ніхто нічого не зробив, хоч ви просили. Я теж вас просив допомогти мені з перекладом. Ви допомогли? Ні!
> 
> @LonwoLonwo також писала вам що робити ведуться, і запрошувала вас допомогти. А ви тупо проігнорили. Зате закрити запит і поскаржитись то це ви перший
> 
> Менше говоріть, більше робіть!!!!

Якщо буде json формат файлу з перекладом, то допоможу. А ставити непотрібні мені програми і тільки для цього перекладу - не хочу. Я веб-розробник, а не софт.

**Comment by CrazyTapok-bit** [comment]
> Якщо буде json формат файлу з перекладом, то допоможу.

Як ви кажете це софт, а не веб. Я також звик до .json. Але повірте, працювати з .properties так само легко.😎

> А ставити непотрібні мені програми

Це ж всього лиш IDE, така сама як PHPStorm чи VSCode. Її легко можна видалити коли вона стане не потрібна😉

> тільки для цього перекладу

Я роблю це не заради самого перекладу як файлу, а заради розвитку української мови і викорінення совка

**Comment by LonwoLonwo** [comment]
It will be implemented in the next sprint - 23.3.2 (08.01.2024)

Thanks, @CrazyTapok-bit, for the contribution!
