### ISSUE TITLE
Add "Digit group size" option for numbers data formatting

### ISSUE THREAD

**Issue by moontide** [dbeaver/dbeaver#16479]
**Is your feature request related to a problem? Please describe.**
None, but it can provide better internationalization support.

**Describe the solution you'd like**
Add an input component "`Digit group size`" when "Use Grouping" is checked:
A drop down list box, which contains at least two options:
 * 3
 * 4

**Describe alternatives you've considered**
Or, a combo box, which contains least two options: 3 and 4, and allow user input a custom `java.text.DecimalFormat` pattern string in it.

**Additional context**
https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping

**Comment by ShadelessFox** [comment]
Hello @moontide,

Thanks for the feature request.
