### ISSUE TITLE
expect postgres text type to display string value

### ISSUE THREAD

**Issue by sakka6868** [dbeaver/dbeaver#16487]
When I use postgres to save text type，as the picture shows
![image](https://user-images.githubusercontent.com/23228684/168574728-a0abff07-61d6-467b-b02e-aa70893aa934.png)
my data type
![image](https://user-images.githubusercontent.com/23228684/168574868-2fbe4e9d-708b-4bcc-8cf2-1c324ba2c8ab.png)
the value i inserted
![image](https://user-images.githubusercontent.com/23228684/168574975-5ec52ff3-ee42-4296-8e41-6e8e76b9a680.png)

**Comment by E1izabeth** [comment]
Hi, @sakka6868! Thank you for report.
Is this method in the screenshot used to save the _"test"_ value to the `value2` column, or are you trying to insert the _source code_ from the screenshot into the value 2 column?

**Comment by E1izabeth** [comment]
Have you tried to Refresh data editor?

**Comment by uslss** [comment]
There has been no update on the issue for a long time.
If it is still actual - feel free to reopen it with additional info,
