### ISSUE TITLE
null inserted between the character values?

### ISSUE THREAD

**Issue by rmpbklyn** [dbeaver/dbeaver#16484]
when import data , in sqlite there are null characters, unable to use like in query. why were null inserted between the character values?

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by ShadelessFox** [comment]
Hello @rmpbklyn,

Unfortunately, It's not clear what you are talking about.

Can you please provide footage showing the issue? Thanks.

**Comment by rmpbklyn** [comment]
when a value in a column should be 'Mary Jane' its displayed 'M a r y J a n e'  which makes it difficult to use the like command to filter. occurs for all text columns, not datetime or numbers. the export also will have  Mnullr.......  eg look at symbols in text editor

**Comment by ShadelessFox** [comment]
It's still unclear what the issue is.

Does it occur when importing data into a table from an external file?

**Comment by rmpbklyn** [comment]
yes during import

**Comment by Xylandor** [comment]
@rmpbklyn 

Could you provide us the OS name and version you are running, as well as the DBeaver version? 

Also, could you provide a sample of the type of external file you are using for your source data, that includes test values that will produce the same results you are getting? I want to use it to see if I can reproduce the problem.

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual, feel free to reopen it.
