### ISSUE TITLE
Configuration option - don't automatically open problems view

### ISSUE THREAD

**Issue by kit-johnson** [dbeaver/dbeaver#16483]
#### System information: 
- Operating system Windows 10
- DBeaver 22.0.4

#### Describe the problem you're observing:

When I make a syntax error in the SQL editor and run the query, it automatically opens a "Problems" view, every time. I don't want to see this view as I can already see the problem in the "Results" view. I find it annoying to have to manually close the problems view each time when I never wanted to see it in the first place.

Is there a way to configure dbeaver so that it doesn't automatically open a "Problems" view every time?

**Comment by ShadelessFox** [comment]
Hello @oldmankit,

Thanks for the report.

Please track issue progress in #15992.
