### ISSUE TITLE
SQLCipher "PRAGMA rekey=" completely blocks access to database

### ISSUE THREAD

**Issue by jet2** [dbeaver/dbeaver#16482]
#### System information: 
- OS Windows 10 Home 21H1
- DBeaver version 22.0.4
- Additional extensions NO

#### Connection specification:
- Database SQLite
- Driver SQLCipher sqlite-jdbc-3.38.1.jar OR sqlite-jdbc-3.34.1.jar
https://github.com/Willena/sqlite-jdbc-crypt/releases?page=2
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Enabling encryption by the keyphrase with the "Pragma rekey=<key>" command completely blocks access to the database:
SQL Error [26]: [SQLITE_NOTADB]  File opened that is not a database file (file is not a database)
DBeaver properly open database encrypted by other tools, but corrupt this database by running same PRAGMA encryption commands.
#### Steps to reproduce, if exist:
1. Add Generic Driver with library sqlite-jdbc-3.38.1.jar OR sqlite-jdbc-3.34.1.jar. 
2. Set options for driver 
Class = org.sqlite.JDBC
Template = jdbc:sqlite:{file}
Driver Properties :
					"cipher": "sqlcipher",
					"hmac_algorithm": "2",
					"legacy": "4",
					"hmac_pgno": "1",
					"hmac_use": "1",
					"plaintext_header_size": "0",
					"fast_kdf_iter": "2",
					"hmac_salt_mask": "0x3a",
					"kdf_iter": "256000",
					"legacy_page_size": "4096"
3. Create database by new driver. Then create table T1 with only one integer field F1.
4. Enable encryption by execute script PRAGMA rekey='123'.
5. Change connection property 'key' to 123.
6. ReConnect Database.
#### Include any warning/errors/backtraces from the logs

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/8691289/dbeaver-debug.log)

**Comment by ShadelessFox** [comment]
Hello @jet2,

SQLite Crypt has native support in DBeaver Enterprise. Can you please verify that the issue is either present or gone there?

https://dbeaver.com/files/ea/

**Comment by jet2** [comment]
Hey! Sorry, I tried to switch to English 2 times, but the interface
remained in Russian. So, with the listed values of the driver keys,
everything works well: creation with a passphrase, pragma rekey. There are
no such problems that were encountered in the Community Edition. However,
the connection settings on the main tab are filled with incorrect values
when SQLCipher 4 is selected. The correct values are in the picture. With
such values, the created database opens correctly in other software. Many
thanks for DBeaver!!!!
[image: image.png]

ср, 18 мая 2022 г. в 16:35, ShadelessFox ***@***.***>:

**Comment by emironovDB** [comment]
Hello @jet2,

Have you tried changing default driver parameters? What DBeaver version and edition do you use?

**Comment by jet2** [comment]
>Have you tried changing default driver parameters?
Yes, I did. Try to compare my parameters with default. You will see the
problem.
My trial has expired. Now I can't show the problem by screenshot.
My version
[image: image.png]


ср, 8 июн. 2022 г. в 15:41, emironovDB ***@***.***>:

**Comment by ShadelessFox** [comment]
Of course some of the parameters will be messed up.

That's why you can set up custom cipher parameters:

![image](https://user-images.githubusercontent.com/35821147/172774041-c3ccf900-41bf-4263-8ec0-4c739e101917.png)

**Comment by LonwoLonwo** [comment]
Hello @jet2 

> Hey! Sorry, I tried to switch to English 2 times, but the interface
remained in Russian. So, with the listed values of the driver keys,
everything works well: creation with a passphrase, pragma rekey. There are
no such problems that were encountered in the Community Edition. However,
the connection settings on the main tab are filled with incorrect values
when SQLCipher 4 is selected. The correct values are in the picture. With
such values, the created database opens correctly in other software. Many
thanks for DBeaver!!!!
[image: image.png]

Can you please provide the image from this message again? Here on the GitHub page, not from the e-mail.

**Comment by jet2** [comment]
![image](https://user-images.githubusercontent.com/24220126/180250279-87c027ad-2446-4690-bf04-0af7d230a4bf.png)

**Comment by LonwoLonwo** [comment]
Ok, thanks.

So. I created the database with DB Browser for SQLite with SQLCirher4 encryption. I used this instruction:
https://gist.github.com/thecodingcod/a3987ddde8892d1a6bda8bd94febb7d0
added a new driver with Driver Manager with all properties and opened the database. 
After that, I executed PRAGMA rekey='123', disconnected from the database, changed the key to 123 in properties, and... I can connect to my database again. I can't reproduce your issue.

Maybe I missed some steps?

![2022-07-21 18_45_28-DBeaver 22 1 2 - _sqlite_cript db_ Script-34](https://user-images.githubusercontent.com/45152336/180258381-02cd6b22-072c-4979-9fba-4c302e7544cf.png)

**Comment by LonwoLonwo** [comment]
Also, did you try to use this driver in the DBeaver EE version?

![2022-07-21 18_54_15-Connect to a database](https://user-images.githubusercontent.com/45152336/180259040-d6585cac-f037-45e9-b209-f89e26d36116.png)

![2022-07-21 18_54_03-Connect to a database](https://user-images.githubusercontent.com/45152336/180259038-70b76b23-659f-4ca0-b4b7-b52c4bdebb32.png)

**Comment by jet2** [comment]
![image](https://user-images.githubusercontent.com/24220126/180472630-c6e36ad0-5fb4-4c2e-a0dc-392fa00b9b9a.png)

**Comment by LonwoLonwo** [comment]
Maybe you can provide me with an encrypted sample database, please?
On sqlcipher4.
You can send it to my e-mail: anastasiia.volkova@dbeaver.com

**Comment by uslss** [comment]
Is the issue still actual?
