### ISSUE TITLE
Auto-completion not working properly

### ISSUE THREAD

**Issue by sushruta19** [dbeaver/dbeaver#16481]
#### System information: 
- Operating system (distribution) and version : Ubuntu 20.04.4 LTS
- DBeaver version : 22.0.4

#### Connection specification:
- Database name and version : mysql Version 8.0.29-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu)) 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : NO

#### Describe the problem you're observing:
![issue](https://user-images.githubusercontent.com/103309163/168337774-27f978de-0208-46ea-b1ef-4b0f8fa4c0c7.gif)

If the unreserved word has one or more than one word separated via underscore or hyphen, the initials of the words come up during auto completion.

**Comment by ShadelessFox** [comment]
Hello @sushruta19,

This is expected behavior. The called initials are alias of the table.

Alias autocompletion can be configured in the preferences:

![image](https://user-images.githubusercontent.com/35821147/168455940-723a099e-a4f8-4fee-b7ff-551e4d0fef5f.png)
