### ISSUE TITLE
Accessing SQL Server Jobs 

### ISSUE THREAD

**Issue by jrich8573** [dbeaver/dbeaver#1651]
I am using Eclipse Neon, with the dbeaver plugin, I am looking to access SSMS SQL job agent. I do not see a link or directory within the database navigator.  Is there a known method for access the SQL job agent in Eclipse using the dbeaver plugin?  

Thank you

**Comment by islamanwar** [comment]
Is this available in dbeaver?

**Comment by MarkFergusonTN** [comment]
Is there a way to "upvote" this feature?

**Comment by LonwoLonwo** [comment]
Hello @MarkFergusonTN 

I've already added this ticket in 21.3.1 Milestone, which is dedicated to the metadata. It means, that our team takes this task to work.

**Comment by ShadelessFox** [comment]
Implemented as a part of the Enterprise Edition.

**Comment by uslss** [comment]
verified

**Comment by MarkFergusonTN** [comment]
Just to make sure I understand, the ability to see/work with SQL Server Agent jobs is now part of the Enterprise edition of DBeaver?

**Comment by ShadelessFox** [comment]
@MarkFergusonTN yes.

**Comment by LonwoLonwo** [comment]
@MarkFergusonTN and part of DBeaver Lite Edition too.

**Comment by MarkFergusonTN** [comment]
Great! Thank you so much!

**Comment by MarkFergusonTN** [comment]
Is there any documentation on how to do this in the Lite Edition yet?
