### ISSUE TITLE
Added create oracle partition table  feature

### ISSUE THREAD

**Issue by travelliu** [dbeaver/dbeaver#16517]
**Is your feature request related to a problem? Please describe.**

Now the Gui cannot create partitioned tables, add, delete, split partitions and subpartitions

**Describe the solution you'd like**

1. The interface can create partitioned tables
2. Partitions/subpartitions can be added
3. Partitions/subpartitions can be deleted
4. Split partitions/subpartitions can be made

**Comment by LonwoLonwo** [comment]
It will be not so easy. But we can try.

Thanks for the suggestion @travelliu

**Comment by LonwoLonwo** [comment]
Some additional links: https://docs.oracle.com/database/121/VLDBG/GUID-0E7205A9-5D01-4642-B7E9-02406200493E.htm
https://docs.oracle.com/en/database/oracle/oracle-database/12.2/vldbg/evolve-nopartition-table.html#GUID-5FDB7D59-DD05-40E4-8AB4-AF82EA0D0FE5

**Comment by travelliu** [comment]
> It will be not so easy. But we can try.
> 
> Thanks for the suggestion @travelliu

tks. It can be implemented in stages, first create a partition table

**Comment by travelliu** [comment]
@LonwoLonwo truncate table partition Not considered update global index.  without  update global index global index change to invalid
![2023-12-15 at 15 24](https://github.com/dbeaver/dbeaver/assets/7792329/afb3e5fb-0a18-4faf-8c2a-025b4cc47194)

**Comment by LonwoLonwo** [comment]
It looks like you can do it before truncating. Manually. @travelliu

**Comment by travelliu** [comment]
> It looks like you can do it before truncating. Manually. @travelliu

Yes, I just found this issue prompted below
