### ISSUE TITLE
ERD Editor

### ISSUE THREAD

**Issue by TomJoyal** [dbeaver/dbeaver#16516]
#### System information: 
- Windows 10 Enterprise
- DBeaver 5.1.3

#### Connection specification:
- Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
ERD: I have a database with 1003 tables and generated the ERD. I then spent hours moving tables around to make it readable. Saved my work. And luckily printed it out. A few days later, opened the ERD project, and all of my arrangement work was GONE - it had reverted to "auto-arranged" which is useless. This needs to be able to save positioning long-term...

**Comment by Matvey16** [comment]
Hello @TomJoyal Have you seen if the button "Keep layouot" was enabled after you saved your diagram? I'm not sure it worked in 5.1.3 version the same way it works now

**Comment by uslss** [comment]
there has been no update on the issue for a long time.
If it is still actual - feel free to reopen it.
