### ISSUE TITLE
Allow to execute script with output to file/one tab

### ISSUE THREAD

**Issue by yoni-yad2** [dbeaver/dbeaver#16518]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to generate a script from multiple commands' output but they open many tabs if I run them as a script.

**Describe the solution you'd like**
Add an Execute to file / single tab option

**Describe alternatives you've considered**
Running the commands in mysql shell.

**Comment by ShadelessFox** [comment]
Hello @yoni-yad2,

Thanks for the feature request.

Closing as a duplicate of #667, please track the issue progress there.
