### ISSUE TITLE
Issues when opening DBeaver

### ISSUE THREAD

**Issue by jgalvan0815** [dbeaver/dbeaver#16524]
Hello - I'm working with a user who is having issues trying to open DBeaver after a recent Windows update. I had the user gather the logs for me and have attached, any insight would be greatly appreciated. 

[log.txt](https://github.com/dbeaver/dbeaver/files/8718449/log.txt)

**Comment by aditya-giri** [comment]
I'm unable to open DBeaver after the recent Windows update too.

**Comment by emironovDB** [comment]
Hello @jgalvan0815 @aditya-giri,

Can you please try uninstalling and installing DBeaver from scratch?

If it doesn't help, try resetting the workspace: https://github.com/dbeaver/dbeaver/wiki/Reset-workspace

Please let me know if it helps

**Comment by aditya-giri** [comment]
Hi @emironovDB, thanks for your response.

I did initially try uninstalling and reinstalling but that did not help either. I will try resetting the workspace and let you know shortly.

Is there anything else I can do? Perhaps attach some logs?

**Comment by jgalvan0815** [comment]
I worked with my end user and what we discovered was the following:

- We uninstalled and reinstalled DBeaver and it did not work
- We uninstalled DBeaver and deleted the folder in AppData where the log was stored and reinstalled DBeaver
- The program was able to run but it looks like the user lost their shortcuts, which they were able to set back up again

**Comment by emironovDB** [comment]
DBeaver does not backup workspace data outside the workspace itself. So before deleting it, it would be better to create a backup or more it somewhere else instead.

Since the original issue was resolved, I will close it.
