### ISSUE TITLE
Visual Query Builder

### ISSUE THREAD

**Issue by osrojas** [dbeaver/dbeaver#1652]
Hi,

Can you implement a visual query builder in DBeaver? This is the only huge feature missing that others like Aqua Data Studio, DBVisualizer, etc. have that DBeaver doesn't. Would this be difficult to implement?

**Comment by serge-rider** [comment]
Good feature. But yes, quite difficult to implement.

**Comment by osrojas** [comment]
Is it possible to have this planned for the next major release?

**Comment by GiantCrocodile** [comment]
Is this really necessary? I thought about this too but then I thought of moments when I ever used a query builder ... it was like never. It just made stuff even more complicated to me. Although, if you think this is needed - I don't want to prevent you from suggesting it :).

**Comment by serge-rider** [comment]
Definitely not in 4.1. But maybe in 4.2

**Comment by osrojas** [comment]
I am requesting this feature on behalf of my company where there are several departments who utilize this feature extensively and is the only reason Aqua Data Studio is the preferred choice. It'd be great if you can get something like this in a 4.2 release. :)

**Comment by TesseractE** [comment]
I work with osrojas, and I'd like to address GiantCrocodile's comment...  I rarely use the ADS Query Builder myself, but that's because I'm comfortable writing directly in SQL.  We're trying to ease some not-so-SQL savvy users into making their own direct requests though, and ADS's Query Builder has been really helpful in driving that adoption.  Right now, that lack of accessibility is the only major thing keeping us from fully embracing DBeaver.

**Comment by kimdobranski** [comment]
I would like this also. Sometimes we have build complicated joins and its much quicker visually.

**Comment by fraxen** [comment]
This is the only feature I miss from Dbeaver!
(Which is a great piece of software - thanks for all the hard work!)

**Comment by PedroSolintel** [comment]
+1 for this feature. I'd like to see it on DBeaver, too.

**Comment by skaos** [comment]
+1

**Comment by serge-rider** [comment]
We have started to work on it. But most likely we won't do this till version 5.1 (release in June).

**Comment by johnlmiller** [comment]
Is this still targeted for 5.1 release in June?  I have a set of business users who need a replacement tool after losing their Toad licensing due to budget constraints.

**Comment by serge-rider** [comment]
Unfortunately we can't include this in 5.1. This is too raw.
Visual Query builder will be the main feature for the next major release (as it is requested by lots of people).
First implementations will be included in EA versions soon.

**Comment by n-osennij** [comment]
+1

**Comment by dmcveay** [comment]
Definite +1 on this needed attribute.   We recommend DBeaver to all of our 3rd party access customers and  many are not confident writing queries directly and on joins and unions etc  and this would be a win for them.     Personal Note-  all of the employee's in the group i work with use DBeaver 10+ hours a day and having this would make DB much better than the competition , hands down

**Comment by tati-kru** [comment]
Visual Query Builder is available for test as a part of early access version of the DBeaver EE. You can find it here: https://dbeaver.com/files/ea/. We are open for your feedback.

**Comment by tati-kru** [comment]
@n-osennij If you run script created in VQB it will be saved and you will be able to switch to the regular SQL editor and edit query manually. But you are right, it's a point for discussion: save or not the edited script when you are switching between SQL editor and VQB. 
Regarding conditions we have just a very base functions now. It will be upgraded and improved further. Thank you for your feedback.

**Comment by dmcveay** [comment]
thank you so much

**Comment by dclong** [comment]
@tati-kru Is this feature for the enterprise version only?

**Comment by tati-kru** [comment]
@dclong yes, it is implemented as a part of DBeaver EE only

**Comment by serge-rider** [comment]
@n-osennij Also you can save query by <kbd>CTRL+S</kbd>. 
@tati-kru I think we'll add save function on query builder presentation switch in the next EA version.

**Comment by esequiel-ferreira** [comment]
Too bad that this feature will only be available in the paid version.

-1

**Comment by serge-rider** [comment]
Basically initial version of query builder is ready. It will require more improvements in future but even now it looks good enough. Please create separate tickets for improvements.
Till EE release it is in Early Access version.

**Comment by GiantCrocodile** [comment]
Thanks for your wonderful work @serge-rider!

**Comment by codesmith55** [comment]
I hit Query Builder under the SQL Editor tab, it highlights, but nothing happens. I can open a new script editor and it's still text only. Your wiki says it should pop open and nothing else is clear for howto.

**Comment by tati-kru** [comment]
@codesmith55 unfortunately, it is not completely clear what do you mean. Visual Query Builder is available in DBeaver EE only. You can find a short demo how it works here: https://twitter.com/dbeaver_news/status/1116687401257140224
