### ISSUE TITLE
Can't do write operation, but can do read operation. When i do write operation, dbeaver happens "SQL error [08003]: No operations allowed after connection closed”.

### ISSUE THREAD

**Issue by mugg1e** [dbeaver/dbeaver#16528]

**Comment by uslss** [comment]
Could you add info accordingly to [template](https://github.com/dbeaver/dbeaver/issues/new?assignees=&labels=bug%2C+wait+for+review&template=bug_report.md&title=)?
Thanks in advance

**Comment by mugg1e** [comment]
What do you mean by info accordingly? For example

**Comment by emironovDB** [comment]
Hi @mugg1e ! 
We already have a spicific template for users request. Link: [template](https://github.com/dbeaver/dbeaver/issues/new?assignees=&labels=bug%2C+wait+for+review&template=bug_report.md&title=)
Please fill the details and send it in your ticket as a comment. 

Thanks!

**Comment by uslss** [comment]
there has been no update on the issue for a long time.
If it is still actual - feel free to reopen it.
