### ISSUE TITLE
can't load driver class 'com.ibm.db2.jcc.DB2Driver'   in DBeaver

### ISSUE THREAD

**Issue by elonmusk408** [dbeaver/dbeaver#16525]
Can't create driver instance
  Error creating driver 'DB2 z/OS' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.ibm.db2.jcc.DB2Driver'
  Error creating driver 'DB2 z/OS' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.ibm.db2.jcc.DB2Driver'
    com.ibm.db2.jcc.DB2Driver
    com.ibm.db2.jcc.DB2Driver

**Comment by uslss** [comment]
@elonmusk408 Cannot reproduce it.
Could you try to reset driver settings to default and then download the driver once again?
![2021-03-25_10h50_09](https://user-images.githubusercontent.com/31996417/112437502-12fad900-8d58-11eb-841d-d4d3d31469c2.gif)

**Comment by elonmusk408** [comment]
Now getting this error. 

Error location: Reply.fill() - socketInputStream.read (-1). Message: Connection reset. ERRORCODE=-4499, SQLSTATE=08001.

But through telnet, able to connect.

**Comment by uslss** [comment]
@elonmusk408 more about this error could be founded [here](https://www.ibm.com/support/pages/faq-jdbc-errorcode-4499-connectivity)

**Comment by jkawah** [comment]
> @elonmusk408 Cannot reproduce it. Could you try to reset driver settings to default and then download the driver once again? ![2021-03-25_10h50_09](https://user-images.githubusercontent.com/31996417/112437502-12fad900-8d58-11eb-841d-d4d3d31469c2.gif) [ ![2021-03-25_10h50_09](https://user-images.githubusercontent.com/31996417/112437502-12fad900-8d58-11eb-841d-d4d3d31469c2.gif) ](https://user-images.githubusercontent.com/31996417/112437502-12fad900-8d58-11eb-841d-d4d3d31469c2.gif) [ ](https://user-images.githubusercontent.com/31996417/112437502-12fad900-8d58-11eb-841d-d4d3d31469c2.gif)

This worked for me (i.e. delete and add in again).
