### ISSUE TITLE
Poor Result Formatting of BigQuery Nested Objects

### ISSUE THREAD

**Issue by agentkirkwood** [dbeaver/dbeaver#16544]
#### System information: 
- Operating system (distribution) and version: macOS Monterey - 12.3.1 (21E258) 
- DBeaver version: 22.0.4.202205011839
- Additional extensions: 

#### Connection specification:
- Database name and version: Google Big Query
- Driver name: SimbaJDBCDriverforGoogleBigQuery42_1.2.22.1026
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

BigQuery has a datatype called STRUCT, which is essentially a key-value type. DBeaver does not display the key names, instead of using `..."f":..` as a stand-in for _all keys_. And similarly uses `..."v":...` to indicate values before displaying the value, which seems unnecessary and convoluted. It also might be reading those objects as strings (i.e., an "ABC" field).

![Screen Shot 2022-05-19 at 3 46 42 PM](https://user-images.githubusercontent.com/16674499/169410730-7ba5e452-b4c1-45d1-8f9f-3711256cc13f.png)

Anyway, all this makes using the data more difficult. Not being able to see the keys means I have to use the web app to look up what keys are available. 

![Screen Shot 2022-05-19 at 3 54 58 PM](https://user-images.githubusercontent.com/16674499/169411021-d70c39e0-a78a-4f51-9b3e-3d0670785b1c.png)

#### Steps to reproduce, if exist:

```sql
select 
	attributes
	, attributes.id
	, attributes.name
from bigquery-public-data.genomics_cannabis.cs10_gff
limit 100;
```

**Comment by LonwoLonwo** [comment]
Thanks for the report @kdonavin

**Comment by LonwoLonwo** [comment]
Note for the future:
Driver returns tris struct value as a String.
So we need some parser for it.

**Comment by marcelo-lara** [comment]
+1 on this issue/feature
is it on the roadmap?? 

thanks!

**Comment by LonwoLonwo** [comment]
Hello @marcelo-lara 

Nope, It is not on the roadmap. 
We will pay attention to this ticket again if he gains sufficient votes.
Also, we are open to new contributions.

**Comment by baodoanjl** [comment]
+1 on this issue if it can get to the roadmap.

**Comment by vanjis** [comment]
+1 on this issue if it can get to the roadmap.

**Comment by elangovankrishna** [comment]
+1 on this issue

**Comment by ashamlian-roadway** [comment]
+1 on this issue!

**Comment by Et9797** [comment]
+1

**Comment by serge-rider** [comment]
We can show it like this:
![image](https://github.com/dbeaver/dbeaver/assets/6398845/c7da7d0b-8462-417e-b07e-710e525a275c)

Is it something what you expect?

If you want to see values in JSON form then you can use query like
```sql
select 
	TO_JSON_STRING (attributes)
	, TO_JSON_STRING (attributes.id)
	, TO_JSON_STRING (attributes.name)
from bigquery-public-data.genomics_cannabis.cs10_gff
limit 100;
```

**Comment by sknoepfler** [comment]
Hello @serge-rider, 

might I ask you for help on this issue?

I am using:
- Dbeaver community edition 23.3.3.202401211839
- SimbaBigQueryJDBC42-1.5.2.1005

I want to visualize the following BigQuery table in dbeaver:
![image](https://github.com/dbeaver/dbeaver/assets/48929584/a66a11b3-f0d8-47bd-9e62-8f5b8af3f23a)

![image](https://github.com/dbeaver/dbeaver/assets/48929584/ac26d716-bd49-4aad-a3c4-e56e78f707af)

But in dbeaver it is shown like that:
![image](https://github.com/dbeaver/dbeaver/assets/48929584/af79516b-462a-4a85-b239-5183aeaa14fb)

Can you see from my information if I did something wrong?

On your screenshot it looks exactly as I would like to have it.

Thank you very much and kind regards
Sven

**Comment by LonwoLonwo** [comment]
Hello @kdonavin 

Could you please provide your table DDL and data example for tests?

**Comment by sknoepfler** [comment]
Here are the sql statements to recreate the table from my example:

```
CREATE OR REPLACE TABLE <project>.<dataset>.bigquery_struct_and_arrays (
  id INT64,
  name STRING,
  address STRUCT<street STRING, city STRING, state STRING>,
  phone_numbers ARRAY<STRING>
);

INSERT INTO <project>.<dataset>.bigquery_struct_and_arrays (id, name, address, phone_numbers)
VALUES
(1, 'John', STRUCT('123 Main St', 'Anytown', 'CA'), ['123-456-7890', '987-654-3210']),
(2, 'Alice', STRUCT('456 Elm St', 'Othertown', 'NY'), ['111-222-3333']);
```

**Comment by LonwoLonwo** [comment]
If you think a new feature does not handle all cases, it is better to create a new ticket.

**Comment by sknoepfler** [comment]
Thanks for your input, I did that now: https://github.com/dbeaver/dbeaver/issues/26418

**Comment by agentkirkwood** [comment]
Hey, @LonwoLonwo -- I no longer have access to a BQ environment. Does this example data from their public datasets help?

```sql
select 
	attributes
	, attributes.id
	, attributes.name
from bigquery-public-data.genomics_cannabis.cs10_gff
limit 10;
```

It contains some STRUCT objects that could be used to test this update.

**Comment by LonwoLonwo** [comment]
Yeah, thanks. We already implemented it in DBeaver PRO versions. You can test it for free https://dbeaver.com/trial/

**Comment by sbuckpesch** [comment]
@LonwoLonwo Will this be implemented in CE as well, like it was stated here? Isn't Data Viewing basic functionality of CE editions? https://dbeaver.io/2024/01/21/dbeaver-23-3-3/
