### ISSUE TITLE
Renaming an active project removes it until restart

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#16540]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 22.0.5

#### Steps to reproduce, if exist:
1. Rename an active project

**Expected:** Project can be seen in projects view
**Actual:** Project disappears from a view and can't be reached until restart

![dbeaver_kTqIvpr5Cj](https://user-images.githubusercontent.com/82543000/169336069-42920f59-9d0b-450d-bfa9-e244e16a7a3e.gif)

**Comment by ShadelessFox** [comment]
Will be fixed in #14634
