### ISSUE TITLE
Multi-protocol support for ClickHouse

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/dbeaver#16545]
**Is your feature request related to a problem? Please describe.**
Below is the dialog popped up when creating a connection to ClickHouse. It's all good except I cannot change URL to something like `jdbc:ch:tcp://localhost` directly, so I have to create the connection first, and then manually change URL by editing driver settings.
![image](https://user-images.githubusercontent.com/4270380/169424797-33abbbb7-032b-45fa-b5e0-48837e73c232.png)

**Describe the solution you'd like**
1. add a drop-down list for user to choose `Protocol`(one of grpc, http and tcp, defaults to http)
2. make `Port` optional because each protocol has its default port, for examples: 8123 for http, 9000 for tcp and 9100 for grpc
3. update URL template to something like `jdbc:(ch|clickhouse)[:{protocol}]://{host}[:{port}][/{database}]`

**Describe alternatives you've considered**
Make `JDBC URL` field editable in the popup.

**Additional context**
This request has nothing to do with ClickHouse(legacy) driver as it only supports http.

**Comment by LonwoLonwo** [comment]
Sounds reasonable.

Thanks for the idea @zhicwu

**Comment by zhicwu** [comment]
Thanks @LonwoLonwo. It's probably too early to say, but you may also want to enhance the `Host` field in order to support load balancing and failover in the future.

For example, for a JDBC URL like `jdbc:ch://server1,(grpc://server2?tags=dc2),(tcp://server3:9000),(http://user4:passwd@server4:8124/db4?tags=dc1)/db?cluster=mycluster&tags=dc1&lbPolicy=firstAlive&autoDiscovery=true` (taken from ClickHouse/clickhouse-jdbc#894, not released yet), it's better to rename `Host` to `Host(s)` and remove validation of the field, because it's `server1,(grpc://server2?tags=dc2),(tcp://server3:9000),(http://user4:passwd@server4:8124/db4?tags=dc1)` in this case.

Update: `0.3.2-patch10` is released with multi-endpoint support.
