### ISSUE TITLE
Cannot Connect Postgresql  via SSL from AWS

### ISSUE THREAD

**Issue by kiattisakph** [dbeaver/dbeaver#16546]
I think AWS change some firewall rules, and dbeaver version 22.0.4 cannnot accept rule via ssl from AWS

![Capture](https://user-images.githubusercontent.com/43429886/169441222-f9dd5fb9-67da-47fa-a682-b4223d496ce9.PNG)

**Comment by LonwoLonwo** [comment]
Can you provide[ the error log](https://github.com/dbeaver/dbeaver/wiki/Log-files) please?

**Comment by cryptiswap-admin** [comment]
The issue seems to be using ubuntu 22.04 on AWS. 
I created 2 identical servers, one with ubuntu 22.04 and another with 20.04.
They both used the same private key for SSH.
I connected successfully on 20.04 but I got "Cannot establish tunnel, Auth fail" when trying to connect on ubuntu 22.04

**Comment by LonwoLonwo** [comment]
I can't help without [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files) unfortunatelly.

Also @cryptiswap-admin can you please check other DBeaver versions? 22.03/22.02 or 22.01?
I want to understand when the problem arose. So far, nothing is clear to me.

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual, feel free to reopen it.
