### ISSUE TITLE
is there a way not to have to reinstall plugins after every updates ?

### ISSUE THREAD

**Issue by itphonim** [dbeaver/dbeaver#16555]
Hi,
i'm using DBeaver in zip version (Windows)
every time I migrate to the newer version I have to redownload et reinstall the plugins.
Fortunatly I'm using only one.

having this message for instance with the Office addon:
![image](https://user-images.githubusercontent.com/82998099/169539807-4fcde566-4931-49d2-b7fa-d08b961020a4.png)

**Comment by uslss** [comment]
thanks for the suggestion
closed a a duplicate of #5317
