### ISSUE TITLE
sqlserver 2016: Table -> SQL for DDL not correct

### ISSUE THREAD

**Issue by datenbank-projekt** [dbeaver/dbeaver#16563]
I am trying to recreate a table. I am right-clicking in the table I want to copy to the the DLL SQL code “create …” DBeaver does NOT create the correct code.

Table DDL which is wrong (I marked the sports)

CREATE TABLE tbl_texte (
id int IDENTITY(834,1) NOT NULL,
textnummer int DEFAULT 0 NOT NULL,
[text] nvarchar COLLATE Latin1_General_CI_AS NOT NULL,
tbl_firma_id int NOT NULL,
beschreibung nvarchar(255) COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
textTyp int DEFAULT 0 NOT NULL,
tbl_person_id int NOT NULL,
negativText nvarchar COLLATE Latin1_General_CI_AS NOT NULL,
text2 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
text3 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
text4 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
text5 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
negativText2 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
negativText3 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
negativText4 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
negativText5 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
html nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
html2 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
html3 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
html4 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
html5 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
CONSTRAINT PK_tbl_texte_id PRIMARY KEY (id)
);

 

Code as it should be. Notice: the (max) behind the nvarchar as the field indeed is not limited (see attached screenshot of SQL Management Studio and DBeaver)

CREATE TABLE tbl_texte (
id int IDENTITY(834,1) NOT NULL,
textnummer int DEFAULT 0 NOT NULL,
[text] nvarchar **(max)** COLLATE Latin1_General_CI_AS NOT NULL,
tbl_firma_id int NOT NULL,
beschreibung nvarchar(255) COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
textTyp int DEFAULT 0 NOT NULL,
tbl_person_id int NOT NULL,
negativText nvarchar (max) COLLATE Latin1_General_CI_AS NOT NULL,
text2 nvarchar **(max)** COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
text3 nvarchar **(max)** COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
text4 nvarchar **(max)** COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
text5 nvarchar **(max)** COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
negativText2 nvarchar **(max)** COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
negativText3 nvarchar **(max)** COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
negativText4 nvarchar **(max)** COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
negativText5 nvarchar **(max)** COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
html nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
html2 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
html3 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
html4 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
html5 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
CONSTRAINT PK_tbl_texte_id PRIMARY KEY (id)
);

This of course makes it impossible to import the data that has been exported first (SQL, XML).

Also: This problem exists when one uses the DATA COMPARE and MIGRATE features

Im am using the version 22.0.0.202203131528
![nvchar_0_max](https://user-images.githubusercontent.com/29085761/169641239-3fe100c1-2716-4bff-8042-f85af6607573.png)

**Comment by LonwoLonwo** [comment]
Hello @datenbank-projekt 

I used your second script for table creation and now I have this DDL:

![2022-05-24 15_08_36-Window](https://user-images.githubusercontent.com/45152336/170031415-9a714ecb-6384-4d6a-8d9f-0a2e21567f54.png)

![2022-05-24 15_09_44-Window](https://user-images.githubusercontent.com/45152336/170031421-14e4cf28-a7eb-4325-9ce0-bf6368957b58.png)

All (max) from your script are in their places. But. I see the difference - in the length of types, I have -1, and you have - 0. But how can I create nvarchar(0)? Do you have any thoughts about it?

**Comment by datenbank-projekt** [comment]
Hi,

I did not create the initial table in SQL Server. I used Dbeaver to to some work with the database, so I can not tell you how and why dbeaver shows "0".

**Comment by emironovDB** [comment]
Hello @datenbank-projekt,

Can you please attach the DDL of this table from SSMS?

**Comment by datenbank-projekt** [comment]
Hi @emironovDB 
I do not know what else I should post but the first DLL which has been generated by dbeaver


`CREATE TABLE tbl_texte (
id int IDENTITY(834,1) NOT NULL,
textnummer int DEFAULT 0 NOT NULL,
[text] nvarchar COLLATE Latin1_General_CI_AS NOT NULL,
tbl_firma_id int NOT NULL,
beschreibung nvarchar(255) COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
textTyp int DEFAULT 0 NOT NULL,
tbl_person_id int NOT NULL,
negativText nvarchar COLLATE Latin1_General_CI_AS NOT NULL,
text2 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
text3 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
text4 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
text5 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
negativText2 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
negativText3 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
negativText4 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
negativText5 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
html nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
html2 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
html3 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
html4 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
html5 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N” NOT NULL,
CONSTRAINT PK_tbl_texte_id PRIMARY KEY (id)
);`

**Comment by LonwoLonwo** [comment]
SQL Management Studio also has the option to create table DDL. Can you please copy tbl_texte DDL from there?

**Comment by datenbank-projekt** [comment]
Hi,

**this is from dbeaver:**
-- mydatabase.dbo.tbl_texte definition

-- Drop table

-- DROP TABLE mydatabase.dbo.tbl_texte;

CREATE TABLE tbl_texte (
	id int IDENTITY(834,1) NOT NULL,
	textnummer int DEFAULT 0 NOT NULL,
	text nvarchar COLLATE Latin1_General_CI_AS NOT NULL,
	tbl_firma_id int NOT NULL,
	beschreibung nvarchar(255) COLLATE Latin1_General_CI_AS DEFAULT N'' NOT NULL,
	textTyp int DEFAULT 0 NOT NULL,
	tbl_person_id int NOT NULL,
	negativText nvarchar COLLATE Latin1_General_CI_AS NOT NULL,
	text2 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N'' NOT NULL,
	text3 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N'' NOT NULL,
	text4 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N'' NOT NULL,
	text5 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N'' NOT NULL,
	negativText2 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N'' NOT NULL,
	negativText3 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N'' NOT NULL,
	negativText4 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N'' NOT NULL,
	negativText5 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N'' NOT NULL,
	html nvarchar COLLATE Latin1_General_CI_AS DEFAULT N'' NOT NULL,
	html2 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N'' NOT NULL,
	html3 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N'' NOT NULL,
	html4 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N'' NOT NULL,
	html5 nvarchar COLLATE Latin1_General_CI_AS DEFAULT N'' NOT NULL,
	CONSTRAINT PK_tbl_texte_id PRIMARY KEY (id)
);
 CREATE NONCLUSTERED INDEX FK_tbl_texte_1 ON dbo.tbl_texte (  tbl_person_id ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 90   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX FK_tbl_texte_2 ON dbo.tbl_texte (  tbl_firma_id ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 90   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- mydatabase.dbo.tbl_texte foreign keys

ALTER TABLE mydatabase.dbo.tbl_texte ADD CONSTRAINT tbl_texte$FK_tbl_texte_1 FOREIGN KEY (tbl_person_id) REFERENCES tbl_person(id);
ALTER TABLE mydatabase.dbo.tbl_texte ADD CONSTRAINT tbl_texte$FK_tbl_texte_2 FOREIGN KEY (tbl_firma_id) REFERENCES tbl_firma(id);


**this is from sql management studio**
.... I get an error message here: TITEL: Microsoft SQL Server Management Studio: "Ungültige Version: 15. (Microsoft.SqlServer.Smo)" (which means invalid version ...)

But this is the
![image](https://user-images.githubusercontent.com/29085761/170659359-f58a69cf-91f6-4986-b904-bf9a382ebd45.png)

**Comment by LonwoLonwo** [comment]
Can you provide your driver and database info, please?

You can find this info in your Connection page.
![2022-06-01 16_33_46-DBeaver Ultimate 22 1 0 - _postgres 13 3_Script-161](https://user-images.githubusercontent.com/45152336/171418026-c1ddd8bb-4d20-41e1-bc40-acfa3d32a2ae.png)

**Comment by datenbank-projekt** [comment]
Hi,

please see screenshot (it would be nice if one could copy the information to the clipboard).

![connection](https://user-images.githubusercontent.com/29085761/171436057-7c9d5f39-173c-439f-b453-9a9aedde0f5f.png)

**Comment by ShadelessFox** [comment]
Thanks for the additional information.

In fact, you can select and then copy this text:

![image](https://user-images.githubusercontent.com/35821147/171436437-70c612db-fdfd-4885-ac6d-7eb96d93653e.png)
