### ISSUE TITLE
Unable to add custom driver and Page crash

### ISSUE THREAD

**Issue by wow-blacksheep** [dbeaver/dbeaver#16568]
![image](https://user-images.githubusercontent.com/37165012/169766409-b263ed15-60ce-4c97-bb2c-54fea9256326.png)
![image](https://user-images.githubusercontent.com/37165012/169766487-0de4a82d-31c2-44c8-9982-2345a3537146.png)
![image](https://user-images.githubusercontent.com/37165012/169766700-1ecdb5a2-6c3a-40d1-bb0e-61d886b374ad.png)

**Comment by LonwoLonwo** [comment]
Hello @wow-blacksheep 

Please provide more info about your OS.

**Comment by LonwoLonwo** [comment]
This link can be helpful: https://stackoverflow.com/questions/2018553/swt-no-more-handles

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual, feel free to reopen it.
