### ISSUE TITLE
Support Apache Kyuubi (Incubating)

### ISSUE THREAD

**Issue by pan3793** [dbeaver/dbeaver#16567]
**Is your feature request related to a problem? Please describe.**

Apache Kyuubi (Incubating)[1] a distributed and multi-tenant gateway to provide serverless SQL on lakehouses, and DBeaver is an amazing database/data warehouse GUI client. I want to add the native support of Kyuubi in DBeaver.

**Describe the solution you'd like**

Kyuubi provides a HiveServer2 compatible thrift API and JDBC driver, so the support is simple, I proposes to refer the Apache Spark Thrift Server to change the xml configuration and add the icons file.

**Describe alternatives you've considered**

User can connect Kyuubi by using Hive JDBC driver, but Kyuubi provides it's own JDBC driver to unlock more functionalities, e.g. Hive JDBC driver supports only the default catalog, but Kyuubi JDBC driver supports multi-catalogs.

**Additional context**

<img width="948" alt="image" src="https://user-images.githubusercontent.com/26535726/169561039-0c6a9631-c7b3-4737-b380-1592ff1921e4.png">

<img width="948" alt="image" src="https://user-images.githubusercontent.com/26535726/169561130-0d2fffdc-ec5d-499f-b988-b9dd6d30b82d.png">

<img width="928" alt="image" src="https://user-images.githubusercontent.com/26535726/169560927-ea4ee58a-284e-4b81-a0bd-46359a0cd393.png">

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/26535726/169553925-6c631149-d202-49a0-b465-cebaeb7ecb13.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/26535726/169561901-8aaa8995-f4fb-4425-9de4-d1b1cabe5e46.png">

[1] https://kyuubi.apache.org/

**Comment by serge-rider** [comment]
Thank you for the contribution.
We will test it and perhaps include in one of the next releases.

**Comment by pan3793** [comment]
Thanks @serge-rider, feel free to ping me if you run into any issues.
