### ISSUE TITLE
show (sub)partitioning key for partitioned tables

### ISSUE THREAD

**Issue by jnahmias** [dbeaver/dbeaver#16582]
**Is your feature request related to a problem? Please describe.**

Partitioned tables are being found more frequently as we work with larger datasets. DBeaver does show when a table is partitioned, and even lists the partition's name, position, tablespace, high value, #rows, etc... on the Partitions sub-tab of the Table properties.
However, a key piece of information -- the partitioning key -- is missing from the display. This makes it very hard understand how the table is structured!

**Describe the solution you'd like**

Please show the partitioning key either in the Statistics/Partitioning subtab, or on the Partitions subtab of the table properties.

**Describe alternatives you've considered**

Alternative is to search/lookup/write SQL to query the data dictionary for this information every time it's needed.  For example, on Oracle, I can use:

```sql
SELECT
  owner AS schema, name AS table_name,
  column_name AS partitioning_key
FROM all_part_key_columns
WHERE object_type = 'TABLE'
  AND owner='TABLE_SCHEMA' AND name = 'TABLE_NAME'
;
```

**Comment by Jnkie** [comment]
@jnahmias thank you for creating an issue and describing alternative (temprorary) solution!

Showing partition key is crucial, without that all information about partitions is worthless

**Comment by LonwoLonwo** [comment]
Implemented here: https://github.com/dbeaver/dbeaver/pull/22463

Changing these fields (partition and subpartition keys) for new tables is available only in [PRO versions](https://dbeaver.com/edition/).
