### ISSUE TITLE
error with job

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#16585]
Dbeaver 22.0.5
postgresql 14
windows 11

Steps:

1. Connect to database
2. Open objects tree and click to jobs
![image](https://user-images.githubusercontent.com/61137576/170185187-eabe53a8-3e0c-44af-9124-dc9e0c67c836.png)

4. After that 2 elemets removed from object tree Blocks and session.
![image](https://user-images.githubusercontent.com/61137576/170185531-2c7ce738-00a8-43c1-9ab7-4df0940e61ac.png)
5. Every click on update database show the error
![image](https://user-images.githubusercontent.com/61137576/170185682-47a847dc-ac8f-443b-8490-3fa4d17f1fa4.png)
![image](https://user-images.githubusercontent.com/61137576/170185719-f5f9af06-ce5d-4e8a-8d2c-1a08d820d45e.png)

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @detkliff
