### ISSUE TITLE
Statistics tab not focused after SQL Update

### ISSUE THREAD

**Issue by kcbaltz** [dbeaver/dbeaver#16605]
#### System information: 
- Operating system (distribution) and version: MacOS 12.3.1
- DBeaver version: 22.0.5
- Additional extensions: none

#### Connection specification:
- Database name and version: AS/400 and MariaDB
- Driver name: DB2 iSeries/AS 400   and MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Issue happens without using tunnel or proxy

#### Describe the problem you're observing:
In the last few months, I've noticed that after performing an SQL update, the Statistics tab that appears at the bottom of the SQL editor indicating how many rows were affected  is not being focused and instead I see one of the previous results tabs (e.g. the results of a previous select query).  The Statistics tab is being created and I can switch to it but this used to happen automatically and still should IMHO.  

FYI, I have DBeaver set to create a new result tab every time (not sure where this setting is but I remember setting it).  

#### Steps to reproduce, if exist:
- Open an SQL editor and connect to DB.
- Execute a select statement several times until there are more result tabs at the bottom that can be displayed and the ">>" icon appears for the overflow
- Select one of the first result tabs
- Execute an UPDATE statement

Expected behavior:  a Statistics tab should appear saying how many rows were affected.  This tab should be visible without having to manually switch to it

Actual behavior: a previous Results tab is displayed showing rows from one of the SELECTS.  The Statistics tab is created but not selected/focused.

**Comment by emironovDB** [comment]
Hello @kcbaltz,

Thanks for the bug report.
