### ISSUE TITLE
sql editor loose datasource  assignation

### ISSUE THREAD

**Issue by aumeli74** [dbeaver/dbeaver#16606]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by aumeli74** [comment]
System information:
Operating system (distribution) and version   MACOS bigsur
DBeaver version  Versión22.0.4.202205011839


 Connection specification:
Database name and version POSTGRESQL 12
Driver name  PostgreSQL JDBC Driver
Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH TUNNEL

Describe the problem you're observing:
Steps to reproduce, if exist:

a) Open new  sql editor
b) select your datasource in the toolbar
c) write and run any dml sql or select and update into table edition any value and save it.
d)try to run any other sql  in the same editor or rerun your last query  and the data source was loose it , appear <N/A> in the data source toolbar
e) select your datasource any  and return step C)

Not always happen but happen too much times ; i try it assigning data source to script but not work ; the same , in fact the datasource assign is loose it too.

**Comment by Matvey16** [comment]
@aumeli74 Hello. Can you show me your preferrences for the data editor? 
![image](https://user-images.githubusercontent.com/82543000/173813921-c79c2795-ef27-4dd0-b7ee-c5c89da3bf2c.png)

Also can you tell me if this happens after some idle time or immidiatly when you execute two queries back to back?

**Comment by aumeli74** [comment]
Hi there!! I removed  directory  DBEaverData from Library and work again , the problem with the connection has gone.

The only thing that persist seem to be the source asociation i can’t see it yet , like this image (Example image taked from another mac)
***@***.***


About my preferences data editor,sorry, I restarted my computer because I transferred  and i can’t send you the images from that.

Regards

From: Matvey16 ***@***.***>
Date: Wednesday, 15 June 2022, 5:13
To: dbeaver/dbeaver ***@***.***>
Cc: AUGUSTO LIZARDI ***@***.***>, Mention ***@***.***>
Subject: Re: [dbeaver/dbeaver] sql editor loose datasource assignation (Issue #16606)

@aumeli74<https://github.com/aumeli74> Hello. Can you show me your preferrences for the data editor?
[image]<https://user-images.githubusercontent.com/82543000/173813921-c79c2795-ef27-4dd0-b7ee-c5c89da3bf2c.png>

Also can you tell me if this happens after some idle time or immidiatly when you execute two queries back to back?

**Comment by Matvey16** [comment]
@aumeli74 Sorry, I can't see the image because responses from email don't attach files to github. To attach the image you need to add it directly on a github page.

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If the issue is still actual for you, feel free to reopen it.
