### ISSUE TITLE
Error downloading database drivers after upgrade to 22.0.5

### ISSUE THREAD

**Issue by 1RichardClarke** [dbeaver/dbeaver#16608]
#### System information: 
- Windows Server 2019
- DBeaver v22.04
- Java OpenJDK jdk-11.0.8.10-hotspot
- Additional extensions - None

#### Connection specification:
- PostgresSQL v14
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
Upgraded to 22.0.5, message saying drivers need updating, but get error message
Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

#### Steps to reproduce, if exist:
Uninstalled and removed Dbeaver folder from AppData, tried to install 22.0.4 but get the same error message as above

**Comment by LonwoLonwo** [comment]
Hello @1RichardClarke 

Please refer to this article. https://github.com/dbeaver/dbeaver/wiki/Importing-CA-Certificates-into-DBeaver

or check this related tickets: #15647, #15612

**Comment by uslss** [comment]
there has been no update on the issue for a long time.
If it is still actual - feel free to reopen it.

**Comment by fritzmg** [comment]
> Please refer to this article. https://github.com/dbeaver/dbeaver/wiki/Importing-CA-Certificates-into-DBeaver

This article only works if Java was installed globally, correct? I am getting the same error, but in my case Java is not installed. Instead I used the option to install Java only for DBeaver during setup.

**Comment by E1izabeth** [comment]
@fritzmg if your OS is Windows you could try turning off/on `Use Windows trust store` preference.
https://user-images.githubusercontent.com/28875055/199441946-1200ed28-9b93-42f6-97eb-231594353ee1.png

**Comment by fritzmg** [comment]
Unfortunately that did not help, the same error message remains.

**Comment by E1izabeth** [comment]
Just to confirm: have you restarted DBeaver after changing that preference?

**Comment by fritzmg** [comment]
Ah thank you, that helped 👍
