### ISSUE TITLE
每次重新打开后再选择打开SQL控制台执行SQL就提示: SQL 错误 [1046] [3D000]: No database selected

### ISSUE THREAD

**Issue by erxiaoouba** [dbeaver/dbeaver#16618]
选择数据库连接右键重新连接也不能执行, 上次关闭时没有手动选择关闭连接, 再次打开时还是连接状态, 可以正常打开表等

可不可以每次重新打开后继续使用上次关闭前的数据库连接呢

1. ![image](https://user-images.githubusercontent.com/30993388/170668125-4603ec1b-4d8e-4f67-9469-aa856a9a9036.png)

2. ![image](https://user-images.githubusercontent.com/30993388/170668182-c07a0178-6282-4fac-8f38-050bb86a9f99.png)

3. ![image](https://user-images.githubusercontent.com/30993388/170668221-69af3bad-22cc-4d1c-8efd-100c24a98f56.png)

<details>
     <summary>Automatic traslation via Google Translate:</summary>

Selecting the database connection and right-clicking to reconnect cannot be executed. The last time it was closed, it was not manually selected to close the connection. When it is opened again, it is still connected, and the table can be opened normally, etc.

Can you continue to use the database connection before the last shutdown after each reopening?
</details>

**Comment by E1izabeth** [comment]
Hi, @erxiaoouba! Could you, please, provide video of this issue and log file? To know how to find the log file, see https://dbeaver.com/docs/wiki/Log-files/

**Comment by uslss** [comment]
there has been no update on the issue for a long time.
If it is still actual - feel free to reopen it.
