### ISSUE TITLE
Invalidate/Reconnect when connection has timed out

### ISSUE THREAD

**Issue by TimNapierVST** [dbeaver/dbeaver#16617]
**Is your feature request related to a problem? Please describe.**
If I haven't been active for a while the connection to snowflake is lost and needs to be invalidated/reconnected

**Describe the solution you'd like**
DBeaver to detect and automatically re-connect ...or.... at least have a button on the dialog box that says reconnect

**Describe alternatives you've considered**
...or.... at least have a button on the dialog box that says reconnect

**Additional context**
A matter of convenience

**Comment by E1izabeth** [comment]
@TimNapierVST , DBeaver usually automatically reconnects when connection is lost. Please, attach the log file. To know how to find it, see https://dbeaver.com/docs/wiki/Log-files/

Also DBeaver has buttons to connect/reconnect/disconnect on the toolbar
![image](https://user-images.githubusercontent.com/28875055/171432179-3513d362-0815-407f-9bbb-1505b87aa4c0.png)

**Comment by TimNapierVST** [comment]
Hi Elizabeth

Thanks for getting back to me.

I have extracted the event from the log and attached it here.

Regards


Tim
***@***.***
***@***.***
***@***.***


Tim Napier
Principal Consultant
Professional Services - Data Practise | Versent

***@***.***

0406430225

***@***.***

***@***.******@***.***>

***@***.***

versent.com.au<http://versent.com.au>

***@***.***

Head Office: Level 19/8 Exhibition Street, Melbourne VIC 3000


On 2 Jun 2022, at 12:44 am, Elizabeth ***@***.******@***.***>> wrote:



@TimNapierVST<https://github.com/TimNapierVST> , DBeaver usually automatically reconnects when connection is lost. Please, attach the log file. To know how to find it, see https://dbeaver.com/docs/wiki/Log-files/<https://dbeaver.com/docs/wiki/Log-files/>

Also DBeaver has buttons to connect/reconnect/disconnect on the toolbar
[image]<https://user-images.githubusercontent.com/28875055/171432179-3513d362-0815-407f-9bbb-1505b87aa4c0.png>

**Comment by E1izabeth** [comment]
Unfortunately, files attached to the email don't come here, to the github. So, it would be appreciated if you come to the github issue and attach it here. Thank you.

**Comment by TimNapierVST** [comment]
[AuthenticationToken.log](https://github.com/dbeaver/dbeaver/files/8819487/AuthenticationToken.log)
As requested @E1izabeth

**Comment by E1izabeth** [comment]
Thank you for quick reply, @TimNapierVST. Could you also provide information about the database and the authentication method you are using?

**Comment by uslss** [comment]
there has been no update on the issue for a long time.
If it is still actual - feel free to reopen it with additional info.

**Comment by TimNapierVST** [comment]
This hasn’t been fixed
[cid:7CB6679A-B581-4D65-8C8B-E95FEFBD6B86][cid:9110CF83-26AF-48E4-840C-8EC9CC1C8ED3] [cid:F2F93279-7F70-4C9B-B763-F21A8908047E]
Tim Napier
Principal Consultant
Professional Services - Data Practise | Versent

[cid:4BDDFC36-A306-423F-A17A-54E9EFF20AEA]
0406430225

[cid:D3A62A1E-AE13-4671-A45D-8BB91531C48C]
***@***.******@***.***>

[cid:AFAECB2D-D9AC-4598-B400-4C7E1F34EB29]
versent.com.au<http://versent.com.au>

[cid:4C607774-CC56-4BBF-A7F9-01A255047435]

Head Office: Level 19/8 Exhibition Street, Melbourne VIC 3000


On 27 Jun 2022, at 6:30 pm, Dziyana ***@***.******@***.***>> wrote:



Closed #16617<https://github.com/dbeaver/dbeaver/issues/16617> as completed.
