### ISSUE TITLE
Groupping panel: wrong ORDER BY clause

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#16628]
When perform ORDER BY COUNT() it fails (because of wrong SQL query).

Another problem is that drag-n-drop of the same column to grouping panel does nothing after grouping clear.

**Comment by serge-rider** [comment]
Fixed.

Please test ordering, multiple attributes, custom SQL queries.
Code is in `devel`.

**Comment by uslss** [comment]
verified
