### ISSUE TITLE
Make dbeaver display better on Linux

### ISSUE THREAD

**Issue by JiaOkay** [dbeaver/dbeaver#16625]
I am using dbeaver on linux
The title bar is too large and takes up too much space
just like this

![image](https://user-images.githubusercontent.com/38833358/170731895-6474b740-290e-4f83-9818-7dbd146ecdf1.png)

I want to reduce the width of the title bar and put the title on the left side of the window with logo of dbeaver
just like it's display on the windows or merge title bar and menu bar in single line.

my systeminfo:
![image](https://user-images.githubusercontent.com/38833358/170732925-ef5bf0cc-8c10-4a75-8f5d-e7460cf2328c.png)

**Comment by flambchap** [comment]
Hi. Thank you for the report. It is a known issue: https://github.com/dbeaver/dbeaver/issues/15920. 

BTW, it seems to affect only certain Linux distros.
