### ISSUE TITLE
SSH2 Message about remote host identification chage hides

### ISSUE THREAD

**Issue by gvaleika** [dbeaver/dbeaver#16626]
#### System information: 
- archlinux current
- DBeaver version -  22.0.4.202205022238
- Additional extensions - NO

#### Connection specification:
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - YES

#### Describe the problem you're observing:

On dBeaver startup if script with connection using ssh is active dBever asks to confirm changed remote host identification. On clicking outside of the SSH message dialog or if other modal dialog (Tip of the day, message about new release etc.) is shown on startup SSH message hides beneath other windows but keeps holding input focus. In that case all GUI becomes locked and there is no way to get back to SSH message dialog to confirm or deny new remote host identification. I think if SSH dialog keeps holding input it must be shown on top and do not hide beneath other windows.

#### Steps to reproduce, if exist:

Open dBeaver with script using ssh tunneled connection with changed remote host identification. When SSH message is shown click any dBeaver GUI element outside this message.

**Comment by Destrolaric** [comment]
Will be done in the scope of #13691
