### ISSUE TITLE
SQL Editor Tab, Quick Switch Editor, Show List: Select wrong Tab

### ISSUE THREAD

**Issue by GuenterSch** [dbeaver/dbeaver#16620]
#### System information: 
- Windows 10 21H1
- DBeaver version: 22.0.5

#### Describe the problem you're observing:
I have 37 SQL Editor Tabs open. Often, when I switch to another tab via Mouse (Cursor) or Quick Switch Editor or Show List, the selected Tab will be open for some milli seconds, then the tab on the left side will be the active tab.

Please, can you correct this, that the selected tab will be opened.

Thanks, BR
Günter

**Comment by ShadelessFox** [comment]
Hello @GuenterSch,

Can you please provide a video showing the issue? Thanks.

**Comment by GuenterSch** [comment]
https://user-images.githubusercontent.com/99535516/170687860-a450be6c-5c31-4334-beb4-b971d032e179.mp4

**Comment by Matvey16** [comment]
@GuenterSch Does it happen at specific times or just randomly and not always?

**Comment by GuenterSch** [comment]
Not always, but very often. After start of DBeaver - I think - always.

**Comment by Matvey16** [comment]
Seems like the same issue as in #9326

**Comment by GuenterSch** [comment]
Hello Matvey16,
this bug still persists.
The first thing is, if I write after the tab switch, I am in a wrong SQL editor window. Thats bad!
And a Ctrl+Tab goes not to the previous SQL editor window.

Would be very fine, if you can correct this bug.
Thanks in advance, BR
Günter

Now I use 22.2.5
