### ISSUE TITLE
Improve search function in drop-down tabs list

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#16632]
We need to extend the search functionality added in #13456 to the search in tab bar, currently the search only works in quick switch editor window, but doesn't if tabs list is opened from the drop-down

![dbeaver_IpQtPefaa3](https://user-images.githubusercontent.com/82543000/170953994-293eed4f-7ba1-41c7-89cb-c222a58a7b0d.gif)

**Comment by ShadelessFox** [comment]
Already implemented in #14748
