### ISSUE TITLE
NPE when you try to open a database object.

### ISSUE THREAD

**Issue by igorlash** [dbeaver/dbeaver#16649]
#### System information: 
- Operating system (distribution) and version : Linux Mint 20.3 Cinnamon, Linux kernel 5.14.0-1038-oem
- DBeaver version : 22.0.5.202205220912
- Additional extensions : DBeaver Debug 6.1.72.202205220912

#### Connection specification:
- Database name and version : MySQL 8.0.27
- Driver name : MySQL Connector/J mysql-connector-java-8.0.17

#### Describe the problem you're observing:
NPE when you try to open a database object.

#### Steps to reproduce, if exist:
Sometimes when I try to open a table using the "Open Database Object in .."  Shift+Ctrl+D after entering a first character in the filter field I receive an error message. 
![image](https://user-images.githubusercontent.com/31065075/171177009-63ea676c-8ea6-4e3d-ac53-fc9189c56064.png)

I have checked the Error log view for this error 
![image](https://user-images.githubusercontent.com/31065075/171177679-d51c90ed-55a5-43fb-93d9-26f4baa63321.png)

```
java.lang.NullPointerException
	at org.jkiss.dbeaver.model.impl.struct.AbstractObjectReference.getFullyQualifiedName(AbstractObjectReference.java:89)
	at org.jkiss.dbeaver.model.DBUtils.getObjectFullName(DBUtils.java:1550)
	at org.jkiss.dbeaver.ui.navigator.dialogs.GotoObjectDialog.getElementName(GotoObjectDialog.java:228)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$HistoryComparator.compare(FilteredItemsSelectionDialog.java:2947)
	at java.base/java.util.TimSort.binarySort(TimSort.java:296)
	at java.base/java.util.TimSort.sort(TimSort.java:239)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
	at java.base/java.util.Collections$SynchronizedList.sort(Collections.java:2470)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$ContentProvider.getSortedItems(FilteredItemsSelectionDialog.java:2583)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$ContentProvider.rememberResult(FilteredItemsSelectionDialog.java:2595)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.filterContent(FilteredItemsSelectionDialog.java:1963)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.internalRun(FilteredItemsSelectionDialog.java:1914)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.doRun(FilteredItemsSelectionDialog.java:1891)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.run(FilteredItemsSelectionDialog.java:1879)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by igorlash** [comment]
I have recheck, the problem shows up when "Procedure" is selected.
![image](https://user-images.githubusercontent.com/31065075/171195139-c37299ad-83ac-4b16-9c93-7987b0fe9db5.png)

**Comment by LonwoLonwo** [comment]
We are using this statement for the search:

`SELECT ROUTINE_SCHEMA,ROUTINE_NAME FROM information_schema.ROUTINES ORDER BY ROUTINE_NAME `

(You can check it in the [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager))

As I can see in DBeavers code, the problem persists if the procedures ROUTINE_SCHEMA field is empty in the result query. 
Can you check it, please? Can you execute this statement?

`SELECT ROUTINE_SCHEMA,ROUTINE_NAME FROM information_schema.ROUTINES ORDER BY ROUTINE_NAME `

and check routines without schema name?

**Comment by igorlash** [comment]
I take it тфьу means name. 

I have checked these requests
```
SELECT ROUTINE_SCHEMA,ROUTINE_NAME FROM information_schema.ROUTINES 
    ORDER BY ROUTINE_NAME;

SELECT ROUTINE_SCHEMA,ROUTINE_NAME FROM information_schema.ROUTINES 
    WHERE ROUTINE_NAME like 'p%'
    ORDER BY ROUTINE_NAME;
```
They all return correct results (no schema name nulls).
But I have found another problem in a similar situation. 
If I try to search in "DB Metadata" with the same character which crashes filtering 

![image](https://user-images.githubusercontent.com/31065075/171216391-446f7607-215e-4a73-b344-e5f942a32f03.png)

another exception is thrown 
```
org.jkiss.dbeaver.DBException: Procedure catalog 'sys' not found
	at org.jkiss.dbeaver.ext.mysql.model.MySQLStructureAssistant$2.resolveObject(MySQLStructureAssistant.java:184)
	at org.jkiss.dbeaver.ui.search.metadata.SearchMetadataQuery.run(SearchMetadataQuery.java:100)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:94)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
This exception might give a hint why this problem pops up.

**Comment by LonwoLonwo** [comment]
In your second example 

```sql
SELECT ROUTINE_SCHEMA,ROUTINE_NAME FROM information_schema.ROUTINES 
    WHERE ROUTINE_NAME like 'p%'
    ORDER BY ROUTINE_NAME;
```

Probably returned 'sys' as schema name for some procedure, and DBeaver didn't find it in your catalogs list.

**Comment by igorlash** [comment]
I don't think it is about 'sys'. ROUTINE_SCHEMA and ROUTINE_NAME are not nullable. It is about how MySQLCatalog is created. 
![image](https://user-images.githubusercontent.com/31065075/171233231-f1f0019b-f4df-4e0f-babb-f5b78022f4db.png). 
Looks like all the information is grouped by a catalog name. In our case it is 'sys', but in my case 
![image](https://user-images.githubusercontent.com/31065075/171233799-4b3e97d6-df6b-4f91-9eff-e5179205156c.png)
they are all not nulls. 

As well catalog info is retrieved from MySQLDataSource's cache, and this cache doesn't have the 'sys' catalog 
![image](https://user-images.githubusercontent.com/31065075/171236562-a8d1aa47-5656-4d52-a2e4-a5e2b16e5844.png)

**Comment by igorlash** [comment]
I have just retested and found out that the problem is reproducible on my remote DB only. It is not reproducible on my local DB. 
Taking it into account and after having reviewed the code I can suggest the bug might be caused by multi-threading processing. 
When the exception is thrown 
![image](https://user-images.githubusercontent.com/31065075/171321502-fae2576a-461b-4323-a052-aac7966ffdb4.png)
some data have not been initialized yet.

**Comment by LonwoLonwo** [comment]
But where is the schema 'sys'? Or is this remote schema or something else?

**Comment by igorlash** [comment]
I think it is not about the schema 'sys' it is about processing results from a DB. The schema 'sys' exists in the both DBs. The difference is the speed of processing, the remote one is slower. 

Check out this method MySQLStructureAssistant.findProceduresByMask
Here 
![image](https://user-images.githubusercontent.com/31065075/171333164-98ac03d7-6085-4690-8851-0202f13f4338.png)
you can see a call to a DB. And catalogName is retrieved successfully. 
And here 
![image](https://user-images.githubusercontent.com/31065075/171333326-6c6d2f36-2b71-459b-9250-23f9d0a24eba.png)
MySQLCatalog is being retrieved without accessing DB. And here the exception is thrown. 
So there are  more then one place where procedure info is retrieved. 
It means that MySQLCatalog has not been initiated when MySQLStructureAssistant.findProceduresByMask is called.

**Comment by igorlash** [comment]
This exception 
![image](https://user-images.githubusercontent.com/31065075/171351506-032d115d-4b92-4a89-99c2-db6857324c12.png)
is very confusing, because it says "Procedure catalog 'sys' not found", but this catalog or at least its name 'sys' has been found in a DB some lines of code above
![image](https://user-images.githubusercontent.com/31065075/171351836-afbb0e70-9558-4d7d-bacd-891520905185.png)

**Comment by LonwoLonwo** [comment]
Ok, thanks for the report.

**Comment by igorlash** [comment]
I was wrong about the speed of processing.

I have debugged a bit and found out that different sets of data used to fill MySQLDataSource.catalogCache, and to read from this cache in MySQLStructureAssistant.findProceduresByMask depending on a user's security configuration. When the cache is filled the same schema list is used as in the Database Navigator. 
![image](https://user-images.githubusercontent.com/31065075/171654944-608b7cd3-805e-4b1c-99aa-783996593b87.png)
But in some cases it is not the same list as returned by 
```
SELECT ROUTINE_SCHEMA,ROUTINE_NAME FROM information_schema.ROUTINES
```
So in some cases less schemas are put in the cache than can be returned by the above mentioned SQL. 
To put it in a simple way, in some cases the 'sys' is not put to the cache, but in MySQLStructureAssistant.findProceduresByMask  it is being read. 

@LonwoLonwo your commit doesn't solve the problem, it is just a workaround.

**Comment by igorlash** [comment]
To find out the reason of the problem it is better to put a breakpoint in AbstractObjectCache.getObjectMap
![image](https://user-images.githubusercontent.com/31065075/171660389-2fc4e7c1-ddab-4e61-97e0-37f9249ecc50.png)
and find out where the data come from when the cache is filled with  schemas.

**Comment by igorlash** [comment]
Here is the bug 
![image](https://user-images.githubusercontent.com/31065075/171683542-c67b4795-f2d5-4865-8b74-90b36a423043.png)
The cache is filled using 
```
SHOW DATABASES;
```
and this request doesn't always return 'sys'

**Comment by LonwoLonwo** [comment]
Yes, this is workaround.
But the main problem is in the "some cases".
I do not have such type of datasourses in my test databases (MySQL, Maria, local, remote), wich have unreaded databases.
"SHOW DATABASES;" always returns to me the correct number of objects.

So, we are always welcome to contributions.

**Comment by igorlash** [comment]
Hello @LonwoLonwo 
About **But the main problem is in the "some cases".**
I don't agree with you on this matter because the problem doesn't show up only if a mysql user is root or has all privileges on all databases or at least access to the 'sys' database. Very often privileges are provided by admins, and privileges are very restricted especially if you want to get access to prod (only a crazy admin can give all the privileges in the case)
 
 About **I do not have such type of datasourses in my test databases (MySQL, Maria, local, remote), wich have unreaded databases.
"SHOW DATABASES;" always returns to me the correct number of objects.**
Here is the list of steps on how to reproduce both of the problems. 
1. Create a new user 
```
CREATE USER 'test'@'%' IDENTIFIED BY 'test';
```
2. Grant the user access to only one DB 
```
GRANT ALL privileges ON my_database.* TO 'test'@'%';
```
3. Create a new connection in DBeaver using the user's credentials 
![image](https://user-images.githubusercontent.com/31065075/171833943-cd262f2d-9d02-49e9-a4b4-65065d9ac0f9.png)
4. The user has access to only a limited numbers of databases
![image](https://user-images.githubusercontent.com/31065075/171834065-faee641a-423d-491d-9323-f226635b464b.png)

And after that all the problems are reproducible 
1. SHOW DATABASES doesn't return 'sys'
![image](https://user-images.githubusercontent.com/31065075/171834297-46097aee-ff16-4162-8c98-7544bbced42d.png)
2. NPE in 'Open data object'
![image](https://user-images.githubusercontent.com/31065075/171834402-cbedc707-6d1e-4730-9167-77e815a1941d.png)
3. And the **Procedure catalog 'sys' not found** exception 
![image](https://user-images.githubusercontent.com/31065075/171834687-1b5ad577-a426-4500-a370-6b3f05c22715.png)

**Comment by LonwoLonwo** [comment]
Ok, but what is the solution to this issue? What do you think about this?
 If we do not have a catalog in our catalogs list, but our select returned this catalog name - I propose to skip this result. Because DBeaver does link between found object and object and navigator tree. We can't do links to objects which the user doesn't know (or see).
So, just skip them.

**Comment by igorlash** [comment]
Just skipping solves the problem 
3. And the Procedure catalog 'sys' not found exception
but I am not sure if it solves the problem
2. NPE in 'Open data object'
or other possible problems
I suggest another solution, instead of using 
```
SELECT ROUTINE_SCHEMA,ROUTINE_NAME FROM information_schema.ROUTINES 
    ORDER BY ROUTINE_NAME;
```
we can use 
```
SELECT ROUTINE_SCHEMA,ROUTINE_NAME FROM information_schema.ROUTINES 
    WHERE ROUTINE_SCHEMA IN ('my_db1', 'my_db1')
    ORDER BY ROUTINE_NAME
;
```
where my ('my_db1', 'my_db1') is a list returned by 

```
SHOW DATABASES;
```
and this list is already cached when we need it. 

PS. Personally I don't like the idea that MySQL has a list of objects in information_schema.ROUTINES  that are not available to a user . It is very strange if is not a security hole.

**Comment by igorlash** [comment]
About my suggested solution. It is important to be careful with the cache. I don't know how it works with databases are filtered.
![image](https://user-images.githubusercontent.com/31065075/171881876-79b706e0-e485-40b5-b026-0706b79b13b1.png)
I don't know if they are filtered in the cache as well

**Comment by igorlash** [comment]
Sorry, I accidentally closed the issue

**Comment by LonwoLonwo** [comment]
Nope, I can't all schemas to the statement. It's not cheap and can contains potential problems with numbers of catalogs (some users have many catalogs in database) or with the catalog naming. 
I will adhere to my decision to simply skip those objects whose catalog was not found.

**Comment by igorlash** [comment]
The problem pops up when only the 'sys' schema is not returned by
```
SHOW DATABASES;
``` 
This schema contains some system procedures that are used by any user under the hood. 
It might be a solution to exclude the 'sys' schema if it is not returned by the above mentioned SQL. 
Something like this
```
SELECT ROUTINE_SCHEMA,ROUTINE_NAME FROM information_schema.ROUTINES 
    WHERE ROUTINE_SCHEMA NOT IN ('sys')
    ORDER BY ROUTINE_NAME
```
