### ISSUE TITLE
Does the data edit field type not support control selection? Can you choose like navicat?

### ISSUE THREAD

**Issue by wasd345** [dbeaver/dbeaver#16644]
数据编辑字段类型为时间不支持控件选择吗？能不能像navicat一样能选的

Does the data edit field type not support control selection? Can you choose like navicat?

**Comment by LonwoLonwo** [comment]
Please translate your message into English.

And provide screens from Navicat and more info about your feature request.

**Comment by E1izabeth** [comment]
DBeaver has its own datetime editor. See https://github.com/dbeaver/dbeaver/pull/15077

**Comment by E1izabeth** [comment]
> DBeaver has its own datetime editor. See #15077

@wasd345, does it satisfy your needs?
