### ISSUE TITLE
SQL editor : function unaccent(); not recognized in Dbeaver 

### ISSUE THREAD

**Issue by wellbigas** [dbeaver/dbeaver#16640]
#### System information: 
- Operating system (distribution) and version : Windows 11
- Dbeaver version : Version 22.0.5.202205220912
- Additional extensions: nothing extensions

#### Describe the problem you're observing:
the documentation in one post do postgreSQL: https://www.postgresql.org/docs/current/unaccent.html
When typing the function documented in postgreSQL, function unaccent();
It is not behaving according to the Dbeaver color standard.

![image](https://user-images.githubusercontent.com/77459233/171065582-76074af9-1d91-481e-bab4-a43e465eeaeb.png)

#### Steps to reproduce, if exist:
open Dbeaver
type SELECT unaccent('coffee');
run the command

#### Include any warning/errors/backtraces from the logs
nothing

**Comment by wellbigas** [comment]
> #### System information:
> * Operating system (distribution) and version : Windows 11
> * DBeaver version : Version 22.0.5.202205220912
> * Additional extensions: noting extensions
> 
> #### Describe the problem you're observing:
> the documentation in one post do postgreSQL: https://www.postgresql.org/docs/current/unaccent.html When typing the function documented in postgreSQL, function unaccent(); It is not behaving according to the dbiever color standard.
> 
> ![image](https://user-images.githubusercontent.com/77459233/171065582-76074af9-1d91-481e-bab4-a43e465eeaeb.png)
> 
> #### Steps to reproduce, if exist:
> open Dbiever type SELECT unaccent('coffee'); run the command
> 
> #### Include any warning/errors/backtraces from the logs
> noting

**Comment by LonwoLonwo** [comment]
Thanks for the report @wellbigas

**Comment by LonwoLonwo** [comment]
Implemented in DBeaver 22.1.0

![2022-05-31 11_31_30-DBeaver Ultimate 22 1 0 - _postgres 13 3_Script-159](https://user-images.githubusercontent.com/45152336/171129879-b2d13891-639c-4370-ac12-ae5b51087fbf.png)
