### ISSUE TITLE
Authentication failed with Salesforce CDP

### ISSUE THREAD

**Issue by santiagomolinadecastro** [dbeaver/dbeaver#16652]
Hi all !!

I'm getting an error when i try to connect with my Salesforce CDP environment. The error says "Authentication failure".

I think that is because salesforce CDP ask a verification code (multi factor authentication). I don't now if dbeaver supports this kind of authentication, but i'm not sure. 

Thanks!

**Comment by LonwoLonwo** [comment]
Can you please provide a full error log? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by uslss** [comment]
there has been no update for a long time.
If the issue is still actual, feel free to reopen it and add log files.
