### ISSUE TITLE
About filtering features

### ISSUE THREAD

**Issue by javen46** [dbeaver/dbeaver#16659]
At present, the "filtering function" hopes to be further optimized, and the style is as intuitive and simple as the filtering function of Navicat;
I hope the bottom column can display the total number of data. Thank you.
About filtering features
![shauixuan6](https://user-images.githubusercontent.com/106662597/171375025-66d50094-5567-4fac-a1e8-f956497e0b93.png)

**Comment by E1izabeth** [comment]
Related to https://github.com/dbeaver/dbeaver/issues/16289

**Comment by E1izabeth** [comment]
@javen46, I'll close this issue as duplicate. DBeaver has not the same, but similar functionality. Please, see how to do the same in DBeaver and answer, does it satisfy your needs or not. Have you met something that you can't do with DBeaver?
