### ISSUE TITLE
Number of large CSV import rows exceeds int.

### ISSUE THREAD

**Issue by qsxzaqq** [dbeaver/dbeaver#16650]
Number of large CSV import rows exceeds int.

class: org/jkiss/dbeaver/tools/transfer/stream/importer/DataImporterCSV.java
method:  runImport

"int lineNum"

**Comment by qsxzaqq** [comment]
![Z)I{_LYK6OZ0X_F~)70Z(ME](https://user-images.githubusercontent.com/29307369/171210484-08e6c963-eb0b-46a9-b324-29f782d47108.png)

**Comment by LonwoLonwo** [comment]
Thanks for the report @qsxzaqq
