### ISSUE TITLE
序列导出数据文件.csv后，然后导入，导入后在表下新生成了一个表。序列节点下，没有此序列

### ISSUE THREAD

**Issue by luyunfei11** [dbeaver/dbeaver#16658]
#### System information: 
- Operating system (distribution) and version ：windows10
- DBeaver version：22.0.4.202205011839
- Additional extensions

#### Connection specification:
- Database name and version： postgres
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? on

#### Describe the problem you're observing:
After the sequence exports the data file .csv, and then imports it, a new table is created under the table after the import. Under the sequence node, there is no such sequence
![image](https://user-images.githubusercontent.com/56383213/171363853-fe6ee098-9b3b-4fa1-a319-7209df7ca9a7.png)
![image](https://user-images.githubusercontent.com/56383213/171364072-3f45b664-6741-4320-8f96-711608a7a596.png)

**Comment by LonwoLonwo** [comment]
Hello @luyunfei11 

By default, DBeaver creates tables during the data import, not sequences.

![2022-06-01 11_50_12-Data Transfer](https://user-images.githubusercontent.com/45152336/171366752-52bcde3f-423d-4de7-aa3d-34bc8685771a.png)

Also, I'm not sure you can add data to the sequence table. What is your goal?

![2022-06-01 11_54_06-Event](https://user-images.githubusercontent.com/45152336/171366731-ab9a2738-c263-4b1b-9a4c-9f15d134c863.png)

**Comment by luyunfei11** [comment]
Under normal circumstances, when exporting a sequence, the original sequence should be restored under the sequence node after importing. I would like to know what is the reason why the table is directly generated after importing? Why is it designed this way?

**Comment by LonwoLonwo** [comment]
> Why is it designed this way?

That's because DBeaver is a universal database tool. And many other databases use sequences not as tables. For this reason, DBeaver's data transfer creates only tables.

**Comment by ShadelessFox** [comment]
Hello @luyunfei11,

Sequences do not store any data, you can't insert data in them, only retrieve it.

Can you please tell me more about your workflow? What are you trying to accomplish?

Thanks.

**Comment by ShadelessFox** [comment]
If you want to create a copy of your sequence, you can take its DDL, execute it, and then use the `setval` function to set the sequence's current value. See https://www.postgresql.org/docs/current/functions-sequence.html
