### ISSUE TITLE
SQL Server: ResultSet is read-only when column aliases are used

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#16669]
#### System information: 
- Operating system (distribution) and version Win
- DBeaver version 22.1.0.202205310836

#### Connection specification:
- Database name and version SQL Server

#### Steps to reproduce, if exist:
Write a select statement with column aliases in the SQL Editor and execute it

**Expected**: the table can be edited in the ResultSet
**Actual result**: the table is read-only

![dbeaver_1Xon8HvI3O](https://user-images.githubusercontent.com/51405061/171444408-5fdf0905-b269-4337-8c97-82c636b96878.png)

**Comment by uslss** [comment]
it is impossible to update the table in case the PK column has the alias

![image](https://user-images.githubusercontent.com/31996417/172398675-d9d5abeb-365d-4d64-9a2b-1a7f3f8a00da.png)

**Comment by serge-rider** [comment]
Fixed for all databases.
Now WHERE clause containes resolved column names instead of aliases
