### ISSUE TITLE
Oracle query is painfully slow

### ISSUE THREAD

**Issue by cherfim** [dbeaver/dbeaver#16664]
#### System information: 
- Operating system (distribution) and version MacOS Monterey 12.0.1
- DBeaver version Version 22.0.5.202205220912
- Java version java version "17.0.2" 2022-01-18 LTS
- Additional extensions

#### Connection specification:
- Database name and version Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
- Driver name oracle.jdbc.OracleDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When running a simple SELECT query in the SQL Console, the execution time is painfully slow compared to when I run the command on the server via sqlplus or even in DBeaver when I right click and export from the query. the attached image shows an example where a query took more than 8 minutes to finish, but when I exported a CSV from the query it finished within 3-4 seconds !

#### Steps to reproduce, if exist:
not sure if this is reproducible for anyone else or a problem with my setup, but just running a SELECT that returns a medium amount of rows. I have already selected all the performance flags in settings (use RULE, use metadata optimizer...).

#### Include any warning/errors/backtraces from the logs

<img width="1058" alt="Screen Shot 2022-06-01 at 4 29 14 PM" src="https://user-images.githubusercontent.com/2437153/171422066-6747bda7-e971-4fc5-a719-d4ed325e7e30.png">

**Comment by serge-rider** [comment]
Did you try to play with performance settings:
![image](https://user-images.githubusercontent.com/6398845/171585785-1c9933b1-c6ee-422f-be22-aab5f1ed834b.png)

Changing Oracle metadata loading settings may increase system catalog queries performance in 10-100 times.

**Comment by cherfim** [comment]
As stated in the problem description, I already have all the performance flags checked; the query with 8 minutes runtime was run with them:
<img width="682" alt="Screen Shot 2022-06-02 at 9 51 39 PM" src="https://user-images.githubusercontent.com/2437153/171706803-277cd1d7-3f15-4f25-91fb-c96354508b1d.png">

**Comment by LonwoLonwo** [comment]
DBeaver reads your metadata to show your data correctly.

Yes, you can use "Performance" flags, but I'm recommended not to use them all. At least, it's not "search metadata on synonyms" - it's usually decreasing performance.

Also, you can turn off auto-completion at all.
The performance will be higher in this case, but auto-complete will not be working.
![2022-06-13 17_42_40-DBeaver Ultimate 22 1 0 - _demo2 2_Script-167](https://user-images.githubusercontent.com/45152336/173380776-bb8004a8-463d-4535-bfbe-10a92c00e37e.png)

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual, feel free to reopen it.

**Comment by zoro956** [comment]
unfortunately there is still this issue, dbeaver (23.0.4) is impossible to use for Oracle database :(

**Comment by E1izabeth** [comment]
Does it (https://github.com/dbeaver/dbeaver/issues/16664#issuecomment-1154020340) help?

**Comment by zoro956** [comment]
I will try, I didn't expect this can be connected. But I use auto completion daily, I will miss it.

**Comment by E1izabeth** [comment]
Please let me know, when you try. We need to understand, what exactly is the slowing factor, to fix it.

**Comment by zoro956** [comment]
it seems that #16664 fix helped in some way. Maybe it's just feeling, but the client is faster.
The bad think is that I've lost autocomplete function.
Maybe that help with finding a source of this error.

**Comment by zoro956** [comment]
it seems that #16664 fix helped in some way. Maybe it's just feeling, but the client is faster.
The bad think is that I've lost autocomplete function.
Maybe that help with finding a source of this error. this error.
