### ISSUE TITLE
copy as sql return bad result if the result is sorted

### ISSUE THREAD

**Issue by Heliner** [dbeaver/dbeaver#16674]
#### System information: 
- Operating system (distribution) and version  Windows 11 21H2
- DBeaver version     22.0.5.202205220912
- Additional extensions

#### Connection specification:
- Database name and version   5.6.28-cdb2016-log
- Driver name   com.mysql.cj.jdbc.Driver  Driver for MySQL 8 and later
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

copy as sql return bad result if the result is sorted

#### Steps to reproduce, if exist:
```sql
CREATE TABLE `foo` (
  `a` int(10) unsigned NOT NULL DEFAULT '0' ,
  `b` int(10) unsigned NOT NULL DEFAULT '0' 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


insert into foo(a,b)value(1,1001);
insert into foo(a,b)value(2,2001);
insert into foo(a,b)value(3,3001);
insert into foo(a,b)value(4,4001);

# select result
select * from foo;

```
prepare data for table `foo`
![image](https://user-images.githubusercontent.com/32272517/171527620-285442c5-8143-4b9f-95fb-1bb9c7ddfa70.png)
we click line 3 which value is `(3, 3001)`and `copy as sql` will get result `INSERT INTO foo (a,b) VALUES (3,3001);`
that's ok~
click the button and let `a` col desc like this
![image](https://user-images.githubusercontent.com/32272517/171527874-227522da-57ad-4a68-b921-2ddaf2f3bea0.png)
then clien line 3 which value is `(2,2001)` and `copy as sql` will get result `INSERT INTO foo (a,b) VALUES (3,3001);` , actually expect result is `INSERT INTO foo (a,b) VALUES (2,2001);`
![image](https://user-images.githubusercontent.com/32272517/171528023-6edebf90-18f2-4fb6-bb1f-64cd16c61fed.png)

#### Include any warning/errors/backtraces from the logs

[log.log](https://github.com/dbeaver/dbeaver/files/8819807/log.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/8819810/dbeaver-debug.log)

**Comment by emironovDB** [comment]
Hello @Heliner,

Thanks for the bug report. As a workaround, you can disable client-side ordering in the preferences.

**Comment by Heliner** [comment]
> 

ths, I will  try it
