### ISSUE TITLE
Remove setting for Delete Object confirmation

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#16680]
We need to remove setting for Delete Object confirmation 
It is not safety setting
To find this preference go to Window->Preferences->User Interface->Confirmations->Delete Object

**Comment by LonwoLonwo** [comment]
I do not see it in the current version:

![2023-01-09 13_00_00-DBeaver 22 3 1 - _postgres_ Script-95](https://user-images.githubusercontent.com/45152336/211282723-60cf1b35-cd58-4433-aa1f-bf44c6c893bd.png)

We probably removed it earlier.
