### ISSUE TITLE
[MySQL] Can't use calendar in value panel for date\time\timestamp\datetime values 

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#16683]
#### System information: 
- Win11
- DBeaver CE 22.1.0

#### Connection specification:
- MySQL

#### Describe the problem you're observing:
https://user-images.githubusercontent.com/43252954/171619109-e9027c7b-86a8-4c25-bb9d-73963b050d4a.mp4

#### Steps to reproduce, if exist:
Set focus to the datetime format and open Value panel. 
Click on this icon for the calendar -> you'll get the error
![image](https://user-images.githubusercontent.com/43252954/171619733-5e54d0c7-fee5-43ac-a16e-939c50887c8e.png)

**Comment by E1izabeth** [comment]
Is the issue still actual for the latest DBeaver version? I can't reproduce it.
