### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by saingsocheat** [dbeaver/dbeaver#16686]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by LonwoLonwo** [comment]
Hello, please add info in your issue template.

**Comment by ShadelessFox** [comment]
According to the profile, they look like a stats hunter.
