### ISSUE TITLE
Improving the implementation of the EXPLAIN command

### ISSUE THREAD

**Issue by sgrinko** [dbeaver/dbeaver#16684]
Good afternoon,
I am using the Enterprise edition of DBeaver

Now Dbeaver has a function to get the plan of the query being executed.
However, at the moment:
- Version 22.0.0.202203131528
no support for all possible options for the EXPLAIN command
For Postgres 14 (latest current version) these options are: `ANALYZE`, `VERBOSE`, `COSTS`, `SETTINGS`, `BUFFERS`, `WAL`, `TIMING`, `SUMMARY`.

Currently only supported:
`ANALYZE` (can be controlled) + parameters that have `True` by default: `COSTS` and `TIMING`.

Please add other options to enable them on request.

Why is it important to use `BUFFERS` in your work:
- Nikolai Samokhvalov wrote very well about this:
https://postgres.ai/blog/20220106-explain-analyze-needs-buffers-to-improve-the-postgres-query-optimization-process#recommendations-to-content-creators (en)
https://www.youtube.com/watch?v=qCLRyF4qChI (ru)
https://www.youtube.com/watch?v=TEIXS3qOci0 (ru) (at 53 minutes, a conversation with a developer from DBeaver)

Other options are also important  :) 

I also ask you to give the opportunity to see the full query plan in the form of text, the `FORMAT TEXT` option

Thank you very much for your product, I really hope for your understanding and implementation of this in the next releases.

**Comment by LonwoLonwo** [comment]
Thanks for the idea and for the investigation @sgrinko

**Comment by uslss** [comment]
#13030
