### ISSUE TITLE
Reset UI settings doesn't work on mac

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#16693]
#### System information: 
- Macos
- DBeaver CE 22.1.0

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/43252954/171834263-f8b5ef41-5efc-4084-95d9-24b2eed68b04.png)
  Steps to reproduce:
1. Hide toolbar with window->appearance->Hide toolbar
2. Edit->reset UI settings
Expected: the ui settings rejected
Actual: this action doesn't affet on ui settings and, for example, the toolbar is still hided
4.

**Comment by LonwoLonwo** [comment]
Looks familiar https://github.com/dbeaver/dbeaver/issues/14083

**Comment by ShadelessFox** [comment]
#18474

**Comment by Matvey16** [comment]
UI settings reset still doesn't work at all on Mac in 22.3.1

**Comment by arhayka** [comment]
Let's try to delete properties on the application start. Use a special file or property for it.

**Comment by ShadelessFox** [comment]
Let's perform all necessary operations on DBeaver startup rather than during shutdown.
