### ISSUE TITLE
Inconsistent behaviour with table valued function and result set limit

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#16694]
#### System information: 
- Database: Microsoft SQL Server 2019 (RTM-CU16) (KB5011644) - 15.0.4223.1 (X64) 
	Apr 11 2022 16:24:07 
	Copyright (C) 2019 Microsoft Corporation
	Express Edition (64-bit) on Linux (Ubuntu 20.04.4 LTS) <X64>
- DBeaver Version 22.0.5.202205220912

#### Connection specification:
- Driver Microsoft JDBC Driver for SQL Server connected over LAN
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

A table-valued function is restricted by the ResultSet fetchSize:

**select 'F' as "Type",Count(*) as "Families",sum(NumMembers) as "Rows" from dbo.fn_Families(0);**
returns
Type Families   Rows
 F	1280	2501

1280 is the ResultSetFetchSize set in Global Settings. Both numbers are incorrect.

The correct result can be  'forced' - using a union produces the correct result:
**select 'Dummy',1,1
union
select 'Function' as "Type",Count(*) as "Families",Sum(NumMembers) as "Rows" from dbo.fn_Families(0);**
returns
Type        Families   Rows
Dummy	1             1
Function	6054       12000

These are the correct numbers. It can be seen that in the union query the output of the table-valued function fn_Families is not limited by the ResultSetFetchSize and when the function is called on its own, the result set is incorrect.

Microsoft SSMS gives the correct result for the function call; This puts the the use of table-valued functions in DBeaver into doubt as the results could be unreliable.

**Comment by Matvey16** [comment]
@PaulSlater25 I was not able to reproduce this issue. Can you tell me if something in my test is different and could have influenced the result

my function:

```SQL
CREATE FUNCTION [dbo].table_val
(  @parameter_name AS int
  
)
RETURNS TABLE
    AS
    RETURN (  select * from dbo.emails )
;
```

![dbeaver_I6qeNR3Fkg](https://user-images.githubusercontent.com/82543000/173818939-9dc1924e-2158-4df7-82c5-0e38ad231aed.png)

![dbeaver_kHEVPdECsJ](https://user-images.githubusercontent.com/82543000/173819955-7a4f7974-1a1b-4fbe-92b4-4cd3dd3d6387.png)

**Comment by ghost** [comment]
The problem must be in the way that the function is declared:

-- Declaration as required (multiple statements needed inside function – see original method below)
CREATE FUNCTION dbo.fn_Passengers()
RETURNS @Response TABLE(LastName varchar(64),FirstName varchar(64))
BEGIN
       INSERT INTO @Response 
       SELECT LastName,FirstName
       FROM txns.Passengers
       ORDER BY 1,2;
       RETURN;
END

select Count(*) from dbo.fn_Passengers();
-- Returns 1280, the size of the ResultSet fetch size
-- In SSMS returns 12000

select Count(*) from txns.Passengers;
-- Returns 12000, the correct number of rows

-- Simple declaration
CREATE FUNCTION dbo.fn_PassengersToo()
RETURNS TABLE
AS
       RETURN (
       SELECT LastName,FirstName
       FROM txns.Passengers);

select Count(*) from dbo.fn_PassengersToo();
-- Returns 12000

 


-- This is the original method…..

CREATE function dbo.fn_Families(@argSize tinyint = 0)
returns @Response table(LastName varchar(64),FirstId int,LastId int,NumMembers tinyint)
begin
       declare @varLowSize tinyint;
       declare @varHighSize tinyint;
       if @argSize = 0
              begin
                     set @varLowSize = 0;
                     set @varHighSize = 99;
              end
       else
              begin
                     set @varLowSize = @argSize;
                     set @varHighSize = @argSize;
              end;
       with Families(LastName,Mini,Maxi,Num) as      
       (
              select distinct p.LastName,
                     Min(p.Id) over (partition by LastName,StreetAddress order by Id rows between 6 preceding and current row) as "Min",
                     Max(p.Id) over (partition by LastName,StreetAddress order by Id rows between current row and 6 following) as "Max",
                     Count(*) over (partition by LastName, StreetAddress) as "Num"
                     from txns.Passengers p
       )
       insert into @Response 
       select LastName,Mini,Maxi,Num
       from Families
       where Num between @varLowSize and @varHighSize
       order by 1,2;
       return;
end

**Comment by Matvey16** [comment]
@ghost Have you tried enabling `use SQL to limit fetch size` in data editor properties?

**Comment by uslss** [comment]
there has been no update on the issue for a long time. If it is still actual - feel free to reopen it
