### ISSUE TITLE
Spreadsheet: Refactor model to support nested rows

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#16695]
Currently, our presentation model is unaware of collection elements and other stuff. That's why we have complex value editors.

There's not a lot of information regarding this issue because it's about development.

This ticket is a part of #12148.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/174446355-2bf86b0b-686b-4eb9-b36f-54d58d755409.png)
