### ISSUE TITLE
(minor bug) sorting order fields for filtering

### ISSUE THREAD

**Issue by JeroenNienhuis** [dbeaver/dbeaver#16700]
When setting up a filter for an integer or a numerical field using the gui and the values are ordered, the sorting order is aphabetical instead of numerical.
![afbeelding](https://user-images.githubusercontent.com/51078213/171847350-7eeb99b1-a3c7-4771-81e7-673ebe6a276b.png)

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @JeroenNienhuis
