### ISSUE TITLE
Improve path readability for ER diagrams with attribute associations

### ISSUE THREAD

**Issue by Destrolaric** [dbeaver/dbeaver#16703]
In the current form, multiple associations unite into a singular line pointing to an attribute sometimes it may cause problems with readability. Probably we need some kind of connector, for multiple lines.

Require to implement:

Decorators should not overlap entity
Orthogonal pathes should not overlap each other (more preferable is parallel way of connection)
Nice to have
Bridge decoration in case of intersection
Rounded intersections

**Comment by serjiokov** [comment]
Require to implement: 
1. Decorators should not overlap entity 
2. Orthogonal pathes should not overlap each other (more preferable is parallel way of connection) 
Nice to have 
3. Bridge decoration in case of intersection
4. Rounded intersections
