### ISSUE TITLE
[Wayland] Data can't be edited inline after double click

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#16705]
#### System information: 
- Operating system (distribution) and version Ubuntu 22.04
- DBeaver version 22.1.0

#### Steps to reproduce, if exist:
1. Double-click on any cell in data editor
2. Input something

**Expected:** Data in a cell is replaced with the input
**Actual:** Nothing happens

**Comment by uslss** [comment]
#5322

**Comment by flambchap** [comment]
It's a Wayland-specific issue.

**Comment by Destrolaric** [comment]
Yep, confirmed in Debian Gnome on Wayland. And was not reproduced in Debian KDE on X11

**Comment by serge-rider** [comment]
It breaks value save on focus change (by mouse click)
