### ISSUE TITLE
Improve confirmation dialogs

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#16702]
We need to rethink the properties that allow or stop confirmations for different actions.

1. Change the name of the Value column and change drop-down list to checkboxes
2. Backward compatibility
3. Add Tooltips for all the confirmations
4. Correct names of some confirmations (e.g. server-side ordering)
5. Swap group and value columns
6. Move confirmations to options:
 - Close extra result tabs
 - Keep open cursor
 - Open exported file
 - Download new version

**Comment by E1izabeth** [comment]
We also need to change the confirmation message on restore database action. See https://github.com/dbeaver/dbeaver/discussions/16395#discussioncomment-3041666

**Comment by E1izabeth** [comment]
I think we need to rename
Confirm dangerous query execution -> Execute dangerous queries
Confirm massive parallel queries execution -> Execute massive parallel queries
Confirm drop table query execution -> Execute drop table queries
