### ISSUE TITLE
Debatable supported databases

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#16713]
**Is your feature request related to a problem? Please describe.**
Enterprise version supports [these databases](https://dbeaver.com/databases) and it is obvious.
Community version is unclear instead. For example, is `Sybase/SAP ASE` compatible?

**Describe the solution you'd like**
Add a specific page at the beginning of documentation with supported databases.

**Useful but not mandatory**
Add a specific page with supported databases at dbeaver.io.
i.e: dbeaver.io/databases `--like for enterprise version`

**EDIT**
[Accordingly to homepage](https://github.com/dbeaver/dbeaver#dbeaver): _Supports any database which has JDBC driver (which basically means - ANY database). [Commercial versions](https://dbeaver.com/download/) also support non-JDBC datasources such as MongoDB, Cassandra, Couchbase, Redis, BigTable, DynamoDB, etc._ You can find the list of all databases supported in commercial versions [here](https://dbeaver.com/databases/).

**This does not clarify as much as create a dedicated docs page. It is faster and useful to link all supported databases in an all-in-one page (maybe with links to docs of each database). It is more tidy too instead of having a messy list in the project's homepage.** 

**Additional context**
![specific](https://user-images.githubusercontent.com/97399553/172163449-f63674fb-7410-4d99-be69-375ecf492b7d.png)
![nonspecific](https://user-images.githubusercontent.com/97399553/172163743-84610a8d-7d4b-48f9-9aa7-ffd29af5abcb.png)

**Comment by LonwoLonwo** [comment]
Ok, maybe we can add a list of supported databases to our wiki https://github.com/dbeaver/dbeaver/wiki

**Comment by LonwoLonwo** [comment]
Thanks for the report

**Comment by dovatti** [comment]
Thank you too! If I had time I'll help with it!

**Comment by ghost** [comment]
Thanks! I'll help with that!

**Comment by flambchap** [comment]
I suspect that the list on our website does not cover all databases we support.

**Comment by ghost** [comment]
> I suspect that the list on our website does not cover all databases we support.

Exactly, it doesn't. I think it should be more clear, almost in the docs.
That's the reason why I've been opening this issue 😄 
I think we could make things easier for everyone - even for ourselves - if we just create better documentation.

**Comment by emironovDB** [comment]
@dovatti 
Hi
Thank you for your request.
We added the complete list of supported databases in the DBeaver Community Edition. 
Please, learn it here https://dbeaver.io/about/

We also updated the list of the supported databases in DBeaver PRO https://dbeaver.com/databases/ and our web application CloudBeaver https://cloudbeaver.io/features/#sql-and-nosql

If you have any questions, please fill free to reopen this ticket.
