### ISSUE TITLE
Attempt to repeatedly automatically download driver becomes annoying if you are behind a firewall

### ISSUE THREAD

**Issue by chbussler** [dbeaver/dbeaver#16718]
Since the last release dbeaver attempts to automatically download drivers. In my environment this is impossible, I have to do that manually. However, even to get to the manual driver manager page causes continuous popup of the automatic download windows. This is very annoying as I have to constantly cancel out, just for those windows to pop up again.

Please change the logic to try once, and then never again automatically, only on user request so that as a user if I exit out once, it'll not try to automatically download this anymore.

Thank you.

**Comment by LonwoLonwo** [comment]
Hello @chbussler 
What DBeaver version do you use?
What OS do you use?
For what database is DBeaver attempting to download drivers automatically?

**Comment by chbussler** [comment]
Hi - 
version that had this behavior after installing: 22.0.5.202205220912
OS: Windows as well as Linux
Database: PostgreSQL

Thank you.

**Comment by E1izabeth** [comment]
Have you tried to delete libraries that can't be downloaded from this list?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/00787b73-97bc-47fd-892a-0b6617e46f0f)

**Comment by chbussler** [comment]
Hi - thanks for following up. After some research we figured out how to set a proxy and now the downloading works.

The key behavior change in DBeaver would be that if there is no connectivity, it is maybe recorded instead of a constantly popping up window. Only my 2 cents.

Thank you!

**Comment by E1izabeth** [comment]
Thank you for update.

**Comment by hrimthrusa** [comment]
Hello there.
Here is a workaround you might find convenient. 

You may create a copy of your driver and have your own version always in place. 

Please follow Database _(main toolbar)_ -> Driver Manager, highlight the driver you are interested in and click _Copy_. Please provide the path to the **.jar** file of your driver in the _Libraries_ tab of _Create new driver_ window as picture shows.


![copy driver](https://github.com/dbeaver/dbeaver/assets/97725836/517d6df3-2cd8-49f4-a8d0-5f677eb9ea22)


You may then create a _New Database Connection_ with the copy of your driver. It will be visible in the list of the available drivers.


![connect to a database](https://github.com/dbeaver/dbeaver/assets/97725836/1b901807-65cf-487d-b50f-15881bcb7506)



Please let us know if that helps.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
