### ISSUE TITLE
Drop table warning on drop index.

### ISSUE THREAD

**Issue by JaanOras94** [dbeaver/dbeaver#16724]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows 10 Pro 10.0.19044 Build 19044
- DBeaver version: 22.1.0.202206051253
- Additional extensions: None

#### Connection specification:
- Database name and version: Postgresql 13
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing:
When trying to drop basic index, I get warning that I'm droping table.
Luckily it drops only index.

#### Steps to reproduce, if exist:

Create index and try to drop it.

#### Include any warning/errors/backtraces from the logs

No errors or anything.
![dbeaver_drop_table_warning](https://user-images.githubusercontent.com/67792795/172347237-0b84d295-234f-4086-9e3d-ab03580c4e0f.png)

**Comment by E1izabeth** [comment]
Thank you for bug report!

**Comment by JaanOras94** [comment]
Just a suggestion, would it be hard to not warn when dropping constraints and other things that are not related to data?

**Comment by E1izabeth** [comment]
I'll see what can be done. Thank you for suggestion.
