### ISSUE TITLE
Bind Parameter(s) not picking up parameters inside $$    $$

### ISSUE THREAD

**Issue by WigraiTH** [dbeaver/dbeaver#16721]
#### System information: 
- Operating system
      - Windows 10
- DBeaver version    
       - from 22.0.2 up

#### Connection specification:
- Database name and version   
       - PostgreSQL 13.3   
- Driver name
 		- postgresql-42.2.5.jar
		- postgis-jdbc-2.2.21.jar
		- postgis-geometry-2.5.0.jar

- Do you use tunnels or proxies (SSH, SOCKS, etc)?  
       -   SSL enabled
- Additional database module 
      - tablefunc 

#### Describe the problem you're observing:
   Bind Parameter(s) Dialog does not pick up parameters inside `crosstab($$  ... $variable_name ...  $$)`. It worked until version 22.0.1.

**Comment by E1izabeth** [comment]
Hi, @WigraiTH! Does your `Show $$ quote as` preference is set to `String` ?
![image](https://user-images.githubusercontent.com/28875055/172339755-62da56a6-7399-4c43-a1e5-59a99602863d.png)

**Comment by WigraiTH** [comment]
Thanks for quick response, Elizabeth. 

No, I have "Code block".  I changed it back and forth, and it still does not work.

![image](https://user-images.githubusercontent.com/26840191/172343054-3f771ebf-06ff-4d0c-a492-8b10ff43938a.png)

**Comment by E1izabeth** [comment]
@WigraiTH, thanks for reply.
Could you show me your SQL Processing settings page?
![image](https://user-images.githubusercontent.com/28875055/172344178-3c2c7d15-5a22-4026-858b-dd45a21a4d79.png)

You can open it through common Preferences or Clicking to Preferences icon in the left-side bar of sql editor.

**Comment by E1izabeth** [comment]
Please, note that to turn on SQL parameters dialog `Show $$ quote as` preference should be set to `Code block`

**Comment by WigraiTH** [comment]
Please find it below (v 22.1.0.xx). 

The difference is "Enable parameters in DDL and $$ blocks". I ticked it on and off for testing, and it is still not working.

![image](https://user-images.githubusercontent.com/26840191/172345243-7dd41a6e-6e22-43c3-aacb-b3a18a1a0fe9.png)

**Comment by E1izabeth** [comment]
@WigraiTH, I see, thank you. Please, set `Show $$ quote as` preference to `String`. It works for me

**Comment by WigraiTH** [comment]
> Please, note that to turn on SQL parameters dialog `Show $$ quote as` preference should be set to `String`

I did change it to both 'String' and 'Code black'. It still does not work.

**Comment by Matvey16** [comment]
Helllo @WigraiTH . Is it possible for you to show the DDL of that function? The only way for me to stop it from working was to disable this option in preferences

![image](https://user-images.githubusercontent.com/82543000/172841416-65cbecf1-0cf3-458e-b544-eb36c78300ee.png)

Also can you add what exactly happens after you execute  the script?

**Comment by WigraiTH** [comment]
Hi @Matvey16 , Disabling "SQL parameters" leaded to another different error (below) as same parameters are also used outside \$$ blocks. If possible, we would like to use parameters in SQL statement including \$ blocks.

![image](https://user-images.githubusercontent.com/26840191/172964156-c4d5f65f-8d90-4fea-98bb-c7f4e7509258.png)

**Comment by WigraiTH** [comment]
The outputs below are to compare between v.22.0.1 and v.22.0.2 (up) when executing the same SQL statement.

v.22.0.1  - All parameters picked up properly
![image](https://user-images.githubusercontent.com/26840191/172964974-646c7847-17ac-4366-9486-45a1a7771eee.png)

From v.22.0.2  - Only parameter OUTSIDE $ block picked up.
![image](https://user-images.githubusercontent.com/26840191/172965106-d5de0bec-d37e-4e98-8063-0c19d4ec1793.png)

**Comment by E1izabeth** [comment]
Since 22.0.2 the manage of use or not to use parameters inside $$-blocks was supposed to work via `Enable parameters in DDL and $$..$$ blocks` due to this request https://github.com/dbeaver/dbeaver/issues/15106. 
But it seems that something is broken.
Thank you so much for your bug report, @WigraiTH.

**Comment by WigraiTH** [comment]
Thank you, @E1izabeth , for your assistance.

**Comment by E1izabeth** [comment]
The bug was fixed along with https://github.com/dbeaver/dbeaver/issues/15369. You can check it in DBeaver 22.1.2.
Feel free to reopen the issue if you encounter the same problem.

**Comment by WigraiTH** [comment]
Hi @E1izabeth , This issue has been fixed since 22.1.2 with "Enable parameters in DLL and $$ blocks" ticked. Thanks a lot for your and the team's help.
