### ISSUE TITLE
Mac Universal control disrupts grid scrolling

### ISSUE THREAD

**Issue by RoaldG** [dbeaver/dbeaver#16722]
#### System information: 
- macOS Monterey 12.4 and iPad mini 6 with iOS 15.5
- DBeaver 22.1.0.202206051253
- No extensions

#### Connection specification:
- N/A
- N/A
- N/A

#### Describe the problem you're observing:
When enabling Universal Control on the Mac the query result grid scrollbars no longer show by default. Only way to show them is to scroll and then quickly click and hold on them.

#### Steps to reproduce, if exist:
1. Disable Universal control in macOS settings
2. Validate scrollbars showing in result grid
3. Turn on Universal control (Link mouse/keyboard and/or Extend display 
4. Check result grid, scrollbars not showing, only when actively scrolling with mouse wheel 
5. Turn off Universal Control (disconnect display on iPad mini) 
6. Validate scroll bars showing again in result grid

#### Include any warning/errors/backtraces from the logs
N/A

**Comment by Destrolaric** [comment]
Hi, I was unable to reproduce mentioned issue. Could you provide a video that demonstrates it?

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it with additional info
