### ISSUE TITLE
Import connections from SQLDeveloper

### ISSUE THREAD

**Issue by Ferrox12** [dbeaver/dbeaver#16737]
Hi,
is there a method to import all the connections and the related passwords from SQLDeveloper to DBeaver?

**Comment by Ferrox12** [comment]
I've found the function to import the connections!

**Comment by LonwoLonwo** [comment]
Can you provide some instructions here please @Ferrox12 

It can be helpful for other users with this question.

**Comment by Ferrox12** [comment]
You have to click on File > Import > Third Party Configuration > Oracle SQL Developer
