### ISSUE TITLE
Export query results to a file, no data

### ISSUE THREAD

**Issue by Iatbzh** [dbeaver/dbeaver#16735]
#### System information: 
- Operating system (distribution) and version 
windows10
- DBeaver version
20.0
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When exporting multiple queries to one file, there is no data in the file，it is recommended to fix bugs and wish to export multiple query results to the same file, one query result per sheet

**Comment by LonwoLonwo** [comment]
Hello @Iatbzh 
Which type of export did you use?
How many queries did you have?

**Comment by Iatbzh** [comment]
There are 7 query statements in Excel and CSV
select * from test1 where serverid = 6277581 order by time desc;
select * from test2 where serverid  = 6277581 order by time desc;
select * from test3 where serverid  = 6277581 order by time desc;
select * from test4 where serverid  = 6277581 order by time desc;
select * from test5 where serverid  = 6277581 order by time desc;
select * from test6 where serverid  = 6277581 order by time desc;
select * from test7 where serverid  = 6277581 order by time desc;

**Comment by Iatbzh** [comment]
There are 7 query statements in Excel and CSV
select * from test1 where serverid = 6277581 order by time desc;
select * from test2 where serverid  = 6277581 order by time desc;
select * from test3 where serverid  = 6277581 order by time desc;
select * from test4 where serverid  = 6277581 order by time desc;
select * from test5 where serverid  = 6277581 order by time desc;
select * from test6 where serverid  = 6277581 order by time desc;
select * from test7 where serverid  = 6277581 order by time desc;

**Comment by LonwoLonwo** [comment]
Sorry, I can't reproduce your issue.

![2022-06-08 16_06_09-export_202206081605 csv — H__asya_special_dbeaver_backup — Atom](https://user-images.githubusercontent.com/45152336/172623959-c3a25962-bba5-4bee-aff7-795cdaa85004.png)

Can you please provide your datatransfer settings?

**Comment by Iatbzh** [comment]
The table you exported has no field name, and you cannot tell which statement is the result of execution. Is this expected

**Comment by LonwoLonwo** [comment]
What is the point to export all result of queries in the one file then, if you can export data to different files (and this is default behavior)?

**Comment by emironovDB** [comment]
there has been no update on the issue for a long time.
If it is still actual - feel free to reopen it.
