### ISSUE TITLE
Cannot Edit Postgres Enum Columns: Column "ColumnName" is read-only: No corresponding table column

### ISSUE THREAD

**Issue by davious** [dbeaver/dbeaver#16733]
#### System information: 
- DBeaver version 22.1.0 CE ... regression from 22.0.5 CE

#### Describe the problem you're observing:

When you try to edit any enum cell from either a View Data or Read Data in SQL Editor, DBeaver prevents the edit with a Column "ColumnName" is read-only: No corresponding table column message

and there is not autocomplete list shown

btw. DBeaver 22.0.5 works fine... and even better than I'm used to because, for a long while, I wasn't able to edit with Read Data in SQL Editor only with View Data

**Comment by talski** [comment]
This message also shows on all enum columns here, no more autocomplete list

**Comment by LonwoLonwo** [comment]
Can you provide more info please? Screenshots will be very beneficial.

**Comment by davious** [comment]
I was able to cell edit these in 22.0.5 CE

## Cell edit with Query Fail w/ReadOnly message
<img width="741" alt="Screen Shot 2022-06-07 at 4 47 30 PM" src="https://user-images.githubusercontent.com/632416/172479628-ef3526fd-a434-41b0-8a04-ecf8fffc1f91.png">

## Cell edit on Table data Fail w/ReadOnly message
<img width="708" alt="Screen Shot 2022-06-07 at 4 46 58 PM" src="https://user-images.githubusercontent.com/632416/172479630-a1567a8e-28dc-4486-937b-626d42bb86b8.png">

**Comment by davious** [comment]
possible dup of #16705

**Comment by LonwoLonwo** [comment]
I can't reproduce for now.

![2022-06-08 10_35_38-DBeaver Ultimate 22 1 0 - _postgres 13 3_Script-163](https://user-images.githubusercontent.com/45152336/172559254-71c3b9df-6fe0-45ef-b667-d4da0998ef53.png)

Can you provide table DDL please?

Also, do you have any other tables in your schema/database with the lower cased names? Is they working fine?

**Comment by davious** [comment]
I've narrowed this down to just citext type fields

example ddl
```
CREATE TABLE test (
     id    integer primary key,
     name   citext
);
```

**Comment by LonwoLonwo** [comment]
Sorry, can't reproduce again.

![2022-06-08 16_28_08-DBeaver Ultimate 22 1 0 - _postgres 13 3_Script-163](https://user-images.githubusercontent.com/45152336/172628917-29ff6839-13f1-43c4-82ac-ce7d7fb65f11.png)

But important note - you need to refresh your schema after table creation in the SQL Editor.

**Comment by talski** [comment]
in the public schema it seems to be working, but if you create a new one, it doesn't

```SQL
--drop TABLE test.ticket; 
--drop TYPE test.status_enum;
--drop SCHEMA test;

CREATE SCHEMA test;

CREATE TYPE test.status_enum AS ENUM ('OPEN', 'AWAITING', 'CLOSED');

CREATE TABLE test.ticket (
	id serial NOT NULL primary key,
	status test.status_enum
);

insert into test.ticket (status) values ('OPEN');
```

**Comment by davious** [comment]
> Sorry, can't reproduce again.
> 
> But important note - you need to refresh your schema after table creation in the SQL Editor.

not sure what to say... I appreciate your trying... I can reproduce... 

* create table
* shut down dbeaver
* read data in Sql Editor
* add new row
* click in name column
* Column is read-only: No corresponding table column

<img width="411" alt="Screen Shot 2022-06-08 at 1 55 28 PM" src="https://user-images.githubusercontent.com/632416/172684698-afb46fba-92e7-4a7a-8fb4-49cf9e791aaf.png">

**Comment by Z1ni** [comment]
I had this problem with all enum fields after upgrading to DBeaver 22.1.0, but updating the PostgreSQL JDBC drivers (under Database -> Driver Manager) fixed the problem.

**Comment by LonwoLonwo** [comment]
I can reproduce with your case @talski 
Thanks

**Comment by davious** [comment]
From my point of view, my issue still exists and my bug report was hijacked. I plan to open another bug report

**Comment by E1izabeth** [comment]
@davious , fix will be available in the next release. Please, check it in 22.1.1. If you encounter the same issue, fill free to reopen this or create another one.

**Comment by adminsyszg** [comment]
@E1izabeth
i have that same problem witch
Version 22.1.2.202207091909
![изображение](https://user-images.githubusercontent.com/70959040/179178226-a96ef2a7-1839-4d1e-a627-79d54596cb74.png)
driver version PG
![изображение](https://user-images.githubusercontent.com/70959040/179178495-70579e38-5fb2-4647-b06e-f810a5ef06ae.png)


ddl
`-- apteka.salestableapreserve definition

-- Drop table

-- DROP TABLE apteka.salestableapreserve;

CREATE TABLE apteka.salestableapreserve (
	recid serial4 NOT NULL,
	dataareaid public.citext NULL,
	tableid int4 NULL DEFAULT 50558,
	createddate timestamp NULL DEFAULT 'now'::text::timestamp without time zone,
	modifieddate timestamp NULL DEFAULT 'now'::text::timestamp without time zone,
	modifiedby public.citext NULL,
	createdby public.citext NULL DEFAULT "current_user"(),
	origrecid int4 NULL,
	custaccount public.citext NOT NULL DEFAULT ''::citext,
	custname public.citext NOT NULL DEFAULT ''::citext,
	custphone public.citext NULL DEFAULT ''::citext,
	delivery bool NOT NULL DEFAULT false,
	deliverydate apteka.transdate NOT NULL DEFAULT 'now'::text::timestamp without time zone,
	dis public.citext NOT NULL DEFAULT ''::citext,
	disccardid apteka.disccardnum NOT NULL DEFAULT ''::citext,
	finishdate apteka.transdate NOT NULL DEFAULT 'now'::text::timestamp without time zone,
	newdisccard bool NOT NULL DEFAULT false,
	"percent" apteka."percent" NOT NULL DEFAULT 0,
	reserveby public.citext NOT NULL DEFAULT ''::citext,
	reservedate apteka.transdate NOT NULL DEFAULT 'now'::text::timestamp without time zone,
	reservedateperiod timestamp NOT NULL DEFAULT 'now'::text::timestamp without time zone,
	reservedeliveryaddrid apteka.reservedeliveryaddrid NOT NULL DEFAULT ''::citext,
	returnreason apteka.returnreasonid NOT NULL DEFAULT ''::citext,
	salesreserveid public.citext NOT NULL DEFAULT ''::citext,
	salesreserverefid public.citext NOT NULL DEFAULT ''::citext,
	salestype public.citext NOT NULL DEFAULT ''::citext,
	status public.citext NOT NULL DEFAULT ''::citext,
	street public.citext NOT NULL DEFAULT ''::citext,
	doorway public.citext NULL,
	deliverytime apteka.reservedeliverytimeid NOT NULL DEFAULT ''::citext,
	hlcard public.citext NOT NULL DEFAULT ''::citext,
	kkmnum public.citext NOT NULL DEFAULT ''::citext,
	inuse bool NOT NULL DEFAULT false,
	built bool NOT NULL DEFAULT false,
	beznal bool NOT NULL DEFAULT false,
	canceled bool NOT NULL DEFAULT false,
	reservetype int4 NOT NULL DEFAULT 1,
	prepaid bool NOT NULL DEFAULT false,
	siteid public.citext NULL,
	CONSTRAINT salestableapreserve_recid PRIMARY KEY (recid),
	CONSTRAINT tableid CHECK ((tableid = 50558))
);
CREATE UNIQUE INDEX salestableapreserve_salesreserveid_idx ON apteka.salestableapreserve USING btree (salesreserveid, status);

-- Table Triggers

create trigger salestableapreserve_geninsert before
insert
    on
    apteka.salestableapreserve for each row execute procedure salestableapreserve_numseq();
create trigger salestableapreserve_modifieddate before
update
    on
    apteka.salestableapreserve for each row execute procedure modifieddate();
create trigger salestableapreserve_update before
update
    on
    apteka.salestableapreserve for each row execute procedure salestableapreserve_update();`

**Comment by SummerHow** [comment]
I have the same problem. while I'm running SELECT statement on a synonyms table, when I try to edit the result, it will say 'Column "REGION" is read-only: No corresponding table column'. Unfortunately, Navicat shows the same tip as Dbeaver. Is there any setting wrong with me?

**Comment by cesek-navisys** [comment]
Same problem. I believe it has something to do with citext. I can easily update data via UPDATE ... SET COLUMN but not in DBeaver UI (22.1.2.202207091909).

![image](https://user-images.githubusercontent.com/79996604/181758264-26ab5412-21f6-41a7-a100-ec5d56c8fa10.png)

**Comment by LonwoLonwo** [comment]
The original issue and ticket about `citext` representation are now in this ticket: https://github.com/dbeaver/dbeaver/issues/17108
You can vote for them (So we can't understand that this is urgent). And subscribe to get news.

**Comment by SummerHow** [comment]
> citext cells #17108

the type of database I am connecting to is Oracle
