### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Iatbzh** [dbeaver/dbeaver#16734]
**Is your feature request related to a problem? Please describe.**
It is recommended to optimize the UI, you can change the size of the address bar and font icons, etc.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LonwoLonwo** [comment]
Hello @Iatbzh 
You can change many elements manually in DBeaver.

You can find some available design changes in the Preferences, like:

![2022-06-08 10_47_20-DBeaver Ultimate 22 1 0 - _postgres 13 3_Script-163](https://user-images.githubusercontent.com/45152336/172561817-eaae7de7-102f-4def-8cec-8525684eac54.png)

Please use it or provide more info about you idea. Screens or videos will be also very beneficial.

**Comment by Iatbzh** [comment]
I don't know how to describe it, but your suggestion can only change the font color size, not the overall layout, which is very troublesome. You can refer to the theme style of the community version of Navicat. The overall layout is very generous and comfortable

**Comment by LonwoLonwo** [comment]
You can change all theme too:

![2022-06-08 17_07_19-DBeaver Ultimate 22 1 0 - _postgres 13 3_Script-163](https://user-images.githubusercontent.com/45152336/172637647-0974e9e7-1f96-40b7-834c-c111ef05cf31.png)

But for now your idea is too general. Please provide more details and screens.

**Comment by uslss** [comment]
There has been no update for a long time.
If issue is still actual for you - feel free to reopen it
