### ISSUE TITLE
DB2 11 - unable to enter value in NUMERIC field

### ISSUE THREAD

**Issue by MocniMax** [dbeaver/dbeaver#16747]
#### System information: 
- MS Windows Server 2019
- DBeaver version 22.1.0.202206051253
- Additional extensions - none

#### Connection specification:
- Database DB2 11 zOS and AIX
- Driver name IBM DB2 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : Nope

#### Describe the problem you're observing:
No DECIMAL filed can be updated from table editor, only by SQL UPDATE

#### Steps to reproduce, if exist:
Try to update DECIMAL field

#### Include any warning/errors/backtraces from the logs

This is shown by dbeaver
![image](https://user-images.githubusercontent.com/26117076/172636320-e2d56e4e-8ab6-4d9f-9978-1a729e6c0a58.png)

Thanks for any idea and help!

**Comment by LonwoLonwo** [comment]
Please provide the full error log. You can find instruction here https://github.com/dbeaver/dbeaver/wiki/Log-files

Also, do you use bundled java for DBeaver or your own?

**Comment by MocniMax** [comment]
Good morning,

Just created clean logs are attached.
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/8867586/dbeaver-debug.log)

[log.log](https://github.com/dbeaver/dbeaver/files/8867589/log.log)

I am always updating dbeaver using Installed with bundled java only.

**Comment by LonwoLonwo** [comment]
Which driver version do you use?

You can find this info in Connection Settings -> Test Connection
 or Connection Settings -> Edit Driver Settings -> Libraries

**Comment by MocniMax** [comment]
It is listed in my first email, the 3.72.44. It is delivered by IBM DB2 jdbc package and I think it is the latest one.

![image](https://user-images.githubusercontent.com/26117076/172806224-6c849932-daf9-44fb-8909-f3a7a5f5359e.png)

**Comment by LonwoLonwo** [comment]
https://www.ibm.com/support/pages/db2-jdbc-driver-versions-and-downloads I see other driver versions, can you please try another one?

Also, I see that DBeaver uses another default driver version, did you tried it?

![2022-06-09 11_58_53-DBeaver 22 1 0](https://user-images.githubusercontent.com/45152336/172817317-6b249836-7e0b-466a-b46d-1edc92d58ba1.png)

**Comment by MocniMax** [comment]
Nope, I am using only drivers delivered by IBM DB2 zOS package itself, otherwise I cannot access data in RW mode, license needed :).
I will download and try this one and come back tomorrow.

Thanks.

**Comment by MocniMax** [comment]
Hi,

I found issue was in using JDBC version 3 driver which is no more compatible :((.

When I switched to version 4 driver, everything started to work. I will test it thorough but it looks like problem is solved.

Thanks for the hint!

Regards

**Comment by LonwoLonwo** [comment]
Thanks for the answer and the investigation @MocniMax 

I'm closing this ticket for now.
