### ISSUE TITLE
Close window button looks strange

### ISSUE THREAD

**Issue by AaronWiora** [dbeaver/dbeaver#16741]
#### System information: 
- Ubuntu 21.10
- DBeaver 22.1.0
- 3440x1440 (21:9) display

#### Describe the problem you're observing:

I noticed that the button to close the window does not look round so I measured the height and length. Take into consideration my screen resolution under the system information section. I had this issue already in Dbeaver 21.X.X
![Screenshot from 2022-06-08 11-17-31](https://user-images.githubusercontent.com/17088412/172582949-5ca02c45-b723-405c-9051-8921db46743c.png)

![Screenshot from 2022-06-08 11-18-06](https://user-images.githubusercontent.com/17088412/172583212-06a17e8d-5bb0-4808-b92b-44fbc6487cb5.png)

**Comment by flambchap** [comment]
Thank you for the report. This is a known bug: https://github.com/dbeaver/dbeaver/issues/15920.
