### ISSUE TITLE
"Remove property" command in Snowflake Driver properties menu of connection config doesn't work

### ISSUE THREAD

**Issue by jtg567** [dbeaver/dbeaver#16750]
#### System information: 
- Operating system (distribution) and version Big Sur 11.6.1
- DBeaver version Version 22.1.0.202206051253
- Additional extensions n/a

#### Connection specification:
- Database name and version 6.18.2
- Driver name Snowflake
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When editing a connection's configuration, using the "Remove property" command on a User property under the Driver properties tab (whether by the UI button or via context menu) results in the property disappearing from the UI.

However, after clicking OK and opening the connection configuration for editing again, the properties that appeared to have been removed in the previous step still appear in the UI.

#### Steps to reproduce, if exist:
Mimic description to reproduce with Snowflake driver (tried similar with Postgres and did not reproduce)

**Comment by Matvey16** [comment]
@jtg567 Hello, I was not able to reproduce it. It looks like it can be connected to a bug where changes to an active connection were not saved in some cases. Can you see if it is still reproducible in the latest version?

**Comment by jtg567** [comment]
Updated to 22.1.1.202206261508 and I still cannot get properties deleted, unfortunately.

Would you be able how to advise how could I wipe out my installation with the exception of my stored SQL files? I have not been able to connect since encountering this error and presume the only way I can fix it is to start fresh.

**Comment by Matvey16** [comment]
@jtg567 Hello, sorry for the late response. I reproduced this issue and it looks like that property was edded in dreiver settings and not connection settings. Can you try to remove this property from snowflake driver in `Database > Driver manager` menu?
![zoVd9mpuEL](https://user-images.githubusercontent.com/82543000/181228591-c1b05c1c-db2b-43fb-9eda-c3c79a30369a.png)
![dbeaver_EXlmrNTcxD](https://user-images.githubusercontent.com/82543000/181228612-5da47d5c-b46f-4ece-836a-6c34515d380c.png)

**Comment by jtg567** [comment]
Thank you @Matvey16; I can use DBeaver with Snowflake again!
