### ISSUE TITLE
InfluxDb support

### ISSUE THREAD

**Issue by majkinetor** [dbeaver/dbeaver#1675]
Are there any plans to support metrics databases such as this one ?

https://github.com/influxdata/influxdb

**Comment by serge-rider** [comment]
I'm not familiar with this one.
But there is Infiniflux jdbc driver in default DBeaver config. Isn't it the same?

**Comment by majkinetor** [comment]
No, its not the same.

InfluxDb, is one of the most popular metric databases currently in use and it uses form of SQL to query metric data.

**Comment by marcopeise** [comment]
+1

**Comment by jcdauchy** [comment]
+1

**Comment by idobarash** [comment]
+1

**Comment by adrinjalali** [comment]
+1

**Comment by nmat** [comment]
+1

**Comment by majkinetor** [comment]
Indeed. 

In the meantime, if you are on windows, I created this tool to help:
https://github.com/majkinetor/psinflux

**Comment by serge-rider** [comment]
Unfortunately there is no JDBC or ODBC driver for InfluxDb. At least public.
But it has quite clear Java API so it is very possble to write DBeaver extension for it.
However it will take relatively much time (1-2 weeks of coding).

If somebody wants to participate in this and contribute some code (on Java) - please tell.

**Comment by majkinetor** [comment]
There is also REST interface that can be used, as I did above in Powershell. 
This also seems legit: https://github.com/influxdata/influxdb-java

**Comment by tati-kru** [comment]
As a BigData database InfluxDB was implemented as a part of DBeaver EE and it will be released in DBeaver EE 5.2 (September, 2018). 
Now, you can test it in the EA version: https://dbeaver.com/files/ea/
