### ISSUE TITLE
All my SQL scripts and database links are missing

### ISSUE THREAD

**Issue by HappinerWinnie** [dbeaver/dbeaver#16751]
#### System information: 
- Operating system (distribution) and version
  windows64 
- DBeaver version
  version: 22.0.0.202203060510
- Additional extensions

#### Describe the problem you're observing:
All my SQL scripts and database links are missing

#### Steps to reproduce, if exist:
I just opened your app

#### Include any warning/errors/backtraces from the logs
![error](https://user-images.githubusercontent.com/31788525/172746881-b8f2c24c-916b-4e88-910c-1b99cbd7f50f.png)

Here's the error log
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/8866124/dbeaver-debug.log)

**Comment by HappinerWinnie** [comment]
I tried to download a new version, but the problem is still not solved
![image](https://user-images.githubusercontent.com/31788525/172748042-3b8b0e9b-32cb-4e08-a3ea-46dcb56ca086.png)

**Comment by HappinerWinnie** [comment]
I am very anxiously awaiting your response

**Comment by ShadelessFox** [comment]
Hello @HappinerWinnie,

Looks like your project name contains Chinese characters that Eclipse (the platform DBeaver is built on) does not recognize.

Try renaming your project to contain ASCII characters only. Please let me know if it helps.

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual, feel free to reopen it.
