### ISSUE TITLE
MySQL/MariaDB column geometry

### ISSUE THREAD

**Issue by maitrepylos** [dbeaver/dbeaver#1676]
hi,
You'll find the 'geometry' type and the stock of the coordinates of gps. When i try to Dump or import the  database the fields values became wrong. Example: value became 2.2359537552925256e63 instead of 50.12345. Because of "e" in the value's field.
Have an idea for this problem ?
Does DbEaver handle geometry fields?
Thanks for help

**Comment by serge-rider** [comment]
Please post sample of DDL/data insert.

**Comment by maitrepylos** [comment]
Hello,

DDL : 
`
CREATE TABLE `adresse`  ( 
	`id`                      	int(11) UNSIGNED AUTO_INCREMENT NOT NULL,
	`lieu`                    	varchar(255) NULL,
	`rue`                     	varchar(255) NOT NULL,
	`num`                     	varchar(15) NULL,
	`boite`                   	varchar(10) NULL,
	`complement`              	varchar(255) NULL,
	`cp`                      	varchar(15) NULL,
	`localite`                	varchar(255) NULL,
	`pays`                    	char(2) NULL DEFAULT 'BE',
	`tel`                     	bigint(15) UNSIGNED NULL,
	`mobile`                  	bigint(15) UNSIGNED NULL,
	`fax`                     	bigint(15) UNSIGNED NULL,
	`coord`                   	geometry NULL,
	`adresseClusterId`        	int(11) UNSIGNED NULL,
	`mobiliteEnumerationLabel`	varchar(255) NULL,
	`nombreOrdinateurs`       	int(11) UNSIGNED NULL,
	`wifiGratuit`             	tinyint(1) NULL,
	`horaire`                 	varchar(500) NULL,
	`prive`                   	tinyint(1) NOT NULL DEFAULT '0',
	`placeId`                 	varchar(300) NULL,
	`reformatted`             	tinyint(1) NOT NULL DEFAULT '0',
	`dateCreation`            	datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`dateModification`        	timestamp NOT NULL,
	`ownerContactId`          	int(11) UNSIGNED NULL,
	`ownerGroupId`            	int(11) UNSIGNED NULL,
	`_OLDId`                  	varchar(255) NULL,
	`pendingDelete`           	tinyint(1) NOT NULL DEFAULT '0',
	PRIMARY KEY(`id`)
);

`

Insert : 
`
INSERT INTO `adresse` VALUES (13, 'Agence du Numérique (AdN)', 'Avenue du Prince de Liège', '133', NULL, 'AWT', '5100', 'Jambes', 'BE', NULL, NULL, NULL, GeomFromText('POINT(50.4640335 4.8875213)'), NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, '2014-10-30 12:43:52', '2015-6-4 15:43:00', NULL, NULL, '446', 0);
`

Value 'coord' for DbEaver

`
         ³_!se;I@} 8b­ó @
`

THX.

**Comment by serge-rider** [comment]
We'll support it with GeoTools library: http://docs.geotools.org/stable/userguide/library/jts/geometry.html

![image](https://user-images.githubusercontent.com/6398845/36123078-9e411e56-105c-11e8-9d97-4fd7560f38e6.png)

**Comment by serge-rider** [comment]
Geometry values read/write support will be added in 4.3.5
