### ISSUE TITLE
When exporting multiple tables to JSON files, file names won't be replaced by table names

### ISSUE THREAD

**Issue by fdj184** [dbeaver/dbeaver#16760]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 22.1.0.202206051253

#### Connection specification:
- Database name and version: MySQL 8.0.29

#### Describe the problem you're observing:

As the image below, 
the table variable in file name pattern won't be replaced correctly if there are more than one table to export as JSON files,
and this feature was working on DBeaver version 21.0.0.202103021012.

![image](https://user-images.githubusercontent.com/21854534/172808496-19f77d46-a29b-4914-abd5-022deb476a2a.png)

#### Steps to reproduce, if exist:

1. Select two or more tables
2. Right click and export data
3. Choose format as JSON files
4. Fill `${table}` in the file name pattern in "Output" section
5. Preview the result in "Confirm" section

**Comment by LonwoLonwo** [comment]
Thanks for the report @fdj184 

We are planning to fix this issue in this ticket soon https://github.com/dbeaver/dbeaver/issues/15695

**Comment by fdj184** [comment]
Thanks for the quick response.
