### ISSUE TITLE
Auto arrange forced after show attributes changed even if for a table only

### ISSUE THREAD

**Issue by CarlGraff** [dbeaver/dbeaver#16776]
After manually arranging a diagram if I change the show attributes for a selected table from say none to show keys then the whole diagram is auto arranged.

I did see that a keep layout exists somewhere not sure if that would help if I can find it but basically I would simply like to not have arrangement changed after changing the show attributes for a table.

The only thing to do right now is to perhaps set show attributes for each table prior to any manual  arranging.

**Comment by dbeaver-pm** [comment]
Thanks for the bug report!
