### ISSUE TITLE
Partially fetched resultset visualization

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#16772]
In some databases error happens during resultset (say, after 100th row).
Currently we visualize it as a failed query however query is fine, fetch is wrong.

We must show fetched rows and show fetch error in the bottom toolbar.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/173104623-21f894c9-58fc-43a9-83ff-241b91496f99.png)

**Comment by Matvey16** [comment]
Verified
