### ISSUE TITLE
Allow to modify the column commnet of VIEW properties.(Oracle DB)

### ISSUE THREAD

**Issue by ch2robin** [dbeaver/dbeaver#1678]
hi!
I'm not good at english.

There is no problem with the modification of View commnet.
I am trying to modify the comment in the View column.

Click the commnet area to modify it, and the screen will change to the properties of the column.

BUT, To modify the COMMENT of the TABLE COLUMN, click the COMMENT of the COLUMN to make it editable.
![view comment of columns](https://cloud.githubusercontent.com/assets/28743365/26241315/36b54058-3cbf-11e7-827c-88a5995c9309.jpg)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
