### ISSUE TITLE
Snowflake - create/modify/delete Store Procedures/Functions

### ISSUE THREAD

**Issue by neb084** [dbeaver/dbeaver#16789]
I want to be able to create/modify/delete Stored Procedures and Functions from DBeaver when connected to a Snowflake server. Currently it appears that I can call these procedures/functions if they are created in Snowflake, but I can't directly create/modify/delete through DBeaver

**Comment by LonwoLonwo** [comment]
Hello @neb084 

Thanks for the suggestion.

Not sure about the "create" part, but modify and delete support we can add for Snowflakes procedures.

**Comment by neb084** [comment]
That's awesome. I don't know if it helps to show the code used to create/replace, but this is an example in Snowflake:

use role RPT;
use PRD;
use schema WRK;

create or replace procedure RETURN_GREATER(number_1 integer, number_2 integer)
returns integer not null
language sql
as
$$
begin
  if (number_1 > number_2) then
    return number_1;
  else
    return number_2;
  end if;
end;
$$
;

call RETURN_GREATER(7, 6)
