### ISSUE TITLE
Auto-size columns in metadata viewer

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#16781]
Quite often column widths are too marrow for all columns because DBeaver saves and restores previous column widths.
We need a way to auto-size column widths by using context menu.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/173531503-00ab933a-6c6e-468d-a3d2-d429d4778a81.png)

**Comment by uslss** [comment]
verified
