### ISSUE TITLE
clickHouse-jdbc error

### ISSUE THREAD

**Issue by wencyGit** [dbeaver/dbeaver#16783]
dbeaver version: 22.1.0.202206051253

error：

Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

**Comment by LonwoLonwo** [comment]
Hello @wencyGit 

What ClickHouse driver version do you have? Do you use bundled java from DBeaver or your own?

Also, maybe this topic can help you: https://stackoverflow.com/questions/32279964/pkix-path-validation-failed-java-security-cert-certpathvalidatorexception-sign

**Comment by wencyGit** [comment]
@LonwoLonwo 

Yesterday, dbeaver linked Clickhouse to download the Clickhouse jdbc driver message. Today, it is downloaded normally
