### ISSUE TITLE
New connection : open existing db vs create new db

### ISSUE THREAD

**Issue by gpetit** [dbeaver/dbeaver#16788]
Hi everyone and DBeaver team.

First of all, I'm a huge fan of DBeaver and thanks a lot for your work.

DBeaver version : Version 22.0.2.202204041542 (Ubuntu 21.10)

## Is your feature request related to a problem? Please describe

I may be wrong but it seems to me that there is a logical problem when connecting to an existing database. Indeed, instead of proposing to open a database, the interface asks us to save the database we have selected and warns us that the selected database will be overwritten.

To be more clear, below is an example with an existing `H2GIS embedded` database:

1. Click on `New connection` icon
2. Select `H2GIS embedded` database --> Next
3. Click on `Browse ...` to point the database. Select `my_h2gisdb.mv.db` file --> Here you can only click on the green `Save` button. Even if I don't want to save (I just want to open my db), I click
4. Here, I have a message telling me `A file named <<my_h2gisdb.mv.db>> already exists. Do you wan to replace it?` --> `Cancel` or `Replace`

## Describe the solution you'd like
Since the db already exists and I just want to open it, I would find it more logical if the interface proposed me a green `Open` button (and without the  `Cancel` or `Replace` step)

From what I understand, the confusion comes from the fact that there is only one common interface, on the one hand, to connect to an existing database and and the another hand, to create a connection with a new empty database.

Hoping not to be wrong and that it helps.
Best
Gwendall

**Comment by ShadelessFox** [comment]
Hello @gpetit,

Thanks for the detailed feature request.

It was implemented #15827 (22.0.4). Could you check it out?

**Comment by gpetit** [comment]
Hi @ShadelessFox and thanks for your quick reply
I updated and it's perfect now !
Best
Gwendall
