### ISSUE TITLE
SQL editor frame color doesn't change when switching between PROD and DEV connections

### ISSUE THREAD

**Issue by yoni-yad2** [dbeaver/dbeaver#16785]
#### System information: 
- Operating system (distribution) and version: Windows 10 64 bit
- DBeaver version: 22.1.0.202206051253

#### Connection specification:
- Database name and version: MySQL RDS 5.7.33
- Driver name: MySQL 5.7
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
When switching from a production connection to a development connection in an SQL editor, editor frame **color stays red**

#### Steps to reproduce, if exist:
1. Create two connections: one with red color for PROD and one with white color for DEV
2. open SQL editor for the PROD connection and switch to DEV connection

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @yoni-yad2

**Comment by uslss** [comment]
fixed ib #17309
