### ISSUE TITLE
The created index needs to be disconnected and reconnected before it can be displayed.

### ISSUE THREAD

**Issue by luyunfei11** [dbeaver/dbeaver#16795]
#### System information: 
- Operating system (distribution) and version :windows10
- DBeaver version : 22.0.4.202205011839
- Additional extensions
- 
#### Connection specification:
- Database name and version :postgres
- Driver name: org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
The created index needs to be disconnected and reconnected before it can be displayed.
#### Steps to reproduce, if exist:
Create a new index through the index node below the table. Under the index node at the same level of the table, refresh does not display the created index. After disconnection and reconnection, the created index is display

https://user-images.githubusercontent.com/56383213/173764368-fa655fc6-47a6-48e8-87ad-d741147fef91.mp4

ed.

**Comment by E1izabeth** [comment]
Hi, @luyunfei11! I guess you need to refresh schema after index creation. Please, click on the schema and press F5.
Does it help?

**Comment by luyunfei11** [comment]
After refreshing or pressing F5, the problem persists.

**Comment by luyunfei11** [comment]
![image](https://user-images.githubusercontent.com/56383213/174016651-98509771-752b-4df9-9f74-740485335b50.png)

**Comment by E1izabeth** [comment]
Thank you for quick response. Could you, please, send the log file. You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by luyunfei11** [comment]
Sorry, this problem was not recorded in the log file, and no error was reported. Therefore, the error log file cannot be provided.

**Comment by LonwoLonwo** [comment]
Hello @luyunfei11 

Does this issue still reproducible in the last DBeaver version? Can you please check?

**Comment by Matvey16** [comment]
Reproduced the issue. The bug can be reproduced only if the schema doesn't have any indexes prior to the creation of a new one
