### ISSUE TITLE
windows store dbeaver cannot be configured for additional cacerts

### ISSUE THREAD

**Issue by egrubbs** [dbeaver/dbeaver#16792]
#### System information: 
- Windows 10 Enterprise 10.0.19042 Build 19042
- DBeaver version: CE 22.1.0.202206051839

#### Describe the problem you're observing:

In the Microsoft Store version of DBeaver, It is very difficult to install a cacert in the embedded jre.
```
PS C:\Program Files\WindowsApps\DBeaverCorp.DBeaverCE_22.1.0.0_x64__1b7tdvn0p0f9y\jre\bin> .\keytool.exe -list
Program 'keytool.exe' failed to run: Access is deniedAt line:1 char:1
+ .\keytool.exe -list
+ ~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\keytool.exe -list
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```
More info on how many steps are necessary to edit those WindowsApps: https://superuser.com/a/1365110/1320689

#### Possible Solution
If this parameter was added to dbeaver.ini, then java should use the Windows keystore.
```
-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT.
```
https://stackoverflow.com/a/52330588/2824140

**Comment by ShadelessFox** [comment]
Hello @egrubbs,

Thanks for the bug report.

Indeed, the Windows Store version of DBeaver does not feature the mentioned parameter, but the regular version does.

**Comment by serge-rider** [comment]
Can be tested after WinStore release
