### ISSUE TITLE
Can the community add a function to modify the table display SQL script

### ISSUE THREAD

**Issue by wklong** [dbeaver/dbeaver#16808]
Greetings DBeaver Team,
pls add new function: SQL scripts for modifying tables are displayed when modifying tables
See the image below for an example
![image](https://user-images.githubusercontent.com/11863572/173981765-6618efd8-02c7-4100-b0a6-0146cd332e1d.png)

**Comment by E1izabeth** [comment]
Hi, @wklong! DBeaver has already provided similar opportunity. You can see generated SQL when you press `Save...` button.

![image](https://user-images.githubusercontent.com/28875055/174029323-e2cb4c97-2b74-4eb5-ba8e-fa8394a04cbf.png)

Does it satisfy your needs?

**Comment by wklong** [comment]
> DBeaver has already provided similar opportunity. You can see generated SQL when you press `Save...` button.

Yeah, that's it ,ths
