### ISSUE TITLE
DATE comparison not working correctly

### ISSUE THREAD

**Issue by PaulDokken** [dbeaver/dbeaver#16803]
#### System information: 
- MacOs 12.2.1
- 22.1.0
- Additional extensions

#### Connection specification:
- MySQL Ver 5.7.35 for Linux on x86_64 (MySQL Community Server (GPL))
- MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

schedule_date is a DATE field but it does not filter correctly.  It thinks 2022-04-25 is 22-04-24
![image](https://user-images.githubusercontent.com/75853422/173826710-f7103dec-dd71-4a32-a841-b547075f0228.png)

**Comment by uslss** [comment]
@PaulDokken unfortunately, cannot reproduce it.
Could you provide table DDL?

**Comment by uslss** [comment]
There has been no update for a long time.
If issue is still actual for you - feel free to reopen it
