### ISSUE TITLE
DB2 AS400/iSeries ability to show short names in meta data

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#16811]
The ability to see short / system names of columns in a table would be highly beneficial.

![Screenshot 2022-06-16 064044](https://user-images.githubusercontent.com/106983457/174053592-88a56f3b-7f6f-4f3b-ab32-a8afc7baf5b2.png)

**Comment by LonwoLonwo** [comment]
Hello @kraisor-kheaa 

Did you try to enable this setting?

![2022-06-16 19_43_27-Preferences](https://user-images.githubusercontent.com/45152336/174124111-a0756fad-ba9c-4a69-9a3a-8e883f0eef5b.png)

Or this?

![2022-06-16 19_47_53-Connect to a database](https://user-images.githubusercontent.com/45152336/174124133-3213109e-9d5c-452b-bdf5-1457c4fefc79.png)

Maybe it can help.

**Comment by ghost** [comment]
I've tried both and neither produce a list of system names for the columns.  Sorry took me so long to reply.

**Comment by LonwoLonwo** [comment]
Ok, thanks for the answer

**Comment by ghost** [comment]
Thank you all for this!  It will be a big help.

**Comment by ghost** [comment]
Is this issue going to be considered?

**Comment by LonwoLonwo** [comment]
We are open to contributions :)

https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse

**Comment by LonwoLonwo** [comment]
Closed as a duplicate of https://github.com/dbeaver/dbeaver/issues/16102
