### ISSUE TITLE
Table name column is empty in detail index of table

### ISSUE THREAD

**Issue by bmoAtolcd** [dbeaver/dbeaver#16826]
- Operating system : Mac os 12.3.1
- DBeaver version : 22.1.0

- Database name and version : postgres 11 

Table name column is empty in detail index of table.

CREATE TABLE public.table1 (
	id_table1 bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
	code text NULL,
	label text NULL,
	CONSTRAINT table1_pk PRIMARY KEY (id_table1)
);
CREATE INDEX table1_code_idx ON sg_reftech.table1 (code);

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/57495449/174310910-82c90c82-50b6-4ac7-bc28-8125018875c7.png">

**Comment by ShadelessFox** [comment]
Hello @bmoAtolcd,

You have to expand the index to see which columns it refers.

**Comment by bmoAtolcd** [comment]
Hello, thanks for you reply.

Ok I missed that.
Perhaps display summary when indexes are collapsed.
Whith many auto-generate indexes, collapsed indexes display no relevant information.
