### ISSUE TITLE
query result ，json field update bug

### ISSUE THREAD

**Issue by ItisDL** [dbeaver/dbeaver#16829]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 22.1.0
- Additional extensions

#### Connection specification:
- Database name and version mysql
- Driver name mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Include any warning/errors/backtraces from the logs

在查询结果中,更新字段的时候, where条件查询json类型字段的时候没有结果导致更新失败

work->
SELECT *
FROM test
WHERE
	type_config = CAST('{"key": "value"}' AS JSON)
LIMIT 0, 200

no-work->
SELECT *
FROM test
WHERE
	type_config = '{"key": "value"}'
LIMIT 0, 200

but dbeaver use no-work way

**Comment by ItisDL** [comment]
Data is updated in the query result. There is JSON type in the field. An error will be reported when updating. Check the log and find that =, which is used in the where condition, should be converted to JSON using the cast function

**Comment by LonwoLonwo** [comment]
Hello @ItisDL 

Thanks for the bug report.
Yes, we can't use a simple JSON value for the WHERE condition.

This ticket is close to https://github.com/dbeaver/dbeaver/issues/11704

**Comment by E1izabeth** [comment]
Should have been fixed along with #16687. Fix will be available in the 22.2.2 release.
