### ISSUE TITLE
Incorrect display of composite data type when all attributes are null

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#16822]
#### System information: 
- Operating system (distribution) and version Win11
- DBeaver version 22.1.0

#### Steps to reproduce, if exist:
1. Create a data type with two fields

```sql
create type aa as (a text, b text);
```

2. Execute a select with this data type so both fields are NULL
```sql
select array[row(null, null)::aa, null];
```

**Expected:** The result shows that there are two null fields
![cmd_Wf7a8RPqnJ](https://user-images.githubusercontent.com/82543000/174100528-7950731a-e681-4e34-821e-d39e32fb013f.png)

**Actual:** nulls are merged into one null and are indistingushable from a single null field
![dbeaver_63engc4laX](https://user-images.githubusercontent.com/82543000/174100505-21764fc6-e4f4-407e-9e3d-d62f1d875b02.png)
![dbeaver_bzlkNRwzZy](https://user-images.githubusercontent.com/82543000/174100520-9b5ab944-edd2-43c6-8e6e-7652830005f1.png)

**Comment by ShadelessFox** [comment]
Unfortunately, this is the issue of our parser (fixable). You can verify that by inspecting the value panel.
