### ISSUE TITLE
Can't use 'local' database through mongos' on server

### ISSUE THREAD

**Issue by Loizzus** [dbeaver/dbeaver#16836]
#### System information: 
- Operating system (distribution) and version: Windows 11
- DBeaver version: Version 22.1.0.202206131757

#### Connection specification:
- Driver name: C:\Program Files\DBeaverEE\plugins\org.jkiss.bundle.mongodb_4.5.1\lib\mongodb-driver-core-4.5.1.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
As a follow up to the new driver being implemented from issue: https://github.com/dbeaver/dbeaver/issues/16168#issuecomment-1098847982
Now when trying to connect to a MongoDB Atlas server instance the following error is received:
```
Error connecting to MongoDB instance [localhost]
  Command failed with error 20 (IllegalOperation): 'Can't use 'local' database through mongos' on server. The full response is {"ok": 0, "errmsg": "Can't use 'local' database through mongos", "code": 20, "codeName": "IllegalOperation"}
```

![image](https://user-images.githubusercontent.com/55563000/174501627-d6907595-40e9-419c-bd01-90c68533f3f4.png)

![image](https://user-images.githubusercontent.com/55563000/174501755-2b8762eb-dab3-43a7-b626-7d225b1ffde1.png)

**Comment by E1izabeth** [comment]
Hello, @Loizzus. Thank you for bug report.
Does this issue appear only in a newer DBeaver versions (since 22.0.5)?

**Comment by Loizzus** [comment]
Hi @E1izabeth, 
Yes this is a new issue since 22.0.5, however I have never managed to get it working so that doesn't necessarily mean much.

**Comment by emironovDB** [comment]
@Loizzus could you attach log file with this error? 
Instructions: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by Loizzus** [comment]
@emironovDB  Here you go: [dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/9105877/dbeaver-debug.log)

**Comment by Loizzus** [comment]
[other.log](https://github.com/dbeaver/dbeaver/files/9105889/other.log)

**Comment by serge-rider** [comment]
Fixed. Now we use database name from URL instead of `local`.

**Comment by Matvey16** [comment]
Verified
