### ISSUE TITLE
The cell to be edited in the pinned column moves as you scroll

### ISSUE THREAD

**Issue by troizet** [dbeaver/dbeaver#16839]
#### System information: 
- Operating system: Ubuntu 20.04.4 LTS
- DBeaver version:  22.1.0.202206051253

#### Describe the problem you're observing:
One pinned column

https://user-images.githubusercontent.com/9607501/174539391-bf93c9ef-aee2-4e2e-86eb-4c07310b0d8c.mp4

Two pinned columns

https://user-images.githubusercontent.com/9607501/174539446-d5a93ce4-d28e-47df-9fce-5031337d556b.mp4

**Comment by uslss** [comment]
thanks for the report
