### ISSUE TITLE
Connection with sql server too long after updating dbeaver 22.1.0 on macos

### ISSUE THREAD

**Issue by Ndysa** [dbeaver/dbeaver#16841]
System information:
Operating system (distribution) and version: macos High Sierra
DBeaver version: Version 22.1.0

Hi! I'm a new user to DBeaver. 
I had the previous version installed of dbeaver community and connected with sql server (using Docker) and I was working fine. Today I've installed the latest version and I'm trying to connect with database (master) but is loading for a quite time and still the Connect to master shows 0%. I cannot see my projects or tables I've created on my database or the ER diagram. For example when I try to open ER diagram  the error failed message displays "Datasource master entities cannot be downloaded-no entity container found".

Does anyone had this issue?

Thank you!

![image](https://user-images.githubusercontent.com/107844058/174565652-2b45e282-75e0-41e3-98f8-7e0c7bb99f82.png)

**Comment by Destrolaric** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by Ndysa** [comment]
> Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

Thank you for your reply. I can't find any log files only a file that contains steps from the update. Can I send you a direct email?

**Comment by LonwoLonwo** [comment]
Hello @Ndysa 

Can you please check your connection view?
If it is custom, can you please set it to "Advanced"?

![2022-06-01 10_54_57-](https://user-images.githubusercontent.com/45152336/171355832-9a73052d-340b-49b5-858d-86d5ba2af074.png)

**Comment by LonwoLonwo** [comment]
Maybe it's connected to https://github.com/dbeaver/dbeaver/issues/16657

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it
