### ISSUE TITLE
How do I change the select item color?

### ISSUE THREAD

**Issue by dennisKwone** [dbeaver/dbeaver#16840]
[when] I type the SQL code, Dbeaver will populate the list of columns. how do i change the selected column color?

![Screenshot 2022-06-20 151351](https://user-images.githubusercontent.com/107837616/174545922-99345e0c-4816-4ba5-a0e3-faa3331d2f33.png)

**Comment by emironovDB** [comment]
@dennisKwone, hi! 

Did you try to restart DBeaver?

**Comment by dennisKwone** [comment]
> @dennisKwone, hi!
> 
> Did you try to restart DBeaver?

tried restarting, it remain unchanged.

**Comment by emironovDB** [comment]
@dennisKwone 

Try resetting UI settings 


![Image](https://user-images.githubusercontent.com/105634259/177562532-67dae71c-e95c-4ab5-ac53-955809b63908.png)

Let me know if it helps

**Comment by dennisKwone** [comment]
> @dennisKwone
> 
> Try resetting UI settings
> 
> ![Image](https://user-images.githubusercontent.com/105634259/177562532-67dae71c-e95c-4ab5-ac53-955809b63908.png)
> 
> Let me know if it helps

@emironovDB 

That does not solve the issue. I remember it has to do with the Preferences settings but i do not know what color should i change.
![image](https://user-images.githubusercontent.com/107837616/177686148-e94d740e-455f-4a3b-97da-79d41ecf68b4.png)

**Comment by uslss** [comment]
@dennisKwone you could try [Darkest Dark theme ](https://github.com/dbeaver/dbeaver/wiki/Eclipse-extensions#popular-3rd-party-extensions-for-eclipse-and-dbeaver)

**Comment by uslss** [comment]
there has been no update on the issue for a long time. If it is still actual - feel free to reopen it

**Comment by Splarv** [comment]
I want to know how to change colour of the selection too.

![image](https://github.com/user-attachments/assets/a5c2c580-e460-4a57-8a00-638182d87ee2)
![image](https://github.com/user-attachments/assets/3e9d3bbe-88cc-4b51-a925-fe936a870c4e)
