### ISSUE TITLE
Darkes Theme deletes configuration

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#16855]
DBeaver 22.1 CE on Mac

With the latest version I experience that all my 

- connections and 
- scripts 

disappear as soon as I install the darkest theme and restart DBeaver.

**Comment by cristian-home** [comment]
I get the same thing on Linux with flatpak, apparently the darkest dark plugin changes the paths for the workspace folder and the drivers folder.

**Comment by Matvey16** [comment]
@JamesInform I was not able to reproduce it on the latest version. Can you check if your workspace has been changed? You can choose workspace by clicking File > Switch workspace

**Comment by JamesInform** [comment]
@Matvey16 Tested again with DBeaver 22.1.1 and DevStyle (includes Darkest Dark Theme) version 1.11.0.202206271604.

Not sure which version did the magic DBeaver or DevStyle Darkest Theme ...

But now everything works fine and closing the bug is fine by me!
