### ISSUE TITLE
The SQLite driver doesn't work on mac on the lastest version

### ISSUE THREAD

**Issue by amorfxda** [dbeaver/dbeaver#16860]
#### System information: 
- Operating system: macOS Mojave 10.14.2
- DBeaver version 22.1.0.202206051253
- Java version ?

#### Describe the problem you're observing:
Have to use an SQLite database for a class in uni and it works on everyone's mac but mine. After installing it for the first time I got an error and it couldn't open any databases. Then cause it wasn't downloading the SQLite driver on its own in the menu. We just deleted SQLite and wanted to add it back manually. 
It says I have to install the driver and when you want to download it there aren’t any you can select and download.
But now I’ve tried installing DBeaver at least 4 times and it just won’t work. Like I can’t do anything. Downloaded sqlite jdbc 3.36.0.3.jar and the latest dbeaver version.
Redownloading DBeaver and sqlite jar data, also didn't change anything. Cause SQLite still wasn't back and the test database I made in the beginning, was still in the app for some reason. Have to specifically use SQLite, others would've maybe worked. But now I don't know how to add it back or get the driver to work. 

#### Include any warning/errors/backtraces from the logs
[Error Log - db.log](https://github.com/dbeaver/dbeaver/files/8958570/Error.Log.-.db.log)

**Comment by uslss** [comment]
hi @amorfxda , sorry for the late response.
Could you try to Reset to the default settings in Edit Driver Dialog and then Update the driver?
![dbeaver_P5ZXg1NwEd](https://user-images.githubusercontent.com/31996417/176861276-5e6fb47c-6ba3-4d65-849c-2f50a50b4de0.gif)

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it with additional info
