### ISSUE TITLE
The same version, but one does not generate SQL function, why is this?

### ISSUE THREAD

**Issue by Fcscanf** [dbeaver/dbeaver#16862]
#### System information: 
- Operating system (distribution) and version：Win 10
- DBeaver version：22.1.0
- Additional extensions：None

#### Connection specification:
- Database name and version：Oracle
- Driver name：oracle.jdbc.OracleDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? ：None

#### Describe the problem you're observing:
After successfully connecting to the Oracle database, the local Bbeaver has the function of generating SQL, and the other one can also successfully connect to the database, but the right-click menu does not have the function of generating SQL, and it is checked that the database driver version is the same for both.
#### Steps to reproduce, if exist:
Right click to generate a screenshot of SQL
![image](https://user-images.githubusercontent.com/27654200/175246317-bffe60f8-2e71-47f7-b9ed-db76de0a6670.png)
Right-click does not generate a screenshot of the SQL function

**Comment by LonwoLonwo** [comment]
Hello @Fcscanf 

Can you provide please the SELECT statement from the second case (without SQL generation)? Is this select from a table?

**Comment by Fcscanf** [comment]
@LonwoLonwo 
Thank you for your reply. In both cases, the SQL menu is not generated. Neither the result set queried from the SQL statement nor the data queried from the table can be

**Comment by LonwoLonwo** [comment]
Video of the issue will be very helpful.

**Comment by Fcscanf** [comment]
@LonwoLonwo Thank you very much for your help! SQL can be generated from an open table, but there is still no SQL generation function for a single table queried from the SQL editor.
This is a right click from the open table to see the generate SQL function

This is a screenshot of a single table queried from the SQL editor without the SQL generation function

**Comment by emironovDB** [comment]
Hello @Fcscanf,

Can you please provide log files? You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by Fcscanf** [comment]
Hi @emironovDB ,
I added his log file, thanks for your help to check, thanks
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/9068348/dbeaver-debug.log)
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/9068349/dbeaver.log)

**Comment by LonwoLonwo** [comment]
Hello @Fcscanf 

I can see in your picture the small lock icon. It means, that your data here is read-only and DBeaver knows nothing about metadata from this object.

![2022-07-22 10_03_12-The same version, but one does not generate SQL function, why is this_ · Issue #](https://user-images.githubusercontent.com/45152336/180383052-19b12165-a8d2-42fe-a150-a716e2c50c15.png)

You can try to open your table in the SQL Editor by double-clicking on this field. Maybe it helps to create the correct select statement in the correct place. 

![2022-07-22 10_09_50-The same version, but one does not generate SQL function, why is this_ · Issue #](https://user-images.githubusercontent.com/45152336/180384078-f2c1f699-2ffc-4f51-a9e2-f9badfe73445.png)

**Comment by Fcscanf** [comment]
@LonwoLonwo Thank you for your help, I will try it later, thank you

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If the issue is still actual for you, feel free to reopen it.
