### ISSUE TITLE
Result View hides cursor position

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#16875]
#### System information: 
- Operating system (distribution) and version: Debian/SID
- DBeaver version: Version 22.1.0.202206051253
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 12
- Driver name: 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When Result View opens at the bottom of the editor, cursor position is hidden.
Seems, before resizing the editor it's already scrolled up, thus moving cursor position out of view.

Given that the actual cursor position is at the currently executed query, the automatic scrolling seems to be unnecessary anyway.

#### Steps to reproduce, if exist:
- Editor with content filling at least until the last line
- no Result View open
- add query at the last line
- execute query

**Comment by emironovDB** [comment]
Hello @2019-05-10,

Thanks for the bug report
