### ISSUE TITLE
Azure SQL Server MFA Authentication Causes Repeated Browser Windows

### ISSUE THREAD

**Issue by Zulu-Inuoe** [dbeaver/dbeaver#16873]
#### System information: 
- Windows x64
- Dbeaver 22.1.0
- Vanilla

#### Connection specification:
- Azure SQL Server 12.0.2000.8
- Azure SQL Server

#### Describe the problem you're observing:

When I use the 'Active Directory - MFA' option to authenticate against my database, dbeaver will switch to my browser, opening a new tab in order to authenticate. This is **expected**.
However, this happens several times, leaving me with dozens of
> Authentication complete. You can close the browser and return to the application.
tabs.

This does not always happen. Most frequently it happens when making a query after a while of not interacting.

#### Steps to reproduce, if exist:

1. Connect to Azure SQL Server using 'Active Directory - MFA'
2. Select the connection and open a new query window on it
    * This will likely bring up a tab or two 
4. begin typing a query like SELECT * FROM SomeTable
    * In the middle of typing, I am redirected to the browser several times

**Note** This is a sporadic issue, but I am able to replicate reliably on a 'first connection' to a database.

#### Include any warning/errors/backtraces from the logs
I deleted my logs, then reproduced the issue, and no new logs were generated in the process.

**Comment by LonwoLonwo** [comment]
Hello @Zulu-Inuoe 

As a workaround you can disable opening separate connections for metadata reading and for separate SQL Editors.

![2022-06-23 23_02_51-DBeaver Ultimate 22 0 3 - _postgres_ Script-12](https://user-images.githubusercontent.com/45152336/175387896-7a9c603c-9f55-499d-89f6-3836b2b99022.png)

![2022-06-23 23_03_15-DBeaver Ultimate 22 0 3 - _postgres_ Script-12](https://user-images.githubusercontent.com/45152336/175387908-65f79bee-0a95-4278-8bf7-e0056fb415c2.png)

**Comment by Zulu-Inuoe** [comment]
@LonwoLonwo Thank you! I've enabled that setting and already things are far less distracting.

**Comment by Zulu-Inuoe** [comment]
Actually, I take that back - it was a false positive. Just executing a query on an already-open editor to this DB today - meaning Ctrl+E, not even typing - I saw 6 tabs open up without any of my interaction at all.

**Comment by LonwoLonwo** [comment]
Did you disable or enable this setting? My point was in DISABLING. To not open new connections each time.

**Comment by Zulu-Inuoe** [comment]
Understood - I DISABLED the setting per your suggestion:

![image](https://user-images.githubusercontent.com/1526310/175549652-9c9018f7-e6d6-44fa-87d3-5dfc0a572bbb.png)

**Comment by E1izabeth** [comment]
@Zulu-Inuoe , please, disable it in the Global settings too. You can click here to go to the Global settings.

![image](https://user-images.githubusercontent.com/28875055/176445806-059d5415-5c44-4fab-ac61-a1dbd8e9cef6.png)

Does it help?

**Comment by Aileron79** [comment]
I updated to the latest version and now I experience the very same behavior. I usually have multiple tabs/editors open for different databases. When (automatically) reconnecting to the server, multiple tabs open in my browser saying "Authentication complete. You can close the browser and return to the application." Please fix, it used to work without any browser tabs!

**Comment by Zulu-Inuoe** [comment]
@E1izabeth Hey sorry for the late reply. I do have it disabled globally and it's still happening

**Comment by Aileron79** [comment]
As a workaround, is there a setting to keep alive a connection so I don't have so many reconnection attempts clogging up my browser window?

**Comment by emironovDB** [comment]
Seems similar https://github.com/dbeaver/dbeaver/issues/15153

**Comment by emironovDB** [comment]
@Zulu-Inuoe 
Your issue was resolved by this ticket #15153 
It will be included in DBeaver version 22.1.3

**Comment by Aileron79** [comment]
I am sorry to say that it has not been resolved. I installed 22.1.3 today, and when running a query in a window that has been idle for a while, the reconnection attempt will open a browser window saying "Authentication complete. You can close the browser and return to the application."

![image](https://user-images.githubusercontent.com/16278437/180783026-89bf9fbf-3455-4e3a-af3b-7b65c8af0c3c.png)

This is clogging up my browser, could you please fix?

**Comment by E1izabeth** [comment]
@Aileron79 does exactly this issue exists (when new browser tabs are repeatedly opened) or this problem has gone and you get authentication tab only on reconnect?

**Comment by E1izabeth** [comment]
@Zulu-Inuoe could you check is this issue actual for the latest DBeaver version?

**Comment by Aileron79** [comment]
@E1izabeth I get new authentication tabs every time a connection is made, no matter if it is a new connection I establish consciously myself or if it reconnects automatically. Sometimes I just type a new statement in the query window, DBeaver tries to come up with suggestions for autocompletion, for that purpose it reconnects in the background to fetch table names (I assume), that causes a browser window to open and the focus is moved to another window which means I am not typing my statement in the query window any longer. 

Note though this behavior is linked to the Azure SQL driver, I don't have that issue when authenticating with SQL U/P - but I have databases I can only connect to using Azure credentials with MFA.

**Comment by E1izabeth** [comment]
Thank you for response.

**Comment by dennishenning** [comment]
@E1izabeth I have the same issue on DBeaver 23.1.2. Is this a known problem?

**System information:**
MacBookPro M1
MacOS Ventura 13.4.1 
Dbeaver 23.1.2
Vanilla

**Connection specification:**
<img width="603" alt="image" src="https://github.com/dbeaver/dbeaver/assets/57574194/cb4d2368-d536-429c-96da-f9125f33d813">

**Comment by rick-gwu** [comment]
> #15153

Me too. Same mac M1, same Dbeaver version.

**Comment by dhorrall** [comment]
This is happening for me too over the past couple of versions.  I am now using Version 23.1.4.202308061552

This only seems to happen if my session times out, and then I try to connect again.  When I try to connect, numerous browser windows open with message:  'Authentication complete. You can close the browser and return to the application.'

I have tried recent driver updates with no luck
![image](https://github.com/dbeaver/dbeaver/assets/22561698/2af4c302-9684-461b-b718-e16134139b8f)

**Comment by dennishenning** [comment]
Are there any updates?

**Comment by E1izabeth** [comment]
You could try checking this option 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/f65ca7f2-afc1-435c-898c-c6a2f217bd26)
