### ISSUE TITLE
Postgis geometry field is not shown in the Map tab

### ISSUE THREAD

**Issue by abrosich** [dbeaver/dbeaver#16872]
#### System information: 
- Operating system (distribution) and version: Debian testing
- DBeaver version: 22.1.0
- Additional extensions

#### Connection specification:
- Database name and version: Postgresql+Postgis 14.4
- Driver name: org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Describe the problem you're observing:
Clicking on a geometry (Postgis extension) field the position is not shown on the map tab on the right side, instead a download dialog is opened for an html file named like this: view17191192810884847905gis.html
That file exists in the /tmp directory and is actually a map, I can open it directly using a browser.

I did not have this issue using previous versions of DBeaver.

**Comment by ShadelessFox** [comment]
Hello @abrosich

Thanks for the bug report

Please take a look at the provided solution: https://github.com/dbeaver/dbeaver/issues/16125#issuecomment-1098990262
