### ISSUE TITLE
Status bar with fetched rows and execution time

### ISSUE THREAD

**Issue by GuenterSch** [dbeaver/dbeaver#16895]
#### System information: 
- Windows 10 21H1
- DBeaver version 22.1.1

#### Connection specification:
- Database name and version All

#### Describe the problem you're observing:
In the previous versions, if you click on the ![grafik](https://user-images.githubusercontent.com/99535516/175928529-1e9fd6b9-d3a2-4555-8de7-482be887901d.png) icon, you get the dialog Status Details. After then, it is possible to copy this information.
In 22.1.1 it is not possible to open the Status Details.

![grafik](https://user-images.githubusercontent.com/99535516/175928050-8bb858bf-79d6-410e-8c7c-29fe97e57667.png)

Thanks for resolving this bug.
Günter

See also #15471

**Comment by uslss** [comment]
thanks for the report

**Comment by Destrolaric** [comment]
Hi, thanks for the bug report, looks like it was caused by some changes in recent versions.
