### ISSUE TITLE
DBeaver v22.1.1 // Export Tasks does not respect ${table}

### ISSUE THREAD

**Issue by valsamis-d** [dbeaver/dbeaver#16893]
#### System information: 
- Operating system (distribution) and version: Windows 10 Enterprise 
- DBeaver version: 22.1.1 x64 Portable
- Additional extensions: Microsoft Office Integration & Darkest Theme

#### Connection specification:
- Database name and version: DB2
- Driver name: DB2 JCC (Type 4) 11.5.6.0 FP000
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes

#### Describe the problem you're observing:
I have an export task with multiple queries
As export type I have Microsoft Excel (Microsoft Office Integration)
As an output, I have specified ${tables}
On execution, I expect to get get 4 different xlsx files.
However, I get a single file with the name "export.xlsx", consisting on the export of the last query. 

#### Steps to reproduce, if exist:
Reverted to v22.1 and was able to to 4 different xlsx files named each one based on ${table}

**Comment by ShadelessFox** [comment]
Hello @valsamis-d,

Perhaps you have the highlighted option enabled?

![image](https://user-images.githubusercontent.com/35821147/175939818-ae502bc2-f058-4a80-98e2-91ef22d24100.png)

**Comment by valsamis-d** [comment]
@ShadelessFox no. It's disabled. I've always had this disabled as my export consists of 4 different queries and I want to have district output files for each one.

This is what I see in v22.1:

![image](https://user-images.githubusercontent.com/17590539/175946075-09ad2c21-6a98-435c-a608-d2131bfb6d61.png)

But In v22.1.1 under the 'Target' column I see 'export.xlsx'

**Comment by ShadelessFox** [comment]
It seems to be broken by #15695.

Thanks for the bug report. Unfortunately, I'm unable to think of any workaround.

**Comment by valsamis-d** [comment]
> It seems to be broken by #15695.
> 
> Thanks for the bug report. Unfortunately, I'm unable to think of any workaround.

Thanks for confirming @ShadelessFox !

Until this is resolved, I will stay in v22.1 :) Thanks for following-up!

**Comment by valsamis-d** [comment]
Hello @ShadelessFox @serge-rider  @emironovDB 

I downloaded 22.1.2 and the issue has been resolved, at least with getting different export files. I see that it was worked around in #16990.  Are they any specific rules in order to help the engine to resolve table name? My current flows are based on some naming conventions, which assume that the first comment in each query has a specific name and date. For example:

-- ENTITY_A_2022_07_10
Query for Entity A for 2022_07_10
-- ENTITY_B_2022_07_10
Query for Entity B for 2022_07_10
etc.

Thank you
Dimitrios

**Comment by ShadelessFox** [comment]
DBeaver attempts to resolve the name of the table from a query.

It works fine for simple queries but fails for others because it expects to find just a single table name.

**Comment by valsamis-d** [comment]
Thanks for the response @ShadelessFox !

Is it difficult to resolve the table name based on the comment that is prior to the query, such as "-- ENTITY_A_2022_07_10"?

This will some flexibility when the output files are passed into so sort of further automated processing.

Thank you
Dimitrios

**Comment by ShadelessFox** [comment]
It is possible. We already have such a feature:

```sql
-- title: A title for this query
SELECT * FROM Album;
```

Executing this query will result in a tab called `A title for this query`.

Unfortunately, it doesn't work for data transfer. It seems like this feature was broken for some time. I will create a separate FR shortly.

**Comment by valsamis-d** [comment]
Thank you so much @ShadelessFox !
