### ISSUE TITLE
Add a new Icon for a graph presentation tab

### ISSUE THREAD

**Issue by emironovDB** [dbeaver/dbeaver#16894]
The current icon is not consistent with the DBeaver color style and should be replaced with another one
![slack_E9nkzjhpF5](https://user-images.githubusercontent.com/105634259/175927975-072c0459-a507-4117-85f0-3fd247fd091a.png)

**Comment by E1izabeth** [comment]
PR: https://github.com/dbeaver/dbeaver-ee/pull/1780
