### ISSUE TITLE
MSSQL Server 2017 Express - SSL connection issue

### ISSUE THREAD

**Issue by kejdajar** [dbeaver/dbeaver#16904]
#### System information: 
- OS: Windows 11, build 22000.778
- DBeaver version: 22.1.1.202206261508
- Additional extensions: none

#### Connection specification:
- MSSQL Server 2017
- Driver name: Microsoft JDBC Driver for SQL Server (MSSQL)
- Do you use tunnels or proxies: no

#### Problem
Hello,
so far I haven't been able to connect to SQL Server 2017 using SSL - the database server is running online and uses Let's Encrypt and I am connecting from my Windows machine using DBeaver. I have no problem connecting to the database from SSMS (filled: _server name_, _login_, _password_, and ticked _encrypt connection_). Unfortunately when using the same credentials with DBeaver and "Use SSL" option enabled, I am getting this error:

```
The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:9fefa833-2d0c-4bb6-9f9d-e10d5e1f7b7e
  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    unable to find valid certification path to requested target
    unable to find valid certification path to requested target
```

I have tried following this guide: https://dbeaver.com/docs/wiki/Importing-CA-Certificates-into-DBeaver/, but with no results - the connection fails with: 

```
The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "Keystore was tampered with, or password was incorrect". ClientConnectionId:ba9e0790-9db9-41a2-886b-9e8de71ce495
  Keystore was tampered with, or password was incorrect
  Keystore was tampered with, or password was incorrect
    Password verification failed
    Password verification failed
```

I have also tried to create the .JKS keystore by myself using this tool [https://keystore-explorer.org/](https://keystore-explorer.org) and importing the Let's Encrypt root certificate from here [https://letsencrypt.org/certificates/](https://letsencrypt.org/certificates/), but I am still getting the _'unable to find valid certification path to requested target'_ error message.

I am fairly new to certificates, so any help would be appreciated.

**Comment by iraidaa** [comment]
Hello @kejdajar,

Could you please provide an output of what you get when you type `where java`  (or non-Windows alternative) as it's said in https://dbeaver.com/docs/wiki/Importing-CA-Certificates-into-DBeaver/?

**Comment by kejdajar** [comment]
Hello,

after running the `where java` command I get the following output:
`C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe` 

Within the ouputted path I wasn't able to find the `cacerts` file. Under the `javapath` there are only `java.exe`, `javaw.exe` and `javaws.exe` files.

After some searching, I was able to find the `cacerts` file in 
`C:\Program Files\Java\jre1.8.0_341\lib\security` though. I have tried to replace the `C:\Program Files\DBeaver\jre\lib\security\cacerts` with the `C:\Program Files\Java\jre1.8.0_341\lib\security\cacerts` file but still I am getting the same error (even restarting the DBeaver app does not help). 

```
The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:e545d390-7701-4836-8a89-378fbd7041d9
  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    unable to find valid certification path to requested target
    unable to find valid certification path to requested target
```

Additionally, running the `where java` on my secondary windows machine (where is DBeaver also installed) results in `INFO: Could not find files for the given pattern(s).` - I suppose that's because I have not explicitly installed JAVA on that machine (and I am unable to connect to the database on this machine as well).

I was told by the administrator of that MSSQL database that I don't need any 'special' certificate - by his words, the [let's encrypt root certificate]([aa](https://letsencrypt.org/certificates/)) should suffice. I guess that's right, because using the SQL Server Management Studio I am able to connect to the database normally. When using the SSMS i have ticked the `Encrypt connection` and unticked the `Trust server certificate` which is what I was supposed to do to ensure to connection is secured.

Maybe I could try to make a new virtual windows machine with JAVA, DBeaver and SSMS installed and try to isolate the issue even further (because it seems as though I have some certificate available on my machine that works with the SSMS but can't be reached by the DBeaver). Thanks for your help.

**Comment by iraidaa** [comment]
Hello @kejdajar,

Did you try to tick Trust Server Certificate in the SSL tab in the Connection configuration? I guess you can try it to enable trust in the SSL certificate of the SQL Server.

![image](https://user-images.githubusercontent.com/49681450/182087450-7e9b1b72-225d-498d-aa06-ddc0d092c31f.png)

**Comment by kejdajar** [comment]
Hello,

I have verified (using our non-pruduction environment) that "Trust Server Certificate" allows the connection to be established successfully. Nonetheless, I was told by the database administrator that the "Trust Server Certificate" should never be ticked for production environments - to ensure the certificate is valid and the connection is secure. 

Currently, I have to use the SSMS to connect to our production environment, because, unlike the DBeaver, the SSMS allows me to connect to the database **without trusting the server certificate** (see the following image)

![image](https://user-images.githubusercontent.com/22682824/182094428-5e433c8a-1927-4882-b762-92a5dd046989.png)

**Comment by iraidaa** [comment]
Hello @kejdajar, 

Could you please send me the log files? You can find instructions here: [dbeaver.com/docs/wiki/Log-files](https://dbeaver.com/docs/wiki/Log-files/). You can send it to email: iraida.lavrova@dbeaver.com. 

Also, attach the DBeaver Connection Settings screenshot please.

Really sorry for the inconvenience you experienced!

**Comment by kejdajar** [comment]
Thank you, 
you can find all the requested details in your e-mail inbox.

**Comment by kejdajar** [comment]
After further investigation and reading a related issue here https://superuser.com/questions/1006250/how-to-add-lets-encrypt-to-the-java-allowed-certificates I have finally managed to connect to the database.

If anyone is interested, here are the steps:
- download certificates from Let's Encrypt website (https://letsencrypt.org/certificates/) - for my case, only the Intermediate Let’s Encrypt R3 certificate was needed (the ```lets-encrypt-r3.der``` file)
- create a JKS KeyStore from the .der file - if using Windows, the KeyStore Explorer worked well for me (https://keystore-explorer.org/)
- when creating the KeyStore, you can assign a password or use no password
- if not already present, add the .jks extension to the exported KeyStore file (not necessary)
- using the DBeaver, set your connection settings accordingly, and on the SSL tab, tick the "Use SSL" option
- also set the keystore parameter path to the previously generated .jks file (you can leave out the keystore password if not specified)
- **do not check Trust Server Certificate** to ensure the certificate is validated and the connection is secure

In my case, when examining the JKS file it looks like this:

![image](https://user-images.githubusercontent.com/22682824/182619160-436e799a-ccd8-4d4c-8578-5c6bab3da7df.png)

The SSL settings example:

<img width="635" alt="image" src="https://user-images.githubusercontent.com/22682824/182618349-3e354988-f0f1-4a89-a7de-763544456bc2.png">


The connection should be now established without any certificate-related errors.

**Comment by marcokrikke** [comment]
For future reference, this issue also occurs when running MSSQL on Linux/Docker, as it won't serve the intermediate certificate (works fine with MSSQL on Windows however). The comment above this one imports the (in this case LetsEncrypt) intermediate certificate to be used by dbeaver. Also see https://github.com/microsoft/mssql-docker/issues/673
