### ISSUE TITLE
Cannot connect to database, active schema has no name

### ISSUE THREAD

**Issue by zucky2021** [dbeaver/dbeaver#16901]
## Current Issue
I can connect to the project, but I can't connect to the database, so I can't execute SQL or make changes to the data.
What should I do?

## This is the current situation.
[![Image from Gyazo](https://i.gyazo.com/14465ce3cff38809885ad5a070b4a65d.png)](https://gyazo.com/14465ce3cff38809885ad5a070b4a65d)

No active schema appears in the drop-down menu.
[![Image from Gyazo](https://i.gyazo.com/175489cc13dc0841f8b9fbeadaf63b05.png)](https://gyazo.com/175489cc13dc0841f8b9fbeadaf63b05)

**Comment by Destrolaric** [comment]
@kanbaru-github, Hi, can you provide an additional information about which database was used?

**Comment by zucky2021** [comment]
We apologize for the inconvenience.
We have resolved the issue by setting the target database to default.
We apologize for the inconvenience.

2022年6月28日(火) 17:30 George ***@***.***>:

**Comment by zucky2021** [comment]
Thank you!

2022年6月29日(水) 18:53 ShadelessFox ***@***.***>:
