### ISSUE TITLE
disable table editor

### ISSUE THREAD

**Issue by valtanders** [dbeaver/dbeaver#1690]
Hello, i start to use dbeaver and is great!. I'm using informix and mySql connections and save me a lot of time.
I just want to know if it is possible to disable the option to edit tables, for security purpose.
Thanks!

**Comment by serge-rider** [comment]
You can make connection read-only (connection properties, page General)

**Comment by valtanders** [comment]
yes, but with that configuration, i can't insert, update or delete on a table. What i want to do, is disable the option for edit the table (change columns properties)

**Comment by serge-rider** [comment]
All metadata editors are now read-only for read-only connections

**Comment by valtanders** [comment]
> 
> 
> All metadata editors are now read-only for read-only connections

Thanks @serge-rider!
