### ISSUE TITLE
Outputs a syntax error even when there is no error in the syntax

### ISSUE THREAD

**Issue by just-nimay** [dbeaver/dbeaver#16907]
#### System information: 
- Operating system (distribution) and version mac os 10.13.6
- DBeaver version: 22.0.0.202203060510

#### Connection specification:
- Database name and version telegram_db MySQL

#### Describe the problem you're observing:
I do not know what this is related to, but when I work in the DBeaver program, this program constantly outputs errors.
For example:
![Снимок экрана 2022-06-28 в 17 36 23](https://user-images.githubusercontent.com/96590760/176206714-5a94242e-6715-4638-9f44-9a7f23a9715c.png)
And the most interesting thing is that when I run this commands in the console, everything is executed.
![Снимок экрана 2022-06-28 в 17 39 41](https://user-images.githubusercontent.com/96590760/176207555-e0f66c79-2677-43ad-94e8-fdce78051fd5.png)

#### Steps to reproduce, if exist:
```
USE telegram_db;

drop table if exists users;
CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    telegram_id BIGINT);
```
#### Include any warning/errors/backtraces from the logs
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'drop table if exists users;
CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    t' at line 3
```

**Comment by emironovDB** [comment]
Hello @just-nimay,

Are you running your script using the <kbd>Ctrl+Enter</kbd> shortcut?

Try running it using the <kbd>Alt+X</kbd> shortcut instead.

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it with additional info

**Comment by wtechgo** [comment]
This happens when you execute with 'Execute Query' which is the first play button or the shortcut alt+ENTER. This mode only executes one line and throws an error if there are more commands than one.

The solution is to 'Execute Script', that's the paper icon or shortcut alt+X.

Thanks [emironovDB](https://github.com/emironovDB) for pointing it out.

**Comment by Guillaume-Georges** [comment]
I had the same issue with a correct SQL command "SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax" in DBeaver.
When I used ALT + X it worked.

The reason seemed that the normal run uses the cursor's position to run the query, while ALT+X use the whole statement.
