### ISSUE TITLE
Value of "Comment" property not save when unfocused - Create New Column

### ISSUE THREAD

**Issue by GaNiziolek** [dbeaver/dbeaver#16911]
- Windows 10 21H2
- DBeaver 22.0.5
- PostgreSQL 12.11
- PostgreSQL JDBC Driver 42.2.20

When creating a new column in any table, the value of "Comment" property is not saved when unfocused, only when I press enter, all the other properties work as expected.

I made a video with the problem here: https://www.loom.com/share/15c820c5a9db42b1a4ced61e5306e60a

**Comment by E1izabeth** [comment]
Hello, @GaNiziolek. Thank you for bug report!
We have already know about this problem. So, I'll close it as a duplicate of https://github.com/dbeaver/dbeaver/issues/15620.
