### ISSUE TITLE
Inaccurate value in UPDATE query

### ISSUE THREAD

**Issue by kelvinwnfeitosa** [dbeaver/dbeaver#1691]
Hi, when we generate an update query of the table contains as primary key a decimal(17), the primary key loses accuracy value.
As in the examples below.

`UPDATE DB2PNG.SLCT_LIB_CRD
SET VL_LIB_SLCD=600
WHERE NR_SLCT=20150871226566400;`
`UPDATE DB2PNG.SLCT_LIB_CRD
SET VL_LIB_SLCD=700
WHERE NR_SLCT=20150871245483100;`

In first case, the right value is 20150871226566398 and in second is 20150871245483101.

**Versions:**
DBeaver: 4.0.7, on Windows 7
DB2 z/OS Driver

**Comment by serge-rider** [comment]
Could you post sample DDL + INSERT?

**Comment by kelvinwnfeitosa** [comment]
DDL:
```
CREATE TABLE DB2PNG.SLCT_LIB_CRD (
	NR_SLCT DECIMAL(17,0) NOT NULL,
	SG_SIS_CDU_SLCT CHAR(3) NOT NULL,
	DT_LIB_SLCD DATE,
	VL_LIB_SLCD DECIMAL(17,2) NOT NULL,
	CD_PRD_SLCT SMALLINT NOT NULL,
	CD_MDLD_SLCT SMALLINT NOT NULL,
	CD_CHV_CTL_TRAN SMALLINT NOT NULL,
	NR_UNCO_CTR_OPR DECIMAL(17,0) NOT NULL,
	CD_FNLD_CRD SMALLINT NOT NULL,
	NR_OPR_SIS_CDTR DECIMAL(17,0) NOT NULL,
	CD_PRF_DEPE_CDTR SMALLINT NOT NULL,
	NR_PRPT_SIS_CTRC INTEGER NOT NULL,
	CD_LNCD INTEGER NOT NULL,
	PRIMARY KEY NR_SLCT
);
```
Insert:
```
INSERT INTO DB2PNG.SLCT_LIB_CRD (
	NR_SLCT, SG_SIS_CDU_SLCT, DT_LIB_SLCD, 
	VL_LIB_SLCD, CD_PRD_SLCT, CD_MDLD_SLCT, 
	CD_CHV_CTL_TRAN, NR_UNCO_CTR_OPR, 
	CD_FNLD_CRD, NR_OPR_SIS_CDTR, CD_PRF_DEPE_CDTR, 
	NR_PRPT_SIS_CTRC, CD_LNCD )
VALUES (
	20150871226566398, 'XPO', NULL, 
	500.00, 73, 11, 1, 20150495367701445, 
	1, 5002713, 123, 22118996, 456
);
```

**Comment by serge-rider** [comment]
Well, I can't test it with DB2 z/OS. In DB2 LUW I see exactly the same values which were inserted.
![default](https://cloud.githubusercontent.com/assets/6398845/26653269/46978ca6-465b-11e7-9f82-71a09003bf96.png)

Probably z/OS driver fetches numbers differently. You could try to play with numbers data format (context menu->View/Format->Data formats->Numbers). E.g. try different rounding modes.

**Comment by kelvinwnfeitosa** [comment]
When we change some atribute on record, the script created loses acurracy on NR_SLCT field. As in the example in image.
Ps.: For consult the script created, click in the magnifying glass below records.

![dbeaver 1](https://user-images.githubusercontent.com/22152919/26930120-a2450aa6-4c32-11e7-9e09-333713373513.JPG)

**Comment by kelvinwnfeitosa** [comment]
@serge-rider The error still persists, could you check, please?

**Comment by uslss** [comment]
hi @kelvinwnfeitosa , is issue still actual for you on 6.2.5?

**Comment by uslss** [comment]
there is no update on ticket more than a month.
If issue still actual for you - feel free to reopen the ticket
