### ISSUE TITLE
Use Chromium as default browser

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#16910]
Currently we use legacy SWT web browser which uses Internet Explorer as embedded browser.
It still works but lacks a lot of function + it is disabled in some corporate environments.

Now SWT supports Chromium and Edge integration. Perhaps its time to migrate.

https://www.eclipse.org/swt/faq.php#howuseedge
https://github.com/equoplatform/chromium-swt
https://stackoverflow.com/questions/45116657/embed-chrome-in-a-swt-application-in-java

**Comment by Destrolaric** [comment]
Linked pr:https://github.com/dbeaver/dbeaver-packaging/pull/42
