### ISSUE TITLE
Extract to Excel - on failure temporary files kept open 

### ISSUE THREAD

**Issue by trybowski** [dbeaver/dbeaver#16923]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 22.1.1
- Additional extensions: Office plugin

#### Connection specification:
- Database name and version: Hana
- Driver name: Hana
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Not in DBeaver

#### Describe the problem you're observing:
When extracting data to Excel (via the official office plugin), a temporary folder is used, called “%temp%\poifiles”. Inside is created an xml file with extracted data in it. The file can be huge, and sometimes space on temp volume is exhausted. If this happens, extract fails, but the partially created temp file is kept, and it still open by dbeaver.exe. It can't be deleted, unless DBeaver is closed. This causes issues with other programs, which can no longer create temporary files.

#### Steps to reproduce, if exist:
1. Run a query which produces a large result.
2. Click "Excel" button below the result grid.

**Comment by uslss** [comment]
#16924

**Comment by emironovDB** [comment]
@trybowski 
Thanks for the bug report.

**Comment by ShadelessFox** [comment]
Hello @trybowski,

I don't have such a drive that is too small to hold the temp file, therefore I can't reproduce the issue but I know it's reproducible.

Can you please provide log files, please? You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
