### ISSUE TITLE
Read only: No corresponding table column

### ISSUE THREAD

**Issue by rotorboy** [dbeaver/dbeaver#16928]
#### System information: 
- Operating system (distribution) and version - MacOS 12.4 
- DBeaver version - 22.1.1
- Additional extensions

#### Connection specification:
- Database name and version - MariaDB 10.6
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:

This bug appears to have returned in some form in version 22.1.1. After adding several columns in one SQL editor, I switched to another editor and ran a "select * from table" query, and the columns came up as "Read only: no corresponding table column". After trying different things, I quit dBeaver and restarted and that fixed the issue.

#### Steps to reproduce, if exist:

Steps to reproduce:
ran the following queries in one editor:

ALTER TABLE mytable ADD latitude decimal(9,7) DEFAULT NULL AFTER zip_code;
ALTER TABLE mytableADD longitude decimal(10,7) DEFAULT NULL AFTER latitude;
ALTER TABLE mytable ADD geofence_radius decimal(6,2) DEFAULT 250 NULL AFTER longitude;

switch to second edior and run:
SELECT * from mytable order by id;

**Comment by E1izabeth** [comment]
Hello, @rotorboy! Updating table in navigator should solve the problem. You need to click on the table or database in the navigator view and press F5 before executing `select` statement.
Does it help?

**Comment by rotorboy** [comment]
Elizabeth;

Humm.. right clicked on result set and refreshed, but didn’t think to right click on table/DB and refresh…will try that next time; or alternatively, DBeaver can auto-refresh after executing such “refreshable” commands...

**Comment by uslss** [comment]
Refresh improvements will be done in the scope of #6398.
Close this issue as a duplicate.
Anyway, thanks for the report
