### ISSUE TITLE
[ERD] Changed preferences are not applied until object is reopened

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#16932]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 22.1.1

#### Steps to reproduce, if exist:
1. Open a diagram
2. Open preferences and change dispalyed table attributes
3. Apply changes
4. Refresh the diagram

**Expected:** Displayed attributes are changed
**Actual:** The diagram stays the same until it is reopened

**Comment by E1izabeth** [comment]
Connected to https://github.com/dbeaver/dbeaver/issues/9625
