### ISSUE TITLE
Snowflake - how to execute select parse_json($1):name from @db.sch.%tbl; wihtout DBEaver thinking "name" is a bind variable and popping window asking to specific BIND value ?

### ISSUE THREAD

**Issue by emanueol** [dbeaver/dbeaver#16945]
**Is your feature request related to a problem? Please describe.**
In snowflake we parse files using:
`select parse_json($1):name from @db.sch.%tbl;`

![image](https://user-images.githubusercontent.com/8422412/176927168-1be872f1-8b74-4d07-920d-18a48f676c0d.png)

**Describe the solution you'd like**
BDeaver shall not open popup asking to set BIND variable "name".
In snowflake $1 $2 etc.. are used on SELECT statements to access fields in files, so DBeaver shall not open consider these as BIND spots for variables.

**Describe alternatives you've considered**
Any settings config I can use to disable DBEaver BINDs ?
How can I have above sql executes in DBEaver ?

**Comment by emanueol** [comment]
UPDATE: I found an Ignore button that executes sql. But still I wonder if anything exists or can be done in future to avoid having the BINDs popup appearing everytime we executing snowflake sql  using $1 $2 etc ?

**Comment by E1izabeth** [comment]
Hello, @emanueol! You can disable `Enable SQL parameters` setting in `Preferences ->Editors->SQL Editor->SQL Processing`. Does it help?

![image](https://user-images.githubusercontent.com/28875055/176928087-05f56d0f-60c4-4b38-be78-3e53602029c3.png)

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it with additional info
