### ISSUE TITLE
CSV import config is very slow for a 50K row file

### ISSUE THREAD

**Issue by mskempri** [dbeaver/dbeaver#16958]
Please note, this is not for the import itself, this is for the dialog that will define the file and the format of the upload
OS: MAC OS 11.6.7
DBeaver version: Version 22.1.1.202206261508
DB: postgres 14.2
drive name:postgres 

I'm trying to upload a file with 50000 rows and I can't really move past the file selection dialog. I am stuck in "update data produces settings from import stream" It might eventually move to the next screen but by this time the conection to the database has dropped. 
my table has 10 columns. 

this is the DDL and I have attached the file. 

```
CREATE TABLE scribe.ff_communication_log (
	id_ff_communication_log int4 NOT NULL,
	id_communication int4 NOT NULL,
	communication_instance_id int4 NULL,
	id_consumer int4 NULL,
	id_auth_group int4 NULL,
	id_barcode int4 NULL,
	manual_entry_enc varchar(20) NULL DEFAULT NULL::character varying,
	email varchar(255) NULL DEFAULT NULL::character varying,
	tlf varchar(18) NULL DEFAULT NULL::character varying,
	id_ff_channel int4 NULL DEFAULT 1,
	hash varchar(255) NULL DEFAULT NULL::character varying,
	status varchar(45) NULL DEFAULT NULL::character varying,
	batch_number int4 NULL,
	"token" varchar(255) NULL DEFAULT NULL::character varying,
	CONSTRAINT ff_communication_log_pkey PRIMARY KEY (id_ff_communication_log)
);
CREATE INDEX email_ix ON scribe.ff_communication_log USING btree (email);
CREATE INDEX ff_communication_log_account_fk ON scribe.ff_communication_log USING btree (id_auth_group);
CREATE INDEX ff_communication_log_barcode_fk ON scribe.ff_communication_log USING btree (id_barcode);
CREATE INDEX ff_communication_log_communication_instance_id_ix ON scribe.ff_communication_log USING btree (communication_instance_id);
CREATE INDEX ff_communication_log_customer_fk ON scribe.ff_communication_log USING btree (id_consumer);
CREATE INDEX ff_communication_log_ff_communication_fk ON scribe.ff_communication_log USING btree (id_communication);
CREATE INDEX hash ON scribe.ff_communication_log USING btree
[messages_small.txt](https://github.com/dbeaver/dbeaver/files/9039331/messages_small.txt)
 (hash);
CREATE INDEX id_ff_channel ON scribe.ff_communication_log USING btree (id_ff_channel);
CREATE INDEX indexmanualentry ON scribe.ff_communication_log USING btree (manual_entry_enc);
```

**Comment by ShadelessFox** [comment]
Hello @mskempri,

Can you please provide your import settings on that page?

Perhaps you can reduce the `Sample rows count` parameter to some small value.

**Comment by mskempri** [comment]
hI @ShadelessFox , thank yo ufor getting back to me. 
I am using the default settings. these are the settings:

![Screenshot 2022-07-04 at 14 28 13](https://user-images.githubusercontent.com/1799119/177164803-7673cf2b-a152-40e0-af68-8882ad8722a6.png)
 
The moment I select the file, it goes into this screen

![Screenshot 2022-07-04 at 14 28 26](https://user-images.githubusercontent.com/1799119/177164889-93ae05c7-df4b-4058-869d-ee77d393b330.png)
 
That takes several minutes to progress with mapping the fields

**Comment by ShadelessFox** [comment]
Unfortunately, I'm unable to reproduce your issue. In my case, the performance is acceptable (it takes less than a second).

A thread dump might help. Please refer to our wiki:
https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump#mac-and-linux

**Comment by mskempri** [comment]
Thank you @ShadelessFox , I'm currently trying with a file of 1.7MB (I think about 1000 rows) and it's now taking a LONG time on 

![Screenshot 2022-07-05 at 10 36 29](https://user-images.githubusercontent.com/1799119/177298742-3b3006cd-a50e-47e8-85fb-eaee4d66c401.png)

I attach the thread dump thus far

[thread-dump_stuck_on_load_child_objects.txt](https://github.com/dbeaver/dbeaver/files/9045187/thread-dump_stuck_on_load_child_objects.txt)

**Comment by ShadelessFox** [comment]
Thanks for the thread dump. I can see that it's reading metadata about your tables. How many tables do you have in the schema containing the target table? (It's an I/O-bound operation. A slow network connection may have an impact on the performance.)

I'm interested in a thread dump during the `Update data produces settings from import stream` status. Sorry for not clarifying that earlier.

**Comment by mskempri** [comment]
I have 2 tables in that schema and NO tables in the progres schema. 

Since I created the thread dump, the process is still stuck on : load child objects (even though I do not have the disable foreing keys box ticked as I don't have any foreign keys. 

If I press on stop, the window hangs there. Here is the thread dump after I pressed stop

[thread-dump_stuck_on_load_child_objects_after_press_stop.txt](https://github.com/dbeaver/dbeaver/files/9045443/thread-dump_stuck_on_load_child_objects_after_press_stop.txt)

I had to force quit and restart. 
it is now waiting in the import stream stage

Here is the thread dump
[thread-dump_stuck_settings_from_import_stream.txt](https://github.com/dbeaver/dbeaver/files/9045465/thread-dump_stuck_settings_from_import_stream.txt)

Thank you for your help

**Comment by mskempri** [comment]
The first screen progressed - now I am waiting for the second screen:

![Screenshot 2022-07-05 at 11 19 08](https://user-images.githubusercontent.com/1799119/177306710-0324e584-7a95-41f6-83aa-52a35892f027.png)


[thread-dump_stuck_settings_from_import_stream_table_mapping_step.txt](https://github.com/dbeaver/dbeaver/files/9045501/thread-dump_stuck_settings_from_import_stream_table_mapping_step.txt)

**Comment by mskempri** [comment]
![Screenshot 2022-07-05 at 11 21 17](https://user-images.githubusercontent.com/1799119/177307072-933b4666-1a33-4151-a3e5-2576afed1adb.png)

![Screenshot 2022-07-05 at 11 19 08](https://user-images.githubusercontent.com/1799119/177307109-353eb9d1-4ce6-4fcc-bef1-36182e96a7bd.png)

I don't know if I mentioned that this is an RDS hosted postgres (I don't konw if that makes a difference) but I still can't get to import a file with 50K rows

**Comment by ShadelessFox** [comment]
After further investigation, it turns out the file you've provided is missing the quote (`"`) at the start, which hangs DBeaver, making it read the file until the end.

The solution is to put `"` at the start of the file.

Please let me know if it helps.

**Comment by mskempri** [comment]
Oh wow, thank you, that worked like a charm straight away. 
I can go ahead and close the ticket, otherwise maybe you can treat it for validating the CSV format before uploading? Whatever you prefer

**Comment by ShadelessFox** [comment]
I'm not sure if we can fix that. I guess the issue can be closed now.

**Comment by mskempri** [comment]
Thank you for your help
