### ISSUE TITLE
I can't write complicated queries

### ISSUE THREAD

**Issue by carlvon** [dbeaver/dbeaver#16950]
I get errors all the time trying to run queries. They work against MSSQL in SSMS, but if I do a CTE or few, or just make a somewhat imagined query, I get dumb errors from DBeaver. They run fine in SSMS. The latest was a simple query that only had a case statement on the join. DBeaver said no go (SQL Error [208] [S0002]: Invalid object name 'TABLENAME'. Error position:) but that same query ran fine in SSMS. Obviously there was issue with the query.

I'll fix that issue and the CTE issue if someone else has had that issue. I love the tool (I have only been using it for a week), but this is frustrating. Is there a precheck it does on the SQL query? Does anyone else have an issue with CTEs or case statements in joins? I'd love to track down the issue and do a PR.

I tried to make this as a discussion, but it wouldn't let me submit it. So an issue it becomes. maybe the DBeaver team can make it one because I'm curious about how everyone else's more than vanilla queries work for them.

Edit: added how to my last sentence.

**Comment by emironovDB** [comment]
@carlvon 
Could you please provide an example of such queries?

**Comment by uslss** [comment]
there has been no update on the issue for a long time.
If the issue is still reproducible for you - feel free to reopen it with additional info.
