### ISSUE TITLE
CSV loads into Netezza - can you increase rows inserted per transaction/SQL?

### ISSUE THREAD

**Issue by doctor-sex** [dbeaver/dbeaver#16955]
Netezza Database is optimised for bulk processing, not single row processing.

When loading from CSV file each, the insert statements insert usually between 1 and 5 rows, occasionally more, but mostly in this range.
The commit rows level was set to 1000 and at this point the inserts were committed, although the actual inserts were in much smaller  quantities.
Inserting very small numbers of rows per transaction/SQL is a painfully slow way of loading data into Netezza.

I am unable to find any setting that affects the number of rows inserted by a single SQL statement (as opposed to the commit level) so a 100000 row CSV file may created around 30000 insert statements, which is very very inefficient.

Is there a way to change this behaviour or can one be added?

Using Dbeaver Version 7.1.1.202006231904
Netezza version: 7.2.1.6-P3
Driver: Netezza JDBC

Sample data from query history

SQL_QUERY1 | SUBMIT_TIME | RESULTROWS
-- | -- | --
INSERT INTO ADMIN.FRANKIE_TELEPHONE_TEST (FRANKIE_CUSTOMER_NAME,FRANKIE_BILLING_ACCOUNT,FRANKIE_CUSTOMER_GROUP,FRANKIE_LGI_SECTOR_GROUP,TELEPHONE,ICOMS,ACCOUNT,SWITCH_ID_1) VALUES ( *removed for data security*)  | 2022-07-01 16:09:49 | **1**
INSERT INTO ADMIN.FRANKIE_TELEPHONE_TEST (FRANKIE_CUSTOMER_NAME,FRANKIE_BILLING_ACCOUNT,FRANKIE_CUSTOMER_GROUP,FRANKIE_LGI_SECTOR_GROUP,TELEPHONE,ICOMS,ACCOUNT,SWITCH_ID_1) VALUES (*removed for data security*) | 2022-07-01 16:09:49 | **1**
INSERT INTO ADMIN.FRANKIE_TELEPHONE_TEST (TELEPHONE,ICOMS,ACCOUNT,SWITCH_ID_1) VALUES (*removed for data security*) | 2022-07-01 16:09:49 | 2
INSERT INTO ADMIN.FRANKIE_TELEPHONE_TEST (FRANKIE_CUSTOMER_NAME,FRANKIE_BILLING_ACCOUNT,FRANKIE_CUSTOMER_GROUP,FRANKIE_LGI_SECTOR_GROUP,TELEPHONE,ICOMS,ACCOUNT,SWITCH_ID_1) VALUES (*removed for data security*) | 2022-07-01 16:09:50 | **5**
INSERT INTO ADMIN.FRANKIE_TELEPHONE_TEST (TELEPHONE,ICOMS,ACCOUNT,SWITCH_ID_1) VALUES (*removed for data security*) | 2022-07-01 16:09:50 | 1
INSERT INTO ADMIN.FRANKIE_TELEPHONE_TEST (FRANKIE_CUSTOMER_NAME,FRANKIE_BILLING_ACCOUNT,FRANKIE_CUSTOMER_GROUP,FRANKIE_LGI_SECTOR_GROUP,TELEPHONE,ICOMS,ACCOUNT,SWITCH_ID_1) VALUES (*removed for data security*) | 2022-07-01 16:09:50 | **41**

**Comment by emironovDB** [comment]
@doctor-sex 
Could you use the latest version of DBeaver and provide log-files if the issue is still there?

**Comment by doctor-sex** [comment]
@emironovDB 

Since posting this, it appears that the single (or few) rows at a time processing happens when rows in the source file contains rows that contain NULL values in different columns.
For example
123,RABC,, 2022-12-31
234,XYZ,, 2021-08-08
in these case when the 3rd column is NULL in both rows, then the rows will load together in a single SQL statement.

However..  if the next rows look like
123,,,2022-01-01
1345,,FISH,2020-09-01
then these rows will generate separate insert statements as the different columns have blank/NULL values.

I am unable to easily upgrade DBeaver versions being on a corporate laptop.

**Comment by emironovDB** [comment]
@doctor-sex 
I recommend you to install the latest version of DBeaver. 
In the last years (version 7.1.1 was published in 2020-11-03) we upgrade a lot of performance and add many features.

**Comment by doctor-sex** [comment]
@emironovDB 
when I click 'check for updates' it tells me there is no newer version  than 7.1.1.202006231904

**Comment by emironovDB** [comment]
@doctor-sex 
I see, can you download the installer from this page? 
https://dbeaver.io/download/

Or your corporate laptop doesn't provide this option?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If the issue is still actual for you, feel free to reopen it.
