### ISSUE TITLE
Privileges for a specific user on a specific DB are not properly displayed

### ISSUE THREAD

**Issue by Kluk** [dbeaver/dbeaver#16961]
#### System information: 
- Operating system (distribution) and version: MS Windows 10 Enterprise 21H2
- DBeaver version: 22.1.1.202206261508

#### Connection specification:
- Database name and version: MySQL 5.7.34
- Driver name: mysql-connector-java 8.0.29
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes

#### Describe the problem you're observing:
In the Users panel, the Schema Privileges tab shows that every privilege is enabled for a specific user on a specific schema even if it's not the case. For example, I have a bunch of users with privileges on specific DBs, the GRANT OPTION is not enabled but the tab shows as if it was. If I uncheck this privilege, save and reload, it's ok.
The users have probably been created with SQL Workbench.

Also, the EVENT privilege is missing from the Schema Privileges tab. I didn't check if others are missing too.

#### Steps to reproduce, if exist:
Connect to a DB, and go to the Users panel. Select a user and select the specific DB on which the user has privileges. Check the privileges pane.

**Comment by emironovDB** [comment]
@Kluk

Try to use the MySQL 5 driver instead:

![Image](https://user-images.githubusercontent.com/105634259/177555805-a893af6c-1757-4aed-ab7f-01d1f8951484.png)

Please let me know if it helps.

**Comment by Kluk** [comment]
Hello @emironovDB,

Thank you for your answer.

I tried with MySQL 5 driver but the result is the same:
![image](https://user-images.githubusercontent.com/5413585/177712501-7863ae8b-93f2-46b4-aed3-3159bb371624.png)

Here is the view from Workbench:
![image](https://user-images.githubusercontent.com/5413585/177712652-f49c3905-1639-4519-8273-3dac80672193.png)

And the EVENT privilege is still missing.

**Comment by uslss** [comment]
@Kluk seems the issue is similar to #12977
Event privilege is available on User Properties Tab.
Unfortunately, cannot reproduce the issue with Grant option

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If the issue is still actual for you, feel free to reopen it.

**Comment by schmunk42** [comment]
Please reopen.

I am having the same issue, users usually are created with `ALL PRIVILEGES` which does not include `GRANT OPTION` https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#priv_grant-option

Schema permissions are also set to `N` in `mysql.db`, but it is shown as checked like in https://github.com/dbeaver/dbeaver/issues/16961#issuecomment-1177175512

I haven't tested with another driver, since we had other issues with the old MySQL 5 driver and need the current one.

**Comment by Kluk** [comment]
> @Kluk seems the issue is similar to #12977 Event privilege is available on User Properties Tab. Unfortunately, cannot reproduce the issue with Grant option

@uslss, thank you for your reply and sorry for the long delay. I thought I replied to this but I've probably been interrupted and forgot to publish my comment.

Yes, but the display is still wrong. EVENT is checked in MySQL Workbench but not in DBeaver as it should be.
Also, administrative roles are not the same as schema privileges.
Administrative roles are global, schema privileges are specific to a user. At least, in my understanding.

Please, reopen this ticket. I will try to be more responsive if you need more testing :)

Thank you in advance.
