### ISSUE TITLE
Enhance new parser to better resolve grammar ambiguities

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#16978]
We need to try to add GSS to our current realization.
It will help with error handling and especially with cases when we don't have a full grammar.

**Comment by emironovDB** [comment]
"Acceptance criteria": 
- [ ] After we integrated this algs all tests should be passed 
- [ ] ClickHouse Enum handling works correct 
- [ ] Grammar SQL-92 could be used for parser (at least for testing) and made an acceptable performance
