### ISSUE TITLE
SQLite drop column generates bad SQL

### ISSUE THREAD

**Issue by wmeitzen** [dbeaver/dbeaver#16972]
Operating system and version: Win Server 2019
DBeaver version: Community 22.1.1.202206261508
Driver class name: org.sqlite.JDBC
Database type: SQLite
SQLite version: 3.36.0

Describe the problem you're observing:

I believe I found some problems with the SQL that DBeaver generates when dropping a column on a table.  The generated scripts do not work in some cases.

These issues are not super-critical as I can edit the scripts DBeaver generates.

----- #1:
SQLite syntax requires that column defaults be delimited by parenthesis.

DBeaver generates this DDL:
```
CREATE TABLE sql_services (
	id_sql_service VARCHAR(16) DEFAULT lower(hex(randomblob(16))) NOT NULL,
	id_credential VARCHAR(16),
	host VARCHAR(256) NOT NULL,
	service_type VARCHAR(5) DEFAULT 'de' NOT NULL,
	instance_name VARCHAR(256) DEFAULT '' NOT NULL,
	port VARCHAR(5) DEFAULT '' NOT NULL,
	added TIMESTAMP DEFAULT strftime('%Y-%m-%d %H:%M:%f', 'now'),
	updated TIMESTAMP DEFAULT strftime('%Y-%m-%d %H:%M:%f', 'now'),
	CONSTRAINT SQL_SERVICES_PK PRIMARY KEY (id_sql_service)
);
```

It should generate (note the parenthesis around the `DEFAULT` expressions):
```
CREATE TABLE sql_services (
	id_sql_service VARCHAR(16) DEFAULT (lower(hex(randomblob(16)))) NOT NULL,
	id_credential VARCHAR(16),
	host VARCHAR(256) NOT NULL,
	service_type VARCHAR(5) DEFAULT ('de') NOT NULL,
	instance_name VARCHAR(256) DEFAULT ('') NOT NULL,
	port VARCHAR(5) DEFAULT ('') NOT NULL,
	added TIMESTAMP DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now')),
	updated TIMESTAMP DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now')),
	CONSTRAINT SQL_SERVICES_PK PRIMARY KEY (id_sql_service)
);
```

----- #2:
If a PK is defined, DBeaver generates a `create unique index` command.  This command is not needed and generates an error.

`CREATE UNIQUE INDEX sqlite_autoindex_sql_services_1 ON sql_services (id_sql_service);`
==> SQL Error [1]: [SQLITE_ERROR] SQL error or missing database (object name reserved for internal use: sqlite_autoindex_sql_services_1)

----- #3:
If a unique constraint is defined, DBeaver does not generate the code correctly.

SQLite cannot create unique constraints as a separate command.  They must be created when the table is created.

For example:
DBeaver generates this command:
`CREATE UNIQUE INDEX sqlite_autoindex_sql_services_2 ON sql_services (host, service_type, instance_name, id_credential);`
==> SQL Error [1]: [SQLITE_ERROR] SQL error or missing database (object name reserved for internal use: sqlite_autoindex_sql_services_2)

Instead, DBeaver should generate this DDL:
```
create table sql_services (
id_sql_service varchar(16) not null primary key default (lower(hex(randomblob(16))))
,id_credential varchar(16)
...
,latest_check timestamp
,added timestamp default (strftime('%Y-%m-%d %H:%M:%f', 'now'))
,updated timestamp default (strftime('%Y-%m-%d %H:%M:%f', 'now'))
	,unique (host, service_type, instance_name, id_credential) -- <----- right here
);
```

**Comment by emironovDB** [comment]
@wmeitzen 
Thanks for the bug report.
