### ISSUE TITLE
DBeaver folder generated when startup the app

### ISSUE THREAD

**Issue by qilinsanshao** [dbeaver/dbeaver#16980]
#### System information: 
- Operating system (distribution) and version
- **win10**
- DBeaver version
- 22.1.0

Describe the problem you're observing:
hello，when I startup the DBeaver，it will auto generate a folder in my git project folders every time. 
In this folder, it has a json file named "project-settings". I dont need to push the usless file to my remote brathes...

![p1](https://user-images.githubusercontent.com/63779854/177521805-07ece738-6395-4b51-ade4-6c945db68e70.jpg)
![P2](https://user-images.githubusercontent.com/63779854/177521812-758ddaa0-aec6-4628-9dc9-7d151db72c33.jpg)

**Comment by E1izabeth** [comment]
Hello, @qilinsanshao! You can add `.dbeaver` folder to `.gitignore` file.

**Comment by qilinsanshao** [comment]
hi  E1izabeth:
thanks for your quick respose, but I really dont want to update the ignore file to the remote bratch.
Could you help to explain why did it happen and how could I to disable it ?
Thanks!

**Comment by E1izabeth** [comment]
It's a dbeaver project file. As well as `.project` from your screenshot. You can't disable it, because dbeaver needs to store project settings.
