### ISSUE TITLE
DB2/400 table information 

### ISSUE THREAD

**Issue by carlosherranz** [dbeaver/dbeaver#1698]
I have a doubt, sometimes in the editor pressing F4 on <schema.table> doesn't retrieve information of Columns, Unique keys, Indexes, DDL, etc... ¿Is that known or is a bug?.

Thank you for your work.

**Comment by serge-rider** [comment]
Could you provide some example?

Potentially this may happen if table information can't be loaded.
Or if you create new table from SQL script - you will need to refresh database navigator then.

**Comment by carlosherranz** [comment]
I can attach an example, but as you can imagine the screen is empty, with no information at all.
![image](https://cloud.githubusercontent.com/assets/28946478/26540191/6f0a450a-4450-11e7-802d-771cf6ad0e88.png)

I am trying to see differences among tables that retrieve information and others that don't. In data tab all files show the rows and columns of the table, but in diagram tab neither show information.

I don't know how DBeaver retrieves this information of tables in DB2/400 system, but all tables of this cases (with and without information) are files created with DDS specifications, not with DDL scripts

**Comment by serge-rider** [comment]
Could you post debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files) - it may explain missing columns.

**Comment by carlosherranz** [comment]
I have seen that in the Database Navigator tab, there are a lot of tables with and without columns information, as can you see in this example:
![image](https://cloud.githubusercontent.com/assets/28946478/26579517/7648aad4-4534-11e7-917e-2b306a5d5372.png)

I attach also the logs you have asked me, both in one file (I have had problems uploading separated): 
[dbeaver-logs.txt](https://github.com/serge-rider/dbeaver/files/1038019/dbeaver-logs.txt)

**Comment by serge-rider** [comment]
Unfortunately there is nothing valuable in logs.
Looks like this is a driver-specific behavior. DBeaver just shows what driver provides..

**Comment by carlosherranz** [comment]
It's the IBM original driver (jt400.jar)
![image](https://cloud.githubusercontent.com/assets/28946478/26622852/12630e3e-45ec-11e7-9788-d34317d1e0a8.png)
as you can see. But the curious is the different "bad" behavior only with some tables, with any others works properly. It's a pity.

**Comment by tati-kru** [comment]
Hi @carlosherranz!
Could you, please, check that it can be reproduced or not on the latest version?

**Comment by carlosherranz** [comment]
Still the same

**Comment by Condor70** [comment]
I have no problem displaying DB2 for i table definitions.

I'm using the jt400-jdk8-9.5.jar driver on IBM v7r1.

1. Which OS version are you using?
2. Which jt400 version are you using?
3. Is the object you want to examine a PF, a LF or a TABLE?

ps. I did set the driver property "metadata source" to "0" to make it return the LABEL instead of the REMARK for the descriptions.

**Comment by carlosherranz** [comment]
I'm using:

1. Windows 8.
2. jt400-jdk8-9.6.jar drviker on IBM v7r1.
3. Always PF objets

I've tried with metadata to '0', and to '1'.. Same results in both cases.

**Comment by serge-rider** [comment]
@carlosherranz Did you try latest jt400 driver version (9.6)?
Is there anything related to columns reading in error/debug log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by carlosherranz** [comment]
Yes, I'm using that driver version. And there is not anything related to columns reading in error/debug  log files.

**Comment by Condor70** [comment]
Do you see the columns when you query them from the metadata?

`select * from QSYS2.COLUMNS where TABLE_SCHEMA = 'DSGCDAT' and TABLE_NAME = 'AUTOSPF'`

**Comment by carlosherranz** [comment]
No I don't

**Comment by Condor70** [comment]
OK, in that case DBeaver is not to blame. Even the jt400 driver is not at fault here.

I assume there is no metadata available for this table, because this table was created incorrectly.

**Comment by uslss** [comment]
There is no update on the ticket for more than a year.
Ticket is closed.
If the issue is still reproducible for you - feel free to reopen the ticket and add some details that could help to reproduce the issue or create the new one.
