### ISSUE TITLE
Write a wiki page about getting rid of UI flickering when using the X Input Method

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#16991]
As an Eclipse RCP apllication, DBeaver suffers from the following bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=517671. We need a wiki page that accumulates known workarounds.

**Comment by Destrolaric** [comment]
https://github.com/dbeaver/dbeaver/wiki/Troubleshooting-system-issues

**Comment by E1izabeth** [comment]
Please add the dots to the end of sentences.
