### ISSUE TITLE
Object parameter [true] binding not supported(DBeaver 21.3.2, ClickHouse 22.6.1.1985)

### ISSUE THREAD

**Issue by zhengb0** [dbeaver/dbeaver#16995]
When I manually insert/modify data, the field of type Bool is set to true and an error is reported, But I have no problem using sql to insert

<img width="346" alt="image" src="https://user-images.githubusercontent.com/23613077/177679526-d728c264-b407-4ad8-afa5-85c86f9c83b3.png">
<img width="204" alt="image" src="https://user-images.githubusercontent.com/23613077/177679563-cf25aed3-453f-4784-a684-706c24333401.png">

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/23613077/177679250-51b1dff9-b186-43a7-9729-df48a86a8804.png">

**Comment by uslss** [comment]
thanks for the report
