### ISSUE TITLE
Azure SQL nvarchar columns show incorrect lengths

### ISSUE THREAD

**Issue by xantari** [dbeaver/dbeaver#16996]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 22.1.1

#### Connection specification:
- Database name and version: Azure SQL
- Driver name: com.microsoft.sqlserver.jdbc.SQLServerDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

When viewing tables with nvarchar columns in Azure SQL The column lengths are divided by 2, which reports an incorrect column length.

I believe it was due to this work around which should be reverted: https://github.com/dbeaver/dbeaver/commit/7d2a5551a27d801a60b62eb5e71c230c5f4f56c9

Which stemmed from this: https://github.com/dbeaver/dbeaver/issues/5981

Here is an example of what SSMS (SQL Server Management Studio) shows:

![image](https://user-images.githubusercontent.com/6610039/177685137-0a505f18-3c1c-4a0b-9601-3ba84bac6b87.png)

As shown in DBeaver (notice FileName shows 127 instead of the correct value of 255):

![image](https://user-images.githubusercontent.com/6610039/177685094-8f9d360d-aa6f-47b9-8398-349ff4d9df21.png)

Table example script:

```sql
CREATE TABLE [dbo].[Downloads](
	[DownloadId] [int] IDENTITY(1,1) NOT NULL,
	[CenterId] [int] NOT NULL,
	[FileName] [nvarchar](255) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[FileDataId] [int] NULL,
	[CreateDate] [datetime2](7) NOT NULL,
	[UpdateDate] [datetime2](7) NULL,
 CONSTRAINT [PK_Downloads] PRIMARY KEY CLUSTERED 
(
	[DownloadId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```

**Comment by E1izabeth** [comment]
Maybe connected to https://github.com/dbeaver/dbeaver/issues/17066
