### ISSUE TITLE
Update the article: Reset UI settings

### ISSUE THREAD

**Issue by emironovDB** [dbeaver/dbeaver#16998]
Need to add more information about functionality in this article: [Reset UI settings](https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings)
[According to this issue](https://github.com/dbeaver/dbeaver/issues/16840#issuecomment-1176229833), user doesn't understand how to reset settings. So we need to add some screenshots to clear this question.

**Comment by E1izabeth** [comment]
Both articles about `Reset UI settings` and `Reset workspace` were updated: screenshot of how to use it with DBeaver
https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings
https://github.com/dbeaver/dbeaver/wiki/Reset-workspace
