### ISSUE TITLE
Picking up wrong spanner database in URL

### ISSUE THREAD

**Issue by stanfordpeng** [dbeaver/dbeaver#16994]
#### System information: 
- Mac OS BigSur
- DBeaver version:22.1.1.202206261508

#### Connection specification:
- GCP Spanner emulator
- driver: Google Cloud Spanner https://cloud.google.com/spanner/docs/use-oss-jdbc

#### Describe the problem you're observing:
Picking up wrong database name when there are two database with same prefix , see below:
![image](https://user-images.githubusercontent.com/48232605/177673979-5840ecf0-8b1f-4abb-a02d-d8684c456d9d.png)
This is the other database with same prefix, DBeaver picks up:
![image](https://user-images.githubusercontent.com/48232605/177674050-a8174974-b47a-4bb9-a568-8f079b358099.png)

#### Steps to reproduce, if exist:
Create twp databases with same prefix in spanner db emulator, then connect using DBeaver

#### Include any warning/errors/backtraces from the logs
Can't believe there is bugs like this....

**Comment by LonwoLonwo** [comment]
Hello @Stanford-Peng 

Did you use the standard Spanner connection? Or some custom connection type?

![2022-07-11 11_49_47-DBeaver 21 1 0 - postgres](https://user-images.githubusercontent.com/45152336/178225739-f62e197f-2e9c-4091-a632-6b629776e81f.png)

![2022-07-11 11_48_00-Connect to a database](https://user-images.githubusercontent.com/45152336/178225563-8ed1daa8-e983-4301-9f24-d6e1254403d7.png)

Is the URL invalid already on the first screen or is the image cropped?

![2022-07-11 11_50_16-177673979-5840ecf0-8b1f-4abb-a02d-d8684c456d9d png (Изображение PNG, 991 × 400 п](https://user-images.githubusercontent.com/45152336/178226116-3b64c8e2-5736-43a4-8f7d-4a560d9b96e2.png)

**Comment by stanfordpeng** [comment]
@LonwoLonwo  I used the first one(Undeprecated one)

**Comment by LonwoLonwo** [comment]
How did you add localhost info into URL? It is not in the snadard connection dialog

**Comment by stanfordpeng** [comment]
Click on Edit Driver Settings:
<img width="705" alt="image" src="https://user-images.githubusercontent.com/48232605/178643370-7978a56c-ea3f-455e-be0a-bec3afdebf7b.png">

**Comment by LonwoLonwo** [comment]
Can you please provide a screen from the Edit driver page?

![2022-07-13 10_18_32-DBeaver Ultimate 22 1 2 - _postgres12local_ Script-170](https://user-images.githubusercontent.com/45152336/178674368-490eb9a7-596d-4c4b-bc8f-a015fbe82024.png)

**Comment by stanfordpeng** [comment]
OK I think Edit Driver Page can configure the URL correctly. But the first page is just so misleading I mean what is the point of asking database name and project if everything is gonna configured in the URL. When they conflict, we tend to believe in the setting in the first page

**Comment by stanfordpeng** [comment]
This can be closed. It might be an "undocumented feature" lol
