### ISSUE TITLE
Private key provided is invalid or not supported .. DerInputStream.getLength(): lengthTag=56, too big

### ISSUE THREAD

**Issue by GuenterSch** [dbeaver/dbeaver#17009]
#### System information: 
- Operating system Windows 10 21H1
- DBeaver version 22.1.1

#### Connection specification:
- Database name Snowflake 6.22.0
- Driver name snowflake-jdbc-3.13.20.jar

#### Describe the problem you're observing:
Test connection in the Connection settings returns the following error:
**Private key provided is invalid or not supported: C:\Users\z000xxxx\Keys\Dev_mnxxxxxxx_tu_exx_taxxxx_private_key.pem: DerInputStream.getLength(): lengthTag=56, too big.**

In Driver properties the following user properties are configured:
private_key_file
private_key_file_pwd

I think, a variable has the wrong size definition.

An older issue with a similar, but not identical, error message is https://github.com/dbeaver/dbeaver/issues/8946#issue-636672378

Maybe this link can give you further hints:
https://community.snowflake.com/s/article/Private-key-provided-is-invalid-or-not-supported-rsa-key-p8--data-isn-t-an-object-ID

Thanks for solving this problem, BR
Günter

**Comment by jtg567** [comment]
Found this issue by searching, facing something similar and wondering if it's actually not a Snowflake bug?

I'm also trying to keypair authenticate to Snowflake to save myself from several MFA pushes to my mobile device when working with DBeaver. I've similarly set the `private_key_file` and `private_key_file_pwd` properties.

My error:`Private key provided is invalid or not supported: /Users/joshgaunt/.ssh/rsa_key.pem: overrun, bytes = 1196`

Open Snowflake issue from almost 2 years ago: https://github.com/snowflakedb/snowflake-jdbc/issues/327

**Comment by emironovDB** [comment]
@GuenterSch 
Could you answer what is the type of the key you are using?

**Comment by GuenterSch** [comment]
Hello Eugene,
the private key file (*.pem) contains the following code:

-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-256-CBC,F7DEB6495A2F896B651E82EDA641F8A8

**Comment by dbeaver-pm** [comment]
Hello @GuenterSch,

Have you tried connecting using the private key in DBeaver PRO? It has dedicate support for private key authentication.

**Comment by GuenterSch** [comment]
Hello DBeaver-PM,

no, I use the DBeaver Community Version. I think it should work here also.

**Comment by uslss** [comment]
Does this issue still actual against the recent version?

**Comment by GuenterSch** [comment]
Hello Dziyana,
I tried it yesterday. YES, I got the same problem with the new version 22.3.3.
BR
Günter

Private key provided is invalid or not supported: C:\Users\xxxxxxxx\Keys\Dev_xxxxxxxxxxxxxxxxxxxxxxx_private_key.pem: DerInputStream.getLength(): lengthTag=56, too big.
--With an other connection
Private key provided is invalid or not supported: C:\Users\xxxxxxxx\Keys\Prd_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_private_key.pem: java.security.InvalidKeyException: IOException : DerInputStream.getLength(): lengthTag=23, too big.

**Comment by iraidaa** [comment]
Here we plan to make the third workaround from https://community.snowflake.com/s/article/Private-key-provided-is-invalid-or-not-supported-rsa-key-p8--data-isn-t-an-object-ID available for such keys in the private key authentication type in DBeaver PRO:

> If it is not viable to use unencrypted private keys, then using third party crypto libraries like Bouncy Castle , to decrypt the encrypted private keys of OpenSSL 1.1.1g 

We plan to fix it in DBeaver PRO. We will be glad if this fix improves the situation with this type of keys in DBeaver CE, but we do not officially support this authentication mechanism in DBeaver CE.

**Comment by serge-rider** [comment]
Cannot reproduce

**Comment by flambchap** [comment]
@GuenterSch Can you please tell me what command you used to create the key?

The article you mentioned in the OP describes the issue with OpenSSL 1.1.1.g and a key with a passphrase. Do you know if you use the same setup?

**Comment by serge-rider** [comment]
I don't think that it is related to key format or something.

It may be related to encryptred keys (keys with password). The last Snowflake drivers just ignores password in some cases.
We added a workaround for that.
