### ISSUE TITLE
Documentation page for setting config.ini system properties has errors

### ISSUE THREAD

**Issue by sochotnicky** [dbeaver/dbeaver#17002]
#### Describe the problem you're observing:
In https://github.com/dbeaver/dbeaver/issues/16146 a suggestion was to follow https://github.com/dbeaver/dbeaver/wiki/How-to-set-a-variable-if-dbeaver.ini-is-read-only to override trust store location

However [example config.ini](https://github.com/dbeaver/dbeaver/wiki/How-to-set-a-variable-if-dbeaver.ini-is-read-only#configini-example) in that documentation has 2 crucial errors in it:
1. `javax.net.ssl.truststore` should be properly capitalized `javax.net.ssl.trustStore` or it won't be actually enabled (on some systems anyway)
2. System properties in `config.ini` should be specified without `-D` prefix.

#### Steps to reproduce, if exist:
You can try setting for example "javax.net.debug=all" vs "-Djavax.net.debug=all" in `config.ini` and compare results. Same thing with `trustStore` vs `truststore`

I tested this in the official flatpak

**Comment by E1izabeth** [comment]
Hi, @sochotnicky.
Thank you for the reporting it to us.

**Comment by riednyko** [comment]
@sochotnicky thank you for the reporting it. These errors in the documentation have been fixed.
