### ISSUE TITLE
Auto-collect log files from the UI

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#17003]
We often ask users to collect log files from the file system and send them back to us. People sometimes face some issues here. For example, they do not send us all the needed log files. We need an option in the Help menu that collects all the logs and suggests saving them as an archive to some place in the file system.

**Comment by flambchap** [comment]
We also need to anonimize logs in the process, see https://github.com/dbeaver/dbeaver/issues/17088.

**Comment by xikeda-hunzi** [comment]
Hello, Could you give me your contact information?I had some problems following this procedure:
https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse
when i import the maven project, some packages cannot be downloaded.
Thanks

**Comment by xikeda-hunzi** [comment]
my email:598968428@qq.com/haofei_mu@163.com

**Comment by xikeda-hunzi** [comment]
> Hello, Could you give me your contact information?I had some problems following this procedure: https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse when i import the maven project, some packages cannot be downloaded. 
Thanks

my email:[598968428@qq.com](mailto:598968428@qq.com)/haofei_mu@163.com
