### ISSUE TITLE
Add update/delete/insert/etc. statements to Console View

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#17014]
We need to show text of query and statistics.

**Comment by jetzerb** [comment]
Text of queries _is_ showing in the console view. With each rowset, it seems:
![image](https://user-images.githubusercontent.com/36859020/178527595-7d26e8a0-f735-49a6-ba79-abebf8d498f1.png)

I would like the query text to be _optionally_ output, based on a setting in the preferences window.

**Comment by E1izabeth** [comment]
@jetzerb, yes, it works for `select`, but doesn't work for other statements which doesn't have result set with data (like `update`, `insert` or `delete`).
