### ISSUE TITLE
Wiki for Console View

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#17018]
Write wiki about Console View: https://github.com/dbeaver/dbeaver/wiki/Console-View

- [x] what is it? how to use it?
- [x] default preference
- [x] saved state per script
- [x] restore after tab was closed if it's still enabled
- [x] context menu

**Comment by AlexandreHGuerra** [comment]
May i suggest a way to describe a way to set 2 things?
1) Line wrap or not
2) Allow a single column of 32-64Kb chars, in orde to dump DDL scripts per table or object
Its an amazing and very useful feature

**Comment by E1izabeth** [comment]
@AlexandreHGuerra, could you describe it in more details?
1. Do you mean to make a setting to include line wrap between query text and result or not? Or which line wrap are you talking about?
2. Do you mean to create a custom DBeaver command to print the object ddl to the console view?

**Comment by E1izabeth** [comment]
Maybe I misunderstood and you asked to make some suggestions for wiki article... Anyway, you can write it here.
