### ISSUE TITLE
Change string representation of arrays in the spreadsheet

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#17017]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 22.1.2

#### Describe the problem you're observing:
Change Default string view for expandable array in Data Grid
#### Steps to reproduce, if exist:
![image](https://user-images.githubusercontent.com/31996417/178000761-0450063b-af5d-4914-a342-cc8ac6a45782.png)

**Comment by ShadelessFox** [comment]
Fixed in #16887
