### ISSUE TITLE
Geometry view for Oracle incorrectly works in CE

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#17024]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 22.1.2

#### Connection specification:
- Database name and version Oracle
- 
#### Describe the problem you're observing:
Geometry view for Oracle incorrectly works in CE. Expand button is available for the row, but it doesn't work
![image](https://user-images.githubusercontent.com/31996417/178007763-492e1c3d-4919-42af-881a-5586201272d5.png)

**Comment by E1izabeth** [comment]
Expand button is not available anymore when `Show complex column structure` is not set.
But expand button is still available and doesn't work when `Show complex column structure` is set.
![image](https://user-images.githubusercontent.com/28875055/205281402-a371e637-0876-4dde-9d5c-659cc30f5b84.png)

**Comment by ShadelessFox** [comment]
It should work, you simply don't have any elements in any of its arrays. So maybe we don't need to fix anything here.

**Comment by E1izabeth** [comment]
You are right, it works if `SDO_ELEM_INFO ` or `SDO_ORDINATES ` has more than one element. The triangle confused me.

**Comment by ShadelessFox** [comment]
So the question is, do we even need to do anything?

**Comment by tati-kru** [comment]
Works as expected
