### ISSUE TITLE
Column autocomplete doesn't work when a table and a schema have the same name

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#17036]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 22.1.1.202207041729

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
Execute a `select * from <a table name like a schema name> where` and call SQL Assist

**Expected**: the table column appear in the dropdown menu
**Actual result**: no proposals appears in the dropdown and the cursor moves to the beginning of the line.

https://user-images.githubusercontent.com/51405061/178107893-350963d2-13f9-44da-bc41-172dd34ff5c8.mp4

**Comment by d2k2-git** [comment]
i have other issue. when i use a scheme prefix in "from"-selection i dont get autocomplete for table columns

select * from schema.table1 as t1 where t1.<autocomplete not working> 

select * from table1 as t1 where t1.<autocomplete working here>

**Comment by E1izabeth** [comment]
The initial reason for this issue is that the cursor jumps to the beginning of the line on right-clicking.
