### ISSUE TITLE
Out Of Memory

### ISSUE THREAD

**Issue by wangqian-49** [dbeaver/dbeaver#17040]
#### System information: 
- Operating system (distribution) and version : Centos 7.4
- DBeaver version : 21.2.2
- Additional extensions

#### Connection specification:
- Database name and version : Oracle
- Driver name 
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:

When previewing GIF files, it takes up too much memory, resulting in out of memory

#### Steps to reproduce, if exist:

1. Create a new Oracle connection and create a table in which the column type is blob.

2. On the data tab page, add a row, right click -->edit-->load from file, Select a GIF file with a size of 14MB.

3. Use free -h to check that the machine memory is 6.2GB.

3. Click the value box on the right to view the preview content.

4. Use free -h to check that the machine memory is 4.9GB.

The screenshot is as follows:

![1657507113911_BD8F9CFC-0E4D-4b57-A1A4-F59E461583AA](https://user-images.githubusercontent.com/52651443/178221682-23c8cf42-e18a-4c09-bce4-0dd68287a3c0.png)

![1657506936787_708ABDAE-45BD-462b-801B-470615E6F0E9](https://user-images.githubusercontent.com/52651443/178221651-a5bc2eb4-c712-4bae-b685-6e1c816893e2.png)

![1657506976254_10939A02-5538-491d-8CBB-5D48803C810C](https://user-images.githubusercontent.com/52651443/178221672-7f6cc42e-2ce5-4416-a3cd-002ec80ae30d.png)

**Comment by Matvey16** [comment]
@wangqian-49 Can you specify what button exatly do you click to view content?

**Comment by wangqian-49** [comment]
> @wangqian-49 Can you specify what button exatly do you click to view content?

1. Double click the table in the tree navigation bar on the left, and the table information will be displayed on the right
2. Click the data tab page
3. Select a data
4. Open the value viewer on the right to view the preview information

**Comment by Matvey16** [comment]
@wangqian-49 Thank you for the report. We'll see what can be done about that.

**Comment by Matvey16** [comment]
@wangqian-49 Is it possible for you to attach this gif here. Or at least say it's dimentions in pixels?

**Comment by wangqian-49** [comment]
@Matvey16 896 × 700 pixels

**Comment by Matvey16** [comment]
@wangqian-49 Thank you for the report. I wasn't able to reproduce that big of a memory leak, but for fullHD gif of 15 mb, DBeaver took 400Mb of memory. As a temporal workaround I can propose to allow more memory for DBeaver by starting it with `-Xmx3072m` that way it will at least continue to work and won't cause out of memory.
