### ISSUE TITLE
Named parameter prefix doesn't work anymore with underscores

### ISSUE THREAD

**Issue by hackenspp** [dbeaver/dbeaver#17043]
#### System information: 
- Operating system (distribution) and version: Windows 11
- DBeaver version: 22.1.2.202207091909
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 14
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
In Preferences / Editors / SQL Editor / SQL processing, the "Named parameter prefix" doesn't work anymore with the underscore character (it used to work in 22.0.4).
It works with :, &, +, ... 
We have tons of scripts with underscore as parameter, so it would be preferable to keep this setting, otherwise I'll stick with the old version.

#### Steps to reproduce, if exist:
Set "Named parameter prefix" to _
>select _parameter
SQL Error [42703]: ERROR: column "_parameter" does not exist
  Position: 8

**Comment by E1izabeth** [comment]
Hello, @hackenspp. Thank you for bug report.
