### ISSUE TITLE
Role field too short in Snowflake connection

### ISSUE THREAD

**Issue by rpalloni** [dbeaver/dbeaver#17047]
#### System information: 
- Ubuntu 20.04
- 22.1.2

#### Connection specification:
- Snowflake

#### Describe the problem you're observing:
If you write a >8 chars role you cannot see it clearly (see image)

![image](https://user-images.githubusercontent.com/17080117/178310780-9115c253-37aa-4a74-a201-9e8ef6e3d2cc.png)

**Comment by LonwoLonwo** [comment]
Thanks for the report @rpalloni

**Comment by GuenterSch** [comment]
Suggestion: Why you do not use the same size like "Authenticator" (resizeable)?

**Comment by LonwoLonwo** [comment]
Hello @GuenterSch 
Usually, ROLE's name is not so long as Authenticator.

**Comment by GuenterSch** [comment]
Hello Anastasiya
in our Account we use role names like
DEV_???_EXTENSION_DISTRIBUTE_RESTRICTED

I thought, the dialog is not more "symetric" (I do not know the right word ;-) ).
