### ISSUE TITLE
DB Full-Text search bug in new version

### ISSUE THREAD

**Issue by PliusMinus** [dbeaver/dbeaver#17041]
#### System information: 
- Operating system (distribution) and version: MS Win 11 Pro
- DBeaver version: 22.1.2.202207091909

#### Connection specification:
- Database name and version: Oracle 11g
- Driver name: Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Describe the problem you're observing:
I noticed two problems after installing the latest version of DBeaver:
1. When trying to mark the objects in which want to search, there is no checkBox and cannot see which objects is (un)marked.
2. If I don't mark the objects and search through the entire database, I get an error (picture attached)
![checkBox](https://user-images.githubusercontent.com/109067184/178224785-0cf442f8-ef91-4d47-8ae9-f4ef7a14a07d.jpg)
![full_db_search](https://user-images.githubusercontent.com/109067184/178224809-06b10976-2597-4128-a6da-8d3fe1efea1f.jpg)

**Comment by LonwoLonwo** [comment]
Hello @PliusMinus 

Thanks for the bug report.

Now Full-text Search looks like Metadata Search, and we think it is better.

You can use Ctrl to select several objects at once.

![8BM9t5Duyu](https://user-images.githubusercontent.com/45152336/178264565-c430bea8-7fdb-4d9b-b0d2-587c8a28617d.gif)

**Comment by PliusMinus** [comment]
Thanks for explanation.
It is better if I want to mark only one or several schemas. But I have many dozens of schemas and I want only few schemas to skip - in this case it is not better.

**Comment by LonwoLonwo** [comment]
And what about `Shift` on all schemas and then `Ctrl` on these schemas, which you want to skip?

**Comment by PliusMinus** [comment]
With shift select all and then with ctrl unselect few... ok, that's a solution too.

**Comment by LonwoLonwo** [comment]
The bug is still not fixed, so I reopened this issue to fix the bug.
