### ISSUE TITLE
The Dbeaver executable launcher was unable to locate its companion shared library

### ISSUE THREAD

**Issue by hansw-nlo** [dbeaver/dbeaver#17048]
#### System information: 
- Distributor ID:	Debian Description:	Debian GNU/Linux 11 (bullseye) Codename:	bullseye
- DBeaver dbeaver-ce (22.1.2) (installed with apt, no Flatpak
- Additional extensions

#### Connection specification:
- 10.5.15-MariaDB-0+deb11u1 Debian 11 (unrelated, it is not connected yet
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When starting using the cli it shows the following, the GUI shows the title in a dialog. 

plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.400.v20211117-0650: cannot open shared object file: No such file or directory

####

**Comment by hansw-nlo** [comment]
B.t.w. All of the updates are installed for Debian

**Comment by hansw-nlo** [comment]
The plugin is not avaliable in the new version, I do have it in timeshift, getting that one in place does not solve it. Maybe a dependency problem?

**Comment by alvaro-canepa** [comment]
I have the same issue in Mint 20.3. 
Back to 22.1.1

**Comment by hansw-nlo** [comment]
I copied the old timeshift version of that plugin recursive ( cp -r ) and now it does work. Suppose it was not distributed somehow

**Comment by gustavohpg** [comment]
I have the same issue in Linux Mint.

**Comment by barba-sudo** [comment]
Removing the lines below from the dbeaver.ini file solved the problem for me.
dbeaver.ini - Located at **/usr/share/dbeaver-ce**

--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.400.v20211117-0650

**Comment by davidjohnsonmedaxion** [comment]
> Removing the lines below from the dbeaver.ini file solved the problem for me. dbeaver.ini - Located at **/usr/share/dbeaver-ce**
> 
> --launcher.library plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.400.v20211117-0650

@barba-sudo 's fix solved the problem for me.

**Comment by turbopixel** [comment]
> Removing the lines below from the dbeaver.ini file solved the problem for me. dbeaver.ini - Located at **/usr/share/dbeaver-ce**
> 
> --launcher.library plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.400.v20211117-0650

@barba-sudo Thanks man! It works on Linux Mint 20.3, too!

**Comment by serge-rider** [comment]
This happened because of two simultaneous events:
- dbeaver.ini was marked as configuration file
- we migrated to a new Eclipse version (it has different launcher jar).

Because dbeaver.ini contains explicit launcher jar reference it broke.

For now we will revert the first fix.
Then we will remove explicit jar references.
Then return config files mark.

**Comment by TechnoDexx** [comment]
> Removing the lines below from the dbeaver.ini file solved the problem for me. dbeaver.ini - Located at **/usr/share/dbeaver-ce**
> 
> --launcher.library plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.400.v20211117-0650

It's worked for me too.

**Comment by barba-sudo** [comment]
Hi guys,
today i found a file named dbeaver.ini.dpkg-dist in the same folder that mentions a different version of the plugin and this one is present in the package.
Replacing the contents of dbeaver.ini with the contents of this file also worked. I think this is some bug related to the update process.

**Comment by turbopixel** [comment]
Yes, this is possible. I was asked during the update if the .ini file should be kept, merged or replaced. 

After I replaced my ini file, the error message came the next time I started dbeaver.

**Comment by hansw-nlo** [comment]
Thanks to all involved. I think I will close the issue
