### ISSUE TITLE
Moving Project to New Location While Keeping Local Versioning Data

### ISSUE THREAD

**Issue by Xylandor** [dbeaver/dbeaver#17051]
**Is your feature request related to a problem? Please describe.**
Yes, when it comes to the need to move a project's physical location to another location. Doing this manually will cause you to lose all local versioning data. DBeaver does not provide a way to easily move projects. 

**Describe the solution you'd like**
It would be nice to have a feature that will allow you to transfer a project from one location to another without losing any historical data, such as local versioning. Using my real-life issue as an example, if you need to move projects from one cloud service's location to another (e.g. OneDrive to Google Drive), there should be a way to transfer everything seamlessly via DBeaver and it still retain all knowledge of local versioning history.

**Describe alternatives you've considered**
Currently, the only way I know of is to remove the project, move the files to the new location, create a new project and point it to the new location. The major problem with this is that you lose all your local versioning history; and because this data is lost, it's not possible to compare changes to a script or revert back to a previous version. This local versioning is a very nice feature in DBeaver, but we do need a way to retain this history during a project move.

**Additional context**
Where is that local history stored at anyways? And is there a way to manually move it over with the project files? Or at least edit a config file or something to point it to the new location?

**Comment by emironovDB** [comment]
Hello @Xylandor,

Can you please explain what you mean by "local versioning"?

**Comment by Xylandor** [comment]
@emironovDB ,

I'm referring to the local history within DBeaver. I use the term "local versioning" because of the way it keeps track of each script's save point to where you can compare and revert back if needed.

**Comment by flambchap** [comment]
Hi @Xylandor. Can you please tell me how you can see this data in DBeaver?

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
