### ISSUE TITLE
Dictionary value from ERD not showing

### ISSUE THREAD

**Issue by l3e7f-scskl** [dbeaver/dbeaver#17059]
System information:

    Operating system Fedora 36
    DBeaver version 22.1.2

Describe the problem you're observing:

Dictionary value from ERD database not showing in resulted query

![image](https://user-images.githubusercontent.com/109147238/178477653-4c5fe807-f041-4835-8020-026a9dccc6ce.png)
![image](https://user-images.githubusercontent.com/109147238/178477912-b8044248-eb69-4c63-a5fa-6b0640e96cb3.png)

**Comment by LonwoLonwo** [comment]
Can you please check the latest DBeaver release? https://dbeaver.io/download/
The Dictionary panel was changed in release 22.1.2

**Comment by l3e7f-scskl** [comment]
> Can you please check the latest DBeaver release? https://dbeaver.io/download/ The Dictionary panel was changed in release 22.1.2

I'm terribly sorry, I meant 22.1.2. As additional information, It works on 22.1.1.

**Comment by LonwoLonwo** [comment]
Can you tell me more please about your database?

**Comment by l3e7f-scskl** [comment]
> Can you tell me more please about your database?

mariadb  Ver 15.1 Distrib 10.5.16-MariaDB, for Linux (x86_64) using  EditLine wrapper.
I get it from standard fedora 36 repository. No other tweaks.

**Comment by LonwoLonwo** [comment]
Can you provide some steps to issue? I can't reproduce for now.

**Comment by l3e7f-scskl** [comment]
Steps:
1. create db
2. import from csv data
3. click 2x on database name 
4. on the arrow menu on the right, select connection
5. from related table connect them
6. create new sql script from db
7. the test i just showed use 'select * from tbl' without ';' (other query are the same, can't get the dictionary value).
9. from the resulted query, click the column value (would show like the picture)

I will give video/gif later...

**Comment by l3e7f-scskl** [comment]
https://user-images.githubusercontent.com/109147238/178671487-61d11137-3dba-4cdd-8c95-3c13b8cf131c.mp4

**Comment by ShadelessFox** [comment]
Thanks for the bug report
