### ISSUE TITLE
Add option to include server output in console view

### ISSUE THREAD

**Issue by jetzerb** [dbeaver/dbeaver#17064]
It would be useful to include the "database server output" in the console view, so that those server messages are collated with the rowset data.

This could be toggled via a config setting:
![image](https://user-images.githubusercontent.com/36859020/178532096-e044b5f9-ca28-4683-9b02-dd7dd5fbba78.png)

Consider a (MSSQL) script like this (from [comment on #667](https://github.com/dbeaver/dbeaver/issues/667#issuecomment-565182905)):
```sql
print 'Explanation for data set 1';
select ... from ...;

print `Explanation for data set 2`;
select ... from ...;

. . . etc . . .
```

Behavior as of 22.1.2.202207091909 puts printed messages only in the server output window.
![image](https://user-images.githubusercontent.com/36859020/178539271-ab8fe437-5af9-4d52-85eb-ddbc069d9835.png)

Desired output (query text removed for clarity):
```txt
Explanation for data set 1

| # | v |
+---+---+
| 1 | 1 |
| 2 | 2 |
| 3 | 3 |

3 row(s) fetched.

Explanation for data set 2

| # | v |
+---+---+
| 1 | a |
| 2 | b |
| 3 | c |

3 row(s) fetched.
```
> See #17014 for discussion on including query text in the console view

**Comment by E1izabeth** [comment]
Hello, @jetzerb. Thank you for feature request.

**Comment by drtdev1** [comment]
Hello Everyone,

In DBeaver 24.3.0 I cannot find "Console View" settings in Preferences ... I am looking for the same, to have a single text output (like in MS), so I can execute a script file with multiple queries and the result will be a single output (and can save/export as some report file)

Any help is appreciated. Thank you!

LATER EDIT: I found "SQL Terminal" on the side of the editor/script window, but it still opens all queries in results grids, does not limit to text output in SQL Terminal only
