### ISSUE TITLE
Hiding a column when all the rows matching this columns are empty or NULL

### ISSUE THREAD

**Issue by deft01** [dbeaver/dbeaver#17061]
Hi,

I would like to know if there is a way to hide **dynamically** empty columns (all rows are empty on this column).
It is very time consuming searching for empty columns every query and display only usefull infos.

![image](https://user-images.githubusercontent.com/10063471/178507731-6233886b-739b-42b1-86cd-8901882fff19.png)

Thanks in advance for your answer.

**Comment by E1izabeth** [comment]
Hi, @deft01. Which database do you use?

**Comment by deft01** [comment]
Thank you for your blazingly fast answer.
Im using Postgresql. :)

**Comment by E1izabeth** [comment]
There is no such option.
Thank you for feature request.

**Comment by deft01** [comment]
I would like to highlight the point which is, this feature could help each time you meet these **two simple conditions** :
 1) SQL request that can contain empty columns (_very often case in my sense, ex : SELECT * FROM table; or just clicking on a table in the GUI_)
 2) SQL request that contains at least ten columns (_also very often with trivial resquest like SELECT * and clicking on a table in the GUI_)

It became **very paintfull** to scroll horizontally to visualise datas (more than ten rows). This feature give you a big gain of time. The idea is we could activate with a button only the columns containing informations (not NULL or not empty).
I think this could be very usefull for a **lot of people**.
 
 Thanks for this amazing tool. :smile:
