### ISSUE TITLE
"Not Null" preference is getting lost while creating a new column

### ISSUE THREAD

**Issue by gsthorat** [dbeaver/dbeaver#17070]
#### System information: 
- Operating system (distribution) and version - Windows 10
- DBeaver version - 22.1.1.202206261508

#### Connection specification:
- Database name and version - Oracle 19c

#### Describe the problem you're observing:
When we try to create a new column using GUI as shown below,

![image](https://user-images.githubusercontent.com/29622633/178719416-6b32ec6a-0958-418f-98d2-4ad3e2a8bc7b.png)

and if you select/tick **Not Null** checkbox to make column as not null

![image](https://user-images.githubusercontent.com/29622633/178719599-ac6d5807-3152-47b2-9041-c6ae59a6df21.png)

It shows that you have selected **Not Null** option but when you try to save it you lose that preference as below,

![image](https://user-images.githubusercontent.com/29622633/178720348-5392b8b2-0e8e-47e8-82c4-16a7c221ab96.png)
 
The generated sql has no Not null in it so when you persist it you see that the column is nullable

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @gsthorat
