### ISSUE TITLE
Editor border very wide, non-functional entries

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#17071]
#### System information: 
- Operating system (distribution) and version Debain/SID
- DBeaver version 22.1.2
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Editors now have a very wide left border, almost double the size as before.
Additionally, there are two entries, dark grey and showing an ellipsis, that have neither a tooltip, nor does anything happen when one hovers over/clicks those.

I seem to be unable to find a setting to revert back nor do I see why exactly the border got so wide.

**Comment by 2019-05-10** [comment]
![Screenshot_20220713_131140](https://user-images.githubusercontent.com/50481865/178722123-3a816b07-f1a1-4226-a0d7-8911bc9847dc.png)

**Comment by E1izabeth** [comment]
Hello, @2019-05-10. Thank you for bug report.

**Comment by E1izabeth** [comment]
@2019-05-10, have you tried to [reset UI settings](https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings)?

**Comment by E1izabeth** [comment]
And how did you install DBeaver?

**Comment by 2019-05-10** [comment]
> @2019-05-10, have you tried to [reset UI settings](https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings)?

What exactly does that reset? The page does say nothing about side effects and what exactly the result will be.
Since DBeaver does not include Eclipse's
`Window -> Perspective -> Save Perspective As ...`
that probably means all configuration (Views, positions) will be lost?

**Comment by 2019-05-10** [comment]
> And how did you install DBeaver?

```
wget https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb -O /tmp/dbeaver-ce_latest_amd64.deb
apt install ./dbeaver-ce_latest_amd64.deb
```

**Comment by E1izabeth** [comment]
> > @2019-05-10, have you tried to [reset UI settings](https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings)?
> 
> What exactly does that reset? The page does say nothing about side effects and what exactly the result will be. Since DBeaver does not include Eclipse's `Window -> Perspective -> Save Perspective As ...` that probably means all configuration (Views, positions) will be lost?

Yes, all ui configuration will be lost.

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If the issue is still actual for you, feel free to reopen it.
