### ISSUE TITLE
Question : Upgrade Portable while Maintaining Additional Software

### ISSUE THREAD

**Issue by valsamis-d** [dbeaver/dbeaver#17081]
Hello,

Is there anyway to upgrade the portable version of DBeaver (Win64) while maintaining, already installed packages, like Office Integration, Darkest Dark Theme etc.?

I have tried the following:

1. unzipping the new version in a temp directory
2. Do a compare by content temp vs. regular directories 
3. Push changes and new files from temp to regular directory 

However, this doesn't seem to work correctly as DBeaver displays an error message upon starting it up.

Thank you 
Dimitrios

**Comment by E1izabeth** [comment]
There is no such possibility for the moment. See #5317
