### ISSUE TITLE
Provide way to export and anonymize logs

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#17088]
Asking for logs, `dbeaver-debug.log` in particular, seems a good idea -- until one looks closer.
It took me some time to fix all occurences of IPs. hostnames, usernames and sundry stuff that should not be made public.

I propose to add a facility to export that logs in a way that one can easily post, without qualms about giving away too much information.

**Comment by flambchap** [comment]
Thank you for the idea. I'll add this functionality in the scope of https://github.com/dbeaver/dbeaver/issues/17003.

**Comment by flambchap** [comment]
We'll do it in this ticket.

**Comment by LonwoLonwo** [comment]
We can add this as an option.

**Comment by ShadelessFox** [comment]
Hello @2019-05-10,

Starting from 24.0.3, we mask sensitive data reported when using SSH tunnels. Maybe you know other places where sensitive information can also be found?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
