### ISSUE TITLE
Snowflake function names randomly highlited

### ISSUE THREAD

**Issue by rpalloni** [dbeaver/dbeaver#17080]
#### System information: 
- Ubuntu 20.04
- Dbeaver 22.1.2

#### Connection specification:
- Snowflake

#### Describe the problem you're observing:
Some snowflake functions are highlighted, some are not and I could not find any settings for custom keywords coloring.

![image](https://user-images.githubusercontent.com/17080117/178783603-d92e32c8-8921-4db7-884b-b269237b5955.png)

**Comment by E1izabeth** [comment]
Related to #6528

**Comment by LonwoLonwo** [comment]
Hello @rpalloni 

You can send us the list of the most popular and helpful Snowflake functions, and we will add them to the Snowflake functions list.

**Comment by rpalloni** [comment]
https://docs.snowflake.com/en/sql-reference/functions-all.html

**Comment by LonwoLonwo** [comment]
Ok, thanks.
