### ISSUE TITLE
Keyboard shortcut for Alt 126

### ISSUE THREAD

**Issue by solisgb** [dbeaver/dbeaver#17083]
Alt 126 (~) is frequently used in Postgres searches with regular expressions.

**Comment by ShadelessFox** [comment]
Hello @solisgb,

Can you please elaborate? It's not entirely clear what your feature request is about.

**Comment by solisgb** [comment]
Please excuse the bad formulation of my request.  On the other hand, I have just checked that it has already been incorporated into the current version of DBeaver. Previously you could not type the ~ symbol in the SQL console by pressing Alt + 1, 2, 5 on the keyboard, but now you can. In conclusion, do not consider this request, I apologize.

**Comment by ShadelessFox** [comment]
I see.

So I assume that the issue can be closed now.

Please let me know if you have any questions left.

**Comment by solisgb** [comment]
Yes, it should be closed.
