### ISSUE TITLE
"Making a thread dump" -- wrong command given

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#17091]
[Making a thread dump](https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump)

says to run on Linux/Mac
```
jstack $(ps aux | grep -m1 dbeaver | awk '{print $2}') > thread-dump.txt
```

Chances are, 
```
$(ps aux | grep -m1 dbeaver | awk '{print $2}')
```
will retrive the PID of the native launcher process `/usr/bin/dbeaver` instead of the expected JVM.
Presuming that there should be one JVM running DBeaver at any given time, the command should be modified to rather look for the JVM process:

```
jstack $(ps aux | grep java | grep dbeaver | awk '{print $2}') > thread-dump.txt
```

**Comment by flambchap** [comment]
Agreed. Thank you for noticing.

**Comment by flambchap** [comment]
Fixed.
