### ISSUE TITLE
Skip duplicate values ​​and continue insert Postgres

### ISSUE THREAD

**Issue by maritogaleano** [dbeaver/dbeaver#17100]
#### System information: 
- DBeaver version: 22.1.2.202207091909
- PostgreSQL version: PostgreSQL 9.2.24 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

When importing a csv, it does not allow me to ignore the duplicates and insert the data that is not in my table, I try the ignore option but nevertheless it does not insert any value

![image](https://user-images.githubusercontent.com/57814047/179242808-9521ef32-6775-4b15-a072-b32244df560b.png)

**Comment by LonwoLonwo** [comment]
Hello @maritogaleano 

Data file example will be beneficial.

Also, did you try using the option "Ignore duplicate values"?

![2022-07-15 17_41_17-Data Transfer](https://user-images.githubusercontent.com/45152336/179246698-8ee7a478-707b-41bc-b9bf-fb3288515abf.png)

**Comment by maritogaleano** [comment]
If I try to use the option, but it doesn't give me the option to enable it, how do I enable it?

![image](https://user-images.githubusercontent.com/57814047/179247858-bb381581-7b85-48b3-b21a-cbaf5d9b5056.png)

Regarding the data, this would be an example which I want to migrate to the table called "clients", in the csv file I have a value which I want to migrate to the table in which said value does not yet exist

### (Those marked in red already exist in the table, however the value marked in yellow does not yet)


![image](https://user-images.githubusercontent.com/57814047/179248495-cdca63b9-bca4-4278-bbdc-9d83ae616839.png)

**Comment by ShadelessFox** [comment]
Hello @maritogaleano,

You have to disable batches.

**Comment by uslss** [comment]
there has been no update on the issue for a long time.
If the issue is still reproducible for you - feel free to reopen it with additional info.
