### ISSUE TITLE
Dbeaver crashed 4 times today

### ISSUE THREAD

**Issue by tsingla-mwb** [dbeaver/dbeaver#17116]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions
<img width="307" alt="Screen Shot 2022-07-18 at 8 44 01 AM" src="https://user-images.githubusercontent.com/86621760/179594506-8566c665-11ff-44ec-9d0e-4002078e2725.png">

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
please, provide some steps to reproduce the issue. [Logs ](https://github.com/dbeaver/dbeaver/wiki/Log-files)also could be helpful

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If the issue is still actual for you, feel free to reopen it.
