### ISSUE TITLE
Postgres connection stuck "Read data types" in DBs with several objects

### ISSUE THREAD

**Issue by marcelothomaz** [dbeaver/dbeaver#17117]
#### System information: 
- Operating system (distribution) and version: Windows 11
- DBeaver version: 22.1.2.202207091909

#### Connection specification:
- Database name and version: PostgreSQL
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH Tunel

#### Describe the problem you're observing:
DBeaver keeps several minutes "Read data types", executing lots of the following queries
SELECT e.enumlabel 
FROM pg_catalog.pg_enum e
WHERE e.enumtypid=XXXXX
ORDER BY e.enumsortorder

XXXXX is an id

It seems lazy (postponed) loading is not working. It would be better to read only times for the current schema.

#### Steps to reproduce, if exist:
Just try to connect to a database instance with several objects.

#### Include any warning/errors/backtraces from the logs
No specific warnings.

**Comment by LonwoLonwo** [comment]
Hello @marcelothomaz 

Different data types can be in different schemas, and data types from a non-current schema can be used in tables, etc., in a current schema. So we need to know about these types.

But tell me, please - what do you mean - stuck? How many enum-reading rows do you have in the Query manager?

**Comment by uslss** [comment]
there has been no update on the issue for a long time. If it is still actual - feel free to reopen it

**Comment by andrewmslack** [comment]
I get same non-responsiveness whilst attempting to connect to a postgresql rds db hosted on AWS:
"connect to jdbc:postgresql://.....  Read data types" and the connection just sits there, waiting.
