### ISSUE TITLE
Unable to generate select SQL on procedures

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#1711]
I would like to run procedures after selecting them. This could be done i.e. if there was a generate select SQL for procedures option. Reference: this is possible in PgAdminIII.

**Comment by serge-rider** [comment]
Please provide some example. I'm not quite understand what is "select on procedures" in general. Or this is something PG-specific?

**Comment by TrampolineMan** [comment]
Example: I have a procudure as  aggregate_all(calendar_yearmonth::smallint)
If I could choose generate SQL -> Select it could come out as
Select aggregate_all(<calendar_yearmonth>).
Then in the script window I just replace the variable name with the time period and hit run to execute the proceedure.
Is there any similar functionality currently?

**Comment by uslss** [comment]
already implemented
![image](https://user-images.githubusercontent.com/31996417/109970325-f8f44a80-7d05-11eb-9cbc-288b12e932f8.png)
