### ISSUE TITLE
[SNOWFLAKE] strange characters in output SELECT

### ISSUE THREAD

**Issue by emanueol** [dbeaver/dbeaver#17120]
#### System information: 
- Operating system (distribution) and version
Windows 10 Home ~ 21H1 ~ 19043.1826

- DBeaver version
22.1.2.202207091909 ~ 11-JULY-2022
- Additional extensions
Eclipse 2022-06 - https://download.eclipse.org/releases/2022-06/ --> TM Terminal

#### Connection specification:
- Database name and version
Snowflake

- Driver name
net.snowflake.client.jdbc.SnowflakeDriver

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:
A simple json file uploaded to a snowflake stage:
--my.json - Json only contains carriage return+new line (0x0D 0x0A) special characters.
[
{"name":"John", "age":"30"},
{"name":"Mary", "age":"35"}
]

--After executing following SELECT to list contents of my.json:
select $1 from @db.sch.internal_stage;
--DBEaver shows text output  strange characters: 0xC2 0xB6 (instead of 0x0D 0x0A)
$1                                 
-----------------------------------
{¶  "age": "30",¶  "name": "John"¶}
{¶  "age": "35",¶  "name": "Mary"¶}

#### Steps to reproduce, if exist:
```
---------------------------------------------------------------------------------------------------------------------------------
--start:          setup test environment                                                                                       --
---------------------------------------------------------------------------------------------------------------------------------
use role accountadmin;
select CURRENT_DATE(), CURRENT_ACCOUNT(), CURRENT_ROLE(), current_warehouse(), CURRENT_DATABASE(), CURRENT_SCHEMA();
 
--creates
use role useradmin;
create or replace role etl;

--grants
use role securityadmin;
grant role sysadmin to role etl;

--assign roles to users
use role useradmin;
grant role etl to user emanueoldev1;
---------------------------------------------------------------------------------------------------------------------------------
--end          setup test environment                                                                                          --
---------------------------------------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------------------------------------
--setup test - internal stage loading file format, copy force=true/purge=true
---------------------------------------------------------------------------------------------------------------------------------
use role accountadmin;
drop database if exists  db;



use role etl;
create or replace database db;
create schema if not exists sch;
select CURRENT_DATE(), CURRENT_ACCOUNT(), CURRENT_ROLE(), current_warehouse(), CURRENT_DATABASE(), CURRENT_SCHEMA();

--------------------------------------------------------------------------------
--my.json file
[
{"name":"John", "age":"30"},
{"name":"Mary", "age":"35"}
]
--------------------------------------------------------------------------------

use role etl;
use database db;
use schema sch;

cd G:\My Drive\myDev  cloud snowflake\.datafiles
snowsql -c dev1 -r etl -d db -s sch -q "PUT file://my.json @db.sch.internal_stage;"
* SnowSQL * v1.2.21
Type SQL statements or !help
+---------+------------+-------------+-------------+--------------------+--------------------+----------+---------+
| source  | target     | source_size | target_size | source_compression | target_compression | status   | message |
|---------+------------+-------------+-------------+--------------------+--------------------+----------+---------|
| my.json | my.json.gz |          57 |          80 | NONE               | GZIP               | UPLOADED |         |
+---------+------------+-------------+-------------+--------------------+--------------------+----------+---------+

list @db.sch.internal_stage;
name                     |size|md5                             |last_modified               |
-------------------------+----+--------------------------------+----------------------------+
internal_stage/my.json.gz|  80|6910dcc3ba0dfb8219e86897c137ea54|Sun, 3 Jul 2022 16:07:55 GMT|

--following strange characters appearing as ¶  are 0xC2 0xB6  in hexedit
select $1 json from @db.sch.internal_stage;
JSON                             
---------------------------------
{¶  "age": 30,¶  "name": "John"¶}
{¶  "age": 35,¶  "name": "Mary"¶}

--now replacing inside snowflake json 0x0D 0x0A to nothing, we can see problem no longer appear - obviously - in DBeaver
select replace($1,chr(13)||chr(10),'') json from @db.sch.internal_stage;
JSON                    
------------------------
{"age":30,"name":"John"}
{"age":35,"name":"Mary"}

```

So some bug from DBEaver which translates 0x0D 0x0A into 0xC2 0xB6 both in the TEXT query output and/or GRID.

![image](https://user-images.githubusercontent.com/8422412/179756119-6e6fd915-92c1-44bb-88c4-e33758a124d4.png)
![image](https://user-images.githubusercontent.com/8422412/179756201-569c463d-ceef-433b-81d6-fe660d198bdd.png)
![image](https://user-images.githubusercontent.com/8422412/179756684-6383a8dc-8015-4057-9987-e76a00d6568b.png)

**Comment by LonwoLonwo** [comment]
Hello @emanueol 

Please tell me more about your issue.
What kind of discrepancy do you see here? DBeaver shows your value with special symbols inside because it tries to show inline.

![2022-09-01 12_47_03-Window](https://user-images.githubusercontent.com/45152336/187897237-ad81f7c0-4a73-41f5-ada3-178696f95916.png)

You can open the Value panel and see your data without special symbols but on different lines.

So Paragraph Characters are some auxiliary characters here.

**Comment by LonwoLonwo** [comment]
Or JSON view 
![2022-09-01 14_12_38-Window](https://user-images.githubusercontent.com/45152336/187900807-a10bf84d-0b8f-4afb-8911-57fc790e3827.png)

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
