### ISSUE TITLE
Timestamp config is not saving selection

### ISSUE THREAD

**Issue by rpalloni** [dbeaver/dbeaver#17125]
#### System information: 
- Operating system: Ubuntu 20.04
- DBeaver version: 22.1.2

#### Describe the problem you're observing:
Client Timezone setting is not persisting selection.
To reproduce the problem simply select a Timezone and apply and close.
If you reenter the config, Default is selected. (And actually what is 'Default'?)

![image](https://user-images.githubusercontent.com/17080117/179797422-8a6d5eb5-1539-4fa0-a6ad-a67b07c74376.png)

This in turn produces some strange behavior with databases (e.g. Snowflake). 
Currently is 18:06 (Europe/Rome timezone). If you run:

```
SELECT
localtime(), 
localtimestamp(),  -- ok
current_time(), 
current_timestamp(), -- ok
sysdate(); -- UTC
```
![image](https://user-images.githubusercontent.com/17080117/179797731-9be3ee4d-46c9-4128-bfe2-be7847001eea.png)

And even if you set timezone, you get strange result:

```
ALTER SESSION SET TIMEZONE = 'Europe/Rome';

SELECT 
localtime(), -- UTC+3 wrong
localtimestamp(), 
current_time(), -- UTC+3 wrong
current_timestamp(),
sysdate();
```

![image](https://user-images.githubusercontent.com/17080117/179798325-e7ac4734-830a-437f-8ca4-b55d0b26e560.png)

It is ok in Snowflake WebUI

![image](https://user-images.githubusercontent.com/17080117/179800557-d4cecabf-e7ef-47d0-ae5d-fce8e6200ef7.png)

**Comment by Destrolaric** [comment]
Hi, I looked into described problems 
1. Unfortunately couldn't reproduce it, a video may help.
2. Data editor applies current timezone for used dates if there is no manual override, you can disable date/time formatting in `Data Formats` preferences

**Comment by uslss** [comment]
there has been no update on the issue for a long time. If it is still actual - feel free to reopen it
