### ISSUE TITLE
[SNOWFLAKE] Can't open SQL Stored Procedures parameters or code on schemas with underscore _

### ISSUE THREAD

**Issue by danryushin** [dbeaver/dbeaver#17121]
#### System information: 
- Operating system (distribution) and version: Windows 10 Enterprise 21H2
- DBeaver version: 22.1.2
- Java version: 1.8.0_331-b04
- Additional extensions

#### Connection specification:
- Database name and version: Snowflake 6.23.0
- Driver name: JDBC Snowflake 3.13.6
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No 

#### Describe the problem you're observing:
When trying to visualize the parameters and source code for stored procedures on schemas with underscore, I get the following error:

/* ERROR WHILE READING SOURCE:

SQL Error [1003] [42000]: SQL compilation error:
parse error line 1 at position 35 near '95'.
parse error line 1 at position 39 near '95'.
*/

On snowflake, it seems that DBeaver is trying to escape the underscore on the schema name on the desc procedure command:

![image](https://user-images.githubusercontent.com/79051427/179764466-8f0e1a89-0cac-4160-9459-8513b588df65.png)

Same doesn't happen on desc function, there no escape of the underscore is done and everything works fine.

![image](https://user-images.githubusercontent.com/79051427/179764691-aa3b3d28-4698-434a-927f-b0ac4c279039.png)

#### Steps to reproduce, if exist:
Create a procedure on a schema that has underline on the schema name. DBeaver won't be able to show the parameters/source code of the procedure.

Create any other object (View, function) inside the same schema name. DBeaver is able to read and get the source code without any issue.

#### Include any warning/errors/backtraces from the logs

[procedure_error.log](https://github.com/dbeaver/dbeaver/files/9141450/procedure_error.log)

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
Maybe connected with https://github.com/dbeaver/dbeaver/issues/17065

**Comment by LonwoLonwo** [comment]
Hello @danryushin 

As I can see, your issue is solved in the last Snowflake driver version.

You can change it in your connection settings.

![2022-09-01 00_58_49-DBeaver 22 2 0 - MediaType](https://user-images.githubusercontent.com/45152336/187792925-291fe5b0-dbef-44ba-98a2-9f90103d8d97.png)

Please try it and give us feedback - is driver upgrading helped you?

**Comment by danryushin** [comment]
Hello,

Thanks, with the new driver the procedures are now working fine for visualization
