### ISSUE TITLE
The JVM shared library "/System/Library/Frameworks/JavaVM.framework" does not contain the JNI_CreateJavaVM symbol

### ISSUE THREAD

**Issue by hxp0618** [dbeaver/dbeaver#17127]
System information:
Operating system: macOs Monterey12.4 (M1 max) 
DBeaver version: 22.1.2

#### Describe the problem you're observing:
Modify vm to local jdk and start the application
<img width="882" alt="image" src="https://user-images.githubusercontent.com/30236140/179943113-d250f128-7714-43d4-9640-4f23f3680eef.png">

<img width="263" alt="image" src="https://user-images.githubusercontent.com/30236140/179942669-b98381f7-acad-4b46-aa98-7008c07bea59.png">

**Comment by hxp0618** [comment]
I have found the problem, I need to specify the vm parameter to the java directory ,as below：
-vm
/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java

**Comment by mannas384** [comment]
I have found the problem, I need to specify the vm parameter to the java directory ,as below：
-vm
/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java


The above command is not working for me.

ERROR:  The JVM shared library "/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/bin/../jre/lib/server/libjvm.dylib"
does not contain the JNI_CreateJavaVM symbol.

**Comment by rebolyte** [comment]
adding `/bin/java` worked for me with JDK 22
