### ISSUE TITLE
Teradata not showing procedures in DBeaver?

### ISSUE THREAD

**Issue by Austin1** [dbeaver/dbeaver#17126]
#### System information: 
- Operating system (distribution) and version: Mac OS Dbeaver
- DBeaver version 22.1.2.202207091909
- Java version: openjdk version "18.0.1.1" 2022-04-22
- Additional extensions: Excel

#### Connection specification:
- Database name and version: Teradata 16
- Driver name: Packaged with dbeaver version 17
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
I would like to be able to view procedures in the navigation window and select them to view the code within the procedure. Similarly, views appear in the navigation window, but you cannot view the "view definition".

#### Steps to reproduce, if exist:
Connect to Teradata source and try to navigate to a procedure or view and double click

**Comment by uslss** [comment]
@Austin1 unfortunately, cannot reproduce the issue. Could you provide video with the issue? Is there something in the [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by Austin1** [comment]
Sorry! For some reason I didn't get a reply notification OR it got buried somehwere in Gmail updates category.

I'm outling what I consider two separate issues below:

I've now upgraded to 22.1.3 and I'm re-testing.

Here are my driver settings to make sure I dont have a versioning issue with what you all deploy as the "latest" that you all partnered with Teradata on:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/341408/182163009-ac8e5895-ba9f-4577-b54e-19989e76ef23.png">

### Not showing anything but Views in the Database Navigator pane
This is me trying to double click a schema and view the contents of that schema. It is missing anything besides views. I know this schema also has procedures. Could it be a setting issue because I use schema filters?
![image](https://user-images.githubusercontent.com/341408/182163937-b6438eda-74f3-437c-8254-dc03ddadda2a.png)

Schema filter - this shouldn't mess with the objects underneath a schema in TD, I thought? I can't see a reason why this woudl have anyhting to do with it, but including for reference.
![image](https://user-images.githubusercontent.com/341408/182164499-bcd81305-f08d-4c18-b02b-c331f248ab27.png)

### Unable to view table/view/procedure definitions
1. Well, I just viewed a "view definition" without a problem. So now I need to solve why I can't see procedures in the navigator and test the definition screen. I want to say procedures used to show up and I could view the definition, but I can't test without resolve above.

**Comment by Austin1** [comment]
Update

I made a net new connection with no schema filters and now all the types are appearing under the database instead of just views. Is that a bug or do I have a setting wrong?

Also - I was able to confirm that seeing source definitions for procedures is NOT a problem.

**Comment by LonwoLonwo** [comment]
Hello @Austin1 

> Also - I was able to confirm that seeing source definitions for procedures is NOT a problem.

So, please tell me. Did your issue disappear after filter clearing? And was the main issue with schema filters?

> It is missing anything besides views.

Yes, that it's not ok.
Could you please send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by LonwoLonwo** [comment]
Also, can you please check your connection view mode? Maybe changing to "Advanced" will help.

![2022-08-03 10_19_43-DBeaver 22 1 4 - TESTDB](https://user-images.githubusercontent.com/45152336/182548350-6dcf3355-d111-4e0c-b559-62b1d760d7f6.png)

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it.
