### ISSUE TITLE
Permissions management

### ISSUE THREAD

**Issue by TrampolineMan** [dbeaver/dbeaver#1712]
I am managing permissions on schemas, tables, views and procedures in a postgres database. I cannot find any feature that lets me efficinetly manage these in dbeaver. In PgAdminIII there was grant wizards, automatic generation of permission for objects when gerneating SQL, and editing of permission was possible when rightclicking on objects. 

For schemas I don't even see the permissions listed among properties.

What is the plan for permission handling in dbeaver in upcoming versions?

**Comment by serge-rider** [comment]
For now DBeaver supports only read-only permissions information in table/view properties. Plus read-only role information.
There is no any plan. If you have any ideas - please share. 
Note that it is better describe UI features without references on pgAdmin because I'm not pgAdmin user.

**Comment by TrampolineMan** [comment]
Sorry about brining up pgAdmin all the time. Only reason I bring it up is because the things dbeaver don't support at this time, I need to use the other one for thoose features only. 
I am trying to find out if there is someway to do all of the tasks from dbeaver directly because I would like to drop the other one premanently.

**Comment by TrampolineMan** [comment]
Regarding permission management I imagine that most database admins with a distributed db will need to give various levels of access to different users. I don't know other dbs than postgres well so I am not able to tell how much thoose features differ between different brands and/or if it can be standardized. I would just like to point out it is a big potential to be able to handle all types of access rights in the same tool.

**Comment by GiantCrocodile** [comment]
I would like to see this too: adding (existing) permissions to tables/dbs/schemas with DBeaver.

**Comment by serge-rider** [comment]
Partially it was done in 4.2.4. Will be continued in 4.2.5.

**Comment by serge-rider** [comment]
First version will be added in 4.3.2:
![image](https://user-images.githubusercontent.com/6398845/34613714-cd1842e4-f23f-11e7-9d6e-8f5361b9d37e.png)

**Comment by jerherder** [comment]
Hello

in dbeaver 4.3.0, the permissions added on the sequences are not visible. it exists but no visible in the properties panel of permissions

Kind regards

**Comment by jerherder** [comment]
Sorry

this functionnality was added in the 4.3.4 version.

PostgreSQL: sequence management
PostgreSQL: default driver version was updated (42.2.0)
PostgreSQL: permission management was improved (sequences support) and fixed (role name escaping)

**Comment by jerherder** [comment]
Hello

with the new version 4.3.4, we don't see the permission select on the sequence. we can just put the permission usage.

**Comment by serge-rider** [comment]
@jerherder this was fixed in #2986
