### ISSUE TITLE
DBeaver fails to start on Linux Mint - GTK initialization error.

### ISSUE THREAD

**Issue by mpapachristoforou** [dbeaver/dbeaver#17138]
#### System information: 
OS Distribution: **Linux Mint 20.3 Una**
OS Base: **Ubuntu 20.04 focal**
Kernel: **5.15.0-41-generic x86_64**
Desktop: **Cinnamon 5.2.7** 
DBeaver: **v22.1.2** _(Deb Installer)_
Java: **OpenJDK v11.0.15** _(build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)_

#### Describe the problem you're observing:

DBeaver fails on start-up with the following GTK initialization error message:

> plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.400.v20211117-0650: cannot open shared object file: No such file or directory

#### Steps to reproduce, if exist:

1. Use a Linux Mint machine with similar setup to aforementioned 'System Information'.
2. Install DBeaver using the DEB package (download from website)
3. Start DBeaver

**Comment by emironovDB** [comment]
Could you please try the latest version and see if this helps?

**Comment by mpapachristoforou** [comment]
Yes, works perfectly! :smiley: 

Thanks Eugene

**Comment by mpapachristoforou** [comment]
closing ticket
