### ISSUE TITLE
no triggers shown in table triggers

### ISSUE THREAD

**Issue by tatod** [dbeaver/dbeaver#17131]
#### System information: 
- Operating system (distribution) and version - Linux Mint 20.2 Uma
- DBeaver version - 22.1.0.202206051253
- Additional extensions - office

#### Connection specification:
- Database name and version - Oracle Oracle Database 12c EE Extreme Perf Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Real Application Clusters, Automatic Storage Management, OLAP,
Advanced Analytics and Real Application Testing options
- Driver name - Oracle JDBC driver 12.2.0.1.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  n/a

#### Describe the problem you're observing:
Table triggers are empty for APPS.
However, the triggers are visible when their table properties are opened.

#### Steps to reproduce, if exist:
Create table in XXDFIX schema, create synonym of it for APPS. Then create trigger on that table under APPS. Try to filter it in APPS table triggers or XXDFIX table triggers - it is not showin in any of them.

#### Include any warning/errors/backtraces from the logs

n/a

**Comment by LonwoLonwo** [comment]
Hello @tatod 

I'm not so familiar with Oracle. Can you please explain to me - what APPS is? Is this the Shema name or something else?

**Comment by tatod** [comment]
> Hello @tatod
> 
> I'm not so familiar with Oracle. Can you please explain to me - what APPS is? Is this the Shema name or something else?

yes, APPS and XXDFIX are the schema names

**Comment by iraidaa** [comment]
Hello @tatod,

I was trying to reproduce the issue. I can see the trigger not on the synonym but the table of the original schema in the Table Triggers folder on the left. 


Maybe you can try to Refresh the schema after the trigger creation?


Could it be an Oracle feature that triggers written on synonym of a table are linked to the original table?

**Comment by uslss** [comment]
there has been no update on the issue for a long time. If it is still actual - feel free to reopen it
