### ISSUE TITLE
Most of Snowflake objects are unavailable in dbeaver

### ISSUE THREAD

**Issue by rpalloni** [dbeaver/dbeaver#17139]
#### System information: 
- Ubuntu 20.04
- DBeaver version 22.1.2

#### Connection specification:
- Snowflake

#### Describe the problem you're observing:

Most of Snowflake objects are unavailable in dbeaver (see image: LF Dbeaver, RG WebUI )

![image](https://user-images.githubusercontent.com/17080117/180204101-94994be8-a4f5-4f97-bb14-9737ecc0f648.png)

**Comment by LonwoLonwo** [comment]
Hello @rpalloni 

Functions and procedures are in the "Procedures" folder in DBeaver.

And I can see INFORMATION_SCHEMA.PIPES and INFORMATION_SCHEMA."STAGES" views to get metadata about stages and pipes.
Not sure about "streams" and "tasks". Maybe, in this case, we can use https://docs.snowflake.com/en/sql-reference/sql/show-streams.html and https://docs.snowflake.com/en/sql-reference/sql/show-tasks.html.

So, thanks for the idea.
