### ISSUE TITLE
ALIAS not showing up in Column Headers

### ISSUE THREAD

**Issue by scottlapoint** [dbeaver/dbeaver#17146]
![Screen Shot 2022-07-21 at 3 12 33 PM](https://user-images.githubusercontent.com/24252132/180284463-5a33e7ea-2bc1-4424-a13d-939d72dfbcd5.png)

#### System information: 
- Operating system (distribution) and version - MACOS 12.4
- DBeaver version - 22.1.2 (this has been going on for the last few updates at least)
- Additional extensions - Darkest Dark (tried without it - issue still persists)

#### Connection specification:
- Database name and version - 5.1.44
- Driver name MYSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  - NO, standard PW authentication

#### Describe the problem you're observing:

When running a query with ALIASES, the ALIAS does not always display in the column header.

#### Steps to reproduce, if exist:

Run any query with ALIASES. (I've attached a sample in the screenshot)

**Comment by LonwoLonwo** [comment]
Hello @scottlapoint 

Can you please provide `log_uploads` DDL and your select query here? For testing.

**Comment by scottlapoint** [comment]
It's not happening on this table specifically, it happens to any of them, here are the details you requested.

SELECT id,pid AS PID,date AS `LOAD_DATE`,FROM_UNIXTIME(stamp) AS `LOAD_DATE_TIME`,records AS `RECORDS_LOADED`
FROM log_uploads WHERE date = current_date

CREATE TABLE `log_uploads` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(11) NOT NULL,
  `date` date DEFAULT NULL,
  `stamp` int(11) DEFAULT NULL,
  `file` varchar(255) DEFAULT NULL,
  `orig_file_name` varchar(255) DEFAULT NULL,
  `log_debug_file` varchar(500) DEFAULT NULL,
  `user` varchar(255) DEFAULT NULL,
  `records` int(11) DEFAULT NULL,
  `dupes` int(11) DEFAULT '0',
  `skipped` int(11) DEFAULT '0',
  `records_infile` int(11) DEFAULT '0',
  `other` int(11) NOT NULL DEFAULT '0',
  `recs_deleted` int(11) NOT NULL DEFAULT '0',
  `hist_record_count` int(11) NOT NULL DEFAULT '0',
  `recs_autoclosed` int(11) NOT NULL DEFAULT '0',
  `filepath` varchar(1000) DEFAULT NULL,
  `batchid` varchar(25) DEFAULT NULL,
  `notified` tinyint(1) NOT NULL DEFAULT '0',
  `dev` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `pid` (`pid`) USING BTREE,
  KEY `date` (`date`) USING BTREE,
  KEY `stamp` (`stamp`),
  KEY `records` (`records`)
) ENGINE=InnoDB AUTO_INCREMENT=8630375 DEFAULT CHARSET=latin1

**Comment by scottlapoint** [comment]
I also installed on a Windows machine, and tested, seems to be ok there, so related to MACOS only it seems.

**Comment by LonwoLonwo** [comment]
Thanks.
I can't reproduce it now, but I also use Windows. We will try to check it on Mac.

![2022-07-25 09_36_39-DBeaver Ultimate 22 1 3 - _MySQL 5 5_ Script-68](https://user-images.githubusercontent.com/45152336/180713548-84125aac-64a6-4fee-91da-3c10f85ef94f.png)

**Comment by scottlapoint** [comment]
Just noticed there was an update and installed.

No change (not sure if the note about fixing column aliases was related to this issue or not). 

 ** Also side note, each time there is an update it wipes out my darkest dark theme, I have to reinstall it each time.

**Comment by Matvey16** [comment]
@scottlapoint Can you run `SHOW variables;` and see what is the value for lowercase_table_names?

**Comment by scottlapoint** [comment]
Here you go.

lower_case_table_names	1

**Comment by emironovDB** [comment]
@scottlapoint 
Could you provide the driver version?

**Comment by scottlapoint** [comment]
MySQL 8.0.30

**Comment by Matvey16** [comment]
@scottlapoint Sorry for the late response, but it is crucial to know which of those drivers you picked to create a connection
![image](https://user-images.githubusercontent.com/82543000/199692449-bcfbc03e-78cb-4aca-be1f-2faa0e59bbf7.png)

**Comment by scottlapoint** [comment]
DBeaver picked and installed the driver when I setup my connection initially.  Here are the details from the driver settings.
![Screen Shot 2022-11-03 at 8 44 01 AM](https://user-images.githubusercontent.com/24252132/199712801-7cd0b32f-da73-4c3f-ad1a-a55dcf956ddb.jpg)
![Screen Shot 2022-11-03 at 8 44 14 AM](https://user-images.githubusercontent.com/24252132/199712802-e759a819-95c0-4dc7-b729-07b851052f4a.jpg)
![Screen Shot 2022-11-03 at 8 44 26 AM](https://user-images.githubusercontent.com/24252132/199712805-292642c2-1dd6-4c9d-895e-ff00181169ec.jpg)
![Screen Shot 2022-11-03 at 8 44 47 AM](https://user-images.githubusercontent.com/24252132/199712806-2e80c832-6e35-469e-8b01-c65279b86fce.jpg)
![Screen Shot 2022-11-03 at 8 45 04 AM](https://user-images.githubusercontent.com/24252132/199712808-7be3c67f-4871-418e-b88e-a5cfd75219ac.jpg)

**Comment by LonwoLonwo** [comment]
![2022-11-18 12_53_16-Preferences](https://user-images.githubusercontent.com/45152336/202673699-9ebed53f-f331-431b-82ae-1fce9cff4691.png)

Hello @scottlapoint 

Can you please change the values of this setting in your Preferences and then recheck your query?

**Comment by scottlapoint** [comment]
That did the trick! I had no idea that setting was there! Works great now!
![Screen Shot 2022-11-21 at 10 40 46 AM](https://user-images.githubusercontent.com/24252132/203082969-e944aa53-0aef-41d1-8eb7-c9cdc23d25c0.jpg)

**Comment by LonwoLonwo** [comment]
Thanks for the answer @scottlapoint

**Comment by KeithGriffiths2002** [comment]
This has been driving me nuts for weeks, thanks
