### ISSUE TITLE
dbeaver.exe: Pin to taskbar not working (Windows 7)

### ISSUE THREAD

**Issue by AlterEgoDev** [dbeaver/dbeaver#1714]
Hello,

I want to pin DBeaver (dbeaver.exe) to the taskbar in Windows 7. The problem is that the right click menu does not open. Please add or implement this feature, I do not want to create a Desktop icon, nor do I want to add DBeaver to the Windows Start menu.

**Comment by serge-rider** [comment]
Can't reproduce (Pint to taskbar work fine in Windows 7/8/10 in my test environment).
How do you install DBeaver (installer/zip archive)? Is there anything special about your system?

**Comment by BernhardMaier** [comment]
Not really, this happens on both of my computers (Windows 7 64-bit and Windows 10 64-bit), I just downloaded the Windows 64-bit ZIP archive from your website: http://dbeaver.jkiss.org/files/dbeaver-ce-latest-win32.win32.x86_64.zip

**Comment by serge-rider** [comment]
Umm.
Did you try to use installer?

**Comment by BernhardMaier** [comment]
I tried it now with the installer and it works. However, it is still annoying that I can't use the ZIP archive because it duplicates the icon in the taskbar.

**Comment by kohanyirobert** [comment]
[I've commented on an issue](https://github.com/dbeaver/dbeaver/issues/3070#issuecomment-381388199) regarding the same problem on Windows 10. There's a solution.
