### ISSUE TITLE
datetime

### ISSUE THREAD

**Issue by Achilles-Wang** [dbeaver/dbeaver#17149]
cant delete data in clickhouse，and turn out to report  “Timestamp format must be yyyy-mm-dd hh:mm:ss”。when I use “select now()”,result is like '2022-07-22 15:51:13.000'.but when i use it in cmd, result is rightly like "2022-07-22 15:51:13"

**Comment by Achilles-Wang** [comment]
is it related to JAVA?

**Comment by LonwoLonwo** [comment]
Hello @Achilles-Wang 

Can you please provide your table DDL and data sample?

**Comment by Achilles-Wang** [comment]
CREATE TABLE review_output.corpus
(

    `comment_id` String,

    `valid` Nullable(Int16),

    `corpus` String,

    `cut_time` DateTime DEFAULT now(),

    `channel` Nullable(String),

    `category` Nullable(String),

    `brand` Nullable(String)
)
ENGINE = ReplacingMergeTree
ORDER BY comment_id
SETTINGS index_granularity = 8192;

**Comment by Achilles-Wang** [comment]
![飞书20220725-150345](https://user-images.githubusercontent.com/46441147/180717904-f2f188e4-a83b-4729-96ae-574291e08b18.jpg)
![飞书20220725-150444](https://user-images.githubusercontent.com/46441147/180717919-f744cc3e-dba2-4d4c-95c1-d91de2af462d.jpg)

**Comment by Achilles-Wang** [comment]
1000000129	1	服务态度 好 锅底 认真 辣 锅底 种类	2022-04-27 18:15:59.000	DP	食品	周师兄火锅
1000000709	1	位置 观音桥 好找 周师兄 外地人 喜欢 本地人 好 味道 喜欢 菜品 精致 还可以 少 服务 帮忙 口罩 明星 打卡 腰片 干 油碟 霸道 机器人 重庆 火锅	2022-04-27 18:15:59.000	DP	食品	周师兄火锅
1000002763	1	好吃 好吃 肚子饿 小郡肝 大 男朋友 牛肉 爱好者 推荐 大刀 腰片 好 小 奥利奥 雪山 不甜 海带苗 嫩 来点 大 小郡肝 冰粉 味道 酒酿 圆子 味道 鸭肠 还行 麻辣 小郡肝 调料 差不多 等位	2022-04-27 18:15:59.000	DP	食品	周师兄火锅

**Comment by Achilles-Wang** [comment]
when i use cmd-client ,datetime columns are correct like '2022-04-27 18:15:59',not '2022-04-27 18:15:59.000'.with the problem,when i modify data,dbeaver report an error like 'Timestamp format must be yyyy-mm-dd hh:mm:ss'

**Comment by Achilles-Wang** [comment]
oh,it reminds me that every datetime column becomes like 'yyyy-mm-dd hh:mm:ss.xxx'.but they seem correct in cmd-client

**Comment by Achilles-Wang** [comment]
oh,it remind me that ervery datetime column becomes like 'yyyy-mm-dd hh:mm:ss.xxx'

**Comment by LonwoLonwo** [comment]
Could you please send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by iraidaa** [comment]
Hello @Achilles-Wang,

Did you try to change the pattern in Windows -> Preferences -> Data Format -> (Format) Type-> Timestamp and Timestamp with Timezone with `yyyy-mm-dd hh:mm:ss` and click **Apply**?

I have performed the steps above and I get the following:

![image](https://user-images.githubusercontent.com/49681450/184112683-9f859984-9de5-457a-a76c-1506e15b2f31.png)

The Delete option works too:
![image](https://user-images.githubusercontent.com/49681450/184114051-01b66f2e-854b-4639-9147-32439fed3e52.png)


You can send us the log files to try to investigate the issue.

**Comment by iraidaa** [comment]
@Achilles-Wang, 

I also suggest trying V22.1.4. Everything worked for me using it.

**Comment by uslss** [comment]
there has been no update on the issue for a long time. If it is still actual - feel free to reopen it
