### ISSUE TITLE
Automatic proxy configuration not showing up on the application

### ISSUE THREAD

**Issue by dimitrispal** [dbeaver/dbeaver#17147]
#### System information: 
- Windows 10 x64
- 22.1.2
- Additional extensions

#### Connection specification:
- Database name and version
- com.mysql.cj.jdbc.Driver  8.0.17
- No 

#### Describe the problem you're observing:
On the documentation i can see the image below but i cannot find it anywhere on the software...
![image](https://user-images.githubusercontent.com/39836056/180375800-49cb0256-915a-4553-a39d-cb880ca0c5aa.png)

I can only see the above: 
![image](https://user-images.githubusercontent.com/39836056/180375953-ceab49a4-6fb4-4d19-8950-f52f7217d871.png)
There is no option "Automatic proxy configuration".

Am i doing something wrong ?

**Comment by LonwoLonwo** [comment]
Hello @dimitrispal 

Thanks for noticing.

Automatic proxy configuration is available only in [DBeaver PRO](https://dbeaver.com/) versions.

I added this info to our wiki page.
