### ISSUE TITLE
Improve object statistics visuals in the navigator

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#17153]
_Originally posted by @givihuda in https://github.com/dbeaver/dbeaver/discussions/16106_

Currently, statistics' visuals are unclear. We want to improve it, so the background is filled left-to-right rather than right-to-left. Also, a light border will highlight the entire statistics bar, making it more pleasant.

![image](https://user-images.githubusercontent.com/35821147/177660984-d4b63ccd-78c8-4049-af2d-797820594cd0.png)

**Comment by givihuda** [comment]
So what happens when the bar overlaps the numbers and letters? They appear to have almost identical colors.

**Comment by ShadelessFox** [comment]
We will use a brighter color for the background and a contrasting color for the text.

It's just a rough visualization of what it would look like.
