### ISSUE TITLE
DBeaver allows exiting while task is running

### ISSUE THREAD

**Issue by valsamis-d** [dbeaver/dbeaver#17152]
#### System information: 
- Operating system (distribution) and version: Windows 10 21H2 (Build 19044.1766)
- DBeaver version: 22.1.2 Portable
- Additional extensions: MS Office, Darkest Theme

#### Connection specification:
- Database name and version: DB2 JCC Type 4 v11.5.70-FP000
- Driver name: db2jcc4,jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes (SOCS)

#### Describe the problem you're observing:
DBeaver allows exiting while a task is running in the background., without prompting with a WARNING!

#### Steps to reproduce, if exist:
Execute a long-running task and exit DBeaver while the task is running.

**Comment by ShadelessFox** [comment]
Hello @valsamis-d,

Which kind of task are you talking about?

**Comment by valsamis-d** [comment]
> Hello @valsamis-d,
> 
> 
> 
> Which kind of task are you talking about?

I have an export task that takes about 1hr to complete. So, when I exit dbeaver by mistake it won't tell that a task is running and let me confirm.

**Comment by ShadelessFox** [comment]
I see. Thanks for the clarification. We should respect background tasks and prevent them from being interrupted.
