### ISSUE TITLE
[Firebird] Update Firebird driver to 5.0.4

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#17169]
### Discussed in https://github.com/dbeaver/dbeaver/discussions/17129

<div type='discussions-op-text'>

<sup>Originally posted by **nilooInGitHub** July 20, 2022</sup>
Hello Dear Community,

I installed DBeaver and firebird 

I have a problem.

1. the stored procedures are not displayed in Navigator?

Can someone help me?        
</div>

**Comment by LonwoLonwo** [comment]
Also, connected discussion: https://github.com/dbeaver/dbeaver/discussions/16920

**Comment by LonwoLonwo** [comment]
Probably we need to read functions and procedures from the system tables, not with the driver.

**Comment by hasanyucel** [comment]
I faced the same problem. Please help me!

**Comment by LonwoLonwo** [comment]
@hasanyucel please check this solution first https://github.com/orgs/dbeaver/discussions/17129#discussioncomment-3187706

**Comment by tonne1** [comment]
I'd suggest this can be closed, as I'm pretty sure that the driver reads the stored procedures from the system tables anyway. Use org.firebirdsql.jdbc:jaybird:RELEASE, Version 5.0.4.java11 or newer.

**Comment by LonwoLonwo** [comment]
Ok, driver updating is a good idea
