### ISSUE TITLE
Exception when open tables list of Clickhouse connection

### ISSUE THREAD

**Issue by zkelo** [dbeaver/dbeaver#17166]
#### System information: 
- Operating system (distribution) and version: **Windows 11 21H2**
- DBeaver version: **22.1.3**
- Additional extensions; **DBeaver Office Support**

#### Connection specification:
- Database name and version: **Clickhouse 21.1.2.15**
- Driver name: **Clickhouse (Legacy)**
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  **Yes, SSH tunnel**

#### Describe the problem you're observing:
When I try to open tables list I get a following error:
```
Code: 47, e.displayText() = DB::Exception: Missing columns: 'comment' while processing query: 'SELECT name AS TABLE_NAME, engine AS TABLE_TYPE, database AS TABLE_SCHEM, comment AS REMARKS, database, name, uuid, engine, is_temporary, data_paths, metadata_path, metadata_modification_time, dependencies_database, dependencies_table, create_table_query, engine_full, partition_key, sorting_key, primary_key, sampling_key, storage_policy, total_rows, total_bytes, lifetime_rows, lifetime_bytes FROM system.tables WHERE database = 'default'', required columns: 'engine' 'database' 'sorting_key' 'total_rows' 'lifetime_rows' 'comment' 'uuid' 'metadata_path' 'engine_full' 'partition_key' 'lifetime_bytes' 'name' 'data_paths' 'metadata_modification_time' 'dependencies_database' 'is_temporary' 'storage_policy' 'create_table_query' 'dependencies_table' 'primary_key' 'sampling_key' 'total_bytes', maybe you meant:  (version 21.1.2.15 (official build))
```

#### Steps to reproduce, if exist:
1. Open app;
2. Create (or use existing) Clickhouse connection;
3. Connect to the server;
4. Click on `Tables` item in connections view.

#### Include any warning/errors/backtraces from the logs
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Ошибка
Mon Jul 25 10:19:06 MSK 2022
java.lang.Throwable: Code: 47, e.displayText() = DB::Exception: Missing columns: 'comment' while processing query: 'SELECT name AS TABLE_NAME, engine AS TABLE_TYPE, database AS TABLE_SCHEM, comment AS REMARKS, database, name, uuid, engine, is_temporary, data_paths, metadata_path, metadata_modification_time, dependencies_database, dependencies_table, create_table_query, engine_full, partition_key, sorting_key, primary_key, sampling_key, storage_policy, total_rows, total_bytes, lifetime_rows, lifetime_bytes FROM system.tables WHERE database = 'default'', required columns: 'engine' 'database' 'sorting_key' 'total_rows' 'lifetime_rows' 'comment' 'uuid' 'metadata_path' 'engine_full' 'partition_key' 'lifetime_bytes' 'name' 'data_paths' 'metadata_modification_time' 'dependencies_database' 'is_temporary' 'storage_policy' 'create_table_query' 'dependencies_table' 'primary_key' 'sampling_key' 'total_bytes', maybe you meant:  (version 21.1.2.15 (official build))
```

![1658733089](https://user-images.githubusercontent.com/13527447/180721123-be350744-6ccc-409a-be5c-2e89b98c46dd.jpg)

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @zkelo

**Comment by Marcdsv** [comment]
Don't know if it's related but I have the same issue and also some queries are running indefinitely. I rolled back to 22.1.2 version and it works fine.

**Comment by LonwoLonwo** [comment]
Hello @Marcdsv

What Clickhouse database version do you use?

**Comment by Marcdsv** [comment]
@LonwoLonwo 
Version 21.3.13.9

**Comment by goranc** [comment]
Why you don't have latest two versions supported to upgrade/downgrade ?

This is very bad practice because we have to manually install previous version of the software in case that something isn't working in new version which is critical, like it was the case here.

**Comment by Raygeku** [comment]
I have same issue. So, only available solution is rollback?

**Comment by LonwoLonwo** [comment]
Hello everyone.

We have Early Acces DBeaver 22.1.4 version: https://dbeaver.io/files/ea/
It can be raw in some places because it's not tested for now, but this bug is fixed in this version.

**Comment by lswjkllc** [comment]
I have same issue with '20.6.3.28' version. Could you tell me how to reslove?

**Comment by LonwoLonwo** [comment]
Hello @lswjkllc 

Do you use the last version of DBeaver? 22.1.4?
If not - please, upgrade DBeaver.

**Comment by Raygeku** [comment]
> Hello everyone.
> 
> We have Early Acces DBeaver 22.1.4 version: https://dbeaver.io/files/ea/ It can be raw in some places because it's not tested for now, but this bug is fixed in this version.

For me and my teammate, it worked.

Thanks!
