### ISSUE TITLE
Incorrect button layout in the Tip of the Day window

### ISSUE THREAD

**Issue by troizet** [dbeaver/dbeaver#17173]
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04.4 LTS
- DBeaver version: 22.1.3.202207240747

#### Describe the problem you're observing:
![Снимок экрана от 2022-07-25 22-31-16](https://user-images.githubusercontent.com/9607501/180817893-9defc261-387c-4b80-9944-48fb2a4b3941.png)

**Comment by uslss** [comment]
Also reproducible on windows os
![image](https://user-images.githubusercontent.com/31996417/181505162-36946846-1671-4f39-91b0-23f217d27674.png)
