### ISSUE TITLE
Russian localization error

### ISSUE THREAD

**Issue by slistov** [dbeaver/dbeaver#17190]
**OS**
Ubuntu, .deb

**DBeaver version**
22.1.3.202207240747

**Problem description**
Russian localization error in "Tip of the day" window

Now
обл**Ы**чных
![image](https://user-images.githubusercontent.com/75843336/181468168-c7cee996-c065-4bb9-a728-0692a3d2a8b4.png)

Expecting
обл**А**чных

**Comment by LonwoLonwo** [comment]
Oops.
Thanks for the bug report @slistov
