### ISSUE TITLE
Single database connection mode?

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/dbeaver#17196]
**Is your feature request related to a problem? Please describe.**

When I use DBeaver to connect to `jdbc:ch://(https://explorer@play.clickhouse.com:443),(https://demo:demo@github.demo.trial.altinity.cloud)?load_balancing_policy=random`, it may show database/table structure from one server and issue query against the other. This is because each connection may pick a different server from the list.

![image](https://user-images.githubusercontent.com/4270380/181658722-93863f78-41d0-49d7-8d55-39a3ddf59f5a.png)

**Describe the solution you'd like**

1. Display connected server (use `java.sql.Connection.getURL()`) at status bar (on the bottom left corner in above screenshot)
2. Display connected server URL instead of defined connection string in mouse-over tooltip
3. Add an option to reuse single database connection

**Describe alternatives you've considered**

At least 1 & 2.

**Additional context**

Perhaps together with dbeaver/dbeaver#16545? Please use ClickHouse JDBC driver 0.3.2-patch11 or above for testing.

**Comment by emironovDB** [comment]
@zhicwu 
Hi! 
Thanks for the request!

**Comment by E1izabeth** [comment]
@zhicwu we have settings to specify whether DBeaver should use one or several connections for metadata read and sql editor https://github.com/dbeaver/dbeaver/wiki/Separate-Connections
Could you try using them? Does it fulfill your needs?

**Comment by zhicwu** [comment]
Thank you @E1izabeth! Just upgraded to version 22.3.0.202212041619, and it works well when the option is `Never`.
