### ISSUE TITLE
更新到22.1.3.202207240747版本后，不再支持多屏自动缩放。

### ISSUE THREAD

**Issue by xm0827** [dbeaver/dbeaver#17197]
这次升级开了倒车。 我之前的版本支持多个屏幕直接拖放后自动缩放的。更新到这个版本后不再支持这种缩放了。这个是要抛弃多屏用户的使用了吗？

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by LonwoLonwo** [comment]
Hello @xm0827 

Please translate your ticket into English.

Also, some screens or videos of the issue will be beneficial.

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If the issue is still actual for you, feel free to reopen it.
