### ISSUE TITLE
SAP hana database schema case sensitive issue

### ISSUE THREAD

**Issue by tonysmz** [dbeaver/dbeaver#17198]
#### System information: 
- Operating system (distribution) and version
  Windows 11
- DBeaver version
  22.1.3
- Additional extensions

#### Connection specification:
- Database name and version
  SAP HANA EXPRESS 2.0
- Driver name
  default sap hana jdbc driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
  no

#### Describe the problem you're observing:
  when connect SAP hana, there are two schemas, one is name "MES" (uppercase), another one is "mes" (lowercase), no matter which one I select, the "mes"( lowercase one) always be selected, and I try to hide the "mes", both are hide. so I have no way to  selected the uppercase one.

![image](https://user-images.githubusercontent.com/17421578/181717095-908febc1-ea18-4196-b83a-e6ebd97da792.png)

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @tonysmz 

I can reproduce your issue.

**Comment by LonwoLonwo** [comment]
Not best, but some small workaround: you can set default schema in the database navigator tree:

![tbYsUEOIF5](https://user-images.githubusercontent.com/45152336/181777559-55f0af5c-45a6-487a-9a40-313fe1c568f9.gif)

**Comment by tonysmz** [comment]
Hi LonwoLonwo, 

Thanks for your reply, according to your instructions, it is indeed possible to use the uppercase schema as the default schema. In fact, I have tried to switch the default schema in the navigator before, but I found that the schema in the top pancel has not changed, so I did not make further tests

Tony

**Comment by tonysmz** [comment]
and I think this issue is not only relate to sap hana only but all kind of databases (though I didn't tested the other database), hope it can be fixed soon, thank you for the great work of  you and your team
