### ISSUE TITLE
Updating while the table is sorted corrupts data

### ISSUE THREAD

**Issue by Lancer11211** [dbeaver/dbeaver#17192]
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04
- DBeaver version 22.1.3 CE
- Additional extensions N/A

#### Connection specification:
- Database name and version H2DB
- Driver name JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

While the table is sorted, updating cells can corrupt the table:

I ordered by the first column and corrected the shop references(no keys) after the previous corruption and this is what I got:
https://ibb.co/KqsVB4D

But if I use a select from the console then I get this:
https://ibb.co/chP4kQt

Note that when I got all the rows with "shop2" the data in the first view has been saved and no error got thrown!

It just simply inserted "shop2" in every row. When I first loaded the data from a csv, sorted by the middle column and updated the last columns then it renamed all references of "shop2" to "shop1".

#### Steps to reproduce, if exist:

Have a simple table with 3 columns. Sort it and updating multiple cells at a time will corrupt the table sooner or later.

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
![dbeaver_6CHCWU3EUs](https://user-images.githubusercontent.com/31996417/182363018-bf4517c7-c69c-44f0-89b4-d260adf4892d.gif)
