### ISSUE TITLE
Improved "Plan" results window

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#17209]
Currently, there are many cases of comparing "PLAN" for sql tuning, so I hope that some improvements will be made in the PLAN execution result window.

1. Add a function to select all in the Oracle PLAN execution result window (ex : ctrl+a)
  ![image](https://user-images.githubusercontent.com/59002295/182050690-056eb297-2c6a-4e22-aba9-ccd1d9e45821.png)

3. When advanced copy is executed, I want the "Operation" item to be indented as shown.
   Or, I would like depth to be displayed.
 ![image](https://user-images.githubusercontent.com/59002295/182050703-5f6bdac8-4047-4b55-9eec-45076ea753c1.png)

Thank you for reading. :)

**Comment by LonwoLonwo** [comment]
Hello @podoni 

Please provide me with more info.

1. Is there any specific reason not to use Shift instead of Ctrl+A?
2. Do you suggest using tab symbols for nested operations?

**Comment by podoni** [comment]
> Hello @podoni
> 
> Please provide me with more info.
> 
> 1. Is there any specific reason not to use Shift instead of Ctrl+A?
> 2. Do you suggest using tab symbols for nested operations?

Hello @LonwoLonwo 
1. I made a request because it was inconvenient to scroll and select an area because there were a lot of content in the SQL plan I wrote.
    If you have trouble with development, you can ignore it.
2. It's good to use tabs for nested tasks, but it's inconvenient to see because it's not currently indented.
   The contents of the PLAN are made into an Excel file and analyzed.
![image](https://user-images.githubusercontent.com/59002295/182744386-5f69441a-324b-4f87-a99d-1900b15aa9de.png)

   If you have trouble with development, you can ignore it.

Thank you for reading. :)

**Comment by LonwoLonwo** [comment]
OK, thanks for the answer.
