### ISSUE TITLE
The production version (release-22.1.2) failed to build

### ISSUE THREAD

**Issue by jiangyutu** [dbeaver/dbeaver#17203]
After inspection found that depend on the package version of ```https://dbeaver.io/eclipse-repo/``` has changed, now I want to build the warehouse at the local, where I need to find the dependencies
<br>
![image](https://user-images.githubusercontent.com/101239834/181814558-08e5a50d-860a-4567-82e0-9d304f0f36ce.png)

**Comment by emironovDB** [comment]
@jiangyutu 
Hi! 
Could you explain what issue did you try to resolve?

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it.
