### ISSUE TITLE
Right click menu and all the system bar menus are invisible

### ISSUE THREAD

**Issue by oguzyildizz** [dbeaver/dbeaver#17204]
#### System information: 
- Operating system (distribution) and version: 13 ventura (beta)
- DBeaver version: 22.1.3
- Additional extensions: None

#### Connection specification:
- Database name and version: Postgres
- Driver name: Default one it made me download

#### Describe the problem you're observing:
Right click menus and all the system bar menus are invisible (they're still clickable but I don't know what I'm clicking until it opens a dialog of the invisible button I clicked)

#### Steps to reproduce, if exist:
It just happened in the middle of the session. I restarted my mac, reinstalled, deleted everything in in the Library/DBeaverData, still happening with fresh install.

#### Include any warning/errors/backtraces from the logs
logs from fresh install:
```
   2   │ 2022-07-29 14:19:25.951 - OS: Mac OS X 13.0 (aarch64)
   3   │ 2022-07-29 14:19:25.951 - Java version: 17 by Eclipse Adoptium (64bit)
   4   │ 2022-07-29 14:19:25.951 - Install path: '/Applications/DBeaver.app/Contents/Eclipse'
   5   │ 2022-07-29 14:19:25.951 - Instance path: 'file:/Users/oguzyildiz/Library/DBeaverData/workspace6/'
   6   │ 2022-07-29 14:19:25.952 - Memory available 64Mb/1024Mb
   7   │ 2022-07-29 14:19:25.963 - Initializing DBeaver 22.1.3
   8   │ 2022-07-29 14:19:25.963 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 22.1.3.202207240747
   9   │ 2022-07-29 14:19:25.963 - Initialize Core...
  10   │ 2022-07-29 14:19:26.019 - BounceCastle bundle found. Use JCE provider BC
  11   │ > Start Core File Systems [org.eclipse.core.filesystem 1.9.400.v20220419-0658]
  12   │ > Start Core Resource Management [org.eclipse.core.resources 3.17.0.v20220517-0751]
  13   │ > Start Team Support Core [org.eclipse.team.core 3.9.400.v20220511-1440]
  14   │ 2022-07-29 14:19:26.106 - Initialize base platform...
  15   │ > Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.86.202207240747]
  16   │ > Start Expression Language [org.eclipse.core.expressions 3.8.100.v20210910-0640]
  17   │ 2022-07-29 14:19:26.120 - Core initialized (157ms)
  18   │ 2022-07-29 14:19:26.120 - Create display
  19   │ > Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.86.202207240747]
  20   │ 2022-07-29 14:19:26.220 - Starting RMI server at 51604
  21   │ 2022-07-29 14:19:26.244 - Run workbench
  22   │ > Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.500.v20220506-1520]
  23   │ > Start Eclipse Application Services [org.eclipse.e4.core.services 2.3.200.v20220513-1235]
```

**Comment by LonwoLonwo** [comment]
Hello @oguzyildiz1991 

Can you please provide a video of the issue?

**Comment by oguzyildizz** [comment]
I'm right clicking in this video, and also clicking the buttons on top https://drive.google.com/file/d/1zDLw1rKiPYmVHPjD4DTkOlSPfj93k7tM/view?usp=sharing

**Comment by LonwoLonwo** [comment]
Yes, I see now, thanks.

DBeaver is based on the Eclipse platform, and this is the Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=580322

It seems to be fixed already, but this fix will be available in our product only in Autumn with the new Eclipse release.

**Comment by oguzyildizz** [comment]
Thanks for looking into it!

**Comment by oguzyildizz** [comment]
Downgrading it worked (also had to do [this](https://github.com/dbeaver/dbeaver/issues/1218#issuecomment-277714288) )

**Comment by jacobator** [comment]
Works again with latest Ventura beta

**Comment by E1izabeth** [comment]
Thank you for informing us that the bug has gone.

**Comment by flambchap** [comment]
Trying 22.2.4 devel on macOS 13.0, the bug seems to be fixed
