### ISSUE TITLE
Filter Objects of Owner while connected with another user

### ISSUE THREAD

**Issue by Character799** [dbeaver/dbeaver#17213]
Hello,

While I know that when connected with the owner of the schema, I can filter the tables I want , it seems it is not possible when connected with, for example, a select user.
Please consider the following scenario:
USER1 connects to (and has only select rights to these schemas)
1)SCHEMA1_OWNER
     Tables
          A
          B
          C
2)SCHEMA2_OWNER
      Tables
          D
          E
          F

Would be nice if I can filter the tables I want in each of the schemas - for example INCLUDE only Table A for Schema 1 and Table D for schema 2.

Please note that the above example is from Oracle Exadata Connection.

Thanks!

**Comment by Matvey16** [comment]
Can you pleasy specify how do you filter tables in the schema?

There is already a way to filter tables in a certain schema, did you try that?

![dbeaver_zKIU6ESKh4](https://user-images.githubusercontent.com/82543000/185351772-8308232b-a385-4e4e-9fa3-c804f9df6038.gif)

**Comment by Character799** [comment]
I used the **Filter** Option from the **User Connection - General Connection Settings**.
But what you showed is exactly what I was looking for .
Thanks!
![Filter](https://user-images.githubusercontent.com/110384758/185581808-b74f5057-51e5-47f7-a5e8-265cde8fc1d2.jpg)

**Comment by Character799** [comment]
Functionality already exists
