### ISSUE TITLE
Dark theme - XML preview not visible

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#17219]
In the dark mode (default) XML preview is completely not readable 
(Screenshot looks in fact better then in real :)

In general dark black / blue on dark grey background are hard to read.
Would be good to have this corrected

![obraz](https://user-images.githubusercontent.com/5410448/182096174-1f806f21-e9e6-429d-a86e-5842dbbe0fdb.png)

**Comment by LonwoLonwo** [comment]
Hello @maciey 

Yes, I can reproduce it. Value panel is fine for JSON format, for String, but not for XML.

**Comment by tinman2501** [comment]
I think a similar error makes the filter panel font/background color combination quite hard to read in dark mode. The font is always black, no matter what.
