### ISSUE TITLE
Error while connecting to Mysql Database

### ISSUE THREAD

**Issue by MrDevCop** [dbeaver/dbeaver#17224]
### Description

Hi everyone!
This is my first time posting an issue on Github so kindly bear with me if I make any mistakes while explaining my issue.
A little background: I have just got a new laptop for my workplace on which i am trying to install and use dbeaver to connect to our MySQL database hosted on AWS. In my old machine I could easily set up a connection to my database without any hassle but since i got a new machine whenever I try to connect to the database an error is thrown. I have tried looking up the remedies online but to no avail. 
The snapshot of the image is given below:
<img width="884" alt="image" src="https://user-images.githubusercontent.com/41063773/182208708-8222d5b6-5a2b-41ba-a54a-f0dd369eb5e6.png">

I put in the correct credentials for the connection and the correct .ppk file for the SSL tunnel as well. The configuration for SSL tunnel works okay but when i try to test the connection to the database it throws the above error.

My new machine is Hp Omen 16 with windows 11.

### DBeaver Version

Community edition 22.1.3

### Operating System

Windows 11

**Comment by LonwoLonwo** [comment]
Could you please share the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by LonwoLonwo** [comment]
Also, a screen of the connection page will be beneficial.
I googled this issue, and it can be bundled with a user name, for example.

**Comment by LonwoLonwo** [comment]
Or maybe this advice can help you: https://github.com/dbeaver/dbeaver/issues/3213#issuecomment-376276865

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If the issue is still actual for you, feel free to reopen it.
