### ISSUE TITLE
SQL Error OpenEdge JDBC (10713)

### ISSUE THREAD

**Issue by SimonDataAnalist** [dbeaver/dbeaver#17232]
### Description

When I run a query via the OpenEdge driver that starts with information about the query, so it starts with /*<here is information about the script>*/ then I get a sql error:
SQL Error [HY000]: [DataDirect][OpenEdge JDBC Driver][OpenEdge] Syntax error in SQL statement at or about "...” (10713)

When I start the same query without starting with /*<here is information about the script>*/ Then I don't get this error message, and I just get the output of the query.

If I do the same but then via an ODBC connection (via the ODBC-JDBC Bridge driver) it works just fine and I also get output of the query, even when the qeury starts with the information data.

Maybe this has to do with a setting that is wrong. But what setting should I adjust to make it work. Or is it really a bug.

### Steps to reproduce

1. Run a query starting with /****** some tekst */
2. Run a query without /**** some tekst */ at the begining
3. Run a query via de ODBC driver starting with /****** some tekst */

### DBeaver Version

Community edition 22.1.3

### Operating System

Windows 10

**Comment by LonwoLonwo** [comment]
Hello @Simon-Zuidwester 
Can you provide a screen from SQL Editor, please?
Are these symbols "//" means comment in OpenEdge dialect? If yes, did you try to use the standard "#" symbol?

**Comment by SimonDataAnalist** [comment]
![Script](https://user-images.githubusercontent.com/110468118/182787527-e79dbbdf-6b7a-4195-820f-a3f4298577a4.png)

When I remove the comment text:
/********************************************************************************
* Dit script haalt alle clienten op met een actief geregistreerd product.            
* Versie     : 1.0                                                                                               
* Datum            : 03-02-2020                                                                                  
* Auteur     : Simon ter Beek                                                                                    
********************************************************************************/
Then the query will run without an error.

I have try it with the # before but then i also get the error

If the query containts /* and */ (for comment text) then the query will run just fine. It only fails if the query starts with /* */

**Comment by SimonDataAnalist** [comment]
It seems that the issue has been resolved with the installation of version 22.1.4

**Comment by SimonDataAnalist** [comment]
Hello,

Here is a screenshot from a script:
***@***.***
When I remove the comment text:
/********************************************************************************
* Dit script haalt alle clienten op met een actief geregisteerd product.
* Versie     : 1.0
* Datum            : 03-02-2020
* Auteur     : Simon ter Beek
********************************************************************************/
Then the query will run without an error.

I have try it with the # before but then i also get the error
