### ISSUE TITLE
SSMS Login Failed.

### ISSUE THREAD

**Issue by zsm369** [dbeaver/dbeaver#17238]
### Description

![image](https://user-images.githubusercontent.com/32601074/182451622-b142fa97-7859-4440-838c-94a3f01733b3.png)

### DBeaver Version

22.1.3

**Comment by LonwoLonwo** [comment]
Hello @zsm369 

What database do you use?
What connection type did you use?
Why do you think this is a DBeaver issue and not an incorrect login/password?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If the issue is still actual for you, feel free to reopen it.
