### ISSUE TITLE
InterSystems IRIS JDBC Driver Link Outdated

### ISSUE THREAD

**Issue by ipcooper** [dbeaver/dbeaver#17234]
### Description

When establishing your first connection to InterSystems IRIS, DBeaver will prompt you to download the appropriate JDBC driver from the official InterSystems github repository using a link which is now out of date and nonfunctional (https://https://github.com/intersystems-community/iris-driver-distribution/raw/main/intersystems-jdbc-3.1.0.jar).

The suggested location to get the latest JDBC driver is now here (https://intersystems-community.github.io/iris-driver-distribution/). This page will continue to be updated with the latest version. The current version of the driver can also be found here (https://github.com/intersystems-community/iris-driver-distribution/blob/main/JDBC/JDK18/intersystems-jdbc-3.3.1.jar) and this link will be updated with new versions as they come (3.3.1 being the current version).

Additionally, while investigating this I found another link under connection-settings>driver-properties>driver-documentation that directs to a 404 page - I believe the correct hyperlink would be this (https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=BJAVA_connecting).

### Steps to reproduce

1. Establish a first connection to InterSystems IRIS (there should only be the link to download the JDBC driver under Connection-Settings>Main>Edit-Driver-Settings>Libraries)
2. Test Connection and receive a prompt to download the JDBC driver from the default link
3. Attempt to download the driver from the popup
4. Get a URL not found error for https://https//github.com/intersystems-community/iris-driver-distribution/raw/main/intersystems-jdbc-3.1.0.jar

### DBeaver Version

Community Edition 22.1.3

**Comment by LonwoLonwo** [comment]
Hello @ipcooper 
Thanks for the report.
We use JDK11 in DBeaver, maybe https://github.com/intersystems-community/iris-driver-distribution/blob/main/JDBC/JDK11/intersystems-jdbc-3.2.0.jar will be better?

**Comment by ipcooper** [comment]
> Hello @ipcooper Thanks for the report. We use JDK11 in DBeaver, maybe https://github.com/intersystems-community/iris-driver-distribution/blob/main/JDBC/JDK11/intersystems-jdbc-3.2.0.jar will be better?

I've been able to successfully use both the driver you linked and the one I linked in the JDK18 folder - if you think the JDK11/3.20 is better then I personally don't see a reason not to use it instead.

**Comment by LonwoLonwo** [comment]
Thanks for the answer and investigation @ipcooper

**Comment by bdeboe** [comment]
@evshvarov : can we post the driver using a generic -latest suffix rather than tie the URL to a specific version?

**Comment by daimor** [comment]
> @evshvarov : can we post the driver using a generic -latest suffix rather than tie the URL to a specific version?

[Expected](https://github.com/dbeaver/dbeaver/pull/10093#issuecomment-718432231) that InterSystems will finally start using Maven for publishing drivers

**Comment by daimor** [comment]
> @evshvarov : can we post the driver using a generic -latest suffix rather than tie the URL to a specific version?

InterSystems, has control over that Repository, and always deletes all previous versions. So, it's InterSystems's decision to add `latest` tag, not community.

[acoppola](https://github.com/intersystems-community/iris-driver-distribution/commit/cbec4c1f4b8b950eed0352b26828efd602c545ff) controls, which drivers available and how it accessible.

**Comment by arhayka** [comment]
Completed in https://github.com/dbeaver/dbeaver/pull/18916
