### ISSUE TITLE
Snowflake: DESCRIBE TABLE not working

### ISSUE THREAD

**Issue by JoMrx** [dbeaver/dbeaver#17241]
### Description

In DBeaver, the DESCRIBE TABLE command does not work with Snowflake. 

### Steps to reproduce

1. Use Snowflake browser GUI or Snowsight:
2. exec DESCRIBE TABLE tablename 
3. result: works fine.
4. Use DBEAVER
5. connect to Snowflake database
6. exec DESCRIBE TABLE tablename 
7. result: 

SQL Error [1003] [42000]: SQL compilation error:
syntax error line 7 at position 9 unexpected 'table'.

### DBeaver Version

Community Edition v22.1.1

### Operating System

Windows 10 Enterprise 21H2 64-Bit0

**Comment by LonwoLonwo** [comment]
Hello @JoMrx 

Unfortunately, I can't reproduce it.

![2022-08-03 09_26_25-DBeaver Enterprise 22 1 3 - _SNOWFLAKE_SAMPLE_DATA_ Script-38](https://user-images.githubusercontent.com/45152336/182539053-d9e197fc-bdd6-410f-b1f4-d48db58d769a.png)

Can you please provide a screen from your SQL Editor? And your database and driver versions (you can check it in the Connection Settings -> Test Connection). Thanks.

**Comment by JoMrx** [comment]
![image](https://user-images.githubusercontent.com/99005935/182543228-c4efeca9-96e9-4ad6-bc55-1c3da237be62.png)
Sorry, was my error. Previous command wasn't terminated while not visible in the window.

**Comment by LonwoLonwo** [comment]
I'm glad that this is ok now.
