### ISSUE TITLE
Auto complete only offers one of two table aliases

### ISSUE THREAD

**Issue by mrclmh** [dbeaver/dbeaver#17246]
### Description

I have to work with especially long table names for some queries. (DB is PostgreSQL 11)
The table aliases are generated by DBeaver and for this expample below, DBeaver only offers `sadpoootbapt` for autocomplete when typing `sad`. `sadpoootbtwt` is missing.

```sql
select *
from hub_aggr_daily_production_order_operation_occupied_time hadpooot
join sat_aggr_daily_prod_order_op_occupied_time_by_adj_prod_time sadpoootbapt
  on hadpooot.id = sadpoootbapt.dpooot
join sat_aggr_daily_prod_order_op_occupied_time_by_total_work_time sadpoootbtwt
  on hadpooot.id =   <auto complete only offers `sadpoootbapt` here>
```

### DBeaver Version

Community Edition Version 22.1.3.202207240747

### Operating System

macOs 10.15.7

**Comment by mrclmh** [comment]
I just noticed that the behavior does not seem to depend on the length of the tables aliases, but on whether they share a common prefix.
In another case with the talbe aliases `spoo` and `spoos`, auto complete does not offer`spoos`.

**Comment by E1izabeth** [comment]
Thank you for bug report.
