### ISSUE TITLE
Datatable export doesn't create varchar(MAX) but varchar(1) instead

### ISSUE THREAD

**Issue by CommandLineConqueror** [dbeaver/dbeaver#17244]
### Description

in Export Data -> Database
When selecting [configure] you can see that it correctly determined column should be _varchar(MAX)_ due to the large string. But it creates _varchar(1)_ instead and causes errors due to truncation of the string during export.

Before I updated DBeaver to see if perhaps it's fixed already there was an option to preview DLL (option now gone), and you could see that the table creation script said 'columnName varchar NULL', instead of 'columnName varchar(MAX) NULL' only for MAX. varchar columns of size that were a number are correct, like 'columnName varchar(255) NULL'. 

![image](https://user-images.githubusercontent.com/35919367/182583852-7a307cb6-1827-458a-89cb-620944239779.png)

Note that the longest string is not actually that long (16777216), it shows that number for any column that contains a long string. 

### Steps to reproduce

As a source, use a datatable that has a column containing a very long string, longer than 255. Try to export it to a different schema where it will have to be created by DBeaver. 

### DBeaver Version

22.1.3

### Operating System

Windows 10

**Comment by LonwoLonwo** [comment]
Hello @swagozaurus 

What database do you use?

**Comment by CommandLineConqueror** [comment]
> Hello @swagozaurus
> 
> What database do you use?

I was using access database (.accdb) as a source, moving data to ms sql server

**Comment by uslss** [comment]
thanks for the report
