### ISSUE TITLE
Console icon in SQL Editor stays enabled in SQ

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#17245]
### Description

Console icon in SQL Editor shows that it is still enabled if the tab is closed manually

### Steps to reproduce

1. Enable console output in SQL Editor
2. Close the console tab

**Expected:** Console button is toggled off
**Actual:** Console button is still on

![dbeaver_3xqUtP70Mc](https://user-images.githubusercontent.com/82543000/182590765-e8acee35-95a4-4cc0-8398-b9af991a822c.gif)

### DBeaver Version

22.1.4

### Operating System

Win 11

**Comment by E1izabeth** [comment]
It's not a bug. Enabled state means that output on query execution will go to console view and console view tab will be opened. In other words, console view button state shows whether this feature is enabled, it's not about the tab opened/closed state.
