### ISSUE TITLE
English connection name and table name can't change font size,

### ISSUE THREAD

**Issue by Maxx-Yang** [dbeaver/dbeaver#17253]
### Description

I found thant the table name in the  Database Navigator is so smalll and I can't change the font size. But the chinese followed the table name can change size. so I want know why this take place.

### DBeaver Version

22.1.3

**Comment by Maxx-Yang** [comment]
like the below image display,chinese can change the font size 
![image](https://user-images.githubusercontent.com/32293803/182744332-e54d4482-2ad1-4a71-abef-29a3e00b5092.png)

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
It may be related with #12975

**Comment by flambchap** [comment]
~Duplicate of https://github.com/dbeaver/dbeaver/issues/12975.~

**Comment by E1izabeth** [comment]
Fixed in scope of #12975
Can be changed in `Tree and table font for views`
![image](https://user-images.githubusercontent.com/28875055/213937047-329fb326-7285-4be9-9560-4677e39f88e7.png)
