### ISSUE TITLE
problem connecting on (mariadb) SkySQL instance

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#17251]
### Description

I recently started using SkySQL for their $500 credit for new account signups, So after ordering one of their systems I connected to the server with MySQL workbench which worked perfectly fine, even though it did bring up a warning about an unknown DB version which SkySQL claims the warning is not to be worried of.

So after connecting with MySQL workbench I come across some odd crashes when trying to create databases and tables with specific row values so I move over to DBeaver.

Now using the same method of connection with the same values brings me:
`(conn=6003) Access denied for user '**********'@'***.***.***.***' (using password: YES)`

Also during the first 3 or so attempts to connect I had found another error which related to the password input charset being windows instead of what I imagine was meant to be the server charset - however this error seemingly disappeared after editing the `passwordCharacterEncoding` variable.

After looking at similar issues (only 1 with similar conditions) I also should mention the password contains alphanumeric characters, symbols including brackets, asterisks and other

currently on a VPN and authorized by SkySQL access list.

notes:
The only thing I can imagine which is causing this error is the connector, or the copying and pasting between the SkySQL logins and the password input box (but i have put them into notepad and then copied only the text component, no spaces or tabs prepending...)
SkySQL also gives a different port (5001) however I don't think that is any part to the issue.

### Steps to reproduce

probably local to just skysql so
1. connect to skysql instance through mysql workbench,
2. do the same but on DBeaver

### DBeaver Version

DBeaver Community 22.1.3

### Operating System

Windows10 - 21H2 / 19044.1826

**Comment by ghost** [comment]
additional: just created a report at MariaDB SkySQL portal querying if they can hand over the connection logs which involve both MySQL workbench and DBeaver...

edit: MariaDB came to the rescue - phew
incidentally was me reading the wrong setup guide and getting the ssl cert mixed up.

Any future lookers: [https://mariadb.com/products/skysql/docs/connect/clients/dbeaver/#connect](setup guide)

**Comment by LonwoLonwo** [comment]
Thanks for the investigation @Jakemcandrew
