### ISSUE TITLE
In the export protocol, the number of records is shown as doubled.

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [dbeaver/dbeaver#17260]
### Description

In the export protocol, the number of records is shown as doubled.
I.e. real records = 6.213.312, but show as 12.426.624 (=6.213.312 * 2)
<img width="344" alt="ss_2022_08_04__11_27_24" src="https://user-images.githubusercontent.com/25248634/182791995-71bdaf76-61d5-48e3-9910-179c06867de2.png">

### DBeaver Version

22.1.3 CE

### Operating System

Win 10

**Comment by LonwoLonwo** [comment]
Yes, I can reproduce.
Thanks for the bug report @aleksandr-shevchenko

**Comment by LonwoLonwo** [comment]
DBCStatistics#addRowsFetched
