### ISSUE TITLE
When the table name is Chinese, the code cannot be completed

### ISSUE THREAD

**Issue by win768** [dbeaver/dbeaver#17262]
### Description

When the table name is Chinese, the code cannot be completed

Video presentation address
https://wwu.lanzout.com/iJIY608zw6eb

### Steps to reproduce

When the table name is Chinese, the code cannot be completed
Video presentation address
https://wwu.lanzout.com/iJIY608zw6eb

### DBeaver Version

22.1.3

**Comment by E1izabeth** [comment]
Thank you for bug report

**Comment by LonwoLonwo** [comment]
![2022-12-26 13_11_33-](https://user-images.githubusercontent.com/45152336/209537602-539c7cb5-d390-450b-bd2c-276f1c30f631.png)

![2022-12-26 13_12_16-](https://user-images.githubusercontent.com/45152336/209537608-8a62f497-bee0-4d50-b529-aee7528a4b78.png)

Can't reproduce against in DBeaver 22.3.1

Can you please check the latest DBeaver version? https://dbeaver.io/download/

**Comment by Matvey16** [comment]
Reproduced on Oracle 12

**Comment by E1izabeth** [comment]
There is no update on this issue for a long time, so I'm closing it. Please let me know if the issue is still actual for you for the latest DBeaver version.
