### ISSUE TITLE
Grouping panel is cleared when switching between panels

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#17270]
### Description

Grouping panel is cleared when switching between panels

https://user-images.githubusercontent.com/43252954/183053880-f01aea17-6404-4ecc-8c75-96d342d2dd7f.mp4

Workaround:
Before switching to another panel or closing the grouping, refresh the table and grouping will be save

### DBeaver Version

22.1.4

### Operating System

win11

### Steps to reproduce

1. Open some table
2. Open grouping panel
3. Drag-n-drop some columns to the panel
4. switch to another panel and backward

As the result the grouping panel would be cleared

**Comment by Matvey16** [comment]
Verified
