### ISSUE TITLE
Sqlite DB is locked (only in DBeaver)

### ISSUE THREAD

**Issue by NiklasRz** [dbeaver/dbeaver#17274]
### Description

I consistently get "[SQLITE_BUSY] The database file is locked (database is locked)" on my SQLite DB in DBeaver. This is only in DBeaver. I can connect, read and write without any problems in Python. This persists through reconnects and reboots.

I tried duplicating the DB and connecting to the copy instead, but I get the same error. 

### DBeaver Version

CE 22.1.3

### Operating System

Ubuntu 20.04

### Database and driver

SQLite JDBC driver 3.39.2.0

### Steps to reproduce

1. I connect to my database
2. I click on my database in the Database Navigator
3. I click on Tables in the Database Navigator
4. alternatively: I try to run any query on my DB
5. I get an error "[SQLITE_BUSY] The database file is locked (database is locked)"

**Comment by Destrolaric** [comment]
Hi, is your SQLite on the Shared folder/WSL?

**Comment by NiklasRz** [comment]
Hi, are you asking where I have the .db file? The file is in my home directory. Just realized that I have another sqlite database there that I can connect to without problems. 
I noticed that in the connection settings for the one that is working I have something like "Path: /home/myuser/mydb.db"
On the one that isn't working I have: "Path: /run/user/1000/doc/2f03b66c/mydb.db"

**Comment by Destrolaric** [comment]
As I remember /run/user/1000 is files created by running programs, so they are probably being used by another program.

**Comment by NiklasRz** [comment]
I still get run/user/1000 after rebooting or duplicating the database file which I assume should get rid of all references to the file by other programs?
Is it possible that the file itself is kind of marked as "busy" which persists through reboot/copy?

**Comment by Destrolaric** [comment]
You can try the solution discussed in https://github.com/dbeaver/dbeaver/issues/17217, write me if it helps.

**Comment by NiklasRz** [comment]
Previously I was unable to edit the "Path" field after choosing the "edit connection" option. I don't know why, but when I tried right now, I was able to edit that field. When I manually changed the path from "run/user/...." to "/home/myuser/.../dbfile.db" it worked and I was able to access the db without getting the error.

**Comment by george-hopkins** [comment]
I was able to access my database after granting DBeaver access to removable media:
```bash
sudo snap connect dbeaver-ce:removable-media :removable-media
```

**Comment by flambchap** [comment]
@NiklasRz Do I understand correctly that the issue is gone for you?

**Comment by NiklasRz** [comment]
@n5a5 the issue is still there but manually replacing the path is a workaround that solves it. Might still be an issue for others users though that are unaware of the workaround

**Comment by Destrolaric** [comment]
Hi, I have a question `run/user` is the filesystem used by running processes. And it shouldn't have any files that are not part of any process. Does SQLite is created by some other process?

**Comment by LonwoLonwo** [comment]
There have been no updates for a long. If the issue is still actual for you - feel free to reopen it with additional info.

**Comment by rayx** [comment]
@Destrolaric @NiklasRz Just FYI. It was a snap configuration issue. See discussion [here](https://stackoverflow.com/questions/71871614/cant-access-db-tables-from-dbeaver-sqllite-busy-database-file-is-locked-dat). I ran into the same issue today and solved it using the solution in that discussion. However, I have no idea how @NiklasRz could fix it by modifying the path manually. If it's a snap configuration issue, it should be impossible, I think.
