### ISSUE TITLE
Unable to Edit Connection v22.1.3

### ISSUE THREAD

**Issue by DBNoobie** [dbeaver/dbeaver#17279]
### Description

After upgrading from 22.0.0, I am unable to edit any existing connections. Selecting Edit Connection from the context menu (or using F4) does nothing.

There have been no changes to file permissions on the DBeaver directory (presently set at Full Control)

### DBeaver Version

Community Edition 22.1.3

### Operating System

Windows 10 21H2

### Database and driver

Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 using Oracle JDBC driver v12.2.0.1.0

### Steps to reproduce

Highlight the desired connection, right-click and select Edit Connection - nothing happens.

**Comment by LonwoLonwo** [comment]
Could you please send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by carlosedsferreira** [comment]
It happens the same to me.

I can see the following error:
```/usr/share/dbeaver-ce/jre/bin/java: symbol lookup error: /home/<my_user>/.eclipse/org.jkiss.dbeaver.product_22.1.4_302967072_linux_gtk_x86_64/configuration/org.eclipse.osgi/141/0/.cp/libswt-pi3-gtk-4952r11.so: undefined symbol: gtk_menu_popup_at_pointer```

**Comment by DBNoobie** [comment]
Log files attached. Two attempts made to edit connection at 15:11:xx.

Thanks for your efforts.

**Comment by dbeaver-pm** [comment]
Please attach the log file here, on this GitHub page @DBNoobie 
It doesn't work with e-mail

**Comment by DBNoobie** [comment]
Files have been uploaded to Public Repository DBNoobie<https://github.com/DBNoobie> / DBeaverIssue17279<https://github.com/DBNoobie/DBeaverIssue17279>.

**Comment by E1izabeth** [comment]
Thank you.
May be connected with https://github.com/dbeaver/dbeaver/issues/17305

**Comment by E1izabeth** [comment]
The fix should be available in the future release. Please, let me know if the bug still exists.
