### ISSUE TITLE
Azure SQL Server MFA Authentication Causes Repeated Browser Windows (not yet fixed!)

### ISSUE THREAD

**Issue by Aileron79** [dbeaver/dbeaver#17288]
### Description

For most databases I authenticate using "Azure SQL Server MFA Authentication". Since version 22.1 a new browser tab opens every time I connect or reconnect to a database, this is also true for automatic reconnects after some idle time. The browser tab points to https://localhost:<someport> and only says "Authentication complete. You can close the browser and return to the application."

A similar issue was raised [here](https://github.com/dbeaver/dbeaver/issues/16873) before that was fixed in 22.1.3, but I still get tons of browser tabs. Running 22.1.4 now and the problem still persists.

Expected behavior: No browser tabs are created when connecting/reconnecting to a database.

I'd also be happy if there's some kind of keepalive for the connection that reduces the amount of reconnects.

### DBeaver Version

Community edition 22.1.4

### Operating System

Windows 10 x64

### Database and driver

Azure SQL / Azure SQL Server MFA Authentication

### Steps to reproduce

- Connect to Azure SQL Server using "Active Directory - MFA"
- A browser window will open that only says "Authentication complete. You can close the browser and return to the application."
- Leave the session idle for some time (until it disconnects, this usually is 15 minutes or so)
- Send a SQL query => automatic reconnect => another tab opens.
- ...

**Comment by E1izabeth** [comment]
Thank you for report.

**Comment by iraidaa** [comment]
The bug is reproduced with Snowflake in DBeaver EE

**Comment by E1izabeth** [comment]
Could you set `Keep-Alive` and `Close idle connections after` to some value? Let me know if this resolves your issue.

![image](https://user-images.githubusercontent.com/28875055/184836756-258b2f04-b0f1-4e46-abf7-685ec63dadab.png)

**Comment by E1izabeth** [comment]
@Aileron79, also please send the log files. You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/

**Comment by iraidaa** [comment]
Hello @Aileron79,

The issue is fixed in 22.2.0. Please, try the new version.

**Comment by dhorrall** [comment]
Can we re-open this?  This is still hapening over the past few versions.  I am on 23.1.4.202308061552.  I think if my sessions times out, I then try to re-connnect and then get numerous browser windows with message:  'Authentication complete. You can close the browser and return to the application.'

EDIT: Connecting to Azure SQL Server with Active Directory MFA

**Comment by Aileron79** [comment]
Yes, I agree, please re-open. I assume though that this issue is caused by the Azure SQL driver and not by dbeaver itself. However, I wonder it it would be possible to use a tiny browser inside dbeaver to handle these authentication requests. It is super annoying, I am connected to dozens of databases at the same time. Whenever my VPN connection fails, all of these connections are being re-established and open multiple browser windows. This means that even when I'm not working in dbeaver the moment the VPN connection is lost/re-established, the browser window appears in the foreground. Imagine working on some code in Visual Studio or on some Excel sheet and suddenly dozens of browser windows keep popping up. This happens multiple times a day and is incredible annoying. I have actually written a simple addon for chrome that auto-closes these windows, but still, the browser window pops up and interrupts my work. Also, the active browser window is being changed, which also is annoying. 

PLEASE find another way to handle Azure authentication!

**Comment by dhorrall** [comment]
I am glad I am not the only one.  I agree, this needs focus from the DBEAVER team.  I was actually looking for a DBEAVER replacement over the wekend it has become so annoying and disruptive...  And I love DBEAVER...Please don't push me away  :-) @E1izabeth

**Comment by E1izabeth** [comment]
Please create a new issue. This particular issue is abut the concrete case that was fixed and has nothing to do with what you're describing.

**Comment by E1izabeth** [comment]
I'll give a priority to the new issue when you create it.
Also you all can vote for the issue with 👍🏻 under the issue description.

**Comment by Aileron79** [comment]
@E1izabeth 
Thanks a lot! "This particular issue is abut the concrete case that was fixed and has nothing to do with what you're describing." => Not entirely true, I opened this very issue for the same reason. The fix slightly reduced the amount of reconnects, but basically it still is the same problem and it gets worse with an increasing number of databases you are connected to. However, I have opened a new issue here:
https://github.com/dbeaver/dbeaver/issues/20887

@dhorrall Feel free to add your own experience there :)

**Comment by E1izabeth** [comment]
Thanks

**Comment by ilrenzo** [comment]
Hi,
@E1izabeth why are all these issues about Az SQL Server connections opening multiple tabs being Closed? I see there are at least other two of them that were closed but I cannot find any fix.
https://github.com/dbeaver/dbeaver/issues/20887
https://github.com/dbeaver/dbeaver/issues/16873

I'm sure I'm not the only one becuase I know other developers that have the same behavior with different versions of Dbeaver. I'm personally running Version 24.1.4.202408041450.

I usually connect to 5/10 database at a time and every time I open DBeaver I need to wait like 5 minutes for it to open about 100+ tabs (no joking) and then close all of them. If I have Chrome open I have to be careful not to close the tabs I was working on.

Also, if by mistake I forget to connect to the VPN before I open DBeaver that becomes a nightmare because: dbeaver will keep trying to connect forever but it will fail because of the VPN; the VPN doesn't connect because it looks like DBeaver is consuming all the network; it's very hard to close Dbeaver because the focus continuously change to the last Chrome tab!

My understanding is this is related to how the MSFT driver works but if that's the case, why are all these issues being closed? Why don't wait for that fix MSFT fix? Is there a ticket opened to msft on that issue that we're waiting for? Could you please share the link?


Thanks!

**Comment by E1izabeth** [comment]
Hi, @ilrenzo 
As far as I see these issues was resolved. If you experience it again, please, create  a new issue. Most probably, it wasn't resolved for your concrete case.

**Comment by E1izabeth** [comment]
@ilrenzo also please update driver. You can do it this way
1. Open your `Connection setting` and press `Driver settings`
![image](https://github.com/user-attachments/assets/b3cfaf1a-dc05-4bae-856b-4d0206d0dbbe)
2. Go to `Libraries` tab. select the driver artifact and press `Download/Update` 
![image](https://github.com/user-attachments/assets/0f8d65c3-989d-4549-bee3-3409a49cb181)
3. Select newer driver version in the list and press `Download`
![image](https://github.com/user-attachments/assets/0ff3641b-5a0e-44fb-803d-3eab24fa956c)
4. Press OK to close `Driver settings` window and try connecting again
