### ISSUE TITLE
Advanced Paste Error 

### ISSUE THREAD

**Issue by google007049** [dbeaver/dbeaver#17284]
### DBeaver Version

community edition 22.1.4

### Operating System

windows 10

### Database and driver

ORACLE 11G

### Description

If you add Row after ADVANCED COPY in Grid and  Advanced paste, the Timestamp value is added to the column value of Date type as shown in the screen below.
Therefore, an error occurs when saving.

The format of Date is also set to yyyy-mm-dd. But
The column values in the Data Grid show the Timestamp format. The data type in the CREATE_DTIME column is Date.
Clear TIMESTAMP from GRID and save GRID to successfully save. I think there is an error because of TIMESTAMP when ADVANCED PASTE is attached.

**[Data Format]**
![image](https://user-images.githubusercontent.com/58673078/183369459-179d8da2-042a-4c23-b60c-3a8e180e3813.png)

**[Advanced copy popup]**
![image](https://user-images.githubusercontent.com/58673078/183326714-fb7e7fe7-9731-47d3-a688-7e015d76d40e.png)

![image](https://user-images.githubusercontent.com/58673078/183332710-2f958b8d-bb38-4b73-929a-d347558084e1.png)

![image](https://user-images.githubusercontent.com/58673078/183326510-d4e8a49f-33d3-4c1d-9f28-8d673302b0c7.png)

**Comment by google007049** [comment]
Thank you for your interest in my question.
We will upload a video of the action for this question.
Please check it again and thank you.

https://user-images.githubusercontent.com/58673078/184273536-32b05d43-7c7e-4173-90ba-86c7de58bab1.mp4

**Comment by LonwoLonwo** [comment]
Closed as duplicate: https://github.com/dbeaver/dbeaver/issues/17210
