### ISSUE TITLE
DBeaver's sql editor forces lower case on sql keywords

### ISSUE THREAD

**Issue by DoctorKrolic** [dbeaver/dbeaver#17282]
### Description

When applying sql keywords suggestions they appear to be in lower case, even though in completion windows they are shown in UPPER CASE. Typing sql keyword and hitting `space` also force-apply active completion, making the keyword in lower case:
![dbeaver_8yOsw6fG6n](https://user-images.githubusercontent.com/70431552/183296742-02256707-af18-4157-8484-ac71cee441a1.gif)
_First time I apply completion suggestion by pressing `enter`, second time I type the whole keyword and press `space`_

### DBeaver Version

Community Edition 22.1.3

### Operating System

Windows 11 21H2

### Database and driver

PostgreSQL 14.0
![dbeaver_Qx9o5F7Kfm](https://user-images.githubusercontent.com/70431552/183296596-cef29122-581d-4919-8f69-caf16eb46bbe.png)

### Steps to reproduce

1. Connect to PostgreSQL database (though I am pretty sure database type is not the source of a bug here)
2. Open up any DB in the GUI
3. Right click on any schema -> SQL editor -> Open SQL console
4. To reproduce the first part of a bug type `SELE` and press `enter` to apply active completion
5. To reproduce the second part of a bug type `SELECT` and press `space`

**Comment by LonwoLonwo** [comment]
Hello @DoctorKrolic 

You can change this behavior in Window -> Preferences -> Editors -> SQL Editor -> Code Completion
Please select "Upper case" for the "Insert case".

![2022-08-08 10_17_08-Window](https://user-images.githubusercontent.com/45152336/183361835-a6e41af9-f94b-445e-bde9-f124dfa82417.png)

**Comment by DoctorKrolic** [comment]
Yes, that helped. I yet have several questions/proposals then:
1) What is a `Default` value here? Why not just upper/lower case? IMO it would be better, if there were only 2 options available
2) Upper case should probably be a default value. There is a convention, that SQL keywords are in upper case, so dbeaver should consider that. However, if user prefer a lower case, he will be able to explicitly set this in the settings
3) Completions are always shown in upper case no matter what option is selected. This is a bug
4) In the issue I described, that typing an sql keyword and hitting `space` auto-corrects it to lower case when such option is selected. Well, that doesn't happen if my preference is set to upper case. If I now type `select` and press `space`, the keyword won't be changed to upper case `SELECT`. I am not sure, what behaviour is better in this case, but it at least should be consistent with different options selected.

**Comment by LonwoLonwo** [comment]
DBeaver - is a universal database tool. It means that DBeaver supports different databases.
Some databases work with lower case (like PostgreSQL), and others with upper case (like Oracle).
So, by choosing the "default" setting, you will know that you will get "select" in the PostgreSQL script and "SELECT" in the Oracle script.

> Completions are always shown in upper case no matter what option is selected.

Because DBeaver store the list of keywords in the upper case. I'm not sure we want to change all these words all the time. It can be expensive.

Please provide more info - maybe a video of the issue, from the 4-th point. I can't reproduce it.

**Comment by uslss** [comment]
there has been no update on the issue for a long time. If it is still actual - feel free to reopen it

**Comment by leandroluk** [comment]
Please add option to "do nothing" with word when user press `enter` or `space` or simple respect the fist letter case (like if need make changes or complentions, just use the first letter case)

**Comment by SeaPlusPlush** [comment]
Please for the love of god, give people options to turn off this "help". If I WANT to type something one way let me. Forcing users to to always have their text "corrected" is a genuine 0/10 take

**Comment by niraj-wh** [comment]
There are two steps:
1. Make autocompletion case UPPER:
![image](https://github.com/dbeaver/dbeaver/assets/152840735/524c8cc6-9bad-445a-b550-adc4bd721080)

2. Make formatting case UPPER as well:
![image](https://github.com/dbeaver/dbeaver/assets/152840735/11211cd9-b237-4b51-b6c7-f37b5d3cfed3)

**Comment by niraj-khatiwada** [comment]
There are two steps:
1. Make autocompletion case UPPER:
![image](https://github.com/dbeaver/dbeaver/assets/152840735/524c8cc6-9bad-445a-b550-adc4bd721080)

2. Make formatting case UPPER as well:
![image](https://github.com/dbeaver/dbeaver/assets/152840735/11211cd9-b237-4b51-b6c7-f37b5d3cfed3)

**Comment by AprilSlisar** [comment]
> There are two steps:
> 
> 1. Make autocompletion case UPPER:
>    ![image](https://private-user-images.githubusercontent.com/152840735/332358929-524c8cc6-9bad-445a-b550-adc4bd721080.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTI5NDIsIm5iZiI6MTcyMDY5MjY0MiwicGF0aCI6Ii8xNTI4NDA3MzUvMzMyMzU4OTI5LTUyNGM4Y2M2LTliYWQtNDQ1YS1iNTUwLWFkYzRiZDcyMTA4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxMDEwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmQ5YmUyMjNhMDM1N2U1NmQ4NTA1NTZmYTY4NDRkMjgzN2RhNGE3ZDFkZDUzODgwYzVhZTI4ZjQ0NDZiOGZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8LQ2ixNvL0zshWQ8vEDxKNEd47p-3xn7FkeE5299wwY)
> 2. Make formatting case UPPER as well:
>    ![image](https://private-user-images.githubusercontent.com/152840735/332359133-11211cd9-b237-4b51-b6c7-f37b5d3cfed3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTI5NDIsIm5iZiI6MTcyMDY5MjY0MiwicGF0aCI6Ii8xNTI4NDA3MzUvMzMyMzU5MTMzLTExMjExY2Q5LWIyMzctNGI1MS1iNmM3LWYzN2I1ZDNjZmVkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxMDEwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2FjY2FlMTlmY2Q5ODA2YTBkMTU1MTAyOGZiZDZjMDhjN2Y3NTFkYWM1OTRhYjQzNzRiMjM2ODhjYmZiMTQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._R61BL6IwK42zsFz-xTMY4WvYBLdhjN_g4AOctX9HDQ)

This second tip was very helpful, thank you for sharing!

I noticed that changing `Code Completion` -> `Insert case` to `Upper case` had the unintended effect of auto-completing the table names with upper case too (on DBeaver 24.1.2), not just the SQL keywords.
To overcome this, I found the best solution was actually to leave that one as `Default` (e.g. omit step 1) and only changing the `Formatting` -> `Keyword case` to `Upper (your suggestion for step 2) :) Sharing here in case it helps others too!

**Comment by McD0ugal** [comment]
Bravo April you are a legend

**Comment by McD0ugal** [comment]
> > There are two steps:
> > 
> > 1. Make autocompletion case UPPER:
> >    ![image](https://private-user-images.githubusercontent.com/152840735/332358929-524c8cc6-9bad-445a-b550-adc4bd721080.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTI5NDIsIm5iZiI6MTcyMDY5MjY0MiwicGF0aCI6Ii8xNTI4NDA3MzUvMzMyMzU4OTI5LTUyNGM4Y2M2LTliYWQtNDQ1YS1iNTUwLWFkYzRiZDcyMTA4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxMDEwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmQ5YmUyMjNhMDM1N2U1NmQ4NTA1NTZmYTY4NDRkMjgzN2RhNGE3ZDFkZDUzODgwYzVhZTI4ZjQ0NDZiOGZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8LQ2ixNvL0zshWQ8vEDxKNEd47p-3xn7FkeE5299wwY)
> > 2. Make formatting case UPPER as well:
> >    ![image](https://private-user-images.githubusercontent.com/152840735/332359133-11211cd9-b237-4b51-b6c7-f37b5d3cfed3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTI5NDIsIm5iZiI6MTcyMDY5MjY0MiwicGF0aCI6Ii8xNTI4NDA3MzUvMzMyMzU5MTMzLTExMjExY2Q5LWIyMzctNGI1MS1iNmM3LWYzN2I1ZDNjZmVkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxMDEwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2FjY2FlMTlmY2Q5ODA2YTBkMTU1MTAyOGZiZDZjMDhjN2Y3NTFkYWM1OTRhYjQzNzRiMjM2ODhjYmZiMTQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._R61BL6IwK42zsFz-xTMY4WvYBLdhjN_g4AOctX9HDQ)
> 
> This second tip was very helpful, thank you for sharing!
> 
> I noticed that changing `Code Completion` -> `Insert case` to `Upper case` had the unintended effect of auto-completing the table names with upper case too (on DBeaver 24.1.2), not just the SQL keywords. To overcome this, I found the best solution was actually to leave that one as `Default` (e.g. omit step 1) and only changing the `Formatting` -> `Keyword case` to `Upper (your suggestion for step 2) :) Sharing here in case it helps others too!

Yes this is the solution to the actual issue. Auto complete isn't what op was showing.
