### ISSUE TITLE
Gis: Topography view is applied for whole column only

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#17283]
### Description

GIS values can't be displayed in the topography view

### DBeaver Version

22.1.3.202207210656

### Operating System

Win

### Database and driver

PostgreSQL

### Steps to reproduce

1. Open a table with gis values (e.p. PostgreSQL gis.public.planet_osm_line)
2. open the Value panel, select some GIS values and change the view on the Topography in the panel

**Expected**: the data is displayed in the Topography view in the Value panel
**Actual result**: the map view isn't changed

https://user-images.githubusercontent.com/51405061/183298441-3270bf9c-1790-4e73-a84f-ba3a0fc02337.mp4

**Comment by ShadelessFox** [comment]
The topography view has a maximum zoom level of 17, while the street view has a zoom level of 20.

You can't switch to a given tile layer when you're zoomed in more than its maximum zoom level.

By selecting multiple points on the map, you've effectively zoomed out, so every point became visible.
