### ISSUE TITLE
Wrong script opened

### ISSUE THREAD

**Issue by bnelissen-orisha** [dbeaver/dbeaver#17291]
### Description

The wrong script is opened when opening a connection. It looks like it's the previously opened script in ALL connections instead the connection I choose.

Bug appears in 22.1.4, previous version are good.

This is my Scripts preferences :
![image](https://user-images.githubusercontent.com/37617999/183428033-8d0bb72e-edb3-4f8f-8fc1-73b2f7bee0d1.png)

### DBeaver Version

22.1.4

### Operating System

Windows 11

### Database and driver

DB2 on IBM i with jt400 JDBC driver

### Steps to reproduce

1. Double clic on a connection (I configured Open SQL editor when double clic on connection)
2. A tab with SQL editor is opened
3. Script inside is not the good one, it opened a script from another connection
4. Saving script causes big problems after...

**Comment by Matvey16** [comment]
@bnserig Thank you for the report

**Comment by dinicolae** [comment]
I have updated DBeaver recently and have the same issue. It is impossible to work now, cause I have so many connections and it messes up all my scripts.

**Comment by moonjoungyoung** [comment]
Same Issue here. It is so hard to work.
Can I downgrade dbeaver version ..?

**Comment by moonjoungyoung** [comment]
@Matvey16 

Same Issue here..
It is impossible to work now, so I am using another SQL tool.
Can I downgrade dbeaver version ..?

**Comment by Matvey16** [comment]
@moonjoungyoung Sorry for this. The earlier versions can be downloaded here https://dbeaver.io/files/
We fixed this bug and as soon as it is merged I'll update this ticket with a link to the new early access version.
