### ISSUE TITLE
Redshift Datashare browsing only available to superusers

### ISSUE THREAD

**Issue by byrider-jparker4** [dbeaver/dbeaver#17297]
### Description

When trying to browse a redshift datashare as a non-superuser, DBeaver is unable to display the schema/tables of the datashare.

It seems DBeaver uses `show datashares` and the `svv_datashare` and `svv_datashare_objects` views to display this information. However, those views are limited to superuser permissions.

Would it be possible to use non-superuser views (like below) to populate that data instead? These views list local and shared schemas/objects and don't require superuser permissions.
- svv_redshift_databases
- svv_redshift_schemas
- svv_redshift_tables
- svv_redshift_columns
- svv_redshift_functions

### DBeaver Version

Enterprise Edition 22.1.0

### Operating System

macOS Monterey 12.5

### Database and driver

1. Database name and version: AWS Redshift Serverless
2. Driver name and version: AWS Redshift JDBC Driver 42-2.1.0.3

### Steps to reproduce

1. create a redshift connection to an endpoint that has:
- a database created from a datashare consumer
- a non-superuser account that has been granted usage to the datashare database
3. connect to the redshift connection
4. attempt to browse the Datashares structure or the datashare database in the Databases structure
5. when attempting to view the schemas, nothing is returned

**Comment by LonwoLonwo** [comment]
Hello @byrider-jparker4 

Thanks for the report.

**Comment by Destrolaric** [comment]
@byrider-jparker4 Hi, sorry for the late response. We looked into our code and found that we used `svv_datashare` and `svv_datashare_objects`, which require root. But I am entirely not sure that `SHOW DATASHARES` requires admin access. AWS Documentation says that it only requires SHARE and ALTER on the datashare. Are you sure that is the case?

> Displays the inbound and outbound shares in a cluster either from the same account or across
> accounts. If you don't specify a datashare name, then Amazon Redshift displays all datashares in all
> databases in the cluster. Users who have the ALTER and SHARE privileges can see the shares that
> they have privileges for.

**Comment by byrider-jparker4** [comment]
@Destrolaric , No problem. I appreciate you looking into it.

*Users who have the ALTER and SHARE privileges*...

[https://docs.amazonaws.cn/en_us/redshift/latest/dg/r_ALTER_DATASHARE.html](Redshift ALTER DATASHARE)
### Required Privileges: 
Following are required privileges for ALTER DATASHARE:
- Superuser.
- User with the ALTER DATASHARE privilege.
- Users who have the ALTER or ALL privilege on the datashare.
- To add specific objects to a datashare, users must have the privilege on the objects. For this case, users should be the owners of objects or have SELECT, USAGE, or ALL privileges on the objects.

So if `SHOW DATASHARES` requires `ALTER`, and `ALTER` requires superuser, then `SHOW DATASHARES` requires superuser. At least that's how i read it, and that's what my testing has confirmed.

**Comment by Destrolaric** [comment]
@byrider-jparker4 More like it requires the superuser to give permissions to the second user, like most privileges in DB. Here is a little more descriptive part of the documentation:

> The following users can alter a datashare:
> A superuser
> The owner of the datashare
> Users that have ALTER or ALL privilege on the datashare

**Comment by byrider-jparker4** [comment]
@Destrolaric Ahh, so i did indeed interpret that wrong. Apologies, I am not a Redshift guru by any means.

So `SHOW DATASHARES` doesn't require superuser, BUT it does require more elevated permissions (`ALTER DATASHARE`) than most admins would be willing to give non-admin type users. 

Chaining the ability to view datashares to a view that requires the user to have the permissions to also change/destroy said datashare seems like a bad practice and doesn't allow for a scenario where non-admin users could still use the feature in DBeaver.

However, if the views mention earlier are used instead, then non-admin users can see exactly what they need without having elevated permissions that would allow them to administer the datashare.

**Comment by Destrolaric** [comment]
@byrider-jparker4 As I looked, I think you can see shared DB without those privileges. But looking for info about data share itself requires you to give alter for the user. Is it the case of viewing shared DB or data share metadata itself?

**Comment by byrider-jparker4** [comment]
@Destrolaric what we are looking for specifically is the ability for non-admin users to be able to "browse" the datashare database the same as they would a regular database. Drilling down in the Database Navigator through Schemas, Tables. etc.

As an admin i can do this, but as a non-admin the Schemas folder never populated because of the view used to gather that data. In the screenshot
![Screenshot 2022-11-30 at 8 27 39 AM](https://user-images.githubusercontent.com/58598218/204808493-44fc6258-25d0-4469-acfa-0466116e35e1.png)
the top connection is an admin, the second is non-admin. I just want non-admins to be able to browse.

**Comment by Destrolaric** [comment]
Ahh, you see, we use svv_datashare for a different thing. You can see a particular Datashares folder. This one contains specific info about data share itself. `Show data shares and mentioned view gives information about it.
Can you try using 
```
GRANT USAGE ON { DATABASE shared_database_name [, ...] | SCHEMA shared_schema}
    TO { username | ROLE role_name | GROUP group_name | PUBLIC } [, ...]
```

**Comment by Destrolaric** [comment]
Reference from Amazon docs:

> The following is the syntax for using GRANT for datashare usage privileges on Amazon Redshift. You grant access to a datashare to a consumer using the USAGE privilege. You can't grant this privilege to users or user groups. This privilege also doesn't support the WITH GRANT OPTION for the GRANT statement. Only users or user groups with the SHARE privilege previously granted to them FOR the datashare can run this type of GRANT statement.
> 
> 
> GRANT USAGE 
>     ON DATASHARE datashare_name 
>     TO NAMESPACE 'namespaceGUID' [, ...] | ACCOUNT 'accountnumber' [, ...]
> The following is the syntax for GRANT data-sharing usage permissions on a specific database or schema created from a datashare. This USAGE permission doesn't grant usage permission to databases that aren't created from the specified datashare. You can only GRANT or REVOKE ALTER or SHARE permissions on a datashare to users and user groups.
> 
> 
> GRANT USAGE ON { DATABASE shared_database_name [, ...] | SCHEMA shared_schema}
>     TO { username | ROLE role_name | GROUP group_name | PUBLIC } [, ...]

**Comment by Destrolaric** [comment]
@byrider-jparker4 Hi, could you tell me if the mentioned information helped?

**Comment by byrider-jparker4** [comment]
@Destrolaric ,When i attempt to expand the Schemas folder under the database created from the datashare, the following query hits redshift `SELECT * FROM SVV_DATASHARES ORDER BY share_name`. The query completes, but the results are empty because the user doesn't have privileged access. 

When i attempt to expand the Datashares folder, the same query hits redshift, with the same result.

So both the database browser and the datashare browser are using the same view.

`GRANT USAGE ON DATABASE warehouse TO GROUP risk;` has already been run and that is part of what allows the users to access the data in the datashare database, but DBeaver doesn't use a command to populate the datashare database browsing section that a non-priveleged user can run.

**Comment by Destrolaric** [comment]
This request happens because the redshift refresh action updates all metadata on the same tree level. It will update databases and refresh metadata for datashares (which fails but doesn't affect catalog refresh). You can easily share your database or schema via the following query.
```
grant usage on database/schema [schema name] to [username]
```
Please write back if helps.

**Comment by byrider-jparker4** [comment]
@Destrolaric , The non-privileged users have no problem using the datashare database (database usage has already been granted), so access/permissions is not the issue, the users can use the database exactly how we want them to, the problem is that DBeaver isn't allowing them to browse the datashare database objects from the tree view.

**Comment by ShadelessFox** [comment]
Unfortunately, we can't even rely on the `svv_redshift_databases` view because it truncates the data we need:

![java_rlHL10kYLp](https://user-images.githubusercontent.com/35821147/209177732-c99f4481-463c-4281-8de6-8883f5f54ccc.png)

Note that the JSON value is truncated in the `database_options` columns because it has type `varchar(128)`. Also, it seems like these options aren't documented anywhere, so we can't rely on this data.

Additionally, we can't directly query the `pg_external_database` table this data comes from because you can't access it even with root access.

**Comment by serge-rider** [comment]
Datashares meta model read has been refactored

**Comment by cesar-loadsmart** [comment]
Hi folks!

Is this already available on dbeaver latest release?

**Comment by serge-rider** [comment]
@cesar-loadsmart yes it is (in PRO products).

**Comment by simon-streamotion** [comment]
Hi....
Will this fix be available in CE soon ?
Many thanks -- Simon

**Comment by serge-rider** [comment]
Unfortunately CE doesn't support Redshift datashares at all.

**Comment by simon-streamotion** [comment]
@serge-rider Thanks for the confirmation....

I've downloaded and installed the free trial for EE and have configured it to access our data-share cluster. When connecting using a standard userid/password combo then a non-admin user can browse the object tree and see the data shares :-)

However, when I configure the JDBC driver to use SAML Federation (OKTA) using the following guide: https://bambooengineering.io/connecting-dbeaver-to-redshift-using-saml-federation-and-mfa/ then the object tree is empty when using a non-admin user (I haven't tried a user with admin privs). Should browsing of data-share object trees work with the SAML Federation setup ?

Thanks -- Simon

**Comment by AlexThomas90210** [comment]
Hi is there any update for this in the CE edition?

**Comment by LonwoLonwo** [comment]
Hello @AlexThomas90210 

What kind of updates do you expect?

**Comment by AlexThomas90210** [comment]
@LonwoLonwo An update to having the ability for non super users to view the schemas and tables in a datashare on Redshift they have access too in the DBeaver CE.

Right now we have a datashare with a bunch of users that have read access to it but they can't explore the schemas/tables in DBeaver and they need to use another tool just to explore the DB

**Comment by LonwoLonwo** [comment]
You can try our PRO versions for free: https://dbeaver.com/trial/

**Comment by gjukes** [comment]
I am hoping for an update on this as well. I have the same issue in DBeaver Ultimate as of now.

**Comment by LonwoLonwo** [comment]
Hello @gjukes 

If you have issues with DBeaver Ultimate version, please get in touch with our tech support: https://dbeaver.com/tickets
