### ISSUE TITLE
After install of latest community edition, getting "Datasource config parse error"

### ISSUE THREAD

**Issue by camoore1979** [dbeaver/dbeaver#17300]
### Description

Just installed the latest community edition of DBeaver (dbeaver-ce-22.1.4-macos-x86_64.dmg) on my MacBook Pro (15-inch, Mid 2015, 2.2 GHz Quad-Core Intel Core i7 running macOS Monterey Version 12.5). I had been running a much older version of DBeaver, but after removing DBeaver completely (so far as I can tell), installed this version and keep getting this error:

<img width="730" alt="Screen Shot 2022-08-08 at 3 33 48 PM" src="https://user-images.githubusercontent.com/4583280/183502267-431632ef-ad2f-4625-a4da-20b6148e6be6.png">

It allows me to create a connection, connect to a database, save and close the application. However, on re-opening it will display the same parsing error and will not show any configured connections.

System Specs:
<img width="246" alt="Screen Shot 2022-08-08 at 3 48 35 PM" src="https://user-images.githubusercontent.com/4583280/183502255-5e713195-2f3e-4f4a-b042-c0a136936d8d.png">

### DBeaver Version

Community Edition 22.1.4

### Operating System

macOS Monterey 12.5

### Steps to reproduce

1. Download DBeaver
2. Install DBeaver
3. Attempt to Open DBeaver
4. DBeaver opens, but displays error in image above.

**Comment by E1izabeth** [comment]
Could you send the `data-sources` or/and `dbeaver-data-sources` file (depends on which one do you have)?
You can find it in the [workspace](https://github.com/dbeaver/dbeaver/wiki/Workspace-Location)\workspace6\General\\.dbeaver.

**Comment by camoore1979** [comment]
@E1izabeth Great Q. That led me to the problem, I could not find the location of those exact data source files and if they existed I didn't care to keep them, but you got me to digging around. To resolve, I did some `find` commands and found all the DBeaver config files, removed them, and did a full uninstall of DBeaver and re-install. That worked. Thanks!
