### ISSUE TITLE
Color workboock sql 

### ISSUE THREAD

**Issue by mipi21** [dbeaver/dbeaver#17309]
### Description

In the last version of DBEaver sql file workboock dont change color.
Example if I open a file SQL whit env PRODUCTION is settend in orance color, afther I change enviroment for this workboock in DEV (DEV has settend whit white color), workboock is stay in orance color and not change in white color.

please fix it.
Thanks.

### DBeaver Version

Community Editions 22.1.4

### Operating System

windows

### Database and driver

Oracle JDBC driver

### Steps to reproduce

1. connect to DB in env PRODUCTION
2. the workboock is settend in Orance color
3. Change env in SVIL dev
4. Check if change color

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
Connected to #16785
