### ISSUE TITLE
Oracle END tag name 

### ISSUE THREAD

**Issue by Roill** [dbeaver/dbeaver#1730]
It seems like DBeaver does not properly support the object name after an end tag in Oracle. When I run a create or replace from a SQL editor, it leaves off the trailing semicolon when the name is provided after the "END" tag.

For example, this works fine.

`CREATE OR REPLACE PACKAGE test_package IS
  PROCEDURE test;
END;`

![image](https://cloud.githubusercontent.com/assets/28357495/26682084/3a959bd0-46ad-11e7-88e8-7efb2200d9a1.png)

But running this, leaves the ending semicolon off in the final package.

`CREATE OR REPLACE PACKAGE test_package IS
  PROCEDURE test;
END test_package;`

![image](https://cloud.githubusercontent.com/assets/28357495/26682061/21bb819c-46ad-11e7-9586-787fef05ad34.png)

Naturally, this means I have to navigate to the object manually, refresh it, add the semicolon, and persist it. It's manageable, but cumbersome. I can reproduce the same issue with procedures and functions as well.

I know the end tag name is not necessary, so I have been leaving it off where I can. However, it's a practice we adhere to in our office, and it keeps things readable when working with multiple procedures/functions

Thanks

**Comment by uslss** [comment]
Issue cannot be reproduced on 6.0.2.
