### ISSUE TITLE
DBeaver no longer associates SQL Editor files with connection

### ISSUE THREAD

**Issue by SultanCordoba** [dbeaver/dbeaver#17316]
### Description

When you right-clicked a connection and selected "SQL Editor", when you wanted to select a file, it used to consider only the scripts used by that connection. Right now it considers ALL of them. 
If you unclick "Show scripts for all connections" the only change is the icon at the left of any row as shown in these two images
![image](https://user-images.githubusercontent.com/8661483/183671343-8f261c46-2f15-48ba-adfa-fd2127f379ef.png)
![image](https://user-images.githubusercontent.com/8661483/183671542-09a53839-1d7c-4cf3-abee-9a8c2716c051.png)

### DBeaver Version

Community Edition 22.1.4.202208051447

### Operating System

Windows 11

### Database and driver

SQL Server and Oracle

### Steps to reproduce

1) Have two connections for different database servers. Both of them with previously created SQL script files to be opened via SQL Editor
2) Connect to one of the servers, open a SQL file. Change anything.
3) Close the connection to that server, so the file will be saved.
4) Open the other connection, and then choose from SQL Editor "Open recent file"
5) It will open the file of the connection of steps 2 and 3.

Expected behaviour: The second connection should not open the file associated with the first one.

**Comment by SultanCordoba** [comment]
How can I verify the behaviour so the issue can be closed?

**Comment by Matvey16** [comment]
Can be related #17291 

@SultanCordoba There is no need, thank you. We will test it and if everything good it will be fixed in the nearest update
