### ISSUE TITLE
AltGr + 1 + 2 + 6

### ISSUE THREAD

**Issue by solisgb** [dbeaver/dbeaver#17311]
Windows 10
Dbeaver Version 22.1.4.202208051447 

When I open a new SQL console and press the keys Alt + 1 + 2 + 6 it writes ~ as I wanted. But after executing any operation from the console, this keyboard shortcut stops working.  

It would be very useful if this keyboard shortcut (Alt + 1 + 2 + 6 typing the ~ symbol in the console) would work in a normal work session.

**Comment by Destrolaric** [comment]
Looks like an active result panel makes using alt + number binding impossible. Looks like a bug.

**Comment by E1izabeth** [comment]
I can't reproduce this issue anymore. Does it still actual?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
