### ISSUE TITLE
Automatic reconnect does not work for menu functionality (such as Generate DDL)

### ISSUE THREAD

**Issue by Aileron79** [dbeaver/dbeaver#17326]
### Description

When a script window loses connectivity, it will automatically reconnect when I execute a new statement. However, when a connection has timed out and I select Generate SQL => DDL from a database object's context menu, an error message will pop up saying that the connection is invalid:
![image](https://user-images.githubusercontent.com/16278437/183894314-c6b6749e-953e-4448-8b91-fa2636fdd05d.png)
When I close it with clicking ok, an empty window pops up:
![image](https://user-images.githubusercontent.com/16278437/183894539-72da89e6-ab6e-40ff-a05c-d7145f21cc6b.png)
There is no point in showing an empty window when the connection fails.

I'd expect the connection to automatically be restored or at least the empty window not to pop up.

### DBeaver Version

22.1.4

### Operating System

Windows 10 x64

### Database and driver

Azure SQL

### Steps to reproduce

Connect to a DB
Expand the table tree view
let the connection time out
right click a table => Generate SQL => DDL
error message will pop up
empty window will pop up

**Comment by uslss** [comment]
thanks for the report
