### ISSUE TITLE
Choose SQL script (F3) shows scripts for all connections  

### ISSUE THREAD

**Issue by McMogan** [dbeaver/dbeaver#17325]
### Description

Choose SQL script (F3) shows scripts for all connections , even if checkbox "Show scripts for all connections" is unchecked.
Works fine on Dbeaver 22.1.2

### DBeaver Version

22.1.4

### Operating System

Windows

### Steps to reproduce

Select a database connexion
press F3

**Comment by Destrolaric** [comment]
Hi, duplicate of https://github.com/dbeaver/dbeaver/issues/17316.

**Comment by E1izabeth** [comment]
Thank you for bug report.
