### ISSUE TITLE
False Table Metadata Displayed

### ISSUE THREAD

**Issue by chiraPaki** [dbeaver/dbeaver#17323]
### Description

The Database Navigator shows me wrong metadata of tables. 
For example, I have a table with NVARCHAR columns having a length 10 letters, but the Navigator states that the length were 5.
Even if I copy the table, the data are not cut down to, the length of the data is still 10, but even the copy table states length = 5.
DBeaver (false):
![grafik](https://user-images.githubusercontent.com/110963347/183828156-16bee2d2-e58c-4042-8fc2-ad672b259359.png)
SSMS (correct):
![grafik](https://user-images.githubusercontent.com/110963347/183828258-5e618920-4e84-404f-8b4d-eedad58e6b39.png)

I am working on a Microsoft SQL Database.
This problem occurred since today since I have created the tables yesterday without any issues.
An update to the latest version didn't help.

### DBeaver Version

Version 22.1.4.202208051447

### Operating System

Windows 10

### Database and driver

1. Database: MS SQL Server / SQL Server, Windows Server 2016 Datacenter (10.0), version 14.0.3445.2
2. Driver: Microsoft JDBC Driver for SQL Server (standard)

### Steps to reproduce

1. I open the metadata information of the table within the Database Navigator
2. I open the metadata information of the table's columns within the Database Navigator

**Comment by uslss** [comment]
@chiraPaki could you provide table ddl to reproduce an issue?

**Comment by chiraPaki** [comment]
Sure. Here it is:

CREATE TABLE DataLake.snow.hlptbl_tickets (
	ID bigint IDENTITY(1,1) NOT NULL,
	[Issue Type] nvarchar(25) COLLATE Latin1_General_100_CS_AS NULL,
	[Number] nvarchar(10) COLLATE Latin1_General_100_CS_AS NULL,
	[Short Description] nvarchar(1000) COLLATE Latin1_General_100_CS_AS NULL,
	[Assignment group] nvarchar(500) COLLATE Latin1_General_100_CS_AS NULL,
	[Assigned to] nvarchar(1000) COLLATE Latin1_General_100_CS_AS NULL,
	[Caller Id] nvarchar(1000) COLLATE Latin1_General_100_CS_AS NULL,
	Priority nvarchar(2) COLLATE Latin1_General_100_CS_AS NULL,
	State nvarchar(1000) COLLATE Latin1_General_100_CS_AS NULL,
	[Created date] datetime NULL,
	[Updated date] datetime NOT NULL,
	[Resolved date] datetime NULL,
	[Closed date] datetime NULL,
	[Related problem] nvarchar(1000) COLLATE Latin1_General_100_CS_AS NULL,
	[Problem Short Description] nvarchar(1000) COLLATE Latin1_General_100_CS_AS NULL,
	[Transfer date] datetime NOT NULL,
	CONSTRAINT PK_hlptbl_tickets PRIMARY KEY (ID,[Updated date],[Transfer date])
);

I just notice that even the automated DDL generation is gettiung it wrong, as the output is:
CREATE TABLE DataLake.snow.hlptbl_tickets (
	ID bigint IDENTITY(1,1) NOT NULL,
	[Issue Type] nvarchar(25) COLLATE Latin1_General_100_CS_AS NULL,
	[Number] nvarchar(5) COLLATE Latin1_General_100_CS_AS NULL,
	[Short Description] nvarchar(1000) COLLATE Latin1_General_100_CS_AS NULL,
	[Assignment group] nvarchar(500) COLLATE Latin1_General_100_CS_AS NULL,
	[Assigned to] nvarchar(1000) COLLATE Latin1_General_100_CS_AS NULL,
	[Caller Id] nvarchar(1000) COLLATE Latin1_General_100_CS_AS NULL,
	Priority nvarchar(1) COLLATE Latin1_General_100_CS_AS NULL,
	State nvarchar(1000) COLLATE Latin1_General_100_CS_AS NULL,
	[Created date] datetime NULL,
	[Updated date] datetime NOT NULL,
	[Resolved date] datetime NULL,
	[Closed date] datetime NULL,
	[Related problem] nvarchar(1000) COLLATE Latin1_General_100_CS_AS NULL,
	[Problem Short Description] nvarchar(1000) COLLATE Latin1_General_100_CS_AS NULL,
	[Transfer date] datetime NOT NULL,
	CONSTRAINT PK_hlptbl_tickets PRIMARY KEY (ID,[Updated date],[Transfer date])
);

**Comment by LonwoLonwo** [comment]
Hello @chiraPaki 

Thanks for the report.
We already have bug ticket this problem: https://github.com/dbeaver/dbeaver/issues/16996

So I'm closing this ticket as duplicate
