### ISSUE TITLE
[Feature]: ee version of the eclipse plugin

### ISSUE THREAD

**Issue by peter-janssen** [dbeaver/dbeaver#1732]
I'm having a hard time using cassandra with a regular eclipse instance. Using dbeaver-ee everything  works fine but due to limited resources of the machine I have to work on I'd like to manage my cassandra db from within my eclipse ide. I tried moving the necessary parts but to no avail. Is there a possibility that you could release an ee version of the eclipse plugin?

**Comment by uslss** [comment]
Already done,
Ticket closed.
