### ISSUE TITLE
Database Tasks saved in 22.1.0 version doesn't work  in higher versions (22.1.1 - 22.1.4)

### ISSUE THREAD

**Issue by Dkrav-UA** [dbeaver/dbeaver#17329]
### Description

Task created in version 22.1.0 produces errors  in higher versions. 
tasks.json file contains wrong information about fields. GUI shows correct information, but file contains different (wrong) names.

tasks.json (version 22.1.0)
![изображение](https://user-images.githubusercontent.com/16414895/183919563-aad28f4b-557b-4dbb-8e0f-4ac76535e941.png)

tasks.json (changed by 22.1.4 version) File was changed when task was opened:
![изображение](https://user-images.githubusercontent.com/16414895/183915527-7a5cee7d-5d7c-4952-9de8-5f5f5a7443cd.png)

Task GUI:
![изображение](https://user-images.githubusercontent.com/16414895/183915724-2d3f9d5b-3edf-44b2-8bf1-ad3033da0643.png)

Error message:
![изображение](https://user-images.githubusercontent.com/16414895/183915946-dc4b9917-d13a-4eaf-9448-c48084b4129f.png)
 
Further more changing fields name in GUI doesn't change field name in tasks.json
I managed to rename NAME1. But first I set this field to 'skip' option. Save task. Set new (correct) name. Save task

### DBeaver Version

Community Edition Version 22.1.4.202208051447

### Operating System

Ubuntu 20.04

**Comment by Matvey16** [comment]
Thank you for the report

**Comment by ShadelessFox** [comment]
Hello @Dkrav-UA,

I'm unable to reproduce your issue. Can you try installing the latest version of DBeaver? https://dbeaver.io/download

**Comment by ShadelessFox** [comment]
This issue was caused by #15860.

**Comment by Dkrav-UA** [comment]
Version 22.2.0
No changes. Still can't import
![изображение](https://user-images.githubusercontent.com/16414895/188386981-85210b04-5c92-45cf-9510-49b304ee50f0.png)

LOG
2022-09-05 10:12:06.511 - Initialize pipes
2022-09-05 10:12:06.512 - Create necessary database objects
2022-09-05 10:12:06.512 - 	Validate table structure table 'street'
2022-09-05 10:12:06.513 - Attribute does not support updating its max length
2022-09-05 10:12:06.513 - Attribute does not support updating its precision
2022-09-05 10:12:06.513 - Attribute does not support updating its scale
2022-09-05 10:12:06.514 - Create target metadata
2022-09-05 10:12:06.514 - 	Create new table column
2022-09-05 10:12:06.560 - Post transfer work
2022-09-05 10:12:06.560 - Task fatal error
org.jkiss.dbeaver.model.exec.DBCException: Can't create or update target table:
ALTER TABLE cadastr_portal.street ADD street_t smallint NULL;
ALTER TABLE cadastr_portal.street ADD name1 varchar(120) NULL;

**Comment by ShadelessFox** [comment]
Are you editing a persisted task or created a new one?

**Comment by Dkrav-UA** [comment]
Continue previous. Your suggestion about "issue was caused by https://github.com/dbeaver/dbeaver/issues/15860"  did not solve the problem. 
When task executes it takes setting from tasks.json. However data in tasks.json and in GUI doesn't match.

When I manually changed all fields in JSON-file to correct values (had to change UPPERCASE to LOWERCASE) I managed to run the task.

**Comment by Matvey16** [comment]
@Dkrav-UA I wasn't able to reproduce this issue on the latest version. Are you sure it is the same problem?
I see tha you had different errors in 22.1.4 and 22.2.0
```
ALTER TABLE cadastr_portal.street ADD "STREET_T" smallint NULL;

and

ALTER TABLE cadastr_portal.street ADD street_t smallint NULL;
```
So in the latest one I see DBeaver trying to create a lowercase column just like in UI

**Comment by Dkrav-UA** [comment]
Error is reproducible.

1. Create table to import from.
     
```
CREATE TABLE public.uppercase (
	id serial4 NOT NULL,
	"TXT" varchar NULL,
	CONSTRAINT uppercase_pk PRIMARY KEY (id)
);
```
2. Create second table :  
```

CREATE TABLE public.lowercase (
	id int4 NOT NULL
);
```
3. Import Data
![изображение](https://user-images.githubusercontent.com/16414895/191238058-fc571f9f-1bec-4749-bbe7-f1c187be3541.png)

4. 
![изображение](https://user-images.githubusercontent.com/16414895/191238649-f1f8caa4-ddc9-4ed9-acec-a3129c64e101.png)
by default, DBeaver will convert 'TXT' to 'txt' . So you need to rename it to "TXT"

5. Save this task .
6. Proceed with import. As a result "TXT" field will be renamed to "txt". **(btw I think this is bug too)**
7. Try to edit this task
![изображение](https://user-images.githubusercontent.com/16414895/191239858-def7aa8c-4802-4f8a-b08e-f82dc26a0864.png)
8. Try to execute it. 
9. Error.

contents of tasks.json

![изображение](https://user-images.githubusercontent.com/16414895/191240355-2cd0363b-36d2-44b8-ad5d-79dd9016b0c7.png)

**Comment by Matvey16** [comment]
@Dkrav-UA Thank you for steps to reproduce, we are looking at it.
