### ISSUE TITLE
Menu bar and right-click not functioning correctly in macOS Ventura

### ISSUE THREAD

**Issue by bendoughty** [dbeaver/dbeaver#17324]
### Description

Hello!

I have been noticing a few oddities while running DBeaver on beta versions of the forthcoming macOS Ventura (13.0) release:

1. Clicking any of the menu bar items (Navigate, Seach, SQL Editor, etc) does not produce a menu as expected.

2. Secondary (aka "right") click does not work in any part of the DBeaver interface

Log: [dbeaver-debug copy.log](https://github.com/dbeaver/dbeaver/files/9298004/dbeaver-debug.copy.log)

### DBeaver Version

CE 22.1.4, both Intel and AS versions

### Operating System

macOS Ventura (13.0)

### Database and driver

Not pertinent (issues are present in a fresh install).

### Steps to reproduce

1. Open DBeaver
2. Try to select an option in the menu bar
3. Try a secondary click anywhere within the interface

**Comment by LonwoLonwo** [comment]
Hello @bendoughty 

DBeaver is based on the Eclipse platform, and this is the Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=580322

It seems to be fixed already, but this fix will be available in our product only in Autumn with the new Eclipse release.

**Comment by LonwoLonwo** [comment]
Duplicate: https://github.com/dbeaver/dbeaver/issues/17204

**Comment by bendoughty** [comment]
Thank you very much both for the information and for your hard work on DBeaver, @LonwoLonwo.

I look forward to using future releases with Ventura, but in the meantime I have taken a look through the issue you linked, and it does indeed appear that earlier versions of DBeaver (<=22.1.0, to be exact) do not suffer from the issues noted above. If any other early adopters of macOS Ventura happen to stumble across this, that might be a decent workaround for the time being.

**Comment by vaaski** [comment]
For anyone trying to install 22.1.0 with homebrew and being annoyed that it isn't as easy as just prepending @22.1.0, heres how I did it according to [this stackoverflow post](https://stackoverflow.com/a/69832222/6765374)

```bash
curl https://raw.githubusercontent.com/Homebrew/homebrew-cask/707f37126777e710d34232ed602c49329907e221/Casks/dbeaver-community.rb > $(find $(brew --repository) -name dbeaver-community.rb)
brew reinstall dbeaver-community
```

this installs https://github.com/Homebrew/homebrew-cask/commit/707f37126777e710d34232ed602c49329907e221, which restored right-click functionality for me on my m2 air running ventura.
