### ISSUE TITLE
Documentation bug in DBeaver SVG Extension

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#17333]
### Description

The link https://dbeaver.com/docs/wiki/Extension-SVG-Format/
contains info about Office extension, not SVG.
So I dont know how to use svg extension

### DBeaver Version

not applicable

### Operating System

not applicable

### Database and driver

not applicable

### Steps to reproduce

not applicable

### Additional context

not applicable

**Comment by E1izabeth** [comment]
@plotn thank you for bug report.
You can install DBeaver SVG Extension by following these steps:
1. Go to the main menu Help -> Install New Software
2. Paste https://dbeaver.io/update/svg/latest/ into Work with field and press Enter
3. Check DBeaver Extension->DBeaver Office Extension item and press Next
4. Accept license agreement, press next.
5. Wait for the installation and agree to restart DBeaver.

**Comment by plotn** [comment]
And how to use it?

**Comment by E1izabeth** [comment]
It allows to save diagram to svg.

**Comment by Matvey16** [comment]
Changed the information to match the name of the page

https://github.com/dbeaver/dbeaver/wiki/Extension-SVG-Format
