### ISSUE TITLE
Search>File: Add scope "Open Files" to "File Search"

### ISSUE THREAD

**Issue by GuenterSch** [dbeaver/dbeaver#17330]
Hello,

in the dialog "File Search", please add the option "Open Files" in section "Scope".
With scope "Open Files" (or "Open SQL Editors") it should be possible, to search in all open SQL Editors (Open Files). This should also work, if the files are distributed on the file system and not in one workspace.

Whether it works on unsaved files too, should be dependend how easy the implementation is.

Thanks, hope you implement this feature. BR
Günter

![grafik](https://user-images.githubusercontent.com/99535516/183913200-97b1dde5-0e16-4f88-bdce-134d33957fe1.png)

**Comment by ShadelessFox** [comment]
Hello @GuenterSch,

Unfortunately, we can't modify this dialog since it's a part of Eclipse, neither it can be extended.
