### ISSUE TITLE
crash on right click

### ISSUE THREAD

**Issue by mgrahamfa** [dbeaver/dbeaver#17344]
### Description

right clicking on things instantly crashes dbeaver.
with the following report.  It did not happen in 7.3.5

JVM terminated. Exit code=127
/initrd/mnt/tmpfs/tmp/.mount_DBeavemitLCF/dbeaver/jre/bin/java
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-jar /initrd/mnt/tmpfs/tmp/.mount_DBeavemitLCF/dbeaver//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
-os linux
-ws gtk
-arch x86_64
-showsplash
-launcher /initrd/mnt/tmpfs/tmp/.mount_DBeavemitLCF/dbeaver/dbeaver
-name Dbeaver
--launcher.library /initrd/mnt/tmpfs/tmp/.mount_DBeavemitLCF/dbeaver//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.500.v20220509-0833/eclipse_11701.so
-startup /initrd/mnt/tmpfs/tmp/.mount_DBeavemitLCF/dbeaver//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
--launcher.overrideVmargs
-exitdata 1b000a
-vm /initrd/mnt/tmpfs/tmp/.mount_DBeavemitLCF/dbeaver/jre/bin/java
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-jar /initrd/mnt/tmpfs/tmp/.mount_DBeavemitLCF/dbeaver//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar 

### DBeaver Version

Community Edition versions 22.1.1 thru 4

### Operating System

Linux :  uname -a
Linux puppypc26280 4.19.164 #1 SMP Sat Jan 2 15:22:11 AEST 2021 x86_64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz GenuineIntel GNU/Linux

### Database and driver

mssql 2017

### Steps to reproduce

right click on anything

### Additional context

It even happens with an appimage I found version 22.1.2

The Linux I use is based on Slackware 14.2
I run other Java applications without any issues.

**Comment by mgrahamfa** [comment]
OS
Linux puppypc26280 4.19.164 #1 SMP Sat Jan 2 15:22:11 AEST 2021 x86_64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz GenuineIntel GNU/Linux

Database mssql
driver libmsodbcsql 17.6

I don't think it is database related, right clicking an just about anything crashes dbeaver.

I am able to connect to the database and use the system as long as I remember to not right click.
unfortunately, some things are more difficult to do that way.

**Comment by mgrahamfa** [comment]
accidently closed... 
the problem is still happening.

**Comment by E1izabeth** [comment]
Thank you for bug report.
Please, send us the log files. You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/

**Comment by mgrahamfa** [comment]
I didn't know where the log files were.  I see the problem is probably my GTK is too old.sorry to bother you. I'll have to see what my options are to upgrade.
thanks.

    On Monday, August 15, 2022, 03:45:32 AM PDT, Elizabeth ***@***.***> wrote:  
 
 


Thank you for bug report.
Please, send us the log files. You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/

**Comment by Guzya** [comment]
+1
[log.zip](https://github.com/dbeaver/dbeaver/files/9673169/log.zip)

`JVM terminated. Exit code=127
/usr/share/dbeaver-ce/jre/bin/java
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-Ddbeaver.distribution.type=deb
-jar /usr/share/dbeaver-ce/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
-os linux
-ws gtk
-arch x86_64
-showsplash
-launcher /usr/share/dbeaver-ce/dbeaver
-name Dbeaver
--launcher.library /usr/share/dbeaver-ce/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.500.v20220509-0833/eclipse_11701.so
-startup /usr/share/dbeaver-ce/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
--launcher.overrideVmargs
-exitdata 31000e
-vm /usr/share/dbeaver-ce/jre/bin/java
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-Ddbeaver.distribution.type=deb
-jar /usr/share/dbeaver-ce/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar 
`

4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Guzya** [comment]
dbeaver 22.2.1

**Comment by mgrahamfa** [comment]
I recreated the crash logs for you in case you might find it helpful.  I did find a newer distribution (debian bullseye)  that works if I install from the debian repository,
The crash is using an appimage of dbeaver (v 22.1.2)

[logs.zip](https://github.com/dbeaver/dbeaver/files/9680987/logs.zip)
