### ISSUE TITLE
Can't expand schemas tab in navigation bar

### ISSUE THREAD

**Issue by vtsimbos** [dbeaver/dbeaver#17346]
### Description

I have connected an Oracle Database in dbeaver v. 22.1.1.202206261508. When I try to expand the schemas in the database navigator I got this error:
"ORA-00904: "U"."USERNAME": invalid identifier". 

And on the details:
SQL Error [904] [42000]: ORA-00904: "U"."USERNAME": invalid identifier
Error : 904, Position : 35, Sql = SELECT U.* FROM ALL_USERS U
WHERE (U.USERNAME IS NOT NULL), OriginalSql = SELECT U.* FROM ALL_USERS U
WHERE (U.USERNAME IS NOT NULL), Error Msg = ORA-00904: "U"."USERNAME": invalid identifier
ORA-00904: "U"."USERNAME": invalid identifier

My Database has a schema that is called ALL_USERS.  If I execute the above querry in the editor I get the same error. But
if I write SYS.ALL_USERS instead of just ALL_USERS, it succesfully retrieves all schemas in Database.

### DBeaver Version

22.1.1 community

### Operating System

Windows 10

### Database and driver

Oracle

### Steps to reproduce

1. Connect an Oracle database that contains a schema with name "ALL_USERS"
2. Expand 'Scemas' in database navigator

**Comment by uslss** [comment]
unfortunately cannot reproduce the issue.
What Oracle version do you use?

**Comment by vtsimbos** [comment]
The version is 19c

**Comment by LonwoLonwo** [comment]
Hello @vtsimbos 

"ALL_USERS" is a specific name for the SYS schema system view.

So, in this case, you can change this setting in your connection settings:

![2022-09-08 16_11_50-DBeaver Ultimate 22 2 0 - MAPS](https://user-images.githubusercontent.com/45152336/189131440-4ebc19a1-362e-4ea3-8e25-3c7380a78ce3.png)

It will help in your case, I hope.

**Comment by vtsimbos** [comment]
LonwoLonwo thank you very much. Your solution works fine.
