### ISSUE TITLE
greenplum prepareLookupStatement is not work on GP7

### ISSUE THREAD

**Issue by wangxuqi** [dbeaver/dbeaver#17341]
### Description

When I build greenplum version 7 with master branch.  It does not have pg_catalog.pg_partitions system view and also the pg_class catalog does not has 'relstorage' column.  Shall we support it?

![image](https://user-images.githubusercontent.com/13748374/184318584-e0507b5a-b2a6-4e79-9e1b-46862606259d.png)
![image](https://user-images.githubusercontent.com/13748374/184318690-0cc43349-bbe6-48d7-b0ac-369fc37de6b1.png)

### DBeaver Version

22.10

### Operating System

all

### Steps to reproduce

![image](https://user-images.githubusercontent.com/13748374/184319016-fd9b65b8-22f2-4518-b8b1-1e987be3a81f.png)

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @wangxuqi

**Comment by LonwoLonwo** [comment]
Fixed in the last (23.0.5) release.
Now we support Greenplum 7 version.
