### ISSUE TITLE
Export data - weird column naming behaviour

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#17348]
### Description

When I try to export data and name columns (I write, then click by mouse on the next field) there are beahavior:
1. Correct renaming and selecting of the next field;
2. Returning of old value (sometimes several times, then it could be as of 1);
3. Active window flickering;
4. If i press enter insead of mouse click - then could be selected row above (or 2,3,4 lines above), not next.

![dbeaver_export](https://user-images.githubusercontent.com/11477081/184548183-435d07d4-6880-46ad-a3d7-9aa73bc67992.png)

### DBeaver Version

22.1.4.202208051447

### Operating System

win

### Database and driver

PostgreSQL

**Comment by E1izabeth** [comment]
Thank you for bug report.
Additional note: 
- I cannot select the previously suggested `Target` if the were only one proposal after `[skip]` has been selected.
- It's not possible to use keyboard to navigate through the target columns list.
- Sometimes several lists shows expanded state, but no one of them are really expanded.
![image](https://user-images.githubusercontent.com/28875055/184974114-5e5142d4-deba-458d-8d90-fc1d9e6d8e44.png)

**Comment by plotn** [comment]
some addition. Exporting from pg to ora:
1. All columns are quoted. Please, don do that - it really hurts. We all except behaviour: pg lower case = ORA UPPER CASE and this is ok. If (if!!) some columns are quoted - god with them, let it be (but not specially!).
2. When I focus, and then defocus values, they become unquoted :)

**Comment by plotn** [comment]
![dbeaver_export_add](https://user-images.githubusercontent.com/11477081/185645870-0f89e752-8cb7-4b0a-846d-6ce4a8b0a174.png)

**Comment by plotn** [comment]
And it finally fails.... :(
so data export (the excellent part of dbeaver need to be refactored, i think)
![dbeaver_export_add2](https://user-images.githubusercontent.com/11477081/185646903-d1eb2976-8ec0-45d5-9c85-f002acf16d2b.png)

**Comment by plotn** [comment]
and (i'm sorry) mostly oracle's word's users dont want to see "singed binary integer" but the "number" (or number(x), or (x,y).
But most ETL scenarios build on "we dont believe the source, let it be maximum number", e.g. just number

**Comment by serge-rider** [comment]
Most problems with columns naming and quoting were already resolved in 22.2.2.

@plotn could you check it one more time? What problems are still there?

**Comment by E1izabeth** [comment]
All mentioned in [my comment](https://github.com/dbeaver/dbeaver/issues/17348#issuecomment-1217087731) issues are still actual.
Mentioned in this issue behavior about window flickering is reproducible too.

**Comment by serge-rider** [comment]
Fixed.

Also redundant buttons were removed + auto-assign button was moved to the bottom.
