### ISSUE TITLE
Directory .dbeaver added on all open projects in Eclipse

### ISSUE THREAD

**Issue by tvogel8570** [dbeaver/dbeaver#17349]
### Description

Using dbeaver ( 22.1.4.202208051447) in Eclipse (2022-06 (4.24.0) Build id: 20220609-1112). 

Periodically  dbeaver creates a directory .dbeaver and project-settings.json in every open project.  This behavior is undesired because not all developers use dbeaver and I have to cleanup before committing to git.

My workaround is to add .dbeaver to the master .gitignore

### DBeaver Version

22.1.4.202208051447

### Operating System

Windows 10

### Database and driver

NA

### Steps to reproduce

Open workspace with multiple projects that do not have .dbeaver directory.  At some point (unsure of duration) a .dbeaver directory will be created.

**Comment by serge-rider** [comment]
Can't reproduce. PErhaps some special action in DBeaver causes this behavior. 
@tvogel8570 do you have any hints?

**Comment by tvogel8570** [comment]
Give me a couple of days to see if I can produce a minimal reproduction.

**Comment by uslss** [comment]
@tvogel8570 do you have any updates?

**Comment by tvogel8570** [comment]
I have a large project that has this behavior but am unable to reproduce on a smaller / test project.  You can go ahead and close as the workaround is acceptable.

**Comment by srolawson** [comment]
Which version of the app has been fixed? When will it become the latest eclipse plugin? Thanks!
