### ISSUE TITLE
trigger not showed on a view ddl

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#17350]
### Description

open ddl tab on view. You cannot see create trigger code in creation script

### DBeaver Version

22.1.4

### Operating System

windows 10

### Database and driver

Postgresql 14.2

### Steps to reproduce

1. Create view
CREATE OR REPLACE VIEW v
AS SELECT...
2. create trigger on this view
create trigger trg_v_change instead of...
3. open ddl tab on view v. You cannot see create trigger code in creation script

**Comment by uslss** [comment]
thanks for the report
