### ISSUE TITLE
open current sql script always opens the last sql-script

### ISSUE THREAD

**Issue by ironbirdie** [dbeaver/dbeaver#17359]
### Description

First, I have to say, what great tool dbeaver is. 

I have been using it a while, i keep finding interesting features.
However I've recently upgraded to the lastest version 22.1.4 and opening the recent sql script from a connection.
Always opens the last recent sql-script of all connections instead of the one associated with the connection.

The last recent sql-script is then also reassociated with the current connection.

Has this functionality changed or is there a new preference that I can select (i don't find any)

Thanks in advance for your response and in any case thanks for a great product!

Bart

### DBeaver Version

Community edition Version 22.1.4.202208051447

### Operating System

Windows 10

### Database and driver

Postgresql v 13
Postgresql JDBC driver 42.2.5

### Steps to reproduce

1. multiple postgresql connections.
2. sql-scripts associated with each of them.
3. select a connection
4. right-click on a connection and select "sql-scripts > recent sql script" or press Ctrl+Enter
--> this always opens the same script (the last one) and associaties it with the current connection. 

Before it opened the most recent script associated with the connection.

**Comment by E1izabeth** [comment]
Thanks for the report.
The issue should be fixed in #17316.
The fix will be available in DBeaver 22.1.5.
