### ISSUE TITLE
[Redshift] - Generating DDL on materialized view doesn't include AUTO REFRESH setting

### ISSUE THREAD

**Issue by match-gabeflores** [dbeaver/dbeaver#17354]
### Description

In Redshift, If I generate the DDL on a materialized view, it doesn't include the auto refresh setting (YES/NO).
Edit: I'm using **Okta Single Signon (SSO) for authentication** and I made a _copy_ of the Redshift driver.

![image](https://user-images.githubusercontent.com/286903/184663880-ab47f526-4401-4bb6-b0bb-51ede71bda71.png)

AWS Docs
https://docs.aws.amazon.com/redshift/latest/dg/materialized-view-create-sql-command.html

This view currently returns: 
```
CREATE MATERIALIZED VIEW public.vwdeviceplatform AS 
	SELECT col1
        from mytable
```

It should return 
```
CREATE MATERIALIZED VIEW public.vwdeviceplatform 
AUTO REFRESH YES   <-- this piece missing
AS 
	SELECT col1
        from mytable

```

The setting can be gathered from this table
STV_MV_INFO

![image](https://user-images.githubusercontent.com/286903/184664428-b8dd1465-e39d-4c63-ba39-7312cb0e5d77.png)

### DBeaver Version

CE v22.1

### Operating System

Windows

### Database and driver

com.amazon.redshift.jdbc42.Driver

**Comment by uslss** [comment]
@match-gabeflores cannot reproduce it. Auto refresh clause is shown for the table where it is enabled. Could you check if the issue is reproducible for you against 22.1.5? t
![image](https://user-images.githubusercontent.com/31996417/187394961-f39743a8-1c90-4b1f-9884-47fbfcf52977.png)

**Comment by match-gabeflores** [comment]
Hi @uslss ,

I upgraded and can still reproduce it. But I left out one detail which appears to be the reason - I'm using Okta Single Sign-On for authentication and I'm using a _copy_ of the Redshift driver. 

When I connect to a different redshift cluster using login/password, this issue doesn't exist
When I connect to our main RS cluster using the copied driver with Okta SSO, the `auto-refresh` isn't shown. 

I believe this might be related to a couple of these issues related to copied drivers that I have seen before:
* https://github.com/dbeaver/dbeaver/issues/14039
* https://github.com/dbeaver/dbeaver/issues/14507

**Comment by emironovDB** [comment]
Hi @match-gabeflores, 

Could you provide the driver version that you use? 

Additionally please provide the output of the following query:
`select pg_get_viewdef(<view-id>);`

**Comment by match-gabeflores** [comment]
driver v2.0.0.7
see below screenshot. Note that the driver type says Postgres which I think is correct

![image](https://user-images.githubusercontent.com/286903/189147711-6e6ed29a-5cf8-43da-9db9-5797fed5c673.png)

output of 
`select pg_get_viewdef('globaldata.vwdeviceplatform', true)`

is like this (snipped the query). Note, `autorefresh on` is not present.
```
CREATE MATERIALIZED VIEW globaldata.vwdeviceplatform AS 

	SELECT *
	from foo
```

When I go on the DEV cluster (which doesn't use Okta SSO and is not a copy of the driver), the output correctly returns 

```
CREATE MATERIALIZED VIEW globaldata.vwdeviceplatform 
  AUTO REFRESH YES
AS 
...
```

**Comment by match-gabeflores** [comment]
hi @appleoddity, 

you helped verify a similar issue in https://github.com/dbeaver/dbeaver/issues/14039 (#14039), wondering if you can reproduce this error in your similar SSO/copied driver environment. 

steps would be: 
1. Create a materialized view with `autorefresh on` attribute
2. then script out the ddl
3. the ddl should have autorefresh on

**Comment by uslss** [comment]
@match-gabeflores is this issue still actual for you?

unfortunately, we've got no possibility to test it with OKTA SSO. Also, I cannot reproduce the issue just with driver copy :(

**Comment by match-gabeflores** [comment]
Unfortunately it still is an issue. 

I tested it just with the latest dbeaver and without creating a copy of the driver and the issue persists. 

Let me know if I can provide additional logs. 

pinging @appleoddity again if he can help

**Comment by LonwoLonwo** [comment]
The strangest thing is that `select pg_get_viewdef()` returns your incorrect value.  
We are using the result of this query, not changing it for the Redshift.
So it looks like a database issue.
Ok, strange suggestion, could you please check this version?

`SELECT pg_catalog.pg_get_viewdef('globaldata.vwdeviceplatform'::regclass::oid, true);`

**Comment by LonwoLonwo** [comment]
And this one too, please:
`select view_definition from information_schema.views where table_name = 'view_name';`

**Comment by match-gabeflores** [comment]
both are missing the autorefresh. 

SELECT pg_catalog.pg_get_viewdef('globaldata.vwdeviceplatform'::regclass::oid, true)
```
CREATE MATERIALIZED VIEW globaldata.vwdeviceplatform AS 
	SELECT ...
	 
```

select view_definition. this returns a null for the field (presumably bc of permissions?). my coworker ran it and didn't have the autorefresh.
```
CREATE MATERIALIZED VIEW globaldata.vwdeviceplatform AS
	SELECT ...


```

**Comment by match-gabeflores** [comment]
Hmm, well I tried on the Redshift Editor V2 and I get the same issue so this doesn't appear to be DBeaver specific. This can prob be closed for the time being.

**Comment by LonwoLonwo** [comment]
Unfortunately, I can't find any info about auto refresh status in the system tables. 
information_schema.views and pg_views do not contain it.
We can reopen this ticket if new information arrives.

**Comment by match-gabeflores** [comment]
A bit more context here:

From an [answer from the AWS folks](https://repost.aws/questions/QUVNcJX9TYQMSo0lDS2uMcEQ#ANoVT5LGLSToKCuoO1Rm4qrw):
```

In this context, please note that STV_MV_INFO table contains DDL used while creating the materialized view.

If the materialized view is created with below command:

—> CREATE MATERIALIZED VIEW globaldata.vwdeviceplatform AS select xyz..

After creating the mv we can turn on AUTO REFRESH Using -

—> ALTER MATERIALIZED VIEW globaldata.vwdeviceplatform AUTO REFRESH YES;

[+] https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_MATERIALIZED_VIEW.html

Now even if autorefresh=’t’ in STV_MV_INFO table, the view definition will be same as below:

CREATE MATERIALIZED VIEW globaldata.vwdeviceplatform AS select xyz..

Same goes with pg_get_viewdef function. So, in both the cases you will get the DDL used while creating the mv only.
```

Apparently the view on prod was created first and then altered with autorefresh. That's the reason the autorefresh doesn't show up in info_schema. I tested by creating another view with autorefresh in the creation script and information_schema.views now contains the AutoRefresh attribute. 

Scripting this new view from Dbeaver now yields below which isn't entirely correct but I'll take it. Thanks all:
```
-- shworkdb.vwdeviceplatform_deleteme source

CREATE OR REPLACE VIEW shworkdb.vwdeviceplatform_deleteme
AS -- globaldata.vwdeviceplatform source

CREATE MATERIALIZED VIEW shworkdb.vwdeviceplatform_deleteme
  AUTO REFRESH YES
AS 
	SELECT

```

**Comment by LonwoLonwo** [comment]
Thanks for the investigation @match-gabeflores
