### ISSUE TITLE
Menu placed upside down

### ISSUE THREAD

**Issue by javaanddonet** [dbeaver/dbeaver#17356]
### Description

Menu placed upside down.

### DBeaver Version

22.1.4.202208051447

### Operating System

macOS Big Sur 11.4

### Database and driver

MySQL 5.7

### Steps to reproduce

1. Chose a mysql connection, and double click it, open this connection.
2. Select Users menu, and double click it, open this menu.
3. On the right side, chose one user and double click it, open this user.
4. Click "Schema Privileges" tab, and then you can see the menu in the top right corner placed upside down.
5. Try to switch back and forth the tab "Properties" and "Schema Privileges", and check the menu in the top right corner.

**Comment by javaanddonet** [comment]
![dbeaver-bug](https://user-images.githubusercontent.com/35132479/184825144-b822478b-c217-4345-b3e0-730bf3f0b50f.png)

**Comment by uslss** [comment]
thanks for the report.
seems to be similar to #10945
