### ISSUE TITLE
{blog-postapi-url}/../wp-admin/post.php?action=edit&post={post-id}

### ISSUE THREAD

**Issue by NikolayTach** [dbeaver/dbeaver#17364]
### XML Parsing Error: not well-formed
Location: file:///home/mint/dbeaver/bundles/gora.xml
Line Number 15, Column 57:
`{blog-postapi-url}/../wp-admin/post.php?action=edit&post={post-id}`

### DBeaver Version

22.1.0

### Operating System

MintOS 11.2.0

### Database and driver

`Framework Laptop 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz`

### Steps to reproduce

`curl https://dbeaver.io`

**Comment by E1izabeth** [comment]
Please, describe in more details what are you trying to do, some steps to reproduce would be helpful.

**Comment by uslss** [comment]
there has been no update on the issue for a long time. If it is still actual - feel free to reopen it
