### ISSUE TITLE
Refresh table properties layout after table creation

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#17360]
### Description

It's [almost impossible to change](https://stackoverflow.com/a/68716746) the table engine in said DBMS, but the corresponding combo box in the Entity Editor is expandable even if a table is already persisted.

### DBeaver Version

Ultimate, devel branch

### Operating System

Pop!_OS 22.04

### Database and driver

ClickHouse 22.1.3.7
ClickHouse JDBC Driver clickhouse-jdbc 0.3.2-patch11 (revision: 27f8951)

**Comment by LonwoLonwo** [comment]
Small note:
Table engines are editable only in one case - after the table creation in DBeaver, then the table tab is still open.
Table engines are not editable for persisted tables.

![2022-08-29 11_37_32-DBeaver Ultimate 22 2 0 - _language5](https://user-images.githubusercontent.com/45152336/187160706-6f1f8a19-e29a-449e-a894-a6d2b2e93a89.png)

This is the generic problem about updatable/editable fields and properties refreshing.

**Comment by LonwoLonwo** [comment]
As I said - this is generic problem. We need to refresh properties after not persisted -> persisted changes. 
So I renaming this ticket.

**Comment by serge-rider** [comment]
Now we recreate editor controls on persistence state change
