### ISSUE TITLE
Add a Use SSL option for ClickHouse

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#17363]
It would be great if we had a `Use SSL` button on the ClickHouse Connection Page, just like in InfluxDB:

![image](https://user-images.githubusercontent.com/26031301/184877411-266c879b-0393-4a90-a8f7-4a830dbfa0ef.png)

**Comment by Destrolaric** [comment]
Probably we should discuss adding that button for other databases. Users, mostly, don't need to change anything in SSL configuration.
