### ISSUE TITLE
Edit Driver Setting - URL Template overwritten between connections

### ISSUE THREAD

**Issue by pjam889** [dbeaver/dbeaver#17376]
### Description

I use two different connections to Amazon Redshift:
Connection 1) Authenticates with AWS Single Sign On, requires this URL template: jdbc:redshift:iam://{host}:{port}/{database}
Connection 2) Autheticates with user/passsword, requires this URL template:          jdbc:redshift://{host}:{port}/{database}

The issue is that "URL Template" setting is not independent, if I add "iam:" to 1, then is is also added to 2 and connection to 2 stops working until I adjust again URL template value. 

The unexpected behaviour makes it tedious to connect to Redshift using differente authentication methods. Additionally it took some time to detect the issue and find the workaround.

### DBeaver Version

CE 22.1.4

### Operating System

Windows 10

### Database and driver

Redshift 
JDBC 4.2–compatible driver version 2.1 and AWS SDK driver–dependent libraries

### Steps to reproduce

1. Setup Redshift user/password connection and try connection, it should work.
2. Setup Redshift SSO connection, you will need to add "iam:" to the URL template, try connection, it should work.
3. Try to connect again with user/password, if fails because "iam:" will be added to the URL template although it is not needed and expected.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
Now you can switch connection configuration type to connect by URL and paste your url there directly without editing driver url template.
