### ISSUE TITLE
Control + Left Click on Foreign Key to View the Row

### ISSUE THREAD

**Issue by numeralnathan** [dbeaver/dbeaver#17379]
**Is your feature request related to a problem? Please describe.**

Open a table and view its data.  Some of the columns are foreign keys.  I currently copy the key and open the corresponding table.  I then filter for that key.

**Describe the solution you'd like**

Please let me Control + Left Click on a key and have DBeaver open the corresponding table with a filter so that I see that row.

**Comment by jetzerb** [comment]
[This feature already exists](https://dbeaver.com/docs/wiki/Navigation/#navigate-foreign-keys---referencing-tables).  Populated cells that are foreign keys have a clickable "external link" icon 
![image](https://user-images.githubusercontent.com/36859020/185950539-08a7a005-c120-49ec-bb0b-ddf4360d3be2.png). When you click it, the row in the referenced table will open.  You can then use the navigation buttons to move back to the original row.

> Note that if you make DDL changes such as creating a foreign key, you'll need to disconnect & reconnect to the server before DBeaver will recognize the new/changed object(s).

Demonstration (on MSSQL):
![image](https://user-images.githubusercontent.com/36859020/185951561-b8b61dae-e1bf-4b89-bcad-e7aac4412bf6.png)
Clicking on the "external link" icon takes you to the referenced row, and the "back" button is then enabled:
![image](https://user-images.githubusercontent.com/36859020/185951805-19140997-c131-40d8-8f2e-4990b258fab4.png)
Clicking on the back button returns you to the original row, and the "forward" button is then enabled:
![image](https://user-images.githubusercontent.com/36859020/185952062-7e5624d9-b3d1-43d1-827b-321c69ed8bf3.png)

**Comment by numeralnathan** [comment]
Thank you!  I am blind.

This works for @OneToOne and @ManyToOne.  What about @OneToMany?  The column doesn't exist in one of the tables.

Oh wait, I found it.  If I right click on the row header > Navigate > References, it shows a list of related tables.  This just showed me a bug in my schema.  A table is missing a foreign key constraint.
