### ISSUE TITLE
Script to connection associations lost in v. 22.1.4.202208051447

### ISSUE THREAD

**Issue by ionel-sirbu-crunch** [dbeaver/dbeaver#17381]
### Description

Whenever I select a connection in the left hand pane & press F3 for opening the SQL script associated with that connection (I usually have just one such script), instead of opening it, I get the pop-out window with all the scripts from all connections in there.
Since that association used to work fine before, I never bothered naming the scripts in accordance with the connection, so now I can only see `Script-xx.sql` in there, which makes it pretty much impossible to identify which script belongs to which connection.

Is there any way I could sort this out? Any help is much appreciated!

Many thanks,
Ionel

### DBeaver Version

22.1.4.202208051447

### Operating System

Windows 11 (v. 21H2 OS Build 22000.778)

### Database and driver

MySql 5.x com.mysql.jdbc.Driver

### Steps to reproduce

1. Select a connection in the `Database Navigator` pane
2. Press F3
3. Notice that instead of opening the associated script or listing just the scripts associated with that connection if there's more than one, all the scripts from all connections are listed.

**Comment by Destrolaric** [comment]
Hi, it is fixed in the scope of https://github.com/dbeaver/dbeaver/issues/17316. The release version with the fix should be available on Monday. For now, you can use an earlier version of DBeaver https://dbeaver.io/files/

**Comment by ionel-sirbu-crunch** [comment]
> Hi, it is fixed in the scope of #17316. The release version with the fix should be available on Monday. For now, you can use an earlier version of DBeaver https://dbeaver.io/files/

Sweet, thanks for the prompt reply! ❤️ And apologies for opening a duplicate - I did do a search by `script` before, but I couldn't spot anything similar after taking a quick gander. 🤷‍♂️
