### ISSUE TITLE
DBeaver does not allow anything after "jdbc:sqlserver://" in MS SQL Server URL template, breaking sqlexpress and localdb connections

### ISSUE THREAD

**Issue by PoseidonEnergy** [dbeaver/dbeaver#17380]
### Description

In DBeaver 22.1.1, the SQL Server URL template is something like

`jdbc:sqlserver://;serverName=localhost;databaseName=testdb`

For a lot of people, this isn't a problem, because they can just use the `serverName` parameter and port to connect via TCP/IP.
However, this breaks support for **sqlexpress** and **localdb** connections, which **cannot** be connected to with the `serverName` parameter. For these connections, the host must be inserted right after the `jdbc:sqlserver://` bit. For example, a **sqlexpress** connection string looks like this:

`jdbc:sqlserver://localhost\sqlexpress;databaseName=testdb;integratedSecurity=true;`

Because DBeaver does not allow inserting anything after the `jdbc:sqlserver://` bit, **sqlexpress** and **localdb** connections don't work.

Please see this StackOverflow answer for a little more info: https://stackoverflow.com/a/40830281

This is also related to (but different than) https://github.com/dbeaver/dbeaver/issues/4243

This should be a very easy fix anyway.

### DBeaver Version

Community Edition 22.1.1

### Operating System

Windows 10 Enterprise

### Database and driver

MS SQL Express & localdb (e.g. `localhost\sqlexpress` or `localdb\testdb`)
com.microsoft.sqlserver:mssql-jdbc:RELEASE [9.2.0.jre8]
com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE [9.2.0.x64]

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
@PoseidonEnergy please, add instance name to the host. Like this

![image](https://user-images.githubusercontent.com/28875055/189209469-e58f6e7e-9c66-415d-9168-9ac46124beb8.png)

As far as I see we generate connection url according to this template https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15

Let me know if it helps.

**Comment by E1izabeth** [comment]
You should do the same in other Database IDEs, for example, in Microsoft SQL Management Studio:

![image](https://user-images.githubusercontent.com/28875055/189310473-d2eb67ae-9ee1-49d2-8cc8-7df1bdf86e72.png)

**Comment by PoseidonEnergy** [comment]
> @PoseidonEnergy please, add instance name to the host. Like this
> 
> ![image](https://user-images.githubusercontent.com/28875055/189209469-e58f6e7e-9c66-415d-9168-9ac46124beb8.png)
> 
> As far as I see we generate connection url according to this template https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15
> 
> Let me know if it helps.

I have tried that, and it still adds "serverName=.\sqlexpress" to the connection string.

The connection string should look like this: `jdbc:sqlserver://.\sqlexpress;databaseName=master;integratedSecurity=true;`

See a screenshot of my attempt below:

![servername](https://user-images.githubusercontent.com/109360495/189421042-a5ce9b87-5868-4ac6-b641-cb04474dc938.PNG)

I also can confirm that ".\sqlexpress" works in SSMS:

![namedinstance](https://user-images.githubusercontent.com/109360495/189421872-9aa63ca0-b120-43ea-81e2-7ee5035af3ae.png)

**Comment by E1izabeth** [comment]
Thank you for explanations.

**Comment by E1izabeth** [comment]
Using `localhost` or windows machine name instead of `.` works for me. Maybe you could try using it as a temporary workaround.

**Comment by PoseidonEnergy** [comment]
@E1izabeth I have tried `localhost` and my machine name and I get the same error. I take it from your screenshots that you are successfully able to connect to a SQLEXPRESS instance with DBeaver. Is this true?

**Comment by E1izabeth** [comment]
Yes, I'm able to successfully connect to sqlexpress running on my local machine.
