### ISSUE TITLE
"Choose SQL script" dialog displays to many scripts

### ISSUE THREAD

**Issue by KLIS-IT** [dbeaver/dbeaver#17386]
### Description

Since upgrade to Version 22.1.4 "Choose SQL script" dialog displays to many scripts.
Also scripts related to other Folders as current select are displayed.
For example I press F3 on a PostgreSQL DB connection before 22.1.4 only scripts for this connection were shown.
Now also connections to Oracle DB shown but icon for PostgreSQL is displayed before script name.
Once ticking "Select scripts for all connections" same set of scripts but now with correct icons are shown.

### DBeaver Version

22.1.4.202208051447

### Operating System

Win10, Version 21H2

### Database and driver

Database independend

### Steps to reproduce

1. expend tree down to e.g. a PostgreSQL connection
2. press F3 to show related scripts
3. all existing scripts are shown with wrong DBMS icon (--> unexpected)
4. tick "Select scripts for all connections" checkbox and correct icons are shown

**Comment by Destrolaric** [comment]
Hi, it is fixed in the scope of https://github.com/dbeaver/dbeaver/issues/17316. The release version with the fix should be available on Monday. For now, you can use an earlier version of DBeaver https://dbeaver.io/files/
