### ISSUE TITLE
DBeaver can't delete primary key contraint

### ISSUE THREAD

**Issue by All3xJ** [dbeaver/dbeaver#17389]
### Description

I can't delete primary key with DBeaver, it says

errno 150 primary key is not correctly formed.

If I execute a script with `set foreign_key_checks=off` and then do it again, it gives me that error again.

If I do it via mysql commandline, (disabling foreign key checks too), doing the SAME query as dbeaver (`ALTER TABLE dbname.tablename DROP PRIMARY KEY; ` )it works....

Also, it seems bugged because even if I press refresh button, it still gives me incorrect db scenario. Only closing and reopening dbeaver finally gives me the correct db scenario just updated.

### DBeaver Version

Version 22.1.3.202207311845

### Operating System

ArchLinux

### Database and driver

Server version: 10.5.15-MariaDB-0+deb11u1 Debian 11

Driver: InnoDB

### Steps to reproduce

I tried to delete the only one constraint (that has two ext ref), and then save, and gives me: `errno 150 primary key is not correctly formed.
`

Even if I disable foreign key checks, it still doesn't allow me to perform that operation.

Doing it manually via commandline works.

### Additional context

This is the output of `SHOW ENGINE INNODB STATUS` after dbeaver failed the command : https://hastebin.com/ucituyeyef.yaml

**Comment by E1izabeth** [comment]
Please, send the query which you see in the [Query Manager](https://dbeaver.com/docs/wiki/Query-Manager/) when trying to delete constraint.
EDITED: never mind, I see it

**Comment by Matvey16** [comment]
@All3xJ Thank you for the report. We will look what can be done with it.

**Comment by E1izabeth** [comment]
@All3xJ, could you send the contend which was in the provided hastebin (it's empty now) or at least the query which you see in the [Query Manager](https://dbeaver.com/docs/wiki/Query-Manager/) when trying to delete the mentioned constraint? Also table DDL will be helpful.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
