### ISSUE TITLE
dbeaver updates don't change the PROJECT_LOC variable to the new directory generated

### ISSUE THREAD

**Issue by ikodev** [dbeaver/dbeaver#17387]
### Description

Platform
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```
Dbeaver
```
Version 22.1.4.202208051447
```

Package Manager
```
Snap
```

Currently, my package manager snap is dealing all the updates of DBEAVER.

Dbeaver was targeting the `/home/user/snap/dbeaver-ce/203/` directory but a recent update has generated the `/home/user/snap/dbeaver-ce/204/` and symlinked it properly to the `/home/user/snap/dbeaver-ce/current/`directory.
**The problem is that the variable PROJECT_LOC still has a value targeting the 203 folder. All others variables have been properly updated.**

The issue causes the impossibility to use any SQL editor telling that the dbus process can't write into the directory 203 which is no more symlinked to the `current/` directory.

This is a huge problem currently.
I am looking for a way to edit the PROJECT_LOC value withing the tree files of linux because it's not an editable variable from DBEAVER settings.

Any help ?

Thank you a lot !

### DBeaver Version

22.1.4.202208051447

### Operating System

Ubuntu 20.04.4 LTS

**Comment by emironovDB** [comment]
@ikodev 

Please try reinstalling DBeaver 
And let me know if it helps

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
