### ISSUE TITLE
The saved sql statement should not be executed, which will lead to unforeseen losses

### ISSUE THREAD

**Issue by hktalent** [dbeaver/dbeaver#17393]
### Description

Prompt to save sql when exiting, for example:
UPDATE vuls.alipay_task_db_saves SET created_at=NOW();
UPDATE vuls.alipay_task_db_saves SET run_status=1;

After a few days, when the tool is started, the saved SQL statement will be executed again unexpectedly, which will cause my data to be irreparably lost.

### DBeaver Version

Version 22.1.3.202207240747

### Operating System

macOS

### Database and driver

mysql

### Steps to reproduce

Prompt to save sql when exiting, for example:
UPDATE vuls.alipay_task_db_saves SET created_at=NOW();
UPDATE vuls.alipay_task_db_saves SET run_status=1;

After a few days, when the tool is started, the saved SQL statement will be executed again unexpectedly, which will cause my data to be irreparably lost.

### Additional context

Prompt to save sql when exiting, for example:
UPDATE vuls.alipay_task_db_saves SET created_at=NOW();
UPDATE vuls.alipay_task_db_saves SET run_status=1;

After a few days, when the tool is started, the saved SQL statement will be executed again unexpectedly, which will cause my data to be irreparably lost.

**Comment by uslss** [comment]
@hktalent could you provide steps to reproduce or video with the issue? thanks in advance
