### ISSUE TITLE
Dump database - Next button disabled by default

### ISSUE THREAD

**Issue by sparrowme** [dbeaver/dbeaver#17390]
### Description

Next button is disabled by default with no indication user must click on an already checked item to cause it to enable.

See #16993 for different Next button issue

### DBeaver Version

Community Edition 22.1.4

### Operating System

Ubuntu 20.04 LTS

### Database and driver

MySQL 8

### Steps to reproduce

1. Right-click on a Database in the Database Navigator and then Tools -> Dump database

The context of the right-click CORRECTLY selects the database and database objects by default, however, the next button is disabled even though there is nothing "new" to click to begin the dump.
![image](https://user-images.githubusercontent.com/1423504/185465905-0ce79973-64b3-4153-b4e6-aac4773e7940.png)

User must either:
1. click the object(database) name itself, OR
2. uncheck and re-check the database option.
Either will result in the Next button activating.

## Expected behavior:

Enable the Next button by default when sufficient items are already selected in the dialog by default.

**Comment by sparrowme** [comment]
I did see the native client error, but did not consider it the cause... adding a default and going through the process again does in fact default the Next button to active.

I suspect it was unintentional to actually allow it to activate the way I introduce above.

Some fix may be helpful, otherwise feel free to close.

**Comment by LonwoLonwo** [comment]
Hello @sparrowme 

Is this issue still reproducible for you in the [latest DBeaver](https://dbeaver.io/download/) release?
Because I can not reproduce it.
Thanks.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
