### ISSUE TITLE
PostgreSQL数据库, bigint数据类型的字段保存后变为了int8, 希望更正

### ISSUE THREAD

**Issue by maxs-marcel** [dbeaver/dbeaver#17394]
### Description

<img width="733" alt="image" src="https://user-images.githubusercontent.com/65930792/185553278-26047640-2586-4a72-ae76-4626390e18c0.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/65930792/185553224-7599c816-8ebe-4313-ad89-f1c7b1f932de.png">

当我使用DataGrip工具进行查看时, 这个字段类型保存的没问题, 只是展示有问题, 希望官方更正.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/65930792/185553416-e194856e-3d07-40a3-950b-2021346d8a37.png">

### DBeaver Version

22.1.4

### Operating System

macOS Monterey 12.5.1

### Database and driver

DB: PostgreSQL 14.4
jdbc-driver: 
<img width="707" alt="image" src="https://user-images.githubusercontent.com/65930792/185553993-f8825981-d3fb-494c-a2c9-ccd3cd43a1d9.png">

**Comment by birdingman0626** [comment]
因为bigint就是int8啊..
