### ISSUE TITLE
CTRL+ENTER error statement when running SQL?

### ISSUE THREAD

**Issue by google007049** [dbeaver/dbeaver#17392]
### Description

I always use it well if I thank you well.

Run ctrl+enter when running QUERY. There is a problem in some cases as below.
1. If there is a comment in the query, an error occurs when the query is included and executed.
2. If the block is processed except for comment, it will be inquired without errors.
3. If you run directly on the line below without block processing, an error will occur.

Please refer to the video.

https://user-images.githubusercontent.com/58673078/185516773-c3e250d2-0599-472b-9ba3-e9a7469d551c.mp4

### DBeaver Version

Community Edition 22.1.4.202208051447

### Operating System

Windows10

### Database and driver

Oracle 11g

**Comment by uslss** [comment]
@google007049, unfortunately, cannot reproduce.
Could you provide logs? https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by google007049** [comment]
Thank you for your answer.
If you watch the video, it will be easy to reproduce, but I'm sorry to hear that it's hard.
For example, I'm going to tell you something

### **select sysdate from dual ; -- sysdate**


In this sentence, an error occurs when you perform Ctrl+enter with a prompt after select sysdate from dual; --sysdate.
However, if you block only select sysdate from dual; or run ctrl+enter with a prompt after dual; it is queried as normal.

I think it should be checked even if there is a comment behind the sql statement.




### **All of the captures below are run in line 1 of the SQL editor.**

**case 1)**
![image](https://user-images.githubusercontent.com/58673078/186330155-32e51963-b55b-4b20-b24d-483c4b36861e.png)

**case 2)**
![image](https://user-images.githubusercontent.com/58673078/186330278-6d858eb2-f9d4-4bae-8228-85090e696f28.png)

**case 3)**
![image](https://user-images.githubusercontent.com/58673078/186330612-c01e573e-2f37-48a3-8e1c-383063cf0fe7.png)

**case 4)**
![image](https://user-images.githubusercontent.com/58673078/186330749-3a7e9d1a-796a-44a3-8eaa-96cef4bcf518.png)




Due to this problem, you should either delete the comment and execute the sql statement, or move the profile to check it.

**Comment by LonwoLonwo** [comment]
Yeah, I see.

`SELECT 1; --select `

Do not work in Postgres too.
We need to handle this case.

Thanks for the bug report.

**Comment by E1izabeth** [comment]
Connected to #17774

**Comment by google007049** [comment]
수고가 많습니다.
해당 문제에 대해 수정해주셔서 감사합니다.
테스트했더니 잘 작동하고 있습니다.
잘 사용하도록 하겠습니다.




-----Original Message-----
