### ISSUE TITLE
Support TiDB

### ISSUE THREAD

**Issue by Icemap** [dbeaver/dbeaver#17396]
**Is your feature request related to a problem? Please describe.**

Add TiDB support.

**Describe the solution you'd like**

- Create TiDB type database
- At the database tab, should show `sequence`, and hide `triggers`, `events`, and `procedures`.

**Describe alternatives you've considered**

**Additional context**

<img width="679" alt="image" src="https://user-images.githubusercontent.com/26212551/185597247-bb6ff48d-e311-4a9d-88aa-b699a3dd08fc.png">
<img width="679" alt="image" src="https://user-images.githubusercontent.com/26212551/185597281-ec7ab79c-a28f-4569-a67a-6a1703300ed2.png">

**Comment by greenpean** [comment]
Which version will plan to release?

**Comment by E1izabeth** [comment]
It's not planned to some release as we're waiting for the response on the PR from contributors.

**Comment by Icemap** [comment]
I'll give feedback once I can use the Windows device.
