### ISSUE TITLE
22.1.4.202208051447 Update table structure refresh and restore again

### ISSUE THREAD

**Issue by bankuaizhuan1** [dbeaver/dbeaver#17397]
### Description

创建表格，新建一个表索引，删除索引，刷新表格，索引又还原了？连续几次都不行，断开连接，再次链接，再次删除才生效

Create a table, create a new table index, delete the index, refresh the table, the index is restored? If it doesn't work several times in a row, disconnect it, link it again, and delete it again to take effect.

### DBeaver Version

22.1.4.202208051447

### Operating System

win10

**Comment by uslss** [comment]
@bankuaizhuan1 what database do you use? video with the issue also would be very helpful

**Comment by bankuaizhuan1** [comment]
mysql 数据库 8.0 ，视频的话等我抽时间录一下

**Comment by uslss** [comment]
still cannot reproduce the issue

https://user-images.githubusercontent.com/31996417/187398206-aa32a703-62a8-485b-89d3-f50590944bb9.mp4

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
