### ISSUE TITLE
Insufficient info in the "Error connecting to datasource" window on startup.

### ISSUE THREAD

**Issue by Hermholtz** [dbeaver/dbeaver#17395]
### Description

When DBeaver starts, it displays the error that it can't connect to a datasource. But it doesn't tell which one it can't connect to. I have several sources, and some of them may be inaccessible (because e.g. a VPN is required or a VM needs to be brought up). Either way, it would be very useful to know which data sources DBeaver complains about, and if it complains about one or more.

Thank you.

![image](https://user-images.githubusercontent.com/15248889/184898777-c93487c6-8749-410d-a125-48ee5c65fb2e.png)

### DBeaver Version

Community Edition 22.1.4

### Operating System

Windows 10 fully updated

### Database and driver

Multiple, irrelevant to the issue.

### Steps to reproduce

1. Configure working data sources.
2. Make some of them inaccessible (e.g. by shutting down their server(s)).
3. Exit DBeaver.
4. Start DBeaver again.

**Comment by E1izabeth** [comment]
Thank you for suggestions.

**Comment by serge-rider** [comment]
Connection name was added to the error message (it is the error message from SQL editor)
