### ISSUE TITLE
Renaming a Stored Procedure or Function

### ISSUE THREAD

**Issue by mauroian** [dbeaver/dbeaver#17403]
It should be possible to rename a Stored Procedure or Function by right-clicking on it in the Database Navigator tree (as it happens for tables or views).

**Comment by LonwoLonwo** [comment]
Hello @mauroian 

What database do you use?

**Comment by mauroian** [comment]
I use SQL Server.

Thanks.

**Comment by uslss** [comment]
thanks for the suggestion
