### ISSUE TITLE
After change a value in reultset the "Save" button is not enabled

### ISSUE THREAD

**Issue by renezito** [dbeaver/dbeaver#17419]
### Description

I execute my SQL, in resultset I change a value and the button "Save" in the lower left corner
![20220822 Error dbeaver 22 1 5-botton save no se habilita](https://user-images.githubusercontent.com/37661233/185960508-1aff46a6-67da-40b4-be73-826c018ff4e0.jpg)
.

### DBeaver Version

22.1.5

### Operating System

Windows 10 Pro

### Database and driver

It's irrelevant for this bug, but I indicate it:
Oracle 12c
Oracle JDBC version 12.2.0.1

### Steps to reproduce

1. Execute a SQL (SELECT)
2. In resultset change a value
3. Button "Save" is not enabled

**Comment by renezito** [comment]
It's very rare.  I execute again the same SQL, change a value and the button "Save" is enabled.... 
Please check it... more than one time.  You can see the imagen I posted that shows the button is not enabled.
Thanks

**Comment by uslss** [comment]
@renezito unfortunately, cannot reproduce it.
Probably some special steps are needed. Video with the issue will be very helpful.
![dbeaver_G83kp847BC](https://user-images.githubusercontent.com/31996417/186159957-697084a9-d449-4c2c-b0ea-0167036dcc5a.gif)

**Comment by renezito** [comment]
Thanks for ur quickly answer.  As I said, then I execute again the SQL and chage a value, the button was enabled.  And, as you say, some special steps are needed.  Please close this issue.
