### ISSUE TITLE
Can't change SRID for BLOB columns with geometry data

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#17411]
### Description

If the blob system contains geometry data it is possible to change view format to geometry and select the SRID, but on the actual map the SRID will be selected as simple and can't be changed.

### DBeaver Version

22.1.5

### Operating System

Win 10

### Database and driver

SQLite

### Steps to reproduce

1. Enter geometry data into Blob column e.g. `POINT (10 10)`
2. Change the column format to geometry
3. Cnange the data presentation from grid to spatial
4. Try to cange the SRID

**Expected:** The SRID is changed
**Actual:** The SRID can't be changed form Simple

![dbeaver_l6Q2ypxDo5](https://user-images.githubusercontent.com/82543000/185873350-30b96474-fd35-4882-a29c-84f0e1bb664e.gif)

### Additional context

NULL

**Comment by ShadelessFox** [comment]
Not reproducible against PostgreSQL:

```sql
select st_point(30, 60)::bytea;
```
