### ISSUE TITLE
Old link to Db2 Driver documentation

### ISSUE THREAD

**Issue by igor2x** [dbeaver/dbeaver#17428]
### Description

The problem is in DBeaver Community Edition 22.1.5 at Db2 Driver there is link to old end-of-life database v11.1. This is the problem. Solution is to update link to latest and officially supported v11.5 database.

### DBeaver Version

Community Edition 22.1.5

### Operating System

Windows 10

### Database and driver

Database name and JDBC driver I am using is irrelevant to this problem.

### Steps to reproduce

1. In **Database Navigator** right click to Db2 database connection.
2. In **Connection settings** click on **Driver properties**.
3. At bottom there is link **Driver documentation**
![image](https://user-images.githubusercontent.com/10895030/186081473-18d77506-7aeb-49ef-bd99-80d16aa8d400.png)
Problem appears. This link points to Db2 v11.1 documentation: https://www.ibm.com/docs/en/db2/11.1?topic=pdsdjs-common-data-server-driver-jdbc-sqlj-properties-all-database-products
Db2 v11.1 is end of life since April this year: https://www.ibm.com/support/pages/db2-distributed-end-support-eos-dates

Update link to v11.5 database version:
https://www.ibm.com/docs/en/db2/11.5?topic=pdsdjs-common-data-server-driver-jdbc-sqlj-properties-all-database-products

Note: The only difference in link is that DBeaver points to "11.1", but the latest is "11.5".

**Comment by igor2x** [comment]
I have tested this little bit more and I see IBM supports "latest" link which is independent of version number and always displays help for the latest version.

I suggest to change current link:
https://www.ibm.com/docs/en/db2/11.1?topic=pdsdjs-common-data-server-driver-jdbc-sqlj-properties-all-database-products

to "latest" link:
https://www.ibm.com/docs/en/db2/latest?topic=pdsdjs-common-data-server-driver-jdbc-sqlj-properties-all-database-products

Currently above "latest" link redirects to:
https://www.ibm.com/docs/en/db2/11.5?topic=pdsdjs-common-data-server-driver-jdbc-sqlj-properties-all-database-products

but this is good news, because when new Db2 version is released it will automatically redirect to new link an DBeaver will automatically get new link and so this "bug" should be needed to fix again.

**Comment by E1izabeth** [comment]
Thank you for investigation, @igor2x!
