### ISSUE TITLE
Update Db2 LUW JDBC driver to version v11.5.7.0

### ISSUE THREAD

**Issue by igor2x** [dbeaver/dbeaver#17427]
**Is your feature request related to a problem?**
In DBeaver Community Edition v22.1.5 on Windows 10 there is 3 years old JDBC driver for Db2 v11.5.0.0 bundled in DBeaver which is pretty old. I need to manually download the latest JDBC and manually import it into DBeaver and I need to help my coworkers to do the same, which is little bit annoying.

**Describe the solution you'd like**
Please include the latest Db2 v11.5.7.0 driver which has many bug fixes and new features.

**Steps to reproduce**
1. In DBeaver from menu **Database** select **Driver Manager**.
2. Click on icon in front of **DB2** to expand.
3. Select **DB2 LUW** and **Edit** button.
4. Click on **Libraries** tab. There is displayed com.ibm.db2:jcc:RELEASE [11.5.0.0].
5. If we look to official IBM JDBC driver web page: https://www.ibm.com/support/pages/db2-jdbc-driver-versions-and-downloads at the near top of web page there is table with caption **DB2 Version 11.5**. The driver included in DBeaver is _DB2 level:_ **v11.5 FP0 (GA)** (this is equal to v11.5.0.0) with version: 4.26.14. This is 3 years old JDBC driver.
6. Please bundle DBeaver with the latest JDBC driver with _DB2 level:_ **v11.5 M7 FP0** (which is v11.5.7.0) and _Driver version:_ 4.31.10 which was released in December 2021 and I am using it for few months without any issue.

**Comment by uslss** [comment]
#17428

**Comment by igor2x** [comment]
Today I have upgraded DBeaver to 22.2.2.202210092258 (info from Help | About).

1. Database | Driver Manager.
2. Select DB2 | DB2 LUW and Edit button.
3. Libraries tab and click on Download/Upgrade.
![image](https://user-images.githubusercontent.com/10895030/195290920-550c10dd-b109-4d38-b51b-e872785af14d.png)
and dialog opens:
![image](https://user-images.githubusercontent.com/10895030/195291097-94f242a6-2f08-41c0-b76d-a20313ed35da.png)

This is obviously still and old driver version 11.5.0.0 (the problem). But I expect to get 11.5.7.0 like fix in this problem report should provide and milestone 22.2.2 promises.

Then I can continue and download the proposed driver and then connect to some Db2 database and test the JDBC driver version with SQL:
```
SELECT
CLIENT_PRDID
AS JDBC_VERSION
FROM
TABLE(SYSPROC.MON_GET_CONNECTION(SYSPROC.MON_GET_APPLICATION_HANDLE(), -1))

```

and SQL returns: JCC04260 so JDBC v4.26.x which is according to official JDBC driver web page: https://www.ibm.com/support/pages/db2-jdbc-driver-versions-and-downloads still three years old  JDBC driver for v11.5.0.0.

**Comment by uslss** [comment]
thanks for the report. new issue was created
