### ISSUE TITLE
SSL Mode = disabled required for successful connection, still working on other installations with SSL off.

### ISSUE THREAD

**Issue by leehach** [dbeaver/dbeaver#17425]
### Description

I don't think this is a bug. It is an unexpected behavior that I can't find information on.

I use DBeaver to connect to a PostgreSQL database. I've put in usual connection string info on the Main tab of the Connection configuration dialog. I've never done anything on the SSL tab for the connection to work. It is currently working on a Linux machine and a Windows machine using Community Edition 22.0.0.

I've just been issued a new Windows laptop and installed Community Edition 22.1.4. When I tried to connect to the same database, I kept getting "SSL error: Connection reset". I can connect to the server from the same laptop on the same wireless network using psql. In DBeaver, I had to go to the SSL tab, check Use SSL, and set the SSL mode to "disabled". Then the connection worked.

Is this due to a change in DBeaver between 22.0.0 and 22.1.4, or is it more likely a change in my university's network security? Why would psql work

### DBeaver Version

Community Edition 22.1.4

### Operating System

Windows 10

### Database and driver

1. Database name and version: PostgreSQL 10.15
2. JDBC org.postgresql:postgresql:RELEASE [42.2.25]

**Comment by iraidaa** [comment]
Hello @leehach,

This could have happened due to many different reasons. For example, the version of the Postgre driver has changed, the Postgre server settings have changed, or the DBeaver cryptography libraries have changed. 

Could you please send us the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.

**Comment by isgales** [comment]
hi, i have the same issue. here is the logs. @iraidaa 
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/12668753/dbeaver-debug.log)

**Comment by MarcoMartins86** [comment]
It's still happening on Version 24.0.3.202404211624, @leehach workaround worked.
