### ISSUE TITLE
Unable to turn off new version notification on startup

### ISSUE THREAD

**Issue by zalox** [dbeaver/dbeaver#17442]
Dear team,

I find it very annoying that I have to dismiss an "Update Available" dialog every time I start DBeaver. For most of my software I use the package manager in my distribution to update and it almost always is one version behind your latest, which is fine for me in most cases. I've scanned through the menus for a way to dismiss this dialog, but no luck. 

Is there a way to turn it off permanently, or does this need to be implemented?

**Comment by tomchiverton** [comment]
Preferences > User Interface > disable automatic update check

Suggest closing the issue

**Comment by zalox** [comment]
Thank you, I'm much happier now.

However, this option was hard to find.

As @tomchiverton mentioned, the option is under 
Preferences > User Interface > "General section" > disable automatic update check

I would have found it more easily if it were under 
Preferences > General > Install/Update.

I don't get why it is under User Interface.

That's my two cents, thank you for your help and your great tool.
