### ISSUE TITLE
Search string, hope to automatically remove the spaces on the left and right sides

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#17444]
DBeaver Enterprise
version info： 22.1.0.202206131757
When I input a string with spaces, there is no result, after removing the spaces there is a result, I hope to be able to automatically remove the spaces.
![image](https://user-images.githubusercontent.com/43258262/186310212-d373d955-fd38-457b-b264-c16bc6a6fd94.png)

**Comment by ShadelessFox** [comment]
Hello @chazhongbao,

What's the type of the `account` column? I assume it's a number?

**Comment by ghost** [comment]
no, It is a number of string type, I have tried inputting the number can be found, inputting the string can not。  The column is  varchar type

**Comment by ShadelessFox** [comment]
We don't want to trim strings since spaces are part of their data, and they may be important. Sorry.

If the column had a numeric type, it would be an option, since a number is only represented by `0..9`, excluding spaces.
