### ISSUE TITLE
Sql Server create new column will lost column description

### ISSUE THREAD

**Issue by j717273419** [dbeaver/dbeaver#17445]
### Description

Sql Server create new column will lost column description, when I create a new column in a table, I type a description for this column. but when I save the change. This column will lost. 

### DBeaver Version

Community 22.1.3

### Operating System

Windows 11

### Database and driver

SQL Server

com.microsoft.sqlserver:mssql-jdbc:RELEASE

9.2.0.jre8

### Steps to reproduce

1. create a new table from an sql server database.
2. create a new column into this table, and add a column description
3. save change.
4. reopen this table, you will find the column description has lost.

### Additional context

![image](https://user-images.githubusercontent.com/2731580/186322964-26cae993-1714-4939-ba82-3324563423a6.png)

**Comment by uslss** [comment]
thanks for the report
