### ISSUE TITLE
SQL Editor disconect on save (Eclipse Plugin)

### ISSUE THREAD

**Issue by thejavalistener** [dbeaver/dbeaver#17457]
### Description

When I save the file, the sql editor loses connection and reconnection is required.

### DBeaver Version

22.1.5 (Eclipse Plugin)

### Operating System

Windows 8.1

### Database and driver

Hyper SQL Server 2.7.0

### Steps to reproduce

1. Create a connection
2. Open any .sql file
3. Execute some statement
4. Save the file
5. Connection lost!

**Comment by Matvey16** [comment]
@thejavalistener Hello, I was not able to reproduce this. Can you add what version of eclipse do you use?
And a few more clarifications. Is the .sql file created in Dbeaver and located in Scripts folder or is it an external file outside of workspace?
Did you make any changes to the file after executing a statement

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
