### ISSUE TITLE
PostgreSQL - _box (box[]) isn't formatted as an array correctly.

### ISSUE THREAD

**Issue by Bas950** [dbeaver/dbeaver#17467]
### Description

Box arrays aren't getting parsed correctly
![image](https://user-images.githubusercontent.com/34792838/186643633-454fff7f-c751-43a9-a21f-d8167ab428d4.png)

Should be like any other arrays:
![image](https://user-images.githubusercontent.com/34792838/186643798-107c5807-86ca-4d8b-89df-c1120ac902fa.png)

### DBeaver Version

22.1.3.202207240614

### Operating System

Windows 11 build: 22000.856

### Database and driver

Database: PostgreSQL 13
Driver: PostgreSQL JDBC Driver 42.2.25

### Steps to reproduce

1. Connect to a database
2. Open a new sql script
3. run `select '{(1\,2)\, (3\,4); (1\,2)\,(3\,4)}'::box[]`

### Additional context

https://www.postgresql.org/docs/current/arrays.html#ARRAYS-INPUT
![image](https://user-images.githubusercontent.com/34792838/186644918-e4780f25-3d34-4454-a7cf-2f879461ab8f.png)
I am guessing since box has a different delimiter character DBeaver's formatter is messing up.

**Comment by uslss** [comment]
thanks for the report
