### ISSUE TITLE
Execute SQL statement considers empty lines and comments as statement delimiters

### ISSUE THREAD

**Issue by Xophmeister** [dbeaver/dbeaver#17466]
### Description

When you click "Execute SQL", or press Ctrl+Enter, in the SQL editor, DBeaver only seems to consider a "statement" to be a contiguous block of text from the cursor position, rather than an actual SQL statement.

For example, this is a complete SQL statement:

```sql
select id,

       -- Some comment
       some_field,
       other_field,

       -- Another comment
       yet_another_field

from   some_table;
```

DBeaver, however, considers this as four separate statements and executes the one where the cursor is located:

1. ```
   select id,
   ```
2. ```
          some_field,
          other_field,
   ```
3. ```
          yet_another_field
   ```
4. ```
   from   some_table;
   ```

If this is configurable behaviour, then it shouldn't be the default.

### DBeaver Version

Community Edition 22.0.2.202206050206

### Operating System

NixOS Linux 22.05

### Database and driver

Driver agnostic (reproduced with AWS Redshift and SQLite drivers)

### Steps to reproduce

1. Write a SQL statement containing empty lines or comments.
2. Try to execute that statement.
3. DBeaver will only send the contiguous text block, relative to the cursor, to the SQL driver and that will probably result in a syntax error (or worse, do something you don't expect if the block happens to be syntactically correct).

### Additional context

n.b., You can work around this problem by selecting the text you want to execute.

**Comment by uslss** [comment]
@Xophmeister could you try to disable Blank line is statement delimiter option in preferences and check if it helps?
![image](https://user-images.githubusercontent.com/31996417/186660493-e9eb479e-47fa-42a0-a877-17d1e8b210fe.png)

**Comment by Xophmeister** [comment]
Thanks @uslss -- That does fix the problem, but that seems like a curious default.
