### ISSUE TITLE
After installing dBeaver 22.1.5, I get "Datasource config parse error"

### ISSUE THREAD

**Issue by ljohnston123** [dbeaver/dbeaver#17476]
### Description

This is similar to https://github.com/dbeaver/dbeaver/issues/17300

I installed dBeaver 22.1.5 this week.  I was prompted to migrate my configuration to the new format and I choose 'Migrate' and my existing connections are imported.

But then I need to create a new connection.  The new connection is type Postgre.  I already have 2 existing postgre connections as well. 

After I create the new connection and exit I get the following error

Datasource config parse error
  Document parse error (line 1, pos 1)
  Document parse error (line 1, pos 1)
    org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
    Content is not allowed in prolog.

![image](https://user-images.githubusercontent.com/112121809/186752550-c14c5e04-a71d-4c60-b37d-e0fa28ad558b.png)

So I can rename the DbeaverData folder at /users/<my user>/AppData/Roaming to something like DbeaerData.last and then I can access my existing connections again.  But my new connection is no longer there, so I have to recreate it again and then of course if I exit at the end of the day, the next time I open DBeaver, I will get the error again.  

I believe my last version of dBeaver was 6.0.5
[](url)

### DBeaver Version

Dbeaver 22.1.5

### Operating System

Windows 10

### Database and driver

PostGre SQL, creating a new connection

### Steps to reproduce

1. Install dBeaver 22.1.5
2. Add a new database connection.
3. Exist dBeaver
4. Open dBeaver

### Additional context

None

**Comment by E1izabeth** [comment]
Please, send the log files. You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/

**Comment by E1izabeth** [comment]
Also could you send your data-sources file (see https://github.com/dbeaver/dbeaver/wiki/Admin-Manage-Connections) to my email? It would be very helpful.

**Comment by ljohnston123** [comment]
Here is my log file
[.log](https://github.com/dbeaver/dbeaver/files/9433099/default.log)

**Comment by E1izabeth** [comment]
Thank you

**Comment by dector** [comment]
+1. All saved connections / driver configurations disappearing:

```
$ tree ~/.local/share/DBeaverData/
~/.local/share/DBeaverData/
├── drivers
│   └── maven
│       └── maven-central
│           └── com.h2database
│               ├── h2-2.1.214.jar
│               └── h2-2.1.214.pom
├── workspace6
│   └── General
│       └── Scripts
│           └── Script.sql
```

(I was downloading h2-2.1.214 driver in the latest session - only maven repo cache is present)

`Version 22.1.5.202208211008`

**Comment by serge-rider** [comment]
Log says that file C:\Users\LJohnsto\AppData\Roaming\DBeaverData\workspace6\General\.dbeaver-data-sources.xml is corrupted.
It is a file where older DBeaver versions kepp datasources configuration.

**Comment by dector** [comment]
Reproducing:
https://imgur.com/a/k4y433y

**Comment by serge-rider** [comment]
The bug was appeared in 22.1.3. Legacy configuration (from DBeaver earlier than version 7) was incorrectly converted to a new configuration format (json contents in xml file).
This was fixed.

How to fix your configuration:
- Delete folder `.dbeaver` in your project
- Restart DBeaver

**Comment by uslss** [comment]
verified

**Comment by s-nt-s** [comment]
Same problem, but I don't want to delete `.dbeaver`. I need to keep my previous data source configuration.
How can I fix it?
