### ISSUE TITLE
Data Import task not matching mapping criteria regarding column name case

### ISSUE THREAD

**Issue by danmaxis** [dbeaver/dbeaver#17498]
### Description

Hello there,
I had a data import task that started to create new columns instead using mapped ones.

My source table always generates uppercase column names (db2).
And my target table is defined to lowercase column names (postgresql).

Except for PKs, all columns have the same name (except for letter case).
But during column mapping phase, it shows every column as 'existing'.

It's been a bit more than a month since I last ran this task without any issues. (June 24th)

Now, it shows 'existing', but creating all columns in uppercase is the first thing it does when running the task.

### DBeaver Version

Community Edition 22.1.5

### Operating System

Windows 11 22H2

### Database and driver

Source:
	DB Name: IBM DB2/LINUXZ64
	Driver: IBM Data Server Driver for JDBC and SQLJ 4.26.14

Target:
	DB Name: PostgreSQL 14.1
	Driver: PostgreSQL JDBC Driver 42.2.20

### Steps to reproduce

1. Select the target table in target server and enter context menu option "Import Data";
2. Mark "Table" as Import Source;
3. In next option, select Source Table in the source connection;
4. Next screen, "Tables Mapping", all columns would be mapped as "existing" (even with different letter case );
5. Extraction settings screen with default values;
6. Data load settings screen with default values;
7. Confirm and proceed;
8. If it's a first run, it may run and create new columns, adding values to it. A second attempt may incur an error trying to create already existing columns.

### Additional context

1. There is a SSH Tunnel for both connections using the same server.

**Comment by Matvey16** [comment]
@danmaxis Thank you for the report. We are already working on this issue in #17329
