### ISSUE TITLE
Provide a way to dump the entire DDL for a single database.

### ISSUE THREAD

**Issue by kfwolf** [dbeaver/dbeaver#17494]
This would be similar to the db2look function available through ibm's db2 or Microsofts SSMS generate scripts for all db objects.  

The goal is to create a script that contains the entire DDL.  After a deployment, one could compare the script to a pre-deployment dump.

**Comment by LonwoLonwo** [comment]
Hello @kfwolf 

For what database do you ask for this functionality?

**Comment by kfwolf** [comment]
> Hello @kfwolf
> 
> For what database do you ask for this functionality?

As it would be extremely valuable to create the full DDL prior to a deployment, run the deployment and look for all changes.  Secondly, if you have a database with multiple references to a table or a function, it would be great to document the entire scope of a db object.  I would recommend looking at MS SQL server SSMS tools and see how it generates a script.

**Comment by LonwoLonwo** [comment]
So you are using MS SQL server and your feature request for MS SQL server? Am I right @kfwolf ?

**Comment by kfwolf** [comment]
> So you are using MS SQL server and your feature request for MS SQL server? Am I right @kfwolf ?

This should have been clarified in the original request... ideally dbeaver would provide a sql script for any database but my database of preference for this request is postgresql.

**Comment by michal-bartak** [comment]
Not sure why x:postgresql has been set to this issue (it's not mentioned in posts above).
Anyway, it's possible to dump the whole db from PostgreSQL using DBeaver's backup feature. It uses the pg_dump utility to dump the entire db (or selected objects) into SQL file.

**Comment by kfwolf** [comment]
Not looking to "dump the whole db".  When using the backup feature, one of the options is "Use SQL Insert instead of copy for rows" - this gives the impression that it is going to "create data".   

The feature ask here is to create the sql only or DDL (no dml) .  Also, it should include all functions, SP, user define data types, etc.

**Comment by michal-bartak** [comment]
IMO it is still possible. Not by clicking on checkboxes though but you can achieve what you want.
Backup is created by `pg_dump` command and at the same time, DBeaver allows to pass of additional parameters to this command, making it possible to control what and how is dumped.

When you open the backup dialog, on the second page you will find "Extra command arguments"
![image](https://user-images.githubusercontent.com/7868445/190436005-605d5346-7c1d-4330-b5f9-bc625e2ebe42.png)

To achieve your need, it's probably enough to put there `-s` or `--section=pre-data --section=post-data`

See https://www.postgresql.org/docs/current/app-pgdump.html for possible options

**Comment by LonwoLonwo** [comment]
Hello @kfwolf 

I think this is the best answer for you: https://github.com/dbeaver/dbeaver/issues/17494#issuecomment-1248213846

Or maybe you have a special request for your initial idea? Because for now, I think pg_dump during our Native Clients support is the best way to generate the DDL of the entire database.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
