### ISSUE TITLE
Problem when "Write to the single file" is checked in XLSX export

### ISSUE THREAD

**Issue by maphstay** [dbeaver/dbeaver#17493]
### Description

When we checked "Write to the single file" in XLSX export, if we using the variables datasource, catalog or schema (these was the options that i tested), the value comes as empty.

Follow some prints to explain better.

### DBeaver Version

Community edition 22.1.5

### Operating System

Windows 10 x64 21H2 build 19044.1889

### Database and driver

Database MySQL
MySQL driver JBDC 8.0.17

### Steps to reproduce

1. First try use the variable catalog without checked "Write to the single file"
2. Try look on left layer: confirm > in the Objects > Target, the name generated there catalog value
![photo_2022-08-29_13-26-45](https://user-images.githubusercontent.com/76125737/187205712-28683181-a47b-499c-8338-a771a6ebe76b.jpg)

AND

3. Now try checking "Write to the single file".
![photo_2022-08-29_13-27-02](https://user-images.githubusercontent.com/76125737/187205922-f44f50be-d569-470c-8b5e-4c231077bb15.jpg)

4. The name generated comes with the catalog value empty.
![photo_2022-08-29_13-26-54](https://user-images.githubusercontent.com/76125737/187205931-e09362a2-c699-4e1e-a74d-4497e13283a9.jpg)

### Additional context

Extension: DBeaver Office Extension

**Comment by ShadelessFox** [comment]
Hello @maphstay,

This is the expected behavior. The option `Write to the single file`, well, writes everything into a single file. Therefore the output filename must **not** be unique.

Perhaps you wanted to use the `Append to the end of the file` option?

**Comment by maphstay** [comment]
Yeah, i can append the name statically, but this way i need change the value for some database that i want export.
In my case too i need edit label sheet to comes with the table name, this is possible using write to the single file ?

**Comment by ShadelessFox** [comment]
No, it's not possible.

**Comment by maphstay** [comment]
so for now this is all, I appreciate your help.
