### ISSUE TITLE
Selection in dictionary value panel makes value hardly readable due to the light blue background

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#17492]
### Description

![image](https://user-images.githubusercontent.com/28875055/187190935-ba97f8a0-c0f6-4ffd-853a-98aefd69731c.png)

### DBeaver Version

DBeaver 22.1.5

### Operating System

Windows 10

### Steps to reproduce

1. Open value panel for foreign key column.
2. Select an item. The font becomes white and the background becomes blue.
2. Put cursor on the selected item. The background becomes light blue, but the font remains white.

**Comment by ShadelessFox** [comment]
#12141

**Comment by E1izabeth** [comment]
Can't reproduce on DBeaver 23.1.3 on Windows 11.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/2380b3aa-8ba5-42f4-a715-8de9a68ec987)
