### ISSUE TITLE
Querying SQL using dbeaver was slow the first time, then very fast.

### ISSUE THREAD

**Issue by soul-F** [dbeaver/dbeaver#17500]
### Description

I have 100,000 tables in my database.
Querying SQL using dbeaver was slow the first time, then very fast.
Time is spent querying database INFORMATION_SCHEMA.
Is there any solution?

select * from information_schema.processlist;

| 806296184 | xxx    | xxx | NULL               | Query   |   30 | checking permissions | /* ApplicationName=DBeaver 22.1.5 - Metadata */ SELECT A.REFERENCED_TABLE_SCHEMA AS PKTABLE_CAT,NULL AS PKTABLE_SCHEM, A.REFERENCED_TABLE_NAME AS PKTABLE_NAME, A.REFERENCED_COLUMN_NAME AS PKCOLUMN_NAME, A.TABLE_SCHEMA AS FKTABLE_CAT, NULL AS FKTABLE_SCHEM, A.TABLE_NAME AS FKTABLE_NAME, A.COLUMN_NAME AS FKCOLUMN_NAME, A.ORDINAL_POSITION AS KEY_SEQ,CASE WHEN R.UPDATE_RULE='CASCADE' THEN 0 WHEN R.UPDATE_RULE='SET NULL' THEN 2 WHEN R.UPDATE_RULE='SET DEFAULT' THEN 4 WHEN R.UPDATE_RULE='RESTRICT' THEN 1 WHEN R.UPDATE_RULE='NO ACTION' THEN 1 ELSE 1 END  AS UPDATE_RULE,CASE WHEN R.DELETE_RULE='CASCADE' THEN 0 WHEN R.DELETE_RULE='SET NULL' THEN 2 WHEN R.DELETE_RULE='SET DEFAULT' THEN 4 WHEN R.DELETE_RULE='RESTRICT' THEN 1 WHEN R.DELETE_RULE='NO ACTION' THEN 1 ELSE 1 END  AS DELETE_RULE, A.CONSTRAINT_NAME AS FK_NAME, (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = A.REFERENCED_TABLE_SCHEMA AND TABLE_NAME = A.REFERENCED_TABLE_NAME AND CONSTRAINT_TYPE IN ('UNIQUE','PRIMARY KEY') LIMIT 1) AS PK_NAME,7 AS DEFERRABILITY FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE A JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS B USING (CONSTRAINT_NAME, TABLE_NAME) JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS R ON (R.CONSTRAINT_NAME = B.CONSTRAINT_NAME AND R.TABLE_NAME = B.TABLE_NAME AND R.CONSTRAINT_SCHEMA = B.TABLE_SCHEMA) WHERE B.CONSTRAINT_TYPE = 'FOREIGN KEY' AND A.TABLE_SCHEMA = 'aaa_schema' AND A.TABLE_NAME='log_operation_agg' AND A.REFERENCED_TABLE_SCHEMA IS NOT NULL ORDER BY A.REFERENCED_TABLE_SCHEMA, A.REFERENCED_TABLE_NAME, A.ORDINAL_POSITION |

8月-30 09:10:33	SQL / User	select * from aaa_schema.oid_instance oi LIMIT 0, 200	78,024	37	succeed  // execution time(78,024ms)
8月-30 09:13:47	SQL / User	select * from aaa_schema.oid_instance oi LIMIT 0, 200	73	    37	succeed  // execution time(73ms)
8月-30 09:13:49	SQL / User	select * from aaa_schema.oid_instance oi LIMIT 0, 200	71	    37	succeed  // execution time(71ms)
8月-30 09:13:50	SQL / User	select * from aaa_schema.oid_instance oi LIMIT 0, 200	73	    37	succeed  // execution time(73ms)

### DBeaver Version

22.1.5

### Operating System

Win10

### Database and driver

MySQL

**Comment by flambchap** [comment]
Hi. Please check out this ticket: https://github.com/dbeaver/dbeaver/issues/16480. You can find a couple of workarounds there. I think we should improve the performance of metadata read. I'm closing this ticket as a duplicate.
