### ISSUE TITLE
Not all columns shown in Table view

### ISSUE THREAD

**Issue by 3DRaven** [dbeaver/dbeaver#17504]
### Description

Opened table column list. In table exists 5 columns, shown 1

### DBeaver Version

22.1.5

### Operating System

ubuntu 22.04

### Database and driver

PostgreSQL driver from dbeaver repo

### Steps to reproduce

1. Create table by DDL
`
CREATE TABLE configuration.task (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	instance_id int4 NOT NULL,
	name varchar NOT NULL,
	count int4 NOT NULL DEFAULT 0,
	created_date timestamp NOT NULL DEFAULT now(),
	config jsonb NOT NULL,
	last_modified_date timestamp NOT NULL DEFAULT now(),
	CONSTRAINT tasks_pk PRIMARY KEY (id)
);
CREATE INDEX a_idx ON vsf_configuration.backup_task USING btree (object_name);

ALTER TABLE configuration.task ADD CONSTRAINT tasks_fk FOREIGN KEY (instance_id) REFERENCES configuration.all_instance(id) ON DELETE CASCADE ON UPDATE CASCADE;`
2. Open table view with data or column list.
3. If I try to rename table to any new name, all columns will shown correctly again.
4. If I try to rename table to old name (task), will shown only one column.
5. Task it is not real name, really used another name from project as example something as "table_task"

**Comment by emironovDB** [comment]
@3DRaven 
Could you provide footage of such behavior?

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
