### ISSUE TITLE
DBeaver's system theme doesn't reflect Windows theme

### ISSUE THREAD

**Issue by anaruzhnii** [dbeaver/dbeaver#17508]
### Description

![image](https://user-images.githubusercontent.com/106668678/187512908-9ebbe817-d295-414a-b49f-324d4f6cf042.png)
By Explorer and task bar you can see that dark theme is selected in Windows, but when I select System theme in DBeaver it turns light

### DBeaver Version

Community Edition 22.1.3.202207240614

### Operating System

Windows 11 Home edition 22000.856

**Comment by Matvey16** [comment]
@anarujnii Hello, this feature is intended for Systems that has Light/Dark theme like MacOS or Ubuntu for example. It doesn't work for Windows because it's theme is not categorized as dark or light. It was added in Windows 11, so maybe we need to look if it can be implemented for windows as well

**Comment by benediktms** [comment]
I am on macOS Ventura 13.2.1 and the system theme option is not even displayed. Was it removed recently?

**Comment by E1izabeth** [comment]
This theme was removed by Eclipse - the platform DBeaver relies on.
I assume the issue can be closed. If you think it's still actual, please let me know.
