### ISSUE TITLE
Error while exporting data "Task execution failed"

### ISSUE THREAD

**Issue by 132262B** [dbeaver/dbeaver#17501]
### Description

An error occurred while exporting data.
mariadb(MariaDB 10.1.48-MariaDB-0ubuntu0.18.04.1) -> mariadb(MariaDB 10.4.19-MariaDB-1:10.4.19+maria~xenial-log)(x)
mariadb -> txt file (x)

Caused by: java.io.IOException: Packets out of order when reading field packets, expected was EOF stream.Packet contents (hex) = 
+--------------------------------------------------+
|  0  1  2  3  4  5  6  7   8  9  a  b  c  d  e  f |
+--------------------------------------------------+------------------+
| 61 6B 2E 0A 22 41 20 73  70 6F 6B 65 73 77 6F 6D | ak.."A spokeswom |
| 61 6E 20 66 6F 72 20 74  68 65 20 55 2E 53 2E 20 | an for the U.S.  |
| 44 65 70 61 72 74 6D 65  6E 74 20 6F 66 20 45 64 | Department of Ed |
| 75 63 61 74 69 6F 6E 27  73 20 4F 66 66 69 63 65 | ucation's Office |
| 20 6F 66 20 49 6E 73 70  65 63 74 6F 72 20 47 65 |  of Inspector Ge |
| 6E 65 72 61 6C 20 73 61  69 64 20 74 68 65 20 6F | neral said the o |
| 66 66 69 63 65 20 68 61  73 20 72 65 63 6F 6D 6D | ffice has recomm |
| 65 6E 64 65 64 20 6D 6F  64 69 66 79 69 6E 67 20 | ended modifying  |
| 74 68 65 20 6C 61 6E 67  75 61 67 65 20 6F 6E 20 | the language on  |
| 66 65 64 65 72 61 6C 20  66 69 6E 61 6E 63 69 61 | federal financia |
| 6C 20 61 69 64 20 66 6F  72 6D 73 20 66 6F 6C 6C | l aid forms foll |
| 6F 77 69 6E 67 20 64 69  73 63 6C 6F 73 75 72 65 | owing disclosure |
| 20 6F 66 20 74 68 65 20  74 61 63 74 69 63 2C 20 |  of the tactic,  |
| 66 69 72 73 74 20 72 65  70 6F 72 74 65 64 20 62 | first reported b |
| 79 20 50 72 6F 50 75 62  6C 69 63 61 20 49 6C 6C | y ProPublica Ill |
| 69 6E 6F 69 73 20 6F 6E  20 4D 6F 6E 64 61 79 2E | inois on Monday. |
| 20 54 68 65 20 57 61 6C  6C 20 53 74 72 65 65 74 |  The Wall Street |
| 20 4A 6F 75 72 6E 61 6C  20 61 6C 73 6F 20 70 75 |  Journal also pu |
| 62 6C 69 73 68 65 64 20  61 20 73 74 6F 72 79 20 | blished a story  |
| 6C 61 74 65 20 4D 6F 6E  64 61 79 20 61 62 6F 75 | late Monday abou |
| 74 20 74 68 65 20 69 73  73 75 65 2E 22 0A 49 20 | t the issue.".I  |
| 77 6F 6E 64 65 72 20 68  6F 77 20 74 68 65 20 57 | wonder how the W |
| 61 6C 6C 20 53 74 72 65  65 74 20 4A 6F 75 72 6E | all Street Journ |
| 61 6C 20 63 61 6D 65 20  74 6F 20 77 6F 72 6B 20 | al came to work  |
| 6F 6E 20 74 68 65 20 73  61 6D 65 20 73 74 6F 72 | on the same stor |
| 79 20 61 73 20 50 72 6F  50 75 62 6C 69 63 61 20 | y as ProPublica  |
| 49 6C 6C 69 6E 6F 69 73  20 61 74 20 74 68 65 20 | Illinois at the  |
| 73 61 6D 65 20 74 69 6D  65 20 2D 20 6F 72 20 76 | same time - or v |
| 69 63 65 20 76 65 72 73  61 2E 0A 41 73 73 69 67 | ice versa..Assig |
| 6E 6D 65 6E 74 20 44 65  73 6B 2C 20 61 63 74 69 | nment Desk, acti |
| 76 61 74 65 21 0A 54 68  65 20 4A 6F 75 72 6E 61 | vate!.The Journa |
| 6C 20 63 6C 65 61 72 6C  79 20 77 61 73 6E 27 74 | l clearly wasn't |
| 20 6A 75 73 74 20 66 6F  6C 6C 6F 77 69 6E 67 20 |  just following  |
| 75 70 20 6F 6E 20 50 72  6F 50 75 62 6C 69 63 61 | up on ProPublica |
| 27 73 20 73 74 6F 72 79  3B 20 74 68 65 79 20 70 | 's story; they p |
| 75 74 20 69 6E 20 77 6F  72 6B 2E 20 54 6F 20 77 | ut in work. To w |
| 69 74 3A 0A 22 54 68 65  20 4A 6F 75 72 6E 61 6C | it:."The Journal |
| 27 73 20 72 65 76 69 65  77 20 6F 66 20 6D 6F 72 | 's review of mor |
| 65 20 74 68 61 6E 20 31  2C 30 30 30 20 70 72 6F | e than 1,000 pro |
| 62 61 74 65 20 63 6F 75  72 74 20 63 61 73 65 73 | bate court cases |
| 20 66 69 6C 65 64 20 69  6E 20 32 30 31 38 20 69 |  filed in 2018 i |
| 6E 20 4C 61 6B 65 20 43  6F 75 6E 74 79 2C 20 49 | n Lake County, I |
| 6C 6C 2E 2C 20 74 75 72  6E 65 64 20 75 70 20 33 | ll., turned up 3 |
| 38 20 63 61 73 65 73 20  69 6E 20 77 68 69 63 68 | 8 cases in which |
| 20 61 20 6A 75 64 67 65  20 67 72 61 6E 74 65 64 |  a judge granted |
| 20 74 68 65 20 74 72 61  6E 73 66 65 72 20 6F 66 |  the transfer of |
| 20 67 75 61 72 64 69 61  6E 73 68 69 70 20 74 6F |  guardianship to |
| 20 61 20 74 65 65 6E 61  67 65 72 20 69 6E 20 68 |  a teenager in h |
| 69 73 20 6F 72 20 68 65  72 20 6A 75 6E 69 6F 72 | is or her junior |
| 20 6F 72 20 73 65 6E 69  6F 72 20 79 65 61 72 20 |  or senior year  |
| 6F 66 20 68 69 67 68 20  73 63 68 6F 6F 6C 2E 20 | of high school.  |
| 4D 6F 73 74 20 6F 66 20  74 68 65 20 66 61 6D 69 | Most of the fami |
| 6C 69 65 73 20 6C 69 76  65 20 69 6E 20 68 6F 6D | lies live in hom |
| 65 73 20 76 61 6C 75 65  64 20 61 74 20 61 72 6F | es valued at aro |
| 75 6E 64 20 24 35 30 30  2C 30 30 30 2E 20 53 65 | und $500,000. Se |
| 76 65 72 61 6C 20 6F 66  20 74 68 6F 73 65 20 68 | veral of those h |
| 6F 6D 65 73 20 77 65 72  65 20 76 61 6C 75 65 64 | omes were valued |
| 20 61 74 20 6D 6F 72 65  20 74 68 61 6E 20 24 31 |  at more than $1 |
| 20 6D 69 6C 6C 69 6F 6E  2C 20 61 63 63 6F 72 64 |  million, accord |
| 69 6E 67 20 74 6F 20 70  72 6F 70 65 72 74 79 20 | ing to property  |
| 73 69 74 65 73 20 69 6E  63 6C 75 64 69 6E 67 20 | sites including  |
| 5A 69 6C 6C 6F 77 2E 0A  22 49 6E 20 63 6F 75 72 | Zillow.."In cour |
| 74 20 64 6F 63 75 6D 65  6E 74 73 2C 20 61 20 70 | t documents, a p |
| 65 74 69 74 69 6F 6E 65  72 20 69 73 20 61 73 6B | etitioner is ask |
+--------------------------------------------------+------------------+

	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readResultSet(AbstractQueryProtocol.java:1829)
	... 15 more
2022-08-30 13:49:52.623 - Execution context opened (dcision; Data transfer producer; 20)
2022-08-30 13:51:13.802 - Can't close statement
java.lang.NullPointerException
	at org.mariadb.jdbc.internal.com.read.dao.Results.loadFully(Results.java:277)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.skip(AbstractConnectProtocol.java:463)
	at org.mariadb.jdbc.MariaDbStatement.skipMoreResults(MariaDbStatement.java:1184)
	at org.mariadb.jdbc.MariaDbStatement.close(MariaDbStatement.java:789)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.close(JDBCStatementImpl.java:497)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:221)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:265)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

### DBeaver Version

22.1.5.202208211008

### Operating System

Windows 10 64bit

### Database and driver

MariaDB 10.1.48-MariaDB-0ubuntu0.18.04.1 / MariaDB Connector/J 2.7.1
---->
MariaDB 10.4.19-MariaDB-1:10.4.19+maria~xenial-log / MariaDB Connector/J 2.7.1

**Comment by uslss** [comment]
@132262B, please, provide steps to reproduce.Videoo with the issue also would be helpful

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
