### ISSUE TITLE
SQL completion: list all possible values to filter

### ISSUE THREAD

**Issue by llnk** [dbeaver/dbeaver#1751]
One of the best feature that the client could have is to facilitate the filtering of a recordset by showing all the possibile values of a column.

This is a common feature of more advanced software like Spotfire https://www.youtube.com/watch?v=mzu0rFgxoVY 

Do you think it would be possible to add something like this? For example while writing the query (or while applyinng a filter) if one presses cltr+space than dbeaver could search for all the distinct values of that column and helping select them (like a filter in Excel)

**Comment by serge-rider** [comment]
It is already supported for results filtering (context menu->Order/Filter->IN ...  - and you can use F11 as shortcut).

But this is not supported in SQL editor. Perhaps this could be yet another feature request.

**Comment by serge-rider** [comment]
First value completion version is ready.
It doesn't filter column values by other query conditions but shows only first 20 possible values.

**Comment by uslss** [comment]
verified.
Created #7913
