### ISSUE TITLE
Tabbed queries do not run on seperate connections

### ISSUE THREAD

**Issue by notzippy** [dbeaver/dbeaver#17518]
### Description

Execute a statement for a single long-running query, Now "execute a statement in a new tab" for a second query. The second query will not begin to execute until the first is completed. 

#2180 sounds similar although it was closed. I know separate SQL editors which would establish different connections which would solve this, but the current design does appear to imply that two statements running in the same editor would have a connection pool to draw the connections from, so rather than having to wait for the first statement to complete a pooled connection would allow you to dynamically scale the connections automatically. This would be only applicable to drivers that support connection pooling.

### DBeaver Version

CE 22.1.3

### Operating System

Manjaro

### Database and driver

Postgresql 14.0

### Steps to reproduce

1) Open sql editor
2) Execute a statement for a single long-running query
3) "execute a statement in a new tab" for a second query. 

The second query will not begin to execute until the first is completed.

**Comment by ShadelessFox** [comment]
Hello @notzippy,

This will not work. Let me explain.

Every SQL editor is associated with its own connection. When using connection pooling, it will result in different queries executing in different connections, not sharing the common state such as transactions. Additionally, a query can depend on the result of a previously executed query. Running queries in parallel can cause any sort of weird things to happen. This can be really harmful.
