### ISSUE TITLE
Scripts are deleted if they are closed without changes

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#17516]
### Description

Any script is deleted if it is opened and then closed

### DBeaver Version

22.2.0

### Operating System

Any

### Database and driver

Any

### Steps to reproduce

1. Turn on a preference to delete empty scripts
2. Open an existing script
3. Close it

**Expected:** Script is closed
**Actual:** Script is deleted permanently

### Additional context

Script won't be deleted if the preference to delete empty scripts is disabled
![dbeaver_EkKItff18y](https://user-images.githubusercontent.com/82543000/187733402-dead1043-f15b-4283-b4ee-226dce6f6614.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Still works not as expected. Not critical right now, but empty scripts are deleted even if they are not new.

1. Open an existing script
2. Delete everything
3. Save th changes and close the script
4. Restart DBeaver
5. Open the script
6. Close it

Script will be deleted even if the preference says `Delete only new scripts`
