### ISSUE TITLE
Filters of type 'equal' doesn't work in data editor 

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#17524]
### Description

https://user-images.githubusercontent.com/43252954/187883172-29f0c818-e1f1-42c0-b408-07bb3c197d59.mp4

Step to reproduce:
1. open a table
2. in context menu select Filters -> Custom\Clipboard\value filter-> select filter with '='
3. Apply the filter
As the result you'll see that filtering value isn't passed to the filter bar

### DBeaver Version

22.2.0

### Operating System

win11

**Comment by serge-rider** [comment]
Fixed

**Comment by DariaMarkaryan** [comment]
Verified
