### ISSUE TITLE
SAP HANA Database connection was removed

### ISSUE THREAD

**Issue by teja463** [dbeaver/dbeaver#17522]
### Description

Hi I am currently using Dbeaver Community edition 22.0.5 and using it to connect to SAP HANA database. But when I downloaded the latest version 22.1.5 I dont see any option to connect to the SAP HANA databse. Is there any reason the support is removed in the new version. 

### DBeaver Version

Community Edition 22.1.5

### Operating System

Windows 10

**Comment by LonwoLonwo** [comment]
Hello @teja463 

Please check that the "All" tab is chosen in the Connection dialog.

![2022-09-01 12_30_19-Window](https://user-images.githubusercontent.com/45152336/187881864-e4bd3002-1c8d-49dd-a2f3-446066012a78.png)

**Comment by teja463** [comment]
@LonwoLonwo my bad, sorry for wasting your time
