### ISSUE TITLE
Error Script Insert after Commit statement by setting manual commit 

### ISSUE THREAD

**Issue by MuellerAndr** [dbeaver/dbeaver#17521]
### Description

hello,
I use a sql scipt which does not work since the last dbeaver update.
the script is executed in manual commit mode.
Script:
```
CREATE TABLE DATABASEVERSIONINFO
( 
   DatabaseVersion     INTEGER NOT NULL,   -- Versionsnummer der Datenbank  x.yyy  x=mainversion y=subversion
                                     -- die Mainversion legt fest ob die Datenbank mit dem Program kompatibel ist
	UPDATETIME Timestamp, -- Datum/Zeit der letzten Veränderung
	UPDATEDBY Varchar(50), -- Wer hat die Änderung gemacht
	UPDATEDESCRIPTION Varchar(500),  -- kurze Beschreibung der Änderungen 

		/* Primary Key  */
	 CONSTRAINT PK_DVI PRIMARY KEY (DatabaseVersion)

);


COMMIT;


INSERT INTO DATABASEVERSIONINFO (DATABASEVERSION,UpdatedBy,UpdateDescription) VALUES (6002,'Installation','create Database');
```

Error:
SQL-Fehler [335544332] [08003]: invalid transaction handle (expecting explicit transaction start) [SQLState:08003, ISC error code:335544332]
  invalid transaction handle (expecting explicit transaction start) [SQLState:08003, ISC error code:335544332]
  invalid transaction handle (expecting explicit transaction start) [SQLState:08003, ISC error code:335544332]
    invalid transaction handle (expecting explicit transaction start)
    invalid transaction handle (expecting explicit transaction start)

if the commit is followed by an update or insert statement the problem does not occur.
in my previous Dbeaver version the problem did not occur.

### DBeaver Version

Edition COMMUNITY  22.1.5.202208211008

### Operating System

Windows 10

### Database and driver

Firebird 3.0.5.33220-0

Driver:
org.firebirdsql.jdbc:jaybird:RELEASE
4.0.0.java8

### Steps to reproduce

Run Script in manual Mode

**Comment by emironovDB** [comment]
@MuellerAndr 
Could you answer what exact version of DBeaver did you use?

**Comment by E1izabeth** [comment]
Does this issue is still actual for the latest DBeaver version?

**Comment by MuellerAndr** [comment]
> I Updated to the last Release from 26.9.2022 Version Today
Version: 22.2.1.202209251341
The Problem is still present.

**Comment by MuellerAndr** [comment]
I Updated to the last Release from 26.9.2022 Version Today
Version: 22.2.1.202209251341
The Problem is still present.

**Comment by ShadelessFox** [comment]
Hello @MuellerAndr,

Don't mix transaction manager and SQL statements. Use just one of them.

Transaction manager uses JDBC API to start/end/commit transactions. The behavior depends on a given driver implementation and it may handle transactions differently from the database itself.

Additionally, we don't want to parse SQL statements and handle `COMMIT` and other statements ourselves.
