### ISSUE TITLE
ADD Database import option: disable foreign key checks

### ISSUE THREAD

**Issue by allanlaal** [dbeaver/dbeaver#1752]
## use case

I have an old dirty database with some broken foreign key relations and I want to import it.
I fire up my trusty DBeaver and select Tools→Restore Database from the right click meny of my db.
in the "Database Import" window I then check "Disable foreign key checks" under the "Settings" section.

DBeaver then prepends:

 	SET FOREIGN_KEY_CHECKS=0;
	
and appends:

	SET FOREIGN_KEY_CHECKS=1;

to the SQL just before importing, so that the dirty database imports nicely

**Comment by kwrjcr** [comment]
What is the status of this request?  There have been a few times that I have needed this.

**Comment by bumbummen99** [comment]
Has there been any update on this?

**Comment by pascaldls** [comment]
Also disable triggers 
ALTER TABLE  xx DISABLE TRIGGER ALL;
ALTER TABLE  xx ENABLE TRIGGER ALL;

**Comment by rulatir** [comment]
Status of this? ANY reaction from developers?

**Comment by serge-rider** [comment]
Sorry, missed this ticket. It is easy to implement.
Moving to 7.2.4.

**Comment by akilovich** [comment]
Feature added.

**Comment by uslss** [comment]
we need sample database to test this feature

**Comment by akilovich** [comment]
Sample sent via dm.

**Comment by uslss** [comment]
verified
