### ISSUE TITLE
DBeaver connects with three connections to DB2 database instead of one

### ISSUE THREAD

**Issue by igor2x** [dbeaver/dbeaver#17525]
### Description

When DBeaver connects to DB2 database I expect (like any other application) that it connects to database with only single connection. But it always connects with three connections. It looks like there are some run away connections.

Because each connection on database server consumes some memory and many application developers accessing database it is just consumed way more resources as it should.

### DBeaver Version

Community Edition 22.1.5

### Operating System

Windows 10

### Database and driver

1. DB2 database 11.5.7.0 (the latest available).
2. JDBC driver 4.31.10 (the latest available).

### Steps to reproduce

1. In **Database Navigator** double click on existing DB2 connection. Problem appears: DBeaver establish 3 connections to DB2 database, but I expect only single connection to happen.

I took _Connection calls_ trace from DBeaver: [trace.zip](https://github.com/dbeaver/dbeaver/files/9469064/trace.zip)
From trace two files appears and in first file are two connections and in second file is one connection visible.

List all connections to database:
`SELECT APPLICATION_HANDLE, APPLICATION_NAME, APPLICATION_ID FROM TABLE(SYSPROC.MON_GET_CONNECTION(NULL, -1));`
and it returns three connections:
![image](https://user-images.githubusercontent.com/10895030/187892935-ce8bdba2-e5aa-45af-a614-f635fb3cebac.png)

Which connection is current application connections:
`SELECT APPLICATION_HANDLE, APPLICATION_NAME, APPLICATION_ID FROM TABLE(SYSPROC.MON_GET_CONNECTION(SYSPROC.MON_GET_APPLICATION_HANDLE(), -1));`
and it returns:
![image](https://user-images.githubusercontent.com/10895030/187893078-4cfb744f-f160-4e73-a6a2-0118af2f6a14.png)

Now from Db2 console I killed connections 232 and 245 and then executed another "select" statement from DBeaver and DBeaver works without an issue.

It looks to me that DBeaver for some reason opens 3 connections to database and immediately two of them get orphaned after connection to database is established.

**Comment by Matvey16** [comment]
@igor2x Hello. It is working as intended. Two additional connections are for metadata read and SQL Editor. Those options can be desabled.

![dbeaver_vEM2j0fZYt](https://user-images.githubusercontent.com/82543000/187894763-45e7a62e-5169-4a9f-8602-0080b8e4e0e1.png)
![dbeaver_NUXyywLjyr](https://user-images.githubusercontent.com/82543000/187894782-b337638c-1fad-4e59-b3b5-d14be7d762db.png)

**Comment by igor2x** [comment]
1. On **Window | Preferences** I have set:
![image](https://user-images.githubusercontent.com/10895030/188388112-da83a6d2-1681-48c7-9822-751f4aa4ddd0.png)

2. On individual connection right click and **Edit Connection** and set:
![image](https://user-images.githubusercontent.com/10895030/188388500-d5ce4b02-8953-48d5-8747-8f17327f6692.png)

Retesting and now only single connection is established between DBeaver and Db2 database. That is excellent.

QUESTION: Setting in step 2 is setting for individual connection. Is there some global setting to be set and it is valid for all of the connections?

**Comment by igor2x** [comment]
For step 2 I have found global setting:
On **Windows | Preferences** I have set:
![image](https://user-images.githubusercontent.com/10895030/188424641-91e0f652-5e77-48b5-9813-b73cd1c894ab.png)
