### ISSUE TITLE
Cursor jumps to the beginning of the line on paste using mouse context menu

### ISSUE THREAD

**Issue by marat2706** [dbeaver/dbeaver#17539]
### Description

When you try to paste text using the context menu, the cursor runs to the beginning of the line and the paste occurs in the wrong place.
![image](https://user-images.githubusercontent.com/68788317/188138188-c8b4a8be-59e9-498f-b89c-77fc64882888.png)

### DBeaver Version

22.1.5.202208211008

### Operating System

Windows 10

### Steps to reproduce

Any paste using mouse context menu.

**Comment by LonwoLonwo** [comment]
Hello @marat2706 

Can you reproduce this behavior in all places of SQL Editor or only at the end of the string?

**Comment by marat2706** [comment]
Hello Anastasiya

I can reproduce this behavior only at the end of the string.


пт, 2 сент. 2022 г. в 19:50, Anastasiya ***@***.***>:

**Comment by LonwoLonwo** [comment]
Thanks for the bug report.

**Comment by E1izabeth** [comment]
Will be fixed in scope of #17036
