### ISSUE TITLE
Default Schema is ignored for Apache Hive connections

### ISSUE THREAD

**Issue by JesseFL** [dbeaver/dbeaver#17532]
### Description

The default schema is not respected for Apache Hive connections.  Every time a new connection is established, the active schema is always N/A

![image](https://user-images.githubusercontent.com/17784067/187958843-b8fedaf3-6c2a-45c9-a5d1-39e459d030b6.png)

Error log is showing this error:
`!MESSAGE Active schema can't be changed for this kind of datasource!`

[dbeaver logs.txt](https://github.com/dbeaver/dbeaver/files/9471452/dbeaver.logs.txt)

If I try to manually select a new active schema, I am offered the list of schemas to select.  After I choose one, nothing happens.  The active schema is still N/A.

I have to run a query...any query, but I have to run one, and then I am able to change the active schema.

### DBeaver Version

Community 22.1.5

### Operating System

Windows 10

### Database and driver

Apache Hive
Cloudera JDBC 4.2

### Steps to reproduce

Create an Apache Hive connection utilizing the Cloudera Driver (unsure if this is specific to Cloudera driver or not)
Define a default schema
Connect to the data source
Observe the active schema still shows N/A

**Comment by LonwoLonwo** [comment]
Hello @JesseFL 

Thanks for the report!
