### ISSUE TITLE
选项卡菜单item名错误

### ISSUE THREAD

**Issue by shawnWXN** [dbeaver/dbeaver#17536]
### Description

![image](https://user-images.githubusercontent.com/47786182/188089461-c24b4214-c90f-4522-86eb-612111ac40c1.png)

### DBeaver Version

Community  22.1.5.202208211008

### Operating System

Windows11

**Comment by ShadelessFox** [comment]
Hello @shawnWXN,

Please use English and provide more information about the issue.

If the localization is incorrect, then please suggest a better translation.

**Comment by LonwoLonwo** [comment]
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/17697

This is the bug from the Eclipse side
