### ISSUE TITLE
Duplicate row that duplicates only selected cells, to the next row

### ISSUE THREAD

**Issue by dbojan** [dbeaver/dbeaver#17548]
**Is your feature request related to a problem? Please describe.**
When duplicating row, primary key/unique values is also duplicated, which obviously cannot be committed to db.

**Describe the solution you'd like**
when duplicating row, duplicate only selected values, or
add option in configuration to not duplicate primary key/unique values.
Or keep 'duplicate row' command, and add another 'duplicate selected cells only"

**Comment by emironovDB** [comment]
We will fix this issue in #17547
