### ISSUE TITLE
Blank scripts are deleted even if they are not new

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#17543]
### Description

Preference to delete empty scripts on closing ignores the option to delete only new scripts and any empty script is always deleted

### DBeaver Version

22.2.0

### Operating System

Any

### Database and driver

Any

### Steps to reproduce

1. Open an existing script
2. Delete everything
3. Save th changes and close the script
4. Restart DBeaver
5. Open the script
6. Close it

**Expected:** Script still exists
**Actual:** Script is deleted

### Additional context

![image](https://user-images.githubusercontent.com/82543000/188172075-39b817cb-0d00-4973-80af-d0a3b0d71dc2.png)

**Comment by E1izabeth** [comment]
Can't reproduce on DBeaver 23.1.3
