### ISSUE TITLE
List databases with turned off multiple connections

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#17541]
We turned off separate connections for metadata and sql editor for some databases in this ticket #15153.
We should describe it somewhere for these databases:
- SQLServer Azure AD MFA
- BigQuery
- BigTable
- Spanner
- Apache Hadoop, Apache Drill, Apache Kyuubi, Apache Spark, Apache Hive, SnappyData, Gemfire XD, Apache Phoenix
- Redshift
- Snowflake

**Comment by E1izabeth** [comment]
https://github.com/dbeaver/dbeaver/wiki/Separate-Connections

**Comment by GuenterSch** [comment]
Remark: It would be helpful, if you write why these databases were excepted.
