### ISSUE TITLE
sum of selected values in 'Values' side panel

### ISSUE THREAD

**Issue by dbojan** [dbeaver/dbeaver#17552]
**Is your feature request related to a problem? Please describe.**
When user selects multiple numerical, non foreign key, values in one column, 'Values' side panel displays just the first value.

Which is probably not what the user wants, since she selected multiple values.

**Describe the solution you'd like**
It would be useful to display sum of all selected values, instead of just the value of the first one, when more than one cell is selected.
And the values are numeric, non foreign keys.

I know there is an Calc side panel, but user has to jump between Values and Calc panel.

If not possible in side panel, please add sum in the status bar, or in the tool-tip.

**Comment by ShadelessFox** [comment]
Hello @dbojan,

The value panel shows the value of the currently focused cell, not the selected one. The focused cell has a thick black border.

We don't want to change this behavior.

As a workaround, you can specify a shortcut for revealing the calculator panel in the <kbd>Preferences</kbd> &rArr; <kbd>User Interface</kbd> &rArr; <kbd>Keys</kbd>.
