### ISSUE TITLE
Can't change the background color of some part of the screen

### ISSUE THREAD

**Issue by vds2212** [dbeaver/dbeaver#17551]
### Description

I'm busy configuring the DBeaver theme to match the Nord theme.
I have two big area where I fail to obtain what I want.

The first is the text background in the editor (but I believe it is related to issue #12591)

The second is that I can't change the background color of
- The menu
- The side bar
- The lists in dialogs

![image](https://user-images.githubusercontent.com/160393/188300553-78e46d01-70a2-4f21-ac04-809176eb4ede.png)

![image](https://user-images.githubusercontent.com/160393/188300571-1d9ce859-6ac8-4105-935c-9d13a9927416.png)

![image](https://user-images.githubusercontent.com/160393/188300581-deba65bc-d494-45bc-af78-23e6a52b8d91.png)

### DBeaver Version

Community Edition: Version 22.1.5.202208211008

### Operating System

Windows 10

### Additional context

I'm using the Dark Theme:

![image](https://user-images.githubusercontent.com/160393/188300636-f4805af3-ae73-4033-8292-6e80bff69758.png)

**Comment by emironovDB** [comment]
@vds2212 
Hi, 
Have you tried [darkest dark](https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle)?

**Comment by vds2212** [comment]
Thanks for you response :-)

It is still a bit unclear to me :-| I understand
- I need first to install the market client
- Then I could install darkest dark

I'm right?

Could you tell me how darkest dark could help me?

Could you give me some pointers about how to install the market client?

Best regards,
Vivian.

**Comment by vds2212** [comment]
I found the option (I don't know exactly how).
The new result is already much better:

![image](https://user-images.githubusercontent.com/160393/189192252-8bdfff49-5292-4dab-b451-28638d28dbd5.png)

Thanks for your support.
Best regards,
Vivian.

**Comment by E1izabeth** [comment]
You don't need to install Eclipse Marketplace. It's in the Menu->Help

![image](https://user-images.githubusercontent.com/28875055/189193218-7698dec2-5e28-4fea-a7ba-2e9d8e18d688.png)

![image](https://user-images.githubusercontent.com/28875055/189193225-10e7e3bd-5ec6-42f1-adc0-0fb48baad9ea.png)

**Comment by E1izabeth** [comment]
Darkest dark theme extension provides more flexible theme customization.

**Comment by vds2212** [comment]
Thanks for your help.
