### ISSUE TITLE
MySQL username isn't with proper back quotes when dragging/copying to SQL editor

### ISSUE THREAD

**Issue by yoni-yad2** [dbeaver/dbeaver#17554]
### Description

When copying a MySQL user from DB navigator to SQL editor it shows as:
`username@%`

or when dragging as:

`` `username@%` ``

instead of the correct way of:
`` `username`@`%` ``

### DBeaver Version

Community Edition Version 22.2.0.2022090406

### Operating System

Windows 10 64 bit

### Database and driver

MySQL / MariaDB

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @yoni-yad2

**Comment by LonwoLonwo** [comment]
Fixed.
