### ISSUE TITLE
dbeaver restarts the database and automatically reconnects

### ISSUE THREAD

**Issue by Iatbzh** [dbeaver/dbeaver#17568]
**Is your feature request related to a problem? Please describe.**

When I close dbeaver, the database is not disconnected, and the script is not closed. When I open it again, it is automatically connected, and the script appears

**Describe the solution you'd like**
It is recommended to add a button to turn off this way in the preferences
**Describe alternatives you've considered**

**Additional context**

**Comment by E1izabeth** [comment]
You can turn off automatic connection to the database on script opening by disabling the _Connect on editor activation_ preference

![image](https://user-images.githubusercontent.com/28875055/188701292-371685d9-7b93-4f2c-9245-9dd39d6f7532.png)
