### ISSUE TITLE
SAP HANA -- Ignore leading comments before anonymous blocks

### ISSUE THREAD

**Issue by JBSP-code** [dbeaver/dbeaver#17564]
Strictly speaking, it is a HANA error that occurs here, but dbeaver might circumvent it. Whenever a enclosed comment (/* */) is placed before a anonymous block and included in the statement sent to the HANA db, only statistics from the query are shown as results. Error does not occur when using single line comments (--):

```
/* Issue */
DO BEGIN
	SELECT * FROM dummy;
END;
```
![image](https://user-images.githubusercontent.com/28879598/188469738-c35f67cf-68be-4bd9-b12b-7bd475d12ae3.png)

```
-- No issue
DO BEGIN
	SELECT * FROM dummy;
END;
```
![image](https://user-images.githubusercontent.com/28879598/188470310-3896d92d-82b7-4497-950b-061520f0f3a1.png)

Could the parser be modified as to not automatically include comments before an anonymous block? SAP HANA Web-Based Development Workbench removes the comment, even when manually selecting it, such that the query produces a result. Thanks.

**Comment by LonwoLonwo** [comment]
Can be connected with https://github.com/dbeaver/dbeaver/issues/17392

**Comment by LonwoLonwo** [comment]
Hello @JBSP-code 

Thanks for the report.

As shown in the Query Manager, DBeaver sends two identical statements. 
But it seems the driver returns the result in the data form only in one case. So it can be an issue from the driver's side.  

We should look into it.

**Comment by LonwoLonwo** [comment]
![2022-09-08 18_28_22-DBeaver Ultimate 22 2 0 - MAPS](https://user-images.githubusercontent.com/45152336/189166284-f2cad6df-1086-4824-853c-245a552563da.png)
