### ISSUE TITLE
There are blank space when export the query result into spreadsheet

### ISSUE THREAD

**Issue by castielhong** [dbeaver/dbeaver#17585]
Hi, each time I export the query result into spreadsheet, there are a few space behind the value. I suppose it is to make up the maximum field due to the dbeaver default setting? And it should not be the dababase issue, because if I export the query result into spreadsheet from QMF, there is no space behind the value. 

My current solution is to use excel formula "=trim" to remove the space, but it is very unproductive...

Appreciate anyone can kindly advise how do I fix the issue. thank you.

<img width="329" alt="image" src="https://user-images.githubusercontent.com/54654953/188839234-41179a1d-ea63-4bf6-b9d8-91482800f509.png">

**Comment by icamacva** [comment]
Hi!!! I have the same problem in a 23.0.0 version. It's possible that this problem not was in older versions? I used an older version and this problem not existed. thx!
