### ISSUE TITLE
Error to Autenticate with Azure of SQL Server

### ISSUE THREAD

**Issue by DanGeekyWorld** [dbeaver/dbeaver#17593]
### Description

Cant load Java MSAL4J cant Autenticate ActiveDirectoryPassword.

Is the same Issue  with AZURE.

### DBeaver Version

22.2.0

### Operating System

Mac os Monterrey 12.5.1

### Database and driver

com.microsoft.azure:msal4j:RELEASE
1.12.0

and for SQL

com.microsoft.sqlserver:mssql-jdbc:RELEASE
9.2

### Steps to reproduce

Try to Add access to a data base on AZURE or SQL

with Active directory will not let U work on it.

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
