### ISSUE TITLE
/usr/bin/dbeaver symlink remains after uninstalling DBeaver CE from RPM file

### ISSUE THREAD

**Issue by joanbm** [dbeaver/dbeaver#17594]
### Description

If one installs DBeaver CE from the RPM file on a distribution such as Fedora Linux 36, then uninstalls it, a broken symlink at `/usr/bin/dbeaver` (pointing to a missing `/usr/share/dbeaver-ce/dbeaver` file) remains.

On Fedora this happens both when installing the package using `rpm` or `dnf`.

Aside from the orphaned/leftover file, this also causes a warning when re-installing DBeaver CE from the RPM file again it again (`warning: %post(dbeaver-ce-0:22.2.0-stable.x86_64) scriptlet failed, exit status 1`).

## Sample console session reproducing the problem
```console
foo@bar$ ls -lah /usr/bin/dbeaver*
ls: cannot access '/usr/bin/dbeaver*': No such file or directory
foo@bar$ sudo rpm -iv dbeaver-ce-22.2.0-stable.x86_64.rpm 
Verifying packages...
Preparing packages...
dbeaver-ce-0:22.2.0-stable.x86_64
foo@bar$ sudo rpm -ev dbeaver-ce
Preparing packages...
dbeaver-ce-0:22.2.0-stable.x86_64
foo@bar$ ls -lah /usr/bin/dbeaver*
lrwxrwxrwx 1 root root 29 Sep  8 02:00 /usr/bin/dbeaver -> /usr/share/dbeaver-ce/dbeaver
foo@bar$ sudo rpm -iv dbeaver-ce-22.2.0-stable.x86_64.rpm 
Verifying packages...
Preparing packages...
dbeaver-ce-0:22.2.0-stable.x86_64
ln: failed to create symbolic link '/usr/bin/dbeaver': File exists
warning: %post(dbeaver-ce-0:22.2.0-stable.x86_64) scriptlet failed, exit status 1
```

## Proposed fix
Running `rpm -qv --scripts dbeaver-ce-22.2.0-stable.x86_64.rpm` I can see there's an scriptlet that is supposed to remove that symbolic link:
```console
foo@bar$ rpm -qv --scripts dbeaver-ce-22.2.0-stable.x86_64.rpm 
[...]
postuninstall scriptlet (using /bin/sh):
#!/bin/sh

set -e

PRODUCT_MODIFIER="ce"
SYMLINK=/usr/bin/dbeaver

if [ "$PRODUCT_MODIFIER" = "ce" ] && [ -f "$SYMLINK" ] ; then
    rm $SYMLINK
fi

exit 0
```

However, this does not do what it's supposed to do, because the `[ -f "$SYMLINK" ]` condition checks if the *target* of the symlink exists, and since this is a *post*uninstall script, it will fail.

**A potential fix is to just change the scriptlet to a *pre*uninstall script**.
In fact, this problem doesn't reproduce on the .deb package precisely because there this is a preuninstall script.
(I'd submit a PR, but it appears that the RPM package generation code is not publicly available)

### DBeaver Version

Community Edition 22.2.0

### Operating System

Fedora Linux 36

### Database and driver

Not database nor driver related.

### Steps to reproduce

1. Set up a clean install of Fedora Linux 36
2. Download the DBeaver CE 22.2.0 RPM file (`dbeaver-ce-22.2.0-stable.x86_64.rpm`, the latest available version at the time of writing)
3. Install the package from the RPM file, e.g. by running `sudo rpm -iv dbeaver-ce-22.2.0-stable.x86_64.rpm`.
4. Uninstall the package, e.g. by running `sudo rpm -ev dbeaver-ce`
5. Observe how a broken symlink remains at `/usr/bin/dbeaver`, e.g. by running `ls -la /usr/bin/dbeaver`.
6. Try to re-install the package again, e.g. by running `sudo rpm -iv dbeaver-ce-22.2.0-stable.x86_64.rpm`.
7. Observe that a warning `ln: failed to create symbolic link '/usr/bin/dbeaver': File exists` is printed.

### Additional context

Clean Fedora 36 install.

**Comment by flambchap** [comment]
Thank you for your report and investigation. We'll fix that for sure.
