### ISSUE TITLE
UTF16 String size is 2098200574, should be less than 1073741823 

### ISSUE THREAD

**Issue by davidh-cloudster** [dbeaver/dbeaver#17595]
### Description

My question is similar to #12510 
System information:
OS: Windows 10 Home
DBeaver: DBeaver Community 22.2.0

In the dbeaver.ini , I have the following setting:

-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx4096m
-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT
-Ddbeaver.distribution.type=exe

I only changed the old value to -Xmx4096m.
I had Java heap space Error before I change the old value
However, after I changed the value to -Xmx4096m, the Java heap space error is gone and I got a new error:
UTF16 String size is 2098200574, should be less than 1073741823

I tried to reset workspace and use dbeaver.exe or dbeaver-cli.exe to open DBeaver
Both ways give me the same error
What should I do?

The SQL file that I am trying to run is 16.4 GB
Is it the cause of the error?

### DBeaver Version

DBeaver Community 22.2.0

### Operating System

Windows 10 Home

### Database and driver

Database name and version: MySQL 5.7
Server OS: ubuntu 20.04

**Comment by ShadelessFox** [comment]
Hello @davidh-cloudster,

You are trying to load a 16.4 GB file, which causes the issue.

Even with 32 GB of RAM, it would be impossible due to the limitations of the Java platform.

So don't open such big files.

**Comment by davidh-cloudster** [comment]
Hi @ShadelessFox  
Thanks for the reply
If I have to import all the data in the 16.4 GB file, would file split be a good way to do it?
The file contains lots of queries, if I can split the huge file into, let's say ten 1.64GB files
Would it be a good approach? 
Also, I wonder what is the max file size that the Java platform can run.
Thanks for your time.

**Comment by ShadelessFox** [comment]
Yes, you can split your file into chunks. Each chunk should be 1.0 GB at most (the number mentioned in error divided by 2^30).

Unfortunately, the Eclipse platform DBeaver is built on handles such big files poorly when it comes to rendering them as text.

So even a 500 MB file can make DBeaver irresponsible.
