### ISSUE TITLE
Mistranslation between GBK and UTF8 

### ISSUE THREAD

**Issue by sssqwe** [dbeaver/dbeaver#17590]
I'm having a problem with DBeaver and Mysql. I used DBeaver to create and insert data(chinese character included)  into the table on a virtual machine. However, after I inserted the data. The data been inserted changed to 斯锟铰达拷 which is a result of mistranslation between UTF-8 and GBK. The question is the Mysql DB on VM is all set to UTF8. I don't know how such mistranslation has happened. Can someone look into it? Thanks! (I tried change every character setting to UTF8MB4 and GBK as well, it gave me the same result)

![insert截图](https://user-images.githubusercontent.com/94358582/188966593-5c7f6b44-0e6a-424c-bd8f-439fbb4b0b04.jpg)
![vehicletype数据截图](https://user-images.githubusercontent.com/94358582/188966595-2c5e5cb6-eb39-433f-818c-e1c81c5bfb92.png)
![数据库UTF8设置](https://user-images.githubusercontent.com/94358582/188966598-737028fd-1bfb-426d-a1d1-e26c02fca925.jpg)

![create截图](https://user-images.githubusercontent.com/94358582/188966588-ad72d8d5-7559-42a2-8914-365f6bc4d536.jpg)
![DBeaver设置](https://user-images.githubusercontent.com/94358582/188966591-c19dbeb2-7712-45ab-8ca9-9bfc11deb8da.jpg)
)

**Comment by emironovDB** [comment]
@sssqwe 
Hi,
Could you provide the data example?

**Comment by sssqwe** [comment]
I don't quite understand what data example are you referring. If you are talking about my SQL files. I uploaded my create and insert SQL files to: https://github.com/sssqwe/Mistranslation-of-SQL.git.

**Comment by Matvey16** [comment]
@sssqwe I wasn't able to reproduce it with your SQL files.

Can you please check what result you would get if you execute SELEct for this table in another client (e. g. command line)

![image](https://user-images.githubusercontent.com/82543000/195578779-caa339a1-de0b-4921-abcb-b6270abb58ec.png)

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
