### ISSUE TITLE
UPDATE statement generation without WHERE

### ISSUE THREAD

**Issue by pamamu** [dbeaver/dbeaver#17608]
### Description

PRECONDITIONS:
- DB2 Database.
- Select using script.
- Script select without PRIMARY KEY.

STEPS:
1. Execute Query and works properly.
2. Select all the rows and columns in the Grid Panel.
3. Right Click -> Generate SQL -> UPDATE.

EXPECTED RESULT:
- Update Statements with the following syntax "UPDATE xxxx SET a=y WHERE b=z"

ACTUAL RESULT:
- Update Statements with the following syntax "UPDATE xxxx SET a=y" -> Missing WHERE clause.

Note: When I click on "DELETE by Unique Key" and select again "UPDATE", it works properly (statements with UPDATE-SET-WHERE).

### DBeaver Version

Community Edition 22.2.0.202209051344

### Operating System

Windows 10 Enterprise 21H2

### Database and driver

DB2 for Linux/Unix/Windows driver

### Steps to reproduce

1. Execute Query and works properly.
2. Select all the rows and columns in the Grid Panel.
3. Right Click -> Generate SQL -> UPDATE.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by LonwoLonwo** [comment]
Hello @pamamu 

Unfortunately, I can't reproduce it in DBeaver 22.3.2.
Can you please check the latest DBeaver version?

![2023-01-09 14_23_09-Generated SQL (SAMPLEDB)](https://user-images.githubusercontent.com/45152336/211313177-7cd2a4ff-8d1a-493d-bddf-d2ce7626b77c.png)

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
