### ISSUE TITLE
dbeaver fields are not fully displayed

### ISSUE THREAD

**Issue by GitHubzjh1997** [dbeaver/dbeaver#17604]
![Snipaste_2022-09-09_11-40-09](https://user-images.githubusercontent.com/83394483/189271078-109bc024-d041-4eac-9290-0b993d23ebea.jpg)
![Snipaste_2022-09-09_11-34-52](https://user-images.githubusercontent.com/83394483/189266700-96f8e35a-03ce-46fe-b051-efce60a29484.jpg)
### Description

1.I created a new CREATE USER ID field in Navicat
2.This field is not displayed in dBeaver
3.But if you create a new field in dBeaver with the same name, it will indicate that the field already exists
4.Select * also fails to query this field
5.But you can find out by specifying the field name select

### DBeaver Version

22.2.0

### Operating System

windows11

### Database and driver

oracle

**Comment by GitHubzjh1997** [comment]
![Uploading Snipaste_2022-09-09_11-33-56.jpg…]()

**Comment by LonwoLonwo** [comment]
Hello @GitHubzjh1997 

Did you refresh your table after column creation in Navicat?

**Comment by GitHubzjh1997** [comment]
Of course。
![Snipaste_2022-09-09_20-04-45](https://user-images.githubusercontent.com/83394483/189346134-91af5c37-4666-4cb4-a272-c2fc9d89f8cf.jpg)
And you can't find out using select*, so I don't think it has anything to do with refreshing
But the fields do exist in the table。
![Snipaste_2022-09-09_20-06-24](https://user-images.githubusercontent.com/83394483/189346458-d80e9466-9e67-45d1-91fa-b70b80792d2b.jpg)

**Comment by LonwoLonwo** [comment]
Ok. How about DBeaver restart?
And if it will not help - can you please check your column in DDL? DBeaver reads table DDL from the server. And Please provide this DDL here.

**Comment by GitHubzjh1997** [comment]
Well, I found out why by looking at DDL.I accidentally selected invisible when creating the field.Thank you for your help, sorry for asking a naive error.
