### ISSUE TITLE
REQ: New shortcut key for "SQL Editor -> New SQL Script"

### ISSUE THREAD

**Issue by kikonen** [dbeaver/dbeaver#17601]
**Is your feature request related to a problem? Please describe.**
Current shortcut key for "SQL Editor -> New SQL Script" action is *extremely cumbersome. It seems to be "CTRL + ]"

Producing "]" requires pressing "ALTGR + 9", which means that full combination would be "CTRL + ALTGR + 9"
=> and that does not seem to work

**Describe the solution you'd like**

Easier shortcut key for opening new SQL script tab

**Describe alternatives you've considered**

none, is there alternatives?

**Additional context**

i18n :)

**Comment by uslss** [comment]
New SQL script also could be created with Ctrl+F3. BTW, the shortcut could be changed in Preferences. Does it resolve your issue?
![image](https://user-images.githubusercontent.com/31996417/190172117-37110509-5164-4cc8-b1cb-ce688ee05657.png)

**Comment by kikonen** [comment]
Marvellous! Didn't realize there is such binding logic. It absolutely resolves issues (existence of CTRL + F3 by itself already did, but possibility to adjust can be useful)
