### ISSUE TITLE
Why I can not login ib Dbeaver with valid postgreSql credentials?

### ISSUE THREAD

**Issue by sergeynilov** [dbeaver/dbeaver#17603]
### Description

I try to login from my Dbeaver 22.0.4 to postgreSql 12.11 under local kubuntu 20,
but got error:

    FATAL: password authentication failed for user "postgres"

In Dbeaver db settings user/password are “postgres” - they are valid, as I login with this credentials in pgphpadmin :
https://prnt.sc/KDIUsmZgiERO

Are there some other settings invalid ?

Thanks!

### DBeaver Version

Dbeaver 22.0.4 

### Operating System

kubuntu 20

### Database and driver

postgreSql

**Comment by LonwoLonwo** [comment]
Hello @sergeynilov 
Can you please try to change host to localhost? I hope it will help.

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
