### ISSUE TITLE
Cannot connect to databases

### ISSUE THREAD

**Issue by AS-WM** [dbeaver/dbeaver#17606]
### Description

Hi I appear to be having an issue connecting to postgres databases via dbeaver. I have checked and the credentials have worked on the same machine using pgadmin, so it is an issue specific to dbeaver and not an issue with the databases themselves.

Whenever I try and connect to a postgresql database I get the following error
SCRAM authentication is not supported by this driver. You need JDK >= 8 and pgjdbc >= 42.2.0 (not ".jre" versions)

Via Command Prompt my openjdk version "11.0.14.1" 2022-02-08 so that meets >= 8
Looking at driver manager my postgresql- 42.2.23.jre6 so that meets 42.2.0 criteria.

### DBeaver Version

Community Edition 22.2.0

### Operating System

Windows 10

### Database and driver

PostgreSQL 14
postgresql- 42.2.23.jre6

**Comment by Destrolaric** [comment]
@AS-WM  Hi, I think this happens due to the driver being compiled for `.jre6`. You should use a different driver, for example, `postgresql-42.2.25.jar`

**Comment by AS-WM** [comment]
@Destrolaric tried that. Have JDK 11 now and postgresql-42.4.0.jar. Still comes up with the same error of

SCRAM authentication is not supported by this driver. You need JDK >= 8 and pgjdbc >= 42.2.0 (not ".jre" versions)

Which JDK 11 >= 8 and 42.4.0.jar. >= 42.2.0

**Comment by AS-WM** [comment]
Fixed the issue. It appears that DBeaver was holding on to an outdated library, which was being checked first, and therefore failing the test.

Steps to solve issue.
1. Download latest JDBC and move to \Program Files\DBeaver\shared_drivers
2. Open DBeaver and click Database -> Driver Manager
3. Double click on PostgreSQL
4. Under libraries click Add file and find the new JDBC
5. Delete any of the previous libraries, so it remains the only one
