### ISSUE TITLE
Multiple underscores in table names get truncated to one when exporting a table to a file

### ISSUE THREAD

**Issue by AviSarmani** [dbeaver/dbeaver#17614]
### Description

Multiple underscores in table names get truncated to one when exporting a table to a file

### DBeaver Version

Community edition 22.2.0

### Operating System

Win 10

### Database and driver

Postgres but have also reproduced under Clickhouse so I don't think it's DB related

### Steps to reproduce

1. Create a table that has multiple underscores in it's name:
```
CREATE TABLE test____2 (
	some_column varchar NULL
);
```
2. Try to export it to a CSV file
3. For simplicity, in the "File name pattern", enter "${table}"
4. The file will be created with only one underscore test_2.csv instead of test____2.csv

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @AviSarmani 

Note for the future: StreamTransferConsumer#stripObjectName
