### ISSUE TITLE
Filter history dropdown: Query preview text apparently is partly using a foreign codeset

### ISSUE THREAD

**Issue by TheMechanist902** [dbeaver/dbeaver#17613]
### Description

When you activate the dropdown menu of recently applied filters, the preview for the query partly uses a foreign set of symbols (In my case some sort of Asian codeset)
![image](https://user-images.githubusercontent.com/8171872/189495385-b2474ddc-da80-43bb-a3f1-f8891791fbe2.png)

It's a purely visual nag, but a fix would be appriciated if somebody finds the time.

### DBeaver Version

dBeaver CE 22.2.0.202209080956

### Operating System

Windows 10

### Steps to reproduce

1. Apply at least two different filters to your current query result set
2. Switch back some filters with the green arrows, until the small dropdown arrow downwards appears
3. The query preview will be in what seems to be an Asian codeset

### Additional context

I use the English user interface setting, but my OS locale is set to German

**Comment by Matvey16** [comment]
@TheMechanist902 Hello. What type of columns does your table have? Does it happen with any query or something specific. Also can you check if the query in Query Manager has the same issue.

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
