### ISSUE TITLE
Support Amazon Redshift Serverless IAM Authentication

### ISSUE THREAD

**Issue by iklose** [dbeaver/dbeaver#17616]
DBeaver supports IAM authentication for Redshift Clusters. One of the mandatory parameters for this is cluster_id. The newly introduced Amazon Redshift Serverless service does not use a cluster_id but a workgroupname parameter for connections. Therefore currently there is no way to use DBeaver with Amazon Redschift Serverless as the current set-up is trying to use cluster_id and o connect to a Redshift Cluster by default. 

In my opinion there are two was to solve this problem. Either add a workgroupname parameter and check if either workgrouname or cluster_id is filled. Secon option would be to introduce some flag like is_serverless and then take cluster_id as the workgroupname.

Thanks for your support and the great tool!

**Comment by LonwoLonwo** [comment]
Thanks for the report @iklose 

Probably we can add a new option somewhere here in the Connection Settings:

![2022-09-12 13_14_56-DBeaver Ultimate 22 2 0 - _localhost_ Script-34](https://user-images.githubusercontent.com/45152336/189629784-f14b73de-cf52-43be-811c-353a9bb693d1.png)

**Comment by markervie** [comment]
Does the current version of  DBeaver Community editionsupport IAM authentication for Redshift Clusters ?

Are there any other key IAM authorization-related Driver properties beyond "ClusterID" that are required ?

Asking b/c I'm consistently getting a "Connection Timed Out" error in DBeaver Community edition (see attached screenshot) even after verifying that the following parameter DO enable me to connect using the SQL Workbench Tool:
- DBNAME: {database}
- DBUser: {user}
- Endpoint URL <jdbc:redshift:iam://{svc nam. us-east-1.redshift.amazonaws.com:5439/{database}
- Host :  localhost
- plugin_name:  com.amazon.redshift.plugin.BrowserSamlCredentialsProvider
- sslmode:  verify-ca
- uid:  <my user id >
- login_url:  <federation svcs url >
- preferred_role:  < preferred role name >

**Comment by LonwoLonwo** [comment]
Hello @markervie 

Only PRO DBeavers versions support IAM authentication for Redshift.

**Comment by markervie** [comment]
> Hello @markervie
> 
> Only PRO DBeavers versions support IAM authentication for Redshift.

Thanks for that confirmation, LL.

**Comment by markervie** [comment]
LL - by PRO DBeaver versions, you're referring to both the Enterprise and Ultimate versions as listed @ the product website https://dbeaver.com/edition/, correct ?

**Comment by iklose** [comment]
Hi,

Sorry for the late reply...I was able to make IAM authentication work with the Comunity edition - but only for Redshift clusters not Serverless.

Steps:

In driver management change URL template: jdbc:redshift:iam://{host}:{port}/{database}

In main connection setting:

- Host: localhost if SSH tunnel is used, otherwise Redshift Endpoint. 
- Port: 5439 as standard Redshift port or the port that is configured in the SSH tunnel Set-Up
- Database: database name

Driver properties:
AutoCreate: true - Will create the DbUser if it does not exist in Redshift already
ClusterID: Name of cluster (not endpoint) 
DbGroups: What Redshift Group to join in order to get the right permissions
DbUser: The user name to be used 
IAMAuth: true
Profile: The Lokal AWS profile to use that has the connection tokens 
Region: The AWS region of the redshift cluster

SSL must be also activated.

Hope this information helps.

Best regards,
Ingo

P.s. This set-up does not work with Redshift Serverless since the ClusterId property is mandatory in DBeaver but not used with serverless connections, for that we need a WorkgroupID or some DBeaver internal logic that renames the property when connection to Serverless is needed.

**Comment by Matvey16** [comment]
Verified

**Comment by SmartCo-Ryan** [comment]
For future reference, I was now able to set up a Redshift serverless connection with IAM Authentication work with the Community Edition by using the following options. 

```
isserverless=true
region={region}
serverlessacctid={account-id}
serverlessworkgroup={workgroup}
```

++ Checking the SSL box in the SSL tab (without any other options configured)
