### ISSUE TITLE
Query result column width autofitting or setting column width

### ISSUE THREAD

**Issue by sonerfromnurland** [dbeaver/dbeaver#17625]
I would like to see columns autofit when looking at results from database. Often I do work with data that are wider than column width and adjusting that manually is just pain. I would like to be able to set it up so, that this will be done automatically.
For reference, please see for example how Oracle SQL Developer does this. Or, we should be able to set determined width to the resulting query table.

**Comment by sonerfromnurland** [comment]
Actually, it can e done as following. It fills the bills.
![74865202-c952ea00-531e-11ea-85e8-fb67af37fe6a 1](https://user-images.githubusercontent.com/99599870/189653306-e19eb4fe-bb29-4b6d-a14a-232e544a658d.gif)

**Comment by LonwoLonwo** [comment]
Hello @sonerfromnurland 

So, as you mentioned - you can use "Columns width: Fit values". Does this option solve your request?

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.

**Comment by doerwalter** [comment]
I started using DBeaver a few days ago (for working with Oracle), and this is one of the most annoying missing features of DBeaver.

In most of our tables all columns have a prefix (for example in the table `customer` there are column `cus_id`, `cus_firstname`, `cus_lastname`, etc.).

So when I execute a `select * from customer;` all I see is this:

![Bildschirm­foto 2022-12-08 um 11 53 31](https://user-images.githubusercontent.com/1387028/206429053-814f4f93-4040-463e-89cb-99b95838c200.png)

For each column I only see `CU` as the column name. What are those four column that have `null` values? I always have to use the mouse to make the column wider. Neither "Column width: fit screen" nor "Column width: fit values" does the right thing.

And for the next query I have to do that mouse dance again.

What I would want to have is a "Column width: fit title and values" and I would like to be able to make that the default for all queries, all connections and all databases.

**Comment by doerwalter** [comment]
OK, I think I found the right preference option that fixes that: "Calculate column width by cell value" under "Preferences" -> "Editors" -> "Data Editor" -> "Appearance". When I deselect that option, the select ressult looks much nicer.
