### ISSUE TITLE
Sequence DDL is not refreshed with a corresponding button

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#17621]
### Description

If the DDL of a sequence is opened in metadata editor, any changes to it won't be updated after any refresh. Only after object is closed and reopened

### DBeaver Version

22.2.0

### Operating System

Any

### Database and driver

Vertica Database 12.00.0000
vertica.jar 12.00.0100

### Steps to reproduce

1. Open a sequence from the navigator
2. Change something through UI (e. g. change a comment)
3. Save changes
4. Click refresh

**Expected:** DDL is updated
**Actual:** Nothing changes

### Additional context

![dbeaver_aF7Kdxu78o](https://user-images.githubusercontent.com/82543000/189634045-67968f6f-ce73-401d-bf24-d96bff04cd67.gif)

**Comment by LonwoLonwo** [comment]
Also, please check Snowflake sequences in EE too.
