### ISSUE TITLE
[Snowflake] Supports materialized views

### ISSUE THREAD

**Issue by Ravi5308** [dbeaver/dbeaver#17622]
### Description

I have connected to Snowflake through DBeaver and created a materialized  view . When deleting the materialized  view by right click on view object, getting an error " **SQL Error [2203] [02000]: SQL compilation error: Object found is of type 'MATERIALIZED_VIEW', not specified type 'VIEW'.
  SQL compilation error: Object found is of type 'MATERIALIZED_VIEW', not specified type 'VIEW'.**"
any other way to delete the view with out using **DROP** statement.?
![image](https://user-images.githubusercontent.com/9348512/189634460-582f9bb4-2592-4972-a27c-fb19b7f421ef.png)

![image](https://user-images.githubusercontent.com/9348512/189634270-acdcda91-a221-4cc6-9dbc-b8cbba6729a3.png)

### DBeaver Version

Version 22.1.2.202207091909

### Operating System

Windows

### Database and driver

Snowflake

### Steps to reproduce

1. Create a materialized view
2. Right Click on created materialized  view
3. Select Delete.
![image](https://user-images.githubusercontent.com/9348512/189634733-b4791c4c-f140-410e-a560-7d8c70243a3a.png)

### Additional context

NA

**Comment by LonwoLonwo** [comment]
Hello @Ravi5308 

Thanks for the bug report.

Can you please check the type of your view in the properties tab? Is it VIEW or MATERIALIZED VIEW?

![2022-09-12 18_24_47-DBeaver Ultimate 22 2 0 - NEWVIEW](https://user-images.githubusercontent.com/45152336/189693741-e1d13fe3-2bb4-4e7c-bf45-fec247c13689.png)

**Comment by LonwoLonwo** [comment]
Note for the future: https://docs.snowflake.com/en/sql-reference/sql/create-materialized-view.html

> Materialized views require Snowflake Enterprise Edition.

**Comment by Ravi5308** [comment]
Actually the object is MATERIALIZED view, 
![image](https://user-images.githubusercontent.com/9348512/189696312-1c72033d-f29a-4ff7-9ab3-ffc63c15f53c.png)

But, Showing it as VIEW.
![image](https://user-images.githubusercontent.com/9348512/189696471-9dbe6a38-bac4-4bdb-9b72-85d8e6ff9f09.png)

**Comment by LonwoLonwo** [comment]
Ok, thanks for the answer.
