### ISSUE TITLE
Network connection proxy settings and plugins  are reset after each upgrade

### ISSUE THREAD

**Issue by GaryLiuTelus** [dbeaver/dbeaver#17626]
### Description

All settings in Preference -> General -> General Connections lost and are reset after each upgrade. 
Also, the plug-in installed from 3rd party sources lost after each upgrade. 

### DBeaver Version

Community 22.2.0.202209051344

### Operating System

Windows 10 Enterprise 20H2

### Steps to reproduce

1. Make some changes in 'Preference' -> 'General' -> 'Network Connections', such as adding a line of 'proxy bypass'.
2. When the new version prompt pop out, choose upgrade, and make sure to deselect 'reset settings'
3. Check Network Connection settings after upgrade, all changes are reset. 

1. Install Eclipse plug in Vrapper using instructions from https://shehuawwal.com/installing-vim-extension-module-for-dbeaver-with-vrapper/.
2. upgrade when prompted 
3. The Vrapper disappeared after upgrade.

**Comment by uslss** [comment]
thanks for the report.
proxy issue will be resolved in #16215 
issue with plugins - #5317
