### ISSUE TITLE
"Insert Case" for Code Completion cannot correctly insert certain case sensitive functions in Clickhouse

### ISSUE THREAD

**Issue by eschaubert** [dbeaver/dbeaver#17635]
### Description

Some functions were added to the code completion dictionary for clickhouse, but when inserting them, the "insert case" as per settings for code completion in DBEAVER can only be either UPPER or LOWER or DEFAULT. But this does not work for Clickhouse specific function, which are all case-sensitive. The case sensitivity is by design and was a deliberate decision by the clickhouse developers

For example the function: toStartOfMonth() works only if its written exactly like that and tostartofmonth() or TOSTARTOFMONTH() will not work.

This case-sensitivity for clickhouse specific function cannot be changed via server-side settings.

### DBeaver Version

Community Edition 22.1.5

### Operating System

Linux PopOs

### Database and driver

Clickhouse 
Yandex ClickHouse driver (server version 21.3+)

**Comment by LonwoLonwo** [comment]
Ok, thanks for the report. We will see what we can do.
