### ISSUE TITLE
Create or replace procedure from sql editor window

### ISSUE THREAD

**Issue by rat1borik** [dbeaver/dbeaver#17638]
Does not update db tree (metadata) for postgres when run create or replace function. It\`s necessary to go in db tree, find node and refresh this node by f5 or context menu (it\`s take so much time). Another solution is reconnect to db but this is awful of course. Please refresh dbtree more frequently.

**Comment by uslss** [comment]
thanks for the suggestion.
close as a duplicate of #6398
