### ISSUE TITLE
Snowflake procedure creation fails in DBeaver, not in Snowflake

### ISSUE THREAD

**Issue by HansKappert-Eneco** [dbeaver/dbeaver#17636]
### Description

I cannot create a snowflake procedure that has a CASE statement in one of it's statements.

### DBeaver Version

22.1.4.202208051447
22.2.0.202209051344

### Operating System

Win 11

### Database and driver

net.snowflake:snowflake-jdbc:RELEASE [3.13.6]

### Steps to reproduce

Running this script:

```
CREATE OR REPLACE PROCEDURE does_not_work_from_dbeaver()
RETURNS NUMBER(1,0)
LANGUAGE SQL
EXECUTE AS CALLER
AS $$
	BEGIN
		
		SELECT  1
			,CASE 
				WHEN TRUE THEN '1' 
				ELSE '2' 
			END AS col1
		;
		
	END;	
$$;

```
in DBeaver gives this error:

```
Error occurred during SQL query execution

Reason:
SQL Error [1003] [42000]: SQL compilation error:
parse error line 15 at position 4 near '<EOF>'.
syntax error line 5 at position 4 unexpected '$'.

```
After much effort I found that the END of the CASE statement is giving DBeaver troubles. When I remove the case statement from the query, the code is accepted.

**Comment by LonwoLonwo** [comment]
Hello @HansKappertEneco 

Did you try to highlight all your query and then execute?

![2022-09-14 10_51_03-DBeaver Ultimate 22 2 0 - _TEST_DB_ Script-17](https://user-images.githubusercontent.com/45152336/190094556-b8bd1cba-c083-4ef2-be70-e4255507758f.png)

Also I see many empty lines in your statement. By default DBeaver recognizes empty lines as delimiters (then you do not have highlighting). You can change this behavior in the Preferences.

![2022-09-14 10_52_49-DBeaver Ultimate 22 2 0 - _TEST_DB_ Script-17](https://user-images.githubusercontent.com/45152336/190094751-6f7e2974-6e6e-4014-8abd-7ef040cca70b.png)

**Comment by HansKappert-Eneco** [comment]
Hi Anastasiya,

Yes I did that.
I am getting this:
![image](https://user-images.githubusercontent.com/103498525/190354412-f319cd5a-11d0-4fa3-8cc2-e8cf2e101e79.png)


And these are my settings. They look identical to me:
![image](https://user-images.githubusercontent.com/103498525/190354516-bacfe638-3def-4317-b175-6af724de974d.png)


When I change the query part as follows, it is accepted:
![image](https://user-images.githubusercontent.com/103498525/190354658-796576bf-af93-40a8-b4d8-4d14ec6710a5.png)

It appears as if you are able to create the procedure. I wonder why.

Kind regards,
Hans Kappert

**Comment by LonwoLonwo** [comment]
Hello @HansKappertEneco 

I suggest that you add screens from your e-mail in the answer, but I can't see them here. Please reload screens here, on the GitHub page directly.

**Comment by HansKappert-Eneco** [comment]
Did so, see above. Thanks a lot for helping me!

**Comment by HansKappert-Eneco** [comment]
By accident we found out why this occurs.
It fails when I use "Execute as script" (what I needed to do before I think)
It succeeds when I use "Execute SQL statement"
Not sure if behaviour was changed.

**Comment by LonwoLonwo** [comment]
You can check this instrument: https://github.com/dbeaver/dbeaver/wiki/Query-Manager 

You can see there - what statements do you execute.

**Comment by HansKappert-Eneco** [comment]
Thank you. Now that my problem is solved, we can close this ticket.
Kind regards,
Hans Kappert
