### ISSUE TITLE
Do not expand code groups after query execution

### ISSUE THREAD

**Issue by dimkas78** [dbeaver/dbeaver#17640]
DBeaver 22.2.0
Database - ClickHouse 22.

I have long query with several CTE in beginning.
So I decide to collapse CTE text by grouping feature of text editor, something like this (comments is in russian, nevermind):
![Снимок экрана 2022-09-14](https://user-images.githubusercontent.com/61900705/190045970-a5c0e0c6-3325-4ffc-bb50-e6f1a649a766.png)
But after executing query all this groups become expanded, and I again can't see whole query structure on one screen.

I think, it is not nessesary to open code group after query execution. Please, change behaviour of DBeaver and let me control state of this groups mannualy.

**Comment by dbeaver-pm** [comment]
Hello @dimkas78,

Thanks for the bug report
