### ISSUE TITLE
Chinese on button of tabs "Close All" is error

### ISSUE THREAD

**Issue by SSSDNSY** [dbeaver/dbeaver#17641]
### Description

Right click on one tab and the Chinese of close all button is Error ,it's shoud be "关闭全部" or “全部关闭”，but it is "关闭关闭“,its mean "close close" not  "close all".

### DBeaver Version

22.2.0.202209051344

### Steps to reproduce

1、open >2 tabs include Sciprt or Connections
2、Right click on one tab and the Chinese of close all button is Error ,it's shoud be "关闭全部" or “全部关闭”，but it is "关闭关闭“,its mean "close close" not  "close all".
![image](https://user-images.githubusercontent.com/15624361/190072176-6c20ddf1-eac4-4e62-b578-23d220a512f6.png)

### Additional context

![image](https://user-images.githubusercontent.com/15624361/190071655-13a0dabe-5c75-48dd-925b-343ad295a368.png)

**Comment by SSSDNSY** [comment]
may be your guys can help me to commit good first PR ，thanks

**Comment by E1izabeth** [comment]
Thank you for bug report.
You can find instructions here https://github.com/dbeaver/dbeaver/wiki/Localization

**Comment by E1izabeth** [comment]
Please, let me know if you are going to create pull request. Otherwise we could fix it by ourselves.

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/discussions/16825

**Comment by SSSDNSY** [comment]
> Thank you for giving the instructions~

**Comment by LonwoLonwo** [comment]
"Close All" is not the DBeaver button but Eclipse. You can't find the localization in our files.

You can try to find or create a ticket about this localization issue here: https://bugs.eclipse.org/bugs/

**Comment by SSSDNSY** [comment]
well,its funny  QAQ

**Comment by SSSDNSY** [comment]
this bug still exist,could you give me more information for this bug about eclipse localization?
@LonwoLonwo

**Comment by MashaKorax** [comment]
fixed
