### ISSUE TITLE
Bug: Changing connection doens't works well

### ISSUE THREAD

**Issue by LucioMenci** [dbeaver/dbeaver#17643]
### Description

Changing connection configuration when you have a window with that connection doesn't works well

### DBeaver Version

22.2.0.2022090513

### Operating System

Win10

### Database and driver

Driver: DB2 LUW

### Steps to reproduce

1- Open a connection with a particular default schema
2- Open a new window with that connection
3- Write a SQL without using schema names, with tables in another schema --> you will have error Object Name doesn't exists
4- Edit the connection changing the schema and confirm the connection change --> you will have the same error
5- Disconnect and reconnect --> you will have the same error

### Additional context

Workaround: Change the active datasource --> rechange the active datasource to the previous one --> yuou won't have the same error

**Comment by uslss** [comment]
@LucioMenci, unfortunately, cannot reproduce it. Could you provide a video with the issue or some screenshots that can help to reproduce an issue?

**Comment by LucioMenci** [comment]
Hi Dziyana,
Thank you for the quick reply.

This is the Start point:
![Snap1](https://user-images.githubusercontent.com/15246491/190176677-82f985bb-139a-47e9-ae03-d9721a985fc4.png)

BBCLIPT is not into DB2ADMIN schema, buti t is into FINANCE schema.

I don’t want the connection Raspini – Pth02 has the default schema DB2ADMIN. I tried to change it into the connection configuration form:
![Snap3](https://user-images.githubusercontent.com/15246491/190176683-1dc2779c-8fc6-4704-bae0-b5a8b8fb6ba9.png)

And confirm it:
![Snap4](https://user-images.githubusercontent.com/15246491/190176690-82f29964-75f1-4ce1-b41a-81688ba73260.png)

I see for a short time disappearing the default schema:
![Snap2](https://user-images.githubusercontent.com/15246491/190176682-04510f3e-1ebd-4d72-9c27-3fd32e0c8ac1.png)

And I espect that bring up the right one, but will bring up the old one:
![Snap1](https://user-images.githubusercontent.com/15246491/190176677-82f985bb-139a-47e9-ae03-d9721a985fc4.png)

If I change the schema, yes, it runs, it is obvious, but also changing the connection and selecting again the old one, the default schema is the right one, that it is was I espected when I choose to reconnect:
![Snap5](https://user-images.githubusercontent.com/15246491/190176693-027c2fa9-ca3c-4639-ae20-e67bb01896af.png)

**Comment by uslss** [comment]
Sorry for the late response. It seems it is expected behavior for SQL editor - https://github.com/dbeaver/dbeaver/wiki/SQL-Editor

If you have some ideas on how to improve the SQL editor, you can create a feature request.
