### ISSUE TITLE
Apache Hive Default Keyword Case Should Be Set To UPPER

### ISSUE THREAD

**Issue by JesseFL** [dbeaver/dbeaver#17657]
### Description

Apache Hive default keyword case is probably undefined.  Auto-convert keyword case is not working.
![image](https://user-images.githubusercontent.com/17784067/190396933-cb5e1fee-d9cd-4849-bf6e-f8f1186f4d49.png)

Apache Hive default keyword case should be set to UPPER.

### DBeaver Version

Commuinity 22.2.0

### Operating System

Windows 10

### Database and driver

Apache Hive
Cloudera Driver

### Steps to reproduce

Connect to Apache Hive
Type select [space] and observe the keyword case is not transformed to upper.

### Additional context

Hive default keywords are UPPER and can be observed in the official language manual examples
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Select

**Comment by LonwoLonwo** [comment]
Hello @JesseFL 

I can't reproduce, unfortunately.

Can you please check this setting?

![2022-09-16 18_07_44-Preferences](https://user-images.githubusercontent.com/45152336/190671456-4d3fa2e7-2fb9-4545-89a1-8015ba747d30.png)

**Comment by JesseFL** [comment]
@LonwoLonwo 
My setting looks like yours, Code Completion is set to Insert Case Default.

Can you please check this setting?  Is your code formatter also set to default?
![image](https://user-images.githubusercontent.com/17784067/190710680-54b0849e-e003-4ab2-8f7f-783d38e1a48a.png)

Also I am not using the included Hive driver, I am using 3rd party Cloudera driver.  Maybe that is related?

**Comment by LonwoLonwo** [comment]
> I am using 3rd party Cloudera driver. Maybe that is related?

It can be because the driver returns info about the default keywords case.

Can you please provide a video of your issue?

**Comment by JesseFL** [comment]
Here is a video.
Should I open as a bug with Cloudera team?
![2022-09-20_07-36-03](https://user-images.githubusercontent.com/17784067/191247952-4df5853b-3204-4b49-9ff2-eeee4d6114d4.gif)

**Comment by LonwoLonwo** [comment]
I can't reproduce your issue with hive-jdbc-uber-2.6.5.0-292

![5K3cBMuinS](https://user-images.githubusercontent.com/45152336/191674929-6009ba5a-dc97-4cc8-b8b7-23fde94e9989.gif)

Probably this is how the Cloudera driver works.

I think you can just set all auto-complete settings from "default" to "upper".

**Comment by JesseFL** [comment]
Yes, I will.  Thank you for checking into it.

**Comment by Donal-Goggin** [comment]
I have this issue now too. It was working up until a few days ago and I can't figure out what changed. All settings releated to formatting are set correctly but they do nothing anymore.

**Comment by LonwoLonwo** [comment]
Hello @Donal-Goggin 

Probably your issue is described here: https://github.com/dbeaver/dbeaver/issues/18131

**Comment by Donal-Goggin** [comment]
Yes that looks like my exact problem. Thank you for linking it
