### ISSUE TITLE
Data Formatting not working when exporting result set

### ISSUE THREAD

**Issue by samuelguesnier** [dbeaver/dbeaver#17659]
### Description

When I export the data , DateTime format is YYY-MM-dd whereas it should be YYYMMdd

![Capture](https://user-images.githubusercontent.com/24391067/190405655-a675484b-a2e7-4933-a1f4-8319a29205e7.PNG)

exported DateTime -> '2015-12-15 00:00:00.000'

### DBeaver Version

Community Edition Version 22.2.0.202209051344

### Operating System

Windows Server 2016 DataCenter

### Database and driver

Database : SQL Server
Driver : Microsoft JDBC Driver for SQL Server 9.2.0

### Steps to reproduce

1. I execute a query and get a result set
2. right click -> export
3. I select SQL target
4. I select YYYMMdd format for datetime columns
5. I get a file with SQL insert
6. the datetime format is 'YYY-MM-DD' so I cannot execute it back because SQL server wants 'YYYYMMDD' format https://stackoverflow.com/a/12957690/7256909

**Comment by uslss** [comment]
@samuelguesnier did you try to uncheck Native date/time format option?
![image](https://user-images.githubusercontent.com/31996417/192731366-2185b06c-2d0f-4e41-a228-5fecf1849605.png)

**Comment by samuelguesnier** [comment]
Thanks @uslss it's working by setting use native date to false,.
