### ISSUE TITLE
Apache Hive "Insert Table Alias" option is ignored

### ISSUE THREAD

**Issue by JesseFL** [dbeaver/dbeaver#17658]
### Description

When connected to Apache Hive, after typing `FROM `, the auto-complete list of tables is displayed.  Selecting any table by pressing `ENTER` populates the table name, but does NOT populate the table alias.

![image](https://user-images.githubusercontent.com/17784067/190402026-6bcf9fa2-640e-4bdf-b934-9733b779ffe4.png)

I realize my screenshot is blurred but please be assured I tested the same functionality against Oracle and it works as expected.  The same steps do not produce an alias in Hive.

### DBeaver Version

Community 22.2.0

### Operating System

Windows 10

### Database and driver

Apache Hive
Cloudera driver

### Steps to reproduce

1. Connect to Apache Hive
2. Type `select * from ` and select one of the offered auto-complete tables
3. Observe the table alias is NOT inserted.

**Comment by LonwoLonwo** [comment]
Thanks for the report @JesseFL
