### ISSUE TITLE
Broken link in DBeaver daily tip

### ISSUE THREAD

**Issue by DeflateAwning** [dbeaver/dbeaver#17666]
### Description

In the tip shown below, clicking the link doesn't do anything. 

Solution: fix the link, but also spell out where to go so users know (example: Window > Preferences > Editors > Data Editor > Appearance > Grid > Highlight rows with selected cells")

![image](https://user-images.githubusercontent.com/11021263/190544957-f60659b8-d419-43a7-9b81-4248ace57b3c.png)

### DBeaver Version

Community Edition 22.2.0.202209051344

### Operating System

Windows 10

### Database and driver

N/A

### Steps to reproduce

See description.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by jkmajcen** [comment]
This seems to be broken again as of 24.0.1.202403241413.

**Comment by E1izabeth** [comment]
Please create a new issue for that.
