### ISSUE TITLE
Native binaries using GraalVM

### ISSUE THREAD

**Issue by coder966** [dbeaver/dbeaver#17660]
**Is your feature request related to a problem? Please describe.**
Currently, DBEaver starts in few seconds and consumes hundreds of megabytes of memory. This could be greatly improved to sub-second startup time and well under 100MB of memory consumption.

**Describe the solution you'd like**
Compiling to native binaries using GraalVM.

I would like to hear your thoughts on this.

Thanks

**Comment by flambchap** [comment]
I find GraalVM's Native Image to be an exciting technology. However, it's not suited for DBeaver. Quote from [their documentation](https://www.graalvm.org/dev/reference-manual/native-image/basics/#static-analysis):

>Only reachable elements are included in the final image. Once a native image is built, no new elements can be added at run time, for example, through class loading. We refer to this constraint as the **closed-world assumption**.

One of DBeaver's defining features is the ability to load different JDBC drivers dynamically (https://github.com/dbeaver/dbeaver/wiki/Database-drivers#libraries). Moreover, in the case of the CE, all the drivers are downloaded from a remote host. It means that DBeaver violates the assumption and cannot use Native Image.
