### ISSUE TITLE
Can't leave client blank 

### ISSUE THREAD

**Issue by AGGGU** [dbeaver/dbeaver#17663]
### Description

Hey Everyone, im sorry to be a bother.

Whenever i try to create a new connection to an oracle DB the client field is automatically filled with "OraDB19Home1" and i don't get the option to leave it in it's default value. When trying to connect to an oracleDB i get socket error.  I have tried in pcs where oracle was never installed and the default client field is different and will let me connect allright. 

pic https://ibb.co/f9p2pV6 

Thanks a lot for your time!

### DBeaver Version

Latest

### Operating System

Windows 10

**Comment by iraidaa** [comment]
Hi @AGGGU,

Did you try to Edit the connection by choosing **Browse...** from the drop-down menu of the Client -> **Remove Home** -> **OK**?  

Could you also send us the log files? Please, check the instruction: https://github.com/dbeaver/dbeaver/wiki/Log-files. Not only the native client can cause such an error.

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
