### ISSUE TITLE
No operation timeout Executing the script has been waiting

### ISSUE THREAD

**Issue by bouyeijiang** [dbeaver/dbeaver#17678]
### Description

I need to disconnect and reconnect to work properly

### DBeaver Version

all version

### Operating System

linux mint 20(ubuntu)

### Database and driver

postgresql 12

**Comment by E1izabeth** [comment]
@bouyeijiang 
Please, describe what's the issue about in more details.
Provide the steps to reproduce your issue. A video with the reproduction could be useful.

**Comment by bouyeijiang** [comment]
If you do not operate the interface for a few minutes and then re execute the script, it will be displayed as being in the query all the time. You need to disconnect the slave connection to be normal.The same operation does not have this problem in the window system
![2022-09-22 21-48-23屏幕截图](https://user-images.githubusercontent.com/4083760/191764649-ebee9883-7904-4f11-8482-0b69e71326c8.png)

**Comment by Destrolaric** [comment]
@bouyeijiang Hi, can you see if https://github.com/dbeaver/dbeaver/issues/12559 is similar to your issue?

**Comment by bouyeijiang** [comment]
didn't solve the problem

**Comment by Destrolaric** [comment]
@bouyeijiang, hi could you provide me an information about query, via Query Manager https://github.com/dbeaver/dbeaver/wiki/Query-Manager

**Comment by AgostinhoBarbosa** [comment]
I'm having the same problem, if I leave any bank open for a certain time without doing anything, when it returns it crashes

**Comment by a-pavlov** [comment]
The same issue - seems after some time the connection to database is expired, but the application does not know about it. As workaround I click on "Cancel" button(important: do not switch tabs because it can hide the "Cancel" button), click to "Invalidate/Reconnect" in tool bar, wait for re-connection and execute the script again.

**Comment by E1izabeth** [comment]
Please, provide the queries which you see in [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) while encountering this issue.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.

**Comment by bouyeijiang** [comment]
谢谢您的来信！我会及时查阅的
