### ISSUE TITLE
To use DBeaver in Oracle compatibility mode in Db2

### ISSUE THREAD

**Issue by Tomoko0930** [dbeaver/dbeaver#17679]
### Description

I have Db2 set to Oracle compatibility mode. In this case, I need to set "set sqlcompat plsql" to the procedure in order to execute the Oracle PL/SQL in Db2. However, SQL editor in DBeaver does not seem to recognize "set.." syntax. How can I run "set sqlcompat plsql" in DBeaver without error?

### DBeaver Version

Community Edition 22.2.0.202209051344

### Operating System

Windows 10 Enterprise

### Database and driver

1. Database name and version : Db2 v11.5.7.0
2. Driver name and version : IBM Data Server Driver for JDBC and SQLJ 11.5.0.0

### Steps to reproduce

1. I try to connect to database Db2 v11.5.7. 
2. This database is set to Oracle compatibility mode.
>  $ db2set
> DB2_COMPATIBILITY_VECTOR=800
3. I executed the following PL/SQL procedure in DBeaver: To execute Oracle PL/SQL procedure in Db2, I need to set "set sqlcompat plsql;" in the procedure.
[test.txt](https://github.com/dbeaver/dbeaver/files/9596218/test.txt)
4. Then the following error is output. : An unexpected token "db2" was found following "set sqlcompat ".  Expected tokens may include:  "=".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.26.14
![DBeaver_set](https://user-images.githubusercontent.com/32427400/190952179-0af99d9d-19c0-49ae-bcdc-b798ef8dce62.png)
It seems that 'set sqlcompat plsql;' is not recognized by DBeaver.
This procedure can be executed without error via Db2 CLP, how can I execute it from DBeaver?

**Comment by Destrolaric** [comment]
Probably related to the old driver, we need to look if it will reproduce after https://github.com/dbeaver/dbeaver/issues/17427 will be completed.

**Comment by LonwoLonwo** [comment]
Hello @Tomoko0930 

I'm not sure that we can do anything here. 
https://www.ibm.com/docs/en/db2/11.1?topic=features-setting-up-db2-oracle-application-enablement
Looks like you can use this set command only in the Db2 command window

> You set and update the DB2_COMPATIBILITY_VECTOR registry variable by using the db2set command.
https://www.ibm.com/docs/en/db2/11.1?topic=features-db2-compatibility-vector-registry-variable

I see that DB2 has SET commands as SQL https://www.ibm.com/docs/en/db2-for-zos/12?topic=statements-set-schema and they working fine for me. But not the Oracle compatibility.

Can you execute set commands in your command window and then in DBeaver to use CREATE PROCEDURE?

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it.
