### ISSUE TITLE
Opening a connection takes a lot of time on `Read data types`

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#17675]
### Description

Related to #17117 - it happens in my case as well.
I have a DB with a dozen schemas and ~315 enums.
Whenever I open a connection to a remote DB the background task stays on `Read data types` for about 35 seconds before the connection is actually opened.
suggestions: 
1. do this as a background task AFTER the connection is made
2. lookup a data type when it's actually needed i.e describing or selecting from a table for the first time.

### DBeaver Version

Community 22.2.0

### Operating System

MacOS 12.6

### Database and driver

postgres 12.4, default JDBC drivers

### Steps to reproduce

create a remote (i.e cloud) database with many enums.
open a connection to it

### Additional context

it only happens when `Connect`ing to a DB - it doesn't happen when invalidating the connection

**Comment by LonwoLonwo** [comment]
Thanks for the report.

Probably we need to enhance enum reading for PostgreSQL

**Comment by mtaieb1** [comment]
I am facing the same issue when trying to connect to remote Postgres DB that hosts around 300 schemas and multiple enums. It takes about 5 minutes to open a connection.
Using Dbeaver v22.2.5 and jdbc driver v42.5.1

**Comment by andrewmslack** [comment]
I get same non-responsiveness whilst attempting to connect to a postgresql rds db hosted on AWS:
"connect to jdbc:postgresql://..... Read data types" and the connection just sits there, waiting .. 10mins so far and still not finished.  Im unable to connect to the db atm, renders the tool useless.  It eventually gave up with an EOFException.
```
SQL Error [08006]: An I/O error occurred while sending to the backend.
  An I/O error occurred while sending to the backend.
  An I/O error occurred while sending to the backend.
    EOFException
    java.io.EOFException
```

**Comment by pyrocks** [comment]
@LonwoLonwo @arhayka sorry for the bump - but are there any plans of addressing this soon? thanks 🙏

**Comment by E1izabeth** [comment]
You can vote for the issue by reacting with thumbs up emoji under the issue body.

**Comment by pyrocks** [comment]
But i am the OP :/

**Comment by pyrocks** [comment]
bump again.
This is really annoying when I need to solve something quickly in a production database and it takes me a minute just to connect to it :/

**Comment by pyrocks** [comment]
thanks for handling this - the experience is so much better now.
