### ISSUE TITLE
Invalid type int8 instead of Int8 when export from PostgreSQL and import to ClickHouse

### ISSUE THREAD

**Issue by was-av** [dbeaver/dbeaver#17674]
### Description

Can not transfer data from PostgreSQL to ClickHouse, because generated DDL for create new table has invalid type 'int8' instead of 'Int8'

### DBeaver Version

CE Version 22.2.0.202209051344

### Operating System

macOS Monterey 12.6

### Database and driver

Connection Drivers:
PostgreSQL standard driver
Yandex ClickHouse legacy driver (server version < 21.3)

### Steps to reproduce

1. In Postgres create table t1 with a column typed int8
2. Insert data to table t1 (insert into t1 values (1)) 
3. Export data by context menu from PostgreSQL to ClickHouse

**Comment by Destrolaric** [comment]
Thank you for the report!
