### ISSUE TITLE
Bug with alter table

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#17676]
### Description

Some strange behaviour while saving changes to a table

### DBeaver Version

22.2.0 CE

### Operating System

ubuntu 22

### Database and driver

Postgres 15 beta

### Steps to reproduce

1. Open existing table
2. Add column, press ok. Type - varchar, name - any, etc unchanged;
3. Column was added to a list, but yet not persisted;
4. Change "default" value to "adfadfasdfasdf";
5. Press "Ctrl+S" to save changes;
6. Press "Save" in dialog;
7. Got an error: "ОШИБКА: в выражении DEFAULT (по умолчанию) нельзя ссылаться на столбцы";
8. Press "Ok";
9. Correct the column - remove default, fill comment;
10. Press "Ctrl+S" - nothing happens;

The way when "Ctrl+S" restores - to switch to another window, to move then to another column in list.

**Comment by LonwoLonwo** [comment]
Hm. I can't reproduce your issue on Windows. Can you provide a video, please?

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
