### ISSUE TITLE
DuckDB  Date Types  add new row error

### ISSUE THREAD

**Issue by llf007** [dbeaver/dbeaver#17673]
### Description

1.Create test table 
```
CREATE TABLE main.test (c1 DATE);
insert INTO test values('2022-01-01');
```
2.I try  add new row
3.input 2022-01-02 
4.Save，See an 
Error synchronizing data with database

Reason:
Can not bind statement parameter
![image](https://user-images.githubusercontent.com/60683568/190852416-6a71b3c2-37a5-4dab-989e-726bc19e7007.png)

![image](https://user-images.githubusercontent.com/60683568/190852624-564d352d-82a7-45ae-afbc-8af194f35dca.png)

 

### DBeaver Version

DBeaver Ultimate 21.3.0  and DBeaver  Community 22.2.0  

### Operating System

Windows 11

### Database and driver

DuckDB v0.5.0
duckdb_jdbc-0.5.0.jar
DuckDBJ 1.0
![image](https://user-images.githubusercontent.com/60683568/190851553-a2adb1f9-51c0-4a86-9ebb-fba682eea8ee.png)

**Comment by Destrolaric** [comment]
Thank you for the bug report!

**Comment by llf007** [comment]
Thank you all, great job!

**Comment by Mause** [comment]
This is the DuckDB bug report for this issue: https://github.com/duckdb/duckdb/issues/6761

**Comment by LonwoLonwo** [comment]
Can not reproduce with the latest DBeaver (23.2.2) and DuckDB (0.9) versions

![2023-09-28 09_20_10-DBeaver Ultimate 23 2 1 - test](https://github.com/dbeaver/dbeaver/assets/45152336/0dd2bdb5-446b-4647-90ac-ba104a99eaf4)
