### ISSUE TITLE
Database changes doesn't save.

### ISSUE THREAD

**Issue by ShpxLbh** [dbeaver/dbeaver#17688]
### Description

edite tables via enter, save changes - then refresh - see changes (delete rows end adit records)
refresh couple of times connection and tables - edit made.
turn off dbeaver, turn on.
connect to sql database - no edits at all... frustrating! can't work . 

### DBeaver Version

22.2.0.202209080956

### Operating System

windows 10

### Database and driver

sql, drivers azure

**Comment by ShadelessFox** [comment]
Hello @ShpxLbh,

Perhaps your transaction mode is set to manual commit?

Please refer to https://github.com/dbeaver/dbeaver/wiki/Auto-and-Manual-Commit-Modes.

**Comment by ShpxLbh** [comment]
@ShadelessFox  nope, tried that option in many ways. Deleted connection from library of connections, connected via different driver (was azure, tried via mssql) and it works well.

**Comment by ShadelessFox** [comment]
I see.

I assume the issue is now resolved and, therefore, can be closed?

**Comment by ShpxLbh** [comment]
probably yes.  but no info why was that error.
