### ISSUE TITLE
Import data saves the last used target container 

### ISSUE THREAD

**Issue by iraidaa** [dbeaver/dbeaver#17692]
The target container is where the data is uploaded, schema or database. We can choose any.
But there may be an attempt to connect to the last used container. In this case, the connection to the database takes a long time, and the UI may freeze. Also, you can encounter an error **'an error occurred while logging in'**.

**Comment by arhayka** [comment]
We don’t want to automatically connect to the database in the first step of the Data Transfer wizard.

We need to add the following:
- button **Connect to the target database**  in the second step of the Data Transfer wizard
- gear button with a link to Data transfer Preferences  in the second step of the Data Transfer wizard
- checkbox **Auto reconnect** in Data Transfer Preferences
