### ISSUE TITLE
SQL compilation error for Snowflake Stored Procedures

### ISSUE THREAD

**Issue by djbeacom** [dbeaver/dbeaver#17699]
### Description

Getting the below error when trying to "View Procedure" or "Generate SQL DDL" for Snowflake Stored Procedures.  This worked flawlessly in previous versions prior to upgrading.

![image](https://user-images.githubusercontent.com/62651897/191509510-89946a68-5941-4a04-a6b6-bea75b1e9ef5.png)

The procedure definition is error-free.  I am able to view and execute using the Snowflake UI.

### DBeaver Version

Community 22.2.0

### Operating System

Windows 10 Enterprise

### Database and driver

![image](https://user-images.githubusercontent.com/62651897/191510540-58e1b6c1-6188-4c5d-8da0-9493796ba69a.png)

**Comment by LonwoLonwo** [comment]
Hello @djbeacom 

What name does your procedure schema have?

Probably driver updating will help you:

![2022-09-01 00_58_49-DBeaver 22 2 0 - MediaType](https://user-images.githubusercontent.com/45152336/187792925-291fe5b0-dbef-44ba-98a2-9f90103d8d97.png)

As here https://github.com/dbeaver/dbeaver/issues/17121

**Comment by djbeacom** [comment]
Thank you!  This resolved the issue.

**Comment by LonwoLonwo** [comment]
Thanks for your answer @djbeacom
