### ISSUE TITLE
Update Babel version

### ISSUE THREAD

**Issue by lastares** [dbeaver/dbeaver#17697]
### Description

<img width="249" alt="image" src="https://user-images.githubusercontent.com/25546446/191394273-a56a894d-e240-40aa-b46c-a7b5682c8cd9.png">

### DBeaver Version

22.2.0.202209051344

**Comment by LonwoLonwo** [comment]
Hello @lastares 

This is a translating issue from the Eclipse side: https://github.com/dbeaver/dbeaver/issues/17641

Probably, we need to find or create a ticket on the Eclipse bug tracker.

**Comment by iraidaa** [comment]
@LonwoLonwo  The ticket is ready: https://github.com/eclipse-platform/.github/issues/68.

**Comment by LonwoLonwo** [comment]
We probably need to update Eclipse Babel from our side first.

**Comment by E1izabeth** [comment]
We need to wait for the new babel build to have correct translation.

**Comment by E1izabeth** [comment]
The latest build [here ](https://www.eclipse.org/babel/downloads.php) contains correct translation.

**Comment by serge-rider** [comment]
Babel 2022-12 is still not released (link above contains only 2021-12 version).
However we can see it in update sites: https://download.eclipse.org/technology/babel/babel_language_packs/RC1/

The roblem is that we can't use update site, we need archived zip with all translations. I think we need to contct Babel team and ask to publich the release.

**Comment by E1izabeth** [comment]
Seems that the latest build 2022-12 is not stable https://www.eclipse.org/forums/index.php/t/1112224/.

**Comment by lastares** [comment]
OK

**Comment by bianyun** [comment]
I found a temporary solution to this problem. 

Taking the latest version 23.2.2 as an example, find following jar file:

> plugins/org.eclipse.e4.ui.workbench.renderers.swt.nls_0.16.0.v20230525-0648.jar 

, and use decompression software to extract the Chinese localization attribute file from it: 

> /org/eclipse/e4/ui/internal/workbench/renderers/swt/messages_zh.properties

, and then change the value corresponding to the key `menuCloseAll` to `\u5173\u95ed\u5168\u90e8(&A)`,

Then, replace the original file in the Jar package with the modified file.

<img width="743" alt="2023-10-10_145621" src="https://github.com/dbeaver/dbeaver/assets/4619776/2c5fe6db-208d-467a-be5e-60abec3b209c">

**Comment by SSSDNSY** [comment]
waiting for update...

**Comment by E1izabeth** [comment]
Still no update here https://eclipse.dev/babel/downloads.php

**Comment by serjiokov** [comment]
So, I used the latest language pack from official update site (pls see the screenshot), 

![image](https://github.com/dbeaver/dbeaver/assets/32031248/3afe8343-59b1-4a6b-b58b-0574eb2a79a5)

The unpacked **org.eclipse.e4.ui.workbench.renderers.swt.nl_zh_4.26.0.v20230220105658.jar**
```
Bundle-Name: org.eclipse.e4.ui.workbench.renderers.swt Chinese (Simplified) NLS Support
Bundle-SymbolicName: org.eclipse.e4.ui.workbench.renderers.swt.nl_zh ;singleton=true

```
already contains required fix
` menuCloseAll=\u5173\u95ed\u5168\u90e8(&A)`

![image](https://github.com/dbeaver/dbeaver/assets/32031248/6da3deed-23ff-4c3e-b921-11e0e1437260)

**Comment by serjiokov** [comment]
menuCloseAll=\u5173\u95ed\u5168\u90e8(&A)
