### ISSUE TITLE
Procedure not loading

### ISSUE THREAD

**Issue by andersonsimioni** [dbeaver/dbeaver#17693]
### Description

When I try to load a procedure to edit, it now show the code, it only show the empty text screen without the procedure code, it's a bug because when I try with workbench the procedure load normaly.

![image](https://user-images.githubusercontent.com/55260999/191288613-c2c8c747-37a1-4358-b079-17c9066e0d42.png)

### DBeaver Version

Community edition 22.2.0

### Operating System

Windows 10 professional 21H1 19043.2006

### Database and driver

 Database name Driver for MySQL 8 and later

### Steps to reproduce

1. Open some existing procedure that you know have code
2. Check if the code show

**Comment by LonwoLonwo** [comment]
Hello @andersonsimioni 

I can't reproduce your issue.

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
