### ISSUE TITLE
Set Application Name parameter in Db2

### ISSUE THREAD

**Issue by igor2x** [dbeaver/dbeaver#17698]
**Is your feature request related to a problem? Please describe.**
DBeaver does not sets APPLICATION_NAME parameter and it is so displayed "db2jcc_application" as it is displayed for all applications that do not set application name. In many tools it is difficult to distinguish which of database connection is DBeaver and which one is from other applications that also do not have set the name.

**Describe the solution you'd like**
Db2 database administrator frequently checks for applications that causes trouble on database with command:
`db2 list applications`
and DBeaver is in Application Name listed as "db2jcc_application", which is default name if no name is set. See "db2jcc_applica" bellow:

```
Auth Id  Application    Appl.      Application Id                    DB
         Name           Handle                                       Name
-------- -------------- ---------- --------------------------------- -------
U1033704 db2jcc_applica 2019       192.168.3.15.64789.220920100224   DBTEST
U3470252 DataGrip       2020       192.168.14.233.66823.22092013233  DBTEST

```
But as it can be seen DataGrip database tool properly sets the Application Name (last line).

If I dig it deeper into Db2 monitoring:
`SELECT APPLICATION_NAME, CLIENT_APPLNAME FROM TABLE(MON_GET_CONNECTION(NULL, -2)) WHERE CLIENT_APPLNAME IS NOT NULL ORDER BY CLIENT_APPLNAME`

It displays:
```
APPLICATION_NAME    CLIENT_APPLNAME
------------------- ---------------------
db2jcc_application  DBeaver 22.2.0 - Main
DataGrip            DataGrip 2022.2.4
```

As it seen DBeaver correctly sets CLIENT_APPLNAME info.

But "Application Name" is used in many tools as the only column displayed and there is no CLIENT_APPLNAME available. It is so impossible to see which of database connections are from DBeaver.

My suggestion is: In DBeaver set APPLICATION_NAME to "DBeaver" without program version, just like DataGrip does.
Data in CLIENT_APPLNAME is just fine and should not be changed.

Bellow is official IBM site how to set APPLICATION_NAME:
https://www.ibm.com/support/pages/name-db2-jdbc-application-appears-db2jccapplication-how-change-it

**Comment by LonwoLonwo** [comment]
Hello @igor2x 

Can you specify, please, what DB2 version you use?

**Comment by LonwoLonwo** [comment]
![2022-09-21 14_16_05-DBeaver 22 2 1 - _SAMPLEDB_ Script-17](https://user-images.githubusercontent.com/45152336/191490481-4394baa3-6bdb-438b-9b2e-c81f6fba74c6.png)

Also, please check this setting. It must be disabled.

For now, I can't reproduce your issue for DB2 Luw

![2022-09-21 14_17_04-DBeaver 22 2 1 - _SAMPLEDB_ Script-17](https://user-images.githubusercontent.com/45152336/191490701-a0cb814f-9525-4061-81c4-7d03d897721b.png)

**Comment by LonwoLonwo** [comment]
I'm not sure that we can do it...

Because we do it already here:
https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.db2/src/org/jkiss/dbeaver/ext/db2/model/DB2DataSource.java#L272

And in the documentation for the Connection class, I can see:

> 
>          * <li>ApplicationName  -       The name of the application currently utilizing
>          *                                                      the connection</li>

So it can be the strange behavior from the driver's class, I'm not sure.

**Comment by igor2x** [comment]
I am using the latest Db2 version v11.5.7.0 with the latest manually [added JDBC Driver 4.31.10](https://www.ibm.com/support/pages/db2-jdbc-driver-versions-and-downloads) and the latest available DBeaver CE 22.2.0.

It has to be some way to add Application Name, because _DataGrip_ does it successfully.

**Comment by igor2x** [comment]
I am not a programmer, but I searched the web and all documentation I have found point to `setClientProgramName`. Are you sure `setClientInfo` pointed from your Github link is the same property? Maybe `setClientInfo` is the column CLIENT_APPLNAME like I have described in my initial post, that is correctly set. But maybe beside that it should also `setClientProgramName` be set.

Sources:
1. [Is there a way to set APPL_NAME on the DB2 Connection externally instead of "db2jcc_application"](https://stackoverflow.com/questions/54722696/is-there-a-way-to-set-appl-name-on-the-db2-connection-externally-instead-of-db2)
2. [Common IBM Data Server Driver for JDBC and SQLJ properties for Db2 servers](https://www.ibm.com/docs/en/db2/11.5?topic=SSEPGG_11.5.0/com.ibm.db2.luw.apdv.java.doc/src/tpc/imjcc_r0052607.html)
3. [How can I get my client application name to show up on zos from java?](https://stackoverflow.com/questions/15575245/how-can-i-get-my-client-application-name-to-show-up-on-zos-from-java)
4. [The name of a DB2 JDBC application appears as "db2jcc_application". How to change it?](https://www.ibm.com/support/pages/name-db2-jdbc-application-appears-db2jccapplication-how-change-it)

**Comment by igor2x** [comment]
I have found another tool that properly sets APPLICATION_NAME. The name of tool is "SQL Workbench/J" and this tool is written in Java and source code is also available to download: https://www.sql-workbench.eu/dev-download.html
Tool uses "Apache License, Version 2.0" which is the same as DBeaver license, so no worries for braking some license checking into the code.

Bellow SQL:
`SELECT APPLICATION_NAME, CLIENT_APPLNAME FROM TABLE(MON_GET_CONNECTION(NULL, -2)) WHERE CLIENT_APPLNAME IS NOT NULL ORDER BY CLIENT_APPLNAME`

and last line is output of this new tool.
```
APPLICATION_NAME    CLIENT_APPLNAME
------------------- ---------------------
db2jcc_application  DBeaver 22.2.0 - Main
DataGrip            DataGrip 2022.2.4
SQL Workbench/J 122 WbWin-1
```

**Comment by igor2x** [comment]
I investigated this problem in deep. Solution is pretty simple, it is just a pure JDBC property setting.

1. Before starting check for application name.
` SELECT APPLICATION_NAME, CLIENT_APPLNAME FROM TABLE(MON_GET_CONNECTION(NULL, -2)) WHERE CLIENT_APPLNAME IS NOT NULL ORDER BY CLIENT_APPLNAME`

2. Output of above command is (first column is the setting I would like it to be changed):
```
APPLICATION_NAME	CLIENT_APPLNAME
db2jcc_application	DBeaver 22.3.1 - Main
```

3. Menu Database | Driver Manager | DB2 | DB2 LUW.
4. Edit button.
5. Driver properties.
6. Right click on empty space and "Add new property".
7. Type in **clientProgramName** as User property and "DBeaver" as Value.
8. Close down all dialogs by OK and Close buttons.
9. If connection to database is opened, disconnect and establish new connection.
10. Re-execute SQL from step 1.
11. Output is:
```
APPLICATION_NAME	CLIENT_APPLNAME
DBeaver                 DBeaver 22.3.1 - Main
```

and that is solution I am looking after.

It would be nice this JDBC setting to be set by default in DBeaver. This would help me a lot, so I don't need to change this setting manually in DBeaver on all of my coworker computers all over again when program is reinstalled on new computer.
Regards
