### ISSUE TITLE
Create Snowflake Procedure

### ISSUE THREAD

**Issue by jdechter** [dbeaver/dbeaver#17700]
### Description

This produces an error

CREATE OR REPLACE PROCEDURE testproc()
RETURNS varchar
LANGUAGE SQL AS 
$$
DECLARE 
	i int;
BEGIN 
	i:=1;
	IF (i=1) THEN
		i:=2;
	END IF;
	IF (i=2) THEN
		i:=3;
	END IF;	
END
$$;

SQL Error [1003] [42000]: SQL compilation error:
parse error line 14 at position 7 near '<EOF>'.
syntax error line 4 at position 1 unexpected '$'.
syntax error line 14 at position 7 unexpected '<EOF>'.

If i remove the second if/then block, it succeeds.
If i use Snowflake's web interface, it will succeed as is.

it looks as if DBeaver is not submitting the whole script; the red highlight lines stop before the last END

### DBeaver Version

Version 22.2.0.202209051344

### Operating System

Windows 10 64bit

### Database and driver

Snowflake jdbc Driver

### Steps to reproduce

1.

CREATE OR REPLACE PROCEDURE testproc()
RETURNS varchar
LANGUAGE SQL AS 
$$
DECLARE 
	i int;
BEGIN 
	i:=1;
	IF (i=1) THEN
		i:=2;
	END IF;
	IF (i=2) THEN
		i:=3;
	END IF;	
END
$$;

get error

2.   remove second if/then block  process succeeds

**Comment by LonwoLonwo** [comment]
Recently we had the very same discussion here: https://github.com/dbeaver/dbeaver/issues/17636
You can find some tips there.

For now, we do not have a test environment, so I can't reproduce your issue.

Can you please provide a screen of your issue?

**Comment by jdechter** [comment]
I read that discussion before.  Not exactly the same thing.
Seem DBeaver is parsing the text incorrectly.
image attached
<img width="305" alt="Screenshot 2022-09-22 111926" src="https://user-images.githubusercontent.com/67009541/191786852-4391407c-ad21-4f18-a90c-f54e7d8d4232.png">

**Comment by LonwoLonwo** [comment]
You can highlight and execute the procedure code body as a workaround.

![2022-09-27 14_58_20-DBeaver 22 2 1 - _SNOWFLAKE_SAMPLE_DATA 2_ Script-28](https://user-images.githubusercontent.com/45152336/192519612-9ece0797-d7b2-415a-a8ca-3cc0fc64b9a1.png)

**Comment by LonwoLonwo** [comment]
Also, you can change this setting in your connection settings. It helped me to execute the procedure.

![2022-09-27 15_01_42-Connection _SNOWFLAKE_SAMPLE_DATA 2_ configuration](https://user-images.githubusercontent.com/45152336/192520013-a6947e9c-d8c6-4f5f-833c-cae4c97ef0cf.png)

**Comment by jdechter** [comment]
Hi-lighting did not work.
changing $$ to string literal did work.

However I do not think that was the original intent.  I believe it is still a bug

thanks

**Comment by LonwoLonwo** [comment]
Ok, this is unclear - wy it is working fine for me, and not for you. Ok, maybe we can investigate it.

**Comment by jdechter** [comment]
It works without modifying the preferences with only 1 if/end if block.
Once you add a second block,  it does not work.

needing to change the preferences for $$, i do not think that is by design.
