### ISSUE TITLE
Setting up dbeaver.ini to start dbeaver from the command line has no effect

### ISSUE THREAD

**Issue by GG668** [dbeaver/dbeaver#17705]
### Description

I am following this operation
https://dbeaver.com/docs/wiki/Admin-Manage-Drivers/
I configured the ini file (-Ddbeaver.drivers.configuration-file=c:\some-path\dbeaver-drivers-config.xml) and xml file, and also downloaded the driver package
But I get a different result when I start dbeaver using the command line than when I start dbeaver directly
I start dbeaver directly, then open the database, and I am not prompted to download the driver
I start dbeaver using the command line and then open the database and I am prompted to download the driver

### DBeaver Version

Community Edition 22.2.0.202209051344

### Operating System

win2008

### Database and driver

clickhouse 0.32

### Steps to reproduce

1、start dbeaver directly （Desktop shortcuts）
2、Open clickhouse connection
3、No need to download drivers to connect

1、Start dbeaver via command line, e.g. 
D:\dbeaver\dbeaver.exe -con "driver=ClickHouse|name=SQLiteChin|host=1.2.3.4|port=8123|user=root|password=123456"
2、Prompt me to download the driver
![20220922173635706](https://user-images.githubusercontent.com/38756157/191713689-488e1720-b1cf-4b91-98f2-7f0bbd13e9ff.jpg)

### Additional context

Offline Environment

**Comment by GG668** [comment]
I seem to know why, I wrote ClickHouse in the driver name but it jumped to ClickHouse (Legacy), but why?

**Comment by E1izabeth** [comment]
@GG668
You can find driver id in the driver description using Driver Manager or through Connection configuration -> Edit Driver Settings.
![image](https://user-images.githubusercontent.com/28875055/191717780-eea8b531-5624-4d10-b550-97e1ed4c2a7b.png)

**Comment by GG668** [comment]
Thank you
