### ISSUE TITLE
BLOB export from Maria with new driver didn't show blob content

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#17703]
### Description

Maria driver has been updated from 2.7.0 to 3.0.7. And BLOBs during export to TXT format (but for example nothing changed in CSV export).
Now in TXT export we can't see BLOBs content, it replaced by string '[BLOB]'
Binaries export properties(Not depends on the encoding selected):
![image](https://user-images.githubusercontent.com/43252954/191665159-b39899dd-e071-4c3c-ace7-2f723ee2a8a3.png)

### DBeaver Version

22.2.1

### Operating System

win10

### Database and driver

Maria  3.0.7

**Comment by LonwoLonwo** [comment]
As s workaround - you can check these settings and increment the LOB cache:

![2022-09-22 15_18_24-DBeaver 22 2 1 - album](https://user-images.githubusercontent.com/45152336/191744937-7f719fcf-cc27-44d1-b7be-3d8b1b36f286.png)

**Comment by DariaMarkaryan** [comment]
So, there is so tiny cash for blobs by default. Change of the settings mentioned above helps export blob values

**Comment by LonwoLonwo** [comment]
Actual for Oracle too. Probably we should read the contents, as we do for CSV export.
