### ISSUE TITLE
Firebird driver missing

### ISSUE THREAD

**Issue by e1ace** [dbeaver/dbeaver#17709]
### Description

Opening a legacy database. The latest Firebird JDBC driver is not compatible with the database. Reverting to an older version database (Firebird 2.2.15) allows the database to be opened and the various table can be edited. Everything works as it should.

![Downloaded Driver](https://user-images.githubusercontent.com/20770537/191912648-d62498f8-1ef6-4ebb-b18e-a26859b7226e.png)

The issues is that when I relaunch DBeaver (after closing) - it says that drivers are missing. Despite it working before.

![Drivers Missing](https://user-images.githubusercontent.com/20770537/191913329-44661678-8b40-4482-8f5b-193d643b4353.png)

If I redownload the 2.2.15 I can get it to work. But in order to do that - I need to close the "Download driver files" dialog above, as you cannot simply select 2.2.15 from the dropdown as the Artifact Id for previous versions of firebird is different. The old Artifact Id is "jaybird-jdk18" and not "jaybird" as per the new versions.

### DBeaver Version

Community Edition 22.2.0.202209051344

### Operating System

Windows 10

### Database and driver

Firebird SQL JDBC 2.2.15

### Steps to reproduce

1. Add legacy firebird database. 
2. Force driver to old version (org.firebirdsql.jdbc:jaybird-jdk18:RELEASE [2.2.15]
3. Connect to database.
4. View Table [Optional]
5. Close Dbeaver
6. Open Dbeaver
7. Prompt for missing driver appears (Despite previous drivers being installed and working)

### Additional context

Force download/overwrite does not change any results.

**Comment by uslss** [comment]
thanks for the report. will be fixed in #17757

**Comment by e1ace** [comment]
@uslss Can this be reopened? Despite it being listed as fixed - I still have the same issue with V22.2.2 - with the exact same steps as above.

**Comment by e1ace** [comment]
I deleted the firebird driver out of the Driver Manager. And then manually added in a new custom driver and it works.

![image](https://user-images.githubusercontent.com/20770537/194870881-6532eefd-37d4-46a2-acc6-d033557a2b26.png)

**Comment by banDeveloper** [comment]
Same issue here, solved in the same way thanks to @e1ace. I'm using Windows 11.
