### ISSUE TITLE
Add support for Kinetica database

### ISSUE THREAD

**Issue by pdarringer-kinetica** [dbeaver/dbeaver#17716]
We (Kinetica) have a number of enterprise customers and developers who are using DBeaver to connect to their Kinetica databases.  It would be great if DBeaver could add standard support for Kinetica using our JDBC driver.

Here's our Maven info:
- GroupID:  com.kinetica
- ArtifactID:  kinetica-jdbc
- Repository:  https://nexus.kinetica.com/repository/releases
- Latest JAR:  kinetica-jdbc-7.1.7.3-jar-with-dependencies.jar

And here's the configuration for our JDBC driver:

```
<driver
	name="Kinetica"
	class="com.kinetica.jdbc.Driver"
	url="jdbc:kinetica://{host}:{port};CombinePrepareAndExecute=1"
	port="9191"
	webURL="http://www.kinetica.com/"
	defaultDatabase="kinetica"
	description="Kinetica DB, Inc."
>

<driver
	name="Kinetica SSL"
	class="com.kinetica.jdbc.Driver"
	url="jdbc:kinetica:URL={url};CombinePrepareAndExecute=1"
	webURL="http://www.kinetica.com/"
	defaultDatabase="kinetica"
	description="Kinetica DB, Inc."
>
```

I've also attached 16x16 and 64x64 versions of our logo:
![kinetica_logo_64x64](https://user-images.githubusercontent.com/59941530/192057762-4ff80c9d-38cc-43b6-9b59-68a63c4bbf88.png)
![kinetica_logo_16x16](https://user-images.githubusercontent.com/59941530/192057763-b15ca380-8626-4010-a312-645f001adb08.png)

**Comment by LonwoLonwo** [comment]
Thanks for the suggestion @pdarringer-kinetica

**Comment by tati-kru** [comment]
In most cases, we do not add commercial databases to DBeaver Community. However, we will be glad to discuss it as an option for DBeaver PRO. Please, contact us by email support@dbeaver.com
