### ISSUE TITLE
Bug when selecting an empty string on MySQL

### ISSUE THREAD

**Issue by artemiuss** [dbeaver/dbeaver#17719]
### Description

When selecting an empty string on MySQL

`SELECT ''`

1. The result is grayed out
![image](https://user-images.githubusercontent.com/15310217/192114658-540d5986-a9c8-46f3-bb20-14779d789321.png)
2. Subsequent execution of queries in this window is no longer possible. The tab becomes broken.

### DBeaver Version

Community 22.2.0

### Operating System

Windows 10

### Database and driver

1. 8.0.30 community,  same behaviour on 5.7.38 enterprise commercial
2. MySQL Connector/J mysql-connector-java-8.0.30 

### Steps to reproduce

1. Connect to DB
2. Execute the query SELECT ''

**Comment by ShadelessFox** [comment]
Hello @artemiuss,

Can you please send log files? You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by artemiuss** [comment]
Here it is 

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Sun Sep 25 02:18:53 EEST 2022
Event loop exception

![image](https://user-images.githubusercontent.com/15310217/192122025-7bdd2a82-380b-46be-ab91-18bf474a2a7e.png)
![image](https://user-images.githubusercontent.com/15310217/192122032-2811648b-a85a-4a40-961e-e6a3c84cb6c4.png)

**Comment by artemiuss** [comment]
[.log](https://github.com/dbeaver/dbeaver/files/9639736/default.log)

**Comment by ShadelessFox** [comment]
Okay, now I understand what's happening. Thanks for the bug report, this is clearly a really bad bug.

As a workaround, you can specify a non-empty alias.
