### ISSUE TITLE
Problems occurred while trying to save the state of the workbench

### ISSUE THREAD

**Issue by RayNeverLearns** [dbeaver/dbeaver#17713]
### Description

Every single time I close DBeaver (in every Windows version for the past couple of months, but I am now on 22.2.0), I get an error saying "Problems occurred while trying to save the state of the workbench" and when I click on Details, it says "Could not reset markers snapshot file". I have searched and not found this issue reported before. Any ideas?

### DBeaver Version

Community Edition 22.2.0.202209051344

### Operating System

Windows 10

**Comment by uslss** [comment]
@RayNeverLearns could you try to reset workspace?
https://github.com/dbeaver/dbeaver/wiki/Reset-workspace

**Comment by RayNeverLearns** [comment]
> @RayNeverLearns could you try to reset workspace? https://github.com/dbeaver/dbeaver/wiki/Reset-workspace
I just did that, twice and the problem is still there. I get it every single time I close DBeaver. :(

**Comment by RayNeverLearns** [comment]
I just did that, twice and the problem is still there. The error comes up every single time I close DBeaver. :(

**Comment by iraidaa** [comment]
Hi @RayNeverLearns,

Could you remove the .metadata folder from your workspace? The last step from this documentation: https://github.com/dbeaver/dbeaver/wiki/Reset-workspace.

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.

**Comment by dolmit-tanel-paaro** [comment]
I deleted my workspace's .metadata folder manually and that worked.
Resetting UI settings did not work.

Workspace location: `C:\Users\{{ userName}}\AppData\Roaming\DBeaverData\{{ workspaceName }}`
