### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by dan-schneider** [dbeaver/dbeaver#17718]
Hi,

I use DBeaver regularly in the German language. Some translations are not quite correct, others are still missing entirely. For this reason I followed this description to improve that: https://github.com/dbeaver/dbeaver/wiki/Localization

When I publish the branch I got this error "It looks like you don't have write access to dbeaver/dbeaber. If you should, please check with a repository administrator."

Can you please assign me the appropriate permission?

Thanks!

**Comment by E1izabeth** [comment]
We do not give write access to the repository. Seems that we need to edit this guide. Thank you.
Please, fork dbeaver repository and follow this instructions https://help.github.com/articles/creating-a-pull-request-from-a-fork/
