### ISSUE TITLE
Columns are read-only then schema and DB having the same name

### ISSUE THREAD

**Issue by williambuchanan2** [dbeaver/dbeaver#17724]
### Description

This problem seems to be related to the use of schemas.

Run a simple query on a table which is not in the dbo schema, then try to edit the data in the grid. The following error is shown:

Column is read-only: No corresponding table column

### DBeaver Version

Community Edition 22.2.1.202209251341

### Operating System

Windows 11

### Database and driver

SQL Server

### Steps to reproduce

Open query editor
Run a simple query on a table which is in a non-dbo schema. E.g.: select * from MySchema.MyTable.
In the result grid, click in a cell to edit the data.
Error shows.

![image](https://user-images.githubusercontent.com/32165641/192170998-ed423b91-a72a-4dc1-a917-434252cd4a3b.png)

**Comment by LonwoLonwo** [comment]
Hello @williambuchanan2 

For now, I can't reproduce your issue.

Do you use select for non-default database? Or for default? 

As a workaround - can you please check the result of selecting one more time (re-run) after you open the `syscore` tables list in the navigator tree?

**Comment by williambuchanan2** [comment]
> Hello @williambuchanan2
> 
> For now, I can't reproduce your issue.
> 
> Do you use select for non-default database? Or for default?
> 
> As a workaround - can you please check the result of selecting one more time (re-run) after you open the `syscore` tables list in the navigator tree?

Hi @LonwoLonwo

The DB wasn't default - I did try to make it default but no change. I have also tried re-running the query. In fact I have rebooted a few times, and refreshed the navigator tree several times as well but it doesn't make a difference.

See screenshot below - the inline editing works fine for a table in the dbo schema in the same database. I have tried a selection of tables in the SysCore schema and all have the same problem.

This is a new issue - I never had this problem before the latest update (or at least I never noticed it before).

Thanks

![image](https://user-images.githubusercontent.com/32165641/192392227-1ddfce4a-33cc-41b5-b45c-7d2dfa4df68d.png)

**Comment by LonwoLonwo** [comment]
Can you please check this option? In case of this action - a new editor with an appropriate connection will be open.
Will the result also be read-only?

![2022-09-28 10_16_45-334 825 971 - AnyDesk](https://user-images.githubusercontent.com/45152336/192758329-bd90dc45-66f5-444b-83f3-0907a5472e05.png)

**Comment by williambuchanan2** [comment]
Hi @LonwoLonwo 

Thanks for your message. In fact that worked! Looking into why it work has revealed the problem... It seems that when you include the database name in the query everything works ok, but without it we get the error. See below - the circled query works, but the second query without the DB name doesn't work.

I wonder if this is a side effect of my schema and DB having the same name? In fact this seems to cause some confusion with auto complete as well...

![image](https://user-images.githubusercontent.com/32165641/192899909-c2f23cb0-3088-4b1a-9a1d-278a47bd9d3f.png)

**Comment by LonwoLonwo** [comment]
> I wonder if this is a side effect of my schema and DB having the same name?

Yes, it can be the reason.

Thanks for the bug report.

**Comment by jyinpci** [comment]
I am getting this error with 22.3.3, on Windows 10 Pro with Oracle.  Now I rolled back to 22.3.2 and it worked with 22.3.2.

**Comment by Donal-Goggin** [comment]
I'm also getting this on 22.3.3. It's behaving very strangely

`select * from table1;` - Execute statement on this returns that table and it's editable like normal

```
#random line comment
/*random block comment*/
select * from table1;
```
Executing this query with the comments above it returns a read-only table with every column having the "No Corresponding table column" error. A yellow lock icon also appears in the top left

**Comment by LonwoLonwo** [comment]
Hello @Donal-Goggin 

Unfortunately, I can't reproduce your issue.
What database do you use?

![2023-01-30 12_19_23-DBeaver Ultimate 22 3 3 - _postgres12local_ Script-209  Script-209](https://user-images.githubusercontent.com/45152336/215436816-88ece1b9-54c1-40f0-a375-fdbdc4bb3b97.png)

**Comment by Donal-Goggin** [comment]
Your test is slightly different to mine. I use MariaDB MySQL so line comments are prefixed with '#'

This was just one way I was able to get that yellow lock icon to display( meaning every column will have that 'No corresponding table column' error). Even adding something like this to a query that usually returns an editable table, will return that table in read-only mode.

`AND column_1 NOT LIKE BINARY 'CLA %'`

**Comment by LonwoLonwo** [comment]
Ok, @Donal-Goggin, I can't reproduce on PostgreSQL, but I can on MySQL.

It is not the case for 17724, and I'm not sure, that this is the case for #18851

So, please, create a new ticket.

**Comment by nominalval** [comment]
Same issue, is a database problem on Dbeaver issue? I even restarted mysql database ... same error.

**Comment by bickgr** [comment]
Adding in my scenario as well, for me the difference seems to be selecting specific columns vs *. 

So for example, this query using select * produces an editable results set.
SELECT
	*
FROM
	"AspNetUsers" anu
ORDER BY
	anu."UserName"
;

But this same query only selecting a couple columns produces a results set with the Column in read-only problem
SELECT
	anu."Id" 
	,anu."UserName" 
	,anu."PhoneNumber" 
	,anu."DateCreated" 
FROM
	"AspNetUsers" anu 
ORDER BY
	anu."UserName"
;

 all columns selected show up as read-only.  They are all listed in the table's column list.  And the yellow lock icon shows up in the top left of the results window as well. 

I'm on DBeaver Version 22.3.4.202302060909, macOS 13.2, postgres DB

**Comment by LonwoLonwo** [comment]
Hello @bickgr 

Can you please provide the "AspNetUsers" DDL?

**Comment by bickgr** [comment]
hey @LonwoLonwo here it is

-- public."AspNetUsers" definition

-- Drop table

-- DROP TABLE public."AspNetUsers";

CREATE TABLE public."AspNetUsers" (
	"UserName" varchar(256) NULL,
	"NormalizedUserName" varchar(256) NULL,
	"Email" varchar(256) NULL,
	"NormalizedEmail" varchar(256) NULL,
	"EmailConfirmed" bool NOT NULL,
	"PasswordHash" varchar(512) NULL,
	"SecurityStamp" varchar(512) NULL,
	"ConcurrencyStamp" bpchar(36) NULL,
	"PhoneNumber" varchar(256) NULL,
	"PhoneNumberConfirmed" bool NOT NULL,
	"TwoFactorEnabled" bool NOT NULL,
	"LockoutEnd" timestamptz NULL,
	"LockoutEnabled" bool NOT NULL,
	"AccessFailedCount" int4 NOT NULL,
	"FirstName" varchar(100) NOT NULL,
	"LastName" varchar(100) NOT NULL,
	"DateCreated" timestamptz NOT NULL,
	"DateLastPlayed" timestamp NULL,
	"DbVersion" varchar(256) NULL,
	"AccessToken" varchar(256) NULL,
	"SelectedLanguage" varchar(256) NULL,
	"LastDeviceLanguage" varchar(256) NULL,
	"LastDeviceId" varchar(256) NULL,
	"LastIPAddress" varchar(256) NULL,
	"RunOnceCompleted" bool NOT NULL,
	"Status" int8 NOT NULL,
	"ProfileImage" varchar(256) NULL,
	"Id" uuid NOT NULL,
	"UserOrganizationId" uuid NULL,
	"Active" bool NOT NULL DEFAULT true,
	"LastPlayedSkillId" int4 NULL,
	"RequirePasswordChange" bool NOT NULL DEFAULT false,
	"PostId" varchar(256) NOT NULL DEFAULT ''::character varying,
	"ViolatedTerms" bool NOT NULL DEFAULT false,
	"MiddleName" varchar(100) NULL,
	"LockedOutOn" timestamp NULL,
	"ExternalIdentityUserId" text NULL,
	"PausePostSubmission" bool NOT NULL DEFAULT false,
	"RemovedFromSso" bool NOT NULL,
	"UserGroupId" uuid NULL,
	"ExternalUsername" text NULL,
	"NormalizedExternalUsername" varchar(100) NULL,
	"NumberOfViolationLockouts" int4 NOT NULL DEFAULT 0,
	"DateLastLoggedIn" timestamp NULL,
	"NormalizedExternalIdentityUserId" varchar(100) NULL,
	"AcceptedEulaTAndCIp" text NULL,
	"AcceptedEulaTAndCOn" timestamp NULL,
	"LastGeneratedClientSiteSession" text NULL,
	"LastGeneratedTrainingAppSession" text NULL,
	"AnalyticsType" text NULL,
	CONSTRAINT "AspNetUsers_pkey" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_AspNetUsers_Modules_LastPlayedSkillId" FOREIGN KEY ("LastPlayedSkillId") REFERENCES public."Modules"("Id") ON DELETE SET NULL,
	CONSTRAINT "FK_AspNetUsers_UserGroup_UserGroupId" FOREIGN KEY ("UserGroupId") REFERENCES public."UserGroup"("Id") ON DELETE SET NULL,
	CONSTRAINT "FK_AspNetUsers_UserOrganization_UserOrganizationId" FOREIGN KEY ("UserOrganizationId") REFERENCES public."UserOrganization"("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_AspNetUsers_LastPlayedSkillId" ON public."AspNetUsers" USING btree ("LastPlayedSkillId");
CREATE UNIQUE INDEX "IX_AspNetUsers_NormalizedEmail" ON public."AspNetUsers" USING btree ("NormalizedEmail");
CREATE INDEX "IX_AspNetUsers_NormalizedExternalIdentityUserId" ON public."AspNetUsers" USING btree ("NormalizedExternalIdentityUserId");
CREATE UNIQUE INDEX "IX_AspNetUsers_NormalizedExternalUsername" ON public."AspNetUsers" USING btree ("NormalizedExternalUsername");
CREATE INDEX "IX_AspNetUsers_UserGroupId" ON public."AspNetUsers" USING btree ("UserGroupId");
CREATE UNIQUE INDEX "IX_AspNetUsers_UserOrganizationId_NormalizedExternalIdentityUs~" ON public."AspNetUsers" USING btree ("UserOrganizationId", "NormalizedExternalIdentityUserId");
CREATE UNIQUE INDEX idx_45106_usernameindex ON public."AspNetUsers" USING btree ("NormalizedUserName");

**Comment by LonwoLonwo** [comment]
Ok, I can reproduce it

![2023-02-09 14_53_22-DBeaver 22 3 4 - _postgres 2_ Script-18](https://user-images.githubusercontent.com/45152336/217805770-d372d3a4-144a-4756-9a19-fb5a5694082a.png)

@bickgr please, create a new ticket for your issue. Because original issue here has other problem

**Comment by chris-hansen** [comment]
> I'm also getting this on 22.3.3. It's behaving very strangely
> 
> `select * from table1;` - Execute statement on this returns that table and it's editable like normal
> 
> ```
> #random line comment
> /*random block comment*/
> select * from table1;
> ```
> 
> Executing this query with the comments above it returns a read-only table with every column having the "No Corresponding table column" error. A yellow lock icon also appears in the top left

Same issue, if I have comments in my select statement, the columns will open read only.  If I remove the comments, I can then edit the columns.  I'm using MariaDB with DBeaver enterprise 23.3.0.202312110545

I don't have this issue with PostgreSQL or MySQL database, just MariaDB in DBeaver.

**Comment by xzl-5039** [comment]
I solved this problem,
![image](https://github.com/dbeaver/dbeaver/assets/62980888/471a7ec5-be0c-478a-a227-18778337562f)
