### ISSUE TITLE
Unreadable XML, JSON, ...

### ISSUE THREAD

**Issue by VXprof** [dbeaver/dbeaver#17729]
### Description

Don't know if this is a bug or not, but I can't see a content in a readable (expected) format.

Example:

![image](https://user-images.githubusercontent.com/114399611/192257415-1049263b-9317-4b0f-9d08-2839fbf6dd13.png)

I've tried all content encondings from the drop-down.

### DBeaver Version

Community 22.2.1.202209251341

### Operating System

WIN10

### Database and driver

1. DB2
2. DB2 LUW

**Comment by ShadelessFox** [comment]
Hello @VXprof,

Are you sure that the cell contents is indeed textual, non-binary data?

**Comment by VXprof** [comment]
Hi @ShadelessFox,

I found out that it is a ZIP file ...

Thank you for your time.
