### ISSUE TITLE
Autocompletion doubles table alias

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#17739]
### Description

![dbeaver_autocompletion](https://user-images.githubusercontent.com/12892581/192493344-afad2e6e-c4bd-49f3-a41a-fa2a3ccb695f.gif)
The alias of a table is doubled by autocompletion when the FROM clause already exists and when the column is already used in the SELECT list.

### DBeaver Version

Community Edition 22.2.1

### Operating System

Ubuntu 22.04

### Database and driver

PostgreSQL 14.5
PostgreSQL JDBC driver 42.3.4.jar

### Steps to reproduce

1. Write the FROM clause with a table and an alias
2. Write the SELECT list with the alias of the table and a column.
3. Write again the alias of the table as a new selected column : the preceding column is proposed by autocompletion. If we accept the autocompletion, the table alias is doubled.

**Comment by Destrolaric** [comment]
Hi, it looks like it is a side effect of using Hippie Engine. You can disable it in the `SQL Editor -> Code Completion -> Activate Hippie Engine for autocompletion`. Thank you for the bug report!

**Comment by ced75** [comment]
Hi,
Thanks for the quick fix! It seems better without Hippie Engine.
