### ISSUE TITLE
Cannot complete the install DBeaver IDE 22.2.1 on Eclipse 2021-12 (4.22.0)

### ISSUE THREAD

**Issue by cniweb** [dbeaver/dbeaver#17730]
### Description

Install / Update from DBeaver IDE 22.2.0 to DBeaver IDE 22.2.1 on Eclipse 2021-12 (4.22.0) fail with:
```
Cannot complete the install because of a conflicting dependency.
  Software being installed: DBeaver IDE 22.2.1.202209251341 (org.jkiss.dbeaver.ide.feature.feature.group 22.2.1.202209251341)
  Software currently installed: m2e-wtp - JPA configurator for WTP (Optional) 1.4.4.20201128-1705 (org.eclipse.m2e.wtp.jpa.feature.feature.group 1.4.4.20201128-1705)
  Only one of the following can be installed at once: 
    Quick Search 1.1.300.v20211203-1705 (org.eclipse.text.quicksearch 1.1.300.v20211203-1705)
    Quick Search 1.1.200.v20210616-1255 (org.eclipse.text.quicksearch 1.1.200.v20210616-1255)
  Cannot satisfy dependency:
    From: m2e-wtp - JPA configurator for WTP (Optional) 1.4.4.20201128-1705 (org.eclipse.m2e.wtp.jpa.feature.feature.group 1.4.4.20201128-1705)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group 3.6.0
  Cannot satisfy dependency:
    From: Eclipse Platform 4.22.0.v20211124-1800 (org.eclipse.platform.feature.group 4.22.0.v20211124-1800)
    To: org.eclipse.equinox.p2.iu; org.eclipse.text.quicksearch [1.1.200.v20210616-1255,1.1.200.v20210616-1255]
  Cannot satisfy dependency:
    From: DBeaver Local Standalone Application 22.2.1.202209251341 (org.jkiss.dbeaver.app.local.feature.feature.group 22.2.1.202209251341)
    To: org.eclipse.equinox.p2.iu; org.eclipse.text.quicksearch [1.1.300.v20211203-1705,1.1.300.v20211203-1705]
  Cannot satisfy dependency:
    From: DBeaver IDE 22.2.1.202209251341 (org.jkiss.dbeaver.ide.feature.feature.group 22.2.1.202209251341)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.app.local.feature.feature.group [22.2.1.202209251341,22.2.1.202209251341]
```

### DBeaver Version

22.2.1

### Operating System

Windows

**Comment by ccczhouxin** [comment]
Are thr new dbeaver not suit eclipse2021-12

**Comment by Matvey16** [comment]
@ccczhouxin Have you tried uninstalling DBeaver plugin completely and reinstalling the newest version?

**Comment by cniweb** [comment]
@Matvey16 Yes, I try it with a fresh installation and dbeaver version 22.2.1.

**Comment by cniweb** [comment]
> Are thr new dbeaver not suit eclipse2021-12

@ccczhouxin Which version is still compatible with Eclipse 2021-12?

**Comment by Matvey16** [comment]
@cniweb I reproduced this issue but it seems that eclipse proposes a solution to this error
Do you think there is something wrong with it?
![image](https://user-images.githubusercontent.com/82543000/199697523-d8f4772a-557a-4620-aa01-3085f4a1a0e5.png)

**Comment by cniweb** [comment]
@Matvey16 But the problem is that Eclipse wants to update to the Eclipse Java Package Version 4.25.0 when you update, so it is Eclipse 4.25.0 and no longer Eclipse 4.22.0.

**Comment by ShadelessFox** [comment]
Hello @cniweb,

Could you please try installing DBeaver on Eclipse 2022-12 to see if it works? Thanks.

**Comment by cniweb** [comment]
@ShadelessFox no, install DBeaver 23.3.3 works noot on Eclipse 2021-12:
`Cannot complete the install because of a conflicting dependency.
  Software being installed: DBeaver IDE 22.3.3.202301211053 (org.jkiss.dbeaver.ide.feature.feature.group 22.3.3.202301211053)
  Software currently installed: m2e-wtp - JPA configurator for WTP (Optional) 1.4.4.20201128-1705 (org.eclipse.m2e.wtp.jpa.feature.feature.group 1.4.4.20201128-1705)
  Only one of the following can be installed at once: 
    Quick Search 1.1.400.v20221023-0941 (org.eclipse.text.quicksearch 1.1.400.v20221023-0941)
    Quick Search 1.1.200.v20210616-1255 (org.eclipse.text.quicksearch 1.1.200.v20210616-1255)
  Cannot satisfy dependency:
    From: m2e-wtp - JPA configurator for WTP (Optional) 1.4.4.20201128-1705 (org.eclipse.m2e.wtp.jpa.feature.feature.group 1.4.4.20201128-1705)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group 3.6.0
  Cannot satisfy dependency:
    From: Eclipse Platform 4.22.0.v20211124-1800 (org.eclipse.platform.feature.group 4.22.0.v20211124-1800)
    To: org.eclipse.equinox.p2.iu; org.eclipse.text.quicksearch [1.1.200.v20210616-1255,1.1.200.v20210616-1255]
  Cannot satisfy dependency:
    From: DBeaver Local Standalone Application 22.3.3.202301211053 (org.jkiss.dbeaver.app.local.feature.feature.group 22.3.3.202301211053)
    To: org.eclipse.equinox.p2.iu; org.eclipse.text.quicksearch [1.1.400.v20221023-0941,1.1.400.v20221023-0941]
  Cannot satisfy dependency:
    From: DBeaver IDE 22.3.3.202301211053 (org.jkiss.dbeaver.ide.feature.feature.group 22.3.3.202301211053)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.app.local.feature.feature.group [22.3.3.202301211053,22.3.3.202301211053]`

**Comment by ShadelessFox** [comment]
I was talking about Eclipse 20**22**-12, not 20**21**-12.

**Comment by uslss** [comment]
There have been no updates for a long time.
If issue is still actual - feel free to reopen it.
