### ISSUE TITLE
Question about db access session count

### ISSUE THREAD

**Issue by skotlex** [dbeaver/dbeaver#17737]
### Description

I used dbeaver at work before. Meanwhile, at dawn, the number of Oracle sessions for certain individuals soared to 60 for unknown reasons. Since the company has a maximum of five db, it is strange for an individual to use nearly 60 sessions. And the number of sessions suddenly increased even though the person in question was not working at the time.

Unfortunately, this is all the information I know. Since then, the cause cannot be reproduced because the use of dbeaver has been banned. 

Is there any significant patch related to the number of connections since 21.0.5 version? I couldn't find it in the patch note, but I'm asking here just in case I didn't see it.

**+ At that time, I used the option below.**
1. Preferences > Connections > Metadata > Open separate connection for metadata read [checked]
2. Preferences > SQL Editor > Connections > Open separate connection for each editor [checked]

= I was using this option at the time, but I don't think this is the cause because the number of sessions increased when people weren't using the program.

### DBeaver Version

Community Edition 21.0.5

### Operating System

Windows 10

### Database and driver

ORACLE 11g

**Comment by LonwoLonwo** [comment]
Hello @skotlex 

So. We didn't have any significant changes about new database connections for Oracle last year. 
As you pointed out - DBeaver opens new connections for metadata reading and newly opened SQL Editors. Yes. 
And I think that disabling this setting can help to decrease the number of connections.

**Comment by skotlex** [comment]
Thank you for your answer. :)
