### ISSUE TITLE
No editor for [geometry]

### ISSUE THREAD

**Issue by TomaszWojtys-TomTom** [dbeaver/dbeaver#17746]
### Description

When I try to visualize geometry column the map preview is not available. The only message I have is "No editor for [geometry]"
![image](https://user-images.githubusercontent.com/24460812/192554152-682ffa69-14fc-4c82-bc09-d43c6f88ce74.png)

### DBeaver Version

Community Edition Version 22.2.1.202209251341

### Operating System

MS Windows 10

### Database and driver

PostgreSQL 11
PostgreSQL Driver 42.2.25
Postgis 2.5.0

**Comment by E1izabeth** [comment]
Please, try switching Client Web Engine in Preferences -> User Interface to Internet Explorer.
![image](https://user-images.githubusercontent.com/28875055/192618514-54cd1955-26c6-4471-a044-ae74999033cf.png)

**Comment by TomaszWojtys-TomTom** [comment]
Indeed, this change helped and map view is working.  
Thank you a lot! 

Issue can be closed.
