### ISSUE TITLE
French traduction error

### ISSUE THREAD

**Issue by jean152** [dbeaver/dbeaver#17744]
### Description

Hello,

I was working with Dbeaver (great tool by the way !) and I saw a traduction error in French. see screenshot below:

It shoud be "Lire les données dans **un** éditeur SQL"
and not "Lire les données dans _**une**_ éditeur SQL" because "éditeur" is "nom masculin".

![traduction_error_editeur](https://user-images.githubusercontent.com/33521187/192547675-c881cc5f-c6b0-46c3-bb59-8f7e2144dd1a.png)

Best regards.

### DBeaver Version

Community Edition 22.2.0

### Operating System

Windows 10

### Steps to reproduce

1) connect to a database
2) right click on a table

**Comment by E1izabeth** [comment]
Thank you for bug report.
