### ISSUE TITLE
MySQL DB object "not found in catalog" error when trying to navigate it using Ctrl+click

### ISSUE THREAD

**Issue by artemiuss** [dbeaver/dbeaver#17740]
### Description

When navigating the DB object(in my case, stored procedure) using the Ctrl+click shortcut, the "not found in catalog" error occurs.
Please note that this error occurs only when this action is performed the second and all subsequent times, while the first time, the error does not occur.

### DBeaver Version

DBeaver Community 22.2.1.202209251341

### Operating System

Windows 10
Windows Server 2019 10.0

### Database and driver

1. MySQL 8.0.30, MySQL 5.7.38 enterprise
2. MySQL Connector/J mysql-connector-java-8.0.30 

### Steps to reproduce

1. Connect to MySQL
2. Try to navigate to some procedure using the Ctrl+Click on its name on the SQL Editor window
2. Repeat the previous action
3. See an error:
![Untitled](https://user-images.githubusercontent.com/15310217/192497630-b586caf8-eb30-4e2f-aa0f-3212da7da5db.png)
![Untitled2](https://user-images.githubusercontent.com/15310217/192497631-99c79f6d-fc2e-406f-85e4-e000e64debfa.png)
![Untitled3](https://user-images.githubusercontent.com/15310217/192497634-05072763-2645-4a4f-8484-d637d3d99c92.png)

### Additional context

[.log](https://github.com/dbeaver/dbeaver/files/9654385/default.log)

**Comment by artemiuss** [comment]
It is a very annoying bug. I would appreciate a fix. I can provide more details if needed.

**Comment by uslss** [comment]
thanks for the report

**Comment by E1izabeth** [comment]
@artemiuss could you check if the issue is still actual for the latest DBeaver version?

**Comment by E1izabeth** [comment]
The issue is actual for DBeaver 22.2.5, it was reproduced.

**Comment by LonwoLonwo** [comment]
![2022-11-21 12_52_37-DBeaver 22 2 5 - _localhost 2_ Script-31](https://user-images.githubusercontent.com/45152336/203020480-317a197b-ffd9-45fb-841e-f451dab019b2.png)

Steps:
1. Open the non-default catalog with procedures in the Navigator.
2. Use "Execute Stored procedure" on any procedure. SQL Editor will appear with the call statement.
3. Use Ctrl+Click on the procedure name in the SQL Editor.
