### ISSUE TITLE
SSH Auth Fail after 22.2.1 update

### ISSUE THREAD

**Issue by brother-z** [dbeaver/dbeaver#17748]
### Description

Updating to 22.2.1 breaks SSH+Jump server with public key connection. Downgrading to 22.2.0 makes it work again.
Error says "Auth fail", log attached.
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/9658583/dbeaver.log)

### DBeaver Version

Community Edition 22.2.1

### Operating System

Windows 10

### Steps to reproduce

1. Configure SSH connection through a jump server with pulic key auth on both
2. Test tunnel, or just connect to database
3. Auth fail

**Comment by E1izabeth** [comment]
Does switching Implementation to SSHJ in Connection Configuration ->SSH -> Advanced Settings help?
![image](https://user-images.githubusercontent.com/28875055/192617950-e35e109b-6c72-4ecd-9160-d760df9f2c8e.png)

**Comment by brother-z** [comment]
I did switch, but then the "jump server" section is missing, so I assumed it can't do the me->bastion->db_srv and didn't dig any further, just downgraded to previous version.

**Comment by E1izabeth** [comment]
Just to make it clear, do you use encrypted key? I mean did you fill passphrase field?

**Comment by brother-z** [comment]
Yes, my keys are encrypted and I don't store passwords in DBeaver, only usernames are in settings.
So my normal "connect to database" workflow is:
1. enter db password
2. enter cert password A
3. enter cert password A again (I use same cert for both remote machines)
4. acknowledge the server fingerprint, because for some reason the bastion host fingerprint gets stored and the DB host never does, but that would be another bug report ;)

After upgrading to 22.22.1 I get to point 2, I enter cert password and end up with auth fail.

**Comment by E1izabeth** [comment]
Thank you for bug report.
