### ISSUE TITLE
 Dbeaver is not showing column default value - SQLSERVER

### ISSUE THREAD

**Issue by geanmatheus** [dbeaver/dbeaver#17759]
### Description

Looking in PowerDesigner, I noticed that a table has columns with default values.
ex:

CREATE TABLE client(
client_id CHAR(8) NOT NULL,
is_active bit  NOT NULL default 1
)

But when I tried to get the script to create this table in Dbeaver, the default value does not appear, causing divergence when I tried to recreate the table:

ex.:

CREATE TABLE client(
client_id CHAR(8) NOT NULL,
is_active bit  NOT NULL
)

### DBeaver Version

Community 22.1.3.202207240747

### Operating System

Windows 10 Enterprise

### Database and driver

MS SQL Server / SQL Server
Microsoft JDBC Driver for SQL Server (MSSQL)

**Comment by uslss** [comment]
@geanmatheus unfortunately, cannot reproduce it against 22.2.1. Could you please check if issue is actual for you against the recent version?

**Comment by geanmatheus** [comment]
still the same
![dbeaver](https://user-images.githubusercontent.com/18244115/192867322-0597f9d2-147b-4196-a1f4-018ed71b00af.png)

**Comment by geanmatheus** [comment]
still the same
![dbeaver](https://user-images.githubusercontent.com/18244115/192867632-11568381-7582-4f76-9910-d958ad26f8af.png)

**Comment by LonwoLonwo** [comment]
Also can't reproduce.

What database version and driver version do you use?

![2022-09-28 22_48_26-334 825 971 - AnyDesk](https://user-images.githubusercontent.com/45152336/192875310-4773ae87-81d0-4dab-a7aa-fc495d474c82.png)

**Comment by geanmatheus** [comment]
Microsoft SQL Server 2016 (SP3-CU1-GDR) (KB5015371) - 13.0.7016.1 (X64) 

MSSQL JDBC 9.2.0 JRE8

**Comment by geanmatheus** [comment]
![image](https://user-images.githubusercontent.com/18244115/193022257-adb8d3cf-6341-4c21-8a0a-a7e1cf05be2b.png)
When viewing information from a table that already existed in the database, this default information does not appear. But creating this example table that I spoke, appears normally.
Is it some specific configuration of this table that already existed?

**Comment by ShadelessFox** [comment]
Hello @geanmatheus,

Can you please confirm that the default value is shown in SSMS?

**Comment by geanmatheus** [comment]
No, it's not. The error message below appears. In DEV environment, I can see the script, but when generating the table script, the default value is not displayed either. Very strange

PRD Enviromet Error:
![image](https://user-images.githubusercontent.com/18244115/193277052-68a7ff79-dd65-40f9-b94e-a06a0118d3f9.png)

DEV Enviroment table script:

![image](https://user-images.githubusercontent.com/18244115/193277410-3062028e-1287-4fa9-a11a-3332973cc1cb.png)

**Comment by LonwoLonwo** [comment]
Ok. the [Internet says](https://www.sqlservercentral.com/forums/topic/property-text-is-not-available-for-defaultconstraint-1) that it can be a definitions access issue.

Can you please check this version? And add access to your database?

`GRANT VIEW DEFINITION ON OBJECT :: <table> TO <user>;`

**Comment by geanmatheus** [comment]
It Worked, Thanks!

![image](https://user-images.githubusercontent.com/18244115/193563172-5d73948f-907b-4a53-b095-2efccad3311d.png)

**Comment by LonwoLonwo** [comment]
Thanks for the answer @geanmatheus
