### ISSUE TITLE
Promts to download (and override) driver everytime I reboot DBeaver

### ISSUE THREAD

**Issue by perereman** [dbeaver/dbeaver#17755]
### Description

I am using Ubuntu 22.04 and DBeaver 22.2.1 CE to connect to an Informix BD.

I need an specific Informix JDBC driver since bundled does not work propperly with the Informix DBM version we have.

Just as soon I installed DBeaver I configured the driver from de Driver Manager and it worked fine. I deleted the bundled driver and added then new one.

However, everytime I close DBever and then I lunch it again, when I try to open the conection with Informix, suddenly a "download driver pop up" promts me.

Could you helpme?

### DBeaver Version

Community Edition 22.2.1

### Operating System

Ubuntu 22.04

### Database and driver

Informix (but I don't know the version)
Informix Driver for Informix 4.50.1

### Steps to reproduce

1.- Configure Informix driver with driver manager and works fine
2.- Close DBever
3.- Open DBeaver again and seems to forget previous configuration

**Comment by uslss** [comment]
thanks for the report. will be fixed in #17757
