### ISSUE TITLE
Sqlserver use CAST function type conversion failure

### ISSUE THREAD

**Issue by loong-coder** [dbeaver/dbeaver#17750]
### Description

I was expecting a date value, but actually got a datetime value
<img width="527" alt="image" src="https://user-images.githubusercontent.com/101961800/192670456-f925898a-d5f1-4ba3-9ab4-ade56a095350.png">

### DBeaver Version

Community Edition Version 22.2.0.202209040629

### Operating System

macOS Monterey Version 12.6

### Database and driver

1. Microsoft SQL Server 2019 
2. Microsoft JDBC Driver 9.2 for SQL Server 9.2.0.0

**Comment by LonwoLonwo** [comment]
Hello @hookv 

Yes, I can reproduce it.

![2022-09-28 13_24_26-334 825 971 - AnyDesk](https://user-images.githubusercontent.com/45152336/192756019-5eae70f2-2dd4-4d06-a02c-d32c61c3c73a.png)

As a workaround you can use other name for your casted column (not original name).

![2022-09-28 13_24_05-334 825 971 - AnyDesk](https://user-images.githubusercontent.com/45152336/192755973-3be1bf51-ddf6-4c85-94c4-de790611c1ce.png)

**Comment by E1izabeth** [comment]
Can't reproduce on the DBeaver 22.3.3
@hookv is the issue still actual for you?

**Comment by E1izabeth** [comment]
If you meet this issue again, please let me know.
I'm closing this issue as it was solved.

**Comment by loong-coder** [comment]
> 

Thanks, this issue has been fixed.
