### ISSUE TITLE
Schema Privileges Save button not enabling on update

### ISSUE THREAD

**Issue by DKhalil** [dbeaver/dbeaver#17754]
### Description

After selecting a new privilege the save/revert/refresh buttons stay disabled.

![image](https://user-images.githubusercontent.com/497250/192737957-693ccc70-8645-4cc5-90be-4c9c9984c764.png)

### DBeaver Version

CE 22.2.0

### Operating System

Windows 10

### Database and driver

MariaDB

**Comment by LonwoLonwo** [comment]
Hello @DKhalil 

Did you change your focus in this dialog?

![hzMkYyHNUG](https://user-images.githubusercontent.com/45152336/192755377-d9cbce6e-5bfc-4e23-bf55-19d2da0a6ebb.gif)

**Comment by DKhalil** [comment]
Ah, okay, I just assumed it was broken because that seems really unintuitive to me. Maybe not a bug but a UX complaint then ;)

**Comment by LonwoLonwo** [comment]
Yeah, it is UIX problem. Ok, maybe we can do something here.
