### ISSUE TITLE
DBeaver snap download inconsistencies in download versions on snap web site

### ISSUE THREAD

**Issue by igor2x** [dbeaver/dbeaver#17768]
### Description

On DBeaver web site: https://dbeaver.io/download/ there is info DBeaver on Linux can also be installed using snap, but there are some inconsistencies.

### DBeaver Version

Not applicable

### Operating System

Not applicable

### Database and driver

Not applicable

### Steps to reproduce

1. Go to DBeaver snap web page: https://snapcraft.io/dbeaver-ce
2. At the top click on drop-down menu and select amd64.
![image](https://user-images.githubusercontent.com/10895030/192832058-30150284-8e20-4180-9980-1f8e28db4b61.png)
There are three versions displayed. Each one in its separate channel.
First line is channel **latest/stable** and it fine.
Second and third lines are channels **latest/candidate** and **latest/edge** and versions in this two channels doesn't make sense.
Candidate channel is like beta release that is going to be next stable. Edge channel is latest development like nightly releases or similar.

SUGGESTION.
It looks to me that DBeaver is only available for latest stable releases, so only **latest/stable** channel makes sense. I suggest to remove DBeaver from **latest/candidate** and **latest/edge** channels.

The second problem. Selecting DBeaver for i386 platform and there is VERSION field with the data **latest**.
![image](https://user-images.githubusercontent.com/10895030/192833316-ed62c12f-3cb7-4bfc-b147-3ecf39fe1593.png)
Label **latest** doesn't make sense, because from date released 21 January 2020, it can't be DBeaver latest version. Please change the **latest** label to the real version it is available for i386 platform.

**Comment by ShadelessFox** [comment]
Hello @igor2x,

Thanks for the report.

We've cleared outdates channels, now there is only the `latest/stable` one.
