### ISSUE TITLE
Oracle database connection error:

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/dbeaver#17764]
### Description

In short, I have problems making a connection to an oracle database when the application is executed from eclipse java and at that moment I perform the connection tests, which makes connections difficult by cloudbeaver since I get the same error, which more rare is when I perform tests with the dbeaver and cloudbeaver applications downloaded from the official site if I can successfully connect to an oracle database

I have problems with the latest version I was reviewing previous projects of dbeaver that I had for example with version 21.0.1 it still does not connect with oracle, I just missed the error since before I only worked with mysql, postgresql and other databases

the error is detailed in the following issue please verify
https://github.com/dbeaver/cloudbeaver/issues/1181

### DBeaver Version

 last version

### Operating System

windows 10 pro and ubuntu server 20.04 

### Database and driver

I use the oracle 11g database, I use the default drivers that dbeaver automatically downloads and installs

### Steps to reproduce

1.  follow the following guide to implement dbeaver in eclipse java https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse
2.  run dbeaver from eclipse java
3. try to connect to a version 11g database
4. you will get the following error

![image](https://user-images.githubusercontent.com/52106718/192810761-2d7de537-3e63-4960-8ce5-21aabadd5aff.png)

by transitivity the same error is had in cloudbeaver running from eclipse as can be seen in the following image

![image](https://user-images.githubusercontent.com/52106718/192811300-dfd39871-85e8-49b7-9190-63c537d4e894.png)

details are mentioned in the following link

https://github.com/dbeaver/cloudbeaver/issues/1181

### Additional context

I don't use proxies my network is free

**Comment by ShadelessFox** [comment]
Hello @miltonchirinos44,

Is the issue only appears when running DBeaver in a development environment?

**Comment by miltonchirinos44** [comment]
Hi @ShadelessFox
If the problem appears when it is in a development environment in eclipse java, but when I run the `mvn package` and generate the compiled files with the new modifications, the error still appears
Binary or binary files that are in `product/community/target/products`

It only happens to me with the oracle database since with the postgres database there is no problem since the connection can be made normally either in a development or production environment

**Comment by ShadelessFox** [comment]
I don't really have any guesses what is going on.

Perhaps the driver is different from one used in DBeaver downloaded from https://dbeaver.io/files?

**Comment by miltonchirinos44** [comment]
Hello @ShadelessFox  tell him that when I connect to the oracle and postgresql database through the official application it does not let me connect to the oracle and postgresql database, to solve this error I had to download other drivers that help me connect, with which I was successful . 
but only in the applications that are on the official page, since when I perform the tests from eclipse java, it does not let me make connections to the oracle database but I can connect to the postgres database from java eclipse.

Can you please verify again since it indicated the cloudbeaver group dbeaver error since they verified it

https://github.com/dbeaver/cloudbeaver/issues/1181

**Comment by miltonchirinos44** [comment]
To date I have no solution to the oracle database connection error

**Comment by flambchap** [comment]
@miltonchirinos44 Hi. Can you please click the 'Test connection' button in  DBeaver (from the dev environment) and paste the results here? Thank you.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
