### ISSUE TITLE
Databricks driver - setup steps not reproducible

### ISSUE THREAD

**Issue by trymzet** [dbeaver/dbeaver#17776]
### Description

1. I'm not able to provide the JDBC URL - the box is there but when I try to type anything in, nothing happens (workaround: edit the driver and hardcode your JDBC URL as the template URL)
3. Guides specify that I should paste my token into the "personal-access-token" field. This field doesn't exist; I only see "username" and "password" fields (workaround: specify `token` as the username and provide the token in the password field)
4. When trying to use the official "Azure Databricks" driver, when I try to connect, I get a popup named "Download driver files", which asks me to download the Simba JDBC driver. However, this fails with the following error: `No target file for 'https://databricks-bi-artifacts.s3.us-east-2.amazonaws.com/simbaspark-drivers/jdbc/2.6.22/SimbaSparkJDBC42-2.6.22.1040.zip'`

### DBeaver Version

22.2.1

### Operating System

Windows 11

### Database and driver

Built-in "Azure Databricks" driver and the official Databricks JDBC driver.

### Steps to reproduce

Follow the official guide from [MS docs](https://learn.microsoft.com/en-us/azure/databricks/dev-tools/dbeaver)/[Databricks docs](https://docs.databricks.com/dev-tools/dbeaver.html#step-2-configure-the-databricks-jdbc-driver-for-dbeaver) or try to use the official DBeaver "Azure Databricks" driver.

### Additional context

The following setup worked for me to connect to Databricks (it's a modified guide from [MS docs](https://learn.microsoft.com/en-us/azure/databricks/dev-tools/dbeaver)/[Databricks docs](https://docs.databricks.com/dev-tools/dbeaver.html#step-2-configure-the-databricks-jdbc-driver-for-dbeaver)):

0. Download Databricks JDBC driver: [LINK](https://databricks-bi-artifacts.s3.us-east-2.amazonaws.com/simbaspark-drivers/jdbc/2.6.29/DatabricksJDBC42-2.6.29.1051.zip) and extract the archive
1. Start DBeaver.
2. If you are prompted to create a new database, click No.
3. If you are prompted to connect to or select a database, click Cancel.
4. Click Database > Driver Manager.
5. n the Driver Manager dialog box, click New.
6. In the Create new driver dialog box, click the Libraries tab.
7. Click Add File.
8. Browse to the `DatabricksJDBC42.jar` file that you extracted earlier and click Open.
9. On the Settings tab, for Driver Name, enter Databricks.
10. On the Settings tab, for Class Name, enter `com.databricks.client.jdbc.Driver`.
11. Click OK.
12. In the Driver Manager dialog box, click Close.
13. Reopen Driver Manager
14. In the Create new driver dialog box, click the Libraries tab.
15. Click Find Class.
16. In the Driver class list, confirm that `com.databricks.client.jdbc.Driver` is selected.
17. Click OK
18. In the Driver Manager dialog box, click Close.

**Comment by LonwoLonwo** [comment]
Hello @Trymzet 

Can you try to choose Azure Databricks from the connections list?

![2022-09-30 14_15_11-Connect to a database](https://user-images.githubusercontent.com/45152336/193258296-0dfcdbdb-5937-4078-ba93-0f2f958021b9.png)

Also if you will have any problems with the driver loading - you can add path to the driver manually in the Connection Settings

![2022-09-30 14_16_24-DBeaver 22 2 1 - customer](https://user-images.githubusercontent.com/45152336/193258510-73b805a7-2985-472c-afdc-5b28a644c405.png)

**Comment by trymzet** [comment]
Yes I tried using this one and it doesn't work, I described the error above.

Yeah I think that workaround can probably work.

**Comment by LonwoLonwo** [comment]
Ok. Driver downloading problems fixed here: https://github.com/dbeaver/dbeaver/issues/17757

Azure URL ticket here: https://github.com/dbeaver/dbeaver/issues/17785

All fixes will be available in the 22.2.2 DBeaver version.

**Comment by LonwoLonwo** [comment]
Hello @Trymzet 

Can you please check our last release? https://dbeaver.io/

**Comment by djagoda881** [comment]
Hello @LonwoLonwo 

I have version 22.2.3.202210231354 of DBeaver installed. I tried to connect to Azure Databricks selected from the list of available connections. However, it receives the message "Invalid JDBC URL" when trying to connect to the database. I can only connect to the database as @Trymzet  pointed out above. That is, by creating a new driver manager. I use the same URL in both cases. 
This is what the URL I am using <HOST> is replaced.
jdbc:databricks://<HOST>:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/endpoints/815a4690a72c5b8a;

**Comment by LonwoLonwo** [comment]
Hm.
Can you please try to change the beginning of your URL to "jdbc:spark://"? @djagoda881

**Comment by djagoda881** [comment]
After the change, everything works properly. 
Thanks for your help

**Comment by E1izabeth** [comment]
@Trymzet does it work for you?
