### ISSUE TITLE
SQL Editor - Alt+Up stops moving to previous SQL Statement if encounters a blank line between Comment and SQL Statement

### ISSUE THREAD

**Issue by HerbertR** [dbeaver/dbeaver#17774]
### Description

In the SQL Editor, when using Alt+Up to move thru the previous SQL statements, Alt+Up stops working if it encounters a blank line between a Comment and a SQL statement. Alt+Down works fine and continues down thru the gap to the next SQL statement.

![DBeaver_Example_Of_Blank_Line](https://user-images.githubusercontent.com/29405190/193047841-1ceef62c-7d38-45f9-866d-6b3bae069c67.jpg)

### DBeaver Version

Community 22.2.1.202209251341

### Operating System

Windows 10

### Database and driver

Does not appear to be driver specific

### Steps to reproduce

See attached image.
In SQL Editor, create several SQL statements and Comments. 
Separate the Comment Line and the SQL Statement with a single blank line
Beginning at the bottom SQL statement, use Alt+Up to move thru the previous SQL statements
Alt+Up stops at the blank line and will not continue to the next previous SQL statement
Alt+Down works fine and continues to the next SQL statement

**Comment by LonwoLonwo** [comment]
Hello @HerbertR 

For now I can't reproduce your issue.

![rZvG825qwP](https://user-images.githubusercontent.com/45152336/194290467-f6e0ed10-5c93-4e7c-9d38-cff50c0a7bef.gif)

Maybe you can generate some script example for testing? Content can be matter.

**Comment by HerbertR** [comment]
I just updated to DBeaver Community 22.2.2.202210092258 and still having this issue. I tried typing in part of your code and the SQL Editor continues to stop moving to previous SQL Statement at the blank like between the comment and the SQL statement. I also noticed that if cursor is at the very bottom of the SQL Editor session and there are a couple of blank lines, Alt+Up won't move the cursor up. 

Please see the attached image (if on red arrows line, Alt+Up doesn't move cursor, but green arrow line works).

I've attached the script that Alt+Up isn't working.


![DBeaver_Example_2](https://user-images.githubusercontent.com/29405190/195114642-a5f8cb0d-d17d-40ae-bfaa-1069cec80f2d.jpg)

[Script-1.txt](https://github.com/dbeaver/dbeaver/files/9756715/Script-1.txt)

**Comment by LonwoLonwo** [comment]
And what database did you use for this screen? I need to know the dialect.

**Comment by HerbertR** [comment]
I'm using the included drivers. The attached script is for IBM DB2 iSeries, and I have the same issue with SQL Server.

**Comment by LonwoLonwo** [comment]
And now, with the DB2i database help, I can reproduce your issue. Thanks.

(As I fought, Alt+Up works fine when the string with comment has folding) 

![2022-10-12 12_43_30-DBeaver Ultimate 22 2 2 - _PUB400 COM 1 1_Script-183](https://user-images.githubusercontent.com/45152336/195309688-74acf383-dc77-4904-9b6b-e0e9cde198fa.png)

**Comment by E1izabeth** [comment]
We need to adjust parsing to handle space between comment and statement. Cases with multiline comments and comments inside comments should be handled also.

**Comment by GuenterSch** [comment]
Info: It dose not work in both directions, if the cursor is in a blank line (or line with only spaces) and the next/previous line is also a blank line.
