### ISSUE TITLE
Broken Feature in Snowflake "Open separate connection for each editor"

### ISSUE THREAD

**Issue by macromatt** [dbeaver/dbeaver#17770]
### Description

The feature in Editors | SQL Editors | "Open separate connection for each editor" no longer works. When using "USE DATABASE" command all tabs change to that database rather than retaining original or last database.  This bug is in Snowflake.

### DBeaver Version

Version 22.2.1.202209251341

### Operating System

macOS Monterey 12.6

**Comment by E1izabeth** [comment]
[This feature was turned off](https://github.com/dbeaver/dbeaver/wiki/Separate-Connections) for Snowflake due to [repeated authentication for MFA](https://github.com/dbeaver/dbeaver/issues/17288).

**Comment by miTsirraH** [comment]
This is terrible that it has been turned off. It is going to cause people to execute SQL in the wrong context.
What was the last version this was not turned off for?

**Comment by E1izabeth** [comment]
DBeaver 22.1.2 doesn't contain this yet.
We will return back the ability to open sql editor in a separate connection for Snowflake. Thank you.
