### ISSUE TITLE
SQL Editor : Context menu in result area shows disabled "Copy" function after first select

### ISSUE THREAD

**Issue by kaiten27** [dbeaver/dbeaver#17781]
### Description

"Copy" function in the context menu of the SQL Editor result set is disabled on "first select". 

### DBeaver Version

Community  22.2.1.202209251341

### Operating System

Windows 10 64-Bit 

### Database and driver

Azure SQL Server 

Driver 
![image](https://user-images.githubusercontent.com/114728107/193219760-c667f625-d47a-4780-aeed-effc649cee3c.png)

![image](https://user-images.githubusercontent.com/114728107/193219823-f4e6dfc9-5e36-4a02-bebe-d8c1b7926b22.png)

### Steps to reproduce

Perform a select in the SQL editor that gives back a result set. 
Right click on one of the cells in the result set...

![image](https://user-images.githubusercontent.com/114728107/193220540-8e340d2b-c32b-4834-82f2-40e4aa37b4f3.png)

=> In the context menu the "Copy" is disabled. 

If you now click "somewhere else" ( not sure what exactly is the trick) ...and then again do the right click on the same cell....

![image](https://user-images.githubusercontent.com/114728107/193220464-f8234226-4763-4960-9e51-935b41968853.png)

now the "Copy" is enabled...

=> You also have to "click" around to do the copy... Not a super big problem, but a little annoying

**Comment by LonwoLonwo** [comment]
Ok, yes, I can reproduce it.

![2022-10-06 14_01_58-DBeaver Ultimate 22 2 2 - _Google Cloud SQL - SQL Server - test-mssql-instance_ ](https://user-images.githubusercontent.com/45152336/194296893-9aba5f28-b1b0-4c6e-acef-510f8981b654.png)

If any other rows are in the result - you can switch to them and back - then the "Copy" button will be available again. As a workaround.
