### ISSUE TITLE
Save all changed scripts on close

### ISSUE THREAD

**Issue by mousey92** [dbeaver/dbeaver#17795]
When closing DBeaver and multiple changed SQL scripts are not saved as indicated by the star on the script name:
![image](https://user-images.githubusercontent.com/26246536/193547229-c8d091c7-f97a-48a8-8309-f97c37f147d7.png)
a separate save prompt is given for each script. Instead of getting a save prompt per SQL script, add buttons to 'save all' and 'save none'

**Comment by E1izabeth** [comment]
Thank you for feature request. It's a duplicate of #12862
