### ISSUE TITLE
DBeaver Results Show Datetime but Changes on CSV export

### ISSUE THREAD

**Issue by cbreen872** [dbeaver/dbeaver#17799]
### Description

When I run a query using an Oracle DB in DBeaver the results show in datetime format. [DBeaver Results]([https://i.stack.imgur.com/0FuBA.png]

Recently, however, once the exports are exported to csv, I open the csv and only the time mm:ss are displayed. [CSV Result [Display]](https://i.stack.imgur.com/gQf6N.png)

I have to format back to the full datetime on every column once opening the csv.

Is there something I am missing in the DBeaver export settings? I am not sure why this started happening. [DBeaver Export Format [Settings]](https://i.stack.imgur.com/BfblP.png)

The data format settings seem to be correct as well. [DBeaver Data Format Settings][https://i.stack.imgur.com/C2T8P.png](url)

### DBeaver Version

22.2.1

### Operating System

Windows 10 Enterprise

### Database and driver

1. Database: Oracle 12
2.  Driver: oracle.jdbc.OracleDriver

### Steps to reproduce

1. I checked Global Settings and ensured the Timestamp setting was correct. 
![image](https://user-images.githubusercontent.com/15809358/193598510-7bf29be6-696b-4a9c-bf71-a7a447fe61e7.png)

2. I ran a query and checked that the results display the datetime stamp correctly
![image](https://user-images.githubusercontent.com/15809358/193598449-0e9d84c5-ea2e-4711-8453-596451fd6d12.png)

3. I hit the export button and went through the export settings 
![image](https://user-images.githubusercontent.com/15809358/193598862-730aa39d-8ca8-4160-9d92-0d42bc9a5425.png)

4. I opened the exported csv to find only the time displays instead of the full datetime 
![image](https://user-images.githubusercontent.com/15809358/193598985-68a7fa39-ca3b-4313-88c6-48d31489f4ee.png)

**Comment by Destrolaric** [comment]
Hi, could you open your CSV file in the Notepad and provide me a screenshot of it? Thanks.

**Comment by cbreen872** [comment]
Interesting - Would this mean that it is something in my excel settings
that would be causing this? Any idea what that could be?

Thank you!

[image: image.png]

**Comment by Destrolaric** [comment]
@cbreen872 Hi, sorry, but email replies don't support attachments. It's better to send them directly. I have a suspicion that it may not recognize the time format correctly.

**Comment by cbreen872** [comment]
![image](https://user-images.githubusercontent.com/15809358/194343893-746e5021-d7a7-4fe9-bf4e-f40e32d7ef2f.png)

**Comment by Destrolaric** [comment]
@cbreen872 
![image](https://user-images.githubusercontent.com/20579256/194344520-0f6cc0a6-2f1c-4cc1-88b0-b71441134042.png)
It looks like your excel uses an incorrect time format, you can change it manually in this excel menu. Write me if it helps.

**Comment by cbreen872** [comment]
Thank you - yes i know how to edit it after the fact, I was hoping there was a solution prior to doing that.  Sometimes i need to go in and edit 20+ datetime fields in the formatting tab and it's quite cumbersome.  I know from the dbeaver side it looks like its fine though, so that's good! Appreciate your help.  It was driving me crazy and I didn't even think to test in notepad++

**Comment by Destrolaric** [comment]
@cbreen872 You can always change the timestamp format in DBeaver itself Editors -> Data Editor -> Data Formats -> Timestamp
![image](https://user-images.githubusercontent.com/20579256/194353226-b44353c1-8526-46fb-aafc-d29f5926d5b1.png)

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.

**Comment by PerlaNT278** [comment]
You have to select the "Format numbers" option in square brackets in your Format Settings window in the exporter settings section
![image](https://github.com/dbeaver/dbeaver/assets/172448781/d5405379-6d4a-43f5-b5e2-347d0c3f3c20)

**Comment by daveleee** [comment]
> @cbreen872 ![image](https://user-images.githubusercontent.com/20579256/194344520-0f6cc0a6-2f1c-4cc1-88b0-b71441134042.png) It looks like your excel uses an incorrect time format, you can change it manually in this excel menu. Write me if it helps.

For those who are having trouble to find this window, you can click on the column and right click on it then you can find format cells.
