### ISSUE TITLE
Global persistent statement history feature request

### ISSUE THREAD

**Issue by stoty** [dbeaver/dbeaver#178]
One feature that I found very useful in Workbench, and is not yet available in DBeaver is  the global execution history feature. 

What I would like to see compared to the current execution log feature is a persistent history that
- contains the full text of the statement and the execution date
- including generated DDL statements
- maybe contains the DB connection and active DB that it was issued on
- History is stored by eclipse/DBeaver installation, and can be carried over in case of reinstall
- Independent of the mysql script that issued it
- can be browsed by date ( like in Workbench)
- maybe can be searched by regex/glob/sql like

**Comment by badloop** [comment]
Is there a status update on this?  Persistent history is key especially when queries are constantly changing in your workload and saved queries aren't nearly as beneficial.

**Comment by serge-rider** [comment]
DBeaver EE already has persistent queries history (in QMDB database). But it still doesn't have UI for it.
Probably will be added in 4.2 version.

**Comment by kruger5050** [comment]
Do you guys have any idea when this is implemented? Would be a very nice feature.

**Comment by serge-rider** [comment]
We plan to do it in 4.3.5 but honestly I'm not sure. 
We have too many FRs at the moment..

**Comment by serge-rider** [comment]
First implementation (basic search + filtering by query types and object types) will be added in 5.0.5.
It allows to search in all past queries including implicit metadata requests made by DBeaver.

Further improvements will be done in separate tickets.

Note: query history persistence is supported only in EE version (it is kept in embedded H2 database, this is one of the very few differences between CE and EE). In CE this feature works only for queries executed during current DBeaver session.
