### ISSUE TITLE
How to set the date format so that it doesn't change when importing the csv file to the dbever database column

### ISSUE THREAD

**Issue by rachmadhartono8** [dbeaver/dbeaver#17804]
### Description

I have a problem importing csv data into DBeaver DBMS, when importing data, the date column changes from 2022-09-30 to 2022-09-29, what should I do to prevent this problem from recurring in my dbever, thanks

### DBeaver Version

Community Edition 22.1.3

### Operating System

mac.OS.Monterey 12.2.1

### Database and driver

1. Database Name MySQL

### Steps to reproduce

I have a problem importing csv data into DBeaver DBMS, when importing data, the date column changes from 2022-09-30 to 2022-09-29, what should I do to prevent this problem from recurring in my dbever, thanks

**Comment by Destrolaric** [comment]
Hi, it looks similar to https://github.com/dbeaver/dbeaver/issues/16624, can you look at it?

**Comment by uslss** [comment]
thanks for the report
closed as a duplicate of #16624

**Comment by rachmadhartono8** [comment]
Thanks Sir and Mrs. That very help me

**Comment by johanyulian92** [comment]
Thanks for the questions
