### ISSUE TITLE
Generate UUID option only generates the same UUID for all rows

### ISSUE THREAD

**Issue by Shizukaax** [dbeaver/dbeaver#17805]
### Description

![image](https://user-images.githubusercontent.com/114982699/193761182-ce223e46-157c-4d04-bc6f-c2bd801c9b7f.png)

### DBeaver Version

22.2.1

### Operating System

Windows 10

**Comment by E1izabeth** [comment]
#4901

**Comment by LonwoLonwo** [comment]
Thanks for the report @Shizukaax

The UUID generator should be improved for the case of many columns, yes.

**Comment by LonwoLonwo** [comment]
Can be implemented with #4901
