### ISSUE TITLE
Row count in the properties tab is different from the row count in the data tab.

### ISSUE THREAD

**Issue by vince-payne** [dbeaver/dbeaver#17807]
### Description

I had a table with exactly 100k rows, which was verified by a count(*) query. Looking at the properties tab of the table shows that the row count is slightly smaller at 99,440 rows, and this anomaly was replicated on another machine with the same data set, but a different local database. On the data tab, the calculate total row count button also says there are 100k rows. 

First screenshot is from double clicking on a table, clicking the properties tab, and then clicking on statistics.
![image](https://user-images.githubusercontent.com/92732062/193841835-a2896f64-d8aa-4fe4-a47d-f4a3088e0775.png)

Second screenshot is from double clicking the same table, clicking the button on the bottom toolbar.
![image](https://user-images.githubusercontent.com/92732062/193842662-20c2ea6b-5a9e-4476-a060-3dadd1672756.png)

Third screenshot is just from the CLI verifying row count.
![image](https://user-images.githubusercontent.com/92732062/193844760-8c3e63ae-4581-4cb7-93aa-b4ffa24097e1.png)

### DBeaver Version

22.1.3

### Operating System

Ubuntu 22.01.1 LTS, Manjaro 5.13.19-2

### Database and driver

Database mariadb 10.8.3
MariaDB JDBC driver (I was unable to find a version number)

### Steps to reproduce

Write 100,000 rows to a table
open that table in dbeaver by double clicking on it in the navigator on the left
click on the properties tab just above the table view
click on the statistics button on the left and look at the row count value.

### Additional context

This so far has only been found on localhost connections. I haven't tried a remote connection, if that is relevant, I can try to reproduce it in that manner and update this bug report.

**Comment by LonwoLonwo** [comment]
Hello @vince-payne 

Yeah, I can reproduce it. And I found the reason.

We are using the [SHOW TABLE STATUS](https://mariadb.com/kb/en/show-table-status/) statement for the additional table information reading - which you can see in the Statistics tab.

But, I see many bug reports incorrect rows number in the result of this statement. Like here: https://stackoverflow.com/a/8624606

I'm not sure what we can do here from our side. 
And as you said - you can always count rows with the special count button.

**Comment by vince-payne** [comment]
Alright thank you. This issue can probably be closed then.

**Comment by laustam** [comment]
The issue described by @vince-payne still persists. May I suggest to add a small warning sign (⚠️) to the Statistics tab? That might cause less confusion for future devs.
