### ISSUE TITLE
Downloading the Data in the Tables

### ISSUE THREAD

**Issue by nosequins** [dbeaver/dbeaver#17818]
### Description

<img width="562" alt="dbeaver error" src="https://user-images.githubusercontent.com/63614464/194090511-c894e0df-0a51-40ab-aa5d-2d53071fad41.PNG">

I can't extract all the rows in my table that has over 1,400,000 rows. I tried segmenting the data, so that I can get multiple output files, but at times I'll either get 1 file or 2 files with one file having the max amount of rows for a microsoft excel file while the other file would only have about 100,000 + rows. I know the total amount of rows I'm supposed to have all together, but the output files all together aren't reflective of that. If I'm getting a random number of output files each time I proceed with downloading, then I don't even trust that I have the correct even within the files.

### DBeaver Version

Community Edition 22.2.0

### Operating System

Microsoft Windows 10 Enterprise 

### Database and driver

1. Database Name and Version: PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.41881
2. Driver Name: RedshiftJDBC 42-1.2.43.1067

### Steps to reproduce

1. I right click on the table I want to download.
2. Click the export selector, then I clicked on the CSV and hit "Next"
3.
- Extract type: By segments
- Segment size: 400,000
- Check select row count
- Fetch size: 10,000
- Then click "Next"
4.
- formatting: <Connection's default>
- Binaries: inline, Encoding: binary
- Value format: Display (default)
- Then click "Next"
5.
- Set my directory to my specific folder
- Check "Show finished message"
- Then click "Next"
6. Click "Proceed"

**Comment by LonwoLonwo** [comment]
Hello @nosequins 

If I understood you correctly, you need to use this export setting:

![2022-10-13 10_40_41-DBeaver Ultimate 22 2 2 - _language](https://user-images.githubusercontent.com/45152336/195533450-459b15ad-b034-432b-b943-7aab8554a9ea.png)

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
