### ISSUE TITLE
error open script location

### ISSUE THREAD

**Issue by rauleando** [dbeaver/dbeaver#17815]
### Description

You cannot open the folder where the script you select is located. 

### DBeaver Version

22.2.1

### Operating System

Ubuntu 22.04

### Database and driver

SQLite
Mysql

### Steps to reproduce

1. Proyect > Scripts
2. Properties any script
3. Click open the path
**¡Error file manager!**

### Additional context

The failure is due to the fact that it tries to open the script with the file manager instead of the folder that contains that script.

**Comment by LonwoLonwo** [comment]
Can you provide some sreens of this issue please? For now, I can't reproduce.

**Comment by rauleando** [comment]
![Captura desde 2022-10-05 14-18-53](https://user-images.githubusercontent.com/115075271/194058664-6a879163-cdcc-4fbd-9342-68ac559d73b0.png)

**Comment by LonwoLonwo** [comment]
How did you install DBeaver? Do you have any DBeaver extensions?

**Comment by rauleando** [comment]
sudo snap install dbeaver-ce
no extensions

but in another virtual machine I have installed the debian package from the official website and exactly the same thing happens. Error when trying to open the folder where the script is located.

**Comment by rauleando** [comment]
![error_open_origin_file](https://user-images.githubusercontent.com/115075271/194288297-b2bd7575-7e02-4c8b-a79f-1c463aaaa1dc.png)
![properties_script](https://user-images.githubusercontent.com/115075271/194288300-f36c0c49-7cd9-46c0-9ea0-f6726c97f826.png)

**Comment by rauleando** [comment]
With the new version 22.2.2 it has been solved. Thank you, great job!

**Comment by LonwoLonwo** [comment]
Thanks for your answer @rauleando
