### ISSUE TITLE
Horizontal scrolling with pinned columns is broken when using Shift+Scroll

### ISSUE THREAD

**Issue by VitaliiTsilnyk** [dbeaver/dbeaver#17827]
### Description

When there is a pinned column in the table data grid view, scrolling to the left using Shift + Mouse Scroll Wheel jumps to the beginning (the leftmost position of the scrollbar). While scrolling to the right keeps working fine.
This only happens when a column is pinned, otherwise it's working fine.

### DBeaver Version

22.2.1.202209251341

### Operating System

Microsoft Windows 10.0.19044.1889

### Steps to reproduce

1. Open a table data view.
2. Perform horizontal scrolling in both directions using Shift + Mouse Scroll Wheel and make sure it's working fine.
3. Pin any column, any number of columns actually.
4. Horizontal scrolling to the right with Shift+Wheel is working fine. But when scrolling to the left, it jumps immediately to the beginning.

### Additional context

On the video below I'm using Shift + Scroll Down a few times to scroll right; Then Shift + Scroll Up a few times to scroll left; Then repeat the same again. Everything works fine up until this point. Then I'm pinning a column and doing the same inputs again.

https://user-images.githubusercontent.com/218479/194260083-6816b4a5-f5a6-4291-89df-927fcd3e8206.mp4

**Comment by uslss** [comment]
thanks for the report
