### ISSUE TITLE
Problem regarding the tables importation

### ISSUE THREAD

**Issue by aalleaa** [dbeaver/dbeaver#17821]
### Description

I sorry to bother you but I have a problem regading the data importation on Dbeaver. I try to apply the easy method as describe here : https://dbeaver.com/docs/wiki/Data-transfer/
But all my columns are in the same column. Instead of having 10 columns with their own data, I have one column with the 10 data separated by a semicolon.

To avoid this problem I tried to create my table and then create the columns one after the other by doing :
- "right click" in the columns tab of the table
- "import data" and select my one-column CSV file
- repeat the manoeuvre for the 10 columns (the 10 single-column CSV files)

However when I do this, only the first column I import has data and all the others are empty. Do you know what the problem is? Is it me making a mistake or is there a problem with Dbeaver?

Thank you for your answer

### DBeaver Version

22.1.3

### Operating System

Windows 10

**Comment by LonwoLonwo** [comment]
Hello @aalleaa 

Can you please make a video of your steps? Or some screens?

**Comment by aalleaa** [comment]
Hey! Yes of course!
I did [Dbeaver_test.zip](https://github.com/dbeaver/dbeaver/files/9823273/Dbeaver_test.zip). 
The problem I want us to focus on is not the error at the end of the procedure when I click on start (commencer in French) but it's when I preview the datas, I am suppose to have 3 columns and all the informations are in the same one.

**Comment by iraidaa** [comment]
Hi @aalleaa,

I suggest changing the Column delimiter in the Input files tab of the Data Transfer wizard. I think you need a semicolon instead of the default comma. 
![image](https://user-images.githubusercontent.com/49681450/198220968-76e7e388-8e7b-4dae-b23c-1afea859f812.png)

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
