### ISSUE TITLE
Joins Between Simple Text and Text That Looks Like Numbers Fails

### ISSUE THREAD

**Issue by JEBanasik** [dbeaver/dbeaver#17824]
### Description

Cannot make a join between a regular text column and a text column that looks like numbers.  DBeaver throws an error that the number contains an invalid character.  Here is the setup: ERP System #1 (ERP1) extract has tables that are 100% NVARCHAR2(500) and ERP System #2 (ERP2) extract has tables that are also 100% NVARCHAR2(500).  The third system is an ORACLE database holding these extracts and the compilations of extracts in different tables. There are two columns of concern in each.  These columns are ID and NAME.  ERP1.ID contains alphabet text characters, with ERP2.ID containing numeric text characters.  The development database has a table the contains a mix of ERP1 and ERP2 data.  This table has been filtered to eliminate any duplicate NAMEs and keeps the original IDs for these NAMEs.  The row count in the development system is less than the sum of ERP1 and ERP2.  The NVARCHAR2(500) ID columns in the development system has both regular and numeric looking alphabets mixed together.  When attempting to join these ERP1 and ERP2 mixed ID column with another table that has only numeric looking alphabet characters, DBeaver throws an error about a number containing an invalid character.  This happens when the join reaches the regular alphabet character in the mixed column.

My take on this is DBeaver is seeing things that look like numbers and converting them to numbers as part of the join work.  Then the join fails when it cannot connect a number with text.  So why are the numbers being converted from text to a number when text was provided?

This issue is creating a major workaround to accomplish something that should be simple to do and involves taking the data to Excel to perform manual compares of the data.  SMH

### DBeaver Version

Community Edition 22.2.1.202209251341

### Operating System

Window Server 2016 (used as a workstation)

### Database and driver

Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
PL/SQL Release 11.2.0.4.0 - Production
"CORE	11.2.0.4.0	Production"
TNS for Linux: Version 11.2.0.4.0 - Production
NLSRTL Version 11.2.0.4.0 - Production

### Steps to reproduce

See Description above.

### Additional context

Normal network connection between Windows 2016 Serve in the datacenter and Oracle in the datacenter.  Users VPN from Windows 11 to the datacenter.  DBeaver is installed on Windows 2016 Server.

**Comment by LonwoLonwo** [comment]
Hello @JEBanasik 

Can you provide some screens of your issue please? 

Also, could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by JEBanasik** [comment]
I’m sorry.  I’m too busy using Excel on a major project to accomplish what I couldn’t do with DBeaver.  It would only take a few minutes to create some test tables for yourself.

**Comment by LonwoLonwo** [comment]
I'll wait.

**Comment by JEBanasik** [comment]
I solved my issue by using ON CONCAT(‘X’, ERP1.ID) = CONCAT(‘X’,ERP2.ID) in the JOIN.  This forced Dbeaver to use text comparison.  This did not change the results of the JOIN’s output.

I’m sure you can solve it with this additional information.

**Comment by LonwoLonwo** [comment]
I can not. I need extra info: screens and scripts. 
Any additional information will be helpful.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
