### ISSUE TITLE
Clear function not working in DB Navigator 

### ISSUE THREAD

**Issue by PaulDokken** [dbeaver/dbeaver#17838]
### Description

When searching in the Database Navigator the clear button does not work in the search.  I am using CE 22.2.1 for Mac.  I know this is a minor thing but just wanted to report it.
![image](https://user-images.githubusercontent.com/75853422/194342500-3b319271-9357-4c36-989d-b2931bc5e6ad.png)

### DBeaver Version

22.2.1

### Operating System

macOS 12.5.1

### Database and driver

MySQL 5.7

### Steps to reproduce

Search for a table in the Database navigator and when you click the black icon with the x in it the search box does not clear

**Comment by LonwoLonwo** [comment]
Thanks for the bug report.

Duplicates https://github.com/dbeaver/dbeaver/issues/10590
