### ISSUE TITLE
Data Transfer stuck when connection is broken

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#17830]
### Description

Can't stop or retry data export if connection was broken while starting.
![image](https://user-images.githubusercontent.com/28875055/194278720-ab11aa9d-477b-49e0-95f6-21b3a95c9e89.png)

### DBeaver Version

DBeaver 22.2.2

### Operating System

Windows 10

### Database and driver

PostgreSQL 11

### Steps to reproduce

1. Load some data
2. Setup and start data export (somewhere in that moment the connection to the database was broken)
3. See an endless Fetching data status without any progress. No response on close or stop actions.

**Comment by serge-rider** [comment]
Can't reproduce anymore

**Comment by uslss** [comment]
Can reproduce against 22.3.4, postgresql

https://user-images.githubusercontent.com/31996417/217517051-28fdf03e-0cd4-4862-b675-3fa056ea9158.mp4

**Comment by arhayka** [comment]
Nobody can reproduce this ticket as well, we don't understand how to fix it.

**Comment by E1izabeth** [comment]
Can't reproduce anymore.
