### ISSUE TITLE
Question about the DDL tab on Table Properties Pages

### ISSUE THREAD

**Issue by michaelcollinsedgov** [dbeaver/dbeaver#17847]
How is that DDL retrieved from the DBMS?  Is there a JDBC API that is used to retrieve DDL from the DBMS, or is generated from system tables, or is it specific to the DBMS module?

**Comment by LonwoLonwo** [comment]
Hello @michaelcollinsedgov 

There is no JDBC API for table DDL extracting (as I know).

We are using different approaches for DDL creation for different DBMSs. Sometimes we can ask the database directly - as we do for MySQL with this query:

`SHOW CREATE <table_name>`

Or we can create table DDL from the table info - as we do for PostgreSQL.

So, it depends on DBMS.

Do you want to know more information about a particular database?

**Comment by michaelcollinsedgov** [comment]
Thanks for the explanation.  That is what I thought.

I have two main DBMS that I use: Oracle and Postgres based (Greenplum and Redshift).  So in the Postgres example, you do some queries against `pg_tables` and some other system catalog tables, and use that to "stitch" together the DDL you show?

**Comment by LonwoLonwo** [comment]
Yes. It is correct. DBeaver read info from `pg_attributes`, `pg_types` etc.

**Comment by chewygranola** [comment]
For the Postgres/Greenplum implementation, this is why the DDL feature does not pull the child partitions of a table into the definition?

**Comment by LonwoLonwo** [comment]
Because we implemented it just recently: https://github.com/dbeaver/dbeaver/issues/15905
You can check it in the last DBeaver version (but be careful with this case https://github.com/dbeaver/dbeaver/issues/17865)

**Comment by michaelcollinsedgov** [comment]
@LonwoLonwo can you point me to the code that does this?

**Comment by LonwoLonwo** [comment]
Hello @michaelcollinsedgov 

Starting here https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/edit/PostgreTableManagerBase.java#L132

If we are talking about partitions.

**Comment by LonwoLonwo** [comment]
Do you have any other questions @michaelcollinsedgov ?
Or I can close this ticket?
