### ISSUE TITLE
connect clickhouse show tables error

### ISSUE THREAD

**Issue by lucky-bin** [dbeaver/dbeaver#17852]
### Description

connect clickhouse show tables error,  `comment` not exists

Code: 47, e.displayText() = DB::Exception: Missing columns: 'comment' while processing query: 'SELECT name AS TABLE_NAME, engine AS TABLE_TYPE, database AS TABLE_SCHEM, comment AS REMARKS, database, name, uuid, engine, is_temporary, data_paths, metadata_path, metadata_modification_time, dependencies_database, dependencies_table, partition_key, sorting_key, primary_key, sampling_key, storage_policy, lifetime_rows, lifetime_bytes FROM system.tables WHERE database = 'test'', required columns: 'engine' 'database' 'sorting_key' 'lifetime_rows' 'comment' 'uuid' 'metadata_path' 'partition_key' 'lifetime_bytes' 'name' 'data_paths' 'metadata_modification_time' 'dependencies_database' 'is_temporary' 'storage_policy' 'dependencies_table' 'primary_key' 'sampling_key', source columns: 'sampling_key' 'primary_key' 'dependencies_table' 'storage_policy' 'is_temporary' 'dependencies_database' 'data_paths' 'name' 'metadata_modification_time' 'engine' 'uuid' 'lifetime_bytes' 'partition_key' 'metadata_path' 'lifetime_rows' 'sorting_key' 'database' (version 219.1.1)

### DBeaver Version

Community Edition 22.2.1

### Database and driver

clickhouse 219.1.1

**Comment by serge-rider** [comment]
The error happens inside Clickhouse JDBC driver itself (i.e. it is not DBeaver issue).

Perhaps it is because you have a quite old server version and use new driver.
Try `Clickhouse (Legacy)` driver instead.

**Comment by uslss** [comment]
fixed in the scope of #17879

**Comment by lucky-bin** [comment]
![image](https://user-images.githubusercontent.com/35718645/199002370-c8d6980e-b52b-45f2-af8f-a54ac3a612bd.png)
system.tables  not match  comment column;

dbeaver source sql:
SELECT name AS TABLE_NAME, engine AS TABLE_TYPE, database AS TABLE_SCHEM, comment AS REMARKS, database, name, uuid, engine, is_temporary, data_paths, metadata_path, metadata_modification_time, dependencies_database, dependencies_table, partition_key, sorting_key, primary_key, sampling_key, storage_policy, lifetime_rows, lifetime_bytes FROM system.tables WHERE database = 'test';
