### ISSUE TITLE
sql server Function and Procedure Issues

### ISSUE THREAD

**Issue by BobinYang** [dbeaver/dbeaver#17874]
### Description

1、sql server navigator： Function and Procedure  want a separate classification to distinguish them.
2、sql server navigator : cannot rename Function/Procedure name and F2 cannot take effect.
3、sql server navigator :Function cannot add a comment ,because  it is treated as a Procedure  and  occur  a error. 
<img width="963" alt="issue" src="https://user-images.githubusercontent.com/41612864/194984313-d3d08967-297f-4e9b-97af-839ff0e17b94.png">

### DBeaver Version

Community Edition 2.2.2

### Operating System

windows 11

### Database and driver

sql server 

### Steps to reproduce

1、sql server navigator： Function and Procedure  want a separate classification to distinguish them.
2、sql server navigator : cannot rename Function/Procedure name and F2 cannot take effect.
3、sql server navigator :Function cannot add a comment ,because  it is treated as a Procedure  and  occur  a error. 
<img width="963" alt="issue" src="https://user-images.githubusercontent.com/41612864/194984313-d3d08967-297f-4e9b-97af-839ff0e17b94.png">

### Additional context

1、sql server navigator： Function and Procedure  want a separate classification to distinguish them.
2、sql server navigator : cannot rename Function/Procedure name and F2 cannot take effect.
3、sql server navigator :Function cannot add a comment ,because  it is treated as a Procedure  and  occur  a error. 
<img width="963" alt="issue" src="https://user-images.githubusercontent.com/41612864/194984313-d3d08967-297f-4e9b-97af-839ff0e17b94.png">

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @BobinYang 

Incorrect:

`EXEC master.sys.sp_addextendedproperty 'MS_Description', N'test', 'schema', N'dbo', 'procedure', N'east_or_west';`

We need to use the function type name here:

`EXEC master.sys.sp_addextendedproperty 'MS_Description', N'test', 'schema', N'dbo', 'function', N'east_or_west';`

And this is the script for the object renaming.

```sql
exec sp_rename 'dbo.east_or_west','east_or_west_2',object
--1st parameter=Original object name
--2nd parmeter=New name
--3rd parmeter=Objecttype to rename(object,column,index)
```
