### ISSUE TITLE
Displaying wrong record number in Record View Mode

### ISSUE THREAD

**Issue by dibyendumca** [dbeaver/dbeaver#17875]
### Description

![image](https://user-images.githubusercontent.com/61493364/194997608-7bce254d-3777-4607-aa4f-12e3a71981ff.png)
![image](https://user-images.githubusercontent.com/61493364/194997706-19b54e40-031e-45ed-9fbd-83686606b73d.png)

The record Row number shown in Grid View is not the same as shown in the Record View.
Please refer the 2 screen shots images attached.
For every record its the same issue.

### DBeaver Version

Community Edition Version 22.2.2.202210092258

### Operating System

Windows 10 Version 21H2 Build 19044.1889

**Comment by ShadelessFox** [comment]
Hello @dibyendumca,

Thanks for the bug report
