### ISSUE TITLE
ClickHouse driver UInt64 wrong value

### ISSUE THREAD

**Issue by ajax16384** [dbeaver/dbeaver#17879]
### Description

current ("new") ClickHouser driver still produces wrong values with UInt64 fields

### DBeaver Version

22.2.2

### Database and driver

clickhouse-jdbc-0.3.2.jar

### Steps to reproduce

````sql
CREATE TABLE default.test_uint64
(
EventDate Date,
TestId UInt64
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(EventDate)
ORDER BY (EventDate, intHash32(TestId))
SAMPLE BY intHash32(TestId)
SETTINGS index_granularity = 8192;


insert into default.test_uint64 (EventDate, TestId) values 
('2022-01-01', 0)
,('2022-01-02', 1)
,('2022-01-03', 4294967295)
,('2022-01-04', 16218631392101484784)
,('2022-01-05', 18446744073709551615);


````
Current ClickHouse driver
```
toString(TestId)    |toUInt64(TestId)    |TestId              |
--------------------+--------------------+--------------------+
0                   |                   0|                   0|
1                   |                   1|                   1|
4294967295          |          4294967295|          4294967295|
16218631392101484784|17357176597978101064|17357176597978101064|
18446744073709551615|18446744073709551615|18446744073709551615|
```
Legacy ClickHouse driver
```
toString(TestId)    |toUInt64(TestId)    |TestId              |
--------------------+--------------------+--------------------+
0                   |                   0|                   0|
1                   |                   1|                   1|
4294967295          |          4294967295|          4294967295|
16218631392101484784|16218631392101484784|16218631392101484784|
18446744073709551615|18446744073709551615|18446744073709551615|
```
16218631392101484784 ->17357176597978101064 ???

**Comment by LonwoLonwo** [comment]
Hello @ajax16384 

I can reproduce it with your driver version, but not with the version: `ClickHouse JDBC Driver clickhouse-jdbc 0.3.2-patch11 (revision: 27f8951)`

So, I suppose, that this is a driver issue. And you can update your driver to fix it.

![2022-10-14 12_53_35-DBeaver 22 2 2 - test_uint64](https://user-images.githubusercontent.com/45152336/195819324-d202f7ac-4354-455c-8cca-d4e90c742560.png)

![2022-10-14 12_54_09-DBeaver 22 2 2 - _default_ Script-21](https://user-images.githubusercontent.com/45152336/195819334-25f5ff1e-7fa7-400f-b36e-8711f6977b60.png)

**Comment by ajax16384** [comment]
"Connection X configuration->Connection settings->Edit Driver Settings->Libraries->Download/Update"
Trying to download same 0.3.2 (no patched) version.

May be dbeaver pinned version sould be updated to fresh clickhouse driver repo reference?
https://github.com/dbeaver/dbeaver/blob/663b7dfbc986b5ff9f97bacb3d802eac869c59be/plugins/org.jkiss.dbeaver.ext.clickhouse/plugin.xml#L59

**Comment by E1izabeth** [comment]
These issues are also waiting for the driver update:
#16189
#16885
#17287
#17852
