### ISSUE TITLE
Error connecting to datasource  Unknow system variable 'character_set_client'

### ISSUE THREAD

**Issue by jackietl1018** [dbeaver/dbeaver#17876]
### Description

mysql5 connecter，local client is mysql  5.7.23

### DBeaver Version

22.1.5

**Comment by LonwoLonwo** [comment]
Hello @jackietl1018 

Please provide more info about your issue.

What steps to reproduce did you have?

Could you please send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. 

Thank you.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it.
