### ISSUE TITLE
PostgresSQL. Result-set fetch size isn't working

### ISSUE THREAD

**Issue by init931** [dbeaver/dbeaver#17887]
### Description

When I open table view "Data" page it usually select 200 rows. But now I can't open large table because dbeaver tries to download whole table.
Also isn't working resut'set fetch size.

![image](https://user-images.githubusercontent.com/45001853/195262420-b6688680-1b13-4b46-9db8-614494e1979d.png)

![image](https://user-images.githubusercontent.com/45001853/195262654-8025c8a7-ee46-437f-be98-e1eab2f9faf7.png)

### DBeaver Version

Community Edition Version 22.2.2.202210092258

### Operating System

Microsoft Windows [Version 10.0.19044.1586]

### Database and driver

PostgreSQL
postgres-jdbc 

### Steps to reproduce

1. View some large table
2. Open Data tab

**Comment by LonwoLonwo** [comment]
Hello. Thanks for the bug report.

You can read more about this problem here (with a workaround): https://github.com/dbeaver/dbeaver/issues/17865

Probably this is your case.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it.
