### ISSUE TITLE
I'm connected to Athena, relying on Presto. Is there a way to check which version of Presto I'm using? I have reason to suspect it's out of date.

### ISSUE THREAD

**Issue by Robynishere1** [dbeaver/dbeaver#17886]
**Is your feature request related to a problem? Please describe.**
The command in the below link doesn't seem to work and I want to see if it's because I need to update the version somehow:
https://prestodb.io/docs/current/sql/show-columns.html

Sorry if there's already a way to do this, if so please show me how!

Thank you!

**Comment by ShadelessFox** [comment]
Hello @Robynishere1,

You can use the `Test Connection` button found in the connection configuration dialog.

Let me know if it solves your issue.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
