### ISSUE TITLE
Copy File Path missing on some SQL scripts

### ISSUE THREAD

**Issue by wistlo** [dbeaver/dbeaver#17882]
### Description

Some open SQL scripts no longer offer the "Copy File Path" option on the tab right-click.  I first saw this in 22.2.1 and it persists in 22.2.2.  
![image](https://user-images.githubusercontent.com/154039/195115303-021b7a0c-936f-4813-8830-d8246c11f586.png)

I thought at first this was related to not having a assigned connection, but that was not the case.  ALso tried shortening the file path (by default, it's a MS Onedrive with a horrendously long root path), but that is not the issue.  File name length does not appear to be a factor, got same error on "C:\temp\today\t.sql" as the source file name.  

It does seem to still work for files that I originate as a script that are saved inside the dBeaver project:

![image](https://user-images.githubusercontent.com/154039/195117029-a981aa0c-2d74-441f-bc75-d1899fec6abb.png)

Some other options are missing, as well.  

### DBeaver Version

22.2.2

### Operating System

Windows 10 Enterprise 2009 10.0.19041.1806

### Database and driver

1. Database:  mySQL
2. Driver:  ID: mysql8  Driver for MySQL 8 and later

### Steps to reproduce

1. Open a mySQL or Postgres script in dBeaver SQL Editor
2. Access editor tab with right-click
3. Look for "Copy FIle Path" (with intention of including full path as a comment in the file, usually). Expectation:
![image](https://user-images.githubusercontent.com/154039/195118809-6b6d10fb-a095-437c-844f-dfcb536d906e.png)

4.  Path is missing, along with other options. Reality:
![image](https://user-images.githubusercontent.com/154039/195118910-61d62c93-424f-4eeb-bea7-c0773f18acab.png)

**Comment by Matvey16** [comment]
@wistlo Hello, it looks strange. Do you know if those script have any difference? How did you open the script that has wrong context menu?

**Comment by wistlo** [comment]
I tried opening several scripts from a variety of sources, including dBeaver>File Open, from Windows FIle Explorer, from Everything V1.5a (using Windows default file association) .   

The only pattern I could discern was that the first three .sql files I opened had the longer correct right-click menu, but as soon as one of the subsequent scripts opens without the menu, most of them open without it regardless of whether they were saved in a dBeaver project, opened from Windows Explorer, from Everything 1.5a, or from dBeaver Recent Files list.  

The length or complexity of the script did not seem to be a factor.    

EDIT:  again on 2022-10-14, opened 28 line query with 16 comment/blank lines (12 actual code lines), no "Copy FIle Path" option in right-click on SQL Script editor tab.  File was opened via Windows right-click "Open with dBeaver" option from Everything 1.5a (an advanced file manager tool) .  Closed and reopened with File > Recent Editors in dBeaver, same thing, no "Copy File Path."

**Comment by E1izabeth** [comment]
Do all opened files located in the same directory on your PC or not? Are all files stored on the local system or some of them are located in the network drive or some cloud?

**Comment by wistlo** [comment]
All files are local, or "local+" (part of OneDrive directory but designated to live on hard disk).

In the test case of the renamed "t.sql", the full path was

`c:\temp\today\t.sql`

This directory is **not affiliated** with OneDrive or any cloud service (corporate OneDrive is the only such service allowed on our workstations).   

I'm really watching subjectively for some indication of why some files show up with the "copy path" on the tab, and others not.  The only pattern I've observed so far is it works right after starting dBeaver but then later "Copy Path" quietly stops appearing on most (but not all) SQL editor tabs.  I wish I had more specific cases to provide you.

**Comment by E1izabeth** [comment]
We add this option to the context menu only if eclipse's method `getLocation()` returns not null.
From the documentation:

> Returns the absolute path in the local file system to this resource, or null if no path can be determined.
> ...
> If this resource is a linked resource under a project that is open, this method returns the resolved path to the linked resource's local contents. This value will be null in the case where the location is relative to an undefined workspace path variable.
> ...
> If this resource is a project that does not exist in the workspace, or a file or folder below such a project, this method returns null. This method also returns null if called on a resource that is not stored in the local file system. For such resources getLocationURI() should be used instead.

I guess we could try using `getLocationURI()` also. Seems it may help in some cases.

**Comment by wistlo** [comment]
> "If this resource is a project that does not exist in the workspace"

I may try to make sure the project exists in the workspace, time permitting.  I am not exactly sure how that works; I use projects for bookmarks connections, etc., but I tend to open .sql source directly via file manager (either directly from File Explorer or Everything 1.5a, or in dB's internal  File -> Open ).   

If I can remember to consistently include source in the workspace, that's a workaround.  (Again not sure how that happens, specifically to meet eclipse's `getLocation()` expectations.)   

This isn't a showstopper obviously but is annoying, especially given how well dBeaver works across the board and different databases—any little defect is the proverbial sore thumb.

**Comment by Urugamai** [comment]
Not sure this will help, but it seems the tab does know where the file actually is (just point at the tab without clicking and the path appears), it just does not give the various file options like Copy Path when you right-click.  In my case it seems the only tabs that do have the copy path option are those to the default Scripts folder in the project.  As mentioned by OP, this did work previously.  I do admit that I have not done extensive testing but the fact that the tooltip does know where the file is suggests that there is a bug in the right-click processing.

**Comment by palilulac** [comment]
Same thing with me. But this worked before even on company onedrive now it is not working at all. When hoovering over tab, data is read correctly, so it looks like all is there, just somehow not working for right click. 
What I have noticed, is that it is not working for all saved SQL files, so it is working when I create new file, and Dbeaver automatically saves it, but the second I go to File save (and change that initial save place) this is gone. Here is example, last pic is after saving script-4 to my local HDD

![opne in expl 00](https://github.com/dbeaver/dbeaver/assets/99472519/463daba8-1b84-417d-b995-a846e3b2382b)
![opne in expl 01](https://github.com/dbeaver/dbeaver/assets/99472519/7c2d8181-ac19-4752-bd8d-8289d4403bb2)
![opne in expl 02](https://github.com/dbeaver/dbeaver/assets/99472519/11d43b82-23f4-4d43-9fee-4608bb835131)
![opne in expl 03](https://github.com/dbeaver/dbeaver/assets/99472519/da8c1df0-6aed-4257-b342-ec7be62c9f50)
![opne in expl 04](https://github.com/dbeaver/dbeaver/assets/99472519/363ba73a-5fb9-48d4-9f52-0b5c774521bc)
