### ISSUE TITLE
Customize perspective shows incorrect preferences

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#17880]
### DBeaver Version

22.2.2

### Operating System

Win11

### Database and driver

Any

### Steps to reproduce

1. Go to Window -> Customize Perspective -> Menu Visibility tab
2. Uncheck `File` and some other menu items and save changes
3. Open perspective customization again

**Expected:** `File` is still unchecked
**Actual:** It is checked but is invisible in the menu

### Additional context

![dbeaver_i7off3Pt1J](https://user-images.githubusercontent.com/82543000/195068993-fe315361-db52-4f54-90ac-bdcd95fbff13.gif)

**Comment by serge-rider** [comment]
Fixe menu actions reconfigured.
Also many redundant items were removed for TE.

**Comment by DariaMarkaryan** [comment]
the problem remains for 'About' in the Help menu

https://user-images.githubusercontent.com/43252954/198577974-8912923d-98a7-4802-899a-40bbe7979ad9.mp4
