### ISSUE TITLE
missing 'tabs list icon'

### ISSUE THREAD

**Issue by almends** [dbeaver/dbeaver#17895]
### Description

I just upgraded from an older version.   In that version and in the screenshots on your home page there was always an icon to the right of the script tabs that allowed you to show the full list of tabs with the long names.  After upgrading I do not get that 'show list icon' that looked something like >>#

### DBeaver Version

Community  22.2.0.202209051344

### Operating System

Windows 10

**Comment by ShadelessFox** [comment]
Hello @almends,

Can you please provide a screenshot showing the problem? Thank you.

**Comment by almends** [comment]
The end of the Script tabs does not include the icon to show the list of tabs (full names)

**Comment by E1izabeth** [comment]
Can't reproduce. I have such button
![image](https://user-images.githubusercontent.com/28875055/196944878-4deb7ea0-08ab-470c-9780-5a609e9bcbb6.png)

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.

**Comment by almends** [comment]
I have noticed that the icon appears after a certain number of tabs are opened.  Its visibility is conditional

From: Dziyana ***@***.***>
Sent: Wednesday, November 30, 2022 5:38 AM
To: dbeaver/dbeaver ***@***.***>
Cc: Almendinger, Steven ***@***.***>; Mention ***@***.***>
Subject: [EXT]Re: [dbeaver/dbeaver] missing 'tabs list icon' (Issue #17895)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.

-
