### ISSUE TITLE
PostgreSQL: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#17897]
### Description

A simple query like "select * from some_table" either fails with "java.lang.OutOfMemoryError: Java heap space" or crashes the application under heavy load. The table from the query contains about 1.5 million records. This problem does not exist on version 22.2.1.
[Log file](https://github.com/dbeaver/dbeaver/files/9765707/log.txt)
![01](https://user-images.githubusercontent.com/22142845/195366585-e72a6ba0-ab06-4ce2-8622-6ce40dcc0302.JPG)
![02](https://user-images.githubusercontent.com/22142845/195366601-881063b2-8e3a-4cf3-adb4-48e12ae0ea71.jpg)

### DBeaver Version

Community Edition 22.2.2

### Operating System

Windows 10 x64

### Database and driver

DB: PostrgreSQL 9.5
Driver: PostgreSQL standard driver (postgres-jdbc)

### Steps to reproduce

1. Open new sql editor.
2. Execute query "select * from some_table"

### Additional context

No tunnels or proxy

**Comment by Colux195** [comment]
It happens exactly the same.

**Comment by LonwoLonwo** [comment]
Hello. Thanks for the bug report.

You can read more about this problem here (with a workaround): https://github.com/dbeaver/dbeaver/issues/17865

I'm closing this ticket as a duplicate.
