### ISSUE TITLE
Embedded Firebird File - Not sure this is a bug with DBeaver

### ISSUE THREAD

**Issue by kbhoward** [dbeaver/dbeaver#17908]
### Description

Trying to create or connect to an embedded/single-file/server-less firebird db file.
Using the driver that DBeaver downloads fails with "Connect to 'file2.fdb'", "com/sun/jna/Platform", "Unexpected driver error occurred while connecting to the database
  com/sun/jna/Platform
  com/sun/jna/Platform
"
![Screenshot from 2022-10-12 23-21-36](https://user-images.githubusercontent.com/8135585/195491673-72575114-5a1d-4b3a-87d3-5279c19027e5.png)

### DBeaver Version

CE 22.2.1

### Operating System

Debian Sid

### Database and driver

FirebirdSQL (JayBird JDBC Driver 4 provided by DBeaver)

### Steps to reproduce

1. Create a new connection
2. Choose "Embedded"
3. Choose "FireBird"
4. Change jdbc to "URL"
5. Enter jdbc:firebirdsql:embedded:<path to file>
6. Test connection

### Additional context

same error in Windows

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by kbhoward** [comment]
Files attached as requested.
Note that I had to rename '.log' to 'log.log' as github doesn't allow uploading hidden files.
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/9778655/dbeaver-debug.log)
[log.log](https://github.com/dbeaver/dbeaver/files/9778660/log.log)

**Comment by E1izabeth** [comment]
@kbhoward does the Fireberd database file located on your PC?

**Comment by E1izabeth** [comment]
I'm not sure that connection url `jdbc:firebirdsql:embedded:` is correct.

**Comment by kbhoward** [comment]
@E1izabeth
Hi E1izabeth,
Yes about the file; it is located on my local filesystem...no network drives.
I can connect to a Firebird server via TCP, by the way, just not the embedded file.
I'm not sure about the connection URL either, to be honest, but that is what I got from the Jaybird user manual:
`

3.1.4 Embedded Server

jdbc:firebirdsql:embedded:<database>

Similar to the Firebird client library, however fbembed.dll on Windows and libfbembed.so on Linux are used, falling back to fbclient.dll/libfbclient.so under the assumption it provides Embedded functionality. Requires correctly installed and configured Firebird embedded library and - for Jaybird 2.2 or earlier - the Jaybird native library, or - for Jaybird 3.0 - the JNA jar file.

Jaybird 4 and higher also support:

jdbc:firebird:embedded:<database>
`

Taken from here:
https://www.firebirdsql.org/file/documentation/drivers_documentation/java/faq.html#embedded-server

Thanks,
Keith

**Comment by kbhoward** [comment]
Also, I _can_ create an embedded Firebird DB using FlameRobin...so, I assume the drivers (shared object files, .so or .dll) are installed correctly....seems to be an issue with Jaybird or DBeaver...just not sure which....or an error or my part....just don't know what(?)

**Comment by kbhoward** [comment]
Looks like Dbeaver is still trying to network connect even though the url says embedded and the driver checkbox is marked 'Embedded'.  It is listed as 'localhost:3050'....see the first screenshot.

**Comment by E1izabeth** [comment]
Please, try 22.2.2 version

**Comment by E1izabeth** [comment]
Or maybe even better to wait for 22.2.3 release in a couple of days.

**Comment by flambchap** [comment]
@kbhoward Is the issue still present in the latest version?

**Comment by kbhoward** [comment]
Hello everyone,
Yes, I am still experiencing an error trying to connect to an embedded Firebird file.

I tried both 22.2.2 and .3

Thanks,
Keith

**Comment by kbhoward** [comment]
All,

I tried 22.2.5 on Debian, DBeaver said something about drivers missing, I forced download and overwrite.
Using a JDBC connection URL of jdbc:firebirdsql:embedded:/home/keith/file.fdb gives me an "unexpected driver error".
Removing the last colon so URL looks like this, jdbc:firebirdsql:embedded/home/keith/file.fdb gives an error of "Your user name and password are not defined. Ask your database administrator to set up a Firebird login."  The thing is, embedded FireBird database files don't support security, so, no user name or password are required.  I think it is still trying to network connect to a server....I changed the "embedded" keyword of the URL to "fakeserv", just made up jibberish to test the result and, as expected, I get the same username/password error.  What else can I do to assist the DBeaver team in resolving this bug?

Thanks
Keith

**Comment by kbhoward** [comment]
All,
This is still an issue in 22.3.
DBeaver still attempts a network request to localhost, even though I specified "embedded" in driver options and JDBC URL.
Still willing to test and give feed back if anyone is serious about resolving this issue.

**Comment by flambchap** [comment]
@kbhoward The fix is scheduled for the next release.

**Comment by E1izabeth** [comment]
@kbhoward you could try early access version https://dbeaver.io/files/ea/

**Comment by kbhoward** [comment]
Ok, will do.  Next couple of days...

**Comment by kbhoward** [comment]
I see....will be happy to test. Thanks for reminding.

**Comment by kbhoward** [comment]
Hello Everyone, Happy Holidays,
Just tried 22.3.1 and the issue persists.
Thanks
Keith

**Comment by mubeda** [comment]
The only way i found DBeaver to connect to Firebird embedded databases what Edit the connection and driver properties. and dowlnoad the proper drivers and JNA jar file. Check the screenshots to see what i changed.

![S1](https://user-images.githubusercontent.com/1380447/219717448-b62fe99f-dfc1-42a1-9ce5-76bf25aac7ed.jpg)




![S2](https://user-images.githubusercontent.com/1380447/219717469-0182f8ad-d4fd-4ad6-9aba-56c5d311625b.jpg)
![S3](https://user-images.githubusercontent.com/1380447/219717487-217ccd1f-672f-402b-8358-0291f7fa64b9.jpg)

**Comment by kbhoward** [comment]
Hi Mubeda,

Thanks for the response.
I can confirm that in the latest release of Dbeaver that it no longer
attempts to connect to a server when embedded is chosen.  I am, however,
tripping over the driver install/config.  I see from the screenshot you are
using Windows, and based on the folder name that it is the full release of
Firebird3, and not just the Jaybird release(?)....correct?  I see from the
icons displayed in the screenshot that you added a folder, but I don't no
about the jna.jar file....do I choose 'Add file' or 'Add artifact' in the
driver config?  Is there a reason you are using the full installation of
Firebird vs Jaybird driver?  Why version 3 as opposed to recent version 4?
I hope I don't overwhelm you with all the questions, just trying to
understand.  I tried the latest version of Jaybird, version 5, extracted
archive, added folder and added file, jna.jar file to paths, but it did not
work...same error.  So, I will try to duplicate what you have done and
download Firebird 3 server and point to it, and add file jna.jar.
Thanks
Keith

**Comment by kbhoward** [comment]
I was premature on Dbeaver not connecting to network when a connection is set to embedded....it still does in Windows.
@mubeda Would you please outline the exact steps you took to get an embedded connection on Windows?
I already have Firebird3 installed in Program Files, and I downloaded Jaybird and added it to that folder.  I now get this error message, still trying to connect to network:
![image](https://user-images.githubusercontent.com/8135585/219765508-035676ca-2bb3-466c-ba9a-603c7d578394.png)
Connection settings:
![image](https://user-images.githubusercontent.com/8135585/219765702-94989597-80c3-4237-827d-342736bd2416.png)
Library settings:
![image](https://user-images.githubusercontent.com/8135585/219766460-08132521-aa25-4784-9ab9-ac87e4c73788.png)
Driver Template:
![image](https://user-images.githubusercontent.com/8135585/219767058-c337053c-ade0-40db-b949-48c9a9ea74af.png)
Java 16:
![image](https://user-images.githubusercontent.com/8135585/219767239-30bba77c-3b3d-496e-a332-a6c80ab9d75c.png)

**Comment by kbhoward** [comment]
In Debian 12 Linux, success!
I had to leave (close out) Dbeaver and go back in then it worked:
![Screenshot at 2023-02-17 14-36-08](https://user-images.githubusercontent.com/8135585/219772318-0fd86708-b5e2-4998-a8e2-fc711ec6e68f.png)

**Comment by kbhoward** [comment]
Got it!
On Windows, I uninstalled Dbeaver, all versions of Firebird and FlameRobin and JayBird.
Reinstalled latest version of each (Firebird4, FlameRobin9.6, Jaybird5).
Setup security for Firebird4 (security.db), apparently even the embedded needs to have it setup, even though it doesn't use it(?)....
In DBeaver, under the driver libraries, added the path to installed Firebird4 root folder (in Program Files) as the embedded server needs a lot more files present, all of which are located here, added a path to the Jaybird5 root directory, and finally added the file for the jna.jar file.
The xnet error is a protocol error coming from the driver and it IS trying to connect via a file and NOT tcp/ip...this and alot of other useful information here: https://ib-aid.com/download/docs/fb4migrationguide.html#_installing_embedded
Probable cause was the lack of the other required files (i.e. fbintl.conf, fbintl.dll, fbclient.dll, firebird.conf.....etc, etc.).
Lastly, the file structure of the db files has changed from Firebird3 to 4, you can convert it using gbak or point to the employee.db in the examples folder.
SO, using the guidance provided by @mubeda and the updated version of DBeaver and perseverance, I got DBeaver to connect to embedded Firebird db in both Windows and Gnu/Linux Debian 12.

Thanks
Keith

**Comment by mubeda** [comment]
> Got it! On Windows, I uninstalled Dbeaver, all versions of Firebird and FlameRobin and JayBird. Reinstalled latest version of each (Firebird4, FlameRobin9.6, Jaybird5). Setup security for Firebird4 (security.db), apparently even the embedded needs to have it setup, even though it doesn't use it(?).... In DBeaver, under the driver libraries, added the path to installed Firebird4 root folder (in Program Files) as the embedded server needs a lot more files present, all of which are located here, added a path to the Jaybird5 root directory, and finally added the file for the jna.jar file. The xnet error is a protocol error coming from the driver and it IS trying to connect via a file and NOT tcp/ip...this and alot of other useful information here: https://ib-aid.com/download/docs/fb4migrationguide.html#_installing_embedded Probable cause was the lack of the other required files (i.e. fbintl.conf, fbintl.dll, fbclient.dll, firebird.conf.....etc, etc.). Lastly, the file structure of the db files has changed from Firebird3 to 4, you can convert it using gbak or point to the employee.db in the examples folder. SO, using the guidance provided by @mubeda and the updated version of DBeaver and perseverance, I got DBeaver to connect to embedded Firebird db in both Windows and Gnu/Linux Debian 12.
> 
> Thanks Keith

Hey Keith ! Sorry to been late to the party, i was off all the weekend.  I'm glad you find the way to make it work.
Regards,
Mauro
