### ISSUE TITLE
Can't create the new task in some cases

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#17904]
### Description

If I do not select something and just want to create a new task by the context menu pressing on an empty place in the tasks area, I can't.
![image](https://user-images.githubusercontent.com/28875055/195452088-195cf576-321c-4df1-8bd1-0c6251015544.png)

Also we have toolbar with "create new task", "create tasks folder" and "delete". This actions appear when I focus a navigator object, but do nothing and just disappear when I click on this buttons.

https://user-images.githubusercontent.com/28875055/195463847-788f6f23-2904-4573-bf35-e83596f5fe73.mp4

Also I don't think that we need delete toolbar button to be appeared on navigator object click. It's not clear what are we going to delete. Delete should appear only when I click on the task in my opinion.

### DBeaver Version

DBeaver 22.2.2

### Operating System

Windows 10

**Comment by serge-rider** [comment]
Tasks view was redesigned.
Now we see only tasks for the active project.
Some ocmmands were moved from toolbar to the view menu.
Active project selector was added to manu as well.

**Comment by Matvey16** [comment]
This removed the buttons to create tasks/folders in toolbar

Expected:
![dbeaver_34tVdMjwY0](https://user-images.githubusercontent.com/82543000/196179449-9a043853-032d-4e73-a069-5591e4ff5685.png)

Actual:
![dbeaver_GLsGucsHfK](https://user-images.githubusercontent.com/82543000/196179490-829ef9e7-52fb-4688-a69e-8b465827fb23.png)
