### ISSUE TITLE
Shortcut for Adding Column/Field

### ISSUE THREAD

**Issue by iambudi** [dbeaver/dbeaver#17919]
Just like shortcut for adding row, it would be nice to have shortcut for adding column `(cmd +)`.

![image](https://user-images.githubusercontent.com/31809529/195727042-990c3a6c-61b6-467f-82bb-a62958badda6.png)

**Comment by flambchap** [comment]
Thank you for the idea.

**Comment by arhayka** [comment]
We want to implement this feature as follows:
1. Use the  [used in Data Editor ](https://github.com/dbeaver/dbeaver/wiki/Shortcuts#result-set)(`Alt+Insert` — if it works correctly on macOS).
2. When multiple objects can be added, this shortcut should open a list with available options.

**Comment by flambchap** [comment]
@arhayka There is no insert button on most keyboards for Mac, and, AFAIK, no universal substitution combination.
