### ISSUE TITLE
Some symbols( ` , ") in columns name are repeated twice during data import to new table

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#17914]
### Description

Some symbols( ` , ") in columns name are repeated twice during data import to a new table if the column name was changed during the import.

was founded during the check of #17619 

### DBeaver Version

22.2.2

### Operating System

win10

### Database and driver

mysql 5.7

### Steps to reproduce

1. Start import from csv to new table
2. Change some column name by adding, e.g. grave accent - We can see that grave accent is doubled in the mapping dialog
![dbeaver_T1KRfjwi11](https://user-images.githubusercontent.com/31996417/195330439-013a1e51-f744-4103-a7ca-0b1180fdb935.gif)

3. Check table DDL - there are four grave accent in DDL
![image](https://user-images.githubusercontent.com/31996417/195330213-aba1a905-dcaf-4404-b24a-9bd02232cbb5.png)importing

**Comment by Arbaz23** [comment]
hello, can i take this issue ?

**Comment by LonwoLonwo** [comment]
Do not forget about ' char (#18148)
