### ISSUE TITLE
JSON format does not work for data editor

### ISSUE THREAD

**Issue by jyinpci** [dbeaver/dbeaver#17913]
### Description

When editing data in data editor, selecting JSON format, and then click ctrl_shift_f, the json data in the editor are not formatted.

### DBeaver Version

22.2.2

### Operating System

Windows 10 Pro

### Database and driver

oracle_thin

### Steps to reproduce

Select a record that contains columns having json strings.  
In the data editor, double click the column containing the json data to show the data in data editor (not inline editor).
In the data editor, select JSON format.
Click ctrl_shift_f to format.  But the data is not formatted as JSON.
See screenshot below.

![dbeaver-screenshot-2022-10-13](https://user-images.githubusercontent.com/12385381/195590682-3ee9700d-a952-4446-aa8e-6ab3a25ef099.jpg)

**Comment by ShadelessFox** [comment]
We need to add an additional action for formatting panel contents (and it should be available in standalone editors, too).

**Comment by eperovgit** [comment]
This was working before 22.2.2 and documented in
**DBeaver Documentation**
*Working with XML and JSON*
https://dbeaver.com/docs/wiki/Working-with-XML-and-JSON/22.2/

**Comment by ShadelessFox** [comment]
I believe this is a side-effect of #17586

**Comment by jyinpci** [comment]
Thanks for looking into this and for the comments.  I hope this gets fixed soon, or DBeaver makes the invocation of external editor easier.  As of now, using external editor has two difficulties: 1) it takes quite a few keystrokes to get the external editor started (right click -> select edit -> select external editor), and 2) the edited/formatted data do not go back to DBeaver easily (so it is more of external browser than editor.  One would need to copy/paste from the external editor back to DBeaver.).  

If DBeaver allows the configuration of a hotkey to bring up the external editor for the data pointed to by the mouse cursor, that would make external editor far more attractive.  Allowing the modified data to flow from the external editor back to DBeaver would be icing on the cake. :-)
