### ISSUE TITLE
Table appears to depopulate

### ISSUE THREAD

**Issue by doreenherold** [dbeaver/dbeaver#17939]
### Description

After creating a table and populating it, Refresh is clicked and the size of the table shows that it has been populated. But when the table is opened, it's empty. When the view is refreshed, the table size decreases. The attached video provides an illustration. The scripts used to create and populate the table have been used regularly in the past and the experience described above started happening since upgrading to DBeaver 22.2.2.
https://user-images.githubusercontent.com/44369283/196206841-5d02dad0-f430-45d8-adf5-d57d91485bc4.mp4

### DBeaver Version

Community Edition 22.2.2

### Operating System

Windows 10 Enterprise

### Database and driver

Database: PostgreSQL 11.13
Driver: PostgreSQL JDBC Driver (2.2.1?)

### Steps to reproduce

1. Create a table with script 1 (attached)
2. Refresh the view (F5)
3. Populate the table with script 2 (attached; includes the data to populate)
4. Refresh the view (F5) and note the table size
5. Open the table to review the data (my tables have been empty)
6. Refresh the view (F5) and note the table size (my experience is that the size reverts to 16K, no matter the size of the table in step 4)
[Step1.txt](https://github.com/dbeaver/dbeaver/files/9801741/Step1.txt)
[Step2.txt](https://github.com/dbeaver/dbeaver/files/9801742/Step2.txt)

**Comment by flambchap** [comment]
From what I can see in the video, the script fails on the VACUUM statement. I suggest executing the script using the `Alt + X` shortcut.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
