### ISSUE TITLE
Allow to execute SQL script before & after executing database export / import task

### ISSUE THREAD

**Issue by krasucki** [dbeaver/dbeaver#17938]
**Is your feature request related to a problem? Please describe.**
It is related to issue I submitted before (#13281), but since there is no progress on it (I understand that can be a specific/complicated problem). Here is an alternative proposal.

**Describe the solution you'd like**
Add option to execute (previously defined) SQL script before & after successfuly executing database *export / import* task .

**Describe alternatives you've considered**
Please take a look - #13281

**Additional context**
Sometimes it can be very specific to export / import (SQL Server) database - especially when it comes to maintaining foreign keys constraints as you may know. Please provide us option to execute additional SQL script in (at least) target's connection context. This way, for example we can take care of FK preparation on our own, run some custom logic before/after task execution etc.  Hope this make sense to you :)

EDIT: One more thing - it is important to run all of this in the same transaction context...

**Comment by LonwoLonwo** [comment]
Hello @krasucki 

If I understood you correctly - this is already implemented in DBeaver PRO versions as Composite tasks: https://github.com/dbeaver/dbeaver/wiki/Composite-Tasks

You can try it for free at https://dbeaver.com/trial/ (14-day free trial version)

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
