### ISSUE TITLE
Non-ASCII characters in Templates names mangled

### ISSUE THREAD

**Issue by jzaruba** [dbeaver/dbeaver#1794]
It appears that non-ASCII characters get saved with weird encoding. (I did not test whether this also applies to actual templates.)

When I noticed they are messed up I fixed one, left another untouched. After re-starting DBeaver the Template name I just fixed was mangled again, and the one I did not touch was mangled even more, i.e. where there were "wing-dings" before now are question marks.

![screenshot 2017-06-20 10 53 48](https://user-images.githubusercontent.com/6112450/27325291-425a3222-55a8-11e7-8218-976c62e01985.png)
![screenshot 2017-06-20 10 54 44](https://user-images.githubusercontent.com/6112450/27325298-45181e34-55a8-11e7-9a27-84e23fb2d69d.png)
![screenshot 2017-06-20 11 08 39](https://user-images.githubusercontent.com/6112450/27325305-4a3d8af2-55a8-11e7-9860-710bf88e8ec3.png)

**Comment by serge-rider** [comment]
Can't reproduce.
What is "Default resource encoding" on Preferences->Database?

**Comment by jzaruba** [comment]
UTF-8
Later today I can try that on my home PC too.

**Comment by jzaruba** [comment]
Tested also on my home PC, same issue. Both Windows 7 instllations are in Czech.
(In one case DBeaver is installed with the bundled-in JRE.)
