### ISSUE TITLE
Cannot reverse engineer a ER diagram from SQL server

### ISSUE THREAD

**Issue by msacs09** [dbeaver/dbeaver#17942]
### Description

SQL Error [40515] [S0001]: Reference to database and/or server name in 'master.sys.schemas' is not supported in this version of SQL Server.
  Reference to database and/or server name in 'master.sys.schemas' is not supported in this version of SQL Server.
  Reference to database and/or server name in 'master.sys.schemas' is not supported in this version of SQL Server.

### DBeaver Version

22.2.2.202210092258

### Operating System

windows

### Database and driver

SQL Server

**Comment by LonwoLonwo** [comment]
Hello @msacs09 

Looks like https://github.com/dbeaver/dbeaver/issues/5258

Do you use SQL Server Azure?

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
