### ISSUE TITLE
SSL parameters sslrootcert  in ClickHouse driver setting doesn't work

### ISSUE THREAD

**Issue by voregnev** [dbeaver/dbeaver#17951]
### Description

I can't connect with ssl root ca to cloud
(at any path in system and installed as Root cert)
system can't find cert

javax.net.ssl.SSLException: Failed to get SSL context
  Failed to get SSL context
  Failed to get SSL context
    No certificate data found
    No certificate data found

		"provider": "clickhouse",
			"driver": "com_clickhouse",
			"name": "cluster.mdb.yandexcloud.net",
			"save-password": true,
			"read-only": false,
			"configuration": {
				"host": "cluster.mdb.yandexcloud.net",
				"port": "**8443**",
				"url": "jdbc:clickhouse://cluster.mdb.yandexcloud.net:8443",
				"type": "dev",
				"properties": {
					"use_server_time_zone": "false",
					"use_time_zone": "false",
					"ssl": "**true**",
					"sslrootcert": "**C:\\ca.crt**" _any variation_
				},
				"auth-model": "native",
				"handlers": {
					"clickhouse-ssl": {
						"type": "CONFIG",
						"enabled": **true**,
						"save-password": true,
						"properties": {
							"ssl.ca.cert": "**C:\\ca.crt**",
							"ssl.client.cert": "",
							"ssl.client.key": "",
							"ssl.method": "CERTIFICATES",
							"ssl.mode": "**STRICT**"
						}
`

### DBeaver Version

СЕ 22.2.2.202210092258

### Operating System

Widows 7 Pro 6.1.7601 Service Pack 1 Build 7601

### Database and driver

Yandex ClickHouse driver (server version 21.3+)
com_clickhouse

### Steps to reproduce

I try to connect to clickhouse cluster with SSL and root cert
dbeaver can't locate file at any path

and setup it in driver or connection tab ( or both)

### Additional context

I try same at MacOS with same results
addition found that dbeaver generate **temp cert file**  and make connection with string.
temp cert  file include path from field in form as string

**Comment by Destrolaric** [comment]
@voregnev Hi. We reopened the Clickhouse SSL ticket. You can track progress there https://github.com/dbeaver/dbeaver/issues/17363 
Closing this one as a duplicate
