### ISSUE TITLE
Failed transactions seem to persist changes for snowflake database

### ISSUE THREAD

**Issue by tudorpop9** [dbeaver/dbeaver#17965]
### Description

Failed transactions seem to persist changes of the queries above the one that failed when a select is executed, but in fact it does not happen.
Example: -- have been put in the steps to reproduce 
*assume that all values for "col" are 0*
Begin
Begin Transaction;
    update table set col = 1 where ID = 1
    update table set col = 2 where ID = 'foo' -- fails
    update table set col = 1 where  ID = 3
Commit;
End;

Select col from table where id = 1 ---> Shows col value to be 1
Right click on the connection -> *invalidate/reconnect to database *
Select col from table where id = 1 ---> Shows the actual value previous of the transaction execution (0 which is correct)

### DBeaver Version

22.2.2, 20...., 21...

### Operating System

Windows 10, Windows 11

### Database and driver

1. Database: Snowflake
2. Driver: snowflake_jdbc 
3. Libraries: snowflake-jdbc-3.13.6.jar

### Steps to reproduce

1) *assume that all values for "col" are 0*
2) execute a failing transaction inside BEGIN/END keywords
Begin
Begin Transaction;
    update table set col = 1 where ID = 1
    update table set col = 2 where ID = 'foo' -- fails
    update table set col = 1 where  ID = 3
Commit;
End;

3) Select on the updated items before the failed query (value is the updated one, incorrect since transaction failed)
Select col from table where id = 1 ---> Shows col value to be 1

4) Right click on the connection -> *invalidate/reconnect to database *

5) Perform the previous select
Select col from table where id = 1 ---> Shows the actual value previous of the transaction execution (0 which is correct)

**Comment by ShadelessFox** [comment]
Hello @tudorpop9,

How exactly are you executing that block?

I suggest selecting it and pressing the `Ctrl+Enter` shortcut.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
