### ISSUE TITLE
Large tables load very slowly and take up a lot of memory.

### ISSUE THREAD

**Issue by grclague** [dbeaver/dbeaver#17962]
### Description

With the previous version of Dbeaver 22.2.1 (Looking at PostgreSQL) a 1.3G table opens in the table viewer in 32ms. When opening with the latest version (2022.2.2) after ~ 40 seconds DBeaver throws a Java heap space exception. Even when opening slightly smaller (eg: ~400M) tables they take excessively long to open in the data viewer tab (>30 seconds rather than < 1 second). 

### DBeaver Version

Community Edition 2022.2.2

### Operating System

Windows 11

### Database and driver

1. Database name and version: PostgreSQL 14
2. Driver name and version: Postgresql JDBC 42.2.5

### Steps to reproduce

1. Connect to the Database in the 'Database Navigator'
2. Open any schema containing a large table
3. Open the table and switch to the 'Data' tab

**Comment by hmica** [comment]
Seems duplicate of #17865

**Comment by LonwoLonwo** [comment]
Could you try this workaround https://github.com/dbeaver/dbeaver/issues/17865#issuecomment-1273928373 ?

**Comment by E1izabeth** [comment]
Does this issue still actual for the latest DBeaver version?
