### ISSUE TITLE
create custom test databases that are populated with fake data 

### ISSUE THREAD

**Issue by TomYule** [dbeaver/dbeaver#17963]
**Is your feature request related to a problem? Please describe.**
create custom test databases that are populated with fake data 

**Describe the solution you'd like**
https://github.com/emirozer/fake2db

**Describe alternatives you've considered**
https://github.com/DiUS/java-faker

**Additional context**

**Comment by flambchap** [comment]
We have the mock data functionality in our EE and UE editions. I suggest trying them: https://dbeaver.com/download/.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
