### ISSUE TITLE
Firebird updatable views appear as tables

### ISSUE THREAD

**Issue by michaschumann** [dbeaver/dbeaver#17967]
### Description

Firebird 3 Views that are accompanied by triggers that allow Insert, update and delete (I use this for simplifiying processes that write to a fully normalized database) are displayed as tables and the wring ddl is shown.

### DBeaver Version

22.1.3

### Operating System

Windows 11 22H1

### Database and driver

Firebird 3 latest version
jdbc:firebirdsql

### Steps to reproduce

create a table with several fields
create a view that selects from that table
create triggers for that view that server Insert, Update and Delete
Open this database in DBeaver and display the updatable view

**Comment by LonwoLonwo** [comment]
Hello @michaschumann 

Please provide DDL examples.

**Comment by uslss** [comment]
It seems it was fixed in #10492

If the issue is still actual for you against the recent version - feel free to reopen the issue with additional info to reproduce it
