### ISSUE TITLE
SSH Tunnel through multiple JUMP Servers

### ISSUE THREAD

**Issue by SaSa1983** [dbeaver/dbeaver#17976]
**Is your feature request related to a problem? Please describe.**
I have a ssh server to which i need to connect (on the shell) the following way:
ssh user@target -J user@jump01,user@jump02

From the target host I can reach the desired database server.
I'm currently unable to enter such a tunneling scenario in DBeaver.

**Describe the solution you'd like**
Redesign the of enable Jump-Server to allow adding or removal of additional servers.
There's no need for "reordering".

**Describe alternatives you've considered**
There's currently no alternative way as of my knowledge to solve this problem.

**Additional context**
![Bildschirmfoto 2022-10-20 um 09 56 53](https://user-images.githubusercontent.com/1494844/196891011-3712e6f4-1a9e-4fa8-b718-76397037bd00.png)

**Comment by E1izabeth** [comment]
Thank you for feature request.

**Comment by pss4281** [comment]
This would've been useful to us as well, our current setup includes multiple jump servers which forces us to use an ssh tunnel setup outside of dbeaver

**Comment by keenonkites** [comment]
agreed, multiple Jumposts would be useful. We have a few destinations that can only be reached via hopping from one to the next jumpost and so on.

**Comment by E1izabeth** [comment]
You can vote for the issue with 👍 under the issue description to promote it to a higher priority.
