### ISSUE TITLE
Update wiki about Separate connection options

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#17975]
We changed UI representation of this setting here https://github.com/dbeaver/dbeaver/pull/17948
Maybe we also should describe `Default` option.

**Comment by E1izabeth** [comment]
https://github.com/dbeaver/dbeaver/wiki/Separate-Connections

**Comment by tati-kru** [comment]
The second part of the article with the second screenshot is unclear. You have some explanation why you need to open a separate connection for the metadata editor but not for the SQL editors. Moreover, it is hard to find the checkbox for the editors on the screenshot.

**Comment by E1izabeth** [comment]
@tati-kru I added the motivation to have separate connection for each editor and fixed the second part which seems to be confusing. There is no checkbox on that preference page, only combo box with 3 options. Is there something else that I could improve?

**Comment by tati-kru** [comment]
Thank you, I'd added a border for the area with checkboxes on the second screenshot. There are a lot of checkboxes in this dialog and it's a bit confusing. But the text is fine now.

**Comment by E1izabeth** [comment]
I did something like border for both screenshots.
