### ISSUE TITLE
Is there APIs to add, edit and delete users in dbeaver?

### ISSUE THREAD

**Issue by anantya-ncompass** [dbeaver/dbeaver#17989]
I can't find any user management APIs in the DBeaver documentation. I need APIs to add, edit and remove user from BDeaver. Please provide me the documentation if available.

**Comment by E1izabeth** [comment]
What database do you use?

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
