### ISSUE TITLE
How to install and use this in arm based linux

### ISSUE THREAD

**Issue by deciphr102** [dbeaver/dbeaver#17984]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by deciphr102** [comment]
none of the version working in arm based linux

**Comment by E1izabeth** [comment]
How are you trying to install DBeaver?
Which of the ways mentioned here https://dbeaver.io/download/ do you use?

What does it mean "none of the version working"? Do you have some error on DBeaver start?

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
