### ISSUE TITLE
Problem with sorting (ASCII)

### ISSUE THREAD

**Issue by CelenaBb** [dbeaver/dbeaver#17982]
### Description

CREATE TABLE TEST1 (
ID NUMBER(38,0),
IP VARCHAR2(255)
);

INSERT INTO TEST1
(ID,IP )
VALUES(1,’1.2.3.4^110.0.0.2′);

INSERT INTO TEST1
(ID,IP )
VALUES(2, ‘110.0.0.0’);

INSERT INTO TEST1
(ID,IP )
VALUES(3, ‘110.0.0.2’);

according to ASCII character “.” is less than “1”

but in version 22.2.2.202210092258 The result of sorting

SELECT * FROM TEST1 ORDER BY IP

is:

110.0.0.0
110.0.0.2
1.2.3.4^110.0.0.2

Connection to my database by sqlplus gives different result of the same sorting

1.2.3.4^110.0.0.2
110.0.0.0
110.0.0.2

please explain the reason for incorrect sorting

### DBeaver Version

22.2.2.202210092258

### Operating System

Версия	20H2 ( Сборка ОС 19042.1826)

### Database and driver

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
com.oracle.database.jdbc:ojdbc8:RELEASE[12.2.0.1]

**Comment by LonwoLonwo** [comment]
Hello @CelenaBb 

Unfortunately can't reproduce your issue.

![2022-10-20 17_13_05-DBeaver Ultimate 22 2 2 - _orcl_Script-190](https://user-images.githubusercontent.com/45152336/196974944-e05e77f6-d272-403b-bcca-a92aece96119.png)

Sorting from the client-side (DBeaver) and the server side is the same (Oracle).

I used Oracle Oracle Database 12c and the same driver as you.

**Comment by CelenaBb** [comment]
![image](https://user-images.githubusercontent.com/116263928/196988664-d32103f5-d072-4296-b23f-8b3740a0feb0.png)
![image](https://user-images.githubusercontent.com/116263928/196988737-99bce724-939f-4180-ae23-78d19a107445.png)

this is what I see sorting the table by pushing the sorting buttom

**Comment by iraidaa** [comment]
Hi @CelenaBb,

Can you please check whether the issue remains in 22.2.3? I can't reproduce it in 22.2.3 with the same driver.

**Comment by CelenaBb** [comment]
Hi @iraidaa  
i have tried it in the same DBeaver and driver, but Oracle  18. It works correct. So I guess it something between DBeaver and Oracle 19 communication. 

More over oracle 19 works with DBeaver 7.3 uncorrectly

**Comment by ShadelessFox** [comment]
Hello @CelenaBb,

Have you tried changing the ordering mode to be server-side only?

![image](https://user-images.githubusercontent.com/35821147/199733962-9fa5eeb4-12c5-443b-b415-c8e5673124b3.png)

**Comment by CelenaBb** [comment]
Hello @ShadelessFox
yes i have
it does not change anything

**Comment by ShadelessFox** [comment]
It's really weird.

DBeaver does not change results in any way, therefore an explicit `ORDER BY` clause should yield the same result regardless of the DBMS tool you're using.

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
