### ISSUE TITLE
PostGIS geometry is not visible in 'Value' window

### ISSUE THREAD

**Issue by Nick-Nal** [dbeaver/dbeaver#17983]
### Description

Greetings 

After release of PostgreSQL 15 last week, I decided to make a clean installation of new DB version and manually upload my geoanalytical pet-project from source SQL-code (not a dump/backup restoration, because I also needed to update some geo data, too).

Anyway, all worked out fine except the fact that DBeaver doesn't show anything in GIS viewer - all I got is a 'No editor for [geometry]' message, screenshot below.

I've tried to switch drivers' versions to older releases, but no luck.

Last time when I've checked geometry data and map viewer worked - this spring (PostgreSQL 14.3, PostGIS 3.2.something, DBeaver 21.0.something)

Does new versions of PostgreSQL and/or PostGIS not fully supported yet?

![Screenshot](https://user-images.githubusercontent.com/92499666/196922747-5c6c0219-4272-42ea-992a-16772e070ec3.png)

### DBeaver Version

Community Edition 22.2.2

### Operating System

Windows 10 Pro 21H2 build 19044.1889

### Database and driver

1. Database name and version: PostgreSQL 15.0, PostGIS 3.3.1
2. Drivers: Postgresql JDBC 42.5.0, PostGIS JDBC 2021.1.0, postgis-geometry JDBC 2021.1.0

### Steps to reproduce

Try to view any geometry column in Map data editor in PostgreSQL 15 (PostGIS 3.3.1, Windows 10, DBeaver CE 22.2.2)

### Additional context

Extensions: Darkest Dark, Office Support

**Comment by E1izabeth** [comment]
Please, try switching Web engine setting to Internet Explorer. Does it help?

![189076967-0ccb360d-ed60-483e-b0b8-59494d0cfa6a.png](https://user-images.githubusercontent.com/28875055/196929360-7c0808ec-8360-4844-956a-8c3bcc9f8f4b.png)

**Comment by Nick-Nal** [comment]
Thanks a lot, it worked (after DBeaver restart)

**Comment by E1izabeth** [comment]
Duplicate of #17746
