### ISSUE TITLE
Context menus are still white when the app is in dark theme

### ISSUE THREAD

**Issue by DoctorKrolic** [dbeaver/dbeaver#17997]
### Description

Context menu is still white even when the app is in dark theme:
![dbeaver_kcak2LTA0A](https://user-images.githubusercontent.com/70431552/197404801-eff11c29-33b4-43e1-827c-88602390dec5.png)
The expected behaviour: context menu should change its color when the app is in dark theme

### DBeaver Version

Community Edition 22.2.2

### Operating System

Windows 11 22H2 build 22621.675

### Database and driver

PostgreSQL 14.5
PostgreSQL JDBC Driver 42.2.25

### Steps to reproduce

1. Change theme to dark
2. Create database connection
3. Right click on connection to bring context menu

**Comment by Destrolaric** [comment]
@DoctorKrolic, Hi. I have looked into the issue. It happens for Windows 11. Unfortunately, coloring is a part of Eclipse framework functionality, and the fix should be done from their side.

**Comment by E1izabeth** [comment]
Does this issue is still actual for the latest DBeaver version?

**Comment by DoctorKrolic** [comment]
Yes, this is fixed now, thanks!
