### ISSUE TITLE
The disk you attached was not readable by this computer

### ISSUE THREAD

**Issue by Maxx-Yang** [dbeaver/dbeaver#17998]
### Description

When i click Help->Check for updates,then dbeaver ask for me teminal app to update. when i click ok, then the error occurs.
<img width="260" alt="image" src="https://user-images.githubusercontent.com/32293803/197438280-6435347c-9b1f-4eea-bc6b-c1889464b8c9.png">

### DBeaver Version

Community Edition 22.2.1

### Operating System

macOS Monterey 12.6

### Steps to reproduce

1.Help -> Check for updates
2.The app ask me to close to update
3.I click 'OK'
4.After a few seconds, the error occurs

**Comment by flambchap** [comment]
Hi. Unfortunately, I cannot reproduce the issue. We are releasing the 22.2.4 version on Monday. Can you please try updating to that version and see if the issue is gone?

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info.
