### ISSUE TITLE
DBeaver 22.2.3 Portable - Unable to install DevStyle with CodeTogether Bundle 

### ISSUE THREAD

**Issue by valsamis-d** [dbeaver/dbeaver#18005]
### Description

System information:

    Windows 10 Enterpise 21H2 19044.2006
    dbeaver-ce-22.2.3-win32.win32.x86_64.zip

Steps to reproduce:

    Download and unzip "dbeaver-ce-22.2.3-win32.win32.x86_64.zip" into a folder
    Launch dbeaver.exe
    Navigate to Help > Install New Software
    Select Darkest Dark Theme - https://www.genuitec.com/updates/devstyle/ci/
    Select DevStyle Features > DevStyle with CodeTogether Bundle 

![image](https://user-images.githubusercontent.com/17590539/197493975-d680bc52-4bb0-4a9e-9f0b-b346f3da5bc8.png)

**NOTE: Darkest Theme was installed successfully.**

Error Message:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: a.jre.javase 10.0.0
  Software being installed: DevStyle with CodeTogether Bundle 1.11.0.202206271604 (com.genuitec.eclipse.theming.feature.feature.group 1.11.0.202206271604)
  Missing requirement: CodeTogether Client Unavailable 2022.2.2.202209131701 (com.genuitec.eclipse.codetogether.ui.client.legacy 2022.2.2.202209131701) requires 'osgi.bundle; org.eclipse.platform [0.0.0,4.8.0)' but it could not be found
  Cannot satisfy dependency:
    From: CodeTogether IDE-to-IDE Client 2022.2.2.202209131701 (com.genuitec.eclipse.codetogether.client.feature.feature.group 2022.2.2.202209131701)
    To: org.eclipse.equinox.p2.iu; com.genuitec.eclipse.codetogether.ui.client [2022.2.2.202209131701,2022.2.2.202209131701]
  Cannot satisfy dependency:
    From: CodeTogether Collaboration 2022.2.2.202209131701 (com.genuitec.eclipse.codetogether.feature.feature.group 2022.2.2.202209131701)
    To: com.genuitec.codetogether; codetogether.client [2022.2.2.202209131701,2022.2.2.202209131701]
  Cannot satisfy dependency:
    From: Client 2022.2.2.202209131701 (com.genuitec.eclipse.codetogether.ui.client 2022.2.2.202209131701)
    To: osgi.bundle; org.eclipse.tm4e.core 0.0.0
  Cannot satisfy dependency:
    From: DevStyle with CodeTogether Bundle 1.11.0.202206271604 (com.genuitec.eclipse.theming.feature.feature.group 1.11.0.202206271604)
    To: org.eclipse.equinox.p2.iu; com.genuitec.eclipse.codetogether.feature.feature.group 1.0.0
  Cannot satisfy dependency:
    From: TextMate support in Java 0.5.0.202206232130 (org.eclipse.tm4e.core 0.5.0.202206232130)
    To: osgi.ee; (&(osgi.ee=JavaSE)(version=17))


```

### DBeaver Version

22.2.3 Portable 

### Operating System

Windows 10 Enterpise 21H2 19044.2006

### Database and driver

DB2 JCC (Type 4)

**Comment by valsamis-d** [comment]
Following up here as I think I found out something. I'm not sure if this is the correct way to install "DevStyle with CodeTogether Bundle", but so far it looks like everything is working.

I noticed that a new site/repository appeared in "Available Sites":

![image](https://user-images.githubusercontent.com/17590539/197509845-11dde888-c8d2-40bb-9c80-ff6b201d3f23.png)

From there I installed  "CodeTogether Client 2022.2.2.202209131701" (or something similar... cannot remember exact name). As soon as this was installed and restarted DBeaver, "DevStyle with CodeTogether Bundle" was installed just fine.

If the above are indeed the right steps, please code this ticket.

**Comment by hnavia** [comment]
Thank you for the solution. It totally worked!

**Comment by flambchap** [comment]
@valsamis-d Thank you for the workaround. I think we need to update our wiki.

**Comment by iraidaa** [comment]
Hi @valsamis-d,

Your first error is caused by the fact that this plugin requires Java 17, while DBeaver uses Java 11.
Indeed, everything should work with the CodeTogether CI Update Site.
We've added information about this option to the wiki and plan to make it clearer in the future https://github.com/dbeaver/dbeaver/wiki/Eclipse-extensions.
Thank you.
