### ISSUE TITLE
Display line number in SQLServer error

### ISSUE THREAD

**Issue by powelleric** [dbeaver/dbeaver#18016]
If my query has an error in the SQL, when I run it in `sqlcmd`, I get: 

```
Msg 207, Level 16, State 1, Server MYSERVER, Procedure MyProc, Line 40
Invalid column name 'Id'.
```
In DBeaver I don't get the line number:

```
Error occurred during SQL query execution

Reason:
SQL Error [207] [S0001]: Invalid column name 'Id'.
```

**Comment by LonwoLonwo** [comment]
Hello @powelleric 

Ok, maybe we can try do this in the ticket https://github.com/dbeaver/dbeaver/issues/15320

Closed as duplicate
