### ISSUE TITLE
 Problem saving edited data in the column by the application

### ISSUE THREAD

**Issue by pedrobianco** [dbeaver/dbeaver#18013]
### Description

When editing a data in the table that returns the values, it does not enable the save option, only when executing another query, which displays a message to save or cancel.

### DBeaver Version

Community Edition 22.2.3.202210231354

### Operating System

Ubuntu mate 20.04.5 LTS

### Database and driver

Mysql database 5.7

### Steps to reproduce

1 - Give a select on a table that contains data.
2 - Edit data visually
3 - the save button will be disabled.

**Comment by flambchap** [comment]
@pedrobianco Hi. Can you please send us screenshots of the issue?

**Comment by pedrobianco** [comment]
@n5a5 Good morning, the problem is sporadic, I will see if it occurs now to send a screenshot

**Comment by pedrobianco** [comment]
@n5a5 I managed to simulate the problem, I edited the value and did not enable the save button

(https://user-images.githubusercontent.com/27033867/198302493-6a8cbab4-8c7b-4745-9ed2-d3ba4e2864bb.png)

**Comment by webian** [comment]
I have the same problem.
Is not only the save button disable, it's the whole bar that allows to edit/browse the result of a query.

I can't yet reproduce the problem systematically, but I found out that switching to the Data tab of a table did re-enabled the bar.

**Comment by Destrolaric** [comment]
@webian Hi, can you send me the logs? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. I think they may contain an error that led to the toolbar being disabled.

**Comment by uslss** [comment]
There have been no updates for a long. If issue is still actual for you - feel free to reopen it with additional info
