### ISSUE TITLE
Postgis preview

### ISSUE THREAD

**Issue by mc1986** [dbeaver/dbeaver#18010]
### Description

When a postgis column is selected (POINT, POLYGON or MULTIPOLYGON), the preview with default OpenstreetMap (or the other ones) not works but instead is request to save an HTML file on disk.
![image](https://user-images.githubusercontent.com/46898354/197517426-87e3a60d-474a-4039-90d1-cc1825049502.png)

### DBeaver Version

Community Edition 22.2.3.202210231354

### Operating System

Xubuntu 22.04

### Database and driver

Postgresql jdbc 42.5.0
postgis jdbc 2.5.0
postgis geometry 2.5.0
waffle jna 1.9.1

### Steps to reproduce

Select a postigis value in a postgis column (POINT, POLYGON or MULTIPOLYGON);

**Comment by flambchap** [comment]
Hi @mc1986, it's [a known issue](https://github.com/dbeaver/dbeaver/issues/16125). I suggest using [this workaround](https://github.com/dbeaver/dbeaver/issues/16125#issuecomment-1098990262).

**Comment by mc1986** [comment]
> Hi @mc1986, it's [a known issue](https://github.com/dbeaver/dbeaver/issues/16125). I suggest using [this workaround](https://github.com/dbeaver/dbeaver/issues/16125#issuecomment-1098990262).

Yes, it works!
I'm sorry: I tried to find a solution (or a workaround), but I didn't find anything before your suggestion.
Have a nice day
