### ISSUE TITLE
SSH Auth Fail after 22.2.3 update

### ISSUE THREAD

**Issue by brother-z** [dbeaver/dbeaver#18017]
### Description

Hi, it's me again :)
So after your fix for https://github.com/dbeaver/dbeaver/issues/17748 that came out in 22.2.3 it's better. I can click on "test tunnel" and it logs in fine using jump server and asking me for cert keys.
But - when I try to connect to database, after all the popups to enter credentials I'm getting "auth error".

From the point of view of my bastion server it seems like "test tunnel" function uses the right user name from config, but when it connects to the database it makes my user name uppercase and then server says "nope, no such user". Not sure if it does that for both bastion and server, because it dies after trying to connect to the bastion.

Rolling back to 22.2.0 again.

### DBeaver Version

22.2.3

### Operating System

Windows 10

### Steps to reproduce

Exactly same as in https://github.com/dbeaver/dbeaver/issues/17748

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by Matvey16** [comment]
Not reproducible anymore

**Comment by E1izabeth** [comment]
@brother-z, could you check if this issue is still actual for the latest DBeaver version? We can't reproduce it.

**Comment by brother-z** [comment]
Installed 22.2.4 and it's still the same - username gets uppercased when connecting to database, but works when just testing the connection. My login is a single letter, maybe that's some weird corner case ;)

Logs from bastion server:

"Test tunnel configuration" button - works fine - login is `a`:
```
sshd: Accepted publickey for a from ...
```

Connecting to database - "auth fail", login is `A`:
```
sshd: Invalid user A from ... port ...
sshd: error: Received disconnect from ... com.jcraft.jsch.JSchException: Auth fail [preauth]
sshd: Disconnected from invalid user A ... [preauth]
```

**Comment by E1izabeth** [comment]
Thank you for checking.

**Comment by brother-z** [comment]
OK, it's even more strange. I reconfigured connection to use `x` as login. Test connection uses `x`, server says no such user, but the login is proper, lowercase, so it picked up the change. But when I connect to database it still tries to use `A`, which happens to be my Windows user name... I tried on two different connections to same database and both behave the same, so it doesn't look like some error in config files.
-- edit
I'm using Win 10 with local account, if it changes anything.

**Comment by E1izabeth** [comment]
Could you send me screenshots of ssh and database credentials pages from connection edit dialog?
(Please, erase or hide important information like username or ip address)

**Comment by brother-z** [comment]
![db_00](https://user-images.githubusercontent.com/47743952/201439825-fe44b57f-47dd-44fa-8446-e97ac3eaf5a9.png)
![db_11](https://user-images.githubusercontent.com/47743952/201439844-a5880e7b-ff0c-42a2-83c7-dcc66af17e5f.png)
I hope I censored everything :). 
The "proxy" and "SSL" sections are not used, all the other things are default. Also when I rollback to 22.2.0, the exact same config works perfectly fine.
And to clarify one thing, didn't notice before that there's also "test connection" button. So "test tunnel configuration" uses right user name and works, "test connection" behaves same as trying to connect to database - seems to be using my Windows login, or a random letter from somewhere else that happens to be my login.

**Comment by E1izabeth** [comment]
Thank you so much for your investigation and help. I hope we will manage to reproduce it with  provided additional information or at least to find what could cause this issue.

**Comment by brother-z** [comment]
In my head it's something like off by one while checking configured username and then "if not username, default to Windows login", which might be some magic done behind the scene by the SSH library. But it's a pure guess, never looked at sources.

**Comment by brother-z** [comment]
Noticed that in 22.2.5 you added jump servers for SSHJ, so I just tried it out. Unfortunately it behaves the same as JSch - "test tunnel" works fine, "test connection" uses my Windows login instead of configured one.
I noticed two more things:
- if I configure my user name to something longer than single letter, it still behaves the same, so it's not some off by one, it's just confused :)
- SSHJ has new popup "permanently added ... to the list of known hosts", but it keeps saying that on every connection. Something similar happens for JSch, minus the "permanently added..." info. It happens only for database server, the jump server gets added properly. Database through jump server is seen as [localhost]:port, maybe that's messing up something.

**Comment by arhayka** [comment]
@brother-z 
Could you please upgrade DBeaver and see if it's reproduced in the new version?

**Comment by brother-z** [comment]
Unfortunately yes. "Test tunnel configuration" works (username passed to ssh is lowercase), "test connection" fails (username is uppercase, bastion server says "no such user").
Checked both JSch and SSHJ.
Rolling back to 22.2.0 :)

**Comment by E1izabeth** [comment]
Could you clarify if the user names in the tunnel settings and database settings are the same?

**Comment by brother-z** [comment]
No, for database itself I'm either as just "postgres", or some other names (but always longer than single letter and different than the SSH users).
The tunnel - both jump server and the target database server behind it - has same username, which is single, lowercase letter.
I use same, single letter for my offline Windows 10 account username, but this one is uppercase.
Maybe I'll make a new Windows user account and see if that fixes the problem...

**Comment by LonwoLonwo** [comment]
Could you please check the latest DBeaver version?

**Comment by brother-z** [comment]
Hi, I'm travelling right now, so don't have access o my Windows PC, on which the problem occurs. I should be back shortly after Easter and can test then.
Meanwhile, I'm using latest DBeaver on MacOS, where all versions, including v23 and now v23.0.1 work perfectly fine with exactly same server and configuration of ssh tunnels.

**Comment by LonwoLonwo** [comment]
Ok, thanks, we will wait.

**Comment by brother-z** [comment]
Tried 23.0.2 and it's still the same.
I even made a new local Windows account, made a fresh DBeaver config for the server and got exactly same result - "test tunnel configuration" works, "test connection" doesn't (because it tries to log in using Windows account username instead of the configured one).
With the new Windows account it's evident that it tries to use the Windows username to log into the SSH servers instead of the configured one, because both logins are now a different, single letter. So config says "user name: a", but SSH server says "unknown user X", where X is the name of the new Windows account I made. Unless I test only the tunnel, then proper "a" is used.
One thing to note - I install the app "for everyone", so if something got corrupted in some folder common for all users, it's still used in the new account I made. But then, during upgrade you seem to overwrite a lot of things, so I'd imagine anything there would be fixed.

**Comment by E1izabeth** [comment]
Thank you for checking and investigation

**Comment by brother-z** [comment]
A small update - I'm in the process of moving to Yubikey and thought I'll try what happens with DBeaver (23.0.2) connection when I tell it to use "agent" instead of "public key" and... it just works.
It seems that the only configuration when it decides to use wrong username for SSH is when the jump server uses "public key" (I don't save the passphrase in config if that changes anything).

**Comment by E1izabeth** [comment]
Unfortunately, still can't reproduce.

**Comment by brother-z** [comment]
Ok, I did something that I didn't want to do, because I haven't touched Java for quite some time. I think I found the problem using the power of FileWriter debugging (because vscode and default Java plugins refuse to place breakpoints and I don't want to spend another day to figure out why :).

So what happens - while UI is asking for certificate passwords the user name gets overwritten to null, which makes it default to OS user name just before connecting to jump server.

To be more exact:
 - data-sources.json are loaded properly, I can see jump server config with `JumpServer0.` prefix that includes nonempty `JumpServer0.name` in the properties when I'm here https://github.com/dbeaver/dbeaver/blob/d43681e9ff6face69aff6170acda9b9b73896890/plugins/org.jkiss.dbeaver.registry/src/org/jkiss/dbeaver/registry/DataSourceDescriptor.java#L1146
 - then this thing says "we need password" https://github.com/dbeaver/dbeaver/blob/d43681e9ff6face69aff6170acda9b9b73896890/plugins/org.jkiss.dbeaver.registry/src/org/jkiss/dbeaver/registry/DataSourceDescriptor.java#L1150 
 - which causes this thing to use `passwordOnly` flag and the user name that is passed in there gets erased https://github.com/dbeaver/dbeaver/blob/d43681e9ff6face69aff6170acda9b9b73896890/plugins/org.jkiss.dbeaver.registry/src/org/jkiss/dbeaver/registry/DataSourceDescriptor.java#L1152 
 - so then this happens, which effectively sets `JumpServer0.name` to `null` 
https://github.com/dbeaver/dbeaver/blob/d43681e9ff6face69aff6170acda9b9b73896890/plugins/org.jkiss.dbeaver.registry/src/org/jkiss/dbeaver/registry/DataSourceDescriptor.java#LL1161C9 
 - when JumpServer user name prop is empty this happens, which effectively sets it to my Windows user name, which is exactly what I see https://github.com/dbeaver/dbeaver/blob/d43681e9ff6face69aff6170acda9b9b73896890/plugins/org.jkiss.dbeaver.net.ssh/src/org/jkiss/dbeaver/model/net/ssh/SSHImplementationAbstract.java#L187

 I don't feel very comfortable making changes there, because there are some config variations possible and while fixing this, I might destroy something else. I think that changing the password-only window to a full credentials login+password one will fix the vanishing user name. As a bonus, it will also solve a different problem - if you don't provide username to jump server, UI will still ask only for certificate password and silently default to OS user name.

From call stacks, I can also see that the `Test tunnel configuration` button works, because it bypasses the whole `askForSSHJumpServerPassword` dance that kills the user name for jump server, but it's still capable of asking for certificate passwords (and unable to ask for user name in case it's missing).

**Comment by E1izabeth** [comment]
Wow! Thank you so much for your investigation.

**Comment by brother-z** [comment]
Well, my startup is using DBeaver a lot. We're on free version because of money constraints, so at least that's how I can contribute (assuming that I'm right about the cause, that is :).

**Comment by Matvey16** [comment]
@brother-z Hello. Can you check if this has been fixed in early access version? https://dbeaver.io/files/ea/

**Comment by brother-z** [comment]
Sorry, was out for a conference and couldn't test.
So the answer is: yes and no :).
 - Yes: it does fix the main problem reported in this issue - I can log in through jump server, using private keys, without key passphrases being stored in config - I get two popups asking for passphrase, the username propagates correctly, everything works fine.
 - No: if you remove username from server, or jump server config, the popup still asks only for certificate passphrase, so username remains blank, so in the end it defaults to OS user.

Maybe you could use the "user name and password" popup instead the "password only" one, then if the user is given in config it will be populated, otherwise you could fill it in. Or make the username field mandatory in config, that would also work :).

Not sure if you want to track the "blank user" problem here, or you want me to create another issue.

**Comment by E1izabeth** [comment]
@brother-z thank you for checking! Could you create a new issue?
