### ISSUE TITLE
Intersystems Caché not able to connect with recent Community releases

### ISSUE THREAD

**Issue by mikeho1218** [dbeaver/dbeaver#18015]
### Description

With the last two releases of the Community version, getting the following error:

Can't create driver instance
  Error creating driver 'Cache' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.intersys.jdbc.CacheDriver'
  Error creating driver 'Cache' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.intersys.jdbc.CacheDriver'
    com.intersys.jdbc.CacheDriver
    com.intersys.jdbc.CacheDriver

If I fall back to Community version 22.2.1 all connections work fine.

### DBeaver Version

Community 22.2.3

### Operating System

Windows 10 21H2

### Database and driver

InterSystems Cache JDBC
CacheDB.jar

### Steps to reproduce

1. Right click on connection and select Connect
2. Error connecting message.

**Comment by LonwoLonwo** [comment]
Hello @mikeho1218 

Thanks for the bug report.

As a workaround for now - you can add driver manualy:

![2022-10-28 00_10_13-DBeaver 22 2 3 - Invoice](https://user-images.githubusercontent.com/45152336/198398960-a61f3037-937f-4d12-91fe-64a988b345fe.png)

**Comment by LonwoLonwo** [comment]
Also, can you please check the newest driver version? https://github.com/intersystems-community/iris-driver-distribution/blob/main/JDBC/JDK11/intersystems-jdbc-3.2.0.jar

Is it compatible with the Iris Cache? I do not have a test environment to check it by myself. Thank you.

**Comment by Raptord** [comment]
@LonwoLonwo I tried your workaround with the driver you linked above, as I'm having the same issue with the Caché driver when updating to 22.2.2/22.2.3. The workaround gives me the same error as before:

![image](https://user-images.githubusercontent.com/2872199/198632294-cad80c31-7e7c-49f6-ac4e-81ea02b993fc.png)

![image](https://user-images.githubusercontent.com/2872199/198631842-3482ef30-86e7-4d3c-919e-55c7b2bbab96.png)

**Comment by mikeho1218** [comment]
@LonwoLonwo, I have the same result as @Raptord. The workaround does not work. I still have to fall back to 22.2.1

**Comment by LonwoLonwo** [comment]
So. People. If you know - when we can find the newest Iris Cache driver - please let us know.

**Comment by Raptord** [comment]
> So. People. If you know - when we can find the newest Iris Cache driver - please let us know.

@LonwoLonwo I found this github repo that seems to be maintained by IRIS with various versions of the Cache driver; is this what you were looking for?

https://github.com/intersystems-community/iris-driver-distribution

**Comment by LonwoLonwo** [comment]
https://github.com/intersystems-community/iris-driver-distribution/blob/main/JDBC/JDK11/intersystems-jdbc-3.2.0.jar does not work for me :( Does any driver from this repo work for you?
