### ISSUE TITLE
Database Navigator: remember _absolute_ width upon resizing

### ISSUE THREAD

**Issue by rumbin** [dbeaver/dbeaver#18022]
**Is your feature request related to a problem? Please describe.**

When working on displays with largely distinct horizontal resolution and switching between them, I always end up having to readjust the Database Navigator's side panel, as the width is stored as relative width of the window.

**Describe the solution you'd like**

As the DB/schema/table names always have the same lengths, regardless of the monitor resolution, I would suggest to keep the width of this side panel constant when resizing the window (for bigger/smaller/screens), in terms of horizontal pixels, set to the value that the user adjusted.

**Describe alternatives you've considered**

Maybe a compromise of both approaches would be useful: try to keep the side pane constant in size, but only up to a certain ratio when the window is getting smaller. So maybe it should not use up more than 50% of the horizontal resolution or so.

**Comment by E1izabeth** [comment]
I guess the customized perspective will fulfill your needs.
1. Add hotkey to `Save perspective as..` command
![image](https://user-images.githubusercontent.com/28875055/198330791-5e21ae66-52c4-4b13-a72a-dc64a889a8a1.png)
2. Write some name and save.
![image](https://user-images.githubusercontent.com/28875055/198331123-9fa877cf-f47c-4f9d-bbcb-43f1741de154.png)
3. Then you can switch between the default one and the custom one in the right top corner. Different perspectives has different layout.
![image](https://user-images.githubusercontent.com/28875055/198331591-5e227d72-6074-485b-b178-a0c0a563b558.png)

`Save perspective as..` command is missing in the menu now. So, we need to return it back to make it accessible through the menu not only via shortcut.

**Comment by E1izabeth** [comment]
Save perspective as.. command will be will be added to context menu in #17089
