### ISSUE TITLE
ssh tunnel attempts password auth when agent is selected

### ISSUE THREAD

**Issue by Spongman** [dbeaver/dbeaver#18020]
### Description

![image](https://user-images.githubusercontent.com/1088194/197671159-bafbbb8f-9363-49a0-a2ec-c04c50a49bf2.png)

after clicking 'test tunnel configuration' the connection to the jump host is correctly established. however, the sshd server on the host in the first text box shows this:

```
Oct 25 02:48:03 <hostname> sshd[13704]: Failed password for <user> from <jumphost> port 27992 ssh2
Oct 25 02:48:03 <hostname> sshd[13704]: Failed password for <user> from <jumphost> port 27992 ssh2
Oct 25 02:48:04 <hostname> sshd[13704]: Failed password for <user> from <jumphost> port 27992 ssh2
```

### DBeaver Version

 22.2.2.202210092258

### Operating System

windows 10 x64

### Database and driver

N/A

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by Matvey16** [comment]
Not reproducible anymore

**Comment by Spongman** [comment]
this definitely still reproduces. please reopen. Version 22.2.4.202211061524

**Comment by Spongman** [comment]
nope, i take it back. this does work. apologies....

**Comment by E1izabeth** [comment]
Thank you for your attention.
