### ISSUE TITLE
since latest update I'm getting many more key-pair authentication attempts per session

### ISSUE THREAD

**Issue by jtg567** [dbeaver/dbeaver#18037]
### Description

1. connect to Snowflake
2. receive push notification on phone to approve key-pair authentication (this was normal behavior prior to the latest update, but since then:)
3. receive 2nd push notification on phone to approve key-pair authentication (immediately after approving first one)
4. receive another push notification for each script I open in connection to the same Snowflake session

### DBeaver Version

Version 22.2.3.202210231354

### Operating System

macOS monterey 12.6

### Database and driver

Database name and version 6.18.2
Driver name Snowflake

### Steps to reproduce

1. connect to Snowflake
2. receive push notification on phone to approve key-pair authentication (this was normal behavior prior to the latest update, but since then:)
3. receive 2nd push notification on phone to approve key-pair authentication (immediately after approving first one)
4. receive another push notification for each script I open in connection to the same Snowflake session

**Comment by E1izabeth** [comment]
Could you show me screenshot of your preferences on the SQL Editor page in two places: Preferences->Editors->SQL Editor and Connection configuration->SQL Editor?

**Comment by jtg567** [comment]
Gladly, @E1izabeth -- ty for the response!

![image](https://user-images.githubusercontent.com/1797418/197881339-a70674af-2b90-47cc-bcff-8caeedcc2514.png)
![image](https://user-images.githubusercontent.com/1797418/197881490-25fc58db-3ad4-4323-be0c-cffd67e2b001.png)

**Comment by E1izabeth** [comment]
Please, check `Datasource "CHIPPER" settings` checkbox and set `Open separate connection for each editor` to `Never` in the Connection configuration->SQL Editor.
