### ISSUE TITLE
Building DBeaver with correct execution environment / JDK?

### ISSUE THREAD

**Issue by ar-jan** [dbeaver/dbeaver#18038]
### Description

For updating DBeaver on Void Linux I had to update the Java version from openjdk11, so I picked the latest available on Void, openjdk17. Now the build log is full of this type of warnings:

> [INFO] --- tycho-compiler-plugin:3.0.0:compile (default-compile) @ org.jkiss.dbeaver.ext.test ---
> [WARNING] Using JavaSE-17 to fulfill requested profile of JavaSE-11 this might lead to faulty dependency resolution, consider define a suitable JDK in the toolchains.xml

The build succeeds, but looking at this [Tycho issue](https://github.com/eclipse-tycho/tycho/issues/655), I think this shouldn't happen?

### DBeaver Version

Community Edition 22.2.3

### Operating System

Void Linux

### Database and driver

N/A

### Steps to reproduce

Build with `mvn package -P all-platforms` (as in the Void build [template](https://github.com/void-linux/void-packages/blob/master/srcpkgs/dbeaver/template)).

**Comment by iraidaa** [comment]
Hi @ar-jan,

Thank you for the report. We're aware of these warnings. We're working on it. 
At the same time, want to assure you that these warnings do not interfere with the DBeaver successful builds and stable work.
