### ISSUE TITLE
Update Db2 LUW JDBC driver to version v11.5.8.0

### ISSUE THREAD

**Issue by igor2x** [dbeaver/dbeaver#18036]
**Is your feature request related to a problem? Please describe.**
Previous week on day 2022-10-19 new Db2 JDBC driver v11.5.8.0 was released. New version of JDBC driver is released like ones per year. Interesting and long anticipating new feature is [support for TLS v1.3.](https://www.ibm.com/docs/en/db2/11.5?topic=1158-security-enhancements)

**Describe the solution you'd like**
Please update the latest Db2 v11.5.8.0 driver in DBeaver. You can download it from [IBM Db2 JDBC web page ](https://www.ibm.com/support/pages/db2-jdbc-driver-versions-and-downloads). On top of web page there is table _DB2 Version 11.5_ and inside that table is JDBC driver for **v11.5 M8 FP0** (this is actually v11.5.8.0) with official version **4.32.28.**

**Useful info**
If it helps, two weeks ago Db2 JDBC driver v11.5.7.0 was added in DBeaver for reference what should be changed in DBeaver source code: https://github.com/dbeaver/dbeaver/issues/17427

**Comment by E1izabeth** [comment]
Thank you for feature request.

**Comment by igor2x** [comment]
Can you please define a milestone for this feature request. It should be easy to add it following https://github.com/dbeaver/dbeaver/issues/17427 issue. It would be excellent it this could be added to DBeaver to the end of November when we are planning to upgrade TLS to v1.3 available only in the latest Db2 version.

**Comment by E1izabeth** [comment]
This issue is not planned for the current sprint, so the new driver version will not be set by default at the end of November.
But you can choose the version you need by your own:
![image](https://user-images.githubusercontent.com/28875055/200361872-74cb5152-dd02-4fb5-a804-91af2e036123.png)

**Comment by igor2x** [comment]
@E1izabeth, thanks for update. I didn't know I could select new version from "Version" column. Now I see bellow dialog there is info how Version column works, but most of the people will not "see" this info...

I just expect if there are multiple versions to download from to have dialog like this:
![image](https://user-images.githubusercontent.com/10895030/200491217-889e5880-5abf-487e-97df-e0a4b0a45c9b.png)
And blue selected line with the one that is going to be downloaded.
