### ISSUE TITLE
Checkbox 'Datasource settings' always disabled after DBeaver restart

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#18045]
### Description

Checkboxes 'Datasource settings' are always become disabled after DBeaver restart. But all of user's datasource settings are saved
![image](https://user-images.githubusercontent.com/43252954/197962134-21818824-1dde-4857-97bf-7d0a7f70be05.png)

### DBeaver Version

22.2.3

### Operating System

win10

### Steps to reproduce

1. for some connection enable datasource settings. 
2. Make some changes
3. Restart DBeaver
As the result settings are saved, but checkboxes are disabled

**Comment by E1izabeth** [comment]
I wasn't able to reproduce this issue on the latest Dbeaver version.

**Comment by Matvey16** [comment]
This is reproducible if connections settings are the same as global settings, which is a bug I think.
Case where it can be disrupting.
1. User checks the box to use exact settings for the connection
2. Restart DBeaver, change global settings
3. Global settings are applied to the connection

**Comment by E1izabeth** [comment]
We don't have a separate preference for this checkbox, so we don't save it. It's always unchecked, if all data source specific settings are the same with global once. We may save it, but it's controversial - there are a lot of unclear situations, for example, if some settings were changed, if the location (preference page) of some setting were changed, if setting presents on two preference pages at the same time.
