### ISSUE TITLE
when view influxDB table, the time is not correct

### ISSUE THREAD

**Issue by we684123** [dbeaver/dbeaver#18044]
### Description

![2022-10-26 09_16_44-DBeaver Ultimate 22 2 0 - server](https://user-images.githubusercontent.com/22027801/197919541-eb1b141e-b5e1-44b8-89d1-5fb6af4cf496.png)

in other DBviewer ,influxDB time is correct, this is day to write
but in DBeaver , timestamp confused

i guess is bc influxDB timestamp have 20 number , like 1666745661761833700 , so DBeaver can't treat
![2022-10-26 09_41_33-Unix Time Stamp - Epoch Converter — Mozilla Firefox](https://user-images.githubusercontent.com/22027801/197920013-ae5445a2-1338-47d0-be3c-aadb73b46f87.png)

### DBeaver Version

DBeaver Ultimate 22.2.0

### Operating System

win11

### Database and driver

1. influxDB 1.8.10
2. influxdb (DBeaver Ultimate default driver)

### Steps to reproduce

0. install python>3.5 , docker

1. `docker compose up`
docker-Compose.yml：
```docker compose
version: '3.9'

services:
  influxdb:
    image: influxdb:1.8.10
    container_name: test_influxdb-1.8.10
    volumes:
      - ./Docker_link:/var/Docker_link
      - ./Docker_link/influxdb:/var/lib/influxdb
    ports:
      - 18086:8086
```

2. `pip install --upgrade influxdb`

3. `python reshow_db_time_error.py`
reshow_db_time_error.py ：
```python
from random import random

from influxdb import InfluxDBClient

print('linking influxDB')

influxDB = InfluxDBClient(
    host='127.0.0.1',
    port=18086,
    username='uuu',
    password='xxx',
    database='ex'
)
if {'name': 'ex'} not in influxDB.get_list_database():
    influxDB.create_database('ex')
assert influxDB.ping() == '1.8.10'

print('linked influxDB')

for i in range(10):
    data = {"id_1_A": random() * 10, "id_1_B": random() * 10}
    list_body = [
        {
            "measurement": 'server',
            "fields": data
        }
    ]
    influxDB.write_points(list_body)

print('influxDB.write_points done')
```

4. use DBeaver Ultimate 22.2.0 link influxDB
host: `127.0.0.1`
port: `18086`
dadtbase: `ex`
username: `uuu`
possword: `xxx`

5. get error Timestamp (today is 2022/10/26)
btw , my time format is `yyyy-MM-dd HH:mm:ss.SSS`
![2022-10-26 10_41_54-DBeaver Ultimate 22 2 0 - server](https://user-images.githubusercontent.com/22027801/197921959-2a29faf6-aa81-471c-92f5-4daf9a6dc495.png)

**Comment by flambchap** [comment]
Hi @we684123. Could you please tell me if you have an active commercial license?

**Comment by we684123** [comment]
@n5a5 hmmm... I have an active "LIMITED License", is it "commercial license"？

**Comment by flambchap** [comment]
Yes. Please open a ticket on our support system on our website, we'll gladly help.

**Comment by we684123** [comment]
@n5a5 
i open the ticket (#184809) , Thank you very much for your willingness to help!
