### ISSUE TITLE
Failed to export CockroachDB table

### ISSUE THREAD

**Issue by rafaelmembrives** [dbeaver/dbeaver#18056]
### Description

Exporting data from a Cockroach DB table fails with the next error:

![image](https://user-images.githubusercontent.com/4113578/198279817-a4c444fe-585c-4628-884c-38125d399197.png)

### DBeaver Version

Community Edition 22.2.3

### Operating System

macOs Monterey 12.6

### Database and driver

1. CockroachDB CCL v22.1.3 (x86_64-pc-linux-gnu, built 2022/07/11 14:04:38, go1.17.11)
2. PostgreSQL JDBC Driver 42.5.0

### Steps to reproduce

1. Select a table from a Cockroach DB in the Database Navigator view.
2. Select Export Data option.
3. Select SQL format (other format fails as well)
4. Press Next button three times and Process button.

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by rafaelmembrives** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/9879746/dbeaver-debug.log)

I attached the debug log. Thanks in advance.

**Comment by LonwoLonwo** [comment]
What commit mode do you have @rafaelmembrives ?

If it is not auto-commit mode - can you please try to use it and check the result?

**Comment by rafaelmembrives** [comment]
Same result with auto-commit and manual.

**Comment by LonwoLonwo** [comment]
Ok. Can you provide please a screen of your datatransfer settings?

![2022-10-28 12_24_43-AnyDesk](https://user-images.githubusercontent.com/45152336/198553979-e88452f4-909c-4c37-b840-864a7020fe54.png)

**Comment by LonwoLonwo** [comment]
Also, can you please check other PostgreSQL driver versions? Older versions.

You can cahnge it in the connection settings - driver settings

![2022-10-28 12_28_12-DBeaver 22 2 3 - Invoice](https://user-images.githubusercontent.com/45152336/198554731-9763edb5-264c-41a2-890c-1f3f1e0b3f12.png)

**Comment by rafaelmembrives** [comment]
Sorry for the late reply. I tried with severals PostgreSQL driver versions and all fails with the same error message. 

My export settings:

![image](https://user-images.githubusercontent.com/4113578/199488097-c16631ab-0cd7-4247-bbb1-28360dd6fda6.png)

**Comment by rafaelmembrives** [comment]
It seems an error related to the version of the database, I have tried with another Cockroach DB version 22.1.8 and 22.1.9  and the table is exported correctly.

**Comment by LonwoLonwo** [comment]
> It seems an error related to the version of the database, I have tried with another Cockroach DB version 22.1.8 and 22.1.9 and the table is exported correctly.

Ok. Very interesting.
So what can we do from DBeaver's side?

**Comment by rafaelmembrives** [comment]
I close the issue, I really appreciate you helping me.

**Comment by LonwoLonwo** [comment]
Thanks for the investigation @rafaelmembrives
