### ISSUE TITLE
Execute query without comments above

### ISSUE THREAD

**Issue by archongum** [dbeaver/dbeaver#18052]
**Is your feature request related to a problem? Please describe.**
Without useless-additional comments, make it easier for Database audit logging.

**Describe the solution you'd like**
There is a switch for execute query by removing or ignoring comments.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/20929338/198183840-1e16fcb5-a625-47d4-8710-70cbc635b8ea.png)

**Comment by E1izabeth** [comment]
You can select the whole query and press Execute. Then DBeaver will send the selected part of text to the database.
![image](https://user-images.githubusercontent.com/28875055/198257372-57812ba4-206d-4284-a1be-32157d4bc4ba.png)


Another option is to add a blank line between comment and the query and turn `Blank line is a statement delimiter `option on.
![image](https://user-images.githubusercontent.com/28875055/198256803-258101d6-b385-4ac0-b2f7-a3b2d0f97855.png)
![image](https://user-images.githubusercontent.com/28875055/198257530-b1766efa-af9d-4387-a6bf-95bcf8e12bc9.png)

**Comment by archongum** [comment]
merci beaucoup
