### ISSUE TITLE
Issue during installation-Installation is not reflecting in all winodows user

### ISSUE THREAD

**Issue by neerajkumar86** [dbeaver/dbeaver#18055]
### Description

Hi All,

Can Someone help me here ..?

I have installed the Dbeaver using the admin account for all the users. but when u checked it is not showing in the Start Menu and Icon on the Desktop of other users of windows.

Although, when I go into the program files and run the application from there it is working for other users also this will be more time-consuming if I need to guide all to run in this way to all my team members.

So can you please suggest if am I doing something wrong during the installation or what could be the problem due to this it is not being properly reflected by other windows users?

A quick response will be appreciable. 

### DBeaver Version

Dbeaver Version 7.1.0.202005311732

### Operating System

Winodws Server 2016 Standard

### Database and driver

Netezza Database Driver

### Steps to reproduce

Normal Installation process on windows using exe file.

### Additional context

None

**Comment by flambchap** [comment]
Hi, @neerajkumar86. Unfortunately, I cannot reproduce the issue against the latest version. Can you please check the newest version to see if the issue is gone there?

**Comment by neerajkumar86** [comment]
ok..I will try and update you.

**Comment by neerajkumar86** [comment]
Thank you
