### ISSUE TITLE
Oracle Driver Broken and not possible to fix since V22.2.3

### ISSUE THREAD

**Issue by dnroldanforwork** [dbeaver/dbeaver#18054]
### Description

When I opened first time Dbeaver V22.2.3 I got an driver error when I tried to connect to Oracle Database.
The error popup shows the next messages:

Can't create driver instance
  Error during driver instantiation
  Error during driver instantiation
    java.sql.Driver.<init>()
    java.sql.Driver.<init>()

The driver box has otrher name and when I try to download again the drivers is not possible because I can't control the popup where you download the drivers from repossitory.

I tried on V22.2.2 and with this version there is no problem.

Please tell me if you need more information.
Thanks

### DBeaver Version

Community Edition 22.2.3

### Operating System

Windows 10

### Database and driver

Oracle
Oracle Driver 21.1.0.0

### Steps to reproduce

Try to connect to existing database

### Additional context

Only Office Extension

**Comment by dnroldanforwork** [comment]
![Dbeaver_2223_driver_error](https://user-images.githubusercontent.com/116801489/198253870-c9f2030f-f491-4fcc-91dc-1d288b3b7fbb.png)

**Comment by dnroldanforwork** [comment]
It's not possible to get focus on "Download driver files Window", it's neccesary to close every other window.
Thanks in advance.

**Comment by E1izabeth** [comment]
@dnroldanforwork did you manage to connect to Oracle after drivers download?

**Comment by E1izabeth** [comment]
We have already fixed the issue about Download driver files dialog in #17892. The fix will be available in the next release.
Thank you for bug report.

**Comment by dnroldanforwork** [comment]
> @dnroldanforwork did you manage to connect to Oracle after drivers download?

Yes, but when I close and open Dbeaver later I need to download again.

**Comment by dnroldanforwork** [comment]
> We have already fixed the issue about Download driver files dialog in #17892. The fix will be available in the next release. Thank you for bug report.

Ok, thanks so much

**Comment by E1izabeth** [comment]
Do you use VPN or some specific network configuration?

**Comment by E1izabeth** [comment]
Maybe connected with #16718

**Comment by dnroldanforwork** [comment]
> Do you use VPN or some specific network configuration?

No...

**Comment by dnroldanforwork** [comment]
> Maybe connected with #16718

But for me only occurs since 22.2.3, I always update every version you launch by this reason.
Now I am working with 22.2.2 and I haven't any problem.

**Comment by E1izabeth** [comment]
Could you reproduce it again and send the log files? You can find instructions here https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by dnroldanforwork** [comment]
> Could you reproduce it again and send the log files? You can find instructions here https://github.com/dbeaver/dbeaver/wiki/Log-files

Good Morning,

I attached the log.

Thanks.
[Dbeaver_log.log](https://github.com/dbeaver/dbeaver/files/9885641/Dbeaver_log.log)

**Comment by E1izabeth** [comment]
Thank you.

**Comment by dnroldanforwork** [comment]
Good morning,

One problem persists with V 22.2.4 and other was fixed.

Now, I can select the download driver Window and I can configure and download the driver correctly but if I close Dbeaver and reopen, it's open an error Windows telling me that configure the driver again.

Please, tell me if you need more information or upload logs again.

Thanks in advance.

**Comment by uslss** [comment]
@dnroldanforwork seems this new issue will be fixed in the scope of #18122 .
Thanks for checking and reporting.
close this ticket as resolved.
