### ISSUE TITLE
Simple Structure Compare requiring pgagent.pga_job

### ISSUE THREAD

**Issue by anazzani** [dbeaver/dbeaver#18066]
### Description

Hi all.

I'm using DBeaver v22.2.3.202210231354 with a remote PostgreSQL db v12.5.

I remember using in the past the very handy compare feature (with the same db, not sure which DBeaver version though) but today it fails with the message:

Can't access pgAgent jobs.
This database may not have the extension installed or you don't have sufficient permissions to access them.
If you believe that this is DBeaver's fault, please report it.
Reason:
SQL Error [42P01]: ERROR: relation "pgagent.pga_job" does not exist
  Position: 15

Is this intended?

### DBeaver Version

Community Edition 22.2.3

### Operating System

macOS Monterey 12.6.1

### Database and driver

PostgreSQL db v12.5

**Comment by LonwoLonwo** [comment]
Hello @anazzani 

Can you please provide some video or gif of your issue? I can't reproduce your issue for now.

**Comment by LonwoLonwo** [comment]
Related: https://github.com/dbeaver/dbeaver/issues/17119

**Comment by anazzani** [comment]
Hi @LonwoLonwo 

I have recorded my screen but I cannot attach it here cause it's too big.

Should be available [here](https://s3-eu-west-1.amazonaws.com/pluridoc/demo.pluridoc.it/transfers/37/Screen%20Recording%202022-11-03%20at%2011.09.59.mov).

**Comment by LonwoLonwo** [comment]
Oh. Ok. I see. You want to compare datasources...
Any specific reason for this? Do you need to administer info in your result?

![2022-11-03 14_55_40-DBeaver Ultimate 22 2 3 - _Azure Databricks_ Script-205](https://user-images.githubusercontent.com/45152336/199714540-9c7a493d-17cd-4539-8855-a004e57659f8.png)

Maybe you can compare only databases as a workaround?

**Comment by anazzani** [comment]
Apologies, Postgres and DBEaver newbie here.

Comparing databases is what I was looking for, and I confirm it works as expected.

I confess the whole "connection" vs "database" vs "schema" thing is still confusing me: I wish there was a way to streamline my workflow through a "simplified" UI/UX showing only schemas (I'm a developer, not a DBA), but I'm going off topic I guess.

Thanks for your time.

**Comment by LonwoLonwo** [comment]
You can try to use the "Simple" navigator view

![2022-11-03 20_01_26-DBeaver Ultimate 22 2 3 - _Azure Databricks_ Script-205](https://user-images.githubusercontent.com/45152336/199786978-b51a654a-74aa-4a94-b8f4-cce4e297f06e.png)

Or customize it as you wish :)

**Comment by anazzani** [comment]
Thanks for your reply.

I already tried the "simple" connection view, but I find it overly simplified for my every day usage (for example opening a table doesn't show constraint, indexes, triggers, etc.).

I just had a look at the custom view, but I'm not sure how to simplify object navigation while still getting all the details I need from the advanced view.

It's no big deal anyway, just a few extra clicks, but still... :)
