### ISSUE TITLE
Installed a new version of Dbeaver and am getting a Java.net.ssl.SSLHandshakeException:PKICK error on startup

### ISSUE THREAD

**Issue by msprewitt** [dbeaver/dbeaver#18062]
### Description

Installed a new version of Dbeaver and am getting a Java.net.ssl.SSLHandshakeException:PKICK error on startup

![Screen Shot 2022-10-27 at 4 02 32 PM](https://user-images.githubusercontent.com/33008504/198406617-2603aca7-e832-4edb-8852-eb73a8fc21a3.png)
![Screen Shot 2022-10-27 at 4 03 39 PM](https://user-images.githubusercontent.com/33008504/198406759-13fddfa2-7b75-48e5-bf68-fd01cf00da6d.png)

### DBeaver Version

Community Edition: Version 22.2.3.202210231354

### Operating System

macOS 12.6 (21G115) Monterey

### Steps to reproduce

1. Start Dbeaver
2. Try to connect to test database

### Additional context

No additional context...

**Comment by E1izabeth** [comment]
Please, try using this guide to fix it https://dbeaver.com/docs/wiki/Importing-CA-Certificates-into-DBeaver/
Does it help?

**Comment by msprewitt** [comment]
I copied the carets file from the Java library...
Here is the copy command and the pwd I copied from...


![Screen Shot 2022-10-27 at 4 27 42 PM](https://user-images.githubusercontent.com/33008504/198410114-3f1acfe0-363c-4f6f-83df-8a0cd30dd97f.png)

After restarting up Dbeaver, got the same error trying to connect the test-database

**Comment by Destrolaric** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by msprewitt** [comment]
Here is what I found:

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/9890073/dbeaver-debug.log)

[dot.log](https://github.com/dbeaver/dbeaver/files/9890104/dot.log)

**Comment by Destrolaric** [comment]
@msprewitt Do you have any kind of firewall? It looks like DBeaver can't download the SQLite driver from maven.

**Comment by msprewitt** [comment]
No..  On a window's computer, I was able to install DBeaver and connect with the Postgres database..  But when trying to download the drivers with my Mac.. Things are just not working right...  I sense that my credentials are screwed up.. but this is a little out of my knowledge-base... *SIGH*

**Comment by msprewitt** [comment]
Was a firewall issue after all..  Got things working and think I can close this ticket.. [Destrolaric](https://github.com/Destrolaric) and [E1izabeth](https://github.com/E1izabeth) thank you for your help!!!

**Comment by E1izabeth** [comment]
Thank you for informing us.
