### ISSUE TITLE
Can not import data CSV 15GB

### ISSUE THREAD

**Issue by tfirmansyah** [dbeaver/dbeaver#18074]
### Description

Hi,

I try to import .csv  7GB -15 GB to postgres , but always fail, i try to increase xmx to be 10000 but still fail.
i keep increasing to be higher and higher...but i don't know whether this is how to fix it permanently for very big data of csv ? is there any permanent solution for this?

### DBeaver Version

enterprise 22.2.0

### Operating System

Windows 10 enterprise, RAM 32GB

### Database and driver

PG admin 4

### Steps to reproduce

i try to upload file in csv format with size of file 7GB until 15 GB, and suddenly dbeaver hang and close by it self

### Additional context

no

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by LonwoLonwo** [comment]
Additionally, did you try to use performance datatransfer settings? 

![2022-11-23 22_47_56-Data Transfer](https://user-images.githubusercontent.com/45152336/203634219-52fff50a-94f7-4d1c-b229-c2dab62a69a1.png)

Bulk load or multi-insert can increase loading performance dramatically.

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
