### ISSUE TITLE
FirebirdSQL connection refused

### ISSUE THREAD

**Issue by frafor** [dbeaver/dbeaver#18075]
### Description

Unable to complete network request to host "127.0.0.1". [SQLState:08006, ISC error code:335544721]
  Connection refused: connect
  Connection refused: connect

### DBeaver Version

community V 22.2.0.202209080956

### Operating System

Windows 11 talking to WSL2 Ubuntu 20.4 same machine

### Database and driver

org.firebirdsql.jdbc.FBDriver

jdbc:firebirdsql://127.0.0.1:3050/devel5 (conn string)

### Steps to reproduce

1. After setting up driver and dbeaver I try to connect
2. I get this all the time:
Unable to complete network request to host "127.0.0.1". [SQLState:08006, ISC error code:335544721]
  Connection refused: connect
  Connection refused: connect
3. It is possible to connect using IBExpert and using PHP with Apache2 running in the WSL2 Ubuntu 20.4

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual - feel free to reopen it with additional info.
