### ISSUE TITLE
SQL Server: max rows works incorrectly

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#18071]
### Description

We use setMaxRows for all SELECT statements.
SQL Server driver (old and new ones) uses  SET ROWCOUNT. Which affects all SELECT-like queries. Including INSERT FROM SELECT which can be executed in referenced stored procedures.
If we not use setMaxRows then we use TOP X to limit fetch size. This leads to the same result.

Maybe we should disable setMaxRows execution for SQL Server (and Sybase).

Possible soltion: disable query limit default.

### DBeaver Version

22.2

### Operating System

Any

### Database and driver

- SQ LServer
- Azure
- Sybase

**Comment by LonwoLonwo** [comment]
https://github.com/microsoft/mssql-jdbc/issues/176 interesting discussion
