### ISSUE TITLE
Postgresql 15 connection with scram-sha-256 encryption

### ISSUE THREAD

**Issue by Softsuit** [dbeaver/dbeaver#18085]
### Description

Using the standard Postgresql 15 setup with scram-sha-256 encryption does not work.  All workarounds lead to lowering security on your database to md5.

### DBeaver Version

CE 22.2.3

### Operating System

Win10 Pro 

### Database and driver

Postgresql 15
JDBC postgresql-42.5.0.jar

### Steps to reproduce

1.  Setup a profile to connect to the database using the standard postgresql driver
2.  use the test button to connect
3. --> error that this not supported

### Additional context

Simple LAN setup, both machines are in the same subnet and have a fixed IP address.

**Comment by LonwoLonwo** [comment]
Hello @Softsuit 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by LonwoLonwo** [comment]
Also, are you sure that issue is from DBeaver's side? 
I found some discussion on the internet: https://stackoverflow.com/questions/64316324/i-tried-to-change-postgresql-md5-to-scram-sha-256-and-i-get-fatal-password-authe.
Did you make all the necessary changes in your config files?

**Comment by Softsuit** [comment]
Hi,

 

Scrolling down up tot he message

 

!MESSAGE SCRAM authentication is not supported by this driver

 

This is the essential problem.  I have a clean install of postgresql15, no databases except fort he postgresql system database, nu users except fort he postgres user, which I set a pasword which was by default in scram-sha-256.  Then I got this error.  So I upgraded tot the version of postgresql JDBC driver, but that did not help.  Only going back to a full md5 setup user password, pg_hba.conf file and all that I got it working again.

 

So that made me conclude that dbeaver was not yet compliant tot he scram-sha-256 authentication.  

 

m.vr.groet,

Pascal

**Comment by LonwoLonwo** [comment]
Could you please provide a full log file? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.

**Comment by uslss** [comment]
There have been no updates for a long. If issue is still actual for you - feel free to reopen it with additional info

**Comment by mboeringa** [comment]
I ran into the same issue of being unable to connect on a fresh PG15 install with scram-sha-256 correctly set (pgAdmin was able to connect). 

It appears DBeaver (in my case v23.0.5) ships with an outdated driver. 

Following the steps to update the drivers used by DBeaver, via the UI of DBeaver itself, as described in this StackOverflow post solved my issue:

https://stackoverflow.com/a/64546286/21113080

**Comment by vgjenks** [comment]
> I ran into the same issue of being unable to connect on a fresh PG15 install with scram-sha-256 correctly set (pgAdmin was able to connect).
> 
> It appears DBeaver (in my case v23.0.5) ships with an outdated driver.
> 
> Following the steps to update the drivers used by DBeaver, via the UI of DBeaver itself, as described in this StackOverflow post solved my issue:
> 
> https://stackoverflow.com/a/64546286/21113080

I went down this rabbit hole, also - no luck. In latest dbeaver w/ latest driver, using the `postgres` user and the correct password, I always get: `FATAL: password authentication failed for user "postgres"`

Following the stack instructions above, it *looks* like it downloads something, but I still can't connect. I don't see any options to select "SCRAM" for authentication, anywhere. This is a frustrating mess. Hours of searching to get to the very start of the entire process.

I can, of course, hop right into to the container as `postgres` user and use psql, no problem.

**Comment by mboeringa** [comment]
> I can, of course, hop right into to the container as `postgres` user and use psql, no problem.

@vgjenks, have you actually properly configured your 'postgresql.conf' to set the listen addresses for machine running DBeaver, and 'pg_hba.conf' to set the associated authentication? Also check firewall settings.

If anything down those lines isn't properly configured, you could easily be blocking yourself and access by DBeaver, but I know for sure I have these things properly configured, if you are building some new setup, this may be different.

I had no problems after updating the drivers based on the StackExchange issue link, it worked right away.

**Comment by mboeringa** [comment]
> I went down this rabbit hole, also - no luck. In latest dbeaver w/ latest driver, using the `postgres` user and the correct password, I always get: `FATAL: password authentication failed for user "postgres"`

Have you set:

`local all postgres scram-sha-256`

in the 'pg_hba.conf'? It defaults to

`local all postgres peer`

which will cause issues if you try to connect in my experience with PG15 and SCRAM set.

**Comment by vgjenks** [comment]
@mboeringa I'm running it in docker and never needed to tweak the .conf file directly before. I spent the last two years in pg 13.3 and all was fine. Will I now need to manually configure and map the conf via the docker command, to connect? No firewall. I just tried pgadmin4 as well, and I get the same error.

**Comment by mboeringa** [comment]
@vgjenks, see my last remark https://github.com/dbeaver/dbeaver/issues/18085#issuecomment-1574214191

**Comment by vgjenks** [comment]
@mboeringa Sorry...timing. :)

Here's everything in my hba conf. Should I change that first option, or does the last line actually do the same?

```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust

host all all all scram-sha-256
```

**Comment by vgjenks** [comment]
> @vgjenks, see my last remark [#18085 (comment)](https://github.com/dbeaver/dbeaver/issues/18085#issuecomment-1574214191)

Sorry, timing. :)

I changed the last line in the hba conf to match and it worked. Thanks! I may write something up that's a little more coherent, to help others. Much appreciated.

**Comment by mboeringa** [comment]
@vgjenks , in my 'pg_hba.conf', I have set _**every**_ line to 'scram-sha-256'. This seems to work so far, and I can connect as postgres user in pgAdmin. For DBeaver, I never connect as postgres user, but I am now also connecting using 'scram-sha-256' after the driver update.

You will need to restart the server process as well after making changes:

`sudo service postgresql restart`

**Comment by mboeringa** [comment]
> I changed the last line in the hba conf to match and it worked. Thanks! I may write something up that's a little more coherent, to help others. Much appreciated.

Maybe change the "down vote" to "up vote" then, because you will still also need to update the driver used by DBeaver ;-)
