### ISSUE TITLE
Can't copy date time value in Oracle

### ISSUE THREAD

**Issue by leezm** [dbeaver/dbeaver#18084]
### Description

When column type is date in Oracle,can't copy date time value in Oracle.It's can only copy date part,time part can't copy.

### DBeaver Version

22.2.3

### Operating System

win11

### Database and driver

oracle19C

### Steps to reproduce

When column type is date in Oracle,can't copy date time value in Oracle.It's can only copy date part,time part can't copy.

**Comment by E1izabeth** [comment]
Please, provide minimal example to reproduce. The video showing the issue would be useful.

**Comment by leezm** [comment]
> Please, provide minimal example to reproduce. The video showing the issue would be useful.

OK.In this pic,I use "SELECT sysdate from dual;" to get sys date,the return value is date type in oracle.it's have time part,but looks like it;s only have yyyy-mm-dd part.When I  double-click this value,It's have edit controls......I copy this value but only have "yyyy-mm-dd" format.
![image](https://user-images.githubusercontent.com/24444492/198908616-f7ed3fcc-379c-43cb-842f-ecddfe669cd3.png)
In mssql,I use "SELECT getdate();" to get sys date.In this pic,then return value is datetime......
![image](https://user-images.githubusercontent.com/24444492/198908655-e045f52d-bd0f-47d1-939d-427fe3b5cdab.png)

My Suggestion：
1.show real date format like previous version and can copy real value
2.date edit controls make it can,t be direct edit......pls optimize it make it can both control editing and direct editing

**Comment by LonwoLonwo** [comment]
Hello @leezm 

It works fine for me with the SYSTIMESTAMP

![2022-10-31 09_16_57-AnyDesk](https://user-images.githubusercontent.com/45152336/198943775-0f8c9e10-52e4-4859-af08-f0a7639d5b88.png)

We fixed date/timestamp representation for Oracle in the last DBeaver version in this ticket: #8673

**Comment by leezm** [comment]
> Hello @leezm
> 
> It works fine for me with the SYSTIMESTAMP
> 
> ![2022-10-31 09_16_57-AnyDesk](https://user-images.githubusercontent.com/45152336/198943775-0f8c9e10-52e4-4859-af08-f0a7639d5b88.png)
> 
> We fixed date/timestamp representation for Oracle in the last DBeaver version in this ticket: #8673

fine...but to ensure compatibility,we use "date" type to record datetime.In previous versions it was fine,fix and optimize it plz!

**Comment by steindlmedia** [comment]
I have the same problem with macOS and the most recent DBeaver version (22.2.3.202210231354).

DBeaver no longer shows the time for columns with type "DATE" of Oracle databases.
I have to use TOAD in order to see + edit the time component in the result set.

See below a comparison between the result set shown in DBeaver and TOAD.

![Bildschirm­foto 2022-11-03 um 10 54 15](https://user-images.githubusercontent.com/11992137/199691682-3afec75c-bee2-4c21-9965-8f31f8be8cc0.png)
![Bildschirm­foto 2022-11-03 um 10 54 37](https://user-images.githubusercontent.com/11992137/199691676-07481d0c-ad13-4feb-8add-7055ec9a5a39.png)

**Comment by LonwoLonwo** [comment]
As a workaround you can try to change the data view in the Preferences -> Editors -> Data Editor -> Data Formats

You can change the pattern for the date or try to enable "disable date/time formatting"

![2022-11-03 12_58_41-DBeaver Ultimate 22 2 3 - _Azure Databricks_ Script-205](https://user-images.githubusercontent.com/45152336/199692755-fc257f80-9f94-4460-95f4-62be44c36c24.png)

**Comment by steindlmedia** [comment]
Thanks, @LonwoLonwo. That fixed it. 😄

**Comment by leezm** [comment]
> As a workaround you can try to change the data view in the Preferences -> Editors -> Data Editor -> Data Formats
> 
> You can change the pattern for the date or try to enable "disable date/time formatting"
> 
> ![2022-11-03 12_58_41-DBeaver Ultimate 22 2 3 - Azure Databricks Script-205](https://user-images.githubusercontent.com/45152336/199692755-fc257f80-9f94-4460-95f4-62be44c36c24.png)

👍
