### ISSUE TITLE
Generate report from selected rows/columns of the Resutlset

### ISSUE THREAD

**Issue by geuss** [dbeaver/dbeaver#1808]
Hi,
this is only a new feature request.... Could be very useful generate a HTML table (in clipboard) of the selected rows/fields selected in the Result View.

Thanks, and good work!!!!

**Comment by efradkin** [comment]
![image](https://user-images.githubusercontent.com/16664546/34364960-38c65946-ea9c-11e7-8ea4-1e266dc23ed3.png)
Now you can set the wizard to export the selected columns/rows only.
