### ISSUE TITLE
Spatial viewer should support labels on map

### ISSUE THREAD

**Issue by PeterBrodersen** [dbeaver/dbeaver#18094]
**Is your feature request related to a problem? Please describe.**
The spatial viewer is nice, however just showing the geometry when viewing all data for a table and selecting the Spatial tab might not help getting an overview of the corresponding data.

**Describe the solution you'd like**
I would like an option of labels next to the geometry showed on the map, e.g. by selecting a corresponding column or even an expression to combine more fields.

**Describe alternatives you've considered**
It doesn't look like it's possible to customize the geometry output at all (besides different columns use different colours)

**Additional context**
Quick mock-up of desired result from the spatial view:

![image](https://user-images.githubusercontent.com/31605591/199212051-64bec520-b87e-4c2e-88af-e2fd23435d5b.png)

**Comment by ShadelessFox** [comment]
Thanks for the feature request

**Comment by mkgrgis** [comment]
This look like JavaScript level task based on `leaflet.js`. But where from should be the labels? From current column first? From active columns combination? From `name` property if no active columns?

**Comment by PeterBrodersen** [comment]
> This look like JavaScript level task based on `leaflet.js`. But where from should be the labels? From current column first? From active columns combination? From `name` property if no active columns?

Anything would do. It would be nice to have a column selector or even an expression field to combine more fields.

If a default column should be used my suggestion for priority would be something along the lines of:

1. Selected column(s) if any
2. First column called "name", "title" or any obvious labels (perhaps across different languages)
3. First string type column
4. First scalar type column
5. First column
