### ISSUE TITLE
Add Filter in the Connection level

### ISSUE THREAD

**Issue by fa5fou5** [dbeaver/dbeaver#18097]
**Is your feature request related to a problem? Please describe.**
I want a filter to be added in the connections level not only in the Table level to filter out the databases not needed to be shown.
And then, in the script file, the database the databases filtered out should not be suggested once we hit Ctrl + Space

**Comment by iraidaa** [comment]
Hi @fa5fou5,

You can already add filters. Please check these articles https://github.com/dbeaver/dbeaver/wiki/Filter-Database-Objects, https://github.com/dbeaver/dbeaver/wiki/Configure-Filters.
