### ISSUE TITLE
Athena driver return same message regardless of error

### ISSUE THREAD

**Issue by t7zhang** [dbeaver/dbeaver#18090]
### Description

I recently updated my DBeaver / driver for Athena. Since the last update, all error message that I receive has been 
"SQL Error [HY000]: Error message not found: ATHENA_CLIENT_ERROR. Can't find bundle for base name com.simba.athena.athena.jdbc42.messages, locale en_CA"
This is universal to the type of error. My script is able to run properly if there is no error. 

![image](https://user-images.githubusercontent.com/73551342/199098827-30fba57d-7b64-4162-8223-c478ba4b1410.png)

### DBeaver Version

Community Edition Version 22.2.3.202210231354

### Operating System

MacOS MOnterey version 12.4

### Database and driver

Amazon Athena
![image](https://user-images.githubusercontent.com/73551342/199099440-99458614-db7c-46bd-a4f1-644da3685a98.png)

**Comment by E1izabeth** [comment]
It looks like a JDBC driver issue. We updated Athena driver version recently. Could you download the previous driver version and check https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.31.1000/AthenaJDBC42.jar. You can replace it in the Edit driver->Libraries.

Please, let me know whether it help.

**Comment by gdcur** [comment]
It happened to me to have the same issue with version "Version 22.2.4.202211062135 Nov 7th, 2022" on Windows 10 working on Athena.
The driver replacement with the old version worked for me.
Thank you Elizabeth.

**Comment by E1izabeth** [comment]
Thank you for replying.

**Comment by MohitMannaMAF** [comment]
I got similar error. Only difference I am using this class com.simba.athena.amazonaws.auth.DefaultAWSCredentialsProviderChain

**Comment by angelchen1030** [comment]
Hi @E1izabeth ,

Sorry, after downloading the previous driver version (https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.31.1000/AthenaJDBC42.jar), where could I find this  'edit driver->Libraries'? Thank you.

**Comment by E1izabeth** [comment]
@angelchen1030 
for example, here
![image](https://user-images.githubusercontent.com/28875055/204778231-df32c4d1-bdbd-4928-9a66-c1a5fe50cd67.png)

**Comment by angelchen1030** [comment]
Okk, I found it, thank you!
I just added the file I download from this link  (https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.31.1000/AthenaJDBC42.jar), is that correct?


![driver](https://user-images.githubusercontent.com/60818869/204942897-2d3ae1d1-c1f9-4ad8-bcb4-deaaf3208775.png)

**Comment by E1izabeth** [comment]
@angelchen1030 also please remove previous driver of 22.0.32 version using `Delete` button here,

**Comment by angelchen1030** [comment]
@E1izabeth  It works! Thank you so much

**Comment by HAZET** [comment]
Works with the old driver. Thank you!
Question is: will this be fixed in newer drivers or is the behaviour intentional?

**Comment by E1izabeth** [comment]
It looks like athena driver bug. Could you try [22.0.34](https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.34.1000/AthenaJDBC42-2.0.34.1000.jar) athena driver version (download link also could be found here https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html)? Has this bug been already fixed in the latest version?

**Comment by HAZET** [comment]
After first tests I believe 22.0.34 displays the same behaviour

**Comment by E1izabeth** [comment]
Thank you, @HAZET

**Comment by HAZET** [comment]
Have to revise my statement above. I tested again with 22.0.34 and this time it worked, the issue was gone. Would be nice if somebody else could test and confirm. I am apparently not reliable, sorry. :(

**Comment by LonwoLonwo** [comment]
Athena driver upgraded.
Fix will be available [here](https://dbeaver.io/) on 2022-12-26 in DBeaver 22.3.1

**Comment by b-gale** [comment]
@LonwoLonwo  Thank you for nice Xmas present :).
