### ISSUE TITLE
DriverManager focus problem

### ISSUE THREAD

**Issue by tolgaong** [dbeaver/dbeaver#18093]
### Description

 I couldn't select anything in "Download driver files" menu. Unless I close the previous opened forms. (Driver manager, Edit driver '<Anything>'). 

### DBeaver Version

Community Edition 22.2.3.202210231354

### Operating System

Windows 10

### Steps to reproduce

1. Click Driver manager 
2. Double click to Sqlite (it doesn't matter)
3.  Select the Libraries tab 
4. Click download/Update

**Comment by E1izabeth** [comment]
We have already fixed the issue about Download driver files dialog in https://github.com/dbeaver/dbeaver/issues/17892. The fix will be available in the next release.
Thank you for bug report.
