### ISSUE TITLE
Results viewer: Refresh after connection lost has to be hit twice

### ISSUE THREAD

**Issue by Otiel** [dbeaver/dbeaver#1810]
When viewing some data, if the connection has been lost and I hit "refresh" (or <kbd>F5</kbd>), I am offered to reconnect:

![image](https://user-images.githubusercontent.com/3851902/27480107-f6fda0e0-5816-11e7-8e65-941c6983c30a.png)

That's all good. After I hit "Reconnect", the connection to the database is restored but the refresh action I originally asked for isn't made. I have to hit "refresh"  (or <kbd>F5</kbd>) one more time.

Could you call again the refresh automatically?

**Comment by Otiel** [comment]
Any love for this bug? :)

**Comment by uslss** [comment]
already implemented
![image](https://user-images.githubusercontent.com/31996417/79891093-29423b80-8409-11ea-80f5-2c5321b633f5.png)
