### ISSUE TITLE
Configuring a SSL-Truststore is no longer working

### ISSUE THREAD

**Issue by ADegele** [dbeaver/dbeaver#18101]
### Description

We use a database which uses a custom SSL-Certificate. In the past we were able to connect to it by adding this SSL-Certificate to a truststore and start DBeaver with the following command:
`"C:\Program Files\DBeaver\dbeaver.exe" -nl en -vmargs -Djavax.net.ssl.trustStore=D:\dbeaver-truststore.jks`

This no longer works after upgrading from version `22.1.3.202207240747` to `22.2.3.202210231354`. On connect, DBeaver displays this error: `The application requester cannot establish the connection. (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)`

Configuring the truststore via dbeaver.ini does not work either.

After downgrading to 22.1.3, connecting works again.

[dbeaver-logs.zip](https://github.com/dbeaver/dbeaver/files/9918016/dbeaver-logs.zip)

### DBeaver Version

Community Edition 22.2.3.202210231354

### Operating System

Windows 10 Enterprise 20H2

### Database and driver

DB2 iSeries/AS 400 in unknown version with driver net.sf.jt400:jt400-11.0

### Steps to reproduce

1. Configure Database with custom SSL-Certificate
2. Add custom SSL-Certificate to a truststore
3. Start DBeaver with `"C:\Program Files\DBeaver\dbeaver.exe" -nl en -vmargs -Djavax.net.ssl.trustStore=D:\dbeaver-truststore.jks`
4. Connect to the database. After supplying the password, DBeaver displays this error: `The application requester cannot establish the connection. (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)`

**Comment by E1izabeth** [comment]
Could you try switching the preference `Use Windows truststore` on/off as a possible workaround?
![image](https://user-images.githubusercontent.com/28875055/199441946-1200ed28-9b93-42f6-97eb-231594353ee1.png)

Also logs would be very useful. You can find instructions how to send log files here https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by ADegele** [comment]
Hello @E1izabeth ,
thank you for your fast response. Indeed, the Setting `Use Windows trust store` was enabled. After toggling it to off and restarting, the connection works again. It seems as this option was added in 22.2.2 and enabled by default, which is incompatible with the JKS-Truststore we use.

Logs are linked in the original text: https://github.com/dbeaver/dbeaver/files/9918016/dbeaver-logs.zip

From my side, this issue is solved, however I am leaving this open in case you want to update your documentation or tweak when this setting enables itself.

**Comment by E1izabeth** [comment]
DBeaver used windows trust store by default (it was written in dbeaver.ini file). In the last release we removed this setting from dbeaver.ini and made a preference for that, because meet some certificate issue after one of the Windows update. We used windows truststore earlier and enable this option by default now. So nothing was supposed to be changed from DBeaver side.

We will investigate it. Thank you.

**Comment by E1izabeth** [comment]
Seems we need to check if `javax.net.ssl.trustStore` or `javax.net.ssl.trustStoreType` options were set in the dbeaver.ini file and do not set `Use Windows trust store` in this case.

**Comment by cbuzzsaw** [comment]
Windows Trust Stores don't seem to work as expected.

When simply using the Windows Trust Store, dbeaver cannot validate a certificate issued from an intermediate Issuing CA coupled with the trusted Root CAfrom the Windows Trust Store. 

Scenario:
Root CA Certificate installed/trusted in Computer's & User's "Trusted Root Certification Authorities" windows store.
Intermediate Issuing CA certificate installed/trusted in the Computer's and User's "Intermediate Certification Authorities" windows store.
Certificate issued from the Intermediate Issuing CA installed on the database we are connecting to from DBeaver. Windows shows the certificate can be validated, yet DBeaver throws the error mentioned above. 

There is something still off when using the new setting under Preferences --> Connections --> Use windows trust store checkbox. When I setup the cacerts file for the java trust store and uncheck the "User Windows trust store" things work as expected. But when setting up the Windows Trust stores properly the connections cannot be established. 

We have tested using an internal Certificate Authority and Intermediate Issuing Authority running Microsoft Certificate Services.
In powershell (and certificate control panel snapin) the Certificate locations are:
Root CA ---                  Cert:\LocalMachine\Root   (Trusted Root Certification Authorities)
Intermediate CA ----   Cert:\LocalMachine:\CA    (Intermediate Certificate Authorities)
Root CA ----                Cert:\CurrentUser\Root   (Trusted Root Certification Authorities)
Intermediate CA ----- Cert:\CurrentUser\CA       (Intermediate Certificate Authorities)

I did validate that this works when all certificates (Root and Intermediates) are in one container such as the "Trusted Root Certification Authorities" however this isn't really how Windows is designed to work. It takes advantage of the different certificate containers.  Example of this is where Root certificates are trusted in the "Trusted Root Certificate Authorities" container and intermediaries are stored in the "Intermediate Certification Authorities" container. When the entire chain isn't in a single container DBeaver doesn't validate the certificate properly. To use the dbeaver.ini file you specify -Djavax.net.ssl.trustStoreType=Windows-ROOT, there needs to be a way to specify the Windows-ROOT plus the Windows-CA containers or just have dbeaver use the Certificate store as windows is designed to by taking into consideration all of the trust chains from the different containers,  Trusted Certification Authorities, Intermediate Certification Authorities, Third-Party Root Certification Authorities, etc. along with the ability to check for "Untrusted Certificates" specified in that store.

**Comment by E1izabeth** [comment]
@ADegele please, try early access version https://dbeaver.io/files/ea/. Has the problem been solved?

**Comment by ADegele** [comment]
@E1izabeth I had the checkbox "Use Windows trust store" unchecked before the upgrade to 22.3.0-preview. After the upgrade, the connection to the DB still works, and I cannot check the checkbox again:
![grafik](https://user-images.githubusercontent.com/32536556/205244320-8f32035b-3565-40ab-8749-890751a6794b.png)
From my side everything is fine and I hope this is the behaviour you expect. Thank you!

**Comment by E1izabeth** [comment]
Thank you for checking. Yes, that's expected behaviour.

**Comment by treatmesubj** [comment]
@E1izabeth should this checkbox also recognize `-Djavax.net.ssl.TrustStoreType` has already been set in `dbeaver.ini` too?
https://stackoverflow.com/questions/44745261/why-do-jvm-arguments-start-with-d
Over my head, but ran into this problem today

**Comment by E1izabeth** [comment]
It will not override settings, which was set not by application itself.

**Comment by sinhote** [comment]
> Windows Trust Stores don't seem to work as expected.
> 
> When simply using the Windows Trust Store, dbeaver cannot validate a certificate issued from an intermediate Issuing CA coupled with the trusted Root CAfrom the Windows Trust Store.
> 
> Scenario: Root CA Certificate installed/trusted in Computer's & User's "Trusted Root Certification Authorities" windows store. Intermediate Issuing CA certificate installed/trusted in the Computer's and User's "Intermediate Certification Authorities" windows store. Certificate issued from the Intermediate Issuing CA installed on the database we are connecting to from DBeaver. Windows shows the certificate can be validated, yet DBeaver throws the error mentioned above.
> 
> There is something still off when using the new setting under Preferences --> Connections --> Use windows trust store checkbox. When I setup the cacerts file for the java trust store and uncheck the "User Windows trust store" things work as expected. But when setting up the Windows Trust stores properly the connections cannot be established.
> 
> We have tested using an internal Certificate Authority and Intermediate Issuing Authority running Microsoft Certificate Services. In powershell (and certificate control panel snapin) the Certificate locations are: Root CA --- Cert:\LocalMachine\Root (Trusted Root Certification Authorities) Intermediate CA ---- Cert:\LocalMachine:\CA (Intermediate Certificate Authorities) Root CA ---- Cert:\CurrentUser\Root (Trusted Root Certification Authorities) Intermediate CA ----- Cert:\CurrentUser\CA (Intermediate Certificate Authorities)
> 
> I did validate that this works when all certificates (Root and Intermediates) are in one container such as the "Trusted Root Certification Authorities" however this isn't really how Windows is designed to work. It takes advantage of the different certificate containers. Example of this is where Root certificates are trusted in the "Trusted Root Certificate Authorities" container and intermediaries are stored in the "Intermediate Certification Authorities" container. When the entire chain isn't in a single container DBeaver doesn't validate the certificate properly. To use the dbeaver.ini file you specify -Djavax.net.ssl.trustStoreType=Windows-ROOT, there needs to be a way to specify the Windows-ROOT plus the Windows-CA containers or just have dbeaver use the Certificate store as windows is designed to by taking into consideration all of the trust chains from the different containers, Trusted Certification Authorities, Intermediate Certification Authorities, Third-Party Root Certification Authorities, etc. along with the ability to check for "Untrusted Certificates" specified in that store.

I found myself with exactly this problem. I am in a corporate computer in Windows, I cannot edit my DBeaver installation and therefore I cannot change the cacerts to import a certificate, nor the dbeaver.ini file to use an external JVM where I have write access to the cacerts file. I can install certificates in my user trust stores, though. However, as this is an intermediate authority (not a root authority), the authentication still fails.

I see this comment sort of went unnoticed. @E1izabeth (tagging you as you were the person handling this fix), was this comment ever taken into consideration?

Thanks!

**Comment by E1izabeth** [comment]
@sinhote please create a new issue. This one is not about that and is closed
