### ISSUE TITLE
The command --NAME:tabName only works once

### ISSUE THREAD

**Issue by Thong2018** [dbeaver/dbeaver#18118]
### Description

I use the --NAME:tabName command to name multiple result tab names, but only the first command works

--NAME:firstTab
SELECT 123

--NAME:secondTab
SELECT 456

As a result, The first tab name is firstTab 1 and the second tab name is firstTab 1 (2) instead of secondTab
![tab-name](https://user-images.githubusercontent.com/44740643/199924314-d1994f01-8591-4be8-bd67-0ec615fdaa1f.png)

### DBeaver Version

21.3.2

### Operating System

Windows 10 Professional

**Comment by E1izabeth** [comment]
I'm unable to reproduce your issue. Could you tell me how exactly do you execute this script? Maybe you do something which is usual for you, but not obvious for us. The video showing this issue would be very helpful.

**Comment by uslss** [comment]
There have been no updates for a long. If issue is still actual for you - feel free to reopen it with additional info
