### ISSUE TITLE
Change of JDBC driver version requires DBeaver restart

### ISSUE THREAD

**Issue by igor2x** [dbeaver/dbeaver#18122]
### Description

If new custom JDBC driver is set, I expect to be applied immediately after click on OK button and reconnect to database.
But new JDBC driver is applied after DBeaver is restarted.

This is pretty annoying when I am now doing some in depth tests with both drivers if any new problems appears in new JDBC driver version.

### DBeaver Version

Community Edition 22.2.3

### Operating System

Windows 10

### Database and driver

1. Database name and version: Db2 v11.5
2. Driver name and version: Db2 JDBC Driver v4.31 and v4.32

### Steps to reproduce

I have two Db2 JDBC driver versions:
- Db2 v11.5.7.0 with JDBC version: 4.31
- Db2 v11.5.8.0 with JDBC version: 4.32
and I am switching between this two to make some in depth tests.

In DBeaver:
1. Database | Driver Manager | DB2 | DB2 LUW | Edit button.
2. Libraries tab.
3. Mark existing driver and Delete button.
4. Repeat step 3 for all drivers in the Libraries window if exists. At the end no drivers should be displayed.
5. Click on Add File and select JDBC v4.31 driver. Confirm with OK and Close buttons to close down dialogs.
6. Reconnect to the database.
7. Check the JDBC driver version:
SELECT CLIENT_PRDID AS JDBC_VERSION FROM TABLE(SYSPROC.MON_GET_CONNECTION(SYSPROC.MON_GET_APPLICATION_HANDLE(), -1))
and "JCC04310" is displayed, so version v4.31.
8. Repeat steps from 1 to 4.
9. Click on Add File and select JDBC v4.32. Confirm with OK and Close buttons to close down dialogs.
10. Repeat steps 6 and 7 and output is the same: "JCC04310". This is the problem. I expect new driver is already applied, but old driver version is still in use.
11. Restart DBeaver and repeat steps 6 and 7 and now "JCC04320" is displayed and now new JDBC is applied.

Like I remember in few versions back, this restart was not required.

**Comment by igor2x** [comment]
I have now tested this problem in DBeaver Community 22.1.0 on Windows 10 another computer I have and DBeaver restart after setting new JDBC version is not required. The only requirement is to reconnect, which is kinda obvious.

Reported problem seams to be a regression in 23.2.x.

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @igor2x 

Just update the driver via the Update button it is ok, but delete+Add does not work in the current session.

**Comment by igor2x** [comment]
1. I have upgraded DBeaver from **Help | Check for Updates** and closed down BDeaver.
2. I started DBeaver and from **Help | About** there is _DBeaver Community Edition 22.2.5__ displayed. This problem should be fixed in this version.
3. Repeat all steps from first post of this bug report and there is still exactly the same problem.

Can you please reopen this bug report.
