### ISSUE TITLE
Cannot install 22.2.4 over old 22.2.3 version

### ISSUE THREAD

**Issue by marcheschi** [dbeaver/dbeaver#18129]
### Description

Hi
I installed 22.2.4 over old 22.2.3 version on debian
using
 sudo dpkg -i dbeaver-ce_22.2.4_amd64.deb 
```
[sudo] password for paolo: 
Selecting previously unselected package dbeaver-ce.
(Reading database ... 309982 files and directories currently installed.)
Preparing to unpack dbeaver-ce_22.2.4_amd64.deb ...
Unpacking dbeaver-ce (22.2.4) ...
Setting up dbeaver-ce (22.2.4) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
```

But it does not upgrade the old version but instead it creates another indipendent program dbeaver, that does not read the old config.

Thank you 

### DBeaver Version

Community edition 22.2.3

### Operating System

Linux xstreamos 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce

sudo dpkg -i dbeaver-ce_22.2.4_amd64.deb

**Comment by Destrolaric** [comment]
@marcheschi Hi, I tried to reproduce this issue but couldn't do it. Could you provide additional information? Does this reproduces for the newer versions?
```
(Reading database ... 186839 files and directories currently installed.)
Preparing to unpack dbeaver-ce_22.2.4_amd64.deb ...
Unpacking dbeaver-ce (22.2.4) over (22.2.3) ...
Setting up dbeaver-ce (22.2.4) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.69) ...
```

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
