### ISSUE TITLE
Error in Console View when Running Eclipse Application inside Eclipse IDE

### ISSUE THREAD

**Issue by alvinjg** [dbeaver/dbeaver#18133]
### Description

We are encountering an error in eclipse Console View when running an eclipse application inside the Eclipse IDE. The error is logged at the start of eclipse application and after shutting it down.
The error is only encountered in the Eclipse Application. No error is logged in main Eclipse IDE metadata.log.

### DBeaver Version

Community Edition 22.1.2 to 22.2.3

### Operating System

Windows 10

### Steps to reproduce

1. Open Eclipse IDE with an installed DBeaver.
2. Run Eclipse Application inside the IDE. A Console Error is logged upon starting the application.
![image](https://user-images.githubusercontent.com/79795600/200319293-f5f70d27-cf11-4806-bece-777adc1bcce1.png)
![image](https://user-images.githubusercontent.com/79795600/200318186-38922c84-4d60-4a94-aa09-b85ce2fce15e.png)
3. Shutdown the opened application. An ExceptionInitializationError is logged. 
![image](https://user-images.githubusercontent.com/79795600/200318112-9c573fa1-0377-480b-ab03-f42633cb1ee1.png)

**Comment by LonwoLonwo** [comment]
Hello @alvinjg 

It's unclear from your message - does this exception affects the application work?

**Comment by alvinjg** [comment]
Hi @LonwoLonwo,
It does not affect our application. We are cleaning up any error in the console and found this issue. Our current workaround is to remove DBeaver from application plugins.

**Comment by ShadelessFox** [comment]
Hello @alvinjg,

If I understand your case correctly, you have Eclipse with DBeaver installed as a plug-in and you're trying to run another Eclipse-based application in Eclipse?

Are you running your application as a standalone application or as a plugin?

**Comment by alvinjg** [comment]
> If I understand your case correctly, you have Eclipse with DBeaver installed as a plug-in and you're trying to run another Eclipse-based application in Eclipse?

Yes

> Are you running your application as a standalone application or as a plugin?

We are developing plugins which are then installed to eclipse as standalone product. The actual product (eclipse based application) though does not package DBeaver plugins. We only install DBeaver in our development IDE. But during development when we run the application inside eclipse, it shows the error in the console log when application is startup/shutdown.
I have tried running a generic eclipse application (without our plugins) inside the IDE and the error is also replicated.

**Comment by ShadelessFox** [comment]
Can you send the entire log from Eclipse, please? We need to figure how DBeaver plugins were activated in the first place.

**Comment by alvinjg** [comment]
Attached are the logs generated by Eclipse IDE and Eclipse Application. I found that the Dbeaver Error is only logged in Console view (not in .metadata/log of the application) so I included the console view log.
[EclipseAppConsoleView.txt](https://github.com/dbeaver/dbeaver/files/10023455/EclipseAppConsoleView.txt)
[EclipseAppInIDE.log](https://github.com/dbeaver/dbeaver/files/10023456/EclipseAppInIDE.log)
[EclipseIDE.log](https://github.com/dbeaver/dbeaver/files/10023457/EclipseIDE.log)

**Comment by ShadelessFox** [comment]
Hello @alvinjg,

I'm sorry for the late response.

I can see that in your configuration you're running your application will ALL plugins from the workspace (including DBeaver's ones)

You need to configure plugins manually and exclude unnecessary ones:
![image](https://user-images.githubusercontent.com/35821147/202475133-1ba752a6-d948-4373-a59c-b3e1d0dbb5a5.png)

**Comment by alvinjg** [comment]
Hi @ShadelessFox,
Yes, we have tried that approach to remove the Dbeaver plugins in application as a workaround. It worked.
But do we have plans to fix the issue even DBeaver plugins are selected? In Eclipse 202106 with Dbeaver 21.1.1.202106210824, we do not need to do this workaround.

**Comment by ShadelessFox** [comment]
Sorry, I don't know how it worked before. This is a general solution that involves explicitly disabling non-required plugins.
