### ISSUE TITLE
Git Buttons and Menus missing on Apple Silicon / Ventura

### ISSUE THREAD

**Issue by DV8SHN** [dbeaver/dbeaver#18140]
### Description

I am running a Macbook Pro with Apple M1 Pro and MacOS 13 Ventura.

My DBeaver project view is missing the Git+ button, and the file menu doesn't have the Git submenu. I have no way of creating a new DBeaver project from Git.

### DBeaver Version

Community Edition 22.2.4 (reproduceable in others)

### Operating System

macOS Ventura

### Database and driver

N/A

### Steps to reproduce

Install the Git extensions using the Install New Software
Restart DBeaver
Notice missing buttons and menu items

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @DV8SHN 

Reproducible on the different macOS versions.
Can't reproduce on Windows.

**Comment by DV8SHN** [comment]
I have just upgraded my Intel iMac to Ventura and can confirm that the GIT+ button and GIT menu are available there. Seems to affect only Apple Silicon...

**Comment by MashaKorax** [comment]
I reproduced the problem on macOS Monterey 12.5.1 (Apple M1 chip) Dbeaver ce version 23.0.3

**Comment by MashaKorax** [comment]
Database tools toolbar on Windows vs Mac M1 (btn **Show git history** is missing on mac Customize Perspective ->database tools toolbar menu)
![image (1)](https://user-images.githubusercontent.com/84867187/234240649-5f7a6e67-07fe-4aae-82b5-fcf00944f4f9.png)
![2](https://user-images.githubusercontent.com/84867187/234240684-fa121563-23ed-447d-8b0a-e6692323e80c.png)

**Comment by MashaKorax** [comment]
![Снимок экрана 2023-04-25 в 11 57 25](https://user-images.githubusercontent.com/84867187/234242746-9f394369-7066-4b7e-86ca-173343ca730e.png)


Projects toolbar win vs mac
![dbeaver_CjUaU7Su0D](https://user-images.githubusercontent.com/84867187/234242913-23bf89b2-56f9-425e-a0ac-0090aa5498cc.png)

**Comment by MashaKorax** [comment]
In fact, for users Mac M1 the git feature is not available

**Comment by MashaKorax** [comment]
verified
