### ISSUE TITLE
Import Data not work cause Database Name Include in INSERT Query

### ISSUE THREAD

**Issue by pascalwilman28** [dbeaver/dbeaver#18142]
### Description

How to hide or remove database name when import data in dbeaver, i have already searching any features in dbeaver, but still not found how to fix it. Help if any one can solve this problem.

Step by step is in pictures

### DBeaver Version

Version 21.2.1.202109181446

### Operating System

Windows 10

### Database and driver

1. Impala JDBC 42-2.6.17-1020
2. Impala Database

### Steps to reproduce

![image](https://user-images.githubusercontent.com/58238421/200469135-d51086b7-20eb-42f6-86b6-f435980fabe3.png)
![image](https://user-images.githubusercontent.com/58238421/200469230-b4d99b4e-2207-472e-b80b-7ac4d2a99abe.png)
![image](https://user-images.githubusercontent.com/58238421/200469257-65574f36-a1a4-4026-aa2d-99eeea7c8115.png)
![image](https://user-images.githubusercontent.com/58238421/200469283-0b82b943-f0c4-4616-9975-5aafdee7d9dc.png)
![Uploading image.png…]()

**Comment by LonwoLonwo** [comment]
Hello @pascalwilman28 

What is the reason for the database name hiding?

**Comment by pascalwilman28** [comment]
Cause in INSERT INTO, the database/catalog name make the import job error

**Comment by pascalwilman28** [comment]
Now already solved, the setting in driver can omit catalog name when DDL and change active object to schema, not catalog

**Comment by LonwoLonwo** [comment]
Hello @pascalwilman28 

Could you please specify this setting? For future questioners.

**Comment by wfmit** [comment]
I am also interested in the setting hot to omit catalog name in Impala-Driver.
