### ISSUE TITLE
Tabs title encoding broken

### ISSUE THREAD

**Issue by Amir0715** [dbeaver/dbeaver#18150]
### Description

I've been using dbeaver for a long time and today, instead of tab names, I have this:
Please help me how to solve this problem
![изображение](https://user-images.githubusercontent.com/45153320/200579141-926b5791-7684-46b3-b92b-de1dad8c55c6.png)

### DBeaver Version

22.2.4

### Operating System

Windows 10 21H2

**Comment by LonwoLonwo** [comment]
Hello @Amir0715 

Please try this https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings

Or reload the application.

**Comment by Amir0715** [comment]
@LonwoLonwo, Unfortunately, after deleting the file, the error remained

**Comment by ShadelessFox** [comment]
Hello @Amir0715,

Perhaps update of Windows broke something. Try updating to the latest Windows version or rollback to the older one.

Please let me know if your issue was solved

**Comment by uslss** [comment]
seems to be similar to #13821

**Comment by uslss** [comment]
Is the issue still actual against the recent version?

**Comment by Amir0715** [comment]
@uslss unfortunately yes:
![изображение](https://user-images.githubusercontent.com/45153320/216257579-b1d20463-166c-4904-8e90-d944a02b0ca9.png)

**Comment by Destrolaric** [comment]
Hi, could you look at the font settings of tab font it is located in:
`Preference -> General -> Appearance -> Colors and Fonts -> Header Font` 
Please, provide screenshot of it's value

**Comment by E1izabeth** [comment]
Does it still actual for the DBeaver 23.0.0? If you still experience this, please try changing font for `Preference -> General -> Appearance -> Colors and Fonts ->DBeaver Fonts -> Main font`  and let me know if it helps

**Comment by Amir0715** [comment]
Hi, I reinstalled Windows and now the error is gone.
I hope I won't meet her again

**Comment by bimantara679** [comment]
> ### Description
> I've been using dbeaver for a long time and today, instead of tab names, I have this: Please help me how to solve this problem ![изображение](https://user-images.githubusercontent.com/45153320/200579141-926b5791-7684-46b3-b92b-de1dad8c55c6.png)
> 
> ### DBeaver Version
> 22.2.4
> 
> ### Operating System
> Windows 10 21H2
> 
> ### Database and driver
> _No response_
> 
> ### Steps to reproduce
![tab title error dbeaver](https://github.com/dbeaver/dbeaver/assets/55911545/d1b9f95d-22d3-44ca-80db-aa87fe3f2699)

> _No response_
> i can fixed mine with change the main font in preference
> ### Additional context
> _No response_

**Comment by thalesaguiar** [comment]
![Captura de tela 2024-07-09 191730](https://github.com/dbeaver/dbeaver/assets/114702209/6ef083fa-36b3-4e24-8166-2a1b399d0d30)

I had this issue only in Dark theme :(

**Comment by songinnight** [comment]
It's not broken in classic theme.
