### ISSUE TITLE
Strange characters with connection between Databricks and Dbeaver

### ISSUE THREAD

**Issue by JaoGaspar** [dbeaver/dbeaver#18155]
### Description

I try different ways to connect the two platforms, but for some reason I see strange characters in my query. 

### DBeaver Version

Version 22.2.0.202209090951

### Operating System

WIndows 10

**Comment by JaoGaspar** [comment]
![image](https://user-images.githubusercontent.com/110673812/200637989-eff15291-0a0d-46c4-9f33-65c79bf7482e.png)

**Comment by LonwoLonwo** [comment]
Hello @JaoGaspar 

I'm sorry for not getting back to you sooner. Can you please provide more info about your database and driver - you can find in in the Test Connection dialog in the Connection settings.
Also please provide example of the original table DDL and data sample for it to reproduce this issue.

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it.
