### ISSUE TITLE
Right-click unselects data

### ISSUE THREAD

**Issue by haufs** [dbeaver/dbeaver#18152]
### Description

Select data in a query tab:
![image](https://user-images.githubusercontent.com/117753713/200605925-57f0f503-e588-451b-bfe4-475f6df6e6ae.png)

Right-click in that tab and data is unselected so I'm unable to use Format:
![image](https://user-images.githubusercontent.com/117753713/200606068-44d62593-f05d-4127-b789-24d59e63b011.png)

### DBeaver Version

Community Edition version 22.2.4

### Operating System

Windows 10

### Additional context

this issue did  not occur in 22.2.3
thank you

**Comment by emanueol** [comment]
Yes just found this problem as well, here's animated gif showing the problem:
![problem - right click on all selection - unselects selection](https://user-images.githubusercontent.com/8422412/200627561-e3b21160-efee-494e-89da-f1b927ae30f3.gif)

**Comment by haufs** [comment]
yes thank you, that is exactly what I'm experiencing.

**Comment by joshcsmith13** [comment]
agreed.  this new "feature" implementation sucks.  I appreciate that you wanted to implement the "selected query" contextual entries, but don't eliminate the traditional "Copy" command for selected text.  This is especially painful when I am just trying to copy one value from a list of field/values in my Where clause.

**Comment by struck89** [comment]
Same here.
In the mean time, how can I "export from query", from the query I have selected?

Found it:
![image](https://user-images.githubusercontent.com/18152095/200662488-6cf338ef-e201-4e39-bf25-bc94a2b7bf0c.png)
I just need to click on the export down there after having executed the query.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by ShadelessFox** [comment]
We aren't big fans of such bugs, too. But please, let's be more friendly to each other.

**Comment by joshcsmith13** [comment]
Forgive my harsh language.  I may have overreacted when I suspected that DBeaver was intentionally now going to act like a certain other database tool I have been stuck using for years which does not support right-click>copy and never will.  :(
