### ISSUE TITLE
table copy features

### ISSUE THREAD

**Issue by Douglassharris12** [dbeaver/dbeaver#18153]
I am trying to copy table data from one instance to another.  I am using the export to SQL option that generates insert statements.  I have two issues:

1) The resulting insert statement requires a lot of formatting cleanup before it will run. I want to automatically have varchars single-quote delimited.  How do I do that? I also want the timestamps to be prefixed by the keyword "timestamp".  How do I do that?

Also, the resulting record set in the insert statements is not accurate. It has the right number of records, 36,011, but there are 1804 missing records and 1804 repeated records to make up the overall count.  A simple select * against the table has the same error.  It seems that only an export to CSV gives the right records.  How can I fix this?

**Comment by iraidaa** [comment]
Hi @Douglassharris12,

Please answer some questions.

What are the databases you work with?
Do you use Tools -> Create new task -> Data export option? 
Please provide some screenshots or a piece of data to reproduce the issue.
Could you please send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.

Thank you.

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
