### ISSUE TITLE
Null pointer exception in Library tab with Information button

### ISSUE THREAD

**Issue by igor2x** [dbeaver/dbeaver#18164]
### Description

When driver JDBC driver is deleted Information button is still enabled. Clicking on it produce _Null pointer exception_ error.

### DBeaver Version

Community Edition 22.2.4

### Operating System

Windows 10

### Database and driver

1. Database name and version: Db2 v11.5.8.0
2. Driver name and version: JDBC v4.31.10 and v4.32.28

### Steps to reproduce

1. Start DBeaver and menu **Database | Driver Manager.**
2. **DB2 | DB2 LUW** and **Edit** button.
3. **Libraries** tab.
4. Select drivers and use **Delete** button to delete all of the drivers.
5. Now no drivers exists in window, but **Information** is still enabled. Clicking on **Information** button produces _Null pointer exception_ error.

Because there is no driver on the list, **Information** button should be greyed out. Also if there are no entries in window **Delete** button should also be greyed out.

**Comment by igor2x** [comment]
Additional problem related to not properly grey out options.

1 - 3 steps the same as above.
4. Select driver from list and click on **Find Class** button.
5. _Driver class_ drop down box is filled up.
6. Select drivers and use **Delete** button to delete all of the drivers. But _Driver class_ drop down box is still filled with data. 
![image](https://user-images.githubusercontent.com/10895030/200856391-2901e4ab-492d-46a0-8f1a-f06c78e8d451.png)
Drop down selection should be cleansed up when **Delete** button is pressed.

**Comment by LonwoLonwo** [comment]
Ok, Thanks for the bug report
