### ISSUE TITLE
Update pg_dump version in windows dbeaver.

### ISSUE THREAD

**Issue by swats-the-floran** [dbeaver/dbeaver#18168]
There is a postgresql 14 server. While i try to create a backup with dbeaver from windows i get an error that pg_dump 13 cannot work with postgresql 14 database. pg_dump in windows postgresql driver is needed.

**Comment by ShadelessFox** [comment]
Hello @swats-the-floran,

Thanks for the feature request

**Comment by Seblor** [comment]
Bumping this as I cannot dump my database since the server needs pg_dump 15

**Comment by flambchap** [comment]
We need to do this for our PRO products as well.
