### ISSUE TITLE
oracle modify column error 

### ISSUE THREAD

**Issue by liheyu719489316** [dbeaver/dbeaver#18167]
### Description

![image](https://user-images.githubusercontent.com/8488480/200972540-ccc1030b-8f90-4041-a7d7-1c3641e789d1.png)

### DBeaver Version

22.2.4

### Operating System

windows 10

### Database and driver

_ORACLE_

**Comment by ShadelessFox** [comment]
Hello @liheyu719489316,

Please provide more information about your problem. Additionally, please attach the error message as a text

**Comment by liheyu719489316** [comment]
@ShadelessFox 
When I modify a column, an SQL statement is created.
![image](https://user-images.githubusercontent.com/8488480/201870964-dc7ad7ab-0243-44f4-8f3b-bf1ffc14086a.png)
An error occurred when I ran the SQL statement.
![image](https://user-images.githubusercontent.com/8488480/201871552-a7093527-f9f3-4685-bf30-92a0d652ebeb.png)

**Comment by ShadelessFox** [comment]
I need a textual representation of that error message, so I can translate it since I don't know your language, sorry.

**Comment by E1izabeth** [comment]
@ShadelessFox, the message from oracle says: "ORA-01451: column to be modified to NULL cannot be modified to NULL"

**Comment by E1izabeth** [comment]
@liheyu719489316 it seems that you have the primary key or check constraint which is enforcing the NOT NULL constraint. Could you check it and drop if such constraint exists?

**Comment by E1izabeth** [comment]
There is no update on this issue for a long time. Please let me know if the issue is still actual for you.

**Comment by zhuhongjie** [comment]
> There is no update on this issue for a long time. Please let me know if the issue is still actual for you.

This problem still exists

**Comment by E1izabeth** [comment]
We still need an answer to that question https://github.com/dbeaver/dbeaver/issues/18167#issuecomment-1352878392
>@liheyu719489316 it seems that you have the primary key or check constraint which is enforcing the NOT NULL constraint. Could you check it and drop if such constraint exists?
