### ISSUE TITLE
Snowflake query doesn't return result when lob column is selected 

### ISSUE THREAD

**Issue by Smart-Bird-ADM** [dbeaver/dbeaver#18165]
### Description

When I run a select query to snowflake where table has a lob kind of column and if this column is used as an output column then query doesn't return result and just goes on and on.  if I remove lob column from select then result returned within a second or two.

if table1 has no lob columns then "select * from table1" returns result.
if table2 has a lob column then "select * from table2" doesn't return result.
if I select explicit column and not selecting lob column then it does return result.

### DBeaver Version

Community Edition 22.2.4

### Operating System

macOS Monterey 12.6.1

### Database and driver

Snowflake on AWS
snowflake-jdbc:release 3.13.6

**Comment by ShadelessFox** [comment]
Hello @mnt1979,

Can you please provide sample DDL of such a table?

**Comment by Smart-Bird-ADM** [comment]
create or replace TABLE TDPR (
	O_ID NUMBER(38,0) NOT NULL,
	D_ID NUMBER(38,0),
	D_GRP_ID VARCHAR(50),
	D_DATE TIMESTAMP_NTZ(9),
	D_BY VARCHAR(100),
	LOB VARCHAR(100),
	S_NAME VARCHAR(250),
	S_ABBR VARCHAR(100),
	S_DB_NM VARCHAR(100),
	CHG_NUM VARCHAR(20),
	TASK_NUM VARCHAR(100),
	TASK_NAME VARCHAR(250),
	GRP_NAME VARCHAR(250),
	PAYLOAD VARCHAR(16777216),
	D_STATUS VARCHAR(20),
	PROCESS_TS TIMESTAMP_NTZ(9),
	primary key (O_ID)
);

**Comment by Smart-Bird-ADM** [comment]
PAYLOAD is a CLOB like column in snowflake and defined as VARCHAR max.

**Comment by ShadelessFox** [comment]
I guess that the problem is that that column is just too big. Can you verify that it has data in it?

During the execution of that statement, is the amount of memory that DBeaver consumes spikes?

**Comment by Smart-Bird-ADM** [comment]
I tried running queries with limit 1 and limit 10, both returned result within couple seconds.  As soon as I ran another query with limit 25, it has not returned any result so far after 1700 seconds and there was no major memory spike in activity monitor.

**Comment by ShadelessFox** [comment]
Thanks for explaining. We'll look into that.

**Comment by LonwoLonwo** [comment]
Hello @Smart-Bird-ADM 

Could you please check the latest DBeaver version? We added some changes for the significant content reading.
Maybe the issue is not reproducible anymore.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
