### ISSUE TITLE
Compare Database data option missing

### ISSUE THREAD

**Issue by davidnewcomb** [dbeaver/dbeaver#18179]
### Description

I keep reading that DBeaver can compare the data in different tables but can not find any options to actually do this!

On page: https://github.com/dbeaver/dbeaver/wiki/Data-compare 

"Then choose Database ⇒ Compare/Migrate ⇒ Data Compare from the menu and the Data Compare Wizard will appear. Here you can preview selected tables or choose other ones. Then you can navigate to the second page."

As you can see from the screenshot the "Data Compare" option is missing:

![Screenshot 2022-11-10 at 16 15 08](https://user-images.githubusercontent.com/951359/201150160-fc6878dc-299a-4650-9aad-75beb53edece.png)

1) If this is a bug and the option is missing by accident then please can you put it back in.
2) If this option has moved can you update the documentation.
3) If this is an option not available in the community edition could you update the documentation to say this is a premium feature.

I have been looking for other documentation about comparing data but this was the only page I could find and it appears to be incorrect :(

### DBeaver Version

Community Edition 22.2.3.202210231354

### Operating System

macOS Monterey 12.5

### Database and driver

DB2 jdbc

### Steps to reproduce

I selected 2 tables like the documentation directs but Data Compare in not in the menu.

**Comment by E1izabeth** [comment]
I can reproduce it

![image](https://user-images.githubusercontent.com/28875055/201157189-35708271-47c5-4837-8ccf-056e254101d3.png)

**Comment by E1izabeth** [comment]
@davidnewcomb this feature presented only in DBeaver PRO
https://dbeaver.com/edition/

**Comment by davidnewcomb** [comment]
Thanks. Then it's just a documentation update then please :)

Also, which version is the PRO version on that page? All of them or just Enterprise up?

**Comment by E1izabeth** [comment]
Updated.

This feature exists in Enterprise and Ultimate editions.

**Comment by honsa** [comment]
@E1izabeth I use the Enterprise Version 23.2.0 but cannot find this option:

![image](https://github.com/dbeaver/dbeaver/assets/526006/ae1f56b4-3aad-472c-b790-def98bdab648)
