### ISSUE TITLE
Network unavailable: javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by jrodriguezm04** [dbeaver/dbeaver#18175]
### Description

I just installed dbeaver in my Windows 10 local machine.

Trying to connect to a PostgreSQL Database, it shows the following error message:

![image](https://user-images.githubusercontent.com/117922106/201119672-c884d10b-942f-4302-88cf-ced9955c413e.png)

And when I try to download the postgres drivers, it shows the same. Any idea?

Thanks in advance.

### DBeaver Version

Community Edition 22.2.4

### Operating System

Windows 10 64bit

### Steps to reproduce

1. Create new connection, selecting PostgreSQL.
2. Adding credentials
3. Trying to connect, but it can't due to the message showed above.
4. Can't even download or update drivers.

**Comment by TheRealAstroboy** [comment]
same here (after update) on old **Windows 7** computer with **DBeaver 22.2.4**

I tried to drop all connexions, remove Postgres driver and reinstall DBeaver, but Posgres driver is now missing 

- update -

I tried to download Postgres driver with maven artifact and same error message : 
_Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target_

I tried again with Firewall down and same situation

**Comment by E1izabeth** [comment]
@jrodriguezm04, @TheRealAstroboy, please uncheck the `Use Windows trust store` setting in `Preferences->Connections` and restart DBeaver. It should help.
![image](https://user-images.githubusercontent.com/28875055/201152880-ed80eb8f-a4da-411d-81c2-327509c216e9.png)

**Comment by jrodriguezm04** [comment]
@E1izabeth it worked!!! thank you so much for your response, have a nice day ahead :D

**Comment by Mohan15054** [comment]
@E1izabeth  Thanks!

**Comment by fff26** [comment]
@E1izabeth - Superstar!

**Comment by d3vdays** [comment]
I am having the exact same issue on Mac Os Ventura and Dbeaver version 23.1.3. 

What's the solution for MacOs as I don't see that Windows setting on Mac App. 

This worked flawlessly before and now this error.

**Comment by tayalnishu** [comment]
I am facing the same issue like @d3vdays with below configurations: 

MacOS Ventura 13.5.1
DBeaver version 23.1.5

**Comment by alun** [comment]
@d3vdays @tayalnishu Just in case my solution for Mac was:

1) go to https://repo1.maven.org/maven2/ and export the certificate to a `.cer` file
2) `cd /Applications/DBeaver.app/Contents/Eclipse/jre/Contents/Home`
3) `bin/keytool -importcert -file ~/Downloads/repo1.maven.cer -alias maven -cacerts` (default password is "changeit", answer yes to the question if you trust the cert)
4) restart DBeaver - it should work 

Note: I've also installed added a cert from here https://dbeaver.io/files/jdbc - not sure which particular one worked

**Comment by d3vdays** [comment]
Thanks. I did something similar. 

When I encountered this issue with dbeaver I downloaded another SQL tool on my Mac and had the exact same issue. So I downloaded the certificate and imported it into the local cert stores and it worked fine.

I also completely uninstalled java from my Mac before this to avoid any confusion. 

I still don't know why this issue started though on my Mac. Everything was working fine before this. Anyway, maybe something changed on my Mac about firewall or java settings.

**Comment by jyang20-gilead** [comment]
Could any one help me and educate me how to export the certificate to a .cer file? I am getting lost in the webpage https://repo1.maven.org/maven2/ . Thanks a lot!

**Comment by JuanY9** [comment]
@alun Could you please educate me how to export the certificate from https://repo1.maven.org/maven2/ . Thanks a lot!

**Comment by gutosantos82** [comment]
@JuanY9 I used Firefox to export the certificate.

1. Open Firefox
2. Go to https://repo1.maven.org/maven2/
3. Click on the padlock on the left side of the URL at the Address bar
4. Click on Connection Secure --> More Information
5. Click on View Certificate
6. Scroll down to Miscellaneous --> Download --> PEM (cert)
I downloaded the PEM file and it worked the same using @alun instructions.

**Comment by JuanY9** [comment]
@gutosantos82 
Thank you very much!

**Comment by tiagofvalerio** [comment]
I'm having this problem on Ubuntu 20.04 and Dbeaver 23.2.5

Anyone facing the same problem?

**Comment by tqi-gleao** [comment]
@tiagofvalerio replace the cacerts file in the dbeaver install folder with the cacerts file from the java install folder, it did the trick for me

**Comment by weynars** [comment]
Thanks @gutosantos82

**Comment by Ubaidbutt** [comment]
Hey @alun, I am facing a similar issue maybe not exactly this one on Macbook M3 with dbeaver version 23.2.0 and even the above solution does not work for me.
I keep getting the following error:

<img width="1261" alt="image" src="https://github.com/dbeaver/dbeaver/assets/41114284/f3b48a9c-f2ca-45c7-968a-1b550553e786">

**Comment by pformanek** [comment]
> Hey @alun, I am facing a similar issue maybe not exactly this one on Macbook M3 with dbeaver version 23.2.0 and even the above solution does not work for me. I keep getting the following error:
> 
> <img alt="image" width="1261" src="https://private-user-images.githubusercontent.com/41114284/308932185-f3b48a9c-f2ca-45c7-968a-1b550553e786.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTgwNTUsIm5iZiI6MTcwOTgxNzc1NSwicGF0aCI6Ii80MTExNDI4NC8zMDg5MzIxODUtZjNiNDhhOWMtZjJjYS00NWM3LTk2OGEtMWI1NTA1NTNlNzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEzMjIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MDU0Y2UxNWJlY2IzZDY0N2EzZWRjOGQwOGQxYTM4NGEyMTMwMzgwMGI3NmQxZTc1YTFmNjM5MmQxNDU2YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._JEKS-K_NYuv2GqGFLf7EbLlj305kl21ZNCBxNApzS4">

I have the same issue on M3. Also tried solution above.

**Comment by pformanek** [comment]
Hi @Ubaidbutt,
I'm also on M3.
What helped me was adding the ZScaler Root certificate.
In a similar way like [above](https://github.com/dbeaver/dbeaver/issues/18175#issuecomment-1722554453).

`bin/keytool -importcert -file ~/Downloads/ZscalerRootCA.cer -alias zscaler_root -cacerts`

I exported the root certificate instead of just dbeaver.

**Comment by ervipin19** [comment]
> Hi @Ubaidbutt, I'm also on M3. What helped me was adding the ZScaler Root certificate. In a similar way like [above](https://github.com/dbeaver/dbeaver/issues/18175#issuecomment-1722554453).
> 
> `bin/keytool -importcert -file ~/Downloads/ZscalerRootCA.cer -alias zscaler_root -cacerts`
> 
> I exported the root certificate instead of just dbeaver.

How can we get ZScaler Root Certificate?

I downloaded other 2 certificates as specified but still getting same error.

**Comment by Joeylu-master** [comment]
I'm also on M3, and follow the way as [above](https://github.com/dbeaver/dbeaver/issues/18175#issuecomment-1722554453.). But still get this error, can any one help with this?

**Comment by rithvikmundra** [comment]
I am having an M3 Mac and unable to get Dbeaver to work. Getting the same error as above after running the steps @alun mentioned above. Can anyone please help?

Error - 

> Network error
> 
> Reason:
> Network unavailable
> javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by jinshen-cn** [comment]
> @d3vdays @tayalnishu Just in case my solution for Mac was:
> 
> 1. go to https://repo1.maven.org/maven2/ and export the certificate to a `.cer` file
> 2. `cd /Applications/DBeaver.app/Contents/Eclipse/jre/Contents/Home`
> 3. `bin/keytool -importcert -file ~/Downloads/repo1.maven.cer -alias maven -cacerts` (default password is "changeit", answer yes to the question if you trust the cert)
> 4. restart DBeaver - it should work
> 
> Note: I've also installed added a cert from here https://dbeaver.io/files/jdbc - not sure which particular one worked

Thanks, it works. the https://repo1.maven.org/maven2 cert fixes the issue.

**Comment by smore07** [comment]
> > Hi @Ubaidbutt, I'm also on M3. What helped me was adding the ZScaler Root certificate. In a similar way like [above](https://github.com/dbeaver/dbeaver/issues/18175#issuecomment-1722554453).
> > `bin/keytool -importcert -file ~/Downloads/ZscalerRootCA.cer -alias zscaler_root -cacerts`
> > I exported the root certificate instead of just dbeaver.
> 
> How can we get ZScaler Root Certificate?
> 
> I downloaded other 2 certificates as specified but still getting same error.

This worked for me! Thanks!
