### ISSUE TITLE
Clickhouse table DDL generation syntax error

### ISSUE THREAD

**Issue by ish1mura** [dbeaver/dbeaver#18172]
### Description

Hello!
We use non-english table names in our Clickhouse DB.
There is an error when I open table DDL tab:
```sql
/* ERROR WHILE READING SOURCE:
SQL Error [62] [07000]: Code: 62. DB::Exception: Syntax error: failed at position 29 ('�'): Клиенты. Unrecognized token: '�'. (SYNTAX_ERROR) (version 22.10.1.1877 (official build))
, server ClickHouseNode(addr=http:1.2.3.4:8123, db=db)@650024970
*/
```
DBeaver runs this query and raises error above:
```sql
show create table Клиенты
```
But if you quote table name, there isn't error:
```sql
show create table `Клиенты`
```
Possible solution is to add quotes in file `plugins/org.jkiss.dbeaver.ext.clickhouse/src/org/jkiss/dbeaver/ext/clickhouse/model/ClickhouseMetaModel.java`:

```java
        try (JDBCSession session = DBUtils.openMetaSession(monitor, sourceObject, "Read Clickhouse view/table source")) {
            try (JDBCPreparedStatement dbStat = session.prepareStatement(
-                "SHOW CREATE TABLE " + sourceObject.getFullyQualifiedName(DBPEvaluationContext.DDL)))
+                "SHOW CREATE TABLE `" + sourceObject.getFullyQualifiedName(DBPEvaluationContext.DDL))) + "`"
            {
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
```

### DBeaver Version

Community 22.2.4

### Operating System

Windows 10, Linux Mint 21

### Database and driver

DB: Clickhouse 22.10.1.1877
Driver: com.clickhouse:clickhouse-jdbc:0.3.2-patch11

### Steps to reproduce

1. Create table with russian name, single-word
2. Open `Table settings -> DDL`

**Comment by E1izabeth** [comment]
Thank you for bug report.

In addition: we can't even create table with non-latin characters in name.

**Comment by ish1mura** [comment]
@E1izabeth 
Try to copy and run this script on some Clickhouse DB (if it helps):
```sql
CREATE TABLE default.`Клиенты`(
    `Клиенты Код` Int16,
    `Клиенты` String
)
ENGINE = MergeTree
PRIMARY KEY `Клиенты Код`
ORDER BY `Клиенты Код`
SETTINGS index_granularity = 8192;
```

**Comment by E1izabeth** [comment]
I reproduced it, thanks.
