### ISSUE TITLE
Export From Query not functioning correctly following update to 22.2.4

### ISSUE THREAD

**Issue by amanda-mason** [dbeaver/dbeaver#18183]
### Description

Since the update to 22.2.4, the 'Export From Query' tool no longer functions and instead results in an Error message.

Normally, I am able to highlight/select a query and use the 'Export From Query' option to execute the query and export the result (as a csv) in a single action. (With the query highlighted, right-click to pull up the query menu, then select 'Execute', then select 'Export From Query'). Prior to the update this worked perfectly, but now (for the same query and actions taken) results in an error stating that a column does not exist (that actually does exist). SQL Error [42703]: ERROR: column "[column_name]" does not exist

I can successfully execute the same query in the main editor window and then select the 'Export result set to file or another table' (with the same data transfer options used) and it will successfully export the result set. 

'Export from Query' seems to work with some freshly written queries, even when written seemingly identically to previously written queries that are erroring.

### DBeaver Version

Community Edition 22.2.4

### Operating System

Windows 11

### Database and driver

PostgreSQL 14.2
PostgreSQL JDBC Driver 42.5.0

### Steps to reproduce

1. Highlight/select sql script in editor
2. Right-click on the highlighted query to pull up the query actions menu
3. Select 'Execute' menu
4. Select 'Export From Query' action

**Comment by amanda-mason** [comment]
After further testing, it looks to be hanging up on blank lines within the query.
For instance, the first query below will allow 'Export From Query' to export successfully, whereas the second query (which is the same other than the empty line) results in an error stating that the column "car" does not exist:
select
      car
     ,driver
from race
;

select
      car

     ,driver
from race
;

**Comment by E1izabeth** [comment]
Please provide more information about the query you're trying to use for export and fail.

**Comment by amanda-mason** [comment]
Hi E1izabeth, 
Thank you for the reply! 
It is happening with any of my previously written queries (for which I used to be able to use this function), seemingly even the simplest of queries. I have pasted an example below. 
```
select
rpt_parent_client

,client_type
from led.ledger_out_pharmacy
;
```

The more I am testing, the more little clues I am finding: If I highlight the query above within an editor (containing other non-highlighted code), I will get the error on 'Export From Query'. If I copy and paste that same highlighted section to a new editor, I can get the 'Export From Query' to work. 
Also, if I delete the blank line before ,client_type and then highlight the section within an editor, it will work. But if I leave the blank line, I get an error stating that column "rpt_parent_client" does not exist. 

It almost seems as if the query delimiters (blank lines or semicolon ;) may be causing the issues? I.e. 'Export From Query' seems to be treating highlighted sections and/or delimiters differently vs the previous version.

**Comment by E1izabeth** [comment]
Probably blank lines cause this issue. Could you try unchecking `Blank lines as a statement delimiter` setting?
![image](https://user-images.githubusercontent.com/28875055/201213774-fb6617de-860d-4d8c-8238-c851e84a0e12.png)

**Comment by LonwoLonwo** [comment]
Also, can you please check your query on this page? Is it your selected query?

![2022-11-11 17_56_05-Window](https://user-images.githubusercontent.com/45152336/201366142-71dee815-7b45-47cc-8b1b-6e9b54b3b390.png)

**Comment by amanda-mason** [comment]
Unchecking ``Blank line is statement delimiter`` solved the issue for the query posted above. 
However, when I add back in my defined named query parameters (see query example below), it hangs up and asks me to bind the parameters (in v22.2.3 it would retain the highlighted parameters for use in the highlighted query for export). After I re-define the parameters, it will run, but you can understand, this is a bit of an irritant to re-enter what I already have defined in the highlighted query.

```
@set mm_ind = 0

@set rx_chain = 7 

/*-------------------------------------------------------------------*/

select
	 rpt_parent_client as parent_client
	,client_type
from led.ledger_out_pharmacy lop 
where rx_chain_id = :rx_chain
and mm_billable = :mm_ind

```

**Comment by amanda-mason** [comment]
I rolled back to v22.2.3 and did some comparisons; both show the selected query as beginning with `/*---------------------*/ select rpt_parent_client....`

The one difference I do notice is the behavior of the highlighted section at the time of right-click. In v22.2.3, the entire highlighted section remains highlighted as I right-click and select 'Execute' -> 'Export From Query'. However, in v22.2.4, the highlighted section becomes deselected on right-click as I select 'Execute' -> 'Export From Query'. Something weird is going on there where it is not actually retaining all of my highlighted section for the execute/export procedure. 

I have attached screenshots showing the above comparison between v22.2.3 and v22.2.4

![DB22 2 3_highlighted_export](https://user-images.githubusercontent.com/64216159/201381600-64ae31cc-3b72-4c57-b9b9-47c019ab888e.png)

![DB22 2 4_highlighted_export](https://user-images.githubusercontent.com/64216159/201381666-2df84754-6199-4218-8b48-1f9f9eb9c136.png)

**Comment by amanda-mason** [comment]
Ok, I think I have solved it (at least for this current sample query). It is the most trivial solution ever - 
In v22.2.3 you can right-click anywhere in your highlighted section to then select Execute -> Export From Query. However, in v22.2.4, you MUST right-click at the very top of the highlighted section to actually execute everything you have highlighted, including defined parameters. 
Right-clicking at the very top of the highlighted section also changes the behavior of the highlighted section to remain highlighted during the right-click (as it does in v22.2.3 in the screenshots in my previous comment).

Although functioning, this behavior is still a bit bizarre; I think the ability to click anywhere in the highlighted section was more intuitive (as in v22.2.3) vs having to highlight what you want to execute and then having to scroll all the way to the top line to perform the right-click. But at least this is a work-around to have Export From Query back. :)

**Comment by LonwoLonwo** [comment]
The last issue is solved here: https://github.com/dbeaver/dbeaver/issues/18152
The fix will be available in the next release.

**Comment by E1izabeth** [comment]
@amanda-mason please, try DBeaver 22.2.5. Is your issue solved?

**Comment by amanda-mason** [comment]
@LonwoLonwo @E1izabeth Works perfectly in 22.2.5! Thank you both so much for your help!!
