### ISSUE TITLE
DBeaver cannot load cert file with multiple certs inside correctly

### ISSUE THREAD

**Issue by zhangyangyu** [dbeaver/dbeaver#18188]
### Description

Trying to connect MySQL using SSL. On macOS, when I give the system cert bundle `/etc/ssl/cert.pem`, the connection fails and reports `Path does not chain with any trust anchors`. The server uses ISRG X1 CA so definitely it exists in `/etc/ssl/cert.pem`. But when I give the cert with only ISRG X1 CA cert inside, the connection succeed!

Seems DBeaver cannot load cert file with multiple certs inside correctly. It could only handle one file one cert. Multiple certs in a single file is allowed for a long time and most system CA bundles all goes like this. And clients could handle it well.

### DBeaver Version

Community Edition 22.2.4

### Operating System

macOS

### Database and driver

MySQL Connector/J 8.0.29

**Comment by ShadelessFox** [comment]
Thank you for your report.

Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by zhangyangyu** [comment]
[sslerror.log](https://github.com/dbeaver/dbeaver/files/10037564/sslerror.log)

@ShadelessFox PTAL. You can use any system builtin cert file to reproduce, usually it contains many certs inside one file.

**Comment by ShadelessFox** [comment]
Thanks for the log file.

According to its contents, it's actually the issue of the MySQL Connector/J driver.

According to [this StackOverflow answer](https://stackoverflow.com/a/48305493), the certificate must contain all the certificates of the chain.

**Comment by zhangyangyu** [comment]
> According to its contents, it's actually the issue of the MySQL Connector/J driver.
> 
> According to [this StackOverflow answer](https://stackoverflow.com/a/48305493), the certificate must contain all the certificates of the chain.

The summary seems not right in this case. Because when I use the pem file with only the CA cert inside, the connection succeeds. It doesn't contain the intermediate cert(thus not all the certs of the chain included).

But the stackoverflow answer does give useful info. The keytool will only import the first cert in the cert bundle file. I think this is what need to be addressed.

**Comment by arhayka** [comment]
Hi @zhangyangyu,
Could you please download the latest DBeaver version and see if the issue is gone there?

**Comment by zhangyangyu** [comment]
@arhayka tried 22.3.5, still no.

**Comment by E1izabeth** [comment]
We need to cut the file by BEGIN-END blocks and read the first certificate.

**Comment by zhangyangyu** [comment]
Take a quick look at the code, seems finally the cert data is parsed by https://github.com/dbeaver/dbeaver/blob/85ca6582673a63c727e812ca4fa1e030484df449/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/app/DefaultCertificateStorage.java#L132. It uses `CertificateFactory. generateCertificate` which only reads one certificates once. The behavior of `CertificateFactory` is clearly documented in https://docs.oracle.com/javase/8/docs/api/java/security/cert/CertificateFactory.html. And the workaround is also documented.
