### ISSUE TITLE
Select error when one field is a string

### ISSUE THREAD

**Issue by jmsanzg** [dbeaver/dbeaver#18193]
### Description

Just executing this leaves DBeaver unable to execute more queries or do anything.
select '' as a from dual

### DBeaver Version

Community Edition 22.2.0.202209051344

### Operating System

Ubuntu Linux

### Database and driver

MySQL 5.7.35
MySQL Driver 8.0.17

### Steps to reproduce

Just execute the following sentence
`select '' as a from dual`

**Comment by LonwoLonwo** [comment]
Hello @jmsanzg 

Please provide more info about your issue. Video or images can be beneficial.

For now, I can't reproduce.

![2022-11-11 18_09_35-Window](https://user-images.githubusercontent.com/45152336/201368437-b069c4bb-148a-4b3f-8175-1b032b5e64da.png)

**Comment by jmsanzg** [comment]
Arrggg, sorry, please, remove the "as a". Just execute:

`select '' from dual`

I'm really sorry. Also, it doesn't happen with numbers, just with strings

**Comment by LonwoLonwo** [comment]
I can do that too.

![2022-11-13 11_29_24-Window](https://user-images.githubusercontent.com/45152336/201512928-b1d63edc-5774-438e-97fb-794f4e628de0.png)

Please provide images, gifs, or videos of your issue.

**Comment by jmsanzg** [comment]
When I execute the query then the editor doesn't show the results and, for instance, I can no longer use CTRL+ENTER to execute a query.
![image](https://user-images.githubusercontent.com/768253/201610990-5320fe4b-7dd0-4ead-9db4-b4c972a61c97.png)

If I set a column name to that field then I get a valid result and the editor allows me to continue working using CTRL+ENTER
![image](https://user-images.githubusercontent.com/768253/201611283-ab179560-8983-4437-84e1-ed22a8f301de.png)

**Comment by ShadelessFox** [comment]
Hello @jmsanzg,

Can you please send the log files? You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by jmsanzg** [comment]
Log file after executing the query: [18193.log](https://github.com/dbeaver/dbeaver/files/10001953/18193.log)

**Comment by ShadelessFox** [comment]
The issue was fixed in #17719 and the fix is available in DBeaver 22.2.2.

Please upgrade to a newer version and let me know if your issue was solved.

**Comment by jmsanzg** [comment]
Fixed from that version. Next time I'll try to search better. Thank you!
