### ISSUE TITLE
Wrong Geography Point with SQLServer

### ISSUE THREAD

**Issue by fnicastri** [dbeaver/dbeaver#18196]
### Description

```
Version 22.2.4.202211061524
OS: Mac OS 12.6.1
SQLServer: 2019 Linux
```

I have a table in SQLServer 2019 with geographical extensions.
The column Location is a Point.
When I open the table from the database and set Format -> Transform -> Geometry the result point is wrong.
`SELECT x.* FROM web.dbo.Csvs x` -> `POINT (0 119.51479153704105)`

In custom query where I can use STAsBinary() I get the right coordinates.
`SELECT Id, Location.STAsBinary() as Location FROM web.dbo.Csvs;` -> `POINT (-83.846884 38.016689)`

Is this a bug?
If not is there a way to set a default filter on the column?

Thanks

### DBeaver Version

22.2.4.202211061524 CE

### Operating System

Mac OS 12.6.1

### Database and driver

Database: SQLServer 2019 Linux
Driver: com.microsoft.sqlserver.jdbc.SQLServerDriver 11.2.1.jre8

**Comment by LonwoLonwo** [comment]
Hello @fnicastri 

Please provide a sample table DDL and sample data for this table.

**Comment by fnicastri** [comment]
I need permission to share anything from that project, I'll try

**Comment by E1izabeth** [comment]
@fnicastri 
It could be not exact that project's table ddl and/or data, just any minimum example to reproduce.

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
