### ISSUE TITLE
log file it's too big

### ISSUE THREAD

**Issue by 1013461195** [dbeaver/dbeaver#18205]
### Description

November 11th, my finish work to home. but work computer not shutdown. November 14 th, computer remind me space is not enough.
![截屏2022-11-14 上午10 05 04](https://user-images.githubusercontent.com/23392657/201560112-ee731ee7-c7b4-42bc-9cb7-e8544bd925cd.png)
![截屏2022-11-14 上午10 05 35](https://user-images.githubusercontent.com/23392657/201560145-ec5e03c0-c65c-4793-bf3f-9d0401971af9.png)
![截屏2022-11-14 上午10 05 46](https://user-images.githubusercontent.com/23392657/201560166-c19be95c-166c-4c97-8778-aa3bf98c8b6f.png)

### DBeaver Version

22.2.2.202210092258

### Operating System

macOS Bigsur 11.4

### Database and driver

mariadb

**Comment by LonwoLonwo** [comment]
Thanks for the report @1013461195 

We probably need to begin to limit the size of our debug-log file. 100 Mb can be enough. And we can add info about the size in the Preferences -> User Interface -> Error logs page
