### ISSUE TITLE
Firebird2Oracle default column type

### ISSUE THREAD

**Issue by cemyilmaz45** [dbeaver/dbeaver#1820]
Hi,
I am trying to convert DB tables and datas from Firebird to Oracle.
But, I have problems with table columb types.
For exp Oracle not support TIME columb type. Dbeaver match it with TIME so I have error Invalid datatypes.

Can I define default column type on Dbeaver ? May be txt files or config file ? Is It possible ?
INT > NUMBER
TIME > DATE
BITINT > NUMBER 
etc etc.

Thanks for your interest.

Cem.

Note : Sorry for English mistakes.

**Comment by mkgrgis** [comment]
https://github.com/dbeaver/dbeaver/issues/7745

**Comment by uslss** [comment]
obsolete
