### ISSUE TITLE
Add minimal system and library requirements

### ISSUE THREAD

**Issue by Destrolaric** [dbeaver/dbeaver#18209]
### Description

We don't have a DBeaver minimum library requirement in our wiki. This isn't nice for users with old software or hardware because they cannot know if DBeaver will launch on their system. We probably should at least add Linux software requirements for the client.

### DBeaver Version

Any version

### Operating System

Any OS

**Comment by miltonchirinos44** [comment]
@Destrolaric I agree with what you mentioned lately dbeaver has been making changes in his project which is affecting cloudbeaver's project,
this issue should be looked into

**Comment by arhayka** [comment]
We've already added the short info about system requirements to the product download pages.
For example:
- https://dbeaver.com/download/ultimate/
- https://dbeaver.io/download/#requirements

This could also be added to the installation description: https://dbeaver.com/docs/dbeaver/Installation/ or perhaps in a special article in wiki.
