### ISSUE TITLE
Duckdb config access

### ISSUE THREAD

**Issue by dominijk** [dbeaver/dbeaver#18202]
**Is your feature request related to a problem? Please describe.**
DuckDB has various config settings including access method (read only etc.), it would be good to have these in dbeaver. I'm using duckDB with Python and when you try to access the database in Dbeaver with python running you get an error due to file lock

**Describe the solution you'd like**
Same options to set a read only connection that are available in Postgres

**Describe alternatives you've considered**
Have attempted to access the config but unsure how to do so, this feature could be covered by an explanation on how to do this

**Additional context**
This question has been posed on [SO](https://stackoverflow.com/questions/74411716/set-read-only-connection-to-duckdb-in-dbeaver)

**Comment by LonwoLonwo** [comment]
Hello @dominijk 
Did you try to use this setting in the Connection Settings?

![2022-11-14 13_43_24-Window](https://user-images.githubusercontent.com/45152336/201640652-1a7a5ba1-902a-4272-a7e9-9bb5be4a00f9.png)

Or maybe this one in the toolbar?

![2022-11-14 13_43_54-Window](https://user-images.githubusercontent.com/45152336/201640663-08a4f817-9794-4c85-8917-fba404a0c67c.png)

**Comment by dominijk** [comment]
Thanks for that, i went back and set as read only but still get the same lock error on mine. I'm using DuckDB 0.6.0. My set up is:

1. Create db through python
2. Set python connection as read_write
3. Open dbeaver create new connection as read only
4. Returns error `IO Error: Could not set lock on file "/Users/Shared/duckdb/testduck.db": Resource temporarily unavailable`

**Comment by dominijk** [comment]
This can be closed as https://github.com/duckdb/duckdb/discussions/3096 
DuckDB (0.6.0) can be either
- single read-write 
- multiple read-only

**Comment by LonwoLonwo** [comment]
Thanks for the answer and investigation @dominijk
