### ISSUE TITLE
Can't parse Presto map(varchar, varchar)  format

### ISSUE THREAD

**Issue by pengwanli** [dbeaver/dbeaver#18220]
### Description

from version 21.3.0 , It can parse Presto map, can't parse Presto map(varchar, varchar). In version 21.2.5 it can parse Presto map and map(varchar, varchar), I see this data with entering F7   

### DBeaver Version

22.2.4

### Operating System

window 10

**Comment by LonwoLonwo** [comment]
Hello @pengwanli 

Please provide more info about your issue. Foto or video can be beneficial.

Also, could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by pengwanli** [comment]
Hello @LonwoLonwo 
# dbeaver-debug.log
> Can't fetch database data types: SQL 错误: Method DatabaseMetaData.getTypeInfo is not yet implemented
> Connected (presto_jdbc-17f52ccd401-754c2e2573bdc0f9, Presto JDBC Driver [1.0])
> Execution context opened (online-presto; SQLEditor <Script-3.sql>; 2)

# .log
>!ENTRY org.eclipse.ui 2 2 2022-11-15 16:55:49.634
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

> !ENTRY org.jkiss.dbeaver.model 2 0 2022-11-15 16:55:51.159
!MESSAGE Can't fetch database data types: SQL 错误: Method DatabaseMetaData.getTypeInfo is not yet implemented

# metaData
> type is  MAP(VARCHAR,VARCHAR)
> press F7 the key and value is null/empty

**Comment by LonwoLonwo** [comment]
Thanks.
But this is the cropped version. Could you please provide a complete log version?

Additionally, please provide more info about your database and driver.

**Comment by pengwanli** [comment]
# before
![image](https://user-images.githubusercontent.com/21196591/201878561-9471784a-e129-4d4d-ae0b-8b1a3e52478e.png)
![image](https://user-images.githubusercontent.com/21196591/201878853-f6402e74-d135-4f36-ad51-c6cc24018d62.png)

# now
![image](https://user-images.githubusercontent.com/21196591/201878639-bba1ff1d-2b94-43b2-b0a4-2a75cb05d069.png)

* presto version is 0.155
@LonwoLonwo

**Comment by pengwanli** [comment]
# .log
!SESSION 2022-11-15 17:16:24.426 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.ui 2 2 2022-11-15 17:16:28.866
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

!ENTRY org.jkiss.dbeaver.model 2 0 2022-11-15 17:16:30.444
!MESSAGE Can't fetch database data types: SQL 错误: Method DatabaseMetaData.getTypeInfo is not yet implemented

# dbeaver-debug.log
> Start 调试核心 [org.eclipse.debug.core 3.20.0.v20220811-0741]
2022-11-15 17:16:29.883 - Connect with 'online-presto' (presto_jdbc-17f52ccd401-754c2e2573bdc0f9)
> Start DBeaver Generic Plug-in [org.jkiss.dbeaver.ext.generic 2.3.179.202211061524]
2022-11-15 17:16:29.918 - Execution context opened (online-presto; Main; 0)
2022-11-15 17:16:30.258 - Execution context opened (online-presto; Metadata; 1)
2022-11-15 17:16:30.443 - Can't fetch database data types: SQL 错误: Method DatabaseMetaData.getTypeInfo is not yet implemented
2022-11-15 17:16:30.629 - Connected (presto_jdbc-17f52ccd401-754c2e2573bdc0f9, Presto JDBC Driver [1.0])
2022-11-15 17:16:30.648 - Execution context opened (online-presto; SQLEditor <Script-3.sql>; 2)

**Comment by ShadelessFox** [comment]
Hello @pengwanli,

Unfortunately, such small portions of logs are not suitable for us. Can you please send full logs, attached as files, instead?

Additionally, what database is used behind Presto?

**Comment by pengwanli** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10051947/dbeaver-debug.log)
 The Presto's database is  PrestoDB .
@ShadelessFox 
Maybe I think error is ' Method DatabaseMetaData.getTypeInfo is not yet implemented'

**Comment by E1izabeth** [comment]
Does it still actual for the latest Presto driver and on the latest DBeaver version?

**Comment by pengwanli** [comment]
> Does it still actual for the latest Presto driver and on the latest DBeaver version?

Now，I have  not  used  the  presto

**Comment by arhayka** [comment]
So, I close this issue. Feel free to reopen it if needed.
