### ISSUE TITLE
SSH credentials field is not properly resized

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#18221]
### Description

Changing SSH uthentication from Agent to password/key don't resize the window and text fields for credentials are missing
Workaround: Manually resize the window for at least 1 pixel and it will resize automatically.

### DBeaver Version

22.2.4

### Operating System

Win11

### Database and driver

Any

### Steps to reproduce

1. Create a cannoection with SSH tunnel that uses Agent for authentication
2. Save the connection
3. Open connection settings
4. In SSH settings change authentication from agent to public key or passphrase

**Expected:** Field is resized to include key and passphrase fields
**Actual:** The field looks like all text fields are missing

### Additional context
![dbeaver_hl2Pry74uS](https://user-images.githubusercontent.com/82543000/201862145-08c15756-d0ff-483c-b1b7-4728dbdb5f0d.gif)

_No response_

**Comment by serge-rider** [comment]
Fixed in another ticket in 22.2.5

**Comment by Matvey16** [comment]
Verified
