### ISSUE TITLE
[Feature request] Add the possibility to configure several character string delimiters

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#1823]
Hi,

In PostgreSQL, we have the ability to use $$ as a character string delimiter, in addition to the single quote.
This is very useful when we have a lot of character strings with quotes (espacially in french).
In DBeaver, I can use the $$ delimiter, but the automatic formating (and syntax coloration) is based the quotes, which means that if I have only one quote in the string, all the following characters and words are considered as part of the string, until the next quote. Autocompletion does not work, etc.

Is it possible to add the possibility to custom a list of quote delimiters (', $$, etc.) that the SQL editor will recognize?

Thanks in advance,

Cedric

**Comment by serge-rider** [comment]
Agreed.
Currently DBeaver recognizes $$ delimiters (generic form is `$term$`) only as block statements but not as string delimiters.

**Comment by kseniiaguzeeva** [comment]
Closed as non-actual.
