### ISSUE TITLE
Connection to Bigquery is failing

### ISSUE THREAD

**Issue by apurvc** [dbeaver/dbeaver#18239]
### Description

Bigquery connection has started failing with **PKIX path building failed** error 

### DBeaver Version

comunity 22.2.4 

### Operating System

Windows 10

### Database and driver

BigQuery Connection using https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.2.23.1027.zip (latest) or 
https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.2.21.1025.zip
is failing with below error 
[Simba][BigQueryJDBCDriver](100004) HttpTransport IO error : PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
  EXEC_JOB_EXECUTION_ERR

Not sure if this is related to

1. https://developers.google.com/identity/protocols/oauth2/resources/oob-migration
2.  https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html 

### Steps to reproduce

1. Install latest Dbeaver community edition.
2. Install/download latest bigquery driver. 
3. Try to establish a connection with any of the authentication method. 

### Additional context

It  works on Windows 11 :)

**Comment by LonwoLonwo** [comment]
Hello @apurvc 

Can you please try this advice? https://github.com/dbeaver/dbeaver/issues/18175#issuecomment-1310567139

**Comment by apurvc** [comment]
@LonwoLonwo  unfortunately above advice didn't work . 

What I have found is DbVisualizer and DbSchema also are having same issue even with latest simba  jdbc driver https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.2.23.1027.zip (Google BigQuery Driver). 

Only DataGrip which was recently updated the driver https://github.com/DataGrip/bigquery-jdbc-driver/releases is working at the moment, Not sure if they have made some fixes in the jdbc driver itself.

**Comment by LonwoLonwo** [comment]
Does the BigQuery connection work for you with the previous driver?

**Comment by apurvc** [comment]
@LonwoLonwo It did work with the old version of driver https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.2.21.1025.zip and I tested it still works. 
Probably the issue is with new drivers.

**Comment by LonwoLonwo** [comment]
Ok, thanks for the investigation. Will be waiting for the new driver version without the issue.

**Comment by apurvc** [comment]
@LonwoLonwo  just for update , I quickly tested all the drivers and not to much for a surprise all of them work . 
I have been thinking that it could be a Windows (10) issue as it was working fine on Win 11. Seems some updates on system happened last week and it all works now. 

Thanks!! for your support
