### ISSUE TITLE
Dbeaver not showing all SQL queries in session browser

### ISSUE THREAD

**Issue by ghiki** [dbeaver/dbeaver#18248]
### Description

When I go to session browser, some sessions not showing thew SQL queries from the session (this is specially useful for monitoring locks in database tables).
![imagen](https://user-images.githubusercontent.com/854302/202438669-0c1edbf6-4866-4ff4-8bf7-72cc2023b7b5.png)

But if I query with:
`SELECT SYSDATE,
vs.process         PID_OS,
vh.inst_id INST_BLOQUEANTE,
vh.sid SID_BLOQUEANTE,
vs.osuser OSUSER_BLOQUEANTE,
vs.username USER_BLOQUEANTE,
vs.machine MAQUINA_BLOQUEANTE,
vs.status ESTADO_BLOQUEANTE,
vs.program PROGRAMA_BLOQUEANTE,
vsq.sql_text SQL_BLOQUEANTE,
vw.inst_id INST_BLOQUEADA,
vw.sid SID_BLOQUEADA,
DECODE (     vh.request, 0, 'None', 1, 'NoLock', 2, 'Row-Share', 3, 'Row-Exclusive', 4, 'Share-Table', 5, 'Share-Row-Exclusive', 6, 'Exclusive', 'Nothing-') MODO_ESPERA,
DECODE ( vw.type, 'CF', 'Control File', 'DX', 'Distrted Transaction', 'FS', 'File Set', 'IR', 'Instance Recovery', 'IS', 'Instance State', 'IV', 'Libcache Invalidation', 'LS', 'LogStartORswitch', 'MR', 'Media Recovery', 'RT', 'Redo Thread', 'RW', 'Row Wait', 'SQ', 'Sequence #', 'ST', 'Diskspace Transaction', 'TE', 'Extend Table', 'TT', 'Temp Table', 'TX', 'Transaction', 'TM', 'Dml', 'UL', 'PLSQL User_lock', 'UN', 'User Name', 'Nothing-') TIPO_ESPERA,
vsw.osuser OSUSER_BLOQUEADA,
vsw.username USER_BLOQUEADA,
vsw.machine MAQUINA_BLOQUEADA,
vsw.program PROGRAMA_BLOQUEADA,
vsqw.sql_text SQL_BLOQUEADA
FROM gv$lock vh,
gv$lock vw,
gv$session vs,
gv$session vsw,
gv$sql vsq,
gv$sql vsqw
WHERE         vs.prev_sql_addr=vsq.address
and
vsw.sql_id=vsqw.sql_id
and vh.inst_id=vs.inst_id
and vw.inst_id=vsw.inst_id
and (vh.id1, vh.id2)
IN (SELECT id1, id2
FROM gv$lock
WHERE request = 0
INTERSECT
SELECT id1, id2
FROM gv$lock
WHERE lmode = 0)
AND vh.id1 = vw.id1
AND vh.id2 = vw.id2
AND vh.request = 0
AND vw.lmode = 0
AND vh.sid = vs.sid
AND vw.sid = vsw.sid;`

I can see the SQL from the session:
![imagen](https://user-images.githubusercontent.com/854302/202438991-2a5f6ac2-acc4-49f8-bda0-cb7c365c8340.png)

### DBeaver Version

Community 22.2.4

### Operating System

MS Windows 10

### Database and driver

Database: Oracle 10.2.0.5.0
Driver:Oracle jdbc 12.2.0.1 (latest integrated in dbeaver)

### Steps to reproduce

-Connect to oracle database
-Go to Administer>Blocks
-Go to Administer>Sessions
-Select any blocked session without SQL query text and annotate their SID
-Launch the SQL inside this comment, which queries to gv$sql view and it SHOWS the SQL text from the blocked session

**Comment by LonwoLonwo** [comment]
Hello @ghiki 

![2022-11-17 17_18_15-DBeaver Ultimate 22 2 5 - Sessions - orcl](https://user-images.githubusercontent.com/45152336/202470382-5bce8130-3cef-4d03-b41a-7030d5591001.png)

![2022-11-17 17_18_36-Window](https://user-images.githubusercontent.com/45152336/202470391-a4b3c7f9-0921-4d33-aa44-3d73d994ed13.png)

Hello @ghiki 
Did you try to check these buttons in the Session Manager?

**Comment by ghiki** [comment]
Yes, I can see the session (machine PID, DB SID, logon time, client...),
but not the SQL statement

**Comment by LonwoLonwo** [comment]
Ok. Any examples of disappeared SQL Queries? Do you see any patterns?

**Comment by ghiki** [comment]
For example, at this time in the session browser:
![imagen](https://user-images.githubusercontent.com/854302/202669655-b34e2397-e103-4cef-a431-8ad9e535c135.png)

And much more sessions without the query (it only shows in 3 of 53 active sql sessions)

**Comment by LonwoLonwo** [comment]
Ok. And what queries should be there instead of null?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
