### ISSUE TITLE
Show DB version in tooltip after connecting

### ISSUE THREAD

**Issue by yoni-yad2** [dbeaver/dbeaver#18243]
It would be useful to have the DB version showing in the connection tooltip after establishing a connection.

**Comment by LonwoLonwo** [comment]
Thanks for the idea

**Comment by LonwoLonwo** [comment]
Implemented.

![2022-11-17 14_53_23-DBeaver Ultimate 22 2 5 - Playlist](https://user-images.githubusercontent.com/45152336/202491242-25805acd-8962-4f93-ba19-8c3e47db0d61.png)

Will be available [here](https://dbeaver.io/) on 2022-12-05
