### ISSUE TITLE
SQL Beautifier

### ISSUE THREAD

**Issue by gpogliani** [dbeaver/dbeaver#1824]
I tried psti.exe because the formatter still looks a little poor.
I tried like you suggested in the post... nothing. It does nothing at all.
C:\tools\psti\psti.exe -i=${file} -o stdout
The tool psti itself works very well...
Any suggestion?

I'm on the latest version of dbeaver...

The best formatter ever is definitely the one of workbench/j

**Comment by serge-rider** [comment]
psti work fine in my test env.
Did you enable "Use temp file" option?

> The best formatter ever is definitely the one of workbench/j

Workbench/J is open-source (ASL2 - just like DBeaver), I can try to use their formatter (as an option) in DBeaver.

**Comment by jimpriest** [comment]
If we could have more native formatting options that would be great.  The problem with relying on third party tools is sometimes they are abandoned...

**Comment by dooferorg** [comment]
Yes!.. formatting in this program is horrible.

Why can I not specify that keywords should always be upper case, and field names should be as-is from the tables. This page is a joke: https://github.com/dbeaver/dbeaver/wiki/SQL-Formatting .. I don't want to uppsercase EVERYTHING, just my keywords.

Maybe I'm just too used to FormatSQL on SQLServer or MySQL Workbench

**Comment by serge-rider** [comment]
SQL formatting doesn't affect table/column names, only keywords.

**Comment by dooferorg** [comment]
Hmm.. when I did the 'to upper case' when editing a view it made everything uppercase.

**Comment by gpogliani** [comment]
Serge,

At least can you suggest a good external SQL formatter?

Workbench/J I think is one of the best tools  but dbeaver does the same things better … EXCEPT THE FORMATTING.

 

Thanks

**Comment by serge-rider** [comment]
@dooferorg "to upper case" does just this - converts everything to upper case. While SQL formatter (<kbd>ctrl+shift+f</kbd>) makes actual formatting (tabs, line feeds, indentations and keywords case conversion).

@gpogliani I'm thinking about adapting Workbench/J formatter. Perhaps as an external extension (similar to the Office integration). I'll contact with the author.

**Comment by dooferorg** [comment]
Ah, I was thinking I was telling the formatter that I wanted all keywords uppercased. I see now

**Comment by serge-rider** [comment]
SQL Workbench formatter (beta version) will be included in 5.2.2
