### ISSUE TITLE
Data Transfer output parameter variables malfunction when used more than once

### ISSUE THREAD

**Issue by ptebault** [dbeaver/dbeaver#18258]
### Description

The first variable that is mentioned, when used the second time, will apply the variable name as a string.

(Examples below were tested on 2022-11-17)

Example (in the output directory parameter)
/some/path/${year}/${year}-${month}/${year}-${month}-${day}

Will result in:
/some/path/2022/${year}-11/${year}-11-17
(Note that year is the first variable, and it works for the first instance. Note that month is the second variable, and it works for both instances.)

Or second example:
/some/path/2022/2022-${month}/${year}-${month}-${day}

Will result in:
/some/path/2022/2022-11/2022-${month}-17

The first instance of the first variable renders correctly. The subsequent instances of the first variable do not.
The subsequent variables work fine no matter how many times they are called.

### DBeaver Version

Community Edition 22.2.4

### Operating System

macOS Monterey 12.6

### Steps to reproduce

Export a query, on the Data Transfer / Output page, in the output directory, place

/some/path/${year}/${year}-${month}/${year}-${month}-${day}

Expected output: 
/some/path/2022/2022-11/2022-11-17

Actual output:
/some/path/2022/${year}-11/${year}-11-17

**Comment by ShadelessFox** [comment]
Thank you for your report.
