### ISSUE TITLE
Show Global Filter button does not show in community edition

### ISSUE THREAD

**Issue by jcrben** [dbeaver/dbeaver#18259]
### Description

Saw this in the documentation https://dbeaver.com/docs/wiki/Configure-Filters/
<img width="756" alt="image" src="https://user-images.githubusercontent.com/5614134/202527390-c54393b3-6750-4afb-a956-fa96a1dcac8f.png">

Meanwhile I see this on my Macbook - I gather from a screenshot online that it should be on the right of the Enable button.
<img width="458" alt="image" src="https://user-images.githubusercontent.com/5614134/202527466-9c447fdc-5225-4207-b83b-ad3c46571894.png">

Could a note be added about which versions this applies to so as to avoid any confusion?

### DBeaver Version

22.2.4

### Operating System

macOS Monterey 12.6

### Database and driver

DBeaver Sample Database (SQLite)

### Steps to reproduce

Install w/ sample
<img width="453" alt="image" src="https://user-images.githubusercontent.com/5614134/202527922-f6fa3a7e-feb9-46f7-8a68-357d495050f2.png">

See resulting image in main issue report

**Comment by ShadelessFox** [comment]
Hello @jcrben,

The `Configure ... filter` is what you are looking for.

Sorry for confusing you with outdated documentation. We will update it.

**Comment by LonwoLonwo** [comment]
Oh, this is a special, strange case for the SQLite and Firebird databases.
If you open this filter configuration dialog from any other database on the level of the tables - you will see this link.
 
![2022-11-23 22_32_44-DBeaver Ultimate 22 2 5 - film](https://user-images.githubusercontent.com/45152336/203633387-fef503ce-e07f-4bb3-8a2d-482ae0ce6bf3.png)

**Comment by LonwoLonwo** [comment]
And this is expected behavior because your table filters in the SQLite are already global for your datasource.
