### ISSUE TITLE
DBever tries to connect to wrong port

### ISSUE THREAD

**Issue by hawkdoc-mtp** [dbeaver/dbeaver#18252]
### Description

I thought this would be straight forward. Add the host: server\Instance
The port is automatically filled when SQL Server is selected : 1433

Add the database I want opened: DatabaseName

Drivers downloaded

Authentication. I'm trying AD Integrated but also created a Sql Server Authenticated user. Both give the same error.

Test Connection: "The TCP/IP
![DBeaver](https://user-images.githubusercontent.com/63544101/202463034-67040927-55fc-4eec-afa0-5460549e5cee.png)
 connection to the host cap-dev-sql, port 62189 has failed. Error: "connect timed out. Verify the connection properties."

Why is it trying to open port 62189?

Firewall is open for MSSQL ports. I connect with SSMS and .net apps. I verified tcp/ip settings.

### DBeaver Version

Version 22.2.4.202211061524

### Operating System

Windows 10 Enterprise

### Database and driver

SQL Server 2017
Driver: Microsoft JDBC Driver for SQL Server

### Steps to reproduce

1.  Add the host: server\Instance
2.  The port is automatically filled when SQL Server is selected : 1433
3.  Add the database I want opened: DatabaseName
4.  Authentication. I'm trying AD Integrated but also created a Sql Server Authenticated user. Both give the same error.

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10032058/dbeaver-debug.log)
[Copy.log](https://github.com/dbeaver/dbeaver/files/10032068/Copy.log)

**Comment by ShadelessFox** [comment]
Hello @hawkdoc-mtp,

Are you using SSH?

**Comment by hawkdoc-mtp** [comment]
No. Very straight forward connection on default port.

**Comment by hawkdoc-mtp** [comment]
Really? No one has any information about DBeaver trying to open a port that is different from the default on specified?

**Comment by ShadelessFox** [comment]
It might be something with the driver. We need to investigate this issue.

**Comment by ShadelessFox** [comment]
Just to minimize the scope of potential problems, have you changed any of the driver properties?

**Comment by hawkdoc-mtp** [comment]
I installed the app and was presented with a key requirement.

**Comment by ShadelessFox** [comment]
What if you change the port to some other value? Will the same value be shown upon connecting?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
