### ISSUE TITLE
INITCAP function in SAP HANA with syntax highlighting and intellisence

### ISSUE THREAD

**Issue by hski-github** [dbeaver/dbeaver#18263]
I noticed is, that the INITCAP function in SAP HANA is not part of syntax highlighting resp. intellisence

![image](https://user-images.githubusercontent.com/1921015/202690360-1d1ca6d2-e8bf-488d-b887-a8ca57648975.png)

See INITCAP function definition for SAP HANA 
https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/d1e67902534d426180459ae45a264667.html

**Comment by LonwoLonwo** [comment]
Thanks for the idea @hski-github 

As I can see, many functions DBeaver doesn't support.

![2022-11-22 19_36_04-DBeaver Ultimate 22 2 5 - _localhost 5_ Script-76](https://user-images.githubusercontent.com/45152336/203370384-0069d65b-1603-4a7a-bbdc-1b2fa9c25e5f.png)

![2022-11-22 19_36_25-DBeaver Ultimate 22 2 5 - _localhost 5_ Script-76](https://user-images.githubusercontent.com/45152336/203370386-8080e79d-68f9-4656-99a2-eb8bb51bded8.png)

**Comment by hski-github** [comment]
Thank you very much! Looking forward to the next release. :-)
