### ISSUE TITLE
Statistics is not available when executing multiple queries as one

### ISSUE THREAD

**Issue by divsri** [dbeaver/dbeaver#18262]
### Description

I am connecting to PostgreSQL DB using DBEAVER. During execution of Query i want to capture the timing of execution execution. How this can be achieved in DBEAVER.

### DBeaver Version

22.2.4.202211061524

### Operating System

Windows

### Database and driver

PostgreSQL Database

**Comment by LonwoLonwo** [comment]
Hello @divsri 

If you have a SELECT statement - you can look on the right side of the lower toolbar.

![2022-11-21 11_33_15-DBeaver Enterprise 22 2 5 - _MySQL 5 5_ Script-83](https://user-images.githubusercontent.com/45152336/203003219-05f0693c-550d-4b90-9a7e-80faf668fbcd.png)

Or you can open the [Query manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager). The query manager has the "Duration" column.

![2022-11-21 11_33_53-DBeaver Enterprise 22 2 5 - _MySQL 5 5_ Script-83](https://user-images.githubusercontent.com/45152336/203003736-65a1b6d8-4102-416e-8832-1bc0617b27d4.png)

**Comment by LorisZ** [comment]
Can confirm as well, previously you would see the duration of the query, now it only works for selects and **only** single selects. As soon as you execute a query that does not return a result or multiple selects, you don't see the duration anymore.

Pretty sure this is a regression, as it previously behaved differently, I think the Bug label is appropriate. The Query Manager workaround works, but is not really satisfying.

I'm using PostgreSQL as well.

**Comment by E1izabeth** [comment]
If you change the following setting to `Always` you can see statistics tab after any queries execution.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/68e2a96e-2601-45d1-9652-cc7eb747114e)

![image](https://github.com/dbeaver/dbeaver/assets/28875055/6f8bd84d-4bbe-4f6f-bfa6-b67a306253bc)

Is it what are you looking for?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
