### ISSUE TITLE
Enable sort indicator in Result set only if sorted

### ISSUE THREAD

**Issue by rythym05** [dbeaver/dbeaver#1827]
Can the up/down sort indicator be displayed only if a column is sorted. Having them always displayed uses up the horizontal column space.
Also displaying a up or down only when sorted help to better identify the columns when sorted. This is just like in excel while sorting

**Comment by serge-rider** [comment]
There should be a hint telling user that it is possible to click on sort icon. I don't see how it is possible without this icon. Note that clicking on column itself just selects cell values and doesn't change sorting (it is like in Excel).
Do you have any good example of existing applications with this UI? 
Screenshot would be very useful.
