### ISSUE TITLE
pg_restore Error: could not execute query: ERROR:  cannot execute CREATE INDEX in a read-only transaction

### ISSUE THREAD

**Issue by anita970120** [dbeaver/dbeaver#18276]
### Description

One database in the server turned into a read-only transaction when I was trying to restore some sql files on this server and the back-up files are failed to be restored. 
[restore_geogrid.txt](https://github.com/dbeaver/dbeaver/files/10054609/restore_geogrid.txt)

### DBeaver Version

Version 22.2.1

### Operating System

Windows Server 2016 Datacenter

### Database and driver

1.Database and name version: PostgreSQL 12
2.Driver name and version: postgresql-42.2.5, postgis-jdbc-2.5.0, postgis-geometry-2.5.0, postgis-jdbc-jtsparser-2.5.0

![image](https://user-images.githubusercontent.com/116291008/202999604-59c8ac33-0885-4dc7-9c67-27652819816b.png)

### Steps to reproduce

1. I use the back-up tool to create the back-up files from a database of another server
2. I use the restore tool to import the back-up files into the current server. 
3. After the operation, creating INDEX of each table in the schema failed due to the error :"cannot execute CREATE INDEX in a read-only transaction"

**Comment by LonwoLonwo** [comment]
Hello @anita970120 

It is not clear for now.

In the attached file, you have an error:

```
pg_restore: error: could not execute query: ERROR:  schema "geo_grid" already exists
Command was: CREATE SCHEMA geo_grid;
```

But in the steps you have:

`cannot execute CREATE INDEX in a read-only transaction`

What is your main problem?

![2022-11-21 12_35_57-DBeaver Enterprise 22 2 5 - try_table](https://user-images.githubusercontent.com/45152336/203016328-1f9323d5-425e-4714-a4ef-c41f93aeaf2a.png)

Also, can you please check this button for the connection with this problem?

**Comment by anita970120** [comment]
Hi,
the main problem is "cannot execute CREATE INDEX in a read-only transaction", which is also written in the attached file. 
The button is always set as unlocked.

**Comment by LonwoLonwo** [comment]
Can you please check this statement?

`SELECT pg_is_in_recovery()`

true -> Database has only Read Access
false -> Database has full Access

**Comment by LonwoLonwo** [comment]
Also, this discussion can be helpful https://stackoverflow.com/questions/31186414/error-cannot-execute-create-table-in-a-read-only-transaction

**Comment by anita970120** [comment]
> Can you please check this statement?
> 
> `SELECT pg_is_in_recovery()`
> 
> true -> Database has only Read Access false -> Database has full Access

I checked it, the result shows false. However, within the restore process, the database changed into read-only mode automatically. Now the situation is, the data in the table was restored, but the indexes were empty. Is that possible that I create the indexes manually for the restored data?

**Comment by anita970120** [comment]
Hi @LonwoLonwo ,

I think I found the problem. The storage of my server is full, so it turns into the read-only mode. Let's see whether the problem could be solved after the storage size is enhanced. 

Thanks for you support anyways.

**Comment by LonwoLonwo** [comment]
Any time. I will wait for your answer about storage enhancement.

**Comment by anita970120** [comment]
Hi @LonwoLonwo ,
after implementing the storage enhancement, the restore went successfully.

**Comment by LonwoLonwo** [comment]
Thanks for the answer @anita970120 

I'm closing this ticket because we can do something in this situation from DBeaver's side.
