### ISSUE TITLE
Return the  button "execute SQL in new tab"

### ISSUE THREAD

**Issue by mopsik10** [dbeaver/dbeaver#18275]
Please bring back the "execute SQL in new tab" button.
Sometimes you need to run several scripts quickly and compare the result. Without this button it is very inconvenient.
![image](https://user-images.githubusercontent.com/69254183/202996486-aaa6c9e6-d154-438f-b4a8-bed45f1183bb.png)
Button disappeared in version 22.2.5.202211202223

**Comment by E1izabeth** [comment]
This command is still available through context menu

![image](https://user-images.githubusercontent.com/28875055/203057672-b57f87ee-4ffd-4d3f-9f8f-3c90deb82ab9.png)


or by shortcut 
![image](https://user-images.githubusercontent.com/28875055/203057416-68568aaa-a2bf-4a82-b6d3-b21b7b2dd821.png)

**Comment by D-750** [comment]
Please bring back the button!
There is space enough in the vertical bar..

**Comment by serge-rider** [comment]
Yes, we have space for it but too many buttons confuse people.
For experienced users there are shortcuts and context menus.

However, maybe we could make it configurable..

**Comment by D-750** [comment]
Yes, I do use the shortcut now however I prefer to make it configurable.

**Comment by serge-rider** [comment]
Further improvements will be implemented in #18300

Fix in `devel`.

**Comment by NHYurdd** [comment]
Yes, please bring back this run SQL in new tab button.  Having it buried in a configuration setting is confusing for basic users.

**Comment by uslss** [comment]
verified.
Fix will be available in 22.3.0 (December 4, 2022)

**Comment by wallygator470** [comment]
The bigger question is why did you think removing it was the right thing to do?  it has been there forever and NOW you decide to remove it?  This is not how you maintain software.  You push out releases very often and then you do something like this that removes functionality to those of us that have used this tool are used to.  In the future please think about the people.

**Comment by mopsik10** [comment]
Hurrah. Button is back. Thank you.

**Comment by D-750** [comment]
Thank you for bringing back the button!
