### ISSUE TITLE
Unable to set result fetch size in 22.2.5

### ISSUE THREAD

**Issue by DamijanD** [dbeaver/dbeaver#18274]
### Description

Unable to set result fetch size in 22.2.5
![image](https://user-images.githubusercontent.com/44526436/202967406-eb3a24cf-7375-4c3f-9047-1b58ff7a27ea.png)
Before it was like:
![image](https://user-images.githubusercontent.com/44526436/202967459-e4984e57-0f24-48bf-94dd-739da037d3b0.png)

Maybe there is a setting somewhere but I can't find it - anyway this possibility to set fetch size on the fly is very important and handy to me.

### DBeaver Version

CE 22.2.5

### Operating System

win 10

### Steps to reproduce

Just select on table with more than 200 rows

**Comment by LonwoLonwo** [comment]
Hello @DamijanD 

What database do you use?

**Comment by DamijanD** [comment]
This was tested with oracle (jdbc)

**Comment by LonwoLonwo** [comment]
![2022-11-21 11_04_40-DBeaver Enterprise 22 2 5 - _MySQL 5 5_ Script-83](https://user-images.githubusercontent.com/45152336/202996789-07bf9254-2f62-4913-bb6d-ea46edb5def2.png)

You can use the "Configure" button to go to the preferences.

**Comment by DamijanD** [comment]
Yes I can -  but I don't know if this is by design or it is a bug that this option is now removed from status bar. Anyway in my humble opinion this was very useful to have it here where you need it and (if this is by design) I would say that this change is step back

**Comment by Gabriel-Voyager** [comment]
Also for me this change is a step back, i usually change the fetch size many times at once executing query.
I ve to return to the 22.2.3

**Comment by apdma** [comment]
Agree. 
I'm used to changing the number of fetch with one click. Now need to go somewhere else to do this.
Also, I think it's UI bug because of this
![image](https://user-images.githubusercontent.com/91953047/203080874-fc63ba5e-8842-449e-ab95-9a2aca265561.png)

**Comment by artemiuss** [comment]
In addition, the "Fetch All" button has now disappeared. I'm disappointed.

**Comment by D-750** [comment]
please bring back the 'fetch' buttons!

**Comment by LonwoLonwo** [comment]
Hello everyone. You can vote with any emoji on the main topic to help us understand - that this feature was essential for you.

**Comment by marc-hawke** [comment]
> 

I use the FetchAll hundreds of times a day.   I found it nested in the Navigate menu (doesn't seem like navigation..shouldn't it be data? or even 'sql editor')  and that told me the hot-key, but it still seems like a button worth having.  They could just have it be tied to the 'count rows' button that's there.   Clicking it again would fetch the rows it just counted.  ;)

**Comment by qilinsanshao** [comment]
please bring back the 'fetch' buttons!

**Comment by Olga-B** [comment]
The disappearance of fetch all is incredibly annoying. definitely going to revert to the previous version until this is addressed.

**Comment by D-750** [comment]
Thank you for bringing back the button fetch all rows!
