### ISSUE TITLE
The problem of Chinese translation

### ISSUE THREAD

**Issue by duzhaofa** [dbeaver/dbeaver#18273]
### Description

Right click on the opening tab, [close all] option should be called [全部关闭], but now is [关闭关闭]。

### DBeaver Version

DBeaver Community 22.2.5

### Operating System

Windows 11

**Comment by Destrolaric** [comment]
![image](https://user-images.githubusercontent.com/20579256/202998630-40edef6f-23cb-43ca-9c0e-3e18482b7215.png)
I agree. It looks weird.

**Comment by LonwoLonwo** [comment]
Hello @duzhaofa 

Thanks for the bug report. This ticket is a duplicate of https://github.com/dbeaver/dbeaver/issues/17697

You can read more info about his problem there.
