### ISSUE TITLE
Start DBeaver on installer close.

### ISSUE THREAD

**Issue by rburke-orthofi** [dbeaver/dbeaver#18289]
**Is your feature request related to a problem? Please describe.**
I open DBeaver, do an upgrade, then it doesn't reopen. If I open DBeaver I'm more than likely wanting to use it, not just upgrade it.

**Describe the solution you'd like**
A checkbox (pre-checked) indicating I want DBeaver to run after installer is closed.

Many applications work like this.

**Comment by ShadelessFox** [comment]
Hello @rburke-orthofi,

Thank you for your request.

What is your OS?

**Comment by E1izabeth** [comment]
This issue looks like a duplicate of #17878
