### ISSUE TITLE
22.5 changes

### ISSUE THREAD

**Issue by hrbruen** [dbeaver/dbeaver#18290]
Just some feedback.

~Query Editor - Top and bottom action toolbars were redesigned  - why? Why muck around with things that worked. Where is the button to run the query and output it to a new tab? "Pin"ing the tabs is very sub-optimal. How can I get it to go back the way it was?~

Property editors (all of them). 2 years on and there is still not enough room in the editors to allow me to view and edit the Comment without continuously having to go keyboard->mouse->keyboard->keyboard.... The Property editors  all look and act like they were designed by a commitee.

**Comment by uslss** [comment]
#18275

**Comment by ShadelessFox** [comment]
Hello @hrbruen,

Can you please show footage showing the second issue?

**Comment by hrbruen** [comment]
#10204

**Comment by ShadelessFox** [comment]
Oh, see.

What about your point regarding the navigation issue? Can you elaborate?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
