### ISSUE TITLE
Wrong PG timestamp type code generation

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#18294]
### Description

I opened (working) function and I see code:

create or replace function repl_log.repl_log_start (
  p_entity          text,
  p_d_period_start  timestamp default null without time zone,
  p_d_period_end    timestamp default null without time zone,

....

So I guess that function header was generated by DBEaver and the type should be:

timestamp without time zone default null

instead of:

timestamp default null without time zone

### DBeaver Version

CE  22.2.5.202211201741

### Operating System

win

### Database and driver

PG 14

**Comment by LonwoLonwo** [comment]
Hello @plotn 

Can you please provide the full function DDL example for the tests?

**Comment by LonwoLonwo** [comment]
DBeaver reads functions DDL differently, but usually, it just does 

`SELECT pg_get_functiondef(<objectId>);`

https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreProcedure.java#L421

**Comment by plotn** [comment]
create or replace function repl_log.repl_log_start (
  p_entity          text,
  p_d_period_start  timestamp default null without time zone,
  p_d_period_end    timestamp default null without time zone,
  p_comment_text    text      default null,
  p_entity_modifier text      default null,
  p_sql_err_code    text      default null,
  p_sql_err_message text      default null,
  p_snapshot_id     bigint    default null
)
  returns bigint
  language plpgsql
as $function$
declare
  l_d_period_start timestamp := p_d_period_start;
  l_id_log integer;
  l_sql text;
begin
  select id
    into l_id_log
    from dblink('dbname=' || current_database(),
                format('insert into repl_log.repl_log_data
                          (entity, d_period_start, d_period_end, comment_text, 
						   entity_modifier, sql_err_code, sql_err_message, snapshot_id)
                        values
                          (%1$L::repl_log.t_log_entity, %2$L::timestamp, %3$L::timestamp, %4$L, 
                           %5$L, %6$L, %7$L, %8$L)
                        returning id',
                       p_entity, l_d_period_start, p_d_period_end, p_comment_text, 
                       p_entity_modifier, p_sql_err_code, p_sql_err_message, p_snapshot_id)
                  ) as t(id int8);

  return l_id_log;
end;
$function$;

alter function repl_log.repl_log_start (text, timestamp, timestamp, text, text, text, text, bigint) owner to sysmcs;

**Comment by plotn** [comment]
SELECT pg_get_functiondef(<objectId>) returns:

CREATE OR REPLACE FUNCTION repl_log.repl_log_start(p_entity text, p_d_period_start timestamp without time zone DEFAULT NULL::timestamp without time zone, p_d_period_end timestamp without time zone DEFAULT NULL::timestamp without time zone, p_comment_text text DEFAULT NULL::text, p_entity_modifier text DEFAULT NULL::text, p_sql_err_code text DEFAULT NULL::text, p_sql_err_message text DEFAULT NULL::text, p_snapshot_id bigint DEFAULT NULL::bigint)

**Comment by plotn** [comment]
Sorry!!!!
This is our fork of DBeaver, the error is inside it.

**Comment by LonwoLonwo** [comment]
Ok :)
