### ISSUE TITLE
Fetch all button missing from UI

### ISSUE THREAD

**Issue by pkExec** [dbeaver/dbeaver#18295]
### Description

There used to be a button in the bottom toolbar "Fetch all rows", as per the documentation:
https://dbeaver.com/docs/wiki/Navigation/#data-rows

This button has disappeared. I can only find the related command in the "Navigate" menu.

### DBeaver Version

Community Edition 22.2.5.202211202223

### Operating System

Windows 10 64bit

### Database and driver

PostgreSQL 11

**Comment by E1izabeth** [comment]
It's a duplicate of #18274
Please, see the discussion there.
