### ISSUE TITLE
Button to load all records from result set is gone

### ISSUE THREAD

**Issue by codearoo** [dbeaver/dbeaver#18301]
Before one of the most recent changes, there was a button at the bottom of a query result set that you could press to load all the records. Now it's been replaced with a button the CALCULATE how many records (which is nice), but the ability to load all the result set seems to be gone!

**Comment by NHYurdd** [comment]
Having the same issue with v22.2.5.   The Load All Records button is gone.

**Comment by ShadelessFox** [comment]
Fixed in #18274, it will be available with the next release.
