### ISSUE TITLE
Intalled, but won't open

### ISSUE THREAD

**Issue by ThePnut** [dbeaver/dbeaver#18306]
### Description

I've installed this for the first time, but it will not run.
Also, If I try to uninstall it, I get this error NSIS ERROR: Error launching installer

Error Log Attatched
[1669192683350.log](https://github.com/dbeaver/dbeaver/files/10073899/1669192683350.log)

### DBeaver Version

22.2.25

### Operating System

Windows 10

**Comment by LonwoLonwo** [comment]
Hello @ThePnut 

`C:\Users\701438393\.swt\lib\win32\x86_64\swt-win32-4954r7.dll: Your organization used Device Guard to block this app. Contact your support person for more info`

Probably your problem is here? Seems to be some security restrictions on your machine.

**Comment by ThePnut** [comment]
Hi,
Could this be the only reason? Just asking as other members in my team have no problems using the App.
Anything to do with my Java? etc.

**Comment by ShadelessFox** [comment]
It doesn't seem like there's something wrong with your Java installation but with your Windows.

It has nothing to do with DBeaver, and we can't help, sorry.

Please contact your system administrator.
