### ISSUE TITLE
Can't install PostgreSQL drivers after clean Windows 10 reinstallation

### ISSUE THREAD

**Issue by inliquid** [dbeaver/dbeaver#18309]
### Description

This is first time I encounter such a problem. I installed DBeaver many times and never seen this before. 
It's Windows 10 clean install with just a couple of tools including Docker and DBeaver. After configuring some quick connection to local PostgreSQL DB, DBeaver was unable to fetch PostgreSQL drivers:

```
Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

![изображение](https://user-images.githubusercontent.com/6797881/203548843-48e0884b-5777-4c37-9894-4d8847e9ba47.png)

 
Network is absolutely fine, it's working, all other applications work normally. Tried with and without VPN.

dbeaver.ini:
```
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.nio=ALL-UNNAMED
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-Ddbeaver.distribution.type=exe
```

### DBeaver Version

Community Edition 22.2.5.202211202223

### Operating System

Windows 10 22H2

### Database and driver

PostgreSQL

**Comment by E1izabeth** [comment]
Could you try switching the preference `Use Windows truststore` off and restart DBeaver?
![image](https://user-images.githubusercontent.com/28875055/203551141-6d4af2aa-d68c-4945-93f8-62de21dddeee.png)

**Comment by inliquid** [comment]
@E1izabeth thanks, that helped. Is it supposed to be disabled? If so why it's enabled by default?

I just checked another Windows 10 machine and it has "Use Windows trust store" enabled, and everything seems to work fine. Configuration of the system is pretty much the same as well as internet connection.

**Comment by E1izabeth** [comment]
It's enabled by default.
We are not sure why this issue happens on one machines and everything is works on another yet. Besides that, some users has another issues when it's disabled, so, it's not planned to disable it by default now.
We are observing this issue now, maybe we will disable it by default in future.

**Comment by inliquid** [comment]
Not sure if this is connected, but I also start seeing these errors when trying to perform some trivial actions like creating a role:
![изображение](https://user-images.githubusercontent.com/6797881/203592024-7e19dd86-5fae-4cd4-977d-dac8e6b6bd5c.png)

**Comment by LonwoLonwo** [comment]
Ups. That's mine.

**Comment by uslss** [comment]
> Not sure if this is connected, but I also start seeing these errors when trying to perform some trivial actions like creating a role: ![изображение](https://user-images.githubusercontent.com/6797881/203592024-7e19dd86-5fae-4cd4-977d-dac8e6b6bd5c.png)

already fixed in #18314

**Comment by SalaryTheft** [comment]
I've encountered same issue with fresh Windows 10 installation.   
Tried with bundled JRE and Amazon Corretto 17, but no luck.

![image](https://user-images.githubusercontent.com/72844671/205899987-24611dfd-87f0-4089-a615-03531b5cf962.png)


dbeaver.ini
```ini
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.nio=ALL-UNNAMED
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-Ddbeaver.distribution.type=exe
```

**Comment by Kaique-Apolinario** [comment]
> Could you try switching the preference `Use Windows truststore` off and restart DBeaver? ![image](https://user-images.githubusercontent.com/28875055/203551141-6d4af2aa-d68c-4945-93f8-62de21dddeee.png)

just had " _Can't create driver instance (class 'org.postgresql.Driver'). Error creating driver 'PostgreSQL' instance. Most likely required jar files are missing. You should configure jars in driver settings. Reason: can't load driver class 'org.postgresql.Driver' Error creating driver 'PostgreSQL' instance. Most likely required jar files are missing. You should configure jars in driver settings. Reason: can't load driver class 'org.postgresql.Driver' org.postgresql.Driver org.postgresql.Driver_ "

and 

"_ maven artifact 'org.postgresql:postgresql:release' cannot be resolved in external repositores dbeaver _"

And it worked as soon as I disabled this Windows trust thing. Thanks!!
