### ISSUE TITLE
Configure SQL editor toolbar

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#18300]
We want to have customization of SQL editor toolbar.
Additional actins like "Execute in new script", "Export from query" and other may be placed on the vertical toolbar.

By default only execute, execute script and explain plan should be visible.

**Comment by E1izabeth** [comment]
It should be possible to modify the left-side toolbar of SQL Editor with predefined commands that we have.
- add new command to the toolbar
- delete command from the toolbar

Commands are the followings:
- Execute SQL Statement (visible by default)
- Execute SQL Statement in a new tab
- Execute SQL Script (visible by default)
- Execute Statements in Separate tabs
- Cancel active query
- Export from query
- Explain Execution Plan  (visible by default)
- Load Execution plan
- SQL Terminal
- Open AI
- Show server output console
- Show SQL Execution log
- Show active SQL variables
