### ISSUE TITLE
Sql keyword `into` is not suggested after `insert`

### ISSUE THREAD

**Issue by DoctorKrolic** [dbeaver/dbeaver#18316]
### Description

`INSERT INTO ...` is a common well-known sql construct that doesn't depend on any specific sql dialect. However, dbeaver doesn't suggest `INTO` completion after `INSERT` when typing

### DBeaver Version

Community Edition 22.2.5

### Operating System

Windows 11 22H2

### Database and driver

PostgreSQL 14.5

### Steps to reproduce

1. Open SQL editor
2. Type `insert`
3. Type space and invoke completion list

**Expected behaviour:**
`into` is in the completion list and I can just hit `Tab` or `Enter` to insert it

**Actual behaviour:**
Suggested completion list is empty:
![dbeaver_k6SMVKSiLL](https://user-images.githubusercontent.com/70431552/203608611-17712a5f-75b8-4ff2-bf34-eddfd397e81c.png)

**Comment by LonwoLonwo** [comment]
Thanks for the suggestion.

**Comment by serge-rider** [comment]
Fixed
