### ISSUE TITLE
Can't create role with GUI

### ISSUE THREAD

**Issue by inliquid** [dbeaver/dbeaver#18314]
### Description

With recent updates creation of any additional role on PostgreSQL start throwing an error:

![изображение](https://user-images.githubusercontent.com/6797881/203599811-596f125c-7137-4af0-a8e7-1b18c105f495.png)

### DBeaver Version

Community Edition 22.2.5.202211202223

### Operating System

Windows 10 22H2

**Comment by LonwoLonwo** [comment]
Thanks for the bug report.

**Comment by LonwoLonwo** [comment]
Fixed.
Will be available [here](https://dbeaver.io/) on 2022-12-05
