### ISSUE TITLE
Postgres Foreign Key - Not using primary key without using console commands

### ISSUE THREAD

**Issue by huths0lo** [dbeaver/dbeaver#18313]
### Description

I have a table that uses a dual column unique row.  (i.e. ALTER TABLE someTable ADD UNIQUE (col1, col2)).  Now that this unique row constraint exists, if I try to set a foreign key that uses this table, its defaulting to the unique key, instead of the primary key "id".  The GUI wont let me change it, so I instead am copying the commands it generates, and then going to the console, modifying it so it uses id, and then executing.

### DBeaver Version

Community Edition 22.2.4.202211061524

### Operating System

Windows 11 22H2

### Database and driver

PostgreSQL 14.5
PostgreSQL JDBC Driver

### Steps to reproduce

1. Create a primary key of ID on table.
2. Create unique key using two or more columns on same table.
3. Create a foreign key that references the first table from a different table.

**Comment by LonwoLonwo** [comment]
Hello @huths0lo 
Can't reproduce it for now.
Can you provide table examples please?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
