### ISSUE TITLE
New feature idea for "content viewer setting"

### ISSUE THREAD

**Issue by ffblanch** [dbeaver/dbeaver#1831]
Hi Serge !
New feature idea for CLOB "content viewer setting".  Add new json format type. 

Binary
Text
XML
json **new

Thanks !

**Comment by serge-rider** [comment]
JSON format is already supported (but only in EE version because originally it was made for MongoDB).
Probably I'll move it to CE at some moment.

**Comment by ffblanch** [comment]
This will be very appreciate
Thanks Serge

**Comment by mirkobrankovic** [comment]
This is a very useful feature for json fields, I would like to see it in CE version also :)

**Comment by ehosca** [comment]
+1
