### ISSUE TITLE
Missing "Fetch next page of results" and "Maximum result-set size" in data editor toolbar

### ISSUE THREAD

**Issue by WEGFan** [dbeaver/dbeaver#18329]
### Description

They exist in 22.2.3, is the removal intended?

22.2.3:
![](https://user-images.githubusercontent.com/7558201/203930764-723e88ac-11f5-4a1e-b3ea-245d2943e12f.png)

22.2.4 & 22.2.5：
![](https://user-images.githubusercontent.com/7558201/203930846-fa753cea-fec4-46c4-a164-fb8a4e4fa117.png)

### DBeaver Version

Community Edition 22.2.4 & 22.2.5

### Operating System

Windows 10

### Database and driver

- Database: MySQL 5.7.34
- Driver: MySQL Connector 8.0.29

### Steps to reproduce

1. Reset UI settings & workspace state
2. Open a database table

**Comment by uslss** [comment]
thanks for the report.
was fixed in #18274 
Close this issue as a duplicate

**Comment by hchau630** [comment]
I still don't see the "Fetch next page of results" button in 23.3.3, only the "Fetch all data" button. Is that intended?
