### ISSUE TITLE
SQLite: "open with" DBeaver

### ISSUE THREAD

**Issue by nmoreaud** [dbeaver/dbeaver#18323]
I would like to be able to open SQLite files easily by setting Windows "open with" setting to DBeaver.exe.
Currently it opens a DBeaver window having an open query tab with binary content.

**Comment by ShadelessFox** [comment]
Hello @nmoreaud,

Thanks for the feature request.

Duplicate of https://github.com/dbeaver/dbeaver/issues/15395
