### ISSUE TITLE
Work with unreacheble host is very slow

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#18327]
### Description

during operation, one of the hosts with the database becomes unavailable. I don't know about it. I click on the object of this database in the object tree and the program freezes.

why not do a very simple check on the availability of the host with the database? For example, elementary ping and give an error without allowing freezes

### DBeaver Version

community edition 22.2.5

### Operating System

windows 11 64bit

### Database and driver

postgresql 14
last drivers jdbc

### Steps to reproduce

1. add 2-4 hosts with database
2. execute any SQL command on hosts
3. shut down any host
4. enter to table of database on this host 

Dbeaver freeze by 1-2 minutes, then he trying to open this table and Dbeaver starts to slow down
![image](https://user-images.githubusercontent.com/61137576/203903678-06a7fa5f-7fea-4f2f-b5f5-a21830312fa5.png)

**Comment by Destrolaric** [comment]
@detkliff, Hi. Could you provide a video showing the issue?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
