### ISSUE TITLE
Postgres Export Error: type modifier is not allowed for type "text"

### ISSUE THREAD

**Issue by kyleflan** [dbeaver/dbeaver#1832]
When exporting from Postgres to Postgres, the text datatype is given a modifier (interpreted from the unknownLength driver setting). This causes an error in Postgres.

> Can't create target table:
> CREATE TABLE public.table_name (
> row_id serial NOT NULL,
> varchar_value varchar(256),
> comments text(2147483647),
> PRIMARY KEY (row_id)
> )
>   SQL Error [42601]: ERROR: type modifier is not allowed for type "text"
>   Position: XXX
>     org.postgresql.util.PSQLException: ERROR: type modifier is not allowed for type "text"
>   Position: XXX

This is fixed by editing the column mappings, which is how I've been getting around this for now. Additionally, setting unknownLength = 0 in the driver settings for the source table seems to alleviate this issue, too, but I'm not sure what other impact that might have in DBeaver.

**Comment by serge-rider** [comment]
Yep, cross-database type mapping has to be  improved.

**Comment by uslss** [comment]
cannot reproduce on 6.0.2

**Comment by JoshuaFlood** [comment]
Reproduced on 6.2.2 (MySQL remote server exported to PostgreSQL running on same remote server) @uslss @serge-rider :

```
Error starting data transfer
  Can't create target table:
CREATE TABLE public."2grams"(
	id int NOT NULL,
	frequency int NOT NULL,
	wordone varchar(255) NOT NULL,
	wordtwo varchar(255) NOT NULL,
	posone varchar(10) NOT NULL,
	postwo varchar(10) NOT NULL,
	lastupdated timestamp NOT NULL,
	lastviewed timestamp NOT NULL,
	description text(65535),
	wikilink varchar(2083),
	PRIMARY KEY (id)
)
  Can't create target table:
CREATE TABLE public."2grams"(
	id int NOT NULL,
	frequency int NOT NULL,
	wordone varchar(255) NOT NULL,
	wordtwo varchar(255) NOT NULL,
	posone varchar(10) NOT NULL,
	postwo varchar(10) NOT NULL,
	lastupdated timestamp NOT NULL,
	lastviewed timestamp NOT NULL,
	description text(65535),
	wikilink varchar(2083),
	PRIMARY KEY (id)
)
    SQL Error [42601]: ERROR: type modifier is not allowed for type "text"
  Position: 276
    SQL Error [42601]: ERROR: type modifier is not allowed for type "text"
  Position: 276
      ERROR: type modifier is not allowed for type "text"
  Position: 276
      ERROR: type modifier is not allowed for type "text"
  Position: 276
```
