### ISSUE TITLE
The fetch all rows button is "missing" in the latest version

### ISSUE THREAD

**Issue by LordMilutin** [dbeaver/dbeaver#18333]
### Description

The fetch all rows button is "missing", please add it back or at least make it customizable so that we can choose if we want to put it in the toolbar or not.

### DBeaver Version

Community Edition 22.2.5.202211202223

**Comment by Alexandr-Kislov** [comment]
Faced the same problem. Please return the button back it is needed very often.
@LordMilutin as a temporary solution you can use a hotkey Ctrl+Shift+=

**Comment by stegus64** [comment]
I have the same problem

**Comment by LonwoLonwo** [comment]
Fixed here: #18274

Fix will be available in DBeaver 22.3.0

Closed as duplicate
