### ISSUE TITLE
Procedure columns cannot be loaded in case there is function with the same name in DB

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#18334]
### Description

Procedure columns cannot be loaded for MySQL in case there is function with the same name in DB

https://user-images.githubusercontent.com/31996417/203994493-b77efd7d-11e9-47f8-bd7b-672b42060236.mp4

### DBeaver Version

22.2.5

### Operating System

win10

### Database and driver

MySQL, > 8.0.25

### Additional context

[dbeaver-debug (2).log](https://github.com/dbeaver/dbeaver/files/10093011/dbeaver-debug.2.log)
[exec.log](https://github.com/dbeaver/dbeaver/files/10093012/exec.log)

**Comment by LonwoLonwo** [comment]
The issue will appear if you are using MySQL driver version > 8.0.25
Workaround: use driver version <= 8.0.25

**Comment by uslss** [comment]
fixed in 8.2.0 mysql driver
