### ISSUE TITLE
SSH tunnel to remote server with putty generated private key: exhausted available authentication methods

### ISSUE THREAD

**Issue by thgsponer** [dbeaver/dbeaver#18331]
### Description

Hi all

I am trying to connect to a remote PostgreSQL database through an SSH tunnel. 

I generated the private key using puttygen, giving me a .ppk file. After google research and browsing the issues [#3125](https://github.com/dbeaver/dbeaver/issues/3125), I found that ppk private keys do not work with DBeaver. I then converted my ppk private key file into a pem file.

Unfortunately, I still get the same error message.

Any advice is very welcome.

Thank you very much for your help.

### DBeaver Version

Community Edition Version 22.2.5.202211202223

### Operating System

Windows 10 Bisness 10.0.19045 Build 19045

### Steps to reproduce

1. I want to configure a connection through SSH tunnel.
2. In the connection settings I go to SSH tab and enable 'Use SSH Tunnel'. 
3. Then I select 'Public Key' as authentication method. 
4. I browse to my private key file and load it.
5. In the advanced settings I select SSHJ.

When I then click 'Test tunnel configuration' I get the error message 'Cannot establish tunnel to <host>, Exhausted available authentication methods'.

[my.log.log](https://github.com/dbeaver/dbeaver/files/10091581/my.log.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10091583/dbeaver-debug.log)

**Comment by Destrolaric** [comment]
@thgsponer Hi, which algorithm was used to generate the key?

**Comment by thgsponer** [comment]
I used RSA

**Comment by Destrolaric** [comment]
Hmm. Could you try to add it to pageant ssh agent and connect via putty itself?

**Comment by thgsponer** [comment]
I can connect via putty when I use the ppk file. When I use the pem file it says 'unable to use key file ... old PEM format'

**Comment by Destrolaric** [comment]
You can try to use .ppk key with SSHJ. Could you try it?

**Comment by thgsponer** [comment]
I tried. Same error. Below are the new log and debug files.
[dbeaver-debug-new.log](https://github.com/dbeaver/dbeaver/files/10093323/dbeaver-debug-new.log)
[mynew.log](https://github.com/dbeaver/dbeaver/files/10093324/mynew.log)

**Comment by Destrolaric** [comment]
@thgsponer Hmm, the last thing you can try is to use pageant - add a key there and use `Agent` auth in DBeaver. Write me if it helps.

**Comment by thgsponer** [comment]
Unfortunately - the same error.
[dbeaver-debug-last-try.log](https://github.com/dbeaver/dbeaver/files/10094076/dbeaver-debug-last-try.log)
[last-try.log](https://github.com/dbeaver/dbeaver/files/10094079/last-try.log)

**Comment by Destrolaric** [comment]
@thgsponer Hmm, could you tell me, which algorhitm was used to generate the key?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
