### ISSUE TITLE
export to csv/xlsx not show column description in header

### ISSUE THREAD

**Issue by MrLuke1110** [dbeaver/dbeaver#18330]
### Description

connection setting: db2 iseries/as400
export to csv/xlsx, header format choose description/both, export data no description,
please help me.

### DBeaver Version

community edition 22.2.5

### Operating System

windows 10

### Database and driver

jt400-11.0

### Additional context

![image](https://user-images.githubusercontent.com/66194793/203948614-a90c43bf-25b2-4028-84ae-bcd8c3bcda6e.png)
![image](https://user-images.githubusercontent.com/66194793/203948627-3e82257c-92b4-44bd-b672-0fc21fc01ee3.png)
![image](https://user-images.githubusercontent.com/66194793/203948634-fcdebc0f-86d0-46bc-b2ef-00af0eb9a6e8.png)

**Comment by LonwoLonwo** [comment]
Hello @MrLuke1110 

Can you please try to export from the table data viewer? I think the problem exists only for the SQL Editor data viewer.

**Comment by LonwoLonwo** [comment]
It is not database-specific. We just do not have comment info during the transfer process.

**Comment by MrLuke1110** [comment]
> 
The previous 2.2.3 is ok, but after the revision to 22.2.4, it cannot be displayed normally

![image](https://user-images.githubusercontent.com/66194793/204951920-9af320ea-a290-4236-8b92-1002a91be488.png)

**Comment by MrLuke1110** [comment]
i choose both( label + description) , but only show label
![image](https://user-images.githubusercontent.com/66194793/205534082-25d03a96-f668-40b2-ab13-92ee539c9a54.png)
![image](https://user-images.githubusercontent.com/66194793/205534088-6fd715ce-1058-4275-8aad-7bdcadf48e53.png)
![image](https://user-images.githubusercontent.com/66194793/205534091-214c5fa8-7326-47fc-8e4d-46af9a81ce1f.png)

**Comment by LonwoLonwo** [comment]
A workaround, for now, is to export from the table data viewer:

![2022-12-07 10_19_27-Window](https://user-images.githubusercontent.com/45152336/206113985-ce274701-d902-45e9-bf7a-b4b17960dea4.png)

**Comment by MrLuke1110** [comment]
choose both, but only show label (1), description (2) is disappear.

![image](https://user-images.githubusercontent.com/66194793/206634918-d882907c-22e2-45bc-84b4-d3e017415f73.png)
![image](https://user-images.githubusercontent.com/66194793/206634928-790f12ad-d492-4fa2-b2cf-b6adb8c6cdc1.png)
![image](https://user-images.githubusercontent.com/66194793/206634934-4e3d4b9b-f2a1-4215-a4d9-75eb4f156cfb.png)
![image](https://user-images.githubusercontent.com/66194793/206635248-82b39863-c5a4-444f-b305-701f50a164a5.png)

**Comment by LonwoLonwo** [comment]
This is again a picture from the SQL Editor. Export from the Result Set has the main problem, yes.

As I said, you could open your table viewer from the [navigator tree](https://github.com/dbeaver/dbeaver/wiki/Database-Navigator) and do export from the table data viewer to keep your descriptions - as a workaround.

**Comment by MrLuke1110** [comment]
Ok, I know how to deal with it, thank you for your patient reply, thank you

**Comment by MrLuke1110** [comment]
> This is again a picture from the SQL Editor. Export from the Result Set has the main problem, yes.
> 
> As I said, you could open your table viewer from the [navigator tree](https://github.com/dbeaver/dbeaver/wiki/Database-Navigator) and do export from the table data viewer to keep your descriptions - as a workaround.

Ok, I know how to deal with it, thank you for your patient reply, thank you

**Comment by caribouman** [comment]
even now, description is not exported  with dbeaver 23.03 with xls or csv

**Comment by LonwoLonwo** [comment]
Hello @caribouman 

Please check this setting and try with enabled setting one more time.

![2023-04-27 11_17_30-Preferences](https://user-images.githubusercontent.com/45152336/234802722-35f14e24-6b99-4308-adb1-16e6d4fbfcdd.png)

**Comment by caribouman** [comment]
Hi, 
![image](https://user-images.githubusercontent.com/33265244/235098294-2bb46d78-f3ce-48c0-a97f-cd755afca656.png)
i put this ,
![image](https://user-images.githubusercontent.com/33265244/235098441-3f1d6c42-d6e8-4170-9990-6c362864d857.png)
![image](https://user-images.githubusercontent.com/33265244/235099358-432122e4-fbaf-42b0-803d-bec20997fe3d.png)
and result
![image](https://user-images.githubusercontent.com/33265244/235099480-8c2669f3-9415-47e4-ab3e-8e2dfe96c845.png)

am i at the good place for parameters? we don t have the same menu...

**Comment by LonwoLonwo** [comment]
This is the place.

For now, I can't reproduce this behaviour.

Can you please check csv export one more time?

**Comment by caribouman** [comment]
Hi, i have the same result, description is not exported.. it  s a AS400 connection with dB2 / Db2 for IBM i driver...perhaps it can help

**Comment by MrLuke1110** [comment]
The latest version still has the same problem, thank you.

![image](https://github.com/dbeaver/dbeaver/assets/66194793/06bf8174-c5d0-45ee-be79-16cc99352081)
![image](https://github.com/dbeaver/dbeaver/assets/66194793/53330f28-5b56-42a7-850e-ed92d6b96f2b)
![image](https://github.com/dbeaver/dbeaver/assets/66194793/e402efe4-5d5a-47cb-a47b-9d32a2c61871)
![image](https://github.com/dbeaver/dbeaver/assets/66194793/919acf03-35f2-4f22-a463-bda68f814923)

**Comment by PaleNeutron** [comment]
I am facing the same problem.

"Show column description in header" only works in "table data viewer" not in "result viewer". That result exported csv from result view not contains description.

Any Suggestions?
