### ISSUE TITLE
Typo in the menu in Russian

### ISSUE THREAD

**Issue by Alexandr-Kislov** [dbeaver/dbeaver#18347]
### Description

There is a typo in the "База данных" (Database) menu option in Russian language. Should be "Новое соединение из JDBC URL" instead of "Новое сое**з**динение из JDBC URL".
![image](https://user-images.githubusercontent.com/68337846/204125420-c2771647-b095-48e5-8175-351944e47595.png)

### DBeaver Version

Community Edition 22.2.5.202211202223

### Operating System

Windows 10

**Comment by E1izabeth** [comment]
Thank you for bug report.
