### ISSUE TITLE
Folders can be created after switching to Projects tab

### ISSUE THREAD

**Issue by kseniaguzeeva** [dbeaver/dbeaver#18342]
### Description

Run DBeaver and press Create folder button
**Expected**: the pop up box appears to enter the folder name
**Actual result:** no visible changes. It's necessary to open Projects tab and go back to the Navigator before it.

https://user-images.githubusercontent.com/112612526/204042094-d39a406a-92e1-48e8-b695-17ce8f72b351.mp4

### DBeaver Version

CE	22.2.5.202211251203

### Operating System

Win10

**Comment by kseniaguzeeva** [comment]
the focus is needed.

**Comment by E1izabeth** [comment]
Not reproducible against DBeaver 23.0.5
