### ISSUE TITLE
Please remove leading whitespaces

### ISSUE THREAD

**Issue by humphreygao** [dbeaver/dbeaver#18351]
### Description

Please see the video:

https://user-images.githubusercontent.com/52394598/204144533-433ae181-4bf8-489b-b371-a87d0b924c10.mp4

If the former SQL has leading whitespaces, there always be leading whitespace in the new line once I press Enter.

### DBeaver Version

22.2.5

### Operating System

Windows 11 22H2

### Database and driver

Any

### Steps to reproduce

1. Type the following SQL:
```sql
   select 1 from dual;|
```
2. Press Enter at the | position

**Comment by LonwoLonwo** [comment]
Hello. Thanks for the report.

I'm not sure about the

> always be leading whitespace

![t0FqcUFRI6](https://user-images.githubusercontent.com/45152336/204228368-7360f31f-1edb-4cb0-861b-8f5828e2fb71.gif)

But the first time - it is true.

**Comment by GuenterSch** [comment]
Hello Anastasya,
I have the same problem like humphreygao. I also think, this should not happen, if I clear the line and I am at the first position of the line. Then the next line after an Enter should also be on the first position.

I use Windows 10, DBeaver 2.2.5 and a Snowflake connection.

Why does this work in your environment?
Do you have other settings?
Is it dependent on the connection?
I do not know.

Principally the auto indent is a very good thing. But sometimes it wolud be fine, to go to the first column with one return.
**Maybe it is possible, that a Shift+Enter returns to the first column.**

I hope you will implement this idea, thanks in advance, BR
Günter

**Comment by jy-hwang** [comment]
is there any solution for this problem?

It is so annoying that unnecessary white space.

this makes me crazy.

please help me.

**Comment by humphreygao** [comment]
duplicate of https://github.com/dbeaver/dbeaver/issues/8552
