### ISSUE TITLE
Causing lock in oracle database

### ISSUE THREAD

**Issue by FarshidShekari** [dbeaver/dbeaver#18353]
### Description

Hi
After editing a view, if there is the same column name in the query(by joins) the client causes a lock happens on the object and needs to kill the session or even restart the service.

Thanks in advance for improving it.

### DBeaver Version

 22.2.5.202211202223

### Operating System

Windows 11

### Database and driver

Oracle

**Comment by LonwoLonwo** [comment]
Hello @FarshidShekari 

Please provide clear steps to reproduce this issue.
A view DDL example will be beneficial.

**Comment by FarshidShekari** [comment]
Suppose there's a column with the same name in another table that you want to use in your join in the view you already created, when you add this table to join and didn't determine which column with the same name comes from which table, after clicking on persisting button to save, this object will be locked :))
and after trying to save view changes nothing was raised as an error.

**Comment by LonwoLonwo** [comment]
Please provide a table and view DDLs to reproduce this issue.

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
