### ISSUE TITLE
Snowflake Parsing Issue in Procedure View

### ISSUE THREAD

**Issue by fa5fou5** [dbeaver/dbeaver#18364]
### Description

Seems that Dbeaver having issue viewing procedure and it seems to be related to this
https://docs.snowflake.com/en/developer-guide/snowflake-scripting/running-examples.html
Exemple of a procedure created in the Dbeaver client
```
CREATE OR REPLACE PROCEDURE DB_IAWT_DEV_DWH.SCHEMA_RACHID.OUTPUT_MESSAGE("ENV" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE DEL_QUERY STRING;
BEGIN
--RETURN ''Hello ''||F_NAME||'' !'';
DEL_QUERY := ''DELETE FROM DB_IAWT_''||ENV||''_DWH.SCHEMA_RACHID.WT_SAT_CONTRACT_AUA_SEG_COMPUTE WHERE 1=1'';
RETURN :DEL_QUERY;
--EXECUTE IMMEDIATE :DEL_QUERY;
END;
 '
```
Error message:
>/* ERROR WHILE READING SOURCE:
>SQL Error [1003] [42000]: SQL compilation error:
>parse error line 1 at position 38 near '95'.
>*/

### DBeaver Version

22.2.5

### Operating System

Windows 10

### Database and driver

1. Database : Snowflake

### Steps to reproduce

1. Click on a procedure to view definition

**Comment by LonwoLonwo** [comment]
Hello @fa5fou5 

Can't reproduce your issue for now.

![2022-11-29 17_53_26-DBeaver Ultimate 22 2 5 - _TEST_DB_ Script-85](https://user-images.githubusercontent.com/45152336/204563304-52025072-832b-4213-b6ae-8eb91a4f008a.png)

What driver version do you use?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
