### ISSUE TITLE
Error loading table data from BigSQL (DB2 Variant) connection

### ISSUE THREAD

**Issue by bkyle** [dbeaver/dbeaver#18366]
### Description

When open the Table Editor for a table in BigSQL and switch to the Data tab the following error message is returned:

> The command or statement was not executed because the following functionality is not supported in the current environment: "RID functions".. SQLCODE=-5115, SQLSTATE=56038, DRIVER=4.31.10

### DBeaver Version

Community Edition 22.2.1

### Operating System

macOS Montery 12.6

### Database and driver

- Server: BigSQL 7.1
- Driver:
  - Group: com.ibm.db2
  - Artifact: jcc
  - Version: 11.5.0.0

### Steps to reproduce

1. Connect to BigSQL Database.
2. In the _Database Navigator_ expand _Schemas_ and a schema.
3. Expand _Tables_ and select a table.
4. Double click on a table to bring up the Table Viewer.
5. In the Table Viewer, click on the _Data_ tab.

### Additional context

[BigSQL](https://www.ibm.com/docs/en/db2-big-sql/7.1) provides a DB2 interface over data in Hadoop HDFS and/or Object Storage.

**Comment by LonwoLonwo** [comment]
Thanks for the bug report and the contribution.
