### ISSUE TITLE
Proposals and auto-complete don't work with partition and alias

### ISSUE THREAD

**Issue by kowilf** [dbeaver/dbeaver#18377]
### Description

![image](https://user-images.githubusercontent.com/91829971/204539239-52d5439b-8eee-42b3-bef5-c57a59be99ac.png)

![image](https://user-images.githubusercontent.com/91829971/204539523-4f1205b8-c9f8-496e-8b7b-f640bf5f1311.png)

### DBeaver Version

Community Version 22.2.5

### Operating System

WIN-11

### Database and driver

MySQL

**Comment by E1izabeth** [comment]
The issue is solved with preference `Editors -> SQL Editor -> Code Completion -> Enable experimental features` on.
