### ISSUE TITLE
Script title pattern gets reset after every restart of DBeaver

### ISSUE THREAD

**Issue by switchfoot7** [dbeaver/dbeaver#18376]
### Description

 **Window > Properties > Editors > SQL Editor > Scripts > Script title pattern** is lost after every restart of DBeaver

### DBeaver Version

22.2.1

### Operating System

Windows

### Steps to reproduce

Go to **Window > Properties > Editors > SQL Editor > Scripts** and set a value in **Script title pattern:** for example **${fileName}**
Apply and Close the Properties window. The value is set and the file names are shown as the tab titles.
Close DBeaver and open it again. The  **Window > Properties > Editors > SQL Editor > Scripts > Script title pattern** has been reset to [empty]

**Comment by LonwoLonwo** [comment]
Hello @switchfoot7 

Can't reproduce your issue. The Script title pattern contains saved value after DBeaver reopening for me.

Can you please check the newest DBeaver version?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
