### ISSUE TITLE
How to get DBeaver Office integration old version

### ISSUE THREAD

**Issue by MrLuke1110** [dbeaver/dbeaver#18372]
### Description

install DBeaver Office integration, only can find the lastest version (https://dbeaver.io/update/office/latest/), use the lastest version on export data, cant find "column names as header".
can't find 2.2.3 in here(https://dbeaver.io/files/)
so where can i get the previous version? 
Thanks.

lastest verion
![image](https://user-images.githubusercontent.com/66194793/204499154-ee6a04c1-9230-41cb-a8c4-510d42b5db4d.png)

old version
![image](https://user-images.githubusercontent.com/66194793/204499335-336c63e7-2f7e-4497-a3fb-e85fee814ab4.png)

### DBeaver Version

Community Edition 22.2.3

### Operating System

windows 10 home 

### Database and driver

1. ibm db2 iseries V7R2M0
2. jt400 11.1

### Steps to reproduce

1. export data
2. xlsx
3. format settings => column names as header

### Additional context

extensions: office extension

**Comment by LonwoLonwo** [comment]
Hello @MrLuke1110 

Maybe this is the setting that you are looking for.

![2022-11-29 13_21_50-Data Transfer](https://user-images.githubusercontent.com/45152336/204503916-260ff1e6-73f3-46a6-a094-edd24ccb08d7.png)

**Comment by MrLuke1110** [comment]
> Maybe this is the setting that you are looking for.

There are other problems with this function, which also need to be dealt with
https://github.com/dbeaver/dbeaver/issues/18330

**Comment by LonwoLonwo** [comment]
Then I do not think that version decreasing will help.

**Comment by MrLuke1110** [comment]
i use offline install from here (https://dbeaver.io/files/21.0.0/repository-office/)
export data will help.

![image](https://user-images.githubusercontent.com/66194793/204950975-0b6ccf84-81f3-4353-9936-65d6d4301e07.png)
![image](https://user-images.githubusercontent.com/66194793/204951373-8f15922b-4573-46bc-a23b-024bcd28a703.png)

**Comment by LonwoLonwo** [comment]
![2022-12-01 13_12_39-playlist_202212011311](https://user-images.githubusercontent.com/45152336/205026511-24f5a18e-9df2-4d66-accb-bf4331bcac1f.png)

And export labels as header works fine for me in the current DBeaver version.

So, again - what problem do you want to solve?

**Comment by MrLuke1110** [comment]
> ![2022-12-01 13_12_39-playlist_202212011311](https://user-images.githubusercontent.com/45152336/205026511-24f5a18e-9df2-4d66-accb-bf4331bcac1f.png)
> 
> 
> 
> And export labels as header works fine for me in the current DBeaver version.
> 
> 
> 
> So, again - what problem do you want to solve?
> 
> 

Hello, the label is displayed normally, but the description cannot be displayed. If you choose both, only the label will be displayed.

**Comment by LonwoLonwo** [comment]
> Hello, the label is displayed normally, but the description cannot be displayed.

You have another ticket for this.
