### ISSUE TITLE
Unable to enter file name in SaveAs dialog

### ISSUE THREAD

**Issue by aplatypus** [dbeaver/dbeaver#18386]
### Description

* I used the File / Save As menu item to save my open SQL editor
* A file save dialog appears
![File save](https://user-images.githubusercontent.com/67028/204724401-296aeaf8-dd80-4321-a6d1-71d44c9a4b61.png)
  * As indicated with the arrow, I expected to enter a meaningful name for the script
* I began to type a useful name and this happened (_screenshot_)
![image](https://user-images.githubusercontent.com/67028/204724765-4fd47543-9a1c-4ddd-9606-ce8f062d98bb.png)
  * Every time I type a key the very annoying search bar pops-up
  * If you clear the search panel, it just returns when you type the next character
*  This can be extremely frustration, especially if you are typing quickly and don't notice your file is saved as something like `a.sql` (for example) because the name was never completed.

### DBeaver Version

22.2.5.202211202223

### Operating System

Ubuntu Linux  22.04

### Database and driver

* mysql 8
* DBeaver:	22.2.5.202211202223	org.jkiss.dbeaver.core.product	null

### Steps to reproduce

1. Open sql editor (or any editor I guess)
2. Us save as menu to save the file
3. type a file name

* you will see the searh bar and  wil be unable to actually enter a name.

### Additional context

* One work around is to enter the filename in an editor and copy the text
* You can paste in the desired filename in the dialog
* And save the file with the name you Want.

**Comment by LonwoLonwo** [comment]
Hello @aplatypus 

Can you provide a video of your issue, please?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.

**Comment by aplatypus** [comment]
* Yes still a bug as far as I'm concerned.
* It is easy to see what happens save as, start typing, jumps to search

**Comment by LonwoLonwo** [comment]
Could you provide a video of your issue, please?
