### ISSUE TITLE
Export in Parquet

### ISSUE THREAD

**Issue by kseniaguzeeva** [dbeaver/dbeaver#18393]
Based on https://github.com/dbeaver/cloudbeaver/issues/1315

Is it possible to export in Parquet?

It would (1) make the data more usable instantly, and (2) it would lead to lower egress than a CSV.

**Comment by igitur** [comment]
Import too, of course.

**Comment by manticore-projects** [comment]
Greetings DBeaver team.

Maybe I can lend a helping hand here. Since I want to test/use DuckDB or ClickHouse and did not find anything good for the migration from Oracle and friends, I wrote a small library:
https://manticore-projects.com/JDBCParquetWriter/index.html
https://github.com/manticore-projects/JDBCParquetWriter

Its a first working version, but it seems to get the Type/Column translation right. Also it uses latest Hadoop/Parquet and supersedes a lot of deprecated samples found in the internet.

It should be very easy to call the `write(..,)` method from DBeaver:
```java
String tableName = "execution_ref";
File file = File.createTempFile(tableName, ".parquet");

String sqlStr = "SELECT * FROM test.execution_ref";
try (Statement st = conn.createStatement(); ResultSet rs = st.executeQuery(sqlStr);) {
    JDBCParquetWriter.write(file, tableName, rs);
}
```

**Comment by ShadelessFox** [comment]
Thanks for the suggestion. We will review the suggested solution later.

**Comment by aelgharabawy** [comment]
Hi, I am waiting for this feature as well, i.e., the ability to export to Parquet format.

**Comment by DeflateAwning** [comment]
Would be a great feature!

**Comment by mixam85** [comment]
I would love that too.

**Comment by flambchap** [comment]
Related task: https://github.com/dbeaver/dbeaver/issues/5821

**Comment by flambchap** [comment]
I think we can do it, but only for our commercial products because of this: https://github.com/dbeaver/dbeaver/issues/5821#issuecomment-1994141845. I submitted this issue for a discussion with our product team.

**Comment by DeflateAwning** [comment]
Why would this be a commerical-only feature? I understand the custom JDBC driver, but this is not a database connection; this is an import/export function similar to CSV.

**Comment by manticore-projects** [comment]
> but this is not a database connection; this is an import/export function similar to CSV.

Maintaining a [custom JDBC driver for Excel Sheets](https://github.com/manticore-projects/sqlsheet), I can only second this.
The requested functionality is: Write-out a JDBC result set into a file (format parquet) and the only JDBC driver involved is related to the data source.

I am able to write a custom JDBC driver (for parquet) but I do not see how this would be of help here?

**Comment by DeflateAwning** [comment]
@manticore-projects, #5821 is a request for a JDBC driver for connecting to Parquets. I would like both of these features very badly. If you'd be willing/able to create a JDBC driver for parquet files (ala data lake), that'd be fantastic!

**Comment by manticore-projects** [comment]
> . I would like both of these features very badly. 

Understandable, though I still see it as a completely different problem (where the only common denominator is the term "parquet").

> If you'd be willing/able to create a JDBC driver for parquet files (ala data lake), that'd be fantastic!

Similar to the Excel JDBC driver, this will be very limited:
- `SELECT * FROM parquet_file ` (without support of joins, where, having, group, limit/offset since there is no DB engine involved)
- `CREATE TABLE parquet_file (...)`
- `INSERT INTO parquet_file VALUES (...)`
- `DELETE FROM parquet_file`  (without support of joins, where, having, group, limit/offset since there is no DB engine involved)
- `DROP TABLE parquet_file`
- maybe `ALTER TABLE parquet_file ADD | DROP | ALTER column ...`
- MetaData information

If you want to do anything really useful, you will need a DB Engine and for this reason there is DuckDB already which treats Parquet as table storage format. So I think, for whatever you want to achieve, the DuckDB JDBC driver may provide the better solution already.

But we are going far off topic here and I don't want to hijack this DBeaver forum (sorry guys!).
Feel free to make a case at my own repositories for a discussion about writing an open source Parquet JDBC Driver.

**Comment by stevennic** [comment]
Import / Export targets shouldn't need a JDBC driver imo. That's only if you want to be able to treat the target like a DB and submit SQL queries to it. Potentially useful, but a very different and much less common use case. Parquet import/export should be a matter for an adapter, which is probably already available.

**Comment by igor-suhorukov** [comment]
[DuckDB JDBC driver](https://duckdb.org/docs/api/java.html) allow reading/writing parquet files via embedded database

**Comment by pratikgujral** [comment]
Any timeline for adding this functionality of exporting Parquet/Avro from DBeaver?

**Comment by serge-rider** [comment]
We going to implement it after 24.2 release

**Comment by serge-rider** [comment]
First version of Parquet data export will be added in DBeaver PRO products.

Unfortunately Parquet requires a lot of 3rd party dependencies and integration with Java Hadoop libraries, it is not possible to add it in the Community for now.

**Comment by igor-suhorukov** [comment]
DuckDB JDBC include all native code dependencies (reimplemented without hadoop). Apache Arrow contains another Apache Parquet implementation

**Comment by DeflateAwning** [comment]
This is quite disappointing. 

I want this for personal use, so this is still a feature I'm requesting in the Community Edition of DBeaver. Is it allowable to open this as a feature request again?

**Comment by carfield** [comment]
> First version of Parquet data export will be added in DBeaver PRO products.
> 
> Unfortunately Parquet requires a lot of 3rd party dependencies and integration with Java Hadoop libraries, it is not possible to add it in the Community for now.

there are a lot difference version of PRO product: https://dbeaver.com/download/ , which one have that? Will lite version have that?

**Comment by E1izabeth** [comment]
@carfield any PRO product, lite version too

**Comment by E1izabeth** [comment]
Here is our documentation about that https://dbeaver.com/docs/dbeaver/Database-driver-Parquet/

**Comment by Hillrunner2008** [comment]
I would suggest this library to you https://github.com/strategicblue/parquet-floor and of course make your own version if desired but no need for the Hadoop dependency hell to ruin your classpath thanks to this good work I wrote a small wrapper you can see below. 


```java
package com.stackleader.io.parquet;

import static java.sql.Types.BIGINT;
import static java.sql.Types.BOOLEAN;
import static java.sql.Types.DECIMAL;
import static java.sql.Types.DOUBLE;
import static java.sql.Types.FLOAT;
import static java.sql.Types.INTEGER;
import static java.sql.Types.REAL;
import static java.sql.Types.SMALLINT;
import static java.sql.Types.TIMESTAMP;
import static java.sql.Types.TINYINT;

import java.io.File;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

import org.apache.parquet.schema.LogicalTypeAnnotation;
import org.apache.parquet.schema.MessageType;
import org.apache.parquet.schema.PrimitiveType;
import org.apache.parquet.schema.Type;
import org.apache.parquet.schema.Types;

import blue.strategic.parquet.Dehydrator;
import blue.strategic.parquet.HydratorSupplier;
import blue.strategic.parquet.ParquetReader;
import blue.strategic.parquet.ParquetWriter;

public final class ParquetIO {

    public static void write(ResultSet rs, File target) throws Exception {
        ResultSetMetaData m = rs.getMetaData();
        MessageType schema = schema(m);

        Dehydrator<ResultSet> dehyd = (record, v) -> {
            try {
                for (int i = 1; i <= m.getColumnCount(); i++) {
                    Object val = record.getObject(i);
                    if (val != null)
                        v.write(m.getColumnName(i).toLowerCase(), convert(val, m.getColumnType(i)));
                }
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        };

        try (ParquetWriter<ResultSet> w = ParquetWriter.writeFile(schema, target, dehyd)) {
            while (rs.next())
                w.write(rs);
        }
    }

    public static Stream<Map<String, Object>> read(File source) throws Exception {
        HydratorSupplier<Map<String, Object>, Map<String, Object>> hs = cols -> new blue.strategic.parquet.Hydrator<>() {
            @Override
            public Map<String, Object> start() {
                return new HashMap<>();
            }

            @Override
            public Map<String, Object> add(Map<String, Object> t, String h, Object v) {
                t.put(h, v);
                return t;
            }

            @Override
            public Map<String, Object> finish(Map<String, Object> t) {
                return t;
            }
        };
        return ParquetReader.streamContent(source, hs);
    }

    private static MessageType schema(ResultSetMetaData m) throws SQLException {
        List<Type> fields = new ArrayList<>();
        for (int i = 1; i <= m.getColumnCount(); i++)
            fields.add(field(m.getColumnName(i).toLowerCase(), m.getColumnType(i)));
        return new MessageType("row", fields);
    }

    private static Type field(String n, int sql) {
        var p = switch (sql) {
            case INTEGER, SMALLINT, TINYINT -> PrimitiveType.PrimitiveTypeName.INT32;
            case BIGINT -> PrimitiveType.PrimitiveTypeName.INT64;
            case FLOAT, REAL -> PrimitiveType.PrimitiveTypeName.FLOAT;
            case DOUBLE -> PrimitiveType.PrimitiveTypeName.DOUBLE;
            case BOOLEAN -> PrimitiveType.PrimitiveTypeName.BOOLEAN;
            default -> PrimitiveType.PrimitiveTypeName.BINARY;
        };
        var b = Types.primitive(p, Type.Repetition.OPTIONAL);
        if (p == PrimitiveType.PrimitiveTypeName.BINARY)
            b = b.as(LogicalTypeAnnotation.stringType());
        return b.named(n);
    }

    private static Object convert(Object v, int sql) {
        return switch (sql) {
            case INTEGER, SMALLINT, TINYINT -> ((Number) v).intValue();
            case BIGINT -> ((Number) v).longValue();
            case FLOAT, REAL -> ((Number) v).floatValue();
            case DOUBLE -> ((Number) v).doubleValue();
            case DECIMAL -> v.toString();
            case BOOLEAN -> v;
            case TIMESTAMP -> ((Timestamp) v).toInstant().toString();
            default -> v.toString();
        };
    }

    private ParquetIO() {
    }
}
```


Not at all saying this is what everyone wants, but it sure would be a decent starting point vs no export to parquet.
