### ISSUE TITLE
Invalidate / Reconnect freeze issue

### ISSUE THREAD

**Issue by tmalahie** [dbeaver/dbeaver#18402]
### Description

In the database navigator, when I right click on a database and select "Invalidate / Reconnect", it blocks at the Invalidation step. I have to manually disconnect and reconnect to make it work again.
This issue seams to exist since version 22.2.5 (22.2.4 is fine)

### DBeaver Version

Community Edition 22.2.5

### Operating System

macOS Ventura 13.0.1 (22A400)

### Database and driver

Database name and version: MariaDB 10.5.15
Driver name and version: MariaDB JDBC driver 3.1.0

### Steps to reproduce

1. Try to connect to a database
2. Right click and select "Invalidate / Reconnect"
3. It will get stuck in stabe "Invalidate DB"
<img width="316" alt="image" src="https://user-images.githubusercontent.com/10288728/205125852-83b30c79-71a7-48fb-8795-4544b60bd2b0.png">
4. If I try to perform a request, it will load indefinitely 
<img width="216" alt="image" src="https://user-images.githubusercontent.com/10288728/205125974-ee014f2a-5a7f-4501-9f70-6ca9ceecb7a1.png">

### Additional context

I have an SSH tunnel configured for this connection, don't know if it changes anything.

**Comment by ShadelessFox** [comment]
Hello @tmalahie,

Please try against the early access version: https://dbeaver.io/files/ea/

**Comment by tmalahie** [comment]
Hello, thanks for the quick reply 🙂 
It works fine on the early access version! I can close the issue then
