### ISSUE TITLE
Postgres enum type editing inconvience

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#18409]
### Description

![dbeaver_enums](https://user-images.githubusercontent.com/11477081/205269649-3863c0ec-1e00-49c2-b2c9-046d06a3990e.png)

### DBeaver Version

22.2.5.202211202223 CE

### Operating System

win

### Database and driver

PG

### Steps to reproduce

lets see at the picture. I have two schemas - repl and repl_log. I have some enums (custom types) declared in both of them.

There are bugs:
1. When I change type in the table editing dialog - i see only type names (without schemas, even when table schema differs from type schema);
2. When I try to save table - it fails, generating SQL:

ALTER TABLE [X] ALTER COLUMN [Y] TYPE [type] USING [Y]::[type];
but it should be:
ALTER TABLE [X] ALTER COLUMN [Y] TYPE [schema.type] USING [Y]::text::[schema.type];

Nota bene: enums cannot be converted directly (by 'USING'), but can be converted via additional 'text'

**Comment by LonwoLonwo** [comment]
Thanks for the report @plotn
