### ISSUE TITLE
Copy button in Status details Dialog

### ISSUE THREAD

**Issue by GuenterSch** [dbeaver/dbeaver#18419]
Hello,
often I copy the content of the Status details Dialog in my SQL editor window and comment it for archiving.

Therefore it would be fine, if there exist a copy button in the Status details Dialog, like in the "Persit changes" dialog. After a press on the copy button, the window should be closed.

![grafik](https://user-images.githubusercontent.com/99535516/205345511-c13afd51-eda6-4a71-98b1-c68ee37e0bb3.png)

If you add the single line comment at the begin of the text, it would be great.
--18 row(s) fetched - 318ms (2ms fetch), on 2022-12-02 at 17:44:28

Another cool thing would be, if there exists a shorcut key, to do this, without open the Status details dialog.

Thanks in advance, BR
Günter

**Comment by ShadelessFox** [comment]
Hello @GuenterSch,

Thank you for your request, but the proposed changes look too specific.

You can comment-out line by pressing the `CTRL+/`, and close this dialog just by pressing `ESC`. These enhancements look redundant.

**Comment by GuenterSch** [comment]
Hallo ShadelessFox,
I think, I am not the only one, who would use this feature (at least the copy button).

**Could you implement the possibility, that I can assign a key to open the Status details dialog.**
That was an option, to do this with the keyboard only, instead of the mouse.

I hope, this is possible.
Thanks, BR
Günter
