### ISSUE TITLE
Multiple-byte character can't be displayed properly by "Result" windows .

### ISSUE THREAD

**Issue by balabalabalaggyy** [dbeaver/dbeaver#1841]
Database : Oracle 11.2.0.1
DBeaver : 4.1.0  Windows 64 bit (installer + JRE)
Operating system: Windows 10 x64 
Sql statement: 
SELECT 1 ,SYSDATE,'hello','안녕하세요',lengthb('안녕하세요'),'你好',lengthb('你好'),'こんにちは',lengthb('こんにちは') FROM DUAL ;

안녕하세요 , 你好，こんにちは  can‘t be displayed properly .

![result_display_bug](https://user-images.githubusercontent.com/8953191/27814402-a86e04f6-60ae-11e7-97cc-d4b6accb4bfb.png)

Export to HTML is fine .
HTML: 

![export_html](https://user-images.githubusercontent.com/8953191/27814453-10e02bcc-60af-11e7-896f-bbc67b5810f7.png)

**Comment by serge-rider** [comment]
This seems to be somehow related to multibyte UTF (when char occupies > 2 bytes) and Oracle JDBC driver.

The same query works fine with MySQL/PostgreSQL. 2-bye characters work fine in all databases including Oracle.
I'll need to investigate this a bit more.. 
(check this: https://asktom.oracle.com/pls/asktom/f?p=100:11:0::::p11_question_id:5783936214008)

**Comment by tati-kru** [comment]
hi @balabalabalaggyy. Could you, please check that it can be reproduced or not on the latest version?

**Comment by serge-rider** [comment]
This works fine with latest Oracle driver (12c).
