### ISSUE TITLE
SQL Editor Tab, ... Reference to 16620

### ISSUE THREAD

**Issue by GuenterSch** [dbeaver/dbeaver#18418]
Hello Matvey16,
this bug still persists.
The first thing is, if I write after the tab switch, I am in a wrong SQL editor window. Thats bad!
And a Ctrl+Tab goes not to the previous SQL editor window.

Would be very fine, if you can correct this bug.
Thanks in advance, BR
Günter

Now I use 22.2.5

_Originally posted by @GuenterSch in https://github.com/dbeaver/dbeaver/issues/16620#issuecomment-1335510486_

**Comment by ShadelessFox** [comment]
We've closed the original issue because we were unable to reproduce it.

If you have steps to reproduce that work 100% of the time, please post them on the original issue.
