### ISSUE TITLE
error SQL parsing

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#18427]
### Description

error SQL parsing with special command

### DBeaver Version

community edition 22.3.0

### Operating System

windows 11 64bit

### Database and driver

Postgresql 14

### Steps to reproduce

1. Open SQL Editor
2.run SQL 
"set random_page_cost = 0.11; select 1;"
3. click on "calc all row count"
![image](https://user-images.githubusercontent.com/61137576/205584652-16731c7c-8a8e-44fd-ada3-0a83e178c8d5.png)

**Comment by uslss** [comment]
@detkliff unfortunately cannot reproduce the issue. Could you provide video of the issue?

**Comment by elring** [comment]
It happens when you press "Calculate total row count" button in the "Statistics" tab (of the set random_page_cost query result). Those re-added buttons (Calculate..., Result fetch size etc.) should be also disabled for Statistic tab.

**Comment by uslss** [comment]
thanks for the report
