### ISSUE TITLE
Data Transfer to DB does not insert all rows

### ISSUE THREAD

**Issue by MeyersJeff** [dbeaver/dbeaver#18425]
### Description

Trying to transfer all rows from FileMaker 16 table (via JDBC driver) into new table on MySQL 8. FileMaker says there are 11,433 records in the table. If I export from the table to a new table in MySQL, only 9878 rows are inserted. There are no errors displayed during the export or in the Error Log.

If I set result set size to 12000 and select * from table, grid shows 11433 rows, but export from there as well only inserts 9878 rows.

I am inserting into a table that does not exist, so there should be no constraints getting in the way.

If I export to CSV, the resulting file has 11433 records, but this format is not usable. I did this just for comparison to confirm all of the data was extracted from the source.

FileMaker tables with smaller number of rows successfully transferred all rows, but other tables w/ large number of rows also only imported a subset.

How do I get more visibility into which rows are not inserted and why? Any tricks to get all rows to be transferred?

### DBeaver Version

Community 22.2.5

### Operating System

Windows 10

**Comment by MeyersJeff** [comment]
My apologies - this may have been my mistake. I think I mistook the "row count" statistic for the target table to represent the number of rows in the table. Apparently this is not the case, and when I select count(*) from the table I get the same number of rows as the source table.

I also just upgraded to 22.3.0, so that may have played a role, but I suspect it was mostly the above.

**Comment by E1izabeth** [comment]
Thank you for letting us know.
