### ISSUE TITLE
Right click issue when have collapsed query

### ISSUE THREAD

**Issue by yaseenhejazi** [dbeaver/dbeaver#18426]
### Description

When right click any area below collapsed SQL query the courser point to wrong position causing for example "Execute From Query" option to run on wrong SQL statement

### DBeaver Version

22.2.5

### Operating System

Windows 11

**Comment by LonwoLonwo** [comment]
Hello @yaseenhejazi 
Please provide any footage of this issue.

**Comment by yaseenhejazi** [comment]
This one sample:

- Step1:
<img width="110" alt="image" src="https://user-images.githubusercontent.com/46435202/205593775-866033ea-30a5-4746-9a52-25e399db0821.png">

- Step2: Collapse first query
<img width="139" alt="image" src="https://user-images.githubusercontent.com/46435202/205594077-d114c926-914f-4b76-b704-4efee4764bc0.png">

- Step3: Right click on second query
<img width="623" alt="image" src="https://user-images.githubusercontent.com/46435202/205594437-e5b8b090-28b5-489d-b0c4-6033e0b346a8.png">

The courser moved to wrong position causing the "Export From Query" option to be disabled
