### ISSUE TITLE
High CPU usage when ER diagram is open

### ISSUE THREAD

**Issue by jacekgajek** [dbeaver/dbeaver#18433]
### Description

Even if if there is no interaction with app, DBeaver constantly uses over 100% CPU usage (around 30% of each core) if there is a tab with a specific ER diagram opened (even if it's not a currently open tab)

![image](https://user-images.githubusercontent.com/68021034/205633597-43658f6d-fd2c-4917-9f2f-c1f0eb4070b0.png)

After closing one of tabs cpu usage (by DBeaver) goes down to around 0%:
![image](https://user-images.githubusercontent.com/68021034/205633817-4c80649b-bdf2-4082-8f75-b306714a55ef.png)

**This seems to happen only for diagrams which does not fit screen**
If diagram fits the screen then it works normally, but as soon as I resize DBeaver window so it doesn't fit, CPU goes up to 100% and stays like that even without interaction.

If I resize it back so all diagrams fit to screen, the CPU usage still is high until I go to each tab (ie display it). Then it goes down to 0%.

**This seems to happen only if the "Mikami-Tabuchi (Experimental)" routing type is selected.**

### DBeaver Version

Community Version 22.3.0.202212041619

### Operating System

Ubuntu 22.04 LTS / Windowing system X11.

### Database and driver

PostgreSQL
org.postgresql:postgresql:RELEASE (42.5.0)

### Steps to reproduce

- Switch to "Mikami-Tabuchi (Experimental)" routing type
- Open a ERD diagram for a schema with a moderate size (~20 tables, ~30 FKs in my case), which doesn't fit the screen (not sure if it can be reproduced with really small schemas)

### Additional context

I can observe this issue since I came back to using Dbeaver about 3 months ago, so it's not a regression of the last version

**Comment by E1izabeth** [comment]
Related to #18031

**Comment by E1izabeth** [comment]
Thank you for bug report.
I'll close it as a duplicate.

**Comment by jacekgajek** [comment]
Oh, I searched for "high cpu usage" before opening the issue. I hope you find my contribution useful anyway.
