### ISSUE TITLE
Keep editors when disconnecting from DB

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#18449]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I disconnect from a database, and all previously opened data editors are gone.

**Describe the solution you'd like**
When disconnecting from a database, all associated editors will become "uninitialized". Every uninitialized editor will have a button that will initialize it back, revalidating the connection and performing other necessary preparations.

This can be further expanded to editors that have failed to load due to some error, e.g., network error or the table it was pointing to was deleted, to have the same button. So after you fix whatever issue you have had, you can press that button and continue your work.

**Describe alternatives you've considered**
1. Manually close and open the editor
2. Restart DBeaver

**Comment by ghYura** [comment]
Please, make such option configurable somewhere in "Options".
I find current auto-closing related bunch of editors for disconnected as convenient.
Thank you

**Comment by ShadelessFox** [comment]
Hello @ghYura,

Thanks for making a point about that. Yes, it will be configurable.

**Comment by ghYura** [comment]
Hello @ShadelessFox ,
Actually my proposition is a bit more global and even abstract applying to any new feature implementation. Someone cached in using old-style "Feature-A" behavior, others - require new one "Feature-B". Someone (me) proposes to keep/modify "Feature-C" configurable (and even give it customizable for any user by its own taste) ...and so on.
So it is a general abstract concept proposal :)

**Comment by ghYura** [comment]
@ShadelessFox 
BTW,  is it possible to implement following feature (also as for IJ IDEA) for expanded tabs overflowing space in a tabs-row in DBeaver?:
(rotating tab names to economize space + their transparency)
[https://youtrack.jetbrains.com/issue/IDEA-313456](https://youtrack.jetbrains.com/issue/IDEA-313456)
(have a look, please)

**Comment by ShadelessFox** [comment]
I don't think we want to add such a feature:
1. It looks like something that not everyone would use/need
2. It would require us to make a lot of effort just to implement it. Perhaps even impossible without modifications to the Eclipse platform.

A more useful feature would be to have tabs wrapped in multiple lines if they can't fit on a single line. See https://github.com/dbeaver/dbeaver/issues/16050.

**Comment by ghYura** [comment]
Current situation (as so as for any other soft) with tabs folding (in known, but invisible place)
or with their placing by eating additional square pixels, that should be used for workspace of tab content itself in viewport.
So I think it is really time (in general for all) to go deeper into underlying frameworks and add such useful thing (rotation+shrinking-in-line and tabs gradient transparency for underlying menu items while cursor out of snapped tabs-line).

**Comment by ShadelessFox** [comment]
Please create a separate issue or use the existing one and suggest related changes there.

This ticket is about editor behavior on DB disconnect. Please don't pollute it with unrelated suggestions.
