### ISSUE TITLE
Table filters not working in Simple View

### ISSUE THREAD

**Issue by fallingrock** [dbeaver/dbeaver#18440]
### Description

I don't know if this is really a bug or user error.

I'm trying to filter out two sets of tables from the database navigator.

I enabled the table filters and added 'bk%' to the list, but tables that begin with 'bk' still appear in the tree.

I'd also like to filter out tables that begin with 'de_', but am not sure how to escape the underscore since that character can be used as a wildcard.

### DBeaver Version

Community Edition 22.2.5.202211202223

### Operating System

Ubuntu 18

### Database and driver

PostgreSQL JDBC Driver 42.5.0

### Steps to reproduce

1. Edit connection
2. Click on general tab
3. click on Tables filter
4. Add 'bk%' and 'de_%' to filter list.
5. Click OK
6. Disconnect & reconnect connection
7. Tables that start with 'bk' and 'de_' still appear in table list.

### Additional context

Using simple navigator view.

**Comment by uslss** [comment]
Thanks for the report

**Comment by ShadelessFox** [comment]
Hello @fallingrock,

I'm unable to reproduce your issue.

Are you sure you're adding filters to the exclusion list?

|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/35821147/211809947-c485830b-2142-4bf8-bb1e-43c4ed7e0ac6.png)|![image](https://user-images.githubusercontent.com/35821147/211809738-2b051c4f-291d-4195-bb71-7fe911b85ada.png)|

**Comment by E1izabeth** [comment]
@ShadelessFox popup says that special symbols `%`,  `_ ` and `*` could be used, but only `%` works.
![image](https://user-images.githubusercontent.com/28875055/211810599-18f772d6-e967-4715-8446-72e1c79d04f8.png)

**Comment by ShadelessFox** [comment]
Still can't reproduce:

![image](https://user-images.githubusercontent.com/35821147/212741931-602f0845-abbb-406c-b064-e984b63b4ec5.png)

**Comment by fallingrock** [comment]
Try doing an exclude. On Jan 16, 2023, at 12:04 PM, ShadelessFox ***@***.***> wrote:﻿
Still can't reproduce:

**Comment by fallingrock** [comment]
![db-filters](https://user-images.githubusercontent.com/4029821/212749318-b6528293-2931-4f0d-b8ee-e5e2f6100a87.jpg)
![db-tree](https://user-images.githubusercontent.com/4029821/212749324-8504d3ab-0a62-483d-b87d-5dba50b60a4b.jpg)

**Comment by ShadelessFox** [comment]
Sorry, I'm still unable to reproduce your issue:

![image](https://user-images.githubusercontent.com/35821147/212751608-8c338ffb-e47c-4354-a1b8-00aff0149f70.png)

Could you please try upgrading to the latest DBeaver version to see if it solves your issue? https://dbeaver.io/download/

**Comment by fallingrock** [comment]
The filters appear to work fine in the custom & advanced navigator view, but not in the simple view.

Custom view:
![image](https://user-images.githubusercontent.com/4029821/217934299-c694548f-a788-4056-8d73-cec730bbc238.png)

Simple view:
![image](https://user-images.githubusercontent.com/4029821/217934686-34b704cd-acd0-44f5-a0cf-13a7e8216230.png)

**Comment by E1izabeth** [comment]
Thank you for investigation. This information helps a lot. I reproduced it.

**Comment by liusiyuxyfx** [comment]
Same problem，hope for reparing

**Comment by HocKu7** [comment]
@liusiyuxyfx @fallingrock Hi! Is this behavior still reproducible on the latest version of the product?

**Comment by fallingrock** [comment]
@HocKu7 seems to be working correctly in both simple & advanced mode for me.

**Comment by E1izabeth** [comment]
@fallingrock thank you for checking
