### ISSUE TITLE
Multiple Redshift databases showing same schemas

### ISSUE THREAD

**Issue by LorrieMonaghan** [dbeaver/dbeaver#18450]
### Description

When connecting a Redshift cluster with multiple databases the schemas for those databases are displayed incorrectly in the database navigator. 

When opening up the tree for each of the databases it just repeats the schemas for the database that was selected by default. This makes it difficult to trust what database dbeaver is actually connected to.

### DBeaver Version

Version 22.3.0.202212041619

### Operating System

Windows 11

### Database and driver

Redshift
AWS Redshift JDBC driver

### Steps to reproduce

1. Connect to a redshift cluster with multiple databases using a jdbc url and defining a default database
2. Open the Database Navigator
3. Open the trees for any of the databases and they will be the same as the default database

**Comment by ShadelessFox** [comment]
Hello @LorrieMonaghan,

Can you please provide footage showing the issue? Thank you.

**Comment by flambchap** [comment]
Reproduces when connecting by URL.

**Comment by ShadelessFox** [comment]
Fixed within #18716

**Comment by Matvey16** [comment]
Verified
