### ISSUE TITLE
Java heap space error when trying to connect to Access DB (.mdb)

### ISSUE THREAD

**Issue by tanj** [dbeaver/dbeaver#18459]
### Description

When attempting to connect to an access database (.mdb jet db) DBeaver fails to connect with a java heap space error.

![image](https://user-images.githubusercontent.com/90219/205960522-6d67f4ba-1e1a-496a-afdc-c140bc3e278a.png)
[dbeaver-access-java-heap.log](https://github.com/dbeaver/dbeaver/files/10168141/dbeaver-access-java-heap.log)

### DBeaver Version

Community Edition Version 22.3.0.202212041619

### Operating System

OS Name	Microsoft Windows 10 Pro, Version	10.0.19043 Build 19043

### Database and driver

1. Microsoft Access .mdb
2. Driver: UCanAccess 5.0.1

### Steps to reproduce

1. Add Access DB connection
2. Click to browse the DB
3. DBeaver tries to connect until heap error occurs

**Comment by ShadelessFox** [comment]
Hello @tanj,

Can you please provide footage showing the issue? Like from the very start, when you connect to the database.

**Comment by tanj** [comment]
https://youtu.be/HyhvAax-XnQ

**Comment by ShadelessFox** [comment]
Thank you.

1. How big is your database file?
2. Is it possible to provide that database file?

If you can't share it with us, perhaps a different solution would be to manually find the cause by stripping the database using external programs until you're left with just a tiny portion of irrelevant data that causes this issue.

**Comment by tanj** [comment]
the database is 521.7M

I can share the file privately, but I don't think I can post it in a public forum like this.

**Comment by ShadelessFox** [comment]
You can email me at `shadelessfox [at] gmail [dot] com`.

**Comment by ShadelessFox** [comment]
I can confirm that the connection takes a long time to establish while DBeaver consumes a lot of memory, but on my machine, it wasn't enough on my machine to show an OOM error.

**Comment by ShadelessFox** [comment]
As a possible workaround, try increasing the memory DBeaver can use.

To do so, go to the installation folder of DBeaver, open the `dbeaver.ini` file, and modify the line that starts with `-Xmx` to `-Xmx4G` to allocate 4GB, for example.

Please let me know if your issue was solved.

**Comment by tanj** [comment]
Increasing the memory allocation limit from 1G to 4G allows it to open without a heap over flow.

Thanks for your help.
