### ISSUE TITLE
Tab key not working anymore to switch between tags inside template ?

### ISSUE THREAD

**Issue by lamazze** [dbeaver/dbeaver#18469]
### Description

I have a template that I use for ages:

```
inner join lid ${alias} on
(
	${alias}.ext = ${column}
	and ${alias}.end = ${cursor}
)
```
I've always use the TAB key to switch from alias to column and vice versa.
With a recent update (cant tell which one), TAB key goes at the end of the template script.

Maybe I'm missing something ?

### DBeaver Version

CE 22.3.0

### Operating System

Windows 10

### Additional context

Editor, templates

**Comment by E1izabeth** [comment]
We added tab as an autocompletion key recently. You can turn it off here 
![image](https://user-images.githubusercontent.com/28875055/206405593-1ce311e5-0188-4b07-ba57-c602a2c0cca2.png)

**Comment by lamazze** [comment]
Isn't it strange to uncheck that option in order to use Tab in templates ?
But anyway it works, thank you.

**Comment by LonwoLonwo** [comment]
Hello @lamazze 
Thanks for the answer.

The `tab` button is now used by default for the autocompletion https://github.com/dbeaver/dbeaver/issues/2316
