### ISSUE TITLE
Не работают кнопки

### ISSUE THREAD

**Issue by Caxm12** [dbeaver/dbeaver#18468]
### Description

Здравствуйте, не могу загрузить БД, т.к. кнопки не активны, 
![Снимок экрана (44)](https://user-images.githubusercontent.com/119796838/206171544-d205d79e-9835-4a99-af20-0ce595a75965.png)
что делать? #

### DBeaver Version

22.3.0

### Database and driver

postgresql 12

### Steps to reproduce

не могу подключить БД т.к. кнопки не работают
![Снимок экрана (44)](https://user-images.githubusercontent.com/119796838/206172651-b9336adb-2bc0-4915-afd0-d73ef90869de.png)
пишет ошибку, "Ошибки возникали при сохранении состояния рабочей среды.
 Рабочее пространство закрыто.
 Рабочее пространство закрыто."

**Comment by E1izabeth** [comment]
Have you tried to reinstall DBeaver?

**Comment by E1izabeth** [comment]
If you can open `File` menu, you could try resetting workspace settings (https://dbeaver.com/docs/wiki/Reset-workspace/).

**Comment by uslss** [comment]
Also, you can try to download the recent DBeaver version https://dbeaver.io/download/

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.

**Comment by seemyown** [comment]
there was the same problem, but reinstalling and resetting did not help

**Comment by E1izabeth** [comment]
Have you tried `Reset UI settings` option?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/4c9ccf31-5d3b-4b75-8437-99e0acf7d7ea)

**Comment by seemyown** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/125135117/040aebab-8d9e-49c8-8ec4-e024d41a318c)
yes, raising this error

**Comment by LonwoLonwo** [comment]
Hello @seemyown 

Did you do it on the last DBeaver version?
Also, please provide logs.  You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by seemyown** [comment]
Yeah, it last version.
I was reload and reset ui, now all right. Thanks a lot for help🙂

**Comment by Yasyyyyya** [comment]
@seemyown такая же проблма. Подскажите, пожалуйста, можете ли вы более подробно объяснить как справиться с тем, что кнопки не активны?

**Comment by seemyown** [comment]
@Yasyyyyya Ну как уже выше описал, я просто перезагрузил приложение и после попробовал сбросить настройки UI. Все получилось.

**Comment by Yasyyyyya** [comment]
Когда сбрасываю насройки, приложение тоже выдает ошибку призакрытии. Как у вас на скрине сверху(( @seemyown

**Comment by ZubovskiyNikolay** [comment]
аналогичная проблема Винда 10, были подключения к 3 бд
переустановил не помогло 

![Image](https://github.com/user-attachments/assets/a4bb8285-e654-40f6-918b-279c9a535df2)
