### ISSUE TITLE
Filter/Sorting icon may be wrong

### ISSUE THREAD

**Issue by mofazhe** [dbeaver/dbeaver#18477]
### Description

![image](https://user-images.githubusercontent.com/41715438/206417384-083ce3b1-9781-445f-a1cc-394b3585a874.png)
These two icons are opposite to the actual functions

### DBeaver Version

22.3.0.202212041619

### Operating System

Windows10 21H2

### Database and driver

SQLite
SQLite JDBC driver 3.39.2.1

### Steps to reproduce

noop

### Additional context

noop

**Comment by ShadelessFox** [comment]
Hello @mofazhe,

I believe they aren't wrong, nor do they represent the opposite of their functions.

The first one represents a filter with a save icon, and it saves filter settings.
The second one represents a dialog with gear, and it's used to edit filters.

Why do you think they are wrong?

**Comment by mofazhe** [comment]
I asked other people around me, they think the same as me, the first button is like a filter function, and the second button is like a save function.

And the icon of the window opened by the second button is also a filter icon
![image](https://user-images.githubusercontent.com/41715438/206437353-4e18f942-0f08-4633-9626-52d4d4c1f628.png)

**Comment by E1izabeth** [comment]
We changed this icon.
