### ISSUE TITLE
eclipse marketplace The installation cannot be completed as requested

### ISSUE THREAD

**Issue by lyh061619** [dbeaver/dbeaver#18475]
### Description

Eclipse Version: 2022-12 (4.26.0) The prompt for installing plug-ins is as follows:
Cannot complete the install because of a conflicting dependency.
  Software being installed: DBeaver IDE 22.3.0.202212041619 (org.jkiss.dbeaver.ide.feature.feature.group 22.3.0.202212041619)
  Software currently installed: Eclipse IDE for Enterprise Java and Web Developers 4.26.0.20221201-1200 (epp.package.jee 4.26.0.20221201-1200)
  Only one of the following can be installed at once: 
    Quick Search 1.1.300.v20211203-1705 (org.eclipse.text.quicksearch 1.1.300.v20211203-1705)
    Quick Search 1.1.400.v20221023-0941 (org.eclipse.text.quicksearch 1.1.400.v20221023-0941)
  Cannot satisfy dependency:
    From: Eclipse IDE for Enterprise Java and Web Developers 4.26.0.20221201-1200 (epp.package.jee 4.26.0.20221201-1200)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group [4.26.0.v20221123-2302,4.26.0.v20221123-2302]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.26.0.v20221123-2302 (org.eclipse.platform.feature.group 4.26.0.v20221123-2302)
    To: org.eclipse.equinox.p2.iu; org.eclipse.text.quicksearch [1.1.400.v20221023-0941,1.1.400.v20221023-0941]
  Cannot satisfy dependency:
    From: DBeaver Local Standalone Application 22.3.0.202212041619 (org.jkiss.dbeaver.app.local.feature.feature.group 22.3.0.202212041619)
    To: org.eclipse.equinox.p2.iu; org.eclipse.text.quicksearch [1.1.300.v20211203-1705,1.1.300.v20211203-1705]
  Cannot satisfy dependency:
    From: DBeaver IDE 22.3.0.202212041619 (org.jkiss.dbeaver.ide.feature.feature.group 22.3.0.202212041619)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.app.local.feature.feature.group [22.3.0.202212041619,22.3.0.202212041619]

### DBeaver Version

CE22.3.0

### Operating System

win 10 pro

**Comment by Matvey16** [comment]
Seems that the error is the same as in #17730

**Comment by lyh061619** [comment]
> Seems that the error is the same as in #17730

Yes, but this problem seems to have existed for a long time. This is a new installation
![20221209090138](https://user-images.githubusercontent.com/15118571/206599213-c03c2bf1-6dd3-4ea9-b8c1-6a7f8b7b169a.png)

**Comment by localtux** [comment]
Jap, same Problem with ArchLinux, Eclipse 2022-12. Cannot install DBeaver. :(

**Comment by flambchap** [comment]
Thank you for your report. We'll fix that with the transition to 2022-12 Eclipse SDK.

**Comment by RoiSoleil** [comment]
Good !!!! When ?

**Comment by flambchap** [comment]
Unfortunately, I cannot give you any estimations at this point.

**Comment by arunvitto** [comment]
_Waiting for the release...

**Comment by arunvitto** [comment]
eager to wait for the update .....

> Unfortunately, I cannot give you any estimations at this point.

**Comment by apetrelli** [comment]
I successfully updated to 22.3.1 and Eclipse 4.26 (2022-12) so I think that this issue can be closed now.

**Comment by Andrei-Pozolotin** [comment]
confirmation:  this combination works:
* Eclipse Version: 2022-12 (4.26.0)
* DBeaver IDE	22.3.1.202212251901

**Comment by cniweb** [comment]
But this combination works not:
- Eclipse Version: 2021-12 (4.22.0.v20211124-1800)
- DBeaver IDE 22.3.3.202301211053

**Comment by E1izabeth** [comment]
> But this combination works not:
> 
>     * Eclipse Version: 2021-12 (4.22.0.v20211124-1800)
> 
>     * DBeaver IDE 22.3.3.202301211053

#17730
