### ISSUE TITLE
[SQLite] ERD throws NPE if system objects are shown in the Navigator

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#18479]
### Description

The latest driver adds system table with specific FK that leads to an error in ERD if that table is shown in the navigator

### DBeaver Version

22.3.0

### Operating System

Any

### Database and driver

SQLite 3.40.0

SQLite JDBC 3.40.0.0

### Steps to reproduce

1. Right click on the connection and enable `Connection view > Show system objects`
2. Doble click on tables folder
3. Select ERD tab

**Expected:** THe diagram is shown
**Actual:** NPE is thrown and ERD is blank

**Comment by ShadelessFox** [comment]
Can't reproduce against the latest driver (3.40.0.0), please provide the database file

**Comment by uslss** [comment]
FR created #18624
