### ISSUE TITLE
Unable to create new connection on MacOS 13.0.1

### ISSUE THREAD

**Issue by OlgaChuianovaArammeem** [dbeaver/dbeaver#18480]
### Description

Can't create new connection, Next button disabled. Test connection is succesfull, Done button just closed connection window and then nothing.

### DBeaver Version

22.3.0 and earlier

### Operating System

MacOS Ventura 13.0.1

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by LonwoLonwo** [comment]
Footage of this issue also will be beneficial.

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
