### ISSUE TITLE
DBeaver ignores default values when Export Data

### ISSUE THREAD

**Issue by fbayer** [dbeaver/dbeaver#18482]
### Description

Right click on a table within the "Database Navigator", then "Generate SQL" and finally "DDL" works just fine - as expected.
I use the "Export Data" function more and more and detected a bug:

Right click on a table within the "Database Navigator", then "Export Data" generates an error like: "SQL Error [1067] [42000]: Invalid default value for 'mtime'"

I guess, that the "Generate SQL" / "DDL" feature considers (all) default values, while the "Export Data" feature doesn't?!

### DBeaver Version

22.3.0

### Operating System

Windows 10 Pro

### Database and driver

MySQL 8.0.30

### Steps to reproduce

1. right click on a table ("Database Navigator")
2. "Export Data"
3. see error message details: there is for example sth. like:
`CREATE TABLE db.tbl (
	col1...,
	col2...,
	ctime timestamp NOT NULL,
	mtime timestamp NOT NULL
)`

But not the correct definition:
`CREATE TABLE db.tbl (
	col1...,
	col2...,
	ctime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	mtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)`

So 'DEFAULT CURRENT_TIMESTAMP' and 'DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP' are missing while dumping / exporting data via the 'Export Data' feature from DBeaver.

**Comment by LonwoLonwo** [comment]
Hello @fbayer 

Do you use the `export data` to another database/data source? And the newly created target table has another syntax for metadata?

**Comment by fbayer** [comment]
Hi @LonwoLonwo,

Yes, I use the export data feature to export the data from one database/server to another.
That has always worked great so far.
But I think the problem are the default values, which is nothing special.

Here's a screenshot from the generated DDL with the defaults:

![image](https://user-images.githubusercontent.com/6584997/206712433-b7eac693-569b-4281-89df-13cf9d741d9b.png)

And here's a screenshot from the export data without the defaults (incl. truncate!):

![image](https://user-images.githubusercontent.com/6584997/206712987-bba1b19a-9849-4ffe-846f-5b69751a6d7b.png)

**Comment by LonwoLonwo** [comment]
Our data transfer instrument is not so smart. He can create only default syntax with NULL/NOT NULL column modifiers. And column types with parameters. That's all.

For now, as a workaround, I Can recommend you create a target table with the SQL Editor and then import data in this table.

**Comment by fbayer** [comment]
@LonwoLonwo: Oh no, why? :/

BTW: It's not a new table, the table does already exist. I've activated the TRUNCATE function in the export data dialog.
Maybe you do that task with the help of a new / temp table and that'd be the "new" table w/0 the default values...

Should I create a feature request or did you already? ;p
Thanks.

**Comment by iraidaa** [comment]
I reproduce the issue in 22.3.1, exporting from one database to another using one MySQL connection.

Here is the DDL of the original table:

![image](https://user-images.githubusercontent.com/49681450/209954478-6dd75b28-7976-4e23-8362-59468820ab52.png)

And here is the DDL of the exported table:

![image](https://user-images.githubusercontent.com/49681450/209954605-2101af19-2fce-4580-affc-01113761efec.png)

**Comment by iraidaa** [comment]
The workaround to create a target table using the SQL Editor first and then import data in this table works. For example, creating an empty table containing a column `NOT NULL DEFAULT CURRENT_TIMESTAMP` and even exporting data from a table with a column `NOT NULL` results in the target table column  keeping the `NOT NULL DEFAULT CURRENT_TIMESTAMP` .

**Comment by LonwoLonwo** [comment]
Unfortunately, I can't reproduce your issue.

![2023-01-25 16_42_38-DBeaver Ultimate 22 3 3 - tbl_timestamps](https://user-images.githubusercontent.com/45152336/214578974-0bb8fa6a-b2f7-490b-ad0b-f43b3d762dc1.png)

I have two tables with the same structure in different catalogs. I did export from the first catalog to the second. I checked the "truncate" option. No errors.

What structure are your tables have? Can you provide DDL for both?

**Comment by fbayer** [comment]
@LonwoLonwo: Sure, here's the source table:

```
-- my_db.my_table definition

CREATE TABLE `my_table` (
  `uid` smallint NOT NULL AUTO_INCREMENT,
  `col1` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` tinyint NOT NULL COMMENT 'bla bla bla',
  `col2` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'blaaa blaaa',
  `col3` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'blaaaaa',
  `buyable_sale_stock_one` tinyint NOT NULL DEFAULT '0' COMMENT 'abc',
  `has_foreign_stock` tinyint(1) NOT NULL DEFAULT '0' COMMENT '12345',
  `export_status` tinyint NOT NULL DEFAULT '0' COMMENT '0 = in queque, 1 = exported, 2 = error',
  `state` varchar(2) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT 'i' COMMENT 'i = insert, u = update, d = delete',
  `state_abc` varchar(2) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT 'i' COMMENT 'This column is for abc jobs.',
  `ctime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`),
  UNIQUE KEY `brand` (`brand`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=462 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`


And here is the target table:

`-- my_db.my_table definition

CREATE TABLE `my_table ` (
  `uid` smallint(6) NOT NULL AUTO_INCREMENT,
  `col1` varchar(64) NOT NULL,
  `status` tinyint(4) NOT NULL COMMENT 'bla bla bla',
  `col2` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'blaaa blaaa',
  `col3` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'blaaaaa',
  `buyable_sale_stock_one` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'abc',
  `export_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0 = in queque, 1 = exported, 2 = error',
  `state` varchar(2) NOT NULL DEFAULT 'i' COMMENT 'i = insert, u = update, d = delete',
  `state_abc` varchar(2) NOT NULL DEFAULT 'i' COMMENT 'This column is for abc jobs.',
  `ctime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `has_foreign_stock` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE KEY `brand` (`brand`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=426 DEFAULT CHARSET=utf8;
```


Actually there are some differences between source and target table, for example the 'has_foreign_stock' column, but that should match, or rather overwrite the target with option truncate first and structure + data export?!

Thanks and have nice day! :)

**Comment by LonwoLonwo** [comment]
And again, I can't reproduce it :( 
Did you change something on the columns mapping page? 
Did you have maybe "recreate" status?

![2023-02-09 15_39_27-DBeaver Ultimate 22 3 4 - my_table](https://user-images.githubusercontent.com/45152336/217815195-70130008-965c-4792-ac25-7eebed6bdefa.png)

**Comment by E1izabeth** [comment]
It's been a long time since no update on this issue. If it's still actual for you, please let me know and provide additional info.
