### ISSUE TITLE
DBeaver randomly switches between two different data-sources.json files

### ISSUE THREAD

**Issue by sinanilyas** [dbeaver/dbeaver#18483]
### Description

After clean installation, I've added all my servers to Database Navigator. One day when I started DBeaver, I saw that Database Navigator was empty and added two servers again. Now, when I start DBeaver, sometimes I see all my servers, and sometimes only two servers.

It seems that there are two different data-sources.json files on the hard drive. And I can't figure out which one will be shown in Database Navigator when I start DBeaver.

The paths of these two files are:
C:\Users\Sinan\\.local\share\DBeaverData\workspace6\General\\.dbeaver\data-sources.json
C:\Users\Sinan\AppData\Local\Packages\DBeaverCorp.DBeaverCE_1b7tdvn0p0f9y\LocalCache\Roaming\DBeaverData\workspace6\General\\.dbeaver\data-sources.json

### DBeaver Version

Community Edition Version 22.2.4.202211062135

### Operating System

Windows 11 Pro Version 21H2 OS Build 22000.1219

### Database and driver

Microsoft JDBC Driver for SQL Server (MSSQL)

**Comment by Destrolaric** [comment]
@sinanilyas Hi, do you have DBeaver installed as Windows store app?

**Comment by sinanilyas** [comment]
> 

Yes, it is installed as Windows Store app.

**Comment by E1izabeth** [comment]
Have you installed WSL on your Windows?

**Comment by sinanilyas** [comment]
Yes, but WSL has no installed distributions.

**Comment by arhayka** [comment]
Hi @sinanilyas,
Unfortunately, the DBeaver Windows Store app is now not available. We'll return to this ticket when it's possible.

**Comment by arhayka** [comment]
Hi @sinanilyas 
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

You can find the logs in your workspaces:
C:\Users\Sinan\.local\share\DBeaverData\workspace6\
C:\Users\Sinan\AppData\Local\Packages\DBeaverCorp.DBeaverCE_1b7tdvn0p0f9y\LocalCache\Roaming\DBeaverData\workspace6\

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still actual for you, feel free to reopen it.
