### ISSUE TITLE
Sharing DBeaver screen under Wayland

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#18487]
**Is your feature request related to a problem? Please describe.**
After switching from Gnome/Xorg to Gnome/Wayland (Fedora), DBeaver window cannot be shared anymore (GoogleMeet, Slack etc).

**Describe the solution you'd like**
Add support for Wayland

**Describe alternatives you've considered**
The only way I recently found is OBS and its virtual camera. Besides troublesome it's still far for optimal.
Another way is to run DBeaver under Xwayland: `env GDK_BACKEND=x11 /usr/share/dbeaver-ce/dbeaver` 

**Additional context**
N/A

**Comment by Destrolaric** [comment]
Unfortunately can't be done from DBeaver side. Our framework uses Eclipse SWT for graphical rendering and unfortunately issue could only be fixed from their side.

**Comment by michal-bartak** [comment]
Are you in a position to motivate the Eclipse team to improve their framework?

**Comment by Destrolaric** [comment]
@michalk-k Unfortunately, this is **extremely** difficult without a personal contribution to the eclipse platform, and even in that case, it will take a lot of time to be merged.

**Comment by michal-bartak** [comment]
I believe you'll find a way. Unless Wayland will fail, it will expand more and more. And nobody wants to use apps without basic functionality.

Please consider finding a way how to run DBeaver under XWayland as a workaround. I mean to mimic `env GDK_BACKEND=x11 /usr/share/dbeaver-ce/dbeaver` command. Just for convenience (some other apps went this way, ie GitKraken). It makes sharing screen as well as copy&paste work properly.

**Comment by michal-bartak** [comment]
For some reason, DBeaver has started to be shared recently (at least in GoogleMeet running in Chrome and FF). Did you do something to DBeaver? Or there were changes to Wayland?

**Comment by Destrolaric** [comment]
@michalk-k Nope, but maybe Java 17 could have fixed that. Not sure.

**Comment by E1izabeth** [comment]
Recently we switched to JDK 17. Not sure if it helped with this issue, but can't remember something else that may bring significant changes to this issue from our side.

**Comment by E1izabeth** [comment]
@michalk-k could you close this issue if it is solved for you? If you encounter it again we can reopen it.
And thank you for update on this issue :)
