### ISSUE TITLE
The SQL generated for SQLite creates the primary key twice on save (persist)

### ISSUE THREAD

**Issue by 0xcrypto** [dbeaver/dbeaver#18491]
### Description

When modifying the SQLite table with dbeaver's graphical interface for an existing table with a primary key, the SQL generated when saving generates PRIMARY KEY constraint twice. 

### DBeaver Version

Community Edition 22.2.5.202211202223

### Operating System

Windows 11 Pro

### Database and driver

SQLite JDBC driver (couldn't find version) https://github.com/xerial/sqlite-jdbc

### Steps to reproduce

- Create a table with a primary key in SQLite using dbeaver graphical interface
- Save it and without closing the tab (not sure if bug persists after closing the tab) create a new foreign key. 
- Now try saving again. This time, the SQL generated would be 
```SQL
-- Create foreign key message_receiver_FK

CREATE TEMPORARY TABLE temp AS
SELECT *
FROM messages;

DROP TABLE messages;

CREATE TABLE messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sender_id INTEGER,
    receiver_id INTEGER,
    CONSTRAINT MESSAGES_PK PRIMARY KEY (id),
    CONSTRAINT messages_FK FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT message_receiver_FK FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
);

INSERT INTO messages
SELECT *
FROM temp;

DROP TABLE temp;
```

As you can see, the constraint `MESSAGES_PK` is declaring PRIMARY KEY twice which would result in an error when clicking persist.

**Comment by LonwoLonwo** [comment]
Hello @0xcrypto 
That's because you marked the id column as an increment column. [INTEGER PRIMARY KEY](https://www.sqlite.org/lang_createtable.html#rowid) == AUTOINCREMENT column in SQLite. 

So you do not need to add a primary key with UI in this situation. It will be added to the CREATE Statement automatically.

**Comment by 0xcrypto** [comment]
@LonwoLonwo yes I understand that. Sorry I wasn't clear with the steps. I create a primary key by using auto increment and not by creating a key. That key constraint is added automatically. That's the bug. The dbeaver is adding that extra constraint automatically.

 I will provide a video demo tonight so that its easier to understand.

**Comment by LonwoLonwo** [comment]
Ok, I can reproduce it.

Thanks for the bug report @0xcrypto

As a small workaround - you can copy this script and execute it without a PRIMARY key string in the SQL Editor.

**Comment by GeorgeCodes17** [comment]
Am I alright to take this ticket?

**Comment by LonwoLonwo** [comment]
We do not have restrictions for contribution @GeorgeCodes17 
So you can try.

**Comment by GeorgeCodes17** [comment]
I couldn't get my local env working unfortunately

**Comment by My1** [comment]
even after removing this extra primary key thing I am getting another error. 
it says that the table already exists for some table changes despite the command list saying to drop the original table, also apparently it tries redoing the table twice for adding 2 foreign keys.

when trying to persist the changes into new tables to avoid the error I get a new message which says `SQL Error: The prepared statement has been finalized`.

eclipse.buildId=unknown
java.version=17.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64
OS: Kubuntu 22.04
dbeaver Version Version 22.3.4.202302060909

<details>
<summary>auto-generated sqlite code with the PK constraints commented out</summary>

```sql
-- Create foreign key Inventar_FK

CREATE TEMPORARY TABLE temp AS
SELECT *
FROM Inventar;

DROP TABLE Inventar;

CREATE TABLE Inventar (
	iid INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT,
	vols_total INTEGER,
	vols_owned TEXT,
	location TEXT,
	title_type TEXT,
	media_type TEXT,
	box_type TEXT,
	col_box INTEGER,
	-- CONSTRAINT INVENTAR_PK PRIMARY KEY (iid),
	CONSTRAINT Inventar_FK FOREIGN KEY (media_type) REFERENCES mediatypes(tid) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT Inventar_FK_1 FOREIGN KEY (box_type) REFERENCES box_types(btype_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO Inventar
SELECT *
FROM temp;

DROP TABLE temp;
-- Create foreign key Inventar_FK_1

CREATE TEMPORARY TABLE temp AS
SELECT *
FROM Inventar;

DROP TABLE Inventar;

CREATE TABLE Inventar (
	iid INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT,
	vols_total INTEGER,
	vols_owned TEXT,
	location TEXT,
	title_type TEXT,
	media_type TEXT,
	box_type TEXT,
	col_box INTEGER,
	-- CONSTRAINT INVENTAR_PK PRIMARY KEY (iid),
	CONSTRAINT Inventar_FK FOREIGN KEY (media_type) REFERENCES mediatypes(tid) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT Inventar_FK_1 FOREIGN KEY (box_type) REFERENCES box_types(btype_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO Inventar
SELECT *
FROM temp;

DROP TABLE temp;

```
</details>
