### ISSUE TITLE
Color by column - Auto coloring

### ISSUE THREAD

**Issue by amosmoss** [dbeaver/dbeaver#185]
Hi,

In addition to the color by column for a specific value, I suggest adding the possibility to auto color a record by a specific column. 
This actually means that for text columns, a record is assigned a color based on a column's text hash function. For numeric values, a record will be assigned a gradient color according the column's value between the result set max and min values.

Examples:
![image](https://cloud.githubusercontent.com/assets/16815760/12749411/25adaf40-c9b9-11e5-9867-850c6ccdff8f.png)

![image](https://cloud.githubusercontent.com/assets/16815760/12749426/35fea1d8-c9b9-11e5-8095-2bafadbda47a.png)

Thanks.

**Comment by serge-rider** [comment]
First version:
![image](https://user-images.githubusercontent.com/6398845/57185375-cba0a080-6ed2-11e9-8681-0b56099629a6.png)

Now all transform and color settings accessible thru main data viewer config action (in the bottom toolbar)

**Comment by amosmoss** [comment]
Amazing!

Thanks :)

**Comment by uslss** [comment]
verified
