### ISSUE TITLE
db freeze when click "Change Password"

### ISSUE THREAD

**Issue by bcag2** [dbeaver/dbeaver#18505]
### Description

db freeze (not responding) see below how to reproduce.

### DBeaver Version

CE 22.3.0.202212041619

### Operating System

Ubuntu 22.04

### Database and driver

Postgresql in docker container

### Steps to reproduce

I go to _Windows_ menu then  _Preferences_ -> _Generality_ -> _Security_ -> _Secure Storage_, in _Description_ table, I have _Linux Integration_ selected. If I click _Change Password_ button, dbeaver freeze (not responding)

### Additional context
_Regional settings_ -> lang -> French

**Comment by LonwoLonwo** [comment]
Hello @bcag2 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by bcag2** [comment]
Thank for you help.  
Here you are my log
[20221213_bcag2-error.log](https://github.com/dbeaver/dbeaver/files/10216570/20221213_bcag2-error.log)
As I saw sqlite warning or error in it, I remove sqlite in db navigator, restart, it freeze always.  
I can work with db, so it is not important !

**Comment by ShadelessFox** [comment]
Hello @bcag2,

Can you please send the thread dump instead? https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump

**Comment by bcag2** [comment]
I don't have jstack installed and don't want install it (478Mo), sorry!

**Comment by ShadelessFox** [comment]
The `jstack` utility comes with Java runtime. If you have DBeaver, then you must have Java runtime somewhere, either embedded or system-wide.

**Comment by bcag2** [comment]
Yes, I have :  
```
$ java --version
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
```
but run jstack, it returns : 
```
$ jstack
« jstack » command is not found, but should be installed with :
sudo apt install openjdk-11-jdk-headless  # version 11.0.17+8-1ubuntu2~22.04, or
sudo apt install openjdk-17-jdk-headless  # version 17.0.5+8-2ubuntu1~22.04
sudo apt install openjdk-18-jdk-headless  # version 18.0.2+9-2~22.04
sudo apt install openjdk-19-jdk-headless  # version 19.0.1+10-1ubuntu1~22.04
```

**Comment by ShadelessFox** [comment]
Weird. You can install the JDK, create a thread dump and uninstall it.

We can't reproduce the issue and can't help you without your assistance.

**Comment by bcag2** [comment]
I installed _openjdk-11-jdk-headless_, here are thread dump :
[thread-dump.txt](https://github.com/dbeaver/dbeaver/files/10247117/thread-dump.txt)

**Comment by ShadelessFox** [comment]
Did you obtain this thread dump while DBeaver was frozen?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
