### ISSUE TITLE
Incorrect result in query with aggregate function (Redshift)

### ISSUE THREAD

**Issue by SerCor** [dbeaver/dbeaver#18504]
### Description

I tried to run this query on a Redshift database

`SELECT DATE_PART("year", sc.sale_date::DATE), SUM(sc.sales) FROM store_sales sc GROUP BY 1;
`
And I get this result:
```
2021	24798549381.024216
2018	24954512598.798773
2022	16202657604.170779
2017	7027361382.795748
2020	21849384368.385742
2019	25707789321.562174
2016	3328.802134
```

The correct result is this one:

```
2019	25705339271.543300
2017	6814069362.250095
2020	21847932891.175105
2018	25166039373.124320
2022	16208155871.270725
2021	24798721216.176021
```

They are slightly similar, but DBeaver is modifying the values and adding one more year to the result for some strange reason. I know DBeaver has the wrong value because I have tried other tools and they all give the correct result.

The query is arriving integrated to Redshift (in the logs it is exactly the same query that I run) but at the time of the results, it is when there is a change.

### DBeaver Version

22.3.0

### Operating System

macOS 12.5.1

### Database and driver

redshift-jdbc42 Driver, Version 2.1.0.3

### Steps to reproduce

Execute the query

`SELECT DATE_PART("year", sc.sale_date::DATE), SUM(sc.sales) FROM sellout_storeproductsellout sc GROUP BY 1;
`
Compare the result with executing the same query in the Redshift Query Editor result

**Comment by LonwoLonwo** [comment]
Hello.
Could you please provide your table DDL and data examples?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
