### ISSUE TITLE
Database Navigator S-TAB Search selection not working in latest release

### ISSUE THREAD

**Issue by Xemptuous** [dbeaver/dbeaver#18519]
### Description

In the earlier 22.1.3 version, when opening the Database Navigator, I would be able to jump between the search and tree-navigation with TAB and S-TAB. Now, I can only TAB (it goes to empty/unknown "buffers" when tabbing from the navigator until about 4 tabs, after which it closes and goes to the active navigator), while S-TAB does nothing.

This was a helpful feature, and now I have to use my mouse to click into the search field, after which I am able to TAB back into the tree. 

### DBeaver Version

22.3.0

### Operating System

Windows 10

### Database and driver

MySQL 8.0

### Steps to reproduce

1. Open Database Navigator
2. Arrow-key movement
3. S-TAB does nothing
4. TAB moves to "next buffer" until it closes after 4 attempts.

### Additional context

Currently using vwrapper, darkest dark theme, relative line numbers, and indent guide plugins.

**Comment by E1izabeth** [comment]
Unfortunately, can't reproduce your issue.
Could you turn on this settings and record a short video of your issue?
![image](https://user-images.githubusercontent.com/28875055/208983383-3b7cab61-4258-42f0-a341-6bb92e2ee5ee.png)

**Comment by Xemptuous** [comment]
@E1izabeth I toggled the options you mentioned, but to no avail (TAB's don't popup).

I initially thought this would be related to using vwrapper, but I tried disabling all addons and still ran into this issue, but I have a 22.1.3 install with the same addons, and it works fine. 

I did find that using <TAB> while focus is in database_navigator will eventually go to an open SQL editor file (selects the name with underline), then another <TAB> will focus that selected file buffer and close the floating database navigator.

This makes me think it's a vwrapper issue with buffers, but I don't get why the upgrade from 22.1.3 to 22.3.0 would cause this.

**Comment by E1izabeth** [comment]
Thank you for investigation.

**Comment by ShadelessFox** [comment]
Hello @Xemptuous,

Can you please provide video footage showing your issue? Thank you.

**Comment by Xemptuous** [comment]
@ShadelessFox I'm unable to replicate the issue exactly now (can't find how to make database navigator a sub-popup window versus its current separate floating window). 
As a separate floating window:
* TAB will cycle through until it eventually gets to the search bar, and will continue looping.
* S-TAB still does nothing

As a window inside the main UI: 
* TAB will not go to search, and will continue to other buffers (SQL Editors).
* S-TAB will navigate between buffers (previous buffer), and sometimes will go back to the database navigator.

I believe it has to do with Vrapper and the use of TAB and S-TAB to cycle through buffers, as when I select the option @E1izabeth mentioned above, TAB's will not show up; hence why a video won't be too helpful.

Nonetheless, here's a video. Super short because of size limits, but it's basically me doing TAB until it hits buffers, then going back to the DB Navigator and doing TAB S-TAB, showing it doesn't go to the search field:

https://user-images.githubusercontent.com/99044751/214740464-ab1357cd-1f45-4217-98de-b2fd6c386987.mp4

**Comment by ShadelessFox** [comment]
Thanks for the response.

1. Are you installing DBeaver via Windows Store?
2. Can you try [resetting UI settings](https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings) to see if it works? **Make sure to backup the workspace before doing so.**

**Comment by E1izabeth** [comment]
It's been a long time since no update on this issue. If it's still actual for you, please let me know and provide additional info.
