### ISSUE TITLE
Native proxy on windows (didn't try other OS) doesn't work

### ISSUE THREAD

**Issue by RoiSoleil** [dbeaver/dbeaver#18511]
### Description

Native proxy on windows (didn't try other OS) doesn't work because in the ZIP package the plugins "org.eclipse.core.net.win32.x86_64" and "org.eclipse.core.net.win32" are missings.

If i  add those plugins in the plugins directory and add it to the bundles.info, it works then.

### DBeaver Version

CE 22.3.0

### Operating System

Windows 10

### Steps to reproduce

Try to set "Native" on Preferences > Network Connection

**Comment by uslss** [comment]
Sorry for the late response. Unfortunately, I cannot reproduce it.
Could you check if the issue still exists for you against the recent version or [early access](https://dbeaver.io/files/ea/) version?

**Comment by RoiSoleil** [comment]
Yes I reproduce it even with early access. The problem is that the Windows Zip package is missing 2 plugins :
org.eclipse.core.net.win32.x86_64_1.1.700.v20220812-1406.jar
org.eclipse.core.net.win32_1.0.100.v20220812-1406.jar
If i add it to the plugins folder and add the 2 entries for those in configuration/org.eclipse.equinox.simpleconfigurator/bundles.info it works.
Please add the 2 plugins to Windows version of dbeaver.

@uslss

**Comment by serge-rider** [comment]
Thanks for bringing this up.
We will fix this issue in the next version

**Comment by uslss** [comment]
verified

**Comment by RoiSoleil** [comment]
Thx !

**Comment by RoiSoleil** [comment]
Reopening. The problem is present in the 24.0.0 package of Windows
