### ISSUE TITLE
Compare function does not work

### ISSUE THREAD

**Issue by did16** [dbeaver/dbeaver#1852]
Hi
Here is my configuration 
- PostgreSQL 9.3.17 , instance name : i1v939, database name: db1939, schema public, table tab1 which contains :  1 and 2 
- Postgresql 9.6.3, instance name: PGPERF, database name : PGPERF, schema public, table tab1 which contains : 1, 2, 4, 4
when I compare these 2 tables with DBeaver I get :
![image](https://user-images.githubusercontent.com/29945788/27909675-118cb546-6252-11e7-9991-cdda55503479.png)
DBeaver tells me **there is no row in my PostgreSQL 9.3.17 table.
Thanks in advance
Didier

**Comment by uslss** [comment]
cannot reproduce an issue.
Ticket closed.
If the issue still actual for you, feel free to reopen the ticket
