### ISSUE TITLE
Statistics tab always becomes active

### ISSUE THREAD

**Issue by rbancells** [dbeaver/dbeaver#18528]
Statistics tab always becomes active when running a SQL script.

Every time I run a script, I have to change from statistics tab to results tab in order to see the results.

It'd be nice to be able to change this behaviour.

**Comment by E1izabeth** [comment]
Thank you for feature request.
It's a duplicate of #17763. The fix will be available in the DBeaver 22.3.1. Also you could try early access version https://dbeaver.io/files/ea/
