### ISSUE TITLE
DBeaver Crashing when trying to connect to ODBC Driver

### ISSUE THREAD

**Issue by tgathje** [dbeaver/dbeaver#18526]
### Description

I am using DBeaver 22.3.0 and I am trying to connect to an ODBC Driver using the ODBC connection. It is using the JDBC:ODBC. Whenever I click connect my DBeaver program quickly crashes and shuts down completely. I know my username and password are correct because I can connect to the ODBC using other programs. I am wondering why my DBeaver keeps crashing and what I can do to fix this problem.

### DBeaver Version

Community Edition 22.3.0

**Comment by uslss** [comment]
@tgathje, unfortunately, cannot reproduce the issue.
Could you provide [logs ](https://github.com/dbeaver/dbeaver/wiki/Log-files)and a video of the issue?

**Comment by tgathje** [comment]
Error was found. Needed to revert back to an older version of the ODBC Driver to make the connection work.
