### ISSUE TITLE
Selected Row Count

### ISSUE THREAD

**Issue by Maglorx** [dbeaver/dbeaver#18521]
### Description

Hi,

After the last dbeaver update (Version 22.3.0.202212131935), I can’t see the selected row count in the result panel. Is there any option for bringing it back?
![dbaver](https://user-images.githubusercontent.com/45281149/208032122-88f3f6c3-6ed1-43d2-88b2-46626ba5cf6d.jpg)

### DBeaver Version

Version 22.3.0.202212131935

### Operating System

windows 10

**Comment by ShadelessFox** [comment]
Hello @Maglorx,

These options were hidden by default.

You can re-enable them here:

![image](https://user-images.githubusercontent.com/35821147/208100503-51376abc-32b8-431c-8b8b-3ccbd1ea68bc.png)
