### ISSUE TITLE
cannot add foreign key in gui on mariadb

### ISSUE THREAD

**Issue by poltpolt** [dbeaver/dbeaver#18537]
### Description

adding foreing key via dbeaver gui os not possible. 
When i select target table and try to add foreign key and pick source table the keys are not shown

### DBeaver Version

22.3.0

### Operating System

Linux (OpenSuse)

### Database and driver

1. Mariadb 

### Steps to reproduce

1. Create table 
-- wrazidlo_test_daily.CiagiKarty definition

```sql
CREATE TABLE `CiagiKarty` (
  `ciag_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `nazwa` varchar(200) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `LastUpdate` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `data_utworzenia` datetime NOT NULL DEFAULT current_timestamp(),
  `prc_id` int(11) DEFAULT NULL,
  `LastUpdate_prc_id` int(11) DEFAULT NULL,
  `zatwierdzenie_prc_id` int(11) DEFAULT NULL,
  `gotowe_prc_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`ciag_id`),
  UNIQUE KEY `Ciagi_UN` (`nazwa`),
  KEY `CiagiKarty` (`ciag_id`) USING BTREE,
  KEY `CiagiKarty_FK` (`prc_id`),
  KEY `CiagiKarty_FK_1` (`LastUpdate_prc_id`),
  KEY `CiagiKarty_zatwierdzenie_prc_id` (`zatwierdzenie_prc_id`),
  KEY `CiagiKarty_gotowe_prc_id` (`gotowe_prc_id`),
  CONSTRAINT `CiagiKarty_FK` FOREIGN KEY (`prc_id`) REFERENCES `PrcKarty` (`prc_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `CiagiKarty_FK_1` FOREIGN KEY (`LastUpdate_prc_id`) REFERENCES `PrcKarty` (`prc_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `CiagiKarty_gotowe_prc_id` FOREIGN KEY (`gotowe_prc_id`) REFERENCES `PrcKarty` (`prc_id`) ON UPDATE CASCADE,
  CONSTRAINT `CiagiKarty_zatwierdzenie_prc_id` FOREIGN KEY (`zatwierdzenie_prc_id`) REFERENCES `PrcKarty` (`prc_id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
```

2. create another one

```sql
CREATE TABLE CiagiKroki (
	ciag_id int(10) unsigned NOT NULL,
	nr_procesu TINYINT UNSIGNED NOT NULL,
	CONSTRAINT CiagiKroki_UN UNIQUE KEY (ciag_id,nr_procesu)

)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;
CREATE INDEX CiagiKroki_ciag_id_IDX USING BTREE ON CiagiKroki (ciag_id);
```

3. and during the creation of 2 or after try to add forefing key for ciag_id 
DBeaver gui does not allow it, when I select source table CiagiKarty the ciag_id is not displayed so i have to use
sql code directly to create foreign key.

```sql
 ALTER TABLE CiagiKroki ADD CONSTRAINT CiagiKroki_ciag_id FOREIGN KEY (ciag_id) REFERENCES CiagiKarty(ciag_id) ON UPDATE CASCADE;
```

This is probably some regresion as it used to work

### Additional context

Direct connection/no ssh tunnel

**Comment by LonwoLonwo** [comment]
Hello @poltpolt 

Did you refresh the catalog after the `CiagiKroki` table creation? Maybe DBeaver didn't find new table at all?

**Comment by poltpolt** [comment]
yes i did

**Comment by E1izabeth** [comment]
Have you tried to switch Unique key to Primary key?
![image](https://user-images.githubusercontent.com/28875055/208969993-274f130e-c02c-4cbd-8ab1-bbe5b3df473b.png)

**Comment by poltpolt** [comment]
With primary key it woks - is it supposed to work only for primary?

**Comment by ShadelessFox** [comment]
Hello @poltpolt,

It's not clear what your issue is about. Can you please provide footage showing your issue?

**Comment by E1izabeth** [comment]
It is supposed to work with any unique key.

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
