### ISSUE TITLE
DBeaver Community "Error AutoRegisterSchemeHandlersJob"

### ISSUE THREAD

**Issue by YomarFerreira** [dbeaver/dbeaver#18530]
### Description

An error already known by the dbeaver community (https://github.com/dbeaver/dbeaver/issues/14882) was displayed to me when starting it after installing it on a new pc. Version 23.0.2, windows 11. Are there any instructions to fix this?
![Captura de tela 2022-12-18 182644](https://user-images.githubusercontent.com/91606858/208320841-fc6136e4-dd54-4eb5-9369-eac94c18dca6.png)

### DBeaver Version
Community 22.3.0.202212070729

### Operating System
Windows 11 Home

### Steps to reproduce
Just run it

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by YomarFerreira** [comment]
Hello LonwoLonwo,
First I would like to thank you for the quick response and willingness to resolve the issue.
But I need to say that the problem solved itself after I installed other applications like Java, Eclipse, VSCode, IntelliJ, MySQL, NodeJs, PgAdmin, Postman... among others. I believe that one of them ended up installing some dll necessary for dbeaver that was missing...

**Comment by LonwoLonwo** [comment]
That happens sometimes.

So, your problem is solved? Can I close the ticket?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.

**Comment by sarthaksh21** [comment]
same error in new DBeaver version 24.0.1
![image](https://github.com/dbeaver/dbeaver/assets/165733477/107a6bd8-5354-473b-9c40-aeacc89464d6)

![image](https://github.com/dbeaver/dbeaver/assets/165733477/fd43c582-42ac-4a66-9bfc-67becee56135)
