### ISSUE TITLE
An ERROR during starting program

### ISSUE THREAD

**Issue by IVKUD95** [dbeaver/dbeaver#18539]
### Description

The ERROR: Could not initialize class org.jkiss.dbeaver.registry.driver.Driver Descriptor
Reason:
Could not initialize class org.jkiss.dbeaver.registry.driver.DriverDescriptor

It pops up immediately after starting the program (in ‘Navigator error’ window) and block any other functions.

When i try to close ‘Navigator window’ or push ‘OK’, it appears again.

Program version: 22.2.3
The ERROR arises after updating to later versions, too.

Could you help me to solve this problem, please?

![image](https://user-images.githubusercontent.com/121086346/208611503-ff608bff-379f-4187-a4b8-b4b53898a504.png)

### DBeaver Version

Community edition 22.2.3

### Operating System

Windows 10 Enterprise 21H2

### Steps to reproduce

1. Open DBeaver
2. Pop up the ERROR

**Comment by ShadelessFox** [comment]
Hello @IVKUD95,

How did you upgrade to the newer version? What type of distribution is that?

**Comment by IVKUD95** [comment]
It's community edition downloaded from official web site

I used two ways for updating:
- deleting of current version, and downloading and installing the newest version from official site
- pop up notification in time of opening program

P.S. I've found and installed an old version of program (21.2.1), it works normal, but doesn't have a part of new functional.

**Comment by ShadelessFox** [comment]
I assume you've used the installation file, not the zip archive?

**Comment by IVKUD95** [comment]
@ShadelessFox yes, I used the installation file

**Comment by ShadelessFox** [comment]
Please try installing the latest version (22.3.0) https://dbeaver.io/download/

**Comment by IVKUD95** [comment]
The problem is resolved. Thank you.
