### ISSUE TITLE
Make temporary tables editable through data editor (PostgreSQL)

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#18549]
Currently it doesn't seems to be possible to use the data editor for e.g. inserting new rows to a temp table.

Example:
1. Create a simple tempory table:
`create temp table myt(a int8, b bytea);`
2. Select data
`select * from myt;`

Now I don't have the '(+)' at the bottom of the data editor to insert a new record into the table.

Because I work with bigger bytea data, it is not really possible to wrap them into an insert statement.

I tried to refresh using F5 but that doesn't seem to work for temporary tables.

Any suggestion on how to solve this problem.

**Comment by E1izabeth** [comment]
@JamesInform please turn on `Show utility objects` option. You can find it through navigator's context menu -> Connnection view -> Custom...
![image](https://user-images.githubusercontent.com/28875055/208991774-3326f385-8952-41ee-bf47-d9a938062680.png)

or in the connection settings -> Navigator -> Navigator View : Customize..
![image](https://user-images.githubusercontent.com/28875055/208991841-d460e46d-5e71-4edd-a22e-45fc4778c878.png)

Then you will see special schemas for temporary tables and get an ability to edit table data through data editor for select statement or work with this table as with any other table.
![image](https://user-images.githubusercontent.com/28875055/208992210-a811cde2-88f6-4106-bbf4-3e121bfd8517.png)

**Comment by JamesInform** [comment]
Wow!

It works!

Thanks a lot.
