### ISSUE TITLE
Dbeaver does not backup Postgresql if the connection details are in the Url. 

### ISSUE THREAD

**Issue by ZeerDonker** [dbeaver/dbeaver#18553]
### Description

Dbeaver does not backup Postgresql if the connection details are in the Url. 
And that is selected to connect with. 

It will try to get the connection details from the Host, Port and Database variables.

### DBeaver Version

Community Edition 22.3.0

### Operating System

Windows 10

### Database and driver

1. Driver : Postgresql JDBC driver
2. Database: Postgresql 11.15

### Steps to reproduce

1. Try to connect to a postgress database with a URL which is not the default. (A dns url, which is not localhost.)
2. Do not change the default Host, Database and Port variables. 
3. Connection succeeds
4. Try to backup the database with the tools. 
5. Its says it fails with connecting to the localhost, which is not in the Url, but defined in the Host.

**Comment by E1izabeth** [comment]
Thank you for bug report.
