### ISSUE TITLE
Crashing when opening spatial data

### ISSUE THREAD

**Issue by ergumayagay** [dbeaver/dbeaver#18557]
### Description

I get this error when I try to open spatial data

[error log.txt](https://github.com/dbeaver/dbeaver/files/10279588/error.log.txt)

### DBeaver Version

Community Edition 22.3

### Operating System

macOS Ventura 13.1

### Database and driver

PostgresSQL 14.6

### Steps to reproduce

Click on spatial button or click on geometry

**Comment by E1izabeth** [comment]
Thank you for bug report. It's a duplicate of  #18117
