### ISSUE TITLE
Exasol driver cannot be installed automatically (maven:/com.exasol:exasol-jdbc.RELEASE not found) - new base version

### ISSUE THREAD

**Issue by HerrB92** [dbeaver/dbeaver#18556]
### Description

Try to install/configure an Exasol connection (any dummy host entry will do). If Dbeaver tries (or you try in the Driver Manager etc.) to download the driver, you might get the error message "maven:/com.exasol:exasol-jdbc.RELEASE not found" and no driver gets installed.

If you get that problem as well, then the problem is related to changes, where the driver is located since 7.1.16 (I think). Until 7.1.4 the driver was located within the Exasol repo, with 7.1.16 "central" is used:
https://mvnrepository.com/artifact/com.exasol/exasol-jdbc

The underlying issue seems to be, that the "Add connection" wizard uses an older driver version by default and then tries to find the driver. As Exasol has removed their own Maven repo completely during a website redesign, the download fails (e.g. 7.1.14 is given in Maven to be available from https://maven.exasol.com/artifactory/exasol-releases/com/exasol/exasol-jdbc/7.1.14/exasol-jdbc-7.1.14.jar, which does not return anything, now).

Immediate solution: Database -> Driver Manager -> Exasol -> Edit -> Libraries -> double click on com.exasol:exasol-jdbc:RELEASE and change the artifact to:
Artifact Id (unchanged): exasol-jdbc
Group Id (unchanged): com.exasol
Version (updated): 7.1.16
Fallback Version: RELEASE
Click on Ok -> Download/Update (which should work now) -> Close all windows and restart Dbeaver

General solution: The default driver version for the Exasol driver should be increased to at least 7.1.16.

### DBeaver Version

Community Edition 22.3.0

### Operating System

Windows

### Database and driver

Exasol

### Steps to reproduce

Try to install/configure an Exasol connection (any dummy host entry will do). If Dbeaver tries (or you try in the Driver Manager etc.) to download the driver, you might get the error message "maven:/com.exasol:exasol-jdbc.RELEASE not found" and no driver gets installed.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by LonwoLonwo** [comment]
Related: https://github.com/dbeaver/dbeaver/discussions/18525

**Comment by LonwoLonwo** [comment]
Fixed in 22.3.2.
Will be available [here](https://dbeaver.io/) on 2023-01-09

**Comment by melissagile** [comment]
Thanks for the input everyone! So had a similar issue and was redirected here. Followed these instructions and now receiving the following connection error:

`java.io.IOException: TLS connection to host (10.150.210.11) failed: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. If you trust the server, you can include the fingerprint in the connection string: 10.150.210.11/CA988988C015F859CB954AB9904FA62A5E466891352CD204843BB43A8BCE636F:8563.`

I assume I just need to add this last part to some permissions somewhere, but not sure where. Any tips?

**Comment by E1izabeth** [comment]
@melissagile it happened because the new driver uses TLS by default instead of ChaCha20. To connect to the database you could set `fingerprint` property to the value specified in the message (`CA988988C015F859CB954AB9904FA62A5E466891352CD204843BB43A8BCE636F`).
Another option is to set `legacyencryption `property to `1`.

Driver properties could be set in the connection settings.
