### ISSUE TITLE
Support for RisingWave Streaming Database

### ISSUE THREAD

**Issue by hzxa21** [dbeaver/dbeaver#18550]
**Is your feature request related to a problem? Please describe.**
Support [RisingWave](https://www.risingwave.com/) Streaming Database in DBeaver

**Describe the solution you'd like**
RisingWave is an open-source cloud-native streaming database compatible with PostgreSQL. We only need to enable a subset of DBeaver PostgreSQL features supported by RisingWave so we will have a RisingWave implementation for `PostgreServerExtensionBase`.

**Describe alternatives you've considered**
Using native PostgreSQL driver doesn't work since the default port/user/database are different and there are some PostgresSQL features that not supported in RisingWave (e.g. trigger, tablespace, ...).

**Comment by E1izabeth** [comment]
> Recently, we have added more supports on the pg system tables and functions in RisingWave so now DBeaver users are able to use the standard postgres connector to connect to RisingWave and explore the basic functionalities in DBeaver. Therefore, there is no need to introduce the RisingWave DBeaver plugin for now.

https://github.com/dbeaver/dbeaver/pull/18551#issuecomment-1611481061

**Comment by LonwoLonwo** [comment]
The implementation will be available in the next DBeaver version, 23.3.4, on 05-02-2024.

A New Connector was added.
Some folders are hidden for RisingWave.
And tables/views DDL reading will provided by a database.
