### ISSUE TITLE
Blinking cursor barely visible on dark theme

### ISSUE THREAD

**Issue by Corxo** [dbeaver/dbeaver#18568]
### Description

The blinking cursor is almost invisible when a cell in edited directly from the results table.

https://user-images.githubusercontent.com/8331877/209159055-059c6003-bf81-4cc8-aa85-33b896202c5d.mp4

### DBeaver Version

Community edition 22.3.0.202212070729

### Operating System

Ubuntu 22.04

### Steps to reproduce

1. Select the dark theme
2. Launch a SELECT and edit any cell in the results

**Comment by Destrolaric** [comment]
@Corxo Hi, I think this may happen if the system theme and DBeaver theme are opposite colors. Could you check if this is the case?

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it.
