### ISSUE TITLE
Stored procedures debugger

### ISSUE THREAD

**Issue by bouyeijiang** [dbeaver/dbeaver#1856]
How to debug stored procedures for db2 or sql server

**Comment by GiantCrocodile** [comment]
Not sure what you mean with debugging stored procedures. You can use explain statements with DBeaver; there is a small icon for this in top right corner, next to the icons for execute SQL statement (hotkey CTRL+SHIFT+E to trigger 'Explain execution plan').

**Comment by serge-rider** [comment]
Stored procedures debugging not yet implemented (but we are working on this feature)

**Comment by bouyeijiang** [comment]
expect for this feature

**Comment by iamnorbiato** [comment]
will this really happen ? SP debug ?

**Comment by serge-rider** [comment]
Yes.
Initially it will work for PostgreSQL (#2556)
I'm not yet sure about 4.3.4 release but quite soon.

**Comment by serge-rider** [comment]
Closing along with #2556 (see comments there)
