### ISSUE TITLE
Layout issue, minimize icon is not centered

### ISSUE THREAD

**Issue by BraveMomo** [dbeaver/dbeaver#18574]
### Description

The minimize icon of the window of the entire software is centered up and down, aligned with the maximize icon, while the minimize icon of the lower subwindow is not centered up and down, which looks very awkward, please optimize and improve
![XU%R_0}FXI8@W9EVV$6B~ P](https://user-images.githubusercontent.com/22335503/209248754-0fac8470-1711-4e56-8010-51d3fe951cf2.png)

### DBeaver Version

22.3.0

**Comment by E1izabeth** [comment]
DBeaver is built on Eclipse platform and these parts of ui are not managed by DBeaver. So, we can't do something with it.
The main window's minimize icon depends on your OS. Eclipse uses such icon for minimize action everywhere, so, maybe it's even stated in https://github.com/eclipse-platform/ui-best-practices. If you wonder about the reasons for that or want to propose suggestion, I suppose you could open an issue or ask in the discussions here https://github.com/eclipse-platform/.github.
