### ISSUE TITLE
Hide users in the database navigator tree

### ISSUE THREAD

**Issue by Rajachekka** [dbeaver/dbeaver#18577]
**Is your feature request related to a problem? Please describe.**
In DBeaver application, Under teradata connection manager name i'm seeing all the unnessary user names, which i don't want to see. 
I just want to see only database names.
Earlier our company used Toad data point software. There we are having option to filter to choose only Databases but that option missing in Dbeaver application.

**Comment by Rajachekka** [comment]
![image](https://user-images.githubusercontent.com/121291977/209328045-40dc44e4-481f-4d65-9244-0e6e729e90b0.png)
![image](https://user-images.githubusercontent.com/121291977/209328095-d456e881-3add-46b9-93a2-700701eaec86.png)
![image](https://user-images.githubusercontent.com/121291977/209328114-f5688eeb-53d3-4a63-bddf-cda7a8832f1a.png)
attaching here the respective screenshots of coonection manager mentioned above

**Comment by LonwoLonwo** [comment]
Hello.

We can probably add an option like "hide users" for Teradata.
