### ISSUE TITLE
Autocomplete deletes schema name

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#18571]
### Description

If auto-complete is used to finish fully qualified name with a name of a quoted table that has dots in it's name, the schema name gets deleted

### DBeaver Version

22.3.1

### Operating System

Any

### Database and driver

Postgres 12

### Steps to reproduce

1. Start typing a query with database name and schema name
2. Select a table with dot(s) in it's name from the proposed tables

**Expected:** Table name looks like `db_name.schema_name."TaBle.Name"`
**Actual:** Table name absorbs schema name `db_name."TaBle.Name"`

**Comment by ShadelessFox** [comment]
Can't reproduce:

https://user-images.githubusercontent.com/35821147/209478205-b570cfe7-d045-42fc-91ce-eeefbeff4426.mp4

**Comment by Matvey16** [comment]
Yeah, the steps to reproduce were not specific enough. It is reproducible for tables that have a dot in their name e.g. `te.st`
