### ISSUE TITLE
Executing procedures

### ISSUE THREAD

**Issue by FarshidShekari** [dbeaver/dbeaver#18583]
### Description

For executing a procedure after setting params values, raised an error like bellow:
`SQL Error [17041] [99999]: Missing IN or OUT parameter at index:: 1`

and also there's a problem with generated code for executing:
`CALL ABC.RegisterAdmin(:PAR_TITLE,:PAR_DESCRIPTION,:USERNAME,:IP,?,?,?);`

my procedure name is case sensitive like `ABC."RegisterAdmin"` but that was generated without considering it;
the last three params are my out params; I need to access them after running the procedure.
and after setting variables, they're didn't set as strings in the preview query in the modal when setting params.

Thank you for considering these issues.

### DBeaver Version

 22.3.0.202212041619

### Operating System

Windows 11

### Database and driver

Oracle

**Comment by LonwoLonwo** [comment]
Hello @FarshidShekari 

Can you please provide a procedure example?

**Comment by FarshidShekari** [comment]
This makes no difference even testing with your procedures ;). 
Just sample:

```
CREATE OR REPLACE Procedure ABC."RegisterAdmin"
   ( name_in IN varchar2 )

IS
   cnumber number;

   cursor c1 is
   SELECT course_number
    FROM courses_tbl
    WHERE course_name = name_in;

BEGIN

   open c1;
   fetch c1 into cnumber;

   if c1%notfound then
      cnumber := 9999;
   end if;

   INSERT INTO student_courses
   ( course_name,
     course_number )
   VALUES
   ( name_in,
     cnumber );

   commit;

   close c1;

EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
```

**Comment by LonwoLonwo** [comment]
Ok, I understood. Generated by the "Execute stored procedure" command has an incorrect procedure name without quotes.

![2023-02-02 14_39_31-DBeaver Ultimate 22 3 3 - _orcl_ Script-102](https://user-images.githubusercontent.com/45152336/216315351-12d31cf6-9c1b-4fa0-88eb-02d3f3b54c76.png)

Thanks for the bug report.
