### ISSUE TITLE
allow generated sql to appear on more than one line of dbeaver sql file editor

### ISSUE THREAD

**Issue by Kevinoh47** [dbeaver/dbeaver#18581]
**Is your feature request related to a problem? Please describe.**
Using BASH, my shell script iterates over a set of files on disk and generate a set of SQL statements, each statement corresponding to future db work based on a particular file on disk. Then the shell script stitches together the complete set of sql statements into a single .sql file and writes that file to disk. 

I then open the .sql file in dBeaver (Version 22.3.0.202212070729 on Mac). 

Unfortunately, the entire script appears on a single line. I have tried adding sql comments that include manual  line feeds between statements, escaped and unescaped "\n" and "\r' characters, all sorts of dead ends. Hours of googling has yielded nothing. 

**Describe the solution you'd like**
I would like a way to insert a line break character in a .sql script that has been generated via a BASH console shell script , such that when the .sql script produced by the shell script is later opened in dBeaver, the line breaks are used to format the script in the editor. The sql statements inside the generated .sql script should be executable from within the sql editor either individually or by executing the entire script at once without regard to the line break characters. 

**Describe alternatives you've considered**
At present, I must either ignore the fact that the entire script appears on a single line, which is not practical, or manually search and replace a designated set of characters with manually entered carriage returns, which is doable but frustrating.

**Additional context**
This feels like so obvious a problem that I must have missed something somewhere. I have been through the dBeaver documentation and spent hours googling, so I have tried to tell the interwebs what I am experiencing using my words, to no avail. My apologies if this is a a complete non-issue.

**Comment by E1izabeth** [comment]
Does this issue still actual to DBeaver 22.3.5?

**Comment by E1izabeth** [comment]
If you still can reproduce it, could you provide an example part of such file for us?

**Comment by E1izabeth** [comment]
It's been a long time since no update on this issue. If it's still actual, please let me know and provide additional info to reproduce.
