### ISSUE TITLE
Multiple SQL Statements with combined output in 1 result tab.

### ISSUE THREAD

**Issue by wattpuppy** [dbeaver/dbeaver#18580]
I would like to be able to run many sql statements and have the results all send to the same output tab.

Query script to run with (Ctrl+Alt+Shift+X)
select 'table_1', count(*) from table_1;
select 'table_2', count(*) from table_2;
...
select 'table_400', count(*) from table_400;

Desired output (echoing sql commands optional) (dots added for justification)

'TABLE_1'|COUNT(*)|
---------+--------+
table_1  |     5400|

'TABLE_2'|COUNT(*)|
---------+--------+
table_2  |        100|

.....

'TABLE_400'|COUNT(*)|
---------+--------+
table_400  |   33009|

Is there a way of sending all the output to a single results tab or can that be added as a feature?

**Comment by E1izabeth** [comment]
Does [SQL Terminal](https://dbeaver.com/docs/wiki/SQL-Terminal/) satisfy your needs?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
