### ISSUE TITLE
Configuration of eclipse integration plugin preferences exception

### ISSUE THREAD

**Issue by lyh061619** [dbeaver/dbeaver#18594]
### Description

Configuration of eclipse integration plugin preferences

 Expand database, click User Interface, and then move the mouse to click Database editors to prompt The currently displayed page contains invalid values

### DBeaver Version

CE22.3.1

### Operating System

win 10 pro

### Database and driver

MariaDB 10.6.11 / org.mariadb.jdbc 3.0.7

### Steps to reproduce

expand database, click User Interface, and then move the mouse to click Database editors to prompt The currently displayed page contains invalid values

### Additional context

![20221226194322](https://user-images.githubusercontent.com/15118571/209545269-a0607d72-edff-426b-ae01-258cd9793f57.png)

**Comment by flambchap** [comment]
Thank you for your report.

**Comment by Destrolaric** [comment]
@lyh061619 Hi, Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it.
