### ISSUE TITLE
Column widths

### ISSUE THREAD

**Issue by greekcntr** [dbeaver/dbeaver#18591]
### Description

What happened to the "Columns widths: fit values" option? I think it disappeared in this latest version. It used to be a right click in the context menu, and before that it was in the preferences. Did it get moved again to somewhere else? 

### DBeaver Version

Version 22.3.1.202212231715

### Operating System

Windows 10

**Comment by Matvey16** [comment]
Fixed in the latest version (as a hotfix). Build with a hotfix can be downloaded at dbever.io
