### ISSUE TITLE
Add images for all Eclipse DBeaver extensions

### ISSUE THREAD

**Issue by RoiSoleil** [dbeaver/dbeaver#18608]
### Description

Icon for JKISS in About Eclipse IDE is too small/not good :

![image](https://user-images.githubusercontent.com/3462260/209661392-f6b2d869-2705-4b6a-ba2a-c186159e400b.png)

### DBeaver Version

All

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
We need to add images for all Eclipse DBeaver extensions. Or at least for the main DBeaver extension. And we need new icons for this, probably.

**Comment by serge-rider** [comment]
Icons for Office and CE features were fixed.
Redundant branding was removed.
