### ISSUE TITLE
Update wiki articles Reset UI Settings & Reset Workspace 

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#18609]
We changed the UI behavoir in #18474 and need to update these articles:
- [Reset UI Settings](https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings) 
- [Reset Workspace](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)

**Comment by G33kNoob** [comment]
thanks for update, now i know how to reset my ui manually

**Comment by ShadelessFox** [comment]
https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings
