### ISSUE TITLE
sort fields by name in record view mode not available any more

### ISSUE THREAD

**Issue by casualuser** [dbeaver/dbeaver#18618]
### Description

With new version 22.3.1 sort button is not available any more and it was the life saver for a long time for searching a filed name with a lot of fields
Please put it back in 22.3.2 or explain how to re-enable it if it's just hidden by default in 22.3.1

![image](https://user-images.githubusercontent.com/1243074/209800064-38cc9ab7-1bb7-4743-ba3a-cab1f84a83ee.png)

### DBeaver Version

CE 22.3.1

### Operating System

macOS Ventura 13.1

### Database and driver

PostgreSQL 14.0

### Steps to reproduce

1. open Record view with 'Tab' key
2. ...

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
Fixed (already in devel)

**Comment by Matvey16** [comment]
Verified
