### ISSUE TITLE
Mongo query document counts failed

### ISSUE THREAD

**Issue by Korov** [dbeaver/dbeaver#18616]
### Description

query document count by `db.getCollection("alert_record").countDocuments();` and get an error `TypeError: Cannot find function countDocuments in object {}. (js#1)`

### DBeaver Version

DBeaver EE Version 22.3.0.202212131935

### Database and driver

Database name and version: mongo 5.0.8

**Comment by ShadelessFox** [comment]
Hello @Korov,

Please use `count()` instead.

Let me know if it solves your issue.

**Comment by Korov** [comment]
> 

Yes， but when I use DataGrip to query by function `count()` get an warn `DeprecationWarning: Collection.count() is deprecated. Use countDocuments or estimatedDocumentCount.`

**Comment by ShadelessFox** [comment]
I thought it was the other way around. Thanks for clarifying.

**Comment by ShadelessFox** [comment]
No need to close the issue. We need to add missing parts of Mongo's JS API.

**Comment by serge-rider** [comment]
Fixed
