### ISSUE TITLE
Ability to fix width columns in result grid

### ISSUE THREAD

**Issue by Moridin11** [dbeaver/dbeaver#18627]
**Is your feature request related to a problem? Please describe.**
Possibly fit to screen bug

**Describe the solution you'd like**
I frequently have limited screen width and it would be nice if there was a way (even if only for a 1 query at a time) that I could have the columns "fit to screen".  The fit to screen that exists doesn't function in the way I expect.  It would even be useful to simply say all column have a width of n.

**Describe alternatives you've considered**
I have tried using the built in width function as well as manually changing the column widths.  The problem with this, is if I change the where clause then it resets the query and I have to do it all again.

**Comment by Destrolaric** [comment]
Hi, you can right-click on columns and use `Columns width: fit screen` write me if it helps.
![image](https://user-images.githubusercontent.com/20579256/210792393-8c5351ea-ec6a-4e54-96a9-3694e8698ff9.png)

**Comment by Moridin11** [comment]
> 

This doesn't appear to work in 22.3.0.  I have a wide monitor so in DBeaver I have it side by side, which could be why it isn't working correctly.

**Comment by ShadelessFox** [comment]
Hello @Moridin11,

Can you please provide footage showing your issue? Thank you.

**Comment by Moridin11** [comment]
> 

This is more difficult, my system is not in an online system.  I will see what I can do but in the mean time I will try to describe it better.  

I have a 32" monitor and DBeaver is fullscreen.   
I have the DB Navigator minimized to take full advantage of the screen width.  
I have 2..n queries open in split screen at least 1 on each side.

When I execute a query on either side where I am returning more results then the width would allow.
I right click on a column and click on `columns width: fit to screen` it does not fit it to my window.  I think it is fitting it to the total screen width.

**Comment by ShadelessFox** [comment]
Try adjusting the following option:

![image](https://user-images.githubusercontent.com/35821147/213692985-88548361-7504-488b-b014-77c75edf4693.png)

As you can see, I got pretty ridiculous results, yet all columns fit.

Please let me know if it helps.

**Comment by Moridin11** [comment]
First.  Awesome response time :). 

Upon initial glance that very well might have done it.  I will play around with it and make sure.  Thank you this is extremely useful.  

That being said, when I made that change DBeaver initially crashed.  I have been experiencing this a little after I started trying to use row colors. So I'm not worried about it, and it doesn't crash outright just if I try doing certain things like `ctrl-f` it will give me an error message and ask me to restart DBeaver.  I am not saying there should be another ticket for this, just wanted to inform you of everything that happened.

**Comment by ShadelessFox** [comment]
A new ticket may be required if your issue continues to appear.

**Comment by Moridin11** [comment]
Ok no worries.   Do you want me to close this ticket out once I finish testing?

I know likely not the right place but is there anyway to persist row colors?

**Comment by ShadelessFox** [comment]
Yes, please close it once you're pleased with the results.

You don't need to do anything special to save row coloring. The only exception is that coloring isn't persisted on result viewers opened from the SQL Editor because they aren't linked to entities from the navigator tree.

**Comment by Moridin11** [comment]
This solution looks good.  Thanks.
