### ISSUE TITLE
SQLite - DDL for Views is broken in CE 22.3.1, worked in CE 22.3.0

### ISSUE THREAD

**Issue by gulux** [dbeaver/dbeaver#18630]
### Description

The display of DDL does not work for Views of SQLite databases in CE 22.3.1, but used to work in CE 22.3.0 (and before).
![DBeaver-22 3 0-SQLite-DDL-View-OK](https://user-images.githubusercontent.com/49115449/210130564-1d09c188-55b7-46e8-805d-605718f78e71.png)
![DBeaver-22 3 1-SQLite-DDL-View-broken](https://user-images.githubusercontent.com/49115449/210130567-b559f39c-ee90-4765-a627-61092539a979.png)

Error message:  -- Can't generate DDL: table editor not found for org.jkiss.dbeaver.ext.sqlite.model.SQLiteView;

### DBeaver Version

CE 22.3.1

### Operating System

OpenSuse Tumbleweed - Linux

### Database and driver

Database: SQLite 3.40.0
Driver: sqlite-jdbc-3.40.0.0.jar  org.serial

### Steps to reproduce

1. Open Database with existing connections (configuration persisted through upgrade/downgrade of DBeaver)
2. Click on arbitrary View.
3. Click on Properties/Definition Tab
4.  DDL for View does not show, but error message is displayed: -- Can't generate DDL: table editor not found for org.jkiss.dbeaver.ext.sqlite.model.SQLiteView;
5. Definition display works for tables.
6. Used to work in 22.3.0

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @gulux
