### ISSUE TITLE
WinGet - Failed to install (Hash mismatch) - 22.3.1

### ISSUE THREAD

**Issue by HeyZiko** [dbeaver/dbeaver#18631]
### Description

When attempting to install / update DBeaver using winget command line utility, an error is encountered. The downloaded installer hash does not match the hash provided in DBeaver's winget repository entry.

### DBeaver Version

22.3.1

### Operating System

Windows 10 (10.0.19045)

### Database and driver

N/A

### Steps to reproduce

1. Launch PowerShell / Windows Terminal as Administrator.
2. Execute `winget upgrade --id "dbeaver.dbeaver"`
3. winget downloads the installer successfully.
4. Installation is skipped because the installer hash did not match, and winget will not bypass hash checks when running as Administrator.

![image](https://user-images.githubusercontent.com/2326213/210154318-9e200de7-d8bb-401d-967f-f7aaa1b61701.png)

### Additional context

This is the same issue as https://github.com/dbeaver/dbeaver/issues/15132 and https://github.com/dbeaver/dbeaver/issues/16169

**Comment by Destrolaric** [comment]
Hi, @HeyZiko. Unfortunately, this can happen when we release a hotfix for the already-released version. Could you wait until Monday? It will be solved by the new DBeaver version.

**Comment by HeyZiko** [comment]
You bet, thank you

**Comment by PsyEng** [comment]
Sry to hijack the thread, but the same happened again for version 24.0.0.
