### ISSUE TITLE
The connection attempt failed: java.io.EOFException

### ISSUE THREAD

**Issue by hugo-torres-factorypal** [dbeaver/dbeaver#18638]
### Description

Whenever I try to establish a connection to my work postgreSQL database, I get the error below, with no further info.

![DBeaverError](https://user-images.githubusercontent.com/100767085/210257528-1cde598c-db50-4430-b91d-039c705cb740.png)

This was working properly until I received a message from DBeaver asking to update drivers. After doing so, this happened. Already tried to restart the computer and reinstall DBeaver, but with no success.

### DBeaver Version

Community Edition 22.3.1.202212251901

### Operating System

Windows 10 Enterprise x64

### Database and driver

Not sure about database version, only that is PostgreSQL. Driver is the one provided by DBeaver

### Steps to reproduce

1. Input all the connection settings and text the tunnel configuration
2. Click on "Test Connection" 
3. Receive the error above

### Additional context

Using an SSH tunnel

**Comment by LonwoLonwo** [comment]
Hello @hugo-torres-factorypal 

You can try to change your default driver to another version in your Connection settings:
 
![2023-01-02 21_08_54-DBeaver 22 3 1 - _master_ Script-29](https://user-images.githubusercontent.com/45152336/210266396-d856757b-5010-44b2-94ec-a6aa62cd5a69.png)

It may help.

**Comment by LonwoLonwo** [comment]
Also, maybe this discussion will be helpful: https://github.com/dbeaver/dbeaver/issues/1156

**Comment by hugo-torres-factorypal** [comment]
@LonwoLonwo tried several different versions of the driver and the problem persists. Also checked the discussion and checked my parameters to rue out the possibility of it being something like the user who had an extra "/" at the end and it doesn't seem to be the case here

**Comment by LonwoLonwo** [comment]
Did you use a host or URL connection type?

![2023-01-05 11_21_54-Connect to a database](https://user-images.githubusercontent.com/45152336/210736798-3786ff04-3ce0-4cee-823c-8c6d695723fe.png)

Because if you are using URL connection type, you need to change your SSH settings https://github.com/dbeaver/dbeaver/issues/17861

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.

**Comment by bchkhaidze** [comment]
Hello. I'm having simillar issue.
I'm connecting with ssl on:
![image](https://github.com/dbeaver/dbeaver/assets/63901465/c0caf05f-56f1-468b-92c7-be0527607a5a)

I have the latest driver:
![image](https://github.com/dbeaver/dbeaver/assets/63901465/97eee9cb-6545-4741-9ad9-72e0866d011f)

It is working fine with pgAdmin4 and psql.

**Comment by E1izabeth** [comment]
@bchkhaidze Did you configure connection by specifying host and port or url?

**Comment by bchkhaidze** [comment]
> @bchkhaidze Did you configure connection by specifying host and port or url?

I did with host and port.
![image](https://github.com/dbeaver/dbeaver/assets/63901465/f96ee53a-f1de-4ecf-a146-271f789a3ccb)

Dbeaver Version:
Version 23.0.4.202305071722

OS:
Windows 11

**Comment by szabozoltan69** [comment]
For me also appeared this issue, and the solution was the usage of a Profile.
In SSH tab (right up) there is a Profile dropdown. If it was empty, did not work.
If I chose a profile, with the same parameters, it began to work fine.
(It was misleading that the tunnel configuration setting was also good in the non-working situation.)

**Comment by MarcosRugerio** [comment]
Hi to all:

I have the same issue, I use DBbeaver con Linux Fedora38. I created a connection but when I try to use a second the same error message 

![image](https://github.com/dbeaver/dbeaver/assets/23510012/86c5cc1a-ca8e-4a4d-a04d-53cb45718c7f)
My driver was updated, I use the latest version of the software.
![image](https://github.com/dbeaver/dbeaver/assets/23510012/53285f04-b4d8-45ef-838d-3cbf8c059331)

**Comment by juanhoil** [comment]
I have the same issue.

Problem:
When trying to connect to my PostgreSQL database using port 5433, I encountered a connection error.

Solution:
I changed the connection port to the default port, 5432, and the connection worked smoothly.

**Comment by e-compagno** [comment]
Same issue. I am connection via port 15432. It started worked fine when I created a profile under SSH tab (with empty settings)
<img width="981" alt="Screenshot 2023-11-28 at 11 34 42" src="https://github.com/dbeaver/dbeaver/assets/49021750/cff3d4fb-c7e3-46b3-89e7-cef0da5face7">

**Comment by alpha951** [comment]
> 
> Because if you are using URL connection type, you need to change your SSH settings #17861

Yes this solved my problem. Thanks @LonwoLonwo

**Comment by pvanhungit** [comment]
It work when I did tunnel ssh to my local by command line. So I disable ssh tunnel config in dbeaver tool.

then the host name is just localhost

**Comment by a3gh** [comment]
> It work when I did tunnel ssh to my local by command line. So I disable ssh tunnel config in dbeaver tool.
> 
> then the host name is just localhost

His comment made me figure it out. When having SSH tunnel enabled, you are obviously connecting to the remote server first (via SSH), before attempting to connect to the database. After connecting to the server, the server is no longer at a remote IP, but rather just `localhost`, so the database host had to be adjusted to `localhost` in my case. Makes sense.

**Comment by ferricae11** [comment]
Hi, I have been reading all your answers and tried several methods in order to solve this problem. I have not been able to fix it yet in DBeaver 24.3.4. 

I get this errror when I try the connection: **_EOFException java.io.EOFException_**
![Image](https://github.com/user-attachments/assets/1246e8fd-3fbd-4290-8ee6-44471fa7f1f3)

Could someone give me a hand with it? I have tried **creating a test profile**, **updating the drivers** in the **driver settings**, etc. 

Appreciate your help!

Best regards.

**Comment by daoane** [comment]
I encountered the problem on a Windows computer, while a second Windows computer and third with Linux were fine.

* close DBeaver
* remove AppData/local/DBeaver (don't touch AppData/Roaming/DBeaverData!)
* start DBeaver

Before: EOFException; After: Everything worked as expected

**Comment by SirPeace** [comment]
> * close DBeaver
> * start DBeaver
> 
> Before: EOFException; After: Everything worked as expected

Just restarting the app surprisingly helped, thanks

**Comment by ahmad-ben** [comment]
Still encountering the same issue. When I tried to connect a second database (for tests) with a different port, it showed the problem. However, after **stopping the first database** and making the second one `5432`, it normally connected.

**Comment by ahmad-ben** [comment]
> Still encountering the same issue. When I tried to connect a second database (for tests) with a different port, it showed the problem. However, after **stopping the first database** and making the second one `5432`, it normally connected.

Important note, i am using Docker.
and this works for me:
```
    ports:
      - "5433:5432"
```
**Keep the container's internal port 5432**

**Comment by cobrien706** [comment]
FYI you'll encounter the same initial error if you mistakenly assume the DB is PostgreSQL and not another one like Oracle. Guess how I know. 🙄
