### ISSUE TITLE
"New Constraint from Selection" context menu item opens wrong dialog

### ISSUE THREAD

**Issue by dlizotte-uwo** [dbeaver/dbeaver#18639]
### Description

When viewing the Properties tab of a table, right-clicking on a Column Name, and choosing the "New Constraint from Selection" item from the context menu, the "Create index for table" dialog is opened instead of the "Create foreign key" dialog.

### DBeaver Version

Community Edition 22.3.1

### Operating System

macOS Monterey 12.6.1

### Database and driver

sqlite3 driver

### Steps to reproduce

Open the "Properties" tab for a column in a table, right click a column name, choose "New Constraint from Selection" from the context menu.

**Comment by Destrolaric** [comment]
Yep, confirmed. Thank you for the info.
