### ISSUE TITLE
Persistent Query Manager for the Community version

### ISSUE THREAD

**Issue by anazzani** [dbeaver/dbeaver#18645]
Would really love to be able to retrieve queries issued in previous sessions.

I have no idea how this is implemented in the Pro version, but I was thinking something like the SQL history offered in Oracle SQLDeveloper.

Are there any plans to port this feature in the free version? BTW, I'm using Postgres, just in case...

Thanks.

**Comment by LonwoLonwo** [comment]
Hello @anazzani 

No, we do not have plans to add the Query Manager history in the Community version.
Query Manager history needs a database, and the Comunity version does not have included databases.
Query Manager history is available in the PRO versions: https://dbeaver.com/
