### ISSUE TITLE
The PG query array data log appears  Can't parse array

### ISSUE THREAD

**Issue by travelliu** [dbeaver/dbeaver#18644]
### Description

PostgreSQL

```
PostgreSQL 13.4 (Debian 13.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
```

Query pg_proc

```
select * from pg_proc where proname='to_timestamp';
```

log 

```
2023-01-03 21:28:47.778 - Can't parse array
2023-01-03 21:28:47.781 - Can't parse array
```
![2023-01-03 at 21 29](https://user-images.githubusercontent.com/7792329/210368138-8f3ed632-9a47-4705-a69f-15f3c7aca02c.png)

General problem: There is an error in the conversion array data

![2023-01-03 at 21 42](https://user-images.githubusercontent.com/7792329/210368828-86722823-732e-44ab-b85b-aaca7f8f95ee.png)

### DBeaver Version

22.3.1

### Operating System

MacOS 10.12

### Database and driver

1. PostgreSQL 13.4
2. PostgreSQL JDBC Driver [42.2.20]

**Comment by E1izabeth** [comment]
Thank you for bug report.
