### ISSUE TITLE
Where the button of 'order by' ...?

### ISSUE THREAD

**Issue by Kei-garak** [dbeaver/dbeaver#18640]
**Is your feature request related to a problem? Please describe.**
The button was lost, or I'm not find that.

**Describe the solution you'd like**
Please show the button or how to on the there?

**Additional context**
![image](https://user-images.githubusercontent.com/121852440/210314693-93302cdb-7def-4ee0-ab8a-1fde025fad6f.png)

**Comment by iambudi** [comment]
Filter and Sort By in the column header has been moved to the popup menu by clicking triangle icon. I miss the previous style, it's straight forward and reduces click motion.

**Comment by uslss** [comment]
#18589
