### ISSUE TITLE
Table with more than one geometry columns

### ISSUE THREAD

**Issue by bad-ch** [dbeaver/dbeaver#18643]
### Description

If you have a table with more than one geometry columns nothing happens => blank screen. In my opinion you have 3 options:

- Take always the first geometry column

OR 

- Take the first visible attribute from the filter

OR 

- Add a geometry field combobox on bottom of the spatial view, where the user could select the geometry field (default is the first) 

### DBeaver Version

Community 22.3.1

### Operating System

Windows

### Steps to reproduce

Show data in a table with more than one column

**Comment by uslss** [comment]
@bad-ch, what database do you use?

**Comment by bad-ch** [comment]
MS SQL Server

**Comment by uslss** [comment]
Could you provide table DDL?

**Comment by bad-ch** [comment]
Yes no problem

**Comment by bad-ch** [comment]
Sorry I have to correct something, with MS SQL Server it's not possible to show any spatial data, I get only weird data in the spatial data column and the and it's not possible to activate the spatial mode with the tab on the left side (Community **and EE version**). With the EE version I see the message in the column that the software could not parse the data (I think because it uses different drivers). But with PG it works, if you want I could provide a DDL with PG ?

**Comment by ShadelessFox** [comment]
Hello @bad-ch,

Can you please provide footage showing your problem?

**Comment by bad-ch** [comment]
Attached you get 2 screenshots (one for Community Version the other one for EE)
![2023-01-13_08-33-29](https://user-images.githubusercontent.com/25458830/212264643-dd35bac5-f699-4ec1-837b-9375c25624ba.png)
![2023-01-13_08-37-36](https://user-images.githubusercontent.com/25458830/212264653-8dbb198b-ba59-46cd-97ae-c731a32ff888.png)

**Comment by ShadelessFox** [comment]
Thank you.

It seems like it would happen to a table with a single geometry column, too.

In fact, the issue seems familiar to #18736

What database and driver version are you using?

**Comment by bad-ch** [comment]
yes it has nothing to do with the count of geometry columns, in this table we have two geometry columns (only one is visible :o). We are using this the suggested driver (for EE it's a different one)
![2023-01-13_10-32-45](https://user-images.githubusercontent.com/25458830/212286938-d73cee84-b26a-4268-b1c5-37922d8f0ec7.png)

**Comment by ShadelessFox** [comment]
Can you please provide a screenshot of the "Test Connection" dialog?

**Comment by ShadelessFox** [comment]
Just a clarification: GIS support for SQL Server is only available in PRO products.

**Comment by bad-ch** [comment]
I know (but it would be good to see at least the wkt), that was the reason to install the EE version but there I have the "Error parsing geometry..." problem from my screenshot above. Like you whished the screenshot from the "Test Conection":
![Screenshot 2023-01-13 110321](https://user-images.githubusercontent.com/25458830/212293471-8e11ee53-8e9a-4f37-b65c-fded75f7cec7.png)

**Comment by ShadelessFox** [comment]
Unfortunately, it's not possible.

The BLOB you see is the actual presentation of the geometry data.

In PRO products, we perform some magic to decode this meaningless sequence of bytes to something meaningful, such as WKT.

**Comment by ShadelessFox** [comment]
Thanks for the screenshot

**Comment by ShadelessFox** [comment]
I'm unable to reproduce your issue against the same database (15.00.4188, in fact) and driver version:

![java_HwumdTVbj8](https://user-images.githubusercontent.com/35821147/212298885-4dca9f2e-34f3-494e-baa5-d24d4794e37b.png)

Can you try executing the following script to see if the created table contains valid data?

```sql
CREATE TABLE SpatialTable (
    id int IDENTITY (1,1),
    GeomCol1 geometry,
    GeomCol2 AS GeomCol1.STAsText()
);

INSERT INTO SpatialTable (GeomCol1)  
VALUES (geometry::STGeomFromText('LINESTRING (100 100, 20 180, 180 180)', 0));

INSERT INTO SpatialTable (GeomCol1)  
VALUES (geometry::STGeomFromText('POLYGON ((0 0, 150 0, 150 150, 0 150, 0 0))', 0));  
```

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
