### ISSUE TITLE
Export in copying jsonb rows 

### ISSUE THREAD

**Issue by asc0910** [dbeaver/dbeaver#18648]
### Description

When exporting MySQL database to PostgresSQL database I got the following error for json field.
> column "words" is of type jsonb but expression is of type character 

### DBeaver Version

22.3.1.202212251901

### Operating System

Windows

### Database and driver

MySQL Server 8.0 to PostgresSQL 14

### Steps to reproduce

1. Select a table of a MySQL (MySQL doesn't have json field but it has a text field)
2. Export Data
3. Select target container as a PostgresSQL table with json field.
4. Proceed

**Comment by uslss** [comment]
unfortunately, cannot reproduce it.
@asc0910, Could you provide ddl for both tables?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.

**Comment by moontide** [comment]
> unfortunately, cannot reproduce it. [@asc0910](https://github.com/asc0910), Could you provide ddl for both tables?

# MySQL (DDL and sample data) #
```SQL
CREATE TABLE `test_for_export_mysql_json_column_to_pgsql_json_column` (t text, j json);

INSERT INTO `test_for_export_mysql_json_column_to_pgsql_json_column` (t, j) VALUES ('{}', '{}');
```


# PostgreSQL #
```SQL
CREATE TABLE "test_for_export_mysql_json_column_to_pgsql_json_column" (t json, j json);
```

# Error log when exporting (MySQL to PostgreSQL) or importing (to PostgreSQL from MySQL) #

**DBeaver 26.2.0 for Linux**
<pre>
org.jkiss.dbeaver.DBRuntimeException: Error while finishing result set fetching into 'public.null'
  Error while finishing result set fetching into 'public.null'
    Can't insert row
      SQL 错误 [42804]: ERROR: column "j" is of type json but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 93
        ERROR: column "j" is of type json but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 93
</pre>

# Cause #
It seems that dbeaver doesn't cast MySQL JSON value (which presented in plain SQL String format: `'{}'`) to PostgreSQL JSON data type (`'{}'::JSON`).
