### ISSUE TITLE
Comment of Oracle 

### ISSUE THREAD

**Issue by clearLove8080** [dbeaver/dbeaver#18666]
### Description

When some comments sql submitted, but the soft fell in error, what should I do?

### DBeaver Version

Dbeaver 7.2.4

**Comment by LonwoLonwo** [comment]
Hello @clearLove8080 
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
