### ISSUE TITLE
Can not open connection to Hive

### ISSUE THREAD

**Issue by nsaolapu** [dbeaver/dbeaver#18663]
### Description

I trying to connect one HIveDB from DBeaver and i am getting the error as shown above . i can connect to the server using other tools like Putty, WinScp and Hive Shell. Any help regrading this is highly appreciated.

### DBeaver Version

22.0.4

### Operating System

Windows 10 Enterprise 

### Database and driver

1 . Database HIVE and Driver "org.apache.hive.jdbc.HiveDriver"

hive-jdbc-uber-2.6.5.0-292.jar

### Steps to reproduce

1. I try to connect to the database using credentials
2. i get this error 
Could not open client transport with JDBC Uri: jdbc:hive2://{HiveServer}:10001/{DB}: java.net.ConnectException: Connection refused: connect
  java.net.ConnectException: Connection refused: connect
  java.net.ConnectException: Connection refused: connect
    Connection refused: connect
    Connection refused: connect
I kept server name as hidden.

**Comment by LonwoLonwo** [comment]
Hello @nsaolapu 
Maybe this thread will be helpful for you: https://community.cloudera.com/t5/Support-Questions/Hive-JDBC-Could-not-open-client-transport-with-JDBC-Uri/td-p/101772

**Comment by LonwoLonwo** [comment]
Did you use the URL connection type or host?

![2023-01-05 12_12_38-Connect to a database](https://user-images.githubusercontent.com/45152336/210743682-2e70f0c8-1cbf-4d55-b578-f710eee93b78.png)

**Comment by nsaolapu** [comment]
Hi ,

I did use host and specified the our server name there. .

**Comment by ShadelessFox** [comment]
Hello @nsaolapu,

I'm sorry for the late response. Are you using an SSH tunnel?

**Comment by nsaolapu** [comment]
We arr not using SSH . its not required . i have specified the connection
that we are using in mail trail above

**Comment by ShadelessFox** [comment]
It looks like the supplied server URL/address is not accessible. Are you sure it's available through other tools without an SSH tunnel?

**Comment by E1izabeth** [comment]
It's been a long time since no update here. If you encounter this issue again, please let me know and provide additional info.
