### ISSUE TITLE
CSV is read only

### ISSUE THREAD

**Issue by ig-z** [dbeaver/dbeaver#18676]
### Description

Please help.

I'm not able to edit, add or remove because it's in read only. I am not able to turn read-only off in any way. Could someone please assist? 

I have other larger files that I want to be able manipulate, remove columns union tables, etc.

Thank you.

<img width="557" alt="Screen Shot 2023-01-05 at 9 51 16 AM" src="https://user-images.githubusercontent.com/119462253/210847843-6c69bad1-4505-436d-b9ed-68c3333ba80c.png">

### DBeaver Version

Version 22.3.1.202212251901

### Operating System

macOS Monterey Version 12.5.1 (21G83)

### Database and driver

Flat files / CSV
Apache License
Version 2.0

### Steps to reproduce

Create new CSV connection and select local folder

**Comment by ShadelessFox** [comment]
Hello @ig-z,

The CSV driver is read-only. This is a limitation of the driver itself (https://github.com/simoc/csvjdbc).
