### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by 210hcl** [dbeaver/dbeaver#1867]
I'm a Chinese user and I don't know how to change the software to Chinese UI.
If you could tell us how to change language, we will appreciate for it.

**Comment by serge-rider** [comment]
All national localization were removed from DBeaver 4.x because they were outdated. We plan to return them back in version 5.x.

**Comment by serge-rider** [comment]
Please check 4.2.2.
You can enable Chinese localization by running DBeaver with command line parameter `-nl zh`.
