### ISSUE TITLE
Transaction Log not available using clickhouse connection

### ISSUE THREAD

**Issue by giopappy** [dbeaver/dbeaver#18670]
### Description

When connecting to a clickhouse database the trasaction log button is greyed. I've checked that it is available using other kind of connections (eg oracle)

### DBeaver Version

Community Edition 22.3.0

### Operating System

Windows 11

### Database and driver

ClickHouse (Legacy)

**Comment by LonwoLonwo** [comment]
Hello. 

Seems to be a strange legacy driver restriction:

![2023-01-05 15_27_41-DBeaver  C__Users_anvolka_work_DbeaverP_dbeaver-workspace-idea  - C__Users_anvol](https://user-images.githubusercontent.com/45152336/210796417-407896a9-70d2-4b08-97d3-6ad1826cdd6f.png)

As I can see, it works fine for the Not Legacy driver.
Can you use not legacy driver?

![2023-01-05 16_54_02-DBeaver Ultimate 22 3 1 - _default 1_ Script-94](https://user-images.githubusercontent.com/45152336/210796842-75df1438-67bc-43e7-bb3b-8456fdf5b1b3.png)

**Comment by Destrolaric** [comment]
Legacy driver doesn't support transactions. They were added after 2021, I think.
https://github.com/ClickHouse/ClickHouse/issues/19352
