### ISSUE TITLE
Filter is applied to the wrong column

### ISSUE THREAD

**Issue by GAEREL** [dbeaver/dbeaver#18685]
### Description

In the table data (grid) view, I want to filter a column : filter is applied on wrong column

Step 1 : open the filter view on 'column2' column
![image](https://user-images.githubusercontent.com/43636651/210973267-8df7fa13-e5c0-4cb5-8d3e-5322b50a51c3.png)
(I want to filter on column2)

Step 2 : filter is applied on the first column ("id" column) (and display its values)
![image](https://user-images.githubusercontent.com/43636651/210973378-06b8da72-20bb-416d-9020-d10d12a0e6d5.png)

it seems to be ok if I select all the column before
![image](https://user-images.githubusercontent.com/43636651/210973435-51308a64-879c-4085-a0be-28c74250dc2d.png)
(filter is applied on the column2. It's ok.)

Thanks for help !

### DBeaver Version

Version 22.3.1.202212251901

### Operating System

Windows 11

### Database and driver

PostgreSQL 13.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

**Comment by ShadelessFox** [comment]
Hello @GAEREL,

Thanks for the bug report.

The issue was already fixed in https://github.com/dbeaver/dbeaver/issues/18572, and the fix will be available in the next version (22.3.2).
