### ISSUE TITLE
Missing filter and ordering icons

### ISSUE THREAD

**Issue by walhalla247** [dbeaver/dbeaver#18690]
### Description

I am missing the filter and ordering icons in the column header. A reset to View default and updates did not change anything.

![image](https://user-images.githubusercontent.com/13706823/211257700-a3db6db9-dc61-4140-af0d-bb5c823e6477.png)

### DBeaver Version

22.3.1

### Operating System

linux

**Comment by ShadelessFox** [comment]
Hello @walhalla247,

Please see https://github.com/dbeaver/dbeaver/issues/18671
