### ISSUE TITLE
variables don't bind when using lowercase in the naming

### ISSUE THREAD

**Issue by bickgr** [dbeaver/dbeaver#18706]
### Description

When using the DBeaver @set command to set a variable, when executing the script the parameter binding is looking for the variable name in UPPER CASE.  The variables tab shows the variable created using same case as the @set command.  

### DBeaver Version

Version 22.3.2.202301060755

### Operating System

macOS 13.0.1

### Database and driver

PostgreSQL
PostgreSQL JDBC Driver

### Steps to reproduce

1. Open a new script
2. set a variable using @set, with name using some mix of uppper and lower case letters
3. use the variable in a SELECT statement and execute

Example of above
`@set userIdList = (SELECT "Id" FROM public."AspNetUsers" WHERE "UserName" IN ('greg@perf.labs', 'BickBick@perf.labs', 'bick2@perf.labs'))

-- title: AspNetUsers
SELECT
	*
FROM
	"AspNetUsers" anu
WHERE
	"Id" IN (:userIdList)
ORDER BY
	anu."UserName"
;`
![parameter bind](https://user-images.githubusercontent.com/46910221/211429101-3bb8287f-3d2d-46ca-ba9b-1c5a37c7673e.png)
![Variables tab](https://user-images.githubusercontent.com/46910221/211429105-550231bd-a9ef-4c5e-ab36-3982beb3423f.png)

**Expected results**
variables with any mix of upper and lower case letters will be recognized during script run so long as the set and the call match up

**Actual results**
Bind parameters during script execution is taking variable names and looking for the upper case version of the variable name.  Since variable was set using mix case the variable's value is not populated at run time and a pop up is presented for variable binding.  

If the variable is name with all upper case during the @set command and called using : later in the script with mixed case the variable replacement happens successfully.  

### Additional context

This was working properly on DBeaver version 22.3.1 and looks to have broken in 22.3.2

**Comment by E1izabeth** [comment]
Thank you for bug report.
As a temporary workaround you can set your variable value directly in the bind dialog.

**Comment by E1izabeth** [comment]
`@unset` has the same flaw
