### ISSUE TITLE
Can the menu display of MySQL and Oracle view modes be consistent?

### ISSUE THREAD

**Issue by xiamaocheng** [dbeaver/dbeaver#18705]
Can the menu display of MySQL and Oracle view modes be consistent?

**Comment by LonwoLonwo** [comment]
Hello @xiamaocheng 

Please can you be more specific? What for you want it?

**Comment by E1izabeth** [comment]
It's been a long time since no update on this issue. If it's still actual for you, please let me know and provide additional info.
