### ISSUE TITLE
Release 22.3.2.202301060755 no longer supports SSO (browser-based) login for Snowflake

### ISSUE THREAD

**Issue by AVBTeague** [dbeaver/dbeaver#18700]
### Description

The SSO (browser-based) login option for Snowflake is missing from the Edit Connection dialog.

### DBeaver Version

22.3.2.202301060755

### Database and driver

Snowflake JDBC

**Comment by LonwoLonwo** [comment]
Hello @AVBTeague 
Thanks for the report.

That was done intentionally as part of our extended support of Snowflake databases. Right now, SSO authentication through UI, as for most other databases, is exclusive to our PRO versions which you can try for free on [dbeaver.com](https://dbeaver.com/trial/)
Configuring SSO authentication through the JDBC driver remains unaffected so that it can be configured manually.

**Comment by AVBTeague** [comment]
Wait. So, the functionality was deprecated in the Community version? We were never on Pro, just the Community version, and had SSO as an Authentication option. Those who didn't upgrade to this version still have it. What is the "manual" configuration? Selecting externalbrowser? Selecting this or snowflake still requires the password to be saved with the connection, correct?

**Comment by LonwoLonwo** [comment]
Please try to change the setting for the ability to use an empty password In the driver settings:

![2023-01-10 18_08_05-DBeaver 22 3 2 - _postgres_ Script-95](https://user-images.githubusercontent.com/45152336/211587875-91383273-5385-484b-823e-6dac44bd646f.png)

**Comment by AVBTeague** [comment]
OK. Tried that. I'm still prompted for a password.

**Comment by pratikgujral** [comment]
How was this issue resolved? I am using the community version as well, and am being prompted to enter password despite choosing externalbrowser as the Atuhentication method.

**Comment by AVBTeague** [comment]
Not resolved. I have to save my login in the Edit Connection dialog's Authentication (Database native) section.

**Comment by LonwoLonwo** [comment]
I can't reproduce.
If the password field is empty, DBeaver does not put it as empty property, just no password in properties.
Could you provide examples and footage?

More about external browser connection - https://github.com/dbeaver/dbeaver/issues/18515

**Comment by E1izabeth** [comment]
It's been a long time since no update here. Let me know, if the issue still actual, and provide additional information.

**Comment by relcodedev** [comment]
I tested with latest dbeaver as of today and the latest snowflake 3.14.2.  I am getting a 401 but if I switch to external browser i can login without issue.
