### ISSUE TITLE
A bug with "Connect by URL" causes a schema exception

### ISSUE THREAD

**Issue by BY-KING** [dbeaver/dbeaver#18716]
### Description

1 use PostgreSQL，and the server choose "connect by url" ，like jdbc:postgresql://localhost:5432/database_A
3. If you perform operations on databases other than database_A, all the data you see is from the database_A database. The same is true for delete operations. For example, if there is a database database_B, you will see the database_A data under the database_B menu If you delete the schema, the database_A data will be deleted. This is very misleading and can lead to serious bugs if applied to production environments

### DBeaver Version

CE 22.3.2

### Operating System

Win 10

### Database and driver

PostgreSQL 12.5

### Steps to reproduce

1. connect to the database using connect by mode
2. Enter the URL, for example, JDBC: postgresql: / / localhost: 5432 / database_A
3. Create a database, such as database_B
4. Open the database_B menu
5. You will see the data in database_A
6. Now perform the schema deletion
7. Open the database_A menu
8. You will see that database_A is missing that schema

**Comment by LonwoLonwo** [comment]
Hello @BY-KING 

Thanks for the bug report.

![2023-01-10 18_42_19-DBeaver 22 3 2 - _postgres_ Script-95](https://user-images.githubusercontent.com/45152336/211596230-08ce9e50-9909-492b-b238-e875c2b0d3db.png)

So, we can see our schemas when we use the usual port/host connection, but the schema list is messed up when we use a URL connection + show all databases.
