### ISSUE TITLE
Remove Save Filter Settings button from filters menu

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#18719]
### Description

1. Sometimes it is not simple to understand what this option is for https://github.com/dbeaver/dbeaver/issues/18642
2. This option isn't working for the resultset in SQL Editor

https://user-images.githubusercontent.com/31996417/211580939-2ffd4046-5a97-4723-bade-0003719b7457.mp4

### DBeaver Version

CE 22.3.2

### Operating System

win10

**Comment by serge-rider** [comment]
Fixed
