### ISSUE TITLE
Unable to open .mdb file using MS Access (UCanAccess) plugin

### ISSUE THREAD

**Issue by JonathanTSilva** [dbeaver/dbeaver#18714]
### Description

When trying to connect with an Access file (`.mdb`) using the **MS Access (UCanAccess)** connection  the following message is given (see image below):

```
Decoding not supported.  Please choose a CodecProvider which supports reading the current database encoding.
---
UCAExc:::5.0.1 Decoding not supported.  Please choose a CodecProvider which supports reading the current database encoding.
Decoding not supported.  Please choose a CodecProvider which supports reading the current database encoding.
```

![image](https://user-images.githubusercontent.com/58694273/211531895-1be267aa-121c-4d1a-949c-25349a9c0024.png)

I performed the same procedures in these different environments, which also gave the same error:

- Linux
 - flatpak installation
 - .deb installation
- Windows 10

### DBeaver Version

Community Edition 22.3.2

### Operating System

Pop!_OS 22.04 LTS

### Steps to reproduce

1. New Database Connection
2. MS Access (UCanAccess)
3. Connect by: Host
4. Fill **Path** with the file path
5. Fill the database **Password**
6. Click in Finish
7. Download (for download outdated drivers)

**Comment by LonwoLonwo** [comment]
Hell @JonathanTSilva 

What driver are you using? 
Can you please try to change the driver version? Connection settings -> Driver Settings -> Libraries.

**Comment by JonathanTSilva** [comment]
Hello @LonwoLonwo!

I'm using the latest UCanAccess driver: 5.0.1.

I didn't find the option you mentioned to change the driver version. Would this option be on this screen?

![image](https://user-images.githubusercontent.com/58694273/211555155-97f9afe5-604d-4b5a-b80f-0542daaa2e29.png)

**Comment by LonwoLonwo** [comment]
Yes, sure.

![2022-12-22 17_18_44-Window](https://user-images.githubusercontent.com/45152336/211572200-1dc86426-e354-4b61-972e-963814dbe31f.png)

**Comment by JonathanTSilva** [comment]
Thanks.

I've tried all below available versions for this driver and the error keeps happening:
- 3.0.1/3.0.2/3.0.3/3.0.3.1/ 3.0.4/3.0.5/3.0.6/3.0.7
- 4.0.1/4.0.2/4.0.3/4.0.4/4.0.5
- 5.0.0/5.0.1

**Comment by amoradell** [comment]
Have you tried this opener ?
https://github.com/gordthompson/ucanaccess-generic-opener

**Comment by JonathanTSilva** [comment]
No, I haven't. Do you have any tips on how I can use it? I tried to add it as a library in my connection's Drivers, but I wasn't successful.

**Comment by amoradell** [comment]
As I read on github, jackcessOpener needs to follow Access database path, I don't know if it's possible to build such a connection in DBeaver

**Comment by amoradell** [comment]
Have you tried with URL option to build connection ?
"jdbc:ucanaccess://home/jonathan/db.mdb;jackcessOpener=com.gordthompson.ucanaccess.crypto.CryptCodecOpener"

**Comment by JonathanTSilva** [comment]
No, I haven't. I put this new library inside the driver's folder and when I try, the following message appears:

```
UCAExc:::5.0.1 com.gordthompson.ucanaccess.crypto.CryptCodecOpener
```

**Comment by Matvey16** [comment]
@JonathanTSilva Is it possible for you to provide a copy of the mdb file (modified to not include any sencible data)?

**Comment by JonathanTSilva** [comment]
@Matvey16 It is not possible for me to provide any of these .mdb files (even the modified ones) due to my company's IT policies of my company. I'm sorry. But I'll try to get an external sample that produces the same error in my DBeaver.

**Comment by hrodward** [comment]
I have the exact same issue

**Comment by E1izabeth** [comment]
It's been a long time since no update here. If this issue is still actual, please provide additional info, otherwise it will be closed.
