### ISSUE TITLE
Remove filters settings option in Filters menu triggers opens References menu

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#18720]
### Description

Remove filters settings option in Filters menu triggers opens References menu both in data and SQL editors

https://user-images.githubusercontent.com/31996417/211582353-14b8f3d9-bcaf-485e-a83e-afa88e0a9664.mp4

### DBeaver Version

22.3.2

### Operating System

win10

**Comment by serge-rider** [comment]
Fixed
