### ISSUE TITLE
Eclipse Marketplace and All Plugins removed on updates to User-installed DBeaver

### ISSUE THREAD

**Issue by Xemptuous** [dbeaver/dbeaver#18728]
### Description

I am currently on version 22.3.2, but this has happened with every update I have done.

I have DBeaver installed "for this user only", meaning it's installed in AppData.

Every time I upgrade DBeaver - even if I don't have "Reset Settings" checked in the installation, it always removes my installed plugins -> Eclipse Marketplace + Vwrapper, Line Numbers, Theme, etc.

This makes it very difficult to upgrade, as I want certain bugfixes incorporated, but don't like having to go through and reinstall all my plugins each time.

### DBeaver Version

CE 22.3.2

### Operating System

Windows 10

**Comment by E1izabeth** [comment]
Duplicate of #5317
