### ISSUE TITLE
https://dbeaverio.io/files/jdbc is no longer open

### ISSUE THREAD

**Issue by tom-flamelit** [dbeaver/dbeaver#18721]
### Description

The driver repository in version 21.2.4 dbeaver-ce has the driver repository as https://dbeaver.io/files/jdbc. This appears closed down except for one Google-captured reference to the firebird licence at https://dbeaver.io/files/jdbc/drivers/firebird/LICENSE.txt.

Where did the drivers go? 

This problem has persisted through several MacOS versions. It is operating behind a firewall and proxies are set up appropriately.

### DBeaver Version

Community Edition 21.2.4

### Operating System

macOS Venture 13.1

### Database and driver

All

### Steps to reproduce

1. I try to download/update driver in driver manager
2. I receive errors (most recently an SSL error that I'll be checking, but others get similar errors)

**Comment by flambchap** [comment]
Hi, @tom-flamelit. Most JDBC drivers are fetched from Maven Central. Can you please tell me with which drivers you experience the issue?

**Comment by tom-flamelit** [comment]
Thanks for responding. All of them have the same issue.

I have specifically tested Oracle and Postgres (and then replaced with local downloads from their websites), and this morning revisited by testing with Neo4j.

**Comment by tom-flamelit** [comment]
Also the default repository website path is not accessible via browser (https://dbeaver.io/files/jdbc). Is there another repository DBeaver recommends instead of this default (or, in other words, how do I reference Maven Central?)

**Comment by flambchap** [comment]
That's odd. We fetch all of these drivers from Maven Central. On top of that, I've just been told that we've never opened the https://dbeaverio.io/files/jdbc path in the first place. Can you please take a screenshot of the Library tab in the Driver Manager for any of these drivers?

**Comment by tom-flamelit** [comment]
Screenshot not available on corporate machine.

In Connection > Drivers, default repo set to https://dbeaver.io/files/jdbc

Example from Library
Driver: Neo4j
Library: org.neo4j:neo4j-jdbc-driver:RELEASE
Path: maven:/org.neo4j-jdbc-driver:RELEASE
Version: RELEASE

Error in connecting: 
`Network unavailable: javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

This shows dbeaver isn't capturing my certs (not the first time I've seen it) but others on my team have received other network errors unrelated to SSL.

**Comment by E1izabeth** [comment]
#12653

**Comment by ShadelessFox** [comment]
Hello @tom-flamelit,

Do you have the firewall enabled? Please make sure that you're able to access Maven repository from your corporate network.

**Comment by E1izabeth** [comment]
It's been a long time since no update on this issue. If it's still actual, please, let me know.

**Comment by tom-flamelit** [comment]
It's still an issue.

**Comment by E1izabeth** [comment]
Please, respond to the last question.
https://github.com/dbeaver/dbeaver/issues/18721#issuecomment-1397035765

**Comment by tom-flamelit** [comment]
I can otherwise access the Maven repository. However, dbeaver is not able
to access.

**Comment by flambchap** [comment]
@tom-flamelit Do I understand correctly that you can access Maven Central using other software like web browsers but not with DBeaver? One common cause is that you work behind a firewall or proxy. Can you please clarify your networking setup?

**Comment by E1izabeth** [comment]
@tom-flamelit please tell us, are you under the firewall or in a corporate network?

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.

**Comment by jcrben** [comment]
@E1izabeth @uslss I'm facing the same issue - would you prefer that I document it here or open a new issue?

I'm using WSL2 - the Ubuntu 22.04 WSL image - on a Windows 10 machine inside of GlobalProtect VPN. I'll update this with more details later. I installed via snap and then updated the `config.ini` to point to a custom certificate bundle as my trustStore which has worked in the past when using java.

**Comment by E1izabeth** [comment]
@jcrben this link is not supposed to be available outside DBeaver.

**Comment by E1izabeth** [comment]
@jcrben this link is not supposed to be available outside DBeaver. Do you see this error when trying to download driverfiles for a connection?

**Comment by jcrben** [comment]
I commented here because I searched on `Network unavailable: javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target` and I saw this as one of the issues. When I try to click to make a connection, it says I'm missing a driver, and tries to download it, failing with the message above.

I'm going to try to reproduce on my personal computer.

**Comment by E1izabeth** [comment]
It's not connected with this issue at all. Please, create a separate issue or discussion.

I'm not sure what you've changed, but it looks like something went wrong with your config.

**Comment by tom-flamelit** [comment]
> @tom-flamelit please tell us, are you under the firewall or in a corporate network?

Apologies for not responding sooner, and appreciate @jcrben's comments as they brought this to top of mind. Yes, we are on a corporate network.

**Comment by flambchap** [comment]
@tom-flamelit DBeaver does not download drivers from its website. For most of the drivers, we download it from Maven Central. Judging from the error, DBeaver cannot make a TLS handshake with Maven Central. Can you please try opening https://repo1.maven.org/maven2/ from the web browser and see if your browser can do that?

**Comment by tom-flamelit** [comment]
Thanks for reaching out @Nikita. That site opens without an issue in the
browser.

If the access path that needs to be open is documented or there is a way to
point to/setup a Nexus passthrough repository, that would probably solve
the issue. I know the Nexus item is out of scope for the dbeaver code
itself, but just understanding how dbeaver reaches out and what needs to be
in place may give us enough information to help the many analysts I work
with that are leery to download drivers by themselves :)

**Comment by Destrolaric** [comment]
`-Djavax.net.ssl.trustStoreType=KeychainStore` could you try to launch DBeaver with this argument?

**Comment by E1izabeth** [comment]
Any updates?

**Comment by E1izabeth** [comment]
@tom-flamelit any updates?

**Comment by tom-flamelit** [comment]
Testing the launch command, then attempting to download a driver (used HIVE
as the new connection starting point) results in a
java.security.NoSuchAlgorithmException (operating on MacOS). This occurs
both with and without the java launch flag.

**Comment by E1izabeth** [comment]
Thanks

**Comment by Destrolaric** [comment]
@ tom-flamelit Hi, could you exclude the license file from the download and retry the download?
You can do that in `Driver Connection Page -> Driver Settings -> Libraries`
![image](https://github.com/dbeaver/dbeaver/assets/20579256/3057df8d-02a8-440c-a2c5-37b8d41a62b4)
Additionally 
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and answer our question.
