### ISSUE TITLE
Move 'Filter by value' above in the dropdown menu

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#18726]
Users can't **Filter by value** option in the dropdown. We should move it to the top of the section, just after the sorting section. 

<img width="468" alt="Screenshot 2023-01-10 at 19 27 46" src="https://user-images.githubusercontent.com/12581569/211632783-5936ff5b-723e-4160-b0b7-69505624bba6.png">

**Comment by serge-rider** [comment]
Fixed
