### ISSUE TITLE
Column description is missing on Panels/Metadata 

### ISSUE THREAD

**Issue by bikeridercz** [dbeaver/dbeaver#18733]
### Description

Friends, thanks for great piece of software !!! To make it event better I decided to create this bug report because I'm convinced that this feature should work but it don't.

In our company most important tables and views are well documented, it means they have Table/View/Column descriptions set. This is very important for educated business users writing theirs own SQL scripts. The problem is that those descriptions does not appear on Metadata panel that is useful during sql design. I suspect that Description shall appear on LABEL column, because now LABEL contains the same value as COLUMN NAME, so I'm convince that this is a mistake.

Thanks you.

### DBeaver Version

Community edition 22.3.0

### Operating System

macOS Ventura

### Database and driver

Latest MS SQL server driver

### Steps to reproduce

see bug description

**Comment by E1izabeth** [comment]
Label on this panel is used to show column alias if it was set.

**Comment by E1izabeth** [comment]
The bug is that not only Label, but Name either is changed if alias was set.
![image](https://user-images.githubusercontent.com/28875055/211776272-89217ef2-e5e3-4453-a5fc-e5a959b39acd.png)

**Comment by E1izabeth** [comment]
Thank you for bug report, @bikeridercz

**Comment by serge-rider** [comment]
Fixed
