### ISSUE TITLE
Postgres numeric columns are displayed rounded to 3 decimals ignoring data format

### ISSUE THREAD

**Issue by apozog** [dbeaver/dbeaver#18734]
### Description

Suddenly, numeric type columns from Postgres are displayed rounded to 3 decimals. If you double click the cell, you can see the full value, but that was not this way recently. My data-formats configuration is default.

### DBeaver Version

22.2.4.202211061524

### Operating System

Windows 10 Pro x64

### Database and driver

Database: PostgreSQL 13.4 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-6), 64-bit
Driver: PostgreSQL JDBC Driver

**Comment by LonwoLonwo** [comment]
hello @apozo-copyright 

Can you provide table DDL and maybe more details about your problem?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
