### ISSUE TITLE
ERD Diagramm DBeaver

### ISSUE THREAD

**Issue by AndreaHaymoz** [dbeaver/dbeaver#18739]
I have 2 questions about the erd diagramm of dbeaver. Is it possible to show the foreign keys as a column in the entity? 

Example:
ID
-----------
Column1 
Column2
-----------
PERS_FK1 
STAT_FK2
  
In the ERD-Diagramm ist shows the Schema-Name.Tablename. Is it possible, to show only the tablename?

**Comment by ShadelessFox** [comment]
Hello @AndreaHaymoz,

Try disabling this option in the context menu:

![image](https://user-images.githubusercontent.com/35821147/211848562-58e98a4d-558c-491a-bc32-f0136ccfd639.png)

Let me know if it helps.

**Comment by AndreaHaymoz** [comment]
Hi, 
yes this works fine. Do you know, if it is possible to show the Foreign Keys as Column at the end of the Entitiy?

**Comment by ShadelessFox** [comment]
No, you can't rearrange columns. Keys are shown on top.

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
