### ISSUE TITLE
Handling of Spatial data types on MS-SQL is wrong

### ISSUE THREAD

**Issue by bikeridercz** [dbeaver/dbeaver#18736]
### Description

Dear Friends, thanks for great piece of software !!! To make it event better I decided to create this bug report because I'm convinced that this feature should work but it don't.

This bug relates to handling of **Spatial** data types retrieved from MS-SQL database. Because of that displaying of **Spatial** data on integrated OpenStreetMap inside of **Panels/Value** is wrong. There is a workaround but this is really annoying.

To reproduce this issue create sample table with the same Point but with 4 different ways ...
```
select 'POINT(14.3038983300 50.0677972200)' point_string, 
       geometry::STPointFromText('POINT(14.3038983300 50.0677972200)', 4326) point_from_text,
       geometry::Point('14.3038983300', '50.0677972200', 4326) point_geometry,
       geography::Point('14.3038983300', '50.0677972200', 4326) point_geography
into L2_USER.GEO_TEST
;
```

This should result as following table structure with **1 Varchar** column and **3 Geometry/Geography** columns
<img width="748" alt="image" src="https://user-images.githubusercontent.com/5019226/211795055-bdb50984-d5ce-443e-92fe-6244987523c4.png">

Then **View data** from this table and on the first **Varchat** column set **View/Format** -> **Set "point_string" transform** -> **Geometry**. Then you can see the point correctly displayed on the OpenStreetMap integrated into **Panels/Value**.

The rest of 3 point have **Geometry/Geography** data types already set so they are identified automatically as **Spatial** points however they are displayed on the map in a bad way (somewhere else)

I suspect that there is an issue during loading this **Spatial** datatypes from database - see the difference in coordinate values between the **Varchar**  and **Geometry/Geography** columns ...
<img width="434" alt="image" src="https://user-images.githubusercontent.com/5019226/211796666-9e41a103-55e9-4ef2-ac3c-e797ac91b0d1.png">

### DBeaver Version

Community edition 22.3.0

### Operating System

macOS Ventura

### Database and driver

Latest MS-SQL driver

**Comment by Matvey16** [comment]
@bikeridercz Thank you for the report!

**Comment by ShadelessFox** [comment]
Hello @bikeridercz,

What are your database and driver versions?

**Comment by bikeridercz** [comment]
see below
<img width="425" alt="image" src="https://user-images.githubusercontent.com/5019226/216997786-5106d9ea-8a42-4d5d-b4a0-72d79ae212b2.png">

**Comment by ShadelessFox** [comment]
Thanks for the response.

Note: not reproducible against SQL Server 2019:

![image](https://user-images.githubusercontent.com/35821147/216998592-f15b9e8d-baa7-4a31-bfe7-252a7d73a492.png)

**Comment by Destrolaric** [comment]
Confirmed for Community Edition.

**Comment by Destrolaric** [comment]
Unfortunately, this is related to the community edition's inability to handle gis values from the SQL server. This functionality exists in DBeaver PRO, which specifically allows handling Oracle and SQL Server GIS values.

**Comment by bikeridercz** [comment]
Wow! So why the Community edition integrates  an open streat map viewer ? I hope you are joking ;-) if it is right so remove all that map support from Community edition completely …

**Comment by ShadelessFox** [comment]
Because many databases use WKT/WKB for storing GIS data, such as PostgreSQL, MariaDB, etc.

SQL Server has its own binary format for storing GIS data, and so is Oracle.

It was available only in PRO versions from the beginning. No functionality was removed from the community edition.

**Comment by bikeridercz** [comment]
Ok, so can you throw some exceprion like “feature not available” to save time to users like me trying to reveal where te problem is? And to save time to developers of community version that was initialy convinced that this is a bug… For all those groups of people it was wasted time. This would be fair wouldn’t be (the exception) ?

**Comment by ShadelessFox** [comment]
We don't want to artificially force the users to purchase PRO versions of the product.

It may be worth adding a note in the transformer that it can operate over WKT/WKB only.

**Comment by bikeridercz** [comment]
My intention is not to encourage user to buy a licence ...

My intention is to save time to users and developers trying to figure out why the hell it is not working ... something like that ... 
![image](https://user-images.githubusercontent.com/5019226/224027999-573fe7d0-8b5d-423b-80a9-91e1c4476443.png)

**Comment by wthueb** [comment]
> We don't want to artificially force the users to purchase PRO versions of the product.
> 
> It may be worth adding a note in the transformer that it can operate over WKT/WKB only.

Assuming that the user has a PRO version (namely, enterprise), what's the fix for this?

**Comment by arhayka** [comment]
@wthueb Thanks for reaching out! If you're using our paid product and have an appropriate license, consider creating your ticket on our website: https://dbeaver.com/submit-ticket/. You might get a quicker response there.
