### ISSUE TITLE
Update Microsoft JDBC Driver version to 11.2.3

### ISSUE THREAD

**Issue by CRudde** [dbeaver/dbeaver#18747]
### Description

I am running DBeaver Version 22.3.2.202301060755 on MacOS 13.1 (M1 Pro)

I am running the same DBeaver Version on my Windows Machine. 

When I try to establish a connection to an AZURE SQL Server instance, the MacOS DBeaver fails to login, the Windows DBeaver does it perfectly. 

Error message on MacOS is: `Login failed for user '*********'. ClientConnectionId:79f5a76c-261d-46d7-88d9-f04b3539358b` (the ClientConnectionId naturaly changes every time)

### DBeaver Version

22.3.2.202301060755

### Operating System

MacOS 13.1 (M1 Pro)

### Database and driver

1. Azure MSSQL Server 
2. Microsoft JDBC Driver for SQL Server (MSSQL)
3. com.microsoft.sqlserver:mssql-jdbc:RELEASE 11.2.2.jre17

### Additional context

No tunnels, no custom driver settings, factory settings

**Comment by ShadelessFox** [comment]
Hello @CRudde,

What authentication method are you using?

**Comment by CRudde** [comment]
> What authentication method are you using?
SQL Server Authentication

The error seems to be in the driver version... i looked into the docs and changed the driver version to 11.2.3.jre17. Now everything works like a charm.

**Comment by ShadelessFox** [comment]
Thanks for the clarification.

We need to update the preferred driver version on our side.
