### ISSUE TITLE
Slowdown while queries on AS400

### ISSUE THREAD

**Issue by LucioMenci** [dbeaver/dbeaver#18744]
### Description

It is very slow during the query execution when connected to a remote AS400 server. See the attached image

![image](https://user-images.githubusercontent.com/15246491/211852318-33086dbb-f810-44f6-98cc-ed49328c591d.png)

### DBeaver Version

22.3.0

### Operating System

Win10, connected with a remote SystemI

### Database and driver

IBM DB2 iSeries/AS 400 driver (com.ibm.as400.access.AS400JDBCDriver) version 10.7 (jt400-10.7.jar)

### Additional context

It seems that the very slow query is:
 -- Load tables [null, PANTH02, %, null]

![image](https://user-images.githubusercontent.com/15246491/211854183-b893d44d-c823-4e6c-881e-9eadf68c615f.png)

**Comment by LonwoLonwo** [comment]
Hello @LucioMenci 

How many tables do you have in the PANTH02 schema?

**Comment by LucioMenci** [comment]
Hi Lonwo,

In Panth02 I have 4980 BaseTables and 8630 views. In all schemes I have 23900 Base tables and 29070 views.

**Comment by LonwoLonwo** [comment]
You can try to use table filters. In case you do not need all these tables and views.

![2023-01-12 17_00_54-DBeaver 22 3 2 - _master 3_ Script-84](https://user-images.githubusercontent.com/45152336/212086685-49a80939-5f62-46d3-8107-6158d905715b.png)

![2023-01-12 16_56_36-DBeaver 22 3 2 - _master 3_ Script-84](https://user-images.githubusercontent.com/45152336/212086738-428671b2-2c49-4900-a331-e6a9c8452e23.png)

I added a filter, and now table loading is faster for me.

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
