### ISSUE TITLE
I cannot see system database in clickhouse

### ISSUE THREAD

**Issue by wangxiaowei8** [dbeaver/dbeaver#18748]
### Description

The system database can be seen in the previous version. After the update, the system database disappears

### DBeaver Version

22.3.2

**Comment by LonwoLonwo** [comment]
Hello @179585800 

Can you please check if  "Show system objects" is enabled?

![2023-01-12 16_36_11-](https://user-images.githubusercontent.com/45152336/212081076-40aa773f-b9aa-4e95-992e-2941179ac17f.png)

**Comment by wangxiaowei8** [comment]
thank you，it's OK.
