### ISSUE TITLE
JSON(Read-only: No corresponding table columns)

### ISSUE THREAD

**Issue by zeornelas** [dbeaver/dbeaver#18756]
### Description

I'm not able to edit JSON cells. This only happens for existing content on the database.
If I try to add a new row I'm able to do it.

If I hover the mouse on the column it says "JSON(Read-only: No corresponding table columns)"
![image](https://user-images.githubusercontent.com/8457553/212123998-a087cd76-c04d-406c-947b-d30b53e14f32.png)

### DBeaver Version

Version 22.3.2.202301060755

### Operating System

macOs Ventura 13.1

### Database and driver

1. Database Name and Version: MySQL 5.7.38
2. Driver: MariaDB JDBC driver

### Steps to reproduce

1. Try editing an existing JSON cell.
2. The cell content doesn't change.

### Additional context

1. Using SSH tunnel.

**Comment by LonwoLonwo** [comment]
Hello @zeornelas 

What is the reason for using the MariaDB driver for the MySQL database?

>     Database Name and Version: MySQL 5.7.38
>     Driver: MariaDB JDBC driver

MariaDB does not have a JSON data type, only as an alias.

So you can use MySQL driver instead.

![2023-01-13 12_44_38-Создать соединение](https://user-images.githubusercontent.com/45152336/212289476-c68f2112-d2a2-41da-818d-5d7bd215786c.png)

Quick way:

![2023-01-13 12_45_55-](https://user-images.githubusercontent.com/45152336/212289506-0af91f13-0ed4-4ff6-ad94-a2b7dbbd3284.png)

**Comment by zeornelas** [comment]
@LonwoLonwo You are right. I'm not sure why this was with MariaDB driver, maybe the connection was duplicated from a MariaDB one.. I've changed the driver and it works as expected.

Thanks for the help! Closing this issue.
