### ISSUE TITLE
Killing a query in windows 1 affects query running in window 2

### ISSUE THREAD

**Issue by ivym1ke** [dbeaver/dbeaver#18758]
### Description

Hi, 

I had a long running update statement running in dbeaver using the sqlite driver.  I opened a second window to connect to the same sqlite db on disk and run a select statement.  The select statement was taking a long time so I cancelled it, but it also terminated the query running in the other window as well. 

I feel like this is probably not the expected behavior. I certainly didn't expect it. Close issue if I am mistaken. 

### DBeaver Version

22.2.5

### Operating System

Monterey

### Database and driver

SQLite using sqlisupport 1.0.143 ? I don't know the driver for sure. I am using the jdbc:sqlite// connection string. 

### Steps to reproduce

- Connect` to demo.db sqlite databae. 
- Create a long-running update statement
- Go to Window -> New window
- Connect to the same demo.db
- Perform a long running select statement
- Cancel the select query
- You will see the update statement in the original window also gets terminated

**Comment by ShadelessFox** [comment]
Hello @ivym1ke,

Could you try changing this option?

![image](https://user-images.githubusercontent.com/35821147/213467949-8e55ca9b-b59b-462e-b739-a1045f5a1c85.png)

**Comment by E1izabeth** [comment]
I'd also suggest to run queries in different sql editors (or you could open SQL Console for this purpose), because with the above option new connection will be created per editor.

**Comment by E1izabeth** [comment]
It's a long time since no update on this issue. If it's still actual, please, let me know.
