### ISSUE TITLE
Database name in url isn't taking into account 

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#18751]
### Description

Database name in URL in connection settings isn't taken into account. 

### DBeaver Version

22.3.2

### Operating System

win10

### Steps to reproduce

1. Start connection creation (e.g. postgres)
2. Switch from Host to url
3. write some URL (e.g. jdbc:postgresql://localhost:5433/db_a)
4. Connect to db - active db is postgres, not db_a

https://user-images.githubusercontent.com/31996417/212059999-c60c53a5-4316-4e52-a679-e18301a1cddd.mp4

**Comment by E1izabeth** [comment]
May be connected with #16107

**Comment by serge-rider** [comment]
Fixed
