### ISSUE TITLE
Parameter dates not working anymore

### ISSUE THREAD

**Issue by palilulac** [dbeaver/dbeaver#18755]
### Description

 @set previous_run='2022-12-12'::date
 @set order_dt_from='2022-12-13'::date
 @set order_dt_to='2023-01-11'::date		

SELECT Produkt.ord_dt::date between ${order_dt_from} and ${order_dt_to}                   

This worked in the previous version, now when I run the same script that I've used it pops up the Parameter window and it is asking me to type in manually. Would not be a problem if it is just once, but it fires a parameter window for each line where it finds ${date} and I do have a lot of them

### DBeaver Version

Community Edition Version 22.3.2.202301060755

### Operating System

Win 10

### Database and driver

PostgreSQL JDBC Driver

**Comment by E1izabeth** [comment]
Thank you for bug report

**Comment by E1izabeth** [comment]
It's similar to #18706 and will be fixed in scope of that issue.
