### ISSUE TITLE
Default bind parameter values

### ISSUE THREAD

**Issue by Mkkl91** [dbeaver/dbeaver#1876]
Is it possible to create your own default bind parameters in terms of values and placeholders?

As an example, let's say I wish the '%' to always be replaced by 'database1.table2' when I run my query, although in the SQL code the '%' sign remains.

I know about ':param' to bind parameters, but these need to be filled in for each query and these require always the ":" character as a prefix.

**Comment by serge-rider** [comment]
You can redefine `:` prefix in preferences (it can be done globally of connection-specific). On SQL Editor->SQL Processing pref page.
And you can use anything (even SQL subqueries ) as parameter values.
Also you can automate this by editing `parameter-bindings.xml` file (it contains all existing bindings).

**Comment by Mkkl91** [comment]
Thanks serge, that really helped, although I'm still not completely where I want to be. I changed the anonymous parameter sign to "%", however, this appears not to work when combined with a string?

As an example, I want to add automatically prefixes to a table:

`SELECT f.* FROM <DATABASE>.%_<TABLENAME>`

**Comment by serge-rider** [comment]
Yes, this doesn't work because DBeaver thinks that underscore is a part of parameter name.
I'm not sure how to resolve this better. Maybe add some new form of parameters  (e.g.l enclose parameter name in some chars - like `@param@`).
