### ISSUE TITLE
Windows sizes/positions of "Connection configuration", "driver properties" not saved

### ISSUE THREAD

**Issue by de-served** [dbeaver/dbeaver#18770]
### Description

"Connection configuration", "driver properties" windows parameters not saved.
Each time it opens with default sizes at default positions and needs to be resized a lot to fit everything needed.

I tried ton of parameters combinations with mariadb-connector .jar to make it work with named pipes and each time I must resize windows to get to needed inputs/parameters. Maybe 150-200 times. And it is annoying a lot.

### DBeaver Version

22.3.2

### Operating System

Win 10

### Database and driver

1. Open "Create connection".
2. Resize/move opened window.
3. Press [driver properties] button.
4. Resize/move opened window.
5. Save connection.
6. Open connection... window size/pos is lost.
7. Press [driver properties] button - window size/pos is lost (and it's size is tiny so nothing fits there and window must be resized).

**Comment by ShadelessFox** [comment]
Thank you for your report.

**Comment by arhayka** [comment]
We want to save the size of the connection dialog. 
When opening a new connection dialog, we need to first apply the saved dimensions and then increase the size of the dialog if needed.
