### ISSUE TITLE
DBeaver Lite: Auto-complete does not working connecting to Netezza with schema-disabled

### ISSUE THREAD

**Issue by mmarsilli** [dbeaver/dbeaver#18777]
### Description

We have similar problem as Kseniiaguzeeva #10955 with **DBeaver Lite (Version 22.3.0)** connecting to a **Netezza DB with schema disabled**.

Writing:
`select * from art`
there is no auto-complete.

Instead by writing:
`select * from admin.art`
auto-complete works well.

Curiously, DBeaver Community works correctly.

Note: Setting "Use Short Object Names (omit schema/catalog)" does not change the behavior of Auto-complete.

Having to write the schema name all the time to get autocomplete is very frustrating.

### DBeaver Version

DBeaver Lite 22.3.0

### Operating System

Windows 11

### Database and driver

Database: Netezza NPS JDBC Driver Release 11.2.1.4
Driver: the one just included in DBeaver Lite (it seems to be 7.2.1)

![image](https://user-images.githubusercontent.com/54542143/212644873-d1d17401-1092-4700-97db-631cefc1d5f6.png)

### Steps to reproduce

1. Connect to Netezza.

2. Write 
`select * from tablenamepart`
Use Ctrl-space to activate Auto-complete: it does not work.
![image](https://user-images.githubusercontent.com/54542143/212645917-9c6be224-8b53-457a-958d-f08c911f82a4.png)

3. Write
`select * from admin.tablenamepart`
Use Ctrl-space to activate Auto-complete: it works.
![image](https://user-images.githubusercontent.com/54542143/212645972-5dd0c9be-d7e0-4b9f-93af-8e81eba3632b.png)

**Comment by LonwoLonwo** [comment]
Hello @mmarsilli 

Could you please provide me a screen of this connection view setting?

![2023-01-18 20_19_35-DBeaver Lite 21 3 0 - _TEST_ Console](https://user-images.githubusercontent.com/45152336/213250659-717a15ed-f905-4001-9312-40f41c3c5ea5.png)

**Comment by LonwoLonwo** [comment]
And did you disable schemas this way? https://www.ibm.com/docs/en/psfa/7.2.1?topic=overview-disable-multiple-schema-support

**Comment by mmarsilli** [comment]
> And did you disable schemas this way? https://www.ibm.com/docs/en/psfa/7.2.1?topic=overview-disable-multiple-schema-support

Yes, we disabled schemas by setting the enable_schema_dbo_check variable to 0 in postgres.conf.

In any case we don't want to nor can we change it because on those databases they are used every day by about 3000 etl and more than 3000 reports and it would be impossible to review all of them so that they use schema correctly.

**Comment by mmarsilli** [comment]
> Hello @mmarsilli
> 
> Could you please provide me a screen of this connection view setting?
> 
> ![2023-01-18 20_19_35-DBeaver Lite 21 3 0 - TEST Console](https://user-images.githubusercontent.com/45152336/213250659-717a15ed-f905-4001-9312-40f41c3c5ea5.png)

Here it is:
![image](https://user-images.githubusercontent.com/54542143/213255677-f33e7773-4ebb-40e7-b338-ededd4b52e95.png)

**Comment by LonwoLonwo** [comment]
Thanks.
Could you please check this setting? Is it enabled?

![2023-01-19 12_55_53-DBeaver Ultimate 22 3 2 - _TEST_ Script-45](https://user-images.githubusercontent.com/45152336/213411975-d17abb3d-63d0-45c3-bc47-e5cfd2845319.png)

**Comment by mmarsilli** [comment]
My configuration looks like this:

![image](https://user-images.githubusercontent.com/54542143/213424718-4f3abb87-1ddd-472a-a97a-353421ef8941.png)

**Comment by LonwoLonwo** [comment]
I have a guess. 

![2023-01-19 14_50_33-](https://user-images.githubusercontent.com/45152336/213435406-d235e8d1-ef84-4b0c-9b39-1dc08f5d39b5.png)

![2023-01-19 14_50_53-](https://user-images.githubusercontent.com/45152336/213435412-1e82be06-86db-4de5-9e77-72aa65ed7655.png)

I can see on your screens that all "articolo" objects are not tables, right? On the screens above, you can see that only tables return without schema names. Can you please check auto-completion without a schema name for any table name?

**Comment by mmarsilli** [comment]
"articolo_d" is a table and is available in all the databases from which I have captured images . In all the tests I was trying to find "articolo_d".
In our main database there are about 4000 tables and views some of which contain the word "articolo". For example "articolo_v", "articolo_unificato_new_v" are views, while "promo_articolo_negozio_d" is a table.
Anyway: if I don't use "admin.artic" I can't find the table "articolo_d".

Img1:
![image](https://user-images.githubusercontent.com/54542143/213500717-dce7dc0e-16b5-4a1b-baa7-e70ad9a6184f.png)

Img2:
![image](https://user-images.githubusercontent.com/54542143/213497652-5c390156-758b-47ad-bb6f-06cf2585954e.png)

I noticed this now:
![image](https://user-images.githubusercontent.com/45152336/213435412-1e82be06-86db-4de5-9e77-72aa65ed7655.png)
... but I have never been able to produce this behavior.

Bye the way: In Netezza, names are not case sensitive. For example, ADMIN and admin are the same, but object names are converted to lowercase when they are stored in the Netezza database. However, if you enclose a name in quotation marks, it is case sensitive.

**Comment by LonwoLonwo** [comment]
> but object names are converted to lowercase when they are stored in the Netezza database

Mmm... I'm not sure about this. It may depend on database configuration settings. By default, objects without quotation marks convert to UPPER case.

https://www.ibm.com/support/pages/changing%C2%A0default-case-all-database-objects

**Comment by LonwoLonwo** [comment]
Ok. Let's continue our investigation.

Please check your Query Manager with all enabled filters. Instruction is here: https://github.com/dbeaver/dbeaver/wiki/Query-Manager

![2023-01-19 20_04_53-DBeaver Lite 22 3 0 - _TEST_ Console](https://user-images.githubusercontent.com/45152336/213512250-07d3e35b-3cad-475e-b562-0789f7526644.png)

Usually, we have a special query to find objects with the part of the name:

```sql
SELECT SCHEMA, OBJNAME, OBJTYPE, DESCRIPTION
FROM TEST.DEFINITION_SCHEMA._V_OBJECTS WHERE UPPER(OBJNAME) LIKE '%ARTIC%' AND OBJTYPE IN ('TABLE')
ORDER BY SCHEMA, OBJNAME LIMIT 100
```

If you see this query - can you execute it and show me the result?

Also, please check your logs. You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by mmarsilli** [comment]
> > but object names are converted to lowercase when they are stored in the Netezza database
> 
> Mmm... I'm not sure about this. It may depend on database configuration settings. By default, objects without quotation marks convert to UPPER case.
> 
> https://www.ibm.com/support/pages/changing%C2%A0default-case-all-database-objects

Yes, unfortunately, IBM since buying netezza has been trying to get it to converge to DB2, but customers have resisted and continued to upgrade servers by choosing the "lowercase" option during instralation. :-)

**Comment by mmarsilli** [comment]
This doesen't work:
![image](https://user-images.githubusercontent.com/54542143/213675110-43667fa4-46a0-4e29-9d66-8e6ffd1d7038.png)

This works:
![image](https://user-images.githubusercontent.com/54542143/213675258-5e8cc3b5-e287-4b83-a035-ff56f75f3d82.png)

**Comment by mmarsilli** [comment]
By the way, this does not work in DBeaver:
![image](https://user-images.githubusercontent.com/54542143/213681505-25ece85b-b368-453d-ad9a-ce7698c7fa1a.png)

While works correctly in SQuirreL:
![image](https://user-images.githubusercontent.com/54542143/213681635-81c74a88-3582-4127-8a33-0527ee5fb040.png)

**Comment by LonwoLonwo** [comment]
> This works:

Oh, wow, you found the bug! thanks. Looks like this case database setting has impact on system data too.
