### ISSUE TITLE
table column name autocomplete does not work as expected whith global search

### ISSUE THREAD

**Issue by buddhiprab** [dbeaver/dbeaver#18778]
### Description

autocomplete table column names does not work at all after updating version to 22.3.2 latest version

### DBeaver Version

22.3.2

### Operating System

Windows 11 Home

### Database and driver

PostgreSQL [12.11
PostgreSQL 12.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit]

PostgreSQL JDBC Driver [42.5.0]

### Steps to reproduce

start typing a select query on the script and it normally shows the suggestions for table column names, but after updating to version 22.3.2 it does not show the suggestions
![image](https://user-images.githubusercontent.com/8514246/212652334-094c5e99-b8a6-40ad-bf69-134d2e888f05.png)

**Comment by LonwoLonwo** [comment]
Hello @buddhiprab 

Can't reproduce it for now.

![2023-01-16 13_35_01-](https://user-images.githubusercontent.com/45152336/212658303-1f6738ec-ce05-48cc-841b-3d0680a88926.png)

Is the "broadcast" table from the default SQL Editor schema/catalog?

![2023-01-16 13_38_00-Window](https://user-images.githubusercontent.com/45152336/212658692-f30e509b-cbc2-4315-9dfc-e04ec9499e35.png)

**Comment by LonwoLonwo** [comment]
Ok, I see. It doesn't work if SQL Editor has another schema/catalog in the context.

![2023-01-16 13_44_50-](https://user-images.githubusercontent.com/45152336/212659954-d5653764-8872-465c-a420-61e7223cbd29.png)

MySQL and PostgreSQL checked

**Comment by LonwoLonwo** [comment]
#10955

**Comment by LonwoLonwo** [comment]
Global search enabled.
![2023-01-16 13_48_11-Window](https://user-images.githubusercontent.com/45152336/212660605-0b4a5cfc-8474-49c6-877e-7a55b7b46d55.png)
