### ISSUE TITLE
Spatial Viewer from string not working

### ISSUE THREAD

**Issue by samueltqx** [dbeaver/dbeaver#18784]
### Description

Previously you are able to view geodata from string on the map by "Set columnName format" as Geometry in "View/Format". It seems that the feature is no longer available, or at least not using the instructions from:
https://dbeaver.com/docs/wiki/Working-with-Spatial-GIS-data/#viewing-string-or-binary-data-from-any-database-on-a-map

### DBeaver Version

Community Edition 22.3.2.202301060755

### Operating System

MacOS Monterey

### Database and driver

Trino version 403

**Comment by ShadelessFox** [comment]
Hello @samueltqx,

Can you please provide more information regarding your issue?

**Comment by samueltqx** [comment]
@ShadelessFox 
Previously, there was an option to set string as geometry to view it on the map like:
![Screenshot 2023-01-16 at 19 27 59](https://user-images.githubusercontent.com/12363062/212753322-f5afdbf3-c7ba-4ffc-a063-08e98cbf5b62.png)


In the latest version, this option is no longer available
<img width="1209" alt="Screenshot 2023-01-16 at 19 26 31" src="https://user-images.githubusercontent.com/12363062/212753280-39eb6b70-2322-4069-8cd2-865c749135b6.png">

This is the instruction on the documentation which do not seem to work anymore. 
https://dbeaver.com/docs/wiki/Working-with-Spatial-GIS-data/#viewing-string-or-binary-data-from-any-database-on-a-map

**Comment by ShadelessFox** [comment]
It's available for me:

![image](https://user-images.githubusercontent.com/35821147/212753778-3e64b669-db15-4dbe-9118-ee5711e2949c.png)

I believe you're experiencing this issue because DBeaver can't determine the type of your column (on your first screenshot, it's text, on the second, it's unknown).

What data type does this column have?

**Comment by samueltqx** [comment]
That column is varchar. I have tested on an older PrestoSQL driver and it displays the right column type (ABC instead of ?) which allows me to set the column type as geometry. So the issue appears to be driver specific. 
Thank you for the help, I'll close this now
