### ISSUE TITLE
Error Running DDL Scripts

### ISSUE THREAD

**Issue by ftironectidata** [dbeaver/dbeaver#18787]
### Description

SQL Error [8] [0A000]: Actual statement count 2 did not match the desired statement count 1.
  Actual statement count 2 did not match the desired statement count 1.

### DBeaver Version

Version 22.3.2.202301060755

### Operating System

Windows 11

### Database and driver

Snowflake

### Steps to reproduce

Run 

DROP TABLE
IF
	EXISTS dim_appt;

DROP TABLE
IF
	EXISTS dim_test;

### Additional context

This worked in the previous version.

**Comment by E1izabeth** [comment]
Thank you for bug report. As a workaround you can highlight the whole statement you need and press Run.

**Comment by ftironectidata** [comment]
Hi Elizabeth,

Your suggestion does not work.

**Comment by E1izabeth** [comment]
Hmm.. it works for me
![image](https://user-images.githubusercontent.com/28875055/212774523-74821d89-79cc-4ee7-b05e-a3f2d238b02d.png)

**Comment by ftironectidata** [comment]
You can try running as a script, not as individual lines.

It is not practical to run one command at a time since I have many commands to run.

Thanks,

Frank

**Comment by ftironectidata** [comment]
How do I get this fix?

Thanks,

Frank

**Comment by E1izabeth** [comment]
@ftironectidata 
It will be available in DBeaver 22.3.3. Additionally the early access version will be available in a couple of hours.

**Comment by ftironectidata** [comment]
OK, and Thanks for the quick turnaround!

Frank

**Comment by E1izabeth** [comment]
Early access version is available here: https://dbeaver.io/files/ea/
