### ISSUE TITLE
Snowflake - getPrimaryKeys()

### ISSUE THREAD

**Issue by rlroyarsa** [dbeaver/dbeaver#18798]
### Description

It appears that DBeaver calls the getPrimaryKeys() method without schema/table names which in some cases can cause performance problems with Snowflake (underlying Snowflake JDBC driver yields a 'show primary keys in database ...' command rather than a 'show primary keys in table xxxx.xxxx.xxxx'.

### DBeaver Version

Community Edition 22.3.2.202301060755

### Operating System

Win 10 (21H2)

### Database and driver

Snowflake JDBC - 3.13.25

**Comment by rlroyarsa** [comment]
Similar issue with foreign keys - further, when using the Generate DDL or trying to show DDL function, the keys calls (primary and foreign) and not being qualified either.

**Comment by rlroyarsa** [comment]
To reproduce:
Click on Keys or Foreign Keys in the tree dropdown under a specific table - review the activity in Snowflake and see that command being called is 'show ... in database ... ' rather than 'show ... in table ...'

**Comment by LonwoLonwo** [comment]
Hello @rlroyarsa 

Unfortunately, I can't reproduce your issue.

![2023-01-17 19_59_31-DBeaver 22 3 2 - _postgres_ Script-34](https://user-images.githubusercontent.com/45152336/212963586-41746aa3-204e-4b58-98f6-045051838cbd.png)

Can you provide some screens or videos?

**Comment by rlroyarsa** [comment]
Looks like it's specific to schema names that contain underscores - if the schema name contains an underscore, it needs to be 'escaped' (each underscore) with a '\\'.

**Comment by rlroyarsa** [comment]
snowflake_jdbc0.log.0:71632:  <method>getPrimaryKeys</method>
snowflake_jdbc0.log.0:71634:  <message>public ResultSet getPrimaryKeys(String catalog=SFPROD, String schema=U_SCHEMA, String table=ATTREP_APPLY_EXCEPTIONS)</message>
snowflake_jdbc0.log.0:71704:  <method>getPrimaryKeys</method>
snowflake_jdbc0.log.0:71706:  <message>sql command to get primary key metadata: show /* JDBC:DatabaseMetaData.getPrimaryKeys() */ primary keys in database "SFPROD"</message>
snowflake_jdbc0.log.0:71718:  <message>execute: show /* JDBC:DatabaseMetaData.getPrimaryKeys() */ primary keys in database "SFPROD"</message>
snowflake_jdbc0.log.0:71730:  <message>executeQuery: show /* JDBC:DatabaseMetaData.getPrimaryKeys() */ primary keys in database "SFPROD"</message>
snowflake_jdbc0.log.0:71766:  <message>JSON: {"sqlText":"show /* JDBC:DatabaseMetaData.getPrimaryKeys() */ primary keys in database \"SFPROD\"","sequenceId":6,"bindings":null,"bindStage":null,"describeOnly":false,"parameters":{"CLIENT_RESULT_CHUNK_SIZE":48},"describedJobId":null,"querySubmissionTime":1673975988270,"isInternal":false,"asyncExec":false}</message>

**Comment by LonwoLonwo** [comment]
Ok, I see it. We do it for columns but not for keys.

![2023-01-18 00_50_15-DBeaver Ultimate 22 3 2 - _TEST_DB 2_ Script-100](https://user-images.githubusercontent.com/45152336/213020288-e4fba1a5-85cd-4645-a773-0251b173bb98.png)

**Comment by LonwoLonwo** [comment]
#9875

**Comment by LonwoLonwo** [comment]
Thanks for the bug report.
