### ISSUE TITLE
No label in Preferences

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#18795]
### Description

There is no label in Preferences, in this section: User interface —> Appearance —> Colors and Fonts —> ER Diagrams

<img width="858" alt="Screenshot 2023-01-17 at 12 23 36" src="https://user-images.githubusercontent.com/12581569/212904933-d2631060-196b-48e4-a096-b41d67e7bd78.png">

### DBeaver Version

CE 22.3.2

### Operating System

Mac OS Monterey

**Comment by E1izabeth** [comment]
Thank you for bug report.
