### ISSUE TITLE
Dbeaver cannot show tables on proxy

### ISSUE THREAD

**Issue by omerkocadere** [dbeaver/dbeaver#18792]
### Description

I have a PostgresSQL database on [fly.io](https://fly.io) servers. I set a proxy on my local machine to connect this database and query tables on my computer. 

![image](https://user-images.githubusercontent.com/9765632/212871385-c4883c32-4c7a-4fcf-af45-779e0b4391d0.png)

I can successfully log in using my credentials and see databases on Dbeaver.

![dbeaver_lcLibDbHKr](https://user-images.githubusercontent.com/9765632/212871740-ef0fbeea-9f5a-4968-ad13-4b5ebcbd0469.png)

But unfortunately cannot see my tables.

![dbeaver_CvQMYt4bC8](https://user-images.githubusercontent.com/9765632/212871960-351c2ada-6970-4566-8095-400114dbe7d8.png)

When I use [PostgreSQL VsCode extension](https://marketplace.visualstudio.com/items?itemName=ckolkman.vscode-postgres) to query my database using VsCode as a client, I can see my tables also can query.

![image](https://user-images.githubusercontent.com/9765632/212872681-8eac234f-9762-44e2-adcb-6f15d81f2d89.png)

When try using PgAdmin4, I can also see tables

![image](https://user-images.githubusercontent.com/9765632/212873033-af12b061-e4ae-48d1-a979-a9cce87f977d.png)

So, what is wrong with Dbeaver I investigated but I could not achieve to see the tables. It seems there is a problem here. Could you please fix this or If I am wrong can you help me with how can I see my tables?

![image](https://user-images.githubusercontent.com/9765632/212874096-c1abd3bd-9505-4145-a371-f855eb8a20cf.png)

### DBeaver Version

Community Edition 22.3.2

### Operating System

Windows 11 Pro

### Database and driver

PostgreSQL 15
jdbc 42.5.0

### Additional context

![WindowsTerminal_pKimwuR8vg](https://user-images.githubusercontent.com/9765632/212874939-1d9a3a65-b360-4778-ab9d-1cfb51ff04ce.png)

**Comment by E1izabeth** [comment]
@zormaxo thank you for bug report. Could you try disconnecting, connecting again, load tables and then send us the log files? You can find instructions of how to find them here https://dbeaver.com/docs/wiki/Log-files/

**Comment by omerkocadere** [comment]
See times after,
2023-01-17 16:20:12.198 - Execution context closed (postgres 2, 66)

 I tried a couple of times.

[metadata.zip](https://github.com/dbeaver/dbeaver/files/10435520/metadata.zip)


![dbeaver_d6lmGhaRUc](https://user-images.githubusercontent.com/9765632/212912938-3f0f9152-cf41-49b8-93a2-2ea5e9c2630c.gif)

**Comment by E1izabeth** [comment]
Thank you

**Comment by LonwoLonwo** [comment]
Hello @zormaxo 

Could you please check your [query manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) during the table loading and find a query like this:

```sql
SELECT c.oid,c.*,d.description,pg_catalog.pg_get_expr(c.relpartbound, c.oid) as partition_expr,  
pg_catalog.pg_get_partkeydef(c.oid) as partition_key
FROM pg_catalog.pg_class c
LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=c.oid AND d.objsubid=0 AND d.classoid='pg_class'::regclass
WHERE c.relnamespace=2200 AND c.relkind not in ('i','I','c')
```

and execute it? Does this query have any results?

**Comment by omerkocadere** [comment]
Hi, unfortunately, there is no result.

![image](https://user-images.githubusercontent.com/9765632/215539605-dbc44e5d-e465-4ea2-858b-2c7848f898ab.png)

![image](https://user-images.githubusercontent.com/9765632/215539685-3ee6b47a-56e6-4167-8dd6-4ef458884eab.png)

**Comment by LonwoLonwo** [comment]
Ok. 
New idea.
Could you please connect to your database from another driver connection? You must choose PostgreSQL(old) in the New Connection dialog.

![2023-01-31 11_48_06-Connect to a database](https://user-images.githubusercontent.com/45152336/215712525-b81971ed-a649-43f5-b7da-0ba0b0c83763.png)

Can you see tables in this connection?

**Comment by omerkocadere** [comment]
Tried but no, I don't see...

**Comment by LonwoLonwo** [comment]
Ok. We need time to reproduce your issue, then.

**Comment by omerkocadere** [comment]
If you need you can connect to my computer via teamviewer and investigate further...

**Comment by LonwoLonwo** [comment]
Ok,  this is the getTables query from the driver. Can you please try to execute it? Do you see any results?

```sql
SELECT
	NULL AS TABLE_CAT,
	n.nspname AS TABLE_SCHEM,
	c.relname AS TABLE_NAME,
	CASE
		n.nspname ~ '^pg_' OR n.nspname = 'information_schema'
		WHEN TRUE THEN CASE
			WHEN n.nspname = 'pg_catalog'
			OR n.nspname = 'information_schema' THEN CASE
				c.relkind WHEN 'r' THEN 'SYSTEM TABLE'
				WHEN 'v' THEN 'SYSTEM VIEW'
				WHEN 'i' THEN 'SYSTEM INDEX'
				ELSE NULL
			END
			WHEN n.nspname = 'pg_toast' THEN CASE
				c.relkind WHEN 'r' THEN 'SYSTEM TOAST TABLE'
				WHEN 'i' THEN 'SYSTEM TOAST INDEX'
				ELSE NULL
			END
			ELSE CASE
				c.relkind WHEN 'r' THEN 'TEMPORARY TABLE'
				WHEN 'p' THEN 'TEMPORARY TABLE'
				WHEN 'i' THEN 'TEMPORARY INDEX'
				WHEN 'S' THEN 'TEMPORARY SEQUENCE'
				WHEN 'v' THEN 'TEMPORARY VIEW'
				ELSE NULL
			END
		END
		WHEN FALSE THEN CASE
			c.relkind WHEN 'r' THEN 'TABLE'
			WHEN 'p' THEN 'PARTITIONED TABLE'
			WHEN 'i' THEN 'INDEX'
			WHEN 'P' THEN 'PARTITIONED INDEX'
			WHEN 'S' THEN 'SEQUENCE'
			WHEN 'v' THEN 'VIEW'
			WHEN 'c' THEN 'TYPE'
			WHEN 'f' THEN 'FOREIGN TABLE'
			WHEN 'm' THEN 'MATERIALIZED VIEW'
			ELSE NULL
		END
		ELSE NULL
	END AS TABLE_TYPE,
	d.description AS REMARKS,
	'' AS TYPE_CAT,
	'' AS TYPE_SCHEM,
	'' AS TYPE_NAME,
	'' AS SELF_REFERENCING_COL_NAME,
	'' AS REF_GENERATION
FROM
	pg_catalog.pg_namespace n,
	pg_catalog.pg_class c
LEFT JOIN pg_catalog.pg_description d ON
	(c.oid = d.objoid
		AND d.objsubid = 0
		AND d.classoid = 'pg_class'::regclass)
WHERE
	c.relnamespace = n.oid
```

**Comment by omerkocadere** [comment]
Yes, there is a result. But when I execute the same count query, dbeaver returns fewer rows than pgadmin. Please see the below images. And I can see my tables in pgadmin4. These tables are inside this difference.

![image](https://user-images.githubusercontent.com/9765632/219663505-600a8889-6832-408e-83fd-79b78aa89975.png)

![image](https://user-images.githubusercontent.com/9765632/219663595-d5cd09ab-5200-46a4-b2ea-308ff8106fa8.png)

![image](https://user-images.githubusercontent.com/9765632/219664275-15af65fd-6c49-45bd-b2fe-6fa293d1c3d4.png)

**Comment by LonwoLonwo** [comment]
Can you please check "tables_schem" column? Does it contain the name of your schemas? `public`, as example.

**Comment by omerkocadere** [comment]
Unfortunately, it does not contain public. And my schema name is public.

**Comment by LonwoLonwo** [comment]
In this step, I can only suggest you change the given queries and find your tables in the system tables. I do not know the reason why they are hidden, unfortunately.

**Comment by lasoama** [comment]
I had the same issue.
Try to edit your db connection to show all databases and then reconnect. 
Right click > Edit Connection > PostgreSQL tab > Check the option "Show all databases" (or something like that)

**Comment by E1izabeth** [comment]
@zormaxo does checking the suggested option helps?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
