### ISSUE TITLE
Execution times per command in function

### ISSUE THREAD

**Issue by cpantziaras** [dbeaver/dbeaver#18790]
Hello. I would like to know if it is possible to get the execution time for each command included in a function. For example, inside a function, I have 10 commands to drop tables and 10 commands to create temp tables. I would like to know how much time each command took to run.

**Comment by Matvey16** [comment]
Have you thought about including this execution time as a server output inside a function which can be seen in server output view?
![image](https://user-images.githubusercontent.com/82543000/220909609-f3a344fd-1493-4412-9ef2-40fb3eb61ce3.png)

**Comment by cpantziaras** [comment]
Yes. I tried this but I have to many functions and it is difficult to add the execution time as server output before each command.

**Comment by E1izabeth** [comment]
What database do you use?

**Comment by cpantziaras** [comment]
It was PostgreSQL.

**Comment by Matvey16** [comment]
Seems like a very specific feature ad not a quick one to implement. As it is actually possible to implement inside a function itself, we think it does not have a high priority. We will maybe return to it, if it has high demand.
