### ISSUE TITLE
Query manager not showing queries run outside of DBeaver

### ISSUE THREAD

**Issue by jayrodrigues** [dbeaver/dbeaver#18800]
### Description

It looks like query manager only shows queries run by DBeaver. I need to see the history of queries happening in real-time - is this possible using DBeaver or any suggestions on how I can get a log of queries being run and the time to execute?

### DBeaver Version

2.3.2.202301060755

### Operating System

macOS Ventura 13.1 Silicon

### Database and driver

MariaDB 10.1

### Steps to reproduce

1. I connect to the database
2. Click on Window > Show View > Query Manager

**Comment by LonwoLonwo** [comment]
Hello @jayrodrigues 

Yes, the Query manager can only show you queries made by DBeaver or in DBeaver. He doesn't know anything about queries outside. 

Can you provide some examples? What queries would you like to see? In which situations?

**Comment by jayrodrigues** [comment]
Hello @LonwoLonwo Thanks for the response. I am trying to profile the queries that are happening on the application side to see how to track queries and see how slow they are. 

I was hoping with DBeaver that I could see all the incoming queries a database incurs.

**Comment by ShadelessFox** [comment]
Hello @jayrodrigues,

Have you tried using the session manager? You can access it under the connection &rArr; <kbd>Administer</kbd> &rArr; <kbd>Session Manager</kbd>.

**Comment by jayrodrigues** [comment]
Hello @ShadelessFox yes, that's very close to what I was looking for, thank you! 

Is there a way to maintain a log or list all the queries that show under the Session Manager?

Trying to track down queries happening that take the most time to execute.

**Comment by ShadelessFox** [comment]
No, unfortunately, you can't maintain a log of executed queries.

I assume your issue is solved, so I'm closing the ticket.
