### ISSUE TITLE
JSON data appears as gibberish

### ISSUE THREAD

**Issue by mholt** [dbeaver/dbeaver#18808]
### Description

JSON in "TEXT" fields (of a sqlite DB) are gibberish:

![image](https://user-images.githubusercontent.com/1128849/213261154-1abf6d48-9b7d-45de-9f36-9250494b375e.png)

Using "Auto format" doesn't work either.

### DBeaver Version

22.3.2

### Operating System

Ubuntu 22

### Database and driver

Sqlite JDBC

**Comment by ShadelessFox** [comment]
Hello @mholt,

SQLite doesn't have native support for JSON. Moreover, DBeaver has no dedicated support for BLOB JSONs in SQLite.

Please provide more information about your database file. Where did this data come from?

**Comment by mholt** [comment]
Hi, thanks for the reply!

I'm basically storing JSON bytes (ASCII) in a TEXT field in SQLite. I am wondering why it shows up like gibberish... I would expect it to show the ASCII text instead.

(I am not using JSON or BLOB data types.)

This column is defined with this in the CREATE TABLE definition:

```
"metadata" TEXT,
```

**Comment by ShadelessFox** [comment]
Can you provide the database file?

**Comment by mholt** [comment]
(Sorry, I thought I replied to this -- but I guess I didn't hit submit)

Unfortunately no, it's full of sensitive data from account exports from services like Google, Facebook, etc...

It sounds based on the response so far, like this is expected for JSON data for some reason -- is that true for TEXT fields though? How can TEXT fields be rendered as a BLOB? Maybe it's just a misunderstanding on my part.

**Comment by ShadelessFox** [comment]
I see.

As said before, SQLite doesn't have native support for JSON fields, but there's more: it has no constraints between metadata and data (you can store strings in numeric columns and etc).

Perhaps the database file was designed that way?

Can you verify that the same data is shown when opened using any other SQLite tool, like DB Browser for SQLite?

**Comment by ShadelessFox** [comment]
Actually, the data appears to be CLOB. The first byte `0x7B` is an ASCII `{`.

**Comment by mholt** [comment]
> As said before, SQLite doesn't have native support for JSON fields,

Right; the TEXT data happens to be JSON, I'm not looking for native JSON-specific type support. Just to display the text (that happens to be JSON) as text.

> Can you verify that the same data is shown when opened using any other SQLite tool, like DB Browser for SQLite?

The same data appears as text in other tools like Table Plus. (I'd get a screenshot but I'm traveling and my other computer has it)

> Actually, the data appears to be CLOB. The first byte 0x7B is an ASCII {.

Interesting (first I've heard of CLOB) -- why does Dbeaver display it as `[` then? And then stop after 11 bytes over in the Value pane...?

(As it is ASCII text, I expect it should simply display ASCII text. That's the goal of the bug report, if I'm not mistaken about something else. I appreciate your feedback!)

**Comment by ShadelessFox** [comment]
I see. Thanks for the information and bug report.

Yet I'm not sure how binary data ended up in the text column.

A nerd explanation: DBeaver displays it that way because this is the default representation of arrays in Java: `[` denotes an array type, `B` denotes `byte`, and the last eight characters resemble hashcode in hexadecimal format.

**Comment by mholt** [comment]
> A nerd explanation: DBeaver displays it that way because this is the default representation of arrays in Java: [ denotes an array type, B denotes byte, and the last eight characters resemble hashcode in hexadecimal format.

That makes sense! I didn't know that. Thank you for working on an enhancement.

> Yet I'm not sure how binary data ended up in the text column.

I'm not sure either. Is the representation different? i.e. If the string "abc" is stored in a TEXT column as a string, are the bytes stored different than if "abc" is stored as binary? I don't have a deep understanding of these things, but I figure the bytes stored would be `97 98 99` either way.
