### ISSUE TITLE
Update repository for Eclipse integration is outdated

### ISSUE THREAD

**Issue by danielgp** [dbeaver/dbeaver#18802]
### Description

https://dbeaver.io/update/latest/ repository still includes the 22.3.1 version although the 22.3.2 has been release quite a few days ago, please make it up-to-date

### DBeaver Version

22.3.1

### Operating System

Windows 10

**Comment by danielgp** [comment]
Same for https://dbeaver.io/update/ce/latest/ which is affecting DBeaver Community Edition 22.3.1 unable to update to 22.3.2...

**Comment by LonwoLonwo** [comment]
Thanks for the report.

Updated.
