### ISSUE TITLE
Setting variables are being ignored

### ISSUE THREAD

**Issue by SajeanSivabalan** [dbeaver/dbeaver#18805]
### Description

I use the @set command to set a variable, but when I use that variable, the bind parameters prompt appears. 

https://user-images.githubusercontent.com/90266198/213221586-413c0892-abfa-4df4-8aab-be9a1a9933c8.mov

### DBeaver Version

Community Edition 22.3.2

### Operating System

macOS Big Sur 11.4

**Comment by E1izabeth** [comment]
Thank you for bug report. It's a duplicate of #18706
The fix is available in the early access version (https://dbeaver.io/files/ea/) and will be available in the next release.
