### ISSUE TITLE
Review Select all rows command

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#18812]
### Description

Now it's not obvious what is the exact purpose of this command and what is the difference between `Evaluate sql expression` and `Select all rows` options from the sql editor context menu. It looks like they do the same. We need to review this option. Maybe we could tune it to make automatic `Select * from <selected text> top 100;` as it was requested here #16074 or remove it.

### DBeaver Version

DBeaver 22.3.3

**Comment by E1izabeth** [comment]
`Evaluate sql expression` evaluates some parts of query, for example it can evaluate 1+2.
` Select all rows` option allows to execute the query under the cursor without limit to fetch all data.

**Comment by huzaifajks** [comment]
@E1izabeth any update? when will this feature available?

**Comment by E1izabeth** [comment]
This issue is closed. In the previous comment I decided how this can be done in DBeaver

**Comment by huzaifajks** [comment]
Can you please provide a sample how you intend to achieve this using mentioned solution?
