### ISSUE TITLE
Result sets and server output not shown

### ISSUE THREAD

**Issue by jetzerb** [dbeaver/dbeaver#18816]
### Description

When I execute batches including multiple result sets, DBeaver displays at most one.  In addition, it doesn't display all the server output.

> NOTE: This is on SQL Server, and I have set a custom statement delimiter of `go` and checked the "Ignore native delimiter" (which is set to `;`), so that I can terminate individual statements in a batch with a semicolon while still having access to variables within the batch.

![image](https://user-images.githubusercontent.com/36859020/213492320-03dcc721-3492-4a0c-860d-559f3e9ee534.png)

### DBeaver Version

Community Edition 22.3.2.202301060755

### Operating System

Windows

### Database and driver

Server:
Microsoft SQL Server 16.00.1000
Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64) 
	Oct  8 2022 05:58:25 
	Copyright (C) 2022 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2022 Datacenter 10.0 <X64> (Build 20348: ) (Hypervisor)

Driver:
Microsoft JDBC Driver 9.2 for SQL Server 9.2.0.0

## Example 1
Three queries, but only 1 result set shown
```sql
declare @var int = 5;

select * from (values (1),(2),(3)) t(IntValue);
print formatmessage('%d integers shown',@@rowcount);

select * from (values ('a'),('b')) t(ChrValue);
print formatmessage('%d characters shown',@@rowcount);

select @var VariableValue;
```
Results, regardless of whether I execute the SQL Statement (CTRL+Enter) or the Script (ALT+X):
- Only the first result set is shown
- Only the first server message is shown
![image](https://user-images.githubusercontent.com/36859020/213493375-85943a64-ef0d-4fa0-86d2-675549182cef.png)

## Example 2 - Part 1
I wanted to verify that the entire script was actually being executed, so modified the script to create a temporary table to hold the data.  But the `create table` statement seems to suppress all output
```sql
create table #audit (chrValue char(1));

select * from (values (1),(2),(3)) t(IntValue);
print formatmessage('%d integers shown',@@rowcount);
```
Results:
![image](https://user-images.githubusercontent.com/36859020/213496413-8dfa0367-07fd-420d-99da-f2d1f9120b6b.png)

## Example 2 - Part 2
The complete script:
```sql
declare @var int = 5;

create table #audit (chrValue char(1));

select * from (values (1),(2),(3)) t(IntValue);
print formatmessage('%d integers shown',@@rowcount);

insert into #audit
output inserted.ChrValue
values ('a'),('b');
print formatmessage('%d characters shown',@@rowcount);

select @var VariableValue;
```
Results are same as above -- `create table` statement suppresses all output.  Checking the temp table shows that the records were indeed inserted:
```sql
select * from #audit;
```
![image](https://user-images.githubusercontent.com/36859020/213497871-7922e41f-f51b-40b6-a7b0-049a1f4b88d4.png)

## Example 3
Similar to example 2 but with the temp table already present in the system before the `select` and `insert` statements are run:
```sql
select * from (values (1),(2),(3)) t(IntValue);
print formatmessage('%d integers shown',@@rowcount);

insert into #audit
output inserted.ChrValue
values ('a'),('b');
print formatmessage('%d characters shown',@@rowcount);
```
Result is the same as in Example 1: only the first rowset is displayed

## Example 4
One result set plus multiple server output messages
```sql
print 'This is the top of the script';
print 'About to insert some records';
insert into #audit
output inserted.ChrValue
values ('a'),('b');
print formatmessage('%d records inserted',@@rowcount);
print 'My work is done here';
print 'I demand to be heard!';
```
Result set is shown, and server output messages up to and including the first one after the result set is generated are shown, but none after that.
![image](https://user-images.githubusercontent.com/36859020/213500660-e228c956-1975-4a66-8cad-c9a126414463.png)

## Example 5
This also occurs in stored procedures.
```sql
create procedure test_bad
as
create table #x (i int); -- the presence of this suppresses the result set
select * from (values (1),(2),(3)) t(IntVal);
```
```sql
exec test_bad;
```
![image](https://user-images.githubusercontent.com/36859020/213744736-dfbeaa57-dbef-49e3-af28-b9e19c8ab956.png)

After removal of the `create table` statement, DBeaver displays the result set:
```sql
create procedure test_good
as
select * from (values (1),(2),(3)) t(IntVal);
```
```sql
exec test_good;
```
![image](https://user-images.githubusercontent.com/36859020/213745830-99244772-c82a-476d-bbdf-35df859c0aa3.png)

**Comment by jetzerb** [comment]
Hmm...seems to be config/setup related.

1. I exited DBeaver
2. renamed my `%AppData%\DBeaverData` directory
3. restarted DBeaver
4. re-applied my desired preferences through the user interface
5. Tested all the examples above, and they worked as expected/desired rather than exhibiting the incorrect behavior documented above.

**Comment by Radioleao** [comment]
I have the same issue, and it is not a matter of delimiter, nor of preferences. And I have a new example.


I notice that:
1. When DBeaver is just started I have no error in output;
2. Since the first time I got this error, it happens everytime until I reboot;
3. **New case**: when I have multiple query and I have a wrong query, I do not get the error message. To debug wrong scripts now I have to move to SSMS.
