### ISSUE TITLE
Table list Pop-up disappear with ESC not working

### ISSUE THREAD

**Issue by shrivatsahosabettu** [dbeaver/dbeaver#18810]
### Description

After changing the font or color in Window->preferences, while typing the SQL pop-up of code hint doesn't disappear with ESC key from Keyboard. 
![image](https://user-images.githubusercontent.com/12061573/213388029-90420ea6-68b8-4466-9f2f-6c5ab52fb3bd.png)

All I need to restart the DBeaver and start working again.

### DBeaver Version

Community Edition 22.3.2

### Operating System

Windows 11

### Database and driver

DB2 12 and com.ibm.db2:jcc:RELEASE 11.5.7.0

![image](https://user-images.githubusercontent.com/12061573/213387292-bf726e79-a7f8-4107-80e6-606c2cda34a0.png)

### Steps to reproduce

1. Try changing any properties like font or color of the SQL statements from top Menu Window--> Preferences
2. Save and now type the SQL which will pop-up the hint options menu.
3. Try press ESC key on the keyboard.
4. The pop-up doesn't go away.

**Comment by E1izabeth** [comment]
Please provide log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by shrivatsahosabettu** [comment]
Please find the log files as requested.
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10454808/dbeaver-debug.log)
[Normal.log](https://github.com/dbeaver/dbeaver/files/10454821/Normal.log)

Please let me know if you need any further information.

**Comment by E1izabeth** [comment]
We have made some changes which hopefully fix this bug in scope of this issue #18771.
Could you try early access version https://dbeaver.io/files/ea/ (or new release version on Monday) to see if the issue was fixed for you?

**Comment by shrivatsahosabettu** [comment]
Thank you so much. I tried the early access version and autocompletion pop-up is disappearing with ESC. 
You can mark this issue close or wait for others feedback until Monday.

**Comment by E1izabeth** [comment]
Thank you. I'll close thus bug, but please inform me if the issue will happen again.
