### ISSUE TITLE
Horizontal scrolling using native Logitech feature

### ISSUE THREAD

**Issue by yan-hic** [dbeaver/dbeaver#18813]
### Description

Horizontal scrolling works using Shift+Wheel but it doesn't using the dedicated wheel for lateral scrolling with mice having that feature. The scroll bar flashes but editor or grid don't move.
Tested with Logitech MX Master

### DBeaver Version

CE 22.3.2

### Operating System

Win10 Pro

### Database and driver

N/A

### Steps to reproduce

Use a (Logitech) mouse with dual wheels

### Additional context

https://www.loom.com/share/b5bc05044e0e43d894fa92f18b4e62b5
See video - scrollbar flickers when using lateral wheel. Then I used Shift +"standard" wheel, which works.

**Comment by yan-hic** [comment]
Hmm. Updating the Logitech Options software resolved the issue... Let's say I opened this if someone hit the snag.

**Comment by yan-hic** [comment]
Re-opening as behavior is not consistent. It does not work more often than it does.
Shift-Scroll is a workaround but native horizontal scrolling is better - and works in most other apps.

**Comment by E1izabeth** [comment]
Please, specify your OS

**Comment by yan-hic** [comment]
updated + recorded video

**Comment by arhayka** [comment]
Duplicate #8404
