### ISSUE TITLE
Table/View listing pop-up with Alias along with the starting characters

### ISSUE THREAD

**Issue by shrivatsahosabettu** [dbeaver/dbeaver#18826]
When a table or a view typing on the SQL command pop-up appears and we can select the table/view name from the pop-up list. Also when we select the table/view from the pop-up list an alias attached to it comes automatically. Can we make that pop-up list to appear with the alias name along with the table_name as well?

Example: If the table name is _Employee_Tax_Summary_Trans_ Table, then we can type with Employee and all the table names starting with Employee is listed in the pop-up, can we add pop-up to appear along with the starting Employee the alias for this one like **_etst_**.

Pop-up to appear along with the starting Table Name or the Alias name

I don't have alternative for this one.

**Comment by arhayka** [comment]
Could you specify why you need this feature? Describe your case, please.

**Comment by shrivatsahosabettu** [comment]
Hi Thanks for looking into this and coming back with the question.
Here below are the things which I think its beneficial with the search
1. With the alias name the pop-up of table names will not have too many tables to go through the list and select.
- This also reduce the over head on the pop-up search functionality
2. I remember the table names by alias like the above one that's the test name but in the actual production system most of the table name I refer by the alias.

Moderators of product can take the call on this feature.

Thanks

**Comment by arhayka** [comment]
Unfortunately, we won't be able to implement it right now because it will drastically change the default behavior of autocomplete proposals and will disrupt the workflow for most of the users. Maybe we will find a more delicate way of implementing this later.
