### ISSUE TITLE
Firebird: Conversion of DECIMAL to INTEGER if a stored procedure parameter type

### ISSUE THREAD

**Issue by tautf** [dbeaver/dbeaver#18836]
### Description

As reported in Firebird repository, the problem seems to be related to DBeaver.

https://github.com/FirebirdSQL/firebird/issues/7457

### DBeaver Version

22.3.1

### Operating System

macOS Ventura 13.1 / Windows 11 Pro

### Database and driver

- Firebird 3.0.10.33601
- Jaybird JCA/JDBC 4.0.0

### Steps to reproduce

1. Create procedure with above script
2. View scripts source with DBeaver explorer

**Comment by tautf** [comment]
Look like a maintainer of Firebird already found the issue with DBeaver:  https://github.com/FirebirdSQL/firebird/issues/7457#issuecomment-1400483932

**Comment by mrotteveel** [comment]
See [`org.firebirdsql.jdbc.metadata.TypeMetaData#getDataTypeName`](https://github.com/FirebirdSQL/jaybird/blob/9d62540db50312f178b123e5a405b9bb429f83b1/src/main/org/firebirdsql/jdbc/metadata/TypeMetadata.java#L294) for how Jaybird infers the type name for its own metadata methods. It looks like some of the newer types (DECFLOAT, INT128, TIME WITH TIME ZONE, TIMESTAMP WITH TIME ZONE, and NUMERIC/DECIMAL with precision between 19 and 38) are missing as well.

**Comment by LonwoLonwo** [comment]
Thanks for the report.
Our FireBirdFieldType class is outdated.

**Comment by tautf** [comment]
@LonwoLonwo Can you tell if this will be fixed soon?

**Comment by LonwoLonwo** [comment]
It definitely will not be fixed soon. We have much work to do. You can see the tickets count. Maybe three months, six.  

But we are open to contributions :)
