### ISSUE TITLE
Unable to edit MySQL JSON fields

### ISSUE THREAD

**Issue by nzimmerman-entegral** [dbeaver/dbeaver#18840]
### Description

After recently updating from `Community Edition 22.3.1` I am unable to edit values in a JSON column of a MySQL 5.7 database. This issue appears in both CE versions `22.3.2` and `22.3.3`.

Here's an example of a schema definition with a JSON field that was editable as of CE 22.3.1:
```
CREATE TABLE `answer` (
  `participant_company_id` int(11) NOT NULL,
  `question_id` int(11) NOT NULL,
  `answer_value` json DEFAULT NULL,
  `deleted` tinyint(1) DEFAULT NULL,
  `not_applicable` tinyint(1) DEFAULT NULL,
  `entered_date` timestamp(3) NULL DEFAULT NULL,
  `entered_by` int(11) DEFAULT NULL,
  `last_update` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`participant_company_id`,`question_id`),
  KEY `pro_answer_last_update_IDX` (`last_update`,`question_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

### DBeaver Version

Community Edition 22.3.3

### Operating System

Ubuntu 22.04.1

### Database and driver

Database: MySQL 5.7.18-15
Driver: MariaDB JDBC Driver 3.0.7

### Steps to reproduce

1. Connect to the MySQL 5.7 database 
2. Execute a select query against a table with a JSON data field (example schema definition in the description)
3. Double-click the JSON field in the results to toggle edit mode
4. When I attempt to change a value, I hear a beep from the application and no keyboard input is recognized. The field header has a dot in the lower-left that displays a message about being read-only

I am able to edit other fields in the table just not the JSON field.

**Comment by LonwoLonwo** [comment]
Hello @nzimmerman-entegral 

What is the reason for using the MariaDB driver for the MySQL database?

> Database: MySQL 5.7.18-15
> Driver: MariaDB JDBC Driver 3.0.7

MariaDB does not have a JSON data type, only as an alias.

So you can use MySQL driver instead.

![2023-01-13 12_44_38-Создать соединение](https://user-images.githubusercontent.com/45152336/212289476-c68f2112-d2a2-41da-818d-5d7bd215786c.png)

Quick way:

![2023-01-13 12_45_55-](https://user-images.githubusercontent.com/45152336/212289506-0af91f13-0ed4-4ff6-ad94-a2b7dbbd3284.png)

**Comment by LonwoLonwo** [comment]
Duplicate: https://github.com/dbeaver/dbeaver/issues/18756

**Comment by nzimmerman-entegral** [comment]
Hi @LonwoLonwo 

I'm using the MariaDB connector because it supports my company's LDAP authentication flow with dynamic credentials to our database. It hasn't caused any issues with the JSON fields until now.

**Comment by nzimmerman-entegral** [comment]
Hi @LonwoLonwo 

I tried switching to the MySQL connector as you suggested and I'm able to connect and edit JSON fields again. My company recently switch auth providers and it appears that the MySQL connector is supported by the new one.

**Comment by E1izabeth** [comment]
@nzimmerman-entegral so the issue is solved for you?

**Comment by nzimmerman-entegral** [comment]
@E1izabeth yes, switching from the MariaDB to the MySQL connector allows me to edit JSON fields again.
