### ISSUE TITLE
Note and Connection options disappeared from not custom ERD

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#18841]
### Description

![image](https://user-images.githubusercontent.com/43252954/214085904-3d732ebe-74bf-4fb3-a2c3-bbbb505febe0.png)
![image](https://user-images.githubusercontent.com/43252954/214085929-f0369484-a970-47a4-8d97-3068c7aeedb9.png)

Since 22.2.2 2 options in ERD Palette have disappeared

### DBeaver Version

22.3.3

**Comment by serge-rider** [comment]
Fixed
