### ISSUE TITLE
Replace [v] by graphical chekboxes 

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#18856]
Since a while boolean values, represented by checkboxes are presented in textual way eg: [v].

I preferred previous version - shown on screen below. In my opinion this was more intuitive and has better / clear visibility 

Is there any chance to return to that? Or at least leave user option to change that in preferences?

![obraz](https://user-images.githubusercontent.com/5410448/214264803-55ba29ec-5603-4f61-b7d7-93ff52dbc8b7.png)

**Comment by Destrolaric** [comment]
Hi, `Editors -> Booleans` there. You could change the boolean presentation to a more favorable format. Could you write me if it helps?  
![image](https://user-images.githubusercontent.com/20579256/214266278-fd0e7a62-2651-4bf5-a37f-ba041e6492fd.png)

**Comment by maciey** [comment]
@Destrolaric - thank you !!! This is exactly I was looking for!
