### ISSUE TITLE
Update MySQL driver version

### ISSUE THREAD

**Issue by mdks2010** [dbeaver/dbeaver#18869]
### Description

Unable to download MySQL  8.0.31、 8.0.32 drivers from   https://repo1.maven.org/maven2/mysql/mysql-connector-java

### DBeaver Version

22.3.3

### Operating System

win10

### Database and driver

MySQL
8.0.32

**Comment by LonwoLonwo** [comment]
Hello @mdks2010 

Mm.. ok. It is sad. But how can we fix it?

https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.mysql/plugin.xml#L215

> maven:/mysql:mysql-connector-java:RELEASE[8.0.29]

You can see in our code that we have the hardcoded 8.0.29 version. And it is available.

You may need to create a ticket on the MySQL bug tracker.

**Comment by gittrolo** [comment]
https://blogs.oracle.com/mysql/post/mysql-connectorj-has-new-maven-coordinates.

The repository has changed. You have to change it. It isn't a bug of MySql

New repository: https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/

**Comment by LonwoLonwo** [comment]
We do not have a link to the latest Release version for the usual MySQL driver. We have a link to the stable version.

We had an issue with the NDB Cluster driver, but we fixed the link there. #18488

We will change the MySQL driver link only when we update it to the latest version. And it is not now. I do not see any specific reasons to do it now. If you know - please, let me know.

**Comment by gittrolo** [comment]
Isn't 8.0.32 the latest stable version?

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/pull/21851
Updated till 8.2.0
Will be available in the next (23.2.5) DBeaver version.
