### ISSUE TITLE
Geometric line with only one point in Postgresql/PostGIS gives unhelpful error

### ISSUE THREAD

**Issue by PeterBrodersen** [dbeaver/dbeaver#18861]
### Description

When viewing a field with a geometry linestring with only one point (which is allowed in PostGIS) the result tab shows the field with  a purple background colour and the text

> Invalid hex digit: 'L'

When changing to Spatial view a new error message pops up:

> Can't switch presentation
> Reason:
> Invalid hex digit: 'o'

The value does not show up in the value panel either.

It is true that an OGC-valid LineString has either zero or two or more points, but [PostGIS also allows single-point LineStrings](https://postgis.net/docs/using_postgis_dbmanagement.html#LineString). Also, other invalid geometries can be shown without getting an error message.

How to display the value spatially is an open question, however it should be possible just to see the value as-is, just as other geometric values are shown as text. In any case the error messages are unhelpful.

### DBeaver Version

22.3.3.202301211053

### Operating System

Windows 11

### Database and driver

Server: PostgreSQL 13.4, PostGIS 3.2.3
Driver: PostgreSQL JDBC Driver 42.2.5

### Steps to reproduce

1. Connect to PostgreSQL database with PostGIS
2. Create line with a single point, e.g.: `SELECT ST_MakeLine(ST_MakePoint(10, 20));`
3. View result: `Invalid hex digit: 'L'`
4. Click on Spatial tab and view result: `Invalid hex digit: 'o'`

### Additional context

Screenshot with error message and no value for field:
![image](https://user-images.githubusercontent.com/31605591/214310854-f4692758-7100-4244-9a20-11b8c0fca2c8.png)

Screenshot of error message when clicking on Spatial tab:
![image](https://user-images.githubusercontent.com/31605591/214311101-48d3d6c5-f89f-4c4b-b06e-34a69c695f2d.png)

**Comment by PeterBrodersen** [comment]
For what it's worth: DBeaver accepts and can visualize a line with two identical points, e.g.:

```SQL
SELECT ST_MakeLine(ST_MakePoint(0,0), ST_MakePoint(0,0))
```

This suggests that the concept of a line without any length is currently accepted by DBeaver in some form.

**Comment by ShadelessFox** [comment]
This is a bug/feature in the geometry library we're using. It expect at least two points for the `LINESTRING`.

Perhaps we could patch it somehow.

**Comment by arhayka** [comment]
Thank you for your report.

**Comment by arhayka** [comment]
Thank you for your report.
