### ISSUE TITLE
Horizontally scrolling in data browser

### ISSUE THREAD

**Issue by GiantCrocodile** [dbeaver/dbeaver#1886]
It would be nice to be able to scroll horizontally in data browser if you can't scroll up/down or if you have scrolling active and move your mouse to right/left.

**Comment by igor-loban** [comment]
It would be nice to have horizontal scroll on _shift + scroll wheel_ like in the most of browsers

**Comment by serge-rider** [comment]
Horizontal scrolling of data viewer was added in 5.x version.
