### ISSUE TITLE
Little Code Completion windows don't close anymore when using ESC

### ISSUE THREAD

**Issue by bcoulam-fmg** [dbeaver/dbeaver#18867]
### Description

My real problem is I had the Auto activation delay set to 0ms. So every time I'd type a table or view alias, followed by a dot, code completion would come up. Most of the time it was unwanted, so I'd hit ESC with me left pinky to make it disappear. Today I upgraded DBeaver Community to 23.3.3.202301211053 And now when I type the alias and the dot, the code completion pops up and won't go away when I hit ESC. I have to click inside one of the two code completion windows in order for ESC to close them.

In fact, the little code completion windows remained on my screen when I Alt + Tab'ed to return here to github to paste the screenshot I'd copied (it's very persistent unless you click inside one of the code completion window first).

I had some screenshots to share with you, but I get a "Something went really wrong" error from Github when I attempt to paste an image from my clipboard here in the Description, or when I try to attach some jpg or png images. Perhaps my org has the network locked down to not allow uploading...not sure.

FYI I have changed the Auto activation delay to 1500ms to prevent seeing this issue in the future, except when I delay and think about a column name after typing the alias and then a dot.

### DBeaver Version

Community Edition 23.3.3

### Operating System

Windows 10 Enterprise

### Database and driver

Azure for Postgres 11.17 (yeah, I know how old it is)

### Steps to reproduce

1. Connect to postgres DB and start typing some SQL that queries from a table. Give the table an alias.
2. Type the alias then a dot in the WHERE clause to bring up code completion, one for all the columns in the table, and one for the highlighted column.
3. Hit the ESC key, the code completion windows do not close.
4. You have to click inside either of the two code completion windows now, THEN hit ESC in order for them both to close.

99.5% sure it did not behave this way in the last version which I replaced with 23.3.3 this morning.

**Comment by LonwoLonwo** [comment]
Hello @bcoulam-fmg 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by bcoulam-fmg** [comment]
Hi,

Well this is embarrassing. I have got to learn that the first step in troubleshooting should be restart the app and the laptop.
All day yesterday, after upgrading to 23.3.3, it was behaving as described in the ticket.
This morning, after a company-forced update and restart, and a restart of DBeaver, it is not behaving the same: the ESC key now makes the code-completion window go away, just as it did before 23.3.3

I’ve attached logs anyway, in case you still want to look into what it was doing on Jan 24th.

bc

**Comment by Destrolaric** [comment]
@bcoulam-fmg Unfortunately, attachments don't work if the response is by mail. Could you send it via the GitHub message?

**Comment by bcoulam-fmg** [comment]
[dbeaver-debug-1674656660324.log](https://github.com/dbeaver/dbeaver/files/10500443/dbeaver-debug-1674656660324.log)
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/10500451/dbeaver.log)

FYI, when I attempted to upload the .log file, GitHub kept saying it was "hidden" and to try again. I checked its properties and it wasn't hidden. I copied it to C:\Temp and that changed nothing. So I renamed it dbeaver.log and it finally uploaded.

**Comment by LonwoLonwo** [comment]
We fixed this specific issue in the last release.
So we can close the ticket.
If this problem happens again - feel free to reopen it.

**Comment by bcoulam-fmg** [comment]
Thank you.

**Comment by wesleyaip** [comment]
> We fixed this specific issue in the last release. So we can close the ticket. If this problem happens again - feel free to reopen it.

It's happening to me in the version 23.2.3.202310221533.
