### ISSUE TITLE
Cannot connect in SSL to AS400 Database

### ISSUE THREAD

**Issue by robertocanton** [dbeaver/dbeaver#18873]
### Description

After upgrade to version post 22.0.0 i cannot connect to AS400 databases in SSL. Similar to version 22.0.0 i put the certificates in cacerts and place it in jre/lib/security of DBeaver Path. 
In version 22.0.0 this configuration work fine after this version the configuration stop working.

### DBeaver Version

Community Versione 22.3.0

### Operating System

Windows 10

### Database and driver

DB2 AS400 (iSeries)

### Steps to reproduce

Put the cacerts under jre/lib/security of dbeaver path
Create the connection
Download the Driver
Set host information
Set to true the secure variable of the driver
Then try connection

**Comment by LonwoLonwo** [comment]
Hello @robertocanton 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by robertocanton** [comment]
Hi, in attachment the application log.
Thanks

Il giorno mer 25 gen 2023 alle ore 16:37 Anastasiya <
***@***.***> ha scritto:

**Comment by LonwoLonwo** [comment]
Hello @robertocanton 

Please use this GitHub page to attach the file. It doesn't work via e-mail.

**Comment by robertocanton** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10508509/dbeaver-debug.log)

**Comment by robertocanton** [comment]
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/10508527/dbeaver.log)

**Comment by LonwoLonwo** [comment]
Please refer to this article. https://github.com/dbeaver/dbeaver/wiki/Importing-CA-Certificates-into-DBeaver

or check this related tickets: https://github.com/dbeaver/dbeaver/issues/15647, https://github.com/dbeaver/dbeaver/issues/15612, #16608

**Comment by robertocanton** [comment]
Solved disabling flag "Use Windows trust store"
![immagine](https://user-images.githubusercontent.com/23379568/215713847-c904b8a5-48c3-4a8c-addf-35bdef24d34c.png)
