### ISSUE TITLE
Task on PostgreSQL native client hangs

### ISSUE THREAD

**Issue by ladeche** [dbeaver/dbeaver#18876]
### Description

I have a fairly simple script (it looks dumb but it's just for the purpose of the bug).

`
SELECT 'DEBUT',clock_timestamp(); 

CREATE
TEMPORARY TABLE test1 AS
SELECT *
FROM tmpJOOOOLANCact;
 
select * from test1;

`

The CREATE TABLE works but the session hangs on SELECT *. Here's a few observations : 
- Table test1 has only 30 rows.
- If I replace "select * from test1;" by "select * from test1 LIMIT 10;", it works
- If I replace "select * from test1;" by "select * from test1 LIMIT 20;", it just hangs as with no limit
- If I execute manually the script using psql.exe on a command line, no problem occurs.

Thanks for your help.

Regards.

### DBeaver Version

Community Edition 22.2.2.202210092258

### Operating System

Windows 10 Enterprise

### Database and driver

PostgreSQL 14.2 native client
PostgreSQL 12.5 Server

### Steps to reproduce

1 Create task with script above
2 Execute task (=> task hangs)

**Comment by iraidaa** [comment]
Hi @ladeche,

Please describe how the session hangs. DBeaver stops working, so you can't use UI in any way (completely frozen, unresponsive UI), or is something loading endlessly, but you can click some buttons?

**Comment by ladeche** [comment]
Hi @iraidaa,

Dbeaver UI works fine, I can do whatever I want.

Maybe my case is unclear. I have created a task of "PostgreSQL script" type which is base on PostgreSQL native client. When I launch the task it hangs after the CREATE TABLE. For some reason the last SELECT is not launched. So the task hangs and the session is still opened and idle on the database (I can see it with pg_top). IF I add "LIMIT 10" to my select it works. If I replace "LIMIT 10" by "LIMIT 20", again the task hangs. Very weird.

Still DBeaver UI works and I can cancel the task execution with the UI to kill the session.

Regards.

**Comment by arhayka** [comment]
Hi @ladeche,
Could you please try to generate a thread dump and attach it here? Here is the instruction: https://dbeaver.com/docs/wiki/Making-a-thread-dump/
Thank you.

**Comment by ladeche** [comment]
[thread-dump.txt](https://github.com/dbeaver/dbeaver/files/10853131/thread-dump.txt)
Hi @arhayka,

I started the task (test_tache_pp01_prob) which then was hanging then I generated the thread dump.

psql.exe which was launched by the task is hanging.

While the task is running (ie hanging) I have access to DBeaver UI without any problems.

If I kill manually psql, the task ends with an error.

Thanks and regards.

Laurent.

**Comment by iraidaa** [comment]
The issue remains in 23.0.0 with PostgreSQL 12  and PostgreSQL 14.2 native client.

The script added to the task contains only the following query

```
CREATE
TEMPORARY TABLE test1 AS
SELECT *
FROM actor;
select * from test1;
```

Table test1 has 203 rows.

Information regarding the task creation
![image](https://user-images.githubusercontent.com/49681450/225593242-2d616e26-4b1a-4c74-b6dd-7527dd396908.png)


![image](https://user-images.githubusercontent.com/49681450/225593023-bdc345fa-b14c-45d4-9be2-bad02d18a2f8.png)

![image](https://user-images.githubusercontent.com/49681450/225593093-648f7066-4b14-4cc0-9a38-58abb78d8acb.png)


The task hangs while the UI is still fully responsive, and it's possible to click Cancel Operation, which ends with the error

![image](https://user-images.githubusercontent.com/49681450/225593317-1d7fec34-2156-4cde-98d3-8c88800ed7ac.png)

![image](https://user-images.githubusercontent.com/49681450/225593380-09fc25ac-5475-4849-8c53-3a4b9082b521.png)

The same task with the limit 10 (or limit 20 or limit 40)  works without any hanging
```
CREATE
TEMPORARY TABLE test1 AS
SELECT *
FROM actor;
select * from test1
limit 10;
```

![image](https://user-images.githubusercontent.com/49681450/225593777-eef8182f-b28a-4ed0-96df-86f11c041ee9.png)

However, the same endless Executing with the limit 100.

![image](https://user-images.githubusercontent.com/49681450/225594292-7fa78317-298c-4867-9791-eeef5279c008.png)
