### ISSUE TITLE
Get prompted every time a variable is referenced in a SQL script

### ISSUE THREAD

**Issue by cnguyen1161** [dbeaver/dbeaver#18885]
### Description

I upgraded DBeaver Community Edition to version 22.3.3.202301211053 a few days ago. After this upgrade the behavior of the variables in DBeaver has changed., I use @set statements to setup values for the variable and was able to use them throughout my SQL scripts. The same scripts now kept prompting for the value of the variables. Looks like it does not use the values that I set in the script. Even after I entered the value in the "Bind parameters" dialog, it popped up each time the variable is used.

I have been searching to see if there is setting that I can control but to no avail... thinking of downgrading to 22.3.2,

Thanks

### DBeaver Version

Community Edition 22.3.3

### Operating System

Windows

### Database and driver

Snowflake

### Steps to reproduce

@set v_WorkFlow = Clone_Operations_Schema
@echo ${v_WorkFlow}, ${V_WORKFLOW}
select '${v_WorkFlow}';

**Comment by E1izabeth** [comment]
Thank you for bug report.
