### ISSUE TITLE
DBeaver (22.3.3) dropping system client messages from Postgresql

### ISSUE THREAD

**Issue by P-Blackburn** [dbeaver/dbeaver#18896]
### Description

In the latest version of DBeaver (22.3.3) some messages from Postgresql are being dropped when they should not be.  This may be a similar issue to #18882, but I can confirm that although  #18882 suggests the issue may be fixed in the ea version, that this and  #18882 appear to still be an issue in the latest ea too, 

I attach screen prints showing the difference between Dbeaver 22.2.1 and 22.3.3 when executing the following:

DO
$$
BEGIN
SET CLIENT_MIN_MESSAGES = DEBUG5;
RAISE DEBUG 'DEBUG %', pg_backend_pid();
RAISE NOTICE 'NOTICE %', pg_backend_pid();
RAISE INFO 'INFO %', pg_backend_pid();
RAISE WARNING 'WARNING %', pg_backend_pid();
END;
$$

### DBeaver Version

Community Edition 22.3.3

### Operating System

Windows 10

### Database and driver

Postgresql 15
jdbc:postgresql://

### Steps to reproduce

Try to execute a RAISE DEBUG or RAISE NOTICE in plpgsql and in Dbeaver 22.2.3 and message is not displayed earlier versions (e.g. 22.2.1) returned the messages.

This is what 22.2.1 returns:
![image](https://user-images.githubusercontent.com/47189653/215146545-aad5c721-de85-4861-81b5-8bab509fb66c.png)

This is what 22.3.3 returns:
![image](https://user-images.githubusercontent.com/47189653/215147418-c7c954e4-361f-4cf3-867a-159617638bf0.png)

**Comment by P-Blackburn** [comment]
This bug has occurred since version 22.3.2 as 22.3.2 correctly displays messages:

![image](https://user-images.githubusercontent.com/47189653/215149714-65321374-869b-4fc4-84f9-983feaab8155.png)

**Comment by uslss** [comment]
thanks for the report
