### ISSUE TITLE
Problem with postgres function debug

### ISSUE THREAD

**Issue by dlasak** [dbeaver/dbeaver#18892]
### Description

During debugging postgres function through dbeaver debugger plugin following message pops out

"ERROR: ... is not a procedure
  Hint: To call a function, use SELECT.
  Position: 6"

### DBeaver Version

Comunity Edition 22.3.3.202301211053

### Operating System

Windows 10 Enterprise

### Database and driver

1. Postgres 13.9
2. jdbc driver 42.5.0

**Comment by ShadelessFox** [comment]
Hello @dlasak,

The PostgreSQL debugger extension doesn't support functions.

The same behavior can be seen in pgAdmin - you can't debug functions.

**Comment by dlasak** [comment]
You mean functions? I am able to debug procedures.
As I thought. Thanks for the confirmation.

Regards

**Comment by ShadelessFox** [comment]
I'm sorry, I meant functions, of course. The debugger supports just procedures.

**Comment by dlasak** [comment]
Hm
I am able to debug functions and procedures using pgadmin, stepping over line after line but getting message "Error while fetching stack information." . I have everything configured properly according to https://www.pgadmin.org/docs/pgadmin4/latest/debugger.html

I see some related topic :|
https://github.com/pgadmin-org/pgadmin4/issues/5784

**Comment by ShadelessFox** [comment]
I'm not sure what is the difference

**Comment by ShadelessFox** [comment]
It looks like pgAdmin indeed allows debugging functions, but only with the `LANGUAGE 'plpgsql'` or `LANGUAGE 'edbspl'` clause. My bad.

Sorry for confusing you, and thanks for providing additional resources.

**Comment by dlasak** [comment]
Yep, I am checking plpgsql function and on main page functions are listed explicitly(https://www.pgadmin.org/docs/pgadmin4/latest/debugger.html). As I mentioned I get "Error while fetching stack information." message in pgadmin using step over.
It looks like any function execution in the procedure causes the problem.

Not sure if it is a problem with debugger or pgadmin so don't bother and close this ticket please.

**Comment by ShadelessFox** [comment]
I believe function debugging is broken in DBeaver for all types of functions, including ones having the mentioned clause.

I won't close the ticket because we want to resolve this issue.
