### ISSUE TITLE
Freeze when creating indexes (like primary key) from GUI

### ISSUE THREAD

**Issue by bob27aggiustatutto** [dbeaver/dbeaver#18898]
### Description

If I create a primary key over a large table (1 million records) all dbeaver freeze.

That only happens if I create the primary key from the GUI editor, if I run the "create index" query the only thing that freeze is the query window, not the whole dbeaver.

I'm not against freezing, but it should be only the GUI editor that freezes.

### DBeaver Version

22.3.3

### Operating System

Win 10

### Database and driver

JDBC Thin Client
Oracle 21 server

**Comment by arhayka** [comment]
Thank you for your report.

**Comment by serge-rider** [comment]
Cannot reproduce anymore.
For long-running save operations DBeaver shows progress monitor in the status bar. You can interrupt operation by clicking on red square button

**Comment by uslss** [comment]
cannot reproduce against 23.3.3
