### ISSUE TITLE
CTRL+SHIFT Forward & Backward Doesn't behave similar

### ISSUE THREAD

**Issue by shrivatsahosabettu** [dbeaver/dbeaver#18903]
### Description

CTRL+SHIFT Forward & Backward Doesn't behave similar functionality.

CTRL+SHIFT Forward Functionality

- If the line start with SPACE and then keyword or column names, then the combination key press will first select the SPACES and then if you keep pressing then it will select the column names.
- If the column names are consists of _ then the selection will stop at each charact before starting the _(underscore).
- At the end of the column name it select the rest of the space if the column name ends.

CTRL+SHIFT Backward Functionality

- If the column name value is ending with space, then the combination key press will select the spaces along with the value.
- If the column names are consists of _ then the selection will stop at each charact before starting the _(underscore).

Quoted string doesn't select in one go. 
First combination key press is selecting the first quote the the string and then the last quote.
If there is a special character in the String itself, again the combination key press will stop at that special character.

### DBeaver Version

Community Edition 22.3.3

### Operating System

Windows 11

### Database and driver

DB2 12 and com.ibm.db2:jcc:RELEASE 11.5.7.0

![image](https://user-images.githubusercontent.com/12061573/215477841-959781f9-295f-4d2b-884e-a91022e24a19.png)

### Steps to reproduce

- Write some SQL and follow the procedure with CTRL+SHIFT forward and Backward key.

Notepad++ has good selection of the text for this combination key as an example on what is the expectation of the fix.

**Comment by E1izabeth** [comment]
There is an issue about selecting words with underscores #1155
Other described cases looks consistent for me: space after word is grabbed, but space before the word for the cursor on the position after previous word is not grabbed. It works the same as eclipse source code editor.

**Comment by shrivatsahosabettu** [comment]
Thank you @E1izabeth for clarification of the issues reported. I didn't knew that it is working as per the eclipse source code editor.
