### ISSUE TITLE
dBeaver stops responding then crashes when connecting to too many servers

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#18912]
### Description

When using dBeaver Community it inevitably stops responding and then crashes if I connect to too many different servers.  
I regularly connect to between fifty and sixty linux servers, each serving one or more PostgreSQL clusters, each containing two or more databases.  If I connect to too many in a single dBeaver session, it crashes.  I've even tried disconnecting from the server when I immediately done working with it, forcing me to reconnect a few minutes later, to see if that helps.  No difference.

dBeaver is very difficult to use for any extended length of time because of this.

### DBeaver Version

Community 22.3.3

### Operating System

Windows 10

### Database and driver

PostgreSQL 11-15

### Steps to reproduce

Start dBeaver, connect to server, connect to db, do work, connect to other server, etc. etc. etc.
Eventually dBeaver will grey out with the message stopped responding
This will be followed by a crash.  No java Heap or other messages appear.

**Comment by ShadelessFox** [comment]
Hello @coleman-rik,

Could you please make a thread dump next time DBeaver stops responding?

You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump. Thank you.

**Comment by E1izabeth** [comment]
It's been a long time since no update here. If you encounter this issue again, please let me know and provide a thread dump.

**Comment by coleman-rik** [comment]
when I get a chance between constantly having to wait until the stops responding goes away, I have to kill the task, restart dBeaver and if I'm really lucky not have to redo all of my work.
