### ISSUE TITLE
DBeaver Graphical UI Bug RHEL 7.9

### ISSUE THREAD

**Issue by advra** [dbeaver/dbeaver#18911]
### Description

I have 2 machines one that has internet and another without. Both use Red Hat Enterprise v7.9 and installed the package `dbeaver-ce-22.3.3-stable.x86_64.rpm` with `sudo rpm -ivh dbeaver-ce-22.3.3-stable.x86_64.rpm`. 

Machine with internet runs DBeaver fine; however, the network airgapped machine has a graphical GUI bug. DBeaver opens up. But the usual dialog prompt "Create a Sample Database" appears but the buttons "yes" and "no" are hidden. Similarly a majority of the DBeaver GUI does not load and is mostly a combination of black and white windows. Im unsure why this is occurring on the offline machine.

(I would post a screenshot but unfortunately my org forbids it.. but it is almost similar to #6913 but I cannot get past the initial dialogue)

### DBeaver Version

Community Edition 22.3.3

### Operating System

Red Hat Enterprise v7.9

### Database and driver

MariaDB Driver

### Steps to reproduce

1. Open DBeaver from Applications start menu or in terminal `dbeaver &`. 
2. DBeaver splash loads fine (no issues)
3. DBeaver loads with prompt asking sample database (missing buttons) and majority of the GUI is not loading

**Comment by advra** [comment]
I forgot to mention default  java is 8 via `which java` and echoing `JAVA_HOME`. I changed the config to Java 11 as suggested [here](https://stackoverflow.com/questions/44095665/a-java-runtime-environment-jre-or-java-development-kit-jdk-must-be-available) . I added thisflag at the top of the dbeaver config file to try and point to java 11 in hopes it resolved the issue. Unfortunately it did not resolve the graphical bug and Im out of ideas.

```
# /usr/share/dbeaver-ce/dbeaver.ini
-vm
/opt/gs/java-11/bin

# rest of default configs in file 
```

**Comment by advra** [comment]
Update 2: After comparing both log outputs it looks like this is related to gtk. Problematic machine says messages:
```
Gtk-WARNING **: 00:33:06.827: Theme parsing error: gtk.css:342:51. The :insensitive pseudo class is deprecated. Use :disabled instead.  
```

**Comment by advra** [comment]
After looking more into the gtk packages it appears the themes are inconsistent across the board. I was using a dark mode theme called `xfce_dusk`. Changing the problematic workstation to `Adwaita` fixed the problem.

**Comment by arhayka** [comment]
Have you tried the solutions provided here? https://github.com/dbeaver/dbeaver/issues/6640#issuecomment-526537443

**Comment by advra** [comment]
Hi @arhayka. I solved the problem in the third comment by changing my OS theme on red hat.

**Comment by Destrolaric** [comment]
@advra Hi, did you have a dark/white theme on DBeaver and a white/dark theme in the system? This is a common issue, unfortunately, we can't exactly do something about it for now.

**Comment by advra** [comment]
Hi @Destrolaric that was correct. I figured out it was my dark theme. Changing it back resolved the issue. I used RHEL's default themes. The dark theme was `xfce_dusk` and switching to the default light theme `Adwaita` fixes the issue.

**Comment by Destrolaric** [comment]
@advra Unfortunately can't do something meaningful regarding this issue; our framework uses System colors for some of the editors. If the System changes them, that may lead to the colors being too different for the color theme.
