### ISSUE TITLE
new connection failed with error 'Error getting JDBC meta data: invalid operation: permission denied for schema information)schema' #18931

### ISSUE THREAD

**Issue by nancy506** [dbeaver/dbeaver#18932]
### Description

when creating a new connection for a user that does not have permission access to information schema, it shows the following error and test connection failed

Error getting JDBC meta data: invalid operation: permission denied for schema information)schema'

### DBeaver Version

Community  22.3.3

### Operating System

macOS Monterey 12.6.2

### Database and driver

redshift

redshift driver provided by Dbeaver by default

### Steps to reproduce

1. create a new connection
2. select redshift
3. enter user name, host, password, port, database name
4. test connection

**Comment by LonwoLonwo** [comment]
Hello @nancy506 

Do you have any specific reason not to grant permissions to the information_schema?
If not, please do or ask your DBA to do the following:

`GRANT USAGE ON SCHEMA information_schema TO <user_name>;`

**Comment by nancy506** [comment]
yes, it is a user I do not want to grant usage to information_schema.

**Comment by nancy506** [comment]
I was able to create new connection for that user on my other laptop though, the permission issue does not seem to hinder the new connection. It is only for that particular device,  I was unable to create new connection

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by nancy506** [comment]
[](url)
![image001](https://user-images.githubusercontent.com/34636919/216572244-b4ecadba-96c2-44d2-9e70-50264a50ef12.png)

**Comment by LonwoLonwo** [comment]
Please provide the file: https://dbeaver.com/docs/wiki/Log-files/#log-files

**Comment by nancy506** [comment]
Thanks! will do. my other device is not with me right now, so bear with me for a few days.

**Comment by nancy506** [comment]
here is the log file. Thanks!
[log.txt](https://github.com/dbeaver/dbeaver/files/10673139/log.txt)

**Comment by nancy506** [comment]
also this one: 2023-02-01 12:45:01.749 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found

**Comment by LonwoLonwo** [comment]
```java
2023-02-01 13:24:54.072 - [Amazon](500310) Invalid operation: permission denied for schema information_schema;
com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: permission denied for schema information_schema;
	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getBindComplete(Unknown Source)
	at com.amazon.redshift.client.PGClient.handleErrorsScenario1(Unknown Source)
	at com.amazon.redshift.client.PGClient.handleErrors(Unknown Source)
	at com.amazon.redshift.client.PGClient.directExecute(Unknown Source)
	at com.amazon.redshift.client.PGClient.directExecute(Unknown Source)
	at com.amazon.redshift.core.jdbc4.PGJDBC4DatabaseMetaData.setDefaultProperties(Unknown Source)
	at com.amazon.redshift.core.jdbc4.PGJDBC4DatabaseMetaData.<init>(Unknown Source)
	at com.amazon.redshift.core.jdbc4.PGJDBC4ObjectFactory.createDatabaseMetaData(Unknown Source)
	at com.amazon.jdbc.common.SConnection.getMetaData(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.getMetaData(JDBCConnectionImpl.java:334)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:448)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initialize(PostgreDataSource.java:417)
```

Unfortunately, we can't fixed in DBeaver, because this is driver specific. 
Maybe you can add permissions to the information_schema to user and revoke permissions for specific tables/views?

**Comment by nancy506** [comment]
Can you elaborate more on this?  the driver I use is the default driver provided by DBeaver for connecting to Redshift: com.amazon.redshift..jdbc42.Driver and it works fine in my other devices. Why does it cause problem here? Thanks!

**Comment by arhayka** [comment]
Please check that you have similar driver versions in different DBeaver versions. You can see this in Connection settings —> Driver settings —> Libraries.

**Comment by nancy506** [comment]
Thanks Arhayka! I have granted user access to information schema and this problem goes away. Will check the libraries in the future if similar problems occurs

**Comment by benle106** [comment]
Hi everyone, I also got the same issue like that. When I tried to connect to a database using DBeaver on my laptop, It showed me a message like this. However, on my PC, I can connect to database without any problem although I checked all the related drivers on my PC and Laptop, and they are the same versions. I also tried to use a higher driver version on my Laptop, but it didn't work. So is there any reason why it happens on my Laptop?

![Screenshot 2023-03-13 120018](https://user-images.githubusercontent.com/46037949/224612070-4f460306-9ec0-42c4-a3aa-30fd894f02bb.png)

**Comment by LonwoLonwo** [comment]
@benle106 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by benle106** [comment]
@LonwoLonwo 
Here is the log file.
[logfile.txt](https://github.com/dbeaver/dbeaver/files/10966026/logfile.txt)

**Comment by LonwoLonwo** [comment]
Hello @benle106 
You have another database and another issue.
`WARNING: TLSv1 was negotiated. Please update server and client to use TLSv1.2 at minimum.`

Please enable this setting in your connection settings:

![2023-03-14 11_50_05-Créer un nouvelle connexion](https://user-images.githubusercontent.com/45152336/224946636-6ea394b6-20a7-46a0-ba14-71444467c241.png)

If it will not help - provide me your driver version as a screen from the Connection settings -> Driver Settings -> Libraries

**Comment by benle106** [comment]
Hi @LonwoLonwo, 
I have tried it, but it doesn't work for me.

Here is the sreeenshot as you required.
![Screenshot 2023-03-14 160428](https://user-images.githubusercontent.com/46037949/224951159-eb0caefc-990f-4fa0-b328-cd669846eba0.png)

**Comment by LonwoLonwo** [comment]
You can try to change one of these settings (in the Connection Settings -> Driver properties tab)

![2023-03-14 12_20_08-Créer un nouvelle connexion](https://user-images.githubusercontent.com/45152336/224954517-067faf56-ec32-489c-8e85-810c7cb2e597.png)

![2023-03-14 12_20_20-Créer un nouvelle connexion](https://user-images.githubusercontent.com/45152336/224954523-4b35ddc5-04d2-4cfe-800b-5ed0d3b61578.png)

**Comment by LonwoLonwo** [comment]
If it will not help, you can try to downgrade your driver to version 9+ instead of 11+

![2023-03-06 11_39_27-DBeaver 23 0 0 - _postgres 2_ Script-18](https://user-images.githubusercontent.com/45152336/224954765-3adeccd9-8f98-4b82-8ee2-4744abed0b96.png)

**Comment by benle106** [comment]
Thank you very much @LonwoLonwo, that's a good help. I downgrade the driver to version 9.4.1, and I connect to my database successfully. It might be some problems with version 11+ related to JDBC driver, right?

**Comment by LonwoLonwo** [comment]
These are encryption changes in the newest SQL Server driver versions (starting 10 version)

**Comment by E1izabeth** [comment]
Does this issue still actual?

**Comment by E1izabeth** [comment]
It's been a long time since no update here, so I'm closing it.
Let me know, if the issue still actual.
