### ISSUE TITLE
after I created Function ,  I found that at the end of the create source code, there is a line ";"  was auto appended

### ISSUE THREAD

**Issue by djr08** [dbeaver/dbeaver#18939]
### Description

```sql
CREATE OR REPLACE FUNCTION schema.test(intext character varying)
 RETURNS boolean
 LANGUAGE plpgsql
 IMMUTABLE PARALLEL SAFE
AS $function$
BEGIN
    if intext =' ' then
       return TRUE;
    else
       return FALSE;
END;
$function$                                 ⇐　**### this is the end line of the function.**
;                                                 ⇐    ### **after create it ,this line was found.**
```

### DBeaver Version

verson21.2.1.202109181446

### Operating System

windows

### Database and driver

Postgre15.0

**Comment by ShadelessFox** [comment]
Hello @djr08,

Thanks for the bug report.

It seems valid to me. Why do you think this is a bug?

**Comment by djr08** [comment]
> 

Thank you for your reply!

Yes it is vaild to me too, but I think it is different from orignal create sql [without ";"].

**Comment by ShadelessFox** [comment]
DBeaver automatically adds a trailing semicolon because it's a typical statement separator.

It doesn't affect the execution but makes it simpler for CTRL+ENTER scenarios.

**Comment by djr08** [comment]
OK,I will close it, thank you very much!
