### ISSUE TITLE
Parameter defaults for Exasol

### ISSUE THREAD

**Issue by allipatev** [dbeaver/dbeaver#18944]
Some JDBC driver parameter defaults for Exasol are rewritten by the plugin:

```xml
<property name="querytimeout" value="600"/>
<property name="connecttimeout" value="1000"/>
```

Query timeout of 10 minutes fits well for Exasol-only queries, but might be too small if external data sources are involved.

"connecttimeout" is deprecated since version 7.1.11: [Drivers: Unified login timeout parameters](https://exasol.my.site.com/s/article/Changelog-content-14618?language=en_US)

The suggestion is to change querytimeout default to 1 hour (3600) and remove connecttimeout from default rewrites.

**Comment by E1izabeth** [comment]
Thank you for suggestion.
