### ISSUE TITLE
DBeaver 22.3.3 : Cannot add "Db2 for IBM i" connexion, jt400 requirement for driver missing.

### ISSUE THREAD

**Issue by jeanbruder** [dbeaver/dbeaver#18947]
### Description

On a fresh install of DBeaver 22.3.3, when trying to add a new "Db2 for IBM i" connexion, an error appears : "jt400 requirement for driver missing".
![image](https://user-images.githubusercontent.com/72472219/216647870-b5c1df72-81c0-491a-a6ca-5a09108d03df.png)
![image](https://user-images.githubusercontent.com/72472219/216648091-9cfbbee4-6314-47f7-adab-567ba2da6e18.png)

[DBeaver.log.log](https://github.com/dbeaver/dbeaver/files/10580522/DBeaver.log.log)

### DBeaver Version

22.3.3

### Operating System

Windows 10

### Database and driver

db2 for IBM i

### Steps to reproduce

1. Create a new "db2 for IBM i" connexion,
2. Clic "Test connexion",
3. Error appears :
![image](https://user-images.githubusercontent.com/72472219/216648943-c02dfeaa-31bf-47ad-97a0-322d30308ff5.png)

**Comment by LonwoLonwo** [comment]
Hello @jeanbruder 

Unfortunately, I can't reproduce your issue.

You probably can't download the driver because of the firewall or other internet restrictions.

**Comment by LonwoLonwo** [comment]
You can add a driver manually.

![2023-02-03 19_13_41-DBeaver 22 3 4 - _master_ Script-29](https://user-images.githubusercontent.com/45152336/216652336-2663306d-e4e2-4d93-825f-5a0146a5faca.png)

**Comment by jeanbruder** [comment]
@LonwoLonwo I setup my proxy, and it appears that I needed to restart DBeaver in order to use it. After a restart of the software, th driver get installed. Thx
