### ISSUE TITLE
SQL Editor font became very thin in 22.3.4

### ISSUE THREAD

**Issue by d-navikas** [dbeaver/dbeaver#18959]
### Description

After 22.3.4 update font in SQL editor became very thin and hard to read on 4K RDP:
![image](https://user-images.githubusercontent.com/53534711/216940481-e50d7136-daca-4f92-b8b2-a69e3d4d7c0a.png)

... this is wrong scaling on github. 2-3 px line width is not enough for 4K 27 inch.
![image](https://user-images.githubusercontent.com/53534711/216942098-a9906a4a-cdd8-4e9e-8624-daf58d45e54e.png)

### DBeaver Version

Community 22.3.4.202302041940

### Operating System

Windows 11 22H2

### Steps to reproduce

1. Open SQL Editor
2. Type SQL

**Comment by ShadelessFox** [comment]
Hello @d-navikas,

Maybe your font settings were affected by the update?

Can you try changing it in the preferences <kbd>User Interface</kbd> &rArr; <kbd>Appearance</kbd> &rArr; <kbd>Colors and Fonts</kbd> &rArr; <kbd>General</kbd> &rArr; <kbd>Text Font</kbd>?

Please let me know if it helps.

**Comment by d-navikas** [comment]
Hello, @ShadelessFox. It is Courier New 10 regular now, preview seems like what i saw in editor. Can you tell please what font or its settings was default in previous versions?

**Comment by ShadelessFox** [comment]
Mine is Consolas 10 Regular which is the default font according to Eclipse.

**Comment by d-navikas** [comment]
Consolas is much better, thank you! But when i press reset or default font, it changes to Courier New...

**Comment by ShadelessFox** [comment]
I don't know why it's happening, sorry. It could be somehow affected by Windows 11.

I will close the issue for now. If you have any questions, please feel free to ask.

**Comment by rccc** [comment]
Hello, 

I had JetBrains Mono font installed, and after an update, font-family has changed !

I cannot figure out how to select a font-family

**Comment by E1izabeth** [comment]
@rccc you can change it in preferences
![image](https://user-images.githubusercontent.com/28875055/225860429-3c32a0d7-bc1c-4e2a-8847-eb1ca436da8e.png)

**Comment by d-navikas** [comment]
I made fresh install 23.0.5 version and default mono font was Courier New. It seems like a bug or thing needs to tune. That font is awful on high dpi screens.

@ShadelessFox

**Comment by ShadelessFox** [comment]
Actually, I don't think anything needs to be changed from DBeaver side.

You can change the font manually.

**Comment by fernandodms** [comment]
Dbeaver doesn't keep selected font size from session to session.
