### ISSUE TITLE
error an open erd file

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#18955]
### Description

Dbeaver can save ERD file, but not open this

### DBeaver Version

community edition 22.3.4

### Operating System

windows 11 64bit

### Database and driver

Postgresql 14

### Steps to reproduce

1. Open Diagram tab of table
2. Click to Save file in external format. ERD format
3. Open this file with DBeaver
![image](https://user-images.githubusercontent.com/61137576/216894069-4e564ea3-d293-4ecd-8a57-7bdb56eac642.png)

DBeaver can not open this file type?

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by serge-rider** [comment]
I don;t think that we need logs.
The bug is reproducible if you follow the steps above.

**Comment by serge-rider** [comment]
@detkliff thanks fir the bug report.

It will be fixed in the next version
