### ISSUE TITLE
Value Viewer -100 problem

### ISSUE THREAD

**Issue by ygoltrant** [dbeaver/dbeaver#18953]
### Description

Hi,

The new version (on snap, ubuntu) is behaving weirdly in the value viewer.
As you can see on the screenshot, it doesn't display the right value (here id 7637) but the value 100 points below if it exists (here, 7537). If it doesn't exist, it displays nothing.

I've tried the search bar to see if it would be coherent, but hopefully not, it's behaving correctly.

![Screenshot 7637 - 100 = 7537](https://user-images.githubusercontent.com/64099997/216842487-5b29972d-aed1-4305-8755-13c9e3f063e2.png)

### DBeaver Version

Snap dbeaver-ce 22.3.4.202302041940

### Operating System

Ubuntu (snap)

### Database and driver

MySQL 8.0
JDBC I think

**Comment by serge-rider** [comment]
It is a bug in the latest version. Thanks for the bug report.

**Comment by serge-rider** [comment]
Side effect of https://github.com/dbeaver/dbeaver/issues/17242
Reverted

**Comment by uslss** [comment]
verified
