### ISSUE TITLE
SQL Error [1406] [22001] Data truncation: Data too long for column 'iso_code' at row 1

### ISSUE THREAD

**Issue by KC2016** [dbeaver/dbeaver#18969]
### Description

Hi, I'm trying to import datasets from `csv` and `xlxs` files of around  26.4 MB using MySQL in Dbeaver version 22.3.3.202301211053. I have the `SQL Error [1406] [22001] Data truncation: Data too long for column 'iso_code' at row 1`, even though this column is not that long. If I skip all, it imports only the rows with the first group of values in the first column.

### DBeaver Version

22.3.3.202301211053.

### Operating System

Mac Monterey 12.2.1

### Database and driver

MySQL 8.0.23
com.mysql.cj.jdbc.Driver - Driver for MySQL 8 and later
<img width="500" alt="Screenshot 2023-02-06 at 16 15 58" src="https://user-images.githubusercontent.com/18695019/217009956-eea41a5c-aabb-473d-ac3b-ef93f9e8d253.png">

### Steps to reproduce

1- press table
2- import data
3- open the csv or xslx file
4- next (3 times)
5- proceed

**Comment by KC2016** [comment]
I noticed that every column that was FLOAT, was imported as REAL. So, the error happens. I handled it changing the column types, one by one, manually.

**Comment by LonwoLonwo** [comment]
Hello @KC2016 

You can specify your target column's data types during the data import. 

![2023-02-09 13_06_13-Configure metadata structure](https://user-images.githubusercontent.com/45152336/217782182-0a8b7921-05f3-404c-b353-ea02a4de7d4f.png)

Did you try to do it? Choose the optimal type of these columns for your data.

**Comment by E1izabeth** [comment]
It's been a long time since no update on this issue. If it's still actual for you, please let me know and provide additional info.
