### ISSUE TITLE
Cannot start since version 22.3.4_microsoftstore (Wrong JRE PATH)

### ISSUE THREAD

**Issue by DefinedZero** [dbeaver/dbeaver#18960]
### Description

Obviously, this folder shouldn't be here
![Snipaste_2023-02-06_17-58-10](https://user-images.githubusercontent.com/47915226/216943137-61b689d8-b60c-4e47-b02d-60052064223d.png)

### DBeaver Version

Community Edition 22.3.4

### Operating System

Windows 11 Pro

### Steps to reproduce

1. Upgrade to dbeaver 22.3.4 from Microsoft Store
2. Run dbeaver

**Comment by E1izabeth** [comment]
Have you tried reinstalling DBeaver?

**Comment by serge-rider** [comment]
It is a bug in the latest release. We will fix it shortly

**Comment by miguellira** [comment]
@serge-rider Are there any workarounds until a new release is published to the Microsoft Store?

**Comment by serge-rider** [comment]
New release should be available tomorrow.
The workaround is to install java on your machine or to download installer from dbeaver.io.

**Comment by miguellira** [comment]
Thanks @serge-rider. Curiously, I do have java installed on my machine, specifically v17. Is there a specific set of versions that is required to run DBeaver?

**Comment by iamsid** [comment]
On my machine, I can see the file specified in the error, but its in `\jre\jre\bin\javaw.exe` instead of `\jre\bin\javaw.exe`.
Tried moving the folders, but unable to figure out permissions.
Work is halted, need that update soon! Don't want to reinstall as I will loose all DB connections.

**Comment by carlos-garcia** [comment]
atm. there's no release with the fix on the microsoft store. only way that i progressed was instainlling the JDK linked in this github readme.md

https://adoptium.net/

the oracle one is "old".. after installing the openJDK from adoptium dbeaver is working again.

**Comment by twielens** [comment]
Should there be a sub-milestone for this? Hope we won't have to wait till the 3.5 release ;)

**Comment by miguellira** [comment]
@carlos-garcia Can you elaborate a bit? Are you saying you were able to run the Windows Store version of DBeaver simply after installing the latest version of OpenJDK? Did you have any JDK installed previously? Did the installation of the JDK add something to your PATH or update your JAVA_HOME environment variables to get DBeaver to resolve a JVM?

**Comment by carlos-garcia** [comment]
@miguellira yes, basically i installed the openJDK and after it finishes, just ran the DBeaver from windows store without problems

i didnt have any jdk or java installed before

i see this added now that i check env vars:

<img width="384" alt="image" src="https://user-images.githubusercontent.com/1264114/217280334-3a49d264-5c5d-499a-b686-2999835d6325.png">

**Comment by johanson** [comment]
> On my machine, I can see the file specified in the error, but its in `\jre\jre\bin\javaw.exe` instead of `\jre\bin\javaw.exe`. Tried moving the folders, but unable to figure out permissions. Work is halted, need that update soon! Don't want to reinstall as I will loose all DB connections.

You can use regular Windows installer version and import data from the Microsoft Store version folder.

**Comment by miguellira** [comment]
@carlos-garcia Thanks for the quick response and screenshot. Did the installation also create or set a JAVA_HOME environment variable? Curious why/how this workaround works for you. I already had a JDK installed on my machine and even after installing the OpenJDK version I am still unable to run DBeaver.

**Comment by carlos-garcia** [comment]
@miguellira my first straight-thing-to-do was downloading java from oracle.. but they just offer the 1.8 (which triggers the linked issue of requiring java 11) thats why after uninstalling the 1.8 from oracle, found the one in the readme.

i dont see any JAVA_HOME path on my env settings
<img width="126" alt="image" src="https://user-images.githubusercontent.com/1264114/217303224-ff7e94ae-dc08-48c4-b71d-084ca308e1b3.png">

**Comment by miguellira** [comment]
@carlos-garcia Thanks again for the quick response and posting a screenshot of all your environment variable keys. 

Not that it should matter but I'm assuming the previous screenshot of the value of your path environment variable was at the system level - correct?

I've tried mirroring your setup and am unable to launch DBeaver. Really hope that new version gets pushed to the Microsoft Store soon.

@ShadelessFox I know you closed a duplicate issue and stated the workarounds are to download and install the non-Windows Store version or install JRE 11 or greater.

Any idea why installing the Adoptium OpenJDK would work for @carlos-garcia and not for others?

**Comment by miguellira** [comment]
@carlos-garcia What is the output of `java --version` on your machine? Is it similar to this:

![image](https://user-images.githubusercontent.com/1449255/217310472-be6d4fa3-1a1d-4ac1-84c8-a6f741a865ba.png)

**Comment by carlos-garcia** [comment]
weird.. got this..

<img width="740" alt="image" src="https://user-images.githubusercontent.com/1264114/217312953-78557a69-c636-415b-9561-3ddd25855927.png">

**Comment by miguellira** [comment]
@carlos-garcia If you're definitely running the Microsoft Store version of DBeaver and not the download version then you sir are one lucky person. 😄 

Thanks again for sharing your setup.

**Comment by serge-rider** [comment]
Unfortunately we still cannot update the latest version.

Microsoft store is a tricky platform, updates are very slow and fail with weird diagnosis. And there is no tech support.

If the problem will persist we will have to disable app on MS store for some time (until it will be resolved).

**Comment by miguellira** [comment]
@serge-rider That is unfortunate but understandable. Apparently, the install "JRE 11 or greater" workaround worked for at least one individual but doesn't work for me and my peers. Any thoughts as to why the inconsistency? Shouldn't the presence of a JDK be enough to get it to run?

**Comment by miguellira** [comment]
@carlos-garcia Still trying to figure out why your Microsoft Store install of DBeaver works and mine does not.

Can you do me a favor and look in your registry under **Computer\HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft** and see if you have an entry for **Java Runtime Environment** and if so, what is the latest key and its values?

This is what mine looks like; I'm guessing yours is different:

![image](https://user-images.githubusercontent.com/1449255/217384690-d412f5be-19d0-4e57-a4bd-00343768de31.png)

![image](https://user-images.githubusercontent.com/1449255/217384615-e8efcc4d-e375-48ac-a6c8-8620db54bb45.png)

**Comment by jh0rman** [comment]
@serge-rider would it be possible for you to share the .appx from the 22.3.3 release?

**Comment by zhao-wuyan** [comment]
@miguellira 
I created a new registry entry \HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\17
And by switching the current version in the Java Runtime Environment, I was able to open dbeaver
![image](https://user-images.githubusercontent.com/59789646/217423934-af72d59a-22a9-4b80-be2e-24d26ddd52be.png)
![image](https://user-images.githubusercontent.com/59789646/217422076-eea69036-22a0-494b-886e-023f6925b5d9.png)
but java -version will have errors
![image](https://user-images.githubusercontent.com/59789646/217425339-840c5046-3f35-4d61-b9a7-188676ed0088.png)

The error disappeared after I added the system environment variable

![image](https://user-images.githubusercontent.com/59789646/217430945-e6a2c9a7-a798-4d21-b073-9669d197d1b0.png)
![image](https://user-images.githubusercontent.com/59789646/217430995-81441586-6341-4b94-91b1-6c86607373ed.png)

in the path, 1.8 is on top java -version is 1.8 , 17 on top version is 17. So, I have to put 17 on top.

**Comment by tmontes** [comment]
> You can use regular Windows installer version and import data from the Microsoft Store version folder

Trying to help a few colleagues with that... But couldn't figure out where the Microsoft Store version folder is (not mentioned in https://github.com/dbeaver/dbeaver/wiki/Workspace-Location). Any pointers?

Thanks a lot, in advance.

**Comment by tmontes** [comment]
> > You can use regular Windows installer version and import data from the Microsoft Store version folder
> 
> Trying to help a few colleagues with that... But couldn't figure out where the Microsoft Store version folder is (not mentioned in https://github.com/dbeaver/dbeaver/wiki/Workspace-Location). Any pointers?
> 
> Thanks a lot, in advance.

Replying to myself in the hopes that it might be helpful to others... I found the Microsoft Store folder holding DBeaver settings at

`%USERPROFILE%\AppData\Local\Packages\DBeaverCorp.DBeaverCE_*\LocalCache\Roaming\DBeaverData`

Copied the `workspace6` directory from there into the settings location for the just-installed downloadable version and everything seems to work (connections, scripts, etc).

**Comment by ygorigor** [comment]
I installed this JDK https://learn.microsoft.com/en-us/java/openjdk/download
DBeaver from MS Markeplace is opening now.

**Comment by miguellira** [comment]
@zhao-wuyan thank you so much for this.

For anyone who is unable to run after installing a JDK (many of us already had a JDK installed). You may have had a previous installation of Oracle Java and its registry setting is pointing to v1.8 which is causing DBeaver to fail to launch.

As @zhao-wuyan pointed out in his [comment above](https://github.com/dbeaver/dbeaver/issues/18960#issuecomment-1421941031), the fix is to create a new registry key with the version of the JDK you have installed and point the CurrentVersion to that location.

Here is my working setup using Amazon's Corretto's JDK:

![image](https://user-images.githubusercontent.com/1449255/217550971-ef088322-814b-43ec-acbf-64cfe07295b2.png)

![image](https://user-images.githubusercontent.com/1449255/217551045-7c7e2881-c7b0-4b65-ae0c-fdac3338e8ba.png)

**Comment by wisliy** [comment]
> @zhao-wuyan thank you so much for this.
> 
> For anyone who is unable to run after installing a JDK (many of us already had a JDK installed). You may have had a previous installation of Oracle Java and its registry setting is pointing to v1.8 which is causing DBeaver to fail to launch.
> 
> As @zhao-wuyan pointed out in his [comment above](https://github.com/dbeaver/dbeaver/issues/18960#issuecomment-1421941031), the fix is to create a new registry key with the version of the JDK you have installed and point the CurrentVersion to that location.
> 
> Here is my working setup using Amazon's Corretto's JDK:
> 
> ![image](https://user-images.githubusercontent.com/1449255/217550971-ef088322-814b-43ec-acbf-64cfe07295b2.png)
> 
> ![image](https://user-images.githubusercontent.com/1449255/217551045-7c7e2881-c7b0-4b65-ae0c-fdac3338e8ba.png)

Thank you @miguellira, this worked for me.

**Comment by alaa9jo** [comment]
Installing JRE from adoptium did the trick for me

1. Visit https://adoptium.net/
2. Select Other Platforms and Versions
3. Use filters: OS: Windows, Architecture: x64, Package Type:JRE
4. Click on MSI button to download JRE
5. When installing, make sure all options are selected, this is a must

**Comment by Sec-Joe** [comment]
![image](https://user-images.githubusercontent.com/31123200/218747639-4910d713-bc6a-4c8b-a610-a1c8e35f5d7c.png)
No support for Microsoft Store in the future?

**Comment by twielens** [comment]
> ![image](https://user-images.githubusercontent.com/31123200/218747639-4910d713-bc6a-4c8b-a610-a1c8e35f5d7c.png) No support for Microsoft Store in the future?

This is temporarily I hope? I'm dependent on the store for DBeaver.. won't be able to use it otherwise

**Comment by miguellira** [comment]
@twielens I sure hope so. But if you read the [comment](https://github.com/dbeaver/dbeaver/issues/18960#issuecomment-1421179822) @serge-rider made early on in this issue, if it does come back to Microsoft Store it will be awhile.

The registry workaround worked for me and some of my colleagues. Good luck!

**Comment by twielens** [comment]
> @twielens I sure hope so. But if you read the [comment](https://github.com/dbeaver/dbeaver/issues/18960#issuecomment-1421179822) @serge-rider made early on in this issue, if it does come back to Microsoft Store it will be awhile.
> 
> The registry workaround worked for me and some of my colleagues. Good luck!

Yeah, I have a managed laptop, so I can only install software provided by the package manager. So installing a different JDK/JRE is not an option.

**Comment by twielens** [comment]
@serge-rider: Any clue on if DBeaver will be available in the store in the coming weeks? Is there any progress on that? 
(hehe yes, I'm a bit desperate ;-))

**Comment by Sec-Joe** [comment]
> @serge-rider: Any clue on if DBeaver will be available in the store in the coming weeks? Is there any progress on that? (hehe yes, I'm a bit desperate ;-))

@arhayka Yes, same question

**Comment by ChrisMoladin** [comment]
> I installed this JDK https://learn.microsoft.com/en-us/java/openjdk/download DBeaver from MS Markeplace is opening now.

This Works!!
kindly try this before doing any change to your regedit

**Comment by dautomationengineer** [comment]
I noticed the installer had a checked box to 'Include Java' as a component in the installation. I unchecked this since I already had JDK 17 installed. The application launched as it should.
<img width="576" alt="DBeaver installer components" src="https://user-images.githubusercontent.com/126614525/221964216-47056f08-8ef1-4b05-8baa-5e5f4660d1f2.png">


I reckon the version the installer has, which would only be used by the app, and the version already installed on my machine, to be used by any java applet, were with odds with each other. This makes sense since the app can only use one JDK at a time.

So if you already have java jdk and jre installed, uncheck this option. It is not for you. The checkbox is there for workstations that are not already running java.

Oh and I am running JDK 17 
![image](https://user-images.githubusercontent.com/126614525/221965189-074186f0-c77c-48b2-b45e-38e38491219c.png)

Installed from the same link @ChrisMoladin referenced. Thanks Chris.

**Comment by mwnu** [comment]
> 

Unfortunately, after three weeks this bug hasn't been fixed, but fortunately, this works, thanks!

**Comment by serge-rider** [comment]
Eventually we have updated Windows Store version (although certification passed with warnings). 

It should work now. No need to install Java or anything.

**Comment by twielens** [comment]
> Eventually we have updated Windows Store version (although certification passed with warnings).
> 
> It should work now. No need to install Java or anything.

Yes! Thanks a lot! Don't have to rely on a dodgy run 7.3.0 version anymore!
