### ISSUE TITLE
Wrong release date

### ISSUE THREAD

**Issue by Alexchertkov** [dbeaver/dbeaver#18963]
### Description

Release date of 22.3.4 is 06.03.2023 - it's March, but should be 06.02.2023 - February
![Image Pasted at 2023-2-6 15-09](https://user-images.githubusercontent.com/75213790/216969430-6a7b0d49-a988-44b0-9320-67c43d872785.jpg)

![Image Pasted at 2023-2-6 14-59](https://user-images.githubusercontent.com/75213790/216969568-5f19d1ea-0a93-4db9-ae6f-7cbc5ac8caeb.jpg)

### DBeaver Version

22.3.4

### Operating System

Windows 10 22H1

### Steps to reproduce

Open About window, or Check for updates from earlier versions shows wrong release date.

**Comment by serge-rider** [comment]
Thanks for the bugf report.

It is a type in the release config. We already fixed it but we can't fix it in already released product :(
