### ISSUE TITLE
[altibase] table description comment(annotation), data type not appear..

### ISSUE THREAD

**Issue by davidoff2500** [dbeaver/dbeaver#18976]
**Is your feature request related to a problem? Please describe.**
 

1. When I double-click the Altibase table, the description I entered in the description section does not appear, and F or V appears.
The Altibase is added as COMMENT ON when you add a table description, and it would be nice if it was displayed in the description column when you double-click the table.

2. As in MYSQL, it would be nice if I press up and down the column order to automatically generate the script.

3. data type is not appear at table description (altibase)

**Describe the solution you'd like**

**Describe alternatives you've considered**
![ol](https://user-images.githubusercontent.com/68527661/217139854-8bf8a705-509e-42b2-a782-84a4a5af1813.jpg)

**Additional context**

**Comment by LonwoLonwo** [comment]
Hello @davidoff2500 

Please provide more info about your database and driver. Versions.

**Comment by davidoff2500** [comment]
hi..

altibase jdbc driver : 6.5.1.8.3
dbeaver version : 22.3.4

if you want to know anything... i will answer as soon as possible...

thanks..

**Comment by LonwoLonwo** [comment]
We may not have the support of Altibase table comments. I do not see Altibase in our databases list at all. So, if there are any problems, you can see with the comments now in Altibase - they depend on the driver's work. So, if you can write to the Altibase driver's maintainers - you can do that.

**Comment by LonwoLonwo** [comment]
Hello @davidoff2500 

Altibase was added to the list of supported databases. Please check it in the latest DBeaver version: https://dbeaver.io/download/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by davidoff2500** [comment]
Thanks for everything..

Issue has been cleared..
