### ISSUE TITLE
Notifications hard to read

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#18971]
### Discussed in https://github.com/orgs/dbeaver/discussions/18950

<div type='discussions-op-text'>

<sup>Originally posted by **givihuda** February  3, 2023</sup>
Whenever I get a notification, for the last several versions of DBeaver, its colors blend in with text, making it hard to read.

![image](https://user-images.githubusercontent.com/74785256/216688261-2d90c21e-6091-47da-802c-b4b921cc5659.png)

I'm not sure what to do about this.

I'm on macOS Monterey (latest version) and DBeaver 22.3.3. </div>

**Comment by arhayka** [comment]
How we can try to reproduce it:
- enable the Dark theme on mac,
- disable themes in DBeaver.

**Comment by Matvey16** [comment]
Theme of the OS actially doesn't matter. The main step to reproduce is to:
1. Pick Dark theme in DBeaver settings.
2. Disable theming only after it, and then restart

**Comment by givihuda** [comment]
Is there a workaround to this? It's still happening after several updates. I haven't changed the theme ever, but I'm hoping there's something I can do to make the notification pop-ups readable again.

![image](https://user-images.githubusercontent.com/74785256/234895683-42c13bf4-b238-479b-b971-b5d302c8df56.png)

**Comment by flambchap** [comment]
@givihuda You can enable theming in DBeaver as a workaround. To do that, click Window -> Preferences -> User Interface -> Appearance -> Enable theming.
