### ISSUE TITLE
Universal infinity support in real-family columns

### ISSUE THREAD

**Issue by mkgrgis** [dbeaver/dbeaver#18974]
**Is your feature request related to a problem? Please describe.**
For SQLite in `real` columns in data grid there is `∞` value if in "Value" sub-window there is `Inf` literal. But in SQLite there is no special infinity values with `real`-affinity https://github.com/pgspider/sqlite_fdw/pull/57 and usual forms for infinity in other databases is `Infinity` and `-Infinity`. I think data-grid from PostgreSQL, Firebird, Oracle and MariaDB also must show and respect useful form `∞`  for `real`-family columns during viewing.

**Describe alternatives you've considered**
Option "Show original form from DB for special infinity values" in properties of numeric forms in data-grid. By default off, shows `∞` in data-grid.

**Comment by E1izabeth** [comment]
Thank you for the idea.

**Comment by ShadelessFox** [comment]
Hello @mkgrgis,

I'm a bit confused by your request.

Is your request about treating SQLite's string literals as IEEE-754 special values?

**Comment by mkgrgis** [comment]
> Is your request about treating SQLite's string literals as IEEE-754 special values?

Not only, my request is about simple common mechanism for many RDBMS. Only SQLite have special de facto not arithmetically literals with **`text`** affinity.

In SQL:2016 databases such as PostgreSQL, Firebird, Oracle etc. there is normal `double` or `float` values with corresponding literals for ±∞. In different java drivers this literals can have different representation, but data grid representation can be unified to `∞` and `-∞`.

All ±∞ values in different DBs are not unified in representation in DBeaver's data grid now. 

About getting and understanding ±∞ values and its special literals in different DBs please read

- [PostgeSQL](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL)
- Oracle `SELECT 1/0F "∞" FROM DUAL` or `SELECT -1/0F "-∞" FROM DUAL`
- [Firebird](https://stackoverflow.com/questions/66763171/does-firebird-support-infinity-as-float-value)
- DB2 [DECFLOAT](https://www.ibm.com/docs/en/db2/9.7?topic=list-numbers)

etc.

**Comment by ShadelessFox** [comment]
SQLite is a special case, indeed. We can manually transform string literals into IEEE-compliant values.

As for other databases, if their drivers are JDBC-compliant, they would return Java's `Float#POSITIVE_INFINITY`, `Float#NEGATIVE_INFINITY`, or their `Double` counterparts that convert to strings `Infinity` and `-Infinity` respectively. I don't see any issues here.

So you want them to be shown as a symbol `∞`?

**Comment by mkgrgis** [comment]
> So you want them to be shown as a symbol `∞`?

Yes, @ShadelessFox! I saw for SQLite a usefully but partially presentation rule
![изображение](https://user-images.githubusercontent.com/41448637/228311006-c94ea1ac-e46e-4bbb-8e57-05f70bef72a8.png)
and requested for unifying this rule to case insensitive `+Inf` and `-Inf` in SQLite and to Java's `Float#POSITIVE_INFINITY` and `Float#NEGATIVE_INFINITY` for all other RDBMS at all.

**Comment by mkgrgis** [comment]
Reopened,
23.2.4,  SQLite after `INSERT INTO ... (9e999)`. 9e999 or other overflow number is SQLite representation of infinity.
![изображение](https://github.com/dbeaver/dbeaver/assets/41448637/cc9afe83-746f-4952-9062-c70bc16f7acd)

**Comment by E1izabeth** [comment]
@mkgrgis could you create a new issue with this case?

**Comment by E1izabeth** [comment]
As far as I understand it's not exactly the same as the current one. Current one was the feature request of support, while you're showing the bug in grid representation, while value panel correctly shows infinity sign.

**Comment by mkgrgis** [comment]
Thanks, @E1izabeth ! Done.
