### ISSUE TITLE
missing documentation for ChatGPT feature

### ISSUE THREAD

**Issue by jkatnik** [dbeaver/dbeaver#18984]
Hello,

I was intrigued by "ChatGPT integration for smart completion and code generation" in DBeaver 22.3.4 release notes.

I couldn't find any trace of that feature in DBeaver or on the Internet.

Please point me to a document describing how to configure and use it.

Regards
  Jarek

**Comment by E1izabeth** [comment]
It will be done in dbeaver/pro#1405

**Comment by E1izabeth** [comment]
Wiki and video are on the way.

**Comment by Promental** [comment]
![image](https://user-images.githubusercontent.com/46361556/217778692-ac5feab4-946b-4db4-a30a-7e184553fd8d.png)
I wonder what chatgpt itself thinks about this chatGPT?

**Comment by E1izabeth** [comment]
Wiki is here https://dbeaver.com/docs/wiki/OpenAI-SQL-Assistance/

**Comment by charlbury** [comment]
That wiki link goes to a page not found:

<img width="632" alt="Screenshot 2023-02-10 at 17 46 22" src="https://user-images.githubusercontent.com/3824684/218160456-a9d8a275-200b-47cb-a353-4f5c912f0bf6.png">

Did you mean this page:

https://dbeaver.com/2023/02/09/gpt-3-your-ai-assistant-in-dbeaver/

**Comment by E1izabeth** [comment]
Seems it was renamed. Here is the correct link https://dbeaver.com/docs/wiki/AI-Smart-Assistance/

**Comment by antonio-petricca** [comment]
Which information DBeaver sends to ChatGPT? Is it compliant with companies NDA?

**Comment by Anteus** [comment]
Maybe could add an option to set the endpoint to be able to use eg FauxPilot? https://github.com/fauxpilot/fauxpilot
