### ISSUE TITLE
The problem of variables in sql editor

### ISSUE THREAD

**Issue by Animalline** [dbeaver/dbeaver#18982]
### Description

If the sql is very long, there will be replacement errors

### DBeaver Version

DBeaver Community Edition 22.3.4.202302060909

### Operating System

Windows 11 Home Edition

### Database and driver

pgsql 10.5.0

### Steps to reproduce

![屏幕截图 2023-02-07 162521](https://user-images.githubusercontent.com/124666606/217197338-4d00a8ec-9df7-42ae-8d50-c28541314d39.png)
![屏幕截图 2023-02-07 164303](https://user-images.githubusercontent.com/124666606/217197347-3db03889-08bb-4049-b678-759f0554a0a4.png)

**Comment by E1izabeth** [comment]
Could you send me this query as a text?

**Comment by Animalline** [comment]
> Could you send me this query as a text?

Well, only the editor created in this previous version has an error, and the editor created in this version will not report an error

[Script-17.zip](https://github.com/dbeaver/dbeaver/files/10682190/Script-17.zip)

**Comment by E1izabeth** [comment]
Thank you
