### ISSUE TITLE
Variables in Database Tasks Are No Longer Being Passed to Scripts

### ISSUE THREAD

**Issue by garrettw-saic** [dbeaver/dbeaver#18998]
### Description

This worked consistently until quite recently. When using the ${variable} notation within .sql scripts I was able to use the 'Variables' button in the Database Task and pass the value. After updating (however I'm not aware of which version this was introduced) the scripts only see NULL in place of the variables.

### DBeaver Version

Community Edition Version 22.3.4.202302060909

### Database and driver

Tested with Postgres: 
![image](https://user-images.githubusercontent.com/84092611/217343850-bfefde10-a480-4710-9999-0b3bc59b4dc2.png)

Tested with MSSQL:
![image](https://user-images.githubusercontent.com/84092611/217343950-53c95598-0421-4bd7-9ba3-3fa5e5e6dc02.png)

Result is the Same

### Steps to reproduce

Create a Database Task with a Script using a variable

Set Variable in the Task Options 
Database Tasks > Variables >
![image](https://user-images.githubusercontent.com/84092611/217343355-d9e7b7e4-00f1-41e7-a654-367e0980ad08.png)

Error Occurs because NULL is being passed rather than Variable

Query Manager Shows
select * from NULL limit 10

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
As a temporary workaround you can change your task parameters to have variable name in upper case.

**Comment by garrettw-saic** [comment]
Confirmed that using upper case workaround in the task variables fixes the issue for now. This is perfectly fine for our project. Thank you.
