### ISSUE TITLE
I can no longer open a database connection

### ISSUE THREAD

**Issue by plinionaves** [dbeaver/dbeaver#19000]
### Description

After receiving the latest update, I can no longer open a connection to any database in my AWS account. I use VPN to access.

DBeaver completes 50% of the connection process and then stays forever in the "Read database meta data" step until it gives an error.
![image](https://user-images.githubusercontent.com/7607265/217358749-0c5d16c7-44cf-4ad1-bd0e-8d1b1dd61f9b.png)

Before the update everything was working perfectly.

Note: if I try to connect to a database running locally on my machine, it works.

### DBeaver Version

22.3.4

### Operating System

Manjaro (Linux)

### Additional context

I use VPN to connect to my databases on AWS

**Comment by E1izabeth** [comment]
Please send the log files. You can find instructions here https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by plinionaves** [comment]
@E1izabeth 
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10679431/dbeaver-debug.log)

**Comment by E1izabeth** [comment]
Thank you

**Comment by LonwoLonwo** [comment]
Please check - does the DBeaver version downgrading (to 22.3.3) help in your case?

**Comment by plinionaves** [comment]
Hi @LonwoLonwo 
unfortunately not... i just tested it
I even tried to downgrade the posgtres jdbc driver version, without success

**Comment by plinionaves** [comment]
Hi @E1izabeth 

bringing an update, for some reason that I still don't know, I managed to connect with the databases again...

**Comment by E1izabeth** [comment]
Thank you for update. I'm closing this issue. If you encounter this again, please let me know.

**Comment by plinionaves** [comment]
Hi @E1izabeth and @LonwoLonwo 

the problem came back... it came back yesterday but I didn't call here because I wanted to try some possible solutions, but without success... I even reinstalled my operating system thinking it could be because of the last upgrade I received, but it didn't help

I really need to solve the problem because it is delaying me with some work tasks, if you have any possible solution, it would be welcome

**Comment by LonwoLonwo** [comment]
Ok. Can you please send the log file one more time from the DBeaver version 22.3.3?

**Comment by plinionaves** [comment]
Hi @LonwoLonwo 

As I ended up reinstalling my OS, I reinstalled DBeaver via pamac (Manjaro) and the most current version there is 22.3.2.202301092226

Here is the log file for this version:
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10699019/dbeaver-debug.log)

**Comment by plinionaves** [comment]
@LonwoLonwo @E1izabeth 

new update... apparently I managed to solve it for good now, **I had to downgrade openvpn to version 2.5.8-2**

3 days in this fight hehe

what ended up complicating the solution (at least for me), is that it was intermittent: sometimes it worked and after a while it stopped again

finally, for now solved! thank you very much and sorry for the inconvenience

**Comment by E1izabeth** [comment]
Glad to hear the good news. Thank you
