### ISSUE TITLE
Again, can't search in table metadata

### ISSUE THREAD

**Issue by Ra5CZ** [dbeaver/dbeaver#19007]
Same problem again. Again, can't search in table metadata. The table exists, but it cannot be searched. The problem first manifested itself on a brand new DBeaver installation. I have tried reinstalling to versions 22.3.4, 22.3.3, 22.3.2, 22.3.1, 22.3.0 and 22.1.5. But strangely, on the old PC where I am using version 22.3.3, the search works. Even resetting the settings does not help.

New PC with 22.3.4 originally installed and reinstalled on 22.1.5
![image](https://user-images.githubusercontent.com/66022207/217502255-8d03a2c6-bb6d-4456-99f1-e22f49d41f31.png)

Old PC with version 22.3.3
![OldPC-22 3 3](https://user-images.githubusercontent.com/66022207/217502297-b5dea101-0084-4b47-8d8c-a79c3e5d860b.png)

_Originally posted by @Ra5CZ in https://github.com/dbeaver/dbeaver/issues/12527#issuecomment-1422363212_

EDIT:
I'm using MS SQL Server 2022
But on MS SQL 2019 (fresh installation) it also does not work

**Comment by LonwoLonwo** [comment]
Hello @Ra5CZ 

Does the search work for you with this setting?

![2023-02-09 12_25_04-Search](https://user-images.githubusercontent.com/45152336/217771808-f9a7d8b1-05f8-42bc-95a9-d47f5ed1e8e8.png)

![2023-02-09 12_26_26-DBeaver Ultimate 22 3 4 - ServerV](https://user-images.githubusercontent.com/45152336/217771923-2dca9737-8e82-44dc-a3bf-31db27821c04.png)

**Comment by LonwoLonwo** [comment]
Also, Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by Ra5CZ** [comment]
My mistake, I didn't attach a picture of the settings, sorry. I found that when I use the 'Contains' option, everything works as it should. Only the 'Like' option doesn't find some tables.

The setting you mentioned works fine even without 'Case-sensitive', but I prefer the 'Contains' setting. I think the issue can be closed, sorry again for the issue and thank you @LonwoLonwo for trying to resolve the issue.

**Comment by LonwoLonwo** [comment]
Thanks for the investigation @Ra5CZ
