### ISSUE TITLE
Search DB Metadata result window just show one column(Name column)

### ISSUE THREAD

**Issue by doitsexy** [dbeaver/dbeaver#19017]
### Description

Search DB Metadata result window just show one column
I must configure columns then show the comment column

### DBeaver Version

22.3

### Operating System

windows 11

### Database and driver

Oracle 11

**Comment by LonwoLonwo** [comment]
Hello @doitsexy 

Please provide more info about your issue.
Screens, log files, and extra info will be beneficial.

**Comment by E1izabeth** [comment]
It's been a long time since no update on this issue. If it's still actual for you, please let me know and provide additional info.
