### ISSUE TITLE
Spatial viewer - polygon wkt for current canvas extent to clipboard

### ISSUE THREAD

**Issue by Blake-Loveland** [dbeaver/dbeaver#19018]
**Is your feature request related to a problem? Please describe.**
When using the Panels pop out, Value viewer for spatial data, which is great by the way, I often end up needing to see all the other polygons in an area. 

**Describe the solution you'd like**
I would love a very easy way to get the wkt for the polygon that is the extent of the view area any any give time. Basically, I would get the area in the viewer using the +/- and dragging and then click "Copy canvas extent to polygon" or have it show up in a right click menu.

Then I could pretty easily paste the wkt into my sql to just search my table for intersects or contains with that polygon to select any other features near my polygon of interest.

**Describe alternatives you've considered**
The closest option I have now as far as I know is the right click and copy/paste coordinates, for the 4 corners and hand build a polygon wkt for my select statements

**Additional context**
For example, I would love the wkt for the polygon of the below view so I can just easily select all the parcels in the current view as I need to see how they are in relation to the currently displayed multipolygon.

![image](https://user-images.githubusercontent.com/42970073/217736793-6d963a03-6c3e-4857-b4b4-44319a74d81d.png)

**Comment by ShadelessFox** [comment]
Hello @Blake-Loveland,

Thank you for your request.

We can integrate your feature in the form of copying the enclosing bounding box of selected objects on the map.

To make it even more "generic", instead of copying it as `ST_Polygon(...)`, we could copy just the coordinates.

**Comment by Blake-Loveland** [comment]
Thank you very very much for considering my feature request.

I think the view area polygon would be more useful generally.  Often times the polygon is not as large as my example, that was just the on my screen. Often it is more a regular sized polygon but I still need the surrounding polygons to check their attributes. The view port area would be a really good, easy way for folks to just get a general area for the polygon coordinates.

Thank you again for your consideration.

**Comment by Blake-Loveland** [comment]
Thank you very much Serge-Rider and ShadelessFox !!

**Comment by Blake-Loveland** [comment]
Just for completeness and in case someone needs a pointer and finds this issue, below is the sql I use the viewport coordinates with. I just directly copy the coordinates with the newly added menu item and then put them into the coordinates portion of PostGIS `ST_MakeEnvelope()`, nested in a `ST_Contains()` command, but it could be `ST_intersects()` as well of course.

```
SELECT geometry
FROM my_table
WHERE ST_Contains(ST_MakeEnvelope( -70.20482003688814,42.0418511184294,-70.20231485366823,42.04352434133901 ,4326), geometry);
```
