### ISSUE TITLE
java.net.SocketTimeoutException:Connect timed out

### ISSUE THREAD

**Issue by arshad95** [dbeaver/dbeaver#19024]
### Description

Hi,

When i try to open my ORACLE DB i have this message : 

<img width="283" alt="image" src="https://user-images.githubusercontent.com/29165642/217852667-897b3906-47e7-4d7e-93d8-88520e8a9ad5.png">

When i was in DBeaver 7.2.1 it's working fine, now i'm on 22.3.4. Did you know can i fix this issue please ? 

And when i close the pop-up i have another one with this message : 

<img width="547" alt="image" src="https://user-images.githubusercontent.com/29165642/217853208-d145f184-c433-45b7-86c1-53c80dd2c21a.png">

But i have correctly upload the oracle.jdbc.OrcleDriver :

<img width="417" alt="image" src="https://user-images.githubusercontent.com/29165642/217853812-0f0f2668-58de-458b-babd-503391bee04c.png">

### DBeaver Version

22.3.4

### Database and driver

Database - Oracle

**Comment by arshad95** [comment]
And when i close the pop-up i have another one with this message : 

<img width="547" alt="image" src="https://user-images.githubusercontent.com/29165642/217853208-d145f184-c433-45b7-86c1-53c80dd2c21a.png">

**Comment by arshad95** [comment]
But i have correctly upload the oracle.jdbc.OrcleDriver :

<img width="417" alt="image" src="https://user-images.githubusercontent.com/29165642/217853812-0f0f2668-58de-458b-babd-503391bee04c.png">

**Comment by E1izabeth** [comment]
Try deleting all blue items in the list Libraries tab.

**Comment by E1izabeth** [comment]
Please let me know if it helps.

**Comment by arshad95** [comment]
Hi E1izabeth,

Yes it's working thank you
