### ISSUE TITLE
Specifying columns to select causes Columns to be read-only in results grid

### ISSUE THREAD

**Issue by bickgr** [dbeaver/dbeaver#19026]
### Description

When running a query and selecting specific columns, the results grid ends up in read-only mode, the user is unable to edit values in the grid.  Run the query as SELECT * allows the results grid to be editable.  

### DBeaver Version

22.3.4.202302060909

### Operating System

macOS 13.2

### Database and driver

PostgreSQL JDBC Driver

### Steps to reproduce

1. Start a new query 
2. run a SELECT * on any table, for example
SELECT *
FROM "AspNetUsers" anu
ORDER BY anu."UserName"
3. Modify the query to select specific columns and run again, for example
SELECT anu."Id", anu."UserName", anu."PhoneNumber", anu."DateCreated"
FROM "AspNetUsers" anu
ORDER BY anu."UserName"
4. Attempt to edit a column value in the results grid

All columns end up as read-only, the yellow lock icon shows up in top left of results grid.  The error when attempting to edit a column comes back as Column is read-only: No corresponding table column.  

![image](https://user-images.githubusercontent.com/46910221/217909937-bd35437d-73ff-4f67-a06f-e4d66f47b019.png)

### Additional context

Adding as a new bug per request in issue #17724. Also as was requested previously see attached for the DDL from the table shown in example.

[AspNetUsers DDL.txt](https://github.com/dbeaver/dbeaver/files/10700455/AspNetUsers.DDL.txt)

**Comment by E1izabeth** [comment]
Thank you for bug report.
The issue is reproducible only if the column names are in quotes.

**Comment by bickgr** [comment]
But the quotes are necessary, otherwise Postgres will interrupt Id as id, which then causes an Error Column does not exist.  So omitting the quotes only works when working with a table were the column names are using all lowercase, which isn't typically the case in my experience.

**Comment by E1izabeth** [comment]
I know. I just highlights an important point to reproduce the issue.
