### ISSUE TITLE
Mysqldump permission denied 

### ISSUE THREAD

**Issue by tony-sar** [dbeaver/dbeaver#19029]
### Description

trying to backup a mysql database using dbeaver-ce on ubuntu. set local client to /usr/bin , i get 
`Error executing process
  Cannot run program "/usr/bin/mysqldump" (in directory "/usr/bin"): error=13, Permission denied
  Cannot run program "/usr/bin/mysqldump" (in directory "/usr/bin"): error=13, Permission denied
    error=13, Permission denied
    error=13, Permission denied
  `originally installed using snap, but after seeing issue here about snap , i installed dbeaver using dep package downloaded from official site. i still get this issue regardless of configuration . 

### DBeaver Version

22.3.4.202302060909

### Operating System

Ubuntu 

### Database and driver

Mysql server 8

### Steps to reproduce

1. select database. 
2. select tools 
3. dump database 
4. set local home > /usr/bin/

**Comment by calflier** [comment]
Same problem here (on Fedora 35).  Installed dbeaver-ce-22.3.4 at 15:38 today.  Got "Permission denied" on /usr/bin/mysqldump.  Downgraded back to version 22.3.3 at 20:08 ... dump works again.

**Comment by LonwoLonwo** [comment]
Hello

The whole discussion is here: https://github.com/dbeaver/dbeaver/issues/18958

Could you test it in the Early Access version? https://dbeaver.io/files/ea/
