### ISSUE TITLE
Error Insufficient Memory

### ISSUE THREAD

**Issue by SimonDataAnalist** [dbeaver/dbeaver#19021]
### Description

When i run a qeury with een To_date then i get an error:
SQL Error [HY000]: [DataDirect][OpenEdge JDBC Driver][OpenEdge] Insufficient Memory. Memory allocation failed at 1654 in Z:/vobs_sql/sql/src/rds/psr_bld1.cxx. Contact Progress Technical Support

I have een connection by OpenEdge but when i connect true ODBC i get the same error

### DBeaver Version

22.3.4

### Operating System

Windows 10/Windows 11

### Database and driver

OpenEdge or ODBC

### Steps to reproduce

I run a query with a To_Date(<datestring>,'dd-mm-yyyy')

**Comment by arhayka** [comment]
Unfortunately, this isn't a DBeaver issue. Please consult the driver maintainers.
