### ISSUE TITLE
ssh tunnel error 13 after 22.3.4 upgrade

### ISSUE THREAD

**Issue by jaymeyer** [dbeaver/dbeaver#19033]
### Description

running Linux Mint Desktop 20.04
upgrade from CE 22.3.3 to 22.3.4
open existing connection to MySQL with Use SSH Tunnel, Public Key
Test Tunnel button results "error=13, Permission denied  Cannot run program "ssh-keygen":error=13, Permission denied"

downgrade to CE 22.3.3 fixes the problem

### DBeaver Version

CE 22.3.4

### Operating System

Linux Mint 20.04

### Database and driver

MariaDB/MySQL

### Steps to reproduce

1. upgrade from CE 22.3.3 to 22.3.4
2. open existing connection to MySQL with Use SSH Tunnel, Public Key
3. Test Tunnel button results "error=13, Permission denied  Cannot run program "ssh-keygen":error=13, Permission denied"

### Additional context

SSH with Public key, RSA
MariaDB connection to a remote host (not localhost)

**Comment by LonwoLonwo** [comment]
Hello @jaymeyer 

Thanks for the report. 
The original report is here: https://github.com/dbeaver/dbeaver/issues/18958
This bug will be fixed in the next release. For now, you can use the [Early Acces](https://dbeaver.io/files/ea/) version or downgrade to version 22.3.3

**Comment by jaymeyer** [comment]
EA release worked for me, thanks for the quick work on this.
