### ISSUE TITLE
ANTLR-based SQL Parser in DBeaver

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#19031]
We need to add xtext dependencies to our parser package, then describe some part of common grammar and get an object model by this grammar. After that, we need to figure out how to use this parser without xtext editor and write tests. Besides that, we should extend described part of grammar for postgresql to check how it will work for different dialects. Also some tests for dialect-specific grammar are required.

More info about our plans is here https://github.com/dbeaver/pro/wiki/Plans-on-Xtext-based-parser

- [x] add xtext dependencies to our parser package
- [x] describe some part of common grammar and get an object model by this grammar
- [x] figure out how to use this parser without xtext editor
- [ ] write tests
- [ ] extend described part of grammar for postgresql to check how it will work for different dialects
- [ ] add tests for dialect-specific grammar

**_(See updates and new todo in the comment)_**

**Comment by E1izabeth** [comment]
Turns out that Xtext brings a lot of dependencies which we don't want to bring to our cloudbeaver-ce.
We decided to try using ANTLR itself.

**Comment by E1izabeth** [comment]
- [x] add antlr dependencies
- [x] describe some part of common grammar
- [x] check error handling
- [x] check parsing only using part of grammar (for expressions, for example)
- [x] extend described part of grammar for postgresql to check how it will work for different dialects
- [x] create an object model for part of grammar
- [x] create translator from AST to object model
- [x] write tests

**Comment by E1izabeth** [comment]
With ANTLR we can get an object model (context classes), but can't use them to build query and get SQL from object model.

**Comment by E1izabeth** [comment]
Also generated object model is like readonly - we can't change it, it's usable only like accessor.
