### ISSUE TITLE
Tip of the day window too short and not displaying complete tip

### ISSUE THREAD

**Issue by fredatgithub** [dbeaver/dbeaver#19030]
### Description

When I start Dbeaver 22.3.4, I have a tip of the day (which is great, I love it) but the text inside is cut off because the window is too short;
Can you increase the window or add a scrollbar ?
Thank you for this great app, I love it.

### DBeaver Version

Community Edition 22.3.4

### Operating System

Windows 10

### Database and driver

PostgreSQL v14.0
no matter what version you use, the tip of the day is not dependent on the version of driver or database.

### Steps to reproduce

1. start Dbeaver Community Edition 22.3.4 and select different tips of the day until you find a long one.

**Comment by fredatgithub** [comment]
![image](https://user-images.githubusercontent.com/6720055/218044782-36f72cfb-bf1b-4b86-8fb3-1a5eb10de277.png)

**Comment by fredatgithub** [comment]
The sentence is truncated

**Comment by LonwoLonwo** [comment]
Thanks for the report @fredatgithub

**Comment by fredatgithub** [comment]
The problem is fixed. I haven't seen that the window could be increased horizontally and vertically.
