### ISSUE TITLE
SSHj update URL 404 error

### ISSUE THREAD

**Issue by enekochan** [dbeaver/dbeaver#19035]
### Description

When trying to install/update SSHj (as described [here](https://github.com/dbeaver/dbeaver/issues/3917#issuecomment-410616717) to fix an issue with SSH) it doesn't work. This URL returns a 404 error:

https://dbeaver.io/update/sshj/latest

But this URL works fine:

https://dbeaver.io/update/sshj/

### DBeaver Version

Any

**Comment by Destrolaric** [comment]
@enekochan Hi, SSHJ now comes preinstalled with all versions of DBeaver.

**Comment by E1izabeth** [comment]
You can switch it here 
![image](https://user-images.githubusercontent.com/28875055/218133328-94b85162-2def-4a4d-8920-fe266361b874.png)

**Comment by E1izabeth** [comment]
Thanks to pointing out to the issue connected with website. Probably we should remove the entire sshj folder.
Please, let me know whether you managed to solve your issue with ssh.

**Comment by enekochan** [comment]
Thank you both!

@E1izabeth The ssh issue was related to #19033 and I've updated to early access version to fix it.

Should I close the issue then?

**Comment by E1izabeth** [comment]
Thank you for response.
Yes please close the issue then.
