### ISSUE TITLE
Support user-defined keybinding for pinning/unpinning tab

### ISSUE THREAD

**Issue by hawthorne3341** [dbeaver/dbeaver#19046]
Hello,

I think dbeaver is a great tool, and would like to propose a small change that I have already implemented and tested locally and will submit a PR for if the idea is well-received - I use a lot of keybindings which help me work quickly and avoid using the mouse, but I noticed there is no option to introduce a custom key binding for pinning/unpinning the active results tab. It is something I do often, and it is slightly frustrating to have to use a mouse to achieve it.

I couldn't discern a reason that this would be intentionally excluded, and the code I would introduce is very similar to the existing SQLEditorHandlerCloseTab.

I hope you like the idea as well, thank you for the great work that you do.

**Comment by E1izabeth** [comment]
It's a good idea.
Please, let me know if you need help working on this issue.
