### ISSUE TITLE
ResultSet tabs action "close tabs to the left" closes pinned tabs

### ISSUE THREAD

**Issue by nicchristeller** [dbeaver/dbeaver#19049]
### Description

When multiple ResultSet tabs are open, the context menu has several options for closing multiple tabs:
- Close All
- Close All of Same Query
- Close Other Tabs
- Close Tabs to the Left

All of these leave pinned tabs open (as expected) _except for "Close Tabs to the Left"_, which closes pinned tabs.

### DBeaver Version

Community Version 22.3.2.202301060755

### Operating System

MacOS 12.6.2

### Steps to reproduce

1. Execute a query and pin the resultset tab
2. Execute 2 more queries, each in a new tab
3. Open the context menu on the 3rd tab, and select "Close Tabs to the Left"
4. Tabs 1 and 2 will both be closed, even though tab 1 was pinned

**Comment by Fesel1** [comment]
Reproduced on Windows 11
22.3.4.202302041940

**Comment by E1izabeth** [comment]
Thank you for bug report.
