### ISSUE TITLE
External formatter encoding issue

### ISSUE THREAD

**Issue by yesexiaoxiao** [dbeaver/dbeaver#19040]
### Description

Chinese will be garbled when calling external formatter.
The external program I use is SQLinFormDesktop.

### DBeaver Version

22.3.4

### Operating System

Win10

### Database and driver

MSSQL

### Steps to reproduce

https://www.sqlinform.com/npp-plugin-help-general-options/
Setting: "C:\SQLinFormDesktop\cli.exe" -dbeaver ${file}

**Comment by Destrolaric** [comment]
@yesexiaoxiao, Hi, could you provide a screenshot showing the issue?

**Comment by yesexiaoxiao** [comment]
![image](https://user-images.githubusercontent.com/38522822/219543545-c036882b-30df-4cef-9ee2-5caf4e783f2a.png)
![image](https://user-images.githubusercontent.com/38522822/219543618-74455707-1480-4f51-b2e5-6768f411a6c5.png)
![image](https://user-images.githubusercontent.com/38522822/219543673-1116646e-b521-451b-bf10-bf6faa1ea56e.png)

**Comment by Destrolaric** [comment]
@yesexiaoxiao Confirmed, Thank you for your report.

**Comment by ShadelessFox** [comment]
Hello @yesexiaoxiao,

Is the issue still present in the latest version of DBeaver? I'm unable to reproduce it.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know.
