### ISSUE TITLE
Microseconds epoch transformer

### ISSUE THREAD

**Issue by BobrPetr** [dbeaver/dbeaver#19043]
When working with databases, I often encounter epoch in microsecond format.  
Previously (in version 7.3.3) there was a transformer that correctly handled these values, but it disappeared in subsequent versions. 
 Please add it again.  
The date format is something like this yyyy.MM.dd HH:mm:ss:nnnnnn

**Comment by E1izabeth** [comment]
Could you give me an example of what are you trying to do and what exactly doesn't work. It would be nice if you could provide some ddl, for example, with create table, insert into and select statements.
I can observe such values with nanoseconds in my data, so we need some example case to understand your needs.

Also please specify what database do you use.

**Comment by BobrPetr** [comment]
PostgreSQL
![Screenshot_20230215_120401](https://user-images.githubusercontent.com/22797528/218862673-5367bf47-341e-4c02-ac53-c0a1079822e4.png)
1676374989617150 ok result: Tue Feb 14 2023 11:43:09 GMT+0000
![Screenshot_20230215_120511](https://user-images.githubusercontent.com/22797528/218862973-243e981e-4a1f-4cf8-b60c-4c3dc102b3f1.png)
none of the current formats gives the correct result

**Comment by BobrPetr** [comment]
I already made a commit that corrects this problem but I can't push it to the repository

**Comment by E1izabeth** [comment]
Please see this guide https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code

**Comment by BobrPetr** [comment]
push 403 error
file with my patch
[my-patch.txt](https://github.com/dbeaver/dbeaver/files/10737604/my-patch.txt)

**Comment by BobrPetr** [comment]
https://github.com/dbeaver/dbeaver/pull/19068

**Comment by BobrPetr** [comment]
how can I transfer the corrected plugin to the current release on my machine?
i use windows ubuntu snap packages
when copying directly to Windows, the program does not start

**Comment by E1izabeth** [comment]
You can't merge it to the already built current release, but you can built the app from sources using maven. For example, with `mvn verify`
