### ISSUE TITLE
PostgreSQL - Backup tool - Keep the filename extension in the pattern between two uses

### ISSUE THREAD

**Issue by bazmap** [dbeaver/dbeaver#19054]
When you use the backup tool on a PostgreSQL database, the pattern used for naming the file dump is kept between two uses of the tool.

But the filename extension isn't... 😢 

For example :
I set the filename field to `$schema_$table.custom`
When I'm using the tool at another time, the filename field is set to `$schema_$table`

This is really anoying because the restoring tool is preset on the `.custom` extension name.

![2023-02-13_20-43-50](https://user-images.githubusercontent.com/8897724/218558642-60a80729-df9a-4343-a046-dd66431ba0fd.jpg)

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by liborpansky** [comment]
Yes please! :pray: Also the `Output folder pattern` should remember the extension: When I perform a restore, the `*.backup` extension is applied as default, but when I perform a backup and add `.backup`, it's never set and I have to write it over and over again.
