### ISSUE TITLE
[Improvement] All object search in tree view instead of just table or views

### ISSUE THREAD

**Issue by yevon** [dbeaver/dbeaver#1905]
This search box is very useful when you have lots of tables or views, but it can be even better.
It would be nice that this search box filters all visible content in tree view, including packages, synonyms etc etc.

![image](https://user-images.githubusercontent.com/121157/28453448-bc1c829c-6df7-11e7-9f59-23dce51ddc71.png)

**Comment by serge-rider** [comment]
Agreed. I can add some additional control which will define what object types to filter.

**Comment by jcrben** [comment]
Why limit it to visible content? I want to be able to search all columns, keys, and so on.

**Comment by uslss** [comment]
already implemented
![image](https://user-images.githubusercontent.com/31996417/151170066-a671b8ab-74cc-4be3-8a68-02c9a29067c5.png)

**Comment by yevon** [comment]
Working fine now
