### ISSUE TITLE
The bottom of the application window obscures the last line of the query

### ISSUE THREAD

**Issue by oomnpe** [dbeaver/dbeaver#19050]
The bottom of the application window obscures the last line of the query.

Linux Ubuntu 22.04
DBeaver Версия 22.3.4.202302041940

![image](https://user-images.githubusercontent.com/59779596/218466389-1e0650fe-6c8e-4a78-ba70-7f4be0d42ef5.png)

**Comment by E1izabeth** [comment]
Thank you for bug report.
Closing as a duplicate of #16875
