### ISSUE TITLE
Exceeding mx context length when attempting to use Salesforce ODBC connection

### ISSUE THREAD

**Issue by gmiller-huseby** [dbeaver/dbeaver#19063]
### Description

I've been using the DevArt Salesforce ODBC connector for several months. Just installed DBeaver 22.3.4 and added the ChatGPT extension. 

I opened the ChatGP window and entered this natural language "query":

contacts where RB8_ContactId__c is not null and not 0

The "loading child objects" window displayed for a few minutes, then the following error message was displayed. If I try to do the same thing again, same error message comes up (more quickly this time).  May be related to the fact that the SF data model has a huge number of tables/fields?

GTP completion error:
{
  "error": {
    "message": "This model's maximum context length is 8001 tokens, however you requested 19200 tokens (18200 in your prompt; 1000 for the completion). Please reduce your prompt; or completion length.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

### DBeaver Version

Community Edition 22.3.4

### Operating System

Windows Pro 10

### Database and driver

Salesforce Spring '23 version
DevArt ODBC for Salesforce 2.2.1 64-bit

### Steps to reproduce

1. Open DBeaver
2. Click existing (blank) query attached to Salesforce database
3. Click ChatGPT icon on left side of query window
4. Enter this "text in a human language" in the GPT-3 smart completion window: contacts where RB8_ContactId__c is not null and not 0
5. Click Translate
6. (First time) Loading child objects window appears
7. Error message appears

**Comment by Destrolaric** [comment]
@gmiller-huseby Hi, it looks like your schema has a lot of tables GPT has a limit for the maximum amount of words in the request, so it's recommended to limit the number of tables by setting `Maximum input tables` to a lower value
![image](https://user-images.githubusercontent.com/20579256/219390509-8dbdb6d6-7c28-4262-a60b-23646cf8a403.png)

**Comment by gmiller-huseby** [comment]
Thanks. Lowering input tables to 50 made it work. Much appreciated!

**Comment by Destrolaric** [comment]
Glad that helped, closing the issue.

**Comment by MrdotZ2017** [comment]
> @gmiller-huseby Hi, it looks like your schema has a lot of tables GPT has a limit for the maximum amount of words in the request, so it's recommended to limit the number of tables by setting `Maximum input tables` to a lower value
> @gmiller-huseby 你好，看起来你的模式有很多表 GPT 对请求中的最大字数有限制，所以建议通过将 `Maximum input tables` 设置为较低的值来限制表的数量
> 
> ![image](https://user-images.githubusercontent.com/20579256/219390509-8dbdb6d6-7c28-4262-a60b-23646cf8a403.png)

macOS 23.0.2为什么没有这个设置项？
<img width="682" alt="image" src="https://user-images.githubusercontent.com/32029270/231327868-82906b85-6d75-495b-bba8-7e896fd31220.png">
