### ISSUE TITLE
Not getting values shown in Results window when using Open With Excel feature

### ISSUE THREAD

**Issue by ginevra12** [dbeaver/dbeaver#19064]
### Description

When I run a query and get results, I use the Open With Excel feature.  When i view the results in Excel, I am getting different values than what was in the Results Window.  And if I use the Open With Excel feature again on the same exact table in the Results window, i still get incorrect values, but a different set of incorrect values.  This is obviously very concerning. 

### DBeaver Version

Community 22.3.4 (current version)

### Operating System

Windows 10 Enterprise

### Steps to reproduce

1. I connect to a database
2. I run a query that I created
3. I right click on the results and press on Open With Excel
4. I compare the results to what's in Excel and they don't match

### Additional context

Since I am using the Community edition, I have to install the Office extension every time there is an update to Dbeaver.

**Comment by LonwoLonwo** [comment]
Hello @ginevra12 

It is not clear - what is the difference between representations? Please, provide examples.

**Comment by ginevra12** [comment]
I can give a simple example.  Let's say my output was one column of numbers and they were 1, 2, 3, 4.   When i right clicked on the output and used Open With Excel, and the Excel spreadsheet opened with the column of values, I would not always get 1,2,3, 4.  I would get random output.  Here is one more thing we just discovered after I posted the issue that may focus the what's going on, or muddy the waters :)....If I include an order by statement in my query and then use the Open With Excel feature, the results in Excel will match the results shown in Dbeaver.   So again, if I don't use the order by statement, I was sometimes getting wrong results in Excel.  If I do use the order by statement, I was getting correct results in Excel.

**Comment by ginevra12** [comment]
My apologies, In my original post, in the steps to recreate section, #4 was incomplete.  I updated it to say the following...
"4. I compare the results to what's in Excel and they don't match"

Some more information as I've looked into this further.  My query had the limit function in it where I limited the query to pull only 1,000 rows.   I bring that up just in case it's the limit function that may be part of the issue.

**Comment by LonwoLonwo** [comment]
Ok. Were you able to use the Export to XLSX file? Does the result also have a difference from the table?

**Comment by ginevra12** [comment]
Yes, I was able to use the Export wizard and got different results in Excel from what was shown in the results window.

**Comment by ginevra12** [comment]
After more investigating, it appears that the issue may be isolated to the following:
1.	It happens on columnstore tables that have significant numbers of obs (e.g., > 50M) AND
2.	“Order by” statement is not used

I did NOT get a different results (between what was shown in the Results window and what was put into Excel via the Open With Excel feature) when I did the following…
1.	Ran the query against the innodb version of the same large tables.
2.	Ran a similar query against a column store table that had < 200K obs.

Here’s a made-up example…

Table name:  sample_data
Field in table:  names
Number of obs in table:  80M
Table exists in columnstore and innodb

If I run the query shown below against the columnstore version of the table, and put the results into Excel via Open With Excel, I get different values than what’s shown in the Results window in the IDE.
If I run the query shown below against the innodb version of the table, and put the results into Excel via Open With Excel, I get the same values as what’s shown in the Results window in the IDE.
SELECT names
FROM sample_data
LIMIT 1000
;

If I run the query shown below against the columnstore version of the table, and put the results into Excel via Open With Excel, I get the same results as what’s shown in the Results window in the IDE (notice that the difference between this query and the one above is the addition of the “Order by" statement:
SELECT names
FROM sample_data
Order by  names
LIMIT 1000
;

My expectation is that whatever I see in the Results window in the IDE should show up in Excel with the same values and in the same order.
Thank you for your help.

**Comment by Matvey16** [comment]
The results shown in excel is based not on results shown in dbeaver, but are taken from results of running the query again. It seems that your table doesn't have an index so the results may vary in evere query. Would you get the same result if you use `SORT BY` clause?

**Comment by ginevra12** [comment]
My apologies for not responding sooner.

I'm just double-checking here because initially I had a whole other response until I reread your comments  :) ...
Are you saying that the Open With Excel feature is actually rerunning the query instead of taking the values in the results window and putting them into Excel?    So, if I run a query, and get results, then use the Open With Excel feature, it's actually re-running the query?   

I forgot to answer your question...as previously stated, when I use an "order by" clause, I always get the same results.  I am just used to using PL SQL Developer for many years and never had to use an order by clause when just querying a subset of a table (i.e., using pl sql's rownum statement instead of mysql's limit statement).  

Okay, I think I've edited my comments enough, so I'll await your response.  :)
If it helps to discuss this issue via a phone call, I'd welcome it.

Thanks!

Thanks!

**Comment by E1izabeth** [comment]
We rerun the query if not all data was fetched. So, it works as expected.

**Comment by ginevra12** [comment]
Thanks Elizabeth.  I appreciate the response/clarification.   Have a great day!  :)
