### ISSUE TITLE
Label drop-down option question

### ISSUE THREAD

**Issue by liuchengss** [dbeaver/dbeaver#19069]
### Description

 Right mouse click on the TAB to display “关闭关闭”

### DBeaver Version

22.3.4

### Operating System

Window10

**Comment by E1izabeth** [comment]
Please, clarify your request.
Which TAB are you talking about?

**Comment by E1izabeth** [comment]
Thank you for bug report.
It's a duplicate of #17697 so I'm closing this issue.
