### ISSUE TITLE
dbeaver not showing up in the microsoft store

### ISSUE THREAD

**Issue by RicardCF84** [dbeaver/dbeaver#19065]
### Description

Hi

Approximately until 2/10/23 the software appears in the store and we could install it without problem.

Today 2/14/2023 we detected that it does not appear in the Microsoft store.

We know if this deployment method is going to be included or discarded.

Regards

### DBeaver Version

ALL

### Operating System

Windows

**Comment by E1izabeth** [comment]
We no longer distribute DBeaver via Microsoft Store.
