### ISSUE TITLE
Snap Dbeaver  - TLS 1.0 and TLS 1.1 support

### ISSUE THREAD

**Issue by nyn0x** [dbeaver/dbeaver#19071]
### Description

Hello,

Connection to SQL server is no longer working
cf: https://github.com/dbeaver/dbeaver/issues/12668

With snap dbeaver we can't modify java.security because it's read-only file (/snap/dbeaver-ce/current/usr/share/dbeaver-ce/jre/conf/security/java.security)

![image](https://user-images.githubusercontent.com/13479932/219012788-c18c7b9c-b75d-486d-b84a-706b0c7a2097.png)

### DBeaver Version

Community Edition 22.3.4

### Operating System

Ubuntu 20.04.5 LTS

### Database and driver

1. SQL Server
2. Microsoft JDBC Driver for SQL Server (MSSQL)

**Comment by Destrolaric** [comment]
@nyn0x Hi, we removed TLS 1.1 and TLS 1.0 from restricted protocols in the EA version. Could you try to use it? 
https://dbeaver.io/files/ea/

**Comment by nyn0x** [comment]
> @nyn0x Hi, we removed TLS 1.1 and TLS 1.0 from restricted protocols in the EA version. Could you try to use it? https://dbeaver.io/files/ea/

It works fine :+1:

**Comment by Destrolaric** [comment]
Closing as already fixed, the fix is available in the EA and will be available in the next DBeaver version.
