### ISSUE TITLE
Windows authentication from linux

### ISSUE THREAD

**Issue by s-nt-s** [dbeaver/dbeaver#19079]
### Description

I am using:

* Debian GNU/Linux 11
* dbeaver Community Edition 22.3.0

And I am trying to connect to Microsoft SQL Server 2017 using Windows authentication

![Captura de pantalla_2023-02-16_09-56-00](https://user-images.githubusercontent.com/5998601/219316750-0ebf6ca4-fc56-423b-b7b3-23b312f7d43b.png)

But I allays get this error:

```
This driver is not configured for integrated authentication. ClientConnectionId:f159b733-7a07-4c03-983e-803e9fbd7a33
  no mssql-jdbc_auth-9.2.0.x64 in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
  no mssql-jdbc_auth-9.2.0.x64 in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
```

How can I use windows authentication from linux?

Also, I see I don't have `com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE` but I don't know how get it.

![Captura de pantalla_2023-02-16_10-34-54](https://user-images.githubusercontent.com/5998601/219326419-c2b25f8e-7ab8-4935-988b-809b4421660b.png)

![Captura de pantalla_2023-02-16_10-37-55](https://user-images.githubusercontent.com/5998601/219327123-90bcdb25-e973-40b5-ab56-5906f21d69b0.png)

`~/.local/share/DBeaverData/drivers/maven/maven-central/com.microsoft.sqlserver/mssql-jdbc_auth-9.2.0.x64.dll` dosen't exist

```
$ ls ~/.local/share/DBeaverData/drivers/maven/maven-central/com.microsoft.sqlserver/
mssql-jdbc-9.2.0.jre8.jar
mssql-jdbc-9.2.0.jre8.pom
mssql-jdbc_auth-9.2.0.x64.pom
```

Should I have mssql-jdbc_auth-9.2.0.x64.dll? Can a dll work in linux?

### DBeaver Version

Community Edition 22.3.0

### Operating System

Debian GNU/Linux 11

### Database and driver

1. Database: Microsoft SQL Server 2017
2. Driver: MS SQL Server / SQL Server = com.microsoft.sqlserver.jdbc.SQLServerDriver (com.microsoft.sqlserver:mssql-jdbc 9.2.0.jre8)

**Comment by LonwoLonwo** [comment]
Hello @s-nt-s 

You can download the SQL Server driver manually from the site: https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc
Or you can wait till DBeaver 22.3.5 release on Monday - we updated the default driver version in DBeaver to version 11.2.3

**Comment by s-nt-s** [comment]
Hello @LonwoLonwo I have installed DBeaver 22.3.5 but I have the same problem.

```
$ wget https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
$ sudo dpkg -i dbeaver-ce_latest_amd64.deb
```

```
This driver is not configured for integrated authentication. ClientConnectionId:5e5a576d-3215-48ce-b94b-5397d28498fe
  Unable to load authentication DLL mssql-jdbc_auth-11.2.3.x64
  Unable to load authentication DLL mssql-jdbc_auth-11.2.3.x64
```

So I did that:

```
$ wget https://github.com/microsoft/mssql-jdbc/releases/download/v11.2.3/mssql-jdbc_auth.zip
$ unzip mssql-jdbc_auth.zip
$ cp x64/mssql-jdbc_auth-11.2.3.x64.dll ~/.local/share/DBeaverData/drivers/maven/maven-central/com.microsoft.sqlserver/mssql-jdbc_auth-11.2.3.x64.dll
```

And I get same error:

```
This driver is not configured for integrated authentication. ClientConnectionId:8c3b0919-25bc-4085-8149-ec3032b4802d
  Unable to load authentication DLL mssql-jdbc_auth-11.2.3.x64
  Unable to load authentication DLL mssql-jdbc_auth-11.2.3.x64
```

**Comment by Destrolaric** [comment]
@s-nt-s Hi, I have looked closer, yes as you mentioned .dll is Windows native, unfortunately Windows authentication is not possible through this, you can look how it can be done in https://github.com/dbeaver/dbeaver/issues/3320
