### ISSUE TITLE
@set commands don't resolve variables in v22.3.4

### ISSUE THREAD

**Issue by knwpsk** [dbeaver/dbeaver#19076]
### Description

Starting (I think) with version 22.3.4, @set commands don't properly resolve and apply variables. This worked as late as version 22.2.3. It did not work in 22.**3**.3, but was even "more broken" in that version than in 22.3.4, so clearly something relevant changed in the latest release.

Example: If I run this script:
**@set t = _20230215
@set o = Order${t}
select ${o};**

I expect the output to be:
**Order_20230215**

But in v22.3.4, the output is:
**Order**

(I regressed to version 22.3.3, and the output for the same script is
**NULL**
(It doesn't run the @set commands at all?)

--

This is important functionality to me because I load order data into a new table each day (due to large data sets). For my queries to work dynamically across all of those tables, I need to set the date dynamically using the "t" variable.

### DBeaver Version

22.3.4

### Operating System

windows 64 bit

### Database and driver

any db

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
As a temporary workaround you can modify the variable name used in the value part of `@set` command like that
```
@set t = _20230215
@set o = Order${T}
```

**Comment by knwpsk** [comment]
Thanks @E1izabeth !

I tried your suggestion on the older version (22.2.3) and it does work, so the variable resolution is apparently case-insensitive there. 

I'm OK sticking with this old version til the bug is fixed. But if you need me to upgrade and test it, I will be happy to do so.
