### ISSUE TITLE
Default Dremio JDBC driver Update

### ISSUE THREAD

**Issue by AndyHunt66** [dbeaver/dbeaver#19088]
### Description

The current default Dremio JDBC driver URL points to 
https://download.dremio.com/jdbc-driver/3.0.6-201812082352540436-1f684f9/dremio-jdbc-driver-3.0.6-201812082352540436-1f684f9.jar

but this is very old 4 or 5 years) and lots of things break with the newer versions of Dremio.

Can you please update the link that downloads the default driver for Dremio to something like the v24 driver?
E.g. 
https://download.dremio.com/jdbc-driver/24.0.0-202302100528110223-3a169b7c/dremio-jdbc-driver-24.0.0-202302100528110223-3a169b7c.jar

### DBeaver Version

Community 22.3.3.202301211053

### Operating System

Linux

### Database and driver

As above
DB : Dremio
Driver : Default should be change to 
https://download.dremio.com/jdbc-driver/24.0.0-202302100528110223-3a169b7c/dremio-jdbc-driver-24.0.0-202302100528110223-3a169b7c

### Steps to reproduce

- Create new connection to Dremio
- Click "Driver Properties" tab
- "Driver Settings" pop up pops up.

Note the URL for "Files required by the driver : "

Observed behaviour:
URL is :
https://download.dremio.com/jdbc-driver/3.0.6-201812082352540436-1f684f9/dremio-jdbc-driver-3.0.6-201812082352540436-1f684f9.jar

Expected behaviour:
URL is 
https://download.dremio.com/jdbc-driver/24.0.0-202302100528110223-3a169b7c/dremio-jdbc-driver-24.0.0-202302100528110223-3a169b7c.j

### Additional context

Note this is **not** the same as changing to Arrow flight driver as per [15535](https://github.com/dbeaver/dbeaver/issues/15535)

**Comment by LonwoLonwo** [comment]
Thanks for the idea @AndyHunt66

**Comment by LonwoLonwo** [comment]
Can you please check - does this driver version
https://download.dremio.com/jdbc-driver/24.0.0-202302100528110223-3a169b7c/dremio-jdbc-driver-24.0.0-202302100528110223-3a169b7c.jar
works fine for you in the latest DBeaver version?

We do not have a Dremio database environment to check from our side.

**Comment by AndyHunt66** [comment]
Yep - I can confirm that that driver works just fine with DBeaver 22.3.5.202302171528 and Dremio 24.0.0
