### ISSUE TITLE
"Cancel running queries" popup alert message is malformed

### ISSUE THREAD

**Issue by brankoradovanovic-mcom** [dbeaver/dbeaver#19089]
### Description

When attempting to close an SQL script tab with a running query, a malformed alert message is displayed ('There are `"<missing argument>"` running SQL queries in this editor.')

### DBeaver Version

CE 22.3.4

### Operating System

Windows 10 x64

### Database and driver

Postgres 13.4, JDBC driver 42.5.0

### Steps to reproduce

1. Open a new SQL tab
2. In the new tab, start a long-running query
3. Try to close the tab by clicking on the "x"
4. The following popup window is displayed:

![image](https://user-images.githubusercontent.com/101108585/219430925-0fadff0c-6700-4995-8828-e0d8976d39e0.png)

`"<missing argument>"` is apparently a placeholder for the actual figure, expected to be 1 in this particular case.

**Comment by E1izabeth** [comment]
Thank you for bug report.
