### ISSUE TITLE
SQL Developer connections import - can't parse url

### ISSUE THREAD

**Issue by MrThibal** [dbeaver/dbeaver#19095]
### Description

Connections import from SQL Develop doesn't work for TNS connections.
"Can't parse URL" error occurs :
<img width="280" alt="dbeaver-error-parse" src="https://user-images.githubusercontent.com/125679803/219706932-1aaa5848-3cd7-4c5f-9942-de1eed77ed8a.png">

### DBeaver Version

Community Edition 22.3.4

### Operating System

Microsoft Windows 10 Entreprise 2016 LTSB

### Database and driver

Oracle 19c

### Steps to reproduce

1. Create a TNS connection in SQL Developer
<img width="269" alt="tns-sqldeveloper" src="https://user-images.githubusercontent.com/125679803/219708181-5d14fd9c-1889-435c-8af3-ced4f712db04.png">
2. Import the connection with "File > Import > Third Party Configuration > Oracle SQL Developer"

**Comment by E1izabeth** [comment]
Thanks to @arons (https://github.com/dbeaver/dbeaver/pull/18421) we improved it in 22.3.5. Hope this issue will be solved in the next release. Could you check 22.3.5 release in a few days (when we publish it on 02.20) and let me know if it was solved for you?

**Comment by MrThibal** [comment]
With the 22.3.5 version, there are no more "can't parse url" errors but the TNS "Network Alias" is not set in my case. I've got the default/first value.
Should I open a new issue ?

**Comment by E1izabeth** [comment]
Yes, please close this issue and create a new one about tns network alias.
