### ISSUE TITLE
 Improvements to the "Toggle results sort order" command execution

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#19091]
### Description

When the "Toggle results sort order" command is executed, sorting in ascending order and default settings are repeated.

According to the description, ascending, descending, and default values ​​are executed sequentially.
I don't remember the dbeaver version, but it worked normally in the old version.

It was confirmed that the 22.2.0 version works normally.

![image](https://user-images.githubusercontent.com/59002295/219550396-e6a7d0df-73ba-48a2-b3cb-b72410db894a.png)

Thank for Reading. :)

### DBeaver Version

Community Edition 22.3.1

### Operating System

Windows 10

**Comment by E1izabeth** [comment]
I can't reproduce it. Could you try 22.3.5 version and if the issue still exists please record a video showing how does it incorrectly work for you?

**Comment by podoni** [comment]
@E1izabeth  

When I execute it on version 22.3.5, it execute normally.
Thnak for Reply.

**Comment by E1izabeth** [comment]
Thanks for update.
