### ISSUE TITLE
Convertion DateTimeOffset to DateTime in exporting

### ISSUE THREAD

**Issue by simon-spier0** [dbeaver/dbeaver#19101]
### Description

Hi,

When I want to export MSSQL table to MySQL database it works great. However conversion of **datetimeoffset** (MSSQL) to **datetime** (MySQL) doesn't work well.

DateTimeOffset is Microsoft special type in format '2023-02-18 16:07:05.998488 +00:00' - there is even timezone. So while exporting it to datetime in format '2023-02-18 16:07:05.998488' it throws error:
**Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]**

Could you please fix it?
Thanks.

### DBeaver Version

CE 22.3.3

### Operating System

Windows 10

**Comment by Destrolaric** [comment]
It looks like this issue happens due to datetimeoffset being recognized as a string, and the timezone part couldn't be parsed for datetime. Maybe we need some additional functionality to handle that.
