### ISSUE TITLE
data import

### ISSUE THREAD

**Issue by sfzsjx** [dbeaver/dbeaver#19108]
### Description

将一张带有自增id表导入另一个库中，发现表的最大id没有改变，插入数据报主键冲突

Import a table with an auto-increment id into another library, and find that the maximum id of the table has not changed, and the primary key of the inserted datagram conflicts

### DBeaver Version

Community Edition 21.1.3

**Comment by E1izabeth** [comment]
Could you clarify what do you mean by "import a table into another library"? Do you mean to import table to another database?

**Comment by sfzsjx** [comment]
Yes, I solved it in the following way：

SELECT setval('"SAMS_SYS_AREA_id_seq"', (SELECT MAX(id) FROM "SAMS_SYS_AREA")+1)

**Comment by E1izabeth** [comment]
Could you provide us steps to reproduce?

**Comment by E1izabeth** [comment]
It's been a long time since no update here. If it's still actual for you, please let me know and provide additional info.
