### ISSUE TITLE
Problem with Sql Trasformation 

### ISSUE THREAD

**Issue by biggio78** [dbeaver/dbeaver#19109]
### Description

I try to execute this script pg/sql with one parameter 
------------
"SELECT *"+
"FROM   pg_settings pg"+
" WHERE  pg.source = :desc;"
------
When paste the code the conversion is done but when execution the script, it return this error 
-------
Errore SQL [42601]: ERROR: syntax error at or near "sc"
  Posizione: 61
--------
With the version community edition 22.3.2,  the same script run correctly.

### DBeaver Version

Community edition  22.3.5 (20.03.2023)

### Operating System

windows 10 64 bit

### Database and driver

PostgreSQL 11.12

### Steps to reproduce

1) open dbveaver
2) connect with db 
3) open new script 
4) copy and past the script to trasformate
5) execute the script

**Comment by E1izabeth** [comment]
Hi, @biggio78 
Could you show me what query do you see in Query Manager when execute it? You can find instructions of how to use Query Manager here https://dbeaver.com/docs/wiki/Query-Manager/

**Comment by E1izabeth** [comment]
Never mind. I reproduced the issue. It is happening because of \r only instead of \r\n at the end of the query.

**Comment by biggio78** [comment]
here the result after insert the value ('default') of the parameter "desc" 
--------------
SELECT *
FROM pg_settings pg
 WHERE pg.source 'default'sc
-------------------
here the link to image https://tinypic.host/i/XCOYe

**Comment by E1izabeth** [comment]
As a temporary workaround you could try copying the query you paste and paste it again. It helped me.

**Comment by E1izabeth** [comment]
The issue was solved in scope of #18982 and fix will be available in DBeaver 23.1.0.
If the issue will appear again for you in the new DBeaver version, please let me know.
