### ISSUE TITLE
Error retrieving date/time information using advanced datetime editor

### ISSUE THREAD

**Issue by phoenix** [dbeaver/dbeaver#19105]
### Description

I activated  advanced datetime editor to edit date field,but it can't work,everytime see this error:
![20230220092858](https://user-images.githubusercontent.com/13561/219989873-59ad038b-3edd-4994-9f4a-e4db34d764d1.png)

### DBeaver Version

Community Edition 22.3.5.202302171528

### Operating System

Windows 11

### Database and driver

MySQL 8.0

**Comment by Destrolaric** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by phoenix** [comment]
> Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

!SESSION 2023-02-24 09:00:04.034 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.ui 2 2 2023-02-24 09:00:08.159
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

There is no more log information,and dbeaver-debug.log is empty

**Comment by phoenix** [comment]
org.jkiss.dbeaver.model.DBUtils.getAttributeValue returns datetime field as a String Object ,but org.jkiss.dbeaver.ui.controls.CustomTimeEditor.adaptToDate can't deal with String Object,so a DBCException be shown.
Maybe DBUtils should return some kind of Date Object,or adaptToDate should try convert String to Date Object,I guess.

![20230224105857](https://user-images.githubusercontent.com/13561/221081453-8e818717-21f4-493a-8cf3-7a0331b51ae0.png)

**Comment by Destrolaric** [comment]
@phoenix Hi, we have a default behaviour to try to convert Strings to Java Date(or other) class before passing it to the editor. Can you please look if in `Editors -> Data Editor -> Appearance -> Dataformats` checkbox `disable date/time formatting` is enabled?

**Comment by phoenix** [comment]
> 

I unchecked the checkbox then it works fine, thanks!
I unchecked the checkbox in global settings, it won't affect the other Datasource settings, even the other Datasource is using global settings. I must repeat this operation for every Datasource.

**Comment by phoenix** [comment]
> @phoenix Hi, we have a default behaviour to try to convert Strings to Java Date(or other) class before passing it to the editor. Can you please look if in `Editors -> Data Editor -> Appearance -> Dataformats` checkbox `disable date/time formatting` is enabled?

I unchecked the checkbox then it works fine, thanks!
I unchecked the checkbox in global settings, it won't affect the other Datasource settings, even the other Datasource is using global settings. I must repeat this operation for every Datasource.

**Comment by Destrolaric** [comment]
@phoenix Hi, I am going to close the issue as it works as expected. You can open a different ticket for preferences issue.
