### ISSUE TITLE
OutOfMemoryError occurred while reading a 3GB sqlite file on Windows

### ISSUE THREAD

**Issue by wgong** [dbeaver/dbeaver#19104]
### Description

I am a first-time user, downloaded dbeaver-ce-22.3.5-x86_64-setup.exe and it was able to show the sample db,
When I tried to open my own SQLite file (3GB), it throws
```
OutOfMemoryError occurred while reading file "file:/C:/Users/tmp/db.sqlite".
```

### DBeaver Version

ce-22.3.5-x86_64

### Operating System

Windows 11

### Database and driver

SQLite comes with python 3.9

driver class name = org.sqlite.JDBC

### Steps to reproduce

1) I have a SQLite database file called db.sqlite (3GB), created by python, working fine in both python and sqlitebrowser
2) launch DBeaver 22.3.5, 
3) navigate to File > Open, select the db file
4) it failed with following error

OutOfMemoryError occurred while reading file "file:/C:/Users/tmp/db.sqlite".

**Comment by ShadelessFox** [comment]
Hello @wgong,

You're not supposed to open database files that way.

You need to add a new connection, please see https://github.com/dbeaver/dbeaver/wiki/Create-Connection.

Please let me know if your issue was solved.

**Comment by ShadelessFox** [comment]
In the future, we want to support associating SQLite `.db` files with DBeaver: https://github.com/dbeaver/dbeaver/issues/15395

**Comment by wgong** [comment]
Sorry for the user error. Please close the issue. Thanks a lot.

**Comment by gitthangbaby** [comment]
this is not a "user error", there should be a better message. It's "File Open" operation, it is about opening file related to the app, in case of a database app: the db files. You can't be reading guides for such basic function.
