### ISSUE TITLE
Cannot import API Token for GPT Chat

### ISSUE THREAD

**Issue by dahmmme** [dbeaver/dbeaver#19117]
### Description

Hello,

I'm trying to integrate the GPT chat into my environment.
I generated my API Key on https://platform.openai.com/.

I connected my database and tried to import my Token, but the Token field is empty even after I paste it.

![image](https://user-images.githubusercontent.com/53038361/220112857-ac5b43d3-e6dc-4052-bf65-cb80ffcddec1.png)

Once I paste it, I click on the Temperature field which makes the API token field not look empty:

![image](https://user-images.githubusercontent.com/53038361/220113000-d2ecfa14-18bc-46a2-b197-d429e0581c3d.png)

Finally, once I try to use GPT I get the following error:

```
GTP completion error:
{
    "error": {
        "message": "Incorrect API key provided: ssk-Iudb************************************************************************************************************************************************************************************************n5Ss. You can find your API key at https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}

```

Meaning my token was never saved.

I tried generating other tokens but no success.

### DBeaver Version

Community Edition 22.3.5.202302180832

### Operating System

macOS Ventura 13.1

### Database and driver

1. Database name and version: PostgreSQL 15.2 (Homebrew) on aarch64-apple-darwin22.1.0, compiled by Apple clang version 14.0.0 (clang-1400.0.29.202), 64-bit | postgresql-42.5.0.jar

**Comment by serge-rider** [comment]
Do you use Early Access version of DBeaver or release from dbeaver.io? 

Anyhow, the error saying that you use incorrect API key. 
Usually OpenAI keys start with `sk-`. Yours starts with `ssk-`. Please recheck.

**Comment by dahmmme** [comment]
I see it says ssk-, but I'm definitely adding an sk... Downloaded from Dbeaver.io directly

Edit: Security reasons

**Comment by Destrolaric** [comment]
@dahmmme If it's a valid token, I recommend to invalidate it. I recommend to avoid sending OpenAI tokens in public.

**Comment by arhayka** [comment]
@dahmmme Unfortunately, we can't reproduce this issue.
Could you please check if there is an extra character added somewhere to your API key?

**Comment by E1izabeth** [comment]
It's been a long time since no update on this issue. Please let me know, if it's still actual.

**Comment by dahmmme** [comment]
@E1izabeth Still open.
After upgrading to 23.0.1, I now don't get the error mentioned above.

After trying to translate a statement, Dbeaver now says:
- AI service error: The model: `code-cushman-001` does not exist

I tried with other models but same output.

**Comment by E1izabeth** [comment]
Thank you for update.

**Comment by Destrolaric** [comment]
@dahmmme Hi, recently, OpenAi disabled the codex models, so you should change it to text models `text-*`. We are adding GPT 3.5 Turbo model in the next release, which is the recommended model for code completion.

**Comment by E1izabeth** [comment]
@dahmmme does changing model to the one startd with `text-` help?

**Comment by dahmmme** [comment]
It leads to the following notification:
- AI service error: You exceeded your current quota, please check your plan and billing details. 

I didn't know I had to pay.

**Comment by Destrolaric** [comment]
@dahmmme Hi, OpenAI gives a limited amount of trial quota which is equivalent to 16$(as I remember). This is free, but an additional quota will require paying `per token`. This is an OpenAI usage policy. Each model has its own pricing. You can look it up here: https://openai.com/pricing#language-models. We are planning to add a turbo model, which is significantly cheaper than other models.
