### ISSUE TITLE
SQL Developer connections import - no network alias

### ISSUE THREAD

**Issue by MrThibal** [dbeaver/dbeaver#19111]
### Description

Connections import from SQL Develop for TNS connections doesn't import the TNS "Network Alias".

### DBeaver Version

Community Edition 22.3.5

### Operating System

Microsoft Windows 10 Entreprise 2016 LTSB

### Database and driver

Oracle 19c

### Steps to reproduce

1. Create a TNS connection in SQL Developer
<img width="269" alt="tns-sqldeveloper" src="https://user-images.githubusercontent.com/125679803/219708181-5d14fd9c-1889-435c-8af3-ced4f712db04.png">
2. Import the connection with "File > Import > Third Party Configuration > Oracle SQL Developer"
3. Check the TNS "Network Alias". It is the default value (the first TNS alias)
<img alt="no-tns-sqldeveloper" src="https://user-images.githubusercontent.com/125679803/220073083-afc0074d-318b-469f-aba3-2c0d4f4516f5.png">

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by hawthorne3341** [comment]
@E1izabeth is this issue claimed? If not, I would like to look into it

**Comment by E1izabeth** [comment]
@hawthorne3341 you can work on this. Let me know if you meet difficulties and need help

**Comment by MrThibal** [comment]
Thanks a lot @hawthorne3341 !
