### ISSUE TITLE
LOAD DATA LOCAL INFILE causes error: asked for file 'FILNEMAE' that doesn't correspond to initial query 

### ISSUE THREAD

**Issue by MS-equinom** [dbeaver/dbeaver#19115]
### Description

Hi
When executing a `LOAD DATA LOCAL INFILE` command, we get the following error:

```
SQL Error [HY000]: (conn=11) LOAD DATA LOCAL INFILE asked for file 'C:/PATH/TO/FILENAME.csv' that doesn't correspond to initial query SET STATEMENT SQL_SELECT_LIMIT=200 FOR LOAD DATA LOCAL INFILE 'C:/PATH/TO/FILENAME.csv'

INTO TABLE T_XXX

FIELDS TERMINATED BY ','

IGNORE 1 LINES. Possible malicious proxy changing server answer ! Command interrupted
```
The error does not happen in all version of dbeaver. And does not happen in other programs such as HeidiSQL. 

I tracked the error to line 1751 [here](https://github.com/microsoft/mariadb-connector-j/blob/master/src/main/java/org/mariadb/jdbc/internal/protocol/AbstractQueryProtocol.java).

It looks like the command `SET STATEMENT SQL_SELECT_LIMIT=200 FOR` is being injected into my command for some reason. Any ideas?

Thanks
Menachem

### DBeaver Version

Community edition 22.3.4

### Operating System

Windows 11

### Database and driver

Driver: MariaDB JDBC driver
Database: MariaDB 10.11.2

### Steps to reproduce

1. Configuration file (`my.ini`):

```
[mysqld]
datadir=C:/Program Files/MariaDB 10.6/data
port=3306
innodb_buffer_pool_size=4058M
lower_case_table_names=2
max_allowed_packet=5G
local_infile=1

[client]
port=3306
plugin-dir=C:\Program Files\MariaDB 10.6/lib/plugin
local_infile=1
```

2. Creating a database with a restore command - worked fine. Tables created
3. Tried executing the following command: 

```
LOAD DATA LOCAL INFILE 'C:/PATH/TO/FILENAME.csv'
INTO TABLE T_XXX
FIELDS TERMINATED BY ','
IGNORE 1 LINES;
```

4. Got the following error:

```
SQL Error [HY000]: (conn=11) LOAD DATA LOCAL INFILE asked for file 'C:/PATH/TO/FILENAME.csv' that doesn't correspond to initial query SET STATEMENT SQL_SELECT_LIMIT=200 FOR LOAD DATA LOCAL INFILE 'C:/PATH/TO/FILENAME.csv'

INTO TABLE T_CROPS

FIELDS TERMINATED BY ','

IGNORE 1 LINES. Possible malicious proxy changing server answer ! Command interrupted
```

**Comment by ShadelessFox** [comment]
Hello @MS-equinom,

Please take a look at the official solution here:
https://mysqlconnector.net/troubleshooting/load-data-local-infile/#how-to-fix

Please let me know if you have any questions left.

**Comment by MS-equinom** [comment]
Thanks! I'll check it out.
For now, we solved this one-time problem with HeidiSQL

**Comment by eangutierrez** [comment]
> Hello @MS-equinom,
> 
> Please take a look at the official solution here: https://mysqlconnector.net/troubleshooting/load-data-local-infile/#how-to-fix
> 
> Please let me know if you have any questions left.

Hi @ShadelessFox,

I am a complete beginner and I am attempting to solve this issue in Dbeaver.  I was able to solve it using MySQL Workbench, but I don't understand how to apply the solution you provided above.  Is there a more thorough resource than the one you provided?  Thank you!

**Comment by ShadelessFox** [comment]
First of all, please make sure you have this option set to `true`:

![image](https://user-images.githubusercontent.com/35821147/228887312-fe35c542-da20-4366-9bbf-4369762e0f83.png)

**Comment by eangutierrez** [comment]
Thank you so much!  This helped solve the issue.  Now I can focus on using dbeaver for now.   You are great!

**Comment by hkirschk** [comment]
Hi, I experienced exactly the same error on DBeaver 23.1.1 on macOS Big Sur & Windows, MariaDB version "10.5.20-MariaDB-log" on FreeBSD 13, JDBC driver MariaDB Connector/J 3.1.4. The fix mentioned here did not work. Rolling back to MariaDB Connector/J 3.0.4 fixed this issue. The same error occurred for each of the JDBC versions between 3.0.5 and 3.1.4.

Using the latest mySQL JDBC connector for MariaDB works as expected, i.e. it does not show the error described here.

**Comment by JTMosaic** [comment]
> Hi, I experienced exactly the same error on DBeaver 23.1.1 on macOS Big Sur & Windows, MariaDB version "10.5.20-MariaDB-log" on FreeBSD 13, JDBC driver MariaDB Connector/J 3.1.4. The fix mentioned here did not work. Rolling back to MariaDB Connector/J 3.0.4 fixed this issue. The same error occurred for each of the JDBC versions between 3.0.5 and 3.1.4.
> 
> Using the latest mySQL JDBC connector for MariaDB works as expected, i.e. it does not show the error described here.

Thanks for the info and testing, hkirschk!

Version 3.2.0 of the MariaDB Connector/J also does not work but rolling back to 3.0.4 does the trick

It should also be noted that the following allows the 3.2.0 driver to work:

Set the ResultSet fetch size parameter to 0 

![image](https://github.com/dbeaver/dbeaver/assets/9417720/38bee327-032c-4c4c-8e19-42a21ff1cc1c)

This, I believe, is a bug in DBeaver. DBeaver _should_ detect a LOAD DATA statement and turn off the fetch size for the transacion.

**Comment by myronwood** [comment]
In my case, the fix was to remove all comments from my script.  The comment lines started with either `#` or `-- `
