### ISSUE TITLE
Created Date/Last DDL Date missing

### ISSUE THREAD

**Issue by angeloruggieridj** [dbeaver/dbeaver#19123]
Would it be possible to add in "Statistics Info" metadata info like Created Date and Last DDL Date for Oracle DB?

I think that this feature is not available on DBeaver and force the developer to write the query for every table in order to know when an object has been created. 
I hope that just under Name and Table Type could be possible to show that info.

**Comment by LonwoLonwo** [comment]
Hello @angeloruggieridj 

Add this info for Oracle tables - correct?

**Comment by angeloruggieridj** [comment]
Yes, it is correct

**Comment by LonwoLonwo** [comment]
Ok, thanks for the idea.

**Comment by ftsfranklin** [comment]
Duplicate of #11179. That issue should be edited to include "Oracle" in the title.

**Comment by LonwoLonwo** [comment]
New metadata info added for Oracle table/views/materialized views

![2023-03-20 14_30_15-DBeaver 23 0 1 - NEWTABLE_4](https://user-images.githubusercontent.com/45152336/226329480-6664c55d-ce0a-4f74-b127-edd9a0989cc3.png)

Implemented in 23.0.1.
Will be available [here](https://dbeaver.io/) on 2023-03-27
