### ISSUE TITLE
Comment lost when add new cols to firebird-table

### ISSUE THREAD

**Issue by Ray642** [dbeaver/dbeaver#19125]
### Description

if i add a new col to an existing table in firebird, i have the possibility to add a comment
![grafik](https://user-images.githubusercontent.com/125958784/220285924-f73a73df-e888-405e-9fd1-ff718767fbb8.png)
When i save the new column, the generated sql doesn't include the comment:
![grafik](https://user-images.githubusercontent.com/125958784/220286204-ae7ab55f-0e34-4486-bdbd-78c3dd798533.png)
The comment is lost after commit the new col.

If i create a new table the comments will be generated and saved.

### DBeaver Version

Community Edition 22.3.5.202302171528

### Operating System

Win10

### Database and driver

![grafik](https://user-images.githubusercontent.com/125958784/220286718-e2114d83-f3b2-4cd9-94e6-b099d2e44a06.png)

**Comment by E1izabeth** [comment]
Thank you for bug report.
