### ISSUE TITLE
URL-configured Postgres connections stopped working in 22.3.5

### ISSUE THREAD

**Issue by heshammourad** [dbeaver/dbeaver#19124]
### Description

I have two Postgres DB connections that use URLs and after upgrading to 22.3.5. They both stopped working and it appears that they're trying to connect to the Host settings, so I get error messages saying it can't connect to localhost:5432 because that's the default, even though I have the URL radio button selected.

The other connection has an older database that I no longer use configured in the host settings and for that one I get an password authentication error, because the old username/password no longer work.

### DBeaver Version

Community Edition 22.3.5

### Operating System

Windows 10

### Database and driver

PostgreSQL JDBC Driver

### Steps to reproduce

1. Open version 22.3.5
2. Attempt to create a new PostgreSQL connection
3. Click on the URL radio button
4. Enter a valid Postgres URL
5. Enter the Username and Password
6. Click on Test Connection ...

Expected:
Connection should succeed

Actual:
Get an error saying connection to localhost:5432 failed

Downgrading to 22.3.4 allows this flow, and the same connections that are working in 22.3.4 no longer work after upgrading.

**Comment by E1izabeth** [comment]
May be broken by this changes https://github.com/dbeaver/dbeaver/issues/18751

**Comment by E1izabeth** [comment]
Do you use ssh?

**Comment by E1izabeth** [comment]
Also you tell that you get the message saying that connection to localhost failed. Do you have some domain name or ip in url configuration?

**Comment by evbelico** [comment]
Hello, I keep encountering the same issue when using 22.3.5. Like @heshammourad, I don't use SSH or a VPN.
It seems like the connection keeps pointing toward `localhost` even when providing a working url.

Downgrading to 22.3.4 solved the issue too.

**Comment by serge-rider** [comment]
Probably side effect of https://github.com/dbeaver/dbeaver/issues/18716 + https://github.com/dbeaver/dbeaver/issues/18751

@evbelico Could you write how your URL looks like? 
You can replace real host name with some fake value.

**Comment by serge-rider** [comment]
Bug fixed.
Also multi-db connections disabled for URL-based configuration (as we can't modify custom URL).

**Comment by heshammourad** [comment]
Looks like this may already be fixed, but in case it's needed, here's some additional info.

I do not use SSH. My URL is something like `jdbc:postgresql://host.amazonaws.com:5432/database`. For the localhost error, the greyed out Host input still has `localhost` in it, as I never updated the default values when creating the connection.
