### ISSUE TITLE
update wiped out entire Workspace

### ISSUE THREAD

**Issue by allanlaal** [dbeaver/dbeaver#19138]
### Description

my workspace is empty now, all the config files in it disappeared,
only .metadata folder remains

### DBeaver Version

Community Edition 22.3.5

### Operating System

Linux Ubuntu Mate 22.04

### Database and driver

N/A

### Steps to reproduce

1. upgrade from 22.3.4 → 22.3.5 with apt

**Comment by Destrolaric** [comment]
@allanlaal Hi, I tried to use DPKG installation, and that didn't cause this issue. DBeaver doesn't contain official distribution through apt. Can you provide more info about the way DBeaver was installed and updated?

**Comment by allanlaal** [comment]
@Destrolaric 

	# cat /etc/apt/sources.list.d/dbeaver.list 
	deb https://dbeaver.io/debs/dbeaver-ce

**Comment by serge-rider** [comment]
@allanlaal Generally it can not happen just because version update. Installer doesn't know about workspace location, it cannot clean it.
Are there any logs in the workspace?

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still actual for you, feel free to reopen it.

**Comment by allanlaal** [comment]
I think the workspace files just got mixed up or overwritten by a duplicate instance

at any point I might have 2..7 DBeavers running from the same workspace
so I changed them to use their own workspace files
