### ISSUE TITLE
NULL is not correct on char/varchar type

### ISSUE THREAD

**Issue by victor0801x** [dbeaver/dbeaver#1913]
SQL-generator and UI do not generate/show correctly on default NULL when datatype is char/varchar.
NULL will generate to 'NULL', that will cause later operation error.
![2017-07-25 10-43-30](https://user-images.githubusercontent.com/4534038/28553430-249f65d8-7126-11e7-9a45-2dd0d444b800.png)

![2017-07-25 10-21-46](https://user-images.githubusercontent.com/4534038/28553325-9035db3e-7125-11e7-8120-94aa5e163c21.png)

then alter table column will generate wrong SQL
![2017-07-25 10-24-26](https://user-images.githubusercontent.com/4534038/28553354-b7cdfa50-7125-11e7-9b3e-2238291e7ef9.png)

![2017-07-25 10-24-35](https://user-images.githubusercontent.com/4534038/28553356-b914f300-7125-11e7-86d4-b1d309eb52a4.png)

![2017-07-25 10-24-54](https://user-images.githubusercontent.com/4534038/28553360-bb4f04b2-7125-11e7-82f2-a7bb766cf399.png)

**Comment by serge-rider** [comment]
What is your database/driver? 
This looks like a driver issue (DBeaver gets column default values from JDBC API). Potentially it is possible to a workaround for some particular driver.

**Comment by victor0801x** [comment]
@serge-rider I'm using MariaDB 10.2.7. I had tried 1.5.5~2.0.3 driver. None of them work.

**Comment by serge-rider** [comment]
Well, I still can't figure out what is the problem.
If you set default value to string 'NULL' then it works fine. String 'NULL' isn't the same as NULL value (which is already default value for all columns and it doesn't make sense to set it explicitly).

Could you provide steps to reproduce the problem?

**Comment by victor0801x** [comment]
1. create new table, column accept NULL,
```sql 
CREATE TABLE test (a char(10), b int);
SHOW CREATE TABLE `test`;
```
```sql
CREATE TABLE `test` (
  `a` char(10) DEFAULT NULL,
  `b` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```
but, dbeaver shows the column a default value is 'NULL' not NULL
![2017-07-29 09-45-33](https://user-images.githubusercontent.com/4534038/28741148-ee75f1ae-73d5-11e7-8541-652919641597.png)
if I alter table (a char(10) to char(20)) by dbeaver, it will generate wrong sql(NULL -> 'NULL'), but executable
```mysql
ALTER TABLE test MODIFY COLUMN a char(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'NULL' NULL ;
```
alter again (a char(20) to char(30)) by dbeaver, it will generate non-executable sql
```mysql
ALTER TABLE test MODIFY COLUMN a char(30) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT ''NULL'' NULL ;
```

**Comment by serge-rider** [comment]
Do you use default pre-configured MariaDB driver?
What is your DBeaver version?
I don't see Partitions tab.
Columns should be:
![default](https://user-images.githubusercontent.com/6398845/28747536-e443f13e-74a9-11e7-9380-86d45042f306.png)

And DDL should look like this:
![default](https://user-images.githubusercontent.com/6398845/28747521-772d67d8-74a9-11e7-8436-445dc930cbca.png)

**Comment by victor0801x** [comment]
I'm using DBeaver 4.1.0~4.1.1
Which version is the default pre-configured MariaDB driver? 
1.5.5 ? (which is new connection to MariaDB for dbeaver default driver). already tried, not working

**Comment by tati-kru** [comment]
Hi @victor0801x!
Could you, please, check that it can be reproduced or not on the latest version?

**Comment by victor0801x** [comment]
@tati-kru still not correct
![2018-01-20 16-50-30](https://user-images.githubusercontent.com/4534038/35181715-10e27ec2-fe02-11e7-805a-83db937faf03.png)
![2018-01-20 16-47-34](https://user-images.githubusercontent.com/4534038/35181699-dda97132-fe01-11e7-8a66-ac4b9404a3ac.png)
![2018-01-20 16-47-45](https://user-images.githubusercontent.com/4534038/35181701-def2b21a-fe01-11e7-86fa-f8bb1294a445.png)
![2018-01-20 16-48-25](https://user-images.githubusercontent.com/4534038/35181703-e0e477b6-fe01-11e7-8e76-9dd5cd9ad1f3.png)

**Comment by serge-rider** [comment]
I still can't reproduce that with our test servers. Perhaps this depends on server config.
Anyhow - I've added a workaround for this case. Please check it in the next version.

**Comment by victor0801x** [comment]
@serge-rider @tati-kru the last version 4.3.3. NULL is correct. Thanks.
But, char/varchar the default value seems has redundant quotes
![2018-01-22 08-32-12](https://user-images.githubusercontent.com/4534038/35200806-2a7bd574-ff4f-11e7-9db1-389c14c931dd.png)

**Comment by serge-rider** [comment]
Yep, another bug. Thanks for noticing

**Comment by victor0801x** [comment]
@serge-rider the latest version 4.3.4 fixed all problems,
thanks
