### ISSUE TITLE
Updated to 22.3.5 ... Dbeaver won't open now 

### ISSUE THREAD

**Issue by CathyBreslow** [dbeaver/dbeaver#19146]
### Description

Upgraded to 22.3.5 Community version on Mac OS Mojave.  Moved to Applications folder.  When I click on the icon to restart, I get "The last time you opened DBeaver Community, it unexpectedly quit while reopening windows. Do you want to try to reopen its windows again?"  I click 'reopen' and nothing happens.   DBeaver was working fine before this. 

### DBeaver Version

Tried to upgrade to 22.3.5

### Operating System

Mac OS Mojave V 10.14.6

### Database and driver

Postgres on AWS and DB2

### Steps to reproduce

1. Install via dmg.
2. Copy to Applications folder (keep both option).
3. Click on DBeaver icon in Applications folder.  Receive "DBeaver is an app downloaded from the Internet. Are you sure you want to open it?"  I click 'Open.'
4. Get popup "The last time you opened DBeaver Community, it unexpectedly quit while reopening windows. Do you want to try to reopen its windows again?"    I click 'Reopen.'  I get a popup indicating "DBeaver quit unexpectedly."

**Comment by CathyBreslow** [comment]
Fixed.   Renamed workspace folder, then restarted DBeaver, which worked. Then I replaced the contents of the current workspace folder with the old contents.

**Comment by serge-rider** [comment]
Thanks for the update.
Probably workspace was corrupted because of unexpected shutdown. Or maybe you used very old version of DBeaver before. Could you say what was it?

**Comment by CathyBreslow** [comment]
I always keep my versions up to date, so it was 22.4.  Probably was due to a bad shutdown.

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it.
