### ISSUE TITLE
postgres jdbc url is ignored

### ISSUE THREAD

**Issue by parcit-nibu** [dbeaver/dbeaver#19149]
### Description

1. Add a postgres connection
2. use jdbc url to connect
3. save
4. try to connect

result: the server settings are used (default localhost)
expected: the jdbc url is used to connect (contains server et al)

Version 22.3.5.202302171528

### DBeaver Version

CE 22.3.5.202302171528

### Operating System

Windows 10

### Database and driver

Postgres Database
Postgres JDBC Driver 42.5.0

### Steps to reproduce

1. Add a postgres connection
2. use jdbc url to connect
3. save
4. try to connect

result: the server settings are used (default localhost)
expected: the jdbc url is used to connect (contains server et al)

Version 22.3.5.202302171528

**Comment by E1izabeth** [comment]
Thank you for bug report.
It's a duplicate of #19124
