### ISSUE TITLE
Autocomplete Only Working on Some Schemas

### ISSUE THREAD

**Issue by anniejestus** [dbeaver/dbeaver#19140]
### Description

Autocomplete stopped working on one of my frequently-used schemas. Previously, typing "SELECT * FROM SCHEMANAME." and then ctrl+click would populate table names to choose from, but now I get "no proposals". Similarly, if i manually enter a tablename, when I try to select columns using "tablename." ctrl+click in that schema, I get a result of "no proposals". The features work for other schemas in the DB2 database, and in other schemas in different DB2 databases, but not in one particular schema. I can run queries against tables in that schema by manually entering table names and column names; only the autocomplete is not working. Attached is a screenshot of my settings. I didn't change anything prior to this issue beginning. 

<img width="704" alt="Screen Shot 2023-02-21 at 11 22 00 AM" src="https://user-images.githubusercontent.com/70293593/220401504-319f5008-eb42-4219-bbc7-4eabfa4fa7c5.png"> 

### DBeaver Version

Community 22.1.4

### Operating System

macOS Monterey 0.6.3

**Comment by LonwoLonwo** [comment]
Hello @anniejestus 

> but not in one particular schema

Can you provide the name of this schema?

Additionaly, could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it.
