### ISSUE TITLE
PosgreSQL role DDL script missing role settings

### ISSUE THREAD

**Issue by yoni-yad2** [dbeaver/dbeaver#19148]
### Description

When generating a DDL SQL script for a PostgreSQL role with settings, these settings do not show up in script as ALTER command.

### DBeaver Version

22.3.5.202302171528

### Operating System

Windows 10 64 bit

### Database and driver

PostgreSQL 14.4
PostgreSQL JDBC Driver

### Steps to reproduce

1. connect to DB and Run:
```
CREATE ROLE test_role;
ALTER ROLE test_role set TimeZone=utc;
```
2. "Generate SQL"->"DDL" in DB Navigator for test_role

### Additional context

The query to get these settings is:
`select r.rolname,pdrs.* from pg_catalog.pg_roles r left join pg_catalog.pg_db_role_setting pdrs on r.oid = pdrs.setrole`

**Comment by LonwoLonwo** [comment]
Thanks for the idea and for the query @yoni-yad2
