### ISSUE TITLE
SQL error unless SQL Statement is correct

### ISSUE THREAD

**Issue by hoppfrosch** [dbeaver/dbeaver#19147]
### Description

Within DBeaver SQL-Editor I try to execute the following MySQL-statement:

`INSERT IGNORE INTO komponentebase(KomponenteBase_Name) VALUES ('SSPAppConfig-108777-EB')`

This fails with the following error-message:

`SQL-Fehler [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT IGNORE INTO komponentebase(KomponenteBase_Name)  VALUES ('SSPAppConfig' at line 1`

I validated the SQL-Syntax for example on https://www.eversql.com/sql-syntax-check-validator/ against my used MySQL-Server version (8.0) 

What's wrong? Why is my value to insert truncated ( `VALUES ('SSPAppConfig' `) within the returned error-message ?

### DBeaver Version

Community Edition 22,3,5

### Operating System

Win10

### Database and driver

MySQL 8.0
com.mysql.jdbc.Driver

### Steps to reproduce

see above

**Comment by E1izabeth** [comment]
Please, describe the exact steps how are you trying to execute this query. What is your cursor position? Which button or shortcut do you press to execute query? Video recording showing this issue would be very useful.

**Comment by E1izabeth** [comment]
it's been a long time since no update on this issue. Please let me know, if it's still actual, and provide additional info.
