### ISSUE TITLE
Large fonts break interface on the mac OS

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#19159]
### Description

If you try to enlarge the font, the user interface will crash in Preferences, Database Navigator, Search, Tips,  and probably elsewhere.

<img width="500" alt="Screenshot 2023-02-22 at 18 43 11" src="https://user-images.githubusercontent.com/12581569/220714102-f1c4478a-ce5d-4853-8ade-8bfb95a9b208.png">

<img width="500" alt="Screenshot 2023-02-22 at 18 55 06" src="https://user-images.githubusercontent.com/12581569/220714424-7b5dd88a-e6c8-4f93-973d-c0f9936e5d54.png">

<img width="400" alt="Screenshot 2023-02-23 at 12 12 51" src="https://user-images.githubusercontent.com/12581569/220890763-ae4a46cc-9389-4f98-abdc-89333893b0c2.png">

### DBeaver Version

CE 22.3.5

### Operating System

Mac OS Monterey

### Steps to reproduce

1. Open Preferences —> User Interface —> Appearance —> Colors and Fonts
2. Set the size of any DBeaver font to 36 or larger

### Additional context

Font failure in Database Navigator must be closed in https://github.com/dbeaver/dbeaver/issues/19013

**Comment by ShadelessFox** [comment]
Unfortunately, this issue is present in Eclipse, too.

But it doesn't look that bad to me:

<img width="1440" alt="Screenshot 2023-02-24 at 16 29 17" src="https://user-images.githubusercontent.com/35821147/221189845-c631db6e-5066-4883-b30a-8705af075ad3.png">

**Comment by arhayka** [comment]
Indeed, only the buttons look strange, the rest looks good.

**Comment by arhayka** [comment]
Testing after https://github.com/dbeaver/dbeaver/issues/19013: tree in Database Navigator looks perfect! What else:

1. List in Properties

<img width="784" alt="Screenshot 2023-02-27 at 23 11 10" src="https://user-images.githubusercontent.com/12581569/221699019-54b1fca2-8cc2-4da1-8281-5277130db1fc.png">

2. Tabs in Connect to database window

<img width="697" alt="Screenshot 2023-02-27 at 23 12 38" src="https://user-images.githubusercontent.com/12581569/221699115-579015cc-be91-4f3c-866e-29bb2998e8f8.png">

3. Search field in Preferences

<img width="751" alt="Screenshot 2023-02-27 at 23 13 52" src="https://user-images.githubusercontent.com/12581569/221699337-406018b9-8ccf-4cfb-806a-81e149156f83.png">

4. Select in Search

<img width="1182" alt="Screenshot 2023-02-27 at 23 18 03" src="https://user-images.githubusercontent.com/12581569/221699434-a7294aa7-b522-4653-ad2e-e88db8def42c.png">

5. Buttons everywhere

**Comment by serge-rider** [comment]
Fix was reverted as it broke fonts in SQL editor and embedded SQL editors.

**Comment by E1izabeth** [comment]
Besides zooming, font in embedded editors like ddl view for objects became main instead of monospace
