### ISSUE TITLE
Table description font is very small

### ISSUE THREAD

**Issue by jmarcher** [dbeaver/dbeaver#19152]
### Description

I just updated to 22.3.5 and the fonts on the Properties page of the table is very small (see screenshot) before the update all was normal
<img width="776" alt="image" src="https://user-images.githubusercontent.com/686843/220596696-40e38354-24b2-45ab-9aec-680542678a0f.png">

### DBeaver Version

22.3.5

### Operating System

macOS Ventura 13.2.1 (22D68)

### Database and driver

MySQL 8

**Comment by thach-huynh** [comment]
Hi @jmarcher ,
The same for me with macos Ventura 13.2.1, DBeaver version 22.3.5.202302180832 on Macbook M1 chip and I found a way to increase it.

Come to Preferences -> User Interface -> Appearance -> Colors and Fonts -> DBeaver Fonts -> Main font and increase the font size here, close the small popup, then Apply and Close. It works for me:

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/68645497/220607546-d1f6111d-ee0b-4221-8b27-1730df8dc0f9.png">

Result:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/68645497/220607878-9789b6b7-f3de-48b0-9a6e-be5ab2437d1e.png">

**Comment by E1izabeth** [comment]
Which font is set by default for you here? 
![image](https://user-images.githubusercontent.com/28875055/220611867-ccdc19e5-c881-4feb-b114-b0fb3b258bfe.png)

**Comment by jmarcher** [comment]
> Hi @jmarcher , The same for me and I found a way to increase it. Come to Preferences -> User Interface -> Appearance -> Colors and Fonts -> DBeaver Fonts -> Main font and increase the font size here. It should work:
> 
> <img alt="image" width="1097" src="https://user-images.githubusercontent.com/68645497/220607546-d1f6111d-ee0b-4221-8b27-1730df8dc0f9.png">
> 
> Result: <img alt="image" width="488" src="https://user-images.githubusercontent.com/68645497/220607878-9789b6b7-f3de-48b0-9a6e-be5ab2437d1e.png">

That did not work for me, now I have a weird padding on all the UI elements

**Comment by jmarcher** [comment]
> Which font is set by default for you here? ![image](https://user-images.githubusercontent.com/28875055/220611867-ccdc19e5-c881-4feb-b114-b0fb3b258bfe.png)

AppleSystemUIFont

**Comment by thach-huynh** [comment]
The default font there is AppleSystemUIFont. Increase to 13, close the small popup, then Apply and Close. 
The font is fixed.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by jmarcher** [comment]
Changing the font worked now, had to restart DBeaver in order to fix the padding

**Comment by E1izabeth** [comment]
Please, don't close the issue. We're going to fix it.

**Comment by thach-huynh** [comment]
So you have to change the font to a different font type @jmarcher ?

**Comment by jmarcher** [comment]
No, left it as the default font
