### ISSUE TITLE
cockroachdb won't connect after upgrade to 22.3.5

### ISSUE THREAD

**Issue by greenbla** [dbeaver/dbeaver#19163]
### Description

Thank you for your superb work on this useful software.
After upgrading from 22.3.4 to 22.3.4s, dbeaver won't connect to cockroachdb. 
error text: '''Connection to 'system' was lost and cannot be re-established.
What do you want to do? Reason: Connection to localhost:26258 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.'''
After downgrading back error disappears, and I can connect as always.

### DBeaver Version

Community Edition 22.3.5

### Operating System

Win 11 Home Build 22621

### Database and driver

database: CockroachDB
driver: PostgreSQL JDBC Driver

### Create CockroachDB instance:
Sign up at https://cockroachlabs.cloud/signup . Download certificate using the Connect button at top right of database overview page.
### Create DBeaver Connection:
In Dbeaver, configure CockroachDB connection using JDBC string provided using same button of web page. Authentication: database native. Fill in Username and Password. In Driver Properties tab, download necessary drivers. On SSL tab, select Use SSL, and in CA certificate, fill in the location of the downloaded certificate.
### Connect:
Open Dbeaver. Database Navigator -> system (default name of cockroachDB connection). Errors '''Connection to localhost:26258 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections. Connection refused: no further information.'''

### Additional context

It should be connecting by URL, not by host. This makes it strange that it complains about localhost!

**Comment by greenbla** [comment]
Probably duplicate of #19124 - cockroach also uses postgreSQL drivers.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by LonwoLonwo** [comment]
Hello @greenbla 

Can you please test the Early Access DBeaver version? https://dbeaver.io/files/ea/ Is the issue solved there?

**Comment by greenbla** [comment]
It works perfectly. Thanks guys for your help.
