### ISSUE TITLE
Problem with DBF

### ISSUE THREAD

**Issue by IbrahimTurgunov** [dbeaver/dbeaver#19166]
### Description

i have a problem with dbf, i cannot join two tables while my sql script is correct, it gives me an error like join is not supported, please help,thanks

### DBeaver Version

22.3.5

### Operating System

windows 10 pro

### Steps to reproduce

1. I make database connection like DBF
2. import my tables
3. write sql script
4. try to join
5. run the query
6. see the error "SQL Error: Syntax error: JOIN not supported"

**Comment by ShadelessFox** [comment]
Hello @IbrahimTurgunov,

What driver are you using? From the error message, it seems that joins are not supported on the database level.

**Comment by IbrahimTurgunov** [comment]
The dirver is CsvJdbc 1 and driver type DBF

**Comment by ShadelessFox** [comment]
The driver does not support joins:

> SQL sub-queries are permitted but joins between tables in SQL SELECT queries are not yet supported

As a workaround, you can export your data to any other database and perform joins there.

Closing as a third-party issue.
