### ISSUE TITLE
Oracle - Large DDL export

### ISSUE THREAD

**Issue by pw-kyu** [dbeaver/dbeaver#19161]
### Description

Hello, I have a view that has over 2000 lines for the script. However when i check the view > declaration or if I right click the view and generate DDL, it gives me a truncated 400 or so lines of the DDL. How do I get the complete DDL in Dbeaver?

Thanks in advance!

### DBeaver Version

Community Edition 22.3.5.202302171528

### Operating System

win 10

### Database and driver

Oracle
ojdbc8-12.2.0.1.jar

### Steps to reproduce

1. Right click view in database navigator > Generate SQL > DDL
2. OR double click view and go to declaration
3. Both DDLs are truncated forms of the original DDL
4. I compared the DDL vs the one I get from TOAD and there is lots of DDL missing

**Comment by LonwoLonwo** [comment]
Hello @pw-kyu 

Thanks for the bug report.
This is duplicate of https://github.com/dbeaver/dbeaver/issues/15730.
So I'm closing this issue.
