### ISSUE TITLE
Reuse JDBC driver in global classpath

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/dbeaver#19165]
### Description

JDBC driver added into global classpath didn't show up in the list of driver settings.

Related to #14080. Probably duplicate as #15408.

### DBeaver Version

Community Edition 22.3.5.202302180832

### Operating System

macOS Ventura 13.1 (22C65)

### Database and driver

Seems irrelevant to specific database or driver.

### Steps to reproduce

1. add SQLite JDBC driver into global classpath
2. edit MySQL connection, Driver Settings -> Libraries -> Find Class, and SQLite JDBC driver is not in the driver class list

### Additional context

I was trying to add a JDBC wrapper, which supposed to work without changing all driver settings, except adding additional prefix to existing connections. For example: change `jdbc:mysql://localhost:3306` to `jdbc:mywrapper:mysql://localhost:3306`, and then DBeaver should pick the JDBC wrapper to establish connection.

**Comment by ShadelessFox** [comment]
Hello @zhicwu,

Thanks for the report.
