### ISSUE TITLE
Error getting JDBC meta data

### ISSUE THREAD

**Issue by SU-R27** [dbeaver/dbeaver#19172]
### Description

Hello,
After upgrading to Dbeaver Community ver. 22.3.5 from 22.3.4 I cannot longer connect to an SQL Server instance on version 10.50.1600.1. I get the error: Error getting JDBC meta data

With another instance of SQL Server on version 12.0.4100.1, I can connect normally.

I tried both SQL Server 12.2.0.jre11 and SQL Server 11.2.0.jre11 driver versions with the same behaviour.

Log file:
[LOG.txt](https://github.com/dbeaver/dbeaver/files/10816843/LOG.txt)

### DBeaver Version

Dbeaver Community 22.3.5

### Operating System

Windows 10 - 20H2

### Database and driver

Database: SQL Server 10.50.1600.1
Driver: SQL Server 12.2.0.jre11 / SQL Server 11.2.0.jre11

### Steps to reproduce

1) Try to connect to SQL Server database.
2) Error shows: Error getting JDBC meta data

**Comment by LonwoLonwo** [comment]
Hello @SU-R27 

I see in the log:

```
ADVERTENCIA: TLSv1 was negotiated. Please update server and client to use TLSv1.2 at minimum.
2023-02-23 13:05:52.585 - Error getting current user: SQL Server no devolvió una respuesta. Se ha cerrado la conexión.
```

This is I found about support the TLSv1.2 https://support.microsoft.com/en-us/topic/kb3135244-tls-1-2-support-for-microsoft-sql-server-e4472ef8-90a9-13c1-e4d8-44aad198cdbe

Also, maybe this driver setting (in the Connection Settings) changing may help, but I'm not sure: 

![2023-02-24 12_46_16-Connect to a database](https://user-images.githubusercontent.com/45152336/221148105-f033843c-d071-4d40-b7a0-72ce3bacf3cb.png)

Or you can try to downgrade your driver to version 9.2.0

**Comment by SU-R27** [comment]
Hello,
Downgrading the driver to version 9.2.0 solved the issue, now I can connect to the database.
Thank you.
