### ISSUE TITLE
Visual bug in CHAR type column, carrying a UUID

### ISSUE THREAD

**Issue by themegazord** [dbeaver/dbeaver#19173]
### Description

When inserting a UUID in an X column with the type Char(36), all the data that are inserted in it, if they start with numbers, will be shown in the selects only that number, those that start with a letter, will show the complete UUID.

### DBeaver Version

Community Edition 22.3.4

### Operating System

Windows 10 Pro

### Database and driver

Database and version: MySQL 15.1
Driver: com.mysql.jdbc.Driver

### Steps to reproduce

1. I create the table with column type char(36)
2. I insert the data with the UUID starting or not with numbers in the appropriate column (in the example below, the id_billing column)

Start with number
```sql
INSERT INTO installments (users_id,id_billing,status,description,debtor_id,emission_date,due_date,overdue_payment,amount,created_at,updated_at) values (4,'80a5b203-aaa1-31d8-a490-a8649a017dd8','Open','And argued each case with MINE,'' said the.',1,'2023-02-02','2023-02-27',0,65.01,'2023-02-23 18:25:35','2023-02-23 18:25:35');
```

[Click here to see image -> Start with number](https://prnt.sc/dow1Ngy2xcVN)

Start with character
```sql
INSERT INTO installments (users_id,id_billing,status,description,debtor_id,emission_date,due_date,overdue_payment,amount,created_at,updated_at) values (4,'a0a5b303-aaa1-31d8-a490-a8649a017dd8','Open','And argued each case with MINE,'' said the.',1,'2023-02-02','2023-02-27',0,65.01,'2023-02-23 18:25:35','2023-02-23 18:25:35');
```
[Click here to see image -> Start with character](https://prnt.sc/gKRGea7BkYJV)

[Print de describle table](https://prnt.sc/5Q9CVdSSaq2e)

**Comment by LonwoLonwo** [comment]
Hello @themegazord 

Can you please provide the DDL of `installments` as text?
Strangely, the `id_billing` column has a numeric data type on your screens.

![2023-03-02 15_02_00-Скриншот сделан с помощью Lightshot — Mozilla Firefox](https://user-images.githubusercontent.com/45152336/222423380-1733f1cb-8c8e-48b7-95f5-765e40c06d79.png)

Additionally, please provide info about your driver and server from the  "Test connection" button in the Connection Settings.

Like this
![2023-03-02 15_03_24-Connection _localhost 2_ configuration](https://user-images.githubusercontent.com/45152336/222423931-ad3b5707-7a76-4d7e-85f9-eef19854f71b.png)

**Comment by themegazord** [comment]
Hi @LonwoLonwo .

Thank you for your attention.

Next, in the Issue there is a link that leads to the print of the description of the table, which shows that `id_billing` is a CHAR(36). I will forward again.

[Here.](https://prnt.sc/5Q9CVdSSaq2e)

**Comment by themegazord** [comment]
![image](https://user-images.githubusercontent.com/75401705/222442433-a0d15b76-cbb3-43e3-88b0-b5aa0745b4a2.png)

**Comment by LonwoLonwo** [comment]
I am confused about your database server. Is it MySQL 5.5? Or is it MariaDB?

If you have a MariaDB database - use the MariaDB provider:

![2023-03-15 12_21_15-Connect to a database](https://user-images.githubusercontent.com/45152336/225264942-28b29ae5-f848-4b4b-b496-1e88ccdaaf62.png)

If you have MySQL 5.5 - then use MySQL 5. If your MySQL database server version starts from 8 - use "MySQL":

![2023-03-15 12_21_25-Connect to a database](https://user-images.githubusercontent.com/45152336/225264956-298aaf43-fdf4-40c7-9420-f5e6c8151f6d.png)

**Comment by themegazord** [comment]
It's MySQL

**Comment by LonwoLonwo** [comment]
Could you please connect with the MySQL 5 connector? And try again.

![2023-03-15 12_21_25-Connect to a database](https://user-images.githubusercontent.com/45152336/225264956-298aaf43-fdf4-40c7-9420-f5e6c8151f6d.png)

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
