### ISSUE TITLE
Annotation relationship

### ISSUE THREAD

**Issue by os3albert** [dbeaver/dbeaver#19184]
is it possible?
# scenario:
imagine someone want to `annotate` a relation between two tables even though they aren't in a relationship. (this sometimes can happen in big projects)
should be very nice add an annotation tab or menu quick options (we call that menu when we press right click on our mouse) where that gives you the opportunity to annotate through a relationship line with 30% opacity instead of 100% 

![image](https://user-images.githubusercontent.com/47365826/213824723-9e49a03f-3f28-4044-b27f-b15568ac7c26.png)

as you can see should be very useful for database analysis

annotation shouldn't be always shown on the screen but just once the user has pressed the button show annotation

**Comment by arhayka** [comment]
@os3albert Are you aware of virtual keys? 
Please take a look at this:
- https://github.com/dbeaver/dbeaver/wiki/ER-Diagrams#structure-adjustment
- https://github.com/dbeaver/dbeaver/wiki/Data-Viewing-and-Editing#defining-virtual-keys

**Comment by os3albert** [comment]
Yep I've a question but connection line made are visible just in local, they don't affect remote db right?

**Comment by arhayka** [comment]
@os3albert Right, this connection line only exists in DBeaver. It doesn't affect the remote database.

**Comment by arhayka** [comment]
It seems that the desired feature already exists. So, I close this issue.
