### ISSUE TITLE
Columns are read-only if query has comment block before

### ISSUE THREAD

**Issue by tohghua** [dbeaver/dbeaver#19188]
### Description

If there's "#\n" before the sql, its query result will not be editable even if it has a primary key.
For example:
\#
select * from foo

### DBeaver Version

Community Edition 22.3.5

**Comment by LonwoLonwo** [comment]
Hello @tohghua 

What database do you use?
Could you provide a screen of the issue?

**Comment by tohghua** [comment]
@LonwoLonwo 
I use mysql 5.7
Screenshot:
![a](https://user-images.githubusercontent.com/12222062/221521215-4eaf21a3-f4c0-47d1-82b2-93454e9ae6ab.png)

**Comment by LonwoLonwo** [comment]
Ok, thanks. The user mentioned that issue here https://github.com/dbeaver/dbeaver/issues/17724#issuecomment-1406990005, but didn't create the ticket.

**Comment by LonwoLonwo** [comment]
You can add an extra line between your comment and query as a workaround.

![2023-02-27 12_36_36-DBeaver Ultimate 22 3 5 - _localhost MySQL 5 5_ Script-209  Script-209](https://user-images.githubusercontent.com/45152336/221527686-cd01c99f-846f-46f5-a250-5ef512579fb1.png)

**Comment by serge-rider** [comment]
The problem caused by JSQLParser lib which doesn't support single line comments starting with #. You can use -- prefix instead.

We will fix it after replacing JSQLParser  with our own lib.

**Comment by antonj19** [comment]
> The problem caused by JSQLParser lib which doesn't support single line comments starting with #. You can use -- prefix instead.

Beside dashes `-- SELECT...`, block comments `/* SELECT ... */` are also working. The only issue seems to be the usage of hash symbols `# SELECT...` within the executed SQL statement.

_DBeaver Version 23.2.0.202309041200_

**Comment by LonwoLonwo** [comment]
Case from #21390 

```sql
SELECT
*
FROM
SOME_TABLE
where COLA = "2024"
and COLB = 17644
# and COLC = 'cat'
```

**Comment by arhayka** [comment]
We decided to fix this problem in a different way. We want to cut the comments before passing it to JSQLParser.
