### ISSUE TITLE
Postgres explain plan and analyze

### ISSUE THREAD

**Issue by simonuwe** [dbeaver/dbeaver#19191]
### Description

When creating eplain-plans for Postgres-SQL-Queries could causs an error when switching on/off the "analyze" option.

### DBeaver Version

Comunity 22.3.5.202302171528

### Operating System

ubuntu 22.04

### Database and driver

Postgres 15.2
JDBC Driver 42.2.24

### Steps to reproduce

1. explain a sql-query
2. switch on all options (analyze, ...)
3. Press OK button
4. You get the plan for your query
5. switch off analyze. now options "wal" and "timing" are disabled
6. Press OK Button
7. Result is "ERROR: EXPLAIN option WAL requires ANALYZE"

### Additional context

Looks like the "wal" and "tuning" options are passed to explain event when "analyze" is off
![grafik](https://user-images.githubusercontent.com/97161460/221402427-802880fd-c493-4f9f-8402-c4ff3fd07c88.png)
![grafik](https://user-images.githubusercontent.com/97161460/221402442-eb24c016-ce97-4c07-9243-2322926d8953.png)

Workarround:
first switch off "wal", "timing" then switch off "analyze".

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @simonuwe
