### ISSUE TITLE
Running queries on Athena gets stuck

### ISSUE THREAD

**Issue by ori-n** [dbeaver/dbeaver#19193]
### Description

I'm having the same issue as https://github.com/dbeaver/dbeaver/issues/7466 - I can authenticate and execute a query, but the results are never returned. If I look in Athena's history, I see that my query returned very quickly with the proper results.

DBeaver continues to spin, as if it's waiting for results, until it finally times out.
It started to happen after I upgraded DBeaver

### DBeaver Version

Community Edition 22.3.5

### Operating System

mac OS

**Comment by serge-rider** [comment]
Could you check what exactly DBeaver is doing in the Query Manager? https://github.com/dbeaver/dbeaver/wiki/Query-Manager

Enable all query types including metadata reads.

**Comment by ori-n** [comment]
I checked and the problem no longer exists - maybe a restart solved it. I believe the issue is related to the output dir since the connection was made. If I will have more info I'll share

**Comment by LonwoLonwo** [comment]
Thanks for the answer @ori-n 

For now, I'm closing the ticket. Feel free to create a new one if the issue occurs again.
