### ISSUE TITLE
"Advanced copy" copies thousand separator as comma

### ISSUE THREAD

**Issue by Radziasss** [dbeaver/dbeaver#19209]
### Description

After I select a set of IDs (INTEGER values) from retrieved table data and use option: _Advanced copy -> Advanced copy..._ it copies values with thousand separator as comma.

When I use standard _Copy_ option, this separator is not copied, what is ok.

**Example**
I selected following set of IDs:

**300
3,567
4,678**

When I select and copy them with _Advanced copy_ (+ comma as row delimiter) I receive the following result:
**300,3,567,4,678**

What I would expect:
**300,3567,4678**

### DBeaver Version

Community 22.3.5.202302171528

### Operating System

Windows 10

### Database and driver

Firebird

### Steps to reproduce

1. Select table column with INTEGER data (numbers >= 1000) from database
2. Select (highlight) results (more than 1)
3. Use Advanced copy option under right mouse click
4. Paste data anywhere
5. Thousand separator was copied as "," (comma)

**Comment by Destrolaric** [comment]
@Radziasss Could you try selecting native as value display format in an advanced copy
![image](https://user-images.githubusercontent.com/20579256/225629982-66f9abeb-3334-4176-9afc-70d4d1e23f1b.png)

**Comment by Radziasss** [comment]
@Destrolaric After selecting "Database native" it works as expected. Thank you 👍
