### ISSUE TITLE
Unable to zoom image in value panel on macOS and Linux

### ISSUE THREAD

**Issue by aspatzier** [dbeaver/dbeaver#19204]
### Description

When I view an image in the  value panel all buttons - like zoom - are missing.

Is this a bug (I don't find a way to show or hide buttons...)?

### DBeaver Version

22.3.5 (latest version)

### Operating System

macOS 13.1 Ventura

**Comment by serge-rider** [comment]
DBeaver uses embedded web browser to view imagaes. You can use standard browser methods like mouse wheel+ctrl or <kbd>ctrl +</kbd> and <kbd>ctrl -</kbd>.

You can also switch to old UI in preferences.

**Comment by arhayka** [comment]
@CommunyAS Thank you for your report.
We need to fix this issue on macOS and Linux.

**Comment by flambchap** [comment]
The mentioned shortcut and zoom with scroll button do not for on Unix.

**Comment by ShadelessFox** [comment]
We can't control the zoom level of the browser view.

The workaround is to disable the browser-based image viewer:

![image](https://user-images.githubusercontent.com/35821147/224359743-1a9bb10f-1eaf-41df-83b7-54e150e62b67.png)
