### ISSUE TITLE
Database Navigator View: cannot create connections/folder on top level, cannot move folders/connections

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#19200]
### Description

Database Connection View: 
I cannot create elements (connections or folders) on the top level anymore -- anything I create ends up in the top-most folder instead.

While trying to move the newly created folder out of the folder In accidentally moved an already existing connection into it and cannot move it out of that folder either.

Before:
```
[Folder A]
|-- Connection 1
```

After creation of new folder in supposedly top level:
```
[Folder A]
|-- [Folder B]
|-- Connection 1
```

After accidentally moving the existing connection:
```
[Folder A]
|-- [Folder B]
          |-- Connection 1
```

There seems to be no way to move elements out of their containing folders anymore.

### DBeaver Version

Community Edition Version 22.3.5.202302171528

### Operating System

Linux 

### Steps to reproduce

1. make sure not to select anything in DB Connection View
2. click on white space below last existing element
3. context menu: Create -> New folder ...
4. folder appears in top-most folder instead
5. select and move, drop does not work, folder stays in wrtong place

**Comment by Destrolaric** [comment]
Can you please provide footage showing your issue? Thank you.

**Comment by E1izabeth** [comment]
It's been a long time since no update here. Please let me know, if it's still actual for you and provide additional information.
