### ISSUE TITLE
Cannot see icons when edit connetion

### ISSUE THREAD

**Issue by zhuwenbing** [dbeaver/dbeaver#1920]
system : windows 7 64bit
dbeaver version : 4.1.0 or 4.1.1
scene : when right click and chose edit connetion, the dialog poped, but the icons 'OK', 'Cancel' and 'Test Connection...' were disappeared, you must change the dialog's size, then the icons came back.
![Uploading image.png…]()

**Comment by serge-rider** [comment]
1. Please post screenshot again.
2. Does this happen every time or problem disappears after you resize dialog

**Comment by ceyhunnabiyev** [comment]
Hi @serge-rider,  Same issue on me with Manjaro Linux , when I maximize this, issue disappeared. It  occurs with any size of the dialog window, except maximized. I use Gnome Desktop 3.24.2.

**Comment by ceyhunnabiyev** [comment]
Sorry for wrong comment,  the problem disappears when it is resized, only occurs when edit connection is clicked

**Comment by serge-rider** [comment]
Still can't reproduce this (on Windows, Mac or Ubuntu).

Could you make a screenshot? 
Maybe some other details?

**Comment by zhuwenbing** [comment]
I've made a video for it, please check it out from here: https://github.com/zhuwenbing/zhuwenbing.github.io/blob/master/reproduce.wmv
@serge-rider

**Comment by uslss** [comment]
cannot reproduce on 6.0.2
