### ISSUE TITLE
Want to enhance the sorting function

### ISSUE THREAD

**Issue by z-hanzhe** [dbeaver/dbeaver#19210]
**The content is translated by Google, please forgive me if the description is wrong**

When you open the database to view all tables, or view table properties, you can sort by display or column name by clicking the table header, but once sorted, you can only sort in ascending or descending order, and the original order cannot be restored. I hope that the sorting function can be enhanced. Revert sorting in addition to ascending and descending

![image](https://user-images.githubusercontent.com/58802604/221802161-1b19b938-140e-4337-96ec-417e2857e3ec.png)

![image](https://user-images.githubusercontent.com/58802604/221801943-e7ee2d97-b44c-4182-a302-b9f4bf9227b5.png)

**Comment by E1izabeth** [comment]
Thank you for feature request.

**Comment by arhayka** [comment]
We decided to fix this issue in the following way:

1. When clicking on a column header, sort the column ASC (just like now)
2. On a second click, sort it DESC (just like now)
3. On the third click return the original order
