### ISSUE TITLE
Unable to import csv/txt file containing varchar data type into trino database

### ISSUE THREAD

**Issue by nguyenann13** [dbeaver/dbeaver#19219]
[###](url) Description

When importing a txt or csv file containing varchar data types, DBeaver will error out during import with "Object parameter [column value] binding not supported.

![image](https://user-images.githubusercontent.com/24360724/221951346-543b14f9-b2b8-435d-92ec-82037a24e4e0.png)

txt file used as example
![image](https://user-images.githubusercontent.com/24360724/221951433-cd699a26-8bad-4cdc-9199-6ef3f28e3b5e.png)

Data Transfer Import Settings
![image](https://user-images.githubusercontent.com/24360724/221951615-6ae69e62-6765-476f-bcf5-35a23967ab4b.png)

Metadata structure
![image](https://user-images.githubusercontent.com/24360724/221951688-269e0e3b-0646-4e41-ac9c-334f476174d0.png)

Data Load Settings
![image](https://user-images.githubusercontent.com/24360724/221951776-e34f99ea-9a27-4d0c-8524-5e1ae73123bc.png)

Error
![image](https://user-images.git
[test_tab_delimit.txt](https://github.com/dbeaver/dbeaver/files/10853941/test_tab_delimit.txt)
hubusercontent.com/24360724/221951869-582bff85-b7ab-4753-ac2e-14c51dd34e75.png)

### DBeaver Version

Community 22.3.5

### Operating System

Windows 10 Enterprise

### Database and driver

Trino 383

### Steps to reproduce

1. Right click schema and click import data
2. Select CSV as source and click next
3. Select a txt file and click Next
4. Click next in the table mapping
5. Click Next  in Data load settings
6. Click next in Confirm
7. Click Proceed
8. Error will pop up regarding Object parameter binding not supported

**Comment by LonwoLonwo** [comment]
Hello @nguyenann13 

Both your issues have one problem - for some reason, the varchar type returned from a driver as an unknown type data type:

![2023-03-01 16_28_16-DBeaver Ultimate 23 0 0 - com sun management_type=diagnosticcommand](https://user-images.githubusercontent.com/45152336/222152728-d787b778-5016-493d-be5f-8a34137a43ea.png)

So we need to check why.

**Comment by LonwoLonwo** [comment]
Yeh, I see; varchar returned as a JAVA_OBJECT. We may need to override the resolveDataKind method for Trino.

**Comment by xxcocoymlxx** [comment]
@LonwoLonwo  Hello, I'm seeing the same issue in Dbeaver with Presto. Could you check please?
<img width="813" alt="Screenshot 2023-11-23 at 3 13 27 PM" src="https://github.com/dbeaver/dbeaver/assets/43554506/ef1d6ecf-e292-4671-928a-043b3776ae6a">
