### ISSUE TITLE
Connection problem with ODBC and a Faircom (cTree) database driver 

### ISSUE THREAD

**Issue by bozo88** [dbeaver/dbeaver#19221]
### Description

Hi

Trying to get an ODBC connection to a Faircom (ctree) database working with dbeaver. 

The driver works in Excel (64 bit) with no issues. And I have been able to connect via a different SQL tool (FlySpeed) at 32 bits in case of a 32/64 bit issue.

Unsure if this a dbeaver issue or a java jdbc-odbc-bridge-jre7.jar issue or JdBCOdbc.dll issue.

### DBeaver Version

Community Edition 22.3.5.202302171528

### Operating System

Windows 10

### Database and driver

Attache database but built on Faircom ctree technology.

The driver is the latest official Attache ODBC drivers - both 32 and 64 bit

[dbeaver-debug-1677627105379.log](https://github.com/dbeaver/dbeaver/files/10855690/dbeaver-debug-1677627105379.log)

### Steps to reproduce

I have a 64 bit ODBC connection created under Windows ODBC manager.

I have created a connection in dbeaver that uses this connection 

In connecting to the database I see first this (which goes away on subsequent attempts)
`class sun.jdbc.odbc.JdbcOdbcDriver (in unnamed module @0x51841f7c) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x51841f7c`

and then this 
`[FairCom][ODBC FairCom Driver 11.2.2.22002(Build-170117)] -305 Driver does not support values exceeding 32 bits`

A connection is established. The tables names are shown but the field names and other meta data is scrambled (if there at all)

SQL SELECT statements will execute but the data return is corrupt.

**Comment by serge-rider** [comment]
This problem will be fixed in the next version (23.0) along with Java version update

**Comment by LonwoLonwo** [comment]
Hello @bozo88

Can you please check your issue with the latest [DBeaver version](https://dbeaver.io/download/)?

**Comment by bozo88** [comment]
Hi

Still having the same problem after upgrading to 23.0.0

Something has been fixed. Previously I was able to view "corrupt" data. Now I can't even connect to view anything.

The error message is still the same. 
`[FairCom][ODBC FairCom Driver 11.2.2.22002(Build-170117)] -305 Driver does not support values exceeding 32 bits`

Thanks

**Comment by Destrolaric** [comment]
@bozo88 Hi, we recently created a new JDBC-ODBC bridge driver for EE. You could try if it works for you by signing up for the 14-day free trial

**Comment by bozo88** [comment]
Hi

Downloaded and installed dbeaver EE (as a trial) but still having same issue.

Have just downloaded and installed dbeaver community and see this first or the 305 error.
![image](https://user-images.githubusercontent.com/126627143/231018443-bddafcfb-2193-418b-83d9-ed11c55f8a54.png)

Eventually I can sort of connect but seeing this sort of thing in the data tables 
![image](https://user-images.githubusercontent.com/126627143/231019147-12fb9468-2ba6-4c3f-84c3-e815bd134a3b.png)

Thanks

**Comment by flambchap** [comment]
Hi @bozo88. Judging from the exception, you tried to use the same deprecated driver. Please create a ticket on our online support system on our website: https://dbeaver.com/submit-ticket/. We'll suggest you the correct driver and extend your trial license.

**Comment by pauljohnyap2023-blip** [comment]
Hi, I am using ctreesql as thg db for our attache payroll system. The odbc connection was working fine, unfortunately for some reason, the connection is not working when refreshing the template, prompting with [FairCom][ODBC FaiCom Driver 11.2.2.22002(Build-170117)][ctreeSQL]-20228 Access denied(Authorization failed). The strange thing is, this error applies when connecting to one table. Otherwise, odbc connection to other tables under the same schema works fine. I was assuming this could related to the permission issue on this specific table that must have been reset. Someone with similar issue and any fix for this? Thank you
