### ISSUE TITLE
[request] Add the ability to change an Oracle expired password

### ISSUE THREAD

**Issue by dariopnc** [dbeaver/dbeaver#1922]
I found this [thread](http://dbeaver.jkiss.org/forum/viewtopic.php?f=3&t=1889) in the old forum while googling a solution for the same problem.

I suppose this request is still valid, due to the fact that I've still not found a solution

**Comment by serge-rider** [comment]
Yep, this still makes sense

**Comment by jerherder** [comment]
Hello 

have you news for this request?

Kind regards

**Comment by jerherder** [comment]
hello

i have found. 

kind regards

**Comment by dhergert** [comment]
I could see this as being a useful feature. I'd consider helping but not sure where to even start in the codebase.  And as far as implementation, could this be a new button on the Connection Info dialog?

**Comment by uslss** [comment]
#9869
