### ISSUE TITLE
Support artifact classifier when downloading driver files from Maven

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/dbeaver#19222]
**Is your feature request related to a problem? Please describe.**
ClickHouse JDBC driver supports multiple protocols(http, tcp, and grpc), hence it comes with multiple classifiers for user to choose. As of now, DBeaver does not support user to specify classifier when downloading driver files from Maven.
![image](https://user-images.githubusercontent.com/4270380/222029957-32ed9efb-9bcb-4063-8d54-1f0f1f0f77fd.png)

**Describe the solution you'd like**
It would be great if we can add one more dropdown list next to `Version` column shown above to allow user to select classifier(e.g. `all`, `cli`, `grpc`, and `http` for ClickHouse, and perhaps empty for others)

**Describe alternatives you've considered**
N/A.

**Additional context**
The discussion started with a bug reported at ClickHouse/clickhouse-java#1257.

**Comment by ShadelessFox** [comment]
Hello @zhicwu,

Thanks for filing a feature request.

Note: specifying the classifier via code in the `plugin.xml` is possible, but it can't be changed via UI. In fact, after opening the edit dialog and saving changes, the classifier is lost.
