### ISSUE TITLE
Import data - Target Type not translating to Target DDL statement

### ISSUE THREAD

**Issue by nguyenann13** [dbeaver/dbeaver#19220]
### Description

When doing a import data the Target Type is not translating over to the Target DDL correctly.

![image](https://user-images.githubusercontent.com/24360724/222009454-8abb341d-ce64-4a0c-b44a-061a7fc70c3a.png)

if I add a space between the datatype and the length it will then translate correctly. Ex. varchar (50).

![image](https://user-images.githubusercontent.com/24360724/222009812-2ce9f455-f2ae-49d5-bf2f-4be7d32617e1.png)

This is not feasible to correct one at a time when I import large horizontal datasets.

### DBeaver Version

Community 22.3.5

### Operating System

Windows 10 Enterprise

### Database and driver

Trino 383

### Steps to reproduce

1. Import data using attached text file
2. In Tables Mapping window, click Configure - see Target Data Type and click the Target DDL tab to see that the data type is different.

[test_tab_delimit.txt](https://github.com/dbeaver/dbeaver/files/10855735/test_tab_delimit.txt)

**Comment by LonwoLonwo** [comment]
Thanks for the report. Will be fixed with this ticket: https://github.com/dbeaver/dbeaver/issues/19219
