### ISSUE TITLE
MSSQL Driver

### ISSUE THREAD

**Issue by fluchette** [dbeaver/dbeaver#19225]
### Description

Hello, i have a problem with the sql driver in new version of dbeaver enterprise (23.0 – 2023-02-28 20:38:32)

Problem that didn’t exist before.

Thanks

![image](https://user-images.githubusercontent.com/29701933/222095187-4e027785-2214-4239-bf9f-4d354ede588f.png)

### DBeaver Version

Enterprise 23.0

### Operating System

Windows 11

**Comment by serge-rider** [comment]
Version 23.0 is not released yet (you probably use EA version). This problem will be fixed in the final release. 
Thanks for the bug report.
