### ISSUE TITLE
Add session information from sys.processlist to MySQL Session Manager 

### ISSUE THREAD

**Issue by yoni-yad2** [dbeaver/dbeaver#19234]
**Is your feature request related to a problem? Please describe.**
I would like to see more session information like program name and statement stats in Session Manager

**Describe the solution you'd like**
Add columns to Session Manager from sys.processlist
using this query:

```
select ip.*,sp.statement_latency,sp.progress,sp.lock_latency,sp.rows_examined,sp.rows_sent,sp.rows_affected,sp.tmp_tables,sp.tmp_disk_tables,sp.full_scan,sp.last_statement,sp.last_statement_latency,sp.current_memory,sp.last_wait,sp.last_wait_latency,sp.source,sp.trx_latency,sp.trx_state,sp.trx_autocommit,sp.pid,sp.program_name from information_schema.PROCESSLIST ip
left join sys.processlist sp on sp.conn_id=ip.ID
```

**Describe alternatives you've considered**
Querying sys.processlist manually

**Comment by LonwoLonwo** [comment]
Hello @yoni-yad2 
Thanks for the idea.
We can only add some of these columns in our current session manager - we need more space. But you can choose 5-6 more informative columns - they will be visible, and others will be hidden.

**Comment by yoni-yad2** [comment]
Can you add all the columns but hide them by default (except program_name which should it visible) ?
The user can configure which one he wants to see and use the horizontal scroll bar to see them.

**Comment by LonwoLonwo** [comment]
Yes, this is the plan. But please feel free to recommend columns that will be visible.

**Comment by yoni-yad2** [comment]
I suggest:
thd_id, pid, program_name, current_memory, trx_state, trx_autocommit
