### ISSUE TITLE
Import CSV File into MariaDB - Tries to import the whole file at once

### ISSUE THREAD

**Issue by adexios** [dbeaver/dbeaver#19236]
### Description

With an older version of DBeaver, I was able to import a large (1 million row) CSV file successfully into MariaDB.
It would insert the rows into the database table as they loaded, not try to load them all at once.

Now it's trying to load the entire file at once and no rows are being inserted at all. Finally, there's a java heap exception because it runs out of memory.

No surprise since it's not properly flushing the data.

This seems like a bug - and it didn't exist as of one of the versions I had last year. (Just updated - not sure which version I had previously, but the new version has the error)

### DBeaver Version

Community Edition 22.3.5.202

### Operating System

Windows 10

### Database and driver

1. MariaDB (10.5.16-MariaDB)
2. MariaDB driver (mariadb-java-client-3.0.7.jar)

### Steps to reproduce

1. I have a large CSV file (849 megabytes)
2. I try to insert this CSV file into MariaDB into an existing table with existing column mappings
3. No matter what settings I chose, it will run until it blows up, having inserted 0 records.

I know I can increase the memory size for the app, but wouldn't it be better to insert the records as it goes?

**Comment by LonwoLonwo** [comment]
Hello @adexios 

What settings do you have in the `performance` section? Are transactions enabled? 

![2023-03-02 13_10_06-DBeaver Ultimate 23 0 0 - Sessions - MariaDB 10 6 1](https://user-images.githubusercontent.com/45152336/222399122-b55be5fa-7515-478b-b663-17355c423966.png)

Please provide a screen of this page.
Also, did you try to use multi-insert?

**Comment by adexios** [comment]
Thanks for the fast reply!

I tried every combination of settings - transactions or no transactions.
Multi-insert, no multi insert. It refuses to insert records as it loads
them. I even tried switching to an earlier version of the Maria database
driver. Nothing seems to change the result. Any ideas?


Thanks!
- Paul

**Comment by adexios** [comment]
I just realized that this particular database was not migrated to MariaDB.

This is a MySQL database.  Version of the connector is 8.0.29. Still an
issue, just the wrong database in the title.

**Comment by Matvey16** [comment]
I was not able to reproduce it. Can you specify which error stops the import and why do you think the file size matters?

**Comment by E1izabeth** [comment]
It's been a while since no update here. Please let me know if the issue is still actual and provide additional information.
