### ISSUE TITLE
Multiple false prompts leads to locking of account

### ISSUE THREAD

**Issue by romit7** [dbeaver/dbeaver#19235]
### Description

I generally connect to redshift in corporate aws cloud via DBeaver by enabling ssh in the configuration via tunneling to a bastion server. I first connect to ssh on bastion server and then to the Redshift Database. If I leave the DBeaver for few mins and work somewhere while the editor is still open. It prompts me to enter the sso password and then passcode. Even if I enter the correct sso password, it still prompts me to enter again and like this, it goes on and on and after multiple prompts it locks me out for 15 mins. After 15 mins, I need to close the window and open the configuration, test the tunnel connection and then test the redshift connection. This time all works fine. But in idle time, it prompts multiple times and even if I cancel it still locks me out. This I think is a bug , let me know if anything can be done about it in Dbeaver

### DBeaver Version

Community Edition 22.3.4.202302060909

### Operating System

Windows10

### Database and driver

1. Redshift
2. Driver name - com.amazon.redshift.jdbc42.Driver

### Steps to reproduce

1. Connect to Redshift 
2. open sql editor
3. remain idle for few hrs
4. come back to the editor
5. It prompts for password
6. It doent take correct password
7. prompts for password again
8. I cancel it, but the prompt keeps coming back
9. ultimately it locks me out of the account

**Comment by serge-rider** [comment]
Thanks for the report.

Coukd you provide additional info:
- What type of authentication do you use?
- How does this password prompt looks like?

Some screenshots would be very useful

**Comment by E1izabeth** [comment]
It's been a long time since no update here. Please let me know if it's still actual and provide additional info.
