### ISSUE TITLE
Cannot connect to Sql Server, "SQLServerDriver has been compiled by a more recent version of JRE"

### ISSUE THREAD

**Issue by piotrek-k** [dbeaver/dbeaver#19230]
### Description

I'm trying to connect to MS SQL Server. I've opened "Connect to a database" window ("File -> New -> Database Connection -> SQL Server"), then selected "Host" option, provided Host URL, port and "Windows authentication" and then clicked "Finish".

Here is what I see when I try to enter this newly created database.

![image](https://user-images.githubusercontent.com/5506878/222175613-c4ab235e-fea2-4570-9c82-766b5ea27dbe.png)

> com/microsoft/sqlserver/jdbc/SQLServerDriver has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

> Can't create driver instance
>   Error creating driver 'MS SQL Server / SQL Server' instance.
> Most likely required jar files are missing.
> You should configure jars in driver settings.
> 
> Reason: can't load driver class 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
>     com/microsoft/sqlserver/jdbc/SQLServerDriver has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

As far as I can see in "Database -> Driver manager", there is a MS SQL Driver installed:
![image](https://user-images.githubusercontent.com/5506878/222177461-a416a20f-8ca9-4caf-8f45-63a647b4e3ca.png)

I've tried to delete it and install again, but it didn't help.

### DBeaver Version

Comunity Edition Version 23.0.0.202302281827

### Operating System

Windows 10

### Database and driver

1. Database: SQL Server 15.0.4261.1
2. Driver: Microsoft JDBC Driver for SQL Server (MSSQL)

### Steps to reproduce

1. Fresh install of DBeaver
2. Try to connect to SQL Server

**Comment by jdeppa** [comment]
Same for "Azure SQL Server" driver and "MS SQL Server (Old driver, MS)" driver, but I'm able to connect with "MS SQL Server (Old driver, jTDS)" driver.

**Comment by LonwoLonwo** [comment]
Hello

A few versions DBeaver have Java 17, and the driver version was for java 17. We returned to Java 11, so you must return your driver to version jre11.

![2023-03-02 12_46_30-DBeaver 23 0 0 - _postgres 2_ Script-18](https://user-images.githubusercontent.com/45152336/222393269-27270fd9-bc89-455d-8994-d041a41e7817.png)

**Comment by AMD-wangjason** [comment]
I ran into the same error, fixed it by manually changing jdbc version from 11.2.3.jre17 to 11.2.3.jre11
Though I don't like the way DBeaver making arrogant changes while leaving ambiguous message/solution
![image](https://user-images.githubusercontent.com/66396454/222996693-e36cdfdc-4897-4948-b4d4-b3aba65626eb.png)

**Comment by serge-rider** [comment]
This issue was fixed in DBeaver 23.0. Now default driver version is for jre11.

**Comment by AsparagusEduardo** [comment]
> This issue was fixed in DBeaver 23.0. Now default driver version is for jre11.

Except it doesn't switch when updating from `22.3.x` (I forget which patch version I had), had to look this up when I had this same issue.

**Comment by artulance** [comment]
> I ran into the same error, fixed it by manually changing jdbc version from 11.2.3.jre17 to 11.2.3.jre11 Though I don't like the way DBeaver making arrogant changes while leaving ambiguous message/solution ![image](https://user-images.githubusercontent.com/66396454/222996693-e36cdfdc-4897-4948-b4d4-b3aba65626eb.png)

this worked for me in DBeaver 23.0 thanks!

**Comment by zeljan1** [comment]
Same problem here but under linux. Linux Mint 20.3, after update to 23.0 cannot connect to mssqldb anymore (same error message as in issue title). I cannot change version like under windows, no way to connect. Anyone can help ?
EDIT: Forget, I've resolved it by manually downloading version 22.3.5 and downgrading package. Now it works fine :)
