### ISSUE TITLE
dBeaver doesn't allow table changes in foreign table in postgresql

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#19231]
### Description

dBeaver apparently doesn't know how to correctly generate SQL needed to alter or update foreign tables in PostgreSQL.
If you have a foreign table in PostgreSQL and you use dBeaver to add a new column, alter an existing column, etc. it fails because dBeaver apparently doesn't know how to generate the proper SQL statements.  At least in PostgresQL.

Ex:  I have a foreign table named foo and I want to add a new column named test.  This is the SQL the dBeaver GUI generates when you go to persist the change:
`ALTER TABLE bar_fdw.foo ADD test varchar NULL;`

what it should have generated is:
`ALTER FOREIGN TABLE bar_fdw.foo ADD test varchar NULL;`

So every time one tries to use dBeaver to manage foreign tables, it fails.  Typically with the error:
"Table bar_fdw.foo doesn't exist."

Can someone look into fixing dBeaver's inability to work with PostgreSQL foeign tables correctly?

thanks.

p.s. it may or may not be related to this existing issue https://github.com/dbeaver/dbeaver/issues/16372 from back on 2022-04-29, but at a minimum it demonstrates that dBeaver still wants to conflate these vastly different object types together.

### DBeaver Version

Community Edition 22.3.5.202302171528

### Operating System

Windows 10

### Steps to reproduce

1. View Table on a foreign table in a PostgreSQL database
2. Attempt to do anything with the DDL of that table (add column, alter column, drop column, etc.)
3. Hit the save button
4. See that the presented SQL to persist this change is incorrect
5. Watch the database throw an error because dBeaver generated invalid SQL

**Comment by LonwoLonwo** [comment]
Thanks for the report @coleman-rik 

For now, we have support for the DROP and CREATE statements

![2023-03-02 12_53_50-Delete script](https://user-images.githubusercontent.com/45152336/222395389-fda4fdc5-9477-43bc-b28f-985479e356a8.png)

but not for the ALTER. https://www.postgresql.org/docs/current/sql-alterforeigntable.html

We need to add this case into the syntax.


Important note: ALTER TABLE, in some cases, can work for foreign tables

![2023-03-02 12_55_50-DBeaver Ultimate 23 0 0 - fb_test_table2](https://user-images.githubusercontent.com/45152336/222395938-244bacfd-b3d8-4047-84a0-58f201d86aa1.png)

**Comment by coleman-rik** [comment]
thanks, it's rather muddled at the moment.  I believe that if dBeaver can't do something correctly, then it would be better if it didn't let you instead of the current behavior which is to try and do it incorrectly and let the database cluster throw errors.  I am not sure which RDBMS allows ALTER TABLE to work on foreign tables, but I've never seen a correctly configured PostgreSQL cluster (from 8-15) allow that.

I believe a major failing in dBeaver with regards to foreign tables is it's insistence in treating them like regular tables.  dBeaver lumps them with normal tables, only differentiating them by a very slight icon change and wants to use the same SQL that's valid for standard tables on foreign tables, which isn't valid, at least not in PostgreSQL's case.

I am seeing a similar thing with roles, and have already entered a bug report there, in that roles in PostgreSQL are cluster wide, yet dBeaver restricts them to database level in the UI.  While the vast majority of objects, idioms, and SQL are standard across RDBMS' not everything is.  Trying to force them to adhere to the most common is bound to generate confusion and errors.

I do hope this can be straightened out soon as foreign servers, tables, views, etc. are a large part of the structure in all of the dozens of databases I manage.

thanks.
