### ISSUE TITLE
Improve Dark Theme

### ISSUE THREAD

**Issue by GeorgeSalu** [dbeaver/dbeaver#19249]
### Description

![image](https://user-images.githubusercontent.com/9308386/222588532-50f60e55-6f94-4353-9a80-b1a0f252f1e6.png)

### DBeaver Version

22.3.5.202302171528

### Operating System

Linux Mint 20.3 x86_64 Xfce

**Comment by E1izabeth** [comment]
Have you tried [Darkest Dark theme](https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle) extension?
https://dbeaver.com/docs/wiki/Eclipse-extensions/

**Comment by E1izabeth** [comment]
It's been a long time since no update here. If you have any questions, please let me know.
