### ISSUE TITLE
 How to avoid triggering Metadata queries - Teradata

### ISSUE THREAD

**Issue by j46374** [dbeaver/dbeaver#19245]
### Description

DBeaver is submitting metadata queries in some cases. Some examples of queries are here. This is impacting the user experience. Is there a way to avoid this extraneous metadata queries against the database and get the metadata from the resultset?

========================================================================================
`SELECT DATABASENAME AS TABLE_SCHEM, CAST(null AS varchar(30)) AS TABLE_CATALOG FROM DBC.DatabasesV ORDER BY DATABASENAME;`

`SELECT CAST(NULL AS VARCHAR(100)) AS TABLE_CAT, DATABASENAME AS TABLE_SCHEM, TABLENAME AS TABLE_NAME, CAST((CASE WHEN TABLEKIND = 'V' THEN 'VIEW' WHEN COMMITOPT IN ('D','P') THEN 'GLOBAL TEMPORARY' ELSE 'TABLE' END) AS VARCHAR(100)) AS TABLE_TYPE, COMMENTSTRING AS REMARKS, CAST(NULL AS VARCHAR(100)) AS TYPE_CAT, CAST(NULL AS VARCHAR(100)) AS TYPE_SCHEM, CAST(NULL AS VARCHAR(100)) AS TYPE_NAME, CAST(NULL AS VARCHAR(100)) AS SELF_REFERENCING_COL_NAME, CAST(NULL AS VARCHAR(100)) AS REF_GENERATION FROM DBC.TablesV WHERE DATABASENAME (not casespecific) like 'AGENT_VIEWS' (not casespecific) escape '\' AND TABLENAME (not casespecific) like 'AGENT_VIEWS' (not casespecific) escape '\' AND ((DATABASENAME = 'DBC' AND TABLEKIND IN ('O','T','V'))  OR  TABLEKIND IN ('O','T')  OR  TABLEKIND = 'V' )  ORDER BY TABLE_TYPE, TABLE_SCHEM, TABLE_NAME;`

### DBeaver Version

Community Edition Version 22.3.2.202301060755

### Operating System

Mac OS Ventura 13.2

### Database and driver

1. Database name and version: Teradata 17.20
2. Driver Name and version: terajdbc4.jar 17.10.00.27
3. Java version : 17

### Steps to reproduce

1. Connect to database and run a few queries. Inspect the queries submitted by the tool to database (from DBQL logs)
2. Check if there are any extra meta data queries.

### Additional context

To avoid possible metadata queries, following items are disabled.
1. Code completion
2. Invalidate connection before execute
3. Refresh active schema after SQL Execution

**Comment by LonwoLonwo** [comment]
Hello @j46374 

To know the source or ResultSet attributes DBeaver must know all about the tables in the statement. 
Otherwise, DBeaver cannot give complete information about the primary/unique keys inside the result, foreign keys and connections with other tables, and the types of columns.

The only that you can do - is disable key reading. But it will not prevent tables and columns reading.

**Comment by E1izabeth** [comment]
It's been a long time since no update here. Please let me know, if it's still actual for you and provide additional information.
