### ISSUE TITLE
Cannot uninstall (cannot run uninstall.exe)  "App can't run on your PC"

### ISSUE THREAD

**Issue by afregeau** [dbeaver/dbeaver#19248]
### Description

![image](https://user-images.githubusercontent.com/117488089/222553732-842a04f5-f805-4d17-8f85-f86b3ea3cad6.png)
 
This is from a clean install maybe 1 hour ago,

### DBeaver Version

Community 22.3.5

### Operating System

Windows 11 Version	10.0.22621 Build 22621

### Steps to reproduce

For me, run the installer for 'all users'
Attempt to run the uninstaller. 
Same issue occurs when uninstalling through windows "add/remove programs"

**Comment by E1izabeth** [comment]
Where do you get installer? Did you download it from our website [dbeaver.io](https://dbeaver.io/), or installed from Microsoft Store, or via some package manager?

**Comment by afregeau** [comment]
Sorry, should have added.

I installed using the [Windows (installer)](https://dbeaver.io/files/dbeaver-ce-latest-x86_64-setup.exe) on the dbeaver.io site

**Comment by ShadelessFox** [comment]
Hello @afregeau,

Please try upgrading to a newer version and uninstalling it afterward.

If it didn't help, please ensure your antivirus doesn't block the executable file.

Please let me know if it helps.

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
