### ISSUE TITLE
SSHJ authentication does not work without saving passphrase locally

### ISSUE THREAD

**Issue by HendrikJan** [dbeaver/dbeaver#19243]
### Description

If I leave the passphrase empty in the settings, DBeaver does not ask me for a passphrase, but instead gives me an error.

I created a new private/public key pair using `ssh-keygen -t ed25519 -b 4096  -C "comment"`.  
I can connect to the server using SSHJ and setting a passphrase:  

![image](https://user-images.githubusercontent.com/2218920/222404376-505321a6-ad31-4c5d-ab91-b550a55817ad.png)

Before (using JSch) I could leave the passphrase empty and I was asked for my phrase everytime I wanted to open the database.

Now, (using SSHJ, because JSch fails) I cannot leave the passphrase empty:  

![image](https://user-images.githubusercontent.com/2218920/222405255-bd5ed62e-1618-4561-a3a4-66eb74d9a9a8.png)

If I leave the passphrase empty, then I get this error: "Decryption of the key failed. A supplied passphrase may be incorrect."
DBeaver did not ask me for a passphrase.

### DBeaver Version

Community Edition Version 22.3.5.202302171528

### Operating System

Ubuntu 22.04.1 LTS

### Database and driver

1. Database name and version: 10.6.12-MariaDB-0ubuntu0.22.04.1
2. Database driver: com.mysql.jdbc.JDBC4CommentClientInfoProvider

### Steps to reproduce

1. Create a keypair using `ssh-keygen -t ed25519 -b 4096  -C "comment"`
2. Go to Edit Connection > SSH
3. In advanced settings choose `Implementation: SSHJ`
4. In settings set Passphrase: "" (empty)
5. In settings make sure "Save Password/Passphrase" is not checked
6. Try to open the connection
7. See the error appear "Decryption of the key failed. A supplied passphrase may be incorrect."

**Comment by Destrolaric** [comment]
Thank you for your report.

**Comment by txdFabio** [comment]
same issue, I'm unable to use a password-protected key without saving the pass-phrase to dbeaver

**Comment by Destrolaric** [comment]
@HendrikJan Hi, we recently updated our ciphers. Could you see if it still happens in recent versions?

**Comment by txdFabio** [comment]
> @HendrikJan Hi, we recently updated our ciphers. Could you see if it still happens in recent versions?

now it works, asking for private key password, thanks!

**Comment by Matvey16** [comment]
Verified

**Comment by HendrikJan** [comment]
Confirmed -- working nicely now.
Thanks for fixing, and thanks for closing this issue :-)
