### ISSUE TITLE
dBeaver improperly doing SQL Transform on pasted data

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#19250]
### Description

When I copy/paste data in the editor containing double quotes ", dBeaver insists on improperly stripping the double quotes from the pasted content.  While there is a fleeting pop up on the lower right of the screen offering to undo this, it shouldn't be doing so by default, if at all.  These double quotes are critical to the SQL statements that I am trying to run.

### DBeaver Version

Community Edition 22.3.5.202302171528

### Operating System

Windows 10

**Comment by E1izabeth** [comment]
Could you provide some minimal query example to reproduce the issue?

**Comment by coleman-rik** [comment]
> grant wow to "j.smith", "m.robertson";

select from the first " before j to the end of the last " in robertson
paste after the to in the below statement
> grant sad to 

get 
> grant sad to j.smith, m.robertson;

followed by a popup stating that the source was automatically reformatted and to press here to undo
If I Ctrl-Z I can undo the reformatting.

**Comment by E1izabeth** [comment]
Am I doing this wrong? I can't reproduce


https://user-images.githubusercontent.com/28875055/225581125-2a2cf4c2-4c24-485c-99ae-49d9705358df.mp4

**Comment by coleman-rik** [comment]
probably not, it's an intermittent thing.

**Comment by LonwoLonwo** [comment]
Could you please disable this setting and try again?

![2023-03-23 16_39_32-Window](https://user-images.githubusercontent.com/45152336/227221798-57ea90b4-339a-4320-99dd-26cefb39053b.png)

**Comment by coleman-rik** [comment]
@LonwoLonwo it _seems_ to have fixed the problem, only now the first couple of times I paste it freezes the UI.  If I try to click in it, it goes white with the "Not Responding"  message.  A few seconds later it finishes.
If I paste the same string repeatedly, I don't get the delay.

thanks.

example used for test:
`select "foo", "bar", "latest.happiness" from test_dummy;`
wrote **select** on the next line, selected "foo", "bar" and pasted it after the bare select statement.
