### ISSUE TITLE
DBeaver does not show materialized views in YugabyteDB

### ISSUE THREAD

**Issue by fritshoogland-yugabyte** [dbeaver/dbeaver#19255]
### Description

When I create a materialized view, this shows up as materialized view in PostgreSQL, but when trying on YugabyteDB, the materialized view folder does not show?

### DBeaver Version

Version 22.3.5.202302180832

### Operating System

ProductName:	macOS ProductVersion:	12.6.3 BuildVersion:	21G419

### Database and driver

YugabyteDB: version 2.17.1.0 build 439

### Steps to reproduce

1. connect to YugabyteDB database
2. create MV:
```
create table t_table( id int primary key, f1 text);
insert into t_table select id, repeat('x',200) from generate_series(1,100000) id;
create materialized view t_mv as select id, replace(f1,'x','y') from t_table;
```
3. Refresh schema: the MV shows up in a PostgreSQL database, not in a YugabyteDB database.

**Comment by fritshoogland-yugabyte** [comment]
It seems this file is turning postgres features on or off for yugabyte db: plugins/org\.jkiss\.dbeaver\.ext\.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/impls/PostgreServerYugabyteDB\.java

```
    @Override
    public boolean supportsMaterializedViews() {
        return false;
    }
```
This should be true

Additionally:
```
    @Override
    public boolean supportsPartitions() {
        return false;
    }
```
This should be true

```
    @Override
    public boolean supportsTablespaces() {
        return false;
    }
```
We do support tablespaces, however we use it to perform YugabyteDB specific 'placement' on your geo distributed tablet servers.

```
    @Override
    public boolean supportsTeblespaceLocation() {
        return false;
    }
```
There seems to be a typo: `Teblespace` -> `Tablespace`.
Not sure what this does?

**Comment by LonwoLonwo** [comment]
Hello @fritshoogland-yugabyte 

Thanks for the report.

Ok, I see. Materialized views are available starting YugabyteDB 2.13 version. We need to check this info and add extra conditions in our methods.

**Comment by fritshoogland-yugabyte** [comment]
An easy way to check for the YugabyteDB version is the following:
```
yugabyte=# select substring(version(),'.*-YB-([0-9]*\.[0-9]*).*');
 substring
-----------
 2.17
```

**Comment by LonwoLonwo** [comment]
Yeah, thanks. Our test environment version is 2.4, so I'm waiting for an update. I will answer you later.

**Comment by LonwoLonwo** [comment]
Ok, I can create a materialized view and a tablespace in YugabyteDB 2.15 and a partitioned table in Yugabyte 2.4.
Thanks for the report and version query.

https://docs.yugabyte.com/preview/explore/ysql-language-features/going-beyond-sql/tablespaces/
https://docs.yugabyte.com/preview/explore/ysql-language-features/advanced-features/partitions/

**Comment by fritshoogland-yugabyte** [comment]
Hi, any word on progress on this? I am perfectly happy to help for the database side things.

**Comment by simon-mottram-cucumber** [comment]
this is a bit of an issue for us, we use materialized views quite a lot.  I'm also happy to chip in as an experienced developer. It would be very useful for us.  Thankyou
