### ISSUE TITLE
Azure w/Active Directory MFA Azure test connection succeeds, but cannot view data

### ISSUE THREAD

**Issue by mark-aaahq** [dbeaver/dbeaver#19257]
### Description

Using DBeaver 22.3.5, connecting to Dynamics 365 using Azure SQL Server stopped working on fresh install of DBeaver on Windows 11.

Host is our D365 endpoint (***.crm.dynamics.com), authentication is Active Directory - MFA

Connection Settings: 
![image](https://user-images.githubusercontent.com/18337484/222931528-2d463c73-f56e-44f6-8c82-560b063e7a77.png)

![image](https://user-images.githubusercontent.com/18337484/222931539-9a863fa4-d926-43ef-baa2-0d4d8ac101ed.png)

![image](https://user-images.githubusercontent.com/18337484/222931551-1cf0f3ae-dd37-4792-b5d8-9e9c873b123e.png)

Toggling the Read-only connection as well as Show all Schemas does not help.

Appreciate any suggestions.

### DBeaver Version

Community  22.3.5

### Operating System

Windows 11

### Database and driver

Azure SQL server / Microsoft JDBC Driver for SQL Server

### Steps to reproduce

Test connection via MFA works perfectly, but attempting  to open Database, then expand Schemas consistently throws this error:

SQL Error [40000] [S0001]: JSON conversion Error: Invalid type System.Object.
RequestId: TDS;f743fa67-ca08-46a2-af4f-0f678c5e9750;13
Time: 2023-03-04T22:37:24.9151384Z
  JSON conversion Error: Invalid type System.Object.
RequestId: TDS;f743fa67-ca08-46a2-af4f-0f678c5e9750;13
Time: 2023-03-04T22:37:24.9151384Z
  JSON conversion Error: Invalid type System.Object.
RequestId: TDS;f743fa67-ca08-46a2-af4f-0f678c5e9750;13
Time: 2023-03-04T22:37:24.9151384Z

**Comment by LonwoLonwo** [comment]
Hello @mark-aaahq 

Please change the version of your driver to `11.2.3.jre11`.

You can do it with the "Download/Update" button.

![2023-03-06 11_43_53-222931551-1cf0f3ae-dd37-4792-b5d8-9e9c873b123e png (Изображение PNG, 500 × 335 п](https://user-images.githubusercontent.com/45152336/223060378-5cf11bfe-7565-47d4-aa28-466d3b1ec644.png)

**Comment by RanDale-Com** [comment]
I have the same problem, but with Authentication AD-Password. The drivers are as you @mark-aaahq mentioned. 

**DBeaver Version**
Community 23.0.0.2

**Operating System**
Windows 10

**Database and driver**
Azure SQL server / Microsoft JDBC Driver for SQL Server
![image](https://user-images.githubusercontent.com/127082807/223368249-2a385dd0-52ce-409d-9793-823afa895026.png)


**Steps to reproduce**
Connection works, expand Schemas throws this error

SQL-Fehler [40000] [S0001]: JSON conversion Error: Invalid type System.Object.
RequestId: TDS;9a042572-722c-46ec-af47-a2977d339d65;10
Time: 2023-03-07T08:35:33.1491972Z
  JSON conversion Error: Invalid type System.Object.
RequestId: TDS;9a042572-722c-46ec-af47-a2977d339d65;10
Time: 2023-03-07T08:35:33.1491972Z
  JSON conversion Error: Invalid type System.Object.
RequestId: TDS;9a042572-722c-46ec-af47-a2977d339d65;10
Time: 2023-03-07T08:35:33.1491972Z

**Comment by LonwoLonwo** [comment]
Hello @RanDale-Com 

Does this setting enable in your connection settings?

![2023-03-07 12_22_22-Connect to a database](https://user-images.githubusercontent.com/45152336/223379229-16f54ccd-1893-4948-8ced-664059961bf2.png)

Maybe you have this issue https://github.com/dbeaver/dbeaver/issues/5258#issuecomment-1103528475

**Comment by RanDale-Com** [comment]
Hi @LonwoLonwo 

Yes, "Show All Databases" is enabled. I tried it with all possible options (Show All Databases, Schemas and with / without Trust Server Certificate). Always the same error if I expand schema

Edit:
Also tested the workarounds from issue #5258 - same result as above.

**Comment by LonwoLonwo** [comment]
@RanDale-Com , Can you expand schemas in your default database?

**Comment by RanDale-Com** [comment]
@LonwoLonwo No, if i "click" on expand, the error occurs. 
![image](https://user-images.githubusercontent.com/127082807/223670365-8737f18f-fefa-42a5-8d52-c80e9ed132b3.png)

**Comment by LonwoLonwo** [comment]
Do your connection settings contain your database name? What navigator view do you have? If it is advanced, you can change it to "custom" to avoid the reading of system metadata.

![2023-03-08 13_29_57-Connection _master 2_ configuration](https://user-images.githubusercontent.com/45152336/223689487-f2f801dd-08f0-4b32-8e75-40a85ecf1b3a.png)

Or you can change the driver version to 10 or 9.

**Comment by E1izabeth** [comment]
It's been a long time since no update here. If it's still actual for you, please let me know and provide additional info.

**Comment by E1izabeth** [comment]
It's been a long time since no update here. If it's still actual for you, please let me know and provide additional info.

**Comment by ronaldpai-bingo** [comment]
Hi, exact same issue as RanDale-Com.
