### ISSUE TITLE
Cannot change the displayed language of DBeaver.

### ISSUE THREAD

**Issue by hwhsu1231** [dbeaver/dbeaver#19253]
### Description

I tried to change the displayed language from **"English"** to **"Traditional Chinese"**.

* Windows -> Preferences -> User Interface -> Language

However, it seems that the modification is not working even though I restart the DBeaver.

The displayed language is still **"English"**.

### DBeaver Version

Community Edition 22.3.5.202302171528

### Operating System

Windows 11

### Steps to reproduce

1. Click the **"Windows"** in the menu bar.
2. Click the **"Preferences"** to open the dialog.
3. Click the **"User Interface"** item.
4. Find the **"Language"** label.
5. Change Language from **"English"** to **"Traditional Chinese"**.
6. Restart the DBeaver program.

![dbeaver-change-language](https://user-images.githubusercontent.com/71438617/222776478-c859dfce-00bd-4f50-bccb-0891cd03d613.gif)

**Comment by ShadelessFox** [comment]
Hello @hwhsu1231,

If you're launching DBeaver using a shortcut, please make sure that parameter `-nl en` is not present:

![image](https://user-images.githubusercontent.com/35821147/222778692-1b98784c-489e-4ed2-b282-dddcff060821.png)

If it's present, please remove it. Let me know if it helps.

**Comment by hwhsu1231** [comment]
@ShadelessFox

I see. It works after removing `-nl en` from the shortcut. Thanks!!

BTW, how do we contribute the translation to the DBeaver?

**Comment by ShadelessFox** [comment]
Please see:
https://github.com/dbeaver/dbeaver/wiki/Localization
https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code

I will close the ticket since your issue was resolved.
