### ISSUE TITLE
Could not create database from template (postgresql)

### ISSUE THREAD

**Issue by leccyril** [dbeaver/dbeaver#19267]
### Description

Creation database from a template needs connection to be disconnected, but on dbeaver once disctonnected we have no option to create database. SO we can't use the option "create a new database from a template".

![image](https://user-images.githubusercontent.com/3234598/223035511-5701a947-20c4-4a42-9305-6f9e00e39c58.png)

### DBeaver Version

communauty edition  22.3.5.202302171528

### Operating System

Fedora 36

### Database and driver

Postgres 15

### Steps to reproduce

Try to find option create database in menu (could not use create database on databse connection opened)

**Comment by Matvey16** [comment]
@leccyril Hello. I was able to reproduce this only by connecting directly to a template database (wich is not recommended)

![image](https://user-images.githubusercontent.com/82543000/223053834-6649de71-f7ea-486f-9bd3-844d7c2b8c4e.png)

Can you try changing the database in connection configuration to `postgres` or even leave this value empty?

**Comment by leccyril** [comment]
if i put postgres or leave it empty, off course i dont see anymore my datas

![image](https://user-images.githubusercontent.com/3234598/223069819-9bd0e428-bebf-4c4e-9e69-2e373a2d68e7.png)

how it is possible to connect on all databases without specifying the database ? i am stucked :/

**Comment by LonwoLonwo** [comment]
Hello @leccyril 

If you are using a connection via host and port, you can enable the "Show all databases" setting in your connection settings in the "PostgreSQL" tab.

![2023-03-06 12_36_43-DBeaver Ultimate 23 0 0 - _postgres12local_ Script-170  Script-170](https://user-images.githubusercontent.com/45152336/223072678-cb1fb30d-4a65-4ebe-8b2f-553c4d473787.png)

**Comment by leccyril** [comment]
Oh great !

**Comment by leccyril** [comment]
It works thanks
