### ISSUE TITLE
H2 databases without password are not accessible

### ISSUE THREAD

**Issue by SockenSalat** [dbeaver/dbeaver#19268]
### Description

dbeaver-version: CE 22.3.4.202302060909
h2-version: 2.1.214

When using an JDBC-URL like `jdbc:h2:tcp://localhost:9092/./rdds_usage;DB_CLOSE_DELAY=-1;` without any credentials I get `Wrong user name or password [28000-214]` which is confusing, since I'm using the same URL from different native Java processes to access the same database, which just works as expected.

Only Dbeaver is not able to connect. Why?

**Comment by SockenSalat** [comment]
There was an SELINUX Issue ... dbeaver also just works fine

**Comment by SockenSalat** [comment]
In order to connect to the H2 database an explicit password was required. Obviously dbeaver does not support _empty users_, which may be a consideration for the H2 driver.

See [Here](https://github.com/h2database/h2database/issues/3734#issuecomment-1432284254) for details on _no password set behaviour_.

So this is a feaure-request now.

**Comment by ShadelessFox** [comment]
Hello @SockenSalat,

If I understand correctly, you're specifying a username without a password?

Please try checking the "Save password locally" next to the password field on the connection page to see if it works.

**Comment by SockenSalat** [comment]
@ShadelessFox 

Yes and no. I'm not giving explicitly an username which seems to translate to a `null` value, but H2 expects an empty username in this case (empty String).

Happens when you start the H2 Server without specifying anything in this regard.

**Comment by LonwoLonwo** [comment]
Hello @SockenSalat 

No, DBeaver doesn't specify the username as null. It is allowed to use an empty password and username. So, I'm not sure that this is precisely DBeaver's issue.

Did you try just adding "sa" as a user name?

**Comment by SockenSalat** [comment]
> Did you try just adding "sa" as a user name?

Of course I did. Tried everything I found on the Internet. Workaround here was to force people to explicitly set a username / password :man_shrugging: 

@LonwoLonwo

**Comment by LonwoLonwo** [comment]
Please try to enable this setting in your driver properties:

![2023-04-06 16_14_58-Connect to a database](https://user-images.githubusercontent.com/45152336/230389806-a6b754b1-f3df-42d0-a22f-5f6705a6436e.png)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.
