### ISSUE TITLE
Sorting isn't disabled if ASC and DESC are applyed after each other

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#19261]
### Description

Sorting in column header is not disabled correctly

### DBeaver Version

23.0.0

### Operating System

Any

### Database and driver

Any

### Steps to reproduce

1. Apply sort by DESC in column header
2. Apply sort by ASC in the same column header
3. Click disable order in column header

**Expected:** Sorting is disabled
**Actual:** Sorting returns to DESC

### Additional context

Note: This is not reproducible the other way around (ASC -> DESC) only DESC -> ASC

https://user-images.githubusercontent.com/82543000/222984324-7ae0b1c2-8953-4718-b0aa-10742a449b22.mp4

**Comment by Vichman67** [comment]
I can confirm the bug provided by Matvey16, and add another detail.

It seems the 'Disable order by' option in column header always applies the 'next' option as shown in the dropdown list:

> ![image](https://user-images.githubusercontent.com/12735950/225855579-d80005f4-f03d-4679-9b58-68e4cd4716c2.png)

I.e.:
> 1. When selecting 'Order by ... ASC', the disable order makes a DESC ordering.
> 2. When selecting 'Order by ... DESC', the disable order makes a disabled ordering.

It has nothing to do with the ordering option previously selected.

**Comment by E1izabeth** [comment]
Fixed in scope of  #19951
