### ISSUE TITLE
Windows Store installed version no longer starts after update to 23.0.0

### ISSUE THREAD

**Issue by justin-tomlinson** [dbeaver/dbeaver#19264]
### Description

Opening app just gives error as below. Not sure where log file is to debug further.

![image](https://user-images.githubusercontent.com/29617113/223012044-e5d60514-664d-4bf3-a808-6e10f62e2edf.png)

### DBeaver Version

Community Edition 23.0.0

### Operating System

Windows 11

### Additional context

Windows Store Installation

**Comment by LonwoLonwo** [comment]
connected https://github.com/dbeaver/dbeaver/discussions/19244

**Comment by arhayka** [comment]
Connected to https://github.com/dbeaver/dbeaver/issues/17257

**Comment by serge-rider** [comment]
We've see many issues with Windows 10 however it worked on most Windows 11.

Please try the fresh version (it was updarted in the store today).

**Comment by uslss** [comment]
verified
