### ISSUE TITLE
Database navigation list items padding lost after update

### ISSUE THREAD

**Issue by jmarcher** [dbeaver/dbeaver#19269]
### Description

I just updated to 23.0 and the list items on the left are comprised and do not have any soft of padding:

I think this is related to the last bug report I made: #19152

![image](https://user-images.githubusercontent.com/686843/223091683-78547e10-fb5a-48cb-9f4b-9b706c64e9d4.png)

### DBeaver Version

Version 23.0.0.202303040621

### Operating System

macOS Ventura 13.2.1 (22D68)

**Comment by Destrolaric** [comment]
@jmarcher Hi. This allowed making the interface uniform for Windows, Linux, and macOS. Works as expected
