### ISSUE TITLE
Ruler in SQL Editor

### ISSUE THREAD

**Issue by richlysakowski** [dbeaver/dbeaver#19260]
### Description

I need a horizontal at the top of the SQL Editor ruler to interpret to help quickly identify which token or keyword is in error.  The error notification does not put the cursor in the exact location of an error, so having a ruler will help find things in error faster.  

### DBeaver Version

22.3

### Operating System

Windows 10 Pro

### Database and driver

Postgresql

### Steps to reproduce

This is a feature request.  It does not exist now.

### Additional context

See original description.  This is a feature request.  It does not exist now.

**Comment by E1izabeth** [comment]
You can observe all problems via Window->Show view->Other...->General->Problems.
![image](https://user-images.githubusercontent.com/28875055/224060188-e49ee3cf-264a-4524-9dfb-72481da232fe.png)

**Comment by E1izabeth** [comment]
It's been a long time since no update here. If suggested solution do not satisfy your needs and you have other ideas, please let me know.
