### ISSUE TITLE
Export from database to different database violates not null constraint

### ISSUE THREAD

**Issue by jasonwheritage** [dbeaver/dbeaver#19262]
### Description

Hi, 

When I export from a database to a different database, I get an error caused by NULL values in one of the original primary key columns. This is particularly annoying after completing a LEFT JOIN. If the join results in the table on the right of the join having no records, then the ID column of the table will be NULL in the result. Even if I change the name of the column or change the datatype,  the export is still trying to maintain the NOT NULL contraint of the PK.
For example:

--export this to database using dbeaver export tool
select 
a.id as a_id, a.column1,
b.id as b_id, b.column2,
from 
a LEFT JOIN b on a.id = b.id;

b_id will have some NULL values as a result of the LEFT JOIN. 
b.id is the PK of table b. 
Dbeaver is attempting to maintain the NOT NULL constraint of the PK b.id 
There is no option in the export tool to enable NULLABLE columns

I only seem to be having this issue in the latest version of Dbeaver (23) upgraded from (22)

### DBeaver Version

Version 23.0.0.202303040621

### Operating System

Windows 10

### Database and driver

Postgres 12

### Steps to reproduce

1. select query using left join on two tables with primary keys, where the join results in some NULL PKs of the right hand table
2. export to another database using the dbeaver export tool
3. configure columns 
4. export

### Additional context

1. tunnels to both databases

**Comment by ShadelessFox** [comment]
Hello @jasonwheritage,

If you're trying to export into an already existing table, there might be a PK with a NOT NULL constraint. Is that what you're trying to do?

DBeaver is not trying to maintain any constraints, it just exports data.

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
