### ISSUE TITLE
Azure sql server driver not working since 23.0.0

### ISSUE THREAD

**Issue by kevgeni** [dbeaver/dbeaver#19275]
### Description

1. try to create a new connection in the database navigator pane
2. in the database type dialog, select azure sql server
3. fill the info to connect to the database
4. Use the test connection, or finish and try to connect to the database

User will receive this error message
`com/microsoft/sqlserver/jdbc/SQLServerDriver has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

I think this might be related to 23.0 changelog item "Problems with Kerberos were resolved (we have reverted to Java 11)". 
It was working fine with dbeaver 22.3.5. 
Do not that on the version 23.0, instead of using sql azure as the database type, you can select microsoft sql server. It will be able to connect to the azure db. I do not know what is the difference, both seems to use the jdbc:sqlserver driver. 

### DBeaver Version

23.0

### Operating System

Windows 10

### Database and driver

1. Database name and version : azure sql server
2. driver version
com.microsoft.sqlserver.jdbc.SQLServerDriver
com.microsoft.sqlserver:mssql-jdbc:RELEASE [11.2.3.JRE17]

### Steps to reproduce

1. try to create a new connection in the database navigator pane
2. in the database type dialog, select azure sql server
3. fill the info to connect to the database
4. Use the test connection, or finish and try to connect to the database

User will receive the error message.

**Comment by kevgeni** [comment]
[18978](https://github.com/dbeaver/dbeaver/issues/18978) kerberos bug referenced by the changelog, I think

**Comment by LonwoLonwo** [comment]
Hello @kevgeni 

Please change the version of your driver to `11.2.3.jre11`.

You can do it with the "Download/Update" button.

![2023-03-06 11_39_27-DBeaver 23 0 0 - _postgres 2_ Script-18](https://user-images.githubusercontent.com/45152336/223366299-ade215d2-b4d4-4f9c-a313-7899c354f20d.png)

**Comment by kevgeni** [comment]
great, thanks. I upgraded both of my drivers to the latest version, using jre11 instead of 18. 
I did not know you could do that. I was kind of expecting the drivers to autoupdate themselves. I checked the auto update driver in one of the dialog and we'll see how it works in the future.
