### ISSUE TITLE
Hi. I am using 22.3.0 version of Dbeaver. My app was working 30 min ago and it won't launch now.  Run it as Admin and getting this message. Is there a way to fix the issue before running to unistall/reinstall part? Thank you

### ISSUE THREAD

**Issue by kaamid** [dbeaver/dbeaver#19277]

**Comment by serge-rider** [comment]
Please write more information.
What message do you see?
(hint: you can copy-paste screenshots right in the comment section)

**Comment by E1izabeth** [comment]
It's been a long time since no update here. If it's still actual for you, please let me know and provide additional info.
