### ISSUE TITLE
Zooming in and out for SQL Server Procedure Source View is broken

### ISSUE THREAD

**Issue by AsparagusEduardo** [dbeaver/dbeaver#19270]
### Description

I don't know if this also happens with other Database Connections like Oracle, but at least the SQL Server view is broken.

https://user-images.githubusercontent.com/2904965/223101633-521d9a6c-e7f0-4bd3-a7b2-a09c126a920b.mp4

### DBeaver Version

Community Edition 23.0.0

### Operating System

Windows 10 64-bit

### Database and driver

1. SQL Server 2019
2. Microsoft JDBC Driver for SQL Server (MSSQL)

### Steps to reproduce

1. Connect to database
2. Open procedure source
3. Press the zoom shortcuts (In my case, Ctrl++ and Ctrl+-)

**Comment by serge-rider** [comment]
Thanks for the bug report.
It is a side effect of https://github.com/dbeaver/dbeaver/issues/19159
