### ISSUE TITLE
SQL Server connection is not working on 22.3.0

### ISSUE THREAD

**Issue by crash5** [dbeaver/dbeaver#19287]
### Description

After upgrade to 22.3.0 old SQL Server connection is not working. It looks like you renamed the old sql server driver and the new driver has some problem with ?integrated jre? but the old profiles are try to using this version and I can't find a method to change the driver on an already existing profile.

![2023-03-07_16-25_1](https://user-images.githubusercontent.com/10976627/223473002-b63be089-7acc-4867-95b3-fbcc9f825f55.png)

![2023-03-07_16-24](https://user-images.githubusercontent.com/10976627/223473373-a856b1fb-e8f3-4a3f-8204-1f31b0c37e41.png)

### DBeaver Version

22.3

### Operating System

Windows 10

### Database and driver

SQL Server

### Additional context

I'm using the .zip version.

**Comment by LonwoLonwo** [comment]
Hello @crash5 

You need to change your driver version to the one with `.jre11`

![2023-03-06 11_39_27-DBeaver 23 0 0 - _postgres 2_ Script-18](https://user-images.githubusercontent.com/45152336/223489451-9cf065dd-9ea7-4dfe-804c-a9bdeafa4750.png)

**Comment by crash5** [comment]
It solved it thank you.
