### ISSUE TITLE
incorrect formatting pgplsql code in procedures

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#19284]
### Description

in previous version  have not this error

### DBeaver Version

community edition 23.0.0

### Operating System

windows 11 64bit

### Database and driver

Postgresql 14

### Steps to reproduce

there are no exact playback steps!

1. Start Dbeaver.
2. Refresh DB connection
3. Open procedure code
![image](https://user-images.githubusercontent.com/61137576/223435016-2a41f9af-d40e-42e6-a260-631427a9c4a9.png)
size all spaces and tabs are reduced
4. Close procedure code
5. Open procedure code again
![image](https://user-images.githubusercontent.com/61137576/223435508-754e549e-69df-403d-9164-696aa562a2f9.png)
size all spaces and tabs are normal

**Comment by ShadelessFox** [comment]
Hello @detkliff,

Thanks for the bug report.

This is a side-effect of https://github.com/dbeaver/dbeaver/issues/19159: the font is not monospace.

We're not going to republish the latest version, so I'd suggest downgrading to a previous version for now.
