### ISSUE TITLE
23.0.0 Windows zip release contains old java version

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#19281]
### Description

23.0.0 Windows zip release contains old java version. This prohibits connecting to SQL Server (and probably others). Replacing the jre directory with the one from 22.3.5 seems to solve the issue.

### DBeaver Version

Community Edition 23.0.0 Windiws zip version

### Operating System

Windows

### Database and driver

SQL Server
mssql-jdbc

### Steps to reproduce

Try to connect to any SQL Server database

**Comment by LonwoLonwo** [comment]
Hello @johnriksten 
We returned to JAVA 11.

To avoid problems with the SQL Server connection, you need to change the driver version to `.jre11`

![2023-03-06 11_39_27-DBeaver 23 0 0 - _postgres 2_ Script-18](https://user-images.githubusercontent.com/45152336/223366697-e4770108-974e-4d79-8b26-9aae04a3fdb3.png)
