### ISSUE TITLE
The font-size  is to small when I open a procedure or package at first time on 23.0

### ISSUE THREAD

**Issue by JiaOkay** [dbeaver/dbeaver#19291]
### Description

When I open a  procedure or package at first time on 23.0, The font-size  is to smal, it is normal when I open again.

In fact, it is not opened with the correct font。

![image](https://user-images.githubusercontent.com/38833358/223592947-5d5db675-c7bb-4bda-888e-4d921f66a069.png)

### DBeaver Version

DBeaver Community Edition 23.0

### Operating System

Win10 LTSC 21H2

### Database and driver

Oracle11G 
com.oracle.database.jdbc:ojdbc8:RELEASE-12.2.0.1

### Steps to reproduce

Description

**Comment by ShadelessFox** [comment]
Hello @NddNice,

Thanks for the bug report.

This is a side-effect of https://github.com/dbeaver/dbeaver/issues/19159: the font is not monospace.

We're not going to republish the latest version, so I'd suggest downgrading to a previous version for now.
