### ISSUE TITLE
Connection to DB2 with Kerberos (Integrated Authentication) warns me about expired password

### ISSUE THREAD

**Issue by rolandlkw** [dbeaver/dbeaver#19294]
### Description

I am connecting to a DB2 with Kerberos integrated authentication. 

To make this work, I had to edit dbeaver.ini and add the following lines:

-Djavax.security.auth.useSubjectCredsOnly=false
-Djava.security.krb5.realm= (our domain name)
-Djava.security.krb5.kdc=(our kerberos server name)

Every day in the morning I am getting a new kerberos ticket with kinit.

Whenever I open dBeaver and connect to my database, I get the warning, that my password is expired since -x days (since the day when my last password expired before the switch to integrated authentication happened)

![Expired](https://user-images.githubusercontent.com/80161643/223686281-6f770a34-09ab-4a83-a365-4114c077c99a.png)

I click **no** and can continue without any problems, I am connected to the database and everything works fine.
It is just the dialogue I have to click away every time (with a no). On top of that, the password warning hides behind one of the other windows on my screen if dBeaver is not in the foreground, so I have to minimize them all (because dBeaver is waiting for an action in the warning, before I can run any queries).

The driver settings know the options "integrated", "no authentication", "empty password", but no combination of checking/unchecking them fixes this behavior.

### DBeaver Version

Community Edition 23.0

### Operating System

Windows 10 21H2

### Database and driver

Database: IBM DB2 iSeries
Driver Name: IBM DB2 iSeries/AS 400 driver

### Steps to reproduce

1. I try to connect to a DB2 iSeries with integrated authentication.
2. I am getting a warning that the password has expired and I have to click "no" in the warning to continue (because yes would prompt me to change it, which is not possible, since it's not set)

**Comment by LonwoLonwo** [comment]
Hello @rolandlkw 

I'm unsure if we can do something from the DBeaver side here.
This message appears during the driver connection and goes from the driver's side.
Probably DB2i has some special option for this situation... something like this one:

![2023-03-08 14_33_03-DBeaver 23 0 0 - _postgres 2_ Script-18](https://user-images.githubusercontent.com/45152336/223702920-7ba136f5-84f5-4abd-ac46-cfb2541856ac.png)

**Comment by rolandlkw** [comment]
Hi @LonwoLonwo 
thanks for your answer. I've tried with all possible driver properties, even added custom driver properties, but nothing seemed to work. The IBM own "Query Tool" connects without this prompt, so I thought there might be a workaround to disable it. :( 

So I guess it won't be fixable from dBeaver side, I'm closing this one.
