### ISSUE TITLE
Newer versions of Oracle drivers

### ISSUE THREAD

**Issue by sacrophyte** [dbeaver/dbeaver#19299]
The 12.2 version of the Oracle jdbc drivers currently do not work well with Oracle databases using native encryption and current patch updates.

Would it be possible to make the latest Oracle jdbc drivers available here for direct dbeaver downloads?

Alternatively, users can manually download the latest jdbc drivers from Oracle and save them in a folder of their choice, and dbeaver allows users to select that new folder.

**Comment by LonwoLonwo** [comment]
Hello @sacrophyte 

> The 12.2 version of the Oracle jdbc drivers currently do not work well with Oracle databases using native encryption and current patch updates.

Could you provide examples, please?

Also, you can update your driver manually in your connection settings:

![2023-03-09 12_27_59-Driver settings](https://user-images.githubusercontent.com/45152336/223979614-3e5eb665-5948-44c6-acd1-a54611edf6e2.png)

**Comment by sacrophyte** [comment]
> Could you provide examples, please?

Sorry for the late response. Here is an example:

![dbeaver_default_oracle_drivers_v12](https://user-images.githubusercontent.com/5789822/225109527-88b05953-4cae-4043-a7db-a11f2a00e04f.png)

 
> Also, you can update your driver manually in your connection settings:

I am unable to comply with the instructions and select a version - you have a drop-down arrow next to version, I do not

![dbeaver_no_option_to_select_oracle_driver_version_download](https://user-images.githubusercontent.com/5789822/225109896-683ab209-5c23-45c7-a231-d4017177bf7b.png)

**Comment by sacrophyte** [comment]
Oh, sorry, I was clicking in the wrong spot. I was able to click on "12.2.0.1" and get the latest driver, which is a HUGE help. Thanks so much!!

Is there a way to make it a little more obvious/intuitive how to get a different version? Especially version 12 is a little old? :)

**Comment by LonwoLonwo** [comment]
I still need examples of the following:

> The 12.2 version of the Oracle jdbc drivers currently do not work well with Oracle databases using native encryption and current patch updates.

We need very important reasons to update the driver of such a complex database

**Comment by sacrophyte** [comment]
When I attempt to go back to the previous/default version (12.2.0.1), I get this error:

![image](https://user-images.githubusercontent.com/5789822/225298882-c1117871-20f6-4e5b-8a65-e5660a148dc2.png)

**Comment by sacrophyte** [comment]
Ok, I figured out the above problem (still getting used to how to manage the drivers). The real problem is ORA-12269; if you google this error, you will see a lot of notes about how the July 2021 CPU introduced new java security options. In order for Oracle drivers to work with new security options and get past the ORA-12269 errors, one needs to apply a patched version of 19c drivers (I forget if it is 19.6 or 19.12 or higher), or 21c drivers. When I use the default 12.2.0.1 drivers, I get this error:

![image](https://user-images.githubusercontent.com/5789822/225304639-f0943c0d-9e91-46d3-be5f-7fb026e03bb4.png)

**Comment by LonwoLonwo** [comment]
Ok, thanks for the clarification

**Comment by WumvanPauwe** [comment]
Hi all, using an Oracle 23 driver (ojdbc11.jar) on a Oracle 19 database disables Native Oracle Encryption. Highest version should be Oracle 21. When using Oracle 19 driver (ojdbc10.jar) encryption works fine.
Is there a piece of documentation to instruct users how to select the correct driver version?

**Comment by WumvanPauwe** [comment]
Seems to work fine with the following settings: 
<img width="859" alt="image" src="https://github.com/user-attachments/assets/e8cb6a49-152d-4851-a131-d7d94b5a6f21">
