### ISSUE TITLE
Cant connect by ODBC to database (hanaCloud)

### ISSUE THREAD

**Issue by Backglacius** [dbeaver/dbeaver#19290]
### Description

When i try connection on ODBC Hana cloud the connection its succed, but quen i try to create a connection to database by odbc, the connection thrwos this:

![image](https://user-images.githubusercontent.com/125837575/223537002-c268672b-f6ad-41ea-8226-fe342a9a0463.png)
 

### DBeaver Version

Com,unity edition 23.0.0

### Operating System

Windows 10 

### Database and driver

1.DATABASE HANA CLOUD DATALAKE
2. ODBC SAP IQ

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by Backglacius** [comment]
Ok, thanks for your repply. This is the log.

[dbeaver-debug-1678218587852.log](https://github.com/dbeaver/dbeaver/files/10925229/dbeaver-debug-1678218587852.log)

![image](https://user-images.githubusercontent.com/125837575/223849577-c448a713-c8d6-441e-8845-9e5bfa6340f0.png)

Thanks.

**Comment by LonwoLonwo** [comment]
https://bugs.openjdk.org/browse/JDK-8038751 can be connected with java

**Comment by Backglacius** [comment]
Ok, i've already connect to the db with java, thanks. I attached the link if anybody needs it.
https://developers.sap.com/tutorials/hana-cloud-dl-clients-jdbc.html
