### ISSUE TITLE
Can I disable newConnection in the find actions in the upper right corner

### ISSUE THREAD

**Issue by limda007** [dbeaver/dbeaver#19303]
Can I disable newConnection in the find actions in the upper right corner,or you can mask the find action function button in the upper right corner

**Comment by LonwoLonwo** [comment]
Hello @limda007 

Please provide a screen of the mentioned action. And could you explain why you need it?

**Comment by limda007** [comment]
![image](https://user-images.githubusercontent.com/36006790/223986472-0331559b-9725-40ff-8fa7-ba23e500ae07.png)
Because I want to restrict the creation of new database connections on the interface, I can only connect to the database through the cmd command.

**Comment by E1izabeth** [comment]
Could you give us more context. What is the exact use case?

**Comment by E1izabeth** [comment]
Why do you need to restrict new connection creation? Why exactly do you need to use cmd - why can't you connect via DBeaver?

**Comment by E1izabeth** [comment]
It's been a long time since no update here. Please let me know, if it's still actual for you and provide additional information.
