### ISSUE TITLE
Show non-display characters clearly

### ISSUE THREAD

**Issue by MarvinKlein1508** [dbeaver/dbeaver#19305]
### Description

We wanted to search for invalid values in our Table on DB2 for i Series.

This is the query we have run:
```sql
SELECT TRIM(TTTEXT) FROM TAMFTEST.TXST
WHERE NOT REGEXP_LIKE(TRIM(TTTEXT), '^[a-zA-Z0-9äöüßÄÖÜ\/€\s\)\-\(\.\!\@\:\=\>\<\+\,\&\\"_\}\{\;\[\]\*\?\%\#°áâãàµ§éêèôúûíîñõóç²³½®\$\´\`\|\~\'']*$') AND TRIM(TTTEXT) <> ''
```

DBeaver shows us this results:
![grafik](https://user-images.githubusercontent.com/32510006/224015560-8f78e6dc-bc6b-4e08-ad50-b96b48bdbd20.png)

As you can see, all results are looking pretty normal. So I did the same logic in C#.

And now I get this result:
```
Formblatt ?Informationen
für die Legalisierung von Dokumenten? einzureichen. Dieses
Verpackung:?
Lieferzeit:?
bis 10 tons ca 1 ? 2 Wochen, full truck auf Anfrage
Zahlung:?
Bedr. "Synth?" PE-b., "Typ 1.a"
```

As you can see, in C# we see a ? for unknown characters. So I saved all results in a textfile to see it within Notepad++
![grafik](https://user-images.githubusercontent.com/32510006/224015971-f148e96a-3baa-4c6b-883e-0486051b16ef.png)

It turns out that the ? are `NBH` characters
https://www.compart.com/en/unicode/U+0083

Even enabling the option in DBeaver to show us the whitespace doesn't show us this characters. I would expect to see them just like in Notepad++.

Also we saw in the DBeaver results this rows:
![grafik](https://user-images.githubusercontent.com/32510006/224016358-c9f2c84e-0737-4adb-a489-08f3206fa070.png)

C# does translate them to:
```
Mo. → Do.           7:00 → 13:00 Uhr
Fr.                          7:00 → 11:30 Uhr
Mo. → Do.           7:00 → 11:30 Uhr
Fr.                          7:00 → 10:30 Uhr
```

Within Notepad++ we can see that those are `SUB` characters
![grafik](https://user-images.githubusercontent.com/32510006/224016530-9cdf25ad-ef57-4999-b98d-eb1fa10efd8c.png)

Is there any way to display those characters just like in Notepad++?

### DBeaver Version

23.0.0

### Operating System

Windows 10 22H2

### Database and driver

Database: Db2 for IBM i
Driver: net.sf.jt400:jt400:RELEASE -> jt400-11.1

**Comment by ShadelessFox** [comment]
Hello @MarvinKlein1508,

Thanks for the report.

Showing non-display characters like in Notepad++ would be a nice feature to have.

**Comment by MarvinKlein1508** [comment]
@serge-rider is this a feature which I have to turn on? It looks like `NBSP` isn't being shown instead it just renders as a whitespace.

**Comment by ShadelessFox** [comment]
@MarvinKlein1508 yes, it's disabled by default. It can be toggled here:

![Image](https://github.com/user-attachments/assets/e4da7edf-b684-4a43-b2c7-b8613058c8b4)

**Comment by MarvinKlein1508** [comment]
@ShadelessFox thanks, I've enabled it now. However the NBSP is still being shown as a normal whitespace.

![Image](https://github.com/user-attachments/assets/31ba2a8c-3426-4a48-b583-97d2a27b14e4)

This is a bit unfortunate because this character is not affected be TRIM operations. It would be great if it can be shown as NBSP as well. :)

**Comment by ShadelessFox** [comment]
Oh. I believe we consider a NBSP as a regular whitespace. Can you please create a new ticket addressing that?
