### ISSUE TITLE
When there are no result set DBEaver still showing blank pane set

### ISSUE THREAD

**Issue by shrivatsahosabettu** [dbeaver/dbeaver#19317]
### Description

When I close the result set still the result set pane is visible with blank set.
You can see the below image the green box of blank result set pane is open.
![image](https://user-images.githubusercontent.com/12061573/224244140-5ef87c56-c6a8-405e-90b2-5d2c7d024ee1.png)

### DBeaver Version

Community Edition 23.0.0

### Operating System

Windows 11

### Database and driver

![image](https://user-images.githubusercontent.com/12061573/224243683-b11d3302-deb2-4065-b686-e631a2adc842.png)

### Steps to reproduce

1. Connect to the data base
2. Run the queries
3. Close manually the result set by click on x mark
![image](https://user-images.githubusercontent.com/12061573/224243613-df0f60dd-1214-4d00-8666-7e54a0973d63.png)

This was not happening in the earlier release of DBeaver.

**Comment by E1izabeth** [comment]
I can't reproduce it. Could you give more information about steps you do?
Does it happen for you when you execute any query or some specific (select, create, etc)?

Also log files would be useful. You can find instructions of how t find them here https://dbeaver.com/docs/wiki/Log-files/

**Comment by shrivatsahosabettu** [comment]
After I restart this is no more happening. I will close this and if it happens will open it with the reproduce steps as well.
