### ISSUE TITLE
For MonetDB no Tables, Views and Indexes are shown in the Database Navigator tree

### ISSUE THREAD

**Issue by mvdvm** [dbeaver/dbeaver#19311]
### Description

For MonetDB no Tables, Views and Indexes data are shown in the Database Navigator tree.
After succesfull connection, it will show 
![Screenshot from 2023-03-09 17-31-30](https://user-images.githubusercontent.com/81317646/224089948-decd0bb1-c17c-4f29-9c69-70b0e2bd7a8b.png)

The Schemas are shown properly.
In each schema the Tables, Views and Indexes are NOT shown, they are always empty. This is the bug.
In each schema the Procedures and Data Types are shown.

In JDBC the database metadata is retrieved using DatabaseMetaData.getSchemas(), DatabaseMetaData.getTables(), DatabaseMetaData.getIndexInfo(), DatabaseMetaData.Procedures(), etc.
All these methods return a ResultSet. I assume DBeaver also uses these methods.
If so, it could be that DBeaver does not correctly deal with ResultSets where the TABLE_CAT column returns null instead of a String.
According to the JDBC specification the TABLE_CAT ResultSet column of DatabaseMetaData.getTables() may be null. See https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/DatabaseMetaData.html#getTables(java.lang.String,java.lang.String,java.lang.String,java.lang.String%5B%5D)

Idem for the TABLE_CAT ResultSet column of DatabaseMetaData.getIndexInfo() 
https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/DatabaseMetaData.html#getIndexInfo(java.lang.String,java.lang.String,java.lang.String,boolean,boolean)

and all other methods which return a ResultSet.
Idem for ResultSetMetaData.getCatalogName().

Also when calling getTables(catalog, schema, table, table_types) the catalog argument must be null.
Idem for all other DatabaseMetaData methods which accept a catalog argument.

MonetDB does not support the catalog naming concept.
The MonetDB JDBC driver returns false for DatabaseMetaData methods supportsCatalogsInDataManipulation(), supportsCatalogsInProcedureCalls(), supportsCatalogsInTableDefinitions(), supportsCatalogsInIndexDefinitions() and supportsCatalogsInPrivilegeDefinitions().

Please improve DBeaver such that catalog names are NOT required, so can be null everywhere, as defined in the JDBC API specification.

### DBeaver Version

community edition Version 23.0.0.202303040621

### Operating System

Linex, Fedora 37

### Database and driver

MonetDB
monetdb-jdbc-3.3.jre8.jar
https://www.monetdb.org/downloads/Java/

### Steps to reproduce

start MonetDB server
(for installing and startup MonetDB server see: https://www.monetdb.org/easy-setup/ )

download MonetDB JDBC driver from  https://www.monetdb.org/downloads/Java/

In DBeaver set up a new Database Connection to MonetDB using default settings, example JDBC connection URL:
  DriverManager.getConnection("jdbc:monetdb://localhost:50000/demo", "monetdb", "monetdb");

Open the connection and inspect the data shown in the Database Navigator tree.
For schemas sys and tmp open the Tables, Views and  Indexes. They should list multiple names, but none are shown.

**Comment by LonwoLonwo** [comment]
Hello @mvdvm 

Unfortunately, I can't reproduce your issue for now.

![2023-03-10 12_31_21-DBeaver Ultimate 22 3 2 - _localhost 4_ Script-94](https://user-images.githubusercontent.com/45152336/224278910-9b14eafb-8f06-4c17-99a3-78c43f46c484.png)

In your image, I see the "sys" schema, which is the system, and if you have a custom navigator view, then please change it on the "Advanced"

![2023-03-10 12_30_19-DBeaver Ultimate 22 3 2 - _localhost 4_ Script-94](https://user-images.githubusercontent.com/45152336/224279501-e8a58d6c-94a7-4351-83b5-3e5ab6a24c8d.png)

> Please improve DBeaver such that catalog names are NOT required, so can be null everywhere, as defined in the JDBC API specification.

If you look into the [Query manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) (with all enabled in settings filters) - you see that DBeaver already uses NULLs as catalogs names

![2023-03-10 12_34_52-DBeaver Ultimate 22 3 2 - _localhost 4_ Script-94](https://user-images.githubusercontent.com/45152336/224280359-ded34501-7b05-4b0e-bf57-e8e0832ef0e1.png)

**Comment by LonwoLonwo** [comment]
So, the question then is - did you change your driver locally with all these settings from https://github.com/dbeaver/dbeaver/issues/19313 ?

**Comment by mvdvm** [comment]
With the 'Show system objects' enabled I can now see the MonetDB system Tables, Views and Indexes.
Thanks.

I did not change the driver locally with all these settings from https://github.com/dbeaver/dbeaver/issues/19313

**Comment by LonwoLonwo** [comment]
thanks for the answer
