### ISSUE TITLE
[Oracle]  "q" symbol on the end of string cropped

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#19319]
### Discussed in https://github.com/orgs/dbeaver/discussions/19295

<div type='discussions-op-text'>

<sup>Originally posted by **Kectai** March  8, 2023</sup>
<img width="267" alt="image" src="https://user-images.githubusercontent.com/46049250/223694391-991bcd05-76ce-4c90-8711-3544e15edf4e.png">

dbeaver community23.0.0

oracle19c

The old version used before did not have this problem.</div>

![2023-03-10 13_09_53-DBeaver Ultimate 23 0 0 - _orcl_ Script-59](https://user-images.githubusercontent.com/45152336/224288671-0c529204-d66c-4d49-b4b0-33ef7d064165.png)

with ; and without

**Comment by E1izabeth** [comment]
q is determined as the query delimiter - that's why it's red. It happens only if you type ; after q. If you don't put ; after q, then the query works fine.
