### ISSUE TITLE
If end if and TABLE IF EXISTS Conflict

### ISSUE THREAD

**Issue by yangmeng66** [dbeaver/dbeaver#19318]
### Description

If the database supports anonymous block execution, it also supports/ TABLE IF EXISTS test; Then there will be a problem to install the JDBC SQLDialect capability of the current dbeaver. The two are conflicting

The following script execution will report an error:
```
DECLARE
i int;
BEGIN
i := 0;
IF i < 5 THEN
i := i + 1;
DBMS_OUTPUT.PUT_LINE ('This is: '||i);
END IF;
END;

select * from YM8.TIMETEST t ;

DROP TABLE IF EXISTS test;
```

### DBeaver Version

22.1.1 ce

### Operating System

WINDOS 10

### Database and driver

YashanDB, a new database similar to ORACLE, from China

**Comment by E1izabeth** [comment]
Could you show which queries do you see in Query Manager (https://dbeaver.com/docs/wiki/Query-Manager/) when execute a script?

Could you also show an error which you get?

Do you use Oracle driver to set up connection to YashanDB?

**Comment by yangmeng66** [comment]
1  `Do you use Oracle driver to set up connection to YashanDB?` We have our own JDBC driver
2 The error is as follows:
Expected in OracleSQLDialect # ORACLE_ BEGIN_ END_ BLOCK is configured with IF as "BLOCK_BEGIN"
![image](https://user-images.githubusercontent.com/51857567/224287906-e43119c1-1137-407a-9822-f2f1ede6c8f5.png)


I have found the specific error location in the source code
org.jkiss.dbeaver.model.sql.parser.SQLScriptParser#parseQuery(org.jkiss.dbeaver.model.sql.parser.SQLParserContext, int, int, int, boolean, boolean)

**Comment by E1izabeth** [comment]
Thank you for quick reply. We will look deeper into your case.

The link to where we can download jdbc driver for YashanDB would be useful, if it's free.

**Comment by yangmeng66** [comment]
As we all know, dbeaver is currently the most popular database ide with powerful functions, so we are now developing our plug-in on dbeaver. We hope that it can be integrated into your source code like China's OceanBase in the future. Of course, it has its own plug-in in dbeaver
![image](https://user-images.githubusercontent.com/51857567/224290654-f1557c98-ce2b-4089-81e0-3f78a74f67dc.png)

this I will reply to you tomorrow
`The link to where we can download jdbc driver for YashanDB would be useful, if it's free.`

**Comment by E1izabeth** [comment]
Sounds cool!

I was able to reproduce the issue for Oracle. It seems that DBeaver tries to execute the followings as a one query
```
DROP TABLE IF EXISTS test;

select * from YM8.TIMETEST t;
```

As a temporary workaround you can select the query `DROP TABLE IF EXISTS test;` and execute it as a single query with "Execute SQL Statement" command, then put cursor to the next query and continue script execution with the command "Execute SQL Script from the position"
![image](https://user-images.githubusercontent.com/28875055/224293761-69f6e888-5acd-4d48-bc79-bf658ef39d78.png)

**Comment by yangmeng66** [comment]
Yes, selecting a single execution is fine, but executing a script is not

So far I have recently temporarily modified SQLScriptParser-Parsequery code locally to be compatible with YashanDB script execution IF.. END IF;   And can support... IF EXISTS... But hopefully dbeaver will work with general support for this case
