### ISSUE TITLE
horizontal scroll sql file

### ISSUE THREAD

**Issue by SergioAraya** [dbeaver/dbeaver#19328]
### Description

Al escribir en la ultima linea de un archivo .sql, la barra de scroll aparece cuando se acerca el puntero del mouse y dificulta la escritura.

![Captura desde 2023-03-10 07-37-21](https://user-images.githubusercontent.com/20360509/224330000-b2b90e38-daf5-4594-bc05-33d7a1f67842.png)

### DBeaver Version

Versión23.0.0.202303040621

### Operating System

Linux

### Database and driver

Mysql

**Comment by uslss** [comment]
thanks for the report - closed as a duplicate of #10950
