### ISSUE TITLE
French message "dangerous query" incorrect parameters {0} {1}

### ISSUE THREAD

**Issue by McMogan** [dbeaver/dbeaver#19329]
### Description

On a production database  : update mytable set col = 1;

English message : You are about to execute UPDATE statement without a WHERE clause on "mytable".
French message :  Vous êtes sur le point dexécuter {0} instructions sans clause WHERE sur {1}'.

The correct message should be "Vous êtes sur le point d'exécuter l'instruction UPDATE sans clause WHERE sur "mytable".

### DBeaver Version

Community Edition 23.0.0

### Operating System

Windows 10

### Steps to reproduce

connect to a production database 
update mytable set col = 1; 

"Execute dangerous queries" popup with incorrect message

**Comment by LonwoLonwo** [comment]
Thanks for the report @McMogan
