### ISSUE TITLE
monospace font not used in function source panes

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#19331]
### Description

It seems it has changed recently together with font updates.
The function source pane uses the main font (Sugoe) instead of a monospace one (unlike a table, an index or others ddl)

### DBeaver Version

CE 23.0.0

### Operating System

Fedora 37

### Database and driver

N/A

### Steps to reproduce

Open function/stored procedure code in Properties/Source

**Comment by E1izabeth** [comment]
Thank you for bug report. It is a side effect of #19159
We reverted these changes in #19270. The fix will be available in the next release.
