### ISSUE TITLE
Redshift Spectrum Schema information not being shown,

### ISSUE THREAD

**Issue by Geogiev** [dbeaver/dbeaver#19330]
### Description

Schema information for Redshift spectrum external table is not being shown.
This was working fine until the recent upgrade to version 23.0.0.202303040621

![Capture](https://user-images.githubusercontent.com/18537644/224342030-f003715c-7dbc-44ab-b984-c43c9b52ab0e.JPG)

### DBeaver Version

Community Edition 23

### Operating System

Windows 

### Database and driver

Database Resdshift
Driver: AWS Redshift JDBC driver redshift-jdbc42:RELEASE(2.1.03)

### Steps to reproduce

1. Create an External table
2. I am able to query
3. Table not visible under Schema --> Tables

**Comment by Destrolaric** [comment]
A duplicate of https://github.com/dbeaver/dbeaver/issues/19288, for community edition fix will be available in the next version.
