### ISSUE TITLE
Geometry viewer no map layer spatialite

### ISSUE THREAD

**Issue by FaFre** [dbeaver/dbeaver#19335]
### Description

When I want to display my geometries using the geometry viewer with spatialite, the map view remains empty. I set the transform for the column to 'Geometry'.

![image](https://user-images.githubusercontent.com/59543085/224466126-cfe144ab-4a5e-44ad-ab2f-a81d569aa2a3.png)

Also changing from 'Simple' to any projection doesn't work.

I don't have any problems using the geometry viewer on my PostgreSQL connection in the very same window.

### DBeaver Version

Community 22.3.4.202302111842

### Operating System

Linux/Manjaro

### Database and driver

SQLite jdbc 3.41.0.0

**Comment by E1izabeth** [comment]
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by E1izabeth** [comment]
Also could you provide minimum example (DDL with create table and insert into queries)? It will help a lot, if we can reproduce your case.

**Comment by FaFre** [comment]
I found the issue.

When using `AsWKT` it is working. However, in my case I used `AsEWKT` (extended WKT: https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry#Format_variations).

The difference is when using `AsEWKT` the SRID is added to the text string. This would be actually benefitial for dbeaver to parse the SRID directly instead of requiring to set it manually by the user.

![image](https://user-images.githubusercontent.com/59543085/224480623-4809be1e-d1bb-4e9a-81f6-1f0a0fc5150e.png)

I think the Problem here is that EWKT is not understood by dbeaver. This is still an issue that should be addressed.

Small example:
```sql
 with geom as (
 	select GeomFromEWKB('0101000020110f00007efedb7da465354114161dadfed95941') as point
 )
 select AsWKT(point) as working, AsEWKT(point) as not_working from geom;
```

**Comment by E1izabeth** [comment]
Thank you for investigation.

**Comment by FaFre** [comment]
It would be also extremely cool to make dbeaver understand EWKB + WKB directly when using sqlite connections. On a postgres connection  I can interpret the EWKB as geometry via right click -> transform without problems. 

The ability to read and interpret EWKB is already there, but doesn't seem to be implemented in the last mile for sqlite connections.
