### ISSUE TITLE
DBeaver 23 not showing Redshift Spectrum tables

### ISSUE THREAD

**Issue by alejandrofm** [dbeaver/dbeaver#19334]
### Description

I just updated to DBeaver 23, the Spectrum schemas no longer have a differentiated icon (they appear) and the tables are not listed. Using the same driver as in the last 22 version.

### DBeaver Version

23

### Operating System

macOS Ventura 13.2.1

### Database and driver

Driver: com.amazon.redshift:redshift-jdbc42:RELEASE

**Comment by LonwoLonwo** [comment]
Hello @alejandrofm 
Thanks for the report.

This is a duplicate of https://github.com/dbeaver/dbeaver/issues/19288. The fix for the community edition will be available in the next version (23.0.1).
