### ISSUE TITLE
Sql Server Connection Settings

### ISSUE THREAD

**Issue by erasmosud** [dbeaver/dbeaver#19340]
### Description

Can't create driver instance
  Error creating driver 'MS SQL Server / SQL Server' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
  Error creating driver 'MS SQL Server / SQL Server' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
    com/microsoft/sqlserver/jdbc/SQLServerDriver has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
    com/microsoft/sqlserver/jdbc/SQLServerDriver has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

### DBeaver Version

23.0.0.0

### Operating System

WIN10

### Database and driver

com.microsoft.sqlserver:mssql-jdbc:RELEASE 11.2.3.jre17
com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE 11.2.3.x64

### Steps to reproduce

Try to connect to database sql server, localhost, default configuration. 

### Additional context

![2023-03-12_23h56_20](https://user-images.githubusercontent.com/785233/224598503-dde2594f-10db-4dcc-a631-6ce204cdc49d.png)

**Comment by E1izabeth** [comment]
Thank you for bug report.

You need to change your driver version to the one with .jre11

![image](https://user-images.githubusercontent.com/28875055/224610986-9dd936d9-aec5-4c0b-985e-ba068a9dcd38.png)
