### ISSUE TITLE
Display whitespaces in result set (feature request)

### ISSUE THREAD

**Issue by N3kOnScreeps** [dbeaver/dbeaver#1934]
Hi,

I would like to see whitespace and other invisible characters in result set strings, like we can see them in editor.
It could help to determine why joins fails sometimes, when a whitespace is at the end of a code, for example.

Thank you for making this app great.

**Comment by serge-rider** [comment]
Agreed, this makes sense

**Comment by VipSaran** [comment]
cmon, 4 years old?

**Comment by Marmeladenbrot** [comment]
Is that feature request set for the 21.2.4 milestone?

Discovered a really really nasty bug because a DB table had \x20 and \xA0 mixed at the end and TRIM() only removes whitespace = \x20.

The result set I used for my analysis was therefore pure garbage because of missing JOINS/GROUP BY due to the funny \xA0 character.

Would have been prevented if I would have seen the non-breaking spaces in the result set.

**Comment by serge-rider** [comment]
We need to test for performance degradation when "show whitespaces" is on

**Comment by ShadelessFox** [comment]
Implemented:

![java_GJBMPLnxnc](https://user-images.githubusercontent.com/35821147/158740433-07ba7233-d673-4b71-aab7-566a926cf23c.png)

Can be enabled in <kbd>Editors</kbd> &rArr; <kbd>Data Editor</kbd> &rArr; <kbd>Appearance</kbd> &rArr; <kbd>Grid</kbd> &rArr; <kbd>Show whitespace characters</kbd>.

**Comment by Matvey16** [comment]
Verified

**Comment by Marmeladenbrot** [comment]
Thanks for implementing this.
Is there a list what counts as "whitespace"? I have this list I check for in my SQL queries:

UTF8-Code | Definition
-- | --
U+000A | line feed
U+000B | vertical tabulation
U+000C | formfeed
U+000D | carriage return
U+0009 | horizontal tabulation
U+0085 | next line
U+00A0 | no-break space
U+0020 | whitespace
U+200B | zero-width space
U+200C | zero-width non-joiner
U+200D | zero-width joiner
U+200E | left-to-right mark
U+200F | right-to-left mark
U+2028 | line separator
U+2029 | paragraph separator
U+202A | left-to-right embedding
U+202B | right-to-left embedding
U+202C | pop directional formatting
U+202D | left-to-right-override
U+202E | right-to-left override
U+2060 | word joiner
U+2066 | left-to-right isolate
U+2067 | right-to-left isolate
U+2068 | first strong isolate
U+2069 | pop directional isolate
U+206A | inhibit symmetric swapping
U+206B | activate symmetric swapping
U+206C | inhibit arabic form shaping
U+206D | activate arabic form shaping
U+206E | national digit shapes
U+206F | nominal digit shapes
U+FEFF | zero-width no-break space

**Comment by ShadelessFox** [comment]
We display only line feeds, carriage returns, spaces, ideographic spaces, zero-width spaces, and tabulations. This is the same set of characters supported for displaying by Eclipse in its text editors.
