### ISSUE TITLE
DBeaver uses ALTER VIEW to rename a VIEW instead of ALTER TABLE [Redshift]

### ISSUE THREAD

**Issue by alejandrofm** [dbeaver/dbeaver#19349]
### Description

When renaming a view from the Database Navigator panel on Redshift, DBeaver uses ALTER VIEW, that command does not exist on Redshift:
ALTER VIEW schema.view RENAME TO schema.view_bkp;
It should use:
ALTER TABLE schema.view RENAME TO schema.view_bkp;

### DBeaver Version

23

### Operating System

macOS Ventura 13.2.1

### Database and driver

Driver: com.amazon.redshift:redshift-jdbc42:RELEASE

### Steps to reproduce

Create a view
Try to rename it using the Database Navigator panel (right click->Rename)

**Comment by LonwoLonwo** [comment]
Hello @alejandrofm 

Thanks for the report
