### ISSUE TITLE
I want to be able to copy data/table/schema from one database to another...dev to qa to prod

### ISSUE THREAD

**Issue by jgrover21** [dbeaver/dbeaver#19350]

**Comment by E1izabeth** [comment]
Probably, you want this https://dbeaver.com/docs/wiki/Data-migration/

**Comment by jgrover21** [comment]
I already know these step. But I can to create stored procedure or sql query to do it.

**Comment by E1izabeth** [comment]
Then could you clarify what is your feature request about?
Am I correctly understand that you want to transfer procedure from one database to another?

**Comment by jgrover21** [comment]
I want to transfer table/data from one database to another. e.g.  I have dev_dbae and qa_dbase.  I want to move table from one to another. I can use export option but it fails with large files.  I want to run stored procedure do this transfer.

**Comment by E1izabeth** [comment]
So, is the request the same as in your other issue #19351?
Could we close this one then and continue in the other one with more detailed description?

**Comment by jgrover21** [comment]
other one is specifically for export feature whch is failiing on large files.

**Comment by LonwoLonwo** [comment]
Hello @jgrover21 

It is still unclear what you want in this ticket. Please, provide examples.

**Comment by E1izabeth** [comment]
It's been a long time since no update here. Let me know, if the issue still actual, and provide more detailed and clear explanation.

**Comment by jgrover21** [comment]
yes, I want to be able to copy data from one database to another in same server..using sql query..but it does not allow that.  I have used export feature in dbeaver.  but I want to schedule it to load.

**Comment by E1izabeth** [comment]
DBeaver has tasks (https://dbeaver.com/docs/wiki/Task-Management/) which you can schedule (https://dbeaver.com/docs/wiki/task-scheduler/)

**Comment by jgrover21** [comment]
I will try that and let you know..
