### ISSUE TITLE
SQL Editor font don't apply without restart

### ISSUE THREAD

**Issue by souhaib100** [dbeaver/dbeaver#19354]
### Description

The sql view/editor has very small font,

### DBeaver Version

Community Edition 23.0.0

### Operating System

Windows 10

### Database and driver

Microsoft SQL Server

### Steps to reproduce

Trying to maximize it using CTRL,SHFT,+ wont take affect, unless you **restart** dbeaver and the current view must **not be sql view/editor**.

**Comment by E1izabeth** [comment]
Please try using only Ctrl+ without Shift.

**Comment by souhaib100** [comment]
Ctrl+ is for expand the body of sections (like BEGIN...END)

**Comment by E1izabeth** [comment]
By the way, you can change the font size in preferences (`Monospace font` for SQL Editor font)
![image](https://user-images.githubusercontent.com/28875055/224772561-04146972-5284-4a73-a520-008c322b89ed.png)

**Comment by souhaib100** [comment]
The same problem this wont apply unless you restart dbeaver.

**Comment by ShadelessFox** [comment]
Hello @souhaib100,

Can you please confirm whether the issue persists in the latest version of DBeaver or not? https://dbeaver.io/download/

Thank you.

**Comment by souhaib100** [comment]
Hello @ShadelessFox , 
It is fixed, good job.

**Comment by ShadelessFox** [comment]
Thanks for confirming that. I'm glad the issue was solved.

**Comment by o42-michalpawlowski** [comment]
This persists in version 23.0.2.202304091457

**Comment by ibobak** [comment]
For me it reproduces with 23.0.3.202304240616 

I did not find this issue, therefore started my own one https://github.com/dbeaver/dbeaver/issues/19815
sorry for duplicate.
