### ISSUE TITLE
Transactions are recorded in READONLY PRODUCTION connections

### ISSUE THREAD

**Issue by dmichulke** [dbeaver/dbeaver#19361]
### Description

For connections that are set to Connection Type production and readonly (Both under: Edit Connection -> General) transactions are recorded, even though they shouldn't.

### DBeaver Version

Community 22.3.4.202302060909

### Operating System

Windows 11

### Database and driver

Tested on
Postgresql 14
Postgres JDBC Driver 42.5

and
Oracle 12 (not sure here)
Oracle jdbc8 v12.2.01.

### Steps to reproduce

Create a connection to a database (Oracle or postgres, probably also works for others)
Set it to production and read-only

execute `SELECT 1;` or 
`SELECT 1 FROM dual;`

Transaction count is set to 1 and you need to COMMIT or ROLLBACK

**Comment by LonwoLonwo** [comment]
Hello @dmichulke 

Sorry, but I'm not sure.
https://stackoverflow.com/questions/818074/transactions-for-read-only-db-access
Does read-only connection not have transactions? Can you point me to the documentation which says that?

**Comment by dmichulke** [comment]
Hmm, following your link I can see how there might be reasons to still have transactions.
I can see that there might be technical reasons to still not autocommit by default. However, the link is 12 years old, performance should matter less these days and I think my point is a bit more specific.

Iḿ not arguing for a general autocommit, I argue (and I could have made that clearer)
for autocommit for plain select statements.

If as a user I ever want a setting to be changed, 
I run it _before_ the SELECT, e.g. "SET ROLE ...;"
At this point it's clear a transaction would make sense.

Still, 95% of the time I just run a plain SELECT and if I'm not in a transaction before running the select, I shouldn't be in a transaction after the select either.

Does that make sense?

**Comment by E1izabeth** [comment]
We can't be sure, that simple plain select do not lead to any modifications as, for example, there can be some functions, which may be triggered by such select execution.

**Comment by LonwoLonwo** [comment]
But what is the point of using production mode with the read-only together? Maybe using of Development mode will help you?

**Comment by dmichulke** [comment]
The point of using "readonly connection" for me is to avoid accidental writes, e.g, INSERT accidentally because you thought you're working on the dev database.
At that time accumulating numbers in the transaction counter via SELECTs is

- useless (assuming we don't do writes via functions)
- uncomfortable (you have to COMMIT or ROLLBACK - I personally would like an auto-rollback here because it makes it clear that nothing was changed) 
- and potentially blocks other peoples' transactions (not sure this can happen)    

Maybe a checkbox implementing auto-rollback would help here? :-)

**Comment by ShadelessFox** [comment]
Hello @dmichulke,

A read-only connection doesn't imply you can't edit data using SQL. Even if a `SELECT` statement doesn't seem to do anything harmful, it can call a function that can potentially alter data in the database. There may be databases that support triggers on query execution that can modify data too.

So having transactions always enabled is better for your safety. I don't consider current behavior as a bug.
