### ISSUE TITLE
Default values do not show for domain procedures parameters

### ISSUE THREAD

**Issue by SolfacodeSoftware** [dbeaver/dbeaver#19366]
### Description

Problem exists when you use domains.

Example:

create procedure with default parametr:
CREATE OR ALTER PROCEDURE DBS$SYSTEMLOG_ADD_TEST("DBS$NAME" VARCHAR(64), DBS$LOG DBS$MEMO, DBS$DELETE DBS$BOOLEAN DEFAULT 0)
AS
BEGIN
-- test procedure with default param
END

show procedure in DBeaver:
CREATE OR ALTER PROCEDURE DBS$SYSTEMLOG_ADD_TEST ("DBS$NAME" VARCHAR(64), DBS$LOG DBS$MEMO, DBS$DELETE DBS$BOOLEAN)
AS
BEGIN
-- test procedure with default param
END

### DBeaver Version

23.0.0.202303040621

### Operating System

Windows 11

### Database and driver

org.firebirdsql.jdbc.FBDriver version 4.0.0.java8

**Comment by LonwoLonwo** [comment]
@SolfacodeSoftware 

Thanks for the report.

**Comment by LonwoLonwo** [comment]
connected  #6059 and  #10164

**Comment by LonwoLonwo** [comment]
Sorry, I do not have a server right now. Can you please provide me DBS$BOOLEAN DDL?

**Comment by SolfacodeSoftware** [comment]
Here it is:

CREATE DOMAIN DBS$BOOLEAN AS
SMALLINT
CHECK (VALUE IS NULL OR VALUE IN(0, 1));

Best regards.
/M

sob., 1 kwi 2023 o 19:52 Anastasiya ***@***.***> napisał(a):
