### ISSUE TITLE
create bookmarks in the database tree

### ISSUE THREAD

**Issue by shtoormanSam** [dbeaver/dbeaver#19377]
In a large database, we usually work with a small number of tables scattered across different branches of the tree.

It is convenient to have bookmarks in the database tree — to collapse the tree, but leave only the necessary tables with bookmarks.

**Comment by ShadelessFox** [comment]
Hello @shtoormanSam,

Are you aware of the `Bookmarks` under the project view?

![image](https://user-images.githubusercontent.com/35821147/225374573-ed93fb7b-cd1d-4fa4-8ad7-9682bc117869.png)

You can drag and drop objects here for quick access.

Please let me know if it helps.

**Comment by shtoormanSam** [comment]
Yohoho! Good tip! Thanks! ))

ср, 15 мар. 2023 г. в 20:23, ShadelessFox ***@***.***>:

**Comment by ShadelessFox** [comment]
I assume the issue can be closed now.

**Comment by shtoormanSam** [comment]
Sorry, I hastened to rejoice - when dragging, the tree is not scrolled, if
the tree is long, then it is not possible to add bookmark (copy / paste
gives an error "Can't detect container for ...")

ср, 22 мар. 2023 г. в 00:20, ShadelessFox ***@***.***>:

**Comment by ShadelessFox** [comment]
Can you please provide more information about the mentioned error, including steps required to reproduce it?

**Comment by shtoormanSam** [comment]
1. Expand the tree long enough so that the Bookmarks are outside the window border.
2a. Try dragging the tree element to the invisible Bookmarks
or
2b. Copy tree element - scroll the tree until Bookmarks appear - Paste. Voila! Error "Can't detect container for 'Bookmarks'"
![DBeaver bookmark error](https://user-images.githubusercontent.com/127952519/227846849-9bce21b2-e090-4ac4-b7e8-f5adfae61962.jpg)

**Comment by ShadelessFox** [comment]
Sorry, I'm not following. Are you talking about the "Projects" view? Can you record a video instead, please?

**Comment by E1izabeth** [comment]
https://user-images.githubusercontent.com/28875055/232122264-b38cf66a-389a-4b6b-a58b-b24a91403715.mp4

**Comment by traffisco** [comment]
Hi, facing the same problem. Any fixes?

**Comment by shtoormanSam** [comment]
Hi-hello! I would like to send the object to bookmarks from the context
menu - the good (best?) way...

ср, 15 мар. 2023 г., 20:23 ShadelessFox ***@***.***>:

**Comment by ShadelessFox** [comment]
This is confirmed to be a bug.

Cases producing different errors:
1. Copy a table, try pasting it into the "Bookmarks" folder
2. Try dragging a disconnected data source into the "Bookmarks" folder
