### ISSUE TITLE
Monospace font size on the plain text tab doesn't change. Restart doesn't help

### ISSUE THREAD

**Issue by Essentia-G** [dbeaver/dbeaver#19375]
### Description

I tried out new "DBeaver fonts" preferences and noticed that the monospace font size on the plain text tab doesn't change. Everything is ok in the SQL Editor, SQL Terminal, etc.

<img width="1400" alt="Screen Shot 2023-03-15 at 11 39 58" src="https://user-images.githubusercontent.com/54938058/225284898-68178441-0675-4f09-a0ad-f667bfffa5d4.png">

### DBeaver Version

Ultimate Edition 23.0

**Comment by arhayka** [comment]
Similar behavior on Windows. The font size on the plain text tab can be changed only by using Ctrl++/Cmd+
