### ISSUE TITLE
Update BigQuery driver to 1.3.2

### ISSUE THREAD

**Issue by ak-workit** [dbeaver/dbeaver#19370]
### Description

The Error "The specified column type is currently unsupported by the driver for column JSON." is causes since theSsimba drivers packaged with the OSS is not supporting JSON columns in google BigQuery tables.

Upgrading BigQuery Simba Driver to latest version to 1.3.2 in the Dbeaver OSS would fix the error..

### DBeaver Version

Community Edition Version 23.0.0.202303040621

### Operating System

macOS ventura 13.2.1

### Database and driver

SimbaJDBCDriverforGoogleBigQuery42_1.2.21.1025

### Steps to reproduce

- Connect to any Bigquery 
- Read the data from table with JSON column

**Comment by LonwoLonwo** [comment]
Thanks for the report @arvind-workit

**Comment by ak-workit** [comment]
hi @LonwoLonwo 
Any idea when this would be looked at please?
The drivers upgrade would be of massive help! 
Thanks again.

**Comment by LonwoLonwo** [comment]
Hello @arvind-workit 

You can always update your driver version manually:

![2023-03-14 18_27_20-DBeaver Ultimate 23 0 0 - SYSROLEGRANT](https://user-images.githubusercontent.com/45152336/229569327-75b57a1a-4aad-4858-ac0f-04ecbbf64ccc.png)

**Comment by EduGuz** [comment]
the JDBC release 1.3.2 1003 driver can be download from here:
https://cloud.google.com/bigquery/docs/reference/odbc-jdbc-drivers
Then, just update the driver as shown in the above comment.
