### ISSUE TITLE
ER-diagram auto-scroll is trollling if you do double click on table's name

### ISSUE THREAD

**Issue by GiantCrocodile** [dbeaver/dbeaver#1937]
1. open ER-diagram view
2. do double click on a table's name at a table with many fields (> 15 or something)

What did happen? You didn't open the table but you scrolled down and opened some field. Really unexpected behaviour, when we talk usability.

**Comment by uslss** [comment]
Reproduces on 6.0.2

**Comment by uslss** [comment]
Issue isn't reproducible in 6.2.0.
Ticket closed
