### ISSUE TITLE
incorrect error line number

### ISSUE THREAD

**Issue by shtoormanSam** [dbeaver/dbeaver#19384]
### Description

DBeaver Community edition — error description show wrong number of code line, it looks like it skips the comment lines.

### DBeaver Version

DBeaver Community edition 22.3.0.202212041619

### Operating System

Win11

### Database and driver

PostgreSQL 13.8
PostgreSQL JDBC Driver

**Comment by E1izabeth** [comment]
Hi, @shtoormanSam 
Could you provide some example? We need to reproduce it.

**Comment by E1izabeth** [comment]
It's been a long time since no update here. Let me know, if the issue still actual, and provide additional info.

**Comment by TechGeorgii** [comment]
Version 24.0.2.202404071654 MAC, Community Edition.
I have a big query wrapped in BEGIN / ROLLBACK transaction and DBeaver shows error in line 3 but actual error is in line 52.

What DBBeaver shows me (line 3)
![image](https://github.com/dbeaver/dbeaver/assets/1381695/835f1ac5-b8d2-4de8-9349-3f84d46e1ef0)

there is no COLUMN statement
![image](https://github.com/dbeaver/dbeaver/assets/1381695/79513308-195c-4cc1-afce-9dac1051d2f4)

where error is actually is (line 52):
![image](https://github.com/dbeaver/dbeaver/assets/1381695/7b3877b1-06a9-4fb0-9489-334bce5e2dc0)


pgadmin does it correctly.
