### ISSUE TITLE
unexpected end of stream 

### ISSUE THREAD

**Issue by plannet2021** [dbeaver/dbeaver#19388]
### Description

i get the errror "Could not connect to 127.0.0.1:12789 : unexpected end of stream, read 0 bytes from 4 (socket was closed by server)"
connections worked fine in the past. i did not change anything myself, but might have got some automatic updates via the company on my laptop. 
i tried to upgrade. same error. i then installed community edition. same error. 
SSH tunnel works fine. double checked passwords. with or without VPN, same error. 

### DBeaver Version

Community Edition     23.0.0.202303040621

### Operating System

MS Windows 10 Enterprise

### Database and driver

1. Database Name and version: MariaDB 10.8.3
2. Drivers name and version: MariaDB jdbc client 3.0.7

### Additional context

SSH used. SSH never was the problem

**Comment by LonwoLonwo** [comment]
Hello @plannet2021 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by LonwoLonwo** [comment]
#9799

**Comment by plannet2021** [comment]
Hi, here is the latest log. 
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10991163/dbeaver-debug.log)

**Comment by LonwoLonwo** [comment]
Ok, please try following solutions:

https://stackoverflow.com/a/33307702

**Comment by E1izabeth** [comment]
It's been a long time since no update here. Please let me know, if it's still actual for you and provide additional information.

**Comment by qkqsb** [comment]
This has started impacting me as of today. I do not know what changed, but I followed the stackoverflow article and tried to set the following parameters:
validationQuery="SELECT 1"
wait_timeout=180

**Comment by raphilevine** [comment]
I am having the same issue.
Did you figure out how to resolve this?

**Comment by Rah1x** [comment]
I ran into the same issue today, but I upgraded and restarted it and worked fine.
