### ISSUE TITLE
Enable catalog support for ClickHouse

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/dbeaver#19383]
**Is your feature request related to a problem? Please describe.**
Both legacy and new ClickHouse JDBC driver use term `schema` as synonymous to database, which is inconsistent with other interfaces(i.e. MySQL) of ClickHouse and most database drivers. Starting from v0.4.2, the driver will support option `databaseTerm`(defaults to schema, can be changed to catalog) to support catalog. In v0.5, the default will be changed from `schema` to `catalog`.

**Describe the solution you'd like**
Change ClickHouse plugin configuration from `<parameter name="omit-catalog" value="true"/>` to the followings:
```xml
<parameter name="omit-catalog" value="true"/>
<parameter name="omit-single-catalog" value="true"/>
```
According to my test, the change works well with v0.4.1. You may verify the change using latest nightly build at [here](https://s01.oss.sonatype.org/content/repositories/snapshots/com/clickhouse/clickhouse-jdbc/0.4.2-SNAPSHOT/).

**Describe alternatives you've considered**
N/A

**Additional context**
Currently the workaround is to change the parameters in driver settings:
![image](https://user-images.githubusercontent.com/4270380/225521297-abe0f53a-be46-4819-b70e-b0083498b046.png)

**Comment by E1izabeth** [comment]
Thank you for request!
