### ISSUE TITLE
Problem Occured while trying to save the state of workbench

### ISSUE THREAD

**Issue by bashartulkarim** [dbeaver/dbeaver#19390]
### Description

Issue while fetching Connection details in Projects.

### DBeaver Version

Community Edition 23

### Operating System

windows

### Database and driver

DB2

**Comment by E1izabeth** [comment]
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by E1izabeth** [comment]
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by bashartulkarim** [comment]
[.log](https://github.com/dbeaver/dbeaver/files/10989611/default.log)

**Comment by bashartulkarim** [comment]
here is the file

**Comment by E1izabeth** [comment]
Thank you

**Comment by bashartulkarim** [comment]
any update on this? I have also uninstalled and reinstalled but the issue still persists

**Comment by E1izabeth** [comment]
Could you try resetting UI settings? https://dbeaver.com/docs/wiki/Reset-UI-settings/

**Comment by E1izabeth** [comment]
Does it still actual?

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
