### ISSUE TITLE
AWS Redshift EXTERNAL TABLE no longer in catalog - Similar to #1897

### ISSUE THREAD

**Issue by orzom411** [dbeaver/dbeaver#19399]
### Description

Recently updated and an artifact of this update I've lost visibility to External Table's in AWS Redshift.  I checked and see a driver update appears to have resolved similar issue as noted under issue 1897 (https://github.com/dbeaver/dbeaver/issues/1897).

Under Database menu, Driver Manager, AWS/Redshift_JDBC, click edit button, this opens a dialog box "Edit Driver 'AWS/Redshift_JDBC'", under Libraries tab, click on the driver (in my case c:\java\aws\Redshift), right side "Download/Update" button is grayed out.

I was going to hunt down AWS's latest Java driver for Redshift, if there is one, but last time I worked around DBeaver and an AWS/Redshift driver issue I had to uninstall and re-install (time consuming).

### DBeaver Version

23.0.0.202303040621

### Operating System

Windows 10 - 21H12

### Database and driver

psql (PostgreSQL) 14.2
(I couldn't determine the Java version from the GUI).

### Steps to reproduce

Connect to Redshift instance
Navigate through the database, schema and open the Tables branch.

Expected result, pre update, to see External Tables listed.  They are missing.

**Comment by orzom411** [comment]
Update (hope this helps):

New Connection default error:
Error setting default catalog/schema for new connection

Reason:
Error changing default database

Details:
Error changing default database
  Error setting search path
  Error setting search path
    SQL Error [0A000]: ERROR: External schema "bla" cannot be set in search_path
    SQL Error [0A000]: ERROR: External schema "bla" cannot be set in search_path
      ERROR: External schema "bla" cannot be set in search_path
      ERROR: External schema "bla" cannot be set in search_path

**Comment by LonwoLonwo** [comment]
Hello @orzom411 

Please check the Early Acces version: https://dbeaver.io/files/ea/

The issue may be solved there.

**Comment by orzom411** [comment]
Thank you @LonwoLonwo, early access version has corrected the catalog issue.  Thank you for your help.
