### ISSUE TITLE
Unable to paste in sql window text copied in Telegram desktop app. Text copied in gedit pastes just fine

### ISSUE THREAD

**Issue by zz-aa** [dbeaver/dbeaver#19396]
### Description

[Screencast from 2023.03.16. 14:43:52.webm](https://user-images.githubusercontent.com/75880235/225622673-cb99c364-13b1-4d35-b1e8-c252e9632a0b.webm)

- Also tried shortcuts like CTRL+V, shift+insert, the result is the same,
- Both dbeaver and telegram desktop are run by the same user,
- Text copied in other apps (like terminal or gedit) or copied inside dbeaver pastes just fine.

### DBeaver Version

Community Edition 23.0.0

### Operating System

ubuntu 22

### Additional context

Telegram Desktop version 4.6.5 was used

**Comment by E1izabeth** [comment]
Can't reproduce on Windows 10. Probably, it's unix-specific issue

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by Pablo-163** [comment]
I had the same problem. Recently after updating to version 23.3.5 the problem was resolved.

**Comment by E1izabeth** [comment]
@Pablo-163 thank you for update!
