### ISSUE TITLE
The zoom is applied only after pressing the refresh button.

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#19392]
### Description

![Screenshot_13](https://user-images.githubusercontent.com/84867187/225595268-4eded138-e35a-4b83-bfae-3a0dce1505b1.jpg)
 
In Menu bar zoom option (Menu bar --> Window -->Editor --> Zoom in) is applied only after pressing refresh button 

### DBeaver Version

23.0.1

### Operating System

windows 10

### Database and driver

DBeaver Sample database

### Steps to reproduce

1. Open DBeaver Sample DataBase
2. Check Menu bar --> Window -->Editor --> Zoom in

expected result: zoom is applied

actual result :  zoom is applied only after pressing the refresh button.

**Comment by E1izabeth** [comment]
#19412
