### ISSUE TITLE
Data Compare database views

### ISSUE THREAD

**Issue by mcpiroman** [dbeaver/dbeaver#19393]
In the description of [Data Compare](https://github.com/dbeaver/dbeaver/wiki/Data-compare) I can only see that tables are mentioned and I cannot find whether comparing views is also possible. If not, here's the FR for it.

I'd find even more useful an ability to compare results of queries. It is requested in #9626 but the issue has been inappropriately closed.

**Comment by ShadelessFox** [comment]
Hello @mcpiroman,

Yes, you can compare views. The mentioned ticket was closed because the issue is tracked on our internal board.

Please let me know if you have any other questions.

**Comment by mcpiroman** [comment]
Thanks for answer, everything is clear.

**Comment by danfoxley** [comment]
> Yes, you can compare views. 
> Please let me know if you have any other questions.

How?

**Comment by ShadelessFox** [comment]
I don't quite understand what exactly you want to know @danfoxley. Data from two sources can be compared using the Data Compare feature; views can be chosen as the input source, just like regular tables. All related information can be found in the corresponding documentation: https://github.com/dbeaver/dbeaver/wiki/Data-compare
