### ISSUE TITLE
Wrong font at the "Deklaration"-Tab

### ISSUE THREAD

**Issue by heyntz** [dbeaver/dbeaver#19391]
### Description

At the "Deklaration"-Tab of a View, Function, Package,... the editor tab shows the code with the wrong font. It chooses the "main font" instead of the "monospace font"

![image](https://user-images.githubusercontent.com/53035087/225592846-0b1b404b-1982-49ee-a78a-05fd34284c51.png)
![image](https://user-images.githubusercontent.com/53035087/225592967-224278ed-564c-45da-bc3f-8803b3af1cfd.png)

### DBeaver Version

23.0.0

### Operating System

Windows 10

### Database and driver

Oracle

### Steps to reproduce

select a view from the list. Let DBeaver show the declaration.

### Additional context

DBeaver is set to german
Behavior occurs since the 23.0 version.

**Comment by E1izabeth** [comment]
Thank you for bug report. It is a side effect of #19159
We reverted these changes in #19270. The fix will be available in the next release.
