### ISSUE TITLE
Backup database -> being asked for password can end in endless loop

### ISSUE THREAD

**Issue by GiantCrocodile** [dbeaver/dbeaver#1940]
If you try to backup your database by exporting it you can end in a loop which is endless. Problem is if your parameters doesn't work for authentication. In my case I had whitelisted ipv4 local ip-range but not ipv6 local iprange. pq_dump was using ipv6 ip-range to dump it and thus it was denied and asked for password. My connection itself had no password specified because on ipv4 it is simply whitelisted for local network. Thus my dbeaver hang endless and I was asked for password but I wasn't able to see that in the export log. I just waited and canceled it after some time, tried same command in console and then I saw that there was an authentication request which fails.

**Comment by uslss** [comment]
is it still actual?

**Comment by GiantCrocodile** [comment]
No clue, I think you have to reproduce it: I'm not using DBeaver at the moment.

**Comment by uslss** [comment]
cannot reproduce it for now.
If it is still actual for you - feel free to reopen it
