### ISSUE TITLE
Nonprintable/non-standard characters aren't parseable

### ISSUE THREAD

**Issue by nateirvin** [dbeaver/dbeaver#19405]
### Description

When you have a SQL query/editor/file that has whitespace characters other than CHAR 32, the SQL parser throws an error.

It feels like the parser should be able to handle non-standard spacings, and if not it should give a clearer error; the current makes the error seem random and nonsensical.

### DBeaver Version

Community Version 23.0.0.202303040621

### Operating System

Windows 10 Pro

### Database and driver

Database: Redshift
Driver: AWS / Redshift (JDBC)

### Steps to reproduce

1. (Attempt to) run a query with non-standard spacing (for example: [problem query.sql.txt](https://github.com/dbeaver/dbeaver/files/10997972/problem.query.sql.txt))
2. Get this error: `SQL Error [42601]: ERROR: syntax error at or near "."`

### Additional context

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10997992/dbeaver-debug.log)

**Comment by ShadelessFox** [comment]
Hello @nateirvin,

The issue has nothing to do with DBeaver. The error is returned from the database.
