### ISSUE TITLE
Duplicates procedures names

### ISSUE THREAD

**Issue by sge38** [dbeaver/dbeaver#19401]
### Description

Hello,
We are encoutering an issue with duplicate functions names when using DBeaver with PostgreSQL database.
Here is an example :

[](url)
![image](https://user-images.githubusercontent.com/128068322/225680967-abcc444d-94c4-482b-8c16-784391e447a2.png)

The functions are exactly identical, and queries in system tables show that the duplicate functions are existing only once in the database.
pgAdmin, which is the official tool to connect to PostgreSQL database does not show the problem.

### DBeaver Version

23.0.0.202303040621

### Operating System

windows

### Database and driver

Database PostgreSQL 13.10
Driver postgresql-42.5.0.jar

### Steps to reproduce

Not sure how you can reproduce. 

The problem seems to be linked to the following query launched by DBeaver to display procedures list:

 SELECT p.oid as poid,p.*,pg_catalog.pg_get_expr(p.proargdefaults, 0) as arg_defaults,d.description
	FROM pg_catalog.pg_proc p
	LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=p.oid
	WHERE p.pronamespace=$1
	ORDER BY p.proname;

In our system, some procedures have the same oid as some tables, which seems to happen in postgres.
And in this case, the query has collected table and columns descriptions for the procedure, as they have the same oid.

Procedure description is only 1 row, but you may have multiple rows for table and columns, wich leads to duplicate display.

Hope this is clear enough.

**Comment by LonwoLonwo** [comment]
Hello @sge38 

Do duplicate procedures have the same DDL? Could you provide examples?

**Comment by sge38** [comment]
Hello,

Yes, the duplicate procedures are exactly identical.
And if I run a query against pg_proc table, there is no duplicate.

What kind of example do you need? 
Screen copy of each identical procedure?

**Comment by LonwoLonwo** [comment]
An example of any duplicate procedure.

And maybe any ideas on how to do this in our test environment:

`In our system, some procedures have the same oid as some tables, which seems to happen in postgres.`

**Comment by sge38** [comment]
Hello,
I can provide you a sample database with the problem (in PostgreSQL 13)
Will it help ? I don't know how to reproduce it, it just happened.

**Comment by LonwoLonwo** [comment]
Yes, It will be very helpful!
you can send it my e-mail anastasiia.volkova@dbeaver.com

**Comment by E1izabeth** [comment]
Does this issue still actual?

**Comment by sge38** [comment]
Hello,

As far as I know, yes.
I have sent a sample database to help you in investigations and never had any answer.

Best regards,
Sylvie GENUER

**Comment by E1izabeth** [comment]
Thank you for response.

**Comment by LonwoLonwo** [comment]
Unfortunately, I still can't reproduce the issue with or without the dump.

Could you please provide the result of this query for your schema with duplicates?

```sql
SELECT p.oid as poid,p.*,pg_catalog.pg_get_expr(p.proargdefaults, 0) as arg_defaults,d.description
FROM pg_catalog.pg_proc p
LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=p.oid
WHERE p.pronamespace=$1
ORDER BY p.proname;
```

**Comment by sge38** [comment]
Hello,

Yes, I can send you that. But as your query includes the source code of the « duplicate » function, it is quite unreadable in an excel file.

Which format do you prefer ?
Or maybe I can send you the result without the source code (it is always the same for all rows) ?

Best regards,
Sylvie GENUER

**Comment by LonwoLonwo** [comment]
Just a screen of the duplicate procedures will be enough.

**Comment by sge38** [comment]
***@***.***

**Comment by sge38** [comment]
Hello,

Sorry for the previous email.
I have sent the screen copy of your query (only the first columns).

Here is another screen copy that seems more relevant to me : the description column is important.
***@***.***


The description column match the columns of a table with same oid as the procedure :
***@***.***


Hope it will help.

Best regards

**Comment by E1izabeth** [comment]
Unfirtunately, attachments from the reply to the github notification don't come to github comment automatically. Could you open an issue and attach a screenshot as a comment?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue still actual, please let me know and provide additional information by writing a comment under the issue here https://github.com/dbeaver/dbeaver/issues/19401

**Comment by Satek7** [comment]
Please add classoid='pg_proc'::regclass to this query 

SELECT p.oid as poid,p.*,pg_catalog.pg_get_expr(p.proargdefaults, 0) as arg_defaults,d.description
FROM pg_catalog.pg_proc p
LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=p.oid **and d.classoid='pg_proc'::regclass** 
WHERE p.pronamespace=$1
ORDER BY p.proname;

**Comment by E1izabeth** [comment]
@Satek7 is this issue reproducible for you?

**Comment by Satek7** [comment]
Table pg_description has namespace for objects like tables, types etc.  also parameter oid is unique only in particular classoid not globaly. If you join to this table you must specify classoid otherwise, duplicates may occur

**Comment by E1izabeth** [comment]
Thank you

**Comment by sge38** [comment]
Thank you

De : Satek7 ***@***.***>
Envoyé : mardi 6 février 2024 14:43
À : dbeaver/dbeaver ***@***.***>
Cc : Genuer Sylvie ***@***.***>; Mention ***@***.***>
Objet : Re: [dbeaver/dbeaver] Duplicates procedures names (Issue #19401)


Table pg_description has namespace for objects like tables, types etc. also parameter oid is unique only in particular classoid not globaly. If you join to this table you must specify classoid

**Comment by LonwoLonwo** [comment]
Hello @sge38 

This is the version with the fix: https://dbeaver.io/files/ea/

Please feel free to check your issue case there.
