### ISSUE TITLE
Restore Defaults btn does not return previous state after applaying

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#19411]
### Description

[Screencast 2023-03-17 08-42-47.webm](https://user-images.githubusercontent.com/84867187/225908366-c87572b4-e83c-410c-b815-9318dba20cff.webm)

In Properties for Query Manager **Restore Defaults** btn does not  discard all changes and does not return default state after pressing **Apply** btn

### DBeaver Version

23.0.1

### Operating System

windows 10 

### Database and driver

Dbeaver Sample Database

**Comment by MashaKorax** [comment]
The same thing when Im trying to restore defaults after creating new connection type

https://user-images.githubusercontent.com/84867187/230321063-bfd9a987-c293-4c52-b1af-b319d7e7011f.mp4

**Comment by LonwoLonwo** [comment]
The Restore Defaults button will return only the original values before applying. It is expected behaviour for now.

QA tests added.
