### ISSUE TITLE
Beaver Community 23.0.0.202303040621 - Zoom In and Zoom Out don't work

### ISSUE THREAD

**Issue by wjatscheslaw1986** [dbeaver/dbeaver#19412]
### Description

Window -> Editor -> Zoom In doesn't work
Window -> Editor -> Zoom Out doesn't work

Neither clicked in drop down menu, nor using hotkey, these doesn't work. Nothing happens, font size in SQL editor window doesn't get changed.

### DBeaver Version

Community 23.0.0.202303040621

### Operating System

macOS Ventura 13.2.1

### Steps to reproduce

Window -> Editor -> Zoom In

Window -> Editor -> Zoom Out

**Comment by ShadelessFox** [comment]
Thanks for the bug report.

Duplicate of #19392
