### ISSUE TITLE
[MacOS] : have DBeaver window in fullscreen mode been reopened in fullscreen mode

### ISSUE THREAD

**Issue by Mumeii** [dbeaver/dbeaver#19420]
**Is your feature request related to a problem? Please describe :**

Right now I'm using the community edition of DBeaver, version 23.0.0.202303040621
Whenever :
- I use the fullscreen mode on Mac OS (green button in the upper left part of the window)
- I quite DBbeaver (Cmd + Q)
- I reopen it

The windows id not reopened in fullscreen mode 😢 

**Describe the solution you'd like :**

I guess it may be due to the fact that DBeaver is relying on eclipse UI tools, and those tools are not conceived in order to require a fullscreen command at (Mac) os level

But if it's not a limitation of the the Eclipse tooling, so it would be nice to have the windows reopening in the same state that they have been closed 😃 

**Describe alternatives you've considered :**
I can't think about any alternative

**Additional context :**
None

**Comment by Destrolaric** [comment]
@Mumeii We don't think this functionality is needed in DBeaver, and this is not the standard behavior for most apps in the macOS.
