### ISSUE TITLE
Deprecated TLS versions aren't available since the last update

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#19429]
### Description

We patch our bundled JRE's security policy to it doesn't restrict the usage of deprecated TLS versions. We do so to make it possible to connect to legacy MSSQL versions: https://github.com/dbeaver/dbeaver/issues/12668. Unfortunately, now it's not the case for Windows.

### DBeaver Version

DBeaver CE 23.0.0

### Operating System

Windows

**Comment by serge-rider** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
