### ISSUE TITLE
Remove blocking popups

### ISSUE THREAD

**Issue by ag0n-e** [dbeaver/dbeaver#19425]
**Is your feature request related to a problem? Please describe.**
dbeaver currently always finds a reason to open a blocking popup. working with it would be a lot more pleasant if you didn't have to click away a popup again for virtually every operation.

**Describe the solution you'd like**
remove unimportant popups completely "tip of the day", remove blocking for less important popups and leave only some really important popups (e.g. do you really want to delete the whole database?)

**Describe alternatives you've considered**
burn my computer and throw it out of the window when the next popup appears :)

**Additional context**
thank you for your dedication and great app

**Comment by ShadelessFox** [comment]
Hello @ag0n-e,

You can disable most of the confirmations <kbd>User Interface</kbd> &rArr; <kbd>Confirmations</kbd>.

Additionally, you can prevent the "Tip of the Day" popup from showing by unchecking "Show tips on startup" in it.

Confirmations are important. You would blame DBeaver for letting you drop your database without confirmation by accidentally hitting DELETE on your keyboard.
