### ISSUE TITLE
DBeaver 23.0.0 - Language not changeable

### ISSUE THREAD

**Issue by francwalter** [dbeaver/dbeaver#19421]
### Description

I have installed the Windows 64-Bit version of DBeaver 23.0.0 for "All Users".

Now I want to change language from german to english.
So I did Fenster > Einstellungen > User Interface > Regional settings > Sprache: English
Save and apply but on the next restart the language is still german.

### DBeaver Version

23.0.0.202303040621

### Operating System

Windows 10 Enterprise

### Database and driver

Not relevant

### Steps to reproduce

I set language to english:

![grafik](https://user-images.githubusercontent.com/927269/226187033-c1b6ebea-3aea-409a-be8d-8f158c02e22d.png)

But after restart ('Anwenden und Schließen') it is german again:

![grafik](https://user-images.githubusercontent.com/927269/226187011-105552c9-fff8-40d4-a96f-2a49736d14bf.png)

It does not help to open it as Administrator.

**Comment by ShadelessFox** [comment]
Hello @francwalter,

We are aware of this issue. Please see https://github.com/dbeaver/dbeaver/issues/19253#issuecomment-1453810985 for a workaround.

And yes, please let me know if it helps.

**Comment by francwalter** [comment]
Thanks!
Indeed, I noticed a parameter for the start icon but didnt think about it. It was:  `-nl de`
Without it all works :) thank!
