### ISSUE TITLE
Teradata JDBC fetch from Maven

### ISSUE THREAD

**Issue by Anteus** [dbeaver/dbeaver#19427]
As Teradata JDBC driver is on Maven it could be easily fetched and updated like other drivers in DBeaver.

https://central.sonatype.com/artifact/com.teradata.jdbc/terajdbc/20.00.00.06/overview
https://github.com/Teradata/jdbc-driver

**Comment by LonwoLonwo** [comment]
Thanks for the info @Anteus!

I also can see it on the mvnrepository
https://mvnrepository.com/artifact/com.teradata.jdbc/terajdbc

**Comment by MashaKorax** [comment]
verified
