### ISSUE TITLE
Error column in exporting csv file from dbvera

### ISSUE THREAD

**Issue by niceyou99** [dbeaver/dbeaver#19423]
### Description

After dbvera exports the csv, opening the csv file causes the data in the same line to run to the next line, resulting in incorrect columns

### DBeaver Version

22.0.3

**Comment by LonwoLonwo** [comment]
Hello @niceyou99 

Could you please provide footage showing your issue? Thank you.

**Comment by E1izabeth** [comment]
It's been a long time since no update here. If the issue is still actual, please let me know and provide additional information.
