### ISSUE TITLE
Not showing table size for Redshift since v23

### ISSUE THREAD

**Issue by alejandrofm** [dbeaver/dbeaver#19433]
### Description

Until the last update, on the Database navigator, as an admin I could see the table size at the right side of the panel, now it only shows "...", also it isn't shown on Table Properties -> Statistics (I think this broke on previous versions)

### DBeaver Version

23

### Operating System

macOS Ventura 13.2.1

### Database and driver

Driver: com.amazon.redshift:redshift-jdbc42:RELEASE

### Steps to reproduce

Open a schema so the tables are listed on the Database navigator panel

**Comment by LonwoLonwo** [comment]
Hello @alejandrofm

Could you please test it in the Early Acces version? Probably, the issue is already fixed and will be available in the next release.

https://dbeaver.io/files/ea/

**Comment by mp24-git** [comment]
For me, 23.0.1 EA fixes the issue and I can see table sizes again:
![image](https://user-images.githubusercontent.com/70982239/226631166-96eec769-b259-4374-b2a4-577cb0155037.png)

**Comment by LonwoLonwo** [comment]
Thanks for testing @mp24-git
