### ISSUE TITLE
Trigger and trigger function sources display using wrong font

### ISSUE THREAD

**Issue by johnrtian** [dbeaver/dbeaver#19436]
### Description

When viewed via the Triggers tab for a particular table, triggers and trigger functions display their source using the main, non-monospace font.

### DBeaver Version

DBeaver CE 23.0.0.202303040621

### Operating System

Windows 10 21H2

### Database and driver

1. DB: PostgreSQL 11.17
1. Driver: PostgreSQL standard JDBC driver 14.2

### Steps to reproduce

1. Open a new DBeaver instance and open a new connection
2. Open Declaration for a table containing a trigger
3. Navigate to the table's Triggers tab, then into a trigger
4. Observe that the trigger's Source is presented in non-monospace font
5. Navigate to the trigger's function
6. Navigate to the function's Source tab
7. Observe that the trigger function's Source is also presented in non-monospace font

Alternatively:
1. Open a new connection (or Disconnect All + Connect)
2. Open a trigger function directly
3. Navigate to the function's Source tab
4. Observe that the trigger function's Source is presented in non-monospace font

### Additional context

For the trigger _function_, only occurs on first open for a given metadata connection.
For the trigger itself, occurs everytime.

![image](https://user-images.githubusercontent.com/21209995/226397489-3439701a-a03f-4f2c-9664-85ce5d7faed8.png)

![image](https://user-images.githubusercontent.com/21209995/226397596-fa56c00c-f873-4997-b429-f8099a1332b4.png)

![image](https://user-images.githubusercontent.com/21209995/226398820-5ffa6db2-3cec-4e45-b3b1-da22d0ac9014.png)

**Comment by E1izabeth** [comment]
Thank you for bug report. It is a side effect of #19159
We reverted these changes in #19270. The fix will be available in the next release.
