### ISSUE TITLE
dBeaver results tab doesn't properly handle chr(10) and chr(13)

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#19441]
### Description

when writing scripts that contain linefeed, chr(10) and carriage return, chr(13) dBeaver doesn't handle them correctly.

linefeed characters get converted into paragraph symbols
carriage return characters get converted into paragraph symbols

when trying to export the results to the clip board or directly to a text file EOL characters are stripped out. 

### DBeaver Version

Community Edition 23.0.0

### Operating System

Windows 10

### Database and driver

doesn't matter any script that contains chr(10) or chr(13) will do.

### Steps to reproduce

select 'col0' as c0, 'test ' || chr(10) || ' test1' as c1 from dual;

**Comment by ShadelessFox** [comment]
Hello @coleman-rik,

This is expected behavior.

CL/RF are replaced with a displayable symbol in all exporters that don't handle line separators in the middle of a value very well (e.g., CSV, TXT, etc.). If you export as SQL, you will notice that string literals are multi-line.
