### ISSUE TITLE
when "select" ,the result has a yellow lock showing

### ISSUE THREAD

**Issue by mawenlong** [dbeaver/dbeaver#19446]
### Description

when "select" ,the result has a yellow lock showing
![36d1d1cf8626ebe198e8d72215685e64](https://user-images.githubusercontent.com/5250579/226854021-4363b224-9924-42f2-8e2d-c490063261c4.jpg)

### DBeaver Version

Community Edition 23

### Operating System

Windows 7

**Comment by LonwoLonwo** [comment]
Hello @mawenlong 

It means - your resultset is read-only. This usually happens when the ResultSet does not receive enough metadata about the columns.

Please provide your database, query example, and DDL of objects in the query.

**Comment by mawenlong** [comment]
> 

hello @LonwoLonwo 
when I used cli mode to select data for this table,the data showing is good,no lock.
I suspect it's a problem with this tool. Where do I need to set it up

**Comment by LonwoLonwo** [comment]
Please provide your database, query example, and DDL of objects in the query. Then I can help you.

**Comment by uslss** [comment]
There has been no update for a long time.
If issue is still actual for you - feel free to reopen it with additional info

**Comment by dayanneramosgove** [comment]
with me, sometimes dbeaver change the connection to read-only by itself

![image](https://github.com/dbeaver/dbeaver/assets/128706195/15183f77-4839-4a94-acb6-581372ec6413)

**Comment by spedroq** [comment]
The solution for me was simply to restart DBeaver
