### ISSUE TITLE
Export/Import Local History for Scripts

### ISSUE THREAD

**Issue by Xylandor** [dbeaver/dbeaver#19456]
**Is your feature request related to a problem? Please describe.**
When transferring project and script data over to a new computer (e.g. upgraded machine), I'm unable to keep the local history for all my scripts.

**Describe the solution you'd like**
Provide a way for us to export our scripts and their local change history over to a new machine via import; or whatever method is best.

**Describe alternatives you've considered**
I'm using latest macOS Ventura and tried to figure out where the local history data is stored, but unable to find the correct file(s) to move over to new machine.

**Additional context**
Is there a work-around that I can use to get all the local history back on my scripts on the new machine? I keep my project and script files synced with OneDrive. In what directory and file(s) are the scripts' local history stored on a Mac?

**Comment by flambchap** [comment]
Hi @Xylandor. Can you please tell me where to find this local history in DBeaver?

**Comment by E1izabeth** [comment]
It's been a while since no update here, so I'm closing this issue. If it's still actual, please let me know.
