### ISSUE TITLE
copy column definition not trim right blank space in name

### ISSUE THREAD

**Issue by gusbenites** [dbeaver/dbeaver#19451]
### Description

When copying the definition of a column from a table in Informix to another table in Mysql, in the name of the column it adds blank spaces to the right, when it applies and saves it gives an error in the column and it is not because of the data type, when editing the name there are blank spaces on the right, I delete them and it is solved.

Dbeaver Community version 23.0.0.202303040621 
Ubuntu 22.10

The same thing happened in previous versions.

![Captura desde 2023-03-22 08-22-28](https://user-images.githubusercontent.com/33515533/226890627-372dc222-61b0-4142-99ad-db815a3f745a.png)
![Captura desde 2023-03-22 08-23-00](https://user-images.githubusercontent.com/33515533/226890644-91704a2b-efe5-4f78-9a13-9f8f314e84b6.png)
![Captura desde 2023-03-22 08-23-27](https://user-images.githubusercontent.com/33515533/226890656-f1de8a05-b191-410b-86b8-bfd9ccfea0d9.png)

### DBeaver Version

Community edition 23.0.0.202303040621

### Operating System

Ubuntu Desktop 22.10

### Database and driver

Database Mysql 8 y driver mysql 8 and later
Database Informix 7.31 y driver IBM Informix Dynamic Server

### Steps to reproduce

1. I search the Informix database for the table where the column to copy is.
2. I select the column in the table, right click and select copy in the contextual menu.
3. I search the Mysql database for the table, I open edit the columns
4. I paste and the dialog opens showing the information of the column to paste, I click on the button, accept in the dialog box.
5. I finish editing the table by clicking the Save button
6. The error box appears informing that it cannot be recorded due to problems in the column (the one that I copied)
7. I modify the name of the column that I copied and I remove the white spaces on the right.
9. I try to save again and it saves without problems.

**Comment by E1izabeth** [comment]
Could you clarify how do you copy the column name? Do you do it in Properties tab or in Data tab?

**Comment by gusbenites** [comment]
In the tree view of the tables on the left, I select the columns I want to copy and then I go to the destination table and paste them in the tab, properties, column definition section. I've also done it in the tree view on the columns branch and it does the same thing. (GOOGLE TRANSLATE)

**Comment by LonwoLonwo** [comment]
Hello @gusbenites 

Could you please provide the source Informix table DDL?

**Comment by gusbenites** [comment]
It does it with all informix tables. I can't pass you the DDL because it doesn't display it.
Fails
```
/* ERROR WHILE READING SOURCE:

Can't read source code of 'acciones           '
*/
```

**Comment by gusbenites** [comment]
In the error message above, in the name of the table "acciones      " there are some spaces between the word actions and the single quote that the github editor removes them.

**Comment by gusbenites** [comment]
![Captura desde 2023-04-11 13-16-19](https://user-images.githubusercontent.com/33515533/231225401-c79a6ea4-d402-4f52-93c6-1691f16c615f.png)

**Comment by Matvey16** [comment]
@gusbenites Hello, can you add a screenshot of a window that is shown in connection settings when you test connection? It looks like it can be a driver issue and I nedd to know the exact driver that you are using. Like I have this for example

![image](https://user-images.githubusercontent.com/82543000/233352044-2864d2e1-d26c-4557-a4d2-406af9764081.png)

And I can't reproduce it on any table or column.

If it is possible I would like to ask you to create a new test table and try to reproduce it on it

**Comment by gusbenites** [comment]
Monday when I'm at work I check. I know it's not a new version since the new version doesn't connect to my Informix 7.31 database. Will that?

**Comment by gusbenites** [comment]
![Captura desde 2023-04-25 07-22-49](https://user-images.githubusercontent.com/33515533/234248821-8111f560-c4ca-45ba-804c-f715257f6ce0.png)

**Comment by LonwoLonwo** [comment]
Ok, thanks for the report.
