### ISSUE TITLE
MySQL edit query results locked

### ISSUE THREAD

**Issue by Montgomeryz** [dbeaver/dbeaver#19457]
### Description

DBeaver seems to have an issue with query results where the returned columns are read only (including PK in results) and there is an order on the primary key. For example:

select t.*
from gos.tcsi_majors_working t
;
Result set is uneditable.

select t.gosid, t.e307, t.e313
from gos.tcsi_majors_working t
;
Result set is uneditable (gosid is PK, e307+e313 = UI).

select t.GOSID, t.e307, t.e313, t.course_group
from gos.tcsi_majors_working t;
Result set is editable.

select t.GOSID, t.e307, t.e313, t.course_group
from gos.tcsi_majors_working t
order by 1;
Result set is uneditable.

DDL:
CREATE TABLE `tcsi_majors_working` (
  `GOSID` bigint NOT NULL,
  `e307` varchar(60) DEFAULT NULL,
  `e313` varchar(40) DEFAULT NULL,
  `course_group` char(10) DEFAULT NULL,
  `course_short_title` varchar(40) DEFAULT NULL,
  `foe` char(6) DEFAULT NULL,
  `foe_supplementary` char(6) DEFAULT NULL,
  `E308A_MAJFLAG` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `E308B_MAJFLAG` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `maj1` varchar(6) DEFAULT NULL,
  `title1` varchar(150) DEFAULT NULL,
  `maj2` varchar(6) DEFAULT NULL,
  `title2` varchar(150) DEFAULT NULL,
  `maj3` varchar(6) DEFAULT NULL,
  `title3` varchar(150) DEFAULT NULL,
  `maj4` varchar(6) DEFAULT NULL,
  `title4` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`GOSID` DESC),
  KEY `tcsi_majors_working_e307_IDX` (`e307`,`e313`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

### DBeaver Version

Community 23.0.0.202303040621

### Operating System

Windows 11 Enterprise 21H2

### Database and driver

MySQL 8.0.31

### Steps to reproduce

Test on table with ordered primary key.

**Comment by LonwoLonwo** [comment]
Hello @Montgomeryz 

Sometimes it happens right after table creation, then DBeaver doesn't know anything about a new object in the Database navigator tree. Could you let me know if you made this select to the newly created table? Or to the existing one?

**Comment by Montgomeryz** [comment]
Hello. That was an old table, although I did invalidate the connection and refresh the table. Interestingly, sometimes it works if you paste the code in a new editor. Weird..

**Comment by E1izabeth** [comment]
Maybe it's somehow connected with #18843
But we need to reproduce it.

**Comment by LonwoLonwo** [comment]
Hello @Montgomeryz 

Could you please check the newest DBeaver version? Does the issue happen in the latest version?

**Comment by Montgomeryz** [comment]
@LonwoLonwo hello, 535 still has the issue.

**Comment by E1izabeth** [comment]
@Montgomeryz what do you mean by 535? The latest DBeaver version is 23.0.1

**Comment by Montgomeryz** [comment]
@E1izabeth 23.0.1.202303250535

**Comment by E1izabeth** [comment]
Thanks

**Comment by uslss** [comment]
Unfortunately, still cannot reproduce the issue against 23.0.3

**Comment by Montgomeryz** [comment]
Try this:

create table  test
(`id` int not null primary key,
`f2` int,
`f3` int)
as select '1' id,'2' f2,'3' f3;

select * from test;

If there is no refresh, result set will be locked.

**Comment by LonwoLonwo** [comment]
> If there is no refresh

Yes, because DBeaver doesn't know at this point about table metadata. Which is required for table data changing.

You need to refresh the navigator tree first.

Does the original issue reproducible for existing tables for you?

**Comment by Montgomeryz** [comment]
It seems to be behaving :)

**Comment by LonwoLonwo** [comment]
Then - again, we need to reproduce it to fix it. Please, provide us an example of the incorrectly recognized result set metadata in the case of existing tables.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.
