### ISSUE TITLE
Open a modele

### ISSUE THREAD

**Issue by Ferrox12** [dbeaver/dbeaver#19450]
Hi,
is there a method to save a SQL sheet as a Model and then open it everytime I open some connections?

**Comment by E1izabeth** [comment]
Could you clarify what exactly do you mean by "Model"?

**Comment by Ferrox12** [comment]
A sheet with the same instructions

**Comment by LonwoLonwo** [comment]
Hello @Ferrox12 

Could you clarify - what sheet? What instruction? Please, provide more examples.

**Comment by Ferrox12** [comment]
In my case when I open a connection I must execute a SQL command. Is there a method to open automatically in the sheet this query?

**Comment by Destrolaric** [comment]
@Ferrox12 Is Datasets something that you are looking for?
https://dbeaver.com/2023/03/24/roles-in-team-edition-manager-editor-viewer/#:~:text=The%20concept%20of%20Datasets

**Comment by Ferrox12** [comment]
Sorry for "Model" I mean a Script that has to be run everytime I open a connection

**Comment by Destrolaric** [comment]
@Ferrox12 You can try adding bootstrap queries in the connection settings
![image](https://user-images.githubusercontent.com/20579256/228867105-1d8482fd-3dfd-49da-8595-f15516026a85.png)

**Comment by Ferrox12** [comment]
Thank you very much!!!

**Comment by Destrolaric** [comment]
@Ferrox12 I am closing the issue. I wish a nice experience working with the DBeaver
