### ISSUE TITLE
Synapse SQL Connectivity failing with below error ( MFA Authentication)

### ISSUE THREAD

**Issue by sqlserverlabs** [dbeaver/dbeaver#19464]
### Description

Failed to load MSAL4J Java library for performing ActiveDirectoryInteractive authentication.

### DBeaver Version

23.0.0.202303040621

**Comment by LonwoLonwo** [comment]
Please try to do this:

```
Go to "Edit Driver Settings," click the "Libraries" tab, then click "Add Artifact," then add the Maven dependency declaration:

<!-- https://mvnrepository.com/artifact/com.microsoft.azure/msal4j --> <dependency> <groupId>com.microsoft.azure</groupId> <artifactId>msal4j</artifactId> <version>1.11.3</version> </dependency> 
```

https://github.com/dbeaver/dbeaver/issues/15446#issuecomment-1097140996

**Comment by sqlserverlabs** [comment]
i did and i got something else now
Login failed for user '<token-identified principal>'. ClientConnectionId:c8830a53-8d24-405a-b39a-813927bcb290

**Comment by sqlserverlabs** [comment]
i was able to make connection now, but got this error then
Reference to database and/or server name in 'synapsedb.sys.schemas' is not supported in this version of SQL Server.

**Comment by LonwoLonwo** [comment]
> Reference to database and/or server name in 'synapsedb.sys.schemas' is not supported in this version of SQL Server.

This is a knowing issue. Described here: https://github.com/dbeaver/dbeaver/issues/5258

Azure does not support cross-database queries, so our advice is to use separate connections for the separate databases.

https://github.com/dbeaver/dbeaver/issues/5258#issuecomment-1205089619
