### ISSUE TITLE
Create a "New window" from "DBeaver - Can't lock workspace" dialog

### ISSUE THREAD

**Issue by enboig** [dbeaver/dbeaver#19463]
**Is your feature request related to a problem? Please describe.**
I am using multiple workspaces (one for dev, prod, ...); to have different dbeaver windows require to the workspace where I have a dbeaver window, create a new window, and move the new window to my actual workspace

**Describe the solution you'd like**
When opening "again" dbreaver, I can choose `ignore`, `retry`, `abort`. A `New window` option would be great.

**Comment by E1izabeth** [comment]
Have you tried running second DBeaver instance with `-reuseWorkspace` parameter?
https://dbeaver.com/docs/wiki/Command-Line/

**Comment by enboig** [comment]
I didn't know about this option; I will change my "system menu entry" to use it.
It will solve my problem, but adding the button may help other people (and me, if I forget to modify the program in my next system reinstall)
