### ISSUE TITLE
URL Scheme to launch database in projects

### ISSUE THREAD

**Issue by nagauta** [dbeaver/dbeaver#19465]
**Is your feature request related to a problem? Please describe.**
I want url scheme like below to launch open database via launcher tools(like Raycast).
https://github.com/Sequel-Ace/Sequel-Ace/pull/1447/files

I couldn't search the feature in docs and codes...

**Describe the solution you'd like**
I want to launch a certain database with DBeaver using url scheme.
dbeaver://?connect=General/db_name
then DBeaver launch and db_name will be open!
I also want the url scheme to get list projects.

**Describe alternatives you've considered**
i have no ideas about others.

**Additional context**
I imagine it like below.
using laucher tool, list dababases and if I choose one then database. will open via url scheme(deeplink) with DBeaver.
![sequel-ace 2023-03-23 at 23 10 50](https://user-images.githubusercontent.com/44369261/227230268-7764afe5-9412-471b-a6c5-5541e4f1d363.png)

**Comment by E1izabeth** [comment]
Please, explain what do you mean when talking about opening database?

**Comment by uslss** [comment]
There has been no update for a long time.
If the request is still actual for you - feel free to reopen it with additional info.
