### ISSUE TITLE
Unable to see and query Redshift Spectrum

### ISSUE THREAD

**Issue by jshe6732** [dbeaver/dbeaver#19466]
### Description

Hello!  I installed the redshift driver and trying to query redshift spectrum tables.  The regular tables show up but the ones from s3 buckets do not display nor am able to query.  Please help.

### DBeaver Version

CE 23.0.0.202303040621

### Operating System

macOS Ventura 13.2.1 (22D68)

### Database and driver

1. Amazon Redshift
2. Amazon Redshift 

### Steps to reproduce

1. Download the latest version of Dbeaver and redshift drivers
2. Connect to Redshift Spectrum
3. Try to find or query external tables (S3 buckets)

**Comment by LonwoLonwo** [comment]
Hello @jshe6732 

Could you please test it in the Early Acces version? Probably, the issue is already fixed and will be available in the next release.

https://dbeaver.io/files/ea/

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
