### ISSUE TITLE
Too many connection open connecting to Greenplum database

### ISSUE THREAD

**Issue by sachiojha** [dbeaver/dbeaver#19479]
### Description

After upgrading to DBeaver Enterprise 22.2.0, we bagan experiencing  this issue. When I connect to Greenplum database, Dbeaver automatically open another 8 connection which are always in the idle state. Since my user id has max 8 connection limit so I keep getting too many open connection error. 

Killing those connection resolves this issue temporarily .

### DBeaver Version

Enterprise Edition 22.2.0

### Operating System

Windows 10

### Database and driver

Greenplum 5.28.7 and 6.19

### Steps to reproduce

Starting Dbeaver and connecting to the database

**Comment by E1izabeth** [comment]
Have you configured these settings https://github.com/dbeaver/dbeaver/wiki/Separate-Connections?

**Comment by sachiojha** [comment]
Yes. we did. BTW  options in the link you presented are different than what we see when connecting to Tanzu Greenplum database. These options are not available. 
We tried few settings based on knowledge base using this forum . Windows ->Connections --> Metadata --> Open Separate connections for Metadata read ( tried ON and OFF both settings)  and Windows ->Connections --> Transactions --> Automatically end long idle transactions to 300. None of these settings resolved the issue permanently.

**Comment by flambchap** [comment]
I'm closing the issue as it's been resolved via the support system on our website.

**Comment by sachiojha** [comment]
I did not see any guidance which fix this issue. Not sure why this issue is closed?

**Comment by E1izabeth** [comment]
Haven't you discussed it with our technical support on our technical support site?

**Comment by sachiojha** [comment]
No.

**Comment by iraidaa** [comment]
Hi @sachiojha,

We have created the ticket on your behalf in the online support system on the DBeaver website. There is a tab called "Tickets"  in your personal account on the website. Please check it.

Please let us know if you have any questions.

**Comment by E1izabeth** [comment]
It's been a while since no update here, so I'm closing this issue. If it's still actual, please, let me know.
