### ISSUE TITLE
Metadata not loading for QSYS and QSYS2 schemas - DB2 for IBM i

### ISSUE THREAD

**Issue by kcaesar-rfhl** [dbeaver/dbeaver#19473]
### Description

On current version of DBeaver when I connect to any IBM i environment, I am no longer able to get metadata info for the QSYS and QSYS2 IBM i system schemas. They do not appear as available schema in the Database Navigator and do not appear in the auto-complete list for the FROM clause. However, if you execute a query over one of the tables or views stored therein, it will return results.

![image](https://user-images.githubusercontent.com/55899829/227364618-8969822c-de07-4c79-b793-b8adb85be3c2.png)

![image](https://user-images.githubusercontent.com/55899829/227364790-a3dca2c7-c373-4959-94ef-da4f59785007.png)

![image](https://user-images.githubusercontent.com/55899829/227365908-659bbe8e-6ff6-4c06-8262-a07da44c9b56.png)

![image](https://user-images.githubusercontent.com/55899829/227365566-97b569de-9e19-4b7d-b338-2880252b107f.png)

### DBeaver Version

Community Edition 23.0.0

### Operating System

Windows 10 Pro

### Database and driver

Db2 for IBM i 
11.2

### Steps to reproduce

1. Connect to IBM i Database
2. Attempt to select schemas from Database Navigator or attempt to get the schema list in the FROM clause of a select statement.

### Additional context

This was working in previous versions.

**Comment by LonwoLonwo** [comment]
Hello @kc-rfhl 

Please check the state of your connection view.

Click on your connection in the Database Navigator tree and change your view type to "Advanced" mode, which shows system objects.

![2023-03-10 12_30_19-DBeaver Ultimate 22 3 2 - _localhost 4_ Script-94](https://user-images.githubusercontent.com/45152336/227458830-e409a480-6f0d-4164-8048-d3a92cd9f401.png)

**Comment by kcaesar-rfhl** [comment]
Thank you very much. That resolved the issue. However, is there a reason that that option is not also accessible from the configuration pane? That seems to be the logical place where someone would look for a toggle like that.

![image](https://user-images.githubusercontent.com/55899829/227472590-e1e7ff08-7872-4209-8add-5e1d227b3675.png)

**Comment by LonwoLonwo** [comment]
> is not also accessible from the configuration pane

What exactly configuration panel do you mean?

**Comment by LonwoLonwo** [comment]
As you correctly mentioned - you also can change this setting in your Connection Settings. And with the right click on your connection.

And in the Preferences - Connection (for the new created connections)

![2023-03-24 18_12_11-AnyDesk](https://user-images.githubusercontent.com/45152336/227565792-39f9e2fb-cbb8-4299-a29d-22d548924b47.png)
