### ISSUE TITLE
The Database Toolbar cannot be made visible because all its children are in an unavailable action set.

### ISSUE THREAD

**Issue by wpf97** [dbeaver/dbeaver#19477]
### Description
[Screenshot](https://github.com/wpf97/test/blob/main/11.jpg)

### DBeaver Version

23.0

### Operating System

macos 12.4

### Database and driver

The Database Toolbar cannot be made visible because all its children are in an unavailable action set.

**Comment by E1izabeth** [comment]
Do you use DBeaver as a standalone application or as an Eclipse plugin?

**Comment by E1izabeth** [comment]
I suppose it's a duplicate of #19495

**Comment by E1izabeth** [comment]
The issue should be fixed in DBeaver 23.0.2
