### ISSUE TITLE
Add a Transpose View option to the table preview window

### ISSUE THREAD

**Issue by DeflateAwning** [dbeaver/dbeaver#19474]
**Is your feature request related to a problem? Please describe.**
Sometimes I'm looking at a very large table with many, many columns. I want to be able to see more columns at once, which would be possible if there was a transposed view. Obviously you'd only get to see a few "rows" at a time, but that's okay. 

**Describe the solution you'd like**
I want to click a button in the Table Data view, and see the table preview transposed (i.e., columns are shown as rows and rows are shown as columns). 

**Describe alternatives you've considered**
Advanced SQL queries can do this; otherwise, you'd need to get the data over in a tool like Excel or Python to do this operation.

**Comment by ShadelessFox** [comment]
Hello @DeflateAwning,

You can enable the record view by pressing <kbd>Tab</kbd> or by clicking on the "Record" button on the bottom left:

![image](https://user-images.githubusercontent.com/35821147/227408485-a6c0a5e6-f40a-40d3-a037-e97ccca37903.png)

Please let me know if it solves your issue.

**Comment by DeflateAwning** [comment]
Record view solves my problem, thanks!
