### ISSUE TITLE
"Hide column [Column Name]" In Context Menu Will Hide The Wrong Column

### ISSUE THREAD

**Issue by BenjaminWKI** [dbeaver/dbeaver#19475]
### Description

When right clicking on the column header in the Data Editor window, the context menu will show the option 

> Hide column [Column Name]

Selecting that item will not hide the column named in the context menu item but instead will hide the column that the cursor is located on instead.

### DBeaver Version

23.0.0.202303040621

### Operating System

Windows 10

### Database and driver

MariaDB 

### Steps to reproduce

1. Open a Data Editor window to a table containing data. 
2. Right click one of the data column headers. 
3. Select "Hide column ... " option to try and hide the named column

**Comment by ShadelessFox** [comment]
Hello @BenjaminWKI,

Can you please provide footage showing the issue?

I'm unsure how one is supposed to hover over a column header while clicking on a menu item.

**Comment by BenjaminWKI** [comment]
![dbeaver_2023-03-27_11-33-18](https://user-images.githubusercontent.com/33195298/227815194-91d1984a-6850-435d-86a3-75cd7f3268a9.gif)

**Comment by ShadelessFox** [comment]
I was able to reproduce the issue. Thank you.

**Comment by serge-rider** [comment]
Fixed (focus column will be used in command handler)
