### ISSUE TITLE
Network Error - Unable to find valid certification path to requested target - When attempting to download driver

### ISSUE THREAD

**Issue by shazzner** [dbeaver/dbeaver#19471]
### Description

Brand new install of dbeaver, 23.0.0, on macOS Ventura 13.2.1. I attempt to create a new mssql connection but it fails when I try to connect. Clicking on the Driver libraries I get the error message below which doesn't allow me to click to download the driver or do anything else. As such I'm unable to connect to any database.

![Screenshot 2023-03-23 at 11 42 31 AM](https://user-images.githubusercontent.com/691304/227318375-55754db4-4be7-44fd-ae0a-9a7a67b37396.png)

### DBeaver Version

Community Edition 23.0.0

### Operating System

macOS Ventura 13.2.1

### Database and driver

SQL Server 11.2.3.jre11
SQL Server 11.2.3.x64

### Steps to reproduce

1. Edit Connection
2. Click on Driver Settings
3. Click on the Libraries tab
4. Click on Download/Update

**Comment by Pacerino** [comment]
I've got the same scenario on a fresh install running on Windows 10 freshly installed!

**Comment by shazzner** [comment]
Looks like I managed to fix it, it was due to my work's firewall/vpn settings. Once I disconnected, and was on normal wifi, I was able to download the driver and get things to work.

I'll leave this open since the solution wasn't terribly intuitive for me.

**Comment by E1izabeth** [comment]
@Pacerino please uncheck the `Use Windows trust store` setting in `Preferences->Connections` and restart DBeaver. It should help.
![image](https://user-images.githubusercontent.com/28875055/227789196-04fe3b1a-ed2d-4dae-96ab-5aa27b2a41d9.png)

**Comment by E1izabeth** [comment]
@shazzner if you encounter this issue again under firewall this article might help https://dbeaver.com/docs/wiki/Importing-CA-Certificates-into-DBeaver/

**Comment by chadmyers** [comment]
@E1izabeth Is there a way to get DBeaver to install on Windows where it doesn't always require turning off the "Use Windows trust store" option?

Also that link to the wiki above (https://dbeaver.com/docs/wiki/Importing-CA-Certificates-into-DBeaver/) is broken. Do you know what the updated URL is?

Thanks!

**Comment by E1izabeth** [comment]
@chadmyers  the error may be caused by lots of reasons connected to the environment, sometimes you don't need to touch this setting at all.

Wiki page
https://github.com/dbeaver/dbeaver/wiki/Importing-CA-certificates-from-your-local-Java-into-DBeaver
