### ISSUE TITLE
tip Unknown system variable 'query_cache_size'

### ISSUE THREAD

**Issue by chenxdGithub** [dbeaver/dbeaver#19480]
### Description

1 connect sharding-proxy- 5.2.0 tip   Unknown system variable 'query_cache_size'
2 driver-class-name: com.mysql.cj.jdbc.Driver

### DBeaver Version

23.0.0.202303040621

### Operating System

macos Ventura  13.2.1 (22D68)

### Database and driver

1 connect sharding-proxy- 5.2.0 tip   Unknown system variable 'query_cache_size'
2 driver-class-name: com.mysql.cj.jdbc.Driver

### Steps to reproduce

1 connect sharding-proxy- 5.2.0 tip   Unknown system variable 'query_cache_size'
2 driver-class-name: com.mysql.cj.jdbc.Driver

### Additional context

1 connect sharding-proxy- 5.2.0 tip   Unknown system variable 'query_cache_size'
2 driver-class-name: com.mysql.cj.jdbc.Driver

**Comment by LonwoLonwo** [comment]
Hello @chenxdGithub 
What database version do you use?
What driver version do you use?

**Comment by chenxdGithub** [comment]
database-proxy version is  sharding-proxy- 5.2.0
database version  is 8.0.22
driver version 8.0.29

**Comment by chenxdGithub** [comment]
> Hello @chenxdGithub What database version do you use? What driver version do you use?

database-proxy version is sharding-proxy- 5.2.0
database version is 8.0.22
driver version 8.0.29

**Comment by LonwoLonwo** [comment]
Probably driver version changing can help in your case.

Please try to change it in your Connection settings -> Driver Settings -> Libraries -> Update.

![2023-03-09 12_27_59-Driver settings](https://user-images.githubusercontent.com/45152336/227862262-23ca099a-7987-494c-9b1d-f631f7f52f90.png)

(Example from another database, but the way is the same)

First, you can choose the driver version like your server version - 8.0.22. If it does not help - you can try to connect to your database with the new connection with provider MySQL 5.

![2023-03-27 09_52_31-Window](https://user-images.githubusercontent.com/45152336/227863005-bbd8b9a2-87b6-4dcc-b8eb-364c6b96ce9f.png)

**Comment by chenxdGithub** [comment]
But I have tried the 8.0.22 driver and mysql5, but it still doesn’t work. Is there
any other solution?

**Comment by ShadelessFox** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual for you, please let me know.
