### ISSUE TITLE
Double click when navigating in ER Diagram

### ISSUE THREAD

**Issue by vimar** [dbeaver/dbeaver#19492]
### Description

When navigating in database using ER Diagram, the double click to open ER Diagram for another table no longer works after the upgrade.

Strangely, this does not only work on a colleague's workstation.

I have the same version and the double click continues to work.

There's a setting somewhere to toggle this feature?

### DBeaver Version

Community Edition 23.0.1 in French

### Operating System

Ubuntu 22.04.1

**Comment by E1izabeth** [comment]
There is no setting for that. Probably, it's a bug.
Could you reproduce this issue and then send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
