### ISSUE TITLE
Cickhouse UInt64 display values

### ISSUE THREAD

**Issue by UseinF** [dbeaver/dbeaver#19490]
### Description

DBeaver displays incorrectly a values of the UInt64 data type for Clickhouse, possibly due to the fact that UInt64 mapping to the long Java data type.
Clickhouse [Supported data types](https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/en/integrations/language-clients/java/index.md?ysclid=lfqikfngqx503330283#supported-data-types)

### DBeaver Version

23.0.1

### Steps to reproduce

CREATE TABLE uint64test (
  id UInt64
)
ENGINE = MergeTree
ORDER BY id;

INSERT INTO uint64test(id)
VALUES (14455996476406444606), (16553254873430290414);

SELECT id, CAST(id AS String) str
FROM uint64test;

id                  |str                 |
--------------------+--------------------+
 4524039566587494706|14455996476406444606|
17214368532876185839|16553254873430290414|

**Comment by LonwoLonwo** [comment]
Hello @UseinF 

What database version do you use?
What driver version do you use?

**Comment by UseinF** [comment]
Hello @LonwoLonwo 
Database: ClickHouse server version 22.12.1 revision 54461.
Driver: Yandex ClickHouse driver (server version 21.3+)
It does not depend on the version. In this case need to use java.lang.Long.toUnsignedString(long) instead of java.lang.Long.toString()

**Comment by LonwoLonwo** [comment]
Please provide also a screen from Preferences -> Editors -> Data Editor -> Data formats

**Comment by LonwoLonwo** [comment]
Have you tried using another Clickhouse provider?
I'm not sure that legacy Clickhouse correctly returns this data type data.

 
![2023-04-06 12_46_41-Connect to a database](https://user-images.githubusercontent.com/45152336/230340939-48aebe52-1efa-4701-8d01-8ecc0826d3a1.png)

**Comment by UseinF** [comment]
D isplays incorrectly with both drivers.

**Comment by LonwoLonwo** [comment]
Please provide a screen from your Data Formats Preference page. Preferences -> Editors -> Data Editor -> Data Formats

**Comment by LonwoLonwo** [comment]
For now, I can't reproduce your issue. (On the newest bot legacy driver)

![2023-04-10 11_24_35-DBeaver Ultimate 23 0 2 - _default_ Script-71](https://user-images.githubusercontent.com/45152336/230862502-4bae29ef-6d60-47db-96a3-e8f7d6c89659.png)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.
