### ISSUE TITLE
grid text will be shield ,when enlarging font.

### ISSUE THREAD

**Issue by HaoWenQiang** [dbeaver/dbeaver#19493]
### Description

 enlarging font , the text in the list tree  will be shield.

i wanna give u the screen shot ,but i don't found how upload image there.

### DBeaver Version

Version 23.0.0.202303040621

**Comment by HaoWenQiang** [comment]
in other word, font enlarged but the grid not .

**Comment by E1izabeth** [comment]
To attach image or document you can click on this area
![image](https://user-images.githubusercontent.com/28875055/229529798-a1ef4bb5-91de-4b1e-b60f-8ba63a01b0d8.png)

**Comment by E1izabeth** [comment]
Could you attach a screenshot please? Also I wonder about your operation system as It seems I can't reproduce it on Windows 10.

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
