### ISSUE TITLE
CTRL + +  or CTRL + -  does not work for increase or decrease size (in script or grid)

### ISSUE THREAD

**Issue by renezito** [dbeaver/dbeaver#19521]
### Description

Hi, When I'm writing the script this combination to increase or decrease size (in script or grid) works very good, but sometimes stop working and I have to restart dbeaver.  I can save a video because you can´t see my keyboard :D

![image](https://user-images.githubusercontent.com/37661233/228284820-676a4f47-d043-4f21-9ff3-e48d6cbff9e9.png)

Note: In previus version, the problem also existed.

Note 2: After I run the script, the size increments or decrements, but I have to run the query.

### DBeaver Version

Community Edition 23.0.1

### Operating System

Windows 10 Pro

### Steps to reproduce

1. Open a new script
2. type a select or whatever
3. press ctrl +   to increaes font size
4. if it work... continuos working and a few minutes/hours later, try it again.
5.

**Comment by ghYura** [comment]
NotaBene: that's where my FW could help for any QA-tester's automation (optional steps that expand every TC). Particularly, steps that add optional delay(s) in between and/or possibly side-affecting extra action(s).  FW dev-n-test - in progress...
[Details](https://www.youtube.com/channel/UCaZT2pB_OrGwpZN-AV1sxEQ)

**Comment by E1izabeth** [comment]
Steps to reproduce which works stable for me, provided in #19600:

1. Open DBeaver (I have scripts saved that automatically open haven't figured out if this matters or not)
2. Zoom in (to verify it is working)
3. Go to Projects and double click a project to open it on the right panel.
4. Close the Projects view that just opened
5. Attempt to zoom in again. (should not zoom in)
6. Restart DBeaver (the zoom should be what it was supposed to be)

**Comment by ghYura** [comment]
@E1izabeth is this zoom "saved-after" state documented at all anywhere? It is a double sence when come to what zoom scale factor should be after DBeaver restart? Maybe default scale after restart to its default is the right option for someones (unleast it is documented for vast majority users as right behavior)
Thanks for reply for this

**Comment by E1izabeth** [comment]
As far as I know, it's not documented

**Comment by serge-rider** [comment]
Fixed

**Comment by renezito** [comment]
@serge-rider  Thansk a lot !!!   When will be this fix available?  I'm using 23.0.2.202304091457

**Comment by E1izabeth** [comment]
It will be available in the next release.

**Comment by renezito** [comment]
Thank you very much !   ... and thanks for ur great job
