### ISSUE TITLE
Crash when closing detached editor tab in another window

### ISSUE THREAD

**Issue by nicchristeller** [dbeaver/dbeaver#19526]
### Description

**Actual**

When closing a detached resultset tab that has been moved into it's own window, DBeaver crashes

**Expected**

No crash

**Logs**

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/11094106/dbeaver-debug.log)

### DBeaver Version

Community Version 23.0.1.202303250535

### Operating System

MacOS 12.6.3

### Steps to reproduce

1. Execute any query (to get a resultset tab)
2. Right click on the resultset tab header, then select "Detach Tab"
    - tab will open alongside editor tabs
3. Right click on resultset tab alongside editor tab, then select "Detach"
    - tab will open in modal window
4. Close the tab (using either the X button on the tab, or the close button of the window)
5. DBeaver exits entirely

**Comment by ShadelessFox** [comment]
Hello @nicchristeller,

Thanks for the bug report.

It looks like the issue has the same roots as #12285. It's caused by out-of-order resource disposal.

**Comment by serge-rider** [comment]
Fixed
