### ISSUE TITLE
wrong automatic sql hint 

### ISSUE THREAD

**Issue by T0toRo** [dbeaver/dbeaver#19530]
### Description

wrong authomatic sql hint 

### DBeaver Version

community edition 23.0.1

### Operating System

windows 11 64bit

### Database and driver

postgresql 14

### Steps to reproduce

1. write SQL in SQL editor
select with table alias

SELECT * from greate_project gp where gp.ele
2. DBeaver show help hint with alias  "gp.election_id"
![image](https://user-images.githubusercontent.com/55893165/228533906-08f02db5-802f-4ab8-b8fe-625d12a85b79.png)

it is wrong, because if we choice DBeaver hint, we see wrong SQL query

![image](https://user-images.githubusercontent.com/55893165/228533964-9993d3ac-b0e1-417f-b21a-49be9feb9041.png)

### Additional context

I did not notice this behavior on the previous version.

the hint that I can choose must not contain an alias

**Comment by LonwoLonwo** [comment]
Hello @T0toRo 

Unfortunately, I can't reproduce it for now.

![2023-03-29 16_18_15-](https://user-images.githubusercontent.com/45152336/228551124-3e31fbd0-f969-43e6-96d0-771926b3addd.png)

Could you provide the whole query?

And screen from this preference page: Preferences -> Editors -> SQL Editor -> Code completion

**Comment by T0toRo** [comment]
Unfortunately after reboot Dbeaver this truble not repeated 
![image](https://user-images.githubusercontent.com/55893165/229023045-3866d058-5744-4b65-a73f-8a0c79569905.png)

**Comment by E1izabeth** [comment]
The question about your preference page is still actual, even if the issue can't be reproduced stable.
Also please let us know, if you meet this issue again and provide the text of such query.

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.

**Comment by detkliff** [comment]
no desigion. This bug in 25.2.0 version
