### ISSUE TITLE
Connecting to Hive database over Kerberos: "GSS initiate failed"

### ISSUE THREAD

**Issue by mtdeguzis** [dbeaver/dbeaver#1953]
```
Could not open client transport with JDBC Uri: jdbc:hive2://server.host.com:10000/;principal=hive/server.host.com@HOST.COM: GSS initiate failed
  org.apache.thrift.transport.TTransportException: GSS initiate failed
```

All the proper jars seem to be in place. I have verified this works just fine with beeline:

```
beeline -u jdbc:hive2://server.host.com:10000/;principal=hive/server.host.com@HOST.COM
```

I tried adding args to the command line and dbeaver.ini file, but they seem to be ignored:

cmdline
```
C:\DBeaver64\Dbeaver.exe -data C:\DBeaver64\dbeaver-data -vmwargs -java.security.krb5.debug=true -java.security.krb5.conf="C:\Dbeaver64\jre\lib\security\krb5.conf" -javax.security.auth.useSubjectCredsOnly=false
```

dbeaver.ini
```
-startup
plugins/org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.401.v20161122-1740
-showsplash
-vmargs
-Xms128m
-Xmx2048m
-Djava.security.krb5.debug=true
-Djava.security.krb5.conf="C:\Dbeaver64\jre\lib\security\krb5.conf"
-Djavax.security.auth.useSubjectCredsOnly=false
```

I have verified a valid keytab is on the Windows sytem with `klist`. I captured a trace with Windows SysInternals ProcMon, and saw no reading of dbeaver.ini.

**Comment by serge-rider** [comment]
Check this ticket: #1036

**Comment by mtdeguzis** [comment]
The example in one of the posts:
```
URL template: jdbc:hive2://{host}:{port}/{database};AuthMech=1;KrbRealm=FOO.BAR;KrbHostFQDN={server}; KrbServiceName=hive;KrbAuthType=2
```
Didn't work for us using one of 2 kdc FQDN's for the "server' part. Why would the beeline jdbc work? I will revisit this with a coworker hopefully in the next day or two

We do not have issues with knit on Linux hosts. Not sure how to test 'kinit' - like behavior on Windows.

**Comment by mtdeguzis** [comment]
We were able to make a Connection in Windows with a small java program, making use of:
```
  7 import java.sql.Connection;
  8 import java.sql.DriverManager;
  9 import java.sql.ResultSet;
 10 import java.sql.Statement;
 11 import org.apache.hadoop.security.UserGroupInformation;
```

**Comment by mtdeguzis** [comment]
We got this working. For those using Hortonworks HiveServer2 with Kerberos, this is what you need to do (providing your kerberos / kr5.conf is valid on your target host):

Plus signs are for diff representation only.

dbeaver.ini:
```
-startup
plugins/org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.401.v20161122-1740
-showsplash
-vmargs
-Xms128m
-Xmx2048m
+ -Djavax.security.auth.useSubjectCredsOnly=false
+ -Djava.security.krb5.conf="krb5.conf"
```

Place the krb5.conf in the main installation path, or provide a path to it. After debugging for hours, and checking traces and more, this is wall it took.

**Comment by mtdeguzis** [comment]
Turns out this is only seemingly doable if you use knit in the `jre/bin` folder (using portable install here on Window). I am not sure where Windows stores it's tickets, if even in a readable form. When you kinit, it stores in `C:\Users\<username>\krb5cc_<username>.`  There must be a way to user the tickets Windows has.

**Comment by serge-rider** [comment]
Thanks for information.

No, there is no any special support of SSPI in DBeaver. But maybe it should there.
Please create separate feature request. Probably there are some existing Eclipse plugins which will simplify the task.

**Comment by mtdeguzis** [comment]
I am wondering why kint.exe is in `jre/bin`? Is it used somehow? For now, we wrote a powershell script via a "Before Connect" shell sequence. This will  prompt the user with `kinit.exe` if certain conditions are not met. Can Dbeaver integrate kinit.exe to obtain a ticket?

**Comment by serge-rider** [comment]
It is a part of standard JRE (http://docs.oracle.com/javase/8/docs/technotes/tools/windows/kinit.html).
Potentially yes, DBeaver can use it to obtain a ticket.

**Comment by mtdeguzis** [comment]
I have also found that if the application is left open until the ticket expires server side, I get a GSS failed, even if my powershell script removes the ticket file in C:\Users\name\

```
Could not open client transport with JDBC Uri: jdbc:hive2://HOST.DOMAIN.COM:PORT/;principal=hive/HOST.DOMAIN.COM@HOST.COM: GSS initiate failed
  org.apache.hive.org.apache.thrift.transport.TTransportException: GSS initiate failed
```

Is there file that holds session information that could cause this to fail? Closing and reopening the application allows the connection to proceed just fine.

**Comment by tati-kru** [comment]
This ticket will be closed because another ticket was created.
