### ISSUE TITLE
Project, Navigator etc. windows do not autoscroll

### ISSUE THREAD

**Issue by RichardSCarchitect** [dbeaver/dbeaver#19542]
### Description

When you drag an item (for example a script) up or down the Project window, if you reach the top or bottom of the window you cannot scroll to other items that are there but not displayed

### DBeaver Version

Community Edition 22.3.5

### Operating System

Windows 10 Enterprise

### Database and driver

Any

### Steps to reproduce

Have a project with lots of scripts divided between several folders
Open the Project window
Open one folder near the top, click and drag one script to move to another folder near the bottom.  The target folder is not displayed because it's too far down
As you drag to the bottom of the window, the window does not scroll down to show the target folder

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by micheal-icp** [comment]
@E1izabeth

It's been well over a year since this was reported. Is it possible we could revisit this and get the auto-scrolling in the project and navigator windows implemented? It is such a big pain when you are having to move scripts around within a big nest of script folders and projects.

**Comment by E1izabeth** [comment]
@micheal-icp 
You can vote for the issue with 👍 under the issue description to promote it to a higher priority.

**Comment by micheal-icp** [comment]
@E1izabeth 

I thumbed it up, but I had no idea we had to upvote bugs. I thought that was for feature requests. This ticket was flagged as a bug, not feature request.

**Comment by arhayka** [comment]
This was fixed in version 24.3.0
