### ISSUE TITLE
Remove filters and navigation from Grouping panel

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#19549]
### Description

We need to remove filters and the navigation bar from the Grouping panel. This doesn't seem to work.

![image](https://user-images.githubusercontent.com/12581569/228865098-da1159d1-b29b-4dd5-a153-dc91e053c242.png)

### DBeaver Version

CE 23.0.1

**Comment by E1izabeth** [comment]
Done https://github.com/dbeaver/dbeaver/commit/60465f53033fbaf474057e323f36e702661068e7
