### ISSUE TITLE
Unable to select "bigint" as column target type when using data import to create a new table.

### ISSUE THREAD

**Issue by dangelsaurus** [dbeaver/dbeaver#19541]
### Description

When using "Import Data" to auto-create a new table, if you try to change the target column type, "bigint" is not an option.

![image](https://user-images.githubusercontent.com/12521900/228707112-ee0ecd12-0a40-41ba-9653-a1cab7adc148.png)

### DBeaver Version

Community Edition 23.0.1.202303250535

### Operating System

Windows 10

### Database and driver

PostgreSQL 15.2 (Ubuntu 15.2-1.pgdg22.04+1)
PostgreSQL JDBC Driver 42.5.0

### Steps to reproduce

Right click a schema name -> Import Data
Select a file to import -> Next
On "Tables mapping" screen, select "Configure", and under "Target Type", **bigint** will not be an option.

**Comment by LonwoLonwo** [comment]
Reproducible. Thanks for the bug report @dangelsaurus 

As a workaround - you can write the target type name in the target type field.

![2023-03-30 12_55_35-Configure metadata structure](https://user-images.githubusercontent.com/45152336/228800314-60c90dbf-3ff8-4717-b549-62f3f19fac66.png)
