### ISSUE TITLE
View comments are not displayed on the object 'Properties' window for Databricks

### ISSUE THREAD

**Issue by RichardSCarchitect** [dbeaver/dbeaver#19540]
### Description

The Properties window for Databricks tables has a 'Table Description' section where you can see the COMMENT ON TABLE comments.  This window is missing on the Properties window of views. 

### DBeaver Version

Community Edition 22.3.5

### Operating System

Windows 10 Enterprise

### Database and driver

Databricks on Azure
Driver: Azure Databricks (Native)

### Steps to reproduce

Connect to Databricks SQL cluster, double click on a view that has a COMMENT ON comment, open Properties tag: view comments are not displayed.  Column comments are displayed in the Columns tag 'Description' field

**Comment by LonwoLonwo** [comment]
Hello @RichardSCarchitect 

Could you please point me to the documentation that says you can comment on views in Databricks on Azure?

If I do COMMENT ON TABLE on my view, I've got this:

`SQL Error [500051] [HY000]: [Simba][SparkJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: org.apache.hive.service.cli.HiveSQLException: Error running query: org.apache.spark.sql.AnalysisException: hive_metastore.default.newview is a view. 'COMMENT ON TABLE' `

And documentation also says about TABLE not view: https://docs.databricks.com/sql/language-manual/sql-ref-syntax-ddl-comment.html

**Comment by RichardSCarchitect** [comment]
Hello

CREATE OR REPLACE VIEW innovation_supplychain.`odw-idh-poc_datamart_1`.date_sap_transform
(UTC_yyyy_mm_dd_nk, 
UTC_yyyy,
UTC_calendar_quarter_number,
UTC_mm,
UTC_calendar_week_of_year_number,
UTC_dd,
UTC_calendar_day_of_year_number,
UTC_calendar_month_name,
UTC_calendar_day_of_week_name,
DATETIME_SAP,
DATE_SAP)
COMMENT 'Transforms different Systems Of Record timestamps into conformed date values based on *redacted*.'
AS 
SELECT
DATE_SQL, 
YEAR_INT,
QUARTER_INT,
MONTH_INT,
WEEK_INT,
blah plah blah


ps we are on Azure databricks.  I can see the view comment in the Databricks web GUI.

**Comment by LonwoLonwo** [comment]
Ok, thanks for the report.
