### ISSUE TITLE
How to enable SSL connection for DB2 LUW

### ISSUE THREAD

**Issue by SriniRaviKrishna** [dbeaver/dbeaver#1954]
Is there a step by step documentation of enabling SSL for db2 luw.

**Comment by serge-rider** [comment]
You can set driver property sslConnection to true.
Also you will need to configure client according to https://www.ibm.com/developerworks/data/library/techarticle/dm-0806sogalad/index.html
If you have some particular problems with SSL config - please ask.

**Comment by SriniRaviKrishna** [comment]
I already tried it based on IBM's documentation. Needless to say, it doesn't work.  In contract it took me an hour to set up SSL based client connection for Postgres.

**Comment by serge-rider** [comment]
I'll try to setup SSL support in my DB2 Express and test this..

**Comment by leewebb** [comment]
@SriniRaviKrishna Once the database is configured for SSL you need to tell DBeaver to use the SSL details. Edit Connection -> Connection settings -> Driver Properties and add the following key name/values:
Name: sslConnection Value: true
Name: sslTrustStoreLocation Value: <location of the Java Key Store>
Name: sslTrustStorePassword Value: <Java Key Store password>

**Comment by SriniRaviKrishna** [comment]
This was one of the first things I did and it did not work.

**Comment by dlsxd** [comment]
Hello, I have the same issue, any progress on this bug?

**Comment by krawchukd** [comment]
Works for me by setting the url template to the following:

`JDBC:db2://{host}{:port}}/{database}:sslConnection=true;sslTrustStoreLocation=/location/to/your/cacerts;sslTrustStorePassword=changeit;`

**Comment by SriniRaviKrishna** [comment]
Thanks.  Let me try.

------------ Original Message ------------

**Comment by markcbooth** [comment]
Still doesn't work...with new European GDPR rules--need the SSL encryption--forces use of Squirrel even though I prefer DBeaver.

**Comment by dlsxd** [comment]
Thanks guys, last comment helped! SSL begin to work if put ssl properties into database name field.

**Comment by nairrashmi90** [comment]
When you say "/location/to/your/cacerts", which server are you referring to? DB2 DB is my server and application server is my client.

**Comment by markcbooth** [comment]
This sslTrustStoreLocation would be the cacerts on your local machine

**Comment by dcrouch1** [comment]
Thank you people. Made my night.

**Comment by herleraja** [comment]
![image](https://user-images.githubusercontent.com/18572477/75326953-db331080-587b-11ea-9be9-822b789989a2.png)

**Comment by kseniiaguzeeva** [comment]
Is this ticket still actual for you?

**Comment by sravikrishna3** [comment]
Sorry I no longer work with DB2, so no idea.  thanks for the effort.

**Comment by sravikrishna3** [comment]
I was the one who created this issue nearly 3 years ago.
