### ISSUE TITLE
Creating a database with psql causes an error

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#19557]
### Description

![image](https://user-images.githubusercontent.com/12581569/229053213-1bb1ed0e-4e58-4ccd-b7fe-5728f7caffab.png)
psql create database ! all ok
[Learn more in Telegram](url)

### DBeaver Version

CE 23.0.1

### Operating System

wsl2 ubuntu 22.0.4

### Database and driver

Postgres

### Steps to reproduce

1. Create a database using psql.
2. Then refresh the database list.

**Comment by ShadelessFox** [comment]
No steps to reproduce / can't reproduce
