### ISSUE TITLE
dBeaver not responding again.

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#19552]
### Description

when running a block of PL/pgSQL across multiple databases dBeaver once again uses > 95% of all cores and the UI freezes with the white  screen and the entirely too common: "(Not Responding)" text in the title bar.

this will typically happen if I visit more than a dozen clusters without restarting dBeaver.

if finally just crashed out.

thread dump included.

### DBeaver Version

Community Edition 23.0.1

### Operating System

Windows 10

### Steps to reproduce

connect to cluster/database
do something
connect to another cluster/database

repeat 12,20, or more times with unique clusters

watch dBeaver UI freeze and eventually crash the application.
[thread-dump_2023-03-30.txt](https://github.com/dbeaver/dbeaver/files/11114428/thread-dump_2023-03-30.txt)

**Comment by E1izabeth** [comment]
Probably will be fixed in #19553

**Comment by serge-rider** [comment]
@coleman-rik Please reopen if this will happen again.
