### ISSUE TITLE
change the "font and color theme"

### ISSUE THREAD

**Issue by SSSDNSY** [dbeaver/dbeaver#19556]
### Description

1. i try to change the "font and color theme"
2. the error information display in the under image

### DBeaver Version

23.0.0.202303040621

### Operating System

win10

### Database and driver

mysql8 

### Steps to reproduce

1. i try to change the "font and color theme"
2. the error information display in the under image

### Additional context

![image](https://user-images.githubusercontent.com/15624361/229002073-0437742f-e51b-4c38-be00-f7dd533c14f4.png)
![image](https://user-images.githubusercontent.com/15624361/229002275-426df7bd-b776-4d6b-8862-5deabcc3a7b7.png)

**Comment by E1izabeth** [comment]
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
