### ISSUE TITLE
Not responding on db connection

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#19553]
### Description

UI showing "Not Responding" and title bar white trying to connect to a db.

[thread-dump_2023-03-30a.txt](https://github.com/dbeaver/dbeaver/files/11114554/thread-dump_2023-03-30a.txt)

### DBeaver Version

Community Edition 23.0.1

### Operating System

Windows 10

### Database and driver

PostgreSQL versions 11-15.

### Steps to reproduce

1. start dBeaver
2. navigate to an open query tab
3. enter sql statement, realize that you are in the wrong tab
4. switch to another SQL query tab with the database you meant to be at
5. switch that query tab to a different database cluster
6. watch as CPU goes to nearly 100%, UI freezes, see (Not Responding) in the title block.

**Comment by arhayka** [comment]
Thank you for your report.

**Comment by serge-rider** [comment]
It looks that problem is caused by unsychronized PostgreSQL database data type cache.

Fixed
