### ISSUE TITLE
Dbeaver 23.0.1 Algorithm negotiation fail

### ISSUE THREAD

**Issue by JaldeaR** [dbeaver/dbeaver#19568]
### Description

failed to setup tunnel with ssh due to algorithm negotiation fail.
```
Algorithm negotiation fail: algorithmName="server_host_key" jsch Proposal="rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521" serverProposal="ssh-rsa,ssh-dss"
```

### DBeaver Version

23.0.1

### Operating System

Pop!_OS 22.04 LTS

### Steps to reproduce

After updating to 23.0.1 this problem persists on connecting to database (via VPN tunnel), reverting back to 22.3.5 problem doesn't exist, have not tested on 23.0.0.

**Comment by Destrolaric** [comment]
@JaldeaR Hi, it looks like your server uses an old deprecated ssh-rsa, we recently updated our JSCH version and this led to this algorithm being disabled. If possible, I would recommend enabling `rsa-sha2-512` or `rsa-sha2-256`. We may consider reenabling the old algorithm in the future, but it will be better to use secure ones.

**Comment by serge-rider** [comment]
We probably need an additional UI option like "Enable legacy algorithms".

**Comment by danielvolpato** [comment]
> @JaldeaR Hi, it looks like your server uses an old deprecated ssh-rsa, we recently updated our JSCH version and this led to this algorithm being disabled. If possible, I would recommend enabling `rsa-sha2-512` or `rsa-sha2-256`. We may consider reenabling the old algorithm in the future, but it will be better to use secure ones.

I have the exact same issue. Unfortunately I cannot make changes to this server and it is no longer maintained so I'll have to stick to previous dbeaver versions.

**Comment by Destrolaric** [comment]
We are going to reenable old algorithm in the next version

**Comment by mcabreb** [comment]
I have upgraded to 23.0.2.202304091457 and it works, thanks.

**Comment by JaldeaR** [comment]
> I have upgraded to 23.0.2.202304091457 and it works, thanks.

Yes, for me as well.

**Comment by bersipy** [comment]
I have DBeaver v. 23.2.5.202311191730, and I cannot connect with server-proposal "ssh-dss".
I've found a fix by changing the SSH library from JSch to SSHJ. Hope it is ok.

(in the connection settings --> SSH tab --> advance settings --> Change "Implementation" from JSch to SSHJ)
