### ISSUE TITLE
Tablespace support for PostgreSQL

### ISSUE THREAD

**Issue by gencer** [dbeaver/dbeaver#1956]
I see this feature requested but for `Oracle`. Couldn't find anything for **PostgreSQL**. So I request this.

I can see tablespace's but cannot edit/delete. I would like to do this job from DBeaver. Can we implement this anytime soon?

**Comment by serge-rider** [comment]
Yes, sure.

**Comment by serge-rider** [comment]
Tablespace and "with OIDs" edit will be added in 5.0.4.
