### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by ygoe** [dbeaver/dbeaver#19567]
### Description

I've just installed DBeaver, latest version, on a fresh Windows 11 computer. That went fine, but I cannot connect to my local PostgreSQL server. The error message says something about expired SSL certificates for the required driver download. I cannot copy the messages and it's on another computer. But it's very easy to try out: Install in a fresh environment and set up a Postgres connection.

One of the several error messages suggests to enable using the Windows trust store, which is already the default, so there's nothing to fix here.

I'm stuck now and cannot set up the environment I need. I'll have to try use the pgAdmin tool that I hate.

### DBeaver Version

DBeaver Community 23.0.1

### Operating System

Windows 11

### Database and driver

PostgreSQL 15.2

### Steps to reproduce

Install and setup Postgres connection

### Additional context

Internet works fine for all software downloads.

**Comment by E1izabeth** [comment]
Have you tried to disable usage of Windows trust store in Preferences and restart DBeaver?

**Comment by ygoe** [comment]
Sorry for the delay. I tried again on Monday but it immediately worked. Somebody must have fixed the broken certificate on their server.

**Comment by E1izabeth** [comment]
Thank you for update.
