### ISSUE TITLE
Connection to Private DB server 10.75.32.182:5432 refused

### ISSUE THREAD

**Issue by sneha-bm** [dbeaver/dbeaver#19561]
### Description

I am unable to connect to private DB 10.75.32.182:5432 

### DBeaver Version

Community 22.1

### Operating System

Windows

**Comment by E1izabeth** [comment]
How can we help you?

**Comment by E1izabeth** [comment]
Please provide more information of what are you trying to do and what is going wrong. Do you see any error?

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
