### ISSUE TITLE
[FireBird] domain procedure names do not have default values in the procedure definition

### ISSUE THREAD

**Issue by SolfacodeSoftware** [dbeaver/dbeaver#19564]
After update to DBeaver 23.0.1.202303250535 the problem still exists.
For simplify solution I've attached prepared EMPLOYEE.FDB ver 2.5
Procedure name DBS$SYSTEMLOG_ADD

Purpose:

CREATE OR ALTER PROCEDURE DBS$SYSTEMLOG_ADD (DBS$NAME VARCHAR(64), DBS$LOG DBS$MEMO, DBS$DELETE DBS$BOOLEAN = 0)
...

Effect in DBeaver:
CREATE OR ALTER PROCEDURE DBS$SYSTEMLOG_ADD (DBS$NAME VARCHAR(64), DBS$LOG DBS$MEMO, DBS$DELETE DBS$BOOLEAN)

Feel free to ask if you need more informations.
[EMPLOYEE.ZIP](https://github.com/dbeaver/dbeaver/files/11076707/EMPLOYEE.ZIP)

_Originally posted by @SolfacodeSoftware in https://github.com/dbeaver/dbeaver/issues/19366#issuecomment-1484766641_

**Comment by LonwoLonwo** [comment]
Ok, thanks for the report. I suggest adding a default value to the type statement as a possible workaround.
