### ISSUE TITLE
sql editor fonts size can't change

### ISSUE THREAD

**Issue by JonSnower** [dbeaver/dbeaver#19576]
### Description

sql editor fonts size can't change use ctrl + +

### DBeaver Version

23.0.1.202303250535

### Operating System

windows 10

### Database and driver

mysql

**Comment by E1izabeth** [comment]
Thank you for bug report. Close as duplicate of #19521

**Comment by JonSnower** [comment]
您好，邮件已收到，我会尽快给您回复。
