### ISSUE TITLE
DuckDB "Number" datatype should be replaced with "Numeric", in the datatype selection pick list

### ISSUE THREAD

**Issue by DeflateAwning** [dbeaver/dbeaver#19573]
### Description

DuckDB "Number" datatype should be replaced with "Numeric", in the datatype selection pick list

### DBeaver Version

23.0.1 Free

### Operating System

Windows 10

### Database and driver

jdbc:duckdb 
latest default install

### Steps to reproduce

1. Add a new "NUMBER" column in the Properties > Columns editor
2. See error

Query it runs: `ALTER TABLE memory.main.test1 ADD Column4 NUMBER;`

Error:
![image](https://user-images.githubusercontent.com/11021263/229264503-f17b2897-43d3-4ca2-8ddd-99c36d7fd874.png)

**Comment by LonwoLonwo** [comment]
Hello @DeflateAwning 

Thanks for the report.

As I can see, DuckDB driver doesn't support data type info for some reason.

```java
public ResultSet getTypeInfo() throws SQLException {
        throw new SQLFeatureNotSupportedException("getTypeInfo");
}
```

As a workaround I can recommend you write the data type name manually.

![2023-04-03 10_43_39-DBeaver 22 3 1 - NewTable](https://user-images.githubusercontent.com/45152336/229444277-75c32e47-da03-468b-9552-09e17037ef9b.png)

**Comment by DeflateAwning** [comment]
I understand that's a good workaround, but I'd prefer if we could hard-code the datatypes in the driver or similar. Is that an option?

**Comment by LonwoLonwo** [comment]
You can probably vote somehow here https://github.com/duckdb/duckdb/issues/6759

**Comment by LonwoLonwo** [comment]
Fixed for the last (at least) DuckDB driver version (0.9)

![2023-09-28 09_16_46-DBeaver Ultimate 23 2 1 - NewTable_1](https://github.com/dbeaver/dbeaver/assets/45152336/a11d9c44-147e-4714-b80a-42188c2a6e34)
