### ISSUE TITLE
Schemas option not available

### ISSUE THREAD

**Issue by mjossany** [dbeaver/dbeaver#19580]
### Description

Hi,

On my work computer I have the option to create a schema inside a database, however when I try to do this on dbeaver installed on my personal computer the option to create a new schema isn't available. Even the folder "Schemas" doesn't appear.

### DBeaver Version

Community Edition 23.0.1

### Operating System

Windows 11

### Database and driver

Database: mysql

**Comment by LonwoLonwo** [comment]
Hello @mjossany 

Please check your connection settings. Choose custom or Advanced for you connection "without schemas".

![2023-04-03 10_15_00-DBeaver 22 3 1 - _none_ compare-change sql](https://user-images.githubusercontent.com/45152336/229439676-314c3069-9280-4b34-ab4a-a68e5049bdb9.png)

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
