### ISSUE TITLE
Rename Chinese localization files

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#19589]
I suggest that DBeaver rename the following two `bundle_xxx.properties` into:

* `bundle_zh.properties` -> `bundle_zh_CN.properties`
* `bundle_tw.properties` -> `bundle_zh_TW.properites` (at least modify these files)

Otherwise, the Resource Bundle of IntelliJ will identify `bundle_tw.properties` as `特威文` instead of `中文/台灣`.

![image](https://user-images.githubusercontent.com/71438617/229443273-ab3c104a-6f94-4e31-b933-d39682d0d938.png)

_Originally posted by @hwhsu1231 in https://github.com/dbeaver/dbeaver/issues/19574#issuecomment-1493834426_

**Comment by SiyaoIsHiding** [comment]
I can work on this issue. May you please assign it to me? @E1izabeth

**Comment by E1izabeth** [comment]
Yes, you can work on it.

**Comment by E1izabeth** [comment]
@SiyaoIsHiding how is it going? Are you still working on it?

**Comment by hwhsu1231** [comment]
I hope this issue can be solved as soon as possible since I want to keep going to contribute the zh_TW localization.

**Comment by SiyaoIsHiding** [comment]
Yes @E1izabeth . Sorry, I worked on another issue #19743 first. I will work on this one soon.

**Comment by SiyaoIsHiding** [comment]
I am sorry that it turns out this issue does not fulfill the requirement of our coursework project. Therefore, we will not work on this issue anymore. Sorry for the inconvenience.

**Comment by E1izabeth** [comment]
We're aware that people who use locale other than `zh_CN` and `zh_TW` couldn't use localization anymore as, for example, `zh_SG` won't match to `zh` which is `zh_CN` now anymore. I don't see a good solution here, but if you can suggest something in this case, we're ready for discussion.
