### ISSUE TITLE
Describe ERD accessibility features on wiki

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#19582]
We need to describe how to work in ERD with the keyboard on wiki, on the [Sortcuts](https://github.com/dbeaver/dbeaver/wiki/Shortcuts) or in [ERD](https://github.com/dbeaver/dbeaver/wiki/ER-Diagrams).

Related to https://github.com/dbeaver/pro/issues/1311

**Comment by Destrolaric** [comment]
See **Bindings** in https://github.com/dbeaver/dbeaver/wiki/ER-Diagrams

**Comment by MashaKorax** [comment]
should remove the description of the ability to open the palette

**Comment by Destrolaric** [comment]
@MashaKorax Looks like it was unfortunately a minor bug, made the pr
