### ISSUE TITLE
[PostGIS] Support of curves geometries (SQL/MM Part 3) in map viewer

### ISSUE THREAD

**Issue by rbovard** [dbeaver/dbeaver#19608]
**Is your feature request related to a problem? Please describe.**

I really like the possibility to have an overview of PostGIS data in the map viewer, this is an amazing feature that I couldn't live without. However, curves geometries are currently not supported.

**Describe the solution you'd like**

Support of curves geometries (SQL/MM Part 3) in map viewer.

**Additional context**

- [SQL/MM Part 3](https://postgis.net/docs/using_postgis_dbmanagement.html#SQL_MM_Part3)

**Comment by ShadelessFox** [comment]
Hello @rbovard,

Thanks for the feature request.

We need to investigate possible solutions as the library we're using for rendering doesn't support curves out of the box.

**Comment by rbovard** [comment]
Thanks a lot for the dev @ShadelessFox, but it seems to not work here (tested with version 23.1.3)

In some case, I have only a line on the map (but not at the right place):

![image](https://github.com/dbeaver/dbeaver/assets/4549666/75632746-4087-4007-b9f8-f80d94ecc7fd)
`SRID=2056;LINESTRING (2554021.510361592 1146045.9171061674, 2554011.061413642 1146056.4932663445)`

Or no geom at all with Z value:

![image](https://github.com/dbeaver/dbeaver/assets/4549666/7be05e3c-dc6a-4e3f-bfcc-fa74be223ac4)
`SRID=2056;LINESTRING (2553886.8849250823 1145802.2807940794 375.55, 2553881.9850559025 1145812.2269134985 375.38)`

**Comment by ShadelessFox** [comment]
Hello @rbovard,

The provided geometries work fine for me. Maybe the viewer has different SRID?

![image](https://github.com/dbeaver/dbeaver/assets/35821147/8494e247-28d2-40db-a640-0f810e15ae8f)

**Comment by rbovard** [comment]
No it's correct, I've checked that:
![image](https://github.com/dbeaver/dbeaver/assets/4549666/779cadbb-869a-4b58-87e8-293fcbeb2e96)

But it I run the same query as you, it's working:
`SELECT st_geomfromewkt('SRID=2056;LINESTRING (2554021.510361592 1146045.9171061674, 2554011.061413642 1146056.4932663445)')`
![image](https://github.com/dbeaver/dbeaver/assets/4549666/03ff16fd-3db7-48ed-b496-48935ed53820)

So the issue is on the "stored" data?

**Comment by ShadelessFox** [comment]
Also works for me. It might depend on the database's data type (I'm testing against PostgreSQL 11.6).

I'm also unsure why we are discussing this issue here, as it's seemingly unrelated to curved geometries.

Can you please create a separate issue, specify the database and attach [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files#log-files)?

**Comment by rbovard** [comment]
Oops, I'm sorry. I was sure my table was with based with curved geometries.

I'll do that.

**Comment by rbovard** [comment]
Mmm, after another check my column is in fact definded as `geometry(compoundcurvez, 2056)` but the geometry inside is stored as linestring.

Should I open another issue or it's better to continue here?

**Comment by ShadelessFox** [comment]
I found the problem.

1. We linearize geometries even for display purposes on the grid, not only in the viewer.
2. Explicit `SRID=2056;` prefix is not stripped for some reason when passed to the viewer.

Please create a separate issue.

**Comment by rbovard** [comment]
Thanks for the research, I'v created 2 separate new issues.
