### ISSUE TITLE
Query Status not showing on next query execution after an error

### ISSUE THREAD

**Issue by StevenShewell** [dbeaver/dbeaver#19613]
### Description

After receiving a sql error - either for Syntax or System error - When the next query is run, The fact that the query is running, as well as the run time bar are not being displayed. 

The only way to tell the query is actually running is by the blue triangles in the query pane. 

### DBeaver Version

Version 22.3.5.202302171528

### Operating System

Windows 10

### Database and driver

Any 

SqlServer
Oracle
Netezza

### Steps to reproduce

Create a query that runs successfully - 
While the query runs  the  query running and time will display correctly 

Change the query to have a syntax error and execute. 

The error will be shown. 

Correct the syntax and rerun the query. 

The query running and run time status will not display, and the only way to tell that the query is running is by the blue 
triangles in the query pain.

**Comment by E1izabeth** [comment]
Probably, connected to #19529

**Comment by Matvey16** [comment]
@StevenShewell  I can't reprosuce it on postgres. Can you specify what happens for you? Does it happen diferrently from my screenshot?
![image](https://user-images.githubusercontent.com/82543000/231745169-7b4d7e4f-dd6a-4791-9c21-656269644974.png)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.
