### ISSUE TITLE
sqlserver procdure suggesstion failed params style

### ISSUE THREAD

**Issue by HomeAndFaraway** [dbeaver/dbeaver#19610]
### Description

when i use exec，the dbeaver suggest "exec proc_test(:@staffChannelId, :@agencyChannelId, :@medicalChanneId) "。but，this is not a right sql style。
dbeaver version：23.0.1
![image](https://user-images.githubusercontent.com/129605939/230065529-b623533a-aa15-4431-8ea9-690ac3fee49c.png)

### DBeaver Version

Community Edition 23.0.1

**Comment by E1izabeth** [comment]
Thank you for report. Could you be more precise about what is wrong and what is expected?

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
