### ISSUE TITLE
DBeaver enterprise schema compare could not find column difference in table

### ISSUE THREAD

**Issue by Saurabhkumar33** [dbeaver/dbeaver#19618]
### Description

We tried to compare two schemas in Greenplum databases but DBeaver did not find the column difference present in one schema but absent in another. 

### DBeaver Version

Enterprise Edition Version 23.0.0.202303131136

### Operating System

Windows 10

### Database and driver

Database versions: Greenplum 4.3 & Greenplum 6.4

### Steps to reproduce

I tried to connecting both databases.
I selected schema on GP 6.4 and right click on schema compare and selected the schema on target schema.

**Comment by LonwoLonwo** [comment]
Hello @Saurabhkumar33 
Could you please provide DDLs of these tables?

**Comment by LonwoLonwo** [comment]
Also, could you let me know if you changed these settings?

![2023-04-06 11_22_23-DBeaver Ultimate 23 0 2 - Album](https://user-images.githubusercontent.com/45152336/230318781-2c2b9a2b-1543-408e-b9f5-2924a13b8fd1.png)

**Comment by Saurabhkumar33** [comment]
Hello @LonwoLonwo ,

The three ccheckboxes were unticked before Schema compare.
[DDL_report_masterfilelist.txt](https://github.com/dbeaver/dbeaver/files/11178385/DDL_report_masterfilelist.txt)

There is only one table in the schema and yet it is taking more than 45 minutes to generate the report.
Just wondering, if it is trying to do DDL compare or DML compare too?
Also are there any settings to make this operation faster.

**Comment by LonwoLonwo** [comment]
unticked? Are you sure? Because schema compare will not work with unticked checkboxes - nothing to create, nothing to drop and nothing to alter - it is null in the end.

DML comparison is not supported. You can use Data Compare for it: https://github.com/dbeaver/dbeaver/wiki/Data-compare

**Comment by Saurabhkumar33** [comment]
@LonwoLonwo , I think if the checkboxes are ticked, then it will create,alter/drop missing objects in target schema. So I have kept the checkboxes unticked. Since this is prod database, we cant make any changes from this tool.

**Comment by LonwoLonwo** [comment]
Oh, no. No changes during the comparison! It just compares two metadata structures.

You can use the result script to apply changes in the target schema, but only with the help of the "Migrate" button:

![2023-04-07 14_48_41-Schema compare · dbeaver_dbeaver Wiki — Mozilla Firefox](https://user-images.githubusercontent.com/45152336/230604184-b4f744cf-1430-420a-bd60-0e96256918e1.png)

So, please, tickle the checkboxes back and recheck the comparison.

**Comment by Saurabhkumar33** [comment]
Thanks for helping. @LonwoLonwo can you suggest any trick or method to fasten this comparision. It is just one tables (75GB) but takes around 45 minutes to generate the report.

**Comment by ShadelessFox** [comment]
This issue is being tracked on our internal board.
