### ISSUE TITLE
Theme is not switched automatically when OS switches between light/dark

### ISSUE THREAD

**Issue by idryzhov** [dbeaver/dbeaver#19615]
### Description

DBeaver automatically uses the OS theme when the app is first launched.
However, if the app is already running and the OS switches the theme, the app keeps the old theme and doesn't switch automatically.
It is necessary to restart the app to reflect the current OS setting.

### DBeaver Version

Community Edition 23.0.1

### Operating System

macOS Ventura 13.3

### Steps to reproduce

1. Open the application.
2. Switch the OS theme in System Settings.
3. The app theme is not switched.

**Comment by E1izabeth** [comment]
Thank you for report.
Well, it's recommended to restart DBeaver even after manually switching theme.

**Comment by idryzhov** [comment]
I use macOS's "Auto" appearance mode which switches the theme automatically – light during the day, dark at night. I have to restart DBeaver two times a day to change the theme according to this schedule.

Unfortunately, I'm not a macOS developer to figure this out myself and open a PR, but literally every other app on my laptop automatically changes its theme together with the OS, so I suppose there should be some simple API that allows to do that. It would be great if DBeaver could also adjust the theme automatically.

**Comment by E1izabeth** [comment]
DBeaver was built on Eclipse platform, which brings some limitations unfortunately.
But we will look what can be done

**Comment by ShadelessFox** [comment]
The theme can't be changed without restarting the application, so we can't change the theme automatically depending on the OS's theme.

**Comment by darren2046** [comment]
How is it now?
