### ISSUE TITLE
"Tip of the day" pop-out cause shuts down everything 

### ISSUE THREAD

**Issue by Yann-C-INN** [dbeaver/dbeaver#19620]
### Description

Hello,
I installed DBeaver from the windows installer:
https://dbeaver.io/files/dbeaver-ce-latest-x86_64-setup.exe

I installed using all the default settings.

I opened the app immidiatly a pop out "tip of the day" opens up and it is impossible to use the app. When hovering over this window the cursor turns to "loading". Nothing works, not even clicking X to shut down, so i have to use Task manager.
I obviously tried to reinstall before issuing this bug. /=

<img width="279" alt="image" src="https://user-images.githubusercontent.com/130037694/230304438-fcc0d9ce-8d8a-4fc7-bd1d-98abb573adec.png">

### DBeaver Version

23.0.1

### Operating System

Windows 11 (or maybe 10?)

**Comment by ShadelessFox** [comment]
Hello @Yann-C-INN,

Can you please send the log files and a thread dump? You can find the respective instructions here:
- https://dbeaver.com/docs/wiki/Log-files/
- https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump

Thank you.

**Comment by Yann-C-INN** [comment]
> Hello @Yann-C-INN,
> 
> Can you please send the log files and a thread dump? You can find the respective instructions here:
> 
> * https://dbeaver.com/docs/wiki/Log-files/
> * https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump
> 
> Thank you.

Thank you for the fast reply. I actually installed the previous version (23.0.0), and I also checked the "clean previous UI" when installed the app. It does work well this time and I am fine with working with the 23.0.0 version.

Anyhow, I did attach the two files you asked, but the app works just well so no issues are supposed to be found. [
[dbeaver error log.log](https://github.com/dbeaver/dbeaver/files/11167605/dbeaver.error.log.log)
[thread-dump.txt](https://github.com/dbeaver/dbeaver/files/11167606/thread-dump.txt)
](url)

**Comment by ShadelessFox** [comment]
This is weird, and we need to figure out what went wrong.

Were these taken while 23.0.1 was installed? The thread dump is empty.

**Comment by Yann-C-INN** [comment]
> This is weird, and we need to figure out what went wrong.
> 
> Were these taken while 23.0.1 was installed? The thread dump is empty.

I uninstalled the 23.0.1 multiple times and reinstalled it, always had this issue. This time, as I was writing this issue, I uninstalled 23.0.1 one last time and just went on to install the previous version, who works fine..

**Comment by ShadelessFox** [comment]
I understand it works for you, but it will only work in the short term. New versions will be released with many new features you might lack.

Could you please install 23.0.1 one more time and provide just the thread dump?

There are a more straightforward set of instructions:
1. Open the command prompt and type the following command:

```bash
tasklist /FI "IMAGENAME eq dbeaver"
```

You will see the following output if DBeaver is running:

```
Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
dbeaver.exe                  23700 Console                    1    293,624 K
```

The PID (23700) will be different for each launch, so you need to run it yourself to see the one that is actual for you.

2. Then type the following command (with PID replaced by the actual PID from the output of the previous command):

```bash
jstack PID > thread-dump.txt
```

You should see no output at all in the console. If there's something, then the PID is invalid.

3. Then type the following command to open the directory where the `thread-dump.txt` file was created:

```bash
start .
```

**Comment by Yann-C-INN** [comment]
> I understand it works for you, but it will only work in the short term. New versions will be released with many new features you might lack.
> 
> Could you please install 23.0.1 one more time and provide just the thread dump?
> 
> There are a more straightforward set of instructions:
> 
> 1. Open the command prompt and type the following command:
> 
> ```shell
> tasklist /FI "IMAGENAME eq dbeaver"
> ```
> 
> You will see the following output if DBeaver is running:
> 
> ```
> Image Name                     PID Session Name        Session#    Mem Usage
> ========================= ======== ================ =========== ============
> dbeaver.exe                  23700 Console                    1    293,624 K
> ```
> 
> The PID (23700) will be different for each launch, so you need to run it yourself to see the one that is actual for you.
> 
> 2. Then type the following command (with PID replaced by the actual PID from the output of the previous command):
> 
> ```shell
> jstack PID > thread-dump.txt
> ```
> 
> You should see no output at all in the console. If there's something, then the PID is invalid.
> 
> 3. Then type the following command to open the directory where the `thread-dump.txt` file was created:
> 
> ```shell
> start .
> ```

```
C:\Users\CoYa00>jstack 9144 > thread-dump.txt
'jstack' is not recognized as an internal or external command,
operable program or batch file.
```
_I got this msg._

I used the proper PID from the documentation page (https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump) as well as your guide.
```
C:\Users\CoYa00>tasklist /FI "IMAGENAME eq dbeaver"
INFO: No tasks are running which match the specified criteria.
```
DBeaver was (and is) active when I typed this.

BUT. I re installed the 23.0.1 and this time, like I did for the 23.0.0, I checked the box to reset previous UI settings and now I dont even get the tip window, and it works! I was also able to connect to my MS database at work, so i guess the problem had to do with residuals from previous installations.

**Comment by ShadelessFox** [comment]
So the issue somehow was fixed? That works, I guess. 

I assume it can be closed now. Thanks for your patience and assistance.
