### ISSUE TITLE
Just a question. how to see a suggestion of users in "Panels -  Value"?

### ISSUE THREAD

**Issue by StasSpawn** [dbeaver/dbeaver#19628]
I'm watching this video 
https://youtu.be/SvPZ0DN8y4o?t=744

And here when he click un NULL user - Value panel showed him created user. 
![2023-04-06_205231](https://user-images.githubusercontent.com/56681850/230457974-c1a86bb5-93ec-4261-b3b8-02f76ac04062.png)

I did the same code, press NULL user and my Value panel is empty. 

Is there a button to show suggestions?

**Comment by E1izabeth** [comment]
It works if you have a foreign key on this column to another table.
