### ISSUE TITLE
Debug under 202303

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#19625]
### Description

I'm trying to compile uder 202303 (is it possible due to: https://github.com/dbeaver/dbeaver/pull/19524 ?)
Do everything as described in: https://dbeaver.com/docs/wiki/Develop-in-Eclipse/

"mvn clean install" works fine but debug fails:

![image](https://user-images.githubusercontent.com/11477081/230407976-0b4693cd-a748-4248-a322-dccdc0d70512.png)

what I did wrong?

### DBeaver Version

current devel

### Operating System

win 10 x64

**Comment by LonwoLonwo** [comment]
You can add all dependencies manually:

![2023-04-06 17_39_52-Debug Configurations](https://user-images.githubusercontent.com/45152336/230413640-b39601f6-5b2a-4514-af0b-05b5d6d0d646.png)
