### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by ClodoaldoPinto** [dbeaver/dbeaver#19636]
Dbeaver 21.3.2.202112271055 (Portable version) on Windows Server 2016 Standard connecting to Teradata 17.05

I don't know how to fix this codification issue in the table view. I tried changing the connection charset.

![image](https://user-images.githubusercontent.com/1433209/230613574-a4f8fba1-f0e7-469e-aef5-ea24a29d0a6d.png)

**Comment by LonwoLonwo** [comment]
Hello @ClodoaldoPinto 

Could you please check the newest DBeaver version? You can download it here: https://dbeaver.io/download/

**Comment by ClodoaldoPinto** [comment]
> Hello @ClodoaldoPinto
> 
> Could you please check the newest DBeaver version? You can download it here: https://dbeaver.io/download/

Same problem with 23.0.1 which is the last in portable
![image](https://user-images.githubusercontent.com/1433209/231245002-e22ae7e4-134a-4267-a134-f5414e5e6e4a.png)

**Comment by ShadelessFox** [comment]
Hello @ClodoaldoPinto,

Can you please send a screenshot of this page?

![image](https://user-images.githubusercontent.com/35821147/233386155-6b842bbd-924c-4163-b59c-37a8a89bd51d.png)

**Comment by ClodoaldoPinto** [comment]
> Hello @ClodoaldoPinto,
> 
> Can you please send a screenshot of this page?
> 
![image](https://user-images.githubusercontent.com/1433209/233389500-c852d0d4-4912-40d9-a682-f74c48f68a35.png)

**Comment by ShadelessFox** [comment]
Does changing the problematic label help?

**Comment by ClodoaldoPinto** [comment]
> Hello @ClodoaldoPinto,
> 
> Can you please send a screenshot of this page?
> 
Thank you. That fixes it.
