### ISSUE TITLE
DBeaver doesn't read UTF-8 data base

### ISSUE THREAD

**Issue by G-Zidarov** [dbeaver/dbeaver#19631]
Hello, I have a problem with loaded data base (MariaDB) which includes Cyrillic letters. I have Macbook Pro 13' 2017 with MacOS Ventura and Dbeaver Version 22.3.4 
On the server (into the cPanel) everything is readable but when connect data base to the DBeaver the result is as it seen on the picture below (column: title).
<img width="651" alt="Screenshot 2023-04-06 at 18 00 20" src="https://user-images.githubusercontent.com/94197202/230419315-c221f6cf-d212-482e-ab95-74ee6521029a.png">
So far, I already tried to edit DB connection and inserted "characterEncoding [UTF-8]" and checked Preferences/General/Workspace but without results.
Would you advise me how to display correctly Cyrillic value from data base.
<img width="719" alt="Screenshot 2023-04-06 at 17 53 17" src="https://user-images.githubusercontent.com/94197202/230417351-09b7322e-5b00-4497-a498-c8e67ddf318b.png"> <img width="845" alt="Screenshot 2023-04-06 at 17 57 37" src="https://user-images.githubusercontent.com/94197202/230418796-2a8b5175-ba57-43cd-8adf-cd02880c19b4.png">

**Comment by LonwoLonwo** [comment]
Hello @G-Ziradov 

Could you please provide your table DDL?

And value from 

```
SELECT default_character_set_name FROM information_schema.SCHEMATA 
WHERE schema_name = <your_catalog_name>;
```

**Comment by G-Zidarov** [comment]
Hello @LonwoLonwo 
thanks for your response.
I've made some screenshots of DDL and SELECT statement.
DDL [screenshot: 1] is from table which is part of data base from row 4 [screenshot: 2].

[screenshot :1]
<img width="750" alt="Screenshot 2023-04-07 at 19 19 23" src="https://user-images.githubusercontent.com/94197202/230644172-59c2f07d-ec8c-4e2b-ad43-0855942e4576.png">
[screenshot:2]
<img width="1064" alt="Screenshot 2023-04-07 at 19 17 16" src="https://user-images.githubusercontent.com/94197202/230645128-a65c23cd-92d4-4595-8518-29c9857903ee.png">

**Comment by E1izabeth** [comment]
Does it still reproducible in the latest DBeaver version? We expect that it has been be solved with #21513

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by G-Zidarov** [comment]
The UTF-8 encoding problem is still ongoing. However, I still use DBeaver, in case of statements whit the Cyrillic text I use other software. I like DBeaver but that unreadable Cyrillic content is a problem.

**Comment by E1izabeth** [comment]
Thank you for update

**Comment by LonwoLonwo** [comment]
Hello @G-Zidarov 

Did you try to change your encoding to the KOI8-R? The field in the Preferences is not read-only. You can write your value there manually. Do not forget to restart DBeaver after that.

**Comment by G-Zidarov** [comment]
Hi, thanks for your advice. I try it but again without success. I've made screenshot of Preferences on the Table which contain Cyrillic symbols.
<img width="859" alt="Screenshot 2023-12-31 at 13 30 13" src="https://github.com/dbeaver/dbeaver/assets/94197202/6b7d92b1-30ef-4ead-af4d-b5e857584ec7">

**Comment by serjiokov** [comment]
@G-Zidarov Could ypu provide product version you use.

**Comment by G-Zidarov** [comment]
<img width="534" alt="Screenshot 2024-01-08 at 20 10 57" src="https://github.com/dbeaver/dbeaver/assets/94197202/aa7362d0-bb12-406c-8362-ea892eb003b5">

**Comment by serjiokov** [comment]
Hi @G-Zidarov, somereleases ago we added specific setting for localization "-Dfile.encoding=UTF-8" 
it located in dbeaver.ini file. Could you try to manage it for your issue?

**Comment by LonwoLonwo** [comment]
Also, if it will not help, could you please try to use another connector - MySQL in DBeaver for your database? Sometimes MySQL driver works better with encodings.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by MashaKorax** [comment]
Thanks for your report. I reproduced your issue. It happens on older versions of Maria and MySQL and does not happen on the latest.

**Comment by G-Zidarov** [comment]
Hello, everyone
related with the post of @MashaKorax I am posting a version of DB which my hosting provider gives me:

Server version: 10.6.17-MariaDB-log - MariaDB Server

**Comment by ceinmart** [comment]
Hi, 

Is there any setting of the encoding on the result set grid? 
I am getting a similar problem here with IBM Informix database. 
The database locale is en_us.UTF-8 and the connection locale are set correctly. 
The data loaded are in UTF-8 format, confirmed using multiple tools. 
The data is correctly visualized on putty terminal when selected on the database using Informix tools (dbaccess). 

However, into the dbeaver they came messing. 
I already checked every config, all are set to UTF-8 , already tried the dbeaver.ini parameter mentioned here https://github.com/dbeaver/dbeaver/issues/19631#issuecomment-1898230724

Version: 24.0.5.202405191503

This is how the data should look: 
![image](https://github.com/user-attachments/assets/843fcc17-e48c-404f-b88f-0209231cb5ef)

This is how dbeaver displays it. 
![image](https://github.com/user-attachments/assets/57f99c99-04aa-448b-bc81-72ef2a08e832)
