### ISSUE TITLE
Dbeaver adds single quotes when exporting dates

### ISSUE THREAD

**Issue by topout** [dbeaver/dbeaver#19639]
### Description

I export from datasets from Snowflake all the time. When I export dates, the CSV file never had single quotes around the date. Then suddenly, when I export to CSV, there are single quotes around the date. I check in Snowflake and there are no quotes. It is only after I export when I find the quote.

Here's an example query:
![image](https://user-images.githubusercontent.com/3910771/230631743-4c5c74c7-1f11-448c-b0b4-d8e9c190c929.png)

Here's what I see in Excel or any text editor. The single quotes are now there:
![image](https://user-images.githubusercontent.com/3910771/230632068-df9e5eb4-29be-4d36-ac7a-dbf9955a0c4d.png)

### DBeaver Version

Community Version 23.0.1.202303250535

### Operating System

Windows 11

### Database and driver

Snowflake

**Comment by LonwoLonwo** [comment]
Hello @topout 

I can reproduce only if I disable date/time formatting in Preferences:

![2023-03-24 11_13_04-Window](https://user-images.githubusercontent.com/45152336/230924250-b4f719ec-d2bd-48d9-bedc-60905dfa9ec5.png)

Or if I use the "database native" transfer setting:

![2023-04-10 17_43_15-Data Transfer](https://user-images.githubusercontent.com/45152336/230924407-c41feb6f-6ea4-4823-a781-a25e205253e6.png)

**Comment by LonwoLonwo** [comment]
![2023-04-10 17_42_09-DBeaver Ultimate 23 0 2 - _DBEAVER_ Script-215  Script-215](https://user-images.githubusercontent.com/45152336/230924569-5094036d-f216-412e-baa6-a36cc392d134.png)

**Comment by topout** [comment]
@LonwoLonwo Thank you! The value display format was the one for me.
