### ISSUE TITLE
PostgreSQL - _box (box[]) isn't formatted correctly.

### ISSUE THREAD

**Issue by Bas950** [dbeaver/dbeaver#19643]
### Description

In my previous issue #17467 it was fixed mostly, but I just noticed a small inconsistency it still displays `,` instead of `;` in the result
![image](https://user-images.githubusercontent.com/34792838/230720918-4d1b0432-cf1a-4a9d-a2c7-ae2089e04f3e.png)

### DBeaver Version

23.0.1.202303250535

### Operating System

macOS Ventura 13.3

### Database and driver

Database: PostgreSQL 13
Driver: PostgreSQL JDBC Driver 42.2.25

### Steps to reproduce

1. run `SELECT '{(3,4),(1,2);(7,8),(5,6)}'::box[]`

**Comment by E1izabeth** [comment]
Thank you for bug report.
