### ISSUE TITLE
BigQuery Session mode

### ISSUE THREAD

**Issue by 1pyxa1** [dbeaver/dbeaver#19648]
**Is your feature request related to a problem? Please describe.**
I don't know if it's possible and if so than how to activate [Session mode](https://cloud.google.com/bigquery/docs/sessions-intro) in BigQuery?

**Describe the solution you'd like**
I would like to be able to use a check-mark anywhere to activate session mode like it states [here](https://cloud.google.com/bigquery/docs/sessions-create#console)

**Additional context**
Session mode is really convincing for reusing temporary tables.

**Comment by arhayka** [comment]
Please clarify what exactly you want from this feature. In which case it could be useful?

**Comment by TobyHewing** [comment]
When doing query investigations in BQ I want to build many temp tables & reference them in further queries. I don't want to have to execute all queries at the same time replacing/building temp tables using 'script' mode but would rather create a session and have the table persist by enabling 'session' mode. This is all to avoid using the heinous bigquery UI and use DBeaver instead.

**Comment by 1pyxa1** [comment]
i apologize, missed the reply. thanks @TobyHewing , it's exactly my case.

**Comment by arhayka** [comment]
Thank you for the idea.
