### ISSUE TITLE
In "View Table", when I press the Option "Foreign Keys", generate "NullPointerException"

### ISSUE THREAD

**Issue by joeduanel** [dbeaver/dbeaver#19654]
### Description

I have a data base MySQL 8.0.28
In "View Table", when I press the Option "Foreign Keys", generate "NullPointerException"

![image](https://user-images.githubusercontent.com/130373641/230909330-140dfa1d-8066-44bb-9d86-78f5fb8ecee8.png)

![image](https://user-images.githubusercontent.com/130373641/230909418-05f92e41-9da5-42ec-84a3-faf8d032d38f.png)

### DBeaver Version

23.0.1

### Operating System

Windows 11 Pro

### Database and driver

I have a data base MySQL 8.0.28

**Comment by E1izabeth** [comment]
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual for the latest DBeaver version, please let me know and provide log files.
