### ISSUE TITLE
The popup has no slider

### ISSUE THREAD

**Issue by yangmeng66** [dbeaver/dbeaver#19664]
### Description

The popup has no slider
There are 20 entries in total, but there are no sliders, only 16 are displayed. You need to enlarge the window to display them completely

code: 
```
        parametersTable = new Table(composite, SWT.SINGLE | SWT.FULL_SELECTION | SWT.BORDER | SWT.H_SCROLL | SWT.V_SCROLL);
        final GridData gd = new GridData(GridData.FILL_BOTH);
```

![image](https://user-images.githubusercontent.com/51857567/231109557-15083aa9-dd27-4de3-b43d-6ee3d0b112dc.png)

### DBeaver Version

22.1.1 ce

### Operating System

WINDOS 10

**Comment by ShadelessFox** [comment]
Hello @yangmeng66,

Thanks for the bug report.

You can submit a PR that will fix this issue.
