### ISSUE TITLE
Add a new item in context menu: "Read data in SQL console"

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#19676]
I want to open the SQL console from the context menu:

![image](https://user-images.githubusercontent.com/69135623/231258011-3c464422-b4f7-48a8-b239-b2b3601a1df6.png)

And it must automatically generate the SELECT query:

![image](https://user-images.githubusercontent.com/69135623/231261857-45dbe8c2-43ba-4a5b-844f-d923a1edfef6.png)

**Comment by E1izabeth** [comment]
Thank you for the idea.

**Comment by sayyidhussain** [comment]
I would like to work on this issue as my first contribution.

**Comment by ghost** [comment]
Thk @sayyidhussain

**Comment by sayyidhussain** [comment]
Hi @E1izabeth, I have completed the functionality. can i create pull request.
![image](https://github.com/dbeaver/dbeaver/assets/85566851/81227a07-fd7d-465f-b935-90c5f7497216)

**Comment by E1izabeth** [comment]
@sayyidhussain sure

**Comment by ghost** [comment]
thk @sayyidhussain ♥

**Comment by arhayka** [comment]
Hi @sayyidhussain 
Thank you for your contribution.
We discussed the implementation of this feature and decided to solve this issue in a different way:

1. We want to leave only one option in the context menu and always open the SQL console by it.
2. In the context menu of the SQL console, add the "Savе as Script" option.
3. When saving (Ctrl+S) also save the console contents as a script.

**Comment by sayyidhussain** [comment]
Hi @arhayka 

will make the necessary changes. I'll post here if I had any questions.
