### ISSUE TITLE
subpartition can't display

### ISSUE THREAD

**Issue by cxshun** [dbeaver/dbeaver#19678]
### Description

when create a table with subpartition, partition view will produce an error.
![image](https://user-images.githubusercontent.com/1651036/231325084-04a4b799-8a7b-4812-9a59-f48176077f4b.png)

### DBeaver Version

Community Edition  23.0.2.202304091457

### Operating System

windows 10 22H2 19045.2728

### Database and driver

1. DB: MySQL 8.0.28
2. Driver: MySQL Connector/J [mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec)]

### Steps to reproduce

1. create a table with subpartition, you can use sql below.
```sql
CREATE TABLE `sub_partition_test_tbl` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `uid` bigint NOT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`uid`,`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
PARTITION BY RANGE (year(`create_time`))
SUBPARTITION BY HASH (`uid`)
SUBPARTITIONS 4
( PARTITION p0 VALUES LESS THAN (2021) ENGINE = InnoDB,
 PARTITION p1 VALUES LESS THAN (2022) ENGINE = InnoDB,
 PARTITION p2 VALUES LESS THAN (2023) ENGINE = InnoDB,
 PARTITION p3 VALUES LESS THAN (2024) ENGINE = InnoDB);
```
2. after creating table, double click table to open table view -> partitions
it will show nothing, click refresh on the right bottom, it will produce the exception that I provide above.

### Additional context

Only exception when subpartition, partition will be ok.

**Comment by LonwoLonwo** [comment]
Hello @cxshun 

Could you please provide your table DDL screen?

**Comment by cxshun** [comment]
Hello, @LonwoLonwo 
Thanks for you reply, here is the ddl screen.
![image](https://user-images.githubusercontent.com/1651036/231924661-bf05d8ae-c85b-4acb-a1f9-5126287cc1cb.png)

PS:It seems everything is ok. I tried to use [MySql Workbench](https://www.mysql.com/products/workbench/), and it works by showing the right partition.

> Hello @cxshun
> 
> Could you please provide your table DDL screen?

**Comment by LonwoLonwo** [comment]
Thanks for the report @cxshun
