### ISSUE TITLE
unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by Yukariiii** [dbeaver/dbeaver#19679]
### Description

版本：23.0.2
详情：
The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:ec85309f-1349-4b80-9ff5-1ffd5379db8d
  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    unable to find valid certification path to requested target
    unable to find valid certification path to requested target

### DBeaver Version

23.0.2

### Operating System

win10 21h2

### Database and driver

Microsoft SQL Server Management Studio						11.0.2100.60
Microsoft Analysis Services 客户端工具						11.0.2100.60
Microsoft 数据访问组件 (MDAC)						6.3.9600.17415
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.9600.20477
Microsoft .NET Framework						4.0.30319.42000
操作系统						6.3.9600

### Steps to reproduce

Double click to connect to the sql server and it reports an error

**Comment by E1izabeth** [comment]
Could you try switching the preference `Use Windows truststore` and restart DBeaver?
![image](https://user-images.githubusercontent.com/28875055/231355423-eef5d9f2-7c79-43e0-b1ac-03cb8a2837b4.png)

**Comment by Yukariiii** [comment]
its ticked
![image](https://user-images.githubusercontent.com/81160995/231363718-952ba283-5be9-48ab-9d08-f7fc2320c204.png)

**Comment by E1izabeth** [comment]
Yes, I 'm asking to untick it.

**Comment by E1izabeth** [comment]
And don't forget to restart DBeaver after that

**Comment by Yukariiii** [comment]
ticked or unticked doesnt work after restart DBeaver

**Comment by E1izabeth** [comment]
Aren't you in a corporate network or under the firewall?

**Comment by Yukariiii** [comment]
My colleague and I are on the same firewall and can link sql server normally,I differ from him in that he uses the version 22.2.3

**Comment by E1izabeth** [comment]
This often helps, maybe it'll help you too https://dbeaver.com/docs/wiki/Importing-CA-Certificates-into-DBeaver/

**Comment by Yukariiii** [comment]
I see the java version is 17 and the java version of Dbeaver22 is 11, does this have anything to do with it?

**Comment by Yukariiii** [comment]
This help didn't work for me

**Comment by LonwoLonwo** [comment]
Hello @Yukariiii 

Also, you can try to enable this setting in your connection settings:

![2023-04-12 14_02_06-Connect to a database](https://user-images.githubusercontent.com/45152336/231438741-ea573f8d-b690-4e81-9080-3f6adb2761dd.png)

Or in the driver properties:

![2023-04-12 14_02_28-Connect to a database](https://user-images.githubusercontent.com/45152336/231438787-8380235c-30ba-46ef-83d4-426e4d62ea56.png)

**Comment by tuliorsc10** [comment]
> 
@LonwoLonwo 
Isso Funcionou pra mim!!!

**Comment by E1izabeth** [comment]
It's been a while since no update here. I assume the issue is solved.
Please let me know if it's still actual and [proposed solution](https://github.com/dbeaver/dbeaver/issues/19679#issuecomment-1505079705) doesn't help.

**Comment by balantain** [comment]
Hello, I faced with the same issue on my Mac. And nothing of mentioned above could help me. But when I use my Windows 10 computer, everything works fine!

**Comment by E1izabeth** [comment]
@balantain are you under the firewall or in a corporate environment?

**Comment by cblevins28** [comment]
I am seeing this same issue on my Mac. It's using the latest OS, Sonoma.

**Comment by vigsank** [comment]
I connect to SAP HANA Cloud Database. It was working for me until December start. But after a month - I am also seeing same problem on my Mac. :(

The weird part is - I deleted the connection and created a brand new. Connection creation works but not working after that.

**Comment by pyxelr** [comment]
This issue occurs on my macOS when checking for DBeaver updates while connected to a specific VPN.

**Comment by astrowonk** [comment]
Mac users finding this thread,  I believe the Mac issue can't be resolved without [this issue on the keychain being fixed](https://github.com/dbeaver/dbeaver/issues/21557) - right now there's no easy way to add a certificate to the community Mac version without going into the app bundle and replacing the `cacerts` file within.
