### ISSUE TITLE
Time formatting doesnt work in MariaDB/MySQL

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#19671]
### Description

1. Change time formatting in Preferences->Editors->Data Editor->Data formats
2. Refresh a table with Time value
Expected: time formatted as set in settings
Actual: after refreshing time value stays in default format HH:mm:ss

https://user-images.githubusercontent.com/43252954/231173786-b946242e-5e35-4390-8504-b5f8fd29e7a7.mp4

### DBeaver Version

23.0.2

### Operating System

win10

### Database and driver

MariaDB - driver MariaDB Connector/J 3.0.7
MySQL 5.7.25-28, driver MySQL Connector Java mysql-connector-java-5.1.48

**Comment by Destrolaric** [comment]
https://github.com/dbeaver/dbeaver/issues/10401 Probably works as expected
