### ISSUE TITLE
Cannot see relationships on ER Diagram - Netezza Driver

### ISSUE THREAD

**Issue by livingstonc** [dbeaver/dbeaver#19688]
### Description

When using ER Diagram feature, all the tables view appear but none of the relationships show. We have a Netezza Appliance so have to use the Netezza Driver to connect and work correctly.

### DBeaver Version

Community Edition 23.0.1

### Operating System

Windows 10

### Database and driver

Netezza database driver

**Comment by LonwoLonwo** [comment]
Hello @livingstonc 

Could you please provide footage showing your issue?
What kind of relationships have your tables?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.
