### ISSUE TITLE
Error when query returns no data

### ISSUE THREAD

**Issue by point1234** [dbeaver/dbeaver#19685]
### Description

I'm using dBeaver Community, to connecto do a Informix Database.

I've recently upgraded to 23.0.2, and i've noticed that when a run a query that returns no data, dBeaver gives an error, instead of the normal behavior from 22.3.5, where is shown a empty results table.

### DBeaver Version

23.0.2

### Operating System

Windows10

### Database and driver

Informix 11.5/12/14
IBM JDBC Driver for Informix 4.50.4.1

### Steps to reproduce

1. Execute a query that returns no data

**Comment by ShadelessFox** [comment]
Hello @point1234,

Can you please provide footage showing the issue? Thank you.

**Comment by point1234** [comment]
Hi,

Meanwhile i've reinstalled DBEaver from scratch and is working fine now

**Comment by E1izabeth** [comment]
Then I'll close this issue. Let me know if you meet it again and provide some footage.

**Comment by steve-swipetospin** [comment]
This error started for me a day or two ago after a version upgrade. Uninstalling and reinstalling dbeaver-ce didn't help. But deleting the entire ~/.local/share/DBeaverData/ directory, then uninstalling and reinstalling dbeaver-ce did.
