### ISSUE TITLE
Download page incorrectly states JDK 11, not JDK 17 is required.

### ISSUE THREAD

**Issue by AlexKotsc** [dbeaver/dbeaver#19689]
### Description

Navigating to https://dbeaver.io/download/ under Install: and Java notes it's specified that Dbeaver requires JDK 11 to run; this has changed recently with a v23 release.

### DBeaver Version

DBeaver v23

### Operating System

Windows

**Comment by serge-rider** [comment]
Thank for noticing.
Fixed.

**Comment by uslss** [comment]
verified
