### ISSUE TITLE
Provide instructions for building an aarch64 binary

### ISSUE THREAD

**Issue by phantom943** [dbeaver/dbeaver#19691]
I am trying to build DBeaver CE from source. 
I run all the instructions as described above, and
`mvn package` successfully runs to the end.
However, on my machine (an M1 Mac) I still only get an x86_64 build in the `product/community/target/products` folder.
When I try to run that binary, regardless, it will not start with 
```
JVM shared library does not contain the JNI_CreateJavaVM symbol
```
error message.
I suspect I am not building the right binary.
I have OpenJDK from Brew:
```
/usr/libexec/java_home -V
 20 (arm64) "Homebrew" - "OpenJDK 20" /opt/homebrew/Cellar/openjdk/20/libexec/openjdk.jdk/Contents/Home
```
My VM is set in `info.plist` as 
```
<string>-vm</string><string>/opt/homebrew/Cellar/openjdk/20/libexec/openjdk.jdk/Contents/Home/bin</string>
```
Could you please help with providing some instructions on this?

**Comment by chirontt** [comment]
By default the `mvn package` command only builds DBeaver for the `x86_64` architecture. To build for the `aarch64` architecture (in addition to `x86_64`), use the `all-platforms` profile, i.e. `mvn package -Pall-platforms`.

**Comment by phantom943** [comment]
Thank you very much! It worked like a charm! Do you think it makes sense to include this info in the readme of the repo?

**Comment by chirontt** [comment]
I hope the DBeaver team would do something with your suggestion.

**Comment by flambchap** [comment]
Thank you for raising our attention. We'll add this info to our docs.

**Comment by chirontt** [comment]
@n5a5 There's a typo in the wiki article that your commit links to:

![image](https://user-images.githubusercontent.com/49886739/236703858-19429124-647a-4a4c-a7b8-06995a7b752c.png)

The directory should be: `product/community/target/products`

**Comment by flambchap** [comment]
Thanks @chirontt, fixed it
