### ISSUE TITLE
Unexpected displaying of array value returned from postgresql c language function

### ISSUE THREAD

**Issue by Dosenkaffee** [dbeaver/dbeaver#1970]
Hi,
when calling a c language function from postgresql which returns an array of a custom composite type, DBeaver (Version 4.1.1)  displays the result false (It is expected to be two array elements with values (1,2) and (3,4)):

`SELECT MY_CUSTOM_ARRAY_FUNCTION();`
![image](https://user-images.githubusercontent.com/9384381/28994902-20025f5a-79da-11e7-948e-d7a8a0c121d1.png)
When casting explicit to text, the array is displayed as expected:
`SELECT MY_CUSTOM_ARRAY_FUNCTION() ::TEXT;`
![image](https://user-images.githubusercontent.com/9384381/28994907-3f508c56-79da-11e7-8e30-f6ba22e31aa4.png)

Attached, you'll find a zip folder with the sql for creating the custom composite type along with the creation of the funciton and the calling. Also within the zip folder, is the c file which contains the called c language function for postgres
[Code.zip](https://github.com/serge-rider/dbeaver/files/1202306/Code.zip)

Edit:
when using unnest on the call, the output looks again as expected.
Look DBeaver tries to do this from the beginning?
`SELECT unnest(MY_CUSTOM_ARRAY_FUNCTION())`
![image](https://user-images.githubusercontent.com/9384381/28995046-74e3bf2e-79de-11e7-9122-65e1eadbe205.png)

**Comment by serge-rider** [comment]
It is a bug in PG arrays handling.
Thanks for report

**Comment by LonwoLonwo** [comment]
Hello @Dosenkaffee 
Is problem is still actual for you?
Many changes have been made to the project in recent years, including array reading. 
Do you have the opportunity to check out new versions of the DBeaver?
Thanks

**Comment by uslss** [comment]
there is no update on issue for a long time.
If issue is still actual for you - feel free to reopen it
