### ISSUE TITLE
Incorrect generated DDL for trigger (schema appears twice)

### ISSUE THREAD

**Issue by AronHK** [dbeaver/dbeaver#19714]
### Description

Right clicking trigger > Generate SQL > DDL, or checking the Declaration section in Properties results in a code where the schema name may appear twice:
![image](https://user-images.githubusercontent.com/9072794/232231122-1fa01b7f-2157-479a-b62f-c6be57104f12.png)

The cause seems to be that the DESCRIPTION column in USER_TRIGGERS already starts with the schema name, and I assume DBeaver automatically appends the schema name too without checking this.
![image](https://user-images.githubusercontent.com/9072794/232233201-f561e947-7abe-4af5-a22f-569969cf1779.png)

### DBeaver Version

Community Edition 23.0.2

### Operating System

Windows 11

### Database and driver

Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

### Steps to reproduce

1. Create a trigger where you specify the schema name:

`create or replace trigger myschema.mytrigger...`

2. Open it from the Database Navigator

**Comment by ShadelessFox** [comment]
Hello @AronHK,

Thanks for the bug report.

Can you please provide the full DDL of the trigger?

**Comment by AronHK** [comment]
I'd rather not show the full trigger from that project.

Here is an example code for a new trigger I just created:
```
create trigger checkout.newtrigger after insert or update on checkout_session
begin
	null;
end;
```

and this is what DBeaver gives me back in the trigger Properties > Declaration:
```
CREATE OR REPLACE trigger CHECKOUT.checkout.newtrigger after insert or update on checkout_session
begin
	null;
end;
```

**Comment by ShadelessFox** [comment]
Thank you. I was able to reproduce your issue.
