### ISSUE TITLE
Dbeaver 23.0.2 CE not able to find files on windows when specifying a trust store location for SSL connections

### ISSUE THREAD

**Issue by lherreranetlink** [dbeaver/dbeaver#19728]
### Description

When I updated to version 23.0.2 I was not able to specify the **sslTrustStoreLocation** anymore, if you notice on the below image, when I paste the location of my sslTrustStore file, I keep getting FileNotFoundException, I tried with normal slash and back slash, if you notice in the image, it always tries to find the file using backslashes in the path even though I clearly pasted the path with regular slashes (/).
This didn't happen in the previous version I started to face this after I updated the product.

<img width="700" alt="Screenshot 2023-04-17 100918" src="https://user-images.githubusercontent.com/30661966/232548684-6fa677ed-9273-44c1-b707-422aa4584f41.png">

### DBeaver Version

Community Edition 23.0.2

### Operating System

Windows 10

### Database and driver

1. Database: DB2 for Luw
2. Driver: Common IBM Data Server Driver for JDBC 11.5

### Steps to reproduce

1. Try to open a new connection to DB2 for Luw
2. Fill the connection details por any DB2 database, host, port, database, user and password
3. Go to driver properties
4. In driver properties add a new property called ssTrustStoreLocation
5. put any valid location for a file on a windows machine
6. specify the property sslConnection equals to true
7. Click on Test Connection and you will see that the file is never found by dbeaver, even though the file does exist. Also note that no matter if you use normal slashes or backslashes dbeaver tries to use backslashes for the specified path. This didn't happen in previous versions of dbeaver.

**Comment by ShadelessFox** [comment]
Hello @lherreranetlink,

Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still actual for you - feel free to reopen it.

**Comment by colt-ds** [comment]
I'm having this issue as well.
