### ISSUE TITLE
Databricks on Azure data transfer maps binary datatype incorrectly

### ISSUE THREAD

**Issue by RichardSCarchitect** [dbeaver/dbeaver#19723]
### Description

Exporting table data from SAP HANA to Azure Databricks using the Data Transfer wizard, with create new table and columns option.  The source table has a few columns of datatype VARBINARY(16) or NVARCHAR(13).  The import on Databricks fails because DBeaver changes the target datatype to BINARY(16) or STRING(13) which are not a valid datatatypes for Azure Databricks (Dbeaver insists to attach the length to the Databricks datatype even though it's illegal).  Crucially when I use the Configure menu in the wizard to override the target datatype to BINARY this has no effect.  In the Transform - DDL window I can see the target DDL with BINARY(16) datatypes, but I cannot edit (type over) the DDL in any way.  So the only way is to 'skip' the columns with VARBINARY datatype.
Wrong datatype mapping, ineffective manual change of datatype and inability to manually edit the DDL of the target object should all be fixed (maybe it's a driver issue?  Don't know)

### DBeaver Version

Community edition 23.0.2

### Operating System

Windows 10 professional

### Database and driver

Azure Databricks
native JBDC driver

### Steps to reproduce

Exporting table data from SAP HANA to Azure Databricks using the Data Transfer wizard, with create new table and columns option.  The source table has a few columns of datatype VARBINARY(16).  The import on Databricks fails because DBeaver changes the target datatype to BINARY(16) which is not a valid datatatype for Azure Databricks (BINARY is valid).  Crucially when I use the Configure menu in the wizard to override the target datatype to BINARY this has no effect.  In the Transform - DDL window I can see the target DDL with BINARY(16) datatypes, but I cannot edit (type over) the DDL in any way.  So the only way is to 'skip' the columns with VARBINARY datatype.

**Comment by ShadelessFox** [comment]
Hello @RichardSCarchitect,

Thanks for the report.
