### ISSUE TITLE
Geometry csv import into Redshift adds empty Z value

### ISSUE THREAD

**Issue by Neifen** [dbeaver/dbeaver#19729]
### Description

When importing a csv into redshift (with a geometry column) I encountered a couple of issues. (csv added)
[capitals_web_202210211431.csv](https://github.com/dbeaver/dbeaver/files/11254675/capitals_web_202210211431.csv)

- First in the import dialog I had to make sure the geometry column was chosen as geometry, otherwise it would try to load it as varchar. (Minor issue)

- After importing it I realized that somehow a Z value was added to the geometry with the value NaN. Now in the csv the geometries are saved as WKT with only 2 dimentions. 

I did try to insert it into redshift with an insert statement and had to use "st_geomFromText(..)" and that didn't create a Z value. So I'm not sure where the error is. Weather in DBeaver or in the redshift jdbc. I can't really tell.

Log:

!ENTRY org.jkiss.dbeaver.model 2 0 2023-04-17 13:30:28.601
!MESSAGE Cannot guess data type for column 'last_edited_date', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2023-04-17 13:30:28.603
!MESSAGE Cannot guess data type for column 'last_edited_user', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2023-04-17 13:30:28.603
!MESSAGE Cannot guess data type for column 'created_user', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2023-04-17 13:30:28.604
!MESSAGE Cannot guess data type for column 'created_date', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2023-04-17 13:30:30.728
!MESSAGE Cannot guess data type for column 'last_edited_date', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2023-04-17 13:30:30.729
!MESSAGE Cannot guess data type for column 'last_edited_user', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2023-04-17 13:30:30.730
!MESSAGE Cannot guess data type for column 'created_user', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2023-04-17 13:30:30.731
!MESSAGE Cannot guess data type for column 'created_date', defaulting to VARCHAR

### DBeaver Version

DBeaver Community edition 23.0.0

### Operating System

Windows 10 Enterprise

### Database and driver

1. Database Name and version: Redshift
2. Driver Redshift-jdbc42:RELEASE [2.1.0.3]

### Steps to reproduce

1. Connect to redshift db
2. Right click on db -> Import Data
4. import from csv
5. choose csv added in description
6. In Table mapping tab choose "configure". Make sure "shape target type is geometry
7. Next
8. Proceed
9. when done run this query:

`select st_asewkt(shape) from capitals_web;`

10. This will return 'Point Z(x y nan)'
(but should return 'Point(x y)'

**Comment by Matvey16** [comment]
@Neifen Hello. I don't see it as a bug. It looks like an expected behaviour of a redshift database. We use `'POINT (10 10)'::geometry` to insert geometry data as it is more universal and error prone way of inserting geometry data. It works correctly in postgresql, but in redshift the data is actually a little bit different from the one that would be produced by "st_geomFromText(..)" function which leads to a different result of "st_asewkt(..)" funtion.

If anything I would consider it a feature request, but I'm not sure if it is something that can be trivially fixed.

**Comment by ShadelessFox** [comment]
Hello @Neifen,

The returned type of the `st_asewkt` function is `varchar`. DBeaver does not transform textual data in any way, so this is a database issue.
