### ISSUE TITLE
Unable to connect athena using DBeaver

### ISSUE THREAD

**Issue by Dnirmania** [dbeaver/dbeaver#19739]
### Description

 I have created 4 connections to different athena environments (different AWS accounts) but I am able to connect only one connection at a time. for remaining connections, I get following error and If I disconnect from first connection and try to connect second connection, it works..
 
 You are not authorized to perform: athena:StartQueryExecution on the resource. After your AWS administrator or you have updated your permissions, please try again. (Service: AmazonAthena; Status Code: 400; Error Code: AccessDeniedException; Request ID: 50bef882-f512-4544-abc8-a36c6a25be0c; Proxy: null)

### DBeaver Version

23.0.2

### Operating System

Windows

### Steps to reproduce

Just try to connect other connection when one connection is already active.

**Comment by ShadelessFox** [comment]
Hello @Dnirmania,

Can you please see which query has failed to execute in the query manager?

Logs will also help in the investigation.

You can find more information here:
- https://github.com/dbeaver/dbeaver/wiki/Query-Manager
- https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by Dnirmania** [comment]
Hi @ShadelessFox 

Thank you for your response!

I have already checked log file of DBeaver. its filled with similar error messages and Using query manager doesn't make any sense because I am unable to connect Athena.. 

I would like to add one more thing here, I am not using any hardcoded credentials like Access and secret key to connect Athena..   We have configured SSO for athena with the help of Azure AD. I have also verified from AWS end that athena is using same AWS IAM role whether connection fails or succeed.  I am using following class..

AwsCredentialsProviderClass: com.simba.athena.iamsupport.plugin.BrowserAzureCredentialsProvider

**Comment by ShadelessFox** [comment]
I see. Perhaps checking these options will reveal something new?

![image](https://user-images.githubusercontent.com/35821147/233387998-f8a7c40f-65e0-4d2b-ae55-c5bda3422e2b.png)

**Comment by Dnirmania** [comment]
I just got few more records which are not useful..

**Comment by ShadelessFox** [comment]
Google and other forums say it has something to do with permissions.

Perhaps you have a limit of simultaneous sessions on your database user. Please try contacting AWS support.

As a possible workaround, try disabling the opening of separate connections for metadata read here:

![image](https://user-images.githubusercontent.com/35821147/233406480-2e3afe8d-ebf8-4b6c-b74e-d3c68d703e96.png)
