### ISSUE TITLE
Add Maven snapshot repository and be able to add snapshot driver version

### ISSUE THREAD

**Issue by Mause** [dbeaver/dbeaver#19756]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to direct users to try out pre-release versions of our (DuckDB) JDBC driver.

**Describe the solution you'd like**
Users should be able to add a maven repository, enable retrieving snapshots from said repo, then specify that they'd like a SNAPSHOT of a given maven specifier.

**Describe alternatives you've considered**
Directing them to manually download and load the jars.

**Comment by ShadelessFox** [comment]
Hello @Mause,

It's now possible to specify the classifier for a Maven artifact in DBeaver 23.0.2:

![image](https://user-images.githubusercontent.com/35821147/233372487-106513a5-f4f0-42ad-9959-e6e5eda8ef9f.png)

Additionally, Maven repositories can be configured in the preferences:

![image](https://user-images.githubusercontent.com/35821147/233372835-36a92afe-c4cf-4b9a-928f-691afd0fd814.png)

Please let me know if it helps.

**Comment by Mause** [comment]
Yes I've tried using that functionality, but that doesn't seem to allow people to download SNAPSHOT versions of our driver, eg, 0.8.0-SNAPSHOT.

We're currently publishing these to this repository: https://oss.sonatype.org/content/repositories/snapshots/org/duckdb/duckdb_jdbc/0.8.0-SNAPSHOT/

**Comment by arhayka** [comment]
Thank you for your report.

**Comment by E1izabeth** [comment]
Probably connected with #13048
