### ISSUE TITLE
(result-set) shortcut CTRL+1 stop working since release 23.0.1

### ISSUE THREAD

**Issue by LFerronato** [dbeaver/dbeaver#19754]
### Description

As documentation says: https://dbeaver.com/docs/wiki/Shortcuts/#result-set
CTRL+1 it's for "Foreign keys and tables referencing current table"

But since 23.0.1, this shortcut doesn't works well.

Please, dont change this shortcut, it's a really useful shortcut, very easy and practical. 
I hope it's just a bug.

For now, i downgrade to 23.0.0, just because this shortcut 😅

### DBeaver Version

23.0.1

### Operating System

Win11

### Database and driver

any

### Steps to reproduce

1. Run any query;
2. In result set, press CTRL+1
3. It should open a little window for References navigation.

**Comment by vitorgdev** [comment]
Yes! please fix it in the next realease

**Comment by douglasgoncalves** [comment]
Please address it in the upcoming release.

**Comment by SubOptimal** [comment]
Here are two workarounds for the recent version.

1. remove the keybinding for the two `Quick Fix` commands
2. press `SHIFT+CTRL+1` instead of `CTRL+1`

![image](https://user-images.githubusercontent.com/653288/233194310-9fed313e-85ac-4601-91e0-5a9475d70142.png)

**Comment by LFerronato** [comment]
@SubOptimal thanks! it works. 
I still think this change in version 23.0.1 was unplanned, wasn't it?

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by serge-rider** [comment]
Unfortunately CTRL+1 clashes with Quick Fix tool (which is used in SQL editor and it is a standard shortcut in may editors).
So we left only CTRL+SHIFT+1 as a default shortcut for references menu.
You can always redefine it on Keys preference page
