### ISSUE TITLE
dBeaver crash while refreshing 

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#19755]
### Description

after creating a couple of matierialized views and a couple of views I deleted a schema in dBeaver.  As it often fails to do, dBeaver doesn't reflect changes in the state of the database unless ytou "Refresh" multiple times, sometimes not even then and it take a invalidate/reconnect, a disconnect followed by a connect, or in extreme cases, exiting dBeaver and restarting the application.

After trying to refresh for the third time I get the dreaded "(Not Responding)" 90+% CPU use, a message concerning java heap space and several error popups that ask if I want to close the application.

Unfortunately, even those popups are white and unresponsive.  Eventually it just crashes.

thread dump attached
[thread-dump_2023-04-19a.txt](https://github.com/dbeaver/dbeaver/files/11277481/thread-dump_2023-04-19a.txt)

### DBeaver Version

Community Edition 23.0.2

### Operating System

Windows 10

### Database and driver

PostgreSQL 15, 14, 11

### Steps to reproduce

run scripts
delete schema
see that the deleted schema is still visible in the database tree
hit refresh
see that the deleted schema is still visible in the database tree
hit refresh
see that the deleted schema is still visible in the database tree
hit refresh

watch dBeaver go white with (Not Responding)
watch CPU climb to over 90%
watch several popups stating that there's an error and asking if I want to close dBeaver
try to say yes, but are unable to as the popups are also white and non-responsive
wait until dBeaver crashes.

**Comment by E1izabeth** [comment]
Probably, similar to #19752

**Comment by LonwoLonwo** [comment]
Hello @coleman-rik 

Please check the latest EA DBeaver version https://dbeaver.io/files/ea/
Does the issue reproducible there? Because we fixed some PG refreshing problems recently.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.
