### ISSUE TITLE
dBeaver locked up again

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#19752]
### Description

After running sql scripts across a number of postgresql clusters, dBeaver locked with the dreaded "(Not Responding)" consuming 100% of CPU before crashing a couple of minutes later.

thread dump attached

[thread-dump_2023-04-19.txt](https://github.com/dbeaver/dbeaver/files/11276854/thread-dump_2023-04-19.txt)

### DBeaver Version

Community Edition 23.0.2

### Operating System

Windows 10

### Database and driver

PostgreSQL 15, 14, 11

### Steps to reproduce

start dBeaver

1. connect to a cluster
2. run scripts
3. repeat steps 1 & 2
4. try to connect to just one cluster too many
5. watch as dBeaver hangs with 100% CPU use and crashes several minutes later.

**Comment by ShadelessFox** [comment]
Hello @coleman-rik,

Can you please try increasing maximum memory DBeaver can use?

Please see:
- https://github.com/dbeaver/dbeaver/wiki/Command-Line
- https://github.com/dbeaver/dbeaver/wiki/Command-Line#vm-arguments

**Comment by coleman-rik** [comment]
it was previously set to:
-Xms64m
-Xms1024m

I'm resetting it to 
-Xms256m
-Xms4096m

that seems rather excessive.
what are the actual memory requirements for this application?

thanks.

**Comment by ShadelessFox** [comment]
It might depend on your environment and workflow. The recommended is 1GB, but I allocate 4GBs just in case.

**Comment by coleman-rik** [comment]
my environment is typically:
30+ servers / clusters (all Linux)
postgresql versions 11, 14, 15
2-5 databases per cluster
20MB - 5TB databases
some schema with 50,000+ tables
some tables with > 200 columns
occasional Oracle use.

**Comment by E1izabeth** [comment]
Does it still reproducible on the latest DBeaver version?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
