### ISSUE TITLE
After upgrade Eclipse and DBeaver, all DB connections disappeared

### ISSUE THREAD

**Issue by clautergatti** [dbeaver/dbeaver#19760]
### Description

After upgrade Eclipse 2023-03 (4.27.0) and DBeaver to 23.0.2, I am getting the error below and all my DB connections disappeared. Also, if I setup a new connection, close Eclipse and come back, same error is happening!

Error refreshing node

Reason:
Cannot invoke "com.google.gson.internal.JsonReaderInternalAccess.promoteNameToValue(com.google.gson.stream.JsonReader)" because "com.google.gson.internal.JsonReaderInternalAccess.INSTANCE" is null

### DBeaver Version

23.0.2

### Operating System

Windows 10 Enterprise

**Comment by ShadelessFox** [comment]
Hello @clautergatti,

Are you installing DBeaver as an Eclipse plugin?

**Comment by clautergatti** [comment]
@ShadelessFox , yes, I am installing DBeaver as an Eclipse plugin

**Comment by ShadelessFox** [comment]
Thanks for the response.

For now, you can either downgrade DBeaver or install it as a standalone application as a workaround.

**Comment by serge-rider** [comment]
@clautergatti Could you send debug and/or error log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)
IT looks like something is wrong with the databases configuration but without logs it is hard to say what exactly.

**Comment by E1izabeth** [comment]
It's been a while since no update on this issue. If it's still actual, please, let me know and provide log files.
