### ISSUE TITLE
Error calling transpiler/statement

### ISSUE THREAD

**Issue by AdminSPI** [dbeaver/dbeaver#19765]
### Description

Hi,

We are having an issue where a data migration between 2 databases stops working.

The task keep running indefinitely without doing anythign in the log. We then have to terminate it in the task manager.

This is the error we are getting in the log and nothing after.

2023-04-20 12:03:29.400 - Error calling transpiler/statement, attempt 1 of 10 (next retry in PT0.243S)****

Do we know what could be the cause'? This is happening since April 10th.

Thanks

### DBeaver Version

23.0.0.202303201558

### Operating System

Windows Server 2019 Datacenter 1809

### Database and driver

JDBC driver - Cloud database to MS SQL server

**Comment by arhayka** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/

In addition, could you please try to generate a thread dump and attach it here? Here is the instruction: https://dbeaver.com/docs/wiki/Making-a-thread-dump/

Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here, so I'm closing this issue. If it's still actual, please, let me know and provide log files and thread dump.
