### ISSUE TITLE
[Firebird] case statement in select is ignored/not processed

### ISSUE THREAD

**Issue by bkcsfi** [dbeaver/dbeaver#19772]
### Description

Given a `select` with a case/when/else/end statement (shown below), when the `select` is executed by dbeaver the results suggest that dbeaver doesn't send the case portion of the query to the server. However the same query works correctly using isql.

```sql
SELECT
	y.carriername,
	y.SHIPTOSTATE,
	count(y.shipmentid)
FROM
	(
	SELECT
		CASE
			WHEN s.carrier = 'OtherLTL'
			AND s.CARRIEROPTIONS IS NOT NULL THEN substr(s.carrieroptions,
			16,
			99)
			WHEN s.carrier IN ('FedexExpress', 'FedexGround') THEN 'FedexCourier'
			ELSE s.CARRIER
		END carriername,
		s.SHIPTOSTATE,
		s.SHIPMENTID
	FROM
		shipment s
	WHERE
		s.ownerid = 'rv'
		AND 
s.shipdate >= '2022-04-17'
		AND 
s.QUOTE_NUMBER IS NOT NULL
		AND 
s.SHIPTOCOUNTRY = 'US'
) y
GROUP BY
	1,
	2
```

subset of result from dbeaver

```
ABF	CA	1
OtherLTL	GA	1
OtherLTL	TX	2
OtherLTL	WA	1
OtherLTL	VA	1
OtherLTL	CA	1
```

vs output from isql

```
CARRIERNAME                                                                      SHIPTOSTATE        COUNT
=============================================================================== =========== ============ 
ABF                                                                              CA                     1
ELITE LINK                                                                       GA                     1
ELITE LINK                                                                       TX                     2
ELITE LINK                                                                       WA                     1
Elite                                                                            VA                     1
Elite LInk                                                                       CA                     1
```

### DBeaver Version

Community Edition 23.0.2.202304091457

### Operating System

Ubuntu 22.04

### Database and driver

Database Firebird 2.0.1  (yeah, its old)

Driver jaybird-5.0.1.java8.jar  (also fails under 4.0.0.java8.jar )

### Steps to reproduce

Connect to the database

execute the query

### Additional context

direct connection to the server over port 3050, no tls

**Comment by LonwoLonwo** [comment]
Hello @bkcsfi 

Could you check the difference between your query and executed query in the [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager)? Does it exist?

And how did you execute your query? Did you highlight the entire statement? Or just with the focus on the center of the statement? Or?

**Comment by bkcsfi** [comment]
Hi,

The query does appear in the Query Manager.  I selected the row, clicked Copy, and pasted the query below. It appears to be the query I wanted executed, without changes.

Is there any way to see the 'raw' query sent to the firebird server?

I execute the query using ALT-X (Execute Sql Script)

![image](https://user-images.githubusercontent.com/6412502/234099411-4eebc63e-b88a-4b92-b00f-d0234a81139c.png)


```sql
SELECT
	y.carriername,
	y.SHIPTOSTATE,
	count(y.shipmentid)
FROM
	(
	SELECT
		CASE
			WHEN s.carrier = 'OtherLTL'
			AND s.CARRIEROPTIONS IS NOT NULL THEN substr(s.carrieroptions,
			16,
			99)
			WHEN s.carrier IN ('FedexExpress', 'FedexGround') THEN 'FedexCourier'
			ELSE s.CARRIER
		END carriername,
		s.SHIPTOSTATE,
		s.SHIPMENTID
	FROM
		shipment s
	WHERE
		s.ownerid = 'rv'
		AND 
s.shipdate >= '2022-04-17'
		AND 
s.QUOTE_NUMBER IS NOT NULL
		AND 
s.SHIPTOCOUNTRY = 'US'
) y
GROUP BY
	1,
	2
```

**Comment by LonwoLonwo** [comment]
Could you please provide DDL examples of your tables with the example data? For testing. 

For now, it is not clear what you mean about:

> doesn't send the case portion of the query to the server

Query in the Query manager - is the query that DBeaver sends to the server.

**Comment by bkcsfi** [comment]
Thanks for looking into this. 

Since the query manager shows the correct sql query is being sent to the database, would you agree that  this issue is likely to be caused by the db driver?  Perhaps I should follow-up with the firebird/jaybird group instead?

**Comment by LonwoLonwo** [comment]
It can be a driver issue, yes. But I cannot be sure without all information for testing from our side.

**Comment by mrotteveel** [comment]
I'd start with upgrading to Firebird 2.0.7 (which, BTW is also not supported, support for Firebird 2.0 ended back in 2012, but there is no good reason to have missed 6 bugfix releases). As an aside, formally, Jaybird 4.0 and higher do not support Firebird 2.0, and it is entirely possible it does things that do not work on Firebird 2.0 (though that shouldn't affect the execution of this query).

In any case, based on the described behaviour, I would guess the `CARRIER` column is a `CHAR(n)`, and I'm wondering if you're using different connection character set in ISQL compared to in DBeaver, and if that connection character set might have a collation with the `NO PAD` clause as its default collation. ISQL defaults to `NONE` unless you used the `SET NAMES <charset>` before connecting, or the `-charset <charset>` commandline option, and I believe DBeaver defaults to UTF8 (but that might just be how I configured my driver settings).

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.
