### ISSUE TITLE
Fetch Count incorrect from export

### ISSUE THREAD

**Issue by KALEL-KANATA** [dbeaver/dbeaver#19775]
### Description

Team I did an export of some data back on March 27, 2023 the fetch count stated 85 but the CSV export had 87

I did the same output today mimicking the same results and the fetch count was the same as the CSV exported.

was something fixed in the  March 27 Update?

I have an audit team asking to to provide a valid reason why this would be and the only reason I can think of what this would happen would be some sort of bug in the SW.

### DBeaver Version

Version 23.0.1.202303250535

### Operating System

Windows

### Database and driver

DB2

**Comment by LonwoLonwo** [comment]
Hello @KALEL-KANATA 

What kind of data did you export? Did this data contain any binary (ex. BLOB) values?

And please clarify it for me. Previously CSV exported files had more data than the source. And now it is the correct value?

**Comment by KALEL-KANATA** [comment]
Hood day no the fetch count in the application had 2 more than the exported
CSV file.  Standard varchar/date col data exported.

**Comment by LonwoLonwo** [comment]
![2023-04-25 10_52_59-Data Transfer](https://user-images.githubusercontent.com/45152336/234215874-da3dbde7-1085-4d76-9d53-30803ccdce34.png)

Hello. Probably the "Selected rows only" setting was checked. 

Do you have this issue now? With an inconsistent count of source and exported files?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual for you, please let me know.
