### ISSUE TITLE
No results fetched when i close statement in DBeaver 21.3.4

### ISSUE THREAD

**Issue by TheMMoh** [dbeaver/dbeaver#19778]
### Description

Hello everyone,

I am new to this so bear with me please.

I recently switched from Dbeaver 3.4.1 to Dbeaver 21.3.4 and now i get an error when i close a statement and no results are shown.
Before when I was using Dbeaver 3.4.1, if i close a statement I get the results that were already fetched before I stopped the script.

So i was wondering if there is a solution to show the results when i close the statement in Dbeaver 21.3.4.

Thank you for your help.

### DBeaver Version

21.3.4

### Operating System

Windows 10

**Comment by uslss** [comment]
@TheMMoh, thanks for the report. Could you provide some scripts to reproduce the issue? video with the issue also could be helpful.

Could you check if the issue is reproducible against the recent dbeaver version (23.0.3)?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual for you, please let me know.
