### ISSUE TITLE
Events in database schema named 'data' are not shown

### ISSUE THREAD

**Issue by cleeh** [dbeaver/dbeaver#19782]
### Description

I guess the reason that tool doesn't show events in database named `data` is the name, `data`
Any other events in databases not named `data` are shown 

![data_events](https://user-images.githubusercontent.com/16813359/233881516-a61faaa5-d1ad-4893-9d9f-595cfd38fc4b.png)
![events_in_data](https://user-images.githubusercontent.com/16813359/233881528-c6279d46-10f0-4a9e-899f-eca45d82270e.png)

### DBeaver Version

Community Edition 20.0.2

### Operating System

Linux Mint 21.1 Vera

### Database and driver

Database: MySQL 5.7.12
Driver: MySQL Connector/J mysql-connector-java-8.0.29

### Steps to reproduce

1. Connect to database named 'data'
2. Create table named `data`
3. Create any event
4. After event is created, event row disappear in database navigator

**Comment by LonwoLonwo** [comment]
Thanks for the report @cleeh
