### ISSUE TITLE
Add debian repository for apt integration

### ISSUE THREAD

**Issue by thomaszbz** [dbeaver/dbeaver#1978]
apt has a notion to verify integrity and origin of downloads, which would be a follow-up to #1977. Plus, does it allow automation of (security) updates.

Both together improves security a lot as it allows to automatically install (security) updates from a trusted source. Thereby, improved usability in fact improves security a lot and by default.

Now that not every distro offers dbeaver in their package repository, I'd like to get .deb packages from upstream sources. Plus, am I interested in up-to-date packages which I seldomly get via repos hosted by a distro.

For the authenticity check, the public key material for the debian repository should be offered via a TLS secured https resource (that seems to be pretty important!) so that the public key exchange can be documented together with a TLS secured ressource:

    wget -O - https://dbeaver.jkiss.org/path/to/archive.key | sudo apt-key add - 

Side note 1: The whole security model is broken if some untrusted random guy uploads the packages on his or her untrusted personal (e.g. launchpad) repo in the hope that people use it. That's very dangerous because the whole build process is more or less unknown at this place, so that the attack vector even scales much better than a MITM attack. That said, should the maintainers of the software themselves offer the debian repo (and most importantly the public key of it) or let the work do by a package maintainer they have trust to (and officially publish who that is and which repo is to be used).

Side note 2: The debian repo should be usable for other debian based distros as well (like ubuntu).

Side note 3: Optional: Once the debian repo is in place, the update check can be disabled by default for the packages in that repo now that apt can do the job. It's not very important to me to mitigate dbeaver to talk home now that I can turn that off manually. On the other side, it's redundant and can be an attack vector, especially when talking home takes place unsecured. So that would be about safe defaults only.

**Comment by netsgnut** [comment]
Very much looking forward to it here. While a self-host solution is often preferred, it is not uncommon that some FLOSS projects turn to [Bintray](https://bintray.com/) or [Packager](https://packager.io/), too, for easier setup. The key is, just as mentioned by @thomaszbz, only the maintainer(s) should have the access to it, rendering it an official release channel.

**Comment by serge-rider** [comment]
Seems to be very similar to #1667 .
However we may need debian repo on jkiss.org as well (not just on launchpad).

**Comment by thomaszbz** [comment]
@serge-rider You could also (publicly) announce that e.g. bintray IS the official channel. This announcement should again be available securely via e.g. TLS-secured download page. And, of course, downloads via such a service must be secure again. And, of course, the maintainer who maintains the official repo, would have to be trusted.

**Comment by serge-rider** [comment]
Since 5.2.2 we host our Deb repository: https://dbeaver.io/download/#deb
```bash
wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -
echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list
sudo apt-get update && sudo apt-get install dbeaver-ce
```

**Comment by unhammer** [comment]
Oh, cool. Maybe this should be closed then?

**Comment by serge-rider** [comment]
Yep
