### ISSUE TITLE
[connect to a database] pop out when startup Dbeaver with version 23.0.3

### ISSUE THREAD

**Issue by qilinsanshao** [dbeaver/dbeaver#19781]
### Description

Hello:
when I upgrate the newest version of Dbeaver, it happens that:
the window of [connect to a database] alway pop out when I startup the Dbeaver....
![Snipaste_2023-04-24_09-47-42](https://user-images.githubusercontent.com/63779854/233881433-3515ad87-643b-4507-91b3-29855c382695.jpg)

### DBeaver Version

Community Edition 23.0.3

### Operating System

Windows

**Comment by LonwoLonwo** [comment]
Hello @qilinsanshao 

Do you have any connections in your workspace? Does the new connection selection window appear any time now in DBeaver or only once after the upgrade?

**Comment by E1izabeth** [comment]
Could you record a short video showing the issue (how you start DBeaver and what is happening then with this window)?

**Comment by qilinsanshao** [comment]
it looks returned normal... I will continuous monitor to check if it had this issue.
thanks!
