### ISSUE TITLE
I found two problems while upgrading to Dbeaver 23.0.3.

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#19780]
### Description

1. When using bind parameters, the input value window pops up every time it is executed.
   However, if the @set command is used, the bind variable input window does not appear.
2. In the previous version, the case of the bind variable was distinguished, but in this version, it is changed to upper case unconditionally.
![이미지 003](https://user-images.githubusercontent.com/59002295/233876490-7af69cc4-c864-4e9f-a69e-8b94680568bc.gif)

I am always grateful for developing good programs. :)

### DBeaver Version

Community Edition 23.0.3

### Operating System

Windows 10

### Database and driver

Oracle

**Comment by E1izabeth** [comment]
Thank you for bug report.

The parameters are case-insensitive, so case does not matter. The only thing changed is how the parameter name in shown in user interface. But if you want to make parameter case-sensitive, now you can put it into quotes.

**Comment by podoni** [comment]
Thank you for always kind replies. :)

**Comment by E1izabeth** [comment]
Could you tell me which version you used before when Bind parameters dialog didn't appear on the second query?

**Comment by E1izabeth** [comment]
Our wiki says that it is a desired behavior to ask the user about parameters on the parametrized query execution: https://github.com/dbeaver/dbeaver/wiki/SQL-Execution#dynamic-parameter-bindings

We have script variables to set implicit context values which doesn't require user intervention during query execution.
