### ISSUE TITLE
Improve security of SSH hosted by dbeaver.jkiss.org

### ISSUE THREAD

**Issue by thomaszbz** [dbeaver/dbeaver#1979]
The server `dbeaver.jkiss.org` only has a [CryptoSense](https://discovery.cryptosense.com/discover/dbeaver.jkiss.org) C rating in terms of SSH security. Please get an A rating for SSH.

The steps to follow mostly are easy and can be done in 10 minutes (just google a bit, it's all there). For a B rating:
- Generate ECDSA and RSA key material server-side in `/etc/ssh` and test if it works and also is used
- Drop 3DES, DSA and RC4 key material without locking yourself out (that's what the previous step is good for)
- Increase the Diffie Hellman Parameters. [Generate](https://weakdh.org/sysadmin.html) custom parameters (can be generated with openSSL) with 2048 bit at least (768 bit and lower have been proven to be breakable, 1024 bit are likely to be doomed next).

For an A rating:
- Get a B rating
- Disable Blowfish cipher and CAST-128 cipher. Again, without locking yourself out
- ~~Eventually, an update of SSH packages does the trick, too. I'm not aware that I ever had to do this step manually.~~

Please note that attackers have the bad habit to break into systems and replace downloads with manipulated versions (together with manipulated hashes, of course). Also, using TLS would not mitigate that attack vector.

Just as an additional measurement, I also suggest to once (and after that periodically) replace any SSH key material used on that server (especially the host key). Also, check `.ssh/authorized_keys` in user profiles for unauthorized or outdated public keys (again, without locking yourself out).

The cryptosense D rating for TLS eventually can be ignored as long as TLS is not used at all (and as long as the certificate currently presented is not used at all).

**Comment by orasul** [comment]
Fixed.
