### ISSUE TITLE
Arch/AzureSQLServer AD MFA - Unable to open default system browser

### ISSUE THREAD

**Issue by joachimnielandt** [dbeaver/dbeaver#19802]
### Description

Hello all,

I am transplanting a working configuration from Windows DBeaver to Arch DBeaver. There, the configured connection doesn't work and fails with an error.

The configuration of the connection is as follows:
- Azure SQL Server
- Authentication: Active Directory - MFA
- Username: my.email

Drivers were downloaded through the dbeaver functionality, I can see them appear as .jar files, e.g., ` ~/.local/share/DBeaverData/drivers/maven/maven-central/com.microsoft.azure`. 

I get the following error when running "test connection":
```
023-04-25 16:59:36.503 - [Correlation ID: a6686b5e-f01d-4a1b-b3ca-76b501152ca3] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed.
com.microsoft.aad.msal4j.MsalClientException: Unable to open default system browser
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.openDefaultSystemBrowser(AcquireTokenByInteractiveFlowSupplier.java:116)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResult(AcquireTokenByInteractiveFlowSupplier.java:61)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:37)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:71)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:20)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

When running `xdg-open https://domain.com` I have a working 'default browser'  functionality, in that it opens firefox with the right URL. Do I need additional configuration here? I tried the DBeaver setting for the browser override, which didn't have any effect.

### DBeaver Version

CE 23.0.2.202304160044

### Operating System

Linux 6.2.12-arch1-1 (amd64)

### Database and driver

Microsoft JDBC Driver for SQL Server
https://github.com/Microsoft/mssql-jdbc
mssql-jdbc-11.2.3.jre11.jar

### Steps to reproduce

1. configure sql azure connection on fresh arch installation (java 17)
2. start dbeaver in console
3. set up connection with MFA
4. download required drivers with dbeaver
5. click test connection
6. error appears in console

**Comment by LonwoLonwo** [comment]
Hello @joachimnielandt 

Please try to do this:

Go to "Edit Driver Settings," click the "Libraries" tab, then click "Add Artifact," then add the Maven dependency declaration:

```
<!-- https://mvnrepository.com/artifact/com.microsoft.azure/msal4j --> 
<dependency> 
<groupId>com.microsoft.azure</groupId> 
<artifactId>msal4j</artifactId> 
<version>1.11.3</version> 
</dependency>
```

Note: if it will not help, please try to use newer version of msal4j

**Comment by joachimnielandt** [comment]
Most excellent, that did the trick. Strange that this works though, as there's already a declared library in the default settings:

![image](https://user-images.githubusercontent.com/11455912/234888841-4fc415f9-a9cf-4ae2-966e-ebb190178a56.png)

1.12.0 was present, I added 1.11.3 per your instructions. Would this mean that 1.12.0 is not functional, or that DBeaver is not loading the library correctly using those default libraries?

**Comment by LonwoLonwo** [comment]
Unfortunately, I do not have a test environment to check it. So, I suppose that 1.11.3 - is a working version for this (11.2.3) driver version. 

Could you please check with the newer msal4j library version?

```
<!-- https://mvnrepository.com/artifact/com.microsoft.azure/msal4j --> 
<dependency> 
<groupId>com.microsoft.azure</groupId> 
<artifactId>msal4j</artifactId> 
<version>1.13.0</version> 
</dependency>
```

Or use the "update" button on the msal4j library in the driver settings -> library dialog? Other (1.12, 1.11.3) msal4j libraries must be removed in this case.

**Comment by joachimnielandt** [comment]
Hi @LonwoLonwo , I removed the other msal4j libs and added the above (1.13.0) manually. Using that, logging in seems to work fine as well. 

Removing the msql4j driver and then automatically resolving the necessary libraries doesn't work though, also when configuring a new Azure connection to use MFA.

**Comment by LonwoLonwo** [comment]
So... It is working, but only with specific jars versions? Could you please provide a screen from your libraries list from connections settings for the working case?

**Comment by joachimnielandt** [comment]
Sure thing: 

![image](https://github.com/dbeaver/dbeaver/assets/11455912/f1dab52a-fb13-488a-b66d-07ebcc521e1e)
