### ISSUE TITLE
many idle sessions

### ISSUE THREAD

**Issue by ggree1** [dbeaver/dbeaver#19817]
### Description

![image](https://user-images.githubusercontent.com/48195768/234765915-ba79c445-c3ec-442e-a97a-b96ac676ff2c.png)

More than 120 idle sessions for on sql editor.
Is that normal?
And too many notifications of 'datasource was invalidated'.
Please let me know if there is a solution.

### DBeaver Version

community 23.0.3

### Operating System

windows 11

### Database and driver

jdbc postgresql 42.5.0

**Comment by arhayka** [comment]
Can you try disconnecting and connecting back **separately** to the database to see if all idle transactions are gone?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.

**Comment by E1izabeth** [comment]
It looks like a duplicate of #8303
