### ISSUE TITLE
Don't override ini file on update

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#19814]
### Description

While trying to run a block of plglsql code across a number of clusters dBeaver starts throwing up out of memory errors and asking if I want to shutdown the application (see attached images).

my memory settings in the dbeaver.ini **were**
-Xms256m
-Xmx4096m

but apparently when dBeaver upgraded itself to 23.0.3 it **reverted** back to
-Xms64m
-Xmx1024m

Is there a way to:

1. stop dBeaver upgrades from resetting the memory allocation in the dbeaver.ini file
2. better handle memory management/garbage collection so that it doesn't need so much memory.

[thread-dump_2023-04-26.txt](https://github.com/dbeaver/dbeaver/files/11333844/thread-dump_2023-04-26.txt)

![dBeaver_23 0 3_crash_p1_20230426_094851](https://user-images.githubusercontent.com/3697063/234597807-9523c13a-5c35-433d-a796-ade40d39f46f.png)
![dBeaver_23 0 3_crash_p2_20230426_094851](https://user-images.githubusercontent.com/3697063/234597830-2f30b4db-d142-4072-880a-56badabacc3b.png)

### DBeaver Version

Community Edition 23.0.3

### Operating System

Windows 10

### Database and driver

PostgreSQL 11,14,15

### Steps to reproduce

connect to cluster
run plpgsql code
connect to cluster
run plpgsql code
connect to cluster
run plpgsql code
connect to cluster
crash on connection

**Comment by shantanubindhani** [comment]
I was working with an AWS remote server, but after updating to the latest Dbeaver, i am unable to connect to that server anymore, 
i was using the snap-installed version, so then i tried the stand-alone version(dbeaver zip) available at the official site, but the problem still remains same.
Again, i was able to connect at ease before update.
![Screenshot from 2023-04-27 10-23-15](https://user-images.githubusercontent.com/48177913/234762607-81f0b02a-9b29-40e9-b618-9d2760b27645.png)

**Comment by LonwoLonwo** [comment]
Hello, @shantanubindhani. Please check that your connection contains all the necessary parameters, including the user name and password.

**Comment by shantanubindhani** [comment]
It does, i have not changed any parameters, i used the same parameters for connecting before the update, which i used after...

And it's not just me, but there are a few colleagues of mine facing the same issue.

**Comment by coleman-rik** [comment]
@LonwoLonwo I think my issue might have been sidetracked by @shantanubindhani.

I just updated to version 23.0.4 and again the upgrade wiped my dbeaver.ini settings.

my memory settings in the dbeaver.ini was:
-Xms256m
-Xmx4096m

but apparently when dBeaver upgraded itself to 23.0.4 it reverted back to
-Xms64m
-Xmx1024m

Is there anything that can be done about this?
thanks.

**Comment by E1izabeth** [comment]
We have existing issue about adding memory jvm parameters to gui #7546
Probably, we should also discuss possibility of non-overriding ini file on update.

Thank you for the issue.

**Comment by E1izabeth** [comment]
The issue about keeping ini file untouched on update is here #7727
Thank you for your request. I'm closing this issue as it duplicates the mentioned. You can vote under these issues by adding the emoji under the issue description.

**Comment by oemaix** [comment]
I have exactly the same problem.
