### ISSUE TITLE
Oracle Date value should not display filler timestamp

### ISSUE THREAD

**Issue by elau1004** [dbeaver/dbeaver#19813]
### Description

An Oracle DATE data type does not have any time component.  When querying these type of column the default should NOT display any "filler" or "padded" time value.

![image](https://user-images.githubusercontent.com/7436809/234590070-62087980-650b-4487-9394-57e84641d7ec.png)

The padded "**00:00:00.000**" time values takes unnecessary screen real estate especially on a laptop.

This should not only be an Oracle specific display default but for all DATE data type that does not have any time component.

### DBeaver Version

Community Edition 23.0.2

### Operating System

Windows 11

**Comment by LonwoLonwo** [comment]
Hello @elau1004 

You can change this behavior in your connections settings:

![2023-04-26 16_52_12-Connect to a database](https://user-images.githubusercontent.com/45152336/234597470-bc683f71-6ce0-4e37-8624-9ef54b03b4b2.png)

**Comment by elau1004** [comment]
I do have it in my setting and it is still displaying  the date with the padded time value.
![image](https://user-images.githubusercontent.com/7436809/234649852-f56b943d-1897-46bb-a4a8-e7843013a9dc.png)

**Comment by LonwoLonwo** [comment]
Yeah, now I see. This setting works in tables but not in the result sets.

**Comment by LonwoLonwo** [comment]
Thanks for the report.
