### ISSUE TITLE
SQL editor font can't be changed

### ISSUE THREAD

**Issue by ibobak** [dbeaver/dbeaver#19815]
### Description

I spend more than 15 minutes trying to find out where is the setting that would allow me to change the font of SQL editor? 

Here is what I see, but nothing of these works:
![image](https://user-images.githubusercontent.com/8807043/234632194-7f832d6e-cbb3-43be-94ec-c67e77079d8f.png)

### DBeaver Version

Community 23.0.3.202304240616

### Operating System

Ubuntu 23.04

### Database and driver

A lot of them, mostly clickhouse. But for my problem it doesn't matter.

### Steps to reproduce

1. Open Windows/Preferences menu
2. Go to User Interface / Appearance / Colors and Fonts
3. Try to find the setting which would allow to change the SQL editor font  -  NO SUCCESS.

**Comment by o42-michalpawlowski** [comment]
See Issue #19354

**Comment by hrimthrusa** [comment]
I couldn't reproduce it in DBeaver Community 23.0.3.202304240616 both in Ubuntu 23.04 and 22.04.2 (TLS). 

I installed DBeaver using .deb [file](https://dbeaver.io/files/23.0.3/) so please try to do the same in case you did it otherwise.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.

**Comment by wesleyaip** [comment]
I'm going through the same problem. Even though I change the font and size, whenever I open DBeaver again, the default font is back to what it was before.
I'm using version 23.1.3.202307231901
