### ISSUE TITLE
Autocomplete duplicates table aliases 

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#19821]
### Description

The user said that DBeaver autocomplete adds an additional alias:

In the following sample query, When we start typing "a." DBeaver generates suggestions of columns and when we pick a column by pressing enter on the required column DBeaver ends up typing not just the column name but a.column_name resulting in text a.a.column_name. Then we have to go back and delete the second alias. It is frustrating. Is this something that can be fixed? Attached is the screenshot of the DBever verison we have also recording of the issue with test datasets in snowflake.

```
select 
a.*
from table_a a inner join table_b b on a.id=b.id
```

https://user-images.githubusercontent.com/12581569/234844531-ceee5aa0-7144-4db5-8b0f-aab4de498bf1.mov

![image](https://user-images.githubusercontent.com/12581569/234845273-b30e312c-41e9-45ec-8ec5-2ea51cb28027.png)

### DBeaver Version

СЕ 23.0.2

### Operating System

macOS

### Database and driver

Snowflake

**Comment by Destrolaric** [comment]
Linked to https://github.com/dbeaver/dbeaver/issues/5247

**Comment by milkandrelish** [comment]
I have the same problem, and it is incredibly frustrating.

**Comment by jezabennett** [comment]
This problem also affects my 100s of times per week. Hope it can be selected for a fix soon.
