### ISSUE TITLE
"Incompatible JVM" message after 23.0.3 install

### ISSUE THREAD

**Issue by JimmyTheExploder** [dbeaver/dbeaver#19836]
### Description

Getting reports from our users that after they install version 23.0.3 (Community Edition) and launch it, then get a dialog titled "Incompatible JVM". Text in the dialog states "Version 11.0.12 of the JVM is not suitable for this product. Version: 17 or greater is required. 
DBeaver is getting installed via the Company Portal or Software Center on Windows 11/Windows 10 devices. The application is managed by a 3rd party vendor. The installer being used is the x86_64-setup.exe. We've had DBeaver in our environment for at least a couple years and I'm unaware of a similar issue being noted previously. 

I did see a similar issue noted here for version 22.3: https://github.com/dbeaver/dbeaver/issues/18991. 

So far, the fix that has worked for us is to have users reinstall the application. They're then able to launch it without getting the dialog noted above.

### DBeaver Version

Community Edition 23.0.3 

### Operating System

Windows 10 and 11

### Database and driver

DB2 (db2jcc4-4.23.42)
Hive (1.9-2.6.5)

### Steps to reproduce

Install DBeaver from Software Center (WIndows 10) or Company Portal (Windows 11). A previous version of the application (generally 22.2) existed on all devices where users have reported having the issue.
Launch DBeaver.
"Incompatible JVM" dialog appears.

**Comment by hrimthrusa** [comment]
In DBeaver root directory you will find a `dbeaver.ini` file. Add a `-vm` parameter with a correct path to the bin directory of your recent JDK with java version 17 or higher just before the `-vmargs` parameter as shown here:

![1](https://user-images.githubusercontent.com/97725836/236395388-5efc4f64-1b1a-491e-91c2-e75a120a1f76.png)

DBeaver comes with JDK 11.0.18 from the Microsoft Store and you may ask your 3rd party vendor to pack the very same JDK in their repacks.
