### ISSUE TITLE
Refresh Resultset button

### ISSUE THREAD

**Issue by almiroliveira** [dbeaver/dbeaver#19839]
### Description

The "resultset refresh" button is closing active resultset tabs every time we click it.

### DBeaver Version

Community Edition 23.0.3

### Operating System

Windows 10

### Steps to reproduce

1. Execute a sequence of queries on some existing tables, for example:
SELECT * FROM customer;
SELECT * FROM order;
SELECT * FROM employee;
....

2. Select, for example, the first result tab;

3. Click on the "resultset refresh button F5";

Notice that the tabs close with each click.
The same thing happens when using the F5 shortcut.

**Comment by Destrolaric** [comment]
Hi, Can you please provide me with some information about the database you are using?
