### ISSUE TITLE
ip address is displayed with a left slash

### ISSUE THREAD

**Issue by pr4gmat1q** [dbeaver/dbeaver#19849]
### Description

Dbeaver from PPA repo. ClickHouse Data view (Data type IPv4)  displayed with a left slash, but the console client shows the correct values
![clhs](https://user-images.githubusercontent.com/19203701/235610431-9a4b2260-cf01-402c-9ffa-4207d78fecac.png)
![clc_console](https://user-images.githubusercontent.com/19203701/235611574-36fc9f32-7626-4442-b5a5-d01c51c79575.png)

### DBeaver Version

CE 23.0.3.202304240616

### Operating System

Ubuntu Mate 20.04

### Database and driver

Clickhouse 22.9.3.18

### Additional context

Tunnel over SSH to server

**Comment by uslss** [comment]
thanks for the report
