### ISSUE TITLE
Replace legacy crypto in password based encryption (PBE)

### ISSUE THREAD

**Issue by thomaszbz** [dbeaver/dbeaver#1984]
DBeaver does "Secure Storage". Without having examined what this "Secure Storage" actually is good for, I stumbled upon the algorithms used for the encryption:

![ajgmehyoiw](https://user-images.githubusercontent.com/11200727/29069074-b4d8f8da-7c39-11e7-9383-d412bc2151c8.png)

- DES is known to be insecure since ~20 years and now there's [practically usable attacks](http://mirror-1.server.selfnet.de/CCC/events/SHA2017/h264-sd/SHA2017-320-eng-Legacy_Crypto_Never_Dies_sd.mp4).
- RC2 has [passed away](https://pdfs.semanticscholar.org/24c2/d12eb86a3b272e5216d41d78d2194f6729c0.pdf) ~20 years ago.
- For MD5, there's rainbow tables and all sorts of things.
- RC4 got forbidden for use in TLS at least via [RFC7465](https://tools.ietf.org/html/rfc7465).
- SHA-1 has been [shattered](https://shattered.io/).

3DES might [still be safe](http://mirror-1.server.selfnet.de/CCC/events/SHA2017/h264-sd/SHA2017-320-eng-Legacy_Crypto_Never_Dies_sd.mp4) in respect to ordinary attackers.

The default setting seems to be `PBEWithMD5AndDES`, which is MD5 together with DES. I guess that SHA-1 together with 3DES would be a much better default if I only take the algorithms which are in use already. The combination of SHA-1 together with 3DES is not in the list, however.

Side note: Now that DBeaver itself is very transparent which algorithms are applied (which is good!), I don't see a reason to keep this issue secret in the manner of responsible disclosure.

**Comment by serge-rider** [comment]
Not sure I can do this easily (all these algorithms came from standard Eclipse extension). But I'll try to do something..

**Comment by thomaszbz** [comment]
Of course. That's something to be done in the long run.

Btw: are these algorithms in use by dbeaver?

A quick catch would be to use a much safer default at least (SHA-1 + 3DES). That's not _that_ much broken.
