### ISSUE TITLE
Inability to connect to PostgreSQL DB using SSL certificates (PG ADMIN 4 connects without issue)

### ISSUE THREAD

**Issue by dkontominas** [dbeaver/dbeaver#19841]
### Description

1. I am using PostgreSQL v15.2 installed in a Windows 10 Pro 64bit machine. 
2. I am using OpenSSL WIN64 v.3.1 and craeted the keys/certificates with this version.
3. The commands that I used for creation the certificates/keys as those as attached in the file ssl_creation.txt:
[ssl_creation.txt](https://github.com/dbeaver/dbeaver/files/11362094/ssl_creation.txt)
4. The corresponding modified lines in the configuration are as follows:

**pg_hba.conf**
hostnossl   all   all   0.0.0.0/0   reject
hostnossl   all   all   ::/0        reject
hostssl     all   all   0.0.0.0/0  cert clientcert=verify-full
hostssl     all   all   ::/0        cert clientcert=verify-full

**postgresql.conf**
ssl = on
ssl_ca_file = 'ca.crt'
ssl_cert_file = 'server.crt'
ssl_key_file = 'server.key'

5. The corresponding generated certificates/keys I am attaching here for quickly testing in your system (in the attached zip file).. 
[keys_certificates.zip](https://github.com/dbeaver/dbeaver/files/11362112/keys_certificates.zip)
 
6. PG Admin application by declaring these files connects successfully using postgres user (PG Admin Version: 4, Application Version: 6.21).
7. The message I get from DBeaver when he attempts to connect is: "Invalid Client Certificate".

I tried various combinations and parameters without success though.

Kindest regards,
Dionisis Kontominas

### DBeaver Version

Community Edition 23.0.3

### Operating System

Windows 10 Professional / Workstation

### Database and driver

Database Name and Version: PostgreSQL 15.2 Windows 64 bit
PostgreSQL JDBC Driver: 42.5.0 (postgresql-42.2.10.jre7.jar) 

### Steps to reproduce

Just modify your database configuration files 
Recreate the keys/certificates with the commands I am ttaching or directly use those attached in the zip file
Move the necessary certificates in the PostgreSQL/15/data directory
Attempt to connect via PG Admin (should connect successfully after providing the SSL settings)
Attempt to connct witj DBEaver using the settings and it will fail :

![DBeaver_Settingsjpg](https://user-images.githubusercontent.com/2861553/235372336-ee689f78-8a4a-4763-9742-8d269d53328f.jpg)

**Comment by dkontominas** [comment]
In continuation to the previous I have found that the source of the issue is the CN that is used to produce the clinet's certificate/key. It has to be the same as the name of the user in postgreSQL that is connecting with the SSL-enabled postgres database. That leads to the need of creating a combination of certificate/key for every database user...

**Comment by arhayka** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.
Please try to change the SSL Factory setting or try to use another SSL mode.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.

**Comment by sangrepura** [comment]
I tried to evaluate DBeaver and had the same issue.  

<img width="1143" alt="Image" src="https://github.com/user-attachments/assets/189dc05c-4415-4200-a14f-2cb4d0534a71" />

#
### Works in Beekeeper**
#

![Image](https://github.com/user-attachments/assets/8012581b-730b-47e3-999c-1004bdbebfde)

#
### Works in VSCode**
#

![Image](https://github.com/user-attachments/assets/46bf3ccd-21ad-4666-bf40-04c96583a267)
