### ISSUE TITLE
Multiple Databases Show the Same Data

### ISSUE THREAD

**Issue by mishatim** [dbeaver/dbeaver#19855]
### Description

I have several databases under "Databases".
All of them show the same data, as in the database that was used in login parameters.
I'd expect that when I'm navigating to another database and check its data, it should actually be different.

### DBeaver Version

Community Edition 23.0.3

### Operating System

macOS 13.3 (22E252)

### Database and driver

Postgresql db and driver

### Steps to reproduce

Simple test:
<db-name>
   Databases
      dbX
      dbY
      dbZ

1. Navigate to dbX and make any change.
2. Navigate to dbY and observe the same change present.

**Comment by E1izabeth** [comment]
Did you configured connection with URL or with host and port?

**Comment by mishatim** [comment]
Configured connection via Host, Port, Database name.

**Comment by mishatim** [comment]
@E1izabeth thank you for the tip!
When I configured connection with URL, I was able to see the data in other databases.
Appreciate your suggestion!  It's perfect workaround.

**Comment by E1izabeth** [comment]
Could you show me how do you configure your connection with URL?It would  nice if you could send a screenshot like I attached.
I was expecting that you experience an issue with URL-configured connection, so I wonder which URL do you use so it work for you.
![image](https://user-images.githubusercontent.com/28875055/236211165-ee35b294-be93-4af2-94ae-debe7916d967.png)

**Comment by mishatim** [comment]
Hi @E1izabeth, just to clarify, the issue was happening when I configured the connection via host.
When I configured via URL, it worked fine.
<img width="691" alt="Screenshot 2023-05-04 at 7 02 59 AM" src="https://user-images.githubusercontent.com/28066822/236232547-3e6e5e48-863c-4f36-8391-46d96ab08b75.png">
<img width="692" alt="Screenshot 2023-05-04 at 7 01 35 AM" src="https://user-images.githubusercontent.com/28066822/236232600-52aee79f-586b-4129-94f2-3a06d2ba975e.png">

**Comment by E1izabeth** [comment]
Thank you for response

**Comment by LonwoLonwo** [comment]
Hello @mishatim 

Could you please remove the database and schema part from your host parameter and try again to connect with the Host authentication method?

![2023-05-08 16_31_04-236232547-3e6e5e48-863c-4f36-8391-46d96ab08b75 png (Изображение PNG, 1382 × 956 ](https://user-images.githubusercontent.com/45152336/236837628-34b14694-ee4a-4038-80b9-a49fcbc98e1e.png)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know.
