### ISSUE TITLE
SSH Tunnel: Incorrect hostname `localhost` is checked against the SSH host certificate

### ISSUE THREAD

**Issue by ryanc-me** [dbeaver/dbeaver#19854]
### Description

The `SSHJ` SSH tunnel implementation incorrectly checks `localhost` against the SSH server host certificate.

This is particularly important for StepCA or Teleport users, where the host certs likely contain the servers IP, and **not** `localhost`.

Note that this error only occurs when using a jump server. The `Local host`, `Remote host`, and `Bypass host verification` options don't have any impact.

### DBeaver Version

Community Edition 23.0.3.202304240616

### Operating System

Windows 11

### Database and driver

Not applicable - the error happens _before_ connecting to the database.

The issue is present for at least these two drivers:
- `mysql:mysql-connector-java` 8.0.29
- `org.postgresql:postgresql` 42.5.0

### Steps to reproduce

You will need:
1. An SSH jump server
2. A remote database server
   - Must be accessible via SSH
   - With _or_ without the jump server
4. Your `known_hosts` configured to accept hostkeys from both the database & jump servers
5. The host certificates for both servers are signed 

Then, in DBeaver:
1. Create a new connection. Any driver will work (I tested with PostgreSQL and MySQL).
2. Enable SSH Tunneling
   - Pick `SSHJ` as the implementation
   - All other advanced settings left as default
3. Ensure the `Use jump server` section is enabled & filled out
4. Click `Test tunnel configuration`

An error is thrown: `KeyExchange certificate check failed: Hostname 'localhost' doesn't match any of the principals: 'xxx.xxx.xxx.xxx'`.

Then, try:
1. Disable `Use jump server`
2. Click `Test tunnel configuration`

The SSH connection works without issues.

### Additional context

[dbeaver.log](https://github.com/dbeaver/dbeaver/files/11377346/dbeaver.log)

**Comment by ryanc-me** [comment]
The PR above is a workaround. Using `Bypass host verification` will totally disable host verification, which isn't ideal.

I've done some digging:
1. When using a jump server, DBeaver actually sets up 2 consecutive SSH connections (i.e., we don't just use SSH's `-J` option)
2. First, we connect to the jump server using its actual hostname (e.g. jump.example.com)
3. Then, we [perform some forwarding](https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.net.ssh.sshj/src/org/jkiss/dbeaver/model/net/ssh/SSHImplementationSshj.java#L89) from `localhost:1234` -> `192.168.1.123:22`
4. Finally, we [SSH to](https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.net.ssh.sshj/src/org/jkiss/dbeaver/model/net/ssh/SSHImplementationSshj.java#L96) `localhost:1234`, which effectively connects us to the final SSH server

As far as SSHJ is concerned, we're connecting to `localhost`, which may not match the hosts certificate. We should be using `192.168.1.123` for the host check The cert check is done [here](https://github.com/hierynomus/sshj/blob/a0169747434e0081a471f7db997b40f61c8270ca/src/main/java/net/schmizz/sshj/transport/kex/AbstractDHG.java#L117). The remote host used for verification is not public, so we can't overwrite that from the DBeaver side.

<br />

As far as I can see, there are two options:
 1. Disable host certificate checking when using a jump server, or
 2. Create a PR at SSHJ to allow for a `hostAlias` specifically for situations like this (allow for the checked hostname to be overriden)


**Edit**: Solution 1 implemented below.

**Comment by E1izabeth** [comment]
Thank you for bug report.

Have you tried using another ssh implementation?
![image](https://user-images.githubusercontent.com/28875055/236561173-affc42b9-8a28-43de-8b66-19eeec01b8f0.png)

**Comment by ryanc-me** [comment]
I did try `JSch`, but they have dropped support for the SSH-cert type we use (though maybe that's a bug also?)

**Comment by E1izabeth** [comment]
Could you share, what cert type are you talking about?

**Comment by ryanc-me** [comment]
@E1izabeth Sorry, I'm not sure what's happening with `JSch`, and I don't have time to debug right now.

Regarding this issue, I've updated #19857 with better notes about the problem. I think @ShadelessFox may have some input.

**Comment by E1izabeth** [comment]
Thank you for update.
