### ISSUE TITLE
Incomplete display of exported pictures when save ER diagram

### ISSUE THREAD

**Issue by zs0123** [dbeaver/dbeaver#19869]
### Description

1. select data types for er diagram；
![image](https://user-images.githubusercontent.com/79460708/236107226-7cdc01bb-cf71-44c6-a240-fca2d58e630c.png)
2. it seems ok display；
![image](https://user-images.githubusercontent.com/79460708/236107762-73ba5bef-98e7-4827-b3f1-06bdfcd64d0c.png)
3. But incomplete display of exported pictures when save ER diagram
![image](https://user-images.githubusercontent.com/79460708/236107970-ee992ea6-5e34-4b33-9ed1-7d66bd398856.png)

### DBeaver Version

Version 23.0.3.202304240616

### Operating System

windows 11

**Comment by LonwoLonwo** [comment]
Hello @zaosheng 

Unfortunately, I can't reproduce it for now.

![postgres - testSc - characters's-2](https://user-images.githubusercontent.com/45152336/236147531-27c87f14-dcfe-4c9c-99cb-d3240ec2fed5.png)

What external format did you choose for the image? Did you change the ERD view before saving?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.
