### ISSUE TITLE
Display Tab [Data] when displaying properties of a column

### ISSUE THREAD

**Issue by rfbrooks** [dbeaver/dbeaver#19863]
When viewing the properties of a column I would like to see the column values aggregated
. E.g. when viewing the properties of TABLE.COLUMN I currently see only the properties Tab. I would like to - like for tables - also see the Data tab showing the distribution of the COLUMN, so something like

![DBeaver Column Data 1](https://user-images.githubusercontent.com/3717188/235929836-634af77b-8075-408a-9a3f-9424f2fa7bc5.PNG)

![DBeaver Column Data 2](https://user-images.githubusercontent.com/3717188/235929838-cb86f877-557e-41f4-8496-8d62498b5c9e.PNG)

SELECT COLUMN, COUNT(*)
FROM TABLE
GROUP BY COLUMN
ORDER BY COLUMN

![DBeaver Column Data 3](https://user-images.githubusercontent.com/3717188/235929841-24d42fee-315e-4e3b-8ec7-b41fc7274c27.PNG)

**Comment by LonwoLonwo** [comment]
Hello @rfbrooks 

So, you want to see data like in the table, but only for one column?

![2023-05-04 10_49_03-Window](https://user-images.githubusercontent.com/45152336/236144681-cbd41a1f-d1a8-4160-9659-22b18e67c19f.png)

As a workaround, you can hide other columns in the data viewer.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.
