### ISSUE TITLE
Database Navigator not showing all tables in external schema from catalog

### ISSUE THREAD

**Issue by benpung** [dbeaver/dbeaver#19867]
### Description

I created an external schema from a glue catalog.  When I view the external schema in the database navigator pane, I can see the external schema and only one of the tables.  When I query the svv_external_tables, I can see both of the tables that should be there.

SELECT * FROM svv_external_tables where schemaname='<my_schema>';

### DBeaver Version

Community Edition 23.0.3.202304240616

### Operating System

Windows 10

### Database and driver

RedshiftJDBC42-1.2.47.1071

### Steps to reproduce

In aws account 1:
1. create s3 bucket containing multiple prefixes (bucket/folder1/data1.csv, bucket/folder2/data2.csv)
2. create glue database and crawler to crawl data in s3
3. create role with privs to s3 bucket and glue and allow it to be assumed by role in account 2
4. run the crawler to create the tables in the glue database

In aws account 2:
1. create role that can assume role in account 1 and is attached to redshift cluster
2. create external schema in redshift from catalog/database in account 1 by chaining the role in account 1 and account 2.
3. browse to the external schema in database navigator.  only one of the tables in glue database are visible in the external schema.

**Comment by LonwoLonwo** [comment]
Hello @benpung 

We are using the same query for external tables reading:

https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/impls/redshift/RedshiftExternalSchema.java#L139

So, can you please check the following:

1. Did you refresh your schema after table creation? Did you try to reconnect?
2. https://github.com/dbeaver/dbeaver/wiki/Query-Manager Check your Query Manager with enabled filters. You can find the "SELECT * FROM svv_external_tables" query and check - how many rows are returned. Still 1?

**Comment by benpung** [comment]
@LonwoLonwo My mistake.  It's working now exactly as I would expect.  I add a file, crawl it with glue, and it's immediately visible in DBeaver.  I'm not sure what I was doing wrong the other day.  I will close this issue.  Thanks for the response!
