### ISSUE TITLE
An issue with keeping editors open after reconnecting when switching between simple/advanced view

### ISSUE THREAD

**Issue by Essentia-G** [dbeaver/dbeaver#19866]
### Description

If I change the connection view from advanced to simple, an opened editor won't reload. The following error message appears:
<img width="1352" alt="Screenshot 2023-05-03 at 18 31 53" src="https://user-images.githubusercontent.com/54938058/235981513-297884cc-5e29-4fd2-97a3-072642cb3657.png">

### DBeaver Version

DBeaver Ultimate Edition 23.0.4

**Comment by LonwoLonwo** [comment]
Thanks for the report @Essentia-G

**Comment by LonwoLonwo** [comment]
We can show here a more user-friendly message instead of the error.

**Comment by Essentia-G** [comment]
Yes, I have the same suggestion

**Comment by ShadelessFox** [comment]
Please see the explanation here: https://github.com/dbeaver/dbeaver/issues/13981#issuecomment-1135687498

**Comment by arhayka** [comment]
Proposed solution:
1. We want to save two node objects identifiers in editors: current node pass + object id. We should try both identifiers on resolve.
2. On resolve try to fix full node pass. On fail, show an error saying that the connection view mode was changed.
