### ISSUE TITLE
Incorrect data displayed with nested Clickhouse groups involving arrays of strings

### ISSUE THREAD

**Issue by tomaszwegrzanowski-st** [dbeaver/dbeaver#19868]
### Description

When creating nested aggregate involving arrays of strings, DBeaver displays and exports incorrect data, not data actually returned by the database.

### DBeaver Version

Community Edition Version 23.0.3.202304240630

### Operating System

Mac OSX 13.2.1

### Database and driver

Clickhouse 22.3.17.13

### Steps to reproduce

Here's minimal SQL needed to reproduce the issue:

```sql
create table posts(
  title String,
  author String,
  tags Array(String)
) ENGINE = MergeTree()
ORDER BY title;

insert into posts values('Hawaian Pizza', 'Alice', ['Cooking', 'Hawaii']);
insert into posts values('Spaghetti Bolognese', 'Alice', ['Cooking', 'Italy']);
insert into posts values('GPT-5', 'Bob', ['AI']);

select
  author,
  arrayZip(
    groupArray(10)(title),
    groupArray(10)(tags)
  ) as metadata
from posts group by author;
```

As you can see data displayed by DBeaver in Attr1 / Spaghetti Bolognese is incorrect:

<img width="458" alt="Screenshot 2023-05-04 at 02 20 28" src="https://user-images.githubusercontent.com/121940350/236086872-2dd4998c-a9af-4129-8a1f-2ed915438b40.png">

Export to JSON also generates incorrect data, as seen here:

```json
{
"select\n  author,\n  arrayZip(\n    groupArray(10)(title),\n    groupArray(10)(tags)\n  ) as metadata\nfrom posts group by author": [
	{
		"author" : "Alice",
		"metadata" : "['[Spaghetti Bolognese, [Cooking, Hawaii]]','[Hawaian Pizza, [Cooking, Hawaii]]']"
	},
	{
		"author" : "Bob",
		"metadata" : "['[GPT-5, [AI]]']"
	}
]}
```

So it's not just a visual issue.

### Additional context

This is definitely DBeaver issue, not Clickhouse issue.

Command line Clickhouse interface displays correct data for the same query:

```
┌─author─┬─metadata─────────────────────────────────────────────────────────────────────────────┐
│ Alice  │ [('Spaghetti Bolognese',['Cooking','Italy']),('Hawaian Pizza',['Cooking','Hawaii'])] │
│ Bob    │ [('GPT-5',['AI'])]                                                                   │
└────────┴──────────────────────────────────────────────────────────────────────────────────────┘
```

VSCode Clickhouse extension also displays correct data. As does Ruby Clickhouse driver.

The original query that triggered the bug was a lot longer and used complex schema, so I kept simplifying it until I got to this. This is the smallest that still triggers the error. Changing types from strings to integers or using only one level of grouping no longer triggers the bug.

On bigger examples there is some additional weird behavior - scrolling to fetch additional rows will update what's displayed for already fetched rows. But I suppose fixing the underlying issue is likely to fix such cases as well.

**Comment by LonwoLonwo** [comment]
Hello @tomaszwegrzanowski-st 

Please also provide your driver version. You can check it with the "Test connection" button in your Connection Settings.

**Comment by tomaszwegrzanowski-st** [comment]
Server: ClickHouse 22.3.17.13

Driver: ClickHouse JDBC Driver 0.4.2 (revision: 1513b27)

**Comment by zhicwu** [comment]
Hi @tomaszwegrzanowski-st, could you upgrade JDBC driver to 0.4.6? The issue was first reported in ClickHouse/clickhouse-java#1324.

**Comment by tomaszwegrzanowski-st** [comment]
@zhicwu How can I do that? I run DBeaver installed from .dmg package. Where can I upgrade JDBC driver?

**Comment by zhicwu** [comment]
You can upgrade in Driver Manager.

1. Go to `Database` -> `Driver Manager`
2. Edit `ClickHouse` and switch to `Libraries` tab
3. (optional) Click `Reset to Defaults`
4. Click `Download/Update`, change version to 0.4.6 in popup, and then click `Download`

**Comment by tomaszwegrzanowski-st** [comment]
@zhicwu I can confirm that changing jdbc driver to 0.46 this way makes the bug go away, both this simplified version, and in the original query I first found it.

Hopefully that fix can be included in future DBeaver versions soon.
