### ISSUE TITLE
You are advised to add multiple file types when importing data.

### ISSUE THREAD

**Issue by lqyiwwx** [dbeaver/dbeaver#19879]
You are advised to add multiple file types when importing data. 
For example, dbf db txt xls xlsx xml json mdb accdb odbc.
You can learn from navicat's import data.

**Comment by LonwoLonwo** [comment]
Hello @lqyiwwx 

Could you please provide a minimal example of the working case? Why do you need it?

**Comment by LonwoLonwo** [comment]
Hello @im-not-a-robot 

It seems you are talking about another issue.
Can you please provide footage showing your issue? Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here, so I'm closing this issue. If it's still actual, please let me know and provide additional information.
