### ISSUE TITLE
 java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors

### ISSUE THREAD

**Issue by wanderso11740** [dbeaver/dbeaver#19877]
### Description

Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
  java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
  java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
    Path does not chain with any of the trust anchors
    Path does not chain with any of the trust anchors

### DBeaver Version

enterprise  23.0.0.202303201558

### Operating System

windows 10

### Database and driver

mysql 5.6.47
com.mysql.cj.jdbc.Driver

### Steps to reproduce

try to connect to the database and i get the  java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors.   
i tried replacing the CACERT per the KB to no effect
i tried reinstalling without java to no effect

I am running jdk 19

**Comment by LonwoLonwo** [comment]
Hello @wanderso11740 

Could you please check to redownload DBeaver with included JAVA?

![2023-05-05 08_40_06-DBeaver Community 23 0 2 (x86_64) Setup](https://user-images.githubusercontent.com/45152336/236384632-27fe3ace-c4dd-4c57-a638-b25cf6cad80a.png)

**Comment by E1izabeth** [comment]
You could also try changing the state of `Use Windows trust store` setting and restart DBeaever.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/763632d0-a5ee-4dee-bb5e-e979cc0da5fd)

**Comment by wanderso11740** [comment]
I was able to resolve by uninstalling and doing an install for everyone.   Since dbeaver was being installed in a local profile I had issues as the system has policies to not execute like that to prevent virus etc infection.

I had already set on “use windows trust store”

Thanks

**Comment by E1izabeth** [comment]
Thank you for sharing the solution, that helped you.
