### ISSUE TITLE
Changing fallback version of a driver prevents it from being updated

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#19875]
### Description

Changing the fallback version of a driver results in the inability to update it:

1. An empty classifier was added
2. The fallback version is not updated in the dialog
3. Reverting changes didn't help

https://user-images.githubusercontent.com/35821147/236216475-9f80e206-86a2-4194-8658-43d189120eda.mp4

### DBeaver Version

23.0.4

**Comment by serge-rider** [comment]
Wrong fallback version set in dialog was fixed.

But we still loose saved fallback version (and classifier?) value during drivers.xml loading

**Comment by serge-rider** [comment]
Now all predefined Maven artifacts are read-only (because artifact references is the only way to recognize them and artifact references includes group, id, classifier and fallback)
