### ISSUE TITLE
How to make a connection between MySQL to DB2(AS400).

### ISSUE THREAD

**Issue by muskii99** [dbeaver/dbeaver#19883]
### Description

Getting error again and again that The application requester cannot establish the connection. (Connection refused: connect).

### DBeaver Version

DBeaver Community 23.0.3.0

### Operating System

windows 10

**Comment by LonwoLonwo** [comment]
Hello @muskii99

Could you please provide more info about your issue?
Steps to reproduce will be beneficial.

**Comment by muskii99** [comment]
Hi,

I want to make a connection from MySQL to DB2. In that I have to send data from MySQL to DB2 and also to receive it, that means TWO-WAY communication is needed between MySQL to DB2, But when I’m trying to make connection using DBeaver it is throwing an error as below.

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

Note: Do not send it via e-mail. Provide it on this GitHub page.

**Comment by muskii99** [comment]
![image](https://user-images.githubusercontent.com/132650515/236450373-cd02472a-eacd-4058-a3ed-318d8d9f6ae3.png)

**Comment by muskii99** [comment]
Above is the error log file.

**Comment by LonwoLonwo** [comment]
Please foloww the link https://dbeaver.com/docs/wiki/Log-files/ and provide the full log file

**Comment by muskii99** [comment]
![image](https://user-images.githubusercontent.com/132650515/236488810-e72383ca-21c1-4a9e-9b94-108337d7e5f6.png)

I followed the steps you mentioned on above link, but I have got only this log file.

**Comment by LonwoLonwo** [comment]
I need to see the full error stack trace: https://dbeaver.com/docs/wiki/Log-files/#log-files

I want to understand - you want to connect to DB2? Or to MySQL? Or how you want to do connection between MySQL and DB2?

**Comment by muskii99** [comment]
I'm stuck at how to do connection between MySQL and DB2 using DBeaver?

**Comment by muskii99** [comment]
[.log](https://github.com/dbeaver/dbeaver/files/11418416/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/11418417/dbeaver-debug.log)

The above are detailed log files which you are asking about.

**Comment by LonwoLonwo** [comment]
Ok. How exactly do you want to make a connection between MySQL and DB2? Do you use MySQL connection parameters in the DB2i provider connection dialog? Or what? Please provide more details.

**Comment by muskii99** [comment]
Actually, I want to make a connection from MySQL to DB2, In that I have to send data from MySQL to DB2 and also to receive it, that means TWO-WAY communication is needed between MySQL to DB2 and I don't know how to make a connection, So when I was searching about it then I got DBeaver they said that it supports all databases Then I downloaded DBeaver and tried to connect but it started giving me error.

**Comment by LonwoLonwo** [comment]
Yes, you can send data from one database to another.
https://github.com/dbeaver/dbeaver/wiki/Data-migration

But for this data migration operation, you need to have access to two databases - MySQL and DB2i. Do you have it? 
Host + user name + password or other authentication abilities?

**Comment by muskii99** [comment]
Yes I have Host + username + password authentication ability for both databases.

**Comment by LonwoLonwo** [comment]
Could you please provide your DB2 connection page screen? You can blur all private data.

**Comment by LonwoLonwo** [comment]
Also please check your connection provider:

![2023-05-09 12_10_48-Connect to a database](https://user-images.githubusercontent.com/45152336/237050358-809ff4e7-d006-4868-8fc8-d70eed886b8d.png)

If you have DB2 database - choose DB2 LUW provider.
If you have DB2 iSeries - choose DB2 for IBM i
And DB2 for z/OS if you have DB2 for z/OS

**Comment by muskii99** [comment]
Thanks for your support, now I'm able to connect with DB2 as well as MySQL.

**Comment by LonwoLonwo** [comment]
Thanks for the answer. I'm closing this issue, then.
