### ISSUE TITLE
Add option to Customize Toolbar for SQL and Data editor preferences

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#19886]
**Is your feature request related to a problem? Please describe.**
For now we can customize SQL/Data Editor toolbars from the Main Preferences only 

**Describe the solution you'd like**
It will be great if Customize toolbars options will be available from "local" preferences for SQL and Data editors
![image](https://user-images.githubusercontent.com/31996417/236464490-585c38d9-1f7e-40f7-bc8a-48af9020e2b2.png)

**Comment by E1izabeth** [comment]
We have an error in the logs
` !MESSAGE Invalid property category path: org.jkiss.dbeaver.preferences.main (bundle: org.jkiss.dbeaver.core, propertyPage: org.jkiss.dbeaver.preferences.main.toolbar.customization)`

**Comment by E1izabeth** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/28875055/023dfbf9-206b-4c5b-8ee9-4dcfd6c1c8e6)

Now this preference page appears in all properties, but should appear only in SQL Editor and Data Editor properties.
