### ISSUE TITLE
Ubuntu ppa not updated since version 23.0.2

### ISSUE THREAD

**Issue by obarbachan** [dbeaver/dbeaver#19891]
### Description

Hello, I've found a [similar issue ](https://github.com/dbeaver/dbeaver/issues/13868) stating the same problem, but in a different moment. 

The last version on http://ppa.launchpad.net/serge-rider/dbeaver-ce/ubuntu/ was last updated on 2022-11-07.

Thank you

### DBeaver Version

23.0.2

**Comment by serge-rider** [comment]
Updated with 23.0.4

**Comment by obarbachan** [comment]
Thank you!
