### ISSUE TITLE
Faulty `char != -1` check in `OracleDialectRules.QStringRule.doEvaluate`

### ISSUE THREAD

**Issue by Marcono1234** [dbeaver/dbeaver#19897]
### Description

`OracleDialectRules.QStringRule.doEvaluate` contains the following check:
https://github.com/dbeaver/dbeaver/blob/0642e8c736bb919041add49621b0cc4a819838bb/plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/sql/OracleDialectRules.java#L55

The problem is that `quoteStartChar` is a `char` and the minimum value of `char` is 0, so the `!= -1` check will always be true.

Maybe the simplest solution is to change `quoteStartChar` to type `int` and remove the `char` cast.

I am not planning to submit a pull request though because I am not familiar with this project.

### DBeaver Version

commit 0642e8c736bb919041add49621b0cc4a819838bb

**Comment by E1izabeth** [comment]
Have you meet some bug? What issue are you trying to solve?
