### ISSUE TITLE
Add information about current Project to the tab tooltip

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#19890]
Sometimes it's hard to understand what project you're in.
We want to add information about the current Project to this tooltip:

![image](https://user-images.githubusercontent.com/12581569/236514412-13b8732a-d52b-4490-9296-13969c56b3d1.png)

**Comment by TanishaAAgarwal4** [comment]
what exactly do you mean by information about current project? do you mean Folder information?

**Comment by E1izabeth** [comment]
By current project we mean the project where the connection was created. You can find Projects view in Navigator.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/fbd89786-d51c-4d94-a811-8bfe8ca23bf8)
