### ISSUE TITLE
Cannot open SQL files directly from Finder in DBeaver on Mac (Sierra 10.12.5)

### ISSUE THREAD

**Issue by iron0012** [dbeaver/dbeaver#1990]
Using Macs, just like with Windows, from the OS' file system navigator (i.e. Finder), one can normally right click on a file (e.g. SQL file) and choose "Open With" in order to open that file in a given application (like DBeaver). Alternatively, one can designate that all files of a certain filetype (e.g. SQL) always open with a given application (e.g. DBeaver). However, I cannot get either of these expected behaviors to work with DBeaver on my Mac. When right-clicking on an SQL file, choosing "open with" and selecting DBeaver, the file simply does not open. Similarly, after changing the file association of SQL files so that they are to be opened by DBeaver by default, and then double-clicking an SQL file in the Finder, the file does not open. It makes no difference if the DBeaver application is already open and running or not. 

As this method of opening SQL files seems much easier and more convenient than opening the files from within DBeaver (by selecting File -> Open File and then browsing to the desired SQL file, or by using the Project Explorer view), would it please be possible to allow SQL files to be opened in DBeaver directly from the Finder, using the methods described above, which are generally very typical, standard, and expected ways to open files? 

This is not a new issue, by the way, I have never been able to open SQL files directly from the Finder in DBeaver as described above. 

The best workaround that I've found, for now, seems to be to simply drag the file from the browser onto the open DBeaver application window, which does successfully result in the SQL file being opened in DBeaver. 

Thank you very much.

EDIT: 
I should add that, if the DBeaver application is NOT already open and running, then attempting to open an SQL file from the Finder in DBeaver WILL result in the DBeaver application being launched, but it will not actually open the SQL file itself within DBeaver.

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.

**Comment by BeggarsPaulSloan** [comment]
Still a problem. Behaviour still exactly as described in original bug report.

**Comment by sfc-gh-ptorres** [comment]
This is still a problem as of Jan 4th 2020. Exact same behaviour as with original post. In addition, associating the file type with Dbeaver as the Open App does not assign a Dbeaver icon to the .sql files in Finder.

**Comment by kkirpichnikov** [comment]
@BeggarsPaulSloan, @PhilippeTorres 
Open the Database Client Homes
<img width="430" alt="image" src="https://user-images.githubusercontent.com/13055750/185032308-7ee8bad8-9a7a-4dfe-9232-64bec774806b.png">

Press `cmd+shift+G` and now you should be able to specify the full path to your client
<img width="886" alt="image" src="https://user-images.githubusercontent.com/13055750/185032446-771fa299-6b1a-41ee-bc8f-ad84c155252d.png">

Put the path to your client, in my case it is `/opt/homebrew/opt/mysql-client/bin/mysql`

**Comment by xoelop** [comment]
Solution here: https://support.apple.com/en-gb/guide/mac-help/mh35597/mac


```
Permanently change the app used to open all files of a particular type
On your Mac, click the Finder icon  in the [Dock](https://support.apple.com/en-gb/guide/mac-help/aside/glosc3855c74/14.0/mac/14.0) to open a Finder window.

Select a file, then choose File > Get Info.

You can also Control-click the file, then choose Get Info.

In the Info window, click the arrow  next to “Open with.”

Click the pop-up menu, choose an app, then click Change All.

Note: Don’t click Change All if you only want the specific file you selected to open with that app.
```

**Comment by edschofield** [comment]
@xoelop : This is not a solution. Your link describes only how it _should_ work. But DBeaver is grayed out:

<img width="587" alt="image" src="https://github.com/dbeaver/dbeaver/assets/78314/10eb9328-edbd-4dd3-a657-0420c91f991f">

So @uslss , the bug is still outstanding; it is not possible to set DBeaver as the default application to open SQLite databases.

**Comment by xoelop** [comment]
Enable: All, done

**Comment by rahulpoptani** [comment]
Issue still persist as on Mar 9 2025. 
Using Dbeaver Community Edition Version 25.0.0.202503021833 on Ubuntu 24.04.1 LTS x86_64

**Comment by iron0012** [comment]
Yeah, this may have been fixed at one point, but it is now broken again. All of the same issues I described in the original post for this issue are now occurring once more! 

Please reopen the issue.

Dbeaver community Version 25.0.1.202503231807
MacOS Ventura 13.7.5
