### ISSUE TITLE
special characters like @#| don't works en sql editor 

### ISSUE THREAD

**Issue by mifisa** [dbeaver/dbeaver#19907]
### Description

Special characters like @#| don't works on sql editor since 23.0.2. Im working on a Mac Studio with apple keyboard (español).

### DBeaver Version

23.0.4

### Operating System

macOS Ventura 13.3.1

### Database and driver

Mysql

### Steps to reproduce

Try to write some mail in sql editor using @.

**Comment by E1izabeth** [comment]
Thank you for bug report. I can't reproduce your issue, at least on Windows, but probably, it's a macos-specific issue.
Could you clarify, what do you mean by "characters don't work"? No symbol appears when you type it or some other symbol appears? It would be extremely useful for us, if you could record a video showing the issue.

**Comment by mifisa** [comment]
Yes, characters don't appears when I type it in the sql editor, in other apps  they appears as always.
I have attached 2 videos, in the 2 videos I’m typing 123456789 with the “option" key that allows me to get the symbols that corresponds to the number key.
In the OK one is with de 23.01 version, I have the |@# symbols and with newer versions like 23.0.3 or 23.0.4 I cat get those symbols.

Hope this help.

Mike.

**Comment by E1izabeth** [comment]
Unfortunately, the videos or images you attached to email didn't come to github. It doesn't work with any attachments, if you answer by replying to a notification email. Could you come to github issue (https://github.com/dbeaver/dbeaver/issues/19907) and attach it directly in a comment?

**Comment by mifisa** [comment]
The videos.
https://user-images.githubusercontent.com/17954258/236899109-188daf35-5d4e-4256-9620-aa6627ac2069.mov


https://user-images.githubusercontent.com/17954258/236899112-b3047973-a1ab-491a-b9d4-7b82ec01910c.mov

**Comment by mifisa** [comment]
This is the OK video
https://user-images.githubusercontent.com/17954258/236899286-8a9aaabc-59c6-46a6-afa1-ae214e564890.mov

**Comment by E1izabeth** [comment]
Thank you.

**Comment by MashaKorax** [comment]
I reproduced the issue on  Mac. (English keyboard) 
macOS Monterey 

Thanks for your bug report!

**Comment by lagp** [comment]
I have the same problem with macOS Ventura 13.3.1 and DBeaver 23.0.4.

**Comment by Matvey16** [comment]
This is caused by newest ERD shortcuts that use option button on Mac, they override default Mac shortcuts so keyboard input gets blocked.

![Screenshot 2023-05-23 at 13 58 36](https://github.com/dbeaver/dbeaver/assets/82543000/2ace5856-36aa-4289-928f-d797cf828be6)

**Comment by mifisa** [comment]
Thanks, this works!
