### ISSUE TITLE
Update software exception

### ISSUE THREAD

**Issue by JasonZhang528** [dbeaver/dbeaver#19901]
### Description

When updating Dbeaver, the exception "Remote host terminated the handshake" occurs

### DBeaver Version

ex. Community Edition 23.0.3

### Operating System

Windows 10

**Comment by LonwoLonwo** [comment]
Hello @JasonZhang528 

How exactly you tried to update DBeaver? Please provide clear steps to reproduce the issue.

**Comment by JasonZhang528** [comment]
1. When I open the software, there was an upgrade pop-up.
2. I hit the upgrade button, and after a while this exception appears.
3. Sometimes it works, sometimes it doesn't.

**Comment by LonwoLonwo** [comment]
Your issue can be connected to the stability of your internet connection.
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. Please, let me know if the issue is still actual and provide log files.
