### ISSUE TITLE
bind issue to extract DDL from DB2 11.5, but only for one user

### ISSUE THREAD

**Issue by mahnya** [dbeaver/dbeaver#19905]
### Description

Hello.
I'm using dbeaver Version 23.0.3.202304240616 and I'm having an issue to extract the ddls of the tables of a database (I tried to extract the DDLs of views, and it works).

The error message I'm getting is this one:

Error running DDL generation
SQL Error [38553]: DB2 SQL Error: SQLCODE=-443, SQLSTATE=38553, SQLERRMC=*RATE_DDL;;SQL0001 Reason code or token: ......../sqllib/bnd/db2, DRIVER=4.11.77

But, I have a coworker who is not having the same issue when she tries to get the ddl using her notebook and the same Dbeaver version. We also have the same grant permissons on the db. It seems like it could be an issue with my dbeaver on my machine.

Is there a way to check it?

### DBeaver Version

CE 23.0.4.202305071722

### Operating System

windows 11

### Database and driver

Database: DB2 v11.5.7
Driver: com.ibm.db2.jcc.DB2Driver

### Steps to reproduce

1.Open the Database lateral toolbar
2. Choose any table to extract the DDL 
3. Go to 'Generate SQL'--> 'DDL' (all the other options generates the SQLs)

![dbeaver issue](https://user-images.githubusercontent.com/132909582/236831096-1814a7dd-93d0-4812-b313-b9b015f102a0.jpg)

Then I get the following error message:

Error running DDL generation
SQL Error [38553]: DB2 SQL Error: SQLCODE=-443, SQLSTATE=38553, SQLERRMC=*RATE_DDL;;SQL0001 Reason code or token: $HOME/sqllib/bnd/db2, DRIVER=4.11.77

**Comment by LonwoLonwo** [comment]
Hello @mahnya 

Could you please provide the full log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by mahnya** [comment]
Sure.
Here are the logs we have on Error Log view:

![DBeaver error log](https://user-images.githubusercontent.com/132909582/236959195-398ecfc9-7aa6-411e-990c-0cac12158305.jpg)


I'm also attaching the logs we have on .log and dbeaver-debug.log realted to this error.
[dbeaver_log.txt](https://github.com/dbeaver/dbeaver/files/11425863/dbeaver_log.txt)

[dbeaver_debug_log.txt](https://github.com/dbeaver/dbeaver/files/11425864/dbeaver_debug_log.txt)

This error only happens when I try to extract a Table's DDL. I get to extract the view's DDLs:

![image](https://user-images.githubusercontent.com/132909582/236959570-d41264aa-0326-4f3e-b00d-e691666db964.png)

**Comment by LonwoLonwo** [comment]
Does this issue occur only for one table DDL or all tables in all schemas?

Also, I can not see the original issue in your logs, only the following:
`Invalid operation: statement is closed.`

Please, reconnect to your database and provide log files again. Thanks.

**Comment by mahnya** [comment]
Hello.

The issue happens for all tables from all schemas.
Here are the logs (this time I tried to extract from more than 1 table):

![DBeaver error log2](https://github.com/dbeaver/dbeaver/assets/132909582/4aff28ba-42ac-42aa-8d67-bf1ccaa37587)

[dbeaver_debug_log2.txt](https://github.com/dbeaver/dbeaver/files/11436082/dbeaver_debug_log2.txt)
[dbeaver_log2.txt](https://github.com/dbeaver/dbeaver/files/11436084/dbeaver_log2.txt)

**Comment by LonwoLonwo** [comment]
I found the original answer to this issue:

https://github.com/dbeaver/dbeaver/issues/492#issuecomment-222968022

Please take a look at it.

If any questions left - feel free to ask.

**Comment by mahnya** [comment]
hello.

It doesn't seem to be the case, since I can get the ddls for views, which means I have the necessary permissions to run the db2look command.
Also, since my coworker gets to extract the ddls, and we have the same permissions, it also seems like grant is not the root cause of this.

**Comment by mahnya** [comment]
Hello!

FYI, I tried to run db2look on the server, and it worked, so it is not a grant issue.

**Comment by mahnya** [comment]
Hello! 
Any news about this ticket?

**Comment by ShadelessFox** [comment]
Hello @mahnya,

You and your coworker might have different driver versions or driver options set. It doesn't seem to be a DBeaver issue.
