### ISSUE TITLE
Toolbar shows wrong database when there are multiple in a connection

### ISSUE THREAD

**Issue by HendrikJan** [dbeaver/dbeaver#19918]
### Description

I have three databases in a connection. The connection is named `"Tapp - DOCKER"` and the databases are named `"test"`, `"fsw"` (this is the default database) and `"farmacie"`.
When I open a table in a non-default database (`"test"` or `"farmacie"`), the toolbar incorrectly tells me I am using the default (`"fsw"`) database.

__Layout of the connection:__

![image](https://user-images.githubusercontent.com/2218920/237023836-286233ca-0d5e-4f4f-b1d6-b51f7d6590f6.png)

If I open the table "farmacie.Courses", the toolbar shows "fsw.Courses".
If I open the table "test.Courses", the toolbar also shows "fsw.Courses".

__This is what the toolbar looks like when opening "farmacie.Courses" or "test.Courses":__
![image](https://user-images.githubusercontent.com/2218920/237023699-59ac702f-e7bf-4528-98f4-d573f69c5a91.png)

This problem only happens when opening tables. When opening a script, the correct database is shown.

__This is what the toolbar looks like when opening a script (this is correct)__
![image](https://user-images.githubusercontent.com/2218920/237024994-8499e563-5661-4adc-a2cf-92df7b737388.png)

The database name above the table is shown correctly.

__In this screenshot you can see both the correct database name above the table ("farmacie") and the incorrect name in the toolbar ("fsw")__
![Screenshot edited from 2023-05-09 09-28-35](https://user-images.githubusercontent.com/2218920/237025979-07a64a41-4cbd-4b21-8f1e-21e5d69a70b6.png)

### DBeaver Version

Community Edition Version 23.0.4.202305071722

### Operating System

Ubuntu 22.04.1 LTS

### Database and driver

Database name: Ver 15.1 Distrib 10.6.12-MariaDB, for debian-linux-gnu (x86_64)
Driver: org.mariadb.jdbc.Driver

### Steps to reproduce

1. Make a connection with multiple databases
2. Have a table with the same name in both databases (not sure if this is needed)
3. Open a table in the database that is not the default
4. See that the database name shown in the toolbar is the name of the default database, instead of the database where the table is from.

**Comment by LonwoLonwo** [comment]
Hello @HendrikJan 

![Screenshot edited from 2023-05-09 09-28-35](https://user-images.githubusercontent.com/2218920/237025979-07a64a41-4cbd-4b21-8f1e-21e5d69a70b6.png)

The top toolbar reminds you - that database is default now (**fsw** in your case).
And in the right corner of the table properties view, you can see the path to your table from the data source.

Then you are opening the new script - it will open as a new connection with a new default database. So it is expected to have a different database name in the toolbar.
This behavior is described here in [Preferences](https://github.com/dbeaver/dbeaver/wiki/Separate-Connections):

![2023-05-09 11_57_31-Preferences](https://user-images.githubusercontent.com/45152336/237047015-98819e59-2deb-49f5-9290-39b1a604dfcd.png)

Please let me know if you still have questions.

**Comment by HendrikJan** [comment]
I see now that I didn't understand the function of the display correctly.
Now that I know, I see that this is no bug.
Thanks for explaining!
