### ISSUE TITLE
Navigator issue with time-based queries filters

### ISSUE THREAD

**Issue by danhydrolix** [dbeaver/dbeaver#19912]
### Description

When using Clickhouse driver in combination with a constraint that all queries have a time-based filter, DBeaver generates an error in the General/Connections/Database hierarchical navigation.  Queries from the navigation panel can safely ignore the need for time-based filters.

### DBeaver Version

Community Edition 23.0.3

### Operating System

macOS Ventura 13

### Database and driver

Hydrolix v3.36
Clickhouse ClickHouse client version 22.7.2.1.

**Comment by LonwoLonwo** [comment]
Hello @danhydrolix 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by LonwoLonwo** [comment]
Also, clear steps for reproducing your issue will be helpful.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.
