### ISSUE TITLE
Exception attempting to connect to Amazon Athena using DBeaver

### ISSUE THREAD

**Issue by dilson-oliveira** [dbeaver/dbeaver#19924]
### Description

I'm trying to connect to Amazon Athena using DBeaver with JDBC driver com.simba.athena.jdbc.Driver (AthenaJDBC42-2.0.36.1000.jar) and I'm getting the following error message:

[Simba][AthenaJDBC](100131) An error has been thrown from the AWS SDK client. Unable to execute HTTP request: Remote host terminated the handshake [Execution ID not available]
  Unable to execute HTTP request: Remote host terminated the handshake
  Unable to execute HTTP request: Remote host terminated the handshake
    Remote host terminated the handshake
    Remote host terminated the handshake
      SSL peer shut down incorrectly
      SSL peer shut down incorrectly

### DBeaver Version

Community Edition 23.0.4

### Operating System

Ubuntu 22.04.1

### Database and driver

1. Database name and version: Amazon Athena 2 and 3
Connection parameters:
Region: region-name
S3 location: a bucket for athena query results

2. Driver name and version: AthenaJDBC42-2.0.36.1000
Driver properties:
AwsCredentialsProviderArguments = mfa-profile-name
AwsCredentialsProviderClass = com.simba.athena.amazonaws.auth.profile.ProfileCredentialsProvider
Workgroup = primary

config and credentials files are in default path ~/.aws

### Steps to reproduce

With the configuration described before I'm pushin the botton "Test Connection" and after some minutes I'm receiving the message:

[Simba][AthenaJDBC](100131) An error has been thrown from the AWS SDK client. Unable to execute HTTP request: Remote host terminated the handshake [Execution ID not available]
  Unable to execute HTTP request: Remote host terminated the handshake
  Unable to execute HTTP request: Remote host terminated the handshake
    Remote host terminated the handshake
    Remote host terminated the handshake
      SSL peer shut down incorrectly
      SSL peer shut down incorrectly

### Additional context

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/11436449/dbeaver-debug.log)

**Comment by LonwoLonwo** [comment]
Hello @dilson-oliveira 

It can be connected with the [Java version](https://stackoverflow.com/questions/21245796/javax-net-ssl-sslhandshakeexception-remote-host-closed-connection-during-handsh).

Do you use included in DBeaver Java or your own?

**Comment by dilson-oliveira** [comment]
Hi @LonwoLonwo 
Yes, I'm using the DBeaver Java in the DBeaver "jre" installation folder.

**Comment by serge-rider** [comment]
It looks like connectivity issue.

@dilson-oliveira are you behind some corporate firewall? If so then you may need to configure proxy settings.

**Comment by dilson-oliveira** [comment]
Hi @serge-rider 
There is no corporate firewall blocking the connection.

**Comment by LonwoLonwo** [comment]
Hello @dilson-oliveira 

Could you please try to add the "-Djavax.net.debug=ssl" parameter in your .ini file? And resend the log after that.
Additionally, please provide info about your configuration - how do you configure SSL?

**Comment by dilson-oliveira** [comment]
Hi @LonwoLonwo 
Resending the log... 
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/11725573/dbeaver-debug.log)
... And, I did not configure SSL
Thank you for your attention! :)

**Comment by LonwoLonwo** [comment]
As I can see in the Internet, 

"Couldn't kickstart handshaking" (from you logs) happens because of the:
"This issue happens because SSL certificate is not added into java truststore certificate."

or maybe disabling/enabling of this setting can help:

![2023-06-13 10_36_04-DBeaver Ultimate 23 1 0 - _TEST_DB 1_ Script-103](https://github.com/dbeaver/dbeaver/assets/45152336/4f7fc6f5-a6bd-422e-aa72-f82bb5c8aa1b)

**Comment by dilson-oliveira** [comment]
I don't have this option in the ubuntu version...
![image](https://github.com/dbeaver/dbeaver/assets/53913507/5f9b7d4e-ddae-4a7b-9178-123854ab70ec)

**Comment by LonwoLonwo** [comment]
Oh, yes, sorry, this is the Windows setting. I forgot about it.

**Comment by dilson-oliveira** [comment]
Did you notice an exception message in the beginning of dbeaver-debug.log ? I get this message every time i start the DBeaver

> Start Team Support Core [org.eclipse.team.core 3.9.700.v20221201-0946]
2023-06-14 11:22:41.267 - java.lang.NullPointerException: Cannot invoke "java.net.NetworkInterface.getHardwareAddress()" because "ni" is null

**Comment by LonwoLonwo** [comment]
This is another issue. Do you see it in the last DBeaver version? We probably fixed it already in the previous release.

**Comment by dilson-oliveira** [comment]
Yes, I'm getting this issue in the last version... DBeaver 23.1.0

**Comment by dilson-oliveira** [comment]
Hi @LonwoLonwo This issue is related to "Network and/or Web Threat Protection" configuration on my antivirus software. Everything works fine when I stop the antivirus manually.
