### ISSUE TITLE
ms sql server Can't create driver instance

### ISSUE THREAD

**Issue by hhtcyounger** [dbeaver/dbeaver#19939]
### Description

Can't create driver instance
  Error creating driver 'MS SQL Server / SQL Server' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
  Error creating driver 'MS SQL Server / SQL Server' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
    com.microsoft.sqlserver.jdbc.SQLServerDriver
    com.microsoft.sqlserver.jdbc.SQLServerDriver

![image](https://github.com/dbeaver/dbeaver/assets/23032343/d0068eb1-833c-43c1-ab04-6067ae0c9676)

### DBeaver Version

版本: 23.0.4.202305071722

### Operating System

Windows 11 专业版 22621.1555

### Database and driver

ms sqlserver 

![image](https://github.com/dbeaver/dbeaver/assets/23032343/f28f7e44-c0fb-4041-a22b-681291622e3d)

### Steps to reproduce

尝试连接ms sqlserver数据库

**Comment by ShadelessFox** [comment]
Hello @hhtcyounger,

Does downloading drivers by clicking on the button of the same name solve the issue?

![image](https://github.com/dbeaver/dbeaver/assets/35821147/125659d4-dff8-453f-8fd4-0f1770bfa821)

**Comment by HaotianWang86** [comment]
Any updates? I faced the same issue. It appears a common issue for MS SQL server

**Comment by E1izabeth** [comment]
@HaotianWang86 you can help us by answering the question asked, as we can't reproduce it.

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still actual for you - feel free to reopen it.
