### ISSUE TITLE
Unable to find the equivalent of exec in sql 

### ISSUE THREAD

**Issue by harleen65** [dbeaver/dbeaver#19945]
### Description

I am creating some sql statements dynamically and exceuting them.Unable to find the command to execute the sql staements written in a parameter.I have only GUI access

### DBeaver Version

NA

**Comment by E1izabeth** [comment]
It's not clear what are you trying to do, but maybe parameters and variables might help you
https://github.com/dbeaver/dbeaver/wiki/Client-Side-Scripting
https://github.com/dbeaver/dbeaver/wiki/SQL-Execution#dynamic-parameter-bindings
https://github.com/dbeaver/dbeaver/wiki/Variables-panel

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.
