### ISSUE TITLE
Reset all settings of all tables for a specific connection

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#19949]
You can now change the view and format of the data tables. We want to add the ability to reset all of these settings for all tables for specific connections. 

We need to figure out where and how to store it all.

**Comment by serge-rider** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/6398845/0991af3e-e8d8-476b-965b-fe424d760c1c)

![image](https://github.com/dbeaver/dbeaver/assets/6398845/284b0888-b377-42f9-b7cb-9059b4f05e13)
