### ISSUE TITLE
"Disable order by" on column header menu not working correctly

### ISSUE THREAD

**Issue by jmadren** [dbeaver/dbeaver#19951]
### Description

In the data or result viewer, you can sort the list by clicking on the dropdown arrow in a column header and choosing an order. Then an additional option will appear on that column's menu to "Disable order by". But it only works if the column is currently sorted in descending order. If it is currently in ascending order, selecting "Disable order by" changes the sort to descending order. Then I can select "Disable order by" again to truly remove the sorting.

### DBeaver Version

Community 23.0.4.202305071722

### Operating System

macOS 12.6.5

### Database and driver

Does it on SQLite and PostgreSQL. Don't think it has anything to do with the database.

**Comment by E1izabeth** [comment]
Thank you for bug report.
