### ISSUE TITLE
[PostgreSQL] Doubling tables in database navigator if there are multiple generated columns

### ISSUE THREAD

**Issue by Nick-Nal** [dbeaver/dbeaver#19952]
### Description

Greetings

Just found weird visual bug in database navigator - it shows N copies of the table that has N generated columns (GENERATED ALWAYS / BY DEFAULT AS IDENTITY / *expression* STORED

These copies have the same OID and doesn't appear in pg_class, so it's only UI problem.

Minimal reproducible example is below. Tested it on latest DBeaver CE on Windows and Ubuntu, same results.
As far as i can tell, it didin't generates table copies like that in older versions.

Here are some screens from that example

![image](https://github.com/dbeaver/dbeaver/assets/92499666/e0301a7b-b73a-4587-9b08-c49559ba94be)

![image](https://github.com/dbeaver/dbeaver/assets/92499666/11f84dfa-04e1-459a-8f8d-b7aa4224e84d)

![image](https://github.com/dbeaver/dbeaver/assets/92499666/d13e5b6d-2525-43ba-961f-7f9c5fc03b84)

![image](https://github.com/dbeaver/dbeaver/assets/92499666/21652188-a34e-407b-a4ae-ce61aaf23050)

### DBeaver Version

Community Edition 23.0.4

### Operating System

Windows 10 Pro 21H2 / Ubuntu 22.04

### Database and driver

PostgreSQL 15.3
PostgreSQL JDBC 42.6.0

### Steps to reproduce

```
create schema test_schema;

create table test_schema.test_table 
(
	id int generated always as identity,
	gen int generated always as (5 * id) stored
);
```

**Comment by LonwoLonwo** [comment]
Ok, I can reproduce it on PostgreSQL 15.
Thanks for the bug report!
