### ISSUE TITLE
Secret cannot be null error even though it's optional when logging in

### ISSUE THREAD

**Issue by kamransh** [dbeaver/dbeaver#19966]
### Description

We get client secret cannot be null popup when logging in to our Database via JDBC event though it's optional. 23.0.3 version works fine.

### DBeaver Version

23.0.4

### Operating System

macOS 13.3.1

### Database and driver

Salesforce CDP - JDBC

### Steps to reproduce

1. connect to Salesforce CDP using the username and password only.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by LonwoLonwo** [comment]
Hello @kamransh 

Could you please check the previous Salesforce CDP driver version?

You can download it here: https://github.com/forcedotcom/Salesforce-CDP-jdbc/releases/download/release_2021.12A/Salesforce-CDP-jdbc-1.11.0.jar

And change the current jar file to the new one:

![2023-05-17 12_15_09-Window](https://github.com/dbeaver/dbeaver/assets/45152336/42afe0c7-27d4-4575-9080-f84a97923dd7)

**Comment by kamransh** [comment]
Hi @LonwoLonwo 
Yes, reverting back to the old version of the driver fixed it.  Thanks. 
Will raise it with Salesforce.
