### ISSUE TITLE
cannot save connection strings in 23.0.4 on Ubuntu 18.04

### ISSUE THREAD

**Issue by cls1chuck** [dbeaver/dbeaver#19961]
### Description

I am trying to create a connection to SQL Server.  Drivers have been loaded (com.icrosoft.sqlserver.jdbc.SQLServerDriver), all the defaults.  In fact yesterday I was able to connect to my database (which is running in a docker container).  This morning I open DBeaver and the first two buttons (New Connection and Connect) are greyed out (no saved connection).  I select New Database Connection, select SQL Server, accepting following defaults:
Host:localhost
Port: 1433 
Database/Schema: master
Authentication: SQL Server
I then provide the username (sa) and the password.

The 'Next' button is greyed out, there is only a 'Finish'.  When I click that I am back to the main display; I'm not connected to anything, the connect button is greyed out, as if I never did anything.  It's as if the connection isn't saved.  Yet if I go under Database/Driver Manager, I see 13 entries there for my failed attempts; if I try to delete them (seems to be all or none), I get an error that I cannot because it's in use by the following data sources.  Yet I see no place to list/connect to my data sources.

I *can* connect via sqlcmd, so I know it's not an issue with my SQL Server container.

I'm sure I'm missing something, and I'm relatively new to DBeaver (esp. the Linux version).  Thanks in advance. 

### DBeaver Version

CE 23.0.4

### Operating System

Ubuntu 18.04

### Database and driver

Database: SQL Server 2019
Driver: com.microsoft.sqlserver.jdbc.SQLServerDriver

### Steps to reproduce

1. Open DBeaver
2. Connection buttons (the first two) are greyed out, so I click File/New
3. Select Database connection, select SQL Server
4. Fill out connection-specific info and click Finish

**Comment by E1izabeth** [comment]
Have you updated DBeaver, right before you meet this issue?

**Comment by cls1chuck** [comment]
No I did not, I had installed a day or two before that for the first time.  This was the first time I tried to use it since then.

**Comment by E1izabeth** [comment]
What version did you use before? The previous minor one 23.0.3 or older?

**Comment by E1izabeth** [comment]
I tried to reproduce an issue.
As far as I see, `Next` button is greyed as there is no next page. You correctly press `Finish` button.
After creating connection a new item appears in Database Navigator, but the focus is not on this item. Could you try to click on the created connection in Database Navigator or directly press Connect from the context menu like on my picture?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/0d89cfb5-908e-45b0-b341-1936c68ee7b3)

**Comment by cls1chuck** [comment]
My DBeaver screen looks nothing like yours, unfortunately (I'm still in the default layout from the install).  I am not able to find a Database Navigator.
This is the main screen I have:
![image](https://github.com/dbeaver/dbeaver/assets/133413141/552bdde1-a3a4-4b21-b248-4ebbc553f3ea)

the buttons in the red box are greyed out/disabled on my system.

I missed your other question.  There was no 'previous version'.  I installed it last week, ran it immediately upon install, and was able to connect. The next day (or perhaps a day after that), I ran it again, and got the screen I have above.

**Comment by E1izabeth** [comment]
Could you try resetting UI settings? You can find instructions here https://dbeaver.com/docs/wiki/Reset-UI-settings/

**Comment by cls1chuck** [comment]
E1izabeth,
Many thanks - resetting the UI resolved the issue!  This took me to a default view of Database Navigator, with my connections (I had created several in my attempts, apparently).  I deleted the ones not needed, and am now able to connect to my database!
