### ISSUE TITLE
Unable to Login to PostgreSQL DB from Windows, Getting error: "No LoginModules configured for pgjdbc"

### ISSUE THREAD

**Issue by jbruneFei** [dbeaver/dbeaver#19971]
### Description

I'm trying to log into a Postgres server.  I am able to connect to the server via PgAdmin, so I know my account is correct.  In DBeaver I selected Authentication 'Database Native'.  When I try to connect I get the error: _GSS Authentication failed
No LoginModules configured for pgjdbc_.

Thanks in advance.

### DBeaver Version

Community Edition Version 23.0.4.202305071722

### Operating System

Windows 11

### Database and driver

1. Database: PostgreSQL 12.12 on x86_64-pc-linux-gnu, compiled by x86_64-pc-linux-gnu-gcc (GCC) 7.4.0, 64-bit
2. Driver: PostgreSQL
![image](https://github.com/dbeaver/dbeaver/assets/40606750/f371c11a-d683-4b5e-8464-17a20fdd4100)

### Steps to reproduce

1. I try to connect to the database
2. I get this error
![image](https://github.com/dbeaver/dbeaver/assets/40606750/8bb6f65a-d87e-491a-86fb-75df78122201)

**Comment by LonwoLonwo** [comment]
Hello @jbruneFei 

Did you use Kerberos authentication? Maybe this discussion will be helpful for you: https://github.com/dbeaver/dbeaver/issues/1737

**Comment by jbruneFei** [comment]
Thank you.  I had viewed this but thought it did not apply since I am able to connect to my Postgres with a different application.

**Comment by LonwoLonwo** [comment]
Still. I have questions.
Did you use Kerberos authentication?
Do you use included in DBeaver JAVA or your own?

**Comment by jbruneFei** [comment]
Yes, I'm pretty sure it uses Kerberos.  

_Do you use included in DBeaver JAVA or your own?_
I don't understand.  I'm on Windows and I don't use Java at all.

**Comment by LonwoLonwo** [comment]
Did you uncheck the "Include JAVA" setting during installation?

![2023-05-05 08_40_06-DBeaver Community 23 0 2 (x86_64) Setup](https://github.com/dbeaver/dbeaver/assets/45152336/62bc1a1b-1084-48c5-b2c3-3693797ddc05)

**Comment by jbruneFei** [comment]
To be honest, I'm not sure.  I see this as "Installed Software". 
![image](https://github.com/dbeaver/dbeaver/assets/40606750/be94fdd8-209a-41a9-8ef4-3d4fdf3660f4)
If I had also selected Java would it appear there?  I can try uninstalling and reinstalling and this time I can make sure to check "Include Java".  Would you suggest that?

Thank you so much for your support, by the way!

**Comment by E1izabeth** [comment]
It wouldn't appear there.
Yes, we suggest to try reinstalling.

**Comment by jbruneFei** [comment]
I have reinstalled and I made sure the "Include Java" was checked.  Odd thing, there is a different Postgres DB I can get to, but not this one.  From pgAdmin I can get to both servers.

**Comment by hrimthrusa** [comment]
Please see if your issue reproduces in DBeaver Enterprise Edition. You may get your free of charge 14-day trial period [here](
https://dbeaver.com/trial/).

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
