### ISSUE TITLE
Grey color in Dark theme is not clearly seen

### ISSUE THREAD

**Issue by chongshanjunlin** [dbeaver/dbeaver#19972]
### Description

现在列描述变成了淡蓝色（淡灰色），黑色主题，看不清列描述写的什么，为什么要改成这个颜色？原来的挺好的啊

### DBeaver Version

23.0.4.202305071722

### Operating System

Ventura 13.2.1 (22D68)

### Database and driver

sql server

### Additional context

<img width="255" alt="WeChat8e946ab11e0480f842e568d500153c08" src="https://github.com/dbeaver/dbeaver/assets/133725469/e31e4939-64a8-4411-9fc6-8beaed2afdb6">

**Comment by LonwoLonwo** [comment]
Please translate your ticket into the English language.

**Comment by E1izabeth** [comment]
You could try Darkest Dark theme extension https://dbeaver.com/docs/wiki/Eclipse-extensions/

**Comment by chongshanjunlin** [comment]
> 请将您的门票翻译成英语。

The macOS system I use, Night Mode, which is the darkest theme, but the column description (column notes) of the new version of dberver can't be seen clearly, and the color is very light. I don't know where to set the column description to be the previous white.

**Comment by E1izabeth** [comment]
There is no such setting in embedded DBeaver theme settings.

However, you could try Darkest Dark theme extension, as I suggested.

Thank you for your issue reporting.

**Comment by DavidHJong** [comment]
> <img alt="WeChat8e946ab11e0480f842e568d500153c08" width="255" src="https://private-user-images.githubusercontent.com/133725469/238509917-e31e4939-64a8-4411-9fc6-8beaed2afdb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTg2NDIsIm5iZiI6MTcyMTcxODM0MiwicGF0aCI6Ii8xMzM3MjU0NjkvMjM4NTA5OTE3LWUzMWU0OTM5LTY0YTgtNDQxMS05ZmM2LThiZWFlZDJhZmRiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwNzA1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTUzNmJlYWQ2YjI5M2JlNmI4YTRkMmNhZGI2YjRiOGM1ODg3ZjE3MWFlODM5ODZhZDc5ZGVlZTRmMzEyMjZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1vG39LvuKk3fcgPuTSPoxxHmo6Zf82Q6sEzZ-NZ_rdU">

The original screenshot doesn't show the severity of this bug, as we can see the comment anyway. The problem escalates when you highlight a column. Then the nightmare comes. This is what you see when highlighting a column. Even with this level of zoom, you can almost see nothing. 

![image](https://github.com/user-attachments/assets/a64fc30e-19dd-43e3-9cc2-c0f3782e9d1e)
