### ISSUE TITLE
TE, CE: Notifications don't appear for scripts, Datasets

### ISSUE THREAD

**Issue by TatyanaSsau** [dbeaver/dbeaver#19974]
I Notifications **don’t appear** for scripts or **appear incorrectly in DBeaver** node when a user is in CloudBeaver node:
1. create a script without a connection - no notifications appear 
2. create a script associated with a connection - 3 notifications appear 
3.  rename a script - no notifications appear+2 scripts are displayed in the project tree
4. associate a saved script with a conection - 3 notifications appear and the script disappears (e.g. associate a script and then relogin in DBeaver)
5. remove connection associatiation from a script - 3 notifications appear (the change is applied)
6. dnd to a folder - no notifications appear
7. create a folder  - no notifications appear
8.  rename a folder  - no notifications appear and two folders with old is new names are displayed in the tree (fixed by refresh/relogin) 

I Notifications **don’t appear for scripts in CloudBeaver** node when a user  in DBeaver node makes any changes except
1. associating a script without a connection with a connection
2. making changes in a script content using following steps
- run two DBeaver and CloudBeaver nodes 
- create an empty script without a connection association in CloudBeaver node
- open this script in the DBeaver node and write smth in it

**note:** if you reopen the script, notifications will stop to appear

**Comment by arhayka** [comment]
This issue will be closed in another project.
