### ISSUE TITLE
column edit

### ISSUE THREAD

**Issue by SV-Guo-Liliang** [dbeaver/dbeaver#19973]
![image](https://github.com/dbeaver/dbeaver/assets/125421504/ebb5cb92-a656-4c3a-962b-05f930cecca9)

Is there a way to modify column`s properties? to me ,only name can  be modified

**Comment by LonwoLonwo** [comment]
Hello @liliang-guo 

What DBeaver version do you use?
What database do you use?

**Comment by SV-Guo-Liliang** [comment]
DBeaver version: 23.0.0.202303040621
Database : sqlite
![image](https://github.com/dbeaver/dbeaver/assets/125421504/416637bc-9bbb-45bc-8a1f-d2e17ec0db0b)
![image](https://github.com/dbeaver/dbeaver/assets/125421504/d0dbb4a6-8c80-42af-abc7-3d0fbfb1f0d6)
![image](https://github.com/dbeaver/dbeaver/assets/125421504/3e17515b-a7f9-4f34-8bc3-6a07ffde6ca7)

**Comment by LonwoLonwo** [comment]
Unfortunately, SQLite doesn't support column altering. Only with the whole table recreation.  
Probably it is better to create a new table via DBeaver UI and use data migration after that: https://github.com/dbeaver/dbeaver/wiki/Data-migration
