### ISSUE TITLE
Read-only: No corresponding table column

### ISSUE THREAD

**Issue by MrLuke1110** [dbeaver/dbeaver#19975]
### Description

SELECT two table use left join can't show column description in header

![image](https://github.com/dbeaver/dbeaver/assets/66194793/06eb4e0c-64f6-4cce-8307-1db01694aa48)

### DBeaver Version

Community Edition 23.0.4

### Operating System

Windows 10 22H2

### Database and driver

Database name and version: DB2 for ibm i V7R2M0
Driver name and version: jt400 11.2

### Steps to reproduce

input select
execute sql query

**Comment by LonwoLonwo** [comment]
Hello @MrLuke1110 

Please provide the DDL of your tables and the whole query with JOIN for testing.

**Comment by MrLuke1110** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/66194793/c3f67a05-eab2-4543-9844-3cbcd9743345)
![image](https://github.com/dbeaver/dbeaver/assets/66194793/e3b81067-22e7-48f7-8fe4-1b1d1a1a868f)
![image](https://github.com/dbeaver/dbeaver/assets/66194793/7a8fe285-c72f-4b4f-be3d-fa24ac6c2412)
![image](https://github.com/dbeaver/dbeaver/assets/66194793/b617b9ac-95db-4e91-97ed-ce4fcf85a187)
![image](https://github.com/dbeaver/dbeaver/assets/66194793/6ac489d1-4f07-4d99-8996-35888611b8ad)
![image](https://github.com/dbeaver/dbeaver/assets/66194793/4584c119-c45d-4a57-b9bd-68b4bdaba105)

**Comment by LonwoLonwo** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide log files.
