### ISSUE TITLE
Code in stored procedures and functions displays alignment lines and can be collapsed for easier reading

### ISSUE THREAD

**Issue by wmdeepsea** [dbeaver/dbeaver#19987]
Similar to toad, when you open a stored procedure to view the source code inside, you can easily see where the method starts and ends, and you can fold the code fragments in it, which is very suitable for developers to read and write programs

**Comment by LonwoLonwo** [comment]
Hello @wmdeepsea 

We already have foldings and line numbers for SQL declarations.
So, please provide more details and examples for your idea.

![2023-05-17 11_14_44-Window](https://github.com/dbeaver/dbeaver/assets/45152336/63c1ed1b-7a15-4fab-9711-c20c3360c67b)

![2023-05-17 11_16_52-Window](https://github.com/dbeaver/dbeaver/assets/45152336/20b74d90-65e0-404a-855d-a33cd5bf5eec)

**Comment by wmdeepsea** [comment]
Thank you for your response, Can the code in the stored procedure and function highlight the alignment line, like if endif； for loop endloop；begin end； code block alignment

**Comment by E1izabeth** [comment]
There is no such feature yet. But we have already got requests about that #13638 #17240 #11830

Closing this issue as a duplicate. Please follow mentioned issues for further information about feature implementation process.
