### ISSUE TITLE
Autocomplete improvement

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#19997]
We should improve Autocomplete.
Now for some reason, it works in the second case ( i.film_id ), but doesn't work in the first case (f.film_id ) (see attachment)

https://github.com/dbeaver/dbeaver/assets/84867187/755ff083-5944-4126-9909-55e54fb06150

```
SELECT  i.inventory_id ,
a2.address_id
FROM 
 public.album a1,
 public.address a2,
 public.actor a3,
 public.accounts a4,
 public.film f 
INNER JOIN public.inventory i on f.film_id = i.film_id 
 WHERE  a4.id =1
```

**Comment by E1izabeth** [comment]
Can't reproduce on DBeaver 23.0.5
