### ISSUE TITLE
Scrambled labels on tabs in GUI v2

### ISSUE THREAD

**Issue by BensHamou** [dbeaver/dbeaver#19993]
### Description

Good morning all,

According to the research i did, i found that the problem i am facing has already been discussed [#6339](https://github.com/dbeaver/dbeaver/issues/6339) and was marked as closed. However, the problem still persists (kinda).

The light theme is working fine as mentioned in that thread, but dark theme is not, the labels still appear scrambled. I tested the same version of DBeaver in another PC (Windows 10), and dark mode worked just fine, which indicated it's a problem of compatibility between the OS and this version of Dbeaver (i should also mention that i tested v23.0.4 and same result).

The images below show how the labels appear in light/dark mode (Classic or Theme Disabled/Dark theme)

LIGHT  =>

![image](https://github.com/dbeaver/dbeaver/assets/34404031/3bac613b-4b1a-417b-a69b-725c47acbb1e)

Wtih:
![image](https://github.com/dbeaver/dbeaver/assets/34404031/6b38ec8f-4494-4458-923a-b6b4786cbb08)

It also works with:
![image](https://github.com/dbeaver/dbeaver/assets/34404031/6aa031fd-a149-4ea1-aeb4-a595407a6a6e)

DARK =>

![image](https://github.com/dbeaver/dbeaver/assets/34404031/74aac43e-fdb6-4028-8475-f0255c87bc49)

With: 
![image](https://github.com/dbeaver/dbeaver/assets/34404031/d02f54f2-1e7b-4013-be7e-0999b899924c)

My question is if there's a fix to this or is working with light theme an obligation? 

### DBeaver Version

Community Edition 21.1.1

### Operating System

Windows 11 Pro

### Database and driver

PostgreSQL

### Steps to reproduce

The installation was straight forward, everything was as default

**Comment by E1izabeth** [comment]
Have you tried using [Darkest Dark theme](https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle) extension?
https://dbeaver.com/docs/wiki/Eclipse-extensions/

**Comment by E1izabeth** [comment]
Also I can't reproduce it on the latest DBeaver 23.0.4

**Comment by E1izabeth** [comment]
It looks like some font issue, probably there is no suitable font on your system. We unified font settings recently, so updating to the latest version might solve your issue.

**Comment by BensHamou** [comment]
@E1izabeth thank you for your return.  

I didn't try the extension you mentioned when I uploaded this. I only did after reading your comment, thank you.

The problem still persists: 

![image](https://github.com/dbeaver/dbeaver/assets/34404031/940278aa-95de-482f-b9ca-f037e142874e)

Is there a specific configuration i should do to make it work?


As for not being able to reproduce, what should I provide for you in order to be able to do it? 


In your last comment you mentioned - "updating to the latest version might solve your issue". Do you mean the latest version of DBeaver? I have it in a different PC and it's not working, i have the latest version as far as I know (23.0.4), i also tried the extension and still the same.

In case you mean the latest version of the OS, then that is covered as well. In case of something else then please inform me.

**Comment by E1izabeth** [comment]
Thank you for response.
I meant the latest version of DBeaver.

Could you check which font is chosen for you in the font preferences? The preference is named Main font in the latest DBeaver version and [Part title font](https://github.com/dbeaver/dbeaver/issues/6339#issuecomment-622220141) in an old DBeaver version.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/9be78eeb-90c9-45d7-835d-24fc73309bfc)

**Comment by BensHamou** [comment]
Hello again, 

Yes, here's the result

![image](https://github.com/dbeaver/dbeaver/assets/34404031/a914b50c-4cf4-4ceb-a661-2b2b84a2c880)

**Comment by E1izabeth** [comment]
Could you try changing this font to some other by pressing Edit button?

**Comment by BensHamou** [comment]
It worked!! 

Thank you so much for your help and time. 

Should I add this fix in the other issue?

Thank you once again!

**Comment by E1izabeth** [comment]
You could left a comment under the closed issue, maybe your case will help someone else :)

**Comment by BensHamou** [comment]
Sir yes sir!
