### ISSUE TITLE
Suggestion: Add data syncing support between systems

### ISSUE THREAD

**Issue by xantari** [dbeaver/dbeaver#1999]
I have a suggested feature for the enterprise edition.

Add a data syncing tool like SqlWorkbench has.

Right now we use that tool for it's syncing capabilities to bring our development database in sync with our production database or to selectively sync some records and not others.

Here is the screenshot of how it works:

![image](https://user-images.githubusercontent.com/6610039/29125545-a74efb1c-7ce1-11e7-98c4-98430eda2c50.png)

SqlWorkbench is open source java program, so take a peak :-)

**Comment by serge-rider** [comment]
Yes, it is one of planned features (although I can't find it in FR list so this will be the one)

**Comment by uslss** [comment]
The schema compare feature is already available in EE

**Comment by xantari** [comment]
@uslss does schema compare only do table schemas or does it also do data in the table and synchronize the data rows?

**Comment by xantari** [comment]
@uslss @serge-rider  Hi, can you please re-check this work item that was closed. You said "schema compare feature is already available in EE", but this work item is talking about data comparisons, not schema comparisons.

I think this was closed in error.
