### ISSUE TITLE
theme and sql edit text color is not match , hard to see

### ISSUE THREAD

**Issue by youngqqcn** [dbeaver/dbeaver#20000]
The default color of sql edit is very hard to see. 

 Dark theme, Light theme, and High Contrast theme, the colors of theme and text in the edit are very not match 

version: 23.0.4.202305071722
system: Ubuntu 23.04
system theme: black
![image](https://github.com/dbeaver/dbeaver/assets/30211020/4f53201f-c062-4a5c-b0a2-88bc34fabec6)

Dbeaver Light theme, on my pc:
![image](https://github.com/dbeaver/dbeaver/assets/30211020/f1c9b38d-39a6-4872-9e74-334fc990e535)

![image](https://github.com/dbeaver/dbeaver/assets/30211020/954ca932-ebb7-4df3-affe-16874c13f6d8)

---
Classic theme 

![XClaM1tIdE](https://github.com/dbeaver/dbeaver/assets/30211020/3834f1f3-662b-40c3-a2fc-8aaffcdec71c)

----

Dark theme is better color match than others

![image](https://github.com/dbeaver/dbeaver/assets/30211020/bcb0c405-a5e5-4265-bb30-3ea09ffc2096)

----

High contrast theme

![image](https://github.com/dbeaver/dbeaver/assets/30211020/fd94600c-eb4b-4500-8f74-57c9f0e611da)

**Comment by AsparagusEduardo** [comment]
20000!

**Comment by hrimthrusa** [comment]
You may adjust the colors of your font and background the way you want them. 


To change the font color please follow Window (main toolbar) -> Preferences -> User Interface -> Appearance -> Colors and Fonts -> SQL Editor -> highlight the SQL text foreground -> Edit. Here you may pick a suitable color and apply it.

To change the background color please follow  Window (main toolbar) -> Preferences -> Editors -> Text Editors -> highlight Background color in the Appearance color options list, choose a comfortable color and apply it.

**Comment by youngqqcn** [comment]
thanks



---Original---
From: ***@***.***&gt;
Date: Tue, May 23, 2023 16:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dbeaver/dbeaver] theme and sql edit text color is not match ,hard to see (Issue #20000)




 
You may adjust the colors of your font and background the way you want them.
 
To change the font color please follow Window (main toolbar) -&gt; Preferences -&gt; User Interface -&gt; Appearance -&gt; Colors and Fonts -&gt; SQL Editor -&gt; highlight the SQL text foreground -&gt; Edit. Here you may pick a suitable color and apply it.
 
To change the background color please follow  Window (main toolbar) -&gt; Preferences -&gt; Editors -&gt; Text Editors -&gt; highlight Background color in the Appearance color options list, choose a comfortable color and apply it.

**Comment by E1izabeth** [comment]
@youngqqcn does proposed solution solve your issue?

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still actual for you - feel free to reopen it.
