### ISSUE TITLE
X-Pack/SQL does not seem to be available on the Elasticsearch node

### ISSUE THREAD

**Issue by kuzuozhou** [dbeaver/dbeaver#20001]
### Description

正常连接后，打开表时报错：
SQL 错误 [bad_server]: X-Pack/SQL does not seem to be available on the Elasticsearch node using the access path '<host-ip>:<port>'. Please verify X-Pack is installed and SQL enabled. Alternatively, check if any proxy is interfering the communication to Elasticsearch
  X-Pack/SQL does not seem to be available on the Elasticsearch node using the access path '<host-ip>:<port>'. Please verify X-Pack is installed and SQL enabled. Alternatively, check if any proxy is interfering the communication to Elasticsearch
  X-Pack/SQL does not seem to be available on the Elasticsearch node using the access path '<host-ip>:<port>'. Please verify X-Pack is installed and SQL enabled. Alternatively, check if any proxy is interfering the communication to Elasticsearch

_UPD: Edited host and port in the description to hide them__

### DBeaver Version

21.3.2，23.0.4

### Operating System

windows10 64

### Database and driver

1、elasticsearch 7.10.2
2、x-pack-sql-jdbc:7.10.2

**Comment by E1izabeth** [comment]
Thank you for bug report.

Could you provide minimal example to reproduce your issue?

**Comment by kuzuozhou** [comment]
> 

![image](https://github.com/dbeaver/dbeaver/assets/33926936/5554c602-ed1b-446c-a710-b6f9e9d5959e)

**Comment by kuzuozhou** [comment]
> Thank you for bug report.
> 
> Could you provide minimal example to reproduce your issue?

![image](https://github.com/dbeaver/dbeaver/assets/33926936/7c3d1d0a-330a-4ad5-9143-cde307ac7450)

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It seems like the issues has nothing to do with DBeaver. The issue is connected with your server configuration.
