### ISSUE TITLE
Database option not available in "Data transfer target type and format" step of Export Data feature

### ISSUE THREAD

**Issue by mkrigba** [dbeaver/dbeaver#20011]
### Description

I'm unable to choose "Database" as target when attempting to export data from a table in one database to another database.

According to Step 2 in https://github.com/dbeaver/dbeaver/wiki/Data-migration, Database should be an option but I don't see it in my version.
![image](https://github.com/dbeaver/dbeaver/assets/16820461/ef051649-c50c-458c-97e3-b70c27a301d9)

### DBeaver Version

DBeaver Lite Edition Enterprise Database Manager - Lite Edition Version 23.0.0.202303161222

### Operating System

Windows 10 Education Version 21H2

### Database and driver

We use several databases and drivers all of which exhibit the same lack of a Database option in the export feature.

### Steps to reproduce

1. Right click on any table in the Database Navigator
2. Select Export Data
3. Note that Database is not available in the Export target step

**Comment by E1izabeth** [comment]
DBeaver Light edition doesn't include Data Transfer to other databases feature. Please use DBeaver Community, Enterprise or Ultimate edition.
