### ISSUE TITLE
A commented line appears as an uncommented line in the sql editor

### ISSUE THREAD

**Issue by troizet** [dbeaver/dbeaver#20015]
### Description

A commented line will appear as an uncommented line in the sql editor when "--" is followed by a TAB character. If "--" is followed by a space, it's fine.

![dbeaver_bug](https://github.com/dbeaver/dbeaver/assets/9607501/79782090-cb98-43d0-8ad2-4db70d0249e9)

### DBeaver Version

23.0.4.202305071722

### Operating System

Debian 10

### Database and driver

Database: 10.3.38-MariaDB-0+deb10u1

**Comment by E1izabeth** [comment]
Unfortunately, I can't reproduce your issue. Could you send me this script or part of script as a file? This way special characters you have there remain untouched and we could reproduce and fix it.

**Comment by troizet** [comment]
I checked on another computer:
OS: Ubuntu Ubuntu 22.04.2 LTS
DBeaver version: 23.0.4.202305071722

The bug only appears for mysql and mariadb connections:
![dbeaver_bug_mysql](https://github.com/dbeaver/dbeaver/assets/9607501/a8f46aa2-2cad-4131-a463-365e70df87de)

For postgres and sqlite connections everything works correctly:
![dbeaver_bug_sqlite](https://github.com/dbeaver/dbeaver/assets/9607501/38700e8f-de2a-41c4-b82f-d08341a8f691)
![dbeaver_bug_postgers](https://github.com/dbeaver/dbeaver/assets/9607501/72b65016-7728-46ad-8b11-d44cf7fb005d)

**Comment by troizet** [comment]
Video for clarity:

https://github.com/dbeaver/dbeaver/assets/9607501/da19f216-2aa1-40a3-a248-4273f807ff3a

**Comment by E1izabeth** [comment]
Thank you for explanation. I reproduced on MariaDB
