### ISSUE TITLE
Inaccurate number appears when querying ClickHouse

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/dbeaver#20014]
### Description

`SELECT toUInt64(15369343623947579499) a, toNullable(15369343623947579499) b` results in two different values in `Grid` view, but somehow it's all good in `Text` view.

![image](https://github.com/dbeaver/dbeaver/assets/4270380/a831fbaa-69a3-4511-85e1-b5346eb1b0a1)

![image](https://github.com/dbeaver/dbeaver/assets/4270380/a2576a0e-9f4c-4478-92d5-bf83a8827a7d)

### DBeaver Version

Community Edition 23.0.4.202305071722

### Operating System

macOS Ventura 13.3.1

### Database and driver

1. Database name and version: ClickHouse 23.3.1.2823
2. Driver name and version: ClickHouse JDBC Driver 0.4.6

### Steps to reproduce

1. Issue `SELECT toUInt64(15369343623947579499) a, toNullable(15369343623947579499) b` against ClickHouse
2. Check result in `Grid` view, the second value is incorrect

### Additional context

It's not a JDBC driver issue as below test works:

```java
String number = "15369343623947579499";
try (ClickHouseConnection conn = newConnection(new Properties());
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt
                .executeQuery(String.format("SELECT toUInt64(%1$s) a, toNullable(%1$s) b", number))) {
    Assert.assertTrue(rs.next());
    Assert.assertEquals(rs.getString(1), number);
    Assert.assertEquals(rs.getString(2), number);
    Assert.assertEquals(rs.getBigDecimal(1), new BigDecimal(number));
    Assert.assertEquals(rs.getBigDecimal(2), new BigDecimal(number));
    Assert.assertEquals(rs.getLong(1), rs.getLong(2));
    Assert.assertEquals(rs.getObject(1), rs.getObject(2));
    Assert.assertEquals(rs.getObject(1, BigInteger.class), rs.getObject(2, BigInteger.class));
    Assert.assertFalse(rs.next());
}
```

**Comment by LonwoLonwo** [comment]
Hello @zhicwu 

Ok, I see the problem.
Partly it is because DBeaver expected data type `UInt64` and not the `Nullable(UInt64)` returned by ResultSetMetaData#getColumnTypeName.

**Comment by zhicwu** [comment]
Hi @LonwoLonwo, thanks for fixing the issue. Does below query work in latest build?

```sql
SELECT [toUInt64(15369343623947579499)] a, [toNullable(15369343623947579499)] b,
	(toUInt64(15369343623947579499), toNullable(15369343623947579499)) c
```

**Comment by zhicwu** [comment]
> Partly it is because DBeaver expected data type `UInt64` and not the `Nullable(UInt64)` returned by ResultSetMetaData#getColumnTypeName.

Will see if I can hide the outermost `Nullable`(and maybe `LowCardinality` too) from JDBC metadata when `dialect=ansi`.

**Comment by LonwoLonwo** [comment]
Oh, now :( Your array examples are still not working. DBeaver handles them as arrays, and then at the point of the array components reading (array.getArray()) - something goes wrong.

![2023-05-30 11_16_16-DBeaver  C__Users_anvolka_work_DbeaverP_dbeaver-workspace-idea  - C__Users_anvol](https://github.com/dbeaver/dbeaver/assets/45152336/5355e900-6abe-446b-9ea7-ed8193eae232)

You can create a separate ticket for this case.
