### ISSUE TITLE
Cannot copy from primary result set when multiple result sets exist

### ISSUE THREAD

**Issue by kyleflan** [dbeaver/dbeaver#2001]
DBeaver 4.1.2 on Mac OSX Sierra

Use the following script to reproduce.

```
CREATE TABLE temp.alpha (row_id serial, 	val text);
CREATE TABLE temp.beta (row_id serial, val int);

INSERT INTO temp.alpha (val) VALUES ('A'), ('B'), ('C');
INSERT INTO temp.beta (val) VALUES (1), (2), (3);
	
-- highlight the two rows below and type Ctrl + Alt + X
-- to produce multiple result sets
SELECT * FROM temp.alpha;
SELECT * FROM temp.beta;
```

After executing the queries, attempt to copy (either standard or advanced copy) a few rows from the primary result set. Nothing gets copied into the clipboard. 

Workaround: move to the 2nd result set and then back to the primary result set and copy to clipboard works. 

Screen capture below shows issue.

![aug-09-2017 14-49-12](https://user-images.githubusercontent.com/5608074/29140993-0d5aad04-7d12-11e7-9cac-c5ab59d1ee8a.gif)

**Comment by serge-rider** [comment]
So far I can't reproduce this on Win, will try on Mac.
Thanks for report

**Comment by serge-rider** [comment]
Can't reproduce on Mac as well. What is your MacOS version?

Please recheck. Maybe it was some glitch or something.

**Comment by kyleflan** [comment]
Mac OS Sierra 10.12.5. Exited DBeaver and restarted and issue persisted. I will follow up after my next reboot.

**Comment by kyleflan** [comment]
Confirmed this issue persists after reboot. Very minor issue that can be alleviated by switching to the second results set and back to the primary result set in order to copy data.

**Comment by budajeff** [comment]
I've encountered this issue on Windows 7 and DBeaver v4.2.2. In my case I have four results tabs open. Once copy stops working in one of them, I'm able to use the workaround (activate other results tabs in DBeaver) to get it to work again.

**Comment by uslss** [comment]
Cannot reproduce on Windows 10 / 6.0.2

**Comment by serge-rider** [comment]
Not reproducible. Please reopen if you still encounter this issue
