### ISSUE TITLE
Can't connect to postgresql database with SSL on

### ISSUE THREAD

**Issue by bchkhaidze** [dbeaver/dbeaver#20018]
### Description

Hello, 
Whenever I try to connect to a database host with "USE SSL" option on I get an error.
We have DBeaver > **PGBouncer** pod forwarded to localhost > Postgre sql server
I'm connecting using host and port configuration:
![image](https://github.com/dbeaver/dbeaver/assets/63901465/78eccf6d-fddb-4277-80ce-d6799c67bc5b)
![image](https://github.com/dbeaver/dbeaver/assets/63901465/f4be74ff-4b62-461e-b64f-dd2ca4989830)

I am getting error:
![image](https://github.com/dbeaver/dbeaver/assets/63901465/9fe4f6f7-c9b9-4438-9a6b-c8d785c60339)

Same certificates and configuration work fine with pgAdmin4 and psql. 

### DBeaver Version

Version 23.0.4.202305071722

### Operating System

Windows 11 Enterprise 22621.1702

### Database and driver

![image](https://github.com/dbeaver/dbeaver/assets/63901465/a860db9e-47d6-47d8-8c71-5055735b8551)

**Comment by E1izabeth** [comment]
Similar closed due to inactivity issue #18638

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by bchkhaidze** [comment]
> Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

!ENTRY org.jkiss.dbeaver.model 4 0 2023-05-22 15:57:01.821
!MESSAGE EOFException
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-05-22 15:57:01.822
!MESSAGE EOFException
!STACK 0
java.io.EOFException
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:589)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:191)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
	at org.postgresql.Driver.makeConnection(Driver.java:443)
	at org.postgresql.Driver.access$100(Driver.java:63)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:353)
	at java.base/java.lang.Thread.run(Unknown Source)

I have also updated details:
We have DBeaver > PGBouncer pod forwarded to localhost > Postgre sql server

**Comment by LonwoLonwo** [comment]
Could you please try to change this parameter? Maybe it can help?

![2023-06-01 16_25_58-Window](https://github.com/dbeaver/dbeaver/assets/45152336/9f8bf8da-f859-4eba-a79d-4db2c3be7340)

For now, it is not clear what is wrong.
Because `at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)` - very basic error. It gives nothing.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by szabozoltan69** [comment]
For me also appeared this issue, and the solution was the usage of a Profile.
In SSH tab (right up) there is a Profile dropdown. If it was empty, did not work.
If I chose a profile, with the same parameters, it began to work fine.
(It was misleading that the tunnel configuration setting was also good in the non-working situation.)

**Comment by rwahyudi** [comment]
Our postgres server is configured to use self signed cert and require hostssl. 

What trips most of our users is that the SSL mode is defaulted to be blank. Also does not help that it's under the advanced section : 
![Image](https://github.com/user-attachments/assets/cf134b57-4dd3-4633-ba66-944b7eb87a5b)

The error when SSL mode is blank is rather cryptic : 
![Image](https://github.com/user-attachments/assets/87afb6ba-5558-4161-81eb-a39d57fb7090)

**Suggestion:** 
- Remove blank option from the SSL mode drop down.

- Set the default selection of SSL mode to require when the top check box of "Use SSL" is ticked. 
The fact that someone clicked "use SSL" implies that the user do want to use SSL. 

- Not sure about other DBs but for MySQL & Postgres , it seems logical to move the Advanced section above the Parameters section and call it SSL options.
