### ISSUE TITLE
[Oracle] SQL*Plus native client hangs on selects with more than a few lines

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#20022]
### Description

Select for a table with more than opproximately 50 rows continues indefinately if executed with native client. It can be stopped manually but the result shown will be incomplete.

### DBeaver Version

23.0.5

### Operating System

Win 11

### Database and driver

Oracle Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options

Oracle JDBC driver 12.2.0.1.0

### Steps to reproduce

1. Create a script with basic `SELECT * FROM TABLE;` for a table that has 100+ rows
2. Right click on schema in navigator and select `Tools > Execute in SQL*Plus`
3. Click Start

**Expected:** Script is executed
**Actual:** Dbeaver shows `Executing` which continues indefinately

![image](https://github.com/dbeaver/dbeaver/assets/82543000/b38dc59c-97a9-4177-8c44-bc51ca3913a4)

**Comment by E1izabeth** [comment]
Maybe similar to #18876
