### ISSUE TITLE
Go to Matching Bracket have save active key binding as Pin/Unpin

### ISSUE THREAD

**Issue by nicholasnyw2** [dbeaver/dbeaver#20031]
### Description

Noticed that the "Go to Matching Bracket" have the same active key binding as "Pin/Unpin" - both are using Ctrl+Shift+P.

### DBeaver Version

Community  23.0.4.202305071722

### Operating System

Windows

### Steps to reproduce

Click on HELP -> "Show Active KeyBindings...."

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by nicholasnyw2** [comment]
Thabks everyone!
