### ISSUE TITLE
Columns autocompletion do not appear in selestion list, if table is withour alias

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#20032]
### Description

do not show columns hint in query without aliase 

### DBeaver Version

23.0.5

### Operating System

windows 11 64bit

### Database and driver

postgresql 14.2 

### Steps to reproduce

1. Create table

![image](https://github.com/dbeaver/dbeaver/assets/61137576/d56903d5-7882-4820-b61d-4302906eaa1a)
2. Open SQL editor
3. write query without table aliase
![image](https://github.com/dbeaver/dbeaver/assets/61137576/d0eca278-5600-4751-aec7-901c44463c88)

### Additional context

In dbaver 23.0.4 columns hint is work correctly
![image](https://github.com/dbeaver/dbeaver/assets/61137576/13ba2eef-e6be-454c-88c4-288889dccf80)

In dbaver 23.0.5 columns hint is work only with table aliase
![image](https://github.com/dbeaver/dbeaver/assets/61137576/cb15e725-08da-4fb2-930c-a24600facd05)

**Comment by MashaKorax** [comment]
Hello,@detkliff.  Thanks for your bug report! I'm reproducing the issue in dbaver 23.0.5. To return the previous behavior you should disable the checkbox in Window -> preferences ->SQL editor -> Code completion->  "enable experimental features"
![chrome_OaHyIvUKKL](https://github.com/dbeaver/dbeaver/assets/84867187/4302eae6-a57b-4bf0-973a-4a5be4103256)

**Comment by MashaKorax** [comment]
Its still not working in case "WHERE"
![4qAVEj5JPE](https://github.com/dbeaver/dbeaver/assets/84867187/9b1e2abd-142e-4b83-a313-c6e8319c4ed0)
![pddUBJIL83](https://github.com/dbeaver/dbeaver/assets/84867187/d3fabe02-c040-4dc3-9940-97bfeecd6e13)
