### ISSUE TITLE
[GIS] Save/copy as picture saves black filled rectangle

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#20038]
### Description

Saving/copying a map with bottom toolbar is impossible. Opening in browser still works though.

### DBeaver Version

23.0.5

### Operating System

Win11

### Database and driver

Any

### Steps to reproduce

1. Open spatial data viewer
2. Click copy as picture
3. Paste the picture in any visual editor

**Expected:** Map picture is pasted
**Actual:** Blank black rectangle is pasted

**Comment by Matvey16** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/dbeaver/project/8805?defectId=14116)
- Test [Spatial View: Miscellaneous buttons](https://web.testquality.com/site/dbeaver/project/8805/runs/176974?resultId=3279384) in Run [23.0.5 General CE](https://web.testquality.com/site/dbeaver/project/8805/runs/176974) (linked to Cycle [General-CE](https://web.testquality.com/site/dbeaver/project/8805/cycles/15194)).

**Comment by E1izabeth** [comment]
Fixed in scope of https://github.com/dbeaver/pro/issues/1151
