### ISSUE TITLE
Views become tables after export

### ISSUE THREAD

**Issue by dengbuliduo** [dbeaver/dbeaver#20030]
### Description

this happen in oracle.I dont repeat it in the other database

### DBeaver Version

23.0.4.202305071722

### Operating System

window 11

### Database and driver

oracle.jdbc.OracleDriver

### Steps to reproduce

1.right click the view in the tablespace a
2.choose export
3.choose table and step by step

**Comment by LonwoLonwo** [comment]
Hello @dengbuliduo 

Could you please provide any screenshots of your issue?

**Comment by E1izabeth** [comment]
It's reproducible.

**Comment by Matvey16** [comment]
@dengbuliduo Can you explain your use case here? THe view doen't contain any data so nothing can be imported there. You can copy a view ddl with another name and the newly created view would show exactly the same data. Or do you imply some other use case there?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
