### ISSUE TITLE
SQL Server: Column autocomplete isn't working for JOINed tables to a subquery

### ISSUE THREAD

**Issue by AsparagusEduardo** [dbeaver/dbeaver#20045]
### Description

![imagen](https://github.com/dbeaver/dbeaver/assets/2904965/3d970aee-e6f4-44f7-a072-4238729e05dc)

### DBeaver Version

Community Edition 23.0.5

### Operating System

Windows 10 Pro 22H2

### Database and driver

1. SQL Server 2019
2. Microsoft JDBC Driver for SQL Server (MSSQL)

### Steps to reproduce

1. Connect to database
2. Create a query with left joins to a subquery
3. Ctrl + Space for autocomplete

**Comment by E1izabeth** [comment]
You could try unchecking this preference or fix your query as currently it contains syntax errors.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/7d3b03f3-aa63-4c01-95d6-e6382cb6ae30)

**Comment by E1izabeth** [comment]
Could you provide a full query or some example. Unfortunately, I can't reproduce the issue.

**Comment by AsparagusEduardo** [comment]
> You could try unchecking this preference or fix your query as currently it contains syntax errors.

Unchecking the setting solves the issue.
![imagen](https://github.com/dbeaver/dbeaver/assets/2904965/9d7aad21-aa1e-4a9e-9b16-eace5e3dadff)

EDIT: the syntax error was due to me accidentally trying to execute the incomplete query.

**Comment by jshmlr** [comment]
Here to report that, without unchecking the "Enable experimental features" box, auto complete would not work for even a basic select query.

**Comment by E1izabeth** [comment]
@jshmlr please, provide your case as it's not true for me
