### ISSUE TITLE
unable to export data from file 800M size from one dbase to another...it is hanging up

### ISSUE THREAD

**Issue by jgrover21** [dbeaver/dbeaver#20049]
### Description

dbeaver failing to export data from one dbase to another.  Dbeaver ver 23.0.4.
out of memory error.

### DBeaver Version

23.0.4

### Operating System

Windows

### Database and driver

postgresql 14.6

**Comment by jgrover21** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/125315744/8c5f05a0-cbc5-4bc3-9ef7-224704bcd2f7)

**Comment by ShadelessFox** [comment]
Hello @jgrover21,

Could you please provide the source table's DDL?

You can try increasing the maximum allowed memory DBeaver can use as a possible workaround. Please see https://github.com/dbeaver/dbeaver/wiki/Command-Line

**Comment by E1izabeth** [comment]
It's been a while since no update here, so I'm closing this issue. If it's still actual, please let me know and provide additional information.
