### ISSUE TITLE
Import arrays from csv to postgres db

### ISSUE THREAD

**Issue by khalid-sani** [dbeaver/dbeaver#2004]
Is this supported? Even when I manually change the mapping type, I'm getting "org.jkiss.dbeaver.model.exec.DBCException: String data type 'VARCHAR' not supported by database"

**Comment by serge-rider** [comment]
No, it is not supported yet. I'll make this ticket feature request.

**Comment by mkgrgis** [comment]
Problems with creating arrays in postgres https://github.com/dbeaver/dbeaver/issues/7819

**Comment by uslss** [comment]
already implemented
