### ISSUE TITLE
Table named `number` doesn't get any field suggestions while other tables do

### ISSUE THREAD

**Issue by remimoncayo** [dbeaver/dbeaver#20067]
### Description

Since a couple of days ago I noticed that I'm not getting any field suggestions for tables named using reserved words.

See the example below. I have a table named account and I'm getting suggestions after a. When using the table number or user, this isn't happening:
![Peek 2023-05-24 11-12](https://github.com/dbeaver/dbeaver/assets/6709596/3913c512-4f9a-48b3-a89c-ece4c21f7991)

### DBeaver Version

Community edition 23.0.5.202305211610

### Operating System

Ubuntu 20.04

### Database and driver

MySQL 5

### Steps to reproduce

1. Create a table using a reserved word such as number, user.
2. Try to obtain field suggestions from the table.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
Does it still reproducible in the latest DBeaver version?

**Comment by E1izabeth** [comment]
I can't reproduce it anymore. Seems it was fixed.
