### ISSUE TITLE
Very slow script start

### ISSUE THREAD

**Issue by perverez** [dbeaver/dbeaver#20060]
### Description

Hello,

between versions 23.0.0 and 23.0.1 there is probably some change that makes the start of the big script extremely slow. The script with a size of 5973 bytes (86 lines) in the older version started within 1 second and took 131 ms to execute, in all newer versions (last tested in version 23.0.5) it takes 3 more than minutes to execute the script (before the blue arrows appear next to the SQL editor), the actual processing of the script is again 131 ms. I also noticed that there is a lot of load on the computer processor. I tried to create a new profile, set the default properties, disable SQL syntax, reinstall the program, but nothing helped.

Can you advise what the problem might be? Thank you. Jan.

### DBeaver Version

Community Edition 23.0.5 (problem from dbeaver-ce-23.0.1-win32.win32.x86_64.zip)

### Operating System

Windows 10 Pro x64

### Database and driver

1) Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)
2) Microsoft JDBC Driver 7.0 for SQL Server 7.0.0.0

**Comment by E1izabeth** [comment]
Could you clarify, what do you mean by "start script": script opening or script execution?

**Comment by perverez** [comment]
Script execution (Alt+X)

**Comment by arhayka** [comment]
Could you please send a script example and additionally try to generate a thread dump during the script exectuion and attach it here? 
Here is the instruction: https://dbeaver.com/docs/wiki/Making-a-thread-dump/
Thank you.

**Comment by perverez** [comment]
Hello,

here is the exact script that slows down the whole processing. Under MSSMS the result is instantaneous, under DBeaver I wait 7 seconds - blue arrows appear and then nothing happens. The script creates a string in GPX format, I modified it so that no table is required. Dump was created during the processing of the script.

`SELECT (SELECT '1.0' AS '@version', (SELECT 'Test' AS 'name', (SELECT (SELECT DISTINCT 51.64315 AS '@lat', 14.31709 AS '@lon' FOR XML PATH('trkpt'), TYPE) FOR XML PATH(''), ROOT('trkseg'), TYPE) FOR XML PATH('trk'), TYPE) FOR XML PATH('gpx'), TYPE) FOR XML PATH('')`

[thread-dump.txt](https://github.com/dbeaver/dbeaver/files/11565560/thread-dump.txt)

**Comment by E1izabeth** [comment]
Thank you. I reproduced the issue.

**Comment by E1izabeth** [comment]
The issue is connected with JSQLParser library, that we use.

**Comment by perverez** [comment]
Thank you, in the meantime I will use version 23.0.0

**Comment by E1izabeth** [comment]
@perverez could you try Early Access version https://dbeaver.io/files/ea/?

**Comment by perverez** [comment]
Hi,

I tried the Early Access version and it looks like the problem has been solved.

Thank you.

P.
