### ISSUE TITLE
Connection conflict when connecting to a DBeaver Database

### ISSUE THREAD

**Issue by Maximelmr539** [dbeaver/dbeaver#20062]
### Description

Our team is currently using DBeaver as our preferred visualization tool for working with our database. However, we also have a requirement to modify the database programmatically using a Python script.

The problem we encountered is that when DBeaver is connected to the database, our Python script fails to establish a connection. We would like to find a solution that allows us to use DBeaver for visualization and have the ability to modify the database concurrently from a Python script.

Please let us know if there are any specific configurations or settings we need to adjust in order to achieve this simultaneous connection.
<img width="369" alt="Error" src="https://github.com/dbeaver/dbeaver/assets/134410202/e8c797aa-a816-42de-b2cf-ee917ee135f7">

### DBeaver Version

23.0.4

### Operating System

Windows 10

### Steps to reproduce

Connect to the database using DBeaver 

subprocess.call(['net', 'use', 'Z:', '\\\\IP.SERVER\\d$'])
conn = duckdb.connect(database=r"Z:\Database_EM\Database\QEM")

**Comment by LonwoLonwo** [comment]
Hello @Maximelmr539 

These discussions may be helpful for you. 
https://github.com/duckdb/duckdb/discussions/3096
https://github.com/dbeaver/dbeaver/issues/18202

If I understand correctly, you can not write from two different connections in the DuckDB database file.

**Comment by Maximelmr539** [comment]
Hello @LonwoLonwo 

Thank you very much, it seems indeed it is impossible to mix read-write and real only connections.

Thanks again for your help!

**Comment by LonwoLonwo** [comment]
Can I close the ticket, then? Or do you have another question?
