### ISSUE TITLE
Error during node load

### ISSUE THREAD

**Issue by tratak** [dbeaver/dbeaver#20065]
### Description

Hello ! 
I was working on Dbeaver. I've done an replace in a sql editor (a " character with nothing) on a SQLServer database. After that the elements from database navigator dissapeared with the following error. 
I've upgraded to the most new version (23.0.5). The same problem at start of program.
Uninstalled, removed all registry form Regedit that I found with Dbeaver name. Reinstalled. The same problem:

com.google.gson.stream.MalformedJsonException: Unterminated object at line 10 column 17 path $..sqlite_jdbc-18793c115a5-5c560f6e7728dcaf.configuration.database
  Unterminated object at line 10 column 17 path $..sqlite_jdbc-18793c115a5-5c560f6e7728dcaf.configuration.database
  Unterminated object at line 10 column 17 path $..sqlite_jdbc-18793c115a5-5c560f6e7728dcaf.configuration.database

and no node in database navigator.

### DBeaver Version

23.0.5.202305211610

### Operating System

Windows 11

### Database and driver

Postgresql
SQLServer
SQLite

### Steps to reproduce

I was working on Dbeaver. I've done an replace in a sql editor (a " character with nothing) on a SQLServer database. After that the elements from database navigator dissapeared with the following error. 
I've upgraded to the most new version (23.0.5). The same problem at start of program.
Uninstalled, removed all registry form Regedit that I found with Dbeaver name. Reinstalled. The same problem:

com.google.gson.stream.MalformedJsonException: Unterminated object at line 10 column 17 path $..sqlite_jdbc-18793c115a5-5c560f6e7728dcaf.configuration.database
  Unterminated object at line 10 column 17 path $..sqlite_jdbc-18793c115a5-5c560f6e7728dcaf.configuration.database
  Unterminated object at line 10 column 17 path $..sqlite_jdbc-18793c115a5-5c560f6e7728dcaf.configuration.database

and no node in database navigator.

**Comment by LonwoLonwo** [comment]
Hello @tratak 

Hmm, we will look into it, thanks.

For now, you can try to fix your issue by yourself.
You need to find your workspace in your system. The workspace path is in the Preferences -> General -> Workspace
Then you need to find your project and choose the `.dbeaver` folder
like `\AppData\Roaming\DBeaverData\workspace6\General\.dbeaver\`
Here is the file for your connections: `data-sources.json`
`Unterminated object at line 10 column 17` - check this place

**Comment by tratak** [comment]
RESOLVED. I've tried to add again all connctions. I've succeded. After a new relaoad the error dissapeared.
