### ISSUE TITLE
Autocomplete of tables with quotes

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#20073]
### Description

Now we support only quotes `"`, we need to support also `[ ]`  and ` as quotes for identifiers.

For example, if we autocomplete propose nor alias, nor table name in this case.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/a013e379-10de-4940-9712-5ee5fb035149)

but should

![image](https://github.com/dbeaver/dbeaver/assets/28875055/7e896b08-07b1-4186-b4d0-1d47f396c669)

### DBeaver Version

DBeaver 23.0.5

**Comment by jaymeyer** [comment]
this was bothering me, we have an old table 'security' which must be quoted to support a mariadb reserved word.  
And now that this is fixed, I can use Auto completion on this table too.  Thanks for fixing this, Love this product / community.
