### ISSUE TITLE
Problem with compare function between Oracle and PostgreSQL

### ISSUE THREAD

**Issue by did16** [dbeaver/dbeaver#2008]
Hi
We are migrating an 11.2.0.4 Oracle database to an 9.6.3 PostgreSQL database.
We want to verify if the data is correct. For this we want to use the compare function of dbeaver 4.0.8.
But when I execute compare function I get the message : 
"Objects of different types were selected. You may compare only objects of the same type"
While I am positioned on the tab "tables"...

Thanks in advance

**Comment by tati-kru** [comment]
Hi @did16! 
Could you, please, check that it can be reproduced or not on the latest version?
