### ISSUE TITLE
Active database/schema changes back to previous after executing script

### ISSUE THREAD

**Issue by SylwesterZarebski** [dbeaver/dbeaver#20089]
### Description

When using script tab after few database changes and script executes, active database goes back to previous.

### DBeaver Version

CE 23.0.5.202305211610

### Operating System

Windows 10

### Database and driver

MariaDB 10.1.48-MariaDB-0+deb9u2

### Steps to reproduce

How to reproduce:
1. Connect to MariaDB server.
2. Open new script tab with current connection.
3. Write some script (i.e. SELECT 1) and save it.
4. Reopen/load script.
5. Change database/schema.
6. Execute script.
7. Repeat points 5-6 and after 2-3 changes active database goes back to previous.

### Additional context

Tunnel using SSH - SSHJ.
Settings has been cleared when installing new version.

**Comment by LonwoLonwo** [comment]
Hello @SylwesterZarebski 

Could you please check this setting in your Preferences? Does it enabled?

![2023-05-25 10_45_14-DBeaver Ultimate 23 0 5 - call_center](https://github.com/dbeaver/dbeaver/assets/45152336/2a6b73d2-1f58-4dff-9101-8ef048d8267d)

**Comment by SylwesterZarebski** [comment]
Yes, it is (was) enabled (by default), but i also disabled this option, it did not fix problem.
After disabling option and restart dBeaver and then open script, it looks like there is no problem, but after close and reopen script tab this weird behaviour is back.

**Comment by flambchap** [comment]
@SylwesterZarebski Unfortunately, I can not reproduce the issue. Can you please provide footage showing your issue? Thank you.

**Comment by SylwesterZarebski** [comment]
Sorry for delay, i have to prepare new test server to make such video (current server configuration is client's), but no time to do this now.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
