### ISSUE TITLE
Table columns do not appear for SELECT with WITH clause

### ISSUE THREAD

**Issue by passacaglia** [dbeaver/dbeaver#20096]
### Description

In Community Edition version 23.0.5, table columns do not appear after entering the table alias and the period character.

![image](https://github.com/dbeaver/dbeaver/assets/1525402/b839643d-7641-43eb-8142-d8a9922a4ebf)

I am expecting behavior similar to a table column prompt in version 23.0.4

![23 0 4](https://github.com/dbeaver/dbeaver/assets/1525402/e5c56923-66f4-4454-a1e1-35c14beaa438)

### DBeaver Version

Community Edition 23.0.5

### Operating System

Windows 11 

### Database and driver

SQL Server 2016
Microsoft JDBC Driver for SQL Server (mssql-jdbc-9.2.0.jre8)

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
As a workaround you can uncheck this setting to return back previous behavior
![image](https://github.com/dbeaver/dbeaver/assets/28875055/be1229a4-8361-49de-8840-ec019700912c)

**Comment by passacaglia** [comment]
Problem solved after uncheck the setting. Thank you so much for your quick response, it was a huge help! 😊

**Comment by jonatasvnascimento** [comment]
I'm using the Community Edition version 23.0.5 and I'm having the same problem with auto completion I'm back to 23.0.0 I'm going to test the suggestion to remove new features

**Comment by mtrentz** [comment]
Just to add to this, I had a similar problem on 23.0.5 (Mac apple silicon), autocompletion would either not work or just be way slower than before. Going back to 23.0.2 which was my previous version fixed for me.

**Comment by alietors** [comment]
As a curiosity I came here for the exact opposite problem. I did not get autocomplete without alias.
I unchecked the experimental and everything is back to normal.

**Comment by E1izabeth** [comment]
Fix for most cases will be available in the next release (DBeaver 23.1.0)

**Comment by AxelRHD** [comment]
Has driven me crazy for over a week now. It is a good example how you rely on your daily helpers. Thanks so much for your great work with this application.

Unchechking the experimental features also solved my problem.

**Comment by 2019-05-10** [comment]
> Fix will be available in the next release (DBeaver 23.1.0)

Will that automatically re-enable that "Enable experimental features" checkbox?

**Comment by E1izabeth** [comment]
@2019-05-10 
Settings are preserved between updates. It will stay disabled.

**Comment by renezito** [comment]
> Fix for most cases will be available in the next release (DBeaver 23.1.0)

Please ensure that will work in 23.1.0.   Yesterday I downloaded 23.1.0 y today I'm trying the autocomplete, but it still have some problems.  I have to uncheck the experimental features and autocomplete works without problem.

Anyway, thanks for this great tool !

**Comment by E1izabeth** [comment]
@renezito 
Please create a separate issue about your problems, if they are not the same as in this issue. At the same time I can't know what exactly are you talking about without any example. so please give me one.

**Comment by 2019-05-10** [comment]
Still an issue with Version 23.1.1.202306251800.
At some point completion suddenly breaks and never resumes. Toggling that "Enable experimental features" checkbox does not change anything.
Could it be related to too large an editor, the parser breaking down w/ too many statements, comments, etc?
Sadly, nothing in `.metadata/.log`

**Comment by 2019-05-10** [comment]
Still an issue with Version 23.1.3.202307231901.
Completion is so unreliable and easily broken to be virtually useless.
Anything we can do to help fix that?

**Comment by E1izabeth** [comment]
@2019-05-10 
If your issue is not about SELECT containing WITH clause, please report it separately.
Also this workaround should help https://github.com/dbeaver/dbeaver/issues/20096#issuecomment-1562591342

**Comment by 2019-05-10** [comment]
Did miss that limitation.

> Also this workaround should help [#20096 (comment)](https://github.com/dbeaver/dbeaver/issues/20096#issuecomment-1562591342)

As mention before: that workaround does not do anything anymore.

**Comment by AxelRHD** [comment]
> Did miss that limitation.
> 
> > Also this workaround should help [#20096 (comment)](https://github.com/dbeaver/dbeaver/issues/20096#issuecomment-1562591342)
> 
> As mention before: that workaround does not do anything anymore.

I can confirm this. Autocompletions seems completely broken (again).
