### ISSUE TITLE
Create table not finishing - Query with 10 subqueries with joins/union/transformation

### ISSUE THREAD

**Issue by jgrover21** [dbeaver/dbeaver#20102]
### Description

I have a query built that has 10 subqueries which are running just fine independently...but when I want to create a table it keeps running for full day and half and still not return...

### DBeaver Version

23.0.5

### Operating System

windows

### Database and driver

postgresql 14.0

**Comment by E1izabeth** [comment]
Probably, connected with #20060

**Comment by E1izabeth** [comment]
Thank you for bug report.

Could you send log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by HrishikeshTangella** [comment]
SQL Error [57014]: ERROR: canceling statement due to user request.
Query is taking long time to execute so cancelling to terminate the process.

**Comment by E1izabeth** [comment]
Thank you. I'm closing this issue as a duplicate of #20060
You can follow that issue to be notified on updates.

**Comment by jgrover21** [comment]
Is there any solution out there?  I noticed this issue listed.

Respectfully,

Jyoti Grover

**Comment by E1izabeth** [comment]
@jgrover21 
Unfortunately, I don't see any workaround. Hope we will fix it soon. The issue is related to JSQLParser library which we use.

**Comment by jgrover21** [comment]
Ok thank you.

Respectfully,

Jyoti Grover

**Comment by E1izabeth** [comment]
By the way, DBeaver 23.0.0 doesn't have this bug.

**Comment by jgrover21** [comment]
Can we revert back to this version?

Respectfully,

Jyoti Grover

**Comment by E1izabeth** [comment]
You can find this version in our versions archive and install it, while the issue is not solved
https://dbeaver.io/files/23.0.0/

**Comment by jgrover21** [comment]
This is even slower to export.

Respectfully,

Jyoti Grover

**Comment by E1izabeth** [comment]
Does your case similar to provided in this comment?
https://github.com/dbeaver/dbeaver/issues/20060#issuecomment-1562949376

**Comment by E1izabeth** [comment]
@jgrover21 could you try Early Access version https://dbeaver.io/files/ea/? Does the issue is solved there?
