### ISSUE TITLE
Field proposal in Version 23.0.5.202305211610

### ISSUE THREAD

**Issue by guiwebdev** [dbeaver/dbeaver#20107]
### Description

Anyone having issues with column proposal in thsi last version

### DBeaver Version

23.0.5.202305211610

### Operating System

W11 Pro

### Database and driver

Oracle, Firebird, etc

### Steps to reproduce

a simple select command won't show the database column proposal while typing script

**Comment by E1izabeth** [comment]
Please, provide an example of query which is not working

**Comment by E1izabeth** [comment]
Also as a workaround you can uncheck this setting to return back previous behavior

![image](https://github.com/dbeaver/dbeaver/assets/28875055/2fe8b576-7fa0-4c9a-9815-8bdbce5156f2)

**Comment by JohannesBeranek** [comment]
Same here. My issue is when I make subselects with parens, and already add the closing paren, then go back with the cursor and type on the subquery. No autocompletion. Removing the closing parens it works again. Also, as soon as anything before the current position goes into syntax issues, the autocomplete is also broken. Not sure there's much you can do there though. I'd be happy though on that if a semicolon outside a string would terminate the current query, even if there's still an open parens or anything like that, so I can start on a new one.

**Comment by guiwebdev** [comment]
Hi Elizabeth,

All queries display the same incorrect beahviour. And just a simple select
won't display proposals.

Unselecting the "Enable Experimental Features" as you proposed *has solved
this issue immediately*.

Elizabeth ***@***.***> escreveu no dia sexta, 26/05/2023 à(s)
10:30:

**Comment by E1izabeth** [comment]
Simple select might be written in lots of ways. Please, provide a concrete example, otherwise we can't fix your case.

**Comment by guiwebdev** [comment]
Select column1
from table_name

if I decide to add a new column, for example column2, I don't get the
proposal, for any column of the database.

Another thing is, as a personal opinion of course, if I unselect a
function, and it solves a problem, I believe you can find the bug without
me explaining a sql query.
Just find the code related to text proposals that was changed in the
"Experimental" feature...

Elizabeth ***@***.***> escreveu no dia sexta, 26/05/2023 à(s)
11:39:

**Comment by E1izabeth** [comment]
Thank you for explanation. It's much more clearer now.
