### ISSUE TITLE
The wiki page "Develop in IDEA" has some incorrect steps

### ISSUE THREAD

**Issue by heartdance** [dbeaver/dbeaver#20105]
### Description

Some steps under Title "Configuring dependencies and compiling the application" on the [Develop in IDEA](https://github.com/dbeaver/dbeaver/wiki/Develop-in-IDEA) wiki page are incorrect. Will cause failure to start using IDEA.

The current steps are as follows:
5.Create new library ECLIPSE (name and case are important)
6.Click the "Add" button. Select the folder eclipse-ide-path/plugins

Should be:
5.Click the "Add" button. Select Java. Select the folder eclipse-ide-path/plugins. Click OK button. Choose all modules **exclude dbeaver**. Click OK button.
6.Change the library name to ECLIPSE (name and case are important)

### DBeaver Version

devel

### Steps to reproduce

1.Open wiki page [Develop in IDEA](https://github.com/dbeaver/dbeaver/wiki/Develop-in-IDEA)
2.Scroll to title "Configuring dependencies and compiling the application"

**Comment by ShadelessFox** [comment]
Hello @heartdance,

Why do you think it should be that way? For me, it works perfectly fine (adding the entire `plugins` directory).

**Comment by heartdance** [comment]
I don't mean to choose which dependencies under the `plugins` directory, but to add these dependencies to which modules. And these two steps do not correspond to the view actually seen in IDEA.

**Comment by ShadelessFox** [comment]
Ah, I see. You're talking about the additional step that is not required. You can click "Cancel".

Let's mention that on the wiki anyways.
