### ISSUE TITLE
[MySQL/MariaDB] do not show empty default partitions

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#20108]
According to the [documentation](https://dev.mysql.com/doc/refman/5.7/en/information-schema-partitions-table.html), any table without created partitions has a default partition:

> A table using any storage engine other than [NDB](https://dev.mysql.com/doc/refman/5.7/en/mysql-cluster.html) and which is not partitioned has one row in the [PARTITIONS](https://dev.mysql.com/doc/refman/5.7/en/information-schema-partitions-table.html) table. However, the values of the PARTITION_NAME, SUBPARTITION_NAME, PARTITION_ORDINAL_POSITION, SUBPARTITION_ORDINAL_POSITION, PARTITION_METHOD, SUBPARTITION_METHOD, PARTITION_EXPRESSION, SUBPARTITION_EXPRESSION, and PARTITION_DESCRIPTION columns are all NULL. Also, the PARTITION_COMMENT column in this case is blank.

![2023-05-26 12_22_52-DBeaver 23 0 3 - account](https://github.com/dbeaver/dbeaver/assets/45152336/8911ec0d-5eea-48e2-9aff-f73152e640ea)

But it is confusing - to have empty partitions in all unpartitioned tables. Let's hide them.

**Comment by uslss** [comment]
error appears during partition creation from UI

![image](https://github.com/dbeaver/dbeaver/assets/31996417/957e90d6-04fc-4bd8-bb09-fbfada643b73)
