### ISSUE TITLE
JOIN autocompletion doesn't work using Backticks In MariaDB

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#20113]
### Description

![EWWHv0PvlG](https://github.com/dbeaver/dbeaver/assets/84867187/f56ace24-1ecd-4ea2-b1ea-4cc17900f176)
![tYk8St1ApG](https://github.com/dbeaver/dbeaver/assets/84867187/b3a7340a-a8d1-40a6-8c17-aa0b15896ee0)

autocompletion  works with SELECT, WHERE, but not with JOIN

### DBeaver Version

23.0.4

### Operating System

win 10

### Database and driver

MySQL 5.7.25-28 MariaDB Connector/J 3.0.7

**Comment by MatteoR23** [comment]
Hello, this issue is affected by Oracle driver too with latest version of Dbeaver. Should I open a new bug?

**Comment by E1izabeth** [comment]
Can't reproduce on DBeaver 23.1.4
![image](https://github.com/dbeaver/dbeaver/assets/28875055/95228b60-0ad8-4e3e-968b-e5d418069940)
