### ISSUE TITLE
Download required libraries automatically

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#20114]
**Is your feature request related to a problem? Please describe.**
I installed fresh DBeaver-23.0.5-ce. It automatically downloads java driver and the I got next error:
![image](https://github.com/dbeaver/dbeaver/assets/799021/179a3f64-81cf-4f36-9cd9-bb7ca229d55a)
 

**Describe the solution you'd like**
Automatically download/install required drivers.

**Describe alternatives you've considered**
Provide a link to an instruction how to do that.

**Comment by KES777** [comment]
How I resolved it: https://stackoverflow.com/a/64546286/4632019

![image](https://github.com/dbeaver/dbeaver/assets/799021/2971ba0d-24e3-4017-86c9-165ef4d03583)

Because it is fresh installation, would be nice to download fresh drivers on first step.

**Comment by KES777** [comment]
After manual `download/update`
![image](https://github.com/dbeaver/dbeaver/assets/799021/4ef97a89-103f-4cb6-9d8e-de2dae77f56a)

**Comment by flambchap** [comment]
Hi @KES777. The default version of the driver is 42.5.2. At the same time, we store drivers separately from the installation. It seems like somehow the old driver got stuck in the `drivers` folder, and DBeaver somehow failed to offer an update. Unfortunately, I don't have an idea of how to reproduce the issue.

**Comment by flambchap** [comment]
I'll close the issue for now. If you or anybody else reencounters this issue, please feel free to reopen the ticket.
