### ISSUE TITLE
connection to spark sql bug

### ISSUE THREAD

**Issue by boy-xiaozhang** [dbeaver/dbeaver#20129]
### Description

connection to spark sql don't show databases and data tables

### DBeaver Version

23.0.5

### Operating System

MAC

**Comment by E1izabeth** [comment]
Please provide log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by boy-xiaozhang** [comment]
> Please provide log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

It is exactly the same as this mistake, but it cannot be solved. #5314

**Comment by LonwoLonwo** [comment]
Hello @boy-xiaozhang 

We still need logs. Additionally, please provide your database and driver versions.

**Comment by boy-xiaozhang** [comment]
<img width="544" alt="image" src="https://github.com/dbeaver/dbeaver/assets/60912722/a676abd9-0b78-4d2e-979d-26f8336f9558">
 hi bro the above is the jdbc driver I am using，also no error log
<img width="910" alt="image" src="https://github.com/dbeaver/dbeaver/assets/60912722/b7949ee4-2350-4c80-b030-3184fd89f950">
<img width="447" alt="image" src="https://github.com/dbeaver/dbeaver/assets/60912722/fe36949f-049e-4499-a250-a89a6382dffc">

**Comment by LonwoLonwo** [comment]
Not all errors from the log are visible in the Error View.
Please, provide us with the log files: https://dbeaver.com/docs/wiki/Log-files/#log-files

**Comment by boy-xiaozhang** [comment]
<img width="513" alt="image" src="https://github.com/dbeaver/dbeaver/assets/60912722/5eed09d3-84e3-4ef2-857f-ea7255fa6616">
hello I did not find

**Comment by boy-xiaozhang** [comment]
<img width="544" alt="image" src="https://github.com/dbeaver/dbeaver/assets/60912722/67348ed6-890e-4150-8bfc-a4982a596e0e">

**Comment by ShadelessFox** [comment]
@boy-xiaozhang it's a hidden folder. Just `cd` into `~/Library/DBeaverData/workspace6/.metadata` and you will find log files.

**Comment by boy-xiaozhang** [comment]
thanks.accustomed to ll command, executed ls -la can operate, I found the log file
<img width="1143" alt="image" src="https://github.com/dbeaver/dbeaver/assets/60912722/a71f132f-11ba-43f8-8bba-f75c08d246d4">

**Comment by boy-xiaozhang** [comment]
According to my judgment, the jar implementation method used may not be supported. Do we need to replace the jar package? If so, do we have any good suggestions? I think some students have used kyuubi to solve this problem, but we do not have kyuubi.

**Comment by ShadelessFox** [comment]
I'm confused. What needs to be fixed for you? You're referring to another ticket about tables not showing, but all I can see are network-related errors. Please provide more information regarding your issue.

**Comment by boy-xiaozhang** [comment]
> I'm confused. What needs to be fixed for you? You're referring to another ticket about tables not showing, but all I can see are network-related errors. Please provide more information regarding your issue.

The real mistake I saw is that the driver is wrong and there is no corresponding implementation method.

**Comment by E1izabeth** [comment]
@boy-xiaozhang can you reproduce it again and send a screenshot of this error?

**Comment by E1izabeth** [comment]
@boy-xiaozhang could you clarify what driver is wrong for you and what is correct?

**Comment by boy-xiaozhang** [comment]
@E1izabeth I am using the default driver downloaded by dbeaver. Figure 1 is the driver, and Figure 2 is a screenshot of the error.<img width="469" alt="image" src="https://github.com/dbeaver/dbeaver/assets/60912722/a832daef-f576-49f1-bef6-3cf64d018dff">
<img width="903" alt="image" src="https://github.com/dbeaver/dbeaver/assets/60912722/27e19846-38ca-4dee-8bfe-9392d81c4f5e">

**Comment by boy-xiaozhang** [comment]
@E1izabeth  hello   is there any good solution or should I try to replace the driver or the dbeaver version

**Comment by boy-xiaozhang** [comment]
spark version 2.4.0 
hive-jdbc-driver version is 1.1.0
The old version of dbeaver can be used in a certain project before

**Comment by ShadelessFox** [comment]
> The real mistake I saw is that the driver is wrong and there is no corresponding implementation method.

If you're claiming the issue is with the driver, it has nothing to do with DBeaver. This is a third-party issue.
