### ISSUE TITLE
New database connector for Altibase

### ISSUE THREAD

**Issue by zennken** [dbeaver/dbeaver#20126]
**Is your feature request related to a problem? Please describe.**

Hello,

This is Choong Hun Kim, working for Altibase.

Altibase is a relational DBMS (https://en.wikipedia.org/wiki/Altibase). DBeaver has only been able to connect to Altibase generically, so we couldn't fully use it. I want to improve mutual compatibility between DBeaver and Altibase by providing Altibase-specific connector.

I'm new to open-source project and DBeaver development. So, any advice or help will be welcomed.

Thanks,

**Describe the solution you'd like**

I want to provide Altibase-specific DB Object browser function and SQL Editor function. I want to add advanced features continuously in the future.

**Comment by LonwoLonwo** [comment]
Hello @zennken 

We are always open to new contributions.

You can look at previous PRs about new databases support: https://github.com/dbeaver/dbeaver/pull/18299, https://github.com/dbeaver/dbeaver/pull/11882/files etc.

You can look at https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code

And on the DBeaver's code as an example. You can create your PR, and we will help you to correct it.

**Comment by DariaMarkaryan** [comment]
Verified

**Comment by zennken** [comment]
Hello, @LonwoLonwo, @serge-rider , @E1izabeth, @ShadelessFox , @DariaMarkaryan 

At last, the long PR has been finished :)

It was my first open source code commit and a great experience that taught me a lot, though it wasn't easy. 

Thank you all of you so much and have a good year :)

**Comment by zennken** [comment]
Hello,  @serge-rider 

Could you let me know when the DBeaver will be packaged with this plugin officially? I'd like to let users know when it will be available.

I couldn't find this feature at the milestone, https://github.com/dbeaver/dbeaver/milestones.

Thanks,

**Comment by serge-rider** [comment]
Hi @zennken
it will be included in 23.3.3

**Comment by zennken** [comment]
Okay, thanks for your quick reply :)

**Comment by LonwoLonwo** [comment]
Thanks again for your contribution @zennken. It means a lot to us.
And thanks for your patience :)

**Comment by zennken** [comment]
> Thanks again for your contribution @zennken. It means a lot to us.
> And thanks for your patience :)

Same here :) @LonwoLonwo 

I appreciate your invaluable help.

I hope see you soon again :)
