### ISSUE TITLE
Unrecognizable table names

### ISSUE THREAD

**Issue by edsonrodsilva** [dbeaver/dbeaver#20123]
### Description

When connecting to any database, the table names are with these special characters.

Print:
![Screenshot-2023-05-29-135440](https://github.com/dbeaver/dbeaver/assets/2845966/76727254-7938-484c-a2bf-96a82fc33b81)

### DBeaver Version

Version 23.0.5.202305211610

### Operating System

Windows 11 - Os Build 22000.1936

### Database and driver

All databases

**Comment by E1izabeth** [comment]
Have you tried changing the default font here?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/f8ebb4dd-8228-4694-9cea-683ccb58a95a)

**Comment by edsonrodsilva** [comment]
Hi thanks for the tip,
But I had already done that and it didn't work.
I already added other fonts and the problem continues.

**Comment by LonwoLonwo** [comment]
Hello @edsonrodsilva 
Did you try to reload DBeaver application?

**Comment by edsonrodsilva** [comment]
Hello @LonwoLonwo 
This problem has been occurring for over a month now.

I've done everything in my power:
- I already restarted the PC
- I already reinstalled DBeaver
- I already changed the language of the operating system
- I already changed the font in DBeaver

No success yet

**Comment by E1izabeth** [comment]
Haven't you tried to update Windows since then?

**Comment by E1izabeth** [comment]
Could you check if the font chosen as Main font in DBeaver installed in your PC? It's in Personalization -> Fonts settings on Windows
![image](https://github.com/dbeaver/dbeaver/assets/28875055/d58fd462-b66f-4b8c-8978-11d1a1dc27a1)

**Comment by edsonrodsilva** [comment]
Hi,

The fonts are installed in the operating system,
Whichever source I choose the problem persists.

![Screenshot-2023-05-31-141527](https://github.com/dbeaver/dbeaver/assets/2845966/8472fdeb-374a-4061-9133-5e7157bf653f)

**When changing the font, the table names were ok, only the names indicated in the print below are valid.**

![Screenshot-2023-05-31-101331](https://github.com/dbeaver/dbeaver/assets/2845966/77d106a9-acff-4c5d-b34c-db8b0824e285)

**Comment by E1izabeth** [comment]
Thank you for checking.

**Comment by ShadelessFox** [comment]
Hello @edsonrodsilva,

Please try the "Reset UI settings" feature:

https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings

Please let me know if it helps.

**Comment by edsonrodsilva** [comment]
I just did the test above and to not work!
But I just found out that it only happens with the dark theme.
In the classic theme everything is 100%.

I switched to the classic theme and it's ok.

see the print...

![image](https://github.com/dbeaver/dbeaver/assets/2845966/254fad66-1d3c-4836-873b-48b1d2f0b59a)

**Comment by E1izabeth** [comment]
Thank you for investigation

**Comment by edsonrodsilva** [comment]
Thank you for your help!

**Comment by edsonrodsilva** [comment]
it was solved by switching to classic theme
