### ISSUE TITLE
DBeaver ignores default values for GreenPlum functions

### ISSUE THREAD

**Issue by euroxes** [dbeaver/dbeaver#20139]
### Description

When viewing into DDl of the GreenPlum functions, the DEFAULT keyword isn't generated for parameters

### DBeaver Version

Enterprise Edition 23.0.0. & Enterprise Edition 23.1.0

### Operating System

Windows Server 2019

### Database and driver

GreenPlum drivers based on Postgres 14 binaries

### Steps to reproduce

Double click on the function

or 

Genrerate DDL for a function

**Comment by LonwoLonwo** [comment]
Hello @euroxes 
Please provide an original function DDL example with DEFAULT keywords.

**Comment by euroxes** [comment]
```
CREATE OR REPLACE FUNCTION func(parameter1 integer DEFAULT 9)
	RETURNS varchar
	LANGUAGE plpgsql
	VOLATILE
AS $$
		
DECLARE
BEGIN
	RAISE NOTICE 'message text';
	return 1;
END;
```

**Comment by LonwoLonwo** [comment]
Thanks for the report.
