### ISSUE TITLE
TimescaleDB - there is still old icon of TimescaleDB in DBeaver

### ISSUE THREAD

**Issue by igor2x** [dbeaver/dbeaver#20148]
### Description

TimescaleDB has rebranded and it introduced new icon. There is still old icon in DBeaver.

### DBeaver Version

Community Edition 23.0.5

### Operating System

Windows 10

### Database and driver

Not applicable.

### Steps to reproduce

1. Database | New Database Connection.
2. Search for TimescaleDB and the following old icon is displayed (the problem):
![image](https://github.com/dbeaver/dbeaver/assets/10895030/cfa511db-6d8c-492a-92d5-abe4bae778e7)
3. Then fill in database connection info and in **Database Navigator** is displayed smaller version of this icon (related problem).
![image](https://github.com/dbeaver/dbeaver/assets/10895030/1f0d9421-1115-4394-9d3d-8a2ce564dd83)

See the official TimescaleDB page at https://www.timescale.com/blog/announcing-the-new-timescale/ where it rolls gif image between the two:
![image](https://github.com/dbeaver/dbeaver/assets/10895030/b325667f-80f4-4e62-9656-d3f52cff6bea)
![image](https://github.com/dbeaver/dbeaver/assets/10895030/d57e37e9-d8c2-4c12-b586-284bd666b9a8)

**Comment by E1izabeth** [comment]
Thank you for the request.

**Comment by E1izabeth** [comment]
@igor2x do you know if the new icon is available to download from somewhere?

**Comment by igor2x** [comment]
I have upgraded DBeaver to 23.1.4.202308061552 on Windows 10 and now I see both images where updated:
- step 2:
![image](https://github.com/dbeaver/dbeaver/assets/10895030/1508361b-a0e8-4d84-9a55-6ab4527d8b98)
- step 3:
![image](https://github.com/dbeaver/dbeaver/assets/10895030/7c13ed42-a46a-4337-a4f1-fbe5817e7f74)

I am closing the issue.

**Comment by E1izabeth** [comment]
Thank you for update.
