### ISSUE TITLE
PostgreSQL Table > Import Data -> CSV -> File Chooser opens twice

### ISSUE THREAD

**Issue by aamsur-933** [dbeaver/dbeaver#20146]
### Description

Importing a CSV causes the file chooser for the CSV file to open twice -- after selecting the CVS , the chooser appears again

### DBeaver Version

Version 23.0.5

### Operating System

Ubuntu 20.04.6

### Database and driver

Postgres JDBC

### Steps to reproduce

- right click on Table Name -> Import Data -> CSV -> [Next]
- file chooser opens -> select CSV file -> [Open]
- file chooser opens again

### Additional context

this issue #9780 seem appears again on recent dbeaver version.

**Comment by LonwoLonwo** [comment]
Hello @aamsur-933 

Could you please check the latest DBeaver version?
I can't reproduce it, unfortunately.

**Comment by aamsur-933** [comment]
hello @LonwoLonwo, thanks for reply. 

I have updated my dbeaver, currently i am using dbeaver 23.0.5 and the problem still exists,
i can confirm, some of my teams are having the same issue, in ubuntu 20.04 with recent dbeaver version.

**Comment by aamsur-933** [comment]
i also confirmed the problem still exists in ubuntu 18.04 with dbeaver 23.1.0

**Comment by Matvey16** [comment]
@aamsur-933 Thank you for the report

Reproduced on Ubintu 22.04
