### ISSUE TITLE
Auto completion does not work if table name has space Reoccured was fixed in #10858

### ISSUE THREAD

**Issue by NehalDamania** [dbeaver/dbeaver#20164]
### Description

If the table name contains space, the auto completion does not work.
for example: if the table name is file list then
when we type the query

select * from `file list` fl where fl.
-- here the autocompletion does not work after the dot
If the table name does not have any spaces, then autocompletion works perfectly.

### DBeaver Version

Community Edition 23.0.5

### Operating System

Windows 11

### Database and driver

1. Mariadb 10

### Steps to reproduce

Create any table in mariadb or mysql with space
Try any query on the table and the autocompletion or suggestion of columns for that table won't work. Please check the gif below.
Autocompletion works perfectly for table tabRole, but doesn't work for table tabHas Role

![image](https://user-images.githubusercontent.com/1287731/103498318-56852b80-4e6a-11eb-9d97-16bcf17bc642.gif)

### Additional context

This issue was first reported few years back as #10858 and it was fixed. In the latest build it has reoccurred. Hence copying all the details from previous issue

**Comment by LonwoLonwo** [comment]
Hello @NehalDamania 

Thanks for the bug report.

![2023-06-01 11_27_32-](https://github.com/dbeaver/dbeaver/assets/45152336/8890ef7d-301c-4209-973c-7fd0495ffb0c)

This bug has already been fixed here https://github.com/dbeaver/dbeaver/issues/20073

The fix will be available on Monday with release 23.1.0

**Comment by E1izabeth** [comment]
As a temporary workaround you can uncheck this setting
![image](https://github.com/dbeaver/dbeaver/assets/28875055/ec6ee723-ed5f-4dca-80fa-b97c7d8325c1)

**Comment by NehalDamania** [comment]
Thank you so much for the workaround
