### ISSUE TITLE
SQL Editor Ability to Scroll Past the bottom

### ISSUE THREAD

**Issue by faabiopontes** [dbeaver/dbeaver#20185]
### Description

I often find myself adding blank lines at the bottom of the sql editor just so I can scroll down such that my last line is in the middle of the editor rather than the bottom of the editor. Can you make it so that you can scroll past the bottom until the last line is at the top of the screen? (See Sublime 3 or VS Code if you need an example of how the proposed feature should work).

Many text editors allow for the user to scroll past the last line of the editor but I am unable to find any setting to allow me to do this.

It would be nice to have this feature in the SQL Script editor window.

cc: @zkirkland, @uslss, @HerCerM

Related to https://github.com/dbeaver/dbeaver/issues/7631 which was closed wrongfully since it's not related to #10950 
Also related to [SQL Editor Ability to Scroll Past the bottom](https://dbeaver.io/forum/viewtopic.php?f=3&t=1758&sid=33a949de46e0666c85bdd1cfceb78201) forum post which was locked without answers.

### DBeaver Version

Community Edition 23.0.1

### Operating System

Ubuntu

### Database and driver

Mysql 5.7, happens with other DBs

### Steps to reproduce

1. Open new SQL Editor
2. Write queries until you are on the bottom of the screen
3. You are not able to scroll past the last lines (like Sublime 3, VS Code, etc)
4. Only way to currently do this is by adding blank lines to the end

**Comment by ShadelessFox** [comment]
Hello @faabiopontes,

Thank you for your request.

Unfortunately, it's impossible due to the limitations of the Eclipse platform.

Please see https://stackoverflow.com/a/2197946 for a technical explanation.
