### ISSUE TITLE
View Preview does not double-quote when convenient (ex : Snowflake + greek letter)

### ISSUE THREAD

**Issue by Thomas-LEILLET-Sanofi** [dbeaver/dbeaver#20187]
### Description

Tested in Snowflake - As a test, let's create a VIEW (SELECT 1), in a schema named with a greek letter, like that : 

`CREATE SCHEMA "ΣTEST";
CREATE VIEW "ΣTEST".VTEST AS SELECT 1 AS DUMMY;`

whereas the call is OK in DBeaver if done properly,
`SELECT * FROM "ΣTEST".VTEST `

...the default preview shows an error because the script generated for the preview does not double-quote (which is here mandatory to handle special characters)
`SELECT * FROM <my_db>.ΣTEST.VTEST
LIMIT 200`

![image](https://github.com/dbeaver/dbeaver/assets/130557869/10d1a7d2-7d94-4ea4-a575-c7bc9130e854)

Is this something to be fixed or is there a feature in the settings to force double-quoting DB/Schema/Object name ?

### DBeaver Version

23.0.4.202305071722

### Operating System

Win11

### Database and driver

Snowflake

### Steps to reproduce

Tested in Snowflake - As a test, let's create a VIEW (SELECT 1), in a schema named with a greek letter, like that : 

`CREATE SCHEMA "ΣTEST";
CREATE VIEW "ΣTEST".VTEST AS SELECT 1 AS DUMMY;`

whereas the call is OK in DBeaver if done properly,
`SELECT * FROM "ΣTEST".VTEST `

...the default preview shows an error because the script generated for the preview does not double-quote (which is here mandatory to handle special characters)
`SELECT * FROM <my_db>.ΣTEST.VTEST
LIMIT 200`

![image](https://github.com/dbeaver/dbeaver/assets/130557869/10d1a7d2-7d94-4ea4-a575-c7bc9130e854)

Is this something to be fixed or is there a feature in the settings to force double-quoting DB/Schema/Object name ?

**Comment by flambchap** [comment]
Thank you for the report.
