### ISSUE TITLE
[DB2] Show duplicates only doesn't work in Grouping panel

### ISSUE THREAD

**Issue by rroliee** [dbeaver/dbeaver#20197]
### Description

Show duplicates only doesn't work in Grouping panel because the generated sql uses alias in having section, which is not supported by DB2. Count(*) should be used instead of count_.

Example generated sql:
SELECT A, B, COUNT(*) AS count_ FROM AB.CD x
GROUP BY A, B
HAVING count_ > 1

Resulting error:
SQL Error [42703]: COUNT_ IS NOT VALID IN THE CONTEXT WHERE IT IS USED. SQLCODE=-206, SQLSTATE=42703, DRIVER=4.31.10

### DBeaver Version

Community edition 23.1.0.202306041918

### Operating System

Win 10

### Database and driver

DB2 10
Driver: 11.5.7.0

### Steps to reproduce

1. Create a groupping on groupping pane
2. Click Show duplicates only button

**Comment by LonwoLonwo** [comment]
Hello @rroliee 

I can't reproduce it for DB2 LUW.

And we have a special condition for this case:

https://github.com/dbeaver/dbeaver/blob/0d22eeead97734858fbc10b8ab8eec66800c641d/plugins/org.jkiss.dbeaver.ext.db2/src/org/jkiss/dbeaver/ext/db2/DB2SQLDialect.java#L167-L170

What provider do you use?

![2023-06-05 11_10_52-Window](https://github.com/dbeaver/dbeaver/assets/45152336/5e4af761-327a-4d17-b220-1ac9fe0552d0)

**Comment by rroliee** [comment]
Hello @LonwoLonwo 

I use DB2 for z/OS provider.

**Comment by LonwoLonwo** [comment]
Thanks for the answer and for the bug report!

**Comment by LonwoLonwo** [comment]
The issue has been fixed and will be available in release 23.1.1.

Could you please check it in our [Early Access version](https://dbeaver.io/files/ea/)?

**Comment by rroliee** [comment]
I've checked in the Early Access version and it is working! :)

Thank you!

**Comment by LonwoLonwo** [comment]
Thanks for the answer!
