### ISSUE TITLE
[mariaDb] "No database selected" error when executing delete with join

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#20208]
### Description

Executing this query

```
delete t1 from table1 t1
inner join table2 t2
where t1.id = t2.id
```

returns error

```
SQL Error [1046] [3D000]: (conn=1498) No database selected
```

while in other GUIs/clients, it works perfectly.

DBe CE Version 23.0.5.202305211610 AND Version 23.1.0.202306041918
MariaDb 10.3.36

### DBeaver Version

CE 23.0.5.202305211610 AND 23.1.0.202306041918

### Operating System

macosx

**Comment by wiwwo** [comment]
No need to create the tables to check the script, just connect to a DB instance, and run it

**Comment by wiwwo** [comment]
From mariadb client ( `mysql` ) :

```
> create table table1 (id int);
Query OK, 0 rows affected (0.03 sec)

> create table table2 (id int);
Query OK, 0 rows affected (0.02 sec)

> delete t1 from table1 t1 inner join table2 t2 where t1.id = t2.id;
Query OK, 0 rows affected (0.01 sec)


```

**Comment by E1izabeth** [comment]
Is database chosen here or you see N/A like on the picture when this error appears?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/88d82420-e21e-4b0b-bea1-a84a60110c17)

**Comment by wiwwo** [comment]
Yes, and it does not matter:

```
delete t1 from meh.table1 t1
inner join meh.table2 t2
where t1.id = t2.id
```
Still gives error

**Comment by LonwoLonwo** [comment]
So, do you want to execute your query without a default catalog? But what is the reason for that specific behavior? Why can not you choose the default catalog for the script?

**Comment by wiwwo** [comment]
Look,
that is a bug. Either you fix it or not.
Me selecting the db, or using a default catalog does not change that.
I am here to help, so - again- fix it or not :-)

**Comment by E1izabeth** [comment]
@wiwwo 
We're trying to understand steps to reproduce, but we can't do it without your help. Am I correctly understood, that you see this error no matter what's chosen on the main toolbar?

**Comment by wiwwo** [comment]
Exactly.
I was already using the DB when the error occurred, without any problem

**Comment by wiwwo** [comment]
And sorry for the misunderstanding :-)

**Comment by ShadelessFox** [comment]
Hello @wiwwo,

Which driver are you using? You only mentioned the server version.

**Comment by wiwwo** [comment]
Hello @ShadelessFox 
It happened with DBE CE 23.0.5.202305211610 AND 23.1.0.202306041918, so I assume it is irrelevant.
Did you try to reproduce the error executing the query I posted in the bug report detail? One does not need to create the tables, as detailed here https://github.com/dbeaver/dbeaver/issues/20208#issuecomment-1577990823

**Comment by ShadelessFox** [comment]
No, we were unable to reproduce your issue.

Please provide the **driver's name and version**. It can be looked up when performing a connection test.

**Comment by E1izabeth** [comment]
Could you share your connection information showing in the Connection test dialog?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/1703e2bc-e557-4dc1-8952-6f2d2a0012a6)

Also it would be extremely useful if you could record a video showing how it doesn't work for you as none of our team able to reproduce the issue. The order of clicks may be very important for us, even if you think that you're doing the things as usual.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by cooldev23** [comment]
> Is database chosen here or you see N/A like on the picture when this error appears? ![image](https://private-user-images.githubusercontent.com/28875055/243581327-88d82420-e21e-4b0b-bea1-a84a60110c17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2OTc1NjMsIm5iZiI6MTcxNDY5NzI2MywicGF0aCI6Ii8yODg3NTA1NS8yNDM1ODEzMjctODhkODI0MjAtZTIxZS00YjBiLWJlYTEtYTg0YTYwMTEwYzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDAwNDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMTdmZTQyNmMzYjA3YmFjMWY3YTY1NzViMjE2NGRlN2IwNzUxNmJkYjE0ZTRhNzNkYmI2NTNjZGJlMzUxOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7iKMpU0T0rps6Czd38q5Ys87bsl8NKrKwnKBgKrkvX8)

Thanks you, choosing the database from the dropdown in the image fixed it for me!
