### ISSUE TITLE
Windows store version - can't find JDK/JRE error

### ISSUE THREAD

**Issue by JonrGull** [dbeaver/dbeaver#20211]
### Description

Updated DBeaver today via the Microsoft store and was met with this error when I tried to start it up.
![image](https://github.com/dbeaver/dbeaver/assets/25947147/a3182864-4c65-463a-8cc0-d50a644ff720)

I've tried rebooting and reinstalling the app in an attempt to fix it. The `.exe` version works fine.

Anyone else have this problem or a solution?

### DBeaver Version

23.1.0

### Operating System

Windows 11

### Database and driver

N/A. Can't open app.

### Steps to reproduce

1. Update DBeaver from Microsoft Store
2. Open DBeaver

**Comment by E1izabeth** [comment]
Thank you for bug report

**Comment by hazbu** [comment]
Same here, i using windows 10, i updated the app today, when i open the app noting happen, even splash screen or warning dont show

**Comment by alassedy** [comment]
Me too!
I'm using Windows 10 and I'm getting this error:
![image](https://github.com/dbeaver/dbeaver/assets/12068755/ff1fc1e2-0e99-4e31-abfe-c0e51f14f499)

**Comment by treysis** [comment]
Same here, Windows 10, MSStore version. Unfortunately, MSStore doesn't have options to downgrade. When can we expect a fix?

**Comment by miguellira** [comment]
This issue came up before with a previous release of DBeaver on the Microsoft Store (#18960).

For me the fix was to modify my registry and point my JRE to an updated JDK: https://github.com/dbeaver/dbeaver/issues/18960#issuecomment-1422646908

It was eventually fixed in a subsequent Microsoft Store release, however, it may take a while for the developers to fix and publish a new build. Good luck!

**Comment by treysis** [comment]
@miguellira Thx for the tip. Last time it happened I was out of office so I didn't encounter it.
The registry workaround is no good because it requires administrative rights (access to HKLM), unfortunately.

Hope this won't take **3 weeks to fix** like last time 🙄 This should warrant an intermediate update, like 23.1.0.1 or so...

**Comment by stevenwong** [comment]
Seems to be an issue with relative path. Java that comes with dbeaver is in `C:\Program Files\WindowsApps\DBeaverCorp.DBeaverCE_23.1.0.0_x64__1b7tdvn0p0f9y\jre\jre\bin`. Notice the double `jre`

**Comment by aresofficial** [comment]
The solution for now: install https://aka.ms/download-jdk/microsoft-jdk-17.0.7-windows-x64.msi

**Comment by treysis** [comment]
@aresofficial That doesn't work! It requires admin rights!!

**Comment by aresofficial** [comment]
> @aresofficial That doesn't work! It requires admin rights!!

yes, unfortunately there is no way to fix it without admin rights / access to regedit

**Comment by miguellira** [comment]
@treysis unfortunately, all workarounds, whether installing a JDK or editing your registry to point to an existing one will require admin rights.

If you don’t have admin rights, you’d have to wait for a future release that will address this issue. Good luck.

**Comment by treysis** [comment]
> If you don’t have admin rights, you’d have to wait for a future release that will address this issue. Good luck.

Exactly. And this should be pointed out. And like I said: **I hope it won't take again 3 weeks** until the release of 23.1.1.

**Comment by stevenwong** [comment]
For now I've just installed the one off the website. https://dbeaver.io/download/

**Comment by treysis** [comment]
@stevenwong Does it retain the settings/database connections from the MSStore version?

**Comment by stevenwong** [comment]
@treysis hmmm I uninstalled the app store version and installed this. It didn't retain the connections. Not sure if there's a way of preserving the settings.

**Comment by GJAlter** [comment]
https://github.com/dbeaver/dbeaver/issues/18960#issuecomment-1421941031
This Solution is Work!

**Comment by serge-rider** [comment]
MS Store version was fixed. Please try to re-download it.

**Comment by JonrGull** [comment]
@serge-rider Works fine now! Thank you so much for the quick fix!

**Comment by Roshang2003** [comment]
> MS Store version was fixed. Please try to re-download it.

But will it regain my previous databases ?

**Comment by Roshang2003** [comment]
> [#18960 (comment)](https://github.com/dbeaver/dbeaver/issues/18960#issuecomment-1421941031) This Solution is Work!

Is it really working, like don't need any admin right ?

**Comment by serge-rider** [comment]
Yes, it is really working. All you connection configuration will work in the new version
