### ISSUE TITLE
New connection wizard displays an empty window at the settings step

### ISSUE THREAD

**Issue by fgiraldi** [dbeaver/dbeaver#20229]
### Description

Platform: Macbook Pro - Intel i7 - MacOS Ventura 13.4
When trying to create a new connection, after picking any driver I get stuck with an empty window where the settings should be presented.
![image](https://github.com/dbeaver/dbeaver/assets/32184202/5f16097f-0740-4050-ae0e-274f5737022b)

### DBeaver Version

Community Edition Version 23.1.0.202306041918

### Operating System

MacOS Ventura 13.4

### Database and driver

All of them

### Steps to reproduce

1. Click on File -> New -> Database Connection
2. Pick any driver and click Next
3. Here I witnes some mouse pointer change but no result. Clicking Next again takes me to next screen
4. The Connection Settings window show up but it is empty. Not a single settings is provided

### Additional context

I already tried versions 22 and 21 of dBeaver with same result.
Attaching a log I got from terminal where some exceptions were logged
[dbeaver_log_1.log](https://github.com/dbeaver/dbeaver/files/11677492/dbeaver_log_1.log)

**Comment by ShadelessFox** [comment]
Hello @fgiraldi,

The fix is postponed to the next version, which will be released in two weeks. Please see #19673

As a workaround, move DBeaver window to your MacBook's primary display and create new connections there.

**Comment by fgiraldi** [comment]
Thanks @ShadelessFox !!! It totally fixed my issue! It's the dual display setup the one to blame.

**Comment by mdgbd** [comment]
@ShadelessFox if I use my laptop monitor I can see the screen like you said, but the new db connection disappear after I click "finish"

**Comment by ShadelessFox** [comment]
@mdgbd please create a new ticket with footage showing your issue.

**Comment by mdgbd** [comment]
https://github.com/dbeaver/dbeaver/issues/20720
