### ISSUE TITLE
当使用dbeaver社区最新版本连接带有Kerberos的浪潮云大数据集群下的Hive、Spark 时报错 

### ISSUE THREAD

**Issue by 172151295** [dbeaver/dbeaver#20221]
希望能够支持带有Kerberos的大数据集群连接HIVE或者Spark,可配置租户名及秘钥文件等选项

**Comment by E1izabeth** [comment]
Please, translate it into English

**Comment by E1izabeth** [comment]
Unfortunately, it's hard to understand what do you mean here with automatic translation.
You write about some connection parameters you need to support, but I'm not sure that I translated it correctly. 

In the title you write that there is an error on connection in the latest version. Does it worked in older versions or it's your first setup? Could you send the error message? It may be a screenshot or you may send us the log files (https://dbeaver.com/docs/wiki/Log-files/)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
