### ISSUE TITLE
Importing data with date values into tables

### ISSUE THREAD

**Issue by dariopnc** [dbeaver/dbeaver#2022]
When importing date values into tables from CSV connections input values are always interpreted as strings and the conversion to date values is prone to errors caused by locales.

It would be great to be able to specify on the go the input data type and, especially for dates/timestamps, the actual format

**Comment by ckljohn** [comment]
I don't get any error, but the date fields become null after the import.
(I am importing to Oracle)

**Comment by ZeroHager** [comment]
Hi,
I'm importing a CSV file with date values, I have the dates with this format dd-mm-rrrr in the CSV file, but when I try to import the file, dbeaver missunderstand the format and read the dates in a wrong way like mm-dd-rrrr, is there a way to cast the format for date values?.

I am importing to oracle.

Thank for your time.

**Comment by serge-rider** [comment]
@ZeroHager  very good point. We'll add date/time format configuration in 6.0:

![image](https://user-images.githubusercontent.com/6398845/54069038-5e6ee700-4264-11e9-84a5-6a8fde614507.png)

**Comment by serge-rider** [comment]
@ckljohn  Also the same can be accomplished with standard CSV driver + date/time fomrat configuring in driver properties.

**Comment by ZeroHager** [comment]
> @ZeroHager very good point. We'll add date/time format configuration in 6.0:
> 
> ![image](https://user-images.githubusercontent.com/6398845/54069038-5e6ee700-4264-11e9-84a5-6a8fde614507.png)

Thanks @serge-rider, I'm happy now!!!

**Comment by uslss** [comment]
verified
