### ISSUE TITLE
Database is Locked, DML-Statements Possible

### ISSUE THREAD

**Issue by vermgit** [dbeaver/dbeaver#20238]
### Description

All tables get the lock-symbol in the top left corner of the grid, reconnecting or restarting DBeaver doesn't help. The cells are obviously read-only.

In the script-editor I can still execute DML-statements normally and commit them. Reloading the grid then shows the changes.

### DBeaver Version

Community Edition 23.1.0.202306041918

### Operating System

Windows 11

### Database and driver

Oracle Database 11g Release 11.1.0.6.0 - Production
PL/SQL Release 11.1.0.6.0 - Production             
CORE 11.1.0.6.0 Production                         
TNS for Linux: Version 11.1.0.6.0 - Production     
NLSRTL Version 11.1.0.6.0 - Production             

### Steps to reproduce

Don't know what's causing it.

### Additional context

When I log in as SYSDBA and check the locks with DBeaver, that view is empty.

Similar to #15229

**Comment by LonwoLonwo** [comment]
Hello @vermgit 

Please check this toolbar element. Does it unlock?

![2023-06-08 19_40_43-DBeaver Ultimate 23 1 0 - Album](https://github.com/dbeaver/dbeaver/assets/45152336/7a45bb90-9458-4149-a8b5-1ca811efa235)

**Comment by vermgit** [comment]
That showed the same unlocked state. I clicked it twice, it reconnected twice, but no change. However, I got this instead:

```
ALTER SESSION SET OPTIMIZER_FEATURES_ENABLE='10.2.0.5'

[96] ORA-00096: invalid value 10.2.0.5 for parameter optimizer_features_enable, must be from among 11.1.0.6.1, 11.1.0.6, 10.2.0.4, 10.2.0.3, 10.2.0.2, 10.2.0.1, 10.1.0.6, 10.1.0.5, 10.1.0.4, 10.1.0.3, 10.1.0, 9.2.0, 9.0.1, 9.0.0, 8.1.7, 8.1.6, 8.1.5, 8.1.4, 8.1.3, 8.1.0, 8.0.7, 8.0.6, 8.0.5, 8.0.4, 8.0.3, 8.0.0
```

**Comment by LonwoLonwo** [comment]
Could you please disable this setting in your connection settings and try to reconnect?

![2023-06-08 20_31_39-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/1d14522b-e6bd-42c1-aaab-493f981d9fd3)

**Comment by vermgit** [comment]
I disabled it, but nothing changed. I also clicked on the lock icon just to see if it helps, but sadly not.

I see a new error now:

```
SELECT
    c.TABLE_NAME,
    c.CONSTRAINT_NAME,
    c.CONSTRAINT_TYPE,
    c.STATUS,
    c.SEARCH_CONDITION,
    (
      SELECT LISTAGG(COLUMN_NAME || ':' || POSITION,',') WITHIN GROUP (ORDER BY "POSITION") 
      FROM ALL_CONS_COLUMNS col
      WHERE col.OWNER ='owner' AND col.TABLE_NAME = 'table_name' AND col.CONSTRAINT_NAME = c.CONSTRAINT_NAME GROUP BY CONSTRAINT_NAME 
    ) COLUMN_NAMES_NUMS
FROM
    ALL_CONSTRAINTS c
WHERE
    c.CONSTRAINT_TYPE <> 'R'
    AND c.OWNER = 'owner'
    AND c.TABLE_NAME = 'table_name'

[923] ORA-00923: FROM keyword not found where expected
```

**Comment by LonwoLonwo** [comment]
Could you please check this query in your SQL Editor? Does it produce the same error?

**Comment by LonwoLonwo** [comment]
Also, could you please provide your driver version? You can find it in your connection settings -> Test connection.

**Comment by vermgit** [comment]
Yes, the same error occurs in the SQL Editor in line 8 where "GROUP" of "WITHIN GROUP" is underlined.

Server: Oracle Oracle Database 11g Release 11.1.0.6.0 - Production
Driver: Oracle JDBC driver 12.2.0.1.0

**Comment by LonwoLonwo** [comment]
Could you please enable this setting and try again?

![2023-06-15 20_34_50-Window](https://github.com/dbeaver/dbeaver/assets/45152336/aebf81aa-bf52-49fa-85b7-d2e7b22fcf60)

**Comment by vermgit** [comment]
Oh nice. Now the lock symbol is gone and also no failing internal queries. Things are looking normal now.

Thanks!

BTW, out of curiosity I changed back those two checkboxes in the Oracle properties and the lock appeared again. Setting them to the new states the lock is gone. So it looks like something in that area fixed it.
