### ISSUE TITLE
Autocomplete using (Oracle) table alias does not work

### ISSUE THREAD

**Issue by swanknight** [dbeaver/dbeaver#20232]
### Description

Autocomplete using Oracle table's alias is not working at all in the latest version (23.1.0). 
I downgraded to (22.3.5) and it worked fine.

### DBeaver Version

Community Edition 23.1.0

### Operating System

Windows 10

### Database and driver

Oracle OJDBC8-Full

**Comment by E1izabeth** [comment]
Please, provide an example of query to reproduce your issue.

**Comment by swanknight** [comment]
> Please, provide an example of query to reproduce your issue.

I'm not sure how to describe it.

```
SELECT t.<Press Control+Space and NOTHING HAPPENS>
FROM table t
```

**Comment by E1izabeth** [comment]
That works for me.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/57f652be-f05d-4d9e-b511-89ceaa735dde)

**Comment by swanknight** [comment]
> That works for me. ![image](https://user-images.githubusercontent.com/28875055/244292735-57f652be-f05d-4d9e-b511-89ceaa735dde.png)

I'm not sure what's going on, as I mentioned, version 23.1.0 didn't work, I downgraded to 22.3.5 and everything worked fine. Same database, connection, and query.

**Comment by E1izabeth** [comment]
The previous version was 23.0.5. Is it a typo or you downgraded to a more older version than the previous one?

We switched to the new autocompletion engine in 23.0.5, but you can return back usage of previous one by unchecking this setting.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/c5630699-9998-4a9d-b8c9-7ce742c3a6c6)

**Comment by swanknight** [comment]
> The previous version was 23.0.5. Is it a typo or you downgraded to a more older version that the previous one?
> 
> We switched to the new autocompletion engine in 23.0.5, but you can return back usage of previous one by unchecking this setting. )

Not a typo, I'm currently using version 22.3.5. I'll try to upgrade again and disable that option later, can't test it right now, though.

**Comment by E1izabeth** [comment]
Is it possible that autocompletion just takes too long for your database? Is it big enough? Could you reproduce it again and wait a little bit after autocompletion request?

And thank you for bug report.

**Comment by swanknight** [comment]
> Is it possible that autocompletion just takes too long for your database? Is it big enough? Could you reproduce it again and wait a little bit after autocompletion request?
> 
> And thank you for bug report.

No, that's not it. Sorry, I wasn't clear enough. Something does happen, it says "No proposals".

**Comment by arhayka** [comment]
@swanknight Can you please provide footage showing your issue? Thank you.

**Comment by swanknight** [comment]
> @swanknight Can you please provide footage showing your issue? Thank you.

That might be difficult since it's on a work PC. In any case, I'll have to wait till Sunday to try anything.

**Comment by Trisk3lion** [comment]
Hello, just wanted to chime in that I have also had problems with auto-completion with the latest DBeaver "23.1.0.202306041918".

Sometimes I get completions and sometimes not, and sometimes it seems like it just takes a lot of time.
I'm using DBeaver against a large DB2 z/OS database. 

But removing the checkbox for "Experimental features" makes it work like before again (which has been working great for me).

**Comment by swanknight** [comment]
> We switched to the new autocompletion engine in 23.0.5, but you can return back usage of previous one by unchecking this setting. 

I just tested it, and I can confirm that after disabling "Experimental features", the autocomplete is working again.

**Comment by E1izabeth** [comment]
Does this issue is still actual for the latest DBeaver version (23.1.1)?

**Comment by swanknight** [comment]
> Does this issue is still actual for the latest DBeaver version (23.1.1)?

Sorry, I have no way to test at the moment, and won't be able to for quite some time. 
Perhaps @Trisk3lion can help?

**Comment by Trisk3lion** [comment]
Hi again!

I still have problem with the completion when "Enable experimental features" is on when running 23.1.1. 
It is mainly (maybe only) when completing table names. 

One example of what happens is that when I'm writing a query like below and stop typing when the cursor is at |:
```
SELECT *
FROM TFT100|
```
Then nothing happens for a few seconds, and suddenly I get a completion for ALL the tables in the schema (I have set a default schema so I don't have to type it out), and the completion seems to be sorted on "T" but no filtering, I have ALL tables in the completion popup.

Then if I write one more character after the completion pops up, for example:
```
SELECT *
FROM TFT100X|
```

Then the completion gets filtered and narrows on "TFT100X", but not before I type the X. So it seems to me that the completion engine is fetching ALL tables as soon as I pressed a SPACE after "FROM" and then it runs while I type "TFT100" and doesn't filters or narrows on that.

When I turn "Enable experimental features of" the completion pops up as soon as I type "T" after "FROM" and then gets filtered and narrows as I type more letters in the table name.

**Comment by E1izabeth** [comment]
Thank you for update.

**Comment by E1izabeth** [comment]
Could you check if the issue is still reproducible on the latest DBeaver version with "Enable experimental features" on?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by vicpermir** [comment]
I confirm autocomplete still does NOT work with Oracle and table aliases.

- DBeaver Community 24.0.0.202403091004
- Oracle JDBC driver (oracle_thin) [oracle.jdbc.OracleDriver] 23.2.0.0
- Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0

![experimental_features_enabled](https://github.com/dbeaver/dbeaver/assets/24521091/ef6ddcb1-3ac4-4065-8e3d-317aaf4521f7)

Disabling "Enable experimental features" fixes the issue.

![experimental_features_disabled](https://github.com/dbeaver/dbeaver/assets/24521091/b7960ece-730a-4558-9fdb-72d1400fd665)
