### ISSUE TITLE
MariaDB data update - Bulk edit is invalid

### ISSUE THREAD

**Issue by wordgao** [dbeaver/dbeaver#20243]
### Description

系统:Ubuntu 20.04.3 LTS x86_64(Py3.7.9)  20.4 MariaDB 10.7.3
驱动：MariaDB Connector/J [3.0.7]

脚本演示代码
数据库中包含 多条-商品库存 *5条 或*10条商品库存
```mysql
update tb_sku set moq=15000 WHERE productModel='商品库存';
update tb_sku set spq=75000 WHERE productModel='商品库存';
```
ctrl+enter 执行上面的2段代码，

```mysql
Updated Rows	6
Query	update tb_sku set spq=75000 WHERE productModel='商品库存'
Start time	Fri Jun 09 09:30:43 CST 2023
Finish time	Fri Jun 09 09:30:43 CST 2023
```

结果：代码执行后返回结果正常，无异常的报错提示，也能显示出正确的修改数据行数。

# 但数据库中的值并未改变，是否有事务未提交？
# 存在部分修改成功后的值，数据修改不完整，或遗漏的情况。

### DBeaver Version

23.1.0

### Operating System

Ubuntu 20.04.3 LTS x86_64(Py3.7.9)

### Database and driver

MariaDB Connector/J [3.0.7]

### Steps to reproduce

update tb_sku set moq=15000 WHERE productModel='商品库存';
update tb_sku set spq=75000 WHERE productModel='商品库存';

**Comment by LonwoLonwo** [comment]
Hello @wordgao 

Please, translate your text into English.

**Comment by wordgao** [comment]
Description
System: Ubuntu 20.04.3 LTS x86_ 64 (Py3.7.9) 20.4 MariaDB 10.7.3
Driver: MariaDB Connector/J [3.0.7]
Script Demo Code
The database contains multiple items -5 or 10 items in stock
```mysql
Update tb_sku set moq=15000 WHERE productModel='Product Inventory';
Update tb_sku set spq=75000 WHERE productModel='Product Inventory';
```
Ctrl+enter executes the above two sections of code,
```mysql
Updated Rows 6
Query update tb_sku set spq=75000 WHERE productModel='Product Inventory'
Start time Fri Jun 09 09:30:43 CST 2023
Finish time Fri Jun 09 09:30:43 CST 2023
```
Result: After code execution, the returned result is normal, without any abnormal error prompts, and the correct number of modified data rows can also be displayed.
But the values in the database have not changed, are there any transactions that have not been committed?
There are situations where some successfully modified values, incomplete data modifications, or omissions exist.

**Comment by wordgao** [comment]
MariaDB update batch modification is invalid

**Comment by Matvey16** [comment]
@wordgao I see in you result message that only the second statement was executed.
THe finish message should show both queries
![image](https://github.com/dbeaver/dbeaver/assets/82543000/33699885-cac9-4c7c-a1dd-28dbe675e057)

Did you execute them by pressing ctrl+enter at the end of the script?
That would only execute the last query.

To execute both you need to either use Alt+X or higlight both of them before pressing ctrl+enter like so
![image](https://github.com/dbeaver/dbeaver/assets/82543000/52c3f947-29b4-463f-8cd1-1c49ae99ab73)

Be mindful though that MariaDB doesn't allow multiple queries by default so you would need to change driver properties in connection settings and set `allowMultiQueries` to true

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
