### ISSUE TITLE
Export Boolean

### ISSUE THREAD

**Issue by yoili1** [dbeaver/dbeaver#20241]
### Description

When a boolean field uses lowercase true false, on csv export it exports as TRUE FALSE  and then import doesn't work

### DBeaver Version

23.1.0

**Comment by LonwoLonwo** [comment]
Hello @yoili1

Please provide:

- a CSV file example
- Database name and driver version
- Target table DDL
- And import error text

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still actual for you - feel free to reopen it.
