### ISSUE TITLE
uncomfortable dark theme with system

### ISSUE THREAD

**Issue by Oliver-GMJ** [dbeaver/dbeaver#20242]
### Description

In a SQL Script or other code editor(such as function).
Words can't read clearly, like this image.
![image](https://github.com/dbeaver/dbeaver/assets/20814213/5d71d46b-370e-4aeb-90ca-4eeb37eb32e1)
I can't set a Light Theme on Window -> Preferences -> User interface -> Appearance, it was still dark style.

### DBeaver Version

23.1.0.202306041918

### Operating System

Linux: Deepin 20.9(base on Debian 11)

### Database and driver

Postgre

### Steps to reproduce

1. System switch to a dark theme automatically.
2. open a SQL Script, Function or which including SQL code etc.

**Comment by LonwoLonwo** [comment]
Hello @Oliver-GMJ 

Did you try the Darkest Dark theme? You can read instructions on how to install it here: https://github.com/dbeaver/dbeaver/wiki/Eclipse-extensions

Also, did you try to change any colors in Preferences?

![2023-06-09 12_10_53-Preferences](https://github.com/dbeaver/dbeaver/assets/45152336/deec71b8-7db2-49d2-9de9-c4ba6bb8b3bd)

**Comment by Oliver-GMJ** [comment]
> Hello @Oliver-GMJ
> 
> Did you try the Darkest Dark theme? You can read instructions on how to install it here: https://github.com/dbeaver/dbeaver/wiki/Eclipse-extensions
> 
> Also, did you try to change any colors in Preferences?
> 
> ![2023-06-09 12_10_53-Preferences](https://user-images.githubusercontent.com/45152336/244648697-deec71b8-7db2-49d2-9de9-c4ba6bb8b3bd.png)

Thanks @LonwoLonwo
It is not effective to change font color.
I try to use other theme.
