### ISSUE TITLE
Firebird Embeded (Firebird-2.5.4.26856-0_x64_embed).  Trying to connect to embedded database file.  

### ISSUE THREAD

**Issue by troydudley** [dbeaver/dbeaver#2026]
Firebird Embeded (Firebird-2.5.4.26856-0_x64_embed).  Trying to connect to embedded database file.  Get this error: Unable to complete network request to host "(null)". [SQLState:08006, ISC error code:335544721]
  java.lang.IllegalArgumentException: Unsupported array argument type: class org.firebirdsql.jna.fbclient.ISC_STATUS

Please see attached file with screen shots.
[Dbeaver-error-screenshots.pdf](https://github.com/serge-rider/dbeaver/files/1229533/Dbeaver-error-screenshots.pdf)
[dbeaver-.log.pdf](https://github.com/serge-rider/dbeaver/files/1229550/dbeaver-.log.pdf)
[dbeaver-debug.log.pdf](https://github.com/serge-rider/dbeaver/files/1229551/dbeaver-debug.log.pdf)

**Comment by Sargul** [comment]
did you have a look at #1556?

**Comment by Sargul** [comment]
No feedback. Closing

**Comment by troydudley** [comment]
Yes, I've already look at this and is not helpful and y'all are to quick to
close a ticket.

**Comment by troydudley** [comment]
Please reopen the ticket.  Thank you.

**Comment by tati-kru** [comment]
@troydudley thank you for your responcse. Reopen.

**Comment by serge-rider** [comment]
Tracked in #3397
