### ISSUE TITLE
Make Keep-Alive setting clearer (improve name and tooltip)

### ISSUE THREAD

**Issue by alattke-chwy** [dbeaver/dbeaver#20272]
### Description

In DBeaver 23.1.0 seeing behavior (with at least the Vertica driver) where `select current_schema()` is being triggered every second.

```
dbadmin=> select request, count(*), max(start_timestamp) from query_requests where user_name ='alattke' group by 1 order by 2 desc limit 1;
         request         | count |              max              
-------------------------+-------+-------------------------------
 select current_schema() |  1100 | 2023-06-12 15:27:48.392504-04
(1 row)

dbadmin=> select request, count(*), max(start_timestamp) from query_requests where user_name ='alattke' group by 1 order by 2 desc limit 1;
         request         | count |              max              
-------------------------+-------+-------------------------------
 select current_schema() |  1268 | 2023-06-12 15:32:00.563201-04
(1 row)
```

I don't see a way to disable this in the settings.

### DBeaver Version

23.1.0 Community Edition

### Operating System

Both Mac and Windows

### Database and driver

Vertica 12.x

### Steps to reproduce

Connect to Vertica. Don't do anything for a few mins. Check the Vertica `query_requests` table.
```
dbadmin=> select request, count(*), max(start_timestamp) from query_requests where user_name ='alattke' group by 1 order by 2 desc limit 1;
         request         | count |              max              
-------------------------+-------+-------------------------------
 select current_schema() |  1100 | 2023-06-12 15:27:48.392504-04
(1 row)

dbadmin=> select request, count(*), max(start_timestamp) from query_requests where user_name ='alattke' group by 1 order by 2 desc limit 1;
         request         | count |              max              
-------------------------+-------+-------------------------------
 select current_schema() |  1268 | 2023-06-12 15:32:00.563201-04
(1 row)
```

**Comment by LonwoLonwo** [comment]
Hello @alattke-chwy 

For the correct display of the current schema, DBeaver needs to know the current schema after every query (because this query can be about schema-changing) 

![2023-06-13 10_39_24-DBeaver Ultimate 23 1 0 - _orcl_ Script-59](https://github.com/dbeaver/dbeaver/assets/45152336/44351f60-0cbf-4d51-8ee5-44bdb78dffb2)


You can change this behavior in the settings:

![2023-06-13 10_38_18-Preferences](https://github.com/dbeaver/dbeaver/assets/45152336/9fe05c42-2d44-4a63-8364-94dec544f1c8)

**Comment by alattke-chwy** [comment]
Thank you @LonwoLonwo for your reply.
If this was issued once per query it wouldn't be an issue. 
This is idle. I make a connection to the DB, **and don't run any queries**. `select current_schema()` runs about every 1s as long as connection is open.

**Comment by alattke-chwy** [comment]
Additionally, these are the current settings:
<img width="618" alt="image" src="https://github.com/dbeaver/dbeaver/assets/49883848/56e52c9a-a756-4526-b4df-dbc1e46a1669">
Behavior is present in both Mac and Windows.

**Comment by Destrolaric** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/20579256/d0bf50d8-9415-4ce6-9bf0-cc14353f6512)
Hi, Could you send me the results from query manager when issue happens? You could open it from `Window-> Open Perspective -> Query Manager`

**Comment by alattke-chwy** [comment]
Hi Georgii. Nothing in the query manager:
***@***.***

Here’s the query activity as seen in the Vertica query_requests log table (4 mins after logging in and not issuing any queries in DBeaver):


select request::varchar(100), count(*), min(start_timestamp) as min_ts, max(start_timestamp) as max_ts from query_requests where user_name ='alattke' group by 1 order by 2 desc;

                                               request                                                | count |            min_ts             |            max_ts

------------------------------------------------------------------------------------------------------+-------+-------------------------------+-------------------------------

 select current_schema()                                                                              |   164 | 2023-07-12 16:30:47.091507-04 | 2023-07-12 16:34:52.16891-04

 set session autocommit to on                                                                         |     4 | 2023-07-12 16:30:46.940981-04 | 2023-07-12 16:30:49.098223-04

 SET search_path = public,"$user",public,v_catalog,v_monitor,v_internal                               |     2 | 2023-07-12 16:30:47.021049-04 | 2023-07-12 16:30:49.144501-04

 select * from (select 'bidb' as catalog_name, name as schema_name from v_internal.vs_schemata where  |     1 | 2023-07-12 16:30:49.323758-04 | 2023-07-12 16:30:49.323758-04

 select * from (select type_name as data_type_name, case odbc_type when 9 then odbc_subtype when 10 t |     1 | 2023-07-12 16:30:49.274807-04 | 2023-07-12 16:30:49.274807-04


From: Georgii ***@***.***>
Date: Thursday, June 29, 2023 at 4:55 AM
To: dbeaver/dbeaver ***@***.***>
Cc: Adrian Lattke ***@***.***>, Mention ***@***.***>
Subject: Re: [dbeaver/dbeaver] current_schema() triggered every second (Issue #20272)

[image]<https://protect-us.mimecast.com/s/pujrCxkx5xI1LZqpzuYWYUL?domain=user-images.githubusercontent.com>
Hi, Could you send me the results from query manager when issue happens? You could open it from Window-> Open Perspective -> Query Manager

**Comment by Destrolaric** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/20579256/5ed1c606-21cb-4d65-84f4-55fa747f6702)
Could you send me your keep-alive settings? You can find them in your connection configuration.

**Comment by alattke-chwy** [comment]
<img width="817" alt="image" src="https://github.com/dbeaver/dbeaver/assets/49883848/2e1cca5d-2111-4fb7-a1c0-c72f0a7e4434">

**Comment by LonwoLonwo** [comment]
Could you please check the latest DBeaver version? https://dbeaver.io/download/
Does the issue still persist?

**Comment by alattke-chwy** [comment]
Tried version 23.1.3 (latest).
```
dbadmin=> select request, count(*), max(start_timestamp) from query_requests where user_name ='alattke' group by 1 order by 2 desc limit 1;
         request         | count |              max              
-------------------------+-------+-------------------------------
 select current_schema() |    52 | 2023-07-27 10:21:05.179038-04
(1 row)

dbadmin=> select request, count(*), max(start_timestamp) from query_requests where user_name ='alattke' group by 1 order by 2 desc limit 1;
         request         | count |              max              
-------------------------+-------+-------------------------------
 select current_schema() |    67 | 2023-07-27 10:21:20.247456-04
(1 row)
```
Issue still there

**Comment by iraidaa** [comment]
We do not reproduce the issue in the latest **CE 23.1.5** on Windows.

According to the Query Manager, with all the filters checked,  the `select current_schema()` is being run per query or after the reconnection to the database.

When we run 

`select request, count(*), max(start_timestamp) from query_requests where user_name ='dbeaver' group by 1 order by 2 desc limit 2;`


We get 


request                     |count|max                    |
----------------------------+-----+-----------------------+
set session autocommit to on|  225|2023-08-30 10:32:55.804|
select current_schema()     |  **92**|2023-08-30 10:32:54.778|

Some minutes later, doing nothing in the SQL Editor:

request                     |count|max                    |
----------------------------+-----+-----------------------+
set session autocommit to on|  225|2023-08-30 10:32:55.804|
select current_schema()     |   **93**|2023-08-30 10:35:29.411|

The `select current_schema()` count is increased only by one due to the query rerun.

Our Vertica version:
![image](https://github.com/dbeaver/dbeaver/assets/49681450/46cebc73-aa4f-49b2-ad9f-1443513f8d53)

We have the following settings:

![image](https://github.com/dbeaver/dbeaver/assets/49681450/eb7fd27c-3f46-4897-8599-8276b8faae63)
![image](https://github.com/dbeaver/dbeaver/assets/49681450/d14e6ec3-c23d-4756-8b65-a0937dfaf464)

**Comment by alattke-chwy** [comment]
I figured out what's causing this:
![image](https://github.com/dbeaver/dbeaver/assets/49883848/d3ba5640-d380-4dd4-9180-7748a6c7bfdf)
The `tcpkeepalive` driver property is not in the list, but should be: 
<img width="693" alt="image" src="https://github.com/dbeaver/dbeaver/assets/49883848/20aed955-c12a-4f66-a155-6106184b1b50">


TCPKeepAlive implementation should leverage the JDBC driver implementation not issue constant queries to the DB.

**Comment by LonwoLonwo** [comment]
We need to enhance the tooltip of the keep-alive setting and add a link to our documentation.

**Comment by alattke-chwy** [comment]
If "Initialization->Keep-Alive" is meant to be an interval at which `select current_schema()` is issued, it should instead be labeled "Keep-Alive Interval (in seconds)" or something along those lines.
In reality this should be a checkbox (boolean) and if set should leverage the JDBC driver's TCPKeepAlive property as such:
`jdbc:vertica://myverticaurl:5433/mydbname?tcpKeepAlive=TRUE`

**Comment by LonwoLonwo** [comment]
Different drivers support keeping alive in different ways. Now, we are talking about the general DBeaver setting. Not Vertica one.

Keep-alive in DBeaver for generic databases does the "select current database" query to check that the connection is still alive.

**Comment by arhayka** [comment]
We decided to:
1. Rewrite the hint about Keep-Alive setting and add a link to the documentation. Smth like this: _Interval between SQL queries executed to keep the database connection alive. View documentation_
2. Change the label to _Keep-Alive (in seconds)_

**Comment by alattke-chwy** [comment]
Please consider allowing a URL of this form: `jdbc:vertica://myverticaurl:5433/mydbname?tcpKeepAlive=TRUE` . As of now this will generate an error when I try to connect using this. This is the proper way to leverage Keep-Alive's with Vertica.

Thank you!

**Comment by LonwoLonwo** [comment]
We can not change our basic mechanism of a keep-alive setting for one database. 
You can change the URL manually in your connection settings.

**Comment by alattke-chwy** [comment]
Understood. This is how I was able to get it to work:

<img width="752" alt="image" src="https://github.com/dbeaver/dbeaver/assets/49883848/5aaa7ed2-a914-4471-a52a-e8f5a5bd110a">

Thank you DBeaver team for all the help!
