### ISSUE TITLE
Impossible to display DB Tasks anymore

### ISSUE THREAD

**Issue by Thomas-LEILLET-Sanofi** [dbeaver/dbeaver#20282]
### Description

The button "Database tasks" does not display the previously recorded DB taskss. Nor the new one. Impossible to edit the existing ones.

### DBeaver Version

Version 23.1.0.202306041918 (CE)

### Operating System

Win11

### Database and driver

n/a

**Comment by E1izabeth** [comment]
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by Thomas-LEILLET-Sanofi** [comment]
It does not seem to trigger any error at all. Just the windows stays empty. I tried to remove the task.json file and start fresh, but nothing changed. Task created cannot be edited, just called by the small shortcut upper screen.
[dbeaver-debug-logs.zip](https://github.com/dbeaver/dbeaver/files/11754041/dbeaver-debug-logs.zip)

**Comment by Thomas-LEILLET-Sanofi** [comment]
Was not in the correct active project ...not an issue, except my correct usage of DBeaver. Sorry.

**Comment by E1izabeth** [comment]
Thank you for update!
