### ISSUE TITLE
Scrollbar doesn't appear on main tab of connection settings

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#20289]
### Description

Main tab of the connection settings can take a lot of space in some cases (e.g. kerberos extra settings) and lower part of the wizard becomes inacessible on smaller displays.

### DBeaver Version

23.1.0

### Operating System

Any

### Database and driver

Any

### Steps to reproduce

1. Open connection settings
2. Select Kerberos authorization
3. Expand extra settings
4. Resize the window so everything won't fit there(or do the same on a smaller display)

**Expected:** Scrollbar appears to access lower part of the page
**Actual:** Lower part becomes inacessible

### Additional context

https://github.com/dbeaver/dbeaver/assets/82543000/20fa567d-0523-404b-a4d4-64bcd3d0cd25

**Comment by arhayka** [comment]
We want to add a scroll bar to all dialog pages. And we need to remove the scroll where it was already added.
