### ISSUE TITLE
"end-of-file" error while executing block with crtl+enter

### ISSUE THREAD

**Issue by Andreas90-AS** [dbeaver/dbeaver#20287]
### Description

Hi, 
before I used to execute code blocks with "crtl+enter". Since the latest update I get an "end-of-file" error. 
e.g. a random procedure (which works fine): 

`BEGIN
	p_email('x@y.com');
END;`

throws: 

 _SQL Error [6550] [65000]: ORA-06550: line 3, column 3:
 PLS-00103:`` Encountered the symbol "end-of-file" when expecting one of the following:
   ; <an identifier> <a double-quoted delimited-identifier>
The symbol ";" was substituted for "end-of-file" to continue.
Error position: line: 2 pos: 2_

When I select the whole block and then press "crtl+enter", everthing works fine. "alt+x" wouldn't be a pleasable solution, since there are other queries in the script as well.

Is this a bug or by design? Am I making a mistake? 

Thanks in advance 

### DBeaver Version

Enterprise 23.1.0.202306120813

### Operating System

Win 10

### Database and driver

Oracle Database 11g Release 11.2.0.4.0 - 64bit Production

**Comment by E1izabeth** [comment]
What database do you use?

**Comment by E1izabeth** [comment]
Never mind, I see that it's Oracle by the error.

I reproduced the issue. The `;` at the end of query is missing in the sql query that DBeaver execute, which cause this error.

**Comment by Andreas90-AS** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/95411448/df70de2c-7849-4373-8cb6-bb744c687342)

**Comment by E1izabeth** [comment]
@Andreas90-AS 
I didn't mean that the query you execute is not correct :) I mean that DBeaver cut `;` at the end for some reason. You may see that it's missing in the right area of the results tab or in Query Manager.

I reproduced the issue, so no more additional information is needed. Thank you for bug report!

**Comment by E1izabeth** [comment]
Th issue was fixed in scope of #20421

**Comment by viktoriiagurina-centris** [comment]
This problem is present in DBeaver 24.2.1 as well. The "end-of-file" or "encountered BEGIN" happens randomly when trying to execute a valid script. Tried to restart the program, to reboot the machine. Resolved by just copy-pasting the script in a new SQL query window.
