### ISSUE TITLE
Autocompletion 3-5 sec waiting

### ISSUE THREAD

**Issue by DeLuffyc** [dbeaver/dbeaver#20284]
### Description

Bought new laptop and there is stuttering when I'm texting my scripts, autocompletion from 3 to 5 sec to find (coolers go louder). What could be the problem? Windows 11, i9-13900HX

### DBeaver Version

23.1

### Operating System

Windows 11

### Database and driver

MySQL

### Steps to reproduce

Create new script
Start SQL query writing
Autocompletion  takes from 3-5sec to appear

**Comment by E1izabeth** [comment]
Could you try disabling this setting?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/f6da0106-7429-427f-8027-aa0f174fcfd4)

**Comment by E1izabeth** [comment]
@DeLuffyc does it help?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by E1izabeth** [comment]
Serge reproduced the issue.
