### ISSUE TITLE
In some cases autocompletion makes DBeaver freeze

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#20299]
### Description

STR:

1. Connect to PostgreSQL 10 
2. Enable experemental feature in SQl editor -> Code completion
3. In schema public write this query:
`SELECT  i.inventory_id ,
a2.address_id
FROM 
 public.album a1,
 public.address a2,
 public.actor a3,
 public.accounts a4,
 public.film f 
INNER JOIN public.inventory i on f.film_id = i.film_id 
 WHERE  a4.id =1`
4. In the inner join statement delete the table name to check if autocomplete works after the schema name

**Actual result** - DBeaver freezed. If I disable the experimental feature after that - Dbeaver works correctly again.

**NOTE** I can reproduce it on Windows (8 GB RAM, AMD), but on Mac M1 (8 GB RAM, Silicon) its not reproducible

https://github.com/dbeaver/dbeaver/assets/84867187/8138a0c8-1a6d-40ac-bc98-190ee4acf9eb

### DBeaver Version

23.1.0

### Operating System

win 10 (8 GB RAM, AMD)

### Database and driver

PostgreSQL 10

**Comment by E1izabeth** [comment]
Fixed in scope of #20284
