### ISSUE TITLE
Bottom scrollbar overlays the text making it unreadable.

### ISSUE THREAD

**Issue by yan5** [dbeaver/dbeaver#20293]
### Description

The bottom scrollbar overlays the text (its the last line in the editor) making it unreadable as shown in below screenshot.
A padding at the bottom would be nice.

![image](https://github.com/dbeaver/dbeaver/assets/20642737/0b9072a7-d79c-4a1a-b5ae-b0174ab3957d)

### DBeaver Version

Version 23.1.0.202306041918

### Operating System

Ubuntu 22.04

**Comment by E1izabeth** [comment]
Thank you for bug report. It's a duplicate of #10950
