### ISSUE TITLE
updated rows display error

### ISSUE THREAD

**Issue by HelloJysun** [dbeaver/dbeaver#20296]
### Description

I have a table `test_updated_rows`
```
CREATE TABLE `test_updated_rows` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `value` int unsigned NOT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
```

Data rows
<img width="548" alt="image" src="https://github.com/dbeaver/dbeaver/assets/19143161/78af48dd-b540-4a2a-979f-a37c353618fd">

When I execute the following SQL in DBeaver, the result is as follows
```
INSERT INTO
    test_updated_rows
    (id, value)
VALUES
    (1, 1)
ON DUPLICATE KEY UPDATE
    value = 1;
```

<img width="342" alt="image" src="https://github.com/dbeaver/dbeaver/assets/19143161/e059ce0c-e747-4923-9c4c-1ebf2682b798">

When I execute the same SQL in the MySQL CLI, the result is as follows

<img width="358" alt="image" src="https://github.com/dbeaver/dbeaver/assets/19143161/af717905-83ea-42ab-bc30-daf7b7abf8c3">

I think this is a bug, because I looked through the MySQL documentation and found that updated rows will show 1 only when a new record is inserted. If the updated value is the same as the original value, affected-rows value should be 0

Reference: https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html#:~:text=With%20ON%20DUPLICATE%20KEY%20UPDATE,set%20to%20its%20current%20values

### DBeaver Version

23.0.5.202305211610

### Database and driver

MySQL version 8.0.32
MySQL JDBC Driver 8.0.29

**Comment by Matvey16** [comment]
@HelloJysun Thank you for the report. This is specific to the JDBC.

According to the MySQL Connector/J development team's interpretation of the JDBC spec, UPDATE statements should return the number of rows matched by the statement, not the number of rows actually changed.

https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-connection.html

But if you actually need it to work as in your example, you need to change driver parameter useAffectedRows to `true`

![image](https://github.com/dbeaver/dbeaver/assets/82543000/3888206d-41aa-4392-a878-55f09a21aa37)
