### ISSUE TITLE
SQL error tooltip appears when hovering over a valid query

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#20298]
### Description

https://github.com/dbeaver/dbeaver/assets/35821147/41a71c56-b49f-48e7-9ce7-b4373a02f90b

### DBeaver Version

DBeaver 23.0.1

### Operating System

Windows

### Steps to reproduce

1. Execute an invalid SQL
2. Place caret at the start of the line
3. Hover mouse over any other query (might require going back and forth)

**Comment by serge-rider** [comment]
Fixed
