### ISSUE TITLE
Reset UI Settings action removes imported projects

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#20306]
### Description

See the title.

### DBeaver Version

DBUE 23.1 (devel branch)

### Operating System

macOS 13.4 (22F66)

### Steps to reproduce

1. Use a non-default workspace, that is, not DBeaverData/workspace6 (not sure if it matters)
1. Import a project using File -> Open Projects from File System...
1. Help -> Reset UI Settings... -> Yes.
1. See that the imported projects are gone from the workspace.

**Comment by ShadelessFox** [comment]
- Rename to "Reset Settings"
- Add settings for removing "plugin configuration" that will delete everything except `org.eclipse.core.resources`
- Maybe something else?
