### ISSUE TITLE
Filter by value (CTRL-F11) on a column in a table does nothing

### ISSUE THREAD

**Issue by jeff-ddm** [dbeaver/dbeaver#20307]
### Description

It used to open a window with all the possible values for a field but now it does absolutely nothing

![image](https://github.com/dbeaver/dbeaver/assets/63684042/f8156782-2997-4424-b63a-6d76cdbdb5c3)

### DBeaver Version

EE 23.1.0

### Operating System

Win11 x64

### Database and driver

Unrelated I would guess

### Steps to reproduce

1. Open a table
2. Click on the down arrow on a field
3. Select "Filter by value"

**Comment by MashaKorax** [comment]
Hello, @jeff-ddm , please enable this setting. It should help you.
![dbeaver_7U8SQwfBWl](https://github.com/dbeaver/dbeaver/assets/84867187/1627847a-e4bd-420d-90b3-bae98fa431df)
