### ISSUE TITLE
Can't update timestamp field

### ISSUE THREAD

**Issue by sryze** [dbeaver/dbeaver#20312]
### Description

In my PostgreSQL DB, when I edit a cell and enter `2023-05-05 ‏‎22:40:42.000` (or without the `.000` part) and hit Save, DBeaver tells me that it's an invalid value. However, other rows have exactly the same format in the same column, and this is a little bit confusing.

```
Error synchronizing data with database

Reason:
SQL Error [22007]: ERROR: invalid input syntax for type timestamp: "2023-05-05 ‏‎22:40:42.000"
  Where: unnamed portal parameter $1 = '...'
```

**Update:**

It looks like we should use the calendar button to set timestamps (it works). Maybe DBeaver should also parse the timestamp from user input string and convert it to the appropriate PostgreSQL type upon saving?

### DBeaver Version

Community Edition 23.1.0

### Operating System

Windows 10

### Database and driver

PostgreSQL 15

### Steps to reproduce

1. Double click a `timestamp` field in a table to edit it
2. Enter a timestamp as text e.g. `2023-05-05 ‏‎22:40:42`
3. Save changes

**Comment by uslss** [comment]
Unfortunately, cannot reproduce the issue. Could you provide table ddl?
Is there something in the [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by sryze** [comment]
I can't reproduce this anymore. Not sure how it happened.
