### ISSUE TITLE
When querying a table, the column suggestion does not show up

### ISSUE THREAD

**Issue by pachecomiguel** [dbeaver/dbeaver#20314]
### Description

Hello Dbeaver.

So I just had this problem recently.

Select cons(_initials for consumer)_ from prestine_dataset

And, when I write the initials for the word consumer, I would expect to have suggestions of columns that start or have "cons" in its name.
The thing is, for some weeks now, this does not happen. Not a single suggestion for column is returned, the only thing returned are functions.

The only way around I found was:

Select  * from prestine_dataset
where cons(_initials for consumer)_ = 2 

and here, I can see all the columns who have the letters cons included in it.

I know for a fact that I am not the only one having an issue, but for the life of me, I cannot find a solution for this.

Thank you for your time.

### DBeaver Version

23.1

### Operating System

OS Name	Microsoft Windows 10 

### Database and driver

Database Version: 7.10
Driver: Exasol

### Steps to reproduce

Select cons(_initials for consumer)_ from prestine_dataset

It does not show any column suggestion

**Comment by uslss** [comment]
Unfortunately, cannot reproduce it.
Could you provide a video of the issue?
Thanks in advance.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
