### ISSUE TITLE
Old Jaybird driver for Firebird

### ISSUE THREAD

**Issue by tomaszdubiel18** [dbeaver/dbeaver#20329]
### Description

When setting up Firebird connection, DBeaver by default uses Jaybird 4.0.0. It should use the latest 4.0, Jaybird 4.0.9.

### DBeaver Version

23.1.0

### Operating System

Windows

### Database and driver

Firebird.
Jaybird.

**Comment by mrotteveel** [comment]
I think it should rather use the latest overall, which is Jaybird 5.0.2

**Comment by LonwoLonwo** [comment]
Thanks for the idea.

**Comment by tomaszdubiel18** [comment]
What's with this issue?

**Comment by LonwoLonwo** [comment]
Hello @tomaszdubiel18 

Thanks for bumping. We have been using Jaybird 5.0.2 since August. So, I'll close this ticket.
