### ISSUE TITLE
Cosmetic: The tooltip containing SQL flickers when the mouse pointer is on the exec plan title text 

### ISSUE THREAD

**Issue by dbza** [dbeaver/dbeaver#2032]
v 4.0.2 (not tested on latest)
Steps to reproduce:
1) Write a query, run explain plan. 
2) Keep the cursor at the end of the SQL and let it blink as normal. 
3) Point the mouse cursor exactly on top of the **text** "Exec. Plan" in title bar on the results pane . The tooltip appears and goes away repeatedly. 
PS: It appears to be in sync with the blinking text cursor, but maybe step 2 is not a necessary condition

**Comment by dariopnc** [comment]
happens with 4.1.2, too

**Comment by serge-rider** [comment]
What is your OS? Can't reproduce this on Windows. 
Perhaps some GTK issue?

**Comment by dariopnc** [comment]
I can reproduce this Issue on Windows 7 for any DBeaver version (at least) from 4.0.0 to 4.2.1

How can I check my GTK Version?

**Comment by uslss** [comment]
Cannot reproduce on 6.0.2
