### ISSUE TITLE
SQL Assistant is not working on versio 23.1.0

### ISSUE THREAD

**Issue by nataklug** [dbeaver/dbeaver#20323]
### Description

For some unknow reason my saved scripts are not working with SQL Assistant. When I try a new one it works:
![image](https://github.com/dbeaver/dbeaver/assets/34246539/58542ab9-66ad-4d28-b06c-4469045e4fac)
But when trying in the old one:
![image](https://github.com/dbeaver/dbeaver/assets/34246539/ea8920d5-fdcc-41b9-8bb2-fe93a28783ac)
I've tried to change the charset but no lucky.

### DBeaver Version

23.1.0

### Operating System

Windows 11

### Database and driver

Database driver: mysql8 (com.mysql.cj.jdbc.Driver)

### Steps to reproduce

1) Open saved script (which was working on version 23.0.5).
2) Try to use auto-complete (SQL Assistant) on an aliased table.

**Comment by E1izabeth** [comment]
Could you try turning off `Enable experimental feature` setting?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/ae20f5bb-ebae-4dad-8207-3910699a4b54)

**Comment by nataklug** [comment]
Thank you Elizabeth. I had not look into this option and it is, indeed, marked:
![image](https://github.com/dbeaver/dbeaver/assets/34246539/f1f65f51-7c9e-45ba-b5ca-602d14a13020)

Unchecking it and it is now working! Thank you!!

**Comment by uslss** [comment]
#20199

**Comment by uslss** [comment]
@nataklug could you provide SQL sample to reproduce the issue?

**Comment by nataklug** [comment]
> @nataklug could you provide SQL sample to reproduce the issue?

Hello @uslss. I am not using that version anymore and after @E1izabeth tip it is working fine with no more problems. To reproduce the problem I had some saved scripts on my computador, most of them made in an old version of DBeaver, with encoding as ISO-8859-1 (I have no idea if this is important). When I opened it on the version 23.1.0 with Experimental marked I was not able to use SQL Assistant. The first thing I made was migrating them to UTF-8. No luck. After that I tried re-writen the code and as it grows more difficult was to SQL Assistant work. I attached one of this scripts but I don't think you will be able to reproduce but you can see the joins I made.
[EXP0003_cancelamento.zip](https://github.com/dbeaver/dbeaver/files/12080123/EXP0003_cancelamento.zip)

**Comment by MashaKorax** [comment]
Thanks for bug report!

**Comment by E1izabeth** [comment]
@nataklug 
We made some improvements recently. Please try our latest version to see if this issue is still actual with `Enable experimental features` on.

**Comment by nataklug** [comment]
@E1izabeth sure, I will try and if I find some error I will let you know. Thank you for the efforts.

**Comment by nataklug** [comment]
Looks like it is working:
![image](https://github.com/dbeaver/dbeaver/assets/34246539/0e4469d9-456f-4993-8cd3-200af9fffb2f)
