### ISSUE TITLE
[ERD]  In palette view "Pin" btn does nothing

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#20325]
### Description

For now by clicking on the header, it always collapses the section, and by clicking on the arrow, the entire palette always collapses

https://github.com/dbeaver/dbeaver/assets/84867187/c4969e21-ac73-470c-8e0c-af56edfa2f6e

### DBeaver Version

23.1.0

**Comment by ShadelessFox** [comment]
It prevents group from collapsing if there's not enough space. This is the default GEF behavior, and it can't be changed.

https://github.com/dbeaver/dbeaver/assets/35821147/75d27374-71d0-4ae2-a5b5-f3b3988fe5d8
