### ISSUE TITLE
Feature Request: Ability to assign hotkey to "Find/Replace" when editing in "Value" pane.

### ISSUE THREAD

**Issue by cmcconomyfwig** [dbeaver/dbeaver#20336]
**Is your feature request related to a problem? Please describe.**
When I query and return a jsonb column, there is a 'value' tab on the right which allows me to view the json contents (fantastic).
There is a context menu, from which I can choose "Find/Replace.." (awesome!)

However - there is no way I can find to bind a hotkey for "Find (in this view)"! (noooo!)

**Describe the solution you'd like**
Ability to bind a hotkey for "Find" in the "value" pane when exploring select results

**Describe alternatives you've considered**
I tried to bind the "Find/Replace" function in the context of:
* Database Navigator View Context
* Editing Text
* Results Edit Context
* Results Viewer Context

But nothing seemed to work.

**Comment by uslss** [comment]
#16424

**Comment by uslss** [comment]
#20092

**Comment by ShadelessFox** [comment]
Thank you for your request.
