### ISSUE TITLE
timediff function return empty

### ISSUE THREAD

**Issue by skyearth99** [dbeaver/dbeaver#20343]
### Description

When using the timediff function, if the result is negative, the returned result will become empty.Use to_char function conversion can return normal results.

### DBeaver Version

23.1

### Operating System

windows 11

### Database and driver

gbase 8a jdbc package.
the same goes for other databases

### Steps to reproduce

timediff(a.etl_time,b.etl_time))

### Additional context

previous versions of dbeaver returned empty regardless of whether the value was positive or not,v23.1 is better.

**Comment by hrimthrusa** [comment]
Hello! Could you please tell us in which databases you are able to reproduce the issue apart from GBase?

We tried the most popular ones in DBeaver v23.1 and couldn't reproduce it:

**PostgreSQL:**
SELECT DATE_PART('year', '2010-01-01'::date) - DATE_PART('year', '2011-10-02'::date);
Result: **-1**

**MySQL 8:**
SELECT TIMEDIFF('2010-10-11 00:00:00', '2010-10-12 00:00:00') AS TIMEDIFF;
Result: **-24:00:00**

**Oracle 12.2:**
SELECT 24 * (to_date('2009-07-07 22:00', 'YYYY-MM-DD hh24:mi') 
             - to_date('2009-07-07 22:30', 'YYYY-MM-DD hh24:mi')) diff_hours 
       FROM dual;
Result: **-0.5**

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by skyearth99** [comment]
Sorry, due to the different implementation methods of databases such as Oracle , MySQL and hive on timediff, and the limited databases available for testing, I am currently unable to reproduce them on other databases.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dbeaver/dbeaver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月24日(星期一) 下午3:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dbeaver/dbeaver] timediff function return empty (Issue #20343)





 
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by LonwoLonwo** [comment]
Could you please provide a screen with the incorrect result of the function?

**Comment by skyearth99** [comment]
look at the "timediff(time1,time2)" column.



***@***.***
 
From: Anastasiya
Date: 2023-07-25 15:15
To: dbeaver/dbeaver
CC: skyearth99; Author
Subject: Re: [dbeaver/dbeaver] timediff function return empty (Issue #20343)
Could you please provide a screen with the incorrect result of the function?

**Comment by E1izabeth** [comment]
@skyearth99 I believe you tried to attach an image, but answered via reply email to the github notification about new comments on the issue. Please, do it by writing a comment to the issue.

**Comment by skyearth99** [comment]
![Catch(07-26-08-16-23)](https://github.com/dbeaver/dbeaver/assets/137269900/4316a1a6-fcec-4ff9-a4e9-f64ac0e65da8)
Try uploading an image by writing a comment .

**Comment by iraidaa** [comment]
We do not officially support gbase so we cannot reproduce the issue now.

**Comment by skyearth99** [comment]
That's all right.I still can get results by to_char function.Thank you.



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 27, 2023 20:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dbeaver/dbeaver] timediff function return empty (Issue #20343)




 
We do not officially support gbase so we cannot reproduce the issue now.

**Comment by skyearth99** [comment]
close
