### ISSUE TITLE
Get binary version from command-line / shell

### ISSUE THREAD

**Issue by staticdev** [dbeaver/dbeaver#20340]
**Is your feature request related to a problem? Please describe.**
Dbeaver does not support a command to just see binary version.

**Describe the solution you'd like**
It would be nice to have a "dbeaver-ce --version" command to check via terminal.

I am developing a [streamlined way to have dbeaver installed in Linux workstations](https://github.com/staticdev/linux-workstation-playbook) (but this command can do the same in other OS). The problem is, without a command to get the version, tools such as ansible have to redownload everytime the binary to check if it has changed or not. With such command I can even create an ansible role to have better update options for dbeaver.

**Describe alternatives you've considered**
I also tried executing the program and getting the version shown in the output, but that is not desirable also, since the process needs to be killed in workstation configuration time (which is not a general best practice).

**Comment by ShadelessFox** [comment]
Hello @staticdev,

Thanks for the feature request

**Comment by staticdev** [comment]
Thanks a lot @serge-rider @n5a5 and @ShadelessFox, will do the proper tests when it is released.
