### ISSUE TITLE
DB2 / Db2 for IBM i : Problem when creating a temporary table

### ISSUE THREAD

**Issue by Jean-OIKONOMOU** [dbeaver/dbeaver#20352]
### Description

Hello,

DECLARE GLOBAL TEMPORARY TABLE X AS (query) WITH DATA; fails with a query that gives more than a million records. I get an SQLCODE = 0 (SUCCESS), the table is created, however, there is no data in it. 

If I do the same with a query that gives less than a million then I do get a table with the correct data.

Finally, I am creating this issue here because when I create a temp table with more than a million records on the IBMi server then it succeeds in doing so (table present in QTEMP library and it has all the data it should have).

Thanks,

### DBeaver Version

Version 23.1.0.202306041918

### Operating System

Windows 10

### Database and driver

1. DB2 / Db2 for IBM i

### Steps to reproduce

1. Connect DBeaver to an IBMi mainframe.
2. Run 
`DECLARE GLOBAL TEMPORARY TABLE TEMPX AS ( query that gives > 1M records ) WITH DATA;`
3. Verify if the temp table TEMPX has data in it : 
`SELECT * FROM QTEMP.TEMPX;`
4. If it does not then run that same query directly on the IBMi mainframe, if it works there then that confirms DBeaver has a difference with the IBMi mainframe.

**Comment by Matvey16** [comment]
Hello @Jean-OIKONOMOU I wasn't able to reproduce this issue.

Can you make a screenshot of the results shown in query manager aftr runing the declare query, like this

![dbeaver_osBlblArA8](https://github.com/dbeaver/dbeaver/assets/82543000/65e334a3-07d0-471a-8fbd-a49b0579eb65)

![dbeaver_KVMYhtxA3d](https://github.com/dbeaver/dbeaver/assets/82543000/986f5152-05eb-4d35-894a-f3375e029dfb)

![dbeaver_fwA5p180wS](https://github.com/dbeaver/dbeaver/assets/82543000/0a4270ea-4046-4002-a4d3-20e8c032c02e)

It would also help if you can share a DDL of the original table and the version of the database which can be checed by clicking `Test connection` in the connection settings

![image](https://github.com/dbeaver/dbeaver/assets/82543000/8b070a94-c522-4a74-a1d8-0af44898499b)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
