### ISSUE TITLE
Copy - Paste project is not working

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#20353]
### Description

Im trying copy project by context menu or ctr C  - ctr V but nothing happens

https://github.com/dbeaver/dbeaver/assets/84867187/34152b1e-6362-4dcc-be2a-0f2331bd9c5b

### DBeaver Version

23.1.1 ce

**Comment by serge-rider** [comment]
It copies project name.
Paste on project does nothing
