### ISSUE TITLE
MSSQL: Wrong affected rows when update

### ISSUE THREAD

**Issue by miquelangeld** [dbeaver/dbeaver#20359]
### Description

Hi, I detected that jdbc for MSSQL is returning the wrong number of affected rows, always return exactly the double. I updated to the last dbeaver version and the problem persists.

This select return just one row
```
select * 
from contacts
where id  = '8CD98804-2C8E-414A-9638-002F55D941EB'
```

but this update statement returns two modified rows

```
update contacts 
set Country = null, Town = null
where id ='8CD98804-2C8E-414A-9638-002F55D941EB'
```
The same statement in SQL MAnagement Studio return just one row affected which is correct.

### DBeaver Version

Comunity 23.1.0.202306041918

### Operating System

Ubuntu 22.04

### Database and driver

JDBC MS SQL 9.20

### Steps to reproduce

This select return just one row
```
select * 
from contacts
where id  = '8CD98804-2C8E-414A-9638-002F55D941EB'
```

but this update statement returns two modified rows

```
update contacts 
set Country = null, Town = null
where id ='8CD98804-2C8E-414A-9638-002F55D941EB'
```
The same statement in SQL MAnagement Studio return just one row affected which is correct. Id is a unique field, no triggers, nothing.

**Comment by E1izabeth** [comment]
Could you send table DDL to reproduce your issue?

**Comment by E1izabeth** [comment]
It's been a while since no update here. However, we still can't reproduce it.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/3ca2549e-5b25-4ab1-86cb-03095f201a46)

If the issue is still actual please let me know and provide additional information.
