### ISSUE TITLE
Redshift external tables are not being displayed in database tree objects

### ISSUE THREAD

**Issue by jcvazquezupgrade** [dbeaver/dbeaver#20370]
### Description

Hi DBeaver Team,

 

I have several users connecting to Redshift through Okta authentication --> IAM role; they are able to connect to Redshift; however when they want to display the database object tree the connection only shows internal tables. All the external tables are not being displayed.

 

The Redshift drivers has been updated and also users are using the DBeaver Version 23.0.3.202304240630 Community Edition.

Is this a known issue?

Thanks in advance

Jay

### DBeaver Version

Community Edition 23.0.3.202304240630

### Operating System

macOS Ventura 13.4

### Database and driver

Database: Redshift 1.0.50708
Driver: redshift-jdbc42-2.1.0.14

**Comment by E1izabeth** [comment]
Could you try the latest DBeaver verison (23.1.1)? The issue could be already fixed.

**Comment by jcvazquezupgrade** [comment]
Hi @E1izabeth , thanks for following this up and apologize for my late response. I still see the issue in version 23.1.2.202307091549, community edition.

Actually, we have one more issue in version 23.1.2, the Redshift internal tables are not being displayed in the tree object as well.  Is this a known issue?

**Comment by E1izabeth** [comment]
@jcvazquezupgrade thank you for update.

No, it's not a known issue.

**Comment by LonwoLonwo** [comment]
Could you please provide a screen of your issue? Of your schema with empty tables?

Also, could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by LonwoLonwo** [comment]
Also, could you please check the following query?

`SELECT * FROM <your_catalog_name>.pg_catalog.svv_external_schemas`

Does it return your external schema's names?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
