### ISSUE TITLE
Regression: dbeaver 23.1.1 does not start, but 23.1.0 does

### ISSUE THREAD

**Issue by Mingun** [dbeaver/dbeaver#20377]
### Description

After upgrading from [23.1.0](https://github.com/dbeaver/dbeaver/releases/tag/23.1.0) to [23.1.1](https://github.com/dbeaver/dbeaver/releases/tag/23.1.1) does not start anymore. After launch the following is written to the console:
```
$ ~/dbeaver-ce-23.1.1-linux.gtk.x86_64-nojdk/dbeaver/dbeaver 
WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.jpackage
```
and then the following window is appearing:
![Dbeaver_23 1 1](https://github.com/dbeaver/dbeaver/assets/450131/e5bbf9b4-ce13-4664-94f9-91c0bc9c44ef)

The mentioned logs are attached:
- [1687757295056.log](https://github.com/dbeaver/dbeaver/files/11864091/1687757295056.log)
- [1687757295056.bak_0.log](https://github.com/dbeaver/dbeaver/files/11864092/1687757295056.bak_0.log)

### DBeaver Version

CE 22.1.1 -- https://github.com/dbeaver/dbeaver/releases/download/23.1.1/dbeaver-ce-23.1.1-linux.gtk.x86_64-nojdk.tar.gz

### Operating System

Ubuntu 22.04.2 LTS

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
DBeaver uses Java 17 from 23.1.1

**Comment by Destrolaric** [comment]
@Mingun `Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=17))"`
DBeaver now requires Java 17 to be able to launch.

**Comment by Mingun** [comment]
Ok. Maybe it would be possible to output a more user-friendly message in that case? If it's too hard, then fine

Maybe also edit Release description to make the Java 17 requirement more clear. Currently it looks like just a minor technical note for developers
