### ISSUE TITLE
Clickhouse Map type handling

### ISSUE THREAD

**Issue by Hubbitus** [dbeaver/dbeaver#20388]
You apparently support even `Tuple` type, but `Map` shown just as "[Object]".

Please support it in similar to `Tuple` way:
```sql
SELECT transaction_id, AsyncReadCounters
FROM system.query_log
```
![image](https://github.com/dbeaver/dbeaver/assets/720349/7a7a0096-1a23-461b-97fd-0b203aab317a)

That will be nice to see `AsyncReadCounters` in similar form of sub-headers, but with key names provided.

DBeaver version 23.1.0.202306041918 CE.

**Comment by E1izabeth** [comment]
Thank you for the report.

**Comment by uslss** [comment]
fixed in #20797

**Comment by Hubbitus** [comment]
Awesome! Thank you.
Will it be included in next release? Which version?

**Comment by E1izabeth** [comment]
@Hubbitus it's planned for DBeaver 23.1.5

**Comment by Hubbitus** [comment]
```sql
SELECT transaction_id, `Settings` 
FROM system.query_log
```
Will looks like:
![image](https://github.com/dbeaver/dbeaver/assets/720349/af907fa1-9c1c-49b4-a94c-ca0a537375df)

Why form is:
```
[{Key:connect_timeout_with_failover_ms, Value:1000}, {Key:load_balancing, Value:nearest_hostname}, {Key:distributed_aggregation_memory_efficient, Value:1}, {Key:do_not_merge_across_partitions_select_final, Value:1}, {Key:os_thread_priority, Value:2}, {Key:log_queries, Value:1}, {Key:parallel_view_processing, Value:1}, {Key:allow_experimental_live_view, Value:1}, {Key:default_database_engine, Value:Ordinary}]
```
instead of:
```
[{connect_timeout_with_failover_ms:1000}, {load_balancing:nearest_hostname}, {distributed_aggregation_memory_efficient:1}, {do_not_merge_across_partitions_select_final:1}, {os_thread_priority:2}, {log_queries:1}, {parallel_view_processing:1}, {allow_experimental_live_view:1}, {default_database_engine:Ordinary}]
```
?

Looks like repeating `key:` and `value:` just like the garbage. Are you agreed??

**Comment by E1izabeth** [comment]
What are you driver and database version?
I don't see this issue on my Clickhouse connection, but the versions are matter
![image](https://github.com/dbeaver/dbeaver/assets/28875055/250f456f-70bd-44b5-a3e4-f9e8a9368ce3)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/75f7d2f7-4312-48b5-a008-d47793c4a70d)

**Comment by Hubbitus** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/720349/de5b3412-15fa-42f8-8a5b-8b1beca81f6a)

ClickHouse 23.3.2.37
ClickHouse JDBC Driver 0.4.6 (revision: dd91e17)

**Comment by E1izabeth** [comment]
We want to remove excessive labels.

**Comment by Hubbitus** [comment]
Now it looks much better! Thank you.
