### ISSUE TITLE
The Window->Preference Menu is duplicated after Integrate Dbeaver Plugin in eclipse

### ISSUE THREAD

**Issue by imad-ELHAJLI** [dbeaver/dbeaver#20384]
### Description

When I Integrate DBeaver plugins (Version 21.1.0)  in my Eclipse 4.19.0 I get The Menu Preference twice in menu window.

### DBeaver Version

21.1.0

### Operating System

Windows

**Comment by E1izabeth** [comment]
I tried on Eclipse 2023-03 (4.27.0) and can't reproduce.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/9fc0718e-f13d-4630-b82d-8c9538200bcd)

**Comment by E1izabeth** [comment]
The bug doesn't present for me on the latest DBeaver version (23.1.1). Could you try on the newest version?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
