### ISSUE TITLE
Creating a table with quotes in the name breaks the cache

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#20383]
### Description

If the table is created via UI and the name is quoted, columns in priperties tab will desappear after saving and data tab will be shown as read-only untill the schema is refreshed

### DBeaver Version

23.1.1

### Operating System

Any

### Database and driver

PostgreSQL 12

### Steps to reproduce

1. Right-click on Schema and select "create table"
2. Type table name with quotes e.g. `"Table1"`
3. Add some columns
4. Save changes

**Expected:** Columns in properties tab are shown as created
**Actual:** Columns disappear

### Additional context

![dbeaver_cBAWOXsRxR](https://github.com/dbeaver/dbeaver/assets/82543000/ad0379d5-fea1-44e0-b348-9b9050df413a)

**Comment by serge-rider** [comment]
Now we unquote object names after saving them
