### ISSUE TITLE
Issue with hanzi in Data Editor

### ISSUE THREAD

**Issue by ywss** [dbeaver/dbeaver#20392]
### Description
Chinese hanzi can't be displayed in a proper way. Encoding change does nothing.
As shown on the picture below it works in other Application, but not in DBeaver.

sqlite db：[hk.zip](https://github.com/dbeaver/dbeaver/files/11877281/hk.zip)

![微信截图_20230627110348](https://github.com/dbeaver/dbeaver/assets/1284357/a993195a-3fb6-4b2a-8cba-2aabb22af2f4)
![微信截图_20230627110423](https://github.com/dbeaver/dbeaver/assets/1284357/61e893df-010e-48e8-8cfd-4e05160d8c19)

### DBeaver Version

community edition  23.1.1.202306251800

### Operating System

windows10

### Database and driver

1. SQLite
2. SQLite JDBC [3.42.0.0]

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
Does it still reproducible in the latest DBeaver version? We expect that it has been solved with #21513

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by gregkotsaftis** [comment]
I can verify this issue as well for Greek characters stored in the db. I use firebirdsql with NONE character set.
Data editor was showing greek characters without any issues in older versions e.g. v6.0.0, but later versions e.g. 22.x.x never worked properly!
