### ISSUE TITLE
When I paste numbers, it rounds up in display.

### ISSUE THREAD

**Issue by marste** [dbeaver/dbeaver#20399]
### Description

Why is it that when I paste in numbers taken from a txt or xls file and paste them in, it shows me the rounded numbers as shown in the image.
Why?
![Immagine 2023-06-27 161052](https://github.com/dbeaver/dbeaver/assets/661803/ba731cfb-92ff-480d-98d8-523d7ef9a99b)

### DBeaver Version

Community Edition 23.1.1

### Operating System

Windows 10

### Database and driver

Oracle DB

**Comment by ShadelessFox** [comment]
Hello @marste,

Unfortunately, I cannot reproduce the issue.

Can you please provide the DDL of the column you're pasting numbers into?

**Comment by marste** [comment]
Sorry, I didn't understand.
What do you mean by "**DDL** of the column"?

**Comment by ShadelessFox** [comment]
In the table's properties, navigate to the DDL tab:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/168e9016-181d-48e6-8e36-ac20cdefd9e0)

I'm interested in the exact data type, its scale and precision.

**Comment by marste** [comment]
Here it is!
![dll](https://github.com/dbeaver/dbeaver/assets/661803/102ea0ba-f2b2-4e85-b799-453e17db8546)

**Comment by MashaKorax** [comment]
For me, the same thing happens even without copy-pasting from anywhere.  Just typing number 86.52, but notice that in my case I used the period **(.)**, with comma **","** not reproducible

https://github.com/dbeaver/dbeaver/assets/84867187/adf0c337-975b-4656-bcae-fb14325440e2

**Comment by marste** [comment]
It also does it to me sometimes while writing, but not always.
I couldn't figure out the rational.
Then anyway the value it enters is correct and without decimal, but I don't understand why it should show it like that.

**Comment by ShadelessFox** [comment]
ALERT: Technical details

Although this is a bug, there is a reason why numbers get messed up so badly.

Please try entering your number here: https://www.h-schmidt.net/FloatConverter/IEEE754.html.
