### ISSUE TITLE
No columns are prompt when using table aliases

### ISSUE THREAD

**Issue by lucaperu** [dbeaver/dbeaver#20409]
### Description

When I use table aliases, intellisense doesn't make any proposals for fields name of the aliased table.
It doesn't happen when I use the table name.
For example:

Works:                `SELECT codpro, datareg FROM pub."movim" WHERE movim.[proposals]`
Doesn't work:     `SELECT codpro, datareg FROM pub."movim" m WHERE m.[no proposals]`

I attach two images that show the behaviour described above:
![image](https://github.com/dbeaver/dbeaver/assets/54074015/fc19403b-e131-40bf-8ee1-74cf914ab27d)
![image](https://github.com/dbeaver/dbeaver/assets/54074015/235d2cc0-ebc2-4426-91fd-5cbf275e515a)

### DBeaver Version

Community Edition 23.1.1.202306251800

### Operating System

Windows 11

### Database and driver

Database name and version: Progress OpenEdge 11.7
Driver name and versione: OpenEdge Progress JDBC driver

**Comment by E1izabeth** [comment]
@lucaperu could you try turning off this setting? Does it help?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/9bc36a10-2524-4960-ab3f-a37bfb07cf8b)

**Comment by lucaperu** [comment]
That setting is already turned off

**Comment by E1izabeth** [comment]
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by lucaperu** [comment]
These are the logs (a.log stands for .log)
[a.log](https://github.com/dbeaver/dbeaver/files/11895997/a.log)

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/11895992/dbeaver-debug.log)

**Comment by E1izabeth** [comment]
Does it still reproducible in the latest DBeaver version?

**Comment by lucaperu** [comment]
Hi E1izabeth,
               I updated DBeaver to the last version 23.2.3.202310221533 but I still get the issue.
You can see it in the 2 images I attached below.
I attached the 2 log files too, if you need them.
[dbeaver-debug.log](https://github.com
![WrongBehaviour](https://github.com/dbeaver/dbeaver/assets/54074015/14daee65-5d6c-4e26-b74d-78ee9729ad60)

![StandardBehaviour](https://github.com/dbeaver/dbeaver/assets/54074015/c8c19e5b-2d8a-490e-8c5a-b368829fe45d)
/dbeaver/dbeaver/files/13068212/dbeaver-debug.log)
[.log](https://github.com/dbeaver/dbeaver/files/13068213/default.log)

**Comment by lucaperu** [comment]
The 2 log files (a.log stands for .log)
[dbeaver-debug.log](
[a.log](https://github.com/dbeaver/dbeaver/files/13068239/a.log)
https://github.com/dbeaver/dbeaver/files/13068234/dbeaver-debug.log)

**Comment by E1izabeth** [comment]
Thank you for update

**Comment by lucaperu** [comment]
Hi E1izabeth,
             I found out that it's working now.
I didn't notice that auto-completion is case sensitive.
In my example, the schema is called PUB (uppercase) and completion works fine if I write it in uppercase.
It stops working if I write it in lowercase. 
I don't know if it was already working at the time of my first report, but now it's ok.

Thank you for your support


![2023-11-15 09_31_07-DBeaver 23 2 4-Script](https://github.com/dbeaver/dbeaver/assets/54074015/d9daaa55-cbeb-428b-95cf-40493b98aee3)
![2023-11-15 09_32_10-DBeaver 23 2 4-2-Script](https://github.com/dbeaver/dbeaver/assets/54074015/22bc3735-d68f-4dbd-9784-63c5d86909e0)

**Comment by E1izabeth** [comment]
Thank you for update. It's a good news.
Then I'm closing the issue.
