### ISSUE TITLE
'update' statament has no prompt to columns

### ISSUE THREAD

**Issue by bonaluo** [dbeaver/dbeaver#20405]
### Description

Prompt worked where columns in where statement，but not worked in set columns

### DBeaver Version

community edition 23.1.1.202306251800

### Operating System

win11 22621.1702

### Database and driver

1. mysql 5.7.31-34-log
2. driver mysql-connector-java 8.0.29

**Comment by E1izabeth** [comment]
Please provide an exact query example. I can't reproduce the issue.

**Comment by bonaluo** [comment]
<img width="360" alt="image" src="https://github.com/dbeaver/dbeaver/assets/27731323/775dd61e-91dc-44d3-8a57-90740bcc656f">
<img width="334" alt="image" src="https://github.com/dbeaver/dbeaver/assets/27731323/fb2e38d6-0395-4a92-b830-627a8c2e5f2f">

No prompt for colums in update statement but for select

**Comment by E1izabeth** [comment]
Thank you for bug report. You can turn off this setting to return that back
![image](https://github.com/dbeaver/dbeaver/assets/28875055/65983c1e-f569-47a8-a097-a40d4960edab)

**Comment by E1izabeth** [comment]
Will be done in scope of #21373
