### ISSUE TITLE
Unable to open DBeaver perspective due to NullPointerException

### ISSUE THREAD

**Issue by alex88at** [dbeaver/dbeaver#20428]
### Description

Hello,

unfortunately I am not able to open a DBeaver perspective anymore in eclipse (2023-06).
Upon opening the perspective a NullPointerException occurs and the only way to get rid of it is to force close eclipse. 
 ![image](https://github.com/dbeaver/dbeaver/assets/7046762/51b6d25b-b435-4d6d-928c-e56790f81274)

In the error log it is stated as an unhandled event loop exception.
[Error.txt](https://github.com/dbeaver/dbeaver/files/11905060/Error.txt)

Does anyone have an idea?

Thanks in advance,
Alex

### DBeaver Version

DBeaver IDE (Eclipse plugin) 23.1.1202306251800

### Operating System

Windows 11

### Steps to reproduce

1.  start eclipse
2. open DBeaver perspective

### Additional context

Additional plugins installed are SAP HANA studio tools.

**Comment by E1izabeth** [comment]
Thank you for bug report. Does your project located on the local drive? Don't you store it in some cloud like OneDrive?

**Comment by alex88at** [comment]
Hi E1izabeth,

it is stored on the local drive.

Best regards,
Alex
