### ISSUE TITLE
DatabaseProducerPageExtractSettings does not handle all NumberFormatException

### ISSUE THREAD

**Issue by tohidemyname** [dbeaver/dbeaver#20423]
### Description

The code is as follows:

 public void createControl(Composite parent) {
   ..
    try {
                    getWizard().getSettings().setMaxJobCount(Integer.parseInt(threadsNumText.getText())); //handled
                } catch (NumberFormatException e1) {
                    // do nothing
                }
   ...
  try {
                        settings.setSegmentSize(Integer.parseInt(segmentSizeText.getText())); // handled
                    } catch (NumberFormatException e1) {
                        // just skip it
                    }
    ...
    fetchSizeText.addModifyListener(e -> {
                settings.setFetchSize(Integer.parseInt(fetchSizeText.getText()));//not handled.
            });
}

### DBeaver Version

dev

**Comment by E1izabeth** [comment]
Please describe the issue you meet. Is something broken for you or you see some error?

**Comment by tohidemyname** [comment]
My stupid setting file produced an exception. It can be caused by the above code.

**Comment by E1izabeth** [comment]
Please, provide steps to reproduce.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual for you please let me know and provide additional information.
