### ISSUE TITLE
PostgreIntervalValueHandler.bindParameter can better throw DBCException

### ISSUE THREAD

**Issue by tohidemyname** [dbeaver/dbeaver#20425]
### Description

PostgreIntervalValueHandler.bindParameter throws SQLException. The other similar methods throw DBCException. The following methods are examples:
PostgreDateTimeValueHandler.bindValueObject()
PostgreContentJSON.bindParameter()

### DBeaver Version

dev

**Comment by E1izabeth** [comment]
We're open for contributions.

**Comment by E1izabeth** [comment]
There is no update on this issue, nor any PR from the reported, so I'm closing it as it's a stale now.
