### ISSUE TITLE
GenericTableBase.loadReferenceInfoList throws an odd exception

### ISSUE THREAD

**Issue by tohidemyname** [dbeaver/dbeaver#20424]
### Description

Only this method throws SQLException. The other methods of this class throw DBException. BTW, GenericProcedure.loadProcedureColumns also throws DBException

### DBeaver Version

dev

**Comment by E1izabeth** [comment]
What is the issue about? Is it only about the way some part of code is written?

**Comment by tohidemyname** [comment]
I happen to notice this code. If other programmers do not know the difference, they write the code as follows:
try{
  H2TableManager table = ..
   table.loadReferenceInfoList
}catch(DBException e){
 ...
}
However, the exception will not be caught. It can avoid such bugs if the thrown exceptions are consistent.

**Comment by LonwoLonwo** [comment]
GenericTableBase.loadReferenceInfoList throws SQLException inside the try block, and the try block has

https://github.com/dbeaver/dbeaver/blob/6b581d60199133b81d8dbd576809f58a1f06cdb6/plugins/org.jkiss.dbeaver.ext.generic/src/org/jkiss/dbeaver/ext/generic/model/GenericTableBase.java#L468-L475

So, what is the question here?

**Comment by E1izabeth** [comment]
It's been a while since no update here, but the issue still remains unclear for the team. If it is still actual please let me know and provide additional information.
