### ISSUE TITLE
download for IBM i DB2 drivers always fails

### ISSUE THREAD

**Issue by catalyst1987** [dbeaver/dbeaver#20431]
### Description

Anytime I open or close DBeaver, I get a message about downloading drivers for my connections to IBM i DB2 databases.  However, the download always errors with the following:

Driver file download failed.
Do you want to retry?

Reason:
Can't open 'https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/3.1.0/maven-antrun-plugin-3.1.0.maven-plugin': Not Found

### DBeaver Version

Community Edition 23.1.1.202306251800

### Operating System

Windows 11

### Database and driver

IBM i DB2

### Steps to reproduce

Either open or close DBeaver after configuring connections to IBM i DB2 instances.  

### Additional context

New install.

**Comment by E1izabeth** [comment]
Do you have specific network settings? Are you under the firewall? Could you open this url in your web browser?

**Comment by catalyst1987** [comment]
> 

I get a 404 when trying it in my browser.  Same if I try to open the same link on my phone which is not connected to my wifi.  I think the URL is just wrong.

**Comment by LonwoLonwo** [comment]
Reproducible. Thanks for the bug report.

**Comment by LonwoLonwo** [comment]
As a workaround, you can manually download previous driver version:

![2023-07-03 11_26_11-DBeaver 23 1 1 - _default 1_ Script-21](https://github.com/dbeaver/dbeaver/assets/45152336/84e0f4c5-fb29-4b6b-b64f-96f1903ff0a4)
