### ISSUE TITLE
Work of non-default workspace with cmd

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#20439]
### Description

STR 

1. Create a new workspace (e.g. workspace-7)
2. Open DBeaver in this new workspace-7
3. Open cmd and execute any command in cmd (e.g. dbeaver-cli -closeTabs)

Expected result: command will be executed for DBeaver in workspace-7
Actual result: DBeaver in workspace-6 will be opened

### DBeaver Version

23.1.1

### Operating System

win 10

**Comment by ShadelessFox** [comment]
We might want to be able to specify a workspace to use using the `-data` argument.

**Comment by E1izabeth** [comment]
It works as is if you specify command line parameter `-data` with the path to the non-default workspace.
For example, `.\dbeaver-cli.exe -closeTabs -data "C:\Users\user\AppData\Roaming\DBeaverData\workspace7"`

**Comment by Matvey16** [comment]
Verified
