### ISSUE TITLE
When opening a connection through the cmd, if you place the connection in a folder, it will disappear

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#20438]
### Description

STR:
1) create a new connection using  command line
 `dbeaver-cli -con "driver=sqlite|database=C:\Users\user\AppData\Roaming\DBeaverData\workspace6\.metadata\sample-database-sqlite-1\Chinook.db|name=SQLite_TEST|openConsole=true|folder=SQLite_TEST"`
2) look at Dbeaver UI - folder with the connection disappered

If you create connection without folder parameter - its ok

### DBeaver Version

23.1.1

### Operating System

win 10

**Comment by E1izabeth** [comment]
If you mean that the connection and folder doesn't exist after DBeaver restart, you might want to add `create=true` and `save=true` options. I couldn't reproduce the issue.

**Comment by E1izabeth** [comment]
I reproduced the issue. It's happening only when an instance of DBeaver is already running.

**Comment by E1izabeth** [comment]
Please clarify steps to reproduce the issue.

**Comment by MashaKorax** [comment]
You're right. If I use these parameters, then the folder with the connection is saved. But why will it be saved without these parameters if I create a connection without a folder?
For example, using this command line my connection is saved:
`dbeaver-cli -con "driver=sqlite|database=C:\Users\user\AppData\Roaming\DBeaverData\workspace6\.metadata\sample-database-sqlite-1\Chinook.db|name=SQLite_TEST2|openConsole=true"`

**Comment by E1izabeth** [comment]
Saved means persisted after DBeaver restart. Doesn't it disappear for you?

**Comment by E1izabeth** [comment]
The issue is that after navigator refresh temporarily created folder and connection are missing in the navigator list.

**Comment by E1izabeth** [comment]
We broke it in DBeaver 22.3.0

**Comment by MashaKorax** [comment]
verified
