### ISSUE TITLE
Unable to open dbeaver

### ISSUE THREAD

**Issue by SagarKaro** [dbeaver/dbeaver#20440]
### Description

Hi team,

I'm unable to open dbeaver app in my VD, but when I run it as different user it does work normally.
Version:-DBeaver Community DBeaver 21.0.4
OS:- Windows 10
steps to reproduce the issue:- When click on application shortcut, nothing happens

### DBeaver Version

DBeaver Community DBeaver 21.0.4

### Operating System

Windows 10

### Database and driver

PostgreSQL

### Steps to reproduce

1. When click on application shortcut,
2. nothing happens

**Comment by ShadelessFox** [comment]
Hello @SagarKaro,

Try uninstalling existing installations and installing DBeaver for all users using the `.msi` installer.

Please let me know if it helps.

**Comment by SagarKaro** [comment]
HI,

Out support team have tried this more than several times and the issue isn’t resolved.
As I mentioned, it work when it is accessed as different user. I guess it just happening with my access only, even though it’s a community edition which I think don’t require any purchase and opensource.

Please try to give me resolution asap.

**Comment by ShadelessFox** [comment]
Without the understanding on what is going on, we can't help, unfortunately.

But you might try the following:
- Run the executable itself. It can be located via the properties of the shortcut
- Run the executable as the administrator
- Look for [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files#log-files) and, if present and they are recent, attach here (on GitHub, not by email, please)

**Comment by SagarKaro** [comment]
Sure,
I’ll get back to you with details.

**Comment by SagarKaro** [comment]
![Dbeaver](https://github.com/dbeaver/dbeaver/assets/138221009/e8e35e27-3ae5-4c31-84da-37ee8f9695f1)
Please Check above Screenshot, as I am using community edition is it fine I’m getting asked for authentication, can this be the cause of issue?
It pops up every time I restart my VD

**Comment by ShadelessFox** [comment]
Sorry, but I don't know what this is. This is not part of DBeaver. But it might indeed cause the mentioned problem.

Please get in touch with your system administrator.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by inzamol** [comment]
Uninstall and reinstall, make sure install for all user and reset settings while install
