### ISSUE TITLE
Auto assign button disabled and Target not reflecting Source table/column CamelCase

### ISSUE THREAD

**Issue by MicJarek** [dbeaver/dbeaver#20447]
### Description

I just installed DBeaver and am trying to migrate tables/data from a MS SQL Server DB to latest PostgreSQL on a local Windows 10 machine. The MS SQL Server is running on a local NT Server, but the PostgreSQL is installed on a local machine. The replication works great except the CamelCase is NOT being reflected in the migration (see screenshots below.)  Note that the 'Auto assign' button is also disabled. 

![image](https://github.com/dbeaver/dbeaver/assets/17038597/7cae9c30-d996-4138-93df-aee62ff2813b)
I've noticed that with the same MS SQL Server selected as Target container, the table name/column names are set correctly, BUT when I change the Target container to PostgreSQL, all the names reset to lower case (see above pic). 
![image](https://github.com/dbeaver/dbeaver/assets/17038597/06e3f465-4a9b-4504-b0a4-1135f25376d0)

Am I not setting/selecting something correctly, or is this a bug?

### DBeaver Version

Version 23.1.1.202306251800

### Operating System

Windows-10-10.0.19045-SP0

### Database and driver

PostgreSQL 15.3, compiled by Visual C++ build 1914, 64-bit
net.postgis:postgis-jdbc:RELEASE Version: 2.5.0

MS SQL Server 2014
Microsoft JDBC Driver for SQL Server Authentication Library for Windows Version: 9.2.0.x64

### Steps to reproduce

1. Select a table in MS SQL Server i.e. dbo.Media (see above pic)
2. Click RMB and select 'Export Data'.
3. In the dialog box, for 'Export Target' select 'Database' and click 'Next>'
4. In 'Tables Mapping', select 'Target Container': If the existing MS SQL Server container (LimitedPlay.dbo [LimitedPlay]) is selected, the Target table name and column names correctly display in CamelCase, BUT if the PostgreSQL is selected as that 'Target Container (LimitedPlay.dbo [LimitedPlayPGSQL]), the table name and all column names are reset to lower case.
5. NOTE: that the 'Auto assign' button is also disabled.

**Comment by Matvey16** [comment]
@MicJarek That is an expected behavior. PostgreSQL uses lowercase by default so column names are automatically lowercased (you can change them to camel case manually), column names would be uppercased for uppercase DBs like Oracle.
On your second screenshot the names are camelcased because they already exist and are not being created from scratch.

**Comment by MicJarek** [comment]
@Matvey16 Thank you for the clarification. But if I can change the table/column names manually, then apparently it is not a standard that MUST be followed. And therefore, I suggest that you should be able to automatically retain the CamelCase if you choose (by perhaps using the 'Auto assign' button).

The reason I suggest this is that when moving from one DB to another there are other factors involved such as stored procedures, functions, and even developer/DBA comfortableness that will have a bearing on the case syntax. Having the option to retain the original case for the table/column names rather than having to manually change dozens (perhaps hundreds) of them manually would be of great help.
