### ISSUE TITLE
Postgres data types UUID and TEXT not styled in SQL editor

### ISSUE THREAD

**Issue by wistlo** [dbeaver/dbeaver#20446]
### Description

A minor issue, Postgres data types **TEXT** and **UUID** appear as plain text in SQL code:
![image](https://github.com/dbeaver/dbeaver/assets/154039/6bddd5aa-71ba-40db-956f-e9803113c81c)

VARCHAR shown for expected styling.

In PostGRES: 

- UUID is a data type, not a keyword.  
- TEXT is both data type and keyword.

**REFERENCES**: 

Postgres references for [data types](https://www.postgresql.org/docs/15/datatype.html) and [keywords](https://www.postgresql.org/docs/current/sql-keywords-appendix.html)

[dbeaver source code](https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreDialect.java) (maybe?)

_Looks like a simple fix, just adding TEXT and UUID as defined "keywords" (though only one is formally defined as such by PostGRES) .  If so, I'm considering having a go at it myself (would be first contribution), but if there's more to it, I won't touch it  ._  

### DBeaver Version

Community 23.1.1.202306251800

### Operating System

Windows 11 21H2 (22000.2057)

### Database and driver

PostgresSQL 15.3
PostgreSQL JDBC Driver postgresql-x64-15

### Steps to reproduce

Write SQL code.
Declare a TEXT or UUID type, or cast to UUID or TEXT type. 
Type defining word appears in plain text

### Additional context

I have DevStyle Themes installed but disabled for the example shown here.  Behavior is the same in DevStyle themes.

**Comment by E1izabeth** [comment]
To add UUID highlighting you need to add this keyword to `PostgreDialect.POSTGRE_EXTRA_KEYWORDS`.

TEXT keyword is highlighted for me as it's declared in `JDBCSQLDialect.LONG_TEXT_TYPES`. I doubt why it doesn't work in your case.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/c8cf717b-4a8c-490f-88be-878d316c5649)

**Comment by E1izabeth** [comment]
@wistlo could you share your plans: will you make a PR?

**Comment by wistlo** [comment]
No, no time right now, looking for new job as company is eliminating remote work and I'm 900 miles from the office.  

Paying attention here for next time, though.

**Comment by E1izabeth** [comment]
Okay then. We will fix it on our own.

**Comment by guilhermepereira2917** [comment]
@E1izabeth are you working on this? I would like to do it.

**Comment by E1izabeth** [comment]
@guilhermepereira2917 no, you can work on this issue 😊
