### ISSUE TITLE
how to use ssh setting ?

### ISSUE THREAD

**Issue by timeisgoing** [dbeaver/dbeaver#20449]
hello，
I want to use this tool in production environment. However, in the production environment, I have to log in to the jumpserver a, and then go to the target host-b before I can log in to the database-c. Can this kind of proxy be set up using ssh?
Thanks

**Comment by E1izabeth** [comment]
Are you looking for this https://dbeaver.com/docs/wiki/SSH-Configuration/#configuring-gateway-host?
