### ISSUE TITLE
Not able to create a foreign key in MYSQL.

### ISSUE THREAD

**Issue by Roshang2003** [dbeaver/dbeaver#20448]
### Description

I am using DBeaver with Mariadb, so I have two tables in a database, and I have to use primary key of first table as a foreign key in second table, but when I am doing so OK button is disabled, I don't know why is it so, Please help me out ASAP, Thanks in advance.
![image](https://github.com/dbeaver/dbeaver/assets/107313954/2fb17aa6-ab52-413b-ad54-b1db0a5cf26b)

### DBeaver Version

 23.1.0

### Operating System

Windows 11

### Database and driver

MariaDB

### Additional context

I have two tables, so to connect them, I wants to use primary key of first table as a foreign key in second table.
but OK button is disable I don't know why. steps which I followed are : 
1. I clicked on foreign key option in second table, right clicked.
2. clicked on this option "Create New foreign key".
3. then in pop up, I selcted first table and its primary key which is only option to select.
4. 
![image](https://github.com/dbeaver/dbeaver/assets/107313954/575eae72-88d2-4b31-985d-cb8324424558)

**Comment by E1izabeth** [comment]
Please, click on `Column` field and choose the column you want. You can't create a foreign key without specifying a column.

**Comment by Roshang2003** [comment]
Since I was not able to do that, I did it by writing sql query, Thanks for your response.
