### ISSUE TITLE
 I installed Dbeaver and when importing my db I can't change some things in a simple way.

### ISSUE THREAD

**Issue by jeolopes** [dbeaver/dbeaver#20452]
I installed Dbeaver, and when importing my db, I can't change the column's data type when I click, only through the sql editor. Is there any blocking of the community version or is there something I should do? sorry for the ignorance, but I'm starting and would love to use dbeaver for product reviews.

![erro](https://github.com/dbeaver/dbeaver/assets/50079830/7c573d8c-8d61-4c69-82f9-265e84390ec7)

**Comment by E1izabeth** [comment]
What database do you use?

**Comment by jeolopes** [comment]
sqlite.

**Comment by E1izabeth** [comment]
It looks like a duplicate of #19973
We don't support columns editing for created tables as SQLite doesn't support it. The only way s to recreate a table.

Closing as a duplicate of #19973

**Comment by E1izabeth** [comment]
You can vote under that issue with 👍🏻

**Comment by jeolopes** [comment]
Excuse my ignorance, but what would be a duplicate of #19973?

**Comment by E1izabeth** [comment]
Your issue is about the possibility of changing columns data type in SQLite. That issue is about the same.
