### ISSUE TITLE
postgresql, keep keywords uppercase and database table/column names lowercase 

### ISSUE THREAD

**Issue by hfcheng66** [dbeaver/dbeaver#20463]
### Description

I wanted keywords to be uppercase and database table/column names lowercase.

Currently:
- type "select" and space, it keeps lowercase as typed.
- type "sel" and "Enter" followed by space, it get the uppercase value from the autocomplete.
- what I would like to is always covert to uppercase for sql keywords.
Same behavior for table/column names.

I have tried changing below two options but none achieve what I wanted:
Editors -> Code Completion: Insert case
Editors -> Code Editor -> Auto format: convert keyword case

Is this possible? If so what configuration changes do I need? 

Thanks.

### DBeaver Version

community version Version 23.1.1.202306251800

### Operating System

Apple M1 Pro 13.4.1

### Database and driver

PostgreSQL 12.11
PostgreSQL JDBC Driver 42.5.0

**Comment by E1izabeth** [comment]
#9349

**Comment by Matvey16** [comment]
@hfcheng66 Have you tried changing keyword case option in formatting tab of SQL editor preferences?
![image](https://github.com/dbeaver/dbeaver/assets/82543000/e83dcfd8-21b7-4f39-a61b-db2c3e742119)

**Comment by hfcheng66** [comment]
the format option works great, thank you!
