### ISSUE TITLE
 Deleted project comes back after reopening DBeaver

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#20471]
### Description

If you try to delete a project without enabling the checkbox  "delete project contents on disk" it comes back after reopening DBeaver
![dbeaver_tggDJRmTUq](https://github.com/dbeaver/dbeaver/assets/84867187/5958af4f-7939-4e59-8060-815d98d7b0e4)

### DBeaver Version

23.1.1

### Operating System

win 10

**Comment by Matvey16** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/dbeaver/project/8805?defectId=14278)
