### ISSUE TITLE
Use of Oracle variables using DBeaver

### ISSUE THREAD

**Issue by imarquez2** [dbeaver/dbeaver#20488]
Hi

I'm working with a Oracle database, and i'm trying to call a store procedure with a OUT parameter and it is not working using DBeaver. I'm receiving an error.

The OUT parameters is SYS_REFCURSOR type and i'm trying to define a variable, include that variable into the store procedure call and finally trying to print the result.

Could you help me?.

@set result=null
CALL GET_INFO(676,:result)
SELECT :result

create or replace PROCEDURE "GET_INFO" 
(
  VAR_ID IN NUMBER
, RESULT	OUT	SYS_REFCURSOR
.
//.str_query is a select sentence
.
.OPEN RESULT for str_query;
END GET_INFO;

**Comment by flambchap** [comment]
Hi  @imarquez2, Can you please show me a video with the error you see?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
