### ISSUE TITLE
Right click context menu is empty app wide, menu items appear when in focus

### ISSUE THREAD

**Issue by collkm** [dbeaver/dbeaver#20487]
### Description

The right-click context menu is empty and white anywhere I right-click within the app. When I hover the mouse over the menu, each menu item appears as it is focused on by the mouse. See attachments for clarification.

* I just updated the application version 23.1.1
* Behavior is consistent when using Classic, Light, and Dark mode
* Persists when closing and restarting app

![2023-07-05_dbeaver_context-menu-1](https://github.com/dbeaver/dbeaver/assets/70382144/fd21a8b8-d2dd-43ce-8bfd-3a68feda6f76)
![2023-07-05_dbeaver_context-menu-2](https://github.com/dbeaver/dbeaver/assets/70382144/38f1fb81-d391-4246-8d06-420bb5594909)

### DBeaver Version

Community Edition 23.1.1

### Operating System

Windows 10

### Steps to reproduce

1. Run new application.
2. Right click on any entity with context (menu is always white and appears empty).
3. Hover mouse over menu (menu items become visible as they come into focus).

**Comment by LonwoLonwo** [comment]
Hello @collkm 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by collkm** [comment]
@LonwoLonwo I found this morning that some other applications were exhibiting the same behavior with context menus, making me suspect issue is with OS. After restarting my computer, I am not seeing this issue any more.
Sorry for the false alarm...

**Comment by LonwoLonwo** [comment]
Thanks for the answer @collkm
