### ISSUE TITLE
Language preferences not being applied

### ISSUE THREAD

**Issue by caiocinel** [dbeaver/dbeaver#20497]
### Description

Since the last update, the language of the application has been changed to Portuguese and I cannot change the language to any other, when restarting the machine language (Portuguese) remains active and in the preferences settings "English" is displayed.

### DBeaver Version

Community Edition 23.1.1.202306251800

### Operating System

Windows 11 22H2

### Database and driver

PostgreSQL 14 -> PostgreSQL standard driver
MySQL 8 -> Driver for MySQL 8 and later

### Steps to reproduce

On top menu:

Janela -> Preferências -> Interface de Usuário -> Idioma -> (Change to English/Spanish) -> Apply -> Yes -> Yes

The application will be restarted, but the language will not change.

**Comment by ShadelessFox** [comment]
Hello @caiocinel,

Are you running DBeaver using the shortcut? If so, open its properties and remove the `-nl en` part from the "target".

Please let me know if it helps.

**Comment by caiocinel** [comment]
Thanks!
