### ISSUE TITLE
Not able to connect to DB

### ISSUE THREAD

**Issue by SachinGuddad** [dbeaver/dbeaver#20491]
### Description

Can't create driver instance
  Error creating driver 'SQLite' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.sqlite.JDBC'
  Error creating driver 'SQLite' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.sqlite.JDBC'
    org.sqlite.JDBC
    org.sqlite.JDBC

### DBeaver Version

DBeaver Community 23.1.1

### Operating System

Windows 11

### Database and driver

Any of the DBs and drivers not able to connect and use.

### Steps to reproduce

1. I try to connect the SQLite DB but failed to connect due to jar files are missing.

### Additional context

Example :
Can't create driver instance
  Error creating driver 'SQLite' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.sqlite.JDBC'
  Error creating driver 'SQLite' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.sqlite.JDBC'
    org.sqlite.JDBC
    org.sqlite.JDBC

**Comment by LonwoLonwo** [comment]
Hello @SachinGuddad 

Does your internet connection is stable? Does DBeaver have permission to download files on your PC?

Please provide a screen from the libraries section of your connection page.

![2023-07-06 13_39_38-DBeaver Ultimate 23 1 2 - DEPARTMENT](https://github.com/dbeaver/dbeaver/assets/45152336/46cf5564-530b-461a-be12-353f7af0443b)

Additionally, if you can not download driver files automatically via DBeaver - you can download and add them manually in the libraries section ("Add file").

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
