### ISSUE TITLE
The time zone cannot be changed. 

### ISSUE THREAD

**Issue by junwei-liu** [dbeaver/dbeaver#20490]
### Description

The time zone cannot be changed. After selecting the specified time zone, the save will not take effect. Open the time zone selection again, and **the default time zone is still displayed**.

### DBeaver Version

23.1.1.202306251800

### Operating System

Mac os 14.01

### Steps to reproduce

**preference-- user interface -- regional setting，**

After the default time zone is changed, saving will not take effect, and after saving, it will still be displayed as the default time zone when entering again.

**Comment by flambchap** [comment]
I cannot reproduce the issue on macOS 13.4.1.

**Comment by junwei-liu** [comment]
> 
![image](https://github.com/dbeaver/dbeaver/assets/78710778/3197bd4b-7db1-45a1-a88f-98292349ce4f)

**Comment by MashaKorax** [comment]
I cant reproduce it on mac OS 12 (M1) as well. Specify settings exactly according your screenshot

**Comment by flambchap** [comment]
It can be an issue specific to macOS 14, in which case we need to wait for its official release.

**Comment by MashaKorax** [comment]
@junwei-liu, it looks like the beta version of macOS 14 might cause this issue

**Comment by MashaKorax** [comment]
I cant reproduce it on mac OS 14

**Comment by pyang30** [comment]
DBeaver Version
Version 23.3.1.202312241705

Operating System
Mac os 13.5.1 (22G90)  M2

I got the same problem, I want to change timezone from Default to Asia/Shanghai, but it does not work.

**Comment by joelkim** [comment]
+1 same in MacOS 14.3.1 intel
