### ISSUE TITLE
"Return to auto-commit on transaction end" setting on by default for production connections

### ISSUE THREAD

**Issue by FunctionalHacker** [dbeaver/dbeaver#20507]
### Description

Recently we noticed a change in the default behaviour of dbeaver at our company. All production connections now have the "Return to auto-commit on transaction end" on by default.

![image](https://github.com/dbeaver/dbeaver/assets/16839187/08c6a619-a9eb-4542-bb9a-2319216909e9)

This is not exactly a bug but in my opinion it's quite a dangerous default and making this change unannounced can result in unexpected data loss. For example this will result in permanent data loss

```sql
SELECT * from foobar;
-- DBeaver has now returned to auto-commit mode
DELETE from foobar;
```

### DBeaver Version

Community 23.1.1.202306251800

### Operating System

Ubuntu 22.04

### Database and driver

PostgreSQL

### Steps to reproduce

1. Connect to a production database
2. Run a select query
3. Observe that auto-commit mode is on

**Comment by FunctionalHacker** [comment]
This default seems also to conflict with my connection type settings
![image](https://github.com/dbeaver/dbeaver/assets/16839187/faaf70ef-5e38-4c23-91c3-872ce331d231)

**Comment by LonwoLonwo** [comment]
Thanks for the report @FunctionalHacker
