### ISSUE TITLE
automatic refresh interval for Sessions and Locks Editor

### ISSUE THREAD

**Issue by MahatmaFatalError** [dbeaver/dbeaver#2050]
Especially when someone want to monitor open locks or sessions it is quite annoying to constantly press F5 in order to refresh the table view. Therefore there should be a Combobox to choose the refresh interval rate, e.g. manual (default), 1s, 5s, 10s

**Comment by mathiasgrimm** [comment]
+1

**Comment by rperre** [comment]
+1

**Comment by serge-rider** [comment]
Auto-refresh for sessions and locks will be added in 5.0:

![image](https://user-images.githubusercontent.com/6398845/36602486-364894f8-18c9-11e8-8be3-014224a1efbe.png)

**Comment by MahatmaFatalError** [comment]
Thx!

**Comment by rscs** [comment]
This is great!  Thank you!

The feature works wonderfully in my testing.  I would just personally change "Refresh each X seconds" to "Refresh every X seconds".  The English sounds better that way.

**Comment by serge-rider** [comment]
Yep. 
This will be fixed as a part of #2050
