### ISSUE TITLE
The TDengine driver is not available from version 23.1.1

### ISSUE THREAD

**Issue by from0to1-lhc** [dbeaver/dbeaver#20506]
### Description

![微信图片_20230707174723](https://github.com/dbeaver/dbeaver/assets/18431865/a2ddf5ba-cecf-445e-9c48-6cb53cab46a5)

### DBeaver Version

Community Edition 23.1.1

### Operating System

windows 10

**Comment by LonwoLonwo** [comment]
Hello @liuhuacong 

Could you please check the latest Early Acces version about this issue? https://dbeaver.io/files/ea/

**Comment by from0to1-lhc** [comment]
> 你好@liuhuacong
> 
> 您能否检查一下最新的 Early Access 版本是否存在此问题？https://dbeaver.io/files/ea/

so good,I tried it, no problem,thank
