### ISSUE TITLE
Change tablespace in Database editor

### ISSUE THREAD

**Issue by MahatmaFatalError** [dbeaver/dbeaver#2051]
All fields in the database editor seems to be read only. Sometimes you need to migrate a database to another table space. Therefore it would be great to make that field changeable. Furthermore, owner should also be changeable.

`ALTER DATABASE <dbname>  SET TABLESPACE <newTableSpace>`

**Comment by serge-rider** [comment]
Sorry, missed that.
What database do you mean? This feature already supported for Oracle.

**Comment by MahatmaFatalError** [comment]
> What database do you mean? This feature already supported for Oracle.

nP, I'm referring to PostgreSQL
