### ISSUE TITLE
Query manager filter "Entries per page" shows incorrect number of queries

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#20516]
### Description

https://github.com/dbeaver/dbeaver/assets/84867187/b131ed87-fd1b-4676-bb2a-174e8a412782

incorrect number of rows shown after applying filter in Query Manager

### DBeaver Version

23.1.2

### Operating System

win 10

**Comment by E1izabeth** [comment]
Don't actual since we removed this setting in #20522
