### ISSUE TITLE
UUID Column in MongoDB displays "Binary" instead of string

### ISSUE THREAD

**Issue by cobap** [dbeaver/dbeaver#20513]
### Description

As can we seen [here](https://github.com/orgs/dbeaver/discussions/20154#discussioncomment-6087756) there is some conditions in which a database in mongo setup to have ID as UUID is showing only "Binary" instead of the UUID output from the database

![image](https://github.com/dbeaver/dbeaver/assets/6344807/76094175-7bc4-44ed-960c-87cf6968bb47)
![image](https://github.com/dbeaver/dbeaver/assets/6344807/6b90e8a2-8d5b-42e9-9a9f-4532bbf6f4a8)

### DBeaver Version

DBeaver Enterprise 23.0.0

### Operating System

Windows 11

### Database and driver

1. org.jkiss.jdbc.mongodb.mongodbDriver (cql - Driver for MongoDB)

### Steps to reproduce

1. Create a collection on mongo
2. Add a document with the UUID as ID
3. Connect on Dbeaver PRO
4. Execute a SELECT * FROM _path_

**Comment by E1izabeth** [comment]
Thank you for bug report

**Comment by mkgrgis** [comment]
Also this is applicable to Oracle `RAW(16)` and SQLite `blob` with 16 bytes.

**Comment by E1izabeth** [comment]
@mkgrgis please create a separate issue for your case.

**Comment by mkgrgis** [comment]
@E1izabeth , for Oracle there is https://github.com/dbeaver/dbeaver/issues/18091

**Comment by E1izabeth** [comment]
Thanks, @mkgrgis . You can vote for the issue with 👍🏻 under the issue description.

**Comment by mkgrgis** [comment]
Thanks, @E1izabeth , I have voted.

**Comment by cobap** [comment]
@E1izabeth all good? I was checking the issue #18091 and your suggestion there also does not apply to my case (I saw similar suggestions over the internet)

![image](https://github.com/dbeaver/dbeaver/assets/6344807/72289a57-b7a5-45ed-b4fc-80725eb46782)

**Comment by E1izabeth** [comment]
@cobap not sure how it may help in your case

**Comment by cobap** [comment]
Team, is there any update on this issue? @E1izabeth

**Comment by E1izabeth** [comment]
@cobap We haven't fixed it yet.

**Comment by E1izabeth** [comment]
@cobap does it still reproducible for the latest DBeaver version?

**Comment by E1izabeth** [comment]
Never mind, I reproduced the issue

**Comment by cobap** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/6344807/65137220-5764-426b-bb4f-3daa36a3f19f)

@serge-rider @E1izabeth can you please detail since this was fixed what are the steps to enable it? I just updated dbeaver but still see not change

**Comment by E1izabeth** [comment]
@cobap The fix will be available in the next release.
Also you could check early access version here https://dbeaver.com/files/ea/enterprise/
