### ISSUE TITLE
SSH connection defaults to OS login, if server login not saved in settings

### ISSUE THREAD

**Issue by brother-z** [dbeaver/dbeaver#20529]
### Description

It's related to credential popup changes from #18017 - now if SSH is set to use encrypted certificates there will be a popup asking for certificate password, but there's no way to enter server login. If the login is stored in settings - it will work - but in case the login is left empty, the connection will default to OS login.

### DBeaver Version

Community Edition 23.1.2

### Operating System

Windows 10

### Steps to reproduce

1. Configure SSH with jump server (probably without the jump server will be the same)
2. Use encrypted certificate as auth, leave passphrases blank
3. Leave the "user name" blank
4. Try to connect
The connection will ask for passphrase, but not for login and then it will default to using OS user name as SSH server login.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by brother-z** [comment]
And a quick update - exact same thing happens when using "agent" as auth method, without SSH user name stored in config. The only difference - there's no popup, because there's no password to ask for, so the connection just defaults to OS user and then fails to connect (because that user does not exist on SSH server).
