### ISSUE TITLE
Investigate the usage of `Entries per page` setting

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#20522]
### Description

We have a setting `Entries per page` in Query Manager, but we don't have pagination in Query manager. Let's find out what does this setting do and make it clear or remove this setting if there is no usage of it.

### DBeaver Version

DBeaver 23.1.2

### Steps to reproduce

https://github.com/dbeaver/dbeaver/assets/28875055/7728f8d5-19c3-474a-86ac-cde5a7ac1cda

**Comment by uslss** [comment]
https://github.com/dbeaver/dbeaver/assets/31996417/fc28d128-588c-4937-91e3-00bb0584a60b

only the last query is shown
