### ISSUE TITLE
Autocomplete no longer working as expected (snowflake)

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#20525]
### Description

Two releases ago, autocomplete worked as expected for lowercase syntax.

Post release, lowercase stopped working (see below for screenshots).

![Screenshot 2023-07-10 at 10 37 15 AM](https://github.com/dbeaver/dbeaver/assets/85576814/0cb4e74f-f114-42aa-8cdc-e7349c53b096)
![Screenshot 2023-07-10 at 10 36 42 AM](https://github.com/dbeaver/dbeaver/assets/85576814/91b8437c-5970-4050-aff2-018842a45314)

### DBeaver Version

Community Edition Version 23.1.2.202307091549

### Operating System

macOS Ventura 13.2.1

### Database and driver

1) Snowflake 7.22.2
2) snowflake-jdbc 3.13.6

### Steps to reproduce

1) type `select * from <database>.` in all lowercase
2) observe auto completion fail (ctrl/cmd+space to bring up _no proposals_)
3) type `select * from <DATABASE>.` in uppercase
4) observe auto completion success

**Comment by LonwoLonwo** [comment]
Hello @murphymoulds-palmetto 

Unfortunately, I can't reproduce your issue.

![2023-07-11 09_46_05-](https://github.com/dbeaver/dbeaver/assets/45152336/5786c52a-5555-41d8-8c7c-21aaf32874d7)

Autocompletion works for me in both cases.

Does autocomplete work for you after step 4 for lowercase? After data loading.
Could you please check the [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) (with enabled filters) at the moment of the auto-completion on the dot focus (step 2)?
Could you observe these commands?:

`-- Load schemas [SANDBOX, %]`

or

`-- Load schemas [sandbox, %]`

**Comment by ghost** [comment]
Hi @LonwoLonwo, thank you for taking a look!

> Does autocomplete work for you after step 4 for lowercase?

Negative, it does not work. When doing the cmd+space, this is what I see:

![image](https://github.com/dbeaver/dbeaver/assets/85576814/33f3caef-e3ca-4356-987b-d46145e61848)

> After data loading. Could you please check the [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) (with enabled filters) at the moment of the auto-completion on the dot focus (step 2)? Could you observe these commands?:

`-- Load schemas [SANDBOX, %]` shows up as expected.
`-- Load schemas [sandbox, %]` does not.

**Comment by MashaKorax** [comment]
Have you got simultaneously 2 schemas - sandbox in lowercase and SANDBOX in uppercase?

**Comment by ghost** [comment]
> Have you got simultaneously 2 schemas - sandbox in lowercase and SANDBOX in uppercase?

We do not have two databases called Sandbox.

**Comment by iraidaa** [comment]
Could you please send the log files https://dbeaver.com/docs/wiki/Log-files/?

**Comment by ghost** [comment]
> Could you please send the log files https://dbeaver.com/docs/wiki/Log-files/?
I cleared log file and repeated the steps above, nothing captured.

I did confirm with a colleague that theirs is not impacted; perhaps it has to do with my settings. I'll do a fresh install and see if that resolves.

**Comment by ghost** [comment]
Resolved with fresh install 😵‍💫 🤦 thank you all for playing a fun game of tag!

**Comment by E1izabeth** [comment]
Thank you for update!
