### ISSUE TITLE
Btn "create project" appear in project tab only after swithing to database navigator

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#20520]
### Description

STR

1. Close DBeaver being in project tab
2. Open DBeaver again
3. Look at the project toolbar - Btn "create project" should be there, but no
4. Switch to database navigator and back to the project tab - Btn "create project" appeared

https://github.com/dbeaver/dbeaver/assets/84867187/eec28cd9-1cf0-4922-a488-cb610b993746

### DBeaver Version

23.1.2

### Operating System

win 10

**Comment by E1izabeth** [comment]
Seems it has been fixed by https://github.com/dbeaver/dbeaver/pull/32346
