### ISSUE TITLE
Order case insensitive as an option at the Client Side 

### ISSUE THREAD

**Issue by vijayap20** [dbeaver/dbeaver#20528]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by E1izabeth** [comment]
Please add more details. It's not clear why do you need this and what is the use case.

**Comment by vijayap20** [comment]
> **Is your feature request related to a problem? Please describe.**
>  yes 
> **Describe the solution you'd like**
>  Have added a new preferences  as case insensitive at the cilent side to order by. attached the video for references [](url)
> **Describe alternatives you've considered**
> 
> **Additional context**


https://github.com/dbeaver/dbeaver/assets/137312001/1cf2ca2e-4ea0-43cb-9733-4fe5651e1a5c
