### ISSUE TITLE
PostgreSQL: Create Role Wizard

### ISSUE THREAD

**Issue by MahatmaFatalError** [dbeaver/dbeaver#2052]
In the Roles context menu it should be possible to open a wizard to create a  new role. The wizard should consist of pages which contain the following configuration items:
- name
- password (password repetition)
- privileges (like superuser, can create database, roles etc.)
and optionally
- connection limit and expiration date for that user

**Comment by clounie** [comment]
Agreed..seems like a pretty foundational feature.

**Comment by Wirone** [comment]
Wizard should allow also viewing/setting attributes like `search_path`.

Today for testing some libraries I used MySQL instead of Postgresql because of lack of this functionality (there is wizard for MySQL) :smiley:

**Comment by serge-rider** [comment]
This is actually duplicate of #1712
