### ISSUE TITLE
Please change the depressing brown picture at the start of the program

### ISSUE THREAD

**Issue by andreysneg** [dbeaver/dbeaver#20546]
Please change the depressing brown ugly picture at the start of the program.

When I see her, I immediately do not want to work. Now I close eyes when start DBeaver .

Maybe programm have options for disable this picture ? 

Thank you

**Comment by E1izabeth** [comment]
You may try adding `nosplash` parameter.
See more here https://dbeaver.com/docs/wiki/Command-Line

**Comment by andreysneg** [comment]
Thank you. It works.

P.S. As a designer, I advise you to change the splach and abandon the brown light in the design of the program and the site. 
Brown color does not motivate and repels.

Use bright orange - #EB8A20  . And your sales go up 2 times

Example:
https://bit.ly/3PR3BB2

**Comment by E1izabeth** [comment]
Thank you for suggestion
