### ISSUE TITLE
Incorrect sql generated for a sequence

### ISSUE THREAD

**Issue by tsilverstein** [dbeaver/dbeaver#20548]
### Description

DDL SQL generated for a sequence is not correct when the sequence is created with 'MINVALUE 0' and 'START WITH 0'.

### DBeaver Version

Community Edition Version 23.1.2.202307091549

### Operating System

macOS Ventura 13.4.1

### Database and driver

PostgreSQL 14.6 on x86_64-pc-linux-gnu, compiled by x86_64-pc-linux-gnu-gcc (GCC) 7.4.0, 64-bit
PostgreSQL standard driver postgres-jdbc

### Steps to reproduce

1. Create sequence as:
`create sequence primary_edge_id minvalue 0 maxvalue 255 start with 0 cycle;`

2. Select the sequence and then Generate SQL > DDL
The following is produced:
`CREATE SEQUENCE primary_edge_id
	INCREMENT BY 1
	NO MINVALUE
	MAXVALUE 255
	CACHE 1
	CYCLE;`

3. Delete the sequence and recreate it with the sql produced in step 2.

4. The new sequence behaves as if it has MINVALUE 1.

**Comment by LonwoLonwo** [comment]
Thanks for the report
