### ISSUE TITLE
Link ppa not updated on Ubuntu since version 23.1.1

### ISSUE THREAD

**Issue by larissaavila** [dbeaver/dbeaver#20559]
### Description

Hello, I've found some [similar issues](https://github.com/dbeaver/dbeaver/issues/19891#issue-1698064239) at different moments.

Could you update the version on ppa?

Thank you!

### DBeaver Version

Community Edition 23.1.1

**Comment by E1izabeth** [comment]
Thank you for report. We'll update it.

**Comment by serge-rider** [comment]
PPA package has been updated
