### ISSUE TITLE
PostgreSQL: Improvements to Execution Plan of EXPLAIN ANALYZE

### ISSUE THREAD

**Issue by MahatmaFatalError** [dbeaver/dbeaver#2056]
The Exec. Plan is great but in order to make it more understandable and easier to read and find the critical parts of the plan the table should be better visualized, e.g. colorized cells by duration time.

Please have a look at https://explain.depesz.com/ (find some examples under "History" and explanation under https://explain.depesz.com/help ) which has a intuitive cell coloring and also a nice Stats overview.

Another example for a graph view would be http://tatiyants.com/pev/#/plans/plan_1503387358333 which could be an alternate view to a table based view

**Comment by uslss** [comment]
already implemented
![image](https://user-images.githubusercontent.com/31996417/105165745-c7de0300-5b27-11eb-9995-049a44c21bf0.png)

**Comment by MahatmaFatalError** [comment]
@uslss I assume there is a misunderstanding. I changed the title to make it more obvious. As you can see here
![dbeaver explain analyze without color coding](https://user-images.githubusercontent.com/776825/105228658-21afee80-5b63-11eb-8be8-2112f0c57b44.png)
DBeaver does not show any color coding of cells depending on their impact on the performance compared to
![explain analyze with color coding](https://user-images.githubusercontent.com/776825/105228791-47d58e80-5b63-11eb-9dff-1ae5ec0cd67a.png)

Highlighting the most expensive operators is very beneficial especially for huge plans to quickly grasp the pain points. That's why I linked the help page to explain the color-coding
![grafik](https://user-images.githubusercontent.com/776825/105229134-c3374000-5b63-11eb-83ab-ec19a3cfd0b9.png)
