### ISSUE TITLE
Data migration

### ISSUE THREAD

**Issue by ChenpiDog** [dbeaver/dbeaver#20566]
Homogeneous or heterogeneous database, table Data migration, table can be selected in batch. Case: I want to migrate 50 tables from a Postgre database to another Postgre database.
The function of importing data can only operate on one table at a time, and OOM occurs when the data volume is large.

**Comment by flambchap** [comment]
@ChenpiDog You can transfer any number of tables at a time using Data Transfer. I suggest selecting all of the tables you want to transfer -> Right mouse click -> Export data.

**Comment by ChenpiDog** [comment]
> @ChenpiDog You can transfer any number of tables at a time using Data Transfer. I suggest selecting all of the tables you want to transfer -> Right mouse click -> Export data.

Yes, I saw that it is necessary to create target tables in advance or create new target tables one after another during export. If I want to do Data migration of many tables, it is not convenient. It would be great if Dbeaver could automatically create tables in the target segment.

**Comment by ChenpiDog** [comment]
> @ChenpiDog You can transfer any number of tables at a time using Data Transfer. I suggest selecting all of the tables you want to transfer -> Right mouse click -> Export data.

Okay, I tried using Export data to migrate a Greenplum table, but there was a problem.

![image](https://github.com/dbeaver/dbeaver/assets/55483982/136c40d9-458f-4f76-942a-37e73d5b0ec9)

**Comment by ChenpiDog** [comment]
@n5a5 I don't know how the above issue was caused, but I also encountered this issue when I switched to the latest version. On another computer, without this issue, I tried to migrate a table with a relatively large amount of data. Encountered two issues:
1) The distribution strategy of the target side greenplum table automatically created by Dbeaver is different from that of the source side;
2) After migrating some data, an exception of duplicate key will be reported.

**Comment by ChenpiDog** [comment]
@n5a5 To add, the table automatically created by DBeaver has no primary key, and the field is allowed to be empty, but the source table has a primary key, and the field is not allowed to be empty. I manually created a table on the target side that is the same as the source side, and encountered the second problem above. If you let DBeaver automatically create tables, you will not encounter the second problem above, but if the table data volume is relatively large, you will encounter OOM problems. My computer has 16G memory.
I want something like this:
1) The table structure automatically created by DBeaver should be as consistent as possible with the original table, including primary key, other constraints, distribution strategy, etc.;
2) When data migration encounters a primary key conflict, it can overwrite the update;
3) Try to optimize the PC with low configuration to avoid OOM problems.

**Comment by ChenpiDog** [comment]
![8210e3cb193ad2f59b1b3f54585ecd0](https://github.com/dbeaver/dbeaver/assets/55483982/d5f86690-4c35-48f9-9377-fb2c4b016b37)

**Comment by MashaKorax** [comment]
@ChenpiDog could you please try this replace method?  ON CONFLICT DO UPDATE SET
![dbeaver_jmJLLjYTec](https://github.com/dbeaver/dbeaver/assets/84867187/fc3350ae-d454-47ea-a874-2b108a21b0be)

**Comment by ChenpiDog** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/55483982/7fe581d3-bf17-486c-8de4-d8f552737c5f)
@MashaKorax option is blank

**Comment by ChenpiDog** [comment]
@MashaKorax OK

**Comment by ChenpiDog** [comment]
> > @ChenpiDog You can transfer any number of tables at a time using Data Transfer. I suggest selecting all of the tables you want to transfer -> Right mouse click -> Export data.
> 
> Okay, I tried using Export data to migrate a Greenplum table, but there was a problem.
> 
> ![image](https://user-images.githubusercontent.com/55483982/253443136-136c40d9-458f-4f76-942a-37e73d5b0ec9.png)

@MashaKorax This problem still exists.

**Comment by MashaKorax** [comment]
@ChenpiDog, thanks for your response

**Comment by iraidaa** [comment]
What is your Greenplum version? Maybe it is somehow connected with the https://github.com/greenplum-db/gpdb/issues/11304

**Comment by ChenpiDog** [comment]
@iraidaa 6.3.0 It should not be a problem with GreenPlum, there is no such problem on another computer.

**Comment by ChenpiDog** [comment]
> @ChenpiDog could you please try this replace method? ON CONFLICT DO UPDATE SET ![dbeaver_jmJLLjYTec](https://user-images.githubusercontent.com/84867187/254846831-fc3350ae-d454-47ea-a874-2b108a21b0be.png)

ERROR: modification of distribution columns in OnConflictUpdate is not supported

**Comment by uslss** [comment]
@ChenpiDog could you provide table ddl to reproduce an issue?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide sample table DDL to reproduce the issue.
