### ISSUE TITLE
Resolve the issue of DBeaver's JDK being dependent on the local JDK

### ISSUE THREAD

**Issue by witt-bit** [dbeaver/dbeaver#20565]
## Problem Description
During the usage of DBeaver, I encountered an issue where the JDK version used by DBeaver conflicts with my local JDK version. I would like to resolve this issue and make DBeaver able to independently use the specified JDK without being affected by reinstallation.

## Proposed Solutions
While addressing this issue, I have considered the following three solutions, hoping that one of them can be implemented:

Provide an Environment Variable: DBEAVER_JAVA_HOME

Create an environment variable named DBEAVER_JAVA_HOME and set the loading order as DBEAVER_JAVA_HOME > JAVA_HOME.
This way, DBeaver will prioritize the JDK path specified in the DBEAVER_JAVA_HOME environment variable, avoiding the impact of reinstallation and enabling independence from the local JAVA_HOME.
Provide User-Based Extended Configuration: ~/.dbeaver/conf/dbeaver.ini

Create a file named ~/.dbeaver/conf/dbeaver.ini in the user's home directory for user-specific DBeaver configuration.
Allow users to configure the -vm parameter in this file to specify the desired JDK path, such as JAVA/bin.
This enables users to customize the JDK used by DBeaver in this configuration file, achieving independence from the local JDK.
Allow DBeaver.ini to Read System Environment Variables and Merge Configurations

Modify DBeaver to enable reading configurations from system environment variables and merging the contents of the new version's dbeaver.ini during reinstallation, rather than overwriting it completely.
This way, DBeaver retains user-customized configurations during updates, making it convenient for users to switch and update DBeaver versions.
I hope that the proposed solutions above can be considered and implemented, as they will help users better manage and utilize DBeaver, resolving the JDK version conflict issue.

Thank you very much for your attention and support! If you need further information or have any questions regarding the solutions, please feel free to reach out to me.

### DBeaver Version

dbeaver-23.1.0-1

### Operating System

Manjaro 23.0.0 UltimaThule

**Comment by flambchap** [comment]
Hi @leleplus. Can you please tell me how you install the application?

**Comment by witt-bit** [comment]
> Hi @leleplus. Can you please tell me how you install the application?

I installed via command line `yay -S dbeaver`

**Comment by flambchap** [comment]
@leleplus Can you please tell me what system Java you use and what kind of conflict you experience? From what I can see in [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/dbeaver/-/blob/main/PKGBUILD), the AUR package in question doesn't bring our Java with it.

**Comment by witt-bit** [comment]
> @leleplus Can you please tell me what system Java you use and what kind of conflict you experience? From what I can see in [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/dbeaver/-/blob/main/PKGBUILD), the AUR package in question doesn't bring our Java with it.

Maybe my previous expression was a bit vague, so I'll rephrase my difficulties.

I am using the `Manjaro Linux` operating system, and I can install and use DBeaver via `yay` or `pacman`, which behave the same way.

Firstly, there are multiple Java environments on my machine, such as `JDK8`, `JDK11`, `JDK17`, etc. However, I primarily use `JDK8`. Before starting DBeaver, I must run `sudo archlinux-java set java-17-openjdk`. After DBeaver starts successfully, I still need to run `sudo archlinux-java set java-8-openjdk`to restore the configuration.

Later, I learned that I can customize the JDK used by DBeaver by editing `dbeaver.ini` and adding the following lines:

```ini
-vm
/usr/lib/jvm/java-17-openjdk/bin
```
However, DBeaver receives frequent updates, and I also wish to experience new features. Whenever I update DBeaver using `yay` or `pacman`, the `dbeaver.ini` file reverts to its original state, and I have to configure the JDK again. This becomes a cumbersome task.

I hope there could be an additional configuration option to set the JDK permanently, unaffected by version upgrades.

**Comment by flambchap** [comment]
I believe this needs to be fixed on the side of the packaging. I suggest creating a request for the package maintainer to automatically add the`-vm` flag and an appropriate value on package installation/update.

**Comment by witt-bit** [comment]
I have released a [hook package : dbeaver-jvm-hook](https://aur.archlinux.org/packages/dbeaver-jvm-hook) to solve this problem. It will get the latest local version of the jvm after dbeaver is installed and updated, and set it to the dbeaver.ini file
