### ISSUE TITLE
unable to install 23.1.2 version  for window 

### ISSUE THREAD

**Issue by rahangdale1** [dbeaver/dbeaver#20560]
### Description

Hi team unable update new version of dbeaver on my system showing This site can’t be reached

### DBeaver Version

7.1.2

### Operating System

windows 11

### Database and driver

postgre v13.3

**Comment by E1izabeth** [comment]
Can you open https://dbeaver.io/download ?

**Comment by rahangdale1** [comment]
Hi team,
Yes I can open this link

**Comment by flambchap** [comment]
@rahangdale1 The option in the UI you're trying to use does not update DBeaver, it updates its plugins. Can you please download the appropriate package from [our website](https://dbeaver.io/download) and use it to update the application?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
