### ISSUE TITLE
Duplication of functions in the list

### ISSUE THREAD

**Issue by mopsik10** [dbeaver/dbeaver#20574]
### Description

I have 1 functions. Query return 1 line:
`SELECT * FROM pg_proc pp, pg_namespace n WHERE pp.pronamespace = n.oid AND pp.proname = 'group_calc' and n.nspname='my_sch'`

And I have many comments . Query return 45 line:
`SELECT pgd.description, pp.oid, pp.*
FROM pg_proc pp 
join pg_namespace n on pp.pronamespace = n.oid
left join pg_catalog.pg_description pgd on  pgd.objoid = pp.oid
WHERE pp.proname = 'group_calc' and n.nspname='my_sch'`

I see in Dbeaver:
![Screenshot 2023-07-14 134216](https://github.com/dbeaver/dbeaver/assets/69254183/4b624a71-b706-4508-b1c1-4e014314adb5)
This is one function, and it duplication 

### DBeaver Version

23.1.2.202307091549

### Database and driver

1.PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
2.PostgreSQL JDBC Driver 42.5.2

### Steps to reproduce

1. Create function.
2. Create many comments.

**Comment by mopsik10** [comment]
don,t ask me, please, how we could create so many comments for one feature. this is a migration to PG15

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by LonwoLonwo** [comment]
Hello @mopsik10 

Could you please explain this point:

`Create many comments.`

Which kind of comments? Comments for which object/objects?

**Comment by mopsik10** [comment]
Hello @LonwoLonwo . 
these are table column comments, and they were bound to the function during migration via oid -column. I can't say in more detail how it happened.
They are definitely not handmade.
here is a link by oid
`SELECT pgd.description, pp.oid, pp.* FROM pg_proc pp  join pg_namespace n on pp.pronamespace = n.oid left join pg_catalog.pg_description pgd on  pgd.objoid = pp.oid WHERE pp.proname = 'group_calc' and n.nspname='my_sch'`

**Comment by LonwoLonwo** [comment]
Could you please check this query:

```sql
SELECT p.oid as poid,p.*,pg_catalog.pg_get_expr(p.proargdefaults, 0) as arg_defaults,d.description
FROM pg_catalog.pg_proc p
LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=p.oid
WHERE p.pronamespace=<your_schema_oid> AND d.objsubid = 0
ORDER BY p.proname
```

With using your schema id.
Does it return correct procedures count?

**Comment by mopsik10** [comment]
Hello @LonwoLonwo .
This query return 27 line. YES, it is correct count. 1 line for 1 Procedure/Function.
And all of this Procedure/Function have Duplication in dbeaver now.
