### ISSUE TITLE
Driver JDBC

### ISSUE THREAD

**Issue by gilmarjovem** [dbeaver/dbeaver#20583]
### Description

I try to extract a file after typing the code and the following message appears?

SQL Error: JDBC driver internal error

![image](https://github.com/dbeaver/dbeaver/assets/139773250/28ec356b-9b96-450b-88bd-6d00ddba85e9)

### DBeaver Version

DBeaver 23.1.2

**Comment by LonwoLonwo** [comment]
Hello @gilmarjovem 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

Steps to reproduce and database + driver version also will be helpful.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
