### ISSUE TITLE
URGENT-Work Stoppage-DOD DHA-Licenses not working

### ISSUE THREAD

**Issue by SIRC-MARANDEZ** [dbeaver/dbeaver#20586]
### Description

Elena Vushinskaia of DBeaver Support confirmed last Friday 07/14/23 with DOD-DHA extending the individual licenses for another week but licenses are not working at this moment.   This is under award contract HT001523F0104. Please reinstate licenses ASAP. End user requested converting the purchased 50 licenses from group to individual licenses and Elena said she will extend the licenses for another week.

### DBeaver Version

0

**Comment by E1izabeth** [comment]
Please contact our sales department by email to sales@dbeaver.com. We don't resolve such issues on GitHub.
