### ISSUE TITLE
macOS text insertion caret location issue after select-all and keyboard arrow navigation

### ISSUE THREAD

**Issue by angusaustralia** [dbeaver/dbeaver#20596]
### Description

macOS text insertion carat location issue after select-all and keyboard arrow navigation

Select all text in a SQL editor (more that one line is required)

press the left arrow button on the keyboard.

The macOS text insertion carat should go to the top of the selected text and set the text insertion carat at text position  0 on the top line

pressing left arrow does not do this, rather the insertion marker moves to position 0 on the last line that had the text insertion carat.  This is not what every other macOS app behaves and is very discombobulating/annoying :-)

if instead I had pressed  the up arrow, then the text insertion moves to the correct location.

The text is unhighlighted correctly in both instance

### DBeaver Version

Community Version 23.1.2.202307091549

### Operating System

macOS Ventura 13.4.1 (c)

### Database and driver

PG 15
jdbc:postgresql

### Steps to reproduce

see above

### Additional context

DBeaver is wonderful! A fantastic product

**Comment by Matvey16** [comment]
@angusaustralia Hello. Can you please recor a video of this behavior. I wasn't able to reproduce it on MacOS 12. For me no matter what part of the text I highlight, pressing the left arrow key move the carret to the top-left part of the highlighted text. In case of selecing all text it moves to the start of the document.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
