### ISSUE TITLE
Keyboard shortcut for "Set row color for..." in results

### ISSUE THREAD

**Issue by Tix2garr** [dbeaver/dbeaver#20592]
First, I **love** dbeaver!  And just how hard all of you work to make it even better.  Thank you!!  :-)

**Is your feature request related to a problem? Please describe.**
Easily setting the row color for a value is VERY handy when looking at lots of code.  I tend to use this a lot.  But every time it is:
- right-click
- view/format
- Set row color for...

**Describe the solution you'd like**
Please add an option in the keyboard shortcuts to go straight to "Set row color for...".  This would automatically bring up the color selector, you select a color and done.

Even AWESOMER :-) would be having multiple keyboard shortcuts for setting the row color to different colors.  But I understand where that could/would get complicated quickly.  <wry smile>

"Solution" 2:
Adding an option in the keyboard shortcuts would work best for everyone, but **I** could get by with a letter "default" (the letter that is underlined in a menu that you can just hit to go to that menu item, sorry don't remember the "proper" name for them) for the "Set row color for..." entry with my Autohotkey script (see below).   

"the letter that is underlined in a menu..." - example, in the Window menu, it shows Editor with the "E" being underlined.

**Describe alternatives you've considered**
I use Autohotkey for lots of things and _tried_ to create a hotkey to effectively do the right-click, v (for view/format), then hitting "s" a couple of times to get down to "Set row color for..." since there are no letter "defaults" (or whatever they are called).  

HOWEVER, some columns show all three below that respond to "s", and others don't have the first one (Set ... transform), so it doesn't really work.  <wry smile>
- Set "<column name>" Transform
- Show complex column structures
- Set row color for...

And hitting "r" instead of "s" takes me right into "Customize colors for <query>", which is much more detailed, but also a lot more to do for just setting a specific color for a value in this result set.

**Additional context**
![image](https://github.com/dbeaver/dbeaver/assets/25388755/6c7c353c-de39-4e64-a08a-4865489720d8)

**Comment by E1izabeth** [comment]
Thank you for feature request.
