### ISSUE TITLE
The map type of clickhouse is displayed as=? 

### ISSUE THREAD

**Issue by guoxiangdaxia** [dbeaver/dbeaver#20591]
Windows version. The map type of clickhouse is displayed as=? 
![image](https://github.com/dbeaver/dbeaver/assets/19209779/7b9ceb2d-557c-4412-a5bf-4d1ae6ab1f2c)

**Comment by LonwoLonwo** [comment]
Hello @guoxiangdaxia 

What Clickhouse server and driver version do you use? You can check it in your connection settings with the "Test connection" button.

**Comment by guoxiangdaxia** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/19209779/c8500460-da95-4b72-a9af-97347b49a0e0) this is my version.

**Comment by LonwoLonwo** [comment]
Ok. And what is the expected result for you in this case from main topic?

**Comment by guoxiangdaxia** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/19209779/aaf817b5-8961-473f-a23b-54ec699a5f16)
Hello, the above image shows the display results of my mac bookpro, and the result I want is as shown in the above image. Display in  "key: value" format.

**Comment by E1izabeth** [comment]
Are your drivers on mac and windows the same?

**Comment by guoxiangdaxia** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/19209779/0ab84541-17d4-4cd7-8f9b-b0b242f807d7)
these are Mac's, they are different.
@E1izabeth

**Comment by ShadelessFox** [comment]
Something was changed on the driver side. Looks like we need to handle maps differently.

**Comment by E1izabeth** [comment]
See also #20388

**Comment by uslss** [comment]
fixed in #20797

**Comment by guoxiangdaxia** [comment]
thanks! @uslss @E1izabeth @ShadelessFox @LonwoLonwo
