### ISSUE TITLE
Missing connection name in Generate SQL shell name

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#20619]
### Description

Instead of {0} there was connection's name
![image](https://github.com/dbeaver/dbeaver/assets/43252954/c17d3841-5469-4fdb-8373-71b25421826f)

### DBeaver Version

23.1.2

### Operating System

win10

**Comment by serge-rider** [comment]
Fixed in 23.1.3 too

**Comment by DariaMarkaryan** [comment]
Verified
