### ISSUE TITLE
Duplicate tables in DB Navigator with PostgreSQL starting from 23.0.4

### ISSUE THREAD

**Issue by sisco70** [dbeaver/dbeaver#20618]
### Description

Starting with version 23.0.4, tables with primary key formed by two IDs "GENERATED BY DEFAULT AS IDENTITY" produces in DB Navigator a duplicate table

### DBeaver Version

Community Edition 23.1.2

### Operating System

Linux Ubuntu 22.04

### Database and driver

PostgreSQL 14.8 
PostgreSQL JDBC Driver 42.5.2

### Steps to reproduce

As of DBeaver 23.0.4, it is sufficient to create such a table:

**CREATE TABLE t1 (
	id1 int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, 
	id2 int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, 
	CONSTRAINT test_pk PRIMARY KEY (id1, id2)
);**

This generates 2 duplicate tables (apparently) in DB Navigator:
![image](https://github.com/dbeaver/dbeaver/assets/5530610/7cf199c6-492f-4e4e-b7de-ae30b6eae97e)

**Comment by LonwoLonwo** [comment]
Thanks for the report @sisco70
