### ISSUE TITLE
Issue with "Create" and "Delete" buttons visibility in authentication profile manager.

### ISSUE THREAD

**Issue by daelynum** [dbeaver/dbeaver#20620]
### Description

When I attempt to create a new profile or delete an existing one in the authentication profile manager, I cannot see the "Create" and "Delete" buttons initially. Only after minimizing and then maximizing the window do these buttons appear.

https://github.com/dbeaver/dbeaver/assets/38179706/0121c3dd-2fab-421a-8338-147e5e6efab3

### DBeaver Version

23.1.2.

### Operating System

macOS Ventura 13.2

### Steps to reproduce

1) Click on "New Database Connection".
1) Select "PostgreSQL".
1) Choose "DBeaver Profile" as the authentication method.
1) Click on "Manage profiles".

Expected: The "Create" and "Delete" buttons should be immediately visible in the profile manager.

Actual: The "Create" and "Delete" buttons are not visible until the window is minimized and then maximized.

**Comment by serge-rider** [comment]
Network and auth profiles dialog layout was fixed (toolbar moved to the bottom of table)
