### ISSUE TITLE
Colored table names when present on current schema (Editor Feature)

### ISSUE THREAD

**Issue by akaCarbone** [dbeaver/dbeaver#20628]
Hello,

Table names found in the schema should be color coded to ease its identification on long scripts.
This is a common feature found on other SQL tools, that would drastically (and positively) improve readability.

Thanks,

**Comment by E1izabeth** [comment]
Thank you for feature request.
I'm closing it as a duplicate of #4099. You can vote for that issue with 👍🏻

**Comment by E1izabeth** [comment]
It's done in https://github.com/dbeaver/dbeaver/pull/21788 and will be available in the next release (DBeaver 23.2.5)
The feature is turned off by default, you can enable it here 

![image](https://github.com/dbeaver/dbeaver/assets/28875055/dca4fef3-3bd6-484b-a11b-21cf916d1423)

**Comment by E1izabeth** [comment]
Done in scope of this issue #10831
