### ISSUE TITLE
Dictionary for tables cannot be cleared

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#20632]
### Description

Dictionary for tables cannot be cleared. Affects value panel and labels for spatial data.

https://github.com/dbeaver/dbeaver/assets/31996417/77301f3a-d512-434e-a853-74d54bd57d7b

### DBeaver Version

CE 23.1.3

### Operating System

win10

### Steps to reproduce

1. Open Spatial data view
2. Enable labels
3. Set some columns for labels and save it
4. Open Label configuration - choose Clear all - OK button is disabled

**Comment by ShadelessFox** [comment]
You're not supposed to leave dictionary columns empty. At least one must be selected.

The "clear all" button is just a convenient way to clear the selection in case you have lots of columns selected for some reason
