### ISSUE TITLE
[Floating] Copy viewport/selection bounds is not always working

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#20633]
### Description

From time to time  Copy viewport/selection bounds don't work in tables/value panels. Also, lasso element isn't shown at this moment.

`2023-07-21 11:39:33.979 - Internal error: actions double-lock by [Browser {} [layout=null]]`
At this time, the error above is in debug log.

https://github.com/dbeaver/dbeaver/assets/31996417/b47c57c8-5d38-41bf-8597-3a5d5f984295

### DBeaver Version

23.1.3

### Operating System

win10

### Database and driver

postgreSQL

**Comment by ShadelessFox** [comment]
The lasso tool is shown only in the value panel as it changes selection in the grid. It makes no sense in the spatial view.

**Comment by uslss** [comment]
not reproducible anymore
