### ISSUE TITLE
Wnen importing csv table mapping step not predefined after previous steps

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#20634]
### Description

STR

1. choose some table and from context menu select import data
2. In data transfer dialog choose CSV
3. Choose csv file from your laptop and press next btn
Actual result - on table mapping page target conteiner and source are not predifined after previous steps, also source column cut down
11

https://github.com/dbeaver/dbeaver/assets/84867187/2ecd6ea4-f7d0-4f8e-9b7e-8da43279f03e

### DBeaver Version

23.1.3

### Operating System

mac M1 monterey 12

**Comment by DariaMarkaryan** [comment]
Also reproduced on windows for table importing https://github.com/dbeaver/dbeaver/issues/20643
