### ISSUE TITLE
Docker networks break when DBeaver is running

### ISSUE THREAD

**Issue by AlexDsv** [dbeaver/dbeaver#20645]
### Description

When all the services have been started with docker compose, running DBeaver won't cause any problem.
If we want to update the services after a build or a down of the services with a simple docker compose up and DBeaver is running, the services cannot access the docker DNS server (to resolve other services IPs from their names).

It looks like it is something from a recent update of DBeaver because the problem didn't appear before.

### DBeaver Version

23.1.2.202307091549

### Operating System

Windows 10 22H2 Build 19045.3208

### Steps to reproduce

1. Launch DBeaver
2. Launch Docker Compose project (with one service accessing an other one)
3. Observe the service accessing the other one failing to reach the Docker DNS server with error message: `querying server version dial tcp: lookup database on 127.0.0.11:53: server misbehaving`

**Comment by E1izabeth** [comment]
Could you specify the version you didn't experience the described behaviour with?

**Comment by AlexDsv** [comment]
I was using DBeaver 22.3.5 before updating to the latest version and I never experienced this behaviour.

**Comment by E1izabeth** [comment]
Are you connecting to some database when you launching DBeaver?

**Comment by E1izabeth** [comment]
Could you verify that there is no open connections and try to reproduce it this way?

**Comment by AlexDsv** [comment]
I disabled "Connect on editor activation" and "Reopen database editors after restart" and it fixed the issue.

Thanks for the help !
