### ISSUE TITLE
Project Password

### ISSUE THREAD

**Issue by cemccccc** [dbeaver/dbeaver#20651]
### Description

When I started dbeaver it kept asking for password. I couldn't turn it off. Now it asks for the same password twice. How can I turn this off?

### DBeaver Version

Version 23.1.0.202306120813

### Operating System

Windows 10

**Comment by cemccccc** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/83164656/6af8755c-13e7-486e-99cc-1f8b07844423)

**Comment by LonwoLonwo** [comment]
Hello @cemccccc 

Could you please try to use the latest DBeaver version? We fixed a similar issue some time ago.
https://dbeaver.io/download/

**Comment by LonwoLonwo** [comment]
Ups, sorry, the latest in your case is the Early Acces version: https://dbeaver.com/files/ea/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
