### ISSUE TITLE
Find dialog broken in 23.1.3

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#20669]
### Description

I just upgraded to 23.1.3.202307231901 and now the Find dialog, accessed via control-F, is no longer reliable.

![dbeaver_missing_find_20230724_142458](https://github.com/dbeaver/dbeaver/assets/3697063/f1f9773b-23b7-40ae-a88e-f3a2f24d4443)

it isn't anywhere in the Edit menu, Ctrl+F will only open it _sometimes_ and sometimes when it does open, it's followed by a java loop error and a warning to close the workspace.

Can someone fix the find?

thanks

### DBeaver Version

Community 23.1.3

### Operating System

Windows 10

### Steps to reproduce

Open Query Editor window
press Ctrl-F
*nothing* happens.

**Comment by E1izabeth** [comment]
I can't reproduce it. Could you provide a video showing your issue? Your exact clicks and opened windows may be important here.

**Comment by coleman-rik** [comment]
@E1izabeth Here is a video where I can consistently duplicate the behavior.

1. Start dBeaver, open a new SQL Editor window, note that there is **no** menu item for Find Replace Ctrl+F
2. try to get the Find Replace dialog by pressing Ctrl+F
3. inset a single character in to the script window
4. there is **now** a menu item for Find Replace
5. Ctrl+F now calls up the Find Replace dialog

This behavior also occurs _randomly_ with a SQL Editor window filled with text.
Occasionally if there is a block of text selected when I press Ctrl+F, dBeaver throws a Java loop error dialog and suggests closing the workspace.

I hope this helps,  

[dbeaver_find_replace_dialog.webm](https://github.com/dbeaver/dbeaver/assets/3697063/776950f5-6ddb-4587-ab34-9c5e7ff53043)

**Comment by E1izabeth** [comment]
Thank you for details and video.
As far as I see, hen you click on other DBeaver parts, focus go outside SQL editor, so your shortcut and menu options applies to that parts. Just put the focus inside SQL editor and it should work. The focus is very important.

**Comment by coleman-rik** [comment]
That isn't the case.

If you pay attention to the details, 
when there is a SQL Editor window open, even if it doesn't have any focus, as long as it's blank the **menu item** for Find Replace doesn't even exist.
if there's so much as a single character in the SQL Editor window, regardless of focus, the **menu item** for Find replace magically appears.

Also, the focus was in the SQL Editor when I was fruitlessly pressing the Ctrl-F key.  Adding a single character is enough to get the dialog to appear.

Try it yourself and confirm.

bonus exercise:
after adding that character(s) into the SQL Editor window and confirming that the **Find Replace** menu item is present, _delete_ all of the text, like magic, the **Find Replace** menu item will disappear. 

Find Next, Find Previous, etc. are **always** present.

**Comment by coleman-rik** [comment]
While working in dbeaver, I had a block of PL/pgSQL selected and pressed ctrl-F.  As it sometimes does in the latest version it presented me with a Java loop error and a request to close dbeaver.  

Attached are a series of screen shots and the Stack trace.

![dbeaver_loop_error_on_ctrl-F_20230803_1129](https://github.com/dbeaver/dbeaver/assets/3697063/ac689606-004e-4bdd-b39d-5e9e1f55b76c)

![dbeaver_loop_error_on_ctrl-F_internal_error_20230803_113019](https://github.com/dbeaver/dbeaver/assets/3697063/a369686e-4415-422e-a0cd-426d33d47330)

![dbeaver_loop_error_on_ctrl-F_event_details_20230803_113137](https://github.com/dbeaver/dbeaver/assets/3697063/b4f7305a-c0db-4a6a-879e-afba908d4b8a)

[dbeaver_loop_error_on_ctrl-F_event_details_20230803_113137.log](https://github.com/dbeaver/dbeaver/files/12252538/dbeaver_loop_error_on_ctrl-F_event_details_20230803_113137.log)

**Comment by coleman-rik** [comment]
After closing and restarting dbeaver, it looks like the Find functionality is **completely** broken.  Even with text in the SQL editor, the Find dialog & menu item is completely broken/missing.

see attached video:

[dbeaver_find_replace_dialog_completely_gone_after_reboot.webm](https://github.com/dbeaver/dbeaver/assets/3697063/a76c4f36-f9f4-48b5-a184-74b340053c5b)

rebooting the computer didn't restore functionality.

switching to another open SQL editor tab, pressing Ctrl-F opened the Find dialog.
only **after** doing that, and returning to the original SQL Editor tab did the Find dialog resume working.

**Comment by Matvey16** [comment]
I reproduced it, but it seems as nothing special to me. Do you think there is a case where a user would want to have find/replace feature in a completely blank script? Because this looks like intended behavior that occurs in scripts where there a no characters at all, even entering a newline enables the find/replace option.

**Comment by coleman-rik** [comment]
@Matvey16, 

there are two separate issues.
1. missing Find menu items, inability to call find dialog
2. find dialog crashing on activation.

for #1,
yes, there is. I have on occasion called up the find /replace dialog on blank SQL Views in preparation for pasting a whole bunch of code.  Also, it's terribly inconsistent.  The **entire** rest of the Find section of the Edit menu is static.  items _other than_ Find Replace are either active or disabled depending on the situation.  Find Replace alone plays peek a boo with the user.

I think you are asking the wrong question, is there **ever**  a programmatic reason to disable the Find Replace dialog (going so far as to **remove** the menu item from the application interface) depending on the number of characters in the window?  I can't think of a single application that allows text editing that makes the Find UI dependent on the number of characters present.  Not VSCode, nor Kate, nor  pgAdmin4, not even JetBrains' DataGrip.  In every case, including previous versions of dbeaver,  the Find UI is independent of the number of characters.

for #2,
you seem to have ignored that case entirely.  it's not easily reproducible, but I did include screen shots and a stack trace the last time it occurred.  I don't think users should have to _roll the dice_ whenever they select a block of code and press Ctrl-F to see if **that** time is the time the application will crash.


I hope your team and fix these issues and return normalcy and stability to this application.

**Comment by coleman-rik** [comment]
any progress on this issue?

it's been 2 weeks since it was re-assigned to @Matvey16 who originally didn't want to do anything about it.

is someone going to fix this?

thanks.

**Comment by ShadelessFox** [comment]
Hello @coleman-rik,

No need to be that rude.

We don't want to fix it since it's expected behavior both in DBeaver and Eclipse.

**Comment by coleman-rik** [comment]
@ShadelessFox 

> No need to be that rude.

I wasn't, just stating facts.

It's a shame that you've decided to have dBeaver play where's **Find Replace Ctrl+F** instead of fixing it.

**Comment by ShadelessFox** [comment]
The first issue sometimes occurs in the depth of the Eclipse platform. We can't fix it.

Regarding the second issue mentioned, I can't reproduce it. The only thing is that the "Find/Replace" is unavailable when the active editor is empty.

Can you please download the latest version to see if the issue is gone there?
