### ISSUE TITLE
Cancelling Generating SQL -> DDL on all tables on Oracle DB schema, does not stop the background process

### ISSUE THREAD

**Issue by neilsteyn** [dbeaver/dbeaver#20672]
### Description

When selecting all tables in the schema to generate DDL, after cancelling the operation, it still runs in the background

![image](https://github.com/dbeaver/dbeaver/assets/20437001/66083c4d-91a0-4773-a570-5ce1d8032deb)
![image](https://github.com/dbeaver/dbeaver/assets/20437001/9e5dc768-3f3e-4037-8aa5-78959d6cd3bc)

### DBeaver Version

Community Edition 23.1.2

### Operating System

Windows 11 Pro

### Database and driver

Database: Oracle Database 19c Standard Edition 2

![image](https://github.com/dbeaver/dbeaver/assets/20437001/6fe13d46-1a73-46b5-ad64-1448fbf60df4)
![image](https://github.com/dbeaver/dbeaver/assets/20437001/e3a3f74a-dd39-46bc-af0c-4cd5e36f1ebf)

### Steps to reproduce

Select all tables then do the following:

![image](https://github.com/dbeaver/dbeaver/assets/20437001/3b3ae9d6-7839-43e9-a9ee-d251884ec881)

**Comment by iraidaa** [comment]
Thanks for the report.

**Comment by serge-rider** [comment]
Query cancel support depends on Oracle server OS and version (https://support.oracle.com/knowledge/Middleware/850511_1.html). Maybe it is not supported by yours.

Anyway, table DDL generation consists of multiple DBMS_METADATA.GET_DEPENDENT_DDL calls, each of which may take time.
I've added DDL generation interrupt for these extra calls.
