### ISSUE TITLE
第三方组件重新安装后不要清空

### ISSUE THREAD

**Issue by zhangdingrui** [dbeaver/dbeaver#20674]
![image](https://github.com/dbeaver/dbeaver/assets/76196230/08e1390a-11e2-443d-9c9a-db1c880ab10b)
例：安装导出excel插件
DBeaver Office integration - https://dbeaver.io/update/office/latest/
每次升级版本，都需要重新安装

**Comment by E1izabeth** [comment]
Thank you for bug report. This issue is a duplicate of #5317, so I'm closing it.
