### ISSUE TITLE
Weird behavior of encoding

### ISSUE THREAD

**Issue by philip-C96** [dbeaver/dbeaver#20698]
### Description

Currently, I am working on a project that requires a feature; just simply inserts a row record from frontend to the backend.
Like submitting a form from FN(React) to BN(Django) and to the DB(MySQL). There will be some Chinese characters and emoji involved in the form data. Thats it. the problem is when submitting the form from FN to BN, the data shown in DBeaver will become gibberish. And the weirder thing is when I try to insert data by DBeaver, FN shows "???" (question marks).
I'm quite sure that's not the problem of request or Django (both are using the default encoding, and the DB connection explicitly declared the charset to 'utf8mb4')
![image](https://github.com/dbeaver/dbeaver/assets/75031477/e00bc40b-6659-4665-978f-45debcb7d61e)
Well, to be honest, I am not so sure whether the problem is DBeaver or not =[ , because the same issue occurs in MySQLWorkBench.

### DBeaver Version

Community 23.1.3

### Operating System

macOS Ventura 13.4.1

### Database and driver

MySQL 5.7.38-log

**Comment by E1izabeth** [comment]
Similar issues #9890 and #19631

**Comment by ShadelessFox** [comment]
Hello @C0837213,

This issue indeed doesn't seem to have anything to do with DBeaver.

I would suggest ensuring that the encoding on the front-end and the back-end is the same (utf8mb4 is not the same as utf8).

**Comment by E1izabeth** [comment]
We expect that it may be solved it with #21513
However, if the issue is still reproducible, please let me know.
