### ISSUE TITLE
Can't create driver instance, Error during driver instantiation, Missing driver

### ISSUE THREAD

**Issue by LightDye** [dbeaver/dbeaver#20712]
### Description

DBeaver forgets user defined drivers between restarts.

Using the Driver Manager I created a custom definition for a JDBC driver that is not available online. The driver is in my local hard drive.

I defined a DB connection using this driver and was able to connect to the database, no problem at all. The next day after restarting my PC and opening DBeaver again, I got this error message when tried to connect to the database:

![image](https://github.com/dbeaver/dbeaver/assets/5836447/63051a4d-e499-45f4-b524-10db12457acc)

Opened the Driver Manager and noticed that the driver I defined before was renamed to a UUID name and shows a "Missing driver" message under the driver selection panel.

![image](https://github.com/dbeaver/dbeaver/assets/5836447/42746b75-d89f-4b48-923a-0437ba4cb713)

Used the Edit button and found that its Libraries list was empty. Added the jar file of the JDBC driver and selected the Driver class, then clicked OK.  After doing this I was able to connect to the database again. However, after restarting DBeaver again the exact same problem occurred.

I have tried these versions of DBeaver and had the same issue with all of them:

* ce-21.1.5-win32.win32.x86_64
* ce-22.1.4-x86_64-setup
* ce-23.1.3-x86_64-setup

### DBeaver Version

Community Edition 22.1.4

UPDATE: it hasn't happened with the latest version 23.1.3, but it happened when upgraded from the previous version to the latest.

### Operating System

Windows 10

### Steps to reproduce

1. Create a User Defined driver
2. Create a DB connection that uses it
3. Confirm that DB sessions can be opened with it
4. Restart DBeaver and try to connect to the database again. The connection may fail with "Can't create driver instance" and the driver appears as "missing" despite the jar file being available.
5. Review the driver definition, set the jar library again and save the changes
6. Attempt to connect to the DB. It should work.
7. Go back to step 4. The issue reappears after every restart.

**Comment by MashaKorax** [comment]
@LightDye Have you modified the file drivers.xml on directory C:\Users\user\AppData\Roaming\DBeaverData\workspace6\.metadata\.config  ? And is it reproduced in version 23.1.4?

**Comment by LightDye** [comment]
Hi @MashaKorax, thanks for your reply. I haven't edited any config files manually. I noticed that this started to happen few versions back every time that I upgraded from one version to the next. In a recent version it didn't keep the configuration between restarts. I have now updated to the latest version 23.1.4 but the issue didn't occur. The drivers appear correctly in the Driver Manager and I had no issue opening database sessions. I think that the issue is probably gone now. I can't reproduce it anymore.

**Comment by MashaKorax** [comment]
Thanks for your response! Please, let me know if it will happen again in the future.

**Comment by dhorrall** [comment]
I have this same problem.  I have a connection to Netsuite database.  I can point to the driver file in the connection and everything works.  But when I exit out of DBEAVER and re-open DBEAVER, I have to reload the driver information again.  It doesn't seem to be saving the driver information in drivers.xml file

**Comment by graemechapman** [comment]
@MashaKorax I've recently started experiencing this exact same issue, I wonder if the previous fix implemented for this has regressed? I'm on macOS, version 25.3.0.202511301802 but it's been occurring for at least a few versions back.
