### ISSUE TITLE
EXPLAIN throws error in Yellowbrick

### ISSUE THREAD

**Issue by jeff-bowles** [dbeaver/dbeaver#20724]
### Description

Getting an error message trying to use EXPLAIN feature

Message is "SQL Error [XX000]: ERROR: FORMAT XML is not supported"

### DBeaver Version

Community Edition 23.1.3

### Operating System

Windows 10 64 bit 22H2 build 19045

### Database and driver

Yellowbrick 5.2
PostgreSQL JDBC Driver (not sure which version - latest available?)

### Steps to reproduce

1. Highlight a SQL query
2. Click the icon or press the keys CTRL-SHIFT-E
3. Accept the default "COSTS" in the next dialog (Yellowbrick Explain Plan Configuration)
4. Error appears

### Additional context

stack trace
![image](https://github.com/dbeaver/dbeaver/assets/32487935/71cca6c2-6023-45a4-ab02-125d3f4cfb7f)

**Comment by LonwoLonwo** [comment]
Hello @jeff-bowles 

Thanks for the report.

https://docs.yellowbrick.com/5.2/ybd_sqlref/explain.html
