### ISSUE TITLE
Database connections don't show up in UI

### ISSUE THREAD

**Issue by mdgbd** [dbeaver/dbeaver#20720]
### Description

When I try to create a new database connection, and press finish, the next screen is empty and there is no trace of my connection anywhere, see video below

### DBeaver Version

23.1

### Operating System

macOS Ventura 13.4.1

### Database and driver

Postgres / JDCB

### Steps to reproduce

https://github.com/dbeaver/dbeaver/assets/139139502/f8e454dc-00b0-4dc2-aa63-06436b06860b

**Comment by ShadelessFox** [comment]
Hello @mdgbd,

It looks like the navigator tree is closed for some reason.

Use `Window -> Database Navigator` to reveal the navigator tree or `Window -> Reset Perspective` to reset the perspective.

Please let me know if it helps.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
