### ISSUE TITLE
Cannot (easily) drop stored procedure in Yellowbrick

### ISSUE THREAD

**Issue by jeff-bowles** [dbeaver/dbeaver#20725]
### Description

When using the GUI, attempting to right-click a stored procedure and choose "delete" will not work.
The script that is generated behind the scenes is not syntactically correct for yellowbrick.  The generated script uses "DROP FUNCTION..." but Yellowbrick expects "DROP PROCEDURE"

If I proceed with the incorrect script, I get the following error:
**SQL Error [42809]: ERROR: "blah.blah" is a stored procedure
  Hint: Use DROP PROCEDURE to drop stored procedures.**

### DBeaver Version

Community Edition 23.1.3

### Operating System

Windows 10 64 bit 22H2 build 19045

### Database and driver

Yellowbrick 5.2
Latest Postgres JDBC driver

### Steps to reproduce

1. right click any stored procedure in a YB database
2. choose "delete" from the context menu
3. In the "Delete Object" dialog, click the "View Script" button
4. Observe the incorrect syntax

### Additional context
Of course the workaround is to just write and execute a "DROP PROCEDURE" statement myself.

error log

![image](https://github.com/dbeaver/dbeaver/assets/32487935/55ad142d-2b54-4584-aebd-5c22e7e801d4)

**Comment by LonwoLonwo** [comment]
Hello @jeff-bowles 

Could you please provide a procedure DDL example?

**Comment by jeff-bowles** [comment]
If I understand correctly, you want a DDL script to create a stored procedure, so you can try to delete it.

Here is one that doesn't do anything except write to the output console.

```
CREATE OR REPLACE procedure Do_Nothing()  
  RETURNS void
  LANGUAGE plpgsql
AS $function$

begin
  raise info E'doing nothing';
  raise info E'finished nothing';
end
$function$;

```

**Comment by LonwoLonwo** [comment]
Can you also please provide footage showing your issue? Thank you.

**Comment by LonwoLonwo** [comment]
Ok, I see, the "prokind" column is absent in the pg_proc system table. And user-defined functions are [not supported](https://docs.yellowbrick.com/4.1/ybd_sqlref/sql_functions_intro.html) in Yellobrick.
But, probably, I can use "prosp" column instead.

**Comment by jeff-bowles** [comment]
For what it's worth, the "prosp" column appears to contain NULL for system-defined procs, and TRUE for user-defined procs.

**Comment by jeff-bowles** [comment]
At least in the DB I am using.
