### ISSUE TITLE
Improve data transfer ui

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#20730]
We want instead of **?** write something like "target table will be selected on the next page", but more concise

Now this wizard page is lil bit confusing because it looks like I should pick some target. 

STR:

1. Click any schema
2. In context menu  - import data

![dbeaver_AkdgsuYs1n](https://github.com/dbeaver/dbeaver/assets/84867187/c5adb250-ce64-47ac-8878-66e9b99061ff)

**Comment by E1izabeth** [comment]
We want to hide Target column on this page if it's not applicable.
