### ISSUE TITLE
Rename database

### ISSUE THREAD

**Issue by andreysneg** [dbeaver/dbeaver#20738]
Please create simple "Rename database"  function like others DB programs ( heidisql ).

Now 100 times easier and faster to launch heidisql for this.

**Comment by ShadelessFox** [comment]
Hello @andreysneg,

What do you mean by "rename database"? What database are you using?

**Comment by andreysneg** [comment]
Mysql/mariadb database.

Errror:
Direct database rename is not yet implemented in MySQL. You should use export/import functions for that.

But all others db programms can do what like simple rename.

**Comment by ShadelessFox** [comment]
The `RENAME DATABASE` was removed in older versions of MySQL for security reasons.

You can either use a dump/restore combination or move tables manually:
1. Create a new database
2. Rename tables like so: `RENAME TABLE old_db.table TO new_db.table`
3. Drop the old database

I'm unaware, but there might be some caveats.

If you want this feature implemented in DBeaver, please "👍🏻" this issue.

**Comment by andreysneg** [comment]
Where is -  "👍🏻" ?  
i dont see

**Comment by ShadelessFox** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/35821147/e5135f02-48a3-440d-9210-73a9b3404314)

**Comment by Nura21** [comment]
I guess, if it can rename, that would be good and easier

**Comment by LonwoLonwo** [comment]
Closed as a duplicate of #2287
