### ISSUE TITLE
Setting for opening the console by @include command

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#20733]
### Description

in previous versions this command executed the included script, but now the behavior has changed
1. create file with script
2. write @include script-path
3. execute this
Expected: the included script executed 
Actual: included script not executed, just opened in SQL console

### DBeaver Version

23.1.3

### Operating System

win10

**Comment by E1izabeth** [comment]
Can't reproduce the issue. However, we could ad a setting to set up whether we should close opened console with included script content.
