### ISSUE TITLE
XML Import from File to Exisintg Table - No options to mapp and import fails 

### ISSUE THREAD

**Issue by jonosooty** [dbeaver/dbeaver#20748]
### Description

Hi, I am evaluating dbeaver Pro/Ulitmate. I have one use case which is to import XML files to a postgres database. Perhaps I am doing something wrong but I can't get this to work. There are never and fields mapped from the XML and then the columns are imported as NULL. 

The same seems true of XLS and CSV - so maybe I am just being dumb. 

Regards, 
Jono

### DBeaver Version

ULTIMATE  23.1.0.202306120813

### Operating System

Windows 10 Enterprise

### Database and driver

1. PostgreSQL 15

### Steps to reproduce

1. Create Table in Schema 
2. Select the Table in DBEAVER and right Click Import 
3. Import - select XML file (large) 
4. Follow wizard - but no chance to map fields 
5. Import  - errors because nulls attempted to be imported into columns.

**Comment by jonosooty** [comment]
> ### Description
> 
> Hi, I am evaluating dbeaver Pro/Ulitmate. I have one use case which is to import XML files to a postgres database. Perhaps I am doing something wrong but I can't get this to work. There are never and fields mapped from the XML and then the columns are imported as NULL.
> 
> The XML is imported using dbFOrge STudio into postgres OK. 



> Regards, Jono
> ### DBeaver Version
> 
> ULTIMATE 23.1.0.202306120813
> ### Operating System
> 
> Windows 10 Enterprise
> ### Database and driver
> 
>     1. PostgreSQL 15
> 
> 
> ### Steps to reproduce
> 
>     1. Create Table in Schema
> 
>     2. Select the Table in DBEAVER and right Click Import
> 
>     3. Import - select XML file (large)
> 
>     4. Follow wizard - but no chance to map fields
> 
>     5. Import  - errors because nulls attempted to be imported into columns.
> 
> 
> ### Additional context
> 
> _No response_

![image](https://github.com/dbeaver/dbeaver/assets/132822066/efa505c4-fed7-438c-a7c6-53f6eb5965f0)

**Comment by jonosooty** [comment]
XSD: 
<xs:schema attributeFormDefault="unqualified" 
		   elementFormDefault="qualified" 
		   xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ifapRohdaten">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Artikel" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
							
								<xs:attribute type="xs:integer" name="PZN" use="required"/>
															
								<xs:attribute name="Name" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value = "50"/>
										</xs:restriction>									
									</xs:simpleType>
								</xs:attribute>	
								
								<xs:attribute type="xs:integer" name="ProduktID" use="required"/>								
								<xs:attribute type="xs:integer" name="AnbieterID" use="required"/>
								
								<xs:attribute name="Menge" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value = "7"/>
										</xs:restriction>									
									</xs:simpleType>
								</xs:attribute>									
								
								<xs:attribute name="Mengeneinheit" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value = "10"/>
										</xs:restriction>									
									</xs:simpleType>
								</xs:attribute>	
								
								<xs:attribute name="Normpackung" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value = "15"/>
										</xs:restriction>									
									</xs:simpleType>
								</xs:attribute>	
								
								<xs:attribute name="Verkehrsfaehig" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value = "150"/>
										</xs:restriction>									
									</xs:simpleType>
								</xs:attribute>	
								
								<xs:attribute name="Vertriebsfaehig" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value = "150"/>
										</xs:restriction>									
									</xs:simpleType>
								</xs:attribute>	
								
								<xs:attribute type="xs:float" name="AVP" use="required"/>
								<xs:attribute type="xs:float" name="UVP" use="required"/>
								<xs:attribute type="xs:float" name="Zuzahlung" use="required"/>
								<xs:attribute type="xs:float" name="Festbetrag" use="required"/>

								<xs:attribute name="Festbetragsstufe" use="required">
									<xs:simpleType>
										<xs:union>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="0"/>
												</xs:restriction>
											</xs:simpleType>
											<xs:simpleType>
												<xs:restriction base="xs:integer">
												</xs:restriction>
											</xs:simpleType>
										</xs:union>
									</xs:simpleType>
								</xs:attribute>					

								<xs:attribute name="Darreichungsform" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value = "3"/>
										</xs:restriction>									
									</xs:simpleType>
								</xs:attribute>
								
								<xs:attribute name="OTX" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value = "4"/>
										</xs:restriction>									
									</xs:simpleType>
								</xs:attribute>
								
								<xs:attribute name="OTC" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value = "4"/>
										</xs:restriction>									
									</xs:simpleType>
								</xs:attribute>
								
								<xs:attribute name="Verbandmittel" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value = "4"/>
										</xs:restriction>									
									</xs:simpleType>
								</xs:attribute>
								
								<xs:attribute name="Teststreifen" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value = "4"/>
										</xs:restriction>									
									</xs:simpleType>
								</xs:attribute>
								
								<xs:attribute name="Kombipraeparat" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value = "4"/>
										</xs:restriction>									
									</xs:simpleType>
								</xs:attribute>
								
								<xs:attribute type="xs:integer" name="PVGL_Gruppe" use="required"/>
								
								<xs:attribute name="HPN" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value = "13"/>
										</xs:restriction>									
									</xs:simpleType>
								</xs:attribute>
								
								<xs:attribute name="Reimport" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value = "4"/>
										</xs:restriction>									
									</xs:simpleType>
								</xs:attribute>
								
								<xs:attribute name="GueltigkeitAVP" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value = "10"/>
										</xs:restriction>									
									</xs:simpleType>
								</xs:attribute>
								
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

**Comment by LonwoLonwo** [comment]
Hello @jonosooty 

Your picture shows that a special triangle for attributes viewing is absent.

![2023-08-01 08_36_14-Data Transfer](https://github.com/dbeaver/dbeaver/assets/45152336/cee32bc7-a9b4-4281-affc-c2f3592123cf)

(This one)

It means that something goes wrong.

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide log files.
