### ISSUE TITLE
Dbeaver connects to mysql to check the partition, which interface is called?

### ISSUE THREAD

**Issue by liujiwen-up** [dbeaver/dbeaver#20744]
### Description

If I want to add a data source, the bottom layer uses the mysql driver, and I want to change the logic of obtaining the partition information of the table, how will I modify it?
![image](https://github.com/dbeaver/dbeaver/assets/61498169/5a97dc96-02ac-4910-98e8-8859ab94c5b8)

### DBeaver Version

23.1.3

### Operating System

macos

**Comment by LonwoLonwo** [comment]
Hello @liujiwen-up 

> I want to change the logic of obtaining the partition information of the table

How exactly do you want to change this info?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
