### ISSUE TITLE
[Feature Request] Pop-up window and new design for creating, editing items (tables, sequences, packages and etc. )

### ISSUE THREAD

**Issue by ceyhunn** [dbeaver/dbeaver#2074]
I think, creating or editing SQL items  is not user-friendly, especially in small resolution (laptops).  To do this actions in separate window (pop-up window) and make new design (+, x ,edit  icons for  SQL table column, constraint operations, save-cancel dialog buttons at the  bottom of the window  and etc.) would be nice...

**Comment by serge-rider** [comment]
Partially it is already implemented (e.g. popup dialog for column creation). We'll keep adding popup dialogs for metadata objects creation.

**Comment by ceyhunnabiyev** [comment]
Thanks, @serge-rider 
Best database tool I ever seen, especially for Linux...
