### ISSUE TITLE
Dameng database support

### ISSUE THREAD

**Issue by zero-wsh** [dbeaver/dbeaver#20740]
### Description

Official website of China Da Meng Database http://www.dameng.com/

Tables and table fields cannot be modified

1: Table fields cannot be modified

2: Table and column annotations cannot be modified
<img width="924" alt="image" src="https://github.com/dbeaver/dbeaver/assets/44697042/d6f60a3a-cb82-4cb3-a769-136e65f25455">

### DBeaver Version

23.1.0.202306120813

### Operating System

windows11

**Comment by LonwoLonwo** [comment]
Hello @zero-wsh 

How are you connecting to your database? DBeaver doesn't have official support for this database.

**Comment by zero-wsh** [comment]
Referenced this blog：https://blog.csdn.net/u012063422/article/details/123759444
Connect using a driver

**Comment by zero-wsh** [comment]
> Hello @zero-wsh
> 
> How are you connecting to your database? DBeaver doesn't have official support for this database.

Referenced this blog：https://blog.csdn.net/u012063422/article/details/123759444
Connect using a driver

**Comment by LonwoLonwo** [comment]
Ok, you are using a custom ODBC driver and connection.

DBeaver doesn't have the support of this database, so I marked this ticket as a feature request.

**Comment by E1izabeth** [comment]
Duplicate of #10133
