### ISSUE TITLE
sybase unable to execute the custom stored procedure

### ISSUE THREAD

**Issue by dottle** [dbeaver/dbeaver#20755]
### Description

We have a custom stored procedure that includes a conditional SELECT statement, for example:

begin
   select @SQLString = 'select * from table'
end
execute(@SQLString)

However, when executing this procedure in DBeaver, it returns the SQL error [207] [ZZZZZ]: Invalid column name.

### DBeaver Version

Community Edition 23.1.2

### Operating System

Windoww 7 Pro

### Database and driver

1.Sybase Adaotive Server Enterprise 16.0.04.02
2.com.sybase.jdbc4.jdbc.SybDriver

**Comment by LonwoLonwo** [comment]
Hello @dottle 

What about the declaration part for your variable? I think this example is not complete enough.

**Comment by dottle** [comment]
@LonwoLonwo 
 example would look something like this 

```sql
CREATE PROCEDURE custom_stored_procedure
AS
BEGIN
    DECLARE @SQLString VARCHAR(500)

    BEGIN
        SELECT @SQLString = 'select * from tableA' 
    END

    EXECUTE(@SQLString)
END
```

**Comment by LonwoLonwo** [comment]
![2023-08-02 09_30_53-DBeaver Ultimate 23 1 3 - _demo_ Script-37](https://github.com/dbeaver/dbeaver/assets/45152336/5862b641-b880-40ad-a5d4-12f68fe9816d)

And it works for me with the declaration.

Did you try to highlight the whole query and then execute it?

**Comment by dottle** [comment]
Apologies, I have noticed that the actual situation differs slightly. The table being selected is not from the connected database, but from another database, and it is achieved using a view.

```sql
create view view_label 
as select testdb.dbo.label.column1, 
	testdb.dbo.label.column2, 
	testdb.dbo.label.column3, 
	testdb.dbo.label.column4,
	testdb.dbo.label.column5
	from testdb.dbo.label;

create procedure custom_stored_procedure     
as       
begin   
		declare @SQLString varchar(500)

		begin 
			select @SQLString = 'select * from view_label' 
		end 
		
   execute(@SQLString)        
end
```

**Comment by LonwoLonwo** [comment]
Ok. But it looks like a database restriction, then. I don't think we can fix it from DBeaver side here.

**Comment by dottle** [comment]
@LonwoLonwo 
The Stored Procedure can be executed successfully using Sybase PowerBuilder, and we have also utilized other vendor software that runs smoothly through the ODBC Driver.

**Comment by ShadelessFox** [comment]
Hello @dottle,

If calling the procedure doesn't work, does the `select * from view_label` query?

It looks more like a driver/database issue, as DBeaver simply asks the driver to execute a given query string.

**Comment by dottle** [comment]
Hello @ShadelessFox ,

I have identified the issue and resolved it. Thank you for your assistance

the custom stored procedure includes double quotation marks,

after setting 'quoted_identifier' off, the execution proceeds normally

![pic](https://github.com/dbeaver/dbeaver/assets/16780666/bd6b4328-c22e-45ac-8bb7-e9b896d88d5a)

**Comment by ShadelessFox** [comment]
Oh, interesting. So this is a database-specific thing. Can the issue be closed now as it's resolved?

Just a note: you can define bootstrap queries in DBeaver as shown on the screenshot:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/cbd10134-28c2-4f83-8074-a06734714a15)

**Comment by dottle** [comment]
yes, it can  be closed
