### ISSUE TITLE
Killling saved connections

### ISSUE THREAD

**Issue by altermodus** [dbeaver/dbeaver#20759]
### Description

All my database connections list is lost!

... after replace `,` to `DEFAULT NULL,`  in sql script editor.

### DBeaver Version

23.1.3

### Operating System

Ubuntu 22.10

### Database and driver

Any driver (tested on MariaDB, PostgreSQL)

### Steps to reproduce

1) Create and save any connection on **Database tab**
2) Open database and open **Script editor** for opened database and print `,`
3) Press **Ctrl+H**, press **"Replace ..."**
4) Replace `,` to `DEFAULT NULL,` and press `OK`

and i get an exception:

```
com.google.gson.stream.MalformedJsonException: Unterminated object at line 3 column 18 path $..Mydb

Reason:
com.google.gson.stream.MalformedJsonException: Unterminated object at line 3 column 18 path $..Mydb
```

Restart Dbeaver and I get and exception:

```
com.google.gson.stream.MalformedJsonException: Unterminated object at line 2 column 17 path $.

Reason:
com.google.gson.stream.MalformedJsonException: Unterminated object at line 2 column 17 path $.
```

**Comment by E1izabeth** [comment]
Thank you for bug report.

We had something similar some time ago, but couldn't reproduce #20065

I can reproduce it now.

**Comment by E1izabeth** [comment]
This suggestion should help to eliminate the error message and restore your connections  https://github.com/dbeaver/dbeaver/issues/20065#issuecomment-1560624522

**Comment by altermodus** [comment]
I found backup json files in 
```
.local/share/DBeaverData/workspace6/General/.dbeaver/.data-sources.json.bak
.local/share/DBeaverData/workspace6/General/.dbeaver/.credetials-config.json.bak
.local/share/DBeaverData/workspace6/General/.dbeaver/.project-metadata.json.bak
```
and restore (rename) to
```
.local/share/DBeaverData/workspace6/General/.dbeaver/data-sources.json
.local/share/DBeaverData/workspace6/General/.dbeaver/credetials-config.json
.local/share/DBeaverData/workspace6/General/.dbeaver/project-metadata.json
```
but in **data-sources.json** I was found
```
    "folders": {
        "Folder1": {}default null DEFAULT NULL DEFAULT NULL,
        "Folder2": {}default null DEFAULT NULL DEFAULT NULL,
        "Folder3": {}default null DEFAULT NULL DEFAULT NULL,
        "Folder4": {}default null DEFAULT NULL DEFAULT NULL,
        "prod": {
            "parent": "Folder5"
...
```
(and **project-metadata.json**)

DBeaver was replace text in json files instead SQL editor.

I fix **project-metadata.json** and **data-sources.json** files and my DBeaver start correctly.

I became interested in the problem. DBeaver working correctly, but...

Ctrl+H - open Search window and designed for searching in files instead SQL editor. 
I should press **Ctrl+F** instead **Ctrl+H**

I am sorry :)

But DBeaver should be protect own configuration files from user. I think.

Thanks.

**Comment by E1izabeth** [comment]
We inherit this dialog from Eclipse platform, but we didn't expect such issue. It definitely shouldn't touch any files like data-sources.json. And I would expect that the dialog called from SQL Editor context would perform replacements only in the current SQL Editor.

**Comment by E1izabeth** [comment]
We want to restrict places where the files are searched. .dbeaver should not be included there.
