### ISSUE TITLE
SQL Server Date values shown incorrectly

### ISSUE THREAD

**Issue by endo64** [dbeaver/dbeaver#20762]
### Description

I have a `datetime` value in SQL Server 2019: `2018-12-31 00:00:00.000`
When I select it, if Value view format is `Display` or `Editable` it looks `12/31/2019` in the results grid.

`SELECT CAST(My_Date AS Date) AS MY_DATE`  

It looks `2018-12-31` in `Database Native` mode. But even it look like that, when I copy or export, it becomes `12/31/2019`.

### DBeaver Version

Community edition 23.1.3.202307231901

### Operating System

Windows 10

### Database and driver

SQL Server 2019 Enterprise Edition
Microsoft JDBC Driver for SQL Server

**Comment by ShadelessFox** [comment]
Hello @endo64,

Can you please see what's set here for "Date"?

![image](https://github.com/dbeaver/dbeaver/assets/35821147/8fec0c3c-d156-44b2-aea7-37dcea388a56)

You can also try enabling the "Disable date/time formatting".

Please let me know if it helps.

**Comment by endo64** [comment]
It is `MM/dd/YYYY`.
If I disable date/time formatting it shows always in YYYY-MM-DD format but copy/paste works in that case.

<img width="458" alt="image" src="https://github.com/dbeaver/dbeaver/assets/840604/fe996959-c222-4510-aa5f-02633997e8fd">

**Comment by Destrolaric** [comment]
@endo64 YYYY - is "week-based-year"
A week is defined by:

The first day-of-week. For example, the ISO-8601 standard considers Monday to be the first day-of-week.
The minimal number of days in the first week. For example, the ISO-8601 standard counts the first week as needing at least 4 days.
The ISO-8601 definition, where a week starts on Monday and the first week has a minimum of 4 days.

Try using `yyyy` in the pattern. It will help with your issue

**Comment by Destrolaric** [comment]
Be free to write again if there will be issues. Closing the ticket for now
