### ISSUE TITLE
brackets pair custom color

### ISSUE THREAD

**Issue by shtoormanSam** [dbeaver/dbeaver#20767]
DBeaver Community 23.1.2
Please add the ability to set the color for the active pair of brackets ( ), and to highlight matches with the current word.
Or tell me how to do it (I didn't find it in the instructions).

The existing setting has a weak contrast for a dark theme.
![image](https://github.com/dbeaver/dbeaver/assets/127952519/7fbef88c-7a01-445c-8bee-c6c1c2016795)

**Comment by ShadelessFox** [comment]
Hello @shtoormanSam,

You can configure highlighting color here:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/5ad4e5a9-3540-431d-9f7a-159543d68e16)

Bracket pairs are also shown when one of them is selected:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/a68e0d32-6595-4d1d-b1fe-0d1f843a1bea)

Or do you want to highlight enclosing brackets when the caret is placed somewhere between?

**Comment by shtoormanSam** [comment]
Hi, ShadelessFox!
Thanks for selected occurrences, this is OK.
About brackets — I mean select background colour (light brown at your
picture) of active brackets pair.
And, as useful future — coloured brackets pairs
(yellow/pink/blue/etc.) as in other modern editors like VSCode.

Thank you for fast reply!


чт, 3 авг. 2023 г. в 15:44, ShadelessFox ***@***.***>:

**Comment by ShadelessFox** [comment]
You're welcome!

Can you please create a separate issue for supporting "rainbow" brackets if you're interested in that feature?

I will close this ticket as the original issue was resolved.
