### ISSUE TITLE
[PostGIS] Do not linearize curved geometries in the data grid

### ISSUE THREAD

**Issue by rbovard** [dbeaver/dbeaver#20774]
### Description

As discussed here https://github.com/dbeaver/dbeaver/issues/19608#issuecomment-1662002883 with @ShadelessFox, the curved geometries are linearized in the data grid **and** in the viewer for display purposes. But it should be only linearized for the viewer, not in the data grid because we want to see the original data there.

### DBeaver Version

23.1.3

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by rbovard** [comment]
Thanks, it's working fine!
