### ISSUE TITLE
server output in ansi (windows-1252) only

### ISSUE THREAD

**Issue by NotSignificant** [dbeaver/dbeaver#20776]
### Description

I tryed my best - even with tips from this source here - to get all outputs in dbeaver to utf8 (like all my databases do). This works well in all cases but not in the server output window (SQL editor bottom toolbar, console like), where still windows-1252 is used. Did I miss something (all my dbeaver/eclipse preferences seem to be configured as utf8)?
![anhang](https://github.com/dbeaver/dbeaver/assets/133522530/8100a245-bc81-4367-918c-900624d280be)
these cryptic letters should be the euro sign.
(https://github.com/orgs/dbeaver/discussions/20579)

### DBeaver Version

23.1.3 on Eclipse Version: 2023-06 (4.28.0)

### Operating System

MS Windows 10 V22H2 (Build 19045.3208)

### Database and driver

PostGreSQL 15
MySQL 10.4.28-MariaDB

### Steps to reproduce

In PostGreSQL for example use 'raise notice 'öäüß' in any function of your choice and call it or try to get some server outputs with non ansi unicodes ("create table if not exists public.t_öäüß (test_id serial)" two times for example).

**Comment by ShadelessFox** [comment]
Hello @NotSignificant,

Can you please open Help -> Installation Information -> Configuration, search for `.encoding` and send the results?

You might try adding the following line to the end of the `dbeaver.ini` file (located next to the DBeaver's executable):
```
-Dfile.encoding=UTF-8
```

**Comment by NotSignificant** [comment]
Since I'm working with Eclipse the path seems to be Help -> About Eclipse IDE -> Installation Details -> Configuration and it's output is

`*** Date: Donnerstag, 3. August 2023, 17:23:56 Mitteleuropäische Sommerzeit

*** Platform Details:

*** System properties:
file.encoding=UTF-8
native.encoding=Cp1252
stderr.encoding=Cp1252
stdout.encoding=Cp1252
sun.io.unicode.encoding=UnicodeLittle
sun.jnu.encoding=Cp1252

*** System environment variables:

*** Features:

*** Plug-in Registry:

*** User Preferences:
/instance/org.jkiss.dbeaver.core/pg.export.all.encoding=UTF-8

*** Current Install Configuration:

*** Security Configuration:

`
-Dfile.encoding=UTF-8 helps although file.encoding already was UTF-8 encoded. I don't know if this is a bug in eclipse or a bug in dbeaver now. But I think it's in eclipse, because the configuration details are part of eclipse, even if dbeaver isn't there. Or could it be, that you use -Dfile.encoding instead of file.encoding somewhere?
after modifying the configuration looks like this

`*** Date: Donnerstag, 3. August 2023, 18:33:08 Mitteleuropäische Sommerzeit

*** Platform Details:

*** System properties:
-Dfile.encoding=UTF-8
file.encoding=UTF-8
native.encoding=Cp1252
stderr.encoding=Cp1252
stdout.encoding=Cp1252
sun.io.unicode.encoding=UnicodeLittle
sun.jnu.encoding=Cp1252

*** System environment variables:

*** Features:

*** Plug-in Registry:

*** User Preferences:
/instance/org.jkiss.dbeaver.core/pg.export.all.encoding=UTF-8

*** Current Install Configuration:

*** Security Configuration:

`

**Comment by ShadelessFox** [comment]
The `-D` prefix is required by the JVM to distinguish between system properties and other JVM options.

I'm a bit confused. Is the issue resolved?

**Comment by NotSignificant** [comment]
I'm confused too, but yes, the issue is resolved.

**Comment by ShadelessFox** [comment]
Although we both are confused, I'm glad I was able to help you. :)

I believe the ticket can be closed now.
