### ISSUE TITLE
[PostGIS] Strip SRID prefix before passing the geometry to the viewer

### ISSUE THREAD

**Issue by rbovard** [dbeaver/dbeaver#20773]
### Description

As discussed here https://github.com/dbeaver/dbeaver/issues/19608#issuecomment-1662002883 with @ShadelessFox, the SRID prefix is not stripped before passing the geometry to the viewer when viewing linearize geometries data, thus the geometry isn't diplayed.

Ex:
- `SRID=2056;COMPOUNDCURVE((2554021.510361592 1146045.9171061674, 2554011.061413642 1146056.4932663445))`
- `SRID=2056;COMPOUNDCURVE((2553886.8849250823 1145802.2807940794 375.55, 2553881.9850559025 1145812.2269134985 375.38))`

### DBeaver Version

23.1.3

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by ShadelessFox** [comment]
Will be fixed in #20774

**Comment by rbovard** [comment]
@ShadelessFox: Thanks for the fix. I just tested my 2 examples with v23.1.5 and it doesn't seem to work.

```
SELECT st_geomfromewkt('SRID=2056;COMPOUNDCURVE((2554021.510361592 1146045.9171061674, 2554011.061413642 1146056.4932663445))');
SELECT st_geomfromewkt('SRID=2056;COMPOUNDCURVE((2553886.8849250823 1145802.2807940794 375.55, 2553881.9850559025 1145812.2269134985 375.38))');
```

Is it the same on your side?

**Comment by ShadelessFox** [comment]
Thanks for the feedback. Looks like it only works for SRID 4326. I'll reopen the issue now.

**Comment by rbovard** [comment]
Thanks a lot @ShadelessFox, it works perfectly!
