### ISSUE TITLE
[Feature Request] Enable a Checkbox For "Use Windows Authentication" for SQL Server Connections

### ISSUE THREAD

**Issue by kyleflan** [dbeaver/dbeaver#2077]
When using the Microsoft JDBC Driver, authenticating to SQL Server using Windows/Domain credentials is cumbersome. The user has to open the driver properties, search for "integratedSecurity" and set it to "true", and be aware that they should leave the user/password inputs blank.

_(Current instructions for connecting using the Microsoft driver [here](http://www.orsburn.net/2014/09/allow-windows-authentication-using-sql.html) and jTDS driver [here](http://www.orsburn.net/2013/01/connecting-to-sql-server-with-jtds.html).)_

The driver properties tab should be for advanced users, and general users shouldn't have to access it to create a connection.

My suggestions is to add a checkbox to the New Connection screen for Microsoft JDBC Driver connections that allows the user specify to use Windows Authentication. When checked, this would clear out and disable the username and password input boxes and set the integratedSecurity option to "true". 

Screen mock-up (this was made on a Mac, but would obviously only apply to Windows machines since the auth library is a dll). Additionally maybe put "(Windows Only)" in the checkbox label.

![image](https://user-images.githubusercontent.com/5608074/29671897-55b8f3ea-88b0-11e7-8930-d6b4ccc9316a.png)

**Comment by serge-rider** [comment]
Extra FR for #810

**Comment by serge-rider** [comment]
@efradkin 👍
