### ISSUE TITLE
The Chinese description of the fields in the Oceanbase database table is garbled  code

### ISSUE THREAD

**Issue by pengyong255237** [dbeaver/dbeaver#20784]
### Description

The Chinese description of the fields in the Oceanbase database table is garbled  code
![Snipaste_2023-08-03_15-45-39](https://github.com/dbeaver/dbeaver/assets/28984017/0808f7d1-3990-4055-902c-67477f3cd5b2)

The database plugin of IDEA can display table field descriptions normally
![Snipaste_2023-08-03_10-02-47](https://github.com/dbeaver/dbeaver/assets/28984017/0859801c-5926-4002-a662-9f0682a55683)

### DBeaver Version

Community 23.1.2.202307091549

### Operating System

windows

### Database and driver

driver：oceanbase-client-2.4.3.jar

**Comment by LonwoLonwo** [comment]
Hello @pengyong255237 

Please translate your ticket text into English, including the title.

**Comment by pengyong255237** [comment]
> Hello @pengyong255237
> 
> Please translate your ticket text into English, including the title.

done

**Comment by LonwoLonwo** [comment]
And what server version do you use?

**Comment by ShadelessFox** [comment]
Hello @pengyong255237,

Does the issue occur in the "DDL" tab? Please make sure to enable the "show comments" option.

**Comment by pengyong255237** [comment]
> Are you asking about the window version or the dbeaver version?

**Comment by pengyong255237** [comment]
> 您使用什么服务器版本？

Are you asking about the window version or the dbeaver version?

**Comment by pengyong255237** [comment]
> 你好@pengyong255237,
> 
> 问题是否出现在“DDL”选项卡中？请确保启用“显示评论”选项。
The ER chart tab displays garbled code, and the DDL tab does not display the DDL SQL for field descriptions, as shown in the following figure
![123](https://github.com/dbeaver/dbeaver/assets/28984017/bb016575-c45b-4080-a441-95e32029a1b9)
![456](https://github.com/dbeaver/dbeaver/assets/28984017/16a29de0-8ae3-4943-b986-318965d95f96)

**Comment by pengyong255237** [comment]
> > 您使用什么服务器版本？
> 
> Are you asking about the window version or the dbeaver version?

After executing the update field description sql statement, only English alphabet and Arabic numerals will be displayed. Chinese is still garbled. The ddl tab does not display the field description at all

![000](https://github.com/dbeaver/dbeaver/assets/28984017/5ffae5b3-b73c-4194-9ea1-70f5e3e310e5)

**Comment by pengyong255237** [comment]
> > > 您使用什么服务器版本？
> > 
> > 
> > Are you asking about the window version or the dbeaver version?
> 
> After executing the update field description sql statement, only English alphabet and Arabic numerals will be displayed. Chinese is still garbled. The ddl tab does not display the field description at all
> 
> ![000](https://user-images.githubusercontent.com/28984017/258264964-5ffae5b3-b73c-4194-9ea1-70f5e3e310e5.png)

![789](https://github.com/dbeaver/dbeaver/assets/28984017/0cd4734f-9abe-4ca2-8cf3-051d69ea8eac)

**Comment by pengyong255237** [comment]
The newly updated field descriptions can be correctly displayed in the IDEA Database plug-in. They can be displayed in Chinese, English, and Arabic numerals

![111](https://github.com/dbeaver/dbeaver/assets/28984017/ca7a48a7-e806-4bcf-b9d8-7fa4a04d0f4f)

**Comment by LonwoLonwo** [comment]
Hello @pengyong255237 

On your screens, I see that you have a custom connection to OceanBase.

Did you try to connect with the supported DBeaver connector?

![2023-08-28 17_57_47-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/c8649b28-5316-41d4-adfd-796f88210ea8)

**Comment by pengyong255237** [comment]
> 
The custom connection through OceanBase cannot connect to my OceanBase database, and I must change the driver package for OceanBase https://github.com/oceanbase/obconnector-j The downloaded driver package can be connected, but it will not display comments. Please note that using this driver package will not display comments in dbeaver at all!

And then I started https://github.com/oceanbase/obconnector-j I downloaded the source code and modified the SQL for extracting data table field annotations in the source code, and created a new driver jar package. After connecting to the database through the new driver package, annotations appeared in the dbeaver, but they were all garbled,

Dbeaver comes with oceanbase driver
![image](https://github.com/dbeaver/dbeaver/assets/28984017/27d360c8-fd93-43a7-b012-fd9e190ef0e3)

Driver package source code modification
![image](https://github.com/dbeaver/dbeaver/assets/28984017/8993e229-72f7-4354-aeef-e3f65bb2fc5c)

**Comment by ShadelessFox** [comment]
What if you perform a select from `user_col_comments`, will it contain garbled characters in the result set?

**Comment by pengyong255237** [comment]
> 如果执行 select from `user_col_comments`，结果集中会出现乱码吗？
Executing this SQL through the dbeaver tool can display it normally. Do you need to modify the parameters of the dbeaver tool?
![image](https://github.com/dbeaver/dbeaver/assets/28984017/6c7472f3-88eb-4a52-ab8f-d7cd89168b14)

**Comment by ShadelessFox** [comment]
Thank you. It looks like a UI encoding issue. We'll investigate this issue soon.

**Comment by E1izabeth** [comment]
Probably will be fixed in scope of dbeaver/pro#1905

**Comment by Matvey16** [comment]
@pengyong255237 
IF it is possible, please check our EA version https://dbeaver.io/files/ea/ to verify if this issue was fixed

**Comment by pengyong255237** [comment]
> @pengyong255237 如果可能，请检查我们的 EA 版本https://dbeaver.io/files/ea/以验证此问题是否已修
Okay, I'll try it now

**Comment by pengyong255237** [comment]
> @pengyong255237 如果可能，请检查我们的 EA 版本https://dbeaver.io/files/ea/以验证此问题是否已修复
Through the Early Access version, the Chinese description can be displayed normally. Thank you!

![image](https://github.com/dbeaver/dbeaver/assets/28984017/1ccf3347-f448-4702-bda7-06510346888f)

**Comment by E1izabeth** [comment]
Thank you for checking.
