### ISSUE TITLE
Scan driver class in class path

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/dbeaver#20780]
**Is your feature request related to a problem? Please describe.**
I have a JDBC driver wrapper called JDBCX, which works only when a real JDBC driver exists. It has its owner driver class `io.github.jdbcx.WrappedDriver` and expects a slightly different connection string (e.g. `jdbcx:*` instead of `jdbc:*`). I added JDBCX in [global classpath](https://github.com/dbeaver/dbeaver/issues/14080#issuecomment-946542109), but the driver didn't show up in driver manager, as I reported earlier in #19165.

I'm not sure if there's any specific reason of using the selected driver. Can we use below approach to find suitable driver to use?
```java
for (Driver d : ServiceLoader.load(Driver.class, currentClassLoader)) {
    if (d.acceptsURL(url)) {
        return d.connect(url, props);
    }
}
```

**Describe the solution you'd like**
When no driver was selected in driver manager, use service loader to find suitable driver from current classpath to use.

**Describe alternatives you've considered**
I actually have a temporary workaround at this point, but it's tricky and unfortunately does not work for all cases...
1. Ensure JDBCX has been added in global classpath
2. Update a driver's classpath in driver manager by adding JDBCX and select `io.github.jdbcx.WrappedDriver` as driver class
3. Re-open driver manager and remove JDBCX from the driver's classpath(and don't make change to driver class)
4. Use the updated driver a connection string `jdbcx:*` to access database as usual

**Additional context**
If it helps, you may use [this driver](https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/jdbcx/jdbcx-driver/0.2.0-SNAPSHOT/jdbcx-driver-0.2.0-20230802.160655-28.jar) to test.

**Comment by ShadelessFox** [comment]
Hello @zhicwu,

We don't want to iterate over all loaded drivers and use the first suitable one. We might have several drivers that accept the given URL.

I believe you can specify `io.github.jdbcx.WrappedDriver` as the "class name" on the "Settings" page instead of choosing it from the drop-down.

Does it solve your issue?

**Comment by zhicwu** [comment]
> I believe you can specify io.github.jdbcx.WrappedDriver as the "class name" on the "Settings" page instead of choosing it from the drop-down.

Thank you for the suggestions. I tried specifying the class name explicitly, but the WrappedDriver is unable to find the actual driver class. This may be because the class loader for the global classpath is the parent of the class loader for the driver classpath.

Anyway, this is probably too complex for people who is not familiar with JDBC/Java to use. Maybe it's the best to add JDBCX as a new driver. I'll come up with a PR for that.
