### ISSUE TITLE
Export to XLSX produces corrupt file

### ISSUE THREAD

**Issue by eteichm** [dbeaver/dbeaver#20792]
b### Description

since version DBeaver 23.1.3, the XLSX export produces a corrupt file.
Here is the error message: Excel cannot open the file '20230803-164007.xlsx' because the file format or file extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file.

### DBeaver Version

Community Edition 23.1.3

### Operating System

Windows x64

### Database and driver

Database: Apache Hive 1.2.1000.2.6.5.0-292
Driver: hive-jdbc-2.0.0-standalone

### Steps to reproduce

1. I connect to the database
2. I execute my sql script
3. I push the Excel button which again executes my sql script and produces an XLSX file
4. This XLSX file is corrupt since version DBeaver 23.1.3

**Comment by E1izabeth** [comment]
Please provide a sample table ddl and table data to reproduce the issue.

**Comment by eteichm** [comment]
When testing with the sample table data, the error disappeared.  So, I suppose this is due to an error on the server side.
