### ISSUE TITLE
The DBeaver program is very dangerous. It has backdoors and daemons. After you install it, your computer will be logged on to your computer at any time by DBeaver developers, modify your program, and create data tables.

### ISSUE THREAD

**Issue by transshipment** [dbeaver/dbeaver#20790]
### Description

The DBeaver program is very dangerous. It has backdoors and daemons. After you install it, your computer will be logged on to your computer at any time by DBeaver developers, modify your program, and create data tables.

### DBeaver Version

The DBeaver program is very dangerous. It has backdoors and daemons. After you install it, your computer will be logged on to your computer at any time by DBeaver developers, modify your program, and create data tables.

### Operating System

The DBeaver program is very dangerous. It has backdoors and daemons. After you install it, your computer will be logged on to your computer at any time by DBeaver developers, modify your program, and create data tables.

### Database and driver

The DBeaver program is very dangerous. It has backdoors and daemons. After you install it, your computer will be logged on to your computer at any time by DBeaver developers, modify your program, and create data tables.

### Steps to reproduce

The DBeaver program is very dangerous. It has backdoors and daemons. After you install it, your computer will be logged on to your computer at any time by DBeaver developers, modify your program, and create data tables.

### Additional context

The DBeaver program is very dangerous. It has backdoors and daemons. After you install it, your computer will be logged on to your computer at any time by DBeaver developers, modify your program, and create data tables.

**Comment by ShadelessFox** [comment]
Yes.
