### ISSUE TITLE
multiple selection

### ISSUE THREAD

**Issue by Pit37** [dbeaver/dbeaver#20798]
It would be cool to have multi-line editing (multiple selection) like in storm.

**Comment by E1izabeth** [comment]
I believe it's already possible in DBeaver.

1. Press Alt+Shift+A to enter block selection mode
2. Use arrow keys or mouse left-click dragging to extend the selection
3. Edit in column mode
4. Press Alt+Shift+A again to leave block selection mode

Is it what are you looking for?

**Comment by Pit37** [comment]
Almost. You can't move the cursor with the arrows on the keyboard. Plus I would like to move arrows with ctrl to be able to move to key places in a line (brackets, end of word/token...).

**Comment by E1izabeth** [comment]
I see. Unfortunately, there is nothing we can do here, as it comes from the Eclipse platform that DBeaver relies on.
