### ISSUE TITLE
Rendered display of Clickhouse Map Type

### ISSUE THREAD

**Issue by larrachecoeur** [dbeaver/dbeaver#20797]
It would be supercool if Clickhouse Map Types could be rendered as Array of key-values 

e.g.

[{ukf_src_lab=ZLAB, ukf_src_code=K, ukf_src_display=Kalium, ukf_src_group_display=Klinische Chemie}]
(for this the Preview Panel ist an empty grid - it seem that the entrys could not be parsed correctly)

### This is the expected display   

|idx|name|value|
|-|---|----|
|0|ukf_src_lab|ZLAB|
|1|ukf_src_code|K|
|2|ukf_src_display|Kalium|
|3|ukf_src_group_display|Klinische Chemie|

**Comment by E1izabeth** [comment]
What's your Clickhouse server and driver version? You can check it in the connection settings with the "Test connection" button.

**Comment by larrachecoeur** [comment]
ClickHouse release 23.7Dbeaver is latest version too

**Comment by E1izabeth** [comment]
Connected issues #20591 and #20388
