### ISSUE TITLE
Firebird Embeded (Firebird-2.5.4.26856-0_x64_embed). Trying to connect to embedded database file. 

### ISSUE THREAD

**Issue by troydudley** [dbeaver/dbeaver#2079]
Firebird Embeded (Firebird-2.5.4.26856-0_x64_embed). Trying to connect to embedded database file. Get this error: Unable to complete network request to host "(null)". [SQLState:08006, ISC error code:335544721]
java.lang.IllegalArgumentException: Unsupported array argument type: class org.firebirdsql.jna.fbclient.ISC_STATUS

Please see attached file with screen shots.
[dbeaver-debug.log.pdf](https://github.com/serge-rider/dbeaver/files/1250550/dbeaver-debug.log.pdf)
[dbeaver-.log.pdf](https://github.com/serge-rider/dbeaver/files/1250551/dbeaver-.log.pdf)
[Dbeaver-error-screenshots.pdf](https://github.com/serge-rider/dbeaver/files/1250552/Dbeaver-error-screenshots.pdf)

**Comment by GiantCrocodile** [comment]
Please attach images or text files in future. PDF files can contain malicious content and thus are not ideal for public issue trackers.

**Comment by serge-rider** [comment]
Tracked in #3397
