### ISSUE TITLE
Lost connection properties when reading driver property info

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/dbeaver#20808]
### Description

I have a JDBC wrapper relies on a connection property `jdbcx.custom.classpath` to find suitable driver. It works well in DBeaver. However, I found that all properties for the actual driver lost in `Edit Connection` -> `Driver Properties`. I think it's caused by [this line](https://github.com/dbeaver/dbeaver/blame/9434e6e86a0c42fb1456c1e7078dbe1a333878f7/plugins/org.jkiss.dbeaver.model.jdbc/src/org/jkiss/dbeaver/model/impl/jdbc/JDBCDataSourceProvider.java#L79). Is there any specific reason of commenting out the line?

```java
Properties driverProps = new Properties();
//driverProps.putAll(connectionInfo.getProperties()); <--- why?
DriverPropertyInfo[] propDescs;
try {
    propDescs = driver.getPropertyInfo(connectionInfo.getUrl(), driverProps);
} catch (Throwable e) {
    log.debug("Cannot obtain driver's properties", e); //$NON-NLS-1$
    return null;
}
if (propDescs == null) {
    return null;
}
```

### DBeaver Version

Community Edition 23.1.3.202307231901

### Operating System

macOS Ventura 13.5 (22G74)

### Database and driver

It's unrelated to the issue but here you go:

1. Database name and version: ClickHouse 22.8
2. Driver name and version: JDBCX 0.2.0 + ClickHouse JDBC Driver 0.4.6

### Steps to reproduce

1. Add [JDBCX driver](https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/jdbcx/jdbcx-driver/0.2.0-SNAPSHOT/jdbcx-driver-0.2.0-20230805.160359-31.jar)
2. Create a folder which container ClickHouse JDBC Driver, for example: `~/MyJdbcDrivers`
3. Create a connection using JDBCX, use URL `jdbcx:ch:explorer@play.clickhouse.com:443?ssl=true` and set connection property `jdbcx.custom.classpath` to `~/MyJdbcDrivers`, no credentials or any other changes are required
4. Validate the connection - it should work
5. Edit the connection and switch to driver properties tab, there's no connection properties for ClickHouse but a few for JDBCX(the wrapper)

**Comment by E1izabeth** [comment]
There is no any specific reason why we commented out this line, it was always commented according to the git history. We haven't met a driver which needed it yet, so your case most probably was never working. We will investigate the issue. Thank you.

**Comment by E1izabeth** [comment]
If I correctly understood it would be nice to find a time to work on this issue in the nearest time as we have a PR that added JDBCX driver https://github.com/dbeaver/dbeaver/pull/20811

**Comment by E1izabeth** [comment]
Maybe this line broke some drivers, but we don't know exactly. Probably we should add a property to the DBeaver driver settings (driver-property) to specify if we should pass all driver properties or not and turn it off by default.

**Comment by zhicwu** [comment]
Thanks @E1izabeth. I'm also not sure if it's better to use `Properties driverProps = new Properties(connectionInfo.getProperties());` instead of cloning the object.

> If I correctly understood it would be nice to find a time to work on this issue in the nearest time as we have a PR that added JDBCX driver

Yes. Defining all properties in `~/.jdbcx/config.properties` avoids the problem for a single connection. But it does not work for multiple connections with varying preferences, and is cumbersome to configure initially.

> Maybe this line broke some drivers, but we don't know exactly. Probably we should add a property to the DBeaver driver settings (driver-property) to specify if we should pass all driver properties or not and turn it off by default.

That's a good idea! This approach allows enabling the feature only for a specific driver without affecting others.
