### ISSUE TITLE
ERD files do not open in DBeaver on other computers

### ISSUE THREAD

**Issue by iraidaa** [dbeaver/dbeaver#20800]
### Description

Even if users have the same database connection, they will not be able to open a custom diagram based on this connection received from another user either in File -> Open file or the Project Explorer (after adding the erd to the C:\Users\user\AppData\Roaming\DBeaverData\workspace6\project\Diagrams folder on Windows).

![image](https://github.com/dbeaver/dbeaver/assets/49681450/0d1c6f18-a3d4-47d0-a7d0-1fa786bcdb4e)

### DBeaver Version

Community Edition 23.1.3

### Operating System

Windows

### Database and driver

Microsoft SQL Server

### Steps to reproduce

1. Create a new connection (SQL Server on db9)
2. Create a new custom diagram in Project Explorer by adding some of the existing tables
3. Share it with someone who has the same connection (SQL Server on db9)
4. Let this person try to open the erd in the ways mentioned above

**Comment by ShadelessFox** [comment]
This is expected as ERD uses data sources' UUIDs that are unique and not shared within different projects/machines.

We can try to improve it by asking the user to choose data source if it can't be found by its UUID when openining an ERD.
