### ISSUE TITLE
MacOS: Locale settings not followed. Showing decimal comma instead of period

### ISSUE THREAD

**Issue by ellipticview** [dbeaver/dbeaver#20810]
### Description

Running on MacOS. Settings as in attached picture. Note the sample displayed number: 4,567.89
Connecting to a SQLite database. Numeric values with a decimal portion are displayed as e.g. 0,1234

### DBeaver Version

Version 23.1.2.202307091549

### Operating System

MacOS Ventura 13.3.1

### Database and driver

Sqlite

### Steps to reproduce

select colname from table

**Comment by ellipticview** [comment]
![Screenshot 2023-08-06 at 09 51 25](https://github.com/dbeaver/dbeaver/assets/8074771/a1a84a5f-ac70-4638-af2a-d24e52a860e9)

**Comment by hrimthrusa** [comment]
Hello.

Could you please verify that your Data Format settings are set to English language in  **Window -> Preferences -> Editors -> Data Editor -> Data Formats** as the following picture shows:

![data formats](https://github.com/dbeaver/dbeaver/assets/97725836/009f0ec1-e60f-4b5c-8e53-dcd0b1ed6665)

**Comment by ellipticview** [comment]
Settings as shown below. Changing the Country does the trick. Thankyou. However, not sure why dBeaver would derive a number format from en_NL differently from MacOS.
![Screenshot 2023-08-10 at 21 54 14](https://github.com/dbeaver/dbeaver/assets/8074771/c6fc3900-c0e6-47c1-801e-97f87efe46b9)

**Comment by ShadelessFox** [comment]
Hello @ellipticview,

Regional formatting options shown in DBeaver come from Java runtime. It's not synchronized with your system settings.
