### ISSUE TITLE
sql editor - completion

### ISSUE THREAD

**Issue by collicalex** [dbeaver/dbeaver#2081]
Hi,

When typing sql statement in sql editor, I have the code completion, but it's working a little bit strange...

Example: I have a table "cash_mgt_data"

I've typped:
select * from cash

It display a popup with "CASHBALANCE" (it's a name of another database on my server), and nothing else.

I've hit escape key, it closed the popup, and then ctrl + space. It reopen the popup, but now in completion list I have:  CASHBALANCE and other lines with dbo.cash_mgt_data (and other table name begining with dbo.cash...).

Question: Why there is no tables listed in first popup completion?
Question: Is it possible to not complete on other database name?

Note:
It's with Sybase ASE.
I'm not connected with the "dbo" user.
I use option "Use short object names (omit schema/catalog)".
I use option "Use global search (in all schemas)".

Regards

Alex

**Comment by Jogai** [comment]
Disabling "Use global search (in all schemas)" fixes the problem (tested in 5.3)
