### ISSUE TITLE
SQL Server:- Generated Database Insert Statement Skips Identity Column

### ISSUE THREAD

**Issue by DanielAdeniji** [dbeaver/dbeaver#20812]
### Description

**SQL Server**

1. In SQL Server, Created a new table ( [dbo].[columnIdentity] )

2. The SQL Server table has a lone column ( id )

3. The column is the primary key

4. It is expected that the column's data is valuable and will be kept and preserved

**DBeaver**

1. In Dbeaver, Export Data out of the SQL Server Table
2. Unfortunately, the exported data skips the identity column  altogether

### DBeaver Version

Dbeaver Community 23.1.1

### Operating System

MS Windows 10

### Database and driver

1) Database Name:- SQL Server

2) Database Driver:- Microsoft SQL Server JDBC

### Steps to reproduce

**SQL Server**

Here is the SQL for creating the table in SQL Server.

``` SQL

/*
    drop table [dbo].[columnIdentity];
*/
if object_id('[dbo].[columnIdentity]') is null
begin

    create table [dbo].[columnIdentity]
    (

            [id]     int    not null
        
                     identity(1,1)

            , constraint [PK_columnIdentity]

              primary key

              nonclustered
              (
                    [id]
              )

    )

end
go

truncate table [dbo].[columnIdentity]
go


set identity_insert [dbo].[columnIdentity] on
go

insert into [dbo].[columnIdentity]
(
    [id]
)
select 

    1 as [id]

union all

select 

    3 as [id]


union all

select 

    7 as [id]

set identity_insert [dbo].[columnIdentity] off
go



```

**DBeaver**

Here is the SQL that DBeaver generates:-

``` SQL

insert into DBLab.dbo.columnIdentity () values ();
insert into DBLab.dbo.columnIdentity () values ();
insert into DBLab.dbo.columnIdentity () values ();

```

**Comment by serge-rider** [comment]
I cannot reproduce this:
```
INSERT INTO TestDb.dbo.columnIdentity
(id)
VALUES(1);
INSERT INTO TestDb.dbo.columnIdentity
(id)
VALUES(3);
INSERT INTO TestDb.dbo.columnIdentity
(id)
VALUES(7);
```

What SQL Server driver do you use in DBeaver?

**Comment by DanielAdeniji** [comment]
Serge:-

Good morning, fam.

Connection Settings

[cid:d51a877f-17c5-4052-a45f-3b335cf6e0c7]




Driver:- Microsoft SQL Server JDBC Diver

[cid:4da14fe9-fda3-4b9d-8d36-02c1c0530bb9]


SQL Server Version



Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)

Oct  8 2022 05:58:25

Copyright (C) 2022 Microsoft Corporation

Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19042: ) (Hypervisor)




SQL Server - Create and Populate Table



set nocount on

go



set XACT_ABORT on

go


/*

    drop table [dbo].[columnIdentity];

*/

if object_id('[dbo].[columnIdentity]') is null

begin


    create table [dbo].[columnIdentity]

    (


            [id]     int    not null



                     identity(1,1)


            , constraint [PK_columnIdentity]


              primary key


              nonclustered

              (

                    [id]

              )


    )


end

go


truncate table [dbo].[columnIdentity]

go



set identity_insert [dbo].[columnIdentity] on

go


insert into [dbo].[columnIdentity]

(

    [id]

)

select


    1 as [id]


union all


select


    3 as [id]



union all


select


    7 as [id]


set identity_insert [dbo].[columnIdentity] off

go



Thank You, Serge.


Daniel

________________________________

**Comment by serge-rider** [comment]
Thank you for hte information.
But I mean DBeaver driver, one of these:

![image](https://github.com/dbeaver/dbeaver/assets/6398845/02112ada-c6e2-4e62-b36b-bf9d72233f9a)

Or could you send a screenshot of your connection configuration?

**Comment by DanielAdeniji** [comment]
Serge:-

The second one "Microsoft SQL Server".



[cid:0e79aad4-2fe4-4223-827b-ae6c06296f49]



[cid:626cb006-3656-4dd6-a566-607a92fe1a4f]




Daniel

________________________________

**Comment by MashaKorax** [comment]
@DanielAdeniji Now we've reproduced and fixed your issue.

**Comment by DanielAdeniji** [comment]
Serge, Masha, et al:-

Thank you so very much all.

Daniel
________________________________
