### ISSUE TITLE
Write a wiki page about the Materialize Driver

### ISSUE THREAD

**Issue by bobbyiliev** [dbeaver/dbeaver#20828]
**Is your feature request related to a problem? Please describe.**
The Materialize DBeaver driver extends the Postgres driver for the most part but there are some extra steps that would be worth mentioning in the Wiki.

**Describe the solution you'd like**
Adding a Materialize docs page to the Wiki will be helpful for Materialize + DBeaver all users.

**Describe alternatives you've considered**
N/A

**Additional context**
I've prepared a docs page + a reference in the Wiki sidebar menu on a fork which can be copied over:
> https://github.com/bobbyiliev/dbeaver/wiki/Database-driver-Materialize

**Comment by E1izabeth** [comment]
Thank you for contribution!

**Comment by daelynum** [comment]
Thank you for your suggestion, @bobbyiliev, and for working on the docs page. We're in the process of reviewing and prioritizing our updates, so we can't publish this right now. But we'll keep it in mind for the future. Thanks for your understanding!
