### ISSUE TITLE
"NewApplication" in menu bar

### ISSUE THREAD

**Issue by bwrightkc** [dbeaver/dbeaver#20822]
### Description

Instead of "dbeaver" in the menu bar, it states "NewApplication" - an error I've never had before. I've unisntalled and reinstalled and removed configuration, and still am seeing this and am unsure if it's a bug. 

<img width="1088" alt="Screenshot 2023-08-07 at 7 38 50 AM" src="https://github.com/dbeaver/dbeaver/assets/33914549/ae67f519-4775-400a-87ed-aaae1714a4a3">

### DBeaver Version

Community Edition Version 23.1.4.202308061552

### Operating System

macOS sonoma 14.0 (23A5301h)

### Database and driver

N/A - GUI issue before connecting to database

### Steps to reproduce

1. Install dbeaver
2. Open dbeaver
3. instead of "dbeaver" in the menu bar, it states "NewApplication" - an error I've never had before.
<img width="1088" alt="Screenshot 2023-08-07 at 7 38 50 AM" src="https://github.com/dbeaver/dbeaver/assets/33914549/ae67f519-4775-400a-87ed-aaae1714a4a3">

**Comment by E1izabeth** [comment]
Thank you for bug report. We couldn't reproduce your issue.
Probably it's somehow connected with your mac version. Have you updated your mac recently?

**Comment by bwrightkc** [comment]
> Thank you for bug report. We couldn't reproduce your issue. Probably it's somehow connected with your mac version. Have you updated your mac recently?

That's the weird part - I've been on the same version of macOS (build 23A5301h) for a month now, and this issue just started occurring today.

**Comment by E1izabeth** [comment]
Thank you for a quick response

**Comment by bwrightkc** [comment]
This issue was a macOS issue, updating to the latest public beta of Sonoma (23A5312d) fixed the issue.

**Comment by E1izabeth** [comment]
Thanks for update
