### ISSUE TITLE
auto-commit and smart commit 

### ISSUE THREAD

**Issue by Lor3nzz** [dbeaver/dbeaver#20827]
### Description

  auto-commit+smart commit switch back to manual commit after executing SQL query.
 This wasn't happening on previous version of Dbeaver

### DBeaver Version

23.1.4

### Operating System

Windows 10

### Database and driver

PostgreSQL

### Steps to reproduce

![image](https://github.com/dbeaver/dbeaver/assets/45643714/19cc136c-f187-4306-99ad-faf4300867de)

after executing update / delete / insert:

![image](https://github.com/dbeaver/dbeaver/assets/45643714/180f53e0-3965-407d-8b48-8c0ea1cfcc17)

**Comment by E1izabeth** [comment]
I reproduced the issue. Thank you for bug report.

**Comment by Matvey16** [comment]
@Lor3nzz That's a new default value for smart-commit mode. To change it to a previous behaviour you need to explicitly enable it in either connection settings or set this as default for a certain connection type
![dbeaver_gkpdY5iiHf](https://github.com/dbeaver/dbeaver/assets/82543000/8a867e7d-4a35-43ce-bcbd-6c951127364b)
![dbeaver_Ywly0Lm21N](https://github.com/dbeaver/dbeaver/assets/82543000/e6ca07c4-45da-4950-a80b-a9b4bfe8b511)

Explicit connection settings takes priority if it differs from connection type setting

**Comment by Lor3nzz** [comment]
Thanks for the explanation :)

**Comment by Cris70** [comment]
> @Lor3nzz That's a new default value for smart-commit mode. To change it to a previous behaviour you need to explicitly enable it in either connection settings or set this as default for a certain connection type

Unfortunately it does not work here.
It's driving me crazy.
I'm on Linux, Dbeaver v23.2.0.

Cris
