### ISSUE TITLE
Cannot edit variables in “Variables panel“

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#20834]
### Description

In the previous version, variable values ​​could be changed immediately, but in version 23.1.4, they cannot be modified.

![image](https://github.com/dbeaver/dbeaver/assets/59002295/bbf633af-1563-4f58-a55e-efc8955701a4)

Thank For reading. :)

### DBeaver Version

DBeaver Community 23.1.4

### Operating System

Windows 10

### Steps to reproduce

1.  @set testvar  = 'hellow'
2.  Open Variable Panel
3. Edit Value... Can't Edit.

**Comment by MashaKorax** [comment]
Thanks for your bug report!

**Comment by serge-rider** [comment]
Fixed
