### ISSUE TITLE
Connection stacked at "Load CatalogCache"

### ISSUE THREAD

**Issue by lg0nzales** [dbeaver/dbeaver#2084]
Hello,

This happen when I try to connect to a MySQL db. It stucks at the following message and I don't have any other option than close DBeaver.

![screenshot_2017-08-25_09-05-36](https://user-images.githubusercontent.com/10042101/29724188-2026b6b2-898d-11e7-8414-df5c8eab7740.png)

This have been tested with the last version of Dbeaver. Then, I tried with older versions and I found that the 4.0.5 version of enterprise edition can connect without problems but when I use the 4.0.5 version of community edition I got the same issue. 

I debugged the application with Eclipse and I have found that the problem happens when the method determineCurrentDatabase in MySQLUtils class is called but i cannot see how ee edition manage this. I understand that I could be a restriction of db configuration(i don't have access to it) but the thing is that it works with enterprise edition. 

So I just wanted to know if it is a feature for ee edition or an issue.

Thank you.

**Comment by serge-rider** [comment]
Thanks for report.
Could you say what is your MySQL server version?
I can't yet realize what is the difference. Maybe you are using different MySQL client driver versions in EE and CE (you can check this in connection properties -> Edit Driver Settings -> Download/Update)

**Comment by lg0nzales** [comment]
The MySQL version is 5.5.48-log.
I'm using the same driver for both editions: mysql-connector-java-5.1.39.jar

Thank you!

**Comment by serge-rider** [comment]
@lg0nzales could you make a thread dump (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump) when DBeaver stuck in CatalogCache?

**Comment by lg0nzales** [comment]
Sure. Find attached the thread dump.
[thdump.txt](https://github.com/serge-rider/dbeaver/files/1257856/thdump.txt)

**Comment by serge-rider** [comment]
Thanks. 
However I still don't know why it happens.
It hangs when DBeaver executes query
```sql
SELECT DATABASE()
```
It is very fast, harmless, doesn't lock any tables, etc.

Maybe you still have some differences in connection properties in CE/EE?

**Comment by xiongxoy** [comment]
![image](https://user-images.githubusercontent.com/936479/82041839-684b7000-96db-11ea-9098-7a12d0491e60.png)
