### ISSUE TITLE
Not able to run multiple SQL statements together

### ISSUE THREAD

**Issue by santoshgurao2001** [dbeaver/dbeaver#20853]
### Description

Hi All,
I am not able to run multiple which have create procedure/trigger scripts along with insert/update or create scripts.I have given the script I am using in the Steps to reproduce sectiion.Please help me resolve this issue.
I am connecting to a AWS RDS MySQL 8 + version

> CREATE PROCEDURE myInsert()
BEGIN
DECLARE i INT DEFAULT 1

SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3

Thanks
Santosh

### DBeaver Version

Version 23.1.4.202308061552

### Operating System

Windows 11Pro

### Database and driver

Driver for MySQL 8 and later

### Steps to reproduce

1.Connect to MySQL 8 database
2.Open SQL editor
3. Copy paste below script in editor
CREATE TABLE `testbig_santosh` (
`A` bigint(11) primary key,
`B` bigint(11) DEFAULT NULL,
`C` timestamp(3) default current_timestamp(3),
`Hostip` varchar(30) default null,
`ProcStarttime` timestamp(3) default current_timestamp(3),
KEY `COL_A_B` (`A`,`B`) USING BTREE
);

delimiter ;;

CREATE PROCEDURE myInsert()
BEGIN
DECLARE i INT DEFAULT 1;
DECLARE j INT DEFAULT 5000;
DECLARE T timestamp(3) default current_timestamp(3);

select count(1)+1 into i from testbig_santosh;
if i=0 then 
SET i=1;
else
SET j=j+i;
end if;

WHILE (i<=j) DO
INSERT INTO testbig_santosh(`A`,`B`,`Hostip`,`ProcStarttime`) VALUES(i,i,(select @@hostname),T);
select sleep(0.5);
SET i=i+1;
commit;
END WHILE;
END;;

DELIMITER ;

drop procedure myInsert;

4.Run it using Execute SQL Script or Alt+X
5.It always fail with the error

**Comment by santoshgurao2001** [comment]
> CREATE PROCEDURE myInsert()
BEGIN
DECLARE i INT(5) DEFAULT 1

SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3

Integer display width is deprecated and will be removed in a future release.
Integer display width is deprecated and will be removed in a future release.

**Comment by E1izabeth** [comment]
It seems that `delimiter ;;` command doesn't work properly. Have you tried to use some other symbols as a delimiter? I tried to run your script with `delimiter $` command and replace `;;` to `$` at the end of the `CREATE PROCEDURE` statement and it works well for me.

**Comment by santoshgurao2001** [comment]
Thanks , it worked with $$.
