### ISSUE TITLE
Problem creating a Bd with Vb.net

### ISSUE THREAD

**Issue by Solilopi25** [dbeaver/dbeaver#20859]
### Description

Hi, I have a problem when I create a Bd from Vb.net, dbeaver does not show it in the list and I have to connect to it and when I try to delete it, it does not do it, it just removes it from the list, it does not delete it. Can you fix the problem? Thank you.

### DBeaver Version

Versión 23.1.4.202308061552

### Operating System

Windows 10 x64

### Database and driver

Postgres ODBC

**Comment by uslss** [comment]
Hi @Solilopi25 , unfortunately, the issue description isn't clear, so we cannot reproduce it. Could you provide steps to reproduce? Screenshots/videos also will be helpful.

**Comment by Solilopi25** [comment]
Hello again, here I leave part of the vb.net function with which I create the bd and two screenshots, one from Dbeaver and the other from PgAdmin, where you can see that with Dbeaver you can't see the new bd created, while with PgAdmin you can see it in the list of them.
Part of the code I use is: "Private connectionString As String = "Server=localhost;port=5432;UserId=postgres;Password=pssw;Database=postgres"
"Public Sub CrearNuevaBaseDeDatos(nombreBD As String)

    Try

        ' ESTABLECEMOS LA CONEXIÓN AL SERVIDOR

        Using connection As New NpgsqlConnection(connectionString)

            connection.Open()

            ' CREAMOS UN CRONÓMETRO Y LO INICIAMOS

            Dim cronometro As New Stopwatch()

            cronometro.Start()

            ' CREAMOS LA BD

            Dim createDatabaseSql As String = $"CREATE DATABASE {nombreBD}"

            Using createDatabaseCommand As New NpgsqlCommand(createDatabaseSql, connection)

                createDatabaseCommand.ExecuteNonQuery()

            End Using

            ' DETENEMOS EL CRONÓMETRO

            cronometro.Stop()

            ' CERRAMOS LA CONEXIÓN

            connection.Close()

            ' OBTENEMOS EL TIEMPO TRANSCURRIDO EN SEGUNDOS CON PRECISIÓN HASTA LAS CENTÉSIMAS.

            Dim tiempoTranscurrido As Double = cronometro.ElapsedMilliseconds / 1000.0

            MessageBox.Show($"NUEVA BD CREADA. TIEMPO EMPLEADO: {tiempoTranscurrido:0.00} SEGUNDOS.")

        End Using

    Catch ex As Exception

        MessageBox.Show("ERROR AL CREAR LA BD: " & ex.Message)

    End Try

End Sub" 
Screenshots of Dbeaver and PgAdmin are at the beginning of the text. You can see how the new Bd created does appear in PgAdmin but not in Dbeaver.

________________________________________
De: Dziyana ***@***.***>
Enviat: dijous, 10 d’agost de 2023 15:16
A: dbeaver/dbeaver
A/c: Solilopi25; Mention
Tema: Re: [dbeaver/dbeaver] Problem creating a Bd with Vb.net (Issue #20859)

Hi @Solilopi25<https://github.com/Solilopi25> , unfortunately, the issue description isn't clear, so we cannot reproduce it. Could you provide steps to reproduce? Screenshots/videos also will be helpful.

**Comment by ShadelessFox** [comment]
Hello @Solilopi25,

You can't attach images when replying by email. Please attach them on github directly: https://github.com/dbeaver/dbeaver/issues/20859

**Comment by ShadelessFox** [comment]
Have you tried reconnecting to your connection in DBeaver after it was created using that code snippet?

**Comment by Solilopi25** [comment]
Hello, it is not really necessary, the images only show that in pgAdmin you can see the database created and in dbeaver not.

**Comment by E1izabeth** [comment]
It is necessary to understand your case. Unfortunately, without your assistance we can't help you.

**Comment by Solilopi25** [comment]
Hi, I don’t know how to explain something that doesn’t need much more explanation. The problem is clear, when creating a database from vb. net, in my case, I can not see it in the list in Dbeaver while, in PgAdmin is seen from the first moment. There is nothing more to say, if you want to check it you only have to make a small program in Vb.net with the corresponding code for the creation of a database and you can check what I say. Greetings and apologies for the inconvenience.

Saludos, best regards, salutacions. Enviado desde mi iPhone. Send from my IPhone. Enviat des-del meu IPhone.

El 15 ago 2023, a las 13:21, Elizabeth ***@***.***> escribió:

﻿

It is necessary to understand your case. Unfortunately, without your assistance we can't help you.

**Comment by Solilopi25** [comment]
﻿Hi, I don’t know how to explain something that doesn’t need much more explanation. The problem is clear, when creating a database from vb. net, in my case, I can not see it in the list in Dbeaver while, in PgAdmin is seen from the first moment. There is nothing more to say, if you want to check it you only have to make a small program in Vb.net with the corresponding code for the creation of a database and you can check what I say. Greetings and apologies for the inconvenience.

Saludos, best regards, salutacions. Enviado desde mi iPhone. Send from my IPhone. Enviat des-del meu IPhone.

El 15 ago 2023, a las 13:21, Elizabeth ***@***.***> escribió:

﻿

It is necessary to understand your case. Unfortunately, without your assistance we can't help you.

**Comment by ShadelessFox** [comment]
> Have you tried reconnecting to your connection in DBeaver after it was created using that code snippet?

**Comment by Solilopi25** [comment]
Yes, of course. As I said in previous comments, in PgAdmin it looks smooth, even having both open at once, Dbeaver and PgAdmin.

Saludos, best regards, salutacions. Enviado desde mi iPhone. Send from my IPhone. Enviat des-del meu IPhone.

El 15 ago 2023, a las 13:51, ShadelessFox ***@***.***> escribió:

﻿

Have you tried reconnecting to your connection in DBeaver after it was created using that code snippet?

**Comment by ShadelessFox** [comment]
Please make sure you're not in the middle of a transaction when viewing databases in DBeaver.

You might also need to enable these options:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/fb78852e-3e65-404f-956f-990734dd23a8)

**Comment by Solilopi25** [comment]
Where can I find those settings? My version of DBeaver is from August 7, 2023.

Saludos, best regards, salutacions. Enviado desde mi iPhone. Send from my IPhone. Enviat des-del meu IPhone.

El 15 ago 2023, a las 14:57, ShadelessFox ***@***.***> escribió:

﻿

Please make sure you're not in the middle of a transaction when viewing databases in DBeaver.

You might also need to enable these options:

[image]<https://user-images.githubusercontent.com/35821147/260715083-fb78852e-3e65-404f-956f-990734dd23a8.png>

**Comment by ShadelessFox** [comment]
In the connection settings. Right-click on your connection -> Edit Connection

**Comment by Solilopi25** [comment]
Hello again, I try to do it but the result it’s the same.

Saludos, best regards, salutacions. Enviado desde mi iPhone. Send from my IPhone. Enviat des-del meu IPhone.

El 15 ago 2023, a las 15:37, ShadelessFox ***@***.***> escribió:

﻿

In the connection settings. Right-click on your connection -> Edit Connection

**Comment by Solilopi25** [comment]
﻿Hello again, I try to do it but the result it’s the same.

Saludos, best regards, salutacions. Enviado desde mi iPhone. Send from my IPhone. Enviat des-del meu IPhone.

El 15 ago 2023, a las 15:37, ShadelessFox ***@***.***> escribió:

﻿

In the connection settings. Right-click on your connection -> Edit Connection

**Comment by flambchap** [comment]
Unfortunately, I cannot reproduce the issue. Can you please provide footage showing your issue? Thank you.

**Comment by Solilopi25** [comment]
Hi, as mentioned in a previous message, I shared screenshots that highlighted a problem. The newly created database using a VB.net program did not appear in Dbeaber. However, it did show up in PgAdmin when listing the databases. It's strange. The database appears in PgAdmin but not in Dbeaver.


------ Mensaje original ------
De "Nikita Akilov" ***@***.******@***.***>>
Para "dbeaver/dbeaver" ***@***.******@***.***>>
Cc "Solilopi25" ***@***.******@***.***>>; "Mention" ***@***.******@***.***>>
Fecha 17/08/2023 15:20:31
Asunto Re: [dbeaver/dbeaver] Problem creating a Bd with Vb.net (Issue #20859)


Can you please provide footage showing your issue? Thank you.

**Comment by E1izabeth** [comment]
Unfortunately, we received none of your screenshots. You're replying on the notification email from github platform. Attachments don't come to the issue thread automatically from your reply.

**Comment by Solilopi25** [comment]
Hi, here are the two screenshots again, the one from PgAdmin and the one from Dbeaver.


------ Mensaje original ------
De "Elizabeth" ***@***.******@***.***>>
Para "dbeaver/dbeaver" ***@***.******@***.***>>
Cc "Solilopi25" ***@***.******@***.***>>; "Mention" ***@***.******@***.***>>
Fecha 17/08/2023 17:25:29
Asunto Re: [dbeaver/dbeaver] Problem creating a Bd with Vb.net (Issue #20859)


Unfortunately, we received none of your screenshots. You're replying on the notification email from github platform. Attachments don't come to the issue thread automatically from your reply.

**Comment by ShadelessFox** [comment]
Images attached when replying by email won't show on GitHub. Please, open this issue (https://github.com/dbeaver/dbeaver/issues/20859) in your browser and attach images there.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide the requested information.
