### ISSUE TITLE
Alternate row background coloring in Properties tab view for tables cutting off increased font sizes

### ISSUE THREAD

**Issue by ghstridr** [dbeaver/dbeaver#20851]
### Description

When looking at the Properties of a table (my case is with a mysql table), the alternating background color rows don't dynamically increase to accommodate an increased font size. The text is being cut off and is especially unreadable on the Columns sub-tab. Picture attached to demonstrate. 

### DBeaver Version

 23.1.4.202308061552

### Operating System

macOS Monterey 12.6.7

### Database and driver

Mysql database and driver supplied with dBeaver

### Steps to reproduce

1. Open Preferences for DBeaver
2. Go to User Interface -> Appearance -> Colors and Fonts
3. Expand DBeaver Fonts
4. Change all four listed font sizes to '18'.
5. Click Apply and Close
6. Connect to a database, expand the tables list
7. Double-click on a table
8. Click on Properties tab for that table after data from table is displayed.
![Screen Shot 2023-08-09 at 12 26 58 PM](https://github.com/dbeaver/dbeaver/assets/296345/df07f34c-960c-4354-9cec-cff4a0706ceb)

**Comment by arhayka** [comment]
I can't reproduce it on macOS Monterey 12.4

**Comment by LonwoLonwo** [comment]
Hello @ghstridr 

Does this incorrect sizing persist after DBeaver restart?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
