### ISSUE TITLE
sql assist not working properly with build-in json functions of mysql

### ISSUE THREAD

**Issue by Cirooo** [dbeaver/dbeaver#20855]
### Description

In SQL Editor, the SQL Assist can't help with completing build-in json functions of mysql. After typing 'js***' , only 'json_table' show up.
![dbeaver](https://github.com/dbeaver/dbeaver/assets/5875152/64a49c1f-5201-49e7-86c4-47e4c47b7525)

### DBeaver Version

Community Edition 23.1.4

### Operating System

Windows 10

### Database and driver

Mysql 5.7/8.0
mysql connector (java latest 8.0.29)

### Steps to reproduce

1. create sql editor panel
2. type ' select js'
3. sql assist gives a hint of 'json_table'
4. other build-in json functions are missing, such as 'json_extract', 'json_arrayagg', json_replace', etc...
not sure other mysql build-in functions, if you can make it more powerful.

**Comment by E1izabeth** [comment]
Have you turned this setting on?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/ef933ced-5500-4f1b-b5be-60d271aaa2c4)

**Comment by Cirooo** [comment]
> Have you turned this setting on? ![image](https://user-images.githubusercontent.com/28875055/259669593-ef933ced-5500-4f1b-b5be-60d271aaa2c4.png)

Sorry, I forgot to update the post. And I tried that option, and not working for hints. 
The more, I found another problem about data view from table. 
Steps:
1. double click on a table
2. click 'data' panel to see table records, it fetch 200 rows base on the settings.
3. scroll to bottom, it fetch more 200 rows. ( as I expected the sql would be limit 200, 400)
4. actually, it is limit 0,400
5. is there any option I didn't found?

**Comment by LonwoLonwo** [comment]
Hello @Cirooo 

I didn't find a functions list for MySQL in system schemas. Probably, we can add them manually.
So, thanks for the idea.

**Comment by LonwoLonwo** [comment]
About you second message:

you can try to disable this setting. By default, DBeaver refreshes old data (first 200 rows)

![2023-08-31 15_55_44-DBeaver Ultimate 23 2 0 - _localhost 7_ Script-127](https://github.com/dbeaver/dbeaver/assets/45152336/6a6e0e46-75a4-4236-b9b8-9ef484d5ce77)

**Comment by Cirooo** [comment]
> Hello @Cirooo
> 
> I didn't find a functions list for MySQL in system schemas. Probably, we can add them manually. So, thanks for the idea.

Thank you for your answer. And your next reply, it's really useful.

**Comment by LonwoLonwo** [comment]
Let's keep it open for now. I've added some extra JSON functions to the list, but our QA team has to check it first.

**Comment by LonwoLonwo** [comment]
More keywords for JSON functions were added for MySQL/MariaDB.
The enhancement will be available in DBeaver version 23.2.1 at 25.09.2023.
