### ISSUE TITLE
MariaDB - Adding JOIN to statement disables ability to edit

### ISSUE THREAD

**Issue by poltpolt** [dbeaver/dbeaver#20860]
### Description

I have a table with a foreign key.
WHen I do
SELECT mytable.* FROM mytable 

I cen edit the values in the grid view

when I do mytable.*, atributes.name FORM mytable JOIN atributes USING (atribute_id)

I cannot add/remove rows (buttons disabled)

I remember that in the past versions as soon as I had primary keys I could edit. If not there was a dialog requesting virtual primary keys.

### DBeaver Version

23.1.4

### Operating System

Linux Opensuse

### Database and driver

MariaDB (standard)

### Steps to reproduce

Run statement SELECTING A.* from  A with JOIN to another table via foreign key

see that adding /deleting row is disabled

Modifying does not work either , IMHO the where clause is malformed (should contain tablenames ?):
working example statement
SELECT x.*,tk.nazwa as n1 ,ak.nazwa as n2 FROM AtrTwr x JOIN TwrKarty tk ON (tk.twr_id=x.twr_id) JOIN AtrKarty ak on (ak.atr_id=x.atr_id)

I change x.disabled value in the grid and I get
SQL Error [1054] [42S22]: (conn:37) Unknown column 'nazwa' in 'where clause'
Query is: UPDATE AtrTwr
	SET disabled=?
	WHERE twr_id=? AND atr_id=? AND disabled=? AND nazwa=? AND nazwa=?, parameters [1,1,1,0,'','P']
  (conn:37) Unknown column 'nazwa' in 'where clause'

**Comment by E1izabeth** [comment]
Could you share these settings?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/3447183a-11c9-4bf7-a761-50fe2d259ac1)

**Comment by poltpolt** [comment]
I have never changed those
FYI my  upgrade strategy is that I follow all upgrades immediately.
![obraz](https://github.com/dbeaver/dbeaver/assets/9408405/e4fc78cd-2b71-4562-b178-84eabc17150c)

**Comment by E1izabeth** [comment]
Could you provide a table DDLs for your query or some other example including create table queries? We need a clear steps to reproduce.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by poltpolt** [comment]
sorry, forgot, here you are

```

CREATE TABLE `AtrKarty` (
  `atr_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `nazwa` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `kod` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `typ` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`atr_id`),
  KEY `AtrKarty_atr_id_IDX` (`atr_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `AtrTwr` (
  `twr_id` int(11) DEFAULT NULL,
  `atr_id` int(10) unsigned DEFAULT NULL,
  `disabled` tinyint(1) NOT NULL DEFAULT 0,
  UNIQUE KEY `AtrTwr_UN` (`atr_id`,`twr_id`),
  KEY `AtrTwr_FK_1` (`twr_id`),
  CONSTRAINT `AtrTwr_FK` FOREIGN KEY (`atr_id`) REFERENCES `AtrKarty` (`atr_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `AtrTwr_FK_1` FOREIGN KEY (`twr_id`) REFERENCES `TwrKarty` (`twr_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `TwrKarty` (
  `twr_id` int(11) NOT NULL AUTO_INCREMENT,
  `nazwa` varchar(500) DEFAULT NULL,
  `kod` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `opis` varchar(300) DEFAULT NULL,
  `nazwa3` varchar(45) DEFAULT NULL,
  `nazwa4` varchar(45) DEFAULT NULL,
  `handlowy` int(1) DEFAULT 0,
  `grupa` enum('towary','tworzywa','wyroby gotowe','produkcja - usługa','produkcja - produkt','produkcja - (dzierżawa)','odpady') DEFAULT 'towary',
  `stan_min` decimal(16,6) DEFAULT 0.000000,
  `stan_min_uzupelnienie` decimal(16,6) DEFAULT 0.000000,
  `global_knt_id_dostawcy` int(11) DEFAULT NULL,
  `knt_id_dostawcy` int(11) DEFAULT NULL,
  `jm_id` int(11) NOT NULL DEFAULT 1,
  `erp_id_1` int(10) unsigned DEFAULT NULL,
  `LastUpdate` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `tymczasowy` tinyint(4) NOT NULL DEFAULT 0,
  `aktywny` tinyint(4) NOT NULL DEFAULT 1,
  `lok_id` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`twr_id`),
  UNIQUE KEY `kod_UNIQUE` (`kod`),
  UNIQUE KEY `TwrKarty_un_erp` (`erp_id_1`),
  KEY `kodowy` (`kod`),
  KEY `TwrKarty_JMKarty_FK` (`jm_id`),
  KEY `TwrKarty_FK` (`knt_id_dostawcy`),
  KEY `TwrKarty_FK_1` (`lok_id`),
  CONSTRAINT `TwrKarty_FK` FOREIGN KEY (`knt_id_dostawcy`) REFERENCES `old_KntKarty` (`knt_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `TwrKarty_FK_1` FOREIGN KEY (`lok_id`) REFERENCES `Lokalizacje` (`lok_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `TwrKarty_JMKarty_FK` FOREIGN KEY (`jm_id`) REFERENCES `JMKarty` (`jm_id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```
