### ISSUE TITLE
SQL Error line number is relative to the query instead of the file

### ISSUE THREAD

**Issue by ParticleMon** [dbeaver/dbeaver#20866]
### Description

Errors are expected to reference the file line number, not the query line number.

If a query (select or with) does not start on line one of a file and the query contains an error, the line number in the error will be incorrect.

Other SQL errors in addition to the example are also affected.

I do not recall whether this emerged or existed in the first version of DBeaver I used but it has existed for several years (almost every release), at least on Snowflake.

### DBeaver Version

CE 23.1.4

### Operating System

Windows

### Database and driver

Server: Snowflake 7.27.1
Driver: Snowflake 3.14.0

### Steps to reproduce

1. Run this query on a line other than line 1 of a file: `select null from null`
2. This error is thrown, indicating the line number of the query: "syntax error line 2 at position 5 unexpected 'null'."
3. The error is expected to indicate the line number of the file.

**Comment by E1izabeth** [comment]
That response comes from the database, not from DBeaver itself. We could try to intercept these error messages and fix them, but is it worth it? You can use `Go to the error` button and look at the error decorator in the SQL Editor.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/756dde08-7593-4605-8358-22c3ce7adab3)

**Comment by ShadelessFox** [comment]
Hello @ParticleMon,

DBeaver sends just the active query, not the entire script. For example, you have the following script:
```sql
1 | select 1;
2 | 
3 | select a;
```
If you were to execute the second statement, DBeaver would ask the driver to execute the following script:
```sql
1 | select a;
```
So the driver doesn't know the "real" location of that query in the script.

The reported message comes from the driver. Unfortunately, we can't change it.

**Comment by ParticleMon** [comment]
> You can use `Go to the error` button and look at the error decorator in the SQL Editor.

@E1izabeth For CTEs, the "Go To The Error" button goes to line 1 of the CTE, not to the line of the error as expected.

**Comment by E1izabeth** [comment]
> @E1izabeth For CTEs, the "Go To The Error" button goes to line 1 of the CTE, not to the line of the error as expected.

This is what the driver returns.

**Comment by rccc** [comment]
Hello,

Everyone need to get the correct line number in case of error !

Is there a trick for a plpgsql procedure to get the right line number ?

**Comment by Sophhalk** [comment]
Would still love a fix on this issue if anyone has cracked it
