### ISSUE TITLE
Lock icon after SELECT

### ISSUE THREAD

**Issue by rodrigoguariento** [dbeaver/dbeaver#20861]
### Description

I'm using dbeaver for linux, and sometimes I'm facing and odd behavior when I use SELECT, see:

... when I let the cursor over the query and I execute, the lock icon appears:
![dbeaver-q1](https://github.com/dbeaver/dbeaver/assets/25516653/d680d2e6-56f5-4762-9dde-f18e3589a33a)

... when I select my entire query and I execute (for same query), the lock icon disappears:
![dbeaver-q2](https://github.com/dbeaver/dbeaver/assets/25516653/94ab87ee-06b8-4caa-8b42-ee748d0c9e4f)

Is there some hidden rule/explanation to the lock icon appears/disappears? This behavior doesn't always happen, it's intermittent, I haven't discovered a pattern.

Thank you since now.

### DBeaver Version

Community Edition 23.1.4.202308061552

### Operating System

Ubuntu 20.04.6 LTS

### Database and driver

"Driver for MySQL 8 and later" connected to MySQL "5.6.32-log" (_SELECT version();_)

### Steps to reproduce

1. execute a simple SELECT letting cursor over query
2. execute a simple SELECT selecting all query

**Comment by uslss** [comment]
Hi @rodrigoguariento , thanks for the report.
Can you use MySQL 5 driver instead of MySQL 8 and write back if it helps?

![image](https://github.com/dbeaver/dbeaver/assets/31996417/5f567a3c-d3fe-4c50-8543-91e64760bce1)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by rodrigoguariento** [comment]
Your suggestion solved my problem! Thanks.
