### ISSUE TITLE
the error display panel in the results panel isn't scrollable.

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#20869]
### Description

When dbeaver encounters an error running code in a SQL Editor script window, it _usually_ displays the error message in a pane on the left of the results tab.

Unfortunately, there is no way to scroll that text area and so it's impossible to see the entire error message.

This is how it looks at it's default size:
![dbeaver_standard_size_results_error_20230810_140504](https://github.com/dbeaver/dbeaver/assets/3697063/7dfd0d52-aa23-476e-b748-4b7c9e97300f)

and here's what it looks like if I make the results panel take up the entire screen, heightwise:
![dbeaver_full_screen_results_panel_error_20230810_140548](https://github.com/dbeaver/dbeaver/assets/3697063/67d0c323-04a1-403a-95fc-dd7295af2453)

As you can see, without some means to scroll, there's practically no way to see the entire error message.

Can the error message area be made scrollable?

Thanks.

### DBeaver Version

Community Edition 23.1.4

### Operating System

Windows 10

### Steps to reproduce

write some code that will throw a large detailed error
run that code
watch as it's impossible to read the entire error message.

**Comment by E1izabeth** [comment]
Thank you for sharing your use case.
