### ISSUE TITLE
Can't add foreign key constraint   with a set null on delete

### ISSUE THREAD

**Issue by ceyhunnabiyev** [dbeaver/dbeaver#2087]
I can't add foreign key constraint   with "a set null on delete",  I don't have not null constraint on referenced column. When I save this, it changes set null to no action on delete...

**Comment by serge-rider** [comment]
What database?

**Comment by ceyhunnabiyev** [comment]
Oracle

**Comment by tsluijter** [comment]
Maybe the constraint is added with a set null on delete, but dbeaver is showing no action on delete.

When I look in Oracle SQL Developer I see constraints with set null on delete, but when i look at the same constraint in dbeaver it is showing no action on delete. (which is still an issue)

**Comment by uslss** [comment]
can't reproduce on 6.0.2
