### ISSUE TITLE
update dbeaver  to Version 23.1.4.202308082323 or later... 

### ISSUE THREAD

**Issue by Dutchglory** [dbeaver/dbeaver#20873]
### Description
please update dbeaver  to Version 23.1.4.202308082323 (Early Access version)  (or latest EA version).
Stable version 23.1.4.202308061552  does not show databases within database navigator window. 

**Images:** (open in new tab/window) 
[dbeaver-flatpak-Version-23-1-4-202308061552.png](https://postimg.cc/r0hQB52W)
[dbeaver-EA-deb-Version-23-1-4-202308082323.png](https://postimg.cc/phVscq4R)
 
### DBeaver Version
community Version 23.1.4.202308061552

### Operating System
Ubuntu 23.10 (Mantic Minotaur)

### Database and driver
* MySQL Community Server Ver 8.0.34 for Linux 
* java version 17.0.7 (dbeaver installation)

**Comment by LonwoLonwo** [comment]
Hello @Dutchglory 

Updated.
Could you please take a look?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know.
