### ISSUE TITLE
Azure SQL Server MFA Authentication repeatedly opens multiple browser windows

### ISSUE THREAD

**Issue by Aileron79** [dbeaver/dbeaver#20887]
### Description

When authenticating with the Azure SQL database driver, it opens a browser tab/window every time a connection is opened or re-connected. In these tabs it only says

**Authentication complete. You can close the browser and return to the application.**

This is super annoying when working with multiple databases and database connections as any time a connection drops and reconnects, a tab will be opened.

I have around 40 SQL databases I work with, and in DBeaver I am normally connected to the majority of them. However, If there's hiccups in the connection (like Wifi connection fails for a moment, VPN disconnects, ...), all open database connections are reconnected automatically which is a good thing. However, for all database connections that are open, DBeaver opens a tab in my browser, which means suddenly I have 30+ browser tabs I have to close manually. This does not only happen when working in DBeaver, but also if I'm in another program like Visual Studio, Word or Excel. If DBeaver in the background decides that it needs to reconnect, my browser pops up and keeps on opening tabs. Sometimes there are a few seconds between the tabs are being opened, so I switch back to where I was working before and after a few seconds the browser pops up again until all sessions have been reconnected.

Sometimes the sessions do not reconnect automatically but when I send a new query in a script window and DBeaver realizes that the connection is dead. Love that feature, but again, a browser tab is opened. That might not be a big problem with one or two connections, but working with many connections you spend a lot of time switching between browser and dbeaver and closing tabs which is super annoying.

This is most likely intended behavior by the Azure SQL driver, however, it seriously disrupts my workflow as this happens multiple times per day. 

My suggestion would be to integrate a tiny browser in dBeaver (or in the driver) which handles re-authentication in the background. I am aware that sometimes I have to re-authenticate with my username and password, but this rarely happens as my credentials seem to be cached in the browser.

Please find a way I can use dbeaver without constantly being harassed by authentication attempts in my browser. I love dbeaver and want to continue using it

### DBeaver Version

Version 23.1.4.202308061552

### Operating System

Win 10

### Database and driver

Azure SQL / Azure SQL Server MFA Authentication

### Steps to reproduce

- Create multiple connections to Azure databases using the Azure SQL driver
- Connect to all of them in different script windows
- Disrupt the connection (turn off/on wifi, ...)
- DBeaver will attempt to reconnect and open multiple browser windows.
- MIght be that the browser window opens when a new query is sent from a browser window.

**Comment by dhorrall** [comment]
Pretty much same phenomenon as me, although, my connection re-attempts end up failing after numerous browser windows.  I normally get impatient and KILL it by disconnecting vpn.  When I re-connect VPN, I get one broswer pop and a successful db connection.  I haven't been able to pin-point the issue.  Seems to be a weird intersection of VPN timeout, database timeout and MFA credentials.  I will let it go with all of the popups next time, and take some screen shots.

**Comment by dhorrall** [comment]
After my VPN connection time out(?) over night?  I tried to access azure sql database then get 11? browser  tabs.  It might have been 10 that were newly generated.  I might have had 1 tab carrying over from yesterday.  Not sure

![image](https://github.com/dbeaver/dbeaver/assets/22561698/ce52caec-285b-4a99-a2ae-94a1679db982)

After, I see IP address error...so I think underlying cause is VPN related.  I have seen it happen where I am active and suddenly I start getting browser tabs opening..probably due to a connectivy hiccup..
![image](https://github.com/dbeaver/dbeaver/assets/22561698/6b66a5e6-ecb9-494f-966f-b51869646169)

**Comment by Aileron79** [comment]
Looks similar on my end, but it could easily be 30-40 tabs. (I actually wrote a plugin for Chrome that autocloses the tabs, but the browser still keeps on popping up and I'm still constantly interrupted with whatever I am working. 

The second error message you see means that your public IP address is not allowed to access the database. That's what you use the VPN for. Once the VPN fails, connection attempts to the database will be made with your public IP. Theoretically you can drill a hole in your firewall to allow access from your public IP, that's basically what the error message suggests. However, I'd rather stick to the VPN. That's basically the same configuration I use.

Are you using the Azure VPN client? That one is notoriously instable and I am facing very similar issues with it. Still, I believe dbeaver should handle reconnects silently in the background without popping up hundreds of browser windows.

**Comment by Aileron79** [comment]
Thank you for taking this problem seriously and implementing a fix so quickly. Unfortunately, the situation now worsened - there seem to be a few problems with that implementation:

I need to connect to a bunch of databases (like 20+), for all of them I authenticate using my Azure credentials. The problem now is, that I need to go through the whole authentication process (Enter username, password, launch authenticator app, enter authentication code, close browser window) for every single database I connect to. 

Sometimes I get caught in a loop: The swt browser pops up, I complete the authentication process, and once it's completed, it starts over again. And again. And again. Eventually I get this error message:
![image](https://github.com/dbeaver/dbeaver/assets/16278437/f0681091-29f0-425e-8f3e-2f7da5c4c047)
Note that I use the correct credentials, authentication works fine with an older version of DBeaver.

It looks as if the swt browser does not support cookies/caching of sessions.

Sadly, I need to install an older version of DBeaver now to actually be able to work with it. 

I would very much like to help sorting out this issue, happy to give a live demo if that helps.

**Comment by dhorrall** [comment]
After installing the latest update, after about 30 minutes (I assume connection timing out)  I get numerous SWT browser popups instead of new browser window popups.  I'll see if I can get a screen-capture gif as it is happening if I can remember.

**Comment by fabricioferreira** [comment]
Issue is also happening here, running on the latest version (23.2.1.202309250303).
The authentication window now opens on a tiny window inside dbeaver, but it kepps happening in a loop.

**Comment by fabricioferreira** [comment]
Now that the authentication opens on its little popup inside DBeaver, the cookies from my previous authentications are not used, which makes it ask for my password and 2FA every single time I need to connect to a database. This is very annoying when we have long passwords and have to respond to the 2FA challenge everytime on the phone. Is it possible to make the use of an external browser configurable?

**Comment by derik-roby** [comment]
I still have this issue in the new update

**Comment by derik-roby** [comment]
Please reopen this issue. I still get new tabs open every time I try to connect to AzureSQL DB with Azure Active Drectory - password authentication

**Comment by Destrolaric** [comment]
https://github.com/dbeaver/dbeaver/issues/21417 The resolution is now tracked in a different issue. The browser popup tabs are caused by the driver retrying to connect multiple times and, each time, requesting SSO authorization. Unfortunately, this is a third-party driver issue, and we are waiting for the resolution on the Microsoft side...

**Comment by ilrenzo** [comment]
@Destrolaric do you have the link to the msft ticket to fix this bug? I couldn't find it. And this still happening with Az SQL Server in 2024.
