### ISSUE TITLE
在分辨率高的屏幕上，工具栏图标非常小

### ISSUE THREAD

**Issue by zhaolirao** [dbeaver/dbeaver#20883]
就像图片上这样
![屏幕截图(2)_LI](https://github.com/dbeaver/dbeaver/assets/18703974/861e5bc2-15fb-470c-aa8f-db4a3799838f)

**Comment by ShadelessFox** [comment]
Hello @zhaolirao,

Have you tried changing the scaling factor for apps in Windows settings?

This is how it looks for me on a 4K monitor with 200% scaling:
![java_iH3a19qiXv](https://github.com/dbeaver/dbeaver/assets/35821147/ca008b29-34f0-4ac1-8111-fadea0c398eb)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
