### ISSUE TITLE
DBeaver Keep running Athena queries - not showing results

### ISSUE THREAD

**Issue by ELAVARASU16** [dbeaver/dbeaver#20892]
### Description

I am connecting to Athena using DBeaver client. It works fine for a month. Suddenly if I try to fetch any table data from Athena and keep running for long time until timeout (the size of the tables is very small) . I am able to see tables names and columns in the navigator but not able to see the data. I have tried latest version of DBeaver also.

![DBeaver_error](https://github.com/dbeaver/dbeaver/assets/19346784/3288df5c-fc2d-40f2-9583-ac3ac298dc72)

### DBeaver Version

dbeaver-ce-23.1.4

### Operating System

Windows 10

### Database and driver

jar: AthenaJDBC42-2.1.0.1000 
class : com.simba.athena.jdbc.Driver

**Comment by LonwoLonwo** [comment]
Hello @ELAVARASU16 

And if you try to change the fetch data size to a smaller one (10, as an example) - will it work? Will read the data?

Also, the default driver supported by DBeaver for Athena now - is AthenaJDBC42-2.0.34.1000.
Could you please try to use it instead? 
https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.34.1000/AthenaJDBC42-2.0.34.1000.jar

![2023-08-24 18_52_51-DBeaver 23 1 5 - Album](https://github.com/dbeaver/dbeaver/assets/45152336/34eeba86-138c-42a2-8d4b-157ffae75511)

**Comment by ELAVARASU16** [comment]
Hi @LonwoLonwo ,

Thanks for your response,

I have tried latest driver and I found some issue with my network to the AWS VPC, I have updated my JDBC URL template in driver settings to use my Athena endpoint , its now able to fetch data.

Thank you.
