### ISSUE TITLE
Table to Java model (JPA?)

### ISSUE THREAD

**Issue by GiantCrocodile** [dbeaver/dbeaver#2089]
I'm not sure how suitable this is regarding implementation and usefulness but maybe we could add an option to export table's structure as a plain Java model with corresponding fields.

**Comment by serge-rider** [comment]
This is similar to #1543

**Comment by p91paul** [comment]
To me, this is very different and much simpler. This feature would allow dbeaver to generate a java class from a table, which is relatively straightforward. That one would allow dbeaver to be queried through hql, which is much more complicated IMHO.

**Comment by claudivanmoreira** [comment]
Hello, is this feature in development? How can I contribute to this development?
