### ISSUE TITLE
Unable to change User Interface preferences or navigate away from those preferences

### ISSUE THREAD

**Issue by MerlinYoda** [dbeaver/dbeaver#20902]
### Description

When attempting to change the User Interface preferences under DBeaver's Database category, both the "Apply" and "Apply and Close" buttons are greyed-out. When attempting to navigate away from these preferences, an error message displays in a dialog box titled "Could Not Accept Changes" saying "The currently displayed page contains invalid values." even if the values remain unchanged from their defaults.

### DBeaver Version

DBeaver Community IDE 23.1.4.202308061552

### Operating System

Windows 10 Professional 22H2

### Database and driver

N/A

### Steps to reproduce

1. Open the Window menu.
2. Select Preferences.
3. Expand the Database category.
4. Click on the User Interface sub-category.
5. Click on any other category or sub-category.

### Additional context

Eclipse IDE for PHP Developers (includes Incubating components)
Version: 2023-06 (4.28.0)
Build id: 20230608-1333
OS: Windows 10, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.8+7
Java version: 17.0.8

**Comment by E1izabeth** [comment]
Thank you for bug report
