### ISSUE TITLE
[Trino] Add support for displaying view ddl

### ISSUE THREAD

**Issue by EinWesen** [dbeaver/dbeaver#20917]
**Is your feature request related to a problem? Please describe.**
Currently DBeaver does not support showing view ddl for Trino sources. It just displays the text "-- View definition not available".

**Describe the solution you'd like**
View ddl is displayed as usual.

**Additional context**
The view ddl could be read from the catalog's information_schema or as the result of the "show create view" -  command.

I already had a look at it and would be willing to implement that myself :)

**Comment by E1izabeth** [comment]
Thank you for feature request. Will be glad for a new contributions.
