### ISSUE TITLE
MYSQL transfer ORACLE，BIGINT TO UNSIGNED BINARY INTEGER，oracle  ORA-00907: 缺失右括号

### ISSUE THREAD

**Issue by xuyewei** [dbeaver/dbeaver#20920]
### Description

my oracle version oracle19c
org.jkiss.dbeaver.model.exec.DBCException: Can't create or update target table:
CREATE TABLE TEST.ACT_DMN_DECISION (
	ID_ VARCHAR2(255) NULL,
	NAME_ VARCHAR2(255) NULL,
	VERSION_ INTEGER NULL,
	KEY_ VARCHAR2(255) NULL,
	CATEGORY_ VARCHAR2(255) NULL,
	DEPLOYMENT_ID_ VARCHAR2(255) NULL,
	TENANT_ID_ VARCHAR2(255) NULL,
	RESOURCE_NAME_ UNSIGNED BINARY INTEGER NULL,
	DESCRIPTION_ VARCHAR2(255) NULL,
	DECISION_TYPE_ VARCHAR2(255) NULL
);

Because there are many bigint fields, can i set the default dataType in the software？Not every field is set once

### DBeaver Version

Community 23.1.4.202308061552

**Comment by hrimthrusa** [comment]
Hello. What seems to be a problem? The query you provided doesn't run? What error code does it show?

**Comment by xuyewei** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/30031565/052fa5b2-2751-4dfa-be8e-15705da14940)

the sql was generate by mysql transfer to oracle
and oracle cant handle the words "UNSIGNED BINARY INTEGER"

**Comment by LonwoLonwo** [comment]
Ok, thanks for the answer.

We need to find a better replacement for the BIGINT type for Oracle.

For now, you can change this type manually:

![2023-09-14 12_24_38-Configure metadata structure](https://github.com/dbeaver/dbeaver/assets/45152336/777670d6-15f3-41e8-8e03-77945f1ad949)

**Comment by xuyewei** [comment]
thanks for your answer,I prefer to set it up once , not every field is set once

**Comment by LonwoLonwo** [comment]
I will keep this ticket open for now. And will remove the SIGNED BINARY INTEGER data type from the list of Oracle data types.
