### ISSUE TITLE
support user profiles

### ISSUE THREAD

**Issue by lev112** [dbeaver/dbeaver#2092]
when there are many connections that share the same user/password
it would be convenient to create a single profile for that user, and use it across many connections.

if the password of the profile changes, all connections that use that profile should be updated accordingly.

**Comment by serge-rider** [comment]
This makes sense.
But I need to think about UI for this feature.

**Comment by lev112** [comment]
any update on this?
is there a plan to do this feature?

**Comment by serge-rider** [comment]
We will add user profiles before 6.2 release.

**Comment by serge-rider** [comment]
Will be added right after #8128

And perhaps in EE only.

**Comment by serge-rider** [comment]
Done.
User profiles can be assigned/managed from connection authentication selector -> Profile.

Also project settings now have global profiles management (DBeaver Settings->Authentication profiles).

**Comment by p91paul** [comment]
Do you confirm this feature is for EE only? Just to know what was of that "perhaps" above :)

**Comment by uslss** [comment]
Authentication profiles:
authentication types names are similar:
![image](https://user-images.githubusercontent.com/31996417/81666623-f0671680-944a-11ea-9e87-ca36546ddb47.png)
Authentication profile name is checked in network profile. If network profile with name Test exists, Authentication profile with the same name couldn't be created
![image](https://user-images.githubusercontent.com/31996417/81666828-358b4880-944b-11ea-814f-494eb68429a9.png)
Password is provided, but error that it is not provided appears when trying to create connection
![image](https://user-images.githubusercontent.com/31996417/81667808-6f108380-944c-11ea-8c8c-f9ab7ea054b5.png)
at the same time I can connect to maria db with incorrect credentials without any errors

**Comment by uslss** [comment]
verified

**Comment by Nisgrak** [comment]
@uslss Will be integrated https://github.com/dbeaver/dbeaver/issues/7647?

**Comment by Nisgrak** [comment]
An option to disable SSH connection with some profiles would be lovely ❤️
