### ISSUE TITLE
Unable to create connection to mariadb

### ISSUE THREAD

**Issue by hubzo** [dbeaver/dbeaver#20926]
### Description

I'm unable to open a connection to mariadb. The database is running in docker container (mariadb:latest). I verified that:
1. container is up and running, inside the container I can see my database
2. database is accessible over port 3306 from host system

My host system is Windows 10, I'm using Docker Desktop with WSL2 integration. 

Tried creating connection to this database with DBeaver community edition and DBeaver Eclipse plugin. 
expected behaivour: either a "Access denied for user 'user'@'localhost' (using password: YES)" or successful connection.

However, I get the following error in both (Eclipse plugin and standalone software):
```
Unexpected driver error occurred while connecting to the database
  loader constraint violation: loader org.jkiss.dbeaver.registry.driver.DriverClassLoader @1b6f7dc7 wants to load class com.sun.jna.Pointer. A different class with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @6a39f8ba. (com.sun.jna.Pointer is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6a39f8ba, parent loader 'platform')
  loader constraint violation: loader org.jkiss.dbeaver.registry.driver.DriverClassLoader @1b6f7dc7 wants to load class com.sun.jna.Pointer. A different class with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @6a39f8ba. (com.sun.jna.Pointer is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6a39f8ba, parent loader 'platform')
```

However, a spring-boot application running on my local machine seems to be able to access the database just fine, it does however produce a "Access denied for user 'user'@'localhost' (using password: YES)", which is just some minor misconfiguration and still proves the database was successfully reached.

Tried 3.1.3 version of mariadb-java-client as well, same error. Originally DBeaver Community edition had some other version of mariadb-java-client, which did not work as well and produced some error about "bad authentication plugin" or somethign similar. Reinstallation of DBeaver and different versions of the driver did not help.

Would appreciate any suggestions. I'd be happy to connect to MySQL or PostgreSQL or whatever open source SQL database, there is no hard requirement for a specific database, except it should be open source SQL.

### DBeaver Version

Community Edition Version 23.1.4.202308061552

### Operating System

Windows 10

### Database and driver

mariadb:latest in docker container

Database driver:
```
<!-- https://mvnrepository.com/artifact/org.mariadb.jdbc/mariadb-java-client -->
<dependency>
    <groupId>org.mariadb.jdbc</groupId>
    <artifactId>mariadb-java-client</artifactId>
    <version>3.1.4</version>
</dependency>
```

### Steps to reproduce

1. create connection for mariadb database
2. test connection

### Additional context

Windows 10 Enterprise
Docker Desktop with WSL2 integration

**Comment by ShadelessFox** [comment]
Hello @hubzo,

Unfortunately, we can't reproduce your issue.

Maybe you have JNA library files specified in the driver's dependencies?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
