### ISSUE TITLE
Error for Google Big Query driver for 23.1.5

### ISSUE THREAD

**Issue by progsurfer** [dbeaver/dbeaver#20935]
### Description

The new version of DB is not working with the GBQ driver.

Set back to previos version is everthing ok.

![grafik](https://github.com/dbeaver/dbeaver/assets/24592280/07251261-23b7-4391-a58b-2d01b22143c6)

### DBeaver Version

23.1.5

### Operating System

Windows 11 Enterprise Version 21H2 Build  22000.2176 Windows Feature Experience Pack 1000.22001.1000.0

### Database and driver

SimbaJDBCDriverforGoogleBigQuery42_1.3.3.1004

Conig for driver: jdbc:bigquery://{host}:{port};ProjectId={database};OAuthType=0;OAuthServiceAcctEmail={user};OAuthPvtKeyPath={server};

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @progsurfer

**Comment by LonwoLonwo** [comment]
Also, as a workaround for now.

1. Go to Connection settings.
2. Click on the Driver Settings.
3. Click on the Restore to Defaults
4. Click Ok
5. Try to connect again

![2023-08-23 13_11_33-Window](https://github.com/dbeaver/dbeaver/assets/45152336/743892ad-32cc-4ed2-85c9-ae0498c6fbfe)

**Comment by LonwoLonwo** [comment]
Not working in PRO.
