### ISSUE TITLE
ERD Notation

### ISSUE THREAD

**Issue by hairullana** [dbeaver/dbeaver#20932]
I find great satisfaction in utilizing DBeaver for generating comprehensive documentation, such as Entity-Relationship Diagrams (ERDs). Yet, there are instances when I require the inclusion of notations that signify relational connections between tables. I envision a remarkable enhancement to DBeaver's functionality—an inclusion of a feature that empowers users to seamlessly append symbols or notations denoting relational associations within the ERD.
The implementation of such a feature would significantly benefit not only myself but also a multitude of other users who rely on DBeaver as their primary database management tool.

As an interim solution, I've resorted to manually embedding textual notes that depict the relationships, although a dedicated feature for adding symbols or notations would streamline the process and elevate the overall user experience.
![image](https://github.com/dbeaver/dbeaver/assets/56705867/39c634c2-7c7e-4d61-a511-dac028087352)

Reference:
![image](https://github.com/dbeaver/dbeaver/assets/56705867/a1dc1181-8b25-4fdf-a092-911722b23276)

**Comment by Destrolaric** [comment]
Greetings, Same theme as https://github.com/dbeaver/dbeaver/issues/1017.

**Comment by Destrolaric** [comment]
@hairullana We have discussed this, and we will see if this can be implemented. I am going to close this ticket as a duplicate of #1017 for now.
