### ISSUE TITLE
Decimal point is added to Int representation in JSON in Value panel

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#20946]
### Description

Then:
![image](https://github.com/dbeaver/dbeaver/assets/43252954/110be6f5-21e1-4384-9496-ef727290db61)
Now:
![image](https://github.com/dbeaver/dbeaver/assets/43252954/6e4b0ece-d9ac-4de8-ab89-69c876cf8612)

Not depends on the database

### DBeaver Version

23.1.5

### Operating System

win10

**Comment by serge-rider** [comment]
Fixed in devel

**Comment by DariaMarkaryan** [comment]
Verified
