### ISSUE TITLE
Don't apply case formatting for comments

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#20944]
### Description

The previously reported GitHub ticket has been closed but the delivered patch doesn't resolve the original issue:
https://github.com/dbeaver/dbeaver/issues/20600#issuecomment-1686110748

See the video:
https://youtu.be/IPjIFPnW7G8

### DBeaver Version

CE 23.1.5

### Operating System

Fedora

### Database and driver

Postgresql 14

### Steps to reproduce

See video

**Comment by E1izabeth** [comment]
The SQL Assistance doesn't appear in the comment anymore. The issue with auto formatting text in comment was not fixed.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by dr-1** [comment]
I believe this is a duplicate of #5994.

**Comment by E1izabeth** [comment]
Yes, indeed.
@dr-1 thank you!
Closing as a duplicate of #5994
