### ISSUE TITLE
MySQL: Routines with definer don't appear in Database objects tree

### ISSUE THREAD

**Issue by Natoshka** [dbeaver/dbeaver#20950]
### Description

I can't see objects with definer (MySQL) in the database navigator? Is it a bag? Or I have to configure DBeaver somehow?
For example, IntelliJ IDEA shows all the routines with the same JDBC library.

See attached screenshot
![image](https://github.com/dbeaver/dbeaver/assets/37998594/c0bfcc3c-806f-4105-ae74-7833c5184a06)

### DBeaver Version

Community Edition Version 23.1.4.202308061552

### Operating System

Microsoft Windows 10 Enterprise

### Database and driver

1. Database MySQL 5.7.12
2. Driver https://mvnrepository.com/artifact/software.aws.rds/aws-mysql-jdbc/1.1.9

### Steps to reproduce

Connect to database and expand in database navigator the objects tree, then expand stored procedures
Expected result: I see all the routines
Actual result: I don't see routines which contains definer

**Comment by LonwoLonwo** [comment]
Hello @Natoshka 

Please provide a query example of a procedure for tests.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
