### ISSUE TITLE
Error loading database task associated with deleted database

### ISSUE THREAD

**Issue by VitaliyCP** [dbeaver/dbeaver#20952]
### Description

DBeaver is unable to load database task and all task configuration is lost 
when database used in this task was deleted:

```
Error loading wizard settings

Reason:
Error loading objects configuration
```
This happens after deleting a database that was used with some database task.
All task configuration is lost if this error occurs (MAJOR ISSUE).
This is extremely inconvenient and annoying.

The work around that I found is to go to `tasks.json` file and fix database name to some existing database - then task will be loaded correctly.

Task should be loaded even if database is missing (maybe with some warning), but it should load all other configuration options in the task and should allow to select new database.

 

### DBeaver Version

Version 23.1.5.202308201919

### Operating System

Windows

### Database and driver

MariaDB

### Steps to reproduce

- Create MySQL database `db1`
- Create MySQL dump task and select `db1` as target database, also modify other options for task
- Save task
- Delete `db1` database
- Try to open saved MySQL dump task
- (ISSUE) In opened task dialog all configuration is reset to default values

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by VitaliyCP** [comment]
This is not fully fixed, some settings are now loaded after an error, but at least one setting is lost.
I use MySQL dump task, and after getting an error about missing database - the value of "Extra command args" parameter is lost.
