### ISSUE TITLE
Two occurrences of the whitespace dots have different meanings

### ISSUE THREAD

**Issue by mrclmh** [dbeaver/dbeaver#20957]
### Description

In the editor, one dot is one whitespace, three whitespaces are three dots, and so on.
In the grid result set, one whitespace dot seems to have a different meaning.
New dots only appear with an odd number of whitespaces. With an even number, only a little more space is added to the right of the dot.

I like the editor variant better because it is easier to count spaces, but in general, I would like it better if both editor and grid result would be consistent and would display the whitespace dots the same way.

### DBeaver Version

CE Version 23.1.5.202308201919

### Operating System

macOS 13.5

### Steps to reproduce

1. Enable showing whitespaces in editor and grid result.
2. Compare whitespace dots in editor and result

```sql
select ' abc'
union
select '  abc'
union
select '   abc'
union
select '    abc'
union
select '     abc'
union
select '      abc'
order by 1 desc;
```
  

<img width="180" alt="dots_editor" src="https://github.com/dbeaver/dbeaver/assets/2975481/7b8fddb2-4266-4e52-b72f-944c86bcd81e">
<img width="170" alt="dots_grid" src="https://github.com/dbeaver/dbeaver/assets/2975481/9750ef94-a472-42c6-8666-c342a182b06f">

**Comment by ShadelessFox** [comment]
Hello @marcelmore,

Thanks for the bug report.
