### ISSUE TITLE
"Data Comparison" requires column mapping but leaves none for keys-only linking tables

### ISSUE THREAD

**Issue by WValenti** [dbeaver/dbeaver#20961]
### Description

"Data Comparison" requires that there be non-PK columns available for column mapping in order to proceed, but some of my large linking tables consist only of FK columns that comprise the PK, so a comparison cannot be performed.

### DBeaver Version

Pro 22.1

### Operating System

macOS 13.4.1

**Comment by ShadelessFox** [comment]
Hello @WValenti,

Thanks for the feature request.

This use case was never considered, therefore, was not implemented before.

**Comment by WValenti** [comment]
Awesome! Thank you very much for a well-maintained tool that truly is critical for our work!
