### ISSUE TITLE
brew upgrade --cask dbeaver-community not working

### ISSUE THREAD

**Issue by GitHuFish** [dbeaver/dbeaver#20963]
### Description

```
brew upgrade --cask dbeaver-community

==> Upgrading 1 outdated package:
dbeaver-community 23.1.2 -> 23.1.5
==> Upgrading dbeaver-community
==> Purging files for version 23.1.5 of Cask dbeaver-community
Error: dbeaver-community: Download failed on Cask 'dbeaver-community' with message: Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.6\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.8\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://dbeaver.io/files/23.1.5/dbeaver-ce-23.1.5-macos-aarch64.dmg` exited with 35. Here's the output:
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to download.dbeaver.com:443
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.18.0 (Ubuntu)
Date: Wed, 23 Aug 2023 05:55:44 GMT
Content-Type: text/html
Content-Length: 154
Connection: keep-alive
Location: https://download.dbeaver.com/community/23.1.5/dbeaver-ce-23.1.5-macos-aarch64.dmg
```

### DBeaver Version

Community Edition 23.1.2

### Operating System

macOS Monterey 12.6.8

### Database and driver

no database, about upgrade only.

### Steps to reproduce

Just run the following command in macos iterm2:
brew upgrade --cask dbeaver-community

**Comment by E1izabeth** [comment]
@GitHuFish, thank you for bug report.
Could you check if the issue is still reproducible? We might had some issues with the website.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by GitHuFish** [comment]
The issue is still actual...What information do you need to know?

**Comment by GitHuFish** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/14013012/82d3a4d3-5217-4ab8-aaf0-81f13a9525fd)

**Comment by E1izabeth** [comment]
Thank you for update

**Comment by Destrolaric** [comment]
Could you see if Safari recognizes the certificate at `download.dbeaver.com` as valid?

**Comment by E1izabeth** [comment]
>Could you see if Safari recognizes the certificate at download.dbeaver.com as valid?

@GitHuFish any updates?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by GitHuFish** [comment]
> > Could you see if Safari recognizes the certificate at download.dbeaver.com as valid?
> 
> @GitHuFish any updates?

This may be related to GFW, I have updated using vpn，thx~
