### ISSUE TITLE
How to fix DBeaver after importing broken plug-in

### ISSUE THREAD

**Issue by humanusdeus** [dbeaver/dbeaver#20960]
### Description

It all started when I wanted to change the color scheme in the UI since the one that comes after installation is unreadable. So I went into github and imported a new scheme as a .epf file without reading it first and it immediately crashes after launch leaving a .log file in home, the code I imported contains an illegal Windows path and im running linux so it naturally doesnt works. No matters what I do it keeps throwing the same error and crashing, I uninstalled several times, deleted the flatpak directory, the DBeaverData directory, I grep'd my entire system in search for that single line that throws the error but I cant find it anywhere

### DBeaver Version

23.1.5

### Operating System

Fedora Workstation

**Comment by E1izabeth** [comment]
Could you share the steps to broke DBeaver: a link to the file you imported and the way you added this scheme to DBeaver?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
