### ISSUE TITLE
Statistics pane can not be deactivated for multiple queries with results

### ISSUE THREAD

**Issue by btanner2** [dbeaver/dbeaver#20976]
### Description

**dbeaver 23.1.1**

![dbeaver_23 1 1](https://github.com/dbeaver/dbeaver/assets/36444364/65edd869-efbf-44ee-84ce-b7f7ffc3d5dc)

- I have “multiple queries with results”
- I have turned off the option "Show statistics for multiple queries with results"
- I see the statistic pane anyway AND it gets the focus after finishing the queries

This behavior was introduced with 23.1.1 and is still present in 23.1.5. This is really anonying and forces me to stay with the previous version 23.1.0.

This is clearly a bug isn’t it?

Thanks
Brian

### DBeaver Version

23.1.5

### Operating System

Windows 10

**Comment by ShadelessFox** [comment]
Hello @btanner2,

The statistics tab will be shown anyway if at least one query is a non-select statement.

In your case, you have a `CREATE TABLE` statement that doesn't produce any results.

**Comment by btanner2** [comment]
Hi,

Thanks for clarification. The two most important questions are why is that and how could it be changed? I do not need this tab, it prevents me from doing my daily work. What I do need instead are multiple queries with at least one of them as a non-select statement.

What do you think could be a proper solution for this?

- Make it possible to hide the statistics tab always?

Or

- At least make it possible to set the focus to the last result table and NOT to the statistics tab?

I am looking forward to any possible solutions for this and I bet I am not alone with this.

Thank you in advance for your help.

Brian

**Comment by ShadelessFox** [comment]
As of now, it's not possible to completely hide that tab.

Adding an option to hide the statistics tab permanently would be a good solution.

I will convert this issue into a feature request.

**Comment by E1izabeth** [comment]
We may need to pay attention to those cases from the comments too #20416

**Comment by btanner2** [comment]
Hi again,

To be honest I am a bit uncomfortable with the status „feature request“ of this issue. In fact, there was a change from 23.1.0 to 23.1.1 where a new feature was introduced:

“Show statistics for multiple queries with results”

This new feature has a massive side effect on the daily work with 23.1.1 and higher. For certain reasons, the institution I work for uses multiple queries with at least one non-select statement all the time. This is something we cannot change. With 23.1.1 and higher we simply cannot use Dbeaver anymore, since every of our SQL produces the new Statistics tab and set the focus on it.

There is no possibility to hide the Statistics tab. There is no possibility to set the focus not to the Statistics tab. There is absolutely nothing we can do about this except staying forever with Version 31.1.0. 

I really appreciative your work on this great tool, but this new introduced feature broke our workflow. I’m asking very politely about rethinking this new feature and make it possible for the user to keep their current workflow. Classifying this issue here as a new feature request, means to me convincing people to give their thumb up on this to get a solution. This seams to be not fair at all.

I’m extremely open for any solution of this issue, even if it comes to using some secret undocumented entries in the dbeaver config files.

We are big fans of dbeaver and we would like to stay with it.

all the best
Brian

**Comment by sdeluca** [comment]
I am running version 23.1 on Windows, against a PostgreSQL database and I have the "show statistics for multiple queries with results" unchecked too. This works as expected most of the time - if my script ends with a comment however the statistics tab will show.

**Comment by vdeltsov** [comment]
I want to add two comments that are really bad. It would be great to remove them.
1. If you execute a script using Alt+X, and an error occurs in it, then an error message appears first, and then a tab with results is displayed, where the result of the previous query is displayed. Every time you have to hide this tab. Here it is clearly required not to display the tab. Why show the previous query result?
2. If you execute a long script, for example, you call a procedure where you submit a large json (10 MB, 400,000 lines), then the request itself is executed in a few seconds, but then it takes a few minutes to output this request to the statistics panel. And it is impossible to win. I believe that it is necessary to limit the length of the output query to several lines. Why copy 400,000 rows to statistics?

**Comment by paul-eeoc** [comment]
Here is the thing:
I am running only a single query like this:
SELECT * FROM shared_code;

And I get no statistics tab.

However, if I have a comment after it like this:
SELECT * FROM shared_code;
--order by 1

Then I get the statistics tab. This is a bug.

**Comment by E1izabeth** [comment]
Resolved in scope of #20416

**Comment by misi01** [comment]
A few additional comments on this. One scenario where I'm running 4 simple selects on 4 different tables.
Based on the (older) layout above, my preferences are set to 

_Show Statistics tab: Only when no data_     (why isn't there a **Never** option ?????)

If I change the first select and include a where clause so I KNOW it won't return anything, I see no stats tab.
However, if I move that where clause to the LAST select, I get the stats tab.

Someone hasn't done there testing all that well, have they? :-)
Running Free version, 25.1.4

**Comment by ShadelessFox** [comment]
@misi01 please create a new ticket. We don't reopen old ones.

**Comment by misi01** [comment]
My apologies. I thought/assumed this was a sort of forum. I'll try and open one. Should I refer back to this one (20976 ???)?
