### ISSUE TITLE
Always generate up-to-date DDL when selecting Generate SQL->DDL

### ISSUE THREAD

**Issue by pkExec** [dbeaver/dbeaver#20984]
**Is your feature request related to a problem? Please describe.**
I use right-click->Generate SQL->DDL to get the definition of a view or materialized view, in order to do some changes.
The problem is that this definition is cached from the last time I connected to the database. If in the meantime the view has been updated, I get the old-code instead of the new one.

**Describe the solution you'd like**
When I press Generate SQL->DDL, DBeaver should always fetch the most up-to-date DDL, not the cached one.

**Describe alternatives you've considered**
I know that I can first refresh the views, but it's really aggravating to have to do those additional steps every time I need to do a change (and in my current workflow, that's very frequent).

**Comment by LonwoLonwo** [comment]
Hello @pkExec 

What database are you using?

**Comment by pkExec** [comment]
@LonwoLonwo
- Database: PostgreSQL 12.13 (Ubuntu 12.13-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
- Dbeaver:  Community Edition, Version 23.1.5.202308201919

**Comment by arhayka** [comment]
We want to add a button Refresh in generate SQL dialogue.

**Comment by dr-1** [comment]
The refresh button will be helpful, but it leaves a risk of forgetting to refresh and copying an outdated definition. I have made it a habit to always refresh the definition (in my workflow by hitting F5 while viewing the Definition page in the properties of a view), but I and people in my group still regularly forget that step and end up working with an outdated definition statement accidentally. It would be nice to have an option to bypass the cache altogether and have DBeaver always fetch the up-to-date definition, as OP described. Should a new issue be opened for this?

**Comment by E1izabeth** [comment]
Yes, could you create a new issue then?
