### ISSUE TITLE
Github Infinite login loop and not authorized to connect repository

### ISSUE THREAD

**Issue by priyank04** [dbeaver/dbeaver#20992]
### Description

I am testing integration of Github with Dbeaver for my SQL project. I am facing an issue with github continuously.
1. Created a private repo on github
2. Tried to clone on Dbeaver - **IT FAILED**
3. Then I cloned repo using terminal 
4. Later imported local git folder to Dbeaver
5. Added a new db connection
6. Added a test script
7. When pushing the code, it asks for git credentials
![image](https://github.com/dbeaver/dbeaver/assets/41550014/5dca4586-40d5-4860-9c68-1eb6c77de3cd)
8. When entering the correct credentials it again asks me for credentials

### DBeaver Version

DBeaver Enterprise 21.3.0

### Operating System

Windows 11 Pro

**Comment by ShadelessFox** [comment]
Hello @priyank04,

You're probably using your account credentials while also having 2-FA enabled. You need to generate an access token and use it as the password.

Please see:
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens

**Comment by priyank04** [comment]
That was it. Didn't realize on the MFA for the github account. Thanks for the prompt response.

**Comment by ghost** [comment]
I'm having the same issue, but even after creating a token, I still get an error when I try to connect.
