### ISSUE TITLE
Empty SQL script editor after saving content of console

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#20994]
### Description

If I start to write SQL query using a console, and then decide I need to store the query as a script, I expect that SAVE AS function will save the content of the console into a file, starting to behave as an opened script since then.

What is happening is, that SAVE AS operation being issued from the console creates the file but the content disappears from the editor. Fortunately the code is indeed stored in the file.

BTW after saving the file, subsequent open command opens completely different location.

Both issues shown on the video
https://youtu.be/t-Yf2N3ET98

### DBeaver Version

CE 23.1.5

### Operating System

Fedora 38

### Database and driver

Postgresql 14

### Steps to reproduce

See video

**Comment by pnewport-CHS** [comment]
I'm experiencing the same issue on Mac running CE23.1.5 , Ventura 13.5 OS, MS SQL Server 9.2.0.jre8 -- exact same steps to reproduce as in your video.

**Comment by E1izabeth** [comment]
Thank you for bug report.
