### ISSUE TITLE
Export failing - creates empty file

### ISSUE THREAD

**Issue by datajunkiejanet** [dbeaver/dbeaver#20998]
### Description

NOTE - this is a new problem. This did not happen until 2 updates ago, but now happens with every export, always.
Whenever I try to export a result set to a file, it will create a file with that name, but it contains zero bytes. I was able to get around this for a while by using the Compression check box. It would then create a zip folder, and the file I need was in there. However, I just upgraded today, and now the Compression workaround doesn't work either. 

### DBeaver Version

Community Edition 23.1.4.202308061552

### Operating System

Windows11 Version 22H2

### Database and driver

1 Database is Oracle 12C
2 Driver is... See screenshot:
![image](https://github.com/dbeaver/dbeaver/assets/46468272/f89b1738-abd3-4d75-b7af-c6450cc2eda8)

### Steps to reproduce

Steps to repeat
While connected to a database,

1 Open SQL Script
2 Write simple query - SELECT * FROM MyTable. Note that it returns 95 records (for example - the point is that the row count is irrelevant).
3 Click on the Export data button on the bottom of the Results tab (or select all results by clicking on the top left grid (the gray space above all the row numbers and to the left of the column names), right click and choose Export.
4 Export target:  CSV
5 Extraction settings: Extract type Single query, no other checkboxes checked.
6 Format settings: Default
7 Output: Choose a directory to save the file to (it doesn't matter where - One Drive, locally on C: drive, still fails)
7A. Fill in the name pattern
7B. Choose Compress if desired (which worked 1 update ago, but stopped with the current update) or uncheck Compress - happens either way
7C For the results section of the tab, I have tried checking or unchecking any of these options - none of them make a difference.
8. For the next step, I have tried both clicking to Proceed from the Output screen, or from the Confirm screen. It doesn't make a difference either.
9. Click Proceed
10. Go to the file location specified, note that there is a file with the desired name, but it has 0 bytes.

### Additional context

The most important thing I can think to note is that it was working early last week. Then I got an update notice - installed the update. Exports maybe worked for a little while, or maybe stopped. I just know that on August 22nd, it started producing these 0 byte files. I did get it to export with a compressed zip folder. But I updated again today, and now nothing will export no matter what options I choose.

**Comment by E1izabeth** [comment]
Thank you for bug report.
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by datajunkiejanet** [comment]
Hi,

I have attached the log. Unfortunately, since the program didn't actually
throw an error - just produced a 0 byte export file instead of the full
data, I'm not sure you could see that in the log. In any case, if I can
provide anything else, please let me know.

Thanks,

Janet

**Comment by E1izabeth** [comment]
Unfortunately, files attached with the reply to the notification email can't be automatically uploaded to the github platform. Could you open the issue (https://github.com/dbeaver/dbeaver/issues/20998) and attach it with a comment?

**Comment by datajunkiejanet** [comment]
Sorry - here is the debug log file: 
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/12454449/dbeaver-debug.log)

I'm having trouble uploading the regular .log file. It says the file is hidden;however, the file itself does not have the "hidden" box checked in the properties. I'll try again

**Comment by datajunkiejanet** [comment]
It accepted the log as a compressed file. See if this works:
[log.zip](https://github.com/dbeaver/dbeaver/files/12454486/log.zip)

**Comment by E1izabeth** [comment]
Thank you. It's fine now.

**Comment by hrimthrusa** [comment]
Hi. Please send us a screenshot of the Output step during the Data Transfer configuration process.

**Comment by datajunkiejanet** [comment]
Here are the screenshots of each step of the Export process that produces an excel file with 0 bytes

![Dbeaver Step1 Export Screenshot 2023-09-05 155544](https://github.com/dbeaver/dbeaver/assets/46468272/fd60e237-963f-4fb6-8b15-1167d4c33132)
![Dbeaver Step2 Export Screenshot 2023-09-05 155556](https://github.com/dbeaver/dbeaver/assets/46468272/fd83c501-bb9d-4b5c-8a7c-e0709cd4bca1)
![Dbeaver Step3 Export Screenshot 2023-09-05 155608](https://github.com/dbeaver/dbeaver/assets/46468272/97c775e3-3ef4-4c73-b97d-660e882aac85)
![Dbeaver Step4 Export Screenshot 2023-09-05 155624](https://github.com/dbeaver/dbeaver/assets/46468272/b80165c0-e549-4bf9-bcee-72d816fae5a5)
![Dbeaver Step5 Export Screenshot 2023-09-05 155634](https://github.com/dbeaver/dbeaver/assets/46468272/4b19e15c-7322-4e0e-a6db-a873d346cfdb)

**Comment by datajunkiejanet** [comment]
I also discovered that the same thing happens if I create a Task that exports data. It will say the task was a success, but it only creates a file with 0 bytes and no file extension.
![image](https://github.com/dbeaver/dbeaver/assets/46468272/0052986d-4fd1-44a4-8f6b-43729ee2102c)

**Comment by datajunkiejanet** [comment]
Has there been any movement on this? I upgraded to 23.2, but it's still happening there too. Not being able to export to Excel is a tremendous problem! Can you help or is this something out of your support scope? I just need to know if there's any point in continuing to wait, or if I should try to find an alternate product now.  Thank you!

**Comment by serjiokov** [comment]
Hi, I able to reproduce issue with same 0 bytes in result exported file. As a workaround please use "File Name Pattern" as plain text or template: ${table}.

**Comment by iraidaa** [comment]
263512

**Comment by serjiokov** [comment]
The output file name resolving procedure is fixed inderectly (commit b9630046b7d803e1dd32b60a53af3f14868be982).
