### ISSUE TITLE
Saves a changed row even though an old row is displayed per select

### ISSUE THREAD

**Issue by KevinKrueger** [dbeaver/dbeaver#20991]
### Description

I have displayed a table via SELECT.
My colleague has changed a row in this table.
I wanted to change this row and no message came up that a new state exists.
The data that was displayed to me was old after the change of my colleague.

The line was overwritten cold!

### DBeaver Version

23.1.5 - Community Edition 

### Operating System

Windows 10

### Database and driver

SQL-Server only

### Steps to reproduce

1. I have displayed a table via SELECT.
2. My colleague has changed a row in this table.
3. I wanted to change this row and no message came up that a new state exists.

### Additional context

-

**Comment by LonwoLonwo** [comment]
Hello @KevinKrueger 

If you know that other people can change the data in a table, you can enable auto-refresh as an option.

![2023-08-24 18_05_32-DBeaver Ultimate 23 1 5 - _140 236 88 151 2_ Script-135](https://github.com/dbeaver/dbeaver/assets/45152336/ff14b902-7563-4ed5-9e2b-51e1d7896b47)

In other cases, DBeaver will not constantly read data and will not keep both old and new data. It would be a rather costly situation.

**Comment by KevinKrueger** [comment]
Thank you for your quick reply.

1. law of the case, there would be one million records, then no 
    normal thinking person will activate an automatic update.
2. what if a record is changed exactly in the second?
3. overwriting an older state with a new one without checking it before is 
    deadly.
4. especially if there is a need for processing timestamps in a software, it is not possible to simply 
    the old state beaten through.

Suggestion:
What's wrong with implementing a caution dialog as a precautionary measure if it is determined during saving that the record displayed is older than the one that is actually in the database?

**Comment by LonwoLonwo** [comment]
> What's wrong with implementing a caution dialog as a precautionary measure if it is determined during saving that the record displayed is older than the one that is actually in the database?

How can DBeaver understand that this row is older? Not all databases have the row number implementation. So, it needs to be checked by the key status, maybe. But if we do not have keys in a table? Or complex keys?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
