### ISSUE TITLE
Error when translating language to Portuguese

### ISSUE THREAD

**Issue by GeekBoyBiel** [dbeaver/dbeaver#21002]
### Description

Upon navigating to the following path: Preferences > User Interface > Regional Settings > Language, and selecting the 'Português Brasil' option, the system fails to retain the chosen language after restarting. Despite attempting solutions mentioned by other users in a related topic, the issue remains unresolved.

### DBeaver Version

23.1.5

### Operating System

windowns x64

### Database and driver

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

### Steps to reproduce

1 Open DBeaver.
2 Navigate to Preferences.
3 Select "User Interface" from the options.
4 Choose "Regional Settings."
5 Click on "Language."
6 Select "Português Brasil."
7 Apply the changes and close DBeaver.
8 Reopen DBeaver.

### Additional context

I have observed that the client is unable to locate the 'pt_BR' language code. My current DBeaver version is 23.1.5.

Please let me know if any further information or testing is required to address this bug effectively.

Thank you for you
![Screenshot_10](https://github.com/dbeaver/dbeaver/assets/41956831/972560af-57dc-4cdb-9cfe-eadcf54916e3)
![Screenshot_1](https://github.com/dbeaver/dbeaver/assets/41956831/b0fb45df-fc7c-43c3-9bb2-ca8e6d13f2d1)
![Screenshot_10](https://github.com/dbeaver/dbeaver/assets/41956831/c4f82209-4c09-4a9f-90f4-d0436c2f10b7)
r attention to this matter.

**Comment by LonwoLonwo** [comment]
Hello @GeekBoyBiel 

As I can see on your screen - language changing helped. So, It is just incorrect item in the Language combobox in Preferences?

**Comment by LonwoLonwo** [comment]
And yes, I can reproduce this bug. And can not reproduce this issue for other languages.

**Comment by JacksonBelizario** [comment]
In my case, I want to continue using the interface in English, but after the update I can't change the language, it seems that the language that is set on my PC is staying.

Even trying to switch to other translations seems to have no effect.

**Comment by JacksonBelizario** [comment]
The current solution for me is stay at version [23.0.2](https://github.com/dbeaver/dbeaver/releases/tag/23.0.2)

**Comment by LonwoLonwo** [comment]
> 6 Select "Português Brasil."

>  I want to continue using the interface in English, but after the update I can't change the language, 

Sorry, I'm confused.
What locale do you have, and what language do you want to see in DBeaver?

**Comment by JacksonBelizario** [comment]
> > 6 Select "Português Brasil."
> 
> > I want to continue using the interface in English, but after the update I can't change the language,
> 
> Sorry, I'm confused. What locale do you have, and what language do you want to see in DBeaver?

Currently my PC is in Portuguese, but I'm used to using dbeaver in English. But after the update, dbeaver automatically changed the language to Portuguese, then I tried to change the language back to English, but I can't, it seems like it's stuck on Portuguese, no matter what language I try to change.

**Comment by HaiFish** [comment]
> > > 6 Select "Português Brasil."
> > 
> > 
> > > I want to continue using the interface in English, but after the update I can't change the language,
> > 
> > 
> > Sorry, I'm confused. What locale do you have, and what language do you want to see in DBeaver?
> 
> Currently my PC is in Portuguese, but I'm used to using dbeaver in English. But after the update, dbeaver automatically changed the language to Portuguese, then I tried to change the language back to English, but I can't, it seems like it's stuck on Portuguese, no matter what language I try to change.

The solution i found to this was create a desktop shortcut and append -nl en, so the app start in english

**Comment by LonwoLonwo** [comment]
Hello @GeekBoyBiel 

We fixed language recognition.
Could you please check our Early Access version? https://dbeaver.io/files/ea/

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual for you - feel free to reopen it
