### ISSUE TITLE
Can't update values in result set from query with JOIN statement if more than one table is updated

### ISSUE THREAD

**Issue by yagudin10** [dbeaver/dbeaver#21010]
### Description

Can't update values in result set from query with JOIN statement if more than one table is updated

### DBeaver Version

Ultimate Edition 22.1.4

### Database and driver

PostgreSQL db1

### Steps to reproduce

1. Execute query with JOIN statement, f.e.:
```
select
    *
from
    test_vqb.basket_a as ba
inner join test_vqb.basket_b as bb on
    bb.fruit_b = ba.fruit_a;
```
2. Try to update values in columns from several tables and save it.

ER: The row is updated.
AR: Error 
![image](https://github.com/dbeaver/dbeaver/assets/59531286/7fb4692c-98cf-4559-9979-843f8171f6af)

Script
![image](https://github.com/dbeaver/dbeaver/assets/59531286/4fb9ec22-b267-43c5-9358-0e0a1d8e7e84)

**Comment by LonwoLonwo** [comment]
Let's do the original one: https://github.com/dbeaver/dbeaver/issues/16755
