### ISSUE TITLE
Connection to Google Cloud SQL (PostgreSQL) not working

### ISSUE THREAD

**Issue by timc13** [dbeaver/dbeaver#2103]
I've tried adding the Cloud SQL JDBC Socket Factory socket library 
and changing the driver settings URL Template to match the instructions here 
https://cloud.google.com/appengine/docs/flexible/java/using-cloud-sql-postgres#setting_connection_strings_and_adding_a_library_1

Per the instructions, the host and port are not required, but it seems to always try to connect to the host and port no matter what URL Template I use.

**Comment by tati-kru** [comment]
hi @timc13 
Is this issue is still reproducible?
