### ISSUE TITLE
Failed to initialize Manjaro - Flathub

### ISSUE THREAD

**Issue by sheilarnold** [dbeaver/dbeaver#21048]
### Description

Since the last update of the application on Manjaro, when it is necessary to start/use the application, it displays the loading screen. Shortly after, it also shows the initial application screen, where the registered connections are displayed. However, a few seconds later, the application is terminated. I have already restarted the computer, reinstalled DBeaver several times, and the issue persists.

### DBeaver Version

DBeaver Community 23.1.5

### Operating System

Manjaro

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by sheilarnold** [comment]
[.metadata.zip](https://github.com/dbeaver/dbeaver/files/12475784/default.metadata.zip)

**Comment by hrimthrusa** [comment]
Hi. Could you please send us the java fatal log files? Here is a how-to: https://github.com/dbeaver/dbeaver/wiki/Log-files#java-fatal-logs

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
