### ISSUE TITLE
Display errors in the result tab

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#21053]
### Description

When there is a bug in a query, it's now difficult to find an error in the result tab: it is hidden behind the query view. Users cannot find it. See details: https://github.com/dbeaver/dbeaver/issues/21013

<img width="940" alt="Screenshot 2023-08-30 at 17 31 27" src="https://github.com/dbeaver/dbeaver/assets/12581569/82e64901-bf0a-4638-a5ee-a42fb8927ed1">

We need to display the view with an error instead of it.

<img width="928" alt="Screenshot 2023-08-30 at 17 31 44" src="https://github.com/dbeaver/dbeaver/assets/12581569/1875b94a-52e7-4f13-bc0d-e886dc219260">

### DBeaver Version

23.1.5

### Steps to reproduce

1. Execute any query with a bug
2. See the result

**Comment by E1izabeth** [comment]
It becomes hidden if you press this arrow.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/2d3bfc02-461e-4443-a32b-a373beba0ae0)

Currently we preserve the state, we decided that the state of this view should reset to the initial state like on my picture.
