### ISSUE TITLE
Ability resize toolbar with buttons

### ISSUE THREAD

**Issue by anazzani** [dbeaver/dbeaver#21060]
Would it be possible to append table AND fields comments to the `CREATE TABLE` DDL output?

I think it would make sense, especially considering the presence of the commented `Drop table` command.

Thanks.

Alessandro

**Comment by anazzani** [comment]
Also indexes would be handy: in other words, I'd like to be able to use the whole table DDL to recreate it EXACTLY identical.

**Comment by LonwoLonwo** [comment]
Hello @anazzani 

What database do you use?

Could you please provide the expected query?

**Comment by anazzani** [comment]
Hi @LonwoLonwo and apologies for the missing details in my question.

I'm using DBeaver Community edition with Postgres v12+.

I was thinking of something like the following:
```
CREATE TABLE public.mytbl (
	customer_id int4 NOT NULL DEFAULT 0,
	user_id int4 NOT NULL DEFAULT 0,
	year int2 NOT NULL,
	month int2 NOT NULL,
	...
	CONSTRAINT mytbl_pk PRIMARY KEY (customer_id, user_id, year, month),
	CONSTRAINT mytbl_fk1 FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id),
	CONSTRAINT mytbl_fk2 FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);

-- NEW OUTPUT
COMMENT ON COLUMN public.mytbl.customer_id IS '...';
COMMENT ON TABLE public.mytbl IS '...';
CREATE INDEX mytbl_idx1 ON public.mytbl (year,month);
...
```
Indexes implicitly created (like the PK) shouldn't be listed, of course.

**Comment by LonwoLonwo** [comment]
![2023-09-07 12_17_58-Window](https://github.com/dbeaver/dbeaver/assets/45152336/013d69ce-faf5-43da-baaf-d81bffc679af)

But we have the comments part for table DDL for PostgreSQL.

Maybe the "Show comments" button is not enabled in your table editor?

**Comment by anazzani** [comment]
Oh my God, you are right!

I have a large monitor (iMac Retina 27") and DBEaver usually maximized: those buttons are almost unreadable to my old eyes. :(

Same goes for the buttons below the Data tab: maybe there's an option somewhere to enlarge those elements? If not, consider this a feature request. :)

Thanks for you help.

**Comment by LonwoLonwo** [comment]
You can generate DDL like this:

Click on a Table in the Navigator tree -> Generate SQL -> DDL

![2023-09-07 12_43_36-Window](https://github.com/dbeaver/dbeaver/assets/45152336/534b440d-9731-4666-8fdd-9e383ba21f1d)

Buttons are not hidden in this dialog.

**Comment by anazzani** [comment]
@LonwoLonwo ok, thanks for the follow-up.

Button visibility is a more general issue though.

I've found this old thread that precisely describe the problem: https://github.com/dbeaver/dbeaver/issues/1391

Is there any setting I can tweak (in a config file or in DBeaver preferences) to mitigate it?

**Comment by LonwoLonwo** [comment]
You can increase the main font or find something similar in Preferences -> User Interface -> Appearance -> Colors and Fonts.

**Comment by anazzani** [comment]
Mmmhh... I might be missing something, but I don't see how increasing the font could make the toolbars buttons more visible.

Not to mention that if I change the font size, this will be applied also to other UI elements, not only the toolbars, right?

I tried the suggestion proposed in the other thread: adding `-Dswt.autoScale=600` to my dbeaver.ini seems to make things better, I just hope it doesn't break some other parts of the app and that it will be retained on the next app update.

EDIT: on MacOS the file is `/Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini`

**Comment by anazzani** [comment]
Sorry, I take it back. I must have imagined it: after checking more carefully it appears that autoscale doesn't change anything in the toolbars.

**Comment by LonwoLonwo** [comment]
Closed as a duplicate https://github.com/dbeaver/dbeaver/issues/20704

As a workaround (not for all OS) https://github.com/dbeaver/dbeaver/issues/20704#issuecomment-1700730969
