### ISSUE TITLE
Support IAM authentication with Google Cloud SQL connector

### ISSUE THREAD

**Issue by EricStG** [dbeaver/dbeaver#21071]
**Is your feature request related to a problem? Please describe.**
Our organization uses IAM authentication for Cloud SQL, which requires us to generate a token every time we connect

**Describe the solution you'd like**
I'd like for DBeaver to be able to generate the token automatically, using the gcloud credentials already configured on the system

**Describe alternatives you've considered**
We can generate the token via the cli with `gcloud sql generate-login-token` every time and copy it in DBeaver

**Additional context**
[Google doc](https://cloud.google.com/sql/docs/postgres/authentication)

**Comment by flambchap** [comment]
Thank you for the idea. Unfortunately, we do not support GCP IAM in the Community edition. Can you please see if our GCP IAM authentication provider solves the issue for you? https://dbeaver.com/download/enterprise/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
