### ISSUE TITLE
Warn of file replacement while exporting project

### ISSUE THREAD

**Issue by MontejoJorge** [dbeaver/dbeaver#21088]
**Describe the solution you'd like**
When you are exporting a project file, and the name matches an existing file in the selected folder, warn the user that the previous file will be lost.

**Describe alternatives you've considered**

- A pop-up window with the warning message
- Warning message below the output file name

**Comment by E1izabeth** [comment]
Please provide more details of how to reproduce your issue. Any screenshots or video would be very useful.

**Comment by MontejoJorge** [comment]
Export DBeaver project:
![image](https://github.com/dbeaver/dbeaver/assets/56157795/8eb3e549-ec3d-4ea9-8d34-5ad077823827)
Then set a name:
![image](https://github.com/dbeaver/dbeaver/assets/56157795/92f3cd56-ef9c-4e9f-abca-97da6be1a4b3)

If u export again other project or the same project with the same name file, you will overwrite the DBP back up file without a warning.

**Comment by Destrolaric** [comment]
@MontejoJorge Thank you for the idea.

**Comment by MontejoJorge** [comment]
I would like to try to get with this, how do you think I should warn the user? pop up or warning message?

**Comment by E1izabeth** [comment]
We already have pop-ups warns about overriding in some other wizards (for example, in data transfer). Let's make a pop-up here too to be consistent.
