### ISSUE TITLE
Excel Data Import

### ISSUE THREAD

**Issue by jdani015** [dbeaver/dbeaver#21093]
### Description

Trying to import data from Excel into a table.  Only file format option available is CSV.  

### DBeaver Version

CE 23.1.5

### Operating System

Windows 10

### Database and driver

Snowflake JDBC driver

### Steps to reproduce

1. From Database Navigator right-click on target table name
2. select "Import Data"
3. Data Transfer pop-up window not showing Excel file format as an option.  Only .CSV is displayed

### Additional context

DBeaver Office Support is installed.

**Comment by E1izabeth** [comment]
Importing from xlsx files is a feature available in PRO version only.
You can try trial version https://dbeaver.com/download/
