### ISSUE TITLE
The execute SQL button

### ISSUE THREAD

**Issue by yxl6716** [dbeaver/dbeaver#21101]
The execute SQL button is too small in a 2K or higher resolution screen. There is no button for adjusting the size. I hope to add an option for resizing.

**Comment by E1izabeth** [comment]
Have you tried the solution provided here https://github.com/dbeaver/dbeaver/issues/20704#issuecomment-1700730969 ?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
