### ISSUE TITLE
Dictionary associated through foreign key is shown empty for new record

### ISSUE THREAD

**Issue by sparrowek** [dbeaver/dbeaver#21114]
### Description

When I select the value in a column that has a foreign key to another table it shows the list of values from the dictionary in the "Value" panel. Recently I have noticed that this panel is empty for new records created with the "+" button. 
When I type some random value in the column, then click another column and again click the dictionary column the "Value" panel is reloaded and shows the list of entries correctly.

### DBeaver Version

Community 23.2.0.202309031556

### Operating System

Windows 11

### Database and driver

Microsoft JDBC Driver for SQL Server

### Steps to reproduce

1. Add new (empty) record in some table
2. Click column which has the FK to some other table.
3. Check the contents of the "Value" panel (is empty but should be filled with the record from related dictionary table)

**Comment by E1izabeth** [comment]
Thank you for bug report.
