### ISSUE TITLE
"Automatically end long idle transactions" can make you loose work without notice

### ISSUE THREAD

**Issue by MGORO** [dbeaver/dbeaver#21123]
I recently updated DBeaver from 22.x to 23.1.5. When doing so "Automatically end long idle transactions" got checked by default for prod connection types due to changes introduced in https://github.com/dbeaver/dbeaver/releases/tag/23.1.1 when merging https://github.com/dbeaver/dbeaver/pull/19520 . Without knowing about that change, I ran a PostgreSQL script against a prod DB with auto-commit disabled. The statements ran were alter table ones to remove OIDs from hundreds of tables, with some taking seconds to run, and others many minutes. Thing is I left the script running, returned a couple of hours after, commited the changes and thought everything was complete. Unfortunately it was not the case as some of the statements were not commited due to "Automatically end long idle transactions" and I got no notice of that. Checking the logs or paying attention to the exact number that appeared to be commited would have allow me to detect this at the moment but maybe having some clear indication/message to users when "Automatically end long idle transactions" kicks in would be helpful.

**Comment by LonwoLonwo** [comment]
Hello @MGORO 

Thanks for the report. 

Probably, we can add something like a status toolbar with info about the next operation, which will be aborted as an IDLE transaction.
