### ISSUE TITLE
Data Grid background color resets to white after using NVDA/JAWs

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#21125]
### Description

Data Grid background color resets to white after using NVDA/JAWs.
Issue is reproducible in case:
- Screen reader was disabled;
- Screen reader was deleted after use 
- Screen reader was launched as portable application and disabled after.

Issue isn't reproducible for newly created local user on the same machine.

Data Grid becomes colorized after refresh again.

### DBeaver Version

23.2.0

### Operating System

win10

### Steps to reproduce

https://github.com/dbeaver/dbeaver/assets/31996417/99f9fcf5-5d1f-4ac0-8cb1-e5ed098c163b

**Comment by LonwoLonwo** [comment]
For me, JAWs work well with odd/even rows. We need to check it.

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/blob/41150073139170525dbd665167675dd3ae2c3153/plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/spreadsheet/SpreadsheetPresentation.java#L2495

remove `!spreadsheet.isAccessibilityEnabled()` and check JAWs on odd/even rows
