### ISSUE TITLE
oracle: unable to connect with user  myproxyusername[myschemaname]

### ISSUE THREAD

**Issue by brasio** [dbeaver/dbeaver#21145]
### Description

As already mentioned by other users, Dbeaver does not accept, in Oracle connections, username such as

myproxyusername[myschemaname]

These kinds of users are called oracle proxy users.

Thanks

### DBeaver Version

Community 23.2.0

### Operating System

Windows 10

### Database and driver

Oracle default thin driver

### Steps to reproduce

Create an oracle connection with an oracle proxy user

**Comment by MashaKorax** [comment]
Hello @brasio! Im trying to reproduce your issue. I successfully created a  proxy user in Oracle using DDL and established a connection.

Create some test users.
```
-- Connect to a privileged user.
conn sys/SysPassword1@//localhost:1521/pdb1 as sysdba

-- Create SCHEMA_OWNER.
create user schema_owner identified by SecretPassword1;
grant create session to schema_owner;

-- Create proxy user.
create user my_user_1 identified by MyPassword1;
grant create session to my_user_1;
```
**Then I established a connection under the proxy user.** 

![dbeaver_rfWRlDYZXW](https://github.com/dbeaver/dbeaver/assets/84867187/a78a4033-29c7-4865-999e-73f24f46864b)

**And than Ive checked current user in oracle (it was this proxy user)**

![dbeaver_x9sVDSwCRU](https://github.com/dbeaver/dbeaver/assets/84867187/46217c7f-67d3-4930-822f-7ca309cbf312)

Note: Oracle Database 12c Enterprise Edition Release 12.1.0.2.0

Maybe it's kind of related with  your Oracle version? As far as I know, this feature is available from Oracle version 9

**Comment by brasio** [comment]
Thanks MashaKorax. I have updated drivers, now it works. May be I made a wrong installation.
