### ISSUE TITLE
Single quota (') Will cause massive rename

### ISSUE THREAD

**Issue by budsz** [dbeaver/dbeaver#21147]
### Description

I've multi row like this:

```
SINGER              TITLE
Easton Corbin	    Lovin You Is Fun
Easton Corbin       All Over the Road
Easton Corbin       Roll With It
```

I edited `Lovin You Is Fun` to `Lovin' You Is Fun` (Added single quota), and hit `Save` button, here is abnormal result:

```
SINGER              TITLE
Easton Corbin	    Lovin' You Is Fun
Easton Corbin       Lovin' You Is Fun
Easton Corbin       Lovin' You Is Fun
```

Thanks

### DBeaver Version

Community Version 23.2.0.202309041200

### Operating System

Debian 5.10.0-23-amd64

### Database and driver

mysql57-server-5.7.42

**Comment by Destrolaric** [comment]
Hi, could you provide the table DDL? It's quite possible the table didn't contain any unique case that led to this behavior.

**Comment by ShadelessFox** [comment]
Hello @budsz,

Your table doesn't have a unique key associated with it.

Please go to the "Virtual" tab in your table's properties and edit the "VIRTUAL_PK" key to include both the "SINGER" and the "TITLE" columns, as they define a unique key only when used together.

**Comment by budsz** [comment]
> Hello @budsz,
> 
> Your table doesn't have a unique key associated with it.
> 
> Please go to the "Virtual" tab in your table's properties and edit the "VIRTUAL_PK" key to include both the "SINGER" and the "TITLE" columns, as they define a unique key only when used together.

Thanks for reply,

I already have "VIRTUAL_PK" but only for SINGER. Anyway, should I use it for all columns to edit?

**Comment by ShadelessFox** [comment]
In that case, yes. The "SINGER" column is not unique on its own (because it has duplicated values), but when combined with the "TITLE" column, it produces a unique key.

I would suggest creating a new integer column with the "auto increment" modifier and a primary key out of it.

Refer to the docs for examples: https://dev.mysql.com/doc/refman/8.0/en/example-auto-incremen.t.html.

Please let me know if the problem is solved.

**Comment by budsz** [comment]
> In that case, yes. The "SINGER" column is not unique on its own (because it has duplicated values), but when combined with the "TITLE" column, it produces a unique key.
> 
> I would suggest creating a new integer column with the "auto increment" modifier and a primary key out of it.
> 
> Refer to the docs for examples: https://dev.mysql.com/doc/refman/8.0/en/example-auto-incremen.t.html.
> 
> Please let me know if the problem is solved.

Look like the problem has been fixed with VIRTUAL_PK in all columns. Actually, I've already a KEY in this table (`  `IDMUSIC` int(15) NOT NULL AUTO_INCREMENT,`), I don't understand why DBeaver still complains about it. Thanks

**Comment by budsz** [comment]
> In that case, yes. The "SINGER" column is not unique on its own (because it has duplicated values), but when combined with the "TITLE" column, it produces a unique key.
> 
> I would suggest creating a new integer column with the "auto increment" modifier and a primary key out of it.
> 
> Refer to the docs for examples: https://dev.mysql.com/doc/refman/8.0/en/example-auto-incremen.t.html.
> 
> Please let me know if the problem is solved.

**Comment by budsz** [comment]
Look like the problem has been fixed with VIRTUAL_PK in all columns. Actually, I've already a KEY in this table ( `IDMUSIC int(15) NOT NULL AUTO_INCREMENT,`), I don't understand why DBeaver still complains about it. Thanks
