### ISSUE TITLE
Error exporting data from Teradata to Hive

### ISSUE THREAD

**Issue by palonsopinto** [dbeaver/dbeaver#2114]
Hi all,

I am trying to use DBeaver to export a table from Teradata to Hive, and I get the following error:

![image](https://user-images.githubusercontent.com/23720538/29974123-cfd0de02-8f29-11e7-8199-901f8e1255ca.png)

Am I doing something wrong, or is what I am attempting to do just not possible to be done in this way?

**Comment by serge-rider** [comment]
Probably generated DDL for target schema contains some errors. You can see DDL by pressing appropriate button on columns mappings wizard page.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. Perhaps, this problem was solved. The ticket will be closed. However, if you think that it is actual just let us know.
