### ISSUE TITLE
When using Data Transfer to import a file, doublequotes in "Tables Mapping" are accepted... then ignored.

### ISSUE THREAD

**Issue by shakeshuck** [dbeaver/dbeaver#21151]
### Description

I tried to import a CSV file into Postgres through the Data Transfer dialog. My column headings are mixed case, and all are doublequoted in the CSV file.
Under 'Tables mapping', in the 'Source' column, some of the headings appeared in doublequotes, but most didn't. I noticed that editing the name in the 'Target' field, by putting doublequotes around the name, the name retained its mixed case. After editing some 240 column names (yes, this is a whinge!), I clicked through to 'Proceed' only to find that my mixed case headings had returned to lowercase, causing the TABLE CREATE to fail due to duplicate column names.

### DBeaver Version

Community Edition 23.2.0

### Operating System

OpenSUSE Tumbleweed

### Database and driver

Database: PostgreSQL 15.4
Driver: JDBC 42.5.2

### Steps to reproduce

See description!

**Comment by E1izabeth** [comment]
Thank you for bug report. I reproduced the issue.

https://github.com/dbeaver/dbeaver/assets/28875055/430ce3f2-d512-45d4-8ca1-88c9b3a3026b
