### ISSUE TITLE
Can't open it

### ISSUE THREAD

**Issue by cysBlank** [dbeaver/dbeaver#21159]
version: dbeaver-ce-23.2.0-win32.win32.x86_64.zip
![image](https://github.com/dbeaver/dbeaver/assets/104050277/4471058f-98a0-4b42-bec0-29b85a74fd45)

**Comment by ShadelessFox** [comment]
Hello @cysBlank,

What OS are you running on?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide more details.
