### ISSUE TITLE
DBeaver 23.15 to enable TLS 1.0

### ISSUE THREAD

**Issue by w0lfcat** [dbeaver/dbeaver#21168]
### Description

Error Message:

The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]".

I've been trying to find the setting for TLS, did not have any luck so far. If you know how to change this please let me know.

*** Note: I know TLS 1.0 is not secure, but this is just my personal project where changing the setting on the server is not an option

### DBeaver Version

23.15

### Operating System

Kali Linux

### Database and driver

MS SQL Server/SQL Server

### Steps to reproduce

I was trying to access "HTB Mantis" MS SQL Server "https://app.hackthebox.com/machines/Mantis", however the server is using old TLS 1.0 configuration.

Please take note that this is not an issue as the server was purposely built this way for learning purposes.

### Additional context

I'm new to DBeaver and just installed it on Kali based on recommendation from others

**Comment by Destrolaric** [comment]
@w0lfcat Hi, do you use your system java to launch DBeaver? If yes, the TLS10 can be disabled there.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by pich4ya** [comment]
I managed to solve this issue.

```
sudo vim /etc/java-21-openjdk/security/java.security

# modify line
jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, DTLSv1.0, RC4, DES, \
# to ->
jdk.tls.disabledAlgorithms=SSLv3, DTLSv1.0, RC4, DES, \
```

**Comment by mrbarletta** [comment]
For those using flatpak the file is: `/var/lib/flatpak/app/io.dbeaver.DBeaverCommunity/current/active/files/jre/conf/security` in Linux/Ubuntu

**Comment by Destrolaric** [comment]
@mrbarletta, Hi, are you experiencing the same issue in the Flatpak version?

**Comment by mrbarletta** [comment]
> [@mrbarletta](https://github.com/mrbarletta), Hi, are you experiencing the same issue in the Flatpak version?

Yes I am - I had to make that change, and again after an update - luckily I don't log in to that DB very often but it makes connecting to old dbs hard.

Is there another workaround like in the driver settings?
