### ISSUE TITLE
it can't set to another language

### ISSUE THREAD

**Issue by ironmantonystark** [dbeaver/dbeaver#21169]
### Description

my DBeaver used to set to English language, because my Windows is Chinese version, it set to Chinese automatically, that's not my expected , I tried to set it back to English, it doesn't work, after I restart it, it return to Chinese interfaces, I can't set it to English anyway, 

### DBeaver Version

23.2

### Operating System

windows 10

**Comment by LonwoLonwo** [comment]
Hello @ironmantonystark 

Where is your dbeaver.exe file on your computer? Is it in the Program files folder or a different place?

**Comment by ShadelessFox** [comment]
Are you launching DBeaver using the shortcut? If so, open its properties and remove the `-nl XX` part from the "target".

Please let me know if it helps.

**Comment by ironmantonystark** [comment]
> Hello @ironmantonystark
> 
> Where is your dbeaver.exe file on your computer? Is it in the Program files folder or a different place?

ty for replying I installed it on D:\DBeaver

**Comment by ironmantonystark** [comment]
> Are you launching DBeaver using the shortcut? If so, open its properties and remove the `-nl XX` part from the "target".
> 
> Please let me know if it helps.

ty so much for help, but nope

**Comment by E1izabeth** [comment]
Did you install DBeaver via installer or from Microsoft Store? Or do you use portable version?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by ironmantonystark** [comment]
> It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

sorry for getting back you late, ty so much ,I appreciate it
