### ISSUE TITLE
Use the same editor for the Soure of procedures as a SQL script

### ISSUE THREAD

**Issue by JTMosaic** [dbeaver/dbeaver#21189]
DBeaver Community 23.2.0.202309041200

I've installed the Vrapper plug-in to allow for vim-like navigation in DBeaver. It works well in scripts but is unavailable in the Source tab of a procedure when viewed with F4. 

It would be great if the source tab used the same editor framework as a script

**Comment by flambchap** [comment]
Hi. Both of the mentioned editors ([script editor](https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditor.java) and [source editor](https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditorNested.java)) are based on Eclipse's `AbstractDecoratedTextEditor` and [share a lot of functionality](https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditorBase.java). I suspect there is something wrong on the side of the plugin.

**Comment by JTMosaic** [comment]
This is an extremely disappointing answer. It is possible that the differences between the two editors is causing the plugin to not attach and activate for some reason. 

However, blaming it on the plugin is tantamount to saying, "Yes, we built DBeaver on Eclipse but please don't ask us to make plugins we don't provide work."
