### ISSUE TITLE
[BigQuery] error while connecting

### ISSUE THREAD

**Issue by pijoter** [dbeaver/dbeaver#21180]
### Description

`
[Simba][BigQueryJDBCDriver](100004) HttpTransport IO error : Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $..
  Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $.
  Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $.
`

The same connection works perfectly on DBeaver CE 23.1.4 version (but not on 23.1.5 or later)

### DBeaver Version

Community Edition 23.2.0

### Operating System

Windows 10

### Database and driver

Google BigQuey with latest Simba drivers

**Comment by LonwoLonwo** [comment]
Hello @pijoter 

Could you please provide a screen from your connection settings -> driver settings?

Like this?

![2023-09-12 11_35_38-Window](https://github.com/dbeaver/dbeaver/assets/45152336/bc98c751-345c-48ec-ab26-900be77eeeea)

Also, clicking the "restore to defaults" in this dialog + the "ok" button will help.

**Comment by pijoter** [comment]
@LonwoLonwo Well, there were differences. I changed ClassName from com.`simba.googlebigquery.jdbc.Driver` (DBeaver 23.1.4) to `com.simba.googlebigquery.jdbc42.Driver` (DBeaver 23.2.0). That's it. Now is OK. Thank you.
