### ISSUE TITLE
Make find/replace dialog search direction selection sticky

### ISSUE THREAD

**Issue by Blake-Loveland** [dbeaver/dbeaver#21195]
**Is your feature request related to a problem? Please describe.**
No problem at all, dbeaver is already the best db client app in existence by far, just a convenience for my work style and I think maybe other's work style as well. 

I keep a very large .sql file as my main workspace in dbeaver. I often want to find the most recent time I have used a command or worked on a table. This means I use ctl-f to open the find/replace dialog pretty often. However, I always have to alt-b or click on the 'Backward' option for search direction, I basically never want to search forward.

**Describe the solution you'd like**
Either of two solutions would work for this:
1. Make the last search direction selection sticky, so if Backward was the last way I searched, it just stayed that way until a forward search was done.
2. Or it could be preference setting as a default preferred value.

**Describe alternatives you've considered**
I usually click on Backward radio button, but I search 10+ times a day so it would just be a convenience to set it once and then not have to worry about it.

**Additional context**
![image](https://github.com/dbeaver/dbeaver/assets/42970073/f65fcf54-9fcf-457a-9743-1f720693c2c6)

**Comment by flambchap** [comment]
Thank you for the idea. DBeaver uses Eclipse Platform as its foundation, and the search dialog we're discussing comes from there. Unfortunately, we cannot patch it from our side. I suggest creating a ticket for the Eclipse Platform. I believe this is the appropriate repo for such a request: https://github.com/eclipse-platform/eclipse.platform.ui.
