### ISSUE TITLE
Tables are not displayed in the schemas

### ISSUE THREAD

**Issue by liam-taly** [dbeaver/dbeaver#21196]
### Description

Same issue reported on https://github.com/dbeaver/dbeaver/issues/8769

### DBeaver Version

Version 23.2.0.202309041200

### Operating System

Windows 11

### Database and driver

DB: postgres (aws -> PostgreSQL 15.3)
driver: postgres-jdbc (could not find the version) 

### Steps to reproduce

Connect to postgres database on AWS RDS
Navigate through the left side menu till you get to the list of tables

List shows blank. It was working until very recently and stopped working even though I had not updated dbeaver. Tried disconnecting, closing dbeaver, running dbeaver, connecting again no change -- both before and after updating dbeaver to the latest version. Two other people recently reported having a similar issue on the previous logged issue https://github.com/dbeaver/dbeaver/issues/8769.

**Comment by LonwoLonwo** [comment]
Hello @liam-taly 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by Supertraining** [comment]
Right click on your connection. 
Select edit connection --> connection settings.  Select PostgreSQL tab, check "show all databases"

I had the same issue and i solved it this way.

Best regards.

**Comment by anirudh-acharya** [comment]
Leaving this comment for posterity. This worked when I tried to connect locally running postgres instance via DBeaver. The advice to select "Show all databases" did the trick.
