### ISSUE TITLE
Clickhouse default time zone settings

### ISSUE THREAD

**Issue by bewareilive** [dbeaver/dbeaver#21208]
### Description

Why does the Clickhouse connection default to "useuserver_time_zone=false" and "use_time_zone=false"?

The value cannot be queried use **where datetime_field='2023-09-14 13:44:41'**. You need to use **toString (toDateTime ('2023-09-14 13:44:41')** 

### DBeaver Version

Commounity 23.2.0.202309031556

### Operating System

windows 10

**Comment by LonwoLonwo** [comment]
Hello @bewareilive 

This decision was made here https://github.com/dbeaver/dbeaver/issues/17362

You can always manually change parameters in your Connection settings -> Driver Parameters

![2023-09-14 12_10_30-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/4f308dcb-d4c5-4f7d-8a8a-8a69f5ab5029)

If you think that this is an incorrect choice - then please provide more info - why do you think so? Links to the documentation will be helpful in this case.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by maskshell** [comment]
According to the ClickHouse JDBC code:

https://github.com/ClickHouse/clickhouse-java/blob/main/clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseClientOption.java

>    /**
>     * Custom time zone. Only works when {@code use_server_time_zone} is set to
>     * false.
>     */
>    USE_TIME_ZONE("use_time_zone", "", "Time zone of all DateTime* values. "
>            + "Only used when use_server_time_zone is false. Empty value means client time zone.");

"use_time_zone" should be empty value if you just want to disable server time zone config and use dbeaver client time zone config.

and "false" is a invalid value for "use_time_zone".

https://docs.oracle.com/javase/8/docs/api/java/time/ZoneId.html

**Comment by powelleric** [comment]
I'm getting an error after upgrading to 25.0.4.  It says invalid value for use_time_zone.  I set it to "Canada/Atlantic" and the error went away.  

(Also, this only happened to me on the server that I use through an SSH tunnel.  Maybe that is just a different version of clickhouse.  Not sure if the tunnel is related.)

**Comment by E1izabeth** [comment]
That's due to the driver update. See #37954
