### ISSUE TITLE
Stored Procedures not restored from dump

### ISSUE THREAD

**Issue by cliffwm** [dbeaver/dbeaver#21200]
### Description

I create a database dump from a remote server using DBeaver Tools > Dump database, with the --routines extra command argument. The dump completes successfully and the .sql file created contains all the statements to recreate all the tables, data, views and strored procedures as expected.

I then create a new database on localhost with the same database name and try to restore the database from the dump. All tables are successfully created and populated but NONE of the stored procedures are created.

### DBeaver Version

Community Edition 23.2.0

### Operating System

MacOS Ventura 13.5.2

### Database and driver

10.4.28-MariaDB

### Steps to reproduce

1. Connect to (remote) database and create a dump using Tools > Dump database with the --routines argument.
2. Create a local database with the same name.
3. Set this database as the default.
4. Open a New SQL Script tab and load the dump script from step 1.
5. Execute the script.
6. I get repeated errors:`Error occurred during SQL script execution
Reason:
SQL Error [1064] [42000]: (conn=11) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 3`
7. I click Skip All and the script completes execution.
8. All tables are successfully created and populated. All views are created. 
9. No stored procedures are created.

**Comment by LonwoLonwo** [comment]
Hello @cliffwm 

What dump/restore version did you use? You can see this info on your connection page -> Local Client

![2023-09-14 11_21_17-Connection _Maria 10 1_ configuration](https://github.com/dbeaver/dbeaver/assets/45152336/55668fae-474b-4a23-a06d-80c5ff14d61e)

Did you check your dump SQL file? Does it contain create procedure statements?
Could you execute these statements in the SQL Editor of your database?

**Comment by cliffwm** [comment]
Dump was created with 10.6.12-MariaDB. Yes, I checked the dump file and it contains all of the expected create procedure statements. Also, yes, I can execute the statements in the SQL editor if I just take the actual CREATE PROCEDURE statements. For example from this code in the dump:

```sql
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'NO_AUTO_VALUE_ON_ZERO' */ ;
/*!50003 DROP PROCEDURE IF EXISTS `usp_CNT_adminusers` */;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = utf8mb4 */ ;
/*!50003 SET character_set_results = utf8mb4 */ ;
/*!50003 SET collation_connection  = utf8mb4_general_ci */ ;
DELIMITER ;;
CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_CNT_adminusers`()
BEGIN
	SELECT COUNT(*) AS admincount from tbladminuser;
END ;;
DELIMITER ;
```

if I extract:

```sql
CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_CNT_adminusers`() 
BEGIN
	SELECT COUNT(*) AS admincount from tbladminuser;
END
```

then this works successfully.

**Comment by LonwoLonwo** [comment]
Mm.. Ok, could you please provide the full log from the restore wizard from the last window? With errors.

**Comment by cliffwm** [comment]
`!ENTRY org.jkiss.dbeaver.model 4 0 2023-09-14 16:51:13.583
!MESSAGE Broken pipe
!STACK 0
java.io.IOException: Broken pipe
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(Unknown Source)
	at java.base/java.io.BufferedOutputStream.write(Unknown Source)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler$BinaryFileTransformerJob.run(AbstractNativeToolHandler.java:440)`

**Comment by cliffwm** [comment]
If I restore from a command line using source <dump.sql> the database is correctly restored, including stored procedures.

**Comment by ShadelessFox** [comment]
Please provide the complete log, not just the part of it.

**Comment by E1izabeth** [comment]
@cliffwm 
Please provide the full stack trace from the log, not just a part of it.

**Comment by cliffwm** [comment]
[restore.log](https://github.com/dbeaver/dbeaver/files/12935382/restore.log)
Sorry to be a bit tardy responding, I have been away. The relevant entry is at the end:
  !ENTRY org.jkiss.dbeaver.model 4 0 2023-10-17 17:01:04.473

**Comment by LonwoLonwo** [comment]
Please provide entire restore log from restore wizard:

![2023-10-18 11_46_11-DBeaver 23 2 2 - _postgres 2_ Script-18](https://github.com/dbeaver/dbeaver/assets/45152336/2ccd210d-d7c5-4620-a803-2eda4fd4e396)

**Comment by cliffwm** [comment]
I think you have helped me solve the problem. I was executing the dump script in a SQL window rather than using the Restore Wizard! It works fine in the wizard (other than having to delete the "DEFINER=`root`@`localhost`" clauses from the CREATE PROCEDURE entiries ) but fails in the SQL window, so I guess I was not using DBeaver correctly. My apologies for wasting your time but thank you for steering me in the right direction :-)

**Comment by E1izabeth** [comment]
Thank you for update!
