### ISSUE TITLE
"No Data Execute query with Ctrl+Enter..." for a table with many records

### ISSUE THREAD

**Issue by rigczTheSky** [dbeaver/dbeaver#21218]
### Description

Hi. I've just installed DBeaver from an official site v 23.2. I connected to PostgreSQL database and tried to get result with: 

`select * from table_name`

![image](https://github.com/dbeaver/dbeaver/assets/59015267/55ffd595-f956-4d6b-ba3e-d70f818929fd)

When i press f4 on the same table from menu on the left i get a few thousands of records. 

Can anybody tell me how to fix that? 

I'm using PostgreSQL version 10.12.

### DBeaver Version

23.2.0

### Operating System

Windows 11

**Comment by E1izabeth** [comment]
Could you explain in details how are you trying to execute the query? The video showing the issue would be very useful.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
