### ISSUE TITLE
DB2 : infinite load schema statistics

### ISSUE THREAD

**Issue by grrosminet** [dbeaver/dbeaver#21216]
### Description

Hi

Each time I start DBeaver, when I double click on a DB2 table it tries to read schema statistics for an infinite time. I have to kill the task in order to get table infos.

![Capture d'écran 2023-09-14 145540](https://github.com/dbeaver/dbeaver/assets/3082795/af8ef525-278c-4a54-8a77-fba9e4b708d3)

### DBeaver Version

Community Edition 23.1.5

### Operating System

Windows 11

### Database and driver

DB2 v11.5
Driver Db2 for LUW

### Steps to reproduce

1) completely close dbeaver
2) start dbeaver
3) double clic on a table in the browser

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.
Also we need thread dump to understand what's happening. You can find a way to do it here https://dbeaver.com/docs/dbeaver/Making-a-thread-dump/

**Comment by grrosminet** [comment]
see attached files

[dbeaver.log](https://github.com/dbeaver/dbeaver/files/12609508/dbeaver.log)
[thread-dump.txt](https://github.com/dbeaver/dbeaver/files/12609509/thread-dump.txt)

**Comment by E1izabeth** [comment]
Thank you

**Comment by ShadelessFox** [comment]
What's the driver version? You can see it by performing a connection test on the connection page.

**Comment by grrosminet** [comment]
IBM Data Server Driver for JDBC and SQLJ 4.31.10

**Comment by LonwoLonwo** [comment]
Hello @grrosminet 

I can't reproduce it with the driver version 4.31.10 and the latest DBeaver.
Could you please check the latest [DBeaver version](https://dbeaver.io/download/)?

**Comment by grrosminet** [comment]
Still the same on 23.2.1 (no update available)

It hangs on :
SELECT TABNAME, SUM(DATA_OBJECT_P_SIZE + INDEX_OBJECT_P_SIZE + LONG_OBJECT_P_SIZE + LOB_OBJECT_P_SIZE + XML_OBJECT_P_SIZE) AS TOTAL_SIZE_IN_KB FROM SYSIBMADM.ADMINTABINFO WHERE TABSCHEMA=? GROUP BY TABNAME

**Comment by LonwoLonwo** [comment]
Could you execute this query (with added parameters) in the SQL Editor? Does it work correctly?

**Comment by grrosminet** [comment]
no it doesn't work, even from DB2 CLI

**Comment by grrosminet** [comment]
instead, you should use this request : 
`SELECT     TABNAME,     SUM(DATA_OBJECT_P_SIZE + INDEX_OBJECT_P_SIZE + LONG_OBJECT_P_SIZE + LOB_OBJECT_P_SIZE + XML_OBJECT_P_SIZE) AS TOTAL_SIZE_IN_KB FROM  table(ADMIN_GET_TAB_INFO('MYSCHEMA','')) GROUP BY TABNAME`

this will avoid loading data for the whole DB whereas we are only interested in 1 schema. Be aware that event if this request is more restrictive and the faster, on very big schemas it will hang too (about 30 secs on a  200Go schema, with top level hardware)


The best would be to load this data only when requested : when I double clic on a table, most of the time I only need to see the structure and/or the datas, not disk usage statistics. And with the provided request you even can get stats on 1 table (second argument).

**Comment by LonwoLonwo** [comment]
But the [documentation](https://www.ibm.com/docs/en/db2oc?topic=aracp-admin-get-tab-info-retrieve-table-size-state-information) says that:

`The ADMINTABINFO administrative view and the ADMIN_GET_TAB_INFO table function provide methods to retrieve table size and state information that is not currently available in the catalog views.`

And the original query also has the condition for the schema - `WHERE TABSCHEMA=?`

Also, if you do not want to see the complete statistics for all schemas - you can turn off the setting:

![2023-10-06 09_14_52-DBeaver Ultimate 23 2 2 - NEWTABLE](https://github.com/dbeaver/dbeaver/assets/45152336/630c2458-5935-4600-bd91-4d534e9259ad)

And check table statistics in the special Statistics tab.

**Comment by grrosminet** [comment]
ADMINTABINFO is a view on ADMIN_GET_TAB_INFO('','') ==> so it fill gather statistics for every table on the whole database ( 5To in my case ) and then apply your filter. That's why you should consider using the workaround I suggested

I'll disable statistics info


----

I have disabled statistics info, but if I double clic on a schema, it opens a "schema tab" and then the UI is completely freezed on the same request

**Comment by LonwoLonwo** [comment]
Ok, we will investigate this case and do some performance tests.

**Comment by LonwoLonwo** [comment]
Ok, I checked, and your query is faster. We can change it.

![2023-11-02 11_26_03-DBeaver Ultimate 23 2 3 - _SAMPLEDB_ Script-124](https://github.com/dbeaver/dbeaver/assets/45152336/126817cf-37ca-46be-ab16-369e6112d120)
