### ISSUE TITLE
Database Navigator doesn't show SQL Server Tables

### ISSUE THREAD

**Issue by kansoit** [dbeaver/dbeaver#21219]
### Description

Database Navigator doesn't show SQL Server Tables.

![image](https://github.com/dbeaver/dbeaver/assets/4549674/fe1ef474-365a-4fba-8a8c-cd1c28da1592)

Log error shows this:
Message: 
Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)
Exception Stack Trace: 
An exception stack trace is not available.

Session data:
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\myuser\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

Logs Attached:
[.log](https://github.com/dbeaver/dbeaver/files/12611891/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/12611892/dbeaver-debug.log)

I also followed these instructions without success
https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings

### DBeaver Version

Version 23.2.0.202309041200

### Operating System

Windows 11 22H2 Build 2263

### Database and driver

1) ![image](https://github.com/dbeaver/dbeaver/assets/4549674/b400a8a3-0fb3-4885-b7f6-99e37b74a0ac)
2) ![image](https://github.com/dbeaver/dbeaver/assets/4549674/5c722c5b-9a00-4a7b-87d7-42b0157ef4f0)

### Steps to reproduce

1. I connect to MSSQL Instance and I tried to see tables inside the database without success

**Comment by E1izabeth** [comment]
Have you tried to look inside schemas?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/d6bc8350-88db-474a-82c5-0be8b0371b36)

**Comment by kansoit** [comment]
I'm truly ashamed to have opened this issue. Can we bury it six feet under and forget about it for ever. Can I say that I was very tired when I opened?

**Comment by kansoit** [comment]
I'm still tired. I didn't thank you properly for your time. I apologize for this inconvenience. Thanks!

**Comment by E1izabeth** [comment]
I'm happy we solved an issue!
Thank you for update :)
