### ISSUE TITLE
Scrolling after update weirdly slow (and high cpu consumption)

### ISSUE THREAD

**Issue by jmarcher** [dbeaver/dbeaver#21214]
### Description

I created a video showing the lagginess of the scroll and the high cpu usage

Video: https://imgur.com/o8EJqxO

### DBeaver Version

23.2.0.202309041200

### Operating System

macOS Sonoma 14.0 (23A339)

**Comment by E1izabeth** [comment]
Your video is unavailable. Could you attach it to the github comment directly?

**Comment by jmarcher** [comment]
https://github.com/dbeaver/dbeaver/assets/686843/19829e4a-5bc4-4192-8d25-566aa2bd8cdc

Sorry didn't knew that was possible to upload videos here

**Comment by E1izabeth** [comment]
Thanks

**Comment by E1izabeth** [comment]
Haven't you updated you mac recently up to 14.0 version?

**Comment by jmarcher** [comment]
Yes, I updated DBeaver at the same time, maybe that is the problem.

**Comment by E1izabeth** [comment]
We don't have macOS Sonoma 14.0 to reproduce this issue, but we couldn't reproduce it on the older mac versions.

**Comment by jmarcher** [comment]
Hi, the issue persists, macOS Sonoma 14.0 is now live

**Comment by E1izabeth** [comment]
Thank you for update

**Comment by Acid-Override** [comment]
I can confirm the issue after updating to Sonoma.  When scrolling a large number of tables there is noticeable lag and high CPU usage.  My symptoms are much worse than what is shown in video.  M1/16Gb machine.

**Comment by Babel78** [comment]
Same Here , when scrolling a large number of package in macOS Sonoma.

**Comment by rendyrey** [comment]
Same here. I've tried to downgrade to 3 months version back. it's still occur. It seems the sonoma issues. 
I can confirm this (Sonoma 14.0 with Intel last macbook generation, 2020)

**Comment by Andrew0002** [comment]
I'm having this issue too after updating to macOS Sonoma. It happens in the database navigator, but not script editor/result panes. Autocomplete is also extremely slow. 2019 Intel MacBook Pro.

**Comment by peterpk** [comment]
I'm seeing the same thing just after update to Sonoma. It seems to be related to the size (number of entries) in the navigator -- I have a DB connection with thousands of schemas and it's painful to navigate. And while most operations in the SQL editor are fine, I do see a delay the first time that I engage auto-complete (i.e. when I type `SELECT * FROM A` and it's trying to find the schemas starting with A).

This is also on a 2019 Intel MacBook Pro with Sonoma 14.0.

**Comment by Andrew0002** [comment]
> I'm seeing the same thing just after update to Sonoma. It seems to be related to the size (number of entries) in the navigator -- I have a DB connection with thousands of schemas and it's painful to navigate. And while most operations in the SQL editor are fine, I do see a delay the first time that I engage auto-complete (i.e. when I type `SELECT * FROM A` and it's trying to find the schemas starting with A).
> 
> This is also on a 2019 Intel MacBook Pro with Sonoma 14.0.

I noticed the same thing with the number of entries. Just to make sure there wasn't an issue with my configuration, I renamed the "DBeaverData" folder in my Library to "DBeaverData-old" then I added my main database back. At first I thought things were better, but as soon as I started drilling down in the database navigator (database, schema, tables, procedures...) it just gets slower and slower.

**Comment by casalistefano** [comment]
Same issue after updating to macOS Sonoma. Navigation in database is very slow and difficult. 
Tested on MacBook Pro 2019 - Intel.

**Comment by jamesandres** [comment]
Hello, if it helps, I'm experiencing this but _not on macOS Sonoma_. I wonder if this is a general issue that occurred with a DBeaver update?

Here's a short video showing how at idle DBeaver consumes negligible CPU, but resizing the window the CPU quickly jumps to near 100%, and scrolling a table the CPU also stays level at near 100%.


https://github.com/dbeaver/dbeaver/assets/392214/a30e70de-6106-4f02-91b4-84f0f81ba8e2

I'm using DBeaver  23.2.2.202310081633 and running macOS Ventura (13.6)

Stab in the dark, perhaps DBeaver is doing UI rendering on the CPU when it should be using the GPU..

**Comment by michaelflynn-dd** [comment]
Also having this issue. Apple M1 Pro, 16 GB, macOS 14.0. It just started this week, immediately after updating to 14.0. Gonna have to switch clients if it keeps up :(

**Comment by jmarcher** [comment]
Tried switching to Oracle JDK 17, still the same problem, Oracle JDK 21, also the same problem.

This issue makes DBeaver on Macos a pain to use.

**Comment by michaelflynn-dd** [comment]
I've switched to VS Code. The Snowflake extension works perfectly well, and there's zero lag. The cutover took me less than 10 minutes, would recommend (even if only as a temporary fix) until someone can track down and resolve this issue.

**Comment by jmarcher** [comment]
Another fact: Tried DBeaver Ultimate Edition 23.2 (trial) and it works perfectly, the CPU consumption gets a little high when scrolling but there is no lag visible. Is 23.2 Ultimate maybe based on an even older Community Branch?

**Comment by klovskim** [comment]
I am experiencing this as well on macOS Sonoma, 2019 Mac Pro with Intel chip.

**Comment by xingxiuyi** [comment]
Also having this issue. macOS Sonoma M1 Max.

**Comment by giovanni-landolina** [comment]
As a workaround, unchecking User Interface -> Navigator -> Show statistics info makes it much better for me

**Comment by ShadelessFox** [comment]
@giovanni-landolina thanks for pointing that out. It can greatly assist in our research.

**Comment by xingxiuyi** [comment]
> As a workaround, unchecking User Interface -> Navigator -> Show statistics info makes it much better for me

it's still slow.

**Comment by jtray23** [comment]
I started experiencing this same issue here after upgrading DBeaver CE and macOS around the same time, about a month ago.

Sonoma 14.1.1 - 2.3Ghz Intel Quad-Core i7

Only seems to affect my "Database Navigator" menu: extreme lag while scrolling up and down, gets worse as more database sub-groups are expanded, before that recent update, scrolling this same Navigator list was smooth and lag-free.

**Comment by ricfwolff** [comment]
Same thing here after upgrading to Sonoma.

**Comment by deyanginev** [comment]
Hi team. 

I can also report a huge performance degradation with DBeaver Version 23.2.5.202311191730 and MacOS Sonoma 14.1.1. My Mac has 32 GB of RAM and a M1 Pro processor. Our project has hundreds of schemas with each schema consisting of roughly a hundred tables. Before updating to MacOS Sonoma DBeaver was working perfectly fine with this setup. Something has changed with MacOS Sonoma.

I can see during lag that DBeaver's CPU usage spikes significantly.

If that helps, I experience significant lag while browsing the Tree View showing the schemas and their child components like tables, etc.

Also, when I start typing in the SQL script editor, the auto-suggest takes 20-30 seconds to barely display a list of suggestions.

Here's a screenshot of how the Dashboard looks like while typing a simple `select * from ...` in the SQL script editor:


![Screenshot 2023-11-29 at 10 40 26](https://github.com/dbeaver/dbeaver/assets/3218237/e94befa2-1279-4928-81d0-d00790fca4d2)

Let me know if I can provide you with further information that might be helpful.

**Comment by peterpk** [comment]
So, very strange, today it seems to be working fine.  Different from my last comment, I'm now on DBeaver 23.3.0.202312031432 and macOS Sonoma 14.2.  Whatever it is with that combination, I have happy scrolling again!

**Comment by deyanginev** [comment]
With 23.3.0.202312122044 the issue still persists on my side. MacOS: 14.1.1 (23B81). Updating to 14.2 and will report.

**Comment by jmarcher** [comment]
> So, very strange, today it seems to be working fine. Different from my last comment, I'm now on DBeaver 23.3.0.202312031432 and macOS Sonoma 14.2. Whatever it is with that combination, I have happy scrolling again!

Can confirm, it looks that it was a weird Sonoma problem after all.

**Comment by deyanginev** [comment]
> With 23.3.0.202312122044 the issue still persists on my side. MacOS: 14.1.1 (23B81). Updating to 14.2 and will report.

Confirming that with MacOS 14.2 and the latest version of DBeaver things are fixed.

**Comment by E1izabeth** [comment]
It's a good news! Thank you!

**Comment by xingxiuyi** [comment]
> > With 23.3.0.202312122044 the issue still persists on my side. MacOS: 14.1.1 (23B81). Updating to 14.2 and will report.
> 
> Confirming that with MacOS 14.2 and the latest version of DBeaver things are fixed.

Confirm MacOS 14.2 are fixed.
