### ISSUE TITLE
[ui typo] tab context menu close all shows 'close close' in Chinese

### ISSUE THREAD

**Issue by LeiYangGH** [dbeaver/dbeaver#21233]
### Description

![image](https://github.com/dbeaver/dbeaver/assets/5386998/3f9f669f-e7f2-4227-822a-5206c5501020)
version： 23.2.0
ui language: chinese

### DBeaver Version

 23.2.0

### Operating System

win11

**Comment by LonwoLonwo** [comment]
Hello @LeiYangGH 

Thanks for the report.

And I'm closing this ticket as a duplicate of https://github.com/dbeaver/dbeaver/issues/17697

You can read more info about translation there.
