### ISSUE TITLE
Support Backup/Restore PostgreSQL 17

### ISSUE THREAD

**Issue by pomazanbohdan** [dbeaver/dbeaver#21241]
Pls add support support Backup/Restore PostgreSQL 16

**Comment by LonwoLonwo** [comment]
Thanks for the idea @pomazanbohdan

**Comment by PrinceJunkie** [comment]
Is there any support for PostgreSQL 16 right now?

**Comment by LonwoLonwo** [comment]
Hello @PrinceJunkie

You can always add it manually in DBeaver.

1. Go to your Connection Settings and choose Native Clients - Browse

![2023-10-02 10_52_12-Connection _postgres 6 1_ configuration](https://github.com/dbeaver/dbeaver/assets/45152336/d3b36ef0-d58d-4ac8-aa71-161638a84594)

2. And Peek up **installed on your computer** PostgreSQL 16 folder with the "Add home" button:

![2023-10-02 10_53_02-Connection _postgres 6 1_ configuration](https://github.com/dbeaver/dbeaver/assets/45152336/032a9bc1-5972-40d5-9ce6-9005b8df1b20)

**Comment by zc-devs** [comment]
[For Windows](https://www.postgresql.org/download/windows/) you can download ZIP-archive with binaries and copy files to clients directory:
```
$ ls -1 ~/AppData/Roaming/DBeaverData/drivers/clients/postgresql/win/16
libcrypto-3-x64.dll*
libiconv-2.dll*
libintl-9.dll*
liblz4.dll*
libpq.dll*
libssl-3-x64.dll*
libwinpthread-1.dll*
libzstd.dll*
pg_dump.exe*
pg_dumpall.exe*
pg_restore.exe*
psql.exe*
zlib1.dll*
```

**Comment by mkgrgis** [comment]
@LonwoLonwom look like this issue can be closed with limitation to https://github.com/dbeaver /dbeaver/issues/8143

**Comment by ivanlonel** [comment]
This issue should be updated to "Support Backup/Restore PostgreSQL 17" now.

**Comment by mkgrgis** [comment]
Still no SSL support?

**Comment by ShadelessFox** [comment]
@mkgrgis what do you mean by "SSL support"?

**Comment by mkgrgis** [comment]
> @mkgrgis what do you mean by "SSL support"?

@ShadelessFox , only https://github.com/dbeaver/dbeaver/issues/8143 and nothing more.

**Comment by ShadelessFox** [comment]
I've assigned a milestone to the linked ticket.

**Comment by mkgrgis** [comment]
> I've assigned a milestone to the linked ticket.

Thanks, @ShadelessFox !
