### ISSUE TITLE
Dates / timestamps BC are not displayed correctly

### ISSUE THREAD

**Issue by hackenspp** [dbeaver/dbeaver#21254]
### Description

Dates before Christus (BC) are not displayed correctly in the data grid, they should indicate 'BC' after the date.

### DBeaver Version

CE 23.2.0

### Operating System

Windows 11

### Database and driver

Postgres 14.8

### Steps to reproduce

```
SELECT '12 July 100 BC'::date
> 0100-07-12
SELECT '12 July 100 BC'::date::text
> 0100-07-12 BC
```
The first select should display a BC at the end as the second select
The same applies for timestamps (and also with time zones I suppose):
```
SELECT '753-01-01T00:00:00Z BC'::timestamp
> 0753-01-01 00:00:00.000
SELECT '753-01-01T00:00:00Z BC'::timestamp::text
>0753-01-01 00:00:00 BC
```

**Comment by Destrolaric** [comment]
Hi, DBeaver formats values by configurable pattern. All data formats can be configured in `Editors -> Data Editor -> Data Formats`. To add Era. You can add a `G` letter to the date/timestamp pattern. 
You can also `disable date/time formatting` to show dates in the database's native format.
![image](https://github.com/dbeaver/dbeaver/assets/20579256/61e21643-5477-4507-bf0d-428d81cf7dcb)
