### ISSUE TITLE
Tools menu disappears from the context menu if the dashboard is open

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#21252]
23.2.0, win10            
  Tools disappear from the context menu if the dashboard is open

https://github.com/dbeaver/dbeaver/assets/31996417/af71f5d6-af96-4c5d-8cc6-12bff9d3ff3b

_Originally posted by @uslss in https://github.com/dbeaver/dbeaver/issues/21156#issuecomment-1725105226_

**Comment by E1izabeth** [comment]
Duplicate of #16469
