### ISSUE TITLE
Unable to load driver libraries (Simba JDBC for BigQuery or Apache Spark)

### ISSUE THREAD

**Issue by mariomiola** [dbeaver/dbeaver#21251]
### Description

Find Class does not return any values when attempting to create a new Driver and setting the Libraries to point to a Folder or individual files.
Driver documentation https://cloud.google.com/bigquery/docs/reference/odbc-jdbc-drivers and https://documentation.insightsoftware.com/simba-spark-jdbc-driver-connector-configuration-guide/content/jdbc/using/intro.htm 

![Screen Shot 2023-09-19 at 5 04 49 PM](https://github.com/dbeaver/dbeaver/assets/108755375/6388c1a1-ac30-4950-b5ad-52f8d8151aa4)

### DBeaver Version

DBeaver-ce 23.2.0

### Operating System

macOS Monterrey 

### Database and driver

Simba Apache Spark JDBC Data Connector 2.26.21
Simba Google BigQuery JDBC Data Connector 1.15.0

### Steps to reproduce

1. From Database/Driver Manager
2. Create New Driver
3. In the Libraries tab, add Folder or individual .jar files 
4. Hit Find Class - it does not find any driver class

### Additional context

Reproducible on Windows Server 2022 as well.

**Comment by LonwoLonwo** [comment]
Hello @mariomiola 

Yes, for some reason, for new drivers, newly added libraries are not used in the find class method logic.

Thanks for the report.

A workaround for now - you can add libraries for a newly added driver, press "Ok" (and create a new driver), choose this driver from the driver's list, click on the "Edit" button, go again to the "Libraries" tab, and try to press "Find Class" again. It works in my case.

**Comment by mariomiola** [comment]
Thanks for the workaround @LonwoLonwo
