### ISSUE TITLE
SQL SERVER Unable to add primary key when adding a new table，The keyword for generating and setting the primary key is' Identity ', but the actual keyword for sqlserver is' PRIMARY KEY'

### ISSUE THREAD

**Issue by luomocp** [dbeaver/dbeaver#21260]
### Description

SQL SERVER Unable to add primary key when adding a new table

### DBeaver Version

23.2.0.202309041200

### Operating System

win

**Comment by LonwoLonwo** [comment]
Hello @luomocp 

Please provide clear steps to reproduce your issue.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
