### ISSUE TITLE
[Exasol] Active schema cannot be changed in Main toolbar

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#21269]
### Description

Active schema for Exasol cannot be changed in Main toolbar. Empty dialog and Schea list is shown.

![image](https://github.com/dbeaver/dbeaver/assets/31996417/90ad6d95-80d0-4b3e-b0f4-6cf4ba228736)
![image](https://github.com/dbeaver/dbeaver/assets/31996417/1fed07ec-25ee-498d-9111-bde7fade8fa0)

### DBeaver Version

23.2.1

### Operating System

win10

### Database and driver

EXASolution 7.1.15
EXASolution JDBC Driver 7.1.16

**Comment by LonwoLonwo** [comment]
Can't reproduce
