### ISSUE TITLE
[Exasol] Table name isn't proposed in SELECT query

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#21267]
### Description

Only WHERE is suggested after FROM keyword for query like `SELECT * FROM`

https://github.com/dbeaver/dbeaver/assets/31996417/194d43f5-c072-4911-b178-2ab89a6e5794

### DBeaver Version

23.2.1

### Operating System

win10

### Database and driver

EXASolution 7.1.15
EXASolution JDBC Driver 7.1.16

**Comment by LonwoLonwo** [comment]
Also can't reproduce 

![2023-09-22 12_47_17-](https://github.com/dbeaver/dbeaver/assets/45152336/39039082-81e0-4224-8c31-ebd5b9d49e83)
