### ISSUE TITLE
Improve query readability on HTML export by aligning text to the left

### ISSUE THREAD

**Issue by lepusarticus** [dbeaver/dbeaver#21278]
**Is your feature request related to a problem? Please describe.**
Hey! As a data professional, I heavily use this "Copy as HTML" feature. (Thank you)
Ref.: [DataExporterHTML.java#L94](https://github.com/dbeaver/dbeaver/blob/e7989f5547716d31d1ec8d10247b9079173c730e/plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/exporter/DataExporterHTML.java#L94)

When the query is exported along with the data, the text-align: center makes the query super unreadable. Changing that to "left" would already be a significant improvement.

I always have to edit this before sharing the query results with others. Sometimes, the tool I paste the results as HTML can't edit the alignment (e.g.: MS Teams), so I have to delete the query from the export and then copy and paste the query separately.

I know this is also used for the table name when the results are exported from a table. The table name would look better aligned to the left as well.

**Describe the solution you'd like**
Just change the alignment to: left
Bonus points: export the query as coloured source code using [HTMLSQLConverter.java#L38](https://github.com/dbeaver/dbeaver/blob/e7989f5547716d31d1ec8d10247b9079173c730e/plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/convert/impl/HTMLSQLConverter.java#L38)

**Describe alternatives you've considered**
I usually erase the query in the export, then copy and paste it again and share it outside the HTML table provided.

**Additional context**
Below are screenshots of the "Copy as HTML" when pasted to MS Teams. The query is only readable because it is simple. But the screenshots show that the query does not even appear unless you scroll to the center.
![Snag_2e76ddd0](https://github.com/dbeaver/dbeaver/assets/145161434/6df0d0c5-c83c-4894-9f73-f057ce9fac68)
![Snag_2e76f65a](https://github.com/dbeaver/dbeaver/assets/145161434/56a0c901-2c61-4988-ad1e-bc3e5b965fb9)
![Snag_2e770a7e](https://github.com/dbeaver/dbeaver/assets/145161434/a689fe94-ddf5-4373-a08d-bc5261775c7e)

**Comment by E1izabeth** [comment]
Thank you for the idea.

**Comment by lepusarticus** [comment]
> Thank you for the idea.

No problem! I created my account on github just to communicate this idea here. It has been my pet peeve for years. hahahah 😄 

DBeaver is amazing. I've been using it since 2017. Thanks for the awesome tool you all built.
