### ISSUE TITLE
[Exasol] Hyperlinks aren't working in SQL editor

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#21270]
### Description

Hyperlinks aren't working in SQL editor

Nothing happens on Ctrl+click on table name and schema_name.table_name

https://github.com/dbeaver/dbeaver/assets/31996417/5962d75a-5042-4fd0-9a29-744ee1d07fbf

### DBeaver Version

23.2.1

### Operating System

win10

### Database and driver

EXASolution 7.1.15
EXASolution JDBC Driver 7.1.16

**Comment by LonwoLonwo** [comment]
Can't reproduce
