### ISSUE TITLE
With Postgres connection mode set to "Simple", can't add or delete columns from table

### ISSUE THREAD

**Issue by DeflateAwning** [dbeaver/dbeaver#21289]
### Description

When you create a Postgresql connection, and set its `Connection view` to "Simple", DBeaver doesn't let you add or remove columns in the table view. 

### DBeaver Version

Community Edition 23.2.0

### Operating System

Ubuntu

### Database and driver

```
PostgreSQL 12.14
PostgreSQL JDBC Driver 42.5.2
```

**Comment by LonwoLonwo** [comment]
Hello @DeflateAwning 

Yes, that's expected behavior for the "Simple View". Other object creation also is not available via UI. 
You can choose a custom or advanced navigator view or change your tables via SQL Editor.

**Comment by DeflateAwning** [comment]
Is there a way to show only tables (or only tables and views) in the sidebar without decreasing the capabilities of DBeaver overall?

**Comment by LonwoLonwo** [comment]
Unfortunately, there is no way to do it like this. 
Please use custom mode or advanced to change metadata via UI.
