### ISSUE TITLE
Wrong shell name for postgres script task creaton called from table node

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#21281]
### Description

1. call the context menu on a table in PostgreSQL
2. context menu -> tools -> execute script
3. Shell for 'MySQL' instead of 'PostgreSQL' is opened

![image](https://github.com/dbeaver/dbeaver/assets/43252954/f0001624-4c7c-4958-a68b-1276a82a50aa)

When calling the context menu on a database node all is OK

https://github.com/dbeaver/dbeaver/assets/43252954/f378320e-6459-45be-9d5c-82742e03ef2e

### DBeaver Version

23.2.1

### Operating System

win10

**Comment by E1izabeth** [comment]
`Execute script` option should be available only for database node.
