### ISSUE TITLE
Receiving error when submitting multiple statements that include a DDL to Teradata

### ISSUE THREAD

**Issue by nicke5012** [dbeaver/dbeaver#2128]
I'm trying to submit the following code to Teradata and get the error `Only an ET or null statement is legal after a DDL Statement`. With other SQL clients the chunk works fine.

```
CREATE VOLATILE TABLE my_test (
    name CHAR(10),
    num  INTEGER
) ON COMMIT PRESERVE ROWS;
INSERT INTO my_test VALUES ('hello', 1);
INSERT INTO my_test VALUES ('somename', 2);
```

**Comment by serge-rider** [comment]
Check this: https://community.teradata.com/t5/Database/3932-Only-an-ET-or-null-statement-is-legal-after-a-DDL-Statement/td-p/48258

Workaround: you can switch to auto-commit mode (see main toolbar or main menu Database).

**Comment by nicke5012** [comment]
Thanks serge-rider. I've tried wrapping the statement with `BT` and `ET`, and have tried with autocommit on and off. Neither solution has worked. I was able to get this to work on Aqua Data Studio after changing a setting to have `;` recognized as a statement separator (vs. `/` which is what was set by default). I've also tried to mess with the statement delimiter settings as well in DBeaver to no avail.

**Comment by austinbeam** [comment]
> Check this: https://community.teradata.com/t5/Database/3932-Only-an-ET-or-null-statement-is-legal-after-a-DDL-Statement/td-p/48258
> 
> Workaround: you can switch to auto-commit mode (see main toolbar or main menu Database).

This did it for me for anyone still running into the issue.

**Comment by vrkadiyala** [comment]
I am able to create a volatile table, however, I am getting the error message of an object does not exist. How to fix this error in Dbeaver?
