### ISSUE TITLE
Auto-format Postgresql JSON/JSONB cells when editing and viewing

### ISSUE THREAD

**Issue by DeflateAwning** [dbeaver/dbeaver#21290]
**Is your feature request related to a problem? Please describe.**
I hate it when JSON contents appear on one line when I go to edit/view them.

**Describe the solution you'd like**
I'd like to see a standard auto-format applied to JSON cells, which splits contents onto new lines as applicable. 

**Describe alternatives you've considered**
Currently, you're required to copy-paste JSON contents to a text editor with JSON formatting capabilities, or to an auto-format website.

**Comment by MashaKorax** [comment]
Hello, @DeflateAwning, please update the app. Probably we already fixed it.

Do you mean this JSON editor?
![HeQUH4wtr6](https://github.com/dbeaver/dbeaver/assets/84867187/d3cd0589-5774-433b-903b-305feae6ddf3)

**Comment by DeflateAwning** [comment]
How do you get to that?

**Comment by MashaKorax** [comment]
Right mouse click on cell -> edit -> edit cell
![dbeaver_wQsDhPi4Xc](https://github.com/dbeaver/dbeaver/assets/84867187/f66b3bf1-6bd2-49ba-bb01-beaf769003e0)

**Comment by DeflateAwning** [comment]
Is there a way to auto-format the JSON? It appears as a massive single-line string still (albeit with syntax highlighting). 

I want it to display auto-formatted across multiple lines, with proper indenting.

**Comment by MashaKorax** [comment]
To auto-format XML/JSON script press **Ctrl + Shift + F** keyboard buttons. But  please note that your application must be updated to the latest version (23.2.1) because we fixed it in the last sprint

https://github.com/dbeaver/dbeaver/assets/84867187/41bd2c5f-bb3b-4686-bca6-0b5382c7db52

**Comment by DeflateAwning** [comment]
Very slick, I am satisfied. Thank you!
