### ISSUE TITLE
Mistake appears during dump expanding

### ISSUE THREAD

**Issue by Natalia27041985** [dbeaver/dbeaver#21291]
### Description

I try to expand PostreSQL dump in DBeaver 23.2.0 however mistake occurs during loading. Dump is [mushrooms.sql](https://code.s3.yandex.net/SQL%20for%20data%20and%20analytics/mushrooms.sql)
![IMG_20230910_170759](https://github.com/dbeaver/dbeaver/assets/143404678/50197389-e892-4982-afbd-a8aa3eba22f9)
![IMG_20230910_170816](https://github.com/dbeaver/dbeaver/assets/143404678/8677a976-a42a-4243-ab1f-2447f73cd900)
[Logs 1.docx](https://github.com/dbeaver/dbeaver/files/12706511/Logs.1.docx)
[Logs 2.docx](https://github.com/dbeaver/dbeaver/files/12706512/Logs.2.docx)

### DBeaver Version

 Free Universal Database Manager 23.2.0.202309041200

### Operating System

Windows 10, version 22H2  desktop

### Database and driver

1.PostgreSQL 16rc1
2.Driver version PostgreSQL JDBC Driver Standard

### Steps to reproduce

1. Projects-Create-Database - Name of database   New_database - Owner   postgres- OK
2. Projects New_database - Set by default
3. Projects New_database - Instruments - Perform script-input file (attached) - Start
 [mushrooms.sql](https://code.s3.yandex.net/SQL%20for%20data%20and%20analytics/mushrooms.sql)
5. Error occures (attached)
[Logs 2.docx](https://github.com/dbeaver/dbeaver/files/12706504/Logs.2.docx)
[Logs 1.docx](https://github.com/dbeaver/dbeaver/files/12706505/Logs.1.docx)
![IMG_20230910_170816](https://github.com/dbeaver/dbeaver/assets/143404678/6de1b327-3b0d-42b0-bbae-0a7c93f63bb7)
![IMG_20230910_170759](https://github.com/dbeaver/dbeaver/assets/143404678/6693ce02-0abd-4859-9f41-cd6986b5240d)

**Comment by LonwoLonwo** [comment]
Hello @Natalia27041985 

First of all, did you try to restore your SQL? Or execute it as a script?
Because I see different info in the header and on screens.

The second one - your locale and native client are different. Probably, for this reason, you see corrupted characters.
And it can be any error inside. Maybe it is - table/column already exists.
Which native Client do you use? You can find this info in your connection settings.

**Comment by E1izabeth** [comment]
We expect that it was solved with #21513 and the bug doesn't exist on the latest DBeaver version.
However, if the issue is still reproducible, please let me know.
