### ISSUE TITLE
Unable to connect Redshift After new Update Version 23.2.1.202309250303

### ISSUE THREAD

**Issue by manikandan-macro** [dbeaver/dbeaver#21298]
### Description

SQL Error [42P01]: ERROR: relation "pg_catalog.pg_enum" does not exist
  ERROR: relation "pg_catalog.pg_enum" does not exist
  ERROR: relation "pg_catalog.pg_enum" does not exist

which has worked in Older versions

Could you please ASAP

### DBeaver Version

23.2.1.202309250303

### Operating System

Windows

**Comment by manikandan-macro** [comment]
we have used AWS Redshift Uses JDBC URL
 connection to connect the Amazon Redsift from DBeaver

**Comment by Destrolaric** [comment]
Tracked in https://github.com/dbeaver/dbeaver/issues/21293

**Comment by Destrolaric** [comment]
Closing the issue as a duplicate, you can track issue resolution in the #21293
