### ISSUE TITLE
Changing of my password

### ISSUE THREAD

**Issue by Joseph18204** [dbeaver/dbeaver#21297]
### Description

Hello,
After installing new version app has changed my password, so now I can't log in.
How can I delete and make new password? 

Sincerely User of DBeaver Program. 

### DBeaver Version

23.2.1

### Operating System

Windows 10

**Comment by MashaKorax** [comment]
Hello, @Joseph18204. Do you mean master password, project password, or database password?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
