### ISSUE TITLE
Cannot connect to Redshift after upgrading to 23.2.1

### ISSUE THREAD

**Issue by esmith1092** [dbeaver/dbeaver#21293]
### Description

After upgrading from DBeaver 23.2.0 to 23.2.1, multiple users are seeing the following error when connecting to the Redshift database. Users still using 23.2.0 are not having any issues connecting to Redshift.

![Screenshot 2023-09-24 at 4 26 53 PM](https://github.com/dbeaver/dbeaver/assets/43520697/b136b6a9-6b8e-49c3-93df-060a658d1cde)

### DBeaver Version

Community Edition 23.2.1

### Operating System

macOS 13.5.2

### Database and driver

redshift-jdbc42 2.1.0.3

### Steps to reproduce

1. Downloaded newest version of DBeaver (23.2.1)
2. Quit and Restart DBeaver (Required for full download)
3. Connect to Redshift DB

### Additional context

https://dbeaver.io/2023/09/24/dbeaver-23-2-1/

Possibly related to the enum changes in today's release

**Comment by knifecake** [comment]
Can confirm this happens after upgrading to version 23.2.1 with Redshift 1.0.56738. Downgrading to [version 23.2.0](https://dbeaver.io/files/23.2.0/) fixes the problem for now.

**Comment by manikandan-macro** [comment]
I have also downgraded the version and it is working now

**Comment by sshtokijin** [comment]
Same problem here (I'm running Windows 11).
DBeaver downgraded to connect to Redshift.

**Comment by pcmasuzzo** [comment]
Downgrading to [23.2.0](https://dbeaver.io/files/23.2.0/) fixes the issue.

**Comment by miguelasse** [comment]
Can anyone comment on how to downgrade via command line for the rpm package in Linux? Is there a way to avoid having to uninstall completely and reinstall?

**Comment by esmith1092** [comment]
@serge-rider When will the fix for this version become publicly available?

**Comment by LonwoLonwo** [comment]
Hello.
Rerelease is available at https://dbeaver.io/files/23.2.1/

**Comment by dangeReis** [comment]
> Hello. Rerelease is available at https://dbeaver.io/files/23.2.1/

Thank you for the quick fix, but why was this a rerelease?  There shouldn't be multiple files with the same version number that behave differently, and it caused some confusion when trying to resolve this for users.  Wouldn't releasing a new version make more sense?

**Comment by jwhipp** [comment]
Also confused by this version number issue, I installed DBeaver via Homebrew today which is a fresh install, the issue remains.   What are the chances you can bump the version so the package managers pick it up?   Otherwise, we'll likely have to install outside of a PM to get it working.

**Comment by armujahid** [comment]
I have Version 23.2.1.202309282157 upgraded from https://archlinux.org/packages/extra/x86_64/dbeaver/ yesterday and I am still getting this issue. it was working fine before the upgrade.

**Comment by Danipiario** [comment]
Please reopen, the issue is still present

**Comment by LonwoLonwo** [comment]
You could try to use our Early Access version or wait till Monday's release.
https://dbeaver.io/files/ea/

**Comment by larshelge** [comment]
On version `23.2.1.202309250303` using the snap package and this issue is (still) present.
