### ISSUE TITLE
Can't connect to any Redshift DB

### ISSUE THREAD

**Issue by cmoschofidis** [dbeaver/dbeaver#21294]
### Description

As of the last update to 23.2.1, I cannot connect to any Redshift database, due to this error
`ERROR: relation "pg_catalog.pg_enum" does not exist`

### DBeaver Version

Community Edition 23.2.1

### Operating System

MacOS Ventura, v. 13.4.1

### Steps to reproduce

1. Tried to connect to existing Redshift Databases after update to DBeaver v. 23.2.1

**Comment by wahlrkr** [comment]
I can confirm this, just upgraded to `Version 23.2.1.202309250303` (MacOS) 😟

**Comment by Destrolaric** [comment]
Tracked in https://github.com/dbeaver/dbeaver/issues/21293

**Comment by Destrolaric** [comment]
Will be closed as a duplicate you can track progress of the issue resolution in the issue above

**Comment by vaishak-m** [comment]
I can confirm that the same issue is present in Windows as well(Windows 11). Current Dbeaver version: 23.2.1.202309250303

**Comment by xpil** [comment]
Same here. Can't connect to any RedShift instance.

**Comment by nikhilsp8** [comment]
same issue is present with Windows 10 Enterprise too

**Comment by regiyev** [comment]
I confirm the same issue. Mac OS 13.6.
DBeaver Version 23.2.1.202309250303 released on 25 Sep 2023.

**Comment by TimSmith-Soaren** [comment]
Confirmed on Windows 10 Pro. DBeaver Version 23.2.1.202309250303

**Comment by xpil** [comment]
> Same here. Can't connect to any RedShift instance.

Btw if anyone is looking for a quick fix, downgrading to 23.2.0 helps.

**Comment by datasurfergtx** [comment]
> > Same here. Can't connect to any RedShift instance.
> 
> Btw if anyone is looking for a quick fix, downgrading to 23.2.0 helps.

Here's the Link: https://dbeaver.io/files/23.2.0/
