### ISSUE TITLE
Backup process

### ISSUE THREAD

**Issue by mpbits** [dbeaver/dbeaver#21302]
**Is your feature request related to a problem? Please describe.**
I just updated to the most recent version and noticed that the whole backup (PostgreSQL dump) GUI process has changed. Now when I click "Proceed" the whole modal dialogue dissapears and the task in moved into the background task. I don't know if this is a bug or by design but I am very annoyed by the new approach. I much preffered the old one.

**Describe the solution you'd like**
Improve the whole backup GUI process to be more interactive with the user.

**Describe alternatives you've considered**
There are none except to accept the new approach which is not the best but it does the job. The lack of feedback about the whole dump process is what bothers me.

**Comment by E1izabeth** [comment]
Thank you for your report

**Comment by uslss** [comment]
Also script execution is broken

https://github.com/dbeaver/dbeaver/assets/31996417/7b8e1dcb-c623-4aad-8783-b4c8a4599b15
