### ISSUE TITLE
23.2.1 update seems to have broken my Redshift connection

### ISSUE THREAD

**Issue by adr-denzel** [dbeaver/dbeaver#21307]
### Description

SQL Error [42P01]: ERROR: relation "pg_catalog.pg_enum" does not exist

Getting this error message on system attempt to connect to Redshift data warehouse instance. 

### DBeaver Version

23.2.1

### Operating System

Windows 10

### Database and driver

com.amazon.redshift.jdbc42.Driver

**Comment by LonwoLonwo** [comment]
Hello @adr-denzel 

Thanks for the report.

The issue was fixed here, and fix will be available soon https://github.com/dbeaver/dbeaver/issues/21293
