### ISSUE TITLE
Error connecting to Redshift database

### ISSUE THREAD

**Issue by bugarce** [dbeaver/dbeaver#21311]
### Description

We have issues when connecting to Redshift database after today we updated dbeaver to the latest version released on 25.Sep.2023

The error is the following: 
SQL Error [42P01]: ERROR: relation "pg_catalog.pg_enum" does not exist
  ERROR: relation "pg_catalog.pg_enum" does not exist
  ERROR: relation "pg_catalog.pg_enum" does not exist

![image](https://github.com/dbeaver/dbeaver/assets/50582902/8853af69-4c4c-4150-afe0-f04105bcecff)

### DBeaver Version

Version 23.2.1.202309250303

### Operating System

Windows 11 Enterprise Version 22H2

### Database and driver

AWS Redshift
Driver: com.amazon.redshift.jdbc42.Driver

![image](https://github.com/dbeaver/dbeaver/assets/50582902/17d9793a-9b3a-46f5-ae19-447fe7999e28)

### Steps to reproduce

When trying an existing or creating a new connection to AWS Redshift database

**Comment by LonwoLonwo** [comment]
Hello  @bugarce 

Thanks for the report.

The issue was fixed here, and fix will be available soon https://github.com/dbeaver/dbeaver/issues/21293

**Comment by LonwoLonwo** [comment]
Hello.
Rerelease is available at https://dbeaver.io/files/23.2.1/
