### ISSUE TITLE
Remove Web browser settings page

### ISSUE THREAD

**Issue by KieranDevvs** [dbeaver/dbeaver#21310]
### Description

I have configured DBeaver to use an external browser to authenticate when connecting to a database. (This was the default setting until the latest release).

![image](https://github.com/dbeaver/dbeaver/assets/21192520/a8c0f5b7-ad21-4b1e-96c1-82c0b77ee35b)

However, in the latest release, the option is ignored and the internal browser is always used regardless of the configuration options.

![image](https://github.com/dbeaver/dbeaver/assets/21192520/94abb4f4-4d23-4cc3-b8e5-a40c2734ea33)

### DBeaver Version

23.2.1

### Operating System

Windows 10

### Database and driver

Azure MSSQL
Microsoft JDBC Driver for SQL Server 11.2.3 JRE 11

### Steps to reproduce

1) Use latest release.
2) Check browser settings to ensure external browser is selected.
3) Try authenticate with a database using `Active Directory - MFA`
2) See internal browser is used.

**Comment by Destrolaric** [comment]
@KieranDevvs Hi, auth in the internal browser is configurable by the `open auth links in the embedded browser` checkbox in User Interface preferences
![image](https://github.com/dbeaver/dbeaver/assets/20579256/7ec853a3-9286-479f-ba29-2d02f228e8d6)

**Comment by KieranDevvs** [comment]
> @KieranDevvs Hi, auth in the internal browser is configurable by the `open auth links in the embedded browser` checkbox in User Interface preferences ![image](https://user-images.githubusercontent.com/20579256/270326140-7ec853a3-9286-479f-ba29-2d02f228e8d6.png)

Ah yes my mistake, thanks for the help.

**Comment by arhayka** [comment]
The page 'User Interface —> Web browser' doesn't work. We need to delete it from Preferences.
