### ISSUE TITLE
Integrating dbeaver ce 23.2.1 in eclipse 2023-09 (4.29.0) opens data table exception

### ISSUE THREAD

**Issue by lyh061619** [dbeaver/dbeaver#21314]
### Description

Integrating dbvehicle ce 23.2.1 in eclipse version: 2023-09 (4.29.0) opens data table exception
![dbeaver-bug](https://github.com/dbeaver/dbeaver/assets/15118571/d49534f4-ff0d-4e86-832e-c9711542065a)

### DBeaver Version

ca 23.2.1

### Operating System

win 10

### Database and driver

mariadb 11
mariadb:mariadb-java-client 3.0.7

**Comment by MashaKorax** [comment]
This should be fixed by this PR https://github.com/dbeaver/dbeaver/pull/21352
