### ISSUE TITLE
Code completion fails

### ISSUE THREAD

**Issue by ufuk-ergin-carbon** [dbeaver/dbeaver#21316]
### Description

Code completion still fails. 

Here is what I did first:
```
select
   bn.full_name,
   to_date(bn.created_at),
   count(bn.id) as count_of_bills,
   count(distinct bn.billID) as distinct_bilnote_count
from production.billnotes bn
group by 1, 2
order by 3 desc;
```
Then I executed the above statement. After the results I went ahead and tried to insert another column after to_date and started typing `bn.`. But, the code completion failed. Here is the screenshot. Also, what I did to restore was this. I went to the connection and right-clicked to "Edit Connection". 
![Screenshot 2023-09-25 at 18 13 53](https://github.com/dbeaver/dbeaver/assets/114302087/041ed37e-ce3b-43b6-9e40-e6f8eb5cae2a)

![Screenshot 2023-09-25 at 18 20 28](https://github.com/dbeaver/dbeaver/assets/114302087/2da03aaf-29dc-4e1d-ba10-4f02a6e9b27d)

Then from there I clicked on SQL Editor and Code Completion. I clicked on Datasource "ANALYTICS_PRODUCTION" Settings and disabled Enable experimental settings.

### DBeaver Version

Version 23.2.1.202309250303

### Operating System

MacOS Ventura 13.5.2

### Database and driver

Database name and version: Snowflake 7.33.1
Driver name and version: Snowflake 3.13.30

### Steps to reproduce

![Screenshot 2023-09-25 at 18 13 53](https://github.com/dbeaver/dbeaver/assets/114302087/38fb7723-4361-424e-8770-d42a604654fd)

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by ems2811** [comment]
Similar problem:
Postgresql 9.5 or 15
Bug in 23.2.1, doesn't reproduce in 23.2.0

```
/*
drop table if exists tab_1;
drop table if exists tab_2;

create table tab_1
	(id serial primary key,
	code text,
	name text,
	ext_id int);

create table tab_2
	(id serial primary key,
	code text,
	name text);
*/

select t1. --<-- here press ctrl+space - no proposals
	exists (select 1
		from tab_2 t2
		where t2.id =t1.ext_id) --<-- if delete this subquery - works fine
from tab_1 t1
```

**Comment by ufuk-ergin-carbon** [comment]
Update: 

code completion still fails despite the settings in the screenshot. Attached is the video for when it broke.
<img width="1260" alt="Screenshot 2023-09-26 at 14 48 19" src="https://github.com/dbeaver/dbeaver/assets/114302087/a11aff9b-626b-466c-bd89-4d6e137664f7">

https://github.com/dbeaver/dbeaver/assets/114302087/685c7a38-9156-4821-99a0-9012faef3cf9

**Comment by E1izabeth** [comment]
@ufuk-ergin-carbon that looks strange.
Does it reproducible on other databases (if you have some to try)?
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by ufuk-ergin-carbon** [comment]
> @ufuk-ergin-carbon that looks strange. Does it reproducible on other databases (if you have some to try)? Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

Unfortunately I have no other database to try :(

[dbeaver-debug-1695654504290.log](https://github.com/dbeaver/dbeaver/files/12727225/dbeaver-debug-1695654504290.log)
[dbeaver-debug-1695718066363.log](https://github.com/dbeaver/dbeaver/files/12727226/dbeaver-debug-1695718066363.log)
[dbeaver-debug-1695719696875.log](https://github.com/dbeaver/dbeaver/files/12727227/dbeaver-debug-1695719696875.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/12727228/dbeaver-debug.log)

Here are the log files. Let me know if these are the ones you're talking about.

**Comment by E1izabeth** [comment]
These are the files I asked for, yes. Thank you.

**Comment by ufuk-ergin-carbon** [comment]
Hey folks, how can I help you reproduce this issue? This is just happened and it's really a show stopper having to quit the application and reopen it with many results tab open. It does not have a systematic way of breaking. It is most certainly breaking after a time of inactivity. But then I cannot restore it even though I try Invalidate/Reconnect or righ-click on the schema and click Refresh. It is really frustrating.

**Comment by E1izabeth** [comment]
Does it still reproducible on the latest DBeaver version?

**Comment by ufuk-ergin-carbon** [comment]
> Does it still reproducible on the latest DBeaver version?
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/13497194/dbeaver-debug.log)

Hello E1izabeth, yes it can be reproducible. I am attaching the log file. Also attaching the screen recording where it failed after I left the Dbeaver open overnight. Now, I had the external authentication step passed with external browser. Everything should have worked correctly. Let me know if you need anything else.

https://github.com/dbeaver/dbeaver/assets/114302087/f7251937-df19-4894-888a-93320170c279

**Comment by LonwoLonwo** [comment]
Hello @ufuk-ergin-carbon 

I'm sorry, but it's unclear to me - did you reconnect and then try to use auto-completion? 
Did the auto-completion work before reconnecting?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by ufuk-ergin-carbon** [comment]
This issue is not happening anymore it looks like. If it reappears, I'll let you folks know. Thanks!
