### ISSUE TITLE
Only the first resultset displays when running selected multi-line statements. 

### ISSUE THREAD

**Issue by BILL-ZHOU-BILL** [dbeaver/dbeaver#2132]
When I selected multiple-line text in SQL editor and ran the selected text as statement instead of script, only the first result set was diaplayed.  I verified the case in ORACLE sqldeveloper, it worked well and displayed all result sets correctly.

For example, select the following sql statements all and click "Execute SQL Statement" button.

select 1 from dual;
select 2 from dual;
select 3 from dual;

**Comment by serge-rider** [comment]
You can execute it as script (<kbd>ALT+X</kbd>).
Then you will see all results.

**Comment by BILL-ZHOU-BILL** [comment]
Yes, that's a way. 
But I hope the statement execution also does work as same as oracle client.
Just make a little change in SQLEditor.processSQL() to fix it, run the lines in script mode if the selected text is not null.
