### ISSUE TITLE
[PERFORMANCE] "Detect Unique Idetifiers" takes forever

### ISSUE THREAD

**Issue by yiding-he** [dbeaver/dbeaver#21335]
### Description

When open data tab for a table of MySQL database, it took forever waiting for "Detect unique idetifiers". And that table has a primary key.
![屏幕截图 2023-09-27 104622](https://github.com/dbeaver/dbeaver/assets/900606/6f194654-26a5-4972-b583-8dbeb130acc1)

### DBeaver Version

CE 23.2.1

### Operating System

Windows 11

### Database and driver

- Server: MySQL [8.0.18]
- Driver: MySQL Connector/J [mysql-connector-java-8.0.29 (Revision: dd61577595edad45c398af508cf91ad26fc4144f)]

### Steps to reproduce

1. Open connection to database;
2. Navigate to a table which has a primary key;
3. Switch to data tab.

### Additional context

Stack trace log is here: [stack.log](https://github.com/dbeaver/dbeaver/files/12800003/stack.log)

When this happened again I checked the active sessions from the server side and found this:

![Tt8BpPfJZw](https://github.com/dbeaver/dbeaver/assets/900606/077d167f-999e-4a05-a969-d7acb7eece1f)

It took minutes to execute this "checking pemissions" operation:

```sql
/* ApplicationName=DBeaver 23.2.1 - Metadata */ SELECT kc.CONSTRAINT_NAME,kc.TABLE_NAME,kc.COLUMN_NAME,kc.ORDINAL_POSITION
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE kc WHERE kc.TABLE_SCHEMA='xz_project_information' AND kc.REFERENCED_TABLE_NAME IS NULL AND kc.TABLE_NAME='project'
ORDER BY kc.CONSTRAINT_NAME,kc.ORDINAL_POSITION
```

**Comment by LonwoLonwo** [comment]
Hello @yiding-he 

Could you please provide your table DDL?

ALso, could you please try to generate a thread dump and attach it here? Here is the instruction: https://dbeaver.com/docs/wiki/Making-a-thread-dump/
Thank you.

**Comment by yiding-he** [comment]
Hi @LonwoLonwo ,
Strangely, I no longer observe this issue after relaunching DBeaver. Is there any way I can print a thread dump when this happens again?

**Comment by LonwoLonwo** [comment]
You can create a new ticket for this. Or you can add your message here. I will close it for now, but if you come up with more details, I can reopen it if that's okay with you.

**Comment by yiding-he** [comment]
@LonwoLonwo Hi, I have added additional context about this issue.
