### ISSUE TITLE
Stuck when saving changes

### ISSUE THREAD

**Issue by ronnifadhlillah** [dbeaver/dbeaver#21336]
### Description

Loading with long respond (or maybe not responding) or stuck when i save after create column. It's bug ?. proofing video / screen capt is attach 

https://github.com/dbeaver/dbeaver/assets/33772449/4906f28d-1248-4ad6-8e92-19785acaefa0

### DBeaver Version

EE / Enterprise 23.2.0

### Operating System

Windows 11

### Database and driver

Database name and version : MariaDB 10.3.16
Driver name : Mariadb Connector/J 3.0.7

### Steps to reproduce

1.  I want to create new column in table login such as "initial" with varchar data type.
2.  Then i want to commit my change so i click save.
3. Then DBeaver stuck. for 1 minutes and still stuck then.

**Comment by LonwoLonwo** [comment]
Hello @ronnifadhlillah 

What type of transaction mode do you have?

![2023-09-27 09_49_34-DBeaver Ultimate 23 2 1 - newtable_1](https://github.com/dbeaver/dbeaver/assets/45152336/87629c82-6cff-43af-8d24-879ffa2e6542)

Could you please try to generate a thread dump and attach it here? Here is the instruction: https://dbeaver.com/docs/wiki/Making-a-thread-dump/

Thank you.

**Comment by ronnifadhlillah** [comment]
Hallo lonwo.

thx for response . here it's the capture of transaction type (attached).
![image](https://github.com/dbeaver/dbeaver/assets/33772449/2acbcbce-2bb2-4e3a-94f3-51a7dda1ebe4)

Then this is the capture of thread dump. i thing i can't generate thread dump cz java is not installed is my computer. 
![image](https://github.com/dbeaver/dbeaver/assets/33772449/f3be3d97-5081-42e3-bd48-f833a66fa26b)

**Comment by ronnifadhlillah** [comment]
Hello team.

So any update of this issued ?

Thank you

**Comment by Destrolaric** [comment]
@ronnifadhlillah Sorry for the long wait. You can find `jstack` in your DBeaver installation. The default location for the installation is:
`C:\Users\{user}\AppData\Local\DBeaverEE`
there you can open the `jre\bin` folder
After that, you can find `jstack` there.

**Comment by ronnifadhlillah** [comment]
Hallo @Destrolaric @LonwoLonwo  ,

Thank you for an advice or solution. i've been finish generating a thread dump. 
So, the thread dump is on attach below. and start discuss bout this issue.

[thread-dump.txt](https://github.com/dbeaver/dbeaver/files/13455171/thread-dump.txt)


by the way, thank you.

**Comment by hrimthrusa** [comment]
@ronnifadhlillah Hello, could you please sent us the link to this ticket in an email to **support@dbeaver.com** so we can create a support ticket for you?

Apologies it is taking so long.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and write a letter to our support team.
