### ISSUE TITLE
PostgreSQL: Data tab in Table view leaves a stale ShareAccessLock after closed

### ISSUE THREAD

**Issue by char101** [dbeaver/dbeaver#21349]
### Description

Clicking on the Data tab in the Table view tab leave a ShareAccessLock on the table after the Table view tab is closed. This prevents dropping the table.

### DBeaver Version

Community Edition 23.2.1.202309250303

### Operating System

Windows 10

### Database and driver

1. PostgreSQL 16.0
2. PostgreSQL JDBC 42.6.0

### Steps to reproduce

Test case:
1. Create a test table
1. Open a table view for that table
2. Click the Data tab
3. Close the table view
4. Drop the table -> hang

Running `select relation::regclass, * from pg_locks` shows a `AccessShareLock` over the table.

**Comment by MashaKorax** [comment]
Hello @char101. What type of transaction mode do you have?
![dbeaver_AgjFloO0bC](https://github.com/dbeaver/dbeaver/assets/84867187/bca19591-b1b5-4522-b6ff-375e09879661)

**Comment by char101** [comment]
Here it is. The database is a development type.

![2023-09-28 20_38_15-](https://github.com/dbeaver/dbeaver/assets/71255/53f84f61-f18a-4e10-a6c9-7351c6cb5812)

**Comment by LonwoLonwo** [comment]
Hello @char101 

For now, I can't reproduce it.

Could you please provide screens for these settings of your connection:

![2023-11-02 11_43_11-Connection _postgres 6 1_ configuration](https://github.com/dbeaver/dbeaver/assets/45152336/ed673af7-2194-4bd4-901f-96ef5c33f713)

![2023-11-02 11_43_27-Connection _postgres 6 1_ configuration](https://github.com/dbeaver/dbeaver/assets/45152336/17e61c4e-bbf5-468e-b574-d87855b34d0c)

![2023-11-02 11_42_50-Connection _postgres 6 1_ configuration](https://github.com/dbeaver/dbeaver/assets/45152336/e359e4df-a503-471d-8d6c-303bd68bef6f)

**Comment by char101** [comment]
These are the settings

![2023-11-02 17_04_29-Connection _stock2_ configuration](https://github.com/dbeaver/dbeaver/assets/71255/27426225-1e94-4ac2-b9c3-df7e53f1dad4)
![2023-11-02 17_04_37-Connection _stock2_ configuration](https://github.com/dbeaver/dbeaver/assets/71255/bef92bef-e735-4471-8a14-b47661b569a7)
![2023-11-02 17_04_47-Connection _stock2_ configuration](https://github.com/dbeaver/dbeaver/assets/71255/90785ea6-d7cf-4352-918e-fc4574995850)

**Comment by char101** [comment]
These are the locks after opening the data view for a table named `sector` and then closing it

```sql
select * from pg_locks pl left join pg_stat_activity psa on pl.pid = psa.pid where pl.relation::regclass::text = 'sector'
```

|locktype|database|relation|page|tuple|virtualxid|transactionid|classid|objid|objsubid|virtualtransaction|pid|mode|granted|fastpath|waitstart|datid|datname|pid|leader_pid|usesysid|usename|application_name|client_addr|client_hostname|client_port|backend_start|xact_start|query_start|state_change|wait_event_type|wait_event|state|backend_xid|backend_xmin|query_id|query|backend_type|
|--------|--------|--------|----|-----|----------|-------------|-------|-----|--------|------------------|---|----|-------|--------|---------|-----|-------|---|----------|--------|-------|----------------|-----------|---------------|-----------|-------------|----------|-----------|------------|---------------|----------|-----|-----------|------------|--------|-----|------------|
|relation|228528|229082||||||||6/224364|622032|AccessShareLock|true|true||228528|stock2|622032||10|char|DBeaver 23.2.1 - Main <stock2>|127.0.0.1||54889|2023-11-02 17:06:40.116 +0700|2023-11-02 17:06:40.384 +0700|2023-11-02 17:06:40.392 +0700|2023-11-02 17:06:40.392 +0700|Client|ClientRead|idle in transaction||864577||SELECT c.oid, a.attnum, a.attname, c.relname, n.nspname, a.attnotnull OR (t.typtype = 'd' AND t.typnotnull), a.attidentity != '' OR pg_catalog.pg_get_expr(d.adbin, d.adrelid) LIKE '%nextval(%' FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON (c.relnamespace = n.oid) JOIN pg_catalog.pg_attribute a ON (c.oid = a.attrelid) JOIN pg_catalog.pg_type t ON (a.atttypid = t.oid) LEFT JOIN pg_catalog.pg_attrdef d ON (d.adrelid = a.attrelid AND d.adnum = a.attnum) JOIN (SELECT 229082 AS oid , 1 AS attnum UNION ALL SELECT 229082, 2 UNION ALL SELECT 229082, 3 UNION ALL SELECT 229082, 4 UNION ALL SELECT 229082, 5) vals ON (c.oid = vals.oid AND a.attnum = vals.attnum) |client backend|

**Comment by LonwoLonwo** [comment]
"idle in transaction", I see.

You can read an extensive discussion about it here: https://github.com/dbeaver/dbeaver/issues/8303

Maybe changing the Connection Type to Production or Metadata -> Open Separate Connection to "Never" will help in your case.

**Comment by char101** [comment]
> Maybe changing the Connection Type to Production or Metadata -> Open Separate Connection to "Never" will help in your case.

I can confirm that this works. Thank you.

**Comment by LonwoLonwo** [comment]
Thanks for the update.
