### ISSUE TITLE
Incorrect data type length in creation DDL when exporting table to a new table

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#21355]
### Description

1. create a table with CHAR column. Default length is set to 100, max is 254
```
CREATE TABLE APP.NEWTABLE (
	COLUMN1 CHAR(100)
);
```
2. start export to a new table: table's context menu -> Export Data -> Select the Database export type , insert new table name
![image](https://github.com/dbeaver/dbeaver/assets/43252954/37d0bc3e-c065-40ae-939a-ccd56b184555)
3. Proceed
![image](https://github.com/dbeaver/dbeaver/assets/43252954/6832c502-e07a-44d5-b204-8ff38d5f0ad6)
Actual result: CHAR in creation DDL has wrong length

### DBeaver Version

23.2.1

### Operating System

win10

**Comment by LonwoLonwo** [comment]
It is influenced by Data Transfer settings (Max data type length). But this setting should have influence only if it was changed.
