### ISSUE TITLE
error occurred when startup

### ISSUE THREAD

**Issue by ken73chen** [dbeaver/dbeaver#21356]
### Description

This happens since Community Edition 23.2.0. After DBeaver splash screen, just a small dialog window shows  the error messages.  No problem before dbeaver-ce-23.1.5.

![螢幕擷取畫面 2023-09-28 161909](https://github.com/dbeaver/dbeaver/assets/37667318/410fefab-2e02-4055-ae9d-5a0a405cf24f)

[1695888661767.log](https://github.com/dbeaver/dbeaver/files/12747330/1695888661767.log)

### DBeaver Version

Community Edition 23.2.1

### Operating System

Windows 10

### Steps to reproduce

1. Click dbeaver icon to launch
2. A small dialog show 'An error has occuirred. See the log file ...'

![螢幕擷取畫面 2023-09-28 161909](https://github.com/dbeaver/dbeaver/assets/37667318/410fefab-2e02-4055-ae9d-5a0a405cf24f)

**Comment by MashaKorax** [comment]
duplicate https://github.com/dbeaver/dbeaver/issues/21228

**Comment by Destrolaric** [comment]
@ken73chen Hi, could you specify is 
`C:\Users\kenchen\AppData\Roaming\DBeaverData`
an existing directory?

**Comment by ken73chen** [comment]
> @ken73chen Hi, could you specify is `C:\Users\kenchen\AppData\Roaming\DBeaverData` an existing directory?

No, it's an old file. And after removing this file, this problem is gone.

Thanks.

![螢幕擷取畫面 2023-10-11 100410](https://github.com/dbeaver/dbeaver/assets/37667318/44b476be-de8a-47d3-bd1f-9296a3ca0071)
