### ISSUE TITLE
Command line parameter "-vmargs" not working

### ISSUE THREAD

**Issue by AdrianoBortoloto** [dbeaver/dbeaver#21363]
### Description

When use the -vmargs parameter, i.e. -vmargs -Xmx2048m, Dbeaver does not start
Example:

`%USERPROFILE%\DBeaver\dbeaver_current\dbeaver.exe -reuseWorkspace -nl en -vmargs -Xmx2048m`

After this command, shows a popup:

![image](https://github.com/dbeaver/dbeaver/assets/12927584/3a2c7cc9-e57d-41cf-83a2-ed3d709e1d79)

If the -vmargs is removed, Dbeaver starts with no issues:
%USERPROFILE%\DBeaver\dbeaver_current\dbeaver.exe -reuseWorkspace -nl en

### DBeaver Version

Community Edition 23.2.1

### Operating System

Windows 11

### Database and driver

No issues with databases and drivers.

### Steps to reproduce

1. Run the command line:
%USERPROFILE%\DBeaver\dbeaver_current\dbeaver.exe -reuseWorkspace -nl en -vmargs -Xmx2048m
2. A popup is shown instructing you to check the log. Dbeaver does not start.
![image](https://github.com/dbeaver/dbeaver/assets/12927584/c29c7b3b-0422-471a-aab9-c5eaa9b522d7)

3. Run the command line without the -vmargs:
%USERPROFILE%\DBeaver\dbeaver_current\dbeaver.exe -reuseWorkspace -nl en
4. Dbeaver starts with no issues.

### Additional context

The command line is executed by the shortcut pinned to the Windows taskbar.

**Comment by MashaKorax** [comment]
Hello, @AdrianoBortoloto . Thanks for your report. 

We have a similar ticket in the current sprint. It should work from version 23.2.2

**Comment by uslss** [comment]
#21299

**Comment by LonwoLonwo** [comment]
Could you please download the latest EA version and see if the issue is gone there?
https://dbeaver.io/files/ea/

**Comment by AdrianoBortoloto** [comment]
> Could you please download the latest EA version and see if the issue is gone there? https://dbeaver.io/files/ea/

I updated to 23.2.2 right now and the issue is gone. Thanks!

**Comment by LonwoLonwo** [comment]
Thanks for the update @AdrianoBortoloto
