### ISSUE TITLE
Added Firebird Extra Keywords

### ISSUE THREAD

**Issue by LuanNadaletti** [dbeaver/dbeaver#21362]
Fix for Firebird some keywords aren't highlighted. Added more keywords.

**Comment by LonwoLonwo** [comment]
Please provide the required list of keywords that you want to see. Link on documentation will also be beneficial.

**Comment by LuanNadaletti** [comment]
I will implement it on my own. Can I make a pull request?

And about the documentation, do you mean the firebird documentation?
