### ISSUE TITLE
GUI default collation is not set as my.ini

### ISSUE THREAD

**Issue by bsienn** [dbeaver/dbeaver#2137]
System: Fedora 26
Database: MariaDB

Hi, I have set chat and collation to utf8mb4 for both under 

[mysqld]
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci

I have restarted mariadb.
If I create db from command line it does create using unicode_ci

But dbeaver by default shows ctf8_general_ci while creating new database. How do I change this?
The config file is suppose to overwrite the default collat.

I changed `/var/my.cnf.d/mariadb-server.cnf`

**Comment by serge-rider** [comment]
You can change character encoding for connection in driver properties:
![image](https://user-images.githubusercontent.com/6398845/30394678-74de1a94-98cc-11e7-82ba-b263e190004b.png)

**Comment by bsienn** [comment]
There is no list of option.

![screenshot from 2017-09-19 11-12-25](https://user-images.githubusercontent.com/3149876/30578130-bc42a5a4-9d2b-11e7-9e8f-45b145a0f7f0.png)

**Comment by bsienn** [comment]
BTW Is there an option to export schema only?
Also the backup options doesn't export stored procedures.

**Comment by serge-rider** [comment]
MariaDB drivr does't support this option (see https://mariadb.com/kb/en/library/about-mariadb-connector-j/). However you can add any driver properties: right click on User Properties->Add new property.
And you could use MySQL driver.

Please create separate tickets for data export (and please clarify what is "export schema only").

**Comment by serge-rider** [comment]
It is still not very clear - what exactly are you trying to achieve?
DBeaver doesn't use information from `my.ini`. And MariaDB doesn't need explicit charset in connection properties.

**Comment by tati-kru** [comment]
hi @bsienn 
Do you have any updates about this issue?

**Comment by bsienn** [comment]
@tati-kru Hi, I tried to be as much clear I could but I don't know the reason why serger-rider isn't able to understand. Its a very generic feature which popular DB Tools already have by default. Sorry I don't have any solution for this myself.

**Comment by tati-kru** [comment]
@bsienn thank you any way. We will try to figure out what we can do with this.

**Comment by serge-rider** [comment]
DBeaver uses `SHOW CHARSET` and `SHOW COLLATION` to read the list of available charsets and collations.

**Comment by bsienn** [comment]
Hi @serge-rider, sorry for late reply, was out of town.
I just want the create database feature to have a default charterset populated by default of user specified choice.

At the moment the app have defaults set to utf8_general_ci
I want them to be utf8mb4_unicode_ci by default and persist.

DBforge uses the my.ini setting and populate the charcterset which is defended in the file.
dbvearr should persist the charset and collation of what user defines.

If this doesn't help, please close this issue.

**Comment by serge-rider** [comment]
You can't set utf8mb4_unicode_ci collation for utf8 charset.
But you can switch to utf8mb4 charset:
![image](https://user-images.githubusercontent.com/6398845/35490644-2bb4714a-04b2-11e8-97a9-3168861d196f.png)

Also I've made charset/collation fields editable so you can enter any value there.

**Comment by the-ge** [comment]
Question: is there any way to have `utf8mb4` and `utf8mb4_unicode_ci `as defaults for the 'Create new database' dialog (instead of `utf8` and `utf8_general_ci`) ?

**Comment by tati-kru** [comment]
@the-ge please create a new ticket for your request
