### ISSUE TITLE
Code completion for update statements

### ISSUE THREAD

**Issue by wheinen** [dbeaver/dbeaver#21373]
### Description

We only use MySQL, so I'm not sure if this issue happens with other databases.

When typing an update query, with the previous version (23.2.0) you would get autocompletion when you used an alias. This was already a step down from earlier in version 23.1.x when you had autocomplete even without an alias.

Now, however, autocomplete doesn't work at all anymore when you type an update query. Look at my examples below. The same query has autocomplete with a select query, but not with an update query.

![image](https://github.com/dbeaver/dbeaver/assets/137804655/6de5c6c4-adc2-4b34-b421-f5f07dc0d823)
![image](https://github.com/dbeaver/dbeaver/assets/137804655/75cb81b9-79b9-4036-8c77-f0275a95681e)

This happens on joins, but also on where-statements:
![image](https://github.com/dbeaver/dbeaver/assets/137804655/055cea19-2812-43dc-aa33-b74dbd8f0f4b)

Could this please be fixed? This makes typing query's so much harder. 
If possible, could the autocomplete also work without a required alias like it did in version 23.1.x?

Thanks in advance!

### DBeaver Version

23.2.1

### Operating System

Windows 10

### Database and driver

MySQL 8
com.mysql.cj.jdbc.Driver
8.0.29

### Steps to reproduce

Type an update query, and try to autocomplete a join or where-statement

**Comment by E1izabeth** [comment]
Thank you for bug report. Does turning this setting off help?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/b7131004-ed55-4d14-a275-2ed16ef44ecc)

**Comment by wheinen** [comment]
Oh, whoops! It does! 😄 
Thank you very much, this makes my life so much easier. I should've known enabling experimental features could lead to bugs like these 😅

**Comment by E1izabeth** [comment]
Thank you for update. Let's keep this issue open as we want to fix it when this setting is on :)

**Comment by nicofari** [comment]
Hi 
unfortunately I am experiencing the very same problem, and have experimental feature enabled already!
my version is Version 23.2.1.202309260508 on Ubuntu 18.04
thanks for any tips/help

**Comment by E1izabeth** [comment]
@nicofari 
Please provide a query example to reproduce.

**Comment by nicofari** [comment]
For SELECTs it works, the problem is for UPDATE
try to upload a screenshot
![Screenshot from 2023-10-06 12-56-32](https://github.com/dbeaver/dbeaver/assets/6568988/b123e5bc-1b1c-4379-b656-77df0ee72abc)

**Comment by nicofari** [comment]
at the cursor appears "no proposal"

This is my preference setup:

![Screenshot from 2023-10-06 12-42-00](https://github.com/dbeaver/dbeaver/assets/6568988/87b5bc47-1992-4488-859b-84d57b49fefc)

**Comment by nicofari** [comment]
I tried to activate "hippie engine" (don't know what is it actually) but the problem remains

**Comment by nicofari** [comment]
Ah! there is a difference actually: I am using MySql 5.7
perhaps catalog views are different?

**Comment by E1izabeth** [comment]
Please uncheck the option `Enable experimental features`. Autocompletion in update queries is not working with turned it on.
We're going to fix it, but that is a workaround for now.

**Comment by nicofari** [comment]
Okkk it works thank you very much :+1:
