### ISSUE TITLE
Tables are not shown in the menu 

### ISSUE THREAD

**Issue by isoctcolo** [dbeaver/dbeaver#21383]
### Description

It looks like there are no tables but there are when you click on the table section.
It is working in 23.2.0 - after update to 23.2.1 the bug appeared.

<img width="1307" alt="Screenshot 2023-09-29 at 14 06 29" src="https://github.com/dbeaver/dbeaver/assets/102313029/4be2b9eb-825a-4b8b-9dea-ac3fc7be70f9">

### DBeaver Version

Community Edition 23.2.1

### Operating System

macos ventura 13.6

### Steps to reproduce

1. connect to the database 
2. open schema 
3. try to open the table menu (no tables visible)

**Comment by isoctcolo** [comment]
Reinstalled 23.2.0 and the bug is gone - Just to verify.

**Comment by LonwoLonwo** [comment]
Hello @isoctcolo 

Maybe there were some filters for the navigator tree or connection.

Could you reproduce this issue now?

**Comment by isoctcolo** [comment]
In 23.2.2 this is working again

**Comment by derman10** [comment]
Version 24.0.4 macOS don't show table list in Schema (MS SQL)
