### ISSUE TITLE
Chinese characters in the MySQL dump task progress log are displayed as garbled characters

### ISSUE THREAD

**Issue by bianyun** [dbeaver/dbeaver#21391]
### Description

When executing a MySQL dump task, localized Chinese characters in the progress log are displayed as garbled characters.

<img width="788" alt="Snipaste_2023-09-30_01-37-15" src="https://github.com/dbeaver/dbeaver/assets/4619776/151bdb84-5b02-4f29-9a2b-3a20af941213">

### DBeaver Version

Community Edition 23.2.1

### Operating System

Windows 11 Professional Edition (Simplified Chinese), 22H2

### Database and driver

1. Database name and version: MySQL 5.7
2. Driver name and version: mysql-connector-java 5.1.44

**Comment by serge-rider** [comment]
Will be fixed in https://github.com/dbeaver/pro/issues/1905

**Comment by serge-rider** [comment]
@bianyun thank you for the contribution!
We fixed this issue in different PR in almost identical way as you proposed. As the change was needed for all products including https://github.com/dbeaver/cloudbeaver we have to do it in a unified fashion.

Fix will be available in 23.2.3
