### ISSUE TITLE
"Failed to create the part's controls" trying to open the database table view (grid)

### ISSUE THREAD

**Issue by nekobito1** [dbeaver/dbeaver#21393]
### Description

I just updated eclipse DBeaver plugin to 23.2.1, and I'm no longer able to open any database objects(schema, tables, procedures...) to view DDL or data (grid).  New and existing SQL scripts are fine.
![Screenshot 2023-09-29 at 12 55 24 PM](https://github.com/dbeaver/dbeaver/assets/51795337/9be3d8a5-647e-4d0f-85ce-23c2661f553a)
[dbeaver_plugin_exception.txt](https://github.com/dbeaver/dbeaver/files/12771404/dbeaver_plugin_exception.txt)

### DBeaver Version

23.2.1

### Operating System

macOS Ventura 13.6

### Database and driver

MySQL 8.0.30
com.mysql.cj.jdbc.Driver (Driver for MySQL 8 and later)

### Steps to reproduce

I'm connected to my local MySQL db fine, and I browse via the Database Navigation and double-click on a table to open, and that is when I get the error in the screenshot attached to the description.

**Comment by nekobito1** [comment]
I was able to revert to the previous DBeaver plugin version 23.1.5, and I can view the database objects again. 

In case anyone else needs to revert, here are the steps to revert.
In Eclipse, go to "Help",  "Install New Software...", then click on "What is already installed" where you can view the installation details.  Go to "Installation History" tab to select the date/time when you had the working version.    Click "Revert".  

![Screenshot 2023-09-29 at 8 55 21 PM](https://github.com/dbeaver/dbeaver/assets/51795337/094b72c3-937e-4497-b470-fe069030345a)

**Comment by LonwoLonwo** [comment]
Hello @nekobito1 

Probably, it was fixed here: https://github.com/dbeaver/dbeaver/issues/21237.

Please, try to check the early access version: https://dbeaver.io/files/ea/update/ce/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by nekobito1** [comment]
Hi, Very sorry I did not get to this sooner.  I did get a new plugin version today (DBeaver 23.2.3.202310221533), and everything works for me.  Thank you for fixing this!
