### ISSUE TITLE
4.2.0 database navigator shows union of all schemas

### ISSUE THREAD

**Issue by c42f** [dbeaver/dbeaver#2139]
I have an MS SQL Server connection, with twenty or so databases.  These have widely different schemas per database (as listed in MS SQL management studio).  However, the dbeaver database navigator is showing every database as having the same schemas (see example screenshots of two *different* databases ("Admin" and "Client")).  The schemas shown appear to be the union of all schemas on the server.

Version: dbeaver version 4.2.0 on ubuntu 16.04 LTS

A colleague using dbeaver version 4.1.0 didn't seem to have this problem.

![admin_schemas](https://user-images.githubusercontent.com/601473/30361616-6260f6a6-989b-11e7-9dbe-adcf92aeefac.png)
![client_schemas](https://user-images.githubusercontent.com/601473/30361621-690f8044-989b-11e7-8337-65d6c59cc0c6.png)

**Comment by serge-rider** [comment]
Most likely your colleague use Microsoft driver while you are using jTDS driver. They are a bit different (execute different queries to read system metadata).

**Comment by c42f** [comment]
Thanks for the reply.

I've checked out the dbeaver source and built both 4.1.0 and master.  Both seem to show the same behavior so you're probably right that this isn't the issue.  I am using the jTDS driver.

However, the underlying problem remains that the schemas appear to be showing up incorrectly.  Do you have any advice about how to pursue this further, and where to look to determine whether this is a problem with dbeaver or with an upstream library?

**Comment by serge-rider** [comment]
Please check 4.3+ version. 
Schema list reading was fixed and redesigned (no matter what driver do you use)
