### ISSUE TITLE
Secret cannot be null error even though it's optional when logging in

### ISSUE THREAD

**Issue by ganort** [dbeaver/dbeaver#21400]
### Description

Similar to issue #19966.
When using the latest driver (Salesforce-CDP-jdbc-1.19.2.jar) we get "Secret cannot be null error".
As per above ticket, we have tried to roll back to 1.11.0 version as well as 1.16.0 version to no avail.

### DBeaver Version

23.2.1

### Operating System

Windows 10

### Database and driver

Salesforce CDP - JDBC

### Steps to reproduce

connect to Salesforce CDP using the username and password only.

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/12781544/dbeaver-debug.log)
![DB CDP Client Secret cannot be null](https://github.com/dbeaver/dbeaver/assets/146710762/f4922279-54ec-4275-99fa-c40d0227c46e)

**Comment by LonwoLonwo** [comment]
Hello @ganort 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by ganort** [comment]
Ciao @LonwoLonwo 

I updated original case comment with requested information.

**Comment by LonwoLonwo** [comment]
Ok. Could you please provide me a screen from your connection settings -> driver settings -> libraries 
with the driver version 1.10 or 1.16?

**Comment by ganort** [comment]
Good morning.  
Here is a screenshot of the 3 different drivers I've tried:  I have not tried 1.10.0 version though and I cant seem to find this version downloadable.  Thoughts in regards?
![image](https://github.com/dbeaver/dbeaver/assets/146710762/6007b550-964a-4821-a3c8-30cd6fdd63b9)

**Comment by LonwoLonwo** [comment]
Did you remove the 1.19.2 version from the libraries section before using 1.16? Just one version can be there.

**Comment by ganort** [comment]
Correct.  I've tried each of the above individually one at a time.

**Comment by ganort** [comment]
For what it is worth the older drivers give a different "Authentication Error" this is the error log for 1.16:
![image](https://github.com/dbeaver/dbeaver/assets/146710762/be8f2549-7ce0-49a5-94f1-4373f48b5aaa)

**Comment by LonwoLonwo** [comment]
Ok. But why do you think the "authentication failure" from your last error log - is not an authentication failure?

**Comment by ganort** [comment]
Yikes.  Well, honestly because I'm system admin, so I didn't consider the obvious. 
But yep.  Seems I locked my account.  That sorted, the 1.16.0 driver works just fine.  
I was too quick to assume that the updated 1.19.2 driver was required.
How embarrassing!  Can we delete this ticket and remove it from existence?  :)

**Comment by LonwoLonwo** [comment]
We just pretended that we didn't see it 🥷
