### ISSUE TITLE
NullPointerExeption in result's column when null expected

### ISSUE THREAD

**Issue by maks56893** [dbeaver/dbeaver#21425]
### Description

When I trying to execute this query:

SELECT (toDate(JSONExtract(jsonData, 'very_bad_date_val', 'String')))
FROM test_db 

I got this in result
![image](https://github.com/dbeaver/dbeaver/assets/61263947/1b33e3bb-0918-4122-9514-cbfa01f06acc)

### DBeaver Version

Community Edition 23.2.1.202309250303

### Operating System

Ubuntu 22.04

### Database and driver

Database - Clickhouse 21.10.2.15
Driver - clickhouse-jdbc 0.4.6

### Steps to reproduce

1. Add json with string field with invalid date 
2. Try to execute query

**Comment by LonwoLonwo** [comment]
Hello @maks56893 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

And minimum example of data to reproduce.

**Comment by LonwoLonwo** [comment]
I can not reproduce with the correct value:

![2023-10-05 10_42_31-DBeaver Ultimate 23 2 2 - _default 1_ Script-126](https://github.com/dbeaver/dbeaver/assets/45152336/3d5f1bab-5bdd-4d9a-b830-9d6b36484665)

And with incorrect value:

![2023-10-05 10_43_29-DBeaver Ultimate 23 2 2 - _default 1_ Script-126](https://github.com/dbeaver/dbeaver/assets/45152336/76ca24a8-41e8-4f7a-846c-74474d4b9d90)

**Comment by maks56893** [comment]
@LonwoLonwo here is log file
[log.log](https://github.com/dbeaver/dbeaver/files/12817930/log.log)

Here is my json from db
{"very_bad_date_val":"202asdasd3-08-12"}

If  I trying parse this json directly from function, i got sql error. Maybe it can be reproduced only from database? 

Queries for create database and inserting, which I used
CREATE TABLE test_db.test_table
(
    `id` String,

    `jsonData` Nullable(String)
)
ENGINE = MergeTree
PARTITION BY (id)
ORDER BY (id);

INSERT INTO test_db.test_table (*)
VALUES ('test', '{"very_bad_date_val":"202asdasd3-08-12"}')

**Comment by LonwoLonwo** [comment]
Still can not reproduce.

Could you please provide a screen from your preferences? This page:

![2023-10-05 15_29_36-DBeaver Ultimate 23 2 2 - _default 1_ Script-126](https://github.com/dbeaver/dbeaver/assets/45152336/15479b7e-d907-49ea-81e9-da6a14e6f7be)

Also, this is issue from the driver side. 

```
!MESSAGE Cannot invoke "java.time.LocalDate.getYear()" because "d" is null
!STACK 0
java.lang.NullPointerException: Cannot invoke "java.time.LocalDate.getYear()" because "d" is null
	at com.clickhouse.jdbc.ClickHouseResultSet.getDate(ClickHouseResultSet.java:358)
	at com.clickhouse.jdbc.ClickHouseResultSet.getDate(ClickHouseResultSet.java:340)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getDate(JDBCResultSetImpl.java:419)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCDateTimeValueHandler.fetchValueObject(JDBCDateTimeValueHandler.java:100)
```

**Comment by maks56893** [comment]
@LonwoLonwo 
![image](https://github.com/dbeaver/dbeaver/assets/61263947/4f85d328-4c17-4566-9ab2-07a94778c225)

**Comment by LonwoLonwo** [comment]
Still, can not reproduce it.

![2023-10-05 18_32_59-DBeaver Ultimate 23 2 2 - _default 1_ Script-126](https://github.com/dbeaver/dbeaver/assets/45152336/5be9f08a-66d2-4671-8fad-4621810ac353)

It is probably better to create a ticket here: https://github.com/ClickHouse/clickhouse-java/issues

**Comment by arhayka** [comment]
This is not a DBeaver issue, so, I'm closing this ticket.
