### ISSUE TITLE
The connection attempt failed: java.io.EOFException

### ISSUE THREAD

**Issue by bazmap** [dbeaver/dbeaver#21423]
### Description

Strange bug I might have found...

I set a classic PostgreSQL connexion : 
![image](https://github.com/dbeaver/dbeaver/assets/8897724/62b31ada-0598-48d1-8471-0f6e5228414d)

No SSH and using the latest binaries.
![image](https://github.com/dbeaver/dbeaver/assets/8897724/d4efb010-10c0-4f8a-811d-2d0a242848fc)

When I try to connect, I have this message : 
![image](https://github.com/dbeaver/dbeaver/assets/8897724/cae4c6e3-633a-4401-9def-3a41141c0640)

The associated error log : 
```
java.io.EOFException
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:589)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:191)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
	at org.postgresql.Driver.makeConnection(Driver.java:443)
	at org.postgresql.Driver.access$100(Driver.java:63)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:353)
	at java.base/java.lang.Thread.run(Unknown Source)
```
Session data : 
```
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Framework arguments:  -eclipse.keyring C:\Users\abazin\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

```

If I change the port number to 5434 : the connexion work, I mean it try to connect (but it can't as there is no postgresql instance on 5434).

I don't understand why there is no try for the 5433 port.
Can you help me ?

### DBeaver Version

Community edition 23.2.1.202309260508

### Operating System

Windows 11

### Database and driver

PostgreSQL 15
JDBC driver : 42.6.0

**Comment by bazmap** [comment]
It seems that de database itself was having an issue but nothing in the DBeaver log show this. 
So I don't know if the error encountered is because of the database issue or because of DBeaver :-(

**Comment by LonwoLonwo** [comment]
Hello @bazmap 

> at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:589)

Does the SSL tab have enabled the "Use SSL" option? Or, maybe, a special driver parameter for SSL?

**Comment by bazmap** [comment]
Hi,
The SSL tab doesn't have the "Use SSL" option activated and there is no parameter set for ssl in the driver settings.

I did other tests and will provide you more context.

We have an infrastructure that allows us to instantiate as many postgresql instance as we want, on the fly with the settings we want.
I've created an instance with basic data but I made a mistake in my parameters and the instance havn't been started.
In this case, I've had the message EOFException

Then, I've created the exact same instance but without de mistake and the instance have started correctly.
By using the exact same connexion in DBeaver, just by changing the host (just a number of instance to change), DBeaver have set the connexion without difficulties.

So "in fine" this is not really a bug but there is a trouble in the way DBeaver handle the "non-possibility" to connect to an instance. The error message is not clear.
I don't know exactly in which state was the PostgreSQL instance but DBeaver couldn't connect to it and the error message was not clear about why it can't.

We don't use SSL here because we are in local and don't need it in this project.

**Comment by LonwoLonwo** [comment]
Ok, thanks for the explanation.

But I'm unsure how we can enhance this process of incorrect connection. Because we just showing issues from a driver or a database. DBeaver knows nothing about the reasons why the issue occurred.
Probably, it can be an enhancement for the driver.

**Comment by bazmap** [comment]
The error here comes from the driver ? there is no other information comming from the driver ?
I will try with jdbc only to check what kind of error there is and if we could handle this one better.
I will post the result here :-)
Thank you for your answer !
Have a nice day !

**Comment by LonwoLonwo** [comment]
Ok. Will wait for your investiogestion results.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
