### ISSUE TITLE
Error - Can't Connect to Amazon Athena 

### ISSUE THREAD

**Issue by ftironectidata** [dbeaver/dbeaver#21424]
### Description

[Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. You are not authorized to perform: athena:StartQueryExecution on the resource. After your AWS administrator or you have updated your permissions, please try again. [Execution ID not available]
  You are not authorized to perform: athena:StartQueryExecution on the resource. After your AWS administrator or you have updated your permissions, please try again. (Service: AmazonAthena; Status Code: 400; Error Code: AccessDeniedException; Request ID: acab5009-88d9-499c-b58b-c8159fd892bc; Proxy: null)
  You are not authorized to perform: athena:StartQueryExecution on the resource. After your AWS administrator or you have updated your permissions, please try again. (Service: AmazonAthena; Status Code: 400; Error Code: AccessDeniedException; Request ID: acab5009-88d9-499c-b58b-c8159fd892bc; Proxy: null)

### DBeaver Version

Community Addition 23.2.1.202309260508

### Operating System

Windows 11

### Database and driver

Amazon Athena 

Magnitude Simba Athena JDBC Data
Version 2.0.25

### Steps to reproduce

Try to connect to database

**Comment by LonwoLonwo** [comment]
Hello @ftironectidata 

> You are not authorized to perform: athena:StartQueryExecution on the resource. After your AWS administrator or you have updated your permissions, please try again

Did you try to ask your database admin for special rights?

**Comment by ftironectidata** [comment]
Hi Anastasiya,

Thanks for your help! Please let me know what permissions I need and how to give them.

**Comment by ftironectidata** [comment]
I added the permissions and It’s working now!

Best Regards,

Frank
