### ISSUE TITLE
After update to 23.2.1 MFA auth on Azure Sql stop to worked

### ISSUE THREAD

**Issue by LevGelman** [dbeaver/dbeaver#21433]
### Description

I'm connecting to Azure SQL database using MFA authentication. 
In a past version, the MFA was opening default browser and it worked OK.
In 23.2.1 version, the dbeaver open internal "browser" and after the authentication complete (password + token),
the connection didn't set and internal "browser" still open, when I close it, I got connection reset error.
I tried to update the drivers.

### DBeaver Version

Community Edition 23.2.1 

### Operating System

Windows 10

### Database and driver

Azure SQL server connector

### Steps to reproduce

1. Azure SQL database using MFA authentication
2.Complete authentication flow (password + token)
3.Can't connect

**Comment by Destrolaric** [comment]
@LevGelman Hi, as a workaround, the auth in the internal browser is configurable by the `open auth links in the embedded browser` checkbox in User Interface preferences
![image](https://github.com/dbeaver/dbeaver/assets/20579256/7ec853a3-9286-479f-ba29-2d02f228e8d6)

**Comment by LevGelman** [comment]
> @LevGelman Hi, as a workaround, the auth in the internal browser is configurable by the `open auth links in the embedded browser` checkbox in User Interface preferences ![image](https://user-images.githubusercontent.com/20579256/270326140-7ec853a3-9286-479f-ba29-2d02f228e8d6.png)

Thank you!

**Comment by Destrolaric** [comment]
@LevGelman Hi, if possible, could you try again with the enabled checkbox and send the logs
You can find instructions on how to get them here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by LevGelman** [comment]
@Destrolaric 
my current version is 23.2.3.202310221533,
It's relevant part of the log:

!SESSION 2023-10-25 13:10:07.402 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\LevGelman\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.e4.ui.workbench 4 0 2023-10-25 13:10:12.293
!MESSAGE Unable to retrieve the bundle from the URI: bundleclass://com.genuitec.eclipse.meexplorer/com.genuitec.eclipse.meexplorer.breadcrumb.e4.BreadCrumbContainer

!ENTRY org.eclipse.ui 2 2 2023-10-25 13:10:14.103
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

**Comment by LonwoLonwo** [comment]
Hello @LevGelman 

Could you please provide a screen from your driver's libraries? 

![2024-03-29 09_49_57-Window](https://github.com/dbeaver/dbeaver/assets/45152336/b61cd42e-63cc-4dad-bbc6-17ea78fd139c)

I have an idea that maybe msal4j library updating could help.

![2024-03-29 09_51_54-Window](https://github.com/dbeaver/dbeaver/assets/45152336/0c0efc0d-7463-4ecf-9e0d-feaa2dc0bf9f)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by LevGelman** [comment]
@E1izabeth After updating to new version, the it was resolved, thank you!
