### ISSUE TITLE
Updates to Microsoft Store version after 23.1.0

### ISSUE THREAD

**Issue by miguellira** [dbeaver/dbeaver#21439]
### Description

Looks like the last version published to the Microsoft Store was back in June (version 23.1.0). Is that the end of the line for the Microsoft Store version?

### DBeaver Version

23.1.0

### Operating System

Windows 11

**Comment by LonwoLonwo** [comment]
Thanks for the report.
We are trying to handle it.

**Comment by Studio384** [comment]
Are there any updates on this?

**Comment by Abyanaki** [comment]
No updates?

**Comment by StarsbySea** [comment]
Any Updates on this? @LonwoLonwo

**Comment by eguif** [comment]
Microsoft store dbeaver update 23.3.2 won't open

**Comment by LonwoLonwo** [comment]
> Microsoft store dbeaver update 23.3.2 won't open

Thanks for the report. We are working on this issue.

**Comment by tysonite** [comment]
It would be awesome if version 23.3.2 in Microsoft Store can be upgrade to 23.3.4.

**Comment by E1izabeth** [comment]
The issue was solved. We updated DBeaver in the Microsoft Store to the latest version.
