### ISSUE TITLE
[Dameng] Sequence cannot be edited on its creation via UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#21441]
### Description

Cannot change any data for sequence on its creation via UI

![image](https://github.com/dbeaver/dbeaver/assets/31996417/7ad74e7f-fcab-4c52-b84b-3a53d69a1de9)

### DBeaver Version

23.2.2

### Operating System

win10

### Database and driver

Dameng

### Steps to reproduce

1. Connect to Dameng
2. Try to create new Sequnce using context menu in DB Navigator - Only Sequence name could be set. Other values are read-only

**Comment by pavants** [comment]
Same in SQL Server, useful could have an option to Generate SQL> DDL
