### ISSUE TITLE
No suitable driver found for jdbc:db2://mylocal:myport/mylocation No suitable driver found for jdbc:db2://mylocal:myport

### ISSUE THREAD

**Issue by DBeaver321** [dbeaver/dbeaver#21456]
### Description

New to this product.  I'm trialing but can't make a connection to z/OS DB2. 

### DBeaver Version

Version 23.2.1.202309260508

### Operating System

Windows 10 Enterprise

### Database and driver

COM.ibm.db2.jdbc.app.DB2Driver 

### Steps to reproduce

Try a test connection

**Comment by LonwoLonwo** [comment]
Hello. Could you please provide your connections settings page screen?

**Comment by DBeaver321** [comment]
Sure, I hope this is what you are looking for?

**Comment by LonwoLonwo** [comment]
Please, provide it on this GitHub page. Sending images via e-mail doesn't work here.

**Comment by DBeaver321** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/147166644/6dd33f44-086a-4a34-a42c-dfd4aa17c19e)

![image](https://github.com/dbeaver/dbeaver/assets/147166644/b4026a1d-0ffc-460e-b854-ead499c3e3d7)

**Comment by LonwoLonwo** [comment]
But why did you change the driver class name? Do you use a non-standard driver? If not, could you please return the Class Name field to the `com.ibm.db2.jcc.DB2Driver` and try to connect again?

**Comment by DBeaver321** [comment]
The default driver class did not work.  I changed it back to com.ibm.db2.jcc.DB2Driver but still get the same message.

**Comment by LonwoLonwo** [comment]
I see that you used some kind of custom driver.
But what if you will create a new connection with a standard driver? Like in the picture:

![2023-10-09 18_56_27-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/e4b1de29-26f5-4524-9568-4243d1917ad5)

**Comment by DBeaver321** [comment]
I really don't know what is wrong, but it keeps picking up the old configuration from the previous one.  I changed the driver to com.ibm.db2.jcc.DB2Driver but no help.  Should I uninstall and reinstall?

**Comment by LonwoLonwo** [comment]
You can reinstall, ok.
And try again.
And if it will not help, please provide me a screen from your connections settings -> driver settings -> libraries page

**Comment by DBeaver321** [comment]
I uninstalled and reinstalled but it's still holding onto the old settings.  I tried setting up a new connection but got the same error.

**Comment by LonwoLonwo** [comment]
please provide me a screen from your connections settings -> driver settings -> libraries page (on this GitHub page, not via e-mail)

**Comment by DBeaver321** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/147166644/03af7360-adbd-43c0-9e4e-e4ecf38a2a94)

**Comment by LonwoLonwo** [comment]
Please, provide me libraries page

**Comment by DBeaver321** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/147166644/e23e11dc-4d91-458b-9b06-cefedaf8c1b3)

**Comment by LonwoLonwo** [comment]
I do not see a default driver in your libraries.

You can or try to use the "Restore to Defaults" button.

Or add the driver manually https://repo1.maven.org/maven2/com/ibm/db2/jcc/11.5.7.0/jcc-11.5.7.0.jar

**Comment by DBeaver321** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/147166644/adacc143-33d6-46a8-a0af-0073d1883d69)

After the reset to default

**Comment by LonwoLonwo** [comment]
Ok. You can choose this element and click the "Download" button. And after downloading you can try to connect again.

**Comment by DBeaver321** [comment]
Thank you!  It's working now.  I did need to add my license file and it worked after that.

**Comment by LonwoLonwo** [comment]
Great. Thanks for the update!
