### ISSUE TITLE
Problem to show large view 

### ISSUE THREAD

**Issue by Mateozmaldonado17** [dbeaver/dbeaver#2145]
java.lang.StringIndexOutOfBoundsException: String index out of range: 2300

**Comment by serge-rider** [comment]
Please post error stacktrace.
You can get it in Error Log view or in error log: https://github.com/serge-rider/dbeaver/wiki/Log-files

**Comment by kseniiaguzeeva** [comment]
Please reopen if it is still reproduced on newer version. A screenshot and logs will help us to fix it.
