### ISSUE TITLE
Oracle and DBeaver

### ISSUE THREAD

**Issue by markbenson33** [dbeaver/dbeaver#21460]
Hello,

Is Oracle still supported with DBeaver?  We noticed it is not on the About page, which lists all the DB Engines supported.

https://dbeaver.io/about/

Thanks,
Mark

**Comment by E1izabeth** [comment]
Hi Mark.
Yes, sure, we support Oracle.
I believe it's a bug on our web site. We will fix it. Thank you for reporting.

**Comment by LonwoLonwo** [comment]
Fixed. Thanks for the report.
Issue fixed
