### ISSUE TITLE
Postgresql database backup does not includes "-T tablename" for unchecked tables in pg_dump command

### ISSUE THREAD

**Issue by bcfreitas** [dbeaver/dbeaver#21462]
### Description

In Tools/Backup, not checked tables (that I don't want to backup) is not cut off from backup.

To workaround my problem, I copied pg_dump command that dbeaver created and ran on terminal with aditional options -T table1 -T table2 ... 

### DBeaver Version

Community Edition 23.2.1.202309260508

### Operating System

Debian 12

### Database and driver

Postgresql 10

### Steps to reproduce

1. Select Tools / Backup on a Postgresql-10 database;
2. Check one or more schemas, and uncheck one or more tables from these schemas;
3. Advance, select Custom format and continue; 
4. Dbeaver shows the pg_dump command with options used and start backup. 
5. Restore the database in other place and see that the tables you have unchecked was part of backup.

**Comment by LonwoLonwo** [comment]
Hello @bcfreitas 

Thanks for the report.

Probably, it is already fixed. I can't reproduce it right now.
You can check it in our [early access version](https://dbeaver.io/), or you can wait until Monday's release.

![2023-10-07 18_43_58-PostgreSQL dump](https://github.com/dbeaver/dbeaver/assets/45152336/590b1586-89af-4c3d-b2ee-cea7bdeeed19)

**Comment by LonwoLonwo** [comment]
Maybe this is the case for multiple schemas: https://github.com/dbeaver/dbeaver/issues/21669

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
