### ISSUE TITLE
Embedded web browser window appears blank during Active Directory - MFA Authentication

### ISSUE THREAD

**Issue by ipimpat** [dbeaver/dbeaver#21470]
### Description

When attempting to authenticate via Active Directory - MFA in DBeaver on Ubuntu 22.04.3 LTS, the embedded web browser window displays as blank. Although visually blank, the window contains selectable (and copyable) text, suggesting the content is present but not rendered visibly.

![image](https://github.com/dbeaver/dbeaver/assets/450038/26553a19-b2d4-4044-9f6a-61bd87b25602)

Disabling the option to open the authentication page in the embedded web browser appears to mitigate the issue.

![image](https://github.com/dbeaver/dbeaver/assets/450038/4c767883-2acf-453d-9b3c-0f58bdd6df95)

### DBeaver Version

23.2.2.202310081633

### Operating System

Ubuntu 22.04.3 LTS

### Database and driver

Database: Microsoft Azure SQL
Driver: Microsoft JDBC Driver for SQL Server
Auth: Active Directory - MFA

**Comment by Destrolaric** [comment]
@ipimpat Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by ipimpat** [comment]
For some reason, I can't reproduce the issue right now. I had intended to replicate it to provide you with the logs, but the embedded browser is currently rendering the page correctly. This might have been a temporary issue with Microsoft's sign-in page.

I'll also check my work computer (also running Ubuntu 22.04), where I observed the same problem. However, I won't be in the office until Thursday or Friday

**Comment by Destrolaric** [comment]
@ipimpat Hi, were you able to reproduce the issue again?

**Comment by ipimpat** [comment]
Apologies for the delayed response - plans shifted, so I have not been near my work machine until today.

I was able to reproduce the issue on my work machine:

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/13177571/dbeaver-debug.log)
[dbeaver-debug-1698324494896.log](https://github.com/dbeaver/dbeaver/files/13177572/dbeaver-debug-1698324494896.log)

![image](https://github.com/dbeaver/dbeaver/assets/450038/6463148c-4c7f-47db-b3da-e004eb0185ba)

**Comment by ipimpat** [comment]
I have experienced the exact same problem with a completely different application: [OneDriver](https://github.com/jstaf/onedriver).

A couple of days ago, when I needed to authenticate in OneDriver using my Microsoft account, the authentication window in OneDriver was also blank.

So, based on that, I suspect this issue is not directly related to DBeaver, but the problem might lie in an underlying component.

I'm not sure if DBeaver and OneDriver are using the same underlying embedded browser component in Ubuntu.

**Comment by Destrolaric** [comment]
@ipimpat Hi, could you try to install libwebkit2gtk.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by ipimpat** [comment]
@E1izabeth sorry for the late reply.

libwebkit2gtk is already installed.

`libwebkit2gtk-4.0-37/jammy-updates,jammy-security,now 2.42.4-0ubuntu0.22.04.1 amd64 [installed]
  Web content engine library for GTK
`
