### ISSUE TITLE
Postgresql wrong DDL for foreign key constraint - MATCH FULL 

### ISSUE THREAD

**Issue by tvape** [dbeaver/dbeaver#21488]
### Description

Dbeaver is generating this incorrect DDL:

ALTER TABLE tbl_example ADD CONSTRAINT tbl_example_fk FOREIGN KEY (col1,col2) REFERENCES tbl_example2 (col1, col2) ON DELETE CASCADE ON UPDATE CASCADE MATCH FULL;

However it's not valid, the MATCH FULL must be placed before ON DELETE, i.e. correctly:

ALTER TABLE tbl_example ADD CONSTRAINT tbl_example_fk FOREIGN KEY (col1,col2) REFERENCES tbl_example2 (col1, col2) MATCH FULL ON DELETE CASCADE ON UPDATE CASCADE;

### DBeaver Version

Community Edition 23.2.2.202310081633

### Operating System

Windows 11

### Database and driver

Postgresql 15.0
Postgresql driver 42.5.2

**Comment by Matvey16** [comment]
@tvape Can you specify how do you get this generated SQL? Do you open a foreign key from navigator or table properties and check the source tab?

**Comment by LonwoLonwo** [comment]
Thanks for the report @tvape

**Comment by tvape** [comment]
The SQL is generated incorrectly if I click on DDL in the table properties as well as when I click on table context menu in database navigator and then select Generate SQL and then DDL (of the table)

**Comment by tvape** [comment]
When I click on Source in the foreign key properties it is generated correctly, as well as if I click on the context menu of the foreign key in the navigator and select Generate SQL and then DDL (of the foreign key)
