### ISSUE TITLE
no changed numeric data format

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#21483]
### Description

I changed numeric data format? but no effect

### DBeaver Version

community edition 23.21

### Operating System

windows 11 64bit

### Database and driver

postgresql 14

### Steps to reproduce

1. create table with column numeric type
![image](https://github.com/dbeaver/dbeaver/assets/61137576/903ef069-828a-4f3d-96db-d1c3c6aeea6b)

2. put value 7.737777 to column, and save
![image](https://github.com/dbeaver/dbeaver/assets/61137576/792d28eb-db3a-4119-a498-54dd8835a87e)

Value cut for 3 symbol after comma and value is rounded.

3. Go to property and chahge 
![image](https://github.com/dbeaver/dbeaver/assets/61137576/3ff42619-313f-41ee-82ad-6d2a090154b8)

have no effect 

4. Use data type scale for fraction digits 
![image](https://github.com/dbeaver/dbeaver/assets/61137576/f23cfd19-2904-4501-8b31-0c89394bc364)
have no effect

**Comment by LonwoLonwo** [comment]
Hello @detkliff 

Could you please check the latest DBeaver version?

Probably, it was fixed here https://github.com/dbeaver/dbeaver/issues/21342.

**Comment by detkliff** [comment]
on latest version version 23.2.2
1. change Maximum fraction digits 
![image](https://github.com/dbeaver/dbeaver/assets/61137576/2f02323f-7ba3-45b0-8a35-a2e9be0df67c)
no effect

2. regime rounding 
![image](https://github.com/dbeaver/dbeaver/assets/61137576/f932ae16-e54a-48a9-9fde-125a9771d688)
![image](https://github.com/dbeaver/dbeaver/assets/61137576/bd0f5a02-2a73-4c18-9104-a9ceaeb16ac4)
![image](https://github.com/dbeaver/dbeaver/assets/61137576/045f8ef1-1afa-4a42-b26f-e5ec4946e7e5)

no effect, rounding not off

3.
![image](https://github.com/dbeaver/dbeaver/assets/61137576/ef66237e-aaa7-460f-93ae-ca03cb507d13)
no effect for numeric type
![image](https://github.com/dbeaver/dbeaver/assets/61137576/90b1a495-9a81-4113-9486-257d086e699f)

4. Only this have effect
![image](https://github.com/dbeaver/dbeaver/assets/61137576/7971c892-782d-4b8f-aa34-76f4e71f2b00)

![image](https://github.com/dbeaver/dbeaver/assets/61137576/bdee6523-af95-43d7-95fe-dc8eab3460c6)

**Comment by E1izabeth** [comment]
Could you try to refresh or reopen the data editor after changing the settings?

**Comment by detkliff** [comment]
> Could you try to refresh or reopen the data editor after changing the settings?

yes i could!

**Comment by detkliff** [comment]
changing parameter 1 view on example, but parameter 2 no effect

![image](https://github.com/dbeaver/dbeaver/assets/61137576/6f3fa669-66de-48c6-a74b-71f01bea78e6)

**Comment by detkliff** [comment]
23.2.4 size groupping have effect
![image](https://github.com/dbeaver/dbeaver/assets/61137576/a6e9a2ba-68aa-4fab-b742-465301736ff4)

**Comment by detkliff** [comment]
in 23.2.4 maximum integer digit have effect. But where is 0 before comma?
![image](https://github.com/dbeaver/dbeaver/assets/61137576/33900faa-1ef9-42e5-8841-246d89f77107)

**Comment by ShadelessFox** [comment]
Hello @detkliff,

What's the complete DDL for that column? Are you using just the `numeric` type without explicitly specifying its scale and precision?

**Comment by detkliff** [comment]
> What's the complete DDL for that column? Are you using just the `numeric` type without explicitly specifying its scale and precision?

![image](https://github.com/dbeaver/dbeaver/assets/61137576/cc6597c7-0b45-4aa9-914d-f495bdad6069)

**Comment by ShadelessFox** [comment]
Is the issue reproducible against the following SQL script?

```sql
create temp table numerics as select '7.737777'::numeric as value;

select * from numerics;
```

**Comment by detkliff** [comment]
> ```sql
> create temp table numerics as select '7.737777'::numeric as value;
> 
> select * from numerics;
> ```

![image](https://github.com/dbeaver/dbeaver/assets/61137576/a98b36c7-5132-4994-86b8-65c2eaec9a70)

![image](https://github.com/dbeaver/dbeaver/assets/61137576/1372ab50-0ebf-4180-90eb-ad700b62bfb4)

![image](https://github.com/dbeaver/dbeaver/assets/61137576/20539d87-20e2-45bc-b64b-fed47b839be9)

**Comment by ShadelessFox** [comment]
I was able to get the same behavior as in your last comment, but at this point, I'm not sure what the expected behavior is. Can you please clarify your expectations?

With default formatted settings, values look like this:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/76bc2341-a58c-4d2c-9fc4-f6125347054a)

**Comment by detkliff** [comment]
Minimum integer digits = 1  solves the problem of absence 0

**Comment by detkliff** [comment]
this parameters do not work for field Example 
![image](https://github.com/dbeaver/dbeaver/assets/61137576/b2e9dc5b-eb4f-420c-93ba-a6e97d72ab39)

**Comment by ShadelessFox** [comment]
Hello again,

Sorry for the long wait. Can you please give an update on your issue? Is it resolved?

**Comment by detkliff** [comment]
> Hello again,
> 
> Sorry for the long wait. Can you please give an update on your issue? Is it resolved?

no. As a result, it is still not clear how this setting works.

how to configure it so that you can see the real value? For example for query select trunc(100, 2)

real value is 100.00

But in DBeaver
![image](https://github.com/dbeaver/dbeaver/assets/61137576/2e9a3e37-cb52-4f46-84bd-0ada52fe6510)
![image](https://github.com/dbeaver/dbeaver/assets/61137576/2e361bda-179f-45b9-ba8a-5e6a89a9e69c)

or 
![image](https://github.com/dbeaver/dbeaver/assets/61137576/a2b5f7fb-290b-4415-92a2-64cef55ea9d9)

![image](https://github.com/dbeaver/dbeaver/assets/61137576/ad20ce60-26ff-4bff-9398-7b61693cb8ad)


but on diuble click
![image](https://github.com/dbeaver/dbeaver/assets/61137576/d23430d6-4109-4935-927f-8acce735fc59)

I do not understand how i can see real returned value after executing query

**Comment by ShadelessFox** [comment]
The `trunc` function does not return a valid numeric type with the scale specified:
![java_U769N0YKqe](https://github.com/dbeaver/dbeaver/assets/35821147/f77b76c4-08e2-42f2-be8f-53c622c6ae91)

This works for me with "Disable numeric formatting" turned on:
```sql
select trunc(100, 2)::numeric(100, 2);
```

**Comment by detkliff** [comment]
ok. Thank you

**Comment by ShadelessFox** [comment]
Is the issue resolved? Can this ticket be closed?

**Comment by detkliff** [comment]
ok
