### ISSUE TITLE
Execution log: incorrect sorting by execution time

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#21487]
### Description

Sorting by execution time in execution log is incorrect. It's order like text, but values are numeric.

### DBeaver Version

Community Edition 23.2.2

### Operating System

Windows 10 x64

### Database and driver

PostgreSQL 15
PostgreSQL JDBC Driver 42.5.2

### Steps to reproduce

1. Run several queries.
2. Open the execution log window.
3. Sort by execution time.
![01](https://github.com/dbeaver/dbeaver/assets/22142845/8de99264-a9a6-4b85-a5ad-44d5b23b583a)
![02](https://github.com/dbeaver/dbeaver/assets/22142845/a0144cf6-2e71-439e-a5ba-2d1cfbfc3d57)

**Comment by E1izabeth** [comment]
Thank you for bug report. I reproduced the issue - if you change the sorting and then execute something, the sorting will be broken, as new items will be added to the top of the list.
You can press to the column header twice to resort the items. It should help.

**Comment by LonwoLonwo** [comment]
Related https://github.com/dbeaver/dbeaver/issues/13954

**Comment by ems2811** [comment]
> Thank you for bug report. I reproduced the issue - if you change the sorting and then execute something, the sorting will be broken, as new items will be added to the top of the list. You can press to the column header twice to resort the items. It should help.

Pressing to the column header twice or more to resort the items doesn't helps

**Comment by E1izabeth** [comment]
Could you then provide the steps to reproduce the issue from the beginning?
1. Open the script
2. Open the execution log
3. ???

**Comment by ems2811** [comment]
1. Open the script
2. Execute script
3. Open the execution log
4. Sorting
or
1. Open the script
2. Open the execution log
3. Execute script
4. Sorting

**Comment by E1izabeth** [comment]
Hmm. Thanks
