### ISSUE TITLE
Settings menu item disappears on MacOS

### ISSUE THREAD

**Issue by JTMosaic** [dbeaver/dbeaver#21494]
### Description

The settings menu item disappears randomly from the DBeaver menu on macOS 13.6

![image](https://github.com/dbeaver/dbeaver/assets/9417720/fa77ee6f-6eba-4462-a885-4e88d9c1b011)

Also, when this happens, the Command-, (![image](https://github.com/dbeaver/dbeaver/assets/9417720/9e2c0813-22f8-4830-9031-db90ab6b85d6))  shortcut stops working.

### DBeaver Version

23.2.2.202310081633

### Operating System

macOS Ventura 13.6

### Database and driver

N/A

### Steps to reproduce

Occurs randomly. Not sure exactly how to reproduce.

**Comment by LonwoLonwo** [comment]
Thanks for the report @JTMosaic

**Comment by JTMosaic** [comment]
This appears to have something to do with the devstyle theme. I've not seen it happen since I uninstalled it.

**Comment by MashaKorax** [comment]
duplicate https://github.com/dbeaver/pro/issues/1964
