### ISSUE TITLE
MariaDB JDBC Drivers do not allow LOAD DATA LOCAL INFILE if ResultSet fetch size is set

### ISSUE THREAD

**Issue by JTMosaic** [dbeaver/dbeaver#21495]
> Hi, I experienced exactly the same error on DBeaver 23.1.1 on macOS Big Sur & Windows, MariaDB version "10.5.20-MariaDB-log" on FreeBSD 13, JDBC driver MariaDB Connector/J 3.1.4. The fix mentioned here did not work. Rolling back to MariaDB Connector/J 3.0.4 fixed this issue. The same error occurred for each of the JDBC versions between 3.0.5 and 3.1.4.
> 
> Using the latest mySQL JDBC connector for MariaDB works as expected, i.e. it does not show the error described here.

Thanks for the info and testing, hkirschk!

Version 3.2.0 of the MariaDB Connector/J also does not work but rolling back to 3.0.4 does the trick

It should also be noted that the following allows the 3.2.0 driver to work:

Set the ResultSet fetch size parameter to 0 

![image](https://github.com/dbeaver/dbeaver/assets/9417720/38bee327-032c-4c4c-8e19-42a21ff1cc1c)

This, I believe, is a bug in DBeaver. DBeaver _should_ detect a LOAD DATA statement and turn off the fetch size for the transaction.

Setting this value can be accomplished through several clicks, which is an annoyance, or running a simple select (such as SELECT 1) and then changing the value in the row limit box and THEN running the LOAD DATA command. 

In both instances, it is necessary to remember to put the limit back after the load is done.

_Originally posted by @JTMosaic in https://github.com/dbeaver/dbeaver/issues/19115#issuecomment-1755506069_

**Comment by LonwoLonwo** [comment]
Hello @JTMosaic 

Please provide clear steps to reproduce.

**Comment by JTMosaic** [comment]
1. Download the attached test file and save it to a known location [testdata.csv](https://github.com/dbeaver/dbeaver/files/12882502/testdata.csv)
2. Ensure your DBeaver settings (global and for the connection) have a ResultSet fetch size > 0
![image](https://github.com/dbeaver/dbeaver/assets/9417720/8eee0981-c93c-414d-87c1-b9eac3fb95c6)

4. Connect to a MariaDB server using a driver version > 3.0.4 
![image](https://github.com/dbeaver/dbeaver/assets/9417720/2e39cdeb-1e84-47cf-bdf3-cb2c8db2c715)

5. Create a table in a schema of your choice:

```
CREATE TABLE loadtest (
row_id int,
value varchar(10));
```

6. Adjust the following script to point to the file saved in step 1

```
load data local infile '<path_to_file>/testfile.csv'
into table loadtest
fields terminated by ','
ignore 1 lines;
```

7. Run the script. The following error will be returned:

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [HY000]: (conn=32110) LOAD DATA LOCAL INFILE asked for file '/testdata' that doesn't correspond to initial query SET STATEMENT SQL_SELECT_LIMIT=1000 FOR load data local infile '/testdata'
into table loadtest
fields terminated by ','
ignore 1 lines. Possible malicious proxy changing server answer ! Command interrupted
```

8. Set the ResultSet fetch size to 0 and run the script in step 6 again 
9. Import successful

**Comment by MashaKorax** [comment]
I reproduced it. Thanks for your report!
