### ISSUE TITLE
Change the zoom level in the SQL Editor using the scroll wheel

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#21499]
**Is your feature request related to a problem? Please describe.**
I don't want the same zoom level every time; I change it each time depending on multiple factors, such as how large the query is or the sunlight reflecting on my monitor. Using the CTRL + or CTRL - shortcuts is not very convenient.

**Describe the solution you'd like**
I want to smoothly change the zoom level in the SQL Editor using CTRL + the scroll wheel.

**Describe alternatives you've considered**
Empty

**Additional context**
Empty

**Comment by E1izabeth** [comment]
Thank you for the idea.
I'm closing it as a duplicate of #17817. You can vote for that issue with 👍 under the issue description to promote it to a higher priority.
