### ISSUE TITLE
data transfer bug. include data export/import

### ISSUE THREAD

**Issue by zghlx** [dbeaver/dbeaver#21507]
### Description

when export data task. occur some error: eg. connection closed or server shutdown, i got too many error prompt,i had to close error prompt windows one by one. if the task contains hundred tables i will close the prompt windows hundred. or kill the dbeaver progress instead.

### DBeaver Version

23.2.2

### Operating System

windws 11

### Database and driver

mysql

### Steps to reproduce

1,create export data task which contains hundred tables
2, close the server or manual close the connection
3, begin to execute the task 
4, huandred connection error prompt windows wait you to manual close one by one.

**Comment by hrimthrusa** [comment]
Hi, could you send us a capture of the issue you are experiencing?

**Comment by ShadelessFox** [comment]
Please provide footage showing your issue. Otherwise, we won't be able to help you resolve it.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
