### ISSUE TITLE
lookup from dictionary using description

### ISSUE THREAD

**Issue by JeroenNienhuis** [dbeaver/dbeaver#21503]
In table view with a look-up field, a dictionary is displayed in addition to the value field
![afbeelding](https://github.com/dbeaver/dbeaver/assets/51078213/71e47d1a-de77-4d77-9952-4c9786579200)

When a value is entered in the value field this is used to bold the matching record in the dictionary. It would be nice if this filter is not only applied to the dictionary value, but also to the description.

**Comment by E1izabeth** [comment]
Thank you for future request. We actually implemented it recently. Could you try the latest version?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
