### ISSUE TITLE
Table description and column comments are lost when export table from A db to B db .

### ISSUE THREAD

**Issue by zghlx** [dbeaver/dbeaver#21508]
### Description

export tables from A mysql db to another B mysql db, the tables and the fields comments are lost.

### DBeaver Version

23.2.2

### Operating System

cnetos7

**Comment by MashaKorax** [comment]
Hello, @zghlx. Please provide more details. What do you mean  "the tables and the fields comments are lost"?

**Comment by zghlx** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/5928564/04958010-d313-45c2-b15a-fa64a97ca01f)

**Comment by MashaKorax** [comment]
Thanks for your report!

**Comment by MashaKorax** [comment]
Reproducible on any database

**Comment by LonwoLonwo** [comment]
Hello @zghlx 

For MySQL you can:

1. Do a copy of your table in the Navigator tree before data transfer. With simple Ctrl+C and Ctrl+V. This case all column comments and table comment will be copied.

2. Other option - you can specify table comment for a new table during data transfer this way:

![2023-10-12 18_01_42-Configure metadata structure](https://github.com/dbeaver/dbeaver/assets/45152336/aff201c7-1785-41a8-843b-55f097b42b9f)

**Comment by LonwoLonwo** [comment]
Also, this is a duplicate of https://github.com/dbeaver/dbeaver/issues/9318

**Comment by zghlx** [comment]
> Hello @zghlx
> 
> For MySQL you can:
> 
> 1. Do a copy of your table in the Navigator tree before data transfer. With simple Ctrl+C and Ctrl+V. This case all column comments and table comment will be copied.
> 2. Other option - you can specify table comment for a new table during data transfer this way:
> 
> ![2023-10-12 18_01_42-Configure metadata structure](https://user-images.githubusercontent.com/45152336/274644474-aff201c7-1785-41a8-843b-55f097b42b9f.png)

thanks! but if mysql db A contains hundred tables and too many fields comments per table, i think you given method is a hard and replate work.  I need transfer A table's coment and fields comments to mysql db B automaticly, just like other db clients tools, like heidisql etc.

**Comment by LonwoLonwo** [comment]
> I need transfer A table's coment and fields comments to mysql db B automaticly

As I said, you can copy-paste tables first. Just metadata. And after that use data transfer.

Also, you can use backup/restore tools: https://github.com/dbeaver/dbeaver/wiki/Backup-Restore
