### ISSUE TITLE
Navigator error upon attempt to open Scripts in the UI

### ISSUE THREAD

**Issue by haufs** [dbeaver/dbeaver#21501]
### Description

I click in Scripts folder and version 23.2.2 throws Navigator error:

![image](https://github.com/dbeaver/dbeaver/assets/117753713/4f2af355-3120-4eca-ae57-5ad3f716d1e2)

Click ok and am able to open scripts  from File > Open File

2nd issue:
my server connections used to auto-connect upon opening of the UI, but this also stopped, but may have happened in previous version of DBeaver?

Thanks in advance for your help!
Steve

### DBeaver Version

Community Edition version 23.2.2

### Operating System

Windows 10

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by haufs** [comment]
Hello,
adding all the log files from this location:
C:\Users\haufs\AppData\Roaming\DBeaverData\workspace6\.metadata

[dbeaver-debug-1697114603809.log](https://github.com/dbeaver/dbeaver/files/12882526/dbeaver-debug-1697114603809.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/12882529/dbeaver-debug.log)
[dbeaver-debug-1697059763623.log](https://github.com/dbeaver/dbeaver/files/12882530/dbeaver-debug-1697059763623.log)
[dbeaver-debug-1697067901846.log](https://github.com/dbeaver/dbeaver/files/12882531/dbeaver-debug-1697067901846.log)

**Comment by ShadelessFox** [comment]
Thanks for the bug report

**Comment by haufs** [comment]
you're very welcome!

**Comment by haufs** [comment]
Thank you very much for resolving all issues in this ticket!!!
Very much appreciated!
please close ticket

**Comment by haufs** [comment]
I failed to say Community Edition:
23.2.4 resolved the issue

**Comment by GaNiziolek** [comment]
The package on Arch stays on 23.2.2 version...
