### ISSUE TITLE
 Can't use DB Metadata search to search plsql code in packages bodies

### ISSUE THREAD

**Issue by sruby** [dbeaver/dbeaver#21519]
### Description

 Can't use DB-Full-Text search and Search metadata to search plsql code in packages

### DBeaver Version

Community Version 23.2.2.202310081633

### Operating System

Windows 11

### Database and driver

Oracle 19C

### Steps to reproduce

1. I want to search "TMP_CALC_KEY_COMPONENT " table in packages.
![image](https://github.com/dbeaver/dbeaver/assets/15009808/230e57fe-8b63-429d-a3d4-b6e0a1be2692)

2. Search metadata
![image](https://github.com/dbeaver/dbeaver/assets/15009808/1f28c64e-01f7-482c-87b5-643a065a6995)

![image](https://github.com/dbeaver/dbeaver/assets/15009808/ec779bd0-9469-49e4-8d51-a7a6628d76d7)

3. Search DB Full-Text
![image](https://github.com/dbeaver/dbeaver/assets/15009808/7b4d5d6e-0ef5-4e3c-97b0-ef415f8cee16)
![image](https://github.com/dbeaver/dbeaver/assets/15009808/2bef9594-8382-4f59-927d-384b4da379ac)

**Comment by E1izabeth** [comment]
Have you tried checking `Search in definitions`?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/72d2ecd0-0b1c-4edc-a1ad-d9ad65e893f6)

**Comment by sruby** [comment]
> Have you tried checking `Search in definitions`? ![image](https://user-images.githubusercontent.com/28875055/274848178-72d2ecd0-0b1c-4edc-a1ad-d9ad65e893f6.png)

Yes, I have tried: "Search in definitions".
Please refer to "2. Search metadata" in "Steps to reproduce".

**Comment by E1izabeth** [comment]
I can't reproduce your issue. Do you see the searched table inside the package in navigator?

**Comment by sruby** [comment]
> I can't reproduce your issue. Do you see the searched table inside the package in navigator?

Yes, please refer to the image of "1. I want to search "TMP_CALC_KEY_COMPONENT " table in packages."
![image](https://github.com/dbeaver/dbeaver/assets/15009808/069d07c1-1a86-4cea-b35d-93562609cad2)

**Comment by LonwoLonwo** [comment]
Hello @sruby 

I see "TMP_%" on your search screen. But did you try to use  "%TMP_%"? Or "TMP_" and the match type - "Contains"?

**Comment by sruby** [comment]
> Hello @sruby
> 
> I see "TMP_%" on your search screen. But did you try to use "%TMP_%"? Or "TMP_" and the match type - "Contains"?

Thanks, it worked when I selected match type = "Contains".

But it can only search for a single word and can't search using SQL statements. How can I search using SQL statements?
![image](https://github.com/dbeaver/dbeaver/assets/15009808/37916c3a-282e-47d2-87d5-8c7bbc98c045)

**Comment by LonwoLonwo** [comment]
I can't reproduce it for now. It works and with a few words inside.

Please provide a screen from the Metadata search wizard for the last case.

**Comment by LonwoLonwo** [comment]
Maybe this tip will be helpful for you https://github.com/dbeaver/dbeaver/issues/21545#issuecomment-1766001386

**Comment by sruby** [comment]
> I can't reproduce it for now. It works and with a few words inside.
> 
> Please provide a screen from the Metadata search wizard for the last case.

Screen step by step:
1. search 
![image](https://github.com/dbeaver/dbeaver/assets/15009808/7e466f4e-11c4-4aa3-ab2a-b5d28aeea521)

2. result
![image](https://github.com/dbeaver/dbeaver/assets/15009808/2ab1e981-b2bf-4988-9f79-7cae611c949b)
3. SQL statement in the package
![image](https://github.com/dbeaver/dbeaver/assets/15009808/58b99e71-432a-4c39-a03e-198acdab8e26)

**Comment by sruby** [comment]
> Maybe this tip will be helpful for you [#21545 (comment)](https://github.com/dbeaver/dbeaver/issues/21545#issuecomment-1766001386)

It didn't  worked
![image](https://github.com/dbeaver/dbeaver/assets/15009808/0b62cf28-cdca-4299-add5-92b3157471a2)

**Comment by LonwoLonwo** [comment]
You can check the [query manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) with all enabled filters and find your search query. And execute it in the SQL Editor. Does the result contain your package?

**Comment by sruby** [comment]
> You can check the [query manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) with all enabled filters and find your search query. And execute it in the SQL Editor. Does the result contain your package?
 
I selected all query types in query manager.
![image](https://github.com/dbeaver/dbeaver/assets/15009808/1004f604-6f09-4cc6-b15a-c0957a7603bd)

There is no search metadata history, only SQL execution history.
![image](https://github.com/dbeaver/dbeaver/assets/15009808/0643a419-0850-4641-beae-2897a712cf43)

**Comment by LonwoLonwo** [comment]
`SELECT  DISTINCT OWNER,OBJECT_NAME,OBJECT_TYPE FROM (...` - this is the query. It is in focus on your screen.

**Comment by sruby** [comment]
> `SELECT DISTINCT OWNER,OBJECT_NAME,OBJECT_TYPE FROM (...` - this is the query. It is in focus on your screen.



![image](https://github.com/dbeaver/dbeaver/assets/15009808/f411e605-4ba8-4a7c-89d2-173b777123ca)

![image](https://github.com/dbeaver/dbeaver/assets/15009808/8849fc25-caf4-4db6-967d-61be86dda3f8)

"INSERT INTO TPRT" is a highly frequent SQL statement fragment. Not only "INSERT INTO TPRT", but I was also unable to search for most SQL statement fragments with spaces in any packages.

![image](https://github.com/dbeaver/dbeaver/assets/15009808/eb527975-966b-458d-af28-f768eff70440)

almost every package contains "INSERT INTO" and the search result in only a few packages.
![image](https://github.com/dbeaver/dbeaver/assets/15009808/99cfd639-d6f3-4a4c-98d3-b89f7f5c13c6)

**Comment by LonwoLonwo** [comment]
You can do some experiments with this query (that DBeaver uses to find objects)

```sql
SELECT  DISTINCT OWNER,OBJECT_NAME,OBJECT_TYPE FROM (
SELECT OWNER,OBJECT_NAME,OBJECT_TYPE FROM DBA_OBJECTS WHERE OBJECT_TYPE IN ('PACKAGE','PROCEDURE','FUNCTION') AND UPPER(OBJECT_NAME) LIKE '%<your_text>%'  AND OWNER = '<your_schema>' UNION ALL SELECT DISTINCT owner, name, type FROM DBA_SOURCE WHERE UPPER(text) LIKE '%<your_text>%' AND OWNER = 'HR')
ORDER BY OBJECT_NAME
```

**Comment by sruby** [comment]
> You can do some experiments with this query (that DBeaver uses to find objects)
> 
> ```sql
> SELECT  DISTINCT OWNER,OBJECT_NAME,OBJECT_TYPE FROM (
> SELECT OWNER,OBJECT_NAME,OBJECT_TYPE FROM DBA_OBJECTS WHERE OBJECT_TYPE IN ('PACKAGE','PROCEDURE','FUNCTION') AND UPPER(OBJECT_NAME) LIKE '%<your_text>%'  AND OWNER = '<your_schema>' UNION ALL SELECT DISTINCT owner, name, type FROM DBA_SOURCE WHERE UPPER(text) LIKE '%<your_text>%' AND OWNER = 'HR')
> ORDER BY OBJECT_NAME
> ```



it worked
![image](https://github.com/dbeaver/dbeaver/assets/15009808/84d4286b-b0bc-4608-89be-f40f633eff6e)

**Comment by LonwoLonwo** [comment]
And what about this one: 

```sql
SELECT  DISTINCT OWNER,OBJECT_NAME,OBJECT_TYPE FROM (
SELECT OWNER,OBJECT_NAME,OBJECT_TYPE FROM DBA_OBJECTS WHERE OBJECT_TYPE IN ('PACKAGE','PROCEDURE','FUNCTION') AND UPPER(OBJECT_NAME) LIKE '%INSERT INTO TPRT%'  AND OWNER = 'XRISK' UNION ALL SELECT DISTINCT owner, name, type FROM DBA_SOURCE WHERE UPPER(text) LIKE '%INSERT INTO TPRT%' AND OWNER = 'XRISK')
ORDER BY OBJECT_NAME
```

**Comment by sruby** [comment]
> And what about this one:
> 
> ```sql
> SELECT  DISTINCT OWNER,OBJECT_NAME,OBJECT_TYPE FROM (
> SELECT OWNER,OBJECT_NAME,OBJECT_TYPE FROM DBA_OBJECTS WHERE OBJECT_TYPE IN ('PACKAGE','PROCEDURE','FUNCTION') AND UPPER(OBJECT_NAME) LIKE '%INSERT INTO TPRT%'  AND OWNER = 'XRISK' UNION ALL SELECT DISTINCT owner, name, type FROM DBA_SOURCE WHERE UPPER(text) LIKE '%INSERT INTO TPRT%' AND OWNER = 'XRISK')
> ORDER BY OBJECT_NAME
> ```

![image](https://github.com/dbeaver/dbeaver/assets/15009808/32a110a6-8e73-4b44-85e4-4ebaac7b4cb5)

**Comment by LonwoLonwo** [comment]
Thanks @sruby 

Now I see the problem.
