### ISSUE TITLE
Special characters aren't properly escaped when doing Advanced Copy

### ISSUE THREAD

**Issue by qishua** [dbeaver/dbeaver#21514]
### Description

先执行个查询，点击查询结果，右键复制为insert，对于结果字段中包含有单引号和双引号的，dbeaver不会转义，导致生成的insert语句执行后和原内容不一致，如字段内容{"afds":"ffff-''--"}, 通过insert执行后，就无法正确解析json了

### DBeaver Version

23.2.2.202310081633

### Operating System

window 10

### Database and driver

mysql 8

**Comment by E1izabeth** [comment]
Hi, @qishua. Could you translate your issue to english?

**Comment by qishua** [comment]
First, execute a query, click on the query result, right-click and copy it as insert. For fields with single or double quotation marks in the result field, dbeaver will not escape, resulting in inconsistency between the generated insert statement and the original content. For example, if the field content {"afds": "ffff - '-"} is executed through insert, JSON cannot be parsed correctly
,  but the data exported by the navica tool can work

**Comment by E1izabeth** [comment]
Unfortunately, I cannot reproduce the issue. DBeaver generates correct SQL and JSON while doing Advanced Copy for value with `"` or `'` - they are escaped when it's needed. Could you provide a footage of the issue and explain what exactly you're doing when you get an error?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
