### ISSUE TITLE
No Physical Key defined 

### ISSUE THREAD

**Issue by mohanedmashaly21** [dbeaver/dbeaver#21510]
### Description

When I try to manually change value of a column in a table It gives the following error 

```
Error saving changes in database

Reason:
No unique key defined
```

But, If I tried to update using normal SQL query it will updates successfully. Also, the table has a primary key so I believe it should work successfully. 

### DBeaver Version

22.3.2

### Operating System

macOS Monterey 12.4

### Database and driver

Postgres 

### Steps to reproduce

1. Open schema for any table.
2. Select the table you want to change value in it. 
3. Try to change the value of the column in any row of the table.

**Comment by serjiokov** [comment]
@mohanedmashaly21, can you provide DDL for your use case, please.

**Comment by mohanedmashaly21** [comment]
Yep sure here you go, 

The DDL model for the table is : 

```
CREATE TABLE public."Table" (
         ........
	"attribute_name" int NOT NULL,
	"Id" varchar NOT NULL DEFAULT nextval('"Player_Id_seq"'::regclass),
	CONSTRAINT "PK_Player" PRIMARY KEY ("Id")
        ......
);
```

when I try to change attribute_name manually it outputs the below error : 

<img width="654" alt="Screen Shot 2023-10-12 at 5 08 20 PM" src="https://github.com/dbeaver/dbeaver/assets/146728172/29915cce-3bbc-4a17-9b75-6f6200a17bd5">

**Comment by LonwoLonwo** [comment]
Is this a new table? Did you create it right before data inserting? Could you please refresh your table and check, that PK is in the keys list and after that try to insert data again?

**Comment by mohanedmashaly21** [comment]
Un-fortunately No, it is has been created a long while ago and to be sure I did try to refresh now and still output the same error. 

Are we suspecting that there is something wrong with table metadata where it does not read there is a primary key

**Comment by LonwoLonwo** [comment]
Also, could you try to turn on this setting in your connection settings and try again after reconnect?

![2023-10-13 11_33_26-AnyDesk](https://github.com/dbeaver/dbeaver/assets/45152336/68de7cfd-2907-415c-9050-8ad0eb8be565)

**Comment by mohanedmashaly21** [comment]
Still Same error

**Comment by LonwoLonwo** [comment]
I can not reproduce the issue with the provided DDL.

Could you please open the Keys tab, check that your PK is in the list, and after that, try to change the data?

Also, is this issue actually only for this table or all tables in your connection?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by rade-radovic** [comment]
I had this issue. For me, the issue appeared when I made a query that went ```select column_1, column_2...```
Then I tried to change the value of some fields in the table that I got as a result of the query.

What worked for me was not to select certain columns in my query, but to select *. When I changed the data in the table I got as a result, the issue was not present.

**Comment by aleksa213playtronix** [comment]
i have this issue as well

**Comment by E1izabeth** [comment]
Please provide clear steps to reproduce the issue.

**Comment by aleksa213playtronix** [comment]
same thing that is written here
https://github.com/dbeaver/dbeaver/issues/21510#issuecomment-2208779084

**Comment by E1izabeth** [comment]
We're unable to reproduce the issue by the steps provided in the issue description. So, we need answer for the questions asked
https://github.com/dbeaver/dbeaver/issues/21510#issuecomment-1763960606

**Comment by aleksa213playtronix** [comment]
link is sending to the wrong comment
i have the same issue as rade-radovic

I had this issue. For me, the issue appeared when I made a query that went select column_1, column_2...
Then I tried to change the value of some fields in the table that I got as a result of the query.

What worked for me was not to select certain columns in my query, but to select *. When I changed the data in the table I got as a result, the issue was not present.

**Comment by E1izabeth** [comment]
Thank you for additional information. We'll try reproducing it.

**Comment by E1izabeth** [comment]
Unfortunately, I can't reproduce the issue, Both "select" queries (with columns and with *) give the same result for me.

**Comment by arhayka** [comment]
@rade-radovic @aleksa213playtronix Could you please try to check this box in the Connection settings. This could help to solve the issue:
![image](https://github.com/user-attachments/assets/4cba692d-63c1-46e4-9e84-bf04c2a077c9)

**Comment by aleksa213playtronix** [comment]
@arhayka thanks for the suggestion but it didn't help
i still have to fetch the whole record in order to change one field

**Comment by arhayka** [comment]
@aleksa213playtronix Thank you for the quick response
Could you please take a screenshot of the grid with the query result? To see what is in the top left corner and the table headers.

<img width="702" alt="Screenshot 2024-09-05 at 15 49 41" src="https://github.com/user-attachments/assets/322188b3-0774-4e57-8659-ac06b76c7b01">

**Comment by aleksa213playtronix** [comment]
if i select all columns like this then it works, i can change fields
![Screenshot from 2024-09-05 16-36-32](https://github.com/user-attachments/assets/2c591178-e94f-43df-9752-affe44c62f33)

**Comment by aleksa213playtronix** [comment]
if i select only one field then i cannot change it's value
![Uploading Screenshot from 2024-09-05 16-37-34.png…]()

**Comment by aleksa213playtronix** [comment]
if i select only one column then i cannot change it's values
![Screenshot from 2024-09-05 16-37-34](https://github.com/user-attachments/assets/181fe7b0-e2ef-4725-ba63-973d2cd97018)

**Comment by aleksa213playtronix** [comment]
here is an example
![Screenshot from 2024-09-05 16-41-09](https://github.com/user-attachments/assets/511ca98c-eff1-4594-80fc-0ef285387449)

**Comment by aleksa213playtronix** [comment]
and here are my configs
![Screenshot from 2024-09-05 16-41-47](https://github.com/user-attachments/assets/1d2562a0-4ed4-45ed-8573-b2fd8df816f2)

**Comment by Destrolaric** [comment]
@aleksa213playtronix Hi, by the looks of it, it is an expected behavior. When you select only the columns that are not part of the key, DBeaver cannot edit the fields. To make the values editable, add a `sequence` column in your example.

**Comment by aleksa213playtronix** [comment]
if this is expected behavior then ok
thanks for your time :)
