### ISSUE TITLE
Grammar improvement "Warning: Content representation size is limited by: 100 KB"  

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#21522]
### Description

New version does not show full value in 
Result Panels -> Value 
anymore.
Instead a warning is displayed in red below the area
"Warning: Content representation size is limited by: 100 KB"

![Screenshot_20231013_112211](https://github.com/dbeaver/dbeaver/assets/50481865/66c3bfdc-a746-4c3c-850b-3a42a7356ec4)

Linguistic issues (it's hardly limited "by" but rather "to") aside -- that limited hasn't been there before, but the panel was an easy way to overcome the limit in the Result View, where the value length was limited already.

I think the value length should not be limited in the Panel at all.
If that limit cannot be waived at all (why not, though -- this can't just be the same data as in the View, but has to be fetched separately, hasn't it?) it has to be configurable by the user.

In fact, there's now no (easy) way to fetch the full value at all.

### DBeaver Version

Community Edition 23.2.2.202310081633

### Operating System

Linux, Debian/Sid

**Comment by MashaKorax** [comment]
Hello @2019-05-10 Thanks for your grammar suggestion. 
You can change this limit on this preference page here 
![image](https://github.com/dbeaver/dbeaver/assets/84867187/e1a3cdb4-98b3-46d7-81bb-b883361efb18)

**Comment by MashaKorax** [comment]
Change "Warning: Content representation size is limited by: 100 KB"  preposition **by** on **to**

**Comment by 2019-05-10** [comment]
> Hello @2019-05-10 Thanks for your grammar suggestion. You can change this limit on this preference page here ![image](https://user-images.githubusercontent.com/84867187/274928059-e1a3cdb4-98b3-46d7-81bb-b883361efb18.png)

Thanks.
But that is hardly straight forward and hard to find.
And what exactly _is_ the point of the limit? What would be a sensible value, what happens if I set an absurdly high limit?

a) that red warning should be a link to exactly that setting
b) there needs to be a explanation -- I wouldn't recognize the view as an "Editor", hence not connect that setting with exactly that view
c) there should be a way to completely disable any limit -- the point of a limit is not clear hence one cannot know what size to set. Setting "0" causes the warning to state a limit of "1 KB", but 0 != 1.

**Comment by serjiokov** [comment]
Hi, the main reason of using it is informing users of restricted displaing content and avoid product freezing while loading huge data in editor that does not suite well for it. It mostly designed to inform user who handle (editing) large object like JSONs

**Comment by vampirepapi** [comment]
> Hello @2019-05-10 Thanks for your grammar suggestion. You can change this limit on this preference page here ![image](https://private-user-images.githubusercontent.com/84867187/274928059-e1a3cdb4-98b3-46d7-81bb-b883361efb18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTk1NTMsIm5iZiI6MTcwOTcxOTI1MywicGF0aCI6Ii84NDg2NzE4Ny8yNzQ5MjgwNTktZTFhM2NkYjQtOThiMy00NmQ3LTgxYmItYjg4MzM2MWVmYjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEwMDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYjllMmIxZTgxNjAwNDcxMTk5ZTEwMTIwN2M5YWIxOWNiYjlmNTYzYWI4OTc3ZTE3ZTNhN2EwMTY0ZjA1MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UHZLVkSlYEZAp26H209OAPXCWCdXojcdO4-0arOAHDc)

thanks mate
