### ISSUE TITLE
Downloaded newest version, now forcing me to use safari to authenticate Snowflake

### ISSUE THREAD

**Issue by wallygator470** [dbeaver/dbeaver#21527]
### Description

I downloaded newest version of DBeaver, now when I try to use any of my Snowflake connections it forces me to authenticate through Safari when Firefox is my default browser.  We use Okta to authenticate and are forced to use external browser.  I have tried to install older versions, but nothing works.  The main problem I have here is when I try to authenticate using the new pop up safari window it cannot get to okta at all and just sits there and hangs on me. The browser window also says it is a dbeaver window and does not actually open safari.  How I know it is safari that is being opened is I get an email saying I have a new sign-on detected email that is sent to me.  
![image](https://github.com/dbeaver/dbeaver/assets/33906196/5224bc2e-98dc-4d8a-be19-3f39b0773621)

Any help here is greatly appreciated to get this back to working.  I would rather use one tool to connect to all my databases.

here is my browser setting:
![image](https://github.com/dbeaver/dbeaver/assets/33906196/13f0d154-c828-4867-aa99-e0e0dfd20df3)

### DBeaver Version

23.2.3

### Operating System

macos ventura 13.5.1

### Database and driver

Snowflake
Newest snowflake driver

### Steps to reproduce

1. try to connect to a snowflake database
2. safari window pops open
3. type in user name and password
4. it tries to okta authenticate and hangs

**Comment by E1izabeth** [comment]
Thank you for bug report. You can turn this off by unchecking `Open auth links in embedded browser` setting. 
![image](https://github.com/dbeaver/dbeaver/assets/20579256/7ec853a3-9286-479f-ba29-2d02f228e8d6)

**Comment by wallygator470** [comment]
Thank you that cleared this up for me.  Not sure how that all of the sudden got enabled or if it is just a new feature, but I can now move forward again.

**Comment by Destrolaric** [comment]
duplicate https://github.com/dbeaver/dbeaver/issues/21341
