### ISSUE TITLE
Cannot log in with Azure credentials anymore

### ISSUE THREAD

**Issue by NicolWeis** [dbeaver/dbeaver#21533]
### Description

Hi!
This is my first issue I post here (and the first serious issue I ever have had with dbeaver after having used it in several years), please bear with me. After upgrading dbeaver to the most recent version, I cannot connect to my database anymore. It looks as if dbeaver uses some kind of internal browser for authentication. But when I enter my credentials I seem to be in a loop. The authentication starts again - and that never ends, I cannot connect to my azure database at all. Sometimes this browser showed a error text saying "Cannot connect to localhost" although my connections set up with Azure database host names which point to their respective IP addresses.

Is there a workaround for this? I tried in the preferences Web browser => use Chrome, but that did not work. Can I change anywhere to use Chrome again?

Can you please fix? dbeaver became unusable for me :(  

### DBeaver Version

23.2.2

### Operating System

Windows 10

### Database and driver

I use Azure SQL driver with an Azure database 

### Steps to reproduce

Try to connect to an Azure database with azure username and password.
Intern browser opens and asks to log in. Window opens to confirm idendity (2FA).
I get the message "Authentication complete. You can close the browser and return to the application."
I click on the database and it asks me again to log in.

**Comment by E1izabeth** [comment]
Please try switching the setting `Open auth links in the embedded browser`
![image](https://github.com/dbeaver/dbeaver/assets/20579256/7ec853a3-9286-479f-ba29-2d02f228e8d6)

**Comment by E1izabeth** [comment]
@NicolWeis does it help?

**Comment by Destrolaric** [comment]
@NicolWeis Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
