### ISSUE TITLE
CTRL+6 stopped working in Version 23.2.2.202310081633

### ISSUE THREAD

**Issue by Rexw099** [dbeaver/dbeaver#21543]
### Description

Keyboard shortcut CTRL+6 to hide/show panel stopped working with the upgrade to 23.2.2.202310081633

### DBeaver Version

23.2.2.202310081633

### Operating System

windows

### Database and driver

All

### Steps to reproduce

Trying CTRL+6 after running a query and getting results.

**Comment by E1izabeth** [comment]
Please try using `Ctrl+T`. We changed this shortcut recently because of the issues with AZERTY keyboards.
Also you can change shortcuts in preferences
![image](https://github.com/dbeaver/dbeaver/assets/28875055/2228273b-357c-471b-b92a-a5ec0447b357)
