### ISSUE TITLE
Horizontal tabs for procedure editor

### ISSUE THREAD

**Issue by xmedeko** [dbeaver/dbeaver#2154]
When I start to edit a DB procedure, the window is opened with the vertical parts: Properties, Parameters and Source. The Source takes about 1/3 of the screen. I  would like to have have a classic simple horizontal tabs instead: Properties, Parameters and Source. When I edit a procedure, I very rarely need to see everything, so switching tabs is OK for me and would have almost whole window space for the Source.
(I know I can collapse Properties and change size of the Source, but it's annoying to do it every time.)
Note: I am used to this simple tab layout from HeidiSQL.

**Comment by serge-rider** [comment]
Agreed. However different people have different preferences.
I think it would be better to make vertical tabs collapsible + save tabs state for particular object types. So you could configure this just once.

**Comment by serge-rider** [comment]
Please check how it looks in 4.2.2. Perhaps it is good enough?

**Comment by xmedeko** [comment]
Yes, it's much better. Just the "Properties" tab is bigger and bigger with every new opened procedure. (Just a few pixel is added to the height.)

Also, it would be cool to really collapse/uncollapse the tabs by clicking (or double clicking) on them. The splitter between Properties and Parameters is IMHO to small to be usable, so it may be removed.

**Comment by serge-rider** [comment]
Will try to improve this after 4.2.3

**Comment by xmedeko** [comment]
Tried the 5.0.2 and the "Properties" stays the same. The current solution is pretty usable for me even without collapse by double click. So closing this issue. Thanks.
