### ISSUE TITLE
Dbeaver - Snowflake authentication not opening in default web browser (chrome) 

### ISSUE THREAD

**Issue by pvvkchaitanya** [dbeaver/dbeaver#21546]
### Description

Hello

 I am using dbeaver to connect to snowflake from many months but with the recent upgrade the authentication is not opening in  windows  default browser (chrome). Instead a new window opens within dbeaver itself. 

![image](https://github.com/dbeaver/dbeaver/assets/62654255/4414223b-3b60-48ef-b1dd-1cf52e5e57eb)

After successfully authenticating I have to manually close the little pop up window 

![image](https://github.com/dbeaver/dbeaver/assets/62654255/6280fb58-e682-4bc7-906e-a3b00428c4d8)

I tried changing the web browser under preferences but still its opening in chrome. 

![image](https://github.com/dbeaver/dbeaver/assets/62654255/504ac5a6-7a24-4535-aba6-8df62c719f75)

### DBeaver Version

Version 23.2.2.202310081633

### Operating System

Windows 10 enterprise

### Database and driver

Snowflake jdbc 3.14.2

**Comment by pvvkchaitanya** [comment]
After submitting this I found this https://github.com/dbeaver/dbeaver/issues/21533 and changed the setting to uncheck the embedded browser. Its working after this and opening in chrome like earlier. 

![image](https://github.com/dbeaver/dbeaver/assets/62654255/d0df097d-fab5-4171-8eb8-971f24f7440a)

**Comment by Destrolaric** [comment]
Duplicate https://github.com/dbeaver/dbeaver/issues/21341
