### ISSUE TITLE
Problem tables with database - show only

### ISSUE THREAD

**Issue by Timez06** [dbeaver/dbeaver#21558]
### Description

Hello, i have problem with filter show only. I marked the database to show me one table. However, when I add it, each time I only have Tables(...) and no table in it.

when I remove the filter, all tables are visible. If I select only one, everything pops up empty and under the database there is only Tables(...)

### DBeaver Version

23.2.2

### Operating System

Win10

### Database and driver

Mysql

### Steps to reproduce

1. connect to mysql
2. I see the tables I am interested in
3. I want to see only one, I click on it and it gives me show only.
4. There is no table
5. There is only the inscription Tables(...)

**Comment by LonwoLonwo** [comment]
Hello @Timez06 

Could you please provide screens before and after the "show only"?

**Comment by Timez06** [comment]
I also noticed that tables that are default are displayed using show/hide, but tables we created are not. @LonwoLonwo

**Comment by LonwoLonwo** [comment]
Screen for this will also be helpful because I do not understand - what "default tables" are.

**Comment by Timez06** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/17595289/750129fd-1161-4b6d-9968-58016ff62174)
![image](https://github.com/dbeaver/dbeaver/assets/17595289/1e0c4a6e-f35b-4653-8ffe-338fdeb18b73)

**Comment by LonwoLonwo** [comment]
Could you please provide your table DDL? including a catalog name.

**Comment by Timez06** [comment]
unfortunately I can't share. while some tables are available using the show only filter. Can you at least help where the problem may be?

**Comment by LonwoLonwo** [comment]
You can enable the Query Manager with enabled filters https://github.com/dbeaver/dbeaver/wiki/Query-Manager
and find the query for the tables list reading. You can execute this query and check.

Also, you can remove all filters and then provide me your table DDL

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
