### ISSUE TITLE
New Version Makes Script Generation Inconvenient

### ISSUE THREAD

**Issue by Jingyu-Yan** [dbeaver/dbeaver#21550]
**Is your feature request related to a problem? Please describe.**
In the new version, the ‘Generate Script’ button in the result set’s bottom toolbar has been hidden and moved into a submenu under the ‘Save’ button. This has increased my workload as my job primarily involves extracting update scripts for submission, making this button very important to me.

**Describe the solution you'd like**
I would like to request that the ‘Generate Script’ button be placed directly on the toolbar as it was before.

**Describe alternatives you've considered**
Alternatively, allow users to customize the toolbar settings to decide which primary buttons they need.

**Additional context**
Please understand that the content has been translated using GPT due to an inconvenient working environment for screenshots.

**Comment by E1izabeth** [comment]
You're talking about this button, right?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/5fe44252-1ab4-4305-8098-f17b43b7a5fa)

**Comment by E1izabeth** [comment]
We haven't removed it. This button should be available by clicking on the arrow in `Save` button.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by Jingyu-Yan** [comment]
Yes, I frequently use this button. I hope a configuration can be added for this button to allow me to conveniently click on it directly.
