### ISSUE TITLE
dbeaver table editing is blocked - some fields are Read-only: No Corresponding table column

### ISSUE THREAD

**Issue by avishayhaliva** [dbeaver/dbeaver#21566]
### Description

Dbeaver table editing is blocked for some fields .
Fields not recognized as alphanumeric are blocked.
![image](https://github.com/dbeaver/dbeaver/assets/148329290/815e21c9-cf14-4630-b34c-8fded1898cac)
![image (1)](https://github.com/dbeaver/dbeaver/assets/148329290/37fc7583-2e93-45cc-9357-cbe6ebad7710)
![bug](https://github.com/dbeaver/dbeaver/assets/148329290/41c5d447-8f96-45ff-8872-dfbbe41fdf5f)

### DBeaver Version

23.2.2

### Operating System

Windows 10 Enterprise

**Comment by LonwoLonwo** [comment]
Hello @avishayhaliva 

Could you please provide your table DDL?

**Comment by avishayhaliva** [comment]
- ASHRAF.ZSYTAB2605 definition
 
-- Drop table
 
-- DROP TABLE ASHRAF.ZSYTAB2605;
 
CREATE TABLE ASHRAF.ZSYTAB2605 (
	XXCONO DECIMAL(3,0) NOT NULL,
	XXDIVI NCHAR NOT NULL,
	XXSTCO NCHAR NOT NULL,
	XXZKY1 NCHAR NOT NULL,
	XXZKY2 NCHAR NOT NULL,
	XXZKY3 NCHAR NOT NULL,
	XXZKY4 NCHAR NOT NULL,
	XXZKY5 NCHAR NOT NULL,
	XXZKY6 NCHAR NOT NULL,
	XXZKY7 NCHAR NOT NULL,
	XXLNCD NCHAR NOT NULL,
	XXTX40 NCHAR NOT NULL,
	XXPARM NCHAR NOT NULL,
	XXRGDT DECIMAL(8,0) NOT NULL,
	XXRGTM DECIMAL(6,0) NOT NULL,
	XXLMDT DECIMAL(8,0) NOT NULL,
	XXCHNO DECIMAL(3,0) NOT NULL,
	XXCHID NCHAR NOT NULL,
	XXLMTS DECIMAL(18,0) NOT NULL
);

**Comment by LonwoLonwo** [comment]
I can not reproduce your issue for now.

![2023-10-18 17_20_34-DBeaver Ultimate 23 2 3 - _PUB400 COM 2 1_ Script-121](https://github.com/dbeaver/dbeaver/assets/45152336/f8947937-44ac-44d7-9d24-a383bf5398d2)

What driver version do you use?

You can check in with the "Test Connection" button.

**Comment by avishayhaliva** [comment]
driver - AS/400 Toolbox for Java JDBC Driver 13.3

server - DB2 UDB for AS/400 07.03.0000 V7R3m0

**Comment by LonwoLonwo** [comment]
Ok, I see now. For me, it works well with the old driver version - 9.something. 
So, this is the driver issue.

![2023-10-19 12_35_56-DBeaver 23 2 3 - ZSYTAB2605](https://github.com/dbeaver/dbeaver/assets/45152336/a6a59fd0-2c85-4b8c-ac85-3a40b5898848)

You can downgrade your version to 11.2 to fix your issue.

**Comment by avishayhaliva** [comment]
Solved, thank you so much.
