### ISSUE TITLE
about dbeaver Install New Software HANA Tools

### ISSUE THREAD

**Issue by 1774256915** [dbeaver/dbeaver#21563]
### Description

Using dbaver Install New Software to install HANA Tools causes dbaver to connect to the database can not be right mouse click to view the database table no pop-up window, which is HANA Tools URL: https://tools.hana.ondemand.com/2023-03

### DBeaver Version

DBaver 23.2.2

### Operating System

win10

### Steps to reproduce

1.help->Install New software
2.HANA Tools URL: https://tools.hana.ondemand.com/2023-03

**Comment by LonwoLonwo** [comment]
Hello @1774256915 

Could you please answer a few questions for me?
What is the reason to use Hana Tools in DBeaver for you?
Does the Hana connection work well without this tool?

> can not be right mouse click to view the database table no pop-up window

Please provide any footage for this, it is not clear for now.

**Comment by 1774256915** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/44608744/473e50a7-8745-4036-871c-a7b4ab64e6f0)
![image](https://github.com/dbeaver/dbeaver/assets/44608744/9999d1ff-eda7-4d9a-8795-968ade10145e)
Thanks for the reply.
I want to install HANA TOOLS to replace HANA STUDIO view modeling through DBeaver.
After uninstalling HANA TOOLS, DBeaver can be used normally, installing HANA TOOLS causes some functions of DBeaver to fail.
After installing HANA TOOLS, the right mouse click on anything under "Database Navigate" does not respond.

**Comment by LonwoLonwo** [comment]
> the right mouse click on anything under "Database Navigate" does not respond.

Still, I need some footage of this part.

Also, could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by 1774256915** [comment]
[.log](https://github.com/dbeaver/dbeaver/files/13038413/default.log)
Okay, this is the log file.
The intuitive way to do this is to install HANA TOOLS, which may take you a few minutes.

**Comment by Destrolaric** [comment]
@1774256915 Could you try to download Hana Tools for version 06 or 09 instead?
https://tools.hana.ondemand.com/2023-06/

**Comment by 1774256915** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/44608744/09f99ded-b377-4864-a355-769cb1609e38)
Officials will be released later, right now it's only updated to 2023-03

**Comment by Destrolaric** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/20579256/f73a8c32-3205-4557-a2b4-da0ab59a1693)
@1774256915 By the log it looks like plugin requires jdt components, you can install them in https://download.eclipse.org/releases/2023-06/.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
