### ISSUE TITLE
Set Strict Mode for mysql for data import

### ISSUE THREAD

**Issue by alberttwong** [dbeaver/dbeaver#21579]
```
SQL Error [1064] [42000]: Insert has filtered data in strict mode
```

from
```
Error occurred during batch insert
(you can disable batch insert in order to skip particular rows).

Reason:
SQL Error [1064] [42000]: Insert has filtered data in strict mode, txn_id = 15 tracking sql = select tracking_log from information_schema.load_tracking_logs where job_id=10181
```

I got the following error when I try to import CSV data into mysql / StarRocks.  Is there a way to set strict mode to false? 

![Screenshot 2023-10-18 at 12 26 46 PM](https://github.com/dbeaver/dbeaver/assets/749093/8ecb67fa-f4d6-4cca-a46f-e20ac9b7ae2f)

**Comment by E1izabeth** [comment]
Related feature request #18964

**Comment by LonwoLonwo** [comment]
Hello @alberttwong 

Probably this line from [the documentation](https://docs.starrocks.io/en-us/3.0/loading/InsertInto) can help:

> You can set the session variable enable_insert_strict to false to allow the transaction to continue by filtering out the rows that mismatch the table.

**Comment by LonwoLonwo** [comment]
Could you please provide your table DDL? Or where are you keeping your strict mode setting?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
