### ISSUE TITLE
Autocomplete on columns in where clause not formatting properly

### ISSUE THREAD

**Issue by cygnim** [dbeaver/dbeaver#21589]
### Description

Previously, when writing a query in Postgres, the autocomplete feature of DBeaver would properly wrap column names with capital letters, in the where clause, in quotes. In the current version, they're not being wrapped in quotes and the query fails to execute due to the syntax error.

e.g.
`SELECT * FROM "Users" WHERE UserId = 0;`
This will not execute as UserId needs to be in quotes. The correct syntax is:
`SELECT * FROM "Users" WHERE "UserId" = 0;`

This functionality was working in a previous release.

### DBeaver Version

23.2.2.202310081633

### Operating System

macOS Sonoma 14.0

### Database and driver

Database: Postgres 14.6 running in Alpine Linux Docker container.

### Steps to reproduce

Write a query for a table with columns that have capitalized first letters. The column names in the where clause will not be contained within quotes, which is the proper syntax.
```
SELECT * FROM "Users" WHERE "UserId" = 0; -- proper and expected syntax
SELECT * FROM "Users" WHERE UserId = 0; -- actual auto-generated syntax
```

**Comment by LonwoLonwo** [comment]
Hello @cygnim 

Thanks for the report. I can reproduce it.

**Comment by E1izabeth** [comment]
In addition, I see fully qualified name for a query with only one source and alias for this source
![image](https://github.com/dbeaver/dbeaver/assets/28875055/4e1d8b98-4d4c-4ee6-905b-2fcd618cad1f)

1. Maybe it's better to use alias in autocompletion suggestion if possible?
2. Probably there is no need to show fully qualified name if the query has only one source - up to discussion.

**Comment by mkgrgis** [comment]
Look like this is duplicate https://github.com/dbeaver/dbeaver/issues/20199

**Comment by cygnim** [comment]
This is not a duplicate and the issue I reported has been resolved.
