### ISSUE TITLE
PostgreSQL autocomplete is not properly escaping table names

### ISSUE THREAD

**Issue by cygnim** [dbeaver/dbeaver#21587]
### Description

This was working previously but is broken in version 23.2.2.202310081633 on macOS. 

If I write a postgresql query for a table with Pascal casing (e.g. Users), the autocomplete is incorrectly suggesting the table name without quotes. This query will throw an error in postgresql.

`SELECT * FROM Users;`

Previously, dBeaver would correctly surround the table name with quotes:

`SELECT * FROM "Users";`

### DBeaver Version

23.2.2.202310081633

### Operating System

macOS Sonoma 14.0

### Database and driver

Database: PostgreSQL 14.6 running in Docker container with alpine-linux

### Steps to reproduce

Write any query with a table name that starts with a capital letter. DBeaver autocomplete is not wrapping in quotes in the autocomplete.

**Comment by E1izabeth** [comment]
I can't reproduce you issue.
The suggestions
![image](https://github.com/dbeaver/dbeaver/assets/28875055/c94e9a5f-8c88-4fc3-a517-c79d7e485584)
The query after applying suggestion
![image](https://github.com/dbeaver/dbeaver/assets/28875055/01ef9cd8-e078-4c50-a5d1-f0392c55b043)

Could you show your `Code Completion` preference page for the connection?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/8d2e97e3-b014-4e7e-8788-435655055f83)

**Comment by jcachat** [comment]
I am having the exact same problem after upgrading from 23.2.1 to 23.2.2.  My Code Completion settings are exactly the same as what you showed above.

**Comment by jcachat** [comment]
Sorry - not having the exact same issue as op:

It is correctly quoting table names for me but it is NOT quoting column names in a where clause.  It does quote column names in the result columns though - very weird.

So this is the result with all of the quoting applied as it's happening for me:

select "Name" from "Employee" where HireDate > '2023-10-01'

Only "HireDate" is not quoting for me.

**Comment by cygnim** [comment]
Ugh. My apologies, it is not the table name population, it is the column names in the where clause for me as well. Will close and open a new ticket.

**Comment by cygnim** [comment]
Closed due to inaccurate description- use this issue instead https://github.com/dbeaver/dbeaver/issues/21589
