### ISSUE TITLE
Oracle ORA-01460 "ORA-01460: unimplemented or unreasonable conversion requested"

### ISSUE THREAD

**Issue by hal1961** [dbeaver/dbeaver#21586]
### Description

Unable to get the table definition from a Oracle 9i database

### DBeaver Version

Coomunity Edition 23.2.2.202310081633

### Operating System

Windows 11

### Database and driver

Connected to Oracle 9i Database 9.2.0.1.0 with oracle_thin driver
The database language is Italian.

### Steps to reproduce

1. Expand the connection node;
2. Expand "Schemas";
3. Expand one schema;
4. Expan tables: getting a first error message saying:
5. "SQL Error [1460] [72000]: ORA-01460: conversione richiesta non implementata o irrazionale
"  Error : 1460, Position : 45, Sql = SELECT 
c.*,c.TABLE_NAME as OBJECT_NAME FROM ALL_TAB_COLS c
WHERE c.OWNER=:1  AND c.TABLE_NAME=:2 , OriginalSql = SELECT 
c.*,c.TABLE_NAME as OBJECT_NAME FROM ALL_TAB_COLS c
WHERE c.OWNER=? AND c.TABLE_NAME=?, Error Msg = ORA-01460: conversione richiesta non implementata o irrazionale
ORA-01460: conversione richiesta non implementata o irrazionale"

In English the translation of the error is "unimplemented or unreasonable conversion requested",

6. Let's go on activating the node of a table;
7. Activate the context menu and hit "Generate SQL" -> "DDL";
8. Again the same error comes up:
"Error running DDL generation
SQL Error [1460] [72000]: ORA-01460: conversione richiesta non implementata o irrazionale"
9. Of course no DDL code will follow.

**Comment by LonwoLonwo** [comment]
Hello @hal1961 

Could you try to execute this query?

```sql
SELECT 
c.*,c.TABLE_NAME as OBJECT_NAME FROM DBA_TAB_COLS c
WHERE c.OWNER='<any_your_schema_name>'
```

DBeaver uses this query for columns metadata reading.

Also, could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by hal1961** [comment]
Dear Anastasiya,

your query made me understand!
Running it I got an error of table not found regarding DBA_TAB_COLS, so I guessed I was lacking some permissions. Then I changed the connection string passing a different user and the error went away.

Thank you

**Comment by LonwoLonwo** [comment]
Thanks for the update!

**Comment by Dicky-Moe** [comment]
In my case, this helped: http://itpsolver.com/dbeaver%EC%97%90%EC%84%9C-%EA%B5%AC%EB%B2%84%EC%A0%84%EC%9D%98-%EC%98%A4%EB%9D%BC%ED%81%B4oracle-9-2-0-7-0-%EC%A0%91%EC%86%8D-%ED%9B%84-%EC%A2%8C%EC%B8%A1-database-navigator%EC%97%90%EC%84%9C/
