### ISSUE TITLE
Unreadable characters in the name of the project or database

### ISSUE THREAD

**Issue by PavelIvanov7** [dbeaver/dbeaver#21584]
### Description

When working with с Dbeaver 23.0.4  - Unreadable characters in the name of the project or database . A copy of the enclosed screen.  **Please help me fix it !!!!!

![изображение](https://github.com/dbeaver/dbeaver/assets/148449479/310a2578-3173-41b4-99a0-3c4c5ba71522)

### DBeaver Version

23.0.4.202305071722

### Operating System

Microsoft Windows 10.0.19044

**Comment by E1izabeth** [comment]
Unfortunately, the quality of your screenshot is poor, so we can't see what's the issue and where is "unreadable characters". Could you send the screenshot here directly by doing Ctrl+V to the text area for the comment (without pasting to Microsoft Word)?

**Comment by PavelIvanov7** [comment]
![изображение](https://github.com/dbeaver/dbeaver/assets/148449479/f20a541f-0862-4243-9b5a-ba1b507dd5ed)

**Comment by PavelIvanov7** [comment]
window or bookmark projects or database => Unreadable characters 

Help !

**Comment by E1izabeth** [comment]
Oh, I see. Could you try changing `Main font` in preferences?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/9330a74e-8989-4c16-b878-e4a12a8af0eb)

![image](https://github.com/dbeaver/dbeaver/assets/28875055/c7d0e740-6e2d-488f-9889-da2d68d2575a)

**Comment by PavelIvanov7** [comment]
Thanks a lot ! I'll try to change the settings within an hour . I’ll write about the results right away

**Comment by PavelIvanov7** [comment]
Your recommendations led to a positive result . Thank you very much . I admire your professionalism

**Comment by PavelIvanov7** [comment]
good luck and have a nice day

**Comment by E1izabeth** [comment]
Thank you for update.
