### ISSUE TITLE
StarRocks database support

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#21583]
> What is StarRocks?
> 
> StarRocks is a next-generation, blazing-fast massively parallel processing (MPP) database designed to make real-time analytics easy for enterprises. It is built to power sub-second queries at scale.
> 
> StarRocks has an elegant design. It encompasses a rich set of features including fully vectorized engine, newly designed cost-based optimizer (CBO), and intelligent materialized view. As such, StarRocks can deliver a query speed far exceeding database products of its kind, especially for multi-table joins.
> 
> StarRocks is ideal for real-time analytics on fresh data. Data can be ingested at a high speed and updated and deleted in real time. StarRocks empowers users to create tables that use various schemas, such as flat, star, and snowflake schemas.
> 
> Compatible with MySQL protocols and standard SQL, StarRocks has out-of-the-box support for all major BI tools, such as Tableau and Power BI. StarRocks does not rely on any external components. It is an integrated data analytics platform that allows for high scalability, high availability, and simplified management and maintenance.

We can add this database to the list of all databases as a fork of MySQL.

https://docs.starrocks.io/en-us/3.0/integrations/IDE_integrations/DBeaver

https://docs.starrocks.io/en-us/3.0/quick_start/deploy_with_docker

**Comment by dishkakrauch** [comment]
Any news?

**Comment by LonwoLonwo** [comment]
Hello @dishkakrauch 

This task is scheduled in our feature releases plan.
