### ISSUE TITLE
How do I select All and copy everything in hex viewer?

### ISSUE THREAD

**Issue by yanOnGithub** [dbeaver/dbeaver#2159]
The binary column is 816 bytes long. I have got only one screenful of it after pressing Ctrl+A and Ctrl+C, then paste in HxD (hex editor).

**Comment by yanOnGithub** [comment]
Sooner or later I am going to ask for everything that a hex editor does, including #2138. So I should probably copy and paste things out. #2138 may not be necessary if I can copy and paste things out.

**Comment by serge-rider** [comment]
Do you mean - copy in hex format? This is not supported.

If you need just text then you can switch to text format (in value view panel toolbar). Or open hex viewer in separate editor window (shift+enter or value in results viewer) and then <kbd>ctrl+a</kbd> and copy.

**Comment by yanOnGithub** [comment]
I have lots of non-printable characters.

table grid cell: worked (60k char)
value panel binary mode hex: cropped
value panel binary mode text: cropped
value panel text mode: cropped until the first null char

`

**Comment by yanOnGithub** [comment]
shift+enter big hex viewer: cropped until the first null char
