### ISSUE TITLE
Can't connect do DB2 z/OS no active connection / cannot obtain session?

### ISSUE THREAD

**Issue by MDRIDB** [dbeaver/dbeaver#21593]
### Description

Can't connect do DB2 z/OS no active connection / cannot obtain session
===============================================

Hi,

Thanks for reviewing my issues.

I'm trying to connect to IBM DB2 z/OS from DBeaver. However, it is getting connected. I am able see schemas in this DB2 instance.

When I issue query, I am getting 

"Can't connect do DB2 z/OS no active connection / cannot obtain session"

I did DB connection dash board and make connection active as well. same issues coming up.

Errorlog sys:

"Error notifying a preference change in listner . Check log for details"

**I am not sure, which log this message referring to. Do we need to set-up listner in DBeaver ?**

If yes, where should I do that?

DBeaver version 22.2.0 Enterprise (Win10/64bits)

Any hint?

Thanks in advance.

### DBeaver Version

Dbeaver nterprise 22.2.0

### Operating System

windows 10 Enterprise

### Database and driver

Db2 z/os

### Steps to reproduce

Connect DB2 z/os 
issue select query

### Additional context

NA

**Comment by LonwoLonwo** [comment]
Hello @MDRIDB 

Could you please provide the log files from these instructions: https://dbeaver.com/docs/wiki/Log-files/? Thank you.

**Comment by MDRIDB** [comment]
Thanks for weighing in. I a m not able to attach log here due site regulation I have. If you suggest some items to pick from logs, I will do that. Here is what I see as last lines.

```
SESSION 2023-10-19 ...
ecipsebuildId=unknown
javaversion =11.0.12

! ENTRY org.jkiss.dbeaver.model 4 0 2023-10-19
!MESSAGE No active connection
```

Thanks.

**Comment by MDRIDB** [comment]
Thanks for looking. It is a simple issue. In this version, connection drop box is not setting to active DB connection automatically. We need to toggle manually. After doing this, the issue was resolved.

I am not sure, why is not making the   just connected DB as active connection . 

 What is the idea of having this to set as manual step?

Are there any doc to show, how we can set different overlapping view of this tool?

Thanks again.

**Comment by LonwoLonwo** [comment]
Does this happen in the SQL Editor?

And do you have this connection status?

![2023-10-23 14_47_03-DBeaver Ultimate 23 2 3 - _MariaDB 10 9 PROD_ Script-77](https://github.com/dbeaver/dbeaver/assets/45152336/d70f1673-d0c9-42da-b659-e51909d06d46)

Did you provide anything in this field?

![2023-10-23 14_48_13-DBeaver Ultimate 23 2 3 - _MariaDB 10 9 PROD_ Script-77](https://github.com/dbeaver/dbeaver/assets/45152336/faede157-e1ca-45ce-813e-b5f44eaf650d)

**Comment by MDRIDB** [comment]
Thanks for weighing in.

It is not going into connection status of connected DB . It shows 'NA' upon successful connection. It looks weird, earlier versions defaulted to connected DB.

Database/Schema has the actual schema name in connection definition.

Is it a bug in this version ?

Thanks for your guidance.

**Comment by LonwoLonwo** [comment]
And if you will set your schema in your connections settings -> initialization?

**Comment by MDRIDB** [comment]
Thanks again. 

Connection configuration shows schema , 

While making connection it shows username /Password. no info about schema there.

If I hover cursor over connected DB, it shows schema appended to jdbc URL.

**Comment by LonwoLonwo** [comment]
Unfortunately, we can not check what is wrong because we do not have a DB2 z/OS test environment.

Does this query return the correct result for you?

`SELECT CURRENT_SCHEMA FROM SYSIBM.SYSDUMMY1`

We use it for the current schema reading.

**Comment by MDRIDB** [comment]
Thanks for weighing in. I understand.

Yes, query results are correct after setting the database connection info at the top manually.

It retains the last connected DB connection info there and expect to manually point to DB connection . Then all works fine.

I am not sure, whether it is a bug in this version.

Thanks.

**Comment by LonwoLonwo** [comment]
But does the query `SELECT CURRENT_SCHEMA FROM SYSIBM.SYSDUMMY1` return the correct result without manual changes in your connection? Without extra info in the initialization section?

**Comment by MDRIDB** [comment]
NO. This query throwing error in either way.

**Comment by LonwoLonwo** [comment]
Could you please provide me with this error?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide the requested information.
