### ISSUE TITLE
Nested floats show random data with duckdb

### ISSUE THREAD

**Issue by Dino-Burger** [dbeaver/dbeaver#21598]
### Description

Running below code with the duckdb .9.1 plugin I get random results

```
with test_data as (
    Select {'x': 0.1, 'y': 0.2, 'z': 0.3} as aa, {'x': 0.1, 'y': 0.2 } as bb, 'fsadlkjlk52903' as getter
    union all
    Select {'x': 0.1, 'y': 0.2, 'z': 0.3} as aa, {'x': 0.1, 'y': 0.2 } as bb, 'fsadlkj442903' as getter

)
Select * 
From
test_data
Where getter = 'fsadlkj442903'

``` 

![image](https://github.com/dbeaver/dbeaver/assets/56079246/07de10fb-962b-4274-9a09-8eba93a64b75)

It is difficult for me to assess where the problem lies, with dbeaver or with duckdb.

### DBeaver Version

Cimmunity Edition 23.2.2.202310081633

### Operating System

Windows 10 Enterprise

### Database and driver

Duckdb 0.9.1

### Steps to reproduce

1. create an in memory connection to duckdb 0.9.1
2. Execute above query multiple times
3. The result varies with each excution

### Additional context

It is important *not* to write `select aa.*` but to just show the overview of the nested data structure with `select *`.

**Comment by E1izabeth** [comment]
I reproduced the issue. The values are just changes on cell selection. That's really weird. 

https://github.com/dbeaver/dbeaver/assets/28875055/f3ea797a-1c8c-466d-91ef-9efd3e802080

**Comment by E1izabeth** [comment]
Also it's happening on column resize

https://github.com/dbeaver/dbeaver/assets/28875055/b86b6c1f-d7fa-4c54-bd8d-493560c5e6a9

**Comment by ShadelessFox** [comment]
This issue will be fixed in the next release of the DuckDB JDBC driver (0.9.2).

**Comment by LonwoLonwo** [comment]
Can not reproduce anymore with the latest (0.9.2) driver version.

**Comment by LonwoLonwo** [comment]
How to upgrade the DuckDB driver version:

![2023-11-29 11_26_16-DBeaver Ultimate 23 3 0 - _duck_database db_ Script-65](https://github.com/dbeaver/dbeaver/assets/45152336/72bf9cdf-e3d5-40e4-9712-7bc86ed1bf13)

**Comment by Dino-Burger** [comment]
Thanks a lot! I also tested it and it works now!
For those updating the plugin: I needed to restart dbeaver after updating the plugin.
