### ISSUE TITLE
is there any way I can translate any country language to English in another column?

### ISSUE THREAD

**Issue by jgrover21** [dbeaver/dbeaver#21590]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LonwoLonwo** [comment]
Hello @jgrover21 

Could you please be more specific? What is the "country language"? What is "another column"? 
Need more details.

**Comment by E1izabeth** [comment]
DBeaver doesn't provide any translation services

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by jgrover21** [comment]
> Hello @jgrover21
> 
> Could you please be more specific? What is the "country language"? What is "another column"? Need more details.

Japanese to English
