### ISSUE TITLE
how to fix "FATAL: no pg_hba.conf entry for host" for aws rds postgres

### ISSUE THREAD

**Issue by will-shatford** [dbeaver/dbeaver#21616]
### Description

FATAL: no pg_hba.conf entry for host "xxx.xxx.xxx.xxx", user "user", database "postgres", no encryption

host postrgredb.ce3xxxxxxxx.us-east-1.rds.amazonaws.com

### DBeaver Version

Community 23.2.2

### Operating System

Windows 10

### Database and driver

Database: AWS RDS Postgres 15.3

### Steps to reproduce

FATAL: no pg_hba.conf entry for host "xxx.xxx.xxx.xxx", user "user", database "postgres", no encryption

I must be missing something at AWS.  Tried all kinds on inbound rules for the default for VPC security groups:
[default (sg-fcd88ccf)](https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1#SecurityGroups:search=sg-fcd88ccf)

**Comment by aya-morsyali** [comment]
any solution for this ? have the same issue

**Comment by frascthx** [comment]
wait i have this exact same issue when try to connect with sequelize in node js, but if im connecting with DBeaver 23.2.2 it connect normaly

**Comment by frascthx** [comment]
> wait i have this exact same issue when try to connect with sequelize in node js, but if im connecting with DBeaver 23.2.2 it connect normaly

i think i found my solution, it requires ssl connection in option of sequelize, but in dbeaver im not touching ssl tab it connect normaly

**Comment by will-shatford** [comment]
I setup the DB to not need encryption.  Do I still need SSL to connect with DBeaver?

**Comment by frascthx** [comment]
im new in field like this, maybe its your db setting in rds?
- in my config i use public acess and default port 5432
![image](https://github.com/dbeaver/dbeaver/assets/91405797/c4a9b94c-d5f9-4e6c-b12f-63004b3f5f1b)
- my inbound rule is TCP/postgresql port 5432 allowing all ipv4 and ipv6, but i try to allowing only my ipv4 its connect normally too
![image](https://github.com/dbeaver/dbeaver/assets/91405797/4495f7b4-ebd2-47c5-8e53-e5fa621f7c45)
- in dbeaver connection i just playing in main tab only, im not check the use ssl checkbox in ssl tab

**Comment by will-shatford** [comment]
Yep, I did publicly avail and the inbound rule for ipv4, but not ipv6.  I'm going to close the account and start over.  I was also using Rout3 53, which I won't start with the next time around.  I also didn't use any IAM.... maybe I should?  I wish there was a simple tutorial to do this from scratch.

**Comment by will-shatford** [comment]
I set up a whole new account.  Did all the VPC stuff to allow inbound traffic from my IP address.  Now just getting "Connection attempt timed out.", so I'm still missing something.

**Comment by kastil79** [comment]
In your database instance's 'Parameter Group,' change the value of rds.force_ssl to 0, restart the instance, and try to establish the connection again

![image](https://github.com/dbeaver/dbeaver/assets/42352290/8f6a167c-79ea-48ac-bf5a-ffa6bce4fece)

Try: psql --host=xxxxxxxxxx.us-east-1.rds.amazonaws.com --port=5432 --username=postgres --dbname=mydbname

**Comment by will-shatford** [comment]
I'll try this, but... seems like a lot to do.  Because you can't change the values in a default parameter group (default.postgre15), you need to copy that to a new parameter group, which I think you can only do with the CLI.  And then change the ssl to 0.  And then I need to modify the instance to use the new parameter group, which I don't see as an option in "Additional configuration"???   Maybe there is an easier way :-)

**Comment by kastil79** [comment]
> I'll try this, but... seems like a lot to do. Because you can't change the values in a default parameter group (default.postgre15), you need to copy that to a new parameter group, which I think you can only do with the CLI. And then change the ssl to 0. And then I need to modify the instance to use the new parameter group, which I don't see as an option in "Additional configuration"??? Maybe there is an easier way :-)

You don't necessarily have to do it with the AWS CLI for you to be able to modify the default parameter group. In the image I shared, you can see that I did it from the AWS web console. If you prefer, you can create a new custom parameter group of the type 'default.postgre15,' make the changes (rds.ssl_force=0) , and then assign your custom parameter group to your database instance. You can do all of this from the AWS web console

**Comment by E1izabeth** [comment]
@will-shatford is your problem solved?

**Comment by will-shatford** [comment]
Nope.  I made a copy of the default.postgres15, changed the ssl to 0, and assigned it to the DB instance.  Still getting "connection timed out".  I'm going to upgrade support and ask AWS to help, or may just help me set up a new instance from scratch

**Comment by flambchap** [comment]
Can you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Additional steps to reproduce the issue would be great as well. Thank you.

**Comment by will-shatford** [comment]
OK, with the awesome help of AWS, here are their comments:
First, I had added my home IP address to the VPC.  They asked that I remove those, so that I on;y had the dafaults.  This didn't fix it, and instaed of a "connection timeout" I was getting ""The authentication type 10 is not supported...."

I then got this information from them:
"To begin with, I would like to inform you that, this type of error is usually thrown when there is a mismatch in the encryption algorithm used for password authentication. As you are upgrading to PG 14.5, thus, please note that PostgreSQL version 14 and newer versions use "scram-sha-256" by default, thus it is very likely that your client driver does not support it."

"Further to provide you support on a best effort basis, I further researched on it and diving deeper internally, I have determined that this error comes from the newer versions of PostgreSQL 14.x and above. This is because this PostgreSQL 14.x and above major version uses a newer JDBC driver which introduced the 'scram-sha-256' algorithm in which the older JDBC drivers are not able to handle."

"Therefore, this causes connections to fail due to a change made to the password authentication method used in the newer versions of PostgreSQL (scram-sha-256) whereby the client driver you are using only supports connecting via md5 passwords."

From AWS, "Below are the steps which you can follow to use a custom parameter group and implement the change"
So, since I had already made a copy of the default parametr group to set the rds-ssl parameter to zero (as suggested in GIT)...
1. In your custom parameter group, modify the parameter "password_encryption" to "MD5".
2. Once the above is done, modify your instance to use the new parameter group. (It was already using the custom parametr group. I just rebotted the DB to make sure...)
3. Once the new parameter group is in-sync, Reset the master user password to update the encryption algorithm used to MD5.

And, I could then connect!

**Comment by E1izabeth** [comment]
Thank you for update 👍

**Comment by Patrick2402** [comment]
Hi, 
I had problem with my Rust app connection with RDS database (psql). For me i had to do 2 steps:
1. create new parameter group set rds.force_ssl = 0 => reboot db. 
2. install on my webserver 
`sudo apt-get install libpq-dev
`

**Comment by prerakhere** [comment]
@will-shatford - updating password_encryption to "MD5" (i also tried with "md5") didn't work for me. Instead, setting rds.force_ssl parameter to 0 worked.

**Comment by tahayk** [comment]
Another solution that worked for me, removing or renaming `~/.postgresql` file or folder. 

Context: for my case I have 2 laptops, one of them is able to connect without any issue, the other one was failing.

Explanation from ([re:Post](https://repost.aws/questions/QUchxICHAWRkS3aF3HAN8B6Q/trying-to-host-my-website-on-aws-using-ec2-and-rds)): 

> The authentication failed because the client environment had previously been configured for certificate-based Postgres authentication (mTLS) but the current server is not configured for certificate-based authentication. Look for a .postgresql subdirectory in your current user HOME directory and remove or rename any postgresql.crt subdirectory in there.

**Comment by theiskaa** [comment]
https://stackoverflow.com/a/77787495

**Comment by tahafarooqui** [comment]
```
Try This to disable the SSL, that worked for me.

    var dbClient =  new Client({
        host: process.env.host,
        user: process.env.user,
        password: process.env.password,
        database: process.env.database,
        ssl: {
            rejectUnauthorized: true
        }
        
        
    });
    
     dbClient.connect((err) => {
      if (err) {
        console.error('connection error', err.stack);
      } else {
        console.log('connected');
      }
    });    
    return dbClient;

```

**Comment by Stefanie-0304** [comment]
what worked for me is the following:
in pg_hba.conf file add the following line, where the IP points to your local network:

host    all             all             192.168.8.0/24          md5

your postgresql.conf file should contain under connection settings: listen_addresses = '*'
restart server after editing pg_hba.conf and postgresql.conf

also, make sure that the firewall on the server allows for connections on the postgres server port (default to 5432)

**Comment by MohitNegi007** [comment]
> OK, with the awesome help of AWS, here are their comments: First, I had added my home IP address to the VPC. They asked that I remove those, so that I on;y had the dafaults. This didn't fix it, and instaed of a "connection timeout" I was getting ""The authentication type 10 is not supported...."
> 
> I then got this information from them: "To begin with, I would like to inform you that, this type of error is usually thrown when there is a mismatch in the encryption algorithm used for password authentication. As you are upgrading to PG 14.5, thus, please note that PostgreSQL version 14 and newer versions use "scram-sha-256" by default, thus it is very likely that your client driver does not support it."
> 
> "Further to provide you support on a best effort basis, I further researched on it and diving deeper internally, I have determined that this error comes from the newer versions of PostgreSQL 14.x and above. This is because this PostgreSQL 14.x and above major version uses a newer JDBC driver which introduced the 'scram-sha-256' algorithm in which the older JDBC drivers are not able to handle."
> 
> "Therefore, this causes connections to fail due to a change made to the password authentication method used in the newer versions of PostgreSQL (scram-sha-256) whereby the client driver you are using only supports connecting via md5 passwords."
> 
> From AWS, "Below are the steps which you can follow to use a custom parameter group and implement the change" So, since I had already made a copy of the default parametr group to set the rds-ssl parameter to zero (as suggested in GIT)...
> 
>     1. In your custom parameter group, modify the parameter "password_encryption" to "MD5".
> 
>     2. Once the above is done, modify your instance to use the new parameter group. (It was already using the custom parametr group. I just rebotted the DB to make sure...)
> 
>     3. Once the new parameter group is in-sync, Reset the master user password to update the encryption algorithm used to MD5.
> 
> 
> And, I could then connect!

worked for me , thanks ,  as mentioned , first let the parameter group to be updated then change master password .

**Comment by minyoon** [comment]
> 1. In your custom parameter group, modify the parameter "password_encryption" to "MD5".
> 2. Once the above is done, modify your instance to use the new parameter group. (It was already using the custom parametr > group. I just rebotted the DB to make sure...)
> 3. Once the new parameter group is in-sync, Reset the master user password to update the encryption algorithm used to MD5.

For those reading this, please be aware that using MD5 for password encryption is strongly discouraged: https://en.wikipedia.org/wiki/MD5

**Comment by Nanaya-L** [comment]
> In your database instance's 'Parameter Group,' change the value of rds.force_ssl to 0, restart the instance, and try to establish the connection again
> 
> ![image](https://private-user-images.githubusercontent.com/42352290/277698791-8f6a167c-79ea-48ac-bf5a-ffa6bce4fece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNzE2MDMsIm5iZiI6MTcyNDI3MTMwMywicGF0aCI6Ii80MjM1MjI5MC8yNzc2OTg3OTEtOGY2YTE2N2MtNzllYS00OGFjLWJmNWEtZmZhNmJjZTRmZWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDIwMTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YWRmMjFhY2Y3MjU3NWU0YWE5MWFhNGU1NTZkYzQ2ODgzOWZlNThhNTUzZmQ0NzYxMDAwYzI2NjM5NTJmZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.19Rdp9scGtFXDPq-x_bVOVUTa_-3MSJl65Dox-FpB80)
> 
> Try: psql --host=xxxxxxxxxx.us-east-1.rds.amazonaws.com --port=5432 --username=postgres --dbname=mydbname

Thank you so much, I've been with a "... no encryption" problem while connection do default parameter group of postgres 16. I made a new parameter Group and disable force ssl and it worked.

**Comment by agifsofyan** [comment]
> In your database instance's 'Parameter Group,' change the value of rds.force_ssl to 0, restart the instance, and try to establish the connection again
> 
> ![image](https://private-user-images.githubusercontent.com/42352290/277698791-8f6a167c-79ea-48ac-bf5a-ffa6bce4fece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjk3NzUsIm5iZiI6MTcyNTM2OTQ3NSwicGF0aCI6Ii80MjM1MjI5MC8yNzc2OTg3OTEtOGY2YTE2N2MtNzllYS00OGFjLWJmNWEtZmZhNmJjZTRmZWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEzMTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZmZlZmVmMjJjYWU5NzcwZGY3MzdhZWJiOTY5NzczOTBhZjkwZWI0YWM5YWY2MDRkNTdhZDczMjI0OGJlMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qCj_Icg6yrDqqjF7z5tiveXloAkgXsOj49m7bWYWrMM)
> 
> Try: psql --host=xxxxxxxxxx.us-east-1.rds.amazonaws.com --port=5432 --username=postgres --dbname=mydbname

Thank you, my problem is solved with this solution

**Comment by cata-code** [comment]
What worked for me when upgrading from AWS RDS Postgresql 14.1 to 16.4:

1. Create a new parameter group with rds.force_ssl = 0
2. Attach that parameter group to my database
3. Reboot (very important)

**Comment by chris-troupe** [comment]
Most of the solutions here involve not requiring SSL. I had a requirement to have SSL. To fix it through the command line I simply had to add `sslmode=require` ref: https://stackoverflow.com/questions/14021998/using-psql-to-connect-to-postgresql-in-ssl-mode/14022480. Once I required SSL, my command worked.

**Comment by jamilAbbas** [comment]
@theiskaa thanks for saving my time. Your solution fixed this problem that i was facing for 2+ hours.

**Comment by harsh-mahobia** [comment]
@cata-code thanks. this worked for me.

**Comment by cozyClassic** [comment]
easiest way to solve it in nestjs, typeorm

```typescript
    TypeOrmModule.forRootAsync({
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => ({
        type: 'postgres',
        host: configService.get<string>('DB_HOST'),
        port: configService.get<number>('DB_PORT'),
        username: configService.get<string>('DB_USERNAME'),
        password: configService.get<string>('DB_PASSWORD'),
        database: configService.get<string>('DB_NAME'),
        ssl: {  
          rejectUnauthorized: false, // <--- add it
        },
```
