### ISSUE TITLE
Date and DateTime32 are off one day

### ISSUE THREAD

**Issue by aadant** [dbeaver/dbeaver#21619]
### Description

```
create database if not exists test;
CREATE TABLE test.test_date
(
    `dt_date32` Date32 NOT NULL,
    `dt_date` Date NOT NULL
)
ENGINE = MergeTree
ORDER BY dt_date32;

insert into test.test_date values('2023-10-17','2023-10-17');

SELECT
    dt_date,
    toString(dt_date),
    dt_date32,
    toString(dt_date32)
FROM test.test_date;


Expected : 

┌────dt_date─┬─toString(dt_date)─┬──dt_date32─┬─toString(dt_date32)─┐
│ 2023-10-17 │ 2023-10-17        │ 2023-10-17 │ 2023-10-17          │
└────────────┴───────────────────┴────────────┴─────────────────────┘

1 row in set. Elapsed: 0.001 sec.
```

Running the same query in DBeaver returns 

```
dt_date   |toString(dt_date)|dt_date32 |toString(dt_date32)|
----------+-----------------+----------+-------------------+
2023-10-16|2023-10-17       |2023-10-16|2023-10-17         |
```

### DBeaver Version

Community Edition 23.03.3

### Operating System

macOS Ventura 3.6

### Database and driver

1. ClickHouse 23.3.8 (also tested with 22.3)
2. ClickHouse JDBC drivers (default, 0.4.2 also 0.5.0)

### Steps to reproduce

Connect to a 23.3.8 instance 
```
create database if not exists test;
use test;
CREATE TABLE test.test_date
(
    `dt_date32` Date32 NOT NULL,
    `dt_date` Date NOT NULL
)
ENGINE = MergeTree
ORDER BY dt_date32;

insert into test.test_date values('2023-10-17','2023-10-17');

SELECT
    dt_date,
    toString(dt_date),
    dt_date32,
    toString(dt_date32)
FROM test.test_date;


Expected : 

┌────dt_date─┬─toString(dt_date)─┬──dt_date32─┬─toString(dt_date32)─┐
│ 2023-10-17 │ 2023-10-17        │ 2023-10-17 │ 2023-10-17          │
└────────────┴───────────────────┴────────────┴─────────────────────┘

1 row in set. Elapsed: 0.001 sec.
```

Running the same query in DBeaver returns 

```
dt_date   |toString(dt_date)|dt_date32 |toString(dt_date32)|
----------+-----------------+----------+-------------------+
2023-10-16|2023-10-17       |2023-10-16|2023-10-17         |
```

**Comment by E1izabeth** [comment]
Similar issue #16624

**Comment by aadant** [comment]
@E1izabeth indeed, disabling date formatting worked around the issue.
What is wrong in my context ? ClickHouse process timezone is America/Chicago and DBeaver runs in the same timezone.

**Comment by E1izabeth** [comment]
It's hard to say what's wrong and on which side, because I can't reproduce it.
Have you tried the latest DBeaver version (DBeaver 23.2.3)? Maybe we have already fixed this.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by aadant** [comment]
@E1izabeth maybe you should disable the data formatting by default ?

**Comment by llchan** [comment]
I am also seeing the same on DBeaver 23.3.0.202312031432.  This is a serious issue as it silently displays incorrect data, and imho this issue should not be closed until resolved.  Please let me know what additional information you need to debug.  I can reproduce it with a simple `SELECT makeDate(2023, 12, 29) AS Date` query which will show `2023-12-28` in the data grid until I toggle formatting off.

Providing this additional information just in case, but this is probably not a clickhouse/driver issue since the internal value is correct.
- ClickHouse 23.3.1.2823
- ClickHouse JDBC Driver 0.4.6 (revision: dd91e17)

**Comment by aadant** [comment]
@E1izabeth please reopen. This is a serious issue

**Comment by aadant** [comment]
You may be in a US TZ to reproduce (maybe CDT) and the server should also be in America/Chicago for example

**Comment by serjiokov** [comment]
Hello @llchan, the corner case that you bumped is the DateTime fetched from the server side and the DateTime proceeded by the client application on the driver level by the cause of location in different time zones.

the toString() - operator is conver server stored value to your time zone 

Such things are useful for storing DateTime in the server timezone and converting to client (application) tmeZone for global users.  

Please try to get the result of query:
```
SELECT
    dt_date AS dt_str,
    toDateTime(dt_str) AS dt,
     timeZoneOffset(dt) AS Offset_in_seconds
FROM test.test_date;
```
if you are in same time zone offset will be 0
![image](https://github.com/dbeaver/dbeaver/assets/32031248/bf516e8e-2138-4ca5-926b-4a2c09f582cd)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by llchan** [comment]
@E1izabeth please reopen, this is still an issue.  I'm not sure what additional information is needed?  We have one-liner repros above, and afaik have answered any questions about our client timezones etc.   cc @aadant 

@serjiokov Why are `Date`s being converted to (UTC) `DateTime`s?  They do not represent time points and should not interact with time zones or offsets at all.  At least I now understand why this symptom is occuring, but I strongly disagree with the conversion.

**Comment by aadant** [comment]
@llchan the workaround is to disable the Date formatting in the "Properties"

**Comment by aadant** [comment]
so @E1izabeth there is an issue with CH and Date formatting which is enabled by default.
It should be fixed because Date / DateTime32 are showing this bug by default.

**Comment by MashaKorax** [comment]
Thanks for your report!
