### ISSUE TITLE
NOT NULL statement is missing in DDL for newly created SQLite tables

### ISSUE THREAD

**Issue by RequestPrivacy** [dbeaver/dbeaver#21618]
### Description

I try to create a SQLite db with tables that have columns with  "NOT NULL" constrains. During column creation via the GUI I check-mark the NOT NULL choice and it gets reflected in the "Columns" section of the "Properties" window (also check-marked).

The DDL has no "NOT NULL" in it though, so once I persist the table my columns can be NULL.

### DBeaver Version

Community Edition, Version 23.2.2.202310081633 (Flatpak)

### Operating System

Linux Ubuntu 22.04.3 LTS (Kubuntu)

### Database and driver

SQLite 

### Steps to reproduce

1. Start DBeaver and open "New Database Connection"
2. Choose "SQLite"
3. Choose "Connect by: Host"
4. Go to "Create..." and create new db file "test.db"
5. Leave everything as is and hit "Finish"
6. In "test.db" go to Tables, right click "Create New Table"
7. In Properties tab choose "Columns" and on lower right part click "Create New Column" 
8. Leave everything as is BUT toggle value of "Not Null" [x]
9. Observe newly created column in the "Columns" tab and the "Not Null" is set
10. Go to "DDL" tab and see that no SQL "NOT NULL" is generated, as well as when clicking on "Save..."

![Screenshot_20231021_142843-1](https://github.com/dbeaver/dbeaver/assets/72392544/4df91f72-fe84-4f3e-af60-6616ea00d17b)

![Screenshot_20231021_142955](https://github.com/dbeaver/dbeaver/assets/72392544/36aa27a1-e235-462c-baa7-878192da411c)

### Additional context

I tried to use the created database for pre-populating an android room database, but the compiler complained my that my schemas differed (as room needs NOT NULL columns but my tables created with DBeaver kept having NOT NULL = false).

The same steps on a local postgres do generate correct (i.e. "NOT NULL") columns.

**Comment by E1izabeth** [comment]
Thank you for bug report.
