### ISSUE TITLE
Open Database Object To Include Views 

### ISSUE THREAD

**Issue by RobertHana1** [dbeaver/dbeaver#21631]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't find a View in Snowflake and Postgres (haven't tried other DBs).

**Describe the solution you'd like**
I would like the Open Database Object dialog to include Views and that 

**Describe alternatives you've considered**
I've looked at the Database Navigator Search/Filter field, which does not find them either, or offer a full path search.  So I have opted to navigate normally, and try to remember to bookmark the found object if I have the foresight to me needing to get to it faster again in the future.

**Additional context**
None.

**Comment by E1izabeth** [comment]
I can't reproduce your issue. This dialog already searches in `Views` if `Table` flag is on.

![image](https://github.com/dbeaver/dbeaver/assets/28875055/574959c3-4523-4fb4-9d95-3056415bc66c)

Could you provide a short video of how are you trying to do that or more detailed steps to reproduce?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
