### ISSUE TITLE
Request : Sessions view : Add "Seconds in wait" column like sql developer

### ISSUE THREAD

**Issue by yoletx** [dbeaver/dbeaver#2163]
Oracle 11 / 12, dbeaver 4.2.0
When database is slow, i open sqldevelopper session view to see witch connexion is active, and i order them by "Seconds is wait". So it's easy to find wich session is locking tables for a long time, and most of the time i kill them.

Can you add this important column ?

Thank you

**Comment by p91paul** [comment]
I'd like to see this feature implemented too. Thanks!

**Comment by serge-rider** [comment]
Wow, it took less than a year :)
