### ISSUE TITLE
https://dbeaver.io/download/ shows linux archives as "zip", but they're ".tar.gz"

### ISSUE THREAD

**Issue by noamraph** [dbeaver/dbeaver#21643]
### Description

A small site issue: the download page at https://dbeaver.io/download/ describes the linux downloads as being "zip", while they are actually ".tar.gz" (which is much better).

Cheers,
Noam

### DBeaver Version

N/A

**Comment by arhayka** [comment]
Thank you for your report! We've updated the description of the file extension on the website.
