### ISSUE TITLE
When I right-click, the software automatically exits

### ISSUE THREAD

**Issue by feiranZhang** [dbeaver/dbeaver#21641]
### Description

OS：aarch64 Linux
JDK：jdk-20.0.1
dbeaver file：dbeaver-ce-23.2.3-linux.gtk.aarch64-nojdk.tar.gz
log content：*/dbeaver/configuration/org.eclipse.osgi/144/0/.cp/libswt-pi3-gtk-4962r3.so: undefined symbol: gtk_menu_popup_at_pointer
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

### DBeaver Version

Community 23.2.3

**Comment by Destrolaric** [comment]
@feiranZhang Hi could you try solution mention in 
https://github.com/dbeaver/dbeaver/issues/19709#issuecomment-1610890954

**Comment by E1izabeth** [comment]
Please, provide the fatal java logs. You can find instructions here https://github.com/dbeaver/dbeaver/wiki/Log-files#java-fatal-logs.

**Comment by E1izabeth** [comment]
And all dbeaver logs (https://github.com/dbeaver/dbeaver/wiki/Log-files#log-files)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
