### ISSUE TITLE
Limit Hadoop Resource while querying From DBeaver

### ISSUE THREAD

**Issue by Krubug** [dbeaver/dbeaver#21649]
Hello
first time here so i hope i write this question in the right place.
we at the company work with DBeaver A lot and we are facing a problem while querying Hive
from DBeaver. the problem is that the Hadoop Farm consumes a lot of resources in order to complete
those queries.  the spike of resources really harm all other process that runs at the same time.

Is there a way to limit DBeaver or to point DBeaver Query to Work in a way that it wont consume
all the HDFS Farm Resources?

version 23.2.0

Thanks in advanced

**Comment by Krubug** [comment]
any one?

**Comment by iraidaa** [comment]
Hi,

Please **uncheck** the **Read table metadata (unique keys)** and **Read table references (foreign keys)** in Window in the menu -> Preferences -> Editors -> Data Editor tab. 

Here:

![Editors2](https://github.com/dbeaver/dbeaver/assets/49681450/dac97e2b-bb95-40ca-82ed-7117d9f1b348)


Does it improve it improve the situation?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
