### ISSUE TITLE
Sorting in grid resets columns widths...sometimes

### ISSUE THREAD

**Issue by JTMosaic** [dbeaver/dbeaver#21647]
### Description

When displaying table data in a grid layout and fitting the column widths to "fit values" and then sorting data in the grid, sometimes the column sizes get reset to their defaults. This should not happen

### DBeaver Version

23.2.3.202310221533

### Operating System

macOS 13.6

### Database and driver

MySQL

### Steps to reproduce

Run a query which returns a set of data. For example:

`select * from information_schema.tables;`

![image](https://github.com/dbeaver/dbeaver/assets/9417720/a93364ea-41d5-408c-8852-f577c68efd9c)

Resize the columns by choosing Column Widths: Fit Values from the menu
![image](https://github.com/dbeaver/dbeaver/assets/9417720/95b52ad5-54b7-4508-9acf-a53880ed5c6b)

![image](https://github.com/dbeaver/dbeaver/assets/9417720/ce422984-efa7-4007-bb49-0e192b5216cc)

Sort any column and the column widths are reset to their default. You may have to sort the column more than once or sort multiple columns but it will eventually reset all of the columns. If doesn't do it every time so it is possible this is a bug.

**Comment by Matvey16** [comment]
@JTMosaic I don't think it's a bug. When you click `fit values` Dbeaver performs an action to resize columns width based on the currently avaliable values (depending on the table it can be only first 200 out of millions). But after sorting query, avaliable values change to other first 200 rows, so you need to fit width again.

We can think about making this option togglable at least, to adjust width after every refresh, but I'm not sure about performance here. But we definately don't want to read all data to fit width based on every row (because of the very big tables)

**Comment by JTMosaic** [comment]
@Matvey16 I get what you're saying but why have the grid reset the widths to their default on fetch? Why not just leave them where they are, if they have been resized? If they turn out to be too small I can always resize them again but otherwise it seems like the UI is wasting time by resetting them to the original/calculated size anyway.

For example, if I run a filtered query which returns, say 8 rows out of a potential thousands and then fit the columns to the values _the values won't be different if I sort the data_ even if the fetch is redone. Yet, DBeaver will sometimes (and I've not figured out the rationale) remove the column fit on sort. And, as I initially stated: It isn't consistent.

 In the video I have such a data set which will not change on sort. Note that I click the column sort and _sometimes_ the fields shrink and sometimes they don't. That is why I raised this as a bug: It should at least be consistent

https://github.com/dbeaver/dbeaver/assets/9417720/f650ae8b-4b61-4678-bb36-6c13dcb83465

And, for what it is worth, if there was an option to fit the fields to the values in the result set when the query is returned that would save a lot of time and gnashing of teeth. I realize that is an enhancement and not a bug and has likely been requested elsewhere already.

**Comment by arhayka** [comment]
@JTMosaic Thank you for the idea!

We want to add a new setting in Preferences that should define the width for the 'Column width: fit values' option depending on the data type.

Also, I created two issues based on this one:
- https://github.com/dbeaver/dbeaver/issues/21948
- https://github.com/dbeaver/dbeaver/issues/21947

**Comment by JTMosaic** [comment]
This seems to have been fixed
