### ISSUE TITLE
Getting Exhausted available authentication methods

### ISSUE THREAD

**Issue by sladejnr** [dbeaver/dbeaver#21645]
### Description

It was working fine until some weeks ago it just stopped connecting. I updated to lates version it still wouldn't connect.

It just keeps saying Exhausted available authentication methods

Logfile:
[logfiledb.log](https://github.com/dbeaver/dbeaver/files/13114652/logfiledb.log)

### DBeaver Version

version 23.2.2

### Operating System

macOS Ventura v13.4.1

### Database and driver

Database : Mysql 8
driver mysql

**Comment by ShadelessFox** [comment]
Hello @sladejnr,

You can try downgrading to an older version of DBeaver to see if the issue still happens there. If so, please contact your system administrator because it seems that your SSH password/key was changed.

**Comment by sladejnr** [comment]
I got the new key. It works now. Thank you
Closing this now
