### ISSUE TITLE
Subquery autocompletion does not work with experimental feature

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#21654]
### Description

![dbeaver_9RpmBIC0Fx](https://github.com/dbeaver/dbeaver/assets/84867187/1df3a300-99e4-4439-8c3c-57adacf1048a)

### DBeaver Version

DBeaver 23.2.3

### Operating System

windows 10

### Database and driver

Oracle

**Comment by E1izabeth** [comment]
Probably we need to solve it together with #7768 and #5580
