### ISSUE TITLE
[SQLITE_ERROR] SQL error or missing database (table "Frames" has more than one primary key)

### ISSUE THREAD

**Issue by jojje888** [dbeaver/dbeaver#21653]
### Description

When adding a foreign key to a table the following code is generated that has both the `PRIMARY KEY` on the `ID` keyword and the a constraint for the same `ID`

```CREATE TEMPORARY TABLE temp AS
SELECT *
FROM Frames;

DROP TABLE Frames;

CREATE TABLE Frames (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Designation TEXT,
	Description TEXT,
	Corners INTEGER,
	FrameType_ID INTEGER,
	CONSTRAINT FRAMES_PK PRIMARY KEY (ID),
	CONSTRAINT Frames_FK FOREIGN KEY (FrameType_ID) REFERENCES FrameTypes(ID)
);

INSERT INTO Frames
SELECT *
FROM temp;

DROP TABLE temp;
```

**Error log**

```!ENTRY org.jkiss.dbeaver.model 4 0 2023-10-25 16:00:43.796
!MESSAGE [SQLITE_ERROR] SQL error or missing database (table "Frames" has more than one primary key)
!STACK 0
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table "Frames" has more than one primary key)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.throwex(DB.java:1150)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:132)
	at org.sqlite.core.DB.prepare(DB.java:264)
	at org.sqlite.jdbc3.JDBC3Statement.lambda$execute$0(JDBC3Statement.java:53)
	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:459)
	at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:42)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.executePersistAction(DBExecUtils.java:358)
	at org.jkiss.dbeaver.model.impl.edit.AbstractObjectManager.executePersistAction(AbstractObjectManager.java:40)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.executeCommands(AbstractCommandContext.java:206)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:122)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.lambda$1(EntityEditor.java:384)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.saveCommandContext(EntityEditor.java:382)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$SaveJob.run(EntityEditor.java:1253)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
``` 

### DBeaver Version

Community Edition 23.2.3

### Operating System

Windows 10

### Database and driver

Database: 
SQLite

Driver: 
sqlite-jdbc-3.43.3.1
slf4j-api-1.7.36

### Steps to reproduce

1. Create a reference table (FrameTypes)
`CREATE TABLE FrameTypes (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Designation TEXT(50),
	Description TEXT(250),
	Ordinal INTEGER,
	IsValid INTEGER DEFAULT (1)
);`
2. Add an ID (int) as the primary key
3. Create another table (Frames)
4. Add an ID (int) as the primary key
5. Add another column to be used as the foreign key of type int
`CREATE TABLE Frames (
	ID INTEGER PRIMARY KEY AUTOINCREMENT
, Designation TEXT(100), Description TEXT(250), Corners INTEGER, FrameType_ID INTEGER);`
7. Save the changes
8. Create a foreign key using the two ID's
9. Save the changes again
10. The error occurs.

**Comment by LonwoLonwo** [comment]
Hello @jojje888 

I see - the generated query contains an extra PRIMARY KEY definition.

![2023-10-25 11_52_22-Frames - Persist Changes](https://github.com/dbeaver/dbeaver/assets/45152336/38a458f9-08fe-4a49-b21a-411ac653c5e0)

Thanks for the bug report.

**Comment by jojje888** [comment]
Hi @LonwoLonwo 
No problem.

**Comment by andreysneg** [comment]
The bug is still there. Imposible create Autoincrement Primary Key  for sqlite.  Only with sql code. 

For example simple sql code, which cannot be repeated through the interface

```
 CREATE TABLE COMPANY(
   id  INTEGER PRIMARY KEY AUTOINCREMENT,
   name TEXT      NOT NULL,
   age     INT       NOT NULL
);
```

**Comment by HannaMalygina** [comment]
Did you try :
id INT AUTO_INCREMENT PRIMARY KEY

**Comment by nanguanlin6** [comment]
It still exists when creating foreign keys when using SQLite with dbeaver 23.2.0. Exactly the same error with op.

**Comment by gitleo1987** [comment]
Still exists on version 24.0.5. I have to copy the generated SQL and remove the line with the primary key constraint.

**Comment by saamdotexe** [comment]
Still present in 24.1.1, is a fix on the roadmap?

**Comment by firelzrd** [comment]
Still present in 24.1.2.202407071610.

**Comment by inert-aesthetic** [comment]
Still present.

**Comment by kellandJuniper** [comment]
bug still present in  24.2.2.202410061621. How to fix it?

**Comment by REDevArtK** [comment]
it still there, pls fix

**Comment by firelzrd** [comment]
2 more days 'til the 1st anniversary since it was first reported.
This bug is so annoying that it makes DBeaver almost useless for constructing SQLite databases,
Devs, please show us that you at least recognize it and that you care.

**Comment by jsgreenwell** [comment]
And we are at the first year anniversary - just got the error with Version 24.2.3.202410200515 so its still not fixed. To fix it is simple at least:

Remove the constraint statement and just leave the PRIMARY KEY declaration in the auto-increment field (column) declaration in the CREATE TABLE statement and you'll now only have a single KEY declared and it will run. Or just don't select the second option when using an autoincrementing primary key:

![image](https://github.com/user-attachments/assets/acfbe9d1-4504-4dcc-85c3-f4cb120347d8)

**Comment by firelzrd** [comment]
@eusebe-cda Thank you very much!

**Comment by logkirk** [comment]
Is it possible there was a regression? I'm seeing this issue on Version 25.1.0.202506011722.

![Image](https://github.com/user-attachments/assets/a5757dbe-9faa-4dbf-a00d-a534f0b46560)

**Comment by eusebe-cda** [comment]
I don't think it's the same problem: I just tested adding a foreign key to a table with a primary key, and it worked.
In SQLite, an auto-increment column is necessarily a primary key. When creating a table with an auto-incrementing column, you don't need to specifically specify that the column is a primary key...

![Image](https://github.com/user-attachments/assets/ec0d3b62-7d84-4aec-a507-6661e32e0128)

![Image](https://github.com/user-attachments/assets/19ff965c-0672-4641-a24d-eb813519d5ef)
