### ISSUE TITLE
dbeaver is unable to recover from an error in sql query - new sql query is required

### ISSUE THREAD

**Issue by wirowka** [dbeaver/dbeaver#21665]
### Description

hi
If I send an malformed/incorrect SQL query **twice** - DBeaver will **not** recover from this error - the only solution is to open **new** SQL query window and execute the corrected query there.
It is very annoying.

It will stuck like in the below screenshot
![image](https://github.com/dbeaver/dbeaver/assets/21661371/261314b8-a85f-4186-9fad-54b0c89aad7b)

### DBeaver Version

community edition Version 23.2.3.202310221533

### Operating System

macOS Ventura 13.6

### Database and driver

1. DB: postgres (PostgreSQL) 14.1. (running on RHEL 8.6)
2. org.postgresql.Driver - 42.5.2
3. 

### Steps to reproduce

1. New SQL window with a SQL query which is incorrect
2. Click Execute SQL query
3. Edit (or not) the query so that it still does not work
4. Click Execute SQL query
5. Correct the query so that it is correct
6. Click Execute SQL query - DBeaver will be still locked with the same error like in the screenshot I pasted above

**Comment by Matvey16** [comment]
@wirowka I was not able to reproduce this. Can you please check if the last (correct) query is shown in query manager and if it has a success or error status, when there is an error in result set view.

Also please show me what preferences do you have in these two sections

![dbeaver_PmxLe4atuu](https://github.com/dbeaver/dbeaver/assets/82543000/f31b1a5d-d5c5-47ae-95d7-c379d55958c2)

![dbeaver_Tm7BmsYiGa](https://github.com/dbeaver/dbeaver/assets/82543000/7d47bd6d-24ae-486a-9097-65c48f56a91e)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
