### ISSUE TITLE
Singletab mode improvements

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#21666]
We want to
- [x] Add setting for removing filters in single tab mode
- [x] Extend functionality not only for Script execution
- [x] Remove warning about parallel execution
- [x] Reuse existing tab on new execution
- [x] Rename command to Show results in a single/multiple tab(s)
- [x] Think about scrolling

Auto calculate the size of the grid by the rows number will be done in a separate issue (#21697)

**Comment by SandroG** [comment]
Hi,
the "Singletab mode" in DBeaver is a great feature, but I'm struggling to find the option mentioned here "Add setting for removing filters in single tab mode". 
Where's this setting?

**Comment by E1izabeth** [comment]
Hi, @SandroG 
It's `Preferences->Editors->Data Editor->Appearance->Show filters panel in single tab mode`
![image](https://github.com/user-attachments/assets/23fe5758-00e6-417c-889e-b5c71d55bac4)
