### ISSUE TITLE
Previously open items are not available after closing and reopening application

### ISSUE THREAD

**Issue by creage** [dbeaver/dbeaver#2166]
Before 4.2.1, when I have some table preview in the Navigator, after closing and reopening application, that table preview was loading and refreshing. Now I only see an empty tab, hitting F5 does not populate it.

**Comment by serge-rider** [comment]
There were no changes related to this in 4.2.1. Maybe it is a bug.
Could you check error log (main menu Window->Show View) for any related errors? 

BTW this behavior is configurable:
![image](https://user-images.githubusercontent.com/6398845/30535801-270d68e4-9c6c-11e7-8eab-0286c29c7df1.png)

**Comment by creage** [comment]
It is definitely a bug. Here is a GIF of issue. I open a table, then close app, reopen it. It tries to reconnect and refresh the table, but displays nothing in the end.

![cantreconnect](https://user-images.githubusercontent.com/910967/30785411-cbb8033c-a166-11e7-950f-d5b801574356.gif)

**Comment by serge-rider** [comment]
Agreed.
Please post error/debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by creage** [comment]
Sorry for keeping it that long, I cannot reproduce it on latest (5.3.2) anymore.
