### ISSUE TITLE
Integrating Python visualization libraries such as seaborn

### ISSUE THREAD

**Issue by jiaqianjing** [dbeaver/dbeaver#21664]
As data analysts, we often find ourselves needing to visualize aggregated data using Python, utilizing libraries such as Matplotlib or Seaborn to create simple line plots, pie charts, and so on. However, the current process involves querying the relevant data using DBeaver, exporting it as a CSV or JSON file, importing this file using Python pandas, and then performing visualization operations. This process is cumbersome and time-consuming.

**Comment by ShadelessFox** [comment]
Hello, thanks for the feature request.

DBeaver provides various virtualization tools, such as plots and charts in PRO versions. You can read more about this feature on our wiki: https://dbeaver.com/docs/dbeaver/Managing-Charts/.

You can also automate your workflow using tasks: https://dbeaver.com/docs/dbeaver/Task-Management/

We do not want to integrate Python/Jupyter Notebook in DBeaver.
