### ISSUE TITLE
Backup of several schemes with selective set of tables is wrong

### ISSUE THREAD

**Issue by mrmedvezhonok** [dbeaver/dbeaver#21669]
### Description

I try to backup 6 schemes from one database, but at one of them I need only several tables, not all. So after Selection of needed schemas and tables I start backup and see that DBeaver save every table, whatever I selected.

### DBeaver Version

Community edition 23.2.3

### Operating System

Windows 10 Pro x64

### Database and driver

1. Database PostgreSQL 14.4 (Ubuntu 14.4-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
2. Driver (PostgreSQL JDBC Driver) org.postgresql:postgresql:RELEASE 42.5.2

### Steps to reproduce

1. Connecto to PostgreSQL server
2. Open right click mouse menu -> Instruments -> Backup (may be not exactly because I translated from Russian)
3. Select schemas
4. Select Needed tables from last scheme (about 3 from ~40 tables)
5. Continue -> select file path and name
6. Start

**Comment by LonwoLonwo** [comment]
Hello @IBunDem 

Thanks for the bug report. 
Looks bad. And if we want to choose some tables in some schemas also will be issue.
