### ISSUE TITLE
One to one relationship shown as one to many in ERD after adding primary key in both tables

### ISSUE THREAD

**Issue by pytest3** [dbeaver/dbeaver#21677]
### Description

This problem is similar to issue https://github.com/dbeaver/dbeaver/issues/21398, but i've added a primary key in both tables.

### DBeaver Version

23.2.3

### Operating System

mac os

### Database and driver

PostgreSQL 16.0

### Steps to reproduce

1. Create Database

```
CREATE TABLE person_phone (
id SERIAL PRIMARY key, 
phone text
);

CREATE TABLE person_email (
id SERIAL PRIMARY key,
person_phone_id INTEGER NOT NULL UNIQUE, 
email TEXT, 
FOREIGN KEY(person_phone_id) REFERENCES person_phone(id)
);

INSERT INTO person_phone (phone) VALUES ('aaa'), ('bbb'), ('ccc');
INSERT INTO person_email (person_phone_id,email) VALUES (1, 'test@test.com'), (2,'hello@hello.com');

```
2. Connect to DB

3. View ERD Diagram

4. Observe that the one-to-one relationship is displayed as one-to-many

![image](https://github.com/dbeaver/dbeaver/assets/98165959/750a9091-23b0-40f8-99f1-fa83ad53bb64)

5. Recreate DB by removing primary key from person_email table

```
CREATE TABLE person_phone (
id SERIAL PRIMARY key, 
phone text
);

CREATE TABLE person_email (
person_phone_id INTEGER NOT NULL UNIQUE, 
email TEXT, 
FOREIGN KEY(person_phone_id) REFERENCES person_phone(id)
);

INSERT INTO person_phone (phone) VALUES ('aaa'), ('bbb'), ('ccc');
INSERT INTO person_email (person_phone_id,email) VALUES (1, 'test@test.com'), (2,'hello@hello.com');

```
7. Refresh and reconnect to DB

9. View ERD diagram

10. Observer that the one-to-one relationship is displayed correctly

![image](https://github.com/dbeaver/dbeaver/assets/98165959/5da80358-8e90-493d-9544-0f0adc6dfc62)

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by MichalPetricek** [comment]
I also have the same problem.

**Comment by cekinmezyucel** [comment]
This problem also occurs in MySQL databases.

**Comment by pytest3** [comment]
Thank you for your hard work on this
