### ISSUE TITLE
postgres: gist exclusion constraint: DDL fail

### ISSUE THREAD

**Issue by fjf2002** [dbeaver/dbeaver#21674]
### Description

I'm using Postgres Exclusion Constraints, see https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-EXCLUSION.

The DBeaver Table DDL tells me something like
```sql
CREATE INDEX i ON t USING gist (a);
```

... but the reality is (and pg_dump tells me):
```sql
ALTER TABLE ONLY t
    ADD CONSTRAINT i EXCLUDE USING gist (a WITH &&);
```

The gist exclusion constraint operators are missing.

### DBeaver Version

CE 23.1.5

### Operating System

Windows 10

### Database and driver

PostgreSQL 15.4
Driver 42.5.2

### Steps to reproduce

```sql
CREATE TABLE t (
	a daterange NOT NULL
);

ALTER TABLE ONLY t
    ADD CONSTRAINT i EXCLUDE USING gist (a WITH &&);
```

**Comment by LonwoLonwo** [comment]
Hello @fjf2002 

Thanks for the report.

**Comment by fjf2002** [comment]
Sorry, my fault. Does indeed work. Closing ticket.
