### ISSUE TITLE
datasource navigator donot select null when mouse click on an empty space

### ISSUE THREAD

**Issue by itsyfx** [dbeaver/dbeaver#21676]
### Description

In the data source navigation bar on the left, when I selected a data source or folder and then clicked on a blank space, the system did not set the previously selected item to empty, which caused me to create a new data source or folder. under the selected folder.

otherwise,it works fine on  my workmate's mac os.

### DBeaver Version

23.2.3

### Operating System

windows 11

### Database and driver

any datasource in folder

### Steps to reproduce

1.create a folder.
2.select the folder.
3.click an empty space
4.create a new datasource (any type)
5.the datasouce doesnot show in root node, but show in the step2 folder instead
![image](https://github.com/dbeaver/dbeaver/assets/55142367/2e9e1dba-c50a-4bca-b542-32f3a91283a7)

### Additional context

i found this problem during developing with dbeaver,and i have solved it 
![image](https://github.com/dbeaver/dbeaver/assets/55142367/33687a3d-f91d-447f-9d58-32271feabe44)

how can i contribute it to community

**Comment by E1izabeth** [comment]
Hi, @itsyfx! We wrote an article about that https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code
Hope it helps.
