### ISSUE TITLE
Client After at least 60 min running procedure

### ISSUE THREAD

**Issue by FarshidShekari** [dbeaver/dbeaver#21672]
### Description

I executed an SQL query for just inserting data and it took too long to insert, maybe 7 hours, it I suspect the why my query didn't finish, and then just after some checking in running queries, I saw anything is running and checked the inserting table and I saw all records inserted but DBeaver still showing me query executing :))))
this also happened in procedure calling.

### DBeaver Version

 23.2.3.202310221533

### Operating System

Windows 11

### Database and driver

Oracle

**Comment by E1izabeth** [comment]
Please provide database and driver versions. You can check them by pressing Test Connection button in the Connection Wizard

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by FarshidShekari** [comment]
I always use the latest version of DBeaver and my database is Oracle 19c, this problem didn't occur in Oracle SQL Developer

**Comment by E1izabeth** [comment]
Thank you for update

**Comment by serjiokov** [comment]
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. 
They are located in the %APPDATA%\DBeaverData\workspace6\.metadata directory.
In case your OS isn't Windows, here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
