### ISSUE TITLE
MS Access (accdb) UCAExc:::5.0.0 Unsupported newer version: 6

### ISSUE THREAD

**Issue by m2i7c9k** [dbeaver/dbeaver#21687]
### Description

I tried connect to ms acces 365 file (accdb) and I got theis error message: UCAExc:::5.0.0 Unsupported newer version: 6

### DBeaver Version

23.2.3

### Operating System

Win 10 22H2

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
Have you tried changing driver version?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
