### ISSUE TITLE
Renaming FK Constraint: GUI not updated

### ISSUE THREAD

**Issue by fjf2002** [dbeaver/dbeaver#21681]
### Description

FK Constraint renaming:
In the state between renaming and persisting, the constraint is still shown as before. Just after persisting, the constraint gets renamed.

### DBeaver Version

CE 23.1.5

### Operating System

Windows 10

### Database and driver

PostgreSQL 15.4
Driver 42.5.2

### Steps to reproduce

* Open Table definition
* Rename an FK Constraint

Now, the renaming is not shown. However, when I click save, the renaming gets persisted.

**Comment by E1izabeth** [comment]
Please provide the detailed steps to about how you rename FK. Do you press Save button after renaming?
The video showing the issue would be beneficial as I haven't managed to reproduce the described behavior.

**Comment by E1izabeth** [comment]
Oh it seems I understood what do you mean. Are you renaming foreign key from navigator by pressing Rename from the context menu?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/e24d7a82-e67b-4f52-b60a-987452ccb3c3)

**Comment by E1izabeth** [comment]
If yes, you need to press F5 with selection on the any parent node in Navigator to reload metadata.

**Comment by fjf2002** [comment]
@E1izabeth: I press F2 or choose "rename" from the context menu, and rename the constraint.

Then, its name should be updated. Which it does not. This is the bug.

When I press Save, the renaming gets applied correctly.

When I press F5, the prepared renaming gets undone, which is no solution.

**Comment by E1izabeth** [comment]
Thank you for explanation.

**Comment by flambchap** [comment]
I reproduced it. Thank you for the report.
