### ISSUE TITLE
DBeaver cannot handle quote character in passwords

### ISSUE THREAD

**Issue by tszazados** [dbeaver/dbeaver#21694]
### Description

I suppose for all kind of databases but for MySql for sure, DBeaver cannot handle quote character in passwords. 
When creating a connection and the mysql password contains quote character ( I mean: " ) the Test connection check fails - and at the same time I can use the same password in console for example. Removing the " from the password solved the problem.

The result is access denined.

Thanks

### DBeaver Version

Communitiy edition 23.2.1.202309250303

### Operating System

Windows 10 latest

### Database and driver

Database name and version: MySql 8.0, Driver for MySQL 8 and later

### Steps to reproduce

1. Create new connection
2. Set credentials including password
3. Press Test connection button.

**Comment by uslss** [comment]
unfortunately, cannot reproduce your issue.
Could you provide user creation ddl?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
