### ISSUE TITLE
Improve vertically display by adjusting windows size for results with few lines

### ISSUE THREAD

**Issue by benjdv** [dbeaver/dbeaver#21697]
Hi,

Dbeaver introduce recently the vertically display  which allows you to display the results of several queries one above the other (https://github.com/dbeaver/dbeaver/issues/6861)

As discussed in https://github.com/dbeaver/dbeaver/pull/21280, would it be possible to improve this fonctionnality with an  "intelligent" auto-sizing of the results. Something like "size of each result" = min(returned rows, 10)
This would allow us to better understand the different query results without having to scroll when they only return a few lines.
"10" should be an option whose value would be left to the user's choice

Regards,
Thanks,

**Comment by E1izabeth** [comment]
Thank you for idea!
