### ISSUE TITLE
When connecting to Dameng database, you cannot use the F2 shortcut key to rename the schema, table, and table fields of Dameng database.

### ISSUE THREAD

**Issue by tianlongJ** [dbeaver/dbeaver#21690]
### Description

When connecting to Dameng database, you cannot use the F2 shortcut key to rename the schema, table, and table fields of Dameng database.

### DBeaver Version

22.2.0

### Operating System

win11

**Comment by LonwoLonwo** [comment]
Hello @tianlongJ 

It doesn't work for schema, because it is not implemented yet.

But for me it works well for tables and columns.

Do you use f2 in the navigator tree? And what exactly table fields do you want to change?

**Comment by Stkai** [comment]
Hello @tianlongJ 

Dameng database does not support renaming schema names. 
For table names and column names, you can try the latest version. 
Since  23.2.2 dbeaver supports Dameng database.

**Comment by zghlx** [comment]
I usually use Dameng, so I try it when I have time.

**Comment by zghlx** [comment]
My 23.2.3 version works fine
![image](https://github.com/dbeaver/dbeaver/assets/5928564/25bd3f6c-dc7a-4257-9ca4-f9c5793b8004)
![image](https://github.com/dbeaver/dbeaver/assets/5928564/77bbb202-7d48-44fe-b56c-e314acc8a2d4)
![image](https://github.com/dbeaver/dbeaver/assets/5928564/baa13c27-4902-42d1-bf80-0f3d4deaf167)
![image](https://github.com/dbeaver/dbeaver/assets/5928564/094bc3d7-3e5c-43b9-8e3b-01bd72b35f8e)

**Comment by tianlongJ** [comment]
> My 23.2.3 version works fine ![image](https://user-images.githubusercontent.com/5928564/279297430-25bd3f6c-dc7a-4257-9ca4-f9c5793b8004.png) ![image](https://user-images.githubusercontent.com/5928564/279297512-77bbb202-7d48-44fe-b56c-e314acc8a2d4.png) ![image](https://user-images.githubusercontent.com/5928564/279297580-baa13c27-4902-42d1-bf80-0f3d4deaf167.png) ![image](https://user-images.githubusercontent.com/5928564/279297614-094bc3d7-3e5c-43b9-8e3b-01bd72b35f8e.png)

Is it Dameng database? I am using dbeaver lite 23.2.0. There is no rename option when right-clicking on the tables and columns of Dameng database. F2 is also unavailable.
Dameng database official website：https://www.dameng.com/

**Comment by zghlx** [comment]
是的，就是达梦。你换个最新版本试试
![image](https://github.com/dbeaver/dbeaver/assets/5928564/0b6b4f0c-da8b-4c79-8493-62efaec77d17)

**Comment by tianlongJ** [comment]
> 是的，就是达梦。你换个最新版本试试 ![image](https://user-images.githubusercontent.com/5928564/279299407-0b6b4f0c-da8b-4c79-8493-62efaec77d17.png)

。中文交流就方便了。是最新的，Dbeaver lite最新版就是23.2.0，不是dbeaver Community
![image](https://github.com/dbeaver/dbeaver/assets/50390874/d13f1e9b-e080-46c9-8bab-88d46263df4f)

**Comment by zghlx** [comment]
> Hello @tianlongJ
> 
> It doesn't work for schema, because it is not implemented yet.
> 
> But for me it works well for tables and columns.
> 
> Do you use f2 in the navigator tree? And what exactly table fields do you want to change?

Dbeaver lite 23.2.0

**Comment by zghlx** [comment]
> Hello @tianlongJ
> 
> Dameng database does not support renaming schema names. For table names and column names, you can try the latest version. Since 23.2.2 dbeaver supports Dameng database.

Dbeaver lite 23.2.0

**Comment by zghlx** [comment]
> > 是的，就是达梦。你换个最新版本试试 ![image](https://user-images.githubusercontent.com/5928564/279299407-0b6b4f0c-da8b-4c79-8493-62efaec77d17.png)
> 
> 。中文交流就方便了。是最新的，Dbeaver lite最新版就是23.2.0，不是dbeaver Community ![image](https://user-images.githubusercontent.com/50390874/279300145-d13f1e9b-e080-46c9-8bab-88d46263df4f.png)

哦，那说不定真是一个bug。 哪里来了个 lite 版本了？我怎么从来没注意到有这个版本

**Comment by tianlongJ** [comment]
> > > 是的，就是达梦。你换个最新版本试试 ![image](https://user-images.githubusercontent.com/5928564/279299407-0b6b4f0c-da8b-4c79-8493-62efaec77d17.png)
> > 
> > 
> > 。中文交流就方便了。是最新的，Dbeaver lite最新版就是23.2.0，不是dbeaver Community ![image](https://user-images.githubusercontent.com/50390874/279300145-d13f1e9b-e080-46c9-8bab-88d46263df4f.png)
> 
> 哦，那说不定真是一个bug。 哪里来了个 lite 版本了？我怎么从来没注意到有这个版本

pro是分三个版本的，lite是最便宜的一个。
![image](https://github.com/dbeaver/dbeaver/assets/50390874/4487dbaf-6843-48c7-9c01-c619b058117f)
https://dbeaver.com/edition/

**Comment by zghlx** [comment]
> > > > 是的，就是达梦。你换个最新版本试试 ![image](https://user-images.githubusercontent.com/5928564/279299407-0b6b4f0c-da8b-4c79-8493-62efaec77d17.png)
> > > 
> > > 
> > > 。中文交流就方便了。是最新的，Dbeaver lite最新版就是23.2.0，不是dbeaver Community ![image](https://user-images.githubusercontent.com/50390874/279300145-d13f1e9b-e080-46c9-8bab-88d46263df4f.png)
> > 
> > 
> > 哦，那说不定真是一个bug。 哪里来了个 lite 版本了？我怎么从来没注意到有这个版本
> 
> pro是分三个版本的，lite是最便宜的一个。 ![image](https://user-images.githubusercontent.com/50390874/279301458-4487dbaf-6843-48c7-9c01-c619b058117f.png) https://dbeaver.com/edition/

哦哦

**Comment by tianlongJ** [comment]
@zghlx 社区版的23.2.3是可以的是吗，不过我还需要nosql支持，等pro的下一个版本看看吧

**Comment by zghlx** [comment]
> @zghlx 社区版的23.2.3是可以的是吗，不过我还需要nosql支持，等pro的下一个版本看看吧

我用的社区版的23.2.3没问题的。

**Comment by LonwoLonwo** [comment]
Hello @tianlongJ 

DBeaver Lite Edition 23.2.0 doesn't have Dameng support. 
But you can test our Early Access version: https://dbeaver.com/files/ea/lite/
Which already has Dameng database support.

**Comment by tianlongJ** [comment]
> Hello @tianlongJ
> 
> DBeaver Lite Edition 23.2.0 doesn't have Dameng support. But you can test our Early Access version: https://dbeaver.com/files/ea/lite/ Which already has Dameng database support.

Thanks, I'll switch to the Early Access version to try it.

**Comment by tianlongJ** [comment]
> Hello @tianlongJ
> 
> DBeaver Lite Edition 23.2.0 doesn't have Dameng support. But you can test our Early Access version: https://dbeaver.com/files/ea/lite/ Which already has Dameng database support.

It works, thank you very much.

**Comment by zghlx** [comment]
> Hello @tianlongJ
> 
> DBeaver Lite Edition 23.2.0 doesn't have Dameng support. But you can test our Early Access version: https://dbeaver.com/files/ea/lite/ Which already has Dameng database support.

@tianlongJ @LonwoLonwo May be he custom the dameng driver using dameng jar like this before 23.2.0
![image](https://github.com/dbeaver/dbeaver/assets/5928564/d7138302-792a-45f5-bb82-0f8ea968b4d0)

**Comment by tianlongJ** [comment]
> > @zghlx 社区版的23.2.3是可以的是吗，不过我还需要nosql支持，等pro的下一个版本看看吧
> 
> 我用的社区版的23.2.3没问题的。

问题解决了。23.2.3在pro版本属于预览版，但是可以下载。我没注意那个东西，默认最显眼的下载是23.2，换成23.2.3可以了，感谢帮忙解答问题😊
![image](https://github.com/dbeaver/dbeaver/assets/50390874/ba149cc5-1d6a-4dec-8021-4ae0ec675e4e)

**Comment by tianlongJ** [comment]
> Hello @tianlongJ
> 
> DBeaver Lite Edition 23.2.0 doesn't have Dameng support. But you can test our Early Access version: https://dbeaver.com/files/ea/lite/ Which already has Dameng database support.

I don’t know why I restarted dbeaver and it couldn’t use f2 again. I need f2 to quickly copy table names and column names.

**Comment by LonwoLonwo** [comment]
Try to restart again, Maybe? And check the version number. It needs to be 23.2.something

**Comment by tianlongJ** [comment]
> Try to restart again, Maybe? And check the version number. It needs to be 23.2.something

I figured it out, I need to set the navigation view to advanced, I don't know why it changed to simple on its own, now it works fine
