### ISSUE TITLE
Make definition statement available without wrapper

### ISSUE THREAD

**Issue by dr-1** [dbeaver/dbeaver#21702]
This is part of a broader feature request, #18060. By breaking it up I hope to make it more manageable.

I would like the definition statement of a view to be available without the wrapping text that DBeaver adds. That would avoid having to remove the wrapping text myself in a common workflow: altering a view by fetching the current `SELECT VIEW` statement, changing it to an `ALTER` statement and executing it.

In other words, instead of getting
```
-- some_view source

CREATE VIEW some_view AS
SELECT some_column
FROM some_table;
```
from the Definition page of the view object properties, I would like to get just
```
CREATE VIEW some_view AS
SELECT some_column
FROM some_table
```
meaning the definition text should be as it is stored in the database information schema, without the comment line and the blank line at the top, and ending the definition with a newline instead of a semicolon.

Perhaps this could be a configurable option.

**Comment by LonwoLonwo** [comment]
Hello @dr-1 

Your case is described here. https://github.com/dbeaver/dbeaver/issues/16188

You can remove the comment section in some databases, like PostgreSQL. What database do you use?

**Comment by dr-1** [comment]
@LonwoLonwo, thanks for the reference.

I currently work mainly with this database and driver:

Server:
Microsoft SQL Server 12.00.5316
Microsoft SQL Azure (RTM) - 12.0.2000.8 

Driver:
Microsoft JDBC Driver 11.2 for SQL Server 11.2.3.0

**Comment by LonwoLonwo** [comment]
> instead of a semicolon

And what is the issue with a semicolon? Because this is a SQL standard.

**Comment by dr-1** [comment]
Like the `-- ... source` comment at the top, the addition of the semicolon can also lead to a slight difference between the definition statement that we see and the one that the database has stored (in the case of SQL Server in INFORMATION_SCHEMA.VIEWS.VIEW_DEFINITION). For us this presents a problem because we have the version from INFORMATION_SCHEMA under version control. Altering a view with DBeaver without manually removing the semicolon then becomes an unintended change that shows in Git logs and diffs, making it more difficult for example to get a list of view definitions that changed in a meaningful way (other than having a semicolon added).

**Comment by LonwoLonwo** [comment]
Ok. The ''--source" part will be removed here: https://github.com/dbeaver/dbeaver/issues/16188

And we can't remove the semicolon because, without it, SQL execution will not work.

So, I'm closing this ticket as a duplicate.
