### ISSUE TITLE
full table list

### ISSUE THREAD

**Issue by bmoAtolcd** [dbeaver/dbeaver#21711]
### Description

Only few tables are displayed on treeview. Refresh not do not change anything (on Tables or on Db).  
The shema have 198 tables, only 5 was listed.

![image](https://github.com/dbeaver/dbeaver/assets/57495449/1ef7cc00-05f0-44a5-b721-fbb2906ae68c)

### DBeaver Version

Community Edition 22.3.5.202302180832

### Operating System

max Os Ventura 13.4

### Database and driver

Database Postgres 13.11

**Comment by LonwoLonwo** [comment]
Hello @bmoAtolcd 

I see in your picture that you have filters on your tables list.

![2023-10-31 13_00_46-279342373-1ef7cc00-05f0-44a5-b721-fbb2906ae68c png (Изображение PNG, 533 × 285 п](https://github.com/dbeaver/dbeaver/assets/45152336/ca4f3c07-cc4b-4c7c-a4c5-222907777ef2)

You can clear or change your filter like this:

![2023-10-31 13_02_54-DBeaver Ultimate 23 2 3 - _postgres 6 1_ Script-122](https://github.com/dbeaver/dbeaver/assets/45152336/5bc71df4-28da-4255-ac55-6d4573e553dd)

**Comment by bmoAtolcd** [comment]
Thank you very much, I didn't know about this feature. No idea how a filter got there!
Everything is ok now.

**Comment by bmoAtolcd** [comment]
This is not a bug

**Comment by LonwoLonwo** [comment]
Thanks for the update @bmoAtolcd

**Comment by serge-rider** [comment]
I think we need to make it more obvious.

E.g. add "fake" element `items were hidden` as first expanded item. Double click on it may delete filtering.
