### ISSUE TITLE
Dbeaver not starting

### ISSUE THREAD

**Issue by manickprime** [dbeaver/dbeaver#21713]
### Description

dbeaver isn't starting, showing an error message like this.

![image](https://github.com/dbeaver/dbeaver/assets/52126957/16c183fa-644e-471e-b06c-bdf7e5324904)

log: 
[1698757645034.log](https://github.com/dbeaver/dbeaver/files/13216731/1698757645034.log)

log content:
!SESSION 2023-10-31 18:37:24.940 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_202
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_IN
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2023-10-31 18:37:25.268
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

### DBeaver Version

version=23.2.3 branch=release_23_2_3 commit=b11bcd7d7f

### Operating System

windows 10

**Comment by bdaler** [comment]
same with a version of 23.2.3. Not starting. Downgrade to version 23.2.2 also not solve problem. 

logs after downgrade

C:\Users\bdaler\AppData\Roaming\DBeaverData\workspace6\.metadata.log 
```
!ENTRY org.eclipse.ui 2 2 2023-10-31 17:25:05.123
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)
```

"C:\Users\bdaler\AppData\Roaming\DBeaverData\workspace6\.metadata\dbeaver-debug-1698758702363.log"
```
2023-10-31 17:25:02.368 - DBeaver 23.2.2.202310081633 is starting
2023-10-31 17:25:02.369 - OS: Windows 11 10.0 (amd64)
2023-10-31 17:25:02.369 - Java version: 17.0.6 by Eclipse Adoptium (64bit)
2023-10-31 17:25:02.369 - Install path: 'C:\Program Files\DBeaver'
2023-10-31 17:25:02.369 - Instance path: 'file:/C:/Users/bdaler/AppData/Roaming/DBeaverData/workspace6/'
2023-10-31 17:25:02.370 - Memory available 64Mb/1024Mb
2023-10-31 17:25:02.382 - Create display
2023-10-31 17:25:02.490 - Initializing DBeaver 23.2.2
2023-10-31 17:25:02.492 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 23.2.2.202310081633
2023-10-31 17:25:02.492 - Initialize desktop platform...
2023-10-31 17:25:02.658 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.10.0.v20230425-0513]
> Start Core Resource Management [org.eclipse.core.resources 3.19.0.v20230510-1240]
> Start Team Support Core [org.eclipse.team.core 3.10.0.v20230317-0901]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.116.202310081633]
2023-10-31 17:25:02.975 - Initialize base platform...
2023-10-31 17:25:03.000 - Platform initialized (508ms)
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.116.202310081633]
2023-10-31 17:25:03.048 - Starting instance server at http://localhost:56309
2023-10-31 17:25:03.055 - Run workbench
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.131.202310081633]
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.17.0.v20230501-1823]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.4.0.v20230429-1914]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.6.0.v20230501-1823]
> Start Eclipse e4 Progress View [org.eclipse.e4.ui.progress 0.4.0.v20230501-1823]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.14.0.v20230501-1823]
> Start Eclipse e4 core commands [org.eclipse.e4.core.commands 1.1.0.v20230501-1823]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.18.0.v20230211-1150]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.14.0.v20230501-1533]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.5.0.v20230501-1823]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.16.0.v20230525-0648]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.18.0.v20230429-1914]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.15.0.v20230317-0802]
> Start jna [com.sun.jna 5.13.0]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.5.0.v20230317-0901]
> Start JGit SSH support based on Apache MINA sshd [org.eclipse.jgit.ssh.apache 6.6.0.202305301015-r]
> Start JGit Apache httpclient based HTTP support [org.eclipse.jgit.http.apache 6.6.0.202305301015-r]
> Start JSch Core [org.eclipse.jsch.core 1.5.0.v20230317-0901]
> Start Internet Connection Management [org.eclipse.core.net 1.5.0.v20230317-0901]
2023-10-31 17:25:05.201 - DBeaver is stopping
2023-10-31 17:25:05.204 - Stop instance server
2023-10-31 17:25:06.214 - Instance server has been stopped
2023-10-31 17:25:06.246 - DBeaver shutdown completed
```

**Comment by ShadelessFox** [comment]
Hello @manickprime @bdaler,

Can you please try following this instruction to see if it solves your issue?

https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings#manual-reset

Please let me know if it helps.

**Comment by manickprime** [comment]
Still facing the same issue! Tried deleting all the plugins too

**Comment by ShadelessFox** [comment]
Was DBeaver installed using msi/zip?

Could you try uninstalling it first and installing it again?

If it doesn't help, please send the `config.ini` file located in the installation directory (it doesn't contain any sensitive data), maybe I'll spot something weird.

**Comment by manickprime** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/52126957/7cca23dc-e5e7-4662-ab42-e2dca4ca2909)

I used msi to install. My last update failing and I guess that's why dbeaver.ini.bak was created. Is there any way I could find the update logs? I will uninstall and install a fresh instance.

**Comment by manickprime** [comment]
this is the file connect in dbeaver.ini.bak:
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
-Dosgi.requiredJavaVersion=17
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/java.nio.charset=ALL-UNNAMED
--add-opens=java.base/java.text=ALL-UNNAMED
--add-opens=java.base/java.time=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
--add-opens=java.base/jdk.internal.vm=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
--add-opens=java.base/sun.security.ssl=ALL-UNNAMED
--add-opens=java.base/sun.security.util=ALL-UNNAMED
-Xms64m
-Xmx1024m
-Ddbeaver.distribution.type=exe

**Comment by manickprime** [comment]
Dbeaver working fine after reinstalling it. Thanks for the help!

**Comment by bdaler** [comment]
I also remove full Dbeaver and install 23.2.2 version. Everything ok.

**Comment by ShadelessFox** [comment]
No, the installation history is not logged.

I'm glad the issue was solved :)
