### ISSUE TITLE
extra b' in the data

### ISSUE THREAD

**Issue by noorsyamiera92** [dbeaver/dbeaver#21718]
### Description

Im using mysql 5 and I have data consist of JSON array. 

![Screenshot 2023-11-01 at 9 12 11 AM](https://github.com/dbeaver/dbeaver/assets/40814112/c900e678-eb05-4907-a394-105dd5d8e62b)

This is when I copy the data:

`[{"id":1993,"value":""},{"id":1994,"value":""}]
[{"id":1993,"value":""},{"id":1994,"value":""}]
[{"id":1993,"value":""},{"id":1994,"value":""}]
[{"id":1993,"value":""},{"id":1994,"value":""}]
[{"id":1993,"value":""},{"id":1994,"value":""}]
[{"id":1993,"value":""},{"id":1994,"value":""}]
[{"id":1993,"value":""},{"id":1994,"value":""}]`

### DBeaver Version

Community Edition 23.2.3

### Operating System

macOS Monterey 12.7.1

### Database and driver

Database mysql 5

### Steps to reproduce

1)I just query and my data have json array in that
2) Noticed extra b' in the data

![Screenshot 2023-11-01 at 9 12 11 AM](https://github.com/dbeaver/dbeaver/assets/40814112/04d071ad-6eb9-4ada-a161-ede7be619eff)

**Comment by LonwoLonwo** [comment]
Hello @noorsyamiera92 

Please provide your driver version (you can check it with the Test Connection button in your connection settings. Table DDL. And data example.

Also, did you check your data in other tools? Workbench?

**Comment by noorsyamiera92** [comment]
It happened when i select certain column.

Ie: SELECT id, taxes FROM xxx;

But if select more columns it will be okay

Ie: SELECT id, date, taxes FROM xxx;

**Comment by LonwoLonwo** [comment]
Please provide your driver version (you can check it with the Test Connection button in your connection settings. Table DDL. And data example.

Also, did you check your data in other tools? Workbench?

**Comment by arhayka** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
