### ISSUE TITLE
Proxy Configuration Doesn't Work with Authentication

### ISSUE THREAD

**Issue by Gr33nR10t** [dbeaver/dbeaver#21712]
### Description

I have configured Dbeaver with proxy on:

- General \ Network Connections
- Connections \ Drivers

But when I try to install a new driver I get the message:

`Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"`

I have added user and pass for the proxy but the variables seems not to be read correctly.

Checking with the error log i can see this:

`System property https.proxyHost is set to 1.2.3.4 but should not be set.`

I have tried to edit the file:

`/snap/dbeaver-ce/current/usr/share/dbeaver-ce/jre/conf/net.properties`

but in the snap installation it is in read only.

### DBeaver Version

CE Version 23.2.3.202310221533

### Operating System

CentOS 7.9

### Database and driver

I was trying to install the MariaDB driver but without success for the proxy authentication problem.

### Steps to reproduce

1 Set the proxy with user and pass
2 Install a database driver

**Comment by Gr33nR10t** [comment]
I have observed a strange behavior, setting:

General \ "Active provider: Manual" \ HTTPS

The "Install New Software.." under the menu help work fine; but the "Check for updates" continue to give me a 407 proxy error.

**Comment by LonwoLonwo** [comment]
Hello.
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by Gr33nR10t** [comment]
Here the log file:
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/13510638/dbeaver-debug.log)

Regards
G.
