### ISSUE TITLE
Nested case causes failure

### ISSUE THREAD

**Issue by the-ure** [dbeaver/dbeaver#21716]
### Description

SQL Error [102] [S0001]: Incorrect syntax near 'Well'.

![image](https://github.com/dbeaver/dbeaver/assets/140629801/151539b6-2a4c-49aa-b164-f4590c713dfd)

### DBeaver Version

23.1.0.202306041939

### Operating System

win11Ent

### Database and driver

SQLserver TSQL Vanilla

### Steps to reproduce

works in Microsoft SQL Server MGT Studio, first one i tried in DBvr fails.
i updated my drivers and DBvr version... and it fails.

If i add parenthesis to coach it it gives different errors but still fails. it seems to not be able to handle the two 'END' statements consecutive.

**Comment by LonwoLonwo** [comment]
Hello @the-ure 

Please provide a text of your query for tests. And your driver version. You can find it in your connections settings -> Test Connection.

**Comment by arhayka** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
