### ISSUE TITLE
Redundant copy option in context menu

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#21723]
### Description

![dbeaver_pH97ezQ9Iv](https://github.com/dbeaver/dbeaver/assets/84867187/91d0b071-2ef2-4155-ada7-9a80f52a6656)

### DBeaver Version

DBeaver 23.2.3

### Operating System

windows 10

**Comment by brunodmartins** [comment]
@MashaKorax and @ShadelessFox , I tested under Linux and checked that most of the context menus (Table, Column) return the same values despite using _Copy_ and _Copy Advanced Info_.  The fix should be remove this advanced option from those menus?

**Comment by ShadelessFox** [comment]
Yes, because they make no sense for "special nodes", such as loading node, filter placeholder, and "load more" placeholder.

**Comment by brunodmartins** [comment]
I will try to remove it and open a PR

**Comment by MashaKorax** [comment]
@brunodmartins We always welcome help for improvement DBeaver

**Comment by brunodmartins** [comment]
PR opened @MashaKorax and @ShadelessFox !
