### ISSUE TITLE
unterminated BEGIN_PROC string Netezza SQL procedure

### ISSUE THREAD

**Issue by StockdaleEoE** [dbeaver/dbeaver#21728]
### Description

Hi

I am evaluating Dbeaver. 

We use Netezza as our dataware house platform.

I have a stored procedure whcih creates successfully using Coginiti. I take the same SQL code, no changes  and try to create the procedure with dbeaver and get a 'unterminated BEGIN_PROC string' error message

_SQL Error [1100] [HY000]: ERROR:  'CREATE OR REPLACE PROCEDURE REPORTING.SP_NETEZZA_VALIDATE_SQL_VIEW_CONTROL (char(250),CHAR(250))
RETURNS INTEGER
EXECUTE AS OWNER
LANGUAGE NZPLSQL AS
BEGIN_PROC'
error                                                                                                                                                             ^ found "" (at char 154) unterminated BEGIN_PROC string_

### DBeaver Version

Dbeaver Enterprise 23.2.0

### Operating System

Windows x64

### Database and driver

Database: Netezza  11.2.1.7

**Comment by LonwoLonwo** [comment]
Hello @StockdaleEoE 

Please provide your procedure DDL for testing.

Also, did you try to highlight the entire procedure text and then execute it in the SQL Editor?

**Comment by StockdaleEoE** [comment]
Yes. I tried highlighting all the text with no success.

DDL attached.

Thanks

**Comment by LonwoLonwo** [comment]
Sorry, I do not see the DDL. Could you please provide it one more time? You can add it to the main topic.

**Comment by StockdaleEoE** [comment]
DDL below.

CREATE OR REPLACE PROCEDURE REPORTING.SP_NETEZZA_VALIDATE_SQL_VIEW_CONTROL (char(250),CHAR(250))
RETURNS INTEGER
EXECUTE AS OWNER
LANGUAGE NZPLSQL AS
BEGIN_PROC

--*************************************************************************************
-- Description : Stored Procedure to control the validatation of SQL Views
--                It updates table NETEZZA_SQL_VIEWS_STATUS 
--
--                2 parameters passed as input.
--                  Database
--                   Schema
--
-- Date        : 23/10/2023
-- Request     : BI-5205
-- Programmer  : Len Stockdale
--*************************************************************************************
-- Amendment History
--
-- Change     : #1
-- Description: 
-- Request    : 
-- Programmer : 
--*************************************************************************************
-- Change     : #2
-- Description:  
-- Request    : 
-- Programmer :  
--*************************************************************************************

--CONTENTS
--1---DROP DELETE Current records off the table
--2---Build table
--3---Read view table and run validate view
--4--Update status table



DECLARE

--Declare input parameters
	
	
	PARAMETER_INPUT_DATABASE    ALIAS FOR $1;
	PARAMETER_INPUT_SCHEMA      ALIAS FOR $2; 
	
-- Basic Variables for error handle and Selects
	var_report_code     		CHAR(10) := 'VALIDSQL';
	var_message_type  			CHAR(10);
	var_message_text  			CHAR(1000);
	var_apostrophe      		CHAR(1);
	var_blank           		CHAR(1) := ' ';
	var_domain          		CHAR(10) := 'IT';
	var_comma           		CHAR(1) := ',';
	var_dot                     CHAR(1) := '.';
	var_returncode      		INT;
	var_view_Code_description   CHAR(50);
	var_input_year       	    INT := 0;
	var_input_week          	INT := 0;
	
	var_database         		character(250);
	var_schema					character(250);
	
	var_recColumn	   			RECORD; 
	var_selectSQL      			NVARCHAR(8000) := '';
	var_updateSQL      			NVARCHAR(8000) := '';
	var_view_name				character(250);
  

--********************************************
-- Start process
--*********************************************
BEGIN

	var_database := rtrim(PARAMETER_INPUT_DATABASE);
	var_schema := rtrim(PARAMETER_INPUT_SCHEMA);
	var_apostrophe := '''';
   
--------------------------------------------
--1---Delete current records             ---
--------------------------------------------

BEGIN


-- Log STATUS: Log the start of the procedure
    var_message_type := 'STATUS';
    var_message_text := 'Start Procedure - REPORTING. SP_NETEZZA_VALIDATE_SQL_VIEWS.';
    CALL REPORTING.SP_UPDATE_MESSAGE_LOG(var_report_code,var_domain,var_message_type,var_message_text,0,0);


-- Log STATUS: Log the start of the operation
     var_message_type := 'STATUS';
     var_message_text := 'REPORTING. SP_NETEZZA_VALIDATE_SQL_VIEWS. About to delete records from REPORTING.NETEZZA_SQL_VIEWS_STATUS table.';
     CALL REPORTING.SP_UPDATE_MESSAGE_LOG(var_report_code,var_domain,var_message_type,var_message_text,0,0);
   
--Perform the DELETE operation
 EXECUTE IMMEDIATE 'DELETE from REPORTING.NETEZZA_SQL_VIEWS_STATUS';
 
EXCEPTION WHEN OTHERS THEN
	ROLLBACK; -- Rolls back any work done above
	RAISE NOTICE 'Caught Exception', SQLERRM;
	var_message_type := 'ERROR';
	CALL REPORTING.SP_UPDATE_MESSAGE_LOG(var_report_code,var_domain,var_message_type,SQLERRM,0,0);
	COMMIT; -- Commits the error log insert
	RETURN 90;
END;

----------------------------------------------
--2---Build the table with the current views -
----------------------------------------------

 BEGIN 
-- Log STATUS: Log the start of the operation
    var_message_type := 'STATUS';
    var_message_text := 'REPORTING. SP_NETEZZA_VALIDATE_SQL_VIEWS. Building list of views.';
    CALL REPORTING.SP_UPDATE_MESSAGE_LOG(var_report_code,var_domain,var_message_type,var_message_text,0,0);

	EXECUTE IMMEDIATE 'Insert into reporting.NETEZZA_SQL_VIEWS_STATUS 
							 select 
							 database,
							 schema,
							 viewname,
							 description
							 from _v_view 
							 where schema = ' || var_apostrophe || var_schema || var_apostrophe;
	
    
EXCEPTION WHEN OTHERS THEN
		ROLLBACK; -- Rolls back any work done above
		RAISE NOTICE 'Caught Exception', SQLERRM;
		var_message_type := 'ERRORS';
		CALL REPORTING.SP_UPDATE_MESSAGE_LOG(var_report_code,var_domain,var_message_type,,SQLERRM,0,0);
		COMMIT; -- Commits the error log insert
		RETURN 91;
		
END; 

------------------------------------------------------------
--3--Read view table and run SELECT count(*) against each view.
--------------------------------------------------------------

BEGIN
-- Log STATUS: Log the start of the operation
    var_message_type := 'STATUS';
    var_message_text := 'REPORTING. SP_NETEZZA_VALIDATE_SQL_VIEWS. Running validation check against the views.';
    CALL REPORTING.SP_UPDATE_MESSAGE_LOG(var_report_code,var_domain,var_message_type,var_message_text,0,0);
--
--Build select statement
--
	    var_selectSQL := 'Select VIEW_NAME as VIEW_NAME from REPORTING.V_NETEZZA_SQL_VIEWS_STATUS where SCHEMA = '
									|| var_apostrophe || var_schema || var_apostrophe
									|| ' and DATABASE = ' || var_apostrophe || var_database || var_apostrophe;
									
	 	--RAISE NOTICE 'select SQL : %,',var_selectSQL;
		--return 157; 	 

for var_recColumn IN EXECUTE 'Select VIEW_NAME as VIEW_NAME from REPORTING.V_NETEZZA_SQL_VIEWS_STATUS where SCHEMA = '
									|| var_apostrophe || var_schema || var_apostrophe
									|| ' and DATABASE = ' || var_apostrophe || var_database || var_apostrophe
									|| ' and VALID_VIEW_CODE = 100'
									|| ' Order by VIEW_NAME'
						
loop
	--
	--Set view name variable
	--
	var_view_name := var_recColumn.VIEW_NAME;
	
	--
	--Process each view
	--
		--
		-- Run sQL count(*)
		-- this is achevied by call an SQL SP an interrogating the return code
		--
		
		var_returncode := REPORTING.SP_NETEZZA_VALIDATE_SQL_VIEW (var_database, var_schema, var_view_name);
		--
		--Validate return code
		--
		-- 0 = no error found
		-- 90 = view name blank
		-- 91 = Invalid view (count failed)
		var_view_Code_description := 'Not yet validated.'; -- initialise
		
		if (var_returncode = 0) then
			var_view_Code_description := 'Valid view. No error.';
		end if;
		
		if (var_returncode = 50) then
			var_view_Code_description := 'WARNING: View has no description.';
		end if;
		
		if (var_returncode = 51) then
			var_view_Code_description := 'ERROR: Invalid SQL view.';
		end if;
		
		if (var_returncode = 1000) then
			var_view_Code_description := 'ERROR: SQL ERROR in SQL SP.';
			exit;
		end if;
		
		var_view_Code_description := rtrim(var_view_Code_description);
	
		--
		--Update Status table
		--
		
		var_updateSQL := '';
		var_updateSQL := 'Update REPORTING.NETEZZA_SQL_VIEWS_STATUS SET VALID_VIEW_CODE = ' 
		                    || var_returncode || var_comma
							|| ' VIEW_CODE_DESCRIPTION = ' || var_apostrophe || var_view_Code_description || var_apostrophe
							|| ' WHERE DATABASE = ' || var_apostrophe || var_database || var_apostrophe
							|| ' and SCHEMA = ' || var_apostrophe || var_schema || var_apostrophe
							|| ' and VIEW_NAME = ' || var_apostrophe || var_recColumn.VIEW_NAME || var_apostrophe;
			
		
		BEGIN
			EXECUTE IMMEDIATE var_updateSQL;
			EXCEPTION WHEN OTHERS THEN
				RAISE NOTICE 'UPDATE SQL : %,',var_updateSQL;
				--return 213; 	 		
					
				ROLLBACK; -- Rolls back any work done above
				RAISE NOTICE 'Caught Exception', SQLERRM;
				var_message_type := 'ERRORS';
				CALL REPORTING.SP_UPDATE_MESSAGE_LOG (var_report_code,var_domain,var_message_type,SQLERRM,0,0);
				COMMIT; -- Commits the error log insert
				
				if (var_returncode = 1000) THEN
					Exit; -- leave loop. 1000 error should not occur
				END IF;
			RETURN 93;
		 END;
			
			
						
END LOOP;

END;

--
--Successfully completed, return 0 error code and place note in Update message log
--
    var_message_type := 'STATUS';
    var_message_text := 'Successfull Procedure - REPORTING.SP_NETEZZA_VALIDATE_SQL_VIEWS.';
    CALL REPORTING.SP_UPDATE_MESSAGE_LOG(var_report_code,var_domain,var_message_type,var_message_text,0,0);
	RETURN 0;
--*****************************************************************************************************************

EXCEPTION WHEN OTHERS THEN
	ROLLBACK; -- Rolls back any work done above
	RAISE NOTICE 'Caught Exception', SQLERRM;
	var_message_type := 'ERROR';
	CALL REPORTING.SP_UPDATE_MESSAGE_LOG(var_report_code,var_domain,var_message_type,SQLERRM,0,0);
	COMMIT; -- Commits the error log insert
	RETURN 1000;
END;	
--*****************************************************************************************************************


END_PROC;
COMMENT ON PROCEDURE REPORTING.SP_NETEZZA_VALIDATE_SQL_VIEW_CONTROL (char(250),char(250)) IS 'Procedure to control the validation of  SQL views. BI-5205';

**Comment by LonwoLonwo** [comment]
What part of this text do I need for testing?

Also, can you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by StockdaleEoE** [comment]
You need all the file SQL text. I am trying to create a SQL stored procedure via dbeaver,

I need to get our IT services to give me access to the logs. I will add them when I get access.

**Comment by LonwoLonwo** [comment]
Sometimes, DBeaver can't parse a big procedure body and can execute not the whole script but for the first semicolon in the script. 

You can check and compare it in the Query Manager: https://github.com/dbeaver/dbeaver/wiki/Query-Manager

Maybe you highlighted not the full text? Did you include the comment part? Or finished on the last `END_PROC;` part?

**Comment by StockdaleEoE** [comment]
[ATT59283.log](https://github.com/dbeaver/dbeaver/files/13248401/ATT59283.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/13248406/dbeaver-debug.log)

**Comment by StockdaleEoE** [comment]
Even though I have highlighted all the query text, it does attempt to execute any code after:
	PARAMETER_INPUT_DATABASE    ALIAS FOR $1;

**Comment by StockdaleEoE** [comment]
Query Manager shows this
CREATE OR REPLACE PROCEDURE REPORTING.SP_NETEZZA_VALIDATE_SQL_VIEW_CONTROL (char(250),CHAR(250))
RETURNS INTEGER
EXECUTE AS OWNER
LANGUAGE NZPLSQL AS
BEGIN_PROC

--*************************************************************************************
-- Description : Stored Procedure to control the validatation of SQL Views
--                It updates table NETEZZA_SQL_VIEWS_STATUS 
--
--                2 parameters passed as input.
--                  Database
--                   Schema
--
-- Date        : 23/10/2023
-- Request     : BI-5205
-- Programmer  : Len Stockdale
--*************************************************************************************
-- Amendment History
--
-- Change     : #1
-- Description: 
-- Request    : 
-- Programmer : 
--*************************************************************************************
-- Change     : #2
-- Description:  
-- Request    : 
-- Programmer :  
--*************************************************************************************

--CONTENTS
--1---DROP DELETE Current records off the table
--2---Build table
--3---Read view table and run validate view
--4--Update status table



DECLARE

--Declare input parameters
	
	
	PARAMETER_INPUT_DATABASE    ALIAS FOR $1

**Comment by StockdaleEoE** [comment]
I have to go back to my old tool to continue development.

Any advise would be appreciated as dbeaver (at the moment) is unusable but I really want to use the tool but am unable to at present.

**Comment by StockdaleEoE** [comment]
Hi
I have resolved the issue.  After the END_PROC; I have a COMMENT ON  PROCEDURE command.
dbeaver did not like this.  If I executed all the SQL up to the END_PROC only then it created the stored procedure.

I then ran the COMMENT ON PROCEDURE as a separate script and it worked OK.

**Comment by LonwoLonwo** [comment]
Thanks for the update @StockdaleEoE
