### ISSUE TITLE
Generate drop comment into function DDL

### ISSUE THREAD

**Issue by DavidPavlicek** [dbeaver/dbeaver#21720]
In Postgres, when I generate a function DDL script, there is no commented drop SQL command for that function in the script. When I generate DDL for a table, there it is.  The only way I can generate a drop command for a function is by clicking "delete" and then "view script". It would be more convenient and safer to generate it as a commented part of a DDL script.

**Comment by LonwoLonwo** [comment]
Hello @DavidPavlicek 

Thanks for the idea.
