### ISSUE TITLE
Error, when try to open AI on mac in CE from early access plugin

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#21733]
### Description

1. On Mac in DBeaver CE install AI from link https://dbeaver.io/files/ea/update/ce/
2. After restart open SQL script - press AI btn -see error
<img width="950" alt="Снимок экрана 2023-11-02 в 16 09 06" src="https://github.com/dbeaver/dbeaver/assets/84867187/729ca749-0090-430e-981c-379dc663c7fb">

### DBeaver Version

23.2.4

### Operating System

mac M1 monterey 12

**Comment by Destrolaric** [comment]
Quite possibly happens due to using EE workspace, which had Azure AI configured, we probably want to change to default in that case
