### ISSUE TITLE
Error getting JDBC meta data

### ISSUE THREAD

**Issue by TiagoSC-TDS** [dbeaver/dbeaver#21746]
Description
when creating a new connection, it shows the following error and test connection failed

Error getting JDBC meta data
  connection is closed
  connection is closed

DBeaver Version
Community 23.2.3

Operating System
Windows 10

Database and driver
SQLSERVER

SQLSERVER driver provided by Dbeaver by default

Steps to reproduce
create a new connection
select SQLSERVER
enter user name, host, password, port, database name
test connection
Additional context
No response

[log.txt](https://github.com/dbeaver/dbeaver/files/13250120/log.txt)

**Comment by E1izabeth** [comment]
Is this database running on your local machine or it's on some server?

**Comment by TiagoSC-TDS** [comment]
> Is this database running on your local machine or it's on some server?

In a Server

**Comment by LonwoLonwo** [comment]
Hello @TabrisSousa9 

What server version do you have and what driver version do you have? Driver version you can find n your Connection Settings -> Driver Settings -> Libraries

**Comment by LonwoLonwo** [comment]
Maybe a driver downgrade will help in your case: https://github.com/dbeaver/dbeaver/issues/19499#issuecomment-1506666271

**Comment by TiagoSC-TDS** [comment]
The connection return after upgrade the software

**Comment by LonwoLonwo** [comment]
Thanks for the update @TabrisSousa9
