### ISSUE TITLE
ISSUES WITH DBEAVER DRIVER SETTINGS FOR SQL SERVER

### ISSUE THREAD

**Issue by TiagoSC-TDS** [dbeaver/dbeaver#21745]
Description
When trying to create a new connection with a data base SQL SEVER i only get this error:

"Error resolving dependencies
  Index 0 out of bounds for length 0
  Index 0 out of bounds for length 0"

DBeaver Version
Community 23.2.3

Operating System
Windows 10

Database and driver
SQLSERVER

SQLSERVER driver provided by Dbeaver by default

Steps to reproduce
create a new connection
select redshift
enter user name, host, password, port, database name
test connection

![sql_server_drivers](https://github.com/dbeaver/dbeaver/assets/80930411/9d4474cb-a895-46df-b7f7-4f68d9030174)

**Comment by E1izabeth** [comment]
Could you try removing the blue item from the driver libraries?

**Comment by TiagoSC-TDS** [comment]
Yes, but i get the same problem

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.
