### ISSUE TITLE
please add script name and change script storage path

### ISSUE THREAD

**Issue by 1013461195** [dbeaver/dbeaver#21740]
**Is your feature request related to a problem? Please describe.**
script name always -1/-2/-3/-4, want find script need open one by one. 
want change script storage path to sync cloud, open on other pc

**Describe the solution you'd like**
add script rename function and change script storage path function

**Describe alternatives you've considered**
right click on script tab, open rename button.
setting add change script storage path

**Comment by E1izabeth** [comment]
1. Rename
You can rename script from the context menu here 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/30cd75c9-d2c9-4caa-abc3-e7e94d3ff0a6)

or here

![image](https://github.com/dbeaver/dbeaver/assets/28875055/ecc9c4af-9b31-4054-85ce-44bbff61b8e0)

or here

![image](https://github.com/dbeaver/dbeaver/assets/28875055/1ed945a6-c25d-438c-a9dc-adfb11a9a162)


2. Location
You can use `Save As` option to change the script location
![image](https://github.com/dbeaver/dbeaver/assets/28875055/dd38fb41-9322-4902-9ee6-5f6e4988b6ec)

Another way is to link an external directory to your project to either save your scripts into it, or to access scripts that were created outside of DBeaver.
To link an External directory right-click anywhere in the Project Explorer and pick Create -> Link Folder. There you can link any directory on your drive to a project. This will allow you to open any externally created scripts through Project explorer and to set this folder as default to save new scripts into (See https://github.com/dbeaver/dbeaver/wiki/Script-Management#changing-default-scripts-directory).

![image](https://github.com/dbeaver/dbeaver/assets/28875055/5ee7e797-a579-4dd1-9056-6c6cbf961de9)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
