### ISSUE TITLE
Oracle Foreign Key Constraint showing incorrect relationship

### ISSUE THREAD

**Issue by chankon45** [dbeaver/dbeaver#21749]
### Description

I downloaded free version of DBeaver yesterday as an alternative to Toad for Oracle and as I am testing the tool, found that the Foreign Key constraint is showing incorrect mapping. Attached screenshots from DBeaver and Toad. Toad is showing correct mapping.

![DBeaver](https://github.com/dbeaver/dbeaver/assets/75909032/f8453caa-f94c-45fd-8e1b-1e221fe99987)
![Toad](https://github.com/dbeaver/dbeaver/assets/75909032/36d84090-85db-4086-89f2-6e3fcd864d46)

### DBeaver Version

23.2.3.202310221533

### Operating System

Windows 10

### Database and driver

Oracle Database 19c

**Comment by LonwoLonwo** [comment]
Hello @chankon45 

Please provide table DDLs for tests.

**Comment by chankon45** [comment]
Emailed

**Comment by chankon45** [comment]
Able to recreate issue. New email just sent.

**Comment by ShadelessFox** [comment]
Hello @chankon45,

I don't see anything suspicious. On both screenshots, there's a constraint called `MARRS_INSPECTION_ROOM_TDL_R04` with three columns listed: `FACILITY`, `FLOOR`, and `ROOM`. I suspect other constraints to be listed below, but they are cropped on the screenshot that is from DBeaver.

Can you please tell what's wrong?

**Comment by chankon45** [comment]
Check my first msg on bug report and see screenshots on constraint point to which table. Dbeaver shows wrong table.

**Comment by chankon45** [comment]
Ref Table in Dbeaver shows wrong table. It should be ARDATADM.TBROOMMASTER.
DBeaver shows it as: PERSONEL_INFO_FOR_ARIES.

**Comment by ShadelessFox** [comment]
Thank you for the clarification. We are still waiting for a sample DDL we can try to reproduce the issue against.

**Comment by chankon45** [comment]
I emailed ddls couple of days back and one yesterday showing able to reproduce issue. 

Sent from Yahoo Mail for iPhone

**Comment by chankon45** [comment]
Se attached files.
Able to reproduce it by creating a new table in ARDATADM schema and DBeaver shows constraint now points to this new table (image: DBeaver2.jpg)
So my guess is it's point to latest DDL object.

**Comment by ShadelessFox** [comment]
You can't attach files via email. Please post them on github: https://github.com/dbeaver/dbeaver/issues/21749

**Comment by chankon45** [comment]
Attached DDLs for tables:
marrs_inspection_room_details.txt (from Toad)
tbdataroommaster.txt (from Toad)
test_dbeaver.txt (from Toad)
marrs_inspection_room_details_from_dbeaver.txt (From DBeaver)

Screenshots of DBeaver Foreign key Refs and ERDs. 

Please let me know if you need any other info.
test_dbeaver table is created for reproduce the issue. When new table is created, this foreign key constraint is point to this table.
DBeaver DDL is showing correct script for marrs_inspection_room_details


[marrs_inspection_room_details_from_dbeaver.txt](https://github.com/dbeaver/dbeaver/files/13311849/marrs_inspection_room_details_from_dbeaver.txt)
[tbdataroommaster.txt](https://github.com/dbeaver/dbeaver/files/13311777/tbdataroommaster.txt)
[marrs_inspection_room_details.txt](https://github.com/dbeaver/dbeaver/files/13311779/marrs_inspection_room_details.txt)
[test_dbeaver_Table_DDL.txt](https://github.com/dbeaver/dbeaver/files/13311783/test_dbeaver_Table_DDL.txt)
[marrs_inspection_room_details_from_dbeaver.txt](https://github.com/dbeaver/dbeaver/files/13311854/marrs_inspection_room_details_from_dbeaver.txt)

![DBeaver2](https://github.com/dbeaver/dbeaver/assets/75909032/0bdbf1f5-96d9-4cea-a4ec-6b39eb962efc)
![DBeaverERD](https://github.com/dbeaver/dbeaver/assets/75909032/5031ebb9-3803-45d0-b84a-d2c2bfe11653)
![DBeaverERD2](https://github.com/dbeaver/dbeaver/assets/75909032/9ecbbcf6-5210-4b54-bb12-a663516980dc)
![DBeaver](https://github.com/dbeaver/dbeaver/assets/75909032/f13772a6-d3a9-4686-8d3e-491e60981fff)

**Comment by chankon45** [comment]
Updated.

**Comment by ShadelessFox** [comment]
Thank you.

**Comment by ShadelessFox** [comment]
I'm sorry for the long wait.

Unfortunately, we were unable to use the provided DDL to reproduce the issue as it is pretty complex and seems incomplete.

Can you please provide a minimal reproducible example?

**Comment by chankon45** [comment]
Create tables in 2 different schemas and create a foreign on one table point to 2nd schema table. It's that simple to reproduce.

**Comment by chankon45** [comment]
Then create 3rd table in the 2nd schema and 1st table which you have foreign key to 2nd table now points to 3rd table in ERD.

**Comment by ShadelessFox** [comment]
I was unable to reproduce against the following DDL:

```sql
create table user2.t1(col1 number primary key);
create table user2.t2(col1 number);
alter table user2.t2 add constraint fk_t2_t1 foreign key (col1) references user2.t1(col1);

create table user1.t3(col1 number);
alter table user1.t3 add constraint fk_t3_51 foreign key (col1) references user2.t1(col1);
```

Please provide something similar for your case. Without it, we won't be able to reproduce and fix your issue.

**Comment by chankon45** [comment]
You still doing wrong.

create table user2.t1(col1 number primary key);

create table user1.t2(col1 number primary key);  (user1 schema not in user2 schema).

alter table user2.t1 add constraint fk_t2_t1 foreign key (col1) references user1.t2(col1);

Check ERD user2.t1. (should be fine).

Now 
create table user1.t3(col1 number);

Now check ERD of user2.t1 , it will be pointing to t3 instead of t2.

**Comment by ShadelessFox** [comment]
After following your steps, I'm still unable to reproduce the issue. The ERD correctly shows me `T1 -> T2` relation:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/33ca599e-9438-4955-9e13-d1de4251dc3b)

I think it's worth mentioning that I'm using Oracle 12c. Maybe something was changed between Oracle 12c and Oracle 19c?

**Comment by chankon45** [comment]
I would like to help, but kind of busy. Also there are lot of changes to 12c to 19c. We saw lot of changes and restrictions in coding. I will try to recreate my side again sometime this week or next week.

**Comment by ShadelessFox** [comment]
Thank you for helping us. Looking forward to seeing the results.

**Comment by chankon45** [comment]
Looks like DBeaver latest version fixed the issue. I  am not seeing the issue in Dbeaver 23.2.5.202311191730.

**Comment by ShadelessFox** [comment]
Oh, interesting. I didn't notice you weren't on the latest version.

I can't recall seeing any changes regarding metadata reading for the past several releases, so I'm not sure what has changed exactly.

**Comment by chankon45** [comment]
Error was there until most recent update.

**Comment by chankon45** [comment]
First version I downloaded is 23.2.3.202310221533. 
And error was there until before 23.2.5.202311191730. So something changed in between these versions.

**Comment by ShadelessFox** [comment]
Thanks for checking out. I assume the issue can be closed now, regardless?

**Comment by chankon45** [comment]
I think so. Btw, our group not recommending this tool as alternative to toad at this time even for limited users that have oracle databases as we need more testing and we are supporting health care applications and need to be more careful what we provide to others when we export info from these tools. It looks like  good tool but we are  hesitant to use at this time. Thank you.

**Comment by ShadelessFox** [comment]
It's unfortunate to hear that. We are constantly working on improving DBeaver, and I'm sure it will be even better in the future, and such critical bugs will be all hunted down and fixed. Anyway, thank you for the cooperation.

**Comment by chankon45** [comment]
Issue still there in version 23.3.0.202312122044. Still seeing incorrect ERD on existing tables.
