### ISSUE TITLE
How to pick a point in the map? + Other issues using spatial data

### ISSUE THREAD

**Issue by mauriciabad** [dbeaver/dbeaver#21748]
Hi, I'm working in a project with geospatial data and I need to fill the database with some values, but I can't find a way to pick or edit a location using the map.

In fact, my experience is that the spatial data in MySQL in dbeaver are completely broken: (I can't view, edit or create properly)
1. The map doesn't show the correct location with the SRID I'm using (25831).
   - I noticed that if I manually change the SRID to 4326, then it shows the right location.
3. I can't manually edit the point text (see screenshot below), there's an error when I save.
4. I can't find a way to select a point in the map to edit the value. 

![error messsage](https://github.com/dbeaver/cloudbeaver/assets/12821361/c51a2397-a965-44db-8c3e-403738604425)

I guess I'm doing something wrong. But the things I need are so simple that I'm surprised that I can't find solutions.

**Comment by ShadelessFox** [comment]
Hello @mauriciabad,

Can you please provide a DDL for your table?

You can select a row containing a particular geometry value by first selecting all rows in the grid and then clicking on the desired feature on the map:

https://github.com/dbeaver/dbeaver/assets/35821147/31bfb1a2-0ffd-4bf3-ba3e-c0c8e7682aaa

**Comment by mauriciabad** [comment]
This is how I created the row (extracted from my migration sql files)

```sql
ALTER TABLE `place` ADD `location` POINT SRID 25831 NOT NULL;
```

DBeaver gives me this DDL:
```sql
-- `descobreix-begur-app`.place definition

CREATE TABLE `place` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `mainImage` varchar(1024) DEFAULT NULL,
  `name` text NOT NULL,
  `location` point NOT NULL /*!80003 SRID 25831 */,
  `mainCategoryId` int NOT NULL,
  `featuresId` int DEFAULT NULL,
  `description` tinytext,
  `content` text,
  `verificationRequirementsId` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=87 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

<img width="1655" alt="Screenshot 2023-11-18 at 12 02 20 AM" src="https://github.com/dbeaver/dbeaver/assets/12821361/665788c5-6c19-4309-877a-1bb815b9d798">

--------------

I didn't use the right wording for point 3. What I meant is to be able to click anywhere in the map, and the clicked location can be used to update or create a row. Like a "Pick new point in map" feature.

This is how I have to get the latitude and longitude (using Google Maps):

https://github.com/dbeaver/dbeaver/assets/12821361/efdf9d27-ead0-4ea6-8253-3868c8d93b65

And, then I have to create a raw SQL insert statement to add a new db row, because I can't do it in the UI, due to errors.

**Comment by ShadelessFox** [comment]
Thanks for the provided information. We will investigate the issue later.

Regarding the third point, you can right-click anywhere on the map to copy the coordinates of that location:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/e3586fdc-e60b-43c2-baf2-08b4dbdef10c)

Please let me know if it helps.
