### ISSUE TITLE
[Oracle] Change type of a column adds unecessary "NULL" at the end of the alter column query

### ISSUE THREAD

**Issue by angeousta** [dbeaver/dbeaver#21757]
### Description

I think this line https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/sql/edit/struct/SQLTableColumnManager.java#L81C46-L81C46 is wrong because in oracle you don't need to add "NULL" at the end

Example
ALTER TABLE SCHEMA_NAME.TABLE_NAME MODIFY COLUMN_NAME NUMBER(5,0) NULL;
it should be simply
ALTER TABLE SCHEMA_NAME.TABLE_NAME MODIFY COLUMN_NAME NUMBER(5,0);
or
ALTER TABLE SCHEMA_NAME.TABLE_NAME MODIFY COLUMN_NAME NUMBER(5,0) NOT NULL;

### DBeaver Version

23.2.3.202310221533 community

### Operating System

Win 10

### Database and driver

Oracle Latest driver

### Steps to reproduce

Alter a column type of an oracle table which is nullable (so it's not "NOT NULL")

**Comment by LonwoLonwo** [comment]
Hello @angeousta 

Thanks for the report.
