### ISSUE TITLE
Background of SQL editors always black

### ISSUE THREAD

**Issue by nicolamarangoni** [dbeaver/dbeaver#21759]
### Description

Background of SQL editors always black.
Settings in "User Interface" -> "Appearance" are ignored.

I tried the following:
- removing the option "Enable theming"
- set theme to "Classic", "Classic theme"

The background of SQL scripts remains black

### DBeaver Version

Community Edition 23.2.4

### Operating System

macOS 14.1

### Database and driver

Any

### Steps to reproduce

Open a new or an existing SQL editor

**Comment by E1izabeth** [comment]
Am I correctly understood that it's reproducible on both themes: Light and Classic?
What's the color of the font then? Could you provide a screenshot of how does it look like?

**Comment by nicolamarangoni** [comment]
Hi, yes it's reproducible in both light and classic. The font is black. That's why the scripts are nor readable.

<img width="1078" alt="Screenshot 2023-11-07 at 10 25 25" src="https://github.com/dbeaver/dbeaver/assets/7083416/90e35d60-a09f-485c-b697-c4aeabd92494">

**Comment by E1izabeth** [comment]
Could you try [resetting ui settings](https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings)?

**Comment by nicolamarangoni** [comment]
Resetting the UI settings fixed the issue. Many thanks!
It is possible that the issue was caused by a previous installation of the darkest theme.
After upgrading top the latest version i didn't reinstall the theme-plugin but some configs should have been still present in the settings.

**Comment by E1izabeth** [comment]
Thank you for update.
If the bug will return to you, please let me know
