### ISSUE TITLE
[Oracle] Hyperlinks in SQL Editor ignore case to open a table

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#21753]
### Description

If there are 2 tables with the same name but different case in it, hyperlink will always open the first one shown in the navigator even if there are quotes in the editor specifically showing which case is used

### DBeaver Version

23.2.4

### Operating System

Any

### Database and driver

Oracle

### Steps to reproduce

1. Create two table with the same name, but different case e.g. "TEST".TABLE and "TEST"."table"
2. Type the name of a lowercase table "TEST"."table" in SQL Editor
3. Ctrl + left-click on table name

**Expected:** "TEST"."table" is opened
**Actual:** "TEST".TABLE is opened

**Comment by Matvey16** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/dbeaver/project/8805?defectId=14773)

**Comment by LonwoLonwo** [comment]
This is a more general issue. (Reproducible in Snowflake also)

https://github.com/dbeaver/dbeaver/blob/4263c9223bbb84a129f2e08e0d8cc643c7dc8b64/plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/syntax/SQLContextInformer.java#L375-L380

For now, we are changing an original case and then trying to find this object. And it is helpful when a database can not have objects like `table` and `TABLE` in one schema.

We may need a special setting for searching in the SQL Editor.

**Comment by E1izabeth** [comment]
Seems I have already fixed it recently, because I can't reproduce it now.

**Comment by Matvey16** [comment]
Verified
