### ISSUE TITLE
Cannot scroll restore status while restoring

### ISSUE THREAD

**Issue by Ataye** [dbeaver/dbeaver#21755]
### Description

I started a restore job for a remote postgresql database, and scrolled up in the history for check some output, then the restore window stopped updating and i couldn't scroll the results any more, and it wouldn't give me any updates until it was complete.

After restore completed i could scroll, but found there was a scrolled panel within the main scroll area.

### DBeaver Version

Community Version 23.2.3.202310221533

### Operating System

Windows 11

### Database and driver

Postgresql 

### Steps to reproduce

1. Start a restore job,
2. Scroll up in the result history.

**Comment by LonwoLonwo** [comment]
Hello @Ataye 

Can you please provide footage showing your issue? Thank you.
Also, please provide the log files. You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by arhayka** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
