### ISSUE TITLE
[SQL Server] The word "NOLOCK" is not correctly spelled

### ISSUE THREAD

**Issue by epsilxn** [dbeaver/dbeaver#21762]
**Is your feature request related to a problem? Please describe.**
Please add syntax highlighting for the NOLOCK keyword. Now this word is highlighted as unknown

**Describe the solution you'd like**
It would be cool if the word NOLOCK was highlighted in the same way as the word SELECT/FROM/WHERE/etc

**Comment by LonwoLonwo** [comment]
Hello @epsilxn 

Thanks for the idea.

**Comment by brunodmartins** [comment]
I want to work on this issue!

**Comment by brunodmartins** [comment]
@LonwoLonwo I dont see this keyword on the official [SQL Server Keywords](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-ver16). Although, we can still add it, right?

**Comment by epsilxn** [comment]
@brunodmartins I'm sorry, I put it a little wrong. This is not a keyword, it's a table hint (previously I meant it as just a word that is in the code editor). It is possible that hints dbeaver exist separately in the source code. I hope this information will help to understand

https://learn.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-table?view=sql-server-ver16#nolock

**Comment by LonwoLonwo** [comment]
We can add it to the keywords list (for SQL Server), I think.

**Comment by brunodmartins** [comment]
@LonwoLonwo I added it locally and it worked, Could you assign me the issue? I can open a PR

**Comment by LonwoLonwo** [comment]
You can create a PR without an assignment.

**Comment by brunodmartins** [comment]
PR opened @LonwoLonwo
