### ISSUE TITLE
DBeaver - Custom Jdbc

### ISSUE THREAD

**Issue by rmoneam** [dbeaver/dbeaver#21761]
### Description

- I'm working on create a custom jdcb driver which connecting to a java application not database direct to return some data and represent it using dbeaver. 
- I need to ask if there is any document or steps to clone and start dbeaver local on my machine to debug on it while creating my custom jdbc ?

### DBeaver Version

Community Edition 23.2.4

**Comment by E1izabeth** [comment]
Maybe you're looking for https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse or https://github.com/dbeaver/dbeaver/wiki/Develop-in-IDEA

**Comment by rmoneam** [comment]
@E1izabeth it dose not build successfully 

![image](https://github.com/dbeaver/dbeaver/assets/115641847/78199f98-5ea2-4023-8155-0957de044afb)

**Comment by E1izabeth** [comment]
What are the errors?

**Comment by arhayka** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
