### ISSUE TITLE
SSH Tunneling not works if ssh has cloudflare based authentication

### ISSUE THREAD

**Issue by SuriyaJin** [dbeaver/dbeaver#21777]
### Description

When I use ssh host which has cloudflare based authentication ssh tunnel is failing. Can you fix this?

### DBeaver Version

23.2.4

### Operating System

ubuntu 22.04

### Database and driver

Postgres and version 13

### Steps to reproduce

Enable cloudflare based ssh tunneling on remote db.
try to connect the database with ssh tunneling option.

**Comment by LonwoLonwo** [comment]
Hello @SuriyaJin 

> ssh tunnel is failing.

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
