### ISSUE TITLE
Identifiers with special characters are not escaped

### ISSUE THREAD

**Issue by alumni** [dbeaver/dbeaver#21779]
### Description

I have a table with some special characters (e.g. `Ĕ` and `Ʋ`). I am not able to work at all with it (not able to view the data or to delete it). It seems that all queries that DBeaver generates do not escape the table name.

### DBeaver Version

23.2.4

### Operating System

any

### Database and driver

1. SAP HANA Cloud 2023.4.35
2. com.sap.db.jdbc.Driver 2.18.13

### Additional context

If I right click on the table and choose Delete, the following SQL query is executed:
```sql
DROP TABLE MY_SCHEMA.Y105ĔC4Ʋ6FBCAA03;
```

This is incorrect SQL, since the identifier contains special characters which need escaping. The correct query would be:
```sql
DROP TABLE MY_SCHEMA."Y105ĔC4Ʋ6FBCAA03";
```

**Comment by LonwoLonwo** [comment]
Hello @alumni 

Thanks for the report.
