### ISSUE TITLE
23.2.4 "Advanced Copy as HTML" also copies HTML Character Entities such nbsp;

### ISSUE THREAD

**Issue by sk280** [dbeaver/dbeaver#21770]
### Description

The latest version (v 23.2.4 CE as of this writing) copies HTML character entites such as nbsp in the column values.

The previous version 23.2.3 CE did NOT have this issue.	

### DBeaver Version

Community Edition 23.2.4

### Operating System

Windows 10

### Database and driver

PostgresQL 14
PostgreSQL standard driver (postgres-jdbc)

### Steps to reproduce

1. Connect to a database and execute a query with any text column that has spaces in the column values.
2. Execute query and on the results grid -> right click -> click on Advanced Copy -> Copy as HTML
3. Open a new Excel workbook (blank) or Notepad
4. Paste from Clipboard. Check if the column value copied has &nbsp instead of space.

**Comment by Destrolaric** [comment]
@sk280 Hi, '&nbsp' allows us to show query and column formatting properly. It is a special HTML value used to show that space should be displayed at the current position.

**Comment by sk280** [comment]
> @sk280 Hi, '&nbsp' allows us to show query and column formatting properly. It is a special HTML value used to show that space should be displayed at the current position. 

Hi there,

This is a bug in the current version. The character enhancements inside the columns should not appear when the HTML content is rendered


The previous version did not have this issue. I've included steps to reproduce. You can also test it in the previous version.

This is a bug in the latest version.

**Comment by saan-saeteurn** [comment]
> > @sk280 Hi, '&nbsp' allows us to show query and column formatting properly. It is a special HTML value used to show that space should be displayed at the current position.
> 
> Hi there,
> 
> This is a bug in the current version. The character enhancements inside the columns should not appear when the HTML content is rendered
> 
> The previous version did not have this issue. I've included steps to reproduce. You can also test it in the previous version.
> 
> This is a bug in the latest version.

+1 for opening this issue.  

I have been using this feature in previous version and pasted the result of 'Copy as HTML' into MS Word with the markups rendered beautifully.  This latest version introduces the HTML entities such as '&nbsp' for a space and not rendered upon pasting the result from clipboard has been difficult to use and get around.  Meaning I have go through and delete every instance of '&nbsp' and replace with an empty space either manually or with find and replace.  This works perfectly in previous version so I hope it this gets addressed in the next update.  Thank you for working on this.

**Comment by saan-saeteurn** [comment]
Sorry, I am still confused why this issue was closed.  The pull request or fix isn't tackling the problem brought by this issue that was originally opened.  The problem still persist in the latest released version.

**Comment by ShadelessFox** [comment]
Hello @saan-saeteurn,

The fix will be available in version 23.3.0, which will be released next Monday.

You can download the early access version that includes the fix here: https://dbeaver.io/files/ea/

**Comment by saan-saeteurn** [comment]
> Hello @saan-saeteurn,
> 
> The fix will be available in version 23.3.0, which will be released next Monday.
> 
> You can download the early access version that includes the fix here: https://dbeaver.io/files/ea/

Ahh, got it!  Thank you for the clarification.  My apologies.  --Saan
