### ISSUE TITLE
unable to connect to redshift

### ISSUE THREAD

**Issue by prangyakar** [dbeaver/dbeaver#21784]
### Description

Connection Timeout

### DBeaver Version

Community Edition 23.2.1

### Operating System

Windows 11 Pro

### Database and driver

AWS->redshift

### Steps to reproduce

Provided redshift host,port,dbname same as other laptop.

see connection timeout

### Additional context

no ssh

**Comment by LonwoLonwo** [comment]
Hello @prangyakar 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. 
And clear steps to reproduce.
Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
