### ISSUE TITLE
cannot modify primary index or drop it

### ISSUE THREAD

**Issue by sirber** [dbeaver/dbeaver#2178]
there's no way to add or remove column from index.
if I drop it, I get SQL errors.

db: mariadb 10.x

I can do those operations in HeidySQL whitout issues.

**Comment by serge-rider** [comment]
If you need to change primary key then you need to edit it in "Constraints" tab. 
Primary key's index can't be modified.

**Comment by sirber** [comment]
Also, an index cannod be modified to be unique or not
