### ISSUE TITLE
Refreshing table changes sort order

### ISSUE THREAD

**Issue by rlaferla** [dbeaver/dbeaver#21785]
### Description

Pressing "Refresh" button (twice) toggles sort order.

### DBeaver Version

Community Edition Version 23.2.4.202311051706

### Operating System

macOS Sonoma 14.0 (23A344)

### Database and driver

 PostgreSQL 15.3 (Debian 15.3-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

### Steps to reproduce

1.  Initial state
<img width="550" alt="image" src="https://github.com/dbeaver/dbeaver/assets/1135694/a47a239d-28e5-4bee-9df1-4322ab017401">

2.  Press "Refresh" button twice.

3.  Sort order changed
<img width="589" alt="image" src="https://github.com/dbeaver/dbeaver/assets/1135694/cb757754-905b-4739-9003-cee6830e2e86">

**Comment by ShadelessFox** [comment]
Hello @rlaferla,

I can see that your rows have different values between screenshots. I suspect that the row with id '3' was updated between refreshes, so the database moved it to the very end.

PostgreSQL doesn't sort columns by primary keys. You need to set ordering explicitly:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/1f8ffe13-1be9-40b2-9a14-6993fa1e7462)

Please let me know if it solves your issue.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by rlaferla** [comment]
I can understand a feature as being not planned but this is a bug.

**Comment by E1izabeth** [comment]
@rlaferla could you clarify if the proposed solution helps you https://github.com/dbeaver/dbeaver/issues/21785#issuecomment-1803864369? If not, please explain why do you consider that it's a bug.
