### ISSUE TITLE
Grid/Record in portuguese is translated Grade/Gravar, when It would make more sense Grade/Registro or Grade/Ficha 

### ISSUE THREAD

**Issue by geraldodev** [dbeaver/dbeaver#21786]
Gravar in portugues is save, which appears to be a out of context translation of Record.

What one would want is Registro that leads to Record but not as Saving or even better (in my opinion) Ficha that points to a paper with data of a entity.

Regards,

Geraldo Lopes de Souza

**Comment by brunodmartins** [comment]
@E1izabeth @LonwoLonwo I want to help with this issue! 🇧🇷

**Comment by brunodmartins** [comment]
I detected another wrong translation: Cumprimento (shake hands) <> Comprimento (length)! I am also fixing it
