### ISSUE TITLE
Parameters replacement in queries without format

### ISSUE THREAD

**Issue by flequi** [dbeaver/dbeaver#21783]
### Description

Some complex queries without formatting (CTRL+SHIFT+F) doesn't replace parameters correctly and put the values in the middle of sentences.
If you format the query, this dissapears.
Some complex queries without formatting don't replace parameters correctly
ORIGINAL QUERY:
![image](https://github.com/dbeaver/dbeaver/assets/4034173/12d59ad2-e5dd-4d39-89b6-6934df89fef9)

PREVIEW EXECUTION QUERY
![image](https://github.com/dbeaver/dbeaver/assets/4034173/7f37d55e-a714-4446-9623-2b861162bb72)

### DBeaver Version

23.0.0

### Operating System

Windows 11

### Database and driver

Oracle
![image](https://github.com/dbeaver/dbeaver/assets/4034173/301f02f2-c69e-4bdc-ab95-c956d895f970)

![image](https://github.com/dbeaver/dbeaver/assets/4034173/19afe461-4d30-42a6-a490-5f29569ab4e5)

### Steps to reproduce

1. Write a complex query with parameters (**WITHOUT FORMAT SQL**)
2. Execute the query.
3. Write some values for parameters
4. View the preview query, there are values in the middle of the sentences

**Comment by E1izabeth** [comment]
Please try the latest DBeaver version (23.2.4 or 23.2.0 if you're using pro). We have fixed similar issue #18982 in 23.1.0

**Comment by flequi** [comment]
Thanks for the response, but with newer versions of DBeaver I've experienced problems to connect to the imported connections, with a Socket Timeout Error, that I don't understand, because the connection string its the same, and the hosts are the same too.

![image](https://github.com/dbeaver/dbeaver/assets/4034173/f5ac8d3f-518b-4a01-a2e8-704c70c19dd4)

I've revised the Proxy Settings of these new versions, but its the same configuration that mine.

**Comment by flequi** [comment]
The solution of change DBeaver doesn't works for me for the other problems:
https://github.com/dbeaver/dbeaver/issues/21793
