### ISSUE TITLE
Question / feature request : exec SQL files by a command line

### ISSUE THREAD

**Issue by yoletx** [dbeaver/dbeaver#2179]
In sql developper i can run script from sql files easily with simple command in sql editor : 
![image](https://user-images.githubusercontent.com/32055492/30596100-7bb3739c-9d53-11e7-8bee-b7b9e46d0cbd.png)
Is it possible to achieve it in Dbeaver ? or add this functionnality in the future ?

**Comment by mythcolor** [comment]
I have met the same problem.I think this feature is very important for us. Issue #4738, #5737 are the same as this. We are looking forward to this feature. Please fix this issue as soon as possible. Thanks!

**Comment by trajnisz** [comment]
There is a possibility but no multiple files and no command intended for that (from my quick research). I think this mechanism could be extended
![exec-script-dbeaver](https://user-images.githubusercontent.com/45018311/56562504-c2960200-65a9-11e9-83a5-e26ddc46187b.PNG)
