### ISSUE TITLE
Unable to update VARCHAR(n) character limit

### ISSUE THREAD

**Issue by jaketig** [dbeaver/dbeaver#21796]
### Description

Attempting to modify a character limit in the UI removes the character limit entirly instead of modifing it

### DBeaver Version

Community 23.2.4.202311051706

### Operating System

Windows 10

### Database and driver

PostgreSQL 15.4
PostgreSQL 15.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
PostgreSQL JDBC Driver 42.5.2

### Steps to reproduce

1.  Open a table properties window
2. Try to update an existing columns character limit (i.e from varchar(250) to varchar(500))
3. Save the changes 
4. Notice generated SQL is missing character limit all together

Generated:
```
ALTER TABLE public.addresses ALTER COLUMN packing_notes TYPE varchar USING packing_notes::varchar;
```

Expected:
```
ALTER TABLE public.addresses ALTER COLUMN packing_notes TYPE varchar(500) USING packing_notes::varchar;
```

**Comment by LonwoLonwo** [comment]
Thanks for the report @jaketig 

As I can see, it will not work for all PostgreSQL types with modifiers.
Broked here: https://github.com/dbeaver/dbeaver/issues/18409
