### ISSUE TITLE
Versions newer than 23.0 doesn't connect with my existing connections

### ISSUE THREAD

**Issue by flequi** [dbeaver/dbeaver#21793]
### Description

If I update my DBeaver 23.00 to newer versions, the same existing connections I've in the older DBeaver, doesn't connect with a Socket Timeout Error

### DBeaver Version

23.2

### Operating System

Windows 11

### Database and driver

Oracle 19
![image](https://github.com/dbeaver/dbeaver/assets/4034173/a48af319-48e0-4a30-a3bf-4cdf6cd35d86)
![image](https://github.com/dbeaver/dbeaver/assets/4034173/47fdf6a6-9f55-45a7-a06d-d83edfbccc27)

### Steps to reproduce

Update new DBeaver version.
Start new DBeaver.
Try to connect with existing connections.
Error of SocketTimeout:
![image](https://github.com/dbeaver/dbeaver/assets/4034173/2150863d-9d31-4ecf-b8af-9550e8af22f1)
Close new DBeaver
Open older DBeavear (23.00)
Try to connect --> SUCCESS

**Comment by ShadelessFox** [comment]
Hello @flequi,

Could you please check if your connections work with an older version of DBeaver?

I suspect that your database is not accessible anymore.

**Comment by flequi** [comment]
Hello.
I have 2 Dbeavers installed. One Dbeaver 23.00 that runs perfectly and other DBeaver 23.2 that with the same connections doen't works.
I have 12 connections, Do you tellme that the 12 databases are not accesible anymore? It's a possibility, like a great meteor crashes with the Earth and all the databases of the world are not accesible anymore.

**Comment by flequi** [comment]
Now seriously, I think it has to be some change that has relation with the connections or VPNs connections, since it gives an error when trying to connect to Databases with a two-node cluster and a balancer, and the Socket Timeout means that it hasn't connectivity with the Hosts.
I Repeat that, if I close the newer DBeaver and I open the older DBeaver, it Works fin, with the same VPN and the same Connections. I've tried with 3 or 4 newer versions of DBeaver and all of them have the same problem.
Thanks

**Comment by ShadelessFox** [comment]
Okay.

What do your connections consist of, just Oracle databases?

Can you provide log files? You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by flequi** [comment]
Yes the important connections are only Oracle 19. I have another connection with MySQL DB and it works fine, but the databases 
of work are the 14 other Oracle connections.

Maybe the problem was to reuse a workspace of older DBeaver version???

I attach the two log files:
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/13299647/dbeaver-debug.log)
[File.log](https://github.com/dbeaver/dbeaver/files/13299656/File.log)

**Comment by ShadelessFox** [comment]
Thanks. I don't see anything suspicious, so can't really understand what's wrong.

Can you please ensure that your connection configuration is correct, including the role?

**Comment by flequi** [comment]
Yes, I have tried to rewrite the pass and the user, but the connections are the same because when I download a new ZIP of DBeaver and I open it, the connections appears automatically, I don't write new connections, are the same of the older DBeaver.
¿Maybe problems with the Window Firewall? ¿Java Version? ¿OracleClient Home version?
The problem its with ALL of my 14 Oracle connections, but no with the MySql other one.

**Comment by ShadelessFox** [comment]
I don't think there's something with your environment, as your connections still work against an oldest version of DBeaver.

**Comment by E1izabeth** [comment]
Could you try creating a one new connection to see if the new connection works? It'll help us understand if the issue is in saved connection configuration compatibility.

**Comment by flequi** [comment]
I have tested ALL of my connections and 2 Oracle connections works fine. I've tested connection to hosts of the queryString and the connections that works have a Balancer Host that I can make ping, the other connections that fails have Balancer Host with the ping restricted. I've writed all the HOSTS with IP in mi hosts file of Windows but it doesn't work. 

I RESOLVED THE PROBLEM MAKING THE VALUES OF THE CONNECTIONS SETTINGS LIKE THIS AND REFRESHED ALL THE CONNECTIONS
![image](https://github.com/dbeaver/dbeaver/assets/4034173/bbd366df-c18f-457e-82e3-43319752c911)

**Comment by serge-rider** [comment]
Thank you for the information!

These are the default settings (except close/invalidate timeouts which are unrelated).
But small connect timeout may cause issues during connection.

Could you say what pref values were before your fix?

**Comment by flequi** [comment]
I can't view the old values, because if I open another DBeaver version 23.2.2 it takes the same global configuration like others, but I think that the old values are this:
![image](https://github.com/dbeaver/dbeaver/assets/4034173/e22b4529-260f-4df8-aabd-8c5aed6287ea)
