### ISSUE TITLE
Unable to Capitalize Column Names

### ISSUE THREAD

**Issue by kevinfusmithrx** [dbeaver/dbeaver#21797]
### Description

SELECT random_column as "Random Column"
FROM table

The output table will have a column called "random column".
How do I get DBeaver to persist the capitalization? Thanks.

### DBeaver Version

Dbeaver Community 23.1.4

**Comment by E1izabeth** [comment]
What database do you use?

**Comment by E1izabeth** [comment]
I couldn't reproduced the issue against SQLite and PostgreSQL

**Comment by kevinfusmithrx** [comment]
@E1izabeth Amazon Redshift

**Comment by ShadelessFox** [comment]
Hello @kevinfusmithrx,

Sorry for the long wait.

It's a default behavior in Redshift. To force identifiers to be case-sensitive, you can use the following statement:

```sql
SET enable_case_sensitive_identifier TO true;
```

You can either alter your user and set this parameter:

```sql
ALTER USER your-user SET enable_case_sensitive_identifier TO true;
```

Or use bootstrap queries in DBeaver and use the statement provided above:
1. Open connection configuration
2. Go to **Connection settings** &rArr; **Initialization** &rArr; **Bootstrap queries**

Please let me know if it helps.

**Comment by kevinfusmithrx** [comment]
No worries!
So where would i put that statement? Just before the select statement, like this, and then run my query as usual?

```
SET enable_case_sensitive_identifier TO true;
SELECT random_column as "Random Column"
FROM table;
```

**Comment by ShadelessFox** [comment]
Yes, before any other queries. I believe the issue is resolved, so I will close the ticket.
