### ISSUE TITLE
Discord or Zulip

### ISSUE THREAD

**Issue by BrettKnoss** [dbeaver/dbeaver#21809]
It would be nice to have a discord or zulip account to discuss minor issues.

**Comment by LonwoLonwo** [comment]
Hello @BrettKnoss 

You can find many places to contact with us here: https://dbeaver.com/company/contact/

Also, you can create tickets with your questions in [Discussions](https://github.com/dbeaver/dbeaver/discussions).
We are trying to give our answers there as well.

**Comment by E1izabeth** [comment]
I'm closing this issue as a duplicate of #20609

You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.
