### ISSUE TITLE
Grid Infinity represetation bug

### ISSUE THREAD

**Issue by mkgrgis** [dbeaver/dbeaver#21805]
### Description

After `INSERT INTO ... (-9e999), (9e999) ... `.
`9e999` or other overflow number is SQLite representation of infinity.

![изображение](https://github.com/dbeaver/dbeaver/assets/41448637/94f52d9e-6439-4244-9efc-2eb297529495)

Also see https://github.com/dbeaver/dbeaver/issues/18974

### DBeaver Version

23.2.4

### Operating System

Linux

### Database and driver

SQLite, default driver

### Steps to reproduce

Open SQLite table with inserted `9e999` or -`9e999`.

**Comment by mkgrgis** [comment]
Not only SQLite, PostgreSQL and FireBird are also affected. Look like there is no expected `∞` sign now at all.

**Comment by mkgrgis** [comment]
`NaN` values also affected.

**Comment by uslss** [comment]
thanks for the report
