### ISSUE TITLE
CRITICAL Error: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

### ISSUE THREAD

**Issue by lubakka** [dbeaver/dbeaver#21816]
### Description

I am getting the following message from the application:

"(DBeaver:129718): Gtk-CRITICAL **: 11:57:43.023: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar"

### DBeaver Version

Community Edition 23.2.4.202311051706

### Operating System

Ubuntu 22.04.3 LTS

### Steps to reproduce

as soon as I open the app

**Comment by LonwoLonwo** [comment]
Hello @lubakka 
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by lubakka** [comment]
sorry but this is not recorded in the log file. It happens when I launch it from the console with following command

     /snap/bin/dbeaver-ce

And the following is recorded in the logs



!SESSION 2023-11-10 12:58:10.036 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -eclipse.keyring /home/lb/snap/dbeaver-ce/268/.local/share/DBeaverData/secure/secure_storage
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.ui 2 2 2023-11-10 12:58:12.367
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

**Comment by ShadelessFox** [comment]
I expect it to be an Eclipse issue.

**Comment by serjiokov** [comment]
@lubakka Could you answer, is issue critical for product use or just logged?

**Comment by flambchap** [comment]
This issue is caused by GTK's scrollbar overlay mode. You can disable it like so: https://github.com/dbeaver/dbeaver/wiki/Troubleshooting-system-issues#gtk-box-gadget-distribute-issue

**Comment by lubakka** [comment]
@n5a5 Thanks, that removed that error, but now it's showing another one :)



`(DBeaver:61425): Gtk-WARNING **: 10:36:43.740: Negative content width -8 (allocation 5, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)`



But it didn't fix the other problem I have either.

Quite often the UI graphics are also unresponsive, which leads to a lot of danger when working with a live data base. Because when the graph is stuck and you can delete some data accidentally. 

I'm not sure if these errors lead to where the DBeaver graph hangs. 

I think I can open another issue

**Comment by Destrolaric** [comment]
@lubakka Hi, sorry for the long wait. The GTK wwarning issue is unfortunately quite possibly is not the reason for freezes. Can you provide more info about the graph issues?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
