### ISSUE TITLE
unable to get the lock on file

### ISSUE THREAD

**Issue by BrettKnoss** [dbeaver/dbeaver#21810]
### Description

When i try to connect to my DuckDB database I get the folowing error:
'''
IO Error: Could not set lock on file "/Users/brettknossmac/Documents/Inventory/Cattle/CattleDB": Resource temporarily unavailable
'''

How do I update or change DuckDB to the latest version? I updated DBeaver recently.

### DBeaver Version

Community Version 23.2.3.202310221533

### Operating System

Ventura 13.3

**Comment by brunodmartins** [comment]
@BrettKnoss I made a little research and found out many [issues](https://duckduckgo.com/?q=DuckDB+exclusive+lock) on libraries and third party systems with the same log. Its seems that DuckDB has some configurations to perform an exclusive lock to it's access. Have you check if you have another connection to DuckDB that performs exclusive lock?

**Comment by LonwoLonwo** [comment]
Hello @BrettKnoss 

Please provide your driver version.
You can find it in your Connections Settings -> Driver Settings -> Libraries

**Comment by BrettKnoss** [comment]
@LonwoLonwo I can't find the Connection Settings menu

**Comment by BrettKnoss** [comment]
@brunodmartins that could be.  I've had issues between runnings of Pluto.jl, and Julia in general.  I've updated to  DuckDB.jl 0.9.0 which runs DuckDB 0.9.1 and I was hoping that the issue was that dbeaver had a driver for an older version of DuckDB, and updating would fix the issue.

**Comment by serjiokov** [comment]
@BrettKnoss Could you try the latest version of Dbeaver, seems it is fixed yet.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
