### ISSUE TITLE
DB2 - The first query is always very slow because of "discover resultset" backgroud tasks

### ISSUE THREAD

**Issue by proietti-francesco** [dbeaver/dbeaver#21818]
### Description

Each time I connect to a DB2 db, the first query takes a very long time. By clicking on background tasks tab I can see the client is doing "Discover resultset metadata" for every object of every schema existing in the DB, even if I'm performing a simple query on a single table.
This is very tedious as I have and use tens of DB2 connections.
 
As a workaround I unchecked the "Read table metadata" and "Read table references" options in the Data editor section of the connection settings. But if I do so I loose the feature of generate SQL statements from the resultset.

I'm wondering if the Discover resultset metadata could be done only on the objects involved in the query.
Thank you.

### DBeaver Version

Community Edition Version 23.2.4.202311051706

### Operating System

Windows 11

### Database and driver

Database Name and Version: DB2 LUW 11.5
Database Jdbc Driver: com.ibm.db2.jcc 11.5.7.0

### Steps to reproduce

1. make sure you have the "Read table metadata" option checked (which is the default) in the "Data editor" section of the connection settings
2. connect to a DB2 db with a thounsand tables
3. perform a simple query on a random user table (SELECT * FROM schema1.tab1)

**Comment by LonwoLonwo** [comment]
Hello @proietti-francesco 

Could you please do some tests with previous driver versions? Because the "Discover resultset metadata" part is going from the driver side.

![2023-11-13 10_23_42-Connection _SAMPLEDB_ configuration](https://github.com/dbeaver/dbeaver/assets/45152336/73731988-7ca4-4fc0-8224-1e308d874e69)

You can downgrade it this way.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
