### ISSUE TITLE
Can I submit SQL in batches when editing data?Similar to mysql when the insert SQL statement is insert...values (),(),();

### ISSUE THREAD

**Issue by huage0524** [dbeaver/dbeaver#21813]
Can I submit SQL in batches when editing data?Similar to mysql when the insert SQL statement is insert...values (),(),();

**Comment by LonwoLonwo** [comment]
Hello @huage0524 

Could you please provide more info about your request?
What is your case? What do you want to do?

**Comment by huage0524** [comment]
When I insert data like this, the data is multiple times insert into tb values ();insert into tab values(),(),();

**Comment by huage0524** [comment]
![Uploading t.png…]()

**Comment by huage0524** [comment]
![Uploading t.png…]()

**Comment by huage0524** [comment]
When I insert data like this, the data is multiple times insert into tb values ();insert into tab values(),(),();

**Comment by huage0524** [comment]
In the data edit box, paste the data directly.If data is inserted multiple times in the background of the database, can you insert batch data once?

**Comment by LonwoLonwo** [comment]
We are using batches for data inserting. On the JAVA level. 
And it is faster than one-row VALUES, yes.

Also, you can use multi-values insert in the data transfer (you can find more info in our documentation: https://github.com/dbeaver/dbeaver/wiki/Data-migration#step-5-data-load-settings)

And you can create and export SQL files with multiple-insert statements (https://github.com/dbeaver/dbeaver/wiki/Data-transfer#export-data)

**Comment by huage0524** [comment]
Ok. Thanks very much.
