### ISSUE TITLE
Add "Parquet" driver, similar to CSV

### ISSUE THREAD

**Issue by DeflateAwning** [dbeaver/dbeaver#21829]
**Is your feature request related to a problem? Please describe.**
I wish I could open a folder with multiple parqute tables in it.

**Describe the solution you'd like**
I want the UX to be the same as opening a CSV.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by LonwoLonwo** [comment]
Hello @DeflateAwning 

Thanks for the idea.

I see the previous request, but it was closed: https://github.com/dbeaver/dbeaver/issues/5821

**Comment by DeflateAwning** [comment]
I won't be closing this one randomly! Can I transfer the 20 votes from the previous issue?

**Comment by LonwoLonwo** [comment]
Nope, It doesn't work this way.
But ok, I will add a special label for this ticket. To attract attention.

**Comment by E1izabeth** [comment]
Another issue about Parquet #18393

**Comment by n5a5** [comment]
Thank you for the request. Closing as duplicate of https://github.com/dbeaver/dbeaver/issues/18393.

**Comment by DeflateAwning** [comment]
What is the PRO label?

This is not a duplicate of that other issue, also.

**Comment by E1izabeth** [comment]
Yes, it's not a duplicate.
PRO label means PRO products.

**Comment by DeflateAwning** [comment]
Does the PRO label mean it's already available in Pro? Or it means that it's planned to be integrated into pro?

**Comment by E1izabeth** [comment]
It's better to ask @n5a5 about that.
I could say that it's not implemented in any of our products yet.

**Comment by flambchap** [comment]
Yes, it's not a duplicate. I'm sorry; I wasn't cautious when comparing the tickets.

When it comes to adding the driver, no FOSS JDBC driver can 'connect' to Parquet files, similar to the driver we use for CSV connections, at least to my knowledge. This means we need to develop such a driver in-house, and we don't offer in-house drivers in the Community edition.

**Comment by DeflateAwning** [comment]
Moved the question over to here to get some insight on how much work it'd be: https://github.com/simoc/csvjdbc/issues/94

**Comment by flambchap** [comment]
I reopened https://github.com/dbeaver/dbeaver/issues/5821. The work will be tracked there.

**Comment by DeflateAwning** [comment]
One workaround, for anyone wondering, is to use an in-memory DuckDB database, and then do:

```sql
SELECT * FROM read_parquet('path_to_parquet');
```
