### ISSUE TITLE
[Window->Navigation->Next Tab] on last tab blocks tab navigation on dbeaver 4.2.1

### ISSUE THREAD

**Issue by cumanacr** [dbeaver/dbeaver#2182]
Hi I'm using dbeaver 4.2.1 on Linux

These lines have two purposes, to report a little tiny bug and ask for an enhancement.

1. bug: I changed user keys for __Previous Tab__ and __Next Tab__ when I travel to the last tab and press __Next Tab__ again, tab navigation is blocked, this isn't happening when I travel to the first tab and press __Previous Tab__ combination, to "unblock" it I have to click on the SQL Editor section.

2. enhancement: It would be nice if tab navigation were an infinite loop, I mean when the last tab is reached, it moves to the first tab and vice-versa, instead of the current behavior that when it reaches any of the ends it keeps there.

Keep up the good work dbeaver is awesome.

Regards

**Comment by serge-rider** [comment]
This is standard Eclipse platform behavior, I'm afraid I can't fix it (see Eclipse FR https://bugs.eclipse.org/bugs/show_bug.cgi?id=210311).

Workaround (poor) is to use <kbd>Ctrl+F6</kbd>/<kbd>Ctrl+Shift+F6</kbd> to traverse over opened editor tabs.

**Comment by cumanacr** [comment]
Well, that's a shame, but thanks for <kbd>Ctrl+F6</kbd>/<kbd>Ctrl+Shift+F6</kbd>, it lit a light.

I also remapped those shortcuts and now when I stuck in the last tab I use the __Previous Editor__ shortcut and it send me to the first tab and the __Next Editor__ shortcut sends me to the previous one.

I changed __SQL Editor__ and __New SQL Editor__ too and I feel like I using a mix between a text editor and a browser.

With <kbd>Alt</kbd> + <kbd>direction</kbd> I can now move between queries and SQL editors, when I stuck in the last tab <kbd>Shift+Alt+Right</kbd> sends me to the first tab.

When I need a new sql editor I'm using <kbd>Ctrl+T</kbd> or to reopen any <kbd>Shift+Ctrl+T</kbd>

I'm pretty happy thank you very much.

If somebody is interested in the actual key bindings they're here:
![selection-03-2017-09-24](https://user-images.githubusercontent.com/6874136/30787760-bd5577a2-a14d-11e7-8202-04d3c7ff9f18.png)

**Comment by tati-kru** [comment]
It looks like this issue was solved. So it will be closed. If you have any additional questions, please write a comment.
