### ISSUE TITLE
MySql :  Compare / Migrate --> Simple Structure Compare not showing Expected output

### ISSUE THREAD

**Issue by crystaldeveloper2017** [dbeaver/dbeaver#21834]
### Description

The Simple Structure Compare Feature does not show the column datatype difference if there is any.
In the Below Shown Example, both the columns have different datatypes but the same is not shown in the compare results.

### DBeaver Version

22.3.4.202302060909

### Operating System

Windows 10 

### Steps to reproduce

Reproducible Steps:

1. Create a table with below query:
```
CREATE TABLE `employee` (
  `employee_id` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

2. Create Another Table with below query:
```
CREATE TABLE `employee2` (
  `employee_id` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

3. From the Database Navigator, Select these two created tables and click on 
Compare / Migrate --> Simple Structure Compare

![image](https://github.com/dbeaver/dbeaver/assets/99576310/d85e7a75-441e-4d08-9117-7e2637a56d90)

### Additional context

Mysql Version : MySQL 8.0.35-0ubuntu0.22.04.1
Dbeaver Version: 22.3.4.202302060909

**Comment by Matvey16** [comment]
I don't think it's a bug, that happens when you check an option to ignore properties. Would it happen if you uncheck this option?
![image](https://github.com/dbeaver/dbeaver/assets/82543000/cc4be916-a231-41da-a941-20f549d08fb3)

**Comment by crystaldeveloper2017** [comment]
@Matvey16 
Sorry My bad. Did not realize that option was checked. 
Works as expected with that option unchecked.
