### ISSUE TITLE
Add `ORDER BY RANDOM()` support to CSV driver system

### ISSUE THREAD

**Issue by DeflateAwning** [dbeaver/dbeaver#21831]
1. View a CSV table.
2. Go to the blue "Customize filters..." button and click
3. In the raw `ORDER BY` field, enter `RANDOM()`. 
4. Click ok.
5. Be sad that it errors.

**Comment by E1izabeth** [comment]
It works for me for PostgreSQL 12 this way
![image](https://github.com/dbeaver/dbeaver/assets/28875055/2085bbd1-fa4c-49b9-9603-628f0cb8759e)

What database are you using? What error do you see?

**Comment by DeflateAwning** [comment]
Per the title of the Issue, this is using the CSV database driver. I agree that it works in Postgres. This is a requested upgrade to the CSV driver.

**Comment by E1izabeth** [comment]
Oh yeah, I see. Thank you for pointing out.

**Comment by E1izabeth** [comment]
I'm afraid there is nothing to upgrade as we already use the latest driver version by default.
Could you give any link to the place where you find that it should work?

**Comment by DeflateAwning** [comment]
I mean that the request is to modify the driver (thus upgrading it). Where is the CSV Driver codebase? I assumed (perhaps incorrectly) that it was in this repo.

**Comment by E1izabeth** [comment]
It's here https://github.com/simoc/csvjdbc

**Comment by DeflateAwning** [comment]
Opened this issue in the proper repo. Thanks.

**Comment by DeflateAwning** [comment]
Just for sake of completeness, these changes are included in Csvjdbc version 1.0.42 (which is pulled into DBeaver automatically). This issue is now fully solved.

**Comment by E1izabeth** [comment]
@DeflateAwning thank you
