### ISSUE TITLE
Building on Mac - A Java Runtime Environment (JRE) or Java Development Kit (JDK) must be available in order to run Dbeaver. 

### ISSUE THREAD

**Issue by rmoff** [dbeaver/dbeaver#21841]
### Description

I followed the instructions in [the wiki](https://github.com/dbeaver/dbeaver/wiki/Build-from-sources) to build Dbeaver on my Mac M1. 
When I came to run it from `product/community/target/products/org.jkiss.dbeaver.core.product/macosx/cocoa/aarch64/DBeaver.app` it failed to load, with the error

```
A Java Runtime Environment (JRE) or Java Development Kit (JDK) must be available in order to run Dbeaver.

No Java virtual machine was found after searching the following locations: 
../Eclipse/jre/Contents/Home/bin/java
```

![CleanShot 2023-11-13 at 16 27 29](https://github.com/dbeaver/dbeaver/assets/3671582/9b103bb8-4052-49b0-8a95-55a79bb29859)

---

After some digging around I found that it worked if I edited `Info.plist` to include an entry as part of the `Eclipse` array: 

```
      <string>-vm</string>
      <string>/Users/rmoff/.sdkman/candidates/java/17.0.5-tem/bin</string>
```

By default the value is `../Eclipse/jre/Contents/Home/bin/java` - but in the built package this jre doesn't exist

```
❯ cd aarch64/DBeaver.app/Contents/
❯ ls -l Eclipse
total 176
-rw-r--r--@   1 rmoff  staff  78137 13 Nov 13:07 artifacts.xml
drwxr-xr-x@  11 rmoff  staff    352 13 Nov 16:13 configuration
-rw-r--r--@   1 rmoff  staff   1483 13 Nov 13:07 dbeaver.ini
drwxr-xr-x@  20 rmoff  staff    640 13 Nov 13:07 features
drwxr-xr-x@  11 rmoff  staff    352 13 Nov 13:07 licenses
drwxr-xr-x@   5 rmoff  staff    160 13 Nov 13:07 p2
drwxr-xr-x@ 314 rmoff  staff  10048 13 Nov 13:07 plugins
-rw-r--r--@   1 rmoff  staff   1811 13 Nov 13:06 readme.txt
```

---

Perhaps this could be added as a note on the build wiki to help others? Or LMK if I'm building it wrong :) 

### DBeaver Version

Community Edition Version 23.2.5.202311131258

### Operating System

macOS Sonoma 14.0 (23A344)

**Comment by flambchap** [comment]
Hi. I suspect you have Java on your system available. You can try deleting the lines

```
-vm
../Eclipse/jre/Contents/Home/bin/java
```

from `DBeaver.app/Contents/Eclipse/dbeaver.ini` file.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
