### ISSUE TITLE
New postgres connection is not picking the right database when connecting by "host" 

### ISSUE THREAD

**Issue by rpgdev** [dbeaver/dbeaver#21848]
### Description

When I add a new connection to a postgres database and I "connect by" host it doesn't pick the database name from the database textbox in the add new connection dialog. The URI section doesn't get grayed out which is weird, I'm unable to edit it but it's not grayed out and in the end the database name that gets picked for the connection comes from the URI instead of the database textbox. What makes this hard to debug is that it still shows the database name from the database textbox in the UI but dbeaver is silently connected to the default "postgres" database. 

### DBeaver Version

Version 23.2.3.202310221533

### Operating System

Fedora Linux 38

### Database and driver

PostgreSQL JDBC Driver 42.2.20
PostgreSQL 14.7 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit

### Steps to reproduce

1. Set up a pg server with a default database "postgres" and another one that can be named anything, add clearly identifiable objects to the latter (several schemas for example).
2. Add a new connection
3. Set "connect by" host
4. Add the connection parameters to the second DB name in database entry
5. Verify that dbeaver connects to the default database regardless, in my case the "default" for the driver which seems to be "postgres".

**Comment by serjiokov** [comment]
@rpgdev Could you provide footage for reproducibility please?

**Comment by rpgdev** [comment]
@serjiokov I will try.

**Comment by MashaKorax** [comment]
@rpgdev Have you any updates?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
