### ISSUE TITLE
SSL connectionconfiguration confusing/not working

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#21854]
### Description

I am trying to create a certficate-only connection to a Postgres 15 DB.
Playing around with a piece of code and the JDBC string I finally figured out it had to look lile

`jdbc:postgresql://myhostname:5432/mydb?ssl=true&sslmode=verify-full&sslrootcert=/tmpmcacert.crt&sslcert=/tmp/myclient.crt`

(Those are PEM certificates). With Java/Spingboot that works.

Now, trying to replicate that in DBeaver is the real challenge:
open "Connection Settings"
a) first stop would be the the aptly named tab "SSL" -- but no matter what I configure there nothing works
b) next tab "Driver properties" -- same game, whatever I configure has no efefct
c) finally I just go back to "Main", switch "Connect by" from "Host" to "URL" and jsut inster the JDBC string shown above.

Looking at `dbeaver-debug.log` _ONLY_ in case c) does the JDBC string actually contain anything except host, port and db name!
So, obviously neither tab "SSL" nor "Driver properties" are used at all -- none of the things configured there ever appear in the JDBC string.

### DBeaver Version

Version 23.2.4.202311051706

### Operating System

Linux, Debian/Sid

### Database and driver

1. Database name and version: PostgreSQL 15.0
2. Driver name and version: PostgreSQL JDBC Driver 42.2.25

**Comment by LonwoLonwo** [comment]
Hello @2019-05-10 

Let's discuss this from the first step.

> but no matter what I configure there nothing works

Could you please provide the log files or your connection error? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by ged-yuko** [comment]
@2019-05-10
Just a small clarification: the connection string you are observing in the log is perfectly fine, when the connection options specified using specific configuration dialog fields. When the logged connection string doesn't have these options it doesn't mean they weren't passed to the connection driver. There is another mechanism called connection properties used by DBeaver, you can observe it being used [here](https://github.com/dbeaver/dbeaver/blob/93728e6c86a1362fdbddd2a445e9499ffa3c89d5/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreDataSource.java#L355), [here](https://github.com/dbeaver/dbeaver/blob/93728e6c86a1362fdbddd2a445e9499ffa3c89d5/plugins/org.jkiss.dbeaver.model.jdbc/src/org/jkiss/dbeaver/model/impl/jdbc/JDBCDataSource.java#L214) and finally [here](https://github.com/dbeaver/dbeaver/blob/93728e6c86a1362fdbddd2a445e9499ffa3c89d5/plugins/org.jkiss.dbeaver.model.jdbc/src/org/jkiss/dbeaver/model/impl/jdbc/JDBCConnectionOpener.java#L109). Note that the _url_ (which represents the connection string) and the _connectProps_ (which represents all the extra connection options) - are a separate objects. 

I can think about SSH settings missing the root certificate option, which you are using with connection string, but the question is - what was really happening besides the details you paid attention to? Here the real log file and error message comes first.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
