### ISSUE TITLE
ADD COLUMN routine generates inefficient code

### ISSUE THREAD

**Issue by JTMosaic** [dbeaver/dbeaver#21860]
DBeaver 23.2.4.202311051706
Mysql 5 / MariaDB 11

When using the GUI to add a column to a table and moving the column _before_ saving the change, inefficient code utilizing an ADD and a CHANGE is generated:

`
ALTER TABLE APP_OPS.t_instance_list ADD NewColumn varchar(100) NULL;
ALTER TABLE APP_OPS.t_instance_list CHANGE NewColumn NewColumn varchar(100) NULL AFTER nginx;
`

Instead, the two above statements should be combined into one:

`ALTER TABLE APP_OPS.t_instance_list ADD NewColumn varchar(100) NULL AFTER nginx;`

The only alternative now is to add the columns in the GUI, open the change code in the editor and manually make this adjustment

**Comment by LonwoLonwo** [comment]
Hello @JTMosaic 

Thanks for the idea. I will add it to this ticket: https://github.com/dbeaver/dbeaver/issues/18501
