### ISSUE TITLE
The script opened after version update from 23.2.2 to 23.2.4 or 23.2.3 displays garbled Chinese characters

### ISSUE THREAD

**Issue by zigzodiac** [dbeaver/dbeaver#21873]
### Description

The script opened after version update from 23.2.2 to 23.2.4 or 23.2.3 displays garbled Chinese characters
And version 23.2 shows normal

### DBeaver Version

commutity 23.2.3 or 23.2.4

### Operating System

windows 11

**Comment by zigzodiac** [comment]
![QQ图片20231123141851](https://github.com/dbeaver/dbeaver/assets/31992421/efb316e4-24e8-438d-954f-5e096b3422f5)
23.2.5

**Comment by LonwoLonwo** [comment]
Hello @zigzodiac 

Could you please find the .ini file (located with the .exe file), delete this parameter
`-Dfile.encoding=UTF-8`
save the file and restart DBeaver?

**Comment by zigzodiac** [comment]
@LonwoLonwo ok
