### ISSUE TITLE
General Error with Athena

### ISSUE THREAD

**Issue by Svensko** [dbeaver/dbeaver#21877]
### Description

Since the upgrade, there seems to be an issue retrieving data from AWS Athena. 
My queries, that work in Alteryx, are underlined in red by DBeaver, which reports "SQL Error [S1000]: General Error" o execution. Even simple SELECT * FROM's don't work, so I think the syntax isn't the problem.

Interestingly, I can still connect to the databases and retrieve metadata (columns, data types, etc). However, when I right-click the table in the Database Navigator and click on "View Data", I get the same error again.

### DBeaver Version

Community - 22.2.4.202211061524

### Operating System

Windows 10 64bit

### Database and driver

Simba Athena JDBC/ODBC driver (Configured in ODBC Connection Manager, both 32 and 64bit). Alteryx can use this connection to run these same queries.

### Steps to reproduce

1. Connect to database.
2. Run SELECT-statement or run "View Data" on a table from the right-click menu, in the Database Navigator.
3. Receive error.

### Additional context

No other configurations specifically set.

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by Svensko** [comment]
Of course, these are the error details from *.log:


!ENTRY org.eclipse.ui 2 2 2023-11-16 14:57:17.230
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-11-16 14:57:23.051
!MESSAGE Error determining server version
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-11-16 14:57:23.051
!MESSAGE UnsupportedOperationException
!STACK 0
java.lang.UnsupportedOperationException
	at sun.jdbc.odbc.JdbcOdbcDatabaseMetaData.getDatabaseMajorVersion(JdbcOdbcDatabaseMetaData.java:4030)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getDatabaseMajorVersion(JDBCDatabaseMetaDataImpl.java:140)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.readDatabaseServerVersion(JDBCDataSource.java:478)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:450)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:488)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1117)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:990)
	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:226)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:134)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-11-16 14:57:45.646
!MESSAGE SQL Error [S1000]: General error
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-11-16 14:57:45.647
!MESSAGE SQL Error [S1000]: General error
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-11-16 14:57:45.647
!MESSAGE General error
!STACK 0
java.sql.SQLException: General error
	at sun.jdbc.odbc.JdbcOdbc.createSQLException(JdbcOdbc.java:6993)
	at sun.jdbc.odbc.JdbcOdbc.standardError(JdbcOdbc.java:7121)
	at sun.jdbc.odbc.JdbcOdbc.SQLExecDirect(JdbcOdbc.java:3117)
	at sun.jdbc.odbc.JdbcOdbcStatement.execute(JdbcOdbcStatement.java:337)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:186)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4982)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-11-16 14:57:49.579
!MESSAGE SQL Error [S1000]: General error
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-11-16 14:57:49.579
!MESSAGE SQL Error [S1000]: General error
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-11-16 14:57:49.579
!MESSAGE General error
!STACK 0
java.sql.SQLException: General error
	at sun.jdbc.odbc.JdbcOdbc.createSQLException(JdbcOdbc.java:6993)
	at sun.jdbc.odbc.JdbcOdbc.standardError(JdbcOdbc.java:7121)
	at sun.jdbc.odbc.JdbcOdbc.SQLExecDirect(JdbcOdbc.java:3117)
	at sun.jdbc.odbc.JdbcOdbcStatement.execute(JdbcOdbcStatement.java:337)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:578)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:487)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:494)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:913)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3726)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4982)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

And from the dbeaver-debug.log

> 2023-11-16 14:57:13.292 - DBeaver 22.2.4.202211061524 is starting
> 2023-11-16 14:57:13.292 - OS: Windows 10 10.0 (amd64)
> 2023-11-16 14:57:13.293 - Java version: 11.0.12 by Eclipse Foundation (64bit)
> 2023-11-16 14:57:13.293 - Install path: 'C:\DBeaver\dbeaver'
> 2023-11-16 14:57:13.293 - Instance path: 'file:/C:/Users/skottks/AppData/Roaming/DBeaverData/workspace6/'
> 2023-11-16 14:57:13.293 - Memory available 64Mb/1024Mb
> 2023-11-16 14:57:13.306 - Create display
> 2023-11-16 14:57:13.413 - Initializing DBeaver 22.2.4
> 2023-11-16 14:57:13.415 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 22.2.4.202211061524
> 2023-11-16 14:57:13.417 - Initialize desktop platform...
> 2023-11-16 14:57:13.549 - BounceCastle bundle found. Use JCE provider BC
> > Start Core File Systems [org.eclipse.core.filesystem 1.9.500.v20220817-1539]
> > Start Core Resource Management [org.eclipse.core.resources 3.18.0.v20220828-0546]
> > Start Team Support Core [org.eclipse.team.core 3.9.500.v20220817-1539]
> > Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.93.202211061524]
> 2023-11-16 14:57:13.807 - Initialize base platform...
> > Start Expression Language [org.eclipse.core.expressions 3.8.200.v20220613-1047]
> 2023-11-16 14:57:13.818 - Platform initialized (401ms)
> > Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.93.202211061524]
> 2023-11-16 14:57:13.826 - Starting RMI server at 32948
> 2023-11-16 14:57:14.171 - Run workbench
> > Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.600.v20220607-1204]
> > Start Eclipse Application Services [org.eclipse.e4.core.services 2.3.300.v20220613-1047]
> > Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.5.0.v20210115-1333]
> > Start Eclipse e4 Progress View [org.eclipse.e4.ui.progress 0.3.500.v20220717-1456]
> > Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.17.0.v20220817-1334]
> > Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.13.100.v20220310-1056]
> > Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.400.v20211102-0453]
> > Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.600.v20220715-1400]
> > Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.100.v20210722-1426]
> > Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.17.200.v20220613-1008]
> > Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.600.v20220621-1327]
> > Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.108.202211061524]
> 2023-11-16 14:57:15.709 - Configure workbench window
> > Start Help System Core [org.eclipse.help 3.9.100.v20210721-0601]
> 2023-11-16 14:57:15.807 - Create actions
> 2023-11-16 14:57:15.813 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
> 2023-11-16 14:57:15.814 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
> 2023-11-16 14:57:15.815 - Disable Eclipse action set 'org.eclipse.ui.actionSet.openFiles'
> 2023-11-16 14:57:16.249 - Initialize workbench window
> 2023-11-16 14:57:16.256 - Finish initialization
> > Start Default Text Editor [org.eclipse.ui.editors 3.14.400.v20220730-1844]
> > Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.16.600.v20220809-1658]
> > Start Search Support [org.eclipse.search 3.14.200.v20220817-1340]
> > Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.93.202211061524]
> > Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.1000.v20220801-1135]
> > Start Internet Connection Management UI [org.eclipse.ui.net 1.4.100.v20220812-1406]
> > Start Internet Connection Management [org.eclipse.core.net 1.4.0.v20220813-1037]
> > Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.83.202211061524]
> 2023-11-16 14:57:17.458 - Total database drivers: 101 (101)
> > Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.130.202211061524]
> > Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.99.202211061524]
> > Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.93.202211061524]
> > Start Draw2d [org.eclipse.draw2dl 3.12.100.20221014131737]
> > Start GEF3 GEF (MVC) [org.eclipse.gef3 3.12.100.20221014131737]
> > Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.53.202211061524]
> > Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.53.202211061524]
> 2023-11-16 14:57:17.817 - Connect with 'AWS_GLSD_COP' (odbc-18b055f7fdd-be9ccb2ca7e8a15)
> > Start DBeaver Generic Plug-in [org.jkiss.dbeaver.ext.generic 2.3.179.202211061524]
> 2023-11-16 14:57:17.868 - Execution context opened (AWS_GLSD_COP; Main; 0)
> 2023-11-16 14:57:20.497 - Execution context opened (AWS_GLSD_COP; Metadata; 1)
> > Start Core Compare Support [org.eclipse.compare.core 3.7.100.v20220812-1406]
> > Start Console [org.eclipse.ui.console 3.11.300.v20220811-1921]
> > Start Debug Core [org.eclipse.debug.core 3.20.0.v20220811-0741]
> 2023-11-16 14:57:22.976 - Connect with 'AWS_CT' (odbc-18b05583b5c-685a9713fa63516f)
> 2023-11-16 14:57:22.980 - Execution context opened (AWS_CT; Main; 2)
> 2023-11-16 14:57:23.048 - Error determining server version
> java.lang.UnsupportedOperationException
> 	at sun.jdbc.odbc.JdbcOdbcDatabaseMetaData.getDatabaseMajorVersion(JdbcOdbcDatabaseMetaData.java:4030)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getDatabaseMajorVersion(JDBCDatabaseMetaDataImpl.java:140)
> 	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.readDatabaseServerVersion(JDBCDataSource.java:478)
> 	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:450)
> 	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:488)
> 	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1117)
> 	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:990)
> 	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:226)
> 	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:134)
> 	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
> 	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
> 	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> 2023-11-16 14:57:23.068 - Can't get column 'TYPE_NAME': [Microsoft][ODBC Driver Manager] Invalid string or buffer length
> 2023-11-16 14:57:23.070 - Can't get column 'TABLE_CAT': Column not found
> 2023-11-16 14:57:23.077 - Connected (odbc-18b055f7fdd-be9ccb2ca7e8a15, JDBC-ODBC Bridge (Simba Athena ODBC Driver) [2.0001 (1.1.18.1001)])
> 2023-11-16 14:57:24.087 - Error reading schemas in catalog 'AwsDataCatalog' - UnsupportedOperationException - null
> 2023-11-16 14:57:28.715 - Execution context opened (AWS_GLSD_COP; SQLEditor <Script-4.sql>; 3)
> 2023-11-16 14:57:30.415 - Can't get column 'TABLE_SCHEM': Column not found
> 2023-11-16 14:57:30.416 - Can't get column 'TABLE_CATALOG': Column not found
> 2023-11-16 14:57:30.988 - Execution context opened (AWS_GLSD_COP; SQLEditor <Script-4.sql>; 4)
> 2023-11-16 14:57:36.067 - Execution context opened (AWS_GLSD_COP; SQLEditor <Script-4.sql>; 5)
> 2023-11-16 14:57:37.631 - Can't get column 'TABLE_TYPE': [Microsoft][ODBC Driver Manager] Invalid string or buffer length
> 2023-11-16 14:57:37.634 - Execution context opened (AWS_GLSD_COP; SQLEditor <Script-4.sql>; 6)
> > Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> 2023-11-16 14:57:39.554 - Execution context opened (AWS_GLSD_COP; SQLEditor <Script-4.sql>; 7)
> 2023-11-16 14:57:40.369 - Execution context opened (AWS_GLSD_COP; SQLEditor <Script-4.sql>; 8)
> 2023-11-16 14:57:42.915 - Execution context opened (AWS_CT; Metadata; 9)
> 2023-11-16 14:57:44.754 - Can't get column 'SOURCE_DATA_TYPE': Column not found
> 2023-11-16 14:57:44.754 - Can't get column 'COLUMN_SIZE': Column not found
> 2023-11-16 14:57:44.756 - Can't get column 'DECIMAL_DIGITS': Column not found
> 2023-11-16 14:57:44.757 - Can't get column 'NUM_PREC_RADIX': Column not found
> 2023-11-16 14:57:44.758 - Can't get column 'ORDINAL_POSITION': Column not found
> 2023-11-16 14:57:44.758 - Can't get column 'IS_AUTOINCREMENT': Column not found
> 2023-11-16 14:57:44.759 - Can't get column 'IS_GENERATEDCOLUMN': Column not found
> 2023-11-16 14:57:44.782 - Can't get column 'COLUMN_DEF': [Microsoft][ODBC Driver Manager] Invalid string or buffer length
> 2023-11-16 14:57:45.539 - Catalog/schema switch is disabled for legacy drivers
> 2023-11-16 14:57:45.540 - Catalog change is disabled for legacy drivers
> 2023-11-16 14:57:45.643 - SQL Error [S1000]: General error
> org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [S1000]: General error
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
> 	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:186)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4982)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> Caused by: java.sql.SQLException: General error
> 	at sun.jdbc.odbc.JdbcOdbc.createSQLException(JdbcOdbc.java:6993)
> 	at sun.jdbc.odbc.JdbcOdbc.standardError(JdbcOdbc.java:7121)
> 	at sun.jdbc.odbc.JdbcOdbc.SQLExecDirect(JdbcOdbc.java:3117)
> 	at sun.jdbc.odbc.JdbcOdbcStatement.execute(JdbcOdbcStatement.java:337)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
> 	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
> 	... 7 more
> 2023-11-16 14:57:49.576 - SQL Error [S1000]: General error
> org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [S1000]: General error
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:578)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:487)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:494)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:913)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3726)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4982)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> Caused by: java.sql.SQLException: General error
> 	at sun.jdbc.odbc.JdbcOdbc.createSQLException(JdbcOdbc.java:6993)
> 	at sun.jdbc.odbc.JdbcOdbc.standardError(JdbcOdbc.java:7121)
> 	at sun.jdbc.odbc.JdbcOdbc.SQLExecDirect(JdbcOdbc.java:3117)
> 	at sun.jdbc.odbc.JdbcOdbcStatement.execute(JdbcOdbcStatement.java:337)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
> 	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
> 	... 12 more
> > Start Log View [org.eclipse.ui.views.log 1.3.300.v20220717-1456]
> 2023-11-16 14:58:05.285 - Error determining server version
> java.lang.UnsupportedOperationException
> 	at sun.jdbc.odbc.JdbcOdbcDatabaseMetaData.getDatabaseMajorVersion(JdbcOdbcDatabaseMetaData.java:4030)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getDatabaseMajorVersion(JDBCDatabaseMetaDataImpl.java:140)
> 	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.readDatabaseServerVersion(JDBCDataSource.java:478)
> 	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:450)
> 	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:488)
> 	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1117)
> 	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:990)
> 	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> 2023-11-16 14:58:05.293 - Can't get column 'TABLE_CAT': Column not found
> 2023-11-16 14:58:05.294 - Connected (odbc-18b05583b5c-685a9713fa63516f, JDBC-ODBC Bridge (Simba Athena ODBC Driver) [2.0001 (1.1.18.1001)])
> 2023-11-16 14:58:05.317 - Execution context opened (AWS_CT; SQLEditor <Script-5.sql>; 10)
> 2023-11-16 14:58:07.786 - Catalog/schema switch is disabled for legacy drivers
> 2023-11-16 14:58:07.787 - Catalog change is disabled for legacy drivers
> 2023-11-16 14:58:27.377 - Catalog/schema switch is disabled for legacy drivers
> 2023-11-16 14:58:27.377 - Catalog change is disabled for legacy drivers
> 2023-11-16 14:58:27.380 - Duplicate object name 'DATE' in cache GenericDataTypeCache. Last value: "date"
> 2023-11-16 14:58:27.380 - Duplicate object name 'TIMESTAMP' in cache GenericDataTypeCache. Last value: "timestamp"
> 2023-11-16 14:58:27.380 - Duplicate object name 'CHAR' in cache GenericDataTypeCache. Last value: char
> 2023-11-16 14:58:27.385 - Duplicate object name 'VARCHAR' in cache GenericDataTypeCache. Last value: "varchar"
> 2023-11-16 14:58:27.385 - Duplicate object name 'STRING' in cache GenericDataTypeCache. Last value: string
> 2023-11-16 14:58:27.385 - Duplicate object name 'ARRAY' in cache GenericDataTypeCache. Last value: "array"
> 2023-11-16 14:58:27.385 - Duplicate object name 'MAP' in cache GenericDataTypeCache. Last value: "map"
> 2023-11-16 14:58:27.385 - Duplicate object name 'STRUCT' in cache GenericDataTypeCache. Last value: struct
> 2023-11-16 14:58:29.899 - Catalog/schema switch is disabled for legacy drivers
> 2023-11-16 14:58:29.899 - Catalog change is disabled for legacy drivers
> 2023-11-16 14:58:32.463 - Catalog/schema switch is disabled for legacy drivers
> 2023-11-16 14:58:32.463 - Catalog change is disabled for legacy drivers
> 2023-11-16 14:58:35.029 - Catalog/schema switch is disabled for legacy drivers
> 2023-11-16 14:58:35.029 - Catalog change is disabled for legacy drivers
> 2023-11-16 14:58:37.614 - Catalog/schema switch is disabled for legacy drivers
> 2023-11-16 14:58:37.614 - Catalog change is disabled for legacy drivers
>

**Comment by ShadelessFox** [comment]
Hello @Svensko,

It appears that you're using an old ODBC driver that is no longer being maintained.

Have you tried using our new ODBC driver? It is available in all PRO products.

For more information, please refer to https://github.com/dbeaver/dbeaver/wiki/ODBC-JDBC-Driver

**Comment by Svensko** [comment]
Hi ShadelessFox,

Thanks for your super quick reply!
The connection was indeed set up a while ago - so I'm going to update my drivers and try again in the morning. 

If it all works out, I'll update and close this issue.

**Comment by arhayka** [comment]
Hi @Svensko, 
Did you get a chance to try the new ODBC driver?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
