### ISSUE TITLE
Athena v3 'Generate SQL -> DDL' errors, whilst 'SHOW CREATE TABLE' succeeds

### ISSUE THREAD

**Issue by jtray23** [dbeaver/dbeaver#21871]
### Description

This might be a configuration issue on my part (or a JDBC issue?), but I couldn't figure it out after a few hours of tinkering, so I wanted to start working on a pull request to fix whatever is wrong here, because it's nice to have DDL generation here in DBeaver UI instead of needing to go to the AWS UI, or typing out "SHOW CREATE TABLE" in DBeaver.

Assuming it's not a config/driver issue on my side, someone may already know a quick fix. If not, I might have time to debug later and build a PR.

<img width="445" alt="Screenshot 2023-11-10 at 1 31 09 PM" src="https://github.com/dbeaver/dbeaver/assets/43098197/9e05e51e-320d-4428-a869-0c8e9da05939">
<img width="532" alt="Screenshot 2023-11-10 at 1 32 15 PM" src="https://github.com/dbeaver/dbeaver/assets/43098197/035ef22b-5d38-47de-8f7f-a5ac4ce24576">
<img width="529" alt="Screenshot 2023-11-16 at 10 04 08 AM" src="https://github.com/dbeaver/dbeaver/assets/43098197/5e360326-bc5d-4f51-865e-fc516bb8c88f">
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/13381359/dbeaver-debug.log)

### DBeaver Version

Community Edition 23.3.1

### Operating System

macOS Sonoma 14.1.1

### Database and driver

I tried the DBeaver auto-fetched drivers: 
(can't remember which version it was now, but it's the ".1000" driver that DBeaver auto-fetches - I can go write the version if needed)

After that failed, I deleted the above driver, then tried again with the latest AWS official Athena drivers from:
https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html
Specifically, this download:
https://downloads.athena.us-east-1.amazonaws.com/drivers/JDBC/SimbaAthenaJDBC-2.1.1.1000/AthenaJDBC42-2.1.1.1000.jar

### Steps to reproduce

1. Connect DBeaver to an AWS Athena workgroup running v3 (Trino) using the fetched .1000 drivers or the AWS provided .1000 drivers
2. Open your Data Catalog then find an External Table defined in any Schema/Database
3. Right-click the External Table -> Generate SQL -> DDL

### Additional context

I remember reverting to our v2 (Presto) workgroup, but got the same error, so probably not Athena v2 / v3 dependent, but I can test that out if needed.

**Comment by LonwoLonwo** [comment]
Hello @jtray23 

Still, it is unclear - what is happening after the third step in your case?
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by jtray23** [comment]
Thank you for taking a look at this, @LonwoLonwo 

Sorry, I should have taken a screenshot of directly what happens on Step 3 (Generate DDL) instead of the Details (new screenshot attached above to reflect the direct error message).

I have also attached the debug log file (above) which shows the full stack trace. I was trying to set some time aside this week to get my dev env up to test and build a PR, but it's a bit tricky since I do everything in Python these days and haven't touched Java/Eclipse since high school.

**Comment by LonwoLonwo** [comment]
Could you please provide a log one more time? Loading didn't finish, as I can see.

**Comment by jtray23** [comment]
@LonwoLonwo Actually, the log file loading did finish (the error / stack trace was the last thing in the log file), and to demonstrate that it did finish, I have ran "Generate DDL" multiple times in a row so you can see the error happening multiple times in a row on this new log file:

<img width="1195" alt="Screenshot 2023-11-17 at 1 37 08 PM" src="https://github.com/dbeaver/dbeaver/assets/43098197/0a6fc4b5-694a-400a-bdd8-84e8b2b506e8">

As you can see (above), the last line in my previous log file "...Worker.run(Worker.java:63)" is the same here, and then the next error / stack trace begins. I attached the new log file with multiple stack traces, but its all the same as the previous log file I provided, so it probably won't help beyond what the first log file already contained:

[dbeaver-debug-friday.log](https://github.com/dbeaver/dbeaver/files/13397741/dbeaver-debug-friday.log)

Hopefully I will have time to try and debug it this weekend and build a PR.

**Comment by LonwoLonwo** [comment]
DBeaver supports Athena with this driver:
https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.34.1000/AthenaJDBC42-2.0.34.1000.jar

Could you please try to check your DDL with it? Because I can't reproduce your issue with the old previous version.

![2023-11-28 11_42_42-DBeaver Ultimate 23 3 0 - cloudfront_logs](https://github.com/dbeaver/dbeaver/assets/45152336/dcd90624-89a4-4591-bb68-da619ee09df7)

**Comment by jtray23** [comment]
@LonwoLonwo interesting find! I had originally used those version 2.0.34.1000 drivers via DBeaver auto-fetch (I found it in my recycle bin folder just now to confirm it was that version) and got the same error on the DDL Generation. 

Unfortunately, this is starting to point in a direction I had searched and found initially on Google (but didn't want to believe it since the error message was not the same in DBeaver):

https://repost.aws/questions/QUXN-vPmu0RmW-SDCUf-ULdw/athena-generate-create-table-ddl-call-results-in-a-java-exception

(My hunch:  We may have doomed JDBC support for usage with our schema by naming it with a hyphen "-" character included. Just a hunch, but if you're not seeing the error on your DBeaver with that same version of JDBC drivers, then it might be related to this issue above.)

**Comment by jtray23** [comment]
@LonwoLonwo I finally had some time to confirm my above findings and, unfortunately, the link to the article seems to fit my problem:

Just like the behavior you saw on the 2.0.34.1000 drivers, I also get successful Generate DDLs in DBeaver UI on schema/database names without hyphens:

![Screen Shot 2023-12-23 at 12 58 51 PM](https://github.com/dbeaver/dbeaver/assets/43098197/91576429-677f-4586-9ea3-f9774ffc8206)

But, if I recreate that same testing Iceberg table above using a schema/database name with a hyphen in it:

![Screen Shot 2023-12-23 at 12 59 19 PM](https://github.com/dbeaver/dbeaver/assets/43098197/3325e27d-fb18-4d29-978a-bbcd6f0137a3)

Then the error happens when trying to generate DDL on that with a single hyphen added to the schema name:

![Screen Shot 2023-12-23 at 12 52 11 PM](https://github.com/dbeaver/dbeaver/assets/43098197/0b9ee51d-8e01-4416-8225-c6fa7f2323f6)

I'm not sure if JDBC is necessarily to blame, though, because the Athena UI's handling of this is just as inconsistent (as hinted by the AWS help article I found):
![Screen Shot 2023-12-23 at 1 15 10 PM](https://github.com/dbeaver/dbeaver/assets/43098197/c8d8f696-6a47-4b2c-91a9-54445ebe6284)
![Screen Shot 2023-12-23 at 1 16 32 PM](https://github.com/dbeaver/dbeaver/assets/43098197/9489b77a-cbf7-4961-ab72-733e1fd1fa65)

But, if you use backticks, then the SHOW CREATE TABLE works:

![Screen Shot 2023-12-23 at 1 19 20 PM](https://github.com/dbeaver/dbeaver/assets/43098197/97d34f87-9d72-4868-afa2-18e3afd2ea19)

But, just because the backticks are the only way to get it working for SHOW CREATE TABLE, doesn't mean it will work on INSERTS:

![Screen Shot 2023-12-23 at 12 50 43 PM](https://github.com/dbeaver/dbeaver/assets/43098197/4c754126-bb8e-4796-a23b-281376ab4708)

So, the only way I can see to workaround this issue is for DBeaver to always use backtick / backquote for SHOW CREATE TABLE schema/database name and table/view name when the "Generate DDL" function is used in DBeaver UI. Right now, the error message in DBeaver is matching the Athena UI error message when double quotes or no quotes are used on SHOW CREATE TABLE, indicating that DBeaver is using either of these non-working methods (double quotes or no quotes) when submitting the SHOW CREATE TABLE to Athena, but should be using backtick \ backquote behind the scenes.

**Comment by jtray23** [comment]
One small addendum to my previous findings above:

There is a third non-working method, which seems to be the one DBeaver is using (backtick the whole schemaordb.tableorview as one):

![Screen Shot 2023-12-23 at 1 47 53 PM](https://github.com/dbeaver/dbeaver/assets/43098197/aa013acc-d287-4bef-808b-d3b7ad75fc4b)

There remains only one working method out of the four available (backtick  schemaordb, then a period, then backtick tableorview):

![Screen Shot 2023-12-23 at 1 47 06 PM](https://github.com/dbeaver/dbeaver/assets/43098197/f9334447-7619-49b3-88a2-9451cb1065a5)

**Comment by jtray23** [comment]
@LonwoLonwo @serjiokov I had some more time to brainstorm what could be a minimally invasive way to just address this quirk in Athena on a single line of code, without changing any plumbing in the `GenericMetaModel` or anywhere else, but I'm not sure if this approach is a non-starter (either on some technical grounding I have overlooked, or personal/style preference of your dev team):

https://github.com/jtray23/dbeaver/commit/049993a88cb5276b2f251067d465d8e5132c890c

But, assuming the idea is on the right track, and that the "Generate DDL" feature in DBeaver UI calls `sourceObject.getFullyQualifiedName()`, and returns the non-quoted version, then changing the above line in the commit with one of the following variations would successfully work around this Athena quirk, as such:

![Screen Shot 2023-12-24 at 2 01 56 PM](https://github.com/dbeaver/dbeaver/assets/43098197/bbac8d0c-b279-42ca-9638-6ec6f947d35c)

Or, if the Generate DDL button in the UI calls `sourceObject.getFullyQualifiedName()` and returns the double-quoted version:

![Screen Shot 2023-12-24 at 2 33 45 PM](https://github.com/dbeaver/dbeaver/assets/43098197/b51afcb8-5879-4da5-8ee6-1ae9014b6f7c)

Or, if the Generate DDL button in the UI calls `sourceObject.getFullyQualifiedName()` and returns the wholly-backticked (which I'm fairly certain it does not due to the error message verbiage no longer matching here, as it does match between Athena UI vs. DBeaver UI for the above double-quoted and non-quoted cases):

![Screen Shot 2023-12-24 at 2 35 12 PM](https://github.com/dbeaver/dbeaver/assets/43098197/3c3967de-7767-4d7b-81e8-413f76e5edcc)

**Comment by jtray23** [comment]
@LonwoLonwo @serjiokov Thank you for getting this fixed as of version 23.3.3!

I didn't see anything in the release notes addressing this, nor did I get any updates here about it being fixes, but it must have been addressed via another issue. Closing this as I have not hit the issue again on 23.3.3

**Comment by LonwoLonwo** [comment]
Hello @jtray23 

We didn't fix anything Athena-specific. So, please report if the issue will return.

**Comment by jtray23** [comment]
@LonwoLonwo Understood, it must have been an improvement y'all made in one of the base classes that handles general SQL, because the issue is gone on all the schemas that had this issue before version 23.3.3.

However, you are correct, because I did see the same error on another schema that started with a number, but this is technically a different issue, so I don't think this needs to be re-opened, and it's on an ancient schema we rarely use anymore, so for the most past, this issue is "resolved" for me. 

The amount of people using DBeaver, with Athena, with schemas that start with a number (instead of a letter), must be incredibly small, so I don't believe even worth opening a new issue for "schema support for Athena schemas that start with a number."

Thanks for DBeaver, and thank you, and your team, for all the time y'all put into making DBeaver.
