### ISSUE TITLE
Adding columns with comments to Oracle tables ignores comment 

### ISSUE THREAD

**Issue by NitemareReal** [dbeaver/dbeaver#21875]
### Description

When adding a new column with a comment to an Oracle table, you can see comment in "columns" grid but when saving changes, no "COMMENT ON COLUMN..." sentence is generated after "ALTER TABLE x ADD y;" only "ALTER TABLE x ADD y;" sentence, so, comment is lost.

### DBeaver Version

Community Edition 23.2.4.202311051706

### Operating System

Windows 10 x64

### Database and driver

Driver name and version: com.oracle.database.jdbcojdbc8:RELEASE [12.2.0.1]
Database name and version: Oracle 19.0.0.0.0

### Steps to reproduce

1. Open any Oracle table
2. Go to "Properties" tab, "Columns" section
3. Press "Alt + Ins" (or right click on grid and select "Create New Column")
4. Enter anything in "Comment" section
5. Press "Ok".
6. In grid, you can see comment in "Comment" column (unhide "Comment" column if not visible)
7. Press "Save..." button (Ctrl + S) to preview changes.
8. You can see that ONLY "ALTER TABLE" sentence is generated.
9. If you press "Persist", column is added but comment is lost.
10. After persisted, if you edit "Comment" cell for any column in grid, add any comment and press "Save..." button, you can see "COMMENT ON COLUMN..." sentence in preview view.
11. If you press "Persist", comment is added.

**Comment by LonwoLonwo** [comment]
Hello @NitemareReal 

Thanks for the report
