### ISSUE TITLE
Consultation on solutions to ：the server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]

### ISSUE THREAD

**Issue by shan1110** [dbeaver/dbeaver#21887]
**Is your feature request related to a problem? Please describe.**
Hello developers, I would like to ask a question about: the server selected protocol version TLS10 is not accepted by client preferences. [TLS13, TLS12] The solution to this problem.

Regarding my above problems, I find that most of the claims are to change java.security, so I am very curious about how you solve this problem, I am looking for solutions through source code or lssues.

But this is a little difficult for me as a developer who has been in the development industry for one or two years. I look forward to getting your answers, thank you

**Describe the solution you'd like**
how is dbeaver solved

**Describe alternatives you've considered**
change java.security file

**Additional context**

**Comment by Destrolaric** [comment]
@shan1110 DBeaver adds TLS10 protocol in included Java `java.security` file
