### ISSUE TITLE
Keyboard Short Cut Not Working: New Sql Script Ctrl + ] and Ctrl + F3 

### ISSUE THREAD

**Issue by mattpiskorz** [dbeaver/dbeaver#21899]
### Description

Problem:
I am not able to open a new sql script using the key binding Ctrl + ] or Ctrl +F3.

Reproduction:
On windows:
1.  Menu
5. Windows
6. Preferences
7. User Interface 
8. Keys
9. Search for "New Sql Script"

Work around:
1. Select a database
2. Right click on the database
3. Select "Sql Editor"
4. select "New Sql Script" 

User Interface / Keys:
![image](https://github.com/dbeaver/dbeaver/assets/8050753/993bcae5-0e41-4195-baca-c52e1c57b182)

No short cut listed on the db:
![image](https://github.com/dbeaver/dbeaver/assets/8050753/dc4e55d1-6cd4-4943-a351-8c92e935f6a1)

### DBeaver Version

Community Edition 23.2.5

### Operating System

Windows

### Database and driver

Postgres  12

### Steps to reproduce

Click on a database
Press Ctrl + ] or Ctrl + F3.
No new sql script appears.

### Additional context

Thank you for a great tool.

This was working until a recent update.  Might be a change on purpose, but would prefer to have the previous workflow back.

**Comment by E1izabeth** [comment]
I can't reproduce it.
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by mattpiskorz** [comment]
I am not able to provide the full log.

I closed dbeaver, and re-opened it.

This is the latest entry on the log:
!SESSION 2023-11-21 21:58:59.793 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring D:\Users\mpiskorz\AppData\Roaming\DBeaverData\secure\secure_stor
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.ui 4 4 2023-11-21 21:59:06.099
!MESSAGE Plug-in 'org.eclipse.ui.ide' contributed an invalid Menu Extension (Path: 'navigate/goTo' is i

!ENTRY org.eclipse.ui 2 2 2023-11-21 21:59:07.535
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclieferencePage)

![image](https://github.com/dbeaver/dbeaver/assets/8050753/1685dd29-196d-47e6-ac6d-92696dec632b)

**Comment by E1izabeth** [comment]
Unfortunately, these messages has nothing to do with your issue

**Comment by mattpiskorz** [comment]
Thank you for taking a look at the ticket.  

I will continue to dig on my end and see if I can identify what is going on.

Closing due to not be able to reproduce the scenario.

**Comment by mattpiskorz** [comment]
I have found the error of my ways...

I had changed to the resource view from the dbeaver view.  Ctrl + ] does not work in the resource view.

![image](https://github.com/dbeaver/dbeaver/assets/8050753/02a1a97e-f3ee-4218-9edd-ab0221c8b895)
