### ISSUE TITLE
Error occurred during SQL Server CTE expression execution after upgrading to version 23.2.5.202311191730

### ISSUE THREAD

**Issue by passacaglia** [dbeaver/dbeaver#21898]
### Description

After upgrading to version 23.2.5 (Community Edition), an error 'Must declare the scalar variable "@VAR_NAME"' occurs when trying to execute the following CTE expression.

![image](https://github.com/dbeaver/dbeaver/assets/1525402/6d813782-790c-4467-ba48-777b1962a372)

I have tried solution mentioned in issue #15543 , doesn't work.

```
IF OBJECT_ID('tempdb..#TempTb') IS NOT NULL DROP TABLE #TempTb

CREATE TABLE #TempTb (Idx INT IDENTITY, Content NVARCHAR(200) NULL, BizTime DATETIME NULL )

INSERT INTO #TempTb(Content, BizTime)
SELECT N'A', N'2023-11-01'
UNION ALL
SELECT N'B', N'2023-11-02'
UNION ALL
SELECT N'C', N'2023-11-03'
UNION ALL
SELECT N'D', N'2023-11-04'
UNION ALL
SELECT N'E', N'2023-11-05'

DECLARE @BizTime DATETIME = N'2023-11-03'

-- Error occurs
; WITH C AS (
    SELECT *
    FROM #TempTb
    WHERE BizTime > @BizTime )
SELECT * FROM C


-- Works fine
-- SELECT * FROM #TempTb WHERE BizTime > @BizTime


``` 

### DBeaver Version

Community Edition Version 23.2.5.202311191730

### Operating System

Windows 11 

### Database and driver

Database : SQL Server 2016
Driver : Microsoft JDBC Driver for SQL Server 9.2.0

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by krstan4o** [comment]
I confirm same issue:

declare @offerId int = 132;
select @offerId;

**Comment by E1izabeth** [comment]
I reproduced the issue

**Comment by hada14ab** [comment]
Hi E1izabeth, when will a new DBeaver version which fixes the declaration bug be released?

**Comment by E1izabeth** [comment]
@hada14ab 
We're working on it. Hopefully, in the next release.

**Comment by hada14ab** [comment]
Hi E1izabeth , when are you planning to release?
