### ISSUE TITLE
Export to excel fails " Processor 'stream.xlsx' not found in 'Files' "

### ISSUE THREAD

**Issue by datajunkiejanet** [dbeaver/dbeaver#21893]
### Description

When attempting to export to excel, I receive the error:

Error loading data transfer configuration
Reason:
Processor 'stream.xlsx' not found in 'Files'

[Stack Trace Log Export Error.docx](https://github.com/dbeaver/dbeaver/files/13394750/Stack.Trace.Log.Export.Error.docx)

### DBeaver Version

Community Version 23.2.4.202311051706

### Operating System

Windows 11

### Database and driver

Oracle
Oracle JDBC driver 12.2.0.1.0

### Steps to reproduce

1. I connect to my database ABS1
2. I run a simple query: SELECT BU.Code from BUSINESSUNIT bu
3. I try to export to excel
4. I immediately get the error

It doesn't matter how simple or complex the query is - it happens with every query
[Stack Trace Log Export Error.docx](https://github.com/dbeaver/dbeaver/files/13394894/Stack.Trace.Log.Export.Error.docx)

### Additional context

This problem only occurred after I had run a query with 300,000 rows and I stupidly clicked the Fetch All Data button. After 20 minutes, I clicked Cancel.  Ever since, I've been unable to export.

I tried uninstalling and reinstalling, but the problem persisted. FWIW, the uninstalled version was lower than the current version that I reinstalled, in case that makes a difference.  

I should add that I also have a machine that runs the PRO version, and it works fine. I searched on that computer for a 'stream.xlsx' file (in hopes of copying it and pasting it) but there wasn't one.

**Comment by ShadelessFox** [comment]
Hello @datajunkiejanet,

The office extension must be installed separately. I suspect you simply don't have it installed (it's not migrated between installs)

Please refer to the following article: https://github.com/dbeaver/dbeaver/wiki/Optional-extensions#office-integration

Let me know if it helps.

**Comment by datajunkiejanet** [comment]
Once I got the extension installed, it works again. Thanks!

**Comment by ShadelessFox** [comment]
You're welcome! As the issue is resolved, I'll close the ticket.
