### ISSUE TITLE
Snowflake numeric columns always show as number(38) in explorer

### ISSUE THREAD

**Issue by DavidfNZ** [dbeaver/dbeaver#21896]
### Description

In the Dbeaver Community edition database navigator, numeric columns always show as NUMBER(38), regardless of their actual datatype (screenshot attached). Other datatypes seem to be correct.

![Dbeaver snowflake issue](https://github.com/dbeaver/dbeaver/assets/107281913/99b56615-d896-431e-9e43-ac4d68c06129)

### DBeaver Version

Community Edition 23.2.5

### Operating System

Windows 10

### Database and driver

Snowflake, using snowflake-jdbc-3.14.3.jar

### Steps to reproduce

Connect to snowflake. Browse any Snowflake table with a numeric column that is NOT number(38), and it shows in Dbeaver as number(38).

**Comment by LonwoLonwo** [comment]
Thanks for the report @DavidfNZ
