### ISSUE TITLE
Don't display server ouput msg after execute plpgsql blocks

### ISSUE THREAD

**Issue by M3e92** [dbeaver/dbeaver#21902]
### Description

Example:
![image](https://github.com/dbeaver/dbeaver/assets/151517985/1bfcc712-6c6a-47b2-9670-a30fd0ae4cd0)

![image](https://github.com/dbeaver/dbeaver/assets/151517985/c8a45ba0-2623-444e-8351-319b5225f6ac)

### DBeaver Version

 23.2.5.202311191730

### Operating System

Windows 7

### Database and driver

Postgres Pro 15.4

**Comment by E1izabeth** [comment]
I can't reproduce the issue.
Are all turned on here?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/e24d1b16-0c39-4d13-90a2-916557acc9a0)

**Comment by M3e92** [comment]
Yes
![image](https://github.com/dbeaver/dbeaver/assets/151517985/6965dd6d-fafb-426c-98a3-d50309ea1e2f)

**Comment by M3e92** [comment]
This effect appeared after the update 23.2.5.202311191730

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by M3e92** [comment]
[log.ZIP](https://github.com/dbeaver/dbeaver/files/13422947/log.ZIP)

**Comment by E1izabeth** [comment]
Thanks

**Comment by EmirLogas** [comment]
After the last update, Output is not filling for me either.
Urgent update required.

**Comment by EmirLogas** [comment]
I need to get output from the script for an important update, but I can't get it. Are there any plans for an update?

**Comment by E1izabeth** [comment]
You can rollback to the previous version while it's not fixed. We're working on it.

**Comment by EmirLogas** [comment]
How can I rollback? Will the registered databases and my settings remain when I download the old version as setup again?

**Comment by E1izabeth** [comment]
Yes, you can just download an older version and install. Your configuration won't be lost.
https://dbeaver.io/files/

**Comment by Jagrab3** [comment]
One more information. In postgres, when you add pg_sleep for about second, after raise info, output dispays messages.
It looks like there is lack of sync with server messages.
do
$$
begin
	raise info 'test1';
	perform pg_sleep(0.5);
	raise info 'test2';
end;
$$

Result is:
test1

**Comment by M3e92** [comment]
Make test latest Early Acces version, bug fixed. Thanks.
