### ISSUE TITLE
Calling stored procedures with output parameters

### ISSUE THREAD

**Issue by joelsolon** [dbeaver/dbeaver#2190]
I have a stored procedure that itself returns a value, as well as returning values for the 3rd and 4th arguments. DBeaver seems to understand this:

<img width="590" alt="screen shot 2017-09-20 at 1 55 38 pm" src="https://user-images.githubusercontent.com/12203701/30659394-a762ae0a-9e0b-11e7-8bef-e32abb4e0b75.png">

But when I try to call the stored procedure it doesn't recognize the difference between input arguments and return/output parameters. This doesn't work:
? = FCE_Operations.ATM_GetAmountOutAndFee(100,0.5,?,?)

Instead, DBeaver asks me to supply values for the 3 ?'s and I get java.lang.NullPointerException.

**Comment by serge-rider** [comment]
What is your database?
Could you post full SQL snippet (table DDL + SQL)?

(bug with NullPointerException will be fixed in the next version).

**Comment by joelsolon** [comment]
I am connecting to the Caché database using its JDBC driver. Everything works great: SELECT, DML, calling procedures, ER diagrams. The only thing that doesn't work is stored procedure return values, either as the return value of the procedure itself, or as OUT or INOUT parameters. So the snippet above is the only snippet that there is. I'm trying to execute this:
? = FCE_Operations.ATM_GetAmountOutAndFee(100,0.5,?,?)

FCE_Operations is not a table; it's a container for stored procedures only.

**Comment by serge-rider** [comment]
You could try this:
1. Disable anonymous parameters (Preferences->General->Editors->SQL Editor->SQL Processing). Thus DBeaver won't ask you to enter parameter value for every question mark.
2. Execute query as `CALL FCE_Operations.ATM_GetAmountOutAndFee(100,0.5,?,?)`

Unfortunately I can't test this because there is no Caché  server in our test environment.

**Comment by joelsolon** [comment]
Thanks for the suggestion. Changing that preference and running as you suggested still doesn't work. I don't have to enter parameter values for the ?, but I get "Not all parameters bound/registered."

I'd like to try to separate this issue from any particular database. Can you write a simple stored procedure using any DB in your environment that takes two integers and returns their sum and difference, plus an extra string, and run that? The sql would looks something like this:
`select (:op1 + :op2), (:op1 - :op2), 'fred' into :sum, :diff, :extra`
op1 and op2 are the first 2 IN arguments. sum and diff are OUT arguments, and extra is the stored procedure's returned value. I want to call it like this:
`? = Test.SumDiff(4, 5, ?, ?)`
or this:
`:a = Test.SumDiff(4, 5, :b, :c)`

There should be a way for DBeaver to display the 3rd and 4th arguments and the return value of the procedure that are returned from the DB. This is not mission-critical for me, by the way. I've just seen this ability in other products.

**Comment by joelsolon** [comment]
@tati-kru @serge-rider: Is it possible that this issue is not getting attention because it is still marked "can't reproduce"? Do you have MS SQL Server or Sybase so that you can recreate this behavior, using the example from my previous post?

**Comment by serge-rider** [comment]
Sorry, mostly it is not getting attention because of huge amount of new tickets. 
However this one sounds reasonable for next releases. Moving to 5.1.5

**Comment by serge-rider** [comment]
I can't make it work in SQL Server Management Studio (it doesn't return output params). 
Syntax { call ... } is supported only by jTDS driver, native MSSQL driver doesn't understand it.

Anyhow, this seems to be SQL Server specific. We'll have a huge improvement in 5.2.5 (see #810). 
Will return to this ticket in 5.3.

**Comment by serge-rider** [comment]
Looks very similar to #5068
Stored procedures invocation will be significantly improved in 5.3.4.

**Comment by artem-emelin** [comment]
Hi all, still getting this issue with the latest 5.3.5

**Comment by serge-rider** [comment]
@artem-emelin Please provide more info (what database it is and some SQL sample)

**Comment by h4diismanto** [comment]
hi all, maybe this will help.
am use Oracle database, Store procedure with out param cursor.
![create test store procedure](https://user-images.githubusercontent.com/36924883/53621081-e4b57880-3c27-11e9-9ffa-f33005ae1050.PNG)

when i use DBEaver 5.3.3
call Store procedure with out param cursor, doesnt work.
![call sp_test1](https://user-images.githubusercontent.com/36924883/53622917-f39f2980-3c2d-11e9-88f0-3356f308a92e.PNG)
![call sp_test2](https://user-images.githubusercontent.com/36924883/53622924-f8fc7400-3c2d-11e9-849b-0f43b10283fb.PNG)

when i use DBEaver 5.3.5
call Store procedure with out param cursor, work well.
![call sp_test1b](https://user-images.githubusercontent.com/36924883/53622997-3cef7900-3c2e-11e9-8cb6-d5cadbdd01c7.PNG)
![call sp_test2b](https://user-images.githubusercontent.com/36924883/53623002-3fea6980-3c2e-11e9-960b-9cb5127a8d78.PNG)

**Comment by artem-emelin** [comment]
Sorry for delay, let me share more light.

1) Using version 6.0.1 with Oracle DB
2) DB procedure has 3 INPUT and 5 OUTPUT parameters.
3) Pick procedure from particular _package_, click right mouse button on it: http://joxi.ru/eAONwvJCxJe1w2
4) When I set input parameters and try to execute the stored procedure I get next: http://joxi.ru/EA4ZlVqCwbkdJm

**Comment by serge-rider** [comment]
@artem-emelin please create separate ticket, this is a different issue

**Comment by souravs-2pirad** [comment]
I am facing the same issue as artem-emelin.
Since, I am seeing that there are similar issues like [#917](https://github.com/dbeaver/dbeaver/issues/917) and this one itself [#2190](https://github.com/dbeaver/dbeaver/issues/2190), I dont know whether I should open a separate issue or not.

Do we have a solution for this?

**Comment by serge-rider** [comment]
@souravs-2pirad please create a separate ticket.

**Comment by joelsolon** [comment]
I'm using v6.0.2.201904071344, and I just wanted to report that this issue, for me, is **almost** fixed. When I run this statement: `CALL FCE_Operations.ATM_GetAmountOutAndFee(100,0.5,?,?)`
I get my two output parameters back!

<img width="668" alt="Screen Shot 2019-04-12 at 12 45 13 PM" src="https://user-images.githubusercontent.com/12203701/56053021-e727e980-5d20-11e9-857d-529bcb805bbd.png">

The only remaining issues are 1) the false error message above, and 2) DBeaver has placed the return values in the wrong columns.
- 2.50 should be in the Fee column instead of the _isc_sp_ret_val column
- 48.75 should be in the AmountOut column instead of the Fee column
- Since I'm calling the procedure using `CALL` and not `? =` the _isc_sp_ret_val column should be empty

As I pointed out in my original post, DBeaver has the correct metadata:
<img width="414" alt="Screen Shot 2019-04-12 at 12 50 59 PM" src="https://user-images.githubusercontent.com/12203701/56053259-a9779080-5d21-11e9-9ea1-5229e34bde79.png">

**Comment by serge-rider** [comment]
@joelsolon could you also make a separate ticket? It is impossible to track all issues related to plsql in a single ticket.

**Comment by liqili** [comment]
Same issue occurred in Version 7.3.0.202011291229 when executing ms-sql SP. It will execute straightly without asking to fill any parameters.

**Comment by 3rdey3** [comment]
In dbeaver 7.3.1 I am getting the same error when calling procedure.
![image](https://user-images.githubusercontent.com/20192686/102970943-a2f37180-4522-11eb-9559-443d5252185a.png)

**Comment by serge-rider** [comment]
@liqili @3rdey3 Fixed in #10772.
Please test the fix in the Early Access version.
