### ISSUE TITLE
SQLite connection-specific `Maximum text editor content length` setting does not apply

### ISSUE THREAD

**Issue by ar-jan** [dbeaver/dbeaver#21907]
### Description

When I configure `Maximum text editor content length` on a specific SQLite connection, the setting does not apply. After reconnecting/restarting there is still a `Warning: Content representation size is limited to: 100 KB`. If I change it in the global settings, the configuration does apply and the warning disappears.

### DBeaver Version

23.2.5

### Operating System

Void Linux

### Database and driver

1. SQLite 3.44.0
2. SQLite JDBC driver 3.44.0.0

### Steps to reproduce

1. `Edit connection` on a SQLite database.
2. Configure `Maximum text editor content length` and set it to e.g. `1000`
3. Reconnect and open a large cell in the results panel; still see `Warning: Content representation size is limited to: 100 KB` (and only part of the content is loaded).
4. If I change the same setting in the global settings, the configuration does apply and the warning disappears as expected.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
Currently this preference is assumed as data source specific, however we always read its global value.
See AbstractTextPanelEditor line 343
