### ISSUE TITLE
After upgrade Sql Editor cannot detect declared variables in the code.

### ISSUE THREAD

**Issue by krstan4o** [dbeaver/dbeaver#21900]
### Description

If we declare variables and try to use them in the same context / connection / session they are not detected and error will popup.

### DBeaver Version

Community Edition 23.2.5.202311191730

### Operating System

Windows 11

### Database and driver

Microsoft JDBC Driver for SQL Server connecting to Azure Database

### Steps to reproduce

1. write example code that declare and use variables in sql editor:

declare @offerId int = 132;
select @offerId;

2. Mark the code.

3. Hit Ctrl + Enter

4. Error is shown: 
Error occurred during SQL query execution

Reason:
SQL Error [137] [S0002]: Must declare the scalar variable "@offerId".

**Comment by E1izabeth** [comment]
Thank you for bug report. It's a duplicate of #21898
