### ISSUE TITLE
Cannot connect to MySQL 5.x instance, CLIENT_PLUGIN_AUTH is required

### ISSUE THREAD

**Issue by mato** [dbeaver/dbeaver#21906]
### Description

As of DBeaver 23.2.5, I can no longer connect to MySQL 5.x instances. I get a connection error dialog box, with the message "CLIENT_PLUGIN_AUTH is required".

I believe this is due to the following change, from the release notes:

> Databases:
>
>    MySQL:
>        Driver version was upgraded to 8.2
>        Legacy MySQL 5.x driver was deprecated and replaced with MySQL 8 driver 

Is there a workaround for this, or must I stay on DBeaver 23.2.4 or earlier?

### DBeaver Version

Community Edition 23.2.5

### Operating System

Linux

**Comment by Carloscentro** [comment]
Same here. After the last update, I lost connectivity with many hosts running 5.x MySQL versions. I think that removing MySQL5 connector-j was not a good idea since connector-j 8 is not compatible with versións of MySQL minor than 5.6.

**Comment by JasonCrossWCG** [comment]
Another confirmed case here.

**Comment by feeling001** [comment]
Successfully rolled back to 23.2.4 here ... same issue.

**Comment by serge-rider** [comment]
MySQL 5 driver will return in the next version. 
EA version will be published this week.

**Comment by carlosbet** [comment]
Thank you, meanwhile, I have downloaded connector-j 5 directly from MySQL created a new driver from _Driver Manager_, and recreated some connections that I urgently needed.

You can download this from: [https://downloads.mysql.com/archives/c-j/]() and select _Product Version_ 5.1.49

**Comment by AllisonF-23** [comment]
The current EA version didn't seem to fix this issue for me. Is it still being worked on?

**Comment by LonwoLonwo** [comment]
Hello @AllisonF-23 
Could you please provide more info about your case?

**Comment by AllisonF-23** [comment]
> Hello @AllisonF-23 Could you please provide more info about your case?

Sure thing! I use dBeaver for a wide range of SQL servers of various ages, and when I updated to dBeaver 23.2.5 last week, all of the older servers I connect to began giving me an error that says "CLIENT_PLUGIN_AUTH is required". The servers I can no longer connect to are on MySQL 5.1.73 . I tried reverting to dBeaver version 23.2.4 and had the same problem, and then lastly I have updated to the latest early access version I see which is 23.3.0 and the behavior still exists. I'm utilizing the Debian version of dBeaver as well if that is relevant. Is there any other information I can provide?

**Comment by AllisonF-23** [comment]
> > Hello @AllisonF-23 Could you please provide more info about your case?
> 
> Sure thing! I use dBeaver for a wide range of SQL servers of various ages, and when I updated to dBeaver 23.2.5 last week, all of the older servers I connect to began giving me an error that says "CLIENT_PLUGIN_AUTH is required". The servers I can no longer connect to are on MySQL 5.1.73 . I tried reverting to dBeaver version 23.2.4 and had the same problem, and then lastly I have updated to the latest early access version I see which is 23.3.0 and the behavior still exists. I'm utilizing the Debian version of dBeaver as well if that is relevant. Is there any other information I can provide?

So an update to this, I managed to get this working. What I ended up doing was exporting my dbeaver settings, nuking my install of dbeaver completely from my PC, installing 23.3.0, importing my settings. When I did this, I was prompted to download the various drivers for each server and it now works as expected.

**Comment by LonwoLonwo** [comment]
We updated EA version, could you please take a look one more time?
https://dbeaver.io/files/ea/

**Comment by LonwoLonwo** [comment]
@AllisonF-23 
Thanks for the update!

**Comment by MattAnctil** [comment]
Used to work, broken since last update...

**Comment by carlosbet** [comment]
The update is now available for everyone. Even so, it's necessary to update the driver properties for the MySQL 5 connections since they were marked to use the MySQL 8 driver in the previous update.

This is easy, just select all of your connections that should work with MySQL 5 in the Database Navigator, then go to the Database > Change Connection(s) Driver, select MySQL 5 and now everything will work again as before.

Thanks for the update.

**Comment by mato** [comment]
I can confirm that DBeaver 23.3.0 works fine again with connections to MySQL 5.x instances.

>Even so, it's necessary to update the driver properties for the MySQL 5 connections since they were marked to use the MySQL 8 driver in the previous update.

Note that you only need to do this if you upgraded to one of the affected versions in the mean time (>= 23.2.5, <23.3.0). If you go from 23.2.4 to 23.3.0 then everything will continue to work with no changes.

Thanks for the fix.
