### ISSUE TITLE
Regression in 23.2.5 with MS SQL: error on selecting and modifying a field from a CTE

### ISSUE THREAD

**Issue by dr-1** [dbeaver/dbeaver#21901]
### Description

Since upgrading to version 23.2.5, this MS SQL query results in an error:

```
WITH CTE AS (
SELECT 'x' AS ColumnA
)
SELECT ColumnA + 'y'
FROM CTE
```

When leaving out the `+ 'y'` the query runs.

The error is
`SQL Error [422] [S0004]: Common table expression defined but not used.`

### DBeaver Version

23.2.5

### Operating System

Windows 10

### Database and driver

Servers: Microsoft SQL Server 12.00.5349; Microsoft SQL Azure (RTM) - 12.0.2000.8 
Driver: Microsoft JDBC Driver 11.2 for SQL Server 11.2.3.0

### Steps to reproduce

1. Run the example query
2. Observe error

**Comment by dr-1** [comment]
This may be related to #21898, although the error and the code that triggers it are different.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
@dr-1 I can't reproduce the issue. Am I doing something wrong?



https://github.com/dbeaver/dbeaver/assets/28875055/b0cb5e73-81a8-43e8-b89e-30ac5daa30a4

**Comment by dr-1** [comment]
That is how I executed it as well. Tried on different databases, both SQL Server and Azure Synapse Serverless.

![image](https://github.com/dbeaver/dbeaver/assets/24420610/93276f0a-9d8c-401f-8c19-20f358a823ff)

**Comment by dr-1** [comment]
Running the same query on the same database through SQLAlchemy works.

**Comment by E1izabeth** [comment]
@dr-1 could you tell me your database and driver version?

![image](https://github.com/dbeaver/dbeaver/assets/28875055/d6861adf-2b53-4051-b5e7-ea158b257682)

**Comment by dr-1** [comment]
The driver is as mentioned in the issue description: Microsoft JDBC Driver 11.2 for SQL Server 11.2.3.0

**Comment by E1izabeth** [comment]
Yeah, thanks

**Comment by E1izabeth** [comment]
Could you try our early access version? We made some fixes that could fix it.
Early access version is available here https://dbeaver.io/files/ea/

**Comment by dr-1** [comment]
With the early access version (23.2.5.202311220022) I do not get the error anymore. The query executes as expected.

**Comment by E1izabeth** [comment]
Thank you for update
