### ISSUE TITLE
SQL Server "defautl" value constraint not listed in treeview

### ISSUE THREAD

**Issue by coucout** [dbeaver/dbeaver#21904]
### Description

I have writing this sql to add a column with a default value:

ALTER TABLE Ressource ADD RessourceIDGarage numeric(1,0) Default 0

But now I Want to remove this Column. So I Write this sql

alter table Ressource DROP column RessourceIDGarage

But SQL Server return me an error : 

DF_RESSOURCE_Resso_xxxxx depends of columns 'RessourceIDGarage'

If a right click on the column in the treeview and choose delete, DBeaver generate correct script:

ALTER TABLE wcnt_ecau.dbo.RESSOURCE DROP CONSTRAINT DF__RESSOURCE__Resso__6D78129F;
ALTER TABLE wcnt_ecau.dbo.RESSOURCE DROP COLUMN RessourceIDGarage;

The problem is I cannot see the constraint "DF__RESSOURCE__Resso__6D78129F" in the treeview. The "Check constraints" leaf is empty.

### DBeaver Version

23.2.5.202311191730

### Operating System

Windows 11

### Database and driver

SQL Server

**Comment by coucout** [comment]
Sorry, the complet version is : 23.2.5.202311191730

**Comment by LonwoLonwo** [comment]
Hello @coucout 

> The problem is I cannot see the constraint "DF__RESSOURCE__Resso__6D78129F" in the treeview. The "Check constraints" leaf is empty.

Please provide your table DDL.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
