### ISSUE TITLE
PG: Checking Hide folders in Navigator view emerges Can't access pgAgent jobs error

### ISSUE THREAD

**Issue by efkz** [dbeaver/dbeaver#21919]
### Description

Hi.
I'm just a dev who wants quick access to tables and constraints and sequences and rows and columns without jumping by folders like a freaky monkey. But when I turn off folders in Navigator view and connect to Postgres DB, I get this error:

Can't access pgAgent jobs.
This database may not have the extension installed or you don't have sufficient permissions to access them.
If you believe that this is DBeaver's fault, please report it.

I found that same error appears when I use folders and try to view Administer/Jobs folder.

I tried Simple view in Navigator view but it's oversimplified and useless for me.

### DBeaver Version

CE 23.2.3.202310221533

### Operating System

Win 10 Pro

### Database and driver

1. PostgreSQL 13.0
2. PostgreSQL JDBC Driver

### Steps to reproduce

1. Create or use existing connection to Postgres DB
2. Edit connection and click 'General' section
3. In 'Navigator view' parameter click 'Customize...' button
4. Uncheck 'Hide folders' checkbox
5. Click 'Ok' and reconnect to DB
6. Double click on connection and here is error

**Comment by LonwoLonwo** [comment]
Hello @efkz 

Thanks for the bug report.
I will add this case to the original ticket: https://github.com/dbeaver/dbeaver/issues/16366
