### ISSUE TITLE
Missing linebreak in Task-Log-File: "Dump query results to log file"

### ISSUE THREAD

**Issue by kfa-t** [dbeaver/dbeaver#21915]
### Description

The first result line is connected by a \t-char to the "Columns:"-line:

2023-11-20 17:20:42.530 - -----------------> Execute query
select '--' rem, to_char(pg_total_relation_size(t.tablename::text), '999,999,999,990') rel_size_str, to_char(pg_table_size(t.tablename::text), '999,999,999,990') tab_size_str, t.schemaname, t.tablename from pg_catalog.pg_tables t
where t.schemaname =current_schema
order by 1 desc
limit 30
2023-11-20 17:20:42.536 - 	Fetch result set
**Columns:**	rem	rel_size_str	tab_size_str	schemaname	tablename	--	          90,112	          73,728	authmgr	amtan	
--	       1,835,008	       1,589,248	authmgr	customer	
--	       3,022,848	         778,240	authmgr	licauth	
...
--	          57,344	          40,960	authmgr	apptype	
2023-11-20 17:20:42.536 - 	30 rows fetched
2023-11-20 17:20:42.536 - -----------------> Time: 7ms, fetched 30 row(s)

### DBeaver Version

23.2.5.202311191730

### Operating System

Windows 10

### Database and driver

PostgreSQL 13.7
PostgreSQL 13.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10), 64-bit
PostgreSQL JDBC Driver 42.2.25

and

Oracle Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production
Oracle JDBC driver 12.2.0.1.0

### Steps to reproduce

create a task "Common" - "SQL Script" (select:  sample see Description-field - - any select will do)
ensure checkbox "Dump query results to log file" is checked
open the resulting log-file

**Comment by E1izabeth** [comment]
Thank you for bug report.
