### ISSUE TITLE
Table with 2 unique fields cant be created. 

### ISSUE THREAD

**Issue by hvprvtr** [dbeaver/dbeaver#21920]
### Description

Hello. If i create table with 2 fields with unique constrant, DBeaver makes 2 constraints with same names - [tablename]_un. Names duplicate break a table creation process. I must go to editor, fix SQL (_un, _un1) and run in manually. 

### DBeaver Version

Community Edition 23.2.5

### Operating System

Win 10

### Database and driver

MariaDB  11.1.3

### Steps to reproduce

1. Create new database
2. Create new table
3. Add two any fields
4. Go to constraints and create 2 unique keys. 
5. Click "Save", view SQL (duplicate un names), run, see error.

**Comment by LonwoLonwo** [comment]
Hello @hvprvtr 

Thanks for the report.
Probably we can improve this behavior.
