### ISSUE TITLE
freezes when expanding the Indexes section

### ISSUE THREAD

**Issue by serban-dobroiu** [dbeaver/dbeaver#21928]
### Description

When expanding the Indexes section for a table in the database navigator pane DBeaver freezes

### DBeaver Version

Community Edition 23.2.5

### Operating System

Windows 10

### Database and driver

MS SQL Server Enterprise 14.0.1000.169

### Steps to reproduce

Connect to db, filter for specific table, expand Indexes section --> DBeaver freezes

**Comment by LonwoLonwo** [comment]
Hello @serban-dobroiu 

> filter for specific table

What type of filtering did you use in this step?

**Comment by serban-dobroiu** [comment]
Hey, @LonwoLonwo , when filtering for a specific DB object (table in this case) in the filter bar of the database navigator pane (where the placeholder is *Enter a part of object name here*) and then I expand the Indexes section of the object in question. 

I have Database and Schema filters configured; I am expanding the DB and schema nodes, enter a search string at the top, identify the object and expand the indexes node, that's when it freezes. If I don't apply the object filter all is good.

**Comment by serjiokov** [comment]
@serban-dobroiu Could you please provide thread dump and short video of the issue?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
