### ISSUE TITLE
unable to run the sql contains for loop in hana

### ISSUE THREAD

**Issue by Hena-Test** [dbeaver/dbeaver#21926]
### Description

it is not working when click execute button

### DBeaver Version

Community 23.2.5

### Operating System

windows 10 22H2

### Database and driver

database name and version: hana 2.0 sp05
driver name and version:
![image](https://github.com/dbeaver/dbeaver/assets/134022716/cde9947f-b11e-44d5-b363-bf5fd14efaa6)

### Steps to reproduce

1. connect to hana db 
2. run the sql as below:
`do BEGIN
DECLARE VAR_1 INTEGER;
FOR VAR_1 IN 0..2 
DO
VAR_1 = :VAR_1 + 1;
END FOR;
P1=SELECT 1 FROM dummy;
SELECT * FROM :P1;
END`
3.try to click execute sql query/script 

### Additional context

the sql can be executed in dbeaver 22.1.2

**Comment by E1izabeth** [comment]
Please try our early access version. You can find it here https://dbeaver.io/files/ea/

**Comment by Hena-Test** [comment]
> Please try our early access version. You can find it here https://dbeaver.io/files/ea/

yes, i can run it in version: 22.1.2 , but when i update to 23.2.5 , it will be not working
![image](https://github.com/dbeaver/dbeaver/assets/134022716/4410dc96-735f-4181-be7b-0987d3da41ca)

**Comment by LonwoLonwo** [comment]
> but when i update to 23.2.5

Sorry, it is unclear from your message. Did you try our [Early Access version](https://github.com/dbeaver/dbeaver/issues/21926#issuecomment-1821309330)? We added some fixes there and want to know if your issue is also solved.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
