### ISSUE TITLE
About page "Supported databases" error

### ISSUE THREAD

**Issue by Icemap** [dbeaver/dbeaver#21923]
### Description

In https://dbeaver.io/about/, it's should be "TiDB Cloud", not "TiDB Cloud Telemetry".

<img width="251" alt="image" src="https://github.com/dbeaver/dbeaver/assets/26212551/d0d8ed68-b40f-46f7-ac49-73cf49ceadb9">

### DBeaver Version

All

**Comment by LonwoLonwo** [comment]
Ok, Thanks @Icemap

**Comment by LonwoLonwo** [comment]
Fixed.
