### ISSUE TITLE
ALTER TRIGGER Fails for Firebird DB in version 23.2.5

### ISSUE THREAD

**Issue by AdamDempsey** [dbeaver/dbeaver#21933]
### Description

Tried making a simple update to a Firebird Trigger and got the error below, reverting from 23.2.5 to 23.2.4 and it updated as expected.

```
Error occurred during SQL script execution

Reason:
SQL Error [335544851] [42000]: Dynamic SQL Error; SQL error code = -104; Unexpected end of command - line 3, column 26 [SQLState:42000, ISC error code:335544851]
```

With the below being the opening lines:

```
ALTER TRIGGER TRIG_ORDERS_4
as
DECLARE VARIABLE KUSERID INTEGER;
BEGIN
```

### DBeaver Version

Community Edition 23.2.5

### Operating System

macOS Ventura 13.6 (22G120)

### Database and driver

Firebird 2.5.9
Firebird Jaybird driver 5.0.2

**Comment by E1izabeth** [comment]
Please try our early access version. You can find it here https://dbeaver.io/files/ea/

**Comment by AdamDempsey** [comment]
That works again now, thanks :)

**Comment by E1izabeth** [comment]
Thank you for update
