### ISSUE TITLE
Task Logging: Format of Oracle TimestampTZ differs from simple select result

### ISSUE THREAD

**Issue by kfa-t** [dbeaver/dbeaver#21944]
### Description

Suprising format of timestamp-column when running in a task:
"oracle.sql.TIMESTAMPTZ@5d7f9f59"  instead of  "2017-01-01 00:00:00.000 +0100"

### DBeaver Version

23.2.5.202311191730

### Operating System

Windows 10

### Database and driver

Oracle Oracle Database 11g Release 11.2.0.4.0 - 64bit Production
Oracle JDBC driver 12.2.0.1.0

### Steps to reproduce

select start_date from user_scheduler_jobs;  --- within a task

**Comment by LonwoLonwo** [comment]
Hello @kfa-t 

Could you please provide more info?
What type of task do you use? How you get the result? 
Clear steps to reproduce will be helpful.

**Comment by kfa-t** [comment]
Hello E1izabeth

I found this output in the logfile of the task when trying to get infos about sheduled-jobs in our  oracle-databases.
The above representation was only visible within the logfiles.
For me "to_char(sj.START_DATE, 'YYYY-MM-DD HH24:MI:SS') START_DATE" did the job.
This seems to be the solution for this small problem: [PzaThief](https://github.com/PzaThief)  https://github.com/dbeaver/dbeaver/pull/21979#issuecomment-1826231137
