### ISSUE TITLE
Right-click to close all displays error

### ISSUE THREAD

**Issue by yangyuanqiang** [dbeaver/dbeaver#21941]
### Description

When I set the language to Simplified Chinese, the 'close all' option displays as '关闭关闭' I think it should be '关闭全部'
![snapy](https://github.com/dbeaver/dbeaver/assets/6103357/e6a56fcc-5cbe-43e5-b413-39df56526a77)

### DBeaver Version

DBeaver Community 23.2.5

### Operating System

Windows 10

**Comment by E1izabeth** [comment]
Thank you for bug report. It's a duplicate of #17697
