### ISSUE TITLE
Fix to the "Opening workspace in Eclipse" section in the "Develop in Eclipse" wiki page

### ISSUE THREAD

**Issue by hendrik-r** [dbeaver/dbeaver#21945]
### Description
The step 8 in the subsection "Opening workspace in Eclipse" the wiki page "Develop in Eclipse" is wrong.

### Expected Behaviour
8. Choose "Maven->Existing Maven Projects".

### Existing Behaviour
8. Choose "General->Existing Maven Projects".

**Comment by E1izabeth** [comment]
Thank you for bug report.
