### ISSUE TITLE
'Column width: fit values' should't reset after sorting

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#21948]
### Description

When the user set up column width by using 'Column width: fit values' and then sorts the column contents, the column width resets. We want to fix this.

Based on https://github.com/dbeaver/dbeaver/issues/21647#issuecomment-1781169122

Reproduced on 23.2.5

### DBeaver Version

23.2.5

### Steps to reproduce

1. Enable column ordering.
2. Use 'Column width: fit values'.
3. Click the ordering icon.

**Comment by Destrolaric** [comment]
Can't reproduce
https://github.com/dbeaver/dbeaver/assets/20579256/b47282fc-13a2-4637-a0e5-3995a23cef57

**Comment by Matvey16** [comment]
Not reproducible anymore
