### ISSUE TITLE
Rollback countdown flashing constantly

### ISSUE THREAD

**Issue by kczx3** [dbeaver/dbeaver#21955]
### Description

After upgrading, I constantly get a "Rollback in 9m 22s" countdown in the status bar that flashes all the time.  Moving the cursor around seems to make it stop, at least for a little bit.  It is rather annoying though.

### DBeaver Version

Community Edition 23.2.5.202311191730

### Operating System

Windows 10.0.19045.3693

### Database and driver

Oracle database with oracle.jdbc.OracleDriver

### Steps to reproduce

Connect to database and run a query.  The rollback should show at the bottom-right of the status bar.  Have the connection set to "Manual Commit (Read committed)".

**Comment by ShadelessFox** [comment]
Thanks for the report
