### ISSUE TITLE
all columns  are read-only

### ISSUE THREAD

**Issue by Dickfp** [dbeaver/dbeaver#21958]
### Description

just a simple query statement  but the results cantnot be edited
![20231123115148](https://github.com/dbeaver/dbeaver/assets/25146643/d0fed496-88f3-4bd7-a4a5-304ff87f48d1)

### DBeaver Version

community  23.2.5.202311191730

### Operating System

win11

### Database and driver

postgresql  driver  42,7

**Comment by LonwoLonwo** [comment]
Hello @Dickfp 

Could you try to refresh the navigator tree for your public schema first and try again?

**Comment by Dickfp** [comment]
I tried, but it's still the same

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by Dickfp** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/13456517/dbeaver-debug.log)

**Comment by Dickfp** [comment]
every time i execute a query ,there will be an error ,Please see the log file for details @LonwoLonwo

**Comment by LonwoLonwo** [comment]
What database do you use? Version and type.

Could you please try to execute this query:
`SELECT current_schema(),session_user`

Does it work for you?

**Comment by Dickfp** [comment]
![1700814400601](https://github.com/dbeaver/dbeaver/assets/25146643/0fe441a3-38b0-44dc-a33b-6c96e0f0acaa)

**Comment by LonwoLonwo** [comment]
But why are all your columns names upper-cased? 
What database do you use?

**Comment by Dickfp** [comment]
i use AntDB   A PostgresSQL-based database

**Comment by Dickfp** [comment]
https://www.asiainfo.com/en_us/product_aisware_antDB.html

**Comment by LonwoLonwo** [comment]
I see this in your log:

```
org.jkiss.dbeaver.model.exec.DBCException: SQL 错误 [42703]: ERROR: column "session_user" does not exist
  Position: 25
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreExecutionContext.refreshDefaults(PostgreExecutionContext.java:228)
```

Maybe your database has some kind of preference to not upper case result column names?

**Comment by Dickfp** [comment]
maybe  i'll try to find it,  thank you

**Comment by Neerajsharma01** [comment]
Facing same issue and if we add database name before schema name its working fine not sure any setting need to change.
