### ISSUE TITLE
Dbeaver oracle dbms output  does not work

### ISSUE THREAD

**Issue by AlexuLag** [dbeaver/dbeaver#21969]
### Description

when we use dbms output in oracle, it does not show the output in output window

### DBeaver Version

23.2.5.202311191730

### Operating System

windows

### Database and driver

Oracle 19
oracle.jdbc.OracleDriver

### Steps to reproduce

1 connect to database
2 on the editor put 
begin
DBMS_OUTPUT.PUT_LINE('BEGIN');
END;

3 run sentence
4 see output window

**Comment by E1izabeth** [comment]
Thank you for bug report. It's a duplicate of #21902
