### ISSUE TITLE
Column descriptions cannot be displayed when connecting to an Oracle database.

### ISSUE THREAD

**Issue by mdks2010** [dbeaver/dbeaver#21971]
### Description

In dbeaver's data editor, column descriptions are displayed in the title bar, and column descriptions can be displayed when querying a MySQL database, but cannot be displayed when connecting to an oracle database.

### DBeaver Version

DBeaver 23.2.5

### Operating System

window10

**Comment by mdks2010** [comment]
As a side note, the column descriptions are not in English.

**Comment by LonwoLonwo** [comment]
Hello @mdks2010 

There exactly you can not see Oracle column descriptions?
Btw, this parameter is lazy in Oracle. Usually it means, that you need to open a table property tab to read column descriptions.

**Comment by mdks2010** [comment]
I entered an SQL statement in the SQL editor to connect to the oracle query, and there was no field comment in the returned result.

Note: I have commented the fields in the oracle table.

**Comment by LonwoLonwo** [comment]
Could you please check this setting:

![2023-11-27 10_41_24-Preferences](https://github.com/dbeaver/dbeaver/assets/45152336/5c065f65-268f-44c9-8a64-5233e5da022e)

Is it on?

**Comment by mdks2010** [comment]
I've already set it up here, and currently by entering SQL statements through the SQL editor, querying MySQL can display column comments.

However, when you enter an SQL statement to query the oracle database, the column comments cannot be displayed.

**Comment by LonwoLonwo** [comment]
Did you refresh yor table? Did you check your comments in your table?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by xzl-5039** [comment]
I encountered the same problem and raised an issue
