### ISSUE TITLE
Can shift+enter on a binary field open an external hex editor?

### ISSUE THREAD

**Issue by yanOnGithub** [dbeaver/dbeaver#2197]
Like WinSCP, I can open a remote file in a local external text editor. After editing, the changes goes to a temp file and the temp file is uploaded to remote.

I would like to have dbeaver launching HxD or any other configurable editor, the changes should be written back to the database.

#2159  and #2138 can be superseded by this ticket.

**Comment by serge-rider** [comment]
I like this
