### ISSUE TITLE
DBeaver does not refresh application information / cache on disconnect for Kerberos handling

### ISSUE THREAD

**Issue by mtdeguzis** [dbeaver/dbeaver#2198]
# Problem description

I have found that if the application is left open until the ticket expires server side, I get a GSS failed, even if my powershell script removes the ticket file in C:\Users\name\. So, it is not a question of getting a fresh kerberos ticket from the server, but in the sesssion/cached data the application and/or plugins has. Closing the application and reopening it allows the connection right away with a non-expired ticket that previous to closing, would fail. Something is not being refreshed that should happen at the application level when you choose "disconnect" or try to reconnect.

```
Could not open client transport with JDBC Uri: jdbc:hive2://HOST.DOMAIN.COM:PORT/;principal=hive/HOST.DOMAIN.COM@HOST.COM: GSS initiate failed
  org.apache.hive.org.apache.thrift.transport.TTransportException: GSS initiate failed
```

Is there file that holds session information that could cause this to fail? Closing and reopening the application allows the connection to proceed just fine.

# Modified files on restart

I found that on application restart touches these files:

```
FullName      : C:\Dbeaver64\dbeaver-data\.metadata\.plugins\org.eclipse.e4.workbench\workbench.xmi
LastWriteTime : 9/20/2017 12:09:11 PM

FullName      : C:\Dbeaver64\dbeaver-data\.metadata\.log
LastWriteTime : 9/20/2017 12:09:11 PM

FullName      : C:\Dbeaver64\dbeaver-data\.metadata\qmdb\qmdb.mv.db
LastWriteTime : 9/20/2017 12:09:12 PM

FullName      : C:\Dbeaver64\dbeaver-data\.metadata\.plugins\org.eclipse.core.resources\.root\107.tree
LastWriteTime : 9/20/2017 12:09:12 PM

FullName      : C:\Dbeaver64\dbeaver-data\.metadata\.plugins\org.eclipse.core.resources\.safetable\org.eclipse.core.res
                ources
LastWriteTime : 9/20/2017 12:09:13 PM

FullName      : C:\Dbeaver64\dbeaver-data\.metadata\.plugins\org.jkiss.dbeaver.core\dialog_settings.xml
LastWriteTime : 9/20/2017 12:09:13 PM

FullName      : C:\Dbeaver64\dbeaver-data\.metadata\.plugins\org.eclipse.core.runtime\.settings\org.jkiss.dbeaver.core.
                prefs
LastWriteTime : 9/20/2017 12:09:13 PM

FullName      : C:\Dbeaver64\dbeaver-data\.metadata\.plugins\org.eclipse.ui.workbench\dialog_settings.xml
LastWriteTime : 9/20/2017 12:09:13 PM

FullName      : C:\Dbeaver64\dbeaver-data\.metadata\.plugins\org.eclipse.core.resources\.root\.indexes\properties.versi
                on
LastWriteTime : 9/20/2017 12:09:14 PM

FullName      : C:\Dbeaver64\dbeaver-data\.metadata\.plugins\org.eclipse.core.resources\.root\.indexes\history.version
LastWriteTime : 9/20/2017 12:09:14 PM

FullName      : C:\Dbeaver64\dbeaver-data\.metadata\.plugins\org.eclipse.core.resources\.root\.indexes\properties.index
LastWriteTime : 9/20/2017 12:09:14 PM

FullName      : C:\Dbeaver64\configuration\org.eclipse.core.runtime\.manager\.tmp1737034209151201296.instance
LastWriteTime : 9/20/2017 12:09:17 PM

FullName      : C:\Dbeaver64\configuration\org.eclipse.equinox.app\.manager\.tmp3496208271669698944.instance
LastWriteTime : 9/20/2017 12:09:18 PM

FullName      : C:\Dbeaver64\dbeaver-data\.metadata\dbeaver-debug.log
LastWriteTime : 9/20/2017 12:09:19 PM

FullName      : C:\Dbeaver64\dbeaver-data\.metadata\dbeaver-workspace.properties
LastWriteTime : 9/20/2017 12:09:19 PM

FullName      : C:\Dbeaver64\dbeaver-data\.metadata\dbeaver-instance.properties
LastWriteTime : 9/20/2017 12:09:20 PM

FullName      : C:\Dbeaver64\dbeaver-data\.metadata\.plugins\org.eclipse.core.resources\.projects\General\.indexes\18\p
                roperties.index
LastWriteTime : 9/20/2017 12:09:28 PM

FullName      : C:\Dbeaver64\kinit.logLastWriteTime : 9/20/2017 12:09:33 PM
```

# Steps to reproduce

1. Open DBeaver
2. Get a kerberos ticket via C:\Dbeaver64\jre\bin\kinit.exe
3. Connect to the profile
4. Leave application open past the expiration window of the kerberos ticket
5. Disconnect from the connection profile
5. Connect to the profile
6. GSS error

**Comment by mtdeguzis** [comment]
Any workaround I can implement for this? This is the one issue preventing us from deploying a version of Dbeaver with a kerberized Hive setup for Hadoop.

**Comment by serge-rider** [comment]
Unfortunately I can't help with this.
Kerberos (especially with with Hadoop) isn't my area :(

**Comment by mtdeguzis** [comment]
Since this works fine when you close and reopen the application though, can't there be an option to flush plugin cache/information?

**Comment by kholis** [comment]
Hi @mtdeguzis , are you aware with this tutorial? http://justnumbersandthings.com/2017-05-06-Dbeaver-Hive-Kerberos.html

I also failed to connect dbeaver with kerberos in windows. Kerberos is so tricky in Windows.

**Comment by serge-rider** [comment]
@mtdeguzis this seems to be Hadoop driver specific. 
May there is some way to flush Kerberos cache using some general API but I'm not aware of this.

**Comment by serge-rider** [comment]
Just in case http://justnumbersandthings.com/2017-05-06-Dbeaver-Hive-Kerberos.html

**Comment by mtdeguzis** [comment]
We are attempting to overcome this with a jaas.conf file, loaded at runtime, but the VM arg itself I think is ignored. SSPI is a better way forward for kerberos houses

```
-Djava.security.auth.login.config="C:\Dbeaver64\jre\lib\security\KerberosLoginConfig.ini"
```

![image](https://user-images.githubusercontent.com/27829577/35442090-fbae5df2-0273-11e8-87ec-370c7a4fd557.png)

**Comment by mtdeguzis** [comment]
Any progress on this since Jan?

**Comment by KraFusion** [comment]
@mtdeguzis  is this still an issue for you?
I have successfully connected by adding the following options to dbeaver.ini and restarting DBeaver.
You will have to create both of these from scratch, but they are very simple.

-Djava.security.auth.login.config=/Users/[userid]/jaas.conf
-Djava.security.krb5.conf=/Users/[userid]/krb5.conf

**Comment by mtdeguzis** [comment]
That would only work if the jaas.conf could be dynamic. This must work for anyone logging into the deployed application. I am familiar with jaas.conf a bit, but not so much with dynamic variables for it (if any). It's not a matter of getting connected, but the kerberos ticket expiring per the original description. I am eager to make this work, so if you have any tips/pointers, I am all ears.

**Comment by KraFusion** [comment]
@mtdeguzis this issue has less to do with DBeaver and has more to do with JDBC connectivity coupled with Kerberos.  In other words, you will see this with any JDBC client, not just DBeaver.
I'll leave it up Serge to keep this open or not.

However, we can continue to work through your issue here for now.
I don't see it mentioned, but have you tried using a keytab? and referencing that keytab in the jaas.conf?

**Comment by sun897827804** [comment]
According to the previous Kerberos configuration, the connection to the Hive URL still appears: "GSS Initiate Failed"。version 6.2.3

**Comment by uslss** [comment]
is it still actual against 21.2.0?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info

**Comment by hwfbest** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/16427578/a80f98ec-3797-4944-bfc1-82bbc93e225d)

Solution: Determine whether the development equipment is synchronized with the server's device clock, synchronize with the server's clock

**Comment by hwfbest** [comment]
dbeaver  debug
`>>> KDCCommunication: kdc=bigdata29 UDP:88, timeout=30000,Attempt =1, #bytes=643
SocketTimeOutException with attempt: 1
>>> KDCCommunication: kdc=bigdata29 UDP:88, timeout=30000,Attempt =2, #bytes=643
SocketTimeOutException with attempt: 2
>>> KDCCommunication: kdc=bigdata29 UDP:88, timeout=30000,Attempt =3, #bytes=643
SocketTimeOutException with attempt: 3
>>> KrbKdcReq send: error trying bigdata29
java.net.SocketTimeoutException: Receive timed out
`
Workaround: Add the following configuration to the krb5.ini configuration file

udp_preference_limit = 1

I hope this helps.
