### ISSUE TITLE
Server Output text doesn't refresh

### ISSUE THREAD

**Issue by renezito** [dbeaver/dbeaver#21984]
### Description

Hi.  When I execute a PL SQL Code, the server output doesn't refresh the output (text).  I have to run another query and then when I go to server output I can see the log.

https://github.com/dbeaver/dbeaver/assets/37661233/d56d2607-4ba2-4c23-aa71-98c1bde12d6e

### DBeaver Version

Community Edition 23.2.5

### Operating System

Windows 10 Pro

### Database and driver

Oracle 12c  -  Oracle JDBC driver

### Steps to reproduce

Run a call to a procedure that writes to dbms and then see the output.  I maked a video =)

**Comment by LonwoLonwo** [comment]
Hello @renezito 

Thanks for the bug report.

Could you please check the latest Early Acces version? https://dbeaver.io/files/ea/

Issue is fixed here: https://github.com/dbeaver/dbeaver/issues/21902
