### ISSUE TITLE
Cannot delete join or table in Query Builder

### ISSUE THREAD

**Issue by zolfj** [dbeaver/dbeaver#21992]
### Description

Hi there,
I am using Version 21.3.0.202112052011 and I use Query Builder to design my queries. The issue I have is I cannot remove a join or table from it. Can you please look into it or what am I missing?
regards
Zolf

### DBeaver Version

Version 21.3.0.202112052011

### Operating System

Win 11

### Database and driver

Mysql 5

### Steps to reproduce

Add tables and join tables and then try to remove the join link or table from the query builder view.It does not show any delete option or when I click on delete button on keyboard nothing happens

**Comment by LonwoLonwo** [comment]
Hello @zolfj 

Could you please provide any footage of your issue?

**Comment by zolfj** [comment]
Hello there,
You mean screenshot?

**Comment by LonwoLonwo** [comment]
Let's start from a screenshot, yes

**Comment by LonwoLonwo** [comment]
But please attach it here on this GitHub page, not via e-mail (it will not work via e-mail)

**Comment by zolfj** [comment]
![2023-11-27_12-21-28](https://github.com/dbeaver/dbeaver/assets/8213324/e60793cc-91bc-4a27-9427-2a66b48ab8d1)

Attached small gif video

**Comment by LonwoLonwo** [comment]
Ok, I will try to reproduce.
But first question - what result do you expect after the join deleting? Because it can not be just a table without connection with other tables in the query.

**Comment by zolfj** [comment]
Thanks, you see sometimes I link to the wrong columns in the two table and want to remove it and again reassign the links

**Comment by LonwoLonwo** [comment]
Unfortunatelly, I can not reproduce your issue.

![2023-11-27 20_52_16-DBeaver Ultimate 23 3 0 - _localhost 5_ test_for_vqb user_depart_link](https://github.com/dbeaver/dbeaver/assets/45152336/17879d48-1b30-48f8-a53b-a094deca8f32)


Could you please try the latest DBeaver version?

**Comment by zolfj** [comment]
I will try it. Thank you.

**Comment by zolfj** [comment]
This happens when I start a new SQL script and start writing query manually. Then I click on Query builder to help me continue with my design. Then is issue arises.

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/issues/21992#issuecomment-1827392635 so, you started from the query from this video? 
Or do you add something with the Query Builder and after it the "delete" button disappear?

**Comment by zolfj** [comment]
Yes

**Comment by zolfj** [comment]
By the way, do you'll have sale season, where I can buy on discount the
latest version

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

And unfortunately, I do not know anything about our sale season...

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by zolfj** [comment]
Yes, everything is fine.

**Comment by pringleb** [comment]
I think that the folks at DBeaver are not understanding that we DON'T want to delete the table.  We just want to be able to remove the line between them and then reconnect them.
