### ISSUE TITLE
The "Check for new driver versions" preference is not saved

### ISSUE THREAD

**Issue by alexander-lazarin** [dbeaver/dbeaver#21999]
### Description

![image](https://github.com/dbeaver/dbeaver/assets/31186865/32ca9474-d124-4ed9-8797-a5c499b744cd)

### DBeaver Version

Community Edition Version 23.2.5.202311191730

### Operating System

Windows 10

### Steps to reproduce

1. Open Window→Preferences→Connections→Drivers.
2. Observe that the checkbox "Check for new driver versions" is unchecked.
3. Check the checkbox.
4. Click Apply.
5. Click Apply and Close.
6. Open Window→Preferences→Connections→Drivers again.
7. Observe that the checkbox is unchecked again.

**Comment by LonwoLonwo** [comment]
Thanks for the report @alexander-lazarin
