### ISSUE TITLE
The default values of a procedure parameters do not appear.

### ISSUE THREAD

**Issue by ugrsyn** [dbeaver/dbeaver#21991]
### Description

As I explained in the "Steps to reproduce", the Procedure->Properties->Source form does not show the default values of the procedure.

### DBeaver Version

Community Edition 23.2.0

### Operating System

Windows Server 2019

### Database and driver

1. DB : Firebird 4.0
2. Driver : Firebird Jaybird driver org.firebirdsql.jdbc.FBDriver 5.0.2

### Steps to reproduce

1. Create a procedure with default values in its parameters.
`SET TERM # ;
CREATE OR ALTER PROCEDURE SP_PARAMS_WITH_DEFAULT_VALUES(P0 integer not null, P1 integer=10, P2 integer default 20, P3 VARCHAR(5) DEFAULT 'TEST')
RETURNS(R0 integer, R1 integer, R2 integer, R3 VARCHAR(5))
as
begin
  R0 = :P0;
  R1 = :P1;
  R2 = :P2;
  R3 = :P3;
  SUSPEND;
end#`
2. Execute this line (with only P0 parameter) in the Sql Editor `SELECT * FROM SP_PARAMS_WITH_DEFAULT_VALUES(12)`
3. Refresh the "Procedures" node in Database Navigator.
4. Double click on the procedure. On the right side, in the "Source" section, the default values of the parameters do not appear.
5. When I make a change in the procedure and press Save and then Persist in the dialog screen, the procedure does not work because the default values of the procedure are lost.

**Comment by LonwoLonwo** [comment]
Ok, thanks for the bug report.

I can't reproduce it with Firebird Server version 2, but I can reproduce it with version 3.
