### ISSUE TITLE
CSV export corrupt the persian character couldn't be able to read

### ISSUE THREAD

**Issue by FarshidShekari** [dbeaver/dbeaver#21990]
### Description

When a table column has Persian characters in its values, in the export of the table that column's values change their face in output.

below is the Persian expression that you can paste into your column value in the table for the test. 

این متن برای تست خروجی به صورت اکسل می باشد. 

### DBeaver Version

Latest

### Operating System

Windows 11

### Database and driver

Database I think didn't impact on it, but that's Oracle 19c

**Comment by PzaThief** [comment]
Did you checked your CSV as text file?
If you open it in Excel, the data may appear corrupted because it uses WINDOWS-1252 encoding rather than UTF-8 encoding.
I tried your text file with Oracle and SQLite, but i can't reproduce data corrupted.

**Comment by FarshidShekari** [comment]
Yes, it's fine with opening that with with notepad but I want to open it with Excel.

**Comment by PzaThief** [comment]
This guide may help you.
https://stackoverflow.com/a/6488070/15643772

**Comment by FarshidShekari** [comment]
Isn't possible to apply it in DBeaver for user experiences?

**Comment by PzaThief** [comment]
If you want to let Excel know encoding to UTF-8 automatically, just check `Insert BOM` check box.
Then BOM will be inserted in front of file, and Excel will catch it.
![image](https://github.com/dbeaver/dbeaver/assets/60059706/871b3cc8-8db9-4405-8eca-a68bb96d167f)

**Comment by FarshidShekari** [comment]
Thanks for clarification
