### ISSUE TITLE
Mysql driver download fails with SSLHandshakeException

### ISSUE THREAD

**Issue by tiagofvalerio** [dbeaver/dbeaver#22007]
### Description

After I upgraded DBeaver CE from version 22.2.0 to 23.2.5 I'm not able to connect to all my configured mysql connections due to an error while downloading mysql driver. 

### DBeaver Version

Community Edition 23.2.5

### Operating System

Ubuntu 20.04.6 LTS

### Database and driver

1. Mysql

### Steps to reproduce

1. With a mysql connection already configured, go to "Edit connection".
2. Go to "Driver properties"
3. The error "javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target" pops up.

**Comment by PzaThief** [comment]
Could you check your network?
For download MySQL driver, Dbeaver attempt to connect with https://repo1.maven.org/ and https://www.gnu.org.
Thus, If your machine is on firewall or use proxy, It may cause connection error.
Related Issue: #18721

**Comment by LonwoLonwo** [comment]
Additionaly, maybe this answer will be helpfull:
https://github.com/dbeaver/dbeaver/issues/16608#issuecomment-1139341329

**Comment by tiagofvalerio** [comment]
@PzaThief My network is ok. The only detail is that I access the database through a VPN (Netskope), but I access the address https://repo1.maven.org/ using java projects with success for example.

@LonwoLonwo I didn't get it. Is it necessary to import a certificate? I've never used it before. Using version `22.2.0` I'm able to access it normally.

**Comment by LonwoLonwo** [comment]
Okay, instead of certificate managing you can try this: https://github.com/dbeaver/dbeaver/issues/18309#issuecomment-1325009193

**Comment by tiagofvalerio** [comment]
@LonwoLonwo This does not apply in this case because I'm using Ubuntu SO.

**Comment by LonwoLonwo** [comment]
Oh, true.

Then you can download drivers manually and add it in your Connections Settings -> Driver Settings -> Libraries

**Comment by LonwoLonwo** [comment]
Does the manual driver download help in your case?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
