### ISSUE TITLE
Key Pair Authentication to Snowflake Not Working

### ISSUE THREAD

**Issue by st3veh** [dbeaver/dbeaver#22008]
### Description

When I put the public key in Snowflake, and then try to connect in DBeaver, I receive this error: "Private key provided is invalid or not supported: … PBE parameter parsing error: expecting the object identifier for AES cipher."  It seems like DBeaver just can't read files generated by the latest Open SSL versions.  And here: https://www.openssl.org/source/ it says, "All older versions (including 1.1.1, 1.1.0, 1.0.2, 1.0.0 and 0.9.8) are now out of support and should not be used." so, using OpenSSL 1.x.x to generate key files is not sustainable.  Am I doing something wrong, or does DBeaver need to be updated before it can connect to Snowflake using key-pair authentication?

Details:
I have setup my private_key_file and private_key_file_pwd properties in DBeaver as this article directs (seems to be a fairly authoritative on the current process):

https://community.snowflake.com/s/article/Using-Private-Key-authentication-in-DBeaver. It does not specify a particular key file type (*.pem, *.p8), but for encrypted key files it points to this: https://community.snowflake.com/s/article/Private-key-provided-is-invalid-or-not-supported-rsa-key-p8--data-isn-t-an-object-ID, which focuses on *.p8 key files. It says that an error about invalid/not supported private keys is occurring, but has workarounds:
 (1) Encrypt the file with a compatible cipher (PBE-SHA1_RC4-128), or
 (2) Not encrypt the file (-nocrypt), or
 (3) Use a 3rd party crypto library like BouncyCastle to decrypt and encrypt the private keys.

The first two I have tried, but to no avail. (I would much rather have my key files encrypted.) The third one I do not yet know how to implement.

Per these instructions (https://docs.snowflake.com/en/user-guide/key-pair-auth), I am using lines like these to generate my files:

openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -v2 des3 -out rsa_key.p8
openssl rsa -in rsa_key.p8 -pubout -out rsa_key.pub

I have tried using OpenSSL in PowerShell (OpenSSL 3.1.1) and Ubuntu (OpenSSL 3.0.2).
I have tried generating with different ciphers, particularly aes256 (aes-256-cbc) due to the error mentioned above.
I have tried generating files step-by-step with the -traditional flag to generate a header:
1.     Generate a key file:  openssl genrsa -traditional -out rsa_key_pkcs1.pem 2048
2.     Change to AES-256-CBC encryption:  openssl rsa -in rsa_key_pkcs1.pem -aes256 -traditional -out rsa_key_pkcs1_aes.pem
3.     Extract the public key part: openssl rsa -in rsa_key_pkcs1_aes.pem -pubout -out rsa_key_pkcs1_aes.pub
4.     Generate the file in pkcs#8 format:  openssl pkcs8 -topk8 -in rsa_key_pkcs1_aes.pem -traditional -inform PEM -v2 aes256 -out rsa_key_pkcs8_aes.p8

(This generates a header that calls out the object identifier for an AES cipher when generating a *.pem file, but not when generating a *.p8 file)
___
See Snowflake forum discussion:
https://community.snowflake.com/s/question/0D7Do000001HoBcKAK/detail?fromEmail=1&s1oid=00Di0000000hZh2&s1nid=0DB3100000001Fq&s1uid=005Do000002ZkBX&s1ext=0&emkind=chatterCommentNotification&emtm=1697813738923&t=1701118954605

### DBeaver Version

Community Edition 23.2.5.202311191730

### Operating System

MS Windows 11  Version 22H2 (OS Build 22621.2715)

### Database and driver

Snowflake
snowflake-jdbc-3.13.7

### Steps to reproduce

In PowerShell or Ubuntu, generate RSA key files, using lines like:
openssl genrsa 2048 | openssl pkcs8 -topk8 -v2 des3 -inform PEM -out rsa_key.p8
openssl rsa -in rsa_key.p8 -pubout -out rsa_key.pub

In Snowflake, apply the public key using lines like:
USE ROLE accountadmin;
ALTER USER the_user UNSET rsa_public_key;
ALTER USER the_user SET RSA_PUBLIC_KEY='paste contents between the headers from the public rsa key file';
DESCRIBE USER the_user;

In DBeaver, create a Snowflake connection, as specified here:
https://community.snowflake.com/s/article/Using-Private-Key-authentication-in-DBeaver.
So, in Driver properties, create two properties of this form:
private_key_file: /local/path/to/rsa_key.p8
private_key_file_pwd: the_file_password

Then try to connect.  It produces the error, "Private key provided is invalid or not supported: … PBE parameter parsing error: expecting the object identifier for AES cipher."

**Comment by LonwoLonwo** [comment]
Hello @st3veh 

Did you try to change the driver version? You can upgrade it to the latest. Because the 3.13.7 version is old enough.

![2023-11-28 11_24_46-DBeaver 23 1 1 - Employee](https://github.com/dbeaver/dbeaver/assets/45152336/c3bc1478-989f-422c-8301-a26690e17ec0)

**Comment by st3veh** [comment]
LonwoLonwo, Thank you for your response.  I updated to Version 3.14.3 and re-started DBeaver just to make sure, but received the same error message.  
![image](https://github.com/dbeaver/dbeaver/assets/89090911/342d46a6-ce71-408e-a602-d0a12324b359)

**Comment by LonwoLonwo** [comment]
Unfortunately, I do not see what we can do from the DBeaver side. Because DBeaver just uses your driver parameter with connection - he passes it to the driver in the form you gave him without changes. After that, the driver and database are working with parameters.

I see you created many discussions, but maybe you can create one more here? https://github.com/snowflakedb/snowflake-jdbc/issues

**Comment by st3veh** [comment]
Thanks for looking into it.  It helps to know how things operate, and where to follow-up.  I will try creating a discussion in the Snowflake JDBC driver area.

**Comment by st3veh** [comment]
We can close this issue.

**Comment by st3veh** [comment]
Actually, Anastasia (LonwoLonwo), your comment gave me the idea to compare with my successful DBT connection, in case it was using the same driver.  In DBeaver, based on previous posts I was using this in DBeaver:
private_key_file = ${KEY_PATH}
private_key_file_pwd = ${KEY_PPHRASE}

However, in DBT I was using:
private_key_path: '{{ env_var(''KEY_PATH'') }}'
private_key_passphrase: '{{ env_var(''KEY_PPHRASE'') }}'

So, I changed my parameters in DBeaver to be:
private_key_path = ${KEY_PATH}
private_key_file_passphrase = ${KEY_PPHRASE}
Then I got the error that said I was using an incorrect username and password.  (A previous post had said that the password did not matter, since it was not being used anyway.)  Well, after putting in the correct username and password as well, everything started working.  So, it looks like the parameter names have been updated since the posts I was looking at.

Thanks so much for all your help!!

**Comment by LonwoLonwo** [comment]
Thanks for the update @st3veh!

**Comment by st3veh** [comment]
Actually, it looks like when I do what I wrote above, and provide the correct user password, that DBeaver is just doing password authentication, and not key-pair authentication.

If I setup MFA on the account, and provide the correct password, it tries to do the second authentication method in addition to the password.  It is not like when I connect from DBT, Domo, Qlik, or Tableau where the user's password is not required and it does not attempt the MFA method because the private key file and private key file password have been given.

So, I think there must be something that needs to be done in DBeaver to have it use the driver correctly for key-pair authentication.

**Comment by yg-dba** [comment]
When setting up the private key using openssl, you should omit the -v2 des3 from the command (even though the instructions on snowflake have this param).  Then the connection works as expected with dbeaver without any issues.

1. Run the command to generate the private key like this:
openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out rsa_key.p8

2. Save the password used when encrypting the file to use in the dbeaver config

3. Update the public key based on the private key:
openssl rsa -in rsa_key.p8 -pubout -out rsa_key.pub

4. Update the snowflake user to store the public key in the user config
ALTER USER example_user SET RSA_PUBLIC_KEY='MIIBIjANBgkqh..';

5. Add two properties to the Driver Properties tab in dbeaver: 
private_key_file
private_key_file_pwd

**Comment by st3veh** [comment]
yg-dba, I tried the method you described, and removed "-v2 des3" from the openssl p8 line, but I am getting the same behavior.  Does DBeaver ask you to enter your password when you connect?  Are you using the PRO rather than the Community version of DBeaver?  Are you using a very old version of DBeaver?  Any of those could make it work for you when it did not work for me.

**Comment by OsirisDBA** [comment]
I found that if I use `-v2 aes256` then everything works fine.
