### ISSUE TITLE
ORACLE: dbms_output not print

### ISSUE THREAD

**Issue by sykyman** [dbeaver/dbeaver#22005]
### Description

When i use dbms_output.put_line, No text is printed to Server output up to next sql operation. 
When I execute with running Panel Server output, no text is printed
`BEGIN
	dbms_output.put_line('HELO WORLD');
END;`

when i, after that, execute for example 
`SELECT * FROM dual;`
The text "HELO WORLD" is printed to Output

### DBeaver Version

Comunity 23.2.5.202311191730

### Operating System

Win 10

### Database and driver

Driver Oracle JDBC driver 12.2.0.1.0

### Steps to reproduce

1. Create simple block with dbms_ouput 
BEGIN
	dbms_output.put_line('HELO WORLD');
END;
2. Open panel Server output
3. execute block
4. swithh to Output - no text printed
5. execute for example select 1 from dual;
6. swithh to Output - HELLo WORLD printed

**Comment by Ryoka** [comment]
There is a similar problem with Output window when working with PostgreSQL in DBeaver 23.2.5. 
Any RAISE NOTICE, RAISE WARNING commands may or may not yield anything in the Output window. It's totally random, I'd say.
I believe the output in the Output window is broken in 23.2.5, and it's not related to a particular database. This is a critical bug, I had to rollback to 23.2.4 which does not have any issues with the Output window.

By the way, scrolling the Objects Tree in Database Navigator is VERY slow in 23.2.5 compared to 23.2.4 (on MacOS 14.1.1). This looks like a different issue, though.

**Comment by sykyman** [comment]
Thank you @Ryoka. It seems to be the same problem. After rollback version to 23.2.4 it is OK.

**Comment by LonwoLonwo** [comment]
Hello and thanks for the bug report.
The issue fixed here: https://github.com/dbeaver/dbeaver/issues/21902
And will be available in the next release.
Or you can check our Early Access version: https://dbeaver.io/files/ea/
