### ISSUE TITLE
[SQL Server] Select into statement causes dbeaver frozen | autocompletion enabled

### ISSUE THREAD

**Issue by StevenLiuCanton** [dbeaver/dbeaver#22010]
### Description

I try to run select * into [newTable] from [oldTable]. When moving the cursor to [newTable] and typing the new table's name, dbeaver became unresponsive. It maybe something related to auto-completion feature. 

### DBeaver Version

Community Edition 23.2.5

### Operating System

Windows 10

### Database and driver

Microsoft JDBC Driver for SQL Server (MSSQL)

**Comment by LonwoLonwo** [comment]
Hello @StevenLiuCanton 

Could you please try to generate a thread dump and attach it here? Here is the instruction: https://dbeaver.com/docs/wiki/Making-a-thread-dump/
Thank you.

**Comment by StevenLiuCanton** [comment]
[thread-dump-6864.txt](https://github.com/dbeaver/dbeaver/files/13519003/thread-dump-6864.txt)
[frozen_window.txt](https://github.com/dbeaver/dbeaver/files/13540724/frozen_window.txt)

Sorry for late feedback. Above is the dump file.

**Comment by E1izabeth** [comment]
Thank you.

**Comment by E1izabeth** [comment]
The issue was solved in DBeaver 23.3.1
