### ISSUE TITLE
Can't use inline editor with ORACLE connection if I set the table and not the owner.table

### ISSUE THREAD

**Issue by fedeolivera1** [dbeaver/dbeaver#22017]
### Description

Only way to get the inline editor to work (grid editing), is to set the owner adead of the table name. If I only set the table name (eg SELECT * FROM table;) I can't edit.
I have NO readonly connection.
Can you tell me if this is a bug, and if not, how to set this owner to connection or elsewhere, to be automatically set when I write a table name in the sql editor?
Thanks!

### DBeaver Version

Community Edition 23.2.5.202311191730

### Operating System

Windows 11

### Database and driver

oracle.jdbc.OracleDriver

**Comment by LonwoLonwo** [comment]
Hello @fedeolivera1 

Can you please provide footage showing your issue? Thank you.

**Comment by fedeolivera1** [comment]
Without setting the owner ahead of the table name:

![no_owner](https://github.com/dbeaver/dbeaver/assets/28544882/bebe17ef-7998-4eaa-aa2b-be6cde69ff0f)

Setting the owner ahead of the table:

![with_owner](https://github.com/dbeaver/dbeaver/assets/28544882/968aa4ae-a8b4-4cf5-9148-baf0658e52f2)

**Comment by LonwoLonwo** [comment]
Did you specify the default schema for your script? Or is it "N/A"?

![2023-11-28 18_07_12-DBeaver Ultimate 23 3 0 - _Oracle - orcl_ Script-46](https://github.com/dbeaver/dbeaver/assets/45152336/7de08773-21a5-4928-9655-037e7d382541)

**Comment by fedeolivera1** [comment]
Active catalog/schema IS provided...

**Comment by LonwoLonwo** [comment]
Could you observe your table from your query in the navigator tree?

**Comment by fedeolivera1** [comment]
Yes I can, ctrl + click takes me to the properties of the table, being with or without the owner ahead.

**Comment by LonwoLonwo** [comment]
Usually if the full table is read-only we have another status. I see on your picture, that only the specific column has read-only status. Could you please provide your query? And table DDL.

**Comment by fedeolivera1** [comment]
The query is a simple SELECT * FROM LINEAS_ARCHIVO ;
To get the inline editor to work: SELECT * FROM OWNTEST.LINEAS_ARCHIVO;

DDL:

CREATE TABLE OWNTEST.LINEAS_ARCHIVO (
	ID_ARCHIVO_LINEA NUMBER(9,0),
	ID_ARCHIVO NUMBER(4,0),
	MES_CARGO NUMBER(6,0),
	CONSTRAINT LA_PK PRIMARY KEY (ID_ARCHIVO_LINEA),
	CONSTRAINT SYS_C00120567 CHECK ("ID_ARCHIVO_LINEA" IS NOT NULL),
);
CREATE UNIQUE INDEX LA_PK ON OWNTEST.LINEAS_ARCHIVO (ID_ARCHIVO_LINEA);

**Comment by LonwoLonwo** [comment]
Still can not reproduce.

![2023-11-29 10_47_20-DBeaver Ultimate 23 3 0 - _Oracle - orcl_ Script-46](https://github.com/dbeaver/dbeaver/assets/45152336/df619e18-5878-49eb-8092-a7ade1cca8de)

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by fedeolivera1** [comment]
Im working with several databases and schemas. There is a clear error, and it's not new, since there are reports from years with this issue. Some people fixes them via refreshing the tables (in the left pane as it seems). In my case, I have another database that will not update inline the records (not even with the owner ahead of the table) that are already set (were previously inserted), but will update if I insert one inline. 
The schema will not show the tables nor any info in some cases (in the left pane). Its a weird behaviour.
It is a common problem as it seems. But there has not been fixed. 
I really wanted to use this db tool.

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here, and we haven't managed to reproduce the issue or understand the issue roots. If the issue is still actual please let me know and provide the log files and additional information to reproduce.
