### ISSUE TITLE
Correct HTML format on "Copy SQL as source code". Less and greater than symbols.

### ISSUE THREAD

**Issue by rasputino** [dbeaver/dbeaver#22027]
**Problem**
Some times we need to copy the source code of a query in a ticket platform (OsTicket) that only support HTML, so we use the HTML format of "Copy SQL as source code" often. The problem is that the < and > symbols aren't formatted correctly.

For example, if we have the SQL sentence:

    select * from table where id <> 10;

Is copied as:

    <pre><span style='color:#739eca;font-weight:bold;'>select</span> * <span style='color:#739eca;font-weight:bold;'>from</span><span style='color:#739eca;font-weight:bold;'>table</span> <span style='color:#739eca;font-weight:bold;'>where</span> <span style='color:#9e9e9e;'>id</span> <> <span style='color:#c0c0c0;'>10</span><span style='color:#eecc64;'>;</span></pre>

And that is showed as:
![image](https://github.com/dbeaver/dbeaver/assets/2887216/c35ef4ea-9db6-4979-9740-cd018e8fd501)

Where the `<>` symbols are lost.

**Solution**
To replace the symbols `<>` with `&lt; &gt;` HTML character entities in the HTML format on "Copy SQL as source code".

**Comment by LonwoLonwo** [comment]
Hello @rasputino 

Thanks for the report.

![2023-11-29 13_01_22-Correct HTML format on _Copy SQL as source code_  Less and greater than symbols](https://github.com/dbeaver/dbeaver/assets/45152336/5298d880-6d78-4649-b723-68fb527e3b2c)
