### ISSUE TITLE
Shell сommand "Before Connect" not terminates then connection failed

### ISSUE THREAD

**Issue by jskvoll** [dbeaver/dbeaver#22020]
### Description

I expect, if connection failed then `Connection settings -> Shell Commands -> Before Connect` shell script should be automatically terminated.

But unfortunately the script is still running, and there is no way to interrupt it.

### DBeaver Version

Community Edition 23.2.5

### Operating System

macOS 13.3.1

### Database and driver

PostgreSQL - any

### Steps to reproduce

1. Create posgrtess connection with default configuration
![image](https://github.com/dbeaver/dbeaver/assets/1451730/4b1b547f-a8bf-4de3-8c61-52e745b138d4)

2. Edit that connection and go to `Connection settings -> Shell Commands -> Before Connect` and set and shell cmomand, which should work until terminated, for instance `ping 8.8.8.8` and set `Terminate process at disconnect` to enabled.
![image](https://github.com/dbeaver/dbeaver/assets/1451730/feadfbf4-2a07-4520-ae45-8eece81a2d77)

3. Try to connect. Connection error should be shown, but script still running
![image](https://github.com/dbeaver/dbeaver/assets/1451730/7c3f9a5a-4db7-42bc-8b67-3a16937c5aa4)

### Additional context

Also unable to terminate processes via "Background tasks" panel

![image](https://github.com/dbeaver/dbeaver/assets/1451730/58142d14-24e6-47a8-8b7a-de9416ffb26f)

**Comment by Destrolaric** [comment]
@jskvoll As a workaround, MacOS's ping is continuous if not specified otherwise. Can you try to add ping count for it to stop continuously pinging?

>    -c count   Stop after sending (and receiving) count ECHO_RESPONSE packets.
>               If this option is not specified, ping will operate until interrupted.
>               If this option is specified in conjunction with ping sweeps, each sweep will consist of count packets.

**Comment by Destrolaric** [comment]
Confirmed, thank you for report

**Comment by jskvoll** [comment]
> @jskvoll As a workaround, MacOS's ping is continuous if not specified otherwise. Can you try to add ping count for it to stop continuously pinging?
> 
> > -c count   Stop after sending (and receiving) count ECHO_RESPONSE packets.
> > If this option is not specified, ping will operate until interrupted.
> > If this option is specified in conjunction with ping sweeps, each sweep will consist of count packets.

Thank you for response! Ping was presented only for simple example, i detect this issue with my own script
