### ISSUE TITLE
import csv file error

### ISSUE THREAD

**Issue by jgrover21** [dbeaver/dbeaver#22022]
### Description

trying to import csv file..it creates columnnames but not data.  it gives error msg Error occurred during batch insert
(you can disable batch insert in order to skip particular rows).

Reason:
SQL Error [22001]: Batch entry 47 INSERT INTO dhc.lookup_mastercodes ("Inpatient_icd10_procedure_code","Outpatient_icd10_procedure_code",icd10_diagnosis_code,icd09_code,hcpcs_cpt_codes,drg_codes,codeset,subset,"Description","PCI_Category","DHC_PCI_Category",no_of_vessels,des,stent,sub_type,category,atherectomy,"Impeller",left_main,inferior_anterior,"STEMI","CABG",vt_ablation,"Cardiomyopathy","Myocarditis","CAD","DRG","Angina","Heart_Transplant","Classification","Comorbidity_dx_codes","Right_Heart_Cath-PA_Cath",rhf,heart_failure_rhf,status,validity,"HFpEF _HFrEF","Cardiac_Sugery_Codes","Acute_Coronary_Syndrom","Acute_Kidney_Incident","Chronic_Kidney_Disease","Pulmonary_Embolism","Cardiogenic_shock","Extracorporeal_Membrane_Oxygenation","Assistance_with_Respiratory_Ventilation","Intra-aortic_Baloon_Pump","Structural_heart","Surgical_Aortic_Valve_Replacement",cto_crt,"Pediatrics","Tricuspid_Codes","Bleeding_Transfusion","Shockwave","History_of_PCI_Vasc_Implant_CAB","Respiratory","CentrimagTandemHeart","Cirrhosis","Parkinson's_disease","Dementia","Emphysema","Chronic_obstructive_pulmonary_disease","Hx_of_Stroke","Peripheral_vascular_disease","Lung_Transplant")
	VALUES ('','92938','','','','','','','Percutaneous transluminal revascularization of or through coronary artery bypass graft (internal mammary, free arterial, venous), any combination of intracoronary stent, atherectomy and angioplasty, including distal protection when performed; each additional branch subtended by the bypass graft (List separately in addition to code for primary procedure)','','Outpatient','Multiple','','','','','Atherectomy','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','') was aborted: ERROR: value too long for type character varying(256)  Call getNextException to see other errors in the batch

### DBeaver Version

22.1.0

### Operating System

windows

### Database and driver

postgresql 14.0

### Steps to reproduce

import csv file using import data from menu

**Comment by ShadelessFox** [comment]
Hello @jgrover21,

According to the error message, you have a column limited to 256 characters, but the data you're trying to import is longer.

Have you tried adjusting the sample row count or minimum column length?

![image](https://github.com/dbeaver/dbeaver/assets/35821147/afbb1a65-db4c-4d62-a7af-9befeb0d7e16)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
