### ISSUE TITLE
Create so many sessions in google cloud spanner.

### ISSUE THREAD

**Issue by aousee** [dbeaver/dbeaver#22024]
### Description

After stopping all Spanner connections in the development environment, I temporarily suspend the Google Cloud service account to reduce all connections to zero. Then, when only DBeaver is run, approximately 10,000 connections occur (this is an estimate).

![image](https://github.com/dbeaver/dbeaver/assets/78615811/2873d8f6-21b8-4e92-9d19-9fb91a90a1a7)

I tried changing the settings as follows, but it was ineffective.
![image](https://github.com/dbeaver/dbeaver/assets/78615811/00de320f-afe7-4fd0-9614-57472358ab75)

### DBeaver Version

23.2.5.202311191730

### Operating System

Windows 10 Pro

### Database and driver

Google Cloud Spanner
google-cloud-spanner--jdbc-2.7.4.jar

**Comment by LonwoLonwo** [comment]
Hello @aousee 

Could you please try to upgrade your driver version to the latest and try again?

You can do it in your connection settings:

![2023-11-29 10_51_01-DBeaver Ultimate 23 3 0 - _Oracle - orcl_ Script-46](https://github.com/dbeaver/dbeaver/assets/45152336/ac97bfff-0ea1-4ab1-8b7f-e5d15d0aa3ad)

**Comment by serge-rider** [comment]
@aousee single DBeaver client cannot produce that many connections. If fact it is not clear what is your use-case.

`SELECT 1` is a "ping" query, it is used by DBeaver to determine that connection is still alive (you can turn this feature off in the connection settings dialog).
Potentially it is possible that client's keep-alive was configured to run this check every second.

**Comment by aousee** [comment]
@LonwoLonwo @serge-rider 

Yes, DBeaver does not create many connections. Although this issue is not directly related, I would like to share some points from my experience that may help others.
When connecting to Spanner, Spanner creates a session and seems to avoid deleting it as much as possible. (Based on tests, it appears that sessions are maintained even if connections within a session become invalid)
Given the nature of the development environment, server instances are frequently restarted, leading to the accumulation of sessions.
I resolved this issue by setting the server instances to delete unused sessions after one hour at the start of the instance

``` cs
public static class SpannerSessionUtility
{
    public class SQLEndPoint
    {
        public string Credential; // Google Cloud Service Account key file path
        public string URI; 
        public int SessionLifetime = 60;
    }

    public static async void Clear(SQLEndPoint db)
    {
        GoogleCredential credential = ServerManager.GoogleCredential;
        if (string.IsNullOrEmpty(db.Credential) == false)
        {
            credential = GoogleCredential.FromFile(db.Credential);
        }

        var cr = credential.CreateScoped(
            "https://www.googleapis.com/auth/cloud-platform", 
            "https://www.googleapis.com/auth/spanner.data");

        var accessToken = await (cr as ITokenAccess).GetAccessTokenForRequestAsync();
        var apiKey = "Google Cloud API Key"; // please input apikey
        var uri = db.URI;

        Doc doc = null;

        using (var client = new HttpClient())
        {
            string url = $"https://spanner.googleapis.com/v1/{uri}/sessions?key={apiKey}";
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = await client.GetAsync(url);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                doc = JsonConvert.DeserializeObject<Doc>(content);
            }
            else
            {
                Log.Warn($"스패너 세션 목록 조회 실패 : {response.StatusCode}");
            }
        }

        if (null == doc || null == doc.sessions)
        {
            Log.Debug("스패너 세션 없음");
            return;
        }

        foreach (var ses in doc.sessions!)
        {
            var diff = ses.approximateLastUseTime - ses.createTime;
            if (diff!.Value.TotalMinutes < 60)
            {
                Log.Debug($"스패너 세션 유지 : {ses.name} {diff.Value.TotalMinutes}분 경과");
                continue;
            }

            using (var client = new HttpClient())
            {
                string url = $"https://spanner.googleapis.com/v1/{ses.name}/?key={apiKey}";
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await client.DeleteAsync(url);
                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    Log.Debug($"스패너 세션 삭제 : {ses.name} {diff.Value.TotalMinutes}분 경과");
                }
                else
                {
                    Log.Warn($"스패너 세션 삭제 실패 : {response.StatusCode}");
                }
            }

            await Task.Delay(300);
        }        
    }

    public class Doc
    {
        public List<Session> sessions;
    }

    public class Session
    {
        public string name;
        public DateTime? createTime;
        public DateTime? approximateLastUseTime;
    }
}
```

**Comment by LonwoLonwo** [comment]
Thanks for the detailed explanation @aousee
