### ISSUE TITLE
Support ed25519 private keys for ssh tunnel

### ISSUE THREAD

**Issue by zman0900** [dbeaver/dbeaver#2202]
Attempting to use an ed25519 private key for an ssh tunnel just results in the error `com.jcraft.jsch.JSchException: invalid privatekey`.  The same works fine with an rsa key.

**Comment by serge-rider** [comment]
JSch (Java SSH client) doesn't support this.
There is a quite old feature request for ed25519 support (https://sourceforge.net/p/jsch/feature-requests/7/) but there is no any activity.

Perhaps we should replace SSH client with something more alive (e.g. https://github.com/hierynomus/sshj)

**Comment by zmirc** [comment]
+1

**Comment by dylanharty** [comment]
The OpenSSH server for windows 10 currently only supports ed25519 key exchange. This key exchange should be supported. As mentioned  [https://github.com/hierynomus/sshj](https://github.com/hierynomus/sshj) supports it and is active. 

+1

**Comment by serge-rider** [comment]
SSHJ extension will be published here - https://dbeaver.jkiss.org/update/sshj/

**Comment by tutaidalal** [comment]
Is there any update for ed25519  support in JSCH ?

**Comment by mstud** [comment]
Why has this been closed? The issue is still present. ed25519 is *the* key cipher going forward from now, and not supporting this is a major blocker for us. What happened to the plans of switchting to sshj if JSCH still doesn't support this?

**Comment by krilim** [comment]
Any updates on this? Need ed25519 support also.
