### ISSUE TITLE
Crash while expanding connection to netbios accdb file using UCanAccess driver

### ISSUE THREAD

**Issue by aviennas** [dbeaver/dbeaver#22030]
### Description

Having worked on a network located .accdb Access DB file via DBeaver Eclipse plugin, 

for several days I was working without a problem, suddenly I get the following crash when I expand the connection to browse the objects
```
UCAExc:::5.0.1 newPosition < 0: (-3776 < 0)
  newPosition < 0: (-3776 < 0)
  newPosition < 0: (-3776 < 0)
```
I have not applied any updates in Eclipse ever since
Do you think this is a UCanAccess bug or a DBeaver one?

### DBeaver Version

23.2.4.202311051706

### Operating System

Windows 11 Pro

### Database and driver

Database: **MS Access 365**
Driver Version: has to be **5.0.1** 

### Steps to reproduce

trying to expand connection

### Additional context

Using Eclipse IDE (2023-09 for Java Devs) plugin
```
Version: 2023-09 (4.29.0)
Build id: 20230907-1323
```

**Comment by LonwoLonwo** [comment]
Hello @aviennas 

We have the release version in our code: `maven:/net.sf.ucanaccess:ucanaccess:RELEASE`

But no Updates for this driver since 2021. 

What if you will create a new connection for your file? Will it be the connection still broken?

**Comment by aviennas** [comment]
Hello @LonwoLonwo! Thank you for the quick reply! A new connection did not fix the issue however repairing the Access ACCDB file via the relevant action button on the Access menu, did fix the problem. From a black box approach It looks like a minor corruption issue on the db file I guess.

**Comment by LonwoLonwo** [comment]
Thanks for the update @aviennas
