### ISSUE TITLE
Version 23.2.5 lost ability to show postgres raise notice messages

### ISSUE THREAD

**Issue by AndreyShvidky** [dbeaver/dbeaver#22031]
### Description

Version 23.2.4 works fine.

### DBeaver Version

23.2.5

### Operating System

Windows 10

### Database and driver

PostgreSQL 16.0 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

### Steps to reproduce

do
$$
declare
input_data text = 'test';
begin
raise notice 'input_data = %', input_data;
end
$$
;

**Comment by LonwoLonwo** [comment]
Hello, and thanks for the bug report.
The issue is fixed here: https://github.com/dbeaver/dbeaver/issues/21902
And will be available in the next release.
Or you can check our Early Access version: https://dbeaver.io/files/ea/
