### ISSUE TITLE
Error compiling procedure in Oracle on DBeaver 23.2.5

### ISSUE THREAD

**Issue by Htr-DbvFo** [dbeaver/dbeaver#22034]
### Description

Hello all, I updated to version 23.2.5 and I cant create or replace procedure

The error is:
"SQL Error [900] [42000]: ORA-00900: sentencia SQL no válida
  Error : 900, Position : 0, Sql = nmVar2  NUMBER, OriginalSql = nmVar2  NUMBER, Error Msg = ORA-00900: sentencia SQL no válida
  ORA-00900: sentencia SQL no válida "

### DBeaver Version

Community Edtion 23.2.5

### Operating System

Windows 10

### Database and driver

Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0
JDBC Thin Client 19.0.0

### Steps to reproduce

I am creating or recreating a procedure, like this:

CREATE OR replace PROCEDURE Prueba_Dbeaver()
/**************** 
 * comentarios
 *****************/
  nmVar1  NUMBER:=0;
  nmVar2  NUMBER;
  dtHoy   DATE;
BEGIN
  SELECT   sysdate 
  INTO  dtHoy
  FROM dual;
END Prueba_Dbeaver;

The error is generated by the assignment of value to the variable nmVal1 in its declaration; before the "Begin" start of the code; When removing the assignment, the procedure compiles without errors. 

### Additional context

If the assignment or initialization of the variable is done after the "Begin", no error is generated.

**Comment by LonwoLonwo** [comment]
Hello @Htr-DbvFo 

Could you please check the latest Early Access version? Maybe the issue is already fixed there. https://dbeaver.io/files/ea/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by Htr-DbvFo** [comment]
Hello Anastasiya, I have tried the version you mentioned and it works correctly again. Thank you so much!


Enviado desde Yahoo Mail para iPhone


El lunes, diciembre 25, 2023, 3:55 a.m., Elizabeth ***@***.***> escribió:




It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
