### ISSUE TITLE
Error compiling procedure SAP IQ on 23.2.5

### ISSUE THREAD

**Issue by Obyzzz** [dbeaver/dbeaver#22032]
### Description

Hello all, I updated to version 23.2.5 and I cant create or replace procedures like this code example
**__CREATE OR replace PROCEDURE SP_TEST_OBYZ()
BEGIN
SELECT 
CASE
	WHEN xxx = 1 THEN 'ooo'
END AS uuu
FROM xxxxxxx a right JOIN yyyyyy b ON a.aaaa = b.bbbb;
END_**

The error is:
SQL Error [102] [42W04]: SQL Anywhere Error -131: Syntax error near '(end of line)' on line 7 (Watcom SQL)

Deleting ; will work and the problem occurs when a case statement appears. Downgrading to previous version 23.2.4 solves the problem.

Thank you very much.

### DBeaver Version

23.2.5

### Operating System

Windows 10 Pro

### Database and driver

SAP IQ 16.1 (using jconnect 4.2 and another versions)

### Steps to reproduce

Executing this code:
**__CREATE OR replace PROCEDURE SP_TEST_OBYZ()
BEGIN
SELECT 
CASE
	WHEN xxx = 1 THEN 'ooo'
END AS uuu
FROM xxxxxxx a right JOIN yyyyyy b ON a.aaaa = b.bbbb;
END_**

**Comment by LonwoLonwo** [comment]
Hello @Obyzzz 

Could you please check the latest Early Access version? Maybe the issue is already fixed there. https://dbeaver.io/files/ea/

**Comment by Obyzzz** [comment]
> https://dbeaver.io/files/ea/
Hello @LonwoLonwo 
I have tried the version you mentioned and it works correctly again. Thank you so much!

**Comment by LonwoLonwo** [comment]
Thanks for the update @Obyzzz
