### ISSUE TITLE
[SQL Server] Error When Executing TSQL with Variables

### ISSUE THREAD

**Issue by pamadden-clgx** [dbeaver/dbeaver#22035]
### Description

When executing script with variables and terminating statements with semi-colon, the following error occurs:

`SQL Error [137] [S0001]: Must declare the scalar variable "@<variable_name>"`

_NOTES:
Scripts execute successfully when removing semi-colon line terminators.
This bug first appeared in version 23.2.5. The error did not occur in version Version 23.2.4._

### DBeaver Version

Community Edition 23.2.5.202311191730

### Operating System

Windows 10 Pro

### Database and driver

Database:  Microsoft SQL Server 2012 (SP4) (KB4018073) - 11.0.7001.0 (X64) 
Driver:  Microsoft JDBC Driver for SQL Server (mssql-jdbc-9.2.0.jre8.jar, mssql-jdbc_auth-9.2.0.x64.dll) 

### Steps to reproduce

This code will throw the error:

```
DECLARE @t varchar(10);
SET @t = 'foobar';
SELECT @t;
```

### Additional context

This code will succeed:

```
DECLARE @t varchar(10)
SET @t = 'foobar'
SELECT @t;
```

**Comment by LonwoLonwo** [comment]
Hello @pamadden-clgx 

Could you please check the latest Early Access version? Maybe the issue is already fixed there. https://dbeaver.io/files/ea/

**Comment by pamadden-clgx** [comment]
@LonwoLonwo Thank you! This issue has been corrected in the following version:

Version 23.2.5.202311300914
Release Date:  November 20, 2023

I will close this issue.

**Comment by LonwoLonwo** [comment]
Thanks for the update.
