### ISSUE TITLE
SQLEditor sends select query to PostgresSQL  in transaction-error state 2 times

### ISSUE THREAD

**Issue by valerysvl** [dbeaver/dbeaver#22044]
### Description

SQLEditor sends select query to PostgresSQL  in transaction-error state 2 times

### DBeaver Version

Comminity Edition 23.2.5

### Operating System

Windows 11

### Database and driver

Database: PostgreSQL 12
Driver: 

### Steps to reproduce

1. Connect to PostgreSQL
2. Create any table, say 'test1', and insert couple records into it
3. Open new SQLEditor window
4. Execute 1st query: begin transaction;
5. Execute 2nd query to make transaction into error state: select * from test2; 
5.1. You will get error about absence of test2 and postgres transaction state will become E (error)
6. Run tcpdump (or anything you like) to trace the connection to postgres: tcpdump -X port 5432
7. Execute 3rd query: select * from test1
8. Trace will show  'select * from test1' is sent to postgres 2 times

**Comment by hrimthrusa** [comment]
@valerysvl Hi,

Am I looking at the right thing? This is what I've got in my _ftp.txt_ after tinkering with **pktmon**.
![image](https://github.com/dbeaver/dbeaver/assets/97725836/f64cca19-a780-4f08-a523-e7969ed3771b)

And what seems to be a problem after all?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
