### ISSUE TITLE
Unable to upgrade from version 23.0.2 to latest version

### ISSUE THREAD

**Issue by hafizan2109** [dbeaver/dbeaver#22043]
### Description

I have performed version upgrade from current version using both auto upgrade and download the installer itself but unable to upgrade to the latest version.
![image](https://github.com/dbeaver/dbeaver/assets/46272579/27eed601-98e5-495f-9fad-c92802acebf2)

I have tried multiple times on different days and still failed. After DBeaver restarted, it maintains in the version 23.0.2

Any other way to solve this other than uninstalling and reinstall again? 

### DBeaver Version

 23.0.2

### Operating System

Windows 11

### Steps to reproduce

1. I try to upgrade
2. Follow the steps to upgrade to latest version
3. Upgrade successful
4. After DBeaver restarts, it remain in old version

**Comment by LonwoLonwo** [comment]
Hello @hafizan2109 

DBeaver can have two versions on your computer. For all users and for the current user. They are located usually in different places. Are you sure, that you are opening the updated DBeaver version?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
