### ISSUE TITLE
Table import/export creating connection to destination database too early

### ISSUE THREAD

**Issue by battmush** [dbeaver/dbeaver#22054]
### Description

When using the table import/export tools using the "Database table" method, destination connection can idle out prior to data transfer for large or slow sources.  In our case, we have some large tables that can take several days to load from the source DB, and by the time it goes to write to the destination DB it has closed the connection due to idle timeout.  This does not occur for smaller/faster tables.

Logfile attached.
[dbeaver-table-copy.log](https://github.com/dbeaver/dbeaver/files/13515405/dbeaver-table-copy.log)

### DBeaver Version

Community Edition 23.2.5

### Operating System

CentOS 8 x86_64, MacOS 14, Windows 11

### Database and driver

Source database: DB2 for iSeries (driver: jt400-20.0.6.jar)
Destination database: Postgres 15.4 (driver: postgresql-42.5.2.jar)

### Steps to reproduce

1. Connect to source database
2. Find the source table to export and select Export Data from context menu
3. Select 'Database table(s)' as the export type
4. Select the destination database, accepting all defaults on mappings
5. Accept default Extraction settings
6. Set the Data Load Settings: using defaults, or any combination of 'Use bulk load', 'Open new connections', or commit sizes.
7. Select 'Proceed'

### Additional context

It appears that there would be at first blush two approaches to resolving this:
1. Not open the destination datasource connection until data is ready to be imported
2. Check connection health and reestablish connection when ready to import

As you can see from that attached log fragment, we're talking an almost 4 day export time from the source database, so messing with timeout settings on the destination datasource don't really make sense.

**Comment by iraidaa** [comment]
Hi @battmush,

Thank you for your report.

Have you tried editing the **Keep-Alive** setting in the Connection wizard of the destination database?

![image](https://github.com/dbeaver/dbeaver/assets/49681450/7ab35dab-94a2-41e1-9849-eda105d53ef8)

Can you add additional driver properties? For example, **connectTimeout** and **socketTimeout**. These are socket timeouts, and their max values can be 2147484 in sec.

Please take a look at the documentation https://jdbc.postgresql.org/documentation/use/.

Here in this tab 
![image](https://github.com/dbeaver/dbeaver/assets/49681450/f3f47a2c-fbbc-499c-8be8-0ef8ffdb9366)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
