### ISSUE TITLE
restore unsaved sql queries after restart

### ISSUE THREAD

**Issue by vindex10** [dbeaver/dbeaver#22058]
Hi! I'm looking for an option to be able to restore sql query editor tab contents across restarts.

The use case is simple, and can intuitively be connected to how people may use browser tabs. You open a tab, then get distracted, and then you come back.

Similar with query tabs, if I work on a project for few days, I'd like to be able to come back to the old buffer after a few days if the tab is still open. If it is closed, I don't need the query to be preserved.

I'm thinking of it as a temporary file attach to the currently open tab which survives restarts, but is removed when tab is closed.

I'm sorry if such issue was raised before, I tried to search for similar requests and didn't find any.

**Comment by Destrolaric** [comment]
You can try enabling script autosaving. This will help you to avoid losing SQL queries

![Image](https://github.com/dbeaver/dbeaver/assets/20579256/e9f566e3-98bf-444b-bfc0-ccfa700cf00f)

**Comment by vindex10** [comment]
@Destrolaric thanks for your answer. 

It worked for me in this configuration:

![image](https://github.com/dbeaver/dbeaver/assets/1962652/b675606d-3efa-4038-b75e-422bee84296c)

Thank you for your work! This is amazing product!

(updated, I tried wrong configuration)
