### ISSUE TITLE
Export of a large table cause DBeaver to crash

### ISSUE THREAD

**Issue by maksiplus19** [dbeaver/dbeaver#22056]
### Description

I have two databases local in docker and remote one. I need to upload large 102GB table from local to remote db. When I try to export this table beaver fetches row count, starts to fetch data and freezes after several second. Docker stats shows 100% usage of cpu while fetching rows then it drops to 0. Mean while dbeaver starts to consume 800+% of cpu, runs for about 2 min, freeze and then been killed by system I guess

I tried different settings, set java memory limit up to 4gb (caught some java heap error during all this) but it still freezes.

Before this I've uploaded a 1.4GB table and worked fine.

<img width="1000" alt="Снимок экрана 2023-12-01 в 02 23 26" src="https://github.com/dbeaver/dbeaver/assets/36230039/7aec717a-67b5-4907-a4f3-1618e2ee3a78">
<img width="1512" alt="Снимок экрана 2023-12-01 в 02 22 17" src="https://github.com/dbeaver/dbeaver/assets/36230039/80163e7b-394f-4c37-93f6-82839fc2a078">

Export settings

<img width="334" alt="Снимок экрана 2023-12-01 в 02 43 30" src="https://github.com/dbeaver/dbeaver/assets/36230039/a72fb233-0549-4f16-ad20-176f4568317e">

<img width="623" alt="Снимок экрана 2023-12-01 в 02 43 39" src="https://github.com/dbeaver/dbeaver/assets/36230039/d469f0bf-2da7-40bb-a382-b58f5efb6ab8">

### DBeaver Version

23.2.5

### Operating System

macOS 14.1.2

### Database and driver

Posgres 16 (postgres:16.0-alpine)

### Steps to reproduce

1. Create a big table
2. Try to export it to another database

**Comment by E1izabeth** [comment]
Could you try to decrease `Fetch size` setting?

**Comment by maksiplus19** [comment]
@E1izabeth 
Hi. I've already updated to DBeaver 23.3.0. Tried 1000, 100, 10 and even 1 and it still crashes.

**Comment by LonwoLonwo** [comment]
Hello @maksiplus19 

Could you please generate a thread dump when DBeaver consumes all resources and attach it here? Here are the instructions: 
https://dbeaver.com/docs/wiki/Making-a-thread-dump/
Thank you.

**Comment by Destrolaric** [comment]
@maksiplus19 Am I correct that during the export docker container doesn't get processor time due to DBeaver using 100% of all cores?

**Comment by maksiplus19** [comment]
@LonwoLonwo 
First time got error `1410: Unable to open socket file /var/folders/83/pg8py7jd7bb26dz46vq_tz1w0000gp/T/.java_pid1410: target process 1410 doesn't respond within 10500ms or HotSpot VM not loaded`. Got dump in second time 
[dbeaver-thread-dump.txt](https://github.com/dbeaver/dbeaver/files/13749207/dbeaver-thread-dump.txt)

**Comment by maksiplus19** [comment]
@Destrolaric I don't think so. In postgres logs looks like dbeaver starts to do something and looses a connection to db
`2023-12-22 06:51:19.608 UTC [44] STATEMENT:  SELECT * FROM cmdm.rpt_inguru_order_notification
06:51:19.609 UTC [44] FATAL:  connection to client lost`

**Comment by Destrolaric** [comment]
Hi, could you provide screenshots of your data transfer configuration?

**Comment by wesshaw** [comment]
@Destrolaric @E1izabeth his export settings are in the original message.  Can we continue this investigation?  I'm having the same issue.

**Comment by wesshaw** [comment]
Increasing the java heap size fixed my crash.

**Comment by Destrolaric** [comment]
@maksiplus19 Hi, it looks like DBeaver has more process priority than Docker, which leads to taking an entire available CPU power. Could you see if DBeaver has a high process priority?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
