### ISSUE TITLE
Column widths no longer fit column names in grid display

### ISSUE THREAD

**Issue by leeford73** [dbeaver/dbeaver#22053]
### Description

In our latest update of 23.2.5 the settings for the grid display of the results have changed and I cannot find how to change them back.  Now, they no longer fit either the value in the column or the column names, making it incredibly difficult to read the results without right clicking and setting the window to fit values, but it still will not fit the column names.  How do I get these settings back?  In addition, when running a query that has a syntax error of some sort, the error no longer appears in the server output, but only in the execution log.  Can I get the error to appear in the server output panel again?
Thank you

### DBeaver Version

Community Edition 23.2.5

### Operating System

Windows 11

### Database and driver

Database:  MySQL 5.7.43-47
Driver:  MySQL

### Steps to reproduce

Running any query with long column names and/or values that are many characters long will generate a result window that displays the results in a grid and the columns are set to a specific width that no longer expands to fit the values or the column names unless I manually right click the window and explicitly select to fit to values, but there isn't an option to expand to fit the column names.
The other issue is that when I run a query  with a syntax error, previous versions would show the error in the server output panel.  This no longer happens.  In fact, nothing appears in the Server Output panel when I run a query.  The only way to determine if there was an error is to have the Execution Log panel open and check it when I run a query.

### Additional context

I feel like these are probably  configuration settings that I need to change back, but I cannot find any documentation that covers how to change these settings back.

**Comment by LonwoLonwo** [comment]
Hello @leeford73 

The second case is already fixed here: https://github.com/dbeaver/dbeaver/issues/21902 
And fix will be available with the next release (on Monday).

And about the main issue. Could you please provide some footage?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
