### ISSUE TITLE
jdbc driver cannot be downloaded

### ISSUE THREAD

**Issue by second-fiddle-biz** [dbeaver/dbeaver#22065]
### Description

An error occurred when creating a postgres connection destination.
mysql was the same

```
Network error

理由:
 Network unavailable
java.net.SocketException:Broken pipe

Network unavailable
java.net.SocketException:Broken pipe
Network unavailable
java.net.SocketException:Broken pipe
```

[![Image from Gyazo](https://i.gyazo.com/7585c90917762ae6baf6614225fdf0b0.gif)](https://gyazo.com/7585c90917762ae6baf6614225fdf0b0)

![image](https://github.com/dbeaver/dbeaver/assets/101646546/74f38d5c-2755-4974-bbd5-4fdef0c2a52b)

### DBeaver Version

23.2.5

### Operating System

macOS Sonoma 14.1.2

### Steps to reproduce

1. create new connection
2. Select PostgresSQL
3. View driver properties

In my environment an error occurs in step 3

### Additional context

log file

[error.log](https://github.com/dbeaver/dbeaver/files/13532056/error.log)

**Comment by ShadelessFox** [comment]
Hello @second-fiddle-biz,

It looks like DBeaver doesn't have access to the internet.

Please check your network/firewall configuration and make sure the following URL is accessible: https://repo1.maven.org

**Comment by second-fiddle-biz** [comment]
Hello @ShadelessFox .

The problem was resolved by turning off the firewall of the antivirus software (McAfee livesafe) I was using.

It happened so suddenly that I didn't notice it until I received some advice.

thank you.
