### ISSUE TITLE
Azure Data Studio can switch between multiple Azure SQL Databases that are under one Azure SQL Server but DBeaver cannot.

### ISSUE THREAD

**Issue by mayanknamasys20** [dbeaver/dbeaver#22066]
**Is your feature request related to a problem? Please describe.**
Azure Data Studio can switch between multiple Azure SQL Databases that are under one Azure SQL Server but DBeaver cannot. When I work with DBeaver, I have to create a separate connection for each Azure SQL Database even though if they are under same Azure SQL Server.

**Describe the solution you'd like**
It should work like Azure Data Studio. I just need to create connection with the Server and then it gives me the dropdown of all Azure SQL Databases and I can select whichever database I want and can change it whenever I want.

**Describe alternatives you've considered**
Azure Data Studio

**Additional context**
Screenshot of Azure Data studio dropdown.
![image](https://github.com/dbeaver/dbeaver/assets/90683579/4ba5a894-5fbc-44d8-b540-4179abbaec90)

Error that I get in DBeaver when I try to change Azure SQL Database
![image](https://github.com/dbeaver/dbeaver/assets/90683579/2a8bebac-97cf-4a30-af94-5ca25d0332b8)

**Comment by LonwoLonwo** [comment]
Hello @mayankhb96 

Thanks for the report.
We will implement it here: https://github.com/dbeaver/dbeaver/issues/17263
I'm closing this ticket as a duplicate.
