### ISSUE TITLE
Bookmark shortkey doesn't work

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#22067]
### Description

Bookmark shortkey doesn't work

### DBeaver Version

23.3.0

### Operating System

Windows 11

### Database and driver

Any

### Steps to reproduce

1. Focus on any DB object in the Navigator
2. Press <kbd>Ctrl + Shift + Alt + D</kbd>

**Expected:** Bookmark can be created
**Actual:** Nothing happens

**Comment by Matvey16** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/dbeaver/project/8805?defectId=14866)

**Comment by LonwoLonwo** [comment]
Can't reproduce. What type of object do you have in the navigator tree?

**Comment by Matvey16** [comment]
Seems like a bug in my system that leads to 4 keys pressed simultaniously not being recognised. I'll close it as not a bug.
