### ISSUE TITLE
[MySql] Hypelinks don't work in sqript if table name in CamelCase

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#22076]
### Description

Hypelinks don't work in sqript if table name in CamelCase or capitalized
<img width="543" alt="2" src="https://github.com/dbeaver/dbeaver/assets/84867187/74c23f88-f75e-4b18-8d5a-a71d2a529abd">

### DBeaver Version

23.3.0

### Operating System

mac M1 Somona

### Database and driver

MySQL Connector/J mysql-connector-j-8.2.0

**Comment by E1izabeth** [comment]
Can't reproduce it anymore. Seems we fixed it.
