### ISSUE TITLE
Pacman Package dont have last updates

### ISSUE THREAD

**Issue by GaNiziolek** [dbeaver/dbeaver#22080]
### Description

The last version on Arch official packages was 23.2.2, this version has many bugs that have already been fixed but I can't upgrade because this package is not updated on Arch.

https://archlinux.org/packages/extra/x86_64/dbeaver/

### DBeaver Version

Community Edition 23.2.2

### Operating System

Arch Linux

**Comment by Destrolaric** [comment]
@GaNiziolek Hi. Unfortunately, the Pacman package is community-maintained. DBeaver team is not updating the package, and we suggest contacting the package maintainer regarding package updates. 
You can also use our flatpak image, which our team maintains.
