### ISSUE TITLE
Definition compare

### ISSUE THREAD

**Issue by monsieurrouge2** [dbeaver/dbeaver#2208]
When I compare two views from two different databases (e.g. Development vs. Production), the result shows compares of several properties (name, comment, schema, columns), but it does not compare the actual view definitions (create view as select from where).

Is there any way this can be done?

**Comment by serge-rider** [comment]
No, it is not yet supported.

**Comment by monsieurrouge2** [comment]
OK, that's clear.
This enhancement would be very welcome!

**Comment by serge-rider** [comment]
View definition property is available in all relational dbs (including generic)

**Comment by monsieurrouge2** [comment]
I installed 4.2.4 yesterday.
When I select two views and compare them, the view definition itself is still not compared. Am I doing something wrong or was I unclear in describing what my enhancement is?

**Comment by serge-rider** [comment]
What is your database?

**Comment by monsieurrouge2** [comment]
Teradata.
Although I am not using the default driver. I am using a different version because the default one was an old one and to slow. I use the Teradata JDBC version 15.10.00.22.

**Comment by uslss** [comment]
not reproducible anymore (7.2.2)
