### ISSUE TITLE
db2 discov3er owner entity slow

### ISSUE THREAD

**Issue by nickhuge666** [dbeaver/dbeaver#22099]
### Description

Hi
I upgraded to a latest version a few weeks ago but am still having real issues specifically when querying / browsing federated objects. I always have to spin up aqua data studio in order to do that.

It will just hang on discover owner entity and i have to kill dbeaver after 10 minutes. Any ideas?

Version 23.2.4.202311070022

### DBeaver Version

Community Version 23.2.4.202311070022

### Operating System

ventura 13.4.1

### Database and driver

Db2 11
jdbc

### Steps to reproduce

either i go to an object and expand the columns or indexes for example and it just spins for ages. then ill try and go and query syscat columns instread and it will hang on doscover owner entity. it does this for normal tables too

**Comment by nickhuge666** [comment]
What normally happens is it then has a connection timeout and then i can query the table. It seems related to the browsing of objects

**Comment by nickhuge666** [comment]
theres a chance this has improved since turning off show statistics info in the connection view

**Comment by LonwoLonwo** [comment]
Hello.
Probably, it is connected to this ticket: https://github.com/dbeaver/dbeaver/issues/21216

**Comment by LonwoLonwo** [comment]
Hello. We changed the query for statistics reading. Could you please check our [Early Access](https://dbeaver.io/files/ea/) version and check your performance issues in this version?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
