### ISSUE TITLE
DBeaver still binding RMI(?) to wide-open address versus localhost

### ISSUE THREAD

**Issue by bkuntzelman** [dbeaver/dbeaver#22093]
### Description

Even though the log says its connecting to localhost, the socket that is opened is bound to the "any" address instead of "localhost" or 127.0.0.1.

### DBeaver Version

Community Edition Version 23.3.0.202312031432

### Operating System

Windows 11 Enterprise (22000.2600)

### Steps to reproduce

1. Launch DBeaver
2. Read debug log: 2023-12-04 09:41:11.296 - Starting instance server at http://localhost:52572
4. At command line: netstat -an -p TCP | find /i "52572": TCP    0.0.0.0:52572          0.0.0.0:0              LISTENING       15752

**Comment by serge-rider** [comment]
We must limit it to localhost (loopback) address.
And add some parameter to keep existing behavior because in some cases we still need REST interface available for external access.

**Comment by serge-rider** [comment]
@bkuntzelman Thank you for the bug report

**Comment by bkuntzelman** [comment]
It might be beneficial to also change the logging statement so that it reflects the actual address which the RestServer is listening on instead of being "hard-coded" to "localhost" since there were really two problems here: (1) listening on the "any" address while (b) reporting it was listening to localhost. The first was likely a mistake, but in the second, the logging lied.
