### ISSUE TITLE
tab页文字显示-关闭关闭

### ISSUE THREAD

**Issue by JGMa-java** [dbeaver/dbeaver#22097]
### Description

为什么这么多版本了还没有人注意到这个错误？中文tab页“关闭全部”的功能显示关闭关闭
![image](https://github.com/dbeaver/dbeaver/assets/36287827/28d04f18-8078-4438-953a-05b6a0d616f2)

### DBeaver Version

23.3.0社区版

### Operating System

windows

**Comment by LonwoLonwo** [comment]
Hello @JGMa-java 

Thanks for the report.

It is a knowing issue described here: https://github.com/dbeaver/dbeaver/issues/17697
