### ISSUE TITLE
PostgreSQL: autocompletion doesn't work with join lateral

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#22104]
### Description

Autocompletion doesn't work with "join lateral" construction. Brokes in 23.2.5. Works correctly in 23.2.4.
![2023-12-05 22-15-14 ](https://github.com/dbeaver/dbeaver/assets/22142845/1fa46a86-95a6-4b69-9d25-780df438e6bb)

### DBeaver Version

Community Edition 23.3.0

### Operating System

Windows 10 x64

### Database and driver

PostgreSQL 9.5 or PostgreSQL 15
PostgreSQL JDBC Driver 42.5.2

### Steps to reproduce

1. Create tables.
```
drop table if exists tmp_tab1;

drop table if exists tmp_tab1;

create table tmp_tab1(
	id int,
	field1 text,
	field2 text);

create table tmp_tab2(
	id int,
	field3 text,
	field4 text);
```
2. Reconnect.
3. Input query and try to autocomplete at mark.
```
select *
from tmp_tab1 t1
	join lateral (select t2.id
		from tmp_tab2 t2
		where t2. --<--- here ctrl+space
where t1.id > 1;
```

**Comment by LonwoLonwo** [comment]
Hello @ems2811 

Thanks for the report.
I will add your case to the main ticket about this issue: https://github.com/dbeaver/dbeaver/issues/7768
