### ISSUE TITLE
The procedure parameters created with "Type Of Column TABLE_NAME.COLUMN_NAME" appear as normal data type in the source code.

### ISSUE THREAD

**Issue by ugrsyn** [dbeaver/dbeaver#22109]
### Description

The procedure parameters created with `Type Of Column TABLE_NAME.COLUMN_NAME` , appear as normal data type in the source code.
![create_sp](https://github.com/dbeaver/dbeaver/assets/23517706/f50a17c9-8cf3-4e6e-a772-3c7b146b37e5)
![show_sp](https://github.com/dbeaver/dbeaver/assets/23517706/529f397f-e7c5-40dc-b9dc-dbf93318f00f)

### DBeaver Version

Community Edition 23.3.0

### Operating System

Windows Server 2019

### Database and driver

DB : Firebird 4.0
Driver : Firebird Jaybird driver 5.0.2

### Steps to reproduce

After creating the table and the procedure, please look at the code of the procedure.
Instead of "TYPE OF COLUMN TBL_TEST.COL1" you will see varchar(10) in both input and return parameters.

`CREATE TABLE TBL_TEST(COL1 VARCHAR(10), COL2 VARCHAR(10));`
`SET TERM # ;`
`CREATE OR ALTER PROCEDURE SP_TEST_PARAM_TYPES(`
`    P_1 TYPE OF COLUMN TBL_TEST.COL1,`
`    P_2 TYPE OF COLUMN TBL_TEST.COL2)`
`RETURNS (    `
`    R_1 TYPE OF COLUMN TBL_TEST.COL1,`
`    R_2 TYPE OF COLUMN TBL_TEST.COL2)`
`AS`
`BEGIN`
`  R_1 = :P_1;`
`  R_2 = :P_2;`
`  SUSPEND;`
`END#`

**Comment by LonwoLonwo** [comment]
Thanks for the report @ugrsyn 

And how about functions? Can functions have such kind of syntax in the definition?

**Comment by ugrsyn** [comment]
Yes, It is also used to define functions. I just checked and functions have the same problem.

**Comment by LonwoLonwo** [comment]
Could you please provide a function definition also?

**Comment by ugrsyn** [comment]
Sure.
`SET TERM # ;`
`CREATE OR ALTER FUNCTION FNC_TEST(P_1 TYPE OF COLUMN TBL_TEST.COL1)`
`RETURNS TYPE OF COLUMN TBL_TEST.COL1`
`AS`
`DECLARE VARIABLE V_TEST TYPE OF COLUMN TBL_TEST.COL1;`
`BEGIN`
`  V_TEST = :P_1;`
`  RETURN V_TEST;`
`END#`

![FNC_TEST](https://github.com/dbeaver/dbeaver/assets/23517706/03ee12d3-3d10-43f3-b76e-ff3b564612ff)
