### ISSUE TITLE
DBeaver crashes due to  problem with script "not found" in the tree

### ISSUE THREAD

**Issue by ivela06** [dbeaver/dbeaver#22101]
### Description

Hello, I am not sure this is a bug, but we have an issue that prevents DBeaver to open and I did not find aby information about the error encountered.

DBeaver crashes on Opening with the message 
org.eclipse.core.internal.dtree.ObjectNotFoundException: Tree element '/General/Scripts/Script-25.sql' not found.

The header of log file is 
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.core.resources 2 10035 2023-12-04 16:37:38.665
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

The file mentioned here (/General/Scripts/Script-25.sql' ) exists in the user directory, it was empty. We added a line inside, and tried again to launch DBeaver, but the problem remains.
Pls find log attached.  Thank you for any help, and sorry if this is not the right place to report

Isa

Log file<
[DBeaver-ObjectNotFound.log](https://github.com/dbeaver/dbeaver/files/13561282/DBeaver-ObjectNotFound.log)

### DBeaver Version

Community edition Version 23.1.1.202306251800

### Operating System

Windows Server 2019 datacenter

### Database and driver

Vertica DB 12.0.4 , vertica jdbc driver

**Comment by serjiokov** [comment]
Hi @ivela06, could you please try to remove script manually from workspace folder located by path:
 "...USER_HOME_FOLDER\AppData\Roaming\DBeaverData\workspace6\General\Scripts" 
and launch the product.
The case is hardly reproduceble on my side, it is seems a result of "The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes."

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual for you - feel free to reopen it

**Comment by ivela06** [comment]
So sorry for no answer... there were holidays in between.
Could the case be re-opened ?
We have tried the solution proposed by serjiokov, but the problem remains, even when the "faulty" file is no more there. How could the user tell DBeaver to ignore this file ?

thanks a lot

**Comment by infocube-dev-team** [comment]
Removing
```
workspace6/.metadata/.plugins/org.eclipse.core.resources/*.snap
```
e 
```
workspace6/.metadata/.plugins/org.eclipse.core.resources/.root/*tree
```
seems solve the problem. They are the only remaining files with reference to the "missing" script.

**Comment by pasquale-basile** [comment]
Removing
```
workspace6/.metadata/.plugins/org.eclipse.core.resources/*.snap
```
e 
```
workspace6/.metadata/.plugins/org.eclipse.core.resources/.root/*tree
```
seems solve the problem. They are the only remaining files with reference to the "missing" script.

**Comment by ivela06** [comment]
Thank you so much, this solved the problem indeed !
The ticket can be closed now.

Thanks again for your help
