### ISSUE TITLE
Crashes upon attempting to export a selected SQL query

### ISSUE THREAD

**Issue by cherio** [dbeaver/dbeaver#22118]
### Description

I experienced a crash when I attempted to export the results of a SELECT SQL into a file. Included is a full java exception stack with a <ins>clearly identifiable</ins> infinite loop.

### DBeaver Version

Community Edition 23.2.4

### Operating System

Linux Arch, Linux Ubuntu

### Database and driver

DB Driver: postgresql-42.6.0.jar

### Steps to reproduce

1. Selected a SELECT statement (sorry, SQL reveals the details of implementation; thankfully the error doesn't seem to relate to the actual SELECT statement)
2. Right clicked on the selected text
3. Chose "`Execute`"
4. Chose "`Export From Query`"

This threw the exception dialog (see the Additional Context field for details copied from that dialog) and subsequently popped up a polite dialog offering to restart DBeaver.

### Additional context

Plugin: `org.jkiss.dbeaver.model`

Session Data:
```
eclipse.buildId=unknown
java.version=21
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -eclipse.keyring /home/yc/.local/share/dbeaver-home/.local/share/DBeaverData/secure/secure_storage
Command-line arguments:  -os linux -ws gtk -arch x86_64
```

Exception Stack Trace (the infinite loop is clearly identifiable) - see the attached file
[dbeaver-java-exception-stack.log](https://github.com/dbeaver/dbeaver/files/13592258/dbeaver-java-exception-stack.log)

**Comment by Matvey16** [comment]
@cherio Does it happen with every query that you try to use in export? Did you see the export wizard window or was the exception thrown immidiately and before it could appear?

**Comment by cherio** [comment]
The error didn't seem to depend on the kind of query.

I myself is a java developer. Reading the stack trace (see attached), there is a clearly identifiable infinite loop in it. The devs who maintain the code should have no trouble identifying logic that causes execution flow to enter that loop.

BTW, the error no longer occurs in version 23.3.0

**Comment by serjiokov** [comment]
@cherio Thanks for update, if issue no longer reproducable suggest to close it.
