### ISSUE TITLE
dbeaver does not work with MacOS Sonoma 

### ISSUE THREAD

**Issue by sedwards75** [dbeaver/dbeaver#22116]
### Description

after upgrading to MacOs Sonoma 14.1.2 dbeaver will now long open connections 

Can't initialize tunnel
  Cannot establish tunnel to hidden ip
  Cannot establish tunnel to hidden ip
    Session.connect: java.net.SocketException: Broken pipe
    Session.connect: java.net.SocketException: Broken pipe
      Broken pipe
      Broken pipe

### DBeaver Version

cummintiy 7.1.3 and Enterprise 23.0.2

### Operating System

MacOS Sonoma 14.1.2

### Database and driver

POSTGRESQL 11.15
driver 42.2.5

### Steps to reproduce

after update to macos sonoma opened dbeaver and existing connection no longer work.

**Comment by buliverd53** [comment]
Got the same problem here, I can configure a connection, but when I try to connect, the app crashes :-(

**Comment by sedwards75** [comment]
attempted to update Postgresql driver 
get error when selecting download/update

Network error

Reason:
Network unavailable
java.net.SocketException:Broken pipe

**Comment by cblevins28** [comment]
DBeaver Version: 23.3.0

I get the same problem with Snowflake. 

Network error

Reason:javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by serge-rider** [comment]
@cblevins28 It seems to be a different issue, please create separate ticket for it.

**Comment by serge-rider** [comment]
@sedwards75 could you attach debug log file?
This looks like a network configuration issue. All outbound connections are reset (probably by MacOS).

You also could try to reinstall DBeaver. Then MacOS may ask network permissions on first start.

**Comment by buliverd53** [comment]
Morning @serge-rider, here's the dbeaver crash log from my mac.
I've made a clean install on my mac and this crash still happens.
[dbeaver-cash.log](https://github.com/dbeaver/dbeaver/files/13601380/dbeaver-cash.log)

**Comment by cblevins28** [comment]
If I check for updates with DBeaver on Mac, I get different error message.

java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
  Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
  Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
    problem accessing trust store
    problem accessing trust store

**Comment by serge-rider** [comment]
@buliverd53 Thank you for the details. 

I see that there is a number of threads spawned, some MySQL connection initiation, etc.

Could you provider more details - what happens when you start DBeaver, what actions lead to this app crash?
Also please attach debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files).

**Comment by sedwards75** [comment]
I resolved my issue by disabling Filters under Network, McAfee adds Filter & Proxies that don't currently work with Sonoma, disabled until McAfee release update

**Comment by buliverd53** [comment]
Hi @serge-rider  I've discovered that the problem happens when I click on the expand arrow on the left side of the name of the connection:

<img width="184" alt="Captura de Tela 2023-12-08 às 12 32 31" src="https://github.com/dbeaver/dbeaver/assets/16110029/66d6a345-b534-4d19-9663-f850e3f76e88">

every time i click this arrow, the app crashes. If i just double click to connect, doesn't crash, but if I try to expand any other view, like DataBase, crashes the same way.
I've attached the debug log.
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/13617341/dbeaver-debug.log)

**Comment by LonwoLonwo** [comment]
>  I resolved my issue by disabling Filters under Network, McAfee adds Filter & Proxies that don't currently work with Sonoma, disabled until McAfee release update

Can I close this ticket then? Did you solve your issue?

**Comment by sedwards75** [comment]
Yes please close

**Comment by divyasshree-BQ** [comment]
> > I resolved my issue by disabling Filters under Network, McAfee adds Filter & Proxies that don't currently work with Sonoma, disabled until McAfee release update
> 
> Can I close this ticket then? Did you solve your issue?

Thanks so much for this reply. Was struggling with this "broken pipe" issue for days

**Comment by cblevins28** [comment]
This issue has been resolved.
