### ISSUE TITLE
Replace keybinding for "Fetch Next Page"

### ISSUE THREAD

**Issue by TB-HunBoka** [dbeaver/dbeaver#22126]
**Is your feature request related to a problem? Please describe.**
When I have a query result that has more rows than the number of fetched rows (200 for my example) and I want to write a semicolon, it doesn't write ; but instead fetches the next page.
I found that this can be done with the ctrl+alt+; key combination.
However, I can on a Hungarian keyboard the semicolon sign can be written by ctrl+alt+, which will act the same way as ctrl+alt+;
Therefore, semicolon and fetch next page is on the same keyboard combination for me.

**Describe the solution you'd like**
Having a different keyboard combination for "Fetch Next Page" fixed the problem on my end, so it can be useful for others too.

**Comment by Destrolaric** [comment]
You can change the shortcut in `Preferences -> User Interface -> Keys`


![Image](https://github.com/dbeaver/dbeaver/assets/20579256/7044b028-130f-41d1-80c1-5987e02e99c4)

**Comment by TB-HunBoka** [comment]
> You can change the shortcut in `Preferences -> User Interface -> Keys`
> 
> ![Image](https://private-user-images.githubusercontent.com/20579256/288785601-7044b028-130f-41d1-80c1-5987e02e99c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5Nzk0NTksIm5iZiI6MTcwMTk3OTE1OSwicGF0aCI6Ii8yMDU3OTI1Ni8yODg3ODU2MDEtNzA0NGIwMjgtMTMwZi00MWQxLTgwYzEtNTk4N2UwMmU5OWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDE5NTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NjI5NWIyMzFlZjQ0YWYyZGFlMmM3YTRlMDI5MjE1MGExNzkyODEzOTU2ZGJhNGE0YTI0ZDAzZDc5NDA1NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wtHIPLfRqs-2l8soaefshxbHJHk680xLyDXRo-2ZpA8)

This is exactly the same as what I did and mentioned it in my comment.
However, since this is the default setting, other users may have a similar unpleasant experience.
That's why I suggested changing the default setting.

**Comment by arhayka** [comment]
Thank you for the report. 
We decided to change this shortcut.
