### ISSUE TITLE
Export wizard cannnot open target directory when the pathname contains a blank

### ISSUE THREAD

**Issue by quido18** [dbeaver/dbeaver#22125]
### Description

When using the export wizard and the target directory contains a space character, the last step (open the target directory) fails.

### DBeaver Version

Community Edition 23.2.5

### Operating System

Windows 10

### Steps to reproduce

Rightlick the result grid -> Export Data.
Go over the export steps.
In the step **Output** choose a directory with a blank, e.g. "C:\Users\Name Surname"
Finish the Wizard

Result: Windows File Explorer is opened, but with location "This PC", since it failed to open the export location.

**Comment by LonwoLonwo** [comment]
Hello @quido18 

What kind of export did you use? Specificaly.

**Comment by quido18** [comment]
Hi, I used HTML export

**Comment by LonwoLonwo** [comment]
> since it failed to open the export location.

Did the export finished fine? Is the issue only in the incorrectly opened folder path?
Do you have the right to make changes for this user?

**Comment by quido18** [comment]
Yes, it's a minor issue. Export finished fine and can be located manually at the defined target location. It can be opened and edited.
It's only issue that the last step might be confusing to the user as it opens a file manager for no obvious reason.

**Comment by LonwoLonwo** [comment]
> it opens a file manager for no obvious reason.

Is this setting turned on?

![2023-12-07 16_55_33-Data Transfer](https://github.com/dbeaver/dbeaver/assets/45152336/ff53ce7e-6505-4cda-818b-7c93d8f8261e)

**Comment by quido18** [comment]
Yes it is. It is enabled by default, I didn't change it.

**Comment by LonwoLonwo** [comment]
For now, it looks like a system permissions issue. 
I can export my file in a folder like "c:\Users\MyUser\Name Surname" and the result window will be correct. 
But it doesn't work for "c:\Users\Name Surname\".
And again, are you sure, that you have enough permission to do it?

**Comment by quido18** [comment]
I assume so, because dbeaver.exe runs under my user (checked in task manager process details) and the export file gets stored in the folder. So I based on that I am assuming it has the permission. But we can close if not reproducible on your side.

**Comment by quido18** [comment]
Maybe [this](https://github.com/dbeaver/dbeaver/blob/57dd446701282f25071aec4df9b86a387d74e772/plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/ShellUtils.java#L140C1-L140C106)?

**Comment by E1izabeth** [comment]
We can't reproduce the issue.
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide log files.
