### ISSUE TITLE
When dbeaver is opened, the loading image shifts

### ISSUE THREAD

**Issue by stigsanek** [dbeaver/dbeaver#22132]
### Description

When I open dbeaver the loading display is not centered as before, but is shifted exactly halfway. This situation started after upgrading to macOS Sonoma.

<img width="758" alt="img" src="https://github.com/dbeaver/dbeaver/assets/37377259/8b4cd49a-705c-485e-827a-866351661629">

### DBeaver Version

Community Edition 23.3.0.202312031432

### Operating System

masOS Sonoma 14.1.2 (23B92)

### Database and driver

It doesn't depend on database and driver

### Steps to reproduce

Open dbeaver

**Comment by MashaKorax** [comment]
Duplicate https://github.com/dbeaver/pro/issues/2256
