### ISSUE TITLE
Incorrect tnsnames default unit

### ISSUE THREAD

**Issue by TB-HunBoka** [dbeaver/dbeaver#22131]
### Description

In our company, we have a CONNECT_TIMEOUT and TRANSPORT_CONNECT_TIMEOUT parameter in the oracle TNSNAMES.ora. Usually these are set to 5 or 3.
The default CONNECT_TIMEOUT unit should be **sec** based on the oracle documentation: https://docs.oracle.com/en/database/oracle/oracle-database/19/netrf/local-naming-parameters-in-tns-ora-file.html#GUID-F20C5DC5-C2FC-4145-9E4E-345CCB8148C7
"In case, no unit is mentioned, the default unit is sec"
However, I got an instant timeout error message, with 4 ms.
![image](https://github.com/dbeaver/dbeaver/assets/126617861/b4d53fad-b996-4176-b582-f03f43fed9d3)

I modified the tnsnames.ora on my end, but I need to do that every time I download the latest version.

### DBeaver Version

Community Edition 23.3

### Database and driver

Oracle 19c

### Steps to reproduce

add the following parameters in the description of a connection:
(DESCRIPTION=
(CONNECT_TIMEOUT=4)(TRANSPORT_CONNECT_TIMEOUT=4)
(ADDRESS_LIST=...

**Comment by Matvey16** [comment]
@TB-HunBoka Can you say what did you modify to fix this. In my case after adding (CONNECT_TIMEOUT=4)(TRANSPORT_CONNECT_TIMEOUT=4) the connection timed out exactly after 4 seconds
![dbeaver_iRRAU0boAA](https://github.com/dbeaver/dbeaver/assets/82543000/1eed7d12-215d-4c45-8a63-c6b5d6d8df20)

**Comment by TB-HunBoka** [comment]
@Matvey16 I am having confusing results. I tried it with Version 23.3.4.202401300022 Early access version, and I am seeing the same issue, it uses ms.
I updated my main dbeaver to 23.3.3 and it was not working. I edited the tns names to increase the TRANSPORT_CONNECT_TIMEOUT value, save the file (not restarting the dbeaver) and started working. Then updated the tns_names again, reduced the TRANSPORT_CONNECT_TIMEOUT to 1 and it's still working.
Restarted the dbeaver, not working.
Starting the Early access version, it works.
Starting 23.3.3, it works.

I will try to find a way to reproduce the issue correctly.

**Comment by E1izabeth** [comment]
Is the issue still actual for you?

**Comment by LonwoLonwo** [comment]
Probably related: https://github.com/dbeaver/dbeaver/issues/19061

**Comment by TB-HunBoka** [comment]
> Probably related: #19061

I am not sure if it was related or not, but I could not reproduce the issue since my last comment.

Several of my friends reported the same error, so maybe the update + clicking the test connection button re-read the tns_names solved the problem for me. I will ask my friends to validate it.

**Comment by E1izabeth** [comment]
Thank you. We will wait

**Comment by TB-HunBoka** [comment]
hello @E1izabeth 

My friend has older DBeaver and older library, where he can still reproduce the problem. So, I can verify that with new DBeaver and new oracle library, this issue is no more.

Thanks
Boka

**Comment by E1izabeth** [comment]
Thank you
