### ISSUE TITLE
Allow change password/expired password handling for Mysql/MariaDB

### ISSUE THREAD

**Issue by JTMosaic** [dbeaver/dbeaver#22148]
A user is unable to change their own password and is not prompted to change their password if it is expired when connecting to MySQL or MariaDB

Similar to what is mentioned in https://github.com/dbeaver/dbeaver/wiki/Change-current-user-password, it would be great if DBeaver could add MySQL/MariaDB to that list.

**Comment by LonwoLonwo** [comment]
Hello @JTMosaic 

I'm not sure that we can do it from our side.
We did it for Oracle, but the Oracle driver supports changing expired password:

https://github.com/dbeaver/dbeaver/blob/cfd833d479c45de6cda1557e07b7eb01a811ccd2/plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/model/OracleDataSource.java#L228-L245

Only I can see now for MySQL - this [info](https://dev.mysql.com/doc/refman/8.0/en/expired-password-handling.html):

```
On the server side, if a client indicates that it can handle expired passwords, the server puts it in sandbox mode.

If a client does not indicate that it can handle expired passwords (or uses an older version of the client library that cannot so indicate), the server action depends on the value of the disconnect_on_expired_password system variable:

    If disconnect_on_expired_password is enabled (the default), the server disconnects the client with an ER_MUST_CHANGE_PASSWORD_LOGIN error.

    If disconnect_on_expired_password is disabled, the server puts the client in sandbox mode.
```

It looks like you can change the password with our [feature](https://github.com/dbeaver/dbeaver/wiki/Change-current-user-password) if disconnect_on_expired_password is disabled. Did you try this way?

**Comment by JTMosaic** [comment]
Thanks for the reply, @LonwoLonwo!

1. The MariaDB driver does not expose that parameter in the configuration but the MySQL driver does. It is set to true by default
2. Changing this parameter to false and reconnecting with an expired password does not change the behavior; the same error appears:
```
SQL Error [1820] [HY000]: You must SET PASSWORD before executing this statement
  You must SET PASSWORD before executing this statement
```
3. Changing this setting does not make the Security menu appear when right-clicking a connection

I would think at this point, as the driver and server should or could handle the change (assuming we can either add the parameter to the MariaDB driver as a user parameter or use the MySQL driver), DBeaver may just need to know to handle the sandbox connection and prompt for a password change.

**Comment by E1izabeth** [comment]
We want to investigate, if it's possible, and implement it, if yes.

**Comment by yoni-yad2** [comment]
It would be great if a popup window will appear to change the password like in MySQL Workbench:

![image](https://github.com/user-attachments/assets/018c8b22-2f83-4807-9d6b-0c22ced4851a)

**Comment by arhayka** [comment]
In this issue, we added the ability to change expired password for MySQL. We can't do the same for MariaDB: https://github.com/dbeaver/dbeaver/pull/36431#issue-2712565892

**Comment by JTMosaic** [comment]
That this cannot be done for MariaDB doesn't make sense to me

https://mariadb.com/kb/en/user-password-expiry/

MariaDB's most current drivers cause DBeaver to show this error for an expired password login attempt: 

![Image](https://github.com/user-attachments/assets/4dd8ee48-ebe0-4d1c-8f53-290add088ac9)

![Image](https://github.com/user-attachments/assets/342a3500-57fe-467e-b197-5dfb59c2cce3)

**Comment by kyle-joiner** [comment]
MariaDB is releasing a new driver this week that allows for updating an expired.  Should we reopen this ticket or create a new one?

**Comment by ShadelessFox** [comment]
@kyle-joiner https://github.com/dbeaver/dbeaver/issues/36880

**Comment by hedyeherfani** [comment]
The customer has provided the following feedback:

"
I was able to test this feature in the Early Access and it still does not work.  In order to get the Security – Change user password menu option, you need to already be connected to the database.  This is still an issue as you cannot connect via DBeaver if your password is expired (because DBeaver appears to be running some script on connect). "
@ShadelessFox @serge-rider

**Comment by ShadelessFox** [comment]
@hedyeherfani 

No need to use **Security -> Change user password** in this case.

When connecting under a user whose password has expired, a prompt should appear asking for a new password.

Can you please ensure that the customer indeed uses the latest early access version? And let's continue this discussion in a new internal ticket.

**Comment by JTMosaic** [comment]
Just tested this in version 25.1.0 and it worked as expected. Thanks!
