### ISSUE TITLE
Problems when transferring data to other DB

### ISSUE THREAD

**Issue by x2game625** [dbeaver/dbeaver#22153]
### Description

I use data transfer, but it doesn't work after the 23.3.0 update.

The Data Transfer pop-up window did not close and DBeaver did not stop. If you look at information_schema.`PROCESSLIST`, there is this phrase in INFO: /* ApplicationName=DBeaver 23.3.0 - SQLEditor <Script.sql>~, and the TIME value continues to increase.

It was working fine before the 23.3.0 version was updated...but not exactly, I had this problem after the update

![image](https://github.com/dbeaver/dbeaver/assets/19172606/28e14e4f-f7a9-430c-bbff-617ae4653f0c)

### DBeaver Version

Community 23.3.0

### Operating System

Windows 10 Pro

### Database and driver

DB: mysql8
MySQL driver: JDBC Type 4 driver for MySQL

### Steps to reproduce

1.Select Query
2.Data transfer
3. Export target Tab/Table select/Next
4. Tables mapping Tab/Target container/DB Select
5. Disable Button

**Comment by LonwoLonwo** [comment]
Hello @x2game625 
Could you please provide a video of the issue?

**Comment by x2game625** [comment]
A popup window appears on my screen, but I can't see it on the recording screen.
The subsequent screens were performed in the order of "Steps to reproduce".
After reproduction, it will look like the picture above

https://github.com/dbeaver/dbeaver/assets/19172606/d0e2e90e-0ad4-4e53-b9a3-8019ef243976

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by x2game625** [comment]
Reproduce the problem sequence and send the log file
[.log](https://github.com/dbeaver/dbeaver/files/13679282/default.log)

**Comment by Destrolaric** [comment]
Could you please try to generate a thread dump and attach it here? Here is the instruction: https://dbeaver.com/docs/wiki/Making-a-thread-dump/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide thread dump.
