### ISSUE TITLE
Autocomplete disables with OVER function in select statements

### ISSUE THREAD

**Issue by jezabennett** [dbeaver/dbeaver#22168]
### Description

When using a row_number function in a select statement, this seems to disable the autocomplete for column names.

### DBeaver Version

Community Version 23.3.0

### Operating System

Windows 11 Enterprise

### Database and driver

SQL Server 2017
Microsoft JDBC Driver for SQL Server

### Steps to reproduce

Working autocomplete:
![image](https://github.com/dbeaver/dbeaver/assets/16517218/f658fbfe-69f7-459d-a798-66a23e2baa02)

Disabled autocomplete once row_number function added:
![image](https://github.com/dbeaver/dbeaver/assets/16517218/1f8f664e-b3ab-4c7d-b40b-b561e0b3f710)

**Comment by jezabennett** [comment]
This behaviour seems to happen as soon as a function is typed in the SQL statement. 
e.g. 
,right(field_a)

Will disable autocomplete

**Comment by MashaKorax** [comment]
I reproduced it in SQL-server on db9 using sqript:
```
CREATE TABLE Persons (    
  person_name varchar(45) NOT NULL,    
  product varchar(45) DEFAULT NULL,    
  country varchar(25) DEFAULT NULL,  
  price float,  
  years int NOT NULL    
); 
```
```
INSERT INTO Persons (person_name, product, country, price, years)     
VALUES ('Steffen', 'Computer', 'USA', 20000.00, 2018),     
('Joseph', 'Laptop', 'India', 35000.00, 2016),     
('Kevin', 'TV', 'USA', 15000.00, 2016),     
('Thompson', 'Mobile', 'France', 12500.00, 2017),   
('Donald', 'Laptop', 'England', 30000.00, 2018),    
('Joseph', 'Mobile', 'India', 18000.00, 2018),    
('Matthew', 'Desktop', 'France', 22000.00, 2017),     
('Antonio', 'Mouse', 'England', 1200.00, 2016);  
```
```
SELECT *, ROW_NUMBER()   
OVER (ORDER BY price) AS row_num  
FROM Persons;  
```

**Comment by E1izabeth** [comment]
We should describe OVER clause in our parser
https://learn.microsoft.com/en-us/sql/t-sql/queries/select-over-clause-transact-sql?view=sql-server-ver16
