### ISSUE TITLE
Columns autocompletion do not appear anymore in INSERT (*)

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#22164]
### Description

In previous version (sorry, I don't remember which one...), it was possible to autocomplete columns list in INSERT INTO statement, adding a star between brackets and using CTRL+Space shortcut.
This shortcut already works with SELECT \*, but no more with INSERT INTO table_name (\*).

Is it possible to restore this feature?

Thanks in advance,

Cedric

### DBeaver Version

Community Edition 23.3.0

### Operating System

Ubuntu 22.04

### Database and driver

Database : PostgreSQL 14

### Steps to reproduce

1. Type the command:
INSERT INTO table_name (\*)

2. Put the cursor right to the star

3. Press CTRL + Space: the column list of table "table_name" does not appear.

**Comment by E1izabeth** [comment]
Thank you for bug report.
I confirm that the feature was working at least on 23.0.1 and it's not working on 23.3.0

**Comment by LonwoLonwo** [comment]
Also duplicate https://github.com/dbeaver/dbeaver/issues/22218

**Comment by Destrolaric** [comment]
The issue is not present when `Enable experimental features` is turned off.
