### ISSUE TITLE
Autocomplete column names disabled when multi-line comment syntax is used

### ISSUE THREAD

**Issue by jezabennett** [dbeaver/dbeaver#22169]
### Description

When using the multi-line comment syntax, this seems to disable autocomplete of column names.
Comments like this will disable the autocomplete.
/*---
test comment
---*/
 
Autocomplete not working example (multi-line comments below the select statement also don't work):
![image](https://github.com/dbeaver/dbeaver/assets/16517218/ac9ceb72-842f-43c9-bff4-ab9a7c4f4c31)

Working with inline comment:
![image](https://github.com/dbeaver/dbeaver/assets/16517218/88f04c6f-0469-4712-9975-0299a3bbc4db)

### DBeaver Version

Community Version 23.3.0

### Operating System

Windows 11 Enterprise

### Database and driver

SQL Server 2017
Microsoft JDBC Driver for SQL Server

**Comment by E1izabeth** [comment]
Thank you for bug report.
As a temporary workaround you can turn off this setting
![image](https://github.com/dbeaver/dbeaver/assets/28875055/2e123853-307a-43e3-8d4f-e668aa50596e)
