### ISSUE TITLE
Functions defined in Oracle WITH clause 

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#22177]
### Description

A similar problem to #14096 occurred.
Even if you select and execute the entire SQL to be executed as in the solution in #14096,
Error Ora-00905 occurs.

SQL)
```
WITH FUNCTION fn_get (vParam IN varchar2) RETURN varchar2
IS vRet varchar2(100);
BEGIN 
 SELECT decode(vParam,'031','a','032','b')
 INTO vRet
 FROM dual;
 RETURN vRet;
END ;
SELECT fn_get ('031') 
 FROM dual
```

![image](https://github.com/dbeaver/dbeaver/assets/59002295/8f4a668c-e452-4ca9-bce9-13ca42b6af6b)

In the previous version(23.2.4), if you selected all of the SQL and then executed it, it ran normally.

Thank for reading. :)

### DBeaver Version

Community Edition 23.2.5

### Operating System

Window 10

**Comment by E1izabeth** [comment]
Please try the latest DBeaver version 23.3.0. The workaround with selecting whole query should work in 23.3.0

**Comment by podoni** [comment]
@E1izabeth
I just installed version 23.3.0 and the problem was resolved. Thank you for quick response. :)
