### ISSUE TITLE
Chinese word error

### ISSUE THREAD

**Issue by myjock** [dbeaver/dbeaver#22178]
### Description

Right click Close TAB, not "Close close" but "Close All"
Right click Close TAB, not "关闭关闭" but "关闭所有"
![微信截图_20231214133540](https://github.com/dbeaver/dbeaver/assets/111119687/21436966-fac1-47a2-a4b3-635a05eb5fee)

### DBeaver Version

23.3.0.202312122044

### Operating System

Windows 11

**Comment by E1izabeth** [comment]
Thank you for bug report.
I'm closing it as a duplicate of #17697 You can subscribe to that issue for updates.
