### ISSUE TITLE
in redshift, function and procedure are not distinguish correctly 

### ISSUE THREAD

**Issue by arshadatSignet** [dbeaver/dbeaver#22175]
### Description

When dropping a stored procedure the drop script that is produced has a drop "function". This problem is carried in other parts of the environment also

### DBeaver Version

community Edition 23.3.0

### Operating System

windows 11

### Steps to reproduce

1. in the Project Explorer,  under functions try to drop a stored procedure. 
2. by right click and delete
3.

**Comment by LonwoLonwo** [comment]
Hello @arshadatSignet 

Can you please provide footage showing your issue? Thank you.

**Comment by LonwoLonwo** [comment]
And database version.

**Comment by arshadatSignet** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/149186791/75cb7a6e-6366-4bf9-b996-b2fff5783b94)
when using delete in the explorer, should be procedure; but is showing as function; this is also when you do a ddl extraction for stored procedure.

select version()
version                                                                                                                   |
--------------------------------------------------------------------------------------------------------------------------+
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.61191 |

**Comment by LonwoLonwo** [comment]
Could you please provide your procedure DDL for tests?

**Comment by arshadatSignet** [comment]
-- this one works fine. Since it is a true function.
```CREATE OR REPLACE FUNCTION sandbox_dat.fn_uuid() 
RETURNS character varying AS 
$$
import uuid  
return uuid.uuid4().__str__()
$$ LANGUAGE plpythonu VOLATILE;
```
-- This one will not work correctly since it is a procedure and not a function
```
CREATE OR REPLACE PROCEDURE sandbox_dat.sp_dat_maco_logger(logtype VARCHAR,msg VARCHAR)
AS 
$$
declare 
    log_type VARCHAR(20);
    log_message VARCHAR(1000);
    ins_sql text;
begin
    log_type := logtype;
    log_message := msg;
	raise info '%', msg;
	ins_sql := $ins_sql$
        INSERT INTO sandbox_dat.dat_maco_logger (log_id,  log_type, log_message) VALUES 
        ('{log_id}', '{log_type}', '{log_message}');
    $ins_sql$;
    
    ins_sql := replace (ins_sql, '{log_id}', sandbox_dat.fn_uuid());
    ins_sql := replace (ins_sql, '{log_type}', log_type);
    ins_sql := replace (ins_sql, '{log_message}', log_message);
    --raise info '%', ins_sql;
    execute ins_sql;
```
The problem is that the UI is not pulling the prockind: 

```
select proname, prokind 
from  pg_Proc_info
WHERE proname in ('fn_uuid', 'sp_dat_maco_logger');
proname           |prokind|
------------------+-------+
fn_uuid           |f      |
sp_dat_maco_logger|p      |
```

**Comment by LonwoLonwo** [comment]
Still, I can not reproduce your issue.

![2024-01-29 18_04_54-DBeaver Ultimate 23 3 4 - _dev 8_ Script-170](https://github.com/dbeaver/dbeaver/assets/45152336/3fcfe452-1851-4fda-9462-3fb98bfc8918)

But we have this condition in our code:

```java
public boolean supportsStoredProcedures() {
        return isRedshiftVersionAtLeast(1, 0, 7562);
}
```

We probably should decrease this value.

**Comment by LonwoLonwo** [comment]
Thanks for the report
