### ISSUE TITLE
CSV Import & truncate bug

### ISSUE THREAD

**Issue by liar666** [dbeaver/dbeaver#22174]
### Description

The "truncate" operation and DDL actions are not synchronized: If I try to import data from a CSV and it fails, then try to import again, adding a column, the DDL will create an "ALTER TABLE statement", but if I've selected the "Truncate Target Table" in the "Data load settings", then the "ALTER TABLE" enters in conflict with the TRUNCATE.

### DBeaver Version

Version 23.3.0.202312031432

### Operating System

Ubuntu 22.04

### Database and driver

Oracle

### Steps to reproduce

- try to import data from a CSV, ignoring a few columns, make it so it fails after a few lines (eg. too small size for some varchar2 fields)
- try to import again, this time adding a column you had previously ignored + select the "Truncate Target Table" in the "Data load settings"
- Get an error

PROBLEM:
- The addition of a colum makes the DDL create an "ALTER TABLE statement"
- The TRUNCATE should have removed all the columns, but has not yet been applied
=> error comes from conflict between emptying table and altering it... Due to bad ordering of the actions

**Comment by Matvey16** [comment]
@liar666 Can you specify what kind of Oracle database and driver do you use.
It does,'t seem to happen in my case. Maybe you can see what was the difference in my case.


https://github.com/dbeaver/dbeaver/assets/82543000/b48b6501-79a8-436d-92e1-7b378289f433

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
