### ISSUE TITLE
Issue with TimeOut Open AI

### ISSUE THREAD

**Issue by VanessaMondillon** [dbeaver/dbeaver#22171]
Hello,

I try to used Open AI in my DB, but I have one issue with time out : 

AI service error: Connect timed out
  Connect timed out
  Connect timed out

One idea ? 

Thank !

**Comment by LonwoLonwo** [comment]
Hello @vanessa2509 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
