### ISSUE TITLE
How to not pass local hostname to remote DB at login

### ISSUE THREAD

**Issue by mhallen** [dbeaver/dbeaver#2218]
I haven't been able to figure out how to do this.  When I try to connect to a remote MySQL DB it's using username@thenameofmylaptop, which I believe is causing the login to fail.  It's throwing a java.sql exception of 'access denied.  Thanks much.  Version is 4.0.3.

**Comment by serge-rider** [comment]
Do you use SSH tunnel?
- If yes then you can set host name to `localhost` on the connection page.
- If not then you just can't connect to this database from a remote machine. Consult with your DBA.

**Comment by tati-kru** [comment]
hi @mhallen 
Do you have any updates about this issue?

**Comment by nlcPrg** [comment]
This continues to be a problem for DBeaver and MySql. My other JDBC clients work fine with the identical MySql driver and host, it's only DBeaver that is adding the local hostname and failing to connect. This should not have been closed.
