### ISSUE TITLE
Encoding CP1251

### ISSUE THREAD

**Issue by Makareene** [dbeaver/dbeaver#22183]
### Description

Hello everyone! How can I get charset CP1251? Earlier, when I opened files from DBeaver with charset CP1251, it was supported. But for now DBeaver opens files always like UTF-8, and I don't see my native symbols. How can I install the charset CP1251?
![изображение](https://github.com/dbeaver/dbeaver/assets/82905264/f649b2ac-380e-4933-8776-35a0225d077f)
![изображение](https://github.com/dbeaver/dbeaver/assets/82905264/70fb42ad-daeb-4f5b-98f7-3b2c9b082751)

### DBeaver Version

Community 23.3.0.202312031432

### Operating System

Windows 10

**Comment by LonwoLonwo** [comment]
Hello @Makareene 

Could you please try to add your value manually in your combo box?

![2023-12-21 15_39_19-Transparent Window](https://github.com/dbeaver/dbeaver/assets/45152336/17032c31-fa29-4570-85c6-cc66f3043cde)

**Comment by Makareene** [comment]
Hello @LonwoLonwo
It's works! Thanks a lot!

**Comment by LonwoLonwo** [comment]
Thanks for the update!

**Comment by LordManubis** [comment]
Hello everyone!
For me adding a value manually didn't help.
Solution that worked was to change dbeaver.ini file in DBeaver installation folder.
![Screenshot](https://github.com/user-attachments/assets/7c9c9cf3-483f-4415-be0a-64e9f23c5d91)
Change "Dfile.encoding" to preferred default character set.
