### ISSUE TITLE
New DBeaver version, 23.3, no longer includes quotes around longtext columns when exporting as insert into

### ISSUE THREAD

**Issue by thudpaw** [dbeaver/dbeaver#22191]
### Description

The new DBeaver version, 23.3, no longer includes quotes around longtext columns when exporting as insert into.

### DBeaver Version

23.3

### Operating System

Windows

### Database and driver

MariaDB
MariaDB JDBC driver

### Steps to reproduce

Create a Data Export task (Common—>Data export).
Data export: Add to the task a table that has at least one column that is a longtext data type.
Export target: SQL - Export to SQL INSERT statements.
The rest of the data export task can be defaults.

### Additional context

Look at the exported file and notice that the longtext column data no longer has single-quotes around their values.  Every previous DBeaver version I have used does wrap longtext values in single-quotes.  The new version, 23.3, no longer does that and it really needs to.  Thanks!

**Comment by Matvey16** [comment]
@thudpaw I wasn't able to reproduce this. Can you copy a DDL for your table and show me a screenshot of settings for your export?

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual for you - feel free to reopen it
