### ISSUE TITLE
Frustrating button placement in data export wizard

### ISSUE THREAD

**Issue by codeandcats** [dbeaver/dbeaver#22194]
### Description

When I want to export something (which can be many times a day), 99.9% of the time I just want all the default options (exporting to csv with the default filename), but I am forced to keep clicking `Next` multiple times. It wouldn't be so bad if I could just spam my left mouse button in the same position on screen but DBeaver inexplicably resizes the window, moving the position of the `Next` button and on the final step forces me to click on a button in different position to finally just export it. It's possible to click the `Proceed` button on the 2nd last page but it's still not very helpful.

https://github.com/dbeaver/dbeaver/assets/6035934/7c856882-c478-43eb-b386-231996645c70

Can we please either:

- Have the `Next` button remain in the same position the entire time and confirm the export on the final page, so we can just spam the left mouse button without moving the mouse to get through all these screens quicker

- Have the `Proceed` button available to click from the start so we can export with one click

### DBeaver Version

Community Edition  v23.3.0.202312031432

### Operating System

Mac OS Ventura v13.5.1

### Database and driver

1. PostgreSQL 11.17
2. org.postgresql.Driver 42.5.2

### Steps to reproduce

1. Right-click on query results
2. Click 'Export Data' menu option
3. Observe the Data Transfer window opens
4. Click the `Next` button
5. Click the `Next` button
6. Observe the Window gets taller, shifting the position of the `Next` button down
7. Click the `Next` button
8. Click the `Next` button
9. Observe that you can no longer click the `Next` button to confirm and perform the export
10. Observe that you must click the `Proceed` button, a couple buttons to the left
11. Have to do this many times a day 😓

**Comment by E1izabeth** [comment]
Thank you for sharing your use case. We will discuss what we can do about it.

By the way, have you tried using our tasks?
https://dbeaver.com/2022/09/08/working-with-tasks-how-to-get-started/
https://dbeaver.com/docs/dbeaver/Task-Management/

**Comment by E1izabeth** [comment]
Similar issue when the user got confused because of that #16993

**Comment by arhayka** [comment]
We decided to make the Proceed button default on the last page.

**Comment by codeandcats** [comment]
@arhayka @E1izabeth thank you so much for scheduling this. 👏

If it's not too much trouble, could you also stop the window from automatically resizing part way through the steps please? If it needs to be a min height for a particular step, it would be great if it opened at that size to begin with. 🙏

**Comment by Matvey16** [comment]
@codeandcats This is tricky because in some cases the window should be resized to include everithing, but with current fix the resizing won't be such an issue, because it would be possible to go from start to finish in export wizard with multiple pushes of only <kbd>Enter</kbd> button
