### ISSUE TITLE
Wrong dbname sent to pg_restore

### ISSUE THREAD

**Issue by PatrickSvenssonSL** [dbeaver/dbeaver#22208]
### Description

I am using a database task for restoring postgres databases.
For some reason it has stopped working as the dbname sent to pg_restore is cropped.
If the database selected from the list is named mydatabase_test, pg_restore gets the argument --dbname mydatabase.
It has worked up until recently.

### DBeaver Version

Community version 23.3.0.202312031432

### Operating System

Windows 11

### Database and driver

PostgreSQL 11

### Steps to reproduce

1. Make a backup using a database task and backuptype folder
2. Create a database with an _ in its name, like mydatabase_test
3. Make a restore using database task and select the database you created
4. Check the logfile, it'll state that the dbname was different from the one you chose

**Comment by PatrickSvenssonSL** [comment]
This issue still exists in version 23.3.2.202401072024.
1. Exported database test-prod with format "folder".
2. Imported to database test-local
Confirmation box says importing to test-local.
pg_restore connectionstring says --dbname=test
pg_restore processing DATABASE says test-prod

**Comment by LonwoLonwo** [comment]
Hello @PatrickSvenssonSL 

Unfortunately, I can't reproduce your issue.

For me, it is working correctly.

![2024-01-12 13_15_18-DBeaver Ultimate 23 3 3 - run_202401121313_2 log](https://github.com/dbeaver/dbeaver/assets/45152336/36b44ad2-602b-4348-b578-92b0be872907)

Could you make a video for this issue? Backup and restore operations, both.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
