### ISSUE TITLE
I am using mac book pro, sonoma.

### ISSUE THREAD

**Issue by ANIRUDHTEAM1000** [dbeaver/dbeaver#22209]
### Description

 want to connect dbeaver communiy to bigquery. I am using mac book bro. when i tried installing bigquery driver I was getting PKIX no valid ssl for "https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.5.0.1001.zip". Then I have downloaded ssl for storage.googleapis.com and the driver is installed.

Now I am getting same kind of error for service account.

[Simba]BigQueryJDBCDriver HttpTransport IO error : Error getting access token for service account: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, iss: p1-k@project-test.iam.gserviceaccount.com. EXEC_JOB_EXECUTION_ERR EXEC_JOB_EXECUTION_ERR Error getting access token for service account: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, iss: p1-k@project-test.iam.gserviceaccount.com Error getting access token for service account: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, iss: p1-k@project-test.iam.gserviceaccount.com PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target unable to find valid certification path to requested target unable to find valid certification path to requested target

### DBeaver Version

23.3.0

### Operating System

mac os

### Database and driver

DB: BigQuery
Driver: SimbaJDBCDriverforGoogleBigQuery42_1.5.0.1001.zip

**Comment by flambchap** [comment]
Hi, @ANIRUDHTEAM1000. Are you working in a restrictive network, behind a proxy, for example?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
