### ISSUE TITLE
Support force password set on login for SAP HANA

### ISSUE THREAD

**Issue by hski-bayer** [dbeaver/dbeaver#22206]
A user can be forced to set a new password on login e.g. when password has been reset by support or if password expired. In case of such a situation DBeaver let you no longer login to the SAP HANA database and shows following error message.

`SAP DBTech JDBC: [414]: user is forced to change password: alter password required for user`

![image](https://github.com/dbeaver/dbeaver/assets/127206085/6855540b-33ec-4ab7-9875-757808f99669)

Instead of the error message, a dialog should be shown to set a new password. 

As a work around I need to login using SAP HANA Studio and set a new password. Then I can go back to DBeaver. Would be fantastic if DBeaver could support password set during login, so that I don't need to work with SAP HANA Studio anymore.

**Comment by LonwoLonwo** [comment]
Hello @hski-bayer 

Thanks for the idea.

Password changing depends on the driver's abilities. If a driver can - then we can do it via the driver. So, we need to investigate this option for Hana.
