### ISSUE TITLE
Star/asterisk expansion from SQL assist seems broken

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#22218]
### Description

Using ctrl + space as described in https://github.com/dbeaver/dbeaver/wiki/SQL-Assist-and-Auto-Complete seems broken for insert statements 

    INSERT INTO tableName (*)

It still works for select statemets

SELECT * FROM tableName

### DBeaver Version

DBeaver Community Edition	23.3.0.202312031432

### Operating System

Windows 10

### Database and driver

Oracle

### Steps to reproduce

1. write INSERT INTO tableName (*)
2. put the cursor after * and before )
3. hit ctrl + space

**Comment by LonwoLonwo** [comment]
Hello @p91paul 

Nice to see you again.

Thanks for the bug report.
I will add your case to the existing issue: https://github.com/dbeaver/dbeaver/issues/22164.
