### ISSUE TITLE
Expanding connections (et al) crashes on Mac Sonoma 14.3

### ISSUE THREAD

**Issue by andreala** [dbeaver/dbeaver#22216]
Referenced @buliverd53 in another thread, but now spawning separate:

 I've discovered that the problem happens when I click on the expand arrow on the left side of the name of the connection:

<img width="184" alt="Captura de Tela 2023-12-08 às 12 32 31" src="https://github.com/dbeaver/dbeaver/assets/16110029/66d6a345-b534-4d19-9663-f850e3f76e88">

every time i click this arrow, the app crashes. If i just double click to connect, doesn't crash, but if I try to expand any other view, like DataBase, crashes the same way.
I've attached the debug log.
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/13617341/dbeaver-debug.log)

_Originally posted by @buliverd53 in https://github.com/dbeaver/dbeaver/issues/22116#issuecomment-1847396187_
            
            
Confirming the same behaviour here (both in brew cask and ce.dmg).

**Comment by andreala** [comment]
[hs_err_pid82696.log](https://github.com/dbeaver/dbeaver/files/13725366/hs_err_pid82696.log)
[hs_err_pid82561.log](https://github.com/dbeaver/dbeaver/files/13725367/hs_err_pid82561.log)

**Comment by Destrolaric** [comment]
Hi thank you for report it looks like an issue with graphics on macOS, it can quite possibly can be connected to changes in macOS Sonoma 14.3.

**Comment by Destrolaric** [comment]
macOs Sonoma 14.3 should have a stable release soon. If the issue persists, we will contact Apple.

**Comment by shyamalapati** [comment]
This seems to be resolved in 14.3 beta 2

**Comment by andreala** [comment]
Confirmed here as well.
Resolved in 14.3b2 with 23.3.1.202312241705
