### ISSUE TITLE
export connection without secrets

### ISSUE THREAD

**Issue by xoyteam** [dbeaver/dbeaver#22225]
I want to transfer the connection configuration, without secrets.
how can I do this?

**Comment by LonwoLonwo** [comment]
Hello @xoyteam 

Did you try just copying your new workspace your data-sources.json file? 
You can find it in your current workspace.
Path example: `DBeaverData\workspace6\General\.dbeaver\`

Your credentials are in another file - credentials-config.json. Do not copy it.

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual for you - feel free to reopen it
