### ISSUE TITLE
Add output to results

### ISSUE THREAD

**Issue by Karsonito** [dbeaver/dbeaver#2222]
Some queries to vertica DB return additional output. For example:
> 42611: Using PARTITION expression that returns a Numeric value
 Hint: This PARTITION expression may cause too many data partitions.  Use of an expression that returns a more accurate value, such as a regular VARCHAR or INT, is encouraged

This is very important to show them in results. I can see them in output tab, but it always hidden when switching to results. We can miss them

**Comment by serge-rider** [comment]
Agreed

**Comment by serge-rider** [comment]
I think that this can be solved by putting output panel (as well as execution log) to the right/down after the results.

**Comment by serge-rider** [comment]
Or move it to a separate view (like error log view)
