### ISSUE TITLE
The time() field type does not handle fractions of a second.

### ISSUE THREAD

**Issue by ivalla** [dbeaver/dbeaver#22227]
### Description

The time() field type does not handle fractions of a second.

### DBeaver Version

Community Edition 23.3.0 

### Operating System

Windows 11

### Database and driver

Microsoft SQL 2016 - Microsoft JDBC Driver for SQL Server

### Steps to reproduce

DECLARE @timeFrom time(4) = '01:23:45.6789'
DECLARE @timeTo time(3) = @timeFrom

SELECT @timeFrom AS 'time(4)' , @timeTo AS 'time(3)'
time(4)  time(3)
-------- --------
01:23:45 01:23:45

**Comment by LonwoLonwo** [comment]
Hello @ivalla 

For now, I can't reproduce your issue.

Did you try to change the data format settings?

![2023-12-21 12_42_52-DBeaver Ultimate 23 3 1 - _master_ Script-101](https://github.com/dbeaver/dbeaver/assets/45152336/fb63a25b-ab7e-48f2-bdc6-ee06e8a59f28)

**Comment by ivalla** [comment]
Hello Anastasiya, 
good suggestion, thanks.

I set a format with .ffffff but only zeros are indicated

DECLARE @timeFrom time(4) = '01:23:45.6789'
DECLARE @timeTo time(3) = @timeFrom

SELECT @timeFrom AS 'time(4)' , @timeTo AS 'time(3)'

time(4)         time(3)
--------------- ---------------   
01:23:45.000000 01:23:45.000000

Unfortunately now I encounter an error when I want to enter the Preferences.

![image](https://github.com/dbeaver/dbeaver/assets/154512013/1576c710-51d2-408b-b998-37142f8a825b)

**Comment by LonwoLonwo** [comment]
Could you please provide the log files for the error? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

Also, maybe the "Disable date/time formatting" on the preference page will help.

**Comment by ivalla** [comment]
I closed DBeaver, deleted the LOG file, restarted Dbeaver: now it's ok. Preferences are accessible.
Great Anastasiya, your suggestion "Disable date/time formatting" solved the problem.
Merry Christmas and Happy New Year 2024.

![image](https://github.com/dbeaver/dbeaver/assets/154512013/9d9ea8c1-bfef-42fa-82cf-96b5e5586de9)

**Comment by ivalla** [comment]
Has been solved. Thank a lot.

**Comment by LonwoLonwo** [comment]
Thanks for the update!
Happy holidays 🦫
