### ISSUE TITLE
DBeaver switches to manual commit mode when Smart Commit is enabled and you execute an invalid query

### ISSUE THREAD

**Issue by wheinen** [dbeaver/dbeaver#22229]
### Description

When you use Smart Commit mode, and you execute a wrong query, like `where id = 123;` DBeaver switches to Manual Commit mode.

I am using smart commit here with autocommit:
![image](https://github.com/dbeaver/dbeaver/assets/137804655/56fc9d6f-3b4e-447f-9626-8f192038dd1e)

After executing the query it switched to manual commit, which means I am now keeping a transaction open.
![image](https://github.com/dbeaver/dbeaver/assets/137804655/3d47c42e-e69f-4b69-a6c2-ea838e9bcae4)

If I don't notice this I could potentially lock a database if I execute a correct select statement afterwards.

### DBeaver Version

Community Edition 23.3.0

### Operating System

Windows 11

### Database and driver

MySQL 8
com.mysql.cj.jdbc.Driver
8.0.29

### Steps to reproduce

1. Enable Autocommit and Smart commit
2. Excute an invalid query like 'where id = 123;'
3. DBeaver switches to Manual Commit

**Comment by E1izabeth** [comment]
It's the desired behavior https://dbeaver.com/2022/05/26/change-the-data-in-the-smart-way

**Comment by wheinen** [comment]
An error is not necessarily an 'unsafe operation'. 

It only seems to happen when you execute a query that starts with 'where' or 'and'. Why is that? Other errors don't give this behaviour, so that's why it's unexpected.

The problem arises when you execute a query like
`select * from table`
`where id = 123`
And afterwards you want to select all from the table, so you add a semicolon to the first line, but accidentally execute the second line.

This behaviour is unexpected as other errors don't cause this.

**Comment by arhayka** [comment]
We want to switch back to smart commit if:
1. we switch to manual commit right before query execution
2. query failed
