### ISSUE TITLE
return value of "org.jkiss.dbeaver.runtime.DBWorkbench.getPlatform()" is null

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#22239]
### Description

In unit autotests call DBWorkbench.getPlatform().getPreferenceStore(); fails because of:
```
Cannot invoke "org.jkiss.dbeaver.model.app.DBPPlatform.getPreferenceStore()" because the return value of "org.jkiss.dbeaver.runtime.DBWorkbench.getPlatform()" is null
```

How to reproduce:
execute **mvn clean install** from **dbeaver-qa-auto\auto-test\unit**

### DBeaver Version

dbeaver ee 23.3.1

### Operating System

win10

**Comment by E1izabeth** [comment]
error on trying to install DBeaver plugin on Eclipse 2023-12
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver IDE 23.3.1.202312241705 (org.jkiss.dbeaver.ide.feature.feature.group 23.3.1.202312241705)
  Missing requirement: DBeaver UI 5.1.136.202312241705 (org.jkiss.dbeaver.ui 5.1.136.202312241705) requires 'osgi.bundle; org.jkiss.bundle.jsvg 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver Databases UI 1.0.112.202312241705 (org.jkiss.dbeaver.db.ui.feature.feature.group 1.0.112.202312241705)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ext.athena.ui [1.0.91.202312241705,1.0.91.202312241705]
  Cannot satisfy dependency:
    From: DBeaver AWS Athena UI 1.0.91.202312241705 (org.jkiss.dbeaver.ext.athena.ui 1.0.91.202312241705)
    To: osgi.bundle; org.jkiss.dbeaver.ui 0.0.0
  Cannot satisfy dependency:
    From: DBeaver IDE 23.3.1.202312241705 (org.jkiss.dbeaver.ide.feature.feature.group 23.3.1.202312241705)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.db.ui.feature.feature.group [1.0.112.202312241705,1.0.112.202312241705]
```

After install can't open any view:
`java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.model.app.DBPPlatform.getNavigatorModel()" because the return value of "org.jkiss.dbeaver.runtime.DBWorkbench.getPlatform()" is null`

**Comment by serjiokov** [comment]
Reproduced,
![image](https://github.com/dbeaver/dbeaver/assets/32031248/20f39622-7868-4007-87e2-654345d76c6a)
 
Root cause: 
2023-12-25 10:14:03.101 - Error injecting field 'platformInstance' in 'org.jkiss.dbeaver.model.impl.app.ApplicationWorkbenchImpl@39fbee74'
java.lang.IllegalStateException: Service '**org.jkiss.dbeaver.model.app.DBPPlatfor**m' is not registered
	at org.jkiss.dbeaver.utils.RuntimeUtils.getBundleService(RuntimeUtils.java:613)
	at org.jkiss.dbeaver.utils.RuntimeUtils.injectComponentReferences(RuntimeUtils.java:644)

**Comment by DariaMarkaryan** [comment]
Verified
