### ISSUE TITLE
Filter stored procedures in navigation panel

### ISSUE THREAD

**Issue by markainick** [dbeaver/dbeaver#2223]
The filter in the navigation panel to the left, currently works only for tables and views.
It would be nice if it also worked for stored procedures.

**Comment by serge-rider** [comment]
This filter actually works for any objects.

You can configure it using context menu:
![image](https://user-images.githubusercontent.com/6398845/31064858-1603310e-a749-11e7-957c-4044ee069e79.png)

**Comment by tati-kru** [comment]
It looks like this question was solved. So it will be closed. Bit if you have any additional questions, please write a comment and we will reopen it.

**Comment by JasonGilley** [comment]
This does not work for MS Sql Server stored procedures. No filtering is available.

**Comment by AvronNet** [comment]
There is no Filter option for procedures for MS SQL database
![image](https://user-images.githubusercontent.com/8115899/45090682-51840600-b110-11e8-9777-4eeeefa95628.png)
Will this be available soon?

**Comment by serge-rider** [comment]
@JasonGilley @AvronNet Yep. It is a bug in Generic driver. Thanks for the report. Will be fixed in 5.2
