### ISSUE TITLE
The problem of querying history cannot find records from one month ago

### ISSUE THREAD

**Issue by leezm** [dbeaver/dbeaver#22238]
**Is your feature request related to a problem? Please describe.**
I find that query history can only show limited rows.For example,I want't find last month’s query records,but it can only shows 4 days ago......
**Describe the solution you'd like**
Can dbeaver set the number of days to save, for example, 90 days? It will be automatically deleted after 90 days.
**Describe alternatives you've considered**
The number of days that query history is retained can be configured
**Additional context**
It is really important to find the query history from a few days or months ago

**Comment by LonwoLonwo** [comment]
Hello @leezm 

Did you try to check these settings?

![2023-12-22 11_18_08-DBeaver Ultimate 23 3 1 - TEST_ROLE_1](https://github.com/dbeaver/dbeaver/assets/45152336/3bf99e58-e171-48e0-8727-47653463c023)

**Comment by leezm** [comment]
> Hello @leezm
> 
> Did you try to check these settings?
> 
> ![2023-12-22 11_18_08-DBeaver Ultimate 23 3 1 - TEST_ROLE_1](https://private-user-images.githubusercontent.com/45152336/292451197-3bf99e58-e171-48e0-8727-47653463c023.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNTU5MDMsIm5iZiI6MTcwMzI1NTYwMywicGF0aCI6Ii80NTE1MjMzNi8yOTI0NTExOTctM2JmOTllNTgtZTE3MS00OGUwLTg3MjctNDc2NTM0NjNjMDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE0MzMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YmNlZjFjYWZmNTRmNmQxOGQwNzlhOWJkYjUyM2ZiOWZiMTI3ZTMyMDg2NGNlYTM4NGM1N2Y3MDI2YTk3M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gk7th0KuG3slmJYs6douyZ06wFHraPb5syTDQT8gM7Y)
No! I thought this setting was used to save the error log during execution or something. . . If I set it up like this, can I find more execution records in the query manager?

**Comment by LonwoLonwo** [comment]
We have separate preferences for error logs.

You can find queries in your files now, but not in DBeaver UI.

**Comment by leezm** [comment]
> We have separate preferences for error logs.
> 
> You can find queries in your files now, but not in DBeaver UI.


It is recommended that you can query it in Dbeaver UI after setting it up.

**Comment by LonwoLonwo** [comment]
Sounds like you need the Query Manager Query History: https://github.com/dbeaver/dbeaver/wiki/Query-Manager

But it is available for the PRO version only. You can try it for free: https://dbeaver.com/trial/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
