### ISSUE TITLE
General -> Network Connections settings is gone on version 23.3.1

### ISSUE THREAD

**Issue by po3nx** [dbeaver/dbeaver#22248]
### Description

Network Connections settings is not available after updating to version 23.3.1

Before update
![beforex](https://github.com/dbeaver/dbeaver/assets/438758/3496ca80-476c-4f02-89a8-08c06da73554)

After update:
![after](https://github.com/dbeaver/dbeaver/assets/438758/28ae3884-cc52-441a-ab7d-53142029c892)

Available configurations is in the Connection->Drivers settings 
![proxys](https://github.com/dbeaver/dbeaver/assets/438758/eb3b068e-591c-462b-8d4e-109607cad110)

However, it appears that the proxy connection is not utilizing this setting, as I am unable to download the driver despite having the correct configuration.
![proxy](https://github.com/dbeaver/dbeaver/assets/438758/0996101b-65fd-4acb-9f02-738b9399f541)

### DBeaver Version

Community Edition 23.3.1

### Operating System

Windows 10

### Steps to reproduce

1.  Windows
2. Preferences
3. General
4. Network Connections

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by eteichm** [comment]
The Network Connections settings is back in 23.3.2 BUT this did not fix the Proxy authentication error https://github.com/dbeaver/dbeaver/issues/22306 saying: HTTP Proxy authentication required 
![DBeaver_authentication_required](https://github.com/dbeaver/dbeaver/assets/12070698/39b388e0-03f0-406c-bfeb-a5f7660d3e1b)

**Comment by E1izabeth** [comment]
@eteichm I reopened your issue.

**Comment by eteichm** [comment]
@E1izabeth Thanks, I've added details to my issue to help in resolving it.
