### ISSUE TITLE
make it obvious which server the tab belongs to

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#22245]
in 23.3.0 version 

Looking at the open tabs, it is not clear on which server, on which database the object or sql editor is open.

This leads to confusion and script execution errors. For example, you can mistakenly execute a script on the wrong server

![image](https://github.com/dbeaver/dbeaver/assets/61137576/00d4bcf4-d039-4fb3-b6d2-f346f5691282)

![image](https://github.com/dbeaver/dbeaver/assets/61137576/114e15b3-838a-4d80-99c5-fdeae3813cd6)

one solution is to create parent tabs like in racle PLSQLDeveloper

![image](https://github.com/dbeaver/dbeaver/assets/61137576/ffecfa47-bbf5-4d67-8ded-3e61ef7e67e5)

By clicking on the desired server, all tabs and objects open only on this server are displayed

perhaps more interesting solutions

**Comment by E1izabeth** [comment]
Thank you for the issue.
Here are the issues about it #10235 #18709
I'm closing this issue as a duplicate. 
You can vote for the mentioned issues with 👍 under the issue description to promote it to a higher priority.

**Comment by detkliff** [comment]
I didn’t understand what the final decision was made

**Comment by detkliff** [comment]
OK. I Voted

**Comment by E1izabeth** [comment]
> I didn’t understand what the final decision was made

We haven't implemented it yet, but we're going to.
