### ISSUE TITLE
[PERFORMANCE] "Detect Unique Idetifiers" takes over one minute

### ISSUE THREAD

**Issue by yiding-he** [dbeaver/dbeaver#22244]
### Description

When opening the data tab for a table in a MySQL database, it took a very long time waiting for "Detect unique identifiers". And that table has a primary key.

![Screenshot1](https://github.com/dbeaver/dbeaver/assets/900606/6f194654-26a5-4972-b583-8dbeb130acc1)

Further investigation showed it was stuck at the "checking permissions" stage while executing SQL like `select ... from information_schema.key_column_usage where ...`, which was taking quite a long time.

![Screenshot2](https://github.com/dbeaver/dbeaver/assets/900606/8e35a91c-4de0-459f-851d-1914ab22b4d4)

### DBeaver Version

23.3.1.202312241705

### Operating System

Windows 11 Pro 22H2 (22621.2861)

### Database and driver

- Server: MySQL [8.0.18]
- Driver: MySQL Connector/J [mysql-connector-j-8.2.0 (Revision: 06a1f724497fd81c6a659131fda822c9e5085b6c)]

### Steps to reproduce

1. Open connection to database;
2. Navigate to a table;
3. Switch to data tab.

**Comment by LonwoLonwo** [comment]
Hello @yiding-he 

Please check this answer from the related ticket: https://github.com/dbeaver/dbeaver/issues/16480#issuecomment-1478369644

Additionally, database version upgrading can be helpful in your case.
