### ISSUE TITLE
Clickhouse connection no working due to ClickHouseLZ4Stream

### ISSUE THREAD

**Issue by pablolopez2022** [dbeaver/dbeaver#22241]
### Description

I did update my dbeaver to latest version (Version 23.3.0.202312122044) and connections to clickhouse are not working.

Could not initialize class ru.yandex.clickhouse.response.ClickHouseLZ4Stream

MySQL connections are working fine.

How can I fix it?

### DBeaver Version

Community Version 23.3.0.202312122044

### Operating System

Windows 10 

### Database and driver

Clickhouse
com.clickhouse - 0.3.2-patch11

### Steps to reproduce

Just to try to connect to database.

**Comment by LonwoLonwo** [comment]
Hello @pablolopez2022 

Looks like you are using the old (legacy) Clickhouse driver version.
Please try to change your driver to non-legacy.

![2023-12-25 09_35_27-Window](https://github.com/dbeaver/dbeaver/assets/45152336/b52e2a3a-999c-46d6-a1d5-07cea6ea92c8)

**Comment by LonwoLonwo** [comment]
If you want to continue using the legacy driver version, go to your Connection Settings -> Driver Settings -> Libraries -> Add Artifact.

and add this string `maven:/ru.yandex.clickhouse:clickhouse-jdbc:RELEASE[0.2.6]`

and remove the downloaded one.

**Comment by LonwoLonwo** [comment]
Ok, I can reproduce this issue.

**Comment by mnvx** [comment]
Same problem with Ubuntu 22.04. It worked well before the update.

DBeaver Version 23.3.1.202312241705

Error message:
> Could not initialize class ru.yandex.clickhouse.response.ClickHouseLZ4Stream

![image](https://github.com/dbeaver/dbeaver/assets/829880/148ccd72-be9f-49e0-9c23-eb290ab8ea8a)

**Comment by pablolopez2022** [comment]
Hello,

I'm using 23.3.1 version.

How can I change the driver to non-legacy?

[image: image.png]

**Comment by LonwoLonwo** [comment]
Hello @pablolopez2022 

You can use step one from this message: https://github.com/dbeaver/dbeaver/issues/22241#issuecomment-1868827829

And then choose the non-legacy driver.

![2023-12-27 10_56_37-Migrate connection(s) to another driver](https://github.com/dbeaver/dbeaver/assets/45152336/557592ac-a110-4e21-bbd6-d6977dd6d064)

Or, if you want to keep using the legacy driver, you can add ai as an artifact, but turn on the dependency loading setting:

![2023-12-27 10_59_27-Connection _localhost 16_ configuration](https://github.com/dbeaver/dbeaver/assets/45152336/312db6bf-7983-418b-8621-1a9d81c803b6)
