### ISSUE TITLE
Data sample on table properties not using limit

### ISSUE THREAD

**Issue by alejandro-fiel-stori** [dbeaver/dbeaver#22251]
### Description

When going to the Data tab on table properties DBeaver throus this query to redshift, without LIMIT (I have 200 as limit)
SELECT
  x.*
FROM
  schema.table x

### DBeaver Version

23,3,0

### Operating System

maOS 14

### Database and driver

Redshift

### Steps to reproduce

Double click in a tabla on Database Navigator, go to the Data tab, and look into the Redshift console for the queries been run on the cluster.

**Comment by LonwoLonwo** [comment]
Hello @alejandrofielm 

Please provide a screen from your preference page. 
Preferences -> Editors -> Data Editor page.

**Comment by alejandro-fiel-stori** [comment]
Here it goes! It limits to 200 on queries but not on the table view.
![image](https://github.com/dbeaver/dbeaver/assets/153534002/21eddb4b-521a-4720-afda-a26ac1bf1c03)

**Comment by LonwoLonwo** [comment]
Could you please try to turn on the "Use SQL to limit fetch size" and check data reading again?

**Comment by alejandro-fiel-stori** [comment]
That was it, I thought it was enabled by default and worked according to this:
![image](https://github.com/dbeaver/dbeaver/assets/153534002/11eef365-c49d-44a3-8b56-0dab0d5831a5)
why is not enabled by default?
Thank you!

**Comment by LonwoLonwo** [comment]
Unfortunately, this is a database-specific setting, and it doesn't work in all databases that DBeaver supports.

**Comment by alejandro-fiel-stori** [comment]
Thanks, will change it manually from now
