### ISSUE TITLE
SQL Server: Awkward table display

### ISSUE THREAD

**Issue by ngohuuduc** [dbeaver/dbeaver#2225]
Dear All, 

I'm using DBeaver on Ubuntu, trying to connect to SQL Server, but got some different in table display which I have no idea why. 

SQL Studio 17.2 on Windows show this 
![image](https://user-images.githubusercontent.com/32363886/30970024-af63acda-a496-11e7-99bb-39275202dc0e.png)

But the DBeaver show this 

![image](https://user-images.githubusercontent.com/32363886/30970069-cfb6ab9a-a496-11e7-99ed-18176cc6cdc7.png)

I really cannot access any table for querry

Can someone help me

**Comment by serge-rider** [comment]
Existing SQL Server driver shows tables grouped by schemas (users).
In some cases some schemas are not visible in the navigator (driver doesn't rerun them for some reason).

Could you try native Microsoft JDBC driver (instead of jTDS)?

**Comment by ngohuuduc** [comment]
hi,

i actually used Microsoft JDBC downloaded from Microsoft as well. same thing has happend

On Sep 28, 2017 10:47 PM, Serge Rider <notifications@github.com> wrote:

Existing SQL Server driver shows tables grouped by schemas (users).
In some cases some schemas are not visible in the navigator (driver doesn't rerun them for some reason).

Could you try native Microsoft JDBC driver (instead of jTDS)?

**Comment by serge-rider** [comment]
What is your SQL Server version?

**Comment by ngohuuduc** [comment]
SQL server 2016 SP1

On Sep 28, 2017 11:56 PM, Serge Rider <notifications@github.com> wrote:

What is your SQL Server version?

**Comment by uslss** [comment]
Issue is not reproducible on 6.0.3
