### ISSUE TITLE
When alter a column from the Table properties view it freezes if tabled is locked

### ISSUE THREAD

**Issue by alejandrofm** [dbeaver/dbeaver#22252]
### Description

I just tried to change a column of a table that was locked by another query.
While the table was locked I couldn't go out of the Table properties tab.

### DBeaver Version

23.3.0 community

### Operating System

macOS 14

### Database and driver

Redshift JDBC 2.1.0.22

### Steps to reproduce

lock a table.
try to change the length of a column
dbeaver freezes

**Comment by LonwoLonwo** [comment]
Hello @alejandrofm 

Please provide more info about the step one. How exactly did you lock your table?

**Comment by alejandrofm** [comment]
Hi! didn't lock the table, the table was locked by a process that had an exclusive lock on it at that time.
The issue here is that DBeaver freezes until it has access to the table, when it should wait but let me use the other tabs/queries, etc.
Thanks!

**Comment by LonwoLonwo** [comment]
> the table was locked by a process that had an exclusive lock on it at that time.

Steel I need more info about it to reproduce your issue.
Could you tell me more about this process?

**Comment by alejandrofm** [comment]
you can do anything that locks a table, vacuum, delete, another way to force a lock will be:
```
begin;

LOCK table;

long query so the lock last a while;

end;
```

https://docs.aws.amazon.com/redshift/latest/dg/r_BEGIN.html
https://docs.aws.amazon.com/redshift/latest/dg/r_LOCK.html

**Comment by hrimthrusa** [comment]
Hi @alejandrofm 

I couldn't reproduce it in the latest v23.3.2. Could you please provide capture of the freezing you see?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
