### ISSUE TITLE
Results tab windows not on the current result tab when multiples tabs open

### ISSUE THREAD

**Issue by ufuk-ergin-carbon** [dbeaver/dbeaver#22264]
### Description

When you have multiple results tab open so that window size is not enough to show all of them, the current result window is not selected and you have to guess which one it is to either close it or switch to it. Screenshot is attached. In the screenshot you can see that the result tab that shows the count could not be closed because you cannot see it is selected in the tabs window and you can't see the x mark to close it. Only after you close some other result windows that fit on the screen, the latest result tab can be accessible to be closed with x mark. For example, how am I going to close the result tab that shows count 2,599,789?

Also, there could be a logical order to the results tab order. Currently, the ones that fall out of window range are grouped inconsistently (some are from the initial tabs, some are the latest results tabs as in the second screenshot).

<img width="1501" alt="Screenshot 2023-12-27 at 13 48 04" src="https://github.com/dbeaver/dbeaver/assets/114302087/8b3080fc-b64c-4c0f-8be7-1268493ccfc5">

<img width="1505" alt="Screenshot 2023-12-27 at 13 52 40" src="https://github.com/dbeaver/dbeaver/assets/114302087/c5099ba1-9fd3-4df1-a7b7-d697a869097c">

### DBeaver Version

Version 23.3.1.202312241705

### Operating System

MacOS Sonoma 14.2.1

### Database and driver

Database name: Snowflake
Database version: Snowflake 7.44.2
Database driver version: Snowflake 3.13.30

### Steps to reproduce

1. Have multiple results tabs so that the screen cannot show all of them. 
2. You'll see that one you just created cannot be selected because you'll have to guess where and which tab it is.

**Comment by serjiokov** [comment]
@ufuk-ergin-carbon Could you please provide footage showing how you achieved such a behavior?

**Comment by E1izabeth** [comment]
Unfortunately, we couldn't reproduce your issue and it's been a while since no update here. If the issue is still actual please let me know and provide steps to reproduce.
