### ISSUE TITLE
Default font size on Mac

### ISSUE THREAD

**Issue by bmoAtolcd** [dbeaver/dbeaver#22263]
### Description

The default font size is 40 in sql editor 
![image](https://github.com/dbeaver/dbeaver/assets/57495449/ac870e56-df81-4413-a26f-ad0581b383f3)
Or genereted sql window
![image](https://github.com/dbeaver/dbeaver/assets/57495449/d69a9eac-5c8b-4e8b-87c2-18a888254c10)

### DBeaver Version

Community Edition 23.3.1

### Operating System

macOS ventura 13.4

**Comment by E1izabeth** [comment]
@bmoAtolcd have you tried changing it in preferences?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/3e55cc0c-0d24-49a3-b8cc-f7c3694de215)

**Comment by bmoAtolcd** [comment]
<img width="794" alt="image" src="https://github.com/dbeaver/dbeaver/assets/57495449/749c0cba-2ffa-4ed2-a6e0-a11f2d3f8c1d">

I change from .AppleSystemUIFont 10 to Courier 10, noway.
Update: .AppleSystemUIFont 13 to Courier 13, noway.

**Comment by serjiokov** [comment]
@bmoAtolcd  Could you provide the logs please.

**Comment by bmoAtolcd** [comment]
My log when I start dbeaver (wich re-open a script sql), and i open a new script sql: both are in big font size!

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/13870324/dbeaver-debug.log)

**Comment by E1izabeth** [comment]
@bmoAtolcd what `Color and font theme` do you have in settings?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/197e1c6f-26c9-4ec2-a9e7-67ae34c4d1d7)

**Comment by bmoAtolcd** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/57495449/cf87764b-5969-4875-8af9-aec4692843af)

**Comment by E1izabeth** [comment]
Have you tried resetting UI settings? https://dbeaver.com/docs/dbeaver/Reset-UI-settings/

**Comment by bmoAtolcd** [comment]
It's ok now, thx
