### ISSUE TITLE
undescore isn't display in Database Navigator 

### ISSUE THREAD

**Issue by bmoAtolcd** [dbeaver/dbeaver#22269]
### Description

Underscores are missing in Database Navigator (database name, table name..)
![image](https://github.com/dbeaver/dbeaver/assets/57495449/c2eb825c-708c-4291-aeee-561eea8ae0a5)

![image](https://github.com/dbeaver/dbeaver/assets/57495449/f7e2c4dd-be2b-4688-9399-ea5a3f1b07a8)

### DBeaver Version

Community Edition 23.3.1

### Operating System

macOS ventura 13.4

**Comment by MashaKorax** [comment]
Cant reproduce on Sonoma

<img width="322" alt="Снимок экрана 2024-01-04 в 16 41 09" src="https://github.com/dbeaver/dbeaver/assets/84867187/4f4143c4-b187-42b1-9e4c-bb8b079846f5">

**Comment by bmoAtolcd** [comment]
I'm in dark mode.
It seem, there  is black rectangle as text background. This rectangle hide the tail of 'p' and 'g' in this picture 
<img width="308" alt="image" src="https://github.com/dbeaver/dbeaver/assets/57495449/743cf358-9e94-4697-b030-02a4dec46021">

I thing, it's same problem.

**Comment by bmoAtolcd** [comment]
I reset UI serttings, and now it's OK.
