### ISSUE TITLE
DBeaver setting SQL Assistant/Completion, the editor only assist with SQL keywords

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2226]
DBeaver - **Version 4.2.1**
DBeaver JDBC driver: **jTDS or Microsoft**
Operating System: **Windows 7 / Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

When checking the DBeaver **SQL Completion** setting **SQL Assistan/completion** - **Enable auto activation**, the editor only assist with SQL keywords when typing.

If unchecking the above setting and I type the first couple of letters of a table name and press CTRL+SPACE keyboard shortcut, the editor assist with **both** tables names (in sys, dbo) and with SQL keywords.

I would like the above setting would assist me with both table names and SQL keywords, not only the latter. As it is now I have to have the setting unchecked since it does not help me at all.

**Comment by serge-rider** [comment]
Yet another enhancement for #810

**Comment by pdanie** [comment]
Clearification: What I would like to happen is the same as I get in DBeaver when connecting to a PostgreSQL database. That the lookup suggestions contain all database table names plus the SQL script commands.

With SQL Server connection the lookup suggestions only contain SQL script commands (no table names). Only way to get the table names is to write "dbo." and then the tables names is shown. Also I can close the automatic lookup suggestion and press CTRL+BLANK to see tables names.

**Comment by sishgupta** [comment]
The workaround for me currently:
1. Driver Manager
2. Edit driver
3. Advanced parameters
4. Check Omit catalogs

This allows the automatic search to not force you to start searching with dbo. or having to ctrl-space.

Might have side effects on the displaying of objects in the Database navigator.

**Comment by andreav** [comment]
Hi,

@sishgupta advice works well for seraching but when I choose the right object, it is inserted in the editor WITHOUT the schema prefix, and the query is not valid.

Am I missing something?

Thank you!

**Comment by pdanie** [comment]
Since the functionality have been implemented and solved with the #4879 issue (with the **New Microsoft Driver**), this issue can be closed too.
