### ISSUE TITLE
GPT Chat smart completion in SQL Editor

### ISSUE THREAD

**Issue by RoiSoleil** [dbeaver/dbeaver#22276]
### Description

UI Bug for DBeaver installed in Eclipse
![image](https://github.com/dbeaver/dbeaver/assets/3462260/e7b7b8e1-18b3-462b-9ed9-daf7eaf0b727)

### DBeaver Version

23.3.1

**Comment by MashaKorax** [comment]
I reproduced it. Thanks for your bug-report!

**Comment by ShadelessFox** [comment]
It was caused by https://github.com/dbeaver/dbeaver/issues/20704. The fix is postponed to the next release (23.3.2).

**Comment by MashaKorax** [comment]
verified
