### ISSUE TITLE
dbeaver 23.3.1can't connect to google bigquery

### ISSUE THREAD

**Issue by xhpk** [dbeaver/dbeaver#22273]
### Description

After i upgrade to 23.3.1，I cant connect to bigquery. I used 23.2.5 before. I compare them. I find the driver version is the biggest different. 23.3.1 is use 1.5.0. and 23.2.5 use 1.3.3 . so maybe the latest dbeaver is not fit the bigquery driver?

### DBeaver Version

23.3.1

### Operating System

win10

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.
