### ISSUE TITLE
A query containing dollar-quoted format string causes SQL editor to run other commands unintentionally (Postgres)

### ISSUE THREAD

**Issue by philosaur** [dbeaver/dbeaver#22286]
### Description

Running a query (Execute SQL query) that contains a dollar-quoted format string causes DBeaver to run that query as well as all subsequent queries in the same editor--as if "Execute SQL script" had been run instead.

My last version of DBeaver was from probably 6 moths ago, and this behavior began when I upgraded to the Christmas Day version.

### DBeaver Version

Community Edition, vers. 23.3.1.202312241705

### Operating System

Windows 10

### Database and driver

Postgres, (PostgreSQL JDBC Driver)

### Steps to reproduce

1. Click "Execute SQL Script" or press F5 (by default) with this SQL:
```
SELECT format($$%1$s$$, 'foo');

SELECT 'bar';

SELECT 'baz1';

SELECT 'baz2';

SELECT 'baz3';
```
2. DBeaver produce five separate output tabs with output from each respective command, instead of running just the first command.  
3. Switching the dollar quotes to single quotes causes it to only run the first query, as expected.

**Comment by E1izabeth** [comment]
You can switch this preference to get the desired behavior
![image](https://github.com/dbeaver/dbeaver/assets/28875055/4665bdca-c773-484e-9f16-e8b3a62a6bde)

**Comment by philosaur** [comment]
I tried changing this setting like you suggested, and it works.  

Thank you.
