### ISSUE TITLE
GPT-3 Smart Completion in DBeaver Community 23.1.3

### ISSUE THREAD

**Issue by EduardPython** [dbeaver/dbeaver#22284]
### Description

The GPT-3 Smart Completion button in DBeaver Community 23.1.3 cannot be used.
The GPT-3 Smart Completion icon cannot be clicked on the left bar. Now a red square appears instead of the icon.
![Snímek obrazovky 2023-12-28 173912](https://github.com/dbeaver/dbeaver/assets/93093821/e8e0d19a-acc4-43c4-863c-c2920052eb80)

### DBeaver Version

Community version 23.1.3

### Operating System

Windows 10

### Database and driver

MySQL, MariaDB

**Comment by E1izabeth** [comment]
How have you installed DBeaver? As an Eclipse plugin, as a portable version or with installer?

**Comment by EduardPython** [comment]
from "dbeaver-ce-23.1.3-x86_64-setup.exe"

**Comment by E1izabeth** [comment]
Similar issue #22276

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by ShadelessFox** [comment]
The fix will be available in the next version (23.3.2).
