### ISSUE TITLE
Wrong Index type in properties/Indexes

### ISSUE THREAD

**Issue by daikoz** [dbeaver/dbeaver#22297]
### Description

In properties/indexes, index type is always Btree

### DBeaver Version

Communty Edition 23.1.0.202306041939

### Operating System

Windows 11

### Database and driver

maven:/org.mariadb.jdbc:mariadb-java-client:RELEASE
version 3.0.7

Server: Mariadb 10.5.21-MariaDB-0+deb11u1-log Debian 1

### Steps to reproduce

1. Create table:

```SQL
CREATE TABLE `Test` (
  `Id` bigint(20) NOT NULL,
  `Text` text DEFAULT NULL,
  `HasText` tinyint(1) GENERATED ALWAYS AS (`Text` is not null) STORED,
  PRIMARY KEY (`Id`),
  KEY `Test_HasText_IDX` (`HasText`) USING HASH,
)
```

2. In DBeaver, double clic on table 'Test'
3. go to "Indexes"
4. Check column "Index Type"
**Test_HasText_IDX is BTree instead of Hash**

**Comment by SaumilP** [comment]
Hi @daikoz , as per official [MariaDB](https://mariadb.com/kb/en/storage-engine-index-types/) documentation, only MEMORY (aka HEAP) storage engine supports HASH indexe-types. After adjusting provided CREATE TABLE statement of yours (removing GENERATED column & BLOB/TEXT type), I was able to create table on my local MariaDb instance. DBeaver Version 23.3.1.202312241705 is showing correct index-type as registered in .

<img width="874" alt="image" src="https://github.com/dbeaver/dbeaver/assets/1245395/a5f39f7d-58cd-4828-a4dc-4313ec7e3a7c">

For InnoDB storage engine BTREE index-type is by default used. Also, You should be able to create and confirm index-type running below statement directly through the mariadb shell.

```sql
show index from mydatabase.Test where key_name IN ('Test_HasText_IDX')
```

**Comment by daikoz** [comment]
Hi,
You are right.
It is strange SHOW CREATE TABLE Test; display hash.

I close this issue.
