### ISSUE TITLE
Connection error / can't create driver instance

### ISSUE THREAD

**Issue by NinniGy** [dbeaver/dbeaver#22295]
### Description

Hi,

I'm new to dbeaver and I'm having some issues trying to connect my first database. I already followed the advice given in another issue #18677, however I was not successful with getting it to work. Any ideas? Connection is fine, the only difference I noticed is that there's a small "x" on the sqlite logo under the driver manager. 

Thanks in advance! 

<img width="543" alt="MicrosoftTeams-image" src="https://github.com/dbeaver/dbeaver/assets/47783594/7e0c597a-356e-4f99-a1a6-415f27b32714">

### DBeaver Version

23.3.1

### Operating System

windows

**Comment by ShadelessFox** [comment]
Hello @NinniGy,

Do you have access to the provided URL in https://github.com/dbeaver/dbeaver/issues/18677#issuecomment-1373000610?

**Comment by NinniGy** [comment]
Yeah, no issues opening the url on my laptop.

**Comment by LonwoLonwo** [comment]
Hello @NinniGy 

Could you please try to download the driver manually in your connection settings?

![2024-01-03 10_54_54-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/729a47a4-254e-4b8f-9ead-4776950a7dfc)

**Comment by NinniGy** [comment]
Got it to work! Thanks!
