### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by CKrings** [dbeaver/dbeaver#22303]
### Description

When I export data I have an error: 'Table doesn't exist', but in the screen shows me all data without
![dbError](https://github.com/dbeaver/dbeaver/assets/155448444/99c6b348-4927-4d49-bf9a-81c7eb770795)
 error

### DBeaver Version

23.3.1.202312241705

### Operating System

Windows 10 Pro

### Database and driver

SQL server

### Steps to reproduce

1.  Running the SQL, is correct
2. Exporting data ->  error  --> table
![dbError](https://github.com/dbeaver/dbeaver/assets/155448444/427d66a3-102b-45c5-88a4-4ba45e6da6c7)
 doesn't exists

**Comment by Matvey16** [comment]
@CKrings I see in your description that you are using SQL Server, but on a screenshot it looks like you are using Informix driver. Can you clarify your environment more certainly for me to try and reproduce this issue?

**Comment by CKrings** [comment]
> @CKrings I see in your description that you are using SQL Server, but on a screenshot it looks like you are using Informix driver. Can you clarify your environment more certainly for me to try and reproduce this issue?

Hello !!!
I am sending you the connections settings, I hope is useful. Thank you !!
![ConSet](https://github.com/dbeaver/dbeaver/assets/155448444/d7ca6802-1d59-41b1-abb9-eabf608ba7e4)
![ConSet](https://github.com/dbeaver/dbeaver/assets/155448444/742d1619-c1ea-4301-8d6e-81650e461ffb)

**Comment by LonwoLonwo** [comment]
I see that you have another database name in your connection settings. Can you please try to copy and paste your connection and change the database name for a sigeapp in the second one? And then try to export again from the second connection SQL Editor?
The "OUTER" keyword in your Select looks Informix-specific, I'm not sure, that DBeaver can handle it.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
