### ISSUE TITLE
Discoloration in SQL editor

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#22302]
### Description

After update to 
Version 23.3.1.202312241705
SQL syntax colors are unpredictable.

Column names oscilate between purple, blue, green, gray and red with underline, table names the same except red w/ underline.

There's no system to it and no apparent rule and it doesn't match the configuration in UI -> Appearance -> Colors either.

May be related to:
I usually collect several queries in one editor and don't always close them with a semicolon, but just use empty lines between them.

### DBeaver Version

CE 23.3.1.202312241705

### Operating System

Linux, Debian/Sid

### Database and driver

Doesn't matter

**Comment by E1izabeth** [comment]
It's an intentional feature. 

Here is a settings to turn this off.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/ab996b4a-a202-4166-b28d-4a9b7294a6a6)
`Read database metadata for query analysis` turns off red highlighting which appears when you established connection to the database and the table or column you use in the query doesn't exist in the active database/schema. 
`Enable semantic analysis` adds coloring of tables, columns and their aliases.

Database actually does matter, and the specific case when it doesn't work well for you too. So please provide this information.

**Comment by 2019-05-10** [comment]
> Database actually does matter, 

So far, I've seen it with both MSSQL and PSQL.

> and the specific case when it doesn't work well for you too.

Define "specific". So far what I wrote above is all I can say -- it changes with every statement in the editor and even in a `SELECT` list of colum names it's not consistent.

**Comment by E1izabeth** [comment]
Does `Blank line is a statement delimiter` option set for you in `Preferences`->`Editors`->`SQL Editor`->`SQL Processing`?

![image](https://github.com/dbeaver/dbeaver/assets/28875055/fa01d491-6e65-45b5-abd0-f43e82e48bcb)

**Comment by E1izabeth** [comment]
And please check in the connection properties too
![image](https://github.com/dbeaver/dbeaver/assets/28875055/22cdc2cb-ac12-4b5f-b297-f9877934d44a)

**Comment by 2019-05-10** [comment]
`Blank line is a statement delimiter` is set already, connection does not have individual settings.

At least red and underlined seems to be related to not using an alias/prefix
Queries like

```
SELECT foo
FROM bar
```

_sometimes_ result in a red and underlined `foo` -- but not consistently.


A query like
```
SELECT foo, CAST(baz AS int) AS baZ
FROM bar
ORDER BY baZ
```
shows the SELECT column names in a greenish color, but the ORDER BY one in red and underlined.

For other colors I don't recognize a pattern yet.

**Comment by E1izabeth** [comment]
Thank you for explanations

**Comment by bauerp** [comment]
It is so annoying that these changes are turned on with new releases. That includes fon't and color changes. Leave them as an option but don't turn it on by default!!
