### ISSUE TITLE
underscores in connection string "Host" field are being replaced by hyphens in subsequent DNS request

### ISSUE THREAD

**Issue by ivzcoleman** [dbeaver/dbeaver#22307]
### Description

Hi, I'm trying to connect to a snowflake DB and the connection fails with the following error: 

JDBC driver encountered communication error. Message: Exception encountered for HTTP request: No such host is known (example-name-eu.eu-central-1.privatelink.snowflakecomputing.com).
  No such host is known (example-name-eu.eu-central-1.privatelink.snowflakecomputing.com)
  No such host is known (example-name-eu.eu-central-1.privatelink.snowflakecomputing.com)

However, the string as entered and displayed in the Host field is: 
example_name_eu.eu-central-1.privatelink.snowflakecomputing.com

I have other connection strings in use that are working with an underscore in the host record.  I checked the DNS logs and the hyphenated request is what is being sent from my machine causing a NXDOMAIN and a connection failure.  

Originally this happened on community version 7.3.2, I upgraded to 23.3.1 and the behavior persists.  I emptied my AppData content for both versions, but it's still replacing the underscores with hyphens.  Any help would be appreciated.

### DBeaver Version

Community Edition 23.3.1

### Operating System

Windows 11 Enterprise

### Database and driver

Snowflake JDBC 3.14.4

### Steps to reproduce

1. I create a new connection string
2. I enter the host value example_name.eu-central-1.privatelink.snowflakecomputing.com
3. I configure the Warehouse, Role, credentials, externalauth for SSO
4. I hit the test connection button
5. I am returned an error that DBeaver can not connect to "example-name.eu-central-1.privatelink.snowflakecomputing.com"

### Additional context

I have other snowflake connection strings in other regions that have underscores in the hostname.  The only difference I see is that some of these newer connection strings have multiple underscores in them... i.e. 
dev_account_eu.eu-central-1.privatelink.snowflakecomputing.com - Doesn't work
dev_account.us-east-1.privatelink.snowflakecomputing.com - Works

**Comment by LonwoLonwo** [comment]
Hello @ivzcoleman 

I did some digging and found this: https://docs.snowflake.com/en/developer-guide/jdbc/jdbc-parameters#allowunderscoresinhost

So, you need to add a new driver parameter in your connections settings:

`allowUnderscoresInHost=true`

![2024-01-04 12_40_28-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/43b87b3d-d3db-4dd1-9102-ad33f7a6c5a3)

It worked for me.

**Comment by ivzcoleman** [comment]
that worked for me as well, thank you!

**Comment by LonwoLonwo** [comment]
Thanks for the update.
I'm closing the issue then.
