### ISSUE TITLE
[Snowflake] add more SQL functions words

### ISSUE THREAD

**Issue by lokofoko** [dbeaver/dbeaver#22305]
### Description

datediff() and getdate() functions are not recognized by Dbeaver

### DBeaver Version

Community version 23.3.0

### Operating System

Win 11 PRO 23H2

### Database and driver

Snowflake, snowflake jdbc driver

### Steps to reproduce

1. Make a connection
2. Write `select getdate()` 
3. See that it doesn't change color

### Additional context

![image](https://github.com/dbeaver/dbeaver/assets/54797607/289466c1-2033-473c-8b7e-da105ec640c3)

**Comment by LonwoLonwo** [comment]
Thanks for the report @lokofoko 

The `datediff` function and more functions have better recognition in our PRO versions.
You can try it for free here https://dbeaver.com/trial/

But we do not have the `getdate` function in the list.

**Comment by rizwan-io** [comment]
Hey @LonwoLonwo 
I would like to work on this issue

**Comment by LonwoLonwo** [comment]
Hello @rizwan-io 

Here is our contribution guide: https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code

**Comment by sarveshhiwase** [comment]
> Thanks for the report @lokofoko
> 
> The `datediff` function and more functions have better recognition in our PRO versions. You can try it for free here https://dbeaver.com/trial/
> 
> But we do not have the `getdate` function in the list.

But in SQLServerDialect.java, I can see the getDate function in the list, so what can be possible issue @LonwoLonwo?

![image](https://github.com/dbeaver/dbeaver/assets/69983214/ec7fa5cf-5f59-43f1-89c7-2220702c7a14)

**Comment by sarveshhiwase** [comment]
Hello @LonwoLonwo, Please check and review the attached PR whenever possible.

Thanks & Regards
