### ISSUE TITLE
SQL Autocompletion wrong results

### ISSUE THREAD

**Issue by OMG-Abaddon** [dbeaver/dbeaver#2230]
I don't know if this has been reported already, sorry if it's a dupe.

I'm encountering errors in the SQL editor, where the autocompletion intelligence doesn't work while editing in a subselection, and doesn't suggest names within scope. For instance:
`
SELECT * FROM (
    SELECT [my_input] FROM EMPLOYEE) T1
`

The field [my_input] won't suggest entities in EMPLOYEE unless I write `EMPLOYEE.<CTRL+Space>`.

**Comment by serge-rider** [comment]
What is your database?
Because as I see this works ok in MySQL and PostgreSQL..

**Comment by Sneezor** [comment]
MS SQL Server 2014 and 2016 produce this error. Prepending the table promptly shows the correct results, but directly typing the field name will only display table names in another table specified out of this subquery, i.e. out of scope.

**Comment by SylwesterZarebski** [comment]
For me autocomplete is not working with joined tables like:
```
SELECT *
FROM table1 INNER JOIN table2 ON field1= field2
```
Could not autocomplete fields from table2 in both SELECT fields and ON clause fields. <kbm>CTRL+SPACE</kbd> shows only table1 fields.

**Comment by uslss** [comment]
@OMG-Abaddon is issue still actual for you?

**Comment by SylwesterZarebski** [comment]
Original issue is resolved, but not autocomplete in `JOIN ... ON` clause on second table fields https://github.com/dbeaver/dbeaver/issues/2230#issuecomment-333371082.

**Comment by uslss** [comment]
@SylwesterZarebski , in case issue is still actual for you, feel free to create new issue.
Original issue closed
