### ISSUE TITLE
[MySQL] The unique key is displayed as a Primary key

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#22314]
### Description

https://github.com/dbeaver/dbeaver/assets/84867187/6ece387d-1df5-4a44-8511-b0789f294c85

### DBeaver Version

DBeaver 23.3.1

### Operating System

windows 10

**Comment by LonwoLonwo** [comment]
Please check other cases.

[The documentation](https://dev.mysql.com/doc/refman/8.0/en/information-schema-columns-table.html) says: A UNIQUE index may be displayed as PRI if it cannot contain NULL values and there is no PRIMARY KEY in the table.

If a unique key shows as UNI in a table with a primary key - then it worked as expected.
