### ISSUE TITLE
Autocomplete misplaces the cursor

### ISSUE THREAD

**Issue by lucarota** [dbeaver/dbeaver#22315]
### Description

Hi all,

Auto-completion of column names incorrectly moves the cursor if there is other text on the line.

Observe the position of the cursor | in the following screencast

![dbeaver](https://github.com/dbeaver/dbeaver/assets/7235722/fc9dabae-7672-47c3-ab0d-6352948cbc42)

I want a where clause like this:
account_status in ('ACTIVE',  'SUSPENDED')
I get this:
account_status ('ACinTIVE',  'SUSPENDED')

### DBeaver Version

Community Edition 23.3.1

### Operating System

Windows 10

### Steps to reproduce

1. Click on 'Filter panel'
2. Write or paste the text ('ACTIVE', 'SUSPENDED')
3. Move the cursor at the beginning of the line and start writing the first **3 or 4** characters of the column name (the menu with the possible columns name appears)
4. Using the arrow keys move to the column name and press enter, the column name is entered and the cursor moves by **3 or 4** **(it appears to move by the number of characters used in step 3)** characters beyond the name

**Comment by E1izabeth** [comment]
Thank you for bug report. I reproduced the issue.

**Comment by sarveshhiwase** [comment]
@E1izabeth I'm working on this one, just wanted to know one thing, when we type any column word which is an autocomplete and we enter then should we keep one space at the end or there should be no space
```For Example
Without space - 
country_name|
With space -
country_name |
```
Just from my personal standpoint and experince I think it's better to have no space just like we have in IDE's, 
Please share your views on this.

**Comment by E1izabeth** [comment]
@sarveshhiwase we have a setting for that 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/0b1496b7-8ce8-43ad-a115-de2c58609e02)

Also you might need to take a look at this issue and comments #18350

**Comment by sarveshhiwase** [comment]
@E1izabeth, I have found the solution to the issue, but wanted to know in code, saw this line ->
File - [ResultSetFilterContentAdapter.java](https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetFilterContentAdapter.java#L66)
```java
// Insert will leave the cursor at the end of the inserted text. If this
// is not what we wanted, reset the selection.
if (cursorPosition <= contents.length()) {
    text.setSelection(selection.x + cursorPosition,
        selection.x + cursorPosition);
}
```

What does it actually mean? because it's saying if this is not what we wanted, reset the selection, but we always want to have cursor at the end, right?

**Comment by E1izabeth** [comment]
@sarveshhiwase unfortunately, I can't say the reason why this code was written like that. Thank you for contribution. We will review your PR soon.
