### ISSUE TITLE
DBeaver cannot start if the workspace directory is a link

### ISSUE THREAD

**Issue by denymen** [dbeaver/dbeaver#22325]
### Description

The latest DBeaver cannot start if the workspace directory is a link. For example in my case it is "D:\workspaces\dbeaver". Please see the image and logs. It was worked before the 23.3 version.
![2024-01-04 08_37_54](https://github.com/dbeaver/dbeaver/assets/44943801/9b401c6a-e4bc-4f8a-860b-f0144a3391f4)
[dbeaver-debug-1704352897590.log](https://github.com/dbeaver/dbeaver/files/13827402/dbeaver-debug-1704352897590.log)

Workaround: Use the -data flag as mentioned here: https://github.com/dbeaver/dbeaver/wiki/Workspace-Location#custom-location

### DBeaver Version

Community Edition 23.3.1.202312241705

### Operating System

Windows 11

### Steps to reproduce

1. Create link to other dir in the default workspace location
2. Try to start the app

**Comment by E1izabeth** [comment]
Another case https://github.com/dbeaver/dbeaver/issues/22360#issuecomment-1880116378

**Comment by bianyun** [comment]
I got the same issue, and the root cause in the log file is :

> Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make boolean sun.nio.fs.WindowsFileAttributes.isDirectoryLink() accessible: module java.base does not "opens sun.nio.fs" to unnamed module @262816a8

The work around is simple: add one line config in dbeaver.ini:

> --add-opens=java.base/sun.nio.fs=ALL-UNNAMED

**Comment by E1izabeth** [comment]
@bianyun thank you for workaround

**Comment by bianyun** [comment]
@E1izabeth You're welcome. It's my pleasure.
