### ISSUE TITLE
Dbeaver 23.3.1-1 crashes on Wayland

### ISSUE THREAD

**Issue by MathXCruz** [dbeaver/dbeaver#22321]
### Description

DBeaver crashses on Wayland after a few clicks, with the error I pasted on additional content. It works just fine on X11. Any older version I tried also works.

### DBeaver Version

23.3.1-1

### Operating System

Arch Linux x86_64

### Database and driver

MySQL 5.7 and MySQL 8.1 with driver mysql-connector-j 8.2.0
Postgres 15.3 with driver PostgreSQL JDBC Driver 42.5.2

### Steps to reproduce

- Open DBeaver
- Close intial dialog
- Click some stuff
- Crash

### Additional context

JVM terminated. Exit code=1
/usr/bin/java
-XX:+IgnoreUnrecognizedVMOptions
-Dosgi.requiredJavaVersion=17
-Dfile.encoding=UTF-8
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/java.nio.charset=ALL-UNNAMED
--add-opens=java.base/java.text=ALL-UNNAMED
--add-opens=java.base/java.time=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
--add-opens=java.base/jdk.internal.vm=ALL-UNNAMED
--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
--add-opens=java.base/sun.security.ssl=ALL-UNNAMED
--add-opens=java.base/sun.security.action=ALL-UNNAMED
--add-opens=java.base/sun.security.util=ALL-UNNAMED
--add-opens=java.security.jgss/sun.security.jgss=ALL-UNNAMED
--add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED
--add-opens=java.desktop/java.awt=ALL-UNNAMED
--add-opens=java.desktop/java.awt.peer=ALL-UNNAMED
--add-opens=java.sql/java.sql=ALL-UNNAMED
-Xms64m
-Xmx1024m
-jar /usr/lib/dbeaver//plugins/org.eclipse.equinox.launcher_1.6.600.v20231106-1826.jar
-os linux
-ws gtk
-arch x86_64
-showsplash
-launcher /usr/lib/dbeaver/dbeaver
-name Dbeaver
--launcher.library /usr/lib/dbeaver//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.800.v20231003-1442/eclipse_11802.so
-startup /usr/lib/dbeaver//plugins/org.eclipse.equinox.launcher_1.6.600.v20231106-1826.jar
--launcher.overrideVmargs
-exitdata 50027
-vm /usr/bin/java
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
-Dosgi.requiredJavaVersion=17
-Dfile.encoding=UTF-8
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/java.nio.charset=ALL-UNNAMED
--add-opens=java.base/java.text=ALL-UNNAMED
--add-opens=java.base/java.time=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
--add-opens=java.base/jdk.internal.vm=ALL-UNNAMED
--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
--add-opens=java.base/sun.security.ssl=ALL-UNNAMED
--add-opens=java.base/sun.security.action=ALL-UNNAMED
--add-opens=java.base/sun.security.util=ALL-UNNAMED
--add-opens=java.security.jgss/sun.security.jgss=ALL-UNNAMED
--add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED
--add-opens=java.desktop/java.awt=ALL-UNNAMED
--add-opens=java.desktop/java.awt.peer=ALL-UNNAMED
--add-opens=java.sql/java.sql=ALL-UNNAMED
-Xms64m
-Xmx1024m
-jar /usr/lib/dbeaver//plugins/org.eclipse.equinox.launcher_1.6.600.v20231106-1826.jar

**Comment by MashaKorax** [comment]
Hello @MathXCruz. What  type of installation DBeaver are you using? (deb file, sudo, flatpak)

**Comment by MathXCruz** [comment]
I'm using the tar.gz version from the site, and I also tried the arch extra repo version.

On an extra note, if I run it from terminal, when it crashes this is what is printed:

```Gdk-Message: 14:43:24.550: Lost connection to Wayland compositor.```

I also tried to fix it by following [this](https://wiki.archlinux.org/title/Dbeaver), but nothing changed.

**Comment by MathXCruz** [comment]
I just tried flatpak too and the error is the same.

**Comment by NINNiT** [comment]
I'm experiencing the same issue.
ArchLinux, installed using the official repo package and using `hyprland` as my wayland compositor

DBeaver 23.3.2.202401141053

**Comment by sgtxn** [comment]
Same, arch + hyprland. Tried official binaries from github releases, as well as the arch repo install - they both crash randomly (often when opening some table or running a query).  
The solution from [this similar thread](https://github.com/dbeaver/dbeaver/issues/19709) (adding `NO_AT_BRIDGE=1` env) seemingly does nothing.  

I ended up downgrading to `v22.3.5` for now, that one is rock solid for me.

**Comment by flambchap** [comment]
That's interesting. I've been using DBeaver on openSUSE with Plasma 5 + Wayland and with Sway without any issues. Now I'm curious if it has something to do with Hyprland. @MathXCruz What graphical environment do you use?

**Comment by MathXCruz** [comment]
I'm using Plasma 5.27.10 with kwin. Version 23.3.2 seems to have fixed the problem.

**Comment by E1izabeth** [comment]
Thank you for update. I'm closing the issue then

**Comment by dzintars** [comment]
This is how it worked for me (Fedora/Wayland/Sway):
Edit `Exec` property in `/usr/share/applications/dbeaver-ce.desktop` to `Exec=env NO_AT_BRIDGE=1 /usr/share/dbbeaver-ce/dbeaver`.
