### ISSUE TITLE
UI Font too small and not consistent with the chosen options

### ISSUE THREAD

**Issue by hotellinawebmaster** [dbeaver/dbeaver#22324]
### Description

 
![image](https://github.com/dbeaver/dbeaver/assets/73776127/ee90b339-583d-4e5a-a327-d675110417a3)
![image](https://github.com/dbeaver/dbeaver/assets/73776127/ed9442a0-2b6e-4960-b36b-b62d9b1198fc)

### DBeaver Version

Version 23.3.1.202312241705

### Operating System

Windows 11 Pro

### Steps to reproduce

- Just open the program.
- my screen is 1920x1080
- I also edited all the fonts in Preferences, but the DB Navigator and menu always show small fonts
- I also tried with the following in the .ini file, but to no avail
-vmargs
**-Dswt.autoScale=180**
-XX:+IgnoreUnrecognizedVMOptions
-Dosgi.requiredJavaVersion=17
-Dfile.encoding=UTF-8
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/java.nio.charset=ALL-UNNAMED
--add-opens=java.base/java.text=ALL-UNNAMED
--add-opens=java.base/java.time=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
--add-opens=java.base/jdk.internal.vm=ALL-UNNAMED
--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
--add-opens=java.base/sun.security.ssl=ALL-UNNAMED
--add-opens=java.base/sun.security.action=ALL-UNNAMED
--add-opens=java.base/sun.security.util=ALL-UNNAMED
--add-opens=java.security.jgss/sun.security.jgss=ALL-UNNAMED
--add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED
--add-opens=java.desktop/java.awt=ALL-UNNAMED
--add-opens=java.desktop/java.awt.peer=ALL-UNNAMED
--add-opens=java.sql/java.sql=ALL-UNNAMED
-Xms64m
-Xmx1024m
-Ddbeaver.distribution.type=zip

**Comment by serjiokov** [comment]
@hotellinawebmaster Could you specify font for main node please. It is going to apply for all product viewers.
![image](https://github.com/dbeaver/dbeaver/assets/32031248/ac204feb-c87f-4bae-80dc-f73da812b1ed)

**Comment by hotellinawebmaster** [comment]
Hello serjiokov, I changed all the fonts as specified, trust me that font you are asking is the same as others I set.
![image](https://github.com/dbeaver/dbeaver/assets/73776127/b8ab93fb-d270-4639-b207-ed58c51a07b8)

**Comment by uslss** [comment]
Unfortunately, cannot reproduce the issue. Probably some special steps are needed? maybe there is something in the [logs](https://dbeaver.com/docs/dbeaver/Log-files/#log-files)?
![image](https://github.com/dbeaver/dbeaver/assets/31996417/851bc9f0-9dfd-4014-bd6c-8ee9b09dd86e)

**Comment by MatteoR23** [comment]
@uslss I have the same issue in Dbeaver 23.3.4 with Windows 11.
The font in settings is applied until you restart the application. After that, the font is back to defaults, even if in settings I see my changes

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information asked here https://github.com/dbeaver/dbeaver/issues/22324#issuecomment-1924101038.
