### ISSUE TITLE
Wrong syntax but still updates the table

### ISSUE THREAD

**Issue by fadils** [dbeaver/dbeaver#22326]
### Description

The SQL statement:
`Update db_payments.payout_service Set status=2, current_term = 8, updated_at = now() where 123123;`

The where clause syntax was wrong. It's missing an ID (should be `where ID = 123123`).

But instead giving us a syntax error, DBeaver updates all the rows in the Payout table

### DBeaver Version

Community Edition Version 23.2.4.202311051706

### Operating System

macOS Monterey 12.4

### Database and driver

MySQL 8.1.0
com.mysql.cj.jdbc.Driver

### Steps to reproduce

Please see the description

**Comment by LonwoLonwo** [comment]
Hello @fadils 

Please provide your table DDL and data example for tests.
Footage also will be helpful.

**Comment by fadils** [comment]
DDL
-- db_payments.payout_service definition

CREATE TABLE `payout_service` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `full_id` varchar(120) NOT NULL,
  `relation_id` bigint(20) NOT NULL,
  `relation_type` varchar(255) NOT NULL,
  `version` int(11) NOT NULL DEFAULT 1,
  `user_id` bigint(20) NOT NULL,
  `termin_count` smallint(30) NOT NULL,
  `current_termin` int(11) DEFAULT 1,
  `termin_count_temp` int(11) DEFAULT 0,
  `total_amount` decimal(18,2) NOT NULL DEFAULT 0.00,
  `paid_amount` decimal(18,2) NOT NULL DEFAULT 0.00,
  `remaining_amount` decimal(18,2) NOT NULL DEFAULT 0.00,
  `status` smallint(30) NOT NULL,
  `stoped_by` bigint(20) DEFAULT NULL,
  `bill_type_id` int(11) DEFAULT NULL,
  `year_level_id` int(11) DEFAULT NULL,
  `bill_user_type` int(11) DEFAULT NULL,
  `due_date` timestamp NULL DEFAULT NULL,
  `bill_date` timestamp NULL DEFAULT NULL,
  `email_sent` tinyint(4) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `lp_learning_space_id` bigint(20) DEFAULT 0,
  `lp_learning_space_name` varchar(191) DEFAULT '',
  `lp_program_type` int(11) DEFAULT 0,
  `sync_date` timestamp NULL DEFAULT NULL,
  `learning_space_id` bigint(20) DEFAULT NULL,
  `program_type` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_due_date` (`due_date`),
  KEY `idx_full_id` (`full_id`),
  KEY `idx_payout_relation` (`relation_type`,`relation_id`),
  KEY `idx_payout_status` (`status`),
  KEY `idx_payout_user` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=225815 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

**Comment by fadils** [comment]
<img width="791" alt="Screen Shot 2024-01-04 at 17 18 32" src="https://github.com/dbeaver/dbeaver/assets/6204776/e807f9fa-a707-463e-a77f-7a0bac63ff4a">

Screenshot showing even though syntax error, but all table's rows changed

**Comment by fadils** [comment]
cc @LonwoLonwo

**Comment by serjiokov** [comment]
@fadils Sorry but DBeaver product does not seems responsiable for driver level query execution.

**Comment by ShadelessFox** [comment]
The query you've provided is completely valid. MySQL treats `123123` as a "truth" value, basically an equivalent of writing `1=1`.

You can test this by writing a simple query:
```sql
select * from db_payments.payout_service where 123123;
```
This will yield all rows in the table.

DBeaver doesn't process or emulate query execution on the client side. Instead, it communicates with the database (which is responsible for query execution) through the driver (which is responsible for sending messages between the database and the client back and forth).
