### ISSUE TITLE
Variable use for MariaDB doesn't detect period in 23.3.1

### ISSUE THREAD

**Issue by JTMosaic** [dbeaver/dbeaver#22335]
### Description

The following set of commands works as expected in 23.3.0 but asks for a value for the variable 'schema.' in 23.3.1

```
@set user=jt
@set schema=z_jt
create schema :schema;
grant all on :schema.* to :user;
```

In 23.3.0, the above commands work
In 23.3.1 this dialog is presented:

![image](https://github.com/dbeaver/dbeaver/assets/9417720/7274b123-4c69-45a9-b498-6eebab887b2d)

### DBeaver Version

23.3.1

### Operating System

MacOS 13.6

### Database and driver

MariaDB 11

**Comment by JTMosaic** [comment]
A workaround is to use the ${variable} notation but that is more typing and means retrofitting existing scripts

**Comment by E1izabeth** [comment]
Thank you for bug report.
