### ISSUE TITLE
[Documentation] is incorrect on how variable assignment works

### ISSUE THREAD

**Issue by JTMosaic** [dbeaver/dbeaver#22339]
### Description

https://dbeaver.com/docs/dbeaver/SQL-Execution/#variables-binding states that a variable can be assigned encapsulated in quotes and with a semi-colon ending a line. This is incorrect. The quotes and the semi-colon become part of the value.

![image](https://github.com/dbeaver/dbeaver/assets/9417720/270356d5-f7f3-4683-85a8-f01840f996dc)

The correct assignment is: `@set actor_name=Mark`

![image](https://github.com/dbeaver/dbeaver/assets/9417720/e51fca89-454e-478d-bc03-ba214bd2db92)

### DBeaver Version

23

### Operating System

macos 13.6

**Comment by daelynum** [comment]
Hello @JTMosaic, thank you for your comment, we fixed the documentation.
