### ISSUE TITLE
Support for indexed views on mssql

### ISSUE THREAD

**Issue by OsirisDBA** [dbeaver/dbeaver#22338]
**Is your feature request related to a problem? Please describe.**
An indexed view is the MSSQL version of PostgresSQL materialized views. It's just a view with a unique clustered index. There is nothing in the current UI to indicate that a view is indexed.

**Describe the solution you'd like**
Option 1: add an Indexes folder to views and expanding them will show any indexes
Option 2: Filter out indexed views from the normal Views folder and create a new folder for Indexed views showing the Index when viewed.
Option 3: At least when generating sql for an indexed view, also generate the index.

**Describe alternatives you've considered**
There are no UI alternatives.

**Additional context**
[Microsoft: Create indexed views](https://learn.microsoft.com/en-us/sql/relational-databases/views/create-indexed-views?view=sql-server-ver16)

**Comment by LonwoLonwo** [comment]
Thanks for the idea @OsirisDBA

**Comment by LonwoLonwo** [comment]
Closed as a duplicate of https://github.com/dbeaver/dbeaver/issues/18365
