### ISSUE TITLE
Statistics result is exported when "Show statistics tab" is Always

### ISSUE THREAD

**Issue by WEGFan** [dbeaver/dbeaver#22341]
### Description

![](https://github.com/dbeaver/dbeaver/assets/7558201/3b70a508-737c-4367-a52e-259c9056b4e4)

Run `select 1, 2, 3, 4, 5` and export the result to markdown:

|1|2|3|4|5|
|-|-|-|-|-|
|1|2|3|4|5|
|-1|select 1,2,3,4,5|Fri Jan 05 15:54:07 CST 2024|Fri Jan 05 15:54:07 CST 2024|

The result in statistic tab is appended to last row.

![](https://github.com/dbeaver/dbeaver/assets/7558201/2a159590-0b21-4a58-87cf-a8f0362c6ed1)

### DBeaver Version

Community Edition 23.3.1.202312241705

### Operating System

Windows 10

### Database and driver

Database: MySQL 5.7.34-log

Driver: MySQL Connector/J mysql-connector-j-8.2.0 (Revision: 06a1f724497fd81c6a659131fda822c9e5085b6c)

**Comment by LonwoLonwo** [comment]
Hello @WEGFan 

For now, I can't reproduce your issue.

How exactly do you export your results?

**Comment by LonwoLonwo** [comment]
Reproducible after DBeaver restart. And not just for the markdown format.

![2024-01-05 12_56_28-Window](https://github.com/dbeaver/dbeaver/assets/45152336/c108f4ab-3bdf-4248-b92d-395bab50b770)

**Comment by LonwoLonwo** [comment]
Thanks for the bug report.
