### ISSUE TITLE
Sub-queries without prompts

### ISSUE THREAD

**Issue by liuzhe101** [dbeaver/dbeaver#22340]
### Description

![image](https://github.com/dbeaver/dbeaver/assets/61652514/31412cee-c5b8-4b79-85dd-597364befca6)

### DBeaver Version

23.3

### Operating System

windows 10

**Comment by E1izabeth** [comment]
Thank you for bug report.
I'm closing it as a duplicate of #7768 #21654

**Comment by liuzhe101** [comment]
> 感谢您的错误报告。 我将其作为[#7768 ](https://github.com/dbeaver/dbeaver/issues/7768) [#21654的重复项关闭](https://github.com/dbeaver/dbeaver/issues/21654)

When will it be solved? If I don't solve this, I have to use other database tools.

**Comment by E1izabeth** [comment]
We can't give you any estimations

**Comment by liuzhe101** [comment]
> We can't give you any estimations

why? Isn’t this the most basic and more important function? It should have a higher priority than bugs, right?

**Comment by E1izabeth** [comment]
We plan to implement it, yes. I just can't say any exact date.
