### ISSUE TITLE
Dbeaver SQL server connection showing month 00 ex 2024-00-01

### ISSUE THREAD

**Issue by waterstyler-afk** [dbeaver/dbeaver#22352]
### Description

Dbeaver SQL server connection showing month 00 ex 2024-00-01
Connecting to SQL Server 2019
When I run Select queries against tables with column (date) format the month zeroes out like yyyy-00-dd

### DBeaver Version

23.3.1.202312241705

### Database and driver

SQL Server 2019
Driver group id com.microsoft.sqlserver
version 9.2.0.jre8

**Comment by ShadelessFox** [comment]
Hello @waterstyler-afk,

I can't reproduce your issue using the following script:
```sql
SELECT CAST(GETDATE() AS DATE);
```

Can you please provide more information regarding your issue and how to reproduce it?

**Comment by waterstyler-afk** [comment]
hi @ShadelessFox this is how it shows for me
![date sample](https://github.com/dbeaver/dbeaver/assets/74998655/772d0539-112c-40c3-b81c-0a05d2cb5cd1)

**Comment by ShadelessFox** [comment]
Can you please show your date formatting settings in Preferences -> Editors -> Data Editor -> Data Formats?

**Comment by waterstyler-afk** [comment]
hi @ShadelessFox - thank you I updated the date format to yyyy-MM-dd and its now fixed

**Comment by ShadelessFox** [comment]
Glad the issue was resolved. I will close the ticket now.
