### ISSUE TITLE
SHOW CREATE TABLE exports with double quotes but MySQL says there's errors with the syntax on usage

### ISSUE THREAD

**Issue by johamm** [dbeaver/dbeaver#22353]
### Description

I'm using ```SHOW CREATE TABLE``` to grab the MySQL table structure so I can copy a table over to another database.  I've noticed it's started adding double quotes around the table name, field names and index names.  However, when I go to run that query, it says there's a syntax error because of the double quotes.  

Here's what's produced:
```
CREATE TABLE "test_table" (
  "id" int NOT NULL AUTO_INCREMENT,
  "test_field1" varchar(255) NOT NULL,
  "test_field2" datetime NOT NULL,
  "test_field3" int NOT NULL DEFAULT '0',
  PRIMARY KEY ("id"),
  KEY "test_table_id_test_field1_IDX" ("id","test_field1") USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Test table';
```

### DBeaver Version

Community 23.3.1.202312241705

### Operating System

Windows 11

### Database and driver

MySQL 8 (MySQL driver)

### Steps to reproduce

1. run SHOW CREATE TABLE `table_name`
2. copy response
3. paste into editor
4. run code

**Comment by ShadelessFox** [comment]
Hello @johamm,

DBeaver doesn't alter the result of script execution. You're executing a statement on the database side; the response comes from the database itself.

Have you considered using the data transfer feature? You can read more about it on our wiki: https://github.com/dbeaver/dbeaver/wiki/Data-transfer

Please let me know if it helps.

**Comment by johamm** [comment]
Ah, sorry about that, thanks for letting me know!
