### ISSUE TITLE
Vertical scrolling with the mouse wheel is disabled when in multiple-tab layout

### ISSUE THREAD

**Issue by SFhockey7** [dbeaver/dbeaver#22356]
### Description

It seems as though vertical scrolling with the mouse wheel is disabled when in the multiple-tab layout. I've directly compared functionality to the single tab layout, which is still scrollable. Ideally, each pane should scroll while hovering, but at a minimum could at least scroll after activating the specific result pane.

### DBeaver Version

Community Edition 23.3.1.202312241705

### Operating System

Windows 10 10.0.19045

### Database and driver

SQL Server 2019 / Microsoft JDBC Driver for SQL Server

### Steps to reproduce

1. Toggle "Show results in a single/multiple tabs" setting to "multiple tabs" in the "SQL Editor" menu.
![image](https://github.com/dbeaver/dbeaver/assets/24802982/5610ab56-b579-4a05-8b91-2922d330e8ae)

3. Select multiple individual queries and simultaneously execute with the "execute SQL script" button.
4. Results appear in multiple panes at the bottom. **Attempt to scroll with the mouse wheel while hovering over a specific pane and the results do not scroll.**
5. Click within a result pane and **attempt to scroll with the mouse wheel while the pane is active. The results still do not scroll.**
![image](https://github.com/dbeaver/dbeaver/assets/24802982/bc7da9a9-95b1-45dd-b6f8-88077f261a71)

Check against default functionality:
6. Toggle the "Show results in a single/multiple tabs" setting back to "single tab" in the "SQL Editor" menu.
7. Select multiple individual queries and simultaneously execute with the "execute SQL script" button.
8. Results appear in multiple tabs at the bottom. **Scrolling with the mouse wheel while hovering over the results pane produces the desired effect of scrolling through the results.**

### Additional context

Initiated from discussion in issue #6861, fixed by #21280. 
https://github.com/dbeaver/dbeaver/issues/6861#issuecomment-1878845621

Referred by @E1izabeth to create new issue.

**Comment by E1izabeth** [comment]
Thank you for bug report.
