### ISSUE TITLE
Not Able to Generate PDF Where the ER Diagram Fits On One Page

### ISSUE THREAD

**Issue by lm-cgodwin** [dbeaver/dbeaver#22354]
### Description

I created an ER diagram that contains 21 tables. When I generate a PDF from this ER diagram, the diagram is rendered on multiple pages instead of one page. Prior to generating the PDF, I changed the page orientation to Landscape and the Paper size to A3. Is there a way to generate a PDF of an ER diagram that fits on one page?

### DBeaver Version

DBeaver Enterprise 23.3

### Operating System

Windows 11

### Database and driver

1. MS SQL Server 2019
2. MS SQL Server (PRO) 

### Steps to reproduce

1. Click the Print icon that is displayed in the bottom right toolbar.
2. Once the Printing from Win32 application modal appears, select the following options:
- Printer: Microsoft Print to PDF
- Orientation: Landscape
- Click More Settings link
- Once Printing Preferences modal appears, click the Advanced... button
- Once the Microsoft Print to PDF Advanced Document Settings modal appears, select A3 for Paper Size option.
3. Click the Print button
4. Provide a file name for the PDF file and click the Save button.
Expected outcome; ER diagram within the PDF document is rendered on one page
Actual outcome: ER diagram within the PDF document is rendered on multiple pages.
![Scheduling ER Diagram](https://github.com/dbeaver/dbeaver/assets/120387603/1827470d-228e-413b-8c85-a4974380606f)
![Printing_Preferences](https://github.com/dbeaver/dbeaver/assets/120387603/be64ddbf-1d92-40d6-b1be-d928f5fe48f0)
![Microsoft Print To PDF Advanced Document Settings](https://github.com/dbeaver/dbeaver/assets/120387603/d45f895b-8aa5-4209-8a25-12c87a00dc8b)

**Comment by ShadelessFox** [comment]
Hello @lm-cgodwin,

As a workaround, you can export to PNG and then manually add that PNG to your PDF. Otherwise, you can print PNG directly.

![image](https://github.com/dbeaver/dbeaver/assets/35821147/07aca790-20ab-4c56-a74b-f1c80b789376)

**Comment by ShadelessFox** [comment]
I just realized that we have a dedicated option for changing how the diagram is fit:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/a27b5433-9c21-4402-90bd-0d26139b0691)

Please let me know if it helps.

**Comment by lm-cgodwin** [comment]
@ShadelessFox, that worked! Thank you so much for all of your help!

**Comment by ShadelessFox** [comment]
Since the issue is resolved, I will close the ticket.

**Comment by nasrulhazim** [comment]
> I just realized that we have a dedicated option for changing how the diagram is fit:
> 
> ![image](https://private-user-images.githubusercontent.com/35821147/295556713-a27b5433-9c21-4402-90bd-0d26139b0691.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTMxMDQsIm5iZiI6MTcxMDc1MjgwNCwicGF0aCI6Ii8zNTgyMTE0Ny8yOTU1NTY3MTMtYTI3YjU0MzMtOWMyMS00NDAyLTkwYmQtMGQyNjEzOWIwNjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA5MDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZjcxNDdhMzU5MGE1OGRhNDE0YWMyOTkwYjA5MjM3YTg5MzUyMGZmOTFjYjljNzgwODMwZDRmMzE0ZWZkMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4PdyQWylKXjXme_nD29VKRpXQb4jLs3d30gG1G14AxI)
> 
> Please let me know if it helps.

works like a charm! thank you!
