### ISSUE TITLE
"show column description in header" disappearance of content

### ISSUE THREAD

**Issue by MrLuke1110** [dbeaver/dbeaver#22367]
### Description

The version is 23.3.2, and after the update, the description is missing. It doesn't appear even after refreshing.

version 23.3.2
![image](https://github.com/dbeaver/dbeaver/assets/66194793/51d181bd-91e9-4e4f-9532-99e779630e9f)

version 23.3.1
![image](https://github.com/dbeaver/dbeaver/assets/66194793/abb9d988-7116-4004-a305-bfbf3072cf3c)

### DBeaver Version

Community Edition 23.3.2

### Operating System

Windows 10 22H2

### Database and driver

DB2 / Db2 for IBM i

### Steps to reproduce

Upon installing the new version, the link data is presented immediately.

**Comment by ShadelessFox** [comment]
Thanks for the bug report
