### ISSUE TITLE
Misleading info on Clean option for PostgreSQL restore

### ISSUE THREAD

**Issue by m-irc-o** [dbeaver/dbeaver#22369]
### Description

When you restore a backup on an existing database there is the "Clean" option.  
![image](https://github.com/dbeaver/dbeaver/assets/110528956/6c8ef8f6-04e2-44fe-8ab6-94fda41fd27e)

The text says that the current database will be delete and recreated. But it seems that it will only drop the tables that are contained in the restored backup. So tables existing in the database but not in the backup will remain and with this there were further issues with primary and foreign keys after the restore.

Either the database is really recreated if this option is checked or the description of this option shall be adjusted.

### DBeaver Version

Community Edition 23.3.2.202401072024

### Operating System

Windows 10

### Database and driver

1. Database version PostgreSQL 15.0
2. Driver PostgreSQL JDBC Driver

### Steps to reproduce

Restore a backup on an existing database

**Comment by E1izabeth** [comment]
Yes, this checkbox is to specify `--clean` option to `pg_restore` tool. And with this option the tool will only drop and re-create the tables (or other objects) that are part of the dump. It will not touch any objects that are not part of the dump.
Thank you for pointing out to misleading description.
