### ISSUE TITLE
Syntax coloring indicates error on object in lower case even without double-quote [SNOWFLAKE]

### ISSUE THREAD

**Issue by Thomas-LEILLET-Sanofi** [dbeaver/dbeaver#22368]
### Description

In Snowflake DB, name of DB objects (schema, tables, fields etc.) are by default interpreted as uppercased from the SQL Client, unless (and only unless) the name is explicitely enclosed by double quote.
For instance, the standard schema `INFORMATION_SCHEMA` and its standard view `TABLES` can be either reached out to via calling them `INFORMATION_SCHEMA.TABLES`, `information_schema.tables`, `inForMatioN_SChema.TablEs` etc. The SF engine will always look for `INFORMATION_SCHEMA.TABLES`.

Only if you use double-quotes, then only the case is taken into consideration : `INFORMATION_SCHEMA` <> `"information_schema"`.

However, the newly added auto-coloring feat in DBeaver, indicating potential errors in syntax, takes the case in consideration even without double-quotes...

![image](https://github.com/dbeaver/dbeaver/assets/130557869/96e50e0f-c1fa-4bbf-ad4f-4a0e34ee1e5b)
 vs
 
![image](https://github.com/dbeaver/dbeaver/assets/130557869/44943fbc-7eee-4bfb-adc4-ebc5e1eedeff)

### DBeaver Version

CE Version 23.3.2.202401072024

### Operating System

Win11 23H2 (Build 22631.2715)

### Database and driver

Snowflake via JDBC 3.13.29

### Steps to reproduce

(see screenshots provided)

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by ufuk-ergin-carbon** [comment]
I also see this problem on Mac 14.2.1 Sonoma with DBeaver version updated to Version 23.3.2.202401072024 today. Screenshots attached. There is no error, all the aliases are fine, but then again if you write the table and field names in caps, it is fine. But, if you write them in lower cases, it highlights them red. Let me know if you need logs.

![Screenshot 2024-01-08 at 15 25 10](https://github.com/dbeaver/dbeaver/assets/114302087/6b14022a-fc67-492f-a4d6-9005a15ddd9b)
![Screenshot 2024-01-08 at 15 29 21](https://github.com/dbeaver/dbeaver/assets/114302087/62812e72-92da-4c61-9481-a1690d2a97e0)

**Comment by E1izabeth** [comment]
@ufuk-ergin-carbon is it Snowflake too?

**Comment by ufuk-ergin-carbon** [comment]
> @ufuk-ergin-carbon is it Snowflake too?

Hi @E1izabeth , yes, I am also using Snowflake.

**Comment by E1izabeth** [comment]
We will investigate and fix it. As a temporary workaround if you don't want to see red highlighting, you can turn it off here.

![image](https://github.com/dbeaver/dbeaver/assets/28875055/bf80edcb-fc10-4e92-aac9-6bac815fc1b5)

**Comment by ufuk-ergin-carbon** [comment]
> We will investigate and fix it. As a temporary workaround if you don't want to see red highlighting, you can turn it off here.

What I did is this for the time being as a workaround: I went to the connection by right clicking, Edit Connection, then changed the Insert case under Code Completion to Default (previously set to lowercase).

**Comment by Thomas-LEILLET-Sanofi** [comment]
Leillet, Thomas /FR/EXT reacted to your message: [like]
