### ISSUE TITLE
Unable to see Oracle packages

### ISSUE THREAD

**Issue by btaing** [dbeaver/dbeaver#2237]
I have attached two screenshots to illustrate an issue I found in DBeaver. One screenshot shows Oracle SQL Developer, which allows me to see the developed packages. The other is the equivalent screenshot from DBeaver, which does not show the packages. 
![packages - oracle sql dev](https://user-images.githubusercontent.com/7122665/31024085-cf778f80-a4f2-11e7-8328-df15fb97ba28.png)
![packages - dbeaver](https://user-images.githubusercontent.com/7122665/31024084-cf5680c4-a4f2-11e7-8567-8c4832b96df9.png)

**Comment by serge-rider** [comment]
Does this happen with all schemas/packages or this schema is special?
DBeaver execute following SQL to read packages:
```sql
SELECT * FROM SYS.ALL_OBJECTS 
WHERE OBJECT_TYPE='PACKAGE' AND OWNER='AUS_SD'  
ORDER BY OBJECT_NAME
```
Does it return any results in your case?
If yes - please check error/debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files) for any errors during packages loading.

**Comment by btaing** [comment]
I'm not the DBA, but I suspect it's special. When I execute your SQL, DBeaver and Oracle SQL Developer returns 0 records. The only thing I can think of is possibly a permissions issue...but it's odd that I can see the packages in Oracle Developer.

**Comment by premyslc** [comment]
Some tools (like PL/SQL Developer) has option to use dba_objects (if available) instead of all_objects. Packages are not in all_objects view, even if user is able to see source code. In the other words. User needs execute privilege on a package to see it in all_views. Imho there is no of such option in DBeaver :-(

**Comment by p91paul** [comment]
yeah, this applies to all objects, not just packages. For example I have a user which can query all dba_* tables, but has basically no other privilege. This means that in other tools I see all the tables/views/functions/whatever with their attributes (e.g. primary keys, columns, indexes) even if I am not able to view data on them or execute them. In dbeaver I see an empty database with that user!

**Comment by serge-rider** [comment]
Currently DBeaver heavily relies on views SYS.ALL_*. OF course it won't show anything if these views are missing.
We also could add such option (use DBA_ views wherever it is possible). Please create a separate feature request for that.

**Comment by camillepicolet** [comment]
Good job @serge-rider , it's fixed now, and it's much better with all objects displayed ! :)

**Comment by camillepicolet** [comment]
Actually there is still the exact same issue with schemas : some schemas that are displayed in Oracle SQL Developer are not in DBeaver

**Comment by serge-rider** [comment]
@camillepicolet Please check option "Hide empty schemas" in connection settings->Oracle Properties

**Comment by camillepicolet** [comment]
@serge-rider Perfect, that was the solution, thanks again !

**Comment by akoylu** [comment]
In my case I fixed it by by checking Always use DBA_* views.

**Comment by ev-i** [comment]
Actually there is still the exact same issue with procedures, functions insdie a package.

**Comment by erso1925** [comment]
I was also not able to see the whole packages on DBeaver, but I was able to see them on Oracle SQL Developer with the very same DB connection and schema. My problem is fixed after turning on the option of: Edit connection → Oracle properties → "Always use DBA_* views" → True (On)
