### ISSUE TITLE
aliases' re-use auto-coloration are inconsistant

### ISSUE THREAD

**Issue by Thomas-LEILLET-Sanofi** [dbeaver/dbeaver#22374]
### Description

Hello, small example : in Snowflake, one can reuse in WHERE clause (for instance) aliases declared in SELECT section. But the syntaxic color feat loses its mind and does not manage to remain consistant throughout the SQL sentence.... (3 ways to test it : )

![image](https://github.com/dbeaver/dbeaver/assets/130557869/dbba872a-0ce2-4b21-956a-f8a2c1f001b4)
![image](https://github.com/dbeaver/dbeaver/assets/130557869/77800fea-7de1-484d-947d-e8b0966847bb)
![image](https://github.com/dbeaver/dbeaver/assets/130557869/4bfde029-bbbb-47a6-8ae0-8438a6e471b4)

### DBeaver Version

CE Version 23.3.2.202401072024

### Operating System

Win11 23H2 (Build 22631.2715)

**Comment by E1izabeth** [comment]
Thank you for bug report. We will investigate and fix it. As a temporary workaround if you don't want to see red highlighting, you can turn it off here.

![image](https://github.com/dbeaver/dbeaver/assets/28875055/bf80edcb-fc10-4e92-aac9-6bac815fc1b5)

**Comment by robertopalloni** [comment]
Same here 
<img width="334" alt="image" src="https://github.com/dbeaver/dbeaver/assets/135619816/c1c25d4d-1d1a-487a-85d7-05d0e3195e0d">

The workaround worked randomly btw. 
I have some fields still red and underlined and, on the contrary, some schemas and tabs are not coloured.
<img width="325" alt="image" src="https://github.com/dbeaver/dbeaver/assets/135619816/0368e613-9656-4fa0-bd7a-28429b70312b">

**Comment by benjdv** [comment]
@E1izabeth, thanks for mentionning the option to deactivate this comportment and return to a normal coloration.

Some points in the same sens of previous writers
- Same problem appears (with Postgres) if you specify the active schema for prefixing table
- Doesn't work with "WITH query", table and/or field are surligned in red
- If you put field (columns ony) into double quote '"' the surligned red dissapears althought it's the same identifier

**Comment by E1izabeth** [comment]
The issue fix is available in the Early Access version (https://dbeaver.io/files/ea/) and will be included in the next release.
