### ISSUE TITLE
semantic analysis doesn't work as intended

### ISSUE THREAD

**Issue by prottach** [dbeaver/dbeaver#22385]
### Description

Everything uppercase
![image](https://github.com/dbeaver/dbeaver/assets/52564630/d01ad8f3-cdef-4099-ba58-b13e25b77e8e)

Library lowercase
![image](https://github.com/dbeaver/dbeaver/assets/52564630/4571ce6e-fa9c-4e4a-b26f-82d68a2ef95d)

"Read database table/columns for semantic analysis" turned off
![image](https://github.com/dbeaver/dbeaver/assets/52564630/3421568c-ab5e-4298-aaa3-5667d4c5f9e6)

With the setting "Enable semantic analysis (experimental)" on, I have to write everything in capital letters, otherwise it marks tables and columns as errors. 
Turning off "Read database table/columns for semantic analysis" still marks columns as Errors. 
I use DB2 for IBM i connection.
I have no problems with mysql, regardless of whether I use upper or lower case.

Didn't have this issue with 23.3.1 

### DBeaver Version

23.3.2

### Operating System

Windows 10

### Database and driver

![image](https://github.com/dbeaver/dbeaver/assets/52564630/ed0cecf5-6988-4dbd-b9ed-c717dca35a76)

### Steps to reproduce

1. Open a DB2 for IBM i Connection 
2. Write any SELECT statement with everything uppercase --> no problems
3. Change library or table to lowercase  --> marked as false but executable

**Comment by E1izabeth** [comment]
Thank you for bug report.
