### ISSUE TITLE
column filter set for wrong column

### ISSUE THREAD

**Issue by poltpolt** [dbeaver/dbeaver#22397]
### Description

I run a query 
something like
SELECT t1.id, t1.code, CONCAT(t2.code,t2.name) as person FROM t1 LEFT JOINT t2 on (t2.id=t1.id)
with a number of columns additional columns  that it returns.
When I triy to quick filter on value from 'person' i Select the values 'my1'  and 'my2' from a list provided by dbeaver but it gets converted to wrong quickfilter string where it says  
code IN ('my1','my2')
instead of supposed
person IN ('my1','my2')

Looks like column index bug or maybe the coinsidence of .code in both t1 and t2 makes it puzzle.

### DBeaver Version

23.3.2

### Operating System

Linux Opensuse

### Database and driver

Mariadb

### Steps to reproduce

run a query 
something like
SELECT t1.id, t1.code, CONCAT(t2.code,t2.name) as person FROM t1 LEFT JOINT t2 on (t2.id=t1.id)
with a number of columns additional columns  that it returns.
When I triy to quick filter on value from 'person' i Select the values 'my1'  and 'my2' from a list provided by dbeaver but it gets converted to wrong quickfilter string where it says  
code IN ('my1','my2')
instead of supposed
person IN ('my1','my2')

**Comment by MashaKorax** [comment]
Hello @poltpolt Could you please provide your tables DDL?

**Comment by poltpolt** [comment]
I cannot reproduce it anymore
