### ISSUE TITLE
Support for Dameng user and role

### ISSUE THREAD

**Issue by Stkai** [dbeaver/dbeaver#22396]
Support for Dameng user info and role info.
https://github.com/dbeaver/dbeaver/pull/22391
![图片](https://github.com/dbeaver/dbeaver/assets/24271418/f262989a-3c66-4fc0-ae32-537c1dd64106)
![图片](https://github.com/dbeaver/dbeaver/assets/24271418/e3c21fdf-b03f-4f25-b069-2f64add16b6b)

**Comment by LonwoLonwo** [comment]
Thanks again for your contribution @Stkai!

Changes will be available in the next release on 22-01-2024.
