### ISSUE TITLE
Microsoft Store version broken since 23.3.2.0

### ISSUE THREAD

**Issue by treysis** [dbeaver/dbeaver#22405]
### Description

Once again it seems the Microsoft Store release was not tested?

Anyway, I just installed the update and now DBeaver CE won't open anymore. It probably does something but fails silently. No error message or anything. Where do I find the logs?
Now I can't do anything until it's fixed 😢 No going back to old version possible.

### DBeaver Version

Community Edition 23.3.2.0

### Operating System

Windows 10 22H2 19045.3930

### Steps to reproduce

1. Install DBeaver CE from Microsoft Store
2. Try to start DBeaver CE

**Comment by LonwoLonwo** [comment]
Hello @treysis 

Thanks for the bug report.

As a workaround for now - you can download DBeaver here https://dbeaver.io/download/

**Comment by treysis** [comment]
> As a workaround for now - you can download DBeaver here https://dbeaver.io/download/

Thx. Unfortunately, this doesn't restore my session :/

**Comment by serge-rider** [comment]
Thank you for the report.
It is a known issue, we are working on it. We also want to update DBeaver version in Store to the latest one.

Note: Microsoft Store app is broken because apparently it is not possible to test application before it was published. 
It passes all verifications and certifications but eventually doesn't work. So we have to do some code changes (blindly), publish it again and retest. It takes a lot of time :(

**Comment by mwnu** [comment]
> Thank you for the report. It is a known issue, we are working on it. We also want to update DBeaver version in Store to the latest one.
> 
> Note: Microsoft Store app is broken because apparently it is not possible to test application before it was published. It passes all verifications and certifications but eventually doesn't work. So we have to do some code changes (blindly), publish it again and retest. It takes a lot of time :(

The same issue exists in the latest version 23.3.21.0. Can you please revert to the previously working version until the issue is fixed?

**Comment by treysis** [comment]
Same for me. 23.3.21.0 still fails silently. Where can I find the logfile to shed some light on the issue? It seems it's failing before DBeaver core is even started as the last log I can find is from before the last working update.

**Comment by serge-rider** [comment]
DBeaver CE was updated in MS Store. 
Please check

**Comment by virgoparna** [comment]
Third update (for me) today seems to work again.
Version 23.3.2.202401100101 once again opens.

**Comment by Matvey16** [comment]
Verified

**Comment by treysis** [comment]
What was the issue after all?
