### ISSUE TITLE
Why do MySQL procedure queries appear with multiple lines when dumping?

### ISSUE THREAD

**Issue by kho96** [dbeaver/dbeaver#22400]
### Description

When creating a procedure and dumping the corresponding database, the queries of the procedure are generated with line breaks, spanning more than one line. Why does this happen?

As shown in the picture below
![스크린샷 2024-01-10 174543](https://github.com/dbeaver/dbeaver/assets/119104915/5511460c-e012-4c30-9450-adeb643c5571)

### DBeaver Version

Commnity Edition 23.3.0

**Comment by LonwoLonwo** [comment]
Hello @kho96 

For now, I can't reproduce your issue.

![2024-01-10 13_25_57-dump-test-test-202401101122 — C__Users_anvolka_work — Atom](https://github.com/dbeaver/dbeaver/assets/45152336/340f266a-84fd-41f7-9a79-44599c25e838)

What database server version do you use?
What native client version did you use?
You can find this info here:

![2024-01-10 13_27_42-DBeaver Ultimate 23 3 2 - _localhost 7_ test apply](https://github.com/dbeaver/dbeaver/assets/45152336/722f15b9-69a3-4191-be50-cd81494c16cb)

Additionally, please provide a screen of the DDL of your procedure in DBeaver.

**Comment by kho96** [comment]
Thank you  @LonwoLonwo 
i want mysql 5.8 version to 8.0 .
and local client version **Mysql Binaries**

**Comment by LonwoLonwo** [comment]
Does your original DDL have a blank line inside? Could you please provide a screen and text DDL example for tests?

**Comment by kho96** [comment]
@LonwoLonwo 

`
CREATE DEFINER=`test`@`%` PROCEDURE `test`.`PK_test_INSERT`(
	in P_USER_NM varchar(100),
	in P_USER_EMAIL varchar(200),
	in P_HP_NO varchar(20),
	in P_INQUIRY_CONTENT NVARCHAR(4000),
	out OUT_MSG NVARCHAR(4000)
)
    COMMENT 'test'
begin
	/*
	* 작성자 : test
	* 작성일 : 2024. 1. 19.
	* 기능 : test
	* 
	* [파라미터]
	*@P_USER_NM : t
	*@P_USER_EMAIL : t
	*@P_HP_NO : t
	*@P_INQUIRY_CONTENT : t
	*@OUT_MSG : t
	*
	*/
	declare V_INQUIRY_NUM INT;
	DECLARE V_STATE VARCHAR(5);
	DECLARE V_ERR_NO VARCHAR(10);
	DECLARE V_ERR_MSG VARCHAR(4000);
	
	DECLARE EXIT handler FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 
					V_STATE = RETURNED_SQLSTATE , 
					V_ERR_NO = MYSQL_ERRNO , 
					V_ERR_MSG = MESSAGE_TEXT;
			ROLLBACK;
			SET OUT_MSG = V_ERR_MSG;
		END;
	
	START TRANSACTION;

	select IFNULL(MAX(INQUIRY_NUM) + 1, 1) INTO V_INQUIRY_NUM FROM tb_base_inquiry;
	
	insert into tb_base_inquiry(INQUIRY_NUM, USER_NM, USER_EMAIL, HP_NO, INQUIRY_CONTENT, REG_DT, INQUIRY_STATE)
	values( V_INQUIRY_NUM, P_USER_NM, P_USER_EMAIL, P_HP_NO, P_INQUIRY_CONTENT, CURRENT_TIMESTAMP(), (select piu_dent.FN_CODE_NM('001000000000000', '004001000000')) );
	
	SET OUT_MSG = "OK";
	COMMIT;
end
`

These are just some procedures.
Comments are not moved when creating a procedure or function, and lines continue to appear in version 8.0.

**Comment by LonwoLonwo** [comment]
I'm unsure what we can do from the DBeaver side here because the result text is generated from the MySQL dump tool.
You can try to find any special parameter to avoid empty strings, maybe https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html
You can add these parameters on the "Export configuration" page.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
