### ISSUE TITLE
Small font/graphical errors in 23.3.1/2 vs 23.3.0

### ISSUE THREAD

**Issue by JTMosaic** [dbeaver/dbeaver#22412]
### Description

In 23.3.1 and 23.3.2 the fields in the Projects window are sometimes cut off:

![image](https://github.com/dbeaver/dbeaver/assets/9417720/dd338b5f-3083-43be-b506-0891af9a12f9)

where they are not in 23.3.0:

![image](https://github.com/dbeaver/dbeaver/assets/9417720/c62be78b-2d12-4e50-bc43-2a71779dbf2f)

It seems there is some kind of invisible border in 23.3.1/2 which moves when a longer field is expanded but is too aggressive otherwise.

This could be an Eclipse 2023-12 vs 2023-09 issue?

### DBeaver Version

23.3.1 or 23.3.2

### Operating System

macOS 14.2.1

**Comment by MashaKorax** [comment]
Hello, @JTMosaic. Please provide more clear steps to reproduce. It's working okey for me.
<img width="227" alt="Снимок экрана 2024-01-18 в 10 56 57" src="https://github.com/dbeaver/dbeaver/assets/84867187/59cf4d8d-dddd-480c-a8b9-71acd98f1f7e">

**Comment by JTMosaic** [comment]
I have no steps to produce other than being on macOS 14.2.1 and using DBeaver 23.3.2.

However, let me add this: If you have anything in the projects list below the test.server.name server which is longer (extends further to the right) then the invisible border is pushed to the right and you may not see it.

May I suggest trying to create a new project that appears last in the list and collapse all of the others? You can see in the screenshots below, each time I expand the previously cut off letter becomes whole.

![image](https://github.com/dbeaver/dbeaver/assets/9417720/4e0aad92-ddb7-494a-a067-1d57e9800402)
![image](https://github.com/dbeaver/dbeaver/assets/9417720/fb47edb6-4001-416d-8d9a-0abc106729de)
![image](https://github.com/dbeaver/dbeaver/assets/9417720/bbb119af-28e8-4b8b-b721-8bb16a97d907)

**Comment by JTMosaic** [comment]
Here's another example, real world usage:

![image](https://github.com/dbeaver/dbeaver/assets/9417720/04559281-04eb-4f5f-a33d-76a8710cc836)

Then, when I expand the Triggers below:

![image](https://github.com/dbeaver/dbeaver/assets/9417720/97a4ef82-aeb9-4de1-af12-aa9a35e3d42a)

**Comment by humphreygao** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt/pull/969

**Comment by E1izabeth** [comment]
We updated Eclipse, so we expect this issue should be solved now. Can you reproduce it on DBeaver 24.0.4?

**Comment by JTMosaic** [comment]
Fixed in 24.0.4. Thanks!
