### ISSUE TITLE
[GaussDb] An index of a table in the database is displayed as a table type in dbeaver，But it's not a table

### ISSUE THREAD

**Issue by guyu818** [dbeaver/dbeaver#22419]
### Description

In GaussDB，I created a Partition Table  and index01,when I use dbeaver to display all tables of this schema. I found an index is displayed as a table in dbeaver table list. The situation is as shown in the picture below.
![20240111-162921(WeLinkPC)](https://github.com/dbeaver/dbeaver/assets/48854614/5f5e3740-ae64-4dea-b4fb-1904e54b364e)
And the table struct like this picture below
![2](https://github.com/dbeaver/dbeaver/assets/48854614/ce83cde0-69d8-46db-a7bf-e78dd44a5e2e)

### DBeaver Version

CE Version 23.3.2.202401072024

### Operating System

Windows 11

### Database and driver

DataBase:GAUSSDB 3.x
Driver: openGauss.jar 3.x

### Steps to reproduce

(see screenshots provided)

**Comment by guyu818** [comment]
Description information not enough

**Comment by E1izabeth** [comment]
@guyu818 you can edit it 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/1953caca-942b-4943-925d-ec5756027c6a)

**Comment by arhayka** [comment]
Hi @guyu818!
Is this still an issue? Did you close it accidentally?
