### ISSUE TITLE
Use eclipse's plug-in update system to upgrade dbeaver

### ISSUE THREAD

**Issue by fallingrock** [dbeaver/dbeaver#22410]
I install dbeaver using the tar.gz file in my home directory.

Updating the application requires downloading the current version and extracting it into the directory.

Eclipse has a very good plug-in update mechanism ... I'd really like to have dbeaver use that functionality to install updates, so I don't have to manually download the whole thing.

If I use the Help -> Install new software route, it appears I can update that way ... but it would be nicer if update check could be automatic and/or invoked from the "Check for updates" menu options.

**Comment by E1izabeth** [comment]
Thank you for report.
I guess you might be interested in this workaround https://github.com/dbeaver/dbeaver/issues/5317#issuecomment-1242878205 while it's not implemented.

**Comment by hrimthrusa** [comment]
Closed as a duplicate #5317
