### ISSUE TITLE
SELECT korean data was broken in specific column_name

### ISSUE THREAD

**Issue by conquermay** [dbeaver/dbeaver#22418]
### Description

Hello,

I created table and Insert Korean data in column

I found that some data in specific column_name was broken 

I attached some error captures. please refer to it
(mgr_hnm -> Selected broken data)
(mgr_hnma -> Selected normal data)

I want to know If it is a bug
![KakaoTalk_20240111_170019052_01](https://github.com/dbeaver/dbeaver/assets/139723102/a20bc045-0ebe-495b-a510-fa9594d6232a)
![KakaoTalk_20240111_170019052_02](https://github.com/dbeaver/dbeaver/assets/139723102/85c7bf83-97bd-4346-ab99-30f9181afd99)

### DBeaver Version

Community Edition 21.0.1

### Operating System

Microsoft Windows 10 Enterprise LTSC

**Comment by conquermay** [comment]
version :  PostgreSQL 15.4 on x86_64-pc-linux-gnu

**Comment by LonwoLonwo** [comment]
Hello @conquermay 

Could you please check two things?

1. Please change the data view to the Text one. Is the value also incorrect there?

![2024-01-11 12_23_49-SELECT korean data was broken in specific column_name · Issue #22418 · dbeaver_d](https://github.com/dbeaver/dbeaver/assets/45152336/e234f734-b9ec-49a1-b005-6e1ccba8c6e7)

2. Is your value correct in the console or other places where you can check the value in your database?

3. Please provide clear steps to reproduce. I see different commands in your script, and it is unclear - which queries were executed (like column rename). And which - not.

**Comment by conquermay** [comment]
Hello, @LonwoLonwo

1. Please change the data view to the Text one. Is the value also incorrect there?
: Yes, Text data is also incorrect

2. Is your value correct in the console or other places where you can check the value in your database?
: I checked the value in the console, and I confirmed that data is correct

3. Please provide clear steps to reproduce. I see different commands in your script, and it is unclear - which queries were executed (like column rename). And which - not.
: here is my script

--script 1
create table test (mgr_hnm varchar(60));
insert into test VALUES ('abcde');
UPDATE test SET mgr_hnm='가나다라마';
SELECT * from test;
=> data was incorrect

--script 2
create table test (mgr_hnma varchar(60));
insert into test VALUES ('abcde');
UPDATE test SET mgr_hnma='가나다라마';
SELECT * from test;
=> data was correct

Please leave a comment if you need more information.

**Comment by conquermay** [comment]
english data also incorrect when using column_name "mgr_hnm"
![KakaoTalk_20240112_135125731](https://github.com/dbeaver/dbeaver/assets/139723102/78d93e02-7d2f-448e-ba80-6887a21f9d92)
I think it is a bug

**Comment by conquermay** [comment]
numeric data also incorrect when using column_name "mgr_hnm"
![KakaoTalk_20240112_153439267](https://github.com/dbeaver/dbeaver/assets/139723102/e9594f75-e316-47e1-87ba-1402a3880165)

**Comment by LonwoLonwo** [comment]
I can't reproduce your issue, unfortunately.

![2024-01-12 12_23_21-DBeaver Ultimate 23 3 3 - _postgres 6 1_ Script-122](https://github.com/dbeaver/dbeaver/assets/45152336/148e7a75-77b8-4b5a-9686-17b4893f5999)

And you closed this ticket. Could you let me know if you found the answer?

**Comment by conquermay** [comment]
yes, I found the answer, The problem occurred due to the masking function of the DB access control solution called dbsafer

it wasn't a bug

**Comment by LonwoLonwo** [comment]
Thanks for the answer
