### ISSUE TITLE
An error has occurred. See the log file Null

### ISSUE THREAD

**Issue by hugocelso** [dbeaver/dbeaver#22416]
### Description

Hello.
I have a small team, and we use DBeaver CE/Git for a while (great tool, many thx).
We work on remote desktops, we have our own server (RDS), same software for everyone in the team, and we are upgrading from Windows Server 2016 to Windows Server 2022. Windows Server 2016 always worked/works fine, but we are noticing some problems in Windows Server 2022.
Installation is regular (for everyone, I reinstalled at least 5 times), but oddly only the first user can open DBeaver CE, after the first user opens DBeaver the others get "An error has occurred. See the log file Null" right away and nothing happens.
I did a few steps already:
added -Ddbeaver.trace.enabled=true to dbeaver.ini (not sure if helped)
found the critical messages at log files at \Program Files\DBeaver\configuration

!SESSION 2024-01-10 21:36:38.371 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en

!ENTRY org.eclipse.osgi 4 0 2024-01-10 21:36:38.809
!MESSAGE Error reading configuration: \Program Files\DBeaver\configuration\org.eclipse.osgi\.manager\.fileTableLock (Access is denied)
!STACK 0
java.io.FileNotFoundException: \Program Files\DBeaver\configuration\org.eclipse.osgi\.manager\.fileTableLock (Access is denied)

And headed up to the directory. Here's the reason for my post, the file ".fileTableLock" is readable for Users, but only full control for the first user that opened DBeaver!
I changed permissions to Full Control on "Users" and removed the permissions for the associated (single) user in control. Now all users can open DBeaver, I hope it helps.

With admin rights I could always open DBeaver if it matters.

This happens with dbeaver-ce-21.3.4-x86_64 and with dbeaver-ce-23.3.1-x86_64, I tried with both, but this fix was done (like one hour ago) with the dbeaver-ce-23.3.1-x86_64, and I will not return to a previous version to test the fix, I still have problems with the "Install New Software..."/"Installation Information" options (nothing happens), to have Git/Office plugins working.

The reported problems only exist in Windows Server 2022, in the old server Windows Server 2016 everything works without problems.

(As a side note, upgrading DBeaver CE from dbeaver-ce-21.3.4-x86_64 to dbeaver-ce-23.3.1-x86_64 changed the plugins architecture at Windows Server 2016, at dbeaver-ce-21.3.4-x86_64 as admin I could install git/office plugins once for everyone, at dbeaver-ce-23.3.1-x86_64 it seems every user needs to install them, but at least no need for admin rights.)

Best regards. Great work/great tool.

### DBeaver Version

dbeaver-ce-23.3.1-x86_64

### Operating System

Windows Server 2022

### Database and driver

N/A

### Steps to reproduce

I suppose multiple users on Windows Server 2022, install DBeaver, the first user gets the app running, and the others can't run DBeaver.

**Comment by hugocelso** [comment]
PS: Problems with the "Install New Software..."/"Installation Information" options (nothing happens), are more or less the same thing.
Log files are at user\AppData\Roaming\DBeaverData\workspace6\.metadata

!ENTRY org.eclipse.e4.ui.workbench 4 0 2024-01-10 21:40:00.186
!MESSAGE Command 'org.eclipse.equinox.p2.ui.sdk.install' failed
!STACK 0
org.eclipse.core.commands.ExecutionException: Error executing 'org.eclipse.equinox.p2.ui.sdk.install': java.lang.IllegalStateException: Profile not locked due to exception: \Program Files\DBeaver\p2\org.eclipse.equinox.p2.engine\profileRegistry\DefaultProfile.profile\.lock (Access is denied)

File ".lock" is read only for all users, no user can use the features "Install New Software..."/"Installation Information", after changing to full control to users, it's working. I was able to install git/office plugins.

**Comment by hugocelso** [comment]
I was checking follow ups on this thread (no worries for me, I have everything working), and I noticed two other problems (issues) I crossed, here is my feedback, as they happened in the same setup (one after the other).
[DBeaver is not identifying the driver class from jar file #22430](https://github.com/dbeaver/dbeaver/issues/22430)
We use a Cloudera JDBC for Hive, and I had the same problem, but I was able to copy paste the setup:
![image](https://github.com/dbeaver/dbeaver/assets/24705801/3f925c65-c980-44b6-8736-3ffaddcfded0)
And the driver was usable (but run into the second problem). If relevant, "Edit connection" > "Driver settings" > "Libraries" > "Find Class" was working.

Second problem with this driver was:
[unable to find valid certification path to requested target in Ubuntu #22454](https://github.com/dbeaver/dbeaver/issues/22454)
In my case, Windows Server 2022:
!ENTRY org.jkiss.dbeaver.model 4 0 2024-01-11 00:55:01.848
!MESSAGE unable to find valid certification path to requested target
!STACK 0
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

The second part of the error message (Details) was very clear (in my case):
![image](https://github.com/dbeaver/dbeaver/assets/24705801/36dcc9b8-9ab9-4b10-8d53-3d9f29fae034)
[Cloudera][HiveJDBCDriver](500164) Error initialized or created transport for authentication: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
  javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      unable to find valid certification path to requested target
      unable to find valid certification path to requested target

Not sure if it is DBeaver not handling cacerts, the fix was to change the URL Template, and add Java default Trust Store to handle the certificate CA roots:
jdbc:hive2://{host}:{port}/{database};AuthMech=3;SSL=1;SSLTrustStore=/path/cacerts

I just copied the default Java 8 cacerts to a new path (I left it next to the krb5.conf) and problem solved. Cloudera Hive Connection with SSL success.
If anyone follows this note, consider the default Java cacerts should not be used as a trust store if it is to keep private info, in this cenario a new trust store should be created, password protected, etc (sslTrustStore=/path/truststore;trustStorePassword=pass). I suppose who needs knows.

**Comment by aitor94** [comment]
In my case happen with Oracle drivers. I got PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target error when I click in test connection and it tries to Download drivers. It doesn`t allow to change URL template.

**Comment by serjiokov** [comment]
Hi, @hugocelso
Thanks for your report.
The multi user scenarios is always complex where product configuration shared between users. In your particular case seems configuration created by the first user is not accessible by others. In order to avoid issues with administrative policy restrictions I would recommend to install product in public folder where all users have access rights (or setup policy after installation). The next point is installation additional plugins, more than one user can't install software to Dbeaver simultaneously in order to avoid any bundle conflicts on the runtime.
Would be great to know more about your multi user case of using product and let me please know is your issue resolved ?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
