### ISSUE TITLE
Red underlining of column names in sql editor

### ISSUE THREAD

**Issue by perrani** [dbeaver/dbeaver#22439]
### Description

Table names are recognized correctly regardless of whether they are written in uppercase or lowercase. However, it appears that the column names are case sensitive.

### DBeaver Version

23.3.2.202401072024

### Operating System

Windows 10

### Steps to reproduce

simply write a query

![image](https://github.com/dbeaver/dbeaver/assets/78496779/71819495-b814-401c-a124-3a1ac6735001)

**Comment by E1izabeth** [comment]
Thank you for bug report. It's a duplicate of #22385
