### ISSUE TITLE
Error when installing DBeaver plugin in eclipse.

### ISSUE THREAD

**Issue by BrandonBlackwell** [dbeaver/dbeaver#22436]
### Description

When installing DBeaver plugin via "Install New Software" in eclipse I receive this error: 

 Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver IDE 23.3.3.202401110022 (org.jkiss.dbeaver.ide.feature.feature.group 23.3.3.202401110022)
  Missing requirement: DBeaver PostgreSQL UI 1.0.99.202401110022 (org.jkiss.dbeaver.ext.postgresql.ui 1.0.99.202401110022) requires 'osgi.bundle; org.eclipse.gef 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver Databases UI 1.0.114.202401110022 (org.jkiss.dbeaver.db.ui.feature.feature.group 1.0.114.202401110022)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ext.postgresql.ui [1.0.99.202401110022,1.0.99.202401110022]
  Cannot satisfy dependency:
    From: DBeaver IDE 23.3.3.202401110022 (org.jkiss.dbeaver.ide.feature.feature.group 23.3.3.202401110022)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.db.ui.feature.feature.group [1.0.114.202401110022,1.0.114.202401110022]

### DBeaver Version

Community Edition 23.3.202401110022

### Operating System
Both 
Linux Redhat
Windows 10

### Steps to reproduce

Clean install of Eclipse 2023-09 and after that installation of dBeaver into it.
1. Downloaded the jar files from this update site: https://dbeaver.io/files/ea/update/ce/ into a local folder.
2. In Eclipse, Install New Software > Add > Archive > folder > content.jar

### Additional context

I have to download all the necessary jars/files and install them in an offline environment in eclipse.

**Comment by Destrolaric** [comment]
Hi, DBeaver requires GEF plugin to be installed, it can be installed using following p2 repository
https://download.eclipse.org/tools/gef/classic/release/3.18.0

**Comment by BrandonBlackwell** [comment]
Thanks, when I install GEF it gives me this:

`Cannot complete the install because one or more required items could not be found.
  Software being installed: GEF Classic Zest Examples 3.15.200.202311222042 (org.eclipse.zest.examples 3.15.200.202311222042)
  Missing requirement: GEF Classic Zest Examples 3.15.200.202311222042 (org.eclipse.zest.examples 3.15.200.202311222042) requires 'osgi.bundle; org.eclipse.pde 0.0.0' but it could not be found`

**Comment by Destrolaric** [comment]
@BrandonBlackwell Zest examples can be excluded.

**Comment by BrandonBlackwell** [comment]
I exclude Zest examples and it gives me this:
`An error occurred while collecting items to be installed
session context was:(profile=_home_entds.ngisn.com_4n36571_eclipse_java-2023-09_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.draw2d_3.14.100.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.draw2d_3.14.100.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/features/org.eclipse.draw2d_3.18.0.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/features/org.eclipse.draw2d_3.18.0.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.draw2d.source_3.14.100.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.draw2d.source_3.14.100.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/features/org.eclipse.draw2d.source_3.18.0.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/features/org.eclipse.draw2d.source_3.18.0.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef_3.16.0.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef_3.16.0.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.doc.isv_3.13.300.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.doc.isv_3.13.300.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/features/org.eclipse.gef.examples_3.18.0.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/features/org.eclipse.gef.examples_3.18.0.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.flow_3.15.100.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.flow_3.15.100.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.flow.source_3.15.100.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.flow.source_3.15.100.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.logic_3.14.200.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.logic_3.14.200.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.logic.source_3.14.200.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.logic.source_3.14.200.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.shapes_3.14.100.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.shapes_3.14.100.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.shapes.source_3.14.100.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.shapes.source_3.14.100.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/features/org.eclipse.gef.examples.source_3.18.0.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/features/org.eclipse.gef.examples.source_3.18.0.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.text_3.14.100.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.text_3.14.100.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.text.source_3.14.100.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.examples.text.source_3.14.100.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/features/org.eclipse.gef_3.18.0.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/features/org.eclipse.gef_3.18.0.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/features/org.eclipse.gef.sdk_3.18.0.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/features/org.eclipse.gef.sdk_3.18.0.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.source_3.16.0.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/plugins/org.eclipse.gef.source_3.16.0.202311222042.jar
Artifact not found: jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/features/org.eclipse.gef.source_3.18.0.202311222042.jar.
jar:file:/home/entds.ngisn.com/4n36571/Downloads/GEF-Updates-3.18.0.zip!/features/org.eclipse.gef.source_3.18.0.202311222042.jar`

**Comment by BrandonBlackwell** [comment]
I excluded Zest Examples and Draw2D Features. Now I'm recieving this:

`An error occurred while collecting items to be installed
session context was:(profile=_home_..._eclipse_java-2023-09_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No artifact repository available.
noArtifactRepositoriesAvailable`

**Comment by BrandonBlackwell** [comment]
Any update on this?

**Comment by BrandonBlackwell** [comment]
UPDATE:
I was able to install via dropins folder. The jars from Dbeaver and Eclipse GEF features folder need to be in the same folder as well as plugin jars, from both, in plugins folder.
