### ISSUE TITLE
Improve switching between export settings with keyboard

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#22440]
Now switching between export settings is possible with Tab button, or pressing Esc to deactivate the setting field then arrows on the keyboard. In the second way it is inconvinient to switching fast between settings because of automatic field activation after pressing arrows 

https://github.com/dbeaver/dbeaver/assets/43252954/dc5c62c2-abb7-4019-90db-4bb6653a9bdc

**Comment by arhayka** [comment]
you can switch fields by tab. we think that this is enough
