### ISSUE TITLE
CSV import ignores escape characters in unquoted values

### ISSUE THREAD

**Issue by HauserV** [dbeaver/dbeaver#22455]
### Description

The CSV import ignores escape characters in unquoted values (as in `foo \ bar`). This is incompatible with the CSV export (see https://github.com/dbeaver/dbeaver/issues/20644) as well as CSV exports produced by some database engines (e.g., PostgreSQL).

### DBeaver Version

Community Edition 23.1.3.202307231901

### Operating System

Windows 11 Pro, Version 22H2 (OS Build 22621.2861)

### Database and driver

1. Database name and version: PostgreSQL 14.9 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit
2. Driver name and version: PostgreSQL standard driver, org.postgresql:postgresql:RELEASE [42.5.2]

### Steps to reproduce

1. Create a sample PostgreSQL table.
   ```
   CREATE TABLE public.test (a varchar NULL);
   INSERT INTO public.test (a) VALUES ('foo \ bar');
   ``` 

2. (Option A) Create a sample CSV file by exporting a cell using PostgreSQL's COPY.
   ```
   CREATE TABLE public.test (a varchar NULL);
   INSERT INTO public.test (a) VALUES ('foo \ bar');
   COPY public.test TO 'file.csv' CSV HEADER ESCAPE '\';
   ``` 
   The `file.csv` looks like so. Note that the value is unquoted because it contains neither the quote nor the delimiter characters.
    ```
    a
    foo \ bar
    ```
   (Option B) Export the table into CSV using DBeaver's CSV export (characters escape set to escape; otherwise default settings).
    ```
    "a"
    foo \ bar
    ```
3. Import the CSV into the table using DBeaver's CSV import (truncate; otherwise default settings).
4. Inspect the contents of the table
    ```
    postgres=> COPY public.test TO STDOUT CSV HEADER ESCAPE '\';
    a
    foo  bar
   ```
   The escape character `\` is missing.

### Additional context

The same behavior is present in more recent versions of OpenCSV as well.

**Comment by Matvey16** [comment]
@HauserV I don't quite understand this issue. Can you please specify what the expected behaviour is for this case?
From my perspective the fact that you are importing a string 'a \ b' and get a result of 'a  b' in the database is expected because we have a setting in the import to specify what is considered an escape char when csa content is being processed.
![image](https://github.com/dbeaver/dbeaver/assets/82543000/e9d3ab4d-7379-45fb-ad1a-baf30a96a869)

This synbol now is considere an esacape char for the purpose of scv processing so it won't be inserted into database itself. But if you change it to another sybol in the settings, the backslash will be actually imported to the database as an actual part of the string.

Maybe I misunderstood you, so I want to know how do you see the expected result of such import

**Comment by HauserV** [comment]
@Matvey16, ultimately, I'm looking for a way to consistently export and import CSVs using DBeaver. Currently, the exporter produces CSV that the importer can't import as demonstrated above.

In particular, my expectation is that the parser would behave just as [PostgreSQL](https://www.postgresql.org/docs/current/sql-copy.html#id-1.9.3.55.9.3) does. 

> If the value contains the delimiter character, the QUOTE character, the NULL string, a carriage return, or line feed character, then the whole value is prefixed and suffixed by the QUOTE character, and any occurrence within the value of a QUOTE character or the ESCAPE character is preceded by the escape character.

<details><summary>Example</summary>
<p>

| Input       | Parsed  |
| ---------- | -------- |
| `a \ b`      | `a \ b`    |
| `a \\ b`     | `a \\ b`  |
| `"a \ b"`   | `a \ b`    |
| `"a \\ b"`  | `a \ b`   |
| `"a \" b"`  | `a " b`   |

```
postgres=> CREATE TABLE public.test (a varchar);
CREATE TABLE
postgres=> COPY public.test FROM STDIN WITH CSV ESCAPE '\';
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
>> a \ b
>> a \\ b
>> "a \ b"
>> "a \\ b"
>> "a \" b"
>> \.
COPY 5
postgres=> SELECT * FROM public.test;
   a
--------
 a \ b
 a \\ b
 a \ b
 a \ b
 a " b
(5 rows)
```

</p>
</details> 

The alternative would be to escape both the quote and the escape characters during export but as @E1izabeth pointed out in https://github.com/dbeaver/dbeaver/issues/20644, that would likely cause more harm than good.

**Comment by ShadelessFox** [comment]
DBeaver will escape whatever symbol comes after the escape character, even if it's a space. This might be considered as a bug.

Regarding the provided escaping rules, I think rules should be independent of whether a string is quoted or not.

**Comment by Matvey16** [comment]
That is definately not a bug, but we need to consider if we want to change how escape char is proceeded in import. We will use #22483 for that

**Comment by HauserV** [comment]
@Matvey16, thanks for considering the other issue
I'm fine as long there's a way! :) 

Additional idea: would it be possible to somehow warn users in the CSV export UI that the files produced with characters escape set to escape cannot be safely imported back? In the quote mode it's fairly obvious because the import configuration throws an exception but this one is quite subtle.
