### ISSUE TITLE
Using shortcut, to select all results, replaces everything with "a"

### ISSUE THREAD

**Issue by vezixig** [dbeaver/dbeaver#22466]
### Description

When working with a large result set (120k+) and using the shortcut Control+a to select all, every cell gets an a written into.

### DBeaver Version

Cumminity Edition 23.3.2

### Operating System

macOS Sonoma 14.2.1

### Steps to reproduce

1. Create a large enough result set
2. Press control+a to select all

**Comment by serjiokov** [comment]
Hi @vezixig, could you provide footage for the issue, please?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
