### ISSUE TITLE
Schema permissions are not shown for PostgreSQL roles

### ISSUE THREAD

**Issue by yoni-yad2** [dbeaver/dbeaver#22471]
### Description

Role has USAGE & CREATE permissions on "temp" schema as can be seen using this query:
```
SELECT 
       r.rolname AS role_name,
	   n.nspname AS schema_name,
       p.perm AS privilege
FROM pg_catalog.pg_namespace AS n
CROSS JOIN pg_catalog.pg_roles AS r
CROSS JOIN (VALUES ('USAGE'), ('CREATE')) AS p(perm)
WHERE has_schema_privilege(r.oid, n.oid, p.perm)
order by 1,2,3
```

But in the Role Permissions screen it is not shown as checked:

![image](https://github.com/dbeaver/dbeaver/assets/103036539/cc3e0f62-1468-42a6-8755-97841b104e8f)

And they do not show up in "Source" neither:

![image](https://github.com/dbeaver/dbeaver/assets/103036539/e2a0678a-9df2-4070-88b6-60319d69aa0a)

### DBeaver Version

Community Edition v23.3.2.202401072024

### Operating System

Windows 10 64 bit

### Database and driver

PostgreSQL v15.5

### Steps to reproduce

1. Run:
```
CREATE SCHEMA temp;
CREATE ROLE myrole PASSWORD 'Abcdefgh1';
GRANT ALL ON SCHEMA temp TO myrole;
```
2. Refresh DB Navigator "Roles" node.
3. Open myrole "Permissions" tab.
4. Open myrole "Source" tab.

**Comment by LonwoLonwo** [comment]
Hello @yoni-yad2 

I can't reproduce your issue. 

![2024-01-16 16_52_30-DBeaver Ultimate 23 3 3 - myrole](https://github.com/dbeaver/dbeaver/assets/45152336/ba5f9fe8-ebc8-4cf6-8249-ae963d2a01b8)

![2024-01-16 16_52_47-DBeaver Ultimate 23 3 3 - myrole](https://github.com/dbeaver/dbeaver/assets/45152336/4ea931ec-6379-42ff-8400-0ef2ba265e1e)

Did you refresh your role after creation? 
Also, you can check the metadata queries in [the Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) (do not forget to enable filters).

**Comment by yoni-yad2** [comment]
I would like to add that I'm experiencing it on an RDS PostgreSQL instance.

**Comment by LonwoLonwo** [comment]
Could you please provide a result of the "Test connection" button in your connection settings?

**Comment by yoni-yad2** [comment]
Connected (2509 ms)

Server: PostgreSQL 15.5
            PostgreSQL 15.5 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-6), 64-bit
Driver: PostgreSQL JDBC Driver 42.5.0

**Comment by yoni-yad2** [comment]
I can see the permissions through the Schema Properties/Permissions tab but not through Role Properties/Permissions tab.

**Comment by LonwoLonwo** [comment]
For now, I can't reproduce, and I do not have ideas.

Could you please check the metadata queries in [the Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) (do not forget to enable filters)?

**Comment by yoni-yad2** [comment]
In Query Manager I was able to find the failed query:

```
SELECT * FROM (
	SELECT DISTINCT relnamespace,
	relacl,
	relname,
	relkind,
(aclexplode(relacl)).grantee as granteeI
FROM
	pg_class
WHERE
	relacl IS NOT NULL
	AND relnamespace IN (
SELECT oid
FROM pg_namespace
WHERE nspname NOT LIKE 'pg_%' AND nspname != 'information_schema')
UNION ALL
SELECT DISTINCT
	n.oid AS relnamespace,
	nspacl AS relacl,
	n.nspname AS relname,
	'C' AS relkind,
(aclexplode(nspacl)).grantee as granteeI
FROM
	pg_catalog.pg_namespace n
WHERE
	n.nspacl IS NOT NULL 
	) AS tr
WHERE tr.granteeI=1467441 AND tr.relkind IN('S', 'm', 'C')
```

Error:
`ERROR: UNION types "char" and text cannot be matched`

Workaround:

Replacing the "relkind" constant expression in the second SELECT below UNION ALL:
`cast('C' as "char") AS relkind,`

**Comment by LonwoLonwo** [comment]
Yes, I see now — the PostgreSQL version matters.
Thanks for the report.
