### ISSUE TITLE
JNA loader constraint violation with MariaDB & waffle-jna

### ISSUE THREAD

**Issue by rusher** [dbeaver/dbeaver#22479]
### Description

when loading latest mariadb connector version (3.3.2), connection throw an error 
```
Unexpected driver error occurred while connecting to the database
  loader constraint violation: loader org.jkiss.dbeaver.registry.driver.DriverClassLoader @76f31bcb wants to load class com.sun.jna.Pointer. A different class with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @4cf5d999. (com.sun.jna.Pointer is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @4cf5d999, parent loader 'platform')

```
This is a problem, because since a few version, mariadb 3.3.2 has a waffle-jna dependency. So this always occurs for all connections, even if GSS authentication is not used. 

Waffle-jna dependency and seems incompatible with dbeaver (reading from #8247), i've tryed to checking "ignore transcient dependencies" that permit connection when not using GSS authentication. 
When needing GSS authentication, adding waffle artificts manually without JNA, that results in error" com/sun/jna/ptr/IntByReference", probably because JNA version doesn't match.

### DBeaver Version

23.3.2.202401072024

### Operating System

windows 11

### Database and driver

mariadb database 10.11 and java connector 3.3.2

### Additional context

This is similar to #8247 and #15289

**Comment by LonwoLonwo** [comment]
Hello @rusher 

Did you do [these steps](https://github.com/dbeaver/dbeaver/issues/8247#issuecomment-624109518)?

> You will need to add both waffle and caffeine artifacts separately.
> Another workaround: download them and add them as jar files.

**Comment by rusher** [comment]
yes, i've been adding all the jars separatly adding : 
```
org.mariadb.jdbc:mariadb-java-client:3.3.2
com.github.waffle:waffle-jna:3.3.0
org.slf4j:jcl-over-slf4j:2.0.7
org.slf4j:slf4j-api:2.0.7
com.github.ben-manes.caffeine:caffeine:2.9.3
org.checkerframework:checker-qual:3.32.0
com.google.errorprone:error_prone_annotations:2.10.0
net.java.dev.jna:jna-platform:5.13.0
```
jars and downloading them

see 
![artifacts](https://github.com/dbeaver/dbeaver/assets/618074/b9893a44-f529-4216-8eba-c28a28dfaa1e)

but that's still result (when using GSSAPI, normal authentication connection work then ok) in:

![connection](https://github.com/dbeaver/dbeaver/assets/618074/94e8c2ed-ee16-413a-b22c-012df7da3483)
probably because JNA jar version is not compatible with net.java.dev.jna:jna-platform:5.13.0.

**Comment by LonwoLonwo** [comment]
Thanks for the answer. We will look at it.

**Comment by serge-rider** [comment]
The problem cause by JNA dependency in MySQL driver extension.
We could try to fix it by moving all JNA interaction to another plugin so classes won't conflict.

**Comment by rusher** [comment]
correction confirmed thanks !
