### ISSUE TITLE
MS SQL Syntax highlight for CTEs not working

### ISSUE THREAD

**Issue by DevinSmithWork** [dbeaver/dbeaver#22478]
### Description

I love the new syntax highlighting, but it doesn't seem to parse CTEs correctly in MS SQL: 
![Screen Shot 2024-01-16 at 12 02 23 PM](https://github.com/dbeaver/dbeaver/assets/25261603/710c358f-4ee7-4204-80ef-39500c436655)

Problems:
1. Items within the CTE are not colored correctly
2. In the main query which reference the CTE are (excepting the CTE's table alias) colored as errors

### DBeaver Version

Community Edition 23.3.2.202401072024

### Operating System

macOS Monterey 12.7.1

### Database and driver

Microsoft JDBC Driver for SQL Server

### Steps to reproduce

1. Connect to a MS SQL db
2. Construct a query using a CTE.

**Comment by E1izabeth** [comment]
Thank you for bug report. It's a known issue and we're going to implement it soon.
