### ISSUE TITLE
Blank line as statement delimiter ambiguity 

### ISSUE THREAD

**Issue by Speedkore** [dbeaver/dbeaver#22489]
**Is your feature request related to a problem? Please describe.**
I saw the other day a blog post of a guy who broke his database because on how dbveaber delimits queries when pressing ctrl + enter
[https://zaidesanton.substack.com/p/how-i-destroyed-the-companys-db](https://zaidesanton.substack.com/p/how-i-destroyed-the-companys-db)

He had a code like this:
**UPDATE orders**
**SET is_deleted = true**

**WHERE id in (1,23)**

And he pressed ctrl + enter on the first line, so the "where" clause was not taken into account, the result was updating the whole table.

**Describe the solution you'd like**
When we hit ctrl + enter, blank lines should not be a delimiter to see where the query ends, I think that it should be ";" that is the standard of the sql syntax.

**Describe alternatives you've considered**
If we still want to use blank line as delimiter, the UI should ask to resolve the ambiguity if it detects that you are about to run more than one query or make a preview of what is about to be executed when it is not clear.

**Additional context**
These are the comments on reddit about this guy, it is interesting to read: [https://old.reddit.com/r/programming/comments/18vdmq5/how_i_destroyed_the_companys_db_stupid_sql_mistake/](https://old.reddit.com/r/programming/comments/18vdmq5/how_i_destroyed_the_companys_db_stupid_sql_mistake/)

**Comment by francescortiz** [comment]
I see in the reddit thread that people suggests that checking the row count is enough. I don't aggree with this because the omitted `WHERE` conditions could keep the number of affected rows intact, but it could be a completely different set of rows that got modified.

**Comment by LonwoLonwo** [comment]
Important note - it is not so simple to execute such queries in DBeaver:

![2024-01-18 10_49_53-DBeaver Ultimate 23 3 3 - _postgres 6 1_ Script-122](https://github.com/dbeaver/dbeaver/assets/45152336/a33030e4-20ce-4417-9fd9-265eefbcaf9b)

**Comment by Speedkore** [comment]
> Important note - it is not so simple to execute such queries in DBeaver:
> 
Yeah true, that is nice if you have it enabled, anyway something similar to this would cause the same issue:
**UPDATE orders**
**SET is_deleted = true**
**WHERE true**

**AND id in (1,23);**

**Comment by LonwoLonwo** [comment]
Just to be precise. Here is the way how to turn off this behavior with the setting disabling:

![2024-01-18 18_48_18-Preferences](https://github.com/dbeaver/dbeaver/assets/45152336/456654bd-f866-4f05-8df1-5b60933d1766)

**Comment by Speedkore** [comment]
Oh! I wouldn't have thought that there was a setting for this, I'm disabling it for my personal safety. In my opinion, this should be disabled by default but this is another story, thank you!!!

**Comment by arhayka** [comment]
Thank you for the idea.
You can vote for the issue with 👍 under the issue description to promote it to a higher priority.

We want to add smart query recognition (make the parser understand that after the blank string, the new query begins).
Add combobox for this setting:
- Always
- Never
- Smart detection (default)

Related ticket: https://github.com/dbeaver/dbeaver/issues/23115

**Comment by alex-solovyev** [comment]
There is a regression there. Now multiple queries treated as one, particularly `SELECT` + `START TRANSACTION`, e.g.

24.0.2:
<img width="520" alt="Screenshot 2024-04-30 at 08 26 23" src="https://github.com/dbeaver/dbeaver/assets/1556417/033ce6bf-8101-4006-b197-76cb57386f3c">

24.0.3:
<img width="567" alt="Screenshot 2024-04-30 at 08 29 09" src="https://github.com/dbeaver/dbeaver/assets/1556417/bd47a17a-9990-4a92-921c-8a5c562cde65">

**Comment by E1izabeth** [comment]
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.
