### ISSUE TITLE
Manage syntaxic coloration for comments starting with double-slashes

### ISSUE THREAD

**Issue by Thomas-LEILLET-Sanofi** [dbeaver/dbeaver#22490]
In snowflake, in-line comment in your SQL code is usually starting with double dash ( -- ), but it can also support in-line comment starting with double-slash ( // ) 
Example : 

![image](https://github.com/dbeaver/dbeaver/assets/130557869/a4239190-5588-4409-858f-34a27a9384a0)

In DBeaver, only double dash is taken into consideration, and not double-slash...
![image](https://github.com/dbeaver/dbeaver/assets/130557869/ab0d5f7f-4b5c-4bab-bf41-5641236d4f5c)

Is there a way to activate the syntaxic coloration in the latter case ? If not, please take it as a feature request
Thanks

**Comment by E1izabeth** [comment]
Thank you for creating the issue. We will improve it.

**Comment by Thomas-LEILLET-Sanofi** [comment]
Leillet, Thomas /FR/EXT reacted to your message: [like]

**Comment by Thomas-LEILLET-Sanofi** [comment]
[like]  Leillet, Thomas /FR/EXT reacted to your message:
________________________________
