### ISSUE TITLE
Export Command, the processor configuration is missing the "target table name."

### ISSUE THREAD

**Issue by guofugaowan** [dbeaver/dbeaver#22494]
### Description

When exporting data using command-line, if the target type is set to SQL, the processor configuration is missing the "target table name."

### DBeaver Version

23.3.2

**Comment by guofugaowan** [comment]
![picture](https://github.com/dbeaver/dbeaver/assets/35140361/12f5d76b-c0b5-4146-a397-79ab994c1de4)

**Comment by uslss** [comment]
@guofugaowan 
could you please provide steps to reproduce the issue?

**Comment by guofugaowan** [comment]
> @guofugaowan could you please provide steps to reproduce the issue?

The export interface has this configuration, but the export command does not.
https://dbeaver.com/docs/dbeaver/Export-Command/#sql

**Comment by Destrolaric** [comment]
@guofugaowan Hi, you can use `userTableName` property to specify target table

**Comment by ShadelessFox** [comment]
Thanks for the report. We're going to update the documentation shortly.

**Comment by guofugaowan** [comment]
> @guofugaowan Hi, you can use `userTableName` property to specify target table

Thank you, that's right

**Comment by guofugaowan** [comment]
> Thanks for the report. We're going to update the documentation shortly.

You're welcome, thank you for your hard work

**Comment by E1izabeth** [comment]
Documentation was updated
