### ISSUE TITLE
DBeaver crashes

### ISSUE THREAD

**Issue by Faiber-Juanias** [dbeaver/dbeaver#22508]
### Description

DBeaver starts correctly, however, when I find myself inside the SQL editor and try to comment on a line, when I press the dash key, it automatically crashes and does not return to its normal state. The only way is to terminate the process from the Windows process manager. Occurs when the hyphen is prefixed before the SQL word "and" within a table query.

### DBeaver Version

DBeaver Enterprise	23.3.0.202312201943

### Operating System

Windows 10 Pro

### Database and driver

Database name: MySQL 8.0.31
Driver name: com.mysql.cj.jdbc.Driver

### Steps to reproduce

1. I write a SQL query to a table with criteria in "where".
2. The query has criteria with "and".
3. I comment the line with "and".
4. Inserting "-" right before, for example "-and", automatically locks Dbeaver.
5. The only way is to finish the task from the Windows 10 task manager.
6. If I restart Dbeaver and comment on the line again, it comes back and crashes.

**Comment by E1izabeth** [comment]
Please try our latest version. We hope the issue has been already fixed. You can download DBeaver 23.3.3 here https://dbeaver.io/files/ea/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by BlueskyFR** [comment]
@E1izabeth hey, it happens again on 24.0.5

**Comment by E1izabeth** [comment]
@BlueskyFR Please create a new issue and provide steps to reproduce.
