### ISSUE TITLE
ORA-00942 Oracle Cloud

### ISSUE THREAD

**Issue by tuzinar3** [dbeaver/dbeaver#22514]
### Description

select on oracle server 19c with mulitiple schemas not working, on plsql is ok.

![image](https://github.com/dbeaver/dbeaver/assets/31776567/6fa4a76a-4895-40ce-87ba-7ffcbad768ca)

### DBeaver Version

Community 23.3.2

### Operating System

Windows 10 22H2

### Database and driver

Oracle JDBC driver

**Comment by LonwoLonwo** [comment]
Hello @tuzinar3 

Are sure, what you choose correct schema (user) for the selection? 

![2024-01-19 20_13_46-ORA-00942 Oracle Cloud · Issue #22514 · dbeaver_dbeaver](https://github.com/dbeaver/dbeaver/assets/45152336/3d684c0a-0102-459e-a58d-a39498b91007)

**Comment by tuzinar3** [comment]
> Hello @tuzinar3
> 
> Are sure, what you choose correct schema (user) for the selection?
> 
> ![2024-01-19 20_13_46-ORA-00942 Oracle Cloud · Issue #22514 · dbeaver_dbeaver](https://private-user-images.githubusercontent.com/45152336/298145472-3d684c0a-0102-459e-a58d-a39498b91007.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MjIwMTEsIm5iZiI6MTcwNTkyMTcxMSwicGF0aCI6Ii80NTE1MjMzNi8yOTgxNDU0NzItM2Q2ODRjMGEtMDEwMi00NTllLWE1OGQtYTM5NDk4YjkxMDA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDExMDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0Njk4ZDU0MTNhNTcyZWZkYTRjMzc3MTY2ZGZmYzU2MGUyZTUxM2U4ZTViY2VlNTU5ODdiMzkyNzY0OTU0NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XEUkIaSKOOd07mw5npIPMGfnpKTDrzbNrSDrNopNj94)

Yes, same schema/server.


The problem only occurs when connected to a base that is in the cloud (19c), if the Oracle is local, the problem does not appear.

**Comment by LonwoLonwo** [comment]
Does it work with the whole table/view + user name?

**Comment by tuzinar3** [comment]
select * from SCHEMA.TABLE_NAME?

**Comment by LonwoLonwo** [comment]
Yes, correct

**Comment by tuzinar3** [comment]
Not

![image](https://github.com/dbeaver/dbeaver/assets/31776567/095cd66b-4965-45a5-a0fa-f635ccfe5b1a)

**Comment by LonwoLonwo** [comment]
Ok. But can you create a table in your remote schema from this SQL Editor? 
If not - then you do not have enough [grants](https://docs.oracle.com/en/error-help/db/ora-00942/) for this user, probably,

**Comment by tuzinar3** [comment]
Create a table in Schema that is connected to dbeaver (in yellow?).

![image](https://github.com/dbeaver/dbeaver/assets/31776567/a06ba81b-19d3-4e21-85a1-ef05c4332f52)


Yes, it is possible to create a table.

**Comment by LonwoLonwo** [comment]
So, this issue only for non-default for SQL Editor schemas? Because I see, that select works correctly for BETIOLO (default) schema.
Could you create a table from your current SQL Editor for your PIR*** schema? 
Could you see PIR*** schema in your navigator tree?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
