### ISSUE TITLE
Bookmarks should be language-independent

### ISSUE THREAD

**Issue by hhmmjjnn** [dbeaver/dbeaver#22517]
### Description

Opening and creating DBeaver bookmark files (`*.bm`) should not depend on the language settings of the GUI.

As of version 23.3.2, released in January 2024, DBeaver writes localized bookmarks.

So a Brazilian Portuguese instance (`"%ProgramFiles%\dbeaver\dbeaver.exe" -nl pt_BR`) emits...

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bookmark title="FOO" description="Tabela FOO" data-source="(...)">
    <path>Esquemas</path>
    <path>BAR</path>
    <path>Tabelas</path>
    <path>FOO</path>
    <image>(...)</image>
</bookmark>
```

...while an English instance (`"%ProgramFiles%\dbeaver\dbeaver.exe" -nl en`) emits...

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bookmark title="FOO" description="Table FOO" data-source="(...)">
    <path>Schemas</path>
    <path>BAR</path>
    <path>Tables</path>
    <path>FOO</path>
    <image>(...)</image>
</bookmark>
```

If you try to open a bookmark that was created with a mismatching GUI setting, you get this error message:

```xml
Cannot open bookmark

Reason:
Can't find node 'Esquemas' in 'BAZ'
```

This bug makes sharing project folders with your colleagues a nightmare.

Please, let DBeaver always read and write bookmarks in English, no matter what.

Thanks!

### DBeaver Version

Community Edition 23.3.0.202312031432

### Operating System

Windows 11 (21H2/10.0.22000.2652)

### Database and driver

oracle.jdbc.OracleDriver

### Steps to reproduce

_See above_

**Comment by hrimthrusa** [comment]
Thank you for your report.
