### ISSUE TITLE
Friendly competitor invitation

### ISSUE THREAD

**Issue by WebDB-App** [dbeaver/dbeaver#22520]
Hello Guys,

First, thanks you for everything you did to the open source community
I just want to invite people to take a look at a new competitor, if possible give feedbacks and even to participate -> webdb.app

Have a great day and happy new year =)
I sincerly hope you doesn't consider this as a awkward move, I just want to help open source community

**Comment by E1izabeth** [comment]
Hello. We wish success to your product =)
