### ISSUE TITLE
When selecting fields for export, field list disappears

### ISSUE THREAD

**Issue by GTGeek88** [dbeaver/dbeaver#22521]
### Description

I needed to export some data to CSV. I only needed two columns of a result set already selected. So, within the Export dialog I used the feature to choose the fields. I hoped to find a Deselect All that I could use, then I'd select the two columns I needed. While checking for that feature, I used right-click to no avail, then I double-clicked on a row (a row represents a column in this case, of course). The form "blanked" - meaning all the controls, except the Ok and Cancel buttons, disappeared. I could not get it to redisplay the controls (I'm assuming clicking Cancel and starting over would, of course). Screen shot:

![image](https://github.com/dbeaver/dbeaver/assets/8461024/486f0f1f-17fd-4c45-81d0-d79b00f50741)

### DBeaver Version

23.3.2.202401072024

### Operating System

Windows 11

### Database and driver

SQL Server 2019
Microsoft JDBC Driver for SQL Server

### Steps to reproduce

I was just right-clicking and double-clicking and the control disappeared. I have tried to recreate it, but can't. Sorry.

**Comment by LonwoLonwo** [comment]
Hello @GTGeek88 
Could you please check [the latest DBeaver version](https://dbeaver.io/download/)? Does the issue still exist?

**Comment by GTGeek88** [comment]
The problem is that I couldn't recreate it later. I know I was double-clicking and right-clicking to see if there was some kind of menu I could find that would let me Select/Deselect All and it happened. Tried to recreate it later and couldn't. I'll try again, though. And the version I was using was up-to-date at the time, so what are the chances this was addressed in the very next release?

**Comment by LonwoLonwo** [comment]
> And the version I was using was up-to-date at the time, so what are the chances this was addressed in the very next release?

We changed some things in this dialog in the last release. It means that all previous bugs are outdated. So, please, check the latest version.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
