### ISSUE TITLE
Not able to download driver on DBeaver

### ISSUE THREAD

**Issue by bashartulkarim** [dbeaver/dbeaver#22539]
### Description

While getting the driver from the server getting the below error.

Network error

Reason:
Network unavailable
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### DBeaver Version

Community Edition Version 23.3.2.2024010720

### Operating System

MacOS 14.2.1

### Database and driver

DB2, Oracle, MS-SQL and MySQL

**Comment by g33kd4ddy** [comment]
We have same issue with windows.

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
