### ISSUE TITLE
Table/Column editor very slow in Fedora Linux

### ISSUE THREAD

**Issue by akshayjain7983** [dbeaver/dbeaver#22530]
### Description

I upgraded from 23.0.1 to 23.3.3 today. Now when I try to add column in table editor it shows a popup dialog instead of inline editing. And the popup dialog takes around 5-7 seconds to pop. Now if I have to add 50 columns then its like way too much time. I don't mind popup dialog either but it cannot take 5-7 secs to pop. Also if there is any way I can revert back to inline column editing UI then tell me please. 

### DBeaver Version

Community Edition 23.3.3

### Operating System

Fedora Linux 39

### Database and driver

PostgreSQL 16.1
PostgreSQL JDBC Driver 45.5.2

### Steps to reproduce

1. Open **_Database Navigator_**
2. Select and connect to some database (assuming there is already an existing connection)
3. Expand **_Databases_**
4. Select and expand some particular database 
5. Expand **_Schemas_** under selected database
6. Select and expand some particular schema
7. Right click on **_Tables_** and click on **_Create New Table_**. This will open a table editor
8. Select **_Columns_** tab from left 
9. Right click on white space in **_Columns_** tab and then click on **_Create New Column_** in the popup menu
10. Now the UI will hang for 5-7 secs before showing the popup dialog for creating new column.

**Comment by Destrolaric** [comment]
Hi, please provide additional information about your Linux environment? Which graphic environment is used, and please provide the result of: 
```
echo "$XDG_SESSION_TYPE"
```

**Comment by akshayjain7983** [comment]
```
akshay.jain@Akshay:~$ echo "$XDG_SESSION_TYPE"

wayland
```

**Comment by Destrolaric** [comment]
@akshayjain7983 Could you also try the early access version https://dbeaver.io/files/ea/, it may have your issue fixed.

**Comment by akshayjain7983** [comment]
@Destrolaric , I tried with ea (version in the ea was also same 23.3.3 so not sure what's different in this) but problem remains same.

**Comment by Destrolaric** [comment]
@akshayjain7983 Did you download an EA version today or yesterday? If today it may not contain the necessary fix.

**Comment by akshayjain7983** [comment]
Today.

**Comment by Destrolaric** [comment]
@akshayjain7983 we published EA once again, can you try again, please? It will be active till the evening.

**Comment by akshayjain7983** [comment]
I am in India and can check only during India morning hours. Would it be
available during India morning
time?

**Comment by serge-rider** [comment]
You can test it in tomorrows EA (potential fix was applied)

**Comment by serge-rider** [comment]
@akshayjain7983 did you have a chance to test EA?

**Comment by akshayjain7983** [comment]
Sorry for the late reply.

I tested and it looks better. The delay is only about 1-2 secs now. Usable.

But I would suggest giving user an option to use inline column addition
instead of popup dialog. Most power users like myself would want to go thru
stuff as fast as possible.

**Comment by serge-rider** [comment]
Thank you for looking into it.

> But I would suggest giving user an option to use inline column addition instead of popup dialog. 
We will create FR for it
