### ISSUE TITLE
Can't save changed values

### ISSUE THREAD

**Issue by thms-k** [dbeaver/dbeaver#22535]
### Description

Hi,
I'm connected to a MySQL database via JDBC. I also created a SQL query which works fine. The problem occurs when I change a value in the table the query gives me. When I try to save it, I get the message:

`Can't update attribute 'name of attribute' - attributes of key 'VIRTUAL_PK' are missing in result set`

How can I solve this?
Thanks!

### DBeaver Version

DBeaver Enterprise Version 23.3.0.202312110545

### Operating System

Windows 10

**Comment by E1izabeth** [comment]
Could you provide some minimal example to reproduce the issue? Or maybe you could show a query giving a result set on which you get an error when editing?

**Comment by thms-k** [comment]
Thank you for your swift reply! This is the query I'm running:

```
SELECT
    k.jahr,
    k.zeit,
    k.d_zeit,
    k.titel,
    s.vorname,
    s.nachname,
    s.institut,
    a.bezahlt,
    a.teilnahmebest,
    k.id,
    a.stammdaten_id,
    a.d_anmeldung,
    a.d_ruecktritt,
    a.warteliste,
    a.anmerkungen
FROM
    anmeldung_fam.anmeldungen a
INNER JOIN anmeldung_fam.kurse k ON
    a.kurs_id = k.id
INNER JOIN anmeldung_fam.stammdaten s ON
    a.stammdaten_id = s.id;
```

Every field gives me the error message when I changed it and try to save it.

**Comment by LonwoLonwo** [comment]
Hello @barghest 

I see only one ID column in your select. Do you have other keys from your tables in your statement? Without your table DDL's it is hard to say. And without keys, DBeaver can't update data.

Maybe this answer will be helpful: https://github.com/dbeaver/dbeaver/issues/19276#issuecomment-1458536698

**Comment by thms-k** [comment]
Hi @LonwoLonwo

Thank you for the hint. I checked an additional id-Box in the query builder and now it works. So, to work properly I always need those id columns?

![Screenshot Query](https://github.com/dbeaver/dbeaver/assets/84884/c222edeb-70da-441b-b056-43dcadc2f91f)

**Comment by LonwoLonwo** [comment]
To help DBeaver find the appropriate key for update - yes. 

Another option is - to specify virtual PK manually:

![2024-01-23 12_02_43-DBeaver Ultimate 23 3 3 - _postgres 6 1_ Script-122](https://github.com/dbeaver/dbeaver/assets/45152336/9f61e0f2-1bb9-4b06-9471-98f8588061b3)

**Comment by thms-k** [comment]
Thanks a lot for your help!

**Comment by LonwoLonwo** [comment]
Thanks for the update!
