### ISSUE TITLE
Field suggestion not working when using ctrl + space in a join query

### ISSUE THREAD

**Issue by djsnake81** [dbeaver/dbeaver#22541]
### Description

When using join in a query with table renaming (i.e. select a.*, b.* from tableA as a inner join tableB as b on (a.id = b.id)), if i want to use field suggestion with ctrl+space, for example taping a. and then ctrl+space, it doesn't show any field. The list remains empty.

### DBeaver Version

22.3.3

### Operating System

Windows 11

### Database and driver

SQL Server - mssql-jdbc 12.4.1-jre11

**Comment by Destrolaric** [comment]
Hi, could you see if it works if experimental features are enabled:
Editors -> SQL Editor -> Code Completion -> Enable experimental features

![image](https://github.com/dbeaver/dbeaver/assets/20579256/664bc8b2-8c1f-4a11-94f8-13e1b6424194)

**Comment by djsnake81** [comment]
Hi, thanks for your answer.
I checked and i already have it enabled. I tried disabling it and then suggestion works back.

**Comment by Destrolaric** [comment]
Hmm, can you provide a more detailed query example, I couldn't reproduce it when it was enabled.

**Comment by djsnake81** [comment]
select a. 
from tableA as a 
inner join tableB as b on (a.id = b.id);

If i try to use the suggestion with ctrl+space after the a. with experimental features on i have nothing in the popup, with the experimental features off i have the list of fields for the a table

**Comment by Destrolaric** [comment]
I unfortunately can't reproduce the mentioned issues in the latest version. 
![java_hMYC49AK8I](https://github.com/dbeaver/dbeaver/assets/20579256/378459db-bdb1-46d7-b157-772926ca525f)

![java_HCntLqBrpf](https://github.com/dbeaver/dbeaver/assets/20579256/4b5ed285-5090-4a31-8b91-6167b63f3971)

**Comment by Destrolaric** [comment]
@djsnake81 Hi again, are there any noticeable differences with the query provided above?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and answer the last question asked.
