### ISSUE TITLE
Date Picker for Date Field

### ISSUE THREAD

**Issue by samyem** [dbeaver/dbeaver#2254]
Can the grid data editor show date picker when editing date fields similar to what some other similar tools do like:
![image](https://user-images.githubusercontent.com/323450/31139768-92db976e-a840-11e7-94cc-04f467be2dc6.png)

**Comment by serge-rider** [comment]
DBeaver had date/time picker a time ago. Eventually we replaced it with text string editor because of multiple requests.
We could try to combine both plain text editor and datetime picker.

**Comment by YassienW** [comment]
Which settings is used to enable the date picker?

**Comment by weeman1337** [comment]
Does anyone know how this works? For me no picker appears.

**Comment by pdimh** [comment]
It seems the last couple commits of this issue never got merged. The PR got merged before them.

**Comment by cbush06** [comment]
Check `Activate advanced datetime editor` under the `Miscellaneous` section here: 
![image](https://user-images.githubusercontent.com/15720146/210601746-d99850b2-0862-4dc8-9d5c-a4b61208bc8d.png)
