### ISSUE TITLE
Font sizes for code and line numbers are not balanced

### ISSUE THREAD

**Issue by bradadamsvumc** [dbeaver/dbeaver#22545]
### Description

After updating to the latest version this morning, the font sizing/scaling has changed. Line numbers appears larger than before (scaled up) and code/text is smaller than before (scaled down). I tried resetting code editor to default settings but the issue persisted. 

![image](https://github.com/dbeaver/dbeaver/assets/140536724/17876063-9d20-4d40-b9b7-815629c393a7)

### DBeaver Version

Community Edition  23.3.3.202401211839

### Operating System

Windows 10 Enterprise 19045.3930

**Comment by E1izabeth** [comment]
Could you try changing fonts here?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/535779d0-79f5-4000-a60c-9b794f93d4c5)

**Comment by bradadamsvumc** [comment]
Thank you for the quick response. I had to change off Courier New 10 to something else and apply. Then change back to Courier New 10 and apply. Then everything returned to it's normal scale.

**Comment by E1izabeth** [comment]
We've made some fixes. You could try Early Access version if you experience it once again on the current version you use https://dbeaver.io/files/ea/

**Comment by Matvey16** [comment]
Verified
