### ISSUE TITLE
The query editor zoom levels were reset after the latest update and I need to ajust it everytime I open a new query tab.

### ISSUE THREAD

**Issue by marcelodmc3** [dbeaver/dbeaver#22548]
### Description

I have some eye sight issues so I like to keep my zoom very high while writing queries.

I updated my DBeaver Community Edition yesterday to the 23.3.3.202401211839 version and my previously set zoom was reset. Now after I open a new tab on the query editor I need to manually go to the "Window > Editor > Zoom In" option to increase the zoom to the levels I like. Also the shortcut **Ctrl** +**+** is not working anymore.

Weirdly enough the cursor maintained it's original size after the update:

![image](https://github.com/dbeaver/dbeaver/assets/5389879/5a7776fc-c9a2-4926-bcf9-4fd7450ccc95)

### DBeaver Version

23.3.3.202401211839

### Operating System

Windows 11 x64 23H2

### Database and driver

PostgreSQL 11.9

![image](https://github.com/dbeaver/dbeaver/assets/5389879/301628f8-f5ed-46fc-81c6-3a8b838e0fcc)

### Steps to reproduce

Open DBeaver > Open a new query editor  TAB > Set the zoom > Open a new query editor TAB and the new tab zoom is reset except for the blinking cursor.

**Comment by E1izabeth** [comment]
@marcelodmc3 
As a workaround you could try changing fonts here
 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/535779d0-79f5-4000-a60c-9b794f93d4c5)

Please let me know if it helps.

**Comment by E1izabeth** [comment]
We've made some fixes. You could try Early Access version https://dbeaver.io/files/ea/

**Comment by Matvey16** [comment]
Verified

**Comment by marcelodmc3** [comment]
@E1izabeth After updating to the Early Access version it seems to be working fine. Thank you!
