### ISSUE TITLE
Editor and results tab query part starts with small font

### ISSUE THREAD

**Issue by ufuk-ergin-carbon** [dbeaver/dbeaver#22554]
### Description

After the update yesterday, the editor and the results tab query (SQL console) font start with small fonts by default. You have to change the editor font everytime back to what you want by first increasing the font and then decreasing, so the small start is actually somewhere smaller than you last wanted. There is even no way to change the sql console font. I attach a screen recording for these.

### DBeaver Version

Version 23.3.3.202401211839

### Operating System

MacOS Sonoma 14.3

### Database and driver

Snowflake Server version: Snowflake 8.2.0
Driver version: Snowflake 3.13.30

https://github.com/dbeaver/dbeaver/assets/114302087/980cf43c-2a65-48f9-9c27-88ba7d0802a9

https://github.com/dbeaver/dbeaver/assets/114302087/e5153238-bda3-47f0-b6f1-5daed1d894e0

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/14020841/dbeaver-debug.log)

**Comment by E1izabeth** [comment]
@ufuk-ergin-carbon 
Could you try changing fonts here?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/535779d0-79f5-4000-a60c-9b794f93d4c5)

**Comment by ufuk-ergin-carbon** [comment]
I did and it made things worse. Now, I cannot even find the original font I screen recorded. How do I get it back?

**Comment by E1izabeth** [comment]
@ufuk-ergin-carbon you could press `Reset` here for some concrete font or color or `Restore defaults`  button to reset all setting on this page.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/a0670a84-852a-4c36-ab67-4fa8d5c84be4)

**Comment by ufuk-ergin-carbon** [comment]
I did that too, however, I am not getting it back. Also, what is the show preview feature supposed to? I turned it on on adjusting font window, however, it is showing nothing. Is that how it is supposed to work? 

https://github.com/dbeaver/dbeaver/assets/114302087/66c63f67-a085-4471-bd83-4d5754ccd16f

**Comment by E1izabeth** [comment]
It's a macOS-specific view. Unfortunately, I can't say.

**Comment by E1izabeth** [comment]
@ufuk-ergin-carbon 
We've made some fixes. You could try Early Access version https://dbeaver.io/files/ea/

**Comment by ufuk-ergin-carbon** [comment]
Does it override settings especially for database connection? And, if there are issues, can I go back to original stable release?

**Comment by E1izabeth** [comment]
It's a common issue, not just for some concrete database.
You can download the version you want and just run installer any time.

**Comment by Matvey16** [comment]
Verified
