### ISSUE TITLE
All dashboards are closed, but the background task of dashboard update is still working

### ISSUE THREAD

**Issue by m1013923728** [dbeaver/dbeaver#22553]
### Description

![WechatIMG11](https://github.com/dbeaver/dbeaver/assets/11659970/be893fe6-d834-4113-8d37-7cbdd0430af1)

All dashboards are closed, but the background task of dashboard update is still working, sometime cause high cpu.

### DBeaver Version

23.3.2.202401072024

### Operating System

macOS Ventura 13.4.1

**Comment by LonwoLonwo** [comment]
Hello @m1013923728 

Thanks for the bug report. I can reproduce it.

```java
public static void startUpdating() {
        new DashboardUpdateJob().schedule(JOB_DELAY);
}
```

As a workaround - it will stop if you stop it manually.

![2024-01-23 10_56_49-All dashboards are closed, but the background task of dashboard update is still ](https://github.com/dbeaver/dbeaver/assets/45152336/ec8535af-dfee-47a8-abfb-1a5615afba75)
