### ISSUE TITLE
Individual queries don't get removed from the outline view when deleted from the SQL editor

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#22551]
### Description

https://github.com/dbeaver/dbeaver/assets/35821147/437e3371-8939-4dcb-938f-a24b8720f238

### DBeaver Version

DBeaver 23.3.3

**Comment by E1izabeth** [comment]
Can't reproduce anymore. Seems it was solved with #22778

**Comment by MashaKorax** [comment]
Can't reproduce the issue.
