### ISSUE TITLE
Pinned grid copy value from unpinned grid issue

### ISSUE THREAD

**Issue by roparo** [dbeaver/dbeaver#2257]
with first result set grid  pinned, run a query to generate a second grid (unpinned).

Select FIRST pinned grid and copy the first (row/column) value.
When you paste it, it will paste the same position value from the SECOND (unpinned) grid.

If you close one of those grids, it will copy the correct value.

Big issue!!

**Comment by serge-rider** [comment]
I can't reproduce this. Perhaps I didn't understand the use case. 
Could you make a small gif video (e.g. with ScreenToGif  or some similar tool).

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. Perhaps, it was solved. This ticket will be closed. However, if you think that it is actual just let us know.
