### ISSUE TITLE
Key Pair Authentication to Snowflake Still Not Working

### ISSUE THREAD

**Issue by st3veh** [dbeaver/dbeaver#22588]
### Description

Regarding connecting to Snowflake from DBeaver using key-pair authentication, at the end of this Issue: https://github.com/dbeaver/dbeaver/issues/22008#issuecomment-1829327624, I said that if I just changed my parameters in DBeaver from (private_key_file and private_key_file_pwd) to (private_key_path and private_key_file_passphrase), then this error goes away: error, "Private key provided is invalid or not supported: … PBE parameter parsing error: expecting the object identifier for AES cipher."  So, I thought that fixed the problem.

However, I had also been entering the username and password, and I had turned off MFA in Snowflake during troubleshooting.  Once I turned it back on, DBeaver started prompting me to do MFA steps, and I realized that DBeaver isn't using key-pair authentication at all, it is just using the username-password authentication.  So, something behind-the-scenes needs to be updated in DBeaver for this to work.

Similar to the behavior described in this post (https://community.snowflake.com/s/article/Using-Private-Key-authentication-in-DBeaver), the password shouldn't matter.  DBeaver should be doing something like this (https://docs.snowflake.com/en/developer-guide/node-js/nodejs-driver-connect) behind-the-scenes with the key-pair parameters, and not sending the password to Snowflake when it connects.

### DBeaver Version

Community Edition 23.3.3

### Operating System

Windows 11

### Database and driver

Snowflake JDBC Driver, release 3.14.5

### Steps to reproduce

See https://github.com/dbeaver/dbeaver/issues/22008#issuecomment-1829327624.

**Comment by Matvey16** [comment]
@st3veh Thank you for the report

**Comment by st3veh** [comment]
Above, where I said DBeaver should be doing something like this (...), it looks like I put in the wrong link.  This was the one I meant to include: https://docs.snowflake.com/en/developer-guide/node-js/nodejs-driver-authenticate#using-key-pair-authentication-and-key-pair-rotation.

**Comment by LonwoLonwo** [comment]
Hello @st3veh 

We have key-pair authentication in our PRO version.

![2024-02-08 19_39_46-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/cded0cb4-63b3-4371-b78e-1d1ef5768cf5)

Could you please check it? You can do it with the trial license: https://dbeaver.com/trial/

**Comment by st3veh** [comment]
That worked.  Good to know.  It is only available in the PRO edition.  I will update the Snowflake forum.

**Comment by st3veh** [comment]
Closing.

**Comment by LonwoLonwo** [comment]
Thanks for checking!
And for an excellent explanation of the issue.

**Comment by nutmix** [comment]
> Hello [@st3veh](https://github.com/st3veh)
> 
> We have key-pair authentication in our PRO version.
> 
> ![2024-02-08 19_39_46-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/cded0cb4-63b3-4371-b78e-1d1ef5768cf5)
> 
> Could you please check it? You can do it with the trial license: https://dbeaver.com/trial/

Hi, where can we get the pro version? The website only has lite, enterprise, ultimate, cloud and team.
enterprise and ultimate are way to expensive for individuals to purchase.  Does the lite support snowflake with key and key password?

**Comment by nutmix** [comment]
FYI, I tried the "lite" version, and it has the private key authentication option. However it doesnt work either, it gives:

JWT token is invalid. [f73b031d-6074-4ea1-834c-9087fd422078]

**Comment by st3veh** [comment]
Yes, I think the conversation above happened when the product naming convention was a bit different.  Now that they have Lite, Enterprise and Ultimate, any of those will have Key Pair Authentication available.  (I only tested on Lite, but I would assume they keep that feature as you move up.)  When you create your Snowflake connection, just select Authentication: Private key.  Then point the Private key field to the location on your machine where you keep the private key file, and in the Key password field, put the password you made when you created the private key file.
