### ISSUE TITLE
Can't connect to Postgres using Pgpass and Azure Access Token

### ISSUE THREAD

**Issue by Haitam95** [dbeaver/dbeaver#22587]
### Description

Im trying to connect to postgres using Pgpass. 
1. I provided Host, Db, Auth : Pgpass, Username
2. I set up Ssh host and public key
3. Then in Shell command tab, i activated before connection and typed : `Powershell.exe -NoProfile -ExecutionPolicy ByPass -File .\pgpass.ps1`
4. I now have my pgpass.ps1 in home directory. The file generated is in C:\Users\e006752\AppData\Roaming\postgresql
5. The content of my ps1 file : 
```
$pgpassFilePath = "C:/Users/e006752/AppData/Roaming/postgresql/pgpass.conf"

# Run the command to get the access token
$accessToken = az account get-access-token --resource-type oss-rdbms --query accessToken -otsv

# Construct the content for the pgpass file
$pgpassContent = "*:*:*:*:$accessToken"

# Write the content to the pgpass file
$pgpassContent | Out-File -FilePath $pgpassFilePath -Encoding utf8

Write-Host "pgpass file generated successfully at $pgpassFilePath"

I get this Error : Couldn't Get password from Pgpass File. No Matches in Pgpass
```

### DBeaver Version

Community Version 23.3.3.202401211417

### Operating System

Windows 10

**Comment by Matvey16** [comment]
@Haitam95 Thank you for the report. I can't seem to find any steps that you do in DBeaver itself. It looks like this issue occurs even before anything in DBeaver. Can you clarify it?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
