### ISSUE TITLE
[l18n] Add Romanian language

### ISSUE THREAD

**Issue by v613** [dbeaver/dbeaver#22586]
Hello DBeaver,

I want to contribute by adding the Romanian language by myself.

According to the [Contribution guide](https://github.com/dbeaver/dbeaver/wiki/Database-driver-SQLite), it's required to create a ticket.

In the meantime, I made a [fork](https://github.com/v613/dbeaver/tree/l18n/ro_RO-localization) and translated the "core" module. According to my calculations, I could translate one module per day

### Modules to be translated
- [x]  cmp
- [x]  core
- [x]  data
- [x]  debug
- [x]  erd
- [x]  ext
- [x]  model
- [x]  net
- [x]  registry
- [x]  tasks
- [x]  team
- [x]  ui

**Comment by arhayka** [comment]
Hello, @v613! Thank you for being with DBeaver! We appreciate your support and want to send you a compliment. Please write to an email [anna.pozdeeva@dbeaver.com](mailto:anna.pozdeeva@dbeaver.com) and provide your nickname in GitHub, First and Last Name and email.

**Comment by v613** [comment]
> Hello, @v613! Thank you for being with DBeaver! We appreciate your support and want to send you a compliment. Please write to an email [anna.pozdeeva@dbeaver.com](mailto:anna.pozdeeva@dbeaver.com) and provide your nickname in GitHub, First and Last Name and email.

Thank you!
I've just sent the message.
