### ISSUE TITLE
Table names identical to any sql command must be enclosed in quotation marks or acting strangely.

### ISSUE THREAD

**Issue by TB-HunBoka** [dbeaver/dbeaver#22594]
### Description

dbeaver autocomplete puts table names that match any sql command in quotation marks.
If I do not write the name of the object name in lowercase letters or put it in quotation marks, then Query Analysis feature does not recognize it as an object.

If I write the object name in lowercase letters then the column name auto completion doesn't works, but the Query Analysis does

Other objects whose name does not match any sql command, works well with uppercase, lowercase and quotation marks too.

![kép](https://github.com/dbeaver/dbeaver/assets/126617861/4ddff331-171a-4393-8547-119ea0c61ede)

### DBeaver Version

Community Edition 23.3.3.202401211839

### Operating System

Windows 10

### Database and driver

I could only test this with Snowflake.

**Comment by E1izabeth** [comment]
Thank you for bug report.
