### ISSUE TITLE
Connection Issue with MariaDB and Inquiry on Connecting to Virtual Machines

### ISSUE THREAD

**Issue by DavidRG25** [dbeaver/dbeaver#22592]
### Description

I am experiencing while attempting to connect to a MariaDB database using DBeaver.

Upon attempting to establish a connection, I am encountering the following error message: “unexpected end of stream, read 0 bytes from 4 (socket was closed by server).” I have verified the connection details, including the host address, port, username, and password, and all seem to be correct.

Could you please provide guidance on troubleshooting this issue? Are there specific settings or configurations that I should be aware of when connecting to a MariaDB database using DBeaver?

Additionally, I am interested in understanding whether DBeaver supports connections to databases hosted on virtual machines. I am currently attempting to connect to a MariaDB instance running on a virtual machine in Azure, and I would appreciate any insights or recommendations you may have.

Thank you for your time and assistance. I look forward to your prompt response.

### DBeaver Version

23.3.3

### Operating System

Windows 10

### Database and driver

DB: Mariadb Ver 15.1 Distrib 10.6.16-MariaDB
Drivers: MariaDB JDBC driver

### Steps to reproduce

Open DBeaver:

Launch DBeaver on your local machine.

New Connection:

In the left panel, select "Database," then choose "New Database Connection."

Connection Configuration:

Select the database you are using (In my case, I would choose MariaDB).
Enter the IP address of the virtual machine in the "Host" or "Hostname" field.
Enter the database port in the corresponding field.
Provide the name of the database.
Enter the username and password.
Connection Test:

After completing the connection details, click on the "Test Connection" button. This is where it indicates the error for me.
![Captura-Error-Dbeaver](https://github.com/dbeaver/dbeaver/assets/123817881/99caa6c0-55df-4732-92b8-38e25685e16e)

**Comment by LonwoLonwo** [comment]
Hello @DavidRG25 

Maybe you can find some answers here: https://github.com/dbeaver/dbeaver/issues/21812
Or here: https://forums.opensuse.org/t/dbeaver-mysql-workbence-unable-to-connect-to-remote-mysql/152497
Or here: https://github.com/dbeaver/dbeaver/issues/19388#issuecomment-1783902344

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
