### ISSUE TITLE
Sql statement does not execute correctly

### ISSUE THREAD

**Issue by Agility6** [dbeaver/dbeaver#22606]
### Description

Syntax error in executing sql statement using DBeaver
<img width="1385" alt="error" src="https://github.com/dbeaver/dbeaver/assets/75616395/d48cb1f1-0379-4cd2-b45b-9f4f89d38519">

Use the command line to execute the `source` command to execute the sql statement, which can be run successfully
<img width="953" alt="done" src="https://github.com/dbeaver/dbeaver/assets/75616395/a18f1729-e96e-42f4-8cae-df1b33947908">

### DBeaver Version

Community Edition 23.3.2

### Operating System

macOS Ventura 13.6.3

### Database and driver

Mysql8.2.0
Driver for MySQL 8 and later

**Comment by Agility6** [comment]
```sql
use test

drop table if exists auth_login;

drop table if exists balance_detail;

drop table if exists coach;

drop table if exists coach_exam_place;

drop table if exists dict_item;

drop table if exists dict_type;

drop table if exists exam_place;

drop table if exists exam_place_course;

drop table if exists exam_place_course_order;

drop table if exists image;

drop table if exists plate_region;

drop table if exists school;

drop table if exists student;

drop table if exists user;

drop table if exists withdraw;
```

**Comment by Agility6** [comment]
I feel like this question is similar to mine #11656

**Comment by humphreygao** [comment]
请多看看左侧执行按钮下面，有没有执行 script 按钮？你点一下试试。

**Comment by LonwoLonwo** [comment]
Hello @Agility6 

Looks like you are trying to execute these queries as one query.
But if you want to execute all queries ones - you need to use the "Execute as a script" button:

![2024-01-29 11_04_47-Window](https://github.com/dbeaver/dbeaver/assets/45152336/7356a9d8-f8f4-49c7-99a5-b06f7106cf7e)

**Comment by Agility6** [comment]
@LonwoLonwo  Thanks for your reply, I followed your method of executing the sql statement and still get an error.

<img width="1396" alt="Snipaste_2024-01-29_18-41-53" src="https://github.com/dbeaver/dbeaver/assets/75616395/cc327659-3ddd-4da3-be35-5dddfed15df5">

This is strange, my sql statement is copied from vscode to DBeaver, is it because of this problem?

Here's my procedure, hope it helps.

https://github.com/dbeaver/dbeaver/assets/75616395/677914e2-c1bc-4f6f-a63b-a430400cb3a4

**Comment by humphreygao** [comment]
第一行写个分号啊

**Comment by LonwoLonwo** [comment]
As @humphreygao  said, you need to add a semicolon after the query "use test" on the first row

**Comment by Agility6** [comment]
Oh sorry I didn't notice thanks @LonwoLonwo @humphreygao 😵😵😵
