### ISSUE TITLE
When i am in google meet and i am sharing my screen in meeting, dbeaver will hang in Ubuntu

### ISSUE THREAD

**Issue by jayesh-bhadani** [dbeaver/dbeaver#22615]
### Description

1. open dbeaver
2. join google meet and share the entire screen
3. now goto dbeaver and doing something like view some table's data and it will hang.

### DBeaver Version

23.3.3

### Operating System

Ubuntu 22

### Database and driver

no

### Steps to reproduce

1. open dbeaver
2. join google meet and share the entire screen
3. now goto dbeaver and doing something like view some table's data and it will hang.

### Additional context

no

**Comment by LonwoLonwo** [comment]
Hello @jayesh-bhadani 

Could you please try to generate a thread dump during this moment and attach it here? Here is the instruction: https://dbeaver.com/docs/wiki/Making-a-thread-dump/
Thank you.

**Comment by Destrolaric** [comment]
@jayesh-bhadani Hi, can you please input the following command in terminal and send the output
`echo $XDG_SESSION_TYPE
`

**Comment by Destrolaric** [comment]
Also, is Google Meet launched from the Google Chrome/Chromium browser? if that is the case could you also 
send me the state of the `chrome://flags/#enable-webrtc-pipewire-capturer` parameter? You can look at it by pasting the flag link in the URL bar.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by malchikovma** [comment]
I have the same problem.
echo $XDG_SESSION_TYPE - wayland
chrome://flags/#enable-webrtc-pipewire-capturer - no such parameter, Chrome Version 123.0.6312.122 (Official Build) (64-bit)

**Comment by malchikovma** [comment]
I'll make thread dump as soon as I catch this behavior again.
