### ISSUE TITLE
Download jdbc driver failed

### ISSUE THREAD

**Issue by gaojinkui** [dbeaver/dbeaver#22614]
### Description

We have installed dbeaver 23.3.3 on Ubuntu 22.04.3, when we set up a connection to database server (SQL Server, MySQL), there is a pop up windows to download JDBC driver, after click Download button, we get error below, it is annoying...

Driver file download failed.
Do you want to retry?

Reason:
/tmp/.dbeaver-temp/driver-files/57E15E524FD501B993BDB2D795B0A5DA

### DBeaver Version

Version 23.3.3.202401211839

### Operating System

Ubuntu 22.04.3,

### Steps to reproduce

1. Open dbeaver client from Ubuntu UI
2. Click "New Database Connection"
3. Select MySQL for example, click Next
4. Click "Test Connection"
5. In the new windows for download, click Download
6. We got error "Driver file download failed."

**Comment by LonwoLonwo** [comment]
Hello @gaojinkui 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by gaojinkui** [comment]
Sorry, my colleague has re-installed a lower version dbeaver, I couldn't get full log.

below is the screenshot I kept before. but we have tried, the user can create directory under /tmp directory.
[cid:fecef450-cbd1-44ca-bb6d-95377c2df17a]

BRs
Gao Jinkui
________________________________

**Comment by LonwoLonwo** [comment]
You need to add your screenshot on this GitHub page. It doesn't work via e-mail.

**Comment by gaojinkui** [comment]
[log-screenshot.pdf](https://github.com/dbeaver/dbeaver/files/14105971/log-screenshot.pdf)
