### ISSUE TITLE
variable declarion Azure SQL server not working with semicolon.

### ISSUE THREAD

**Issue by braampje** [dbeaver/dbeaver#22624]
### Description

Since some time running this simple script doesn't work with semicolons in between, while this was no problem on a previous version. Maybe updating Dbeaver caused a setting to change, but I can't find which one potentially caused this.

![image](https://github.com/dbeaver/dbeaver/assets/11930454/f51788c6-9161-4832-a33a-6d021303a8d0)

### DBeaver Version

Version 23.2.5.202311191730

### Operating System

Windows server 2012 R2

### Database and driver

Azure SQL server , 11.2.3.jre11

**Comment by uslss** [comment]
thanks for the report.
As a workaround you can select whole statement and press Ctrl+Enter to run it.

**Comment by braampje** [comment]
Thanks for the reply, that is what I used to do, but this also stopped working somehow. Both alt x and ctrl enter give the same error now.

**Comment by E1izabeth** [comment]
@braampje please try latest DBeaver version 23.3.5

**Comment by braampje** [comment]
@E1izabeth we just reinstalled to a higer version and indeed it seems the strange behavior is gone again. Thanks for the tip!

**Comment by E1izabeth** [comment]
Thank you for update
