### ISSUE TITLE
DBeaver installer does not support command-line parameter "/D" as expected

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2262]
DBeaver - **Version 4.2.2 CE**
Operating System: **Windows 7 / Windows 8.1**

When specifying a "/D" command-line parameter when installing DBeaver, it has no effect what so ever. It does not matter if I try the 32-bit installer or the 64-bit installer. They both do as bad.

The links below state that the installer uses NSIS installer. The "/S" parameter for silent install work, but the "/D" parameter has no effect.

[DBeaver Forum](https://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=1798)
[SourceForge](http://nsis.sourceforge.net/Docs/Chapter4.html#silent)

**Comment by serge-rider** [comment]
Yes, this issue appeared after adding support of installation for current user option.

**Comment by serge-rider** [comment]
We going to switch to Windows MSI installer after DBeaver 4.3.
NSIS is so old and poorly supported :(

**Comment by serge-rider** [comment]
Will be fixed in #2783 in 4.3.3

**Comment by pdanie** [comment]
This issue is still not fixed in _DBeaver_ version **5.1.2 CE**.

**Comment by tati-kru** [comment]
@pdanie Thank you for the report. 
Unfortunately, it is really complicated issue. It was fixed but reverted after some time due to a conflict with another functional. 
I will reopen it but it looks like we need help of someone else for this issue.

**Comment by pdanie** [comment]
Ok. The issue popped up since we have trouble running our rebundled version of _DBeaver_ on Windows 7.

If you thinking on rewrite the the insallation, I'm really fond of myself of _Inno Setup_. We also have a MSI installer, but that does not work as good as _Inno Setup_.
