### ISSUE TITLE
Disabling all metadata queries when executing queries in SQL Editor Execution for Greenplum database

### ISSUE THREAD

**Issue by CC-Hsu** [dbeaver/dbeaver#22637]
Hi, Team,

I find that when executing queries in the SQL Editor, it takes additional time to complete compared with directly executing query,
and I observe that there are several metadata queries are executed along with the queries in the SQL Editor.

Sometimes it take additional 10~30 seconds when executing queries in a database with many objects, which is annoying for users.

And for some systems it is less likely have too many metadata queries to occupy database system resource.

For example, in the above Query Manager screenshot, I execute a query `SELECT * FROM pg_class LIMIT 10` in a Greenplum 6.25.1 database (one of PostgreSQL database derivatives), DBeaver executes 9 additional queries.
![dbeaver-query_manger](https://github.com/dbeaver/dbeaver/assets/8018872/80cc1d0e-5016-4409-ae3d-182a4c71a5c5)

In the above metadata queries, the below SQL takes 2 seconds to complete.
```
SELECT i.*,i.indkey as keys,c.relname,c.relnamespace,c.relam,c.reltablespace,tc.relname as tabrelname,dsc.description,pg_catalog.pg_get_expr(i.indpred, i.indrelid) as pred_expr,pg_catalog.pg_get_expr(i.indexprs, i.indrelid, true) as expr,pg_catalog.pg_relation_size(i.indexrelid) as index_rel_size,pg_catalog.pg_stat_get_numscans(i.indexrelid) as index_num_scans
FROM pg_catalog.pg_index i
INNER JOIN pg_catalog.pg_class c ON c.oid=i.indexrelid
INNER JOIN pg_catalog.pg_class tc ON tc.oid=i.indrelid
LEFT OUTER JOIN pg_catalog.pg_description dsc ON i.indexrelid=dsc.objoid
WHERE  i.indrelid=1259 ORDER BY c.relname
```

It would be great if such metadata queries can be disabled completely.

Best Regards.

**Describe the solution you'd like**
Provide some options to completely disable metadata query during SQL Editor Query Execution.

**Describe alternatives you've considered**
Caching these metadata required by SQL Editor when a connection start, and avoiding to repeat these metadata queries whenever executing SQL in the editor.

**Comment by LonwoLonwo** [comment]
Hello @CC-Hsu 

You can disable this behavior with these settings:

![2024-01-30 18_28_59-Preferences](https://github.com/dbeaver/dbeaver/assets/45152336/4c664bf4-47be-40a5-a1c0-b74125f1af42)

But without key info, it will be hard to edit data values in the result set.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
