### ISSUE TITLE
Unable to create a table in Cassandra using the context menu or Alt + Insert

### ISSUE THREAD

**Issue by neilsteyn** [dbeaver/dbeaver#22636]
### Description

I'm unable to create a table in a keyspace for cassandra

![image](https://github.com/dbeaver/dbeaver/assets/20437001/028a3846-4d29-487b-ac09-f624f41d7912)

Alt + Insert

![image](https://github.com/dbeaver/dbeaver/assets/20437001/c345260f-0a2a-4d39-a6fe-f0c89882e62a)

But for other database, like MySQL I can:

![image](https://github.com/dbeaver/dbeaver/assets/20437001/b730adf8-98bc-459d-a2e8-8a44f5b51901)

### DBeaver Version

Ultimate 23.2.0

### Operating System

Windows 11 Pro

### Database and driver

Driver for Apache Cassandra 2.x/3.x/4.x

![image](https://github.com/dbeaver/dbeaver/assets/20437001/7b7a82e9-98c0-4c33-b33b-2d1b38a4385d)

**Comment by LonwoLonwo** [comment]
Hello @neilsteyn 

This feature is not supported for now because it is important to create PK along with a table for Cassandra.

Also, we have this related issue: https://github.com/dbeaver/dbeaver/issues/17187
