### ISSUE TITLE
Wrong syntax highlight for Oracle DB 

### ISSUE THREAD

**Issue by VadimMuhtarov** [dbeaver/dbeaver#22641]
### Description

Sometimes syntax highlighting doesn't work for schema names (AUTH for example)

### DBeaver Version

23.3.3

### Operating System

macOS 14.3

### Database and driver

Oracle 19
org.jkiss.dbeaver.ext.oracle, Version: 2.1.208.202401211839
org.jkiss.dbeaver.ext.oracle.ui, Version: 1.0.110.202401211839

### Steps to reproduce

I don't know how to reproduce it exactly, I have this bug in 2 queries on my screen. These requests work without problems.

### Additional context
![3](https://github.com/dbeaver/dbeaver/assets/17072773/1cb29a61-b892-48e2-83bf-a5bb405265ac)
![2](https://github.com/dbeaver/dbeaver/assets/17072773/8285aae5-9be9-4821-9e6c-cceb094fe150)

**Comment by uslss** [comment]
thanks for the report

issue is reproducible for AUTH schema name. Even if it doesn't exists it is not highlighted as red

![image](https://github.com/dbeaver/dbeaver/assets/31996417/f28ce19f-cb0c-49e9-81c7-3ddec01036f1)

**Comment by VadimMuhtarov** [comment]
Also the "VALUE" column is not highlighted in SELECT and WHERE. Should I create another bug for it?
 
<img width="644" alt="Screenshot 2024-02-02 at 11 30 42" src="https://github.com/dbeaver/dbeaver/assets/17072773/ca8fe909-e821-4dfe-a0a4-03033318e413">
<img width="319" alt="Screenshot 2024-02-02 at 11 49 01" src="https://github.com/dbeaver/dbeaver/assets/17072773/bb055cf2-9b23-4898-8bfa-560845319508">

**Comment by VadimMuhtarov** [comment]
Now I have a regression bug in DBeaver 23.3.4. The table name is displayed as incorrect if the schema is not specified in the SELECT, and if the schema is specified, its name is highlighted in the wrong color. Especially noticeable when merging multiple tables using JOIN
<img width="293" alt="Screenshot 2024-02-06 at 12 03 28" src="https://github.com/dbeaver/dbeaver/assets/17072773/4d033fce-7c29-4ced-8d0d-ba17e64a7ef9">
<img width="316" alt="Screenshot 2024-02-06 at 12 03 44" src="https://github.com/dbeaver/dbeaver/assets/17072773/462ba38f-8144-4c7f-98de-b4de0e460a28">
