### ISSUE TITLE
automatic row count

### ISSUE THREAD

**Issue by JeroenNienhuis** [dbeaver/dbeaver#22657]
For a row count on a (result) table yu have to click on the count button on the bottom toolbar.
I often have large files and want to know the number of records or use the count as a check on sql command

Is it possible to calculate it by default? Perhaps add it as an option to do so on the data editor settings.

**Comment by E1izabeth** [comment]
Thank you for the idea

**Comment by GiorgioSgl** [comment]
This will be useful!

**Comment by ShadelessFox** [comment]
We have discussed this feature and propose the following requirements:
1. Row count must be calculated only once when opening the data viewer. It should not be triggered when new data is fetched.
2. The "data editor" preferences must have a setting to turn it on/off.

**Comment by JeroenNienhuis** [comment]
Does "only once when opening the data viewer" mean "every time an sql is executed"
and "not be triggered when new data is fetched" mean "not every time a next portion from LIMIT OFFSET is fetched"?
That would be nice.

**Comment by ShadelessFox** [comment]
Correct.
