### ISSUE TITLE
ipv6 domains pointing to postgresql server time out

### ISSUE THREAD

**Issue by JavaProgswing** [dbeaver/dbeaver#22663]
### Description

I had a postgresql 16.1 database running on a ipv6 address, I tried connecting to the ipv6 address and it worked but dbeaver cannot resolve it from the domain having an AAAA record to the same ipv6 address. The request results in a timeout in dbeaver and does work in pgadmin.

### DBeaver Version

Community Version 23.2.5

### Operating System

Windows 11 Version 22H2

### Database and driver

PostgreSQL 16.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
PostgreSQL JDBC Driver 42.5.2

### Steps to reproduce

1. Create a postgresql 16.1 database which is accessible by ipv6.
2. Link a domain to it by adding a AAAA record to the server's ipv6.
3. Access the server both by the domain and by the ipv6.
4. It times out to the domain but resolves to the raw ipv6.

### Additional context

1. I try to connect to the postgresql database hosted on a ipv6 address.
2. It does connect successfully to the raw ipv6 address.
3. I try to connect to the same using the domain having an AAAA record to the ipv6 address.
4. It fails to connect on the domain and results in a time out.

**Comment by LonwoLonwo** [comment]
Hello @JavaProgswing 

Maybe this is indeed the timeout issue?

Did you try to increase timeout period? You can find these settings in your driver properties page:

![2024-02-02 20_20_43-DBeaver Ultimate 23 3 4 - _DBeaver Sample Database (SQLite)_ Script-7](https://github.com/dbeaver/dbeaver/assets/45152336/cc9e6010-dd41-4711-a6d9-14455e297f90)

**Comment by JavaProgswing** [comment]
No as I said it works for the raw ipv6 but not the domain.

**Comment by JavaProgswing** [comment]
cuz both are basically pointing to the same ip, one shouldn't time out while the other works instantly.

**Comment by JavaProgswing** [comment]
@LonwoLonwo it connects to the raw ipv6 address instantly but does not connect(even when I increased timeout to 60s) to the domain which has a AAAA resource to the same ipv6 address.

And to prove that the domain works, I tried connecting to it from pgadmin and it worked!

**Comment by JavaProgswing** [comment]
@LonwoLonwo You should cross check this, I can post more details on how to reproduce this.

**Comment by JavaProgswing** [comment]
hey @LonwoLonwo, I can give you the domain and the raw ipv6 for which this wasn't working to reproduce this issue.

It seems it cannot resolve AAAA resource from the domain properly.

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by JavaProgswing** [comment]
Now it seems to work and I know why it wasn't working.

the domain had both A and AAAA record, it gave preference to the A record which led to a timeout.

**Comment by ShadelessFox** [comment]
Maybe the DNS settings were outdated. Anyway, thank you for the follow-up. I will close the issue as it's now resolved.

**Comment by JavaProgrammer11** [comment]
Still it's strange how pgadmin resolved it correctly, even if it had both A AND AAAA records(The ipv4 A record was timing out).

**Comment by JavaProgswing** [comment]
It is strange that pgadmin resolved it correctly, the domain had both A and AAAA record. it maybe checked the A record first then upon timeout resolved to the AAAA record.

**Comment by ShadelessFox** [comment]
We will never know for sure. Feel free to reopen this ticket if the issue arises again.

**Comment by JavaProgswing** [comment]
pgadmin seems to follow https://en.wikipedia.org/wiki/Happy_Eyeballs or something similar resolving all ipv6 addresses before ipv4 from A records. why doesn't dbeaver do the same?

**Comment by ShadelessFox** [comment]
This technology seems to be implemented mainly by web browsers. IIRC, pgAdmin4 is a web-based application, so it's something that's available from the box.

DBeaver is a Java-based application, and some Googling led me to the following: inside DBeaver's installation folder, there's a file called `dbeaver.ini`. You can add the line `-Djava.net.preferIPv6Addresses=true` after the `-vmargs` line in it. This hopefully will force Java to prefer IPv6 over IPv4 when selecting an address.

**Comment by JavaProgswing** [comment]
Oh I suspected that for pgadmin, thanks for the info!
