### ISSUE TITLE
Language preference should be locked whenever -nl is passed

### ISSUE THREAD

**Issue by hhmmjjnn** [dbeaver/dbeaver#22666]
### Description

This is an UX bug with the **User Interface** page of the **Preferences** window:

![image](https://github.com/dbeaver/dbeaver/assets/133042358/8fdc0f69-497b-4cc7-bfe4-4dbbed2aac66)

If `dbeaver.exe` was given the `-nl` option through the command line, then the **Language** field should be locked. An informative text label should pop right below it, explaining why so.

The thing is that the data store of this setting is ambiguous. It can come either...

1. from the file `%AppData%\DBeaverData\workspace6\.metadata\.plugins\org.eclipse.core.runtime\.settings\org.jkiss.dbeaver.core.prefs` ; or
1. from the command line, as the argument to the option `-nl` .

In the second case, the **Preferences** window would be hopeless trying to configure anything. By letting the user pick something in the **Language** field, we are selling the user an illusion that something is about to change. Then this expectation is bound to be frustrated.

The frustration manifests in two moments: immediate and long-term.

![image](https://github.com/dbeaver/dbeaver/assets/133042358/d0444aa9-328b-49f9-acb5-53a973c1cd92)

The immediate frustration arises right after clicking the **Apply** button. If `-nl` was given, the workbench is restarted in the very same language in that it previously was. That is because the argument is not cleared, internally, before reset:

https://github.com/dbeaver/dbeaver/blob/d83e5838dc4a5f6a50b891eaf730d0acd8923a56/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/preferences/PrefPageDatabaseUserInterface.java#L306

The long-term frustration comes from the fact that the overriding data store was not touched at all so, when the user re-opens DBeaver the next day, they are getting the old setting once again:

![image](https://github.com/dbeaver/dbeaver/assets/133042358/e9bcc8af-874e-4a9a-bb58-9710db143fe9)

### DBeaver Version

DBeaver Community Edition 23.3.0.202312031432

### Operating System

Windows 11 (21H2/10.0.22000.2652)

### Database and driver

Driver-independent.

### Steps to reproduce

1. Run `"%ProgramFiles%\DBeaver\dbeaver.exe" -nl en`
1. try to switch to any other language, from within the UI
1. when prompted to restart the workbench, press **Yes**
1. DBeaver restarts in English, once again, no matter what

### Additional context

1. https://github.com/dbeaver/dbeaver/issues/14694#issue-1064162326
1. https://github.com/dbeaver/dbeaver/issues/17857#issuecomment-1287051415
1. https://github.com/dbeaver/dbeaver/issues/19253#issue-1608940980
1. https://github.com/dbeaver/dbeaver/issues/19421#issue-1630991792
1. https://github.com/dbeaver/dbeaver/issues/20346#issue-1767294503
1. https://github.com/dbeaver/dbeaver/issues/20497#issue-1792045217
1. https://github.com/dbeaver/dbeaver/issues/20693#issue-1820764035
1. https://github.com/dbeaver/dbeaver/issues/20878#issuecomment-1719618325
1. https://github.com/dbeaver/dbeaver/issues/21002#issuecomment-1751120876

Also, this other proposal: *(with which I disagree, btw...)*

* https://github.com/dbeaver/dbeaver/issues/16187#issue-1204271562

**Comment by hhmmjjnn** [comment]
I had previously mentioned issues no. 9383 and 19387 by accident. The are not actually related to this. Sorry!

**Comment by E1izabeth** [comment]
Thank you for the idea of disabling preference in the described cases.

**Comment by arhayka** [comment]
Thanks again for the idea!
We discussed this issue with the team and decided to change the mechanism for saving the language.
We will create a special file for the language in DBeaverData and use it whenever needed.
In this case, language editing in Preferences will always be available.

**Comment by hhmmjjnn** [comment]
How is this possible? I mean... You can't change the program who is calling you so that it passes a different `-nl` So, what do you do? 🤨

**Comment by E1izabeth** [comment]
We stop specifying `-nl` by installer. But if it's already specified, we won't change it.

**Comment by hhmmjjnn** [comment]
Thank you for addressing that.

**Comment by KawtharAlakri** [comment]
Hi, I have cloned the repo and start developing using Eclipse (trying to fix another issue), but I am unable to change the language when I run it from eclipse, it ask to restart but nothing change, and I also changed in my eclipse-rcp-2023-12-R-win32-x86_64\eclipse\eclipse.ini 
![image](https://github.com/user-attachments/assets/3e688ea2-867c-4c26-8185-417ae7a87e8c)
 
 did this issue has been solved or not yet?
