### ISSUE TITLE
Foreign keys screen is super confusing

### ISSUE THREAD

**Issue by hhmmjjnn** [dbeaver/dbeaver#22679]
### Description

This is an UX bug report on the **Define foreign keys** dialog box, which is just so confusing. Also, on the **Define virtual foreign keys** dialog box, which is a tad worse:

![image](https://github.com/dbeaver/dbeaver/assets/133042358/1e5f205c-4108-4ddc-94e1-e9d192e7f53b)

It was only very recently that I figured out how I was supposed to operate it. That after many attempts, across many months. Also, I could not find any sort of manual for these screens.

![image](https://github.com/dbeaver/dbeaver/assets/133042358/8e2df938-89ee-4edb-9af1-eda33392a0f0)

For almost an year, I just stared at the **OK** button stubbornly grayed out. No matter what I did, it just refused to get enabled.
virtual foreign keys.

![image](https://github.com/dbeaver/dbeaver/assets/133042358/3a4e3ac5-6d47-4226-af45-d8d4a0429b78)

I even hypothesized on whether "virtual foreign keys" was some sort of experimental yet-to-be-implemented kind of feature.

![image](https://github.com/dbeaver/dbeaver/assets/133042358/569c517e-50e1-46e3-a41b-3462a0836c4e)

It was only after some frustation-driven random clicking aimlessly around, that this sphynx of a screen decided to share its secrets with my poor soul

![image](https://github.com/dbeaver/dbeaver/assets/133042358/65e1a367-fb47-4196-80fa-1bb7401a3352)

It was only then, that it dawned upon me that these cells...

![image](https://github.com/dbeaver/dbeaver/assets/133042358/bc0c57b6-2bb0-4747-a0cc-11165a13e554)

...secretly are combo boxes:

![image](https://github.com/dbeaver/dbeaver/assets/133042358/a82e046a-3276-4f47-9271-917671fb1e77)

After filling these cells, the  **OK** button finally enables:

![image](https://github.com/dbeaver/dbeaver/assets/133042358/f252981b-a8f2-4418-8c13-33ae1c7b5a43)

Yay!

But this is just **Sub-issue 1**. There's more...

**Sub-issue 2** The titles ...

![image](https://github.com/dbeaver/dbeaver/assets/133042358/c0db0dfa-f613-4a85-bb74-f5eb26308c86)

![image](https://github.com/dbeaver/dbeaver/assets/133042358/d4ea274a-74f5-4813-ab64-83466cdb2a88)

...are not consistent with other dialog boxes...

![image](https://github.com/dbeaver/dbeaver/assets/133042358/8b8b81fc-0c4b-4ba4-a500-a15cdd633a26)

![image](https://github.com/dbeaver/dbeaver/assets/133042358/180ec9f0-1d92-45ac-a79d-e4d7b3030730)

**Sub-issue 3** This **Choose ...** button...

![image](https://github.com/dbeaver/dbeaver/assets/133042358/a1b2c09d-944c-4845-98fd-850a7082d890)

...opens the **Select reference table catalog/schema** dialog box:

![image](https://github.com/dbeaver/dbeaver/assets/133042358/01e314de-90a7-40fe-8b5e-ca33e1eb6f11)

It's got this *Show connected databases only* checkbox... 

![image](https://github.com/dbeaver/dbeaver/assets/133042358/ebea85f6-bb1f-4918-9a18-e81a39687a14)

...which is redundant with this little guy, up here...

![image](https://github.com/dbeaver/dbeaver/assets/133042358/ccb17ad9-4e6c-4bd8-bd84-48f240122caa)

**Sub-issue 4** Speaking of which... There you can find these **Filter table containers** and **Filter tables, procedures, etc.** options...

![image](https://github.com/dbeaver/dbeaver/assets/133042358/d448bd5e-8e58-4904-acb1-c96b4b4900ab)

Their names are complete lies.

* "Filter table containers" actually filters schemes, not table containers. *(Remember, 'tables containers' = 'schemes' + 'packages')*
* "Filter tables, procedures, etc." actually filters packages.

I wonder whats even the point of talking about "tables" and "procedures" in a screen that is not supposed to show either.

There is another screen in DBeaver with a similar issue:

* https://github.com/dbeaver/dbeaver/issues/22675#issue-2113564276

**Sub-issue 5** Back to the **Define foreign keys** dialog box. There's this *Reference table:* list...

![image](https://github.com/dbeaver/dbeaver/assets/133042358/2284febf-41c9-4f51-a512-047c0781b10d)

This list definitely deserves a filtering feature.

**Sub-issue 6** The tables in this list don't have any context menu. There should be at least be a "Copy" option.

**Sub-issue 7** When you have that list focused and type a letter on the keyboard, it advances to the first item whose name starts with that letter.

If you hit more keys, you would expect that it would keep refining the search by the second, third, fouth... letters. But no... It seeks by the first letter, once again.

This is super frustating.

Sub-issues 5 and 7 combined make creating virtual keys withing a BBoM scheme a huge pain. You have to pick the reference table you are looking for very diligently, which is annoying.

**Sub-issue 8** Finally, there's this **Unique Key:** combo box...

![image](https://github.com/dbeaver/dbeaver/assets/133042358/aa684254-6466-4e68-b113-40b34d998d19)

...which does make sense if you *already know* how the dialog operates, but is rather daunting the first time you see it.

If you are stuck with the disabled **OK** button caused by the **Columns:** table not beign filled, as I previously was, you may think there's something wrong with this "unique key" thing. Even when it's just fine.

That's some pure cognitive overload you just would not want.

To be honest, I can't devise a better place for it to be. Perhaps, transform the *Reference table:* list into a tree...?

Maybe? I dunno `¯\_(ツ)_/¯`

### DBeaver Version

DBeaver Community Edition 23.3.0.202312031432

### Operating System

Windows 11 (21H2/10.0.22000.2652)

### Database and driver

`oracle.jdbc.OracleDriver`

### Steps to reproduce

*(...)*

### Additional context

*(...)*

**Comment by E1izabeth** [comment]
Thank you for sharing your UI complaints. We value it and try improving.

**Comment by arhayka** [comment]
We discussed this with the team and decided to do the following:
1/ User doesn’t understand what to do because there is no columns => Add hint to the tables ‘Click here to choose source column’
2/ Delete duplicate dialog names after slash **|** 
3/ Write everywhere ‘Show connected databases only’ (near the checkbox and in the Context menu)
4/ Filter table container — rename to “Filter catalogs and schemes”
5/ Add a filter to the Reference tables 
6/ Add a context menu for the table
