### ISSUE TITLE
'Loading...' spinner won't go away after timeout

### ISSUE THREAD

**Issue by hhmmjjnn** [dbeaver/dbeaver#22677]
### Description

When a connection fails to open, the "Loading ..." spinner disappears...

![image](https://github.com/dbeaver/dbeaver/assets/133042358/19a10fd3-eba9-4d94-b0db-868e9a71e848)

...except if the reason for failure was timeout, in which case it stays there, forever...

![image](https://github.com/dbeaver/dbeaver/assets/133042358/14af61cc-fab7-4942-9007-e385a99a904f)

Isn't that odd?

### DBeaver Version

DBeaver Community Edition 23.3.0.202312031432

### Operating System

Windows 11 (21H2/10.0.22000.2652)

### Database and driver

`oracle.jdbc.OracleDriver`

### Steps to reproduce

*(...)*

### Additional context

*(...)*

**Comment by E1izabeth** [comment]
Thank you for bug report. We need to reproduce and fix it.

**Comment by E1izabeth** [comment]
Does it still reproducible in the latest DBeaver version?

**Comment by E1izabeth** [comment]
Can't reproduce anymore

**Comment by hhmmjjnn** [comment]
Dear @E1izabeth 

Tested right now with **23.3.0.202312031432** and it happened again. Then, updated to **24.3.2.202501051917** and it happens no more.

Thanks!
