### ISSUE TITLE
Add ability to batch `INSERT` statements into a single `INSERT` for selected batch of data

### ISSUE THREAD

**Issue by PauliusLozys** [dbeaver/dbeaver#22697]
**Is your feature request related to a problem? Please describe.**
Hello, sometimes I need to select a certain chunk of data and then insert it via SQL console. 
Right now, when a chunk of data is selected and I do `Generate SQL -> INSERT` it generates individual `INSERT` statements.
![image](https://github.com/dbeaver/dbeaver/assets/42966213/718a2fd1-0227-4e64-8920-9fe086e5252c)

And when it is copied to SQL console, I have to manually run them one by one. This can get annoying with large chunks of data.

**Describe the solution you'd like**
I would like to have a checkbox in the generation dialog that would batch all `INSERT` statements into a single `INSERT` like this:
```
INSERT INTO timers (tstamp, dates) VALUES
('2024-02-03 15:38:36.000', '2024-02-03 15:38:36.000'),
('2024-02-02 20:10:53.000', '2024-02-02 20:10:53.000'),
('2024-02-03 14:47:11.000', '2024-02-03 14:47:11.000'),
('2024-02-03 07:22:17.000', '2024-02-03 07:22:17.000'),
('2024-02-03 15:38:36.000', '2024-02-03 15:38:36.000'),
('2024-02-02 20:10:53.000', '2024-02-02 20:10:53.000'),
('2024-02-03 10:19:06.000', '2024-02-03 10:19:06.000'),
('2024-02-03 03:56:32.000', '2024-02-03 03:56:32.000'),
('2024-02-03 05:53:57.000', '2024-02-03 05:53:57.000'),
('2024-02-02 23:52:20.000', '2024-02-02 23:52:20.000'),
('2024-02-03 15:38:36.000', '2024-02-03 15:38:36.000'),
('2024-02-02 20:10:53.000', '2024-02-02 20:10:53.000'),
('2024-02-03 14:47:11.000', '2024-02-03 14:47:11.000'),
('2024-02-03 07:22:17.000', '2024-02-03 07:22:17.000'),
('2024-02-03 15:38:36.000', '2024-02-03 15:38:36.000');
```

**Describe alternatives you've considered**

**Additional context**

**Comment by LonwoLonwo** [comment]
Hello @PauliusLozys 

You can configure this as the "Copy as SQL" command.

First, you need to change the command settings:

![2024-02-05 11_38_34-DBeaver Ultimate 23 3 4 - film](https://github.com/dbeaver/dbeaver/assets/45152336/ef78544d-f320-486e-8b8e-4ddc6db7efe9)

And change the upsert keyword to "Insert all" (you can configure a number of rows in a batch as well):

![2024-02-05 11_38_52-DBeaver Ultimate 23 3 4 - film](https://github.com/dbeaver/dbeaver/assets/45152336/6f4be0d6-7574-416c-9bd3-e1c8d645e0ec)

And then you can copy highlighted data as SQL:

![2024-02-05 11_39_11-](https://github.com/dbeaver/dbeaver/assets/45152336/89324a6b-aa44-4031-8c7b-bc776c5b4276)

**Comment by PauliusLozys** [comment]
Hi @LonwoLonwo, thanks for your response.
It seems that the generated syntax is limited to Oracle databases. I'm using `MariaDB` and it does not seem to support `INSERT ALL ... SELECT 1 FROM DUAL;` syntax. I think it would be better if the solution was database-independent.

**Comment by LonwoLonwo** [comment]
Oh, yes, you didn't specify the database.

So, you can leave default settings in the command configuration and do Copy as SQL. It is multi-value by default (for 10 rows).

**Comment by PauliusLozys** [comment]
Sorry, for not specifying the database earlier, thank you, seems just what I needed 👍
