### ISSUE TITLE
Blank line as statement delimiter issue

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#2270]
Hi,

My version of DBeaver is 4.2.2
In my "Preferences", I have configured the SQL editor to have the blank line as statement delimiter.
This works fine, except when the last line of the first statement finishes with a comment.

Exemple:
```
SELECT 1

SELECT 2
```
This works fine

But:
```
SELECT 1 -- This is my comment

SELECT 2
```
The blank line is no more considered as a statement delimiter and I get a syntax error.

Regards,
Cedric

**Comment by serge-rider** [comment]
Hm, I can't reproduce that.
Note: in script mode (<kbd>alt+x</kbd>) blank line never works as delimiter, only in single query mode.
BTW do you use the most recent version? There were some issues with trailing comments in some version.

**Comment by ced75** [comment]
Thanks for your answer.

My DBeaver version is the most recent version (4.2.2), with Linux Mint as OS.
I'm using it with PostgreSQL 9.6, where I get the issue. But if I try the same with SQL Server, it works.
So, it seems related to PostgreSQL.

**Comment by serge-rider** [comment]
This is quite odd. As scripts are parsed on client side and it doesn't depend on database type.
And I can't reproduce that (if I copy-paste you example abode in DBeaver for PG9.6 - it works like a charm).
Please check your script doesn't contain any special characters (which may look like spaces) in some special encoding.

**Comment by ced75** [comment]
This is probably because I'm not clear enough in the steps to reproduce it.
OK, here is what I do:
- create a new script
- write "SELECT 1", and execute the query with cursor at the beginning of the line => OK
- add a blank line
- write "SELECT 2", and execute the query with cursor at the beginnig of the line => OK
- go back to the end of the first line, add a space and a comment like " -- this is a comment", then execute the first query with cursor at the beginning of the line (without selecting any word) => error message.

I hope it could help to reproduce.

**Comment by serge-rider** [comment]
I'm quite sure this was fixed a time ago. Please reopen if this problem persists.
