### ISSUE TITLE
DBeaver CE 23.3.4-x86_64 won't work

### ISSUE THREAD

**Issue by SigmundTveit** [dbeaver/dbeaver#22714]
### Description

Today's new Monday version of DBeaver CE 23.3.4-x86_64 refuses to work - apparently for security reasons, 100 % reproducible. A dialog box shows up (translated): Cannot access the specified device, path, or file. Maybe you don't have access rights to the object. (Original Norwegian: Får ikke tilgang til den angitte enheten, banen eller filen. Kanskje du ikke har tilgangsrettighet til objektet.) Please note, I don't have administrator rights on my machine.

Workaround: I found and tried an older installer CE 23.0.4-x86_64 from May 2023. It installs a DBeaver that works.

### DBeaver Version

Community Edition 23.3.4

### Operating System

Windows 11

### Database and driver

PostgreSQL

### Steps to reproduce

Install and try to run DBeaver.

### Additional context

Not administrator rights.

**Comment by Solomon-0xGuardian** [comment]
I am having a very similar issue. Unable to access the file. Then cancelled the install. Now it will not open with the following error.
![DError](https://github.com/dbeaver/dbeaver/assets/53942567/82585fd2-3d34-4b11-ae43-886110f928cf)

**Comment by Solomon-0xGuardian** [comment]
Reverted to 23.3.3 x64 installer for fix: https://dbeaver.io/files/23.3.3/

**Comment by AdrianoBortoloto** [comment]
Very similar issue here, for security reasons version 23.3.4 does not open showing a Windows Defender SmartScreen below:

![image](https://github.com/dbeaver/dbeaver/assets/12927584/1b1b6de1-ed3e-473a-91a2-ec6203fa4b7f)

Translated: "Windows protected the computer. Microsoft Defender SmartScreen prevented an unrecognized app from launching. Running this application may put your computer at risk."

I downloaded the Windows (zip) version (23.3.4) and extracted the folder at the same local of previous version (23.3.3). The previous version is working fine, the newer version shows that Windows popup.

**Comment by Solomon-0xGuardian** [comment]
Interesting. I wonder if it needs the installer to be run in administrator mode to access locations that are usually off limits to installers.

**Comment by treysis** [comment]
@Foudree I don't think so. I always installed DBeaver without admin privileges (I wouldn't even be able to, as I don't have the admin credentials for my work computer).
The original message and the SmartScreen window suggest that the exe-file just wasn't known to Windows, which can happen if it's very new or has never been reported by the devs to Microsoft.

Maybe also the DBeaver dev team changed something in the installer, because it appeared on the Winget repository yesterday, and when I tried to install it, there was a Sha256 mismatch of the installer file. So they probably fixed the installer and re-released it, but without updating the hash.

**Anyway, the current installer (and zip) work just fine on my computer where I don't have admin rights.**

**Comment by LmG7119** [comment]
We don't use installer at all. We just unzip and over-write in the same folder. I'm having the same issues. I even tried to unzip into a new folder and still getting the same error message.

**Comment by AdrianoBortoloto** [comment]
@LmG7119, just to confirm, are you getting the same Windows defender message?

**Comment by LmG7119** [comment]
> @LmG7119, just to confirm, are you getting the same Windows defender message?

No. I get what AFoudree gets on my locked-down work laptop. I reverted back to the previous version and everything is working fine.

**Comment by E1izabeth** [comment]
How are you installing DBeaver? From Microsoft Store or by running exe installer downloaded from the web site?

**Comment by SigmundTveit** [comment]
> How are you installing DBeaver? From Microsoft Store or by running exe installer downloaded from the web site?

23.3.4 (didn't work): Responded to Monday-ly update. 23.3.3 (works): Zip, direct copy.

**Comment by E1izabeth** [comment]
I can reproduce the issue with Windows Defender, but not the initial issue with java or access rights.

**Comment by E1izabeth** [comment]
@AFoudree admin rights are not needed, unless you chose option to install `For anyone who uses this computer`
![image](https://github.com/dbeaver/dbeaver/assets/28875055/adb3d912-57a1-492a-8b69-71c42d4a4bfc)

**Comment by E1izabeth** [comment]
@AdrianoBortoloto 
To run DBeaver if Windows Defender prevents it, you can click on `More information` and then press `Run anyway` button.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/eeab66e9-2621-4832-9aaa-ab7b25990581)

**Comment by E1izabeth** [comment]
@SigmundTveit do you use any anti-virus software other than Microsoft Defender? Is there any chance that something might be put to the quarantine? Could you check?

**Comment by serge-rider** [comment]
It is a bug in dbeaver packaging. Exe file in archive is not signed.
Will be fixed in 23.3.5

**Comment by SigmundTveit** [comment]
> @SigmundTveit do you use any anti-virus software other than Microsoft Defender? Is there any chance that something might be put to the quarantine? Could you check?

Only Defender. Just "for me"

**Comment by AdrianoBortoloto** [comment]
@E1izabeth The "Run anyway" button doesn't show here, only the "Don't run" one. It's a work laptop, but Windows Defender shows the warning only for 23.3.4 version.

**Comment by E1izabeth** [comment]
@AdrianoBortoloto you need to press `More info` first
![image](https://github.com/dbeaver/dbeaver/assets/28875055/62698fcc-c7e4-457c-88c1-5ed7ba7c4397)

**Comment by AdrianoBortoloto** [comment]
@E1izabeth sorry, I forgot to mention, I clicked on "More info" but the option didn't appear. Maybe some sort of company security rule...

![image](https://github.com/dbeaver/dbeaver/assets/12927584/600f45db-56bf-41b1-a1a0-136751c3ee8c)

**Comment by E1izabeth** [comment]
@AdrianoBortoloto hmm.. okay, thanks. Hope we will fix it soon

**Comment by E1izabeth** [comment]
Please try our new version 23.3.5. Has it been fixed?

**Comment by SigmundTveit** [comment]
> Please try our new version 23.3.5. Has it been fixed?

Yes, 23.3.5 works OK. Thank you!

**Comment by E1izabeth** [comment]
Thank you. I'm closing the issue then
