### ISSUE TITLE
Windows version (32/64-bit) of DBeaver.exe does not contain version information

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2271]
DBeaver - **Version 4.2.2 CE**
Operating System: **Windows 7 / Windows 8.1**

If would be great it the _DBeaver.exe_ fil could get added information information.

This since I want to repack the Dbeaver ID and resent what version of DBeaver just was installed.

**Comment by serge-rider** [comment]
Eclipse build doesn't support this out of the box. Potentially I can patch dbeaver.exe during release packaging but there is another problem: 
all DBeaver releases are built on Linux (Ubuntu) and there are no utilities which can manipulate with Windows exe file resources on Linux. At least I didn't find any (we need something like veripatch, rcedit, resourcelib, etc - there is a bunch of similar soft on Windows).

**Comment by pdanie** [comment]
I noticed that the **.eclipseproduct** file contain a **"version=4.3.2"** information.

Will this file continue to exist and have a "version=..." property in the future too. In that case I can use that instead of version information on the exe-file.

**Comment by tati-kru** [comment]
It looks like this issue was solved. If you think that it is actual just let us know.
