### ISSUE TITLE
Generate script by specific column (UPDATE)

### ISSUE THREAD

**Issue by EmirLogas** [dbeaver/dbeaver#22726]
**Is your feature request related to a problem? Please describe.**
I want it to use only one value when creating the update script. It automatically takes a guid as a condition, but I want to get another column.

**Describe the solution you'd like**
While generating the update script. Creating by selecting which columns will be used in the Set section and which columns will be used in the Where section.

**Additional context**

**Comment by LonwoLonwo** [comment]
Hello @EmirLogas 

> Creating by selecting which columns will be used in the Set section and which columns will be used in the Where section.

You can mark this column for the Where condition as a virtual key like this:

![2024-02-06 15_38_19-DBeaver Ultimate 23 3 4 - _language](https://github.com/dbeaver/dbeaver/assets/45152336/c61f34f4-3cbe-43db-a801-81eaacf7aa72)

**Comment by EmirLogas** [comment]
Hello @LonwoLonwo 
Before creating the UPDATE script, as you said, I specified the column I want to be in the where condition as a virtual unique key, but when I created the update script, I saw that it continued to create with guid.

**Comment by LonwoLonwo** [comment]
You can create this script for changed columns:

![2024-02-06 15_52_39-DBeaver Ultimate 23 3 4 - syscolumns](https://github.com/dbeaver/dbeaver/assets/45152336/41f3f8ce-c687-48c6-8003-2e7e87cd5943)

Also, the generated script for deletion uses a virtual key value.

![2024-02-06 15_55_21-Generated SQL (MYSYBASE)](https://github.com/dbeaver/dbeaver/assets/45152336/c98de3f8-1530-4fad-acd5-cc05c8a3537a)

So, we are talking only about a script for the update. 
Ok. Thanks for the report.

**Comment by EmirLogas** [comment]
Do you want me to explain it through a short screen share? I guess I didn't explain the problem well.
https://talk.brave.com/MYj1gjJPglEHx_MfettDc6NcN2LbDk-WnIHV54k6vyo

**Comment by EmirLogas** [comment]
That's not what I said. I will get back to you when available.

**Comment by EmirLogas** [comment]
Consider a table with 7 columns. I manually updated only 1 column of many records from these columns. In order to move these changes to another database with a script, when I select the data I update and say generate update script, it creates a script by putting all the columns in the set section, whereas I only want the column I changed to be in the set section. Even if I set it as "virtual unique key" in the where section, it does not create the where section with the virtual unique key I selected.

**Comment by LonwoLonwo** [comment]
> Even if I set it as a "virtual unique key" in the where section, it does not create the where section with the virtual unique key I selected.

As I said, we have only the DELETE statement generator for now, which can check virtual keys.
But you can always specify the virtual key, manually update one column, and check the script for potential data saving, like this:

![2024-02-06 15_52_39-DBeaver Ultimate 23 3 4 - syscolumns](https://github.com/dbeaver/dbeaver/assets/45152336/41f3f8ce-c687-48c6-8003-2e7e87cd5943)
