### ISSUE TITLE
Close idle connection setting not saved when restarting dBeaver

### ISSUE THREAD

**Issue by alesc2000** [dbeaver/dbeaver#22721]
### Description

Recently I noticed that DBs get disconnected after a while, so I found the "Close idle connection after (seconds)" setting in the Connection Types. I uncheck it, and apply. After dBeaver restart it is checked again...
I notice the connection is closed even if I have an open dashboard, so the connection shouldn't be idle...
![image](https://github.com/dbeaver/dbeaver/assets/19900533/9f991f8a-1fa7-45db-a336-5066003f4af3)

### DBeaver Version

23.3.4.202402041841

### Operating System

Linux Mint 20.3

### Database and driver

Postgres 14

**Comment by E1izabeth** [comment]
Thank you for bug report. I reproduced the issue.

**Comment by serge-rider** [comment]
Fixed.
We also added checkbox to disable idle connection close for individual connection:
![image](https://github.com/dbeaver/dbeaver/assets/6398845/1a0dd417-4f10-4da9-94a6-1ba58003ecc4)
