### ISSUE TITLE
"End transaction" dialog on each query

### ISSUE THREAD

**Issue by antonio-petricca** [dbeaver/dbeaver#22728]
### Description

Each time I run a query (selects too), after about a second, I get the following annoying dialog:

![image](https://github.com/dbeaver/dbeaver/assets/6660386/0d7adbc8-7107-42f8-b729-fdae9cb629a1)

### DBeaver Version

23.3.4.202402041841 (SNAP version)

### Operating System

Ubuntu 22.04.03

### Database and driver

Not relevant.

### Steps to reproduce

1. Connect to any DB.
2. Open a SQL script window.
3. Execute a SELECT query.
4. Wait for a second...

**Comment by RobiABC** [comment]
See this https://github.com/dbeaver/dbeaver/issues/22709

**Comment by antonio-petricca** [comment]
Thank you, it solved my issue!
