### ISSUE TITLE
"Data Transfer" does not add the "On conflict expression" at the end of the statements

### ISSUE THREAD

**Issue by ggregoire** [dbeaver/dbeaver#22733]
### Description

I'm trying to export a query from Postgres with the "Data Transfer" window and with setting the "On conflict expression" to "ON CONFLICT DO NOTHING" but the generated INSERT statements are missing the on conflict expression.

<img width="1246" alt="Screenshot 2024-02-06 at 12 33 22" src="https://github.com/dbeaver/dbeaver/assets/591804/3e6b4670-b812-4d40-a287-d7edc7e7508f">

Result:

```sql
INSERT INTO test (id, name) VALUES
  (1, 'test'),
  (2, 'test'),
  (3, 'test');
```

Expected:

```sql
INSERT INTO test (id, name) VALUES
  (1, 'test'),
  (2, 'test'),
  (3, 'test') ON CONFLICT DO NOTHING;
```

### DBeaver Version

Community Edition 23.3.4 (wasn't working on 23.2.5 either, I upgraded to test on the latest version)

### Operating System

macOS Sonoma 14.1.1

### Database and driver

Postgres 11, probably latest JDBC driver

### Steps to reproduce

1. right click on a query in the SQL Editor
2. Execute
3. Export from query
4. set the "On conflict expression"
5. Proceed

**Comment by LonwoLonwo** [comment]
Hello @ggregoire 

Thanks for the report. 
It will work like this (you need to change the upsert keyword) :

![2024-02-07 11_08_26-Configure 'Copy as' commands ](https://github.com/dbeaver/dbeaver/assets/45152336/d0f4bd10-c4ee-4fdf-9e3f-68e46ac6e571)

But I agree, that it should work and in your case also.

**Comment by ggregoire** [comment]
@LonwoLonwo thank you
