### ISSUE TITLE
Add support to "zero" the zoom factor both when text edit and when viewing diagram

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2274]
DBeaver - **Version 4.2.2 CE**
Operating System: **Windows 7 / Windows 8.1**

Today you can zoom in and out using keyboard shortcuts, but there is no way to get back to 100% (ie no plus/minus zoom).

Compare keyboard shortcut **Ctrl+Numeric_Multiply** in _Microsoft Internet Explorer_. It use **Ctrl+Numpad_Add** to zoom in, **Ctrl+Numpad_Subtract** to zoom out, and **Ctrl+Numpad_Multiply** to zero the zoom factor back to 100%.

**Comment by serge-rider** [comment]
For some reasons (mostly philosophical) this feature is not included in Eclipse editors framework. 
Check this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=482913

I still hope that it'll be included in the next Eclipse version..

**Comment by tati-kru** [comment]
This is not a DBeaver issue. It will be closed.
