### ISSUE TITLE
Bug: Unexpected closure when fetching large amount of records from SQL server

### ISSUE THREAD

**Issue by acalantoni** [dbeaver/dbeaver#22752]
### Description

Hello,

I have encountered an issue with version 23.3.4.202402060628 of DBeaver Community Edition. When attempting to fetch a table containing a large number of records (around 120,148 records), the program unexpectedly closes. The issue specifically occurs during the fetching of rows, around 11,000 records, and happens without any error message or warning.

### DBeaver Version

Community Edition version 23.3.4.202402060628

### Operating System

Windows 11 Pro

### Database and driver

MSSQL Microsoft JDBC Driver for SQL Server 

### Steps to reproduce

- Connect to an SQL server using DBeaver Community Edition version 23.3.4.202402060628.
- Open a table containing a large number of records (in my case, around 120,148 records).
- Attempt to fetch the rows of the table.
- The program unexpectedly closes during the fetching, around 11,000 records.

### Additional context

Hello,

I have encountered an issue with version 23.3.4.202402060628 of DBeaver Community Edition. When attempting to fetch a table containing a large number of records (around 120,148 records), the program unexpectedly closes. The issue specifically occurs during the fetching of rows, around 11,000 records, and happens without any error message or warning.

Steps to reproduce the issue:

- Connect to an SQL server using DBeaver Community Edition version 23.3.4.202402060628.
- Open a table containing a large number of records (in my case, around 120,148 records).
- Attempt to fetch the rows of the table.
- The program unexpectedly closes during the fetching, around 11,000 records.
- Expected behavior:
- I expected DBeaver Community Edition to be able to handle the fetching of a large number of records from an SQL server without unexpectedly closing.

No error messages or warnings were displayed before the unexpected closure of DBeaver.

Thank you for your attention and assistance in resolving this issue.

**Comment by LonwoLonwo** [comment]
Hello @acalantoni 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by acalantoni** [comment]
Please provide the screenshot of the error you encountered along with the log file, and I'll assist you in resolving the issue.
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/14207501/dbeaver-debug.log)
[dbeaver-debug-1707374146860.log](https://github.com/dbeaver/dbeaver/files/14207502/dbeaver-debug-1707374146860.log)
[dbeaver-debug-1707374237517.log](https://github.com/dbeaver/dbeaver/files/14207503/dbeaver-debug-1707374237517.log)
![2024-02-08 11_03_25-DBeaver 23 3 4 - DOC_R](https://github.com/dbeaver/dbeaver/assets/42345873/3dfad1d0-29a7-46fc-a5df-75adb0f55bc5)

[dbeaver-debug-1707386527606.log](https://github.com/dbeaver/dbeaver/files/14207504/dbeaver-debug-1707386527606.log)

**Comment by ShadelessFox** [comment]
Hello @acalantoni,

I don't see anything suspicious in your logs. How did DBeaver crash, exactly? Did its window suddenly close? In such a case, please look for another type of log files: https://github.com/dbeaver/dbeaver/wiki/Log-files#java-fatal-logs

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
