### ISSUE TITLE
Window Title missing from authentication prompts in 23.3.4, so Password Manager cannot identify the Window for Auto Type

### ISSUE THREAD

**Issue by tbigby-kristin** [dbeaver/dbeaver#22766]
### Description

Since upgrading to 23.3.4, the popup authentication prompt when connecting to a database no longer has a Window Title. This means my Password Manager cannot Auto-Type the password for the database, as it uses the Window Title to determine which password should be chosen to be auto-typed for that database.

The same occurs for the 'SSH Tunnel' authentication also, this popup's Window Title is also missing and again the Password Manager cannot select the right password to Auto-Type.

I narrowed this down to `plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/runtime/ui/DBPPlatformUI.java`, lines 124 and 146.

In a recent commit, these methods have been added to add a description to the user credentials prompt. On these lines, the first parameter refers to the Window Title, and the second parameter to the new description label on the popup window. The Window Title (parameter name `prompt`) is being set to `null`, and the inputted `prompt` is passed to the `description` parameter.

I tried replacing the `null` parameters with the variable `prompt` (so that `prompt` is used twice in the call), and can confirm that the Window Title returned and the Password Manager can once again Auto-Type the password.

Screenshot of DBeaver 23.3.4 version (missing Window Title):

![image](https://github.com/dbeaver/dbeaver/assets/16282833/179294e1-fa2c-40df-90fe-22dc01265f02)

Screenshot of patched version (restoring Window Title):

![image](https://github.com/dbeaver/dbeaver/assets/16282833/03823393-69ce-49fb-8c33-ca902f9b06a0)

Here is a patch file, but it may be easier to just overwrite both `null`s with `prompt`.

[fix-window-title-on-authentication-popups.patch](https://github.com/dbeaver/dbeaver/files/14217359/fix-window-title-on-authentication-popups.patch)

### DBeaver Version

Community 23.3.4

### Operating System

Windows 10

### Database and driver

Independent of database and driver, but noted occurring when connecting using drivers mysql8, MariaDB, Microsoft SQL Server.

### Steps to reproduce

1. Create a database connection; enter the username, but do not choose to Save the password

Screenshot of my `localhost` configuration:
![image](https://github.com/dbeaver/dbeaver/assets/16282833/10dbe81b-d95e-43a9-bbd7-cb79b3b2b0b2)

2. If connected, disconnect from the database
3. Right-click on the database connection - click Connect

Observe that there is no Window Title on the authentication popup box

### Additional context

As noted in 'Steps to reproduce', my database connection does not have the password saved in DBeaver.

My database passwords are stored in my Password Manager, for which I use KeePassXC on Windows.

I can't take a screenshot of KeePassXC for whatever reason, but the KeePassXC entry has under Auto-Type a Window Association for the 'Window title' being `'localhost' Authentication`, that is what chooses the right KeePassXC entry to Auto-Type for that database connection.

My KeePassXC Auto-Type global keyboard shortcut is Alt-Shift-R so that it doesn't conflict with other shortcuts. That means that I can press Alt-Shift-R at any time, and if a DBeaver authentication popup is open (including for SSH Tunnels) KeePassXC will Auto-Type the password quickly and press Enter. Such a time-saver compared to opening KeePassXC and finding the right password.

I noticed issue #22748 . I use KeePassXC whereas they appear to be using KeePass, both use the same database but have different user interfaces. However, it is possible that the lack of a Window Title might be confusing KeePass into typing the password into the wrong place? I could not replicate that issue in my setup either pre-patch or post-patch.

**Comment by tbigby-kristin** [comment]
Just to respond to the questions asked in the other Password Manager issue:

> What version of DBeaver did you upgrade from? Was the described issue occurring before?

Exactly the same answer - I use Chocolatey to regularly upgrade, so it would have previously been 23.3.3. I would also have noticed this immediately in the previous version, as these steps are all I use to ever connect to a database, which I would usually do something weekly.

> What is the configuration of your password manager that automatically makes it appear when typing passwords?

In my case, KeePassXC I have the 'Global Auto-Type shortcut' set to Alt-Shift-R to avoid conflicts. As soon as the DBeaver prompt shows up, I press Alt-Shift-R, and then magically the password is typed out and an Enter pressed to connect to the database. Several databases also have an SSH Tunnel, at which I again press Alt-Shift-R to type that password from KeePassXC too.

**Comment by LonwoLonwo** [comment]
Hello @tbigby-kristin 

Thanks for the report, detailed explanation, patch and link to another issue. 

I can reproduce it.

![2024-02-09 11_19_47-DBeaver Ultimate 23 3 4 - dbo](https://github.com/dbeaver/dbeaver/assets/45152336/aeb0b8f3-6e25-43b6-9def-ba962db7c18a)

**Comment by ShadelessFox** [comment]
Thanks for the bug report and the proposed soluton

**Comment by tbigby-kristin** [comment]
Many thanks team for accepting and merging this quickly! Much appreciated!
