### ISSUE TITLE
DBeaver 23.3.4 not showing Redshift Spectrum tables

### ISSUE THREAD

**Issue by alejandrofm** [dbeaver/dbeaver#22763]
### Description

I just found out that DBeaver 23.3.4, on the Spectrum schemas tables are not listed.

### DBeaver Version

23.3.4 community

### Operating System

macOS 14

### Database and driver

com.amazon.redshift.jdbc42.Driver

**Comment by LonwoLonwo** [comment]
Hello @alejandrofm 

Could you please check your connection settings? Does the tab contain the Redshift logo in the right corner or the PostgreSQL logo?

![2024-02-09 11_28_56-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/0f274973-5e2e-48b3-a341-c7ff7f9192a9)

And how exactly did you create your connection?

**Comment by alejandrofm** [comment]
Yes, logo it's there. used that connector.
schemas are showing correctly, but empty
![image](https://github.com/dbeaver/dbeaver/assets/19591174/ae8aa080-5c3f-4ea9-bcd6-9c2c5912769a)

**Comment by LonwoLonwo** [comment]
1. Did you refresh your schema after table creation? Did you try to reconnect?
2. https://github.com/dbeaver/dbeaver/wiki/Query-Manager Check your Query Manager with enabled filters. You can find the "SELECT * FROM svv_external_tables WHERE schemaname=<your_schema_name>" query and check - how many rows are returned. Or execute it in your SQL Editor and tell me the result.

**Comment by alejandrofm** [comment]
Thanks, apparently is an issue on my side

**Comment by LonwoLonwo** [comment]
Okey, thanks for the update!
