### ISSUE TITLE
Hidden text on collapse

### ISSUE THREAD

**Issue by engineerchange** [dbeaver/dbeaver#22774]
### Description

When the "General" folder is collapsed, it is shortened to "Genera". When it is expanded, it becomes "General" again. Also, "Connections" and parts of other areas "postgres 2" are being cutoff at the end of the string.

### DBeaver Version

Community Edition 23.3.4

### Operating System

macOS Monterey 12.7.3

### Database and driver

Postgres, PostgresSQL JDBC Driver

### Steps to reproduce

On loading DBeaver, "General" is cut off, despite ample whitespace:
![image](https://github.com/dbeaver/dbeaver/assets/3580210/597fe10b-3c7d-4fe0-a353-1484169c004c)

On uncollapsing, "General" is expanded, but the "s" in "Connections" and the "2" in "postgres 2" is trimmed.
![image](https://github.com/dbeaver/dbeaver/assets/3580210/ff97d081-90a8-4744-8388-8b3789a2c2e1)

**Comment by LonwoLonwo** [comment]
Hello @engineerchange 

Thanks for the bug report.

I'm closing it as a duplicate of https://github.com/dbeaver/dbeaver/issues/22412
