### ISSUE TITLE
No editor descriptor for id org.eclipse.ui.internal.emptyEditorTab

### ISSUE THREAD

**Issue by ianlewisau** [dbeaver/dbeaver#22782]
### Description

Running 23.2.4. Starting DBeaver under Windows results in error "No editor descriptor for id org.eclipse.ui.internal.emptyEditorTab", and application terminates. This is covered in the wiki at https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings. I have tried using both suggested methods - the first one, deletion of %APPDATA%\DBeaverData\workspace6\.metadata\.plugins\org.eclipse.e4.workbench\workbench.xmi removes the immediate exit, but then the splash screen just remains and the application eventually must be terminated. The second approach of removing the whole .plugins directory results in a different error: 'AutoRegisterSchemeHandlersJob' has encountered a problem. An internal error occurred during: "AutoRegisterSchemeHandlersJob".  This also results in the application termination. I've tried dbeaver-cli.exe -clean and get the same error.
As a final attempt, I tried to delete the whole DBeaverData directory, but that also results in the AutoRegiesterSchemeHandersJob error above.

Is there anything else I can try?

### DBeaver Version

Community Edition 23.2.4

### Operating System

Windows 10 Enterprise 22H2

### Steps to reproduce

I just have to attempt to launch DBeaver.

**Comment by E1izabeth** [comment]
Please provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by ianlewisau** [comment]
Sorry, I should have thought to do that.

[.log](https://github.com/dbeaver/dbeaver/files/14236579/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/14236581/dbeaver-debug.log)

**Comment by E1izabeth** [comment]
Thank you

**Comment by ShadelessFox** [comment]
Hello @ianlewisau,

What installation method did you use? Did you install DBeaver using an executable or use the portable version?

**Comment by ianlewisau** [comment]
It was the executable version.

**Comment by LonwoLonwo** [comment]
Hello @ianlewisau 
Could you please check the latest DBeaver version? https://dbeaver.io/download/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
