### ISSUE TITLE
h2 DB file gets reset at startup

### ISSUE THREAD

**Issue by shnok** [dbeaver/dbeaver#22783]
### Description

I'm currently using DBeaver to edit my h2 DB. I have to keep a save of the DB file because at each DBeaver startup, the DB gets completely reset. It seems like it's overwriting the existing file.

### DBeaver Version

23.3.0.202312031432

### Operating System

Windows

### Database and driver

H2 Embedded org.h2.Driver

### Steps to reproduce

1. Start SpringBoot
2. Stop SpringBoot
3. Open DBeaver
4. H2 DB is wiped

**Comment by E1izabeth** [comment]
Please provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by shnok** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/14274853/dbeaver-debug.log)

**Comment by shnok** [comment]
ok, I found one "solution" is that my SpringBoot was renaming my tables in lowercase but DBeaver should not delete my file content in any case

**Comment by E1izabeth** [comment]
Do you set `spring.datasource.hbm2ddl.auto=create-drop` or `spring.jpa.hibernate.ddl-auto=create-drop` in application properties file?

**Comment by shnok** [comment]
no, I can start/stop my app multiple times without issue, It only gets dropped when starting DBeaver

**Comment by E1izabeth** [comment]
Ok, thank you

**Comment by LonwoLonwo** [comment]
Hello @shnok 

DBeaver doesn't drop any metadata.
Could you please provide your application.properties info? You can remove sensitive data from it.

**Comment by shnok** [comment]
More details:

1. When editing the DB with DBeaver, the file size is around 4MB.
2. When running springboot with hibernate, the file size becomes 2MB.
3. When reopening (if DBeaver startup is not wiping the DB), the DB contents seem correct, nothing is missing.

I've ensured that both spring and dbeaver h2 drivers are the same version com.h2database:h2:1.4.200.

![image](https://github.com/dbeaver/dbeaver/assets/7059964/47f296f8-23cb-435f-b578-a02fba51bb1b)

![image](https://github.com/dbeaver/dbeaver/assets/7059964/87b4dc22-4ae6-49be-be4d-3f206746006e)

I might be using the wrong hikari datasourceclassname ?

**Comment by LonwoLonwo** [comment]
Ok, I do not see anything special here. However, it is still unclear how exactly you are creating your database.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
