### ISSUE TITLE
Rollback timer flickers after the last update

### ISSUE THREAD

**Issue by ufuk-ergin-carbon** [dbeaver/dbeaver#22795]
### Description

The rollback timer at the bottom right used to stay stable but now it is flickering two times every second. Is this an intentional choice? Attaching the screen recording.

https://github.com/dbeaver/dbeaver/assets/114302087/bcb7d6c3-9f07-4b94-a545-f9395f6ee890

### DBeaver Version

Version 23.3.4.202402041841

### Operating System

MacOS Sonoma 14.3.1

### Database and driver

Server: Snowflake 8.5.2
Driver: Snowflake 3.14.4

### Steps to reproduce

Wait after your first query and put Dbeaver in the background without rolling your mouse pointer over it. Make it so that you would be able to see the Rollback timer in the background. After a while, you'll see that it will flicker like in the screen recording.

**Comment by E1izabeth** [comment]
I believe it's not intentional. Thank you for bug report.

**Comment by E1izabeth** [comment]
Reproduced on Windows 11
Also I have the orange icon for several second at the beginning, then it disappears.

**Comment by epancake** [comment]
Please please fix this it is so distracting and interrupts my workflow to have to minimize dbeaver everytime I need to click somewhere else.

**Comment by E1izabeth** [comment]
You can vote for the issue with 👍 under the issue description to promote it to a higher priority.

**Comment by ShadelessFox** [comment]
I was able to reproduce the issue:
1. You must have two connections: one with a disconnect timeout set and the second without
2. Open SQL editors for both of them
3. Go away for some time so the timer appears
