### ISSUE TITLE
Add Generate DDL to Oracle Tablespaces

### ISSUE THREAD

**Issue by RickSaavedra** [dbeaver/dbeaver#22809]
**Is your feature request related to a problem? Please describe.**
We need to be able to generate the DDL for Oracle Tablespaces. 

**Describe the solution you'd like**
Under the Storage->Tablespaces tree node, we would like a Generate SQL->DDL option for tablespaces. 

**Describe alternatives you've considered**
Running scripts manually to get the DDL for required tablespace.

**Additional context**

**Comment by LonwoLonwo** [comment]
Hello @RickSaavedra 

Thanks for the idea.

**Comment by LonwoLonwo** [comment]
For potential contributors:
You need to implement `DBPScriptObject#getObjectDefinitionText`
and add the OracleTablespace class to the list of objects, which support DDL non-editable tab:
```
<editor id="source.declaration.read-only" class="org.jkiss.dbeaver.ext.oracle.ui.editors.OracleObjectDeclarationViewer"
                label="%editor.package.declaration.name" description="%editor.package.declaration.description" icon="#sql_text" position="additions_middle"
                contributor="org.jkiss.dbeaver.ui.editors.sql.SQLEditorContributorNested" type="folder" embeddable="false">
            <objectType name="org.jkiss.dbeaver.ext.oracle.model.OracleSchema"/>
            <objectType name="org.jkiss.dbeaver.ext.oracle.model.OracleTableIndex"/>
            <objectType name="org.jkiss.dbeaver.ext.oracle.model.OracleSequence"/>
</editor>
```

**Comment by SSSDNSY** [comment]
> <objectType name="org.jkiss.dbeaver.ext.oracle.model.OracleSequence"/>

this issue have already to resolved ?  I want make my first contribution for this for dbeaver (its very interesting!) if nobody to contribute . (forgive my poor English level , but I believe you all are so smart can understard mine  idea)

**Comment by E1izabeth** [comment]
The issue is open. It means it is not resolved.

**Comment by SSSDNSY** [comment]
> The issue is open. It means it is not resolved.

ok ,i ll try and very thank you so quicklly  reply!

**Comment by SSSDNSY** [comment]
@LonwoLonwo 

First,Thank you very much, And I do it follow your tips
whith 2 file change like this bellow image:

![image](https://github.com/dbeaver/dbeaver/assets/15624361/53e48913-3180-4ced-97b5-59f830c0aaaf)


![image](https://github.com/dbeaver/dbeaver/assets/15624361/a4b2c737-4a5e-4b7c-9ba7-6898df91d6a6)
![image](https://github.com/dbeaver/dbeaver/assets/15624361/c5ec6493-2ad0-4a01-8fc0-0f3887d23a51)


and  I not sure its getObjectDefinitionText() implement is  like to "org.jkiss.dbeaver.ext.oracle.model.OracleSchema#getObjectDefinitionText" ,I think it just return String about the oracle database's tablespace ddl?
