### ISSUE TITLE
Fetching second time after first execution query

### ISSUE THREAD

**Issue by mauriliolima** [dbeaver/dbeaver#2280]
When i'm running some query, normal acting would be read (fetch) 200 rows and stop, waiting command to fetch more 200 rows. I'm using DBeaver 4.2.2 and after run my query and fetch first 200 rows, Dbeaver is fetching more 200 rows, even when I do nothing after hit <ctrl> + <enter>

**Comment by serge-rider** [comment]
I can't reproduce that.
Do you mean DBeaver fetches 200 + 200 rows (400) or it reads full table data?

Note: if you position cursor after 200 row (or 200+ row is visible) then DBeaver will fetch as much rows as required to show this row again.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
