### ISSUE TITLE
Read Metadata issue

### ISSUE THREAD

**Issue by Zaahid15** [dbeaver/dbeaver#22802]
### Description

When connected to an oracle server using presto, Dbeaver remains stuck at 50% reading metadata. This results in all or most of the script being highlighted in red which also results in the query failing and throwing an error.

<img width="365" alt="image" src="https://github.com/dbeaver/dbeaver/assets/62289462/268d6f23-9c0e-401e-9cac-49cf2969ce88">

The credentials are fine because after restarting my pc i can run queries again

### DBeaver Version

Dbeaver community Version 23.3.4.202402041841 

### Operating System

Windows 11

### Database and driver

oracle database
catalogue hive
presto connection

### Steps to reproduce

1. connect to database
2. read metadata
3. run query

**Comment by LonwoLonwo** [comment]
Hello @Zaahid15 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by Zaahid15** [comment]
Good day Anastasia.

I am delighted at your prompt response.

I have tracked this issue to my company server admins, it is not a Dbeaver
issue.

Thank you for your time and apologies for any inconvenience caused.

Warm regards.
Zaahid.

**Comment by LonwoLonwo** [comment]
Thanks for the answer, @Zaahid15 

Feel free to reopen this ticket if this issue occurs again.
