### ISSUE TITLE
Excel Export Freezes (DBeaver Office Support 1.0.0.21B1cKol-V7737A373E3E7I)

### ISSUE THREAD

**Issue by zenandjuice** [dbeaver/dbeaver#22814]
### Description

After upgrading to DBeaver 23.3.4.202402041841 and DBeaver Office Support 1.0.0.21B1cKol-V7737A373E3E7I, any export to Excel causes the application to freeze.  CSV and other exports work fine.

### DBeaver Version

Community edition 23.3.4.202402041841

### Operating System

macOS Sonoma 14.2.1

### Database and driver

PostgreSQL JDBC Driver

### Steps to reproduce

Run query (I've tried many), Export:  Export to XLSX (Excel spreadsheet formula)

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by LorisZ** [comment]
Experienced the same problem, maybe I found the reason: If you select all the rows and then click on export (or through context menu), then it will hang. If you just select one row, it should still export everything, but it does not hang and works.

Also related to this: The export for me never seems to work the first time; there is no file. Only after the second time I can find it in the selected folder.

**Comment by Destrolaric** [comment]
@LorisZ @zenandjuice Hi,
Could you please try to generate a thread dump and attach it here? Here is the instruction: https://dbeaver.com/docs/wiki/Making-a-thread-dump/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
