### ISSUE TITLE
Can you add "QUALIFY" as a keyword for syntax highlight?

### ISSUE THREAD

**Issue by whelanmike** [dbeaver/dbeaver#22812]
**QUALIFY** has been a keyword in many SQL dialects for a long time. 
It allows filtering on windowing functions. 

This is a nice to have. Definitely not urgent :)

Thanks

**Comment by E1izabeth** [comment]
Thank you for the idea

**Comment by lucydodo** [comment]
I'd like to try to resolve this ticket. :)
