### ISSUE TITLE
Login window for Database-Connection without title

### ISSUE THREAD

**Issue by Neumi25** [dbeaver/dbeaver#22818]
### Description

Unlike the previous version CE 23.3.3, the login windows for the database connection do not have a title, e.g. "'XP2HAD02 (P - Big2: DDA, DMK, DNL)' Authentication" any longer.
This means that the windows can no longer be identified with KeePass and therefore not filled out automatically.

### DBeaver Version

Community Edition 23.3.4

### Operating System

Windows 10

**Comment by E1izabeth** [comment]
Thank you for bug report. It's a duplicate of #22766
The issue has been already solved. You could try Early Access version (https://dbeaver.io/files/ea/) or wait for the next release on Monday.
