### ISSUE TITLE
Oracle user field values are empty in Users List View and User Property view.

### ISSUE THREAD

**Issue by RickSaavedra** [dbeaver/dbeaver#22810]
### Description

When viewing users for an Oracle database, some of the columns are not returning any values in either the list view or the user properties view. (ie, Lock Date, Expiry Date, Default tablespace, Temporary tablespace, and profile)

List View
![image](https://github.com/dbeaver/dbeaver/assets/10950037/a65bbc95-8fed-40ad-870e-6d05042c3126)

Properties View
![image](https://github.com/dbeaver/dbeaver/assets/10950037/c4785f4f-6d5c-4f8d-a518-1180a1a109b6)

### DBeaver Version

Community Edition 23.3.2

### Operating System

Windows 10

### Database and driver

Database Server: Oracle 19c
Oracle Client JDBC: Oracle JDBC 23.30..23.09

### Steps to reproduce

1. Connect to Oracle Database
2. Navigate to Security
3. Double click on Users in tree view.
4. Results will be listed and values will not be shown
5. Double click on user to bring up the properties window.
6. Fields will be empty

### Additional context

N/A

**Comment by LonwoLonwo** [comment]
Hello @RickSaavedra 

You need to check this setting in your Connection settings to see more admin-specific data:

![2023-10-17 12_10_15-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/d9648a13-defc-4adb-acbb-f4adf8a5952c)

**Comment by RickSaavedra** [comment]
@LonwoLonwo Thank you so much. That did the trick.
