### ISSUE TITLE
Azure AD authentication with MFA SocketException

### ISSUE THREAD

**Issue by rgn** [dbeaver/dbeaver#22819]
### Description

Hi,

I've setup a SQL Server connection with Azure AD authentication (MFA). When I try to test the connection a browser window opens and tell my that the authentication is complete and I can close it. Directly after this I get an error in DBeaver telling me that the established connection was closed.

Any hint or idea what causes this issue and an explanation how to get it working?

### DBeaver Version

22.3.4.202302060909 (Community Edition)

### Operating System

Windows 11 22H2

### Database and driver

MSSQL, Azure Sql Database

### Steps to reproduce

Connection Settings
![image](https://github.com/dbeaver/dbeaver/assets/63072/a2b2922e-a71f-4d5c-b736-c296ab6e731b)

Driver Settings
![image](https://github.com/dbeaver/dbeaver/assets/63072/30ff9489-3085-49cf-aa9a-98ff1a9bd2b9)

Browser Content
![image](https://github.com/dbeaver/dbeaver/assets/63072/8592684e-fc1c-41ce-8f2c-d5757d86922c)

Error Message
![image](https://github.com/dbeaver/dbeaver/assets/63072/0a2bfafd-bfcc-44cf-abdc-61bf2cace91d)

**Comment by Destrolaric** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by rgn** [comment]
Here is the .log (renamed to default.log) and dbeaver-debug.log.

[default.log](https://github.com/dbeaver/dbeaver/files/14288958/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/14288949/dbeaver-debug.log)

**Comment by MikeCoyote** [comment]
I do have the same issue since previous releases... and have to user MsSQL!

After confirming my MFA with Azure, The browsr screen remain blank like Below
![image](https://github.com/dbeaver/dbeaver/assets/162514122/8d723dfe-b66c-440e-98bc-37673567f4ce)

**Comment by MikeCoyote** [comment]
I am on version : Version 24.0.0.202403031740

**Comment by MikeCoyote** [comment]
New message in my logs :

Connection to 'Prod-Nop' cannot be established.

Motif:
Échec de l'authentification de l'utilisateur  dans Active Directory (Authentication=ActiveDirectoryInteractive).

Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr
Framework arguments:  -eclipse.keyring C:\Users\milapierre\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

**Comment by arhayka** [comment]
We are unable to reproduce the issue, so I’ll close the ticket. Please feel free to reopen it if the issue persists.
