### ISSUE TITLE
Enhance Hide folders mode

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#22826]
We need to review the 'Hide folders' mode and improve it for PostgreSQL and other databases.

To enable 'Hide folders' mode:
1. Right-click on the connection on Database Navigator
2.  Select Custom view —> Hide folders

- Hide encoding and other service entities
- Remove an error message

<img  width="200px" src="https://github.com/dbeaver/dbeaver/assets/12581569/35d03704-64ab-422c-8c9d-2de5fa2f5b61">

<img  width="200px" src="https://github.com/dbeaver/dbeaver/assets/12581569/facd0b7c-b66f-40d5-89ce-46c84497ef86">

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/issues/16366 error ticket
