### ISSUE TITLE
Schema objects not loading on refresh

### ISSUE THREAD

**Issue by lalato** [dbeaver/dbeaver#22828]
### Description

When I create a new table, the new table is not getting picked up on reload/refresh of Schema objects.

### DBeaver Version

Version 23.3.4.202402060628

### Operating System

macOS Sonoma 14.1.1

### Database and driver

Snowflake
Server 8.6.2
Driver 3.13.6

### Steps to reproduce

1. Expand Schema to see objects underneath
2. Right-Click on "Tables"
3. Select Refresh from context menu

**Comment by E1izabeth** [comment]
@lalato
Thank you for bug report.
Could you tell me what database server and driver version do you use?
You can check it by pressing Test Connection button in the connection wizard
![image](https://github.com/dbeaver/dbeaver/assets/28875055/9a1758ec-a70f-4414-b79a-91533bb39ba7)

**Comment by E1izabeth** [comment]
Do you have any active transaction while trying to refresh Tables? You can see it here
![image](https://github.com/dbeaver/dbeaver/assets/28875055/4085fd04-c3c1-4895-a3e1-a848eb2d6a3f)

**Comment by lalato** [comment]
Updated the original post with Server and Driver details.

Snowflake
Server 8.6.2
Driver 3.13.6

**Comment by lalato** [comment]
> Do you have any active transaction while trying to refresh Tables? You can see it here 

There are no active transactions

**Comment by E1izabeth** [comment]
Thank you

**Comment by E1izabeth** [comment]
Unfortunately, I can't reproduce the issue.
Could you reproduce it again and send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by arhayka** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
