### ISSUE TITLE
parallel execution query not work

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#22830]
### Description

button parallel execution query not work

### DBeaver Version

community edition 23.3.4

### Operating System

windows 11 64bit

### Database and driver

postgresql 14

### Steps to reproduce

1. added pg_sleep(20) to procedure
2. push button "simultaneous execution of requests"
![image](https://github.com/dbeaver/dbeaver/assets/61137576/0418e2a8-1346-4e6e-9728-0b050bc8832b)

only one process is started

**Comment by LonwoLonwo** [comment]
Related: https://github.com/dbeaver/dbeaver/issues/22504

**Comment by Destrolaric** [comment]
Hi, @detkliff could you provide the video which demonstrates the mentioned issue?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
