### ISSUE TITLE
Mismeasured Idle period

### ISSUE THREAD

**Issue by davidespagnoli** [dbeaver/dbeaver#22840]
### Description

after every query I get the message "Trasnsactions in database [DB_NAME] will be ended because of the long idle time
press 'Cancel' to prevent this"
if I press "Cancel" the message keeps showing up after 1-3 seconds, I have to be quick to commit the transaction before it shows up again.
I guess the idle period is mismeasured

### DBeaver Version

Community Edition 22.3.4

### Operating System

Windows 11

### Database and driver

MariaDB 10.5.24

### Steps to reproduce

with "autocommit" off, the message will appear after ANY query, either from "Script SQL" panel or from table data view
![Screenshot 2024-02-16 112922](https://github.com/dbeaver/dbeaver/assets/25242572/d822239e-397b-490e-96ba-1daf5c3c84f2)

**Comment by davidespagnoli** [comment]
Edit: unchecking "Close idle connection after (seconds)" option in the preferences page solves temporaly the problem, but the next app restart will check the option again
![image](https://github.com/dbeaver/dbeaver/assets/25242572/aa52ad95-8357-4b74-b73f-0edad1eb5347)

**Comment by E1izabeth** [comment]
Hi, @davidespagnoli 
Thank you for bug report.
There was a bug in version 23.3.4 with saving this checkbox state and we have already fixed it. You can try fix now in the Early Access version https://dbeaver.io/files/ea/ or wait for the next release on Monday.

**Comment by alr888rav** [comment]
I have the same problem

**Comment by CComparon** [comment]
Had the same annoying problem. Thanks for the quick fix.

**Comment by E1izabeth** [comment]
@davidespagnoli does this issue reproducible on the latest DBeaver version? Could you check?

**Comment by davidespagnoli** [comment]
I confirm that the issue is fixed now, thank you

--

Ing. Davide Spagnoli
Adam S.r.l.
Via della Volta, 183 - 25124 Brescia
Tel +39.030.35.32.818www.adamcashmanagement.com
Il presente messaggio ed ogni suo eventuale
allegato contengono informazioni da considerarsi
riservate e confidenziali e sono indirizzate
esclusivamente ai destinatari in esso indicati.
Qualora abbiate ricevuto questa email per errore,
vi invitiamo gentilmente ad avvisare il mittente e
a provvedere alla sua cancellazione dal vostro sistema.
