### ISSUE TITLE
light theme is broken

### ISSUE THREAD

**Issue by AshutoshSajan** [dbeaver/dbeaver#22846]
### Description

when switching to the light theme it's not applied to the entire app and the left side db list section is still in dark mode.

### DBeaver Version

comunity editon 23.3.4.202402060628

### Operating System

Ubuntu 20.04.6 LTS x86_64

### Additional context

when switching the dark theme to light from window -> preferences -> user interfaces -> appearance 
light theme is broken, in SQL editor, left side db list section, properties, and ER diagram tabs when viewing table details

system info
![image](https://github.com/dbeaver/dbeaver/assets/44765540/79fadc89-5e66-4b92-b14c-b148808c1850)

screenshots
![image](https://github.com/dbeaver/dbeaver/assets/44765540/5c746cf3-aa68-402c-8e1a-dcff2c21b255)
![image](https://github.com/dbeaver/dbeaver/assets/44765540/849592e9-7d2a-4ba6-bb54-158c594cba7b)
![image](https://github.com/dbeaver/dbeaver/assets/44765540/571cf0ea-3021-49eb-a000-418ba4071744)
![image](https://github.com/dbeaver/dbeaver/assets/44765540/904ac686-1e81-434b-9d15-3b7e809b4429)

**Comment by E1izabeth** [comment]
Have you restarted DBeaver after theme switching?

**Comment by AshutoshSajan** [comment]
> Have you restarted DBeaver after theme switching?

yes i have restarted

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
