### ISSUE TITLE
PostgreSQL rules

### ISSUE THREAD

**Issue by ksamborski** [dbeaver/dbeaver#2284]
I use dbeaver mostly with PostgreSQL. When I look how some view is defined I can see only the source select query and triggers. But in postgres you can use rule instead of trigger which simple rewrites the update/insert/delete query. And the rules are not shown neither in Source nor Triggers tab. Could you please add them somewhere?

**Comment by shadowRR** [comment]
@serge-rider Any news on this ? I'm in the same situation, and was wondering if any progress had been made ? Thanks.

**Comment by serge-rider** [comment]
Raising priority

**Comment by russmo** [comment]
Just stumbled on this same issue.  Considering rewriting the rules as triggers now just so I can see them in DBeaver.  Any progress?

**Comment by shadowRR** [comment]
@russmo It's on the roadmap for the v5.2.4, so one version away. Shouldn't be too long now, that version is normally due on November 5 (worst case scenario, by the end of the year i'm guessing).

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/50557629-12e60d00-0cf8-11e9-8032-c48ff27a6d9c.png)
