### ISSUE TITLE
[Query Results / Advanced Copy / Copy as SQL] Add an option to preserve copying auto-incremented primary key column

### ISSUE THREAD

**Issue by coldenol** [dbeaver/dbeaver#22841]
**Is your feature request related to a problem? Please describe.**
When copying query results as `Copy as SQL` the column `id` with auto-incremented primary key is skipped and is missed in the `INSERT` statements.
<img width="705" alt="image" src="https://github.com/dbeaver/dbeaver/assets/49859188/d081af14-4cd6-4b80-9533-303d134a6455">
<img width="335" alt="image" src="https://github.com/dbeaver/dbeaver/assets/49859188/d04a4033-8153-4ff8-b133-c90192945b27">

**Describe the solution you'd like**
It would be great to have an additional item below the `Copy as SQL` called, for example, `Copy as SQL (preserved auto increment)` (1), or to have it as a setting in the configuration (2).
<img width="659" alt="image" src="https://github.com/dbeaver/dbeaver/assets/49859188/96847622-4830-40b1-a56d-b36e0c746e7e">

**System**
MacOS 14.3
Dbeaver 23.3.3
MySQL 8.0.35

**Comment by LonwoLonwo** [comment]
Hello @coldenol 

Did you try to enable this setting?

![2024-02-21 15_27_02-Configure 'Copy as' commands ](https://github.com/dbeaver/dbeaver/assets/45152336/cccd3e64-572e-4b49-80b7-bb0dd8e62123)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
