### ISSUE TITLE
Renaming a project fails silently when the name includes an invalid caracther

### ISSUE THREAD

**Issue by miguelbrandao** [dbeaver/dbeaver#22843]
### Description

When renaming a project, if the name contains an invalid character (like `/`) the action fails silently, simply not renaming the project. Recording below to illustrate the issue:

https://github.com/dbeaver/dbeaver/assets/26719984/c4d104f5-c811-40ab-bca7-69cca5a4ef21

I believe a user would expect a behavior similar to the Project Create Wizard, where it shows an error message and the 'confirm' button is disabled:

![image](https://github.com/dbeaver/dbeaver/assets/26719984/2d42a2df-46ec-48c4-8724-4a1aafa387fa)

---
PS: Not sure if I should have filed this under bug or feature request as, technically, it's working fine. However, since an error message should be the expected behavior, I think it fits better under a bug report. Apologies if I misclassified the issue.

### DBeaver Version

Community Edition 23.3.4

### Operating System

macOS Sonoma 14.1

### Steps to reproduce

1. Rename a project with a name containing an invalid character (like `/`)
2. Observe that the name has not changed

**Comment by LonwoLonwo** [comment]
Hello @miguelbrandao 

Thanks for the report.

As for other errors - you can find the info in the Error Log.

![2024-02-21 13_43_10-DBeaver 23 3 5 - Album](https://github.com/dbeaver/dbeaver/assets/45152336/39d49f6e-0f2a-44bc-83a7-5a2b2f18187d)

But we can enhance this specific case and add some warning.
