### ISSUE TITLE
Sorting rule bug when editing column properties

### ISSUE THREAD

**Issue by Jackxiaojiahuo** [dbeaver/dbeaver#22852]
### Description

When creating a new column in the table, the sorting rule is set in the drop-down menu, and data cannot be selected

### DBeaver Version

23.3.5.202402181738

### Operating System

Windows 10

### Database and driver

MySql 8.0.28

**Comment by serjiokov** [comment]
@Jackxiaojiahuo Please provide more details for the issue.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
