### ISSUE TITLE
workspace migration version 23.3.5 lost data

### ISSUE THREAD

**Issue by fgibaux** [dbeaver/dbeaver#22858]
### Description

I upgraded DBeaver Community to version 23.3.5. 

I got a message saying the workspace format had changed and proposed to migrate it. I clicked yes. 

It lost a few projects, connections, and scripts. (without a recent backup, my bad)

I would have expected the migration to succeed or a backup to be done.

here is the  debug log:

[dbeaver-debug-1708339368172_redacted.log](https://github.com/dbeaver/dbeaver/files/14330200/dbeaver-debug-1708339368172_redacted.log)

### DBeaver Version

DBeaver Community 23.3.5

### Operating System

Fedora 38

**Comment by Ocanipse** [comment]
The folder that the application used and the one that has all the previous configuration is /home/user/.local/share/.DBeaverData, and as of this update the application seems to use /home/user/.local/share/DBeaverData. I had to rename folders and fixed it. So your information should be there thankfully.

Anyway, when I installed a new driver, it reinstalled it in the .DBeaverData folder.

**Comment by fgibaux** [comment]
oh thank you! I didn't realised that. 

I confirm `.DBeaverData` has the correct workspace data, and copying it into the `DBeaverData`  folder works.

**Comment by serge-rider** [comment]
@fgibaux What is your previous version of DBeaver?

**Comment by Ocanipse** [comment]
You didn't ask me, but since I had the same problem, I take the liberty to answer: my previous version was 23.3.4. Today I installed 23.3.5 and I found this huge problem, which fortunately I was able to solve temporarily.
I hope it can be solved.
Regards

**Comment by MrMitch** [comment]
Hi,

I encountered the same situation and the fix mentionned in [@Ocanipse's first comment](https://github.com/dbeaver/dbeaver/issues/22858#issuecomment-1952228186) allowed me to retreive the lost configuration.

I had just updated `dbeaver-ce:amd64` from  `23.3.3~ubuntu16.04` to `23.3.5~ubuntu16.04` on Ubuntu 22.04.4 LTS

**Comment by teicors** [comment]
Hi,
the same from 23.3.4 to 23.3.5 CE
Linux Ubuntu 23.10 amd64

**Comment by Khartir** [comment]
Just a bit more information, since I had the same problem:
After migration I had only 4 of my configured connections show up. These were described in both `/home/user/.local/share/DBeaverData/workspace6/General/.dbeaver-data-sources.xml` and `/home/user/.local/share/.DBeaverData/workspace6/General/.dbeaver-data-sources.xml`.

After copying the complete contents of the workspace from `.DBeaverData` to `DBeaverData` the missing connections were back.
So it appears there are multiple places where configurations are stored and the migration script maybe only migrates one of them?

**Comment by serjiokov** [comment]
Hello @fgibaux, 
So, this is a side effect specifically on Linux in Dbeaver version 23.3.5 in case the path '/.local/share/.DBeaverData' exists.
In short, the resent workspace path is out and the default ("~/.local/share/DBeaverData") was created, your data is not lost.
As a workaround, please point to your previous workspace (".local/share/.DBeaverData/workspace6") using "File->Switch Workspace" or copy data as suggested before.

**Comment by fgibaux** [comment]
> @fgibaux What is your previous version of DBeaver?

My previous version was 23.3.4

> Hello @fgibaux, So, this is a side effect specifically on Linux in Dbeaver version 23.3.5 in case the path '/.local/share/.DBeaverData' exists. In short, the resent workspace path is out and the default ("~/.local/share/DBeaverData") was created, your data is not lost. As a workaround, please point to your previous workspace (".local/share/.DBeaverData/workspace6") using "File->Switch Workspace" or copy data as suggested before.

Thank you, as commented previously I copied the data and found all my connections/project back.

**Comment by arhayka** [comment]
@fgibaux Thanks for the feedback, it's really great to hear that the workaround helped!
However, we still want to fix this issue. Please, don't close this ticket.

**Comment by alessandrofuda** [comment]
Solved! thanks @Ocanipse , but it's a problem to solve. I lost about one hour.
