### ISSUE TITLE
java.net.SocketException:java.security.NoSuchAlgorithmException for version 23.3.5

### ISSUE THREAD

**Issue by landy8530** [dbeaver/dbeaver#22853]
### Description

When I updated the DBeaver to version 23.3.5, it occurs following errors.
<img width="1053" alt="image" src="https://github.com/dbeaver/dbeaver/assets/26703026/0d93e761-2b1a-46b6-804e-1d22ef9d8911">

### DBeaver Version

Community 23.3.5

### Operating System

mac OS 13.6.1 (22G313)

### Database and driver

When I updated the DBeaver to version 23.3.5, can not connect databases like mysql and Oracle

**Comment by landy8530** [comment]
It works for version 23.3.0, and it does not work when its version greater than 23.3.0(i.e. 23.3.1 +)

**Comment by landy8530** [comment]
After add the maven repo as following, it works now.
![image](https://github.com/dbeaver/dbeaver/assets/26703026/06f2b0fc-3881-45e0-998a-d5423c4f20be)
The driver has been dowloaded successfully.
![image](https://github.com/dbeaver/dbeaver/assets/26703026/bbd20eee-bdfe-4cd4-a4b7-f72645167ed8)

**Comment by LonwoLonwo** [comment]
Thanks for the update @landy8530
