### ISSUE TITLE
Setting a Database as Default is not persistent 

### ISSUE THREAD

**Issue by mezlondr** [dbeaver/dbeaver#22869]
### Description

Selected default database is not persistent after restarting DBeaver.

### DBeaver Version

Community Edition 23.3.5

### Operating System

Windows 10

### Database and driver

MS SQL Server / SQL Server

### Steps to reproduce

1. Open the application
2. In the Database navigator, open some connection and expand Databases
3. RMB to a database and click Set as Default
4. Restart the application
5. -> The previously selected database is no longer default

**Comment by LonwoLonwo** [comment]
Hello @mezlondr 

If you want to keep the default database name for your connection - you can make this choice in your connection settings -> Initialization -> Default database.

![2024-02-20 10_31_48-Connection _master_ configuration](https://github.com/dbeaver/dbeaver/assets/45152336/f2cb7b33-3077-4b00-a605-88a2b42e3341)

**Comment by mezlondr** [comment]
Hello @LonwoLonwo 
That's nice, seems to work.
Then, in case this is not a bug it can be closed?

**Comment by LonwoLonwo** [comment]
Yes, I'm closing it. Thanks for the update.

**Comment by mezlondr** [comment]
Thanks for the help
