### ISSUE TITLE
MariaDB Performance and Session details query not returning any result

### ISSUE THREAD

**Issue by balajiboopathi1997** [dbeaver/dbeaver#22877]
### Description

Hello,

I'm currently utilizing MariaDB version 11.2.2, installed on a Linux machine via [this link](https://archive.mariadb.org/mariadb-11.2.2/bintar-linux-systemd-x86_64/mariadb-11.2.2-linux-systemd-x86_64.tar.gz). Upon extracting the tar file, databases are automatically created, including the SYS database.

We utilize the table sys.x$session to retrieve session details and sys.x$statement_analysis for performance details. However, we are encountering an issue where these queries return empty results on Linux, while they work correctly on Windows.

Any assistance in addressing this matter would be greatly appreciated.

Thank you.

### DBeaver Version

Maria DB 11.2

### Operating System

Linux

**Comment by LonwoLonwo** [comment]
Hello @balajiboopathi1997 

Does it mean your ResultSet is empty in the SQL Editor for selecting queries for sys.x$session and sys.x$statement_analysis?

Could you please provide the log files after the Select operation? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
