### ISSUE TITLE
DBeaver - Office support Addon not working at all | Dbeaver CE, Version 23.35202402181738

### ISSUE THREAD

**Issue by m3n3chm0** [dbeaver/dbeaver#22871]
### Description

Dear all guys,

Office support Addon not working at all. I'm using Dbeaver CE, Version 23.35202402181738, any clue ?

If you need any log file, just let me know.

Thank you in advance.

![image](https://github.com/dbeaver/dbeaver/assets/14914905/561e9003-a85f-4405-8b07-86a9c8a3d3b7)

![image](https://github.com/dbeaver/dbeaver/assets/14914905/90ca61e4-76dc-46ac-b3cf-a4b20379229e)

![image](https://github.com/dbeaver/dbeaver/assets/14914905/aca50a8b-f2f8-4aa2-8c2a-ba2744d77659)

### DBeaver Version

23.3.5

### Operating System

Windows 11 64bit, 22H2

### Steps to reproduce

1. Run query.
2. Data extraction to Excel is not possible as the Excel add-in is not available in the GUI.

**Comment by E1izabeth** [comment]
Have you updated DBeaver after installing Office support?

**Comment by m3n3chm0** [comment]
Dear, @E1izabeth 

Indeed, I’ve already closed and reopened Dbeaver after enabling the Office support addon. However, that option is still missing. In addition, I’ve also tried reinstalling Dbeaver, but the same issue persists :(

Thank you for your attention.

**Comment by E1izabeth** [comment]
I'm asking for version update, not about restarting it.

**Comment by m3n3chm0** [comment]
If I’m not misunderstanding you, I already have the latest version installed.

![image](https://github.com/dbeaver/dbeaver/assets/14914905/a5842330-2589-4d60-b81e-4661ceb9e12c)

**Comment by E1izabeth** [comment]
Office support installation is required each time when you update DBeaver version. So, I'm asking you about the exact time when you installed Office support - before you get the latest version or after?

**Comment by m3n3chm0** [comment]
OK, I guess Office support installation was installed before the latest version.

**Comment by E1izabeth** [comment]
Please install it again and it will work.
Here is an issue about the need to install plugins each time #5317 You can vote for this issue with 👍 under the issue description to promote it to a higher priority.

**Comment by m3n3chm0** [comment]
OK, I'll try, thank you so much for your quick support ! Really appreciated.

**Comment by m3n3chm0** [comment]
@E1izabeth, I've tried to reinstall the Office plugin but something strange happens, in the list of plugins it appears installed but it does not work. And even stranger, when trying to uninstall the plugin and close Dbeaver and open it again the plugin is still installed. ☹️

**Comment by m3n3chm0** [comment]
Let me share this video so you'll find what I mean.

https://github.com/dbeaver/dbeaver/assets/14914905/b2a7dfa0-654d-4294-9ca2-355ad8a8edf0

**Comment by E1izabeth** [comment]
Could you provide the log files? 
You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by E1izabeth** [comment]
@m3n3chm0 could you also show your Installation Information?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/8e64ca82-e037-488f-b507-c821e5d05912)

**Comment by m3n3chm0** [comment]
@E1izabeth here you go. 

Thank you !

[Dbeaver Logs.zip](https://github.com/dbeaver/dbeaver/files/14361572/Dbeaver.Logs.zip)

![Dbeaver_Installation_Info](https://github.com/dbeaver/dbeaver/assets/14914905/b27156fd-9789-410f-9043-78c6edf6f490)

**Comment by m3n3chm0** [comment]
Morning guys @serjiokov @LonwoLonwo @E1izabeth 

After the upgrade of DBeaver from this morning, the office addon is working again  finally so please you could close this ticket 

Really appreciated !

Steps to fix the issue after the upgrade:

1. disable office addon.
2. enable office addon.
3. restart DBeaver.

![image](https://github.com/dbeaver/dbeaver/assets/14914905/fcce5607-505a-4991-a0ba-18802e7cbcbc)

**Comment by E1izabeth** [comment]
Thank you

**Comment by m3n3chm0** [comment]
Hi, @E1izabeth 

After upgrading to the new version 24.0.2, I am still experiencing the same error. The Office Addon is installed, but it is not working at all. I've already tried what worked for me the latest time, disabling and reinstalling the Office Addon, but this time with no success.

![image](https://github.com/dbeaver/dbeaver/assets/14914905/8d8d5a2c-049f-441a-ab20-63de2cd1c30a)

**Comment by Yigitttttttt** [comment]
I think this issue no longer exists with #28259

**Comment by E1izabeth** [comment]
@m3n3chm0 does it still reproducible?

**Comment by E1izabeth** [comment]
Seems the issue is solved. If it's not so, please let me know
