### ISSUE TITLE
after upgrade issue

### ISSUE THREAD

**Issue by poltpolt** [dbeaver/dbeaver#22880]
### Description

I upgrade to latest 23.3.5 and when i try to connect to localhost I get

class [B cannot be cast to class [C ([B and [C are in module java.base of loader 'bootstrap')

### DBeaver Version

23.3.5 official RPM package

### Operating System

Linux Opensuse

### Database and driver

Mariadb 11.2.2

### Steps to reproduce

verify mariadb/mysql works for localhost in console with user and pass by executing `mariadb -u myuser -p`
create a direct connection to mariadb in dbeaver and hit ok or test connection
see the error given

**Comment by ShadelessFox** [comment]
Hello @poltpolt,

Can you please send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.

**Comment by poltpolt** [comment]
I fixed it desperately messing blindly with the settings, I am convinced entering Driver Manager and redownloading the driver fixed the issue cause now I can use it
