### ISSUE TITLE
Relationship lines not showing on ER diagram

### ISSUE THREAD

**Issue by trdinger** [dbeaver/dbeaver#22882]
### Description

Multiple team members are unable to open the ER diagram and observe the relationship lines.  The table entities are shown but fact tables are now highlighted until one goes to the individual table ER diagram.  I am attaching screenshots for both the schema and individual table ER diagrams.
![Screenshot 2024-02-20 at 9 36 18 AM](https://github.com/dbeaver/dbeaver/assets/67650729/e611dd5a-8429-43b5-b2e4-7764ad0f3def)
![Screenshot 2024-02-20 at 9 36 41 AM](https://github.com/dbeaver/dbeaver/assets/67650729/a8360478-b763-46cd-9b35-d7d0fa3b8efc)

### DBeaver Version

Community Edition Version 23.3.5.202402181738

### Operating System

macOS Sonoma Version 14.2.1

### Database and driver

DB2 for LUW

### Steps to reproduce

1.  I select the schema or table.
2. I select the ER diagram tab.

### Additional context

On initial download of DBeaver in December, the ER diagram correctly showed the relationship lines.  Multiple updates have since been applied, but it is unclear at what point the current behavior began.

**Comment by LonwoLonwo** [comment]
Hello @trdinger 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by trdinger** [comment]
[dbeaver-debug-1708435893565.log](https://github.com/dbeaver/dbeaver/files/14363557/dbeaver-debug-1708435893565.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/14363572/dbeaver-debug.log)

**Comment by LonwoLonwo** [comment]
Thanks for the report!
I can reproduce it.

**Comment by serge-rider** [comment]
Fixed

**Comment by ElectroLund** [comment]
I see that this is an old bug report, but I just upgraded to 25.1.5.202508171444 and now I no longer have any diagram connections between tables.

The only recent error log entry is:

eclipse.buildId=unknown
java.version=21.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\{USER}\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -eclipse.keyring C:\Users\{USER}\AppData\Roaming\DBeaverData\secure\secure_storage

org.eclipse.ui
Warning
Tue Aug 19 10:01:43 MDT 2025
Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)
