### ISSUE TITLE
Syntax highlighting for WHERE clause does not work for more than one condition

### ISSUE THREAD

**Issue by shenzj1994** [dbeaver/dbeaver#22887]
### Description

If I have multiple conditions in a WHERE clause, only the first condition get highlighted.
![image](https://github.com/dbeaver/dbeaver/assets/12000606/5fdb884e-6c0d-462e-b6ab-7da4f3634d7b)

### DBeaver Version

Community Edition Version 23.3.5.202402181738

### Operating System

Windows 10 Enterprise

### Database and driver

**Database:**
PostgreSQL 9.4.26
PostgreSQL 9.4.26 (Greenplum Database 6.22.2)

**Driver:**
PostgreSQL JDBC Driver 42.6.0

### Steps to reproduce

Write a SQL query in the query editor with multiple condition in WHERE clause.

**Comment by TK-517** [comment]
Just got a similar case which might help fixing the bug:
As this syntax helps to comment / uncomment specific condition in the where clause I usually us a first condition which is always true and add a seperate line for each additional condition.

If I use `WHERE TRUE` as first condition the syntax highlighting partially stops working after this condition (`v.name` and `v.brand` ),

![grafik](https://github.com/dbeaver/dbeaver/assets/78752258/3870fd8b-7d53-4496-9807-096d03daaa5d)

while syntax highlighting works fine if I use `WHERE 1=1` instead
![grafik](https://github.com/dbeaver/dbeaver/assets/78752258/dc9f1fe6-bdd3-4b81-bae2-cff36f0733a4)

I am using a MySQL database.

@shenzj1994: as you can see in the screenshot multiple conditons work fine for me (using MySQL at least). Maybe it's rater the `num::int<>0`?#

DBeaver Version
Community Edition Version 23.3.5.202402181738

Operating System
Windows 10 Enterprise

Database:
MySQL

**Comment by shenzj1994** [comment]
@TK-517 Yes you are right! If I replace `meter_num::int` with `cast(meter_num as int)`, the syntax highlighting began to work. Seems like it had difficulty processing the `::` operator.

**Comment by E1izabeth** [comment]
Please try new version 24.0.0. I believe it's fixed there.

**Comment by shenzj1994** [comment]
Yes it's fixed in the new version. Thanks.

**Comment by TK-517** [comment]
Unfortunately the syntax used in my post still brakes the highlighting

**Comment by E1izabeth** [comment]
@TK-517 here is a separate issue for your case #23079
