### ISSUE TITLE
Auto Save SQL Editor (secondary file)

### ISSUE THREAD

**Issue by nicolas-jimenez-itsn** [dbeaver/dbeaver#22894]
On several occasions I have had problems on my computer and it has caused loss of work in dbeaver.

I think it would be a good idea for Dbeaver to automatically save the work to an alternative file, in the same way that tools like vi work in linux, saving a file ending in ~ for autosaves, and only replacing the original file when the user decides to save. This autosave could be performed at each execution of the code.

Solution #491 is not valid for all users because you do not always want your changes to be saved.

**Comment by LonwoLonwo** [comment]
Hello @nicolas-jimenez-itsn 

For now, we have two settings for SQL Editor content auto-saving.
Are you sure you can't use the "Auto-save editor on close"?

![2024-02-21 11_44_25-Preferences](https://github.com/dbeaver/dbeaver/assets/45152336/79426eb6-41c3-4d7d-a006-7f2e6c2ea1dd)

**Comment by nicolas-jimenez-itsn** [comment]
Hello @LonwoLonwo ,
No, these options modify the original file, but I would prefer that this file is only modified when I decide to do so, and in the meantime it is stored in another file. This way, I could decide to discard the changes and not save them.
Thanks for your reply

**Comment by humphreygao** [comment]
I think none of people really like vi
.

This autosave could be performed at each execution of the code.
So if you do not execute the SQL, the file will not be saved??? We could not accept it.

**Comment by nicolas-jimenez-itsn** [comment]
> So if you do not execute the SQL, the file will not be saved??? We could not accept it.
>
It was a proposal looking for a simple solution, maybe you would prefer to save "after any modifications".

**Comment by LonwoLonwo** [comment]
Maybe the Git integration will be helpful for you. 

https://github.com/dbeaver/dbeaver/wiki/Project-team-work

This extension is included in the EE version. It can also be installed manually on the CE version.
Marketplace URL:https://marketplace.eclipse.org/content/dbeaver-git-support
P2 repository URL:https://dbeaver.io/update/git/latest/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by nicolas-jimenez-itsn** [comment]
It is a pity that it will not be implemented.
I am currently working on a vdi that logs out (sign off) after a certain amount of inactivity, and I have lost my work on several occasions. I will have to use the option to save on every execution, although I think I'm not the only one who doesn't like not being able to decide when to save and when not to save.
Thanks!

**Comment by E1izabeth** [comment]
@nicolas-jimenez-itsn what about the [proposed solution using git](https://github.com/dbeaver/dbeaver/issues/22894#issuecomment-1959598461)?
