### ISSUE TITLE
"show column description in header" doesn't wrok 

### ISSUE THREAD

**Issue by DavidHJong** [dbeaver/dbeaver#22907]
### Description

I follow this instruction to show the comment in table header, but it doesn't work. 
windows > preferences > editors > data editor > appearance > show column description in header.

Do you guys have any idea how to fix it? 

<img width="810" alt="Screenshot 2024-02-22 082322" src="https://github.com/dbeaver/dbeaver/assets/31554275/dc7eac81-ee25-4986-9787-5c924a772100">
<img width="1280" alt="Screenshot 2024-02-22 082432" src="https://github.com/dbeaver/dbeaver/assets/31554275/3f053efb-38a9-4b8c-8384-65c54f4fc0e4">
<img width="1280" alt="Screenshot 2024-02-22 082417" src="https://github.com/dbeaver/dbeaver/assets/31554275/d88084b7-545e-48ad-8e7f-fe052a5290c2">

### DBeaver Version

community edition 23.3.5.202402181738

### Operating System

Windows 10 19045

### Database and driver

Database: Postgresql 15.5 
Driver: PostgreSQL JDBC driver 42.5.2

**Comment by LonwoLonwo** [comment]
Hello @DavidHJong 

Unfortunately, I can't reproduce it.

![2024-02-22 13_04_54-DBeaver Ultimate 23 3 5 - forest](https://github.com/dbeaver/dbeaver/assets/45152336/cfabcf7a-01b5-456e-8a0c-c685d172a89f)

Did you try to restart DBeaver?
Also, you can try to do this: https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings

**Comment by DavidHJong** [comment]
Ahh, I didn't restart the DBeaver and now it works. Thank you @LonwoLonwo !
