### ISSUE TITLE
"show all databases" checkbox does not see in Postgres SQL connection 

### ISSUE THREAD

**Issue by kuodebbie** [dbeaver/dbeaver#22909]
### Description

I am using DBeaver Community Version 23.3.5.202402181738. 

Database: PostgresSQL
In the Connection Settings-> PostgresSQL tab: I don't see any checkbox with option "show all databases". I need this option to view databases other than default postgres.

![image](https://github.com/dbeaver/dbeaver/assets/160827263/0ab4f197-87e1-4b4d-8fa9-c7294892c44e)

### DBeaver Version

Community Version 23.3.5.202402181738

### Operating System

Mac

**Comment by aamsur-933** [comment]
Hello @kuodebbie  

just my 2 cent, in dbeaver v23.3.5 ubuntu 20.04 you can see the **Show all databases** checkbox in **Main** tab

![Screenshot from 2024-02-22 14-04-35](https://github.com/dbeaver/dbeaver/assets/74174455/8641d1ce-c963-4d58-80c1-44a6c3420e31)

**Comment by kuodebbie** [comment]
Thanks. I was checking the old documents. I am closing this defect myself
