### ISSUE TITLE
Can't type on remote desktop Windows Server 2022 on Azure from MacOS

### ISSUE THREAD

**Issue by JorgeGarciaEnki** [dbeaver/dbeaver#22928]
### Description

Hello,

I am experiencing the following problem:

I have a table where I store SQL queries to later be used in an ETL process.

When I try to edit any of the queries stored in the table, with right click > Edit > Edit cell it does not allow me to write anything in the edit box, it only allows me to delete content with backspace or the delete key, but it does not allow me to make any modifications to the text of the query.

I am connecting via RDP to a virtual machine with Windows server 2022 in Azure from the MacOS RDP client.

Any clue?

Thanks.

### DBeaver Version

Any CE

### Operating System

MacOS Sonoma 14.3.1

### Database and driver

SQL Server 2022 installed locally

### Steps to reproduce

1. Store a query on a table
2. select the table content
3. edit the query from the editor

**Comment by LonwoLonwo** [comment]
Hello @JorgeGarciaEnki 

Please provide a video of your issue.

**Comment by JorgeGarciaEnki** [comment]
I think I found the problem.

For some reason, the length for the column where we save the query list changed when the backup is generated from a TEXT(MAX) to TEXT(19) causing the error.

Thanks.

**Comment by Destrolaric** [comment]
@JorgeGarciaEnki Hi, is the issue still reproducible?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
