### ISSUE TITLE
Results returning SQL Statement

### ISSUE THREAD

**Issue by Datatatata** [dbeaver/dbeaver#22920]
### Description

Hi,
I have a problem since recently that when executing a statement the result tab appear showing the SQL statement I executed instead of extracting data. Would anyone know how to fix this?
![Dbeaver bug](https://github.com/dbeaver/dbeaver/assets/160870529/0a98d00c-de52-4f57-8310-efc440ab30b8)

### DBeaver Version

21.0.1

### Operating System

Windows 64-bit operating system, x64-based processor

### Database and driver

Vertica ADB

**Comment by E1izabeth** [comment]
Could you try clicking on this arrow?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/65ab6e97-90dc-4219-8604-079a57d1d738)

**Comment by Datatatata** [comment]
Hi Elizabeth, 
thanks for indicating the arrow, it seems that I have an access issue as I get the message that my username "does not have privileges to execute 'SELECT' on: adb.f_cases"
![image](https://github.com/dbeaver/dbeaver/assets/160870529/da496b51-4458-4444-abc8-100bf32409a5)

However I can open the data table and see all information:
![image](https://github.com/dbeaver/dbeaver/assets/160870529/fb2bb84e-e217-4940-bbc5-76d0c53e7ea5)

**Comment by E1izabeth** [comment]
I suppose you clicked the Collapse arrow accidentally some time ago, that's why the left-side area was collapsed.
The issue is solved now, right?

**Comment by Datatatata** [comment]
Yes I think it is fine now, thanks Elizabeth =) !
