### ISSUE TITLE
Usability improvement for saving SQL when closing DBeaver

### ISSUE THREAD

**Issue by johnrix** [dbeaver/dbeaver#22926]
**Is your feature request related to a problem? Please describe.**
When closing DBeaver, you are first prompted with the 'Are you sure?' dialog box. On clicking 'Yes', if there are unsaved SQL Editors open, you are then prompted whether you want to save them or not. At this point, the "Don't Save" button is in the same position as the "Yes" button was a moment ago. If you are are in a hurry/not paying attention and just click again, you can end up losing work rather than saving it.

**Describe the solution you'd like**
Swapping the positions of the buttons on one or other dialog box would avoid this.

**Describe alternatives you've considered**
Paying more attention when closing DBeaver 🤣

**Additional context**
Windows 11, DBeaver version 23.3.5

![image](https://github.com/dbeaver/dbeaver/assets/12581569/70e37937-b2f1-4f09-9cd3-f793fba114fd)

**Comment by E1izabeth** [comment]
Thank you for the idea.

As a workaround, you can turn auto-save editor settings on
![2024-02-21 11_44_25-Preferences](https://github.com/dbeaver/dbeaver/assets/45152336/79426eb6-41c3-4d7d-a006-7f2e6c2ea1dd)

**Comment by johnrix** [comment]
Thanks @E1izabeth, that's a good suggestion. Switching off the close confirmation prompt would also solve it admittedly!

**Comment by E1izabeth** [comment]
We have reviewed your proposal and we have decided that we do not want to implement it at this time. The default order of the buttons on our platform is from left to right, with "yes", "no", and then "cancel". Additionally, we usually use this order in most of our dialogues, so it would be an arguable change to make.

**Comment by johnrix** [comment]
No problem, thanks @E1izabeth. The alternative suggested above works well enough in any case.
