### ISSUE TITLE
Disable Trigger(s) not available in contextual menu for Oracle

### ISSUE THREAD

**Issue by 4javier** [dbeaver/dbeaver#22934]
### Description

It looks like a partial regression from a feature added some years ago
https://github.com/dbeaver/dbeaver/issues/11312

In particular I can see the `Tools → Enable triggers` entry for already disabled triggers
![immagine](https://github.com/dbeaver/dbeaver/assets/459381/d2d81b9c-6f91-4603-b44d-1e483ee6eb29)

But not its counterpart for disabling enabled ones
![immagine](https://github.com/dbeaver/dbeaver/assets/459381/deecef6d-80f2-4c09-8072-e3babfef9506)

### DBeaver Version

Community Edition 23.3.4

### Operating System

Arch Linux 6.7.5

### Database and driver

DB Oracle 11.2.0.1.0
Driver Oracle JDBC

**Comment by LonwoLonwo** [comment]
Thanks for the report @4javier
