### ISSUE TITLE
Lose the button of "Install new software"--23.3.5

### ISSUE THREAD

**Issue by qilinsanshao** [dbeaver/dbeaver#22933]
### Description

Hello:
When I upgrade the new version 23.3.5 Dbeaver across the way of ZIP pacakge, It looks the button of "Install new sofeware" lost.
![image](https://github.com/dbeaver/dbeaver/assets/63779854/dfbd4709-a221-4343-bde3-4ca754ee9fdd)

### DBeaver Version

DBeaver Community 23.3.5

### Operating System

Win 11

**Comment by E1izabeth** [comment]
Seems `Check for Updates` button is missing in your case too
![image](https://github.com/dbeaver/dbeaver/assets/28875055/62ac2960-226b-456c-b661-f94b975835cf)

**Comment by qilinsanshao** [comment]
> Seems `Check for Updates` button is missing in your case too ![image](https://private-user-images.githubusercontent.com/28875055/307382348-62ac2960-226b-456c-b661-f94b975835cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTQ0ODIsIm5iZiI6MTcwODkxNDE4MiwicGF0aCI6Ii8yODg3NTA1NS8zMDczODIzNDgtNjJhYzI5NjAtMjI2Yi00NTZjLWI2NjEtZjk0Yjk3NTgzNWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAyMjMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNDA3OTllZGQwODNkZTY4ZThmNWIzMWEzMGI3ZDRkNjA3MTRmZmQyNzZmNGNhY2Q4YWI3NDU2YTBiYTFhMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s8ZA57LxHVAsw9WfGqCsEAR_BCCY3WcLvyDYSrLRj7M)
You are right. the button of 'Check for updates' is also missing.Not sure if it is a bug or not.

**Comment by LonwoLonwo** [comment]
Hello @qilinsanshao 

Could you please try to do this? https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings

**Comment by qilinsanshao** [comment]
I am afraid it lead to risk of losing my configration if I do like this...
I will check it with next version if no better way
thanks!

**Comment by E1izabeth** [comment]
Have you installed DBeaver on your own? Do you have this argument `-Dpolicy.software.install.disabled` in the dbeaver.ini file?

**Comment by qilinsanshao** [comment]
hi E1izabeth. Sorry that Ididn't find the configuration you mentioned in the dbeaver.ini file...
![image](https://github.com/dbeaver/dbeaver/assets/63779854/0b3e9de3-8bc6-4168-9f96-bdc742abf823)

**Comment by E1izabeth** [comment]
Thank you

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? During the dialog opening without buttons. You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.
And, please, do it on the last DBeaver version.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by qilinsanshao** [comment]
Sorry to respose late. Have no issue with verision 24.0.2
