### ISSUE TITLE
dbeaver continually crashes

### ISSUE THREAD

**Issue by colinwerner** [dbeaver/dbeaver#22946]
### Description

I have been experiencing a number of crashes that started last week when I was doing a lot of work with ERDS -- and selecting tables to include in the ERD.

Now when I try to switch to other tabs, the whole things crashes.

### DBeaver Version

Community 23.3.5

### Operating System

Ubuntu 22.04.4

### Database and driver

Postgres 12
jdbc

### Steps to reproduce

Open dbeaver
select SQL editor tab
<kaboom>
[hs_err_pid281098.log](https://github.com/dbeaver/dbeaver/files/14389219/hs_err_pid281098.log)

**Comment by serjiokov** [comment]
Extracted from dump:

Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libgobject-2.0.so.0+0x3dfc1]  g_type_check_instance_is_fundamentally_a+0x11

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 10363  org.eclipse.swt.internal.gtk.OS.g_object_set(J[BJJ)V (0 bytes) @ 0x00007f87dd1413fb [0x00007f87dd1413a0+0x000000000000005b]
J 9888 c1 org.eclipse.swt.widgets.Tree.cellDataProc(JJJJJ)J (486 bytes) @ 0x00007f87d6256cf4 [0x00007f87d6256560+0x0000000000000794]


in /snap/dbeaver-ce/285/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 at 0x00007f87c045b000

**Comment by colinwerner** [comment]
Now dbeaver won't even start... I am going to nuke it and reinstall.

**Comment by E1izabeth** [comment]
Please let us know if reinstall helps

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
