### ISSUE TITLE
SQL Editor "Copy as source code" shortcut doesn't work

### ISSUE THREAD

**Issue by flachtiago** [dbeaver/dbeaver#22940]
### Description

Select SQL in editor, press CTRL+Shift+C.
The "Choose Format" window is not shown, nor the selected sql section is copied.
If, otherwise, we right-click "Copy as source code" in the context menu, wich states CTRL+Shift+C as shortcut, everything works as expected.

### DBeaver Version

Community Edition 23.3.5.202402181738

### Operating System

Windows 

### Database and driver

Intersystems Caché, PostgreSQL, Oracle...  The same behavior, regardless of the driver used.

### Steps to reproduce

Select SQL in editor, press CTRL+Shift+C.
The "Choose Format" window is not shown, nor the selected sql section is copied.

**Comment by E1izabeth** [comment]
Hmm.. I can't reproduce it.
Do you use qwerty keyboard?

**Comment by flachtiago** [comment]
> Hmm.. I can't reproduce it. Do you use qwerty keyboard?

Yes. My coworkers report the same behavior. It's not only with me.

**Comment by flachtiago** [comment]
@E1izabeth, I upgraded to version 24 and now it is working again. The same with my coworkers. Everything is just like it's supposed to be. Thanks.

**Comment by flachtiago** [comment]
@E1izabeth, I upgraded to version 24 and now it is working again. The same with my coworkers. Everything is just like it's supposed to be. Thanks.

**Comment by E1izabeth** [comment]
Thank you for update
