### ISSUE TITLE
"Link with editor" doesn't work for connections in a subfolder

### ISSUE THREAD

**Issue by kseniaguzeeva** [dbeaver/dbeaver#22956]
### Description

Link with editor doesn't work for connections in a subfolder

### DBeaver Version

CE Version 24.0.0.202402261217

### Operating System

Win10

### Steps to reproduce

1. Create a folder in DB Navigator, create another folder in it and place a connection in the subfolder
2. Open a database object of the connection in the Metadata Editor (e.g. a table)
3. Relaunch DBeaver, be sure that the connection is established, place focus on the opened object and press "Link with editor" in the Navigator top toolbar

AR: no changes
ER: the opened database object is found and displayed in the Navigator tree

Workaround: expand the folder and repeat the action.

https://github.com/dbeaver/dbeaver/assets/112612526/6a942a72-16da-4048-af56-efb232047e9b

**Comment by flambchap** [comment]
Increasing priority: This button plays a major role in navigating between navigator objects and tabs when many tabs are open.

**Comment by E1izabeth** [comment]
Maybe it's related to dbeaver/pro#2031, dbeaver/pro#1944
