### ISSUE TITLE
Error code ORA-17820 when attempting to connect to database

### ISSUE THREAD

**Issue by mkeb1** [dbeaver/dbeaver#22958]
### Description

When we attempt to connect to a database, an error with the code ORA-17820 is produced (screenshot below). This has been reproducable on three separate computers, all of which run Windows 11 OS.
We have already tried newly setting up the computer and resetting the user profile, but the error persists.

However, on another different computer, also running Windows 11, the error was _not_ produced.

What exactly is the issue and how do we solve it?

Screenshot of error message:
![fehlermeldung](https://github.com/dbeaver/dbeaver/assets/105415763/6a9f2f72-1268-4876-abe4-23b9391794ba)

Text copied from error log files:
[error log.txt](https://github.com/dbeaver/dbeaver/files/14405848/error.log.txt)

### DBeaver Version

Community Edition 23.3.3

### Operating System

Windows 11

### Database and driver

- Oracle database
- Oracle JDBC Driver

**Comment by ShadelessFox** [comment]
Hello @mkeb1,

It seems to be local network issue because DBeaver can't access the database. Please contact your system administrator.

**Comment by nicodtkomgo** [comment]
I've the same issue. 
I'm using Windows 11 
on the same network with a MAC I'm able to connect

**Comment by iggusti** [comment]
I've the same issue.
I'm using Windows 11

**Comment by aroguszny** [comment]
I've the same issue. Everything works fine on sqldeveloper.

**Comment by francescoPadovani81** [comment]
Same here.
And for me too, everything works fine with both sqldeveloper and sqlplus command.

**Comment by HohesP** [comment]
Same issue using DBeaver CE 24.0.0.202403040957 from microsoft store in windows 11.
Everythings works fine using postgres or mysql connections.
No issue under windows 10 using same DBeaver CE Version from microsoft store.

**Comment by E1izabeth** [comment]
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\.metadata directory. In case your OS isn't Windows, here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by HohesP** [comment]
[.log](https://github.com/dbeaver/dbeaver/files/14835738/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/14835739/dbeaver-debug.log)
Log files using DBeaver CE 24.0.1.202403241445 from microsoft store in windows 11. 
I hope the files will help to analyse the issue.

**Comment by LonwoLonwo** [comment]
Hello @mkeb1 

Please check these:

- Make sure your tnsnames.ora is complete and has the databases you wish to connect to
- Make sure you can tnsping the server you wish to connect to
- On the server, make sure it will be open on the port you desire with the specific application you use.

**Comment by gkellerer** [comment]
we have the same issue on to windows 11 computers - one is a store installation and the other is a normal install.

**Comment by rodpinst** [comment]
Same here Windows 11 DBeaver 24.0.2.202404071719 (From Windows Store) Oracle JDBD Driver 23.2.0.0 not working

On Windows 10 DBeaver 24.0.2.202404071654 works fine.

Same network.

**Comment by tanelkaar** [comment]
For me restarting dbeaver solves the issue. Usually appears when the computer wakes from sleep / hibernate. In some cases the error is different: ORA-17800: Got minus one from a read call. (CONNECTION_ID=ItOGRxtsQqyb8yLygttgog==

Windows 10, DBeaver 24.0.2.202404071654

**Comment by NadChel** [comment]
I had this issue too. Had to download SQL Developer to connect to an Oracle db. It was fine just yesterday

Unfortunately, I'm not sure what steps are required to reproduce the issue. My coworkers don't have it

I have a bootleg Windows 10 x64. Others have too, though

A localized error message:
```lang-none
ORA-17820: Сетевому адаптеру не удалось установить подключение (CONNECTION_ID=xAWNLkmPSMexlDZPKkDVhQ==)
ORA-17820: Сетевому адаптеру не удалось установить подключение (CONNECTION_ID=xAWNLkmPSMexlDZPKkDVhQ==)
```

**Comment by serjiokov** [comment]
Hello, after internal discussion we need to ask a particular windows version, driver version and database version.

**Comment by gkellerer** [comment]
Tested with Windows 11 (11h2), Oracle Database 19c and oracle client 12.2 and 19c)


Hello, after internal discussion we need to ask a particular windows version, driver version and database version.

**Comment by aroguszny** [comment]
It seems the problem lies with DBeaver installed from the Microsoft Store. It started working after I removed it and installed it again using the file from the website

**Comment by NadChel** [comment]
> It seems the problem lies with DBeaver installed from the Microsoft Store. It started working after I removed it and installed it again using the file from the website

I downloaded DBeaver from the DBeaver website, not Windows Store

**Comment by aroguszny** [comment]
> > It seems the problem lies with DBeaver installed from the Microsoft Store. It started working after I removed it and installed it again using the file from the website
> 
> I downloaded DBeaver from the DBeaver website, not Windows Store

I'm sorry to hear that. Well, my problem has been resolved after fresh install.

**Comment by Destrolaric** [comment]
`-Djava.net.preferIPv4Stack=true`
Can anyone having this issue add this argument to `dbeaver.ini` and see if it will work?
@aroguszny

**Comment by jvmbatista** [comment]
I also have problems getting the one from windows store to work. I've looked at the ini files to try and add that command to it but I noticed a small difference between files(also, couldn't edit ini from WindowsStore):

Installer from the website:
plugins/org.jkiss.dbeaver.launcher_1.0.3.202404211624.jar

Installer from WindowsStore:
plugins/org.eclipse.equinox.launcher_1.6.800.v20240426-1701.jar

everything else is the same besides:
-Ddbeaver.distribution.type=exe

Also noticed one of the shortcuts has a few extra params:
-nl en

edit: Tried the one from window store in the installer one and works fine
Also did a comparison between folders and these are the differences
![image](https://github.com/dbeaver/dbeaver/assets/7399523/5c580c07-85d5-467a-8fb9-91d524e3da79)

Let me know if there's any specific file you guys wanna check the difference

**Comment by ShadelessFox** [comment]
It seems that the issue can be solved by adding the following VM parameter:

```
-Djava.net.preferIPv4Stack=true
``` 

Unfortunately, it's impossible to even confirm that this solves the issue as the windows store directory and all contained files are protected and can't be edited.

**Comment by jvmbatista** [comment]
> It seems that the issue can be solved by adding the following VM parameter:
> 
> ```
> -Djava.net.preferIPv4Stack=true
> ```
> 
> Unfortunately, it's impossible to even confirm that this solves the issue as the windows store directory and all contained files are protected and can't be edited.

Can't that just be an update from the store?

Anyway, I was a bit surprised when I check the differences between them. Was expecting to have the same files and versions everywhere...

24.1.0 hasn't popped up for me yet, maybe a last minute change to that ini file ?!?

**Comment by AbdealiLoKo** [comment]
I had the same issue - a new laptop. Windows 11.
When I installed from store I saw the same issue with oracle (all other DBs worked). Installing it from the website fixed it just like @aroguszny mentioned:

> It seems the problem lies with DBeaver installed from the Microsoft Store. It started working after I removed it and installed it again using the file from the website

(My earlier Win 10 with store install had no issues.)
Thanks !

**Comment by jvmbatista** [comment]
Just an update, still having the error with latest version (24.1.1)
ORA-17820: The network adapter could not establish the connection. (CONNECTION_ID=...)

I've looked at the ini file and proposed param is not there.

PS: For some reason the refresh didn't refresh the page, just noticed it was pushed for 24.1.2

**Comment by jvmbatista** [comment]
Still happening for me. 
Tried auto and ipv4 and still get the same error.

![image](https://github.com/user-attachments/assets/677e1c82-7c4f-48b2-a7d1-24093405466d)

![image](https://github.com/user-attachments/assets/9912d4c2-1132-49dc-b577-f8108d7e6f90)

**Comment by HohesP** [comment]
We were able to solve the problem using DBeaver from microsoft store in windows 11.
Cause is not the ip4|6 settings but the version of the oracle driver.

Go to connection settings -> click edit driver settings -> go to register libraries -> click download/update -> then choose a version under 23.* for example 21.14.x (see also screenshot) and click download.
![image](https://github.com/user-attachments/assets/2383cd02-493d-4290-8172-2c32d02b17df)

If you connect to the oracle database dbeaver ask you for new driver version check. You can disable the check on the global settings under connection -> driver.

I hope it helps.

**Comment by jvmbatista** [comment]
> We were able to solve the problem using DBeaver from microsoft store in windows 11. Cause is not the ip4|6 settings but the version of the oracle driver.
> 
> Go to connection settings -> click edit driver settings -> go to register libraries -> click download/update -> then choose a version under 23.* for example 21.14.x (see also screenshot) and click download. ![image](https://private-user-images.githubusercontent.com/97506694/350978200-2383cd02-493d-4290-8172-2c32d02b17df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTU2NTAsIm5iZiI6MTcyMTY1NTM1MCwicGF0aCI6Ii85NzUwNjY5NC8zNTA5NzgyMDAtMjM4M2NkMDItNDkzZC00MjkwLTgxNzItMmMzMmQwMmIxN2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDEzMzU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NjY1MDdmNTk0YTNkY2Y3OGQzOWVlNTU2NWE5N2JmN2RmY2IzZDEzMTMxNjlkMDI3MTM5N2I3OGMwNzM1MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T7ARo7KxGcS_RYw77qWfwBm4bY7pZBoCYelXJ1ir6M0)
> 
> If you connect to the oracle database dbeaver ask you for new driver version check. You can disable the check on the global settings under connection -> driver.
> 
> I hope it helps.

Thank you, that solved the issue...

**Comment by HohesP** [comment]
The problem no longer occurs using DBeaver CE 25.1.0 and Oracle driver version 23.8.0.25.04
The workaround is no longer required.

**Comment by pasisavolainen** [comment]
I had an installation of DBeaver from spring (windows store updated to 25.1.3) and it didn't want to update to newer (23.8) oracle driver series by simple 'download/update', I had to explicitly select the 23.8 (like in the workaround).
New 'portable' installation of 25.1.4 worked correctly.

Ran into this with F5 Network Access VPN

**Comment by treyhodgsonbkv** [comment]
I ran into this issue today when trying to connect to an Oracle database.  Certain combinations of DBeaver CE & Oracle driver just cannot successfully connect.

DBeaver CE Version 25.2.3.202510191709 + Oracle driver 23.2.0.0
>>> failed with message "ORA-17820: The network adapter could not establish the connection. (CONNECTION_ID=UrnJ7mPLSYafd+iI0v7/cg==)"

DBeaver CE Version 25.2.3.202510191709 + Oracle driver 23.9.0.25.07
>>> successfully connected
