### ISSUE TITLE
Chinese characters is garbled in longblob type fields

### ISSUE THREAD

**Issue by Duo123shy** [dbeaver/dbeaver#22964]
### Description

Chinese characters is garbled in longblob type fields when I execute the query。

### DBeaver Version

  DBeaver	23.3.5

### Operating System

Windows10

### Database and driver

MySQL   mysql-connector-j-8.2.0,jar

### Steps to reproduce

![info1](https://github.com/dbeaver/dbeaver/assets/161436000/349e9c26-f355-478c-86f0-a5875db2f392)
![info2](https://github.com/dbeaver/dbeaver/assets/161436000/7e3942ce-a901-4de0-9332-206e28198752)

**Comment by ShadelessFox** [comment]
Hello @Duo123shy,

Have you tried setting encoding during the export to match the table column's collation?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
