### ISSUE TITLE
script associate with multiple connections

### ISSUE THREAD

**Issue by szylmzs** [dbeaver/dbeaver#22980]
how to make a script associate with multiple connections

**Comment by E1izabeth** [comment]
Please add more details to your request. Why you may need it? What is the use case?

**Comment by szylmzs** [comment]
> Please add more details to your request. Why you may need it? What is the use case?

I want to execute a script which select from different mysql servers

**Comment by E1izabeth** [comment]
Is it possible in mysql? Could you provide any documentation article?

**Comment by szylmzs** [comment]
> Is it possible in mysql? Could you provide any documentation article?

feature like linkedserver in mssql

**Comment by szylmzs** [comment]
> > Is it possible in mysql? Could you provide any documentation article?
> 
> feature like linkedserver in mssql

maybe dblink will solve my issue

**Comment by LonwoLonwo** [comment]
Hello @szylmzs 

Still, it is unclear how it should work.
What behavior do you expect after a query execution? A question about where we need to execute your query: in which data source? 

Also, you can change your data source at any moment with this button:

![2024-03-13 16_54_09-DBeaver Ultimate 24 0 0 - _MySQL 5 5 1_ Script-83](https://github.com/dbeaver/dbeaver/assets/45152336/edbfe48d-d66b-447a-9376-7ac657db6c86)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
