### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Siva0902** [dbeaver/dbeaver#22996]
### Description

I have issues connecting to Postgres via DBeaver . Please let me how to resolve this
![Screenshot ![Screenshot (61)](https://github.com/dbeaver/dbeaver/assets/161642660/65d6d216-c225-4e07-b10e-c2809308f2ff)61)](https://github.com/dbeaver/dbeaver/assets/161642660/aca3b201-ca90-4ccd-8c04-39e75a8c5233)

### DBeaver Version

23.2.0

### Operating System

Windows 10

**Comment by LonwoLonwo** [comment]
Hello @Siva0902 

Do you have Kerberos authentication? SSPI?
In this case, I can recommend you try our [PRO products](https://dbeaver.com/trial/), which supports these authentication types.

Or you need to configure your connection with specific driver properties, you can find the list in the "driver properties" tab.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
