### ISSUE TITLE
CSV value with comma inside double quotes treated as separator

### ISSUE THREAD

**Issue by mikebridge** [dbeaver/dbeaver#22998]
### Description

I am importing a file with a field

`"test, 123"`

It is being treated as two fields, splitting on the comma, even though I have:

`Column Delimiter`: `,`
`Quote Char`: `"`

I even copied-and-pasted the quotes from the file to make sure I had the right one.

### DBeaver Version

23.3.5 community

### Operating System

MacOS 14.3.1

**Comment by Matvey16** [comment]
@mikebridge Can you specify more info for this case. What else is in this csv file? Is this field a column name or part of data? So where did you find out it is treated as 2 fields and not one?

In my case where this is the only data in csv file
![Notepad_4YXDeseIGD](https://github.com/dbeaver/dbeaver/assets/82543000/2dd13ee6-7ff6-4bbe-abef-d17cf2e073c0)

It is correctly recognised as the name of only one column
![dbeaver_t0CODWeUw2](https://github.com/dbeaver/dbeaver/assets/82543000/3b777f48-ad40-46c2-9984-26e60011570e)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by mikebridge** [comment]
@Matvey16 @E1izabeth Sorry, yes, here's what I did:

```
innodb_version	5.7.43
protocol_version	10
slave_type_conversions	
tls_version	TLSv1,TLSv1.1,TLSv1.2
version	5.7.43
version_comment	MySQL Community Server (GPL)
version_compile_machine	aarch64
version_compile_os	Linux
```

```sql
CREATE TABLE `test_table` (
  `foo` varchar(100) DEFAULT NULL,
  `bar` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

- Control-Click on `test_table` to bring up the menu
- Select "Import data" and then "CSV/Import from CSV file(s) and click "Next >"
- Select my csv file that has one line `"test, 123"` in it.
- Verify that the "column delimiter" is a comma `,`
- Verify that the quote character is the double quote `"`
- Click "Next >"
- Click on the filename---you can see that it sees the value as one value, `"test, 123"`, not two values.


<img width="854" alt="Screenshot 2024-04-25 at 11 14 04 AM" src="https://github.com/dbeaver/dbeaver/assets/213273/b4a2828c-91fe-48bb-881e-d0bd4b2f00d8">

I don't see a way to separate these out into two.  This is a minimal example, but the real-world examples also happen when I have column headers in the CSV file.

Here are my import settings:

<img width="850" alt="Screenshot 2024-04-25 at 11 17 39 AM" src="https://github.com/dbeaver/dbeaver/assets/213273/59694d3f-5e2b-486a-a244-45bc4bb35262">

**Comment by mikebridge** [comment]
@Matvey16 @E1izabeth Sorry, yes, here's another example with DBeaver 24.0.0.  I wasn't able to reproduce my original test case, but was able to reproduce it with this:

`one-column.csv`:
```
foo,bar
"test, 123",456
```
With this DB:
```
innodb_version	5.7.43
protocol_version	10
slave_type_conversions	
tls_version	TLSv1,TLSv1.1,TLSv1.2
version	5.7.43
version_comment	MySQL Community Server (GPL)
version_compile_machine	aarch64
version_compile_os	Linux
```
Here's the DDL:
```sql
CREATE TABLE `test_table` (
  `foo` varchar(100) DEFAULT NULL,
  `bar` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
To reproduce:
- Control-Click on `test_table` (after Refreshing) to bring up the menu
- Select "Import data" and then "CSV/Import from CSV file(s) and click "Next >"
- Select my csv file from above.
- Verify that the "column delimiter" is a comma: `,`
- Verify that the quote character is the double quote: `"`
- Click "Next >"
- Click on the filename---here it seems to be splitting on the first comma and ignoring the quotes:

<img width="845" alt="Screenshot 2024-04-25 at 11 26 44 AM" src="https://github.com/dbeaver/dbeaver/assets/213273/f38fb5b4-dcdf-4875-a0bc-fee731fb8b43">


Here are the import settings
<img width="850" alt="Screenshot 2024-04-25 at 11 17 39 AM" src="https://github.com/dbeaver/dbeaver/assets/213273/727f6481-6a90-48de-b765-21a6b16b6fd6">

**Comment by mikebridge** [comment]
Ah, wait, the problem may be with the headers---if I put each column name in quotes it seems to work.

I have CSV files where these fields have quotes only when "necessary", e.g. if there's a comma.

**Comment by Matvey16** [comment]
I'm sorry. I still wasn't able to reproduce this. Whis your step dbeaver for me shows the creation of two columns which are foo and bar. Your example seems strange in another way. If the quotes were ignored then the error would have been in the imported data (according to contents of the csv file where the comma inside the quotes is part of the data and not the header). But on the screenshot of your result it seem the entire header is ignored and the second row with data is used as the header for column names.

Can you try using exactly this file as an import source and tell how it goes?
[test1.csv](https://github.com/dbeaver/dbeaver/files/15403951/test1.csv)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
