### ISSUE TITLE
existing roles password change

### ISSUE THREAD

**Issue by jgrover21** [dbeaver/dbeaver#22997]
### Description

I created a user role in dbeaver for Azure postgresql data base.  User forgot password.  How do I change their password.  this role has created on table that he owns.  becuase of that I can not even delete him to recreate user role.

### DBeaver Version

dbeaver 23.0.1

### Operating System

Windows

### Database and driver

Azure postgresql

**Comment by LonwoLonwo** [comment]
Hello @jgrover21 

Did you try the [standard PostgreSQL query](https://www.postgresql.org/docs/current/sql-alterrole.html)?

`ALTER ROLE davide WITH PASSWORD 'hu8jmn3';`

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by naxim92** [comment]
How can I change password with UI?

**Comment by E1izabeth** [comment]
It's not possible now
