### ISSUE TITLE
Snappified version of DBeaver

### ISSUE THREAD

**Issue by 124603ac** [dbeaver/dbeaver#2299]
Hi, 
I would like to push for a Snap package (snapcraft.io). This would allow for automatic updates, no dependency issues, and the possibility to rollback to a previous version in case anything goes wrong. 

Thanks for considering this.

**Comment by serge-rider** [comment]
Sounds like a good alternative for Ubuntu PPA (#1667).

**Comment by zendre4** [comment]
+1

**Comment by vlachmilan** [comment]
+1

**Comment by TerkiKerel** [comment]
Also would be great if we can have a nix package too.

**Comment by thomaszbz** [comment]
It would be great to have the snap package provided in an official manner. In particular, it should be avoided that some random guy provides this package because nobody knows what the build looks like under the hood (catchword: trusted build).

**Comment by benyanke** [comment]
Yes - also, if it's provided as part of Travis, it gives the ability to try our builds of the edge branch, using the --edge channel, which can be nice if you want to test prereleases but not have to always manually rebuild.


I know I'd probably commit to using --edge day to day if it were a snap, since it would need no extra work - it would automatically update to the latest dev branch commits every night.

I'd also love to see this work. Tag me in if you need any help.

**Comment by rockenbauerjonas** [comment]
+1

**Comment by serge-rider** [comment]
Snap is tricky.. Moving forward.

**Comment by nestor-custodio** [comment]
Almost two whole years later, this remains the single most thumbed-up issue on the repo. If there is anything at all we can do to help make this happen, please let us know.

Let's see if we can get this snap out there and give DBeaver one more distribution channel!

**Comment by serge-rider** [comment]
We tried it one more time. But there are a few blockers with Java and Eclipse packaging.
By some reason snappified version don't start from snap folder and it hangs during app loading.
We'll make another try after 6.3.

If anybody has experience in Java apps packaging for snap - please write me on serge@jkiss.org.

**Comment by nestor-custodio** [comment]
Thank you for looking into this again, @serge-rider . We do appreciate it.

**Comment by serge-rider** [comment]
It seems to be working. Finally.
We'll publish 6.3.1 in new Snap build.

**Comment by benyanke** [comment]
YES

**Comment by 124603ac** [comment]
I just wanted to thank you for implementing this. It's great to have DBeaver in the Snap store, very useful. 

Thanks!

**Comment by Jens2205** [comment]
For raspberry pi only 5.2.4 is available via snap and poorly it is not working. Is it possible to provide the latest version also for this environment? 

Thanks in advance!
