### ISSUE TITLE
Removing Window Titles On Connection Windows Breaks Keepass Compatibility

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#22999]
**Is your feature request related to a problem? Please describe.**
In a recent update DBeaver has stopped to set the window title for the connection popup window. This breaks compatibility with KeepassXC, as it relies on window titles for non-browser windows.

**Describe the solution you'd like**
Re-add Window Titles to the connection/authentication window.

**Describe alternatives you've considered**
Direct Keepass integration, although that might be too much.

**Additional context**
The below window used to have a title, which allowed KeepassXC's autotype feature to pick it up:
![image](https://github.com/dbeaver/dbeaver/assets/25014890/1a855048-3408-4728-92d0-a90af3da0e42)

**Comment by LonwoLonwo** [comment]
Hello @Slade0120 

Thanks for noticing.
This issue is already fixed: https://github.com/dbeaver/dbeaver/issues/22766
Please check the latest DBeaver version.

**Comment by ghost** [comment]
Thank you, I will wait for the AUR repository to update then!
