### ISSUE TITLE
apply "connection type" color to tab

### ISSUE THREAD

**Issue by jeanrajotte** [dbeaver/dbeaver#23018]
**Is your feature request related to a problem? Please describe.**

I understand that connection type with a color is a way to distinguish which of the tabs is associated with what connection.  IMO, seeing the background of the panel is less useful that seeing the color on a tab.  The tab allows me to go where I want to go. A colored tab would be enough. The color in the background of the panel make it harder to use.   

**Describe the solution you'd like**

Whether you keep the panels' background color matching the connection is not important.  CHANGING the color of the tab is what I'm suggesting would be a great help.

**Describe alternatives you've considered**
N/A

**Additional context**

The "orange" on this panel is less useful to me than setting the background color on the circled "Account" tab would be.

![image](https://github.com/dbeaver/dbeaver/assets/312996/3bb5d9f2-8c04-4c4b-a0e8-7806dc2849f6)

**Comment by LonwoLonwo** [comment]
Hello @jeanrajotte 

Thanks for the idea.

We already have a similar ticket here: https://github.com/dbeaver/dbeaver/issues/16827 
You can vote for them with 👍 emoji
