### ISSUE TITLE
Syntax highlighting doesn't work after the SELECT UNIQUE statement

### ISSUE THREAD

**Issue by VadimMuhtarov** [dbeaver/dbeaver#23021]
### Description

Syntax highlighting does not work after the SELECT UNIQUE statement in Oracle database
<img width="417" alt="Screenshot 2024-03-01 at 11 00 57" src="https://github.com/dbeaver/dbeaver/assets/17072773/9836476b-a05c-4e54-9d9b-9fad75a4fbc4">

### DBeaver Version

23.3.5

### Operating System

Sonoma 14.3.1

### Database and driver

Oracle 19.8.0
DBeaver Oracle Model	2.1.210.202402181738	org.jkiss.dbeaver.ext.oracle

### Steps to reproduce

Use the SELECT UNIQUE statement

**Comment by VadimMuhtarov** [comment]
Also something wrong with syntax in the WHERE statement

**Comment by E1izabeth** [comment]
Thank you for bug report.
