### ISSUE TITLE
Cannot stay connected to MySQL server w/ a SSH tunnel

### ISSUE THREAD

**Issue by JiDW** [dbeaver/dbeaver#2302]
Hello,

When I try to connect to my MySQL database server with a SSH tunnel, I get an error just after the connection. The same settings works in others softwares (heidi, navicat).

Here is what happens when I test the connection: 
http://www.serenity-ff.com/images/screenshots/screenshot1507624096.jpg

And immediately after, this error occurs:
http://www.serenity-ff.com/images/screenshots/screenshot1507624157.jpg

I am not "disconnected" from the server, but when I try to display the databases, the same occur occurs again and the databases can't be shown.

http://www.serenity-ff.com/images/screenshots/screenshot1507624406.jpg
http://www.serenity-ff.com/images/screenshots/screenshot1507624490.jpg

Am I going something wrong ? With Heidisql and Navicat, I use a PPK file, but I've read that I need a PEM file with DBeaver. It doesn't work anyway.

Regards.

**Comment by serge-rider** [comment]
Is MySQL server located on the same machine as SSH tunnel target?
If so - could you try to set server host name to `localhost` and check?

**Comment by JiDW** [comment]
Unfortunately no, it is not on the same server.

**Comment by serge-rider** [comment]
I can't reproduce that.
This error doesn't look like a problem with certificate file (connection error happens way before key auth).

If this works with Heidi (or in plain Putty/Plink) - please recheck connection properties in DBeaver. Generally if it works in Putty it has to work in DBeaver.

Standard workaround - configure tunnel in Putty and then configure connection to connect to some local machine port (the one you set in tunnel config in Putty).

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
