### ISSUE TITLE
Select field wrap

### ISSUE THREAD

**Issue by liuzhe101** [dbeaver/dbeaver#23039]
### Description

When writing SQL, select fields according to the prompts and position the cursor on the new line.
You can see issue #16838

### DBeaver Version

2023.3.3 DBeaver UE

### Operating System

macos 14.3.1

### Steps to reproduce

You can see issue #16838 ；
I know how to reproduce it. Copy a piece of sql and there is no space after t1.id     -》

select t0.name from ems_equipment t0
left join mfg_work_order t1 on t1.idwhere t0.is_deleted=0；

Then press Enter in the middle of t1.id to become-》

select t0.name from ems_equipment t0
left join mfg_work_order t1 on t1.id
where t0.is_deleted=0；
Then type four spaces in front of where to become --》

select t0.name from ems_equipment t0
left join mfg_work_order t1 on t1.id
    where t0.is_deleted=0
Then delete the .id of t1.id, and choose the id according to the t1. prompt, and the cursor will automatically be positioned on the new line.

Please fix it in time and push it to UE

https://github.com/dbeaver/dbeaver/assets/61652514/45a057fd-cb2b-4410-84ea-5fc0aba11aa6

**Comment by MashaKorax** [comment]
Thanks for your report, I reproduce the issue
