### ISSUE TITLE
datasource variable doesn't work in 

### ISSUE THREAD

**Issue by ElMads** [dbeaver/dbeaver#23041]
### Description

Using ${datasource} in shell commands doesn't resolve to the actual connection name/variable value. 
Using for example ${database} works fine. This happens for all 4 event types.
I recreated it using the following command on the Dbeaver Sample Database;
`cmd /C "echo DataSource=${datasource},DataBase=${database}  > C:\Temp\ShellCommands\BeforeConnect.log"`
![image](https://github.com/dbeaver/dbeaver/assets/144915169/efb083e8-ba14-47c7-a908-b2a4bf1d9cc7)
This gives the result;
![image](https://github.com/dbeaver/dbeaver/assets/144915169/ef244065-89f5-49d4-a3fe-b95a73f328db)

${datasource} appears to have a value in the dbeaver ui at least;
![image](https://github.com/dbeaver/dbeaver/assets/144915169/6f64dd1c-6ed9-43ac-9078-b8b6336c541d)

### DBeaver Version

Community Edition 24.0.0

### Operating System

Windows 11

### Database and driver

Tested it using Oracle, DB2, MSSQL and SQLite jdbc drivers. Doesn't seem to be driver specific.

### Steps to reproduce

1. Create sql lite sample database or create a connection to an existing database.
2. Create folder C:\Temp\ShellCommands(or modify the path in the next step)
3. Setup a "Before Connect" shell command;
`cmd /C "echo DataSource=${datasource},DataBase=${database}  > C:\Temp\ShellCommands\BeforeConnect.log"`
4. Connect and observe the output in the file.

**Comment by LonwoLonwo** [comment]
Hello @ElMads 
Thanks for the report.
We will check it.

Maybe this is a duplicate of https://github.com/dbeaver/dbeaver/issues/21396

**Comment by ElMads** [comment]
Could be, but I don't think so as this happens with already saved connections, even after restart of program.

**Comment by ElMads** [comment]
After reviewing kgns' comment on https://github.com/dbeaver/dbeaver/pull/22800 I think you are correct @LonwoLonwo

**Comment by LonwoLonwo** [comment]
The PR to fix this issue is already in the testing stage. I hope we fix it soon. I will add your case for testing cases.
