### ISSUE TITLE
mysql does not support executing multiple query statements at the same time and displaying the query results separately.

### ISSUE THREAD

**Issue by binbin5261** [dbeaver/dbeaver#23040]
mysql does not support executing multiple query statements at the same time and displaying the query results separately.

ver:24.0.0

**Comment by E1izabeth** [comment]
Please clarify your request.
What do you mean by "executing multiple query statements at the same time"? Is it about executing several statement by pressing one button or about parallel execution?
What do you mean by "displaying query results separately"?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
