### ISSUE TITLE
“network unavailable”

### ISSUE THREAD

**Issue by HIqbal123** [dbeaver/dbeaver#23044]
### Description

I'm a desktop engineer so my knowledge on this particular subject is minimal. a database team from one of my departments is using DBeaver with PowerBi when they try to open a database they are met with the error “network unavailable”.

### DBeaver Version

Community edition 23.3.5

### Operating System

windows 10

### Database and driver

PostgreSQL 14.10

### Steps to reproduce

try to connect to database via PowerBi

**Comment by HIqbal123** [comment]
We do use a proxy, I'm guessing when DBeaver tries to pull the repo from Github, our network doesn't allow it.

**Comment by LonwoLonwo** [comment]
Hello @HIqbal123 

Please provide clear steps to reproduce your issue.
Log files are also very welcome. 
You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by HIqbal123** [comment]
Hi please see error log attached
[DBeaver_error.log](https://github.com/dbeaver/dbeaver/files/14483788/DBeaver_error.log)

**Comment by LonwoLonwo** [comment]
And please provide clear steps to reproduce your issue.

**Comment by HIqbal123** [comment]
To reproduce the issue, please follow these steps:

1.Click on "New Database Connection" option on the DBeaver Application.
2.Select "PostgreSQL" from the list of available databases.
3.Fill in the required connection details such as host, port, username, and password.
4.Once the connection details are filled, proceed to the next step.
5.On the connection settings page, locate and select the "Driver Properties" tab as shown below.
6.Upon selecting the "Driver Properties" tab, the following error message is displayed:

 
![image](https://github.com/dbeaver/dbeaver/assets/162123109/579db34f-e7ed-4b92-843a-2181109ba89b)


Please let me know if you need any more information.

**Comment by LonwoLonwo** [comment]
It looks like your DBeaver application doesn't have enough rights to download something from the Internet. 
Please check DBeaver's permissions.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by bossanova1986** [comment]
https://stackoverflow.com/questions/71539122/network-error-in-dbeaver-mysql-connection-unable-to-find-valid-certification-p solved this issue for me

**Comment by mustafa-altuntas** [comment]
1) Window->Preferences->Connections
2) I deselected the “Use Windows trust store” feature under “Security” in the Connections area.
3) Close and open DBeaver.
I encountered the same error and as a result of my research, I solved the problem by following the steps above.

![2024-09-28 14_15_09-DBeaver 24 2 1](https://github.com/user-attachments/assets/470c06fd-796e-4bf9-b476-8ae8cbf33ee1)

**Comment by mustafa-altuntas** [comment]
> Sorunu yeniden oluşturmak için lütfen şu adımları izleyin:
> 
> 1. DBeaver Uygulamasında "Yeni Veritabanı Bağlantısı" seçeneğine tıklayın. 2.Kullanılabilir veritabanları listesinden "PostgreSQL"i seçin. 3.Ana bilgisayar, bağlantı noktası, kullanıcı adı ve şifre gibi gerekli bağlantı ayrıntılarını doldurun. 4.Bağlantı ayrıntıları doldurulduktan sonra bir sonraki adıma geçin. 5.Bağlantı ayarları sayfasında, aşağıda gösterildiği gibi "Sürücü Özellikleri" sekmesini bulun ve seçin. 6."Sürücü Özellikleri" sekmesini seçtikten sonra aşağıdaki hata mesajı görüntülenir:
> 
> ![image](https://private-user-images.githubusercontent.com/162123109/310055947-579db34f-e7ed-4b92-843a-2181109ba89b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NjQzNzMsIm5iZiI6MTcyNzQ2NDA3MywicGF0aCI6Ii8xNjIxMjMxMDkvMzEwMDU1OTQ3LTU3OWRiMzRmLWU3ZWQtNGI5Mi04NDNhLTIxODExMDliYTg5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxOTA3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDg3ODgyMTdiMmQ2MDExNjc4YWM5NDk5YTRiZGQwZjE5NTFiZTBiNmQ0Zjc1YmU2NDUwNTljOWNmMzFkYzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eVc-isDt8qkIRf85ADd7jvyjiwV1bYZgETjtgrx9Fgs)
> 
> Daha fazla bilgiye ihtiyacınız olursa lütfen bana bildirin.


1) Window->Preferences->Connections
2) In the Connections area, under “Security”, deselect “Use Windows trust store”.
3) Close and open DBeaver.
I encountered the same error and as a result of my research, I solved the problem by following the steps above.
![2024-09-28 14_15_09-DBeaver 24 2 1](https://github.com/user-attachments/assets/83f5082c-8438-4be8-8eee-661b34531b01)
