### ISSUE TITLE
Enable spatial viewing for DuckDB geometries

### ISSUE THREAD

**Issue by AliHmaou** [dbeaver/dbeaver#23049]
### **Description of the problem**
An issue arises when attempting to visualize spatial geometries stored in DuckDB using DBeaver's spatial visualizers. 
The geometries are not displayed and a question mark appears in the column header : 
![image](https://github.com/dbeaver/dbeaver/assets/1844031/175dcb21-fcf4-4a64-9902-088e1038afe8)
![image](https://github.com/dbeaver/dbeaver/assets/1844031/8aab6634-f06a-42c3-9b74-f576606c6dee)

### **Feature requested**
The desired solution is for DBeaver to support the display of DuckDB geometries in its spatial visualizers, like to its support for PostGIS. 
This enhancement would significantly improve user experience, facilitating seamless visualization and interaction with spatial data in DuckDB.

### **Workaround**
As a workaround, it is possible to convert the geometry to text (with st_astext function) and set the transformation to "Geometry" : 
![image](https://github.com/dbeaver/dbeaver/assets/1844031/29b1ff6c-590f-4471-9c34-dc7da3bfb8ed)

However, this approach introduces unnecessary complexity and is not optimal for data exploration.

### **Additional context**
Ensuring accurate visualization of geometries in DuckDB within DBeaver is crucial for users working with spatial data. This feature enhancement would streamline data analysis workflows and bolster productivity.
Personally, this constraint compels me to continue using Postgres for rapid data exploration.

**Comment by E1izabeth** [comment]
Thank you for the request

**Comment by AliHmaou** [comment]
Do I have to get lots of "thumbs ups" to have a chance to get it implemented ?

**Comment by E1izabeth** [comment]
Not necessary. Your request is quite clear and useful for sure.

**Comment by rduivenvoorde** [comment]
Good to see this, just wanted to write a FeatureRequest myself :-)

Some background: https://cloudnativegeo.org/blog/2023/09/duckdb-the-indispensable-geospatial-tool-you-didnt-know-you-were-missing/

**Comment by AliHmaou** [comment]
New feature works like a charm ! Thank you very much !!!
