### ISSUE TITLE
`brew install` adding `dbeaver` to `PATH`

### ISSUE THREAD

**Issue by jamesbraza** [dbeaver/dbeaver#23059]
**Is your feature request related to a problem? Please describe.**

After running `brew install --cask dbeaver-community` for version 24.0.0 of DBeaver, running:

```none
> dbeaver
zsh: command not found: dbeaver
```

**Describe the solution you'd like**

It would be cool if `dbeaver` showed up in `PATH` after running `brew install`.

**Describe alternatives you've considered**

N/a

**Additional context**

- OS: macOS Sonoma 14.3

**Comment by flambchap** [comment]
Hi @jamesbraza. We don't provide Homebrew casks ourselves. The Homebrew community provides them. I suggest opening a FR here: https://github.com/Homebrew/homebrew-cask.

As a workaround, I suggest creating an alias `alias dbeaver="/Applications/DBeaver.app/Content/MacOS/dbeaver"`, adding `/Applications/DBeaver.app/Content/MacOS/dbeaver` to `PATH`, or using `open -a "DBeaver.app" --args [PARAMETERS]`.

**Comment by jamesbraza** [comment]
I made a new FR here: https://github.com/orgs/Homebrew/discussions/5188

Thank you @n5a5 for the response and also workaround 👍

**Comment by jamesbraza** [comment]
Alright, I took a look at https://github.com/Homebrew/homebrew-cask/blob/master/Casks/d/dbeaver-community.rb, and they are basically just invoking the DBeaver DMG.  Please see https://github.com/orgs/Homebrew/discussions/5188 for more information.

So, to add an alias for this, it's not a Homebrew cask problem, we need the DBeaver DMG installer to create the alias or ensure `dbeaver` is in the `$PATH`.

Cc @n5a5 what do you think of the installer here setting that up for us?
