### ISSUE TITLE
sqlserver adds a new schema option

### ISSUE THREAD

**Issue by thenext600** [dbeaver/dbeaver#23051]
Select schema when editing ms sqlserver sql just like postgresql
![im](https://github.com/dbeaver/dbeaver/assets/130520290/cd916e98-0105-4a5f-93c3-3f1daf4cf563)

**Comment by E1izabeth** [comment]
Thank you for the idea. However, it's not possible due to SQL Server limitations. It does not support schema change - it's not possible to chose any schema, but the default one. So, showing schemas here doesn't make sense, as we can't change the schema.
