### ISSUE TITLE
Error switching active page

### ISSUE THREAD

**Issue by JaldeaR** [dbeaver/dbeaver#23054]
### Description

When the edit connection option is selected on the newest update, i get the following error:

```
Error switching active page

Reason:
Cannot invoke "org.eclipse.swt.widgets.Control.setFocus()" because the return value of "org.eclipse.jface.dialogs.IDialogPage.getControl()" is null
```

![image](https://github.com/dbeaver/dbeaver/assets/58230005/175e2b9d-8ab7-4f36-af7d-2137ccbd2bc5)

### DBeaver Version

24.0.0

### Operating System

Pop!_OS 22.04 LTS (Ubuntu)

### Steps to reproduce

Edit connection

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by JaldeaR** [comment]
> Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

[error.log](https://github.com/dbeaver/dbeaver/files/14493176/error.log)
Log is too long to post in spoiler or codeblock.

**Comment by Destrolaric** [comment]
@JaldeaR Hi, which method was used for DBeaver installation?

**Comment by JaldeaR** [comment]
Eddy (install manager)

I've purged the installation and rebooted.
It seems the error is no longer present when doing the same operations.

the program seems to be working fine again, i also had issues with editing data in the DB's. this is also resolved.

Any idea what caused the issue?

**Comment by Destrolaric** [comment]
@JaldeaR Quite possibly you had your version update not remove previous class files which caused the issue, when DBeaver is updated it is heavily recommended to avoid having multiple plugin versions in installation

**Comment by JaldeaR** [comment]
@Destrolaric Eddy usualy does this installation/update process perfectly fine so weird it might have failed for this occasion.

Thanks anyhow, i'll close the case.
