### ISSUE TITLE
spacebar key in Mac version of DBeaver does not work in sql query editor

### ISSUE THREAD

**Issue by hornsong** [dbeaver/dbeaver#23056]
### Description

in the query editor the spacebar key does't work

### DBeaver Version

Community latest edition

### Operating System

macOS Sonoma 14.3.1

### Database and driver

sqlite example database of DBeaver

### Steps to reproduce

I try to type a query in the query editor and the spacebar key doesn't work at all, so this makes it impossible to write a query.

**Comment by LonwoLonwo** [comment]
Hello @hornsong 

Could you please provide a video of your issue?

**Comment by hornsong** [comment]
I solved the issue, by disabling the full keyboard access om my MacBook.
This solution is described on weburl
https://www.macobserver.com/tips/how-to/fix-spacebar-not-working-mac/

Op di 5 mrt 2024 om 14:11 schreef Anastasiya ***@***.***>:

**Comment by LonwoLonwo** [comment]
Ok, thanks for the update. Is your issue solved now? Can I close this ticket?

**Comment by hornsong** [comment]
yes, you can close it

Op ma 11 mrt 2024 om 20:01 schreef Anastasiya ***@***.***>:
