### ISSUE TITLE
Website incorrect path for `/Application` in Mac

### ISSUE THREAD

**Issue by jamesbraza** [dbeaver/dbeaver#23060]
### Description

https://dbeaver.com/docs/dbeaver/Command-Line/#mac

Has `/Application/DBeaver.app`. It should be `/Applications/DBeaver.app`.

### DBeaver Version

Community Edition 24.0.0

### Operating System

macOS Sonoma 14.3

### Database and driver

n/a

### Steps to reproduce

> /Application/DBeaver.app/Content/MacOS/dbeaver
zsh: no such file or directory: /Application/DBeaver.app/Content/MacOS/dbeaver
> /Applications/DBeaver.app/Contents/MacOS/dbeaver --help
usage: dbeaver [-help] [-vars <arg>]

### Additional context

n/a

**Comment by E1izabeth** [comment]
Thank you

**Comment by daelynum** [comment]
Fixed
