### ISSUE TITLE
Exporting CSV from Query does not show exported file in system explorer

### ISSUE THREAD

**Issue by wleodinh** [dbeaver/dbeaver#23063]
### Description

Despite ticking the "show exported file in system explorer" option in the Right Click > Execute > Export from Query wizard, when the CSV is done, I am taken to the parent directory ("C:\Users\my_user_name") of the directory I selected ("C:\Users\my_user_name\Downloads"). This was not an issue when I was using DBeaver on the same Windows laptop approximately 3 months ago and, while not a major blocker, does impact my workflow efficiency as I typically export dozens of files this way each day.

### DBeaver Version

Community 22.3.0.202212070729

### Operating System

MS Windows 10 Enterprise 10.0.19045 Build 19045

**Comment by E1izabeth** [comment]
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by wleodinh** [comment]
Hi Elizabeth,

I have attached the requested log files. Please let me know if anything
else is needed.

Thanks,

Phoenix Leodinh (she/her)

**Comment by E1izabeth** [comment]
Please attach the log files on the github platform in comment https://github.com/dbeaver/dbeaver/issues/23063. When you reply to the notification email, the text of your reply come here, but attachments are not.

**Comment by wleodinh** [comment]
[Comment 23063 - Issue Replication Log.zip](https://github.com/dbeaver/dbeaver/files/14541481/Comment.23063.-.Issue.Replication.Log.zip)

**Comment by wleodinh** [comment]
Hi @E1izabeth, I've attached the two log files as a ZIP archive.

**Comment by Destrolaric** [comment]
@wleodinh Hi, is the Windows store DBeaver version used during export?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
