### ISSUE TITLE
Do not change view formatting after saving

### ISSUE THREAD

**Issue by cezarbarboza1** [dbeaver/dbeaver#23076]
**Is your feature request related to a problem? Please describe.**
I'm using MariaDB and MySQL, everytime I save view on the database a lot parentesys and quotation marks and I would like to keep the format that I use to create the SQL query to be used in the view.

**Describe the solution you'd like**
I would like to keep the format as I used to create originally 

**Describe alternatives you've considered**
A button or option to be select when saving the view to select if you want to keep the original format or save as the database defaults.

**Additional context**

**Comment by ShadelessFox** [comment]
Hello @cezarbarboza1,

Sorry, but it's not possible.

The query submitted to the database is processed and transformed by the database itself and stored in, likely, a compiled form that lacks any comments or specific formatting. To retrieve its DDL, DBeaver uses a set of commands supported by the database, e.g., `SHOW CREATE VIEW`.
