### ISSUE TITLE
Show the URL attempted when connection not working

### ISSUE THREAD

**Issue by codearoo** [dbeaver/dbeaver#23070]
**Is your feature request related to a problem? Please describe.**
I'm using DBeaver behind a restrictive proxy, and when it tries to download drivers, it gets blocked and just simply shows the error that it couldn't connect.

**Describe the solution you'd like**
If it can at least show me what URL it was trying then I can submit that to the proxy bypass to get it to work.

**Describe alternatives you've considered**
The alternative to download the driver actually did not work. I was able to get the driver installed, but yet, it still is stuck on some internet connection, and again, I have no idea what it's trying to connect to.

**Comment by ShadelessFox** [comment]
Hello @codearoo,

URLs should be visible in the log files. You can find them here: https://github.com/dbeaver/dbeaver/wiki/Log-files#log-files

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by codearoo** [comment]
hi... @E1izabeth and @ShadelessFox   sorry for the delay; I don't log in often. So I was able to get what I needed mostly from the logs. However the enhancement request still stands because.. why should we go through all the extra steps to find that part in the logs when it could just be included in the error message? Unless the team decided not to do this request.
