### ISSUE TITLE
Option for Explain exec plan in Postgres

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#2307]
"Explain execution plan" always do EXPLAIN **ANALYZE** ...  that executes the query during analyse, but when the query is rather big and complex and not yet optimized, it may take very much time to wait.
The additional option is needed here - do the ANALYZE or not.

**Comment by hofoen** [comment]
Even the removal of the analyze is better. If the analyze is necessary, you can do it manually.

**Comment by serge-rider** [comment]
Agreed

**Comment by pyrocks** [comment]
Hi, any news about this?
