### ISSUE TITLE
Usage statistics setting seems to be not used

### ISSUE THREAD

**Issue by GeriZ** [dbeaver/dbeaver#23073]
### Description

Even though I've deactivated usage statistics in preferences a usage statistics window will be display at every start

### DBeaver Version

24.0.0

### Operating System

Windows 10

### Database and driver

DB2

**Comment by GeriZ** [comment]
I've tried to upload a screenshot of this window but neither the jpeg nor the png file will be displayed in the preview of my comment....;-(

**Comment by ShadelessFox** [comment]
I was able to reproduce the issue. Thank you for the bug report.

**Comment by serge-rider** [comment]
Will be fixed in https://github.com/dbeaver/dbeaver/issues/23087
Version 24.0 with the hotfix will be re-published this week.
