### ISSUE TITLE
The statistics dialog should be skipped after first hitting confirm button

### ISSUE THREAD

**Issue by serjiokov** [dbeaver/dbeaver#23087]
### Description

The statistics dialog should be skipped after first hitting confirm button

### DBeaver Version

24.0.0

### Operating System

All

### Steps to reproduce

1. Launch on the new workspace 
2. Hit don't send checkbox 
3. Hit confirm button on the dialog 
4. Restart product
Observed: 
The statistic dialog appears again.
Expected:
The dialog should be skipped

**Comment by MashaKorax** [comment]
verified

**Comment by daeho-ro** [comment]
I hope this changes also will be published to brew soon.
