### ISSUE TITLE
Empty Entity column in exec plan for CTE in Postgres

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#2308]
When reading execution plan for query with many CTEs I have to look for its name in the details window, but in the same time the column Entity in the main list is empty.
![default](https://user-images.githubusercontent.com/16996529/31416844-2132835e-ae6f-11e7-9b4b-ab956c59f118.png)

**Comment by uslss** [comment]
cannot reproduce on 6.0.2
