### ISSUE TITLE
Prompt for Master Password on DBeaver Launch and Viewing Passwords

### ISSUE THREAD

**Issue by bajins** [dbeaver/dbeaver#23084]
### Description

![image](https://github.com/dbeaver/dbeaver/assets/30252550/1129d4d2-7059-465f-b099-404338afc837)

### DBeaver Version

Community Edition 24.0.0

### Operating System

Windows11

### Database and driver

- Oracle
- PostgreSQL

or all ?

### Steps to reproduce

Every time I open DBeaver, add connection configurations, or attempt to view passwords, I am prompted to enter a master password. I had previously set up this master password, but I have since removed it from the configurations. However, the prompt still appears, expecting me to input this master password. Could you please assist with permanently removing or resetting this master password prompt, as it is currently asking for a password I no longer use or have set up?

### Additional context

![image](https://github.com/dbeaver/dbeaver/assets/30252550/99ab7e46-410d-4cc9-bdc1-3acbfd3ba6d8)
![image](https://github.com/dbeaver/dbeaver/assets/30252550/1384b892-f4ab-462d-ad09-066d3f3edd31)
![image](https://github.com/dbeaver/dbeaver/assets/30252550/eeee21a5-c00a-416e-acf7-02cb3d5c3972)
![image](https://github.com/dbeaver/dbeaver/assets/30252550/28fc4622-c361-4f23-ab56-9b49d495a9e6)

**Comment by MashaKorax** [comment]
Hello, @bajins. I see  from your screenshots that you use project password ( not master password). To disable it go to Projects view - > project properties - > project security -> Clear password. (Watch my video)

https://github.com/dbeaver/dbeaver/assets/84867187/c245fc0d-e246-4eda-81a6-3c0f0446ea77

**Comment by bajins** [comment]
> Hello, @bajins. I see from your screenshots that you use project password ( not master password). To disable it go to Projects view - > project properties - > project security -> Clear password. (Watch my video)
> 
>  REC-20240310144118.mp4

Thank you for your response. After my verification, the issue has not been resolved. When I click the `Clear password` button, a window pops up asking me to enter a password. However, I cleared the password a long time ago and now I can't enter a password.
![image](https://github.com/dbeaver/dbeaver/assets/30252550/957a9d67-2b0f-4659-808a-7a496949558d)

**Comment by bajins** [comment]
The issue has been resolved. Please refer to my screen recording video. Thank you.

https://github.com/dbeaver/dbeaver/assets/30252550/ae73d317-78dd-41b4-b76f-f5dd4ef79fad
