### ISSUE TITLE
Data importing problem from CSV files.

### ISSUE THREAD

**Issue by bugsoft337** [dbeaver/dbeaver#23105]
### Description

I think there is a problem with importing table data from CSV files(MS Excel).

### DBeaver Version

Version 24.0.0.202403031740 (Zip version)

### Operating System

Windows 11 Pro

### Database and driver

MARIADB 10.3

### Steps to reproduce

1. Create a new database table which has three columns ( ex: table_cat1, table_cat2, table_cat3) 
2. Try to import data from MS Excel CSV file.
3. At the "Tables mapping", you can see the data is mapped with table_cat1, table_cat2, table_cat2(not 3).
4. Even though I specified the columns one by one from source to target.

### Additional context
I tested it again, and I think at least 5 fields are needed to repaet this problem.
Always my fifth field data is linked to fourth field of target.
_No response_

**Comment by MashaKorax** [comment]
Hello @bugsoft337, I Can not reproduce your issue. Could you provide a screen record?

**Comment by bugsoft337** [comment]
![2024-03-11 17 18 23](https://github.com/dbeaver/dbeaver/assets/33536758/fd274041-8c1c-463f-810a-d6a72c0b5f8e)

I am not sure if I made some mistakes when I tried to make a new table for this, so I upload the SQL syntax as well.

CREATE TABLE `articles2` (
  `deleted_at` timestamp NULL DEFAULT NULL,
  `old_num` INT,
  `a_cat` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `b_cat` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `c_cat` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `atcl_seq` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `new_article` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `memo` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `old_article` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `item` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `model_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `barrel_spec` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `registered_by` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `reason` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

**Comment by bugsoft337** [comment]
Field names are not the same with the picture because I changed them several times to check the result of data importing.
Thank you.

**Comment by meteor1113** [comment]
I had the same problem

**Comment by Matvey16** [comment]
@bugsoft337 Thank you for the report!
