### ISSUE TITLE
display error on macos Sonoma

### ISSUE THREAD

**Issue by toxmc** [dbeaver/dbeaver#23108]
### Description

![image](https://github.com/dbeaver/dbeaver/assets/3990846/8fb9852a-9069-44fc-8247-2ba20add480c)

look this picture.

### DBeaver Version

23.3.2.202401072024

### Operating System

macos Sonoma  14.4

### Database and driver

mysql  SQL editer

**Comment by LonwoLonwo** [comment]
Hello @toxmc 

Thanks for the bug report.
It is a knowing issue. You can check this tip to handle this behavior: https://github.com/dbeaver/dbeaver/issues/22299#issuecomment-1957274749
And I'm closing this ticket as a duplicate.

**Comment by LonwoLonwo** [comment]
Also, you can check the latest DBeaver version.

**Comment by toxmc** [comment]
thank you very much. I used the latest version to fix it.
