### ISSUE TITLE
This dialog box (statistics collection) is displayed every time you open dbeaver, and some places are blurry in dark mode.

### ISSUE THREAD

**Issue by mgl-pub** [dbeaver/dbeaver#23106]
### Description

This dialog box (statistics collection) is displayed every time you open dbeaver
![Screenshot from 2024-03-11 20-10-54](https://github.com/dbeaver/dbeaver/assets/4723621/8afbc4ce-43c8-49db-a880-324f0efd29a8)

### DBeaver Version

24.0.0

### Operating System

archlinux 

### Database and driver

mysql driver version 8.3.0

**Comment by serjiokov** [comment]
Thanks for the report, already fixed in https://github.com/dbeaver/dbeaver/issues/23087
