### ISSUE TITLE
Request for Procedure Creation Functionality in Firebird

### ISSUE THREAD

**Issue by MaiconMichel** [dbeaver/dbeaver#23100]
Hello, I am using Firebird and I noticed that the menu to create procedures is not appearing. I would like to know if it is possible to add this functionality. Also, are there other functionalities that are not yet available in Firebird? If so, are there plans to implement them in the future? Thank you in advance for your help and I look forward to your response.

![Captura de tela 2024-03-10 005050](https://github.com/dbeaver/dbeaver/assets/48292687/66c08c95-ffdb-451f-89f0-9c231d7e1fb0)

**Comment by LonwoLonwo** [comment]
Hello @MaiconMichel 

For now, this functionality has not been implemented. And we already have this request https://github.com/dbeaver/dbeaver/issues/14225
You can vote for the original ticket.
And I'm closing this one.
