### ISSUE TITLE
Rerelease issues: brew install failed

### ISSUE THREAD

**Issue by daeho-ro** [dbeaver/dbeaver#23103]
### Description

After the version 24.0.0 re-deployed, sha256 changed and so cannot install the package through `brew`.

```
brew install dbeaver-community
==> Downloading https://dbeaver.io/files/24.0.0/dbeaver-ce-24.0.0-macos-aarch64.dmg
==> Downloading from https://download.dbeaver.com/community/24.0.0/dbeaver-ce-24.0.0-macos-aarch64.dmg
###################################################################################################### 100.0%
Error: SHA256 mismatch
Expected: 27cf2a216d526d59640c1fc2f427274c41d57e40c3a01ffaab7045999030476c
  Actual: 52590c378cf9d4f974827d70f11b0a60b7b0cc6397c8c7ba4d8f417f4c0df0a2
    File: /Users/daeho.ro/Library/Caches/Homebrew/downloads/d0f8bb2002c112bea1fc04f5332dc2065b5b06d54f4e127195f65673f311e21b--dbeaver-ce-24.0.0-macos-aarch64.dmg
To retry an incomplete download, remove the file above.
```

### DBeaver Version

Community Edition 24.0.0

### Operating System

macOS Sonoma 14.3.1

**Comment by daeho-ro** [comment]
https://github.com/Homebrew/homebrew-cask/pull/168727

**Comment by ShadelessFox** [comment]
Hello @daeho-ro,

Can you please confirm that the issue is resolved? Can the ticket be closed now?

**Comment by daeho-ro** [comment]
Yes, It is resolved @ShadelessFox.
Thanks!

**Comment by koehntopp** [comment]
Back in 24.1.0

![image](https://github.com/dbeaver/dbeaver/assets/7113567/94234a2b-8c7c-4f11-9f8d-ba754bf52886)

**Comment by ShadelessFox** [comment]
@koehntopp this is a third-party issue, please ask Homebrew guys to update checksums.
