### ISSUE TITLE
sqlite file not exists but connect successful

### ISSUE THREAD

**Issue by alctny** [dbeaver/dbeaver#23118]
### Description

1. use dbeaver connect to local sqlite
2. delete sqlite local file
3. dbeaver still connected sqlite and able to query or other action

### DBeaver Version

DBeaver 24.0.0.202403042157

### Operating System

Arch Linux x86

### Database and driver

Server SQLite 3.45.1
Driver SQLite JDBC 3.45.1.0

### Steps to reproduce

1. create local sqlite file
3. connect to sqlite with dbeaver
4. create table and insert data (optional)
5. delete *.db local file
6. SELECT or other action with dbeaver

![dbeaver-connect-sqlite-bug](https://github.com/dbeaver/dbeaver/assets/44720162/dba087a1-e5f1-4f2d-a8b3-9ec6b2fa815f)

### Additional context

OS: Arch Linux x86_64
EVN: localcation

**Comment by ShadelessFox** [comment]
Hello @alctny,

It's expected as SQLite doesn't instantly persist changes on the disk. It has an in-memory cache.

Moreover, if you reconnect and the file doesn't exist, it will be created automatically by the driver.
