### ISSUE TITLE
If a table view is closed stop querying metadata

### ISSUE THREAD

**Issue by alejandrofm** [dbeaver/dbeaver#23110]
### Description

I opened 5+ tables (double click on table) to look at the SQL source, but for some reason it didn't load, so I closed the tabs, Background tasks keep running trying to get the data to a now-closed tab.
<img width="1176" alt="image" src="https://github.com/dbeaver/dbeaver/assets/19591174/4d6cbcbc-6793-49a7-abc1-a2597a9f91d7">

### DBeaver Version

24.0.0 community

### Operating System

macOS 14

### Database and driver

Redshift: com.amazon.redshift.jdbc42.Driver

### Steps to reproduce

Open multiple tabs to look at metadata for tables, in this case, were +10Gb tables.
Close the tabs before getting the result, DBeaver should stop trying to get that data

**Comment by alejandrofm** [comment]
Also when I cancel one of those from "background tasks" they stay grayed out "closing", why does it take so much time to close a metadata request? The request didn't get to Redshift for what I saw in the Redshift console.
<img width="1083" alt="image" src="https://github.com/dbeaver/dbeaver/assets/19591174/d3dac560-000b-4171-985d-7eb5a8015395">

**Comment by ShadelessFox** [comment]
Hello @alejandrofm,

It's hard to tell what's going on without having any logs, especially [thread dumps](https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump). Please reproduce the issue again and make a thread dump.

In most cases, it's impossible to terminate an ongoing blocking I/O operation.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
