### ISSUE TITLE
High CPU usage when DB is not reachable (Oracle JDBC 12.x, Ubuntu 16.04)

### ISSUE THREAD

**Issue by Mjasnik** [dbeaver/dbeaver#2311]
I have encountered issue when DBeaver starts using quite a lot of CPU (100+) after DB is not reachable.

Steps to reproduce is:
1. connect to DB
2. make some queries
3. disconnect cable / turn off wifi
4. after some time DBeaver starts using more CPU
5. it does NOT help if I choose "Disconnect all" from menu

This can happen in two situations:
1. firewall silently close the connection to DB
2. unplug the cable / connect to different network

Versions:
DBeaver: 4.2.2
Java: openjdk version "1.8.0_131" (I have tried Oracle java as well, issue does not seem to depend on version)
Oracle JDBC: ojdbc7 (12.1.x version)

**Comment by serge-rider** [comment]
Maybe this is the same as #1041
Please try to execute
```
SWT_GTK3=0
```
before running DBeaver.

**Comment by Mjasnik** [comment]
Hi,

Should not be, this is my startup script:
`#!/bin/bash`
`. $HOME/.bashrc.CUST`
`export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64`
`export PATH=$JAVA_HOME/bin:$PATH`
`export SWT_GTK3=0`
`/data/.applications/DBUtils/dbeaver/dbeaver "$@"`

Actually, yesterday, I think I left DBeaver open, but  I definitely disconnected from all of the DB's and it started using more CPU after some time which I didn't measure, hour maybe.
I'll try to measure next time.

**Comment by serge-rider** [comment]
Ok.
I still can't reproduce that (left it with disconnected wifi for an hour and nothing). Perhaps this depends on OS/settings.
Could you make a thread dump once DBeaver will start to consume CPU (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump) and post it here.
Thanks

**Comment by Mjasnik** [comment]
I did more deep investigation, it seems that particular kernel's single task CPU usage accounting may show greater numbers than it actually is.
If this will be the case, I'll close the bug.

**Comment by piqoni** [comment]
I also face the same every day. When I go out of the network, or close the laptop lid, then I open the fans go crazy, and I have to force kill dbeaver.

**Comment by serge-rider** [comment]
@piqoni Could you try to make a thread dump (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump)

**Comment by Mjasnik** [comment]
[thread-dump.txt](https://github.com/serge-rider/dbeaver/files/1438506/thread-dump.txt)

Here is my thread-dump file. Reopening since someone else has similar problem and I'm still not sure about accounting though.
Hope this helps.

**Comment by Mjasnik** [comment]
Actually I have tested DBeaver extension on Eclipse Photon, I don't see such CPU usage there.
I'll continue using Photon to see whether this issue is a non-issue on Photon.

**Comment by Mjasnik** [comment]
Photon uses CPU as well, did not notice it right away, so this definitely is the issue.
In the image here, see that DBeaver uses the most resources on the system, although I use it very rarely. It's sitting in background 98% of time, but check CPU "time" in the image.
![image](https://user-images.githubusercontent.com/32698211/34644423-00bb8ce6-f33f-11e7-83fb-1371ab09bbc7.png)

**Comment by serge-rider** [comment]
@Mjasnik what is you Linux version?

Most typical advise is to add
```
--launcher.GTK_version
2
```
In dbeaver.ini. But it is already there if you download DBeaver from GitHub or dbeaver.jkiss.org.


https://askubuntu.com/questions/776717/eclipse-using-high-cpu-after-upgrade-to-ubuntu-16-04
https://stackoverflow.com/questions/11346357/high-cpu-usage-in-eclipse-when-idle
https://bugzilla.redhat.com/show_bug.cgi?id=1294697
