### ISSUE TITLE
[RisingWave] remove the "Aggregate Functions" panel

### ISSUE THREAD

**Issue by neverchanje** [dbeaver/dbeaver#23126]
### Description

Given that RisingWave doesn't support Aggregate Functions as well as `pg_catalog.pg_aggregate`, clicking into this panel will pump up errors. Please remove this panel if possible.

If I understand correctly, the method `supportsAggregates` in `PostgreServerRisingWave` should returns false.

https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/impls/PostgreServerRisingWave.java#L129-L132

### DBeaver Version

Version 24.0.0.202403091004

### Operating System

13.0.1 (22A400)

### Database and driver

1. Database name: RisingWave
2. Driver name: postgres-jdbc 42.7.2

### Steps to reproduce

1. Connect to a local RisingWave 

2. Double-click the panel "Aggregate functions"
  <img width="364" alt="Screenshot 2024-03-14 at 12 14 32" src="https://github.com/dbeaver/dbeaver/assets/6970676/e7cdc0d8-ba2c-4cb5-984f-3d820225690e">

3. The error below will appear
```
ERROR: Failed to prepare the statement

Caused by:
  Feature is not yet implemented: pg_catalog.pg_aggregate is not supported, please use `SHOW` commands for now.
`SHOW TABLES`,
`SHOW MATERIALIZED VIEWS`,
`DESCRIBE <table>`,
`SHOW COLUMNS FROM [table]`

Tracking issue: https://github.com/risingwavelabs/risingwave/issues/1695
```

**Comment by LonwoLonwo** [comment]
Hello @neverchanje 

Thanks for the report!
