### ISSUE TITLE
Decimal places not showing on numeric columns

### ISSUE THREAD

**Issue by dolfangle** [dbeaver/dbeaver#23157]
### Description

Hi, I've just setup dbeaver at my work, but numeric columns (which should have decimals) are showing as integers with no decimal places, and when I run sql the same happens. eg if I run select 1/2 it returns 0.
Is there a setting somewhere to show the decimal places?
![image](https://github.com/dbeaver/dbeaver/assets/163842136/98eb5a0f-ea3c-462e-9112-2c266e3273ff)

These are my number settings
![image](https://github.com/dbeaver/dbeaver/assets/163842136/db3135a4-5c9b-4b3b-b551-5116b7778219)

### DBeaver Version

Community Edition 23.3.2

**Comment by ShadelessFox** [comment]
Hello @dolfangle,

What database and driver are you using?

Why do you think this expression must yield a decimal instead of an integer? It's up to the database semantics.

**Comment by dolfangle** [comment]
Hi @ShadelessFox 
Many thanks for the reply. It's Oracle database, driver is ojdbc8.jar.
I have viewed the same database in other database tools (sql developer and dbvisualiser) and it showed the decimals. Apologies I'm sure I'm missing something here.

**Comment by ShadelessFox** [comment]
Thanks for the information.

Unfortunately, I'm unable to reproduce your issue (although I'm testing against Oracle 12c):
![image](https://github.com/dbeaver/dbeaver/assets/35821147/2f6f23f0-41dd-49d1-b900-bf36f5bf661c)

Can you please hover the column's header to show its type and send it there?
![image](https://github.com/dbeaver/dbeaver/assets/35821147/321a47e0-9beb-4783-a753-b31222961166)

**Comment by dolfangle** [comment]
Thank you. This was the 1/2 example (just says number)
![image](https://github.com/dbeaver/dbeaver/assets/163842136/0a532214-5f08-41db-9c7d-3f1694f572f2)

However this column for example isn't showing any decimals despite seeing decimal values in the same column in the other database tools i mentioned
![image](https://github.com/dbeaver/dbeaver/assets/163842136/4d2be6ac-9549-4b56-98e2-a957bb1ccc64)

**Comment by ShadelessFox** [comment]
Try disabling number formatting to see if it affects anything:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/23df86a7-95b3-4abe-b0cd-9ef9db8aa65e)

**Comment by dolfangle** [comment]
Thanks for the suggestion. I tried this but doesn't seem to have any effect on the decimal

**Comment by ShadelessFox** [comment]
What's the database version you're testing against? It can be seen in the connection configuration -> test connection.

**Comment by dolfangle** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/163842136/23bb6a34-768c-4b2c-83e5-5044f2b7d557)

**Comment by dolfangle** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/163842136/29d84f91-5308-4a5d-b3de-034009661f16)

**Comment by ShadelessFox** [comment]
I tried reproducing the issue with the following setup without success:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/dd68a351-c13f-440c-ae7e-7d9a218c85db)

I wonder if they may have changed something between the standard and enterprise editions of the database 🤔

**Comment by dolfangle** [comment]
Yes it could be that. Doesn't seem to be anything in Dbeaver that is setup incorrectly. Thanks for taking the time to look at this for me. I will keep looking and comment back if I find a fix.

**Comment by ShadelessFox** [comment]
Thanks. Looking forward to hearing updates.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know.

**Comment by AuroraLantean** [comment]
set the Maximum fraction digits to 15 in your DBeaver. https://dbeaver.com/docs/dbeaver/Managing-Data-Formats/24.0/#numbers

**Comment by maroony** [comment]
I had the same problem with Oracle. I fixed it by creating a *new connection object* for that database. There you have to select Oracle and all is working fine. My faulty connection was listed as a generic database or something. I think that was the problem. 

DBeaver 25.1.2
