### ISSUE TITLE
Clickhouse UInt64 incorrect display

### ISSUE THREAD

**Issue by howbownotnow** [dbeaver/dbeaver#23152]
### Description

DBeaver displays UInt64 values for Clickhouse incorrectly (see screenshot). The only way to make it display correctly is to cast values to string.

![image](https://github.com/dbeaver/dbeaver/assets/14977233/9c69e698-d6a0-48d8-b9b8-5640829db453)

### DBeaver Version

Community Edition  23.3.5

### Operating System

macOS Sonoma 14.4

### Database and driver

Clickhouse 23.3.18.15
Yandex ClickHouse driver (server version 21.3+)

### Steps to reproduce

CREATE TABLE uint64test (
id UInt64
)
ENGINE = MergeTree
ORDER BY id;

INSERT INTO uint64test(id)
VALUES (14455996476406444606), (16553254873430290414), (18446683486735532172);

SELECT id, toString(id) from uint64test;

**Comment by Ninefiveblade** [comment]
also occurs when uploading into file (csv and more) from the dbeaver interface

**Comment by LonwoLonwo** [comment]
Hello @howbownotnow 

I can't reproduce your issue, unfortunatelly.
Please provide a screen from your settings.
Preferences -> Editors -> Data Editors -> Data Formats

**Comment by howbownotnow** [comment]
![2024-03-22_15-20-32](https://github.com/dbeaver/dbeaver/assets/14977233/0d7050bb-5989-4f4b-90d2-5cfb414252a3)

**Comment by Destrolaric** [comment]
@howbownotnow Hi, just to be sure, can you specify the driver version? You can find it in `Connection Page -> Driver Settings -> Libraries`

**Comment by howbownotnow** [comment]
@Destrolaric 
![image](https://github.com/dbeaver/dbeaver/assets/14977233/63cfd962-7d32-4ccd-81ce-5c99147ae8ec)

**Comment by E1izabeth** [comment]
Could you try pressing Download/Update button here? It looks like the driver version issue
![image](https://github.com/dbeaver/dbeaver/assets/28875055/e3f9b259-6095-4c62-82eb-8a324d1cae23)

**Comment by howbownotnow** [comment]
@E1izabeth It seems to solve the problem, data is displayed correctly now, thank you!
