### ISSUE TITLE
Dark theme: Database navigator - Table size graph color has very bad visibility

### ISSUE THREAD

**Issue by Progress1** [dbeaver/dbeaver#23153]
### Description

Dark theme In Database Navigator, statistics info > table size graph color has very bad visibility. 
![image](https://github.com/dbeaver/dbeaver/assets/10151485/af99b330-1c21-4830-9736-4c68358828f2)

### DBeaver Version

Community 24.0

### Operating System

Windows

**Comment by LonwoLonwo** [comment]
Thanks for the report @Progress1
