### ISSUE TITLE
Native proxy on windows (didn't try other OS) doesn't work #18511

### ISSUE THREAD

**Issue by RoiSoleil** [dbeaver/dbeaver#23167]
### Description

Native proxy on windows (didn't try other OS) doesn't work because in the ZIP package the plugins "org.eclipse.core.net.win32.x86_64" and "org.eclipse.core.net.win32" are missings.

If i add those plugins in the plugins directory and add it to the bundles.info, it works then.

Same as : https://github.com/dbeaver/dbeaver/issues/18511

### DBeaver Version

CE 24.0.0

### Operating System

Windows 10

### Steps to reproduce

Try to set "Native" on Preferences > Network Connection

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by RoiSoleil** [comment]
Is it possible to add a test to avoid that this issue reoccures in future releases ?

**Comment by Matvey16** [comment]
Verified
