### ISSUE TITLE
New Versions Are Not Connecting to Redshift

### ISSUE THREAD

**Issue by MConant** [dbeaver/dbeaver#23172]
### Description

Hello! Many coworkers have reached out to me about not being able to connect to Redshift after upgrading versions. I have verified they have entered all the correct information. The only way I have been able to get them to connect is to downgrade them to the version that I am currently using, which is 22.0.4. 

I have been avoiding upgrading versions because of this issue. I may consider switching to DataGrip since it does noy have this issue. 

### DBeaver Version

22.0.4 (issues are with newer versions)

**Comment by LonwoLonwo** [comment]
Hello @MConant 

Could you please provide the log files after the connection fails? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by LonwoLonwo** [comment]
And what Redshift server version and driver version do you have? You can check it in your connection settings -> driver settings -> Libraries

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
