### ISSUE TITLE
Error for installing Eclipse Plugin

### ISSUE THREAD

**Issue by ngrulier** [dbeaver/dbeaver#2317]
I can't install the plugin in Eclipse (Marketplace or Install new software).
I have an error about a certificate:

https://dbeaver.jkiss.org/update/latest/content.xml.
com.ibm.jsse2.util.h: PKIX path building failed: java.security.cert.CertPathBuilderException: PKIXCertPathBuilderImpl could not build a valid CertPath.; internal cause is: 
	java.security.cert.CertPathValidatorException: The certificate issued by CN=Untrusted Certificate Warning, O="Cisco Systems, Inc.", L=San Jose, ST=California, C=US is not trusted; internal cause is: 
	java.security.cert.CertPathValidatorException: Certificate chaining error

Do you have a soluce to fixe it ?

![image](https://user-images.githubusercontent.com/6436659/31481364-29aa04b2-af23-11e7-97a9-ba8acb6dccf0.png)

**Comment by serge-rider** [comment]
Can't reproduce (Eclipse 4.6 and 4.7, JDT).
What Eclipse do you use? Maybe there are some conflicting plugins.
OR maybe there are some security constraints. DBeaver plugins aren't signed indeed. But this doesn't block installation.

**Comment by ngrulier** [comment]
Hello,

I'm using Eclipse Oxygen (for php) and RDi, an eclipse version packaged by IBM for Iseries (As400) developments (COBOL, RPG, CL... language).

**Comment by serge-rider** [comment]
I still can't figure out what exactly is wrong. And what exactly certificate is no trusted (the one mentioned in error dialog is definitely not DBeaver SSL certificate).

Are you able to install other plugin using Eclipse marketplace?

**Comment by tati-kru** [comment]
Hi @ngrulier
Could you, please, check that it can be reproduced or not on the latest version?

**Comment by nkolban** [comment]
I seem to be getting the same error when I try and install

![image](https://user-images.githubusercontent.com/3421732/37058146-2b2b41ea-214f-11e8-9554-072c561aaee0.png)

**Comment by serge-rider** [comment]
Please check solution in #2724
