### ISSUE TITLE
[Eclipse] Dbeaver plugin is  not working

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#23173]
### Description

Install Dbeaver from https://dbeaver.io/files/ea/update/ce/ and see a bunch of errors

[log.txt](https://github.com/dbeaver/dbeaver/files/14652760/log.txt)

![eclipse_Nw9Mc226UZ](https://github.com/dbeaver/dbeaver/assets/84867187/0370d14e-db02-4faa-8a74-20d3ea8317b9)

### DBeaver Version

DBeaver 24.0.1

### Operating System

windows 10

**Comment by serjiokov** [comment]
Root cause:
java.lang.ClassCastException: class org.jkiss.dbeaver.ui.app.DBeaverPluginApplication cannot be cast to class org.jkiss.dbeaver.model.app.DBPApplicationDesktop

**Comment by MashaKorax** [comment]
verified
