### ISSUE TITLE
Missing 'AS' in alias when SELECT

### ISSUE THREAD

**Issue by Catwoolfii** [dbeaver/dbeaver#23171]
### Description

I work in dbeaver with ClickHouse via the "ClickHouse (legacy)" connection.
I noticed that when opening the “table” object and then the “data” tab, a query like this is executed (example of opening system.asynchronous_metric_log):
`SELECT x.* FROM system.asynchronous_metric_log x FORMAT TabSeparatedWithNamesAndTypes;`
That is, in queries when opening the “data” tab of “table” objects, the keyword “ASS” is missing.

### DBeaver Version

Community Edition 24.0.0

### Operating System

Windows 10 Pro 64-bit (10.0, Build 19044)

### Database and driver

1. ClickHouse 24.1.5.6
2. ClickHouse JDBC 0.2.6

### Steps to reproduce

I just marked the steps in the screenshot:
![dbviewer_clickhouse_open_table](https://github.com/dbeaver/dbeaver/assets/13075570/6e1d4941-aa04-4446-9331-c7af70e55f16)

### Additional context

Is there an option to add the "ASS" keyword in dbeaver settings or driver settings?

**Comment by LonwoLonwo** [comment]
> That is, in queries when opening the “data” tab of “table” objects, the keyword “ASS” is missing.

Hello, please describe more - what for do you need another alias word? I do not see any issues on your screenshot.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
