### ISSUE TITLE
User Guide PDF is empty

### ISSUE THREAD

**Issue by jbosse** [dbeaver/dbeaver#23179]
### Description

The download PDF for the Beaver documentation downloads a PDF with no documentation.

### DBeaver Version

24.0

### Operating System

macOs

### Steps to reproduce

1. Visit https://dbeaver.com/docs/dbeaver/24.0/
2. Click Download PDF
3. Open PDF.

### Additional context

[DBeaver_v_24_0.pdf](https://github.com/dbeaver/dbeaver/files/14654791/DBeaver_v_24_0.pdf)

**Comment by LonwoLonwo** [comment]
Thanks for the report @jbosse!

**Comment by flambchap** [comment]
Thank you @jbosse. We've fixed the docs.

**Comment by jbosse** [comment]
Thank you. I just want to say I originally downloaded DBeaver Community in an emergency to dump some data from a Postgres database. SQLTools in VSCode handled my needs pretty well. But this tool has really grown on me. Great work!
