### ISSUE TITLE
单击“解释计划”按钮：Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive; at path $

### ISSUE THREAD

**Issue by baojiahui** [dbeaver/dbeaver#23183]
### Description
![2 1](https://github.com/dbeaver/dbeaver/assets/28584504/78658e04-1d84-4478-bb48-75ec96dbed26)
![2](https://github.com/dbeaver/dbeaver/assets/28584504/184c266f-b3f6-48bc-84e1-ab4cde264a23)
![3](https://github.com/dbeaver/dbeaver/assets/28584504/bace47cf-b9da-49a1-b67c-666967692d6f)
![4](https://github.com/dbeaver/dbeaver/assets/28584504/7eef2a93-2f11-4dcc-a8fa-ae0d9712a8aa)

### DBeaver Version

24.0

### Operating System

W10

### Database and driver

数据库:Mysql 8.0 
驱动包：8.20

**Comment by baojiahui** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/28584504/c25deef6-c402-4f1d-9fcd-e1d1b1f28a25)

**Comment by ShadelessFox** [comment]
Hello @baojiahui,

I'm unable to reproduce the issue with the following configuration:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/1af4d2e1-ba83-4c05-ad31-409284914644)

![image](https://github.com/dbeaver/dbeaver/assets/35821147/13cd515b-7111-45ab-bd17-d7eb98dc5a9a)

It appears to me that it might be a database issue, considering that the query clearly contains the `FORMAT=JSON` clause.

Can you please confirm that the database is indeed MySQL, not a fork/clone of some sort?

**Comment by baojiahui** [comment]
@ShadelessFox  阿里云分布式数据库PolarDB

**Comment by ShadelessFox** [comment]
Please write in English.

You're using a third-party database with MySQL driver and DBeaver's extended support for MySQL, not PolarDB.

For more information, please refer to the PolarDB docs:
https://www.alibabacloud.com/help/en/polardb/polardb-for-oracle/explain-syntax

If you want to request extended support for PolarDB in DBeaver, please submit a new issue.
