### ISSUE TITLE
MySQL/MariaDB "set user" privilege is not schema-based

### ISSUE THREAD

**Issue by JTMosaic** [dbeaver/dbeaver#23180]
### Description

The "set user" privilege in MySQL and MariaDB is applicable only to all schemas and not to specific schemas, similar to the "super" privilege

The checkbox for this privilege belongs on the "DBA Privileges" list and not on the "Schema Privileges" list. 

The action to set it for a specific schema will throw an error.

I am proposing the following changes to DBeaver:

1. Add a "Set user" privilege to the DBA Privileges page for a user. The current implementation of this privilege is correct (grant set user on *.* to <user>)
2. Remove the "set user" privilege from the Schema Privilege pages for ALL and individual schemas

Add to: 
![image](https://github.com/dbeaver/dbeaver/assets/9417720/c9fd8a40-3e39-4459-912f-8fff0bc5dcbe)

Remove from:
![image](https://github.com/dbeaver/dbeaver/assets/9417720/202fbd01-b34d-426f-b082-f9d7ea7c0624)

### DBeaver Version

24.0.0

### Operating System

macOs 14

### Database and driver

MySQL/MariaDB

**Comment by Destrolaric** [comment]
@JTMosaic Hi can you specify the database version?

**Comment by JTMosaic** [comment]
MariaDB 11.2

**Comment by LonwoLonwo** [comment]
Thanks for the report.
I see that not just the "Set user" privilege is in the incorrect section.
