### ISSUE TITLE
Proposals not working in SQL Editor!

### ISSUE THREAD

**Issue by dahmmme** [dbeaver/dbeaver#23198]
### Description

Hello everyone,

Using an M3 Pro with Sonoma 14.4, the proposals are not working when pressing ctrl + space. I made no change to the preferences on that level.

![grafik](https://github.com/dbeaver/dbeaver/assets/53038361/bd4a7e1d-9b14-417d-b736-c3c2e067f934)

Everything else works perfectly fine (autocompletion, suggestion of table names when i start writing, etc).

Any ideas if this is a bug or a misconfig from my side?

Thank you

### DBeaver Version

Community Edition 24.0.0

### Operating System

macOS Sonoma 14.4

**Comment by dahmmme** [comment]
Please delete, this is not a bug. It's due to the fact that mac shortcuts are used instead of dbeaver's shortcuts.
I had to turn off the "input sources" shortcuts on mac which were "ctrl + space".

**Comment by LonwoLonwo** [comment]
Thanks for the update @dahmmme
