### ISSUE TITLE
SQL Execution with Plan Visualizer

### ISSUE THREAD

**Issue by collicalex** [dbeaver/dbeaver#2319]
New feature request:

SQL Execution with the Plan Visualizer.
like:
http://www.toadworld.com/platforms/oracle/w/wiki/11002.explaining-the-explain-plan-using-pictures
https://help.sap.com/doc/bed8c14f9f024763b0777aa72b5436f6/2.0.00/en-US/c1f281fbbb571014aaf38a264c0e12c4.html
https://www.dbvis.com/features/tour/explain-plan/

**Comment by titou10titou10** [comment]
Did you try the "Explain execution plan" in DBeaver? (CTRL-Shift-E in teh SQL Editor ), or right click in the SQL Editor, then Execute -> Explain execution plan ?

**Comment by collicalex** [comment]
This option is disabled... even if I enable the query plan execution for my session (by executing query: 'set showplan on').

**Comment by titou10titou10** [comment]
What database are you using? DB2? Oracle? ...?

**Comment by collicalex** [comment]
Sybase ASE

**Comment by serge-rider** [comment]
This feature will be added in #810
