### ISSUE TITLE
Mongo limit native query

### ISSUE THREAD

**Issue by loctd98** [dbeaver/dbeaver#23205]
### Description

1. Function limit() in native query not working e.g: `db.getCollection("user_profile").find().limit(10);`
2. The exception `Cannot invoke "java.util.Iterator.hasNext()" because "<local3>" is null` when i run aggregate with limit() e.g: `db.getCollection("user_profile").aggregate({"$limit": 10});`
![Screenshot 2024-03-22 095755](https://github.com/dbeaver/dbeaver/assets/67491511/66c62496-f8c5-44bf-890d-b37770952161)
****

### DBeaver Version

Dbeaver Enterprise 24.0.0.202403110838

### Database and driver

DB version: MongoDB 4.4.17
Driver verison: mongo-java-driver 4.5.1

**Comment by LonwoLonwo** [comment]
Hello @loctd98 

Thanks for the request.

**Comment by E1izabeth** [comment]
It should work this way `db.getCollection("user_profile").aggregate([{"$limit": 10}]);`
Please take a look at the documentation
https://www.mongodb.com/docs/manual/reference/operator/aggregation/
https://www.mongodb.com/docs/manual/reference/operator/aggregation/limit/

**Comment by MashaKorax** [comment]
Confirmed
