### ISSUE TITLE
DBeaver constantly goes to "Not Responding" state

### ISSUE THREAD

**Issue by ChrisJEllis** [dbeaver/dbeaver#23202]
### Description

DBeaver constantly goes to "Not Responding" state and takes a long time to recover. It's typically if I make a syntax error and try to activate the query. DBeaver will tell me I have a syntax error and then go into a state of "Not Responding". It usually recovers but it takes about a minute of waiting. I have provided the thread dump to help with the situation. 

Is there any other information I can provide info on that I might have forgot?
[dbeaver-thread-dump.txt](https://github.com/dbeaver/dbeaver/files/14697175/dbeaver-thread-dump.txt)

### DBeaver Version

DBeaver Version 24.0.0.202403031740 Community Edition

### Operating System

Windows 10

### Database and driver

Database version: IBM Informix Dynamic Server Version 12.10.FC13
Driver: com.informix.jdbc.IfxDriver

### Steps to reproduce

1. Execute any query that has a syntax Error in Informix
2. Click anywhere in the app to do anything right after the application tells you that it's a syntax error.
This is when it freezes..

**Comment by Destrolaric** [comment]
@ChrisJEllis Hi, footage with the issue will be useful and logs might also help.
To obtain logs:
You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. 
Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual for DBeaver 23.0.3 please let me know and provide log files.

**Comment by WymaRogerJarrett** [comment]
I am getting the same problem with version 25.1.1 Community Edition on Windows 10
