### ISSUE TITLE
Data transfer QOL improvements

### ISSUE THREAD

**Issue by vmsh0** [dbeaver/dbeaver#23209]
**Is your feature request related to a problem? Please describe.**
The Data Transfer tool would take advantage from the following functionality:

1. It should be allowed to provide an export list in a more convenient way than pre-selecting the objects from the Navigator, e.g. from a file
2. There should be the option to continue on an error. I've currently been babysitting a data transfer for more than an hour that would have taken a few minutes if DBeaver would be able to recover from transient connection errors and permission errors on tables (i.e. just skip tables that can't be accessed and report back at the end)

An additional observation: when Data Transfer fails, the error message disappears after a while by itself. If you're not constantly watching the screen, you might either believe the data transfer was successful (potential disaster), or be confused about why it failed (frustrating)

**Comment by Destrolaric** [comment]
Hi, data transfer can be configured as a task in the CE edition. This will solve the first and third issues. Can you see if it will work for your case?
 https://github.com/dbeaver/dbeaver/wiki/Task-Management

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by vmsh0** [comment]
Hi,
Thank you for getting back to me and apologies for not getting back sooner.

Thank you for providing an additional way to perform the requested function.

I did take a look at it, but I ended up extracting the data with a Python script; it proved much quicker and simpler in the end, as it allowed me to work around all of the issues that I have described in the initial post.

**Comment by E1izabeth** [comment]
As far as I understood, the issue is solved.
