### ISSUE TITLE
Option to disable all metadata queries

### ISSUE THREAD

**Issue by emanueol** [dbeaver/dbeaver#23203]
---------------------------------------------------------
--TEST 1: when executing SQL queries in Snowflake, I see 2 extra queries done by dbeaver on same session:
![image](https://github.com/dbeaver/dbeaver/assets/8422412/fdfcfeaa-4c7c-4f70-8e0d-71dc45d9d73b)

--I found 2 settings to turn off suggested in:
[](https://github.com/dbeaver/dbeaver/issues/22637)

> preferences > editors > data editor >
    [ ] Read table metadata (unique keys)
    [ ] Read table references (foreign keys)

But that only removes one of the rogue metadata queries from being executed:
![image](https://github.com/dbeaver/dbeaver/assets/8422412/6731f2fd-2a20-41f5-9e51-6d2546889942)

---------------------------------------------------------
--TEST 2 - another test, simple disconnect/connect and execute 3 USE + query to grab all queries executed 
![image](https://github.com/dbeaver/dbeaver/assets/8422412/c2932519-4210-48e5-9c3a-b796d473891e)

I executed 4 queries but Snowflake says DBEaver executed 11 queries in total:
my 4 queries:
`
use role sysadmin;
use database db;
use schema s;
`

the 7 extra metadata queries that seems DBeaver enjoying doing on its own :(
`
--1st dbeaver query:
SELECT DISTINCT
  CASE TABLE_TYPE
    WHEN 'BASE TABLE' THEN 'TABLE' // For backward compatibility. 
    ELSE TABLE_TYPE
  END AS TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES;

--2nd dbeaver query:
SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();

--3rd dbeaver query:
SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();

--4th dbeaver query:
show /* JDBC:DatabaseMetaData.getCatalogs() */ databases in account

--5th dbeaver query:
show /* JDBC:DatabaseMetaData.getSchemas() */ schemas in database "DB"

--6th dbeaver query:
USE DATABASE DB;

--7th dbeaver query:
SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();
`

Is there any options to disable/prevent  DBEAVER from executing ANY queries on its own ?
If I execute 4 queries, I only want to see 4 queries executed in snowflake.

Thanks ~

**Comment by LonwoLonwo** [comment]
Hello @emanueol 

DBeaver uses this query to identify your current schema/database in the SQL Editor.

> SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();

![2024-04-17 14_08_32-Preferences](https://github.com/dbeaver/dbeaver/assets/45152336/aa0560a9-2474-4f73-b335-addd33336240)

Also, we now have a new idea. 
We can add a new setting on the Preferences -> Connections -> Metadata page.
Something like "Disable extra metadata reading".

This setting will disable all extra metadata queries. All metadata synchronization. 
Only direct requests will work (like navigator tree nodes expanding).
With all outdated metadata and with read-only data, maybe.

These settings will be disabled in the scope of "Disable extra metadata reading" enabling:

Metadata: Show row count for tables
Editors: Force object refresh on editor open
Data Editor: Read table metadata (unique keys)
Data Editor: Read table references (foreign keys)
SQL Editor: Save/restore active schema
Code editor: Read database table/columns for semantic analysis
SQL Processing: Refresh active schema after SQL Execution

**Comment by arhayka** [comment]
Probably fix https://github.com/dbeaver/dbeaver/issues/21774

**Comment by arhayka** [comment]
We decided to add info about conflicting settings to hints in Preferences:

<img width="531" alt="Screenshot 2024-06-05 at 13 01 14" src="https://github.com/dbeaver/dbeaver/assets/12581569/3f5c1fd2-b1dd-4206-a356-2488dc6d5232">

**Comment by rlroyarsa** [comment]
Has this actually been fixed?  That is, I'm trying to use Version 24.2.1.202409221725 - with various version of the Snowflake JDBC driver, and I can't find any way to disable the extra metadata queries.  I've tried all above (unchecking ALL of Metadata: Show row count for tables
Editors: Force object refresh on editor open
Data Editor: Read table metadata (unique keys)
Data Editor: Read table references (foreign keys)
SQL Editor: Save/restore active schema
Code editor: Read database table/columns for semantic analysis
SQL Processing: Refresh active schema after SQL Execution)

And I still get the extra queries, such as:
show /* JDBC:DatabaseMetaData.getForeignKeys() */ imported keys in database "ZZZZZ";

Which cause the whole tool to just hang forever in our environment because of the catalog.

Is there a way to truly turn off all the extra meta-data querying?

Thanks-
R

**Comment by pedrochans** [comment]
Hello, I also have this problem, specially in 25.0.1, some Snowflake metadata queries are taking so long:

![Image](https://github.com/user-attachments/assets/d5dc1a47-045a-44e8-a4a0-331f0965805c)

Is this solved ??

**Comment by pedrochans** [comment]
Just saw the solution in #35895

For readers in this issue, check the box Do not read tables information in sql and data editors

![Image](https://github.com/user-attachments/assets/00ba8e42-6f6a-492d-9ac1-ea7b2270b2d1)
