### ISSUE TITLE
Selecting active connection

### ISSUE THREAD

**Issue by mvelkavrh** [dbeaver/dbeaver#23211]
At first I'd like to thank you for a great product!

I was trying to find a way to select active connection from Database navigator pane without success.
I guess such an option actually doesn't exist.

If that's the case it would be great if one could pin "Select Data Source" dialog.
Or if this dialog could be shown as a pane, like DB navigator.
Or if "Link with editor" button got a sibling, functioning the other way - setting editor connection to the one selected in DB navigator.
Or any combination of above.

This would make applying the same sql statements in many connections easier/less annoying.

Thanks.

**Comment by ShadelessFox** [comment]
Hello @mvelkavrh,

Perhaps you're looking for this?

![image](https://github.com/dbeaver/dbeaver/assets/35821147/1c55af6c-45e4-41ab-9225-862ab07f0970)

**Comment by mvelkavrh** [comment]
Thanks @ShadelessFox,

But no - I know about this. But it would be more handy to have something like I've tried to describe above.

One of the options would look something like this, but with "Select Data Source" being a tab on the left pane, the same way as Database navigator and Projects:

![image](https://github.com/dbeaver/dbeaver/assets/164540629/6a018efa-2d2c-4678-818d-a575124566ea)

**Comment by ShadelessFox** [comment]
Thank you for clarifying.

I believe this can be done by using the **SQL Editor** -> **Set connection from navigator** action, or **Ctrl+Shift+Dot** while focusing the editor.

**Comment by mvelkavrh** [comment]
Wow, indeed - but while focusing navigator, not editor.

Thank you!

**Comment by ShadelessFox** [comment]
My bad, thanks for correcting me.

As the issue is now resolved, I will close the ticket. Feel free to ask any other questions here or create a new ticket if needed.
