### ISSUE TITLE
Wording change on db export confirmation dialog (override -> overwrite)

### ISSUE THREAD

**Issue by mcsilver** [dbeaver/dbeaver#23215]
### Description

In my opinion, the word "override" should be "overwrite" in the following confirmation dialog:

![DBeaver-Wording-Change](https://github.com/dbeaver/dbeaver/assets/2747224/39758975-a955-4c0a-ace6-e507ea86b4b7)

(You get this dialog when dumping a MySQL database.)

Rationale: You override something when you leave it intact but substitute it for something else. However, when exporting the database, the confirmation dialog is confirming that it's okay to _overwrite_ an existing file (replace it completely).

### DBeaver Version

Community Edition 24.0.0.202403031740

### Operating System

Windows 11

### Database and driver

MySQL (where's the version???)

### Steps to reproduce

Right click on a MySQL database.
Tools > Dump database > Next > Start

**Comment by E1izabeth** [comment]
Thank you for paying attention to the messages. It makes sense to change it this way.

**Comment by mcsilver** [comment]
My pleasure! Keep up the great work.

[Description: ***@***.***
Craig Silver
Owner Operator
t. 604-339-7417 | e. ***@***.******@***.***>
computer services with a personal touch
