### ISSUE TITLE
24.0.1 fails to start

### ISSUE THREAD

**Issue by swiffer** [dbeaver/dbeaver#23218]
### Description

![grafik](https://github.com/dbeaver/dbeaver/assets/2990373/a4f22c5a-c57c-4eff-a3d5-f671d084ce40)

### DBeaver Version

24.0.1

### Operating System

Windows 11 Pro 23H2 22631.3296

### Steps to reproduce

Upgrade to DBeaver 24.0.1 (User Install (AppData))

**Comment by serge-rider** [comment]
Can't reproduce.
- How do you install DBeaver? (Windows installer, zip archive).
- Have you tried to install Early Access version before?
- Please attach contents of `dbeaver.ini` file (it is located in the installation folder

Possible workarounds: 
- delete folder `%APPDATA%\DBeaverData\install-data`
- reinstall DBeaver

**Comment by swiffer** [comment]
uninstalled, deleted the folder, reinstalled - working fine now - sorry, might have been an oversight on my end (think i have not selected to include java yesterday).
