### ISSUE TITLE
date conversion dd.mm.yy from csv import to MS SQL database mixes up dd and mm

### ISSUE THREAD

**Issue by andrematzke** [dbeaver/dbeaver#23212]
### Description

date conversion dd.mm.yy from csv import to MS SQL database converts to yyyy-dd-mm, 
instead of yyyy-mm-dd, so the ISO date is wrong then, and even fails if dd from dd.mm.yy is too high to be a month.

So, if I have a (german) 02.11.22 (dd.mm.yy) in my csv, which means : 11/02/2022 in english date (mm/dd/yyyy), the result in datetime should be: 2022-11-2, but it is 2022-02-11, which is 11.02.22 .. so the importer is doing a wrong conversion.
  

### DBeaver Version

Version 24.0.0.202403091004 community edition

### Operating System

Mac OSX 14.1.1 (23B81)

### Database and driver

Database SQL Server 2019

### Steps to reproduce

- prepare a table with datetime field
- prepare a csv, in the first line the table-field name, from 2nd then 2 lines with dates: one 11.02.22 and one 16.08.22
- right mouse click on our database table --> import
- choose csv type -> Next
- browse for the prepared csv
- choose import parameter, in source date props say dd.mm.yy 
![Screenshot 2024-03-22 at 21 49 54](https://github.com/dbeaver/dbeaver/assets/33298027/b5d931a7-53c9-4a00-930e-48e88bdf139a)
--> next
- check data and mapping
- proceed import
- 1 import will work but with ISO Date 2022-11-02, which should have been 2022-02-11
- 1 import will fail, because instead MM = 08, it will try to parse the DD field into a month, and there is no 16th month

**Comment by ShadelessFox** [comment]
Hello @andrematzke,

The date/time pattern is case-sensitive. In your case, it should be `dd.MM.yy`. Please let me know if it helps.

For more information, please refer to the following docs (can be found by hovering the property in DBeaver):
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#patterns

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
