### ISSUE TITLE
No confirmation on closing a modified .sql file

### ISSUE THREAD

**Issue by Condor70** [dbeaver/dbeaver#23230]
If you open an .sql file from disk, modify it and then close it, the file is automatically saved.

I have accidentally overwritten several common queries i had stored for repeated use this way.

Could you add a confirmation dialog when closing a modified file (Save/Discard/Cancel)?

**Comment by ShadelessFox** [comment]
Hello @Condor70,

Perhaps you have this option enabled?

![Image](https://github.com/dbeaver/dbeaver/assets/35821147/8c2a2ef6-7def-4dd6-a416-09e684d7ac85)

**Comment by Condor70** [comment]
You are completely correct. No idea how this option got activated.
Or is auto-saving the default option? That would be bad!

**Comment by ShadelessFox** [comment]
No, it's turned off by default. Call the Ghostbusters! You might have ghosts in your house who write SQL while you are asleep :^)
