### ISSUE TITLE
Problems with connect to database using the same configuration that can connect from other PC

### ISSUE THREAD

**Issue by franciscoguerrero86** [dbeaver/dbeaver#23233]
### Description

I´m using the same configuration as my college. Appears the error:

Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
  Connect timed out
  Connect timed out

![image](https://github.com/dbeaver/dbeaver/assets/163907387/84375ff2-4bc7-4ec4-b542-8f78181ed7af)

![image](https://github.com/dbeaver/dbeaver/assets/163907387/09acf52d-9abb-46ea-aa4f-cec54a9897a7)

Have you any idea how to check and solve this?

Regards

### DBeaver Version

24.0.1.202403241413

### Operating System

Windows 11

### Database and driver

MySQL

### Steps to reproduce

1. I try connect to db
2. I push double click
3. the error appears after 20-30 seconds

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
