### ISSUE TITLE
Remove 'use short object names' from SQL preferences

### ISSUE THREAD

**Issue by EvgeniaBzzz** [dbeaver/dbeaver#23239]
Interface - Editor - SQL Editor - Code Completion

There are two mutually exclusive options:
- Use short object names
- Use long object names

Looks like 'use short' is not needed
nothing - short
'short' - short
'long' - long
both - long

![image](https://github.com/dbeaver/dbeaver/assets/139753579/4c849e84-ef16-4e12-b844-330e5daa7ce1)

**Comment by LonwoLonwo** [comment]
Major status because this setting is connected with CloudBeaver preferences

**Comment by LonwoLonwo** [comment]
We need to create combo box with default/short/long values
