### ISSUE TITLE
Unable to modify the Workbenche theme (colour)

### ISSUE THREAD

**Issue by fsalva93** [dbeaver/dbeaver#23253]
### Description

I downloaded the new version Dbeaver 24.0.1 and my colour workbenche returns to default. I want to continue using the Dark theme but I can't see the option. Someone knows how can I do it? Thanks

### DBeaver Version

Dbeaver 24.0.1

### Operating System

windows

**Comment by E1izabeth** [comment]
Are you talking about Darkest Dark plugin?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
