### ISSUE TITLE
SAP IQ procedure definition query has changed and all original indentation is lost

### ISSUE THREAD

**Issue by zolovey** [dbeaver/dbeaver#23259]
### Description

SAP IQ procedure definition query has changed compared to 24.0.0 and all original indentation is lost

Most likely after https://github.com/dbeaver/dbeaver/commit/2e2e5fafdb46ce10954d70df8a37473d1e0c21bc implementation

### DBeaver Version

CE 24.0.1

### Database and driver

SAP IQ, 16.1.050.2532
Driver: jConnect (TM) for JDBC (TM) jConnect (TM) for JDBC(TM)/20.00.000.01(Build 27499)

### Steps to reproduce

Open definition of procedures in 24.0.0 and compare same procedure in 24.0.1

in 24.0.1 original indentation is lost
![image](https://github.com/dbeaver/dbeaver/assets/56155099/38145a3c-8cb9-420c-bd73-22e086834c42)

![VdvOl1lDI6](https://github.com/dbeaver/dbeaver/assets/56155099/ba52b058-4f62-46b0-a08c-74150dd2a7e4)

**Comment by LonwoLonwo** [comment]
Hello @zolovey 

We changed the source of procedures definition. Previously, we used sysobjects system table. And now, we are reading from SYS.SYSPROCEDURE, because it returns procedures DDL more correctly for big procedures.

**Comment by zolovey** [comment]
@LonwoLonwo isn't it so that you have used sys.syssource for SAP IQ DB objects?

SYSSOURCE.source contains the original source code for the object.

https://help.sap.com/docs/SAP_IQ/a898e08b84f21015969fa437e89860c8/3bea22036c5f10148027ceb50bfb8bba.html?locale=en-US

And SYSPROCEDURE.proc_defn contains definition of the procedure after it has been parsed and unparsed by the database server. So without original formatting which sometimes leads to unreadable code

https://help.sap.com/docs/SAP_IQ/a898e08b84f21015969fa437e89860c8/3be97af56c5f1014a1b1a537360ec408.html?locale=en-US

**Comment by zolovey** [comment]
seems that here is similar issue - https://github.com/dbeaver/dbeaver/issues/23260

**Comment by LonwoLonwo** [comment]
Ok, I will check it

**Comment by E1izabeth** [comment]
Seems the new way of reading source also caused this bug #23247
