### ISSUE TITLE
Double quotes on source stored procedures view

### ISSUE THREAD

**Issue by Obyzzz** [dbeaver/dbeaver#23260]
### Description

When I look at the code of a procedure (or generate DDL), the objects appear with double quotes since DBeaver version 24.0.1,
but were not declared with quotes at creation
![Captura_3818](https://github.com/dbeaver/dbeaver/assets/93196033/ace8eeff-8c95-491c-8915-459a316834ad)

### DBeaver Version

24.0.1

### Operating System

Windows 11

### Database and driver

SAP Sybase IQ jconnect

### Steps to reproduce

1st Create procedure
![image](https://github.com/dbeaver/dbeaver/assets/93196033/5a919a5c-0057-484c-b18a-0add997a08cf)
2nd View procedure created
![image](https://github.com/dbeaver/dbeaver/assets/93196033/66b115ca-0754-49f8-8da2-62cdc13f40a7)
3rd We can see double quotes on code
![image](https://github.com/dbeaver/dbeaver/assets/93196033/7eca8b4f-04c2-4bdb-8095-25682afcb03e)

**Comment by LonwoLonwo** [comment]
Hello @Obyzzz 

We changed the source of procedures definition. Previously, we used sysobjects system table. And now, we are reading from SYS.SYSPROCEDURE, because it returns procedures DDL more correctly.

So, I do not see any errors here. Many databases use quotes for **all** objects in the definition. 
So, please explain why it is inconvenient for you.

**Comment by Obyzzz** [comment]
Hello LonwoLonwo,

Sometimes it happens that we have to get the code from the server instead of a repository. If we obtain the code full of double quotes, when we go to recreate it in a "case sensitive" database like Snowflake, it will fail. So if it can be (pleeease), can you include an option to obtain DDL from "source FROM sys.sysprocedure" and another for "proc_defn FROM sys.sysprocedure" please?
I'll have to pin to version 24.0.0 in the meantime.

Thank you very much for your work

**Comment by arhayka** [comment]
We hope it will be fixed in https://github.com/dbeaver/dbeaver/issues/23259
So I close this ticket as a duplicate.
