### ISSUE TITLE
Error connecting to Solr

### ISSUE THREAD

**Issue by LottarWolf** [dbeaver/dbeaver#23264]
### Description

I cant connect to a solr core, I get this error:

Unexpected driver error occurred while connecting to the database
  java.util.concurrent.TimeoutException: Could not connect to ZooKeeper xxx.xxx.xxx.xxx:9983/ within 15000 ms
  java.util.concurrent.TimeoutException: Could not connect to ZooKeeper xxx.xxx.xxx.xxx:9983/ within 15000 ms
    Could not connect to ZooKeeper xxx.xxx.xxx.xxx:9983/ within 15000 ms
    Could not connect to ZooKeeper xxx.xxx.xxx.xxx:9983/ within 15000 ms

-------------------------------------------------------------------------------------

OS Version
Edition	Windows 10 Home Single Language
Version	22H2
Installed on	‎2021-‎03-‎19
OS build	19045.4170
Experience	Windows Feature Experience Pack 1000.19054.1000.0

### DBeaver Version

Community Edition 24.0.1.202403241413

### Operating System

Windows 10 Home x64

### Database and driver

solr-impl-version: 6.4.0 bbe4b08cc1fb673d0c3eb4b8455f23ddc1364124 - jim - 2017-01-17 16:01:31
solr-solrj-9.21.jar
Class Name: org.apache.solr.client.solrj.io.sql.DriverImpl

### Steps to reproduce

Following the connection wizard y place the next information.

Host:
Port:
Database/Schema
No User/No Password

And when I test the conenction I get the error message.

### Additional context

I use a vpn to access the server where solr is installed.

**Comment by LonwoLonwo** [comment]
Hello @LottarWolf 

Are you sure that this is DBeaver issue? It can be incorrect connection specifications, not enough rights to use the Internet from DBeaver, or VPN restrictions. Anything.

**Comment by LottarWolf** [comment]
Hello Anastasiya, thank you for your reply, I´m not sure about your
question, can you give me advice on how I can check what you mention?

**Comment by LonwoLonwo** [comment]
Could you connect to your database using any other tool?

**Comment by LottarWolf** [comment]
I can connect using the web interface.

[image: image.png]

**Comment by LonwoLonwo** [comment]
Did you try to use different ports in your connection settings?
https://solr.apache.org/guide/6_6/getting-started-with-solrcloud.html
8983? 8987?

**Comment by LottarWolf** [comment]
Yes, I tried with the ports you mentioned and still get the error.

**Comment by ShadelessFox** [comment]
Perhaps you could find any helpful information here? https://github.com/orgs/dbeaver/discussions/572

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
