### ISSUE TITLE
Show the new line in the middle of the screen

### ISSUE THREAD

**Issue by ffbh123456** [dbeaver/dbeaver#23266]
As you can see in the image, the new line I added by clicking the '+' icon appears at the bottom of the screen. When I attempted to scroll, it only shifted two lines up, leaving it near the bottom. I prefer to have it scroll to the middle or top of the screen for more comfortable editing, as I prefer not to look at the bottom of the screen for too long
<img width="771" alt="Screenshot 2024-03-28 at 12 26 31 PM" src="https://github.com/dbeaver/dbeaver/assets/20750357/a17ba97a-045b-451c-9c3f-6bb384064bde">

**Comment by humphreygao** [comment]
你点左边的Record试试？

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
