### ISSUE TITLE
DBeaver 24.0.1 silently crashes when requesting parquet file via DuckDb

### ISSUE THREAD

**Issue by Alexey-Stolyarov** [dbeaver/dbeaver#23277]
### Description

DBeaver 24.0.1 silently crashes when requesting parquet file via DuckDb. 
The query is like `select * from read_parquet('path to parquet') limit 200'
The same query works fine with v23.3.5

### DBeaver Version

24.0.1

### Operating System

Win11

### Database and driver

Server: DuckDB v0.9.1
Driver: DuckDBJ 1.0

### Steps to reproduce

1. Create new database via new connection dialog (file based)
2. Write query `SELECT * from read_parquet('c:\work\fmt=parquet\*.parquet') limit 200`
3. Execute query
4. DBeaver main window immediately disappeared and closed.

**Comment by ShadelessFox** [comment]
Hello @Alexey-Stolyarov,

Can you please provide JVM crash logs? You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files#java-fatal-logs

Can you also try updating the driver to the latest version (0.10.0) to see if the issue is gone there?

**Comment by Alexey-Stolyarov** [comment]
Hi @ShadelessFox, I've installed back the latest version of DBeaver (24.0.1) and updated the DuckDB driver to DuckDBJ 1.0  and server to DuckDB v0.10.0 and issue gone. The reason why I used v0.9.1 was in performance of DuckDB with wide tables introduced in the latest versions. 

I've rolled back to driver v0.9.1 and issue reproduced. Java fatal log is attached.
[hs_err_pid7828.log](https://github.com/dbeaver/dbeaver/files/14805457/hs_err_pid7828.log)

Thank you!

**Comment by ShadelessFox** [comment]
Thanks. I just wanted to ensure the issue is on the driver's side.

Unfortunately, I can't find a correlation between the crash and the newer version of DBeaver, so I can't tell what might be the culprit besides an undefined behavior in the old version of the driver.

It looks like you will have to update the driver to the latest version anyway. Maybe they've improved the performance as well.

**Comment by ShadelessFox** [comment]
Please let me know if the issue can be considered resolved.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
