### ISSUE TITLE
Not able to view the list of objects on the left panel 

### ISSUE THREAD

**Issue by Kimmikanuyi** [dbeaver/dbeaver#23288]
### Description

At DBever tool,  when we click on the left panel to see list of tables or views,  we get error code 
DB2 SQL ERROR :SQLCODE=-471, SQLSTATE=55023,SQLERROR=SYSIBM.SQLTABLES,00F30091,DRIVER=3.57.82 

any idea what happen ?  thansk 

### DBeaver Version

23.3.2

### Operating System

windows

**Comment by Kimmikanuyi** [comment]
to connect to Db2 zOS v12

**Comment by LonwoLonwo** [comment]
Hello @Kimmikanuyi 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by Kimmikanuyi** [comment]
[dbeaver-debug-1712022698136.log](https://github.com/dbeaver/dbeaver/files/14833013/dbeaver-debug-1712022698136.log)

Dear @LonwoLonwo ,   I attached the log file.   Appreciate your help ....thanks thanks thanks

**Comment by LonwoLonwo** [comment]
Did you use this connector to your database? This one?

![2024-04-02 09_33_30-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/002db8de-2af2-4d89-8219-117e69ced8d3)

What driver do you use? You can find this info in your connection settings -> "test connection" button

**Comment by Kimmikanuyi** [comment]
Hi,  I found out the root cause.   It's connecting to DB2 on zOS.  
Apparently the RRS/MVS component wasn't up running.  Thus users received 00F30091 error code.   
[Doc1.docx](https://github.com/dbeaver/dbeaver/files/14854676/Doc1.docx)

Started the RRS on zServer,  everything is running OK now.   

Thank you so much for your time to help me out here ,  appreciate it very much !

**Comment by Kimmikanuyi** [comment]
thank you so much for your valuable time & effort :)    Cheers ...

**Comment by LonwoLonwo** [comment]
Thanks for the update!
