### ISSUE TITLE
Database i created dissapeared after reopen the Dbeaver

### ISSUE THREAD

**Issue by Slimand** [dbeaver/dbeaver#23284]
### Description

i created new postgres connection in Dbeaver and i created new database it is called "testflyway", it worked well, but after i close the Dbeaver and open it again i dont find my database i previously had created, and when i use this command "SELECT datname FROM pg_database WHERE datname = 'testflyway';" to find the database, i find it, so i drop it and i created again, but after i close the Dbeaver and reopen it again i have the same problem

### DBeaver Version

Community edition 24.0.1

### Operating System

Micorsoft Windows 11 pro

### Steps to reproduce

psql (PostgreSQL) 15.3

**Comment by Matvey16** [comment]
@Slimand Hello. Do you initially connect to another database (in connection settings) and then create a new one (in navigator UI or by running a query in sql editor?) that is not visible after restart?

If that's the case, p;ease check your connection settings that change visibility of all databases other than the one used for the connection.

![dbeaver_u8eY87u9kp](https://github.com/dbeaver/dbeaver/assets/82543000/ea4dcb46-0541-4177-83ec-6cf2dbfae9b3)

![dbeaver_yIptbIj0GA](https://github.com/dbeaver/dbeaver/assets/82543000/79c399cd-8698-4c40-a737-38c7f7405b28)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
