### ISSUE TITLE
Content Loss in DBeaver Editor after a certain number of lines

### ISSUE THREAD

**Issue by xnnzh** [dbeaver/dbeaver#23285]
### Description

When the content reaches a certain number of lines, I have observed that a portion of the content in the middle gets lost, as if there is a triangular mask covering the content.
![test](https://github.com/dbeaver/dbeaver/assets/14057796/c70e3f2b-6981-4a7f-83e3-9ac84cfec413)

### DBeaver Version

Community Edition 24.0.1.202403241413

### Operating System

MacOS Sonoma 14.4 (15-inch,2019)

### Database and driver

1. Database name and version: MySQL 5.7
2. Driver name and version: MySQL JDBC Driver 8.0.33

### Steps to reproduce

Add SQL content until the editor contains a large amount of lines (not specific to the particular SQL as below).

```mysql
select t.table_schema, 
    t.table_name, 
    t.column_name, 
    t.data_type, 
    t.column_comment, 
    t.character_maximum_length column_length, 
    t.numeric_precision, 
    t.numeric_scale,
    (case when t.is_nullable = 'YES' then 0 else 1 end) required_flag, 
    t.column_default,
    (case when t.column_key = 'PRI' then 1 else 0 end) primary_key_flag
from information_schema.columns t
where t.table_schema = 'xx'
and t.table_name in ('xx');
```

**Comment by Matvey16** [comment]
It looks like another case of #22299 on Sonoma

Please try the workaround mentioned in this comment https://github.com/dbeaver/dbeaver/issues/22299#issuecomment-1910602876 to confirm if that's the same issue
