### ISSUE TITLE
Unable to set table comment to empty

### ISSUE THREAD

**Issue by Inasayang** [dbeaver/dbeaver#23280]
### Description

When clearing comment from a table, the sql will be `ALTER TABLE db.table;`

not `ALTER TABLE db.table COMMENT='';`

### DBeaver Version

Community Edition 24.0.1.202403241413

### Operating System

Windows 11

### Database and driver

MySQL

### Steps to reproduce

1. clearing comment from a table

**Comment by LonwoLonwo** [comment]
Hello @Inasayang 

Thanks for the report.
