### ISSUE TITLE
Broken text display

### ISSUE THREAD

**Issue by sequencerr** [dbeaver/dbeaver#23305]
### Description

![image](https://github.com/dbeaver/dbeaver/assets/45060278/1b0f30ce-d2b6-45b2-8dda-598fde488939)

### DBeaver Version

CE 24.0.1

### Operating System

win 10

**Comment by ShadelessFox** [comment]
Hello @sequencerr,

Please provide more information regarding your issue.

Is this the first time you installed DBeaver, or were you using an older version and decided to update? If so, what version did you use before that? Was the issue present there?

Additionally, please try resetting UI settings to see if it helps. You can find related information here: https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings#reset-settings

**Comment by sequencerr** [comment]
Hi. I've just installed it for very first time using zip. Resetting doesn't help.

**Comment by LonwoLonwo** [comment]
Hello @sequencerr 

Maybe this tip will help you: https://github.com/dbeaver/dbeaver/issues/20123#issuecomment-1572614592

**Comment by sequencerr** [comment]
Dupe of #20123, #20190
