### ISSUE TITLE
About how to display the title of script panels

### ISSUE THREAD

**Issue by upaccount** [dbeaver/dbeaver#23301]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open many panels , many script panels, table panels, it just only can display the connect database. 
For example: <Postgre.Em...  <Postgre.Em...  <Postgre.Em... 
I can't distinguish between these files.

**Describe the solution you'd like**
to only display the file name is OK, the connect database has showed in toolbar.

**Describe alternatives you've considered**
the connected database can appears in the tip or after the filename.

**Comment by ShadelessFox** [comment]
Hello @upaccount,

You can change tab names for scripts here:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/1ed8a799-786b-4424-bab6-643468fe1cf4)

Please let me know if it solves your issue.

**Comment by upaccount** [comment]
yes, it can work, thanks a lot

**Comment by ShadelessFox** [comment]
As the issue is resolved, I'm going to close the ticket. Feel free to ask any other questions.
