### ISSUE TITLE
Queries not saved in console on exit

### ISSUE THREAD

**Issue by bakoontz2** [dbeaver/dbeaver#23313]
### Description

Queries in SQL console aren't being saved on exit, despite setting SQL Editor options "Auto-save after any modifications" and "Auto-save editor on close."

### DBeaver Version

Community Version 24.0.1.202403241413

### Operating System

Windows 10E

### Database and driver

Azure Databricks

### Steps to reproduce

0. In Preferences, check "Auto-save after any modifications" and "Auto-save editor on close."
1. Open SQL Console
2. Type a query
3. Exit DBeaver
4. Restart DBeaver.  Contents are not restored.

**Comment by ShadelessFox** [comment]
Hello @bakoontz2,

Consoles are designed this way - they don't persist any data when you close them.

But you can press CTRL+S while in the console to turn it into a standard SQL editor and save the script.

**Comment by bakoontz2** [comment]
Guess I missed that in the docs.  Thanks for the quick clarification, live and learn!
