### ISSUE TITLE
result grid shows columns as wrong type

### ISSUE THREAD

**Issue by kartas39** [dbeaver/dbeaver#23311]
### Description

![image](https://github.com/dbeaver/dbeaver/assets/9109375/a75d09b7-4ddf-4a4a-914a-e70e30a142bb)

As you can see, metadata for column CreatedDate is Datetime2, but result grid displays as type of Second column in subselect (IsDeleted)

### DBeaver Version

Community Edition 24.0.1

### Operating System

Windows

### Database and driver

MSSQL, driver version 12.6.1

### Steps to reproduce

run query 
select field_1, field_3 from (select field_1, field_2, field_3 from table_abc)
result grod will show field_3 as type of field_2 from subquery

**Comment by ShadelessFox** [comment]
Hello @kartas39,

Can you please provide a DDL of your table or a shorter example so we can reproduce the issue?

**Comment by kartas39** [comment]
@ShadelessFox well, you can create any table, it is 100% reproducible

create table dbo.test1 (
    col_int int,
    col_bool bit,
    col_vc varchar(10),
    col_dt datetime2
);

select 
    col_dt,
    col_vc,
    col_bool,
    col_int
from (
    select 
        col_int,
        col_bool,
        col_vc,
        col_dt 
    from dbo.test1
) a

![image](https://github.com/dbeaver/dbeaver/assets/9109375/7eb7e933-cc34-443a-8d8e-4cf5c752be4d)

**Comment by ShadelessFox** [comment]
Now I see the issue, thanks. The columns listed are in the reverse order, but DBeaver resolves them as if they weren't reversed.

**Comment by kartas39** [comment]
seems to be fixed

**Comment by E1izabeth** [comment]
@kartas39 thanks for update. I'm glad to hear that
