### ISSUE TITLE
Syntax error occured when using stored procedure in Vertica

### ISSUE THREAD

**Issue by ych-ot** [dbeaver/dbeaver#23324]
### Description

It was OK in vsql or DbVisualizer but executed in DBeaver it failed with error messages "Missing a matching closing delimiter in statement " or "Syntax error at or near "n_Cnt" at character 7"

### DBeaver Version

Community Edition 24.0.1.202403241413

### Operating System

Windows 11

### Database and driver

Database name: Vertica 23.4.0.7
Client: Vertica JDBC 23.4.0.7

### Steps to reproduce

```sql
CREATE OR REPLACE PROCEDURE TEST1()
LANGUAGE PLvSQL AS 
$$
DECLARE
    i INT := 1;
BEGIN
    WHILE true LOOP
        IF i = 10 THEN
            EXIT;
        END IF;
    
        i := i + 1;
        
        RAISE NOTICE 'i [%]', i;
    END LOOP;
END;
$$;
```
--> Missing a matching closing delimiter in statement

```sql
CREATE OR REPLACE PROCEDURE TEST2()
LANGUAGE PLvSQL AS 
$$
DECLARE
        n_Cnt               INT;  
BEGIN 
        n_Cnt := 0;
        IF ( n_Cnt = 1 ) THEN
            RETURN  ;
        END IF;
END;
$$;
```
--> syntax error at or near "n_Cnt

**Comment by LonwoLonwo** [comment]
Hello @ych-ot 

Did you try to highlight the whole procedure creation query and then execute it?

**Comment by LonwoLonwo** [comment]
Ok, I see. Highlighting helps, but we need to parse this query more precisely.
Thanks for the bug report.

**Comment by E1izabeth** [comment]
As a workaround, you can set `Show $$ quotes as` setting to `String literal` in Connection Configuration
![image](https://github.com/dbeaver/dbeaver/assets/28875055/b7c0dd04-dba0-4cf9-97b3-6a2e36940d58)

**Comment by E1izabeth** [comment]
The issue can be solved only after https://github.com/dbeaver/dbeaver/issues/15542
