### ISSUE TITLE
Custom dashboard chart removed after installing new version

### ISSUE THREAD

**Issue by alesc2000** [dbeaver/dbeaver#23335]
### Description

I made a copy of "Server sessions" chart of PostgreSQL, and altered the chart query to my needs. But after each version update it disappears. So after each update I need to add it again and also add it to Dashboard.
![image](https://github.com/dbeaver/dbeaver/assets/19900533/bca9cec2-81f9-42c6-8437-babf3f7b1ec3)
![image](https://github.com/dbeaver/dbeaver/assets/19900533/04a27e2d-bfbf-4236-9401-23f24b03e85a)

### DBeaver Version

24.0.2.202404071654

### Operating System

Linux Mint

### Database and driver

PostgreSql 14

**Comment by serge-rider** [comment]
Thanks for the bug report.

In version 24.0.2 we changed the format of dashboards configuration storage. It is a bug in the migration process.
After version 24.0.2 dashboard config shouldn't reset.

Anyway, we will fix the bug in the dashboards migration.
