### ISSUE TITLE
Can't connect to Sql Server with Microsoft Active Directory Integrated

### ISSUE THREAD

**Issue by simonsk90** [dbeaver/dbeaver#23331]
### Description

When I try to connect, I'm asked to download driver libraries. I tried lots of times, and tried deleting and reseting, but no luck. The error I get is this:

Failed to load both mssql-jdbc_auth-12.4.1.x64 and MSAL4J Java library for performing ActiveDirectoryIntegrated authentication. Please install one of them to proceed.

Then I tried to add the files manually, like this:

![image](https://github.com/dbeaver/dbeaver/assets/8894931/2c0546c2-d1f8-4832-b27d-eb06bcab6355)

But I still get the same error.

Im using Ubuntu, and this is the reponse of "java -version":
openjdk version "11.0.22" 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1)
OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1, mixed mode, sharing)

### DBeaver Version

24.0.1

### Operating System

Ubuntu 22.04

### Database and driver

driver name: SQL Server 
driver class name: com.microsoft.sqlserver.jdbc.SQLServerDriver

**Comment by arhayka** [comment]
Hi @simonsk90 
Please try to download the missing library here:  https://mvnrepository.com/artifact/com.microsoft.azure/msal4j
And then add it manually by pressing **Add File**.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
