### ISSUE TITLE
The Restore Defaults doesn't work for the SQL Editor Formatting settings

### ISSUE THREAD

**Issue by kseniaguzeeva** [dbeaver/dbeaver#23343]
### Description

The Restore Defaults button doesn't return any default values for the SQL Editor Formatting settings

### DBeaver Version

24.0.2

### Operating System

Win10

### Steps to reproduce

1. go to Preferences > Editors > SQL Editor > Formatting
2. change any settings and press The Restore Defaults button

AR: no visible changes

https://github.com/dbeaver/dbeaver/assets/112612526/eee30a2d-9722-4e98-bc31-7912e418c7e6

ER: default values are set for the settings

**Comment by MashaKorax** [comment]
verified
