### ISSUE TITLE
[CrateDB] Can't create table in data import

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#23350]
### Description

During import the DDL to create table would always have nullability argument in it wich leads to an error in CrateDB. The same bug is also present in generated DDL of any existing table.

### DBeaver Version

24.0.2

### Operating System

Any

### Steps to reproduce

1. Open import wizard
2. Select any CSV file
3. Set mapping to create
4. Start the import

**Expected:** Table is created
**Actual:** SQL error

**Comment by Matvey16** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/dbeaver/project/8805?defectId=15223)

**Comment by surister** [comment]
CrateDB added NULL constraint in 5.6, https://cratedb.com/docs/crate/reference/en/5.6/appendices/release-notes/5.6.0.html could you check if the error still persist in >=5.6 versions?
