### ISSUE TITLE
DBeaver unable to re-establish secure tunnel

### ISSUE THREAD

**Issue by rotorboy** [dbeaver/dbeaver#23359]
### Description

Since upgrading to DBeaver 24.0.1, after initial successful connection to DB via secure SSH tunnel, DBeaver disconnects SSH tunnel at some point, and is no longer able to invalidate/reconnect to DB via secure tunnel properly.

The following error occurs after invalidate/reconnect is attempted

SQL Error [08000]: Could not connect to address=(host=127.0.0.1)(port=23363)(type=master) : Socket fail to connect to host:127.0.0.1, port:23363. Connection refused

### DBeaver Version

CE 24.0.2

### Operating System

macOS 12.1

### Database and driver

JDBC

### Steps to reproduce

Connect to DB via SSH Tunnel
Allow tunnel to time out
attempt to reconnect 

### Additional context

using SSH tunnel

**Comment by ShadelessFox** [comment]
Hello @rotorboy,

What authentication method for SSH are you using?

Can you please provide log files? Instructions are here: https://github.com/dbeaver/dbeaver/wiki/Log-files. Please note that the logs will contain sensitive information, such as domain names and SSH usernames.

**Comment by laundmo** [comment]
Everyone at my workplace has been experiencing the same error, using Agent authentication and the JSch implementation.
At some point, the tunnel doesn't re-establish itself causing errors. It feels like this happens randomly, but i suspect its more to do with a timeout of some sort.

(Version 24.0.2)

**Comment by ShadelessFox** [comment]
The issue seems only to be related to the Agent authentication.

**Comment by rotorboy** [comment]
Now that it’s repeatable, do you still require logs? -AviOn Apr 10, 2024, at 09:31, ShadelessFox ***@***.***> wrote:﻿
The issue seems only to be related to the Agent authentication.

**Comment by ShadelessFox** [comment]
No, not for now. We're going to try reproducing the issue. I'll let you know if we still need logs.

**Comment by Matvey16** [comment]
Thank you for the report, I reproduced this bug.

It happens only with JSch implementation and Agent authentication. Can be reproduced with any manual internet connection disruption.

**Comment by rotorboy** [comment]
It should be noted that the issue only occurs when “auto” invalidate/reconnect happens; if I remember to MANUALLY invalidate/reconnect PRIOR to running a new query, the reconnection works properly...

**Comment by richardliechty** [comment]
Just wanted to add that I'm experiencing similar behavior going through an SSH tunnel using a Public Key. The connection is not reestablished doing an auto or manual invalidate/reconnect. The only way to reestablish the connection is to perform a manual disconnect and connect operation.

> Can't open editor connection
> Communications link failure
> The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

Let me know if you need more info. Thanks.

**Comment by lemon-juice** [comment]
I'm using password authentication method with JSch and experience this issue but with the error message as above:

> SQL Error [08S01]: Communications link failure
> The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

Interestingly, when I press "Test tunnel configuration" the connection succeeds. However, trying to test the main connection to the MySQL server results in the error above. Usually, this happens after I wake up the computer from sleep and I can't reconnect to the database - the only thing that works is to close and restart DBeaver.

**Comment by Amitkad** [comment]
@E1izabeth or @ShadelessFox 
This issue really affects my work. therefore two questions:
1. is there a way to minimize the times that it happens? (i.e by increasing the threshold the it requires invalidation etc)
2. in which version or when should I expected that to be published? (is there a nightly version? i prefer it ven if it is less stable)

**Comment by E1izabeth** [comment]
@Amitkad the fix will be available in the next release (24.0.3). Also you can download early access version here https://dbeaver.io/files/ea/

**Comment by kahyong-gvrn** [comment]
i am on 24.0.5, the issue still exists.
unable to reconnect. also ssh tunnelling.
on ubuntu 24
