### ISSUE TITLE
ER diagram foreign key

### ISSUE THREAD

**Issue by Sp0rtb1lly** [dbeaver/dbeaver#23362]
### Description

Since the version 24.0, in ER Diagram, the foreign key are not well designed.
When you select the link between two tables, all the foreign key columns are not underlined, as they were previously.

**Example**
>Version 24.0.1: 
![2024-04-09_09h47_20](https://github.com/dbeaver/dbeaver/assets/166487529/9a1a8bac-3df3-460d-b89c-e6b5892a1256)

>Version 23.3.2:
![2024-04-09_09h49_56](https://github.com/dbeaver/dbeaver/assets/166487529/146cfd11-82e5-4f12-8ec8-ee2510c9af8f)

Script to reproduce:
```
CREATE TABLE Customers (
	customer_id int NOT NULL,
	name varchar(50) NOT NULL,
	CONSTRAINT PK_Customers PRIMARY KEY (customer_id,name)
);

CREATE TABLE Orders (
	order_id int NOT NULL,
	amount decimal(10,2) NULL,
	customer_id int NULL,
	name varchar(50) NULL,
	CONSTRAINT PK_Orders PRIMARY KEY (order_id),
	CONSTRAINT FK_Orders_Customers FOREIGN KEY (customer_id,name) REFERENCES Customers(customer_id,name)
);
```

### DBeaver Version

Community edition: Version 24.0.1

### Operating System

Windows 10

### Database and driver

Data base: SQL Server
Driver	Microsoft JDBC Driver 9.2 for SQL Server [9.2.0.0]

**Comment by LonwoLonwo** [comment]
Hello @Sp0rtb1lly 

Thanks for the bug report!
