### ISSUE TITLE
Network unavailable 

### ISSUE THREAD

**Issue by Lakhan9033** [dbeaver/dbeaver#23369]
### Description

Hello Team,

I have DBeaver version 24.0.2 and I am trying to connect PostgreSQL and Oracle but as soon as I try to drag menu down it creates error for both of the bank. 

any solutions woud be highly appreciated.

Thanks in advance.

<img width="959" alt="2024-04-09 14_42_30-" src="https://github.com/dbeaver/dbeaver/assets/166515593/0a010492-9e4f-4ef9-9fe9-d01382dac7f2">

### DBeaver Version

DBeaver Community 24.0.2

### Operating System

Windows

**Comment by Yegrii** [comment]
After upgrading to version 24.0.2, I had a similar problem. When trying to connect to the Postgres database I was constantly getting the error "Internal error connecting to jdbc:postgresgl://localhost:5432/postgres Invalid thread access". I rolled back to version 24.0.0 and the error has gone.

**Comment by E1izabeth** [comment]
@Lakhan9033 please open Driver Settings and Download libraries, if they weren't downloaded
![image](https://github.com/dbeaver/dbeaver/assets/28875055/fcbc18dd-9903-4484-9b00-844570b26b77)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
