### ISSUE TITLE
DBeaver application error on 24.0.1 version

### ISSUE THREAD

**Issue by sarthaksh21** [dbeaver/dbeaver#23360]
same error in new DBeaver version 24.0.1
![image](https://github.com/dbeaver/dbeaver/assets/165733477/107a6bd8-5354-473b-9c40-aeacc89464d6)

![image](https://github.com/dbeaver/dbeaver/assets/165733477/fd43c582-42ac-4a66-9bfc-67becee56135)

_Originally posted by @sarthaksh21 in https://github.com/dbeaver/dbeaver/issues/18530#issuecomment-2030887178_

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide log files.

**Comment by sarthaksh21** [comment]
Hi @E1izabeth, yes, issue still persist.

**Comment by E1izabeth** [comment]
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)
