### ISSUE TITLE
Support for Turso (libsql remote db)

### ISSUE THREAD

**Issue by RScrusoe** [dbeaver/dbeaver#23361]
**Is your feature request related to a problem? Please describe.**
I want to connect to my turso DB which is a libsql db hosted on cloud. To connect to Turso db, it requires db url and auth token. Currently this is not supported. Would really appreciate this feature.

**Describe the solution you'd like**
To enter turso db url and auth token and to be able to connect to the turso db.

**Describe alternatives you've considered**
Recently TablePlus added support for this, but as I have been using Dbeaver since long time, would like to use this tool with turso db as well.

**Comment by arhayka** [comment]
Thank you for the idea!

**Comment by GustavoOS** [comment]
@arhayka are there enough votes for now?

**Comment by hood** [comment]
Any news on this? This would be a killer addition, as libsql (and Turso in particular) has been gaining A LOT of traction lately.

**Comment by serge-rider** [comment]
There is no Java driver for libSQL yet.
We will investigate possibility to develop a custom one.

For the reference: https://github.com/libsql/libsql-client-java/issues/4

**Comment by serge-rider** [comment]
We are going to include LibSQL driver in 24.2.5.

**Comment by serge-rider** [comment]
JDBC driver: https://github.com/dbeaver/dbeaver-jdbc-libsql
It is included in DBeaver build.
It will be published on Maven Central later this week.

**Comment by braaar** [comment]
Would it be possible to make some documentation for how to use this driver? I can't seem to get this to work with Turso's URL + auth token.

What goes where? I've tried some variations without success.

![Screenshot 2024-12-02 at 13 48 56](https://github.com/user-attachments/assets/c1cfc530-c292-4015-b7fe-98ac4860b4b6)

**Comment by serge-rider** [comment]
You can enter server URL (https://...) in server field.
Token in user password field.

We are going to make specific connection page for LibSQL later.

**Comment by dorlanpabon** [comment]
Efectivamente, para la conexión en dbeaver, se debe usar https://xxxxxxxxxx.xxxxxxxxxx.turso.io

**Comment by emvouvakis** [comment]
The existing views in turso db are not shown in dbeaver. Is there any solution for this?
