### ISSUE TITLE
Unable to fully view DDL information delimiters and other information of external tables in DBeaver

### ISSUE THREAD

**Issue by 406636258** [dbeaver/dbeaver#23367]
### Description

When I want to view the addresses and separators of external table references through DBeaver (24.0.0.202403031740), I cannot see that information and can only see information similar to the following:
`
CREATE TABLE ext.trace_lys20231017 (
	queryserialno varchar(40) NULL
);
`
But I can see the following information from the DBeaver(22.0.4) on other people's computers:
`
CREATE EXTERNAL TABLE iap.ext.trace_lys20231017 (
	queryserialno varchar
)
LOCATION (
	'GPFDIST://[***:8082/trace_lys20231017.csv](http://***:8082/trace_lys20231017.csv)'
) ON ALL
FORMAT 'CSV' ( delimiter '' null '' escape '^' quote '' header )
ENCODING 'UTF8';
`

### DBeaver Version

24.0.0.202403031740

### Operating System

window11

### Database and driver

PostgreSQL 9.4.26 (Greenplum Database 6.25.1 build commit:337d85331f0330dea32d229f450da438d5e948f6) on x86_64-unknown-linux-gnu

**Comment by LonwoLonwo** [comment]
Hello @406636258 

Could you please provide related screenshots?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
