### ISSUE TITLE
Syntax highlighting stops working after functions contains multiple argument

### ISSUE THREAD

**Issue by shenzj1994** [dbeaver/dbeaver#23377]
### Description

![image](https://github.com/dbeaver/dbeaver/assets/12000606/688601aa-1272-4c15-8e8c-990accd665de)

As you can see here, everything after `RIGHT` function failed to highlight properly.

But if I change to a different function like `TRIM`, then everything works fine:
![image](https://github.com/dbeaver/dbeaver/assets/12000606/b7670618-6031-4081-8eaa-bdf6bf094265)

What makes things more weird is, if I remove the second argument of RIGHT, then the highlight works fine although the syntax is wrong:
![image](https://github.com/dbeaver/dbeaver/assets/12000606/bf881aee-ba68-4522-b86d-8460a1cb054a)

### DBeaver Version

Community Version 24.0.1.202403241413

### Operating System

Windows 10

### Database and driver

PostgreSQL 9.4.26
PostgreSQL 9.4.26 (Greenplum Database 6.22.2)

### Steps to reproduce

In the join statement, use some functions like CAST(), RIGHT() or LEFT() with 2 or more arguments.

**Comment by E1izabeth** [comment]
Thank you for bug report.
