### ISSUE TITLE
I want import data directly from Blob storage using import data feature in debeaver

### ISSUE THREAD

**Issue by jgrover21** [dbeaver/dbeaver#23393]
### Description

I can easily import .csv file from my local folder to create a new table in dbeaver.  But I do not see option to do so with Blob storage.  How can I do that?

### DBeaver Version

Community versio

### Operating System

Windows 

### Database and driver

Postgresql 14.0

**Comment by ShadelessFox** [comment]
Hello @jgrover21,

Can you please elaborate on your use case? Where do you want to import your blob into?

If you want to import a blob into a column, you can use the highlighted button in the value panel on the right:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/f072e773-d4de-4c5c-b7e3-ea0728b7f132)

If you want to create a new table from a blob, it needs to be in a format supported by DBeaver. What format is your blob?

**Comment by jgrover21** [comment]
Hi,
In Dbeaver, import data feature can be used to import files from local folder.  I can move data from one database to another but how can I do from blob to database.

**Comment by ShadelessFox** [comment]
What do you mean by "blob"? It's an acronym for Binary Large OBject. It might represent anything: pictures, videos, models, etc.

Please clarify what format you are using.

**Comment by jgrover21** [comment]
I mean blob storage container.

Respectfully,

Jyoti Grover

**Comment by ShadelessFox** [comment]
Can you please provide a link to the documentation covering the format?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by dolphinotaku** [comment]
I tried to upload a almost 80KB zip file into blob field, but I got this error on Save

Error synchronizing data with database

Reason:
SQL Error [22001]: The value of a host variable in the EXECUTE or OPEN statement is out of range for its corresponding use.. SQLCODE=-302, SQLSTATE=22001, DRIVER=4.33.31

seems the file is too larger?

**Comment by E1izabeth** [comment]
@dolphinotaku please create a new issue and provide log files there. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.
