### ISSUE TITLE
is there any way you can enhance your ER diagram feature to show full map of all table joined to create a new table or view?

### ISSUE THREAD

**Issue by jgrover21** [dbeaver/dbeaver#23392]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ShadelessFox** [comment]
Hello again @jgrover21,

I don't quite understand what you mean.

Perhaps you're looking for the edit mode? https://github.com/dbeaver/dbeaver/wiki/Edit-mode

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
