### ISSUE TITLE
Support REAL_VECTOR type in HANA plugin

### ISSUE THREAD

**Issue by stefanuhrig** [dbeaver/dbeaver#23390]
The new vector data type `REAL_VECTOR` was introduced with HANA Cloud Database QRC 1/2024. Details about the new type are available at the [SAP HANA Database Vector Engine Guide](https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-vector-engine-guide/sap-hana-cloud-sap-hana-database-vector-engine-guide).

HANA's JDBC driver natively supports that type starting with version `2.21.5`.

A new value handler should be introduced so that vectors are displayed like arrays. Furthermore, the column type modifiers should be adapted to display vector dimension constraints.

**Comment by stefanuhrig** [comment]
I'd like to implement the support of the new type myself.

**Comment by LonwoLonwo** [comment]
Hello @stefanuhrig 

Thanks for the idea and for your contribution.

**Comment by mahanteshimath** [comment]
Is this not present in on premise  Hana?

**Comment by stefanuhrig** [comment]
@mahanteshimath 
No, the Vector Engine is a HANA Cloud only feature. There are currently no plans to also add it to on-premise HANA.
