### ISSUE TITLE
Finicky hover recognition on close button

### ISSUE THREAD

**Issue by kwilson62** [dbeaver/dbeaver#23417]
### Description

![IMG_3988](https://github.com/dbeaver/dbeaver/assets/67450655/ff9b7117-4012-4d34-bafb-c177401a3691)
![IMG_3989](https://github.com/dbeaver/dbeaver/assets/67450655/02ec10de-ace9-47d8-9637-fab92465b790)

Slightly annoying issue. The close button is finicky about whether or not is actually being hovered over, causing an issue when trying to close the window it will sometimes click-through and close any other full screen window behind DBeaver.
This results in unintentionally closing the wrong window.

### DBeaver Version

Community Edition 24.0.2.202404071654

### Operating System

Windows 11 Pro 10.0.22631

### Steps to reproduce

1. Move mouse over the close window button

**Comment by Destrolaric** [comment]
@kwilson62 Hi, unfortunately, this is the issue with Windows. I am not sure anything can be done to solve it from DBeaver side.
