### ISSUE TITLE
SQL generation and Export as SQL use wrong notation for hstore type (PostgreSQL). 

### ISSUE THREAD

**Issue by foal** [dbeaver/dbeaver#2342]
While I Use SQL generation or Export and the table or result set contains hstore type the dbvear generate the following code `{key1=value 1, key2=value 2}`. The right code have to look like `"key1"=>"value 1", "key2"="value 2"`.

![image](https://user-images.githubusercontent.com/458209/31603169-9edd84d6-b25f-11e7-8ada-38c147a28fa1.png)

**Comment by uslss** [comment]
Already fixed.
Ticket closed.
