### ISSUE TITLE
Execution of 2-select commands fails. (MySQL)

### ISSUE THREAD

**Issue by KevinKrueger** [dbeaver/dbeaver#23424]
I come from the MSSQL Studio from microsoft and still have a mysql database. 
I wanted to execute:
```sql
select * from tableA;
select * from tableB;
```
and I assumed that the 2 tables would be displayed one below the other.
Since I am used to this in MSSQL Studio, and it doesn't work in dbeaver, I was extremely annoyed.

<img width="456" alt="image" src="https://github.com/dbeaver/dbeaver/assets/25382167/5b943e81-d7f6-48b2-9355-93d6bebb1d65">

**Comment by ShadelessFox** [comment]
Hello @KevinKrueger,

Have you tried executing these queries as a script using **Alt+X**?

**Comment by KevinKrueger** [comment]
Hey @ShadelessFox,
this works but if I want to look at 2 data sets from different tables (practice from software development) then these are displayed in different tabs but not one below the other in one and the same section. This makes viewing, comparing/troubleshooting in the database model very tedious

**Comment by ShadelessFox** [comment]
You can enable vertical tab layout by clicking on the highlighted button on the toolbar on the left:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/7941a0e1-ea6c-40ce-8c57-5c2ca8f60f92)

If it doesn't show up for you, you might need to turn it on in the preferences:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/7f5f7b9b-6932-44c2-a24f-956d9aa49faa)

**Comment by KevinKrueger** [comment]
Oh, thank you @ShadelessFox :)

This is what I looking for XD

**Comment by ShadelessFox** [comment]
Glad I was able to help. I assume the ticket can be closed now.
