### ISSUE TITLE
sha256 hash files are missing in releases

### ISSUE THREAD

**Issue by Zutatensuppe** [dbeaver/dbeaver#23422]
**Is your feature request related to a problem? Please describe.**
Previously, the hash files for a certain version of dbeaver were available.
For example, for the download of 24.0.2, the url was 
https://download.dbeaver.com/community/24.0.2/dbeaver-ce-24.0.2-win32.win32.x86_64.zip
and the according hash file was found at
https://download.dbeaver.com/community/24.0.2/checksum/dbeaver-ce-24.0.2-win32.win32.x86_64.zip.sha256
(or similar)

**Describe the solution you'd like**
It seems that the downloads are not hosted by dbeaver directly anymore, but rather are hosted by github through the releases. There are no hash files here. It would be nice to have the hash files available somewhere for automatic installers like `scoop`.

**Additional context**
I tried to just update the urls for dbeaver in the scoop installer extras bucket (https://github.com/ScoopInstaller/Extras/pull/13115), but as the sha256 checksum files are not found, the tests fail.

**Comment by flambchap** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
Fixed.
It was a side effect of distributions layout redesign.

**Comment by serge-rider** [comment]
Note: correct URLs for checksums are on dbeaver.io. 
List is at https://dbeaver.io/files/24.0.2/checksum/
https://dbeaver.io/files/24.0.2/checksum/dbeaver-ce-24.0.2-macos-aarch64.dmg.md5
...

Please do not use final links. They may change at any moment.
