### ISSUE TITLE
DBeaver simple SELECT takes 90s vs 200ms in CLI : DBeaver fetches all possible values

### ISSUE THREAD

**Issue by mbrouillet** [dbeaver/dbeaver#23436]
### Description

`select * from members where email like "%ar%uillet.or%";`

- DBeaver : ---> 96 670 ms (note that  `LIMIT 0, 200` is added by DBeaver)
- CLI : ---> 196ms

A `show full process list` on the server caught this: `SELECT DISTINCT email FROM m***r.members ORDER BY 1`

Why does **DBeaver attempts to get all possible values** instead of letting the database use its indexes and optimizations ?
(There is an index on `email`).

### DBeaver Version

24.0.2.202404071654 of April 8th 2024

### Operating System

Ubuntu 22.04.3 LTS

### Database and driver

Database: 11.3.2-MariaDB
Driver: org.mariadb.jdbc:mariadb-java-client:3.3.2:RELEASE [3.3.2]

### Steps to reproduce

I can't provide the database, but run
`select * from members where email like "%ar%uillet.or%";`
in both DBeaver and mysql linux CLI ; compare timings.

### Additional context

Production database with 400 000 distinct entries in that table.
Slow DSL connection. I suppose most of the delay is network transfer of this phantom  `SELECT DISTINCT email FROM m***r.members ORDER BY 1`  to DBeaver.

**Comment by E1izabeth** [comment]
Do you have this setting turned ON?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/bc28bd14-aeb3-4dad-a0de-2ef7c12b0c51)

**Comment by mbrouillet** [comment]
It is indeed selected. I understand that adds the LIMIT 0,200 and this is good. Thank you.

I don't see how  this would explain the SELECT DISTINCT that is inducing the lag, though.

**Comment by serge-rider** [comment]
DBeaver execute SELECT DISTINCT whenever you want to see possible values for a column. E.g. when you press CTRL+Space `email like `

**Comment by serge-rider** [comment]
You can disable this behavior by turning off option "Show values" in completion settings:
![image](https://github.com/dbeaver/dbeaver/assets/6398845/abf66028-23cb-4481-9647-58dc2921e523)

**Comment by mbrouillet** [comment]
Interesting @serge-rider , thank you. I don't think I did try to get auto-completion ; I believe I typed the request and entered Ctrl-Enter to run it, but I'll see if it is linked to this.

**Comment by E1izabeth** [comment]
Does our suggestion help?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
