### ISSUE TITLE
On geometry rows selection - map is not displayed on spatial tab. just blank screen

### ISSUE THREAD

**Issue by ondrej-ivanko** [dbeaver/dbeaver#23434]
### Description

Hi,

since last update of DBeaver Free (24.0.2), the map component stopped working my Fedora 39 after I select one or more valid geometries from the rows in `Data` tab in `Grid` view and than click on `Spatial` tab. All I get is blank screen.

I added logs and one things stands out. The app fails to find `xdg-mime` bin, which is weird, because it's installed and working. Proof is included in attachments.
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/14991652/dbeaver-debug.log)
[oji_dbeaver_failing_spatial_map_view.log](https://github.com/dbeaver/dbeaver/files/14991656/oji_dbeaver_failing_spatial_map_view.log)
![Screenshot from 2024-04-16 09-32-20](https://github.com/dbeaver/dbeaver/assets/44980578/1fcabac7-02ba-4626-969e-dd1993e29525)
![Screenshot from 2024-04-16 09-48-25](https://github.com/dbeaver/dbeaver/assets/44980578/a5d39146-5ca9-4ca1-afcd-2bea835d51ac)

### DBeaver Version

24.0.2.202404071654

### Operating System

Fedora 39

### Database and driver

PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

jdbc:postgresql driver - PostgreSQL v2.5.0 and PostgreSQL v42.7.2. I can see both drivers, but no sure which one is used. I added screenshot to attachements.
![Screenshot from 2024-04-16 10-00-27](https://github.com/dbeaver/dbeaver/assets/44980578/a13f1714-5a92-4afc-ad90-9a97b0c96f85)

### Steps to reproduce

- Start DBeaver
- open a table in Postgresql/Postgis database
- click Data tab
- click Grid tab
- click on geometries in geometry column
- click on `Spatial` tab

### Additional context

I'm using private VPN to connect to DB, but had no issue using it. Others have no issue with it either. Colleagues are using different OSes (Win 11/10, Debian, Ubuntu) and have no issue with map either.

**Comment by Destrolaric** [comment]
@ondrej-ivanko Hi, it looks like your system is lacking required linux binary to interact with DBeaver. 
`java.io.IOException: Cannot run program "xdg-mime": error=2, No such file or directory`
By the looks of it, the xdg-utils should help
https://src.fedoraproject.org/rpms/xdg-utils

**Comment by ondrej-ivanko** [comment]
Hi @Destrolaric , that's the first thing I was checking.

![Screenshot from 2024-05-30 17-35-46](https://github.com/dbeaver/dbeaver/assets/44980578/9331444a-3485-4f8e-83be-e1e89897cf2b)

As you can see, it's present. Half of other things would fail it I would be missing it. Maybe DBeaver is looking for it in a strange path, I dunno.

**Comment by ondrej-ivanko** [comment]
DBeaver was installed via flatpak. Flatpak is installing it's own depedencies.

**Comment by ondrej-ivanko** [comment]
Hi, upon checking the functionality the issue seems to be resolved possibly by latest updates of DBeaver/Flatpak/System library updates. I'm closing it.
