### ISSUE TITLE
Unable to edit Remote and Local host fields from SSH tab UI when editing connections in Port Forwarding section

### ISSUE THREAD

**Issue by mfoleyshift** [dbeaver/dbeaver#23442]
### Description

Steps to Reproduce
1. Open DBeaver
2. Right click on previously existing connection profile
3. Select "Edit Connection"
4. Navigate to SSH tab
5. Expand Advanced Settings
6. Locate Remote and Local Host field in Port Forwarding section

Expected Result:  User should be able to click into Remote and Local host fields to make edits in the Port forwarding section
Actual Result:  Only the Remote and Local Host field labels are present.  There is no field rendered in the UI.
![image](https://github.com/dbeaver/dbeaver/assets/95516309/0f327998-b1dd-4914-a7e9-7b28bea7970a)

### DBeaver Version

Version 24.0.2.202404071654

### Operating System

Windows 11

### Database and driver

PostgreSQL JDBC Driver

**Comment by ShadelessFox** [comment]
Hello @mfoleyshift,

This is a layout issue. Please try resizing the window.

**Comment by E1izabeth** [comment]
I reproduced the issue. Resize helps 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/dd8bac7b-24be-4b38-89a9-c6ff27aee1d8)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/558658e8-dc77-40eb-8eb8-bf1ff315822d)
