### ISSUE TITLE
Setting permissions in Mariadb with "grant options" doesn't work.

### ISSUE THREAD

**Issue by buhlerax** [dbeaver/dbeaver#23443]
### Description

See screenshots in ticket #326891 in enterprise support.
Dbeaver generates the syntax with grant grant. It should be Grant all.

### DBeaver Version

Dbevar enterprise Version 24.0.0.202403110838

### Operating System

Windows 11

### Database and driver

Database version: 10.11.7-MariaDB-1:10.11.7+maria~deb12 on Debian 12 server

### Steps to reproduce

Try giving general permission or in a database with grant options

**Comment by LonwoLonwo** [comment]
Hello @buhlerax 

Thanks for the bug report.
A ticket was created on the internal board, and this case will be solved there.
