### ISSUE TITLE
Package 'org.jkiss.dbeaver.ui.swt' does not exist in this plug-in

### ISSUE THREAD

**Issue by chelproc** [dbeaver/dbeaver#23479]
### Description

Hello DBeaver Team,

I frequently use DBeaver in my work and appreciate its utility and your efforts.
I encountered an issue following the Eclipse setup instructions on [your documentation page](https://dbeaver.com/docs/dbeaver/Develop-in-Eclipse/).

Could you advise on a fix or update the documentation if needed?

### DBeaver Version

Commit hash: 7bf16e7e033cfe8da077ce38dbdccfde279f99e3

### Operating System

Ubuntu 22.04

### Steps to reproduce

Here you can see how to reproduce this issue starting from a clean installation of Ubuntu 22.04.
https://e.pcloud.link/publink/show?code=XZqu7MZIDwHHFhSORh22QiJGmfrd7nhLTlk

### Additional context

Eclipse Error Log
https://e.pcloud.link/publink/show?code=XZhf7MZM0wetG7Rq7u075WRsPEBkV0JeiTX

**Comment by Destrolaric** [comment]
Hi, could you look if you have file in home  `/home/user/eclipse-workspace/.metadata/.plugins/org.eclipse.m2e.core/lifecycle-mapping-metadata.xml`

**Comment by chelproc** [comment]
Hi @Destrolaric,

I tried the method you suggested, but the XML content was the same as what's listed in Step 9 on https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse/.

Is there anything else I should try?

![Screenshot 2024-04-28 101550](https://github.com/dbeaver/dbeaver/assets/45363260/5cb2086c-7c41-412f-9894-0d09a5a40881)

**Comment by Waldenth** [comment]
same problem
![image](https://github.com/dbeaver/dbeaver/assets/51648137/c187fd97-8912-4863-8d9a-dc31e696d48b)

**Comment by Destrolaric** [comment]
@chelproc I am Not sure, but DBeaver can't see the file. Are you sure that DBeaver has access to it?

**Comment by Waldenth** [comment]
> ### Description
> Hello DBeaver Team,
> 
> I frequently use DBeaver in my work and appreciate its utility and your efforts. I encountered an issue following the Eclipse setup instructions on [your documentation page](https://dbeaver.com/docs/dbeaver/Develop-in-Eclipse/).
> 
> Could you advise on a fix or update the documentation if needed?
> 
> ### DBeaver Version
> Commit hash: [7bf16e7](https://github.com/dbeaver/dbeaver/commit/7bf16e7e033cfe8da077ce38dbdccfde279f99e3)
> 
> ### Operating System
> Ubuntu 22.04
> 
> ### Database and driver
> _No response_
> 
> ### Steps to reproduce
> Here you can see how to reproduce this issue starting from a clean installation of Ubuntu 22.04. https://e.pcloud.link/publink/show?code=XZqu7MZIDwHHFhSORh22QiJGmfrd7nhLTlk
> 
> ### Additional context
> Eclipse Error Log https://e.pcloud.link/publink/show?code=XZhf7MZM0wetG7Rq7u075WRsPEBkV0JeiTX

Hey, have you used a wrong version of Eclipse, dbeaver needs eclipse rcp
![image](https://github.com/dbeaver/dbeaver/assets/51648137/17e2e06b-7acf-4222-88f5-0796b786792b)

**Comment by chelproc** [comment]
Hi, @Destrolaric @Waldenth 

I recently updated the dbeaver/dbeaver repo to the latest commit (66babe562e40e8a6b021ac777dec2a811b397478). I saw the error changed, but I was able to solve all of them. So I suppose I can close this issue now.

Here's are how I solved the errors:

<p><img width="1240" alt="image" src="https://github.com/dbeaver/dbeaver/assets/45363260/d28d52e1-6d8e-4755-8c4a-cc4658ff3ab2"></p>

### `plugins/org.jkiss.dbeaver.ext.altibase/src/org/jkiss/dbeaver/ext/altibase/model/AltibaseSQLDialect.java`

String#formatted is introduced since Java 15, but `dbeaver.ext.altibase.model` is built for Java SE 11.

```diff
@@ -431,7 +431,7 @@ public class AltibaseSQLDialect extends JDBCSQLDialect
 
     @Override
     public String getClobComparingPart(@NotNull String columnName) {
-        return "DBMS_LOB.COMPARE(%s,?) = 0".formatted(columnName);
+        return String.format("DBMS_LOB.COMPARE(%s,?) = 0", columnName);
     }
     
     @Override
```

### `plugins/org.jkiss.dbeaver.ui.editors.sql.ai/META-INF/MANIFEST.MF`

`org.jkiss.dbeaver.ui.editors.sql.ai.model` is moved to `org.jkiss.dbeaver.ui.editors.sql.ai` by #29998

```diff
@@ -9,7 +9,6 @@ Import-Package: org.jkiss.dbeaver.model.ai,
 Export-Package: org.jkiss.dbeaver.ui.editors.sql.ai,
  org.jkiss.dbeaver.ui.editors.sql.ai.controls,
  org.jkiss.dbeaver.ui.editors.sql.ai.format,
- org.jkiss.dbeaver.ui.editors.sql.ai.model,
  org.jkiss.dbeaver.ui.editors.sql.ai.openai,
  org.jkiss.dbeaver.ui.editors.sql.ai.popup,
  org.jkiss.dbeaver.ui.editors.sql.ai.preferences
```
