### ISSUE TITLE
[Hive] Driver downloads fail

### ISSUE THREAD

**Issue by DuncanBeard** [dbeaver/dbeaver#2349]
When I try to connect to an Apache Hive database DBeaver asks to download drivers, but then fails with this error:

![screen shot 2017-10-16 at 2 17 13 pm](https://user-images.githubusercontent.com/5641626/31627947-0d44e4b0-b27d-11e7-8968-a5be2cc8c7b1.png)

Is there a workaround or fix?

**Comment by serge-rider** [comment]
1. You could try another Hive driver version (2.1.0 download is ok).
2. You could download Hive driver manually (e.g. from here : https://github.com/timveil/hive-jdbc-uber-jar/releases) and then add it to the Hive driver library list (in driver edit dialog). Note: don't forget to remove maven repo reference first.

**Comment by DuncanBeard** [comment]
#2 worked!

**Comment by tati-kru** [comment]
Great! Thank you @DuncanBeard
