### ISSUE TITLE
Horizontal scrolling with shift

### ISSUE THREAD

**Issue by kerhong** [dbeaver/dbeaver#2352]
It is usually possible to scroll horizontally using scroll wheel while holding shift.

This functionality does not currently work in DBeaver.

**Comment by serge-rider** [comment]
This is not supported by Eclispe platform. But it is supported by some OSes. And with some additional extensions (which you can install in DBeaver as well as in Eclipse IDE).
https://stackoverflow.com/questions/2119184/horizontal-scrolling-with-the-scrollwheel-in-eclipse/21420631#21420631

**Comment by tati-kru** [comment]
It looks like this issue cannot be fix from the DBeaver side. There is a workaround. 
So this ticket will be closed. If you have any additional questions just let us know.

**Comment by dipnlik** [comment]
Just wanted to let you know that neither the workaround nor the additional info (in another answer in the same SO page) worked globally on DBeaver, at least on my machine.  They work for the Navigator sidebar but do not work for the SQL editor or the Results panel (in either ), which are arguably the most important parts of DBeaver's UI.

I found [a thread from 2014](https://dbeaver.jkiss.org/forum/viewtopic.php?p=3378) where Serge says the Results panel is a custom control, but not sure if this still applies.  Maybe some form of horizontal scrolling can be implemented on it somehow?

(If this is the wrong issue to follow/comment, please let me know, and sorry in advance.)

**Comment by serge-rider** [comment]
I agree.
After all I see how it can be done in our custom controls.
We'll add horizontal scrolling in results viewer in 5.0.6.

**Comment by serge-rider** [comment]
Not sure about SQL editor though.
