### ISSUE TITLE
Ubuntu PPA enhancement

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#2355]
Enhance existing PPA (see #1667):
- Support 32-bit version
- Perhaps move to `dbeaver` account
- Add copyright and other standard stuff
- Something else?

**Comment by benyanke** [comment]
Perhaps this is already on the roadmap, but perhaps EE support, along with a terminal way to activate a license? This would allow very easy scriptable installation and activation.

**Comment by benyanke** [comment]
Also seconding the slow download report mentioned [here](https://github.com/serge-rider/dbeaver/issues/1667#issuecomment-337044614). I seem to be pulling < 2 MBPS.

Would you like some additional help setting up a mirror or two? I'd be willing to provide a bit of free hosting on my multiple VPSes in Chicago and NYC if that would help, and is possible.

**Comment by robinfrick** [comment]
I would add to that list:

- add to https://dbeaver.jkiss.org/download/ as a download option :+1:

**Comment by stafio** [comment]
Shortly after you added zesty support, Artful Ardvark was released. Can you add that as well? There won't be any new releases for six months now, so there won't be any changes needed until then.

**Comment by serge-rider** [comment]
@robinfrick Yep. We'll have to make deb repository on jkiss.org first. Going to do this in 4.2.5 release.
@stafio will add Ardvark in 4.2.4.

**Comment by Wirone** [comment]
@serge-rider How often is PPA updated? I wanted to upgrade to 4.2.5 and it's still unavailable but DBeaver says there is update..

**Comment by serge-rider** [comment]
It'll be updated today, thanks for noticing.
It is still in beta and updated in manual mode.

**Comment by benyanke** [comment]
@serge-rider Still pulling at about 2 mbps. Would you be interested in some help with some hosting for the actual DEB files (as mentioned above). I'd love to donate some resources to help this project if it would be helpful...

**Comment by serge-rider** [comment]
@benyanke Thanks!
But I'm not sure yet what exactly do we need to fix this. Potentially we can host deb files right on Github.
We going to add custom deb repository on jkiss.org soon. Then automate PPA updates and improve download speed (I've heard this can be done even on standard launchbox).

I'll reply in this ticket once we'll be ready.

**Comment by benyanke** [comment]
ok, sounds good. It's not a huge deal, but long term, it's one more thing to sort out!

**Comment by Wirone** [comment]
@serge-rider can I kindly ask for updating PPA with 4.3.0? Thanks in advance :)

**Comment by serge-rider** [comment]
@Wirone done for 4.3.1

**Comment by benyanke** [comment]
Just following up on the speed issue - still seems to be an issue
![image](https://user-images.githubusercontent.com/4274911/40936422-e3f5c34c-6800-11e8-9c08-4b6bad37613d.png)

**Comment by serge-rider** [comment]
Did you try apt-fast? I'm not sure is this launchpad traffic limit or something else..

**Comment by nazrhyn** [comment]
I didn't, though I can try to set that up next week.

**Comment by DanielSiepmann** [comment]
You could mention that an PPA exists somehwere, e.g. in the readme or on the website.

I just searched and found the two issues and am really happy. Would loved to see this right on the download page.

**Comment by nazrhyn** [comment]
It actually is on the download page, but it's a bit down. That's why I said this in my comment:

>Apparently scrolling on the download page is hard for me :disappointed:.

![image](https://user-images.githubusercontent.com/1672405/45820658-48b93580-bcb5-11e8-8d08-bef97947307f.png)

**Comment by nazrhyn** [comment]
@serge-rider
> Did you try apt-fast? I'm not sure is this launchpad traffic limit or something else..

Well, either you fixed it, or `apt-fast` fixed it:

```
d7229f|OK  |   2.9MiB/s|/var/cache/apt/apt-fast/dbeaver-ce_5.2.1~ubuntu16.04_amd64.deb
```

:man_shrugging:
