### ISSUE TITLE
Change default IDENTITY to 1,1

### ISSUE THREAD

**Issue by simon-spier0** [dbeaver/dbeaver#23656]
Hello,

Currently, the default IDENTITY is **(0,1)**:
![image](https://github.com/dbeaver/dbeaver/assets/60992048/c931e362-c4c8-4068-a2ea-ef4059986c61)

However, could you please change it to **(1,1)** as it has [MS SQL Server Management Studio by default](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver16#arguments)?

> You must specify both the seed and increment or neither. If neither is specified, the default is (1,1).

Thanks.

**Comment by E1izabeth** [comment]
Thank you for request

**Comment by E1izabeth** [comment]
I'm unable to reproduce your issue. Could you clarify, how do you create the table to get this behavior?

**Comment by E1izabeth** [comment]
Also which DBeaver version do you use?

**Comment by Sgierek106** [comment]
I am not the original submitter of this issue, but I encountered this today in DBeaver Community Version 24.0.4.202405051837

In SQL Server, when you create a new identity column for a table and then click "Save", the resulting DDL defaults to an identity seed value of 0, which means the first record inserted into the table gets an id of 0.

@E1izabeth Would you be open to me submitting a PR to fix this?

**Comment by E1izabeth** [comment]
@Sgierek106 we're open for contributions, sure. Here is some useful information on this matter https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code
