### ISSUE TITLE
Data transfer profiles

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#2372]
We need to support profiles for data transfer wizard.

Profile must contain all data transfer configurations (source/target containers, options, etc).
It also must have id, name and description. Some minimalistic profiles management UI should be also provided.

Potentially it should be possible to run data transfer just by specifying its ID.

**Comment by uslss** [comment]
#6865 bug created

**Comment by serge-rider** [comment]
DT profiles were implemented as tasks.
