### ISSUE TITLE
[Postgres] No column comments in DDL

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#2379]
DDL script of a table doesn't contain table and columns comments

**Comment by lemon-juice** [comment]
This also applies to DDL scripts of views, procedures and other objects. They should contain code like this:

`COMMENT ON TABLE mytable IS 'some comment';`

and `COMMENT ON VIEW...`, `COMMENT ON FUNCTION...`, etc.

**Comment by serge-rider** [comment]
Fixed a time ago in other PostgreSQL DDL-related bugs.

**Comment by mirandadam** [comment]
Hi, @serge-rider! Please explain how to display that information in DBeaver. I found this bug report by @offstate exactly because my DDL is not displaying the comments. I am running DBeaver 4.2.4 against PostgreSQL 9.6.3, please let me know if you need any more info.

Thanks!

**Comment by serge-rider** [comment]
@mirandadam 
1. Upgrade to the most recent version
1. Use PostgreSQL driver (not PostgreSQL Generic)

Column comments are after table create statement.
