### ISSUE TITLE
Open pre-configured connection from command-line parameter

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2389]
DBeaver - **Version 4.2.3 CE**
DBeaver JDBC driver: **jTDS or Microsoft**
Operating System: **Windows 7 / Windows 8.1**

Would be benificial if an already defined connection could be opened from command-line parameter. 

I know that I can create a completely new connection from _DBeaver_ command-line parameter **-con "name=XXX|driver=XXX|..."** (see ISSUE #2341). But if I have already a configurered connection that I want to use and only set [User name], [Password] and [Database/Schema], I can not find a way to do this.

PS. I tried to create a command-line connection using the **-con** parameter with the same name as a predefiened connection. But that only resulted in two connections with the same name in the _DBeaver_ **Database Navigator** tree.

**Comment by pdanie** [comment]
DBeaver - **Version 4.3.2 CE EA**
DBeaver JDBC driver: **Microsoft Driver 2**
Operating System: **Windows 7** / **Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

It would be super great if this feature could be incorportated in _DBeaver_ in the near future. Its a feature that would same our company much time and simplify the login/connection to the database.

**o** If the **Connection Name** is **not** already defined in _DBeaver_, create the new Connection (no change from current functionality).
**o** If the **Connection Name** is already defined in _DBeaver_, the command line **Connection Parameters** should override the predefined values in the existing connection.

Your thoughts on this ?

**Comment by hunsakerbn** [comment]
This functionality would be very useful to me.  I would also like the ability to specify an existing connection on the command line to connect to.

**Comment by dsu-inf** [comment]
Why is this issue closed? Is this feature already implemented or it was rejected?
This feature is valuable.

**Comment by p91paul** [comment]
@dsu-inf looks opened to me, not closed!

**Comment by dsu-inf** [comment]
@p91paul 
My fault. I saw "Close" label on an action but it was about #2314 :)
I see that this feature was added for 6.0.5 milestone. It's an excellent news.

**Comment by serge-rider** [comment]
New CLI connection parameter was added: "create=false"
https://github.com/dbeaver/dbeaver/wiki/Command-Line

**Comment by uslss** [comment]
verified
