### ISSUE TITLE
Linux - Dbeaver hangs on "too many" schema on DB Connection

### ISSUE THREAD

**Issue by Nope7** [dbeaver/dbeaver#2391]
I installed DBeaver on Linux Ubuntu 16.04 LTS. I configured 2 DB types:
- SQL Server --> Works
- DB2 i Series (AS400) --> When I expand the schema list using the Database Navigator frame, the application first starts to select all the schema on the DB connection but finally the application hangs and the only thing that I can do is to kill the process. 

My PC has 16 GB of RAM and a i7 CPU, so I don't think it could be a matter of system req.

Thanks in advance

**Comment by serge-rider** [comment]
Most likely this is similar to #2152
On some Linuxes (seems to be related to window manager) UI hangs if there are thousands of elements in navigator tree. You could try one of workarounds in #2125 ..

**Comment by serge-rider** [comment]
Also as a workaround you can use filters (on connection properties page or in navigator tree). Thus you can see only schemas you actually need.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. Perhaps, it was solved. This ticked will be closed. However, if you think that it is actual just let us know.
