### ISSUE TITLE
Feature Request: Allow to Save Script of Export Query Data

### ISSUE THREAD

**Issue by isapir** [dbeaver/dbeaver#2392]
One of my favorite features in DBeaver is the ability to export query data to a different database.

I can not find, however, a way to save the script to file so that it can be executed at a later time.  

That would be a great addition since many users need to migrate large databases from one DBMS to another, so it will allow to prepare all of the scripts beforehand, and then execute them when it's time to make the final switch of the migration.

Thank you for your consideration.

**Comment by isapir** [comment]
@serge-rider Can you estimate the difficulty in implementing this enhancement/feature?  Thanks.

**Comment by lsascha** [comment]
just got DBeaver Enterprise and imediately had the same usecase where i would have liked to export the result of a rather complex query to a query that includes the result as INSERTS. Would have liked it. But maybe i can for the time being use a different format.

**Comment by guitman444** [comment]
Yes, would also love this feature to save the under-the-hood scripts used by the export module. 

An example of my environment:

I have 3 separate database servers connected, 1 SQL and 2 Oracle. Right now I use Access to link tables from all three, and then I write various queries to select from one and insert into another all in one step. Would be nice to do this without Access. So, an example would be:

insert into [SQLServer.table] values (value1, value2)
values [OracleServer.table/query] (value1, value2)

**Comment by uslss** [comment]
Export to SQL is already available
![image](https://user-images.githubusercontent.com/31996417/171186954-bc2a2d1f-ad98-4ccf-b291-6b3575407525.png)
