### ISSUE TITLE
Excel Export: Warn if Column with Length > 32767 is exported

### ISSUE THREAD

**Issue by Sargul** [dbeaver/dbeaver#2397]
When a table with a column char length >32767  is exported there should be a warning that this exceeds the capabilities of the Excel 2007 format.

**Comment by serge-rider** [comment]
Good point

**Comment by serge-rider** [comment]
Currently export will fail if cell value will exceed 32767. 
We can cut it to 32767 bytes and show warnings. Or just keep failing.
Warning about potential value length exceeding doesn't look good. Because any text/CLOB column will produce such warnings and users will just ignore it.

**Comment by igortank** [comment]
You can make a setting to choose whether to trim to 32767 characters or not.
