### ISSUE TITLE
i can't read my view

### ISSUE THREAD

**Issue by Mateozmaldonado17** [dbeaver/dbeaver#2402]
i love dbeaver !!! 

![screenshot_1](https://user-images.githubusercontent.com/5784157/31895276-62526384-b7d6-11e7-913e-00a11ea8a52b.jpg)

**Comment by serge-rider** [comment]
Please post error stacktrace (main menu Window->Show View->Error Log)

**Comment by uslss** [comment]
Issue cannot be reproduced.
There isn't any activity about this ticket for a very long time. It will be closed. However, if you think that it is actual just let us know.
