### ISSUE TITLE
Fetching cursor

### ISSUE THREAD

**Issue by cpjeanpaul** [dbeaver/dbeaver#2403]
Cant fetch cursor rows from postgres
`SELECT schema.sp('o', '0', 'x', 'x'); FETCH ALL IN o;`

**Comment by serge-rider** [comment]
Please post sample DDL for stored procedure.

**Comment by tati-kru** [comment]
Hi @cpjeanpaul 
Do you have any updates about this issue?

**Comment by serge-rider** [comment]
Closing as non-reproducible.
