### ISSUE TITLE
I can't change "target type" when I transfer data from csv source table

### ISSUE THREAD

**Issue by lucsm** [dbeaver/dbeaver#2411]
I need to transfer data from a table to another one. CSV file has all collumns type like string and I need to change to integer. When I mapping collumns and I press "ok" the system says: 

"Syntax error: Encountered " <NAME> "CREATE "" at line 1, column 1.
Was expecting:
    "SELECT" ... ".
Am I doing something wrong?  

Thanks.
(sorry for my english).

**Comment by serge-rider** [comment]
If you map csv table to some `new` target table then DBeaver will need to create this new table. Some columns can't be translated automatically - that's why new table creation was failed.

Open columns mapping dialog and check how source columns are mapped to target columns.
