### ISSUE TITLE
Allow Selection of Display Timezone

### ISSUE THREAD

**Issue by jw-maynard** [dbeaver/dbeaver#2414]
Right now DBeaver seems to convert TIMESTAMPTZ columns to the local timezone of the machine on which it is being run and there is not option to override this timezone in the client itself. I've seen this stackoverflow: 
https://stackoverflow.com/questions/45323552/how-to-change-dbeaver-timezone-how-to-stop-dbeaver-from-converting-date-and-ti
But adding command line options is not a very user friendly way to adjust this. In addition, without running it from the command line I'm unsure how you would set this in MacOS.

Can we get an option added to preferences that allows you to set an offset that TIMESTAMPTZ columns are converted to please?

**Comment by serge-rider** [comment]
Agreed. Also check #238

**Comment by alex88** [comment]
Is this a "UI setting" for not having to add `-Duser.timezone=UTC` to the ini file after each upgrade?

**Comment by uslss** [comment]
Already implemented.
Timezone can be set in Preferences
![image](https://user-images.githubusercontent.com/31996417/127872104-a73bc87b-79d9-4062-9fc0-b4d86e7a7feb.png)

**Comment by alex88** [comment]
@uslss how do I add that? 21.1.3

![image](https://user-images.githubusercontent.com/436888/128042855-49e8b2f5-342f-4a0e-9fda-5eb7336ea72a.png)
