### ISSUE TITLE
Export to csv

### ISSUE THREAD

**Issue by tpgol** [dbeaver/dbeaver#2417]
When I export the results with fields 'integer', the value is truncated

**Comment by isapir** [comment]
Can you give an example of a line with such an integer field and the value that you see in the database afterwards?

**Comment by tpgol** [comment]
Original
FIELD_1            FIELD_2
58878941	NNN
75926864	NNN
80146310	NNN

Export to CSV

"FIELD_1";"FIELD_2"
1;NNN
4;NNN
0;NNN
I changed the name of the field for privacy
Thanks

**Comment by tpgol** [comment]
Sorry I got a wrong key

**Comment by isapir** [comment]
I see a different issue with it.  Consider the following query (PostgreSQL):

```
SELECT 	*
FROM 	(VALUES(58878941::int, 'AAA'), (75926864, 'BBB'),(80146310, 'CCC')) consts(col1, col2)
```

I right-click the result set and choose `Export Resultset` from the context menu.  Instead of showing `col1` as integers and quoting `col2`, I see quotes on the integers (because of the commas) and no quotes on `col2` unless there is a comma in the value.  In this case:

```
"col1","col2"
"58,878,941",AAA
"75,926,864",BBB
"80,146,310",CCC
```

**Comment by serge-rider** [comment]
@tpgol Check Numbers formatting (preferences->Database->Result Sets->Data Formats). By default numeric format print only 10 fraction digits.

@isapir For me this works as expected. In CSV format value must be quoted if it contains any delimiter.

**Comment by isapir** [comment]
@serge-rider That makes sense, but is there a way to prevent the thousand-separator (commas) from showing in the integer fields?

**Comment by serge-rider** [comment]
@isapir Sure, you can use numbers format configuration (see above)

**Comment by tati-kru** [comment]
It looks like this issue was solved. It will be closed. If you think that it is actual just let us know.
