### ISSUE TITLE
Query execution confirmation not shown when running a highlighted part of a query

### ISSUE THREAD

**Issue by genericjon** [dbeaver/dbeaver#2421]
For production connections (or another connection type that has the "Confirm SQL execution" option enabled), I am not prompted to confirm execution when running a highlighted part of a larger query.
For example, running the following query will prompt for confirmation:

    INSERT INTO foo.some_table
    SELECT * FROM bar.some_table WHERE uniqid = 123;

But by selecting only the second line with the caret (`SELECT * FROM bar.some_table WHERE uniqid = 123;`) and executing, that part will be executed immediately without prompting.

The same is true for other queries, e.g.:

    SELECT * FROM foo.some_table WHERE uniqid = 123
    UNION ALL
    SELECT * FROM bar.some_table WHERE uniqid = 123;

Executing the whole text will prompt for confirmation, but highlighting and executing either of the select statements on their own will not.

In both of these examples, the prompt does appear if you highlight the whole text, so it doesn't seem as simple as the confirmation behaviour always being skipped when executing a highlighted statement.

**Comment by serge-rider** [comment]
DBeaver shows query confirmation for any non-SELECT query.
All DML, DDL or complex  queries (e.g. with unions) are executed without confirmation. Does this bring any problems?
