### ISSUE TITLE
Execution plan analyzer

### ISSUE THREAD

**Issue by tati-kru** [dbeaver/dbeaver#2428]
Execution plan analyzer

**Comment by serge-rider** [comment]
This is about plan visualization (because we already have very simple tree-like visualization).

And we'll start from PostgreSQL.

**Comment by edgarsti** [comment]
There is online tool I usually use to analyze complicated plans.
http://tatiyants.com/pev/#/plans/new
This might be good example how explain plans should be visualized.

**Comment by PHCCorso** [comment]
Personally, I prefer [explain.despez](https://explain.depesz.com/) over Tatiyant's plan analyzer. It might be used as an example as well. And it seems to fit best on DBeaver, since it's just plain simple table visualization.

**Comment by tati-kru** [comment]
This feature was added to DBeaver EE 6.0.
