### ISSUE TITLE
Stored procedure DDL with drop option

### ISSUE THREAD

**Issue by PatriciaGomesB** [dbeaver/dbeaver#2437]
I want to know if is any option to force Drop stored procedure in Generate SQL -> DLL with mysql database?

I used Heidisql before with this feacture, It's important to me have the drop option because I have to export a lot of stored procedure between server.

I try to configure that but I can't find any place to do it.

**Comment by LonwoLonwo** [comment]
@PatriciaGomesB hello. if this FR is still actual for you, can you clarify?
![2020-11-02 13_51_17-DBeaver Enterprise 7 3 0 - IX_Address_PostalCode](https://user-images.githubusercontent.com/45152336/97860177-bb10f680-1d12-11eb-87ba-a3445bd00164.png)
 You can drop procedure with "Delete" button. 

Or you want DDL comment like for tables?
![2020-11-02 13_55_51-Stored procedure DDL with drop option · Issue #2437 · dbeaver_dbeaver](https://user-images.githubusercontent.com/45152336/97860548-5d30de80-1d13-11eb-94c2-708e2a7b6625.png)

**Comment by uslss** [comment]
there are no updates on the issue for a long time.
If it is still actual for you - feel free to reopen the ticket with an additional info
