### ISSUE TITLE
DBMS_JOBS in Oracle

### ISSUE THREAD

**Issue by danieleangellotti** [dbeaver/dbeaver#2438]
Hi Serge,
maybe I'm asking for a feature request: in Scheduler section I can see just "DBMS_SCHEDULER jobs" and programs, but not "DBMS_JOB jobs".

Thanks.

**Comment by danieleangellotti** [comment]
Just a note: "Jobs" folder shows what is retrieved with `SELECT * FROM USER_SCHEDULER_JOBS` query and "Programs" does the same with `SELECT * FROM USER_SCHEDULER_PROGRAMS` query. The enhancement should be listing jobs retrieved with `SELECT * FROM USER_JOBS` query.

**Comment by jonwarren** [comment]
This may or may not be related (thinking it could be a deeper driver issue or a limitation on what 3rd party tools can access about jobs).
`SELECT * FROM USER_SCHEDULER_JOB_RUN_DETAILS;` shows `LOG_DATE` as null, but checking in Oracle's SQL Developer shows dates in that column for the same entries.
