### ISSUE TITLE
How to share ED Diagrams with team

### ISSUE THREAD

**Issue by NicoBotha** [dbeaver/dbeaver#2440]
Left bottom window, Project General, there is ED Diagrams function. On right click you see Team/Share Project option. Mine is grayed out after my first attempt at it.

How can we share these custom ER Diagrams with other users (on the same database).

For info: Postgres DB on network, DBeaver 4.2.4

Thank you

**Comment by serge-rider** [comment]
Currently there is no direct integration with VCS in DBeaver CE.

But you can checkout some Git/SVN repository into some folder and then link this folder to DBeaver project. Then you can set any project folder as ER diagrams default location.

**Comment by tati-kru** [comment]
This question was answered. So the ticket will be closed. 
If you think that we need this feature in DBeaver, please create a separate feature request with more detailed description.

**Comment by jeisoncp** [comment]
I tried to working with GIT to share the .erd files, but the XML have a data source instruction that is different for each one. So, my partners only can see a blank screen.

![Captura de tela de 2019-04-24 11-43-50](https://user-images.githubusercontent.com/7952798/56668661-4a513e80-6686-11e9-866a-6888b24edb50.png)

![Captura de tela de 2019-04-24 11-45-56](https://user-images.githubusercontent.com/7952798/56668828-97351500-6686-11e9-91d0-07f5e7cf3b2f.png)

**Comment by mahendra-korat** [comment]
We are also facing the same issue. Any update on this?

**Comment by NicoBotha** [comment]
I gave on that route and start using SchemaSpy that links to the PostgresSQL database. It generates a very nice set of Webpages. 
But still only single user maintain.

**Comment by JorgeValverde18** [comment]
I tried changin de **data-source id** sharing my ed with my partners and editing the xml file replacing it with the **data-source id** that they have on their ed diagrams for the same db and its working, they can see the ed diagram not the blank screen
