### ISSUE TITLE
[Feature request] Search for content inside objects

### ISSUE THREAD

**Issue by PedroSolintel** [dbeaver/dbeaver#2443]
In pgAdmin's search function (Ctrl + G) I'm able to search also by definitions and comments. This is specially useful to me when I want to search for the content inside stored procedures and tables. This is a feature that I frequently use in pgAdmin and I would very much appreciate if I were able to do this in DBeaver too.

![image](https://user-images.githubusercontent.com/28440086/32182805-bace08ee-bd7e-11e7-9e74-5e17ee5ff8ff.png)

**Comment by serge-rider** [comment]
This would be a good feature. 
I think we can extend existing "Search metadata" functionality.

**Comment by PedroSolintel** [comment]
Do you still plan on developing this functionality? Just yesterday I needed to change a function that was largely used within other functions in my database. Had to install pgAdmin to search and correct the input parameters of that specific function everywhere. Also, today I had to check which would be the effects of changing an specific column data-type on the entire database. Again, had to use pgAdmin's search function to check every procedure that was using that column on a `SELECT` statement.

I can't wait to finally get rid of pgAdmin and start using DBeaver only.

**Comment by BorjaMinguela** [comment]
This is a very interesting feature. In the meantime, i'm using this query to search for text inside functions:
`select proname, prosrc from pg_proc where prosrc ilike '%TEXT%';`
I don't know if it can be used to search for comments to, but maybe can help for this.

**Comment by flambchap** [comment]
Search in comments was implemented in the scope of https://github.com/dbeaver/dbeaver/issues/10370, now I'm going to implement search in definitions.

**Comment by flambchap** [comment]
Implemented for the databases listed above.

**Comment by Matvey16** [comment]
Error when searching in Oracle

![2021-06-30_11h30_19](https://user-images.githubusercontent.com/82543000/123930429-694f6780-d998-11eb-949e-66d1a6221478.png)

![2021-06-30_11h28_09](https://user-images.githubusercontent.com/82543000/123930497-7d936480-d998-11eb-8ccc-ca338e5ffd3b.png)

**Comment by flambchap** [comment]
Fixed the error above.

**Comment by Matvey16** [comment]
Now search in Oracle doesn't find some of the data from definitions and sometimes messes up with upper and lower case.
![2021-07-01_10h42_51](https://user-images.githubusercontent.com/82543000/124090912-f9a3b000-da5d-11eb-871a-f02bde480efc.gif)

https://user-images.githubusercontent.com/82543000/124091031-150ebb00-da5e-11eb-85d7-6b10fa5fa3c7.mp4

**Comment by Matvey16** [comment]
Verified
