### ISSUE TITLE
Keep plugins when update

### ISSUE THREAD

**Issue by wviana** [dbeaver/dbeaver#2444]
Hello,

I use DBeaver with Vrapper plugin.

Evertime I do update Dbeaver I have to install Vrapper again.
Would be nice to keep my plugins in .dbeaver folder.

**Comment by serge-rider** [comment]
Correlates with #1590.
Although I'm not sure that we'll use fully functional version update in near time. Eclipse P2 update is too fragile :(

**Comment by stophe72** [comment]
Hello,

I tried to install vrapper plugin, from the "Install software" menu and the url http://vrapper.sourceforge.net/update-site/stable (and unstable), without success.
I have also try using vrapper-0.72.zip archive : failed too
How did you install vrapper plugin ?

Thanks for your response :)

**Comment by wviana** [comment]
- I've open Help > Install New Software
- add the link: http://vrapper.sourceforge.net/update-site/stable
- Enter
- Select the modules that you want to install
- Done

**Comment by stophe72** [comment]
Thank's
This is the way I tried. But just before end, I've got the following error message (using ArchLinux) :

An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.ibm.icu.base,56.1.0.v201601250100
No repository found containing: osgi.bundle,org.eclipse.compare,3.7.1.v20170103-1805
No repository found containing: osgi.bundle,org.eclipse.compare.core,3.6.0.v20160418-1534
No repository found containing: osgi.bundle,org.eclipse.core.commands,3.8.1.v20161221-1651
No repository found containing: osgi.bundle,org.eclipse.core.contenttype,3.5.100.v20160418-1621
No repository found containing: osgi.bundle,org.eclipse.core.databinding,1.6.0.v20160412-0910
No repository found containing: osgi.bundle,org.eclipse.core.databinding.observable,1.6.0.v20160511-1747
No repository found containing: osgi.bundle,org.eclipse.core.databinding.property,1.6.0.v20160427-0852
No repository found containing: osgi.bundle,org.eclipse.core.expressions,3.5.100.v20160418-1621
No repository found containing: osgi.bundle,org.eclipse.core.filebuffers,3.6.0.v20160503-1849
No repository found containing: osgi.bundle,org.eclipse.core.filesystem,1.6.1.v20161113-2349
No repository found containing: osgi.bundle,org.eclipse.core.jobs,3.8.0.v20160509-0411
No repository found containing: osgi.bundle,org.eclipse.core.net,1.3.0.v20160418-1534
No repository found containing: osgi.bundle,org.eclipse.core.resources,3.11.1.v20161107-2032
No repository found containing: osgi.bundle,org.eclipse.core.runtime,3.12.0.v20160606-1342
No repository found containing: osgi.bundle,org.eclipse.e4.core.commands,0.11.100.v20160506-0804
No repository found containing: osgi.bundle,org.eclipse.e4.core.contexts,1.5.1.v20170203-1100
No repository found containing: osgi.bundle,org.eclipse.e4.core.di,1.6.1.v20160712-0927
No repository found containing: osgi.bundle,org.eclipse.e4.core.di.annotations,1.5.0.v20151127-1241
No repository found containing: osgi.bundle,org.eclipse.e4.core.di.extensions,0.14.0.v20160211-1614
No repository found containing: osgi.bundle,org.eclipse.e4.core.services,2.0.100.v20160509-1032
No repository found containing: osgi.bundle,org.eclipse.e4.emf.xpath,0.1.200.v20160506-0804
No repository found containing: osgi.bundle,org.eclipse.e4.ui.bindings,0.11.100.v20160509-1025
No repository found containing: osgi.bundle,org.eclipse.e4.ui.css.core,0.12.1.v20161114-0210
No repository found containing: osgi.bundle,org.eclipse.e4.ui.css.swt,0.12.100.v20160517-1505
No repository found containing: osgi.bundle,org.eclipse.e4.ui.css.swt.theme,0.10.100.v20160523-0836
No repository found containing: osgi.bundle,org.eclipse.e4.ui.di,1.1.100.v20160506-0759
No repository found containing: osgi.bundle,org.eclipse.e4.ui.model.workbench,1.2.0.v20160229-1459
No repository found containing: osgi.bundle,org.eclipse.e4.ui.services,1.2.100.v20160506-0759
No repository found containing: osgi.bundle,org.eclipse.e4.ui.widgets,1.1.100.v20160506-0759
No repository found containing: osgi.bundle,org.eclipse.e4.ui.workbench,1.4.0.v20160517-1624
No repository found containing: osgi.bundle,org.eclipse.e4.ui.workbench.addons.swt,1.2.101.v20170206-1129
No repository found containing: osgi.bundle,org.eclipse.e4.ui.workbench.renderers.swt,0.14.1.v20170117-1415
No repository found containing: osgi.bundle,org.eclipse.e4.ui.workbench.swt,0.14.1.v20160829-0832
No repository found containing: osgi.bundle,org.eclipse.e4.ui.workbench3,0.13.100.v20160506-0759
No repository found containing: osgi.bundle,org.eclipse.ecf,3.8.0.v20160823-2221
No repository found containing: org.eclipse.update.feature,org.eclipse.ecf.core.feature,1.3.0.v20160823-2221
No repository found containing: org.eclipse.update.feature,org.eclipse.ecf.core.ssl.feature,1.1.0.v20160823-2221
No repository found containing: osgi.bundle,org.eclipse.ecf.filetransfer,5.0.0.v20160823-2221
No repository found containing: org.eclipse.update.feature,org.eclipse.ecf.filetransfer.feature,3.13.2.v20160823-2221
No repository found containing: org.eclipse.update.feature,org.eclipse.ecf.filetransfer.httpclient4.feature,3.13.2.v20160823-2221
No repository found containing: org.eclipse.update.feature,org.eclipse.ecf.filetransfer.httpclient4.ssl.feature,1.1.0.v20160823-2221
No repository found containing: org.eclipse.update.feature,org.eclipse.ecf.filetransfer.ssl.feature,1.1.0.v20160823-2221
No repository found containing: osgi.bundle,org.eclipse.ecf.identity,3.7.0.v20160823-2221
No repository found containing: osgi.bundle,org.eclipse.ecf.provider.filetransfer,3.2.200.v20160823-2221
No repository found containing: osgi.bundle,org.eclipse.ecf.provider.filetransfer.httpclient4,1.1.100.v20160823-2221
No repository found containing: osgi.bundle,org.eclipse.ecf.provider.filetransfer.httpclient4.ssl,1.1.0.v20160823-2221
No repository found containing: osgi.bundle,org.eclipse.ecf.provider.filetransfer.ssl,1.0.0.v20160823-2221
No repository found containing: osgi.bundle,org.eclipse.ecf.ssl,1.2.0.v20160823-2221
No repository found containing: osgi.bundle,org.eclipse.emf.common,2.12.0.v20160420-0247
No repository found containing: osgi.bundle,org.eclipse.emf.ecore,2.12.0.v20160420-0247
No repository found containing: osgi.bundle,org.eclipse.emf.ecore.change,2.11.0.v20160420-0247
No repository found containing: osgi.bundle,org.eclipse.emf.ecore.xmi,2.12.0.v20160420-0247
No repository found containing: osgi.bundle,org.eclipse.equinox.bidi,1.0.0.v20160307-1318
No repository found containing: osgi.bundle,org.eclipse.equinox.common,3.8.0.v20160509-1230
No repository found containing: osgi.bundle,org.eclipse.equinox.ds,1.4.400.v20160226-2036
No repository found containing: osgi.bundle,org.eclipse.equinox.event,1.3.200.v20160324-1850
No repository found containing: osgi.bundle,org.eclipse.equinox.frameworkadmin.equinox,1.0.700.v20160102-2223
No repository found containing: osgi.bundle,org.eclipse.equinox.launcher,1.3.201.v20161025-1711
No repository found containing: osgi.bundle,org.eclipse.equinox.launcher.gtk.linux.x86_64,1.1.401.v20161122-1740
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.artifact.repository,1.1.500.v20160419-0834
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.console,1.0.500.v20160504-1450
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.core,2.4.100.v20160419-0834
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.core.feature,1.3.203.v20170131-1444
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.engine,2.4.100.v20160419-0834
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.metadata,2.3.100.v20160427-2220
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.metadata.repository,1.2.300.v20160419-0834
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.operations,2.4.200.v20160504-1450
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.rcp.feature,1.2.203.v20170131-1444
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.repository,2.3.200.v20160421-0324
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.touchpoint.eclipse,2.1.400.v20160419-0834
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.touchpoint.natives,1.2.100.v20160419-0834
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.transport.ecf,1.1.201.v20161115-1927
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ui,2.4.100.v20160419-0834
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ui.sdk,1.0.400.v20150423-1455
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ui.sdk.scheduler,1.3.0.v20161124-1529
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.updatechecker,1.1.300.v20161124-1529
No repository found containing: osgi.bundle,org.eclipse.equinox.preferences,3.6.1.v20160815-1406
No repository found containing: osgi.bundle,org.eclipse.equinox.registry,3.6.100.v20160223-2218
No repository found containing: osgi.bundle,org.eclipse.equinox.security,1.2.200.v20150715-1528
No repository found containing: osgi.bundle,org.eclipse.equinox.security.ui,1.1.300.v20150803-1225
No repository found containing: osgi.bundle,org.eclipse.equinox.simpleconfigurator,1.1.200.v20160504-1450
No repository found containing: osgi.bundle,org.eclipse.equinox.simpleconfigurator.manipulator,2.0.200.v20160504-1450
No repository found containing: osgi.bundle,org.eclipse.help,3.7.0.v20160602-1307
No repository found containing: osgi.bundle,org.eclipse.jface,3.12.2.v20170113-2113
No repository found containing: osgi.bundle,org.eclipse.jface.databinding,1.8.1.v20161026-1531
No repository found containing: osgi.bundle,org.eclipse.jface.text,3.11.2.v20170220-1911
No repository found containing: osgi.bundle,org.eclipse.ltk.core.refactoring,3.7.0.v20160419-0705
No repository found containing: osgi.bundle,org.eclipse.ltk.ui.refactoring,3.8.0.v20160518-1817
No repository found containing: osgi.bundle,org.eclipse.osgi,3.11.3.v20170209-1843
No repository found containing: osgi.bundle,org.eclipse.osgi.compatibility.state,1.0.200.v20160504-1419
No repository found containing: osgi.bundle,org.eclipse.osgi.services,3.5.100.v20160504-1419
No repository found containing: osgi.bundle,org.eclipse.platform,4.6.3.v20170301-0400
No repository found containing: osgi.bundle,org.eclipse.search,3.11.1.v20161113-1700
No repository found containing: osgi.bundle,org.eclipse.swt,3.105.3.v20170228-0512
No repository found containing: osgi.bundle,org.eclipse.swt.gtk.linux.x86_64,3.105.3.v20170228-0512
No repository found containing: osgi.bundle,org.eclipse.team.core,3.8.0.v20160418-1534
No repository found containing: osgi.bundle,org.eclipse.team.ui,3.8.0.v20160518-1906
No repository found containing: osgi.bundle,org.eclipse.text,3.6.0.v20160503-1849
No repository found containing: osgi.bundle,org.eclipse.ui,3.108.1.v20160929-1045
No repository found containing: osgi.bundle,org.eclipse.ui.editors,3.10.1.v20161106-1856
No repository found containing: osgi.bundle,org.eclipse.ui.forms,3.7.1.v20161220-1635
No repository found containing: osgi.bundle,org.eclipse.ui.ide,3.12.3.v20170119-0935
No repository found containing: osgi.bundle,org.eclipse.ui.ide.application,1.1.101.v20160829-0827
No repository found containing: osgi.bundle,org.eclipse.ui.intro,3.5.2.v20161116-1147
No repository found containing: osgi.bundle,org.eclipse.ui.navigator,3.6.101.v20161006-1120
No repository found containing: osgi.bundle,org.eclipse.ui.navigator.resources,3.5.101.v20161006-0640
No repository found containing: osgi.bundle,org.eclipse.ui.themes,1.1.300.v20161107-1827
No repository found containing: osgi.bundle,org.eclipse.ui.views,3.8.102.v20170111-0801
No repository found containing: osgi.bundle,org.eclipse.ui.views.log,1.2.1.v20160829-0826
No repository found containing: osgi.bundle,org.eclipse.ui.views.properties.tabbed,3.7.0.v20160310-0903
No repository found containing: osgi.bundle,org.eclipse.ui.workbench,3.108.3.v20170216-1539
No repository found containing: osgi.bundle,org.eclipse.ui.workbench.texteditor,3.10.1.v20160818-1626
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ce.feature,4.1.2
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core,4.1.2
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core.application,4.1.2
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.core.feature,4.1.2
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.db2,2.1.47
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.db2.feature,2.1.47
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.derby,1.1.47
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.erd,2.0.64
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.exasol,1.0.20
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.exasol.feature,1.0.20
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.firebird,1.0.63
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.generic,2.3.48
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.generic.feature,2.1.48
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.h2,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.hsqldb,1.0.9
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.import_config,2.1.25
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.informix,1.0.53
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.mssql,1.0.56
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.mysql,2.1.47
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.mysql.feature,2.1.47
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.netezza,1.0.27
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.oracle,2.1.47
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.oracle.feature,2.1.47
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.phoenix,1.0.31
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.postgresql,2.1.35
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.sqlite,1.0.11
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.teradata,1.0.30
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.ui.locks,1.0.7
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.vertica,1.0.55
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.wmi.feature,2.0.64
No repository found containing: osgi.bundle,org.jkiss.dbeaver.model,1.0.51
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.rcp.feature,2.1.36
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.standalone.feature,4.1.2
No repository found containing: osgi.bundle,org.jkiss.utils,2.1.45
No repository found containing: osgi.bundle,org.objectweb.asm,5.1.0.v20160914-0701
No repository found containing: osgi.bundle,org.tukaani.xz,1.3.0.

**Comment by wviana** [comment]
You would probably get more help in [DBeaver repository](https://github.com/dbeaver/dbeaver) or [website](http://dbeaver.jkiss.org)

**Comment by serge-rider** [comment]
This issue (or both issues) should be resolved after recent P2 plugins update. 
Please reopen if it is still a problem.

**Comment by programus** [comment]
It has been 2 years after this is closed, but I am still install vrapper every time I got dbeaver updated. 
I think I may miss something, how can I keep the plugins across updates? 
@wviana  Is your problem solved and how if so?

**Comment by wviana** [comment]
No it isn't. I do have to install every time I update.
