### ISSUE TITLE
Extra Connection Settings Strange Behavior

### ISSUE THREAD

**Issue by montehansen** [dbeaver/dbeaver#2452]
There are 2 sections that "appear" to be the same thing. Specifically:

1. The 'Connection XYZ configuration' dialog (Tree on the left), and;

2. The "Edit Driver XYZ" > "Connection Properties" | "User Properties" dialog.

As an aside, you might consider settling on a consistent label for the items, even though they may/may not have different scope. Connection Settings/Driver Properties and Connection properties/User Properties appear to have the same use.

The issue: 

1. I was unable to make these properties stick. For instance, I am using the HSQLDB Embedded crypt_key related settings. I attempted to set these values and the crypt_key stickyness was flaky.

2. The settings appear to (effectively) have global scope. So I am not able to specify different options for different connections. Therefore, I am unable to open more than one connection at a time because each database has a different encryption key.

Thanks!

Monte

**Comment by serge-rider** [comment]
Sorry, missed that.
Well, properties in driver settings are global (for all connections based on this driver).
Properties specified in connection itself (page driver properties) are connection-specific. And different for different connections.

**Comment by tati-kru** [comment]
It looks like this questions was answered. So this issue will be closed. If you have any additional questions just let us know.
