### ISSUE TITLE
[DB2 LUW plugin]: Generate SQL not working when select from alias

### ISSUE THREAD

**Issue by Sargul** [dbeaver/dbeaver#2453]
This is related to #2149.

Auto complete for alias works now but generate SQL does not

![grafik](https://user-images.githubusercontent.com/5595511/32211568-6428bcd8-be13-11e7-8681-cf71a5c09198.png)

Also edit of results is disabled

Edit: Version 4.2.4

**Comment by INGCRENGIFO** [comment]
Hi, it works for me with Db2

![image](https://user-images.githubusercontent.com/12200313/32333021-ddb34940-bfb4-11e7-99c4-707dd2eac75f.png)

you just have to activate this option

![image](https://user-images.githubusercontent.com/12200313/32333089-0132bc84-bfb5-11e7-825c-3b84aea641a2.png)
in metadata.

**Comment by Sargul** [comment]
Nope

You did a SQL from an Alias? Because for tables and views everything works smooth.
´´´´sql
create table TEST.DUMMY (COL1 INTEGER NOT NULL, CONSTRAINT DUMMY_PK PRIMARY KEY(COL1));
CREATE ALIAS TEST.DUMMY_ALIAS FOR TEST.DUMMY;
INSERT INTO TEST.DUMMY VALUES (1);
-- -> refresh meta data on connection
select * from TEST.DUMMY_ALIAS;
´´´

When I now right click on the alias I and want to generate the sql for the row there is the original error message.

When I select the dummy table generation of SQL statements works for me aswell

**Comment by INGCRENGIFO** [comment]
It worked for me. Now that I re-run "dbeaver" it stopped working and I have not moved or updated anything. I do not know happened.

**Comment by cniweb** [comment]
The error still occurs in the Version 5.0.3 when called from a Select result.

**Comment by serge-rider** [comment]
Aliases support (for Oracle and DB2) will be added in the next version.
Thanks for reminding :)
