### ISSUE TITLE
Language selector in UI

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#2458]
We need to find some way to select language/locale from DBeaver UI. 
E.g. in preferences.

**Comment by liuyuanyuan** [comment]
Serge, how about to use [New Message Extension](http://blog.vogella.com/2013/05/22/eclipse-internationalization-part-24-new-message-extension-by-dirk-fauth-and-tom-schindl/) ? It makes Eclipse based application re-localized at runtime.

**Comment by serge-rider** [comment]
There is no good way to do this. New message extension is good but it will require to redo i18n model in DBeaver. Also it is not supported by most of Eclipse plugins.

So, eventually I've decided to make it by patching dbeaver.ini file (passing -nl parameter there).
This won't work if DBeaver is installed in some system-protected folder (e.g. "Program Files" on Windows or /usr/share on Linux). But will work ok in portable mode or if DBeaver was installed in user home folder.

**Comment by dibog** [comment]
Bump. 
That feature would be very nice. I'm on a German desktop but would prefer to see the English as display application language.

**Comment by serge-rider** [comment]
This feature is already there. You can change it in preferences or in dbeaver.ini file
