### ISSUE TITLE
References shown with too few tables and to many columns

### ISSUE THREAD

**Issue by artoli** [dbeaver/dbeaver#2461]
The References subtab on the Properties tab of a table does not correctly list all foreign keys referencing the table. 

In the screenshot the ER diagram correctly shows all foreign keys pointing to the table MEDDELANDE_MALLAR. The list of foreign keys in the References subtab is obviously not correct. There are too few tables listed and for one foreign key there are far too many columns listed.

Most likely DBeaver lists all foreign keys with the same name as one foreign key irrespective of in which table they exist..

And the meaning of "Owner" and "Referenced Table" seem to have been switched.

![bild](https://user-images.githubusercontent.com/33284166/32314898-38b073fa-bfaa-11e7-87d3-e74e1ee9095a.png)

**Comment by serge-rider** [comment]
Sorry missed that.

What is your database/driver?

**Comment by artoli** [comment]
Database: DB2
Driver: com.ibm.db2.jcc.DB2Driver found in db2jcc4.jar

**Comment by uslss** [comment]
hi @artoli is issue still actual for you?

**Comment by uslss** [comment]
cannot reproduce an issue. 
ticket closed.
if it is still actual for you - feel free to reopen the ticket
