### ISSUE TITLE
MS SQL - Foreign Key Columns

### ISSUE THREAD

**Issue by fairport** [dbeaver/dbeaver#2471]
I just started using this wonderful application today. Thanks for it !
I am using it with an Azure SQL database

I had created many, multiple column foreign key cascade delete constraints on tables before (in MS SQL Management Studio) .. but they are only showing me 1 column in DBBeaver. 
I thought maybe I'd stuffed up so I have been deleting them and adding them back in using SQL Scripts in DBeaver .. BUT .. those are only showing me 1 column also (instead of 2 or 3) when I Right click on a FK & Choose Edit Foreign Key

![image](https://user-images.githubusercontent.com/1224192/32364592-aa23a654-c0b0-11e7-8ef0-d5cacca14358.png)

![image](https://user-images.githubusercontent.com/1224192/32364631-e7ff53e2-c0b0-11e7-8ed3-854351e6390b.png)

Thanks

**Comment by uslss** [comment]
There is no update on the ticket more than a year.
If the issue is still reproducible for you - feel free to reopen the ticket and add some details or create the new one.
