### ISSUE TITLE
Feature Request: Password Protected or Alert on Project Open

### ISSUE THREAD

**Issue by benyanke** [dbeaver/dbeaver#2474]
Currently, I organize my production DBs in a different project than my dev/testing/local DBs. That way, I can more easily protect myself from accidental deletions and such.

What are your thoughts on setting a project to some sort of "restricted mode" which could alert on load, or even pw protect?

I'm thinking of a workflow like this:

1) Open project 'Dev'
2) Do normal work
3) Open project 'prod'
4) Receive a message saying something like 'Warning: You are opening production databases. Do you want to continue?'
5) The project only opens after accepting.

Additionally, there could be protections built in which auto-close the project on program close, etc, etc.

This could be implemented most generically as some sort of project open-confimation message.

**Comment by uslss** [comment]
already implemented
https://github.com/dbeaver/dbeaver/wiki/Project-security
