### ISSUE TITLE
No support for custom postgresql types?

### ISSUE THREAD

**Issue by scippie75** [dbeaver/dbeaver#2478]
Postgresql allows a user to create types like for example an ENUM: https://www.postgresql.org/docs/9.1/static/datatype-enum.html

When I create a table, I can't choose one of my custom types from the list, nor can I type it manually because DBeaver tells me it's not a valid type (while it is). If I manually create the table, it works of course. If I then look at the table in the properties tab in the user interface, it just shows varchar as type, but it really isn't. Also, there doesn't seem to be a way to create types with DBeaver (which must be a hard feature to program, I admit)

Is there something I need to do to make it work or is it just not yet implemented in DBeaver? If support is planned, I would already be very happy if the custom types are just recognized by DBeaver, even if there is no support to create or view them yet.

**Comment by serge-rider** [comment]
There is a bug with data type resolution in some PostgreSQL servers. I can't reproduce it in my test environment :( Please provide a bit more details about yours (PG server/driver versions, OS).
Also there should be some errors in error/debug logs (https://github.com/serge-rider/dbeaver/wiki/Log-files).

Workaround: try to use `PostgreSQL (Generic)` driver.

**Comment by scippie75** [comment]
Hi,

First of all, the generic driver indeed understands the types. I guess I will be using that one from now on. Can you please explain me why there are different drivers?

The postgres server specs: PostgreSQL 10.0 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
I connect through an SSH tunnel (set up by DBeaver).

So... this is very weird... I just restarted the old connection with the non-generic driver (my pc has been off in between, so new dbeaver session) and now the type IS recognized... (I still need to type it manually, it's not in the list). This is very strange.

I do remember creating the type with a self-typed SQL query, I don't see where I can create types using dbeaver. Maybe that was the problem?

I'm sorry that I can't give any better information.

**Comment by LukaszEnegive** [comment]
I'd also love to get the answer to those questions.

**Comment by serge-rider** [comment]
You need to refresh type list in database navigator after you create a type in SQL editor. Just click on schema and press F5.
