### ISSUE TITLE
Database object alias (model)

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#2481]
We need to support aliases in DBeaver model. Initially this is needed for DB2 (#2149, #2453) but it should be general feature.
When opening alias DBeaver should navigate to target object and open it.

```java
...
interface DBSAliasObject<TARGET extends DBSObject> {
  TARGET getTargetObject(DBRProgressMonitor monitor)
}
...
```

**Comment by serge-rider** [comment]
This also should support Oracle synonyms.

**Comment by zorrorefractive** [comment]
Additional the auto-completion should work with ALIAS. It should gather the columnlist from Sourcetable of the ALIAS

**Comment by uslss** [comment]
Already resolved

**Comment by LonwoLonwo** [comment]
![2021-11-03 11_30_48-DBeaver Ultimate 21 2 0 - DEPT](https://user-images.githubusercontent.com/45152336/140029530-c1025a5e-6555-4c7a-b6ab-7bf2ca76988e.png)
