### ISSUE TITLE
DB Full-Text

### ISSUE THREAD

**Issue by c3lumsy** [dbeaver/dbeaver#2482]
When you start the application for the first time, calling the "Search> DB Full-Text" function takes extremely long time. All DB connections of the last search are reopend.
Suggestion:
Save the last search and open the search function with default values or blank. Selection of the last search in a dropdown?

**Comment by serge-rider** [comment]
Agreed. Full-text search UI has to be improved.

**Comment by serge-rider** [comment]
In 4.2.5 I'll just disable tree state save (as it can be really huge).
Need to make some better solution in 4.2.6
