### ISSUE TITLE
Window error needs scroll viewer

### ISSUE THREAD

**Issue by danjaredg** [dbeaver/dbeaver#2483]
Hi,

First, dbeaver is a grate job, but some databases send a very long message error, and I believe that window error needs have a scroll viewer to show the long messages, I send you a screenshot from apache hive error.

![dbeaver-window-error](https://user-images.githubusercontent.com/2866615/32456318-ceadbba4-c2ea-11e7-8171-2c353a980d73.jpg)

**Comment by uslss** [comment]
already implemented
