### ISSUE TITLE
Executing the SQL prompts the error "SQL Error [911] [22019]: ORA-00911: Invalid Character".

### ISSUE THREAD

**Issue by hanfengluoyu** [dbeaver/dbeaver#24868]
### Description

Click "Execute SQL Script," and you will receive the prompt "SQL Error [911] [22019]: ORA-00911: Invalid Character". However, if you select a single statement and click "Execute SQL Statement" to run it, the execution will work fine. Previously, simply clicking "Execute SQL Script" was sufficient.

![微信截图_20240422162157](https://github.com/dbeaver/dbeaver/assets/19600862/beef94f0-11c0-4d28-90c4-90af31e965b1)
![微信截图_20240422162130](https://github.com/dbeaver/dbeaver/assets/19600862/be52d73b-f434-4440-9e42-550e646cc625)
![微信截图_20240422162100](https://github.com/dbeaver/dbeaver/assets/19600862/87a37d23-814d-4b5d-8cb5-81e5b02750a7)

### DBeaver Version

Community 24.0.3.202404211624

### Operating System

windows 11

### Database and driver

ORACLE

**Comment by hanfengluoyu** [comment]
CREATE TABLE T_PARK_REQUIREMENT_APPLICATION(
    ID VARCHAR2(32) DEFAULT  SYS_GUID() NOT NULL,
    COMPANY_NAME VARCHAR2(500),
    APPLICANT_NAME VARCHAR2(200),
    CONTACT_PHONE VARCHAR2(100),
    DATE_RAISED DATE,
    DEMAND_TYPE VARCHAR2(50),
    REPORT_TYPE VARCHAR2(50),
    REPORT_CONTENT VARCHAR2(4000),
    STATUS INT,
    CREATE_BY VARCHAR2(32),
    CREATE_TIME DATE,
    UPDATE_BY VARCHAR2(32),
    UPDATE_TIME DATE,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE T_PARK_REQUIREMENT_APPLICATION IS '园区需求申请';
COMMENT ON COLUMN T_PARK_REQUIREMENT_APPLICATION.ID IS '主键';
COMMENT ON COLUMN T_PARK_REQUIREMENT_APPLICATION.COMPANY_NAME IS '公司名称';
COMMENT ON COLUMN T_PARK_REQUIREMENT_APPLICATION.APPLICANT_NAME IS '申请人';
COMMENT ON COLUMN T_PARK_REQUIREMENT_APPLICATION.CONTACT_PHONE IS '联系电话';
COMMENT ON COLUMN T_PARK_REQUIREMENT_APPLICATION.DATE_RAISED IS '提出日期';
COMMENT ON COLUMN T_PARK_REQUIREMENT_APPLICATION.DEMAND_TYPE IS '需求类型';
COMMENT ON COLUMN T_PARK_REQUIREMENT_APPLICATION.REPORT_TYPE IS '报事类型';
COMMENT ON COLUMN T_PARK_REQUIREMENT_APPLICATION.REPORT_CONTENT IS '报事内容';
COMMENT ON COLUMN T_PARK_REQUIREMENT_APPLICATION.STATUS IS '状态';
COMMENT ON COLUMN T_PARK_REQUIREMENT_APPLICATION.CREATE_BY IS '创建人';
COMMENT ON COLUMN T_PARK_REQUIREMENT_APPLICATION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_PARK_REQUIREMENT_APPLICATION.UPDATE_BY IS '更新人';
COMMENT ON COLUMN T_PARK_REQUIREMENT_APPLICATION.UPDATE_TIME IS '更新时间';

**Comment by E1izabeth** [comment]
Thank you for report.
You could try switching `Blank line is statement delimiter` setting to `Always`
![image](https://github.com/dbeaver/dbeaver/assets/28875055/be8457a0-d62c-4acb-ac2f-67ce518cf3f5)

**Comment by giansystem** [comment]
@E1izabeth You saved my day thank you. I think maybe the 'always' option should be default.. :)

**Comment by E1izabeth** [comment]
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.
