### ISSUE TITLE
MongoDB SSL Support

### ISSUE THREAD

**Issue by sheyd** [dbeaver/dbeaver#2486]
I don't see a checkbox option for SSL connectivity to MongoDB instances in the `Create New Connection` window. Is it possible to this will be a future release, or does this functionality already exist, and I'm not seeing the option for it?

Amazing job with DBeaver! Our entire data team is in love with it. Thank you for providing such an amazing tool!

**Comment by serge-rider** [comment]
MongoDB SSL configuration (in UI) isn't yet supported.

**Comment by serge-rider** [comment]
Generally Mongo connector supports SSL:

![image](https://user-images.githubusercontent.com/6398845/36504993-47ecc0ba-1763-11e8-9bc2-517680d5327c.png)

However if you have to use specific CA/key then they should be configured using command line (http://mongodb.github.io/mongo-java-driver/3.4/driver-async/tutorials/ssl/#jvm-system-properties-for-tls-ssl) or in dbeaver.ini.
Potentially it is possible to add UI for CA configuration. But I'm not sure how many people are actually need this. 
We'll support this if more people will vote.

**Comment by huineng** [comment]
i would certainly support this , now i have to use tools like nosqlbooster or 3T to get me quickly to my collection. i got it working like above, but that's cumbersome . So yes if possible , ssl for mongo would be very useful on the ui

**Comment by serge-rider** [comment]
We need certificate configuration + jvm config in UI.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/53898071-7538f200-4048-11e9-984c-5a5dc256b6d4.png)
