### ISSUE TITLE
Alter mssql stored procedure.

### ISSUE THREAD

**Issue by MazrimT** [dbeaver/dbeaver#2488]
A big part of working in mssql server is altering/creating stored procedures.

Something like right-clicking a stored procedure and selecting "alter" that would bring the script up in a new tab with "alter procedure [name] begin" at the top and and " end" att the bottom would be a great feature.

**Comment by serge-rider** [comment]
Yes.
This feature already supported for MySQL, PostgreSQL, Oracle, etc.
Stored procedures edit will be added in #810

**Comment by serge-rider** [comment]
Stored procedures edit support will be added in 5.3.3

**Comment by MazrimT** [comment]
Not sure how this was implemented.. but I see now that you can open procedure properties, then do any edit in the "source" tab, then ctrl+s, this brings up a preview window where you can click on "Open Editor".

This is 3 steps more than expected.
Expected behaviour would be to be able to directly from navigator to the editor. 
This is something you do around 100 times a day as a mssql developer.. having those extra 3 steps is a bit of a pain.
