### ISSUE TITLE
Variables in SQL script

### ISSUE THREAD

**Issue by sae-gfc** [dbeaver/dbeaver#2490]
Hello 

On a DB2 database with DBeaver 4.2.4, db2jcc4.jar 4.22.29, i have to calculate bank charge like
```
SELECT AMOUNT * :value1 + :value2
WHERE CODE LIKE :value3
```

I understand that if I want to set default value for variables it is automatically remember for the next time in the bind parameters windows.
CODE is a VARCHAR(8) which always begins with 999 four other numbers and a control alphabetic character (ex: 9991234A).
So I wrote '999%' in the parameters window  and I have to complete with the four numbers I need before the % character.
Is there a way to let the quote and the % character in the SQL request ?
I tried `WHERE CODE LIKE '999:value3%'` but it doesnt work.

**Comment by serge-rider** [comment]
I can't figure out what is the actual problem.

What happens if you set parameter to `'999%'`?

**Comment by sae-gfc** [comment]
It's not a SQL problem but a syntax I used with another DB tools that I search to transpose in Dbeaver.
I was able to write in SQL `WHERE CODE like '${myvarCODE||999}$%' ` and in the parameter windows I have only to complete the default value 999 without the % at the end and without the quote, it's more efficient when you have to do that lot of times.
To search `like '99912%'` I just need to complete with 12.
![myvarcode](https://user-images.githubusercontent.com/33481143/32701519-f69565bc-c7f0-11e7-892c-634d035daa34.png)
I'm trying to do the same thing with Dbeaver but I dont find the right syntax also I dont know if it is possible.

**Comment by serge-rider** [comment]
I see.
Variables syntax `${varName}` really makes sense.

**Comment by sae-gfc** [comment]
Another example of use , so the name search run even if user (non technician) puts space or - in the name
`WHERE NAME LIKE 'TRANSLATE(${myvarNAME},'',' -''','')%'`

**Comment by sae-gfc** [comment]
Default value will interested me too for example ${myvarCODE||defaultvalue}.
I have hundred mysql servers and I use the same scripts for all, when I switch to another connexion the bind parameters windows keep the previous value.
Using a script default value which overwrite the previous value will be great.

**Comment by serge-rider** [comment]
First version of SQL variables support will be added in 4.3.3.
As it is experimental feature it is disabled by default.
Please check how it works. Default values are not yet supported.

![image](https://user-images.githubusercontent.com/6398845/35197780-edd7fef8-fef5-11e7-9f36-0cced86de1d0.png)

Further improvements and bug should be tracked in separate tickets.

**Comment by sae-gfc** [comment]
Hello,
Great, it work's well.
Thank's a lot.

**Comment by dvht** [comment]
This option confuses me.  I have an oracle background and :bind_vars here replace literals and make sure you always execute the same parsed & cached statement, regardless of your values.  Since oracle knows it is a bind variable, you don't have to use quotes for strings. But in DBeaver, I know, it works different, like a replacement variable &name. in sqlplus. Different, but OK.  And now we have another option to replace a replacement variable ?  Why would I need that ?  It doesn't add any functionality.

**Comment by slotbite** [comment]
Can not export from query this script :(
 
BEGIN 
	DECLARE @t INT ; 
	SET @t = 20190320;
	WITH ASDASD AS  ( 
		SELECT @t AS DATO
	)
	SELECT * FROM ASDASD
END

**Comment by ChetanSolur** [comment]
> First version of SQL variables support will be added in 4.3.3.
> As it is experimental feature it is disabled by default.
> Please check how it works. Default values are not yet supported.
> 
> ![image](https://user-images.githubusercontent.com/6398845/35197780-edd7fef8-fef5-11e7-9f36-0cced86de1d0.png)
> 
> Further improvements and bug should be tracked in separate tickets

A lot of people miss this fundamental check, thanks! This helped me
