### ISSUE TITLE
Clickhouse readonly user error

### ISSUE THREAD

**Issue by alivelimeli** [dbeaver/dbeaver#2499]
Hello,

When I'm trying to connect Clickhouse DB with a readonly user DBeaver gives error because of trying to set some settings which is not allowed for readonly user.

How can we solve it?

**Comment by serge-rider** [comment]
Do you mean user with some specific permissions or "Read-only connection" option in DBeaver?

Please post exact error message/stacktrace.

**Comment by serge-rider** [comment]
Yes, this totally makes sense. But DBeaver doesn't update/delete/create anything during connection.
Although it reads some database metadata and maybe one of such reads identified by Clickhouse as update query.
That's why I need exact error message and stacktrace (you can get it in Error Log view).

**Comment by alivelimeli** [comment]
The error message is:

`Unexcepted driver error occured while connecting to database
    ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 164, host: 127.0.0.1, port:8123; Code: 164, e.displayText() = DB::Exception: Cannot override setting (extremes) in readonly mode, e.what() = DB::Exception`

Maybe its related to driver. But from the error message, it looks like while DBeaver is trying to connect its trying to modify extreme setting (maybe with a default value).

**Comment by serge-rider** [comment]
Thanks. 
But please post error stacktrace (main menu Window->Show View->Error Log or from log file https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by alivelimeli** [comment]
I've checked log files (both .log and debug log), unfortunately there aren't logs after this connection error. There weren't any logs for the day of testing (I tested again and no logs created)

**Comment by serge-rider** [comment]
This issue is no longer reproducible with last versions of Clickhouse driver.

**Comment by optionals** [comment]
> This issue is no longer reproducible with last versions of Clickhouse driver.
DBeaver 5.2.3, Clickhouse  driver 0.1.42 

log in clickhouse-server.log
Trace> HTTPHandler: Request URI: /?compress=1&max_result_rows=200&password=password&user=user&extremes=0&database=default&result_overflow_mode=break

 {} <Error> HTTPHandler: Code: 164, e.displayText() = DB::Exception: Cannot override setting (max_result_rows) in readonly mode, e.what() = DB::Exception, Stack trace:


delete DBeaver.app & config folder, reinstall  did not work
