### ISSUE TITLE
hot keys

### ISSUE THREAD

**Issue by cathemlin** [dbeaver/dbeaver#2505]
I like DBeaver, and hope it will support the follow things.
hotkeys for:
1. cursor  jump to result viewer like alt+2, jump to sql editor alt+1;
2. emacs key conflict, Ctrl+N, Ctrl+P only work in one place( sql editor or result viewer), and ctrl+F, ctrl+b not work in result viewer to select columns;
3. in sql editor, emacs key: ctrl+space to text without high light blue backgroud;
4. quick switch schema or database using hotkeys;
another:
 auto reconnect to database and schema when re execute a sql command.  SQL CLI will auto connect and execute the sql;

**Comment by serge-rider** [comment]
1. This can be done with <kbd>alt+f6</kbd>)
2. Please clarify. I'm not very familiar with emacs shortcuts. What each shortcut should do?
3. <kbd>ctrl+space</kbd> triggers auto-completion. How is this related to background color? (which can be configured in preferences)
4. This will be added in 4.2.5 (<kbd>ctrl+9</kbd>, <kbd>ctrl+0</kbd>)

**Comment by cathemlin** [comment]
thanks for the replay
1.` alt+f6` changes the active panel but without setting the cursor to previous location in editor or  selecting result cell like click mouse. 
2. emacs, keybinding: command. `ctrl+n`:line Down in sql editor or next row in result set; `ctrl+p`:line up in sql editor or previous row in result set. the problem is `ctrl+n, ctrl+p` only works in one panel either in sql editor or in result viewer and they supposed to work in both two panels. plus: `ctrl+f` supposed to select next cell in result set and `ctrl+b` supposed to select previous cell in result set.
3. emacs keybindind,`ctrl+space`  triggers set-mark and works with moving cursor (like using `ctrl+f, ctrl+b` etc.) to select the text. And it works like dragging mouse to select text to copy with background color .So `set mark` command supposed to have that color.

**Comment by cathemlin** [comment]
thanks for the replay
1.alt+f6 changes the active panel but without setting the cursor to previous location in editor or selecting result cell like click mouse.
2. emacs, keybinding: command. ctrl+n:line Down in sql editor or next row in result set; ctrl+p:line up in sql editor or previous row in result set. the problem is ctrl+n, ctrl+p only works in one panel either in sql editor or in result viewer and they supposed to work in both two panels. plus: ctrl+f supposed to select next cell in result set and ctrl+b supposed to select previous cell in result set.
3. emacs keybindind,ctrl+space triggers set-mark and works with moving cursor (like using ctrl+f, ctrl+b etc.) to select the text. And it works like dragging mouse to select text to copy with background color .So set mark command supposed to have that color.
