### ISSUE TITLE
Entity editor - sash form size restore bug

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#2507]
Sash form size restore is buggy. It grabs a few extra pixels on every editor re-open.
Seems to be result of complicated sash resize procedure (outer sash form in ObjectPropertiesEditor - see update weights function + inner sashes of tabbed folders)

**Comment by LonwoLonwo** [comment]
Can not reproduce anymore in the latest DBeaver versions (23.2.4).
