### ISSUE TITLE
Column type field doesn't offer a value from the list 

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#2508]
In the table properties window when you begin to input a type value the drop down list doesn't appear and doesn't search the value you entered

**Comment by serge-rider** [comment]
This feature (type auto-complete) was disabled in 4.2.5 because of too many issues in different databases.
But you still can use drop-down control for fast type search.

**Comment by offstate** [comment]
Could you make that after I entered some part of a value and then open the drop-down list, the list select the first found item beginning with this part?

**Comment by serge-rider** [comment]
This is not so easy because of SWT nature (it has to work on different platforms with the same behavior and combobox is a tricky control).
But I'll try.
