### ISSUE TITLE
Getting 22021: invalid byte sequence for encoding UTF-8

### ISSUE THREAD

**Issue by tokiaquino** [dbeaver/dbeaver#2513]
When try to expand any item child (tables, views, indexes, etc...) of a scheme, i'm getting 22021: invalid byte sequence for encoding UTF-8 error

<img width="954" alt="imagen" src="https://user-images.githubusercontent.com/3130266/32729789-b37ff0ee-c863-11e7-8460-b810b343038c.png">

**Comment by serge-rider** [comment]
What is your database/version?
Are you sure you are using correct driver (PostgreSQL native)?

**Comment by tokiaquino** [comment]
The DB version is 9.6,

And this is my driver configuration
<img width="888" alt="imagen" src="https://user-images.githubusercontent.com/3130266/32743341-ddc25564-c88a-11e7-845e-bf8d55433f0a.png">

**Comment by tokiaquino** [comment]
Using Query Manager, i found the query that fail is 
`SELECT
	c.oid,
	c.*
	d.description
FROM
	pg_catalog.pg_class c
LEFT OUTER JOIN pg_catalog.pg_description d ON
	d.objoid = c.oid
	AND d.objsubid = 0
WHERE
	c.relnamespace = 18292
	AND c.relkind NOT IN(
		'i',
		'c'
	)`

I breakdown the query and found the column pg_catalog.pg_description.description of one specific record give me that error.

**Comment by serge-rider** [comment]
Interesting.
You could try to upgrade driver to the most recent version (42.1.4+).
No other ideas so far..

**Comment by tokiaquino** [comment]
I upgrade te version, same error!
Maybe it's the same of [this](https://stackoverflow.com/questions/38631101/)

**Comment by tokiaquino** [comment]
I upgrade te version, same error!
Maybe it's the same of [this](https://stackoverflow.com/questions/38631101/)?

**Comment by tokiaquino** [comment]
> Maybe it's the same of this?

Aparently is the same

<img width="245" alt="imagen" src="https://user-images.githubusercontent.com/3130266/32780878-a489d262-c921-11e7-98df-53189ab47ebe.png">

**Comment by tati-kru** [comment]
It looks like it is not a DBeaver issue and we cannot fix from our side. If you have any ideas about enhancement of DBeaver, please write a comment and we will reopen the ticket.
