### ISSUE TITLE
Database name shown twice in the Database Navigator tree

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2515]
DBeaver - **Version 4.2.5 CE**
DBeaver JDBC driver: **Microsoft**
Operating System: **Windows 7** / **Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

A database name is shown twice in the Database Navigator tree when the database name is filtered as a **Include Catalog**.

**o** Create a database source/connection do the **AdventureWorks2012** (SQL Server Demo Database)
**o** Right click on the database source/Connection and choose **Edit Connection**.
**o** Edit the **CONNECTION SETTINGS** -> **DATABASE/SCHEMA NAME** as **AdventureWorks2012**.
**o** Choose **GENERAL** settings.
**o** Click on the **FILTERS -> CATALOGS**.
**o** Include the **AdventureWorks2012** in the filter.
**o** Save changed Connection.
**o** Restart _DBeaver_ and connect to the **AdventureWorks2012** database.
**o** Press **CTRL+SHIFT+D** to **OPEN DATABASE OBJECT**.
**o** Enter **[person]** as **item name**. Choose the **[Person.Person]** table. Press the **OK** button.
**o** Two active database entries for **AdventureWorks2012** database is shown in the **Database Navigator**.

Seems to have something to do with the CATALOG FILTER.

**Comment by serge-rider** [comment]
Sorry for the late fix, somehow I've missed this ticket.
