### ISSUE TITLE
Error when creating procedure/function/trigger where SQL script contain semicolon character

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2539]
DBeaver - **Version 4.2.5 CE**
DBeaver JDBC driver: **Microsoft**
Operating System: **Windows 7** / **Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

When Writing SQL scripts for SQL Server it is supported/encouraged to use ";" character as end of command marker.

But when trying to execute script in DBeaver that create procedure, function or triggers and contain ";" error messages are generated.

&nbsp;&nbsp; **Error occurred during SQL script execution**
&nbsp;&nbsp;  **Reason: SQL Error [102][S0001]: Incorrect syntax near ';'.**

Execute the SQL Scripts below using **SQL EDITOR** -> **EXECUTE SQLSCRIPT** menu choice.

**This work OK**

```
CREATE PROCEDURE **TestProc**
AS BEGIN
  SELECT 'TestProc'
END
GO
```

**This generate an ERROR**

```
CREATE PROCEDURE **TestProc**
AS BEGIN
  SELECT 'TestProc';
END;
GO
```

Seems that the ";" character after "**SELECT 'TestProc'**" make it fail. If run in _SQL Server Management Studio_ or _JetBrains DataGrip_ everything works ok.

**Comment by serge-rider** [comment]
DBeaver doesn't fully support SQL Server dialect (see #810). 
In order to execute complex SQL with delimiters select query in editor and execute it with <kbd>ctrl+enter</kbd>.

**Comment by johnjsora** [comment]
You need go to dbeaver preferences-sqleditor-sql processing and remove the semicolon on the statements delimiter

**Comment by pdanie** [comment]
Thanks for the tips **johnjsora**. Seems to work after that change.

**Comment by pdanie** [comment]
Only drawback is when I remove that semicolon is the separater I can no longer place the cursor at a SQL command line and choose execute if I have more SQL commands in the editor. _DBeaver_ will execute all SQL commands not only execute the SQL command under the cursor.

**Comment by pdanie** [comment]
Is there no way that _DBeaver_ when requesting **Execute script** _(Alt+X)_ can recognize if a colon are wrapped in a BEGIN/END or within a TRIGGER/PROCEDURE/FUNCTION ?

**PS**. Nowdays Microsoft recomment that i use colon to end each statement, so this is a frequent problem for me.

**Comment by Sleepful** [comment]
@johnjsora workaround works out to execute the script, just delete the delimiter char in the settings

**Comment by kseniiaguzeeva** [comment]
Is the ticket still actual for you?

**Comment by jeanrajotte** [comment]
Is it really completed? I'm not able to run the following:

```sql
create procedure bob (a char(32)
	BEGIN
        INSERT INTO log_api (id, api_name) values (234, a);
        SET @cargo = 1234;
        INSERT INTO log_api (id, api_name) values (235, @cargo);
    END
```

I have removed ";" from the preferences, as instructed above. I highlight the above text, press ctrl+enter, and get the following:

```
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BEGIN
        INSERT INTO log_api (id, api_name) values (234, a);
        SET ' at line 2

Error position: line: 1
```
because DBeaver parses on ;.

Same behaviour if I put only this statement in the editor and use alt+A. 

??
