### ISSUE TITLE
DBeaver version update download times out

### ISSUE THREAD

**Issue by haufs** [dbeaver/dbeaver#25480]
### Description

Prompted for update:
![image](https://github.com/dbeaver/dbeaver/assets/117753713/ed38de82-844f-42a8-9968-68cf15685f04)

Click Upgrade

install file downloads
![image](https://github.com/dbeaver/dbeaver/assets/117753713/ac137c93-a908-43b9-9929-842786cf2d1a)

gets to 98% and:
![image](https://github.com/dbeaver/dbeaver/assets/117753713/adc4b744-1523-46c6-9fb9-0556f87fcaab)

![image](https://github.com/dbeaver/dbeaver/assets/117753713/e0672b04-2645-4652-9828-fc23004e3cfb)

### DBeaver Version

Community Edition version 24.0.2

### Operating System

Windows 10

### Database and driver

not applicable

### Steps to reproduce

see Description

**Comment by LonwoLonwo** [comment]
Hello @haufs 

Did you try to repeat your steps?

**Comment by haufs** [comment]
Hello,
Please close this ticket, we discovered an issue on our side.
Thank you!

**Comment by LonwoLonwo** [comment]
Thanks for the update!
