### ISSUE TITLE
The interface is the local language

### ISSUE THREAD

**Issue by yujishe** [dbeaver/dbeaver#2570]
hi！
 I would like to ask what canceled the dbeaver international interface language design?
Is it localized language too large?
If this is the reason, you can build a separate file, so that people need to download!
Although English is the most widely spoken language, it is even more convenient to use a native language for people whose native language is not English.
This is just a suggestion.
Once again, thank you for developing this software, hope DBerver become better.

**Comment by serge-rider** [comment]
All localizations were disabled because they were outdated.
We going to enable localizations again in version 4.3 (see https://github.com/serge-rider/dbeaver/milestones)

**Comment by yujishe** [comment]
I will look forward to it. I want to promote Dberver to our project team,but they still feel that dbvisualizer is a little better. After my investigation and found that they like to use dbvisualizer only one reason, check out the results, you can directly modify the data on the results.

**Comment by serge-rider** [comment]
You can directly modify results (including custom SQL queries) in DBeaver as well. 
Not for any query but for the most.
