### ISSUE TITLE
PostgreSQL Timestamp & TimestampTZ discrepancy

### ISSUE THREAD

**Issue by StepanYankevych** [dbeaver/dbeaver#2575]
He Jkiss Team !

I'm experiencing following issue during about a year
Steps to reproduce using current versions (DBeaver 4.2.6 (win10/win7) PostgreSQL 9.6.6 RHEL7)
DB is Located in -5 timezone
One client is located on -5 timezone
Another one in +2 timezone
One more client in + 3 Timezone

`create table TMTZ_test (Test_TZ timestamptz default now(), test_wtz timestamp default now(), id int);`
Each of clients performs similar insert in during few seconds only 

+2 Timezone client performs 
`insert into TMTZ_test (id) values (1)`

+3 Timezone client performs
`insert into TMTZ_test (id) values (2)`

-5 Timezone client performs 
`insert into TMTZ_test (id) values (3)`

Let's do following select in dBeaver and pgAdmin
`select * from TMTZ_test`
See results in dBeaver 
2017-11-27 13:06:24.347469	**2017-11-27 13:06:24.347469**	1
2017-11-27 13:06:26.055396	**2017-11-27 13:06:26.055396**	2
2017-11-27 13:06:31.050823	**2017-11-27 06:06:31.050823**	3

PgAdmin4 results 

'2017-11-27 06:06:24.347469-05','**2017-11-27 13:06:24.347469**',1
'2017-11-27 06:06:26.055396-05','**2017-11-27 13:06:26.055396**',2
'2017-11-27 06:06:31.050823-05','**2017-11-27 06:06:31.050823**',3

As you can see test_wtz contains field converted to local timezone (_but still do not understand why +3 timezone and +2 timezone shows the same results_). 

If we perform each of inserts in pgAdmin then everything looks good. 

It is expected to use server timezone while converting timestamptz to timestamp.

Looking forward your answer/fix

Thanks!
Stepan.

**Comment by StepanYankevych** [comment]
Any updates?
I saw some comments (somewhere there ) that new jdbc driver should allow to implement the fix.
I still need to use PgAdmin while processing any code where( for example) before insert/update trigger sets clock_timestamp into row. Like insert_time, update_time etc...

**Comment by psteffek** [comment]
Just a note to say I'm running into a similar issue, SHOW TIMEZONE against postgres shows America/Los_Angeles in DBeaver. In pgadmin it shows UTC...

**Comment by uslss** [comment]
cannot reproduce an issue.
Ticket closed.
If it is still actual for you - feel free to reopen the ticket
