### ISSUE TITLE
SQL Error [08S01]: The "variant" data type is not supported.

### ISSUE THREAD

**Issue by angelmanner** [dbeaver/dbeaver#2577]
Dear Team
i use mssql 2012. and os is windows 10, dbeaver 4.2.6

An error occurs when viewing the sequence. The error message like this..

> SQL Error [08S01]: The "variant" data type is not supported.
>   The "variant" data type is not supported.

i just guess same case...Maybe....
[https://social.msdn.microsoft.com/Forums/sqlserver/en-US/b76a3ed6-dd5e-4d62-8c90-2a4487642c4c/sql-2005-error-the-variant-data-type-is-not-supported?forum=sqldatabaseengine](url)

> SELECT SERVERPROPERTY('ProductVersion')    <-  gives the same error
> 
> SELECT CONVERT(varchar(100), SERVERPROPERTY('ProductVersion'))  <- fixes the problem (make sure your varchar field you convert to has enough space for your datatype)

Thanks for your help.

**Comment by agnahi** [comment]
Same error, when trying to open the new SQL Sequence tree in the navigator pane

MsSQL Azure, Win 10, dbeaver 4.2.6

**Comment by angelmanner** [comment]
i solved the issues.. i changed from mssqljdbc to TDS driver... 

http://jtds.sourceforge.net/
http://beone.tistory.com/159
http://beone.tistory.com/159
