### ISSUE TITLE
ADD search/find text in cell editor (Shift+Enter)

### ISSUE THREAD

**Issue by allanlaal** [dbeaver/dbeaver#2584]
# use case

I have a large text cell to edit.
I open the large cell editor by hitting Shift+Enter when the cell is selected, a large editor opens up
I then need to find a string inside the text of that cell to edit sth so I hit Ctrl+F

# expected result

a search dialog opens 

# actual result

nothing. I have to copypaste the cell contents into a proper text editor to find text inside it

**Comment by serge-rider** [comment]
Agreed, this would be helpful

**Comment by serge-rider** [comment]
In 3.0 I'll add find/replace thru context menu.
Shortcut support will be added later.

**Comment by esequiel-ferreira** [comment]
A button to print cell content would be nice as well.

**Comment by serge-rider** [comment]
I've added ability to open strings in a separate text editor. This will give you all standard editor features (search/replace, print, etc).
Default editor type (dialog or text editor) can be configure in preferences (Database->Result Sets->Editors->String)

![image](https://user-images.githubusercontent.com/6398845/34641722-8717d734-f319-11e7-8087-e75992ef7511.png)

![image](https://user-images.githubusercontent.com/6398845/34641735-ac5307d0-f319-11e7-909c-74a64a2efba0.png)
