### ISSUE TITLE
PostgreSQL DDL generation losing comment

### ISSUE THREAD

**Issue by StepanYankevych** [dbeaver/dbeaver#2585]
DBeaver 4.2.6
PostgreSQL 9.6.6 / 10.1
Steps to reproduce 
Run following script 
```
create table test (my_column int);
comment on column test.my_column is 'my comment';
```

Check if it looks good. 
![image](https://user-images.githubusercontent.com/25589816/33420972-3e407886-d5b9-11e7-8691-8108cd21915c.png)

Then right click on the table and choose 
Generate SQL => DDL
The result is following statement
```
CREATE TABLE test (
	my_column int4 NULL
)
WITH (
	OIDS=FALSE
) ;
```

As you can see comment is missed.

**Comment by serge-rider** [comment]
Yes, DBeaver doesn't append comments to DDL.  Mark as FR.
