### ISSUE TITLE
[Question]"Open Declaration" doesn't show the changes i've made

### ISSUE THREAD

**Issue by super3dmax** [dbeaver/dbeaver#2587]
if i edit a procedure, save it ,and then press f4 to generate ddl, it doesn't show the changes i've made.
after saving, i didn't refresh manually, because i am used to minimizing the database navigation.
i edit a procedure in "SQL editor", save it by "CTRL + Enter".
DATABSE:sqlserver 2008 r2.

There's the same problem for DB2, but not "Open Declaration", it's "View Procedure".
"Open Declaration" can't generate a ddl for procedure with db2, how to?

**Comment by serge-rider** [comment]
After you execute some DDL scripts in SQL editor you need to manually refresh database object in the navigator.

Click on your procedure in navigator and press <kbd>f5</kbd> or choose "Refresh" from context menu.

**Comment by super3dmax** [comment]
i found a option here, Preferences -> General -> Editors -> SQL Editor -> SQL Processing -> Refresh active schema after SQL execution. 
can this solve my problem?

**Comment by serge-rider** [comment]
Sorry for so late reply.

No, "Refresh active schema" is very different thing (DBeaver will read active schema name after each query execution).
Currently manual refresh of database navigator is the only way to refresh metadata.
