### ISSUE TITLE
Exporting data from postgres gives quotes around character fields that look like numbers when choosing NO quotes in export

### ISSUE THREAD

**Issue by rvantland** [dbeaver/dbeaver#2589]
Exporting data from postgres gives quotes around character fields that look like numbers when choosing NO quotes in export. Also the header contains quotes. Please make the option available to export without any quotes.

**Comment by rvantland** [comment]
Nb i have this problem on my MAC, did not test it on a Windows laptop yet. I often have to make exports and it is very unhandy when i need to export a mega file of 20mio rows and dbeaver is putting quotes (") around every row. Tried all kind of settings but did not find out how not to get them..

**Comment by serge-rider** [comment]
You can use space character as quote to disable quotes:
![image](https://user-images.githubusercontent.com/6398845/33922611-fd7cc966-dfdc-11e7-9846-95c804443f2d.png)

**Comment by tati-kru** [comment]
hi @rvantland 
Does a suggested way suit you?

**Comment by rvantland** [comment]
Seems i had characters escape blanked too and then it is still quoting cells starting with numbers. With that one filled with quotes and the quote character filled with the space, then it does work. thnks!
