### ISSUE TITLE
PL/SQL wrong block end matching

### ISSUE THREAD

**Issue by dariopnc** [dbeaver/dbeaver#2590]
The following (valid) block of PL/SQL is not run through DBeaver 4.2.6 using Alt+X

```
DECLARE
	test_v NUMBER:=0;
	FUNCTION test_f(value_in_v IN number)
	RETURN
		varchar2
	IS
		value_char_out VARCHAR2(10);
	BEGIN
		SELECT to_char(value_in_v) INTO value_char_out FROM dual;
		RETURN value_char_out;
	END; 
BEGIN
	dbms_output.put_line('Start');
	dbms_output.put_line(test_v||chr(9)||test_f(test_v));
	dbms_output.put_line('End');
END;
```

It prints the following error:

```
SQL Error [6550] [65000]: ORA-06550: line 11, column 5:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   begin function pragma procedure

SQL Error [6550] [65000]: ORA-06550: line 11, column 5:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   begin function pragma procedure

  ORA-06550: line 11, column 5:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   begin function pragma procedure

  ORA-06550: line 11, column 5:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   begin function pragma procedure

```

**Comment by serge-rider** [comment]
Seems to be a bug in blocks parsing.
Thanks for report.

Workaround: select full query and execute with <kbd>ctrl+enter</kbd>.

**Comment by arnaud-jacquemin** [comment]
Hello,
The workaround doesn't seem to work with DBeaver 5.0.0 ( I don't think it worked with the previous version either).
With the provided example I get the following error :

> 
> SQL Error [6550] [65000]: ORA-06550: line 1, column 8:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    begin function package pragma procedure subtype type use
>    <identificateur> <identificateur entre guillemets> form
>    current cursor
> The symbol "" was ignored.
> ORA-06550: line 2, column 19:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    begin function package pragma procedure subtype type use
>    <identificateur> <identificateur entre guillemets> form
>    current cursor
> The symbol "" was ignored.
> ORA-06550: line 3, column 39:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    return
> 
>   SQL Error [6550] [65000]: ORA-06550: line 1, column 8:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    begin function package pragma procedure subtype type use
>    <identificateur> <identificateur entre guillemets> form
>    current cursor
> The symbol "" was ignored.
> ORA-06550: line 2, column 19:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    begin function package pragma procedure subtype type use
>    <identificateur> <identificateur entre guillemets> form
>    current cursor
> The symbol "" was ignored.
> ORA-06550: line 3, column 39:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    return
> 
>     SQL Error [6550] [65000]: ORA-06550: line 1, column 8:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    begin function package pragma procedure subtype type use
>    <identificateur> <identificateur entre guillemets> form
>    current cursor
> The symbol "" was ignored.
> ORA-06550: line 2, column 19:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    begin function package pragma procedure subtype type use
>    <identificateur> <identificateur entre guillemets> form
>    current cursor
> The symbol "" was ignored.
> ORA-06550: line 3, column 39:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    return
> 
>       SQL Error [6550] [65000]: ORA-06550: line 1, column 8:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    begin function package pragma procedure subtype type use
>    <identificateur> <identificateur entre guillemets> form
>    current cursor
> The symbol "" was ignored.
> ORA-06550: line 2, column 19:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    begin function package pragma procedure subtype type use
>    <identificateur> <identificateur entre guillemets> form
>    current cursor
> The symbol "" was ignored.
> ORA-06550: line 3, column 39:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    return
> 
>         ORA-06550: line 1, column 8:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    begin function package pragma procedure subtype type use
>    <identificateur> <identificateur entre guillemets> form
>    current cursor
> The symbol "" was ignored.
> ORA-06550: line 2, column 19:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    begin function package pragma procedure subtype type use
>    <identificateur> <identificateur entre guillemets> form
>    current cursor
> The symbol "" was ignored.
> ORA-06550: line 3, column 39:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    return
> 
>         ORA-06550: line 1, column 8:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    begin function package pragma procedure subtype type use
>    <identificateur> <identificateur entre guillemets> form
>    current cursor
> The symbol "" was ignored.
> ORA-06550: line 2, column 19:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    begin function package pragma procedure subtype type use
>    <identificateur> <identificateur entre guillemets> form
>    current cursor
> The symbol "" was ignored.
> ORA-06550: line 3, column 39:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    return

**Comment by arnaud-jacquemin** [comment]
Hello,
The workaround (`ctrl+enter`) now works with Dbeaver 5.1.3.
`Alt+X` is still not working, so this bug report is still relevant.

**Comment by uslss** [comment]
Still reproduces on 6.0.3 version

**Comment by serge-rider** [comment]
The problem was in nested PL/SQL blocks parser

**Comment by uslss** [comment]
verified

**Comment by serge-rider** [comment]
It was broken at some moment. Block header additions were reverted in #8208. We need to find another way to parse this properly.

**Comment by uslss** [comment]
verified
