### ISSUE TITLE
Renaming table is not reflected on the generated INSERT statements

### ISSUE THREAD

**Issue by anatoliykmetyuk** [dbeaver/dbeaver#2591]
Reproduction steps:

1. Create a random table and populate it with some values
2. `alter table <your_table> rename to <your_table>_bak;`
3. Take from the Data view of the table, select a random value, right-click -> Generate SQL -> INSERT.
4. The resulting insert statement will target the table by its old name (e.g. `<your_table>` instead of `<your_table>_bak`).

**Comment by uslss** [comment]
Issue isn't reproducible.
Ticket closed
