### ISSUE TITLE
DBeaver freezes: mysql, edit an enum cell

### ISSUE THREAD

**Issue by knoxyz** [dbeaver/dbeaver#2594]
Hello,

DBeaver 4.2.6 is able to read out **mysql** tables with **enum** columns.
But it will freezes each time if I do a double click  on such a cell to modified it.

It's only possible to edit the value my context menu.

PS: DBeaver is works pretty well at all.

**Comment by serge-rider** [comment]
Can't reproduce on Windows.
What is your OS?

**Comment by knoxyz** [comment]
Generally I use Kubuntu 17.10 but just try it out with Windows. It works with Win 7.

**Comment by knoxyz** [comment]
So only the linux-version contains this problem.

**Comment by exussum12** [comment]
using xubuntu 17.10 with dbeaver 4.2.6 cant replicate this

**Comment by serge-rider** [comment]
@knoxyz I can't reproduce this too. Could you make a thread dump next time DBeaver will freeze (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump) and post it here?

**Comment by tati-kru** [comment]
hi @knoxyz
Do you have any updates about this issue? It looks like we will not be able to fix it without your help.

**Comment by knoxyz** [comment]
Hi @tati-kru 
I never found out the reason for this crashes.
A re-installation of dbeaver and driver doesn't fixed that.

But last week an kernel updated destroy my kubuntu 17.10.
After a complete new set up of OS and software everything works fine again.

Have a nice weekend
knoxyz

**Comment by tati-kru** [comment]
@knoxyz nice to hear that, thank you!
