### ISSUE TITLE
FIX query editor: results and query show/hide buttons too small on HiDPI screens

### ISSUE THREAD

**Issue by allanlaal** [dbeaver/dbeaver#2601]
the ⯅⯆ buttons in the middle between the query and the results are so small its hard to click on them:

![screenshot](https://image.ibb.co/hpkW5G/Screenshot_at_2017_12_05_13_00_05.png)

**Comment by maffe** [comment]
The expand/collapse icons in the navigator tree are also affected. There is also a mismatch between the visible icon and the area reacting to mouse clicks, making it hard to trigger the actions.

**Comment by allanlaal** [comment]
UI bug still present in 7.3.4

**Comment by uslss** [comment]
will be resolved in #12768
