### ISSUE TITLE
More intuitive column/block text selection in sql editor

### ISSUE THREAD

**Issue by andremp3** [dbeaver/dbeaver#2602]
Hi Guys, 

The actual short cut for block text selection (alt+shit+a) isn't intuitive like only pressing ALT (in other editors).

Could you guys set just ALT as default shortcut to this?

Thank you in  advance!

**Comment by esequiel-ferreira** [comment]
Additionally, this default shortcut is a toogle. In most text editing software, block text selection is only active while ALT is pressed.

**Comment by serge-rider** [comment]
Sounds reasonable. However it is core Eclipse editor functionality, not sure I'll be able to patch it so easily..

**Comment by rabund** [comment]
In addition, there is a bug. When you have selected a block and try to enter the opening bracket, only on the first line the bracket (opening and closing) is insert the content between start and end of selection gets lost.

**Comment by esequiel-ferreira** [comment]
I just do not use this feature at Dbeaver. I usually switch to notepad++
and then after edit the query by column select/edit i switch back to
Dbeaver.

*Esequiel de Paiva Ferreira*
(11) 95955 4778

2018-07-03 10:00 GMT-03:00 Ralf Bund <notifications@github.com>:

**Comment by rabund** [comment]
That's exactly what I'm doing now. But all of dBeaver's functions can be done by switching to another tool. I think, the editor should be good enough to handle this without the need to switch to NP++.

**Comment by serge-rider** [comment]
@rabund Partially this bug (with selection) was fixed in #3642. Apparently this fix doesn't help in some circumstances.
Adding extra fix, thanks for noticing.
