### ISSUE TITLE
User defined functions, incorrect working aggregation functions

### ISSUE THREAD

**Issue by chichivica** [dbeaver/dbeaver#2603]
Many thanks for really awesome project! 
I would like to report a small issue related with user defined function in t-sql.
I'm using Microsoft JDBC Driver for SQL Server. And I have simple user defined function, **fGiveTaskForAnalysis**. So, when I made a plain query, 
```
select * from [dbo].[fGiveTaskForAnalysis](9)
```
Pagination works pretty well, at the first time downloaded 200 rows, and when I'm scrolling until bottom of the results, new results is fetched
![](https://i.imgur.com/5eOu2qr.png)
![](https://i.imgur.com/rNTw62o.png)
But the problem is with the count and filtering queries:
![](https://i.imgur.com/JvaleSw.png)
It looks like it only calculates prefetched rows for paginated results.
But from the Sql Management Studio everything is ok:
![](https://i.imgur.com/ATXKesU.png)

**Comment by serge-rider** [comment]
Looks like a bug. Thanks for report!
Could you post some SQL snippet (user function definition) to reproduce this in default SQL Server database (e.g. using some system table).

**Comment by uslss** [comment]
Ticket is closed.
There is no any update on this ticket more than a year. If issue is still actual for you, feel free to reopen the ticket.
