### ISSUE TITLE
DB2 and MySQL Show Table Privileges

### ISSUE THREAD

**Issue by jtorresc** [dbeaver/dbeaver#2606]
Hello, I can not find the tab about the privileges of the tables in databases of type DB2 and MySQL. However, this tab exists for Oracle and PostgreSQL.

**Oracle**

![image](https://user-images.githubusercontent.com/15322059/33635895-13b409b0-da1a-11e7-91e4-767cfd4cd6e9.png)

**DB2**

![image](https://user-images.githubusercontent.com/15322059/33635818-cfda1bd0-da19-11e7-8534-ebe0047016fb.png)

Thank you...

**Comment by titou10titou10** [comment]
HI,
In DB2 you can see all privileges and authorities held by roles/groups/users  under the "Security" tab (At the same level as the "Schemas" tab)
This is the "reverse" view (role/group/user -> object) compared to what you see for Oracle (object -> role/group/user)
Denis

**Comment by jtorresc** [comment]
With my database user, I do not have dba privileges and it shows an error of privilege when consulting the SYSCAT.MODULEAUTH object when clicking on this tab. Is there another alternative?

Thank you...
