### ISSUE TITLE
Suggested Improvement - Simplify resultset filtering

### ISSUE THREAD

**Issue by 0biWanKenobi** [dbeaver/dbeaver#2619]
I'd like to suggest a simpler, quicker way to filter a resultset by column(s) value(s). Currently the user has to right click a column, and choose Order\Filter, or use F11, while I propose a filter icon (permanent or on hover) as a quicker way to access filters. Also, I think directly listing all possible values (as you can do with the IN.. filter) would make filtering much quicker. The screenshot below is taken from dbForge: their strategy is to tuck the "advanced" filters in a separate popup, while giving immediate acces to null, not null, and a list of distinct values. I've been able to test that solution for a while, it' really effective.

![image](https://user-images.githubusercontent.com/4061104/33800821-11a06268-dd49-11e7-8a2c-473feb53667b.png)

**Comment by serge-rider** [comment]
This makes sense. But we'll need to think a bit more about UI consistency. Column header is already divided on 3 zones (draggable icon, selectable title and sortable icon). Adding one more might be a bit confusing.

BTW Inline combo with list of possible (existing) values is also useful for cell editor.

**Comment by 0biWanKenobi** [comment]
Yeah, I agree.. maybe the show-on-hover (or just dim and highight?) could help there. Great idea about the cell editor!

**Comment by 0biWanKenobi** [comment]
I decided to give it a try, this is the result so far:
![image](https://user-images.githubusercontent.com/4061104/34427036-a5c1b3c2-ec3d-11e7-93aa-edc3434a543d.png)

I still need to bind value selecting with actual resultset filtering, but it looks nice to me!

**Comment by serge-rider** [comment]
Thanks for contributing!
Additional enhancements were also pushed
