### ISSUE TITLE
Bad driver [Informix] configuration

### ISSUE THREAD

**Issue by INGCRENGIFO** [dbeaver/dbeaver#2621]
Hello, I have updated dbeaver to version 4.3.0 and the following error has occurred.

![image](https://user-images.githubusercontent.com/12200313/33854756-cb56e1e4-de90-11e7-9f9b-24d4c0336eb9.png)

![image](https://user-images.githubusercontent.com/12200313/33854781-e3d05692-de90-11e7-9f2f-f5209bcba9a1.png)

Have you deleted the informix driver? :(

**Comment by serge-rider** [comment]
Informix driver configuration is there, it wasn't changed.

But driver itself (jar files references) was removed from community edition - as well as all other non-opensource or non public domain drivers.  Now all such drivers are bundled in EE version.

You can download Informix driver (as jar) from IBM web site or get it from your DBA. And the add it in driver configuration in DBeaver driver edit dialog: 
Main menu->Database->Driver manager->Informix:
![image](https://user-images.githubusercontent.com/6398845/33887388-ae57606c-df5a-11e7-92a2-bad7d596f25f.png)

**Comment by INGCRENGIFO** [comment]
thanks for your answer.

It is a pity that they have removed the drivers, I will search how to download them.

**Comment by tati-kru** [comment]
It looks like this question was solved. So it will be closed. But if you have any additional questions, please write a comment and we will reopen it.
