### ISSUE TITLE
Newest version of DBeaver keeps crashing

### ISSUE THREAD

**Issue by hepstein** [dbeaver/dbeaver#2628]
I have a bunch of open tabs in Dbeaver for sql editors for various connections. Whenever I switch tabs from a Mysql editor tab to a psql editor tab, the program does not respond for a while. Eventually, it recovers. Any suggestions?

**Comment by serge-rider** [comment]
Is the a problem of the newest version (4.3) or you did see this behavior before?
- What is your OS?
- What type of installer do you use?
- Is there anything valuable in log files (https://github.com/serge-rider/dbeaver/wiki/Log-files)?

**Comment by hepstein** [comment]
It looks like I somehow missed the 4.3 version… I was running 4.2.6.

Thanks so much for taking the time to check on this!

Hadassah Epstein

**Comment by tati-kru** [comment]
It looks like this question was solved. So it will be closed. But if you have any additional questions, please write a comment and we will reopen it.
