### ISSUE TITLE
Sybase and Dbeaver tables not showing within project pane

### ISSUE THREAD

**Issue by twosmooth4u** [dbeaver/dbeaver#2633]
Hello All, 

I am having an issue not being able to see the tables within my Sybase DB. When I connect to the sybase, I am able to see all databses. However, when I click on any of the databses, only the usres from the User Folder appear. No folders appear (Ie. views, tables, functions, Users.) Can you help me with this issue. 

NOTE: I am able to query the databse with know issues. 
          
Using: JTDS -1.3.1.jar file for connection. 

Thank you, 

- TW4U

**Comment by serge-rider** [comment]
Could you post a screenshot? 
You can erase any secure information from it.

**Comment by twosmooth4u** [comment]
Sure.  I've attached the image. 

![22](https://user-images.githubusercontent.com/11982142/34123567-ddfb2db0-e3e4-11e7-9e95-8cf3a682d547.jpg)

**Comment by serge-rider** [comment]
Looks like a bug in schema reading, similar to SQL Server bug (#2626).
Could you check the fix in EA version: https://dbeaver.jkiss.org/files/ea/

**Comment by twosmooth4u** [comment]
Hello agian, 

The issue continues while connected to my Sybase server. 
Instead of the users now it is the roles that apear and none of the schema. Pic above reflects the same ting basically/.

**Comment by collicalex** [comment]
Hi,

Have you check if tables are listed under "dbo" user?
On my server, only "dbo" create tables, so all tables are list under the "dbo" user node.

But, if I connect under another user (who has the privilege to read a table), I can do a select * from my_table. Even if "my_table" is notlisted under my user node.

Regards

**Comment by shockshot** [comment]
same issue to me. I can see "dbo" user with 4.3.0, but 4.3.1. I tested other version drivers, but not worked.
Under "dbo" user, table lists appear.

**Comment by serge-rider** [comment]
It is a bug in Sybase schema reading, thanks for report.

**Comment by serge-rider** [comment]
In 4.3.2 DBeaver will show only non-empty schemas by default.
Also there will be a new option in connection settings:
![image](https://user-images.githubusercontent.com/6398845/34480033-12cc9f74-efbb-11e7-8038-363dac94f467.png)

**Comment by alexandresn** [comment]
this error occurred to me using the ms sql server with jtds driver

**Comment by serge-rider** [comment]
SQL Server and Sybase use the same driver/extension. Thus they share the same errors :)
