### ISSUE TITLE
Bug on calling stored procedures

### ISSUE THREAD

**Issue by lbassuncao** [dbeaver/dbeaver#26397]
### Description

Wrong behaviour on execution of stored procedures

### DBeaver Version

24.0.3 CE

### Operating System

Ubuntu 22.04

### Database and driver

Database version: MySQL v8.0.36
MYSQL JDBC Driver: Connector/J 8.3.0 

### Steps to reproduce

1. Create a script file with many stored procedures, one by each line
2. Try to execute just one stored procedure, setting the cursor on the line of the stored procedure to execute,  using the key combination: CTRL+ENTER

### Additional context

On a file with many calls to stored procedures, previously it was possible to set the cursor on the line of one stored procedure and press CTRL+ENTER to execute. With the latest update 20.0.3, it's no longer possible to execute the action the the key combination. Instead it calls all the stored procedures on the same script.

**Comment by E1izabeth** [comment]
Please try switching Blank line is statement delimiter setting to Always
![image](https://github.com/dbeaver/dbeaver/assets/28875055/be8457a0-d62c-4acb-ac2f-67ce518cf3f5)

**Comment by E1izabeth** [comment]
Unfortunately, I am unable to reproduce the issue you are experiencing. Could you please provide the clear steps to follow?

**Comment by lbassuncao** [comment]
The solution you gave solve the problem. 

Thanks. :)
