### ISSUE TITLE
Select SQL code and then Run Script, throws Compilation Error if code ends in single semicolon followed by comments

### ISSUE THREAD

**Issue by MikeCSanJose** [dbeaver/dbeaver#26416]
### Description

After upgrading to latest version this afternoon, the first script I tried to run (running fine last week) failed with error.  I was able to isolate and repeat the issue.  I am running over Snowflake.  The simplified code below yields the same error.

Select either entire line below, then click "Execute SQL script", get the error below.
select 10 ; -- Comments
select 10 ; /* Comments */

Error occurred during SQL query execution
Reason:
SQL Error [1003] [42000]: SQL compilation error:
syntax error line 2 at position 0 unexpected 'LIMIT'.

Adding a second semicolon and the code runs fine:
select 10 ; ; -- Comments
select 10 ; ; /* Comments */

### DBeaver Version

Community 24.0.3.202404211624

### Operating System

Windows 10 Enterprise - 19045.4291

### Database and driver

Snowflake JDBC driver

### Steps to reproduce

Select either entire line below, then click "Execute SQL script", get the error below.
select 10 ; -- Comments
select 10 ; /* Comments */

Error occurred during SQL query execution
Reason:
SQL Error [1003] [42000]: SQL compilation error:
syntax error line 2 at position 0 unexpected 'LIMIT'.

Adding a SECOND semicolon and the code runs fine:
select 10 ; ; -- Comments
select 10 ; ; /* Comments */

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
You could try switching `Blank line is statement delimiter` setting to `Always`
![image](https://github.com/dbeaver/dbeaver/assets/28875055/be8457a0-d62c-4acb-ac2f-67ce518cf3f5)

**Comment by E1izabeth** [comment]
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.

**Comment by Moridin11** [comment]
I have tested this with 24.0.4 and I am still experiencing the issue

**Comment by jachincollins** [comment]
> I have tested this with 24.0.4 and I am still experiencing the issue

I am still experiencing this issue as well.
```
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎11/‎1/‎2021
OS build	19045.4170
Experience	Windows Feature Experience Pack 1000.19054.1000.0
```

**Comment by E1izabeth** [comment]
Please provide examples to reproduce and create a new issue. This one is closed.

**Comment by MikeCSanJose** [comment]
@E1izabeth - I submitted the original bug report.  I'm now using Version 24.0.4.202405051837.  Seems to be working for me.  My only issue now is that my 24.0.3 "work-around" was to use double semi-colons to avoid the issue.  When I have double semi-colons on 24.0.4, now I get an "Empty SQL Statement" error - which I expect and was how it was working prior to 24.0.3.  Will be on the look-out for any remaining issues, and trying to remember to not use the double semi-colons anymore.
