### ISSUE TITLE
Multiple taskbar buttons for multi windows 

### ISSUE THREAD

**Issue by DavidHJong** [dbeaver/dbeaver#26417]
**Is your feature request related to a problem? Please describe.**
When I open multiple windows (floating windows) in DBeaver, they share one button in the taskbar. When I click on that button, it will show any DBeaver window randomly. I can't select which window to show. 

**Describe the solution you'd like**
Make each floating window to have a separate button in the taskbar, so they are selectable. 

I'm using Windows 10.

**Comment by E1izabeth** [comment]
Please clarify which button are you talking about

**Comment by DavidHJong** [comment]
It's the button in the windows taskbar, as shown in the screenshot. 
<img width="1280" alt="Screenshot 2024-05-01 103507" src="https://github.com/dbeaver/dbeaver/assets/31554275/c2675427-5863-457d-a49d-eba771adaccb">

**Comment by E1izabeth** [comment]
What is floating window? If you're talking about modal windows inside the application, then I'm not sure we can do it. The modal window always has parent, so when you open the parent window, you should see the modal one.
DBeaver is based on Eclipse platform. And Eclipse has the same behavior with modal windows on Windows 10.

**Comment by DavidHJong** [comment]
I don't know modal window. But here is what I want. As you can see I have two windows opened in two monitors. But there are only one button(icon) in the taskbar. Any way to make each window a unique button? 

<img width="2560" alt="Screenshot 2024-05-06 152801" src="https://github.com/dbeaver/dbeaver/assets/31554275/c3dafe24-4e13-43c7-aee1-02ef189abd23">

**Comment by E1izabeth** [comment]
Have you tried opening new window with this button? 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/bdd5f403-8ec6-4e27-90ff-6a7b9b08d822)


If I use it, I have more than one windows in the taskbar
![image](https://github.com/dbeaver/dbeaver/assets/28875055/7ab68b8b-f36a-4c30-af4d-9a2096b0b7d0)

**Comment by DavidHJong** [comment]
Oh I didn't know that. Thank you! It works. But one more problem. I can't drag tabs between the two windows. Any way to do that?

**Comment by E1izabeth** [comment]
I think there is no way to drag-n-drop tabs between different windows
