### ISSUE TITLE
Feature Request: Delete command w/ Ignore Foreign Key Constraint

### ISSUE THREAD

**Issue by benyanke** [dbeaver/dbeaver#2642]
When deleting all the tables in a DB which contain a bunch of FKs, I often need to run the delete 2 or 3 times, due to key issues.

I'd love an option to integrate FK-no-check mode for deleting.

Working on MySQL/MariaDB, assuming it also applies elsewhere.

**Comment by serge-rider** [comment]
Looks similar to #2535
