### ISSUE TITLE
is it possible to export (postgres) / import (mariadb) whole database with schema?

### ISSUE THREAD

**Issue by et4891** [dbeaver/dbeaver#2644]
I am actually trying to migrate from postgres to mariadb, is it possible to migrate through your software? I thought data export / import would be the one to do the job but I think I misunderstood that it only exports row data of the tables, or am I doing this wrong? Can I have some instructions please?  Thanks in advance

P.S. first time posting, wanted to label help wanted but can't find a way to label

**Comment by serge-rider** [comment]
There is no full cross-database dump/restore feature. Just because they are too different and you have to specify mapping manually.

You could try data transfer (Export data->specify target database/schema).

**Comment by et4891** [comment]
I tried the target database but keeps giving me error too.  At least the data export for each data does help a lot since the exporting sql are really close to mariaDB, I would just have to import them one by one carefully
