### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by rm17tink** [dbeaver/dbeaver#26446]
### Description

SQL error now hides in the bottom right corner of the statistics. How can it be visually front and center in the below output? 

### DBeaver Version

Community Edition 22.1.5.

### Operating System

Windows 10

**Comment by E1izabeth** [comment]
Please provide footage of your issue. Currently it's not clear, what behavior you're talking about.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
