### ISSUE TITLE
Suggestion: Metadata "Show row count for tables" disabled by default (PostgreSQL)

### ISSUE THREAD

**Issue by GiannisDem** [dbeaver/dbeaver#2648]
I had some issues when working with PostgreSQL when this option was enabled by default.

Probably due to low performance of the count(*) and the sequential scan performed on the underlining table.

![image](https://user-images.githubusercontent.com/25582863/34044456-b54f88b8-e1ad-11e7-94a1-b7a8eeb6cd24.png)

**Comment by serge-rider** [comment]
In fact this option is disabled by default. 
At least since 4.x version. Perhaps you upgraded from some older version or enabled this option accidentally.

**Comment by chriszrc** [comment]
If we do enable this option, where is it? I opened the metadata panel from the right side toolbar, but I still don't see row count anywhere :(

**Comment by chriszrc** [comment]
For anyone else coming here, the option is here:

<img width="616" alt="Screen Shot 2021-08-17 at 11 40 17 AM" src="https://user-images.githubusercontent.com/25695785/129746914-e094a2c5-cc2e-4d9d-a9cd-0f1483d2086d.png">

But the actual table count is in the "Properties" panel, and is only populated when the table is highlighted in the Database Navigator:

<img width="1344" alt="Screen Shot 2021-08-17 at 11 42 47 AM" src="https://user-images.githubusercontent.com/25695785/129747362-f4248e7a-4c8f-4f24-993b-8293af0917ef.png">
