### ISSUE TITLE
Datetime column falsely shown as IDENTITY when generating DDL of table in MSSQL

### ISSUE THREAD

**Issue by someRandomGuyFromTheInternet** [dbeaver/dbeaver#26504]
### Description

When generating the CREATE TABLE statement in a MSSQL database it shows that a datetime column named `timestamp` is an IDENTITY column even though a datetime column cannot even be a IDENTITY.

### DBeaver Version

24.0.3

### Operating System

Windows

### Database and driver

Microsoft SQL Server 2019 (RTM-CU25) (KB5033688) - 15.0.4355.3 (X64) 
mssql-jdbc-8.2.0.jre8.jar

### Steps to reproduce

```
CREATE TABLE schema.WHY_IDENTITY1 (
	[timestamp] datetime  NOT NULL
	);

```
results in 

```
-- database.schema.WHY_IDENTITY1 definition

-- Drop table

-- DROP TABLE database.schema.WHY_IDENTITY1;

CREATE TABLE WHY_IDENTITY1 (
	[timestamp] datetime IDENTITY(0,1) NOT NULL
);
```

while 
```
CREATE TABLE schema.WHY_IDENTITY2 (
	[timestampd] datetime  NOT NULL
	);
```
correctly results in 
```

-- database.schema.WHY_IDENTITY2 definition

-- Drop table

-- DROP TABLE database.schema.WHY_IDENTITY2;

CREATE TABLE WHY_IDENTITY2 (
	[timestampd] datetime NOT NULL
);
```

### Additional context

SSMS generates the DDL correctly

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
Also the bug #8278 is reproducible again. Should be fixed in scope of this issue.
