### ISSUE TITLE
Convert MetaData into a view and link with sql editor

### ISSUE THREAD

**Issue by lidderupk** [dbeaver/dbeaver#2651]
Feature request - Datagrip has this feature where clicking on a table/schema in code shows DDL for that table/schema on the side. MetaData has this information already, but it is only viewable in the Output view. I wonder if this can be taken out into a view and linked with the sql editor? That way, I don't have to go into the "navigator" to view table structure when writing sql for tables I am not familiar with.

**Comment by serge-rider** [comment]
Currently you can try <kbd>CTRL+Click</kbd> or <kbd>F4</kbd> when your cursor is on table name. This will open table declaration is a separate editor.
Also you can use context information (>kbd>F2</kbd>) but it doesn't provide columns information. This can be improved.

I agree that having some easy way to see columns would be great. I'm just not very sure about this separate view..

**Comment by lidderupk** [comment]
I was initially thinking something like

![image](https://user-images.githubusercontent.com/3187457/34075725-23c7d648-e284-11e7-86c5-deb77d1c7f89.png)

It could also be just a popup/tooltip with the DDL. I used eclipse in a past life and something like the following? Just throwing ideas out there.

![image](https://user-images.githubusercontent.com/3187457/34075731-6d683f9a-e284-11e7-846f-078a1ae91d15.png)

**Comment by ruspl-afed** [comment]
It sounds like standard Eclipse "Outline" view support for DBeaver SQL editor

**Comment by serge-rider** [comment]
Usually Outline  (or Quick Outline) shows structure of currently opened object (e.g. Java class). It is not supposed to show context hints.
Screenshot above shows context "Information" tip which is triggered by <kbd>F2</kbd>.  We already support it but it shows just table properties and doesn't show table DDL.

We could include DDL  there but there is one concern. In some cases DDL extraction is a quite long procedure (may take 5-20 seconds). Forcing it in all context tips might be not so good as it looks.

Any thoughts?

**Comment by lidderupk** [comment]
I personally like a static view on the side like datagrip does instead of a tooltip that I need to bring up and then goes away. In either case, I think it is okay to show a progress bar or something similar. 

Any chance you can cache the result for the current session? From my experience, people tend to work with only 20% tables for 80% of the time. No scientific research to back that up :). Are you thinking of including the whole DDL? or a summary (columns names, type and length perhaps).

**Comment by ruspl-afed** [comment]
I agree that deferred content is not popup-friendly, so the static view sound reasonable for this. I'm not sure should it be a part of Outline or not, probably the separate view may give more flexibility to organize the layout.

**Comment by serge-rider** [comment]
I think this should more general. 
All panels (including MetaData) can be placed in separate view(s).
