### ISSUE TITLE
Flat file export to DB table

### ISSUE THREAD

**Issue by danieleangellotti** [dbeaver/dbeaver#2652]
Hi Serge,
from a Flat files connection (CSV), when I export a table to a DB connection choosing to create a new table, first I get a "New table _TABLE_NAME_ not found in _CONTAINER_ container" error and if I go back and try again then I get an error "ORA -00955 name is already used by an existing object": it seems that the creation of the table and the insertion of records occurs concurrently and that the first time the table is created after trying to insert at least one record, hence the "_TABLE_NAME_ not found ..." error. In fact, if I go back and choose to export to an existing table, I can find the table just created.
For the sake of completeness, I'm exporting to an Oracle connection, working with autocommit set to false.
I'd have another (related) question: is there anything already planned about importing from Microsoft Excel files? It would be very useful to be able to import XLS / XLSX files as already done with CSV files (I am currently using a tiny Java tool I developed to perform this kind of import).

Thank you for your attention, as always!

**Comment by serge-rider** [comment]
>from a Flat files connection (CSV), when I export a table to a DB connection choosing to create a new table, first I get a "New table TABLE_NAME not found in CONTAINER container" error and if I go back and try again then I get an error "ORA -00955 name is already used by an existing object"

Please check this in the recent version (there were a few fixes

Import from CSV (and other file formats) is planned in 5.1.x and 5.2.x versions (see #130)

**Comment by mdahlman** [comment]
Is there a regression in 6.0.5?
I am consistently getting this now when I try to Export from CSV to database (PostgreSQL):
New table my_table not found in container "RDS us-west-1 - my_schema"
