### ISSUE TITLE
not all queries being written to log

### ISSUE THREAD

**Issue by TobyHewing** [dbeaver/dbeaver#26572]
### Description

I have my configuration set to 'save to log files' which has written every query I run files in my 'Log Files Folder' but since upgrading I only get 1 or 2 queries written to the logs before it just stops writing them. I think this started happening at the prior version.

### DBeaver Version

Community edition Version 24.0.3.202404211624

### Operating System

macOS Sonoma 14.4.1

### Database and driver

I'm connecting to both postgres (PostgreSQL standard driver) and BigQuery (simba Google BigQuery driver)

### Steps to reproduce

Start DBeaver
execute a query against either DB
Hit and miss if the query gets written to the log file

**Comment by TobyHewing** [comment]
Seems to be fine in Version 24.0.0.202403091004

**Comment by E1izabeth** [comment]
Unfortunately, I can't reproduce the issue. Did you notice, if it happen with some specific queries?

**Comment by TobyHewing** [comment]
No, I just start DBeaver, the first 2 or 3 queries get written to the log then nothing after that. I've reverted to 24.0.0 and everything is being written. It appears the same issue exists in the query manager view in that I only see a handful of the queries I am executing.

**Comment by E1izabeth** [comment]
@TobyHewing do you have all these options checked?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/eebe1495-c793-41fc-963d-0577d26d57ab)

You can open it by right-clicking in Query Manager view

**Comment by TobyHewing** [comment]
I have User, User filtered, User script, Transactions and Queries ticked. In version 24.0.0 as soon as I execute a query it appears in the query manager view and in the log but in version 24.0.4 it does not. Changing the setting to include all of the above causes the BEGIN SESSION message to be written to the query manager view / log but no others are written

**Comment by MashaKorax** [comment]
Hello @TobyHewing, Could you please send a video with your issue?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by TobyHewing** [comment]
Having upgraded to 24.1.0 all queries are now logging correctly.
