### ISSUE TITLE
[Feature Request] Allow advance filtering in Database navigator.

### ISSUE THREAD

**Issue by prog-rajkamal** [dbeaver/dbeaver#2659]
## Issue

In database navigator we can filter out only tables and views.

![dbeaver__feat_table_filter__request](https://user-images.githubusercontent.com/11518519/34155291-bded4f62-e4de-11e7-973a-ea7f5b6bc1e8.png)

I believe that filtering capabilities can be improved by adding following features:

 1. Filter by Database (as MS SQL Server and postgres can have multiple dbs in a single server)
 2. Filter by Schema (all DBs have multiple schemas)
 3. Hide DB and schema which have no relevant table. 

## Motivation

In my day job. I deal with with Oracle and MS SQL database and need to filter out few tables among 100s of schema (and DBs for SQL Server). An advanced filter, like I am requesting, will immensely help me and others with similar use cases.

**Comment by serge-rider** [comment]
Advanced filters are already supported: https://github.com/serge-rider/dbeaver/wiki/Filter-Database-Objects

**Comment by prog-rajkamal** [comment]
@serge-rider I am already aware of schema filters. 

They have 2 limitations:
 
 1. They do not work on global level (i.e. on all databases). This means I need to set them for each database.
 2. They require extra steps for updating entries. 

The feature, "table/view filter", works on global level. and works by changing a single text input.

**Comment by serge-rider** [comment]
Agreed

**Comment by uslss** [comment]
implemented in #9718
