### ISSUE TITLE
"Search with Google" from menu should open default browser

### ISSUE THREAD

**Issue by JTMosaic** [dbeaver/dbeaver#26611]
When right-clicking on text and selecting "Search with Google" from within DBeaver, Safari is opened on macOS 14 even though it is not my default browser

Instead, either the default browser should open or there should be an option to select the installed browser to use

![image](https://github.com/dbeaver/dbeaver/assets/9417720/1f95e20c-c572-4409-b0af-db38f19708f8)

This may be a macOS setting but I'm opening this issue in case it isn't or can be overridden

**Comment by E1izabeth** [comment]
Does DBeaver installed as a standalone application or as a plugin for Eclipse?
Do you have any other plugins installed?

**Comment by JTMosaic** [comment]
Standalone. I have only Vrapper installed

**Comment by flambchap** [comment]
Thank you for the report. It's a bug in the Eclipse Platform.

**Comment by JTMosaic** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt/issues/1215#issuecomment-2098518056

**Comment by E1izabeth** [comment]
Please don't mix DBeaver command in result set and this Eclipse command. The issue is only about Eclipse command here.

**Comment by JTMosaic** [comment]
@E1izabeth, please read my comment in the Eclipse project.

I opened this case because the context menu in the results pane doesn't open the default browser. Yet, the context menu _outside_ of the results grid is a different command that does open in the default browser.

So, is this a DBeaver issue or an Eclipse issue?

**Comment by E1izabeth** [comment]
The issue description shows that you're trying to use Eclipse command from the error text.

**Comment by JTMosaic** [comment]
In that case, Eclipse has said that is a SWT component that there is likely nothing they can do. If that is correct, and the results grid is an SWT component, then please feel free to close this issue as unsolvable.

If, on the other hand, the results grid is not an SWT component, then please consider this an enhancement request to change the way it interacts with the context menu for search with google.

**Comment by E1izabeth** [comment]
Just to clarify :)
"Search with Google" - Eclipse's command
"Search selected text with Google" - DBeaver's command

**Comment by JTMosaic** [comment]
Thanks for the clarification.

Does that mean the results grid is, in fact, an SWT component?

**Comment by E1izabeth** [comment]
Results Grid with data is not, but the control where the error text is shown - yes.

**Comment by JTMosaic** [comment]
Why would the control on the error text or on text in the results grid be different than the one in a script?

I guess I can copy errors into the script window and then highlight and search... but I'm wondering if there is a way to reduce the steps and have the context menu in the error pane, results grid and scripts use the same control, at least for searching Google.

![image](https://github.com/dbeaver/dbeaver/assets/9417720/9bdb9a79-daff-4c25-b15d-fe5d10da68bf)

![image](https://github.com/dbeaver/dbeaver/assets/9417720/a90a471e-1389-49a1-b991-177af957da1a)

**Comment by E1izabeth** [comment]
SQL Editor is a custom control, because it has lots of features - highlighting, autocompletion, folding, etc.

**Comment by JTMosaic** [comment]
Therefore the results grid is not. If that is the case and there will not be a change to a custom control for the results grid then this is not resolvable easily and this issue can be closed. I accept the explanation.

Thanks for your time, @E1izabeth !

**Comment by flambchap** [comment]
In short, `Search selected text with Google` is our (DBeaver's) custom menu item, and we use the default browser there. `Search with Google` is a Safari service (as explained by [Phillipus](https://github.com/Phillipus) in [the corresponding ticket](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1215)).

Thank you, @JTMosaic, for bringing this up. I've learned a few things about macOS today!

**Comment by arhayka** [comment]
We have discussed this situation with the team, and we cannot fix this behavior. The default browser opens, and that default browser depends on the OS settings. So in this case, it's a macOS-specific issue.
