### ISSUE TITLE
Binary columns cause JSON export to be invalid

### ISSUE THREAD

**Issue by hchargois** [dbeaver/dbeaver#26613]
### Description

A table that contains a binary column causes the JSON generated by the "Export data" feature to be invalid.

For example,

```
{
"select * from t1": [
	{
		"id" : 0x1234
	},
	{
		"id" : 0x5678
	}
]}
```

The export menu offers to choose an "Encoding" for "Binaries", but none of the options produces valid JSON:

* Native: `"id" : 0x1234`
* Binary: `"id" : 4` (including a non-printable character before the "4"!)
* Base64: `"id" : EjQ=`
* Hex: `"id" : 0x1234` (same as Native)

### DBeaver Version

Community Edition 24.0.3.202404222221

### Operating System

Linux

### Database and driver

Database: MySQL (Percona) v8.1.0
Driver: MySQL (I don't see any version number)

### Steps to reproduce

Create a simple table, insert some binary data, select it:

```
create table t1 (
	id varbinary(10)
);

insert into t1 values (0x1234),(0x5678);

select * from t1;
```

Click "Export data", choose "JSON / Export to JSON file(s)"

**Comment by uslss** [comment]
thanks for the bug report

**Comment by E1izabeth** [comment]
We need to cover this case too #34012

**Comment by hchargois** [comment]
Hi, I see that's there's been a PR that tried to fix the bug, thanks. However, just by reading the change in the PR, it was _immediately obvious_ that the fix was very wrong since binary data was still being copied unencoded. To be sure I've built dbeaver from source and indeed, the fix doesn't work.

With the same data and export as the original message in this issue, and using "binary" for the format of the binary columns, this is the generated "JSON", which is still not valid JSON since it contains non-printable characters (in that case `0x12`):

```
00000000: 7b0a 2273 656c 6563 7420 2a20 6672 6f6d  {."select * from
00000010: 2074 3122 3a20 5b0a 097b 0a09 0922 6964   t1": [..{..."id
00000020: 2220 3a20 2212 3422 0a09 7d2c 0a09 7b0a  " : ".4"..},..{.
00000030: 0909 2269 6422 203a 2022 5678 220a 097d  .."id" : "Vx"..}
00000040: 0a5d 7d0a                                .]}.
```

I must say that

1) rolling your own JSON serializer, when it's probably the most popular data exchange format, with myriads of libraries available...
2) failing at it, when JSON is extremely simple and well-defined...
3) letting such obviously wrong PRs go through without scrutiny and without tests...

are _extremely concerning_ especially for an app that's expected to handle data, possibly critical data.

I've now lost all trust in dbeaver and I'm currently looking for a replacement.

**Comment by serge-rider** [comment]
This PR just adds quotes around encoded binary data. There is no single "correct way" to encode binary value in json, it is always app-specific.
In dbeaver you can change binary encoding to base64, hex or raw binary (on the Binary Editor preference page).

What behavior would be the correct one?

**Comment by hchargois** [comment]
At the very least, I expect a JSON exporter to produce JSON.

**Comment by E1izabeth** [comment]
So, have you changed encoding here?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/0003897a-ae27-4650-bd05-2ffad6cbb139)

**Comment by hchargois** [comment]
> have you changed encoding here

Yes, these are the 4 options (Binary, Base64, Hex, Native) that I'm referencing to in my very first post.

As I've shown in my previous post, choosing "Binary" (I've not re-tested others) still doesn't lead to JSON being produced.

I don't understand what's confusing about "I expect a JSON exporter to produce JSON"? Is that unclear, or don't you agree?

**Comment by E1izabeth** [comment]
I get your point. Thank you.
Lets always use Base64 encoding for JSON export.

**Comment by serge-rider** [comment]
It is still controversial.
We can force base64 usage always just ignoring formatting option.
But this is a regression.

Binary format is intended to be plain binary, no additional encoding is needed. It may produce well-formed JSON and it may not. It depends on the data in the table.

In some cases using Binary format is useful because sometimes plain text values are stored in binary columns.
In other cases people use non-standard JSON parser which allows binary characters in quotes.

But generally this option may break final JSON, this is an expected behavior. Binary format should be used only if you are sure what you are doing.

Perhaps, what we need is to improve "Native" formatting. Then, for binary data we could use plain text for valid characters and unicode escape for non-valid characters.

WDYT?

**Comment by hchargois** [comment]
I don't think "producing JSON" from a JSON export should be controversial. Asking for JSON and not getting JSON is absolutely, 100% unexpected and can only be described as a bug, not a feature. If you can't find a way to properly encode binaries with the "Binary" option, then the option should not be provided.

BTW, there are 2 non-control characters that should also be escaped in JSON strings, that currently aren't: `"` and `\`. So even "plain text" can lead to invalid JSON being produced.

As someone has remarked above, JSON doesn't provide an obvious way to represent binary data. The simplest, most standard way would probably be to represent it as an array of numbers in the 0-255 range. But that doesn't help if you want to have printable characters represent themselves.

JSON strings are supposed to represent Unicode data. Luckily all the code points from 0 to 255 are valid (and are non-combining, I think), so it would be valid to encode binaries as if they were a string of Unicode code points from 0 to 255. As per JSON string escaping rules, printable characters would be represented by themselves (except for `\` and `"` which would be escaped by a `\`), and control characters could be escaped with the `\u00xx` sequence.

**Comment by Code-Divine** [comment]
Thank you for fixing this. Thank you so much.
