### ISSUE TITLE
Export JSON resultset with column names equals aliases

### ISSUE THREAD

**Issue by filipemanuelofs** [dbeaver/dbeaver#2662]
```
SELECT AB.FIRSTATT AS "thisIsMyFirstAttribute"
    ,AB.SECONDATT AS "thisIsMySecondAttribute"
    ,AB.THIRDATT AS "thisIsMyThirdAttribute"
FROM ABC.TABLE_ATT AB
```
![first](https://user-images.githubusercontent.com/1047292/34162278-4e2034ac-e4ba-11e7-8880-5bb91aac9bba.PNG)

After click "Export Resultset..." and select JSON

`
[
	{
		"FIRSTATT" : 55,
		"SECONDATT" : 0,
		"THIRDATT" : "274607"
	},
	{
		"FIRSTATT" : 118,
		"SECONDATT" : 0,
		"THIRDATT" : "62782"
	},
	{
		"FIRSTATT" : 369,
		"SECONDATT" : 0,
		"THIRDATT" : "288650697"
	}
]	
`

Table names are generated with capitalized title, not with aliases.

**Comment by serge-rider** [comment]
What is your database?

**Comment by filipemanuelofs** [comment]
DB2 LUW

**Comment by beonit** [comment]
This issue resolved
https://github.com/dbeaver/dbeaver/commit/2a1bb6c27c2cb93f7a0dd15fb3b70d66be98f09d

**Comment by tati-kru** [comment]
Thank you @beonit
