### ISSUE TITLE
Change query execution time [N rows fetched - Xs (Ys fetch)] to optionally force showing in millisecond timescale

### ISSUE THREAD

**Issue by CrimsonVex** [dbeaver/dbeaver#26658]
**Problem:**
Query execution time (bottom right of the UI) is reported in varying timescales. For short-running queries (e.g. 2-3 seconds), it will only display in integer seconds (won't show milliseconds). It's difficult to distinguish small query performance improvements (2100ms vs 2900ms) because milliseconds aren't shown for query execution times >1 second.

**Solution:**
Option to force the displayed query execution time to show in milliseconds. I understand forcing display of milliseconds would be futile for query times of more than ~15 seconds, but the option would be nice.

**Current workaround:**
Adding manual PRINT statements to the SQL code to measure the query time manually

**Community support:**
Support for this feature noted in [this discussion thread](https://github.com/orgs/dbeaver/discussions/22632).

**Comment by E1izabeth** [comment]
Thank you for sharing your use case. Have you tried using Query Manager?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/e4ca0ec8-863a-46f7-9712-4c8965913fe9)

You can open it here 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/64e98d58-019b-4755-a2ef-eeed5a64c51e)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
