### ISSUE TITLE
Querying Solr 

### ISSUE THREAD

**Issue by rltheis27** [dbeaver/dbeaver#2666]
Hello,
  First off:
              DBeaver Version:  4.3.0 CE
              Desktop OS: Windows 7
              Solr device driver:  Driver included with DBeaver

  I finally established a connection with my Solr environment. I tried using port number 9983 and received zookeeper timeout messages. I changed the port number to 2181 (default clientPort number--got from the zoo.cfg file).

  I'm trying to query my solr collection. I have tried (plus a few other combinations):
                  select?indent=on&q=*:*&wt=json
                  qt=select&indent=on&q=*:*&wt=json

I receive this message:
                   Query Execution failed

                    Reason
                    SQL Error: java.io.IOException: java.io.IOException: Slices not found for [collection]

What is the syntax for querying Solr? Are the query features/functions available on the Solr's Web UI available with DBearver?

Thank you for your help and time,
  Richard

**Comment by serge-rider** [comment]
It works similarly to other Solr JDBC clients (e.g. https://lucene.apache.org/solr/guide/6_6/solr-jdbc-squirrel-sql.html#querying )
