### ISSUE TITLE
.project and .settings hidden in Eclipse Plugin

### ISSUE THREAD

**Issue by uqpik** [dbeaver/dbeaver#26708]
### Description

Because of https://github.com/dbeaver/dbeaver/pull/20846 .project and .settings resources are hidden in all Projects, including Java Projects, when using the DBeaver Plugin for Eclipse.

This results in the following behavior:
- Create a new Generic Project
- .project/.settings visible in Project Explorer
- Restart Eclipse
- .project/.settings no longer visible

This also causes the problem, that, when project properties are changed, they are not immediately recognized by EGit (as .project/.settings are hidden) until Eclipse is restarted.

A preferences switch to hide this files could solve the issue.

### DBeaver Version

Community Edition 24.0.3

### Operating System

Windows 10

**Comment by E1izabeth** [comment]
Please clarify the steps to reproduce the issue. What is Generic project? Which eclipse should I use to find this Generic project?

**Comment by uqpik** [comment]
Sorry, i meant General project. However it occurs on other projects types too. Using Eclipse 2024-03 (package Eclipse IDE for Enterprise Java and Web Developers).
As an alternative to #20846 a filter may fullfill the requirement to hide the .* files, like the one within the Project Explorer:
<img width="403" alt="image" src="https://github.com/dbeaver/dbeaver/assets/2535938/e85102c6-5d7f-48e1-bb5d-f5d54e53684f">
It can be found within the Project Explorer menu "Filters and Customization..."

**Comment by E1izabeth** [comment]
Thank you. I reproduced the issue.

**Comment by uqpik** [comment]
Thank you
