### ISSUE TITLE
Create fk working incorrect

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#26711]
### Description

there is no way to select a unique key for the connection.

In versions 23* it worked

### DBeaver Version

community edition 24.0.3

### Operating System

windows 11 64bit

### Database and driver

Postrgresql 14

### Steps to reproduce

1.create table with pk and unique index
CREATE TABLE public.newtable_1 (
	c int4 NOT NULL,
	c2 varchar NOT NULL,
	CONSTRAINT newtable_1_pk PRIMARY KEY (c)
);
CREATE UNIQUE INDEX newtable_1_c2_idx ON public.newtable_1 USING btree (c2);

2.create table2
CREATE TABLE public.newtable_2 (
	ff varchar NULL
);

try to create a foreign key on a table using a unique index.

![image](https://github.com/dbeaver/dbeaver/assets/61137576/8db3ebda-71be-4f67-ae2e-ea73ed37c93c)

There is no option to select a unique index for a connection

**Comment by JoelHz** [comment]
SQLITE foreign key behavior is not working as well 

Step to reproduce :
1.
-- Definition of Table : paramet 
-- tabla de parámetros 
DROP TABLE IF EXISTS paramet ; 
CREATE TABLE IF NOT EXISTS paramet ( 
clavpar INTEGER NOT NULL , --id de la tabla de parámetros  
tipopar TEXT  , 
titupar TEXT  , --Titulo del tipo de parametro 
descpar TEXT  , --descripción del parámetro 
valopar TEXT  , --valor del parámetro 
pborpar TEXT  , --Propiedad de que el elemento pueda borrarse 
notapar TEXT  , --notas de la tabla de parámetros  
etiqpar TEXT  , --etiqueta del parámetro, ejemplo  #ligero, separados por el símbolo ;  ejemplo #desayunorapido;#siempreenmesa 
comepar TEXT  , --comentario del parámetro  
vigepar TEXT  , --estado del parámetro OK (esta vigente) o real para indicar el día de borrado  
tradpar TEXT  , --Este parametro es traducible 
CONSTRAINT paramet_pk PRIMARY KEY (clavpar)
); 


2.
-- Definition of Table : paracls 
-- Tabla de la clasificación de artículos 
DROP TABLE IF EXISTS paracls ; 
CREATE TABLE IF NOT EXISTS paracls ( 
clavcls INTEGER NOT NULL , --Clasificación de los artículos en alimentos, complementos o mixtos 
CONSTRAINT paracls_pk PRIMARY KEY (clavcls)
, CONSTRAINT fk_paracls_0 
  FOREIGN KEY (clavcls) 
  REFERENCES paramet(clavpar) 
 ON DELETE CASCADE 
 ON UPDATE CASCADE
); 


3.
INSERT INTO paramet (clavpar, tipopar, titupar, descpar, valopar, pborpar, notapar, etiqpar, comepar, vigepar, tradpar) VALUES (0, 'CLS', 'CLASE DE ARTICULO', 'CLASE DE ARTICULO', 'Alimento', 'N', 'NoMostrar', '-', 'NoMostrar', 'OK', 'S');
INSERT INTO paramet (clavpar, tipopar, titupar, descpar, valopar, pborpar, notapar, etiqpar, comepar, vigepar, tradpar) VALUES (0, 'CLS', 'CLASE DE ARTICULO', 'CLASE DE ARTICULO', 'Complemento', 'N', 'NoMostrar', '-', 'NoMostrar', 'OK', 'S');
INSERT INTO paramet (clavpar, tipopar, titupar, descpar, valopar, pborpar, notapar, etiqpar, comepar, vigepar, tradpar) VALUES (0, 'CLS', 'CLASE DE ARTICULO', 'CLASE DE ARTICULO', 'Mixto', 'N', 'NoMostrar', '-', 'NoMostrar', 'OK', 'S');

I have a query to update sequentially field clavpar but table paracls holds a 0 no matter what, even if I change it manually

**Comment by serge-rider** [comment]
- Indexes returned to unique constraint list
- Proper data type is set when create new column for new FK

**Comment by kseniaguzeeva** [comment]
The first described issue is verified.
