### ISSUE TITLE
Can't be run in eclipse

### ISSUE THREAD

**Issue by Hackeruncle** [dbeaver/dbeaver#2671]
dbeaver code：4.3.0
eclipse version：4.7.2
I have already installed  a few additional Eclipse plugins which DBeaver depends on.
I reference with [Develop-in-Eclipse](https://github.com/serge-rider/dbeaver/wiki/Develop-in-Eclipse).

**I check with error log:**
!MESSAGE Product org.jkiss.dbeaver.core.application.product could not be found.
java.lang.RuntimeException: No application id has been found.

![1 plug-ins](https://user-images.githubusercontent.com/20901151/34252353-312a9d18-e67e-11e7-869f-51a2587f2c18.png)
![2 main](https://user-images.githubusercontent.com/20901151/34252351-30b06372-e67e-11e7-8ce8-329df1095d77.png)
![3 error](https://user-images.githubusercontent.com/20901151/34252352-30f28680-e67e-11e7-8a12-2b5dc92103bd.png)

**ERROR Detail Log:**
`!SESSION 2017-12-21 16:04:13.151 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Framework arguments:  -product org.jkiss.dbeaver.core.application.product
Command-line arguments:  -product org.jkiss.dbeaver.core.application.product -data C:\Users\wujipeng\eclipse-workspace/../runtime-DBeaver.product -dev file:C:/Users/wujipeng/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/DBeaver.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

!ENTRY org.eclipse.equinox.app 0 0 2017-12-21 16:04:19.740
**!MESSAGE Product org.jkiss.dbeaver.core.application.product could not be found.**

!ENTRY org.eclipse.osgi 4 0 2017-12-21 16:04:19.927
!MESSAGE Application error
!STACK 1
**java.lang.RuntimeException: No application id has been found.**
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:242)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)`

**Comment by Hackeruncle** [comment]
@serge-rider  I need you help.

**Comment by ruspl-afed** [comment]
Please check that you have "org.jkiss.dbeaver.core.application" bundle available and selected in your workspace
"Warning" decoration for the product id fild means it cannot be found

**Comment by serge-rider** [comment]
@Hackeruncle did you try this:

> If product won't start with No application id has been found error try this workaround:
> https://stackoverflow.com/questions/13575695/eclipse-rcp-no-application-id-has-been-found

> What you need to do is go to your Run Configurations (Run -> Run Configurations). Select the Plug-ins tab and then hit "Add Required Plug-ins". Apply, then Run, and it should work now.
> That's it.
```

**Comment by Hackeruncle** [comment]
@ruspl-afed Thanks.

How to let "org.jkiss.dbeaver.core.application" bundle available , press Ctrl+B to build?

**Comment by Hackeruncle** [comment]
1. Download the dbeaver-4.3.0 code in linux , use "mvn clean package";

2. Shell:  zip -r dbeaver-4.3.0.zip dbeaver-4.3.0/* ;

3.Upload dbeaver-4.3.0.zip to window, and unzip;

4.Download eclipse from [eclipse-packages](http://www.eclipse.org/downloads/eclipse-packages/);
![4.download eclipse](https://user-images.githubusercontent.com/20901151/34292779-1f1e6a04-e73d-11e7-96c6-2461fe61802d.png)

5.Open eclipse:
Open main menu **Help** -> **Install New Software**
Select "--All Available Sites--"  and press enter 
Input “plug” and Select Plug-in and Install.

6.Open eclipse:
Open main menu **Help** -> **Install New Software**
Copy http://dbeaver.jkiss.org/eclipse-repo/ into "Work with" field and press enter 
Check all plugins and finish the installation process
![2 install some plugins](https://user-images.githubusercontent.com/20901151/34292965-c9d529d8-e73d-11e7-9270-dbe93252e360.png)

7.Import-->Existing Maven Projects-->Select the unzip dbeaver-4.3.0 dir -->Finsh

8.eclipse will auto install some plugs and restart eclipse.

9.To run the standalone version find file DBeaver.product (it is located in product/standalone directory). 
 Click mouse right button and select Run Configurations (Run -> Run Configurations). 
 Select the Plug-ins tab and then hit "Add Required Plug-ins". Apply, then Run, and it should work now.

**Comment by serge-rider** [comment]
Thanks for info.

Important note: you need `Eclipse for RCP and RAP developers`. Eclipse for Java developers is not enough to build/run DBeaver. That's why you had to install extra plugins maually.

**Comment by Hackeruncle** [comment]
I close this issue.
