### ISSUE TITLE
Mongodb listCollections requires authentication error 13

### ISSUE THREAD

**Issue by mdeniz63** [dbeaver/dbeaver#26722]
### Description

hello when i try to open Collections from dbeaver gui for mongodb i get error like below;

Command failed with error 13 (Unauthorized): 'command listCollections requires authentication' on server 172.16.2.63:27017. The full response is {"ok": 0.0, "errmsg": "command listCollections requires authentication", "code": 13, "codeName": "Unauthorized"}

### DBeaver Version

DBeaver EE

### Operating System

Windows 11

### Database and driver

Mongodb Default Driver

**Comment by E1izabeth** [comment]
Could you try performing `Test connection` operation? Is it successful?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/4b2bdef8-669a-42f1-ac55-6d8ac94d7339)

**Comment by mdeniz63** [comment]
![MongoDBError](https://github.com/dbeaver/dbeaver/assets/28572223/a824badd-a594-4784-9f7c-9d496d738cd6)

Test Connection is ok. When I click collection not opening as seen at picture

**Comment by LonwoLonwo** [comment]
Hello @mdeniz63 

It looks like it is better to report to our PRO users technical report team https://dbeaver.com/tickets

**Comment by mdeniz63** [comment]
I can't because i dont have licence id for open technical support ticket.
it give this warning;
"We provide technical support for DBeaver customers only. Please, enter your valid License ID or create a ticket in our [GitHub issue tracker.](https://github.com/dbeaver/dbeaver/issues/new/choose)"

**Comment by flambchap** [comment]
Hi @mdeniz63. Can you please take a screenshot of the Connection settings dialog and post it here? Thank you.

**Comment by mdeniz63** [comment]
Connection Test is OK no problem about connection.

Problem is about open Collections at gui

![image](https://github.com/dbeaver/dbeaver/assets/28572223/9903818d-94c0-42af-b2e0-9375b71232a3)

**Comment by E1izabeth** [comment]
Have you specified `readWrite` role to the user?
https://www.mongodb.com/docs/manual/reference/built-in-roles/#mongodb-authrole-readWrite

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
