### ISSUE TITLE
How to specify "show system objects" property from command line

### ISSUE THREAD

**Issue by Samwiseuk** [dbeaver/dbeaver#2673]
Hi,

Hopefully a quick question.  I can launch DBeaver from a Windows Command Prompt to directly connect to a MySQL database by using the following:

`dbeaver.exe -con "name=My db server|driver=mysql|url=jdbc:mysql://127.0.0.1:3306/oozie?user=root&password=mypassword"`

However, I would also like to enable the "show system objects" checkbox, which is found on the General page of the Edit Connections dialog, from this command line.  I thought I should be able to do this using the show-system-objects property, but despite several attempts I have been unable to get this to work (so that it shows the built-in databases e.g. mysql).

Is there a way of getting this property to work from the command line?

Thanks.

**Comment by serge-rider** [comment]
No, it is not yet supported. Mark as FR.

**Comment by Samwiseuk** [comment]
Ahh, just to add to the reasoning behind my request ... I have created some entries in KeePass that allow me to automatically load DBeaver and connect to a MySQL database, even through a SOCKS proxy.  This means that I can securely store my usernames, passwords and connection information within a secure KeePass database, along with all my other credentials.

This is great, but it does require that any additional connection configuration needs to be available as a command line parameter.  In this particular case, I'd like to be able to see the system objects from launch but, obviously, it's applicable to any of the other connection configuration options.

Would be great, if this were supported in future.  Thanks.

**Comment by uslss** [comment]
already implemented
https://github.com/dbeaver/dbeaver/wiki/Command-Line

**Comment by serajhqi** [comment]
Database > Driver Manager > MS SQL SERVER > SQL SERVER > Edit > Driver Properties

Add `showSystemObjects=true` to User Properties values:
