### ISSUE TITLE
Can't create DB on MSSQL 2017 

### ISSUE THREAD

**Issue by ggoelles** [dbeaver/dbeaver#2674]
With version 4.3.0 on Linux I'm getting this error, when I try to create a new DB on a MSSQL2017 .

--> Object manager not found for type 'org.jkiss.dbeaver.ext.generic.model.GenericCatalog'

**Comment by serge-rider** [comment]
Database create not yet supported for SQL Server (will be added as a part of #810).

In fact menu item "Create new database" shouldn't be there. This is a bug in UI, thanks for report.
