### ISSUE TITLE
New constraint: loose field number on uncheck

### ISSUE THREAD

**Issue by sirber** [dbeaver/dbeaver#2676]
![image](https://user-images.githubusercontent.com/3911428/34271037-9c09940c-e658-11e7-87b5-9c041b3ebace.png)

**Comment by sirber** [comment]
The number 4 will show if check the line again.

I would rate this bug as highly critical ;)

**Comment by sirber** [comment]
might be related...

![image](https://user-images.githubusercontent.com/3911428/34276300-c9bcf112-e66e-11e7-9bbd-8594f7713e2e.png)

I'm on Windows 10.

**Comment by serge-rider** [comment]
Thanks for report, it is a glitch in column selector dialog.

Second screenshot isn't related (and seems to be another bug). Could you create separate ticket for that?

**Comment by sirber** [comment]
Alright! Thank you!
