### ISSUE TITLE
Redis Data Fetching Error in DBeaver Enterprise 4.3.0

### ISSUE THREAD

**Issue by BBQyuki** [dbeaver/dbeaver#2677]
I got a NullPointerException when I double click an entry in key list. Here is the error log:
![screen shot 2017-12-22 at 20 25 13](https://user-images.githubusercontent.com/6779063/34297977-3b758f48-e756-11e7-9450-71693c3f65d9.png)
The Redis itself works fine since I can connect to and fetch data from it with another Redis client.
The NPE also occurs when I try to refresh the content under Data tab.
Any thoughts about this exception? Thanks.

**Comment by serge-rider** [comment]
Will be fixed in 5.0. Also you can check fix in EA version (https://dbeaver.com/files/ea/)
