### ISSUE TITLE
Auto-Commit Produces [Teradata Database] [TeraJDBC 20.00.00.16] [Error 3932] [SQLState 25000] Only an ET or null statement is legal after a DDL Statement.

### ISSUE THREAD

**Issue by dgw-teradata** [dbeaver/dbeaver#26772]
### Description

In Auto-Commit mode this error occurs.
SQL Error [3932] [25000]: [Teradata Database] [TeraJDBC 20.00.00.16] [Error 3932] [SQLState 25000] Only an ET or null statement is legal after a DDL Statement.

This was working in Community Edition 24.0.2

### DBeaver Version

Community Edition 24.0.3

### Operating System

macOS Sonoma

### Database and driver

Teradata Database 16.20.22.01
com.teradata.jdbc.TeraDriver 20.00.00.16

### Steps to reproduce

CREATE SET TABLE EMPLOYEE,FALLBACK ( 
   EmployeeNo INTEGER, 
   FirstName VARCHAR(30), 
   LastName VARCHAR(30), 
   DOB DATE FORMAT 'YYYY-MM-DD', 
   JoinedDate DATE FORMAT 'YYYY-MM-DD', 
   DepartmentNo BYTEINT 
) 
UNIQUE PRIMARY INDEX ( EmployeeNo );

INSERT INTO Employee (
   EmployeeNo, 
   FirstName, 
   LastName, 
   BirthDate, 
   JoinedDate, 
   DepartmentNo 
)
VALUES ( 
   101, 
   'Mike', 
   'James', 
   '1980-01-05', 
   '2005-03-27', 
   01
);

COLLECT STATS ON
EMPLOYEE INDEX (EmployeeNo);

**Comment by E1izabeth** [comment]
Thank you for report.
Could you try switching `Blank line is statement delimiter` setting to `Always`? Does it help?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/be8457a0-d62c-4acb-ac2f-67ce518cf3f5)

**Comment by dgw-teradata** [comment]
Hi Elizabeth, yes that worked! Thank you for your quick response.

**Comment by E1izabeth** [comment]
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.
