### ISSUE TITLE
Issue with connection to the Postgres on the docker container from master host

### ISSUE THREAD

**Issue by iuaacvs** [dbeaver/dbeaver#26800]
### Description

Suddently I can't connect to the PG from the DBeaver. Couple of days ago everything worked fine.
In the same time PgAdmin and SQL Manager for PostgreSQL connect with no problem.

### DBeaver Version

Community Edition Version 24.0.3.202404211624

### Operating System

Windows 11

### Database and driver

PostgreSQL 13.x on the docker container
postgresql-42.7.3.jar
![connect_issue2PG](https://github.com/dbeaver/dbeaver/assets/115172336/0c6b2786-c673-4b33-b683-039db118609c)
![connection_details](https://github.com/dbeaver/dbeaver/assets/115172336/85877d79-177b-46fa-81ea-9ecb7cb55785)

**Comment by E1izabeth** [comment]
Have you upgraded DBeaver before it stoped working?

**Comment by iuaacvs** [comment]
I think so. But I have tried to rollback to previous versions. They don't work either.

**Comment by iuaacvs** [comment]
I've found out the workaround. I've set the IP of the Ethernet adapter vEthernet (WSL (Hyper-V firewall))
![image](https://github.com/dbeaver/dbeaver/assets/115172336/34c92818-31bb-4d13-ba57-09bd6eeae414)

After that I've successfully connected. However, it's very strange.

**Comment by serjiokov** [comment]
Looks like a third-party issue depending on your virtual Hyper-V settings.
