### ISSUE TITLE
Bad column names in constraints

### ISSUE THREAD

**Issue by sirber** [dbeaver/dbeaver#2681]
![image](https://user-images.githubusercontent.com/3911428/34276300-c9bcf112-e66e-11e7-9bbd-8594f7713e2e.png)

from #2676

**Comment by serge-rider** [comment]
How to reproduce this?

**Comment by sirber** [comment]
I have no clue... I played with constraints then I got this.
I cannot seem to be able to reproduce it... :(

**Comment by serge-rider** [comment]
I'll close it as non-reproducible then. Please reopen if any new information will be available.
