### ISSUE TITLE
How to connect to MS SQL Server in "dbeaver"?

### ISSUE THREAD

**Issue by it19862** [dbeaver/dbeaver#2682]
In "Navicat Premium" everything is connected well.
Login and password to enter the database is not required.

How to connect to MS SQL Server in "dbeaver"?
![3029](https://user-images.githubusercontent.com/18245828/34329906-68182b40-e923-11e7-9840-02ce035b9937.jpg)

**Comment by serge-rider** [comment]
Just leave username and password empty. 
Set server name to `localhost`.

**Comment by serge-rider** [comment]
This is with jTDS driver.

**Comment by efradkin** [comment]
@it19862, the Windows Authentication checkbox will be added to the connection page in scope of #2077.
