### ISSUE TITLE
Postgres: Cannot see enum data type content and DDL

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#2683]
When editing a column with custom data type (enum) in a table, I can choose a value from the dropdown list, and when I check the properties of the type, there is no list of values.

**Comment by serge-rider** [comment]
What database?

**Comment by offstate** [comment]
postgresql 9.5

**Comment by serge-rider** [comment]
Thanks for report. Enum values information will be added in data type description in the next version.
