### ISSUE TITLE
DBeaver not opening after Office extention re-install

### ISSUE THREAD

**Issue by SeppBerkner** [dbeaver/dbeaver#26848]
### Description

Because I received an error message `Export to excel fails " Processor 'stream.xlsx' not found in 'Files'` (like in issue #21893) I reinstalled the office package. However, after closing DBeaver and reopening it, I receive a pop-up message that the start of DBeaver fails and that I should look in the logs. They state the following:

```
SESSION 2024-04-26 10:40:25.113 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en
Framework arguments:  -keyring /Users/jbe/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -keyring /Users/jbe/.eclipse_keyring

!ENTRY org.eclipse.osgi 4 0 2024-04-26 10:40:25.725
!MESSAGE An error occurred while automatically activating bundle org.eclipse.ui.workbench (176).
!STACK 0
org.osgi.framework.BundleException: Error starting module. osgi.identity; type="osgi.bundle"; version:Version="3.131.0.v20231201-0512"; osgi.identity="org.eclip$
        at org.eclipse.osgi.container.Module.doStart(Module.java:614)
        at org.eclipse.osgi.container.Module.start(Module.java:468)
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
        at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:500)
```

I am now unable to open DBeaver

### DBeaver Version

Community Edition 23.3.2

### Operating System

macOS Ventura 13.6.1

**Comment by E1izabeth** [comment]
Please, provide full log file
You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by SeppBerkner** [comment]
@E1izabeth Well... I couldn't find any log files in either `workspace/workspace6/.metadata/.log` nor `workspace/workspace6/.metadata/dbeaver-debug.log`. Also no files in `<install-path>/configuration` or 
`${HOME}/.eclipse/org.jkiss.dbeaver.product_<dbeaver-version>` (the hidden folder `.eclipse` doesn't exist it seems). And Java fatal logs I couldn't find as well... 

[EDIT] I could find log files in the two first directories, but they were older.

**Comment by E1izabeth** [comment]
Hmm. OK, thank you

**Comment by SeppBerkner** [comment]
What are my options now? Reinstall? How about all the settings I have once I reinstall DBeaver, are they still kept somewhere (like connections or code style)?

**Comment by E1izabeth** [comment]
Yes, you could try reinstall. All settings will remain. They're stored in the workspace directory.

**Comment by SeppBerkner** [comment]
By reinstalling the bug disappears. Thanks
