### ISSUE TITLE
Execute query going beyond the paragraph the cursor is in.

### ISSUE THREAD

**Issue by GAZ082** [dbeaver/dbeaver#26867]
### Description

Have something like this:

```sql
SELECT
	q.id,
	q.FIRST_YEAR_CONTRACT_VALUE__C,
	q.CURRENCYISOCODE,
	q.CONTRACT_START_DATE__C,
	qq.contract_start_Date,
	q.APPROVALSTATUS__C,
	qqq.OPPORTUNITY_AMENDED_CONTRACT
FROM
	STG_WDMS_REPORTING.SF_SBQQ__QUOTE__C q
LEFT JOIN DM_DIGITAL_MEDIA.contract_dim qq ON q.SBQQ__OPPORTUNITY2__C = qq.CONTRACT_OPPORTUNITY
LEFT JOIN DM_DIGITAL_MEDIA.OPPORTUNITY_DIM qqq ON qqq.OPPORTUNITY_ID = q.SBQQ__OPPORTUNITY2__C
WHERE qqq.OPPORTUNITY_STAGENAME = 'Closed Won'

https://xxx.lightning.force.com/a1APZ000000yulh2AA
```

And when I put the cursor in the main paragraph of the code, it also picks up the URL at the bottom:

![image](https://github.com/dbeaver/dbeaver/assets/100194/fc77fa7d-307e-436b-89bb-5d9c9c88034a)

The commented lines are not picked up.

### DBeaver Version

CE 24.0.3.202404211624

### Operating System

Windows 11

### Database and driver

Snowflake: snowflake_jdbc

![image](https://github.com/dbeaver/dbeaver/assets/100194/f11554f2-f881-450d-b570-a50132cd0f63)

### Steps to reproduce

Just hit CTRL+ENTER in the paragraph of code you want to execute.

**Comment by E1izabeth** [comment]
It's an expected behavior as you don't have a separator at the end of the query. Options are:
- add `--` before the URL
- switch `Blank line is statement delimiter` setting to `Always`
![image](https://github.com/dbeaver/dbeaver/assets/28875055/be8457a0-d62c-4acb-ac2f-67ce518cf3f5)

**Comment by GAZ082** [comment]
Thank you @E1izabeth . But this worked fine before the update to the version I reported. Setting to always worked, but wonder if there was some change in the "Smart" algorithm.

Free free to close this if you want.

**Comment by E1izabeth** [comment]
It's a new mode of statements execution. With this mode DBeaver takes everything between the statement start and the query delimiter or a new statement start

**Comment by E1izabeth** [comment]
So, if it doesn't fit to your use cases, switching this setting to Always returns the previous behavior.

**Comment by E1izabeth** [comment]
The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.

**Comment by drewmie** [comment]
@E1izabeth, has the intended behavior of Smart mode changed in this fix?  Or is it still as you stated here?

> ...DBeaver takes everything between the statement start and the query delimiter or a new statement start

**Comment by E1izabeth** [comment]
@drewmie 
The behavior I described is what this mode do. If it doesn't fit to your use cases, you can switch the mentioned setting.
