### ISSUE TITLE
AUTO INCREMENT MySQL processing issue

### ISSUE THREAD

**Issue by davidlaffan** [dbeaver/dbeaver#26869]
### Description

When adding a new column that AUTO INCREMENTs and then adding it as a key, DBeaver treats it as two commands even though if an AUTO INCREMENT column is introduced in MySQL it must be a key. This means that if using the GUI, there is no way 

### DBeaver Version

24.0.2.202404071654

### Operating System

Debian-based Linux

### Database and driver

MySQL

### Steps to reproduce

In the table's tab, create a column that AUTO INCREMENTS
Go to Constraints and set up a new primary key
Commit the changes
Should get an SQL error saying that only one AUTO INCREMENT column is allowed and it must be a key

**Comment by E1izabeth** [comment]
It's not quite clear, what are you trying to do. Are you creating PK for the column created with AUTO INCREMENT attribute? Are there other columns with AUTO INCREMENT attribute in this table?

Have you tried using the options to create PK automatically, when creating a column?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/3e19e559-66c0-4754-9ff7-6ee1785324fd)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
