### ISSUE TITLE
Wiki documentation does not match ER Diagram Viewer behavior for creating new table

### ISSUE THREAD

**Issue by michael-s-crouch** [dbeaver/dbeaver#26879]
### Description

The project wiki, at https://github.com/dbeaver/dbeaver/wiki/New-Table-Creation , says "From [ER Diagram](https://github.com/dbeaver/dbeaver/wiki/ER-Diagrams): In the Database Navigator, double-click on the database name or table name. In the window that opens, navigate to the ER Diagram tab, right-click on the window, and choose Create New Table. Alternatively, in the Database Navigator, right-click on the database/table name and click View Diagram. In the window that opens, you can right-click and choose Create New Table."

However, these options do not appear on the right-click menu (screenshot attached).
![image](https://github.com/dbeaver/dbeaver/assets/1367392/c4dc8d73-c1b8-4a25-b1e1-d41ed7e9d7bc)

The project wiki should be updated appropriately.

### DBeaver Version

Community Edition 24.0.3

### Operating System

Ubuntu 23.10

### Database and driver

MariaDB.

### Steps to reproduce

In the database navigator, double-click a database name. Navigate to the ER Diagram tab, and right-click within the diagram.

**Comment by LonwoLonwo** [comment]
Hello @michael-s-crouch 

Thanks for noticing.
This menu action is visible only in the Edit mode in the ERD diagram. 
This Edit mode is only available in PRO versions. We need to add this information to our wiki.
