### ISSUE TITLE
SQL Error [102] [42000]: Incorrect syntax near 'go'

### ISSUE THREAD

**Issue by tjcts-meubanks** [dbeaver/dbeaver#26870]
### Description

Prior to the update on 4/22/2024 to Version 24.0.3.202404211624 I was able to run scripts (using the Execute SQL Scripts option) like the attached without incident.  Now when I try to do this I get the error message **SQL Error [102] [42000]: Incorrect syntax near 'go'**.  For this particular file I get that message 3 times when there are 4 go statements.  

I have tried looking at the driver data as suggested in https://github.com/dbeaver/dbeaver/issues/78 but the didn't change the outcome.

I am able to work around this issue at the moment by selecting each block of code for the go statement and running it separately.  That tells me that the issue isn't in the code I have written but in the actual inclusion of the go statement.  Please advise if there is anything I can do to address this issue.
![default](https://github.com/dbeaver/dbeaver/assets/16493862/b5a9e2e1-0712-417a-82b2-ead661226f02)
![delimiterUpdated](https://github.com/dbeaver/dbeaver/assets/16493862/939a161f-853e-4332-878e-45b005752af6)
[r_startData .txt](https://github.com/dbeaver/dbeaver/files/15131323/r_startData.txt)

### DBeaver Version

24.0.3.202404211624

### Operating System

Windows 10 Pro

### Database and driver

SAP ASE jConnect driver 

### Steps to reproduce

1. Connected to my DB which has a schema called common_db and a table called start
2. Opened a new SQL Console
3. Pasted attacked txt text into console
4. Selected all text and use the Execute SQL Scripts option.
3 versions of the error were thrown.

**Comment by E1izabeth** [comment]
Could you try Early Access version https://dbeaver.io/files/ea/ ? It's possible that it has been already fixed.

**Comment by tjcts-meubanks** [comment]
Yes!  The Early Access version worked great.  Thanks!

From: Elizabeth ***@***.***>
Sent: Thursday, May 2, 2024 9:59 AM
To: dbeaver/dbeaver ***@***.***>
Cc: Eubanks, Millisa ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [dbeaver/dbeaver] SQL Error [102] [42000]: Incorrect syntax near 'go' (Issue #26870)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe
________________________________
Could you try Early Access version https://dbeaver.io/files/ea/<https://dbeaver.io/files/ea/> ? It's possible that it has been already fixed.

**Comment by E1izabeth** [comment]
Thank you for checking. I'm closing the issue then
