### ISSUE TITLE
'Read database list' has encountered a problem

### ISSUE THREAD

**Issue by cmdexe** [dbeaver/dbeaver#2689]
Hi team, 
when I'll try to connect to DB2 I'll get the following window
![problem occurred 2017-12-26 09 32 36](https://user-images.githubusercontent.com/1254625/34349099-131eace2-ea20-11e7-87ca-55c0f707a58a.png)
It would be great if you tell me how to disable this.
I use DBeaver version 4.3.1, win10 (x64), DB2 version 11.

**Comment by serge-rider** [comment]
What DB2 server do you use? LUW, z/OS, iSeries?

**Comment by cmdexe** [comment]
The DB2 server runs on z/OS.

**Comment by titou10titou10** [comment]
Hi,
Is it possible that you created your session with the wrong kind of database?
It seems you used "DB2 LUW" instead of "DB2 z/OS" as the connection type?
Denis

**Comment by cmdexe** [comment]
Hi Denis
I have already solved my problem. It was in wrong kind of database. Thank you very much for the help guys. Sorry for wasting your time.
