### ISSUE TITLE
Exception when Create New Procedure for PostgreSQL

### ISSUE THREAD

**Issue by liuyuanyuan** [dbeaver/dbeaver#2691]
When I used [Create New Procedure] for PostgreSQL， I execute ctrl+s before enter nothing, then the procedure tree node was added, no error prompted.
But when I refresh its parent node , the new added node disappared.
It seems a bug, please have a look. Thanks~
![image](https://user-images.githubusercontent.com/5370221/34353197-ba845e1e-ea61-11e7-8dbd-e7f1dfc0d342.png)

**Comment by serge-rider** [comment]
Thanks for noticing!
