### ISSUE TITLE
SQL Scripts with Creating Stored Procedures

### ISSUE THREAD

**Issue by amivanovano** [dbeaver/dbeaver#2692]
Is it possible execute SQL block 

CREATE PROCEDURE ... ;
...... ;
...... ;
END PROCEDURE 

as single statement without changing Delimiters in Preferences ?

TIA

**Comment by serge-rider** [comment]
Yes, it is possible.
This actually depends on database (e.g. for MySQL and PostgreSQL it usually works).
Universal approach - select the query and execute with <kbd>CTRL+Enter</kbd>

**Comment by amivanovano** [comment]
CTRL+Enter execute SQL statements from previous delimiter to next for me.
I use semicolon as delimiter for SQL statements.
If cursor is in PROCEDURE block, when current line in block will be executed 
( semicolon is native delimiter for my Informix database )
It's not I needed. 
( I want to сreate procedure, of course and execute all stetements before and after PROCEDURE block ).

**Comment by serge-rider** [comment]
If you have a selection then CTRL+Anter executes only selected text.

**Comment by amivanovano** [comment]
Thanks, Serge.
That's exactly what I wanted.

**Comment by amivanovano** [comment]
No, I haven't.

**Comment by tati-kru** [comment]
Thank you @amivanovano
