### ISSUE TITLE
MySQL begin; ... rollback; stopped working in 24.0.3

### ISSUE THREAD

**Issue by Zaught** [dbeaver/dbeaver#26943]
### Description

In 24.0.2 with MySQL, i could run

begin;
update table
set id = 10
where id = 1;
rollback;

to test a query. It no longer works in 24.0.3

### DBeaver Version

24.03

### Operating System

MacOS Ventura 13.6.5

### Database and driver

Driver for MySQL 8 and later

### Steps to reproduce

In 24.0.2 with MySQL, i could run

begin;
update table
set id = 10
where id = 1;
rollback;

to test a query. It no longer works in 24.0.3

**Comment by E1izabeth** [comment]
Please try Early Access version with fix https://dbeaver.io/files/ea/

**Comment by Zaught** [comment]
Thank You. Looks like it is fixed in 24.0.4

**Comment by E1izabeth** [comment]
Thank you for checking
