### ISSUE TITLE
How to hide tables?

### ISSUE THREAD

**Issue by it19862** [dbeaver/dbeaver#2694]
I created an empty database.
And it was created with tables.

How to hide tables?
![3032](https://user-images.githubusercontent.com/18245828/34362902-8683e40a-ea88-11e7-9f9d-a6b3aeff5ecb.jpg)

**Comment by serge-rider** [comment]
It is not very clear what do you need to do.
If you need to hide something then you can filters (context menu->Filter).
Things in red square are schemas (not tables).

**Comment by it19862** [comment]
@serge-rider 
I'm starting to learn ms sql server.

When I open a database in another program, I see only my tables and nothing superfluous
![3040](https://user-images.githubusercontent.com/18245828/34390427-bc8833f8-eb50-11e7-8924-df8de9ebd818.jpg)


1. Can you tell me what is "db_sessionammin" and other list items highlighted in red?

2. How are the elements of the highlighted in red color hidden?

**Comment by serge-rider** [comment]
These elements are schemas (users). SQL Server has specific users model - maybe a bit too verbose.

Usually your tables reside in schema `dbo` - so you can just expand it and work only with them.

**Comment by it19862** [comment]
Thank you.

Could you help with this question:
["How do I edit the table name and column name? "](https://github.com/dbeaver/dbeaver/issues/2695)

**Comment by serge-rider** [comment]
DBeaver will support SQL Server schemas filtering in the next version (4.3.2).
Table/column rename feature will be added later.
