### ISSUE TITLE
How do I edit the table name and column name?

### ISSUE THREAD

**Issue by it19862** [dbeaver/dbeaver#2695]
How do I edit the table name and column name?
Can I edit (table name and column name) by pressing F2?

**Comment by saurabhg476** [comment]
Both table name and column name can be edited by pressing F2 or by clicking on the rename option in the right click panel.

**Comment by it19862** [comment]
@saurabhg476 

The video shows how I on each element "table name" and "column name" click "F2"
But renaming does not happen.

What am I doing wrong?

video  -   [link](https://youtu.be/x3EH8OFFCZ0)

**Comment by serge-rider** [comment]
Rename isn't support for SQL Server databases.
See #810

**Comment by iambudi** [comment]
Renaming and Changing Data type for SQLite seems does not support too?

**Comment by kseniiaguzeeva** [comment]
You are right. Please reopen the ticket if you have any other questions on this theme.
