### ISSUE TITLE
Why do not you see the fields on the diagram?

### ISSUE THREAD

**Issue by it19862** [dbeaver/dbeaver#2698]
Why do not you see the fields on the diagram?
![3034](https://user-images.githubusercontent.com/18245828/34376890-5df19af6-eaff-11e7-899e-0605d49f4956.jpg)

**Comment by serge-rider** [comment]
Right click anywhere on diagram:
![image](https://user-images.githubusercontent.com/6398845/34430580-93f724c6-ec77-11e7-9e53-a2a2fcb48e69.png)

**Comment by tati-kru** [comment]
hi @it19862 
Was a suggested solution useful?
