### ISSUE TITLE
How to package into the installation package

### ISSUE THREAD

**Issue by zhenglincheng** [dbeaver/dbeaver#2703]
How to package into the installation package ？

**Comment by serge-rider** [comment]
Please clarify. 
Why do you need this?

**Comment by zhenglincheng** [comment]
I need to customize some functions for our company.  like snippets . To increase productivity.

**Comment by ruspl-afed** [comment]
You are welcome to contribute it to the DBeaver Community Edition and then get it with the regular update.

**Comment by serge-rider** [comment]
@zhenglincheng product packaging artifacts aren't public domain. If you need some commercial development - please write on serge@dbeaver.com
