### ISSUE TITLE
Allow quick filter in new schema lookup window in 4.3.0

### ISSUE THREAD

**Issue by xantari** [dbeaver/dbeaver#2704]
In the past the scheme lookup drop down as indicated in red circle here would be a drop down list.

![image](https://user-images.githubusercontent.com/6610039/34419393-3e8639b8-ebc9-11e7-9d38-9ddcc49960ce.png)

Now it pops up as this:

![image](https://user-images.githubusercontent.com/6610039/34419399-4caf32ec-ebc9-11e7-9c36-1cd74d93a565.png)

What I would like is the search filter like this window available on the above schema filter window:

![image](https://user-images.githubusercontent.com/6610039/34419430-79d01372-ebc9-11e7-816f-a2804836ef23.png)

**Comment by serge-rider** [comment]
Agreed, that'd be handy.
But it'll have a bit different UI.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/34463464-e3f37c16-ee6d-11e7-914e-cdc80fc984e9.png)
