### ISSUE TITLE
No restore for table of PostgreSQL

### ISSUE THREAD

**Issue by liuyuanyuan** [dbeaver/dbeaver#2707]
I found DBeaver 4.3.1 didn't provide restore for table of PostgreSQL.
PostgreSQL pg_restore could support table level restore, will DBeaver add this feature?

**Comment by serge-rider** [comment]
It is quite complicated to extract possible table names from a dump file. So generally it will be just a text widget where user can enter any names.
I think it would be better to allows user to specify any additional command line parameters to pg_dump/pg_restore.
Like this:
![image](https://user-images.githubusercontent.com/6398845/34495034-631ca502-f004-11e7-8d48-f2841eadd709.png)

**Comment by serge-rider** [comment]
So, if you want to restore just a few table you can use extra parameters like this:
`--table=Table1 --table=Table2 ...`
