### ISSUE TITLE
Connections' context menu needs improvements

### ISSUE THREAD

**Issue by Wirone** [dbeaver/dbeaver#2709]
As of 4.3.1 (but also in 4.2.6 and before) there are 2 things I find not intuitive:
- When using Postgres, "Create New Database" can be found in context menu for... other database inside connection, not for connection itself (and it doesn't make sense since you create database within connection, not inside other database). On the other hand, creating new database for MySQL connection is intuitive since there is "Databases" node and context menu for that node allows creating new database.
- "Creating New Connection" can be found in any connections' context menu and it does not make sense too. There is "New Connection" button at the top of the "Database Navigator" view, also there is item in context menu when clicking on the view's background (not connection) and it's all user needs. When user right-clicks on connection, menu should represent connection's context and creating connection from other connection is, in my opinion, out of that context.

I hope this is clear enough :smile:

**Comment by uslss** [comment]
behaviour of the Create menu is changed.
Seems that ticket is obsolete
