### ISSUE TITLE
Use of Connection General Filters for Schemas/Users broken with version 4.3.1

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2712]
DBeaver - **Version 4.3.1 CE**
DBeaver JDBC driver: **Microsoft**
Operating System: **Windows 7** / **Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

The use of Connection filters for Schemas/Users seems to have been broken with DBeaver version 4.3.1.

**Neither Include nor Exclude filtering works any more.**

**PS**. Unsure if it misbehaves for other drivers than "Microsoft JDBC".

**Comment by danhanly** [comment]
Did you find a solution for this?

**Comment by serge-rider** [comment]
It is a bug in 4.3.1. 
Thanks for report.
