### ISSUE TITLE
no need dependences for openjdk-8-jre-headless and ca-certificates-java, since I have installed oracle-java8.

### ISSUE THREAD

**Issue by zymint** [dbeaver/dbeaver#2714]
I try to install  dbeaver-ce_4.3.1_amd64.deb on my mint 18.3
but it request dependences for openjdk-8-*...
However, I've intalled oracle-jdk-8 (java environment configured) and purge remove openjdk-8-* before.
I don't want to install openjdk one more time, that's the question.
...
at last, using a dbeaver-*.tar.gz might be a good idea.

**Comment by serge-rider** [comment]
Good point.

**Comment by serge-rider** [comment]
However I'm still not sure about correct resolution.
Currently we have `openjdk-8-jre-headless | java-runtime-headless` in deb dependencies.
I can turn it into `openjdk-8-jre-headless | java-runtime-headless | java8-runtime | oracle-java8` but this doesn't look well. 
Everything I read about dependencies on ANY Java vendor says - "don't do this"..
