### ISSUE TITLE
Escape special character in MySQL breaking highlights on DBeaver EE

### ISSUE THREAD

**Issue by douglaszickuhr** [dbeaver/dbeaver#2716]
I realized that when I am writing a SQL code to concatenate data and I want to escape a character like ' in the result-set, the highlights are being wrongly set, like the following example.

![image](https://user-images.githubusercontent.com/12372536/34484546-3876c1bc-efbd-11e7-9ac0-7e71fdc8e673.png)

It makes really hard to read and understand the code. The correct highlights should be something like that:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/12372536/34484525-1a7e9d60-efbd-11e7-8b6e-1b927bc8bbe7.png">

PS: The result-set is correct. The only issue is the highlight.

**Comment by serge-rider** [comment]
Thanks for report

**Comment by serge-rider** [comment]
BTW what is your database?
Most databases uses two single quote characters for escape.

**Comment by douglaszickuhr** [comment]
It's MySQL. You can do with two single quotes but is not easy to read as with the back slash (in my opinion). Some further information can be found on https://dev.mysql.com/doc/refman/5.7/en/string-literals.html.

Thanks Serge!
BTW. Thanks for DBeaver. It's such a powerful tool. :)
