### ISSUE TITLE
Possible to add "" around all values on exporting resultset?

### ISSUE THREAD

**Issue by lidderupk** [dbeaver/dbeaver#2719]
Hi, 

Is it possible to add quotes around all values and not just headers. Example data:

![image](https://user-images.githubusercontent.com/3187457/34502293-b7cb0fc2-efc7-11e7-987b-6d9b75a54577.png)

Export preferences:

![image](https://user-images.githubusercontent.com/3187457/34502309-c52379b6-efc7-11e7-84fe-6bfd180c8022.png)

Result:
```csv
"AlbumId","Title","ArtistId"
1,For Those About To Rock We Salute You,1
2,Balls to the Wall,2
3,Restless and Wild,2
4,Let There Be Rock,1
5,Big Ones,3
6,Jagged Little Pill,4
7,Facelift,5
8,Warner 25 Anos,6
9,Plays Metallica By Four Cellos,7
10,Audioslave,8
11,Out Of Exile,8
12,BackBeat Soundtrack,9
13,The Best Of Billy Cobham,10
14,Alcohol Fueled Brewtality Live! [Disc 1],11
```
Is it possible to get
```csv
"AlbumId","Title","ArtistId"
"1","For Those About To Rock We Salute You","1"
"2","Balls to the Wall","2"
```

**Comment by beonit** [comment]
@serge-rider Assign this issue to me?

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/34787751-6c00d76a-f649-11e7-8513-7a1c6c4900fe.png)
