### ISSUE TITLE
Error reading signed content: com.github.jsqlparser_1.1.0.jar

### ISSUE THREAD

**Issue by pprossi** [dbeaver/dbeaver#2720]
Hi, im unable to install dbeaver in my eclipse photon installation, also in an fresh installation.

I allways get the folowing error:

> An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
> session context was:(profile=C__Programme_eclipse-photon2_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
> Error reading signed content.
> Exception in opening zip file: C:\Programme\eclipse-photon2\eclipse\plugins\com.github.jsqlparser_1.1.0.jar
> 

The Repositories in my available software sites are: 

- DBeaver CE dependencies - https://dbeaver.jkiss.org/eclipse-repo/
- DBeaver CE Repository - https://dbeaver.jkiss.org/update/latest/
- org.jkiss.dbeaver.ce.office.updateSite - https://dbeaver.jkiss.org/update/office/latest/
- org.jkiss.dbeaver.ce.svg.updateSite - https://dbeaver.jkiss.org/update/svg/latest/

Is this an photon dependend problem?

- Version: Photon Milestone 4 (4.8.0M4)
- Build id: 20171214-1849
- Java: jre1.8.0_91
- os.arch: amd64
- os.name: Windows 7
- os.version: 6.1
- osgi.arch: x86_64

**Comment by ruspl-afed** [comment]
Generally we didn't migrated to Photon yet, but the porblem is not Photon specific, it is Eclipse p2 specific.
There are some workarounds here https://stackoverflow.com/questions/25094583/error-when-try-install-plugin

**Comment by pprossi** [comment]
Yes, seems to work.
I've renamed all artifacts.xml files found in eclipse folder and tried to install.

The Installation worked as expected.
I'm not sure if its safe to keep this new artifact files i've restored all original artifacts.xml files.
After a restart everything seems to be fine.

Thanks for that quick help ;)
