### ISSUE TITLE
Export/Import SQL templates

### ISSUE THREAD

**Issue by diegoqueres** [dbeaver/dbeaver#2722]
Can you add "Templates" to Export function of DBeaver?

**Comment by ruspl-afed** [comment]
Please provide more detailed description

**Comment by diegoqueres** [comment]
DBEaver have Templates tab, to add SQL snippets to code.
DBEaver have Export function on File Menu too.
I suggest add the option to export the templates created on DBEaver on the "Export Wizard" window.

**Comment by uslss** [comment]
already implemented
![image](https://user-images.githubusercontent.com/31996417/109970861-9bacc900-7d06-11eb-9924-9c047dcb2262.png)

**Comment by Augustinas01** [comment]
It exports only one  template at the time, is it possible, to export all templates at once? Thanks.
