### ISSUE TITLE
Error while run cursor on script

### ISSUE THREAD

**Issue by dellasavia** [dbeaver/dbeaver#2723]
I have this code snippet and I trying to run

```
DECLARE @name as VARCHAR(100);

DECLARE my_cursor CURSOR FOR
select top 10 t.name from table t;

OPEN my_cursor;
FETCH NEXT FROM my_cursor INTO @name
WHILE @@FETCH_STATUS = 0
BEGIN	
	print @name	
	FETCH NEXT FROM my_cursor
	INTO @name
END 
CLOSE my_cursor;
DEALLOCATE my_cursor;

```
And i'm faced with this error message:

Must declare the scalar variable "@name".

If I run the same snippet on SQL Server Management Studio, it's run nice...

My Dbeaver version is 4.3.1 (2017-12-25)

Thanks in advance!

**Comment by serge-rider** [comment]
How do you execute this snippet?
Try to select it and execute with <kbd>CTRL+Enter</kbd>

**Comment by dellasavia** [comment]
Thank you, Serge! From this way it is works fine! I was attempting to run with  <kbd>Alt+X</kbd>
