### ISSUE TITLE
Error while installing eclipse plugin

### ISSUE THREAD

**Issue by 66303** [dbeaver/dbeaver#2724]
I am trying to install DBeaver 4.3.0 through Eclipse Marketplace
Eclipse Version: Mars.1 Release (4.5.1)

Error:
```
Unable to read repository at https://dbeaver.jkiss.org/update/latest/content.xml.

sun.security.validator.ValidatorException: PKIX path building failed: 

sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by serge-rider** [comment]
Looks like a known issue with older Java versions.
Please validate that you have Java 8 Update 101 or later.

**Comment by 66303** [comment]
Eclipse is using 

> java.runtime.version=1.8.0_131-b11

**Comment by serge-rider** [comment]
What is your OS and Java vendor?

**Comment by 66303** [comment]
java.specification.vendor=Oracle Corporation
OS: Windows 10, 64bit

**Comment by serge-rider** [comment]
Just tried this on exactly the same OS/Java and Eclipse Mars.2 (just downloaded from eclipse.org - not sure where to get Mars.1). It works just fine.
Is there anything special about your Eclipse installation and/or Java?

**Comment by 66303** [comment]
Nothing specific that I could think of.

**Comment by serge-rider** [comment]
Could you try any other (newer) version of Eclipse?

**Comment by 66303** [comment]
I don't have enough permissions to get and install newer Eclipse.

**Comment by ashleylester** [comment]
I am also having this issue when installing dbeaver from Eclipse marketplace. I'm running Version: Oxygen.3a Release (4.7.3a) on Kubuntu 18.04 (clean install) running Oracle JDK.

```
ash@thinkpad:~$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

Error message is: 
```

Unable to read repository at https://dbeaver.io/update/latest/content.xml.
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

**Comment by serge-rider** [comment]
@ashleylester Thanks for information

**Comment by therealnlee** [comment]
same problem in OS: Windows 10, 64bit / openjdk: jdk-13.0.1
eclipse Version: 2019-09 R (4.13.0)
Build id: 20190917-1200
