### ISSUE TITLE
Default export location for dbeaver

### ISSUE THREAD

**Issue by jheinrich22** [dbeaver/dbeaver#2726]
Hello all,

I am attempting to set up dbeaver with default connections for several users. I am able to redirect the default location of the saved connections with the -data command. 

When the users go to save an export from a query, the location defaults to the C:\users\ directory. Is there any way to redirect that to another location?

**Comment by serge-rider** [comment]
Yes. You can edit this location in file 
${WORKSPACE_PATH}\.metadata\.plugins\org.eclipse.core.runtime\.settings\org.jkiss.dbeaver.core.prefs 
Parameter `dialog.default.folder` is the default path for export output (as well as for some other file operations).

${WORKSPACE_PATH} is the path you specify in -data parameter. `<user-home>/.dbeaver4` by default.

**Comment by jheinrich22** [comment]
So our users will be connecting to a server that has the application installed. We want to redirect all settings, database connections, default paths to a different filesystem. 

That server will be refreshed everyday, so these settings will need to be redirected to preserve them.

**Comment by serge-rider** [comment]
Drivers location can be changed in the same file (`${WORKSPACE_PATH}\.metadata\.plugins\org.eclipse.core.runtime\.settings\org.jkiss.dbeaver.core.prefs`)
parameter `ui.drivers.home`.

In regards to dialog.default.folder - please make sure you patched the correct file (it had to have this option with some other default value). It works fine in all our test configurations.

**Comment by richdevboston** [comment]
I have the same problem as @heinrich22 above with making changes to the file location for data exports.  In the file 

```C:\Users\myname\AppData\Roaming\DBeaverData\workspace6\.metadata\.plugins\org.eclipse.core.runtime\.settings\org.jkiss.dbeaver.core.prefs```

the output directory is set to  'C:\Users\myname'

In the Data Transfer Dialog box the field "Output" has Directory =  'C:\Users\myname', which I change to point to `c:\users\myname\desktop\data_download`.  

Then I close DBeaver, and the next time I open DBeaver, it still points the output directory to the location:  `C:\Users\myname`.   I need this setting to persist between user sessions.

**Comment by richdevboston** [comment]
> Yes. You can edit this location in file
> `${WORKSPACE_PATH}\.metadata\.plugins\org.eclipse.core.runtime\.settings\org.jkiss.dbeaver.core.prefs `
> Parameter `dialog.default.folder` is the default path for export output (as well as for some other file operations).
> 
> ${WORKSPACE_PATH} is the path you specify in -data parameter. `<user-home>/.dbeaver4` by default.

Changing the Data Export Directory no longer works.  The changed setting does not persist across user sessions.
