### ISSUE TITLE
org.eclipse.ui.preferencePages.Startup not found

### ISSUE THREAD

**Issue by tohghua** [dbeaver/dbeaver#2730]
DBEaver 4.3.1 Pref window error message:
![image](https://user-images.githubusercontent.com/12222062/34552635-9911b968-f15d-11e7-938c-95562476933c.png)

**Comment by ruspl-afed** [comment]
There is a platform problem:
org.eclipse.ui.internal.ide.dialogs.IDEWorkspacePreferencePage from org.eclipse.ui.ide bundle has an implicitly depends on 
org.eclipse.ui.internal.ide.application.dialogs.IDEStartupPreferencePage from org.eclipse.ui.ide.application

@serge-rider , should we enable org.eclipse.ui.preferencePages.Startup back?

**Comment by serge-rider** [comment]
@ruspl-afed  @tohghua In fact this prefs page was explicitly removed from CE (see ApplicationWorkbenchAdvisor.EXCLUDE_PREF_PAGES constants). 
Because it is not used by DBeaver itself and it confuses users. We can return them back if you think it makes sense in CE.
