### ISSUE TITLE
Missing Schemas & Users with 4.3.1

### ISSUE THREAD

**Issue by danhanly** [dbeaver/dbeaver#2732]
I have a connection to a Sybase database that uses the jTDS driver. Recently, upon updating to 4.3.1, I'm now unable to see certain users.

If I open the connection, then view our database schema beneath, normally when I open the database schema, I have access to users/roles, then the tables exist as a child of each role. There are certain crucial roles now missing from the list, cutting me off from a large portion of my production database.

A colleague is still running 4.2.6 and the roles and users are visible to him, so I can confirm with absolute certainty that the role still exists.

Whats-more, if I write a query that accesses a table beneath a missing role, the query still works as expected, leading me to believe that the roles I require are simply hidden from the list, but are otherwise still accessible.

**Comment by danhanly** [comment]
![screenshot from 2018-01-04 12-51-33](https://user-images.githubusercontent.com/1150741/34564470-b591d1a4-f14e-11e7-9c69-2ae14f2e883d.png)

I downgraded to version 4.2.6 to take this screenshot to illustrate which roles are missing from the new version. I've blurred some names for privacy, but hopefully this still allows you to see which roles are missing.

**Comment by serge-rider** [comment]
This is a bug in 4.3.1 (see #2633 comments).
Will be fixed in the next version. Thanks for report anyway.
