### ISSUE TITLE
execute sql file encoding issue

### ISSUE THREAD

**Issue by tohghua** [dbeaver/dbeaver#2736]
There are Chinese characters in utf8 sql file:
![image](https://user-images.githubusercontent.com/12222062/34597326-f28b468a-f220-11e7-8956-c67bfb7b1839.png)

When executing, it displays:
![image](https://user-images.githubusercontent.com/12222062/34597346-0ec534d2-f221-11e7-9597-7e25a8da0a4e.png)

That also caused other problem that when executing very long insert statement, it reported error like this:
ERROR 1366 (HY000) at line 5: Incorrect string value: '\xAA\xE5\xAE\x9A\xE4\xB9...' for column 'paper' at row 1

**Comment by uslss** [comment]
cannot reproduce an issue now.
Ticket closed.
If issue is still actual for you - feel free to reopen the ticket
