### ISSUE TITLE
Modify connection: data loss...

### ISSUE THREAD

**Issue by undertherainITA** [dbeaver/dbeaver#2739]
Hi.
By modifying a connection, only Host and Port are present.
The Database, User name and Password fields are empty.
I see the problem in version 4.3.1.
In my opinion is not present for a long time.
Thanks for DBeaver, I could not live without him... ;)
Ciao... ;)

**Comment by serge-rider** [comment]
What is your database?
Some screenshot will be also  helpful.

**Comment by undertherainITA** [comment]
You are right.
I have verified and with Microsoft SQLServer... not problem.
With IBM DB2 yes (please see screenshot).
I use the same driver that I used when the bug was not present, so it does not depend on the driver.
Excuse me if my company use DB2 yet... ;)

![connectionlostdata](https://user-images.githubusercontent.com/15998009/34606355-46a83348-f20f-11e7-9391-a61e501c8060.jpg)

**Comment by serge-rider** [comment]
It is a bug in the last version (4.3.1).
Thanks for report!

**Comment by serge-rider** [comment]
Could you also check the fix in EA version (https://dbeaver.jkiss.org/files/ea/) ? Thanks

**Comment by undertherainITA** [comment]
Yes my friend, now it's perfect.
Also on Friday evening... thanks... ;)
Ciao... ;)
