### ISSUE TITLE
Unable to refresh MySQL tables when in the "Tables" tab in "Edit Database" mode

### ISSUE THREAD

**Issue by rscs** [dbeaver/dbeaver#2740]
If I hit F4/Edit Database on a database, the default tab that opens is "Tables". From here I am unable use F5/Refresh in the "Tables" tab until I first click into the "Information" tab and then back into the "Tables" tab. After I've been in the "Information" tab at least one time, then F5/Refresh on the "Tables" tab works as expected. But if I've never viewed the "Information" tab, F5/Refresh does not work in the "Tables" tab.

I am using DBeaver CE v4.3.1. I've tried this with several different MySQL and MariaDB databases on several different connections and I can reproduce it consistently every time, therefore this appears to be a client-side bug.

**Comment by uslss** [comment]
not reproducible (6.2.5).
ticket closed
