### ISSUE TITLE
Impala SQL dialect - driver and syntax highlighting

### ISSUE THREAD

**Issue by chrisdabel** [dbeaver/dbeaver#2744]
Can you add these Impala SQL keywords to be detected as keywords/sql functions?
This will ensure consistent syntax highlighting when scripting for Impala and/or Hive:

(a). Functions
I would like it if these keywords were colored as the common aggregation functions are, such as sum(), count(), etc.
- group_concat()
- to_date()
- date_add()
- adddate()
- lag()
- lead()
- any other date functions mentioned here:  https://www.cloudera.com/documentation/enterprise/5-8-x/topics/impala_datetime_functions.html

(b). keywords
These are some that could be treated as sql keywords and highlighted/capitalized accordingly (i use the setting to automatically capitalize keywords):
- days
- months
- years
(^ These are used in INTERVAL expressions commonly)
- compute stats

**Comment by serge-rider** [comment]
BTW what Impala driver do you mean? 
Is it Cloudera Impala driver preconfigured in DBeaver?

**Comment by chrisdabel** [comment]
I am using "Cloudera_Impala_JDBC_41_2.5.41", or "2.5.41.1061 GA"

I was not aware there existed a preconfigured Cloudera Impala driver. 
I only saw that DBeaver had driver configuration template as of version 4.2.5
