### ISSUE TITLE
Configure DBeaver for Mac against Vertica

### ISSUE THREAD

**Issue by camsanchez** [dbeaver/dbeaver#2748]
I have recently moved from a Windows to Mac and I am needing to configure the application to cater for our connection to Vertica.

My windows shortcut configuration looks like this:
C:\Windows\System32\cmd.exe /c C:\"Program Files"\DBeaver\dbeaver -vmargs -Djavax.net.debug=ssl -Djavax.net.ssl.trustStore=C:\verticastore -Djavax.net.ssl.trustStorePassword=passw0rd

I need to do something similar to make it work on Mac as it currently tells me that it does not recognise my login details (a problem I experienced before when the above configuration was not set properly).

If you could provide me some details on how I can configure this, that would be much appreciated.

**Comment by serge-rider** [comment]
On MacOS you should do it similarly. E.g. 
`
/Applications/DBeaver.app/Contents/MacOS/dbeaver -vmargs -Djavax.net.debug=ssl -Djavax.net.ssl.trustStore=<path-to-keystore> -Djavax.net.ssl.trustStorePassword=passw0rd
`
path-to-keystore depends on your local configuration.

**Comment by camsanchez** [comment]
Hi Serge

Maybe I am a bit thick, but I can't seem to get it to work. I suspect the biggest issue is trying to get the KeyStore to be properly recognised. I keep bumping in to an issue:

`[Vertica][VJDBC](100024) IOException while communicating with server: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
  [Vertica][VJDBC](100024) IOException while communicating with server: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
    [Vertica][VJDBC](100024) IOException while communicating with server: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
      sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
          unable to find valid certification path to requested target
          unable to find valid certification path to requested target`

Any assistance would be greatly appreciated.
