### ISSUE TITLE
Connection Settings dialog for Microsoft SQL Server do not enable buttons if PORT is empty

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2749]
DBeaver - **Version 4.3.2 CE**
DBeaver JDBC driver: **Microsoft**
Operating System: **Windows 7** / **Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

If I clear the value for **PORT** in dialog **CONNECTION SETTINGS for MS SQL SERVER / Microsoft Driver 2 Connection settings**, the **OK**/**FINISH** and **TEST CONNECTION** button is not enabled.

This worked in version 4.3.1 (with the Microsoft Driver "1" Connection settings).

**NOTE**: The reason I clear the **PORT** value, is that if I use SQL Server Browser to set the socket port, I can not have a value in the **PORT** value. I specify the instance name in the **HOST** entry (something like "localhost\SQLEXPRESS").

**Comment by serge-rider** [comment]
Yep. Thanks for report.
