### ISSUE TITLE
Display of schemas for Microsoft SQL Server is broken in 4.3.2 CE

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2750]
DBeaver - **Version 4.3.2 CE**
DBeaver JDBC driver: **Microsoft Driver 2**
Operating System: **Windows 7** / **Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

Seems something has become broken with version 4.3.2 (with the move to the **Microsoft Driver 2**) when it comes to what schemas are displayed. 

**o** Create a New Connection to the demo database **AdventureWorks2012** using the **Microsoft Driver 2**.
**o** The demo schemas **HumanResources**, **Person**, **Production**, **Purchasing** and **Sales** are not shown.

The above worked in version 4.3.0 with the **Microsoft Driver** JDBC driver.
The above have never worked with the **jTDS Driver** JDBC driver.

**Comment by serge-rider** [comment]
Since 4.3.2 DBeaver filters schemas (shows only non-empty schemas by default). 
You can disable this in connection properties dialog:
![image](https://user-images.githubusercontent.com/6398845/34672877-3c3f85d0-f491-11e7-858c-b289d9f57af0.png)

**Comment by jest** [comment]
The same happened to me. Switching to new MSSQL connection provider causes custom schema to disappear.

In 4.3.1 my hand-created `opti` schema is shown. In 4.3.2 it is not visible either with "Show All Schemas" enabled or not.

When "Show All Schemas" is enabled, only standard schema are visible (like dbo, guest, db_*, INFORMATION_SCHEMA).

DB is SQL Server 2017 for Linux.

**Comment by BertieFulton** [comment]
The same thing has happened to me (as described by @jest). I can still access the schemas via the SQL editor, thought obviously, auto-complete doesn't work.

DB is Azure SQL Server

**Comment by pdanie** [comment]
If I check **SHOW ALL SCHEMAS** in the _DBeaver_ connection dialog, a bunch of SQL Server internal schemas are shown. But still the schemas for **AdventureWorks2012** (and our Company database) is not shown.

**Comment by tperrigo** [comment]
I'm having the same problem since upgrading to 4.3.2.  Database is MS SQL Server (JTDS driver), client machine is Ubuntu 14.04.  Prior to the update, I could simply connect to the database and see the list of our schemas; now, even save checking "Show all Schemas", I only see SQL Server schemas, as well as schemas for our DBA User and a fellow developer, who has not yet updated to 4.3.2.  I am able to connect and view the tables in an informix database, though they are not partitioned into custom schemas.  Any help would be very much appreciated.

**Comment by serge-rider** [comment]
It is a bug, DBeaver doesn't show SQL Server external schemas .
Thanks for report.

**Comment by serge-rider** [comment]
Please check the fix in EA version - https://dbeaver.jkiss.org/files/ea/

**Comment by tperrigo** [comment]
The link posted to the EA version seems to still go a page with downloads to the CE version.  I tried downloading / reinstalling using the dbeaver-ce_4.3.2_amd64.deb version, but have noticed no change in behavior-- I'm still unable to see any of the (numerous) schemas in our SQL Server databases (using the JTDS driver).  Prior to updating, everything worked as expected-- I would open a connection, see a list of the various schemas, view the tables in each schema, etc.  I've only tested with SQL Server and Informix, but of the 2 SQL Server is the only one that seems to have the issue.  Is there a way to roll-back to a previous version?

**Comment by pdanie** [comment]
I have downloaded the **dbeaver-ce-4.3.2-x86_64-setup.exe** file from the [https://dbeaver.jkiss.org/files/ea/](https://dbeaver.jkiss.org/files/ea/) address.

**Note**: The downloaded file above differed from the official version 4.3.2 file.

**o** Create a New Connection to the demo database **AdventureWorks2012** using the **Microsoft Driver 2**.
**o** The demo schemas **HumanResources**, **Person**, **Production**, **Purchasing** and **Sales** are not shown.

So. No changes compared to the official release 4.3.2.

**Comment by serge-rider** [comment]
@tperrigo @pdanie Yep, sorry, something went wrong during version publish process.
Please try it again.
This is how it should look now:
![image](https://user-images.githubusercontent.com/6398845/34691469-bb159516-f4cd-11e7-9657-ad4f651459a2.png)

**Comment by tperrigo** [comment]
That seemed to do the trick!  Thanks for the quick assistance!

**Comment by jest** [comment]
Indeed, now the user-created schema is shown with "Show All Schemas" enabled or not. Thanks!

**Comment by pdanie** [comment]
Checked out the new early release of DBeaver. It seems that the schemas now are shown as expected. Great work.

**Comment by shatfield** [comment]
This is happening for me in 4.3.2. We have several non empty schemas that do not appear, even if "Show All Schemas" is selected. This is using the official SQL Server driver. 4.3.1 works as expected. I have attached screenshots to show the difference.
v4.3.1:
![dbeaver 4 3 1 schemas](https://user-images.githubusercontent.com/22104299/34946080-7655aafa-f9d3-11e7-8b33-a962df3faa99.png)

v4.3.2:
![dbeaver 4 3 2 schemas](https://user-images.githubusercontent.com/22104299/34946091-7e60964c-f9d3-11e7-9ef5-3f36f567785b.png)

**Comment by serge-rider** [comment]
It is not fixed in 4.3.2.

It will be fixed in 4.3.3 (see milestone info). Also you can download EA version (see above)

**Comment by ced75** [comment]
I tested the EA version and it works fine for tables and views.
Unfortunately, I still get an error on procedures.
If I double-clic on a function, the information tab is the following one:
![image](https://user-images.githubusercontent.com/12892581/35097526-d30508a2-fc50-11e7-8474-3197f4c053d1.png)

dbo is the appropriate schema.

But when I clic on the source tab, I get the following error:
![image](https://user-images.githubusercontent.com/12892581/35097588-093f1250-fc51-11e7-86e6-567025fc18f6.png)

meaning that it searches in sys schema.

**Comment by serge-rider** [comment]
Well, yes, it gets sources using sp_helptext procedure in sys schema.
Do you know any better way way to do this?

**Comment by ced75** [comment]
In SQL Server 2000, I usually get the procedure sources by querying INFORMATION_SCHEMA.ROUTINES.
The sources are in ROUTINE_DEFINITION column.

So, for a function named fct1 in a database named db1, I get the sources with the following query:
SELECT ROUTINE_DEFINITION
FROM db1.INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_CATALOG = 'db1'
AND ROUTINE_SCHEMA = 'dbo'
AND ROUTINE_NAME = 'fct1';

**Comment by rcarlomagno** [comment]
in version 4.2.6 CE i used to connect to a sql server 2000 using jTDS driver, because Microsoft Driver 2 doesnt support sql server 2000, i got "sql server version 8 is not supported by this driver". so, everything was ok using jTDS, but now when i updated dbeaver to 4.3.2 CE, i cant list my tables in any of my databases, i get an error "SQL Error [208] [S0002]: Invalid object name 'Northwind.sys.sysusers'.", so i cannot access my tables, views, etc

**Comment by serge-rider** [comment]
@rcarlomagno this exact issue was fixed in this ticket. You can test it in EA or in 4.3.3 version.
