### ISSUE TITLE
New Icon Set Needs Larger Areas of Distinction

### ISSUE THREAD

**Issue by Lonniebiz** [dbeaver/dbeaver#2751]
The new toolbar icons look good, but for me it is harder to distinguish between certain icons due to the fact that the part of the icon that distinguishes it from another is too small.

![ToolBar](http://neartalk.com/ss/2018-01-08_001_1147x31.png)

For example, the "New SQL Script" icon only dedicates a very small portion of its bottom-right corner for distinguishing it from other similar icons on the toolbar. I'd like the distinguishing portions of each icon to be as large as possible, because it reduces eye strain and the time it takes me to select the correct one.

**Comment by serge-rider** [comment]
Yep, this issue was already mentioned in #2680. We'll try to change these icons (as well as connection/disconnect icons) in the next version.

**Comment by Lonniebiz** [comment]
The icons are better in 4.3.3.1.
