### ISSUE TITLE
brew upgrade formula?

### ISSUE THREAD

**Issue by lalato** [dbeaver/dbeaver#2752]
Is there a brew upgrade formula for dbeaver-community?  If not, what's the correct procedure to upgrade the latest version using brew?

**Comment by etudoras** [comment]
brew cask upgrade dbeaver-community

**Comment by lalato** [comment]
I've tried this.  The result is always...

**No Casks to upgrade**

**Comment by etudoras** [comment]
Did you try upgrading brew itself before?

**Comment by lalato** [comment]
Good question. Tried to update brew and it resulted in an error.  So I re-installed brew.  That seems to have resolved the issue with upgrading the dbeaver cask via brew.  Thanks!

**Comment by coryroyce** [comment]
This works for me:
`brew upgrade --cask dbeaver-community`
