### ISSUE TITLE
default UI when opening a table

### ISSUE THREAD

**Issue by sirber** [dbeaver/dbeaver#2753]
When I  double-click on a table in a list or the tree navigation, could it be possible to land on "Properties" tab and "Columns" sub-tab by default?

"information" sub-tab isn't useful day to day.
sometimes "data" tab is showed first instead of "properties", whichcan get a hit on the database if the table is already queried elsewhere. data tab should only be showed/queried when explicitly asked for.

thank you!

**Comment by serge-rider** [comment]
You can "detach" information panel so it will look like in earlier DBeaver versions:
![image](https://user-images.githubusercontent.com/6398845/34691931-57f26700-f4cf-11e7-85f4-a4e514926e7a.png)
![image](https://user-images.githubusercontent.com/6398845/34691953-6b7067b4-f4cf-11e7-9b2a-5367411503c8.png)

I'll make this look-and-feel default in the next DBeaver version. 
Indeed it is not very obvious how this UI switch works.

**Comment by sirber** [comment]
nice! thank you! the information is now hidden (detached, then hidden).

what do you think about always use properties tab by default when opening a table/view?

**Comment by serge-rider** [comment]
> what do you think about always use properties tab by default when opening a table/view?

It will be changed in the next version

**Comment by sirber** [comment]
thank you!
