### ISSUE TITLE
How to change project location folder?

### ISSUE THREAD

**Issue by snakyjake1** [dbeaver/dbeaver#2754]
How do I change the PROJECT_LOC?
The Edit button is disabled.
![image](https://user-images.githubusercontent.com/8312560/34695566-38d5a502-f480-11e7-8d00-9629fdff0990.png)

![image](https://user-images.githubusercontent.com/8312560/34695630-79c5887a-f480-11e7-94cd-7a97d4e1f440.png)

**Comment by serge-rider** [comment]
Looks like your project is located outside of DBeaver workspace. 
You can't change this location from DBeaver but you can copy/move your using file browser and then open it in DBeaver using new project wizard:
![image](https://user-images.githubusercontent.com/6398845/34706587-c20dee4e-f519-11e7-9a47-00a5779b1d97.png)
