### ISSUE TITLE
Vertica: table columns edit

### ISSUE THREAD

**Issue by BETEP0K1** [dbeaver/dbeaver#2756]
Version 4.3.2.

I can change, for example, in MySQL, in the existing column column Data Type from the drop-down list.
[http://ibb.co/nvf5sR](url)
But in Vertica it does not work, the field is not available for modification, 
I can do it  only through the SQL query.
[http://ibb.co/bZOx6m](url)

**Comment by BETEP0K1** [comment]
My sql screenshot http://ibb.co/nvf5sR
Vertica screenshot http://ibb.co/bZOx6m

**Comment by serge-rider** [comment]
Yes, you are right. This feature is not yet supported by Vertica extension.
I'll mark this ticket as FR.

**Comment by BETEP0K1** [comment]
OK. understood. many thanks

**Comment by serge-rider** [comment]
Column editor will be added in 5.0.6
