### ISSUE TITLE
-vm switch in dbeaver.ini not read / not working

### ISSUE THREAD

**Issue by Henry-Jones** [dbeaver/dbeaver#2757]
I'm trying to reference a JRE with the -vm switch in the dbeaver.ini

Serge Rider suggested that the switch should be placed before -vmargs in the ini file but the result is the same. I tried it in multiple places (at the very beginning, before -vmargs, as only option in the file).

Every time a Dialog box come up complaining that the JRE cannot be found and was searched at programpath\jre\bin\javaw.exe.

This message also stays the same, when I use only a single word as path or an absolute path.

If I start dbeaver via shortcut and the -vm switch it works as expected.

The System is Windows 10 / 1709 x64.

**Comment by titou10titou10** [comment]
Hi,
Could you show us your dbeaver.ini file?
Thanks

**Comment by Henry-Jones** [comment]
Please see attached file (containing 4 different Version, all of them not working.

The commandline in the shortcut (which works) is:

"J:\Tools - Portable\DBeaver\dbeaver.exe" -vm ..\CommonFiles\Java\bin\java.exe -data .workspace

[DBeaver.zip](https://github.com/dbeaver/dbeaver/files/1615101/DBeaver.zip)

**Comment by titou10titou10** [comment]
In `dbeaver.ini`:
*  The "`-vm`" argument must be the line just before the "`-vmargs`" line and you can not write anything on the same line
* The link to `java.exe` must be just after it and it must not start with spaces

Reference from the eclipse site [here](https://wiki.eclipse.org/Eclipse.ini#Specifying_the_JVM)

Example:
```
...
-showsplash
-vm
K:/jdk8_64/bin/javaw.exe
-vmargs
-XX:+IgnoreUnrecognizedVMOptions 
...

**Comment by Henry-Jones** [comment]
Ok, this works, thanks. As just tested the same goes for the -data switch (must be two lines).

As I'm unfamiliar with java style ini files, I expected switch and parameter must be in the same line as in common ini files.

Maybe the readme.txt can be updated then, as this more or less suggest that switch and parameter share the same line.

Anyway, thanks for the quick help.
