### ISSUE TITLE
Incorrect count returned when using "SQL Editor" -> "Select row count"

### ISSUE THREAD

**Issue by antonwierenga** [dbeaver/dbeaver#2759]
When I execute "SQL Editor" -> "Select row count" incorrect SQL is generated (only the first distinct column is considered) and as a result an incorrect result is returned.

<img width="1024" alt="screen shot 2018-01-09 at 15 32 30" src="https://user-images.githubusercontent.com/14827290/34725954-dde37d1c-f552-11e7-8afd-9f12c06b51fe.png">

This seems to be specific for EnterpriseDB (9.6.5.10). I could not reproduce this on Oracle or Postgres (on these databases the correct count of 2 is returned).

OSX 10.13.2 / DBeaver 4.3.2

**Comment by serge-rider** [comment]
What driver do you use for Enterprise DB? 
Is is PostgreSQL/PostgreSQL Generic?

**Comment by serge-rider** [comment]
In any case I've fixed COUNT transformer (it'll include all source query columns).

**Comment by antonwierenga** [comment]
Thanks for the fix. For completeness; I am using the PostgreSQL driver.
