### ISSUE TITLE
'Access denied' to jdbc:mariadb socket connection in DBeaver.  OK from shell.

### ISSUE THREAD

**Issue by ahenry2** [dbeaver/dbeaver#2761]
I've got MariaDB 10.2.12 installed on linux.

It's set up for socket access,

```
	ls -al /var/run/mariadb/mariadb.sock
		srwxrwxrwx 1 mysql mysql 0 Jan  6 12:19 /var/run/mariadb/mariadb.sock=
```

Via shell, socket connection works perfectly,

```
	mysql -h localhost -u root -D mysql
		Reading table information for completion of table and column names
		You can turn off this feature to get a quicker startup with -A

		Welcome to the MariaDB monitor.  Commands end with ; or \g.
		Your MariaDB connection id is 1371
		Server version: 10.2.12-MariaDB-log Source distribution

		Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

		Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

		MariaDB [mysql]>
```

I'm trying to get a socket connection to it using DBeaver 4.3.2 GUI.

I've got JDK 1.8 installed
```
	java -version
		OpenJDK Runtime Environment (IcedTea 3.6.0) (build 1.8.0_151-b12 suse-281.2-x86_64)
		OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

I grabbed latest MariaDB Connector-j,

```
	ls -al /root/.dbeaver-drivers/maven/maven-central/org.mariadb.jdbc/mariadb-java-client-2.2.1.jar
		-rw-r--r-- 1 root root 553K Dec 22 03:48 /root/.dbeaver-drivers/maven/maven-central/org.mariadb.jdbc/mariadb-java-client-2.2.1.jar
```

In Dbeaver, I have a DB connection defined:

```
	@Database connection settings ->
		Server Host: localhost
		Port: 3306
		Database: mysql
		User name: root
		Password: xxxxxxxx

		Local Client: /usr/local/mariadb
		Driver Name: MariaDB

	@Database connection settings -> Edit Driver Settings
		Driver Name: MariaDB Driver       Type: MySQL
		ClassName: org.mariadb.jdbc.Driver
		URL Template: jdbc:mariadb://localhost:3306/mysql?socket=/var/run/mariadb/mariadb.sock
		DefaultPort: 3306       [ ] Embedded

		Libraries
			/root/.dbeaver-drivers/maven/maven-central/org.mariadb.jdbc/mariadb-java-client-2.2.1.jar
```

But when I try to access the connection, I just get:

```
	"Could not connect: Access denied for user 'root'@'localhost'"
```
What am I missing in my DBeaver config?

**Comment by ahenry2** [comment]
In closed issue

https://github.com/dbeaver/dbeaver/issues/279

@serge-rider said

>  I'm afraid this is not possible with standard MySQL JDBC driver: http://lists.mysql.com/java/8749

Fyi, the MariaDB "Connector-J" driver

https://mariadb.com/kb/en/library/about-mariadb-connector-j/#connection-strings

_does_ support socket based connections

**Comment by serge-rider** [comment]
You can perform this by setting driver property `localSocket`.
![image](https://user-images.githubusercontent.com/6398845/34744475-5f0e0614-f59e-11e7-8a0f-5d6d297726d9.png)

Note: you will need to add extra driver libraries (JNA - https://repo1.maven.org/maven2/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar)

**Comment by ahenry2** [comment]
@serge-rider Thanks, that gets me further:

I added the new user property

```
DBeaver ->
	Edit Connection ->
		Connection settings ->
			Driver properties
				Name: localSocket
				Value: true
```

and located jna's jar


```
rpm -qa jna
	jna-4.5.0-58.1.noarch
rpm -ql jna | grep jar
	/usr/share/java/jna-platform.jar
	/usr/share/java/jna.jar
```

and added to the "Maria DB" connection's libraries,

```
/etc/mariadb/connector-j/mariadb-java-client-2.2.1.jar
/usr/share/java/jna.jar
```

with the URL Template still:

```
jdbc:mariadb://localhost:3306/mysql?socket=/var/lib/mariadb/mariadb.sock
```

But now, when I 'test connection', I get

> Could not connect to address=(host=localhost)(type=master):native connect() failed: No such file or directory

![SCREENSHOT](https://i.imgur.com/HWrRKw9.png)

**Comment by ahenry2** [comment]
After a little digging, it's not

```
localSocket = true
```

It's

```
localSocket = /var/lib/mariadb/mariadb.sock
```

fyi

> https://mariadb.com/kb/en/library/about-mariadb-connector-j/

```
localSocket
	Permits connecting to the database via Unix domain socket, if the server allows it.The value is the path of Unix domain socket (i.e "socket" database parameter : select @@socket) .since 1.1.4
```

Once that's changed, I get a connection.

**Comment by serge-rider** [comment]
@ahenry2 Thanks for information!

**Comment by catalin560** [comment]
its 2020, I'm on linux mint, dbeaver community version 7 and this bullshit is still unresolved even by trying the stuff above... why the frickin hell do I have to go through debugging this stuff right after installing mariadb???

**Comment by flip111** [comment]
I second that @catalin560

**Comment by jbrumwell** [comment]
@ahenry2 using google cloud sql locally the only option is a socket. I was previously using valentina studio which handles this use case and its restricting me from switching over to dbeaver. I tried the options above but closest I got was authentication error root no password.

**Comment by Abdull** [comment]
* step 1: find out *mariadb* Unix socket file
  * strategy 1: via filesystem: `grep -rin socket /etc/mariadb /etc/mysql`
  * strategy 2: via SQL query: `mysql -e "show variables like 'socket';"`
  * in my case it is `socket=/run/mysqld/mysqld.sock`
* step 2: use a **fresh/untinkered** installation of *DBeaver*, Version *23.2.0.202309040911*
  * select "New Database Connection". a pop-up "Connect to a database. Select your database" appears.
    * select "MariaDB", click "Next >". the pop-up becomes "Connect to a database. Connection Settings. MariaDB connection settings".
    * click button "Driver Settings" (lower right). a pop-up "Edit Driver 'MariaDB'" appears.
      * select "Libraries" pane. select "org.mariadb.jdbc:mariadb-java-client:RELEASE [x.y.z]". click on "Download/Update". a pop-up "Driver settings. Download driver files. Download MariaDB driver files" appears.
        * under "Files required by driver", within row "org.mariadb.jdbc:mariadb-java-client:RELEASE [x.y.z]", click on the "Version" cell. a drop-down appears.
        * select the latest version (in my case, "3.2.0"). click "Download". The "Driver settings. ..." pop-up closes.
      * back in the "Edit Driver 'MariaDB'" pop-up, click "OK". This pop-up closes.
    * back in the "Connect to a database. Connection Settings. MariaDB connection settings" pop-up, on the "Main" tab, under "Server":
      * for "Connect by:", select "URL"
      * for "URL.", provide "jdbc:mariadb://localhost:3306/?localSocket=/run/mysqld/mysqld.sock" - adapt "localSocket=..." to the file path identified during the previous "step 1".
    * configure "Username:" as appropriate
    * click "Test Connection ..." (lower left). if everything goes well, a pop-up "Connection test" with a successful "Connected ..." information should appear. click "OK" to close this pop-up.
    * back in the "Connect to a database. Connection Settings. MariaDB connection settings" pop-up, click "OK" to finish the connection setup.

![setup-mariadb-unix-socket-1](https://github.com/dbeaver/dbeaver/assets/529862/fa363a75-17ac-44ce-8bb9-64143adb04b7)
![setup-mariadb-unix-socket-2](https://github.com/dbeaver/dbeaver/assets/529862/ea362238-1db3-452f-bc76-ed6636b3dca6)

**Comment by Pysis868** [comment]
Finally, still had 23.0.2 in Fedora Linux 39 repos, not 23.2.3.  Updating provided the MariaDB 3.2.0 library by default, and the Host Connect By URL additional settings!

So with those updates and defaults helping, I think all that is needed is the `jdbc:mariadb://localhost:3306/?localSocket=/run/mysqld/mysqld.sock` URL.

Wanted to try updating using official methods to 24.0.2, but the Flathub variant did not want to work, using socket access, gave me the error message:
> native connect() failed : No such file or directory
I installed the MariaDB and Postgres plugins, but maybe still a permission issue?

Back to first party, direct-downloaded packages from the website, cleaning the others away, using 24.1.1 now, and removing any global driver setting `localSocket` value, just providing the socket paths in each connections' string instead.



Keep coming back to this issue.
Using the manually installed RPM package for the application,
been upgrading, now using DBeaver 25.3.4,
using my existing connection profile with the JDBC URL and option entered and selected,
cleared `Driver Settings` `localSocket` setting,
but MariaDB driver version 3.5.7 would not work, still only 3.2.0.
Strange still need to use such an old version just to retain the socket connection capability..

**Comment by jmsarmientopalma** [comment]
> * step 1: find out _mariadb_ Unix socket file
>   
>   * strategy 1: via filesystem: `grep -rin socket /etc/mariadb /etc/mysql`
>   * strategy 2: via SQL query: `mysql -e "show variables like 'socket';"`
>   * in my case it is `socket=/run/mysqld/mysqld.sock`
> * step 2: use a **fresh/untinkered** installation of _DBeaver_, Version _23.2.0.202309040911_
>   
>   * select "New Database Connection". a pop-up "Connect to a database. Select your database" appears.
>     
>     * select "MariaDB", click "Next >". the pop-up becomes "Connect to a database. Connection Settings. MariaDB connection settings".
>     * click button "Driver Settings" (lower right). a pop-up "Edit Driver 'MariaDB'" appears.
>       
>       * select "Libraries" pane. select "org.mariadb.jdbc:mariadb-java-client:RELEASE [x.y.z]". click on "Download/Update". a pop-up "Driver settings. Download driver files. Download MariaDB driver files" appears.
>         
>         * under "Files required by driver", within row "org.mariadb.jdbc:mariadb-java-client:RELEASE [x.y.z]", click on the "Version" cell. a drop-down appears.
>         * select the latest version (in my case, "3.2.0"). click "Download". The "Driver settings. ..." pop-up closes.
>       * back in the "Edit Driver 'MariaDB'" pop-up, click "OK". This pop-up closes.
>     * back in the "Connect to a database. Connection Settings. MariaDB connection settings" pop-up, on the "Main" tab, under "Server":
>       
>       * for "Connect by:", select "URL"
>       * for "URL.", provide "jdbc:mariadb://localhost:3306/?localSocket=/run/mysqld/mysqld.sock" - adapt "localSocket=..." to the file path identified during the previous "step 1".
>     * configure "Username:" as appropriate
>     * click "Test Connection ..." (lower left). if everything goes well, a pop-up "Connection test" with a successful "Connected ..." information should appear. click "OK" to close this pop-up.
>     * back in the "Connect to a database. Connection Settings. MariaDB connection settings" pop-up, click "OK" to finish the connection setup.
> 
> ![setup-mariadb-unix-socket-1](https://user-images.githubusercontent.com/529862/265451065-fa363a75-17ac-44ce-8bb9-64143adb04b7.png) ![setup-mariadb-unix-socket-2](https://user-images.githubusercontent.com/529862/265451099-ea362238-1db3-452f-bc76-ed6636b3dca6.png)

This is it!! Thanks man...

**Comment by tristbisch** [comment]
This fixed it!  Also, I did have to uninstall dbeaver and reinstall to get a fresh install of 24.0.1 in order for this to work.  The only visible change I noticed was that on Connection Settings under Advanced: Local Client was now set to /usr.  Maybe try that before reinstalling.

**Comment by YoungFrog** [comment]
For future reference : the snap version of dbeaver (dbeaver-ce) did not allow me to connect through the unix socket. I installed the .deb file and all went well.

Special thanks @Abdull for your precise step-by-step: it gave me enough confidence that the problem was somewhere else.
