### ISSUE TITLE
Launching DBeaver from a Web Page

### ISSUE THREAD

**Issue by rltheis27** [dbeaver/dbeaver#2762]
Hello,
  Can DBeaver be launched from a web page? Or is there a web UI for DBeaver? Is there any documentation to accomplish the above?

  My office needs to provide a general purpose database query tool for our customers located in multiple divisions. My office does not have access to a division's network. This causes issues trying to develop DBeaver. All the users have access to our web server. Being able to provide DBeaver over the web would eliminate our deployment issues.

Thank you,
  Richard

**Comment by serge-rider** [comment]
Potentially yes - using Java Web Start technology. This is supported by Eclipse framework.

But we don't provide this type of deployment right now. 
This looks more like an enterprise installation and usually it is combined with some predefined connections configuration.

**Comment by sirber** [comment]
You (OP) could write an installer that install dbeaver and configures it...
