### ISSUE TITLE
execute multiple query at the same time on the same database

### ISSUE THREAD

**Issue by sirber** [dbeaver/dbeaver#2764]
could it be possible to have one connection per tab, so I could execute multiple queries at the same? actually other queries just wait that the first one finishes. if I look in session I already have like 20 sleeping connections from dbeaver on the db doing nothing.

![image](https://user-images.githubusercontent.com/3911428/34742700-09d608b6-f555-11e7-8255-98d22ae5337a.png)

**Comment by sirber** [comment]
I understand that if I lock a table, it's my fault and I have to wait. But I,m not currently locking anything and I have 3 queries waiting.

**Comment by sirber** [comment]
dup #2737

**Comment by serge-rider** [comment]
Yes, you can do this.
DBeaver can open separate connection for each SQL editor. Thus one query won't block another in network communications:

![image](https://user-images.githubusercontent.com/6398845/34844127-7e28e80a-f721-11e7-9738-c4aba80c6f86.png)

**Comment by sirber** [comment]
sweet!!! thank you!

**Comment by sthorntonbarrick** [comment]
Is there anyway to have all the results from all the queries executed display on the same tab? I am coming from a SQL background & it is very useful to to have all results on 1 tab instead of having to reference back & forth. Thank you.

**Comment by serge-rider** [comment]
@sthorntonbarrick this feature is tracked in #667
