### ISSUE TITLE
IO Error: Utility 'mysqldump.exe' not found in client home 'MySQL Connector/Net'

### ISSUE THREAD

**Issue by levilogics** [dbeaver/dbeaver#2765]
When I try to backup database using tools->dump database.
I have an error:
IO Error: Utility 'mysqldump.exe' not found in client home 'MySQL Connector/Net'

**Comment by sirber** [comment]
you'll have to (probably) install mysql on your windows client for that to work. 
on a linux desktop with mysql installed it works well.

**Comment by sirber** [comment]
Yeah.. 

1. install mariadb for windows, including the client.
2. open windows services, stop Mysql and set it manual startup
3. restart dBeaver
4. open tour database connection properties. set local client to "Mariadb 10.x"
5. export your database.

**Comment by serge-rider** [comment]
You can install MariaDB or MySQL server (choose not to install service if you need only command line tools). Or you can also install MySQL Workbench which also contains cli tools.

**Comment by sirber** [comment]
MySQL Workbench isn't detected by dBeaver for windows though.

**Comment by serge-rider** [comment]
Please check replies in #1361 . 
That is pretty the same topic, so clising as duplicate

**Comment by chupakabra305** [comment]
I'm getting this weird error on the MacOS enterprise version when I try to export(dump) a database.
mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')  
Process exit code: 2

**Comment by dankkomcg** [comment]
This works for me without installing any MySQL Server on w10 and using WSL:

* Download the zip from your mysql version.
* Go to `C:\Users\{ YOUR USER }\AppData\Local\DBeaver`
* If doesn't exist, create into MySQL Binaries folder.
* Open the zip and go to bin
* Search mysqldump.exe and extract it into MySQL Binaries folder.
* Try to export again.

**Comment by kuworking** [comment]
Following what @dankkomcg said I have been able to start dumping the db (w10)

- download `mariadb server`, extract and find `mysqldump.exe`
- go to `C:\Program Files\DBeaver\` and create the folder `MySQL Binaries`
- copy-paste the previous `exe` file to that folder, and I've been able to start dumping my database 

However, it seems to be frozen in this state without doing anything nor giving the change to finish the process (I ignore if this is related to the binary or it is another issue)

![image](https://user-images.githubusercontent.com/4474004/83355254-9331f700-a35e-11ea-8fce-304ce6164093.png)




> This works for me without installing any MySQL Server on w10 and using WSL:
> 
> * Download the zip from your mysql version.
> * Go to `C:\Users\{ YOUR USER }\AppData\Local\DBeaver`
> * If doesn't exist, create into MySQL Binaries folder.
> * Open the zip and go to bin
> * Search mysqldump.exe and extract it into MySQL Binaries folder.
> * Try to export again.

**Comment by 88gm** [comment]
So, after a few hours trying to dump a database, i finally made it through that way:



> This works for me without installing any MySQL Server on w10 and using WSL:
> 
> * Download the zip from your mysql version.
> * Go to `C:\Users\{ YOUR USER }\AppData\Local\DBeaver`
> * If doesn't exist, create into MySQL Binaries folder.
> * Open the zip and go to bin

Then: 
* Copy **ALL** the files from mysql `bin` to the DBeaver `MySQL Binaries` folder.
* Restart DBeaver and try again to dump.

PS: If you are using MySql 8.0 you might need to add a extra argument before dumping:

`--column-statistics=0`
![1_7](https://user-images.githubusercontent.com/31501870/83781882-7ef34000-a665-11ea-9ab1-887641a92315.jpg)

**Comment by Madhan-Tradezap** [comment]
https://dbeaver.com/docs/wiki/Backup-Restore/
Check this link , Change "Client" on export option

**Comment by selabie68** [comment]
> https://dbeaver.com/docs/wiki/Backup-Restore/
> Check this link , Change "Client" on export option

This was not 100% clear but for future reference

Click "Client..."

![image](https://user-images.githubusercontent.com/5601142/93201956-3e8f7c00-f795-11ea-921c-a69d5141b654.png)

Select "MySQL Binaries"

![image](https://user-images.githubusercontent.com/5601142/93202083-73033800-f795-11ea-80ce-a291d52369a0.png)

**Comment by Fernando-Braulio** [comment]
> > https://dbeaver.com/docs/wiki/Backup-Restore/
> > Check this link , Change "Client" on export option
> 
> ‎Isso não foi 100% claro, mas para referência futura‎
> 
> Click "Client..."
> 
> ![image](https://user-images.githubusercontent.com/5601142/93201956-3e8f7c00-f795-11ea-921c-a69d5141b654.png)
> 
> Select "MySQL Binaries"
> 
> ![image](https://user-images.githubusercontent.com/5601142/93202083-73033800-f795-11ea-80ce-a291d52369a0.png)

Show, isso funcionou para mim

**Comment by niraj-khatiwada** [comment]
For future Linux users,

1) Find mysql client path:
![image](https://user-images.githubusercontent.com/51436631/190435704-841bb9d5-282e-4f1f-b16f-5bfdadd7dacb.png)


2) Add the path to "Load Client"  window:
![image](https://user-images.githubusercontent.com/51436631/190435808-ecd20a1d-40ac-445a-8bb6-19bd53df0d32.png)
![image](https://user-images.githubusercontent.com/51436631/190436452-3b0bb9be-7638-414d-b360-fa1d49fe650d.png)

It should work now.

**Comment by sanyonishah** [comment]
I simply copied mysqldump.exe from mysql server folder/bin to mysql router folder /bin
