### ISSUE TITLE
auto indent not working on new line after semicolon

### ISSUE THREAD

**Issue by wthys** [dbeaver/dbeaver#2768]
I'm using DBeaver CE 4.3.2 on Ubuntu 16.04 and have noticed since 4.3.1 that when I start a new line in Oracle PL/SQL code the autoindent as in 4.2.x is only replicated when the previous line was not ended with a semicolon (';'). If the previous line was ended with a semicolon, the new line will start at column 1, not the at the previous indentation level.

There's no autoindent option in the GUI that I can find under preferences so I'm inclined to think this is a regression on previous behaviour

**Comment by wthys** [comment]
It seems it was a deliberate feature added in aedd8cda20f807d6b260517f729bce6a64b3a032. Any chance in getting a config option to turn this on/off?

**Comment by serge-rider** [comment]
Yes, this probably should be configurable.

**Comment by serge-rider** [comment]
Or, better, we shouldn't reset indentation but we should do single "unindent" after semicolon. This makes sense for complicated query/procedures with multiple indentations.
