### ISSUE TITLE
Persist Changes error (RENAME + ALTER)

### ISSUE THREAD

**Issue by infectormp** [dbeaver/dbeaver#277]
**3.6.2**

I did 2 changes for mysql db in this order: change column comment then change column name

Persist Changes show me:
1. ALTER TABLE borg_logs.bfiles MODIFY COLUMN **flag** tinytext NOT NULL COMMENT 'Item flag';
2. ALTER TABLE borg_logs.bfiles CHANGE flags flag tinytext NOT NULL COMMENT 'Item flag';

for first alter table i must have column name = **flags**.

And surely i get error, because column **flag** not exist yet.

DBCException: SQL Error [1054] [42S22]: Unknown column 'flag' in 'bfiles'
  SQLSyntaxErrorException: Unknown column 'flag' in 'bfiles'
    org.mariadb.jdbc.internal.util.dao.QueryException: QueryException: Unknown column 'flag' in 'bfiles'

**Comment by uslss** [comment]
Issue is not reproduced on 6.0.2

**Comment by uslss** [comment]
Issue still reproduces on 6.2.1

**Comment by uslss** [comment]
fixed
