### ISSUE TITLE
Highlight Selected Column In Insert Statement

### ISSUE THREAD

**Issue by mknisc** [dbeaver/dbeaver#2770]
I work with very large insert statements which contains many columns in the insert header. A complication I experience is knowing which column I am editing when I am editing data in the values or select statement.

SQL Prompt has a feature which will "highlight" a column in the insert statement's insert header when the cursor for that column's corresponding data is selected or in the editing process.

Take the example below:

INSERT INTO TABLE_a(columnA, ColumnB, ColumnZ)
VALUES('1', '2', '3')

Whenever I selected a value in the statement above, such as 1, 2 or 3, the column in the insert Header will be highlighted.  In this case, if I were to place my cursor in the '3' value or select/edit the value, the column 'ColumnZ' would then be highlighted. 

Can this functionality be added?

**Comment by serge-rider** [comment]
Will mark as FR. This doable (using SQL editor annotations) but not easy.

**Comment by mknisc** [comment]
Thank you

**Comment by ChristopherMagee** [comment]
Just wanted to second this request, it would be a welcome quality of life improvement. 

Great job otherwise, DBeaver is a god send.

**Comment by OysteinBrandt** [comment]
I also second this request.

**Comment by 0xAnasEzz** [comment]
This is much needed.

**Comment by ShadelessFox** [comment]
Duplicate of #11052

Please track issue there

**Comment by co-dax** [comment]
I would like it too.

**Comment by csmith6-godaddy** [comment]
Did this ever progress? I see it has a duplicate label, but not sure how to see if this was implemented and if so how to enable it.
