### ISSUE TITLE
Text Declaration from large view truncated <oracle>

### ISSUE THREAD

**Issue by hugorn** [dbeaver/dbeaver#2771]
The text in Properties - Declaration is truncated for objects with large code.

Version: 4.3.2
OS: Deepin Linux
DB: Oracle
Driver: ojdbc8.jar

![deepin screenshot_selecionar area_20180110170055](https://user-images.githubusercontent.com/9035153/34792817-04d4d8d2-f628-11e7-8938-900b24861f02.png)

**Comment by serge-rider** [comment]
We'll use DBMS_METADATA.GET_DDL instead of direct sys catalog reading.
It is slower but it produces more accurate DDL.
