### ISSUE TITLE
solarized dark theme

### ISSUE THREAD

**Issue by cathemlin** [dbeaver/dbeaver#2775]
hoping the new version can support solarized dark theme~

**Comment by calfzhou** [comment]
and also solarized light theme 🥇

**Comment by serge-rider** [comment]
Version 5.1.2 will contain Color Theme extension support so any theme (including Solarized Dark/Light) can be applied.
For example:
![image](https://user-images.githubusercontent.com/6398845/45653474-cf68e980-bae0-11e8-8a2a-46bb15496851.png)

However I've stuck in this issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=443373 (theme settings are reset on restart). Hope to find some workaround..

**Comment by serge-rider** [comment]
https://github.com/eclipse-color-theme/eclipse-color-theme/issues/223

**Comment by serge-rider** [comment]
Please check it in 5.2.1.
