### ISSUE TITLE
DBeaver command line parameter -con "autocommit=..." have error in documentation

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2776]
DBeaver - **Version 4.3.2 CE EA**
DBeaver JDBC driver: **Microsoft Driver 2**
Operating System: **Windows 7** / **Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

The commandline sub parameter **autocommit** have error in documentation [Serge Rider DBeaver Wiki](https://github.com/serge-rider/dbeaver/wiki/Command-Line#connection-parameters).

The commandline sub parameter should be **autoCommit** (uppercase "C") instead of **autocommit** that the documentation state.

**Example of usage**: 

`C:\> dbeaver.exe -con "name=...|driver=...|autoCommit=false"`

**Comment by serge-rider** [comment]
Yep, indeed.
Thanks for report!
