### ISSUE TITLE
Add of command line parameter that expands the connection in the Database Navigator

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2777]
DBeaver - **Version 4.3.2 CE EA**
DBeaver JDBC driver: **Microsoft Driver 2**
Operating System: **Windows 7** / **Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

A _DBeaver_ command line parameter that expands the connection in the **Database Navigator** would be benificial.

Today I can with command line parameters create a connection and have the connection connect, but there user still have to click on the connection in the **Database Navigator** to have the connection tree expand.

Maybe a command line **Connection Parameter** like **connectExpand=true** that expand the connection tree if the connection parameter **connect=true** is also specified (implicit or explicit).

`C:\> dBeaver.exe -con "name=...|connect=true|connectExpand=true"`

**Comment by serge-rider** [comment]
This feature is already there (it is a global config, not per-connection):
![image](https://user-images.githubusercontent.com/6398845/35135976-abf8156e-fcf1-11e7-8793-098d1bc5bde1.png)

**Comment by pdanie** [comment]
That will suffice. Thanks
