### ISSUE TITLE
How do I donate to you guys?

### ISSUE THREAD

**Issue by isteven** [dbeaver/dbeaver#2778]
After some hellish experience with another PostgreSQL admin tool (I don't want to name it), I found DBeaver. It helps me regain my mental sanity.

I don't have budget and need to buy the Enterprise edition, so perhaps I can send a small token of gratitude through Paypal?

**Comment by carlosspohr** [comment]
Good question @isteven ,

@serge-rider, could you add a link to PayPal account or it's better to support team/project buying EE licences ?

I also interested in contribute.

**Comment by serge-rider** [comment]
@isteven @carlosspohr Thanks)
Although it is better to buy EE license (at least you will have EE version - even if you don't need it right) but it could be a bit expensive for a donation.
I think we'll add PayPal button with smaller donations (10-20$) somewhere in GitHub project info soon.

**Comment by chriseaton** [comment]
Just thought I'd chime in - hope you add a new payment option soon. Paypal blocks us in the USA from purchasing EE, and an international bank wire is expensive.

**Comment by serge-rider** [comment]
We've added donate button/information in readme (https://github.com/dbeaver/dbeaver/) and on community web site (https://dbeaver.jkiss.org).

Thank you!

**Comment by isteven** [comment]
@serge-rider 

I just donated. 

Again, thanks. You guys rock.

**Comment by serge-rider** [comment]
@isteven Thank you :)

It is here: https://dbeaver.jkiss.org/contribution/
