### ISSUE TITLE
DBeaver command line parameter -con "prop.propName" does not work

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2779]
DBeaver - **Version 4.3.2 CE EA**
DBeaver JDBC driver: **Microsoft Driver 2**
Operating System: **Windows 7** / **Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

I have tried to use the _DBeaver_ command line parameter -con "prop.propName" for **advanced connection parameters** and it does not seem to have any effect.

The command line below does not set the connection driver parameter **loginTimeout**.

`C:\>dBeaver.exe -con "name=...|driver=Micorosoft Driver 2|host=localhost|prop.loginTimeout=99"`

The command line below does not set the connection driver parameter **encrypt**.

`C:\>dBeaver.exe -con "name=...|driver=Micorosoft Driver 2|host=localhost|prop.encrypt=true"`

I have tried a number of the **Driver Parameters** that I can see in **Connection Configuration** dialog, and no one affect the specified advanced connection parameter.

**Comment by serge-rider** [comment]
This is a bug in parameters parser, thanks for report.
