### ISSUE TITLE
How can I view the "Save" button in the upper toolbar ?

### ISSUE THREAD

**Issue by roberto2357** [dbeaver/dbeaver#2781]
In previous versions of DBeaver (< 4.3.0) the save button 

![save](https://user-images.githubusercontent.com/22471800/34830857-7ef75280-f6e5-11e7-9506-f3e367ee656b.png)

was visible in the upper toolbar. Currently in 4.3.2 version I use the CTRL+S shortcut (or "File/save" from the menu) but the button was usefull. There is a method to show this button in 4.3.2 version?

Thanks.

**Comment by sirber** [comment]
I think you have a "save / revert" buttons in the right bottom corner too

**Comment by serge-rider** [comment]
Yeah, we removed this toolbar from default perspective settings (because it occupied too much space and it duplicated bottom toolbar).
But perhaps we should return possibility to add it in perspective configuration (for those who miss it).

**Comment by roberto2357** [comment]
Ok, I know the save button in the bottom toolbar (shortcut = CTRL+ALT+S)

![save2](https://user-images.githubusercontent.com/22471800/34869445-36fc9e70-f787-11e7-8364-c877658f6c08.png)

but it perform a different operation compared to the "upper save button".

The upper save button (for example) saves the changes in sql editors whereas the "bottom save button" saves changes (commit) in table data.

I'm wrong?

Thank you very much ;-)

**Comment by serge-rider** [comment]
@roberto2357 Exactly. Save in results viewer toolbar saves only data changes. While pper save saves all editor changes (including data).

**Comment by serge-rider** [comment]
We can make a separate "upper" toolbar for basic editor actions. It will be hidden by default but can be enabled in perspective settings.

**Comment by roberto2357** [comment]
Yes, it's a good idea :-)
Thanks Serge.

**Comment by serge-rider** [comment]
Done.
This toolbar will be visible only for database editors.

**Comment by jsmith0103** [comment]
Perhaps I'm dense, but I'm unable to enable this under 'Customize Perspective'. I can see it under the 'Edit Actions' toolbar, however attempting to check the box results in an error message "'Edit actions' cannot be made visible because all of its children are in unavailable action sets."
