### ISSUE TITLE
how can i install in silent mode 

### ISSUE THREAD

**Issue by blari18** [dbeaver/dbeaver#2783]
i want automaticaly install _**Windows 64 bit (installer + JRE)**_  in silent mode  
is it possible?
how can i do?  
thanks

**Comment by serge-rider** [comment]
This option doesn't work currently (see #2262)
We going to replace NSIS with MSI.

**Comment by serge-rider** [comment]
We'll fix this in 4.3.3 by modifying NSIS installer.
We just won't install in `program files` by default. Thus we'll remove NSIS multiuser  module. This will fix \D option.
