### ISSUE TITLE
PLS-00103: Encountered the symbol "" when expecting one of the following

### ISSUE THREAD

**Issue by rcperezg** [dbeaver/dbeaver#2785]
When I execute a block like this  in Oracle 12, everything is OK:
```
DECLARE 
x NUMBER;
BEGIN
dbms_output.put_line('HI EVERYBODY');
END;
```
But in Oracle 9 I get an error:

> SQL Error [6550] [65000]: ORA-06550: line 1, column 9:
> PLS-00103: Encountered the symbol "" when expecting one of the following:
> 
>    begin function package pragma procedure subtype type use
>    <an identifier> <a double-quoted delimited-identifier> form
>    current cursor

This is an example (I know x is not used). It doesn't work with more complex blocks.

Any idea?

**Comment by ajperez81** [comment]
I'm having the same problem with Oracle 10g (10.2) and DBeaver 5.0.0.
The script works fine with SQL*Plus and 10g.

**Comment by lucacicinelli** [comment]
Same error with Oracle 10g and DBeaver 5.0.2. No issue with SQLDeveloper.

`BEGIN
DBMS_SCHEDULER.RUN_JOB(job_name => '"WELFARE_BANDI"."JOB_REFRESH_MV_MIR"', USE_CURRENT_SESSION => FALSE);
END;`

--- or ---
`BEGIN
    DBMS_SCHEDULER.RUN_JOB(job_name => 'WELFARE_BANDI.JOB_REFRESH_MV_MIR', USE_CURRENT_SESSION => FALSE);
END;`

```
Errore SQL [6550] [65000]: ORA-06550: line 1, column 6:
PLS-00103: Encountered the symbol "" when expecting one of the following:

   begin case declare exit for goto if loop mod null pragma
   raise return select update while with <un identificativo>
   <un identificativo delimitato da virgolette>
   <una bind variable> << close current delete fetch lock insert
   open rollback savepoint set sql execute commit forall merge
   pipe
The symbol "" was ignored.
```

**Comment by serge-rider** [comment]
Perhaps it is related to Windows CR/LF.
Could you try to:
- Open SQL editor with your query
- main menu File->Convert Line Delimiters To->Unix

If this will help then I'll try to add some workaround for Oracle < 10.

**Comment by rcperezg** [comment]
If I replace Line delimiters no errors appear, but dbms_output does'n't write anything at Output tab.

**Comment by serge-rider** [comment]
I've pushed the fix (specifically for Oracle 10 and earlier).
Please check it in EA version (https://dbeaver.jkiss.org/files/ea/)

**Comment by serge-rider** [comment]
I presume that this was fixed.

**Comment by CengBeng** [comment]
DECLARE

	--Declare variables
	nValue		NUMBER(10) := &enter_value;
	vMessage	VARCHAR(30);

BEGIN
	--Test the value entered by the user
	IF nValue > 60000 THEN

		--Set and display the message
		vMessage := q'!The value isn't valid.!';
		dbms_output.put_line(vMessage);

	END IF;

END;

**Comment by CengBeng** [comment]
DECLARE

	--Declare variables
	nValue		NUMBER(10) := &enter_value;
	vMessage	VARCHAR(30);

BEGIN
	--Test the value entered by the user
	IF nValue > 60000 THEN

		--Set and display the message
		vMessage := q'!The value isn't valid.!';
		dbms_output.put_line(vMessage);

	END IF;

END;
