### ISSUE TITLE
Keyboard navigation is frustrating.

### ISSUE THREAD

**Issue by chriseaton** [dbeaver/dbeaver#2789]
I think it may be valuable to share my experience trying to use DBeaver as a relatively new user... Maybe there's a setting somewhere to change this... but here it is.

In many of the dialogs I'm presented with information to edit. When I tab into those fields and they then highlight and show as-if they are ready for editing, for some reason, they suddenly and surprisingly open some weird text box in the bottom-right corner that appears to do nothing.

In addition, for some reason hitting spacebar doesn't toggle a checkbox, which is very odd as that is a default in most GUIs - in fact, I can't seem to figure out *how* to toggle a checkbox with the keyboard.

Here is [a video capture of my experience](https://gfycat.com/SadSilverLemur). The only thing you can't hear is my frustrated key taps...

I would expect the editing of fields via keyboard to be relatively easy and straight-forward. I hope this can be improved!

Maybe the devs could spend a day or two mouse-less to see how much it drives them crazy!

**Comment by serge-rider** [comment]
Agreed, checkbox editor is a bit frustrating.

**Comment by chriseaton** [comment]
Glad to see the checkbox will be fixed. Any idea what that box is that for some reason appears in the bottom right when I try typing a value (in the video, I enter a column name, then TAB to the grid, and with the first cell selected start typing and that box appears).

**Comment by serge-rider** [comment]
> that textbox is that for some reason appears in the bottom right when I try typing a value

This is some native Linux windows manager behavior. 
DBeaver has nothing to do with that.
