### ISSUE TITLE
SybasejConnect - how to ignore errors and continue processing

### ISSUE THREAD

**Issue by jpm-jpm** [dbeaver/dbeaver#2792]
I use DBeaver 4.3.2 and a jConnect Sybase connection (to Sybase ASE V15.7 or V16)

Some Sybase commands return errors that can be ignored and processing should continue.
For example the following command under the "isql" Sybase command line utility returns data after error 17411 :

```
1> sp_configure 'statement'                                         
2> go                                                               
Msg 17411, Level 16, State 1:                                       
Server 'JPMLNXV157', Procedure 'sp_configure', Line 424:            
Configuration option is not unique.                                 
                                                                    
 Parameter Name                 Default     Memory Used Config Value
 ------------------------------ ----------- ----------- ------------
 statement cache size                     0       11250         5000
 statement pipe active                    0           0            1
 statement pipe max messages              0         599         1000
 statement statistics active              0           0            1
                                                                    
(1 row affected)                                                    
(return status = 1)                                                 
1>                                                      
```

            

Under DBeaver, processing stops due to error 17411
even if I configure "Ignore" for error management  in SQL Processing.

Could it be possible not stop processing in case of error if "ignore" is choosen ?

**Comment by serge-rider** [comment]
If you execute a script (<kbd>alt+x</kbd>) then clicking on Ignore after error message will process the rest of the script without error dialog.

Or do you mean something else?

**Comment by jpm-jpm** [comment]
When I execute **"sp_configure 'statement' "** (with Ctrl+Enter or Alt+x) I get error message and the result set returned by Sybase is not displayed (even if I choose OK in the error window)
![image](https://user-images.githubusercontent.com/35460124/34989849-5a43cba2-fac4-11e7-9da2-5c0dc26d6c8a.png)

If I choose "Ignore" in the data source configuration :
![image](https://user-images.githubusercontent.com/35460124/34989953-a21fd75e-fac4-11e7-85c0-01afdf8eda79.png)
then when I execute the query, the error 17411 is not displayed and the result set is not displayed also.

Jpm

**Comment by serge-rider** [comment]
This is Sybase-specific behavior (and it works only in jConnector driver). However I'll add a workaroudn which will let to fetch resultset even if other results fetch is failing.

**Comment by jpm-jpm** [comment]
Ok, thank you
