### ISSUE TITLE
After upgrade 4.3.2 can't connect to MSSQL using JTDS 

### ISSUE THREAD

**Issue by drmito** [dbeaver/dbeaver#2795]
Hi, 
up until 4.3.1 I was able to connect without problem to my work DB. I use a mac and since I am not in my works Domain I used 
jdbc:jtds:sqlserver://SYKPHSHAREHIE1V.nslijhs.net;DOMAIN=***** ( with my work domain here)  worked flawlessly since I started using dbeaver. 
since the upgrade ( maybe coincidence) I get refused connection. I started getting the same issue with DBvisualizer but Valentina Studio and Tableau could connect without a problem to the server. DBvisualizer was fixed by adding jdbc:jtds:sqlserver://*****.****.net;DOMAIN=******;user=****;password=****** to the string, not so much with dbeaver. 

![image](https://user-images.githubusercontent.com/1476649/34988694-883a5abc-fa8d-11e7-8387-77dc4ebfa9c9.png)

![image](https://user-images.githubusercontent.com/1476649/34988705-95a1111e-fa8d-11e7-9557-ae38ecd2cf21.png)

I go into Driver settings and the libraries are red 
![image](https://user-images.githubusercontent.com/1476649/34988473-d88b3c80-fa8c-11e7-9d18-660683c7c03a.png)
and the download says drivers missing but the download seems to not be working

![image](https://user-images.githubusercontent.com/1476649/34988507-ef719c46-fa8c-11e7-87ea-74a4ef621c23.png)

**Comment by serge-rider** [comment]
You have obviously incorrect connection configuration.

You shouldn't enter full JDBC URL in Database/Schema field. Enter just database name there or keep it empty.
Also enter valid host name (SYKPHSHAREHIE1V.nslijhs.net?) in Host field.

**Comment by drmito** [comment]
this is another server from same domain... was working fine until last tuesday when I upgraded... 
![image](https://user-images.githubusercontent.com/1476649/35007432-b44bdb64-fac7-11e7-8d87-4e247d34c0c7.png)
this configuration was working fine in dbeaver and dbvisualizer.... dbvisualizer suggested I add the username and password to the schema and it started work again... not same case with dbeaver

**Comment by osrojas** [comment]
Try this and let us know if it works:

In Driver Properties, try specifying the **DOMAIN** and **USER** and also set **USENTLMV2** to true. In Connection settings, specify your Username and Password. Use the default URL Template that DBeaver already provides _jdbc:jtds:sqlserver://{host}[:{port}][/{database}]_

**Comment by serge-rider** [comment]
@drmito if you need driver config to work this way (with full JDBC url) then you could create new driver configuration without URL pattern. In that case JDBC URL and user/password will be the only available fields and it will work like in dbvis.

But it is much better to use correct configuration. 
Enter host name in host field, database name in database field, user in user, password in password and additional parameters (like domain) in driver properties.

**Comment by drmito** [comment]
sorry for delay... was away from this for a while... @serge-rider your solution worked
Thanks!!!
