### ISSUE TITLE
DBEaver Generate SQL

### ISSUE THREAD

**Issue by george175** [dbeaver/dbeaver#2796]
Hi,

I ran a query for a simple table only using some of the fields (no joins), when I click on the result and choose generate sql , I get:  Not available, cannot resolve table. I tried to select all fields and I got same issue. The option is disabled.

I noticed thought that it's enabled for a different table.  Is there a reason why this won't work on some tables? 

Database is DB2 and I am using Jdbc to connect

**Comment by serge-rider** [comment]
I can't reproduce that. Please post some real example (query example).
What DB2 do you have (LUW, zOS, iSeries)?

**Comment by geuss** [comment]
Hi, I've the same issue on DBeaver Windows client (on linux client it works correctly). I'm connected to Oracle 12c DB and Teradata 15.0 DB.

![dbeaver_error](https://user-images.githubusercontent.com/26387091/36601874-96bb1a9e-18b6-11e8-9304-3bf8fed7bc5f.png)

**Comment by geuss** [comment]
The query was: "select * from cat" (it was hidden by pop-pup)

**Comment by satyakishorm** [comment]
I'm running into the same issue. I have to use 3.8.X version as a workaround for now. Any reason why generate sql is not working in 4.X versions?

**Comment by serge-rider** [comment]
Could you check this issue in 5.x?
There were a lot of fixes (besides other things DBeaver now supports editor of results produced by joined tables).

**Comment by serge-rider** [comment]
You could try to use fully-qualified (with schema name prefix - schema.table) table names in your query.

**Comment by serge-rider** [comment]
@geuss Ok. Could you post debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files) - perhaps something is going wrong during metadata reading and it may contain a clue.

**Comment by uslss** [comment]
is issue still actual in 6.2.3?

**Comment by geuss** [comment]
Hi uslss. No, the contextual menu changed... and the new feature "Copy as SQL" is working correctly.

Thanks

**Comment by george175** [comment]
copy as sql works, but we use to have the option to generate sql for
update, delete and insert .
Now all we have is copy as sql which generates only insert.

We cannot have the other options anymore ?

On Fri, Oct 25, 2019 at 6:21 AM geuss <notifications@github.com> wrote:

> Hi uslss. No, the contextual menu changed... and the new feature "Copy as
> SQL" is working correctly.
>
> Thanks
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dbeaver_dbeaver_issues_2796-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAIO3OXI2NAQIZA4GY77TD5LQQLCCTA5CNFSM4EMA2WV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECH5GQA-23issuecomment-2D546296640&d=DwMCaQ&c=7f1YSuqIGbgL_Gzm5POfng&r=JRCCeEX1QT3HhTaPuUit7pMBNHH8xB3YZMFwZDVCH8g&m=NS79KMwZJXQiwP17p4ITelSd1JH5XarNSSl1QhaBuOQ&s=4EAQEMDr8dWsBEJFAVF5QXCXWfTTz16-F1eM7vbW6LY&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIO3OXPFPULHLWLYNWH4IALQQLCCTANCNFSM4EMA2WVQ&d=DwMCaQ&c=7f1YSuqIGbgL_Gzm5POfng&r=JRCCeEX1QT3HhTaPuUit7pMBNHH8xB3YZMFwZDVCH8g&m=NS79KMwZJXQiwP17p4ITelSd1JH5XarNSSl1QhaBuOQ&s=BRfl4ZlXIHsIkSFnO_qCqn6sQN3ib-y36PGkseVOE6Y&e=>
> .
>


-- 


*Thank you,*

*George Daoud*

Engineer-Systems Lead.-IS Customer Service & Distribution Systems
Shaw Industries Inc
900 VD Parrott Jr Pkwy.
Dalton, GA 30721

Email:  George.Daoud@shawinc.com
Office:  706-532-3259
Mobile: 423-580-7850

-- 
**********************************************************
Privileged 
and/or confidential information may be contained in this message. If you 
are not the addressee indicated in this message (or are not responsible for 
delivery of this message to that person), you may not copy or deliver this 
message to anyone. In such case, you should destroy this message and notify 
the sender by reply e-mail.
If you or your employer do not consent to 
Internet e-mail for messages of this kind, please advise the sender.
Shaw 
Industries does not provide or endorse any opinions, conclusions or other 
information in this message that do not relate to the official business of 
the company or its subsidiaries.

**********************************************************

**Comment by george175** [comment]
I noticed that if I have multiple records returned, and I select all
records then the "generate sql" option will show up in the context menu

ut if I select 1 line , I cannot see the generate sql option

On Fri, Oct 25, 2019 at 7:20 AM George Daoud <george.daoud@shawinc.com>
wrote:

> copy as sql works, but we use to have the option to generate sql for
> update, delete and insert .
> Now all we have is copy as sql which generates only insert.
>
> We cannot have the other options anymore ?
>
> On Fri, Oct 25, 2019 at 6:21 AM geuss <notifications@github.com> wrote:
>
>> Hi uslss. No, the contextual menu changed... and the new feature "Copy as
>> SQL" is working correctly.
>>
>> Thanks
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dbeaver_dbeaver_issues_2796-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAIO3OXI2NAQIZA4GY77TD5LQQLCCTA5CNFSM4EMA2WV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECH5GQA-23issuecomment-2D546296640&d=DwMCaQ&c=7f1YSuqIGbgL_Gzm5POfng&r=JRCCeEX1QT3HhTaPuUit7pMBNHH8xB3YZMFwZDVCH8g&m=NS79KMwZJXQiwP17p4ITelSd1JH5XarNSSl1QhaBuOQ&s=4EAQEMDr8dWsBEJFAVF5QXCXWfTTz16-F1eM7vbW6LY&e=>,
>> or unsubscribe
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIO3OXPFPULHLWLYNWH4IALQQLCCTANCNFSM4EMA2WVQ&d=DwMCaQ&c=7f1YSuqIGbgL_Gzm5POfng&r=JRCCeEX1QT3HhTaPuUit7pMBNHH8xB3YZMFwZDVCH8g&m=NS79KMwZJXQiwP17p4ITelSd1JH5XarNSSl1QhaBuOQ&s=BRfl4ZlXIHsIkSFnO_qCqn6sQN3ib-y36PGkseVOE6Y&e=>
>> .
>>
>
>
> --
>
>
> *Thank you,*
>
> *George Daoud*
>
> Engineer-Systems Lead.-IS Customer Service & Distribution Systems
> Shaw Industries Inc
> 900 VD Parrott Jr Pkwy.
> Dalton, GA 30721
>
> Email:  George.Daoud@shawinc.com
> Office:  706-532-3259
> Mobile: 423-580-7850
>


-- 


*Thank you,*

*George Daoud*

Engineer-Systems Lead.-IS Customer Service & Distribution Systems
Shaw Industries Inc
900 VD Parrott Jr Pkwy.
Dalton, GA 30721

Email:  George.Daoud@shawinc.com
Office:  706-532-3259
Mobile: 423-580-7850

-- 
**********************************************************
Privileged 
and/or confidential information may be contained in this message. If you 
are not the addressee indicated in this message (or are not responsible for 
delivery of this message to that person), you may not copy or deliver this 
message to anyone. In such case, you should destroy this message and notify 
the sender by reply e-mail.
If you or your employer do not consent to 
Internet e-mail for messages of this kind, please advise the sender.
Shaw 
Industries does not provide or endorse any opinions, conclusions or other 
information in this message that do not relate to the official business of 
the company or its subsidiaries.

**********************************************************
