### ISSUE TITLE
Keyword highlight for PostgreSQL misses word LANGUAGE

### ISSUE THREAD

**Issue by tkitynski** [dbeaver/dbeaver#2800]
In a code like:
```sql
CREATE OR REPLACE FUNCTION foo() RETURNS int AS $$
BEGIN
    RETURN 1;
END;
$$ LANGUAGE plpgsql
```
the keyword `LANGUAGE` at the end is not highlighted. It concerns Eclipse plug-in (4.3.2) and DBeaver standalone (also 4.3.2).

PS I've just switched from pgAdmin4 to DBeaver and I'm in love with it! ;-)

**Comment by AndrewKhitrin** [comment]
Thanks for your report and interest in the project. I've added LANGUAGE and any other keywords.

PR #2802   All checks have passed wait for review.

**Comment by tkitynski** [comment]
Wow, that was fast! Thanks!
