### ISSUE TITLE
Problem with Data Navigator and Teradata 16

### ISSUE THREAD

**Issue by bochkarevnv** [dbeaver/dbeaver#2801]
When I try to see columns of view on new version of Teradata (16.10) I get error related with another view. I track SQL query and see something like:
`select  some fields
from Dbc.TablesV t
join Dbc.ColumnsJQV c on t.DatabaseName=c.DatabaseName and t.TableName=c.TableName
where t.DatabaseName like 'dbname' and t.TableName like 'tablename'`.

It is problem, because Dbc.ColumnsJQV contains information about all views and if someone was broken or not allowed, query without predicate return error.

**Comment by serge-rider** [comment]
Well, DBeaver doesn't execute such queries. 
Perhaps they are initiated by Teradata JDBC driver.
In any case I can't realize what we can do from DBeaver side..

**Comment by bochkarevnv** [comment]
Ok, can you help me understand.
DBeaver use JDBC Driver getColumns?

**Comment by serge-rider** [comment]
Yes, for Teradata it uses DatabaseMetaData.getColumns() function.
