### ISSUE TITLE
Prevent restoring editor

### ISSUE THREAD

**Issue by hernandev** [dbeaver/dbeaver#2803]
Even with both options related to reopen on restart, editor tabs even If empty will always show up after closing and opening DBeaver.

Only way so far is closing all tabs and them closing DBeaver.

Is there a way to start fresh / empty like any other app?

thanks!

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/35296805-42e896b6-008e-11e8-8d39-e8f22d83b892.png)

**Comment by hernandev** [comment]
Yes, that's unchecked and they are being restored, actually, checking or unchecking it has no effects

**Comment by serge-rider** [comment]
This option affects only database object editors (like tables ,schemas, etc) and only new opened editors. 
Ie after changing this option you need to close all already opened editors. All new editors won't restore next time.

**Comment by hernandev** [comment]
So is there an option to avoid restoring SQL editors?

**Comment by serge-rider** [comment]
No, there is no such option. It is the default behavior of all Eclipse-based IDEs.
Potentially it is possible to add such option.

Just curious - why do you need this?  Why keeping last opened editor after restart is bad?
You can disable automatic database connect if it bothers you.

**Comment by Otiel** [comment]
I'd like to see such an option in order to be able to start with a fresh workspace.

**Comment by puyt** [comment]
I'd like an option for this too, I have multiple docker instances running during the day but when I open up DBeaver the next day all my tabs from the day before are still there because I just shutdown my computer.

The next day my active connections could be totally different and I have to click "ignore error" for a lot of tabs.. So starting with a fresh workspace would be nice indeed.

**Comment by serge-rider** [comment]
As a workaround you can start DBeaver with command line parameter -closeTabs (see https://github.com/dbeaver/dbeaver/wiki/Command-Line).

**Comment by puyt** [comment]
@serge-rider Oh great! Thanks
