### ISSUE TITLE
Problem of executing sql when one execution is hang on postgresql

### ISSUE THREAD

**Issue by highgozhangyc** [dbeaver/dbeaver#2807]
Hi,
I had a problem of execution sql when one execution is hang on postgresql.
The below is the process of my testing.
**I made a lock on postgresql by psql like this:**
postgres=# begin;
BEGIN
postgres=# update test_tab1 set col1 =102 where col1=101;
UPDATE 1
postgres=# 
**Then,i opened an sql editor on dbeaver,and execute this sql:**
update test_tab1 set col1 =102 where col1=101;
this execution was hang.
**Last,i opened another sql editor on dbeaver,and execute an other sql,like this:**
select * from pg_class;(or some other sql).
this execution was also hang.

So,the question is why the last execution was hang?
I gussed these two sql editor was using the same connection(or session),so when the first sql editor was hang,the second sql editor was also hang.
So ,i thought that is a bug, how do you think?

Thanks.

**Comment by serge-rider** [comment]
Maybe it is a bug. You can check Query Manager to see what exactly query is hanging (you can enable all query types in QM preferences).
Maybe it is some system catalog querying..

**Comment by zhangyc145** [comment]
Thanks for your reply.
I enabled all query types in QM preferences and check Query Manager, i found there was only the two query was executing,the result :
![default](https://user-images.githubusercontent.com/22016800/35376593-ba7ad38e-01e6-11e8-9d2e-50313480e9bc.png)
There were no other query was executing, it was the two query hang it.So i think this is a bug.

**Comment by highgozhangyc** [comment]
Hi,
@serge-rider Can you checkout this problem?
Thanks!

**Comment by serge-rider** [comment]
@highgozhangyc sorry for delay.
So dis you realize what was wrong and why it hanged? Found any workaround?
