### ISSUE TITLE
Cant Edit field on a result set

### ISSUE THREAD

**Issue by aeperez94** [dbeaver/dbeaver#2808]
![image](https://user-images.githubusercontent.com/12971632/35114666-457616b6-fc64-11e7-8551-4a3d0806016d.png)
Oracle database
Cant edit fields on a query result. i can select the field and it allows me to "edit" but i cant type and i hear an error sound.
how can i edit the field right of the UI instead of writing an Update statement?
Thanks

**Comment by serge-rider** [comment]
For some reason DBeaver can't find table referenced in your query in metadata catalog.
Workaround: try to specify table schema explicitly.
Also you can find and open this table thru database navigator and edit data in "Data" tab.

Hint: to find a table press <kbd>ctrl+shift+d</kbd> and type part of table name.

**Comment by PavolGanzarcik** [comment]
I have the same problem with Oracle.
If it helps, it works correctly in the 4.1.2 version for the same project and settings.

**Comment by serge-rider** [comment]
I can't reproduce this. Perhaps it was fixed along with other bugs.
Please check this in 4.3.4 (release on Feb 4)

**Comment by PavolGanzarcik** [comment]
I have the 4.3.4 version and it does not work. Is there any information that would be useful to help you to reproduce it?

**Comment by aeperez94** [comment]
Sorry for late answer. It indeed worked when i set the correct schema.
Thanks! awesome software
