### ISSUE TITLE
Failure When modifying permissions for users with "-" in name PostgreSQL

### ISSUE THREAD

**Issue by joseph-bradfield** [dbeaver/dbeaver#2816]
For PostgreSQL
When modifying permissions for users/groups with "-" in name the persist changes will fail and there is no method to add double-quotes

as a work-around the sql can be copied to a new window , modified and ran.

> SQL Error [42601]: ERROR: syntax error at or near "-"

**Comment by serge-rider** [comment]
It is a bug in permission manager.
Thanks for report!
