### ISSUE TITLE
Permissions granted to groups are not visible in PostgreSQL from table view

### ISSUE THREAD

**Issue by joseph-bradfield** [dbeaver/dbeaver#2817]
***Version 4.3.2***
When navigating to
`DB->Schemas->schema_name->Tables->table_name` Properties Tab->Permissions 
when I click on a Group name, none of the granted permissions are visible
likewise none of the permissions are visible for members of that group

The only method I have found to view the roles is to navigate to 
`DB->Roles->group_name Properties tab->Permissions` then find the table name

Recommend that we be able to see which permissions are inherited from groups from the table->properties->permissions

**Comment by serge-rider** [comment]
This problem happens only with unquoted user names (similar to ticket #2816).
Thanks for report
