### ISSUE TITLE
Automatically update DBeaver

### ISSUE THREAD

**Issue by guisantana0** [dbeaver/dbeaver#2818]
When the software are out of date, on the new features dialog, add a button to download Dbeaver from the links where is showed on the https://dbeaver.jkiss.org/download/, then install the same on the system

**Comment by ybelov-modus** [comment]
1+ year and we still have to manually update. It is terrible UX. :disappointed:

**Comment by serge-rider** [comment]
Going to add some automation in 6.1.5.
We'll initiate new version download automatically.

Works fine for Windows and Mac but I can't realize how to determine correct Linux distro (deb vs rpm). 
Will download deb by default (it can make some CentOS/RedHat users quite angry).
Any ideas?

**Comment by p91paul** [comment]
running "which dpkg" can be a good way to test if the system is deb-based

**Comment by LeoLozes** [comment]
Just to point out that if you're using Windows and [Chocolatey](https://chocolatey.org/), you can use it to automatically update DBeaver typing `choco update dbeaver` in cmd / powershell. It makes all the updating process that much easier.

**Comment by uslss** [comment]
verified.
tested on win and ubuntu
