### ISSUE TITLE
DBeaver does not recognize sql script files from MySQL Workbench

### ISSUE THREAD

**Issue by pollaloca** [dbeaver/dbeaver#2821]
DBeaver doesn't recognize the SQL script files that i have created with MySQL Workbench. In order to use them i have to paste the content of those files in a new "SQL Editor" in DBeaver and save them.

Sice i have my scripts in a pendrive that i use to move between home and work it's a bit unconvenient.

**Comment by serge-rider** [comment]
Did you resolve this?

It is not clear what do you mean under "not recognize".
