### ISSUE TITLE
Missing highlight for some plpgsql keywords in PostgreSQL editor

### ISSUE THREAD

**Issue by tkitynski** [dbeaver/dbeaver#2822]
In the code:
```sql
CREATE FUNCTION sum(int[]) RETURNS int8 AS $$
DECLARE
  s int8 := 0;
  x int;
BEGIN
  FOREACH x IN ARRAY $1
  LOOP
    s := s + x;
  END LOOP;
  RETURN s;
END;
$$ LANGUAGE plpgsql;
````
keywords `FOREACH` and `LOOP` are not highlighted. See [PostgreSQL docs on Looping Through Arrays](https://www.postgresql.org/docs/9.2/static/plpgsql-control-structures.html).

**Comment by serge-rider** [comment]
Thanks for report
