### ISSUE TITLE
Sql console execute error when the script exist "delimiter ;;"

### ISSUE THREAD

**Issue by stormsen** [dbeaver/dbeaver#28236]
### Description

When I execute the script for creating procedure and use "delimester;;", a syntax error is thrown.

### DBeaver Version

24.0.2.202404071654

### Operating System

windows 10

### Database and driver

1.Database name and version: 5.7.44; 
2.Driver: MySQL 5 Binaries;       5.5.62

### Steps to reproduce

When I execute the script for creating procedure and use "delimester;;", a syntax error is thrown as below：
![Snipaste_2024-04-28_11-25-35](https://github.com/dbeaver/dbeaver/assets/18321034/73aad81d-0f5b-4ce4-b6cf-d9d4c55c805a)

**Comment by stormsen** [comment]
If I replace ";;" to "$$", the execution is ok. 
Please fix it.

**Comment by stormsen** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/18321034/39a42453-b69c-486f-ae8d-7ba5a2a15190)

**Comment by E1izabeth** [comment]
Could you try Early Access version https://dbeaver.io/files/ea/ ? It's possible, that it has been already fixed.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
