### ISSUE TITLE
Short-hand type names in Postgre? 

### ISSUE THREAD

**Issue by chriseaton** [dbeaver/dbeaver#2824]
Not sure if this is already in the preferences or not... When working w/ Postgre, I prefer to use shorthand variable type names, for example:

INT4 instead of INTEGER  
VARCHAR instead of CHARACTER VARYING  
TIMESTAMPTZ instead of TIMESTAMP WITH TIME ZONE  

Is there a way I can ensure the SQL output uses these short names? Right now it always converts it to the long-hand name, even after saving with short-hand.

**Comment by serge-rider** [comment]
Agreed, this makes sense

**Comment by serge-rider** [comment]
Although we still can't break PostgreSQL naming rules. According to https://www.postgresql.org/docs/9.2/static/datatype.html INT4 is an alias while real type name should be INTEGER.
From the other hand type names like "CHARACTER VARYING" or "TIMESTAMP WITH TIME ZONE" are too long.

Yet another problem that pg_catalog keeps short forms of type names (at least for PG 9.x+) and this conflicts with documentation (see above).

Kind of a mess. But we can make this configurable..
