### ISSUE TITLE
before 24.0 it was portable

### ISSUE THREAD

**Issue by Yigitttttttt** [dbeaver/dbeaver#28259]
Hi,

we're using Dbeaver in a virtual maschine, bcoz of this we need to have a portable version (the network is closed we just put Dbeaver folder) before 24.0 version it was so and the life was easy. after version 24.0 Office etc. addins saving in folder users/dbeaverdata/instal-data or something like this.. it makes harder using the Dbeaver portable. Please could you do like before this feature.

Thank you
(sorry for my English)

**Comment by ShadelessFox** [comment]
It was always like this. DBeaver stores its data inside the `%APPDATA%\DBeaverData` folder. Was it different for you? What distribution do you use?

**Comment by Yigitttttttt** [comment]
After 24.0 its creating a folder install-data and saves there office and
svg plugins. İt wasnt so before

Thanks for reply

29 Nis 2024 Pzt 02:20 tarihinde ShadelessFox ***@***.***>
şunu yazdı:

**Comment by ShadelessFox** [comment]
Previously, it would store data from this directory in your user home directory. Now, it's unified, and all DBeaver-related data is stored in one place.

**Comment by Yigitttttttt** [comment]
But with this change we cant use it portable right now. Before we moved
only c:/dbeaver folder to other computer and plugins was working
succesfully. Now it s not..

29 Nis 2024 Pzt 02:27 tarihinde ShadelessFox ***@***.***>
şunu yazdı:

**Comment by ShadelessFox** [comment]
Now I understand what you're talking about. Thanks for the report.

**Comment by ShadelessFox** [comment]
You can workaround this issue by adding the following line to the end of the `dbeaver.ini` file:
```bash
-Dosgi.configuration.area=.\configuration
```

Please let me know it it helps.

**Comment by Yigitttttttt** [comment]
It doesnt work. I get this error. (I sent as at attachment)

29 Nis 2024 Pzt 13:12 tarihinde ShadelessFox ***@***.***>
şunu yazdı:

**Comment by ShadelessFox** [comment]
You can't attach files by email. Please reply directly on GitHub.

**Comment by Yigitttttttt** [comment]
![20240429_134709](https://github.com/dbeaver/dbeaver/assets/168306503/78e0d707-12b4-4b4b-94b1-74825a34c0d1)
![20240429_134709](https://github.com/dbeaver/dbeaver/assets/168306503/1edf532d-abf9-435c-866b-4733e1ced5d6)

**Comment by ShadelessFox** [comment]
Try reinstalling DBeaver and do this https://github.com/dbeaver/dbeaver/issues/28259#issuecomment-2082348992 before even launching it.

**Comment by Yigitttttttt** [comment]
Nothing changed still i got same message :(

29 Nis 2024 Pzt 15:35 tarihinde ShadelessFox ***@***.***>
şunu yazdı:

**Comment by serjiokov** [comment]
Hello @Yigitttttttt, first thanks for your request, but I see here mixed issues: 
1) Portable product version ( location of configuration should be in the same location for the zipped product version)
2) Additional plugin installation, There are no clear steps for reproducing.

**Comment by Yigitttttttt** [comment]
Can we make it what it was in the previous versions to solve the problem?

7 May 2024 Sal 14:39 tarihinde Sergei Kovalchuk ***@***.***>
şunu yazdı:

**Comment by ShadelessFox** [comment]
It's a little more complicated.

**Comment by Yigitttttttt** [comment]
Now we can no longer use the new versions...

7 May 2024 Sal 14:53 tarihinde ShadelessFox ***@***.***> şunu
yazdı:

**Comment by ShadelessFox** [comment]
This ticket is scheduled for the current milestone. The fix will be available in two weeks.

**Comment by Yigitttttttt** [comment]
Thank you

7 May 2024 Sal 15:06 tarihinde ShadelessFox ***@***.***> şunu
yazdı:

**Comment by Yigitttttttt** [comment]
I have another urgent problem, is it possible to get it done in two weeks?
https://github.com/dbeaver/dbeaver/issues/29306
