### ISSUE TITLE
SQL Editor syntax coloring

### ISSUE THREAD

**Issue by paveless** [dbeaver/dbeaver#2829]
Hello!
This is the feature request.
It would be nice to support standard eclipse syntax coloring for sql editor.
When adding theme from Eclipse Color Themes, SQL editor doesn't recognize it correctly.

**Comment by serge-rider** [comment]
I'm not quite sure I understand this.
What do you mean under "standard syntax coloring"?
We have coloring config in standard preferences, is something wrong with them?

![image](https://user-images.githubusercontent.com/6398845/35346348-0d965be6-0143-11e8-84e1-5c0e97934d42.png)

**Comment by paveless** [comment]
I talk about standard support of http://www.eclipsecolorthemes.org/ themes.
In Eclipse SQL editor color section presented in other place.
Import of Eclipse color themes don't affect sql syntax coloring, only standard editor colors.
![image](https://user-images.githubusercontent.com/9075686/35346639-da6f0d7a-0143-11e8-9462-0b92c1af42f0.png)

**Comment by sebbodes** [comment]
I would like request a more detailled coloring as well. For me as a tester, it is easier to read statements for Oracle. Toad for Mac also had own coloring for aliases, colums, tables and more (Screenshot attatched)

![image](https://user-images.githubusercontent.com/36955235/36841857-075a7ece-1d4a-11e8-8fc3-e1f8da847452.png)

**Comment by serge-rider** [comment]
Eclipse Color themes support was added in 5.1.x. Now DBeaver supports all standard ECT colors.

However I'd recommend to use Darkest Dark extension (is is much more powerful than Eclipse Color Theme). DBeaver supports it as well.
