### ISSUE TITLE
"Data transfer IO error"

### ISSUE THREAD

**Issue by JoleneEssence** [dbeaver/dbeaver#2830]
Hi there, 
I'm using dbeaver to export a set of data, the data is able to be generated however I face an issue exporting the data. It keeps showing an error message - "Data transfer IO error". Attached is an image of the error message I'm seeing. Any way to solve this?

Appreciate the help!

![image](https://user-images.githubusercontent.com/35680187/35207880-50c3f62c-ff80-11e7-9e10-3b922629ae64.png)

**Comment by serge-rider** [comment]
Please post error/debug logs (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by Xtinction** [comment]
I think this user may have done what I just did, used an illegal character in the filename. Just for posterity. Error details gave me a hint.

**Comment by AlekseyDevOps** [comment]
Изменилась сетевая папка сохранения файла, изменил папку для сохранения и это помогло!
