### ISSUE TITLE
where is the icons in the download package？

### ISSUE THREAD

**Issue by panjunle** [dbeaver/dbeaver#2832]
I want to use the icons to customize the MBP touch bar.
I download the OS X and Linux tar.gz packages,after looking in every directory and still can't find the icons. 
please HELP ME!Thank a lot!

**Comment by serge-rider** [comment]
Well, there is dbeaver.icns in Resources folder in MacOS version.
And dbeaver.png + icon.xpm in the root of Linux version.

Or do you mean something else?

**Comment by panjunle** [comment]
@serge-rider    
thanks and yes i mean something else，i don't mean the beaver icon.
i want to find the icons of buttons ,sucn as Connect   Sql Editor...

**Comment by serge-rider** [comment]
Different icons are packed in different jars. Also you find then in GitHub sources (just search for png files).
