### ISSUE TITLE
4.3.3: Windows installer doesn't ask for admin rights anymore

### ISSUE THREAD

**Issue by Otiel** [dbeaver/dbeaver#2833]
With the latest release (4.3.3), the Windows installer doesn't ask for admin rights anymore, which gives the following error:

![image](https://user-images.githubusercontent.com/3851902/35215405-6d05dbaa-ff64-11e7-88e7-55023c0292c0.png)

The workaround is to right-click → "Run as administrator".

**Comment by serge-rider** [comment]
Yes. In fact installing DBeaver in `Program Files` isn't a good idea (some functions like 3rd party extensions install won;t work in this case).
So not DBeaver default install directory is in local user home. If your previous installation was in Program Files then this may cause problems (you need to change target path manually or run it as administrator).

This is a kind of bug (perhaps installer shouldn't use install path from previous versions).
I'm not yet sure how to resolve this..

**Comment by Otiel** [comment]
Honestly I will make sure DBeaver is always installed in `Program Files` for security reason. In any other folder, it is too easy for a malware to tamper with the exe files.

I think the installer should detect if the path is in `Program Files` or not, then ask for admin rights if needed.

**Comment by serge-rider** [comment]
@Otiel good point about security.

**Comment by serge-rider** [comment]
Installer was reverted to 4.3.2 state (see 4.3.3.1 hotfix version).
