### ISSUE TITLE
Execute Statement button broken 

### ISSUE THREAD

**Issue by andywicht** [dbeaver/dbeaver#2836]
It seems the Execute Statement Button is broken. Same for the SQL Editor > Execute Statement Menu Item.
The only way to execute a statement is CTRL+Enter.

DBeaver Version 4.3.3
Postgresql Connection

**Comment by chtuqu** [comment]
+1
But Ctrl+Enter is broken too. The only way to execute a statement is when the cursor is at the semicolon which finishes the statement. Attempting to highlight the statement and execute it with the shortcut results in removing this block altogether.

**Comment by serge-rider** [comment]
What is your OS?

**Comment by chtuqu** [comment]
macOS High Sierra 10.13.2

**Comment by andywicht** [comment]
Windows 7

**Comment by serge-rider** [comment]
Could you post a screenshot or something? Debug logs also would be helpful (https://github.com/dbeaver/dbeaver/wiki/Log-files)

I can't realize how this can be broken. 
The only situation when execute is disabled is when SQL editor don't have associated connection.

**Comment by chtuqu** [comment]
The GIF pictures pressing Cmd+A to highlight all and then Ctrl+Enter to execute. Nothing is executed, the highlighted block is removed. The logs are coming.

![db-bug](https://user-images.githubusercontent.com/15345359/35230926-76a1c810-ffa8-11e7-941a-7d6667619900.gif)

**Comment by chtuqu** [comment]
I've only edited the username and the DB name.

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/1652688/dbeaver-debug.log)

**Comment by chtuqu** [comment]
[log-general.log](https://github.com/dbeaver/dbeaver/files/1652729/log-general.log)

**Comment by serge-rider** [comment]
This is a bug in SQL processor. And it is reproducible only with PostgreSQL.
Thanks for report!

I think I'll make a hotfix release of 4.3.3 today evening.

**Comment by serge-rider** [comment]
Check the fix in 4.3.3.1 (hotfix) version.

**Comment by andywicht** [comment]
great work! Thank you!
