### ISSUE TITLE
How to set the interface language to English?

### ISSUE THREAD

**Issue by a854363956** [dbeaver/dbeaver#2838]
My operating system language is Chinese, so DBeaver interface language is Chinese, but I want to change to English, how do I operate?

**Comment by a854363956** [comment]
dbeaver.ini  add  -Duser.language=en

**Comment by ygoe** [comment]
I have to redo this change after every new installation of the frequent updates. Translations just don't get better. Can't there be a saved setting for that, please?

**Comment by serge-rider** [comment]
There are a few ways:
- If you use Windows installer then you can choose language in the installer and it will be used in DBeaver
- You can run DBeaver with command line parameter "-nl en"
- You can add lines
```
-nl
en
```
in dbeaver.ini file (before -vmargs line)
- You could try to change language on Preferences->Database page. Note: it won't work if DBeaver is installed in write-protected folder and you run not under admin permissions.

**Comment by serge-rider** [comment]
In regards to translations. Yes some of them are very incomplete. Perhaps we should disable them until they become more complete. However it is quite controversial. Some people still prefer them because of poor English knowledge.

**Comment by ygoe** [comment]
Now I don't know how many bugs I've just discovered. The app is installed in my LocalAppData (Windows), so not write-protected. Yet the language setting isn't working. Then I've already found the "-nl en" part (two lines) in my ini file before "-vmargs". Also not working.

Finally, reinstalling with the language set in the installer to English, the application UI is also in English. The parts you mentioned have disappeared from the ini file though. I'm not sure where the current language preference is now stored but it is effective where it is. All others are not.

**Comment by serge-rider** [comment]
Installing with English language just adds "-nl en" parameter to the DBeaver shortcut. So this also works.

If you have installed DBeaver with German language chosen in installer then changing dbeaver.ini won't help, as well as changing it in preferences.  You can only modify the Windows shortcut or reinstall DBeaver with another language.

**Comment by hawktien** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/795866/a5601744-b6c0-49a4-b7fe-61475c65834c)
在 Windows 10 安装 DBeaver [ version 24.0.1 ] 完毕后，
软件在桌面创建了快捷方式，其指向的目标是：
C:\Users\hawk\AppData\Local\DBeaver\dbeaver.exe -nl zh
可以看到，exe后面指定了和操作系统相同的语言，
导致启动后修改设置中的语言无效，
解决办法：
打开桌面快捷方式的属性，删除目标后面的 -nl zh 即可。

**Comment by cornguo** [comment]
Just a reminder, for Microsoft Store version it is not possible to change dbeaver.ini.
After some search I've found following pages explains how to use config.ini to override settings.

https://dbeaver.com/docs/dbeaver/How-to-set-a-variable-if-dbeaver.ini-is-read-only/
