### ISSUE TITLE
DBeaver 4.3.3 Query execution issue

### ISSUE THREAD

**Issue by sandeepsoftengg** [dbeaver/dbeaver#2839]
In 4.3.3, When we hit ctrl+enter on the selected queries, then the selection is overwritten with a blank line. 
In the earlier version, it was executing the selection with ctrl+enter. Can you fix this in your new release?

**Comment by serge-rider** [comment]
Do you use PostgreSQL? Is it the same as #2836 ?
If so then just re-download (now 4.3.3.1 is the most recent version).
