### ISSUE TITLE
PostgreSQL - functions autocompletion over multiple schemas

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#2841]
Hi,

PostgreSQL 9.6
DBeaver 4.3.3.1 (Linux 64 .deb version)

When I try to perform a completion of a function name with ctrl + space, if the function is in another schema than the "public" schema, nothing is displayed, since the function exists.
Only tables in "public" schema are displayed if I type the function name .

I don't remember precisely if it used to work in prior versions or not, but I think it did.

Regards,

Cedric

**Comment by andywicht** [comment]
Try including the schema where your function is located in your search_path. For me this seems to work!

**Comment by ced75** [comment]
Thanks for your answer.
Unfortunately, for me, it doesn't work, even if I include the schema name in my search_path.

**Comment by serge-rider** [comment]
Perhaps you should enable global object search:
![image](https://user-images.githubusercontent.com/6398845/35490362-3353dd0c-04b0-11e8-9f31-057663f9573b.png)

**Comment by ced75** [comment]
Yes, with this option checked, it works.
Thanks for your help.

**Comment by sqlpro20** [comment]
Hi,

in my current setup, this does not work - whether I activate global search or not. It only finds tables of one schema. Autocompletion does work if I start with <schemaname>. (CTRL +Space). However, I don't know the schema name for every object. Can someone give a hint? Might something like cache invalidation in DBeaver help?

My current setup:
Dbeaver 6.04
Windows
Postgres 9.3 /JDBC driver 42.2.0
