### ISSUE TITLE
Bug generating procedures source in Firebird

### ISSUE THREAD

**Issue by icaromarlon** [dbeaver/dbeaver#2842]
I have found an important bug generating procedures source in Firebird databases. When you do this the input and output parameters are generated with their original basic types when you are using domains.

Example:
I have a domain called T_MOEDA as DOUBLE(15,2) and when I generate the procedure source it came as DOUBLE, if I compile this source the procedure's input and output will be now as DOUBLE but without the precision and sub type, it means that is the same as INT.

**Comment by serge-rider** [comment]
What is your Firebird server and client driver version?
Generally DBeaver takes procedure source from driver which in its turn executes 
```sql
Select RDB$PROCEDURE_SOURCE From RDB$PROCEDURES Where RDB$PROCEDURE_NAME = ?
```
So, looks like this is taken from FB server. Do you have any thoughts how to fix this?

**Comment by serge-rider** [comment]
Seems to be non-DBeaver issue anyway.
