### ISSUE TITLE
Exception at click on uuid foreign key link

### ISSUE THREAD

**Issue by rcguerrra** [dbeaver/dbeaver#2844]
Follow the printscreen showing the exception.
https://drive.google.com/file/d/1sI1jbgatA2nq2Zz__Jc_p5fyteXFE9_A/view?usp=sharing

**Comment by serge-rider** [comment]
Is this SQLite? 
Is this some extension for UUIDs native support?
Anyhow - could you post table DDL and some sample INSERTs to let me reproduce this on test environment.

Thanks for report.

**Comment by uslss** [comment]
There is no update on ticket more than a year. 
Ticket is closed.
If issue is still reproducible for you, feel free to reopen the ticket.
