### ISSUE TITLE
User Defined Drivers

### ISSUE THREAD

**Issue by rltheis27** [dbeaver/dbeaver#2846]
Hello,
  I copied some database drivers into a new category I called MyDrivers. I modified the drivers under MyDrivers for my local environment. For example, changing the default port number. Where are the MyDrivers drivers saved? I looked under .dbeaver4 and .dbeaver-drivers fold and cannot find them. 

  I want to share the modified drivers with a co-worker. I was hoping all I had to do was copy a jar file or directory to my co-workers DBeaver directory structure.

Thank you, 
    Richard

**Comment by serge-rider** [comment]
Drivers definition resides in `.metadata/.plugins/org.jkiss.dbeaver.core/drivers.xml` file in DBeaver workspace. E.g.:
`C:\Users\USER\.dbeaver4\.metadata\.plugins\org.jkiss.dbeaver.core\drivers.xml`

Custom drivers have attribute `custom="true"`

**Comment by rltheis27** [comment]
Thank you.
