### ISSUE TITLE
Federated Queries

### ISSUE THREAD

**Issue by rltheis27** [dbeaver/dbeaver#2848]
Hello,
  I've been searching the Internet to see if DBeaver can be configured to perform a federated query. I found, https://www.linkedin.com/pulse/unified-access-geodegreenplum-christian-tzolov, showing a JSON document with a federated connection. I created a simple JSON federated connection and could not figure out how to import the JSON file. Is this a valid way of creating a federated connection? Can DBeaver be configured to perform a federated query? My approach would be to create a wrapper driver that includes the appropriate drivers (i.e. Oracle and Sybase). 

  If DBeaver cannot perform federated searches, is this on a future feature list?

Thank you,
  Richard

**Comment by serge-rider** [comment]
No, currently DBeaver doesn't support this out of the box.
We have FR #1804 for this exactly feature. 

Until then you could try to use some existing composite (federated) JDBC driver. As far as I know there are a few commercial ones.

**Comment by rltheis27** [comment]
Thank you. Do you have an estimated time frame for when this feature will be included?

**Comment by serge-rider** [comment]
No, there is no time frame for it. It is not in the list of first priority features :(
Once we'll have some free resources. 

I personally want this feature very much. But people vote for others.
