### ISSUE TITLE
Fetching all rows results in "Error executing query"

### ISSUE THREAD

**Issue by PicusViridis** [dbeaver/dbeaver#2849]
Hello,
Since v4.3.2, clicking on "fetch all rows" button results in "Error executing query" :
![image](https://user-images.githubusercontent.com/4224278/35291966-4fe702ae-006f-11e8-9be1-c99ba28224f0.png)
v4.3.1 is working well.
This error can be seen on both Windows 7 and Windows 10 systems.
Thank you,
Sara.

**Comment by serge-rider** [comment]
Thanks for report

**Comment by PicusViridis** [comment]
Thank you!
