### ISSUE TITLE
Generate SQL/ JOIN statement clicked on a diagram(ER diagram of subset of tables)

### ISSUE THREAD

**Issue by gajoseph** [dbeaver/dbeaver#2850]
Will be really nice if there is a option that could be added to generate SQL query(JOIN codition) when a user clicks on a diagram(ER diagram of subset of tables) 

After a user has picked a table from DB navigator window; from the diagram layout there could be an option to generate the select statement/ at least a **FROM** statement with **JOIN Clause** condition to associated **Foreign Key** tables.
1) so in a given case scenario a user picks a table from DB navigator window. the Diagram with links to other table/s are displayed
2) when the user right click on the diagram app can easily generate the **SQL/ JOIN** condition as the app already know the link/s to other tables (for example: tab1 has 2 FKS; one to tab2 and another tab2;  which is displayed in the diagram). Based on that info generate SQL JOIN condition. It will be really useful as user do not have to manually write the SQL(SELECT statement )
3) if there are 2 fks to same table alias them accordingly 

please let me know 

Thanks,
George (DBA )

**Comment by serge-rider** [comment]
Sounds like a good feature for me.

**Comment by serge-rider** [comment]
And this correlates with #397

**Comment by serge-rider** [comment]
In fact this feature is much more complicated then you described (because of complex nature of SQL joins).
I've added simple inner join generator (by foreign keys and by matched column names).
It works from table list and from ER diagrams. You need to select tables you want to join and then Generate SQL->JOIN.

Please check this in EA version (https://dbeaver.jkiss.org/files/ea/)

**Comment by gajoseph** [comment]
Thanks! Agreed. 
somehow have to recursively pull the foreign keys for each table. 
I would say putting Left outer join (unless FK is not null ) might be better  inner join...just a suggestion
