### ISSUE TITLE
AutoComplate works better on 4.2 than 4.3++

### ISSUE THREAD

**Issue by tranbaohuu** [dbeaver/dbeaver#2851]
Dear Technical
   I already update to the latest version 4.3.3 but the issue is still same. AutoComplate code won't to show on the latest version and Grid of Result after selected unable to edit directly on. I have to re-install to version 4.2 and everything work as well. Thank for your help in the future.

+Below were attached of features in version 4.2

![dbeaver_2018-01-24_09-39-13](https://user-images.githubusercontent.com/10123641/35311857-55b9799c-00eb-11e8-98c4-9219f1e1335e.png)
![dbeaver_2018-01-24_09-38-57](https://user-images.githubusercontent.com/10123641/35311858-55e89204-00eb-11e8-8df8-4e10b6a02520.png)

**Comment by tranbaohuu** [comment]
Addition information: I'm using SQL Server 2000 and 2005 with both drivers jTDS and SQL Server Driver

**Comment by serge-rider** [comment]
Could you clarify a bit - what is actually wrong in 4.3+ version? It doesn't work at all or some completion feature was broken?
And please attach debug logs, it greatly helps to discover the original problem (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by tranbaohuu** [comment]
Dear Technical
+The problem happen from version 4.3. to latest. I just send to you pictures AutoComplete command feature on Version 4.2.6 and 4.3.3.1 . You can see I want to Select table Invoice then on version 4.2.6 it's worked and can't on 4.3.3.1. 

![dbeaver_2018-01-26_13-58-53](https://user-images.githubusercontent.com/10123641/35428709-263e9166-02a3-11e8-9217-63acab02e276.png)
![dbeaver_2018-01-26_13-56-23](https://user-images.githubusercontent.com/10123641/35428710-266aad96-02a3-11e8-8ba0-b3ca86f6b6c5.png)

![dbeaver_2018-01-26_14-01-38](https://user-images.githubusercontent.com/10123641/35428714-2bc7d16a-02a3-11e8-8a86-c58b45ae46af.png)
![dbeaver_2018-01-26_14-01-30](https://user-images.githubusercontent.com/10123641/35428715-2bf55b94-02a3-11e8-8b59-a1f9d1621583.png)




+One more thing is i can't edit directly on the grid of result after i select.
E.g: Select * from dbo.Invoices -> I will have a grid of result -> On version 4.2.6 I can double click on a cell of record then typing anything i want  and press save. But on 4.3.3.1 i can't do it again.

![dbeaver_2018-01-26_13-57-45](https://user-images.githubusercontent.com/10123641/35428725-349311c4-02a3-11e8-8799-7b121f7330a1.png)


+I don't know is it bug from Application or jTDS Driver. I tried rollback to version 4.2.6 and used driver jTDS to connect SQL Database but the feature Edit Directly  did not work.

+But when i connect to Sql Database use jdbc:sqlserver the feature Edit Directly work as well.
![dbeaver_2018-01-26_13-58-23](https://user-images.githubusercontent.com/10123641/35428730-3cced8e6-02a3-11e8-9553-cec63d5ad92f.png)

**Comment by serge-rider** [comment]
Looks like some problem with metadata read in SQL Server extension. Problems with auto-complete and cell editor are just side effects.
Could you please post debug log (instruction: https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by serge-rider** [comment]
And I think this is the same problem as in #2870

**Comment by tranbaohuu** [comment]
These is log files that you want.

[.log](https://github.com/dbeaver/dbeaver/files/1669600/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/1669601/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Thanks for details. Indeed the problem is in schema read error.
Please check how it works in EA version (https://dbeaver.jkiss.org/files/ea/)

**Comment by tranbaohuu** [comment]
Dear Technical
-After updated the EA version 4.3.3.1, Both of features work is OK. Thank for your support.

+But I have a question I don't know should i need to create a new article or not.

+I send to you 2 images about Select in a table between DBeaver 4.3.3.1 and SQL Server Management Studio 2017 v17.2

![dbeaver_2018-01-29_13-53-16](https://user-images.githubusercontent.com/10123641/35497386-92985b5c-04fc-11e8-97d4-36475cd26ccf.png)

There is record for DBeaver 4.3.3.1

![ssms_2018-01-29_13-54-23](https://user-images.githubusercontent.com/10123641/35497401-9d752b4a-04fc-11e8-9216-16df8abe0fb7.png)

There are 5 records for SQL Management Studio 2017 V17.2

And log files

[.log](https://github.com/dbeaver/dbeaver/files/1672536/default.log)

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/1672537/dbeaver-debug.log)

Regards

**Comment by serge-rider** [comment]
Thanks for info.
Is is definitely makes sense to create a separate ticket for that.
