### ISSUE TITLE
Postgres: sql export in windows environment

### ISSUE THREAD

**Issue by simonedelmonte92** [dbeaver/dbeaver#2853]
Hello,
there is an issue exporting the database as sql inserts if you run DBeaver on a Windows. The postgres native types (json objects and json arrays) are exported in the wrong way: they are not surroundend by single quotes (plus single quotes that are inside the object/array are not escaped).

**Comment by serge-rider** [comment]
Can't reproduce (JSON column must be escaped properly).
What is your DBeaver version and what PostgreSQL driver do you use?

**Comment by simonedelmonte92** [comment]
Your question gave me an hint to solve the problem on my own :)
I was using the wrong PostgresSQL driver, the one labeled as "Postgres generic" in the DBeaver driver list, that is the one to use for the version of PostgresSQL server 8.x or older. Using the other PostgresSQL driver available in DBeaver list, the export is correct :)
