### ISSUE TITLE
If connection with Windows Authentication is used, then there is no need to shown a user/password dialog

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2854]
DBeaver - **Version 4.3.3.1 CE**
DBeaver JDBC driver: **Microsoft Driver 2**
Operating System: **Windows 7** / **Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

If parameter **CONNECTION SETTINGS** -> **WINDOWS AUTHENTICATION** is set to **TRUE** then parameter **GENERAL** -> **SAVE PASSWORD LOCALLY** ought to be set to **FALSE** automatically.

It does not feel logical to get a user/password dialog when I connect, if I have choosen to use windows authentication.

**Comment by efradkin** [comment]
I disagree. When you set WINDOWS AUTHENTICATION to TRUE the user name and password aren't used. It's correct. But they are still stored in the connection settings. So when you uncheck the WINDOWS AUTHENTICATION they'll be available.

**Comment by serge-rider** [comment]
@efradkin yep, this makes sense too. You can work under some explicit user and then decide to switch to Windows auth. Then you'll need just to uncheck this option to return back to your user.
