### ISSUE TITLE
Export data from multiple queries (script)

### ISSUE THREAD

**Issue by pabs88** [dbeaver/dbeaver#2855]
Hello, I am new to Dbeaver. I have four queries (q1.sql, q2.sql, q3.sql, and q4.sql). What I am doing now is running one query, copying the result table, and pasting it into an excel file, and I repeat the process with the other queries.

Is there a way to automate the process? For example, creating an script through which I run and export everything into an .CSV file for example?

Thank you :)

**Comment by serge-rider** [comment]
No, there is no such feature yet.
You can export multiple tables but not multiple queries.

Perhaps we should make this feature request..

**Comment by pabs88** [comment]
I think it will be very useful. How can we do this request?

When you use Access, for example, you can write VBA code to automate different tasks, and even createa VB script or batch file to run everything automatically. I think a similar feature would be very useful so that once you have different queries you can run them one by one and then also automatically export the results, for example ina CSV file.

**Comment by serge-rider** [comment]
I'll make this ticket FR

**Comment by pabs88** [comment]
Thnak you!

**Comment by jbuffi** [comment]
This is so needed - I have been searching for a way to do this.

**Comment by chinul** [comment]
Any update on this request

**Comment by asheemchhetri** [comment]
Any update here folks?

**Comment by agustinfavilla** [comment]
same problem here, 
i need to export form a script. In my script first I create two tables, then i make a select from these two tables and finally i drop the two tables. any idea to make an export from this script?

**Comment by serge-rider** [comment]
Also very similar to #4972

**Comment by goxr3plus** [comment]
Yes similar please add this feature :)

**Comment by serge-rider** [comment]
This feature will be added in 5.3.4.

Just select any number of SQL queries and run "Export from query" command. 
It works like exporting from multiple tables:

![image](https://user-images.githubusercontent.com/6398845/52169548-4aa70100-274b-11e9-8fce-cb31f2325370.png)

**Comment by goxr3plus** [comment]
Excellent ❤ DBeaver is growing very fast and i think it's if not thr best,
one of thr best tools.

**Comment by goxr3plus** [comment]
I tested it in 6.1.1 and it doesn't work correctly it is producing multiple files ->

Selecting 3 tables -> Export Data -> SQL/SQL -> Write to Single File -> Next -> Finish -> I see `2` files instead of one . I need all the data in one file . 

It used to work as far as i remember 

@serge-rider
