### ISSUE TITLE
It's impossible to have both (CE and EE) version on Mac.

### ISSUE THREAD

**Issue by tati-kru** [dbeaver/dbeaver#2856]
If you install CE version to Mac it will be impossible to install EE version using the Mac installer. You need to delete CE version firstly.

**Comment by acherukuri** [comment]
@tati-kru I was able to install both CE(4.3.3.1) and EE(4.3.0) on my Mac 10.12.6 yesterday with no issues. However, I can't run them both at the same time though coz both of them are trying to use .dbeaver4 folder in the home directory at the same time and first opened app (either CE or EE) obtains a lock on that folder which prevents the other version app to access that folder.

**Comment by serge-rider** [comment]
@acherukuri I think @tati-kru meant PKG installer.

**Comment by serge-rider** [comment]
@acherukuri In order to use different workspaces you can run DBeaver with command line parameter 
-data `<path-to-workspace>`

**Comment by acherukuri** [comment]
@serge-rider thanks for the info.

**Comment by serge-rider** [comment]
Mac installer and DMG image are fixed.
