### ISSUE TITLE
 Goto Database Object <Ctrl+Shift+d> doesn't work for stored procedures

### ISSUE THREAD

**Issue by amivanovano** [dbeaver/dbeaver#2857]
It works nice for database tables, but always find the first procedure in the database regardless of my choice.

DBEaver 4.3.3.1
Informix Drivers 3.70.JC8DE, 4.10JC9DE
Windows 7

TIA,
Alex

**Comment by serge-rider** [comment]
Generally DBeaver supports search of procedures in a database. And this works for most databases.
Perhaps something is wrong with Informix driver.
Could you check error/debug logs for any details? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by super3dmax** [comment]
DB2 is the same.
SQLServer is OK.

**Comment by serge-rider** [comment]
Yep. Added routine search for DB2.

**Comment by amivanovano** [comment]
It is strange.
When I choose the procedure from the procedure list, then everything works.
Only using <Ctrl+Shift+d> matching items not works for procedures.
And it occurs in all versions of Informix driver.

**Comment by serge-rider** [comment]
These exceptions are just warnings.
It looks like Informix JDBC driver doesn't support procedures search by mask.
Potentially this can be solved by custom procedures read functions for Informix. 
But I don;t have access to a live instance of Informix to test this.
