### ISSUE TITLE
DBeaver cannot read SSL key file: extra data given to DerValue constructor

### ISSUE THREAD

**Issue by danielealfarone** [dbeaver/dbeaver#2859]
I have configured a Postgres server to accept SSL connections, generated a key for my client, but I cannot connect through DBeaver:

```
Could not read SSL key file C:\Users\Owner\Desktop\ssl\postgresql.key.
    extra data given to DerValue constructor
```

I've already looked into related issues #843 and #1063. I have tried both installing JCE unlimited strength policy manually and re-installing DBeaver with the shipped JRE, but the error remains the same.

`postgres.key` uses 2048 bit RSA, as generated by 

```
openssl genrsa -des3 -out postgresql.key
```

Any hints?

![image](https://user-images.githubusercontent.com/35766012/35330359-96299b84-0103-11e8-94d7-443af32e598b.png)

**Comment by danielealfarone** [comment]
Update: here is the full stack trace of the error
https://github.com/dbeaver/dbeaver/files/1659766/error.log

**Comment by serge-rider** [comment]
Seems to be duplicate of #1835

General solution is to convert your key into DER format:
```
openssl pkcs8 -topk8 -inform PEM -outform DER -in postgresql.key -out postgresql.pk8
```

**Comment by danielealfarone** [comment]
It worked! Thanks a lot.
And let me also take this chance to thank you for DBeaver, it's a great product :)
