### ISSUE TITLE
Compare tables from different databases (drivers)

### ISSUE THREAD

**Issue by nikitaclarion** [dbeaver/dbeaver#286]
Trying to compare metadata of 2 tables of databases-SQL Server 2008 R2 & My SQL respectively.
But its displaying message that 'Objects of different types are selected.You may compare only objects of the same type'. Please suggest.

**Comment by jiangxincode** [comment]
Yeah, I also want it.

**Comment by serge-rider** [comment]
Agreed, this would be a great feature.

**Comment by serge-rider** [comment]
Correlates with #957

**Comment by serge-rider** [comment]
Closing as duplicate of #957 (see comments)
