### ISSUE TITLE
Using the keyboard shortcut for Rollback freezes my system

### ISSUE THREAD

**Issue by mwz-cg** [dbeaver/dbeaver#2860]
I'm a happy user of DBeaver (version 4.3.3.1 for Linux 64-bit), except when I press Ctrl+Shift+Alt+R to Rollback the current transaction(s). If I do that, my entire computer freezes instantaneously.

I am on Ubuntu 17.10 on Wayland with GNOME 3.26.2. When the bug occurs, I can't even switch to a console to kill dbeaver, as the keyboard is no longer responsive. In a previous version of DBeaver, it used to be that instead memory consumption would start to increase quite fast, fast enough that I had time to kill the process. But now somehow the problem has gotten worse. Any idea about what could be causing this?

**Comment by mwz-cg** [comment]
Indeed, it appears that Ctrl+Shift+Alt+R is the default shortcut for recording video on GNOME. The weird thing is that if DBeaver is not opened, video is recorded and no freeze occurs, although memory consumption is increasing rapidly.

**Comment by serge-rider** [comment]
Ok, I'll change these shortcuts for Linux.
On e.g. <kbd>CTRL+4</kbd> and <kbd>CTRL+8</kbd> - if you have any better shortcuts on mind please tell me  (and note that most of good shortcuts are occupied by other actions).

**Comment by mwz-cg** [comment]
It seems that Alt+R for rollback, and Alt+C for commit, could work. Thanks!

**Comment by serge-rider** [comment]
By default all ALT+letter shortcuts are reserved by main menu items. E.g. <kbd>ALT+R</kbd> is for Run in Eclipse.
