### ISSUE TITLE
Restore Database appears to be mangling dump file as Unicode

### ISSUE THREAD

**Issue by AlexMax** [dbeaver/dbeaver#2863]
Whenever I try to use the Restore database functionality to restore a dump file into my MariaDB database, I get the following error message:

    ERROR 1062 (23000) at line 799: Duplicate entry '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xEF\xBF\xBD\xEF\xBF\xBD' for key 'PRIMARY'

After investigating the error, I found out that my dump file (dumped with DBeaver) did not have this sequence of bytes anywhere in the file.  The error message was pointing to a section of the file with a bunch of raw binary data.  I soon realized that **EF BF BD** is the Unicode replacement character byte sequence - �.  I then tried to import the dump file using `mysql` at the command line, and had no issues, both db server and locally using the same mysql I pointed DBeaver at.

Thus, I conclude that somewhere along the line, DBeaver is parsing my dump file as Unicode and replacing any invalid byte sequences with the replacement character.  This is not desirable - the file should be treated as binary and passed through to `mysql` untouched.

I am using the macOS version of DBeaver 4.3.3.1 and the 2.2.1 version of the MariaDB driver.  My command line tools and server are all version 10.2.12-MariaDB.  For what it's worth, the dump I was using was dumped with the same version of DBeaver a few moments earlier, and I did not find that problematic byte sequence in the file, so as far as I can tell, dumping data works just fine.

**Comment by serge-rider** [comment]
Indeed, MySQL/MariaDB db import has used text file reader (in UTF8 encoding).
I thought there was some reason for that but I can't remember what exactly..

Anyhow, now it works with binary stream.

**Comment by serge-rider** [comment]
Please check how it works in EA version (https://dbeaver.jkiss.org/files/ea/)

**Comment by AlexMax** [comment]
Hi there.  I just checked the EA version and I'm now having a different error when importing the same dump file:

    /usr/local/bin/mysql --no-beep --host=127.0.0.1 --port=10999 -u root example
    Database Import started at Mon Jan 29 09:06:43 EST 2018
    Database Import finished at Mon Jan 29 09:07:17 EST 2018
    Process exit code: 143

I also notice that my database is still missing a few tables compared to what I expect to see, though it seems to have gotten further this time than before.

**Comment by serge-rider** [comment]
Please one more time. One more small bug was fixed.

**Comment by AlexMax** [comment]
The dump appears to be imported successfully.  I then spot-checked my new database against the old one and I do not see any replacement characters inside my blobs.

**Comment by jeliasson** [comment]
To people using ```HeidiSQL```, update your version to the latest (9.5 at writing of this comment).
