### ISSUE TITLE
MySQL type Year incorrect display

### ISSUE THREAD

**Issue by juliardi** [dbeaver/dbeaver#2866]
I have a column with 'year' as its data type in MySQL database :
![screenshot_20180125_114354](https://user-images.githubusercontent.com/4223302/35371216-57fc2bac-01c5-11e8-9fb2-ed447f7d1b65.png)

However it displayed incorrectly in data view : 
![screenshot_20180125_114410](https://user-images.githubusercontent.com/4223302/35371217-583487f4-01c5-11e8-817e-e60e7dc0f908.png)
It should be displayed as '2017' or '2016', but the table shows '2017-01-01' and '2016-01-01'. It also happened when I want to update or insert new row.

**Comment by juliardi** [comment]
Is it possible to change the way Dbeaver display type 'year' data?

**Comment by juliardi** [comment]
@serge-rider can you look at this issue? 
Also recently I found another problem with Export Table Data feature which is related to this issue. When I want to export data from source table to another database, the Export Table Data will create a `year_column` with `timestamp` data type in the newly created destination table, even though when I look at the source table the data type is stated as `year(4)`.
Source Table :
<table>
<tr>
<td><b>Column Name</b></td>
<td><b>Data Type</b></td>
<tr>
<tr>
<td>year_column</td>
<td>year(4)</td>
<tr>
<tr>
<td>another_column</td>
<td>................</td>
<tr>
</table>

Destination Table :

<table>
<tr>
<td><b>Column Name</b></td>
<td><b>Data Type</b></td>
<tr>
<tr>
<td>year_column</td>
<td>timestamp</td>
<tr><tr>
<td>another_column</td>
<td>................</td>
<tr>
</table>

**Comment by serge-rider** [comment]
This will be fixed in 5.3.3. Sorry for so long delay

**Comment by juliardi** [comment]
No problem, thank you for addressing this issue
