### ISSUE TITLE
exportdate 

### ISSUE THREAD

**Issue by highgoyangguoqing** [dbeaver/dbeaver#2867]
When I select checkbox "Execute process on finish", then "Next" button  should be unenable before input the context of command.
Please check out.
![image](https://user-images.githubusercontent.com/34262632/35376253-2a68f63c-01e5-11e8-93a7-55f7761686d8.png)

**Comment by highgoyangguoqing** [comment]
update title

**Comment by serge-rider** [comment]
Thanks for report
