### ISSUE TITLE
Index description on PostgreSQL 

### ISSUE THREAD

**Issue by val5244** [dbeaver/dbeaver#2868]
After 

`COMMENT ON INDEX xxxIS 'ddd';
`
description on INDEX do not shown in propetries tab 
and in DDL sources tab.

Example:

```
CREATE INDEX c_stop_location_sd_ed_idx ON c_stop USING gist (location, tsrange(sd, ed));
COMMENT ON INDEX c_stop_location_sd_ed_idx
  IS 'Пространственный индекс по местоположению с учетом версионности';
```

![2018-01-25_12-49-49](https://user-images.githubusercontent.com/1685287/35381787-78d47650-01ce-11e8-87e2-a40973296273.png)

**Comment by serge-rider** [comment]
Thanks for report
