### ISSUE TITLE
MySQL slash-escaping breaks MS SQL Server highlifhting

### ISSUE THREAD

**Issue by piaste** [dbeaver/dbeaver#2869]
The fix for #2716 caused a regression for MS SQL Server (and possibly other databases?). 

In Transact-SQL, slashes aren't used to escape quotes, so if you write the string literal `'\'` (for example, to create a Windows path), DBeaver thinks it hasn't been closed and breaks highlighting in the query.

Example: 

![image](https://user-images.githubusercontent.com/12280683/35383797-9f0371f6-01c3-11e8-8e30-56e68ce630b5.png)

The escaping rules should be set according to the dialect in use.

**Comment by serge-rider** [comment]
Subject is a bit confusing. Is it MSSQL, not MySQL?

Yes, backslash shouldn't work as escape char in SQL Server.
