### ISSUE TITLE
Connection jdbc Sybase IQ not work in new releases (4.3.1, 4.3.2, 4.3.3, 4.3.3.1)

### ISSUE THREAD

**Issue by karlochev** [dbeaver/dbeaver#2870]
Hi,
In these releases 4.3.1, 4.3.2, 4.3.3, 4.3.3.1, connector jdbc for SybaseIQ not working, or not connect or not display tables of schema. In  4.2.6 release still working normally.

Please, check this.

Regards,

**Comment by serge-rider** [comment]
What driver do you use?
There is jTDS driver and jConnect driver (native SAP one)

**Comment by karlochev** [comment]
Hi, I tried both, but it did not work with either. But, in 4.2.6 release, if it works normally

**Comment by serge-rider** [comment]
Do you see some error? Or what do you mean under "did not work"?

**Comment by karlochev** [comment]
The errors was:
"Can't instantiate meta model" - When i trying to connect (JConnect y jTDS)
"NullPointerException" - When trying to visualize the tables (jTDS  4.3.3.1 release Dbeaver) It connected to the data base, but the tables could not be displayed

**Comment by serge-rider** [comment]
Wow. Looks like a bug.
Please post debug/error log - https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by karlochev** [comment]
Ok, I reinstall the previous release that works fine. I have to install the newer release, and post file. Thanks

**Comment by serge-rider** [comment]
Most likely you are using some non-very-standard config.
Bug itself should be easy fixable. Log will greatly help to localize/fix the problem.
Thanks for report.

**Comment by karlochev** [comment]
Hi, this is the logfile, you can view the errors in the 18-19/January forward!
[log.zip](https://github.com/dbeaver/dbeaver/files/1667830/log.zip)

**Comment by serge-rider** [comment]
Looks like something went wrong during schema list read (it is empty). 
Could you try to enable "Show all Schemas" option in connection dialog?

**Comment by serge-rider** [comment]
BTW you could check the most recent fix in EA version (https://dbeaver.jkiss.org/files/ea/)
