### ISSUE TITLE
Tables filters work only one Include table

### ISSUE THREAD

**Issue by code32** [dbeaver/dbeaver#2871]
If add more one include table to filter. Filter hide all tables. 
On Version 4.0.7 filters work good.
On Version 4.3.3 filter more one table hide all tables.
![2018-01-25 16-58-59](https://user-images.githubusercontent.com/3153076/35392051-9cb879ae-01f1-11e8-983d-8dedd23c8540.png)
![2018-01-25 17-08-37](https://user-images.githubusercontent.com/3153076/35392295-7c6fa7a2-01f2-11e8-8202-b2a6d4c0f527.png)

**Comment by serge-rider** [comment]
It is a bug in MySQL tables filter routine (filters work fine for other databases/object types).
Thanks for report!
