### ISSUE TITLE
Set Database in script (SQL Server)

### ISSUE THREAD

**Issue by acceler9** [dbeaver/dbeaver#2872]
Greetings!
I'm trying to create a SQL script in DBeaver 4.3.2 that will change the database as part of the script.  This is for SQL Server.
Pseudo Example:

BEGIN;
use ServerA
Insert into ServerA.Schema.Table ….
use ServerB
Insert into ServerB.Schema.Table ….
use ServerC
Insert into ServerC.Schema.Table ….
COMMIT;
END;

So far, I’ve been unable to use a server name (in ‘USE Database’) that DBeaver will accept.  I do not have Linked Servers enabled in any of the three SQL Server databases.
Am I missing something obvious??

Thanks!

**Comment by serge-rider** [comment]
Well, if you use classic SQL Server syntax `use DB_NAME`) then it should work. You don';t need to put DB_NAME in quotes or something, just plain database name.

What is the actual problem, do you see some error?

**Comment by acceler9** [comment]
serge-rider,
Thanks for the response!  I've tried multiple variations, and all return the same error:
"SQL Error [911] [S0001]: Database 'ServerA' does not exist. Make sure that the name is entered correctly."
I've tried:
use ServerA
use 'ServerA'
use [ServerA]
use DBeaverName for ServerA

Do I need to append anything to the server name, for DBeaver to accept the 'Use' statement?

Thanks!

**Comment by serge-rider** [comment]
Most likely database ServerA doesn't exist indeed.
Do you see it in database navigator? Could you post a screenshot?
