### ISSUE TITLE
Table Save button disabled after making changes and exiting cell editor

### ISSUE THREAD

**Issue by svrana** [dbeaver/dbeaver#2874]
..however the column is highlighted indicating that there is an outstanding change that has not been saved to the DB (and indeed it has not). If I press ctrl-s, I can get the state of the save button to reset so I can save the record, but it's a bit of a hassle.

By cell editor I'm referring to the full-screen one, not the line editor. I cannot reproduce this when editing the cell in the line editor.

This is with version 4.3.2

**Comment by svrana** [comment]
I should mention that after hitting ctrl-s in the full-page cell-editor it is necessary that focus go immediately back to the tab that contains the table that contains the cell. If focus goes to another table and you must navigate back to the table manually, the state of the 'Save' button is correct (i.e., it's clickable).

**Comment by serge-rider** [comment]
Yep, good point

**Comment by wysokinskim** [comment]
Bug is still present in DBeaver 22.0.3 on MacOs
