### ISSUE TITLE
Sequences permissions

### ISSUE THREAD

**Issue by Fridz5** [dbeaver/dbeaver#2877]
How to change sequences permissions for other users if DBeaver didn't want to do it

![default](https://user-images.githubusercontent.com/28841548/35437759-e7526214-02a4-11e8-837f-b0b3d23fa285.jpg)

**Comment by serge-rider** [comment]
It is more a misfunction than a bug. In any case sequences manager will be added in the next version.
Note: for sequences there is only on privilege: `USAGE`.
