### ISSUE TITLE
No result when put accents in a word at query

### ISSUE THREAD

**Issue by siderbit** [dbeaver/dbeaver#2881]
After two or three dbeaver updates, the queries started not accepting accented words, not giving the result. I solved temporarily the situation by taking the accents out of the words.
For an exemple:
Select city from user where city = 'São Paulo';
no results       // I expected "São Paulo"
Select city from user where city = 'Sao Paulo';
Result query: "São Paulo"

**Comment by serge-rider** [comment]
There were no any changes related to special characters.
I can see that queries with all national characters (including Chinese, Russian, etc) work fine.

To validate you can open your table, find a cell with national characters (e.g.  'São Paulo'), right click->Order/Filter->column_name = 'São Paulo'. It should show correctly filtered results.

Check your driver configuration (encoding parameters?).
