### ISSUE TITLE
Can't open 'https://dbeaver.jkiss.org/files/jdbc/drivers/sybase/jconnect/jconn4.jar': Not Found

### ISSUE THREAD

**Issue by CarlosDomingues** [dbeaver/dbeaver#2884]
When trying to create a Sybase connection with JConnect, I get the following error:

> Can't open 'https://dbeaver.jkiss.org/files/jdbc/drivers/sybase/jconnect/jconn4.jar': Not Found

First I thought that my issue was related to #2024, but from the error message we can see the rep is already the correct one. I also went to Window > Preferences > Database > Drivers just to make sure. 
Any thoughts?

**Comment by serge-rider** [comment]
Thanks for noticing, fixed.
