### ISSUE TITLE
Cannot show over 24 hours, cannot input also

### ISSUE THREAD

**Issue by jtanaka** [dbeaver/dbeaver#2885]
The `TIME` data type on MariaDB (MySQL also) can contain over 24 hours.
https://mariadb.com/kb/en/library/time/

But I cannot show (input also) over 24 hours like `25:00:00` on dbeaver.

### Results with dbeaver
![results_with_dbeaver](https://user-images.githubusercontent.com/1379640/35481198-58924bc4-0462-11e8-8ae5-d7235494853e.PNG)

### Results with commands
![results_with_cmd](https://user-images.githubusercontent.com/1379640/35481199-5bff34a2-0462-11e8-8ad8-cf3c4f7ae1fa.PNG)

**Comment by serge-rider** [comment]
Seems to be a bug. But honestly I'm not sure that this is supported by JDBC driver. In any case this violated standard TIME data type rules.
I'll check what can we do..

Workaround is to use cast function in your SQL query.

**Comment by serge-rider** [comment]
MariaDB driver is more accurate here. but still returns this as JDBC TIME data type.
Maybe we should poll a bug report to driver devs..
