### ISSUE TITLE
 Remove the incorrect record

### ISSUE THREAD

**Issue by rodolfope** [dbeaver/dbeaver#2887]
Stage: (Bug)

1. I have two tabs of query results.
2. I put a result tab as "pin tab". (I have one record in this query)
3. In the other tab I keep making another query, in which I proceed to delete a record. (Delete button)
4. The record that removed the software was from the "Pin Tab". This is wrong.

DB: DB2

I hope you can help me.

**Comment by serge-rider** [comment]
I can't reproduce this behavior. Maybe there are some additional steps to do?
Could you record a short gif video (using tool like ScreenToGif)?
