### ISSUE TITLE
Bug: NULL tab when opening dbeaver 4.3.3.1

### ISSUE THREAD

**Issue by sirber** [dbeaver/dbeaver#2890]
![image](https://user-images.githubusercontent.com/3911428/35516926-0ce6215e-04db-11e8-8acc-9757d568b49c.png)

**Comment by serge-rider** [comment]
Please post error/debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by sirber** [comment]
It looks fine today. Seen the issur 3-4 times in the past week. Will post the logs when I see it again.

**Comment by sirber** [comment]
Lol got it again (with a view open). Posting logs

**Comment by sirber** [comment]
[metadata.zip](https://github.com/dbeaver/dbeaver/files/1678090/metadata.zip)

**Comment by serge-rider** [comment]
I see a few exceptions (which look like a bug) but I can't realize how to reproduce this.
Do you  remember how this happened?

**Comment by sirber** [comment]
I don't know... When I close the app, I don't close all the tabs. Once in a while, when I reopen the app, one of the tab is NULL....... sorry

**Comment by sirber** [comment]
I'm trying 4.3.4

**Comment by sirber** [comment]
The last tab is still NULL when opening dBeaver. Can I clean some files to have a default install but keep connexion infos?

**Comment by serge-rider** [comment]
Perhaps something was corrupted in workspace config.
Could you try to delete workbench.xmi (https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)?

**Comment by serge-rider** [comment]
Any update on this?

**Comment by sirber** [comment]
I'm on 5.1.1 with a new workspace (I deleted everytoing a while ago). Looks fine since. Sorry I forgot about the issue. Thanks for the fellow up!
