### ISSUE TITLE
[Usability] Double-click on database to set active (PostgreSQL, maybe others?)

### ISSUE THREAD

**Issue by piaste** [dbeaver/dbeaver#2892]
PostgreSQL only allows a connection to access one database at the time.

So when you double-click a database other than the active one, or try to expand its Schemas folder, this will *always* result in this error message:

![image](https://user-images.githubusercontent.com/12280683/35527022-a44a125a-0529-11e8-966a-73ea3927ae89.png)

And you *always* need to click OK, right-click the database, and choose `Set active` before proceeding. 

It would be nice to skip this extra step, and just make it so that when you double-click a PostgreSQL database it gets automatically set as active. It's a deliberate action and hard to do by accident.

It may make sense to make this the default behaviour for other databases as well, for consistency, but I'm less sure about that.

**Comment by serge-rider** [comment]
I like this.

**Comment by serge-rider** [comment]
However this should be configurable

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/35693570-9c702052-078f-11e8-90b9-f2de9bd02bfc.png)

**Comment by piaste** [comment]
Awesome! Thanks a lot.

**Comment by jnazander** [comment]
Thank you! Now more redundant "set active database" clicks! It should've been like that from the start.

**Comment by anxodio** [comment]
In the last release, this check is removed:

> Multi-database support was improved (no need to switch active database on access) 

I would prefer to keep the checkbox, because is util to change all the active database (for example, if you open the SQL Editor it will be open with the last active database).

**Comment by aruprakshit** [comment]
Why don't I see the "switch default database on access" checkbox? 

<img width="1434" alt="screen shot 2018-09-05 at 12 11 11 pm" src="https://user-images.githubusercontent.com/3428463/45075485-e5e86b80-b104-11e8-83c9-c5bcbf540c3f.png">

**Comment by jyinpci** [comment]
This feature (auto-switch by double-click) had disappeared since 5.2.0.  I wish it is brought back.  Without it, I sometimes query/update a wrong database - rather dangerous.

Please bring this feature back.

**Comment by DKhalil** [comment]
Is this going to be added again? This would be really really useful to have.

**Comment by jyinpci** [comment]
Please bring it back.  I beg you.

**Comment by tati-kru** [comment]
We are not sure that the double click is the best option. Double click is already overloaded by different actions. We can make something like a special icon or button  near each database name for the fast switching. Let's discuss it in the new ticket (https://github.com/dbeaver/dbeaver/issues/5027).
