### ISSUE TITLE
Same query but no result on DBeaver 4.3.3.1 and have data on SQL Server Management Studio 17.2 (2017)

### ISSUE THREAD

**Issue by tranbaohuu** [dbeaver/dbeaver#2893]
Dear Technical
-After updated the EA version 4.3.3.1, Both of features work is OK. Thank for your support.

+But I have a question I don't know should i need to create a new article or not.

+I send to you 2 images about Select in a table between DBeaver 4.3.3.1 and SQL Server Management Studio 2017 v17.2

![dbeaver_2018-01-29_13-53-16](https://user-images.githubusercontent.com/10123641/35497386-92985b5c-04fc-11e8-97d4-36475cd26ccf.png)

There is record for DBeaver 4.3.3.1

![ssms_2018-01-29_13-54-23](https://user-images.githubusercontent.com/10123641/35497401-9d752b4a-04fc-11e8-9216-16df8abe0fb7.png)

There are 5 records for SQL Management Studio 2017 V17.2

And log files

[.log](https://github.com/dbeaver/dbeaver/files/1672536/default.log)

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/1672537/dbeaver-debug.log)

Regards

**Comment by serge-rider** [comment]
I see error 
```java
SQL Error [245] [S0001]: Conversion failed when converting the varchar value '1199796-53' to data type int.
```
in the log. It is internal error in JDBC driver .Could you try another driver? jTDS for example or newer version MSSQL.

**Comment by tranbaohuu** [comment]
I already tried for jTDS 1.3.1 (Latest) and Microsoft JDBC Driver 6.2 (Latest). But it's same problem. Does it came from configuration of SqlServer or something else?

**Comment by serge-rider** [comment]
I can't say yet.
Please post table DDL, there is something in column declaration.

**Comment by tranbaohuu** [comment]
CREATE TABLE MyPDM.dbo.tblversion (
	vsflid int,
	vsid int NOT NULL,
	vsname varchar(100),
	vscomment varchar(2000),
	vsstage varchar(50),
	vsitno varchar(50),
	vsitds varchar(50),
	vskind varchar(50),
	vswhoin varchar(50),
	vswhenin datetime,
	vswhoupd varchar(50),
	vswhenupd datetime,
	vspriority smallint,
	vslockedby varchar(50),
	vseccc varchar(50),
	vsQdesc varchar(50),
	vsQquality varchar(50),
	vsQmetal varchar(50),
	vsQqty varchar(50),
	CONSTRAINT PKey_tblversion_New PRIMARY KEY (vsid)
) go
CREATE INDEX IX_tblversion_New ON MyPDM.dbo.tblversion (vsflid) go
CREATE INDEX IX_tblversion_New_1 ON MyPDM.dbo.tblversion (vsitno) go
CREATE INDEX IX_tblversion_New_2 ON MyPDM.dbo.tblversion (vsitds) go;

**Comment by serge-rider** [comment]
Thanks. Please check how it will work in 4.3.4 - there were a few fixes in SQL Server metadata model.

**Comment by tranbaohuu** [comment]
For version 4.3.4 it's still problem. I already changed between 2 drivers jTDS and SQL Server but it was same.

**Comment by tranbaohuu** [comment]
Dear Serge 
   I found problem is: 2 database same name but on two differences servers. It's my mistake, sorry to waste your time. 
Have a good day!

**Comment by serge-rider** [comment]
Ok)
