### ISSUE TITLE
export table to insert sql, lost id column

### ISSUE THREAD

**Issue by helppass** [dbeaver/dbeaver#2895]
version: 4.3.3.1 CE

Export table data to insert sql.
But lost id column.

![default](https://user-images.githubusercontent.com/12808832/35556020-06400444-05dc-11e8-842b-42b260ad93cc.png)

![default](https://user-images.githubusercontent.com/12808832/35556030-0c5176ec-05dc-11e8-8c0f-ae4e041dedad.png)

![default](https://user-images.githubusercontent.com/12808832/35556036-1130ecec-05dc-11e8-909f-114847fd42bd.png)

![default](https://user-images.githubusercontent.com/12808832/35556048-159c2efe-05dc-11e8-99de-14857da68603.png)

The table ddl :
CREATE TABLE `t_parent_student_link` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `parent_id` bigint(19) DEFAULT NULL,
  `relation_ship` bigint(10) DEFAULT NULL COMMENT '1,0',
  `student_id` bigint(19) DEFAULT NULL,
  `create_time` varchar(14) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_parent_student_link_1` (`parent_id`,`student_id`),
  KEY `idx_parent_student_link_parent_id` (`parent_id`),
  KEY `idx_parent_student_link_student_id` (`student_id`)
) ENGINE=InnoDB AUTO_INCREMENT=453485 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

The export sql:
INSERT INTO bzplatform.t_parent_student_link (parent_id,relation_ship,student_id,create_time) VALUES 
(565,7,564,NULL)
,(580,1,579,NULL)
,(565,7,527,NULL)
,(745,7,693,NULL)
...

**Comment by serge-rider** [comment]
Yep. Since 4.3.2 DBeaver doesn't include auto-generated columns in SQL INSERTs. I think we need a special option for that.

**Comment by tentree-development** [comment]
Does this related to when exporting data to another database auto increment attributes don't get to move over to new database? If so where in setting I can set this? Or is not available for community edition?
