### ISSUE TITLE
Feature Request: select subquery to execute.

### ISSUE THREAD

**Issue by oferz** [dbeaver/dbeaver#2897]
Hi,

Datagrip has this cool feature where you can choose to execute only a subqurey and not the entire query. This is really helpful to debug complex queries. The way it works in Datagrip, is that if you have the cursor inside a subquery when executing (ctrl+enter) it will popup a window with the options to select the scope to execute, starting with the inner most scope where the cursor is, and going up to the entire query. One more cool implementation detail they have is that when you move between the options, it highlights the query part that will be executed.
Any chance to get something similar in DBeaver?

Thanks,
o

**Comment by kseniiaguzeeva** [comment]
Similar option already exists in DBeaver:
set the cursor inside a subquery and press "Execute SQL Statement" (Ctrl+Enter).
If you want to execute the whole script, press "Execute SQL Script" (Alt+X).
![dbeaver_TRqVAkNkPd](https://user-images.githubusercontent.com/51405061/73076525-57c67e00-3ecf-11ea-876c-853e5064917e.png)
Or are you interested in implementing the described popup and highlighting?

**Comment by oferz** [comment]
Hi,
Thanks for taking a look at this issue.
Does ctrl+enter work on subqueries? I had the impression it was only executing the current query if there are multiple ones in the script. In anycase, it would be nice if the query that will be executed was highlighted somehow.

Cheers,
o

**Comment by uslss** [comment]
@oferz you could select needed subquery and execute it.

> To execute a query under cursor or selected text, press Ctrl+Enter or right-click the query and click Execute -> Execute SQL Statement on the context menu. You can do the same using the main toolbar or main menu: SQL Editor -> Execute SQL Statement. **This executes the SQL query under cursor or selected text** and fills the results pane with the query results.
https://github.com/dbeaver/dbeaver/wiki/SQL-Execution

**Comment by ccrothers** [comment]
@uslss oferz feature request isn't addressed by that workaround. I think you may have misunderstood the feature request.

Here is a video of the behavior in datagrip vs dbeaver that oferz was referring to. In it, I compare them and discuss different approaches dbeaver could use to implement the solution/feature.

https://youtu.be/qepZgKam8YA

selection expansion might be simpler, and would make the selection of the inner query, as mentioned by your last comment, much faster.

Be sure not to confuse selection expansion (DataGrip's ctrl+w) with statement selection (dbeaver's alt+up and alt+down)
