### ISSUE TITLE
V$ Oracle Table Query Causes App Crash On Mac

### ISSUE THREAD

**Issue by KraFusion** [dbeaver/dbeaver#2898]
Community Edition 4.3.3.1
Using Oracle thin driver

I do not have grants to query this table, but when I try to query it, I get the spinning color wheel and the app become unresponsive. I let it sit there for about 15 minutes before Force Quitting it.
In previous versions, say pre 4.1 versions, it would hang for about 30 seconds and then recover.

-- this query causes a reproducible effect, every single time
select name from V$database;

**Comment by serge-rider** [comment]
- What is your OS? 
- Could you post a screenshot of frozen UI?
- Could you post a thread dump (https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump)

Thanks for report

**Comment by uslss** [comment]
There is no update on the ticket for more than a year.
If the issue is still reproducible for you - feel free to reopen the ticket and add some details or create the new one.
