### ISSUE TITLE
The SQL Editor is not running queries that have been terminated by semicolon

### ISSUE THREAD

**Issue by ivanelson** [dbeaver/dbeaver#2899]
Hello

I downloaded version 4.3.3 today and I just realized that "SQL Editor" is not running queries finalized by the ";" symbol.

In the example below, the second query is not executed. However, after removing the ";" the query flows normally.

![image](https://user-images.githubusercontent.com/779883/35584542-1631886c-05d4-11e8-87ac-5af3e67fc00b.png)

**Comment by serge-rider** [comment]
I can't reproduce that.
The first query on the screenshot doesn't has terminating `;` or empty line after it. This is not correct (you can execute it only by selecting it) - DBeaver just concatenates first two lines in single query (and this is valid for some databases).

Please provide a bit more info. 
"Bad" query example,  "good" query example. Do you see any errors when you execute it?

**Comment by ivanelson** [comment]
@serge-rider In later versions (> 4.3.3), I did not get this problem. thx
