### ISSUE TITLE
 crash

### ISSUE THREAD

**Issue by ssyang0102** [dbeaver/dbeaver#2902]
when  I paste a long string to script tab ,the  dbeaver  crash，i use mac，  dbeaver 4.3.2

**Comment by serge-rider** [comment]
Can't reproduce.
How long is this string? Maybe you could attach a sample (just replace all valuable information with any non-secure info)

**Comment by ssyang0102** [comment]
select * from user where id in (1,2,3,4,5,,,,,,,,,)
the id count is 5000+,or even more

**Comment by serge-rider** [comment]
Could you post a real sample? Sometimes it fails because of some special symbols or some particular sequence of characters.

**Comment by ssyang0102** [comment]
To be exact, if you enter too many characters in a line(More than 10000 characters), will very slow or crash.

**Comment by beeing** [comment]
This happened on line with 7k+ characters as well.

**Comment by beeing** [comment]
Nope, word wrap does not help. It looks like it slows down (unresponsive) when cursor entering and exiting the long lines and also going through brackets (highlighting brackets)

But after manually splitting the long lines to shorter ones, the short lines will not jerk as much compared to longer lines.

After I turned off the Text Editor -> Highlight Current Line, it does not slows down when cursor moving in and out of the line, but going through brackets still slow.

Hope this helps.

**Comment by jvstein** [comment]
I'm using queries of the same style (`UPDATE table SET column = value WHERE id in (...);`). It's easy to reproduce if the query is ~50,000 characters long.

I'm on Linux and I don't get a full crash, but the editor goes totally unresponsive when pasting long queries, often using 100% of one CPU. It's also hard to move around those lines, with the editor hanging for several seconds every time you arrow/scroll past.

I'm also not using word wrap and it doesn't seem to help.

**Comment by uslss** [comment]
if the issue is still actual - feel free to reopen the ticket or create a new one.
