### ISSUE TITLE
How to have multiple JDBC driver settings for SQL Server in dBeaver

### ISSUE THREAD

**Issue by robbielusk** [dbeaver/dbeaver#2903]
I've got multiple SQL Server databases and I can connect to them one at a time as long as I update the driver setting JDBC information. I'd like to be able to open multiple connections at once and ideally I'd like to click on one and connect rather than update the JDBC string for each connection. 

Is there a way to accomplish this? Maybe I'm not understanding the UI. Please advise. Thanks.

**Comment by serge-rider** [comment]
You shouldn't edit driver information at all. Leave it as is (as it was configured in DBeaver - you can reset to original settings by clicking on "Reset to Defaults").
Then just create any number of connections using this driver: https://github.com/dbeaver/dbeaver/wiki/Connecting-to-Databases

**Comment by robbielusk** [comment]
Okay, I'm trying it the way described. I'm using the jTDS driver for SQL Server and I've updated the domain and user information. However it gives me the domain is from an untrusted domain....even though this is the exact info i used in the jdbc driver edits before (which worked).

**Comment by robbielusk** [comment]
thx - it worked

**Comment by serge-rider** [comment]
Try to set domain in driver properties:
![image](https://user-images.githubusercontent.com/6398845/35633147-9cc07e5c-06b9-11e8-95c7-339f8345660f.png)
