### ISSUE TITLE
Copy paste number without thousand separator

### ISSUE THREAD

**Issue by Moorhed** [dbeaver/dbeaver#2905]
When copy/paste number like 32,075,105 ("Use grouping" check box is checked)  I would like paste the number without thousand separator - so like 32075105.
Would be possible to introduce settings for ignoring formating for simple Copy/Paste?

I can use Ctrl+Shift+C but then another window appear.

**Comment by serge-rider** [comment]
Numeric value are copied without formatting if you copy it directly from grid without value editor activation. 
If you copy from an editor (text control) then native copy function is used and it copies value as is (with formatting).
