### ISSUE TITLE
No DDL for view in Oracle on fresh 4.3.3.1 install

### ISSUE THREAD

**Issue by JiCiT** [dbeaver/dbeaver#2906]
Unable to to see DDL for a view on Oracle server on fresh 4.3.3.1 x64 install on Windows 7.  Getting the error "-- Can't generate DDL: table editor not found for org.jkiss.dbeaver.ext.oracle.model.OracleView".

![view_ddl](https://user-images.githubusercontent.com/5899292/35653960-91ecb53c-06b8-11e8-9c13-0fc58c19207c.png)

**Comment by serge-rider** [comment]
Thanks for report
