### ISSUE TITLE
How to Exporting Blanks in CSV as NULL?

### ISSUE THREAD

**Issue by viiiinii** [dbeaver/dbeaver#2907]
Hi! I'm trying to export some CSV data into a table I've created. I'm running into the issue "can not bind statement parameter; invalid parameter index" from redshift due to my CSV having blanks in various columns. 

Does anyone have recommendations on how I could adjust my CSV so that I'd be able to successfully export the data? I've tried filling in the blanks with NULL, [NULL] and \N but it just interprets it as text.

**Comment by serge-rider** [comment]
Where do you see error "can not bind statement parameter"? 
Is this happens during export operation?

Perhaps you should try to export in SQL INSERT form. CSV looses all source data type information.

**Comment by viiiinii** [comment]
Btw - I did manage to export in SQL INSERT form where I just pulled all my data values in excel, populated NULL for my blank values, and then pasted the data as a SQL INSERT.

Thanks for the advice Serge!!
