### ISSUE TITLE
Generate update or insert statement with matching (Firebird)

### ISSUE THREAD

**Issue by Franki1986** [dbeaver/dbeaver#2908]
Hello,

is it possible to create an update or insert statement of selected rows? At the moment you can only create an update or an insert statement.

'UPDATE OR INSERT INTO TABLE_NAME (ID_1, UNIQUE_1, UNIQUE_2, CONTENT, AUDIO) VALUES ('1', '2', '3', NULL, NULL) MATCHING(UNIQUE_1, UNIQUE_2);'

**Comment by serge-rider** [comment]
I think this would be helpful. 
The only complication is that UPSERT/UPDATE OR INSERT isn't very standard. different databases use different SQL syntax.
What database do you mean here?

**Comment by Franki1986** [comment]
Hi,
In my case it is firebird.

**Comment by ghost** [comment]
Hi, 
is this issue still available? 
If yes, I would give it a try. I checked this issue with an Postgres Database. In this case there is an opportunity to create a merge statement. 
Maybe someone missed it to close the issue.

**Comment by uslss** [comment]
MERGE option is already available in table context menu in DB Navigator
![image](https://user-images.githubusercontent.com/31996417/151171522-0549a674-7e54-4c07-a417-a6a72a403af8.png)
