### ISSUE TITLE
Sybase ASE stored procedure source code with jconn

### ISSUE THREAD

**Issue by MadKulhas** [dbeaver/dbeaver#2911]
Hello,

when using the jconn4 driver now available with DBeaver latest versions, I'm not able to get the source code of the procedures, but with the older Sybase configuration using jtds 1.3.1 it was working correctly.

Is it possible to add this with jconn4?

Thank you.

**Comment by serge-rider** [comment]
jConn driver returns bad  procedure name (so called "specific name"). I'll add a workaround for that.

BTW you can use jTDS in newer DBeaver version as well.
