### ISSUE TITLE
PostgreSQL CREATE EXTENSION query issue

### ISSUE THREAD

**Issue by alex-toth** [dbeaver/dbeaver#2912]
Hello 

In DBeaver 4.3.3.1 I have the following issue:

Running the following query: 

```
CREATE EXTENSION if not EXISTS hstore;

select (x).key, (x).value 
from ( select EACH(hstore(t)) as x 
	   from pg_stat_database as t
	   where datname = 'dvdrental' --replace with whatever database you want to check
	   ) as q
where (x).key not in ('datid','datname', 'stats_reset')
```
Returns this:
![image](https://user-images.githubusercontent.com/36038191/35678552-151e6298-0754-11e8-9171-19123cb061fd.png)

instead of the actual query result. Running the same query in HeidiSQL returns the expected result.

**Comment by serge-rider** [comment]
What is the expected result? You are executing multiple queries (CREATE EXTENSION and SELECT) as a single SQL query.
If you want to execute these queries as a script- use <kbd>ALT+X</kbd>.
If you want to execute them manually one by one - use <kbd>CTRL+Enter</kbd> of each query (and you don't need to select query if there are some query delimiters like `;`).
