### ISSUE TITLE
Unmatching colors for Dark theme

### ISSUE THREAD

**Issue by nmadham** [dbeaver/dbeaver#2914]
**I guess Colors are not really getting along  with the Dark theme.**
Colors defined for both Basic & SQL Editor categories have similar contrast values when compared to black background.Thus,making characters typed on the screen dissolve in the background and unable to quickly identify what has been typed.
Here is an Example.
   
![image](https://user-images.githubusercontent.com/16705400/35686640-bd2c5770-073a-11e8-83e2-f96ed19ac0ab.png)

Thank you for your attention to these requests.

**Comment by serge-rider** [comment]
Try to restart DBeaver. Sometimes theme switch causes such glitch.
This how it should look:

![image](https://user-images.githubusercontent.com/6398845/35702269-b71d7c8c-07a9-11e8-86cd-946f6c1abf82.png)

**Comment by nmadham** [comment]
Reinstalling application fixed the issue.

**Comment by brianspo** [comment]
Hmm, I reinstalled to no avail.  What else can I do?

**Comment by serge-rider** [comment]
Do you use standalone version or Eclipse plugin?

**Comment by brianspo** [comment]
Standalone.  I can manually fix the colors (which I just did) so things are readable, but I think I had to do this by hand before when I first installed.  Today I installed the Git plugin and the editor font settings were reset.  I just reinstalled although apparently I didn't lose all of my settings as my license and some settings were retained.
