### ISSUE TITLE
Allow importing the same database script multiple times from the same dialog

### ISSUE THREAD

**Issue by nikowitt** [dbeaver/dbeaver#2917]
Hi there,

I really like DBeaver, which is my default DB management tool. One thing that could be probably improved easily is the ability to be able to import a dump multiple times.

![image](https://user-images.githubusercontent.com/1472328/35718666-e72e5d9c-07e5-11e8-8e54-276ce05ad021.png)

When the import is done, I can use back and next, but basically

I either expect
a)  "Start" to be reenabled again after clicking "Back"
b) "Start" be enabled all the time, giving an confirmation prompt when the file  was already imported using the current dialog.

When we deal with tests that are incorrectly commit data to the database, we might have to repeatedly import dumps to the database. In the current situation, I have to close the window and then to start the whole import process again, meaning I have to reselect the SQL file again.

Probably a minor improvement that could be quite useful in certain situations.

Keep up the good work!

Regards,
Niko

**Comment by serge-rider** [comment]
Good point.

**Comment by nikowitt** [comment]
Works fine, thank you!
