### ISSUE TITLE
Internationalization: Does not default display time correct with fractions

### ISSUE THREAD

**Issue by larsbuch** [dbeaver/dbeaver#2918]
I have not been looking at the code to find the configuration that needs to be changed to make the internationalization not remove fractions in result sets.

UI Correction: Preference → Database → Results Sets → Data Formats
for Format Type:
Time change Pattern from HH:mm:ss to HH:mm:ss.ffffff
Timestamp change Pattern from yyyy-MM-dd HH:mm:ss to yyyy-MM-dd HH:mm:ss.ffffff

**Comment by uslss** [comment]
cannot reproduce an issue.
Ticket closed.
If issue is still actual for you - feel free to reopen the ticket
