### ISSUE TITLE
question: commit/rollback in sql editor possible?

### ISSUE THREAD

**Issue by pvanek** [dbeaver/dbeaver#2925]
Tools I used before have possibility to commit/rollback directly from the SQL editor. Example:

```
insert into t values (1);
<ctrl+enter>
commit;
<ctrl+enter>
```

is this possible in Deaver? For me it looks like I have to use commit/rollback buttons (shortcuts) even after one statement.

Or do I understand concept of Dbeaver wrongly? I'm old DB guys, who always lives in a transaction. So for me there are regular usecases to make set of DML + selects before I commit/rollback...

**Comment by serge-rider** [comment]
You don't need to do commit/rollback after each command.
I'm not quite sure I understand the problem..

1. You can execute COMMIT/ROLLBACK commands directly from SQL editor (if your database supports them)
2. You can use Commit/Rollback buttons/shortcuts
3. You can switch to auto-commit mode

**Comment by mdahlman** [comment]
I'd like to re-open this topic. For me the behavior is like Petr Vanek suggests. For example:

1. I make a brand new connection to a PostgreSQL server.
2. I execute "begin;"
Expected: A transaction is started.
Actual: A transaction is started. (good!) I can see it in the green transaction count field.
Also: the output window displays "there is already a transaction in progress" (this is bad). I just started a transaction, in a brand new connection. There should not have been a transaction in progress.
3. I execute "rollback;"
Expected: The transaction is rolled back. The statements in progress display should go back to 0 (actually displayed as "Auto")
Actual: the query "rollback;" seems to be added to my transaction. My statement count increments to 2. This is very confusing. I'm not sure what it means for rollback to be part of the transaction.

I can use the Commit/Rollback buttons to manage my transaction. But I don't seem to be able to manage it from a script.

Certainly PostgreSQL supports BEGIN and ROLLBACK.

Are you sure that Serge's point #1 is correct?

Thanks

**Comment by p91paul** [comment]
issuing rollback from the sql editor does rollback the transaction, however dbeaver is not yet smart enough to know you issued a rollback and so it should reset transaction count.
Also, dbeaver automatically starts a transaction when you issue any statement, which is why you get that warning in the output window when you issue the "begin" statement (you are not supposed to).
Anyway, if you want to propose different behavior, you should open a new issue, this one's ancient.
