### ISSUE TITLE
Data Types Mixed when Exporting MS SQL Query to CSV

### ISSUE THREAD

**Issue by Tylermarques** [dbeaver/dbeaver#2926]
When exporting a MS SQL query to csv, a column which is originally an int is being partially converted to a string on export. Any ints >= 1000 are being converted to a string representation, with a comma inserted (i.e 2018 -> "2,018").  This is produced by selecting a row using  `col = SUM( CASE WHEN col_1 = 'ValueName' THEN col_2 ELSE 0 END )`. 

When doing identical steps on a windows machine, this does not occur, leading me to believe that this is a DBeaver on Mac issue. DBeaver version 4.3.3.1, Mac OS 10.13.3.

**Comment by serge-rider** [comment]
This happens because of different numbers representation. Comma is used for numbers grouping. It is configurable in Data Formats preferences:
![image](https://user-images.githubusercontent.com/6398845/35941925-0154679c-0c65-11e8-9a73-395e801b453d.png)

**Comment by Tylermarques** [comment]
Thanks for the answer, though it does seem to me like this shouldn't occur by default? It seems odd to change numbers into a string representation by default.

**Comment by serge-rider** [comment]
This is very dependent on the software you are using for CSV reading.
However, I agreed. In most cases it doesn't make sense to have numbers formatting in CSV. I'll add special export option for that (disabled by default):

![image](https://user-images.githubusercontent.com/6398845/35989868-64104dc0-0d13-11e8-9d99-fde25ea27df6.png)

**Comment by Tylermarques** [comment]
Thanks! I appreciate the change.
