### ISSUE TITLE
Save blob to file doesn't work for sqlite

### ISSUE THREAD

**Issue by icegood** [dbeaver/dbeaver#29270]
### Description

Cannot neither view nor at least export images to dedicated files from query

### DBeaver Version

Community edition Version 24.0.3.202404211624

### Operating System

Distributor ID:	Ubuntu Description:	Ubuntu 22.04.4 LTS Release:	22.04 Codename:	jammy

### Database and driver

sqlite_jdbc-18f2a3c9c94-5ae768d64334e5b1

### Steps to reproduce

1) get some query with desired field. Convert it to blob:
cast(d.data15 as blob) as d15_blob

2) Do for query result:
'export data' -> 'Format settings' -> 'Binaries' => 'Save to files'

### Additional context

Expected: filed for each record will be saved in dedicated file
Actual: field is saved as binary hext right in 'common' file

**Comment by E1izabeth** [comment]
I can't reproduce your issue. It works well for me. Please provide a footage of your issue.

https://github.com/dbeaver/dbeaver/assets/28875055/9270a51b-bf44-43d5-9f7c-2f96ef64227f

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
