### ISSUE TITLE
Fix potential github action smells

### ISSUE THREAD

**Issue by ceddy4395** [dbeaver/dbeaver#29272]
### Description

Hey! 🙂
I want to contribute the following changes to your workflow:

- Stop running workflows when there is a newer commit in PR
- Use commit hash instead of tags for action versions
- Use fixed version for runs-on argument
- Define permissions for workflows with external actions

These changes are part of a research Study at TU Delft looking at GitHub Action Smells. [Find out more](https://ceddy4395.github.io/research/gha-smells.html)

### DBeaver Version

24.0.3

**Comment by ShadelessFox** [comment]
Thanks for the contribution. Most of the proposed changes are questionable. More information can be found in the PR itself.

You still can help us make DBeaver better by:
- Fixing a bug https://github.com/dbeaver/dbeaver/issues?q=is%3Aissue+is%3Aopen+label%3Abug
- Localizing it to your native language or improving existing localization https://github.com/dbeaver/dbeaver/wiki/Localization
