### ISSUE TITLE
Add more keywords for smart block recognition

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#29279]
![image](https://github.com/dbeaver/dbeaver/assets/28875055/7f155858-bd34-43c1-a78c-077a287a2288)
We should improve our query start recognition mechanism to handle such cases.

**Comment by mbezhanov** [comment]
I am currently being affected by this:

![image](https://github.com/dbeaver/dbeaver/assets/785542/b014db3f-a918-4e19-8a2b-e58e5790a80a)

The `GRANT` statement is being grouped with the `CREATE` statement and the two are being sent together to the SQL server.

From the execution log:


> **Time**: Apr-30 13:19:39
> **Type**: SQL / User script
> **Text**: CREATE USER 'test'@'%' IDENTIFIED BY 'test';GRANT ALL ON test.* TO 'test'@'%'
> **Duration**: 105
> **Result**: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GRANT ALL ON test.* TO 'test'@'%'' at line 2

Would be great to have it resolved!

**Comment by E1izabeth** [comment]
The fix for your case will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.

**Comment by mbezhanov** [comment]
Awesome, thank you!
