### ISSUE TITLE
Search Function Not Highlighting Correct Schema

### ISSUE THREAD

**Issue by ufuk-ergin-carbon** [dbeaver/dbeaver#29280]
### Description

The search function in the Dbeaver does not work correctly. I am not sure if it is the intended outcome but as the way it is, it is very useless. When you search for a table name, it highlights the wrong schema and you'd have guess to expand tables. It does not narrow it down for you. I am attaching a screen recording for the behavior. I am also attaching a screen recording as to how it should be in Snowflake's own editor window.

https://github.com/dbeaver/dbeaver/assets/114302087/51350bbd-835a-48c1-8b66-e7c621120a88

https://github.com/dbeaver/dbeaver/assets/114302087/b7b94e40-3295-42df-993c-37deacc764c6

Edit: This has been going on for a long time. Not a new issue.

### DBeaver Version

CE Version 24.0.3.202404211624

### Operating System

MacOs Sonoma 14.4.1 (23E224)

### Database and driver

Snowflake Server: Snowflake 8.16.10
Driver: Snowflake 3.14.4

**Comment by E1izabeth** [comment]
Could you clarify what the issue is? Where do you expect to meet highlighting?
Filtering removes all elements from the navigator, which doesn't correspond to the condition.

**Comment by ufuk-ergin-carbon** [comment]
Hello @E1izabeth , when you search for a table name for example, the search should filter as to where the navigator found the search string. This is what happens in Snowflake UI (the second screen recording). However, in Dbeaver, it does not do anything when you copy and past the table name and hit return in the search bar. It does not tell you where it found the table, it does not filter, in the video, I have to guess where it could have been and expand it. Does it make sense?

**Comment by E1izabeth** [comment]
I see. Thank you for explanation. The difference is that it's a filter, not search. That's why it works differently. We will discuss your suggestion to improve this behavior.
I may suggest you to use search this way:

1) Use shortcut ⌃⇧D to open search dialog
![image](https://github.com/dbeaver/dbeaver/assets/28875055/7dfd112a-7334-457b-a332-8f51b1c69676)

OR
2) Use Metadata search from the main toolbar 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/0fe73b51-9e49-43c7-a833-290f7d613482)

Here is how it look like

![image](https://github.com/dbeaver/dbeaver/assets/28875055/a5d6177c-bc04-4683-8d99-1513d3cdee9a)

**Comment by ufuk-ergin-carbon** [comment]
The Metasearch from the main toolbar does not work or I am missing something. I am attaching the screen recording:

https://github.com/dbeaver/dbeaver/assets/114302087/9b0c0084-5548-49e7-9cd3-0f7eb5432343


And, the shortcut ⌃⇧D does not provide the full addresses, catalog names are missing (jumps to schema):


https://github.com/dbeaver/dbeaver/assets/114302087/7abc9556-5a57-42f4-bdff-77e32dec6be5

Also, while it is searching, it does not indicate whether or not it is searching (but it actually is in the background and OK button is disabled). Does your version indicate something like "Searching..."?

**Comment by E1izabeth** [comment]
>Also, while it is searching, it does not indicate whether or not it is searching (but it actually is in the background and OK button is disabled). Does your version indicate something like "Searching..."?

Yes. It's here
![image](https://github.com/dbeaver/dbeaver/assets/28875055/3570c357-329e-4fd7-83c2-1cc2ff8ff46d)

**Comment by E1izabeth** [comment]
>The Metasearch from the main toolbar does not work or I am missing something.

It works after you press Search button. For me it works this way

https://github.com/dbeaver/dbeaver/assets/28875055/9ed7b905-04a6-47f0-960a-1af95432c2f9

**Comment by ufuk-ergin-carbon** [comment]
I cannot hit the Search button because it is disabled. I am attaching the screen recording again. Nothing happens.


https://github.com/dbeaver/dbeaver/assets/114302087/1b9d62d8-c854-49c7-8c13-e5a3b82dcb36

**Comment by E1izabeth** [comment]
I see. Thank you.
The issue here is that Object Types field is empty for you.
Could you provide log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by ufuk-ergin-carbon** [comment]
there are multiple log files, but I am attaching one. Let me know if need some others.

Also, do I need to do anything to fix the Object Types field being empty?

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/15166342/dbeaver-debug.log)

**Comment by E1izabeth** [comment]
Nothing in logs. It looks like a bug, that this field is empty for you. I'm not sure it can be fixed from your side.

**Comment by E1izabeth** [comment]
Could you send `.log` file also?

**Comment by ufuk-ergin-carbon** [comment]
[dbeaver-debug-1714487425196.log](https://github.com/dbeaver/dbeaver/files/15166409/dbeaver-debug-1714487425196.log)

Does this work for you?

**Comment by E1izabeth** [comment]
Seems there is no error to see it in logs.
Could you create Sample SQLite database and check if it works with SQLite for you?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/1ec51370-cec7-476f-83d2-bc8cbf457912)

**Comment by E1izabeth** [comment]
> I cannot hit the Search button because it is disabled. I am attaching the screen recording again. Nothing happens.
> Screen.Recording.2024-04-30.at.17.00.24.mov

Have you clicked on the connection item here in the video? Maybe it's just not selected

**Comment by ufuk-ergin-carbon** [comment]
@E1izabeth , yes, after double clicking and selecting it the Object Type section became available and now it works as it should. Thanks for the help. Appreciated.
