### ISSUE TITLE
Schedule SQL Script execution

### ISSUE THREAD

**Issue by SEBJAK67** [dbeaver/dbeaver#2928]
Hello 
Could you tell me if it's possible to Schedule SQL scripts with DBEAVER and Windows Schedule task ? 
so as WINSQL Pro ? 
If it's possible ? could you help me to anderstand ? 

Thanks 
Sébastien 
[Creating a Task to Run a SQL Script.docx](https://github.com/dbeaver/dbeaver/files/1692703/Creating.a.Task.to.Run.a.SQL.Script.docx)

**Comment by benyanke** [comment]
I'm not sure if dbeaver supports this specific feature, but this seems like a better job for a shell script.

**Comment by serge-rider** [comment]
No, DBeaver doesn't support this.
However we are working on "headless" mode (ability to run commands/execute SQL in DBeaver without GUI).

**Comment by SEBJAK67** [comment]
Hello 
Thank's for your answers !
I'm interest with the mode you are working ! 
Please tell me when it's possible to test it 

Thanks

**Comment by drudd75077** [comment]
This would be awesome!

**Comment by serge-rider** [comment]
Adding to 5.2.x plan.
And I think this can be more general (we need ability to schedule almost any DBeaver command).

**Comment by SEBJAK67** [comment]
Hello 

I am waiting for this adding on dbeaver ! 
thank's

**Comment by surpavan** [comment]
It would be great combination with #4337

**Comment by serge-rider** [comment]
Now SQL script execution can be saved as a task.

Generic task scheduler can be used for script execute schedule.

**Comment by kseniiaguzeeva** [comment]
Verified. 
Task scheduler is available in EE version.
SQL script task is included in CE.
