### ISSUE TITLE
ollama support

### ISSUE THREAD

**Issue by morandalex** [dbeaver/dbeaver#29281]
**Is your feature request related to a problem? Please describe.**
I think is interesting testing local LLM for sql generation 

**Describe the solution you'd like**
I should be able to put in settings the ollama endpoint so I can create query or fix query with ai helper using local llm

for more information about ollama check https://ollama.com/

**Comment by Destrolaric** [comment]
@morandalex The ability to work with LLAMA was already added for DBeaver Pro editions. it will be available for commercial editions in the 24.1.0 release.
