### ISSUE TITLE
is there any way to start Dbeaver with old style SQL highlight?

### ISSUE THREAD

**Issue by Yigitttttttt** [dbeaver/dbeaver#29303]
is there any way to start Dbeaver with old style SQL highlight?
can i use something on dbeaver.ini or config.ini to do this?

I know i can change it with menu settings.

But I will share it to many users.

it should be on c:/dbeaver folder....

Thanks

**Comment by E1izabeth** [comment]
You can export all settings by the menu File->Export
![image](https://github.com/dbeaver/dbeaver/assets/28875055/35763324-19ad-47af-a55e-457fac0ee862)

Or if you want the concrete one, it's in `DBeaverData\workspace6\.metadata\.plugins\org.eclipse.core.runtime\.settings\org.jkiss.dbeaver.core.prefs` file called `SQLEditor.Highlighting.advanced.enable`
![image](https://github.com/dbeaver/dbeaver/assets/28875055/8aaa4287-5873-4eaf-ae5c-1f0c7c07e512)
