### ISSUE TITLE
Summarized Query execution

### ISSUE THREAD

**Issue by stefan3331** [dbeaver/dbeaver#29308]
### Description

When using statement "EXPLAIN" in queries, the query above is also executed. Example pictures are assigned.
![correct_execution](https://github.com/dbeaver/dbeaver/assets/43066302/ca80573b-51ce-4350-a2e9-456db15c7f17)
![incorrect_execution](https://github.com/dbeaver/dbeaver/assets/43066302/036d71a7-a557-4c4b-9375-452166389cae)
In second picture the execution order is wrong. The IDE executes both queries when trying to execute the second query.
This behaviour also happens when using statement "ANALYZE".

### DBeaver Version

Community Edition 24.0.3

### Operating System

Windows 11

### Database and driver

PostgreSQL Driver 42.7.3, PostgreSQL 14 and PostgreSQL 16

**Comment by E1izabeth** [comment]
We have already fixed it. The fix will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.
