### ISSUE TITLE
Like TOAD using (+) button to create new SQL Tab

### ISSUE THREAD

**Issue by Yigitttttttt** [dbeaver/dbeaver#29305]
Hi,

is it possible to have a button for create new SQL tab (it means F3 shortcut with button on UI)

Thanks

**Comment by E1izabeth** [comment]
Do you want `New SQL script` command? It can be called with `Ctrl+]` shortcut. Also default shortcuts can be changed in preferences. 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/3a9f2932-47b1-42fe-8542-42b901d8246d)

**Comment by Yigitttttttt** [comment]
I just want to click on UI to get new one without using shortcut. It s like
Toad For Oracle.

2 May 2024 Per 13:32 tarihinde Elizabeth ***@***.***> şunu
yazdı:

**Comment by E1izabeth** [comment]
There are a plant of ways to do it:
1.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/53f68f25-bf14-41ce-97f1-e10ea9efc0fc)

2.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/d61eeb2a-466d-463e-a9e5-9ba2db5f2005)

3. 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/6cf4d553-088a-4776-a26c-907c952f0046)

**Comment by Yigitttttttt** [comment]
Yes I know but it s a feature want. We want a button for this like Toad for Oracle

**Comment by E1izabeth** [comment]
I'm sorry, but I don't understand your request. Please clarify, what does "button for this like Toad for Oracle" mean. We don't use Toad, so we are unaware of this button.

**Comment by Yigitttttttt** [comment]
![Screenshot_20240502_175726_Gmail](https://github.com/dbeaver/dbeaver/assets/168306503/3b14ac77-543b-4d31-a78e-1c876fa8dfb5)

İf you get the screenshot. You'll see the + button. If you press this button it creates a new tab with same Db.

Thanks

**Comment by E1izabeth** [comment]
Right-clicking on any sql editor tab shows you the same button "New SQL Script"
https://github.com/dbeaver/dbeaver/issues/29305#issuecomment-2090138732

**Comment by Yigitttttttt** [comment]
For users in my IT department, this is not the user-habit. Toad has been
used for years and I am trying to migrate to Dbeaver because I think
Dbeaver is great.

2 May 2024 Per 18:10 tarihinde Elizabeth ***@***.***> şunu
yazdı:

**Comment by Yigitttttttt** [comment]
Hi,
Is there any progress?

**Comment by E1izabeth** [comment]
It wasn't assign to any milestone.

**Comment by E1izabeth** [comment]
We wonder how many people are interested in this feature.
Please vote for the issue with 👍 under the issue description to promote it to a higher priority.

**Comment by Yigitttttttt** [comment]
I think not so much in worldwide :D
Should I close this??

**Comment by E1izabeth** [comment]
Please, left it. Your issue has 2 likes already
