### ISSUE TITLE
problem when running the "use" database command

### ISSUE THREAD

**Issue by pedrobianco** [dbeaver/dbeaver#29301]
### Description

when running the command use to select a base it gives the error: Error SQL [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'use x' at line 10

### DBeaver Version

Comunity version 24.0.3.202404211624

### Operating System

Ubuntu Mate

### Database and driver

Mysql driver 8.0

### Steps to reproduce

Running command "use" in your database

**Comment by E1izabeth** [comment]
Please provide minimal script example and detailed steps to reproduce your issue.

**Comment by pedrobianco** [comment]
Good morning @E1izabeth, to reproduce just run the use command in your database as shown in print 
![Captura de tela em 2024-05-02 07-14-45](https://github.com/dbeaver/dbeaver/assets/27033867/ac314260-7c04-456d-b5ba-20118f7ce6ca)

Steps to reproduce:

1 - Running command use "database".
2 - syntax error will occur

**Comment by pedrobianco** [comment]
This problem did not occur in the previous version

**Comment by E1izabeth** [comment]
I can't reproduce your issue, but you may try Early Access version https://dbeaver.io/files/ea/ maybe it has been already fixed (we fixed a bug about queries execution).

**Comment by pedrobianco** [comment]
@E1izabeth I downloaded this early version and apparently the problem was resolved.
