### ISSUE TITLE
DBeaver not reading SQLite composite foreign keys correctly

### ISSUE THREAD

**Issue by aspatzier** [dbeaver/dbeaver#29309]
### Description

Since the release of DBeaver-Community 23.3.2 DBeaver does not read composite foreign keys in a SQLite database correctly - it worked perfectly before until version 23.3.1.
The problem persist until the latest version 24.0.3

The problem is that DBeaver seems to mixe up the columns referencing two table if it is defined with a composite foreign key. 

In the screenshot below one can see that the integer value **42** and the text string **RAHal2** turn up at the wrong place in the  command line generated by DBeaver (as indicated with the red arrow). Consequently, this results in an error message, since **RAHal2** is not put in parentheses and there interpreted as column - but in fact it is the field value of column  **ID_FSTkurz** (vise versa with **42** and **ID_Bef**)
> SQL Error [1]: [SQLITE_ERROR] SQL error or missing database (no such column: RAHal2)

![Screenshot 2024-05-02 at 11 35 09](https://github.com/dbeaver/dbeaver/assets/74900017/dc539110-1147-4e39-a436-e7db859e7e86)

The composite screenshot with parts of the DDLs of both tables provides information on table definition with focus on primary and foreign keys.

![Screenshot 2024-05-02 at 11 54 47](https://github.com/dbeaver/dbeaver/assets/74900017/b40ed422-4996-43cf-a404-56b1b53a9856)

I aware that it might not be best practice to use composite primary/foreign keys, but for my purposes I deem it necessary.

### DBeaver Version

Community Edition 24.0.3.202404211624

### Operating System

macOS Sonoma 14.4.1

### Database and driver

1. SQLite
2. Driver: SQLite JDBC 3.45.3.0 (org.xerial:sqlite-jdbc:RELEASE 3.45.3.0)

### Additional context

[error.log](https://github.com/dbeaver/dbeaver/files/15186820/error.log)

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by serjiokov** [comment]
So, I tried to reproduce it
1. Created tables  two tables with composite PK, composite FK, and references
 ```
CREATE TABLE firstTable(
	Id_FST TEXT,
	Id_SEC INTEGER UNIQUE DEFAULT (9999),
	Id_PR INTEGER,
	PRIMARY KEY (Id_FST, Id_SEC)
);
  
CREATE TABLE secondTable(
	Id_FST TEXT,
	Id_SEC INTEGER NOT NULL,
	Id_PR INTEGER,
	PRIMARY KEY (Id_PR),
	CONSTRAINT FK_First_Second FOREIGN KEY (Id_FST, Id_SEC)  REFERENCES  firstTable(Id_FST, Id_SEC) ON UPDATE CASCADE
);
  
```
3. Populated it by test data
DBeaver represent data correctly and navigates to references correctly 
![image](https://github.com/dbeaver/dbeaver/assets/32031248/024868bc-69f4-4e8a-ab91-bf29a554d8ab)
![image](https://github.com/dbeaver/dbeaver/assets/32031248/61bbe26e-3736-4608-844b-e433f7be7a02)
![image](https://github.com/dbeaver/dbeaver/assets/32031248/b5de3949-2add-4000-b47f-279cab3299dc)

**Comment by aspatzier** [comment]
Thank you for checking this issue @serjiokov 

As you had no problems with your test, I wondered if it might be a problem with my DBeaver installation. So I created a SQlite test database and two table referencing to each other with composite primary keys
```
CREATE TABLE TEST_A (
	ID_A TEXT ,
	ID_B INTEGER ,
	PRIMARY KEY ( ID_A, ID_B)
);
CREATE TABLE TEST_B (
	ID_A TEXT ,
	ID_B INTEGER ,
	ID_C INTEGER ,
	PRIMARY KEY (ID_A, ID_B, ID_C) ,
	CONSTRAINT FK_TEST_A_B FOREIGN KEY (ID_A, ID_B) REFERENCES TEST_A (ID_A, ID_B)
		ON UPDATE CASCADE
);
```

… and also encountered no problem after populating both table with sample data!

HOWEVER, the problem persist with my existing databases.
To check if the problem might be within those databases, I rebuild the tables using the existing table definitions in the new test database and
1. Populated the tables with test data
2. Imported the original data into the tables
In both cases the same problem in the new test database - as described in my initial post (i.e. still working in DBeaver 23.3.1, but not working in the actual version 24.1.2).

It might perhaps help to say that `on update cascade` works fine.

I have no idea where the problem arises.

Perhaps you can check if there is an error in my original table definitions, so I attach them:
[Sqlite_table_definition.txt](https://github.com/user-attachments/files/16189890/Sqlite_table_definition.txt)

**Comment by serjiokov** [comment]
Hi @CommunyAS, 
Sorry but can not reproduce on product version 24.1.3 
`Driver SQLite JDBC 3.42.0.0 Server SQLite 3.42.0`
![image](https://github.com/user-attachments/assets/08cdac9d-c24c-4e40-b74b-d1f7cf4c85ab)
Could you update product on latest version or update driver version?

**Comment by serjiokov** [comment]
@CommunyAS Please provide details regarding your driver version?

**Comment by aspatzier** [comment]
Sure:

DBeaver Community 24.1.2

SQLite JDBC 3.46.0.0
(was installed and, to be sure, updated just now)

![Screenshot 2024-07-16 at 11 06 19](https://github.com/user-attachments/assets/33354494-1e4b-4bea-b010-77c4769f6fc5)

**Comment by serjiokov** [comment]
I guess a reason of issue in key ordering 
The composite primary key created like
`PRIMARY KEY (ID_FSTkurz, GrabBefNr)`
in UI presented like 
 
![image](https://github.com/user-attachments/assets/60e68b41-34fb-40f1-9d35-4092655c270d)

same for table Ind_Skelett
`PRIMARY KEY (ID_FSTkurz , GrabNr , IndNr) `
![image](https://github.com/user-attachments/assets/2e4f4e39-fe59-4b27-91e5-85f2d69acb2a)

The generated statement has a wrong field order 
`SELECT x.* FROM BEFUNDE x  WHERE (GrabBefNr = fst.2) AND (ID_FSTkurz = '0')`

The original system info contains correct order of fields 
![image](https://github.com/user-attachments/assets/f85e59b0-9538-4de6-ae44-183d4e2133e5)
![image](https://github.com/user-attachments/assets/207fb437-385b-4907-8363-723643d44cec)

**Comment by serge-rider** [comment]
Unfortunately previous fix broken PK naming.
Proposing another PR which fixes only ordering (SQLite driver returns columns in a wrong order by `orderPosition` attributes is valid so we can reorder them on DBeaver side)
