### ISSUE TITLE
Kaspersky Endpoint Security for Windows 12.1.0.506 thinks dbeaver-cli.exe is malware after version 24.0 and later

### ISSUE THREAD

**Issue by Yigitttttttt** [dbeaver/dbeaver#29302]
### Description

Kaspersky Endpoint Security for Windows 12.1.0.506 thinks dbeaver-cli.exe is malware after version 24.0 and later

### DBeaver Version

24.0.3

### Operating System

windows 10

**Comment by E1izabeth** [comment]
Are you talking about portable version or installed?

**Comment by Yigitttttttt** [comment]
Portable version

2 May 2024 Per 16:01 tarihinde Elizabeth ***@***.***> şunu
yazdı:

**Comment by E1izabeth** [comment]
Thank you

**Comment by Yigitttttttt** [comment]
You're welcome!

2 May 2024 Per 18:11 tarihinde Elizabeth ***@***.***> şunu
yazdı:

**Comment by serge-rider** [comment]
It is classic false positive.
It no longer reports issues (in version 24.0.4 at least)

**Comment by Yigitttttttt** [comment]
Glad to hear it!

6 May 2024 Pzt 10:32 tarihinde Serge Rider ***@***.***> şunu
yazdı:

**Comment by Yigitttttttt** [comment]
Hi, today i downloaded 24.0.5 and problem still exist.
