### ISSUE TITLE
Ocient - DDL generating incorrectly 

### ISSUE THREAD

**Issue by cwoolwine-ocient** [dbeaver/dbeaver#29307]
### Description

When using an Ocient database, attempting to export any table with values of `BIGINT` and `SMALLINT` turns the values into `LONG` and `SHORT` respectively 
![image](https://github.com/dbeaver/dbeaver/assets/124913069/99664c8a-0c39-414a-b19b-7457078e5f4b)
![image](https://github.com/dbeaver/dbeaver/assets/124913069/ecb8ae42-d77a-4b84-aa2c-d01722b8cc55)

### DBeaver Version

24.0.3

### Operating System

Ubuntu 20.04.5 LTS

### Database and driver

1. Database name and version: Ocient
2. Driver name and version: Ocient JDBC 3.1.4

### Steps to reproduce

1. Create a table with a BIGINT value or a SMALLINT value
2. Generate DDL

### Additional context

This happens because of the way our driver reports metadata into DBeaver. To fix this I plan on extending `GenericMetaModel.java` into the Ocient model. I believe this is all that needs to be done but please correct me if I'm wrong.

**Comment by E1izabeth** [comment]
Its just an alias name used for this type. SMALLINT is the same as SHORT, BIGINT is the same as LONG.

**Comment by LonwoLonwo** [comment]
Hello @cwoolwine-ocient 

Could you execute this generated by DBeaver DDL? Will it return an error?
If not, you need to provide more information about why you think this behavior is incorrect. As @E1izabeth said, it is just data type names aliases.

**Comment by cwoolwine-ocient** [comment]
@LonwoLonwo Ocient does not support these types. The DDL is not executable on an Ocient database.

**Comment by cwoolwine-ocient** [comment]
Hi- I've been working on a solution for this but I can't seem to push my branch to remote. Do I need permissions?

**Comment by E1izabeth** [comment]
Please take a look at this guide https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code
You need to fork the repo first

**Comment by MashaKorax** [comment]
Thanks for your report.

**Comment by mjsterckx** [comment]
Hey everyone, I'm on the same team as @cwoolwine-ocient at Ocient and I will be taking over this ticket, if that's okay with you. The problem is that the generic `getObjectDDL` method does not return SQL that can be executed by our Ocient driver, so I'll add a new `OcientMetaModel` file with a custom implementation for that method. Should have a PR from my fork in the next day or 2, unless there are any objections/comments.

**Comment by E1izabeth** [comment]
Hi, @mjsterckx ! Thank you for sharing your plans with us.
