### ISSUE TITLE
[feature request] Option: restore last tree state on app start

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#2930]
I suppose it would be useful feature. Sometimes I work many days with the same db objects in many databases and I have to restore object tree state after every app restart.
Thank you

**Comment by serge-rider** [comment]
This can be helpful.

**Comment by uslss** [comment]
Already implemented
![image](https://user-images.githubusercontent.com/31996417/109970676-61dbc280-7d06-11eb-8392-79dce53f6daa.png)
