### ISSUE TITLE
[feature request] All sql-scripts in one tab

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#2931]
This is just an idea. I don't know if you will treat it as useful.

Before dbeaver I used SQL Manager for PostgreSQL and it has the following feature. All scripts of the db connection use only one tab and you can switch between script files inside the tab, create and delete them quickly.

![default](https://user-images.githubusercontent.com/16996529/35784992-af5dc076-0a68-11e8-882a-07c8819619e2.png)

I use sql-editor to create scripts. When the script is rather big and complex, I create many variants of it, split it to parts and test that parts separately. For that purpose I create many files, switch between them trying to find the best variant and when the main script is ready I delete all the files. 

Maybe you'll find better solution.
Thank you

**Comment by serge-rider** [comment]
In DBeaver you can quickly open scripts associated with current connection. It is the most basic "Open SQL Editor" command (<kbd>F3</kbd> or <kbd>CTRL+[</kbd> on newer versions).
You can see script short preview and you can filter scripts by name.

Isn't this what you need? I'm not quite understand how scripts organized in your screenshot. 
What is `1, 14, 4` etc? Script names? File names?

**Comment by offstate** [comment]
1, 14, 4 etc is script names (I think they store them in some db table but I don't care) and they are sub-tabs in only one script tab.

The main problem is that every script file takes one tab in tabs line. When you open several db objects and many scripts from different connections they overfill the width of the screen. The tab names are truncated and some tabs are hidden in drop-down menu and you cannot see them all at once. 
When the names of script tabs are truncated you cannot see the name of the script and tabs of the one connection looks the same.

**Comment by serge-rider** [comment]
I think this can be implemented as a separate view with list of scripts associated with current connection.

**Comment by serge-rider** [comment]
After all I think this will be redundant. We already have "Open SQL Editor" command which shows panel with all scripts associated with current connection. moreover you can search in it.
Maybe we could improve UI of this panel but having yet another panel for the same function doesn't look like a good UI improvement.
