### ISSUE TITLE
Locked SQL in a SQL editor cause other SQL in other SQL editor keep hanging abnormally 

### ISSUE THREAD

**Issue by liuyuanyuan** [dbeaver/dbeaver#2934]
Serge~
I found a problem:
      I executed a locked SQL （caused by some PostgreSQL exclusive lock ) in a SQL Editor,
after that, if  I execute other SQL in other SQL editor, then all the other SQL will keep hanging until I cancel the Locked SQL.
     Normally, the SQL has exclusive lock should hang,  meanwhile other SQL should not.
     Please have a look, thanks and regards~

**Comment by serge-rider** [comment]
@liuyuanyuan Umm, do you have some SQL snippet to reproduce that?
Generally DBeaver doesn't make anything special about transactions, all locks happen on server side. Maybe this behavior is affected by transaction isolation level? You could try to change it in main toolbar/menu.

**Comment by liuyuanyuan** [comment]
@serge-rider Thanks for your reply, I'll try that~
