### ISSUE TITLE
[Feature request] Triggers in editors to call shell commands

### ISSUE THREAD

**Issue by diegosiao** [dbeaver/dbeaver#2935]
Hi, it would be really great to have a chance to associate shell commands before or after some general database actions with data related to them.

**E.g. 1:** After compiling an Oracle Package it would be possible to call '**my-cmd [connection-name] [package-name]**' to save the changes made locally for versioning purposes.

**E.g. 2:** After closing a connection it would be possible to call a company specific tool or web page to document the work done.

**Comment by serge-rider** [comment]
Currently DBeaver supports only connection-related events - you could try it for your second case:
![image](https://user-images.githubusercontent.com/6398845/36071313-8ff12d86-0f1d-11e8-836b-e85bd8d5c0a6.png)

Regarding package compile and other commands. We'll need something more generic here.
Potentially it is possible to tie OS process run on any DBeaver command execute.
That's a bit tricky and will require new config UI.
But possible, if more people will vote for it.

**Comment by serge-rider** [comment]
Please create separate ticket for particular improvements of this feature.
