### ISSUE TITLE
Context Menu Over Version Update Notification

### ISSUE THREAD

**Issue by chtuqu** [dbeaver/dbeaver#2936]
Seems like a minor bug, might be an Eclipse/Cocoa GUI issue.
I've fired DBeaver and went right-clicking on a tab straight away. That's when the version update notification appeared. The context menu was visible in front of the notification window for some reason and was completely unusable. No selections or clicks were possible. Closing the notification window solved the problem.
DBeaver v4.3.3.1, macOS High Sierra 10.13.2.
<img width="689" alt="screen shot 2018-02-05 at 14 53 45" src="https://user-images.githubusercontent.com/15345359/35811736-4a9e8bc4-0aa0-11e8-9e68-d06b690e19c2.png">

**Comment by serge-rider** [comment]
Thanks for report. Will try to catch this..

**Comment by uslss** [comment]
there is no update on ticket for a long time. ticket closed
