### ISSUE TITLE
Eclipse Oxygen.2 + DBeaver - error opening ER Diagram

### ISSUE THREAD

**Issue by LeonidMew** [dbeaver/dbeaver#2937]
Installed latest stable __Eclipse PDT and DBeaver__. All work fine in DBeaver except one thing - when clicking __ER Diagrams__ for database or table following errors appear:
[first error][1] , [second, after clicking ok in first error dialog][2] , [part of error log][3]

> java -version
> Picked up JAVA_TOOL_OPTIONS: 
> openjdk version "1.8.0_151"
> OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12)
> OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

Checked this only on mysql database, user with all granted permissions.

> mysqld --version
> mysqld  Ver 5.7.21-0ubuntu0.17.10.1 for Linux on x86_64 ((Ubuntu))

  [1]: https://i.stack.imgur.com/Budg0.png
  [2]: https://i.stack.imgur.com/FgkHs.png
  [3]: https://paste.ubuntu.com/26516953/

**Comment by serge-rider** [comment]
I can't reproduce this. This error means "out of native GUI handles". This may appear in case of GUI handles leak or in case of opening of huge number of GUI resources.
Are there some particular steps to reproduce? Does this happen after DBeaver restart?

**Comment by LeonidMew** [comment]
This happend after dbeaver restart. Im not opening hude number of gui resources, this is latest eclipse ptd, with few plugins. Also I have try to add more memory in eclipse.ini  - 2gb.

If I go to one table, got error, then go to another table - then error not appears, when clicking on er diagram, just light gray background displayed in tab.

When installing DBeaver, I miss installing GEF and draw2k. Then add update site for GEF and installed both, latest versions. I guess it was possible without adding update site, just unable to find them in list of all packages and categories for oxygen.2

**Comment by LeonidMew** [comment]
Reinstalling dependencies
Deleting:
  Draw2d	3.10.100.201606061308	org.eclipse.draw2d.feature.group	Eclipse GEF
  GEF (MVC)	3.11.0.201606061308	org.eclipse.gef.feature.group	Eclipse GEF

Installing: From original update sites of oxigen.2, eclipse 4.7.2
Checked: "Only software applicable to target environment"
  Modeling	
    GEF (MVC) SDK	3.11.0.201606061308
Unable to find Draw2D in this repositories.
Install following(description says draw2d included) from Oracle Enterprise Pack for Eclipse 12.2.1.6 Dependencies:
  GEF (Graphical Editing Framework)	
    GEF All-In-One SDK	3.11.0.201606061308

**Comment by LeonidMew** [comment]
Case sensitive search found Draw2d in Oracle Enterprise Pack for Eclipse 12.2.1.6 Dependencies:
  GEF (Graphical Editing Framework)	
    Draw2d	3.10.100.201606061308
> Your original request has been modified.
>   "Draw2d" is already present because other installed software requires it.  It will be added to the installed software list.

__Still the same error__

**Comment by LeonidMew** [comment]
Find some other error/warning in error log, appears before above errors:
eclipse.buildId=4.7.2.M20171130-0510
java.version=1.8.0_162
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=ru_RU
Framework arguments:  -product org.eclipse.epp.package.php.product -server
Command-line arguments:  -data file:/home/lenya/Eclipse-Workspace/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.php.product -server

org.jkiss.dbeaver.model
Warning
Thu Feb 08 06:09:27 MSK 2018
Some data source listeners are still registered: [org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageProperties@c3b71d2]

**Comment by uslss** [comment]
Hi @LeonidMew , is an issue still actual for you?

**Comment by uslss** [comment]
there are no updates for ticket more than a month.
ticket closed
