### ISSUE TITLE
PostgreSQL: generate full DDL for Foreign Keys (as an edit workaround)

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#2938]
I find it very hard to edit foreign keys in DBeaver. I know Postgres doesn't allow altering FK's but at least DBeaver could generate DDL's that would be a ready SQL template to do just that. 

For example, currently when I right click on a FK and choose Generate SQL -> DDL then I get this:

`FOREIGN KEY (location_id) REFERENCES mag.locations(id) ON UPDATE CASCADE ON DELETE CASCADE;`

It's better than nothing but I can't do much with it on its own. Compare to how pgAdmin generates DDL:

```
-- Foreign Key: mag.stores_location_id_fkey

-- ALTER TABLE mag.stores DROP CONSTRAINT stores_location_id_fkey;

ALTER TABLE mag.stores
  ADD CONSTRAINT stores_location_id_fkey FOREIGN KEY (location_id)
      REFERENCES mag.locations (id) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE CASCADE;
```
This is a fully working SQL which I can quickly edit to drop and re-create the FK. I suspect adding full-fledged altering of FK's via UI would be a lot of work but if only DBeaver generated rich FK DDL's like the above then this would help a lot and could be used as a quick method to alter FK's. The first comment line with the FK name is not that important IMO.

**Comment by offstate** [comment]
In addition I noticed that there is no FK name in the table's DDL.
The script should be:
```
CREATE TABLE foo (
bar_id
....
CONSTRAINT fk_bar FOREIGN KEY (bar_id) REFERENCES bar(id) ...
)
```
(the same for other constraints)

**Comment by lemon-juice** [comment]
Good catch. For table DDL there is also no name for primary and unique keys. The CONSTRAINT keyword with the index name is missing for FK's, PK's and unique constraints. I don't know if that should not be for a separate bug but of course it would be best if all these issues were fixed in one go as it were.

**Comment by serge-rider** [comment]
Good point.
Both these issues (missing constraint names and missing ALTER TABLE in constraint DDL) will be fixed in the next version, thanks for noticing.

**Comment by lemon-juice** [comment]
Thanks, this is great news!

Will we also get the DROP CONSTRAINT query in the FK DDL? In the source code I noticed this line:

`String OPTION_INCLUDE_OBJECT_DROP = "script.includeDrop";`

Does it mean this is can be configured? If so then where? I haven't found such an option in Preferences.

**Comment by serge-rider** [comment]
@lemon-juice it is not configurable. This is used internally for databses which don't support SQL like CREATE OR REPLACE.

**Comment by lemon-juice** [comment]
Ok, I understand. In that case could we also have the `ALTER TABLE ... DROP CONSTRAINT ...` generated automatically for DDL? It can be commented out just like in the sample from pgAdmin. This makes altering FK's easier because all the code has been generated and we only have to edit what we want to alter.
