### ISSUE TITLE
Questions about new PostgreSQL features

### ISSUE THREAD

**Issue by ygoe** [dbeaver/dbeaver#2940]
The release notes for version 4.3.4 say:

* PostgreSQL: database switch support was added
* PostgreSQL: default driver version was updated (42.2.0)

I can't see anything of this after installing the new version. What do these notes mean and what do I have to do to see the changes?

PS: I've added DBeaver to my Windows 10 start menu as a tile. That tile was non-functional after installing the new version over the previous release. I had to remove that tile and re-add it from the start menu. I don't think the installation path has changed but I don't know how these tiles work.

**Comment by GiantCrocodile** [comment]
> I can't see anything of this after installing the new version. What do these notes mean and what do I have to do to see the changes?

The database switch support has to be enabled in the DBeaver settings because it changes default behaviour.

**Comment by ygoe** [comment]
Mhm, can you please provide details? I don't know where to look, haven't found it in the settings.

And I don't see any updated PostgreSQL driver, even though drivers are configured for auto-update in the settings. In fact I can't find any version number that comes close to what's in the release notes. All numbers I can find (and it's several) are much different.

**Comment by serge-rider** [comment]
You should enable these settings in connection properties:
![image](https://user-images.githubusercontent.com/6398845/36071513-66572176-0f20-11e8-9a44-5de79119ce24.png)

Note: you must use `PostgreSQL` driver, not `PostgreSQL Generic`

**Comment by ygoe** [comment]
I have found this option by chance yesterday. I believe it appeared later than installing the DBeaver update.

But still, it doesn't work correctly. When I open the first database, I can access its tables normally. When I switch to another database and try to access one of its tables, I get an error message saying I don't have access. When I use a separate configured connection that initially uses the second database, I can access it just fine. So the multi-database thing may be able to connect to other databases, but fails to let me do anything with them.

**Comment by ygoe** [comment]
Umm, I can't reproduce it either. Maybe I just had to restart the app to make it work. Possibly last time I changed the configuration and connected to the server immediately instead of waiting a day.

**Comment by serge-rider** [comment]
Ok.
Then closing as resolved.
