### ISSUE TITLE
GC Overhead Limit

### ISSUE THREAD

**Issue by jerherder** [dbeaver/dbeaver#2941]
HEllo

i got this error on a postgres table of 250000 rows and many columns. for 100000 rows,no problem for display. but after 100000 problem.

its works with 19 columns but when i set 20 columns, i have the error java heap space or GC Overhead Limit

have you a solution?

i use DBEAVER V 4.3.3

**Comment by serge-rider** [comment]
Do you fetch all 100000 rows in grid?
Why do you need this? You could try to export them.

In any case - if you want to increase maximum memory available for DBeaver use command line parameters (or edit dbeaver.ini file) - https://github.com/dbeaver/dbeaver/wiki/Command-Line

**Comment by jerherder** [comment]
Hello

yes i fetch all the 100000 rows in grid.

i already increase maximum memory to 4 gb but the same problem. and the export doesn't works.

**Comment by serge-rider** [comment]
See comments in #2209
