### ISSUE TITLE
View JSON

### ISSUE THREAD

**Issue by fabiopedrosa** [dbeaver/dbeaver#2944]
Sometimes there's JSON stored inside string fields in both mysql and cassandra, and I'd love to be able to view these fields pretty-formatted. Maybe a button in the `Value viewer` to present as JSON?

**Comment by offstate** [comment]
It would be nice to have this feature also for Postgres JSON/JSONB data types

**Comment by serge-rider** [comment]
@offstate it is already there (but only in EE version).

**Comment by fabiopedrosa** [comment]
@serge-rider can you point me to the right code class/section I would need to change to make this happen for cassandra?

**Comment by serge-rider** [comment]
Sorry for late reply.
For PostgreSQL just open any table with JSON/JSONB columns. You can see/edit formatted JSON in value view panel (<kbd>F7</kbd>).

**Comment by BrutalSimplicity** [comment]
I am currently using the Postgres with JSON/JSONB support and it still seems like the json view feature is incomplete.

![image](https://user-images.githubusercontent.com/5298126/43432040-7a67d67e-9436-11e8-8a0b-76ba39c4082e.png)


On my Mac I can view the json in the value panel, but there is no whitespace formatting, so I can't easily see nested or array fields. This is particularly difficult when the json payload is large. Is there an option to view with pretty-print and multi-line formatting, much like you view json in a browser or text editor extension.

The end result above would look something like this in my mind.

```
{
    "PID": "CHVVOYM",
    "Tags": [],
    "Tier": "Tier3",
    "Gtins": [
        {
            "Id": 400000000021525,
            "Score": 100
        }
    ],
    "Title": "",
    "Images": [],
    "Offers": [],
    "Quality": 0.0,
    "Reviews": [],
    "CreatedAt": "2018-07-11T20:15:49.872562Z",
    "SaleLinks": [],
    "SalesRank": null,
    "UpdatedAt": "2018-07-11T20:15:49.872567Z",
    "Attributes": [],
    "Categories": [],
    "ClusterKey": null,
    "Blacklisted": false,
    "Description": null,
    "ReviewCount": 0,
    "DisplayTitle": null,
    "ReviewRating": 0.0,
    "Subscriptions": [],
    "AggregationIds": [],
    "MediaContentScore": {
        "Type": "Global",
        "Score": 0,
        "Weight": 1,
        "Version": "1.0",
        "CreatedAt": "2018-07-11T20:15:49.763946Z",
        "UpdatedAt": "2018-07-11T20:15:49.763946Z"
    },
    "TotalQualityScore": {
        "Type": "Global",
        "Score": 0,
        "Weight": 1,
        "Version": "1.0",
        "CreatedAt": "2018-07-11T20:15:49.763946Z",
        "UpdatedAt": "2018-07-11T20:15:49.763946Z"
    }
}
```

**Comment by plessmann** [comment]
I hope json format for the values panel will be added soon. In times more and more nosql data is transferred and needs to be stored this would be a helpful feature. 
Currently only XML and Simple Text is supported (for mysql connections).

**Comment by tati-kru** [comment]
@plessmann , the JSON format is supported in the DBeaver EE version only. You could download and try it here: https://dbeaver.com/download/

**Comment by kevinchou-pge** [comment]
Holy Cow! You right click and select auto-format! I can't believe I just found how to do it in 2021.
