### ISSUE TITLE
"Ambiguous column" when sorting in results window

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#2946]
I press the column header in query results window to sort the data and I receive an error if the result set has another column with the same name. Only when data does not fit on the result page

Try to sort this:
```
with t as (select generate_series(1,100) f)
select *
from t t1,t t2
```

**Comment by serge-rider** [comment]
Yes, it fails because column name is ambiguous. 
But do you see any solution/workaround?

**Comment by offstate** [comment]
Here are some ideas.
If you cannot find out full name of the column, in Postgres and Mysql you can do like this:
```
with t as (select generate_series(1,100) f)
select *
from t t1,t t2
order by 2
```

Another way is to give your own aliases to the ambiguous columns:
```
with t as (select generate_series(1,100) f)
select * --->t1.f as t1_f, t2.f as t2_f
from t t1,t t2
order by t2_f
```
but in this case you will need to parse the script somehow

Third way is to give aliases to all the columns before sending sorting query. When result returned you can map new data to prior result columns.  (only Postgres)
```
-- original query (remember column names)
with t as (select generate_series(1,100) f)
select *
from t t1,t t2

-- sorting query (when user clicks sort button)
select * 
from(
   with t as (select generate_series(1,100) f)
   select *
   from t t1,t t2
) wrap (wrap_f1, wrap_f2)
order by wrap_f2

-- then map data to original column names
```

**Comment by serge-rider** [comment]
Patching source query is always a bad idea.
After all I think only the first way is more or less standard and could work.
Perhaps we'll need one more SQL dialect config option.

**Comment by serge-rider** [comment]
This will be fixed in the next version (we'll use numeric attribute references in such cases)

**Comment by KrisDeCooman** [comment]
For me this issue is still not resolved..Can execute a query in DBeaver but when I click to sort a column it give me 'ORA-00918 : column ambiguously defined' Same action works perfect in SQLDeveloper so it's still a bug in DBeaver
