### ISSUE TITLE
Dates from DB2 on IBM i are displayed as "null"

### ISSUE THREAD

**Issue by savadgecayet** [dbeaver/dbeaver#2948]
I'm using DBeaver 4.3.4
I connect to an IBM i system running V7R1.
I've created a dummy file containing a field of type "date"
When the date is before 1940-01-01, it displays an "null", even when the date is correct.
Here's the contents of my file:
![image](https://user-images.githubusercontent.com/36272161/35982339-d51adde2-0cef-11e8-898b-ace6b8719ecc.png)
and here's what DBeaver displays:
![image](https://user-images.githubusercontent.com/36272161/35982375-f4e37972-0cef-11e8-8ca0-6bf13f7e23b4.png)

Is this a question of settings somewhere or is this a bug ?
Thanks for your help.

**Comment by serge-rider** [comment]
I think there should be some errors when DBeaver reads these values.
Please check Error Log view or error/debug logs (https://github.com/dbeaver/dbeaver/wiki/Log-files).

**Comment by savadgecayet** [comment]
I had previously made some tests changing some of the drivers settings (tab Adv. Parameters, Formatting) but without success.
I've changed the date format and date separator in the driver's properties and it works fine.
![image](https://user-images.githubusercontent.com/36272161/36200734-e83a6996-117d-11e8-96a4-4b4ff3b697bf.png)

![image](https://user-images.githubusercontent.com/36272161/36200758-ffd20848-117d-11e8-8e99-52b9d29e22c9.png)

By the way, serge-rider, I didn't find anything relevant in the logs.  Thanks for your help.

**Comment by serge-rider** [comment]
Thanks for information!

**Comment by JMarkMurphy** [comment]
Just a FYI on this. The date separator property is ignored when the date format is iso. And just to maintain consistency, I like to set time format to iso as well.
