### ISSUE TITLE
PostgreSQL - "Go to reference" icon on table data view doesn't appear when foreign key is of type text

### ISSUE THREAD

**Issue by PedroSolintel** [dbeaver/dbeaver#2949]
Usually the following icon appears when the column is referencing a row in another table:

![dbeaver 4 3 4 - tabcategoriadre 2018-02-08 14 28 24](https://user-images.githubusercontent.com/28440086/35984832-6140ce80-0cdc-11e8-84b6-d0ba0e88a80f.png)

However, this icon doesn't show up when column type is `TEXT`.

**Comment by lemon-juice** [comment]
I've checked in one of my tables and the icon does appear for TEXT columns, it's just on the left side. So perhaps there are some specific circumstances where this doesn't work.

**Comment by serge-rider** [comment]
@lemon-juice Since 4.3 link icons are rendered according to cell justification (on the left for numbers, on the right for others).
@PedroSolintel this link appears if column is included in a foreign key. It doesn't matter what data type this column has.

**Comment by PedroSolintel** [comment]
It happened that I was just so used to looking for the icon on the right side of the cell that my brain just ignored its existence when it appeared on the left side. Sorry for the inconvenience.

**Comment by serge-rider** [comment]
Ok :)
