### ISSUE TITLE
Issue: Mac keyboard shortcut 'New SQL Editor' (^F3) doesn't work

### ISSUE THREAD

**Issue by chrisdabel** [dbeaver/dbeaver#2950]
The default keyboard shortcut `^` + `F3` is not working to open a 'New SQL Editor' tab on a Default Macbook Pro, with Sierra or High Sierra installed.

It requires pressing `control` + `fn` + `F3`, which doesn't work, due to the existing Mac shortcut "Move focus to the Dock".

Workaround:  Open DBeaver Preferences > Bind the Action to an alternate keyboard shortcut, such as `control` > `]`.

**Comment by serge-rider** [comment]
Yes, good point.
F3 never was a good shortcut (as well as all other FX shortcuts - we got rid of most of them). I like <kbd>CTRL+[</kbd> and <kbd>CTRL+]</kbd> shortcuts for "Open SQL editor" and "Open New SQL Editor" commands. 
Thanks for idea :)
