### ISSUE TITLE
Copy text from the statistics tab

### ISSUE THREAD

**Issue by Cris70** [dbeaver/dbeaver#2952]
Hi, thank you for your great software!
I have one feature request: when I execute a DML statement, DBeaver gives results in a "Statistics" tab.
It would be very nice if I could copy the text from this tab: presently it is not possible.
It would also be very nice if we could have the statistics in text format too, just like it can be done with the results tab.
T.I.A.
Cris

**Comment by serge-rider** [comment]
Good point. Copy command will be added in the context menu (in 4.3.5).

Regarding text form - there is a FR #667 for that.
