### ISSUE TITLE
MySQL triggers with fully-qualified database name

### ISSUE THREAD

**Issue by rscs** [dbeaver/dbeaver#2955]
DBeaver is creating MySQL triggers with fully-qualified database names for the CREATE TRIGGER and ON targets (as shown in the example below). This becomes a problem when trying to use mysqldump to copy data into a database with a different name. The mysqldump fails because it cannot find the database specified in the trigger.

After reading [this stackoverflow post](https://stackoverflow.com/questions/4001071/mysqldump-fully-qualifies-triggers-with-database-name,) it looks like mysqldump uses the CREATE TRIGGER statement exactly how it was originally created. So if the trigger is created with a database name, the database name will be included in the dump. If it was created without the database name, there will be no database name in the dump.

I was able to confirm this by dropping and manually re-creating my trigger without the database name using SQL, but if I use the DBeaver GUI, the GUI seems to always include the database name. I recommend the GUI should NOT include the database name after the CREATE TRIGGER and the ON.

```
DELIMITER $$
$$
CREATE TRIGGER dbname.test
AFTER INSERT
ON dbname.matrix_zones FOR EACH ROW
IF NEW.zoneId IS NOT NULL AND new.providerId IS NOT NULL THEN
    REPLACE INTO matrix_providers_zones(zoneId,providerId) VALUES(NEW.zoneId,NEW.providerId);
END IF $$
DELIMITER ;
```

**Comment by serge-rider** [comment]
DBeaver doesn't insert database name in CREATE TRIGGER queries. Dumps are generated by mysqldump utility. So I just can't realize what can we do from DBeaver side to help in this problem.

BTW I've fixed trigger source extraction in DBeaver (it missed CREATE statement)

**Comment by rscs** [comment]
The example I showed ...

```
DELIMITER $$
$$
CREATE TRIGGER dbname.test
AFTER INSERT
ON dbname.matrix_zones FOR EACH ROW
IF NEW.zoneId IS NOT NULL AND new.providerId IS NOT NULL THEN
    REPLACE INTO matrix_providers_zones(zoneId,providerId) VALUES(NEW.zoneId,NEW.providerId);
END IF $$
DELIMITER ;
```

... is exactly how the DBeaver GUI created the trigger. You'll see DBeaver uses ```dbname.test``` and ```dbname.matrix_zones``` in the CREATE statement. I am saying it should not include the ```dbname``` and instead simply use ```test``` and ```matrix_zones``` respectively. Drop off the ```dbname.``` prefix.

If one includes ```dbname``` in the CREATE statement, mysqldump will include the ```dbname``` in its output. If one does NOT include ```dbname``` in the CREATE statement, mysqldump will not have it in its output.

**Comment by serge-rider** [comment]
Ah, I see.
Agreed ,this should be fixed. I can use `USE dbname` before trigger creation to create it in appropriate database and to avoid explicit db name in CREATE TRIGGER statement.

**Comment by serge-rider** [comment]
Please check how it works now in EA version - https://dbeaver.jkiss.org/files/ea/

**Comment by rscs** [comment]
Working great in the EA version. Thanks for the quick turnaround!
