### ISSUE TITLE
Extract SQL from source code doesn't work properly anymore

### ISSUE THREAD

**Issue by alesc2000** [dbeaver/dbeaver#2956]
Copy from source:
"\tSELECT * \n" +
                "\tFROM table \n" +
                "\tWHERE id = 1" ;
Paste in sql editor doesn't remove \n and \t.
Auto format / Extract SQL from source code - is checked.
It worked well until update
Version 4.3.4, Ubuntu 17.10

**Comment by serge-rider** [comment]
Works fine for me. 
Please make sure that this option (Extract SQL from source code) wasn't redefined for particular data source (<kbd>ALT+Enter</kbd> in SQL Editor->SQL Formatting)

**Comment by alesc2000** [comment]
No, there's no special setting defined for any data source... 

![screenshot from 2018-02-10 16-11-23](https://user-images.githubusercontent.com/19900533/36062858-2b62e5e4-0e7d-11e8-9c2d-493e996cb066.png)

**Comment by serge-rider** [comment]
Yep. It works only in MySQL.
It is a bug in the recent DBeaver version. 
Thanks for report!

**Comment by alesc2000** [comment]
Thanks! :)
