### ISSUE TITLE
Improving the MySQL Sessions view

### ISSUE THREAD

**Issue by rscs** [dbeaver/dbeaver#2957]
There is only one reason I still have Workbench installed on my computer: the Sessions view for MySQL is not as robust in DBeaver. A few things I can think of:

1 - The ability to see the actual query being performed as a column in the tabular output. In DBeaver, I have to click on a specific query to see the details in the info window below, but I'd like to be able to see all queries currently being executed so I can quickly eye which one(s) may be causing an issue if there's a deadlock or other problem I am troubleshooting.

2 - The "Hide sleeping connections" checkbox in Workbench is also great because I can condense the view to only show what's actively being run.

3 - The "Refresh Rate" option in Workbench is nice to be able to automatically refresh the sessions output every few seconds instead of manually.

4 - A **really** awesome feature would be enabling a new connection settings checkbox option that can mark a connection as "AWS RDS compatible" or something similar. Because of the AWS RDS permissions model, the normal ```KILL CONNECTION``` and ```KILL QUERY``` commands do not work. Instead, AWS RDS provides two stored procedures to simulate that functionality: ```CALL mysql.rds_kill(thread-ID)``` and ```CALL mysql.rds_kill_query(thread-ID)```. If "AWS RDS compatible" mode is enabled on a connection, then using "Kill Session" or "Terminate Query" in the Sessions view would call these special RDS stored procedures instead of ```KILL CONNECTION``` and ```KILL QUERY```.

**Comment by serge-rider** [comment]
1 and 2 will be added in 4.3.5.
Please create separate feature request for 4.

**Comment by rscs** [comment]
Thank you, @serge-rider ... I've broken out 4 into #2960. Should I break 3 out as a separate ticket too?

**Comment by serge-rider** [comment]
Yes, please. It is more generic than just MySQL session manager.

**Comment by rscs** [comment]
Thanks, #2961
