### ISSUE TITLE
EXPORT results (csv) after REFCURSOR and Shift+enter 

### ISSUE THREAD

**Issue by jfcjfc** [dbeaver/dbeaver#2962]
oracle 11gR2 XE, dbeaver 4.3.4, Ubuntu 17.10
=> procedure, dynamic pivot sql with refcursor, and shift+enter as the 2207 issue for looking results

view image - 
REFCURSOR in the result panel,
then "shift+enter", see 2207 issue,
the results appear in another window
but no possibility to save the results in spite of a correct presentation on the additional panel (482 lines X 52 rows),.
right click, "export results" not available,
====> how to export in csv (in the procedure or in.. select proc from dual)??   - thanks in advance -
![refcursor](https://user-images.githubusercontent.com/4738651/36093223-5455185a-0fea-11e8-9295-9ac410f88958.png)
![github_pv5b](https://user-images.githubusercontent.com/4738651/36097753-85199396-0ffc-11e8-81ae-0ed878e7c543.png)

**Comment by serge-rider** [comment]
Data export from REFCURSORs is not supported.
What you can do is to fetch all rows, then select them (<kbd>CTRL+A</kbd>) and copy to clipboard (<kbd>CTRL+C</kbd>. Then you can paste it into any text editor or in Excel (cells should be formatted properly)
