### ISSUE TITLE
Warn user when more than 10 SQLs will be executed in "separate result tabs"

### ISSUE THREAD

**Issue by shivan** [dbeaver/dbeaver#2963]
Feature request

Currently it is possible to open a big sql script with many sqls. Then if someone has the bad idea to execute them all in separate tabs (ctrl + alt + x), dbeaver will maybe get stuck.

Proposed solution: On start of ctrl+alt+x - if there are more than 10 SQLs which will be executed, show the user a warning message:

Do you really want to execute <XXXX> statements in separate tabs?
Yes  / No 

(default = no)

**Comment by serge-rider** [comment]
Good point

**Comment by shivan** [comment]
Hopefully my colleague won't try to execute ~2300 commands in new tabs again then ;-)

**Comment by serge-rider** [comment]
Yep :)
![image](https://user-images.githubusercontent.com/6398845/36114909-7997a382-1042-11e8-8fcc-f710edefff80.png)

**Comment by shivan** [comment]
Great!
I would suggest default focus to "cancel" button ?

**Comment by serge-rider** [comment]
Agreed. Although this is more general enhancement (for all confirmations of type "warning")
