### ISSUE TITLE
Disable Grid Column Icons

### ISSUE THREAD

**Issue by Clinton27** [dbeaver/dbeaver#2965]
Hi

A feature request please...
Would like the option to disable the datagrid header column icons (datatype, sort, question mark, etc.) 

![image](https://user-images.githubusercontent.com/18426463/36101765-f04e50be-1012-11e8-9baf-a7bdc58c9527.png)

I think it would improve readability, especially on large tables.

Thanks

**Comment by serge-rider** [comment]
Yes, this makes sense.

**Comment by Clinton27** [comment]
Thanks Serge, much appreciated!
