### ISSUE TITLE
[bug] Some one-letter column names are not visible in results

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#2967]
![default](https://user-images.githubusercontent.com/16996529/36128712-8a03c5a8-10af-11e8-9f65-ec435bf9825f.png)

**Comment by fer22f** [comment]
![image](https://user-images.githubusercontent.com/3057302/36385116-61e2a6be-1570-11e8-849f-4522b019fdff.png)
Had a different result. I guess there is a lot of factors that influence this bug.

**Comment by serge-rider** [comment]
Yep, I've reproduced that.
Thanks for report
