### ISSUE TITLE
error infomation is displayed two times in error dialog

### ISSUE THREAD

**Issue by highgoyangguoqing** [dbeaver/dbeaver#2968]
When the table 'test' is exist,I want to save the same name of table. An error  occurred. But the error is displayed two times.please check out.
![image](https://user-images.githubusercontent.com/34262632/36138130-21dee812-10d3-11e8-9856-a922cade5923.png)

**Comment by serge-rider** [comment]
This is how Eclipse error dialog works. 
I'm afraid I can't fix it.

**Comment by highgoyangguoqing** [comment]
Ok. Thanks.
