### ISSUE TITLE
Syntax coloring bug

### ISSUE THREAD

**Issue by AndreaOmodeo** [dbeaver/dbeaver#2969]
The "escaped quote" (backslask-quote) used to insert a single quote in a text string confuses the syntax-coloring logic.
Please see the attached PNG.

The statement is syntactically correct (at least for Impala): as you can see it produces results.
It's only the syntax coloring that is is very confusing.
![cattura](https://user-images.githubusercontent.com/7797685/36140776-c39afb2c-10a2-11e8-8683-3eb95423d0da.PNG)

**Comment by serge-rider** [comment]
What is your database?
Currently backslash escaping works only for MySQL and MariaDB.

**Comment by AndreaOmodeo** [comment]
Hy Serge.
I'm on Impala 2.x. 
I struggled a bit writing this statement, because Impala does not accept the other way of escaping quotes (quote-quote) and Dbeaver insisted in coloring my statement in this way.

My reference is
https://www.cloudera.com/documentation/cdh/5-0-x/Impala/Installing-and-Using-Impala/ciiu_literals.html
which says "Use the backslash to escape single or double quotation mark characters within a string literal"

**Comment by serge-rider** [comment]
Impala driver config was fixed. Also this can be configured in driver advanced properties->String escape character.
