### ISSUE TITLE
Question - MacOS jTDS MSSQL Driver w/SSL Failure

### ISSUE THREAD

**Issue by aLTeReGo-SWI** [dbeaver/dbeaver#2970]
I'm stuck between a rock and a hard place. It seems the jTDS supports Windows Integrated Authentication, but I can't for the life of me get SSL to work (which is also required). I can't even use the jTDS MSSQL Driver to work with SQL Authentication when SSL is required.

The Microsoft Driver supports SSL beautifully, but on a Mac it's not possible to use Windows Integrated Authentication with this driver.  

Since both SSL and Windows Authentication are required by the SQL server I'm needing to connect to and I only have a Mac, what is the recommended way to resolve my SSL issues with the jTDS driver?  

When SSL Is required DBeaver returns the following errors when SSL = require in the MSSQL jTDS driver. 
Network error IOException: Socket closed
  Network error IOException: Socket closed
    Socket closed
    Socket closed

There are no errors in the Event Log of the SQL server when SSL = require in the MSSQL jTDS driver, but if it's set to 'Off' then I get the following error (obviously) on the SQL server that encryption is required. 

Encryption is required to connect to this server but the client library does not support encryption; the connection has been closed. Please upgrade your client library. [CLIENT: 10.110.118.13]

**Comment by serge-rider** [comment]
I'm not sure that this is possible.
Looks like you need Microsoft driver. 
However it looks like you can use only SQL Server auth on Mac/Linux.
