### ISSUE TITLE
Error executing Stored Procedure

### ISSUE THREAD

**Issue by george175** [dbeaver/dbeaver#2971]
Hi,

I am using DB@ for Z/oz and when I call a stored procedure from DBeaver I get a strange error.

The call is the following:

CALL SHXP.CUSSP500(
	'GETAGREE',
	'',
	'0003167',
	'**',
	'**',
	'SSH38',
	'0001-01-01',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	''
);

This is the stored procedure DDL

CREATE PROCEDURE "SHXP"."CUSSP500" (IN_FUNCTION CHAR(8) CCSID EBCDIC FOR SBCS DATA, 
		IN_USERID CHAR(8) CCSID EBCDIC FOR SBCS DATA, 
		IN_CUST_NBR CHAR(7) CCSID EBCDIC FOR SBCS DATA, 
		IN_SELCO CHAR(2) CCSID EBCDIC FOR SBCS DATA, 
		IN_LOC CHAR(2) CCSID EBCDIC FOR SBCS DATA, 
		IN_STYLE CHAR(5) CCSID EBCDIC FOR SBCS DATA, 
		IN_CHG_DATE CHAR(10) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_CUST_NAME CHAR(30) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_ADDR1 CHAR(30) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_ADDR2 CHAR(30) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_CITY CHAR(20) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_FILL1 CHAR(1) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_STATE CHAR(2) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_FILL2 CHAR(1) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_ZIP CHAR(16) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_EFFDT CHAR(10) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_CARRIER CHAR(3) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_CARRIER_NAME CHAR(24) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_TERMS CHAR(2) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_TERMS_DESC CHAR(24) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_EXTRA_FRT CHAR(4) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_FRT_CD CHAR(2) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_GROUP CHAR(7) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_COMM1 CHAR(36) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_COMM2 CHAR(36) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_COMM3 CHAR(36) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_COMM4 CHAR(36) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUT_COMM_CUST CHAR(7) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUTPUT_CODE CHAR(5) CCSID EBCDIC FOR SBCS DATA, 
		OUT OUTPUT_DATA CHAR(100) CCSID EBCDIC FOR SBCS DATA)
	DYNAMIC RESULT SETS 2
	PARAMETER CCSID EBCDIC
	EXTERNAL NAME "CUSSP500"
	LANGUAGE COBOL
	MODIFIES SQL DATA
	PARAMETER STYLE GENERAL
	FENCED
	WLM ENVIRONMENT DBS1SPSM
	ASUTIME LIMIT 900000
	COLLID SHXPPROC
	RUN OPTIONS 'NOTEST(ALL,*,PROMPT,TCPIP&172.16.45.17%8001:)'
	STAY RESIDENT YES
	COMMIT ON RETURN NO
	PROGRAM TYPE MAIN
	SECURITY DB2
	PARAMETER CCSID EBCDIC;

All the parameters are CHAR, but the error I get is the following:

SQL Error [42601]: [jcc][t4][10427][12544][4.14.122] Error parsing INTEGER literal value starting at index 227.  Error Detail:Invalid character '
' found in INTEGER literal.  Full SQL statement text=CALL SHXP.CUSSP500(
	'GETAGREE',
	'',
	'0003167',
	'**',
	'**',
	'SSH38',
	'0001-01-01',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	''
)

Not sure what INTEGER is being parsed.

If I execute the same statement in different database tool, it works fine and returns the data.

One more note, is that if I right click on the SP in DBeaver and choose execute, it generates this SQL:

select SHXP.CUSSP500(
	:IN_FUNCTION,	-- put the IN_FUNCTION parameter value instead of 'IN_FUNCTION' (CHAR(8))
	:IN_USERID,	-- put the IN_USERID parameter value instead of 'IN_USERID' (CHAR(8))
	:IN_CUST_NBR,	-- put the IN_CUST_NBR parameter value instead of 'IN_CUST_NBR' (CHAR(7))
	:IN_SELCO,	-- put the IN_SELCO parameter value instead of 'IN_SELCO' (CHAR(2))
	:IN_LOC,	-- put the IN_LOC parameter value instead of 'IN_LOC' (CHAR(2))
	:IN_STYLE,	-- put the IN_STYLE parameter value instead of 'IN_STYLE' (CHAR(5))
	:IN_CHG_DATE 	-- put the IN_CHG_DATE parameter value instead of 'IN_CHG_DATE' (CHAR(10))
);

This won't work, because it does not have the OUTPUT variables in the call

**Comment by serge-rider** [comment]
Look like DB2 driver issue (like this: http://www-01.ibm.com/support/docview.wss?uid=swg1PI34907)
Try to upgrade driver version.
