### ISSUE TITLE
[bug] Field is marked as edited when I changed nothing

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#2972]
[Postgres]
When result set has JSON or array column and I open (F7) Value editor. Then I select some text in it but edit nothing. After this the field become marked as edited.

![default](https://user-images.githubusercontent.com/16996529/36182854-5406d788-1177-11e8-9496-68fb0ccca6fc.png)

**Comment by serge-rider** [comment]
Thanks for report
