### ISSUE TITLE
Non printable char in Eclipse plugin window title (Minor bug)

### ISSUE THREAD

**Issue by LeonidMew** [dbeaver/dbeaver#2976]
DBeaver add \n to Eclipse window title.

[![screenshot][1]][1]

  [1]: https://i.stack.imgur.com/YP0iZ.png

**Comment by serge-rider** [comment]
Dunno how to reproduce that. Most likely you redefined windows title in workspace preferences.

**Comment by LeonidMew** [comment]
I don't change any title in preferences.
I'm planning to install eclipse on newly installed ubuntu, will report if it reproduced.
