### ISSUE TITLE
Dbeaver cannot open on RHEL 7.4

### ISSUE THREAD

**Issue by marcus-mota** [dbeaver/dbeaver#2977]
Hi,
I'm facing issues with dbeaver while tries to open.
This is happening for a long time (5+ versions), but didn't have time to check it before.

The error points to a log on /$HOME$/.eclipse/org.jkiss.dbeaver.product_4.3.4_620785679_linux_gtk_x86_64/configuration/1518647328898.log

Attached the log.
[1518647328898.log](https://github.com/dbeaver/dbeaver/files/1725933/1518647328898.log)

Thanks in advance.

**Comment by ceyhunnabiyev** [comment]
Dbeaver supports Java 8  and Java 9 versions. You have Java 7.

**Comment by serge-rider** [comment]
Yep. Java 8 is the minimum requirement.
