### ISSUE TITLE
DBeaver not activate focus

### ISSUE THREAD

**Issue by Bsplesk** [dbeaver/dbeaver#2979]
> Info:
> DBeaver 4.3.4
> Arch Linux/Gnome 3.26.2
> java -version
> openjdk version "1.8.0_144"
> OpenJDK Runtime Environment (build 1.8.0_144-b01)
> OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

hotkey
"Maximize results panel : Shift+Ctrl+6" 
**Problem:**
not activate focus window when switching, the additional click on a window is required.

**Comment by serge-rider** [comment]
Good point.
