### ISSUE TITLE
Update/Install DBeaver Extensions does not work

### ISSUE THREAD

**Issue by mradeschnig** [dbeaver/dbeaver#29804]
### Description

There is an entry missing to update all DBeaver Extensions ( https://dbeaver.io/update/latest/).
For each individual DBeaver Extension the link does not work. Seems there is a unneeded slash at the end (latest seems to be a file).
e.g. "DBeaver Office integration - https://dbeaver.io/update/office/latest/"

### DBeaver Version

24.0.4

### Operating System

Windows 11 / Ubuntu 24.04 LTS

### Steps to reproduce

Open Help, Install New Software and select one of the predefined entried for DBeaver.
-> In the File List you see "Could not find .."

**Comment by passacaglia** [comment]
Same issue for me, after upgrading to Version 24.0.4.202405051837, on Windows 11, when I tried to reinstall the Office Support plugin. Is the Office Support plugin website (https://dbeaver.io/update/office/latest/) down?

**Comment by bnelissen-orisha** [comment]
Same issue. Can't install Git Support.
https://dbeaver.io/update/git/latest/ returns 404.

**Comment by mradeschnig** [comment]
I installed the updated extensions using the link https://dbeaver.io/update/latest/ which was not predefined anymore.

**Comment by serge-rider** [comment]
Extensions deployment has been fixed.
Please try again

**Comment by bnelissen-orisha** [comment]
@serge-rider works for me ! Thank you.

**Comment by uslss** [comment]
verified
