### ISSUE TITLE
Derby driver: 'Find Class' disabled

### ISSUE THREAD

**Issue by hublol** [dbeaver/dbeaver#2981]
Info:
DBeaver: multiple versions (4.3.4, but same with 3.6.1)
Windows 2012 R2

I am trying to configure the Derby driver (both Embedded and Server) without internet connection. So I try to manually add files to the list of Libraries. Unfortunately, the 'Find Class' button stays grayed out and there is no way to select the appropriate driver class.
Notes:
1. This happens only when editing the existing Derby drivers. If I create a new driver, then everything works as expected.
2. This happens only with the Derby drivers. When editing the DB2 driver for example, I have no problem to add libraries and select the driver class.
3. I don't have the problem on my Linux box. Sure, DBeaver version and Java are different, but I am following the same steps (I don't think that I am doing something wrong).
4. Simply adding the files and keeping the default class name doesn't work either. When trying to connect, DBeaver can't find the class.

The question is: what's likely to be the root cause of the problem, and how can I troubleshoot this?

[derby_config.txt](https://github.com/dbeaver/dbeaver/files/1727437/derby_config.txt)

**Comment by hublol** [comment]
I think that I found a workaround:
1. disable all the Maven repositories
2. remove the Maven reference in the list of libraries (note that it gets automatically added if the Maven repositories are not disabled).
3. add the required libraries as usual.

The problem still persists, ie. 'Find Class' is still disabled, but at least DBeaver somehow finds the class when trying to connect to the database. With Maven enabled this wasn't working at all.

**Comment by serge-rider** [comment]
Indeed this is a bug in DBeaver. It is not Derby specific but it is related to Maven artifacts delete.
Thanks for report
