### ISSUE TITLE
Permission Missing in MySQL (RDS Aurora)

### ISSUE THREAD

**Issue by benyanke** [dbeaver/dbeaver#2983]
When setting up my magento app server, permission for 'EVENT' is required, which is not provided. I'm not seeing it on the list.

![image](https://user-images.githubusercontent.com/4274911/36262374-d81637b6-122c-11e8-8293-8a2f9d6b3457.png)

Is this something that can/should be added?

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/38782163-931ad69a-40f7-11e8-9c4d-81d0e83b3637.png)

**Comment by benyanke** [comment]
Most excellent!
