### ISSUE TITLE
DBeaver portuguese translation 

### ISSUE THREAD

**Issue by lcocbr** [dbeaver/dbeaver#2984]
Hi,

As a brazilian portuguese DBeaver user, it would be very nice to see DBeaver translated into my language. Do you have any plans on this? If not, is there a way for me to contribute in such a task? For example, I could start translating wiki docs and, then, the program itself. Just need to know how to start. 

Thanks in Advance.

Leo

**Comment by serge-rider** [comment]
Hello,

We'd be happy to have Portuguese translation!
Please write me on serge@jkiss.org.

Thanks

**Comment by gugaferoz** [comment]
Good Morning. Any progress on this issue?

**Comment by jarciano** [comment]
Hello,

Every day more people from Brazil are using the tool that by the way I consider the best database manager today, it would be very interesting to have it in Brazilian Portuguese.

As proposed by @lcocbr, I will also be happy to collaborate with the community to have more of this software added value.

**Comment by wellesximenes** [comment]
Pessoal acredito que fiz a tradução total do dbeaver mas gostaria se possivel alguem revisasse segue o tutorial e o meu git .
Wiki: https://github.com/dbeaver/dbeaver/wiki/Localization
git: https://github.com/wellesximenes/dbeaver
