### ISSUE TITLE
Postgres Permission 4.3.4

### ISSUE THREAD

**Issue by jerherder** [dbeaver/dbeaver#2986]
Hello

with the new version 4.3.4, For postgres, we don't see the permission select in the properties of the sequence. we can just put the permission usage. because in the version 4.3.3, we saw the permission select.

the same thing on the list of permissions for the user or role, we don't see the exact permissions. see attachment for exemple.

Difference_V4_3_3_vs_V4_3_4.docx

When i click on grant all, i don't know what are the permissions.

**Comment by jerherder** [comment]
And the sequences are not displayed in the permissions by user or role, only the tables, views and materialized views.

kind regards

**Comment by serge-rider** [comment]
in 4.3.4 we show only USAGE privilege for sequences. 
It is the only sequence permission available in PostgreSQL 9.x+.

Missing sequences in object list is a bug, thanks for report.

**Comment by jerherder** [comment]
Hello

thanks for your help.

if it's possible to add the view for see all the permissions for the sequences like in the version 4.3.3 it will be perfect. in fact, the same display that for the tables.

or display it in the permissions by role like say by you.

because in other postgres tools, we can see the exact privileges for the sequences.

a great thanks to you for this tool.

Best regards

**Comment by jerherder** [comment]
this query display the sequence permissions: 
select  objtype,
        schemaname,
        objname,
        owner,
        objuser,
        privs,
        string_agg(
            (case   privs_individual
                    when 'arwdDxt' then 'All'
                    when '*' then 'Grant'
                    when 'r' then 'SELECT'
                    when 'w' then 'UPDATE'
                    when 'a' then 'INSERT'
                    when 'd' then 'DELETE'
                    when 'D' then 'TRUNCATE'
                    when 'x' then 'REFERENCES'
                    when 't' then 'TRIGGER'
                    when 'X' then 'EXECUTE'
                    when 'U' then 'USAGE'
                    when 'C' then 'CREATE'
                    when 'c' then 'CONNECT'
                    when 'T' then 'TEMPORARY'
            else 'Unknown: '||privs end
            ), ', ' ORDER BY privs_individual) as privileges_pretty
from    (select objtype,
                schemaname,
                objname,
                owner,
                privileges,
                (case when coalesce(objuser,'') is not distinct from
'' then 'public' else objuser end)
                    || (case when pr2.rolsuper then '*' else '' end)
                as objuser,
                privs,
                (case   when privs in ('*','arwdDxt') then privs
                        else regexp_split_to_table(privs,E'\\s*')
                end) as privs_individual
        from    (select distinct
                        objtype,
                        schemaname,
                        objname,
                        coalesce(owner,'') || (case when pr.rolsuper
then '*' else '' end) as owner,
                        regexp_replace(privileges,E'\/.*','') as privileges,
(regexp_split_to_array(regexp_replace(privileges,E'\/.*',''),'='))[1]
as objuser,
(regexp_split_to_array(regexp_replace(privileges,E'\/.*',''),'='))[2]
as privs
                from    (SELECT n.nspname as schemaname,
                                c.relname as objname,
                                CASE c.relkind WHEN 'r' THEN 'table'
WHEN 'v' THEN 'view' WHEN 'S' THEN 'sequence' END as objtype,
regexp_split_to_table(array_to_string(c.relacl,','),',') as
privileges,
                                pg_catalog.pg_get_userbyid(c.relowner) as Owner
                        FROM pg_catalog.pg_class c
                        LEFT JOIN pg_catalog.pg_namespace n ON n.oid =
c.relnamespace
                        WHERE c.relkind IN ('r', 'v', 'S', 'f')
                        AND n.nspname !~ '(pg_catalog|information_schema)'
                        --AND pg_catalog.pg_table_is_visible(c.oid) /*Uncomment to show only objects */
                        ) as y                                      /*visible in search path */
                left join pg_roles pr on (pr.rolname = y.owner)
                ) as p2
        left join pg_roles pr2 on (pr2.rolname = p2.objuser)
        --where coalesce(p2.objuser,'') is distinct from '' /*Uncomment to hide "public" role */
        ) as p3
group by objtype, schemaname,objname, owner, objuser, privs
order by objtype,schemaname,objname,objuser,privileges_pretty;

**Comment by serge-rider** [comment]
Check fix in 4.3.5

**Comment by jerherder** [comment]
ok thanks you
