### ISSUE TITLE
Query with WITH statement throws error in DB2

### ISSUE THREAD

**Issue by jdussouillez** [dbeaver/dbeaver#2987]
This is a bug report. I created a DB2 connection and when running a select query using WITH it fails.

Here's the query which doesn't work :
```
WITH MYTABLE AS (
	SELECT *
	FROM SYSIBM.SYSDUMMY1
)
SELECT T.*
FROM MYTABLE T
```
**Error** : 
_Query execution failed.
Reason : SQL Error [42704]: [SQL0204] MYTABLE type *FILE not found_

The same query without the WITH statement works fine : 
```
SELECT T.*
FROM (
	SELECT *
	FROM SYSIBM.SYSDUMMY1
) T
```
The first query is valid because it works when I run it in the "Run SQL Script" tool of IBM i Access Client Solutions 1.1.6.1.

DBeaver v4.3.4
Driver Name : DB2 iSeries/AS 400
Class Name : com.ibm.as400.access.AS400JDBCDriver
JDBC URL : jdbc:as400://myibmi;translate binary=true
The library used is the [JT400 9.4](https://mvnrepository.com/artifact/net.sf.jt400/jt400/9.4)

**Comment by serge-rider** [comment]
Can't say what is this. Looks like local env specific issue.
Are you sure that exactly the same query (copy-pasted) works find in Access Client?

Note: you can monitor actual SQL executed (passed to server) by DBeaver in Query Manager view.

**Comment by jdussouillez** [comment]
Yes the same query works fine in Access Client. I uninstall DBeaver and then installed the v4.3.5 and it works now. I don't know why but it works.
Thank you anyway, this app is great !

**Comment by bahchis** [comment]
A bit old, but I had the same problem with AWS Athena and it seems to be related to DBeaver (Version 6.3.0.201912042122) and a line break.

This works:
```
WITH MYTABLE AS (
	SELECT *
	FROM SYSIBM.SYSDUMMY1
)
SELECT T.*
FROM MYTABLE T
```

This does NOT work (with a line break before the main select):
```
WITH MYTABLE AS (
	SELECT *
	FROM SYSIBM.SYSDUMMY1
)

SELECT T.*
FROM MYTABLE T
```

Small stuff but it would be a deal-breaker if it wouldn't work at all and it got me scratching my head for a few minutes to find the reason (line break is not the first assumption).

Thank you!

**Comment by lynchkl** [comment]
Line break is still an issue in DBeaver 23.0.1 - so glad I found this comment!

**Comment by saminter22** [comment]
Спасибо - ваш комментарий про пустую строку сделал этот вечер. 1,5 часа искал причину ошибки и думал, что медленно схожу с ума, но оказалось все просто. Очень рад, что нашел ответ в вашем комментарии!
