### ISSUE TITLE
Find/Replace Selected Lines broken in version 24.04

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#29886]
### Description

In the lasted update of DBeaver the behavior of the Selected lines Scope radio button toggle chaged/is broken.
Previously when you selected a block of text then opened the Find/Replace dialog either one of two things happened:

1. the Scope defaulted to **Selected lines**
2. the Scope defaulted to **All** (which was anoying)

if you were lucky enough to be in situation 1, you just pressed whatever operation you wanted and the effects would be limited to the selected text.

if you were in situation 2, you would go back into the editor, reselect the block of text, which would toggle the Scope to **Selected lines** (sometimes, sometimes you would have to manually set it to **Selected lines**) and you could proceed as above.

After upgrading to the recent version, when you select a block of text and open the Find/Replace dialog the scope is set to **Selected lines**, if you then do any operation, it's applied to _All lines_ in the editor.

The only way now to have the Find/Replace operations opperate on a selected text is to switch the scope from Selected lines to All and then back to Selected lines.

I hope that someone can fix this _dangerous_ soon.

### DBeaver Version

Community Edition 24.0.4

### Operating System

Windows 10

### Steps to reproduce

1. Have a bunch of text in an SQL Editor window
2. Select several lines
3. Cntrl-F to open the Find/Replace dialog.
4. Note that the Scope is set to **Selected lines**
5. Perform an operation (ex: replace all 'e' with '@') with Replace All
6. Be dismayed as every matching text in the entire SQL Editor has been effected.

**Comment by coleman-rik** [comment]
note:
why does DBeaver have **two different** selected modes?

apparently there's _selected_ when the  user selects things, and for things are select as the result of a **Find** operation [deep blue], but a different _selected_ [slightly lighter blue] when thte Find/Replace dialog is going to **actually** limit it's operations to the selected area. 

the second selected area doesn't honor the user selection, in that toggling the Scop radio buttons can often clear the user selection, and it can be confusing as to what's operations of the Find/Replace dialog are **actually** going to effect.

**Comment by E1izabeth** [comment]
I can stable reproduce it only if DBeaver window loose focus (for example, if I switched to some other app or pressed hotkey for screen recording).

**Comment by E1izabeth** [comment]
This dialog comes to DBeaver from Eclipse platform. So, actually we inherit this bug from them https://github.com/eclipse-platform/eclipse.platform.ui/issues/1819 https://github.com/eclipse-platform/eclipse.platform.ui/issues/1235 
It came in this version, because we just updated Eclipse version we use.

**Comment by coleman-rik** [comment]
> I can stable reproduce it only if DBeaver window loose focus (for example, if I switched to some other app or pressed hotkey for screen recording).

@E1izabeth I am sorry to confirm that I can reliably reproduce without ever leaving DBeaver or ever losing focus.

if I make DBeaver full screen, and never leave the application. Then:

1. open a new SQL Editor window
2. write/paste text into the editor
3. select a subset of lines (notice that they are the dark blue, user selection)
4. press Ctrl+F which will cause the Find/Replace dialog to open with **Selected line** Scope selected
5. notice that the selection is still _user selected_ and **not** the lighter _find/replace selected_
6. type a common character in Find and a symbol in Replace so that the results will be obvious
7. press Replace All
8. watch in dismay as that replacement is done in the entire document.

as you can see in the steps outlined above, DBeaver **never** lost focus.

if at step # 5 you flip the Scope dialog  from the defaulted **Selected lines** to **All** and then back to **Selected lines** (and you don't lose your selection, which happens sometimes) you will notice that the selection has changed from the _user selection_ (dark blue) to the _Find/Replace selection_  (light blue).  Replace All will now function as expected.

I hope that helps.

**Comment by E1izabeth** [comment]
@coleman-rik could you check if it's still reproducible for you on the latest DBeaver version? We expect that this bug is fixed and I can't reproduce it anymore.
