### ISSUE TITLE
Travamento ao executar bloco de scripts

### ISSUE THREAD

**Issue by syspone** [dbeaver/dbeaver#29889]
### Description

Pessoal estou com problemas em travamentos ao executar varios scripts, na versao 24.0.04

### DBeaver Version

24.0.04

### Operating System

Windows 11

### Database and driver

jdbc:oracle:thin:@//172.16.23.20:1521/wint

### Steps to reproduce

Eu estou realizando o script e ao mesmo tempo o sistema trava e nao consegue mais executar.

**Comment by E1izabeth** [comment]
Please translate your issue into English and provide clear steps to reproduce it.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
