### ISSUE TITLE
DBeaver, snowflake, VPN issue

### ISSUE THREAD

**Issue by mrmusial** [dbeaver/dbeaver#29904]
### Description

Hi.

I'm trying to access Snowflake DB (MacOS 14.3) via VPN - but it looks like DBeaver doesn't see this connection for some reason...

I've got some IPs whitelisted on my Snowflake db (those that are used on VPN gateways) and I'm using SSO (externalbrowser) authentication.

When using VPN, I'm getting IP let's say it is 10.11.22.33, when trying to connect using snowsql tool it is connecting correctly, then when I execute select current_ip_address(); it shows 10.11.22.33.

On DBeaver, I'm getting 
Incoming request with IP/Token 1.2.3.4 is not allowed to access Snowflake. Contact your account administrator. For more information about this error, go to https://community.snowflake.com/s/ip-xxxxxxxxxxxx-is-not-allowed-to-access.
where 1.2.3.4 is my global IP (not tunneled), while VPN is still connected...

Strange thing is that it was working fine till last week. One day morning I was not able to connect, have no idea what had happened.

### DBeaver Version

Comunity Edition Version 24.0.4.202405051837

### Operating System

macOS 14.3

**Comment by ShadelessFox** [comment]
Hello @mrmusial,

There seems to be an issue with your VPN client - it doesn't send all traffic through itself. Maybe the client got updated?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
