### ISSUE TITLE
Advance Copy Options -> modifications

### ISSUE THREAD

**Issue by jad986** [dbeaver/dbeaver#2990]
It would be nice if we have the possibility of saving selected items in advanced copy options and use them next times from the drop-down list (something similar to Value Format).

In addition I think in advanced copy options should also be an option regarding the choice of decimal separator.

**Comment by serge-rider** [comment]
I'm not quite sure I got it. What do you mean under "selected items"?
DBeaver saves all options in advanced copy dialog (as far as I know). If some of them not working - please tell which exactly.
