### ISSUE TITLE
Teradata connection requires Database/Schema override

### ISSUE THREAD

**Issue by Anteus** [dbeaver/dbeaver#29934]
**Is your feature request related to a problem? Please describe.**
When creating a connection to a Teradata database the field Database/schema (DATABASE=) is required by DBeaver but not by Teradata as it is only used to override the default database defined for the database user. It causes some confusion for newcomers.
> Specifies a default database for use after logon, to override the default database defined for the database user.
https://teradata-docs.s3.amazonaws.com/doc/connectivity/jdbc/reference/current/jdbcug_chapter_2.html#URL_DATABASE

**Describe the solution you'd like**
The field Database/schema to be optional.
I guess changing it here: https://github.com/dbeaver/dbeaver/blob/28ecc6e2f484ee8c8038c0fd736d2c80d98b92cb/plugins/org.jkiss.dbeaver.ext.generic/plugin.xml#L584
Perhaps using defaultDatabase somehow?
**Describe alternatives you've considered**
Setting it to the username of the user connecting?
**Additional context**

**Comment by E1izabeth** [comment]
Thank you for report

**Comment by serge-rider** [comment]
We will use user name as default database name
