### ISSUE TITLE
Caret not visible while scrolling/moving through text

### ISSUE THREAD

**Issue by matt-wirtz** [dbeaver/dbeaver#2995]
Hi,

I have a question regarding the caret in the SQL editor.

When I navigate the caret through the SQL text with left, right, up and down keys, the caret is not visible while it's moved. The caret disappears as long as one of the arrow keys is pressed and hold down.

Once the arrow key is released the caret appears again but not until a short second has passed.

This makes navigating through the text difficult. One has to guess where the caret might be right know - kind of a blind flight. Usually the caret is visible while moving it through the text.

Can this behavior be changed by parameter?

I'm using dbeaver 4.3.2 on a SUSE Leap42.3 with KDE.

Thx.

**Comment by serge-rider** [comment]
Seems to be this bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=517487
It is already fixed in the platform. So this will be auto-fixed in DBeaver in one of the next releases (I can't say when this fix became publicly available in Eclipse P2 repos - perhaps DBeaver already have it, you can test it in the most recent version).

In any case it is Eclipse bug not DBeaver's.
Thanks for report anyway.

**Comment by matt-wirtz** [comment]
Hi,

the referenced bug by serge-rider sounds [https://bugs.eclipse.org/bugs/show_bug.cgi?id=517487](https://bugs.eclipse.org/bugs/show_bug.cgi?id=517487) to be somewhat similar. But so far even the newest dbeaver release 4.3.5 has the bug. I just tested it.

In addition the referenced bug was already fixed in eclipse in August 2017 making me wonder if these issues are really related.

So I would rather keep this issue open until it is definitely fixed in dbeaver. So other users can more easily find this bug report and are not tempted to create new issues targeting the same problem.

CU.

**Comment by serge-rider** [comment]
This seems to be an Eclipse issue not DBeaver's.
We could keep it open but I can't fix it anyway. 
So let it be here just in case. Maybe some additional info will be posted.
