### ISSUE TITLE
Truncated text in Preferences - Cosmetic Bug

### ISSUE THREAD

**Issue by sae-gfc** [dbeaver/dbeaver#2997]
Hello,

Some text is trunked, I looked all items I only found 2 problems, see captured pictures.
The windows was opened large enough.
V4.3.5 Ubuntu 17.10 - 64bits  - Wayland

![2018-02-19 12-54-12](https://user-images.githubusercontent.com/33481143/36369779-f0ad0aec-1575-11e8-98da-e2bbb3c608d3.png)
![2018-02-19 12-54-35](https://user-images.githubusercontent.com/33481143/36369780-f3947ab0-1575-11e8-9784-7af085695600.png)

**Comment by serge-rider** [comment]
It is an error in pages components layout.
Thanks for report.
