### ISSUE TITLE
DBeaver Freezes and Has High CPU Usage with Large Scripts

### ISSUE THREAD

**Issue by CalDude10** [dbeaver/dbeaver#29996]
### Description

DBeaver 24.0.3 and 24.0.4 freeze when performing certain actions on large script files (5,000 lines for example).  This behavior began with 24.0.3 and I have verified that 24.0.2 behaves normally with the same large files.  At first, I thought the app had completely hung, but I eventually realized that it will return to normal if I let it sit for 5 - 15 minutes depending on the script and system specs.  During this time, the app is constantly using 10% - 25% CPU depending on system specs.  I tried a clean install of 24.0.4 on a system that never had DBeaver and I get the same bug.  If I then uninstall it and install 24.0.2, everything is fine.  Some of the actions that cause the freeze are:

1. Open or save the file
2. Change the active datasource
3. Change the active catalog/schema

As mentioned above, the app eventually returns to normal after a considerable wait.  When executing the script, everything runs normally.  In previous versions of DBeaver I have worked with scripts up to 50,000 lines with no issues, but now it trips up on even a few thousand.  Below is an example of the types of statements in these scripts.  So far I have had the problem with INSERT or UPDATE statements, but haven't tried any deletes lately.

Example script lines:
UPDATE PROCS SET IS_ACTIVE = '0' WHERE PROC_NAME = '17-20AR-29' AND REVISION_LEVEL = '';
UPDATE PROCS SET IS_ACTIVE = '0' WHERE PROC_NAME = '33K1-4-716-1' AND REVISION_LEVEL = '';
UPDATE PROCS SET IS_ACTIVE = '0' WHERE PROC_NAME = '33K2-4-46-1' AND REVISION_LEVEL = '';
UPDATE PROCS SET IS_ACTIVE = '0' WHERE PROC_NAME = '33K3-4-2925-1' AND REVISION_LEVEL = '';
UPDATE PROCS SET IS_ACTIVE = '0' WHERE PROC_NAME = '33K3-4-3410-1' AND REVISION_LEVEL = '';
UPDATE PROCS SET IS_ACTIVE = '0' WHERE PROC_NAME = '33K3-4-3554-1' AND REVISION_LEVEL = '';

### DBeaver Version

24.0.3 Community

### Operating System

Windows 10 Pro

### Database and driver

Database:  Microsoft SQL Server 2014
Driver Name:  MS SQL Server / SQL Server

**Comment by E1izabeth** [comment]
Could you try switching this setting to `Always`?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/7c671ff3-a181-4140-9b8e-813d10501c4e)

Does it help?

**Comment by CalDude10** [comment]
Yes, setting that to Always fixed the issue.  Looks like I gave Smart too much to think about!

**Comment by E1izabeth** [comment]
Thank you. I think we should disable this heuristics for big scripts.

**Comment by E1izabeth** [comment]
We turned off `Smart` mode for `Blank line is statement delimiter` setting by default. However, we still need to fix the issue
