### ISSUE TITLE
Create connection from command line "-con" parameter generate Meta Model error

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2999]
DBeaver - **Version 4.3.5 CE, 4.3.4 CE, 4.3.3.1 CE**
DBeaver JDBC driver: **Microsoft Driver** or **jTDS driver**
Operating System: **Windows 7** / **Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

A change in how to a connection is created when connection is created using command line parameter "**-con**" seems to have been introduced in DBeaver version 4.3.3 CE (worked with version 4.3.2 CE).

If I execute the command line (using Windows):

`
C:\...> dbeaver.exe -con "name=TEST|driver=Microsoft Driver|host=localhost|port=1443"
`

The _DBeaver_ start up and show the error message:

> Can't instantiate meta model
> org.jkiss.dbeaver.ext.mssql.model.SQLServerMetaModel.<init>()

This worked as expected when using _DBeaver_ version 4.3.1 CE.

**Comment by serge-rider** [comment]
Can't reproduce. I can open connection with -con parameter without any issues.
Please post error/debug logs (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by pdanie** [comment]
Here is my ${HOME}\.dbeaver4\.metadata\DBeaver-debug.log file (from Windows)

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/1736661/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Do you use custom (manually created) driver?
In DBeaver 4.3.4+ we have switched to SQL Server data source provider.

This bug happens only with Generic driver. 
Thanks for report.

**Comment by pdanie** [comment]
I do not quite understand what a custom (manually created) driver is. I use the **MS SQL Server / Microsoft Driver" that is supplied by _DBeaver_ and downloaded within _DBeaver_.

Should I used another driver, downloaded a driver from other source, or should I have specified the command line parameter differently?

On that the bug only happens with Generic driver in _DBeaver_ 4.3.4+ seems odd, since the fault already existed in _DBeaver_ version 4.3.3.1.

**Comment by serge-rider** [comment]
Well, I found yet another bug. Sometimes DBeaver detects driver incorrectly when you specify driver name in -con command.
Generally it is much better to specify driver ID. In your case it will be `mssql_jdbc_jtds`.
But this ID is not visible in GUI. So I'll add extra field in driver editor dialog:
![image](https://user-images.githubusercontent.com/6398845/36391993-259f1cec-15ba-11e8-81c0-9d70f1dcf5ef.png)

**Comment by serge-rider** [comment]
Answering your questions:
- No, you don't need to create/change any driver. Just use driver name `mssql_jdbc_jtds`. In DBeaver 5.0 you can use driver name (`jTDS driver`) as well.
- Yes, this is quite old bug.
