### ISSUE TITLE
Connection to created from command-line can not be edited if no database is specified

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#3001]
DBeaver - **Version 4.3.5 CE**
DBeaver JDBC driver: **PostgreSQL**, **Microsoft Driver** or **Microsoft jTDS driver**
Operating System: **Windows 7** / **Windows 8.1**
Database Server: **PostgreSQL 9.5.2**

Connection to _Microsoft SQL Server_ or _PostgreSQL_ created from command-line can not be edited if no database is specified.

The command line below creates a connection **ok**, but if I right click on the "TEST" connection in the **Database Navigator** and choose **Edit Connection** nothing happens. The command below is for _PostgreSQL_ but the same misbehaviour exist for _Microsoft SQL Server_.

`
C:\> dbeaver.exe -con "name=TEST|driver=PostgreSQL|host=localhost|port=5432|user=postgres|password=<my pwd>"
`

The command line below (where I have specified a databasename) creates a connection **ok**, and if I right click on the "TEST" connection in the **Database Navigator** and choose **Edit Connection** the **Connection settings** dialog pops up **ok**.

`
C:\> dbeaver.exe -con "name=TEST|driver=PostgreSQL|host=localhost|port=5432|user=postgres|password=<my pwd>|database=dvdrental"
`

**Comment by serge-rider** [comment]
Thanks for report (and for other you bug reports, they are awesome)!

**Comment by dsu-inf** [comment]
I have the same problem when I create an Oracle connection using DBeaver 5.0.2 from command line.
