### ISSUE TITLE
Join autocompletion doesn't concatenate the string correctly with composite keys

### ISSUE THREAD

**Issue by fer22f** [dbeaver/dbeaver#3004]
Hey, I loved the new support for join autocompletion in the last release! One thing that brought my attention however is how this didn't work correctly:

```sql
SELECT * FROM movement
-- correct
INNER JOIN cashier ON movement.cashier_id = movement.id
-- correct, but it doesn't join the string with AND
INNER JOIN movement_payments
ON movement_payments.movement_id = movement.idmovement_payments.cashier_id = movement.cashier_id
```

The composite keys are being concatenated without any joining operator whatsoever.

**Comment by serge-rider** [comment]
Yep. Thanks for report!
