### ISSUE TITLE
Windows Defender find Trojan (false positive)

### ISSUE THREAD

**Issue by ffblanch** [dbeaver/dbeaver#3005]
Trojan:Win32/Sprisky.U!cl 
in Windows 64 bit (installer + JRE) 4.3.5

**Comment by infectormp** [comment]
False positive. Feel free to scan it on virustotal.com

**Comment by ffblanch** [comment]
can i download oldest version ?

**Comment by tati-kru** [comment]
@ffblanch of course, you can find all DBeaver versions in the archive: https://dbeaver.jkiss.org/files/.
We will check it once again and fix near future. Thank you for your issue.

**Comment by serge-rider** [comment]
Can't reproduce this in any available online services (including MS Windows Defender).
Closing as a glitch.

(I assume that you downloaded DBeaver installer from the official web site)

**Comment by ffblanch** [comment]
I tried this morning and everything works !
