### ISSUE TITLE
Displaying numbers with decimal - make configrable

### ISSUE THREAD

**Issue by rythym05** [dbeaver/dbeaver#3006]
After updating to 4.3.5 today, I see number fields displaying with decimal. Is there a way to turn this off ?

 I am using Oracle.

![image](https://user-images.githubusercontent.com/29409893/36393930-a1bd4dde-1566-11e8-8f4f-2a7ca6a5c96f.png)

**Comment by serge-rider** [comment]
Agreed, some people don't need this feature.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/36395386-fd95301e-15c9-11e8-8441-04a46175a1b6.png)
