### ISSUE TITLE
[CUBRID] Provide more information on Query Plan TableView

### ISSUE THREAD

**Issue by rathana-pvs** [dbeaver/dbeaver#30087]
**Description:**
* provide additional information (yellow colored columns)
1. index: index name if index scan is used
2. terms: predicate
3. total (r/p): Rows and Pages to be fetched 
4. extra: extra information

![MicrosoftTeams-image (3)](https://github.com/dbeaver/dbeaver/assets/108510204/b48078bb-3a5b-49ae-8a1a-038aeca77c25)

**Comment by E1izabeth** [comment]
Thank you for request.
