### ISSUE TITLE
Please add Comment Statement when Create DDL Statement of a View in Oracle

### ISSUE THREAD

**Issue by progsurfer** [dbeaver/dbeaver#3008]
Hi, thanks a lof for great Software,

can you please extend the funktion of DDL for View in Oracle.

When I create the DDL for table, the DDL creates the comment statement but not for the view.

It would be very useful to have  same function for DDL generator for a view Statement as for tabels.

Thank you and best regards 

Denis

**Comment by serge-rider** [comment]
Good point
