### ISSUE TITLE
If I use Oracle 23c driver F4 won't work (it works with other drivers)

### ISSUE THREAD

**Issue by Yigitttttttt** [dbeaver/dbeaver#30090]
### Description

If I use Oracle 23c driver F4 won't work (it works with other drivers)

### DBeaver Version

24.0.3

### Operating System

windows 10

**Comment by E1izabeth** [comment]
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by Yigitttttttt** [comment]
Even if it is a log file, I am not asked to share externally, sorry.

**Comment by E1izabeth** [comment]
Does it work if you open `Connection settings` from the context menu?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/f2c6ac05-8be2-4a26-838d-fab9b00470a7)

**Comment by E1izabeth** [comment]
Have you selected connection in the navigator tree before trying to press F4?

**Comment by Yigitttttttt** [comment]
I did the same as oracle 12 connection ok but it doesnt work on oracle 23c.
Just not working.

10 May 2024 Cum 10:01 tarihinde Elizabeth ***@***.***> şunu
yazdı:

**Comment by ShadelessFox** [comment]
Sorry, but we can't do anything without the logs. We need them to understand the culprit of your issue.

**Comment by Yigitttttttt** [comment]
No problem, I understand.

10 May 2024 Cum 17:05 tarihinde ShadelessFox ***@***.***>
şunu yazdı:

**Comment by ShadelessFox** [comment]
If you're going to provide log files, please do so on GitHub rather than add attachments to your mail (it doesn't work).

**Comment by E1izabeth** [comment]
If you worry about privacy, you can send it to email

**Comment by Yigitttttttt** [comment]
Sorry i cant. So we can close i cant send. Maybe someone could have same
issue thanks
