### ISSUE TITLE
Can't see Procedures and Views Oracle 11g

### ISSUE THREAD

**Issue by CrPbI3yH** [dbeaver/dbeaver#3009]
I'm using Dbeaver 4.3.5 and trying to connect Oracle 11.2.0.3.0 within ojdbc8.jar (JDBC ver 12.2.0.1.0) and don't see any schema procedures, views, functions e.t.c..
Same result for connection with ojdbc6.jar (jdbc ver 11.1.0.7.0)
I have all DB privileges that I needed  (checked with sqldeveloper)

**Comment by serge-rider** [comment]
Could you check error/debug logs for any related errors? https://github.com/dbeaver/dbeaver/wiki/Log-files
Also you could try Oracle 12 driver (sometimes it works better for Oracle 11)

**Comment by CrPbI3yH** [comment]
@serge-rider , unfortunately, I can't upload files through browser due to internal policy. Can I send it to  
you by mail (serge@jkiss.org)?

**Comment by serge-rider** [comment]
@CrPbI3yH sure, please send them on serge@jkiss.org or support@jkiss.org

**Comment by serge-rider** [comment]
Any updates?

**Comment by CrPbI3yH** [comment]
Sorry, but we have decided to pick another tool

5 июл. 2018 г. 12:50 ПП пользователь "Serge Rider" <notifications@github.com>
написал:

Any updates?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dbeaver/dbeaver/issues/3009#issuecomment-402668962>,
or mute
the thread
