### ISSUE TITLE
Dbeaver began to make a slow opening on Citrix machines

### ISSUE THREAD

**Issue by Yigitttttttt** [dbeaver/dbeaver#30091]
### Description

Dbeaver began to make a slow opening on Citrix machines

### DBeaver Version

24.0.3

### Operating System

windows 10

**Comment by E1izabeth** [comment]
Please describe your issue in more details? How slow is it? Do you have some editor open on start?

**Comment by Yigitttttttt** [comment]
The opening logo hangs on the screen too long compared to the 23 version

10 May 2024 Cum 09:57 tarihinde Elizabeth ***@***.***> şunu
yazdı:

**Comment by ShadelessFox** [comment]
Unfortunately, we don't have Citrix machines to reproduce this issue. Can you please record a thread dump to see what's happening behind the scenes? You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump.

Log files can be helpful as well: https://github.com/dbeaver/dbeaver/wiki/Log-files#log-files

By the way, are you a paid customer? The issue might be related to DBeaver having a hard time accessing our license server to validate your license.

**Comment by Yigitttttttt** [comment]
I will wait new version of Dbeaver and will try thanks

10 May 2024 Cum 17:44 tarihinde ShadelessFox ***@***.***>
şunu yazdı:
