### ISSUE TITLE
Command line in SQL returns SQL error: 00917 PRS ISC Invalid SQL Statement

### ISSUE THREAD

**Issue by nightbeaver** [dbeaver/dbeaver#3011]
**Works:** 
> SELECT DISTINCT BTNr FROM ATSUBT

**Doesn't work:**
> -- Test
> SELECT DISTINCT BTNr FROM ATSUBT  

**Doesn't work:**
> SELECT DISTINCT BTNr FROM ATSUBT -- Test 

**Doesn't work:**
> SELECT DISTINCT BTNr FROM ATSUBT
> -- Test 

_see_ attached error message

![sql_error_00917](https://user-images.githubusercontent.com/36659527/36415424-241845da-1626-11e8-9ca9-a871da6fd49d.png)

**Please advice**

- currently I am using DBeaver Version 4.3.4 (released 04.02.2018)
- did not work on previous versions either // with me and several other colleagues 
- all desperately looking for a solution as we need to command complex SQL statements
- all but one colleague (who promoted DBeaver) where commads work fine

**did not find solution under Window -> Preferences**

**Comment by serge-rider** [comment]
What is your database server/driver?

**Comment by serge-rider** [comment]
Well, original error doesn't looks like Oracle error. And queries works fine in Oracle.
I assume it was some database which doesn't like comments in queries.
