### ISSUE TITLE
Cannot perform operation Create New SQL Editor due to folder scripts already exists

### ISSUE THREAD

**Issue by badger1961** [dbeaver/dbeaver#3012]
Question.

The operation Create New SQL Editor completes with error  :
A resource exists with a different case: '/dev_6.100.00_FXPST_21626/scripts'.

In my projects folder scripts exists and contains batch scripts that are used in project. Seems to me this operation (Create New SQL Editor)  tries to create one more folder with name Scripts and cannot to do this. 
My questions is : Can user change the default folder where SQL scripts are saved

Thanks
Alex

**Comment by serge-rider** [comment]
Open project settings:
![image](https://user-images.githubusercontent.com/6398845/36443694-89c9581a-168a-11e8-8d4a-a41dc73c761b.png)
In DBeaver settings click on Folder column of SQL scripts row.
![image](https://user-images.githubusercontent.com/6398845/36443724-9b7af1ae-168a-11e8-92a4-d3854c7d4c9f.png)
Set new folder within workspace.

It makes sense to restart DBeaver after that

**Comment by serge-rider** [comment]
@lockmotiv DBeaver settings appears there only if the project has DBeaver nature. You can add it manually (in Project Natures tab) or just create a DBeaver database connection in this project.

**Comment by lockmotiv** [comment]
This one did the trick. Thanks!
