### ISSUE TITLE
Bug report: Hidden panel when opening "Edit Connection" window.

### ISSUE THREAD

**Issue by marcopin** [dbeaver/dbeaver#3013]
Hi,
I use dbeaver in my work and I think it's a very useful tool.

I want to report this bug:
Xubuntu 16.04, 64bits: when opening "Edit Connection" window the lower panel is hidden and when this window is resized then lower panel appears.

![lower-panel-hidden](https://user-images.githubusercontent.com/3383909/36426214-c3322b6a-161f-11e8-9b5f-f5a376b2743f.png)
![lower-panel-shown-after-resize](https://user-images.githubusercontent.com/3383909/36426223-c9827aa6-161f-11e8-9bd1-92fe2044b0d0.png)

**Comment by serge-rider** [comment]
I've seen similar behavior on some Macs (with 4k).

**Comment by serge-rider** [comment]
Fixed
