### ISSUE TITLE
Transaction Blocks not working after most recent update 

### ISSUE THREAD

**Issue by Chandler149** [dbeaver/dbeaver#30147]
### Description

Whenever trying to use a transaction after updating my DBeaver, away from the Christmas logo might I add, it reads the statements above regardless of what I try to do. The only fix I have found is if you paste it at the very top with no code above, it does seem to run properly, still hoping for it to go back to normal. 

### DBeaver Version

24.0.3.202404211624

### Operating System

Windows 11

**Comment by E1izabeth** [comment]
Please try 24.0.4 version. It has already been fixed.

**Comment by E1izabeth** [comment]
Duplicate of #26416
