### ISSUE TITLE
Invalid object name 'maestro-api-dev.Properties' while opening the "Data" tab from an Azure databse's table

### ISSUE THREAD

**Issue by aibars** [dbeaver/dbeaver#3014]
Hi,

After I tried to see the data from a table of an Azure SQL database, I got the following message:

```SQL Error [208] [S0002]: Invalid object name 'server-name.table-name'.
  Invalid object name 'server-name.table-name'.
  Invalid object name 'server-name.table-name'.
```
Of course, `server-name.table-name ` is the actual Azure SQL server name and the table I wanted to open.

I think this issue was introduced on the latest version 4.3.5 for Windows x64.

Thank you.

**Comment by serge-rider** [comment]
What driver/version do you use for Azure?

**Comment by serge-rider** [comment]
Can't reproduce without additional details
