### ISSUE TITLE
Feature Request: Disconnect All or Reconnect All

### ISSUE THREAD

**Issue by pburney** [dbeaver/dbeaver#3015]
Hi Serge,

I really love DBeaver. It's a great piece of software and your timely updates are very much appreciated. 

For work, I use DBeaver to connect to multiple MS SQL Server instances (typically around 10 at any given time). When I switch networks from wired to wireless to VPN etc., the connections to those instances are no longer valid. I've experimented a bit with the loginTimout driver property but that doesn't seem to work well in this case.

I think it would be great if there was a button in the UI somewhere (or a menu option) that would disconnect all connections. It would be even better if it could re-connect them all as well. Another thought that might be easier to implement would be to have a connect all / disconnect all / reconnect all option on the folder containing the connections.

Thanks for your consideration,

-Paul

**Comment by serge-rider** [comment]
Disconnect All is already there:
![image](https://user-images.githubusercontent.com/6398845/36447803-898fcde6-1696-11e8-96f0-50331fad176e.png)

Reconnect is a bit tricky. 
Should it be done simultaneously or one by one?
Each attempt may cause another error(s) leading to lots of errors on a screen if server is not accessible for some reason.

**Comment by pburney** [comment]
Good question. I'd think maybe it would try one and if successful, then continue on to others. If there's an error, it would prompt the user with the error message and ask whether to continue trying or to give up.

I think for my purposes, though, the Disconnect All in the menu is perfect. I just set it to a keyboard shortcut and I think that will work great with my work-flow. I'll close this issue, though you or others are welcome to re-open it if Reconnect All would be helpful.

Thanks so much for the fast response!
