### ISSUE TITLE
Connection created from command line with -con command does not show Windows Authentication correctly

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#3016]
DBeaver - **Version 4.3.5 CE**
DBeaver JDBC driver: **Microsoft Driver**
Operating System: **Windows 7** / **Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

If I request _DBeaver_ to start up and create a connection from the command-line, the **Connection Settings** dialog does not show the information for choosen value for **...|prop.integratedSecurity=true|...** correctly.

**o** From the command-line execute the command:

`
C:\...> dbeaver.exe
-con "name=TEST|driver=mssql_ms|host=localhost|port=1433|database=master|prop.integratedSecurity=true"
`

**o** When _DBeaver_ start up choose to **Edit Connection**.
**o** Notice that the **Windows Authentication** check box is not checked.
**o** Notice that the **User Name** and **Password** edits are not grayed and editable.
**o** Notice that the **Driver Properties** dialog show that **integratedSecurity=true** correctly.

My guess is that when the new **Connection Settings** was created with the check box
for **Windows Authentication**, it was a one way functionality. Ought to be bidirectional.

**Comment by serge-rider** [comment]
Thanks for report.
