### ISSUE TITLE
Feature: Merge table navigation using Navigate link and Referencing tables into one command

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#3017]
DBeaver - **Version 4.3.5 CE**
Operating System: **Windows 7** / **Windows 8.1**

Instead of having the two navigations below:

**o** Right click on a table cell and choose **Navigate** -> **Navigate link** (Alt+Space).
**o** Right click on a table cell and choose **Navigate** -> **Referencing tables** (Ctrl+1).

Merge them into one command that does both direction navigation that look something like:

**o** Right click on a table cell and choose **Navigate** -> **Related data** (Alt+Space).

The result of the one command, could be a grid that looks something like:

_&lt;Table Referenced&gt;_
&nbsp;&nbsp;&nbsp;**Table 1 name**
_&lt;Table References&gt;_
&nbsp;&nbsp;&nbsp;**Table 2 name**
&nbsp;&nbsp;&nbsp;**Table 3 name**
&nbsp;&nbsp;&nbsp;**...**

PS. The new function to be able to navigate **Referencing tables** in _DBeaver_ version **4.2.6** (from support issue #2044) is super great. Makes navigation between tables a breeze. Great job!

PPS. Compare functionality [JetBrains DataGrip](http://www.jetbrains.com/datagrip) to have one command for navigation in both directions.

[YouTube movie clip 1](https://www.youtube.com/watch?v=Xb9K8IAdZNg) (_at timestamp 01:05 in the movie_)
[YouTube movie clip 2](https://www.youtube.com/watch?v=RlNEwBhckDA) (_at timestamp 13:40 in the movie_)

**Comment by serge-rider** [comment]
I'm not sure this is the best approach. <kbd>ALT+Space</kbd> navigates on current cell link. There are many different destinations and they depend on focused cell (row + column).
While references tables depend on focused row (corresponding unique key) and are the same for all columns of this row.
Having single interface for them isn't very consistent. But maybe I'm missing something..

**Comment by serge-rider** [comment]
I think I keep both commands but Referencing tables will show links in both directions.

**Comment by serge-rider** [comment]
Done.
Also added foreign key name (as some table can be linked multiple times).
Also using <kbd>Ctrl+Shift+1</kbd> will open associated table in new window.

![image](https://user-images.githubusercontent.com/6398845/43369462-721036ca-9377-11e8-98d0-471945b103d7.png)

**Comment by pdanie** [comment]
Thanks a million. Super great implementation. Good work.
