### ISSUE TITLE
Default action when dismissing the Execution Error dialog

### ISSUE THREAD

**Issue by antoniustefan** [dbeaver/dbeaver#3019]
The Execution Error dialog that is shown when encountering errors in a script has the default button Stop, but the default action (when closing it or pressing Escape) as Ignore.
Is this intentional? I think it would be best if Stop was the default also when dismissing it.

Thank you!

**Comment by serge-rider** [comment]
This is a bug. It definitely should stop script on ESC.
Thanks for noticing.
