### ISSUE TITLE
Auto complete in SQL Server

### ISSUE THREAD

**Issue by lestevam** [dbeaver/dbeaver#3020]
I have had problems with auto completing.
I have many objects with similar names, but when trying to find an exact name it does not auto-complete the searched object directly, I noticed that if you give ESC and later a CTR + SPACE the auto complete correctly focuses the searched object.

I am using the driver: Microsoft JDBC Driver for SQL Server
OS: Windows 2008 R2

Congratulations to all involved in this project!

**Comment by uslss** [comment]
is issue still actual for you?

**Comment by uslss** [comment]
there is no update more than a month. Ticket closed.
If issue is still actual feel free to reopen the ticket or create a new one.
