### ISSUE TITLE
Missing table description on DB2 / DB2 iSeries/AS 400 driver

### ISSUE THREAD

**Issue by Anthael** [dbeaver/dbeaver#3022]
On tables, fields descriptions and tooltip are missing .

**Comment by Anthael** [comment]
Driver or tool issue ?

**Comment by serge-rider** [comment]
It is driver of connection properties (e.g. "remarks" driver property value).
Check this: https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/rzahh/javadoc/com/ibm/as400/access/doc-files/JDBCProperties.html

**Comment by serge-rider** [comment]
Setting `remarks` property to `sql` or `system` should help
