### ISSUE TITLE
[PostgreSQL] Comment is lost when adding new column to a table

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#3023]
I found a bug: When I add a new column to an existing table and provide a comment (description) for this column then DBeaver does not save the comment nor does it generate any DDL for it. After adding a column with a comment and hitting "Save" I am presented with DDL like this:

`ALTER TABLE public.my_table ADD col_name bool NOT NULL DEFAULT false ;`

The comment DDL is missing and when I click "Persist" the column is added and the comment I have entered disappears from the view. In order to add the comment I have to enter it again to a column that already exists and only then I get the proper DDL like this:

`COMMENT ON COLUMN public.my_table.col_name IS 'my comment' ;`

**Comment by serge-rider** [comment]
Thanks for report

**Comment by lemon-juice** [comment]
great!
