### ISSUE TITLE
[PostgreSQL] Adding comments to constraints

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#3024]
DBeaver lacks the ability to add comments to table constraints (FK's, PK's and check constraints). It also doesn't detect and show existing comments of constraints. It would be great if DBeaver supported this feature. I think this should consist of:

1. When using Edit Constraint: new field for comment/description in the properties tab.
2. When using Create New Constraint: new field for comment/description.
3. Creation of comment DDL's like this: `COMMENT ON CONSTRAINT constr_name ON public.table_name IS 'constraint comment';`
4. Displaying constraint comments as mouse-over tool tips in the Navigator pane (just like for table columns).

**Comment by serge-rider** [comment]
Constraints and foreign key comments are now read from DB. Comment edit is also fully supported.
All constraint comments are also included in table DDL.
