### ISSUE TITLE
Truncate destination table when exporting to database

### ISSUE THREAD

**Issue by chrismoors** [dbeaver/dbeaver#3025]
Hey I'd love to be able to truncate a destination table before importing new data when using the export wizard (either from directly from query,results or the tables themselves.)  Any chance this could be added?

**Comment by serge-rider** [comment]
Good point

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/39144972-00faa0f2-473b-11e8-8c74-02f8958049fc.png)
