### ISSUE TITLE
Copy tables (Oracle)

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#3026]
It would be great to have Copy Table (to another schema) function.
In Oracle (and some other bases) it can be implemented as a tool which generates SQL like this:
```sql
CREATE TABLE destschema.TARGET_TABLE AS 
SELECT * FROM srcschema.SOURCE_TABLE
```
It is very handy if you have a lot of tables to copy.

**Comment by yevon** [comment]
I would make it more generic for all kind of objects, you can do it with dbms_metadata package. It would be nice to select multiple objects, right click and press "Generate DDL". It would open a new editor with generated DDL statements.

http://www.dba-oracle.com/t_1_dbms_metadata.htm

select 
   dbms_metadata.GET_DDL(u.object_type,u.object_name,'PUBS')
from 
   dba_objects u
where 
   owner = 'PUBS';

Or with user_objects:

select 
   dbms_metadata.GET_DDL(u.object_type,u.object_name,'PUBS')
from 
   user_objects u
