### ISSUE TITLE
connect to oracle via cmd

### ISSUE THREAD

**Issue by harrysus** [dbeaver/dbeaver#3029]
Hi guys,

need your support. i wanna connect to oracle via command line.
i already using this command : 
dbeaver-cli.exe -con driver=oracle|host=192.168.19.1|port=1521|database=XE|user=DBTEST|password=P@ssw0rd|connect=true|openConsole=true

dbeaver-cli.exe -con driver=oracle|//192.168.19.1:1521/XE

dbeaver-cli.exe -con driver=oracle|host=//192.168.19.1:1521/XE

but doesn't working.
the error is : IO Error: Invalid connection string format, a valid format is: "//host[:port][/service_name]"

do you have any idea ?

Thanks,
Harry

**Comment by yevon** [comment]
Why don't you use oracle client for this purpose with sqlplus? You just need to download oracle instantclient and add a system path to the sqlplus executable.

http://www.oracle.com/technetwork/topics/winx64soft-089540.html

**Instant Client Package - SQL*Plus: Additional libraries and executable for running SQL*Plus with Instant Client**

**Comment by serge-rider** [comment]
@harrysus Check what URL DBeaver uses to connect. 
You can get it in Properties view (main menu Window->Show View->Properties). Just select connection in navigator and see Server-URL property value.

**Comment by harrysus** [comment]
hi @yevon i wanna integrate dbeaver with cyberark, currently the customer using dbeaver for connecting to oracle. i wanna create custom script for connecting to oracle using dbeaver via command line.

hi @serge-rider i already tried, but still not work. 
dbeaver-cli.exe -con driver=oracle url=jdbc:oracle:thin:@//192.168.19.1:1521/XE, thats correct ?


Thanks,
Harry

**Comment by serge-rider** [comment]
Well, your first example should work. But you should use driver `oracle_thin`.
-con driver=oracle|host=192.168.19.1|port=1521|database=XE|user=DBTEST|password=P@ssw0rd|connect=true|openConsole=true

**Comment by decebals** [comment]
I encounter the same problem like @harrysus.
My use case is that I want to open DBeaver with a predefined database connection from Java application. So, I know the path to DBEAVER_HOME (the directory where dbeaver was installed), I know the database connection parameters (url, username, password, ...) and I want to open dbeaver exactly on this database connection.
Now, I use DbVisualizer as database tool and I want to migrate to DBeaver.

DBeaver version: 
   `5.0.0`
Command lines tried:
   `dbeaver-cli.exe -con driver=oracle_thin|name=TEST|url=jdbc:oracle:thin:@192.168.16.5:1521:orcl|user=u|password=p`
   `dbeaver -con driver=oracle_thin|name=TEST|host=192.168.16.5|port=1521|database=orcl|user=u|password=p`
Error:

**Comment by decebals** [comment]
After I receive the error, if I edit connection parameters via "Edit Connection" (F4) everything work perfect. 
I use ojdbc8 as Oracle driver but I don't think that is relevant.

Another feedback/observation is that the error message is not complete (useful) in my opinion, they lack information about the string used by dbeaver to connect to database (something like `jdbc:oracle:thin:@192.168.16.5:1521:orcl`).

**Comment by decebals** [comment]
Somehow, I resolved the problem (something strange with my environment). I can confirm that it works.
