### ISSUE TITLE
Auto complete doesn't work at join tables in delete statements

### ISSUE THREAD

**Issue by carlosspohr** [dbeaver/dbeaver#303]
Hi there,

All delete queries that have table joins, as in example below, at `'on (...) '` point, doesn't open the field list, just field of target table `'f.bar'`. Just remember, I always use table aliases, even for sub-queries.

``` sql
delete
    b
from
    bar b
        join foo f on (f.bar = b.<HERE DON'T THROW FIELD LIST>)
where
    1=1
;

update
    bar b
        join foo f     on (f.bar = b.<HERE DON'T THROW FIELD LIST>)
        join other o on o.bar = b.<HERE DON'T THROW FIELD LIST>
set
    b.bla = 'bla'
where
    1=1
;
```

Sometimes it also happens on update queries, and this 'bug' appears since older versions. Fields dialog doesn't appears by auto trigger or triggering through **Ctrl + Space;**

**Comment by uslss** [comment]
issue is not reproduced on 6.0.2
