### ISSUE TITLE
launch error after updating to DBeaver 4.3.5

### ISSUE THREAD

**Issue by riazXrazor** [dbeaver/dbeaver#3030]
please help getting error i hv attached the log file generated.

[1519379473000.log](https://github.com/dbeaver/dbeaver/files/1751196/1519379473000.log)

**Comment by serge-rider** [comment]
DBeaver 4 requires Java 8 (while you have Java 7 installed).

**Comment by riazXrazor** [comment]
thanks @serge-rider.

**Comment by riazXrazor** [comment]
yup its fix :) :+1: :100:
