### ISSUE TITLE
[PostgreSQL] Invalid source SQL/DDL for constraints and FK's

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#3031]
When I edit a constraint or a FK DBeaver generates SQL in the Source tab like this:

`ALTER TABLE table_name CREATE CONSTRAINT ...`

this is invalid and causes syntax error. It should be:

`ALTER TABLE table_name ADD CONSTRAINT ...`

**Comment by serge-rider** [comment]
Thanks for report

**Comment by lemon-juice** [comment]
Great, thanks!
