### ISSUE TITLE
copy to the column of numeric type ,content is not correct

### ISSUE THREAD

**Issue by highgoyangguoqing** [dbeaver/dbeaver#3035]
The Content at Clipboard is '99***7'. When I copy the content to the editor,then '99' is showed. I think null is correct.Please check .
![image](https://user-images.githubusercontent.com/34262632/36624635-8f62f866-194c-11e8-933a-cf2d3cf66630.png)

**Comment by serge-rider** [comment]
Well, why do you think that NULL is more correct? For clipboard paste DBeaver parses input number until the first error. Looks like a correct (and preferred) behavior for me.

**Comment by highgoyangguoqing** [comment]
When input number is unlawful，then parsed value is NULL. I think. Or a hint had at least for customer.

**Comment by serge-rider** [comment]
No sure about this. But we can change default behavior if more people will vote for that.

**Comment by highgoyangguoqing** [comment]
Thanks very much.
