### ISSUE TITLE
SSH tunnel password prompt when connecting with public key method

### ISSUE THREAD

**Issue by CurvesTech** [dbeaver/dbeaver#3036]
When you create a connection using SSH Tunnel, and  use public key for authentication method. 
On clicking 'Test Connection', it prompts for the password, It works if you leave it blank, and goes ahead with the key and connects successfully. But it results in a confusing experience. So it probably is a UI bug.

**Comment by serge-rider** [comment]
What DBeaver version do you use? This bug was fixed in 4.3.x if I remember correctly..

**Comment by CurvesTech** [comment]
4.3.0





Sent from OPPO Mail
On Serge Rider <notifications@github.com>, Feb 24, 2018 6:17 PM wrote:

What DBeaver version do you use? This bug was fixed in 4.3.x if I remember correctly..

**Comment by serge-rider** [comment]
Just checked, it was fixed in 4.3.3, just upgrade to the most recent version.

**Comment by serge-rider** [comment]
Actually it was fixed in #1115 ticket (see comments).
