### ISSUE TITLE
Exporting data from data browser view is broken

### ISSUE THREAD

**Issue by GiantCrocodile** [dbeaver/dbeaver#3040]
Windows:
1. open a DB table
2. context menu > export result
3. try to export this data

Export succeeded according to Dbeaver but failed in reality: The $ sign in file name causes a problem.

**Comment by serge-rider** [comment]
Can't reproduce (export works fine in my case). Please post error message/stacktrace or error log.

**Comment by GiantCrocodile** [comment]
There is no error. If I don't remove the $, no file will be created on my desktop.

**Comment by serge-rider** [comment]
What exactly file name do you use?

**Comment by GiantCrocodile** [comment]
Filename pattern: {table}_${timestamp} -> {table}_${timestamp}

With our without the $ sign, the file name is always the same. I try to export a json file. See this:
![grafik](https://user-images.githubusercontent.com/6271057/36643999-d689c1ae-1a53-11e8-946a-5167ccf3b425.png)

**Comment by serge-rider** [comment]
Both these patterns work fine in my case.
Please check logs (https://github.com/dbeaver/dbeaver/wiki/Log-files) for any related errors/warnings.

**Comment by GiantCrocodile** [comment]
Nothing has been logged, there is not even a *.log file at all in DBeaver program folder nor in AppData.

**Comment by uslss** [comment]
Cannot reproduce the issue on 6.2.0. Ticket is closed.
If issue is still reproducible for you feel free to reopen the ticket.
