### ISSUE TITLE
bundle_zh.properties “rowCount” translation error

### ISSUE THREAD

**Issue by helppass** [dbeaver/dbeaver#3042]
nls/bundles/org.jkiss.dbeaver.ext.mysql.nls/OSGI-INF/l10n/bundle_zh.properties

meta.org.jkiss.dbeaver.ext.mysql.model.MySQLTable$AdditionalInfo.rowCount.name=\u884C\u6280\u672F
"行技术" ：“row technology”

it should be "行计数”: "row count"
meta.org.jkiss.dbeaver.ext.mysql.model.MySQLTable$AdditionalInfo.rowCount.name=\u884C\u8BA1\u6570

**Comment by serge-rider** [comment]
Thanks for noticing!
