### ISSUE TITLE
Can't open folders with left/right arrow buttons in database view

### ISSUE THREAD

**Issue by antonlukyanov** [dbeaver/dbeaver#3043]
I'm using DBeaver 4.3.5 with KDE 4.14 (CentOS 7.4) and can't open folders in database view using keyboard (left and right arrows). I didn't find any shortcuts for such an action either. So the question is: is it KDE bug or not?

![folders](https://user-images.githubusercontent.com/935193/36669648-a84b105a-1b06-11e8-80b7-5ac8a3602ac2.png)

**Comment by serge-rider** [comment]
Well, these shortucts works fine on Windows. And this is native OS control.
So I assume this is KDE-specific issue.

**Comment by antonlukyanov** [comment]
Left and right keys work fine on macOS too. I've tested the latest dbeaver release on openSUSE with KDE 5.8.7 installed assuming it might be because of rather old KDE version on CentOS. But left and right keys still don't work.

**Comment by serge-rider** [comment]
Yep.
However it is definitely not a DBeaver issue.
