### ISSUE TITLE
Invisible rows in result view

### ISSUE THREAD

**Issue by ldesousa** [dbeaver/dbeaver#3047]
DBeaver 1.0.35 on Eclipse 4.7.2. Every other row of the results view is invisible.

![dbeaver](https://user-images.githubusercontent.com/1137878/36732157-3570ced6-1bcd-11e8-9a26-6b7909e2a8e9.png)

**Comment by alesc2000** [comment]
I think it's because of the background color of odd rows. You can change it:
![screenshot from 2018-02-27 18-47-35](https://user-images.githubusercontent.com/19900533/36741854-db2f48d6-1bee-11e8-989a-e2ece77b79aa.png)

**Comment by serge-rider** [comment]
Sometimes this happens after theme switch. Sometimes it can be fixed by editor re-open.
But sometime it is fixed only after DBeaver restart.

**Comment by ldesousa** [comment]
I think this should be market as a bug, not as a question. Results should be visible by default, imho, and not require some special colour tweaking.

**Comment by serge-rider** [comment]
@ldesousa sure they should. This is how this look in our test env:
![image](https://user-images.githubusercontent.com/6398845/36811711-cc1e19fc-1cdf-11e8-88b4-485cbc8c7874.png)

Does this mean that editor reopen and DBeaver restart doesn't help and colors are still corrupted?

**Comment by serge-rider** [comment]
This issue exists only in Eclipse plugin version, in standalone DBeaver default colors for dark theme are fine.
They are defined in https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.core/css/e4-dark_dbeaver_prefstyle.css
