### ISSUE TITLE
Result set editor stops input when using auto refresh in a Sessions tab

### ISSUE THREAD

**Issue by rscs** [dbeaver/dbeaver#3049]
Bug related to #2050.

If I have a "Sessions" tab open with auto refresh on and I am editing a table result set in another tab, the result set editor stops taking my input whenever the "Sessions" tab refreshes ... as if I had hit Enter or clicked out of the input box. I then have to click back into the input box to continue typing, but only if I type fast enough before the next refresh interval comes around.

This does not happen when using auto refresh on another table result set; it only happens when using auto refresh in a separate "Sessions" tab.

**Comment by serge-rider** [comment]
Thanks for report
