### ISSUE TITLE
Ctrl + F to find column name in Results Grid

### ISSUE THREAD

**Issue by ashokjv** [dbeaver/dbeaver#3052]
I think a feature to Ctrl + F to find column name in Results Grid will be very useful. I don't think DBeaver can do this currently ? It is only possible to search for data in results grid

Generally in very large tables, it is very tedious to scroll left, right to search for columns.

**Comment by serge-rider** [comment]
It is not possible for now.

Workaround (silly): switch to record mode (TAB), then order columns alphabetically and find your column. Then switch back to grid.

**Comment by lazb** [comment]
This is the only thing that I'm missing from Navicat switch.

**Comment by bicaydaha** [comment]
for dbeaver; click [tab] and [ctrl + f] then search your target column name. thats it

**Comment by bicaydaha** [comment]
> I think a feature to Ctrl + F to find column name in Results Grid will be very useful. I don't think DBeaver can do this currently ? It is only possible to search for data in results grid
> 
> Generally in very large tables, it is very tedious to scroll left, right to search for columns.

for dbeaver; click [tab] and [ctrl + f] then search your target column name. thats it

**Comment by LendLord** [comment]
+1 for this

**Comment by nasikgears** [comment]
> > I think a feature to Ctrl + F to find column name in Results Grid will be very useful. I don't think DBeaver can do this currently ? It is only possible to search for data in results grid
> > Generally in very large tables, it is very tedious to scroll left, right to search for columns.
> 
> for dbeaver; click [tab] and [ctrl + f] then search your target column name. thats it

+1

**Comment by weeejw** [comment]
+1

**Comment by ghost** [comment]
+1 for this

**Comment by bmnascimento** [comment]
+1 for this

**Comment by endrilz** [comment]
You can also use the filter button from above the table, it will take you to a list of all column names where you can enter the search string at the top. The TAB suggestion is also really nice, thanks!

![Image 2023-07-03 15-33-48](https://github.com/dbeaver/dbeaver/assets/33114614/1c2950ff-6b2d-47bf-894e-5bfcddf69ecf)



In case you want to search for a column name across the entire structure of the db, use the search function form the top menu bar (looking glass icon), then select Table and Table Column as Object Types, it's impressively fast and useful. 

![Image 2023-07-03 15-33-09](https://github.com/dbeaver/dbeaver/assets/33114614/083aa37c-5a49-4535-8461-3bee058b15b7)


I am very grateful for dbeaver and the wonderful work of the wonderful people behind it. It's a pleasure to use and saving me tons of time and mental energy :D

**Comment by endrilz** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/33114614/b51abc3a-43c0-4d91-bf47-9609eae241ba)

**Comment by henghengyang** [comment]
+1 for this

**Comment by arhayka** [comment]
We want to do the following: 
1. add  a filter to the Metadata panel
2. add an item **Find column** to the Context menu and a shortcut for it as a "Go to line"
3. rename "Go to line" to "Go to row"

**Comment by LonwoLonwo** [comment]
Duplicate? https://github.com/dbeaver/dbeaver/issues/14742
