### ISSUE TITLE
Pasting from Java source doesn't handle casting properly

### ISSUE THREAD

**Issue by petromir** [dbeaver/dbeaver#3054]
Imagine that I have the following SQL presented in Java source file:

```java
String sql = "select (foo.bar=:bar)::::int" // query doesn't work without ::::
```
If I select the entire string and paste it in DBeaver `::::` is not converted to `::`

**Comment by serge-rider** [comment]
Well, this is no standard.
PostgreSQL specific?

**Comment by petromir** [comment]
Yes, we are using PostgreSQL and this is some kind of escaping. Not sure if this is required when using other databases in Java.
