### ISSUE TITLE
Dbeaver crashing OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by dsofeir** [dbeaver/dbeaver#3055]
Dbeaver 4.3.5 is crashing my machine when I run it on a fresh install of OpenSUSE Tumbleweed (kernel 4.15.5-1) on a Lenovo 720S (Ryzen 7 2700U).

Happens when I install from the .rpm or run `dbeaver -clean -vm /usr/loca/java` from the extracted .tar.gz.

Output from `dbeaver` command in terminal is as seen here: 
![20180228_222207](https://user-images.githubusercontent.com/2790648/36785448-f1e93d78-1cd6-11e8-9729-8bfe24c4074b.jpg)

**Comment by serge-rider** [comment]
Please check for any hs_* log files in the directory where you start DBeaver. They should contain stacktrace which can help.
Thanks

**Comment by dsofeir** [comment]
Unfortunately not, there are no hs_* files. Is there a parameter I can set to enable debug logging?

**Comment by serge-rider** [comment]
Perhaps this warning from Open JDK is related (never saw this before).
What is your Java version (run `java -version` in console)?
Is it 32/64 bit? 
Did you try another version of DBeaver (32bit)?
