### ISSUE TITLE
Confluence Wiki Markup table output / custom DSV formats

### ISSUE THREAD

**Issue by dmccanny** [dbeaver/dbeaver#3056]
It would be very useful to be able to export the result of a query as Wiki Markup, e.g. when working with confluence. The alternative is to export as CSV and then manually fix the data.

For example this is how DataGrip handles it.
https://blog.jetbrains.com/datagrip/2017/11/08/export-data-in-any-way-with-intellij-based-ides/

**Comment by serge-rider** [comment]
Yep, this could be helpful
