### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by carlosherranz** [dbeaver/dbeaver#3058]
When there are very large fields in result grid that not fit in the screen width,  when enlarge a large field would it be possible to have horizontal scrollbar to see well all its content?
Thanks

**Comment by serge-rider** [comment]
It is not supported at the moment but you can use plain text presentation or Vale View panel for that.

**Comment by serge-rider** [comment]
In 5.2.4 we'll add columns pack actions:
![image](https://user-images.githubusercontent.com/6398845/47935559-d1013c00-deeb-11e8-8e62-b6fda16c5d47.png)
