### ISSUE TITLE
[Oracle] Copy/Paste Float value problem 

### ISSUE THREAD

**Issue by fayca121** [dbeaver/dbeaver#3062]
Hello,

I've tried to change a number value directly in the result pane by copy/paste a new number, I've noticed that after commit another value is shown instead of the expected one.

Steps to reproduce that : 

- CREATE TABLE TABLE_A
   (
   COLUM1 FLOAT(126) NOT NULL
   ) ;

-  INSERT INTO table_A VALUES (1);
-  select * from table_A 
-  Copy for example the number 1073741824 and paste it to replace the value of the result .
- Save and commit.
-  select * from table_A 

As a result, the number 1073741820 is shown instead of 1073741824 

Should I change any setting to fix that ?
 
Thanks

-----------------------------------------------------------
My current Config:
---------------------
Dbeaver CE 4.3.5
Oracle 11g
Java 8
ojdbc6.jar
Windows 7 x64

**Comment by serge-rider** [comment]
Can't reproduce.
Please post Oracle driver exact version (you can get it from Properties view or in connection settings dialog by clicking on Test connection).

**Comment by fayca121** [comment]
![2018-03-03 10_55_57-success](https://user-images.githubusercontent.com/547548/36933003-1666102a-1ed2-11e8-9c14-ad92345e00a4.png)

**Comment by fayca121** [comment]
Hi,

I think the problem comes from copy/paste of a big float value (without decimal part)
When I try to paste for example 9999999999 I always get the value 10000000000 displayed on the result grid but if I write it directely the problem doesn't occur.

**Comment by serge-rider** [comment]
I've reproduced that. Indeed, this is a bug in copy-paste handler. Thanks for report.
