### ISSUE TITLE
Saved passwords view

### ISSUE THREAD

**Issue by Xtinction** [dbeaver/dbeaver#3066]
Hey guys,

I think it's kind of weird that DBeaver stores your database passwords in plain text in the .dbeaver-data-sources.xml file. That seems like a pretty big breach in data security. Am I wrong? Feels like the passwords should not be stored in that file, but seperately, hashed somewhere...

**Comment by serge-rider** [comment]
DBeaver EE and DBeaver Eclipse plugin versions support passwords storage in secured database (encrypted with master password).
You can enable this in Preferences->Database->Security.

Regarding CE version:
Many users share database configurations so they need to keep password in the same configuration file (which is actually resides in some version control system).
But if your database passwords are secure then you can disable passwords save at all.

**Comment by hginzel** [comment]
Add a feature to see stored passwords in DBeaver in the same way as in Firefox for example, please. Why not to show passwords directly on explicit request when [there is a software](https://stackoverflow.com/questions/39928401/recover-db-password-stored-in-my-dbeaver-connection) for easily decrypting?

**Comment by serge-rider** [comment]
I'm still not sure that we should do this in default DBeaver configuration (without master password, cloud-based credentials storage or something similar). This is way too not secure (anybody will be able to see passwords in a second).
Postponing this feature for a while..

**Comment by khanhicetea** [comment]
> Regarding CE version:
> Many users share database configurations so they need to keep password in the same configuration file (which is actually resides in some version control system).
> But if your database passwords are secure then you can disable passwords save at all.

I don't see any points when users share their database configurations by sending whole .xml file within all weak encrypted passwords.
How about store master encrypt key in OS keychain ? They can share the file but re-update password by himself later.

Btw, thanks for great job 👍

**Comment by serge-rider** [comment]
The best way to implement "See password" would be to use the same approach as in Chrome: ask user to enter current OS password/pin/whatever.
However I doubt that this is possible (at least easily)in Java. It is very OS-dependent and requires different UIs for different auth models.

Another way is to use master password in dbeaver itself. Use this password (hash) to encrypt secure credentials and to unlock "View password" feature.
However it also requires change of general auth model and extra UI..

Any other ideas?

**Comment by khanhicetea** [comment]
Agree!

Master Password is a good way to go if we don't want to mess with OS-dependent keychain systems.

**Comment by kseniiaguzeeva** [comment]
verified
