### ISSUE TITLE
Unable to export data as sql

### ISSUE THREAD

**Issue by jiatz85** [dbeaver/dbeaver#3075]
Hi, I am unable to export a table as an sql insert statement

using version 4.3.5 on Windows 10
![dbeaver export issue](https://user-images.githubusercontent.com/8371776/36956065-32b497ba-2067-11e8-8d40-5fa7b103d976.png)

**Comment by uslss** [comment]
cannot reproduce the issue.
ticket closed.
if it is still actual for you - feel free to reopen the issue
