### ISSUE TITLE
Export Resultset CSV still using quotes for subsequent columns when quotes not selected 

### ISSUE THREAD

**Issue by hollerith** [dbeaver/dbeaver#3079]
1.  Select from the table of 

select distinct stringdata
     , 0
     , replace(convert(varchar(8), [timestamp], 112)+convert(varchar(8), [timestamp], 114), ':','') --  datetime 
     , lfloat1
     , lfloat2
     , 0
     , 0
     , ''
  from SQLSERVERTABLEJOIN

2. Export to Resultset. (Clipboard)
We do not want any quotes at all - so deselected by removing quote character. Uncheck quote always. 

Without doing this we would get:
"XY99ABC", 0, "20180302215609"	53.7025	-0.875139	0	0	

Doing this we get 
XY99ABC, 0, "20180302215609", 53.7025, -0.875139, 0, 0	

3. Expected to get:
XY99ABC, 0, 20180302215609, 53.7025, -0.875139, 0, 0

**Comment by Xrizoo** [comment]
Hi... I've got the same issue but with quotes. My problem is about no quotes when the entire string  didn't start with number:
With:
`select 
    'DDS'   as STR,    
    33      as NUM1,
    '33'    as NUM2
from DUAL;`
I get:
`DDS;33;"33"`

Modifing STR column:
`select 
    '0DDS'   as STR,    
    33      as NUM1,
    '33'    as NUM2
from DUAL;`
I get:
`"0DDS";33;"33"`
Now, quotes appears!!

**Comment by serge-rider** [comment]
You can use <kbd>space</kbd> as quote character. This will remove quotes at all.
Maybe we need separate export property for that. Or somehow make this config more obvious.
![image](https://user-images.githubusercontent.com/6398845/37560554-acb62afe-2a4b-11e8-995d-4f1191f19c92.png)

**Comment by serge-rider** [comment]
I've added property "Quote never".
