### ISSUE TITLE
Close all opened connections on a project

### ISSUE THREAD

**Issue by crochut** [dbeaver/dbeaver#3080]
Feature request : 
Would it be possible to close "all" opened connection on a project. 
it would be very kind to select a project and have a menu entry to close all opened connection on this project.
Currently, we must connection one by one. 
TY
Best regards

**Comment by serge-rider** [comment]
This is already supported (but for whole workspace):
![image](https://user-images.githubusercontent.com/6398845/37140101-974a78fa-22c1-11e8-8735-848a33934b8d.png)

Do you think that disconnecting just one project still makes sense?

**Comment by crochut** [comment]
I haven't seen this feature before. 
It's a great feature but closing all connections of a project could still makes sense.
We have created one project by environnement (production, preproduction, integration ...).
Before an upgrade on an environnement, we wan't close all opened connections on this environnement without closing connection on other environnement.

Best regards

**Comment by serge-rider** [comment]
Disconnect Project command will be added in 6.1.5. It is visible only when there are multiple projects in the current workspace.

**Comment by kseniiaguzeeva** [comment]
Verified
