### ISSUE TITLE
F3 for new SQL Editor

### ISSUE THREAD

**Issue by TomGeoDK** [dbeaver/dbeaver#3081]
The current version is sporting Ctrl + [ and Ctrl + ] to switch or respectively create a new SQL Editor. In older versions, at least the shortcut for a new SQL editor was F3. Could the F3 shortcut be re-established? User with keyboards layouts where [ and ] are only accessible via AltGr cannot use the current shortcuts.

**Comment by chrisdabel** [comment]
I believe the new shortcuts were chosen because the old shortcuts did not work for mac users on Mac OS. You should have the ability to change it back, though, unless the latest version removed that from preferences.

**Comment by serge-rider** [comment]
Well, we can return F3 as default shortcut on Windows. And use ctrl+[] on MacOS/Linux.,
