### ISSUE TITLE
Dead lock on update with no rows

### ISSUE THREAD

**Issue by Anthael** [dbeaver/dbeaver#3084]
If an update sql command is performed having 0 result record,  the lock is kept on the engine.
ie update mytable set valx = 'test' where id= 5;
and the record 5 doesn't exists, the engine is keeping a lock.

The command Commit or Rollback doesn't affect the query and the lock is not removed.

**Comment by serge-rider** [comment]
I can't reproduce such behavior. What is your database?

Although I don't think that this is related to DBeaver.
