### ISSUE TITLE
[postgresql] issue on sort in index 

### ISSUE THREAD

**Issue by titep** [dbeaver/dbeaver#3085]
Hello,
there is a funny behavior on sort in index.

database : postgresql 9.6
dbeaver : 4.1.0
the sql script used is 
CREATE INDEX xxx ON yyy (aaa DESC, bbb DESC, ccc ASC);
the ddl generated by dbeaver
CREATE INDEX xxx ON yyy (aaa, bbb, ccc DESC);
it looks like the sort is reversed
and the case asc seems to be the default and is not in the generated ddl

dbeaver : 4.3.5
the behavior set all to asc

pgAdmin provides the good information.

hope this helps.
Bye.

**Comment by greenpeas** [comment]
And:
![image](https://user-images.githubusercontent.com/3856344/62042106-f1a1bc80-b205-11e9-9926-7979fc4b5f30.png)
![image](https://user-images.githubusercontent.com/3856344/62042124-02eac900-b206-11e9-8561-631c060f52da.png)

**Comment by uslss** [comment]
seems that issue is already fixed.
Ticket closed
![image](https://user-images.githubusercontent.com/31996417/74144352-a3866080-4c0d-11ea-8aef-b4db05a9d621.png)
