### ISSUE TITLE
Autocomplete should work using default database w/o requiring FQ descriptors.

### ISSUE THREAD

**Issue by vstokesjr** [dbeaver/dbeaver#3086]
dbeaver Version: 4.3.5
OS Version: Ubuntu 16.04.03 x64 LTS
SQL Server: MS SQL Server 2008 SP1

The autocomplete should work using the default database without requiring the user to provide fully qualified descriptors. In other words, I should be able to do:

```
SELECT
  table.ab<column hint pop-up>
FROM ...
```
and not be required to do

```
SELECT
  schema.dbo.table.ab<column hint pop-up>
FROM ...
```

**Comment by jim256** [comment]
This would be GREAT. Removes half the benefit of autocomplete if I still have to type that much to get to the hint.

**Comment by uslss** [comment]
it is already implemented.
Ticket closed
