### ISSUE TITLE
Feature Request: format elapsed time for running queries

### ISSUE THREAD

**Issue by jdefontes** [dbeaver/dbeaver#3087]
It would be nice if the elapsed time displayed for running queries was formatted as HH:MM:SS instead of just displaying seconds:

![dbeaver](https://user-images.githubusercontent.com/74665/36989585-18343b80-2070-11e8-8fdd-552d6286d1d7.png)

I use dbeaver for a lot of long-running analytics queries and this would be useful for monitoring run times.

**Comment by IdaStats** [comment]
Yes, second this request. I don't want to have to keep dividing by 60 to get a real sense of time elapsed.

Thanks.

**Comment by Manja-S** [comment]
I second this request as well.

**Comment by micheal-icp** [comment]
@serge-rider Is there any updates you could provide related this feature request? I believe this would be something quick and easy to provide. Any reason why this couldn't or wouldn't be implemented?

**Comment by E1izabeth** [comment]
You can vote for the issue with 👍 under the issue description to promote it to a higher priority.
