### ISSUE TITLE
Null variable in scripts

### ISSUE THREAD

**Issue by sae-gfc** [dbeaver/dbeaver#3088]
Hello,
When using variables in script like
```
WHERE name LIKE '${Name}%'
   and surname LIKE ' ${Surname}%'
```
When Name = 'J' and Surname='DO' it's work I got John DOE
but when I search without the name (Name = '') and Surname='DO' I've nothing because the real request to the Database is
`WHERE name LIKE 'Null%'`

![image](https://user-images.githubusercontent.com/33481143/37017661-da485278-212a-11e8-9ebf-33a20426ffaf.png)

I see the request https://github.com/dbeaver/dbeaver/issues/1660 where it ask to pass Null value when parameter is empty.

If default values for variables ${myVar|DefaultValue} will be implemented, it is possible to define no DefaultValue as empty ?

Ubuntu 17.10 - IBM DB2 - Dbeaver 4.3.5 and 5.0
Thanks

**Comment by sae-gfc** [comment]
Hello,
A temporary solution is to write LIKE '${Name}' in script and in the value of Name to write %  .

**Comment by serge-rider** [comment]
You can just remove quotes in your query:
```sql
WHERE name LIKE ${Name}%
   and surname LIKE  ${Surname}%
```
To set some not-null value just specify it with quotes in parameters binding dialog. If you need NULL - leave it empty.

Note: Some databases will fail processing expression 'LIKE NULL'. As they may support only `IS NULL` expression.
