### ISSUE TITLE
Program crash when specific action in "Bind parameter" window

### ISSUE THREAD

**Issue by sae-gfc** [dbeaver/dbeaver#3089]
Hello
When requested for Value, when in the area to insert a Value, if I Right Click the software is freezing.
I just use :param not the variable syntax ${}

Before
![image](https://user-images.githubusercontent.com/33481143/37019107-66a63be0-2130-11e8-8fc3-8f52c2854fd4.png)

After a Right Click in the Value Area
![image](https://user-images.githubusercontent.com/33481143/37019137-91878bac-2130-11e8-842b-cc05205363bc.png)
Unable to click anywhere (Value, Cancel, OK).

Ubuntu 17.10 - Dbeaver 4.3.5 and 5.0
Thanks.

**Comment by aranteslucas10** [comment]
Same here.
Linux Mint 18.2 Sonya - Dbeaver 5.0.4

**Comment by uslss** [comment]
hi @sae-gfc , is issue still actual for you in recent version?

**Comment by uslss** [comment]
there is no update on ticket for a long time. Ticket closed.
if issue is still actual - feel free to reopen the ticket.
