### ISSUE TITLE
Postgres feature request

### ISSUE THREAD

**Issue by gvaleika** [dbeaver/dbeaver#3090]
What is purpose for schema selection of posgresql connection?

SQL commands in pg are run using the schema search path managed by search_path:

https://www.postgresql.org/docs/current/static/runtime-config-client.html

Instead of this it would be very useful feature possibility to change PG connection dabatase (as in dbeaver SQL Server dialect).

Best regards,

Gražvydas

**Comment by serge-rider** [comment]
Schema selection chages search_path.
It is possible to change database (just enable "Show non-default databases" and "Switch default database on access" option on connection props dialog).

**Comment by gvaleika** [comment]
Thanks,

I see. Changing active object in Database Navigator works, but is little
bit surprising.

To me DB selection in PG is much more similar to SQL server style than
Oracle style schema selection.

Other things:
- PG search path can contain more than one schema in specified order
- can be changed by SQL script command: set search_path=information_schema;

DBeaver shema selection control can't do first and gets out of sync in
second case. It would be much more streamlined experience to select database
there.

G.

**Comment by serge-rider** [comment]
In PostgreSQL each database requires separate connection. 
This makes PG databases very different from SQL Server/MySQL databases or Oracle/DB2 schemas.

Yes, DBeaver doesn't use ability to add multiple schemas in search path. It is a kind of limitation to make PG UI consistent with other databases.
