### ISSUE TITLE
Link folder is deleting folder in Windows

### ISSUE THREAD

**Issue by marcinhom** [dbeaver/dbeaver#3092]
Hi amazing guys,

I Have a Feature Request to share with you..

In a version 4.3.2, and all off old versions when you link a folder to see scripts you can't unlink... and... when you delete the 'link' the folder and all content is also delete from Windows.

Can you please check to include a feature to unlink folder?

Best regards,

Marcio
Database: Oracle
Country: Brazil

**Comment by ruspl-afed** [comment]
The Eclipse platform contract is:

> 	 Deleting a linked resource does not delete its contents from the file system,
	 iit just removes that resource and its children from the workspace.  Deleting
	 children of linked resources does remove the contents from the file system.
	 
http://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fcore%2Fresources%2FIResource.html

So it is not clear what is requested,
