### ISSUE TITLE
Cannot delete or update rows in grid in DB2 iSeries/AS 400

### ISSUE THREAD

**Issue by carlosherranz** [dbeaver/dbeaver#3093]
Sometimes If I perform a select, and then I press the del key on to a row, or I try to change any field when I click on save button in order to confirm the changes, I get the message: "Can't detect source entity"
and then I get a second message: Error saving changes in database Reason: "No unique identifier defined"

**Comment by carlosherranz** [comment]
I think that is not the problem. Sometimes it works fine (without error) and sometimes It does'nt, updating or deleting rows on the same table,

**Comment by uslss** [comment]
is it still actual?

**Comment by carlosherranz** [comment]
Certainly from long time ago is not happen, perhaps is been solved
