### ISSUE TITLE
Query not executing after upgrade to 5.0 

### ISSUE THREAD

**Issue by kalgally** [dbeaver/dbeaver#3096]
Hi Team, 

I have upgraded to latest version 5.0 yesterday and after that all the queries taking more time and not getting result.  when i try to access from Other tool its working fine, so there is no issue with database. Is there a way I can move back to older version?

Thanks 
K

**Comment by serge-rider** [comment]
Sorry for so late reply.
You always can get older version from archive (https://dbeaver.jkiss.org/files/)
But your issue looks like some DBeaver installation corruption. You could try to remove previous version completely and reinstall 5.x.
