### ISSUE TITLE
Procedures with same name and different variables are treated as the same

### ISSUE THREAD

**Issue by icaptnbob** [dbeaver/dbeaver#3097]
DBeaver doesn't show the correct procedure details when there are more than one procedure with the same name but different variables: E.g. two functions getdimcells() and getdimcells(name) are defined. 
This is in a Postgres database, using the General Postgres driver supplied with DBeaver.

In DBeaver:
1. The procedure tree list shows two getdimcells entries, but both without the variable names.
![image](https://user-images.githubusercontent.com/16313976/37059707-f9933b84-21f2-11e8-8211-19bda35f1d52.png)

2. When double-clicking on each entry, only one of the definitions are shown, and the same one each time, getdimcells(name) in my case.
![image](https://user-images.githubusercontent.com/16313976/37059760-1f9cd8ee-21f3-11e8-8990-13727d270137.png)
![image](https://user-images.githubusercontent.com/16313976/37059780-2cb456ce-21f3-11e8-9b1c-886b82294add.png)

3. The same happens when ctrl-click on the code select * from getdimcells(name), I am shown the code for getdimcells() not getdimcells(name). When I hover over the function, I am shown getdimcells twice, but irrespective of which one I choose, I'm shown the code for getdimcells().

For reference, these show correctly in SQL Workbench and PGadmin as the two entries with the variable definitions. I.e. it's not a problem with the database.
From SQL Workbench
![image](https://user-images.githubusercontent.com/16313976/37059852-5b9a5ed4-21f3-11e8-9221-5ef8562471ae.png)

**Comment by uslss** [comment]
case 2 is still actual

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/81275853-ec0db880-905a-11ea-804f-24e6c8728cd4.png)
