### ISSUE TITLE
impala error line number not matching actual line number

### ISSUE THREAD

**Issue by chrisdabel** [dbeaver/dbeaver#3098]
Impala errors that contain line numbers do not match the actual line number of the referenced error.

Is it a problem with how the line feed and/or carriage returns are being read?

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on the issue for a long time
additional info is needed to reproduce an issue.
ticket will be closed. feel free to reopen an issue and add info that could help to investigate it.
