### ISSUE TITLE
Exporting a diagram to an image: the image is cropped

### ISSUE THREAD

**Issue by electrotype** [dbeaver/dbeaver#3099]
Using Dbeaver 5.0.0 Community edition, on Windows 10. When I export  a Diagram that is bigger than a single screen, the image is cropped. It's the same with `png`, `gif` and `bmp`.

![](https://i.imgur.com/5Zm0aKx.png)

Is that a known issue?

Thanks a lot!

**Comment by serge-rider** [comment]
I can't reproduce that. 
Are there any errors/warnings in Error Log view?

**Comment by electrotype** [comment]
@serge-rider Thanks for the reply. There are no errors in the Error Log view.

Here's a video of the issue : https://youtu.be/PN8qRCMpY70

**Comment by electrotype** [comment]
By the way, I did ty in a linux Ubuntu VM, simply to be able to export the diagram properly, and I did get exactly the same result! The image is still truncated...

**Comment by serge-rider** [comment]
That's weird.  
- Does this happen with any diagrams? 
- Did you try to export custom diagrams?
- Did you try to export in SVG format?

**Comment by electrotype** [comment]
Thanks for the support @serge-rider !

It is a custom diagram.

I did try SVG and the result is also truncated! But less... I can see more of the diagram.

I'm pretty sure this have to do with the fact that I moved some of the tables higher than the default top. This is what I mean by that : 

https://youtu.be/wGp5usKzRig

If it could help, let me know if you want me to send you some files (privately).

**Comment by serge-rider** [comment]
I've reproduced that, thanks for details. Your guess was correct.

**Comment by serge-rider** [comment]
I've published EA version (https://dbeaver.jkiss.org/files/ea/) - please check ERD export.

**Comment by electrotype** [comment]
Almost! :-)

But the image is still truncated on the right side! I may have dragged tables after the default righ side too, the same way I did to the top!

The table on the right is named "individuals_phones" (I added blur to the other part of the image):

![](https://i.imgur.com/3JOZszo.gif)

**Comment by serge-rider** [comment]
I can't reproduce that again. Moreover there should be some thin transparent border around the diagram.
Could you try to make a diagram from some system views/tables for MySQL/PostgreSQL or Oracle and send it here or on serge@jkiss.org?

**Comment by electrotype** [comment]
Done, I sent you the DBeaver project and a database dump. Sadly, this is for SQL Server.

**Comment by electrotype** [comment]
Now works perfectly using https://dbeaver.jkiss.org/files/ea/

Thanks a lot @serge-rider !

**Comment by uslss** [comment]
Not reproduced on 6.0.2

**Comment by ajperez81** [comment]
> Not reproduced on 6.0.2

I'm having the same issue, and I'm running v6.0.2... The PNG image gets cropped on the bottom and right sides.

**Comment by dgilman** [comment]
Having the same issue with 6.0.4. To get around the cropping you need to make sure your ERD boxes are aligned against the left and top edges of the ERD space.

Sounds like the bug is that it calculates the dimensions of just the ERD (without any spacing you may have put between the ERD and the left and top edges), renders a PNG with those spacing-less dimensions but doesn't realign the ERD in the PNG space to the left and top edges resulting in parts of the ERD getting cropped off along the right and bottom edges.

**Comment by audiBookning** [comment]
> make sure your ERD boxes are aligned against the left and top edges of the ERD space

@dgilman's solution worked for me. Thanks.

**Comment by harveymoons** [comment]
Thank for help

I solved this issue by @dgilman's solution

**Comment by oorigunwa** [comment]
Thanks @dgilman

**Comment by williamszostak** [comment]
I ran into this same issue in version 7.3.2.  Thanks for the work-around, @dgilman - it still worked for me.
