### ISSUE TITLE
How can i remove a bold for keywords?

### ISSUE THREAD

**Issue by HajongJeong** [dbeaver/dbeaver#3100]
I want to remove bold types in query editor. 
How can i set it?

**Comment by ashleylester** [comment]
I'm having the same issue.

**Comment by HajongJeong** [comment]
I did not find a answer. so i decided to use other solution. 

Use a fixed font for developer. (ex. Consolas)

**Comment by serge-rider** [comment]
This option will be added in 5.0.4:
![image](https://user-images.githubusercontent.com/6398845/39400127-2f2d5e3c-4b33-11e8-8956-cd7b6096743a.png)
