### ISSUE TITLE
On opening MS SQL Server view: 'There is no text for object'

### ISSUE THREAD

**Issue by erikolai** [dbeaver/dbeaver#3101]
Whenever we open a view against MS SQL Server, we get the attached error message. It says that there's "no text for the object". The details say exactly the same. When we click OK, everything works fine.

Do you know what causes the error, and what might be done to resolve it?

![skjermbilde](https://user-images.githubusercontent.com/37139472/37083527-0f3b4f06-21f0-11e8-9a4b-9d8d93b3edad.PNG)

**Comment by uslss** [comment]
Issue isn't reproducible.
Ticket closed
