### ISSUE TITLE
Feature request: Table view column sorting

### ISSUE THREAD

**Issue by raqua** [dbeaver/dbeaver#3102]
When I open table view (using Oracle, but I believe this is universal also for other databases) on Properties tab I can see columns. These are sorted alphabetically by column name. I would like to have this sorted by column number as that is the same order my result sets come in. The current way is confusing. 
I have not found a configuration option to set this. I would appreciate if this option was added. 
Thanks.

**Comment by serge-rider** [comment]
By default columns are sorted by number.
Perhaps you set option "Order elements alphabetically" in preferences (Preferences->Database->Navigator)?

**Comment by raqua** [comment]
Yes, that has done it. Thank you. It is a bit confusing in my opinion, because Navigator suggests to me "Database Navigator" that is on the left side of screen.
