### ISSUE TITLE
Bug: Strange BEGIN END behavior

### ISSUE THREAD

**Issue by raqua** [dbeaver/dbeaver#3103]
I am using Oracle PL/SQL.
When I type something like this:

PROCEDURE X IS
BEGIN <enter>
then END is added, but no ";" behind it, so I still have to navigate at the end of "END" and add it. 
It would be nice if this is done automatically, otherwise it is not much help. I keep having this forgotten ";" all the time.

When I create a method like this:
PROCEDURE X IS
BEGIN
NULL;
END;

.. and then want to add some more code at the beginning, I usually go to BEGIN line and press enter and then start typing. However, I end up with code like this: 
PROCEDURE X IS
BEGIN

END
NULL;
END;

This is obviously nonsense and it would be nice if the END is not added again if there is one already. 
Thanks.

**Comment by serge-rider** [comment]
This is a bug in SQL editor auto-indent, thanks for report.
