### ISSUE TITLE
Feature request: Simple code completion ala Atom editor

### ISSUE THREAD

**Issue by raqua** [dbeaver/dbeaver#3104]
When writing PL/SQL procedures, there is lack of code completion. I understand that it is probably rather complex to support all the specifics of all DBs, but Atom editor has rather simple and very effective approach to solving this. 
It remembers everything typed already on current screen and then after 3 characters typed it starts to offer these remembered words as code completion. I believe this is quite simple approach to implement and works surprisingly well. With this approach code completion works also for custom variable names etc.
Thanks.

**Comment by E1izabeth** [comment]
It has been implemented.
