### ISSUE TITLE
Clickhouse: problem counting rows in tables

### ISSUE THREAD

**Issue by stef1409** [dbeaver/dbeaver#3105]
Hello,
I use DBeaver for the connection to Clickhouse server. I found a problem (from DBeaver version 4.3 and also in the last version) when I count rows in a table: the result is wrong. For example, if I create a table (with engine=Log) and a view from the same table and with the same constraints and then I count the number of rows, the result from the view is right, while the result from the table is wrong.
Can anyone help me?

Thank you

**Comment by serge-rider** [comment]
Basically DBeaver counts row number by executing query `SELECT count(*) FROM TableName`.
You can view actual query in Query Manager view (you will need to enable all query types in QM prefs).
Perhaps this is somehow related to Clickhouse specific.

Could you check is row count query correct?

**Comment by stef1409** [comment]
I will try to explain the problem in a better way... If I execute the query "select count (*) from TableName" the result is wrong. If I create a view instead of a table and I execute "select count (*) from ViewName" the result is right. This problem doesn't happen with other server for example MySQL, but only with Clickhouse.

**Comment by serge-rider** [comment]
Well, this seems to be Clickhouse server issue, not DBeaver.

**Comment by stef1409** [comment]
the problem happens only from Dbeaver 4.3. With previous versions there wasn't any problem.

**Comment by serge-rider** [comment]
Maybe Clickhouse driver version matters? You can try to downgrade it in driver properties dialog (click Download/Upgrade->click on version number)

I don't see how DBeaver can be involved if SELECT COUNT query returns wrong results. DBEaver doesn't perform any results post-processing.
BTW what do you mean under "wrong"?
