### ISSUE TITLE
Feature request: Firebird 3.x support to view SQL user functions

### ISSUE THREAD

**Issue by stone977a** [dbeaver/dbeaver#3106]
Hi, in FB 3.x user can now create function (like MSSQL), but there is no way to view or edit or even create function in DBeaver. Is this planned for future?

Thanks and best regards, Tone

**Comment by LonwoLonwo** [comment]
Functions with parameters are readable in DBeaver 21.0.0
Functions DDL, ability to drop/edit function/procedure via UI implemented in scope with https://github.com/dbeaver/dbeaver/issues/10872
Will be available [here](https://dbeaver.io/) at 2021-03-22

**Comment by uslss** [comment]
#14225
