### ISSUE TITLE
CC Can't support export xls?

### ISSUE THREAD

**Issue by bouyeijiang** [dbeaver/dbeaver#3109]
export xls not supported for cc

**Comment by serge-rider** [comment]
What is CC?
Do you mean CE (community edition)?
It supports export in XLS but you need to install Office support as a separate extension (free - https://github.com/dbeaver/dbeaver/wiki/Optional-extensions).

**Comment by bouyeijiang** [comment]
yeah,
but exception error
An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
Error reading signed content.
Exception in opening zip file: D:\Program Files (x86)\DBeaver\plugins\org.jkiss.bundle.apache.poi_3.16.0

**Comment by serge-rider** [comment]
Do you use IBM Java?
Could you try to download Windows installer (with bundled Java)?

**Comment by jerherder** [comment]
hello

for install the office extension without internet connection, you should download all the files at this adress https://dbeaver.jkiss.org/update/office/latest/ and reproduce the structure of folder in a specific folder :+1: 

1 folder with the files .jar and . xml and .xz
and in this folder add the folder features and plugins with the specific files.

after in dbeaver, do this : 

help
install new softaware
add
type a name and click on local and find the folder with all the files
choose office extension
next 
next 
finish

be careful, you should have the administrator privileges on the folder dbeaver

**Comment by serge-rider** [comment]
Or you can just download EE version (which bundled wit all DBeaver extensions including Office).

**Comment by bouyeijiang** [comment]
EE version need buy it? hwo long can used?

**Comment by tati-kru** [comment]
Yes, DBeaver EE is a commercial product. The license for DBeaver EE is perpetual but includes only one year of support and upgrades.
