### ISSUE TITLE
How to filter by more than one value when clicking on the filter icon in the column header

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#3110]
DBeaver - **Version 4.3.5 CE**
Operating System: **Windows 7** / **Windows 8.1**

If I click on the filter icon in a column header, a dialog is shown with something like:

```
+--------------------------------+
| Filter by column value         |
+--------------------------------+
| Choose value(s) to filter by:  |
+--------------------------------+
| 1                              |
| 2                              |
| 3                              |
+--------------------------------+
```

I understand how to select one value (click, enter, etc.). But how do I select more than one value ?

**Comment by p91paul** [comment]
right click on the cell, you'll have a filter option, select value in.. and a popup will allow you to select multiple values.
F11 is an handy shortcut to get the filter dropdown after clicking on a cell
