### ISSUE TITLE
SQL files auto-delete configuration enhancement

### ISSUE THREAD

**Issue by edmiller3** [dbeaver/dbeaver#3113]
This is related to the enhancement (#962 Enhancement - Do not automatically delete empty files on closing, Nov 2016).  I am currently using version 4.3.4 Feb 4 2018 on Windows 10.  It appears that perhaps the enhancement works a little too well; while it added the option not to delete empty files on close, now it appears to me that no matter what you choose in the preferences, it will never delete an empty file.

How I tested this:
When I open a New SQL Editor (Ctrl+F3), type "test" into it, save it (Ctrl-S), then delete the word "test" and save the empty document (Ctrl-S), then when close this empty document, the script still exists in my project.  If I then close the application completely and re-open it, the script still exists in my project.  This is regardless of whether the script is open in the editor when I close the application.  I wasn't clear if "delete on close" meant on close of the file, or on close of the application.  It doesn't appear to work either way.

I have checked both my general and connection-specific SQL Editor Settings, and I have the option checked to delete empty files (see attachment).

![image](https://user-images.githubusercontent.com/37191503/37170866-f0737252-22c0-11e8-8d5b-0ffd187d22ed.png)

**Comment by edmiller3** [comment]
P.S. I will download 5.x now to see if it works correctly there, and if so I will report it here so this issue can be documented but marked closed.

**Comment by serge-rider** [comment]
@edmiller3 DBeaver deletes empty file only if didn't have any contents. I.e. if you just open it, execute a few queries and close it. Otherwise DBeaver won't delete it because this script has history which can be used.

You can see local history by clicking Team->Show Local History in editor context menu.

PS Maybe we need another config option "Force empty scripts delete" which will ignore script history.

**Comment by edmiller3** [comment]
I understand now what you're saying.  It's beginning to sound like the Delete Empty Scripts checkbox might be better as a dropdown with choices of behavior like Delete (No Text Present), Delete (No Text or History Present), Don't Delete.  I'm not sure that's the best label for it, or the best description of options or whatnot.  I'll look at the history of the file I was testing.

**Comment by serge-rider** [comment]
Sounds reasonable.
I'll turn this into FR.

**Comment by edmiller3** [comment]
Serge, thank you for your efforts.  This is a great product and I will be buying the enterprise version to show my support for this project.
