### ISSUE TITLE
No show all tables - Informix

### ISSUE THREAD

**Issue by nemdaz** [dbeaver/dbeaver#3114]
- The connection is successful.
- But no show all tables on Informix database.
- See the image:

![08-03-2018 04-17-07 p-m-](https://user-images.githubusercontent.com/6315069/37177515-b2538cbe-22ed-11e8-8c39-9186b38af7a6.png)

**Comment by nopris** [comment]
196/5000
Neither do I see all the tables in some databases (not all of them). I think I can only see the ones I'm the owner, not those that I have public access, as I would like.
I have no errors in the log file.

**Comment by nopris** [comment]
Driver: ifxjdbc.jar
IBM Informix Dynamic Server Version 11.50.FC3

**Comment by nopris** [comment]
I can acces invisible tables only in result set of a Query over this tables.
But in the result set of this tables I can not make changes. I can make changes in this tables only with SQL phrases (insert, update, delete).

**Comment by ceinmart** [comment]
Just add a note about this defect. 
With the last drive version, 4.10.JC12, it also not showing the synonyms for each owner.

**Comment by brian-hughes** [comment]
If you can help point me to the query or API call dbeaver is using, I can check what might be going wrong with the Informix JDBC driver

**Comment by ceinmart** [comment]
> If you can help point me to the query or API call dbeaver is using, I can check what might be going wrong with the Informix JDBC driver

About the missing synonyms, I don't know what is implemented into the dbeaver, I think isn't.

But, here is the tables to get the synonyms information in the informix : 
For each catalog have two tables where you can get information : systables (tabtype = 'P','S') and syssyntables

- systables
 [references here ](https://www.ibm.com/support/knowledgecenter/en/SSGU8G_12.1.0/com.ibm.sqlr.doc/ids_sqr_072.htm) 
- syssyntable
  [references here](https://www.ibm.com/support/knowledgecenter/en/SSGU8G_12.1.0/com.ibm.sqlr.doc/ids_sqr_069.htm)

```sql
select t.tabid, t.owner, t.tabname, t.created, t.tabtype
     , decode(t.tabtype,'S','Public','P','Private')
     , s.dbname||decode(nvl(s.servername,'-'),'-','','@'||s.servername)||':'||trim(s.owner)||'.'||s.tabname as remote_table
     , t2.tabname as local_table
from systables t, syssyntable s, outer systables t2 
where t.tabtype in ('P','S') 
  and s.tabid = t.tabid 
  and t2.tabid = s.btabid
order by 5 ;
`

Thru JDBC driver I don't know how works. I looked at Informix JDBC manual and there is no reference about how retrieve the objects , so I believe this is some JDBC standard functions.
I'm not a developer , then I cann't help with this kind of details...

**Comment by ceinmart** [comment]
About the missing tables reported by @nemdaz , I do not experience this issue with dbeaver 6.0 and Informix JDBC 4.10.JC12 .

**Comment by brian-hughes** [comment]
It should be an API they call.  I can dig for it.  Just seeing if anyone knew which one off hand was being used here and the parameters they call.  I do development for the Informix JDBC driver now.  So just looking to make tools like this work a little smoother when I can :)

**Comment by nemdaz** [comment]
dbeaver groups the tables by user, so it does not show all of them. Aqua displays all the tables without grouping by user.
