### ISSUE TITLE
Previous/Next Word skips periods?

### ISSUE THREAD

**Issue by traviscook21** [dbeaver/dbeaver#3115]
If I use the keyboard shortcut for "Previous Word" (defaults to Alt+Left Arrow) from this location:

![image](https://user-images.githubusercontent.com/3671851/37177682-ff738d5a-22d4-11e8-9010-00588e24d776.png)

I would expect to end up here:

![image](https://user-images.githubusercontent.com/3671851/37177725-1f6bf1e2-22d5-11e8-933b-62571ee13d01.png)

but instead I end up here:

![image](https://user-images.githubusercontent.com/3671851/37177737-2aab9a8a-22d5-11e8-9aa3-6e1fccbfac1c.png)

It seems that DBeaver is using a space character defined what the next word is instead of also including things like periods.  This is different than behavior that I've seen in SQL Server Management Studio, IntelliJ, and even in browsers like Chrome.  Is this something that is configurable or is this a bug that can be fixed?

**Comment by traviscook21** [comment]
This is a question but I can't figure out how to tag it as such.  Is this a bug?  Is this a future improvement that can be made?  Is there a setting I can switch to fix this behavior?

**Comment by Neospiro** [comment]
I have the exact opposite problem :
On Windows 7 64b, when I use my "Previous word" shortcut in DBEAVER 5.2.5.201811181655, it stop on ".", and it also stop on "_".
As I have many "_" in tables names and columns names, it is a big issue for me.

I would like "Previous word" to stop on characters not prevent in regex "\w" selector.

> A word character is a character from a-z, A-Z, 0-9, including the _ (underscore) character.

Thanks

**Comment by uslss** [comment]
Seems that the main issue is solved. The ticket will be closed.
@Neospiro you could open new ticket if problem is still actual for you.
