### ISSUE TITLE
Autocomplete on COLUMNS sometimes not working

### ISSUE THREAD

**Issue by tonjo** [dbeaver/dbeaver#3117]
Ubuntu 16.04, Dbeaver version 5.0.0 but also 4.3.5

Writing something like `select col<...wait for suggestions ...> from tableA`, 
I cans see hints on columns taken from tableA.
Sometimes, with a long-named column, it does not work anymore and shows always table names.

**Comment by uslss** [comment]
hi @tonjo , is issue still actual for you on recent version?

**Comment by uslss** [comment]
there is no update on issue for a long time. ticket closed.
