### ISSUE TITLE
default value is missing in generated DDL for PostgreSQL in primary key field

### ISSUE THREAD

**Issue by GiantCrocodile** [dbeaver/dbeaver#3120]
Generated DDL for PostgreSQl is missing the default value attributes for primary key fields:

generated: `id bigserial NOT NUL,`
missing: default value `nextval('note_id_seq'::regclass)`

**Comment by lemon-juice** [comment]
I think the generated DDL is correct. `bigserial` means:
 `bigint NOT NULL DEFAULT nextval('note_id_seq'::regclass)`

In other words, bigserial creates both the sequence and the default value so there is no need to specify it. Even NOT NULL is not necessary and it could be just:

`id bigserial,
...`

**Comment by GiantCrocodile** [comment]
Ah, I was confused and read `bigint` and not `bigserial`. First one is obviously wrong but `bigserial` sounds indeed right. I will try to create a table with that and see if the result is correct. Thanks for your remark @lemon-juice!

**Comment by GiantCrocodile** [comment]
I close this issue because @lemon-juice was right and thus this issue is invalid.
