### ISSUE TITLE
Could not download postgres driver

### ISSUE THREAD

**Issue by benyanke** [dbeaver/dbeaver#3121]
Is this a known issue? Or is this a temporary outage?

![image](https://user-images.githubusercontent.com/4274911/37223425-13249e54-2396-11e8-8ec7-c6abf70a8e25.png)

https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.0.jre7/postgresql-42.2.0.jar

**Comment by serge-rider** [comment]
I think it is some kind of glitch. Right now it works fine for me..

**Comment by benyanke** [comment]
Just doing housecleaning - haven't had this issue since, evidently a CDN issue or something.
