### ISSUE TITLE
5.0 Version Moving keys issue

### ISSUE THREAD

**Issue by marcinhom** [dbeaver/dbeaver#3122]
Hi guys,

I just downloaded the last version, and I got a issue with keys navigation.

So... let me try to explain... when you run a query and got a result set... and you try to use CTRL+left or right arrows, the screen apply these commands into result set, however I was put the cursor in the SQL query not in result set. 

Then, isn't possible to use CTRL + LEFT key to jump over the words in a query because the screen redirect this command to result set.

Best Regards,
Marcio Cunha
Brazil.

**Comment by marcinhom** [comment]
UP.

**Comment by serge-rider** [comment]
Can't reproduce.
What is your OS?

**Comment by DragonStorm97** [comment]
I have the same problem.
DBeaver 5.0.0
Windows 10

**Comment by serge-rider** [comment]
Shortcuts for results navigation were changed to <kbd>CTRL+ALT+LEFT</kbd> and <kbd>CTRL+ALT+RIGHT</kbd>
