### ISSUE TITLE
Generate SQL - unwrap

### ISSUE THREAD

**Issue by sfkristof** [dbeaver/dbeaver#3124]
It would be greate to export SQL statements in 1 line without line wraping:
INSERT INTO table (a, b, c) VALUES (1, 2, 3);
INSERT INTO table (a, b, c) VALUES (4, 5, 6);
...

**Comment by GiantCrocodile** [comment]
This should be an optional feature then.

**Comment by sfkristof** [comment]
Yes, it would be great to have such an option.
With this (1 statement is 1 line) layout it's much easier to modify the generated script with a multiline editor like Notepad++ for example.

**Comment by lemon-juice** [comment]
I agree - 1 insert per line is much more readable and manageable than having it split in 3 lines. If some people prefer it in split form then this should be an option.

**Comment by serge-rider** [comment]
This is already supported.
Just set parameter "Data rows per statement" to 1.

**Comment by sfkristof** [comment]
Oh, I see it's only available from the <right click on table> / Export Table Data menu.
It would be great to have a similar option on the "Generate SQL" option as well,
because then the selected rows/columns are much easier to be given.

**Comment by lemon-juice** [comment]
Yes, "Generate SQL" option is very convenient and it would be great to have one-line inserts there.

Also, after adding rows to a table and pressing "Script" before saving it would also be good to have one-line inserts. It's strange but this script shows 2-line inserts now while "Generate SQL" creates 3-line inserts.

**Comment by serge-rider** [comment]
Ah, do you mean line feeds in INSERT queries? We could add special option for "compacting": queries.
That's easy to implement:
![image](https://user-images.githubusercontent.com/6398845/37547461-e2a2dc3a-2982-11e8-9a12-43ae65b930c4.png)

**Comment by serge-rider** [comment]
But this won't work in case of Script preview.

**Comment by sfkristof** [comment]
Cool, thanks Serge!

**Comment by lemon-juice** [comment]
Wonderful!
