### ISSUE TITLE
SSH tunnel with PPK key

### ISSUE THREAD

**Issue by sfkristof** [dbeaver/dbeaver#3125]
If I want to create a connection and using a PPK key file the connecting says:

Can't initialize tunnel
Cannot establish tunnel
Auth fail

Like explained here: https://github.com/dbeaver/dbeaver/issues/298

**Comment by sfkristof** [comment]
I read earlier somewhere that DBeaver can't use a PPK key and I have to convert it to some other type to make it work?
Is this true? Which type will work and how can I convert my PPK key file to this format?
I dont want to open a putty ssh tunnel if it's not neccesary. Thanks!

**Comment by sfkristof** [comment]
Ok, it's working now, I converted it to Open SSH key using puttygen and I set it up on the "SSH Tunnel" tab, using the "Authentication method" field with the "Public Key" value.

**Comment by davidlwillson** [comment]
It would be great if the error message could say something like, "couldn't load your private key", instead. Or, if DBeaver could support ppk format keys. That would be even better than a clearer error message.

Having to just memorize the fact that "ppk format" doesn't work and "the other format" does, is pretty unsatisfactory, at least for one of me.
