### ISSUE TITLE
Autocomplete without catalog

### ISSUE THREAD

**Issue by sfkristof** [dbeaver/dbeaver#3126]
If the DB and catalog is already selected when I use Ctrl+Space on the suggestion list there are not just the 
table names but even the catalog/schema which is annoying and makes harder to select the table wanted.

Config:
![db-ss2](https://user-images.githubusercontent.com/22003889/37244194-916ee2de-2485-11e8-9dd3-de4a317ff06f.PNG)

Example:
![db-ss](https://user-images.githubusercontent.com/22003889/37244178-5b23ee36-2485-11e8-9c33-8915e2ce8134.png)

**Comment by uslss** [comment]
already fixed
