### ISSUE TITLE
Tab navigation with custom keys

### ISSUE THREAD

**Issue by sfkristof** [dbeaver/dbeaver#3127]
I setup the keys: Ctrl+PageUp / PageDown like this:

![db-ss3](https://user-images.githubusercontent.com/22003889/37244224-ee6c3478-2485-11e8-8902-2c638be25aa1.PNG)

![db-ss4](https://user-images.githubusercontent.com/22003889/37244225-f1b5826a-2485-11e8-8e81-6eeedba41b70.PNG)

But it's not working: nothing happens when trying to navigate between the open scripts in the SQL editor.
(No other function uses these bindings.)

**Comment by serge-rider** [comment]
This is because <kbd>Ctrl+PageDown</kbd> and <kbd>Ctrl+PageUp</kbd> are reserved for sub tab navigation (you can see it in object editor).

**Comment by sfkristof** [comment]
Thanks Serge, I set it to Alt+Left and Alt+Right then.
