### ISSUE TITLE
[Feature Request] cycle(is_cycled) property is not show in sequence view.

### ISSUE THREAD

**Issue by joelkim** [dbeaver/dbeaver#3128]
`cycle`(`is_cycled`) property in sequence is shown in "data" tab, but not shown in "properties" tab.
Can I add this property to "properties" tab?

**Comment by serge-rider** [comment]
What is your database?

**Comment by joelkim** [comment]
I am using PostgreSQL.

**Comment by serge-rider** [comment]
You mean PostgreSQL 10?
Looks like they have redesigned sequences meta model there.

**Comment by joelkim** [comment]
Sorry for not being specific. 
I am using PostgreSQL 9.6.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9), 64-bit. 
Actually this is AWS RDS service.

**Comment by serge-rider** [comment]
Thanks for details.
Fix will be added in the next version
