### ISSUE TITLE
first query very slow

### ISSUE THREAD

**Issue by osvfr** [dbeaver/dbeaver#3129]
I realized this issue passing from the V7R1M0 version of the old AS400 to the V7R2M0 version of the new AS400. The version of DBeaver is irrelevant, now I installed 5.0.0. The first query I run takes about 50 seconds, the next ones are immediate. Some of my colleagues use Advanced Query Tool or Orbada and they do not happen. Do you have any suggestions ? Thanks.

**Comment by lucianoshl** [comment]
+1

**Comment by osvfr** [comment]
Installing last cumulative PTF package fix that issue
