### ISSUE TITLE
DB2: Alert with driver load

### ISSUE THREAD

**Issue by frankmusolf** [dbeaver/dbeaver#3130]
only on this way i can use dbeaver currently:
Open editor to disconnected DB2 (with configured driver) -> error dialog to download driver -> choosing abort -> connection is established

Regards
Frank

dbeaver 4.3.5

!SESSION 2018-03-01 13:38:06.516 -----------------------------------------------
eclipse.buildId=4.7.2.M20171130-0510
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -data E:\eclipse_workspaces\xxx

eclipse logfile
```
!ENTRY org.jkiss.dbeaver.model 4 0 2018-03-12 11:42:05.969
!MESSAGE Error loading artifact version POM: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

!ENTRY org.jkiss.dbeaver.model 2 0 2018-03-12 11:42:31.026
!MESSAGE SQL Warning (DataSource: XYZ (DB2); Code: -99999; State: 01H20): Extra connection property is ignored.

```

**Comment by titou10titou10** [comment]
Hi,
Some questions:
- What version of DB2? what "flavor" of the server (Linux, windows...)?
- What version of the Db2 driver are you using?
What kind of connection in DBEaver (DB2 LUW, DB2 x/OS...)?
Do you set extra parameters in the connection dialog?
What exactly happens when you try to connect via DBEaver?
Thanks
Denis

**Comment by frankmusolf** [comment]
DB2 driver is net.sf.jt400.jt400 version 8.5, no extra parameter

DB2 runs on AS400 with version V7R2

i start eclipse -> double click on DB2 connection in dbeaver -> user, password dialog -> press ok -> driver download dialog is open -> abort -> connection is established

regards
frank

**Comment by frankmusolf** [comment]
right mouse on connection->connect_user,password->dialog for driver is opening->select db2.driver8.5->press ok->connection ist not established

right mouse on connection->connect_user,password->dialog for driver is opening->select db2.driver8.5->press driver->press download->press abort->connection ist established

**Comment by frankmusolf** [comment]
Any news or questions for that? Select of driver8.5 is unnecessary. press download is enough.

right mouse on connection->connect_user,password->dialog for driver is opening->select db2.driver8.5->press ok->connection ist not established

right mouse on connection->connect_user,password->dialog for driver is opening->press download->press abort->connection ist established

**Comment by serge-rider** [comment]
I can't reproduce this behavior.
Maybe it is some kind of misconfiguration after series of DBeaver version upgrade.
Could you try to run DBeaver on some other machine?

**Comment by frankmusolf** [comment]
this behaviour i found only on my machine.
what can i do to clean my dbeaver installation?

**Comment by serge-rider** [comment]
You could try to reset workspace (https://github.com/dbeaver/dbeaver/wiki/Reset-workspace).
Firstly try to delete file `.dbeaver4\.metadata\.plugins\org.jkiss.dbeaver.core\drivers.xml ` and restart DBeaver.
