### ISSUE TITLE
error running new version 

### ISSUE THREAD

**Issue by tarkstar** [dbeaver/dbeaver#3131]
[1520884400379.log](https://github.com/dbeaver/dbeaver/files/1804350/1520884400379.log)

**Comment by serge-rider** [comment]
What type of distro do you use - installer or zip archive?
If you use zip archive - did you remove previous version completely?

**Comment by tarkstar** [comment]
I originally used installer.  I did remove all previous versions.

Scott B. Tarkowski
Vice President
Treasury Strategic Product Delivery
Technology
6023 Airport Rd
Oriskany, NY 13424
T 315 765 4479
M 315 335 6326
scott.tarkowski@bnymellon.com<mailto:scott.tarkowski@bnymellon.com>
www.bnymellon.com<http://www.bnymellon.com/>
This message is confidential

**Comment by serge-rider** [comment]
Error log says that some jars are missing. 
For instance `org.eclipse.jface` - although jar `org.eclipse.jface_3.13.2.v20171022-1656.jar` must be in `plugins` directory.
Maybe something went wrong during installation (e.g. DBeaver was running while you run an installer).
Could your try to reboot and reinstall DBeaver?

**Comment by tarkstar** [comment]
I was able to download the zip archive and run that way.

Scott B. Tarkowski
Vice President
Treasury Strategic Product Delivery
Technology
6023 Airport Rd
Oriskany, NY 13424
T 315 765 4479
M 315 335 6326
scott.tarkowski@bnymellon.com<mailto:scott.tarkowski@bnymellon.com>
www.bnymellon.com<http://www.bnymellon.com/>
This message is confidential

**Comment by serge-rider** [comment]
Great!
