### ISSUE TITLE
version 5.0 requires postgis drivers for postgres connection. Why?

### ISSUE THREAD

**Issue by jgomo3** [dbeaver/dbeaver#3132]
Just upgraded to 5.0 and for a new PostgreSQL connection is asking me to download the Postgis drivers (although I already had many PostgreSQL connections).

![postgispostgres](https://user-images.githubusercontent.com/1125678/37307146-ea4048ba-261c-11e8-876a-b7d6cbc1d2d5.png)

**Comment by serge-rider** [comment]
PostGIS is not required. It is just a part of default driver because GIS data types are widely used.
You can just ignore this dialog (or remove postgis jars from driver properties).
