### ISSUE TITLE
"All Obejcts Pattern" set to null but '%' is used in generic driver

### ISSUE THREAD

**Issue by aviv-jethro** [dbeaver/dbeaver#3133]
I've set "All Objects Pattern" to "null" in "Advanced parameters" tab of Driver Settings for a generic driver.
I was expecting JDBC sqlColumns() and sqlTables() to be passed null as the all objects pattern but the value being passed '%' 
running on v 5.0.0 but has been true for at least a 3 releases
windows 10 64bit

**Comment by serge-rider** [comment]
It is a bug in driver properties load.
Workaround: set property value to `null` manually (type it but not choose from drop-down list)

**Comment by aviv-jethro** [comment]
tx for quick response
but workaround does not fix for me

**Comment by serge-rider** [comment]
I'll publish EA version with this fix today evening

**Comment by serge-rider** [comment]
https://dbeaver.jkiss.org/files/ea/

**Comment by aviv-jethro** [comment]
tx. works. just had to reset the option to null in the driver dialog.
great work. super great responsiveness.
