### ISSUE TITLE
cannot install RPM package on fedora 27 using gui gnome Software

### ISSUE THREAD

**Issue by ahmed89albttashi** [dbeaver/dbeaver#3134]
Dear Team , 

I couldn't install dbeaver 5 on Fedora 27, I have already previous version without any issue.
![image](https://user-images.githubusercontent.com/6708191/37328811-e6c9b5e8-26b4-11e8-95a7-70339098b842.png)

![image](https://user-images.githubusercontent.com/6708191/37328819-edac3cdc-26b4-11e8-9354-9432e3e06f1f.png)

install it using cli : 

![image](https://user-images.githubusercontent.com/6708191/37330652-352c1f2c-26bb-11e8-9505-7017aa3c728c.png)

and work fine

**Comment by serge-rider** [comment]
Looks like you need to uninstall previous version manually before installing new one.

**Comment by dgjustice** [comment]
@ahmed89albttashi I ran into the same issue.  I had a hard time uninstalling the old version as well.  This worked for me: `rpm -ivh --replacepkgs --replacefiles /path/to/dbeaver-ce-5.0.1-stable.x86_64.rpm`

**Comment by ivanaugustobd** [comment]
Same here.. looks like the .rpm package for 5.x release is a "source" package, so despite the installation direct with `rpm`, it can't be installed trough a package manager :confused: 

![Print on Fedora 27](https://ibin.co/3wRVhbtB5DVy.png)

**Comment by guard43ru** [comment]
confirm bug,
dnf install ./dbeaver-ce-5.0.2-stable.x86_64.rpm 
Ошибка: RPM пакет с исходным кодом не будет установлен (dbeaver-ce-5.0.2-stable.src).

Translate:
Error: Will not install a source rpm package (dbeaver-ce-5.0.2-stable.src).

**Comment by nenadalm** [comment]
```shell
$ sudo dnf install ./dbeaver-ce-5.1.0-stable.x86_64.rpm
Error: Will not install a source rpm package (dbeaver-ce-5.1.0-stable.src).
```

environment:
```shell
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 28 (Twenty Eight)
Release:	28
Codename:	TwentyEight
```

**Comment by jonua** [comment]
on fedora 28 same mistake

**Comment by elken** [comment]
![image](https://user-images.githubusercontent.com/2872862/45921804-ad8eae80-beb4-11e8-8e8f-dd02b1f226a8.png)

The RPM built isn't valid. Will take a _quick_ look to see if I can create a valid one.

**Comment by tati-kru** [comment]
This has to work for DBeaver 6.2.

**Comment by ahmed89albttashi** [comment]
thanks for resolve. 

I forget about this issue because currently switched to flatpak package of dbeaver. 

it's wrapped by flathub maintainers. 
https://flathub.org/apps/details/io.dbeaver.DBeaverCommunity

I think it's will be better if it's prepared by this team directly for creditability(upstream) and distro-agnostic.
