### ISSUE TITLE
[Question] - Keyboard shortcut to access "Active Database" dropdown?

### ISSUE THREAD

**Issue by ryancabanas** [dbeaver/dbeaver#3137]
Hi,

Is there a keyboard shortcut (or a way to set one up) that will allow you to get to the "Active Datasource" dropdown so that you can quickly change that while working in your Query Editor window?

Thanks!

**Comment by serge-rider** [comment]
<kbd>CTRL+9</kbd> and <kbd>CTRL+0</kbd>

**Comment by ryancabanas** [comment]
Thanks!
