### ISSUE TITLE
Toolbar is ugly on Mac

### ISSUE THREAD

**Issue by timster** [dbeaver/dbeaver#3138]
The connection and database selectors in the toolbar are not aligned with the rest of the items on the toolbar:

![capture 2018-03-13 at 12 35 57 pm](https://user-images.githubusercontent.com/173666/37355926-405328c8-26bb-11e8-8a33-c3cf3da03b58.png)

I guess I would expect them to be the same height as the row count box next to them.

Is it supposed to be this way or is it possible to align them properly?

**Comment by serge-rider** [comment]
Agreed. See fix in the next version.

**Comment by timster** [comment]
You're awesome! Thanks for the quick fix.

**Comment by slokhorst** [comment]
Is this the same issue or should I open a new bug? (can't read the number of transactions and another icon is looking weird, on Linux)

![2018-03-18-161319_1479x162_scrot](https://user-images.githubusercontent.com/8083666/37567449-5d822394-2ac7-11e8-9bc6-a60388d43b0d.png)

**Comment by serge-rider** [comment]
@slokhorst This is definitely a different bug.
