### ISSUE TITLE
[Question] - Is there a way to open a new SQL Editor tab with the Results pane hidden, instead of showing?

### ISSUE THREAD

**Issue by ryancabanas** [dbeaver/dbeaver#3140]
Hi,

When I open a new SQL Editor tab, the Results pane in the bottom area is always visible.  I must press "Ctrl + 6" to close it.  Is there a setting somewhere I can change so that when I open a new SQL Editor tab, the Results pane is not showing in the bottom area by default?

Thanks!

**Comment by serge-rider** [comment]
No, but it sounds like a good configuration enhancement.

**Comment by ryancabanas** [comment]
Great!  Thanks!

**Comment by uslss** [comment]
already implemented
