### ISSUE TITLE
Windows 10 High DPI support

### ISSUE THREAD

**Issue by martingbrown** [dbeaver/dbeaver#3141]
I'm trying to use DBBeaver on a Surface Pro 3 which has a High DPI screen. While most of it looks ok, the tool bar buttons are extremely small.

**Comment by serge-rider** [comment]
Do you use any zoom?
Most of time I'm working on PC with 4k screen and zoom factor 175%, toolbar looks big enough.

If for some reason you don't want to use it you could try to increase scale factor only for DBeaver.
Add following to the end of dbeaver.ini:
```
-Dswt.autoScale=300
-Dswt.autoScale.method=nearest
```
Actual scale factor (300 in my case) depends on your machine. Try to set value from 150 to 500 to find the best value.

**Comment by martingbrown** [comment]
The Surface Pro 3 I use is FHD+ (2160x1440) and I run it on a scale factor of 150%. The screen is reasonably small (12") though. With those settings DBeaver mostly looks fine, it is just the tool bar buttons that are coming out about 3mm tall. As you suggested I set the autoScale value to 150 and that seems to be about right. Thanks for your help.

**Comment by dooferorg** [comment]
So where is this config.ini file located?

**Comment by dooferorg** [comment]
This doesn't seem to work on the latest version of DBeaver. After trying to find the location of dbeaver.ini I found it in C:\Program Files\DBeaver ... however adding those entries made the program unable to start 'Cannot initialize Java VM' .. any other suggestions?

**Comment by serge-rider** [comment]
DBeaver 5.x supports HighDPI monitors (on Windows and MacOS) without any configuration changes.
If it doesn't work in your case - please post some details.

**Comment by dooferorg** [comment]
![dbeaver_tiny](https://user-images.githubusercontent.com/4922046/44872477-a1bc1d80-ac63-11e8-904e-f7da38cb6e58.png)

Ah, sorry if I responded to the wrong issue. I saw the thing about buttons mentioned. I'm also running at 150% scaling (4k displays) and although the fonts are ok in the application the buttons are teeny-tiny and some controls seem cut-off.

**Comment by serge-rider** [comment]
Just in case - SWT scaling options described above (-Dswt.autoScale etc) are deprecated. Don't use them (I believe you don't).

I'm running Windows 10, 4k monitor and native (Windows) zoom factor 175 or 150. And everything (including toolbars) look fine.
Do you have any specific options or zoom configurations?

**Comment by dooferorg** [comment]
Good to know those are no longer supported options

I'm not sure what the difference may be. I selected to have Windows improve programs that don't scale well (so they're not fuzzy). I too am using 150% scaling. It's really just the size of the buttons that's the issue. I don't know if there's a (simple) way to increase the toolbutton size or toolbar height?

**Comment by serge-rider** [comment]
- What is your screen resolution?
- Could try some other zoom ratio? (125, 175, 200)?

**Comment by dooferorg** [comment]
It's 3840 x 2160.. 4k

**Comment by PachowStudios** [comment]
Also seeing the same issue as @dooferorg 

![image](https://user-images.githubusercontent.com/1417838/52440464-ce624400-2ae3-11e9-8812-620b47eb0f1b.png)

3840x2160 with 150% scaling

**Comment by vladeck** [comment]
This is still an issue with DBeaver 5.3.4 on Windows 10 x64 1809 and scaling of 150%.

**Comment by datauduong** [comment]
I am still having issue with DBeaver 5.3.5 on Windows 10 x64 Version 10.0.17763.316

![image](https://user-images.githubusercontent.com/2460101/53534748-460c1780-3b54-11e9-86d5-a6c973221c87.png)

![image](https://user-images.githubusercontent.com/2460101/53534827-879cc280-3b54-11e9-867a-cef5a55fbe51.png)

**Comment by endrigo** [comment]
I am still having issue with DBeaver 6.0.0 on Windows 10 x64 Version 1809 compilation 17763.379

![Captura](https://user-images.githubusercontent.com/2512290/54867785-2cc94600-4d63-11e9-9fcf-c76a34237396.JPG)

**Comment by romme** [comment]
I just 

> Just in case - SWT scaling options described above (-Dswt.autoScale etc) are deprecated. Don't use them (I believe you don't).
> 
> I'm running Windows 10, 4k monitor and native (Windows) zoom factor 175 or 150. And everything (including toolbars) look fine.
> Do you have any specific options or zoom configurations?

Without this deprecated option the icons don't get zoomed past somewhere around 200%. Setting -Dswt.autoScale=integer in dbeaver.ini made the icons big enough to use comfortably on a high dpi display.

**Comment by Xymanek** [comment]
Issue appears when using screens with different scaling values.

Scaled screen (all good):

![image](https://user-images.githubusercontent.com/2865341/92994494-46d08880-f503-11ea-8f94-897ab7f75a39.png)

Non-scaled (100% scaling) screen:

![image](https://user-images.githubusercontent.com/2865341/92994503-5b148580-f503-11ea-9f8d-7e17aa5c6c19.png)

Notice the difference between the window frame/header and the UI under it

Process explorer reports DBeaver as "System Aware" instead of "Per-Monitor Aware"

![image](https://user-images.githubusercontent.com/2865341/92994532-bf374980-f503-11ea-8513-190f00257332.png)

**Comment by Xymanek** [comment]
Note: when overriding the scaling to be done by `System (Enhanced)`

![image](https://user-images.githubusercontent.com/2865341/92994762-be071c00-f505-11ea-9d65-0fd228c8fd59.png)

DBeaver causes reproducible BSODs when using Shift+Win+arrow keys to move the window between scaled and non-scaled screens. Right before the BSOD a full redraw is happening with different UI elements slowly appearing

**Comment by wacher74** [comment]
> -Dswt.autoScale=300
Thank you very much, this ini settings saved my eyes from popping out :)

**Comment by cot2493** [comment]
> Note: when overriding the scaling to be done by `System (Enhanced)`
> 
> ![image](https://user-images.githubusercontent.com/2865341/92994762-be071c00-f505-11ea-9d65-0fd228c8fd59.png)
> 
> DBeaver causes reproducible BSODs when using Shift+Win+arrow keys to move the window ~between scaled and non-scaled screens~ from a scaled to a non-scaled screen. Right before the BSOD a full redraw is happening with different UI elements slowly appearing. Moving the window with a mouse doesn't seem to cause a BSOD, no matter how fast or slow I do it

 I had blurry/non-pixel perfect text and UI but this solved my issue perfectly. Thanks so much

**Comment by wiredmind** [comment]
This is still a problem in DBeaver version 7.3, both Enterprise and Community editions:
- Screen resolution: 3840x2160
- Scaling: 150%
- Operating System: Windows 10 20H2 (10.0.19042)

Fiddling with High DPI scaling override does correct the toolbar icon size, but the application UI becomes blurry. Setting `Dswt.autoScale` to match OS scaling corrects the problem

**Comment by pamxy** [comment]
> Do you use any zoom?
> Most of time I'm working on PC with 4k screen and zoom factor 175%, toolbar looks big enough.
> 
> If for some reason you don't want to use OS settings you could try to increase scale factor only for DBeaver.
> Add following to the end of dbeaver.ini:
> 
> ```
> -Dswt.autoScale=300
> -Dswt.autoScale.method=nearest
> ```
> 
> Actual scale factor (300 in my case) depends on your machine. Try to set value from 150 to 500 to find the best value.

Yes, thank you!

**Comment by b-hayes** [comment]
SHould probably re-open this and provide actual high DPI support without having to disable it in the application profile in windows and then edit an ini file to a fixed value.
The major flaw with this workaround is it doesn't help if you have many screens with different DPI/scales eg. I have 4k screen in the middle and 1440p screens on the sides. If I move dbeaver off my main screen to the side it then becomes gigantic.

If I don't use the workaround then the text is blurry when on my main 4k screen.

**Comment by nathan-alden-sr** [comment]
Yep. Scaling needs to be handled by the actual UI framework and the OS settings working in concert. Frameworks like WPF and UWP handle this kind of thing natively. Not sure if that's possible with whatever Java UI framework is in use here, but high DPI support is table stakes for modern Windows apps.

Think how all Electron apps can scale seamlessly (VS Code in particular).

Additionally, there are lots of UI elements that don't seem to scale with font size--notably buttons. Some of the UI buttons are absolutely _tiny_, even on a regular 1080p display. At 1440p they become nearly unclickable unless one has really good mouse skills (I happen to, but others don't). Some fonts don't seem to use the font settings at all (e.g., the toolbar labels, menu bar, and Database Navigator tree items).

Just now, I went through every font setting and increased every size by 2pt. This made it very obvious what parts of the UI were not scaling with the increased font sizes.

![image](https://user-images.githubusercontent.com/1189759/142291235-6e36f1f7-6025-4705-a446-c6f999162a33.png)

**Comment by wvolkov** [comment]
```
-Dswt.autoScale=150
-Dswt.autoScale.method=nearest
```
and `CTRL +` twice at code area made it much better at my Surface Pro 7+ device with 2736x1824 12" device

![image](https://github.com/dbeaver/dbeaver/assets/49549154/d84c9424-d64e-4b89-965c-b66de6e9b160)

**Comment by regs01** [comment]
Can't this be automated? dbeaver.ini gets reset every update.

There is a WinAPI function GetScaleFactorForMonitor
https://learn.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getscalefactorformonitor

**Comment by regisbsb** [comment]
-Dswt.enable.autoScale=true
-Dswt.autoScale=exact
-Dswt.autoScale.method=nearest

this is the best, as it adapts to the monitor it was launched.

https://stackoverflow.com/a/61546243
