### ISSUE TITLE
Not able to connect to SQL server database from DBeaver 4.3.5

### ISSUE THREAD

**Issue by rohit9771** [dbeaver/dbeaver#3143]
Hello Team,

I'm facing connection issue whereas my fellow associates are able to connect to MS SQL db thru Dbeaver.

I sense there is some firewall or something blocking my connection.

![dbissue11](https://user-images.githubusercontent.com/25564271/37389890-ecf14f4a-275d-11e8-8468-122710619698.png)

Any suggestion would be helpful.

Thanks.

**Comment by infectormp** [comment]
Can you connect to db without DBeaver

**Comment by serge-rider** [comment]
Do you use SSH tunnel or this is a direct conect?

**Comment by rohit9771** [comment]
Thanks for reply.

It was DNS issue. I flushed and then tried reconnecting, it worked.
