### ISSUE TITLE
Table row counts not displayed in Exasol 

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#3144]
If I activate the 'Show row count for tables' option in DBeaver (Window -> Preferences -> Database -> Metadata), then after I connect to an Exasol DB, double-click a table and check the statistics tab, I don't see the row count in there.
Happens with versions 4.3.3 and 5.0.0, running under linux (debian sid, 64-bit)

Steps to reproduce:
-Go to Window -> Preferences -> Database -> Metadata.
-Check the option 'Show row count for tables'
-Open an exasol DB connection
-Double-click some table under it
-In the tab that opens, expand the 'Statistics' section

Expected behavior:
-There should be an entry in the statistics section displaying the row count of the table.

Actual behavior:
-Row count is missing there, even though the option to display it is activated.

Reproducible: always

**Comment by Sargul** [comment]
Row counts were added to the Exasol Plugin and should be available with 5.0.2
![grafik](https://user-images.githubusercontent.com/5595511/37758764-a517359a-2db1-11e8-81a2-d9c555c147e1.png)
