### ISSUE TITLE
Bug Report:  Oracle 11g Functions not Available for DBeaver

### ISSUE THREAD

**Issue by YoYo-Pete** [dbeaver/dbeaver#3146]
Oracle 11g - 11.2.0.4.0

I use Oracle's SQL Developer and the user defined functions are available in my user's schema.

However, in DBeaver, they are not in the Procedures folder for that schema, nor available when running scripts.

**Comment by serge-rider** [comment]
DBeaver uses following query to read procedures:
```sql
SELECT  * FROM SYS.ALL_OBJECTS WHERE OBJECT_TYPE IN ('PROCEDURE','FUNCTION') AND OWNER='SCHEMA_NAME' ORDER BY OBJECT_NAME
```
As far as I know there are no other object types for procedures (except PACKAGE but packages are listed separately).
Do you know what object type your UDF have?

**Comment by YoYo-Pete** [comment]
I came back to update and found that it was some weird issue with SQL Developer and not an issue with DBeaver. 

Sorry for the noise.  I appreciate the response.   Love DBeaver.
