### ISSUE TITLE
Can't build 5.0.0 due to missing dependency

### ISSUE THREAD

**Issue by der-eismann** [dbeaver/dbeaver#3147]
Hey everyone,

I wanted to build version 5.0.0 of DBeaver on Solus, but it failed because of a missing dependency:

```
[INFO] Resolving dependencies of MavenProject: org.jkiss.dbeaver:org.jkiss.dbeaver.ext.ui.svg:1.0.14 @ /home/build/YPKG/root/dbeaver/build/dbeaver-5.0.0/plugins/org.jkiss.dbeaver.ext.ui.svg/pom.xml
[INFO] {osgi.os=win32, osgi.ws=win32, org.eclipse.update.install.features=true, osgi.arch=x86}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.jkiss.dbeaver.ext.ui.svg 1.0.14
[ERROR]   Missing requirement: org.jkiss.dbeaver.ext.ui.svg 1.0.14 requires 'bundle org.apache.xmlgraphics.batik-svggen 1.9.1' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.jkiss.dbeaver:org.jkiss.dbeaver.ext.ui.svg:1.0.14 @ /home/build/YPKG/root/dbeaver/build/dbeaver-5.0.0/plugins/org.jkiss.dbeaver.ext.ui.svg/pom.xml: See log for details -> [Help 1]
```

In the [eclipse-repo](https://dbeaver.jkiss.org/eclipse-repo/plugins/) I can only find verson 1.9.0 of batik-svggen, so can you upload the newer version please?
Oh and btw: The contributing file is empy, but I guess you know that :)

**Comment by serge-rider** [comment]
Batik dependencies were changed in 5.0 (now we have just one bundle jar for all batik libraries)
You need to reinstall all stuff from eclipse-repo.

**Comment by efradkin** [comment]
Just import dependencies form [the repo](http://dbeaver.jkiss.org/eclipse-repo/) as described here: https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse. Then clean and rebuild the project.

**Comment by der-eismann** [comment]
Thanks for your answers! Importing dependencies in Eclipse could be hard because I wanted to package it. The current package for DBeaver is just build with `mvn package`: https://dev.solus-project.com/source/dbeaver/browse/master/package.yml

If this isn't possible anymore I have to find another way.

**Comment by ruspl-afed** [comment]
Do you mean you cannot build 5.0.0 sources with the root pom?

**Comment by serge-rider** [comment]
@der-eismann Maven build works fine without any changes. Maybe some of your artifacts are outdated or local Maven cache contains something outdated.

**Comment by der-eismann** [comment]
I just tried again with the 5.0.1 release and it succeeded without any errors. There's no Maven cache in solbuild (it's cleared after every build), just Maven itself and the tarball. Maybe it's because the [eclipse-repo](https://dbeaver.jkiss.org/eclipse-repo/plugins/) now has the required 1.9.1 version of batik, maybe it's something else, I don't know.
Either way, it works, thanks for your help!
