### ISSUE TITLE
WHY i cant import, i was doing that before successfully. java heap space?

### ISSUE THREAD

**Issue by KuoLianMei** [dbeaver/dbeaver#31503]
### Description

![image](https://github.com/dbeaver/dbeaver/assets/120097559/72f92130-ebc0-4057-98ab-244fd20c2bb9)

### DBeaver Version

24

### Database and driver

![image](https://github.com/dbeaver/dbeaver/assets/120097559/be9e6f1e-c58c-4d1d-8542-fbe11350fd05)

### Steps to reproduce

![image](https://github.com/dbeaver/dbeaver/assets/120097559/c76c7969-40bc-4f23-87d8-43c8bef912fa)

**Comment by ShadelessFox** [comment]
Unfortunately, the same screenshot posted three times doesn't help us understand what happened.

Can you instead provide steps to reproduce the issue along with the DDL of the source table?

As a quick suggestion, if your table has LOBs, try decreasing the fetch size on the "Extraction settings" page.

**Comment by KuoLianMei** [comment]
1
![image](https://github.com/dbeaver/dbeaver/assets/120097559/1beac2f6-9277-4086-940a-481adcc77605)
2
![image](https://github.com/dbeaver/dbeaver/assets/120097559/bd106ad3-28f0-4c4a-b685-634095be2a0f)
3
![image](https://github.com/dbeaver/dbeaver/assets/120097559/ead1ac98-8068-44e9-b232-9e1b237ff366)
4
![image](https://github.com/dbeaver/dbeaver/assets/120097559/d55a0592-3d6a-4ad1-a633-845591aa6baa)
5
![image](https://github.com/dbeaver/dbeaver/assets/120097559/fb571cd4-3274-4033-aad2-9c57692a7b1f)
6
![image](https://github.com/dbeaver/dbeaver/assets/120097559/b114edb4-8928-4af8-b327-023e3a325ae8)

java heap space

how could i resolve it?

thanks for everyone replay me!
thank you

**Comment by E1izabeth** [comment]
Please try decreasing the driver version to 8.0.31
![image](https://github.com/dbeaver/dbeaver/assets/28875055/c840fefa-fdd8-4386-9c54-e8692fc5abfb)

Does it help?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
