### ISSUE TITLE
Reuse query parameter values

### ISSUE THREAD

**Issue by ljantzen** [dbeaver/dbeaver#3152]
I have a script with severeal queries, where many of them use the same parameter, ':customerid'.  This value does not change for the duration of the script.  

Currently, DBeaver prompts me for the value every time it encounters this parameter.  It would be nice if there was a checkbutton on the 'Bind parameters dialog' that let the user choose not to be asked for the same value for each and every query in the script (when run with Alt-X).

**Comment by serge-rider** [comment]
How do you see this?
What if you still need to change parameter value? Maybe this could be solved by special "silent" mode which can be enabled/disabled. But I'm not sure that it'll be convenient and obvious for users.
