### ISSUE TITLE
Hive Diagrams not showing FKs

### ISSUE THREAD

**Issue by gpogliani** [dbeaver/dbeaver#3155]
Hi,
starting from version 0.8 Hive supports constraints PK and FK.
PK are well displayed in dbeaver not FK.
Is there a particular reason why not? JDBC Driver?

It would be great to have it to leverage the diagram functionality very useful for the users.

Thanks

**Comment by serge-rider** [comment]
I didn't actually try this but most likely JDBC driver just doesn't provide information about FKs. Perhaps it can be fixed by upgrading the driver version.
