### ISSUE TITLE
M3 MAC DBeaver unable to connect to any database due to "Network Unavailable SSL Handshake Exception error"

### ISSUE THREAD

**Issue by rithvikmundra** [dbeaver/dbeaver#31572]
### Description

Unable to connect to SQL lite or MYSQL Server db (in fact any DB) on a M3 MAC due to network error when downloading driver files.

Followed the steps listed in this issue and no luck - https://github.com/dbeaver/dbeaver/issues/18175

Also followed the fix listed by @alun (https://github.com/alun) in the same issue above [here](https://github.com/dbeaver/dbeaver/issues/18175#issuecomment-1722554453) but it doesn't work on M3 Mac.

<img width="962" alt="error" src="https://github.com/dbeaver/dbeaver/assets/17887041/bdc40f2b-41f6-48ab-8fe4-7405f17dc79b">

### DBeaver Version

Community Edition 24.0.4.202405051837

### Operating System

macOS Sonoma 14.4.1

### Database and driver

Microsoft SQL Server

### Steps to reproduce

Download Dbeaver on a M3 Mac and just try setting up a basic SQL lite DB and it errors out.

**Comment by Matvey16** [comment]
@rithvikmundra Have you tried ZScaler Root Certificate? https://github.com/dbeaver/dbeaver/issues/18175#issuecomment-1983533747

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
