### ISSUE TITLE
Bug - Title of Error Message (Can''t obtain session)

### ISSUE THREAD

**Issue by matty-codes** [dbeaver/dbeaver#3159]
When disconnected from the database, the title is displaying two single quotes.
Error might be caused in the following file: dbeaver/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/CoreResources.properties (line 696).
**Possible** fix: remove one of the quotes. Unsure if this will break anything, as two single quotes seem to be the standard used across the file.
![screenshot from 2018-03-16 10-45-01](https://user-images.githubusercontent.com/9097319/37516764-27f3ab88-2907-11e8-9430-2d64820f0e08.png)

**Comment by serge-rider** [comment]
Thanks for noticing!
