### ISSUE TITLE
[Question] Function wont compile - works in sql developer - need advice

### ISSUE THREAD

**Issue by YoYo-Pete** [dbeaver/dbeaver#3161]
This is a function that I can compile when I use Oracle SQL Developer, but DBeaver will not and I dont understand what I need to do to make DBeaver happy.    This is the last piece holding be back from removing SQL Developer.  

**Oracle 11g**

`CREATE OR REPLACE FUNCTION SCHEMA_NAME."USER_NAME" `
`    (V_USER_ID IN VARCHAR2) `
`    RETURN VARCHAR2 `
`IS `
 `   V_USER_NAME VARCHAR2(255);`
 `  BEGIN `
 `   SELECT`
 `   CASE `
 `       WHEN V_USER_ID = '#APP' THEN 'Application' `
 `       ELSE (SELECT LASTNAME || ', ' || FIRSTNAME FROM V_USER_DATA WHERE USER_ID = V_USER_ID)`
`    END  USERNAME `
`      INTO V_USER_NAME`
`      FROM DUAL;`
`    RETURN(V_TECH_NAME);`
`END;`

This is a vendor's database (table names changed to protect the IP) and I have a function that simply returns the User Name from the UserID.

**Usage Example**
`Select USER_NAME(USER_ID), User_ID From Table   `
| YoYo-Pete | 17 |

DBeaver wont compile this.  ORA-06550 error (end of file)

I'm not connecting the dots on the differences with DBeaver and SQL Developer to correct the error and get this to compile.

Any advice?

**Comment by p91paul** [comment]
Try selecting everything from the word "CREATE" to the last "END;" and use ctrl+click (Execute statement).
You are probably using Alt + X (execute script).

Still Alt + X should be taught to understand begin/end blocks in Oracle and avoid to split them in multiple statements because of ;

**Comment by YoYo-Pete** [comment]
That did it... I was indeed using Execute Script.

Highlighting then Execute Statement is the trick. 

Thank you!!
