### ISSUE TITLE
Oracle DDL - Unchecked fully qualified name does not remove schema name

### ISSUE THREAD

**Issue by osirus31** [dbeaver/dbeaver#3164]
Reproduce:
1) with Oracle connection generate DDL for any object in any schema
2) with popup window open uncheck the "Use fully qualified names" checkbox

Expected: The DDL should regenerate with the schema name removed
Actual: It does regenerate but schema name remains, no actual change

Occurs: 100% of the time
DBeaver versions : 4.3.3+ (and probably earlier as well)

Additional info:
In OracleUtils class the below call can be added with the value conditional on the "Use fully qualified names" preference setting, this will correct table DDL generation.

DBMS_METADATA.SET_TRANSFORM_PARAM(dbms_metadata.SESSION_TRANSFORM, 'EMIT_SCHEMA', false);

**Comment by uslss** [comment]
will be fixed in scope of #7042
