### ISSUE TITLE
Cannot define a connection url with no port specified.

### ISSUE THREAD

**Issue by jbgisser** [dbeaver/dbeaver#3165]
I have just downloaded DBeaver and setting up my first client ... 
Trying to connect to an MS SQL Server that should have a connection url that looks like this:

> jdbc:sqlserver://servername\internal;databaseName=thedatabase

(there is no port number)

But whenever DBeaver tries to connect, it inserts the Port number like this:

> jdbc:sqlserver://servername:1433\internal;databaseName=thedatabase

My url template looks like this:

> jdbc:sqlserver://{host}[;databaseName={database}]

That is, I have removed the [:{port}] parameter, but it continues to be used by the connection process.

I'm not able to make the connection work, and I'm not sure if the problem is because of the port number being inserted when it shouldn't be.

The connection does work from another server so maybe the issue may be a firewall, but just saying that the template changes that I'm trying to make aren't respected.

Edit: I tried specifying the port on the url for the connection that is working and it fails. So I'm hopeful that if I can get DBeaver to ignore the port then it might also work

**Comment by serge-rider** [comment]
After version 4.3.5 SQL Server URL is constructed differently than for Generic driver.
However this problem with port number is a bug (if port is the same as default port then it shouldn't be specified explicitly).
Thanks for report.

**Comment by Taariqq** [comment]
Having similar issue with the message "Must specify port after ':' in connection string" when I try to connect to mysql inside a vagrant client.

**Comment by smithaitufe** [comment]
@Taariqq 
I tried this `localhost;port=14330` and it worked. I connected to Microsoft SQL Server running in Docker in port 14330.
In place of server, simply specify the name of the server and the port. In my case `localhost` is the server. Notice the semi colon after the server name. then specify the `port=value`
