### ISSUE TITLE
Commit and Rollback buttons does not enable (connection JDBC to Progress db)

### ISSUE THREAD

**Issue by mauro1068** [dbeaver/dbeaver#3168]
Hi All,

I've just updated from DBeaver 3.8.3 CE to 5.0.0 CE and I'm wondering if buttons "Commit" and "Rollback" doesn't enable enymore when switching in maual commit (read committed).
I use DBeaver to interface to a Progress 4GL database using JDBC drivers.
Could someone help?
Cheers,
Mauro

**Comment by serge-rider** [comment]
Can't reproduce this issue.
What is your OS? 
Do you use standalone version or Eclipse plugin?
What actions you perform to trigger transaction start?

**Comment by mauro1068** [comment]
Windows server 2008 R2 Standard with Service Pack 1
I use standalone CE version
In previous version (3.8.3) when in read committed mode I was able (switching to manual commit) to manually execute commit and/or rollback (this because buttons becamed enabled). 
Now (version 5.0.0) even if I switch to manual commit when in read committed mode these two buttons doesn't enable.

**Comment by mauro1068** [comment]
[video.zip](https://github.com/dbeaver/dbeaver/files/1825437/video.zip)

here attached two videos with behavior on two versions.

**Comment by serge-rider** [comment]
Commit/Rollback buttons will become enabled once you will execute any transactional query.

**Comment by mauro1068** [comment]
ok,thanks. Now I got it.

Cheers,
Mauro
