### ISSUE TITLE
Ctrl+C doesn't work if navigated through arrow keys

### ISSUE THREAD

**Issue by msau9** [dbeaver/dbeaver#3169]
This is minor but pretty weird:

In the screen that shows details of the table, (refer screenshot), if I click-select a column and press Ctrl+C, it copies the column name (as intended), but if then I press up/down arrow keys to navigate to a different column and press Ctrl+C, then it doesn't copy the name to clipboard! Instead I have the previous column's name stored in the the clipboard. Now if I click-select(with the mouse) the other column, and press Ctrl+C, then it correctly copies this column's name to clipboard.
![screenshot from 2018-03-19 14-07-39](https://user-images.githubusercontent.com/15860193/37585377-edc10b48-2b7e-11e8-9914-2ab9f3a1418c.png)

**Comment by serge-rider** [comment]
Thanks for report
