### ISSUE TITLE
Cassandra: Filtering does not work

### ISSUE THREAD

**Issue by naraesk** [dbeaver/dbeaver#3170]
I can't run filter expressions on tables of a cassandra database. Please have a look at the screenshot. I'm talking about the field for entering filter criteria in the red circle. 
When entering something like `category = 3 ALLOW FILTERING` I get the following error message

`
com.datastax.driver.core.exceptions.SyntaxError: line 1:61 mismatched input 'LIMIT' expecting EOF (...category = 3 ALLOW FILTERING [LIMIT]...)
  com.datastax.driver.core.exceptions.SyntaxError: line 1:61 mismatched input 'LIMIT' expecting EOF (...category = 3 ALLOW FILTERING [LIMIT]...)
    com.datastax.driver.core.exceptions.SyntaxError: line 1:61 mismatched input 'LIMIT' expecting EOF (...category = 3 ALLOW FILTERING [LIMIT]...)
      line 1:61 mismatched input 'LIMIT' expecting EOF (...category = 3 ALLOW FILTERING [LIMIT]...)
      line 1:61 mismatched input 'LIMIT' expecting EOF (...category = 3 ALLOW FILTERING [LIMIT]...)
`

It's not specific for the mentioned filter criteria, I get the same error for every query I tried.

**Comment by naraesk** [comment]
Forgot the screenshot :-)

![screenshot_20180319_142937](https://user-images.githubusercontent.com/7393797/37607497-7a577a74-2b98-11e8-9b5d-463c49962ded.png)

**Comment by uslss** [comment]
Issue is already fixed. It is not needed to add "Allow filtering" in that case.
Ticket closed
