### ISSUE TITLE
Rename database in postgres does not work.

### ISSUE THREAD

**Issue by LorisZ** [dbeaver/dbeaver#3171]
When you try to to rename a postgres-database in DBeaver it says "Direct database rename is not yet implemented in PostgreSQL. You should use export/import functions for that."

I expected it to execute `alter database oldname rename to newname`, which actually works (when you are connected to a different db).

used: DBeaver 5.0.1 on Ubuntu 16.04.

**Comment by serge-rider** [comment]
Good point.
Will add db rename in the next version.

**Comment by LeroyAndrade** [comment]
Created a new DB and set that as default so that I could rename my DB name foo|

SQL Error [0A000]: ERROR: current database cannot be renamed
  ERROR: current database cannot be renamed
  ERROR: current database cannot be renamed

Ubuntu 22
Holding back.

**Comment by LeroyAndrade** [comment]
Also, the databases keep existing but they can't be seen when deleted.
Good, so I deleted database foo1
delete the entire program(dbeaver)

and the program was still, accessible to the db

What are you doing below water that makes this happen?!

Reinstalled the program without any issue and when creating foo1, it said it already existed ...
