### ISSUE TITLE
Postgres - Database/Schema name conflict

### ISSUE THREAD

**Issue by LorisZ** [dbeaver/dbeaver#3172]
When you have a database and a schema of another database with the same name, then everytime you try to use that schema, it switches to the other database. Only way around is writing `from database.schema.table` in every query or renaming either database or schema (or turning off `Switch default database on access`, I assume). Also the autocomplete-drop-down only shows the database not the schema when you write `from testschema.`, where I would expect both to show up.

Steps to reproduce:

1. Create a postgres database named `test`.
2. Create another database with `anotherdb` on the same server, and create a schema called `test`.
3. Connect to the server with options `Show non-default databases` and `Switch default database on access` enabled. 
4. Open a sql editor on `anotherdb`.
5. Write `select * from tes`

Autocomplete only shows database `test`, not schema `test`. When you choose the db or just write it manually, once you have `select * from test.` DBeaver automatically switches db.

Tested on DBeaver 5.0.1, Ubuntu 16.04.

**Comment by serge-rider** [comment]
Honestly this is complicated (because of specific PG databases model).

**Comment by uslss** [comment]
the issue is not reproducible on 6.0.2.
