### ISSUE TITLE
5.0.1 installers being quanrantined by Symantec

### ISSUE THREAD

**Issue by jk3us** [dbeaver/dbeaver#3174]
Both Windows installers for 5.0.1 are being caught and quarantined by Symantec Endpoint Protection like this:

```
Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: WS.Reputation.1
File: c:\users\abcde\downloads\dbeaver-ce-5.0.1-x86-setup.exe
Location: Quarantine
Computer: UVXYZ
User: abcde
Action taken: Quarantine succeeded
Date found: Monday, March 19, 2018  5:02:07 PM
```

The zip files seem to be okay.  I've downloaded every version for the last year and half or so and never had a problem. I don't know if something changed in the installers or if our infosec folks have gotten more paranoid, but I thought I'd post in case other people have the same thing.

**Edit** I just wanted to clarify that this isn't necessarily an indication of a virus:

>WS.Reputation.1 is a detection for files that have a low reputation score based on analyzing data from Symantec’s community of users and therefore are likely to be security risks. Detections of this type are based on Symantec’s reputation-based security technology. Because this detection is based on a reputation score, **it does not represent a specific class of threat like adware or spyware**, but instead applies to all threat categories. 

https://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99

**Comment by carlosspohr** [comment]
Hi there,

I also get this warning from Avast every time I'll install new release. Avast always alert me about verification on his database, and, after some minutes the installer file is released from quarentine.

**Comment by infectormp** [comment]
no have any problem from Kaspersky and Windows defender

**Comment by serge-rider** [comment]
Perhaps Symantec has changed something on their side. I saw similar warnings for previous DBeaver releases - they warn about new files during a 1-2 days.
But usually this is just a warning, not quarantine:
![image](https://user-images.githubusercontent.com/6398845/37645347-a1b02d9c-2c37-11e8-96b1-b0d07b1b9da7.png)
You can just click "Allow this file".

**Comment by serge-rider** [comment]
Note that corporate Symantec Endpoint Protection may count users for specific organization (actually this depends on corporate policy). So this may take some time until number of users in your particular organization will be big enough.

**Comment by jk3us** [comment]
I was able to restore the file from quarantine, which I didn't think I would be allowed to do... But I was able to get it installed.

**Comment by lemonsoftltd** [comment]
In my computer, AVG Free Edition says IDP.Generic for DBeaver 5.1.2. What did I do wrong?

**Comment by serge-rider** [comment]
Now we use another coe sign certificate and we also participate in Microsoft developer program so most such issues should go away.
