### ISSUE TITLE
Mock data generator on integer fields have a weird parameter ("% of NULLs"). 

### ISSUE THREAD

**Issue by utkukaratas** [dbeaver/dbeaver#3176]
Mock data generator on integer fields have this parameter named "% of NULLs". One would expect a "max/min" parameter instead. Maybe i'm misunderstanding something.

ps. dbeaver is a superb tool, thanks to everyone on the team!

**Comment by efradkin** [comment]
@utkukaratas, "% of NULLs" parameter specifies the quantity of NULL values among all generated values.
Min/max parameters affect not-NULL generated values.
