### ISSUE TITLE
SqlServer drivers need to be downloaded every time i restart dbeaver

### ISSUE THREAD

**Issue by JohnS-BCS** [dbeaver/dbeaver#3177]
I am using dbeaver to connect and work with SQL Server and I have a connection set to use the MS SQL driver. After I setup, the connection things work fine. When I close the app and reopen and I try to open the connection I am prompted to download the drivers again. When I redownload them things work for that session. Close and reopen and I need to download them again. I have tried several things like Force check box. I tried using the jtds driver but had the same issue, needed to download again when i opened the connection in a new session, I prefer the MS drivers.

I am running Windows Server 2016 as admin with SQL Server 2016. 

thanks for your time and support.

John 

![image](https://user-images.githubusercontent.com/16564985/37659065-54c457d6-2c25-11e8-8c16-2aef23034caa.png)

**Comment by serge-rider** [comment]
Can't reproduce. Do you know - does this happen only with SQL Server driver or with any driver?

DBeaver downloads and saves driver files in ${USER_HOME}\.dbeaver-drivers\ folder. Binary is saved in `drivers\mssql\auth\x64\` subfolder, Maven jars are in `maven/maven-central/com.microsoft.sqlserver` subfolder. Are these folders/files present on your machine?

BTW did you try another driver (jTDS)?

**Comment by JohnS-BCS** [comment]
First off i was able to fix it by deleting everything in the 
> C:\Users\Administrator\.dbeaver4\.metadata
and starting the app up to reinitialize that folder. I needed to download the drivers once and now it appears to be fixed. 

While snooping around I noticed some files in the .plugins directory appeared older than I would expect. One of the files mentioned version 4 but I am currently running 5. I upgraded a while back. 

I've attached debug log before I cleaned out the metadata directory.

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/1835165/dbeaver-debug.log)

Thanks 
John

**Comment by serge-rider** [comment]
Yep, these errors seems to be a result of incorrect version upgrade (e.g. if you use zip archive then previous version has to be deleted completely before extracting new one in the same location).
There were a lot of Access Denied errors, DBeaver wasn't able to save configuration properly.

Thanks for letting know.
