### ISSUE TITLE
How to quickly delete only the whitespace before/after cursor?

### ISSUE THREAD

**Issue by chrisdabel** [dbeaver/dbeaver#3179]
There seems to be no option to do this, as in other IDEs/Text Editors.
I'm on a Mac (OSX Sierra).

Typically, `option + Del/Backspace` or `Ctrl + Del/Backspace` does this. But in DBeaver, it deletes the previous/next word.

**Comment by serge-rider** [comment]
There is no such shortcut but you can use <kbd>SHIFT+Left</kbd> or <kbd>SHIFT+Right</kbd> and then<kbd>Backspace </kbd>. 
I'm afraid this is the only workaround at the moment.

**Comment by chrisdabel** [comment]
Is this feature a future enhancement?

**Comment by serge-rider** [comment]
No, it should already work on Mac. At least it works on my Mac Air (Sierra)
