### ISSUE TITLE
 Cassandra UDT displaying as Null

### ISSUE THREAD

**Issue by tanneess** [dbeaver/dbeaver#3181]
Apparently this is a recurring bug as it is present in version 5.0.1 (EE).
I see that the issue was already fixed in  "Cassandra UDT displaying as Null #1404", but it is now broken again.
Maybe worth having an automated regression test on this one :)?

**Comment by serge-rider** [comment]
Thanks for report.
Actually it is not exactly the same issue. It will be fixed in the next version (we going to release EA version of DBeaver EE along with CE releases)

And yes, good regression tests is one of our goal :)

**Comment by tanneess** [comment]
Great news, in the mean time where can I download a previous version of DBeaver working fine with cassandra. I could not find a way to download version 4 for instance.

**Comment by serge-rider** [comment]
Here it is: https://dbeaver.com/files/

**Comment by tanneess** [comment]
Thanks
