### ISSUE TITLE
Statement delimiter problem with BEGIN; under PostgreSQL

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#3182]
Hi,

With DBeaver 5.0.1, I am facing the problem descripted here: https://github.com/dbeaver/dbeaver/issues/1114

The enhancement was fixed in previous version.
Is it a regression?

Thanks in advance for your help.

Regards,
Cedric

**Comment by serge-rider** [comment]
Can't reproduce that (BEGIN statement is correctly executed as a separate statement in PostgreSQL).
Could you provide a bit more details?

**Comment by ced75** [comment]
OK, I think it is a border effect with this issue: https://github.com/dbeaver/dbeaver/issues/1823

It is because I have quotes and $$ just before my BEGIN statement.

Sorry for the wrong issue.

**Comment by serge-rider** [comment]
Well, if you still experience some issue with pgSQL processing - please post example of problematic query.
