### ISSUE TITLE
Erro Select FieldType BLOB 

### ISSUE THREAD

**Issue by reccall** [dbeaver/dbeaver#3184]
WHY???? >>> [img2.pdf](https://github.com/dbeaver/dbeaver/files/1834970/img2.pdf)

**Comment by serge-rider** [comment]
Please provide more info.
What is your database/driver?

**Comment by reccall** [comment]
.GDB - Firebird - 2.5;

**Comment by mrotteveel** [comment]
This can occur when the blob is retrieved in a different transaction than the select, for example with holdable result sets if the transaction was (auto) committed.
