### ISSUE TITLE
[Question] - Is there documentation on how to use the Mock Data feature?

### ISSUE THREAD

**Issue by ryancabanas** [dbeaver/dbeaver#3187]
Hi,

I'm running 5.0.1 and I just happened to notice the "Mock Data" button at the bottom of the results window.  Is there documentation explaining how to use this?  When I click it right now I just get a message that states, "Mock Data can be generated for a table only."

Thanks!
Ryan

**Comment by serge-rider** [comment]
We are working on documentation.
You can generate mock data by right clicking on a table in database navigator or in results viewer on "Data" tab of table editor.

**Comment by ryancabanas** [comment]
Thanks, Serge!

I was successfully able to generate mock data using both methods you mentioned.

Thanks again!

**Comment by efradkin** [comment]
@ryancabanas take a look at short article here: https://github.com/dbeaver/dbeaver/wiki/Mock-Data-Generation

**Comment by ryancabanas** [comment]
Great!

Am I able to make any edit suggestions on documentation page in GitHub?

Thanks!
Ryan

**Comment by efradkin** [comment]
@ryancabanas you can ask @serge-rider to get rights to edit the wiki.

**Comment by serge-rider** [comment]
@ryancabanas I can add you as collaborator (write me on serge@jkiss.org) or you can just post some improvements in comments and we'll fix wiki.

**Comment by kid1412621** [comment]
@serge-rider is this feature removed? I cannot find it any more in version 6.2

**Comment by serge-rider** [comment]
See #6592

**Comment by kid1412621** [comment]
Thx,  ee version is a little bit expensive for indie developer through.

**Comment by serge-rider** [comment]
:(
Well, you could try monthly subscription, it is not expensive. 
And fits if you need to use some EE feature just a few times.
