### ISSUE TITLE
Tento alterar o tipo de dados de VARCHAR para outro tipo de dados pela interface do sistema (não quero alterar via SQL) mas não consigo

### ISSUE THREAD

**Issue by srRodolfo** [dbeaver/dbeaver#3191]
Bom dia!

Tento alterar o tipo de dados de VARCHAR para outro tipo de dados pela interface do sistema 
(não quero alterar via SQL) mas não consigo devido ao charset e collation do campo estarem setados respectivamente 'utf8' e 'utf8_general_ci' acredito que seja necessário remove-los mas, não estou conseguindo encontrar a forma de faze-lo. Solicito seu auxilio.
Desde já agradeço!
![2018-03-22-062922_630x230_scrot](https://user-images.githubusercontent.com/18177332/37762395-f00f6a0c-2d9a-11e8-8ea2-df53306dba2b.png)
![2018-03-22-063415_1280x800_scrot](https://user-images.githubusercontent.com/18177332/37762450-0e3415b4-2d9b-11e8-841c-e8ef75d85c29.png)

**Comment by serge-rider** [comment]
You can just click in data type column and change it. Then you can save changes (<kbd>ctrl+s</kbd>)

**Comment by srRodolfo** [comment]
Justamente amigo quando eu vou lá na bendita coluna "tipo de dados" e altero de "varchar" para qualquer outro tipo e tento salvar ocorre o erro da imagem.

**Comment by serge-rider** [comment]
What error do you see?

**Comment by srRodolfo** [comment]
esse da imagem que coloquei na pergunta, observe a query que o dbeaver cria errada

**Comment by serge-rider** [comment]
Ok. 
- Please post SQL generated by DBeaver (in Persist Changes dialog)
- What MariaDB (MySQL) server version do you use?

**Comment by srRodolfo** [comment]
**Sistema:**

Servidor: Localhost via UNIX socket
Tipo de servidor: MariaDB
Versão do servidor: 10.1.28-MariaDB - Source distribution

Ubuntu 16.04 LTS 64bits

**Texto da caixa de dialogo:**

ALTER TABLE db_essentials.Cidades MODIFY COLUMN estado INT CHARACTER SET utf8 COLLATE utf8_general_ci NULL ;

**Texto da mensagem de erro:**

SQL Error [1064] [42000]: (conn:3) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CHARACTER SET utf8 COLLATE utf8_general_ci NULL' at line 1
Query is : ALTER TABLE db_essentials.Cidades MODIFY COLUMN estado INT CHARACTER SET utf8 COLLATE utf8_general_ci NULL
  (conn:3) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CHARACTER SET utf8 COLLATE utf8_general_ci NULL' at line 1
Query is : ALTER TABLE db_essentials.Cidades MODIFY COLUMN estado INT CHARACTER SET utf8 COLLATE utf8_general_ci NULL
    You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CHARACTER SET utf8 COLLATE utf8_general_ci NULL' at line 1
Query is : ALTER TABLE db_essentials.Cidades MODIFY COLUMN estado INT CHARACTER SET utf8 COLLATE utf8_general_ci NULL
    You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CHARACTER SET utf8 COLLATE utf8_general_ci NULL' at line 1
Query is : ALTER TABLE db_essentials.Cidades MODIFY COLUMN estado INT CHARACTER SET utf8 COLLATE utf8_general_ci NULL

**Comment by serge-rider** [comment]
I've reproduced that. This happens if column data type was changed from character data type to numeric. It still keeps charset/collation information and DBeaver uses it in ALTER TABLE.
After fix it will use it only for character data types.
Thanks for report.

**Comment by srRodolfo** [comment]
Obrigado, pelo auxilio e pelo ótimo Software. Fica com Deus!
