### ISSUE TITLE
Drag and Drop columns name

### ISSUE THREAD

**Issue by renezito** [dbeaver/dbeaver#3193]
Please, can you add the feature "drag and drop" for column names.  See the video, I use SqlTools and now I'm using this great tool, but it could be better with this feature :-)

[sqltools_drag_and_drop.zip](https://github.com/dbeaver/dbeaver/files/1838206/sqltools_drag_and_drop.zip)

Thanks
René

**Comment by serge-rider** [comment]
This is already supported. Just drag column data type icon.

**Comment by offstate** [comment]
Drag and Drop doesn't  work  for the result column names. I can drag it to any place, but when I drop it nothing happens. (CE version)
I would like to drop the column name to:
- sql-editor
- result filter
- different position in the result header

Thank you

**Comment by serge-rider** [comment]
Drag-n-drop is already supported for grid columns. It will be improved in 5.1.
Text drop support for filters editor will be also added in 5.1.

**Comment by renezito** [comment]
Everything i sfine for me.  I'm using DBeaver 5.1 CE.  Thanks!

**Comment by offstate** [comment]
Doesn't work for me at all
[dbeaver-2018-06-23_18.37.45.mp4.zip](https://github.com/dbeaver/dbeaver/files/2129770/dbeaver-2018-06-23_18.37.45.mp4.zip)

**Comment by GAZ082** [comment]
This works in grid view but does not work in single record view (the one activated by pressing tab in the output window).

CE, Version 23.1.4.202308061552, Windows
