### ISSUE TITLE
Help: Add procecure to exisiting database

### ISSUE THREAD

**Issue by SockeTopp** [dbeaver/dbeaver#3194]
Hello fellow community,

I am fairly new to dbeaver so excuse me if this is a trivial issue that I should have solved myself.

I am conntected to an mssql database where I would like to add more procedures. 

My issue is that I can't find a way to add more procedures to the database. Is this not implemented or have I completely missed this feature?  

Thanks beforehand,
//ST

**Comment by serge-rider** [comment]
This depends on database (DBMS). Some (like Oracle, MySQL, PostgreSQL) support procedure creation in UI. For others the only way is to execute SQL script.
