### ISSUE TITLE
Dbeaver 5.0 sybase stored procedure multiple result set

### ISSUE THREAD

**Issue by kothapet** [dbeaver/dbeaver#3195]
Is running sybase ase stored procedure which results in multiple result sets supported. I am not seeing the results.
e.g. 
sp_help tablename
execute sp_help tablename

suppose to return 10 result sets..

**Comment by serge-rider** [comment]
Returns 10 resultsets in my test env.

![image](https://user-images.githubusercontent.com/6398845/37849191-c581cd68-2ee7-11e8-90ee-0a31d083036b.png)

- What result do you see?
- What driver do you use?

**Comment by kothapet** [comment]
Sorry for later replay, but tHis is what I see. Is there a setting to show multiple result sets in tabs..

![dbeaver](https://user-images.githubusercontent.com/18431847/37926660-e0eb7796-3105-11e8-8fcf-cc40bef42022.jpg)

**Comment by serge-rider** [comment]
What server version/driver do you use? You can click on "Test connection" in connection properties dialog and post the screenshot.

**Comment by kothapet** [comment]
Database is Sybase ASE V16 and I am using Jconnect4 JDBC drivers.

**Comment by kothapet** [comment]
Actually it seems to be working fine, if I run it as a execute as Script. 
It wasn't working when I run as a execute sql statement..
So, I am good with this issue. Thanks for looking into it and Sorry for wasting your time.

**Comment by serge-rider** [comment]
So far I have no idea why it doesn't work in your case :(
Could you try jTDS driver?

**Comment by anilsoni85** [comment]
+1.
Same issue.
DBeaver v4.2.0
Sybase ASE 15.7

DBeaver doesn't show output for store procedure call e.g. sp_help, sp_who, It only displays statistics.

e.g. run
exec sp_help
exec sp_who

Driver Class Name: com.sybase.jdbc4.jdbc.SybDriver
Lib: %SybaseRoot%\jConnect-7_0\classes\jconn4.jar

**Comment by tati-kru** [comment]
@anilsoni85 the version 4.2.0 is out of support. Could you please check it for the version 6.1.1?

**Comment by kothapet** [comment]
Also run it as script option, instead of run it as a sql. That should work.

**Comment by anilsoni85** [comment]
"Driver Supports multiple results" parameters was disabled by default in Driver Adv. Parameters tab under "Edit Driver", i enabled and it fixed the issue.

**Comment by ChrisLynch42** [comment]
"Driver Supports multiple results" was my issue as well.  Thank you.
