### ISSUE TITLE
[Question] - Is there a setting that will remember the last folder location used when opening a file with "Ctrl + O"?

### ISSUE THREAD

**Issue by ryancabanas** [dbeaver/dbeaver#3196]
Hi!

I'm running Windows 10.  When I use "Ctrl + O" to open a file, the first time I do this, the app starts me off at the folder "C:\Users\Ryan".  During the same DBeaver session, if I use "Ctrl + O" again, the app remembers the last folder I opened a file from (this is what I want).

Is there a way to set up the app so that it **always** remembers the last folder I opened a file from, even from session to session?  If not, is there a setting where I can designate a static starting folder, other than "C:\Users\Ryan"?

Thanks!
Ryan

**Comment by serge-rider** [comment]
Unfortunately no. It is standard Eclipse action.

But I can add custom handler for this command which will remember last folder..

**Comment by ryancabanas** [comment]
That would be great.  Thanks!

**Comment by georgethemarmot** [comment]
bump for feature

**Comment by uslss** [comment]
already implented
