### ISSUE TITLE
Is there a mini-map/satellite view/radar/navigator for ER diagram

### ISSUE THREAD

**Issue by yanOnGithub** [dbeaver/dbeaver#3197]
My schema is too bit to fit on on screen. Can I have an RTS-style minimap? It should work like oracle data modeler's navigator. The red rectangle is the area that is zoomed in the ER diagram edit window. The largest schema here has about 1500 tables.

![image](https://user-images.githubusercontent.com/25423046/37808968-258b4a0a-2e88-11e8-8bce-0c9b02ea3bfb.png)

**Comment by serge-rider** [comment]
You can use Outline view (main menu Window->Show View->Other->Outline)
![image](https://user-images.githubusercontent.com/6398845/37850263-8f1ad414-2eeb-11e8-957b-6b55a2e1c3e1.png)

**Comment by yanOnGithub** [comment]
thx
