### ISSUE TITLE
In ER diagram, clicking the mouse wheel on empty space should toggle free scrolling like chrome

### ISSUE THREAD

**Issue by yanOnGithub** [dbeaver/dbeaver#3198]
Currently pressing the mouse wheel on empty space turns the mouse pointer into a crosshair. Releasing the mouse wheel returns the mouse pointer to a pointer. What is the crosshair for? I would like to enable free scroll mode, move the mouse pointer in the direction that I want to scroll to, then exit free scroll mode. I am used to this kind of scrolling in chrome.

**Comment by serge-rider** [comment]
Unfortunately mouse wheel is not supported in ERD.
But you can use <kbd>CTRL++</kbd> and <kbd>CTRL+-</kbd> for zoom.

**Comment by yanOnGithub** [comment]
I mean scrolling, not zooming. Mouse wheel may be replaced by middle button.

**Comment by yanOnGithub** [comment]
something like pan & zoom when the website is much bigger than the browser viewport.

![20180324t090604-yani5](https://user-images.githubusercontent.com/25423046/37858651-d51e3daa-2f42-11e8-9038-76831030be36.png)

**Comment by yanOnGithub** [comment]
The outline view you provided in #3197 would suffice. I have been looking for a way to scroll thru large ER diagrams. This one is not needed. Thx.

**Comment by serge-rider** [comment]
Zoom with mouse wheel will be added in 6.1.1
