### ISSUE TITLE
Can the global and table-level columns filter be applied to both database navigator and ER diagrams?

### ISSUE THREAD

**Issue by yanOnGithub** [dbeaver/dbeaver#3199]
Currently the ER diagram always show all columns of selected tables. I am looking for a way to hide some columns on the ER diagram by pattern matching.

![20180323t173052](https://user-images.githubusercontent.com/25423046/37821924-01bc6126-2ec0-11e8-8931-2d82959b79cd.png)

![20180323t172424](https://user-images.githubusercontent.com/25423046/37821680-411b2f88-2ebf-11e8-83ec-67eaab52f147.png)

**Comment by yanOnGithub** [comment]
![20180324t113533-yani5](https://user-images.githubusercontent.com/25423046/37859975-84b15108-2f57-11e8-9793-7df82505ed64.png)

**Comment by serge-rider** [comment]
Yep, this would be a good enhancement.

**Comment by uslss** [comment]
verified
