### ISSUE TITLE
Bug Report Open Query Results in Excel - Excel 2016 complains of error and cannot recover file

### ISSUE THREAD

**Issue by Buyur** [dbeaver/dbeaver#3200]
When trying to open the results of a query in Excel 2016 (Office365 subscripton) Excel shows error dialog 'We found a problem with some content in {filename}. Do you want us to try and recover as much as we can? ...  Selecting Yes fails to recover anything and blank worksheet displayed.

**Comment by serge-rider** [comment]
Maybe it was the same as  #3178 (NULL cell values). 

Or maybe it is a different issue. Is there anything special about your resultset? 
Some special data types?
Does this error happen with any resultsset or just with some?
