### ISSUE TITLE
Dbeaver Installation issues

### ISSUE THREAD

**Issue by alrsrinivas99** [dbeaver/dbeaver#3202]

**Comment by alrsrinivas99** [comment]
Hi, I am seeing issues with dbeaver 5.0.1 installation. It Seems like its related to the Java in my windows machine. I am looking for help in resolving this.

![image](https://user-images.githubusercontent.com/15706477/37860919-6a9b13b4-2f55-11e8-89dd-d25bc6653196.png)

I have updated to version 5.0.1 then am all stuck with errors and my current work is halted. 

Any leads are highly appreciated. 

Thank you and Warm Regards,
Srini

**Comment by alrsrinivas99** [comment]
I am seeing this alert constantly when am installing the 5.0.1 ver. I had it aborted but it shuts down after I aborted it

![image](https://user-images.githubusercontent.com/15706477/37860979-6e160386-2f56-11e8-8832-7e4356b1b07d.png)

**Comment by alrsrinivas99** [comment]
does it need JDK/JRE 8 or 10 , I have 10 on my machine

**Comment by serge-rider** [comment]
1. Try to reboot.
2. DBeaver requires Java 8 but DBeaver installer already contains it. So you don't need to install Java separately.
3. If it still doesn't start - please post log file which mentioned in the first error dialog.

**Comment by alrsrinivas99** [comment]
![image](https://user-images.githubusercontent.com/15706477/37874389-9a61d0c8-304b-11e8-801b-d21b79f9a5f9.png)

**Comment by alrsrinivas99** [comment]
It is getting abort all the time, quickly send me the log file.

**Comment by alrsrinivas99** [comment]
deleted the workbench and metadata files and now the dbeaver is running is fine

**Comment by serge-rider** [comment]
Thanks for info.
Perhaps workspace was corrupted. However it is enought to delete just `.metadata` fodler - not entire workspace with configurations, scripts, etc

**Comment by alrsrinivas99** [comment]
Not able to upgrade to 5.1.1

![image](https://user-images.githubusercontent.com/15706477/41896268-c1182ad4-7941-11e8-8c55-128de452e9cc.png)

**Comment by serge-rider** [comment]
Looks like you have 32bit Java and running 64bit DBeaver.
Try to download 32 bit DBeaver or use installer (which is already bundled with JRE)
