### ISSUE TITLE
Idle cpu usage keeps growing, reproducible.

### ISSUE THREAD

**Issue by sjdrew** [dbeaver/dbeaver#3203]
On OSX idle cpu usage grows from about 1.5% when first launched to 8 to 10% after using it for a while.

DBeaver: 5.0.1 or any version of DBeaver (I have noticed this for a long time).
maxOS: High Sierra 10.13.3

Easy to reproduce.

Start DBeaver, see Activity monitor shows 1.5%, 40 threads, 80 idle wakeups per second.

Then:
1)  Open connection (local mysql) expand table list, select a table to "read data in sql".
2)  Close query window.
3)  Disconnect connection.
 
Now Activity Monitor shows: 44 threads 140 idle wakeups per second
 
Repeat steps above now Monitor shows 45 threads and 150 wakeups per second
 
Each time repeat seems to gain at least one thread and 10 more wakeups per second and more cpu usage.
 
After having DBeaver open for a few hours and normal use, by end of day cpu usage is up around 8% and hundreds of idle wakeups per second. (Not great if running on battery).
 
Closing down the program and starting again frees the resources.

**Comment by serge-rider** [comment]
I did localized this problem. Indeed every new SQL editor makes new thread (and doesn't terminate it after editor close). This thread doesn't consume much resources except thread itself.

Thanks for report!
