### ISSUE TITLE
PostgreSQL: include permissions in view DDL

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#3204]
Hi,

Would it be possible to add grants in views DDL for PostgreSQL?

Thanks in advance.

**Comment by liuyuanyuan** [comment]
@serge-rider  
1. Add grant SQL into getObjectDefinitionText of DBPScriptObject, or add a new interface class ?
2. I think COMMENT SQL also need to add, especially for table and view.

**Comment by serge-rider** [comment]
@liuyuanyuan That's a bit tricky, I think I'll add this feature in 5.0.5

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/39757189-c624f108-52d4-11e8-9277-ce228094d34d.png)
