### ISSUE TITLE
PostgreSQL: include permissions in schema DDL

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#3205]
Hi,

Would it be possible to add grants in schema DDL for PostgreSQL?

Thanks in advance.

**Comment by serge-rider** [comment]
Currently DBeaver doesn't support schema DDL at all. We need to support it first (and it is not clear what should it be - DDL of all schema objects or just schema create statement + permissions (like in pgAdmin).

**Comment by ururu-fy** [comment]
Please, vote for this feature. Grants like pgAdmin for PostgreSql in DBeaver is only what stop me to migrate on DBeaver. I hope in future all grants Postgres feature will be support in DBeaver.

**Comment by serge-rider** [comment]
I've added schema DDL similarly to pgAdmin (create + authorization).
Nested objects DDL (with permissions) isn't included.

**Comment by ced75** [comment]
Thanks!
