### ISSUE TITLE
PostgreSQL: include permissions in function definition

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#3206]
Hi,

Would it be possible to add grants in function definition?

Thanks in advance.

**Comment by serge-rider** [comment]
We need to support function permissions first.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/38769831-ec5e94a8-4011-11e8-8b45-a988ae82e189.png)

**Comment by ced75** [comment]
It works fine.
Thanks a lot!
