### ISSUE TITLE
Request: Order column of result

### ISSUE THREAD

**Issue by seantra94** [dbeaver/dbeaver#3207]
A *'Quality of life'* request. 
Say one is working with large data results, and want to compare values from two columns. 
Wouldn't it be great if one could just move the two columns aside each other and compare them visually.

Thanks for making an open source, awesome database administration tool!

**Comment by serge-rider** [comment]
This is already implemented. You can drag-b-drop columns (just drag column data type icon) or reorder them in results custom filters dialog (4th button after filter text).
