### ISSUE TITLE
[Bug] Dbeaver  shows  different column number type length  as the same (length 22)

### ISSUE THREAD

**Issue by ceyhunnabiyev** [dbeaver/dbeaver#3208]
Dbeaver shows  column number type length  only 22. I created column with type number(1) in another Database Tool. However dbeaver shows me number(22). Seems like Length column doesn't work properly.
I use Oracle Database.

**Comment by serge-rider** [comment]
Number length is always 22 in Oracle. I assume you mean precision and scale (number of integer and fractional digits). 
![image](https://user-images.githubusercontent.com/6398845/38292012-c1b199e6-37ea-11e8-904e-9f9db46bd268.png)

**Comment by ceyhunnabiyev** [comment]
@serge-rider, thank you for the answer. How create number size  that only satisfied digits(0-9).

**Comment by serge-rider** [comment]
Scale/precision edit support will be added in 5.0.3

**Comment by ceyhunnabiyev** [comment]
Thank you so much)).
