### ISSUE TITLE
How can I copy resultset metadata?

### ISSUE THREAD

**Issue by yanOnGithub** [dbeaver/dbeaver#3210]
Ctrl+A, Ctrl+C copied the text in the SQL editor. I would like to copy the resultset metadata. The resultset metadata is different from table metadata. I do not have access to user_tab_columns for resultsets.

![image](https://user-images.githubusercontent.com/25423046/37900046-a96e855a-311f-11e8-962d-3fd3085b847a.png)

**Comment by yanOnGithub** [comment]
I expected it to work like copying a rectangular region from excel. The clipboard should get a number of lines, columns separated by tabs. Then I could parse the clipboard text by cygwin getclip for the column name, data type, nullability, and other ResultsetMetadata. I could generate the source code for a POJO/JavaBean/Data transfer object.

**Comment by ryancabanas** [comment]
> I expected it to work like copying a rectangular region from excel. The clipboard should get a number of lines, columns separated by tabs. Then I could parse the clipboard text by cygwin getclip for the column name, data type, nullability, and other ResultsetMetadata. I could generate the source code for a POJO/JavaBean/Data transfer object.

On Windows, I managed to copy all of the Metadata doing the following:

1. Click on the first row.
2. Hold **Shift** and hold the down arrow to highlight all the records.
3. Press **Ctrl + Shift + F10** to bring up the right-click menu.
4. Click on **Copy selection**.

That will copy all the Metadata, minus the column headings, of course.

**Comment by yanOnGithub** [comment]
👍
