### ISSUE TITLE
Can't find bundle for base name com.amazon.redshift.core.messages

### ISSUE THREAD

**Issue by vinlopez** [dbeaver/dbeaver#3213]
Hi Serge,

I keep running into this very annoying error:
```
SQL Error [42601]: Error message not found: PG_GENERAL_ERR. Can't find bundle for base name com.amazon.redshift.core.messages, locale en_DE
  Error message not found: PG_GENERAL_ERR. Can't find bundle for base name com.amazon.redshift.core.messages, locale en_DE
    Error message not found: PG_GENERAL_ERR. Can't find bundle for base name com.amazon.redshift.core.messages, locale en_DE
    Error message not found: PG_GENERAL_ERR. Can't find bundle for base name com.amazon.redshift.core.messages, locale en_DE
```
Basically, none of the errors gets returned, only this message.

The connection is a Redshift using JDBC, and the locale en_US is set in the related datasource settings.

The ODBC.ini locale for redshift is also set to en_US.

I have no idea where this en_DE is coming from (although I live in Germany).

Any idea?

PS: thanks for the excellent work with DBeaver ;)

**Comment by serge-rider** [comment]
I assume that en_DE is your default locale. You can change it by adding these lines to the end of dbeaver.ini file:
```
-Duser.country=US
-Duser.language=en
```
