### ISSUE TITLE
mssql export creates invalid syntax

### ISSUE THREAD

**Issue by tony-gutierrez** [dbeaver/dbeaver#3214]
Exporting Azure mssql data results in:
`
INSERT INTO [ffctower-dev].dbo.airports (code,name,createdAt,updatedAt,startOffsetHrs,endOffsetHrs) VALUES 
('ATL','ATL',2018-03-26 16:04:40.867 +00:00,2018-03-26 16:04:40.867 +00:00,'-1','4')
`

Which fails on the dates at "16:"

**Comment by serge-rider** [comment]
We recently patched SQL generation routines so now they use native data formats.
This should be fixed in 5.0.4, please verify.
