### ISSUE TITLE
Problem of internationalization when package by maven

### ISSUE THREAD

**Issue by highgozhangyc** [dbeaver/dbeaver#3221]
I packaged dbeaver by maven,but there were some parts not be internationalized.Then I download the installer(zip) from site of dbeaver and opened it,i amost did not found something not be internationalized.So i want to ask what should i do during packging to solve this problem?

**Comment by serge-rider** [comment]
Standard Eclipse UI localization is provided by Babel package. 
Injecting Babel localizations is a part for DBeaver packaging project (installers, code sign and other stuff) which is no public domain.

**Comment by highgozhangyc** [comment]
@serge-rider Thanks for your reply.You means there should be some other operation for injecting babel localizations in dbeaver packaging project , but these operation can not be published . Could i understand like this?
Thanks again.

**Comment by highgozhangyc** [comment]
@serge-rider Thanks for your reply.You mean that there should be some other operation for injecting babel localizations in dbeaver packaging project , but these operation can not be published . Could i understand like this?
Thanks again.

**Comment by serge-rider** [comment]
Yes
