### ISSUE TITLE
SQL Editor does not go to position on PostgreSQL  errors

### ISSUE THREAD

**Issue by rngadam** [dbeaver/dbeaver#3222]
PostgresSQL 10
DBeaver 5.0.0

Executing queries creating function I get:

```
SQL Error [42601]: ERROR: syntax error at or near "743"
```

the error position is not highlighted, Doesn't seem to have a Goto position

WORKAROUND: copy query into another editor and use "Go to Position..." with the error message position number.

**Comment by rngadam** [comment]
I finally ended up debugging the same query with pgAdmin III and just figured out I had a ```END``` instead of ```END IF```.

Here's a simplified version of why I had such a hard time finding the issue (it seems to involved having two functions one after the other as if only one the position is correctly shown):

```
CREATE OR REPLACE FUNCTION some_other_function() RETURNS void AS 
$$
BEGIN
	NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION syntax_error() RETURNS void AS 
$$
BEGIN
	FOR i IN 1 .. 10
		LOOP 
		IF safe_cast('something', NULL::uuid) THEN 
			NULL;
		ELSIF NULL IS NOT NULL THEN
			NULL;
		END;
	END LOOP;
END;
$$ LANGUAGE plpgsql
```

## pgAdmin III LTS:
<img width="593" alt="screen shot 2018-03-27 at 1 11 34 pm" src="https://user-images.githubusercontent.com/538542/37947977-6db254c8-31c0-11e8-927a-cd52cc800586.png">

## DBeaver 5.0.0:

<img width="630" alt="screen shot 2018-03-27 at 1 10 53 pm" src="https://user-images.githubusercontent.com/538542/37947978-6de44d5c-31c0-11e8-92d1-89b5ac0673d7.png">

**Comment by serge-rider** [comment]
There are two different queries in your example.
Error positioned correctly if you execute these two queries one by one (<kbd>CTRL+Enter</kbd>) or in script mode (<kbd>ALT+X</kbd>).
I assume you executed them bot has a single statement (by selecting them and running with ctrl+enter).

**Comment by serge-rider** [comment]
BTW you can navigate quries with <kbd>ALT+Up</kbd> and <kbd>ALT+Down</kbd>

**Comment by rngadam** [comment]
@serge-rider ok, but I don't understand why it cannot position itself correctly on the error? to me, this still looks like a bug?

**Comment by serge-rider** [comment]
This is a kind of JDBC driver limitation. PostgreSQL driver provides error position in a query, not in whole script. I'm afraid I can't fix this.

**Comment by yonisade** [comment]
Then can you please add a manual "Go to position" option?

**Comment by apiszcz** [comment]
Also interested in a Goto Position offset for the SQL statement. Currently using NotePad++ go to offset feature 
Another bonus would be to highlight the position in the editor with an icon change/etc.
