### ISSUE TITLE
Options window pops up when I coly column name.

### ISSUE THREAD

**Issue by Retko** [dbeaver/dbeaver#3224]
Hello,

How can I limit this pop up please? It started to appear from version 5.
Thank you

**Comment by serge-rider** [comment]
This dialog was added a long time ago in some 4.x version. It can't be removed. Potentially it can be done by adding new cope command.

**Comment by Retko** [comment]
Hello, I didn't have this in version 4, just after updating to version 5 it appeared.
Can you please explain what is cope command, because I don't understand you response.
Thank you.

**Comment by serge-rider** [comment]
I meant we can add yet another Copy command (like "Copy with default parameters"). But I'm not sure we should, this may overcomplicate UI.
