### ISSUE TITLE
[Bug report] query data incorrect

### ISSUE THREAD

**Issue by hoyho** [dbeaver/dbeaver#3225]
query with SSMS
![image](https://user-images.githubusercontent.com/8370967/37962235-0c1c9c6e-31ed-11e8-88cb-0430f832b885.png)

however, when using dbeaver to query the same database
![image](https://user-images.githubusercontent.com/8370967/37962101-ab2d0cfe-31ec-11e8-90fe-c5f6aae9f54d.png)

**Comment by serge-rider** [comment]
From the screenshot I see that field with remarks is empty (also numeric field AccountStatus has value 0).
I can't reproduce that.
- What is your SQL Server version and what driver do you use (jTDS or Microsoft)?
- Dos this happen with all tables/columns or just in this particular case?

**Comment by hoyho** [comment]
@serge-rider   
product:Microsoft SQL Server Enterprise (64-bit)
OS: Microsoft Windows NT 6.2 (9200)
Version: 11.0.3000.0

driver jTDS 

as for question 2, i think it is not only this table,
i remember the scene was that i have some update operation in program but dbeaver didn't refresh

and this is not the first time!
i had met it before, that is Dbeaver  return 3 rows ,actually there's 4 rows .
but i didn't care so much.

maybe it will happen again very soon ,if so ,what should i do or what information i can collect

**Comment by serge-rider** [comment]
Have no idea so far. You could try Microsoft driver but I'm not sure it'll change anything.
I could expect that DBeaver handles Chinese text incorrectly but different numeric values make me think that this is something else.

> i remember the scene was that i have some update operation in program but dbeaver didn't refresh

This might be related to transactions (e.g. you were not in Auto Commit mode and thus you can't see changes made in other connection until you end (commit or rollback) your transaction.

**Comment by serge-rider** [comment]
Yep, jTDS is quite old driver and works incorrectly with some SQL Server versions.
Thanks for info
