### ISSUE TITLE
BUG: Firebird 3.x execute script SET TERM not working

### ISSUE THREAD

**Issue by NunzioModesto** [dbeaver/dbeaver#3228]
Hi, I am trying to execute a long script that has several statements and sometimes in the script a 
SET TERM ^ ; 
is required in order to create a stored procedure or a trigger.
The problem is that the script parser seems to recognize the new terminator and try to execute the statement, but it also include the terminator char in the statement and Firebird sql engine reports an error since the termination character is not supposed to be part of the statement

I don't know hot to solve this problem.

Thanks in advance.

**Comment by serge-rider** [comment]
It is a bug in new delimiter value extraction. 
Thanks for report
