### ISSUE TITLE
Deleting a Project?

### ISSUE THREAD

**Issue by brianspo** [dbeaver/dbeaver#3230]
How do I delete a project in 5.0.01?  I do not see a "Delete" option on the right-click menu:

![capture](https://user-images.githubusercontent.com/34524455/38045525-de407d08-3271-11e8-99dd-b308e5b40fa1.PNG)

**Comment by serge-rider** [comment]
You can't delete  active project (it is **bold**).
First you need to change active project (context menu->Set Active Project) and then you can delete it.

**Comment by brianspo** [comment]
Yes, that was it.  I made the General project the active one and I was able to delete the other one.  

Thanks for the help!  Is this in the category of "things people who use Eclipse regularly already know"? :-)

**Comment by lackovic** [comment]
> You can't delete active project (it is **bold**). First you need to change active project (context menu->Set Active Project) and then you can delete it.

Maybe this could be added to DBeaver Documentation [Deleting project](https://dbeaver.com/docs/wiki/Projects/#deleting-project) section: currently it is only stated at the top of the page and that can be easily missed when the reader is focused on deleting and is not reading the whole page.

**Comment by watery** [comment]
Or maybe, the 'Delete' menu entry may be present for the active project too, but disabled with a tooltip explaining what to do.
