### ISSUE TITLE
Feature request: Display trigger attribute in table's Properties tab, under Declaration window

### ISSUE THREAD

**Issue by DedicatedTools** [dbeaver/dbeaver#3235]
Using DBeaver 5.0.1 CE on PostgreSQL 9.6.3.
When a table's declaration window is opened (F4, Windows), in Properties tab, under Triggers sub-tab, it would help to see trigger's attribute(s), if any, as an additional column.

**Comment by serge-rider** [comment]
Good point.

![image](https://user-images.githubusercontent.com/6398845/39401049-382f9b1e-4b45-11e8-8826-1b573099bbaf.png)
