### ISSUE TITLE
Error creating read-only SQLite connection

### ISSUE THREAD

**Issue by jest** [dbeaver/dbeaver#3237]
I'm adding SQLite connection. On the last wizard screen there's a checkbox "Read-only connection". When it is checked, either clicking "Test connection" on the wizard, or connecting on created DB results in error:

```
Cannot change read-only flag after establishing a connection. Use SQLiteConfig#setReadOnly and SQLiteConfig.createConnection().
  Cannot change read-only flag after establishing a connection. Use SQLiteConfig#setReadOnly and SQLiteConfig.createConnection().
  Cannot change read-only flag after establishing a connection. Use SQLiteConfig#setReadOnly and SQLiteConfig.createConnection().
```

Unselecting "Read-only connection" allows to work normally on the connection.

DBeaver CE 5.0.1
SQLite driver 3.21.0

**Comment by serge-rider** [comment]
This seems to be SQLite driver limitation.
Fortunately there is a workaround (https://stackoverflow.com/questions/4574303/java-sqlite-how-to-open-database-as-read-only)

Thanks for report
