### ISSUE TITLE
OpenStreetMap view not displaying map when showing point with EPSG 32188 projection in DBeaver

### ISSUE THREAD

**Issue by czakaria** [dbeaver/dbeaver#32371]
### Description

In a Postgres/POSTGIS database, the map in the OpenStreetMap view does not display when we show a point with the 32188 projection in DBeaver.

### DBeaver Version

24.0.4.202405051837

### Operating System

macOS monterey 12.6.2

### Database and driver

PostgreSQL 13.14 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20), 64-bit

### Steps to reproduce

1. Create and connect to a PostGIS database.
2. Run the following query: `SELECT 'SRID=32188;POINT(294075.499183 5041320.944168)'::geometry;`
3. Double-click on the only entry in the result tab.
4. The spatial view will appear on the right, and you should see the point displayed on the map view, albeit without the OpenStreetMap layer.
<img width="1131" alt="Screen Shot 2024-05-13 at 11 00 35 PM" src="https://github.com/dbeaver/dbeaver/assets/22241576/e52c55a2-c800-4ef7-b3b0-667e952fd162">

### Additional context

I tested both 4326 and 3857 projections, and both worked perfectly.

```sql
SELECT 'SRID=4326;POINT(-73.631820 45.51615)'::geometry;
SELECT 'SRID=3857;POINT(-8196656.763401 5703149.381776)'::geometry;
```

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
From logs:
```
2024-05-14 14:01:01.045 - Cannot create a CoordinateOperation from :
[EPSG:32188] NAD83 / MTM zone 8
to :
[EPSG:4326] WGS 84
2024-05-14 14:01:01.045 - No transformation found from EPSG:32188 to EPSG:4326
```

**Comment by czakaria** [comment]
Hi @E1izabeth , thank you for your response. So, I assume that it's not a bug, but rather a feature that's not available, right?

**Comment by E1izabeth** [comment]
@czakaria I can't say for sure. This message is returned from the library we use.

**Comment by czakaria** [comment]
@E1izabeth Are you able to give me the name of the library used? I will do more research to understand by reading their documentation, and then maybe I can make a pull request if it's a problem that can be fixed.

**Comment by E1izabeth** [comment]
The message comes from this library https://github.com/orbisgis/cts

**Comment by czakaria** [comment]
This problem can't be fixed because all NAD83 projection are  not yet supported in [cts](https://github.com/orbisgis/cts). [see](https://github.com/orbisgis/cts/issues/145).

Thanks you @E1izabeth

**Comment by E1izabeth** [comment]
Thank you for investigation
