### ISSUE TITLE
BUG : Flat Files Separator is not correctly serialized

### ISSUE THREAD

**Issue by Neospiro** [dbeaver/dbeaver#3239]
Reproduce : 

- Create a flat files connection with a tabulation chr(9) separator
- Restart Dbeaver
- Open your flat files connection driver properties : the separator is now a space chr(20)

`5.0.1`

**Comment by uslss** [comment]
is it still actual?

**Comment by Neospiro** [comment]
no, it seems to have been fixed. Well done :+1:
