### ISSUE TITLE
[macOS] Auto-Refresh error

### ISSUE THREAD

**Issue by dsibiski** [dbeaver/dbeaver#3241]
I'm using DBeaver on macOS 10.12.6 with a Postgres db and when I try to set Auto-Refresh for a data view, I'm getting this error when the timer counts down and actually tries to perform the first refresh:

![screenshot 2018-03-30 11 38 47](https://user-images.githubusercontent.com/2922932/38143534-f48fe50a-340e-11e8-8eb0-1e4f500df8c3.png)

**Comment by serge-rider** [comment]
What is your DBeaver version?
I believe this bug was fixed in 5.0.1 or 5.0.2.

**Comment by dsibiski** [comment]
@serge-rider You're right, I upgraded to v5.0.2 and it works. Thanks!
