### ISSUE TITLE
MongoDB bad DBCException message

### ISSUE THREAD

**Issue by codebling** [dbeaver/dbeaver#3243]
In the data view filter bar, use the query `column='value1' OR column='value2'`

DBeaver shows the error `org.jkiss.dbeaver.model.exec.DBCException: Unsupported left operand: column = 'value1'`, but if you remove the simple query `column='value1'` works fine, it's in fact the `OR` that is unsupported. The error message is misleading. 

(As a feature request, it would be great if `OR` worked)

**Comment by serge-rider** [comment]
Yep, it is a bug in Mongo SQL parser.
Thanks for report.
