### ISSUE TITLE
update search_path more precisely

### ISSUE THREAD

**Issue by stefanrehm** [dbeaver/dbeaver#3244]
Hi Serge, 

related to https://github.com/dbeaver/dbeaver/issues/2501 and the emails we exchanged. In your words:

> I think this may be related: https://dba.stackexchange.com/questions/84804/hstore-type-does-not-exist-with-hstore-installed-postgresql
> This means that such error may occur if hstore can't be found because it's schema is not in the search_path. You could try to set search_path manually in the script right before your query.
> 
> If this will help then you can fix it in DBeaver. Most likely you have "default schema" option set (in connection properties, page General). DBeaver updates search_path when you change default schema.
> You can remove this option and set default schema in connection properties (property "currentSchema").
> And  if this will help then it makes sense to create a bug report. DBeaver should update search_path more precisely.

Since the original query already includes the correct schema (in bold below), I would assume that the search path would be updated automatically?

SELECT
so_order_number,so_sales_order_number,
* 
FROM **esprinter_data**.shipment_order
WHERE so_client_id=5076
AND (so_external_order_numbers->'sales')::text='5895368'

Thanks a lot for the help, and please keep working on DBeaver!

**Comment by serge-rider** [comment]
Agreed

**Comment by offstate** [comment]
This is a bad idea to change search_path automatically.
For example if I have extension 'intarray' installed in public schema and I execute the following query:
```
select * 
from product.product_rel
where rel=sort(array[182076099,4536557])
```
I receive an error that function  'sort' doesn't exists.
Or maybe there should be some config where I could set mandatory schemas. 
For example "public" instead of "$user"

**Comment by serge-rider** [comment]
I've committed the fix.
DBeaver will keep all original schemas in search_path. 
New default schema will be added in the beginning of search_path.
