### ISSUE TITLE
Dump Database not functioning

### ISSUE THREAD

**Issue by arpoodle** [dbeaver/dbeaver#32457]
### Description

Attempting to dump a database using DBeaver, clicking start results in the dump window flickering, unresponsive and closing the whole program results in this error :  ![image](https://github.com/dbeaver/dbeaver/assets/31689926/b7b89855-e69f-4965-a9a4-17ce12a94409)

### DBeaver Version

Community 24.0.4.202405051837

### Operating System

Windows 11

### Database and driver

MySQL 5.7

### Steps to reproduce

Connect to DB
Highlight DB and select 'dump database' from tools
Select the DB and tables to dump and click 'start'

### Additional context

going via SSH tunnel

**Comment by arpoodle** [comment]
Using different clients result in the same outcome

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
