### ISSUE TITLE
Вопрос о развитии проекта (The question of development project)

### ISSUE THREAD

**Issue by sgrinko** [dbeaver/dbeaver#3246]
Текущее понятие проекта в DBeaver слишком примитивно...
Нужна полноценная работа в проекте с отдельными объектами БД - 1 объект 1 файл (таблица, представление, функция...), рефакторинг, поддержка разных версий (столько же сколько и поддерживает сообщество).
То есть проект - это описание всех необходимых объектов для того, чтобы по ним сформировать полноценную схему БД в виде скрипта.
Проект должен уметь создаваться из БД, то есть реверс-инженеринг должен быть.

Проект нужно сравнивать с БД и по найденным различиям формировать скрипт наката в БД и также уметь из БД портировать изменения в проект (знаю, что это стоит в планах...но боюсь что немного не так как ожидается). 
Очень желательно иметь возможность сохранять авторское форматирование (которого нет в постгрессе), чтобы при сравнении кода из проекта и кода из БД в данном случае не находить отличий (здесь есть 2 варианта реализации, у каждого свои плюсы и минусы, если интересно, то опишу).
В проекте нужна синтаксическая поддержка кода (избегать хотя бы грубых ошибок), чтобы можно было в нём писать код.

Ну и конечно всё это в Community Edition... :)
понимаю, что по сути я прошу полноценную IDE... но вы ведь уже так много сделали для этого!
В общем можно озвучить планы в отношении именно проекта нужного вида?
Меня интересует только PostgreSQL, так как для многих других БД такое понимание проекта уже есть в других продуктах.

ENG
--
The current project concept in DBeaver is too primitive ...
Need full-fledged work in the project with separate database objects - 1 object 1 file (table, view, function ...), refactoring, support for different versions (as many as the community supports).
That is, the project is a description of all the necessary objects in order to form a complete database scheme in the form of a script on them.
The project should be able to be created from the database, that is, reverse engineering should be.

The project needs to be compared with the database and, based on the differences found, form the back-end script in the database and also be able to port the changes to the project from the database (I know that this is in the plans ... but I'm afraid that it's not as expected).
It is very desirable to be able to save the authoring formatting (which is not present in the postgrace) so that when comparing the code from the project and the code from the database in this case, there are no differences (here there are 2 options for implementation, each has its pros and cons, if interested, I will describe) .
The project needs syntactic code support (avoid at least gross errors), so you can write code in it.

And of course it's all in the Community Edition ... :)
I understand that in fact I'm asking for a full-fledged IDE ... but you already did so much for this!
In general, it is possible to sound plans for the particular project of the required kind?
I'm only interested in PostgreSQL, since for many other databases this understanding of the project already exists in other products.

**Comment by efradkin** [comment]
@sgrinko слова не мальчика, но программиста ;-)

**Comment by infectormp** [comment]
@sgrinko как говорится `feel free to make PR`

**Comment by sgrinko** [comment]
Ребята, мне всё же хотелось бы услышать от вас что-то по делу :)

ENG

Guys, I still would like to hear from you something on the case :)

**Comment by sgrinko** [comment]
Я понял, что вы двигаетесь в другом направлении.
Пока наиболее подходящим для моих целей является проект "pgcodekeeper" (есть на github).
Конечно им также ещё много чего есть улучшать, однако они идут именно в сторону IDE (хоть до этого ещё и далеко).
Я очень надеялся услышать, что у вас в планах это есть...
Спасибо за ответ.
issue можно закрыть.

ENG

I realized that you are moving in a different direction.
While the most suitable for my purposes is the project "pgcodekeeper" (there is on github).
Of course they also have a lot more to improve, but they are heading towards the IDE (although this is still far off).
I really hoped to hear that you have it in your plans ...
Thanks for the answer.
issue can be closed.
