### ISSUE TITLE
SSHJ fails to open tunnel, dependency error

### ISSUE THREAD

**Issue by tprobinson** [dbeaver/dbeaver#3247]
Platform:
* Dbeaver CE 5.0.2
* SSHJ 1.0.1
* Ubuntu 16.04 x64
* Java 1.8.0_144-b01

When attempting to open a tunnel with an ed25519 key, I get the following error:
```
net/i2p/crypto/eddsa/math/Curve
  net.i2p.crypto.eddsa.math.Curve cannot be found by com.hierynomus.sshj_0.23.0
```

If there's any other information I can provide, please let me know.

**Comment by zman0900** [comment]
Looks like I am having the same issue.

Using new SSHJ plugin with ed25519 private key fails with error:

    net/i2p/crypto/eddsa/math/Curve
      net.i2p.crypto.eddsa.math.Curve cannot be found by com.hierynomus.sshj_0.23.0
      net.i2p.crypto.eddsa.math.Curve cannot be found by com.hierynomus.sshj_0.23.0

SSHJ works fine with an RSA key.  This is on MacOS 10.13.3 with DBeaver 5.0.2 from pkg installer. SSHJ 1.0.1.

Key is valid and works for logging in through shell:

    $ ssh-keygen -lf ~/.ssh/id_ed25519
    256 SHA256:<redacted> (ED25519)

**Comment by serge-rider** [comment]
Thanks for report

**Comment by serge-rider** [comment]
Looks like i2p Maven artifacts can't be repackaged into OSGI bundles (at least easily). Export packages are missing or incorrect.
So we'll need to repackage all SSHJ dependencies as a separate bundle (similar to POI and Batik).
