### ISSUE TITLE
Unable to show the synonym

### ISSUE THREAD

**Issue by aloon9999** [dbeaver/dbeaver#3249]
Enable to see the synonym in Database Navigator even it is available. It is confirm exist by selecting from the system table ALL_SYNONYMS. The synonyms is shown in Oracle SQL Developer.

![capture](https://user-images.githubusercontent.com/38023062/38236631-61106fc4-3757-11e8-99d4-cc37a9c350db.JPG)

**Comment by serge-rider** [comment]
Public synonyms are in Global metadata->Public Synonyms path (the same about public db links).
This is not very obvious. Perhaps it is better to have PUBLIC schema but it is quite specific..

**Comment by aloon9999** [comment]
I have check the Global metadata but i do not see the synonym appear in the Global Metadata tree.  i create a non-public synonym, i expect to see it under my schema but it does not show up too.

Capture1.jpg Not able to see under Global Metadata
![capture1](https://user-images.githubusercontent.com/38023062/38344309-7db32620-38bb-11e8-9f58-5e762a67a09d.JPG)
Capture2.jpg Not able to see under specific schema.
![capture2](https://user-images.githubusercontent.com/38023062/38344310-813a5c00-38bb-11e8-9fcc-69eb4fc673be.JPG)

.

**Comment by serge-rider** [comment]
According to select results above your synonym reside in PUBLIC schema.
It is no it particular schema. To see public synonyms check this:
![image](https://user-images.githubusercontent.com/6398845/38392385-fffd2e04-392f-11e8-82d9-56e3c2ebe2dd.png)

**Comment by aloon9999** [comment]
I did not see the public synonym appear in TYPE tree either. May i know what i expect to see, is it the synonym name?
![capture3](https://user-images.githubusercontent.com/38023062/38399126-f9444f02-397a-11e8-8268-a05d3f3f1cb1.JPG)

Secondly what about the synonym with specific schema and not public that i have defined, may i know where can i see it.

**Comment by serge-rider** [comment]
You can see all synonyms but PUBLIC in their schemas->Synonyms.
And you can see PUBLIC synonyms in Global Metadata->Public synonyms (why TYPE?)

To read synonyms DBeaver uses this query:
```sql
SELECT s.*,O.OBJECT_TYPE 
FROM ALL_SYNONYMS S, ALL_OBJECTS O
WHERE S.OWNER=? AND O.OBJECT_TYPE NOT IN ('JAVA CLASS','PACKAGE BODY')
AND O.OWNER=S.TABLE_OWNER AND O.OBJECT_NAME=S.TABLE_NAME
ORDER BY S.SYNONYM_NAME
```

**Comment by aloon9999** [comment]
I have check and unfortunately it does not work.
The query show there are 2 synonyms created.
![capture1](https://user-images.githubusercontent.com/38023062/38409367-bfa018e2-39b3-11e8-8b6d-e461583f3482.JPG)

However when i use query that provided above also no result return.
![capture2](https://user-images.githubusercontent.com/38023062/38409374-c6f1ee9a-39b3-11e8-8162-9c064afcbdc8.JPG)

**Comment by aloon9999** [comment]
After i try with the provided query, i found something wrong with the query to get the synonym.
![capture3](https://user-images.githubusercontent.com/38023062/38409543-668a6edc-39b4-11e8-9481-cc62cd11997f.JPG)
1. Firstly the query to get synonym should get the O.OBJECT_NAME=S.SYNONYM_NAME and not O.OBJECT_NAME=S.TABLE_NAME.
2. The object owner does not always same as  table owner, hence condition O.OWNER=S.TABLE_OWNER is not valid too.
3. Last but not least, i cannot get the public synonym either, i believe the query to get the public synonym also need to modified.

**Comment by serge-rider** [comment]
Good point.
I've just committed the fix.
Please try this in EA version: https://dbeaver.jkiss.org/files/ea/

**Comment by serge-rider** [comment]
@p91paul Yep, also a good point. I forgot about permissions.
But I don't understand this outer join. Synonym doesn't make sense if we can't get it's target object (which is resolved by OBJECT_TYPE).

**Comment by aloon9999** [comment]
@p91paul, may i know what about the permission that you refer to. I can select from the the synonym, i can also see the synonym in Oracle SQLDeveloper as mention in my first post.  Can you elaborate more  what else can i investigate. 
By the way, the synonym that i create is from another oracle database that exist in different host, just to clarify this point.

**Comment by p91paul** [comment]
@serge-rider Oracle allows creation of synonyms to non existent objects. They may be invalid or make no sense to exist, but they are in database and they should be shown.

@aloon9999 case is quite different, because the object exists in _another database_ reached through a dblink. To get the object type you should query the remote all_objects view using the dblink (i don't even know if that's feasible); however the outer join would serve at least the purpose of showing them in the synonyms list.

**Comment by aloon9999** [comment]
@serge-rider, may i confirm if you going to revert the fix? If you revert then i not going to see the synonym.

I try the newly propose SQL by @p91paul, it work for my case and i can see the result for both public and schema Synonym. 
**********************************
SELECT owner, synonym_name, max(table_owner), max(table_name), max(db_link), max(object_type) from (
SELECT s.*, NULL OBJECT_type FROM all_synonyms s
UNION all
SELECT s.*,O.OBJECT_TYPE  FROM ALL_SYNONYMS S, ALL_OBJECTS O
WHERE 
O.OBJECT_TYPE NOT IN ('JAVA CLASS','PACKAGE BODY')
AND O.OWNER=S.TABLE_OWNER AND O.OBJECT_NAME=S.TABLE_NAME
) WHERE synonym_name LIKE 'ERP%'
GROUP BY owner, synonym_name
ORDER BY SYNONYM_NAME;
**********************************

**Comment by serge-rider** [comment]
@aloon9999 Agreed about broken synonyms. We must show them.

But I still have some concerns about performance. 
Anyhow, let's try this is new EA version (the same location).
