### ISSUE TITLE
PostgreSQL отладка, как стартовать? (Debug: How to start?)

### ISSUE THREAD

**Issue by sgrinko** [dbeaver/dbeaver#3261]
На мой вопрос об этом в задаче 2556 я получил ответ:

1.     open the procedure from the "Databases" view
2.     switch to "Sources" tab
3.     enable the "Omit procedure header" to sync line numbers #3257
4.     Use "Debug As" -> "PL/pgSQL Procedure" context menu item to configure and launch the debug

не могу выполнить пункт 4, так как в контекстном меню у меня нет такого пункта:
![default](https://user-images.githubusercontent.com/10084993/38304424-18258478-3812-11e8-90a1-1c51d398772d.png)
что я делаю не так, как всё же активировать режим отладки?
PS. если можно, то напишите ответ по русски.

ENG

To my question about this in task 2556, I received the answer:

1.     open the procedure from the "Databases" view
2.     switch to "Sources" tab
3.     enable the "Omit procedure header" to sync line numbers #3257
4.     Use "Debug As" -> "PL/pgSQL Procedure" context menu item to configure and launch the debug

I can not execute item 4, because I do not have such an item in the context menu:
![default](https://user-images.githubusercontent.com/10084993/38304424-18258478-3812-11e8-90a1-1c51d398772d.png)

What am I doing wrong, how can I activate the debugging mode?

**Comment by ruspl-afed** [comment]
Sorry for not highligting the prerequisite covered by #3255 , 
Please switch the perspective to "Debug"first : this will enable the platform debug capabilities.
You can do it via main menu "Window -> Perspective -> Open Perspective" for example

**Comment by sgrinko** [comment]
Я переключался на "Debug" перспективу, но это никак мне не помогает.
Что ещё не хватает?
На самом кластере всё, что нужно для отладки стоит.
![default](https://user-images.githubusercontent.com/10084993/38350008-31d50a4c-38b2-11e8-9dcc-fda3d732163d.png)

PgAdmin III успешно выполняет отладку...
![default](https://user-images.githubusercontent.com/10084993/38350100-8b322fd4-38b2-11e8-997a-8f3093be950a.png)

**Comment by ruspl-afed** [comment]
Hmm, do you have this instaled? https://marketplace.eclipse.org/content/dbeaver-sql-debugger

**Comment by sgrinko** [comment]
Я только лишь скачал и установил версию: Windows 64 bit (installer + JRE)
В этой версии нет Marketplace как и я не нашел в списке такого плагина dbeaver-sql-debugger
Очень не хотелось бы устанавливать весь Ecipse и ставить в него DBeaver как плагин.
Как это сделать в рамках текущей инсталяции?

**Comment by ruspl-afed** [comment]
@serge-rider , do we have a possibility to install marketplace features to DBeaver CE?

**Comment by ruspl-afed** [comment]
Interesting, there is link to marketplace, but there is no marketplace client inside
Looks like one need to do some extra steps.

Please go to the Help->Install New Software
And add another update site with URI "https://dbeaver.jkiss.org/update/debug/latest/", like
![image](https://user-images.githubusercontent.com/15242312/38362459-976355d6-38d9-11e8-839e-2c0786ee3f34.png)

Then you need to install it via
![image](https://user-images.githubusercontent.com/15242312/38362654-4da91ec0-38da-11e8-97eb-f70f2fd61cb0.png)
And it should be available after restart

**Comment by sgrinko** [comment]
Error:
![default](https://user-images.githubusercontent.com/10084993/38372924-a0121b9e-38f8-11e8-840b-43b15b235b54.png)

An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.apache.commons.cli,1.3.1
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ce.feature,5.0.2
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ce.nls.feature,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core.application,5.0.2
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core.application.nls,5.0.2
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core.nls,5.0.2
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.db2.nls,1.0.12
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.db2.nls.feature,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.derby.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.erd.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.exasol.nls,1.0.12
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.exasol.nls.feature,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.firebird.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.generic.nls,1.0.12
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.generic.nls.feature,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.h2.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.hsqldb.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.import_config.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.informix.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.mssql.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.mysql.nls,1.0.12
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.mysql.nls.feature,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.netezza.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.oracle.nls,1.0.12
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.oracle.nls.feature,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.phoenix.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.postgresql.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.sample.database,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.sample.database.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.sqlite.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.teradata.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.ui.locks.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.vertica.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.wmi.nls,1.0.12
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.wmi.nls.feature,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.model.nls,1.0.12
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.rcp.feature,2.1.55
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.rcp.nls.feature,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.runtime.ide.core.nls,1.0.12
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.runtime.nls.feature,1.0.12
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.standalone.feature,5.0.2
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.standalone.nls.feature,1.0.12
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ui.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.utils.nls,1.0.12
No repository found containing: osgi.bundle,org.jkiss.wmi.nls,1.0.12

**Comment by sgrinko** [comment]
может быть будет проще этот плагин включить в сборку заранее?

**Comment by serge-rider** [comment]
Well, there are two different issues here.
1. To be able to install extension you have to install DBeaver in some non-write protected folder (e.g. not in Program Files on Windows). Errors you see are result of inability of Eclipsep platform to install new plugins.
2. CE version isn't bundled with Marketplace. You can use Install New Software menu.
All this stuff is described here: https://github.com/dbeaver/dbeaver/wiki/Optional-extensions

**Comment by sgrinko** [comment]
Мне удалось установить плагин через запуск под администратором. Согласен, что это было не очевидно... и стоило обратить на это внимание сразу.
![default](https://user-images.githubusercontent.com/10084993/38408120-d6af8af6-3984-11e8-880c-22adad60f8d1.png)
Однако после попытки старта отладки, что-то всё же идет не так:
![default](https://user-images.githubusercontent.com/10084993/38408209-34716416-3985-11e8-822a-3d8a8d726670.png)
возможно, что проблема состоит в том, что я использую SSH тунель который стоит снаружи программы DBeaver  и поэтому не удается установить коннект.... я прав?
![default](https://user-images.githubusercontent.com/10084993/38408283-8bb520fa-3985-11e8-895a-5a5df41f7939.png)
?
PS. Пожалуйста пишите по русски тоже ответ.

ENG

I was able to install the plug-in by running under the administrator. I agree that it was not obvious ... and it was worth paying attention to it right away.
![default](https://user-images.githubusercontent.com/10084993/38408120-d6af8af6-3984-11e8-880c-22adad60f8d1.png)
However, after trying to start debugging, something still goes wrong:
![default](https://user-images.githubusercontent.com/10084993/38408209-34716416-3985-11e8-822a-3d8a8d726670.png)
it's possible that the problem is that I'm using an SSH tunnel that stands outside the DBeaver program and therefore can not connect .... I'm right?
![default](https://user-images.githubusercontent.com/10084993/38408283-8bb520fa-3985-11e8-895a-5a5df41f7939.png)

**Comment by sgrinko** [comment]
Я попробовал переключиться на SSH тоннель через интерфейс программы, но запустить отладку так и не удалось.

ENG

I tried switching to the SSH tunnel through the program interface, but I could not start the debugging.

**Comment by serge-rider** [comment]
It should work (and it works) with SSH tunnel. Most of our test databases are remote and use SSH all the time.
We have brand new WIKI article about PG debugger: https://github.com/dbeaver/dbeaver/wiki/PGDebugger

(sorry, it takes too much time to write messages in two languages, so let's use the one which is understandable by the most users)

**Comment by sgrinko** [comment]
Я попробовал переключиться на SSH тоннель через интерфейс программы, но запустить отладку так и не удалось.

ENG

I tried switching to the SSH tunnel through the program interface, but I could not start the debugging.

**Comment by sgrinko** [comment]
В конце-концов мне удалось запустить отладчик.
Конечно мне очень помогло описание в wiki, спасибо!
Надеюсь, что в будущих версиях вы существенно облегчите этот процесс и он станет таким же простым как в PgAdmin III
issue можно закрыть

ENG

In the end, I managed to start the debugger.
Of course I was very helped by the description in the wiki, thanks!
I hope that in future versions you will greatly facilitate this process and it will become as simple as in PgAdmin III
issue can be closed

**Comment by serge-rider** [comment]
Great.
Yep, we are working on that. Hopefully PG debugger will become fully functional till 5.1 release. And we'll include it in DBeaver CE distribution.
Thanks for testing.
