### ISSUE TITLE
Can't connecting to IPv6 PostgeSQL 

### ISSUE THREAD

**Issue by ofersapir6** [dbeaver/dbeaver#3262]
Is there IPv6 support for a PostgeSQL connection? 
I am using v5.0.2 on mac.

("sqlpro for postgres" downloaded from appstore works fine with the same hostname&port). 

Thanks

Test connection error response looks like this - 

Connection to **********:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
  Connection to **********:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
    No route to host (connect failed)
    No route to host (connect failed)

**Comment by ofersapir6** [comment]
I tried using an IPv6 address (the hexadecimal quartets w/ colons format) & tried using a hostname (which is an AAAA record) - I get the same error for both.

Thank you for looking into this

**Comment by serge-rider** [comment]
Could you try to enclose host name/IP in brackets like [::1]
(https://jdbc.postgresql.org/documentation/80/connect.html)

**Comment by ofersapir6** [comment]
I saw that one & tried the brackets - I receive the same error. 

Thanks

**Comment by serge-rider** [comment]
Have no idea so far. IPv6 addresses work fine in our test env.

You could check this: https://stackoverflow.com/questions/20825734/postgresql-connection-refused-check-that-the-hostname-and-port-are-correct-an
Maybe this somehow related to server config.
