### ISSUE TITLE
feature request:  allow user to change auto-completion key

### ISSUE THREAD

**Issue by ccurvey** [dbeaver/dbeaver#3264]
I'd really like to be able to change the auto-completion key from "return" to "tab".  That way it will work the same as my other editors, and my shells.

**Comment by serge-rider** [comment]
I'm afraid it will be very hard to implement. Current behavior (including shortcuts) is hardcoded in Eclipse platform.

**Comment by serge-rider** [comment]
Duplicate of #2316
