### ISSUE TITLE
JSON editor for RDB

### ISSUE THREAD

**Issue by Phunkafizer** [dbeaver/dbeaver#3265]
Is it possible to

- prettify JSON viewer for blob fields? (indention)
- view w/o JSON specific escape characters? In my example only "/dev/ttyS1" should be visible

Using EE 5.0.1

![grafik](https://user-images.githubusercontent.com/1410717/38361822-fcf3f0aa-38ce-11e8-9fb1-bc81fefd635f.png)

**Comment by serge-rider** [comment]
Pretty formatting will be applied automatically if you use panel value viewer. Click on cell value and press F7 (or click on Panels button).

![image](https://user-images.githubusercontent.com/6398845/38471357-c39de3b8-3b78-11e8-8043-a16318ea2d23.png)
