### ISSUE TITLE
Postgres schema name does not show on ERD.

### ISSUE THREAD

**Issue by gerhardcit** [dbeaver/dbeaver#3266]
The schema name is not shown on the object in the ERD. It's only visible on the tooltip.
The ERD is created in a project. (The only way to see different schema tables in the same ERD)

In the attached image, schema1.table1  and schema2.child is depicted. But the schemas are not visible in the design.

<img width="380" alt="no-schema-on-erd" src="https://user-images.githubusercontent.com/5508278/38362421-1c2cdc32-38d1-11e8-91d1-b2af1a6c62c1.png">

**Comment by serge-rider** [comment]
We can add extra ERD config option (in addition to attributes visibility and layout) to show FQ table names.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/38473041-a8c137c0-3b91-11e8-894a-3742ee7eae7b.png)
