### ISSUE TITLE
DBeaver is acting strange when showing/saving/updating multibyte characters in json field

### ISSUE THREAD

**Issue by Markussss** [dbeaver/dbeaver#3267]
I have only tested this with special Norwegian letters (æ, ø, å), a Chinese letter (汉) and a few emojis (😀 😁 😂 🤣 😃 😄).

1. I start by saving the following as a json field in a table with charset: utf8mb4, collation: utf8mb4_unicode_ci:
`{"test": "æ ø å 汉 😀 😁 😂 🤣 😃 😄"}`

2. When refreshing the data in the view (by pressing F5), the view of the field changes to:
`{"test": "Ã¦ Ã¸ Ã¥ æ± ð ð ð ð¤£ ð ð"}`

3. Updating the field, by adding ' test' to the end of the field:
`{"test": "Ã¦ Ã¸ Ã¥ æ± ð ð ð ð¤£ ð ð test"}`

4. Refreshing the data in the view shows all multibyte characters getting some extra bytes:
`{"test": "ÃÂ¦ ÃÂ¸ ÃÂ¥ Ã¦Â±Â Ã°ÂÂÂ Ã°ÂÂÂ Ã°ÂÂÂ Ã°ÂÂ¤Â£ Ã°ÂÂÂ Ã°ÂÂÂ test"}`

5. Now, removing the ' test':
`{"test": "ÃÂ¦ ÃÂ¸ ÃÂ¥ Ã¦Â±Â Ã°ÂÂÂ Ã°ÂÂÂ Ã°ÂÂÂ Ã°ÂÂ¤Â£ Ã°ÂÂÂ Ã°ÂÂÂ"}`

6. And updating:
`{"test": "ÃÂÃÂ¦ ÃÂÃÂ¸ ÃÂÃÂ¥ ÃÂ¦ÃÂ±ÃÂ ÃÂ°ÃÂÃÂÃÂ ÃÂ°ÃÂÃÂÃÂ ÃÂ°ÃÂÃÂÃÂ ÃÂ°ÃÂÃÂ¤ÃÂ£ ÃÂ°ÃÂÃÂÃÂ ÃÂ°ÃÂÃÂÃÂ"}`

The updates to the database in step 3 is kind of destructive, as it renders all multibyte characters unreadable for other applications.

If I do not touch the fields from DBeaver, the json fields will behave properly in my application (although, not display properly in DBeaver). If I update the fields from outside DBeaver, the json fields will behave properly and just display the correct characters.

**Comment by serge-rider** [comment]
This looks like some server/connection misconfiguration. Will try to reproduce this on server with utf8mb4 charset.
BTW check this: https://stackoverflow.com/questions/44591895/utf8mb4-in-mysql-workbench-and-jdbc
