### ISSUE TITLE
DB2 - Showing Null Result when column is not null

### ISSUE THREAD

**Issue by rfranchi** [dbeaver/dbeaver#3269]
When I execute a query on Dbeaver 5.0.2, database DB2 - Connection DB2 / DB2 LUW (tested on other connections settings too), I have the result set with Null Column but the column is not null.

Database: DB2
Column Type: VARCHAR2

![db2_dbeaver_problem](https://user-images.githubusercontent.com/1450286/38367520-4a9cd990-38b9-11e8-9ab2-76797bce49aa.JPG)

Thank you.

**Comment by serge-rider** [comment]
How do you know it is not NULL?
Could you check error/debug logs (maybe something is failing during value reading) https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by titou10titou10** [comment]
`"VARCHAR2"` is an Oracle data type, not a native DB2 one
Could you confirm that DB2 is configure in "Oracle compatibility mode" and tell us what is the value of the `"DB2_COMPATIBILITY_VECTOR"` registry variable and the `"varchar2_compat"`db configuration param in your case?
Thanks 
Denis

**Comment by rfranchi** [comment]
Thank you for the responses.

@serge-rider in the print the query filter by not null column (SELECT * FROM dbprod.ESPDE_MDICA WHERE iespde is NOT NULL) and dbeaver show the result.

I think you solve the mistery. On error dialog it shows: ERRORCODE=-4220 java.io.CharConversionException occurs when accessing DBCS data from a JDBC application running under JRE 1.8+. Looking the page http://www-01.ibm.com/support/docview.wss?uid=swg21982529 it seems the solutions is to update the jdbc driver. It works now.

Thank you all.

**Comment by serge-rider** [comment]
Thanks for details
