### ISSUE TITLE
Feature Request: IAM Authentication to RDS

### ISSUE THREAD

**Issue by benyanke** [dbeaver/dbeaver#3270]
Currently, AWS RDS allows users to connect with IAM credentials, so that you can centrally manage permissions. However, this occurs using temporary tokens which only last 15 min.

I have not found a single GUI app which can support IAM tokens, so this could also be a big value add for RDS.

Here's an example bash script which I use to open a database connection using the mysql terminal tool:

```
#!/bin/bash

username="HERE"
hostname="INSTANCE-NAME.INSTANCE-ID.us-east-2.rds.amazonaws.com"
port="3306"
rootCerts="https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem"
rootCertLocalPath="/tmp/rdscerts.pem"

echo "Getting token";
token=$(aws rds generate-db-auth-token  --hostname $hostname --port $port --region us-east-2  --username $username)


if [ ! -f "$rootCertLocalPath" ]; then
    echo "Getting certs"
    curl "$rootCerts" > "$rootCertLocalPath"
fi

echo "Connecting with token..."

mysql --host="$hostname" --port="$port" --ssl-ca="$rootCertLocalPath" --enable-cleartext-plugin --user="$username" --password="$token"

```

This, of course, uses the two pieces of an IAM credential behind the scenes: key id and secret key.

It would be amazing if this functionality would be implemented directly into dbeaver, ether reading the aws keys from env vars (as most tools do), or even allow them to be specified. This would allow me to push our company to use more secure DB extensions, and also to use dbeaver!

**Comment by serge-rider** [comment]
This is very possible to support using AWS Java SDK (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.Java.html)

However it is not so easy to test (at the moment we do not have live instance of RDS, especially with IAM authentication).
Also, implementing this will require special extension for MySQL. Not big deal but still.

**Comment by landsman** [comment]
First step: allow using pem key in SSH Tunnel for login. There is just Authentication Method: Public Key which wants Passphrase after I tried test connection with pem key.

**Comment by vonkinder** [comment]
I don't see a big issue with the test. It will be mandatory to use the aws sdk to generate the token. On my tests the problem sits on the length of the token/password I assume. I'm getting a valid token to be used as a password from AWS CLI working on a shell script but it's not working on the dbeaver connection test. @landsman you need to use the rds-combined-ca-bundle.pem on an standard tcp/ip->SSL, SSL CA File connection, but then it's not possible to connect because the token seems to be not valid there.

**Comment by CloudOpsMHG** [comment]
Any updates for this feature request?

**Comment by durchgedreht** [comment]
Would be interested in an update as well. Can also test new versions as I'm working on AWS anyway. It somehow feels like in the 90s not being able to use the most common cloud service around (applies to all UIs, but DBeaver is my goto tool).

**Comment by serge-rider** [comment]
AWS SDK is huge, we include it only in DBeaver EE.
Potentially it is possible to implement it in a pure Java/HTTP calls.

Scheduling to 6.2.2.

**Comment by durchgedreht** [comment]
Thanks for the quick response. Are you saying there's IAM support in the EE edition (couldn't find anything in the docs)?

Or are you saying you are considering adding IAM in a basic version?
And thanks for all the great work!

**Comment by gjunqueira** [comment]
The proposed feature would be a great addition to DBeaver!

We are enforcing our security policies in our startup and the developers are very found of DBeaver, but it will mandatory for us to use RDS IAM authentication, so I won't have to ditch DBeaver if this comes in effect.

Please, please, please implement this! :)

**Comment by marc-mabe** [comment]
As another idea: This could also be done using a custom shell command execution before open connection and be able to use result somehow as password. This would at least remove the need to include aws java sdk and it could also be useful for other features like we use aws-vault to connect to multiple aws accounts.

**Comment by maratkalibek** [comment]
This feature will be released in next DBeaver EE version. Both for MySQL and PostgreSQL.

**Comment by CloudOpsMHG** [comment]
Is there an ETA on release?

**Comment by serge-rider** [comment]
@CloudOpsMHG It will be included in 7.1, release planned on early June. 

Meanwhile you can test this feature in the Early Access version (https://dbeaver.com/files/ea). 
Feel free to create bug reports on it or create support tickets on dbeaver.com.

**Comment by MightyCrabKing** [comment]
@serge-rider Thanks i have just tried to configure this using a postgresql connection on the latest EA release, however i don't see an option for how this is configured. Is any documentation available as to how to get this hooked up?

**Comment by serge-rider** [comment]
@MightyCrabKing 
![image](https://user-images.githubusercontent.com/6398845/79635224-680d9280-8178-11ea-982c-f9314314c5c9.png)

**Comment by serge-rider** [comment]
@MightyCrabKing 
Sorry, there was a mess with latest EA, it still didn't include IAM auth model. Now it does:
![image](https://user-images.githubusercontent.com/6398845/79635224-680d9280-8178-11ea-982c-f9314314c5c9.png)

**Comment by alexpetralia** [comment]
Thanks for adding this feature! Quick question - does this permit only the [default] profile in `~/.aws/credentials`? Is there any possibility to specify local/dev/prod profiles? Thanks Serge.

**Comment by thomastownsend** [comment]
What version is this in ?  I am using Windows 10 - Version 7.1.0.202006031909 and it's not there. Not sure how to update this version as its windows app?

**Comment by mattdodge** [comment]
@thomastownsend Make sure you are using the EE edition and not community edition. The AWS IAM auth method is an enterprise feature.

**Comment by thomastownsend** [comment]
So I can’t test it unless I pay for the Enterprise version - that’s sad!

Sent from my iPhone - please excuse 
typos

**Comment by karpov-denys** [comment]
> @MightyCrabKing
> Sorry, there was a mess with latest EA, it still didn't include IAM auth model. Now it does:
> ![image](https://user-images.githubusercontent.com/6398845/79635224-680d9280-8178-11ea-982c-f9314314c5c9.png)

Hi, @serge-rider. Is this feature a part of prepaid version?

**Comment by karpov-denys** [comment]
> Currently, AWS RDS allows users to connect with IAM credentials, so that you can centrally manage permissions. However, this occurs using temporary tokens which only last 15 min.
> 
> I have not found a single GUI app which can support IAM tokens, so this could also be a big value add for RDS.
> 
> Here's an example bash script which I use to open a database connection using the mysql terminal tool:
> 
> ```
> #!/bin/bash
> 
> username="HERE"
> hostname="INSTANCE-NAME.INSTANCE-ID.us-east-2.rds.amazonaws.com"
> port="3306"
> rootCerts="https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem"
> rootCertLocalPath="/tmp/rdscerts.pem"
> 
> echo "Getting token";
> token=$(aws rds generate-db-auth-token  --hostname $hostname --port $port --region us-east-2  --username $username)
> 
> 
> if [ ! -f "$rootCertLocalPath" ]; then
>     echo "Getting certs"
>     curl "$rootCerts" > "$rootCertLocalPath"
> fi
> 
> echo "Connecting with token..."
> 
> mysql --host="$hostname" --port="$port" --ssl-ca="$rootCertLocalPath" --enable-cleartext-plugin --user="$username" --password="$token"
> ```
> 
> This, of course, uses the two pieces of an IAM credential behind the scenes: key id and secret key.
> 
> It would be amazing if this functionality would be implemented directly into dbeaver, ether reading the aws keys from env vars (as most tools do), or even allow them to be specified. This would allow me to push our company to use more secure DB extensions, and also to use dbeaver!

Thank you for your useful script. I am new in BE programing. Could you please explain how I can use your script for connection to db via DBeaver?  I do not get.

**Comment by Gkodkod26** [comment]
@MightyCrabKing

This is only implemented for postgres and not mysql running on managed AWS ?

**Comment by ecdy** [comment]
continuing @Gkodkod26  comment , is there a plan to implement this for mysql ?

**Comment by Jeetah** [comment]
Trying to get DBeaver EE for Postgres working with generate-db-auth-token - but there seems to be no easy way? Or am I missing something? Getting "FATAL: PAM authentication failed for user ..." I also do not see a way to assign this token to the password variable via shell script.

**Comment by n1ngu** [comment]
Take a look at https://github.com/dbeaver/dbeaver/issues/9413#issuecomment-1371150240 if you are using MySQL or were bummed out because this feature only landed in the Enterprise Edition.
