### ISSUE TITLE
Search Functionality Not Returning Any Results

### ISSUE THREAD

**Issue by halilozanyilmaz** [dbeaver/dbeaver#3271]
Sorry I couldn't find any resource about this online, even after checking dbeaver documentation, I couldn't find what I need. I am trying to search a text in all tables in a MySQL database in my godaddy hosting. So I tried:

1- CTRL + H
2- Select DB Full-Text Tab
3- Fill String text box, with text like with a keyword example: cat
4- Click Search.

The application tells me: "You have to set search query" and gives no results. What am I missing here? 

I am trying to search for "cat" text in all my tables, and see which database tables includes this text. What should I do?

**Comment by serge-rider** [comment]
You need to select (check) data sources on the left side. You can search in multiple connections or just in a few tables.

**Comment by halilozanyilmaz** [comment]
Hi @serge-rider 

I am also doing this. Please check my screenshot if I am missing anything. I am just clicking to the search button after this screen below, no results. (I tried with searching with letters too, to be sure that system works. Like 'a')

![image](https://user-images.githubusercontent.com/25062864/38411165-1d7ef6ba-398f-11e8-9a33-99360c1585e1.png)

**Comment by serge-rider** [comment]
You screenshot looks correct.
Do you see progress dialog when clock on Search? If yes then most likely nothing was found. 
Could you test it with some 100% existing string?

And yes, message `You have to set search query` is confusing. I'll fix it.

**Comment by halilozanyilmaz** [comment]
Hi, 
I was seeing the progress dialog at the right bottom, but there were no results. Today I tried again and it started working. Maybe restarting fixed the issue.
Thank you for the help.

**Comment by serge-rider** [comment]
Ok, thanks for info.

**Comment by serge-rider** [comment]
Anyhow, we'll fix bad status message.
