### ISSUE TITLE
Introduce navigation to Associated Entity from constraint

### ISSUE THREAD

**Issue by amplexdenmark** [dbeaver/dbeaver#3274]
- Feature request

When navigating Foreign Keys for a table DBeaver nicely shows:
"Associated Entity" it would be very nice if it was possible to navigate to this entity.
It is all ready shown as a link, but that link takes you to the constraint definition, not the entity.

**Comment by amplexdenmark** [comment]
Okay, 
When you use the database navigator,
I would like the entity links shown in these screenshots to actually take me to the entity.
In the first case it takes me to the foreign key definition. In the second case it does nothing.

![screen shot 2018-04-09 at 08 33 47](https://user-images.githubusercontent.com/5492584/38483073-f5aab422-3bd1-11e8-8223-0b1f364220ad.png)
![screen shot 2018-04-09 at 08 40 03](https://user-images.githubusercontent.com/5492584/38483084-fef09768-3bd1-11e8-9b6b-476b27381388.png)

**Comment by serge-rider** [comment]
To navigate hyperlink press <kbd>ALT</kbd> or <kbd>CTRL</kbd> and click on the link. This works for all links in all metadata editors.

If you double-click on FK column then FK column editor will be opened.

**Comment by amplexdenmark** [comment]
Ahh, thanks! Perfect!!
