### ISSUE TITLE
Getting a com.amazon.ws.emr.hadoop.fs.EmrFileSystem class not found error from Hive HTTP Connections

### ISSUE THREAD

**Issue by blaztoff** [dbeaver/dbeaver#3280]
I created a connection to connect to Hive HTTP (Not Binary) Mode. I can connect fine. I can browse the Schemas and Tables but when I do a select query when the query tries to display the results I get the EmrFileSystem class not found error. (We do use EMRFS)  I added the Jar emrfs-hadoop-assembly to the Driver Connections. This jar does contain the missing class:

com/amazon/ws/emr/hadoop/fs/EmrFileSystemException.class
com/amazon/ws/emr/hadoop/fs/EmrFileSystem.class

But I still get the error.

SQL Error: java.io.IOException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class com.amazon.ws.emr.hadoop.fs.EmrFileSystem not found

Is there a different way to add the missing class to the connection?

**Comment by serge-rider** [comment]
Did you use Hive driver precofigured in DBeaver?
Also you could try hive-jdbc-uber driver from https://github.com/timveil/hive-jdbc-uber-jar (btw it is bundled in DBeaver EE and you could try it in trial mode)

**Comment by blaztoff** [comment]
Yes I am using that driver. It does not work for hive using http mode on EMR.

**Comment by serge-rider** [comment]
You could try to use Hive JDBC from Maven. 
In driver editor remove existing uber jar and add Maven artifact: 
- Group id: org.apache.hive
- Artifact ID: hive-jdbc
Click on Download/Update and choose the latest version (2.3.3 at the moment)
It is huge but potentially more stable than uber jar.

**Comment by serge-rider** [comment]
Another driver: https://docs.aws.amazon.com/emr/latest/ReleaseGuide/HiveJDBCDriver.html

**Comment by jddonaldson** [comment]
@blaztoff were you able to resolve your original request? I am also having the same issue in DBeaver when trying to query my EMR cluster. Can see tables/columns but running a simple select returns the class not found error.
