### ISSUE TITLE
Mongodb cursor issue

### ISSUE THREAD

**Issue by codebling** [dbeaver/dbeaver#3285]
![dbeaver pager bug](https://user-images.githubusercontent.com/1073841/38461604-cfd37cdc-3aa2-11e8-8f85-247ab84c6d53.png)

Screenshot is best explanation. Rows are repeated every time you scroll to the limit of displayed rows. In this case it's set for a 200 rows ResultSet and you can see that the 201st is a duplicate of the 192nd row. The number of duplicated rows varies. Tested in DBeaver 4.0.5

**Comment by codebling** [comment]
(This is DBeaver 4.0.5)

**Comment by serge-rider** [comment]
Can't reproduce. At least in collection data viewer and in simple selects.
Perhaps this issues was resolved since 4.0.5 (although I don't remember such bug). Or maybe you have some more sophisticated use case,

**Comment by codebling** [comment]
I'm not able to reproduce in DBeaver 5.0.3. Sorry for wasting your time with a bug that's already fixed !

**Comment by serge-rider** [comment]
Perhaps this happens because this table is actively updated by other processes? And some kind of mass data insert/delete happens? 
DBeaver just fetches next 200 rows using cursor.skip function. This doesn't guarantee the same result set if other processes modify your collections between fetches.

**Comment by codebling** [comment]
Ok, I understand the problem now. Yes, the table has inserts happening in the background, so I guess when I couldn't reproduce it was just because no inserts were happening. 

My understanding is that the behaviour with regards to how cursors will react when data is added between fetches varies with DB, DB driver, read mode and sometimes other factors, so this is surely not a universal solution, but the MongoDB manual [has this to say](https://docs.mongodb.com/manual/tutorial/iterate-a-cursor/#cursor-isolation) on cursor results:

> As a cursor returns documents, other operations may interleave with the query. For the MMAPv1 storage engine, intervening write operations on a document may result in a cursor that returns a document more than once if that document has changed. To handle this situation, see the information on Cursor Snapshot.

[and](https://docs.mongodb.com/manual/core/read-isolation-consistency-recency/#cursor-snapshot)
> MongoDB cursors can return the same document more than once in some situations. As a cursor returns documents other operations may interleave with the query. If some of these operations are updates that cause the document to move (in the case of MMAPv1, caused by document growth) or that change the indexed field on the index used by the query; then the cursor will return the same document more than once.
> 
> If your collection has a field or fields that are never modified, you can use a unique index on this field or these fields so that the query will return each document no more than once. Query with hint() to explicitly force the query to use that index.

MongoDB has row IDs, so the [hint](https://docs.mongodb.com/manual/reference/method/cursor.hint/#cursor.hint) should be fairly easy to implement. Then MongoDB behaviour would be more consistent with MySQL with repeatable read mode. 

Sorry for bothering and opening so many issues.

**Comment by serge-rider** [comment]
I'm quite sure that it was fixed long time ago

**Comment by uslss** [comment]
cannot reproduce for now
