### ISSUE TITLE
Show error position in query (Oracle and Postgres)

### ISSUE THREAD

**Issue by themadsens** [dbeaver/dbeaver#3286]
I know similar reports has been posted (eg #3222). Here i will try to clarify difference with eg. SQLWorkbenchJ. For the error position to be useful in non trivial queries, it must be shown as as a marker in the query text.

Too bad you have to switch out of DBeaver, just to resolve syntax errors.

### For postgres, error position is shown, but not as a marker in the text:
In DBeaver
![image](https://user-images.githubusercontent.com/4084443/38464745-12e40288-3b13-11e8-9bc0-769966639ed9.png)

In SQLWorkbenchJ:
![image](https://user-images.githubusercontent.com/4084443/38464754-320c0282-3b13-11e8-880f-cce79f907084.png)

### For oracle there is not even a text position in DBeaver
In DBeaver
![image](https://user-images.githubusercontent.com/4084443/38464825-0aafde10-3b14-11e8-941a-cc8594bd0575.png)

In SQLWorkbenchJ:
![image](https://user-images.githubusercontent.com/4084443/38464775-9a974906-3b13-11e8-898a-1b26711027d4.png)

**Comment by serge-rider** [comment]
DBeaver sets cursor (and selection) to error position:
![image](https://user-images.githubusercontent.com/6398845/38495487-6b1cec5e-3c02-11e8-8367-325109a2c00a.png)

But it doesn't show market in error text itself. This would be a good enhancement.

**Comment by themadsens** [comment]
Thanks for the clarification. Very useful once you realize it :-)

And yes, obeying the UI design principle of least element of surprise, I think that would be a useful addition.

Thank you for a very neat product by the way ..

**Comment by konstantin-yua** [comment]
So is there any progress since the last comment was left here?

**Comment by carrerapcl** [comment]
This feature would be very useful...

**Comment by nickmccullum** [comment]
I would LOVE this feature. Can we build it?

**Comment by E1izabeth** [comment]
It has been implemented.
