### ISSUE TITLE
MSSQL: Missing table description

### ISSUE THREAD

**Issue by andreas5588** [dbeaver/dbeaver#3287]
For MSSQL Server the table description is not visible in DBeaver. Tested with MS SQL Server 2017, "Microsoft JDBC Driver for SQL Server" and MS WideWorldImporters Demodatabase.

Please see Screenshot:

![2018-04-08 09_59_51-dbeaver 5 0 3 - application](https://user-images.githubusercontent.com/17796626/38464849-a65e054e-3b14-11e8-9e80-8aba93bb0932.png)

![2018-04-08 10_06_30-table properties - cities](https://user-images.githubusercontent.com/17796626/38464850-a81121c8-3b14-11e8-94ed-58cbecfadd78.png)

**Comment by serge-rider** [comment]
Good point.
By default SQL Server drivers don't provide table descriptions.

Will add this feature in the next version. However it will require separate SQL query for each table (might be a bit slow in some environments).
