### ISSUE TITLE
MSSQL: Can't identifie System-Versioned tables in database navigator

### ISSUE THREAD

**Issue by andreas5588** [dbeaver/dbeaver#3288]
For MSSQL Server System-Versioned tables are listed as "simple" tables and not matched with the history counterpart. Maybe this table types should be listed like in MS SQL Server Management Studio. 
Tested with MS SQL Server 2017, "Microsoft JDBC Driver for SQL Server" and MS WideWorldImporters Demodatabase.

Please see screenshot:

![2018-04-08 10_15_37-eclipse_workspace - org jkiss dbeaver ext mssql_src_org_jkiss_dbeaver_ext_mssql_](https://user-images.githubusercontent.com/17796626/38464946-f4a100c0-3b15-11e8-84d4-7cc9c931cb20.png)

![2018-04-08 10_09_45-dbeaver 5 0 3 - application](https://user-images.githubusercontent.com/17796626/38464906-9137566a-3b15-11e8-9baf-339f632bf0b6.png)

![2018-04-08 10_09_24-sqlquery3 sql - not connected_ - microsoft sql server management studio](https://user-images.githubusercontent.com/17796626/38464907-94773be2-3b15-11e8-8042-165dc2edec6e.png)

**Comment by serge-rider** [comment]
Part or #810
