### ISSUE TITLE
Compare database structure should compare procedure body, too

### ISSUE THREAD

**Issue by xmedeko** [dbeaver/dbeaver#3292]
I've just tried DBeaver compare databases and it's very nice. However, when comparing "structure only", then procedure bodies are not compared. When comparing all, then I have too many differences like table row count etc. which does not interests me.
Please, include procedure, function, view ... definition in the "structure only" comparison. Thanks.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/40589618-dd898204-61f8-11e8-98ad-b0856a64179a.png)
