### ISSUE TITLE
bug: filter from bool column (NULL not work correctly)

### ISSUE THREAD

**Issue by majsterkoo** [dbeaver/dbeaver#3294]
I have a table with a column of type bool.

SELECT * FROM test;

test   |bool  |
-------|------|
foo    |false |
bar    |true  |
foobar |NULL  |

When I try to autofilter on this bool column for the first time I can choose from values NULL/true/false. When I choose false or true (other then NULL), DBeaver filter rows correctly but when I try to choose again (with filter ON) I can see only true and false (NULL is not listed).

-------------------
Driver Type: PostgreSQL
Server: PostgreSQL 10.3
Host OS: Debian 9 amd64

**Comment by serge-rider** [comment]
What do you mean under autofilter? Filter->IN ?

**Comment by serge-rider** [comment]
Agreed. This is a bug (NULL values are processed separately).
Thanks for details
