### ISSUE TITLE
using cli dbeaver does not reuse existing connections

### ISSUE THREAD

**Issue by wumpz** [dbeaver/dbeaver#3296]
For my workflow I want to start dbeaver with some database connection information. It looks something like:

dbeaver.exe --connect \"driver=msaccess_ucanaccess|folder=myfolder|database=<mypath>

I know I can specify a connection name as well. Every time I start dbeaver like this, it creates another database connection instead of reusing a identical one. Is there a solution for this.

**Comment by serge-rider** [comment]
It is a bug (connection with the same name should be reused).
Thanks for report
