### ISSUE TITLE
ADD ability to edit cells in a multiple join query (where joined tables are decoration)

### ISSUE THREAD

**Issue by allanlaal** [dbeaver/dbeaver#3298]
## use case:

 I need to mass edit cells in table A, but it would be helpful to see LEFT OUTER JOINed B, C, D, etc..

## implementation:

one would somehow specify to DBeaver that one only wants to edit table A in this case, so the UPDATE statements completely ignore B, C, D, etc..

**Comment by serge-rider** [comment]
Yes, this would be really handy. Although it is not that easy to implement.

**Comment by serge-rider** [comment]
Edit for particular cell will work only if query result contains all columns for this table unique key.
