### ISSUE TITLE
Minor translation issue with German translation "Zeigen alle Datenbanken an"

### ISSUE THREAD

**Issue by maxbobse** [dbeaver/dbeaver#32986]
### Description

In https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.postgresql.ui/src/org/jkiss/dbeaver/ext/postgresql/PostgresResources_de.properties, the phrase "Zeigen alle Datenbanken an" for dialog_setting_connection_nondefaultDatabase is not proper German - it should be "Alle Datenbanken anzeigen"

### DBeaver Version

Community Edition 24.0.3.202404211624

### Operating System

Windows

### Database and driver

Postgres

**Comment by E1izabeth** [comment]
Thank you for bug report
