### ISSUE TITLE
Automatic table creation in SQL server fails

### ISSUE THREAD

**Issue by gintas** [dbeaver/dbeaver#330]
I'm trying to copy some data from a CSV file to a SQL server table, and when using the default mapping, CREATE TABLE fails because the default columns exceed the size limit:

DBCException: Can't create target table:
CREATE TABLE ... (
...
  DBCException: SQL Error [131] [S0002]: The size (32767) given to the column 'Evt ID' exceeds the maximum allowed for any data type (8000).
    com.microsoft.sqlserver.jdbc.SQLServerException: SQLServerException: The size (32767) given to the column 'Evt ID' exceeds the maximum allowed for any data type (8000).

I can work around the issue by editing the mapping and changing the type of each column, but it's quite tedious to do manually when there are many columns.

I just checked, and VARCHAR(MAX) works well here, that would seem like a good default for the dialect in this context.

**Comment by mdahlman** [comment]
As a workaround (or separate enhancement idea) it would be convenient to be able to set the CSV default String length. Setting the datatype length to 8000 in the CSV metadata isn't quite as elegant as using MAX... but it's functionally identical in many cases.

**Comment by uslss** [comment]
seems issue is outdated
