### ISSUE TITLE
DBeaver no longer associating scripts with a specific DB connection

### ISSUE THREAD

**Issue by ChristopherMagee** [dbeaver/dbeaver#3300]
Hi,

Not sure if this is a bug or something I introduced myself by selecting the wrong property. I have circled back through my preferences and cannot seem to fix my issue.

Previously, my scripts/editor pane would only associate with the database I created them against. However, now those lines seem to be blurred. For example, I used to have my script pointing to a Production database, however when I click on my Test/QA DB the Prod script stays on the screen. 

Example:
Original script/editor setup while I'm connected to PRD.
![image](https://user-images.githubusercontent.com/8886697/38564484-37e1f392-3cad-11e8-9215-9b6ba930cb27.png)

I then click on another DB and the script reconnects to that DB. Previously it would have gone to a script I had made for that database.
![image](https://user-images.githubusercontent.com/8886697/38564551-5cfd7ec6-3cad-11e8-9951-4658712891b5.png)

Any ideas what may be causing this? Thanks in advance!

**Comment by serge-rider** [comment]
Maybe you have enabled editor auto-sync option?
![image](https://user-images.githubusercontent.com/6398845/38598009-55c92900-3d63-11e8-993a-27ecfc562536.png)

**Comment by ChristopherMagee** [comment]
Hi,

Thanks for reaching out. I tried toggling the "Link with editor" a few times and still couldn't fix the issue. 

Is there anyway to do a clean "reset" of my workspace/preferences while still saving my connections? Or a way to export/import the current connections I have?

**Comment by serge-rider** [comment]
Yes, check this: https://github.com/dbeaver/dbeaver/wiki/Reset-workspace
Deleting workbench.xmi reset standard UI settings (window layout, etc).
Also you could try to delete file `.dbeaver4\.metadata\.plugins\org.eclipse.core.runtime\.settings\org.jkiss.dbeaver.core.prefs` to reset most of DBeaver-specific UI settings.

Deleting whole .metadata resets everything including script to datasource associations.

**Comment by ChristopherMagee** [comment]
Thanks! 

Just updated to 5.0.3 and it didn't fix it. Kept poking around... not sure how I missed this setting before but here was the culprit.

![image](https://user-images.githubusercontent.com/8886697/38831639-0630f4ac-418e-11e8-90e7-726942195e71.png)
