### ISSUE TITLE
Text color of select "datasource" and "catalog/schema" in dark theme

### ISSUE THREAD

**Issue by mnvx** [dbeaver/dbeaver#3301]
It is Bug report.

In firsts, lot of thanks for great product!

I use Ubuntu 16.04 with standard Abmiance theme.
When I use dark theme, I see names of datasource and schema in light gray color on white background:
![](http://dl4.joxi.net/drive/2018/04/10/0025/2812/1657596/96/588c806f77.jpg)

Would be great to change color to dark as in auto commit field.

Also I found linked feature request #2495

Best regards

**Comment by serge-rider** [comment]
This seems to be only Linux issue. 
Works ok on Windows and Mac.

**Comment by landsman** [comment]
same in my install

**Comment by uslss** [comment]
is it still actual?

**Comment by mnvx** [comment]
@uslss Yes, but currently it looks more better then early.

![image](https://user-images.githubusercontent.com/829880/80031894-0429f780-84f3-11ea-967e-453fa522c4e5.png)

**Comment by serge-rider** [comment]
Fixed.
No we keep connection/schema selectors enabled for entity editors. You still can't change connection/schema but selectors look much better.

**Comment by uslss** [comment]
verified
