### ISSUE TITLE
Reorganizing Tabs hard crashes GNOME Shell

### ISSUE THREAD

**Issue by Eonfge** [dbeaver/dbeaver#33089]
### Description

Based on this report for the DBeaver Flathub package:
https://github.com/flathub/io.dbeaver.DBeaverCommunity/issues/268

> I am experiencing a GNOME Shell crash when using DBeaver Community Edition installed via Flatpak. The issue occurs specifically when I open two or more tabs from the same database but with different tables, and then try to move one of the tabs to reorganize them. This results in an immediate crash of GNOME Shell.
Steps to Reproduce:

 >   Open DBeaver
 >   Connect to a database and open two or more tabs with different tables from the same database.
 >   Attempt to drag and move one of the tabs to a different position to reorganize.
 >   Observe GNOME Shell crashing immediately.

## Additional context
I've reproduced this issue, even with the .tar.gz package. I can thus state that this is not Flathub specific, but that there is a bug in your application.

### DBeaver Version

24.0.4, both Flathub and .tar.gz version

### Operating System

Fedora Linux 40

### Database and driver

Irrelevant. Can be reproduced with the sample database.

### Steps to reproduce

- Open a database
- Open multiple tables
- Re-arrange

### Additional context

https://github.com/dbeaver/dbeaver/assets/33983090/fbcb1ed6-f34d-4101-a94d-3a5aaf015928

**Comment by Eonfge** [comment]
Also reported with the GNOME Shell team because a bug like this should never have such a serious impact: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7658

**Comment by Eonfge** [comment]
Might be an issue in the Mutter display manager: 
https://gitlab.gnome.org/GNOME/mutter/-/issues/3462

Would be best to put this issue on hold, until there is an update for Mutter. After that, we should see if this bug still occurs.

**Comment by Eonfge** [comment]
Fixed with the latest version of Mutter.
https://gitlab.gnome.org/GNOME/mutter/-/issues/3462

**Comment by serjiokov** [comment]
Thanks for your effort in this issue.

**Comment by Eonfge** [comment]
@serjiokov No problem, I am one of the Flathub volunteers after all. I maintain the package now for 4 years, and in that time DBeaver had half a million downloads. It's one of the most popular software development packages on Flathub:

https://flathub.org/apps/category/Development

It's still not perfect, but I gladly help in making it better for Linux users
