### ISSUE TITLE
[Bug] Completion case depends on the default formatter

### ISSUE THREAD

**Issue by Raphi111** [dbeaver/dbeaver#3308]
Hi, 

I think I found a minor bug. Here's how to reproduce it:

- in the preferences => SQL Editor => SQL Formatting set the formatter to "Default formatter" and keyword case to lower, or database.
- when you type "SELECT" and hit space in an editor, it's converted to lowercase (as intended).
- now choose an *external* formatter that sets the keyword case to uppercase.
- format your file with ctrl+alt+F. All keywords should now be uppercase.
- now type "SELECT" followed by a space. It will be converted to lowercase.
- as a workaround, choosing "default formatter" then setting keyword case to lower produces the expected behaviour, even after setting the formatter back to an external one.

I guess the fix is just to set the "Keyword case" drop-down list visible no matter which formatter is selected.

Btw, thank you for the awesome software dbeaver is!

**Comment by serge-rider** [comment]
Good point 👍
