### ISSUE TITLE
Feature Request: Retain column data types when exporting ERD in graphml format

### ISSUE THREAD

**Issue by cyriacgc** [dbeaver/dbeaver#3310]
Hi,

Exporting ERD in graphml format doesn't contain datatype information which is otherwise shown in DBeaver UI.

Steps:

1. Open ERD of a table schema.
2. Make sure "Show Data Type", "Show Nullability" is selected in "Attribute Styles"
3. Use "Save diagram in external format" and select graphml.
4. Open this file in a supported editor and observe that it doesn't contain primary key, data type, nullability information, which was otherwise seen on DBeaver UI.

It would be great to have this information also in the exported file.

Thanks.

PS: Love the tool. DBeaver has replaced SQLDeveloper as my daily.

**Comment by serge-rider** [comment]
I've added Data type info in graphml export. 
However adding extra styles (bold/italic for nullability and keys) is a bit more complicated.
Maybe we need to rework exporter (https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.erd/src/org/jkiss/dbeaver/ext/erd/export/ERDExportGraphML.java)
