### ISSUE TITLE
[DuckDB] Aliases are not completed in SQL statements

### ISSUE THREAD

**Issue by EvgeniaBzzz** [dbeaver/dbeaver#33107]
### Description

'Insert table aliases (in FROM clause)' is set to `my_table mt`

1. Connect to DuckDB
2. Open SQL editor
3. Type statement and select table name from autocomplete list

Actual: `SELECT * FROM main.TableName`
Expected: `SELECT * FROM main.TableName tn`. It works as expected for other drivers

![image](https://github.com/dbeaver/dbeaver/assets/139753579/59ef1cc0-3f1d-4230-ba56-4226838536fe)

Client version: DuckDBJ 1.0
Server version: DuckDB v0.10.2

### DBeaver Version
24.0.4

**Comment by AliHmaou** [comment]
Thank you very much for the new feature, works like a charm !
