### ISSUE TITLE
[Bug] ClickHouse: Column of type Nullable(UInt64) will cause error.

### ISSUE THREAD

**Issue by luisd303** [dbeaver/dbeaver#3311]
Having a column of type Nullable(UInt64) will cause DBeaver to display an error message. The message says:
For input string: "64)"
  For input string: "64)"

This message pops up when trying to view the Data, Properties or ER Diagram.

UInt64 on it's own does not cause this problem. Nullable(Float64) doesn't either.

**Comment by serge-rider** [comment]
Could you post error stacktrace (https://github.com/dbeaver/dbeaver/wiki/Log-files)?
Most likely this is a driver implementation problem but perhaps we can add some workaround.

**Comment by serge-rider** [comment]
Thanks.
Indeed, it is a bug in Clickhouse driver (it is quite raw). It fails during numeric data types scale/precision reading.
I'll add a workaround for this.
