### ISSUE TITLE
Grid view shows extra zero decimals

### ISSUE THREAD

**Issue by Otiel** [dbeaver/dbeaver#3313]
The results viewer shows extra zero decimals while in grid view, for instance on float8 type:
![image](https://user-images.githubusercontent.com/3851902/38662142-a67133d6-3e33-11e8-8d5e-f317998a72d9.png)

No issue in text view:
![image](https://user-images.githubusercontent.com/3851902/38662163-b9f5ae96-3e33-11e8-8cc2-bf6563cc1308.png)

For reference, the `psql` request:
![image](https://user-images.githubusercontent.com/3851902/38662182-c8357068-3e33-11e8-9407-786c112dbbab.png)

Here are my number settings:
![image](https://user-images.githubusercontent.com/3851902/38662348-460d89f8-3e34-11e8-8a4a-4c80702b3c2a.png)

*DBeaver 5.0.2, PostgreSQL database*

**Comment by serge-rider** [comment]
You can just turn off "Use data type scale for fraction digits" option.

**Comment by Otiel** [comment]
Thanks, that works as expected.
