### ISSUE TITLE
commit mode bug

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#3315]
Commit mode switches to 'auto' **itself** (!) and even doesn't change the icon. 

![default](https://user-images.githubusercontent.com/16996529/38714638-85ed922a-3f1a-11e8-8edc-c60934e6f774.png)

**Comment by serge-rider** [comment]
Can't reproduce. Please provide more details. 
At which moment this happens?

**Comment by serge-rider** [comment]
Yep, it is a bug. 
Thanks for details.
