### ISSUE TITLE
[PostgreSQL] Comments for tables are missing in DDL in 5.0.2 version

### ISSUE THREAD

**Issue by jerherder** [dbeaver/dbeaver#3317]
HEllo

in the new version 5.0.2, the comment on the table is missing.

[problem_comment_table_DDL.docx](https://github.com/dbeaver/dbeaver/files/1906865/problem_comment_table_DDL.docx)

**Comment by serge-rider** [comment]
Bug #3078 appeared again after table manager refactoring.
Thanks for report.

**Comment by StepanYankevych** [comment]
Still loosing columns comment while generating DDL of table tables 
DBeaver 5.1.3, PostgreSQL 10.4

**Comment by serge-rider** [comment]
@StepanYankevych Can't reproduce. Works fine in out test environment standard PG 9 and 10.
Like this:
```sql
CREATE TABLE public.foo (
	col1 int4 NULL -- Column comment 3
)
WITH (
	OIDS=FALSE
) ;
COMMENT ON TABLE public.foo IS 'Soem comment' ;

-- Column comments

COMMENT ON COLUMN public.foo.col1 IS 'Column comment 3' ;
```
