### ISSUE TITLE
Enhance Auto Completion with Contains-Matching

### ISSUE THREAD

**Issue by Lonniebiz** [dbeaver/dbeaver#3318]
Dbeaver's auto-completion is very good at listing matches that **begin** the same way as what has been typed.

However, it would be very useful if it could also match all table-names/field-names that **contain** what has been typed.

If implemented, I'd still prefer that **begin-matches** precede **contains-matches** in the match-listing.

As is, when I'm having difficulty finding a field-name (because I don't know exactly how the field-name begins), I end up having to open a new tab via Dbeaver's "table > edit" feature which offers a contains-search via ctrl-F.

If Dbeaver's auto-completion were enhanced (as proposed above), I'd never have to leave the current tab (I'm working in) to quickly achieve the same goal (of finding field-names for which I only remember an internal segment of their full name).

**Comment by serge-rider** [comment]
Agreed, this would be a handy improvement.

![image](https://user-images.githubusercontent.com/6398845/39066832-2bed2dce-44df-11e8-98c6-10d3d3481bb6.png)

**Comment by Lonniebiz** [comment]
I enabled "Search inside names" in DBeaver 5.0.4, but I cannot detect any difference in auto-completion behavior. Here's a [video](https://youtu.be/KPsO0gKLDEU).

**Comment by Lonniebiz** [comment]
Ok, I just tried this again and I noticed something. If you type slowly, it does indeed find inside-string-matches. However, if you type fast it does not.

Actually, after making this [video](https://youtu.be/yaqf-gkXANA), I see that it does not have to do with the speed I type. Instead, it just seems to alternate between working and not-working each try.

**Comment by serge-rider** [comment]
Umm. It works but only if you press <kbd>ctrl+space</kbd>.
Need to add this to auto-proposals too.

**Comment by serge-rider** [comment]
Yep. 
This is because of Eclipse completions caching. There is a bug in already found completions filtering.
Just committed the fix. Thanks for details.

**Comment by serge-rider** [comment]
You could check the fix in EA version

**Comment by Lonniebiz** [comment]
In the EA version, I confirm that inside-search is working on each try.

FYI, there is still some reminisce of that caching issue you mentioned on alternating tries in regards to whether keywords are included or not.

**Comment by Lonniebiz** [comment]
I've been loving this feature today!

You know, this is so good, I can't imagine anyone not preferring it as default behavior. I certainly recommend it as the default option; I think people will love it.

**Comment by Yoshimit** [comment]
Hi there!
I'm using v5.3.2 with Postgresql and seems the behavior still the same.
With option "Search inside names" unchecked I got the result below.
I was expecting to see the exact match first.
Should I reopen this issue? 

Thank you!

 
![image](https://user-images.githubusercontent.com/7319095/51337004-2e2d7800-1a6d-11e9-858b-77af31412831.png)

**Comment by serge-rider** [comment]
@Yoshimit this dialog (GoTo Object) works differently than SQL editor auto-completion. Option "Search inside names" has nothing to do with this dialog.
Perhaps we need separate configuration for GoTo object. Please create separate issue for that.
