### ISSUE TITLE
[CUBRID] Add Ping Query to Keep Connection Alive

### ISSUE THREAD

**Issue by rathana-pvs** [dbeaver/dbeaver#33184]
**Description**

- Add ping query to keep Cubrid connection alive.

**Comment by E1izabeth** [comment]
We actually have this feature. You can turn it on here (set seconds to value other that 0)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/ae686f06-4788-48dc-8cec-0fe8987e0c65)

**Comment by rathana-pvs** [comment]
> We actually have this feature. You can turn it on here (set seconds to value other that 0) ![image](https://private-user-images.githubusercontent.com/28875055/331683387-ae686f06-4788-48dc-8cec-0fe8987e0c65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMDk3MDEsIm5iZiI6MTcxNjAwOTQwMSwicGF0aCI6Ii8yODg3NTA1NS8zMzE2ODMzODctYWU2ODZmMDYtNDc4OC00OGRjLThjZWMtMGZlODk4N2UwYzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDA1MTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNzU0ZDA4YzY5NDNmYjAxOGY2YjA2OWEwZGZkMDI0YTJkOWI1ODJjZjkxN2JhZDkyODZkNTdmNWVjZmQxODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cd60Hfr9I3GahVCGNRnfBNlQKvsv5h2LJolYqnLeniE)

This feature is to add a default test query when the **isConnectionAlive**(JDBCUtils.java:440) function is called.
I think this function was called when "Keep connection alive" set any value. Please correct me if I am wrong.

By default, "**getTestSQL**" was not set any value in the Generic plugin. So  getTables "**DBEAVERFAKETABLENAMEFORPING**" 
 will be call instead (JDBCUtils.java:478). Cubrid supports "**SELECT 1**" as a test query, So We would like to add this as a default value for the test query.

**Comment by E1izabeth** [comment]
Yes, got it. Thank you

**Comment by E1izabeth** [comment]
@rathana-pvs do you plan to create a Pull Request?

**Comment by rathana-pvs** [comment]
> @rathana-pvs do you plan to create a Pull Request?

Yes, I do. 
I will create Pull Request soon.
