### ISSUE TITLE
DBeaver Crashes When Clicking Outside Window on Multi-Screen Setup

### ISSUE THREAD

**Issue by Aristevao** [dbeaver/dbeaver#33195]
### Description

I have encountered a recurring issue while working with DBeaver on a dual-screen setup, comprising a notebook and a second screen. The problem arises when I am actively working within the DBeaver window and subsequently click anywhere on the second screen or vice versa. Invariably, this action triggers a crash of the DBeaver application.

Notably, the issue persists even during the app's startup phase, exacerbating the inconvenience. This behavior has been consistent across multiple versions, including the latest release, as well as several preceding versions that I've tested.

After updating to the latest Java 17 version, the crashes reduced, but didn't cease.

### DBeaver Version

Comunity Edition 24.0.4.202405051837

### Operating System

Windows 10

### Database and driver

Database: PostgreSQL 14.6
Driver: PostgreSQL JDBC Driver 42.2.5

### Steps to reproduce
1. Launch DBeaver on a dual-screen setup.
2. Click within the DBeaver window.
3. Click anywhere on the second screen or vice versa.

### Expected Results
Normal functioning without any crashes or disruptions when interacting with different screens while the DBeaver application is active.

### Actual Results
DBeaver crashes every time there is an interaction between the DBeaver window and the second screen, leading to a disruption in workflow.

### Additional context

**Did it work before?**
- It worked several months ago.
__________
**Java version:** 
- Current: 17.0.11 2024-04-16 LTS
- Previous : 11.0.17 2022-10-18 LTS

When updated to java `17.0.6 2023-01-17 LTS` the problem ceased temporarily.
This action triggers a crash of the DBeaver application yet, but not every time as before.

When I open the application again after the crash, it doesn't show any log error. If I can find it anywhere, please, let me know.

**Comment by E1izabeth** [comment]
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

If there are some java fatal logs [dbeaver.com/docs/dbeaver/Log-files/#java-fatal-log](https://dbeaver.com/docs/dbeaver/Log-files/#java-fatal-logs), please provide them too.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by iagoholekdev** [comment]
The same thing happens to me on Linux Ubuntu. When I’m working with my laptop and an external screen, DBeaver sometimes freezes when I switch windows and try to return to it. I can't understand why this is happening.
