### ISSUE TITLE
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Shell.addDisposeListener...

### ISSUE THREAD

**Issue by henriquedesousa** [dbeaver/dbeaver#33191]
### Description

After upgrading to newest DBeaver version, the program won't start anymore.

### DBeaver Version

Community 24.0.4-202405051837

### Operating System

Windows 10

### Steps to reproduce

1. Open DBeaver
2. DBeaver crashes
![image](https://github.com/dbeaver/dbeaver/assets/12630569/419f7e37-5f88-423f-aa37-70f8b597fc36)

Here's the logfile: 
[.log](https://github.com/dbeaver/dbeaver/files/15346162/default.log)

### Additional context

Installation is in a portable folder.

**Comment by ShadelessFox** [comment]
Hello @henriquedesousa,

Did you unpack a ZIP archive on top of the existing installation? You can't do that; it might break things. Please perform a clean installation.

**Comment by henriquedesousa** [comment]
I come from a different time, in the world of DOS and Windows 3.1 where things were more simple. I've unpacked onto a different folder and all is well now. Thank you for your time!
