### ISSUE TITLE
SQL Server NTLM Authentication does not work since DBeaver 23.2.0 (The login is from an untrusted domain) 

### ISSUE THREAD

**Issue by cppelf** [dbeaver/dbeaver#33196]
### Description

After an upgrade of DBeaver I got the following error message when trying to connect to SQL Server via NTLM Authentication:
**"Connection to 'xxxx' cannot be established.  Reason: Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication. ClientConnectionId:xxx"**

* With DBeaver 23.1.5 the connection works.
* With DBeaver 23.2.0 the connection does not work anymore. I tried a few newer versions, including also EA 24.0.5. Same error message.

It is not related to the SQL Driver. Same behaviour with different drivers: 9.2 or 11.2.3 or 12.4 I get the same error message or success depending on the version of DBeaver.
If I downgrade to 23.1.5 or an earlier version, then it works.
I tried several versions after 23.2.0 and they all gave the error message.

Client:
* Windows 10 Pro (different PCs).

Server:
* Windows Server 2019
* SQL Server 2017

Error:
![DBeaverError](https://github.com/dbeaver/dbeaver/assets/170115821/dc42601c-2163-4a35-8715-fc42b5456461)

Success:
![DBeaver 23 1 5](https://github.com/dbeaver/dbeaver/assets/170115821/cab80df3-f144-4765-95dd-02d6624e5f0a)
![DBeaver 23 0 0](https://github.com/dbeaver/dbeaver/assets/170115821/199f538e-9aeb-4d63-857f-da232186b362)

Driver:

![DBeaver Properties](https://github.com/dbeaver/dbeaver/assets/170115821/db358d3b-5095-4aa0-885d-123e522670f1)
![SQLDrivers](https://github.com/dbeaver/dbeaver/assets/170115821/51411986-3fac-405e-9175-aeb912d35ca5)

Attached full Logs (Asterisks on sensitive data).

When doing a Diff on the Logs I noticed that in the error logs there is the following additional line:
Framework arguments:  -eclipse.keyring C:\Users\*******\AppData\Roaming\DBeaverData\secure\secure_storage

And this line is missing in the debug error log:
Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.1000.v20220801-1135]

![Diff Log](https://github.com/dbeaver/dbeaver/assets/170115821/677b5023-b8e1-4ccd-94e5-fb7a7b295358)
![Diff Debug Error](https://github.com/dbeaver/dbeaver/assets/170115821/79535cec-dcfc-4bfe-8921-f6e052117a88)
[error__.log](https://github.com/dbeaver/dbeaver/files/15353932/error__.log)
[success__.log](https://github.com/dbeaver/dbeaver/files/15353933/success__.log)
[error__dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/15353934/error__dbeaver-debug.log)
[success__dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/15353935/success__dbeaver-debug.log)

### DBeaver Version

24.0.5 (issue since 23.2.0, ok with 23.1.5)

### Operating System

Client: Windows 10, Server: Windows Server 2019 + SQL Server 2017 

### Database and driver

Driver:
* mssql-jdbc-9.2.0.jre8.jar OR mssql-jdbc-12.4.1.jre11.jar 

Connection Properties:
Host: IP Address
Port: 1433
Authentication: NTLM
Username: ***
Password: ***

Override following Driver Properties:
* trustServerCertificate: true

Added following Driver Properties / User Properties:
* Domain: **** (our Domain)
* Password: **** (my Password)
* User: ${user}

### Steps to reproduce

I try to connect to the database. Error: **"Connection to 'xxx' cannot be established.  Reason: Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication. ClientConnectionId:xxx"**

**Comment by E1izabeth** [comment]
Thank you for report.
Seems `integratedSecurity=true` driver property cause this for you https://stackoverflow.com/questions/18603696/trouble-connecting-to-sql-server-login-failed-the-login-is-from-an-untrusted-d
We set it to `true` before connect [here](https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.mssql/src/org/jkiss/dbeaver/ext/mssql/auth/SQLServerAuthModelNTLM.java#L43)

**Comment by Matvey16** [comment]
This is not reproducible with Windows authentication. Note that user pointed out that it is not connected to driver version, but the error started to appear specifically after DBeaver 23.2.0 and is not reproduced on earlier versions

**Comment by serge-rider** [comment]
New option to disable integrated security was added:

![Image](https://github.com/dbeaver/dbeaver/assets/6398845/7464a06e-e345-4c32-ba25-965d9dc564a3)

**Comment by serge-rider** [comment]
@cppelf Please test the fix in the Early Access: https://dbeaver.io/files/

**Comment by cppelf** [comment]
Unfortunately I get the same error message with the the new CheckBox "Integrated Security" set to enabled or disabled.

[dbeaver-debug24.1.2_error.log](https://github.com/user-attachments/files/16051334/dbeaver-debug24.1.2_error.log)
