### ISSUE TITLE
Firebird templates for object creation

### ISSUE THREAD

**Issue by tonne1** [dbeaver/dbeaver#33200]
"If you want to help - you can recommend a dummy function create statement. I have only for procedures:

```sql
create procedure sample_procedure
as
begin
end
```

_Originally posted by @LonwoLonwo in https://github.com/dbeaver/dbeaver/issues/14225#issuecomment-1988743234_
          
Certainly I'd like to help. The following templates are taken from the Firebird 5 language reference, https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref50/firebird-50-language-reference.html#fblangref50-ddl-func-create, here we go:

(Moved to #14225)

**Comment by LonwoLonwo** [comment]
Hello @tonne1 
I do not see any reason to have this information as a separate ticket. Please move your comment to the original ticket: https://github.com/dbeaver/dbeaver/issues/14225
