### ISSUE TITLE
Read database output in async mode

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#3322]
From #1298 - we need to read database output during query execution in async mode.
Perhaps this should be database specific.

**Comment by KES777** [comment]
Hi. I am on 6.0 version. But I can not see that notices are displayed like psql does:
![_](https://user-images.githubusercontent.com/799021/60647793-33c62100-9e47-11e9-9f30-16298b0d25b3.jpg)
I just see the error message:
![_](https://user-images.githubusercontent.com/799021/60647903-74259f00-9e47-11e9-83db-b63467da4ae1.jpg)

is there some configuration options?

**Comment by andywicht** [comment]
Is it possible that this feature does not work anymore on Windows in version 6.3.2? 
I stopped seeing the output.

**Comment by serge-rider** [comment]
Seems so. #7568
