### ISSUE TITLE
Severe issue with data deletion happening when using DBeaver

### ISSUE THREAD

**Issue by jkashwin** [dbeaver/dbeaver#3323]
When running some queries against oracle 12c database using DBeaver latest version (5.0.2), it was unknowingly deleting multiple rows of data. We lost so much of production data unknowingly and had to spend multiple days re-generating the data. I sincerely advise people to NOT use DBeaver on production databases.

Below is the SQL captured by DBA using SQL trace (this SQL was never sent manually using a query) - 
DELETE   FROM SCH.INVENTORY x WHERE x.LOCATION_NAME=:1

**Comment by serge-rider** [comment]
This SQL uses dynamic parameters (parameter value is set by application in runtime). Query itself is very similar to SQL which DBeaver generates when you edit data manually (e.g. deleting rows in data viewer).

Most likely somebody just deleted some rows manually. Nobody can restrict data manipulation if users have permissions for that. It has nothing to do with any database/sql client.

To be more safe I'd recommend to set "Read-only" flag for production connections + connection type "Production" (it forces transactions use).

**Comment by jkashwin** [comment]
Thank you for your quick reply.

It's true! Our intention was to delete only some rows manually through data viewer - the query to delete was similar to DELETE FROM SCH.INVENTORY WHERE LOCATION_NAME='ABCD' and DATE='01-Apr-18'

I'm still not sure why it would strip that additional "date" condition to delete data for a "location_name" for all "dates"?

BTW, the connection type was correctly set as "Production".

**Comment by serge-rider** [comment]
By default DBeaver uses unique keys to delete rows (thus you can't delete more than one row at once).
Sometimes a table doesn't has a unique key. In that case user may define "virtual" unique key manually. Maybe somebody defined such virtual key incorrectly. And again there is no protection from such situations - just double check your queries. You can see actual SQL which will be executed on save by clicking on "Script" button.
