### ISSUE TITLE
PostgreSQL create function

### ISSUE THREAD

**Issue by mshurutov** [dbeaver/dbeaver#3324]
Hi guys!

When I create function in PostgreSQL I see follow window:
![dbeaver-create-function](https://user-images.githubusercontent.com/19235593/38775314-c2154b26-4087-11e8-97ea-e6dd10e5af9f.png)
But PostgreSQL has only CREATE FUNCTION statement. So I propose next behaviour: instead "Type" include point "Language" and show installed languages in drop-down list. Selected language insert after LANGUAGE keyword in head of function instead keyword "SQL".
And I think that empty filed "Name" with non-empty require is more right then autonaming.

**Comment by serge-rider** [comment]
Good point.

**Comment by mshurutov** [comment]
I'm sorry. But when I created this issue I didn't know that PostgreSQL 11 include "CREATE PROCEDURE" statement: https://www.cybertec-postgresql.com/en/tech-preview-postgresql-11-create-procedure/
So, There is need to check of server version PostgreSQL and if it 11+ then add point "Type" with "CREATE PROCEDURE" statement when choice of type is "PROCEDURE"
I'm sorry.
