### ISSUE TITLE
PostgreSQL. Autocomplete.

### ISSUE THREAD

**Issue by mshurutov** [dbeaver/dbeaver#3325]
Hi guys!

When I use any variables in PostgreSQL function I'm not get variable names when I press Ctrl+Space or Ctrl+Shift+Space, as it shows in screenshot:
![dbeaver-create-function-autocomplete](https://user-images.githubusercontent.com/19235593/38775531-a579ca68-408d-11e8-98b9-ccb5bc93c494.png)
I start insert variable name!

**Comment by mshurutov** [comment]
When I type query in SQL-editor in drop-down list there aren't function names as it show in next screenshot, but function is present in DB (schema).
![dbeaver-autocomplete-function](https://user-images.githubusercontent.com/19235593/38775791-7de69322-4093-11e8-8b68-e0542622ed8a.png)

**Comment by serge-rider** [comment]
> When I use any variables in PostgreSQL function I'm not get variable names when I press Ctrl+Space or Ctrl+Shift+Space, as it shows in screenshot:

<kbd>ALT+/</kbd> and <kbd>Ctrl+Shift+Space</kbd> work as simpel word completion (which completes variable names).

> When I type query in SQL-editor in drop-down list there aren't function names as it show in next screenshot, but function is present in DB (schema).

You can start typing function name and it will be auto-completed. If you list all objects then DBeaver shows only tables (to avoid huge drop-down lists).

**Comment by mshurutov** [comment]
So, when I try to autocomplete on select in body of function I want to see list of functions of DB or schema if I use schema name. Now list is empty:
![dbeaver-function-autocomplete-01](https://user-images.githubusercontent.com/19235593/39097400-4bd0131e-4664-11e8-85e7-4075172284d1.png)

**Comment by serge-rider** [comment]
Resolved in #3473
