### ISSUE TITLE
db change did't work 

### ISSUE THREAD

**Issue by lx769596759** [dbeaver/dbeaver#33256]
### Description

![image](https://github.com/dbeaver/dbeaver/assets/42170609/79289800-9495-42b5-aa49-916a451617fb)
the db has already changed to “dm_i18n”，but when i do query, still query "dm_community","dm_community" is the default，but i already select “dm_i18n” by the change button 
![image](https://github.com/dbeaver/dbeaver/assets/42170609/75f3c83a-6c55-4e64-b11c-064d3698ff0d)

### DBeaver Version

Community Edition 24.0.5.202405191503

### Operating System

Windows 11

**Comment by E1izabeth** [comment]
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by lx769596759** [comment]
[.log](https://github.com/dbeaver/dbeaver/files/15398830/default.log)

**Comment by lx769596759** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/15398832/dbeaver-debug.log)

**Comment by lx769596759** [comment]
https://github.com/dbeaver/dbeaver/assets/42170609/2d07d414-82ca-40d6-9916-c1df79fd6589

**Comment by E1izabeth** [comment]
Thank you

**Comment by E1izabeth** [comment]
@lx769596759 
Could you show me your settings on this page?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/afe45ea5-8f17-460d-9a0f-e3ef3d13a6d6)

**Comment by E1izabeth** [comment]
Maybe was managed to reproduced the issue, but I'm not sure it's the same case. Here it's happening because I imitated unstable network. However, I don't see any messages about disconnection in the log files.

https://github.com/dbeaver/dbeaver/assets/28875055/02681b17-6d20-4e84-985f-4d2ae0081645

**Comment by serjiokov** [comment]
@lx769596759 Could you provide details regarding the database driver, server type and version?

**Comment by E1izabeth** [comment]
@lx769596759 
Could you tell me your driver and server version? You can get this information by clicking `Test connection...` button in the `Connection configuration` dialog.
![image](https://github.com/user-attachments/assets/1b6a9403-0c19-4148-8f54-6bc5706b210b)

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. If the issue is still present, please let me know and provide additional information.
