### ISSUE TITLE
Unable to install new software / configuration folder not writeable

### ISSUE THREAD

**Issue by Enphynity** [dbeaver/dbeaver#33258]
### Description

I tried to install the office support add-in after updating the software this morning and after it restarts the software I am getting the below error messages and the office support add-in is not working.  

![image](https://github.com/dbeaver/dbeaver/assets/102975271/b17a563e-6814-4810-a66e-6ed85cc8ae69)
![image](https://github.com/dbeaver/dbeaver/assets/102975271/dfa778d0-97f9-4f48-bb8a-f01cc033e75f)

### DBeaver Version

Community 24.0.5.202405191503

### Operating System

Windows 10

### Additional context

We use FortiEDR endpoint protection which has been blocking file creation for DBeaver.  This hasn't caused problems with installing the office add-in in the past.  Exceptions have been added for DBeaver but I still can't install the office add-in.

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by Enphynity** [comment]
Here is the log file
[error.log](https://github.com/dbeaver/dbeaver/files/15389645/error.log)

**Comment by E1izabeth** [comment]
Logs contains lots of access denied errors and the paths from the errors in the pictures from issue description are broken.
We would recommend to try resetting the workspace https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings

**Comment by Enphynity** [comment]
If the access denied errors are resolved is this possible to fix without resetting everything?

**Comment by E1izabeth** [comment]
Currently we have no other recommendations

**Comment by Enphynity** [comment]
Ok, thank you for your response.

**Comment by Matvey16** [comment]
@Enphynity I reproduced this issue, but in my case the plugin itself works after those errors. And they don't appear again after restart. Do you have the same situation or those errors repeat after restart?

**Comment by Enphynity** [comment]
No, the plugin is not working.  I’ve tried uninstalling and reinstalling multiple times but the plugin still does not work and I still get the error message.

**Comment by Matvey16** [comment]
@Enphynity Thank you for the report

**Comment by serjiokov** [comment]
Hello @Enphynity,
Could you, please provide details about 'Access denied' in the log file?
I see you have only the read access to the directory: `C:\Users\jpalmer\AppData\Roaming\DBeaverData\workspace6\`
and at the same time `C:\Program Files\DBeaver\configuration` is not writable.

Are both locations read-only?

**Comment by Enphynity** [comment]
Yes, they are both read-only and I don’t know why.  I’ve tried to change the setting but it goes back to Read-only each time.

**Comment by serjiokov** [comment]
Hello @Enphynity, 
So, considering these conditions I would recommend to do next: 
1. Archive your workspace at location  C:\Users\jpalmer\AppData\Roaming\DBeaverData\workspace6\
2. Move and unzip to some writable directory on your machine 
3. Open the file in the root product directory `dbeaver.ini` and add the new line `-data D:\New\Path\Workspace`

As a result, the product should start with the same workspace from the new location.
Let me know any issue on this
If you still struggling with a product, please contact me by mail ` sergei.kovalchuk@dbeaver.com`

**Comment by Enphynity** [comment]
Thank you, I was able to install the office add-on after I updated the software.

Jordan Palmer
Business Systems Analyst
2855 Gramercy St.
Houston, TX 77025
Office  713-395-1527
Ext.      2199
http://www.houstoneye.com/
#SeeTheDifference

[Logo, company name  Description automatically generated]
[nophi]
