### ISSUE TITLE
dragging and copying causes crashes

### ISSUE THREAD

**Issue by WarsenLiu** [dbeaver/dbeaver#33253]
### Description

When I drag a sql from editor, it causes the application to crash

### DBeaver Version

24.0.5

### Operating System

win11

### Database and driver

NA

### Steps to reproduce

1. open sql editor
2. dragging a certain string

### Additional context

Installed jdk11

**Comment by E1izabeth** [comment]
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files).
If there are any java fatal logs (https://dbeaver.com/docs/dbeaver/Log-files/#java-fatal-logs), please provide them too.

**Comment by WarsenLiu** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/15375138/dbeaver-debug.log)
[.log](https://github.com/dbeaver/dbeaver/files/15375141/default.log)

**Comment by WarsenLiu** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/15375153/dbeaver-debug.log)

[.log](https://github.com/dbeaver/dbeaver/files/15375155/default.log)

**Comment by E1izabeth** [comment]
How did you install DBeaver: with installer downloaded from the website, from Microsoft Store, or do you use portable version?

**Comment by WarsenLiu** [comment]
Downloaded 24.0.4 from the official website, upgrading to the latest version still works like this.

**Comment by Destrolaric** [comment]
@WarsenLiu `Installed jdk11`
The minimum JDK for DBeaver is 17. If this is not the case now, could you try launching it using the JDK provided by the client?

**Comment by WarsenLiu** [comment]
@Destrolaric I didn't specify the use of jdk11 in the ini configuration, I only configured it in the system env.

**Comment by E1izabeth** [comment]
Please clarify what do you mean by "drag a sql from editor"

**Comment by E1izabeth** [comment]
And what do you mean by "crashes"? I don't see anything fatal in logs. How does this "crash" look like?

**Comment by WarsenLiu** [comment]
There are too many situations that cause crashes. Last time, I only gave one example, and the following are the video and logs of dragging SQL to crash.

https://github.com/dbeaver/dbeaver/assets/77057177/4979fd61-6897-4c54-9893-689313f3d22d

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/15425878/dbeaver-debug.log)
[.log](https://github.com/dbeaver/dbeaver/files/15425901/default.log)

**Comment by E1izabeth** [comment]
Thank you for providing more information

**Comment by E1izabeth** [comment]
Could you provide java fatal logs?
https://github.com/dbeaver/dbeaver/wiki/Log-files#java-fatal-logs

**Comment by WarsenLiu** [comment]
I couldn't find it in the workspace, but every time I crash, it's generated in the exe directory.
[hs_err_pid45168.log](https://github.com/user-attachments/files/15507400/hs_err_pid45168.log)
[hs_err_pid20276.log](https://github.com/user-attachments/files/15507412/hs_err_pid20276.log)

**Comment by ShadelessFox** [comment]
I don't know if it's possible, but can you try turning off the Chinese input method (Pinyin) popup to see if the issue still reproduces?

**Comment by WarsenLiu** [comment]
Even if the Chinese input method is turned off, it still crashes.
It seems to have nothing to do with this. My friend's Lenovo computer on win11 also experiences this situation.

**Comment by E1izabeth** [comment]
For now we haven't managed to reproduce the issue.

**Comment by serjiokov** [comment]
Hello, Can you please check same case on another PC, if it is possiable? Seems native call lead to swt error.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
