### ISSUE TITLE
All keys except typing stop working after .sql file reload if it is modified externally

### ISSUE THREAD

**Issue by nyurik** [dbeaver/dbeaver#33262]
### Description

After the latest update to `Version 24.0.5.202405191503`, most non-typing keys like arrows stop working if the file content is edited elsewhere, and after I click `replace editor content`.

### DBeaver Version

Community Edition 24.0.5.202405191503

### Operating System

Linux Mint

### Database and driver

PG 16

### Steps to reproduce

1. open some sql file in dbeaver, edit it, and save (but don't close)
2. open the same file in another editor and edit/save it
3. switch back to dbeaver, aggree to replace the content
4. observe that arrow keys no longer work, but typing works

**Comment by Destrolaric** [comment]
@nyurik Hi, Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
