### ISSUE TITLE
Export the data to TXT having space on the all column for txt format

### ISSUE THREAD

**Issue by Pandi4239** [dbeaver/dbeaver#33270]
### Description

|ARTICLE_ID|CONCEPT_NAME|BRAND              |
|159966452 |Splash      |SP-Splash Intimates|

![image](https://github.com/dbeaver/dbeaver/assets/170426922/1fc64d7a-253d-46a2-89d5-f9e228aec03e)

### DBeaver Version

22.1.2

### Operating System

window

**Comment by E1izabeth** [comment]
Please add more information regarding the issue.

**Comment by Pandi4239** [comment]
Setp: 
1.Excuting the query 
2.Export the Date to TXT format 
3.Open the exported notepad 
4.Paste into excel 
5.if any Number value on the cell its ok but if text values on the cell its not fitted on the cel having extra sapace coming after word .

**Comment by Pandi4239** [comment]
[20240522_export.txt](https://github.com/dbeaver/dbeaver/files/15399554/20240522_export.txt)
[transfer to excel.xlsx](https://github.com/dbeaver/dbeaver/files/15399555/transfer.to.excel.xlsx)


find the attached file , can you check the excel file red highlight having space issue .

**Comment by E1izabeth** [comment]
Have you tried exporting to excel format directly? You can do it with Office Plugin https://dbeaver.com/docs/dbeaver/Optional-extensions/#office-integration

txt format intentionally has these spaces, otherwise it will be barely readable due to different length of values

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
