### ISSUE TITLE
Question: Problem installing on Fedora, report missing java though I have java?

### ISSUE THREAD

**Issue by MartinHvidberg** [dbeaver/dbeaver#3327]
I downloaded: https://dbeaver.jkiss.org/files/dbeaver-ce-latest-stable.x86_64.rpm
and, according to the instructions, ran: **sudo rpm -ivh dbeaver-ce-5.0.2-stable.x86_64.rpm**
It replied: **error: Failed dependencies: jre >= 1.8 is needed by dbeaver-ce-0:5.0.2-stable.x86_64**

I checked that I had a relevant java jre: **java -version
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)**

Is OpenJDK not good enough, can it be a path, or naming, issue?

For the record
I did read the one-line document: https://github.com/dbeaver/dbeaver/blob/devel/CONTRIBUTING.md

**Comment by serge-rider** [comment]
Well, it works ok on CentOS. However current dependency (jre) isn't quite correct.
It should be "java >= 1.8". You copuld try it in EA version or in 5.0.3 release.

Thanks for report

**Comment by serge-rider** [comment]
Could you check how it works in 5.0.3?
