### ISSUE TITLE
MongoDB record changes in record view during refresh

### ISSUE THREAD

**Issue by codebling** [dbeaver/dbeaver#3329]
Have a record open in record view. If more rows are added to the DB and then the view is refreshed (F5), the record currently being viewed changes.  

(It seems like the record being viewed is based on an index in the collection view, so for completeness I should say that my case my collection view was sorted chronologically, with more recent entries first.)

**Comment by serge-rider** [comment]
This is not Mongo-specific. DBeaver remembers just row number from results begin. So if resultset changes - row content also changes.

This is a very old question - how should it behave in such case.
Remembering current row unique key will complicate everything. DBeaver will need to position somewhere deep in results, trying to find "current" row. Potentially it may become a million'th row. Bad idea.

**Comment by codebling** [comment]
I am not sure what you mean but I'd like to understand, can you link me to the relevant code?

**Comment by codebling** [comment]
Like maybe here?  I'm looking right now to understand 
https://github.com/dbeaver/dbeaver/blob/17554c9b82d994a4067bfb8e223b76ed46a36af2/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetViewer.java#L1326

**Comment by codebling** [comment]
I will have to update my DBeaver git repo and take a closer look in my IDE but it looks like you're passing a ResultSetRow in these cases, which contains a row number and a visual row number which are relative to the result set for whatever was queried...so if rows which appeared in the original query were deleted or new rows are added which will appear in the query, then the ResultSetRow will point to the wrong row when the view is refreshed?

I can't find the code, but when we delete a row in a table with no key, aren't we asked if we'd like to use all columns? Could we not use the same mechanism for Record View/mode

**Comment by serge-rider** [comment]
I mean that there is no good way to remember row position and then jump to that row after refresh. 

Row can be identified by
- index (we do it now)
- key

There is no guarantee that row with saved key will be there (in the first results fetch) after refresh. It is not clear how to search this row in results. There might be millions of new inserts.

**Comment by codebling** [comment]
I think my expectation was that this record mode was a separate view (like another tab) and it would not be tied to the table view query. 

From what I saw in the code, it looks like decoupling would be a lot of work. One solution might be to clone the Objects storing the cursor + results (ResultSetView?) when opening record mode, but modify the query to be a direct fetch against the primary key or row ID. I'm not sure this would be a worthwhile use of DBeaver development time, since 1) it only affects connections/collections which have had records inserted or removed AND which are not using/do not have a concept of repeatable read, 2) it doesn't work with records that do not have a unique key/row ID.

Keeping this issue closed, sorry again for opening so many new issues
