### ISSUE TITLE
MongoDB JSON view expand/collapse arrows sometimes unresponsive

### ISSUE THREAD

**Issue by codebling** [dbeaver/dbeaver#3330]
On Windows, in Record View using the JSON display, I have a row/document open which contains 2 objects and 1 array of objects at the top level. Under one of the top-level objects, I have another array of objects. 

When alternately and somewhat randomly clicking on all of the expand/collapse arrows for these structures, I've found that sometimes some of them will not respond. Once I've found one that won't respond, if I click on the other arrows until I find one that does respond, I can return to the arrow that wasn't working and it will usually then work (the arrow which doesn't work seems to rotate depending on the expand/collapse state of all of the arrows). Sometimes there is only one that doesn't work and sometimes there are more. There always seems to be at least one arrow that works, though. 

Let me know if you need more info to debug this.

**Comment by uslss** [comment]
cannot reproduce an issue.
Ticket closed.
If issue still actual for you, feel free to reopen it
