### ISSUE TITLE
MongoDB grid view "DBObject"

### ISSUE THREAD

**Issue by codebling** [dbeaver/dbeaver#3331]
Usually in Grid View, DBeaver shows `#document` greyed-out for an object, and `[5]`-style count for an array.

Sometimes, however, DBeaver displays `DBObject` for objects/sub-documents which would normally be indicated by `#document`. When it does this, DBObject is not greyed-out and is not able to be expanded in Grid View (it behaves exactly like a cell containing the string "DBObject"), and it's only by switching to JSON View that one can see the details of this object. 

I'm not sure that much can be done about this, since I expect that this is part of the fix/problem from #3108 (this is the same data set that was caused that issue), but if `DBObject` could at least be greyed-out, that would help. Ideally, the cell would display `#document` with the standard presentation, and a tool tip that one needed to switch to JSON View to view/edit the value. 

As it stands, if one tries to open a DBObject cell in the Cell Editor (Context menu -> Edit cell -> Open Editor), DBeaver displays the message "Unsupported content value type: DBObject".

**Comment by serge-rider** [comment]
I believethis issue was rsolved s tim ago.
