### ISSUE TITLE
Package compile error highlighting and compile errors window

### ISSUE THREAD

**Issue by yevon** [dbeaver/dbeaver#3334]
I thought that package error highlighting and compile errors window was implemented, but i recently checked again and I don't know if I'm doing something wrong but I'm not able to see it. Tested with Oracle:

When compiling a package, an error pop up appears, but you cannot click and go to error line, or keep errors in the bottom compile errors messages area while you correct them.

![image](https://user-images.githubusercontent.com/121157/38793007-c1832dcc-414f-11e8-962a-e1bffd750c6d.png)

The compile errors message area appears blank:

![image](https://user-images.githubusercontent.com/121157/38793039-e0c28d2c-414f-11e8-9edf-4ac06cc38bd2.png)

And there is no code error highlighting:

![image](https://user-images.githubusercontent.com/121157/38793062-f2fd0ddc-414f-11e8-9072-7274ccf5f6fb.png)

Thanks for your work!

**Comment by uslss** [comment]
seems that it is already fixed.
issue closed.
feel free to reopen it if it is still actual for you
