### ISSUE TITLE
Export resultset to SQL INSERT statements (4.3+ versions)

### ISSUE THREAD

**Issue by Zabbah** [dbeaver/dbeaver#3336]
Hello.
The option to _export resultset to SQL INSERT statements_ was removed in version 4.3+

I need that feature, so I cannot update my DBeaver 4.2.6 to newer versions because the lack of  it.
Is there any plan to add that feature again?

I know there's a feature called "Generate SQL INSERT", but it's not as good as to export directly to SQL insert statements when you have to backup lines before delete them in multiple tables.

Thank you.

**Comment by Zabbah** [comment]
Hi, 

I cannot find it on versions after 4.3+

Version 4.2.6:
![426](https://user-images.githubusercontent.com/38419891/38804055-55a0cac0-4171-11e8-9ad8-ee5fb337082a.PNG)

Version 5.0.3:
![503](https://user-images.githubusercontent.com/38419891/38804209-e256e0b2-4171-11e8-8907-a8eb567df00d.PNG)

**Comment by serge-rider** [comment]
Super-weird. Looks like some bug but I can't reproduce that.
Could you post error/debug log? https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by Zabbah** [comment]
It's not that. Screenshot 1 and screenshot 2 are from same database, same single table, screenshot 1 with DBeaver 4.6.2 and screenshot 2 with DBeaver 5.0.2

**Comment by Zabbah** [comment]
Attaching logs.
One more thing... I see you can also export to XLSX files (MS Excel files). I have Excel 2010 installed on my computer. Should not I be able to export to XLSX too? As you can see, I can't, neither version 4.6.2 not 5.0.3...

**Comment by Zabbah** [comment]
Now I uninstall 5.0.3, install 4.2.6 (using reset settings) and voilá! I can export to SQL insert statements again... Now I install 5.0.3 over 4.2.6 (resetting settings again)... no export to SQL insert.

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/1915157/dbeaver-debug.log)

**Comment by Zabbah** [comment]
Export result set.
![export_resultset](https://user-images.githubusercontent.com/38419891/38811774-cafb0eac-418a-11e8-8221-cdfbdf98152c.png)

**Comment by serge-rider** [comment]
Yep, it is a bug in one of recent versions.

**Comment by Zabbah** [comment]
If it helps, export resultset to SQL inserts disappears (in my case) if I install a version after 4.2.6, I mean, 4.3.X and 5.0.X versions.

**Comment by serge-rider** [comment]
See fix in the next version.
