### ISSUE TITLE
ERD diagrams - export image using dark theme

### ISSUE THREAD

**Issue by mppfiles** [dbeaver/dbeaver#3341]
DBeaver 5.01 on Linux Mint Cinnamon 18.1 x64.
I'm using a standard OS dark theme (mint-y-dark) and DBeaver displays ERDs correctly.
But, when I export the diagram to image, dark colors are preserved, which is not printer-friendly.
Is there a way to export images using the 'classic' theme?

**Comment by serge-rider** [comment]
Sounds reasonable. 
But I'm not sue that it is possible to disable Eclipse theming just for one image render (GEF).

**Comment by uslss** [comment]
still actual in 21.2.4

**Comment by arhayka** [comment]
It looks like everything works fine now. So, I'm closing this ticket.
