### ISSUE TITLE
Not searching through third party repository list

### ISSUE THREAD

**Issue by gpogliani** [dbeaver/dbeaver#3342]
Hi,
i've set a list of repositories to satisfy the dependencies of hive MapR drivers located in repository.mapr.com.maven.
During the download the import fails looking for jar actually not in the repository.
This is legit because the dependency relates to jars that are part of the community release.
I added that repository... but nothing still tries to find them the repository.mapr.com

In previous versions was working great....

![image](https://user-images.githubusercontent.com/3237192/38831242-bb63de68-418c-11e8-89c0-6101f67a4961.png)

**Comment by serge-rider** [comment]
Nothing were changed in Maven repository exploration in last versions.

The error you posted says that Maven artifact is missing in mapr repository (and this means that DBeaver tries to read from Maps repository). Most likely something is wrong with repository itself..
You could check this URL in the web browser.
