### ISSUE TITLE
MongoDB memory concerns

### ISSUE THREAD

**Issue by codebling** [dbeaver/dbeaver#3345]
DBeaver does a splendid job of managing memory with the MySQL driver. I've tested this by scrolling through hundreds of thousands of rows and checking the memory usage - it does not go up. 

The MongoDB driver, however, uses memory at an alarming rate. I've found that every 8000 rows uses an additional ~500 Mb of memory. GC is able to reclaim a small amount of this but very little. I can't speak to whether this is a memory leak or just a heavy memory footprint without profiling, but as it stands, at around 38000 rows DBeaver is consuming 2.1+ gigs of memory and becomes unresponsive (I imagine that the JVM is hitting the defined max heap size and attempting GC in order to free up more space on the heap). Attached screenshot shows memory and CPU usage while scrolling through a collection. The CPU usage never dropped back down and DBeaver had to be killed.

![memory concerns](https://user-images.githubusercontent.com/1073841/38839429-8dbf6c90-41a8-11e8-841d-b65634b2b241.png)

Again, it's entirely possible that the MongoDB driver is just very memory-heavy (or perhaps only memory-heavy for my data set), and if that's the case, then the easiest possible fix to me would be to release rows at the top while scrolling down and release rows at the bottom when scrolling up, such that there are never more than (X * ResultSet_fetch_size) rows loaded at the same time. 

Let me know if I can help on this in some way, profiling or whatever

**Comment by serge-rider** [comment]
Yep, Mongo is quite memory eager. It keeps full document in memory in a form similar to DOM, thus 10kb JSON may consume a few Mb of memory. Plus DBeaver uses its own wrappers for Mongo objects.

Potentially it is possible to keep client-side documents in some compact form (e.g. json) and parse it on demand. But it will require a lot of time.

**Comment by codebling** [comment]
Closing for now, let me know if there's anything I can help with on this!

**Comment by serge-rider** [comment]
Ok, thanks for investigation of this issue.
