### ISSUE TITLE
Bookmark drag-drop behaviour (feature request)

### ISSUE THREAD

**Issue by smcateer** [dbeaver/dbeaver#3347]
Firstly, I love DBeaver - great work!

When you drag a table bookmark (from the Projects navigator) to the editor, the _bookmark title_ is inserted in the editor. It would be great if instead the original table reference was inserted (<schema>.<table>) - as happens when the original table is dragged to the editor (from "Connections" in the Projects navigator).

This would be nice-to-have, but it is low-priority.

**Comment by serge-rider** [comment]
Good enhancement and easy to do
