### ISSUE TITLE
Can not create UPPER/Mixed case table-names

### ISSUE THREAD

**Issue by ADoby** [dbeaver/dbeaver#3348]
I am trying to create tables using DBeaver.
I try to type a mixed or upper case "Table Name" into the "Properties" tab of a table.
As soon as I hit enter the name is converted into lower case.

How can I create mixed case table names ?
(Preferably without SQL statements)

I can't find any information about it whith google for some reason.
Only about the keyword casing (which I don't mind)

**Comment by ADoby** [comment]
Update:
The same problem is present when editing column names.
You can create columns with mixed casing but the first time you try to rename the column it gets updated to lower case.

I guess other fields may have the same "problem"

**Comment by serge-rider** [comment]
What is your database?

**Comment by ADoby** [comment]
Oh forgot, we are using a PostgreSql database

**Comment by serge-rider** [comment]
In order to set table/column name in mixed case you need to quote it, e.g. `"ColumnName"`.
Also there was a bug in names conversion.

Please test it in EA version : http://dbeaver.jkiss.org/files/ea

**Comment by ADoby** [comment]
Correct. The problem was that quotation marks did stay when hitting enter.
Causing the table name to be "Name" WITH quotation marks.

Now, tested with "dbeaver-ce-5.0.4-win32.win32.x86_64.zip":
Works as intended. Adding quotation marks now correctly removes them after hitting enter.
Tested for table name and column name for now.

**Comment by Igor180** [comment]
Hello,
This same issue seems to continue in 2021 with Dbeaver version 21.1.4  (02.08.2021).
When trying to alias field names with mixed letters i.e. field_name as "Field_Name" it returns it with all lowercase i.e. field_name.
Any thoughts on how to overcome the issue?

**Comment by timbze** [comment]
@Igor180 See Window > Preferences > Connections > Metadata > and enable "Use case-sensitive names in DDL statements"

**Comment by Igor180** [comment]
> @Igor180 See Window > Preferences > Connections > Metadata > and enable "Use case-sensitive names in DDL statements"

Thanks a lot @timbze 
It works in MySQL connection, but not in Amazon Redshift. The issue seems to continue only in the Amazon Redshift connection, so it is not a big deal.
Thanks a lot for your time and your help.
