### ISSUE TITLE
Query Results view steals key events from SQL Editor

### ISSUE THREAD

**Issue by Neospiro** [dbeaver/dbeaver#3349]
- Execute a query
 - Browse the result view (apply a filter, use arrow keys)
 - now, click in the SQL Editor and type : when you use "CTRL + arrow keys", it moves the result table cursor

I expect the SQL Editor text cursor to move words-by-words when the SQL Editor have focus, not the table one in result view.

I encourage anyone to rephrase my bad English

**Comment by serge-rider** [comment]
Yes, this happens sometimes (not so easy to reproduce). Seems to be some glitch in Eclipse.
Anyhow, I think we should change default shortcuts for results browsing to something unambiguous.

Changes to <kbd>CTRL+ALT+Right</kbd> and <kbd>CTRL+ALT+Left</kbd>
