### ISSUE TITLE
Failure to select column named "end", keyword is not ignored.

### ISSUE THREAD

**Issue by mtdeguzis** [dbeaver/dbeaver#3351]
I came across [dbeaver/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/sql/SQLConstants.java](https://github.com/dbeaver/dbeaver/blob/master/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/sql/SQLConstants.java) after a user reporting failure to select data from a column that matches "end". Can this keyword be avoided in this context? I understand that quoting or using backticks will work, but the aim here is to allow this to function so itellisense runs more smoothly. Is there a way to make exceptions / auto quote certain keywords?

Reproducible steps:

```
drop table if eixsts somedb.test_reserved_keywords;
show create table somedb.test_reserved_keywords;
```

Create basic table
```
create table if not exists somedb.test_reserved_keywords
(col1 string, col2 string, `end` string, `COUNT` int)
STORED AS ORC LOCATION '/group/somedb/hive/test_reserved_keywords';
```

Test
```
select * from somedb.test_reserved_keywords where COUNT = '';
[OK]
```

```
select * from somedb.test_reserved_keywords where end = '';
[FAIL]

# END is within the reserved keywords list.
select * from somedb.test_reserved_keywords where END = '';
[FAIL]
```

Error message:
```
Error while compiling statement: FAILED: ParseException line 1:54 cannot recognize input near 'end' '=' '''' in expression specification
  Error while compiling statement: FAILED: ParseException line 1:54 cannot recognize input near 'end' '=' '''' in expression specification
    org.apache.hadoop.hive.ql.parse.ParseException:line 1:54 cannot recognize input near 'end' '=' '''' in expression specification
    org.apache.hadoop.hive.ql.parse.ParseException:line 1:54 cannot recognize input near 'end' '=' '''' in expression specification
```

**Comment by mtdeguzis** [comment]
Hmmm, if so, any idea where to go with this one since Apache Hive is an included driver?

**Comment by uslss** [comment]
Hi @mtdeguzis , is issue still actual for you?

**Comment by mtdeguzis** [comment]
Hello. I tested this again with version 5.0.3. Same issue

**Comment by uslss** [comment]
Could you try on the recent version (6.2.3)?

**Comment by mtdeguzis** [comment]
Sure, thankfully the database connection settings migrate fine on OS X, and I can have multiple side by side by the nature of the DMG.
![image](https://user-images.githubusercontent.com/27829577/67205589-07c2b180-f3de-11e9-8db3-22fe01527185.png)

Version 6.2.3.201910201831

query
```
drop table if exists cdis_it_db.test_reserved_keywords;

create table if not exists cdis_it_db.test_reserved_keywords
(col1 string, col2 string, `end` string, `COUNT` int)
STORED AS ORC LOCATION '/group/somedb/hive/test_reserved_keywords';

--ok
select * from cdis_it_db.test_reserved_keywords where COUNT = '';

--fail
select * from somedb.test_reserved_keywords where end = '';

```

Still fails
```
Error occurred during SQL query execution

Reason:
SQL Error [40000] [42000]: Error while compiling statement: FAILED: ParseException line 2:50 cannot recognize input near 'end' '=' '''' in expression specification
```

**Comment by serge-rider** [comment]
@mtdeguzis You can enclose end in double quotes, like this:
```sql
select * from cdis_it_db.test_reserved_keywords where "end" = '';
```
