### ISSUE TITLE
MSSQL date/time types show text icon.

### ISSUE THREAD

**Issue by chriseaton** [dbeaver/dbeaver#3353]
## Issue Description
Within an ERD (visual diagram) and the UI, when showing certain date/time types from a MS-SQL db it uses the text "abc" icon instead of the clock, which would probably be more appropriate.

Here's the list of [MS-SQL date/time types](https://technet.microsoft.com/en-us/library/ff848733(v=sql.105).aspx) that probably should use the clock icon:

- date
- datetimeoffset
- datetime2
- ~smalldatetime~  *already shows clock icon*
- ~datetime~ *already shows clock icon*
- time

![screenshot from 2018-04-17 16-40-00](https://user-images.githubusercontent.com/5247568/38904323-8e684480-425e-11e8-9c14-f41065682f8b.png)
![screenshot from 2018-04-17 16-40-31](https://user-images.githubusercontent.com/5247568/38904324-907c6350-425e-11e8-9485-d668c3c1e25e.png)

**Comment by uslss** [comment]
still reproducable for datetimeoffset only

**Comment by serge-rider** [comment]
@uslss `datetimeoffset ` is not a datetime column. It is handled completely differently and it was treated as string since #4724 fix
