### ISSUE TITLE
Debugging in dbeaver 5.0.2 and PostgreSQL 10.2

### ISSUE THREAD

**Issue by jmaciassuarez** [dbeaver/dbeaver#3355]
Hello, 

I am trying to debug with dbeaver community edition Dbeaver 5.0.2, PostgreSQL 10.2 and Windows 7 but I have problems.

I have successfully installed and configured the Postgre Server plugin version "REL-10_0-BETA1"  (https://git.postgresql.org/gitweb/?p=pldebugger.git;a=tree;h=6ce7152ea74a414bf8e560364bc851df9fcd605b;hb=ca1041dc3db6f516899be669dc6fbfd6339f8168).

![dbeaver debugger4](https://user-images.githubusercontent.com/35451042/38919330-97fecce8-42f0-11e8-88dd-10e45bc214cf.PNG)

![dbeaver debugger6](https://user-images.githubusercontent.com/35451042/38919701-a6820d56-42f1-11e8-8a96-c6c0a34be9a4.PNG)

![dbeaver debugger5](https://user-images.githubusercontent.com/35451042/38919421-d24fc58c-42f0-11e8-841c-8d998b26a2ea.PNG)

I have correctly installed "DBeaver - SQL Debugger" (http://marketplace.eclipse.org/content/dbeaver-sql-debugger).

![dbeaver debugger3](https://user-images.githubusercontent.com/35451042/38919231-4e88c2d0-42f0-11e8-8dd5-34466867b3a5.PNG)

But when I access the Dbeaver debug perspective I get an error and I can not find the PostgreSQL instance, as in the documentation (https://github.com/dbeaver/dbeaver/wiki/PGDebugger). (Attached image).

![dbeaver debugger](https://user-images.githubusercontent.com/35451042/38918577-72fda2cc-42ee-11e8-9839-d82f7198a1b4.PNG)

![dbeaver debugger2](https://user-images.githubusercontent.com/35451042/38918864-38194926-42ef-11e8-9c67-4ae97a5d43ba.PNG)

Any ideas about the error or configuration that is missing?

**Comment by ruspl-afed** [comment]
The "Problem Occured" on the first screen means some inconsistency between "DBeaver" and "DBeaver -SQL Debugger" components. Do you have them in sync?

**Comment by ruspl-afed** [comment]
For me it looks like you need to updgrade "DBeaver" to 5.0.3.

**Comment by jmaciassuarez** [comment]
Thanks Alexander,
I have updated DBeaver to version 5.0.3 but now when I try to install the Dbeaver Debugger plugin I get the following error:

![dbeaver debugger7](https://user-images.githubusercontent.com/35451042/38921297-b2b30c0c-42f5-11e8-98f0-a4eec624dd91.PNG)

**Comment by ruspl-afed** [comment]
Please have a look here https://github.com/dbeaver/dbeaver/wiki/Optional-extensions

> IMPORTANT: installation won't work if DBeaver is installed in write-protected folder (like Program Files, /Applications, /usr/). To proceed you need to run DBeaver from some non write-protected folder or run it as Administrator/root.

**Comment by jmaciassuarez** [comment]
Thanks so much, I have completed the installation successfully (I changed the installation directory). Now I have no problems, but I do not identify the debug option in the context menu.

![dbeaver debugger9](https://user-images.githubusercontent.com/35451042/38923365-a3f70a2e-42fa-11e8-8c7b-ee38f1e0700d.PNG)

![dbeaver debugger10](https://user-images.githubusercontent.com/35451042/38923368-a78174c2-42fa-11e8-8fc1-99ee52f8aead.PNG)

Does Dbeaver need any specific configuration?

![dbeaver debugger11](https://user-images.githubusercontent.com/35451042/38923566-2cf53db4-42fb-11e8-8dcf-60218fb01334.PNG)

**Comment by ruspl-afed** [comment]
Yes, we have an usability issue here, addressed with #3255 
Currently the debug is available from the context menu of edtor's "Source" tab only (https://user-images.githubusercontent.com/35451042/38923368-a78174c2-42fa-11e8-8fc1-99ee52f8aead.PNG), please find the standard "Debug As" item there. 
After initial launch it will be visible at "Debug Configurations" dialog.

**Comment by jmaciassuarez** [comment]
:1st_place_medal:  Alessander, finally I can debug :D. Thank you very much!

![dbeaver debugger12](https://user-images.githubusercontent.com/35451042/38926935-8e14dcae-4304-11e8-9590-6767ed83d87d.PNG)

**Comment by ruspl-afed** [comment]
Great! Looking forward for your suggestions how to imrobe the user experience!

**Comment by tonifirnandes** [comment]
Hello sir @jmaciassuarez , i am havaing trouble to installed it on mac os. What i have done:
1. Installed dbeaver community edition version 5.1.5

2. Installed 'brew install postgresql'

3. Cloned pldebugger "https://git.postgresql.org/git/pldebugger.git" and run this following command into the pldebugger cloned folder =
export USE_PGXS=1
make
make install
resulted =
clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -I/usr/local/lib/postgresql/pgxs/src/makefiles/../../src/pl/plpgsql/src -I. -I./ -I/usr/local/Cellar/postgresql/10.5/include/server -I/usr/local/Cellar/postgresql/10.5/include/internal -I/usr/local/Cellar/icu4c/62.1/include -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2   -c -o plpgsql_debugger.o plpgsql_debugger.c
clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -I. -I./ -I/usr/local/Cellar/postgresql/10.5/include/server -I/usr/local/Cellar/postgresql/10.5/include/internal -I/usr/local/Cellar/icu4c/62.1/include -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2   -c -o plugin_debugger.o plugin_debugger.c
clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -I. -I./ -I/usr/local/Cellar/postgresql/10.5/include/server -I/usr/local/Cellar/postgresql/10.5/include/internal -I/usr/local/Cellar/icu4c/62.1/include -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2   -c -o dbgcomm.o dbgcomm.c
clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -I. -I./ -I/usr/local/Cellar/postgresql/10.5/include/server -I/usr/local/Cellar/postgresql/10.5/include/internal -I/usr/local/Cellar/icu4c/62.1/include -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2   -c -o pldbgapi.o pldbgapi.c
clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -bundle -multiply_defined suppress -o plugin_debugger.so plpgsql_debugger.o plugin_debugger.o dbgcomm.o pldbgapi.o -L/usr/local/lib  -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -Wl,-dead_strip_dylibs   -bundle_loader /usr/local/Cellar/postgresql/10.5/bin/postgres
/bin/sh /usr/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/lib/postgresql'
/bin/sh /usr/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/share/postgresql/extension'
/bin/sh /usr/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/share/postgresql/extension'
/bin/sh /usr/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/Cellar/postgresql/10.5/share/doc/postgresql/extension'
/usr/bin/install -c -m 755  plugin_debugger.so '/usr/local/lib/postgresql/plugin_debugger.so'
/usr/bin/install -c -m 644 .//pldbgapi.control '/usr/local/share/postgresql/extension/'
/usr/bin/install -c -m 644 .//pldbgapi--1.1.sql .//pldbgapi--unpackaged--1.1.sql .//pldbgapi--1.0--1.1.sql  '/usr/local/share/postgresql/extension/'
/usr/bin/install -c -m 644 .//README.pldebugger '/usr/local/Cellar/postgresql/10.5/share/doc/postgresql/extension/'

4. After that i changed the postgres file configuration by "nano /usr/local/var/postgres/postgresql.conf" and changed the following line to be = #shared_preload_libraries ='/Users/tonifirnandes/Documents/backend/pldebugger'

5. Restart my postgresql services = brew services restart postgres

6. When i open dbeaver again, and create extension pldbgapi on selected dbconnection, but unfortunately i got this error 
{
Query execution failed

Reason:
SQL Error [58P01]: ERROR: could not open extension control file "/usr/share/postgresql/9.4/extension/pldbgapi.control": No such file or directory
}

Could you please help me sir @ruspl-afed .

Best regards,

**Comment by serge-rider** [comment]
@AndrewKhitrin any thoughts?

**Comment by ruspl-afed** [comment]
I am not sure that this is an exact cause of your issue, but paths in your logs and configurations looks inconsistent: the make is targeting postgresql/10.5 while the SQL Error is mentioning postgresql/9.4.
