### ISSUE TITLE
Saving columns filter not working in macOS with Postgres database

### ISSUE THREAD

**Issue by bmscmoreira** [dbeaver/dbeaver#3359]
I've tried to save a custom filter (column visibility and order) - i.e. "saving custom filter settings for current object" in a table in Postgres database, but they appear not to be saved at all. If I close the table and reopen it, the visibility is wrong (some columns are invisible, but other aren't).

**Comment by serge-rider** [comment]
I can't reproduce this issue.
Maybe there are some steps to reproduce?
Or maybe there are some error in error log view?
