### ISSUE TITLE
Feature request - Keep current procedure line in focus after saving procedure in Postgres

### ISSUE THREAD

**Issue by roparo** [dbeaver/dbeaver#3362]
Hello,

DBeaver focuses at the beginning of a procedure code, loosing current editing line focus.

This happens when using DBeaver non maximized (i.e.: half of display height) on Windows 
and editing and saving a procedure in Postgres which is longer than current DBeaver display height.

Thank you.

**Comment by serge-rider** [comment]
Good point

**Comment by serge-rider** [comment]
Please test in 5.0.4

**Comment by roparo** [comment]
Tested today in 5.0.4

The problem is not fixed, same behavior was observed.

Thanks.

**Comment by serge-rider** [comment]
Can't reproduce.

What is your OS?
Could you make some screenshots/short video?

**Comment by serge-rider** [comment]
Well, I see this.
The strange part is that I still can't reproduce this on our test machines (Windows 10 and Mac OS).
Perhaps we need Windows 7..

Could you update to the most recent version to be 100% sure that this wasn't fixed there.

**Comment by roparo** [comment]
Hello,


I've just installed the latest DBeaver 5.0.5 version an I've got the same
issue.

As an observation, it doesn't matter if is Postgres or Oracle, it is the
same .

Thanks.

**Comment by brkerez** [comment]
Same here with DBeaver 5.0.5. I'm forced to use Windows 7 and focus is on the first line of package after each save. 
os: Windows 7 (I can't switch to win10)
db: Oracle 12c 12.1.0.2.0

**Comment by Speirs47** [comment]
Same on Linux in MySQL/MariaDb

**Comment by serge-rider** [comment]
Will be fixed in the next version. 
Procedure editor won't be refreshed for existing objects.

**Comment by serge-rider** [comment]
Please reopen if this issue will happen again. Attach gif video if possible.
