### ISSUE TITLE
Feature request: Change Password dialog

### ISSUE THREAD

**Issue by fayca121** [dbeaver/dbeaver#3365]
Hi,
It would be very useful to be able to change the session password from a dialog, especially when the password is expired and you need to define a new one.

![2018-04-21 11_36_59-change password](https://user-images.githubusercontent.com/547548/39083220-f4c3c4b4-4558-11e8-9360-dc5b48528fe9.png)

Thanks.

**Comment by fayca121** [comment]
Hi Serge,

In our company we have a password expriration policy for oracle db and each time my session password is expired I have to connect through Toad to change it, so it would be helpful if I could do it direclty with dbeaver.

thanks again.

**Comment by serge-rider** [comment]
Please test it in 5.0.4

**Comment by fayca121** [comment]
Hi,

I've tested the new feature with oracle dirver v12.2.0.1 and it worked perfectly.

Thank you so much.

**Comment by zulfiqarhaider** [comment]
> new feature with oracle dirver v12.2.0.1 and it worked perfectly.

Can this be explained a bit more in detail; how to enable it.

**Comment by fayca121** [comment]
Hi,
I don't know how to enable it :) .
In my case the popup window is automatically displayed when the password is expired.

**Comment by serge-rider** [comment]
@fayca121 @zulfiqarhaider it is not possible to show this dialog manually. It is a special Oracle feature embedded in Oracle network protocol (supported by 12g+ driver). 
This dialog appears only if password was expired.

**Comment by ridicolos** [comment]
@serge-rider Is there something like this for Postgres? 

We assign a default password to our users, this should be changed by the colleagues. We are now faced with the challenge that we have not found an option in DBeaver with which we can change the password of the own user. Is this not possible under Postgres?

**Comment by p91paul** [comment]
@dennisneise I suggest you open a new issue or open a discussion, commenting years old closed issues has a very high chance of being overlooked!
