### ISSUE TITLE
Oracle - Disable Autoconnect to Previous Execute DB

### ISSUE THREAD

**Issue by aloon9999** [dbeaver/dbeaver#3366]
The opened DB script always auto connect to previous execute DB. How to disable this feature.

**Comment by serge-rider** [comment]
Not sure I fully understand the question but maybe this could help:
![image](https://user-images.githubusercontent.com/6398845/39092521-40bdafb4-4618-11e8-838e-18568399ebc3.png)

**Comment by tomhanax** [comment]
I have same problem - I do NOT want to autoconnect to any DB. I have those checkboxex UNchecked globally, and no overrides on DB connection definitions. Still it autoconnects. Using 6.1.5. Can anybody help?
