### ISSUE TITLE
PostgreSQL function editor freeze.

### ISSUE THREAD

**Issue by mshurutov** [dbeaver/dbeaver#3368]
Hi guys.

When I create or edit function in FUNCTION editor (not SQL editor) and then try to save it dbeaver freeze. Screenshots.
1. I try to save function:
![dbeaver-create-function_before-save-01](https://user-images.githubusercontent.com/19235593/39094971-56f310de-4641-11e8-9656-2cd56c7bdf9e.png)
2. dbeaver freeze:
![dbeaver-crash-after-save-function-01](https://user-images.githubusercontent.com/19235593/39094975-63f502a6-4641-11e8-904e-9e69136e44a1.png)
3. Window with error:
![dbeaver-crash-after-save-function-crash](https://user-images.githubusercontent.com/19235593/39094981-79b71f3e-4641-11e8-8f2c-aad0b799ec73.png)
and trace of error as text:
```
JVM terminated. Exit code=143
/usr/bin/java
-XX:+IgnoreUnrecognizedVMOptions
-Xms64m
-Xmx1024m
-jar /opt/dbeaver-bin-5.0.3//plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
-os linux
-ws gtk
-arch x86_64
-showsplash
-launcher /opt/dbeaver-bin-5.0.3/dbeaver
-name Dbeaver
--launcher.library /opt/dbeaver-bin-5.0.3//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.551.v20171108-1834/eclipse_1630.so
-startup /opt/dbeaver-bin-5.0.3//plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
--launcher.overrideVmargs
-exitdata 29d802f
-vm /usr/bin/java
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
-Xms64m
-Xmx1024m
-jar /opt/dbeaver-bin-5.0.3//plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar 
```
This behavior I see in Gentoo Linux and MS Windows 10.

**Comment by serge-rider** [comment]
Can't reproduce
1. Do you see the same error on Windows?
2.  Once UI become frozen - please make thread dump (https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump)

**Comment by mshurutov** [comment]
Thanks for your answer!
Now I know how to get thread dump so I cann't reproduce this permanent behavior as it was before. Tomorrow I will try to reproduce it on Windows. On Windows behavior is same as that on Linux but on Windows system sends information about crash to Microsoft after I close the DBeaver window by click to Window Close button.

**Comment by mshurutov** [comment]
Thread dump from Windows is not upload, so there is a link: https://cloud.mail.ru/public/4B8R/9NDwtNbhM
Description. I create pgbench tables by command `pgbench -iqs 30` and few times create and edit functions, which returns count of rows on every table as follow:
<PRE>CREATE OR REPLACE FUNCTION public.get_acc_count()
 RETURNS bigint
 LANGUAGE sql
AS $function$
	select count(*) from pgbench_accounts;
 $function$
</PRE>
I download from and upload to local instance of PostgreSQL DemoDB (small) from PostgresPro site: https://postgrespro.com/education/demodb
Next I create and edit functions from query from <A HREF="https://postgrespro.com/docs/postgrespro/10/apls05.html">Usage</A> link.

**Comment by mshurutov** [comment]
In addition to the previous message. I have several **thousand** objects (tables, views, functions etc) in work DB. I have three connections to this DB: production, testing, develop. DBeaver freeze when I connect to any of these DB instances.

**Comment by serge-rider** [comment]
Thanks for details. This seems to be a bug in SQL editor folding.
Workaround: disable SQL editor folding in preferences.

**Comment by uslss** [comment]
Not reproducible on 6.0.2. Closed.
