### ISSUE TITLE
Sybase SQL Anywhere is giving '@p0' error

### ISSUE THREAD

**Issue by nguyelongt** [dbeaver/dbeaver#3371]
So I can connect to the DB just fine and see all the tables and such

But when I tried to query, its giving me this error: 
example: Select * From Billing;

Query execution failed
Reason:
SQL Error [137][42W14]: SQL Anywhere Error -260: Variable '@p0' not found

Details shows:
SQL Error [137] [42W14]: SQL Anywhere Error -260: Variable '@p0' not found
  SQL Error [137] [42W14]: SQL Anywhere Error -260: Variable '@p0' not found
    SQL Error [137] [42W14]: SQL Anywhere Error -260: Variable '@p0' not found
      SQL Error [137] [42W14]: SQL Anywhere Error -260: Variable '@p0' not found
        SQL Anywhere Error -260: Variable '@p0' not found
        SQL Anywhere Error -260: Variable '@p0' not found

But if I were to run the same query again with Top 100 or something it works just fine
Example: Select Top 500 * from Billing;

I tried to set the global / local amount of rows of data it returned back but the errors still 
come back

Any ideas what is causing this?

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on the issue for a long time
additional info is needed to reproduce an issue.
ticket will be closed. feel free to reopen an issue and add info that could help to investigate it.

**Comment by mmellon** [comment]
I have duplicated this issue.

**Comment by AndreiLetyushov** [comment]
I have got this bug too. SQL Anywhere 16 server.

**Comment by luvelloso** [comment]
I have the same issue.

**Comment by LonwoLonwo** [comment]
Hello

Unfortunately we do not have test environment to check.
Please, if you still have this issue - check the [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager).
![2023-02-23 18_28_22-Event](https://user-images.githubusercontent.com/45152336/220953276-c2c86d08-5a46-4263-bedf-41ba681a5862.png)
If your failed query has special limitations inside you will see it. Like `SELECT * FROM TABLE LIMIT 100`
Maybe DBeaver add incorrect limitation syntax there.
Thanks.

**Comment by zalmanlew** [comment]
I'm getting this error as well when making any query on Sybase SQL Anywhere 17.0.11.7058

there doesn't seem to be anything wrong with the syntax in the query manager

this also happens when just trying to view the records for a table, not only when running a query manually

<img width="568" alt="image" src="https://user-images.githubusercontent.com/35234925/224413503-29360211-d81c-4fba-8bd5-9f8667c7b064.png">

Like the other suggestion, including `TOP X` in the query made it work. I guess we need to make it always include the TOP X in the queries it sends.

**Comment by zalmanlew** [comment]
Discovered the following as workarounds which will allow the query to go through without failing. Still not sure what the cause is.

1. Declare the `@p0` variable before running the query
```sql
DECLARE @p0 int;
SELECT 1;
```
2. Wrap the query in a `begin` and `end` statement
```sql
begin
select 1;
end
```
3. already mentioned including the `top` statement
```sql
select top 1 1;
```

**Comment by LonwoLonwo** [comment]
Still can't reproduce 

Only that I can found is: https://stackoverflow.com/a/39294301

We can probably add a TOP limitation to Sybase to avoid this issue.

**Comment by LonwoLonwo** [comment]
A TOP limit will be added in the query for Sybase/SQL Server if the setting "Use SQL to limit fetch size" is enabled:

![2023-03-20 12_43_57-Preferences](https://user-images.githubusercontent.com/45152336/226303461-ec4d2e63-c305-4d86-a2b4-a25d79d85271.png)

Fixed in 23.0.1.
Will be available [here](https://dbeaver.io/) on 2023-03-27

**Comment by zalmanlew** [comment]
@LonwoLonwo can you please reopen this - I found some new info.

I managed to enable logging on the DB and found the following

<img width="468" alt="image" src="https://user-images.githubusercontent.com/35234925/227785867-18b3a7f7-74cd-40ba-be30-47e9f9ecc4a1.png">

Worth noting that this `@p0` error occurs before even attempting to run the query I'm sending (I can send an obviously invalid query and it fails on the `@p0` variable before even attempting the query)

**Comment by LonwoLonwo** [comment]
Hello @zalmanlew 

Unfortunately, your message does not add any clarity to the situation. DBeaver does not add  '@p0' for queries or anything else. It can be a driver issue. And workaround for now - https://github.com/dbeaver/dbeaver/issues/3371#issuecomment-1479406684

**Comment by shtoormanSam** [comment]
I have got this bug too.
SQL Anywhere 17 server (SQL Central), 
DBeaver Sybase jConnect driver (com.sybase.jdbc4.jdbc.SybDriver)

upd: Eureca!
DBeaver \ DataBase \ DriversManager \ Sybase jConnect \ Additional params \ Driver supports result set limit == FALSE 
(default is "true")
