### ISSUE TITLE
SQL editor strange behaviour 

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#3372]
I've got this query:
![default](https://user-images.githubusercontent.com/16996529/39163143-8743270c-47bc-11e8-8f15-011c9148849b.png)

I want to change the table. I press Ctrl+Space and select new table
![default](https://user-images.githubusercontent.com/16996529/39163246-039503a2-47bd-11e8-9049-f20fa7d02578.png)

After I press Enter I get this
![default](https://user-images.githubusercontent.com/16996529/39163472-f8f29224-47bd-11e8-933a-e71929691b20.png)

**Comment by serge-rider** [comment]
Somehow it ate line feed.
I can't reproduce this. 
There was a fix in SQL autocompletion after 5.0.3 release (DBeaver won't replace full word if cursor is inside it) - perhaps this also fixes your issue. You coudl test it in EA version.

Thanks for report anyway.

**Comment by offstate** [comment]
I cannot reopen the issue, but the bug is still present in 5.0.4
The problem appears in the names with sign '_'. The parser think this is the end of a word.
