### ISSUE TITLE
Feature request: Ability to disabel/enable constraints and triggers on 

### ISSUE THREAD

**Issue by thiemo-taken** [dbeaver/dbeaver#3374]
Thanks for this great tool!

I reckon buttons/drop down menu entries to disable or enable constraints and triggers would make object managment easier. I think there along TOAD or Oracle SQL Developer.
![grafik](https://user-images.githubusercontent.com/35094030/39170389-a3747a1e-479b-11e8-846c-4bf8157a9345.png)
![grafik](https://user-images.githubusercontent.com/35094030/39170392-a70e24ea-479b-11e8-86b0-8917c043e807.png)

**Comment by ivanelson** [comment]
Like in PGAdmin! By mouse through the user's GUI it is possible to disable the trigger, and still displays the generated DDL.

**Comment by thiemo-taken** [comment]
Ivanelson, would you mind to provide a screenshot? I was not able to find your way unless you ment to recreate the trigger in disabled state - if that's possible that is.

**Comment by uslss** [comment]
verified

**Comment by p91paul** [comment]
OP mentions SQL Developer, which is an Oracle tool. Yet this issue is tagged postgres, and commits are about postgres. Does the Oracle equivalent require another issue to be opened?

**Comment by thiemo-taken** [comment]
Well, it would be nice to have this feature for every supported and supporting database. At least, that was my intention opening this fr.
