### ISSUE TITLE
Feature Request : AutoRefresh navigator tree  on a timer base

### ISSUE THREAD

**Issue by roparo** [dbeaver/dbeaver#3375]
Hello,
After creating a new table or deleting an existing one, the tables list (from navigator window) remains unchanged.

One has to click on Refresh in order to see new table or to not see deleted one.

I don't know how the other tools (sql*developer, etc) do their refreshing but they are displaying correct list of tables at any moment.

Thank you.

**Comment by kseniiaguzeeva** [comment]
Will be implemented in https://github.com/dbeaver/dbeaver/issues/6398
