### ISSUE TITLE
Ctrl+Shift+L does not work when in editor

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#3378]
I have tested to use the Ctrl+Shift+L inside the editor to get the keybindings but it seems that its overwritten or does not work.

If I however select Database Navigator then the keybinding does work.

OS: windows 10
1709 (OS Build 16299.371)

**Comment by nmat** [comment]
on the other hand I can see the keyboard shortcut change in the menu upon select.

So I wonder if this is intentional and in that case, is there documentation over how this all works with the keyboard shortcuts?

**Comment by serge-rider** [comment]
Currently <kbd>Ctrl+Shift+L</kbd> is bound to "Convert to lowercase" command.
But maybe we don't need it, maybe "Convert to uppercase" (<kbd>Ctrl+Shift+U</kbd>) should work as a case toggle.

**Comment by serge-rider** [comment]
In fact there are other default Eclipse shortcuts for upper/lower case commands. These explicit keybidnings were made for very old DBeaver version.
I'll remove them as they doesn't make much sense now.

**Comment by nmat** [comment]
thank you! and very nice job on dbeaver. :)
