### ISSUE TITLE
Tab Delimited File Not Working

### ISSUE THREAD

**Issue by drudd75077** [dbeaver/dbeaver#3379]
Why am I having issues with a dbeavers csv. I have a tab-delimited file. I have changed the connection property to \t and the table is showing up as a single column. I have tried TAB and &#09;. Neither appears to fix the issue. Any help would be excellent.

![image](https://user-images.githubusercontent.com/32606119/39216137-23ae40c2-47e0-11e8-8054-d7d26375efc9.png)

**Comment by wilhelmpaulm** [comment]
I know this doesn't solve your issue but in the meantime why not just replace your tabs with some other character?

**Comment by drudd75077** [comment]
What's the easiest way to do that? Some of these documents are 10 - 30 million lines long

**Comment by freddefred** [comment]
Same problem for me. Anybody with a suggestion on solution?

**Comment by p91paul** [comment]
It works if you copy-paste a tab character into the "separator" field.

**Comment by drudd75077** [comment]
Thanks @p91paul that worked
