### ISSUE TITLE
Wrong DDL when dropping index on Oracle 

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#3380]
DBeaver Version 5.0.3 (Community Edition)

When I try to drop an index on an Oracle table by right clicking it and choosing delete, DBeaver generates the following DDL statement:

`ALTER TABLE MYSCHEMA.MYTABLE DROP INDEX IX_MYINDEX;`

This is wrong! It should be just:

`DROP INDEX IX_MYINDEX;`

**Comment by serge-rider** [comment]
Thanks for report
