### ISSUE TITLE
Wrong/missing name in Open Perspective dialog

### ISSUE THREAD

**Issue by bender316** [dbeaver/dbeaver#3381]
Hi,

I just installed the Eclipse plugin 5.0.3 (fresh installation, no update) and the name of DBeaver is not properly displayed in the Open Perspective view:
![image](https://user-images.githubusercontent.com/36400962/39228652-73376aa4-485f-11e8-95dd-c176f1a03cbc.png)

Eclipse Java EE IDE for Web Developers.
Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200
OS: Windows 10, v.10.0, x86_64 / win32
DBeaver plugin: 5.0.3

Regards,
Daniel

**Comment by ruspl-afed** [comment]
Thanks for report, key restored at OSGI-INF\l10n\bundle.properties
