### ISSUE TITLE
org.jkiss.dbeaver.core is missing a plugin.properties file

### ISSUE THREAD

**Issue by lordyavin** [dbeaver/dbeaver#3382]
Trying to open the DBeaver 5.0.3 perspective displayed the variable `%perspective.name` instead of the perspective name. Looking at the installation and latest sources of the plugin *[org.jkiss.dbeaver.core](https://github.com/dbeaver/dbeaver/tree/devel/plugins/org.jkiss.dbeaver.core)* I see that this variable is used in the [plugin.xml:3801](https://github.com/dbeaver/dbeaver/blob/00c421ebb770a65e057d963157af103e7f5eff0a/plugins/org.jkiss.dbeaver.core/plugin.xml#L3801) for the name of the perspective, but there is no plugin.properties file that defines it.

**Comment by ruspl-afed** [comment]
It should in OSGI-INF\l10n\bundle.properties, will be fixed with #3381

**Comment by lordyavin** [comment]
Duplicate of #3381
