### ISSUE TITLE
Search for matches by the target table name is performed as case-insensitive

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#33843]
### Description

Even if the target table will be in a case-sensitive database. Still can create new table in different case from the navigator
Steps to reproduce:
1. create table with name **TEST test**
2. start export table to a new table (or from CSV)
3. set target table name as existing one, but with different letters case (e.g. **test TEST**, or tEsT teST ...)
![image](https://github.com/dbeaver/dbeaver/assets/43252954/7e62f653-a066-4735-bee4-3d5dc4e522b7)
4. Press Enter. Then the target table name changes to existing one with different case
![image](https://github.com/dbeaver/dbeaver/assets/43252954/c47e2fdc-bab2-401b-a3a2-d66b1c5c0a33)

https://github.com/dbeaver/dbeaver/assets/43252954/77c7f413-709d-4e37-b056-84d4ca3a09e2

### DBeaver Version

24.0.5

**Comment by LonwoLonwo** [comment]
Can be related to this one: https://github.com/dbeaver/dbeaver/issues/22442

**Comment by HocKu7** [comment]
We decided not to fix it for a while
