### ISSUE TITLE
liquiBase integration

### ISSUE THREAD

**Issue by sekaijin** [dbeaver/dbeaver#3384]
Hi
A suggestion :
integrate liquiBase as a tool in DBeaver.
- liquiBase XML/JSON editor
- liquiBase excute/rollBack on database
- generate XML/JSON liquidity from the database state
- more difficult: generate liquiBase chanset from the actions on the database.
  1. something like
  2. set a snapshot
  3. add change remove columns, data, tables etc.
  4. compute the difference with the snapshot
  5. create changeset

Bye

**Comment by serge-rider** [comment]
We plan to integrate with Liquibase for metadata compare/DDL generation.
Making snapshots also sounds interesting.

**Comment by hoyacom** [comment]
How is it going ? I'm very interesting this issue

**Comment by uslss** [comment]
This feature is implemented in scope of 6.1 version. It is available in EE version only.
