### ISSUE TITLE
cannot open oracle connections via SSH tunnel

### ISSUE THREAD

**Issue by lhoekenga** [dbeaver/dbeaver#33849]
### Description

I use tunneled connections for Oracle, and I'm receiving `Cannot invoke "String.length()" because "input" is null
![image](https://github.com/dbeaver/dbeaver/assets/1020459/c5683a2f-7d2b-4da7-bd42-3f0a7843db04)

### DBeaver Version

Community Edition 24.0.5.202405191503

### Operating System

macOS Sonoma 14.5

### Database and driver

DB: Oracle Exadata 19.c
Driver: oracle.jdbc.OracleDriver
- com.oracle.database.jdbc:ojdbc11:RELEASE [23.2.0.0]
- com.oracle.database.nls.orai18n:RELEASE [23.2.0.0]
- com.oracle.database.xml.xdb6:RELEASE [18.3.0.0]
- com.oracle.database.xmlparerv2:RELEASE [23.2.0.0]

### Additional context

SSH tunneling using JSch.
- "Test tunnel configuration" returns success
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/15405680/dbeaver-debug.log)

**Comment by lhoekenga** [comment]
It looks like during an upgrade, the "save credentials" box got checked.  If I uncheck the box, the error goes away, which says to me the thing it's trying to run `String.length()` against is the saved password that I haven't provided via "save credentials".

Even when "save credentials" is checked, I do get a "Password required" prompt for the SSH when opening the DB connection.  I leave "save password" unchecked, and I get the `String.length()` error.

**Comment by lhoekenga** [comment]
Seems like unchecking "save credentials" was a one time fix (for each connection).  The error re-appears intermittently with subsequent application sessions.

**Comment by ShadelessFox** [comment]
Thank you for the bug report.

Perhaps you have exact steps required to reproduce the issue? Are you using TNS/Custom connection type?

**Comment by lhoekenga** [comment]
> Perhaps you have exact steps required to reproduce the issue? Are you using TNS/Custom connection type?
### Basic setup
My oracle connections are set up using ldap based DSN, e.g.
```
jdbc:oracle:thin:@ldap://oidprd1-ora.example.edu:3060/mydatadev,cn=OracleContext,dc=example,dc=edu
```
authentication is set to "Oracle Database Native", with the credentials (username and password) stored.
No changes to Oracle Properties or Driver Properties.

On the SSH tab, the hostname is set to a server that has permission to access the tablespace.
I specify the username, but not the password.  I leave "save credentials" unchecked.  I do not modify anything under "Jump Servers" or "Advanced Settings", although the "Share this tunnel with other connections" box is checked.

### replicate the issue?
I double click on the connection name, and am prompted with "Specify password for SSH tunnel".  The username is pre-filled and I supply the password.  I leave "Save password/passphrase" unchecked.  I get prompted for 2fa (Duo), which I supply.

and then, maybe I get connected, or maybe I get the error `Cannot invoke "String.length()" because "input" is null`

My initial investigation seemed to support that at some point the "save credentials" checkbox under the SSH tab in the connection details became checked, and I could fix it by unchecking it... but subsequent tries have been hit-and-miss.  I seem to be able to get it working again (briefly) if I change the host that I'm tunneling through.

[dbeaver-debug.log.txt](https://github.com/dbeaver/dbeaver/files/15407066/dbeaver-debug.log.txt)

**Comment by ShadelessFox** [comment]
Thank you. Unfortunately, I'm still unable to reproduce the issue. We'll find the potential problems and fix them blindly.

**Comment by ShadelessFox** [comment]
Please try this version and let me know if it helps: https://dbeaver.io/files/ea/

**Comment by ShadelessFox** [comment]
@lhoekenga did you have a chance to test the new version? https://github.com/dbeaver/dbeaver/issues/33849#issuecomment-2129747750

**Comment by lhoekenga** [comment]
> @lhoekenga did you have a chance to test the new version? [#33849 (comment)](https://github.com/dbeaver/dbeaver/issues/33849#issuecomment-2129747750)

Not yet.  I'll pull it down and try.

**Comment by lhoekenga** [comment]
It seems to be better.  I was not able to replicate the issue.

**Comment by arhayka** [comment]
@lhoekenga Thank you for testing!
