### ISSUE TITLE
Enums with ' are incorrectly rendered

### ISSUE THREAD

**Issue by joereynolds** [dbeaver/dbeaver#3388]
I have an Enum with 3 values

Yes
No
Wouldn't Say

In the UI, there are 4 entries in the dropdown for the enum, these are
Yes
No
Wouldn
t Say

It's splitting on the '.

I'm on dbeaver 5.0.3

Thanks!

**Comment by serge-rider** [comment]
I assume it is MySQL issue.
Thanks for report.
