### ISSUE TITLE
ERD: Display relationships on the columns

### ISSUE THREAD

**Issue by maffe** [dbeaver/dbeaver#3389]
I think the ERD view would benefit from a different relationship notation (as an option) which is called “connect to columns” in MySQL workbench. It also seems to be the default (or only) option in Microsoft Access and pgModeler.
![connect to columns](https://user-images.githubusercontent.com/515302/39300097-de4e02b2-494a-11e8-92ea-e43d57333786.png)
With this notation it is clearly visible which columns the foreign keys use without clicking on the relationship (which is not possible on printouts).

**Comment by KrisPetkov** [comment]
Hello @serge-rider @tati-kru 
Do you know if different types of relationship will be implemented soon or is there work in progress on such an item?
And do you have any ETA about that?

Thank you!

**Comment by uslss** [comment]
duplicates #1319
