### ISSUE TITLE
'Close SSH session' with Oracle driver

### ISSUE THREAD

**Issue by kprusov** [dbeaver/dbeaver#3390]
Hi there,

I've encountered the issue with Oracle JDBC driver 11.2.0.4.0 in my Mac when I connect via SSH tunnel to Oracle DB. 

The issue is: 'Close SSH session' has encountered a problem. java.lang.AbstractMethodError

Is it a DBeaver bug?

**Comment by uslss** [comment]
cannot reproduce an issue.
Ticket closed.
If it is reproducible for you feel free to reopen the ticket.
