### ISSUE TITLE
Can't add new User in Oracle DB

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#3392]
**DBeaver 5.0.3 / Mac OS X 10.12.6 / Driver: ojdbc7.jar and ojdbc6.jar**

I am logged into Oracle as the sys user with sysdba role.

I can see all system objects like users, roles, sessions, locks. So fine on this side.

But when I do a right click on the users folder or on a specific user, I am only able to view this user. But I cannot edit it or create a new one. Copy is shown in the context menu but then I am not able to paste in order to create a similar user.

Is there anything that I am doing wrong? Does the sys user need specific privileges? 

DBeaver recognises the sys and shows the locks and security objects. I haven't configured that in the connection properties. So I think there is something wrong.

**Comment by AlanSandovalDev** [comment]
I have the same issue. I hope they answer you to know.

**Comment by serge-rider** [comment]
In fact you can create user. In Oracle User = Schema so just create a schema (you will need to set name and password).
Although this is not very obvious. Not sure how to make it  better..

**Comment by serge-rider** [comment]
I'll add extra explanation in create dialog + extra schema props
