### ISSUE TITLE
Syntax coloring breaks

### ISSUE THREAD

**Issue by ufuk-ergin-carbon** [dbeaver/dbeaver#33951]
### Description

Syntax highlighting/coloring breaks for some unknown reason in the additional WHERE clause statement. Screen recording is attached.

https://github.com/dbeaver/dbeaver/assets/114302087/6b4bc3dd-5fe2-4b91-8aeb-b9f4a46a37c3

### DBeaver Version

Version 24.0.5.202405191503

### Operating System

MacOs Sonoma 14.4.1 (23F79)

### Database and driver

Server: Snowflake 8.20.0
Driver: Snowflake 3.14.4

**Comment by E1izabeth** [comment]
Hello, @ufuk-ergin-carbon 
Have you tried to finish the condition? The query in the video is not correct after AND

**Comment by ufuk-ergin-carbon** [comment]
Hi @E1izabeth, yes, I finished it several times but it does not work. Attaching a screen shot. Let me know if you need a screen recording.

![Screenshot 2024-05-23 at 15 54 17](https://github.com/dbeaver/dbeaver/assets/114302087/3e85e7aa-d2a9-484f-a8f8-f868fe3b926a)

**Comment by E1izabeth** [comment]
I see. Thank you

**Comment by ufuk-ergin-carbon** [comment]
Tested this on Windows. I was able to replicate the issue there.

Also, I think this echoes my previous issue reports where the autocompletion breaks, I found out that whenever Dbeaver is not used for some time (say 2 hours), the autocompletion breaks. If you right click the connection name on the left pane and hit refresh, the functionality does not come back. Only after you expand the connection name and then right click the database name and hit refresh, you get the autocompletion back. If right clicking on the connection name and refreshing is not working, why do we have refresh option on the connection name? Should it not refresh whatever comes below it hierarchically? 

Attaching screenshot for this. Right clicking on the connection name "ANALYTICS_PRODUCTION" does not restore the autocompletion functionality but only ANALYTICS_PROD_DB. If you are pulling data from others, like AI_EHR_DEBUGGER_APP, you need to right click and refresh that too to get the autocompletion functionality.
<img width="233" alt="Screenshot 2024-05-25 at 12 04 58" src="https://github.com/dbeaver/dbeaver/assets/114302087/07d180f5-5b1b-4943-98af-d07eb8cc7d77">

**Comment by ufuk-ergin-carbon** [comment]
Hello folks, I see that this issue was fixed. However, after updating to the latest version today, I still see that ILIKE keyword does not work properly. Attaching a screenshot.

Edit: Tested this on Windows.

![Screenshot 2024-06-24 121338](https://github.com/dbeaver/dbeaver/assets/114302087/8433ef4b-c07b-47ed-bf7e-6ab77f846427)
