### ISSUE TITLE
changes on tnsnames.ora are not noticed

### ISSUE THREAD

**Issue by dbuchhorn** [dbeaver/dbeaver#3396]
If tnsnames are used and the file tnsnames.ora was modified (change server ips or other properties) then this changes are not noticed. It seems not the standard connections string "jdbc:oracle:thin:@tnsname" is used. In the properties viewer the property Server.URL has a value like "jdbc:oracle:thin:@[connect string from the tnsnames.ora file]". The connection must be edited to get the right parameter.

If the oracle thin driver is used then the system property "oracle.net.tns_admin" must be set to the tnsnames.ora directory then the connect string "jdbc:oracle:thin:@tnsname" can be used. The oracle jdbc driver will read the tnsnames.ora file.

If the tnsnames.ora is in a version control system and the .dbeaver-data-sources.xml is in another repository then changes on the tnsnames.ora file implying changes on the dbeaver data source file too.

If you want to change the tnsnames implementation then maybe the oci driver can be supported too (jdbc:oracle:oci:@tnsname).

**Comment by dbuchhorn** [comment]
Any comments are welcome.

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.

**Comment by iron0012** [comment]
I am also experiencing this. Changes made to an entry in a tnsnames.ora file are not picked up by connections in Dbeaver that use the entry. Hovering over the connection entry in Dbeaver to see the connection string as a tool tip confirms that the old connection string is still being used.
