### ISSUE TITLE
[PostgreSQL] Comment DDL missing for views

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#3398]
DBeaver 5.0.4 can read and display view comments but in the DDL/Source the comment SQL is missing:

`COMMENT ON VIEW my_view IS 'my comment';`

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/39757208-d4b814ac-52d4-11e8-90a0-250658a76e3b.png)

**Comment by lemon-juice** [comment]
thanks!
