### ISSUE TITLE
Wrong StartupWMClass for DBeaver Enterprise

### ISSUE THREAD

**Issue by vmaleze** [dbeaver/dbeaver#3399]
Hello,

When using DBeaver Enterprise under Ubuntu the dbeaver.desktop entry is not working. Even if the application launch, the icon I see is "unknown" and I can not attach it to the dock.

To make it work, you need to edit the dbeaver.desktop file => `StartupWMClass=DBeaver Enterprise`

Could it be patch in the debian package ?
I tried to make a pull request but could not find this particular file in your repo.

**Comment by serge-rider** [comment]
Fixed.
Could you check this in EA version (https://dbeaver.com/files/ea/) ?
