### ISSUE TITLE
Improvement - Layout

### ISSUE THREAD

**Issue by douglascomim** [dbeaver/dbeaver#3401]
Hello,
in linux, the status bar gets disorganized using two lines after executing any query.
Would you like to narrow down the highlighted item in the red rectangle to fix this?

You guys do a great job.

Thank you.

_Imagem_
![captura de tela de 2018-04-30 09-22-19](https://user-images.githubusercontent.com/29402875/39427048-ae13f49c-4c58-11e8-95c0-7901f91dbb24.png)

**Comment by uslss** [comment]
can't reproduce.
if issue is still actual for you, feel free to reopen the ticket
