### ISSUE TITLE
exporting base64 in quotes

### ISSUE THREAD

**Issue by Code-Divine** [dbeaver/dbeaver#34012]
Hi,

I am exporting binary column to base64, please make sure the base64 in the exported json is in quotes. Otherwise it's not a valid JSON, and I have to do string replace in every file.

So in short, please make the exported file 
```
{
"id" : "4",
"opis" : TFVNQkFHTyBTTyBJU0lKQUxHSUpB,
"created_on" : "2024-05-21T19:39:30.000Z"
}
```

into this:

```
{
"id" : "4",
"opis" : "TFVNQkFHTyBTTyBJU0lKQUxHSUpB",
"created_on" : "2024-05-21T19:39:30.000Z"
},
```

Thanks

**Comment by E1izabeth** [comment]
Thank you for report.
Connected with #26613

**Comment by Code-Divine** [comment]
Thank you for fixing this. Thank you so much.
