### ISSUE TITLE
[Linux] 'WITH' statement not working for exasol

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#3402]
In the Linux version, when trying to execute some query that has a name defined through `WITH name AS (.)`, it is not possible to later do `SELECT (.) FROM name`. Under Max (running DBeaver 4.3.3.1), the problem is not present and such queries execute properly.

Steps to reproduce:
-Connect to some exasol DB
-Open an SQL Editor tab
-Try to run a valid query with a `WITH` statement - e.g.
```
WITH tbl AS (
SELECT col1 FROM table1 WHERE col2 = 'val'
)
SELECT * FROM tbl
```

Expected Behavior:
-Should return the query results, just like other clients do with the same query

Actual Behavior:
-Throws error 42000 saying that `name` was not found

Reproducible: always

Bug happens with versions 5.0.3 and 5.0.4.

**Comment by Sargul** [comment]
Hi,

i just tried to reproduce the issue and everything works fine AFAIK.

When you get an error 42000 it's from the exasol system and not from DBeaver.

Can you take a look at the execution log and see if the statement executed looks the same as the one in the editor. If not: Please check your statement terminator or blank lines in your statement.
![grafik](https://user-images.githubusercontent.com/5595511/39430219-8b9104fc-4c8d-11e8-9ad2-e72ad5a759a0.png)

**Comment by david-cortes** [comment]
Oh, got the problem - I was hitting Ctrl+Enter and DBeaver was executing only the last line, thereby ignoring the `WITH` that had been defined above. The issue is solved either by selecting the whole code chunk with both the `WITH` and the `SELECT` blocks, or by not putting any empty lines between them.

I think it'd be nevertheless useful to have dbeaver look for potential WITH definitions elsewhere in the editor in these cases, as the same query with spaces in between is executed whole in other clients.

**Comment by Sargul** [comment]
You can change statement parsing by ignoring blank lines.

I would recommend this settings to get the behaviour you want:
![grafik](https://user-images.githubusercontent.com/5595511/39431689-c3d72b62-4c91-11e8-984f-608f9fc9dd9d.png)
