### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Could not load SWT library

### ISSUE THREAD

**Issue by tugalsan** [dbeaver/dbeaver#34034]
### Description

I cannot Start dbeaver, after updating from 24.0.3 to 24.0.5 on Windows Server 2008 R2. The error in the log says Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library

### DBeaver Version

Community Edition 24.0.3 -> 24.0.5

### Operating System

Windows Server 2008 R2

### Database and driver

database: mariadb-10.4.33-winx64
driver: org.mariadb.jdbc.Driver

### Steps to reproduce

1. On my pc (Windows Server 2008 R2) , I had a running dbeaver (24.0.3).<br>
2. It asked for update at startup, I did download the update and extract to a clean folder.<br>
3. When I run the updated dbeaver (24.0.5) it caused attached error.

### Additional context

see the startup error log
[1716420482960.log](https://github.com/dbeaver/dbeaver/files/15409811/1716420482960.log)

**Comment by E1izabeth** [comment]
Thank you for your report. We have reproduced the issue and are investigating.

**Comment by chrisv5** [comment]
Also happens on Windows Server 2012 R2 and DBeaver 24.1.0. My error log is identical (minus the paths, obviously) with those of the OP. I had to revert to 24.0.4.

**Comment by chrisv5** [comment]
Now that I have a working system again, I can give you a hint what went wrong. Of the four SWT DLLs, one was missing. Namely the one in the log (swt-win32-4965r8.dll). Only the specific ones (awt, gdip, wgl) were present.

**Comment by arhayka** [comment]
Unfortunately, after upgrading to Eclipse 2024-06, the following OS are no longer supported: Windows 8, macOS 10, and Windows Server 2012. This issue is not on DBeaver side, you can see the details here: https://github.com/eclipse-platform/eclipse.platform.swt/issues/1252.

We have already added the system requirements to the download pages and are working on ways to warn users before the update.

However, we will keep an eye on the situation and try to do something if possible.

**Comment by yoloz** [comment]
Also happens on Window7 Ultimate Service Pack 1

**Comment by yoloz** [comment]
Also happens on  window 7 Ultimate Service Pack 1 and temporarily i manually modified `eclipse-version` in `root/pom.xml` to `2024-03`, then rebuild and can open it success.
> maybe temporarily remove `-Pall-platforms` in build script, its will create `aarch64` fail

**Comment by E1izabeth** [comment]
Windows Server 2016, Windows Server 2012, and Windows 8.1 are supported again.

**Comment by E1izabeth** [comment]
@tugalsan could you check is the issue is solved for you?

**Comment by rmarzocchi84** [comment]
I confirm: 
DBeaver 24.3.0 works on Windows Server 2012

**Comment by voronamanga** [comment]
I have the same issue on OpenSuse Tumbleweed. Same rpm package works well on OpenSuse Leap 5.7.
