### ISSUE TITLE
Strange timestamp behavior in Oracle

### ISSUE THREAD

**Issue by raqua** [dbeaver/dbeaver#3403]
Hi. 

When I run this SQL on Oracle DB with UTC server settings:
`select current_timestamp, systimestamp from dual;`

I get this in Oracle SQL developer (which I believe is correct):
![screenshot from 2018-04-30 15-35-00](https://user-images.githubusercontent.com/1541886/39429931-baafb1da-4c8c-11e8-92d5-d8d7d58481c7.png)

and this in DBeaver:
![screenshot from 2018-04-30 15-34-57](https://user-images.githubusercontent.com/1541886/39429950-c69449ac-4c8c-11e8-83e1-5c0e4a81b39d.png)

**Comment by Sargul** [comment]
I think this is related to #238

**Comment by serge-rider** [comment]
Yep, it is.
