### ISSUE TITLE
Altibase: Update tablespace information

### ISSUE THREAD

**Issue by zennken** [dbeaver/dbeaver#34048]
Hello,

I'd like to update tablespace information.
1. List of tables belonging to a specific table space
2. List of table spaces accessible to a specific user

Thanks,

**Comment by E1izabeth** [comment]
Hi, @zennken . Thank you for creating issues. 
We wonder is it your plan for contribution? 😄

**Comment by zennken** [comment]
Hello, @E1izabeth

Long time no see :) 

First of all, I would like to share the good news that Altibase users are very happy to have the DBeaver available. I'll be very glad if I have a chance to contribute to the DBeaver again. If you don't mind, I'm planning to take care of these issues whenever I have time, so it might take some time. Is that okay? 

https://github.com/dbeaver/dbeaver/issues/33392
https://github.com/dbeaver/dbeaver/issues/34040
https://github.com/dbeaver/dbeaver/issues/34041
https://github.com/dbeaver/dbeaver/issues/34042
https://github.com/dbeaver/dbeaver/issues/34044
https://github.com/dbeaver/dbeaver/issues/34045
https://github.com/dbeaver/dbeaver/issues/34046
https://github.com/dbeaver/dbeaver/issues/34047
https://github.com/dbeaver/dbeaver/issues/34048

Have a great weekend :)

**Comment by E1izabeth** [comment]
It sounds great. Thank you :)
