### ISSUE TITLE
Confusion on ConnectionSetting for parameters useSSL and sslMode

### ISSUE THREAD

**Issue by tugalsan** [dbeaver/dbeaver#34049]
**Is your feature request related to a problem? Please describe.**
I am frustrated on configuring connection for SSL. I do not understand the tests I did by chaging the parameters on Connection Setting. There is two parameters I am changing. Connection_Settings->Driver_Properties->sslMode:DISABLED/REQUIRED/PREFFERED  |  Connection_Settings->SSL->Use SSL

**Describe the solution you'd like**
I wish UseSSL will be renamed as sslMode. and she will be a combobox rather than Checkbox. And when I change it from SLL tab, the Driver_Properties->sslMode also automatically updated. 

**Describe alternatives you've considered**
I think, useSSL is a deprecated parameter. For compatability reasons, may be my solution is not valid. Another more better solution can be presented.

**Additional context**
For now from ssl to non-ssl, I am changing both parameters for security reasons. just to be sure.

**Comment by LonwoLonwo** [comment]
Hello @tugalsan 

All driver properties (non-custom) come from the driver side. This list depends on the driver version.
We can't change these properties. 
But in DBeaver, we have the SSL tab on the connection page. Maybe you can use this form for connection: https://github.com/dbeaver/dbeaver/wiki/SSL-Configuration

**Comment by E1izabeth** [comment]
We discussed and decided that we would like to add information about how this option overrides driver properties in the description for the "Use SSL" checkbox.
![image](https://github.com/user-attachments/assets/4f0ef80c-e299-42ec-8e3b-d290c2ea2c8d)
This settings priority is higher than in driver properties.
