### ISSUE TITLE
Altibase: Explain execution plan parsing error when TRCLOG_DETAIL_MTRNODE = 1 option used.

### ISSUE THREAD

**Issue by zennken** [dbeaver/dbeaver#34042]
### Description

Parsing error occurs at explain execution plan for Altibase when the following query has been set to print MtrNode.
ALTER SYSTEM SET TRCLOG_DETAIL_MTRNODE = 1;

### DBeaver Version

Community edition 24.0.0

### Operating System

Windows 11

### Database and driver

Altibase 7.3.0 or higher

### Steps to reproduce

1. Run the following SQL statements
DROP TABLE T50764;
CREATE TABLE T50764 ( I1 INT, I2 INT, I3 INT );
INSERT INTO T50764 VALUES ( 1,1,1);
INSERT INTO T50764 VALUES ( 2, 2, 1);
INSERT INTO T50764 VALUES ( 3,1, 1);
ALTER SYSTEM SET TRCLOG_DETAIL_MTRNODE = 1;

2. Click 'Explain execution plan' with the following SQL at DBeaver SQL editor -> Parsing error
SELECT * FROM T50764 WHERE I1 > 0 AND I2 > 0 ORDER BY I1; -> Explain execution plan

![image](https://github.com/dbeaver/dbeaver/assets/32251385/3b35bbeb-644c-4b4b-b1a2-50c4ae2235ce)

**Comment by E1izabeth** [comment]
Thank you for bug report
