### ISSUE TITLE
Setting default database on connect based on username

### ISSUE THREAD

**Issue by brlarini** [dbeaver/dbeaver#34055]
### Description

While trying to connect to a given PostgreSQL server which has one database with the same name as its user (also its owner), still doesn't set that database as default, as implied it would do in the connection setup.
Upon connection, the default database is always set to 'postgres' instead.

The 'Database' field says it will use the username to set the default one, if left emtpy:
![image](https://github.com/dbeaver/dbeaver/assets/23079160/41fe2fe7-36d4-4787-92f0-3ef8c55e8b2c)

Leaving those fields empty prompts the user for both the username and password. Then the expected result is DBeaver setting the default database as the same username informed on connect.

This feature would help on the workflow, as the user wouldn't need to go to the database list and set the desired one as default.
We have lots of sample databases that are created and deleted frequently, so setting one profile for each database only to be changed soon after is a chore on itself.

So, I wanted to know if what I described is in fact the intended behavior of the empty database field (therefore a bug?), or if it has another purpose that I maybe didn't understand correctly.

Thanks!

### DBeaver Version

Community Edition 24.0.5.202405191503

### Operating System

Windows 10

### Database and driver

- PostgreSQL 16 server
- PostgreSQL JDBC Driver 42.7.2

**Comment by E1izabeth** [comment]
For me it looks like a bug. Thank you for report.

**Comment by E1izabeth** [comment]
However, I can't reproduce the issue. Am I doing something different than you?

https://github.com/dbeaver/dbeaver/assets/28875055/191ae05d-1e0f-4d72-9f96-f2172836114b

**Comment by brlarini** [comment]
Hi, thanks for replying.
I noticed you're using a database named 'e1izabeth**db**' and username 'e1izabeth'. DBeaver indeed refuses to connect if there isn't a database with the same name as the username.
However, if you go and create a database with the **same** name as the user, then it connects BUT sets 'postgres' as the default anyway.

**Comment by E1izabeth** [comment]
Ok, got it. Thank you for explanation
