### ISSUE TITLE
Lost edited datas

### ISSUE THREAD

**Issue by didiandalucia** [dbeaver/dbeaver#34065]
### Description

Edit datas in more as one records (data - inline editing), after save button looks good and when actualize, then diferented fields are has the same default (null) as before! So thats crazy to make the same editing more times! The problem exists in actual and version before. I have never seen before!

### DBeaver Version

Community Edition Version 24.0.5.202405191503

### Operating System

Linux Mint

### Database and driver

Percona 5.7.0 

### Steps to reproduce

Open table and edit records - save - check ok - actualize

**Comment by E1izabeth** [comment]
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by ShadelessFox** [comment]
Perhaps you are using transactions? Make sure to commit after you finish changing the data.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
