### ISSUE TITLE
Backticks are exported as double backticks when exporting resaults from query as SQL

### ISSUE THREAD

**Issue by diabuiltbypixel** [dbeaver/dbeaver#34060]
### Description

When trying to export the data that came out from a query result single backticks are converted to double.

Here is the data I got from the query:

<img width="976" alt="Screenshot 2024-05-23 at 4 47 14 PM" src="https://github.com/dbeaver/dbeaver/assets/167980911/d03c2074-f39b-4d00-973c-b23be05030b8">

And here is how it's generated after I click Export to SQL INSERT statements:

<img width="386" alt="Screenshot 2024-05-23 at 4 51 57 PM" src="https://github.com/dbeaver/dbeaver/assets/167980911/e73a57f1-3895-4816-8c45-51c744515cb4">

### DBeaver Version

Version 24.0.4.202405051837

### Database and driver

MySQL 8

### Steps to reproduce

Just select any column that has a backtick (`) and try to export it as SQL statement and the result will be double backticks (``)

**Comment by diashalabi** [comment]
https://github.com/dbeaver/dbeaver/pull/34167

**Comment by E1izabeth** [comment]
Thank you for bug report.
