### ISSUE TITLE
Firebird and BLOB Data

### ISSUE THREAD

**Issue by SynapseUser** [dbeaver/dbeaver#3406]
Hi -

I have recently been working with php and Firebird to upload BLOB files to a database. For some time I thought my upload was being corrupted as when I used the "Edit / Save As" option - the resulting file was the wrong size and was no longer in the format it was originally uploaded in.

Specifically, image data. I uploaded an image - used the Save as option and when I tried to view the saved file - got an error basically saying it could not be identified as an image.

Does DBeaver do some processing of the data before saving that would account for this ? Shame its not working as being able to save blob fields is very useful when testing.

Thanks.

**Comment by mrotteveel** [comment]
I have just inserted and retrieved a sizable image file using DBeaver and it loads just fine without corruption, and the inserted image has exactly the same size as the image on disk (both before insert and after loading). Without a suitable reproduction recipe, it is more likely that your PHP application corrupted the image on save.

_Note: I'm not part of the DBeaver team, but I maintain the Firebird JDBC driver_

**Comment by mrotteveel** [comment]
A `blob sub_type 1` is a `blob sub_type text`, which means you are trying to store binary data in a text column. That is not going to work (or at least, you'll get corruption because of character set transliteration issues).

If you want to store binary data, you need to use a `blob sub_type binary` (== `blob sub_type 0`).

**Comment by SynapseUser** [comment]
Ahh ok, that would explain it then. Sorry for wasting your time and thanks for all the work you do :)
Cheers.
