### ISSUE TITLE
Exports file as "{table}_{timestamp}.sql"

### ISSUE THREAD

**Issue by hollerith** [dbeaver/dbeaver#3408]
The export data function is no longer naming the files properly. It uses the literal template rather than substituting the intended variables. 

Version 5.03+

**Comment by serge-rider** [comment]
Just use `${table}_${timestamp}` pattern.
I believe support of legacy patterns (without dollar prefix) was ended a few versions ago.
To view all available patterns press ctrl+space in text field (or see tooltip).

**Comment by hollerith** [comment]
Yes I had noticed the tooltip had the ${thing} format and used that instead, thought I had the same issue but it probably used the previous one. I have verified that it works okay for me. Thanks. Release notes eh. must read them sometime.  :)
