### ISSUE TITLE
Importing scripts fails.

### ISSUE THREAD

**Issue by realgeek** [dbeaver/dbeaver#3409]
DBeaver-community 5.0.4 via homebrew cask on High Sierra.

I have script files from a prior install of DBeaver on another machine. When I attempt to drop them into General/Scripts and then execute them, I get "No property pages for Script-5.sql."

When I attempt to use File->Import->DBeaver->Scripts to import the scripts to my MySQL-localhost connection, I get "Resource '/General/Scripts' does not exist." I tried creating that path and putting the scripts in there, but I get the same thing. 

Interestingly, the import says it works for the dbeaver default test database. But of course, any statement in my script that references a MySQL db name will fail.

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on the issue for a long time
additional info is needed to reproduce an issue.
ticket will be closed. feel free to reopen an issue and add info that could help to investigate it.
