### ISSUE TITLE
How to list all databases in a REDSHIFT connection?

### ISSUE THREAD

**Issue by ANTGOMEZ** [dbeaver/dbeaver#3412]
Started using DBeaver last week, loving it so far. However, it will not list all the databases for Redshift - I'm using the redshift driver (jdbc:redshift://). Looks like I have to make a new connection for every database. The PostgreSQL connection lists all the DB's.

Or am I missing some setting somewhere?

BTW, Aginity lists all the Redshift DB's.

Thanks!

**Comment by serge-rider** [comment]
Since 5.1.6 we use PostgreSQL extension for Redshift.
Just check "Show non-default databases" option in connection properties.
