### ISSUE TITLE
Improvement - Change shortcut

### ISSUE THREAD

**Issue by witoreel** [dbeaver/dbeaver#3413]
I was using the application and tried to use the "Fetch All Rows" shortcut (Ctrl + Alt + End).
Curiously, it was the same shortcut on linux (at least on Mint) to Turn Off the computer.
I guess it's a little dangerous this shortcut conflict, so I think would be better using a new shortcut.

**Comment by serge-rider** [comment]
Agreed.
However it is not so easy to find a good shortcut.
Any contras for <kbd>ctrl+alt+page up</kbd>?

**Comment by witoreel** [comment]
I hadn't found any contra for ctrl+alt+page up. 
What do you think about ctrl+alt+page down? For me, down is more compatible with download the data and getting to the end of file (like ctrl + alt + end in text files).
But, ctrl+alt+page up is as good as down.

**Comment by serge-rider** [comment]
ctrl+alt+page down already reserved for next page reading. I found out that also these shortcuts are used by Eclipse framework for editors switching.

I'll change fetch page and fetch all to <kbd>CTRL+\ </kbd> and <kbd>CTRL+ALT+\ </kbd>.
