### ISSUE TITLE
Issue when ugrading dbeaver eclipse plugin in 5.0.4

### ISSUE THREAD

**Issue by nanard34** [dbeaver/dbeaver#3414]
Having the following error after update to 5.0.4 (Eclipse Mars).

An error has occurred. See error log for more details.
org.jkiss.dbeaver.ui.OverlayImageDescriptor.createCachedImageDataProvider(Lorg/eclipse/jface/resource/ImageDescriptor;)Lorg/eclipse/jface/resource/CompositeImageDescriptor$CachedImageDataProvider;

**Comment by serge-rider** [comment]
Yep. This is because of Oxygen API dependency (for HIghDPI support).
Will fix that, thanks for report.
