### ISSUE TITLE
Can't Update or Insert on Tables using INHERIT (Postgres)

### ISSUE THREAD

**Issue by joshuamcginnis** [dbeaver/dbeaver#34141]
### Description

I recently started running into issue where I'm unable to issue UPDATES or INSERTS on Postgres db tables which inherit time objects and constraints. (e.g. `INHERITS (my_schema.timed_object);`)

All updates generate this error (note it always says *new row* even on updates):

> Error synchronizing data with database
Reason:
SQL Error [23514]: ERROR: new row for relation "my_table" violates check constraint "timed_object_created_at_check"

The affected tables all inherit from this table:

```sql
CREATE TABLE my_schema.timed_object (
id uuid DEFAULT uuid_generate_v1mc() NOT NULL,
created_at timestamptz DEFAULT now() NOT NULL,
updated_at timestamptz DEFAULT now() NOT NULL,
CONSTRAINT timed_object_check CHECK (false) NO INHERIT,
CONSTRAINT timed_object_created_at_check CHECK ((date_part('timezone'::text, created_at) = '0'::double precision)),
CONSTRAINT timed_object_pk PRIMARY KEY (id),
CONSTRAINT timed_object_updated_at_check CHECK ((date_part('timezone'::text, updated_at) = '0'::double precision))
);
```

`selects` and `deletes` work fine, but all attempts to save edits from the Data tab or issue manual UPDATES that satisfy the constraint fail.

I have tried:
* Downgrading DBeaver (this just started happening in the last week)
* Using an older version of the local client

### DBeaver Version

CE 24.0.5

### Operating System

macOS Sonoma 14.5

### Database and driver

![image](https://github.com/dbeaver/dbeaver/assets/391074/eb8a9422-a812-450e-ba94-4d1d9752a750)

### Additional context

The exact same updates and inserts work fine in other clients (e.g. Postico or psql).

**Comment by LonwoLonwo** [comment]
Hello @joshuamcginnis 
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by joshuamcginnis** [comment]
@LonwoLonwo I would like to share both logs and a screenshare of me replicating the issue. How can I share these with you confidentially? I don't want to share my logs (which contains hosts, db names, table names, etc) in public.

**Comment by E1izabeth** [comment]
You can send it to me

**Comment by joshuamcginnis** [comment]
Logs and video sent @E1izabeth

**Comment by ShadelessFox** [comment]
Hello @joshuamcginnis,

Are you sure the `timed_object_check` makes sense? Judging by its definition, it's always evaluated to `false`. I don't quite understand how it's supposed to work in the first place.

**Comment by ShadelessFox** [comment]
I can see that in your case, the `timed_object_created_at_check` is the culprit. It checks the current timezone and ensures it's UTC. Can you please try changing your timezone to UTC here?

![Image](https://github.com/dbeaver/dbeaver/assets/35821147/cd004032-f3bd-49a4-8b1d-047e15ed9deb)

Please let me know if it works.

**Comment by joshuamcginnis** [comment]
@ShadelessFox Yes, that fixed it. Thank you. Two quick questions:
* The Timezone config was set to `Default` by default. What does that refer to? I've never had to modify this before.
* Why is the created_at constraint being fired on updates?

**Comment by ShadelessFox** [comment]
1. The "Default" timezone means the timezone set in the system settings in the OS.
2. Every time you modify data in your table (by inserting, deleting, or updating), the database uses all table constraints to validate that your data's integrity is valid. Most databases don't let you specify which events will trigger a constraint. In such cases, you would use database triggers for that.

**Comment by joshuamcginnis** [comment]
That makes sense. I guess other clients like Postico just default to UTC which is why I never had this issue with other clients. I appreciate your help on this!
