### ISSUE TITLE
Kaspersky Endpoint Security for Windows 12.1.0.506 thinks dbeaver-cli.exe is malware

### ISSUE THREAD

**Issue by Yigitttttttt** [dbeaver/dbeaver#34154]
### Description

Hi, I open this issue bcoz in milestone 24.0.5 the problem not solved.
Kaspersky Endpoint Security for Windows 12.1.0.506 still thinks dbeaver-cli.exe is malware. Could you find a solution for this?

### DBeaver Version

24.0.5

### Operating System

windows 10

### Steps to reproduce

I use portable version. After unzip Kaspersky says malware found.

**Comment by ShadelessFox** [comment]
Hello @Yigitttttttt,

What the report says, exactly?

**Comment by Yigitttttttt** [comment]
It's very strange, but I think with the new Kaspersky update, there is no longer a malware alarm. Thank you
