### ISSUE TITLE
Invalidate/Reconnect takes a long time - reopening #1885

### ISSUE THREAD

**Issue by yuriscom** [dbeaver/dbeaver#3415]
I'm referring to a closed ticket #1885. It is closed, but in version 5.0.4 community edition for mac it's still a big problem. Every time i have to wait for socket timeout up to 5-10 minutes. disconnect + connect is not solving it either.

**Comment by serge-rider** [comment]
Yes, it is still a problem.

I think we can use some kind of DBeaver-side timeout for disconnect. If it won't finish in time then just ignore it (eventually socket will finish and will be collected by GC).

**Comment by serge-rider** [comment]
I've added connect/disconnect/invalidate timeouts. 
They are configurable:
![image](https://user-images.githubusercontent.com/6398845/39946169-d20d2dfc-5575-11e8-9707-c6b06af45c6e.png)

Please check how it works in 5.0.5.
