### ISSUE TITLE
Integrate column management into the data view editor

### ISSUE THREAD

**Issue by danielrosehill** [dbeaver/dbeaver#34162]
In the data view editor you can't delete a column in the table through the GUI:

![26_104124](https://github.com/dbeaver/dbeaver/assets/40233203/4f945a85-3aff-4f80-b36c-8f410fe36957)

This can be accomplished within the column dropdown navigation, however:

![26_104209](https://github.com/dbeaver/dbeaver/assets/40233203/93aa2982-03e3-4946-a3b5-f1f98f736670)

It would be useful to be able to drop columns from the table in the data view / UI

**Comment by arhayka** [comment]
This seems to be dangerous.
You can switch to the Properties tab to delete columns.
