### ISSUE TITLE
SSH Tunnel issue

### ISSUE THREAD

**Issue by shamsheerothayoth** [dbeaver/dbeaver#34172]
### Description

When try to reconnect idle connection using SSH tunnel giving below error

The connection attempt failed.

Sometime EOF Exception.

Only after restart dbeaver i can connect.

### DBeaver Version

24.0.5

### Steps to reproduce

1.) Open connection using ssh tunnel
2.) After long idle time connection disconnected
3.) try t reconnect

Only with SSH tunnel having the issue

### Additional context

The connection attempt failed.

**Comment by E1izabeth** [comment]
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\\.metadata directory. In case your OS isn't Windows, here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by geourjoa** [comment]
Hi

I have also issue when trying to connect to a database through SSH tunnel with DBeaver. It was impossible to access the database with this way or using public/private key method.
I was getting this error : 
![image](https://github.com/dbeaver/dbeaver/assets/122985699/8f237919-cd2c-43fc-a51c-4ae1f0dc5254)

I solved by : 
- Uninstalling Dbeaver (previously install via snap as described [here](https://dbeaver.io/download/)
- Reinstall using .deb package (I'm on Ubuntu 22.04 LTS)

Everything is working right after. Problem probably came from snap isolation ?

**Comment by E1izabeth** [comment]
The author of this issue haven't specified the OS, so we can't guess.

**Comment by erickbonas** [comment]
I have a similar problem with tunnel connection. 

**DBEaver Version**:  24.1.0.202406021658

**OS version**: Ubuntu 22.04.4 LTS

**Database**: Mysql 

![image](https://github.com/dbeaver/dbeaver/assets/1825196/a8b1dba7-81c9-4a87-9d7c-cdc4d356491d)

[dbeaver-debug.log](https://github.com/user-attachments/files/15787358/dbeaver-debug.log)

**Comment by E1izabeth** [comment]
@shamsheerothayoth is this issue still actual for you?
Could you share your ssh configuration? Do you use SSHJ or JSCH? Do you have jump servers?

**Comment by shamsheerothayoth** [comment]
@E1izabeth I am using jump server. I am not able to replicate the issue now.

**Comment by E1izabeth** [comment]
Thank you for response. I'm closing this issue then
