### ISSUE TITLE
Saving changes in the grid

### ISSUE THREAD

**Issue by lavalex** [dbeaver/dbeaver#3417]
Hello,

Is it possible that after I change a cell, I will be able to press CTRL+S right away, without hitting on Enter? It's not very comfortable.

**Comment by lavalex** [comment]
When I'm editing a field, in order to apply the change to the database, I need to hit Enter, so the field will be applied in the grid and then ctrl+s to apply the change to the database.

In similar too, that I currently switched from, I could hit ctrl+s right away, so field was applied to the grid and then whole row to the database.

Hope it's more clear now.

**Comment by serge-rider** [comment]
Good point.
It will work with <kbd>CTRL+S</kbd> and <kbd>CTRL+ALT+S</kbd> shortcuts.
