### ISSUE TITLE
If DbEaver is open on windows and shutdown PC there is a problem

### ISSUE THREAD

**Issue by MatteoBaudino** [dbeaver/dbeaver#34178]
### Description

If I had DBeaver Community Edition 24.0.5.202405191503 open and shutdown my Windows 11 notebook it waits and cannot stop the software and the PC cannot be turned off.

### DBeaver Version

Community Edition 24.0.5

### Operating System

Windows 11

### Database and driver

PostgreSQL e SQLServer JDBC

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
