### ISSUE TITLE
I was able to delete a row in a DB that was read only.

### ISSUE THREAD

**Issue by DanielCardiel** [dbeaver/dbeaver#34179]
### Description

Due to data security issues, I cannot give more information. But, I had the client DB in read only.
I was able without an issue to remove data from the DB with "DELETE FROM..."_

### DBeaver Version

community Version 23.2.0.202309041200

### Operating System

Windows 11

**Comment by ShadelessFox** [comment]
DBeaver does not limit you from submitting database queries in read-only mode. It's simply not possible to cover all cases.

What you can do instead is to create a separate database user with limited access.

**Comment by arhayka** [comment]
We discussed this issue with the team and decided to do the following: we can restrict INSERT, DELETE, and UPDATE, DROP, CREATE, ALTER execution via SQL Editor if the connection is in the Read-only mode.
Not configurable.
Error message.
