### ISSUE TITLE
Select statement on Oracle database creates a new pending transaction 

### ISSUE THREAD

**Issue by premyslc** [dbeaver/dbeaver#34184]
### Description

When i execute a select statement on Oracle DB, dbeaver creates new pending transaction in the pending transactions list. Any subsequent select queries do the same. Then i have many pending trasactions in pending list but in reality, there is no transaction on database level. 

select dbms_transaction.local_transaction_id from dual;
Select above returs NULL, because there is no transaction on DB level.
Select statement is not modifying statement on Oracle.

### DBeaver Version

24.0.1

### Operating System

Linux, Windows

### Database and driver

Oracle JDBC Driver, 11.2.0.3

### Steps to reproduce

1. Execute select statement on Oracle database
2. Pending transaction counter is increased for each subsequent select

**Comment by E1izabeth** [comment]
You probably want to switch transaction mode https://github.com/dbeaver/dbeaver/wiki/Auto-and-Manual-Commit-Modes
Does it satisfy your needs? If no, please specify the concrete steps to reproduce the issue - at least types of the statements you execute.

**Comment by premyslc** [comment]
> You probably want to switch transaction mode https://github.com/dbeaver/dbeaver/wiki/Auto-and-Manual-Commit-Modes Does it satisfy your needs? If no, please specify the concrete steps to reproduce the issue - at least types of the statements you execute.


Seems that AutoCommit with Smart Commit is what i need. 
Thanks

**Comment by E1izabeth** [comment]
I'll close the issue then. If you experience some issue with it, please let me know and I'll reopen it.
