### ISSUE TITLE
Copying from table view generates UTF-16 text instead of UTF-8

### ISSUE THREAD

**Issue by braiam** [dbeaver/dbeaver#3418]
How to reproduce:

1. Create a table and column with data. In my case the backend is MariaDB 10.1.28, using charset utf8mb4 and collation utf8mb4_unicode_ci for the table and the column
2. Use `select * from table` in the table view
3. Copy the result and paste it in LibreOffice Calc

What should happen:

Text being detected as UTF-8 without trouble.

What happens instead:

Text import dialog informs you that the character set is UTF-16. Changing to UTF-8 adds a extraneous extra line between each cell.

Additional details:

I'm not entirely sure why it happens. The entire database is set to use the real UTF-8. If I paste it into Excel it just paste the whole thing with the extra line in the middle.

I created a empty database to test this. The connection/client/server is set to use UTF-8 where it makes sense.

**Comment by uslss** [comment]
cannot reproduce an issue.
Ticket closed.
If an issue is still actual for you - feel free to reopen it
