### ISSUE TITLE
copy and paste not work on Mac

### ISSUE THREAD

**Issue by iriskyc** [dbeaver/dbeaver#34186]
### Description

I use command c & v for copy & paste but fail. Also command z did't work

### DBeaver Version

24.0.5

### Operating System

mac OS 12.7.5 

### Database and driver

postgre. scripts

### Steps to reproduce

close and re-open, sometimes work , sometimes didn't work

**Comment by E1izabeth** [comment]
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by AdamHyski** [comment]
I am experiencing the same problem on
DBeaver Version
24.1.0

Operating System
mac OS Version 14.5 (23F79)

Database and driver
Oracle

this is the only log entry I have
```
2024-06-13 12:29:59.820 - Paste error: clipboard contains data in unsupported format
```

[edit] 
I wanted to clarify problem occurs when I try to copy the connection to the database

**Comment by Matvey16** [comment]
@AdamHyski  Did you try clicking on anyhing in the navigator before pasting? Also are you sure about the content of your clipboard in the moment of pasting it? I wasn't able to reproduce it. Maybe you can make a short video with this issue?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
