### ISSUE TITLE
After upgrade ver. 23.xx to 24.0.5 existing connections hangs

### ISSUE THREAD

**Issue by Koryakov** [dbeaver/dbeaver#34193]
### Description

I updated DBv to the latest version, 24, from 23.xxx, and since then, 2 out of 3 connections in Database Navigator were hang.
I use default JDBC driver to MSSQL.

I re-created connection, but the New Connection window is hanging while testing the connection...
After that I create connection again (in the same way) and it works.

### DBeaver Version

24.0.5

### Operating System

Windows 10 Enterprise

### Database and driver

MS SQL 15.0.4355.3	RTM	Developer Edition (64-bit)
Microsoft  JDBC driver to MSSQL.

### Additional context

its a cloud VMs

**Comment by serge-rider** [comment]
Try to enable option "Trust server certificate" on the connection settings dialog.

**Comment by Koryakov** [comment]
> Try to enable option "Trust server certificate" on the connection settings dialog.

Thanx for advise, but after a few attempts without cert trusting it also works  :)

**Comment by E1izabeth** [comment]
Does it still reproducible?

**Comment by Koryakov** [comment]
> Does it still reproducible?
I think I cannot reproduce the same situation because it happened with existing connections after version updating.
Now if I add new connections to the same servers it creates without problems
