### ISSUE TITLE
No way to save procedure

### ISSUE THREAD

**Issue by rccc** [dbeaver/dbeaver#34191]
### Description

I used ti click on the green "save" icon to save modifications on a procedure.

Now, a window is open, ask me to open editor, copy or cancel, but connat save my script.

### DBeaver Version

Version 24.0.5.202405191503

**Comment by ShadelessFox** [comment]
Hello @rccc,

I'm not sure what this issue is about. Can you elaborate, please?

**Comment by rccc** [comment]
@ShadelessFox 

Hello ! Thanks for your attention.

In fact i understand that a specific option is now checked by default : 
https://github.com/dbeaver/dbeaver/issues/7915

I have just found this option to uncheck !

Thanks a lot.

**Comment by ShadelessFox** [comment]
Okay, so I'm going to close the issue.
