### ISSUE TITLE
DuckDB filtering on columns with spaces doesn't work

### ISSUE THREAD

**Issue by frankzandhuis** [dbeaver/dbeaver#34192]
### Description

When I have this sample query in Dbeaver with DuckDB :memory: setting:

`SELECT 'test' AS "test value"`

And I want to filter on this column, via:
<img width="659" alt="image" src="https://github.com/dbeaver/dbeaver/assets/58481860/a5958a95-2a1f-4409-8623-a8a116dc01a1">

I get this error:

`SQL Error: java.sql.SQLException: Parser Error: syntax error at or near "value"`

Probably because this SQL is generated automatically:

```
SELECT * FROM (
SELECT 'test' AS "test value"
) z_q WHERE test value = 'test'
```

If I copy this SQL to a new tab and change it as follows (enclose column name with double quotes), it does work:

```
SELECT * FROM (
SELECT 'test' AS "test value"
) z_q WHERE "test value" = 'test'
```

The request is to have filter queries and group by panel queries automatically enclosed with double quotes, as per the DuckDB standard: https://duckdb.org/docs/sql/keywords_and_identifiers.html

A possibly related issue might be Grouping on columns with a `/` (slash) in the column name. However, if you want I can make a separate ticket for this.

Perhaps this bug/ request is related to: #23020 and/ or #24122 

### DBeaver Version

Community edition Version 24.0.1.202403241413

### Operating System

Windows 11 Pro x64

### Database and driver

duckdb_jdbc-0.10.3.jar with `:memory:` as Path

### Steps to reproduce

Create :memory: connection to DuckDB
Execute MWE query as described above
Attempt to filter on this value, as per the printscreen

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
The same issue happens in any database (e.g. SQLite)

**Comment by serge-rider** [comment]
Another fix proposed. Previous broke composite attribute expressions.
