### ISSUE TITLE
Oracle DDL for View please extend the statetment with comment part

### ISSUE THREAD

**Issue by progsurfer** [dbeaver/dbeaver#3419]
Hi,
can you please  to the DDL Statement for the View the comment part if the comment on is existing ?

You did it already for the table DDL :)

It would be very helpful.

Best regards 

Denis

**Comment by LonwoLonwo** [comment]
Reading DDL Statement for Views and Materialized views like in Oracle Tables implemented.

**Comment by uslss** [comment]
Verified
created issue #10154
