### ISSUE TITLE
Implements database data comparator 

### ISSUE THREAD

**Issue by gabrieltomio** [dbeaver/dbeaver#342]
## Use Story

As an user I want to compare table and database data.
Today the system provides a database schema comparator, but is extremely useful for database managers and software testers compare data.

---
## Example

**Database 1 - Table 1**

| First Field | Second Field |
| --- | --- |
| 1 | 2 |
| 3 | 4 |

**Database 2 - Table 1**

| First Field | Second Field |
| --- | --- |
| 1 | 2 |
| 5 | 4 |

**Diff between Database 1 and Database 2**

| First Field | Second Field |
| --- | --- |
| **5** | 4 |

The feature can be used like the schema comparator.

![feature](https://cloud.githubusercontent.com/assets/18080156/14325029/c8df0f1c-fbfd-11e5-8926-3108f49e3418.png)

---
## Use cases
- Compare deployment and production database
- Check algorithm's results in database
- Help software CRUD tests
- Help software regression tests
- Generate data mutation history (log)
- ETC

---

Sorry about my english (I am from Brazil ><).
Thanks a lot.

**Comment by RobertoDebarba** [comment]
That feature would be awesome.

As a software tester, in legacy system I can't mock or test software routines without database, and that's useful for check the result data.

I searched for a good software to do this, but I can't find nothing good and price free, and free software, impossible! :smile:

I think it will be a great feature!

My suggestion for implementation is export data to a file format like JSON and call the Eclipse file comparator. Today I use something similar, exporting the data to JSON files and using WinMerge to see the diff.
![capturar2](https://cloud.githubusercontent.com/assets/5933968/14325467/d57a5c0c-fbff-11e5-9f3d-8a95029e136c.PNG)

**Comment by mrkeuz** [comment]
+1 for this feature!

**Comment by efradkin** [comment]
Good tables data comparer is implemented in the JetBrains DataGrip:
![image](https://user-images.githubusercontent.com/16664546/34084511-cd68badc-e392-11e7-8257-a0c565f14b43.png)
