### ISSUE TITLE
Error on `\connect db_name` while executing SQL-script

### ISSUE THREAD

**Issue by dayfuaim** [dbeaver/dbeaver#34207]
### Description

I've done the SQL-script with DB_NAME > Tools > Backup.

When I want to restore my DB from this script, DBeaver stops with error on `\connect <DB_NAME>` line:
```sql
CREATE DATABASE XXXXX WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'C';

ALTER DATABASE XXXXX OWNER TO YYYYY;

\connect XXXXX
```

Error is:
```
SQL Error [42601]: ERROR: syntax error at or near "\"
  Позиция: 1
  ERROR: syntax error at or near "\"
  Позиция: 1
  ERROR: syntax error at or near "\"
  Позиция: 1
```

`psql < ~/my_script.sql` work normally.

Please, fix this.

### DBeaver Version

Community Edition 24.0.5.202405191503

### Operating System

macOS Sonoma 14.5

### Database and driver

1. DB: PostgreSQL 14.0
2. PostgreSQL JDBC driver 42.7.2

### Steps to reproduce

1. Create DB backup in SQL format. "DROP if exists" & "CREATE if not exists" should be on.
2. Try to restore DB from this script: open the file, push `Alt-X` (`Option-X`).
3. Get an error.

**Comment by ShadelessFox** [comment]
Hello @dayfuaim,

The `\connect` is a meta-command available only in PSQL. DBeaver doesn't know anything about it.

What you want to do instead is to use **Tools -> Restore**.

**Comment by dayfuaim** [comment]
@ShadelessFox Thanks for the answer.
This helped.
😎
