### ISSUE TITLE
Eclipse scrollable and display errors since DBeaver version 24.0.5

### ISSUE THREAD

**Issue by TB-HunBoka** [dbeaver/dbeaver#34209]
### Description

Discussion:
https://github.com/orgs/dbeaver/discussions/34173#discussioncomment-9605771

After installing the Darkest Dark theme, and setup a custom color or change the icon color, the UI strangely behave and sometimes raises errors. (Change the icon color setting generates Unable to generate image error)
Example setup:
![image](https://github.com/dbeaver/dbeaver/assets/126617861/2c728ad6-6bef-41af-809a-19ed49045d1f)

For example the metadata panel looks like this:
![image](https://github.com/dbeaver/dbeaver/assets/126617861/db880555-b42f-477c-b095-0f9aacab8646)

The error log tab is not rendered correctly:
![image](https://github.com/dbeaver/dbeaver/assets/126617861/fe677356-630e-4d96-80f9-d00e1336c4f7)

The Key preferences raise an error:
![image](https://github.com/dbeaver/dbeaver/assets/126617861/84273ca4-c8ba-4df2-b1c8-9749a2725906)
An error has occurred. See error log for more details.
Cannot invoke "com.codeaffine.eclipse.swt.widget.scrollable.context.Reconciliation.runWithSuspendedBoundsReconciliation(java.lang.Runnable)" because "this.reconciliation" is null

_With the DBeaver 24.0.5 some Eclipse plugin was upgraded from 2023-12 eclipse to 2024-03_

Error logs:
[eclips.scrollable.error.at.export.window.log](https://github.com/dbeaver/dbeaver/files/15500634/eclips.scrollable.error.at.export.window.log)
[eclips.scrollable.error.at.Keys.settings.log](https://github.com/dbeaver/dbeaver/files/15500635/eclips.scrollable.error.at.Keys.settings.log)

### DBeaver Version

Community Edition Version 24.0.5.202405191503

### Operating System

Windows 10

### Steps to reproduce

1. install DBeaver 24.0.5 or 24.1.0
2. install darkest dark theme
3. change the theme to any darkest dark theme
4. change the icon color settings (not required, but generates more error)
5. restart the dbeaver
6. Try to open the Keys preferences or file / export (I think any scrollable window works)

### Additional context

I installed the dbeaver on top of my Eclipse ide 2024-03 and I could install darkest dark theme. Had no issue with it. It can be some version conflict between eclipse plugins.

**Comment by TB-HunBoka** [comment]
Little update I saw:
org.eclipse.osgi.services plugin is not installed by default, but when I install the darkest dark theme on 24.0.4 I got multiple lincence approval:
![kép](https://github.com/dbeaver/dbeaver/assets/126617861/ec5932e0-d077-493c-ae02-6f1091385b67)
On 24.1.0 it is a single licence:
![kép](https://github.com/dbeaver/dbeaver/assets/126617861/f4666333-ae68-48e9-9c39-7503373ff8de)

The required org.eclipse.osgi.services is installed by default on the Eclipse Ide, thats why it was working on the Eclipse IDE installing dbeaver as a module.

Also I saw this error while installing the darkest dark on 24.1.0:
Cannot complete the install because one or more required items could not be found.
  Missing requirement: Enhanced Explorer 2024.1.0.202402281519 (com.genuitec.eclipse.meexplorer 2024.1.0.202402281519) requires 'osgi.bundle;  0.0.0' but it could not be found
  Software being installed: DevStyle with CodeTogether Bundle 2024.1.0.202402281519 (com.genuitec.eclipse.theming.feature.feature.group 2024.1.0.202402281519)
  Cannot satisfy dependency:
    From: DevStyle (includes Darkest Dark Theme) 2024.1.0.202402281519 (com.genuitec.eclipse.theming.core.feature.feature.group 2024.1.0.202402281519)
    To: org.eclipse.equinox.p2.iu; com.genuitec.eclipse.meexplorer [2024.1.0.202402281519,2024.1.0.202402281519]
  Cannot satisfy dependency:
    From: DevStyle with CodeTogether Bundle 2024.1.0.202402281519 (com.genuitec.eclipse.theming.feature.feature.group 2024.1.0.202402281519)
    To: org.eclipse.equinox.p2.iu; com.genuitec.eclipse.theming.core.feature.feature.group [2024.1.0.202402281519,2024.1.0.202402281519]

**Comment by humphreygao** [comment]
this error is related to eclipse clean sheet plugin https://github.com/fappel/xiliary, you could report it there.

**Comment by TB-HunBoka** [comment]
Hey @humphreygao,
Can you help me what should I write in the issue ticket on xiliary? What part of the log, or how do you know it is xiliary related? I would copy that part there.
Thanks

**Comment by TB-HunBoka** [comment]
Happy to announce that this issue is resolved with 24.1.4 DBeaver + Latest Darkest Dark theme.
