### ISSUE TITLE
Oracle session manager shows %productName 5.0.3

### ISSUE THREAD

**Issue by crowne** [dbeaver/dbeaver#3420]
The Remote Program names in the Session manager are displayed as follows:

- %productName 5.0.3 - View sessions
- %productName 5.0.3 - Main
- %productName 5.0.3 - Metadata

**Comment by serge-rider** [comment]
It is definitely a bug but I can't reproduce it.
Do you use standalone version or Eclipse plugin? CE or EE?

**Comment by crowne** [comment]
I've used the Eclipse plugin CE.

**Comment by serge-rider** [comment]
Thfnks for bug report

**Comment by cesarmansur** [comment]
Hello!
I'm having same issue using Eclipse plugin.

Eclipse version: 2020-03
![image](https://user-images.githubusercontent.com/43681608/80285163-648a8600-86f9-11ea-9e77-18ce1987bc93.png)

Dbeaver plugin: 7.0.3
![image](https://user-images.githubusercontent.com/43681608/80285182-8be15300-86f9-11ea-9b1e-5fecc4a534e3.png)

Operating System: Windows 10 Pro 64-bit
![image](https://user-images.githubusercontent.com/43681608/80285299-3e191a80-86fa-11ea-8997-a030431fc288.png)

Windows notification area:
![image](https://user-images.githubusercontent.com/43681608/80285313-5426db00-86fa-11ea-8946-9972d4a6fb06.png)

Oracle session details:
![image](https://user-images.githubusercontent.com/43681608/80285320-61dc6080-86fa-11ea-8633-841532b5feb4.png)
