### ISSUE TITLE
[CUBRID] Create and Edit Trigger using UI

### ISSUE THREAD

**Issue by longhaseng52** [dbeaver/dbeaver#34201]
Allow an alternative option for user to create and edit Trigger using UI.

**Comment by longhaseng52** [comment]
We are thinking of 2 options for implementing our Trigger:
1. Follow the existing plugins like MySQL, Oracle.
2. Create a new customize UI based on our preferences.

For us, we would like to go with option 2. 
What is your suggestion?

**Comment by E1izabeth** [comment]
You can try going by the second path, why not. However, I suppose better show us your plans for this UI earlier, than later, to come together to a UI that we will merge.
