### ISSUE TITLE
Autocomplete not working anymore in 5.0.4

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [dbeaver/dbeaver#3421]
I updated dbeaver from 5.0.2 to 5.0.4 and now the auto completion of table names is not working like before.

I connected to SQL Server 2016 with Microsoft Driver.

In previous version I could do 'select * from bta<suggestion>' and I was able to choose the correct entry
Now I have to put 'dbo.' before the table name, otherwise I'm always prompted 'no proposal'.

I read about option 'use short object names' but it's now working either.
Could you help me? This is really annoying

**Comment by amivanovano** [comment]
5.0.4 + Informix = not working too.

**Comment by Teofast** [comment]
Same issue with mssql DBMS, still working with oracle.

**Comment by douglascomim** [comment]
Here is also happening in MSSQL.

**Comment by gabriele-ricci-kyklos** [comment]
@serge-rider Any feedbacks for this issue?

**Comment by serge-rider** [comment]
Could you check this in EA version (https://dbeaver.io/files/ea/)?
I believe I fixed an issue in auto-complete on the last week..

**Comment by gabriele-ricci-kyklos** [comment]
Not working either in EA version 5.0.5 x64.
The only changing is that it tries to autocompletes the name of the database.
Downgrading to 5.0.3 for now, I hope this will be fixed in the next version.
Many thanks

**Comment by serge-rider** [comment]
Thanks for testing. I think I've just found and fixed the problem. 
New EA was published.

**Comment by nmat** [comment]
I think this is still a bit of a problem.

The first autocomplete does not read tables but next command or database.

Then the columns are not in autocomplete list either. The only way to get this is by using dbo. still to get the autocomplete.

Using: 5.0.5 against mssql

**Comment by serge-rider** [comment]
It works for tables if you use <kbd>ctrl+space</kbd> after first letters of table name. 
The same for columns.
If you don't specify schema then DBeaver searches columns in database (executing object search queries) and this could be not very fast if you have a remote database. That's why it is disabled by default.
Maybe we should have a special option for "smarter" autocomplete..

Could you create another ticket for that?

**Comment by nmat** [comment]
I will create a another ticket for "smarter" autocomplete based on active database/schema.

For now I guess the way to write the table a little longer and then press Ctrl+Space works to get around it.

Thank you @serge-rider
