### ISSUE TITLE
Export data base64

### ISSUE THREAD

**Issue by brankotasevski** [dbeaver/dbeaver#34215]
### Description

When exporting data with base64 as value in JSON format is exported base64 but without quotes and JSON is not valid.

### DBeaver Version

24.0.5

### Operating System

Windows 11

### Database and driver

Firebird

### Steps to reproduce

1. Add base64 value in column 
2. Export data
3. Export target - JSON
3. Proceed

**Comment by E1izabeth** [comment]
Thank you for bug report. You can try Early Access version - it should be fixed there https://dbeaver.io/files/ea/
Alternatively, you can check the next release on Monday - the fix is included there.

**Comment by E1izabeth** [comment]
Has been done in scope of #26613
