### ISSUE TITLE
java.sql.SQLSyntaxErrorException when trying to query Duckdb schema

### ISSUE THREAD

**Issue by Jeroen-Sen** [dbeaver/dbeaver#34216]
### Description

Duckdb can have multiple schema's in a single database file. In my case, for testing purposes, I created a database file named 'discogs_diff' having 2 schema's ('discogs_today' and 'discogs_yesterday'). These schema's both contain tables named 'artist', 'release' and 'artist_release'.

![Screenshot 2024-05-31 at 10 48 02](https://github.com/dbeaver/dbeaver/assets/14215991/a5cc037d-c2f6-4946-a3b2-f53c8e7f5f27)

The SQL generated by DBeaver to query a table is correct. It uses the convention <database>.<schema>.<table>.

![Screenshot 2024-05-31 at 10 48 27](https://github.com/dbeaver/dbeaver/assets/14215991/bb0ae57b-7476-4414-8ef3-49e37c75f63e)

Executing the SQL however, results in an error.

![Screenshot 2024-05-31 at 10 52 18](https://github.com/dbeaver/dbeaver/assets/14215991/51eafd91-71a1-4cb4-aee3-93291104505d)

Looks like the SQL syntax parser doesn't handle the convention <database>.<schema>.<table> correctly (for Duckdb?).

Note 1: executing the query in the Duckdb CLI obviously works correct.
Note 2: I didn't test this for other databases which support the same feature.

### DBeaver Version

Community Edition Version 24.0.5.202405191503

### Operating System

macOS Sanoma 14.5

### Database and driver

1. Database name and version: DuckDB 8.3.0
2. Driver name and version: ? (Regular driver, probably most recent version)

### Steps to reproduce

1. Execute any query containing <database>.<schema>.<table> convention.

**Comment by LonwoLonwo** [comment]
Hello @Jeroen-Sen 

Could you please provide a screen from your driver's libraries?
You can do it in your connection settings -> driver settings -> libraries

Because I see the MySQL driver name on your screen, not DuckDB

Or did you choose maybe the incorrect connection in your SQL Editor? 

You can check this info in the top toolbar

![2024-05-31 18_44_19-Window](https://github.com/dbeaver/dbeaver/assets/45152336/d46e954f-2465-45ac-ba5f-8919fa951ad1)

**Comment by Jeroen-Sen** [comment]
Aha, that is the case. However, it looks like the connection will always default into the MySQL connection I have enabled. That's kinda shitty.

**Comment by LonwoLonwo** [comment]
We do not have such a logic. Your scripts are bound to your data sources.
If you can make a video of this issue

> However, it looks like the connection will always default into the MySQL connection I have enabled.

I would appreciate it.

**Comment by E1izabeth** [comment]
Is this issue still actual?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
