### ISSUE TITLE
Cannot connect to plugin update site.

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#34227]
### Description

Cannot connect to plugin update site.

### DBeaver Version

DBeaver Community 24.1.0

### Operating System

Window10

### Steps to reproduce

Help -> Install New Software -> Dbeaver Office interation

### Additional context

**When I access the update site (https://dbeaver.io/update/office/latest), a "404 Not Found" error occurs.**

![image](https://github.com/dbeaver/dbeaver/assets/59002295/6dbae5e2-f38d-40ed-b72e-dfb35ab625d5)
![image](https://github.com/dbeaver/dbeaver/assets/59002295/ee01e626-e914-4623-925b-a0e78c5c9be1)
![image](https://github.com/dbeaver/dbeaver/assets/59002295/c4b6fdde-259e-49d7-bba5-ef947040f6eb)
![image](https://github.com/dbeaver/dbeaver/assets/59002295/1026b92c-3025-4e07-9798-fdcb4e74f0fd)

Thnak for reading. :)

**Comment by serge-rider** [comment]
It is an issue in release publishing process.
Release has been fixed but we still investigate the root cause.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
