### ISSUE TITLE
Debugging Oracle PL/SQL procedures and functions

### ISSUE THREAD

**Issue by erkilinc** [dbeaver/dbeaver#34236]
**Is your feature request related to a problem? Please describe.**
It is required debugging Oracle PL/SQL procedures and functions in Dbeaver. Except this, developers should have to use a different tool

**Comment by E1izabeth** [comment]
Thank you for idea. It's a duplicate of #3404
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.
