### ISSUE TITLE
Can the refresh button be placed in the same place

### ISSUE THREAD

**Issue by MrRohwei** [dbeaver/dbeaver#34246]
Double click on the table name to view the refresh of the table property bar in the bottom right corner, but the refresh of the data bar is in the bottom left corner

### data bar
<img width="417" alt="image" src="https://github.com/dbeaver/dbeaver/assets/35440977/a8896d9f-1d08-4713-8c6a-d2eaf8dd972b">

### property bar
<img width="1114" alt="image" src="https://github.com/dbeaver/dbeaver/assets/35440977/08133808-34da-4a54-8b7d-66547ffa79de">

**Comment by E1izabeth** [comment]
Thank you for report. We agree, that it would be nice to bring more consistency here.
We want to make it similar to Data Editor.
