### ISSUE TITLE
Mock data with multiple unique constraints per column

### ISSUE THREAD

**Issue by ADoby** [dbeaver/dbeaver#3425]
I have a simple column for many-many relation:

```
CREATE TABLE public."UserPermissions" (
	"Id" varchar NOT NULL,
	"UserId" varchar NOT NULL,
	"PermissionId" varchar NOT NULL,
	CONSTRAINT userpermissions_pk PRIMARY KEY ("Id"),
	CONSTRAINT userpermissions_un UNIQUE ("UserId", "PermissionId"),
	CONSTRAINT userpermissions_permissions_fk FOREIGN KEY ("PermissionId") REFERENCES "Permissions"("Id"),
	CONSTRAINT userpermissions_users_fk FOREIGN KEY ("UserId") REFERENCES "Users"("Id")
)
WITH (
	OIDS=FALSE
) ;
```

**Users** table only has one user in it: "testuser"
**Permissions** table has many permissions.

When I try to mock data for "UserPermissions" it only generates one entry and then tells me about an error:
    Error generating mock data: 
      Can't generate appropriate unique value for the 'UserId' <varchar> attribute.
      Try to change the generator or its parameters.

It seems like it is trying to generate mock data per column.
The unique constraint should allow for many entries with "testuser" in the "UserId" column and different entries in "PermissionId" column.

**Comment by efradkin** [comment]
@ADoby, multi-columns unique constraints support will be included in the next version.
