### ISSUE TITLE
Autocomplete on self joins does not work with "Enable experimental features" turned on

### ISSUE THREAD

**Issue by juutilainenj** [dbeaver/dbeaver#34251]
### Description

If "Enable experimental features" is turned on, autocomplete with self joins only works with alias mentioned last.

![self_join_ac_select](https://github.com/dbeaver/dbeaver/assets/17760082/abe2bb19-d511-462a-a808-1c795fd8f3d0)
![self_join_ac_tri_select](https://github.com/dbeaver/dbeaver/assets/17760082/2016ff8f-d573-4237-80ff-d7383985765e)
![self_join_no_props_select](https://github.com/dbeaver/dbeaver/assets/17760082/c02e5bbc-c399-4840-999d-15ffbf31473d)
![self_join_no_props_tri_select](https://github.com/dbeaver/dbeaver/assets/17760082/79889d62-5133-4c18-adef-f874058ae5c3)

### DBeaver Version

Community Edition 24.1.0.202406021658

### Operating System

Windows 10

### Database and driver

MySQL 8.0.36-commercial
MySQL Connector/J mysql-connector-j-8.2.0 (Revision: 06a1f724497fd81c6a659131fda822c9e5085b6c)

### Steps to reproduce

1. Make sure "Enable experimental features" option is on
2. Write self join statement
3. Try autocomplete

**Comment by E1izabeth** [comment]
Thank you for bug report.
