### ISSUE TITLE
Eclipse plugin not updated to 24.1

### ISSUE THREAD

**Issue by danielgp** [dbeaver/dbeaver#34254]
### Description

https://dbeaver.io/update/latest/ still reflects releases on 19th of May 2024 although a 2nd of June 2024 is 2 days ago...

### DBeaver Version

Eclipse 4.31

### Operating System

any platform

### Database and driver

irrelevant

### Steps to reproduce

Open https://dbeaver.io/update/latest/ and if you see files and folders older than 2024-06-02 (thatțs 2nd of June 2024) than no most recent release is reflected as advertised on official website

**Comment by E1izabeth** [comment]
Thank you for report.

**Comment by E1izabeth** [comment]
We updated files in `latest`

**Comment by danielgp** [comment]
Thank you very much!
