### ISSUE TITLE
DBeaver UE  Start Task Schedule Unable to output csv to AWS S3

### ISSUE THREAD

**Issue by tsukasa-shimizu** [dbeaver/dbeaver#34260]
### Description

I am using DBeaver UE. When I run the DataBase task Schedule, I can't put csv to AWS S3. Please tell me how to solve it.

### DBeaver Version

DBeaver Ultimate 24.0.0.202404011634

### Operating System

Window Server 2022

### Database and driver

1.data export：DB2 for IBM i
2.data put：AWS S3(Cloud Explorer connect)

### Steps to reproduce

1.DataBase Task Create
2.Data export from DB2 for IBM i ⇒ Create CSV to AWS S3

①Manually(Run task) executed from the console　Success
②Using Schdule Tasks NG(ERROR)

Error message
illegal char <:> at index 2 s3://aws/<bucket>

**Comment by E1izabeth** [comment]
Thank you for bug report
Please create a ticket on our support system available for PRO users: https://dbeaver.com/support/
(you can add a link on this issue there)

**Comment by E1izabeth** [comment]
@tsukasa-shimizu 
Have you contacted our tech support team?

**Comment by tsukasa-shimizu** [comment]
@E1izabeth 
I contacted this site. Please tell me how to solve it.

**Comment by E1izabeth** [comment]
They'll investigate the issue and try helping you.

**Comment by tsukasa-shimizu** [comment]
What action should I take?

**Comment by E1izabeth** [comment]
Please, wait for the answer for your ticket on our support system.

**Comment by tsukasa-shimizu** [comment]
Thank you!
We are waiting for a response from our support team.

**Comment by E1izabeth** [comment]
We fixed the bug, connected to the issue in DBeaver 24.1.3
https://github.com/dbeaver/dbeaver/pull/34745
