### ISSUE TITLE
Creating View through UI Results in Error

### ISSUE THREAD

**Issue by CaptZapp1729** [dbeaver/dbeaver#34267]
### Description

When creating a view through the UI (Right click on Views, then Create New View), and saving after entering SQL code, the Persist Changes window comes up with only the text "CREATE OR REPLACE VIEW <schema.viewname> AS;
Clicking Persist results in "ERROR: syntax error at end of input Position: 46"
Incidentally, the same happens if updating a previously defined view.

![Screenshot 2024-06-05 092739](https://github.com/dbeaver/dbeaver/assets/108160009/fe78949b-cdfc-4723-a063-3f513756d732)
![Screenshot 2024-06-05 092650](https://github.com/dbeaver/dbeaver/assets/108160009/da8b8d45-0841-4d18-a119-9305fd75a778)

### DBeaver Version

Community Edition 24.1.0.202406021658

### Operating System

Windows 11

### Database and driver

PostgreSQL 15.3 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit
PostgerSQL JDBD Driver 42.7.2

### Steps to reproduce

1. Expand Schema to Views
2. Right Click on Views, select Create New
3. Enter SQL source on the source tab
4. Save View

### Additional context

Creating or Replacing a View by entering a SQL script in the SQL editor works fine.

**Comment by ShadelessFox** [comment]
Thanks for the bug report. I was able to reproduce the issue.

**Comment by serge-rider** [comment]
Fix will be in the next version (and we will probably rerelease 24.1 later this week).

**Comment by CaptZapp1729** [comment]
Updated this morning, and it is working now. Thank you for the quick response and turn-around!

**Comment by serge-rider** [comment]
Thank you for checking this
