### ISSUE TITLE
Turn on "Show all databases" by default for PostgreSQL

### ISSUE THREAD

**Issue by Flyslinger2** [dbeaver/dbeaver#34265]
### Description

psql \list:
`KeyCloak    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 dev-file    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 flyslinger2 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
             |          |          |             |             | postgres=CTc/postgres
 template1   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
             |          |          |             |             | postgres=CTc/po

![Screenshot from 2024-06-05 08-22-39](https://github.com/dbeaver/dbeaver/assets/38768547/cbb6d603-795f-4321-b7a4-2c061d8112d4)
`

### DBeaver Version

CE 24.1.0

### Operating System

Ubuntu 18.04

### Database and driver

PostgreSQL 12.18 (Ubuntu 12.18-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, 64-bit

### Steps to reproduce

Refreshing database doesn't list additional dbases.

**Comment by E1izabeth** [comment]
Have you check this setting?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/d614587a-0d6d-421d-bb37-bf7fb9bd95cf)

**Comment by Flyslinger2** [comment]
-.-

I'm viewing all of this in HyperV and apparently it doesn't like to present the full screen.  I had to monkey around with video settings to find that switch. 

Got it. 

Got the dbases. 

Thanks much!

**Comment by Flyslinger2** [comment]
Silly question. Shouldn't that be enabled by default? Why wouldn't you want to see ALL dbases?

**Comment by flambchap** [comment]
@Flyslinger2 PostgreSQL's wire protocol requires opening a separate physical connection for each catalog. On top of that, for performance reasons, DBeaver opens two connections for each db instance (one general, one for metadata read). This means that if you have N catalogs in a PostgreSQL instance and 'Show all databases' on, DBeaver opens `N * 2` sockets. In production environments, it's common to set an upper limit for the number of simultaneous connections from one user, and with this setting on, it's really easy to hit one.
