### ISSUE TITLE
generating DDL of redshift table stalls out

### ISSUE THREAD

**Issue by tim-oe** [dbeaver/dbeaver#34275]
### Description

when trying to generate the DDL for certain tables will not complete
lower right shows status of "generating DDL" with a bar that blinks
the backound tasks tab shows a bar with no progress.
only restarting dbeaver will stalled process die

### DBeaver Version

Version 24.1.0.202406021658 community

### Operating System

windows 11

### Database and driver

RDS cluster version: [1.0.68540](https://docs.aws.amazon.com/redshift/latest/mgmt/cluster-versions.html)

server:
Redshift 8.0.2
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.68540

driver:
Redshift JDBC Driver 2.1.0.22

### Steps to reproduce

select reshift table and try to generate DDL

### Additional context

using SSL for connection

**Comment by serjiokov** [comment]
Hello @tim-oe, Is the same behavior for any table in a cluster or just specific? 
Could you provide log details, please?  
https://dbeaver.com/docs/dbeaver/Log-files/#log-files

**Comment by tim-oe** [comment]
it's random for tables throughout the cluster, both big and small.
[dbeaver-debug-1717643998831.log](https://github.com/user-attachments/files/15821297/dbeaver-debug-1717643998831.log)
[dbeaver.log](https://github.com/user-attachments/files/15821313/dbeaver.log)
[dbeaver2.log](https://github.com/user-attachments/files/15821330/dbeaver2.log)


[dbeaver-debug-1717648434491.log](https://github.com/user-attachments/files/15821298/dbeaver-debug-1717648434491.log)
[dbeaver-debug-1717648820398.log](https://github.com/user-attachments/files/15821299/dbeaver-debug-1717648820398.log)

i needed this for shutting down the instance so i no longer have an instance to verify with

**Comment by alejandrofm** [comment]
Same issue on Community Version 24.1.1.202406231636
MacOs
Sometimes it gets fixed restarting DBeaver, sometimes not, have to restart until it works and then starts failing again.

**Comment by LonwoLonwo** [comment]
Related https://github.com/dbeaver/dbeaver/issues/8473

**Comment by E1izabeth** [comment]
@tim-oe 
Does DDL generating works at least for 1 table? Does it stable reproducible for you?

**Comment by alejandrofm** [comment]
It's random, but when it stops working (after showing one or two DDLs), the only way to fix it is to restart DBeaver

**Comment by tim-oe** [comment]
i could get 1 or 2 tables to gen but once it goes off in the weeds you have to recycle the app.
if i try to do it for multiple tables it always hangs. it didn't seem to matter the table size, ie # of columns or the data size

**Comment by serge-rider** [comment]
It looks like this issue is also related to the new Redshift driver which breaks connection unexpectedly during SQL query executions.
Downgrade to 2.1.0.9 version solves most of issues.

**Comment by Destrolaric** [comment]
@tim-oe, @alejandrofm  Hi, could you see if a workaround suggested by @serge-rider works for you?

**Comment by alejandrofm** [comment]
A combination of updating to dbeaver to Version 24.1.3.202407211303
and driver downgrade to 2.1.0.9 solved all my issues

**Comment by tim-oe** [comment]
Sorry no longer have access to Redshift. I'm closing this as a driver error
