### ISSUE TITLE
Error trying to open a DBF file.

### ISSUE THREAD

**Issue by CarlossDMC** [dbeaver/dbeaver#34271]
### Description

When i was trying to open .DBF file I got this error
![image](https://github.com/dbeaver/dbeaver/assets/83795819/090e8264-273a-4120-b428-2801252aef91)
![image](https://github.com/dbeaver/dbeaver/assets/83795819/5ea7420d-816d-4a1c-8911-e466e841eb54)
![image](https://github.com/dbeaver/dbeaver/assets/83795819/70be5764-9af4-4f22-9bba-73619387c732)

### DBeaver Version

Community edition 23.3.5

### Operating System

Windows 11

### Database and driver

DBF

### Steps to reproduce

1. I select the DBF option in the connections menu.
2. Put a folder that has a lot of DBF files.
3. I did try to do a simple SELECT * FROM myfile.

**Comment by E1izabeth** [comment]
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\\.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
