### ISSUE TITLE
DBeaver freezes due to a non-responding script tab

### ISSUE THREAD

**Issue by ShaliChand** [dbeaver/dbeaver#34276]
### Description

When DBeaver freezes due to a non-responding script tab, it is impossible to close the specific tab 

None of the below steps helped
**1. Use Task Manager (Windows) or Activity Monitor (Mac)**
First, ensure that DBeaver is not entirely unresponsive. If the entire application is frozen, you may need to force quit and restart it.

Windows:

Press Ctrl + Shift + Esc to open Task Manager.
Locate DBeaver in the list of running applications.
Right-click on DBeaver and select End Task.

**Increase Memory Allocation**
Sometimes, DBeaver freezes due to insufficient memory allocation. Increasing the memory available to DBeaver can help mitigate this.

Steps:

Locate the dbeaver.ini file in the DBeaver installation directory.
Open the dbeaver.ini file in a text editor.
Increase the values for the -Xms (initial heap size) and -Xmx (maximum heap size) parameters. For example:
-Xms1024m
-Xmx4096m
Save the file and restart DBeaver.

**Update or Reinstall DBeaver**

### DBeaver Version

24.1.0

### Operating System

Windows

### Database and driver

PostgreSQL 14
Driver default settings . (SQLite JDBC driver) . Unable to confirm at this point since the Dbeaver is frozen

### Steps to reproduce

Connect to the database.
One of the Script tab does not respond
Entire Dbeaver is frozen 
![image](https://github.com/dbeaver/dbeaver/assets/133135984/c3bd31c1-72c3-429a-acf2-5e5855b50086)

### Additional context

Connecting via TSH  (teleport)

**Comment by tim-oe** [comment]
i've turned off SSL and still get same behavior tried against linux install Version 24.1.0.202406021658
Background Tasks shows "Loading SQL Source..." never finishes

**Comment by tim-oe** [comment]
I can run Show Table and it completes

**Comment by serjiokov** [comment]
Hello @ShaliChand, Could you please provide the log details,
https://dbeaver.com/docs/dbeaver/Log-files/#log-files

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by Impaler67** [comment]
I, too, increased limit settings in the .ini file, but I still have the same issue because DBeaver never uses the whole amount of available RAM, it just stops responding
