### ISSUE TITLE
ERROR AFTER FORMATTING SQL

### ISSUE THREAD

**Issue by cristianchies** [dbeaver/dbeaver#3427]
Lets say I have this SQL query, when I run it, as it is, works fine!!
```
SELECT ID FROM CUSTOMER WHERE EMAIL LIKE :email;
```

Then when i resolve to format the query (Ctrl + Alt + F), as below, It shows me error "SQL Error [1008] [72000]: ORA-01008: not all variables bound"

```
SELECT
	ID
FROM
	CUSTOMER
WHERE
	EMAIL LIKE:email;
```
This is an error with the junction of "LIKE" and ":email" if a add a space between than it works just fine!
I was not able to find a configuration for this any where.

SQL Formatting configuration:
![image](https://user-images.githubusercontent.com/1386342/39628900-dea2da80-4f80-11e8-97f6-0e08d59b6634.png)

DBeaver Version:
![image](https://user-images.githubusercontent.com/1386342/39628982-0e83d11e-4f81-11e8-92f6-25cf2aa18682.png)

**Comment by serge-rider** [comment]
Thanks for report
