### ISSUE TITLE
Wrong default browser on Linux

### ISSUE THREAD

**Issue by Yanpas** [dbeaver/dbeaver#3428]
Running `xdg-open http://ya.ru` opens this URL in google chrome, but all links in dbeaver are opened in Firefox.

I use kde, the default browser is settings is google-chrome. Eclipse uses google chrome as default too (4.7.3)

**Comment by serge-rider** [comment]
Well, this seems to be related: https://bugs.eclipse.org/bugs/show_bug.cgi?id=439529
But that doesn't resolve the problem. Perhaps we need to add web browser configuration page to CE version. Maybe just in Linnux distribution..

**Comment by hal869** [comment]
With DB 5.1.6 CE, on Linux, links -- e.g. "Install DBeaver Extensions" (trying to get the SSH extension ...) -- open a new Firefox instance (not using an existing instance), with no URL populated.  I.e., just a blank page.

Afaict, there's no 'usual' Preferences -> General -> WebBrowser setting, dialog, etc.

**Comment by uslss** [comment]
Ticket is closed as not actual anymore.
Default web-browser could be chosen in Preferences.
![image](https://user-images.githubusercontent.com/31996417/66121543-22c3b200-e5e6-11e9-9f84-c89cd3cd6004.png)
BTW, if problem is still actual for you, feel free to create new ticket.
