### ISSUE TITLE
Unable to consistently execute queries

### ISSUE THREAD

**Issue by AussieScorpio** [dbeaver/dbeaver#34291]
### Description

I have several servers running Postgres and MySQL and connecting through SSH. Sometimes when I execute SQL against one of these servers, the results come back in the time expected; sub-second for simple queries, a few seconds for queries requiring joins or table scans. Unfortunately, about half the time, the query sits there with the elapsed time ticking over and not returning results. Sometimes I can rectify this by doing invalidate/reconnect, though often I need to do this more than once. Sometimes I need to close DBeaver and reopen it. It's a major productivity killer.

I've noticed whilst DBeaver is open, it's constantly displaying a message saying "Datasource invalidated".

I don't understand why this is such an issue. Maintain a connection; fine. Reconnect if it drops; also fine, but whatever happens I should always be able to execute a query without having to take any other action first. I've never worked with a SQL client tool that is so temperamental. How can I prevent this from occurring?

I know it's not a network issue as I have SSH sessions open that aren't dropping and applications on my local machine that need to access remote databases aren't having issues. This is something particular to how DBeaver works.

### DBeaver Version

Version 24.1.0.202406021658

### Operating System

Ubuntu 22.04

### Database and driver

psql (PostgreSQL) 10.22
psql (PostgreSQL) 15.2

(happens with both)

/home/genesys/snap/dbeaver-ce/304/.local/share/DBeaverData/drivers/maven/maven-central/org.postgresql/postgresql-42.7.2.jar

### Steps to reproduce

Execute SQL against a remote DB. Repeat. Pretty soon it will happen.

### Additional context

SSH with private key.

**Comment by ShadelessFox** [comment]
Can you please try reproducing the issue again and send log files afterward? https://github.com/dbeaver/dbeaver/wiki/Log-files#log-files

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
