### ISSUE TITLE
Connection isn't getting Stored when connecting to C* in Docker

### ISSUE THREAD

**Issue by anote2chris** [dbeaver/dbeaver#3429]
When using DBeaverEE, I set up a connection to Cassandra (in Docker on a mapped port) and the "Test Connection" succeeds, but the connection config isn't stored and available under the "Database Navigator" section of the app.

I've tried simple things like giving a simple name instead of the one it defaults to, but no luck.

**Comment by serge-rider** [comment]
I'm not sure I quite understand the use-case.
In order to save connection you need to click "Finish" in connection wizard, not just "Test connection".
