### ISSUE TITLE
An error is reported when dbeaver is on

### ISSUE THREAD

**Issue by Lming2024** [dbeaver/dbeaver#34294]
### Description

[1717469353238.log](https://github.com/user-attachments/files/15722340/1717469353238.log)

### DBeaver Version

24.1.0

### Operating System

Windows 7

**Comment by E1izabeth** [comment]
Thank you for bug report. It's a duplicate of #34197
Latest versions of DBeaver don't support Windows 7 and 8. Please use DBeaver 24.0.3
