### ISSUE TITLE
Add support for "geometry" column type

### ISSUE THREAD

**Issue by zeleznypa** [dbeaver/dbeaver#34297]
**Is your feature request related to a problem? Please describe.**
The MariaDb database supports column type ["Geometry"](https://mariadb.com/kb/en/geometry-types/), which is not available in the "Data Type" selectbox.

![Snímek obrazovky 2024-06-07 v 12 45 38](https://github.com/dbeaver/dbeaver/assets/1191472/5487827b-ffd8-46e7-82fa-d725e3cc50e5)

**Describe the solution you'd like**
It will be nice to have the value in the selectbox values to know, that it is the correct value :)

**Describe alternatives you've considered**
It is possible to just fill in the "geometry" string the field and hit enter.

**Comment by Destrolaric** [comment]
@zeleznypa Hi, are you sure that you MariaDB server supports geometry types? Most of the times DBeaver gets info about available types from the server.

**Comment by zeleznypa** [comment]
Yes, the link i have posted (https://mariadb.com/kb/en/geometry-types/) confirms the support.
And it also work on my machine :)
And when I wrote the "geometry" manually, it works also.
The "geometry" is just not in the list. Everything else works well :)

**Comment by E1izabeth** [comment]
OK, thank you for request.
