### ISSUE TITLE
Unable to connect to repository https://dbeaver.io/update/debug/latest/content.xml

### ISSUE THREAD

**Issue by zdposter** [dbeaver/dbeaver#34301]
### Description

I update dbeaver  to the latest version (Version 24.1.0.202406021658) and I got error:
`Unable to connect to repository https://dbeaver.io/update/debug/latest/content.xml`
when I try to 'Help->Install New Software... ' and e.g. Dakest Dark Theme.  

When I open  `https://dbeaver.io/update/debug/latest` there is no `content.xml` but `content.xml.xz`:
![image](https://github.com/dbeaver/dbeaver/assets/76629990/cd82aa60-8584-4330-8b24-3aa5193bf622)

### DBeaver Version

Community Edition 24.1.0.202406021658

### Operating System

Windows 10 64bit

### Steps to reproduce

1. Help->Install New Software...
2. 2 Select `Dakest Dark Theme`

**Comment by E1izabeth** [comment]
Could you clarify your step 2? What exactly do you put to the `Work with:` field?
Also why are you talking about `debug` plugin? I just tried and I successfully installed `debug` plugin. So, is this issue about `Darkest Dark` or `debug` plugin?

**Comment by E1izabeth** [comment]
Also I was able to successfully install Darkest Dark theme on DBeaver Community Edition 24.1.0

**Comment by zdposter** [comment]
Step 2.:
![image](https://github.com/dbeaver/dbeaver/assets/76629990/f22386af-710f-4a6f-9c8f-792fb4e4dea6)

Result:

![image](https://github.com/dbeaver/dbeaver/assets/76629990/594edae8-3f66-4215-95f8-c5f12c6ed3fa)

**Comment by zdposter** [comment]
When I select `...Office integrations...`


![image](https://github.com/dbeaver/dbeaver/assets/76629990/7a1ec300-24a3-4cb1-9760-2c6e99cf375b)

**Comment by E1izabeth** [comment]
Do you have internet connection on that PC?
Is it under the firewall?

**Comment by zdposter** [comment]
Yes I have internet connection on that PC.
E.g Checking for version updates has no problem:

![image](https://github.com/dbeaver/dbeaver/assets/76629990/0c58ab27-7cc4-4c9b-b6c8-33a6c79ddbbf)

**Comment by zdposter** [comment]
Problem was with firewall - after I manually set it up it works:

![image](https://github.com/dbeaver/dbeaver/assets/76629990/5aa9986c-a92e-43b0-8ae4-4da0c7fe5490)
