### ISSUE TITLE
"Format SQL" incorrectly separates PostgreSQL "@>"  array operator

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#3431]
Hi,

I noticed a minor issue with the "Format SQL" right click command of the SQL Editor window: it incorrectly separates PostgreSQL "@>"  array operator by inserting a space, resulting in subsequent syntax error when you try to execute the query.

E.g. 
**ARRAY[1,4,3] @> ARRAY[3,1]**
becomes:
**ARRAY[1,4,3] @ > ARRAY[3,1]**
after choosing Format SQL

https://www.postgresql.org/docs/9.6/static/functions-array.html

**Comment by serge-rider** [comment]
Thanks for report
