### ISSUE TITLE
Please add at least one readable theme

### ISSUE THREAD

**Issue by alfonz19** [dbeaver/dbeaver#34328]
Please, add at least one readable scheme. I'm still looking for one, I restarted 10 times already trying some combination which works,
 but it's all black-on-black, white-on-white, white-on-white with stylish gray shading. NOTHING is readable. I really don't care if it's yellow-on-blue or old-school black on white, but please, at least one easy to find, ideally default, readable color scheme.

**Comment by E1izabeth** [comment]
Please provide screenshots of how does it look like and specify your OS and version.

**Comment by alfonz19** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/9654980/6c4c6ea3-77a3-4887-9a54-f8ac8cb91abd)

![image](https://github.com/dbeaver/dbeaver/assets/9654980/8242aebe-2f82-432d-96d4-c7a52fada2bb)

I almost test all combinations really only the high-contrast is actually readable (still not ideal, but at least somehow readable). I'm not without and issue, but with color sensitivity 10/10.

taken on ubuntu 22.04, dbeaver 24.1

**Comment by alfonz19** [comment]
update: not even high-resolution:

![image](https://github.com/dbeaver/dbeaver/assets/9654980/8a633324-99ce-490e-9625-3b2b2ed62443)

**Comment by E1izabeth** [comment]
If I correctly understood, provided screenshots are for High-contrast theme. Could you show how does just Dark or Light theme are look like for you?

**Comment by alfonz19** [comment]
no, first two are default, as shown as first screen shot.
second is hi-res.

turning off theming also does not work.
while mode also unreadable.
You can just change what will be unreadable, and what color the unreadable stuff will have.

are there donwloadable some custom skins or ability to somehow tweak it?

**Comment by alfonz19** [comment]
light theme:

![image](https://github.com/dbeaver/dbeaver/assets/9654980/d99ca822-5a79-4dbb-b2e5-5167ecfe2904)

**Comment by E1izabeth** [comment]
I see. It's the same issue as here #34311
I'll close this issue as a duplicate to keep it in one place. You can left a comment or subscribe to the mentioned issue to get updates.
It's a bug and we will investigate it.

**Comment by E1izabeth** [comment]
Could you provide log files?
Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by alfonz19** [comment]
I'd like to do so, but I'd have to clean them up as I see there some potentially sensitive data. I don't see any errors in them. If you want me to grep you smth from then, I can do that.

**Comment by E1izabeth** [comment]
I would be looking for errors, yes.
OK, thank you.

**Comment by alfonz19** [comment]
I undersand, but I would like to avoid company security complaints, so I cannot share them all. Grep result:

~/.local/share/DBeaverData/workspace6/.metadata$ ls *log | xargs grep -i exception
dbeaver-debug.log:org.jkiss.dbeaver.DBException: Can't read tablespace statistics
dbeaver-debug.log:Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

ls *log | xargs grep ERROR
<nothing>

so only 2 exceptions, which are related to wrong statement/connection?

**Comment by E1izabeth** [comment]
It seems there is no exceptions in the logs, which might help investigating. I see. Thank you.

**Comment by E1izabeth** [comment]
Could you try installing Early Access version from here https://dbeaver.io/files/ea/?

**Comment by alfonz19** [comment]
that was quick! 
I checked, it looks very nice. 

I used dark+classic theme, it looks like this now:
![image](https://github.com/dbeaver/dbeaver/assets/9654980/1b393fe1-68bc-48a0-b8ed-17bf65a42c59)


Thank you!
