### ISSUE TITLE
Navigation keys are not working in confirmation modals

### ISSUE THREAD

**Issue by crojasaragonez** [dbeaver/dbeaver#34334]
### Description

When you try to delete something (table, schema, database, connection) you are not able to confirm the operation with the keyboard. For some reason right and left keys are not working and you are forced to use the mouse.

![image](https://github.com/dbeaver/dbeaver/assets/4663192/6ae9379f-4683-4fe9-ac6b-8e4fee112cdc)

### DBeaver Version

Community Edition 24.1.0

### Operating System

openSUSE Tumbleweed

### Database and driver

This issue is not related with the database or driver.

### Steps to reproduce

1. Create a new database
2. Right click and try to delete the database.
3. Press left and right keys in the keyboard to try to confirm the action.

**Comment by flambchap** [comment]
Thank you for the report. I experience the same issue on macOS, but have not found the time to file a ticket.

**Comment by Phillipus** [comment]
> I experience the same issue on macOS, but have not found the time to file a ticket.

On Mac you have to turn on the "Keyboard navigation” setting to use the tab key.

See https://support.apple.com/en-gb/guide/mac-help/mchlp1399/mac

**Comment by Matvey16** [comment]
I'm not sure if this is a bug. You can cycle through buttons with `tab` on keyboard, but can't use arrow keys like it's possible on windows. But that seems to work as expected for Linux

**Comment by arhayka** [comment]
Conclusion:
- On Linux, you can use the `tab` button as a navigation key in confirmation modals.
- On macOS, you can turn on "Keyboard navigation” and then the `tab` button will also work.
It seems that everything works as expected, so I closed this ticket.

**Comment by flambchap** [comment]
Navigation is possible on macOS. However, hitting enter on the 'Yes' button doesn't produce the desired effect.


https://github.com/dbeaver/dbeaver/assets/26031301/33bcccfe-83e0-4a92-92f5-aab85990bba0

**Comment by Phillipus** [comment]
> Navigation is possible on macOS. However, hitting enter on the 'Yes' button doesn't produce the desired effect.

That's because the Cancel button is set as the default button. To select "Yes" use the space bar when it has the focus.

**Comment by flambchap** [comment]
Thanks a lot, @Phillipus
