### ISSUE TITLE
[CUBRID] Improve Keyword in SQL Editor

### ISSUE THREAD

**Issue by rathana-pvs** [dbeaver/dbeaver#34331]
**Description**
Currently, some of the reserved keywords in SQL editor are missing and doesn't support for Cubrid.

**Solution**
- Remove keywords that Cubrid doesn't support.
- Add keywords that SQL Editor missed.

_Reference link:_  [https://www.cubrid.org/manual/en/11.3/sql/keyword.html](https://www.cubrid.org/manual/en/11.3/sql/keyword.html)

**Comment by LonwoLonwo** [comment]
Hello @rathana-pvs 

Thanks for the report.
