### ISSUE TITLE
SQL editing page

### ISSUE THREAD

**Issue by Zhengk1998** [dbeaver/dbeaver#34333]
After selecting all SQL on the SQL editing page, entering other keys will not replace all selected ones?

**Comment by E1izabeth** [comment]
Please describe the clear steps to reproduce the issue or provide a video showing it.
For now, it's not quite clear, what is this issue about.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
