### ISSUE TITLE
Redshift - external table cannot be queried

### ISSUE THREAD

**Issue by Auric-Manteo** [dbeaver/dbeaver#34343]
### Description

Hi,

Here is an example of a very simple select statement on an external table that does not complete.
Works fine on the command line.

`select id from "oneflow"."staging_external"."core_api_account_billing" limit 1;`    

![image](https://github.com/dbeaver/dbeaver/assets/112462529/b018bfb1-afc8-4f5e-bfca-c621b8e6c503)

### DBeaver Version

Version 24.0.5.202405191503 Community version

### Operating System

macOS 14.2 (23C64)

### Database and driver

Redshift
Not sure how to look up the driver.

### Steps to reproduce

Create an external table, for instance via a parquet file and do a simple select query on the table.

**Comment by serjiokov** [comment]
Hello @Auric-Manteo, please provide the error and log details. 
https://dbeaver.com/docs/dbeaver/Log-files/#log-files

**Comment by Auric-Manteo** [comment]
Hi serjiokov,
I truncated the logs and only executed the relevant statement which I cancelled manually after it ran for 40 min.
[dbeaver-diagnostic-info-1718779279414.zip](https://github.com/user-attachments/files/15896465/dbeaver-diagnostic-info-1718779279414.zip)

**Comment by Auric-Manteo** [comment]
Just to clarify, this query returns in seconds if I run it via psql on the command line.

**Comment by Auric-Manteo** [comment]
@serjiokov I can't remove the wait for response label myself I think.
Is this enough information or do you need anything else?

**Comment by Auric-Manteo** [comment]
I have a possibly related issue where the query takes forever and the status says "Discover owner entity...".
I followed the setting recommended here and now the query returns in less than a second:
https://github.com/dbeaver/dbeaver/issues/4193

**Comment by Auric-Manteo** [comment]
It seems like that is also a workaround for the original issue described in this ticket.

**Comment by uslss** [comment]
Sorry for the late response.
unfortunately, I cannot reproduce it against 24.2.5. Is the issue still actual for you?

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. If the issue is still present, please let me know.
