### ISSUE TITLE
When using Chinese input method, pressing Enter after typing often causes the program to crash

### ISSUE THREAD

**Issue by jackChen1212** [dbeaver/dbeaver#34357]
### Description

When using Chinese input method, pressing Enter after typing often causes the program to crash

### DBeaver Version

24.1.0.202406091028

### Operating System

win10

**Comment by E1izabeth** [comment]
Please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

If there are some java fatal logs [dbeaver.com/docs/dbeaver/Log-files/#java-fatal-log](https://dbeaver.com/docs/dbeaver/Log-files/#java-fatal-logs), please provide them too.

**Comment by jackChen1212** [comment]
> Please send us the DBeaver log files. The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)
> 
> If there are some java fatal logs [dbeaver.com/docs/dbeaver/Log-files/#java-fatal-log](https://dbeaver.com/docs/dbeaver/Log-files/#java-fatal-logs), please provide them too.

[hs_err_pid3012.log](https://github.com/user-attachments/files/15836372/hs_err_pid3012.log)
[hs_err_pid3056.log](https://github.com/user-attachments/files/15836373/hs_err_pid3056.log)
[.bak_0.log](https://github.com/user-attachments/files/15836402/default.bak_0.log)
[.log](https://github.com/user-attachments/files/15836429/default.log)

**Comment by serjiokov** [comment]
@jackChen1212 The log details contains pointer to native crash, could you provide execution enviriment for  DBeaver product?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
