### ISSUE TITLE
[Oracle] Broken schemas with no content

### ISSUE THREAD

**Issue by Reitertom** [dbeaver/dbeaver#34350]
### Description

![image](https://github.com/dbeaver/dbeaver/assets/172612200/71354ad6-017d-4dc2-84bc-36e327e5977c)

When I run these, I get back correct results

```
SELECT U.* FROM ALL_USERS U
WHERE (U.USERNAME IS NOT NULL)
```
![image](https://github.com/dbeaver/dbeaver/assets/172612200/329e3557-aed4-485d-8513-68554db27da8)

```
SELECT U.* FROM DBA_USERS U
WHERE (U.USERNAME IS NOT NULL)
```
![image](https://github.com/dbeaver/dbeaver/assets/172612200/4bd0818b-753e-403e-9986-13ea70c1a2cf)

I tried switching between these drivers, but with no success
ojdbc11-23.2.0.0
ojdbc8-23.2.0.0
ojdbc10-19.10.0.0

### DBeaver Version

Community edition 24.1.0

### Operating System

Win 10 Pro

### Database and driver

Database: Oracle Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.17.0.0.0
Driver: Oracle JDBC driver 19.17.0.0.0

### Steps to reproduce

Error log
![image](https://github.com/dbeaver/dbeaver/assets/172612200/b938c315-dca9-472e-a0e3-443625faae24)

Event details
Exception Stack Trace: **An exception stack trace is not available.**

**Session Data**

eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\reiter\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

[dbeaver_issue_log.log](https://github.com/user-attachments/files/15821752/dbeaver_issue_log.log)

**Comment by LonwoLonwo** [comment]
Hello @Reitertom 

It can be a driver issue.
Could you please try this solution https://github.com/dbeaver/dbeaver/issues/15144#issuecomment-1011636822 ?

**Comment by Reitertom** [comment]
@LonwoLonwo Hi, 

as far as I understand, the comment suggests using driver ojdbc11-21.3.0.0?
Tried that, but still the same

![image](https://github.com/dbeaver/dbeaver/assets/172612200/e7657b24-35ee-4509-a8fe-062ba957f355)

**Comment by LonwoLonwo** [comment]
Ok, could you please try to enable this setting?

![2024-06-13 22_37_52-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/fbcecd46-ea9e-4543-9751-2e807fd64db9)

**Comment by Reitertom** [comment]
@LonwoLonwo HI, I already did mess with the settings here a bit. Looks like this right now
![image](https://github.com/dbeaver/dbeaver/assets/172612200/12eae541-12c6-41d5-b680-b3ee3b23f9ff)

**Comment by Destrolaric** [comment]
@Reitertom Hi, are you sitting behind the firewall? I can see multiple network errors in the log.

**Comment by Reitertom** [comment]
@Destrolaric Hi, yes Im behind company firewall. The connection to Maven repo is blocked, so I had to download the driver files manually. But since I connected to the DB, I forgot to mention that

**Comment by Destrolaric** [comment]
@Reitertom It might be an issue with missing dependencies
Can you also download this libs:
![image](https://github.com/dbeaver/dbeaver/assets/20579256/833e0d8d-7e1c-4dcf-ac6b-667439014b07)

**Comment by Reitertom** [comment]
@Destrolaric Hi,
I downloaded and added those libs as .pom and also as .jar, but nothing changed as you can see on the screenshots
![image](https://github.com/dbeaver/dbeaver/assets/172612200/2f54cb91-6e2e-4ec4-b4b4-10dbdac36142)
![image](https://github.com/dbeaver/dbeaver/assets/172612200/b56e1c7b-1750-43ff-bc8e-3848836f85be)

Regards
T.

**Comment by Reitertom** [comment]
After 2 restarts it started working, so solved!
Thanks
T.
