### ISSUE TITLE
Reserved Words as Table Names Colored Red When Escaped with the backtick along with every column name from that table

### ISSUE THREAD

**Issue by gwolbrecht** [dbeaver/dbeaver#34353]
### Description

I have a table named, Cycle.  When escaped with the backtick, everything connected with that table turn red

`select a.ColumnOne from mySchema.Cycle where ...`

a.ColumnOne, mySchema.Cycle are all colored red.  NOTE: Cycle is enclosed in backtick.  Omitted here as it is a MD character

### DBeaver Version

Community Edition Version 24.0.5.202405191503

### Operating System

Windows 10 

### Database and driver

MySQL 

### Steps to reproduce

Escape a table with the name Cycle or other reserved word.  Anything associated with that table will turn red (e.g. schema, column names).

**Comment by E1izabeth** [comment]
Bright red color means that the table doesn't exist in the database. Also it may happen if you just create this table and haven't refreshed the DBeaver metadata. You can do it by selecting the parent node in navigator and pressing `Refresh` in the context menu or F5
![image](https://github.com/dbeaver/dbeaver/assets/28875055/b4633dce-c288-4ba4-afe4-1b708c7e0445)

**Comment by E1izabeth** [comment]
For now, I can't reproduce the issue
![image](https://github.com/dbeaver/dbeaver/assets/28875055/8a23f2a0-efe0-4b74-a454-47db1935caa2)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
