### ISSUE TITLE
DBeaver Configuration for project 'General' is encrypted Please open it in DBeaver PRO

### ISSUE THREAD

**Issue by 501956430** [dbeaver/dbeaver#34359]
### Description

DBeaver Configuration for project 'General' is encrypted Please open it in DBeaver PRO
<img width="1308" alt="截屏2024-06-14 13 59 24" src="https://github.com/dbeaver/dbeaver/assets/20204491/c35b12e4-4888-41fe-87c0-fea683c13583">

### DBeaver Version

DBeaver Community 24.1.0

**Comment by E1izabeth** [comment]
The behavior shown on the picture is expected: this project was protected with password in PRO version, you can't open it again in Community Edition.

**Comment by 501956430** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by arhayka** [comment]
We should make the error message more clear:

The ‘Name’ project was protected with a password in another edition of DBeaver. In this edition the password does not work, so this project cannot be opened. You can try to open it in [another DBeaver edition](https://dbeaver.com/download/).
