### ISSUE TITLE
Add feature to expand list of columns of a query from symbol * after pressing Tab

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34365]
Add feature to expand list of columns of a query from symbol * after pressing Tab when cursor is set after the symbol *.
See this gif-file for an example:

![0000002581](https://github.com/dbeaver/dbeaver/assets/33929221/f121015a-e44b-4627-b482-e2c82928d5c9)

**Comment by E1izabeth** [comment]
You can do the same in DBeaver with `Ctrl+Space`

https://github.com/dbeaver/dbeaver/assets/28875055/f7a49378-ba0e-49f0-95c9-e7d571349918
