### ISSUE TITLE
[SQL Server] Not reading the "on delete" and "on update" rules for foreign keys properly

### ISSUE THREAD

**Issue by aibars** [dbeaver/dbeaver#3436]
Hi,

I think that for all elements listed in the Foreign Keys section while inspecting the Properties tab of a table, the value is always `Restrict` both for the update and the delete rule. The following images depict the difference:

![image](https://user-images.githubusercontent.com/14154859/39677046-37214efa-514b-11e8-8ca8-0004742bbddf.png)

but when I inspect the same table using SSMS I see

![image](https://user-images.githubusercontent.com/14154859/39677057-514bdc3c-514b-11e8-81b6-db96df892de3.png)

This means that for the same table, the values are different. I think the right one should be `SET NULL`.

I'm using Dbeaver 5.0.4 on Windows x64
Thank you.

**Comment by uslss** [comment]
issue isn't reproduced on 6.0.3
