### ISSUE TITLE
Color "SQL datatype color" is applied for some sql keywords other than datatypes

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34371]
### Description

![0000002617](https://github.com/dbeaver/dbeaver/assets/33929221/94ef0f06-c8c5-4456-abc6-41d56bf296ac)

### DBeaver Version

Community Edition 24.1.0

### Operating System

Windows 10

### Database and driver
PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

1. copy-paste this code to a new script:
select 1::int;
select min(oid) from pg_class;

2. change color of datatype as shown in gif

Expected: word "int" has changed the color, word "min" has not changed the color (because it is not a datatype, it is an sql keyword).
Actual: both words changed the color

### Additional context
Another case:
```
    select 
        row_number() over(order by p."Id") as "Id",
        p."MyColumn"::int::bool as "SomeColumnName123",
        upper(p."Code"),
    from  public."Product" as p;
```

![изображение](https://github.com/dbeaver/dbeaver/assets/33929221/847b90c1-c5f9-4933-a2ab-945a8f43b1b8)

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
We added the separate color setting for functions. It will be available in DBeaver 24.1.2
The color is the same as for data types by default. However, you can change it.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/dd9313a9-57fd-4c49-b75e-5869d1311f07)

**Comment by ask9** [comment]
Thank you for fixing it. It is much better now!
I've checked the result but there still exists an issue with wrong color of a column alias "SomeColumnName123":

![изображение](https://github.com/dbeaver/dbeaver/assets/33929221/0ae4ff70-e399-45f4-ae54-7bf0c8f56b9f)

Should I create a standalone bug report and add a link to this thread?

**Comment by E1izabeth** [comment]
Yes, please create a separate issue for that.
