### ISSUE TITLE
Autocomplete appears and suggests object names inside single quoted values

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#34378]
### Description

It may appear somwhere else too, but the most obvious example of this bug can be found when the user generates sql for insert and then tries to enter values in SQL Editor. Autocomplete starts suggesting table or container names after any symbol is typed

### DBeaver Version

24.1.1

### Operating System

Any

### Database and driver

Any

### Steps to reproduce

1. Generated insert SQL for any table with varchar column
2. Copy it to SQL editor
3. Start typing values inside single-quoutes

**Expected:** Nothing is suggested
**Actual:** Object names appear in autocomplete

### Additional context

https://github.com/dbeaver/dbeaver/assets/82543000/12532e2c-3e7a-49e3-b94f-28941094a786

**Comment by E1izabeth** [comment]
There is no proposals with New autocompletion engine
![image](https://github.com/dbeaver/dbeaver/assets/28875055/fd0440ee-67ea-474f-905c-d4d72f53ec67)
