### ISSUE TITLE
Find + Replace In Cell Greys Out Save Button

### ISSUE THREAD

**Issue by danhennion** [dbeaver/dbeaver#34374]
### Description

When I perform a find + replace action on a cell's value field (this happens to be psql db, not sure if it matters) and there are matches found + replaces I see "x matches replaced" as expected.

But then the value field should be aware that the contents has just changed, and allow me to hit the 'save' button to persist the changes to the DB, as if I edited the contents by hand.

Instead, after a successful find + replace in the value field, it seems unaware that there are changes which can be persisted.

### DBeaver Version

24.1.0

### Operating System

max OS Ventura 13.3.1 (a)

### Database and driver

Postgres JDBC driver

### Steps to reproduce

Perform a successful find + replace on the value of any field, any row, in psql jdbc (or possibly any db / driver) and the 'save' button at the bottom you would expect to be green and clickable after contents update remains grey.

**Comment by E1izabeth** [comment]
Unfortunately, I'm unable to reproduce your issue. Please provide clear steps to reproduce or video showing the issue.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
