### ISSUE TITLE
Error using variable in subqueries

### ISSUE THREAD

**Issue by guilhermefacanha** [dbeaver/dbeaver#34387]
### Description

When using variables in subquery the replace is missplaced.

Query:
```sql
@set myvar = '123456';
delete from mytable where fk = (select id from othertable where var = :myvar );
```

Throws error:
```
SQL Error [42601]: ERROR: syntax error at or near ";"
  Position: 137

Error position: line: 6 pos: 136
```

With final/replaced query:
```
delete from mytable where fk = (select id from othertable where var = '123456'; )
```

### DBeaver Version

Community Version 24.1.0.202406091028

### Operating System

macOS Sonoma 14.5

### Database and driver

1. Database PostgreSQL

### Steps to reproduce

See description

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
Actually, it's not a bug. The value for variable is everything between `=` and the new line. So, you just don't need a `;` here.
