### ISSUE TITLE
Scripts with UPDATE / CASE not executing properly

### ISSUE THREAD

**Issue by diegosiao** [dbeaver/dbeaver#3439]
The script below works fine on SQL Developer but finds a parse error on DBeaver.

DECLARE
	vError VARCHAR2(4000);
BEGIN
	  UPDATE MY_TABLE
	  SET NU_PUSH = (NU_PUSH + 1),
	  	  ST_PUSH = (
  	  					CASE
		  	  				WHEN ((NU_PUSH + 1) >= 3) AND vError IS NOT NULL THEN 'FL'
		  	  				WHEN ((NU_PUSH + 1) < 3) AND vError IS NOT NULL THEN 'PD'
		  	  				ELSE 'EN'
	  	  				END
	  	  			),
	  	  TX_ERROR_PUSH = vError,
	  	  TM_PUSH = SYSDATE
	  WHERE ID_NOTIFICATION = -1;
END;

**Comment by serge-rider** [comment]
Yes, the bug was in incorrect CASE statement parsing.
Thanks for report.

Workaround (as for all other similar problems) is to select query and execute it with <kbd>CTRL+Enter</kbd>
