### ISSUE TITLE
ORDER BY fails on "interval" PG datatype

### ISSUE THREAD

**Issue by GTonehour** [dbeaver/dbeaver#34398]
### Description

When right-clicking a column of PG "interval" datatype and using GUI's ORDER BY, DBeaver orders alphabetically. It results in a different order than PG's native ORDER BY.
![image](https://github.com/dbeaver/dbeaver/assets/86954612/4bdad4dd-2020-460b-b79a-6b1519687d46)

### DBeaver Version

Community Edition 23.3.2

### Operating System

Windows 11

### Database and driver

PostgreSQL 15.3.0

### Steps to reproduce

1. 
  ~~~sql
CREATE TABLE test (c1 INTERVAL)

INSERT INTO test (c1)
VALUES (INTERVAL '9 days') ,(INTERVAL '1 year')

SELECT *
FROM test
ORDER BY c1
  ~~~
2. Right-click on the c1 column
3. Order / ORDER BY c1 ASC
4. Witness that DBeaver considers that "1 year" is less than "9 days"

**Comment by E1izabeth** [comment]
DBeaver sends the following query to the database and return the results for you
```
SELECT *
FROM test
ORDER BY c1
```
![image](https://github.com/dbeaver/dbeaver/assets/28875055/081f6b2e-b076-44d2-8443-f3dd63eec972)

You can check it in [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager)

So, this is what the driver returns.

**Comment by E1izabeth** [comment]
I managed to reproduce the issue. Thank you for bug report.
