### ISSUE TITLE
Result Set Order/Filter Settings window is too small

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#34419]
### Description

Window size is too small - columns headers are not visible. 

![image](https://github.com/dbeaver/dbeaver/assets/28875055/5066dc9c-9796-4df2-bb35-96320c8a5fc5)

Video:
https://github.com/dbeaver/dbeaver/assets/28875055/cbb3a5a6-8d60-4807-a188-2f9842f1ee73

### DBeaver Version

DBeaver 24.1.0

**Comment by serge-rider** [comment]
Fixed.
Also "Save filter" button moved to drop-down.
![image](https://github.com/dbeaver/dbeaver/assets/6398845/8bae03ce-3435-4c49-9d79-1ae4a4007bf8)

**Comment by E1izabeth** [comment]
I'm afraid moving this button to drop-down make it more unobvious. No one find it.

**Comment by E1izabeth** [comment]
Also we have a separate ticket to change the icon https://github.com/dbeaver/dbeaver/issues/34421

**Comment by serge-rider** [comment]
Also fixes https://github.com/dbeaver/dbeaver/issues/34421
