### ISSUE TITLE
known_hosts file being asked to change every time

### ISSUE THREAD

**Issue by piradata** [dbeaver/dbeaver#34413]
### Description

every time I open any connection, dbeaver asks me to add the host to the known_host file, but it should only ask one time for each server, not every time I open any connection on already knows servers

### DBeaver Version

Community 24.1.0.202406091028

### Operating System

Windows 11 Pro 22631.3737

### Database and driver

Postgresql 14 (error happens in any of them tho)

### Steps to reproduce

just open any connection

**Comment by piradata** [comment]
It may be because it tries to add this on known_hosts? i use a jump connection so everytime it add a localhost entry with different ports...

![image](https://github.com/dbeaver/dbeaver/assets/16529503/6a48aaef-62f9-4382-a361-39f3e187eed6)

![image](https://github.com/dbeaver/dbeaver/assets/16529503/03edf200-651c-4110-a516-62425437e689)

![image](https://github.com/dbeaver/dbeaver/assets/16529503/324e8c74-2be9-41c4-baf9-868ab7f47c90)

**Comment by piradata** [comment]
And this is how the known_hosts file is becoming 😅

![image](https://github.com/dbeaver/dbeaver/assets/16529503/84c45e88-ba11-47c8-aff6-0ff78c6d8580)

**Comment by piradata** [comment]
Sorry if its a duplicate or someone already opened this, but just could not find any open issue about this, and is happening with all my coworkers starting the last dbeaver version before the current one. might have been a regression on the second to last version then. before that, everything worked normally and was one entry for host normally.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by humilimo** [comment]
same happening with me!

**Comment by piradata** [comment]
this commit `940f5c0d351c2a77d740de7380cc4ed36db4e0e2` from [HocKu7](https://github.com/HocKu7) is already on main? any way i can test if it fixed the problem?

**Comment by E1izabeth** [comment]
no, it's not
we haven't fixed it yet

**Comment by piradata** [comment]
its working now as intended just like before, just downloaded and tested the version `24.2.0` :)
