### ISSUE TITLE
SSH user name and auth method fields are incorrect, when using profiles

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#34425]
### Description

I have a profile with Public Key auth method, however disabled area shows it as an Agent, until you reselect the profile to force those fields to be filled with correct information. It usually happens with all connections after DBeaver restart.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/722c4828-838c-48e3-ae32-1aae44841fa9)

Video showing the issue:
https://github.com/dbeaver/dbeaver/assets/28875055/8c6ff499-29e6-4268-8ec7-27f324080ed8

### DBeaver Version

DBeaver 24.1.0

**Comment by E1izabeth** [comment]
Seems it's a bug in my configuration - not an issue.

**Comment by HocKu7** [comment]
Need to reproduce and provide STR

**Comment by E1izabeth** [comment]
It's reproducible right after launch. As soon as you opened it once, it's not reproducible anymore.

**Comment by E1izabeth** [comment]
https://github.com/user-attachments/assets/85faa9eb-e6e6-43ed-adda-1f3da1a1180d

**Comment by Gfrni** [comment]
I think this method of ssh configuration can be avoided by [supporting system OpenSSH configurations](https://github.com/dbeaver/dbeaver/issues/21394), so user can skip these redundant settings.

**Comment by E1izabeth** [comment]
Steps to reproduce:
1. Create two ssh profiles.
![image](https://github.com/user-attachments/assets/e13c02cd-b5e5-48bd-9702-2d770f2ec2ca)
![image](https://github.com/user-attachments/assets/a3805f05-35ea-43e9-b31c-270ad82ff9bb)

2. Choose profile test with Agen auth for connection
![image](https://github.com/user-attachments/assets/0cd0e5cf-6de6-4fa7-b1e7-0b6446180267)

3. Restart DBeaver
4. Change in test profile Agent to Public key
5. Restart DBeaver
6. Issue reproduced

**Comment by HocKu7** [comment]
Closed by [this](https://github.com/dbeaver/dbeaver/issues/35916)
