### ISSUE TITLE
Save filter settings button icon

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#34421]
### Description

These two icons actually look the same. It's too hard to see that this green dot is an abstraction of diskette.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/0ca2bfb0-be30-4611-acc0-14e2414139f7)

In real size:
![image](https://github.com/dbeaver/dbeaver/assets/28875055/1366aa6a-8699-454b-9a61-03e1875515fc)

Let's think of the replacement.

For example, I could suggest using the approach we use with value panel for saving by timeout:
![image](https://github.com/dbeaver/dbeaver/assets/28875055/ee7db8b5-b566-4915-9eb4-476da72080dd)

Draft approach for filters:
![image](https://github.com/dbeaver/dbeaver/assets/28875055/870507d3-8c92-49fa-9cbd-7040cf78c622)
Real size:
![image](https://github.com/dbeaver/dbeaver/assets/28875055/89c35103-3cb8-4d82-91c1-1cc1896dfcbd)

### DBeaver Version

DBeaver 24.1.0

**Comment by arhayka** [comment]
This seems to be fixed with https://github.com/dbeaver/dbeaver/issues/34419

**Comment by E1izabeth** [comment]
We moved this to drop-down menu of a button with filter icon and wrote a name for the action there
![image](https://github.com/dbeaver/dbeaver/assets/28875055/ee06cffc-dfae-4089-b3c7-497b18b04707)
