### ISSUE TITLE
`Booleans` settings UX is too complex

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#34420]
### Description

1. We want to move this settings to some other page about UI (it's hard to find them now)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/81ffaac4-87d8-4535-8ea1-1695b56df232)
2. It's not clear how to use all these switches. State column confuses. Label contents in text representation should
3. Label contents disappear if you switch to Icons and then back. Page becomes invalid - see error in the top, Apply button disabled.

https://github.com/dbeaver/dbeaver/assets/28875055/26ecb8f4-e78f-4df6-8320-24d7e08169ae

### DBeaver Version

DBeaver 24.1.0

**Comment by E1izabeth** [comment]
We want to
- [x] move this settings group to other page
- [ ] fix mentioned bug
- [ ] maybe relayout / hide unrelated settings like label for icons?

**Comment by arhayka** [comment]
We decided to not change this UX right now.
Only fix this bug: Label contents disappear if you switch to Icons and then back. Page becomes invalid - see error in the top, Apply button disabled (see detail on the video)
