### ISSUE TITLE
A minor Turkish Translation error

### ISSUE THREAD

**Issue by Yigitttttttt** [dbeaver/dbeaver#34432]
Hi, 
I use Dbeaver in Turkish. 
The program works with a flawless Turkish translation, 
but at one point there is a minor word redundancy, I wanted to share it.
![Adsız](https://github.com/dbeaver/dbeaver/assets/168306503/8cdcc7c5-f714-4ae4-9e35-87fde3acedd0)

**Comment by E1izabeth** [comment]
Thank you for bug report.
This message comes from the Oracle driver, unfortunately, we can't fix it.
