### ISSUE TITLE
Could You add 'tr' to Data Formats

### ISSUE THREAD

**Issue by Yigitttttttt** [dbeaver/dbeaver#34433]
Hi,

Could You add 'tr' to Data Formats. It's same like 'de'

![Adsız2](https://github.com/dbeaver/dbeaver/assets/168306503/eda7882c-8ad3-4e86-9d12-fa00da59eacd)

**Comment by Yigitttttttt** [comment]
tr - Turkey (or if is possible tr - Türkiye)

**Comment by E1izabeth** [comment]
It's already there. How did you install DBeaver?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/035e26d0-22cd-4ca5-967b-d65843b3fa27)

**Comment by E1izabeth** [comment]
These locales comes from Java. Have you unchecked Include Java in the installer and use your own Java?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/5f26dda1-803d-4712-9b50-8a5f6fd3cda0)

**Comment by Yigitttttttt** [comment]
Hi, I use portable (zip) version.

**Comment by E1izabeth** [comment]
I see. Thank you for quick reply.
I have a limited amount of locales in portable version too.

**Comment by Yigitttttttt** [comment]
should I close this? :)
