### ISSUE TITLE
Some questions about Dameng

### ISSUE THREAD

**Issue by NewBody-LC** [dbeaver/dbeaver#34438]
### Description

1. The visual interface cannot see the constraints in the table (including in DDL statements).
2. After editing the field description in the interface, there is no DDL statement when saving.
3. DDL statements about tables, only fields and indexes, field descriptions and constraints

### DBeaver Version

 Community 24.1.1

### Operating System

Windows10 Professional Edition 10.0.19044

### Database and driver

Dameng8
Dameng JDBC driver
com.dameng:DmJdbcDriver18:RELEASE

**Comment by MashaKorax** [comment]
Hello @NewBody-LC 
I can not reproduce your issue on Dameng 7; I should probably 
![iScreen Shoter - DBeaver Community - 240717125021](https://github.com/user-attachments/assets/3b69784a-b4b3-4468-a18c-85efca42fd55)
try it on the newest version.

I didn’t understand the third question, please provide more details

**Comment by NewBody-LC** [comment]
The third question is as follows
![Uploading 20240722171423.png…]()

**Comment by NewBody-LC** [comment]
The third question is as follows
![20240722171423](https://github.com/user-attachments/assets/fe371227-36e2-4601-ba73-fd16f080b05d)

**Comment by NewBody-LC** [comment]
Regarding your picture, you can try to edit the field description of this table to see if the saving is successful.（I am in Dameng 8.）

**Comment by jeffxjh** [comment]
> Regarding your picture, you can try to edit the field description of this table to see if the saving is successful.（I am in Dameng 8.）
Dameng 8 can not modify the comment,and generate DDL without comments
