### ISSUE TITLE
Kaspersky Endpoint Security for Windows 12.1.0.506 thinks dbeaver-cli.exe is malware

### ISSUE THREAD

**Issue by Yigitttttttt** [dbeaver/dbeaver#34445]
### Description

Hi, I open this issue bcoz in milestone 24.0.5 the problem not solved.
Kaspersky Endpoint Security for Windows 12.1.0.506 still thinks dbeaver-cli.exe is malware. Could you find a solution for this? (I use portable version)
![image001](https://github.com/dbeaver/dbeaver/assets/168306503/19ced0f5-4de4-4d57-959f-102322204ebd)

### DBeaver Version

24.1.1

### Operating System

windows 10

**Comment by E1izabeth** [comment]
Thank you for report. We will try fixing it.

**Comment by Yigitttttttt** [comment]
Hi, I started using 24.1.2 this morning. Interestingly, I didn't have any problems. For your information, the antivirus program didn't cause any problems

**Comment by Yigitttttttt** [comment]
Today, Kaspersky deleted dbeaver-cli.exe on 24 1.2
