### ISSUE TITLE
Unable to see Trigger Body for Oracle Database.

### ISSUE THREAD

**Issue by megalomaniac107** [dbeaver/dbeaver#3444]
I am unable to see trigger body using the navigator in DBEAVER but I am able to see it when i use the below. Any pointers would be helpful.

SELECT trigger_body
FROM SYS.ALL_TRIGGERS

**Comment by serge-rider** [comment]
Do you see any errors? Maybe there is something in Error Log view?

**Comment by megalomaniac107** [comment]
No. Nothing in the Error Log.

**Comment by serge-rider** [comment]
DBeaver reads trigger body from ALL_SOURCE.
```sql
SELECT TEXT FROM SYS.ALL_SOURCE 
WHERE TYPE='TRIGGER' AND OWNER='SCHEMA_NAME' AND NAME='TRIGGER_NAME' 
ORDER BY LINE
```
