### ISSUE TITLE
Error loading certificate file. Error 2147942405, access is denied.

### ISSUE THREAD

**Issue by i-radev** [dbeaver/dbeaver#34441]
### Description

I get the following error on Windows 11 when testing a Redshift connection using an SSL CA certificate file
![image](https://github.com/dbeaver/dbeaver/assets/95762236/3792c8bd-879e-4f64-9234-9136bdcc5f99)

### DBeaver Version

Community Version 24.1.1.202406231636

### Operating System

Windows 11

### Database and driver

Redshift, redshift jbdc 2.1.0.28

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
