### ISSUE TITLE
Jsonb - Visor takes too long to display the JSONB

### ISSUE THREAD

**Issue by jhoss64** [dbeaver/dbeaver#34450]
### Description

When select a column with jsonb type, is too long for to charge the data in the visor and the program does not respond. I'd had to install the old version 24.0.5.

### DBeaver Version

Community Edition 24.1.0 and 24.1.1

### Operating System

Windows 10 Pro 21H2

### Database and driver

Postgresql  with driver jdbc

**Comment by CComparon** [comment]
I don't know what Visor is, but FWIW, Dbeaver has always been excruciatingly slow to render large json payloads in the "Results cell value viewer". Plus it apparently hogs the UI thread, which locks the entire app, to the point that I sometimes have to kill DBeaver when clicking accidentally somewhere in a json column. Known issue?

**Comment by E1izabeth** [comment]
Thank you for report. We weren't aware of this issue.

**Comment by M111q** [comment]
I have the same problem. Earlier versions respond much faster, from 1-2 seconds (before update) to >20 seconds (after update)

Linux, Ubuntu 22.04, Dbeaver Version 24.1.1.202406231636 Postgresql with driver jdbc, JSON with ~2000 lines

**Comment by serge-rider** [comment]
Embedded text editors may freeze if you have long content AND word wrap is enabled.

Workaround: disable word wrap mode.

**Comment by CComparon** [comment]
Thanks @serge-rider for your quick reply. I does the trick!
It's not very practical though, and it's surprising that a monospace text area struggles so much calculating text layout with wordwrap enabled :/

**Comment by E1izabeth** [comment]
We use the "Word wrap" feature for styled text, which comes from the platform that Beaver is built on. There is a bug related to this feature at https://bugs.eclipse.org/bugs/show_bug.cgi?id=168557. Unfortunately, it doesn't appear that anyone from Eclipse will be fixing this issue. Perhaps WE should consider trying to fix it. Or create our own "Word wrap" solution.

**Comment by serge-rider** [comment]
We improved panel editor so word wrap won't freeze UI. However this fix is more like a workaround.

**Comment by CComparon** [comment]
Thanks a bunch @serge-rider for the improvement. 

As for longer-term priorization of this issue, I can only re-iterate how important it is to be able to visualize JSON data from within our SQL client, not having to copy cell data and paste it to another editor every time one need to simply look at the data or do basic text search in it.
