### ISSUE TITLE
Make it possible to disable / configure help features in a script editor

### ISSUE THREAD

**Issue by mlubimow** [dbeaver/dbeaver#3445]
I think it would be great to be able to disable auto-indent and auto-completion in a script editor.

I really like DBeaver but, for example:

After typing:
```
select
    *
```
and pressing return, the cursor gets indented. I think in this case it would be much better if the cursor could just go to the beginning of the new line. Having a tickbox to disable auto-indent in preferences would be great.

Regarding auto-completion, after typing `select` list of suggestions is coming up, this is useful but if I think that if suggestion matches the typed text, RETURN button should just go to the new line. At the moment, it just confirms select and another return press is needed to go to a new line.

Thanks, M

**Comment by uslss** [comment]
already implemented

**Comment by mlubimow** [comment]
@uslss uhmm, how can I do that? I've tried to find it now in 6.2.4 with no success
