### ISSUE TITLE
Connection Settings Changing Automatically

### ISSUE THREAD

**Issue by sjmoore00** [dbeaver/dbeaver#3446]
I am having an issue with using multiple DB2 databases.  I have access to a test and a production DB2 environment.  If I just set up one of the connections and edit the driver settings, it works fine.  The problem occurs when I try to set up a second DB2 connection to a different location like production, but using the same driver.  In this case db2jcc4.jar.  What happens is when I save the new driver settings for the new prod connection, then the previous test connection changes.  The URL Template changes in the Test connection to be the same path in the Prod connection and then the JDBC Url is changed on the connection settings page.
I have tried saving the Driver file with different names and then update the driver details and no change.

Is this a known issue?  If so, is there a workaround?

I am running on Windows 7, connecting to Mainframe and local DB2 instances.
Thanks for your assistance.

**Comment by serge-rider** [comment]
You are not supposed to change anything in driver settings to setup new connection. Driver settings are shared among all connections for that driver.

You can configure everything in connection settings dialog.
For example (DB2 LUW):
![image](https://user-images.githubusercontent.com/6398845/39971568-00cb315c-5706-11e8-9f55-c04e991ab9a6.png)

**Comment by sjmoore00** [comment]
Thanks for your reply, but it was not addressing my question at all.  I am trying to setup 2 connections to 2 different remote mainframe databases using the same db2 driver file.  They are the difference between Test and Prod.  They have different connection strings, but use the same drivers.  Have you actually accomplished this before?  If so, please show an example.

**Comment by sjmoore00** [comment]
The solution for this was quite simple.  The instructions I was given were hard coding the connection strings in the template.  The fix was to use the parms in the template.

jdbc:db2://{host}[:{port}]/{database}
