### ISSUE TITLE
Postgre DDL generation skips constraints

### ISSUE THREAD

**Issue by horv001** [dbeaver/dbeaver#34467]
### Description

In prior versions, it worked perfectly but I noticed that above version 24 the Postgre DDL generation skips the constraints. What else could be missing? It's a big problem for me because I used it for backing up the schema DDLs before a change.

### DBeaver Version

24.1.1.202406231636

### Operating System

Windows 11

### Database and driver

1. PostgreSQL 14.9
2. JDBC 42.7.2

### Steps to reproduce

1. Right-click on the schema name
2. Generate SQL and choose DDL
3. Check the "Show full DDL"
4. Click on Copy

**Comment by ask9** [comment]
What kind of constraint is missing?
I can't reproduce. Foreign keys, primary keys, check constraints are generated correctly.
The only one thing could be an issue if you created a constraint and did not refresh the list of objects in a tree of databases before generating DDL, which I would also treat as a bug.
Maybe it is your case?

**Comment by E1izabeth** [comment]
Please provide minimal example to reproduce the issue.

**Comment by horv001** [comment]
I'm always refreshing the tree before the DDL exports. Unfortunately, I know this "refreshing issue".

My steps were:

1. I created a DDL export from a schema to have a DDL before the changes that I would apply. 
2. I moved a very old table called table_A to table_A_bck
3. I created table_A with a new structure.
4. I checked all the referenced objects and they are pointed to table_A_bck as expected.
5. I refreshed the tree and generated the schema DDL export again.

After your comment, I checked my export again and I noticed the following.

- No foreign keys depending on table_A_bck can be visible in the export. I searched for their names but did not succeed. The table was there.
- I checked the DDL export generated in Step 1 and no foreign keys were pointing to the original table. 
- Finally, I exported only the table DDL, and the missing foreign keys were there.

**Comment by HocKu7** [comment]
@horv001 Hi. Could you provide a backbone for your tables, especially their relation? And what exactly did you mean under "_moved_ a table A to B"?

**Comment by horv001** [comment]
@HocKu7 Hi, Sorry, I meant I renamed the **table_A** to **table_A_bck**. This is the reason why all the dependent objects are pointing to the **table_A_bck** table. There is no relation between these tables. 

The **table_A_bck** is the original table (but renamed) and **table_A** (created in step 3) is the new table with the original name.

**Comment by HocKu7** [comment]
Hi, @horv001. Thank you for providing additional information, but unfortunately, I'm still not able to reproduce the issue. Can you please provide footage showing your issue with every STR? Thank you.

**Comment by E1izabeth** [comment]
We were unable to reproduce the issue. If it's still actual, please provide a video showing it.
