### ISSUE TITLE
Unable connect to mysql8.0

### ISSUE THREAD

**Issue by ygh1986** [dbeaver/dbeaver#3447]

**Comment by drduan** [comment]
Public Key Retrieval is not allowed Mysql8.0

**Comment by drduan** [comment]
@serge-rider

**Comment by luffyke** [comment]
@drduan You should set client option allowPublicKeyRetrieval=true on driver properties tab.

**Comment by Crazyokd** [comment]
> Public Key Retrieval is not allowed Mysql8.0

![image](https://user-images.githubusercontent.com/74645100/226531439-2486e057-f4f9-4947-8094-b6fc65a2cde1.png)
