### ISSUE TITLE
[Feature Request] Vim keybinds

### ISSUE THREAD

**Issue by dclong** [dbeaver/dbeaver#3448]
Is Vim keybindings supported in dbeaver? It's cool to have this feature if it does not already exist.

**Comment by pinzolo** [comment]
Standalone dbeaver can install some eclipse plugins.
So I'm using vrapper as vim keybindings on dbeaver.

1. Help -> Install Software
1. Add vrapper repository http://vrapper.sourceforge.net/update-site/stable
1. Install
1. Restart dbeaver

**Comment by dclong** [comment]
@pinzolo 

It works well. Thank you very much!

**Comment by dirkniblick** [comment]
FYI, I followed @pinzolo's steps above on my Windows 5.2.4 install and, after clicking the button to restart, DBeaver repeatedly restarted.  The splash screen kept popping up and disappearing over and over.  I had to reboot my PC to get control of it.  Anyhow, deleting the %HOMEPATH%\\.dbeaver4\\.metadata\\.plugins\org.eclipse.e4.workbench\workbench.xmi file and then starting DBeaver seemed to fix the restarting problem and I have my Vim bindings.

**Comment by dxdinh** [comment]
Many thanks for the tip. For Windows the workbench.xmi is under
%AppData%\DBeaverData\workspace6\.metadata\.plugins\org.eclipse.e4.workbench

**Comment by koen-dejonghe** [comment]
Following the vrapper installation instructions did not work for me, and I wasted more than an hour re-installing DBeaver from scratch.
OS: Windows 10
DBeaver Version 6.3.3.202001191557

**Comment by Anogoya-Dagaate** [comment]
@koen-dejonghe Not sure what issue you encountered but I successfully installed the plugin into the latest version of DBeaver
OS: Windows 10 Pro
DBeaver Version: 7.0.0

**Comment by verajosemanuel** [comment]
not working. After reboot, Dbeaver has no available vim keybinding.

**Comment by matthias-vigelius** [comment]
I encountered the same problem as @dirkniblick  .. unfortunatelty, deleting the workbench.xmi did not help and I had to reinstall dbeaver from scratch. 

I then followed the instructions in 

https://github.com/dbeaver/dbeaver/issues/8219

which works really well. In short, you'll have to install the eclipse marketplace first and get vrapper from there.

**Comment by jarvis8x7b** [comment]
valuable insight, thank you @pinzolo
