### ISSUE TITLE
[Oracle] Bug length in number columns 

### ISSUE THREAD

**Issue by vbelles87** [dbeaver/dbeaver#3449]
In Dbeaver community the properties of columns shows always numbers data with length=22.

I was using with ojdbc6.jar. I change to ojdbc7.jar with Implementation-Version: 12.1.0.2.0 and I have the same problem. The database is an oracle 12c.

Database: Oracle 12c
Client: DBeaver community 5.0.4 Win x64 + ojdbc7.jar 12.1.0.2.0

![image](https://user-images.githubusercontent.com/24482408/39808011-1dfa7548-537e-11e8-8334-0da706895bb2.png)
Left DBeaver - Right SQLDeveloper

**Comment by Sargul** [comment]
I think this is duplicate with #3208 

What does DBeaver show in the Precision Column?

**Comment by serge-rider** [comment]
Yep, looks like the same issue. However I can't reproduce this and see valid Scale/Precision values in numeric columns.

Generally I think that maybe we should change current type presentation (name + length + scale + precision) to SQL Developer style (we already do this for MySQL).

**Comment by serge-rider** [comment]
We'll show Oracle data types in FQ format:
![image](https://user-images.githubusercontent.com/6398845/69675256-46b7e700-10af-11ea-9b7c-2ae731bc3040.png)

However you still can view them as separate type + precision + scale columns.

**Comment by uslss** [comment]
verified
