### ISSUE TITLE
"Autosave editor on close" checkbox works correctly only for sql, but not for other extensions (for example, txt-files)

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34515]
### Description

"Autosave editor on close" checkbox works correctly only for sql, but not for other extensions (for example, txt-files)
Is it a feature or bug?
Why should it depend on extension?
Are there any other settings depended on extension?

### DBeaver Version

Community Edition 24.1.1

### Steps to reproduce

1. set the option "Autosave editor on close" to true 
2. open txt-file
3. change file 
4. close the tab

Expected: I expected the same behavior as for sql-files (no confirmation about saving changes and autosave)
Actual: there is a confirmation about saving changes

**Comment by E1izabeth** [comment]
These autosave settings are placed in SQL Editor page, which means that they are applied only for SQL Editor, not any other editors. 
You can check general Autosave setting here
![image](https://github.com/dbeaver/dbeaver/assets/28875055/97956343-ea10-45df-b5e6-09f15efb5896)

**Comment by ask9** [comment]
I would rather suggest to move these group of "auto-save" settings from "only to sql-files" to "all files in spite of extension".
I.e. move it from Editors -> SQL Editor, to User Interface -> Editors -> Autosave.
Especially these options: Auto-save after any modification, auto-save editor on close.

Because autosave interval you suggest me is quite another option and it is also affects sql-files in a way I don't need.

**Comment by arhayka** [comment]
We discussed the issue with the team and decided that right now, everything is working as expected, and there is no need to change this behavior.
