### ISSUE TITLE
Idle timeout setting from connection types does not affect connections

### ISSUE THREAD

**Issue by JTMosaic** [dbeaver/dbeaver#34516]
### Description

Two related issues:

1. When creating a new database connection, the default setting for "Close idle connection after (seconds)" is active and set to 0. This overrides any setting from the connection type and should not be the default
![image](https://github.com/dbeaver/dbeaver/assets/9417720/17de09f9-d0df-49df-8d1c-ada63c1aafcb)

3. Idle timeout settings from the connection type do not work

### DBeaver Version

24.1.1

### Operating System

macOS 14.5

### Database and driver

MariaDB 3.4.0

### Steps to reproduce

1. Create a new MariaDB connection
2. Go to the Connection settings | Initialization tab
4. The "Close idle connection after (seconds)" box is checked and set to 0
5. Uncheck the box
6. Assign the a connection type to the connection
7. Set the idle timeout for the connection to a short duration (10 seconds)
8. Connect to the database. The connection will not close after the idle time expires

**Comment by arhayka** [comment]
Thank you for the report, we want to fix the default timeout.

**Comment by magpieE5** [comment]
This issue exists for DuckDB as well

**Comment by Matvey16** [comment]
The value for idle timer is now copied from the connection type and would be changed if the type of the existing connection is changed.

But we still have a problem where the checkbox is actually not copied from the type settings. It is always on when the new connection is created.

**Comment by magpieE5** [comment]
FWIW, I installed the latest version just now and I'm still maintaining a persistent connection with DuckDB even with the idle set above zero.  This feature used to work, and was really helpful for development workflow with DuckDB which doesn't allow both an active read and write connection.

**Comment by JTMosaic** [comment]
This was set to be fixed in 24.1.4 so I'm going to wait for that release to re-test as it isn't quite working right in 24.1.3

**Comment by Matvey16** [comment]
@brockblampman Thank you for the report. It seems like this feature stopped working for embedded databases like DuckDB or SQLite. We will look into it
