### ISSUE TITLE
Vertical scrollbar not visible in Dark Theme

### ISSUE THREAD

**Issue by DedicatedTools** [dbeaver/dbeaver#3452]
Using DBeaver 5.0.4 CE connected to PostgreSQL DB.
I chose the Dark Theme (Windows > Preferences > General > Appearance). However, this makes the vertical scroll bar invisible. And I don't know which setting controls it.
The horizontal scrollbar is fine.

Also, in the Execution Log tab, successfully executed lines are unreadable, unless hoovered over. The background color's too light.

**Comment by ClodoaldoPinto** [comment]
Vertical and horizontal bars hard to distinguish in dark theme. How to change? 

![image](https://user-images.githubusercontent.com/1433209/62045135-fdc45480-b1da-11e9-8fd2-b448416f2d0b.png)

**Comment by mpcarter** [comment]
Also lost visibility of vertical scroll bar in Dark theme (after update to 6.2.4, 6.2.5 did not fix either). Horizontal scrolling is visible, but only after hovering over the bottom of the pane (actually it is super thin, but it expands on hover). 

Only affects SQL editor. All other panes, visibility is fine for both vertical and horizontal. 

Using Windows 10.

**Comment by uslss** [comment]
Affects 6.3.5. Scrollbars are shown only on hover. In classic theme scrollbars are always shown 
![2020-02-24_14h43_15](https://user-images.githubusercontent.com/31996417/75149952-3a761100-5714-11ea-9753-947bc44f171f.gif)

**Comment by ajshrom** [comment]
I was able to solve the problem of the nearly-invisible SQL editor scroll bars by selecting theme "Dark (Linux)" in properties (vs. "Dark").

**Comment by uslss** [comment]
not actual against 21.0.3
