### ISSUE TITLE
SQL Editor: Reconnect to the database if disconnected

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#34536]
Currently, if you try executing a query in the SQL editor against a disconnected data source, DBeaver will show an error that the connection needs to be established **manually**. Instead, we can ask the user if they want to connect and execute the query.

**Comment by ask9** [comment]
Please also consider an option in settings to disable the confirmation (agree automatically without confirmation).
Some other RDBMS behave in this way.

**Comment by serge-rider** [comment]
We already have this feature: 
![image](https://github.com/dbeaver/dbeaver/assets/6398845/8abc9124-caff-414e-a446-e48538251fc2)

Just enable "Connect on query execute"

**Comment by ShadelessFox** [comment]
I thought this option was turned off by default (and it indeed was until this year). I guess the issue can be closed now.
