### ISSUE TITLE
[MS SQL Server] SQL editor incorrectly reads metadata for tables from all schemas except dbo

### ISSUE THREAD

**Issue by k4rl0sA** [dbeaver/dbeaver#34537]
### Description

Al realizar una consulta en el editor Sql , no se puede realizar la edición de los campos ya que indica que los campos son de solo lectura, es necesario cerrar y volver a abrir el dbeaver para que se solucione el problema 

### DBeaver Version

24.1.1

### Operating System

Linux Ubuntu 22.04.4 LTS

### Database and driver

com.mysql.cj.jdbc.CommentClientInfoProvider

**Comment by k4rl0sA** [comment]
![Captura desde 2024-06-27 09-08-00](https://github.com/dbeaver/dbeaver/assets/71453079/54dfd860-c6a4-4ba3-9dca-b7d0632682e5)

**Comment by E1izabeth** [comment]
It's expected behavior in several cases.
If it's a fresh new table, that you just created a moment ago, then you need to refresh schema/tables/... in navigator by selecting the parent node and pressing Refresh (F5).

Also please translate your issue to English.

**Comment by AbdullahNUROGLU** [comment]
I'm experiencing the same issue. After the last update, a lock icon appeared. I haven't added any new columns or tables. I tried refreshing the table and the parent node, but this didn't resolve the issue.

I also attempted the 'Reset Settings' option, uninstalled the app, and deleted the 'DBeaverData' folder located in 'C:\Users\MYUSER\AppData\Roaming\DBeaverData'. Unfortunately, none of these steps fixed the problem.

**Comment by E1izabeth** [comment]
Please provide clear steps you follow to.

**Comment by E1izabeth** [comment]
@AbdullahNUROGLU 
Could you provide some minimal example to reproduce the issue?
Also we appreciate if you could provide an example of SELECT query, on which you reproduce this bug.

**Comment by E1izabeth** [comment]
Also does this table have a primary key?

**Comment by lilbruthal** [comment]
Hi there, I am facing same issue, and I believe this bug was introduced in the latest 24.1.1 release. I rollback to 24.1.0 and it doesn't occur.

Affected Dbeaver Community Release: 24.1.1

Database: 
MS SQL Server (PostgreSQL doesn't seem to be affected for me)

Observation: 
When executing script (ie: SELECT * FROM {Schema.TableName}), the result grid is not editable. Attempting to edit result in the following error:
![column is read only, not corresponding column](https://github.com/dbeaver/dbeaver/assets/24869197/efb1b912-c389-495c-8f21-02d58715702b)

The result grid also seem "locked" where there is a "lock" icon at the top left corner (this is new in 24.1.1)
![lock icon in result grid](https://github.com/dbeaver/dbeaver/assets/24869197/688f6e94-be82-4643-a227-ffeec5b966cf)
A same transaction screenshot from 24.1.0 below:
![result grid 24.1.0](https://github.com/dbeaver/dbeaver/assets/24869197/9645d8d0-8028-49b6-b3df-83ebb8841b18)


Further troubleshooting effort:
I tried to navigate to the target table (by ctrl + left click) and the grid is editable with a "pencil" icon at the top left corner

Another effort is by including the database name in the select statement (ie: SELECT * FROM {DatabaseName.Schema.TableName}) will also allow editing directly from the result grid. Similarly, a 
"pencil" icon can be seen at the top left corner.
![pencil icon in result grid](https://github.com/dbeaver/dbeaver/assets/24869197/189974eb-3d31-4037-991d-2b67a0ea7e42)


Hope this clarifies!

**Comment by E1izabeth** [comment]
We recently made some changes and expect that it may solve this issue. Please try Early Access version and let me know if the issue is still actual. You can download this version here https://dbeaver.io/files/ea/

**Comment by lilbruthal** [comment]
The top left icon changed, and I am able to see more information.  
![table metadata not found](https://github.com/dbeaver/dbeaver/assets/24869197/674d7af3-8230-4a7f-80e7-1b6ad2171d3b)

Issue persists whereby I can't edit directly from query result grid without specifying the Database Name even though I have selected the target Database in the "Active catalog/schema (ctrl+0)" from the top of the screen.

Perhaps some changes on using Fully Qualified Name causing it the Database Name to not be detected correctly? 

On side note, UPDATE query script that was generated came with the correct Database Name in v24.1.0 when editing directly via result grid.
![Fully qualified name in generated script](https://github.com/dbeaver/dbeaver/assets/24869197/bdb29510-57ea-4feb-830c-b9abbba78ecb)

**Comment by AbdullahNUROGLU** [comment]
As @lilbruthal mentioned earlier, this error started to occur after the last update. It's happening in all select queries. However, if I navigate to a table from the 'Database Navigator' and double-click it, the error doesn't occur in the 'Data' tab, and I can edit the data there.
![image](https://github.com/dbeaver/dbeaver/assets/31141414/9a4badc1-7b7c-43da-a00c-fbe4e2961bf8)

**Comment by Matvey16** [comment]
@lilbruthal It doesn't reproduce fore me
![image](https://github.com/dbeaver/dbeaver/assets/82543000/a2aedf83-751e-4219-a959-359e027857f1)

Can you please include what version of the database do you use, the whole DDL of any table that is afflicted and a screenshot of this page

![image](https://github.com/dbeaver/dbeaver/assets/82543000/19f8cbd8-8de3-4668-8652-2c05689c9465)

**Comment by Powsey** [comment]
Hello, the bug appeared in the last update (24.1.1)
You can rollback to the former version 24.1.0 to fix this (until they fix the issue in a next update). 

Former version can be downloaded here: https://github.com/dbeaver/dbeaver/releases/tag/24.1.0

It fixed it for me. 
Have a good one guys

**Comment by E1izabeth** [comment]
Unfortunately, we're uable to reproduce the issue. So, we need your help in investigation. Please answer @Matvey16 's questions https://github.com/dbeaver/dbeaver/issues/34537#issuecomment-2208727942

**Comment by AbdullahNUROGLU** [comment]
My DB version is
![image](https://github.com/dbeaver/dbeaver/assets/31141414/0ae6d2a9-bc60-43c0-b458-342b6f6e5eca)

![image](https://github.com/dbeaver/dbeaver/assets/31141414/95aef0eb-df7c-4d67-a170-7055544523d4)

**Comment by AbdullahNUROGLU** [comment]
My DB version is
![image](https://github.com/dbeaver/dbeaver/assets/31141414/0ae6d2a9-bc60-43c0-b458-342b6f6e5eca)

![image](https://github.com/dbeaver/dbeaver/assets/31141414/95aef0eb-df7c-4d67-a170-7055544523d4)

a DDL example:

`


CREATE TABLE job.JobDescription (
	Id bigint IDENTITY(1,1) NOT NULL,
	StatusId int NOT NULL,
	CreaDate datetime NOT NULL,
	CreaUserId int NOT NULL,
	ModifDate datetime NOT NULL,
	ModifUserId int NOT NULL,
	Name nvarchar(100) COLLATE Turkish_CI_AS NOT NULL,
	ScheduledTimeCron nvarchar(50) COLLATE Turkish_CI_AS NOT NULL,
	PluginName nvarchar(250) COLLATE Turkish_CI_AS NOT NULL,
	EmailNotificationActive bit NOT NULL,
	EmailNotificationReceivers nvarchar(1000) COLLATE Turkish_CI_AS NOT NULL,
	Active bit DEFAULT 0 NOT NULL,
	AllowTrigger bit DEFAULT 0 NOT NULL,
	Module varchar(100) COLLATE Turkish_CI_AS NULL,
	CONSTRAINT PK_JobDescription PRIMARY KEY (Id)
);
`

**Comment by FabLCDS** [comment]
Hello, as said in [#34452](https://github.com/dbeaver/dbeaver/issues/34452), adding DB name as prefix solves the issue.
But it's not a permanent solution.

**Comment by Matvey16** [comment]
@AbdullahNUROGLU Thank you for your info. I've reproduced it.

**Note for developers:** It is not reproducible if the database and the schema have the same name, also not reproducible specifically in `dbo` schema

**Comment by serge-rider** [comment]
The bug was caused by #23203 
Fixed

Fix will included in the next release (24.1.2)

**Comment by k4rl0sA** [comment]
[Grabación de pantalla desde 04-07-24 08:24:24.webm](https://github.com/dbeaver/dbeaver/assets/71453079/7d2a8818-97cb-4870-8abc-1420556631df)
