### ISSUE TITLE
Some functions do not use color from settings

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34542]
### Description

I don't know where to find complete list of all functions in postgres, but I do not see these functions are highlighted with a new color from settings:
pg_terminate_backend
pg_backend_pid
pg_database_size
pg_sleep

![изображение](https://github.com/dbeaver/dbeaver/assets/33929221/7d6006dd-5420-483b-8dba-89d264e3c9a3)

### DBeaver Version

Community Edition 24.1.2

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

**Comment by ask9** [comment]
Linked with: #34371

**Comment by E1izabeth** [comment]
Looks like these functions are not recognized as functions. Probably, we need to add them to dialect (see class PostgreDialect).

**Comment by Rakib-mbstu** [comment]
Can I try?

**Comment by E1izabeth** [comment]
Sure

**Comment by Rakib-mbstu** [comment]
I have created a PR. Please let me know if u have any feedback.

**Comment by asifjoardar** [comment]
hi @E1izabeth 

Seems like there are more PostgreSQL-specific functions missing from the dialect. Can I add them and make a PR? This will be my first contribution to DBeaver

missing functions:

**System Information Functions:**
pg_is_in_recovery
pg_is_in_backup

**Logical Replication Functions**
pg_replication_origin_advance
pg_replication_origin_create
pg_replication_origin_drop
pg_replication_origin_session_reset

**File Handling Functions**
pg_ls_dir
pg_read_file
pg_read_binary_file
pg_stat_file

**Comment by E1izabeth** [comment]
Yes, let's add them too.

**Comment by E1izabeth** [comment]
Please create the new issue for this.
