### ISSUE TITLE
Choose Catalog Schema

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#34557]
### Description

Hi

Can you please assist with understanding how the following should work. 

I am connecting to Salesforce Data Cloud using the JDBC driver as prescribed by Salesforce. When I open a new SQL editor the correct Data Source is selected. However the Catalog/Schema dropdown is populated with "N/A". Only once I execute a query does it auto populate the correct Schema. The implication of this is that I can not create a new SQL editor window where SQL proposales are provided.

Either I have a incomplete configuration, do not fully understand how the tool works, take note I am a new user or there is a possible bug.

Thanks,

Leon.

### DBeaver Version

Enterprise Edition 24.1.0

### Operating System

Windows 11

### Database and driver

Salesforce Data Cloud; jdbc driver Salesforce-CDP-jdbc-1.19.7

### Steps to reproduce

1. Open connection to database.
2. Open new SQL Script editor.
3. Select Catalog / Schema drop down is populated with N/A
4. Start new SQL statement.
5. No database objects appear in prompt that appears as proposals.
6. Wait a few seconds and try again.
7. Prompt for database objects now contains database objects to choose from.
8. Add where clause and prompt appears with no column prompts.
9. Execute select * from [table name]
10. Select Catalog / Schema drop down is now populated with schema name for data source.
11. Retry where clause and after a few seconds database object columns are available for selection in prompt.

**Comment by E1izabeth** [comment]
Please contact out tech support team for PRO versions users in the online support system https://dbeaver.com/support/. They're happy to assist

**Comment by ghost** [comment]
Hi,

I have since been able to resolve the issue. However I can not provide the exact reason for this. This is due to comparing the installation with a collegue. After making a few changes, we decided to do a fresh installation and not change any of the settings. This the produced the desired functionality.

I am confident that I made changes to either the data source or driver settings that introduced this challenge. If I had more time, I would like to have been able to provide better context, but for now I have the functionality working.

Thanks for your reply!

Leon

**Comment by E1izabeth** [comment]
Thank you for update. Then I'll close the issue. Let me know if it appears again
