### ISSUE TITLE
Executing UTF-8 SQL File in Windows10 outputs unexpected characters

### ISSUE THREAD

**Issue by rogyw** [dbeaver/dbeaver#3455]
Windows 10
DBeaver 5.0.4 Community
MariaDB
SQL File in UTF-8 format - copied from Linux source.

Problem/Question: Attempting to run "Database Name" > "Tools" > "Execute Script" and supply a 80MB+ UTF-8 formatted sql file. When using verbose output, I can see DBeaver is sending/outputting  multiple characters for each extended character - and that is then showing up on the target database output.
Short simplified example:

'It’s a “TEST”.' 
includes:
U+2019 : RIGHT SINGLE QUOTATION MARK {single comma quotation mark}
U+201C : LEFT DOUBLE QUOTATION MARK {double turned comma quotation mark}
U+201D : RIGHT DOUBLE QUOTATION MARK {double comma quotation mark}

Verbose DBeaver script output and target database value results in something like 
 'Itâ€™s a â€œTESTâ€�.'
 
Have searched for places in DBeaver to indicate file input is UTF-8:
"Windows" > "Preferences" > "General" > "Workspace" > "Text file encoding"  has been changed to "Other:" and "UTF-8"

The database connection is to a database with utf8mb4 / utf8mb4_general_ci

If I open the small UTF-8 test script now, I can get it to display as expected in DBeaver SQL Editor. However I can't open the 80MB+ file as the UI becomes unresponsive and Windows offers to close it.

How do I set the format of the executed script to UTF-8?

Thanks.

**Comment by rogyw** [comment]
Update: I have found:
"Project - General" panel >"Scripts" >  (Right Click Menu) > "Properties" > "Resource" > "Text file encoding"  set to "Other" and "UTF-8" > (Apply + Close) 

But making this change results in the same issue.

Also tried adding the folder the script is in to the project > Scripts  > folder list and checking the properties of the script is set to utf-8 too.

**Comment by rogyw** [comment]
In "Database Name" > "Tools" > "Execute Script" has a  "Settings" section with an option for "Extra command args:" 
adding `--default-character-set=utf8mb4` resolved the issue in the target database. DBeaver verbose logging will still show the wrong characters.

**Comment by FlamboyantN** [comment]
Same issue here. 

After restarting DBeaver / reloading the file though it again 'forgets' it's supposed to be encoded in UTF-8 and displays gibberish. 

Thanks for the suggested improvements, however, they didn't fix it for me (v5.1.3). Once I saved it in the global settings it persisted through restarts:
1. Click on the **Window** menu item -> **Preferences**
2. Search for "encoding" or go to **General** -> **Workspace** 
3. Set "Text file encoding" at the bottom to "Other:" & select UTF-8 from the drop down.

Voilà.

**Comment by uslss** [comment]
Hi @rogyw , is an issue still actual for you?
