### ISSUE TITLE
Output messages are duplicated in case of several result sets are returned

### ISSUE THREAD

**Issue by zolovey** [dbeaver/dbeaver#34563]
### Description

Messages in output are shown several times when executing query that return several data sets
![image](https://github.com/dbeaver/dbeaver/assets/56155099/f276068d-4ed1-48c5-bf81-d181b52645ec)

### DBeaver Version

Community edition 24.1.0

### Operating System

Windows 10

### Database and driver

Database: SAP IQ SAP IQ/16.1.050.2532/13911/P/SP05.11/Linux/Linux64 - x86_64 - 3.10.0-327/64bit/2024-01-04 17:25:36
Database driver: jConnect (TM) for JDBC (TM) jConnect (TM) for JDBC(TM)/20.00.000.01(Build 27499)/P/EBF29953 C/JDK 1.8.0/jdbcnebula/OPT/Wed Jul 14 02:53:36 PDT 2021

### Steps to reproduce

Execute following query
```
BEGIN

    SELECT 1;

    MESSAGE 'Affected rows 1: ' + CHAR(13) TO CLIENT;

    SELECT 2;

    MESSAGE 'Affected rows 2: ' + CHAR(13) TO CLIENT;

END

### Additional context

_No response_

**Comment by E1izabeth** [comment]
Hi, @zolovey 
We recently fixed similar issue for Oracle. Could you try Early Access version to check, that the issue is solved? You can download it here https://dbeaver.io/files/ea/

**Comment by zolovey** [comment]
hi @E1izabeth 

Still same issues

![image](https://github.com/dbeaver/dbeaver/assets/56155099/7ffdbd8c-9f9e-4cb2-86de-f958ede228c6)

**Comment by E1izabeth** [comment]
Thank you for checking
