### ISSUE TITLE
Backspace/Delete removes more symbols than expected

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34569]
### Description

Backspace or Delete keys delete two space symbols instead one symbol at a time.

### DBeaver Version

Community Edition 24.1.2

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

https://github.com/dbeaver/dbeaver/assets/33929221/e720a3b1-ab8c-4ef2-9b78-97c95ff859a2

1. Use this query:
```
select  * 
from pg_class;
```

2. notice that there are two spaces after the word "select" 
3. try to delete one of them using backspace

Expected: only one symbol is deleted
Actual: two space-symbols deleted

### Additional context
Please also check Delete key which behaves the same way.

**Comment by E1izabeth** [comment]
Unfortunately, I can't reproduce the issue. I tried with Backsace and Delete keys - works as expected for me.

https://github.com/dbeaver/dbeaver/assets/28875055/2e285bb2-5dcf-4798-a3ce-d68630a5d4c4

**Comment by E1izabeth** [comment]
@ask9 could you send this query as a file? Maybe you have some special characters there

**Comment by ask9** [comment]
Yes, sure. I have no problems to reproduce it with this file.
[Script-9.zip](https://github.com/user-attachments/files/16052000/Script-9.zip)

Have you tried it on fresh install with all settings by default on Version 24.1.2.202406262322?

**Comment by ask9** [comment]
OK, I can see now that it is really not reproducible on a fresh install on my side also.
There seems to be there is some setting involved...
So don't waste your time. 
I'll back to you with reproducible steps after some time.

**Comment by ask9** [comment]
@E1izabeth Export my settings from this file (File - Import - General - Preferences) and repeat the steps.
It becomes reproducible.
[preferences dbeaver_.zip](https://github.com/user-attachments/files/16052299/preferences.dbeaver_.zip)

**Comment by E1izabeth** [comment]
Still can't reproduce. I'll ask our QA team to try.

**Comment by humphreygao** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/52394598/ec660039-60e7-47ac-b6b1-bca3f13c351c)
this is a setting

**Comment by E1izabeth** [comment]
I reproduced with this setting. Thank you.

**Comment by E1izabeth** [comment]
@ask9 please turn off this setting and it will stop happening

**Comment by ask9** [comment]
Thank you! It works now as expected!
