### ISSUE TITLE
Visualize connection establish in navigator trees

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#34579]
Currently connection establish is visualized only when user expands navigator item explicitly.

When connection is triggered from SQL editor activation there is no any visualization (connect job is visualized in background tasks but it is hard to mention).

**Comment by MashaKorax** [comment]
https://github.com/dbeaver/dbeaver/assets/84867187/a308208f-06e6-4935-8781-67a3b8df36a4

**Comment by MashaKorax** [comment]
verified
