### ISSUE TITLE
Show result sets one under the other instead of different tabs

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34570]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to compare two or more result sets of queries from different tabs.
I have to switch between them to compare result sets by eyes, and it is not comfortable.

**Describe the solution you'd like**
I suggest to add option in settings to show result sets one under the other instead of different tabs.
See how it works in SSMS.

![2  All result sets are shown on one page  Desired behavior (SSMS)](https://github.com/dbeaver/dbeaver/assets/33929221/99c61da5-179d-468d-8dc6-0b12c09f8131)

Why?
This is useful when user wants to analyze quickly more than one result set at a time.
User wants to avoid switching between different tabs using mouse.
There could be more than 2 tabs and user wants to compare/correlate data in datasets by eyes.
User doesn't want to rewrite the queries using join (it might be complicated or it would need additional efforts).
User doesn't want to open different windows and move each query in its window (loosing time + additional efforts, breaking focus).
User doesn't want to detach/rearrange windows (it takes time and efforts, and user needs easy way).

You can add global option in settings to show result sets one under the other (true/false).
In this way all the executed queries will be shown as on the gif.

The better way is to add separate hotkey so that user decides in any particular case whether he wants to see results set in different tabs as it is now, or by a new algorithm (for example, with Shift pressed):
Alt + X => execute sql query (in different tabs = as it works now)
Alt + Shift + X => execute sql query (one under the other = new algorithm)

**Comment by E1izabeth** [comment]
Please take a look at this feature. It sounds like what you want https://github.com/dbeaver/dbeaver/wiki/SQL-Editor#multiple-results-in-one-tab

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by ask9** [comment]
> Please take a look at this feature. It sounds like what you want [](https://github.com/dbeaver/dbeaver/wiki/SQL-Editor#multiple-results-in-one-tab)

Yes, thanks, it seems what I need!
It is OK that it is closed.
