### ISSUE TITLE
The file that needs to be read is in the wrong address when I develop the project.

### ISSUE THREAD

**Issue by Erional** [dbeaver/dbeaver#34571]
### Description

I can't follow the steps in [develop-in-idea](https://github.com/dbeaver/dbeaver/wiki/Develop-in-IDEA) to develop.
The file that needs to be read is in the wrong address.
<img width="941" alt="PixPin_2024-06-29_20-39-53" src="https://github.com/dbeaver/dbeaver/assets/105800742/52969310-5ac9-4b8b-811d-85cb08a99672">
<img width="330" alt="PixPin_2024-06-29_20-43-38" src="https://github.com/dbeaver/dbeaver/assets/105800742/d402f410-4fd6-4fe6-b80d-5dae6ae9aeaf">

### DBeaver Version

Community Edition 24.1.1

### Operating System

windows 10

### Additional context

1. Create a folder /e/code/dbeaver-ce.
2. cd dbeaver-ce
3. git clone git@github.com:dbeaver/dbeaver.git
4. git clone git@github.com:dbeaver/dbeaver-common.git
5. git clone git@github.com:dbeaver/idea-rcp-launch-config-generator.git
6. cd dbeaver
7. sh build.sh
8. sh generate_workspace.sh
The file that needs to be read is in the wrong address.

**Comment by Destrolaric** [comment]
@Erional Hi, can you try running the bat script and see if it will work for you? It might be an issue of handling of MingGW input by the script.

**Comment by Erional** [comment]
works
