### ISSUE TITLE
FK navigation issue

### ISSUE THREAD

**Issue by alesc2000** [dbeaver/dbeaver#3459]
When I click on FK cell in resultset I get redirrected to the FK table with filtered result. If I have 2 different FK to the same table, it always filters to the first FK in the result:
SELECT a.id, a.currency_id, b.currency_id
FROM a
	INNER JOIN b ON (b.a_id = a.id);
![screenshot-2018-5-11](https://user-images.githubusercontent.com/19900533/39924328-f937df44-552f-11e8-9a3e-f55233cd5bb7.png)

In my case it always filters currency_id = 5157, even if I click on the 5158 cell.

**Comment by uslss** [comment]
cannot reproduce it against 7.2.
if the issue is still actual - feel free to reopen it.
