### ISSUE TITLE
Oracle: Scheduler Job Run Log shows "No Data"

### ISSUE THREAD

**Issue by Arne1346** [dbeaver/dbeaver#34592]
### Description

Oracle: Scheduler Job Run Log shows "No Data" - even if this is existing.
This is the case for **ALL** Oracle Scheduler Jobs. The screenshots just express **ONE** example

DBeaver:
![image](https://github.com/dbeaver/dbeaver/assets/72160775/f2d05214-188f-40c5-be6a-0853f08b3985)

TOAD:
![image](https://github.com/dbeaver/dbeaver/assets/72160775/16fdc82f-33c6-42d2-93d4-b6220482fdce)

### DBeaver Version

Community Edition 24.1.1

### Operating System

Win 11

### Database and driver

![image](https://github.com/dbeaver/dbeaver/assets/72160775/44680d8c-a968-4914-ad48-c6c3863b3175)

![image](https://github.com/dbeaver/dbeaver/assets/72160775/b1d9a87d-e4a2-41d1-bffc-80e387585824)

**Comment by ShadelessFox** [comment]
Hello @Arne1346,

Can you open the query manager and refresh or open the run log for a job again? 

![image](https://github.com/dbeaver/dbeaver/assets/35821147/1f78bb82-9143-405c-be72-ef4402f206c2)

Please ensure you have the "User filtered" filter checked here in the context menu:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/86d85ec8-2297-441e-97e6-0760717b6f39)

**Comment by Arne1346** [comment]
Hi,
For me the filter button does not work - clicking on it does not open
anything.

ShadelessFox ***@***.***> schrieb am Do., 11. Juli 2024,
17:00:

**Comment by LonwoLonwo** [comment]
Hello @Arne1346 

Looks like this is your case: https://github.com/dbeaver/dbeaver/issues/17909

Could you please check this workaround?

> You can click on your connection -> choose navigation view -> choose "advanced".
> Then you will see the SCHEDULER_JOB view.

**Comment by Arne1346** [comment]
Hi ShadelessFox,

Sorry - due to summer holidays my response took a bit longer.

[image: image.png]

Clicking on the little "green SQL" icon:
[image: image.png]

BUT:
[image: image.png]

I am logged in with the same user account who "owns" the scheduler job.

As you can see on my screenshot all filters are empty / filter icon in the
first screenshot is greyed out.


Please let me know if you need more information.


Thanks,
Arne

Am Do., 11. Juli 2024 um 17:00 Uhr schrieb ShadelessFox <
***@***.***>:

**Comment by ShadelessFox** [comment]
@Arne1346 thanks for the response.

Unfortunately, you can't attach files when replying by email. Please attach them directly on GitHub.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
