### ISSUE TITLE
Connection still alive long after Azure AD token expires

### ISSUE THREAD

**Issue by tommasodargenio** [dbeaver/dbeaver#34594]
### Description

I've a few pgSQL servers in Azure and I've implemented access to them using my AZ Entra credentials as documented [here](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-configure-sign-in-azure-ad-authentication).

I can successfully connect to the server using the AZ token as a password, however even though my AZ token expires (after 1 hour roughly), dBeaver still keeps the connection alive (the conn keep alive is set to 0 - close idle connection is disabled) and I can still run queries. I did a test with the dashboard open which queries the server every few seconds, I was expecting this to fail after the token expired however it did not and kept on running.

If I try to reconnect (or refresh the connection) to the server without changing or refreshing the token then it behaves as expected refusing to connect.

I expect it to drop the connection (or fail anyway) if I try to run a query when the token is expired or have the dashboard open (i.e. this should stop updating) - When I configure it to close idle connections after xx seconds I get the behaviour I want, however, this is not the point, as it should do that when the token expires and is no longer valid.

Is this a bug or have I misconfigured something?

### DBeaver Version

Community Edition 24.0.5

### Operating System

macOs Sonoma 14.5

### Database and driver

Database name and version: pgSQL 14.11 on x86_64 linux Ubuntu 7.5.0
Driver: org.postgresql.driver standard driver 42.7.2

**Comment by ShadelessFox** [comment]
Hello @tommasodargenio,

Even though your token has expired, your session is still alive. I don't think it's either DBeaver or the driver issue; it seems that's just how the database works.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
