### ISSUE TITLE
Ask for username or password on connect if absent.

### ISSUE THREAD

**Issue by ravshansbox** [dbeaver/dbeaver#3460]
Ask for username or password on connect if absent. This is useful for connecting to databases with different username and passwords with single connection.

**Comment by serge-rider** [comment]
DBeaver will ask for password unless you check option "Save password in connection properties.

**Comment by serge-rider** [comment]
The same:
![image](https://user-images.githubusercontent.com/6398845/39961173-8b8414ee-5639-11e8-9657-95512ce805bd.png)
