### ISSUE TITLE
Simple Structure Compare fails when the generated file name is too long.

### ISSUE THREAD

**Issue by nutmix** [dbeaver/dbeaver#34613]
### Description

When you compare several database (8 in our case), each with around 30 character names, it cant save the generated comparison file, it gives the error: 

`"C:\Users\myfirstname.mylastname.myorg\Downloads\compareXXXXXX-report.html (The filename, directory name, or volume label syntax is incorrect)"`

where XXXXX is a long list of our database names which gives a path of 335 characters.

The limit in windows 10 for file names is 255 chars
The limit in windows 10 for the path is 260 chars. 

In this case, I would recommend that dbeaver either allow users to edit the file name, or truncate the file name.

It is possible in windows 10 to enable long path names, but this requires regedit which is blocked on all corporate PCs, and it didnt solve the problem for me.

### DBeaver Version

community edition 24.1.1

### Operating System

windows 10

### Database and driver

N/a

### Steps to reproduce

On a windows 10 Machine:
1) select 7 databases to compare, each with names > 30 chars.
2) right lick on one of the selected databases and choose "compare/migrate"->"Simple Structure Compare"
3) hit next until it tries to save the file.
4) observe error saving file.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
@nutmix we fixed the issue. You can try Early Access version https://dbeaver.io/files/ea/
