### ISSUE TITLE
Cannot set field value to NULL when editing Table's "Data" tab

### ISSUE THREAD

**Issue by njminchin** [dbeaver/dbeaver#34611]
### Description

The right click context menu has no option to set a field value to `NULL` when editing table data using the table's "Data" tab view editor.

I realise the reason is because the field I'm trying to set to `NULL` is a non-nullable field, however it's also `GENERATED ALWAYS` so it **must be NULL** when inserted...

My strong opinion is that this option should never be excluded from being selected, regardless if the field is non-nullable or not. If the user NULLs a field accidentally and tries to save the edits, they'll get an error. We can then go back and fix it, rather than not being able to fix it due to lacking visibilility logic.

![image](https://github.com/dbeaver/dbeaver/assets/47411133/96d01a1c-156c-49b2-8b3c-92e76085db24)
![image](https://github.com/dbeaver/dbeaver/assets/47411133/475a75f4-338d-4645-8596-15cc8277f51b)

### DBeaver Version

Community Version 24.1.1.202406231636

### Operating System

Windows 10

### Database and driver

Postgre 15

### Steps to reproduce

1. Create table with field set to non-nullable with a generated expression.
2. Insert a row
3. Duplicate the row, try to NULL the non-nullable generated field value

**Comment by E1izabeth** [comment]
What's the column type?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by kingho** [comment]
Only available if the field is allowed to be NULL

<img width="592" height="224" alt="Image" src="https://github.com/user-attachments/assets/4b7d8a98-a70e-4681-adbe-f0035cf58a0f" />
