### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by BobInCT** [dbeaver/dbeaver#3462]
1. In Postgres, DBeaver doesn't recognize a schema with a period in it such as rms.nrcadmin.  This is allowed in Postrgres and I have to do setup in Admin4 to get around this problem

2. Adding a function to an existing bit of text is quite annoying because of the automatic addition of a closing parentheses bracket.  For example I have an existing column XXX in a query and want to add a rounding statement to it.  round()XXX is what happens and I have to manually remove the closing ")".  And if I forget I get errors.  Please fix so that if starting next to existing text that doesn't happen, or put the ")" at the end of the text.

**Comment by serge-rider** [comment]
1. What do you mean under "don't recognize"? I can create and browse schemas with any characters in name, including period:
![image](https://user-images.githubusercontent.com/6398845/39961167-512fe2fa-5639-11e8-911f-7ebee2360def.png)
2. You can disable this in preferences:
![image](https://user-images.githubusercontent.com/6398845/39961171-6acf7338-5639-11e8-9481-50b6845fb89b.png)

**Comment by BobInCT** [comment]
1.       I haven’t tried the latest version but with version 5.0.2 I get the following error when creating a new schema.  If this has changed in the next one then I’ll be happy to download it.

**Comment by serge-rider** [comment]
Please reply on GitHub, you can't use attachments in email notifications reply.

**Comment by BobInCT** [comment]
Sorry, new to GitHub.  This is the error I see with version 5.0.2 by trying to add new schema abc.xyz

![image](https://user-images.githubusercontent.com/2408296/39961499-69380bb8-5605-11e8-93d5-82a32052c3ce.png)

**Comment by serge-rider** [comment]
Yep, I think you should try the latest version. 
There were a few fixes in PG extension recently.

**Comment by BobInCT** [comment]
Thanks.  And appreciate the work you're doing, great product

**Comment by BobInCT** [comment]
I just updated to version 5.05 and still get the above error when I attempt to add a new schema via the following dialog

![image](https://user-images.githubusercontent.com/2408296/39961619-3a4c6bac-5608-11e8-8ecd-253fbe3305be.png)

**Comment by serge-rider** [comment]
Now I can reproduce this.
The problem is not in the schema name but in the owner name (which also contains period).
Fix will be added in 5.0.5, thanks for details.
