### ISSUE TITLE
Add search over option's name in "Preferences" window

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34632]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to find some option that I remember the name of but don't remember its location in hierarchy of a tree in Preferences window.
In this case user has to click each item in a tree and search it manually.
The more settings are added in the settings, the more difficult it is to find the desired option.

You already have an excellent solution to fix the issue: search over Preferences.
But for some reason you don't make use of it fully: search over the certain option name do not give any results.

I suggest to search over text of all available options on a form.

Ideally, that newly added options should be searchable without adding its text manually to a search base to avoid the case when the option was added to a form but not available for searching.

**Comment by E1izabeth** [comment]
Thank you for idea.
