### ISSUE TITLE
[Firestore] - Update json data

### ISSUE THREAD

**Issue by mviniciuscorrea** [dbeaver/dbeaver#34639]
### Description

I want update my json data into firestore, so i make a select to bring a unique data from collection and go to button JSON.

I added a new object like this:

```
customer: {
    firstName: "Marcus",
    lastName: "Corrêa",
    newsletter: true,
    termsAndConditions: false
}
```

When i try save, show me this error 

Attribute ##document was changed but it hasn't associated unique key

![image](https://github.com/dbeaver/dbeaver/assets/37540504/d8fee6f3-1853-44aa-ae39-3ba111987646)

How i can updated my json and save? Need i try another way?

tks

### DBeaver Version

Enterprise 24.1.0

### Operating System

macOS Sonoma 14.5

### Database and driver

Firestore

### Steps to reproduce

1 - Make a select into editor
2 - Go jo JSON button option
3 - Edit whatever field
4 - Click Save button in bottom screen

**Comment by E1izabeth** [comment]
Please contact out tech support team in the online support tickets system https://dbeaver.com/support/
They will be glad to help you.

**Comment by Destrolaric** [comment]
I can't reproduce in recent devel version, please contact our support.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
