### ISSUE TITLE
"Check for Updates" brings error message: "PKIX path building failed"

### ISSUE THREAD

**Issue by Paul2701** [dbeaver/dbeaver#34644]
### Description

1. In Menu Help choose "Check for Updates"
<img width="244" alt="image" src="https://github.com/dbeaver/dbeaver/assets/34183524/bc18d21d-b386-413b-9a75-6a8ac473bfaa">

Error message appears:

> Cannot obtain version information. Perhaps the network connection is down?
Reason:
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

![image](https://github.com/dbeaver/dbeaver/assets/34183524/696a1a49-e840-4361-82f4-abab2ba5bb0b)

### DBeaver Version

Version 24.1.1.202406231636

### Operating System

Windows 10

### Database and driver

I don't use any DB, I want to check to update...
This didn't work in the previous version either.

### Steps to reproduce

s. description

**Comment by ShadelessFox** [comment]
Hello @Paul2701,

Have you tried turning on this option?

![Image](https://github.com/dbeaver/dbeaver/assets/35821147/fd6822e2-f92b-4955-8251-2c0236630baa)

Please let me know if it helps.

**Comment by joyvuu-dave** [comment]
@ShadelessFox What would the equivalent step be on the mac client? (I'm having the same issue)

 Note: I tried toggling on the two "Trust all content" checkboxes in the Trust preferences pane, but that didn't appear to have an effect.

**Comment by ShadelessFox** [comment]
@joyvuu-dave I assume you have the same issue as in https://github.com/dbeaver/dbeaver/issues/34710. Please track the progress and updates there.

**Comment by Paul2701** [comment]
@ShadelessFox 
this option is always disabled for me:
![image](https://github.com/user-attachments/assets/ab707d5d-ffaf-44ef-b2cd-db174eafd646)

**Comment by serjiokov** [comment]
Could you please provide the log details?

**Comment by E1izabeth** [comment]
@Paul2701 it might be disabled in case if you configured custom trust store. Is it the case?

**Comment by Paul2701** [comment]
@E1izabeth 
thank you! If I disable the custom trust store, it works :-)
