### ISSUE TITLE
在sql编辑窗口 使用搜狗输入法  切换中文时，打字不显示

### ISSUE THREAD

**Issue by wangyao123haha** [dbeaver/dbeaver#34646]
### Description

在sql编辑窗口 使用搜狗输入法  切换中文时，打字不显示

### DBeaver Version

24.1.1

### Operating System

windows10

**Comment by MashaKorax** [comment]
Hello, @wangyao123haha. Please translate your issue into English.

**Comment by wangyao123haha** [comment]
When using Sogou input method to switch to Chinese in the SQL editing window, typing is not displayed

**Comment by wangyao123haha** [comment]
When using Sogou input method to switch to Chinese in the SQL editing window, typing is not displayed

> Hello, @wangyao123haha. Please translate your issue into English.

**Comment by MashaKorax** [comment]
Do you use a special program?

**Comment by MashaKorax** [comment]
I can't reproduce the issue. It works  for me, but you can reopen the issue and provide details to reproduce it. 
![iScreen Shoter - DBeaver Enterprise Edition - 240718172128](https://github.com/user-attachments/assets/293c555f-e182-40b1-86b3-c629a11f9203)
