### ISSUE TITLE
The use of dbeaver to update table field annotations in the Dameng database does not take effect

### ISSUE THREAD

**Issue by yumifen** [dbeaver/dbeaver#34641]
### Description

![WX20240704-094215](https://github.com/dbeaver/dbeaver/assets/32358947/b85273d4-c6c2-4c96-8bd4-d2f7ca9ebd3b)
Adding or modifying fields after adding a new table does not take effect. Under normal circumstances, the following message should appear: "comment on column wyb_smgs.info.fstaion_id is' 发站id '" in order to add corresponding comments to the fields

### DBeaver Version

版本: 24.1.1.202406231636

### Operating System

macOS Sonoma 14.5

**Comment by MashaKorax** [comment]
Hello @yumifen . What version of Dameng do you use?

**Comment by jeffxjh** [comment]
dm 64 v8 version has the same problem.
![image](https://github.com/user-attachments/assets/77738352-e375-4a7b-b9d0-8b0b48bfccaa)
