### ISSUE TITLE
DBeaver closes on clicking on No button in "Are you sure" window

### ISSUE THREAD

**Issue by pasolid** [dbeaver/dbeaver#34642]
### Description

DBeaver is closing even if option No is clicked in "Are you sure" dialog window (appears on close dbeaver)

### DBeaver Version

24.1.1.202406231636

### Operating System

MacOS Sonoma 14.5

### Steps to reproduce

Open DBeaver.
Click on close button (x)
Closing dialog window with "Are you sure" appears. 
Click on "No"
DBeaver terminates anyway

**Comment by MashaKorax** [comment]
Duplicate https://github.com/dbeaver/dbeaver/issues/34462
