### ISSUE TITLE
[Sqream] I want Keep-Alive to work even when a query is running

### ISSUE THREAD

**Issue by yuri-sq** [dbeaver/dbeaver#34651]
Somewhat opposite to #4704.

I'm sending long-running queries to a Sqream server, DBeaver doesn't send keep-alive packets while the query is active, so the connection is dropped somewhere between the client and the server after 1 hour. DBeaver doesn't receive any information about it.

As written in #4704, Vertica doesn't allow parallel queries. But Sqream allows. If it is possible it would be cool to detect automatically if the connector allows to keep-alive in parallel, and use it. In any case, a setting in UI would be enough.

**Comment by E1izabeth** [comment]
Thank you for request

**Comment by Destrolaric** [comment]
@yuri-sq Hi, are you using Vertica driver or Generic SQream driver?

**Comment by yuri-sq** [comment]
> @yuri-sq Hi, are you using Vertica driver or Generic SQream driver?

Generic SQream driver

**Comment by ShadelessFox** [comment]
Hello @yuri-sq,

Have you tried setting the keep-alive interval in connection settings?

![Image](https://github.com/user-attachments/assets/113b5835-fd80-4738-b71c-093d2756cbbb)

**Comment by yuri-sq** [comment]
Yes, but it looks like the driver ignores this setting.

**Comment by E1izabeth** [comment]
Could you tell me your driver and server version? You can get this information by clicking `Test connection...` button in the `Connection configuration` dialog.
![image](https://github.com/user-attachments/assets/acc2caae-cf87-42f8-8c63-b6c7697e137f)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
