### ISSUE TITLE
Export MSSQL DDL inconsistency

### ISSUE THREAD

**Issue by JonnyTech** [dbeaver/dbeaver#3465]
Using DBeaver 5.0.5 with MS JDBC driver on Linux to export data causes error on import due to restrict:

`CONSTRAINT [FK_dbo.tablename1] FOREIGN KEY (UserId) REFERENCES tablename2(Id) ON DELETE CASCADE ON UPDATE RESRTICT`

but with Windows it is not there so no error

`CONSTRAINT [FK_dbo.tablename1] FOREIGN KEY (UserId) REFERENCES tablename2(Id) ON DELETE CASCADE`

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on the issue for a long time
additional info is needed to reproduce an issue.
ticket will be closed. feel free to reopen an issue and add info that could help to investigate it.
