### ISSUE TITLE
[DB Navigator] Action icons and object statistic disappear if there is horizontal scrollbar in DB Navigator

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#34656]
### Description

Action icons and object statistic disappear if there is horizontal scrollbar in DB Navigator

### DBeaver Version

24.1.2

### Operating System

win11

### Steps to reproduce

https://github.com/dbeaver/dbeaver/assets/31996417/2b67e86a-bc2f-48ff-b9d3-c230136ef141

**Comment by ShadelessFox** [comment]
I believe this is an expected behavior. Although not the desired one.
