### ISSUE TITLE
Some PostgreSQL functions do not use color

### ISSUE THREAD

**Issue by asifjoardar** [dbeaver/dbeaver#34650]
### Description

missing PostgreSQL-specific functions:

**System Information Functions**
pg_is_in_recovery
pg_is_in_backup

**Logical Replication Functions**
pg_replication_origin_advance
pg_replication_origin_create
pg_replication_origin_drop
pg_replication_origin_session_reset

**File Handling Functions**
pg_ls_dir
pg_read_file
pg_read_binary_file
pg_stat_file

### DBeaver Version

Community Edition 24.1.2

### Operating System

Windows 10

### Database and driver

PostgreSQL 16.1
PostgreSQL JDBC Driver 42.7.2

**Comment by asifjoardar** [comment]
hi @E1izabeth 

I have added the issue and am working on it.

**Comment by ask9** [comment]
Hope you will add all available functions from docs:
https://www.postgresql.org/docs/16/functions.html

**Comment by asifjoardar** [comment]
hi, @E1izabeth 
I have made a PR. Could you please check it?
