### ISSUE TITLE
Window closes even when I say "no" at the "are you sure" dialog.

### ISSUE THREAD

**Issue by vfest** [dbeaver/dbeaver#34672]
### Description

When I hit the close window button by mistake, I hit "no" at the "are you sure?" dialog.
Then DBeaver closes anyway.

### DBeaver Version

Community Edition 24.1.1

### Operating System

Windows 10 Entreprise

### Steps to reproduce

1. Open DBeaver
2. Hit the close button
3. Hit "no" at the "are you sure?" dialog.

**Comment by ask9** [comment]
Update DBeaver. It is already fixed in a new version. 
https://dbeaver.io/files/ea/
