### ISSUE TITLE
Navigator Object List limited to 12500 tables?

### ISSUE THREAD

**Issue by lalato** [dbeaver/dbeaver#34678]
### Description

I don't recall seeing this issue before.  But when trying to find a table in the object list that I know exists.... I can write and run queries against the table... the table doesn't show up.

Seems that the list is limited 12500 items.  I've tried changing the object fetch size.  I had originally had it set to 60,000 and bumped it up to 100,000.

There are no filters applied to the object list.

### DBeaver Version

24.1.1.202406231636

### Operating System

macOS Sonoma 14.5

### Database and driver

Snowflake

### Steps to reproduce

1. Connect to DB
2. Expand DB, Schema, Table List
3. Table List only displays first 12500 objects

**Comment by flambchap** [comment]
Hi @lalato. DBeaver shows only 5k objects by default and then suggests loading an additional 5k. As you can see from the screenshot, I loaded more than 12500 here. Can you please tell me if you see a similar navigator node that proposes to load additional tables?

<img width="509" alt="image" src="https://github.com/user-attachments/assets/5320a206-2aa2-4e7c-b7ee-22c5b06ea85a">

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
