### ISSUE TITLE
Autocomplete: suggest procedure/function/package parameters

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#3467]
When you autocomplete a procedure with parameters, it would be great to have pre-filled parameters (like it happens for eclipse with java). For example if I have 

    CREATE PROCEDURE PROC(FOO IN VARCHAR, BAR IN VARCHAR) AS
    --procedure body here
    END

I would like to be able to write PR -> CTRL+space -> select PROC  and get

    PROC(FOO, BAR)

currently I would get

    PROC()

Alternatively (or in addition), there should be a tooltip indicating the list of parameters with their types (Datagrip-like)

**Comment by ceyhunnabiyev** [comment]
Hi @p91paul ,
Seems like this is allmost same  with my issue: #1552.
