### ISSUE TITLE
Drop Down Box and Sub Tables

### ISSUE THREAD

**Issue by matthewandichabod** [dbeaver/dbeaver#34683]
### Description

I have some tables (on Azure SQL) that I would to link via a Primary and Foreign key, both tables have a TicketID (Primary) and SubTicket (Foreign)..

How to I link them like a sub table (like in MS Access)
Is there a way to have a drop down box

### DBeaver Version

CloudBeaver EE (Academic)

### Operating System

Ubuntu Server (CloudBeaver Docker Template - Azure)

### Database and driver

Azure SQL
SQL Server Authentication
Docker Container

**Comment by ShadelessFox** [comment]
Hello @matthewandichabod,

Can you please explain what you mean? Do you have any resources on that feature?

**Comment by matthewandichabod** [comment]
I'm sorry about the late reply, I'm trying to link 2 tables together via primary and foreign keys (like you would in MS Access).

My other question is there a way of linking a table to a Dropbox?

**Comment by serjiokov** [comment]
@matthewandichabod Would be great to share some samples with us for your request.

**Comment by matthewandichabod** [comment]
Ok, I hope this makes sense. I would like to be able to have one ticket to multiple to tickets

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by E1izabeth** [comment]
@matthewandichabod please open the github issue through the web browser https://github.com/dbeaver/dbeaver/issues/34683 and left the comment here. Emails that you receive are notifications. Your replies comes as a comments to the issue, but attachments are not.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
