### ISSUE TITLE
Invalidate database connection after system sleep

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#34689]
When desktop goes to sleep it typical that all database connection hang (for 10-120 seconds, depends on the driver).
This is very annoying especially on MacOS.

We can forcibly r-close all opened connection and reestablish them in background once we detected system sleep.

**Comment by serge-rider** [comment]
![image](https://github.com/user-attachments/assets/64450643-fcbf-445b-907f-c13ab13dfb7d)

**Comment by serge-rider** [comment]
Behavior on MacOS and Windows is a bit different. 
- On Windows all connection will be invalidated after OS awakes from sleep mode and only if sleep took more than 20 seconds.
- On MacOS all connections will be closed once computer goes into sleep mode

**Comment by seatsemmanuel** [comment]
I am not able to turn this setting off. I un-click the 'Close database connections in sleep mode' and hit 'Apply and Close' but it does not change it. I even tried closing and opening the application. I am on Mac OS Sonoma 14.5 with DBeaver Version 24.3.2.202501051917
