### ISSUE TITLE
Unable to edit URL on a Generic driver with Template

### ISSUE THREAD

**Issue by heimankl** [dbeaver/dbeaver#34684]
### Description

I have setup a generic driver to a custom JDBC source. I put in a template for the URL.
When I setup a Connection, the JDBC URL is not editable.
In previous version / use I was able to edit the TEMPLATE URL to add new connections.  I got a new PC and just installed DBeaver and now unable to edit.

<img width="488" alt="DBeaver 2024-07-07 072635" src="https://github.com/dbeaver/dbeaver/assets/40582296/188e26c4-f473-452d-9c71-64a491702f91">

[dbeaver-diagnostic-info-1720354891825.zip](https://github.com/user-attachments/files/16119316/dbeaver-diagnostic-info-1720354891825.zip)
<img width="336" alt="DBeaverGeneric 2024-07-07 072518" src="https://github.com/dbeaver/dbeaver/assets/40582296/37e4d791-7ed0-4d5d-b66e-0a25c6af1ae6">

### DBeaver Version

24.1.1

### Operating System

Windows 10

### Database and driver

Infor Compass 2023.10

### Steps to reproduce

1. setup a new Driver using Generic, enter a URL Template name, add file to JDBC driver. add default connection file detail
2. setup a new database connection using the new driver  .  test connection to default , success. 
4. setup or copy paste a new database connection.  attempt to edit the URL to add a different connection.   Field is uneditable.
https://docs.infor.com/inforos/2024.x/en-us/useradminlib_cloud/default.html?helpcontent=datafabrug/dan1631199548336.html

**Comment by E1izabeth** [comment]
From the first screenshot, I see that both radio buttons Host and URL are unchecked. I suspect this is the reason for this issue - it should not happen.
Please try checking URL radio button.

**Comment by heimankl** [comment]
I was attempting with neither or each and still it is protected.
I have since found that if I set a TEMPLATE in the driver this is protected.  I removed the template from the driver definition, and now I can enter the URL in my connection.
Sounds like a defect, but I am working for now.  Just seems wrong to have a template but not be able to overwrite the template in a connection.

**Comment by E1izabeth** [comment]
Yeah, it looks like a bug. Thank you for report.

**Comment by E1izabeth** [comment]
@heimankl as a workaround you can clear `URL Template` field in driver settings.
