### ISSUE TITLE
Oracle SQL formatter issue (single line comments)

### ISSUE THREAD

**Issue by kiravi** [dbeaver/dbeaver#3468]
1.  See this formatted SQL:
```sql
SELECT
'abc' AS str,
SYSDATE AS dt,
 1 AS qty,
 2 AS another_qty
FROM
  dual;
```
2. Now when the first 2 lines are commented:
```sql
SELECT
  --'abc' AS str,
 --SYSDATE AS dt,
 1 AS qty,
  2 AS another_qty
FROM
  dual;  
```
 --> issues: 
    a) the second and subsequent uncommented line are always misaligned.
    b) i.e. the formatter does not indent well.

Note: it is not apparent here, but take a look at this in the SQL editor.

3. Look at this initial code:
```sql
SELECT
'abc' AS str,
SYSDATE AS dt,
 1 AS qty,
 2 AS another_qty
FROM
  dual
 WHERE 1=1 
 -- test
 AND 2=2;
```
A comment has been provided in the and statement.  On formatting this becomes:
```sql
SELECT
  'abc' AS str,
  SYSDATE AS dt,
  1 AS qty,
  2 AS another_qty
FROM
  dual
WHERE
  1 = 1 -- test
  AND 2 = 2;
```
Issue:  do not want the single line comment to move to end of previous line.  Want the comment to retain its line number.

**Comment by serge-rider** [comment]
Thanks for report
