### ISSUE TITLE
Clicking on the X does not close tabs

### ISSUE THREAD

**Issue by dsk8311** [dbeaver/dbeaver#34688]
### Description

When clicking on the X (cross) to close a tab nothing happens. Right-click then selecting "Close" from the context menu works as expected

### DBeaver Version

24.1.2.202407071610

### Operating System

Windows 10

### Steps to reproduce

1. Display any tab (editor, result panel, etc)
2. Click on the X to close the tab
3. Nothing happens

**Comment by E1izabeth** [comment]
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

Also any video showing the issue would be helpful. We can't reproduce this issue, for now.

**Comment by E1izabeth** [comment]
Is the DBeaver application window active? Maybe you switched to another app and then tried to click on the Close icon? I could imagine this situation only in this case.

**Comment by dsk8311** [comment]
The issue appeared immediately after the updating to latest version.  
Now it does not seem to happen again, most likely it was caused by Windows or interaction with another application. I will reopen the ticket if I'm able to reproduce.
