### ISSUE TITLE
(xx) Reconnecting for opened tabs doesn't reconnect automatically if database was recreated

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34687]
### Description

I work with database using select queries, then drop database in another application, recreate it and try to execute the same query but the error occurs "SQL Error [08003]: This connection has been closed".
Why reconnection should not be done automatically?
Please check this case.

### DBeaver Version

Community Edition 24.1.3.202407042322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

- execute some select-queries for some database on a few tabs
- drop the database using another application
- create database and all the objects with its data using another application
- go back to the same tab in DBeaver
- execute the last query you executed right before database was deleted

Expected: query executed successfully. Reconnection done automatically (seamlessly).
Actual: 
1. query failed with error: SQL Error [08003]: This connection has been closed. 
2. two notifications with the same text are shown in right bottom corner: Datasoure was invalidated. Live connection count: 2/2.

Disconnect + Connect = fixes the issue but I expect it should work automatically.

**Comment by serjiokov** [comment]
Hi @ask9,
First of all, you should not drop DB if any active session is open, but you can do it with FORCE flag that is specifically designed to terminate all existing sessions, after that you examine that "This connection has been closed".
If you recreate the db schema again you have to open a new session.

**Comment by ask9** [comment]
Yes, I forgot to mention it. I use the flag Force.

> If you recreate the db schema again you have to open a new session.

Yes, of course. It is done in another application without any issues. 
But the next execution of a query in DBeaver sometimes works correctly and reconnects without issues but sometimes it is not.
