### ISSUE TITLE
XML functions not working/implemented - Feature request(?)

### ISSUE THREAD

**Issue by guyfromwy** [dbeaver/dbeaver#3469]
Whenever I attempt to pull anything using XML functions, I get no results with a warning:
  java.lang.NoClassDefFoundError - oracle/xdb/XMLType

I am on DBeaver 5.0.4, Oracle 12 and attempt something simple like:
  SELECT XMLCOMMENT('test')
  FROM DUAL;

This should produce:
 `<!-- test -->` 

Same error when trying to use XMLELEMENT or XMLAGG.

If it is supposed to work, then I'm reporting a bug. Otherwise, I guess I'm submitting a feature request. :)

Thanks

**Comment by serge-rider** [comment]
Duplicate of #171
(you need to add xdb6.jar and xmlparserv2.jar)
