### ISSUE TITLE
Autocomplete generates column name in incorrect case (lowercase) for objects from schemas other than current schema

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34698]
### Description

In certain case, autocomplete generates identifiers in lowercase resulting in a wrong query.

### DBeaver Version

Community Edition 24.1.3.202407042322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

https://github.com/dbeaver/dbeaver/assets/33929221/778d7344-1ccf-4608-919a-b9f07b35fdce

**Comment by E1izabeth** [comment]
Thank you for bug report. It's a bad bug.
