### ISSUE TITLE
GIS viewer "color" property

### ISSUE THREAD

**Issue by dmitrysyrchin** [dbeaver/dbeaver#34692]
**Is your feature request related to a problem? Please describe.**
Sometimes it's hard to quick analyze geo data using GIS viewer in case you try to view various geo data (points, linstrings, polygons, etc.) at the same time. I'd like to be able to manually separate geo data in GIS viewer for convenient work with them.
![2023-12-12 18_52_35-DBeaver GIS viewer - Leaflet](https://github.com/dbeaver/dbeaver/assets/18523818/6e1d52c4-a861-4f23-9036-fa3e8a16e368)

**Describe the solution you'd like**
DBeaver CE version 21.2.3 and older allowed to display geometry objects from same column with various colors by specifying hex code in column named "color".
![2024-07-08 10_05_30-DBeaver 24 1 2 - Script-266 sql](https://github.com/dbeaver/dbeaver/assets/18523818/e441f5fc-1cbd-46b1-91c8-62946bee1a15)
![2023-12-12 18_38_04-DBeaver GIS viewer - Leaflet](https://github.com/dbeaver/dbeaver/assets/18523818/0ced6dbb-2ef1-41ff-a1fd-bbd00b8ad0be)
In bugfix https://github.com/dbeaver/dbeaver/pull/14377 "colorizing" was considered a bug and now all geometies from same column displayed in default blue. "color" column is ignored in DBeaver CE version 21.2.4 and later.

I'd like to bring back the ability to set value for "color" column for colorize geo data as I please.

**Describe alternatives you've considered**
I can separate geo data in different columns to get different colors, but it's too inconvinient to work with many various geo data and I can't choose color that's I need.
![2024-07-08 10_50_03-DBeaver 24 1 2 - Script-266 sql](https://github.com/dbeaver/dbeaver/assets/18523818/e0afddf9-fc80-4107-b54c-26afaef57712)
![2024-07-08 10_49_31-DBeaver 24 1 2 - Script-266 sql](https://github.com/dbeaver/dbeaver/assets/18523818/2b925a54-29fa-441f-8e9a-23038b3558d2)

**Additional context**
Related discussion: https://github.com/orgs/dbeaver/discussions/22157

**Comment by E1izabeth** [comment]
Thank you for request.
