### ISSUE TITLE
The Transaction log doesn't contain all queries

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#3470]
I inserted a record in a table using UI in manual commit mode.
Query counter shows 1, but nothing in the transaction log.

![default](https://user-images.githubusercontent.com/16996529/40040624-54a36f98-585e-11e8-9b21-da4e35e51d96.png)

**Comment by serge-rider** [comment]
Do you use CE or EE version?

**Comment by serge-rider** [comment]
Note: I've been able to reproduce this only in Early Access EE version

**Comment by offstate** [comment]
I use CE xubuntu postgresql

**Comment by serge-rider** [comment]
Please try EA (https://dbeaver.io/files/ea/)

**Comment by offstate** [comment]
Now it shows all queries (even SELECTs). 
Thank you

![default](https://user-images.githubusercontent.com/16996529/40335321-6145895a-5da6-11e8-82db-b6c79cee43f2.png)

One note: when you edit a table structure, the transaction is committed after clicking the Persist button. I expect it stay uncommitted

**Comment by serge-rider** [comment]
If you edit structure directly from database navigator then yes - transaction will be committed. That's quite typical for UI clients. 
Otherwise table structure may become inconsistent with UI and the data (which can be read using another connection). This confuses people a lot.
