### ISSUE TITLE
Super wide Export data window

### ISSUE THREAD

**Issue by pyrokineis** [dbeaver/dbeaver#34705]
### Description

After clicking on the "Export Data" button, if the query length is small, the window opens as usual
![image](https://github.com/dbeaver/dbeaver/assets/63732622/f91416e9-3dd6-4dc8-9468-8cf64b28e0e3)
![Pasted Graphic](https://github.com/dbeaver/dbeaver/assets/63732622/d5a2ccee-b51f-434e-b19b-f635a17b00f4)

But if the query is long, the window opens very wide
<img width="1728" alt="Снимок экрана 2024-07-08 в 19 24 31" src="https://github.com/dbeaver/dbeaver/assets/63732622/5c1b17b5-ce2d-4d4a-b28c-c436c9189443">

You have to scroll several times to get to the right edge of the window
The window does not respond well to resizing and glitches
The longer the query, the wider the window 

### DBeaver Version

Community Edition 24.1.2.202407071610

### Operating System

macOS Sonoma 14.5

### Database and driver

1. PostgreSQL 14.11 
2. PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

1. Connect to database 
2. Execute query 
3. Click 'Export data' button under query result table

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by emacsist** [comment]
Why was this issue closed? On macOS, this is still the case in version 25.2.1.

**Comment by amun83** [comment]
I've just upgraded from 23.1.1 to 25.2.3, and get this issue. It's not a big problem, but a bit annoying..
