### ISSUE TITLE
Additional lines are shown in a tooltip in mouse hover over column name with comment containing new lines

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34707]
### Description

Additional lines are shown in a tooltip in mouse hover over column name with comment containing new lines

### DBeaver Version

Community Edition 24.1.3.202407042322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

1. use code 
```

create table t1 (x int);

comment on column t1.x is 'State:
N - new,
P - processed,
E - error';


select * from t1

```

2. mouse hover on column name

![0000002716](https://github.com/dbeaver/dbeaver/assets/33929221/35f2d004-8504-4efb-9f13-9a6f2522324e)

**Comment by ShadelessFox** [comment]
Thanks for the report
