### ISSUE TITLE
It's possible to make a ssl connection to mariadb without client certificates ?

### ISSUE THREAD

**Issue by xagaba** [dbeaver/dbeaver#3471]
I have a mariadb cluster that i can access remotely with command line mysql with --ssl parameter.
With DBeaver i get a:
'Could not connect to server:3306: sun.security.validator.ValidatorException: No trusted certificate found'
I have only checked 'Use SSL' and 'Require SSL' in SSL Connection tab.
The server has a snake-oil self-made certificate.
Any advice ?

**Comment by serge-rider** [comment]
Looks like this is impossible: https://mariadb.com/kb/en/library/using-tlsssl-with-mariadb-connectorj/#handling-self-signed-certificates
You need to put self-signed cert in the local keystore.
