### ISSUE TITLE
Avoid blinking and make more notable a hint of the location where the tab will be moved to (when drag & drop a tab)

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34716]
Avoid blinking and make more notable a hint of the location where the tab will be moved to (when drag & drop a tab)
1. now it is a barely noticeable vertical line of a gray color and it is unclear where the tab will be moved to
2. the vertical line is blinking. It is better to avoid any blinking in applications due to additional eyes strain

https://github.com/dbeaver/dbeaver/assets/33929221/3db66e1e-c7d5-4504-a6ee-abfceba38527

Here is an example how to make it more noticeable (vertical line is also ok but the color should be more intense): #34715

**Comment by serjiokov** [comment]
@ask9 This is an original Eclipse behavior that can not be fixed on the side.

**Comment by serjiokov** [comment]
Please open an issue for the Eclipse platform here: https://github.com/eclipse-platform#reporting-issues
