### ISSUE TITLE
Boundaries of the query are detected incorrectly if a query contains blank line and the query followed by ; (with option: Blank line statement delimiter = Smart)

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34731]
### Description

Boundaries of the query are detected incorrectly if a query contains blank line and the query followed by ; (with option: Blank line statement delimiter = Smart).

### DBeaver Version

Community Edition 24.1.3.202407042322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

- set option: Blank line is statement delimiter = Smart
- use this code:
```
select * 
from (values(random())
        
    ) as s(v)
where s.v is not null;
```
- set caret at where-clause
- execute the query with Ctrl + Enter

![0000002754](https://github.com/dbeaver/dbeaver/assets/33929221/6d61e93a-eb67-43a0-a61d-ecab6b8304db)

### Additional context

Notice that it works correctly without symbol ; somehow so it is possible to detect boundaries in spite of an empty line in between a query text

**Comment by E1izabeth** [comment]
Thank you for bug report.
