### ISSUE TITLE
Postgre functions auto-completion Dbeaver

### ISSUE THREAD

**Issue by ArieStern** [dbeaver/dbeaver#3473]

**Comment by serge-rider** [comment]
Check this in 5.1

**Comment by ArieStern** [comment]
Thanks

________________________________
מאת: Serge Rider <notifications@github.com>
‏‏נשלח: יום ראשון 03 יוני 2018 19:57:25
‏‏אל: dbeaver/dbeaver
עותק: ArieStern; Author
‏‏נושא: Re: [dbeaver/dbeaver] Postgre functions auto-completion Dbeaver (#3473)


Closed #3473<https://github.com/dbeaver/dbeaver/issues/3473>.
