### ISSUE TITLE
Dbeaver Crashing M1 Mac

### ISSUE THREAD

**Issue by IS-Josh** [dbeaver/dbeaver#34733]
### Description

Dbeaver has become very unstable over the last few releases and seems to be getting worse

I'm using a M1 Mac, and I can't go a day wihtout it crashign at least 5-10 Times.  My team experiences the same issues. We connect to a postgres database.  Happy to provide further details if it helps locate the cause.

### DBeaver Version

CE Version 24.1.2.202407071610

### Operating System

MacOS Sonoma 14.5 (23F79)

### Database and driver

Postgresql JDBE Driver 42.7.2. Connecting to GCP AlloyDB or GCP CloudSQL

### Steps to reproduce

Connect to database, work in the editor, crash

### Additional context

Our database contains multiple schemas.  We also have many partitions per table.

**Comment by ShadelessFox** [comment]
Hello @IS-Josh,

What do you mean by "crashing"? Is the application itself closed as a result of a crash?

Can you please provide log files, as described here? https://github.com/dbeaver/dbeaver/wiki/Log-files#java-fatal-logs

**Comment by danijelrudman** [comment]
I have the same issue, it crashes every 5 minutes (application closes), it is unusable at this point.
Also M1 Mac
I thought at first it may be because of low available memory so I made sure there is enough, but it didn't help.

**Comment by E1izabeth** [comment]
@danijelrudman
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.
Especially Java fatal logs https://github.com/dbeaver/dbeaver/wiki/Log-files#java-fatal-logs

**Comment by danijelrudman** [comment]
[errorLog.txt](https://github.com/user-attachments/files/16176390/errorLog.txt)

Here is the error log that is shown once I reopen DBeaver after it crashes. I didn't find any log files when I followed the instructions

**Comment by E1izabeth** [comment]
Thank you

**Comment by ShadelessFox** [comment]
@IS-Josh @danijelrudman do you have any clues what might cause the issue? Is DBeaver idling before the crash?

**Comment by danijelrudman** [comment]
> @IS-Josh @danijelrudman do you have any clues what might cause the issue? Is DBeaver idling before the crash?

When it crashes it is always when I tried to execute a query. Not to say that every execution crashes it, but when it crashes it is when I was executing one or more queries at once

**Comment by E1izabeth** [comment]
How do you execute queries? Which button or the shortcut do you use?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/e3908e47-480a-4060-bd55-ce0db781d0c4)

**Comment by danijelrudman** [comment]
I use either Ctrl+Enter or the execute button in the UI

**Comment by IS-Josh** [comment]
i'll take a look at your instructions tomorrow, im not sure  whats causing the crashes but the app exits completly.  our metadata queries can be slow possibly due to many partitions per table in  our database.  The query pgadmin uses seems to be more efficient however This normally causes freezing when retrieving results and displaying them in the editor rather than a full crash.

we have quite a few json b columns or array's of json in many queries we run. These display normally most times so i wonder if the documents are sometimes to large or too much data is being retuned? 

The crash's often occur when i have a few editors open. the query to be run is highlighted and  executed.

crashes also seem more common when i have connections to more than one database.

**Comment by E1izabeth** [comment]
As a workaround, you can try turning on the following setting `Connection configuration->Metadata->Do not read tables information in SQL and data editors`

![image](https://github.com/user-attachments/assets/990bd416-6960-43f8-b17a-13470928d140)

**Comment by E1izabeth** [comment]
We made some changes that are supposed to solve the issue. Could you try DBeaver 24.1.4 version to check?

**Comment by ashafaei** [comment]
Dbeaver was working for me all fine until today. It has started crashing as soon as I open some tables, and as I scroll down other tables. It seems like an issue with Swift on Mac -- may be a JVM specific issue. I just find it odd that it started happening today, while nothing has changed as far as I know.

```
Thread 1 Crashed::  Dispatch queue: CA DispatchGroup
0   libswiftCore.dylib            	       0x1949c2c8c _assertionFailure(_:_:flags:) + 188
1   libswiftCore.dylib            	       0x194b2f610 KEY_TYPE_OF_DICTIONARY_VIOLATES_HASHABLE_REQUIREMENTS(_:) + 3420
2   AppKit                        	       0x1889fb22c 0x1885ea000 + 4264492
3   AppKit                        	       0x1889f8f08 0x1885ea000 + 4255496
4   AppKit                        	       0x1889f90d0 0x1885ea000 + 4255952
5   AppKit                        	       0x1889db800 0x1885ea000 + 4134912
6   AppKit                        	       0x1889db4d4 0x1885ea000 + 4134100
7   AppKit                        	       0x1889dbaf0 0x1885ea000 + 4135664
8   QuartzCore                    	       0x18d000a38 display_callback(void*, void*) + 100
9   QuartzCore                    	       0x18d0009b4 CA::DispatchGroup::dispatch(bool) + 172
10  libdispatch.dylib             	       0x184b363e8 _dispatch_client_callout + 20
11  libdispatch.dylib             	       0x184b3da14 _dispatch_lane_serial_drain + 748
12  libdispatch.dylib             	       0x184b3e544 _dispatch_lane_invoke + 380
13  libdispatch.dylib             	       0x184b492d0 _dispatch_root_queue_drain_deferred_wlh + 288
14  libdispatch.dylib             	       0x184b48b44 _dispatch_workloop_worker_thread + 404
15  libsystem_pthread.dylib       	       0x184ce300c _pthread_wqthread + 288
16  libsystem_pthread.dylib       	       0x184ce1d28 start_wqthread + 8
```

**Comment by ashafaei** [comment]
I think my problem had to do with the external display, it's almost definitely because of JVM and MacOS integration. Not sure what triggered it. My normal setup is one external display and mac lid closed. Everything works fine. When I sit at the other desk, I get one external display and mac display to work together, and that seems to break something when using DBeaver. I don't use any other Java application to know whether it's a generic problem with JVM, or something specific about DBeaver that triggers this bug.

**Comment by Matvey16** [comment]
@ashafaei That may be another issue. Can you please create another issue with your system information

**Comment by scene-sarias** [comment]
Just happened to me:

```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	       0x1ae8325f8 _assertionFailure(_:_:flags:) + 140
1   libswiftCore.dylib            	       0x1ae99e0c4 KEY_TYPE_OF_DICTIONARY_VIOLATES_HASHABLE_REQUIREMENTS(_:) + 2912
2   AppKit                        	       0x1a154a744 0x1a10e3000 + 4618052
3   AppKit                        	       0x1a154904c 0x1a10e3000 + 4612172
4   AppKit                        	       0x1a15d5ffc 0x1a10e3000 + 5189628
5   AppKit                        	       0x1a15d6a70 0x1a10e3000 + 5192304
6   AppKit                        	       0x1a149e8c8 0x1a10e3000 + 3913928
7   AppKit                        	       0x1a15d6350 0x1a10e3000 + 5190480
8   QuartzCore                    	       0x1a625f0b4 CA::Layer::display_if_needed(CA::Transaction*) + 748
9   QuartzCore                    	       0x1a63f3464 CA::Context::commit_transaction(CA::Transaction*, double, double*) + 492
10  QuartzCore                    	       0x1a62403a8 CA::Transaction::commit() + 644
11  AppKit                        	       0x1a123fedc __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 272
12  AppKit                        	       0x1a1c87b04 ___NSRunLoopObserverCreateWithHandler_block_invoke + 64
13  CoreFoundation                	       0x19d4cc1a8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
14  CoreFoundation                	       0x19d4cc090 __CFRunLoopDoObservers + 536
15  CoreFoundation                	       0x19d4cb700 __CFRunLoopRun + 784
16  CoreFoundation                	       0x19d4cad68 CFRunLoopRunSpecific + 572
17  HIToolbox                     	       0x1a8c7b27c RunCurrentEventLoopInMode + 324
18  HIToolbox                     	       0x1a8c7e31c ReceiveNextEventCommon + 216
19  HIToolbox                     	       0x1a8e09484 _BlockUntilNextEventMatchingListInModeWithFilter + 76
20  AppKit                        	       0x1a111dab4 _DPSNextEvent + 684
21  AppKit                        	       0x1a1abacd4 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
22  libswt-pi-cocoa-4967r8.jnilib 	       0x1102376c4 Java_org_eclipse_swt_internal_cocoa_OS_objc_1msgSendSuper__Lorg_eclipse_swt_internal_cocoa_objc_1super_2JJJJZ + 172
23  ???                           	       0x137e17a04 ???
24  ???                           	       0x138149988 ???
```
