### ISSUE TITLE
Alt + X and Ctrl + Enter show errors in a different way

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34737]
### Description

Alt + X shows error message in a new window but Ctrl + Enter shows error in a result tab
Is it by design (feature)?
Why?
Isn't it better to show consistently: always show errors in a Results tab, in spite of which hotkey the query was executed with? 

On the separate window user has no some features: buttons "Details", "Error log", "Go to the error" and a panel with context of a query.

### DBeaver Version

Community Edition 24.1.3.202407042322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

**Comment by serjiokov** [comment]
@ask9 It is our design way 
the ALT+X allows invoking Retry and Stop script execution;
the Ctrl+Enter allows executing one single query
