### ISSUE TITLE
Rearrange buttons so that they take less space and more space will be available for a precious error message

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34732]
I suggest to rearrange buttons in error message so that they took less space and more space will be available for a precious error message.
It is especially useful for long error messages and when user divide a screen on two parts what leads to lack of free space in each part of the window.

"As is" and "to be":

![изображение](https://github.com/dbeaver/dbeaver/assets/33929221/fd306b06-8fcf-4cf5-be8f-681c289cfe36)

**Comment by E1izabeth** [comment]
Thank you for request.

Another request about ui of this view #34726

**Comment by E1izabeth** [comment]
We moved these buttons to the bottom
<img width="542" alt="356183131-230fa75c-1a9c-47d5-b32d-375403800d16" src="https://github.com/user-attachments/assets/1ffc3488-8c56-4104-ba39-97e787ba05f6">

Will be available in 24.1.5

**Comment by ask9** [comment]
Excellent!
