### ISSUE TITLE
Some reserved keywords of sql language use wrong color

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34741]
### Description

use this code (it has no error but it is colored with "SQL semantic error foreground"):
`SELECT CURRENT_DATE;`

### DBeaver Version

Community Edition 24.1.3.202407042322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by ask9** [comment]
This issue is very similar to: #34751

**Comment by theresa-de-ocampo** [comment]
Same goes for:

- `INTERVAL`
   ```sql
    SELECT NOW() - INTERVAL '10 minutes';
    ```

- `jsonb_array_elements` aliases, e.g., `grade` is incorrectly colored as red.

    ```sql
    SELECT
      *
    FROM
      jsonb_array_elements('[77, 85, 92, 95, 74, 79, 80, 97]') AS grade
    WHERE
      CAST(grade AS INTEGER) > 85;
    ```

**Comment by E1izabeth** [comment]
@theresa-de-ocampo thank you. I created separate issues for that #35464 #35465

**Comment by montovaneli** [comment]
Same goes for `current_timestamp`
![image](https://github.com/user-attachments/assets/e7982baf-4c01-4b88-93f0-37fdbeb5e970)

@E1izabeth
