### ISSUE TITLE
Internal query executed on Vertica by DBeaver making queries slow (5.0.5)

### ISSUE THREAD

**Issue by mukundbajaj** [dbeaver/dbeaver#3474]
Hi,

Just noticed an issue with the version 5.0.5.

Whenever a new session is established on Vertica through DBeaver, the first query executed is very slow, and DBeaver fires the following query internally:

**SELECT p.*,c.comment FROM v_catalog.projections p LEFT OUTER JOIN v_catalog.comments c ON c.object_type = 'PROJECTION' AND c.object_schema = p.projection_schema AND c.object_name = p.projection_name WHERE p.projection_schema='public'**

Is this somewhat related to auto-complete? 

Regards,
Mukund

**Comment by serge-rider** [comment]
This query reads projection list. Basically it should be read only if you expand "Projections" folder.
I'll remove projections from child nodes of schema (not sure why they appeared there in the first place).

Thanks for report.

**Comment by mukundbajaj** [comment]
Thanks for the quick resolution and response!
