### ISSUE TITLE
Highlight problem for some cases in Oracle SQL

### ISSUE THREAD

**Issue by Yigitttttttt** [dbeaver/dbeaver#34751]
### Description

Some codes appear red even though there are no errors.
![Adsız](https://github.com/dbeaver/dbeaver/assets/168306503/05fa163d-1138-450f-af10-3d2201f27209)

### DBeaver Version

24.1.2

### Operating System

windows 11

### Database and driver

infos given at picture

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by Yigitttttttt** [comment]
Hi I use 24.2.2 and now it's ok :)
