### ISSUE TITLE
Problem with encoding in Value window

### ISSUE THREAD

**Issue by breakmt** [dbeaver/dbeaver#3475]
PostgreSQL. In field "bytea" we have XML. In there we have some fields written in Russian.
If I open it in "Value" window there are problems in encoding, so I can't see all Russian text.
If I "Save it" to file and open in Notepad++ than I can see text without problems.

Screenshot: https://cloud.mail.ru/public/Eoyc/zdns6am8Z

**Comment by serge-rider** [comment]
I think we need encoding selector for binary fields.

Workaround: you can open value in a separate editor (shift+enter -> open in editor). And then change text encoding in main toolbar.
