### ISSUE TITLE
I downloaded the Phoenix related jar error ?

### ISSUE THREAD

**Issue by a854363956** [dbeaver/dbeaver#3476]
Here's the wrong message 
![tim 20180516161451](https://user-images.githubusercontent.com/16779224/40105115-9ee05082-5924-11e8-92d3-8bfeecc963e8.png)

**Comment by serge-rider** [comment]
Looks like a bug in Maven artifacts resolution.

**Comment by serge-rider** [comment]
I've fixed this particular issue with Maven resolution. However new Phoenix driver is still doesn't work out of the box - it has HBase explicit dependencies. We need to patch driver configuration.

At the moment easiest way to resolve this is to download Phoenix  full distribution (e.,g. from here http://apache-mirror.rbc.ru/pub/apache/phoenix/apache-phoenix-4.13.2-cdh5.11.2/bin/) and then add jar `phoenix-XXX-HBase-ZZZ-client.jar` in DBeaver driver properties.

**Comment by a854363956** [comment]
@serge-rider  thank you very much !
