### ISSUE TITLE
Only able to connect to Oracle DB on DBeaver v23

### ISSUE THREAD

**Issue by rnyagwaya** [dbeaver/dbeaver#34768]
### Description

I am only able to connect to Oracle DB on version 23.0 and below. 
<img width="401" alt="image" src="https://github.com/dbeaver/dbeaver/assets/175286417/b2c3616c-71e9-4566-a6f3-5067e43f413d">

Since that update, connecting to the DB has ben failing with the below error
<img width="789" alt="image" src="https://github.com/dbeaver/dbeaver/assets/175286417/b780d089-9d9b-46e9-ab3b-7f7e3b6f44f9">

### DBeaver Version

Community Edition Version 23.0.0.202303040621

### Operating System

Mac Sonoma 14.5

### Database and driver

Oracle Version 
Oracle driver version 12.2.0.1

### Steps to reproduce

When i upgarade to any version after version 23.0.0
and try to connect to my oracle DB
i am requested to update my driversOn completion i get the below error
<img width="789" alt="image" src="https://github.com/dbeaver/dbeaver/assets/175286417/94d1a704-8ba5-4886-8d98-22b6c5f7b266">

**Comment by ShadelessFox** [comment]
Hello @rnyagwaya,

What's your database version and the driver version? What authentication method do you use?

**Comment by rnyagwaya** [comment]
Good day, thanks for writing to check on my issue

The DB Version is Oracle 12c
I think those are the drivers

[image: image.png]

**Comment by ShadelessFox** [comment]
Unfortunately, you can't attach images when replying by email. Please attach them directly on GitHub.

**Comment by rnyagwaya** [comment]
Driver - Oracle
Library - com.oracle.database.jdbc:ojdbc8:RELEASE
path - maven:/com.oracle.database.jdbc:ojdbc8:RELEASE
Version - 12.2.0.1

Libraries
com.oracle.database.jdbc:ojdbc8:RELEASE [12.2.0.1]
com.oracle.database.nls:orai18n:RELEASE [23.2.0.0]
com.oracle.database.xml:xdb6:RELEASE [18.3.0.0]
com.oracle.database.xml:xmlparserv2:RELEASE [23.2.0.0]

rnyagwaya

**Comment by ShadelessFox** [comment]
Thanks for the information.

**Comment by TB-HunBoka** [comment]
ojdbc8 only supports JDK 8-11. Can it be that after dbeaver upgraded to JDK 17 it causes conflict?
@ShadelessFox I could not find a way to upgrade the ojdbc version from 8 to 11 in the driver manager, is it possible?

My Version 24.1.2.202407071610 community edition has the correct ojdbc 11 in the oracle driver.

**Comment by ShadelessFox** [comment]
@TB-HunBoka I don't think so.

You can manually add new artifacts. Go to **Libraries -> Add Artifact** and paste the following code block there:
```
com.oracle.database.jdbc:ojdbc11:23.2.0.0
com.oracle.database.nls:orai18n:23.2.0.0
com.oracle.database.xml:xdb6:18.3.0.0
com.oracle.database.xml:xmlparserv2:23.2.0.0
```

By the way, the driver was updated to `23.2.0.0`  in DBeaver 23.3.1 (https://github.com/dbeaver/dbeaver/issues/19299).

**Comment by ShadelessFox** [comment]
Alternatively, as a workaround, driver files can be downgraded to versions prior the update:
```
com.oracle.database.jdbc:ojdbc8:12.2.0.1
com.oracle.database.nls:orai18n:12.2.0.1
com.oracle.database.xml:xdb6:12.2.0.1
com.oracle.database.xml:xmlparserv2:12.2.0.1
```

**Comment by WumvanPauwe** [comment]
Hi all, using an Oracle 23 driver (ojdbc11.jar) on a Oracle 19 database disables Native Oracle Encryption. Highest version should be Oracle 21. When using Oracle 19 driver (ojdbc10.jar) encryption works fine.
Is there a piece of documentation to instruct users how to select the correct driver version?

**Comment by WumvanPauwe** [comment]
Seems to work with the following settings:
<img width="859" alt="image" src="https://github.com/user-attachments/assets/0c83a49d-4343-4991-b824-bd8cee5b8baf">

**Comment by ShadelessFox** [comment]
Hello @rnyagwaya,

Sorry for a long wait. Can you please confirm that the proposed solution works for you? https://github.com/dbeaver/dbeaver/issues/34768#issuecomment-2230870654

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.

**Comment by rnyagwaya** [comment]
Apologies,

I have not had a chance to test the solution you provided as I was
travelling. I am still on version 23 at the moment and will try and give
feedback as soon as possible as issue is closed
