### ISSUE TITLE
There is a problem with the details of the UI

### ISSUE THREAD

**Issue by BraveMomo** [dbeaver/dbeaver#34766]
**Is your feature request related to a problem? Please describe.**
The minimization button in the upper right corner of the window inside the software is not centered, but the other icons are centered, which makes OCD very uncomfortable
![企业微信截图_17206654647344](https://github.com/dbeaver/dbeaver/assets/22335503/4e006582-4ede-4828-8ff2-14e74b9ff8c0)

**Describe the solution you'd like**
Please center these icons
**Describe alternatives you've considered**

**Additional context**

**Comment by Destrolaric** [comment]
It looks like our framework platform, Eclipse, is suffering from the exact same issue. I'm not sure how we can fix it from our side.
![image](https://github.com/dbeaver/dbeaver/assets/20579256/a8d05657-2a2a-4d24-b4f6-37fda8489f4d)

**Comment by serjiokov** [comment]
Please open an issue for the Eclipse platform here: https://github.com/eclipse-platform#reporting-issues
it can not be fixed on our side.
