### ISSUE TITLE
Can't install DuckDB nightly build

### ISSUE THREAD

**Issue by ericemc3** [dbeaver/dbeaver#34773]
### Description

I'd like to benefit from DuckDB last functionalities but can't manage to install nightly build from https://artifacts.duckdb.org/latest/java-jars.zip

### DBeaver Version

Community Edition 24.1.2

### Operating System

Win 11

### Database and driver

DuckDB and nightly driver from https://artifacts.duckdb.org/latest/java-jars.zip (curently 1.0.1-dev)

### Steps to reproduce

1 - disconnect the database
2 - add new driver in the driver editor
![image](https://github.com/dbeaver/dbeaver/assets/17407796/429a204f-54a4-45d7-a0f6-834ce7bd3394)
3 - connect the database
4 - PRAGMA VERSION -> still 1.0, and not 1.0.1 dev as expected

**Comment by ShadelessFox** [comment]
Hello @ericemc3,

Try removing the Maven artifact:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/6a6cf12f-957c-4a81-9910-f9960d07c806)

If it still shows as 1.0, then it seems that DuckDB devs forgot to update its version.

**Comment by ericemc3** [comment]
Thanks for your reply,
i tried
![image](https://github.com/dbeaver/dbeaver/assets/17407796/eb7072a2-78d0-4795-bee1-a77c850cdede)
but then i get a fallback to an old version:
![image](https://github.com/dbeaver/dbeaver/assets/17407796/e7723a8d-9af4-43da-bd5f-bb1aed1870ea)

**Comment by ShadelessFox** [comment]
This is what I get as well. It indeed seems like the issue is on the DuckDB team's side.

**Comment by ericemc3** [comment]
Thanks a lot, i told DuckDB teeam's.
