### ISSUE TITLE
Salesforce Data Cloud Connector

### ISSUE THREAD

**Issue by isoctcolo** [dbeaver/dbeaver#34778]
### Description

I had this connector before but it disappeared.

### DBeaver Version

Cummunity Edition 24.1.2.202407071610

### Operating System

Macos 14.5 M1

**Comment by LonwoLonwo** [comment]
Hello @isoctcolo 

Maybe this advice will help you? https://github.com/dbeaver/dbeaver/issues/34765#issuecomment-2222823175
