### ISSUE TITLE
Bug: PostgreSQL call functions v.5.0.5

### ISSUE THREAD

**Issue by AShynkevich** [dbeaver/dbeaver#3477]
I updated to dbeaver  v. 5.0.5 
Now I can't perform request such as:
`select uuid_generate_v1();`
I always get the error:
`
SQL Error [42883]: ERROR: function uuid_generate_v1() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
  SQL Error [42883]: ERROR: function uuid_generate_v1() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
    SQL Error [42883]: ERROR: function uuid_generate_v1() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
      SQL Error [42883]: ERROR: function uuid_generate_v1() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
        ERROR: function uuid_generate_v1() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
        ERROR: function uuid_generate_v1() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
`

If I perform the same request for the DB via PgAdmin - it works properly.
P.S. [necessary extensions were enabled, and it worked for previous version of DBeaver]

**Comment by serge-rider** [comment]
Function `uuid_generate_v1` is part of `uuid-ossp` extension. In PostgreSQL you install extensions for a particular schema. This schema must be in search_path (or be a current schema) otherwise you will get that error.

Just change your active schema or update search_path or install uuid-ossp in your current schema by running `create extension "uuid-ossp"`

**Comment by serge-rider** [comment]
However. Recently we've changed the way how search_path is updated if you change active schema in DBeaver. Now `$user` is replaced with actual current session user name. Maybe it is reason why your extension is not accessible.

I'll keep $user as is. Please test it in EA version (https://dbeaver.io/files/ea/)

**Comment by AShynkevich** [comment]
Thank you! Let me check it and I will respond you.

**Comment by AShynkevich** [comment]
>I'll keep $user as is. Please test it in EA version (https://dbeaver.io/files/ea/)

Great! Now, It works for this version.

**Comment by serge-rider** [comment]
👍
