### ISSUE TITLE
Salesforce Data Cloud connector 

### ISSUE THREAD

**Issue by isoctcolo** [dbeaver/dbeaver#34781]
### Description

The data Cloud connector is not working as expected - I followed the tutorial here 
https://help.salesforce.com/s/articleView?id=sf.c360_a_set_up_dbeaver_connected_app.htm&type=5

I added the clientId and ClientSecret in the driver properties - added the user and passwort and it gives me authentication failure. Which is not correct I tested extra the login details and they work.

### DBeaver Version

Cummunity Edition 24.1.2.202407071610

### Operating System

Macos 14.5 M1

### Database and driver

Salesforce Data Cloud, CDP driver https://github.com/forcedotcom/Salesforce-CDP-jdbc/releases/tag/v1.19.7

The latest driver wa not automatically downloaded

**Comment by isoctcolo** [comment]
<img width="947" alt="Screenshot 2024-07-11 at 16 03 07" src="https://github.com/dbeaver/dbeaver/assets/102313029/b7220c6d-664a-41f2-b7af-b8ee8e82b829">

Driver properties

**Comment by E1izabeth** [comment]
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by E1izabeth** [comment]
Also could you tell me your server version? You can get this information by clicking `Test connection...` button in the `Connection configuration` dialog.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/4df54f5a-44e0-4185-afd4-1cd78e13c929)

**Comment by isoctcolo** [comment]
<img width="865" alt="Screenshot 2024-07-11 at 17 03 10" src="https://github.com/dbeaver/dbeaver/assets/102313029/85e4e810-b620-4822-9b0e-e91a9be4870b">
The test connection does not give my any of those - just user authentication failure

**Comment by isoctcolo** [comment]
[debug.tgz](https://github.com/user-attachments/files/16179764/debug.tgz)
I didn't have a .log only a debug log file - this is attached.

**Comment by E1izabeth** [comment]
Thank you.

**Comment by isoctcolo** [comment]
Just as a note you have to add dataspace property from your dataspace and also change from login.salesforce.com to your domain then it is working. No bug on Dbeaver side

**Comment by E1izabeth** [comment]
Thank you for update!
