### ISSUE TITLE
setting a database as default not works in sql editor

### ISSUE THREAD

**Issue by Inasayang** [dbeaver/dbeaver#34789]
### Description

After setting a database as default, `create table ...` in a SQL editor will not use this database.

### DBeaver Version

Community Edition 24.1.2

### Operating System

Windows 11

**Comment by E1izabeth** [comment]
How exactly do you set the database as default?

**Comment by Inasayang** [comment]
1. right-click a database
2. `set as default`
3. `SQL Editor`
4. `create table...`

**Comment by E1izabeth** [comment]
Does the active database change here for you after this action?
![image](https://github.com/user-attachments/assets/f2747d89-15b9-4877-b599-96265c31a6d3)

**Comment by Inasayang** [comment]
Works in the new script editor. Not in old/recent script editor.

**Comment by Inasayang** [comment]
I know how to use it. Thx.
