### ISSUE TITLE
New autocomplete engine doesn't enquote identifiers with double quotes if identifier has upper case symbols

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34799]
### Description

https://github.com/user-attachments/assets/0c7eb6f6-9c56-49f6-a4b5-6441e8c0fa6b

### DBeaver Version

Community Edition 24.1.3.202407042322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

1. Choose in Preferences "New completion engine"
2. Use code:
```

create table "HelloWorld" ( "World" int );

select * from 

```

### Additional context

Please also check all other kinds of identifiers (column names, etc...).

**Comment by E1izabeth** [comment]
Please try early access version https://dbeaver.io/files/ea/
We just merged some changes yesterday and I can't reproduce the issue anymore.

**Comment by ask9** [comment]
Thanks. I confirm that it is fixed now.
