### ISSUE TITLE
New autocompletion replaces words that it is not supposed to

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#34797]
### Description

I don't know all the cases, but in some the proposed word would be added while deleting words that come before it. In my case it happened with `AND` keyword. THis also happens regardless if the property to replace initial word is checked or not.

### DBeaver Version

24.1.3

### Operating System

Any

### Database and driver

PostgreSQL

### Steps to reproduce

1. Start typing a query with a `where` clause
2. Type a condition and then type `and`
3. Call autocomplete after a space and select one of the proposals

**Expected:** Text is added after the caret
**Actual:** text is added inside the `and` keyword

### Additional context

https://github.com/user-attachments/assets/413b25d3-b53a-4f57-b0f4-3aba5012e6e6

**Comment by ask9** [comment]
Another case, quite similar to this (I press Ctrl + Space on this video):

https://github.com/user-attachments/assets/c66ae056-f051-41ea-bba4-21e67490ca2f
