### ISSUE TITLE
Bug: create table in a db fails if I change the active database before saving the new table

### ISSUE THREAD

**Issue by sirber** [dbeaver/dbeaver#3479]
create table in a db fails if I change the active database before saving the new table.
the table doesn't get saved and I get no errors.

![screenshot from 2018-05-16 09-53-41](https://user-images.githubusercontent.com/3911428/40121206-0c9daed4-58ef-11e8-9064-58751bdb52b9.png)

**Comment by serge-rider** [comment]
What is your database?

**Comment by uslss** [comment]
Cannot reproduce on 6.0.2
