### ISSUE TITLE
New autocomplete engine doesn't care of user setting upper/lower case for sql keywords

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34801]
### Description

When I choose option "FROM" in a list of suggestions it gives me:
select * FROM
instead:
select * from

### DBeaver Version

Community Edition 24.1.3.202407042322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

**Comment by E1izabeth** [comment]
Thank you for bug report!

**Comment by E1izabeth** [comment]
Please try early access version https://dbeaver.io/files/ea/
We just merged some changes yesterday and I can't reproduce the issue.

**Comment by ask9** [comment]
Yes, I confirm it is also fixed in this version.
