### ISSUE TITLE
dbms_output.put_line doesn't output anything

### ISSUE THREAD

**Issue by imachequa** [dbeaver/dbeaver#34803]
### Description

Previous version used to print things in output tab, not sure which one I have.  Most probably previous to the one I have installed now

### DBeaver Version

Community Edition Version 24.1.2.202407071610

### Operating System

macOS Sonoma / Windows 2016

### Database and driver

Oracle Database 12c 

### Steps to reproduce

1. Open Sql script
2. Paste code for loop deleting
`Declare
var_rows NUMBER(20):=0;

TYPE source_tab IS TABLE OF ROWID;
rec_tab source_tab;
Cursor crs IS
        select rowid from sometable;
Begin
  execute immediate 'alter session enable parallel dml';
  Open crs;
  loop
	  FETCH crs BULK COLLECT
	  INTO rec_tab limit 100000 ;
	  forall i in 1 .. rec_tab.last
	  delete sometable where rowid = rec_tab(i);
	  var_rows := var_rows + SQL%ROWCOUNT;
	  commit;
  	  exit when crs%NOTFOUND;
  End loop;
  Close crs;
  dbms_output.put_line('Records deleted: ' || TO_CHAR(var_rows));
EXCEPTION
  WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('Records deleted: '|| TO_CHAR(var_rows) || ' Error in executing: '||SQLERRM);
End;
`
3. Run
4. Output tab doesn't show anything

**Comment by babychaos** [comment]
Did you run from `Alt + x`? I suffered same problem and realized `Ctrl + Enter` would show the result in `24.1.2` version. I don't know why but it may be intended. I hope there should be an option about it.

**Comment by imachequa** [comment]
> Did you run from `Alt + x`? I suffered same problem and realized `Ctrl + Enter` would show the result in `24.1.2` version. I don't know why but it may be intended. I hope there should be an option about it.

I actually use the button in the GUI.... I honestly don't want to try any more till fixed since for my use case it is very important to know how many records are deleted... and any try I do is resulting in deletions that I have not control over how many they were

**Comment by MashaKorax** [comment]
closed as duplicate https://github.com/dbeaver/dbeaver/issues/34865

**Comment by E1izabeth** [comment]
Thank you for bug report!
