### ISSUE TITLE
New autocomplete engine: Ctrl + Space don't expand a symbol * in select

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34800]
### Description

Nothing happens if a user press Ctrl + Space after symbol * in this select:

```
create table "HelloWorld" ( "World" int );

select * from "HelloWorld"
```

In default engine, it expands to a full list of columns.

### DBeaver Version

Community Edition 24.1.3.202407042322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

### Additional context

Please also check this case for: INSERT INTO table (*)

**Comment by E1izabeth** [comment]
Thank you for bug report!
