### ISSUE TITLE
New autocomplete: sometimes list of columns and table aliases are doubled in suggestion list

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34804]
### Description

Press Ctrl + Space after AND in this query:

```
CREATE TABLE public.prod (
    abc int4 NULL
);

select * from prod p
where p.abc and 
```

https://github.com/user-attachments/assets/5a680098-4440-491d-b5d1-fcd0789c4c44

### DBeaver Version

Community Edition 24.1.3.202407122322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

**Comment by E1izabeth** [comment]
I can't reproduce this issue on DBeaver 24.1.4 anymore. Could you check if it's still actual for you?

**Comment by ask9** [comment]
I reproduced it easily on 24.1.4.202407250946.
I can try to export my settings.
You can apply it on your side and check if it becomes reproducible.
Is it ok?

**Comment by E1izabeth** [comment]
Yes, let's try

**Comment by ask9** [comment]
[dbeaver pref 25_07_2024.zip](https://github.com/user-attachments/files/16383242/dbeaver.pref.25_07_2024.zip)

[preferences dbeaver_25_07_2024 (this is epf-file zipped manually - unzip before importing).zip](https://github.com/user-attachments/files/16383291/preferences.dbeaver_25_07_2024.this.is.epf-file.zipped.manually.-.unzip.before.importing.zip)

**Comment by E1izabeth** [comment]
I was managed to reproduce the issue.
