### ISSUE TITLE
New autocomplete mode doesn't suggest system tables

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34807]
### Description

New autocomplete mode doesn't suggest system tables, for example, pg_class.

Start typing: select * from pg_c
press Ctrl + Enter

Expected: "pg_class" is in a list of suggestions
Actual: No suggestions at all

### DBeaver Version

Community Edition 24.1.3.202407122322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by iraidaa** [comment]
We have the same request from our customers. Ticket number on our internal support system is 387162.
