### ISSUE TITLE
Try to avoid blinking when drag & drop objects (some items somehow don't have it)

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34805]
### Description

When drag & drop "Value" tab - it has no blinking (of course, I understand it is not draggable).
When drag & drop all other (draggable) objects: table names, column names, schema names - the dragged object is blinking.

It only blinks when you drag it over some text.
For example, if you remove all the text in sql editor, it will not blink.
Looks like unneeded repaint happens on each movement of mouse when caret position moves from symbol to symbol to obtain the drop position.
For example, "Value"-tab object is not draggable and there is no need to get position where to put it in a text and therefore there is no blinking.

### DBeaver Version

Community Edition 24.1.3.202407122322

### Operating System

Windows 10

### Steps to reproduce

First I show that there is no blinking (with empty sql editor).
After that I add symbols in sql editor and show that blinking happens.

https://github.com/user-attachments/assets/d1e52253-9fb7-49b3-8741-55c8f0fd6a0a

**Comment by arhayka** [comment]
Thank you for the report. However, it can't be fixed on DBeaver side, this is an Eclipse issue.
