### ISSUE TITLE
Ctrl + Enter doesn't detect boundaries of a query for some sql operators if there is no ; at the end of the previous query (Blank line is statement delimiter = Smart)

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34815]
### Description

Use this code:
```
select * 
from film_actor

SHOW SEARCH_PATH;
```

I expected to execute only the first query, but the application tries to execute both.
Adding symbol ; at the end of the first query fixes the issue.

### DBeaver Version

Community Edition 24.1.3.202407122322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

https://github.com/user-attachments/assets/d07122cf-fa04-4c03-90c0-659c1dd04483

**Comment by TB-HunBoka** [comment]
Did you try changeing the "Blank line is statement delimiter" to always?
![kép](https://github.com/user-attachments/assets/ad9c1c5e-a22f-4de0-9509-dfeea8f96bc8)

**Comment by E1izabeth** [comment]
Thank you for bug report.
