### ISSUE TITLE
Generate SQL context menu not activating

### ISSUE THREAD

**Issue by dsk8311** [dbeaver/dbeaver#34819]
### Description

When opening table detail, right-click on the empty grid space the "Generate SQL" menu item shows up in the context menu does not activate

### DBeaver Version

24.1.2.202407071610

### Operating System

Windows 10

### Database and driver

Firebird v3.0.10, Jaybird JCA/JDBC driver 4.0.0

### Steps to reproduce

https://github.com/user-attachments/assets/d8d5afcf-5bae-4a10-854a-de54984cc282

**Comment by E1izabeth** [comment]
Thank you for bug report.
