### ISSUE TITLE
Bug with CASE WHEN ELSE END in Oracle script #231 (REOPEN)

### ISSUE THREAD

**Issue by aloon9999** [dbeaver/dbeaver#3481]
This issue #231 happen again in latest DBeaver version 5.0.5.

**Comment by serge-rider** [comment]
This bug was a side effect of #3439 fix.
Thanks for report.

**Comment by AlperArikan** [comment]
This issue seems to continue in latest DBeaver version 6.1.5 (I think since 5.2.5)

**Comment by AlperArikan** [comment]
6.2.0 same, when can you fix this again? It really affects our productivity. We have to run queries one by one, even drop/creates.

**Comment by serge-rider** [comment]
@AlperArikan please create new ticket with details (some PL/SQL snippet would be very helpful)
