### ISSUE TITLE
DBaver creates package error in PostgreSQL library

### ISSUE THREAD

**Issue by jzhu2024** [dbeaver/dbeaver#34827]
Why is the syntax error reported when executing the 'create package' statement in pgadmin successful, but when executing it in DBEAVER

**Comment by E1izabeth** [comment]
Please provide, what database do you use, and your query DDL.

**Comment by E1izabeth** [comment]
Also you may try selecting the whole query and pressing Execute button as a workaround

**Comment by jzhu2024** [comment]
DB : POLARDB FOR ORACLE 

> Please provide, what database do you use, and your query DDL.

The database  is PolarDB PostgreSQL for oracle

**Comment by jzhu2024** [comment]
> Also you may try selecting the whole query and pressing Execute button as a workaround

Tried, but it didn't work

**Comment by E1izabeth** [comment]
Please provide the example of query that doesn't work for you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
