### ISSUE TITLE
DBeaver cannot start on ARM

### ISSUE THREAD

**Issue by Anlele1701** [dbeaver/dbeaver#34834]
### Description

I'm currently using a Mac Air M2, I run Ubuntu 22.04 through VMware Fusion
I installed beaver, when I launched it, it doesn't launched.
I tried to launch it from terminal using: dbeaver-ce &
It gave this error
<img width="861" alt="image" src="https://github.com/user-attachments/assets/96bb2af4-135f-4154-8e1e-2ab7a3c7595f">

### DBeaver Version

Community 24.1.2

### Operating System

MacOS 14.5

### Steps to reproduce

1.  I installed beaver
2. I launched dbeaver
3. Nothing happened

**Comment by Destrolaric** [comment]
@Anlele1701 Hi, I understand you are using an ARM-based Mac. DBeaver snap is compiled for x86-64 architecture on Linux, so this might be a reason why you can't launch the client. Unfortunately, I don't have knowledge if there are ways to use x86 apps via the translation layer on Linux; if they are present, they should help.

**Comment by serjiokov** [comment]
@Anlele1701 Generally if you are using ARM-based processor it might be a cause for this issue. 
So far we don't support ARM cores.
