### ISSUE TITLE
Query time

### ISSUE THREAD

**Issue by clemlaugit** [dbeaver/dbeaver#34837]
### Description

After the latest update, when I run a query now on a table I haven't queries on before there is some pop up now "discover XXXX entity" that pops up now which can take minutes to run before the query actually executes.  This is a total blocker...What is this?  

![image](https://github.com/user-attachments/assets/0e8e493e-be0a-4cc5-bbee-5a2cb9e6cb06)

### DBeaver Version

24.1.2.202407071610

### Operating System

Mac Sonoma 14.5

### Database and driver

snowflake jdbc driver

### Steps to reproduce

run a query on a new table

**Comment by E1izabeth** [comment]
@clemlaugit 
Could you do the following actions?
1. Open Query Manager
![image](https://github.com/user-attachments/assets/f505f676-a578-4af2-a786-ba6c1273c17f)

2. Turn on showing of all types of queries 
![image](https://github.com/user-attachments/assets/8065c206-dad8-4457-b597-daeb1c2f0616)

3. Clear log
![image](https://github.com/user-attachments/assets/c7d94ecb-83d9-4684-8862-01ffb182a39e)

3. Reproduce the issue once again

4. Send us the screenshot of Query Manager view

**Comment by E1izabeth** [comment]
As a workaround, you can turn on the following setting `Connection configuration->Metadata->Do not read tables information in SQL and data editors`

![image](https://github.com/user-attachments/assets/990bd416-6960-43f8-b17a-13470928d140)

**Comment by E1izabeth** [comment]
@clemlaugit does proposed workaround help?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
