### ISSUE TITLE
Default autocomplete mode suggests a list of possible values in incorrect order

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34844]
### Description

Here I expect NULL should be the first in the list, not NOTNULL

https://github.com/user-attachments/assets/bb87a2fc-fbf0-415d-88bc-7826f175c223

### DBeaver Version

Community Edition 24.1.3.202407122322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

**Comment by E1izabeth** [comment]
I reproduced the described behavior. However, I'm not sure it's a bug, so I changed the label to enhancement. We haven't implemented any algorithm that sorts proposals from most matched to least matched yet.

**Comment by E1izabeth** [comment]
Should be implemented in #34974
