### ISSUE TITLE
New autocomplete mode sync issue

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34845]
### Description

By the way, in this video I do not call suggestions by Ctrl + Space.
It appears only on Space symbol automatically.

https://github.com/user-attachments/assets/1d75ed2e-fdc8-482c-87f4-85003a600933

Please also check this query on dvdrental database (Ctrl + Space after "on"):

```
select * from actor as a
join film_actor as fa on 
```

### DBeaver Version

Community Edition 24.1.3.202407122322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

**Comment by E1izabeth** [comment]
Yeah, we haven't solved this issue yet. Thank you for bug report. It happens due to synchronization issue. If you press ESC and call autocomplete again, columns will come.
