### ISSUE TITLE
DBeaver crashes when selecting `Fetch All Data` with java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by romiof** [dbeaver/dbeaver#34854]
### Description

DBeaver application hang out and freeze, when reaches 25,000 rows of selected data.

<details>

![image](https://github.com/user-attachments/assets/8747cdfe-ade3-418d-b818-f292ae699c27)

![image](https://github.com/user-attachments/assets/b1f2262b-d957-4946-9895-9992a7c99fe1)

</details>

### DBeaver Version

Community Edition 24.1.2

### Operating System

Windows 11

### Database and driver

1. Oracle Oracle Database 12c Release 12.1.0.1.0 - 64bit Production
2. Oracle JDBC driver 23.2.0.0.0

### Steps to reproduce

1. SELECT a huge amount of data
2. after preview is loaded, click on  `Fetch All Data`
3. wait a couple of time

### Additional context

When the application hang out, CPU and RAM usage goes crazy:
![image](https://github.com/user-attachments/assets/554bf5a0-31ce-49bf-a9d0-b9c8c641e19c)

Java logs shows `java.lang.OutOfMemoryError: Java heap space`

[dbeaver-diagnostic-info-1721218206488.zip](https://github.com/user-attachments/files/16265555/dbeaver-diagnostic-info-1721218206488.zip)

**Comment by E1izabeth** [comment]
By default DBeaver Community has maximum memory limit 1gb.
You can increase this limit in dbeaver.ini file (see how to find it here https://dbeaver.com/docs/dbeaver/Configuration-files-in-DBeaver/#how-to-locate-the-dbeaver-ini)
Try to change -Xmx1024m into -Xmx4096m to increase maximum memory to 4Gb.

**Comment by romiof** [comment]
> By default DBeaver Community has maximum memory limit 1gb. You can increase this limit in dbeaver.ini file (see how to find it here https://dbeaver.com/docs/dbeaver/Configuration-files-in-DBeaver/#how-to-locate-the-dbeaver-ini) Try to change -Xmx1024m into -Xmx4096m to increase maximum memory to 4Gb.

I didn't know about this limitation. But I can confirm: it works when setted to 4Gb.

Thanks.
