### ISSUE TITLE
Export Window

### ISSUE THREAD

**Issue by brankotasevski** [dbeaver/dbeaver#34850]
### Description

![export windows](https://github.com/user-attachments/assets/ef10cd55-cb11-4108-bb74-06b6826a5fd1)

Hi after update i have problem with export window, is going on second screen

### DBeaver Version

24.1.2

### Operating System

Windows 11

### Steps to reproduce

1. get data
2. export data

**Comment by E1izabeth** [comment]
Thank you for bug report.
I'm closing it as a duplicate of https://github.com/dbeaver/dbeaver/issues/34705
The fix will be available in the next DBeaver version. Also you can try it now with Early Access version https://dbeaver.io/files/ea/
