### ISSUE TITLE
Wrong DDL generated for computed columns on SQL Server

### ISSUE THREAD

**Issue by queueseven** [dbeaver/dbeaver#3486]
Create a table with a computed column, e.g.:

```
CREATE TABLE [dbo].[foo](
	[something] [int] NULL,
	[bar]  AS ((3)*[something])
) ON [PRIMARY]
```

Now, generate the DDL for that table in DBeaver. It will look like this:

```
CREATE TABLE foo (
	something int,
	bar int
) go;
```

This is wrong and clearly a bug. Note how `bar` isn't a computed column in DBeaver's result. The entire ` AS ((3)*[something])` part is missing.

**Comment by uslss** [comment]
will be implemented in the scope of #3487 
closed as duplicate.

**Comment by ShadelessFox** [comment]
Reopening this issue since it is not a duplicate. The referenced issue is about UI, but this one is about invalid SQL.

**Comment by flambchap** [comment]
Closing it once again, now as a duplicate of https://github.com/dbeaver/dbeaver/issues/11426.
