### ISSUE TITLE
Broken output when use Execute SQL script

### ISSUE THREAD

**Issue by Ryoka** [dbeaver/dbeaver#34865]
### Description

After upgrading to 24.1.2, output in the Output window became broken. It may or may not display anything in the window. For example, this code on PostgreSQL may or may not produce a row in Output window:

DO $$ 
DECLARE
    v   TEXT = 'test';
BEGIN
   RAISE NOTICE '%', v;
END;$$;

My colleague on Windows could not reproduce the issue. I downgraded to 24.1.1 where the issue does not exist.

### DBeaver Version

24.1.2 for Apple Silicon

### Operating System

macOS 14.5

### Database and driver

Database is PostgreSQL 14.12
PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

Connect to the database and execute the following script, and look at the Output window:

DO $$ 
DECLARE
    v   TEXT = 'test';
BEGIN
   RAISE NOTICE '%', v;
END;$$;

**Comment by alchemistmatt** [comment]
I am seeing this issue on Windows with version 24.1.3.  Observations:
* I have an anonymous code block (DO $$ ... END;$$;) in a script tab and I highlight the lines of text with the SQL, then run them using `Right Click`, `Execute`, `Execute SQL Script`
  * Result: nothing appears in the Server Output panel
* If I have an anonymous code block, highlight lines of text, then run them using `Right Click`, `Execute`, `Execute SQL Query`
  * In this case, I do see the output in the Server Output panel
* Calling a procedure that has `RAISE INFO` statements, I see the server output (when using either `Execute SQL Script` or `Execute SQL Query`)

So, `Execute SQL Query` shows the correct behavior for highlighted SQL, but `Execute SQL Script` erroneously has no output.  My observations are likely consistent with issue #34744

**Comment by MashaKorax** [comment]
Thanks for your report. I reproduce it.
There is no server output  when use  **Execute SQL script**

**Comment by fifonik** [comment]
I'm having the same issue in DBeaver 24.1.2 (Linux), 24.1.3 (Linux), 24.1.4 (Linux), 24.1.4 (Windows) when working with PostgreSQL.
24.1.1 does not have the issue on both Windows & Linux.

**Comment by serge-rider** [comment]
PR also fixes https://github.com/dbeaver/dbeaver/issues/35135

**Comment by E1izabeth** [comment]
We fixed this bug.
You can try Early Access version with fix (https://dbeaver.io/files/ea/) or wait for the next release
