### ISSUE TITLE
No way to see if a column is a computed column in SQL Server

### ISSUE THREAD

**Issue by queueseven** [dbeaver/dbeaver#3487]
There's practically no way to know is a column is a computed column in DBeaver.

The DDL generated by DBeaver is wrong (see #3486).

And in the GUI, there's no way to see a computed column, too.

For example, here's what the GUI for the same table looks like in Management Studio and DBeaver:

Management Studio:

![image](https://user-images.githubusercontent.com/3126597/40163712-d496f0e4-59b7-11e8-9a6d-fe1f37c07c68.png)

DBeaver:

![image](https://user-images.githubusercontent.com/3126597/40163717-d827aa5a-59b7-11e8-8a41-e91d2f7c12ba.png)

**Comment by icenold** [comment]
any update on this?

**Comment by denious** [comment]
Any update?

**Comment by ShadelessFox** [comment]
Implemented (in scope of #11426):

![image](https://user-images.githubusercontent.com/35821147/115540312-a1ef0880-a2a6-11eb-9278-45d016619a43.png)

These properties are hidden by default. They can be toggled in <kbd>Configure columns</kbd>, available in table's header context menu.

Also it is possible to edit them when creating a new column.

**Comment by uslss** [comment]
verified
