### ISSUE TITLE
Data preview forces full table Scan in Trino

### ISSUE THREAD

**Issue by schaffino** [dbeaver/dbeaver#34887]
### Description

If a trino cluster is configured with fault tolerant execution, queries are run to completion before results are returned. This means previewing a table in dbeaver ends up scanning the whole table and taking a lot of time, and potentially a huge amount of resources and storage for large tables.

Trino supports SQL limit statement, so we can enable SQL based row limiting in the plugin and make it the default for trino connections.

### DBeaver Version

Community Edition 24.1.2

### Operating System

Linux

### Database and driver

Default trino JDBC driver

### Steps to reproduce

1) Configure a trino cluster with TASK or QUERY retry policy and an exchange manager for fault tolerance
2) Preview any large table with DBeaver. The whole table contents will be read and the contents spooled to the exchange manager storage.

**Comment by E1izabeth** [comment]
Thank you for bug report
