### ISSUE TITLE
[CUBRID] Error Handling when connected with EOL version

### ISSUE THREAD

**Issue by longhaseng52** [dbeaver/dbeaver#34885]
There is a problem cannot be connected from DBeaver version 24.1.1 to CUBRID version 9.3.
Because the 'db_charset' class does not exist in Version 9.3.
 
Since version 9.3 is EOL(End Of Life), our solution is, we will make modifications as follows to address future issues.

1. Error handling.
 
2. Create a warning pop-up like the message below.
"The connected CUBRID is an EOL version. Limited features are available."
 
3. Remove the navigator list excluding Data types.

**Version 9.3 is only supports query editor.**

**Comment by E1izabeth** [comment]
Thank you for request
