### ISSUE TITLE
Text cursor (caret) disappearing randomly

### ISSUE THREAD

**Issue by meglio** [dbeaver/dbeaver#34883]
### Description

Take a look at this example screenshot:

<img width="478" alt="image" src="https://github.com/user-attachments/assets/db366cc6-63a0-4daf-adeb-fd09eb3ce5eb">

The input has the focus, and I can edit the text. But the text caret is not shown.

There are no reproducible steps, it just happens randomly in difference places in the DBeaver interface.

### DBeaver Version

Version 24.1.1.202406231636

### Operating System

macOS Sonoma 14.5 (23F79)

**Comment by MashaKorax** [comment]
Unfortunately we have no idea how to reproduce this. If you catch steps to reproduce, you can reopen the issue.
