### ISSUE TITLE
postgresql and python function

### ISSUE THREAD

**Issue by selster1** [dbeaver/dbeaver#34884]
### Description

I am unable to run a python function because I consistently get this error:
SQL Error [08006]: An I/O error occurred while sending to the backend.
Despite having used the following successfully
SELECT * FROM pg_available_extensions WHERE name = 'plpython3u';
CREATE EXTENSION plpython3u;
CREATE LANGUAGE plpython3u;
SELECT * FROM pg_extension;
SELECT * FROM pg_language;
SELECT * FROM pg_available_extensions WHERE name LIKE '%python%' ORDER BY name;
Thanks, Steve

### DBeaver Version

24.1.3.202407172322

### Operating System

win 10 64 bit

### Steps to reproduce

1. install the language and run the following commands
2. create needed environmental variables
SELECT * FROM pg_available_extensions WHERE name = 'plpython3u';
CREATE EXTENSION plpython3u;
CREATE LANGUAGE plpython3u;
SELECT * FROM pg_extension;
SELECT * FROM pg_language;
SELECT * FROM pg_available_extensions WHERE name LIKE '%python%' ORDER BY name;
3. create a function then get the error
4. SQL Error [08006]: An I/O error occurred while sending to the backend.

**Comment by selster1** [comment]
sample function but all functions in python produce this error
CREATE OR REPLACE FUNCTION url_quote (url text)
RETURNS TEXT
AS $$
    from urllib.parse import quote
    return quote(url)
$$
LANGUAGE 'plpython3u';

**Comment by selster1** [comment]
in pgadmin I get this message
The application has lost the database connection:
⁃ If the connection was idle it may have been forcibly disconnected.
⁃ The application server or database server may have been restarted.
⁃ The user session may have timed out.
Do you want to continue and establish a new session

**Comment by Destrolaric** [comment]
@selster1 Hi, as you mentioned, the issue is reproducible in pgadmin. I am not entirely sure that it comes from the DBeaver side. Are you sure that it works this way?

**Comment by selster1** [comment]
Eventually resolved by reading the POStgresql.coNF file which specified
Python 3.11. So I uninstalled Python 3.13. Then I ran the dependency walker
and found another DLL that was missing.

**Comment by selster1** [comment]
If somebody needs to know which file that dependency walker looked at, let
me know and I’ll look it up
