### ISSUE TITLE
Altibase table and column description not displayed...

### ISSUE THREAD

**Issue by davidoff2500** [dbeaver/dbeaver#34891]
You are using Altbase.

When double-clicking the table, it is uncomfortable that comments are not displayed in the table and column specification.

The red mark part of the attached file image is the column description, it should be column comment..

but it display "F" or "V"..
![제목 없음](https://github.com/user-attachments/assets/127ac1d0-e07a-45d0-bb10-ec6ddc5f8e2a)

**Comment by E1izabeth** [comment]
Thank you for report.

**Comment by Matvey16** [comment]
@davidoff2500 Are you sure those are not the actual comments on your columns?
What is a version of your database and driver?

I see the actual comments in my table

![image](https://github.com/user-attachments/assets/df88482b-808d-4c5a-bdb0-e198df05eae0)


Can you try modifying any of those comments with SQL query and see if it changes?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
