### ISSUE TITLE
Some text fields show up as type "NA" and DBeaver can't find text in these fields

### ISSUE THREAD

**Issue by rhstanton** [dbeaver/dbeaver#34906]
### Description

I'm trying to edit my Adobe Lightroom catalog file (SQLite) to change the location where it thinks my photos are. When I use "Search" -> "DB Full TexT" to search for the string "thunder", the search returns no results, despite my being able to see this string just fine in some fields. Further investigation reveals that DBeaver reports the data type for these fields as "NA", which I assume has something to do with the inability to search for text in them. Can anyone help me here?

### DBeaver Version

Enterprise Version 24.1.0.202406100905

### Operating System

macOS 14.5

### Database and driver

SQLite (Pro)

### Steps to reproduce

I've created a tiny version of the original database with just one table in it. Download it from:

https://www.dropbox.com/scl/fi/hwtr77qw78gbkm5jxn7pg/test.lrcat?rlkey=emz9anxkt1oc13vv5oos6600o&st=w4zl7ltm&dl=0

Open a SQLite connection to the file and do a full-text search for "thunder". It returns no results, even though you can see the string in the field "absolutePath"

**Comment by E1izabeth** [comment]
Thank you for bug report.
I see that JDBC driver returns empty string as data types for this columns. So, for me it looks like a driver issue.

**Comment by rhstanton** [comment]
Thanks for checking. How do we handle driver issues?

**Comment by E1izabeth** [comment]
We need some time to discuss and investigate, what can we do here.

**Comment by rhstanton** [comment]
Thanks.
