### ISSUE TITLE
Connect visualizer aren't stopped working

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#34901]
### Description

If you open several scripts to the disconnected database and connect won't be successful, only one script get disconnected badge, others are still get the animation like the connection is still in progress.
Although, I see blinking Connect visualizer task all the time, when any editor is open. It's annoying.

### DBeaver Version

DBeaver 24.1.3

**Comment by E1izabeth** [comment]
Caused by #34579

**Comment by EmirLogas** [comment]
I have this problem too. It happens when I am connected to the db and when I disconnect from all dbs and wait idle. So it happens all the time.

https://github.com/user-attachments/assets/34f4dea7-7190-491e-9862-ae15e6ea972f

**Comment by HiIamJeff** [comment]
Just to add a side issue, when this happens (blinking Connect visualizer), it appears that "mouse hovering on an item to show brief info" (whether a DB connection or a column name) would not work correctly (the item info would show up for a millisecond only and go away).
