### ISSUE TITLE
Incorrect database is chosen when changing connection

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34909]
### Description

When I choose another connection from a list of connections, application doesn't choose "active catalog/schema" of a chosen connection, instead it remains the same.
Finally, I end up with connecting to wrong database.

### DBeaver Version

Community Edition 24.1.3.202407122322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

- create 5 databases and 5 connections, each connection - connects to its own database (pg1 = db1, pg2 = db2, etc..)
- in proprerties of each connection, set option "Show all databases" = true
- close and open the app, so that postgres databases are grouped in one sub-list of items "PostgreSQL" when pressing a small triangle with connection list 
- being connected to pg1 connection, try to change current connection to pg2, how I do it in the video

expected: "Active catalog/schema" is set to "public@db2"
actual: "Active catalog/schema" is set to "public@db1"

https://github.com/user-attachments/assets/5bc5a255-2d5e-4219-91b2-0f67b4aa13d9

**Comment by uslss** [comment]
thanks for the report
