### ISSUE TITLE
TRUNC() is not working for timestamps

### ISSUE THREAD

**Issue by eponcede** [dbeaver/dbeaver#34902]
### Description

Not able to format timestaps with any function

### DBeaver Version

24.1.2

### Operating System

Windows 10

### Database and driver

Oracle

### Steps to reproduce

select ID, NAME, TRUNC(LAST_UPDATE_DATE) from TCR_HUB.C_XL_CAPIQ_PRTY

**Comment by E1izabeth** [comment]
Close as duplicate of discussion https://github.com/orgs/dbeaver/discussions/34903
Answer https://github.com/orgs/dbeaver/discussions/34903#discussioncomment-10111975
