### ISSUE TITLE
(xx) Drag & drop of sql files doesn't allow to drop file to controls other than sql editor

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34910]
### Description

It is not handy for a user to drop it only in specified areas.
I suggest to allow dropping sql-files to the whole application's main window, if possible, so that a user will not have to put additional attention to move mouse precisely.

### DBeaver Version

Community Edition 24.1.3.202407122322

### Operating System

Windows 10

### Steps to reproduce

https://github.com/user-attachments/assets/c1516123-e81a-41e1-b5c4-4cff9946d02e

**Comment by arhayka** [comment]
We discussed this suggestion with the team and decided that this is expected behavior. 
So, I closed this ticket.
