### ISSUE TITLE
Feature: Add context menu to enable selected trigger(s)

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#3491]
DBeaver - **Version 5.0.5 CE**
DBeaver JDBC driver: **Microsoft Driver**
Operating System: **Windows 7** / **Windows 8.1** / **Windows 10**
Database Server: **Microsoft SQL Express 2014**

It would be benificial when connected to a MS SQL Server to be able to "right-click" on a trigger in the **Database Navigator** or equivalent and be able to choose **Enable Trigger** or **Disable Trigger**.

Also if I select more than one trigger, that all selected triggers get enabled/disabled.

**NOTE 1**

Maybe also indicate if a trigger is enabled or disabled. Compare functionality in _Microsoft SQL Server Management Studio_ that show a small "x" on the trigger if it is disabled.

**NOTE 2**

If there are other databases that also support enable/disable triggers, that the functionality is added for them too.

**Comment by mlt** [comment]
Isn't it a dup of #3374?

**Comment by uslss** [comment]
verified
