### ISSUE TITLE
Splash screen overlaps error message and doesn't disappear until closing the error message which is not visible

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34917]
### Description

If some error is shown due to opening a script, the splash window can overlap the error message and block the user.
It is very confusing for a user because he could miss the error message and wait for the splash screen to close (infinitely 🤣).

### DBeaver Version

Community Edition 24.1.3.202407122322

### Operating System

Windows 10

### Steps to reproduce

- open dbeaver(!)
- use command line (cmd.exe) to run dbeaver with passing an argument (file path to a script, which actually not exists)

expected: error message is shown to a user
actual: error message is behind the splash screen, so user is unable to see the message and react

By the way, I'm not sure if splash screen should be shown at all in this case.
For example, SSMS doesn't show splash screen if main window has already opened.

Here on the video, first of all I show that the Dbeaver has already running before executing a command in cmd.exe.

https://github.com/user-attachments/assets/6d7bbc5a-e2a3-4149-8da0-71b26a4185f4

**Comment by E1izabeth** [comment]
Thank you for bug report.
