### ISSUE TITLE
Feature: Add context menu to drop selected trigger(s) 

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#3492]
DBeaver - **Version 5.0.5 CE**
DBeaver JDBC driver: **Microsoft Driver**
Operating System: **Windows 7** / **Windows 8.1** / **Windows 10**
Database Server: **Microsoft SQL Express 2014**

It would be benificial when connected to a MS SQL Server to be able to "right-click" on a trigger in the **Database Navigator** or equivalent and be able to choose **Drop Trigger**.

Also if I select more than one trigger, that all selected triggers get dropped.

**Comment by serge-rider** [comment]
Good point
