### ISSUE TITLE
Table alias in update-query (in set-clause) is colored with wrong color

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34924]
### Description

use this code:

```
create table tab1 (
    id int primary key,
    name1 varchar(100)
);
insert into tab1 values(1, 'jack');
insert into tab1 values(2, 'john');

create table tab2 (
    id int primary key,
    name1 varchar(100)
);
insert into tab2 values(1, 'ann');
insert into tab2 values(3, 'kate');

update tab1 t
set name1 = t2.name1
from tab2 t2
where t.id = t2.id
```

https://github.com/user-attachments/assets/97742f3a-94de-4f36-8c0f-85533e0452ed

### DBeaver Version

Community Edition 24.1.3.202407122322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

**Comment by uslss** [comment]
thanks for the bug report
