### ISSUE TITLE
Navigator node 'node://General/datasources/*/*' not found

### ISSUE THREAD

**Issue by ghsatpute** [dbeaver/dbeaver#34934]
### Description

I have one directory in DBeaver named "XYZ Dev DBs" (not giving actual name). Inside that I have one more directory called "MyGroup". I earlier had one connection, named "abcd", which I copied into "efgh". 

I updated the relevant details by changing the database name, SSH connection details and saved the connection. Now, I tried to open a table in the new connection "efgh". 

So the tree looks like as below 
```
XYZ Dev DBs (Directory):
      MyGroup (Directory):
             abcd (old connection)
      MyGroup2 (Directory):
             efgh (new connection)
```

Now, when I try to open any "efgh", the left side tree opens correctly but when I click on any table, I get below error
<img width="875" alt="image" src="https://github.com/user-attachments/assets/f8b10a5b-ed61-4c9c-9539-6ee06cd6c152">

What I suspect is, somewhere there is a reference of the old directory, "MyGroup" which is not getting replaced while copy-pasting. I've tried to manually see any references of "MyGroup" in all the connection settings, but I couldn't find any reference. 

1. Can somebody help me identify where is the reference to "MyGroup"
2. Can we fix this issue during copy-pasting so in future other people are not facing the same issue. 

### DBeaver Version

Community Edition Version 24.1.2.202407071610 

### Operating System

MacOS 14.5 (23F79)

### Database and driver

PostgresSQL 

### Steps to reproduce

Mentioned in the description.

**Comment by MashaKorax** [comment]
Hello @ghsatpute How exactly did you copy your connection? This way or another?

https://github.com/user-attachments/assets/f757dfc2-eeb8-4f7c-a856-847349d90bb3

**Comment by ghsatpute** [comment]
Hi @MashaKorax, 

Yes I copied it that way. I used shortcuts CMD + C & V to be specific.

**Comment by MashaKorax** [comment]
Could you please provide log files?

**Comment by ghsatpute** [comment]
Hi @MashaKorax 
PFA attached. 

[dbeaver-diagnostic-info-1723124298075.zip](https://github.com/user-attachments/files/16548826/dbeaver-diagnostic-info-1723124298075.zip)

**Comment by ShadelessFox** [comment]
Hello @ghsatpute,

Can you reproduce your issue using our sample database (Help -> Create sample database) and record a video showing the steps?

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
