### ISSUE TITLE
Feature Request: Duration in Minutes

### ISSUE THREAD

**Issue by JRDK92** [dbeaver/dbeaver#34935]
**Is your feature request related to a problem? Please describe.**
Long running scripts show duration in milliseconds, which is not helpful. No one uses milliseconds for anything in the real world. When you go for a run, or microwave something, it's either minutes or seconds. Seeing 514,926 ms run time isn't helpful, because then you have to export to excel, divide that out to get seconds, divide again to get minutes. 

**Describe the solution you'd like**
Simple option in the preferences/settings to identify how long each step of an SQL query is taking. Ex: 15 mins 45 seconds

**Comment by E1izabeth** [comment]
What DBeaver version do you use? I can't reproduce it on the latest version.
![image](https://github.com/user-attachments/assets/c7984ff0-bf7f-4463-a2b4-30648c0a67f6)

**Comment by JRDK92** [comment]
@E1izabeth How did you get that pop up window? As far as I can tell on the latest version for Windows, it is not standard. When you run a script, not a single query, it shows query manager with each sequential step that it goes through, and each of those steps are listed in milliseconds. There's no big progress bar like the picture you showed

**Comment by E1izabeth** [comment]
You're right. It appears only on single query execution.
And Query Manager shows time only in milliseconds after the end of query execution.
We will discuss, how we can improve this behavior. Thank you for request

**Comment by arhayka** [comment]
Thank you for your request!
We could add a setting and change the query duration results presentation in Statistics tab, Query manager, and in the status bar.

**Comment by JRDK92** [comment]
@arhayka Thanks. I think this would be a terrific idea.
