### ISSUE TITLE
Maven artifact 'com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE' not found in any available repository.

### ISSUE THREAD

**Issue by JustGitting** [dbeaver/dbeaver#34949]
### Description

Hi all,

I've just upgraded from 24.0.<something> to 24.1.3 on a Windows 10 Enterprise PC.
After the upgrade the MS SQL Server driver is unable to update/install correctly, specifically the windows mssql-jdbc_auth.dll for windows authentication cannot be found.

Each time I start DBeaver or try to access a MS SQL Server database the "Download driver files" pop-up window appears and says "MS SQL Server /SQL Server driver files are missing", but the "Files required by driver" list is blank.

I've reset defaults for the mavern repositories and SQL Driver settings with no success. 

The MS JDBC JAR file is successfully downloaded, but not the auth dll file.

"C:\Users\user1\AppData\Roaming\DBeaverData\drivers\maven\maven-central\com.microsoft.sqlserver\mssql-jdbc-12.7.0.jre11-preview.jar"
"C:\Users\user1\AppData\Roaming\DBeaverData\drivers\maven\maven-central\com.microsoft.sqlserver\mssql-jdbc-12.7.0.jre11-preview.pom"

Checking the logs it shows that the mssql-jdbc_auth dependency cannot be found.

```
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\user1\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Warning
Tue Jul 23 14:19:27 AEST 2024
Maven artifact 'com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE' not found in any available repository.

eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\user1\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Jul 23 14:19:27 AEST 2024
Error resolving library 'com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE' dependencies

	eclipse.buildId=unknown
	java.version=17.0.6
	java.vendor=Eclipse Adoptium
	BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
	Framework arguments:  -eclipse.keyring C:\Users\user1\AppData\Roaming\DBeaverData\secure\secure_storage
	Command-line arguments:  -os win32 -ws win32 -arch x86_64

	org.jkiss.dbeaver.model
	Error
	Tue Jul 23 14:19:27 AEST 2024
	Maven artifact maven:/com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE :12.7.0.jre11-preview.x64 is not found

	java.io.IOException: Maven artifact maven:/com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE :12.7.0.jre11-preview.x64 is not found
		at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:343)
		at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:247)
		at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
		at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
		at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:135)
		at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
		at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)

eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\user1\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Jul 23 14:19:36 AEST 2024
Error resolving library 'com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE' dependencies

	eclipse.buildId=unknown
	java.version=17.0.6
	java.vendor=Eclipse Adoptium
	BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
	Framework arguments:  -eclipse.keyring C:\Users\user1\AppData\Roaming\DBeaverData\secure\secure_storage
	Command-line arguments:  -os win32 -ws win32 -arch x86_64

	org.jkiss.dbeaver.model
	Error
	Tue Jul 23 14:19:36 AEST 2024
	Maven artifact maven:/com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE :12.7.0.jre11-preview.x64 is not found

	java.io.IOException: Maven artifact maven:/com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE :12.7.0.jre11-preview.x64 is not found
		at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:343)
		at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:247)
		at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
		at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
		at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:135)
		at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
		at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
```

The odd thing is that it's trying to install the testing version 12.7.0-preview. Shouldn't it be using a stable version like 12.6?

Do I need to add another maven repo for this to work?

Thanks for any suggestions.

Cheers

### DBeaver Version

Community v 24.1.3

### Operating System

Windows 10 Enterprise

### Database and driver

Database: MS SQL Server 14

Driver: MS SQL JDBC v12.7.0.jre11-preview

### Steps to reproduce

1. Start DBeaver
2. Driver Settings - Download Driver files pops up automatically.
3. No files required by driver is found.
4. Check logs to find it is unable to find mssql-jdbc_auth file.

**Comment by E1izabeth** [comment]
Please, try latest DBeaver version 24.1.3

**Comment by JustGitting** [comment]
Hi @E1izabeth

Sorry, typo.

I meant to say I upgraded to 24.1.3.

**Comment by E1izabeth** [comment]
@JustGitting 
Please perform the following steps as a workaround:
1. Open connection configuration
![image](https://github.com/user-attachments/assets/409765cd-8ea3-4635-978e-1068ba2999b5)

2. Press `Driver settings`
![image](https://github.com/user-attachments/assets/a2a91089-6511-4ebb-9065-391623559f6e)

3. Switch to `Libraries` tab
![image](https://github.com/user-attachments/assets/bbadc348-ad70-4be1-922c-d5884f25a109)

4. Select every blue item in the list and press `Download\Update`
![image](https://github.com/user-attachments/assets/9e5c6677-add0-4a87-a173-160e6c7c218e)

5. Press `Download` in the `Driver settings` dialog, even if the list is empty
![image](https://github.com/user-attachments/assets/b10f8cc8-4461-428e-aeba-4dad9b6e191d)

**Comment by A-Nicoladie** [comment]
On 24.1.1, I have this driver configuration for MsSQL

![image](https://github.com/user-attachments/assets/597702ed-67f7-4cfd-99cf-5cc6b1994d73)

After upgrade to 24.1.3, the driver configuration have change to this

![image](https://github.com/user-attachments/assets/fdf3f711-bc41-466b-a12b-a4b695e93c0c)

And I wasn't able to download or install anything

![image](https://github.com/user-attachments/assets/9647fbd8-4571-4a93-9850-5519f91a554b)

ℹ️ I was able to connect again by deleting the two library lines (mssql-jdbc and mssql-jdbc_auth)\
Then back to version `24.1.1`, applying the **default settings** : driver 12.4.1 \
⚠ Important : default driver must be this version, not 12.7.0\
and finally (but not necessarily), updating drivers to version 12.6.3

![image](https://github.com/user-attachments/assets/c2548e85-aa74-4841-935b-ccbe260bf781)

**Comment by JustGitting** [comment]
> @JustGitting Please perform the following steps as a workaround:
> 
>     1. Open connection configuration
> ...

@E1izabeth 
Yes, tried it and same error.

Hi @A-Nicoladie, 
Thanks, I tried your suggestion, but didn't work. 

Within DBeaver 24.1.3 I removed the two lines (referencing the MS files for v12.7) within the libraries tab.
Then I downgraded DBeaver from 24.1.3 to 24.1.1. Within the driver libraries, I selected "reset to defaults", but it still defaults to 12.7.0 preview, not 12.4.

Maybe there is some crud left-over from the previous install...not sure where to look for it.

Hi @Destrolaric, thanks for the quick fix.

https://github.com/dbeaver/dbeaver/milestone/219

I hope it's released sooner than the 5th August as I'm stuck at the moment.

**Comment by E1izabeth** [comment]
@JustGitting we will build the Early Access version as soon as make sure that provided fix helps.

**Comment by E1izabeth** [comment]
@JustGitting @A-Nicoladie please try Early Access version https://dbeaver.io/files/ea/

**Comment by A-Nicoladie** [comment]
It's OK form me. Perfect ! 

![image](https://github.com/user-attachments/assets/656c9cea-21a4-4199-b20e-4d9db806cf94)

Thanks 👋

**Comment by JustGitting** [comment]
Thanks @E1izabeth

> @JustGitting @A-Nicoladie please try Early Access version https://dbeaver.io/files/ea/

Are there sha256 hashes to verify the downloads?

**Comment by E1izabeth** [comment]
@JustGitting no

**Comment by Ceesarcaceres** [comment]
Thanks @E1izabeth 

> @JustGitting @A-Nicoladie please try Early Access version https://dbeaver.io/files/ea/

Works here installing this version.

**Comment by JustGitting** [comment]
@E1izabeth 
> @JustGitting no

Okay, can that be added so downloads can be verified?

**Comment by E1izabeth** [comment]
@JustGitting yes, we'll add it. Thank you

**Comment by arhayka** [comment]
Added checksum folder to https://dbeaver.io/files/ea/

**Comment by luis13005** [comment]
you found a solution? Same error here.

**Comment by Ceesarcaceres** [comment]
> you found a solution? Same error here.

Try to update to the newest version.

**Comment by jonasnordlund** [comment]
This is still a problem for me in 25.0.2 Early Access. I've tried resetting to default settings as well as deleting the artifacts and then resetting, but that just restores the invalid artifact locations again. Will try manual install next.
