### ISSUE TITLE
WITH queries not available

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [dbeaver/dbeaver#3494]
Simple [WITH](https://www.postgresql.org/docs/9.1/static/queries-with.html) queries aren't working in v5.0.5

![screen shot 2018-05-18 at 7 54 28 am](https://user-images.githubusercontent.com/8518288/40235780-ed0c345e-5a70-11e8-992a-9559ddb99fb8.png)

I've confirmed below that I am able to successfully run the same query directly from the command line
![screen shot 2018-05-18 at 7 57 51 am](https://user-images.githubusercontent.com/8518288/40235872-33ebdbcc-5a71-11e8-9fa5-81fc1c5eb60c.png)

**Comment by serge-rider** [comment]
What is you database?

**Comment by serge-rider** [comment]
Oops, it is clearly PostgreSQL :)

**Comment by serge-rider** [comment]
You have incorrect SQL query (see https://www.postgresql.org/docs/9.1/static/queries-with.html).
You don't see error in psql because you didn't terminate your query with `;` character.

**Comment by ConstantinoSchillebeeckx** [comment]
:flushed: my bad ...

For those that end up here for some reason, the correct syntax in my case would have been:
```
with x as (select * from apis) select col_a from x where col_a = something;
```
