### ISSUE TITLE
Question: Session Management for Oracle DB

### ISSUE THREAD

**Issue by angelotodaro** [dbeaver/dbeaver#3495]
I'm looking to use the Session Manager tool for Oracle and have seen it mentioned when googling but I can't seem to find where it is at in the software. The only mention of it in the official docs is just saying that it supports it. I'm on 4.2.4 CE

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/40278903-2572da0a-5c42-11e8-8e79-c007ca524b2e.png)

**Comment by angelotodaro** [comment]
I don't have that option under mine. I know my schema has access as I can query the tables and view the sessions from Oracle SQL Developer.

**Comment by serge-rider** [comment]
Perhaps this is because you don't have DBA role.
I'll enable visibility of this folder for all users (sometimes you can view session without DBA access).
Please check it in 5.0.6
