### ISSUE TITLE
Paste into table  is not working when table has no keys

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#34956]
### Description

if there are no keys in the table the option Copy-Paste does not work
Note - It is working in case if  you first place the cursor in a cell

STR:

1. Open table without keys (orange mark)
2. Copy cell
3. Paste  into another cell of this table (NOTE cell should be NOT in inline edit mode)

https://github.com/user-attachments/assets/92068672-ac8b-4e13-8df1-ad45d879a11a

### DBeaver Version

24.1.4

### Operating System

mac M1 Sonoma

**Comment by serge-rider** [comment]
Fixed

**Comment by MashaKorax** [comment]
verified
