### ISSUE TITLE
Bug: editing array value in PostgresSQL

### ISSUE THREAD

**Issue by studiointer** [dbeaver/dbeaver#3496]
We have table with structure
`CREATE TABLE public.event (
	id serial NOT NULL,
	"start" time[] NULL
)`

**start** column is array. When I try to edit it with visual editor, BDeaver generates code:
`UPDATE public.event
SET "start"='{'11:00:00','12:00:01'}'
WHERE id=2;
`
It cant execute, because of double **'** symbols.

Can execute if
`UPDATE public.event
SET "start"='{"11:00:00","12:00:01"}'
WHERE id=2;
`
**"** symbols in array instead **'**
PostgreSQL 10.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18), 64-bit

Thank you for free and comfortable SQL editor!

**Comment by serge-rider** [comment]
See fix in 5.0.6
Thank for report.
