### ISSUE TITLE
Cannot connect to Redshift database with same driver as SQL Workbench/J

### ISSUE THREAD

**Issue by coretemp** [dbeaver/dbeaver#3497]
> Read contribution guide before submitting ticket:
> https://github.com/dbeaver/dbeaver/blob/devel/CONTRIBUTING.md

This is an empty file. Please remove this template or update the CONTRIBUTING.md file.

I recently learned about the existence of your program, but apparently it doesn't work. 

I configured dbeaver in exactly the same way as SQL Workbench/J (also provided the correct jdbc42 driver, etc.), but I got the following response:

![screenshot_20180519_190527](https://user-images.githubusercontent.com/34454443/40271091-b642ec14-5b98-11e8-964a-3921025c33c0.png)

The expected response is a connection to the database.

## Technical data
version: DBeaver 5.0.5

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.18, NixOS, 18.03.git.ee80654 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - channels(coretemp): `"nixos-18.03.132192.ce0d9d638de"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by serge-rider** [comment]
* What exactly driver did you use (please post link on AWS resource?)
* Did you try the Redshift driver preconfigured in DBeaver?

**Comment by coretemp** [comment]
@serge-rider 

> What exactly driver did you use (please post link on AWS resource?)

On https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html JDBC 4.2–compatible driver: https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.12.1017/RedshiftJDBC42-1.2.12.1017.jar.

> Did you try the Redshift driver preconfigured in DBeaver?

Yes and it didn't work. There is a reason I was using 4.2 with SQL Workbench/J too. I don't recall that reason, but I also know that 4.1 does not work.

**Comment by serge-rider** [comment]
Please post error stacktrace (you can get it in Error Log view or in file - https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by coretemp** [comment]
@serge-rider It's just a usability issue; I hadn't selected the right class to use via the standard UI workflow that is available. I don't know whether it's a bug, because I think the other way should also work. 

I have access now. Thanks. 

I am closing this now, but you might want to test the other flow too.

**Comment by serge-rider** [comment]
Ok, good.

In any case I'll update Redshift driver version in DBeaver config.
