### ISSUE TITLE
Incorrect syntax highlighting of Postgres functions and procedures

### ISSUE THREAD

**Issue by brankoradovanovic-mcom** [dbeaver/dbeaver#34972]
### Description

Functions and procedures are incorrectly syntax-highlighted in the Source tab.

### DBeaver Version

CE 24.1.3

### Operating System

Windows 10 x64

### Database and driver

n/a

### Steps to reproduce

When a Postgres function or procedure is displayed in the Source tab, it looks e.g. like this:
![Screenshot 2024-07-24 144548](https://github.com/user-attachments/assets/06c19323-f1b4-4956-b9fd-8d679f1c7635)
Note the entire function body is green, as if it is all a literal. The earlier versions correctly highlighted function/procedure bodies.

### Additional context

n/a

**Comment by E1izabeth** [comment]
I can't reproduce the issue. What settings do you have here?
![image](https://github.com/user-attachments/assets/44c25571-8223-4e52-842b-28cd22cea805)

**Comment by brankoradovanovic-mcom** [comment]
> I can't reproduce the issue. What settings do you have here?

Both set to "Code block".

**Comment by E1izabeth** [comment]
Could you change mentioned setting to String literal, then reconnect, then return back to Code block and reconnect again? Does it help?

**Comment by brankoradovanovic-mcom** [comment]
Changed to "String", reconnected, changed back to "Code block", reconnected again, but there is no change.

But: **if I change `$function$` to `$$`, it works**. It also works with right click -> "Show header" turned off.

**Comment by arhayka** [comment]
Related ticket: https://github.com/dbeaver/dbeaver/issues/35015

**Comment by fq-mn** [comment]
The problem described affects not only the source tab for functions and procedures, but also the SQL editor for scripts.

I was able to narrow down the breaking change to commit [d3633d72124c59f78b7de90802695de2c1f559ba](https://github.com/dbeaver/dbeaver/commit/d3633d72124c59f78b7de90802695de2c1f559ba) using git bisect. Especially the changes in class `SQLDollarQuoteRule` seem to be causing the problems for PostgreSQL.

I have been using the following dummy script:
```sql
select 1 as x;

do $$
begin
	raise notice 'Test';
end
$$;

select 2 as x;

do $dummy$
begin
	raise notice 'Test with tag';
end
$dummy$;

select 3 as x;
```

With the old versions of the code, this gets displayed as follows:
![image](https://github.com/user-attachments/assets/ff7d6c18-4374-49fe-b605-b6ee089e18fb)

However, in newer versions it is displayed as follows:
![image](https://github.com/user-attachments/assets/8e706b70-4525-436d-ad92-a4a4503cd2dc)

Here are my connection-specific settings regarding dollar-quoting:
![image](https://github.com/user-attachments/assets/7fb9ad98-0859-4b08-bb08-dea5f24385fa)

And this are my general settings for the PostgreSQL driver:
![image](https://github.com/user-attachments/assets/2835253b-abfe-4dd8-b908-ac16155978c5)

**Comment by E1izabeth** [comment]
As a workaround, you can turn the setting `Enable semantic analysis` in `Preferences->Editors->SQL Editor->Code Editor`

![image](https://github.com/user-attachments/assets/02b9de1b-7663-465f-b97d-6665ba37b84e)

**Comment by fq-mn** [comment]
> As a workaround, you can turn the setting `Enable semantic analysis` in `Preferences->Editors->SQL Editor->Code Editor`

Thank you for this advice. I remember that I turned semantic analysis off when it was first introduced, as it didn't really fit in with my needs at the time. But I have now reactivated it for the time being in order to regain the beloved syntax highlighting for  dollar-quoted code blocks 🙂
