### ISSUE TITLE
dbeaver client two user's privs error!

### ISSUE THREAD

**Issue by liuchuanlong9** [dbeaver/dbeaver#34989]
### Description

connect to oracle two user,one user A just has select privs on user B's tables,In the sql session, A compile insert,update,delete on B'tables, has no privs, It's RIGHT!But if click to B'table and insert,update,delete, It can run and success! amazing!!!!!.that's why?

### DBeaver Version

ex.Community Dbeaver 24.1.1

**Comment by antdbv** [comment]
hi @Aaroncu9 
could you please provide:
1. your database and driver (Edit connection-> Test connection)
2. privileges for both users
3. did you try to reproduce this issue in other applications?
Thank you

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
