### ISSUE TITLE
DBeaver pops up bind parameter dialog on every query 

### ISSUE THREAD

**Issue by mrcolumbia** [dbeaver/dbeaver#34992]
### Description

Hi,

If I am running a script with multiple parametrized queries, the bind parameters dialog box pops up for every single query, even though the parameters haven’t changed. Is there a way to suppress this, as it’s quite annoying and makes running a full script of such queries impractical.

### DBeaver Version

Version 7.1.0.20200531173

### Operating System

Windows 

### Database and driver

Snowflake

**Comment by mrcolumbia** [comment]
Please let me know if further detail is needed.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by mrcolumbia** [comment]
Thanks @E1izabeth. Any idea when you guys might be able to get around to fixing this?

**Comment by E1izabeth** [comment]
I added this issue to the next milestone 24.1.5

**Comment by mrcolumbia** [comment]
Sorry, I’m new here - could you please give me a quick sentence on how milestones correlate with releases?

**Comment by E1izabeth** [comment]
The number is the same :)
So, we plan to fix it in 24.1.5 release

**Comment by mrcolumbia** [comment]
Understood. Thank you.

**Comment by E1izabeth** [comment]
@mrcolumbia have you tried executing `@set` command or adding parameter or variable to the Variables dialog?
![image](https://github.com/user-attachments/assets/08044d3b-786e-40ca-9f51-62df54dd6eb3)

You can open this dialog by pressing at this button on the SQL Editor left bottom toolbar
![image](https://github.com/user-attachments/assets/3fa4943d-3759-4b27-8576-e2a1e8af6fb5)

**Comment by E1izabeth** [comment]
It works as expected for me - Bind parameter dialog appears for every execution, until you set the parameter not through this dialog.

**Comment by E1izabeth** [comment]
Also I would suggest installing latest DBeaver version 24.1.4

**Comment by MashaKorax** [comment]
It works as expected.
