### ISSUE TITLE
Duplicated menu items "Show results in a single/multiple tabs"

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35005]
### Description

https://github.com/user-attachments/assets/156be93c-1596-47ff-a46a-78d9fe135223

### DBeaver Version

Community Edition 24.1.4.202407250946

### Operating System

Windows 10

**Comment by TB-HunBoka** [comment]
#34176

**Comment by E1izabeth** [comment]
Thank you for bug report.
I'm closing it as it's a duplicate of #34176
