### ISSUE TITLE
Unable to create new DuckDB connection

### ISSUE THREAD

**Issue by freakynit** [dbeaver/dbeaver#35014]
### Description

On double clicking the just added duckdb connection (opening it), follwing error gets thrown:
<img width="1277" alt="Screenshot 2024-07-29 at 5 54 12 PM" src="https://github.com/user-attachments/assets/fa5781af-443b-4fdd-9ca9-2c092360b50e">

### DBeaver Version

Version 24.1.3.202407211303

### Operating System

macOS Big Sur 11.5.1

### Database and driver

1. DuckDB
2. Version: tried it with both: `0.10.3` and `1.0.0`

### Steps to reproduce

1. Create new DuckDB connection (in-memory or disk, doesn't matter)
2. Connection gets added on left panel
3. Double click to open it
4. !!Error mentioned above

**Comment by ShadelessFox** [comment]
Hello @freakynit,

It seems that your macOS version is a bit too outdated. DuckDB uses a dynamic native library shipped with our OS that doesn't have the expected symbol (which, presumably, is present in more recent versions).

You can either try using an even older version of the driver or upgrade to the latest macOS.

Please let me know if it helps.

**Comment by freakynit** [comment]
@ShadelessFox I believe you are right. since dbeaver was not working, I thought to use metabase. But it also threw same error. So, I set up a docker container for metabase to test the same... And it worked.

My OS version is 3 year old now.. and im afraid to update it :)

We can close this ticket. Thanks for the support..
