### ISSUE TITLE
sql statement autocomplete error

### ISSUE THREAD

**Issue by pia9322** [dbeaver/dbeaver#35019]
### Description

The search function works normally, but the function that was automatically completed when writing the sql statement is not exposed in that version

### DBeaver Version

24.1.3

### Operating System

window 10

### Database and driver

MySQL

### Steps to reproduce

1. db connect
2. SQL write
3. autocompleter error

**Comment by ShadelessFox** [comment]
Hello @pia9322,

Can you please provide footage showing the issue?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by pia9322** [comment]
I didn‘t feel the experience recently.
