### ISSUE TITLE
Incorrect notification on invalidate

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#35030]
### Description

For some not very clear reason sometimes after clicking invalidate on one connection (background tasks view shows invalidation of only one connection) you will see other connections as invalidated in notification. I'm still not sure what binds different connections to each other. In my case it happend with CUBRID and DB2 connections

### DBeaver Version

24.1.4

### Operating System

Win11

### Database and driver

DB2
CUBRID

### Steps to reproduce

1. Connect to CBURID database
2. Connect to DB2 LUW database
3. Click on Invalidate on any of those connections

**Expected:** Notification shows that only one connection was invalidated
**Actual:** Notification says thet two connections were invalidated

### Additional context

https://github.com/user-attachments/assets/fbbc3e5b-5496-4c36-8238-5ddf9d7f9ef9

**Comment by Matvey16** [comment]
This actually may not be a bug because this appears when connections share the same ssh tunnel host

**Comment by ShadelessFox** [comment]
This behavior is expected and caused by reusing SSH tunnels.
