### ISSUE TITLE
Rebuild indexes 

### ISSUE THREAD

**Issue by rsmolkin** [dbeaver/dbeaver#3503]
Is there a way to rebuild table indexes from the UI like there is in Microsoft SQL Server Management Studio?  If not, how can we rebuild SQL Server table indexes?

**Comment by serge-rider** [comment]
There is no such feature yet.
But of course you can do this in SQL editor (ALTER INDEX ... REBUILD).

**Comment by uslss** [comment]
verified

**Comment by rbuquet** [comment]
#5657 PR was implementing this feature for SQLServer only. Is it possible to reopen this issue to implement it for other databases, ie Oracle Database, PostgreSQL, etc. ?

**Comment by osscar** [comment]
> #5657 PR was implementing this feature for SQLServer only. Is it possible to reopen this issue to implement it for other databases, ie Oracle Database, PostgreSQL, etc. ?

bump on this, in my case for postgres
