### ISSUE TITLE
System table names without specifying optional schema name are colored with wrong color

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35048]
### Description

Both queries are executed correctly but "pg_class" in the second query is colored with red color what means semantic error.
Use this code:
```
select * from pg_catalog.pg_class

select * from pg_class as pc
```

![изображение](https://github.com/user-attachments/assets/bbb6536d-8aca-4736-a522-16617eb6eb6a)

It is similar to this: #34741

### DBeaver Version

Community Edition 24.1.4.202407250946

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

**Comment by E1izabeth** [comment]
Thank you for report.
