### ISSUE TITLE
SQL command use database or use schema does not change active datatabase in Dbeaver 24.1.3

### ISSUE THREAD

**Issue by TokaMora** [dbeaver/dbeaver#35040]
### Description

Regression bug
In Snowflake SQL you have commands like __use database__ or __use schema__ to switch to a certain database or a certain schema. We used to use an old version of Dbeaver (23.1.0) and in this version, when you do __use database__, it switches the database for the session __and__ it switches the active database for DBeaver, which is shown in the menu bar. 

Now we have DBeaver version 24.1.3 and the behaviour changed. A __use database__ still switches the database for the session, but not the active database for DBeaver. This means, the SQLs you type and execute will use the database set for the session (with __use database__). However, it is very confusing to see another database (which is the default database) at the top of the menu bar as the active database. You are never sure which database you are working in.

When you use F4 to see the definition of what's under the cursor, it's using the database shown in the menu bar and __not__ the one set for the session with __use database__.

### DBeaver Version

24.1.3

### Operating System

Windows 10

### Database and driver

Snowflake

**Comment by TokaMora** [comment]
I just now checked with DBeaver version 24.1.0. In this version the behaviour is correct as expected (by me). When you change database with __use database__ this also changes the active database for DBeaver.

**Comment by E1izabeth** [comment]
Thank you for report. This is expected for now as we turned off the setting `Refresh active schema on query execution` due to #34657 
You can turn it on here
![image](https://github.com/user-attachments/assets/d1437d0b-db37-45f4-8a86-a0978e5d5135)

**Comment by TokaMora** [comment]
Hi @E1izabeth , thank you for your response and your suggestion. The setting "Refresh active schema on query execution" was and still is active in my installation, but seems not to work as intended. It's on in global settings as well as it is in the settings for datasource "Snowflake".

**Comment by JTMosaic** [comment]
With the "Refresh active schema after SQL executions" checkbox selected, the active catalog/schema box in the toolbar updates but the schema is not highlighted (bold) in the projects pane. Is this a setting or an enhancement? (Note that as far back as 23.0 it doesn't do this)

**Comment by zippie-lab** [comment]
For me setting the _„Refresh active schema after SQL executions“_ property changes the active database/schema in the menu bar and makes them bold in the Database Navigator. The difference compared to version 24.0.5 is that now (I checked versions 24.1.4 and 24.1.5) a `SELECT CURRENT_DATABASE(), CURRENT_SCHEMA()` is issued after each and every SQL line I'm starting. In version 24.0.5 it was issued only once, after all my SQL statements. In case of multi-line statements (executed as SQL script [Alt+X]), where previous results are read, e.g.:
`show views in schema SOME_DATABASE.SOME_SCHEMA;`
`select "schema_name", "name", "text" from table(result_scan(last_query_id()));`,
the second ends with an error, because of the hidden „refresh“ statement in between. It would be nice and useful to me to have the behaviour of 24.0.5 again.

**Comment by TokaMora** [comment]
I found something. In preferences, when I turn ON Metadata > Do not read tables information.... (put a check mark) then it will NOT change active database or schema when I do "use database" or "use schema". When I turn this feature OFF (no check mark), it DOES change. But unfortunately, when this setting is off, any SQL does a "detect unique identifiers" which can last for a minute or more. For me this is a no go, so I turned the setting ON (put a check mark). I had no idea that these two things are related.

Can these two features be separated from each other?

![image](https://github.com/user-attachments/assets/2f78d05c-43d4-4099-a093-b2304ef46159)

**Comment by TokaMora** [comment]
As it looks, the two functions are connected => To read metadata (like unique keys) and to change active database and schema after running a SQL statement.

![image](https://github.com/user-attachments/assets/bce2803a-1f72-4eed-b4bc-f801afe13559)

At least in Snowflake, this metadata read feature has a big impact to processing time. Even a SELECT * on a tiny small table with just 94 rows in it needs more than a minute to "detect unique identifiers". 

Can we switch on/off seperately the feature to write back query results? I think this is the feature that needs to read unique identifiers in the first place. I don't need the write back feature nor do I need to identifiy unique identifiers. It's way to time consuming. What I do need is just a change in active database after use database or use schema.

**Comment by TokaMora** [comment]
In DBeaver version 24.1.0 this is not connecetd. But the settings look different. The relevant options are under Data editor, not in Metadata. When you switch off both read table options in Version 24.1.0, I have no long running SQL and I have expected behaviour when using use database or use schema (i.e. switching active database).

So for me, version 24.1.0 is a keeper for the time being.

![image](https://github.com/user-attachments/assets/37037dfd-a7e3-445a-be30-cd1175a5c380)
