### ISSUE TITLE
Could not save changes in Procedure MSSQL Server 2019

### ISSUE THREAD

**Issue by jrmejiaa** [dbeaver/dbeaver#35062]
### Description

Hi, 

I am trying to change a Procedure in a MSSQL 2019 server and I got always the error down. 

[dbeaver-debug.log](https://github.com/user-attachments/files/16474542/dbeaver-debug.log)

### DBeaver Version

Community Version  24.1.4.202408041450

### Operating System

Debian 12

### Database and driver

1. MSSQL Server 2019
2. Microsoft JDBC Driver 12.4 for SQL Server [12.4.1.0]

### Steps to reproduce

1. Connect to MSSQL Database
2. Be able to see tables and procedures
3. Open a Procedure
4. Make any change
5. Try to save file `Ctrl + S`

```
Couldn't generate alter script

Reason:
Cannot invoke "org.jkiss.dbeaver.model.struct.DBSObject.getDataSource()" because "object" is null
```

**Comment by E1izabeth** [comment]
Thank you for bug report.
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by E1izabeth** [comment]
Thank you for bug report. Does it stable reproducible? I'm unable to reproduce it for now.
The error from logs:
```
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.model.struct.DBSObject.getDataSource()" because "object" is null
	at org.jkiss.dbeaver.model.DBUtils.getQuotedIdentifier(DBUtils.java:95)
	at org.jkiss.dbeaver.ext.mssql.edit.SQLServerObjectManager.addDatabaseSwitchAction2(SQLServerObjectManager.java:46)
	at org.jkiss.dbeaver.ext.mssql.edit.SQLServerProcedureManager.createOrReplaceProcedureQuery(SQLServerProcedureManager.java:110)
	at org.jkiss.dbeaver.ext.mssql.edit.SQLServerProcedureManager.addObjectModifyActions(SQLServerProcedureManager.java:86)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor$ObjectChangeCommand.getPersistActions(SQLObjectEditor.java:371)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.lambda$4(EntityEditor.java:539)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
```

**Comment by jrmejiaa** [comment]
Hi @E1izabeth, yes the error happens in every save. I tried removing the connection, removing the application, install the last version of the app, but I got always the same result. I upload the Issue message with the version of the driver that I used to connect to the server. 

```bash
Linux intan 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux
```

Please let me know if I can check something else, maybe there is a dependency that is too old or too new?

Thanks for the help.

**Comment by jrmejiaa** [comment]
BTW: Editing and saving data from tables directly in the GUI seems to be working without problem

**Comment by E1izabeth** [comment]
We couldn't reproduce the issue, but tried to fix it by the logs.
Please try Early Access version https://dbeaver.io/files/ea/
Does it solve the issue?

**Comment by jrmejiaa** [comment]
Hi @E1izabeth, 

Thank you for your time, I really appreciate that you tried to help me in this whole process despite the fact that you could not reproduce the error. I will try to be explain what my problem was, in case that someone else would have that problem. 

#### TLTR

In order to avoid this error or the one explain bellow when you want to CREATE or ALTER a Procedure, it is necessary to set in DBeaver the DB as default. You can do this from the Database Navigator.

#### What happen?

- The SQL server that I am working on is not handled by me, but by a hosting and they use the same server for all the other web-app clients. That means that my account only have access to my specific DBs, I could see the other ones, but I could not change any information. This is specially important that I do not have access to **master** DB. 
- By default, the MS SQL Server connection focus on the **master** DB, which is by default always there.
- Because I did not have access to the master DB, but the connection in DBeaver is focus on it, I got the first error `DBSObject.getDataSource()` gets a null, because I don't have the rights to access that DB.
- With the fix made by Elizabeth, I was able to pass that point and I got a new error, where it says that the procedure does not exists. This makes me realize that in order to CREATE or ALTER a Procedure with DBBeaver it is mandatory to be focus on that DB, because a Procedure in MS SQL server is not allow to specify the database as prefix as other commands like SELECT.

```bash
SQL Error [166] [S0001]: 'CREATE/ALTER PROCEDURE' does not allow 
specifying the database name as a prefix to the object name.
```
- After setting the DB that I was working on as default, I was able to CREATE and ALTER Procedures.

Thanks again for the help and the awesome app. Happy coding!
