### ISSUE TITLE
Newly created postgres database disappears after refresh

### ISSUE THREAD

**Issue by h2cone** [dbeaver/dbeaver#35070]
### Description

![dbeaver_wsm3FUOrfV](https://github.com/user-attachments/assets/92083add-ef19-4e37-8fcc-d2eca8fb3a73)

### DBeaver Version

Version 24.1.3.202407211303

### Operating System

Windows 11

### Database and driver

PostgreSQL 16.3 and org.postgresql:postgresql:42.7.2

### Steps to reproduce

1. Create New Database
2. Refresh

**Comment by ask9** [comment]
It is by design.
Just set the checkbox "Show all databases" to true to see all available databases, otherwise only one database is shown in connection:

![изображение](https://github.com/user-attachments/assets/0d1261f4-201e-477a-bba8-9075f5f4b0c4)
