### ISSUE TITLE
Add a possibility for the grouping

### ISSUE THREAD

**Issue by tati-kru** [dbeaver/dbeaver#3507]
Add a special button for grouping at the bottom line of the grid.
When user presses this button a new panel will appear. User can drag-and-drop columns one by one from the grid to the new panel and they will be grouped automatically. User can delete the column form the grouping panel using the context menu.
By default columns will be grouped by the meaning count. But it is possible to add additional parameters for grouping from the context menu: average, max, min, etc.

**Comment by serge-rider** [comment]
Further improvements should be done in separate tickets.
![image](https://user-images.githubusercontent.com/6398845/40827534-86d3d978-6586-11e8-9e5d-dcceace99907.png)
