### ISSUE TITLE
"Execute script" on multiple databases

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35078]
Sometimes it is useful for a user to execute the same script on multiple databases at once.
I suggest to not disallow doing it for a user (as it is now):

https://github.com/user-attachments/assets/34095550-b337-454e-a438-739de9bf23d3

Ideally, scripts could be started simultaneously in different threads on different databases or sequentially (add some form where user can set it somehow).

**Comment by E1izabeth** [comment]
Thank you for the idea.
It's a duplicate of #34071
You can vote for the mentioned issue with 👍 under the issue description to promote it to a higher priority.
