### ISSUE TITLE
Pinned Tab is being replaced by new query

### ISSUE THREAD

**Issue by settify-mattweston** [dbeaver/dbeaver#35072]
### Description

Expected behaviour: 
Pinning a tab, then running another query would open result for new query in a seperate tab. 

Current behaviour: 
It no longer does this, after pinning the tab the new query replaces the previously pinned tab.

### DBeaver Version

Community Version 24.1.4.202408041450

### Operating System

macOS Sonoma 14.5

### Database and driver

Mysql 8.2.0 Driver

### Steps to reproduce

Run first query:
```select 'hi there' data from dual;```

Pin the result windows

Run second query:
```select 'hi again' data from dual;```

Pinned tab is replaced, no new tab is opened.

### Additional context

Was able to replicate this against database on local machine and remote via socks tunnel

**Comment by iboruk** [comment]
The same behaviour with pinning for the Operating System - Windows 11

**Comment by m3n3chm0** [comment]
Dear all guys,

The same situation here on a Windows 11 machine. It’s very annoying and has been happening since this version:

Version 24.1.4.202408041450

![image](https://github.com/user-attachments/assets/71b72fd1-8db6-43e9-a2ab-638d526ef3ca)

**Comment by JTMosaic** [comment]
Rolled back to 24.1.3 due to this bug

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
We fixed this bug.
You can try Early Access version with fix (https://dbeaver.io/files/ea/) or wait for the next release
