### ISSUE TITLE
Sometimes progressbar is spinning indefinintely after error on executing a query

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35082]
### Description

I don't remeber certain steps to reproduce. 
I executed some queries, then the error occurs and the progressbar started spinning indefinitely.
On the script below you can see the progress bar doesn't stop spinning even if I execute another query in the tab.

https://github.com/user-attachments/assets/65d3b259-e493-486e-9c6e-8ff9ef932c07

By the way, `pg_stat_activity` has no any active transactions (running queries) to this database.
Maybe some check for Null should be added based on information from stack of this error message for better error handling?
It would be enough for this issue since I can't reproduce it but I've managed to caught it somehow.

<details><summary>Stack info</summary>
<p>

> 
> eclipse.buildId=unknown
> java.version=17.0.6
> java.vendor=Eclipse Adoptium
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
> Framework arguments:  -eclipse.keyring C:\Users\user1\AppData\Roaming\DBeaverData\secure\secure_storage
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.eclipse.e4.ui.workbench
> Error
> Execution exception for: ParameterizedCommand(Command(org.jkiss.dbeaver.ui.editors.sql.run.script,Execute SQL script,
> 		Execute script,
> 		Category(org.jkiss.dbeaver.core.sql,SQL Editor,SQL Editor Commands,true),
> 		WorkbenchHandlerServiceHandler("org.jkiss.dbeaver.ui.editors.sql.run.script"),
> 		,,true),null) in 
> 	context chain: WorkbenchContext -> TrimmedWindowImpl (IDEWindow) Context -> PerspectiveImpl (org.jkiss.dbeaver.core.perspective) Context -> PartImpl (org.eclipse.e4.ui.compatibility.editor)  removeOnHide org.jkiss.dbeaver.ui.editors.sql.SQLEditor active activeOnClose (<.dvd> Script-307) Context
> 
> org.eclipse.core.commands.ExecutionException: Error executing 'org.jkiss.dbeaver.ui.editors.sql.run.script': java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryProcessor.getFirstResults()" because "this.curQueryProcessor" is null
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:179)
> 	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
> 	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:569)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:644)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:439)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
> 	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1294)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1159)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1184)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1169)
> 	at org.eclipse.swt.widgets.Control.traverse(Control.java:4219)
> 	at org.eclipse.swt.widgets.Control.translateMnemonic(Control.java:4069)
> 	at org.eclipse.swt.widgets.Composite.translateMnemonic(Composite.java:1255)
> 	at org.eclipse.swt.widgets.Control.translateMnemonic(Control.java:4087)
> 	at org.eclipse.swt.widgets.Display.translateMnemonic(Display.java:4950)
> 	at org.eclipse.swt.widgets.Display.filterMessage(Display.java:1312)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3669)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
> 	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:291)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:648)
> 	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:608)
> 	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1459)
> Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryProcessor.getFirstResults()" because "this.curQueryProcessor" is null
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:299)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:233)
> 	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
> 	... 41 more
> Caused by: java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryProcessor.getFirstResults()" because "this.curQueryProcessor" is null
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.processQueries(SQLEditor.java:2779)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.processSQL(SQLEditor.java:2590)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.processSQL(SQLEditor.java:2510)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.processSQL(SQLEditor.java:2506)
> 	at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLEditorHandlerExecute.execute(SQLEditorHandlerExecute.java:65)
> 	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:277)
> 	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:98)
> 	at jdk.internal.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
> 	... 45 more
> 
> 

</p>
</details> 

### DBeaver Version

Community Edition 24.1.5-202408012322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

**Comment by TB-HunBoka** [comment]
I can confirm that I saw this issue couple days ago when I tried to reconnect to a database after a long idle time (potentially unsuccesfully, can't remember). I am not sure how, but somehow I was able to make the spinning go away. Only saw it once.

**Comment by E1izabeth** [comment]
Connected with #34901 or the same issue

**Comment by TB-HunBoka** [comment]
> Connected with #34901 or the same issue

Yes. My problem was the same as the mentioned ticket.

**Comment by E1izabeth** [comment]
We fixed this bug. You can try Early Access version https://dbeaver.io/files/ea/

**Comment by ask9** [comment]
Good news! Thanks.
Since it is difficult to reproduce for me, I believe it is fixed.
