### ISSUE TITLE
Snowflake Externalbrowser authenticator opens a browser tab in dbeaver

### ISSUE THREAD

**Issue by TB-HunBoka** [dbeaver/dbeaver#35085]
### Description

The externalbrowser authenticator mode supposed to open my default browser and log me in the Snowflake, as we use SSO system, it works without any interaction.
After the latest refresh the authenticator doesn't use my browser, but opens a popup window inside the DBeaver and ask me to login to our SSO system.

### DBeaver Version

Community Edition Version 24.1.4.202408041450

### Operating System

Windows

### Database and driver

Snowflake
I used the snowflake driver 3.14.x default one and tried with the newest 3.18.0.

### Steps to reproduce

1. Create a snowflake connection
2. Set the authenticator to externalbrowser
3. Connect to the database

### Additional context

My default browser is Microsoft Edge Version 127.0.2651.86 (Official build) (64-bit)

**Comment by Destrolaric** [comment]
![image](https://github.com/user-attachments/assets/8d242662-eb5e-44fe-8583-6c6de24e466f)
Hi, you can disable this behavior by unchecking the `interface -> open auth in embedded browser` it should not be a default behavior in this version.

**Comment by TB-HunBoka** [comment]
> ![image](https://private-user-images.githubusercontent.com/20579256/355376787-8d242662-eb5e-44fe-8583-6c6de24e466f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzgzMDksIm5iZiI6MTcyMjkzODAwOSwicGF0aCI6Ii8yMDU3OTI1Ni8zNTUzNzY3ODctOGQyNDI2NjItZWI1ZS00NGZlLTg1ODMtNmM2ZGUyNGU0NjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA5NTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNjRjMTRhYzMyMGI0ZTUyY2YyYTRiMTZhODZiNjI0YTdkOWZlNjhlMThlYjlkNTI4MzMxNTMyNjQ3NWNmZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gbo350aQYmYK-vuVGYHDUfKeH4uLEJDV__PwN-GHqRc) Hi, you can disable this behavior by unchecking the `interface -> open auth in embedded browser` it should not be a default behavior in this version.

I changed this setting, and I will check it tomorrow, but I think it will make my login work as it did before.
I was not aware of this setting changed.
Thanks.

**Comment by TB-HunBoka** [comment]
Now I can login the same way as before.
I checked the release notes, and it was not mentioned that this setting will be changed. 

I found when the default value were changed to disabled
![kép](https://github.com/user-attachments/assets/c12a63c8-3769-4ba1-bf62-5252c5530263)
And now it is enabled for windows.
https://github.com/dbeaver/dbeaver/commit/3bdd9e87e7d9ef93c00dfeeb44391593461339cd

Is this the desired final state or it is experimentally changed? I ask it because I like to teach my coworkers to use DBeaver and I have a collection of settings that I recommend them to change, so I would add this to the list as our company uses SSO, that is better supported when using the active browser instead of embeded one.

**Comment by MikeCSanJose** [comment]
I had the same issue, and after entering my Snowflake login credentials, the embedded browser says "Redirecting to Snowflake client in 1 seconds...", and it never changes or goes away.  At that point, if I click on "Open in external browser", it does open an Edge window, but fails to connect:
![2024-08-06_184923](https://github.com/user-attachments/assets/9f78a66d-efe6-4242-b19c-76cd9526c2a0)

If I then try to run my query, it runs fine, so the connection was made.  I have changed the setting, and will check tomorrow to see if there is any issue.  I would agree that the new setting change should not be the default.

**Comment by MikeCSanJose** [comment]
Since disabling "open auth in embedded browser", logon has reverted back to the way it was before the latest upgrade, and I no longer have any issues.

**Comment by arhayka** [comment]
Thank you all for the feedback. We discussed this issue with the team and decided to turn off this setting by default.
Related ticket: https://github.com/dbeaver/dbeaver/issues/34762
