### ISSUE TITLE
When will support for gbase8s databases be added? 

### ISSUE THREAD

**Issue by marsapolo** [dbeaver/dbeaver#35087]
If I want to adapt GBase 8s to be added to DBeaver like OceanBase, do I need to apply for anything?
website:        
https://www.gbase.cn/

Database download link.
https://www.gbase.cn/download/gbase-8s-1?category=INSTALL_PACKAGE

**Comment by E1izabeth** [comment]
Currently it's not planned to any concrete day. However, we're open for contribution.

**Comment by marsapolo** [comment]
dbeaver is a great product.
We strongly hope to add our database product, GBase 8s, added to  dbeaver for showcase.
Like many China database vendors, GBase 8s has a relatively high market share.
Adding an excellent product can bring a better experience to users.
If we want to make this plan happen, do we want to do something first?

**Comment by marsapolo** [comment]
![chinaDatabase](https://github.com/user-attachments/assets/6e632891-3008-4a76-bf0f-0c1d85c075b6)

**Comment by E1izabeth** [comment]
Here is our guide for contributors https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code
And guides for setting up development environment in IDEA https://github.com/dbeaver/dbeaver/wiki/Develop-in-IDEA or Eclipse https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse

**Comment by marsapolo** [comment]
Thx, I went to learn these URL

**Comment by marsapolo** [comment]
Hi，@E1izabeth
We will contribute support for GBase 8s，
As mentioned in a previous article,“Before creating a pull request, you should create a ticket on our issue tracker. ”
Do we need to create another ticket, or just use this ticket #35087 ？

**Comment by E1izabeth** [comment]
Please, use this issue. No need to create another one

**Comment by marsapolo** [comment]
This address is our website, and it is in Chinese. https://www.gbase.cn/
Do I need to provide an English version of the website?
Is this a mandatory prerequisite?

**Comment by E1izabeth** [comment]
@marsapolo it's not a mandatory requirement. No need to provide English version right now.

**Comment by marsapolo** [comment]
Got it. 
We plan to submit the contribution code in about two weeks. 
Should we follow the steps provided on the website https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code, or is there anything else we need to do before that?

**Comment by E1izabeth** [comment]
No, just create Pull Request :)
