### ISSUE TITLE
SQLCipher v4 issue with Dbeaver and UUID fields (after Dbeaver version: 22.3.1)

### ISSUE THREAD

**Issue by frllnr** [dbeaver/dbeaver#35089]
### Description

Connecting to a ciphered SQLite database via Dbeaver, the values stored in UUID fields are shown as numbers.

**The problem does not occur with DBEAVER versions up to 22.3.1.202212251901**

Table structure:
![1](https://github.com/user-attachments/assets/1ad305d1-21d3-40b5-a10b-3e48d34c463f)

Shown data vs Real data:
![2](https://github.com/user-attachments/assets/20321b22-69f3-4bb4-9b89-4801cb03bffc)

Expected behavior:
I expected to see the data stored in UUID type fields as shown in "REAL_DATA" column, as was in versions before or equal to 22.3.1.202212251901

### DBeaver Version

Community Edition 24.1.3

### Operating System

Windows 10 x64

### Database and driver

Driver: sqlite-jdbc version 3.46.0.0

### Steps to reproduce

Driver settings:
![3](https://github.com/user-attachments/assets/b36fd558-52a1-4518-abd8-1cebf583c888)

**Comment by E1izabeth** [comment]
I reproduced the issue

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by ShadelessFox** [comment]
Hello @RobertoF-80,

Can you please try the early access version to see if it works there? https://dbeaver.io/files/ea/

Thank you.

**Comment by frllnr** [comment]
Hello @ShadelessFox @arhayka,
   I tried it and now it works as I expected

   great job, thank you ;)
