### ISSUE TITLE
BigQuery: Number format not following Data Format Options 

### ISSUE THREAD

**Issue by jeff-bradley** [dbeaver/dbeaver#35092]
### Description

I have tried to adjust the Number format for Bigquery datasource but it seems that no options are being respected in the UI. I would like to add commas, and have tried changing all the options but nothing seems to make a difference with the Data Formats for Numbers. 

![image](https://github.com/user-attachments/assets/d5101576-7803-44b4-be95-c9ca74c559f6)

### DBeaver Version

Enterprise 24.1.0

### Operating System

Windows 11

### Database and driver

Driver name: Google BigQuery

### Steps to reproduce

Open BigQuery Table in Data Editor
Click Configure Gear
Click Editors> Data Editor> Data Formats
Make and changes to Format type Number settings. 
Hit Refresh on the bq table, and nothing changes.

### Additional context

Also Timestamps do change but its confusing with BQ DateTime formats being changed to TIMESTAMP UTC but that is a different issue.

**Comment by uslss** [comment]
Thanks for the report.
What exactly do you want to change in number formatting?
For me, separators change according to local.

https://github.com/user-attachments/assets/69de7b8d-af0a-4784-9372-aeff7ec2fbdc

**Comment by jeff-bradley** [comment]
Hey @uslss that works for all my other my other data sources just like in your video but for BigQuery ones I can never get the numbers to have commas.

**Comment by ShadelessFox** [comment]
Hello @jeff-bradley,

Can you please record a video showing the issue and how you change formatting settings?

**Comment by E1izabeth** [comment]
Unfortunately, we have not been able to reproduce the reported behavior. Therefore, I am closing this issue. Please provide a video showing the issue.
We will reopen it if we receive a similar report from another user or can reproduce the issue in the future.
