### ISSUE TITLE
Export Data to CSV - The size of the "Data Transfer" pop-up window expands beyond the screen width if the Directory path is long

### ISSUE THREAD

**Issue by scokna4gh** [dbeaver/dbeaver#35102]
### Description

When exporting the query results to CSV, the size of the [**Data Transfer** pop-up window expands beyond the screen width](https://app.screencast.com/9Gl8WwS6dZVY3) on the **Output** and **Confirm** steps if the **Directory** path is long.

### DBeaver Version

DBeaver Community 24.1.4

### Operating System

macOS Sonoma - Version 14.5 (23F79)

### Database and driver

1. mysql-8.0.33-macos13-arm64
2. jdbc:mysql

### Steps to reproduce

[https://app.screencast.com/9Gl8WwS6dZVY3](https://app.screencast.com/9Gl8WwS6dZVY3)

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by serge-rider** [comment]
Fixed. Also vertical dimensions were fixed to avoid dialog resize. So now bottom buttons should be on the same position on all pages.

**Comment by scokna4gh** [comment]
Thanks, Serge! :-)  When will this fix be deployed?

**Comment by MashaKorax** [comment]
Hello @scokna4gh  this fix will be deployed at 1 September in release 24.2.0.  Or tomorrow night it will be in early access here https://dbeaver.io/files/ea/

**Comment by scokna4gh** [comment]
I downloaded the latest version of DBeaver today (v 24.2.0) and see the wonderful updates to the CSV Export process. Thanks @serge-rider!

**Comment by robroy73** [comment]
Hello I'm on 25.0.2 and I am still running into that exact same issue that has been described prior to this 24.0.2 release.  Thanks.
