### ISSUE TITLE
Right Click menu got triggered when using SQL Query Execute shortcut (^ + Enter)

### ISSUE THREAD

**Issue by pietsteph** [dbeaver/dbeaver#35109]
### Description

When I perform the SQL Query Execute shortcut (^ + Enter), the right click menu got triggered. It kind of annoying.

<img width="637" alt="image" src="https://github.com/user-attachments/assets/b338a44c-fd62-4d3d-b35b-c2ce1ef4acd0">

https://github.com/user-attachments/assets/9504a77e-165f-48ae-a8b6-a6957ed19964

I'm pretty sure it's not because the OS, it was happened even when I was on macOS Sonoma before. I thought it was just a bug that will be fixed in the future, but this kind of bug never happened to my office Mac. What happened to my dbeaver?

### DBeaver Version

24.1.4.202408041450

### Operating System

macOS Sequoia 15.1

**Comment by TB-HunBoka** [comment]
Could you please check the keys preferences and check if the Show Context Menu has any key combination assigned?
Also check the Show key binding when command is invoked - Through keyboard box, and repeate the issue. This will tell you if it triggered any keyboard command.

**Comment by pietsteph** [comment]
Show Context Menu is invoked by Shift+F10 (Shift+fn+F10 on macOS).
<img width="741" alt="image" src="https://github.com/user-attachments/assets/d8b3042d-c5f0-4e77-989e-cfc01be523f3">


https://github.com/user-attachments/assets/697f9178-fa80-4eab-aef8-f7dd602140dc

**Comment by pawelwalat** [comment]
It started when I upgraded to macOS Sequoia 15.0.
Dbeaver version: Version 24.1.1.202406231636

**Comment by pawelwalat** [comment]
OK.. It looks like it is a new shortcut in Squoia. Once disabled, it works as expected.
![image](https://github.com/user-attachments/assets/51b55888-1677-4717-87e5-ebba58733886)

**Comment by MashaKorax** [comment]
@pawelwalat Thanks for your help and investigation.

**Comment by mohangbits** [comment]
This worked for me. Thank you @pawelwalat 

For anyone unable to find this settings, go to System Settings --> Keyboard (scroll down on the left) --> Keyboard Shortcuts (opens a popup) --> Select Keyboard (from the left menu in the popup) --> Uncheck "Show contextual menu"

**Comment by wanwoochang** [comment]
Thank you for the help @pawelwalat!

**Comment by shinyzhu** [comment]
Annoyed me a lot. But thanks for the work around. :)

**Comment by SalvadorAlonsoOrtega** [comment]
thanks @pawelwalat !

**Comment by cagataybulanik** [comment]
thank you!

**Comment by serge-rider** [comment]
I think we can use another default shortcut for query execution on MacOS.
Something like <kbd>CMD+Enter</kbd>

**Comment by akgkfk3** [comment]
thanks @pawelwalat !!!

**Comment by Umar-elGrocer** [comment]
> OK.. It looks like it is a new shortcut in Squoia. Once disabled, it works as expected. ![image](https://private-user-images.githubusercontent.com/3890439/360791946-51b55888-1677-4717-87e5-ebba58733886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5Nzg0MjMsIm5iZiI6MTczMDk3ODEyMywicGF0aCI6Ii8zODkwNDM5LzM2MDc5MTk0Ni01MWI1NTg4OC0xNjc3LTQ3MTctODdlNS1lYmJhNTg3MzM4ODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMTExNTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZThmNjUwOGExNmYzNmFiN2FjYWY3YTE2MzY4MWJjZTM0M2RhMWU0MWFmOWE0ZThhNGU1YzY1N2NmYzc2NWY3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.d04JWpVR35NvrVt4jeapiECqeZavS05COB0S4QJ3Hz4)

@pawelwalat Amazing 👌🏽

**Comment by Remi-C** [comment]
Thank people, it was so annoying !

**Comment by Qaddooomz** [comment]
Thank you for your help! @pawelwalat

**Comment by alexzaharia24** [comment]
@pawelwalat Thank you 🚀

**Comment by yuriscom** [comment]
Thank you! It was very annoying.
