### ISSUE TITLE
Dropdown list not showing

### ISSUE THREAD

**Issue by sevaus** [dbeaver/dbeaver#3510]
Hello,

Whenever I create an alias for a table, the dropdown list stops showing (I'm talking about this https://imgur.com/a/aAtNQde).

I didn't find anything helpful in Preferences.

Any help?

**Comment by uslss** [comment]
hi @sevaus , is issue still actual for you in recent version?

**Comment by Lori753** [comment]
I have the same problem.  If I use a fully qualified table name, I get a drop down list.  If I alias a table, no drop down list.  My Preferences settings match my coworker's who can use table aliases successfully.  I took screen shots but unfortunately cannot upload them.

**Comment by Lori753** [comment]
Hi @sevaus ,  did you find out how to get table aliases to work?  @uslss , do you have any suggestions?  Thanks!

**Comment by uslss** [comment]
seems that issue is already solved in recent (6.3.5) version
![image](https://user-images.githubusercontent.com/31996417/75150317-2a126600-5715-11ea-92eb-dc6d76cd4c06.png)
Ticket will be closed. If it is still actual for you - feel free to reopen the ticket

**Comment by uslss** [comment]
@Lori753 probably you've got "Blank line is statement delimiter" option enabled
![image](https://user-images.githubusercontent.com/31996417/75162220-3ce56480-572e-11ea-8cd3-9186614aecf4.png)

**Comment by Lori753** [comment]
@uslss you're correct, I did have that option selected.  So happy to finally have alias ability!  Thanks for starting my week off right!
