### ISSUE TITLE
Unable to install DBeaver Debugger

### ISSUE THREAD

**Issue by bfree-github** [dbeaver/dbeaver#35121]
### Description

Attempting to install DBeaver Debug (via Help > Install New Software: https://dbeaver.io/update/debug/latest/) results in the following error report:

Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver Debug 6.1.126.202408041450 (org.jkiss.dbeaver.debug.feature.feature.group 6.1.126.202408041450)
  Missing requirement for filter properties ~= $0: DBeaver Debug 6.1.126.202408041450 (org.jkiss.dbeaver.debug.feature.feature.group 6.1.126.202408041450) requires 'org.eclipse.equinox.p2.iu; org.eclipse.debug.ui 0.0.0, filter=(!(org.eclipse.equinox.p2.exclude.import=true))' but it could not be found

I'm running on Ubuntu 22.04 and Postgres 16 + /usr/lib/postgresql/16/lib/plugin_debugger.so

### DBeaver Version

Version 24.1.4.202408041450

### Operating System

Ubuntu 22.04.4 LTS

### Database and driver

PostgreSQL 16.3
Whatever driver DBeaver uses

### Steps to reproduce

Help > Install New Software

Enter: https://dbeaver.io/update/debug/latest/

Add

**Comment by E1izabeth** [comment]
Do you use standalone DBeaver application or Eclipse plugin?

**Comment by E1izabeth** [comment]
For now, we're unable to reproduce the issue

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
