### ISSUE TITLE
oracle 9i package compilation issue (Non supported SQL92 token at position: 238128: Sub)

### ISSUE THREAD

**Issue by reddyshyam** [dbeaver/dbeaver#3512]
Hi, 

Before anything thank you for excellent front end for major databases. Just today I stumbled upon the issue where trying to compile a package on Oracle9i Release 9.2.0.8.0 - 64bit is causing the below error.  

SQL Error [17034]: Non supported SQL92 token at position: 238128: Sub
  Non supported SQL92 token at position: 238128: Sub
  Non supported SQL92 token at position: 238128: Sub

Can you help resolve the issue please? Works fine on Toad Free v12.12. Checked both on 5.0.5 CE and also 5.0.6 EA. I am on Windows 10 RS4 64 bit latest.

**Comment by serge-rider** [comment]
Perhaps there is some issue with PL/SQL parsing. Could you post problem package test? Here or on serge@jkiss.org.

Workaround: select full package text and execute it with ctrl+enter.

**Comment by aplewe** [comment]
I have the same issue; I'm trying to compile this from a public github repository:

```
create or replace and compile java source named "Geohash"
as
package com.test;
import java.util.BitSet;

public class Geohash {
static int numbits = 30;
static char[] digits = { '0', '1', '2', '3', '4', '5', '6', '7', '8',
            '9', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'j', 'k', 'm', 'n', 'p',
            'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z' };

 public static String encode(double lat, double lon,int geolength) {
        BitSet latbits = getBits(lat, -90, 90);
        BitSet lonbits = getBits(lon, -180, 180);
        StringBuffer buffer = new StringBuffer();
        for (int i = 0; i < numbits; i++) {
            buffer.append( (lonbits.get(i))?'1':'0');
            buffer.append( (latbits.get(i))?'1':'0');
        }

        return base32(Long.parseLong(buffer.toString(), 2)).substring(0,geolength);
    }
    
 public static BitSet getBits(double lat, double floor, double ceiling) {
        BitSet buffer = new BitSet(numbits);
        for (int i = 0; i < numbits; i++) {
            double mid = (floor + ceiling) / 2;
            if (lat >= mid) {
                buffer.set(i);
                floor = mid;
            } else {
                ceiling = mid;
            }
        }
        return buffer;
    }

 public static String base32(long i) {
        char[] buf = new char[65];
        int charPos = 64;
        boolean negative = (i < 0);
        if (!negative)
            i = -i;
        while (i <= -32) {
            buf[charPos--] = digits[(int) (-(i % 32))];
            i /= 32;
        }
        buf[charPos] = digits[(int) (-i)];

        if (negative)
            buf[--charPos] = '-';
        return new String(buf, charPos, (65 - charPos));
    }
}
```

When I select this text as a block and do ctrl+enter, I get "non supported SQL92 token at position: 1210". Specifically, I think DBeaver's parser doesn't like "--", but that's just a guess.

**Comment by serge-rider** [comment]
It is Oracle-specific issue (https://stackoverflow.com/questions/16141737/create-java-on-oracle-database-with-jdbc)
Will be fixed in the next version, thanks for bug report and sample SQL snippet.

**Comment by reddyshyam** [comment]
Hi serge-rider,

I tested the latest EA dated Aug 9th and can now compile the package earlier I reported was not compiling. Has the fix gone in? Just confirming,

**Comment by serge-rider** [comment]
Yes, it is in EA.
