### ISSUE TITLE
Running one SQL is OK, running multiple SQL exceptions;

### ISSUE THREAD

**Issue by 91hm** [dbeaver/dbeaver#35122]
### Description

Running one SQL 
```
UPDATE `label`.`label` SET `code` = 'C10015', `kind_code` = 'C1', `name` = 'busiAuthCheckMonitor', `desc_name` = '业务_是否监听', `inter_code` = '', `label_update_time` = NULL, `ef_duration_time` = 172800, `label_data_type` = 'VALUE', `is_save_history` = 1, `description` = NULL, `create_by` = 'system', `create_time` = '2023-04-27 07:34:32', `update_by` = 'system', `update_time` = '2023-04-27 07:34:32', `is_del` = 0 WHERE `id` = 1651369194534469708;

```
<img width="1897" alt="image" src="https://github.com/user-attachments/assets/e1851976-2882-4cd7-bbd4-9837d3e22866">

running multiple SQL exceptions
```
UPDATE `label`.`label` SET `code` = 'C10015', `kind_code` = 'C1', `name` = 'busiAuthCheckMonitor', `desc_name` = '业务_是否监听', `inter_code` = '', `label_update_time` = NULL, `ef_duration_time` = 172800, `label_data_type` = 'VALUE', `is_save_history` = 1, `description` = NULL, `create_by` = 'system', `create_time` = '2023-04-27 07:34:32', `update_by` = 'system', `update_time` = '2023-04-27 07:34:32', `is_del` = 0 WHERE `id` = 1651369194534469708;
UPDATE `label`.`label` SET `code` = 'H10001', `kind_code` = 'H1', `name` = 'agentIdVc', `desc_name` = '座席_工号', `inter_code` = NULL, `label_update_time` = NULL, `ef_duration_time` = 172800, `label_data_type` = 'VALUE', `is_save_history` = NULL, `description` = NULL, `create_by` = 'system', `create_time` = '2023-05-25 10:49:51', `update_by` = 'system', `update_time` = '2023-05-25 11:38:13', `is_del` = 0 WHERE `id` = 1661565208147003349;

```
<img width="1689" alt="image" src="https://github.com/user-attachments/assets/9bd19906-978d-431f-989b-da382cc6fe8a">

```
SQL 错误 [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UPDATE `label`.`label` SET `code` = 'H10001', `kind_code` = 'H1', `name` = 'agen' at line 2
```

### DBeaver Version

24.1.2.202407071610

### Operating System

windwos 10

### Database and driver

mysql8.4.0.jar
<img width="703" alt="image" src="https://github.com/user-attachments/assets/b7e8d509-f787-401c-8fa0-461d5e2bfc47">

### Steps to reproduce

1.create database;
```
CREATE TABLE `label` (
  `id` bigint(20) NOT NULL,
  `code` varchar(255) NOT NULL,
  `kind_code` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `desc_name` varchar(255) NOT NULL,
  `inter_code` varchar(255) DEFAULT NULL,
  `label_update_time` datetime DEFAULT NULL,
  `ef_duration_time` bigint(20) NOT NULL,
  `label_data_type` enum('VALUE','MAP','LIST') NOT NULL,
  `is_save_history` tinyint(1) DEFAULT NULL,
  `description` text,
  `create_by` varchar(255) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(255) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `is_del` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `kind_idx` (`kind_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

**Comment by E1izabeth** [comment]
Please use this button to execute multiple queries.
![image](https://github.com/user-attachments/assets/ea31ee0d-a262-48ae-b3bd-3c69803d483e)

When you select something, DBeaver send this text as is to the database for execution. MySQL database can't execute such query.

**Comment by 91hm** [comment]
I tried, but it was wrong
1. use database  label   error
<img width="728" alt="image" src="https://github.com/user-attachments/assets/42101975-5522-4ce0-8b3d-fcfd05091b5a">
<img width="435" alt="image" src="https://github.com/user-attachments/assets/1fa6f935-08ad-44c7-aaeb-80d12d200cef">

2. run  
```
use label;  
```
database changer;

<img width="598" alt="image" src="https://github.com/user-attachments/assets/2ba05a82-9128-4d6c-998b-6def96d4fe87">

4.  The environment does not have an external network, and the jar package is imported offline
<img width="1609" alt="image" src="https://github.com/user-attachments/assets/2bf0b1f7-6e5e-4f0f-baf9-9c3f923df2ab">

**Comment by E1izabeth** [comment]
Is this issue stable-reproducible? Seems that the connection to the database was lost. Does reconnect helps?

**Comment by 91hm** [comment]
> Is this issue stable-reproducible? Seems that the connection to the database was lost. Does reconnect helps?

It has always been such a problem, can be repeated, the software is installed offline; Drive manual import;

**Comment by E1izabeth** [comment]
Please try executing script without selecting the text.

**Comment by 91hm** [comment]
> Please try executing script without selecting the text.

没有用哦,选中执行还是异常哦;

我描述还不清楚吗

**Comment by E1izabeth** [comment]
For now, we can't reproduce the issue.
Could you tell me your driver and server version? You can get this information by clicking `Test connection...` button in the `Connection configuration` dialog.
![image](https://github.com/user-attachments/assets/1f32a413-22a4-43fd-adc1-375468be2e48)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
