### ISSUE TITLE
[CUBRID] Issue with about transaction(log) in 'Keep Alive' when Autocommit is false.

### ISSUE THREAD

**Issue by hwany7seo** [dbeaver/dbeaver#35120]
If you set 'Keep Alive' and 'autocommit' to false, When not used for a long period of time, transaction(log) accumulate occurs. (Because every 'SQL Editor's connection' sends a 'Keep Alive')

Similar or identical issues are expected to occur in other databases.
(when database overriding 'testsql')

To this end, we offer the following suggestions:

1. Request to modify isConnectionAlive inside the JDBCUtils class.
Even if testSQL is defined, We want to execute 'conntion.isValid' first.
<img src="https://github.com/user-attachments/assets/b8b3e831-98a7-4f89-bd96-cbd0438ef79d" width=50% height=50%>

2. Let's create a PR by overriding 'checkContextAlive' just for Cubrid. This creates duplicate code.

3. We want to use 'select 1' , but Let's create a PR by delete 'testsql' defind again for Cubrid . No duplicate code is not created.

Would like advice.
Best Regard.

**Comment by E1izabeth** [comment]
Thank you for asking. We will discuss and let you know

**Comment by E1izabeth** [comment]
We suggest to set test sql to empty string for Cubrid.
