### ISSUE TITLE
Add Arabic Support for Localization 

### ISSUE THREAD

**Issue by KawtharAlakri** [dbeaver/dbeaver#35128]
**Is your feature request related to a problem? Please describe.**
There is no Arabic support. 

**Describe the solution you'd like**
Add localization for Arabic.

I would like to work on this by myself.

**Comment by ShadelessFox** [comment]
Hello @KawtharAlakri,

We have a localization guide that might be worth reading: https://github.com/dbeaver/dbeaver/wiki/Localization

**Comment by Matvey16** [comment]
I don't think we need to close this ticket because in 3 linked PRs it feels like not even 20% of everything is translated
