### ISSUE TITLE
Some keys/hotkeys are blocked in the area-selection-mode (Alt + Shift + A) when nothing selected

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35129]
### Description

I'm not sure if it is by design or not.
But pressing Enter is blocked after pressing a hotkey: Alt + Shift + A

Actually, I don't see a lot of reasons to block it in this mode.
How necessary it is for this mode **if nothing has been selected yet**?
By the way, some other hotkeys are also blocked, for example, Ctrl + Backspace, if click was done somewhere in empty space where there is no symbols.
Seems like it is OK to block it when some area is selected but not when nothing selected.

### DBeaver Version

Community Edition 24.1.3-202407162322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

- press Alt + Shift + A.
- left mouse click somewhere in a text of any query in sql editor (don't select any text)
- press Enter (imagine, at the last moment user decided to do some little edit in the sql query)

Expected: a new line is added (since no area selected - no problems to add it in spite of current mode)
Actual: a new line is not added

**Comment by TB-HunBoka** [comment]
This functionality if inherited directly from Eclipse, and it works the same in both app.
I think you have to reach out to the eclips Git repo to change this behavior. I am not sure how should the Enter/Return work in this situation. If you would like to insert a line after the selection, that works with shift+enter.

If I move the cursor with arrows, then it works normally.

**Comment by ask9** [comment]
OK. I close it due to Eclipse platform inheritance.
