### ISSUE TITLE
Datadrid resultSet limit should be ignored, or optionally turned off for SQL queries.

### ISSUE THREAD

**Issue by mrforsythexeter** [dbeaver/dbeaver#35134]
I'm always frustrated when I run an SQL query which is slow, and the datagrid has limited the fetch size to 200, so I have to request all results or page slowly to get them.

I would like an SQL query to return ALL results without having to query again, showing getting to the answers.

I have set the resultset to 0, however then a large tables crash DBeaver on viewing the 'data' tab. Other solutions I use to query a database DO NOT limit my result set.

**Comment by arhayka** [comment]
By default DBeaver Community has maximum memory limit 1gb.
You can increase this limit in dbeaver.ini file.
Try to change -Xmx1024m into -Xmx4096m to increase maximum memory to 4Gb.
https://github.com/dbeaver/dbeaver/wiki/Configuration-files-in-DBeaver#dbeaverini

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
