### ISSUE TITLE
"Execute SQL script" does not always work first time after upgrade to Version 24.1.4.202408041450

### ISSUE THREAD

**Issue by MikeCSanJose** [dbeaver/dbeaver#35135]
### Description

This is happening many times a day since the upgrade, but I have not been able to identify the exact sequence of events to duplicate it.  I write long scripts made up of Temp Table creation queries (each preceded by a DROP of that same Temp Table), which cascade one to the next.  So, I will often highlight a single (DROP + query that creates a Temp Table) script and will click the "Execute SQL script" icon.  Estimating about 1 out of every 3 or 4 times I do this, after waiting longer than I expected, I'll look at the screen and see the area is still highlighted, but there are no right pointing arrowheads on the left edge of the editor.  I'll click the "Execute SQL script" icon again, and execution will start.  I go through this process a hundred or more times every day, so it is very ingrained - highlight query then click Execute.

I hesitated to post since I have not been able to reliably duplicate it, and have been checking ISSUES to see any similar problems.  But since it has been happening so much and only after the most recent upgrade, I wanted to submit it anyway.  I will continue trying to identify some sequence of events that cause it.

### DBeaver Version

Version 24.1.4.202408041450

### Operating System

Windows 10 Enterprise  Version:22H2  Build:19045.4651

### Database and driver

Driver: Snowflake

### Steps to reproduce

I have not been able to reliably duplicate the steps, but it is happening many time every day.

**Comment by MikeCSanJose** [comment]
Prior to the latest upgrade, if I was re-running an SQL script using "Execute SQL script", I would get the message:

![image](https://github.com/user-attachments/assets/8f89e1f2-cc7c-4815-b763-e4d37dbab7f1)

I would click "Yes", the message would close and the script would run.

Now, after the latest upgrade, when I hit "Yes", the message closes, but the script does not run, I have to run it a second time.

Code used to duplicate it:

USE XXXXXX.YYYYYY ;    -- USE database/schema that you have write access to

DROP TABLE IF EXISTS T_Temp_Table_Name ;
CREATE TEMPORARY TABLE T_Temp_Table_Name as
(
		select 'Junk'		as "Dummy Output"
) ; 

select * from T_Temp_Table_Name ;

Steps to duplicate:
1. Click icon to "Execute SQL script" - should execute fine the first time
2. Click icon to "Execute SQL script" - message box opens to "Close extra results tabs"
3. Click "Yes" - message closes, but script does not run
4. Click icon to "Execute SQL script" - should execute fine

**Comment by E1izabeth** [comment]
Thank you for bug report. I reproduced the issue.

**Comment by E1izabeth** [comment]
@MikeCSanJose you can try Early Access version with the fix https://dbeaver.io/files/ea/
