### ISSUE TITLE
MSSQL JDBC driver issues

### ISSUE THREAD

**Issue by leezm** [dbeaver/dbeaver#3513]
I used the latest 6.4 version, after the change data saved prompt error; then I replaced the driver for 6.0, CURD no problem, but some SQL can not be implemented, can use SSMS (after all, the official ...) , For example, the SQL for checking the table and the field Description does not pass... There is a “Description” column after each field that is empty. If you can directly display the field comment, you do not need the SQL statement. Version 6.4 And the 6.0 version of the driver is so

**Comment by serge-rider** [comment]
I'm not sure I fully understand the question.
Could you post some examples of queries which are not working? 
Or the problem is in metadata reading?

**Comment by leezm** [comment]
@serge-rider OK.The following SQL can run in navicat and SSMS,but can't run in dbeaver 5.0.6(my jdbc driver's version is 6.2.2):
SELECT
A.name AS table_name,
B.name AS column_name,
C.value AS column_description
FROM sys.tables A
INNER JOIN sys.columns B ON B.object_id = A.object_id
LEFT JOIN sys.extended_properties C ON C.major_id = B.object_id AND C.minor_id = B.column_id
WHERE A.name = 'tableName'

**Comment by leezm** [comment]
@serge-rider next question:
Why description column is empty and can't edit?But If dbms is oracle,there's no these questions!It seems like mssql has these questions......
![tim 20180529085426](https://user-images.githubusercontent.com/24444492/40632940-978cfd36-631e-11e8-847c-afe6545f7a56.png)

**Comment by serge-rider** [comment]
@leezm Well, first query run fine in our test environment. 
Do you see some error(s)? Could you post a bit more details?

Regarding description column. Perhaps there are some issues reading non-ascee contents/driver configuration. Could you chec kerror/debug logs (https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by leezm** [comment]
@serge-rider When I run dbeaver,this message shows in then logs:
null
org.jkiss.dbeaver.model
警告
Thu May 31 16:10:11 CST 2018
Some data source listeners are still registered: [org.jkiss.dbeaver.ui.editors.sql.syntax.SQLContextInformer$1@34dff7c, org.jkiss.dbeaver.ui.editors.sql.syntax.SQLContextInformer$1@74d0d95]

Is this matter？

**Comment by uslss** [comment]
Hi @leezm ,
is issue still actual for you?

**Comment by leezm** [comment]
> Hi @leezm ,
> is issue still actual for you?

It’s ok，if use public jre,I can resolve it.But CE version I can't do it.
