### ISSUE TITLE
Some built-in system function names are colored with wrong color

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35148]
### Description

The word `regexp_substr ` is not colored with pink color (in comparison with another similar function "regexp_replace").
Please also check the full list of built-in functions in postgres docs.

- Use code:

```
select regexp_substr('1000', '1\d', 1, 1, 'i', 1);

select regexp_replace ('hello_world', 'hello', '');
```

![изображение](https://github.com/user-attachments/assets/e2c788b7-b36e-442b-9b71-e89e2916cbdc)

### DBeaver Version

Community Edition 24.1.5.202408012322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

**Comment by E1izabeth** [comment]
Thank you for bug report.
