### ISSUE TITLE
Password provided via CLI is logged in plain text 

### ISSUE THREAD

**Issue by chadmyers** [dbeaver/dbeaver#35145]
### Description

When calling dbeaver-cli.exe with the `-con` argument, the password in the connection string gets logged in its entirety in plaintext in the log file. 

I am looking at the log file: `%APPDATA%\DBeaverData\workspace6\.metadata\.log`  (yes, that's `.log`. For some reason it doesn't have a filename, only the `.log` extension)

### DBeaver Version

Community Edition 24.1.3.202407211303

### Operating System

Windows Server 2019 (1809, 17763.6054)

### Database and driver

MySQL

### Steps to reproduce

 - Call DBeaver CLI:  `"C:\Program Files\DBeaver\dbeaver-cli.exe" -data "%APPDATA%\DBeaverData\workspace6" -nosplash -con "name=Test|driver=mysql|host=TEST|database=TEST|user=TEST|password=NAUGHTY|savePassword=true|connect=false|create=true|save=true"`
  - Inspect the log file at %APPDATA%\DBeaverData\workspace6\.metadata\.log
  - Search for the word NAUGHTY

**Comment by chadmyers** [comment]
This issue was reported in 2019 (#3788) and closed due to inactivity.  I don't think it should be closed as it's a significant security concern.

**Comment by ask9** [comment]
Agree with you.
Actually, it was not about inactivity. 
Ideally, the issue should then have been reopened at the moment the user did not confirming that it had been fixed.

**Comment by kkaminsky** [comment]
see https://github.com/dbeaver/dbeaver/issues/3788#issuecomment-2294995335

**Comment by chadmyers** [comment]
Thank you @Matvey16 and @serge-rider and anyone else involved with this that I missed!
