### ISSUE TITLE
Not getting a warning if closing an SQL Script tab without saving

### ISSUE THREAD

**Issue by MikeCSanJose** [dbeaver/dbeaver#35146]
### Description

I just lost a small snippet of code because I closed the tab in the editor and did not get a warning that it was not saved.  I thought there was a warning in previous releases.

### DBeaver Version

Version 24.1.4.202408041450

### Operating System

Windows 10 Enterprise Version:22H2 Build:19045.4651

### Database and driver

Driver: Snowflake

### Steps to reproduce

1. Open a New SQL Script
2. type anything
3. close the tab

**Comment by E1izabeth** [comment]
Since DBeaver 24.1.1 the setting `Auto-save editor on close` is turned on by default.
You can turn it off in `Preferences->Editors->SQL Editor`
![image](https://github.com/user-attachments/assets/9578f26d-11f5-49b7-9e3d-18b7b28d1863)
