### ISSUE TITLE
Not working "Foreign Data wrappers configurator" whith tds_fdw

### ISSUE THREAD

**Issue by TheCHIM** [dbeaver/dbeaver#35155]
### Description

Not working "Foreign Data wrappers configurator" whith tds_fdw

![2024-08-11_16-19-01](https://github.com/user-attachments/assets/02df75fe-1836-4f6a-9865-97af54ba9008)
![2024-08-11_16-19-17](https://github.com/user-attachments/assets/5189a008-3c35-4055-af86-b627c04b048b)
![2024-08-11_16-20-09](https://github.com/user-attachments/assets/4735cc62-a953-491b-8f5d-1995c196962e)

### DBeaver Version

24.1.4

### Operating System

Windows 10 Pro x64

### Database and driver

 PostgreSQL 16.3 on x86_64-alt-linux-gnu(10.3) and MSSQL Server 16 on Windows 10 Pro (64-bit)

### Steps to reproduce

screenshots

**Comment by uslss** [comment]
thanks for the report
