### ISSUE TITLE
Foreign key links problem

### ISSUE THREAD

**Issue by fayca121** [dbeaver/dbeaver#3515]
Hello,

When you click on a foreign key link to navigate from table A to table B and you return again to table A all the links disappear from the resultset. 
 
Would it be possible to fix that?

I'm using Dbeaver 5.0.5 CE.

Thanks.

**Comment by serge-rider** [comment]
I'm not quite sure how to reproduce that (I can navigate and return back and I still see all links).
Could you post some steps to reproduce or maybe some video?

**Comment by fayca121** [comment]
Hi Serge,

here are the steps:

![2018-05-31 11_19_27-dbeaver 5 0 6 - _cbiop_ script-31](https://user-images.githubusercontent.com/547548/40777261-4bf11d14-64c5-11e8-880f-3261a29c8402.png)

I click on the link to go to the correpending table

![2018-05-31 11_20_16-dbeaver 5 0 6 - _cbiop_ script-31](https://user-images.githubusercontent.com/547548/40777321-773103ae-64c5-11e8-84c4-e610ad55cdda.png)

Then I click on the row to go back to the first table and as you can see, there are no links anymore

![2018-05-31 11_20_55-dbeaver 5 0 6 - _cbiop_ script-31](https://user-images.githubusercontent.com/547548/40777382-9856b0c4-64c5-11e8-8f2a-3875ef40d804.png)


My config is:

Dbeaver ce 5.0.6
Windows 7 x64
Oracle 11g

thanks

**Comment by serge-rider** [comment]
Thanks, now I can reproduce that.
