### ISSUE TITLE
SAP HANA DDL Functions

### ISSUE THREAD

**Issue by MatthiasBergen** [dbeaver/dbeaver#3516]
Hi!
First: Great Project :-) I'm working with dbeaver and HANA and I miss a few things. I found you added support for Procedures und Views. Can you implement Functions as well?

Here is the SQL:
SELECT SCHEMA_NAME, FUNCTION_NAME, DEFINITION FROM SYS.FUNCTIONS WHERE SCHEMA_NAME = ? and FUNCTION_NAME = ?

That would be great!
Thanks

**Comment by serge-rider** [comment]
I can't test this right now. I assume that some procedures are actually functions and have procedure type "FUNCTION". Please check fix in 5.1. It this won't help then please reopen this ticket.

**Comment by MatthiasBergen** [comment]
Hi serge-rider,

I now find it under procedures with type function like you said! thanks!

Don't know how much time it will cost for you but it is possible to show functions under functions category instead of procedures category?

thx

**Comment by serge-rider** [comment]
@MatthiasBergen good 👍 
Please create separate feature request for that.

**Comment by MatthiasBergen** [comment]
@serge-rider thx man! I did 8-)
