### ISSUE TITLE
Wiki "UI Language" page: Incorrect language code for Traditional Chinese

### ISSUE THREAD

**Issue by willy08wu07** [dbeaver/dbeaver#35160]
### Description

There are some inconsistencies in the language code table on the "UI Language" wiki page (https://github.com/dbeaver/dbeaver/wiki/UI-Language).

The issues I found are:

1. The table lists `zh` as the language code for Traditional Chinese. However, based on my testing and [source code review](https://github.com/dbeaver/dbeaver/tree/devel/plugins/org.jkiss.dbeaver.ext.mssql/OSGI-INF/l10n), the correct code for Traditional Chinese in DBeaver is actually `tw`.
2. The table also uses `zh` for Simplified Chinese. This creates ambiguity as `zh` is being used for both Traditional and Simplified Chinese.

It would be helpful if the wiki could be updated to reflect the correct language code for Traditional Chinese by changing it from `zh` to `tw`. This adjustment would align the documentation with the actual implementation and help users who wish to manually set their UI language to Traditional Chinese using the `dbeaver.ini` file.

### DBeaver Version

Community Edition 24.1.1 (Flatpak)

### Operating System

Debian GNU/Linux 12 (bookworm)

### Database and driver

N/A

### Steps to reproduce

1. Install and launch a fresh DBeaver Flatpak.
2. Notice that the UI is not in Traditional Chinese.
3. Close DBeaver.
4. Edit the file `/var/lib/flatpak/app/io.dbeaver.DBeaverCommunity/current/active/files/dbeaver/dbeaver.ini` and add the following two lines before `-vmargs` as per the Wiki instructions:
  ```
  -nl
  tw
  ```
5. Launch DBeaver again.
6. Observe that the UI has successfully changed to Traditional Chinese.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by willy08wu07** [comment]
Sorry, the issue has not been resolved. I noticed that the Wiki page did not change the Traditional Chinese "zh" to "tw".

Screenshot:
![Image](https://github.com/user-attachments/assets/8b4f1a75-a86e-4fc2-8738-d2df6960179a)

**Comment by E1izabeth** [comment]
We updated sources, but haven't published them yet.
