### ISSUE TITLE
External browser does not longer work for authentication

### ISSUE THREAD

**Issue by Aileron79** [dbeaver/dbeaver#35165]
### Description

After upgrading to 24.1.4 the external browsers does not work for authentication any more. 

### DBeaver Version

24.1.4

### Operating System

Win 11

### Database and driver

Azure SQL

### Steps to reproduce

- Configure an External Browser in Preferences => User interface => Web browser (chrome in my case)
- Configure a database connection to an Azure SQL server with MFA authentication
- Connect to that database
- The internal browser is used for authentication instead of Chrome. This worked in the previous version.

Note: I'd happily use the internal browser if it would keep the session token, but sadly I have to re-authenticate with MFA whenever I need to reconnect (after a network/database glitch, timeout, ...) which is a very time consuming process.

**Comment by E1izabeth** [comment]
Please try turning off the setting in Preferences `User interface -> Open auth in embedded browser`. Does it help?

**Comment by E1izabeth** [comment]
Similar issue about this preference default state change #35085

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.

**Comment by YuriyGavrilov** [comment]
+1 25.3.4  even if i remove every thing and reinstall ( also tried flatpak and snap and portable ) - Ubuntu  firefox

**Comment by miferrer7-cyber** [comment]
Hi, 
Had same issue today after updating to 26.1.
Tried everything and finally I fixed it restoring driver settings to default (Snowflake).
The URL template I had was somehow wrong and stopped working on this version.
