### ISSUE TITLE
SAP HANA Editor work with Parameters

### ISSUE THREAD

**Issue by MatthiasBergen** [dbeaver/dbeaver#3517]
I am having an issue working with parameters in HANA SQL Script. I can run the following simple query without problems in SAP HANA Studio:

```
DO
BEGIN
   
    DECLARE I INT = 1;
           
    IF :I = 1 THEN
      SELECT 2 FROM DUMMY;
    END IF;
   
END;
```

But when I am running this in dbeaver I am constantly getting the following error:
SQL Error [257] [HY000]: SAP DBTech JDBC: [257] (at 110): sql syntax error: line 8 col 9 (at pos 110)
SQL Error [257] [HY000]: SAP DBTech JDBC: [257] (at 110): sql syntax error: line 8 col 9 (at pos 110)
  SQL Error [257] [HY000]: SAP DBTech JDBC: [257] (at 110): sql syntax error: line 8 col 9 (at pos 110)
    SAP DBTech JDBC: [257] (at 110): sql syntax error: line 8 col 9 (at pos 110)
    SAP DBTech JDBC: [257] (at 110): sql syntax error: line 8 col 9 (at pos 110)

At the beginning I always got a prompt for named parameters because of ':I' in my sql script. I changed that in the properties and now I am stucked at the error mentioned above. 

Am I doing something wrong? How do you parse the query to the server?

Thank you

**Comment by serge-rider** [comment]
DBeaver doesn't support HANA-specific SQL syntax, it fails to parse blocks correctly. Thus query ends after `END IF;` statement.
Workaround: select all query and run it with CTRL+Enter.

**Comment by serge-rider** [comment]
Please test blocks processing in 5.1
