### ISSUE TITLE
Size of postgres databases is not shown

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35171]
### Description

If I expand a list of databases in connection to SQL Server host, each database in a list is shown with the overall size of the database right of the database name.
If I do the same for Postgres connection, no one database has the size.

*Please also check all other types of databases.

### DBeaver Version

Community Edition 24.1.5.202408012322

### Operating System

Windows 10

### Database and driver

SQL Server databases:

![изображение](https://github.com/user-attachments/assets/e7024971-c0dc-49c8-a496-b375d9b24a72)

Postgres databases:

![изображение](https://github.com/user-attachments/assets/5aa1c50b-2605-4383-8182-852d45c32d1f)

**Comment by arhayka** [comment]
Thank you for the report!

**Comment by ivgag** [comment]
This is not a bug.

You can find the "Show database statistics" checkbox in the PostgreSQL connection configuration. If it is checked, statistics will be shown. SQL Server does not have such a property, so statistics are shown by default.

<img width="1076" alt="image" src="https://github.com/user-attachments/assets/891413c4-14f8-4fa1-a5c1-d98847aa27c0">

**Comment by ask9** [comment]
Thanks. It is not obvious.

**Comment by arhayka** [comment]
Thank you for this observation. 

It seems that we should describe this in DBeaver documentation. 
This setting is described in [the article about PostgreSQL ](https://dbeaver.com/docs/dbeaver/Database-driver-PostgreSQL/#postgresql-connection-settings), but there is nothing in [the article about Database Navigator](https://dbeaver.com/docs/dbeaver/Database-Navigator/).
