### ISSUE TITLE
"Change active database" keeps appearing and Choosing schema is not working 

### ISSUE THREAD

**Issue by shashikiran-alloli** [dbeaver/dbeaver#35183]
### Description

The "Choose catalog/schema" dialog box is inefficient even after I Select a schema, as soon as I close the dialog box the schema does not seem to be selected and as soon as I try to run to the query I face the error "Change active database"
![DBeaver_Issue](https://github.com/user-attachments/assets/3e3dc743-cb94-4057-8bf0-e38607fb17e9)

### DBeaver Version

Version 24.1.4.202408041450

### Operating System

Windows OS

### Database and driver

snowflake-jdbc-3.13.6.jar

### Steps to reproduce

Try connecting to the snowflake database

**Comment by E1izabeth** [comment]
We would kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
