### ISSUE TITLE
AWS Athena queries no longer work without error messages and has degraded performance

### ISSUE THREAD

**Issue by bazsalehoczki** [dbeaver/dbeaver#35184]
### Description

Running queries against AWS Athena running so much slower in DBeaver, for example

- the query runtime in Athena is 1 min 46.415 sec
- but it took 2 min 53 sec to finish in DBeaver

The AWS credentials work perfectly, the queries can be run, results can be saved and retrieved from CLI. The Athena data catalog and the workspace can be the default or a non-default one the experience is the same.

Additional side-effects:
- this pop-up generated many times by the tool during the query execution:
![image](https://github.com/user-attachments/assets/61402a1a-0f22-4991-b709-7b8a295d00b3)

- or just seeing this screen for the infinity:
![image](https://github.com/user-attachments/assets/08fd99ab-34f5-4cf3-8b1d-322efff9e1dc)

 

### DBeaver Version

Version 24.1.4.202408041519

### Operating System

Windows 11 Enterprise (22631.3880)

### Database and driver

SimbaAthenaJDBC-2.0.34.1000.jar

### Steps to reproduce

1.	Connect to AWS Athena (non-default catalog and workspace)
2.	Run a query, even a simple one
3.	Wait till completion, if DBeaver can complete
4.	Compare Athena runtime with DBeaver runtime

### Additional context
The memory settings is the default from dbeaver.ini which is -Xmx1024m. The tool is using 400-500 MB only during the query executions

Tried different kind of settings with no luck such as:
- MaxQueryExecutionPollingInterval
- MinQueryExecutionPollingInterval
- QueryExecutionPollingIntervalMultiplier
- ConnectTimeout
- ….

We haven't had this problem with the DBeaver 22.1.1, that one works perfectly. Since 22.1.1 has a missing feature for handling non-default data catalogs, the new version is needed. However the problem is the same for default data catalog too with the new version.

**Comment by bazsalehoczki** [comment]
The memory settings is the default from dbeaver.ini which is -Xmx1024m. The tool is using 400-500 MB only during the query executions

**Comment by E1izabeth** [comment]
Please try turning on the following setting `Connection configuration->Metadata->Do not read tables information in SQL and data editors` as a workaround. Does it help?
![image](https://github.com/user-attachments/assets/990bd416-6960-43f8-b17a-13470928d140)

**Comment by serge-rider** [comment]
Could you open Query Manager view to see what is going on? (main menu, Show View->Query Manager)
Turn on all query types in filters.

Maybe there are some metadata queries are executed simultaneously..

**Comment by bazsalehoczki** [comment]
Thank you for your quick and great response and sorry for the late feedback from my side. We have tried to figure out whether could be any issue at our side as well.

@serge-rider: The query manager tab is not showing anything else just the query itself even if I’m allowing everything in the filter section of manager tab. The metadata related queries (before I'm executing any custom query) are running successfully.

@E1izabeth: It’s a great option and it solves the performance and the error problem as well. However we are losing the auto-complete feature in the SQL editor which is so needed for our end-users

What we could found is the **23.1.4 is working perfectly which doesn’t have any error, doesn’t have the performance issue and it has the auto-complete feature working as expected**. This was the first version where the “Show catalogs” option has been introduced into DBeaver as I know.

I hope this helps to investigate the issue further and thanks again for your help in this.

(For now, we are going to release that version for our end-users but it would be great if we can upgrade them to the latest one in the near future.)

**Comment by arhayka** [comment]
Could you please try to test this in the last DBeaver version 24.2.0?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
