### ISSUE TITLE
Highlighting issues after reconnect

### ISSUE THREAD

**Issue by chrisbird-t2rl** [dbeaver/dbeaver#35207]
With a relatively complex query against a redshift database, DBeaver 24.13 (Community edition) highlights all of the column names in my tables as red. Even though I qualify the table name properly. This happens in the ON clause in a join, in simple selection of the columns in a table, inside a wit tn as(select....) construct. In other words pretty much anywhere.

select
	t.tkt_num_id tnum,
	tc2.cpn_num cnum,
	t.base_fare_amt amnt
from
	tkt t
join tkt_cpn tc2 on
	tc2.tkt_num_id = t.tkt_num_id

In the example pasted the columns tkt_num_id and base_fare_amt are both in the tkt table (aliased as t)
Also cpn_num is in the tkt_cpn table (aliased as tc2). However they are both shown in red as can be seen in the attached screenshot.

![Screenshot 2024-08-14 094947](https://github.com/user-attachments/assets/5dc1fbec-fbad-4794-9ebe-903535926f2e)

Is there something that I can do to help DBeaver get this right? Or is it that my query is too complicated? There are 7 tables involved in the actual query, some of them multiple times (with different aliases, of course)

**Comment by E1izabeth** [comment]
Does active catalog/schema selector shows the schema where these tables are located?
![image](https://github.com/user-attachments/assets/22d49731-77a2-4841-9a2c-a115ea866b95)

**Comment by chrisbird-t2rl** [comment]
Thanks, Elizabeth. Yes it does. It seems rather random when DBeaver does this. All of a sudden it is behaving!

**Comment by E1izabeth** [comment]
Does the query is able to successfully run, when tables and columns are highlighted with red?
If it's not a stable-reproducible thing, maybe you noticed some pattern, when it happens?

**Comment by chrisbird-t2rl** [comment]
Yes, the query runs fine even when things are highlighted like that. Also when I add more columns/selection criteria, I don't get the prompt for column names after entering the table alias. Especially inside a with clause.

The situation seems to arise when I reconnect to the database with a tab containing the query open. I haven't tried (but will!) closing the tab and reopening.

**Comment by E1izabeth** [comment]
@chrisbird-t2rl 
Could you try checking if specifying table with fully qualified name helps?
Also does it happen if you write just `select * from tkt`?

**Comment by chrisbird-t2rl** [comment]
In a new query that works fine.
I seem to have isolated this to having my big query open when I lose the connection. When I reconnect it doesn't refresh.  If I close the query and reopen or if I save it, it seems to be OK.

**Comment by E1izabeth** [comment]
> When I reconnect it doesn't refresh

Does the active schema is still correct after reconnect?
DBeaver might switch the active schema to the default one on reconnect. I want to make sure, that it's not the issue root.

**Comment by chrisbird-t2rl** [comment]
Yes the active schema is set on reconnect. I have just done the following:
![Screenshot 2024-08-16 090425](https://github.com/user-attachments/assets/48cfb8d4-cf8e-48a1-b3be-4800fd06e608)
 Where the tkt table is referenced in the bigger query that I excerpted the end of. 
The script was open when I reconnected. New query behaves OK. Existing query not.

**Comment by aespejou** [comment]
Im having similar problem using dbeaver for SQL server. Just began on last dbeaver upgrade. SQL editor shows error (unknow column) for SELECT COL1, COL2 FROM TABLE but no errors for SELECT COL1, COL2 FROM dbo.TABLE. Both select statements retrieve data fine, but I am now forced to use "dbo" schema if I want the autocomplete to work. NOTE: autocomplete works fine without the "dbo" schema if I disable Filters "Connection Settings>General>Database/Catalogs". But is a pain looking for my databases within dozens of them in the navigation pane.

**Comment by E1izabeth** [comment]
@aespejou it is not connected to the current issue. Please create a new one

**Comment by E1izabeth** [comment]
@chrisbird-t2rl thank you
