### ISSUE TITLE
Data transfer from MSSQL to PGSQL fails for very large varchar() types

### ISSUE THREAD

**Issue by golanv** [dbeaver/dbeaver#3520]
MSSQL will allow for some very large varchar() data type sizes, such as varchar(2147483647).  When attempting data transfers to PostgreSQL from MSSQL, these large varchar() data types produce failures.  Perhaps varchar types from MSSQL that are beyond a certain size could be translated to "text" types for PostgreSQL?

**Comment by uslss** [comment]
is it still actual? what version of MS SQL do you use?

**Comment by uslss** [comment]
there is no update on an issue for almost a month.
if the issue is still actual for you - feel free to reopen the ticket with additional info
