### ISSUE TITLE
Pinning of tabs in the result panel does not work anymore

### ISSUE THREAD

**Issue by drahkrub** [dbeaver/dbeaver#35203]
### Description

works in 24.1.3, broken in 24.1.4

(broken = content of pinned tab is overwritten)

### DBeaver Version

24.1.4

### Operating System

Ubuntu 20.04.6 LTS

**Comment by E1izabeth** [comment]
Thank you for bug report.
I'm closing it as it's a duplicate of https://github.com/dbeaver/dbeaver/issues/35072

You can try Early Access version with fix (https://dbeaver.io/files/ea/) or wait for the next release
