### ISSUE TITLE
First TCP Tunnel then SSL to PostgreSQL-DB not working

### ISSUE THREAD

**Issue by tkoelpin** [dbeaver/dbeaver#3521]
## Question

How can I connect to my PostgreSQL-Database with firstly a TCP/IP-Connection to the Database-Server, then a SSL-Connection to the database? 

The command which I use in the Database-Server is `psql` and is automatically connected with SSL. The SSL-Feature is already set in the settings and the Server is already restarted after the setting. 

It should be an SSL-Connection with no authentication for test purposes only.
I currently use the PostgreSQL JDBC Driver 42.2.2

Is this a bug or a missing feature of DBeaver? Because I receive this error all the time.

![dbeaver_connectionerror](https://user-images.githubusercontent.com/8818843/40534445-576d2160-6006-11e8-81f7-b9833770c97c.png)

Thank you so much for your support in advance.

## Purpose

I want to connect a PostgreSQL-Database on an other network, so I need a TCP/IP-Tunnel to achieve this. When the tunnel is established, then I need a SSL-Connection to the PostgreSQL-Databse for the communication between the DB-Client and the PostgreSQL-Database.

Enclosed for a better comprehension I attached an image of the network.

![dbeaver-bug](https://user-images.githubusercontent.com/8818843/40533511-51ee2566-6003-11e8-89f8-709f752d8114.jpg)

## Current settings

I also enclosed following images of my current settings.

![dbeaver_connectionsettings](https://user-images.githubusercontent.com/8818843/40534492-7f1609f2-6006-11e8-8852-1cab82589ed3.png)
![dbeaver_connectionsettings_driverproperties_part1](https://user-images.githubusercontent.com/8818843/40534493-7f349ad4-6006-11e8-9b2c-3ba679eca5ac.png)
![dbeaver_connectionsettings_driverproperties_part2](https://user-images.githubusercontent.com/8818843/40534494-7f55e9f0-6006-11e8-8a05-006cb97c5ecf.png)
![dbeaver_connectionsettings_network_socksproxy](https://user-images.githubusercontent.com/8818843/40534495-7f7515be-6006-11e8-85ee-687a929bfc24.png)
![dbeaver_connectionsettings_network_sshtunnel](https://user-images.githubusercontent.com/8818843/40534496-7f91eac2-6006-11e8-848b-eccd0a204804.png)
![dbeaver_connectionsettings_network_ssl](https://user-images.githubusercontent.com/8818843/40534497-7fae2926-6006-11e8-9b25-7b4db84c9dfa.png)

**Comment by uslss** [comment]
issue isn't reproducible.
Ticket closed.
If it is still actual for you - feel free to reopen the ticket
