### ISSUE TITLE
Columns not show to create a Relationship in Foreign keys

### ISSUE THREAD

**Issue by 1ui61** [dbeaver/dbeaver#35227]
### Description

In both tables I had the same field to create a relationship but the wizard to create a foreign key not display columns
![Screenshot_4](https://github.com/user-attachments/assets/64d20ee1-8a6a-4fb2-ac5e-e04dc72baa04)

### DBeaver Version

Community 24

### Operating System

Windows 11

### Database and driver

Oracle

**Comment by E1izabeth** [comment]
Hi, @1ui61! Thank you for the issue.
Unfortunately, I can't reproduce it.
Does it happen for any table or only for specific ones? Could you show me the screenshot of the Virtual tab for TRFORMS_REQUI01DTABLE?
![image](https://github.com/user-attachments/assets/1b33b636-af14-4161-ab88-1c5abf35d3b6)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
