### ISSUE TITLE
Make the array length visible at all times in the array cell (or show the full array string like it used to)

### ISSUE THREAD

**Issue by MattB543** [dbeaver/dbeaver#35224]
**Is your feature request related to a problem? Please describe.**
Knowing the length of an array is key while skimming through data. I recently updated Dbeaver and now the array is always hidden in a collapsed drop-down without even the length shown.

**Describe the solution you'd like**
Either show the length of the array in the cell or let me change the cell view to show the array string (maybe I can already change this, I just don't know where the setting is) so I can see immediately which arrays have one element and which have multiple

**Comment by E1izabeth** [comment]
Please let me know, what database do you use?

**Comment by MattB543** [comment]
@E1izabeth PostgreSQL

You can see a cell here that is an array, it looks like one item until you click it:
![image](https://github.com/user-attachments/assets/390ad827-84b0-48f3-a09e-88203d2ef903)

![image](https://github.com/user-attachments/assets/c7641d25-63d4-424c-b360-b860e4c6fe75)

**Comment by E1izabeth** [comment]
I would say it's a bug. Thank you for report.

**Comment by Ploki72** [comment]
I am experiencing the same issue. The last working version is 24.1.0. Starting from version 24.1.1, the number of items is no longer displayed. The database used is Postgres.

In version 24.1.0 and earlier, the application displays the number of items correctly, as shown in the screenshot below:
![2410](https://github.com/user-attachments/assets/52ce920b-989b-4dc2-b691-6488261bcfe3)

In version 24.1.5, there are two ways the results are displayed:
If there is only one column, it displays all items inline.
![2415_1](https://github.com/user-attachments/assets/4c8cb2fd-b552-4fea-a89f-7d1d9703bf46)

If there are additional columns (before or after), it only shows the first item.
![2415_21](https://github.com/user-attachments/assets/fa0ae0f4-6b5e-4c8a-ade1-76ea7c360cbb)

There is a small arrow to expand the items, and the number of array items is only displayed after expanding.
![2415_22](https://github.com/user-attachments/assets/7da710ba-becd-4e1b-8d7a-5dfb7604fa12)

**Comment by uslss** [comment]
will be fixed in 24.2.2

![image](https://github.com/user-attachments/assets/04dc0e0b-29c7-47f5-b147-5b003339cc9f)

**Comment by Ploki72** [comment]
Upgraded to 24.2.2 and it works

**Comment by simonriker** [comment]
Is there any way to disable this expand / collapse functionality? I strongly prefer seeing the full value of the array (or truncated if long) inline, and I have not been able to find a way to restore that view in the latest version.

**Comment by E1izabeth** [comment]
@simonriker 
There is no way to disable it right now. However, you can create a feature request
