### ISSUE TITLE
[feature request] - Find and Replace in all open tabs

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#3522]
Sometimes I have several open tabs for one database to divide what queries are being ran where.

The find and replace dialog I think could have information regarding in which tab to make changes.

Current tab
All open tabs
or In selected tabs

**Comment by serge-rider** [comment]
Workaround: you can select all scripts you want to search in and use text  search (kbd>CTRL+H</kbd>). Check "Selected resources" option to narrows search.

**Comment by nmat** [comment]
Thank you @serge-rider 👍

**Comment by nmat** [comment]
any updates on this?

**Comment by uslss** [comment]
duplicates #2082
