### ISSUE TITLE
Grant for groups shows wrong statement on Redshift

### ISSUE THREAD

**Issue by alejandrofm** [dbeaver/dbeaver#35221]
### Description

When going into a table->properties->DDL (show permissions activated) the permissions are shown with the same statement for groups and users, like:

GRANT RULE, TRIGGER ON TABLE stori_ccm_pl.account_active_flag_info TO user;
GRANT SELECT ON TABLE stori_ccm_pl.account_active_flag_info TO group1;

The second statement is wrong and it should say TO GROUP group1

### DBeaver Version

24.1.4

### Operating System

macOS 14

### Database and driver

Redshift jdbc 2.1.0.9

### Steps to reproduce

Go to a table DDL via:
table->properties->DDL (show permissions activated)

**Comment by E1izabeth** [comment]
Thank you for bug report.

https://docs.aws.amazon.com/redshift/latest/dg/r_GRANT.html
