### ISSUE TITLE
Autofill doesn't work properly related to search_path after recent updates

### ISSUE THREAD

**Issue by saichander17** [dbeaver/dbeaver#35229]
### Description

Hi all, 
From last 2 versions I think this issue is occurring. 
In the console, if you do set search_path='someschemaname' and then try to write further queries, it automatically doesn't detect the table names and all present in that set schema above

### DBeaver Version

24.1.4.202408041450

### Operating System

macOS 14.1.1

### Database and driver

PostgreSQL

### Steps to reproduce

1. Open console of an existing DB connection
2. Write and execute the query like this `set search_path='schema';`
3. Now in the next line try to write 'select * from tablename' where tablename is present in the schema but DBeaver thinks it doesn't exist. So, Autofill doesn't really work and the table name is shown in red color

**Comment by E1izabeth** [comment]
Could you try turning on the `Refresh active schema after SQL execution` setting? It's in Preferences or Connection configuration -> SQL Editor -> SQL Processing

![image](https://github.com/user-attachments/assets/390eb01c-522e-44f7-9919-93354b96eeeb)


Does it help?

**Comment by saichander17** [comment]
Thanks! That works

**Comment by li398779124** [comment]
Thanks, I also encountered the same problem after updating to the latest version.
After changing the configuration now, it's okay
