### ISSUE TITLE
dbeaver Support

### ISSUE THREAD

**Issue by drudd75077** [dbeaver/dbeaver#3523]
- Question
Is there some way to purchase support for working with dbeaver. I really like using it to manage my databases. I'm starting to use it at work to connect to my employer's databases, it would be really helpful if there was a support line that could help with technical problems that I won't know the answer to since I don't understands the in and outs of the tool. Any opportunity for this?

**Comment by tati-kru** [comment]
hi @drudd75077 
All licensed users of DBeaver EE have an access to a special support system where they can ask questions. Tickets and questions from licensed users have higher priority. 
I can recommend you to buy license for the enterprise version and use support if you need.
