### ISSUE TITLE
customising the type of connection on the command line is not run

### ISSUE THREAD

**Issue by ccavallie** [dbeaver/dbeaver#35240]
### Description

Hello I try to pass the connection type in a command line but that it's not work.
here this is my command line:
dbeaver.exe -nl fr -nosplash -vars C:\Users\ddi355\dbeaver.properties -con "driver=postgresql|host=prd13003|port=5432|database=db_prod|user=${user}|password=${password}|name=prd13003|folder=postgresql/prod|SecurConnectsavePassword=true|**connection.type=production**|create=true|save=true|connect=false"

the postgresql connection is created but with the default type
The production type has been created beforehand.

### DBeaver Version

24.01

### Operating System

Windows 11 Entreprise  22631.3880

**Comment by E1izabeth** [comment]
It's not supported yet.
Here is a feature request about it #22358

I'm closing this issue as a duplicate. 
You can vote for the issue with 👍 under the mentioned issue description to promote it to a higher priority.
