### ISSUE TITLE
Clickhouse data filtering works incorrectly

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#35248]
### Description

For data type Date

```
CREATE TABLE COUNTRY_USAGE
(
    `month` Date,
    `app_name` String,
)
ENGINE = MergeTree
ORDER BY (month,
 app_name)
SETTINGS index_granularity = 8192;
```

![Снимок экрана 2024-08-19 145247](https://github.com/user-attachments/assets/fbaae55f-d608-4304-aa8b-fe68e98452fb)
![Снимок экрана 2024-08-19 145343](https://github.com/user-attachments/assets/9eec8ca2-6a12-447d-88f4-2f60fc5c1ddf)

### DBeaver Version

Ultimate 24.1.5

### Database and driver

ClickHouse modern 22.1.3.7

### Steps to reproduce

Open a table with a Date data type
Choose filtering on a cell with any value

Not reproducible on MySQL with Date data type.

Expected: we have the correct filtering
Actual: Query fails

**Comment by uslss** [comment]
Reproducible on db3.test.COUNTRY_USAGE
![image](https://github.com/user-attachments/assets/8e180619-1e67-4fa2-bbff-18cc5d7d1892)

**Comment by serge-rider** [comment]
What exactly do you do? Or just attach video

**Comment by uslss** [comment]
https://github.com/user-attachments/assets/957050cf-0d34-4201-9101-a14e2de6101d

**Comment by serge-rider** [comment]
New Clickhouse driver returns date/time values as LocalDate and LocalDateTime.
Fixed
