### ISSUE TITLE
Breakpoint view window

### ISSUE THREAD

**Issue by AndrewKhitrin** [dbeaver/dbeaver#3525]
In  case of local postgress debug session there is "starnge" behavor of breakpoint window after adding brekpoint or starting debug session.

Breakpoint not visible in   breakpoint window after creating and becomes visible after several switches of perspective (dbeaver <-> debug)

**Comment by E1izabeth** [comment]
Does this issue still actual for the latest DBeaver version? I can't reproduce it. Any video or detailed steps to reproduce would be useful.
