### ISSUE TITLE
PostgreSQL: Dbeaver freeze UI during query typing 

### ISSUE THREAD

**Issue by StepanYankevych** [dbeaver/dbeaver#35261]
### Description

DBeaver 21.1.* 
PostgreSQL 15.* 
During query typing or part of query selection DBeaver UI freezes for several second 
The issue appeared in nearest few weeks. 
It is reproducible in 24.1.5 and 24.1.4. 
Maybe in some older versions as well 

### DBeaver Version

Community Edition 24.1.5

### Operating System

Windows 11

### Database and driver

JDBC 42.7.2 
PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

### Steps to reproduce

start typing some query the select some part of query . UI is freeze. Syntax highlight disappears then highlight is recovered and UI unfreeze

**Comment by E1izabeth** [comment]
Hi, @StepanYankevych 
Could you tell me how large is your script, where you're typing?

**Comment by ask9** [comment]
I've noticed something similar if there any many syntax errors in the script for some reason.
Is it your case?

**Comment by StepanYankevych** [comment]
Could you tell me how large is your script, where you're typing? - Even half a screen. 
And i agree a lot of highlighted in red words. (Red words it could  be another issue :)  )  
Just opened simple script like , trying to select some part of query text using mouse and it hangs time to time 
```
select 
col1,
col2, 
..
col50
from table1 
where date=current_date
union all 
select 
col1,
col2, 
..
col50
from table2 
where date=current_date
```

**Comment by E1izabeth** [comment]
Do you have the correct database and schema chosen here?
![image](https://github.com/user-attachments/assets/edb53806-781c-4297-a65a-03625acefdb5)

**Comment by E1izabeth** [comment]
Also could you explain what do you mean by "frozen"? Is it that the highlighting is updating with a time delay or that your typing comes to the editor with delay?

**Comment by StepanYankevych** [comment]
Do you have the correct database and schema chosen here? - Database - yes. Schema - not,  because tables from different schemas used in the query and schema specified in the query like shema_name.table1 

"frozen" - Means Application does not respond for several seconds. Like i can't even resize app window, move app window. 

It is not all the time reproducible. Sometime it is reproducible often , sometimes i can't reproduce

**Comment by E1izabeth** [comment]
I see. Thank you

**Comment by StepanYankevych** [comment]
![image](https://github.com/user-attachments/assets/989233a9-c2ec-4440-a3de-05d56b99d376)

See screenshot.

**Comment by E1izabeth** [comment]
Could you check if it's reproducible, if you turn off the setting in preferences `Editors->SQL Editor->Code Editor->Enable semantic analysis`?

**Comment by E1izabeth** [comment]
Also could you perform a thread dump, when you reproduce it again? You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump

**Comment by StepanYankevych** [comment]
Look like turning off "Read database table/column for semantic analysis" resolved the issue. 
![image](https://github.com/user-attachments/assets/cfcf8ed8-aac9-4878-ac9e-bfd44b89a02c)

**Comment by E1izabeth** [comment]
Thank you for investigation

**Comment by E1izabeth** [comment]
@StepanYankevych could you try DBeaver 24.2.0 to see if the issue is solved?

**Comment by ask9** [comment]
@E1izabeth try to provoke the issue with the following steps (right of the sql editor - procmon is opened with CPU usage by threads):


https://github.com/user-attachments/assets/baba5a27-40ce-492f-97fe-c985a8c0c1ba



- copy-paste any query with **many syntax errors** to a new sql editor, for example:

```
SELECT datid, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id,  query, backend_type, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id, query, backend_type, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id, query, backend_type, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id, query, backend_type, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id, query, backend_type, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id, query, backend_type, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id, query, backend_type, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id, query, backend_type, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id, query, backend_type, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id, query, backend_type, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id, query, backend_type, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id, query, backend_type, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id, query, backend_type, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id, query, backend_type, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id, query, backend_type, datname, pid, leader_pid, usesysid, usename, application_name, client_addr, client_hostname, client_port, backend_start, xact_start, query_start, state_change, wait_event_type, wait_event, state, backend_xid, backend_xmin, query_id, query, backend_type
FROM pg_stat_activity;
```

- hover mouse pointer over a list of exclamations left of the text of the query
- try to scroll the vertical scrollbar in sql editor
- try to edit some text in the script, for example, remove a column or wirte an alias for a table, start typing join ...
- select all the text: Ctrl + A, then cut it: Ctrl + X

Consider the possible solution: 
I didn't see the code, but I feel the syntax parser routine should work in a separate thread (asynchronously) so that it doesn't block the main UI thread (if possible).
Perhaps it would let to avoid these freezes no matter how long it would take to parse the syntax.
In addition, better utilization of the processor cores will be ensured.
Here is my current utilization from task manager while performing syntax parsing.
As you can see, there any plenty of cpu cores in an idle state but the application does not respond:

![изображение](https://github.com/user-attachments/assets/4f86d3e2-4ef6-4db9-be5b-4bff0d87b884)


Another stress-case is to copy-paste the same long query to many tabs splitted on the same screen, so that parsing started for all of them at the same time:

![изображение](https://github.com/user-attachments/assets/598838b4-5706-4cd1-be06-b9eb45d7ab9a)

**Comment by E1izabeth** [comment]
> I didn't see the code, but I feel the syntax parser routine should work in a separate thread (asynchronously) so that it doesn't block the main UI thread (if possible).

Yes, it works in the background job.

**Comment by E1izabeth** [comment]
Thank you for providing the cases.

**Comment by ask9** [comment]
@E1izabeth  I would suggest adding tag Performance for the issue.
I would suggest adding additional logging to codebase to measure performance of background query parsing tasks (the number of milliseconds and its frequency).
I would suggest to test this case on heavy queries (for example, many joins in one query or long cte) or long scripts with many separate queries and with many problem markers.

**Comment by ivgag** [comment]
The initial issue can not be reproduced.
