### ISSUE TITLE
semantic analysis and highlighting is not working when use Subquery

### ISSUE THREAD

**Issue by L-Jiyong** [dbeaver/dbeaver#35260]
### Description

after v24.1.3  semantic analysis and highlighting is not working when Subquery included.

![shot1](https://github.com/user-attachments/assets/77058beb-4c9c-496a-82bc-5888e6d08b2b)
![shot2](https://github.com/user-attachments/assets/c8d414bf-37e2-4bac-9824-b6d3067228fd)

### DBeaver Version

Community Edition 24.1.5

### Operating System

Windows 10

**Comment by E1izabeth** [comment]
Thank you for bug report.
