### ISSUE TITLE
MS Sql Server  Metadata not reading after 24.1.3

### ISSUE THREAD

**Issue by farhanrashid** [dbeaver/dbeaver#35272]
### Description

Metadata for previously saved scripts are not read correctly. If I have multiple tabs open. Metadata is only read on current tab.

Problem started since  24.1.3
24.1.1 seems ok 
24.1.2 some times  have problem

### DBeaver Version

24.1.2+

### Operating System

Windows 11

### Database and driver

MySQL Server

### Steps to reproduce

Connect with MS SQL Server database, 
open 2 tabs
write some SQL in both tabs
close and restart dbeaver
Metadata of inactive tab is not available (BUG)

**Comment by E1izabeth** [comment]
Thank you for report.
Could you please clarify. how do you check that "Metadata of inactive tab is not available"? Why do you need some metadata for inactive editor?

**Comment by farhanrashid** [comment]
This green circle show meta data is read correctly
![image](https://github.com/user-attachments/assets/4275fee9-fdf7-440a-833f-7919af652d73)

meta data not read correctly
![image](https://github.com/user-attachments/assets/c1997046-4267-4d65-bb52-502985d580b2)


I am always working with multiple tabs with different databases.
after closing and reopening dbeaver, only 1 tab has meta data others don't.
I need to reconnect database on other tabs in order to fix it.

**Comment by farhanrashid** [comment]
this is similar issue

https://github.com/dbeaver/dbeaver/issues/35375

**Comment by E1izabeth** [comment]
Are you connecting to SQL Server through ODBC driver?

**Comment by farhanrashid** [comment]
yes default ODBC driver in DBeaver

**Comment by E1izabeth** [comment]
Could you tell me, why are you using ODBC driver? Have you tried using JDBC driver? The ODBC driver is not maintained and is only left for backward compatibility, whereas the JDBC driver gets regular updates from Microsoft.

**Comment by farhanrashid** [comment]
my bad sorry, default driver is JDBC
I am not using ODBC

**Comment by MashaKorax** [comment]
Hello @farhanrashid . Im trying to reproduce your issue. Could you see my video and verify that my steps are correct?



https://github.com/user-attachments/assets/a097905d-0eb7-4b83-90c2-1623e1835284

**Comment by farhanrashid** [comment]
1) In your case database is same (test). I am using different databases.
2) your version is 24.2.1. I tried 24.2.0, problem is still there

**Comment by E1izabeth** [comment]
Please provide the video showing the issue.
For now, we can't reproduce it.
https://github.com/user-attachments/assets/664f2a53-3403-4667-a7d1-1f333d46d774

**Comment by farhanrashid** [comment]
please check its even easier to reproduce
https://github.com/user-attachments/assets/925e5be4-3e78-46b2-9483-d31ddbdb260d

**Comment by farhanrashid** [comment]
setting this option to "Never" solved my issue.
![image](https://github.com/user-attachments/assets/d3f1f1df-0a1a-466a-b81f-fa74e3263bb5)
