### ISSUE TITLE
MySQL 5.7  Error parsing geometry value from binary when NULL is inserted into POINT column

### ISSUE THREAD

**Issue by EastLord** [dbeaver/dbeaver#35279]
### Description

Error parsing geometry value from binary when NULL is inserted into POINT column

### DBeaver Version

Community 24.1.5.202408181605

### Operating System

macOS 14.6.1

### Database and driver

1.Database: MySQL 5.7
2.driver:mysql-connector-j:8.2.0

### Steps to reproduce

1.Create a table with a POINT type column in MySQL:
CREATE TABLE test (
    c_point POINT NOT NULL
);
2.Insert a NULL value into the POINT column using the following query:
INSERT IGNORE INTO test (c_point) VALUES(NULL);
3.Attempt to view the data in DBeaver.
Expected Behavior:
•DBeaver should handle the NULL value in the POINT column gracefully, either by showing NULL or an appropriate message without an error.
Actual Behavior:
•An error message is displayed: “Error parsing geometry value from binary”.
![image](https://github.com/user-attachments/assets/c1340f4d-f1d2-4cde-b4b5-a2116b50f5a3)

### Additional context

This issue seems to occur specifically when trying to view data from a POINT column where a NULL value has been inserted.

**Comment by EastLord** [comment]
I will try to fix

**Comment by E1izabeth** [comment]
I reproduced the issue. Thank you for bug report.
