### ISSUE TITLE
Results viewer: horizontal scroll with mouse wheel - does not work on windows 10

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#3527]
Version: 5.0.6

OS: windows 10

General information:
Tested with postgreSQL and mssql.

Tested to use the mouse pad on my laptop also on one machine which does not read it. Also tested with a standard mouse with no effect change.

Vertical scroll works perfect.

Tested the scroll on macOS also but there it works with the mousepad on the laptop. seems to be isolated to windows for some reason.

**Comment by serge-rider** [comment]
You need to press <kbd>SHIFT</kbd> to perform horizontal scroll

**Comment by nmat** [comment]
Verified that it works with Shift + mouse on windows 10

Trackpad on laptop from when I tested did not work with Shift though (windows 10).

Shouldn't this be the same binding on macOS btw? Where shift is the key to use for doing vertical horizontal scroll?

**Comment by serge-rider** [comment]
Trackpad works a bit different in SWT (not like mouse wheel).
It works on MacOS but with trackpad it makes both vertical+horizontal scrolling (diagonally) with shift. A bit weird :)
