### ISSUE TITLE
Further Column recognition issues

### ISSUE THREAD

**Issue by chrisbird-t2rl** [dbeaver/dbeaver#35277]
### Description

I am using a construct whereby I put my constants into a with clause, so in a complex query, I can change the constants values.

The with clause(s) look like this.

with 
vars as (
select
	date '2023-12-01' as upg_start,
	date '2023-12-02' as upg_end,
	DATEADD (day ,
	1,
	upg_start) as back_date),
get_stuff as 
(
select
	tc.tkt_iss_dt issue_date
	from
	tkt_cpn tc
where
	1 = 1
	and tc.tkt_iss_dt between (
	select
		upg_start
	from
		vars) and (
	select
		back_date
	from
		vars)
![Screenshot 2024-08-20 095456](https://github.com/user-attachments/assets/4fea632d-16c4-4220-8e37-973e6ea08636)

)
select distinct issue_date from get_stuff;

As you can see from the pasted screenshot, DBeaver is unhappy with the use of upg_start in the DATEADD predicate, and it doesn't recognize issue_date in the final select.

The query runs fine, though.

### DBeaver Version

Community Version 24.1.5.202408181605

### Operating System

Windows 10

### Database and driver

Redshift com.amazon.redshift.jdbc42.Driver

### Steps to reproduce

Develop a similar query

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by chrisbird-t2rl** [comment]
Thanks, everyone. Looking forward to downloading the appropriate version.
