### ISSUE TITLE
Date not inserted correctly when importing a CSV into Snowflake

### ISSUE THREAD

**Issue by ben-nour** [dbeaver/dbeaver#35284]
### Description

I'm trying to import a CSV into Snowflake. but the date being inserted into the table is not the correct date.

My CSV (1st July 2024):
```
MONTH
1/07/2024
```

My table::

```SQL
create or replace TABLE BEN_TEST (
	MONTH DATE
);
````

This is the format I use when importing:

![image](https://github.com/user-attachments/assets/06e6c0ed-8105-4738-9712-ef01567dd041)

This is what gets inserted into the table:

![image](https://github.com/user-attachments/assets/3242fed9-0ba4-465f-9295-454107ce2ed4)

``` SQL
SELECT MONTH(MONTH)
FROM  ben_test
;
```

Output:
```
1
````

Thanks!

### DBeaver Version

Community Edition 24.1.5.202408181605

### Operating System

Windows 10 Enterprise

### Steps to reproduce

I tried importing with date format in settings set to 'MM-DD-YYYY' but had the same issue.

**Comment by TB-HunBoka** [comment]
Can you try with 2 digits day value?

MONTH
**0**1/07/2024

I have no experience with this, just blind shooting.

**Comment by E1izabeth** [comment]
Thank you for bug report. I reproduced the issue

**Comment by ben-nour** [comment]
> Can you try with 2 digits day value?
> 
> 
> 
> MONTH
> 
> **0**1/07/2024
> 
> 
> 
> I have no experience with this, just blind shooting.

I did try this and it did not work unfortunately.

**Comment by ShadelessFox** [comment]
Hello @ben-n93,

The `mm` in the format string denotes **minute-of-hour**. Months are denoted using `MM`.

https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#patterns

**Comment by ben-nour** [comment]
> Hello @ben-n93,
> 
> The `mm` in the format string denotes **minute-of-hour**. Months are denoted using `MM`.
> 
> https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#patterns

Thank you! 

It worked with `d/MM/YYYY`.

**Comment by ShadelessFox** [comment]
We still want to improve the UX and maybe at least provide link to the documentation describing all formatting options. So I will reopen the ticket for now.
