### ISSUE TITLE
Bug report: launcher problem: plank dock

### ISSUE THREAD

**Issue by dominikzogg** [dbeaver/dbeaver#3529]
The behavior of the launcher of dbeaver changed since 5.0.5 (same on 5.0.6).

Up to 5.0.4 i clicked to the launcher and there was a dot to show me its open.

Since 5.0.5 i clicked to the launcher and i get a new ones which shows me its open. Since then i often try to start and new instance accidentally

![dock](https://user-images.githubusercontent.com/1011217/40612306-40204db8-627a-11e8-9679-9413e0dc5547.jpeg)

Using elementary os 0.4

**Comment by esl51** [comment]
Have the same issue on Manjaro XFCE.

**Comment by uslss** [comment]
cannot reproduce it for now. Issue closed
