### ISSUE TITLE
Left tree collapses at random

### ISSUE THREAD

**Issue by meglio** [dbeaver/dbeaver#35302]
### Description

The database/tables tree get collapsed at will.

### DBeaver Version

Version 24.1.5.202408181605

### Operating System

macOS Sonoma 14.6.1

### Database and driver

PostgreSQL, but it does not matter for this bug report.

### Steps to reproduce

1. Expand the database/tables tree on the left.
2. Put your laptop to sleep for a minute.
3. Awake your laptop
4. The tree is collapsed

**Comment by ged-yuko** [comment]
> 1. Expand the database/tables tree on the left.

At this step database connection is being established and DBeaver reads information about the tables from the database.

> 2. Put your laptop to sleep for a minute.

At this step database connection is being broken, but the system switched to sleep mode, so DBeaver may not have time to react.

> 3. Awake your laptop

At this step the DBeaver also awakes and finally handles disconnect (the same as when you intentionally click "Disconnect" while the database is selected), so the database subtree contents cannot be manipulated with, so DBeaver collapses it.
Autoreconnect could have been initiated here, but only if the disconnection detected during normal DBeaver operation. But in this case it is a result of sleep preparation procedure, so then DBeaver just handles system's state change. 

> 4. The tree is collapsed

@
