### ISSUE TITLE
An error occurs on applying filters (when the value of the checkbox "Enable" was changed) in a Filter window when filtering databases

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35300]
### Description

... if the option in connetion is set Show all databases = false.

I understand that filtering has no sense with the option Show all databases = false. But sometimes user may want to toogle these values for the certain connection and forget about the filters.
The error says that there is no databases after filtering/unfiltering, but I can see my database in a list of databases after appliying the filter.
So the error can confuse the user.

![0000003552](https://github.com/user-attachments/assets/cd5ce5e5-fe8f-435b-b0f2-770cafa73529)

### DBeaver Version

Community Edition 24.1.5-202408122322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

- set option Show all databases = false  in connection settings
- set the database for the connection - db1
- add filter %db% for a list of databases in Database Navigator
- press OK
- ensure that you see your database in a list of databses
- open filters again and turn off the checkbox "Enable", press OK
- repeat these steps 1-2 times (sometimes it happens on enabling a filter, sometimes - on removing the filter)

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
fixed in the scope of #35506
