### ISSUE TITLE
Extra spaces during SQL formatting

### ISSUE THREAD

**Issue by Sachin-Hajeri** [dbeaver/dbeaver#35307]
### Description

When we use default SQL formatter extra spaces are added to string literals used in PLSQL stored Procedure code

### DBeaver Version

Community edition 24.1.5

### Operating System

Windows 11 Enterprise

### Database and driver

DB: DB2
Version 11.5

### Steps to reproduce

1. Write any simple PLSQL stored Procedure having some strings literals used.
2. Format the PLSQL query written using default formatter in dbeaver.
3. See the spaces added to literals automatically.

**Comment by E1izabeth** [comment]
Thank you for report. Could you clarify what spaces are you talking about? Please provide some example to reproduce it.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
