### ISSUE TITLE
[Bug] DBeaver 5.0.6 Redshift Connection Error

### ISSUE THREAD

**Issue by Parannarae** [dbeaver/dbeaver#3530]
According to the release note, DBeaver 5.0.6 has changed its Redshift driver, but it gives following error when tried to connect to Redshift:

```
Can't create driver instance
  Can't load driver class 'com.amazon.redshift.jdbc41.Driver'
    com.amazon.redshift.jdbc41.Driver
    com.amazon.redshift.jdbc41.Driver
```

I resolved the issue by either **1) downgrade DBeaver to 5.0.5** or **2) manually get Redshift driver from AWS and use that driver**.

I found that the changed Redshift driver (used by DBeaver) version is `1.2.12.1017`. However when I manually get Redshift from AWS it has version number as  `1.2.15.1025` (https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html).

So I guess it is better to use the newest version of Redshift driver or keep with the old one.

**Comment by serge-rider** [comment]
My bad. I've updated driver jar URL but not driver class (which also should be com.amazon.redshift.jdbc42.Driver). Need better QA :(
Thanks for report.
