### ISSUE TITLE
Miss Warning In SQL Editor

### ISSUE THREAD

**Issue by mehmetkurban** [dbeaver/dbeaver#35313]
### Description

Everting works. But SQL editor giving me table all cons colums not found. My script works well and returning me succsess result. But i dont understand why sql editor shows error. Is there a bug here? 
![17243242085998099003552667939204](https://github.com/user-attachments/assets/c706595f-a280-4340-a746-2ee21494c87b)

### DBeaver Version

24.1.5

### Operating System

W10 Enterprise 

### Database and driver

Oracle
Oracle ojdbc11-23.2.0.0

### Steps to reproduce

![17243236389573843568635365780093](https://github.com/user-attachments/assets/eacd26cb-5221-4e48-a924-c1dbd9853c24)

**Comment by E1izabeth** [comment]
Does active catalog/schema selector shows the schema where these tables are located?
![image](https://github.com/user-attachments/assets/22d49731-77a2-4841-9a2c-a115ea866b95)

**Comment by mehmetkurban** [comment]
Its active. Not N/A. 
The ALL_CONSTRAINTS table is a system view in Oracle databases. It provides information about all the constraints in the database, such as primary keys, foreign keys, unique keys, and check constraints. This table is particularly useful for database administrators and developers to query and manage table constraints.


Oracle Database: The ALL_CONSTRAINTS table is part of the Oracle database system and is provided by Oracle.

[![IMG_20240822_160151.jpg](https://github.com/user-attachments/assets/2731db8e-3e35-4504-9abf-5ce74c1d5efa)

One more point SQL Editor not shows my whole squences and giving me Warning. But i can take succsses seqence id when i run script. 

If you want, you can try miss warning.
I am sharing the script:
SELECT

    a.owner AS schema_name,

    a.table_name AS table_name,

    col.column_name AS foreign_key_column,

    --a.constraint_name AS foreign_key_name,

    a.delete_rule AS delete_rule,

    c.owner AS referenced_schema,

    c.table_name AS referenced_table

    --c.constraint_name AS referenced_constraint

FROM

    all_constraints a

JOIN

    all_constraints c ON a.r_constraint_name = c.constraint_name

JOIN

    all_cons_columns col ON a.constraint_name = col.constraint_name AND a.owner = col.owner

WHERE

    a.constraint_type = 'R'

ORDER BY

    a.owner, a.table_name;

**Comment by E1izabeth** [comment]
Unfortunately, I can't reproduce it
![image](https://github.com/user-attachments/assets/01f44f80-05b8-4bc1-9d87-fd074aa4a9b7)

**Comment by ged-yuko** [comment]
I noticed two things with respect to this behavior:
1. DBeaver supports only table and view entites validation at the moment, so it tries to treat the sequence reference as a column and fails. This is a matter of semantic analysis being under construction, i assume.
2. In the second case, if the active schema is correct and the connection is alive, it looks like a cached metadata being stuck for some reason. It typically helps to manually reconnect the database (pressing Disconnect in the toolbar, then Connect again). 

Note that, as @E1izabeth demonstrated, SYS schema should be selected for system views to be correctly resolved. I assume, its because DBeaver just cannot know about all the transparently accessible system representations for all the databases it supports. Although it is a work in progress apparently, judging by the [work being prepared ](https://github.com/dbeaver/dbeaver/pull/35161), so it might partially change in the nearest future.

**Comment by mehmetkurban** [comment]
Its active.
The ALL_CONSTRAINTS table is a system view in Oracle databases. It provides information about all the constraints in the database, such as primary keys, foreign keys, unique keys, and check constraints. This table is particularly useful for database administrators and developers to query and manage table constraints.

Source and Usage:

Oracle Database: The ALL_CONSTRAINTS table is part of the Oracle database system and is provided by Oracle.

[![IMG_20240822_160151.jpg](https://github.com/user-attachments/assets/2731db8e-3e35-4504-9abf-5ce74c1d5efa)


If you want, you can try miss warning.
I am sharing the script:
SELECT

    a.owner AS schema_name,

    a.table_name AS table_name,

    col.column_name AS foreign_key_column,

    --a.constraint_name AS foreign_key_name,

    a.delete_rule AS delete_rule,

    c.owner AS referenced_schema,

    c.table_name AS referenced_table

    --c.constraint_name AS referenced_constraint

FROM

    all_constraints a

JOIN

    all_constraints c ON a.r_constraint_name = c.constraint_name

JOIN

    all_cons_columns col ON a.constraint_name = col.constraint_name AND a.owner = col.owner

WHERE

    a.constraint_type = 'R'

ORDER BY

    a.owner, a.table_name;

**Comment by mehmetkurban** [comment]
I understand what's wrong In SQL editor. As you say, especially i have to choose SYS scheme on "active catalog/scheme" to fix warnings. 
Totally I have 206 schema and when clicked "active catalog/scheme" I saw 100 schema. Most probably bug occurs here. İts couldn't show me rest of shcemes. ![IMG_20240822_234916_edit_110993289321604.jpg](https://github.com/user-attachments/assets/41e82f59-cbd1-4b9d-9be5-e77324b1103f)

**Comment by E1izabeth** [comment]
@mehmetkurban could you try pressing to the button itself, where the name of the currently selected schema is written? This window should appears. It contains search field at the bottom
![image](https://github.com/user-attachments/assets/4c513319-82f6-4fd9-bf91-181b26357d0b)

**Comment by E1izabeth** [comment]
Thanks for investigation, @ged-yuko 
Yes, indeed, the provided query should work if any schema is selected. We can improve it.

**Comment by mehmetkurban** [comment]
Thank you @E1izabeth , its fixed

**Comment by E1izabeth** [comment]
We want to fix the SYS schema tables and columns validation - seems they're available even if SYS is not active schema.
Also we want to support NEXTVAL sequence for semantic analysis.

Let's keep the issue open to implement these.

**Comment by aespejou** [comment]
Im having similar problem using dbeaver for SQL server. Just began on last dbeaver upgrade. SQL editor shows error (unknow column) for SELECT COL1, COL2 FROM TABLE but no errors for SELECT COL1, COL2 FROM dbo.TABLE. Both select statements retrieve data fine, but I am now forced to use "dbo" schema if I want the autocomplete to work. NOTE: autocomplete works fine without the "dbo" schema if I disable Filters "Connection Settings>General>Database/Catalogs". But is a pain looking for my databases within dozens of them in the navigation pane.

**Comment by mhrafin** [comment]
Facing this similar issue.
The Query works fine. But the editor keeps showing warning. The database is also selected.
![image](https://github.com/user-attachments/assets/e8560fd0-9858-4f29-a3de-d9774528a02a)

``SELECT *
FROM c5practice.`Movie-Data`
WHERE Genre = "Comedy"``

![image](https://github.com/user-attachments/assets/8e7d4e99-8919-4c78-942b-3af657e75adc)
![image](https://github.com/user-attachments/assets/aeabe8e7-c8e0-4512-9199-9ba631270745)

**Comment by E1izabeth** [comment]
@aespejou @mhrafin your cases are not the same as the case from this issue. Please create a new one

**Comment by mhrafin** [comment]
> @aespejou @mhrafin your cases are not the same as the case from this issue. Please create a new one

@E1izabeth Created that Two weeks ago.
https://github.com/dbeaver/dbeaver/issues/35578#issue-2523575141
