### ISSUE TITLE
problem about package the dbeaver

### ISSUE THREAD

**Issue by mawubin** [dbeaver/dbeaver#3531]
When I use command "mvn package",the system always tells me
 " org.apache.http.impl.client.DefaultRequestDirector tryConnect
message: I/O exception (java.net.SocketException) caught when connecting to {s}->https://dbeaver.io: Connection reset" 

can you help me how to handle this?
thank you very much!

**Comment by serge-rider** [comment]
Well, it says that dbeaver.io isn't accessible (although it should be). 
Are you behind some kind of corporate firewall?
