### ISSUE TITLE
Data Types not showed for MS SQL Server

### ISSUE THREAD

**Issue by peterprvy** [dbeaver/dbeaver#35322]
### Description

Data Types not showed for MS SQL Server in DBeaver version 24.1.5, but showed in older version 24.0.5

### DBeaver Version

24.1.5

### Operating System

Windows 10

### Database and driver

1. DB name: MS SQL Server 2019 (15.00.2080)
2. connector: Microsoft JDBC Driver 9.2 for SQL Server 9.2.0.0

### Steps to reproduce

1. Connect to DB
2. expand    Databases -> [database] -> Schemas -> [schema] -> Data Types -> <data type> -> Columns -> EMPTY
3. or  expand Databases -> [database] -> Schemas -> [schema] -> Data Types -> <data type> -> <double click> -> EMPTY COLUMS / EMPTY SOURCE

### Additional context

DBeaver  24.1.5

![image](https://github.com/user-attachments/assets/e5c73c75-3c5c-4d5c-a0d3-deba50b4ef1a)

DBeaver  24.0.5

![image](https://github.com/user-attachments/assets/5bcae20c-d8ab-43b3-848e-2021357b9160)
![image](https://github.com/user-attachments/assets/ddaf81e2-6aea-485f-a8e8-483013e8637d)

**Comment by E1izabeth** [comment]
Thank you for bug report. I reproduced the issue.

**Comment by serge-rider** [comment]
Fixed (table type search was broken in #23203)
