### ISSUE TITLE
Unexpected char 0x7279 at 28 in X-Trino-Source value

### ISSUE THREAD

**Issue by stanhaishan** [dbeaver/dbeaver#35336]
### Description

SQL 错误: Error executing query: Unexpected char 0x7279 at 28 in X-Trino-Source value: DBeaver 24.1.4 - SQLEditor 

### DBeaver Version

24.1.4

### Operating System

windows 10

**Comment by ShadelessFox** [comment]
Hello @stanhaishan,

Please provide some information that would assist us in reproducing your issue.

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
