### ISSUE TITLE
Open file using drag and drop doesn't anymore

### ISSUE THREAD

**Issue by TheSharpSwan** [dbeaver/dbeaver#3533]
Hi, 
since a couple of version i see that the drag and drop feature to open a .sql file doesn't work anymore.

**Comment by serge-rider** [comment]
Weird.
I saw something like that but it was resolved by restarting the client.
Could you try to close other editors and retry? Also try to drop in editor tabs area.

**Comment by TheSharpSwan** [comment]
A reboot solved the problem.

Weird.
