### ISSUE TITLE
Cannot Login to remote mysql server 8.4, faced error "Plugin mysql native_password is not installed"

### ISSUE THREAD

**Issue by rmpasswd** [dbeaver/dbeaver#35337]
### Description

I faced same problem in Workbench and now in DBeaver. Workbench did give warning that it didn't support newer mysql 8.4

When trying to login to remote mysql server 8.4 it gave this error:
![image](https://github.com/user-attachments/assets/9ce346ec-7caa-47c1-ab46-e2ba4a6e5273)

It means that that plugin is not installed in my newer mysql 8.4 Well thats because in 8.4 use cache_sha2_password.

**My question is how to connect to mysql server using DBeaver(or workbench) without downgrading security to mysql_native_password** 

does the 'local client option' play any role in this?

### DBeaver Version

24.1.5.202408181605

### Operating System

Win10

### Database and driver

mysql-connector-j 8.2.0

**Comment by rmpasswd** [comment]
Installed the plugin by [adding this line:](https://dev.mysql.com/doc/refman/8.4/en/native-pluggable-authentication.html#native-pluggable-authentication-installation)
![image](https://github.com/user-attachments/assets/3e16dac9-5cbf-4841-9cd5-5dd10c912d74)

now DBeaver and Workbench connect successfully. Even though all user passwords are using _caching_sha2_password_ plugin...

**Comment by inspire22** [comment]
This still seems required for dbeaver? Then it won't work on 9.0 as even the plugin isn't supported there.  Wish there was a way to get dbeaver to not try and use this...
