### ISSUE TITLE
all connection profiles are DELETED during latest Community Edition Version 24.1.5.202408181605 update 

### ISSUE THREAD

**Issue by speed-57** [dbeaver/dbeaver#35335]
### Description

Why do we still seem to miss this in the "upgrade" regression testing?  If any?

### DBeaver Version

Community Edition: Version 24.1.5.202408181605

### Operating System

Window 10

### Database and driver

Oracle 

### Steps to reproduce

create a connection or 20 (to get the full disapointing effect) then upgrade from the previous latest to the now latest versions!

### Additional context

nothing special about this... just an upgrade

**Comment by E1izabeth** [comment]
Hi, @speed-57! Unfortunately, I can't reproduce the issue. Do you remember, what was the previous version you used?

**Comment by speed-57** [comment]
I don’t have the version.. but, it was the last, most recent… as I had update to it only a week or two ago before updating to the new latest on 8/26.

I was surprised as well.. usually my connection profiles move right over no problem… I did not check “reset settings”… only the first two items.. product and java …. In the upgrade process.

I have painstakingly recreated them all and exported as a backup … will make that part of the upgrade process from now on.  You guys might consider doing that during the process or give user the option / a reminder at least… ??

Steve

**Comment by E1izabeth** [comment]
Please clarify, if your connections in Navigator disappeared or Connection Profiles for Network handlers (SSH, SSL and so on) disappeared?

**Comment by E1izabeth** [comment]
Also please send us all DBeaver log files.
The log files are generated automatically and have .log extension. They are located in the %APPDATA%\DBeaverData\workspace6\\.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by ask9** [comment]
Maybe you somehow created/opened another workspace which is empty?
Try to find on your drive some files specific to DBeaver's workspaces, for example, file with name: 
`dbeaver-workspace.properties`

Let us know in which folders these files are stored on your machine.
Then try to click menu: 
`File -> Switch workspaces `-> choose each of you folders.

Here is example path:
`C:\Users\user\AppData\Roaming\DBeaverData\workspace6`

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
