### ISSUE TITLE
The word "information_schema" (which is a system schema) is not visible in suggestion list both for Default and New autocomplete

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35338]
### Description

It is expected that autocomplete suggests the word "information_schema".

Please also check all other kinds of databases.

https://github.com/user-attachments/assets/0fe56697-9326-43ff-8034-e29b460d5fc0

### DBeaver Version

Community Edition 24.1.5-202408122322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

**Comment by ged-yuko** [comment]
It is a "tables" keyword to blame here apparently. The information_schema is perfectly resolved. Try something like 
`select t.collation_name from information_schema.collations t;`
![изображение](https://github.com/user-attachments/assets/11519a9e-46f3-46ba-ab04-80b2f04ce154)

Also information_schema is being proposed at least in 24.0.4 with default autocompletion engine.
![изображение](https://github.com/user-attachments/assets/bbe236b7-af50-40c4-8300-83a2b8395b76)
![изображение](https://github.com/user-attachments/assets/e0bf6ca9-fc82-4c20-aa5e-81d1fd236b06)

**Comment by ask9** [comment]
Your first and third cases seems like work correctly on my side also.
This issue is only about the second case.
Look at what happens when typing, then pressing Ctrl + Space.
Why do we have different results?

https://github.com/user-attachments/assets/bd4dac00-96db-43e7-9737-53610e5fc450

**Comment by E1izabeth** [comment]
@ask9 if you want to see `information_schema` in the list of proposals, you need to turn on reading information about system objects. Open context menu on the connection and turn on `Connection view-<Show system objects`. If it's not set, DBeaver doesn't read metadata about this schema and objects inside.
![image](https://github.com/user-attachments/assets/9beb8830-3377-417e-a8bb-0bc26d56179d)

**Comment by ask9** [comment]
Thank you!
It fixes the issue!
It was not obvious for me that displaying/hiding items in a tree impacts autocomplete.
I expected autocomplete should take into account all the available objects in a database in spite of active filters.

**Comment by E1izabeth** [comment]
We don't read metadata for system object by default, as it can significantly affect performance on large enterprise databases
