### ISSUE TITLE
can't drop sequence when it's inside a schema

### ISSUE THREAD

**Issue by aledmb** [dbeaver/dbeaver#3534]
My databases are organized into several schemas and each schema has it's own sequences.

DBeaver will not let me drop those sequences using the UI delete right-click menu option, because it generates SQL that does not include the schema name.

it generates this:
DROP SEQUENCE example;

instead of this:
DROP SEQUENCE schema_name.example;

**Comment by serge-rider** [comment]
I assume you meant PostgreSQL.
Thanks for report
