### ISSUE TITLE
[CUBRID] Create, edit and drop User by using UI

### ISSUE THREAD

**Issue by rathana-pvs** [dbeaver/dbeaver#35351]
**Description**

- Add UI plugin to allow user can create, updated and delete user.

**Comment by E1izabeth** [comment]
Thank you for request

**Comment by arhayka** [comment]
Hello, @rathana-pvs ! Thank you for being with DBeaver! We appreciate your support and want to send you a compliment. Please write to an email [anna.pozdeeva@dbeaver.com](mailto:anna.pozdeeva@dbeaver.com) and provide your nickname in GitHub and shipping details: First and Last Name, Email, Contact phone, Full Address (apt, street, city, state, country, post code).
