### ISSUE TITLE
[CUBRID] Create Procedure/Function by using UI

### ISSUE THREAD

**Issue by longhaseng52** [dbeaver/dbeaver#35360]
Add UI plugin to allow user can create procedure/function.

**Comment by serge-rider** [comment]
PR fails with conflict (because of previous PR merge)

**Comment by longhaseng52** [comment]
> PR fails with conflict (because of previous PR merge)

Hello @serge-rider, I have already solved the conflict.

**Comment by arhayka** [comment]
Hello, @longhaseng52! Thank you for being with DBeaver! We appreciate your support and want to send you a compliment. Please write to an email [anna.pozdeeva@dbeaver.com](mailto:anna.pozdeeva@dbeaver.com) and provide your nickname in GitHub and shipping details: First and Last Name, Email, Contact phone, Full Address (apt, street, city, state, country, post code).
