### ISSUE TITLE
Inappropriate type mapping in data export from MSSQL to PostgreSQL

### ISSUE THREAD

**Issue by alexkoay** [dbeaver/dbeaver#3536]
Not sure if it's a DBeaver issue directly, or if it's due to the JDBC type mapping configured in the different database connectors, but when I try to export data from a SQL Server database to a PostgreSQL table, some of the type mappings are weird. The ones I've noticed so far is that `datetime` in MSSQL will map to `date` in PG instead of `timestamp` and `nvarchar` to `char` instead of `varchar`.

**Comment by uslss** [comment]
not reproducible anymore.
ticket closed
