### ISSUE TITLE
Unexpected displaying of array value returned from ClickHouse JDBC driver

### ISSUE THREAD

**Issue by tobia** [dbeaver/dbeaver#3537]
Selecting a simple numerical array from ClickHouse:

```sql
select [1,2,3] as test_array
```

results in an opaque array value, both in grid view and in record view:

![dbeaver1](https://user-images.githubusercontent.com/48756/40711842-7f7388e4-63fc-11e8-9799-d5ac40072120.png)

![dbeaver2](https://user-images.githubusercontent.com/48756/40711843-7f9a4006-63fc-11e8-8944-6643d768e1d2.png)

`[J` is the Java class name for a `long[]` which is what is being returned here.

Trying the same query from a simple Groovy script (yes, all the import noise is required):

```groovy
@GrabConfig(systemClassLoader=true)
@Grapes([
  @Grab('ru.yandex.clickhouse:clickhouse-jdbc:+')
, @Grab('org.slf4j:slf4j-nop:+')
])
import groovy.sql.Sql
Class.forName('ru.yandex.clickhouse.ClickHouseDriver')

DB = Sql.newInstance('jdbc:clickhouse://clickhouse:8123')

def arr = DB.firstRow('select [1,2,3] as test_array').test_array
println arr.class.name
println arr
```

I can see that it returns an actual array of longs:

    [J
    [1, 2, 3]

**Comment by serge-rider** [comment]
Clickhouse  driver is tricky. According to JDBC API it should return java.sql.Array objects instead of native Java arrays. However I think we can make some workaround for it..

**Comment by serge-rider** [comment]
Please test it in 5.1
