### ISSUE TITLE
Explain Execution Plan shows only 4 columns

### ISSUE THREAD

**Issue by m3c-ode** [dbeaver/dbeaver#35381]
### Description

Trying this feature, I do not get options to choose some other valuable information (time...) such as displayed on the wiki

My view:
![image](https://github.com/user-attachments/assets/2435333e-3b4a-452c-96da-430862655769)

Wiki page: 
https://dbeaver.com/docs/dbeaver/Query-Execution-Plan/#simple-plan-view

Not sure why.

### DBeaver Version

community  24.1.5.202408181605

### Operating System

Windows 

### Database and driver

MySql

**Comment by E1izabeth** [comment]
Hi, @m3c-ode 
Different databases have different number of columns in Execution plan. Mysql has the ones you observe.
