### ISSUE TITLE
Can't create output directory

### ISSUE THREAD

**Issue by AimeePrior** [dbeaver/dbeaver#35388]
### Description

Hi,
we run composite tasks early each day but they all failed to output this morning, despite showing they had run successfully. The log shows  'Can't create output directory' after each Perform Data Transfer.
These are tasks that run 50+ data exports daily between them and we have not had this issue before. The same happens when trying to run each data export individually, but works when running each SQL code manually and then manually exporting the data. 
What can we do to resolve it so we don't have to run these reports manually again tomorrow?

### DBeaver Version

Enterprise Edition 23.0.0.202303131136

### Database and driver

PostgreSQL JDBC Driver

### Steps to reproduce

run data exports on their own or as part of a composite task

**Comment by Destrolaric** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by AimeePrior** [comment]
Hi, this has now been resolved. Thank you
