### ISSUE TITLE
Pinned tabs are overwritten if statistics tab is present

### ISSUE THREAD

**Issue by JTMosaic** [dbeaver/dbeaver#35380]
### Description

The pinned tab overwrite issue rears its ugly head again.

If the "Show Statistics Tab" setting is set to "Always" or otherwise appears, it too must be pinned or the pinned tab is overwritten.

### DBeaver Version

24.1.5

### Operating System

macOS

### Steps to reproduce

1. Set "Show statistics tab" to "Always"
2. Run a query. Two tabs will be generated: One for the query results, one for the statistics
3. Pin the results tab
4. Run a different query. The results tab is overwritten, even though it is pinned.
5. Pin the statistics tab
6. Run the first query. A new results tab is created

### Additional context

Related to #35072 #35173  #35203  #35238

**Comment by E1izabeth** [comment]
Thank you for bug report. I reproduced the issue
