### ISSUE TITLE
 Import from CSV not getting all rows

### ISSUE THREAD

**Issue by SeppBerkner** [dbeaver/dbeaver#35386]
### Description

Similar to #14227 I have a CSV with 30354 entries. When uploading it to my Postgres database using DBeaver only 15781 entries are uploaded. And it is always the same amount for every run I try.

### DBeaver Version

Community Edition 24.1.0

### Operating System

macOS Ventura 13.6.1

### Database and driver

PostgreSQL 12.5
PostgreSQL JDBC Driver

### Steps to reproduce

Same as in #14227

### Additional context

Same as in #14227

**Comment by E1izabeth** [comment]
Similar discussion https://github.com/orgs/dbeaver/discussions/35154

**Comment by SeppBerkner** [comment]
Strangely, a second CSV with more entries (40942) is uploaded correctly. So whether it has to do with the CSV itself or there is a specific range of rows that causes this issue. The process planer also just considers the 15781 rows and stop there (even though I set the batch limit to 50000).

![grafik](https://github.com/user-attachments/assets/f65fbb3d-c902-4888-921a-409cb685ea19)

Also, in contrast to other CSV files where the newly created table is opened in the UI when the process is finished, this is not the case for the problematic CSV

**Comment by Destrolaric** [comment]
Hi, if possible,  could you provide a similar example of row 15782 data.

**Comment by E1izabeth** [comment]
For now, we're unable to reproduce the issue. Could you try reproducing it again and send us log files? You can collect them to archive automatically with `Help->Collect Diagnostic Info`
![image](https://github.com/user-attachments/assets/51c7ca2e-6be2-489e-b495-028b9aa0e386)

**Comment by E1izabeth** [comment]
Seems this issue is stale. Let me know if the problem is still actual for you and provide requested log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.
