### ISSUE TITLE
Mock Data Template extension

### ISSUE THREAD

**Issue by GHNewbiee** [dbeaver/dbeaver#3538]
When text is chosen, 
> Random length substrings from the 'Lorem ipsum text appears as a Template.

It would be a good idea if template could also be a constant string with a variable; for example `string%`: 'string' is the constant string and after the variable applies it becomes text like: 'string1', 'string2', etc.

In future, more flexible templates would be adopted like: `string1%string2%`. By this way, more complicated type data could be entered; for example ranges: '[%, %*5)'.

Note: I find it more convenient to enter mock data like: column_name_1, column_name_2, etc. than entering pure random text. I can more easily define problems in queries by observing the return rows because row identification is easier (1, 15, 100, etc.)

**Comment by GHNewbiee** [comment]
I have a table with columns `name`, `surname`, `integer_range`.

I want to populate it with the following mock data:
```

name1, surname1, [0, 1)

name2, surnname2, [1, 2)

name3, surname3, [2, 3)

...

name100..., surname100..., [100...-1, 100...)
```

Can I do it with the current options that dbeaver gives me?

Note: Please, don't get stuck to `name100..., surname100..., [100...-1, 100...)`. It is not important at all!

**Comment by serge-rider** [comment]
We'll add this feature (Template generator) in EE 5.1 firstly. As it is linked with many other EE generators.
In future we plan to add such feature in CE version as well (it has to be improved and work with other generators in some dynamic way).

Here is Wiki article with instructions (including this new generator)

Thanks for good idea.
