### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by anisch** [dbeaver/dbeaver#35387]
### Description

crash after edit
[dbeaver-diagnostic-info-1724930643355.zip](https://github.com/user-attachments/files/16798346/dbeaver-diagnostic-info-1724930643355.zip)

### DBeaver Version

Community Editon 24.1.5

### Operating System

Linux Mint 22 Wilma

### Database and driver

Server: MariaDB 10.11.6-MariaDB-1:10.11.6+maria~ubu2204 from Docker image MariaDB Connector/J 2.7.1
Driver: MariaDB Connector/J 2.7.1

### Steps to reproduce

1. Edit Cell Content
2. Leave Cell with TAB or ENTER

**Comment by Destrolaric** [comment]
Hi, you have a lot of warnings about missing `xdg-mime` library, could you try installing it and see if it works.

**Comment by anisch** [comment]
I can see that there are already present on the system.
```
~$ which xdg-mime
/usr/bin/xdg-mime

~$ xdg-mime --version
xdg-mime 1.1.3
```

**Comment by Destrolaric** [comment]
@anisch How DBeaver was installed? Is it as a part of snap/flatpak package, or by using deb installation?

**Comment by anisch** [comment]
> @anisch How DBeaver was installed? Is it as a part of snap/flatpak package, or by using deb installation?

Some time ago I switch from .deb to flatpack to get the automatic updates.

**Comment by anisch** [comment]
I tested the previous installation via .deb and ist works fine. I think there is something wrong with the flatpak installation.

**Comment by flambchap** [comment]
@anisch, I cannot reproduce the issue in the latest flatpak release. What column type do you edit to cause a crash?

**Comment by anisch** [comment]
After updating to the latest flatpak release, the `ENTER` key is now working. But the `TAB` key is still broken. It can happen on every cell. 
I go into some cell and press `TAB`, `TAB` ... and then it crashes.
[dbeaver-diagnostic-info-1728382316153.zip](https://github.com/user-attachments/files/17291792/dbeaver-diagnostic-info-1728382316153.zip)

**Comment by flambchap** [comment]
@anisch, Can you please make a screen recording of a crash?

**Comment by anisch** [comment]
[dbeaver_1.webm](https://github.com/user-attachments/assets/01813f81-09be-4e54-a7e3-b970ebc50e51)
[dbeaver_2.webm](https://github.com/user-attachments/assets/ed108517-dc4b-4ef5-a18e-9a870988dd40)
[dbeaver-diagnostic-info-1728393270243.zip](https://github.com/user-attachments/files/17293863/dbeaver-diagnostic-info-1728393270243.zip)

**Comment by flambchap** [comment]
Thank you. I need a bit of time to figure out how to proceed. I'll keep you posted.

**Comment by anisch** [comment]
Starting the DBeaver flatpak package from bash, it looks like there is something bad happen on the jvm.
[bash.log](https://github.com/user-attachments/files/17307170/bash.log)
[hs_err_pid24.log](https://github.com/user-attachments/files/17307171/hs_err_pid24.log)

**Comment by flambchap** [comment]
@anisch Thank you. The JVM process crashed while accessing native code on the platform. I believe this issue can be fixed by the team that packages flatpacks by providing the missing libraries.

By the way, does this workaround work for you? https://github.com/dbeaver/dbeaver/issues/35977#issuecomment-2429662054

**Comment by anisch** [comment]
Yes, there are no crashes with this workaround.

**Comment by E1izabeth** [comment]
Thank you. I'm closing this issue as a duplicate of #19709
