### ISSUE TITLE
Loading parametrs from others configuration file

### ISSUE THREAD

**Issue by HocKu7** [dbeaver/dbeaver#35391]
We would like to have the ability to launch application with custom parameters like -Xmx, etc. In order to do it, we need to consider the ability to launch the application with another configuration file (not dbeaver.ini)

**Comment by E1izabeth** [comment]
Connected to 
#7727
#7546
#21806
#16187
#12683
#35080

**Comment by arhayka** [comment]
This will be implemented here: https://github.com/dbeaver/dbeaver/issues/35080
