### ISSUE TITLE
Mock data generation fails

### ISSUE THREAD

**Issue by GHNewbiee** [dbeaver/dbeaver#3539]
I have a table with the following columns:

```
column1: id  -- PK
column2: integer  -- FK
column3: citext NOT NULL
column4: citext
```

I am trying to generate data for columns 3 and 4 by using text but I receive the following error:

> Error generating mock data: bound must be positive

Please advice.
Tia

**Comment by efradkin** [comment]
@GHNewbiee did you try to change the generators and their parameters? Are you seeing the error with any generators settings? Are there any data in the table that is related to the column2 FK?

**Comment by GHNewbiee** [comment]
Q1: Yes, I did try to change parameters of the text option.
Q2: Why should I change generator type when it is obviously text? What is the purpose of choosing integer for a text type?
Q3: Yes, there are. It was populated earlier.

I shall carry out more tests and come later.

**Comment by efradkin** [comment]
> Q2: Why should I change generator type when it is obviously text? 
Why are you sure you have a problem with the text column?
Please take a look at the debug/error log (https://github.com/dbeaver/dbeaver/wiki/Log-files). Is there any exception stack messages there?
Thanks.

**Comment by GHNewbiee** [comment]
Hi,

I think I have found the "problem":

When the length of the `Template` **is less than** `Min Length` then an error arises.

For example: Set `Template` as "name_" and `Min Length` as 6, then you will get the error. I chose this since I wanted to get `name_1` which consists of 6 characters.

Tia

**Comment by efradkin** [comment]
Fixed
