### ISSUE TITLE
Unwanted array representation introduced with 24.1.1 – 24.1.5

### ISSUE THREAD

**Issue by btanner2** [dbeaver/dbeaver#35403]
### Description

Please take a look at this SQL

```
SELECT
ARRAY[1,2,3,4] AS a,
ARRAY[1,2,3,4] AS b
```

`**This is the result in 24.1.0**`
![24 1 0](https://github.com/user-attachments/assets/14be49b0-4e59-40aa-96ad-fd96c261c3cf)

`**This is the result in 24.1.1**`
![24 1 1a](https://github.com/user-attachments/assets/08761557-8a33-4a6f-bd27-7de5df1dc0cb)

`**This is the result in 24.1.1 with only one column**`
![24 1 1b](https://github.com/user-attachments/assets/8e8bdd82-bd84-45b1-8f11-b96684b7d2f7)

The presentation of arrays seems to change with 24.1.1 if more than one column returned. This is really a disadvantageous behavior. We need always all arrays expanded like in 24.1.0.

How can that be changed? Is it a bug?

Kind regards Brian
 

### DBeaver Version

24.1.1 - 24.1.5

**Comment by E1izabeth** [comment]
Thank you for bug report. It seems to be fixed already.
Please try Early Access version https://dbeaver.io/files/ea/ or wait for the next release 22.2.0

**Comment by btanner2** [comment]
Hi,

I am just using the new version v24.2.1, but the bug is still there. It is reproducible with the given example.

Could you please check that?

Thx
Brian

**Comment by E1izabeth** [comment]
Thank you for the update. We're working on it.
I expect it will be fixed in 24.2.2

**Comment by uslss** [comment]
Issue will be fixed in 24.2.2

![image](https://github.com/user-attachments/assets/662e57e5-f940-441a-b73f-418ef11cc2c4)

**Comment by btanner2** [comment]
Thanks for fixing the issue. How can I restore the representation to the way it was in version 24.1.0? I need to always display all values in an array, at least when the count is less than 10 or so. It should look like this:

![24 1 0](https://github.com/user-attachments/assets/14be49b0-4e59-40aa-96ad-fd96c261c3cf)

**Comment by E1izabeth** [comment]
@btanner2 there is no way to do it right now. However, I created the issue #35904. You can vote for it with 👍🏻  under the issue description to promote it to a higher priority
