### ISSUE TITLE
Connecting to a Spark SQL endpoint is very slow - 67 seconds

### ISSUE THREAD

**Issue by alberttwong** [dbeaver/dbeaver#35415]
### Description

Connecting to a Spark SQL endpoint is very slow - 67 seconds
[dbeaver-diagnostic-info-1725054025842.zip](https://github.com/user-attachments/files/16822226/dbeaver-diagnostic-info-1725054025842.zip)

### DBeaver Version

Community Version 24.1.5.202408181605

### Operating System

14.6.1 (23G93)

### Database and driver

the one that is bundled in community version.

**Comment by E1izabeth** [comment]
Hi, @alberttwong 
Unfortunately, I can't reproduce the issue. Is your database huge? How many tables do you have there?

**Comment by E1izabeth** [comment]
Seems this issue is stale. If the problem is still actual please let me know and provide the answers to the [questions](https://github.com/dbeaver/dbeaver/issues/35415#issuecomment-2378844693).
