### ISSUE TITLE
Aborted transaction blocks DBeaver

### ISSUE THREAD

**Issue by ivanhigueram** [dbeaver/dbeaver#3541]
Hi! 

I'm running a simple query like this:

```
SELECT 
id_column
sum(column_text),
sum(column_integer)
FROM schema.table
GROUP BY column_group
```

As expected a SQL error stop the execution of the code and informs that the `SUM` function does not exist for the specified column type (text). Nonetheless, after correcting the error and re-running the code, a new message error appears saying that the transaction was aborted, and that all commands will be ignored until the transaction ends [see attached image].

<img width="606" alt="dbeaver_error" src="https://user-images.githubusercontent.com/9004403/40747293-7475a9ce-6422-11e8-8a69-2667c4ccbe8a.png">

I tried to fix the error in the command line running `ROLLBACK` in `psql`, but the error keeps appearing even making simple `SELECT` queries. Checking in the `pg_stat_activity` table, the wrong query appears as `idle in transaction (aborted)`. The only way to keep working from DBeaver is killing the process using the `pid` and re-starting the connection to the server. 

Is this caused by a bad configuration on my end? I've used DBeaver in a daily basis and this is the first time I encounter this issue. I just recently upgrade it to the last version.  

Thanks :)

**Comment by serge-rider** [comment]
This is PostgreSQL-specific behavior
You can:
- Commit or rollback current transaction from main toolbar (or main menu)
- Switch to auto-commit mode
- Enable "Rollback on error" option:
![image](https://user-images.githubusercontent.com/6398845/40799376-16e9cdc2-6516-11e8-9f00-070fb907e239.png)

**Comment by alamothe** [comment]
What a garbage software
