### ISSUE TITLE
PC crashes when tooltip text is too long

### ISSUE THREAD

**Issue by jayeeson** [dbeaver/dbeaver#35411]
### Description

When hovering over a cell in a table and the tooltip text would be too long, it takes the whole screen and is truncated. This causes the entire PC to crash.

[dbeaver_tooltip_crash.log](https://github.com/user-attachments/files/16819122/dbeaver_tooltip_crash.log)

### DBeaver Version

24.1.5

### Operating System

Ubuntu 24.04

### Database and driver

Mysql 8.2.0

### Steps to reproduce

1. Open a table
2. open either the Properties or Data view
3. hover over a cell that has a lot of text content
4. Text is larger than the screen
5. result: crash

### Additional context

Tested back to version 23.3.5, still reproducible

**Comment by E1izabeth** [comment]
Thank you for bug report.
Unfortunately, DBeaver logs doesn't tell a lot in case of crash. Could you try looking for java fatal logs? They're called `hs_err_PID.log`, where `PID` is a number and usually resides in the same directory where the DBeaver launcher is.
You can find information about them here https://dbeaver.com/docs/dbeaver/Log-files/#java-fatal-logs

**Comment by jayeeson** [comment]
[dbeaver-debug-1725031480203.log](https://github.com/user-attachments/files/16820911/dbeaver-debug-1725031480203.log)

This file has the error.

**Comment by ShadelessFox** [comment]
What do you mean by "crash"? Does the app just close, or does an error appear in the error log? If the former, please look for the fatal logs mentioned in https://github.com/dbeaver/dbeaver/issues/35411#issuecomment-2321755946. Regular debug logs won't help there.

**Comment by serge-rider** [comment]
I think we can just truncate long tooltips. It doesn't make sense to have too big ones.

**Comment by jayeeson** [comment]
> What do you mean by "crash"? Does the app just close, or does an error appear in the error log? If the former, please look for the fatal logs mentioned in [#35411 (comment)](https://github.com/dbeaver/dbeaver/issues/35411#issuecomment-2321755946). Regular debug logs won't help there.

"crash": The entire Ubuntu desktop crashes with an irrecoverable error, and I am forced to log out + login
