### ISSUE TITLE
Ctrl+Maj+X does not work anymore to convert into uppercase

### ISSUE THREAD

**Issue by Thomas-LEILLET-Sanofi** [dbeaver/dbeaver#35424]
### Description

Ctrl+Maj+X does not work anymore to convert into uppercase (Ctrl+Maj+Y still works to convert into lowercase)

### DBeaver Version

CE 24.2.0.202409011551

### Operating System

Win11

**Comment by ShadelessFox** [comment]
Hello @Thomas-LEILLET-Sanofi,

  Please ensure you have the shortcut set here, and its scope is **Editing Text**:
![image](https://github.com/user-attachments/assets/86cc0882-531b-4825-821d-3a078dc778e5)

**Comment by Thomas-LEILLET-Sanofi** [comment]
Hello, I have ensure such. Impossible to input Ctrl+Shift+X, it seems the entry is rejected (it is well set as by default, but inactive in the effects - I managed to replace it by Ctrl+Shift+U, it's working. If I set back the default, still not working. If I manually type Ctrl+Shift+X, it does not accept the input (Ctrl is detected, Shift is detected, but X is rejected : any possible conflict with another shortcut ?)

I just updated to current version this morning.

**Comment by ShadelessFox** [comment]
You indeed might have conflicts with another command - try typing the shortcut in the search box to see where it's used

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
