### ISSUE TITLE
Dump Database / Impossible to have a good dump

### ISSUE THREAD

**Issue by df-romain-francois** [dbeaver/dbeaver#35428]
### Description

Hello,

After dump database with the new update 24.2

- some tables are not DROP
- some data are not dumping
![Capture d'écran 2024-09-02 150020](https://github.com/user-attachments/assets/48d4041e-fa3c-428e-b88f-1920e3974607)
- some data are trunked 
![Capture d'écran 2024-09-02 145949](https://github.com/user-attachments/assets/fcb74224-8e18-402c-a608-2a1fc15e941d)

3 dumps in less than 5min with no active works : 116Mo, 124Mo, 118Mo
It seems random for the forgotten lines.

No problem this week before the software update.

Thx for this software.

### DBeaver Version

24.2

### Operating System

Windows 11

### Database and driver

MariaDB

**Comment by NGRichter** [comment]
Same issue here

### DBeaver Version
24.2.0.202409011551
### Operating System
MacOS 14.6.1
### Database and driver
MySQL

**Comment by thiagoolivier** [comment]
Had the same issue today.
Dumps are generated but when restoring, it fails.

DBeaver Version: 24.2.0.202409011551
OS: Windows 10 x64

**Comment by E1izabeth** [comment]
Thanks for the bug report.
This is a duplicate of https://github.com/dbeaver/dbeaver/issues/35421. Please track the progress on the issue there.
