### ISSUE TITLE
Dump dialog change size during the dump. No text wrap in log

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#35426]
### Description

Dump dialog change size during the dump. No text wrap in log

![image](https://github.com/user-attachments/assets/e6d94f65-563c-4af2-94c8-dedc273bb65b)

### DBeaver Version

24.2.0

### Operating System

win11

### Database and driver

PG, mysql

**Comment by ask9** [comment]
Please also fix "no text wrap" for all other similar windows displaying logs (highlighted with yellow): 

![0000003603](https://github.com/user-attachments/assets/82773988-cbc3-4cb8-b78b-15d3a2d7e092)
