### ISSUE TITLE
Lag while exporting data  (to CSV, or other formats)

### ISSUE THREAD

**Issue by LaxManan1** [dbeaver/dbeaver#35423]
It takes a long time to export the data, results returned by a query, connected to RedShift or Oracle. 
I would like to see the results exported without a Process Query: Execute Query, which takes, at times, longer than the actual query. In one other tool I use, the export function is very fast, if the number of rows exported is less than 15-20 k. 

Could someone optimize this flow?

Regards

**Comment by MashaKorax** [comment]
Could you please provide log files?

**Comment by Matvey16** [comment]
@LaxManan1 Can you please check if the same query in SQL Editor would be faster than export without a limit of 200 rows (that is a default limit in our SQL Editor)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide requested information.

**Comment by LaxManan1** [comment]
Apologies, I couldn't respond earlier. I will remove the limit and try exporting again. If there is still a delay, will send the logs.
