### ISSUE TITLE
Can't see included columns on index

### ISSUE THREAD

**Issue by LukeWebber** [dbeaver/dbeaver#3542]
I'm a big fan of DBeaver, but I'm having a small problem. This is on SQL Server 2016 Developer Edition and DBeaver 5.0.6 Community Edition.
We have indices with INCLUDEd columns, but they don't seem to show up anywhere. The table in question is partitioned, but the index is not the clustered index.
For example, this index...

CREATE NONCLUSTERED INDEX [THISTALLIDX02_ANZ] ON [TRANS_HISTORY_ALL]
(
	[LINK_NUMBER] ASC,
	[TRANSACTION_ID] ASC
)
**INCLUDE ( [TRANSACTION_TYPE])** 

I can't see TRANSACTION_TYPE in the index properties. This is affecting both partitioned and non-partitions indices.
Note that this is not a problem in DB2, where the Include indicator is shown in the Ascending/Descending column.
Also note that you can find these include columns in SQL Server by checking if sys.index_columns.is_included_column is non-zero.

Many thanks, and congratulations on a great product.

**Comment by iainelder** [comment]
@LukeWebber, did you resolve this?

We wanted to create a include index in a PostgreSQL database, but couldn't see how to do it in the graphical interface.

In the end we created it with SQL statements.

**Comment by LukeWebber** [comment]
No, I'm afraid it seems to be a limitation of DBeaver on SQL Server and, I
guess, also on PostgreSQL. It works just fine on DB2.

I always create my DB objects through scripts or via FluentMigrator, so it
wasn't a huge problem for me. And I never use include columns myself.

**Comment by LonwoLonwo** [comment]
@LukeWebber it is still actual for you? I can see included column in Indexes Properties.

**Comment by LukeWebber** [comment]
Hi @LonwoLonwo . Yes, it's still a problem for me, using the jTDS driver...

CREATE INDEX IDX_Test ON IndexTest (Name) INCLUDE (PostCode)

![image](https://user-images.githubusercontent.com/10580184/97834497-1e5b5280-1d2c-11eb-81cb-1b820a21a9ac.png)

**Comment by LonwoLonwo** [comment]
@LukeWebber May be, it is driver issue? i use Microsoft JDBC Driver com.microsoft.sqlserver:mssql-jdbc.8.2.0
And what DBeaver version you use now?
