### ISSUE TITLE
Data is cleared ，when configure columns at sessions of progresql.

### ISSUE THREAD

**Issue by highgoyangguoqing** [dbeaver/dbeaver#3543]
At editor of sessions,nothing is selected when I configure columns. 
![image](https://user-images.githubusercontent.com/34262632/40765183-41c6a796-64de-11e8-8950-f143279c8903.png)
After OK is selected,the editor is showed 
![image](https://user-images.githubusercontent.com/34262632/40765248-73a274f2-64de-11e8-9f5c-52948f652f0d.png)
 I want to show some columns,so I configure columns again.
![image](https://user-images.githubusercontent.com/34262632/40765376-d22aeb80-64de-11e8-8aa6-a6177805dabd.png)
but all data is cleared at this moment。
![image](https://user-images.githubusercontent.com/34262632/40765505-38fde1aa-64df-11e8-80d6-f02ad20f9778.png)
Please check. Thanks

**Comment by serge-rider** [comment]
Both issues will be fixed in 5.1
Thanks for report
