### ISSUE TITLE
INFORMATION_SCHEMA views aren't recognized in SQL Server

### ISSUE THREAD

**Issue by Tix2garr** [dbeaver/dbeaver#35430]
### Description

When trying to use INFORMATION_SCHEMA in SQL Server, the views are marked as not found.  Such as:

`SELECT *
FROM INFORMATION_SCHEMA.ROUTINES`

I get a message _Table INFORMATION_SCHEMA.ROUTINES not found_, like:

SELECT *
_Table INFORMATION_SCHEMA.ROUTINES not found_
FROM INFORMATION_SCHEMA._ROUTINES_

If I just have

SELECT *
FROM INFORMATION_SCHEMA

and don't type fast enough, I get 
_Table INFORMATION_SCHEMA not found_

The new analysis is nice, and it's getting better!, but still has some issues.  <wry smile>

[dbeaver-diagnostic-info-1725285105290.zip](https://github.com/user-attachments/files/16838713/dbeaver-diagnostic-info-1725285105290.zip)

### DBeaver Version

Community edition 24.2.0

### Operating System

Windows 10

### Database and driver

Microsoft JDBC Driver for SQL Server 
12.8.0.jre11

### Steps to reproduce

1. Connect to SQL Server
2. Type in 

SELECT *
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE

and wait for the error.  <wry smile>

**Comment by E1izabeth** [comment]
Hi, @Tix2garr 
Thank you for bug report. For now I can't reproduce the issue. However, I see a lot of errors saying that connection is broken. Could you check if this bug is stable reproducible for you to check if it's related to the connection state?

**Comment by uslss** [comment]
Thanks for the report.
The issue is reproducible for me after reconnecting and the script reopen

https://github.com/user-attachments/assets/13e43a85-fb15-437a-8d37-9ad2e1e671c0
