### ISSUE TITLE
How to turn off feature "Toggle left panel (Database Navigator + Project)" on double click to a tab in sql editor?

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35436]
### Description

I found out it is not convenient for me due to accidential false-clicks to a tab.
I like the hiding-feature itself, but I want to have more control over that behavior.
I would like to have a hotkey to toggle the visibililty of the left panel, rather than double click to a tab.

1. how to turn off the double click on a tab for hiding the panel.
2. is there any hotkey for the same action? If not, I suggest to add it.

I know there are hotkeys to toggle only Database navigator, or only Project panel, but I look for the hotkey to toggle the whole panel with both (Database navigator + Project).

### DBeaver Version

Community Edition 24.1.5-202408122322

### Operating System

Windows 10

### Steps to reproduce

- double click to any tab in sql editor

**Comment by MashaKorax** [comment]
It is possible using ctrl + m. Could you verify this?

**Comment by ask9** [comment]
@MashaKorax  Yes, that's exactly what I looked for! Second question answered!

Maybe you also know the answer to my first question:
1. how to turn off the double click on a tab for hiding the panel?

**Comment by Matvey16** [comment]
@ask9 That is an Eclipse feature that can't be disabled by individual users.
