### ISSUE TITLE
Use the table's first letter as the alias instead of "X" when generating queries from the "Click to open query in editor" button

### ISSUE THREAD

**Issue by rasputino** [dbeaver/dbeaver#35445]
**Is your feature request related to a problem? Please describe.**  
When using the "Click to open query in editor" button while viewing filters on a table in DBeaver, the generated query always assigns the alias "X" to the table. This can be frustrating, especially when working with multiple tables, as it is not very intuitive and requires extra effort to change the alias to something more meaningful.

![image](https://github.com/user-attachments/assets/d8ca9a10-90fd-48b0-a87f-0c33617365f2)

**Describe the solution you'd like**  
I would like DBeaver to automatically use the first letter of the table's name as the alias in the generated query. For example, if the table name is "public.table," the query should look like this:
```sql
SELECT t.* FROM public.table t
```

instead of:

```sql
SELECT x.* FROM public.table x
```

**Describe alternatives you've considered**
An alternative solution could be allowing users to configure a default alias pattern in the settings. However, in my opinion, automatically using the first letter of the table's name would be the most intuitive and efficient solution.

**Comment by E1izabeth** [comment]
Thank you for the idea
