### ISSUE TITLE
F6 Shorcut to hide Results Pane

### ISSUE THREAD

**Issue by lasmaty07** [dbeaver/dbeaver#3544]
recently updated to version 5.0.5 and the F6 keyboard shortcut (To hide the Results Pane ) is no longer working. According to the [Wiki](https://github.com/dbeaver/dbeaver/wiki/SQL-Editor) it should be working.

there's small arrow to hide it, but it does not serve the same purpose, because after executing a new query, stays hidden. (with the F6 shortcut did not)

Thanks

**Comment by lasmaty07** [comment]
well.. after a few time looking through the menus, I found that now is binded to `Ctrl+6` hotkey... changed back to `F6` in **Preferences -> General -> Keys: Togle Results Panel** .
 Way more comfortable with just one key
Please Update the Wiki

**Comment by serge-rider** [comment]
Wiki updated, thanks for noticing.

We have changed default shortcut because functional keys aren't always applicable (e.g. they have special meaning on MacOS and Linux, on some laptops you need to use fn+FX combination which is also not very convenient)

**Comment by nickolay** [comment]
The "Toggle results panel" shortcut is now `CTRL+T`, at least on Windows.

**Comment by MateusPitura** [comment]
For Ubuntu 24.04 and Dbeaver 25.3.2 is `CTRL+T`
