### ISSUE TITLE
Bind type does not appear.

### ISSUE THREAD

**Issue by devSonicgirl** [dbeaver/dbeaver#3545]
The bind type does not appear when executing procedure in oracle.
What settings should I set?

![capture-20180601-115242](https://user-images.githubusercontent.com/28799959/40818523-5b4ded32-6592-11e8-9287-64b020659b9d.jpg)

**Comment by jmiserez** [comment]
I have the same issue for all DB vendors, and I'm running the latest DBeaver 5.0.5 and the latest DB drivers. The screenshots in [this thread](https://dbeaver.io/forum/viewtopic.php?f=2&t=1812) suggest that this was a feature as far back as DBeaver 3.4.0.

Binding e.g. a DATE is not the same as using an expression like TO_DATE or similar, i.e. DB behaviour can be different when it comes to implicit vs. explicit casts.

**Comment by jmiserez** [comment]
I have the same issue for all DB vendors, and I'm running the latest DBeaver 5.0.5 and the latest DB drivers. The screenshots in this thread suggest that this was a feature as far back as DBeaver 3.4.0.

Does DBeaver actually bind the parameters using a PreparedStatement, or does it just replace the binds in the query string with the given expressions?

**Comment by serge-rider** [comment]
DBeaver do not bind prepared statement parameter, it just replaces parameter with specified value. So you can use expressions and any other SQL elements.

**Comment by jmiserez** [comment]
Thanks! I've been debugging some issues with binds in PreparedStatements and was wondering why I couldn't reproduce them using DBeaver.

Are there any plans to add support for "real" bind parameters? This would help a lot with debugging misbehaving or slow statements, as the DB behaviour and execution plans can be quite different with/without binds. Implementing this would probably be possible in a fairly generic way so it works for many DBs.
