### ISSUE TITLE
Schema Active/Catalog Ded  

### ISSUE THREAD

**Issue by CoolHanMatt** [dbeaver/dbeaver#35455]
### Description

My IT Department created a new schema for my team. However now DBeaver dosnt recognize the schema. I can see it in the navigator but must use fully qualified names to query tables. This is annoying and I cant figure out how to fix.

Does Not Work = SELECT * FROM Table1; (Object Table1 not recognized)
Does Work = SELECT * FROM coe.Table1;

I cannot figure out why DBeaver cannot see that schema in the catalog or i cannot change default. This is EE version 23.somthing

Any help would be appreciated. Just FYI I can query SQL but Im not a DBA etc.

TIA
![schemacoe](https://github.com/user-attachments/assets/e5820fff-2251-46c6-bef8-1985e07d42d7)

### DBeaver Version

23.something 

### Operating System

Windows 11

### Database and driver

MySQL

**Comment by E1izabeth** [comment]
Please try clicking on the button with active schema 
![image](https://github.com/user-attachments/assets/0931e029-829c-45df-ae57-8ce9a86ade9d)
And then switch active schema by double clicking on the desired one
![image](https://github.com/user-attachments/assets/ab25d500-9eb4-42df-82ca-7ca708aa6129)

**Comment by E1izabeth** [comment]
Never mind, I see on your screenshot, that you tried and don't get the schemas list there

**Comment by CoolHanMatt** [comment]
Thank you for your response.

I discovered this is an issue with SQL Server and not Dbeaver. I resolved
by having my admin assign a default schema to my user name.

Thank you for the help.

**Comment by E1izabeth** [comment]
Thank you. I'm closing the issue then.
