### ISSUE TITLE
Errors with Postgres driver download cause download dialog to open on each connection

### ISSUE THREAD

**Issue by cs-aquilance** [dbeaver/dbeaver#35466]
### Description

Creating a new connection to Postgres initiates the driver download automatically, however there appears to be some kind of error downloading the license file.  Because of that, the driver download dialog pops up every time when trying to connect to a Postgres database.

<img width="696" alt="SCR-20240904-iahf" src="https://github.com/user-attachments/assets/29e15247-8167-4cc1-9e63-4a1b617d0405">

Looking at the Driver Manager, I see the LICENSE file is red:

<img width="702" alt="SCR-20240904-iavi" src="https://github.com/user-attachments/assets/ffd21213-0166-444e-adaa-c0fa7749620c">

If I put that URL into my browser, it shows up just fine.  My only theory is that it may be related to being logged in to Github already?

When I look at the file system where the LICENSE file should be download, I see that the folder is empty.

### DBeaver Version

Community Edition: 24.2.0.202409011551

### Operating System

MacOS Sonoma 14.6.1

### Database and driver

Postgres 16 and newer Postgres driver

### Steps to reproduce

1. Create Postgres connection
2. Open connection

**Comment by E1izabeth** [comment]
Hi, @cs-aquilance 
Thank you for bug report. As a workaround, you can select this red item in Libraries list and press Delete. It's a license file, so it won't affect your connection.

**Comment by E1izabeth** [comment]
The link opens successfully for me, regardless of whether I am logged in or not.

**Comment by cs-aquilance** [comment]
> Hi, @cs-aquilance Thank you for bug report. As a workaround, you can select this red item in Libraries list and press Delete. It's a license file, so it won't affect your connection.

Thanks for the tip.  That does indeed seem to fix the continuous prompting.  I can't say why it gets in that state, but I can say that I completely deleted the DBeaverData folder out of ~/Library to see if a "clean" install would solve it, but ended up right back in the same place.  Very strange.

**Comment by E1izabeth** [comment]
For now I can't reproduce the issue with PostgreSQL driver downloading. However, I reproduced the issue with continuous prompting, if the link is wrong.

**Comment by Matvey16** [comment]
Reproduced it for MariaDB driver. This seems to be ecxlusive for MacOS

**Comment by serge-rider** [comment]
![image](https://github.com/user-attachments/assets/54a2da41-f575-469f-a382-ba4c2a4beaba)
![image](https://github.com/user-attachments/assets/29934bb7-358b-4dd4-9b4e-2a896e9ecac1)
