### ISSUE TITLE
Reinstalling extensions upon program update takes VERY long

### ISSUE THREAD

**Issue by Cris70** [dbeaver/dbeaver#3546]
When DBeaver is updated, the first time you launch it after update it asks you to update the extensions too.
If I say yes, DBeaver starts verifying the prerequisites and this phase takes a real LOT of time (like 20 minutes or so).
Then it finally prompts you to accept the license, you accept and click "next". At this point, the progress meter climbs up to about 14% and it stalls there. After a LOT of time (like 5 or 6 minutes) it warns me that I am installing software that is not signed (IIRC) and when I click "OK" it terminates the installation in a few seconds.
I think that those long pauses are not the way the update is supposed to work. Maybe a bug?

I am using DBeaver on linux openSUSE Tumbleweed. 

The extensions I have installed are: 
- DBeaver Office Support
- DBeaver SVG Extension

**Comment by serge-rider** [comment]
In most cases this is caused by the same problem as in #4201

Please reopen if problem will remain in 5.2.1+

**Comment by Cris70** [comment]
Problem is still very much alive.

This time, however, I had to break the update process due to time constraints, and I ended up having a detailed log that may shed some light on the problem (or maybe this log is new to DBeaver 6.1.0?).

Here it is:
```
Cannot complete the install because of a conflicting dependency.
  Software being installed: DBeaver SSHJ 1.0.23.201902031804 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.23.201902031804)
  Software currently installed: DBeaver 6.1.0.201906091949 (org.jkiss.dbeaver.core.product 6.1.0.201906091949)
  Only one of the following can be installed at once: 
    DBeaver SSH tunnels 1.0.17.201811051019 (org.jkiss.dbeaver.net.ssh 1.0.17.201811051019)
    DBeaver SSH tunnels 1.0.28.201904211926 (org.jkiss.dbeaver.net.ssh 1.0.28.201904211926)
    DBeaver SSH tunnels 1.0.15.201810071756 (org.jkiss.dbeaver.net.ssh 1.0.15.201810071756)
    DBeaver SSH tunnels 1.0.24.201902172105 (org.jkiss.dbeaver.net.ssh 1.0.24.201902172105)
    DBeaver SSH tunnels 1.0.31.201906091949 (org.jkiss.dbeaver.net.ssh 1.0.31.201906091949)
    DBeaver SSH tunnels 1.0.23.201902031804 (org.jkiss.dbeaver.net.ssh 1.0.23.201902031804)
    DBeaver SSH tunnels 1.0.19.201812092025 (org.jkiss.dbeaver.net.ssh 1.0.19.201812092025)
  Cannot satisfy dependency:
    From: DBeaver Community Edition 6.1.0.201906091949 (org.jkiss.dbeaver.ce.feature.feature.group 6.1.0.201906091949)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [6.1.0.201906091949,6.1.0.201906091949]
  Cannot satisfy dependency:
    From: DBeaver Core 5.2.2.201810071756 (org.jkiss.dbeaver.core.feature.feature.group 5.2.2.201810071756)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.net.ssh [1.0.15.201810071756,1.0.15.201810071756]
  Cannot satisfy dependency:
    From: DBeaver Core 5.2.4.201811051019 (org.jkiss.dbeaver.core.feature.feature.group 5.2.4.201811051019)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.net.ssh [1.0.17.201811051019,1.0.17.201811051019]
  Cannot satisfy dependency:
    From: DBeaver Core 5.3.0.201812092025 (org.jkiss.dbeaver.core.feature.feature.group 5.3.0.201812092025)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.net.ssh [1.0.19.201812092025,1.0.19.201812092025]
  Cannot satisfy dependency:
    From: DBeaver Core 5.3.4.201902031804 (org.jkiss.dbeaver.core.feature.feature.group 5.3.4.201902031804)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.net.ssh [1.0.23.201902031804,1.0.23.201902031804]
  Cannot satisfy dependency:
    From: DBeaver Core 5.3.5.201902172105 (org.jkiss.dbeaver.core.feature.feature.group 5.3.5.201902172105)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.net.ssh [1.0.24.201902172105,1.0.24.201902172105]
  Cannot satisfy dependency:
    From: DBeaver Core 6.0.3.201904211926 (org.jkiss.dbeaver.core.feature.feature.group 6.0.3.201904211926)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.net.ssh [1.0.28.201904211926,1.0.28.201904211926]
  Cannot satisfy dependency:
    From: DBeaver 6.1.0.201906091949 (org.jkiss.dbeaver.core.product 6.1.0.201906091949)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [6.1.0.201906091949,6.1.0.201906091949]
  Cannot satisfy dependency:
    From: DBeaver SSHJ 1.0.23.201902031804 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.23.201902031804)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.core.feature.feature.group 0.0.0
  Cannot satisfy dependency:
    From: DBeaver Runtime 6.1.0.201906091949 (org.jkiss.dbeaver.runtime.feature.feature.group 6.1.0.201906091949)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.net.ssh [1.0.31.201906091949,1.0.31.201906091949]
  Cannot satisfy dependency:
    From: DBeaver Standalone 6.1.0.201906091949 (org.jkiss.dbeaver.standalone.feature.feature.group 6.1.0.201906091949)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.runtime.feature.feature.group [6.1.0.201906091949,6.1.0.201906091949]
```

**Comment by Cris70** [comment]
BTW, how do you reopen a bug?

**Comment by serge-rider** [comment]
@Cris70 you have too many too old versions installed. Eventually this ended up in dependencies conflicts (version 6.0 contains completely different set of features).

What you can do: uninstall previous DBeaver version (from Help->About Eclipse IDE->Installation Details->Installed Software, find DBeaver and uninstall it).

If this won't help then only install into the clean Eclipse IDE will help.

**Comment by Cris70** [comment]
@serge-rider thank you for your help. I will do as you suggest.
HOWEVER: how can it be that I have all those old versions still installed? I always download the most recent rpm package and install it. RPM always tells me that it is going to **update** the installed package.
RPM is a package manager, one of the most widely used, so I trust what it is saying.
So my question is: are you sure that the package you build is correct? Does it correctly supersedes old releases? 
I am no RPM expert but DBeaver is the only package that is giving me those kind of problems. Is it because it is java-based?

Thank you in advance
Cris

**Comment by p91paul** [comment]
it's more likely that your issue is caused by something in your .eclipse or .dbeaver folder in your home directory, which get created when dbeaver runs, so are not touched by the rpm package

**Comment by serge-rider** [comment]
@Cris70 Well, possibly it is caused by rpm packager misconfiguration (we are using redline-rpm packager). It has to remove previous version completely before installing new version.
As a workaround you could try to delete `/usr/share/dbeaver` folder before version update. Perhaps we'll need to fix rpm packaging.

If you can validate that old /usr/share/dbeaver contents isn't removed on update then please create new bug report ticket (specific to rpm installer).

Thanks for checking this.

**Comment by Cris70** [comment]
> @Cris70 you have too many too old versions installed. Eventually this ended up in dependencies conflicts (version 6.0 contains completely different set of features).
> 
> What you can do: uninstall previous DBeaver version (from Help->About Eclipse IDE->Installation Details->Installed Software, find DBeaver and uninstall it).
> 
> If this won't help then only install into the clean Eclipse IDE will help.

@serge-rider it does not seem that I have older versions installed:
![image](https://user-images.githubusercontent.com/5107224/59588725-951c8f00-90e8-11e9-9d81-5d2dfe401dc5.png)

**Comment by Cris70** [comment]
...but I do have a lot of files from previous versions, apparently, in ~/.eclipse, as @p91paul suspected:
![image](https://user-images.githubusercontent.com/5107224/59588992-360b4a00-90e9-11e9-9117-17e1de0c4a19.png)

What should I do? 
Shouldn't this be taken care by the installation package? Or am I supposed to manually clean the older versions files upon every update?

**Comment by Cris70** [comment]
After removing all the files and directories from old releases in the ~/.eclipse directory, the installation of the updated plugins took less than one minute.
However, DBeaver did not ask me to update the plugins, as if it had lost track of which plugins I had previously installed. I had to manually search for the plugins and install them.

**Comment by Cris70** [comment]
Installed v6.1.4 today.
In ~/.eclipse I had only two directories:
- org.eclipse.equinox.security
- org.jkiss.dbeaver.product_6.1.2_620785679_linux_gtk_x86_64

After starting DBeaver 6.1.4 for the first time, I had a dialog windows asking me to migrate the workspace, which I confirmed. It completed in a few seconds.
Then the usual dialog box asking me to upgrade the existing extensions.
It started "Calculating requirements and dependencies" at 9:47AM.
It finished this first phase at about 10:30AM, when I could click on the "Finish" button and it started actually "Installing software".
This second phase finished at 11:01AM, when I got a warning dialog windows asking to confirm the installation of unsigned content, which I did.
It finished almost immediately asking to restart DBeaver.
In total, I had to wait 1 hour and 13 minutes to complete the extension reinstall.

**Comment by uslss** [comment]
Hi @Cris70 ,
unfortunately cannot reproduce issue on 6.2.1.
Is it still reproducible for you?

**Comment by Cris70** [comment]
Hi @uslss ,
yesterday I upgraded from 6.2.1 to 6.2.2.
I started the upgrade at 11:40 AM, with the "Calculating requirements and dependencies" phase, which ended at 12:48 PM. Next phase ("Installing software...") ended at about 1:50 PM. Notice that at 1:45 PM it was still at 7%, then in a few minutes it completed the rest of the work.
So yes, it is unfortunately still very reproducible for me.

**Comment by Cris70** [comment]
Yesterday I updated from 6.2.2 to 6.2.3. It took a few seconds.
If next update is this fast, I'd say this bug can be closed (for me at least).

**Comment by serge-rider** [comment]
I know that there were a few improvements in P2 extensions installation (in Eclipse platform). And there will be a few more in near releases. Hopefull this problem will be resolved after migration to Eclipse 2019-09 (we can't migrate to it now as it has critical bugs in Windows SWT) or 2019-12.

**Comment by kseniiaguzeeva** [comment]
Please reopen if the problem is actual for you again.

**Comment by Cris70** [comment]
Just upgrade from 6.3.4 to 6.3.5. Everything was fine and quick. Let's hope this is fixed for good.
