### ISSUE TITLE
Multiple insert in multi-selection mode

### ISSUE THREAD

**Issue by shtoormanSam** [dbeaver/dbeaver#35462]
### Description

When use Ctrl+Shift+L (add all matches to multi-selection) and insert Ctrl+V copied value - editor inserts many copies in each position.

### DBeaver Version

Community 24.2.0

### Operating System

Win10

### Database and driver

PostgreSQL JDBC Driver

### Steps to reproduce

1. Copy any item (Ctrl+C)
2. use multi-selection (Ctrl+Shift+L)
3. Insert Ctrl+V

https://github.com/user-attachments/assets/18c47952-ba3b-4ab6-841d-6d5d357798fd

### Additional context

Workbench DevStyle DarkestDark Theme - DarkGrey
Editor theme - Wombat

**Comment by E1izabeth** [comment]
Thank you for bug report. It's a duplicate of #21230
