### ISSUE TITLE
Corretly executed code is displayed with an error (exclamation left of the query) and highlighted with red color

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35469]
### Description

https://github.com/user-attachments/assets/903f88bb-7677-42f9-8de9-9c2cee1643d8

- use code:
```
drop table if exists hello;
```

Please also check all other Postgres statements with `if exists`-clause.

### DBeaver Version

Community Edition 24.1.5-202408122322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by E1izabeth** [comment]
Thank you for request.
Seems you have already dropped this table. So, it doesn't exists and the message says about it.
Maybe we can show warning here, not an error.

**Comment by ask9** [comment]
Please consider the possible solution: never show the error `<object> not found` for `drop ... if exists `-statements.
