### ISSUE TITLE
SQL Editor Formatting setting (Use bold font for keywords) also affects single quoted string text

### ISSUE THREAD

**Issue by ChetWang** [dbeaver/dbeaver#35478]
### Description

The default sql formatter setting in sql editor is checked 'Use bold font for keywords', it's OK and the sql keywords are bold fonts, but strings (single quoted) are applied bold font too.
![image](https://github.com/user-attachments/assets/bd29a825-714b-4d1c-bea6-5fdeb16b9b90)

### DBeaver Version

Community edition 24.2.0.202409011551

### Operating System

Windows 11

**Comment by E1izabeth** [comment]
Thank you for report.
