### ISSUE TITLE
sqlite json format truncated

### ISSUE THREAD

**Issue by pillarcoin** [dbeaver/dbeaver#35472]
### Description

<img width="730" alt="SCR-20240905-cshp" src="https://github.com/user-attachments/assets/d15e9fdc-3e21-4139-ae2c-020f9c9a084c">
<img width="1109" alt="SCR-20240905-crln" src="https://github.com/user-attachments/assets/15952a55-bac6-4071-b479-a5e0599b25ee">
<img width="989" alt="SCR-20240905-crvg" src="https://github.com/user-attachments/assets/8c7ee065-6eac-4694-b6ee-4cd42af687ef">

### DBeaver Version

DBeaver Ultimate 24.1.0

### Operating System

macOS Sonoma 14.5

### Database and driver

Database : sqlite
Driver : default

**Comment by HocKu7** [comment]
Hi @liangyi9812 . Thank you for your report. Could you please provide a DDL of the table?

**Comment by pillarcoin** [comment]
Hi @HocKu7.

After I updated my DBeaver Ultimate from 24.1.0 to **24.2.0**, this bug seems to no longer exist.

Here is the SQL.
```sql
-- camdict definition

CREATE TABLE `camdict` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `oid` VARCHAR(255), `word` VARCHAR(255), `pos_items` JSON, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL);

INSERT INTO camdict (oid,word,pos_items,created_at,updated_at) VALUES
	 ('60c0be95a54d7519e524eeb4','overdrawing','[{"type":"verb","pronunciations":[{"region":"uk","audio":"https://dictionary.cambridge.org/media/english/uk_pron/u/uko/ukove/ukoverc011.mp3","pronunciation":"ˌəʊ.vəˈdrɔː"},{"region":"us","audio":"https://dictionary.cambridge.org/media/english/us_pron/u/uso/usove/usoverd003.mp3","pronunciation":"ˌoʊ.vɚˈdrɑː"}],"definitions":[{"definition":"to take more money out of your bank account than the account contains","examples":["I overdrew my account by £20.","If students do overdraw, penalties are less severe than those on standard accounts."]}]}]','2024-03-23 01:03:57.786 +00:00','2024-03-23 01:03:57.786 +00:00');

```

<img width="1538" alt="SCR-20240911-tiwl" src="https://github.com/user-attachments/assets/f671cf1b-d5ed-4ba6-8a36-20567e5426dd">
<img width="1533" alt="SCR-20240911-tipr-2" src="https://github.com/user-attachments/assets/5a2545ee-7f7f-4809-8d7e-2697c75af0fc">
<img width="621" alt="SCR-20240911-tiew" src="https://github.com/user-attachments/assets/eec46b63-4007-4890-8806-029c40cacd3b">
