### ISSUE TITLE
Driver manager cannot set up MS SQL Server driver

### ISSUE THREAD

**Issue by palmaresk8** [dbeaver/dbeaver#3547]
I have failed to setup a MS SQL Server connection. Reason: DBeaver (version 5.0.5) didn't found the driver files.

> Drive file download failed.
> Do you want to retry?
> Reason:
> Can't open 'https://dbeaver.jkiss.org/files/jdbc/drivers/mssql/auth/x64/sqljdbc_auth.dll': Moved Permanently

**Comment by serge-rider** [comment]
It was Apache configuration issue on dbeaver.io.
Could you check it one more time?

**Comment by nmat** [comment]
Tested it here and downloaded for me at least:

![image](https://user-images.githubusercontent.com/383031/40879960-3acf7de2-66a9-11e8-9fe1-31492a8cc6f7.png)

**Comment by serge-rider** [comment]
Good (x86 wasn't downloaded because you are on 64 bit system)
