### ISSUE TITLE
ORA-17008: Closed connection

### ISSUE THREAD

**Issue by mdwajahat** [dbeaver/dbeaver#35481]
### Description

Dear Team,

Can you please help me getting connected to database that runs on Oracle 12c

I am facing the below error from the DBeaver Community Edition

ORA-17008: Closed connection

Thanks

### DBeaver Version

Community Edition Version 24.2.0.202409011551

### Operating System

Windows 10

### Database and driver

Oracle database connectivity

### Steps to reproduce

I tried to connect to database that runs on oracle by providing all details like port, hostname, username, pass 

And also tried entering by making the TNS entry as well, but still ended up with below error

ORA-17008: Closed connection

### Additional context

Kindly help to fix this connectivity issue

**Comment by MashaKorax** [comment]
We kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\\.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by E1izabeth** [comment]
Seems this issue is stale. If the issue is still actual please let me know and provide requested log files.
