### ISSUE TITLE
User management/create on Galera Cluster

### ISSUE THREAD

**Issue by garyx** [dbeaver/dbeaver#3549]
I have been scouring the documentation but I cannot see any info on user management/creation on a galera cluster. I used DBeaver to connect to the cluster and tried updating/creating users and it seems the client is not aware that of it is talking to a cluster and updates users password incorrectly with an insert and that is not replicated through the cluster. 

Some explanation can be found here. 
http://galeracluster.com/documentation-webpages/userchanges.html

Am I doing something wrong, I cannot find any setting to tell the client that it is talking to a cluster anywhere. Using msyql workbench does this correctly but DBeaver always desyncs my users password.

I didn't find any info when searching info or the old forums on this issue.

**Comment by serge-rider** [comment]
Sorry, missed this FR.
Yes, we have to change this. Using direct INSERT was the only way to create users in MySQL 4 and earlier, nowadays it doesn't make sense. However we'll keep old way too (for backward compatibility).
