### ISSUE TITLE
Data export does not work correctly

### ISSUE THREAD

**Issue by BorisPBA** [dbeaver/dbeaver#35519]
### Description

Data export does not work correctly in dbweaver 24.2.0 for MySQL 8.0.30 and 8.0.35
I want to dump the database, but it comes out truncated.

### DBeaver Version

24.2.0

### Operating System

Windows 10 64bit

### Database and driver

MySQL 8.0.30 and 8.0.35
Driver for MySQL 8 and later

### Steps to reproduce

database -> tools -> database dump -> select database -> select all tables -> by default -> next -> start
We get an incorrect database dump.

**Comment by ask9** [comment]
Try the latest Early Access build:
https://dbeaver.io/files/ea/

**Comment by BorisPBA** [comment]
Please add line breaks for table entries in the database dump. Just another checkbox.
It's very inconvenient when the line is very long.

**Comment by BorisPBA** [comment]
Dbeaver 24.2.1 works good.
Thank you!

**Comment by roubilibo** [comment]
i got this same problem to.
thx

**Comment by E1izabeth** [comment]
Thank you for bug report.
I'm closing it as a duplicate of #35421 #35426
The fix will be available in the next release

**Comment by hairullana** [comment]
> Thank you for bug report. I'm closing it as a duplicate of #35421 #35426 The fix will be available in the next release

when you'll release fix version?

**Comment by ask9** [comment]
@hairullana It was already fixed two weeks ago, wasn't it?
Look at my first message.

**Comment by hairullana** [comment]
> @hairullana It was already fixed two weeks ago, wasn't it? Look at my first message.

owh sorry, I missed it
thanks a lot
