### ISSUE TITLE
New Autocomplete doesn't suggest system schema names (for example, pg_catalog)

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35515]
### Description

When you press Ctrl + Space, it doesn't suggest to complete "pg_catalog".
May be related to this one: #35338

*Please also check other system schema names in Postgresql.
*Please also check other system schema names in other sql-engines.

![image](https://github.com/user-attachments/assets/236edf04-81db-4078-bca5-739b413fc253)

### DBeaver Version

Community Edition 24.1.5-202408122322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by E1izabeth** [comment]
Thank you for your report.
Related to #34807

**Comment by E1izabeth** [comment]
Works for new autocompletion engine

**Comment by ask9** [comment]
Thanks. I confirm it works now.
