### ISSUE TITLE
Import data does not work with Snowflake when using Single Sign On (SSO)

### ISSUE THREAD

**Issue by PeterF-21** [dbeaver/dbeaver#35514]
### Description

Note - this occurs where connection to Snowflake is only possible using SSO, we are using Azure AD and the Cisco Duo app. When trying to import a CSV (or any other) file using the Import Data option, the "SAML Response for Snowflake" appears in the browser window as normal, but no matter how quickly this is responded to in the the Duo app there is always an immediate error "SQL Error [2003][02000]: SQL compilation error: Database 'DBNAME' does not exist or not authorised.  If the target table does not exist then it is created (but it is empty).  If the table already exists the same error occurs.  DBeaver does not seem to wait for the SAML authentication to complete before trying to select the Snowflake database for the import itself, hence it fails.

### DBeaver Version

23.2.3

### Operating System

Windows 10 Pro

### Database and driver

Snowflake JDBC driver installed as per: https://docs.snowflake.com/developer-guide/jdbc/jdbc-configure 

### Steps to reproduce

1. Set up SSO for Snowflake, we use Azure Active Directory and the Cisco Duo Security application (https://duo.com/)
2. Check that you can log in to Snowflake this way via Snowsight
3. Open DBeaver and set up the JDBC driver for Snowflake
5. Check you can use Snowflake interactively from DBeaver, and that SSO is working correctly with the Duo app
6. Now try to upload data from a CSV file...

**Comment by E1izabeth** [comment]
Please try unchecking this setting in the `Data load settings` page of the Data Transfer wizard
![image](https://github.com/user-attachments/assets/1cf7fbda-6e6b-44d8-9665-7bf86d4a286d)

**Comment by E1izabeth** [comment]
Seems this issue is stale. If it's still actual, please let me know and try changing the proposed setting.
