### ISSUE TITLE
Unable to open dbeaver after installing on App Center

### ISSUE THREAD

**Issue by GlowCheese** [dbeaver/dbeaver#35510]
### Description

I'm trying to install DBeaver via App Center but when I open it, nothing happens.
![image](https://github.com/user-attachments/assets/f33427af-90cc-434a-a2ca-1cb766d1c871)

I also tried installing it using different methods, but none of them works for me:
- `snap install dbeaver`: also doesn't show up any popup when I open it.
- `add-apt-repository ppa:serge-rider/dbeaver-ce`: when I run `apt install dbeaver-ce` it shows `Unable to locate package dbeaver-ce`.

### DBeaver Version

Community Edition 24.2.0

### Operating System

Ubuntu 24.04.1 LTS

**Comment by GlowCheese** [comment]
As an additional information, here is the output of my `neofetch`:
```
OS: Ubuntu 24.04.1 LTS aarch64
Host: Raspberry Pi 5 Model B Rev 1.0
Kernel: 6.8.0-1010-raspi
Uptime: 2 hours, 29 mins
Packages: 1920 (dpkg), 12 (snap)
Shell: bash 5.2.21
Terminal: /dev/pts/0
```

**Comment by E1izabeth** [comment]
Hi, @GlowCheese 
Do you have java installed?

**Comment by E1izabeth** [comment]
If no, please try installing it
`sudo apt install openjdk-17-jre`

**Comment by GlowCheese** [comment]
> Hi, @GlowCheese Do you have java installed?

I've checked if I have Java installed. The answer is I do. However it is Java 21 instead of 17 (as you specified in the latest reply).

```
$ java --version
openjdk 21.0.4 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu224.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu224.04, mixed mode, sharing)
```

**Comment by ivgag** [comment]
@GlowCheese
Could you run DBeaver from the terminal using the command `dbeaver-ce`? If that doesn’t work, try running it with `/snap/bin/dbeaver-ce`.
Also, could you provide the output of the `uname -m` command in the terminal?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
