### ISSUE TITLE
Dameng support bug

### ISSUE THREAD

**Issue by ftr5672227** [dbeaver/dbeaver#35523]
### Description

a table with id column, but no auto-increment, there is some data in it. So when try to add auto-increment to this id column, it failed.

### DBeaver Version

Community 24.2.0

### Operating System

windows11

### Database and driver

Dameng

### Steps to reproduce

double-click on this id column, and click auto-increment, then save.

**Comment by humphreygao** [comment]
https://github.com/dbeaver/dbeaver/issues/23071#issuecomment-1982561114

which version do you use？ It may only support dameng 8 auto_increment keyword.

**Comment by ftr5672227** [comment]
DM Database Server 64 V8
DB Version: 0x7000c
03134284172-20240321-222308-20093
Msg Version: 0
Gsu level(3-4) cnt: 3
Gsu level(5) cnt: 0

it is dameng 8.

**Comment by MashaKorax** [comment]
Hello @ftr5672227 Could you please provide log files and screencast with your issue?

**Comment by E1izabeth** [comment]
We were unable to reproduce the issue. If it's still actual, please provide the log files and the video showing it.
Before collecting log files, please reproduce the issue once again. The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\\.metadata directory.
