### ISSUE TITLE
Some cross-reference links in documentation (pdf and online help) are not clickable

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35527]
### Description

Full list with screenshots and page numbers is here:
[screenshots.zip](https://github.com/user-attachments/files/16944302/screenshots.zip)

Additionally:
* Search all occurences of the keyword: "Security Settings Guide". They also have no links.
* Search all occurences of the keyword: "Redis Sentinel" (add it if is ready)
* Please also try to find other missing links as my list is incomplete.

### DBeaver Version

Community Edition 24.2.1-202409092322

### Steps to reproduce

- open pdf-documentation (ver 24.3 EA)
- go to chapter "Disabling AI features"
- try to click the text "our article" highlighted with blue color

![изображение](https://github.com/user-attachments/assets/a8c23b8f-326b-45e8-ab4e-4e0e28e2603f)

**Comment by arhayka** [comment]
Thank you for the report!

**Comment by daelynum** [comment]
Thank you for the report, the links have been corrected.
