### ISSUE TITLE
Dont remember column type on create

### ISSUE THREAD

**Issue by studiointer** [dbeaver/dbeaver#3553]
Hello.
I'm use DBeaver 5.0.6 for MacOS. Work with PostgresSQL.
I create new column by clicking on Columns in table interface list:
[Screenshot](http://eval.su/dbeaver/creating.png)

Then window appears. I choose type (eg. bool). Click Ok.
[Screenshot](http://eval.su/dbeaver/window.png)

Columns created with type **varchar**.
[Screenshot](http://eval.su/dbeaver/list.png)
And I can really change it on tab double clicking on column name.

**Comment by serge-rider** [comment]
This is MacOS specific (and also an issue in SWT framework). I will try to make some general fix for all similar issues.

Workaround: press <kbd>Enter</kbd> or click somewhere outside of edit field. This will apply edited value and then you can click on "Ok".

**Comment by studiointer** [comment]
After hit enter all works fine!
Thank you!
