### ISSUE TITLE
Additional option to the epoch timestamp variants (Apple Cocoa / Mac absolute time)

### ISSUE THREAD

**Issue by jsimon1080** [dbeaver/dbeaver#35538]
When configuring a "date transformation" for a column, the user can select "Epoch Time" and choose different value types. The following text is shown in the explanation paragraph at the top :

"Represents numerical value as timestamp in Epoch (C, Unix, POSIX, Java, etc) time or one of its Windows-friendly variants - the number of seconds that have elapsed since 1970/01/01 00:00:00 (UTC), or a reference point specific to the chosen variant."

It would be nice to add Apple (Cocoa / Mac absolute time) timestamps in the choices of value types to make it easier to work with SQLite databases from Mac or iOS.

According to the Epoch Converter web site...

"A Core Data timestamp is the number of seconds (or nanoseconds) since midnight, January 1, 2001, GMT (see [CFAbsoluteTime](https://developer.apple.com/documentation/corefoundation/cfabsolutetime)).
The difference between a Core Data timestamp and a Unix timestamp (seconds since 1/1/1970) is 978307200 seconds."

An even nicer solution would be to allow the users to configure their own variants.

Thanks.

**Comment by ivgag** [comment]
> a "date transformation" for a column

Hi! What is it? It's not clear :(

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and answer the question
