### ISSUE TITLE
Add an "order by NULLS LAST" in the data editor window

### ISSUE THREAD

**Issue by hackenspp** [dbeaver/dbeaver#35532]
In the data editor window, you can order by any column ascending or descending. When you choose descending order, the null values appear on top which as it is generally the case in SQL, but sometimes you want them to appear last.

**Comment by ivgag** [comment]
If you want to shadow all rows that contain `null` values, you can use a filter (see the picture).
![Image](https://github.com/user-attachments/assets/313eeb11-f5ec-4835-950c-4ed037337636)
