### ISSUE TITLE
Optimize layout of UI elements in the "Key"-tab in "Preferences"-window

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35548]
I suggest to make it more compact moving group of tabs a little higher.

https://github.com/user-attachments/assets/04ac0f9e-a2b2-4517-a3ea-11388588a489

**Comment by E1izabeth** [comment]
DBeaver inherit this preferences page from Eclipse. So, we can do nothing about the layout on this page.
![image](https://github.com/user-attachments/assets/1860b919-d8d6-4824-a3d6-d11fc397a279)
