### ISSUE TITLE
Database Native > Incorrect password entry > returns Connection Error > GSS-API Authentication Exception error > Unable to obtain Principal Name for Authentication

### ISSUE THREAD

**Issue by bviase** [dbeaver/dbeaver#35557]
### Description

When users enters incorrect password on Database Native authentication, seems the driver is failing and reporting a "Connection Error" with "GSS-API Authentication Error" indicating "Unable to obtain Principal Name for Authentication"

This probably shouldn't be going to Kerberos on a Windows install.

Seen this for a few terms now, it should just say "Incorrect Password"

Windows 10 & 11
MariaDB 11.5.2 & 11.4.0.0
DBeaver EE 24.1.0.202406100905
Connection error
Unable to obtain Prinipal Name for authentication
GSS-API authentication exception
Unable to obtain Principal Name for authentication

### DBeaver Version

Enterprise Edition 24.1.0.202406100905

### Operating System

Windows 10 and 11

### Database and driver

MariaDB 11.5.2 and 11.4.0.0

Driver Settings 
> Settings:
Driver Type indicates: MySQL (PRO)
Class Name: org.mariadb.jdbc.Driver
ID: mariaDB
Description: MariaDB JDBC driver
> Libraries:
MariaDB
drivers/mariadb/LICENSE.txt - C:\Users\bradv\AppData\Local\DBeaverEE\drivers\mariadb\LICENSE.txt
drivers/mariadb - C:\Users\bradv\AppData\Local\DBeaverEE\drivers\mariadb
>Local Client
ID/Path/Name: both 11.4 and 11.5 pointing to C:\Program Files\MariaDB 11.5 ...doesn't seem right.
Product Name: MySQL/MariaDB
> Driver License 
MariaDB JDBC driver is distributed under the GNU Lesser General Public License (LGPL). Text of the license can be obtained from http://www.gnu.org/copyleft/lesser.html.

### Steps to reproduce

If password is incorrect on Test Connection:

![image](https://github.com/user-attachments/assets/a6e2330d-84ee-4675-a0f4-05b1a8bd5a69)

The following error message gets produced:

![image](https://github.com/user-attachments/assets/a08ef77b-3960-493f-a9d9-7a25887541e1)

...and it should just indicate: Password is Incorrect or Incorrect Password.

### Additional context

Just a local install of MariaDB, on Windows, connecting to localhost, no tunnels.  Using 3307 for 11.4, and 3306 for 11.5, the issue predates those port configs.  No SSH or SSL.  If password is correct, the Test Connection yields:

![image](https://github.com/user-attachments/assets/b04a8eeb-90b7-410e-b754-a536152489be)

...so the driver might have some issue, as it should definitely not be reporting such a confusing error message like this.

**Comment by E1izabeth** [comment]
DBeaver gets this error message directly from the driver. We can't handle it and show another message because it might be confusing in other situations when this message is sent, but the password is correct. At the same time, DBeaver doesn't know if your password is correct.
I agree with you, that this error is confusing. And unfortunately, we can do nothing here.
