### ISSUE TITLE
Several issues on 24.2.0 (fine on 24.1.0) on Redshift

### ISSUE THREAD

**Issue by alejandrofm** [dbeaver/dbeaver#35553]
### Description

Hi! I will try to enumerate some things that are happening randomly and were fixed on previous version, want to know if I'm the only one here or if someone can reproduce without my randomness.
- Views are not loading DDL
- Sometimes Tables don get Metadata (like columns)
This solves itself by restarting DBeaver, is like when I had to rollback the driver, but I'm running on the recommended one now

### DBeaver Version

Community 24.2.0

### Operating System

macOS 14

### Database and driver

 Redshift 2.1.0.9

**Comment by E1izabeth** [comment]
Hi, @alejandrofm. For now, we can't reproduce the issue.
We kindly ask you to reproduce the issue again and send us the log files. You can collect them to archive automatically with `Help->Collect Diagnostic Info`
![image](https://github.com/user-attachments/assets/51c7ca2e-6be2-489e-b495-028b9aa0e386)

**Comment by alejandrofm** [comment]
Hi! it's working again on 24.2.1, closing this. Thank you
