### ISSUE TITLE
SQLServer DDL generated with wrong size for datetime2 column

### ISSUE THREAD

**Issue by aldebaranbm** [dbeaver/dbeaver#3555]
**_SQLServer DDL generated with wrong size for datetime2 column_**
> Client: DBeaver 5.1.0 CE (Linux Debian 64 bit)
> Server: Microsoft SQL Server 2008

## Try:

```
CREATE TABLE test_table (
	test_column0 datetime2(0),
	test_column1 datetime2(1)
)
```

## Posteriorly wrong DDL is generated

**With jTDS driver:**
```
-- Drop table

-- DROP TABLE database_test.dbo.test_table

CREATE TABLE database_test.dbo.test_table (
	test_column0 datetime2(19)
	test_column1 datetime2(21)
) go
```

**With Microsoft Driver**
```
-- Drop table

-- DROP TABLE database_test.dbo.test_table

CREATE TABLE database_test.dbo.test_table (
	test_column0 datetime2,
	test_column1 datetime2
) go
```

**Important note:**
With jTDS driver, in "Columns" the ico is "ABC" (text column). Datetime2 columns not return scale, only length;
With Microsoft Driver, the ico, in "Columns", is correctly (clock) and returned scale and length;**

**Potential solution:**
_Maybe solution is use "scale" to generate DDL to columns datetime2. This solution make valid DDL to both drivers and with Microsoft Driver make valid and correct SQL Create_

**Comment by serge-rider** [comment]
Good point.
Although I can't fix jTDS driver (it doesn't return scale for datetime  columns). 
At least it will be fixed for Microsoft driver + we'll resolve datetime columns as date/time (but without scale).
