### ISSUE TITLE
Office 365 Excel reports sheet from 'Open results in Excel' as broken

### ISSUE THREAD

**Issue by GiantCrocodile** [dbeaver/dbeaver#3556]
I'm using DBeaver Enterprise v5.0.1 and when I open a table with zero rows and use the 'Open results in Excel' context menu option, I get an warning popup from latest Office 365 Excel: Some parts of the file are damaged and Excel can try to recover as much as possible from the damaged file. Do I trust this file so the recover can start? [Yes/No].

If I click yes, Excel reports that restoring the file failed and thus it can't be opened. This occurs only with exports from empty tables, so low priority.

**Comment by serge-rider** [comment]
That's easy to fix. Thanks for report.
