### ISSUE TITLE
Error exporting MySQL database

### ISSUE THREAD

**Issue by cayi** [dbeaver/dbeaver#35561]
### Description

At the dump progress, shows information about the tables been exported (community Edition version 24.2) and when i tried to import, shows several errors. Works fine in version 24.1.5

### DBeaver Version

Community Edition version 24.2

### Operating System

Windows 11

### Database and driver

MySQL dump

### Steps to reproduce

Righclick con Database, Tools, Dump Database (MariaDB / MySQL) MariaDB JDBC driver

**Comment by ask9** [comment]
It has already been fixed in the latest Early Access build:
https://dbeaver.io/files/ea/

**Comment by cayi** [comment]
Fixed 24.2.1 Thanks!

**Comment by LonwoLonwo** [comment]
> Fixed 24.2.1 Thanks!

Thanks for checking
