### ISSUE TITLE
Why am I always getting this error?

### ISSUE THREAD

**Issue by dBeaverZach** [dbeaver/dbeaver#35563]
### Description

Getting this error periodically. If I have a window open it will close it.

<img width="454" alt="image" src="https://github.com/user-attachments/assets/32eb52ab-0031-4ad5-a25f-3b89620af793">

"An internal error occurred during: "Periodic workspace save.".
Cannot parse null string"

### DBeaver Version

UE Version 24.2.0.202409091031

### Operating System

Sonoma 14.5

### Database and driver

Currently using an oracle db on AWS RDS

**Comment by ShadelessFox** [comment]
Hello @dBeaverZach,

It's hard to tell what went wrong without any additional information.

Please provide log files. You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files. Thank you

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
