### ISSUE TITLE
Oracle - table completion does not work

### ISSUE THREAD

**Issue by MatteoR23** [dbeaver/dbeaver#35566]
### Description

Table completion does not work when you have joins on the same table.

### DBeaver Version

CE 24.2

### Operating System

Windows 11

### Database and driver

Oracle 19c

### Steps to reproduce

Example:

``` sql
SELECT  T.A, T1.B, T3.C
FROM T
INNER JOIN T1 ON T1.KEY = T.T1_KEY
INNER JOIN T1 T3 ON T3.KEY = T.T3_KEY
```

If I type "T1." or "T3." it won't complete, while if I type "T." the completion works as expected.

**Comment by uslss** [comment]
Cannot reproduce in 24.2.2
