### ISSUE TITLE
Select and Execute Specific Chunks of SQL Queries Within Stored Procedures

### ISSUE THREAD

**Issue by mskperera** [dbeaver/dbeaver#35579]
It would be great to have a feature for executing specific chunks of SQL queries within stored procedures. This would make debugging and testing more convenient by allowing selective execution of query blocks rather than running the entire procedure.

**Comment by ged-yuko** [comment]
Doesn't it already work exactly like your title says: select a fragment of script editor's text you want to execute as a unit and then use Run query command?

**Comment by E1izabeth** [comment]
@ged-yuko it does. The feature already exist
