### ISSUE TITLE
Issue in the Backup dialog

### ISSUE THREAD

**Issue by aledmb** [dbeaver/dbeaver#3557]
Hello,

Small issue i've noticed with the UI in the Backup dialog.

If you have more than one schema and you click the "All" button, all schemas are selected, but the "Next" button is still disabled. You are required to click one of the schema names to proceed to the next step.

![untitled](https://user-images.githubusercontent.com/5561899/40890804-24493442-6752-11e8-84f7-344beffc3248.png)

**Comment by serge-rider** [comment]
Thanks for report
