### ISSUE TITLE
Mouse click to toggle boolean value in a cell doesn't work if there is no unique key in a table

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35583]
### Description

use code:
```
drop table if exists tab;

CREATE TABLE tab (
    id int4 NULL,
    hello bool NULL
);

insert into tab 
values(1, true), (2, false);


select * from tab;

```

https://github.com/user-attachments/assets/2f32aaec-b522-4b23-8334-ae53be62144e

### DBeaver Version

Community Edition 24.2.1-202409092322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by MashaKorax** [comment]
Hello @ask9, in the first case, your table is in read-only mode; it is expected behavior.

**Comment by ask9** [comment]
Shouldn't the program ask a user this confirmation to allow edit in this mode?
Because if I try to change a value in a column of another data type, it allows me do it.

![изображение](https://github.com/user-attachments/assets/a60bd897-5d8f-4c88-b985-bac43cc97fb5)

The change of the boolean value is also possible if "Set NULL" to the cell first.
After that it becomes clickable.
Here is an example how I managed to change the value and save it correctly without a unique key:

https://github.com/user-attachments/assets/8a6b8c33-1374-403f-a3c2-0cfdeabb81a2
