### ISSUE TITLE
Copy & paste of a row is not possible

### ISSUE THREAD

**Issue by GiantCrocodile** [dbeaver/dbeaver#3559]
I would like to be able to copy a row, change the database structure and then being able to paste the content of the copied row again. Right now, when I paste it, every field's content is pasted behind each for each field.

Row example:
```
1 Test 123
```

will result in

```
1Test123 1Test123 1Test123
```

A very cool thing would be that copy and paste works with recognizing column names by name. Although it should be very unlikely that new columns get inserted between previously existing columns.

EDIT: I think I forgot to use 'extended insert' option. Maybe this one should be the default behaviour on CTRL + V?

**Comment by serge-rider** [comment]
Not sure about default behavior. Sometimes text values contain tabs and this may frustrate people even more. 
After all multi-cell paste is not so frequent operation, advanced paste seems to be right way to do this.
