### ISSUE TITLE
Resultset Fetch Size not working when query huge table in Teradata database

### ISSUE THREAD

**Issue by ahhmedbilal** [dbeaver/dbeaver#35600]
### Description

I have set resutlset fetch size to 10000 in Data Editor setting. Please see the picture....

![image](https://github.com/user-attachments/assets/fe7a7ed3-2754-4ab5-bfd6-dbb0f3d2b2ce)

I dont want to use "Use SQL to limit fetch size" as it does not work with "select distinct" clause. 

My tables has 3.2 million rows. DB is hosted in cloud. 

dbeaver fetches 10,000 rows in under 1 second and then the progress bar on bottom right should stop, but it keeps on moving untill all the data is fetched. 

see this picture: 
![image](https://github.com/user-attachments/assets/6996c34d-d398-4759-93c6-d09574c6ee65)
in above pic, 10,000 rows are fetched. but progress bar keep on moving. 

I took this second picture wihin 10 or 15 seconds. bar is still moving. 

![image](https://github.com/user-attachments/assets/e4e7a28e-347d-416c-b305-23ef910b809a)

in this last pic, you can see how much time it took to fetch first 10,000 rows, 

![image](https://github.com/user-attachments/assets/a9be3186-88ef-4d7a-9fbe-4c4da3d2d32f)

but the whole query get executed in 37,000 ms. see picture for execution log. 

![image](https://github.com/user-attachments/assets/7e92fe32-2639-454b-a91c-1f6f5cddfb5b)

This happens when we query the table using select statement. But if we open the table using right click in the navigator then it fetches only 10,000 and stops. 

Can you please fix this? 

### DBeaver Version

Enterprise 24.2.0

### Operating System

Windows 10

### Database and driver

1. Teradata
2. Teradata JDBC Driver 20.00.00.34

### Steps to reproduce

As mentioned in the description.

**Comment by arhayka** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
Teradata driver has a quite specific behavior when handling max rows.
Will be fixed in 24.2.5.
