### ISSUE TITLE
Driver download: proxy credentials configured but "Password Required" windows pops up many times

### ISSUE THREAD

**Issue by keen85** [dbeaver/dbeaver#35604]
### Description

Hi,
We have a **proxy with authentication** in place. I configured it here:
`Preferences » Connections » Driver`
![image](https://github.com/user-attachments/assets/f7a839e4-2f5d-440f-b08f-da736a4df0d6)

When trying to download a driver using the Driver Manager, the "Password Required" windows pop up _a lot of times_:
![image](https://github.com/user-attachments/assets/48767a71-9ce2-4e70-bc17-e926fbd5b859)
- after going to `Driver Manager » DuckDB » Libraries` and hitting `Download/Update` the credential window opens **two** times (sequentially); I retype the same user and password as under `Preferences » Connections » Driver`. Then the required drivers are listed.
- after pressing `Download`, another **two** instances of the credential window open (sequentially). Again, I retype the credentials for every instance. Finally, all files are successfully downloaded.

I have the impression that the first issue is that the credentials form `Preferences » Connections » Driver` are not used. Additionally, after inserting credentials, these are only used for _one request_. For every following request the user is prompted again for credentials. That is why for drivers that require downloading _many_ files (e.g. MSSQL), the user is basically spammed with credential popups.

### DBeaver Version

Community Edition 24.2.0.202409011551

### Operating System

Widows 11

### Steps to reproduce

1.

**Comment by ShadelessFox** [comment]
Hello @keen85,

Sorry for making you wait for so long. Is the issue still reproducible?

Can you reproduce it again and perform a _thread dump_ with that popup open?

You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump. Thank you.

**Comment by ShadelessFox** [comment]
Could it be that you have a leftover network configuration from https://github.com/dbeaver/dbeaver/issues/35581 that is causing the issue?

**Comment by keen85** [comment]
Hi @ShadelessFox,
Thanks for reaching out.
Concerning #35581: I don't think that it is related. To my understanding there are proxy settings for the _driver download_ (`Preferences » Connections » Driver`) that is the topic of this very issue. And #35581 is about the proxy setting for the actual _database connection_ (`Preferences » Connections » Network Connections`).

I reproduced the issue and created a dump having the pop-up open.
[dump_35604_proxy_credentials_popup.zip](https://github.com/user-attachments/files/17331890/dump_35604_proxy_credentials_popup.zip)

**Comment by arhayka** [comment]
Unfortunately, we have not been able to reproduce the reported behavior. Therefore, I am closing this issue. 
We will reopen it if we receive a similar report from another user or are able to reproduce the issue in the future.
