### ISSUE TITLE
Error when building a connection

### ISSUE THREAD

**Issue by addyqin** [dbeaver/dbeaver#35606]
### Description

Hi,
I am encountering a problem when I try to connect to the database of the company. when I click on the connect button, it firstly pops a window saying MySQL driver files are missing, but when I try to "download " the file it gives me another error message as 
```
"Network error: Network unavailable
java.io.IOException:Exception during a connection to https://repo1.maven.org

Reason:
Network unavailable
java.io.IOException:Exception during a connection to https://repo1.maven.org"
```

AND

```
"Can't create driver instance (class 'com.mysql.cj.jdbc.Driver').
  Error creating driver 'MySQL' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.mysql.cj.jdbc.Driver'
    com.mysql.cj.jdbc.Driver
    com.mysql.cj.jdbc.Driver
"
```

I've googled this error and tried all available solutions but none of them helps. Does anyone know what else I can do?

Thanks in advance!

### DBeaver Version

Community Edition 24.2.0

**Comment by E1izabeth** [comment]
Can you open https://repo1.maven.org in the web browser?

**Comment by E1izabeth** [comment]
Please provide info about your operation system

**Comment by E1izabeth** [comment]
Are you in a corporate network or under some firewall?

**Comment by addyqin** [comment]
Hi Elizabeth,
Yes I am able to open https://repo1.maven.org/. I am using windows 10 Enterprise and I am not sure if i am under some firewall. What I am trying to do is to connect to my company's database.

**Comment by addyqin** [comment]
Problem fixed. It should be due to company's block of access at first.
