### ISSUE TITLE
Line break character handling on CSV export

### ISSUE THREAD

**Issue by Noelemahc7** [dbeaver/dbeaver#35614]
This was submitted before but obvious miscommunication between the reporter and the responders led to it being left unresolved. Shame.

https://github.com/dbeaver/dbeaver/issues/8285

When a string value contains a linebreak symbol of any kind, it utterly breaks Excel when you try exporting a CSV and then opening it in Excel.

As is:
Step one. Export CSV. Your settings do not seem to matter.
Step two. Open CSV in Excel.
Step Three. Watch your table get disfigured because the importer cannot handle a linebreak symbol and starts a new line partway through the column list causing columns to be displaced. If you have 54 columns and column 33 has a linebreak in it, column 34 becomes column 1 of a new line which is no good terrible horrible if it occurs more than once per file.
EDIT: It also notably breaks the breaking up of the rest of the original lines into separate columns at least as far as Excel's CSV importer is concerned, which makes it impossible to fix in Excel itself unless you write an excessively meticulous macro.

To be:
Add an option to excise or replace all "unprintable signs" as Microsoft Office understands them (the button that looks like a reverse capital P with an extra line, the carriage return) with a chosen symbol when exporting CSVs, focusing on line breaks you cannot remove with REPLACE in your SQL query.

Not all of us can edit the table data to fix incorrect data entries, and manually fixing all occurences is intractable if your CSV is more than a hundred lines long.

**Comment by E1izabeth** [comment]
Thanks for the request

**Comment by vanHuong0202** [comment]
i m facing the same issue, when exporting table to csv file, if the cell data contains special character like \n, open the file with vs code, it shows new line for the col and code logic can not properly read or convert csv data.

**Comment by vanHuong0202** [comment]
> Thanks for the request

Any update for the issue now? thanks

**Comment by E1izabeth** [comment]
The issue has not yet been resolved. We intend to address it, but I am unable to provide any specific timelines or estimates.

**Comment by kseniaguzeeva** [comment]
Can we add a setting to configure an escape type?

**Comment by serge-rider** [comment]
Regression, reverted, reopened
