### ISSUE TITLE
Snowflake SSO authentication method is case senstiive

### ISSUE THREAD

**Issue by josh-hilbert** [dbeaver/dbeaver#35616]
### Description

The Snowflake connector SSO method uses a string "externalbrowser" and this can cause intermittent connection issues while trying to connect. Manually updating the string to "external**B**rowser" resolves this issue.

Unsure why this works.

### DBeaver Version

Community Edition 24

### Operating System

Windows

### Database and driver

Snowflake DSIIDriver

**Comment by E1izabeth** [comment]
Thank you sharing your case.
By the Snowflake documentation, I see that this parameter should be case-insensitive
https://docs.snowflake.com/en/user-guide/admin-security-fed-auth-use#setting-up-browser-based-sso
https://docs.snowflake.com/en/developer-guide/node-js/nodejs-driver-authenticate#use-single-sign-on-sso-through-a-web-browser

However, I see you're using Snowflake DSIIDriver. Could you tell me why you don't use default JDBC driver for Snowflake that DBeaver propose to download?

**Comment by josh-hilbert** [comment]
@E1izabeth You are correct, I was mistaken and I am using the JDBCdriver with DBeaver. I was looking in the incorrect spot.

I am not experienced in GitHub or repositories, but would this location benefit from updating?

https://github.com/dbeaver/dbeaver/blob/76d9d8e538986abc0b16885dad9f1cbb692c5f74/plugins/org.jkiss.dbeaver.ext.snowflake.ui/src/org/jkiss/dbeaver/ext/snowflake/ui/config/SnowflakeAuthSnowflakeConfigurator.java#L72

**Comment by E1izabeth** [comment]
Yes, it's in the right place in the code. However, I still can't find any docs saying this parameter is case-sensitive. Moreover, I've seen official docs with this parameter in different cases—in one place, it's in lowercase, and another, it's in uppercase.

**Comment by josh-hilbert** [comment]
Thank you for this research! I have not experienced this issue personally, but have been informed from others that sometimes the lower case string works and sometimes it does not.

**Comment by E1izabeth** [comment]
Unfortunately, we have not been able to reproduce the reported behavior. Therefore, I am closing this issue. 
If you reproduce it, please send us log files. You can collect them to archive automatically with `Help->Collect Diagnostic Info`
![image](https://github.com/user-attachments/assets/51c7ca2e-6be2-489e-b495-028b9aa0e386)

We will reopen it if we receive a similar report from another user or can reproduce the issue in the future.
