### ISSUE TITLE
Sharing Scheduled tasks with Colleges

### ISSUE THREAD

**Issue by LeonDenBoer** [dbeaver/dbeaver#35612]
Dear DBeaver Team,

I would like to propose a feature that would greatly enhance the usability of scheduled tasks within DBeaver, especially in collaborative environments.

Feature Request: Shareable Scheduled Tasks

It would be incredibly useful if scheduled tasks could be made shareable among different users within the same organization. Specifically, having the ability to:

- Share scheduled tasks across users so that colleagues can easily access and manage these tasks.
- Store scheduled tasks on the server, enabling seamless access and updates by team members when needed.
- Avoid manual copying of task settings, making it easier for tasks to be taken over when someone leaves or moves to a different role within the company.

This feature would improve efficiency by ensuring that scheduled tasks are easily transferable and maintainable within a team, fostering better collaboration and reducing administrative overhead.

I believe this functionality would be a valuable addition to DBeaver and look forward to hearing your thoughts.

Thank you for considering this request.

Best regards,
Léon den Boer

**Comment by E1izabeth** [comment]
Hi, @LeonDenBoer 
Thank you for your feature request. We have already implemented this feature. It's available in DBeaver Team Edition.
https://dbeaver.com/dbeaver-team-edition/
