### ISSUE TITLE
failed to download snappydata driver

### ISSUE THREAD

**Issue by witwall** [dbeaver/dbeaver#3561]
When I tried download snappydata driver, got the following error, 
···
No enum constant org.jkiss.dbeaver.registry.maven.MavenArtifactDependency.Scope.${HADOOP.DEPS.SCOPE}
···
![image](https://user-images.githubusercontent.com/3222056/40892597-d23887aa-67cb-11e8-8c80-6c01926a5111.png)

Mac OS X
DBeaver 5.0.6

**Comment by serge-rider** [comment]
It is a bug in Maven artifact download process. Thanks for report.

Workaround: manually download snappydata client jar (https://www.snappydata.io/download#) and attach it to driver library list (and delete maven artifact from library list).
