### ISSUE TITLE
Upgrade to dbeaver 24.2.0 causes SSH Connections to disappear

### ISSUE THREAD

**Issue by snapple42** [dbeaver/dbeaver#35619]
### Description

Connections through SSH Tunnel stopped workning
[dbeaver-diagnostic-info-1726518132714.zip](https://github.com/user-attachments/files/17019565/dbeaver-diagnostic-info-1726518132714.zip)

org.jkiss.dbeaver.model.net.ssh.config.SSHAuthConfiguration$Password cannot be found by org.jkiss.dbeaver.net.ssh.ui_1.0.158.202408181605  
  

### DBeaver Version

Community Edition 24.2.0

### Operating System

Ubuntu Budgie 24.04.1

### Database and driver

Maria DB

### Steps to reproduce

1) Upgrade to 24.2.0
2) Edit Connection of a connection with an SSH Tunnel
3) Click on Connection Settings -> SSH

**Comment by snapple42** [comment]
Adding new connection allows edit of SSH properties.

**Comment by E1izabeth** [comment]
What installation method did you use?

**Comment by E1izabeth** [comment]
I see messages like `Can't determine object class 'org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl'` in logs. Probably, something went wrong during update.

**Comment by snapple42** [comment]
Downloaded latest .deb and did dpkg -i

**Comment by E1izabeth** [comment]
For now, we can't reproduce your issue
Have you try uninstalling and installing DBeaver again?

**Comment by snapple42** [comment]
I have one machine that hasn't been upgraded, it's currently 24.03... most of the connections are the same.

If I do that is there something you would want me to capture before upgrading?

**Comment by E1izabeth** [comment]
You can backup the workspace folder just in case we would need to compare some config files. Here is its location https://dbeaver.com/docs/dbeaver/Workspace-Location/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
