### ISSUE TITLE
Hive-Imapla connection with password lenght 24 Characters

### ISSUE THREAD

**Issue by rk-dataengineer** [dbeaver/dbeaver#35611]
### Description

dbeaver imapla/hive jdbc connections not working after changing password length to 24 characters. Same connection working if password lesser than 10 charracter. 

### DBeaver Version

21.0.4

### Operating System

Windows 10

### Database and driver

JDBC Driver for Imapla

**Comment by E1izabeth** [comment]
I doubt it's a bug in DBeaver. DBeaver only pass the password to the database driver.

**Comment by E1izabeth** [comment]
We kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\\.metadata directory. Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

**Comment by rk-dataengineer** [comment]
logs as below:


Exception Stack Trace: com.cloudera.impala.jdbc41.internal.apache.thrift.transport.TransportException at com.cloudera.impala.jdbc41.internal.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132) at com.cloudera.impala.jdbc41.internal.apache.thrift.transport.Transport.readAll(TTransport.java:84) at com.cloudera.impala.jdbc41.internal.apache.thrift.transport.TSas|Transport.receiveSas|Message(TSas|Transport.java:178) at com.cloudera.impala.jdbc41.internal.apache.thrift.transport.TSas/Transport.open(TSas|Transport.java:288) at com.cloudera.impala.jdbc41.internal.apache.thrift.transport.TSas|ClientTransport.openTSas|ClientTransport.java:37) at com.cloudera.impala.hivecommon.api.HiveServer2ClientFactory.createTransport(Unknown Source) at com.cloudera.impala.hivecommon.api.HiveServer2ClientFactory.createClient(Unknown Source) at com.cloudera.impala.hivecommon.core.HiveJDBCCommonConnection.establishConnection(Unknown Source) at com.cloudera.impala.impala.core.impala/DBConnection.establishConnection(Unknown Source) at com.cloudera.impala.jdbc.core.LoginTimeoutConnection.connect(Unknown Source) at com.cloudera.impala.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source) at com.cloudera.impala.jdbc.common.AbstractDriver.connect(Unknown Source) at org.jkiss.dbeaver.model.imp|jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176) at ora.ikiss.dbeaver.model.impl.idbc.JDBCDataSource.openConnectionJDBCDataSource.iava:195)


org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:135) at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connectJDBExecutionContext.java:101) at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContextUDBCRemoteInstance.java:100) at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>JDBCRemotelnstance.java:59) at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109) at org.jkiss.dbeaver.ext.generic.mode .GenericDataSource.<init>(GenericDataSource.java:107) at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSource|mpl(GenericMetaModel.java:90) at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSourceGenericDataSourceProvider java:106) at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:897) at org.jkiss.dbeaver.runtime.jobs.Connect/ob.run(Connect/ob.java:70) at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTest/eb.java:103) at org.jkiss.dbeaver.model.runtime.Abstract/ob.run(Abstract/ob.java:105) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63) Session Data: eclipse.buildld=unknown java.version =[11.0.9.1/ java.vendor=AdoptOpen/DK](http://11.0.9.1/%0Djava.vendor=AdoptOpen/DK) BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US Command-line arguments: -os win32 -ws win32 -arch x86_64 -data C:\Program Files\dbeaver\.dbeaver4\data

**Comment by E1izabeth** [comment]
There is no error message in the provided logs parts; please send the full logs or at least a full log entry starting with an error message

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide full log files.
