### ISSUE TITLE
Impossible to enable TLS 1.3 in Connection Settings

### ISSUE THREAD

**Issue by ophelialifeeva** [dbeaver/dbeaver#35626]
### Description

I cannot find an option to enable TLS 1.3 in Connection Settings - Driver properties. The following options are available: TLS, TLSv1, TLSv1.1, TLSv1.2.
![image](https://github.com/user-attachments/assets/603e8e9b-ae7f-4696-a2d4-8e735bc97431)

### DBeaver Version

Version 24.2.0.202409011551

**Comment by E1izabeth** [comment]
Please provide me with your driver and server version. You can access this information by clicking the `Test connection...` button in the `Connection configuration` dialog.
![image](https://github.com/user-attachments/assets/8500d7c1-9f94-4fd6-843e-98bceffb1c5d)

**Comment by ophelialifeeva** [comment]
Well, now I just tried to create new connection without indicating host name. And noticed that interface lets me choose TLSv1.2, but there is no option to choose TLSv1.3.

**Comment by E1izabeth** [comment]
Please tell me your driver and server versions

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by ophelialifeeva** [comment]
<img width="411" height="293" alt="Image" src="https://github.com/user-attachments/assets/3b43aded-6216-4bbe-91d0-a4b66ef79f73" />

**Comment by ophelialifeeva** [comment]
@E1izabeth could you check it please?

**Comment by SolovevAnton** [comment]
We recently made some changes and expect that it may solve this issue. Please try Early Access version and let me know if the issue is still actual. You can download this version here https://dbeaver.io/files/ea/

**Comment by ophelialifeeva** [comment]
Hi, actually this Early Access version still does not have TLS 1.3 in the dropdown list.

**Comment by ophelialifeeva** [comment]
<img width="719" height="692" alt="Image" src="https://github.com/user-attachments/assets/a73d1a68-7f44-4682-93fa-2066cfc5af08" />

**Comment by IvanGorshechnikov** [comment]
Looks like it is a bug in the SQL Server JDBC driver. It doesn't show TLSv1.3, but it actually supports it. Could you type this version manually and test?
