### ISSUE TITLE
No Trusted Certificate Found When Connecting to Snowflake

### ISSUE THREAD

**Issue by mrcolumbia** [dbeaver/dbeaver#35631]
### Description

My connection to Snowflake was working just fine prior to recently. Suddenly I'm getting the error: 

`JDBC driver encountered communication error. Message: No trusted certificate found.`

Does anyone know what could be causing this?

### DBeaver Version

Community Edition 24.1.5.202408181605

### Database and driver

Snowflake

**Comment by mrcolumbia** [comment]
I found that Snowflake may have had a certificate authority change recently:
 https://docs.snowflake.com/en/release-notes/bcr-bundles/un-bundled/bcr-1657. Hopefully that helps.

**Comment by anthonyrussano** [comment]
the fix for us was to 
Open DBeaver, open the Window Menu > Preferences > Connections > Security >
Uncheck "Use Windows TrustStore"
Restart DBeaver
![image](https://github.com/user-attachments/assets/d297e60d-f46a-479a-b725-1bd889c3dca4)

**Comment by E1izabeth** [comment]
@mrcolumbia do provided suggestions help? Is the issue still actual?

**Comment by mrcolumbia** [comment]
The issue went away on its own the next day. My best guess is that
Snowflake was trying something out and then walked it back?

**Comment by E1izabeth** [comment]
Thank you for sharing. I'm closing the issue then
