### ISSUE TITLE
Dbeaver not authorized to 

### ISSUE THREAD

**Issue by inspire22** [dbeaver/dbeaver#35638]
### Description

Just wanted to bring this up again - having this kind of 'extra queries by default that will definitely crash your server if it's very large ' is exceedingly dangerous should NOT be on by default...

https://github.com/dbeaver/dbeaver/issues/12087

### DBeaver Version

Community 23.0.4.202305071722

### Operating System

Windows 11

### Database and driver

mysql

### Steps to reproduce

Trying to run an sql command like update items  SET tagnames=concat(tagnames, ", adult") WHERE id=17939088

Causes the query SELECT DISTINCT tagnames\nFROM apm.items\nORDER BY 1 to be sent by dbeaver without permission and without any logging in the query log.  As there are ~20m rows and this is not an indexed column, this crashes the site.

Quite a few folks have had this problem as evidenced in the original ticket.

Thanks for an otherwise great program :)

**Comment by E1izabeth** [comment]
Judging by the description and the query, it was sent by autocompletion engine. You can switch automatic autocompletion proposals off for this connection in `Connection configuration->SQL Editor->Code completion` or globally in `Preferences->Editors->SQL Editor->Code Completion`
![image](https://github.com/user-attachments/assets/7cf16ee2-697a-4efa-ade2-deb8edd7f2b3)

About Query Manager. By default, it doesn't show all queries. You can configure it from the context menu
![image](https://github.com/user-attachments/assets/facd3f06-7ea6-483d-b37b-fac3d58de072)
or in Query Manager Properties
![image](https://github.com/user-attachments/assets/c57fbd2f-ab3a-4141-8ec8-4bc03b1cfc93)

**Comment by inspire22** [comment]
Thanks, I appreciate the detail on how to turn it off, I've done so :)

Wouldn't you agree though that it probably shouldn't be sending these queries automatically if they'll crash most databases?

**Comment by E1izabeth** [comment]
I would turn off the `Show values` setting, which turns on the proposals that require SELECT DISTINCT queries, and leave `Enable auto-activation` and `Activate on typing` turned on.
![image](https://github.com/user-attachments/assets/70572ee4-4bd9-4181-a0c1-107a33d4d0a9)
