### ISSUE TITLE
Remember column reorder per table

### ISSUE THREAD

**Issue by bombillazo** [dbeaver/dbeaver#35655]
**Is your feature request related to a problem? Please describe.**
Some DBs (like PostgreSQL) do not allow for column position changing in a table. This makes it hard to organize columns since their order will depend on how the table was created.

**Describe the solution you'd like**
It would be great for DBeaver to render columns and store the order as the users change it in the GUI so that the order is maintained the next time the user opens the table.

**Describe alternatives you've considered**
Having to create a view, which is more work than DBeaver simply remembering the order and introduces a new DB entity simply for presentation purposes

**Comment by E1izabeth** [comment]
This feature exists. Here is a short video showing how to use it:


https://github.com/user-attachments/assets/165aa0f2-ff83-44f3-931c-17e62a4b8965

**Comment by bombillazo** [comment]
Oh excellent! Did not know about this at all, this is a game changer for me, thanks!
