### ISSUE TITLE
${time} variable for script name does not work

### ISSUE THREAD

**Issue by Thomas-LEILLET-Sanofi** [dbeaver/dbeaver#35666]
### Description

${time} variable for script name does not work
![image](https://github.com/user-attachments/assets/1b9f3090-97eb-4349-9721-167d38be7c02)
![image](https://github.com/user-attachments/assets/b80e302d-8906-468e-b0db-2b1619b8324b)

### DBeaver Version

CE Version 24.2.0.202409011551

### Operating System

Win11 23H2 (Build 22631.4169)

**Comment by E1izabeth** [comment]
Thank you for your report.

**Comment by Thomas-LEILLET-Sanofi** [comment]
Still present in version Version 24.2.3.202410201725

**Comment by Thomas-LEILLET-Sanofi** [comment]
Still not corrected on verison 24.2.4.202411031831.... this is simple yet very annoying issue, can anybody fix it please ?

**Comment by ShadelessFox** [comment]
@Thomas-LEILLET-Sanofi it hasn't been fixed yet. 

We have hundreds of tickets waiting to be resolved. We don't often prioritize such a low-priority issue despite them being trivial to fix.

We have a contribution guide if you want to contribute yourself:
https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code

**Comment by pajonas** [comment]
@Thomas-LEILLET-Sanofi @ShadelessFox I added the PR #36426 to address the issue

![image](https://github.com/user-attachments/assets/404d5ccc-c9ae-4749-bc59-01abafffcf2d)
