### ISSUE TITLE
PostgreDataSource - Remove restriction on databases where datistemplate is true

### ISSUE THREAD

**Issue by DDtMM** [dbeaver/dbeaver#3566]
In PosgreDataSource.java, `DatabaseCache.prepareLookupStatement`, it prepares a query to retrieve all the databases.  In that query is restricts all databases where `NOT datistemplate`.

I have a scenario where I need to query a database from a third party that for whatever unknown reason is marked as a template.  I can actually still query that database in DBeaver if I set the default database in the connection, but it causes all sorts of funkiness, the most annoying of which is the lack of auto complete.

Is there any way that the `NOT datistemplate` restriction get removed, either by just removing it, or by adding an option similar to ShowNDD?  

Personally I feel like just removing it is sufficient for the following reasons:
* The allow connection restriction (`datallowconn`) would still be in place.
* By default the application restricts the display of non-default databases.
* I doubt I'm the only person that has a legitimate reason to query template databases.
* Easiest way to correct "funkiness" that occurs when querying template databases.

**Comment by serge-rider** [comment]
I think we can just add yet another connection property for that

**Comment by DDtMM** [comment]
Thank you! Thank you! Thank you @serge-rider!  Works perfectly.
