### ISSUE TITLE
Catalog name (fullpath to file) is repeated twice in Navigator and looks very long for Excel ODBC

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35677]
### Description

I suggest to do not show fullpath to xlsx-file twice here in Database Navigator.
It is not convenient to resize navigator every time you want to read the xlsx-filename or sheet name, beause the most useful information (actual name of a **file/sheet**) is located at the end of the **fullpath**.
Showing fullpath in Navigator leads to very wide nodes in a tree, especially when the path to the xlsx-file is **very long**.
If user will want to check the certain folder the xlsx-file is located in, he can open connection properties or properties of a workbook.
Specifying the fullpath to the xlsx-file in not necessary in select-query, so these both work correctly (if active catalog is chosen):
```
select * from `C:\exp_data\address_202409171804.xlsx`.`Sheet0$`

select * from `Sheet0$`
```

I suggest to remove text highlighted with yellow color:

**In Database Navigator:** 

![0000004303](https://github.com/user-attachments/assets/b09a92b8-66c3-4c2b-9ae6-1dfdb4fb99b2)

**In Data tab:**

![0000004304](https://github.com/user-attachments/assets/d22c4dac-e305-46f8-874a-8e0b5e8d2761)

**In Sql editor tabs and its tooltips:**

![0000004305](https://github.com/user-attachments/assets/0690b4e7-89c2-4c38-b38f-798501bba10e)

### DBeaver Version

Enterprise Edition 24.2.1-202409122322

### Operating System

Windows 10

### Database and driver

EXCEL 12.00.0000
DBeaver JDBC-ODBC Bridge (ACEODBC.DLL) 1.0.61 (Microsoft Access database engine)

**Comment by ShadelessFox** [comment]
The data shown in the navigator is retrieved directly from the ODBC driver. Since we have one ODBC driver for all drivers, this cannot be fixed/improved in any way.
