### ISSUE TITLE
Need help with password reset

### ISSUE THREAD

**Issue by mbickfordrelay** [dbeaver/dbeaver#35675]
### Description

Hi! I am having trouble logging into our institution's Canvas database using DBeaver. I tried my current Canvas database password and an admin sent me a password reset link but those credentials didn't work either. Is anyone able to assist with this?

### DBeaver Version

Community Edition 24.1.0

**Comment by E1izabeth** [comment]
Is Canvas the name of the database? How are you configuring connection?

**Comment by mbickfordrelay** [comment]
Hi Elizabeth,

When my colleague Martha, cc'ed here, tried to access the test connection, she just received a password authentication error and was unable to see the server and driver information you displayed in your image below. Please advise next steps.

**Comment by E1izabeth** [comment]
Is Canvas the name of the database? How are you configuring connection?

**Comment by E1izabeth** [comment]
I recommend you to contact your database administrator. I'm not sure we can help you

**Comment by E1izabeth** [comment]
Seems this issue is stale. If it's still actual, please let me know and provide additional information
