### ISSUE TITLE
MYSQL dump issue

### ISSUE THREAD

**Issue by uzairali98** [dbeaver/dbeaver#35670]
### Description

im facing improper mysql dump in DBeaver Community 24.2.0, but in older version it was working fine 
MYSQL version == 8.0.39
SOLUTION for now -> reverted to dbeaver  Version 24.1.4.202408041450

### DBeaver Version

Community 24.2.0

### Operating System

Windows

**Comment by E1izabeth** [comment]
Thanks for the bug report.
This is a duplicate of #35421.
You can try the latest Early Access build with fix: https://dbeaver.io/files/ea/
