### ISSUE TITLE
Error installing Office extension in CE 5.1.0

### ISSUE THREAD

**Issue by jniggemann** [dbeaver/dbeaver#3567]
An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.apache.commons.cli,1.3.1
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ce.feature,5.1.0
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ce.nls.feature,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core.application,5.1.0
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core.application.nls,5.1.0
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core.nls,5.1.0
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.db2.nls,1.0.17
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.db2.nls.feature,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.derby.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.erd.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.exasol.nls,1.0.17
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.exasol.nls.feature,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.firebird.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.generic.nls,1.0.17
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.generic.nls.feature,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.h2.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.hsqldb.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.import_config.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.informix.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.mssql.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.mysql.nls,1.0.17
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.mysql.nls.feature,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.netezza.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.oracle.nls,1.0.17
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.oracle.nls.feature,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.phoenix.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.postgresql.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.sample.database,1.0.22
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.sample.database.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.sqlite.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.teradata.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.ui.locks.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.vertica.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.wmi.nls,1.0.17
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.wmi.nls.feature,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.model.nls,1.0.17
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.rcp.feature,2.1.60
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.rcp.nls.feature,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.runtime.ide.core.nls,1.0.17
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.runtime.nls.feature,1.0.17
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.standalone.feature,5.1.0
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.standalone.nls.feature,1.0.17
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ui.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.utils.nls,1.0.17
No repository found containing: osgi.bundle,org.jkiss.wmi.nls,1.0.17

**Comment by serge-rider** [comment]
https://github.com/dbeaver/dbeaver/wiki/Optional-extensions :
`
IMPORTANT: installation won't work if DBeaver is installed in write-protected folder (like Program Files, /Applications, /usr/). To proceed you need to run DBeaver from some non write-protected folder or run it as Administrator/root .
`

**Comment by jniggemann** [comment]
Thank you very much for your answer!

**Comment by lcocbr** [comment]
Hi,

Despite following the instructions here, I am still facing trouble with this installation. Even running latest version of DBeaver **as Administrator** (Windows 10), got the same error every time: 

![dbeavererror](https://user-images.githubusercontent.com/35585962/42073341-986bb950-7b55-11e8-8ee4-5e2e44909f9a.PNG)

Any workaround on this? Tks in adv.
