### ISSUE TITLE
Infor Datalake JDBC - Unable to verify trust for server certificate chain

### ISSUE THREAD

**Issue by bensode123** [dbeaver/dbeaver#35686]
### Description

Unable to connect to Infor Datalake via JDBC driver and Amazon Corretta v8.  Error message below:

```
Data Lake is not available

  com.infor.idl.shaded.javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: Unable to verify trust for server certificate chain [CN=*dmp.inforcloudsuite.com, CN=Amazon RSA 2048 M02, O=Amazon, C=US, CN=Amazon Root CA 1, O=Amazon, C=US]

  com.infor.idl.shaded.javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: Unable to verify trust for server certificate chain [CN=*dmp.inforcloudsuite.com, CN=Amazon RSA 2048 M02, O=Amazon, C=US, CN=Amazon Root CA 1, O=Amazon, C=US]

    javax.net.ssl.SSLHandshakeException: Unable to verify trust for server certificate chain [CN=*dmp.inforcloudsuite.com, CN=Amazon RSA 2048 M02, O=Amazon, C=US, CN=Amazon Root CA 1, O=Amazon, C=US]

    javax.net.ssl.SSLHandshakeException: Unable to verify trust for server certificate chain [CN=*dmp.inforcloudsuite.com, CN=Amazon RSA 2048 M02, O=Amazon, C=US, CN=Amazon Root CA 1, O=Amazon, C=US]

      Unable to verify trust for server certificate chain [CN=*dmp.inforcloudsuite.com, CN=Amazon RSA 2048 M02, O=Amazon, C=US, CN=Amazon Root CA 1, O=Amazon, C=US]

      Unable to verify trust for server certificate chain [CN=*dmp.inforcloudsuite.com, CN=Amazon RSA 2048 M02, O=Amazon, C=US, CN=Amazon Root CA 1, O=Amazon, C=US]

        PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

        PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

          unable to find valid certification path to requested target

          unable to find valid certification path to requested target
```

### DBeaver Version

23.3.3, 22.4.1

### Operating System

Windows 11 (current on updates)

### Database and driver

Infor Datalake (Amazon AWS Hosted) with JDBC driver provided by Infor

### Steps to reproduce

Install driver
Point to library file & folder
Attempt connection
Fails with certificate error

### Additional context

This still seems to work on a couple other workstations but my current installation stopped working last week and subsequent installations on other workstations all now have the same issue.

**Comment by lericsson11** [comment]
Same issue here.

**Comment by E1izabeth** [comment]
Please try changing the setting `Use Windows trust store` in Preferences->Connections and restarting DBeaver. If you haven't overridden the trust store, it might help.

**Comment by bensode123** [comment]
Turns out Infor needed to provide updated TLS certs for their datalake access.  We opened a support request in parallel here and Infor provided the instructions to acquire updated certs.

**Comment by lericsson11** [comment]
> Turns out Infor needed to provide updated TLS certs for their datalake access. We opened a support request in parallel here and Infor provided the instructions to acquire updated certs.

Could you possibly post the instructions from Infor here or provide the KB?   

Thanks!

**Comment by bensode123** [comment]
### Instructions from Infor :

For selective users potentially impacted with the below error while connecting to the Data Lake via 3rd party tools such as DBeaver, or others, please follow the below steps to update the Windows Trust Store on the specific client machine.   

Unable to verify trust for server certificate chain [CN=*.dmp.inforcloudsuite.com, CN=Amazon RSA 2048 M02, O=Amazon, C=US, CN=Amazon Root CA 1, O=Amazon, C=US  

###  Steps:

1. Obtain a copy of your ION API credentials. Opening your credentials locate the "iu" and "pu" entry and their values - We will need to get the certificates of the two URL’s those two URLs. In Edge, open both URLs. You may get a 404 error or something similar, this is fine. We only care about the certificate. For both tabs, click on the lock icon beside the URL  

2. From there, click the connection information  

3. And then the show certificate button  

4. In the certificate info window, click the details tab. In the bottom right of the details tab, click the export button, selecting PKCS#7 certificate chain as the save type.

5. Next, hit windows key + r to open the run dialog, then type mmc  

6. From the console menu bar, select File → Add/Remove Snap-in  

7. Add the certificates snap in, selecting My user account in the preceding options pop-up. Then click OK.  

8. In the side navigation pane, select the new certificates option, then right click on Personal selecting All Tasks → Import  

9. Set the file type to all, then select the first certificate you downloaded in the file selector. Click open, then next.  

10. Select “Automatically select certificate store based on the type of certificate”, then click next and finish to being the import.  

11. Repeat steps 8 through 10 for the remaining certificates.  

12. Once all certificates are imported, exit the mcc console. You may save your profile if you wish.  

13. The latest certificates should now be on your system. You may need to reboot your system for the changes to take effect
