### ISSUE TITLE
The driver received an unexpected pre-login response.

### ISSUE THREAD

**Issue by mrhargro** [dbeaver/dbeaver#35680]
### Description

This isn't so much a dbeaver issue, but curious if anyone has encountered it. My platform team can't figure it out (not a huge surprise). I'm connecting to a sql server and getting this error. I'm the only one who can't connect, but also the only person on a mac. 

The TCP/IP connection to the host server.database.windows.net, port 1433 has failed. Error: "The driver received an unexpected pre-login response. Verify the connection properties and check that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. This driver can be used only with SQL Server 2005 or later.". ClientConnectionId:2acb2450-5e18-4e9b-b791-1b1b186519b2
The TCP/IP connection to the host sql-shared-general-dev-eus2-01.database.windows.net, port 1433 has failed. Error: "The driver received an unexpected pre-login response. Verify the connection properties and check that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. This driver can be used only with SQL Server 2005 or later.". ClientConnectionId:2acb2450-5e18-4e9b-b791-1b1b186519b2

### DBeaver Version

Version 24.0.0.202403110838

### Operating System

Apple M3 Pro Version 14.6.1 (23G93)

### Database and driver

jdbc driver
Azure sql server

**Comment by sircinnamon** [comment]
I'm seeing the same error attempting to connect to a DB running in a Docker container, which was working immediately before updating

**Comment by Matvey16** [comment]
@mrhargro Can you check if your IP is in the list of the accepted IPs on your server? That looks like your address is not allowed to connect to that server.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
