### ISSUE TITLE
Context Menu gets open

### ISSUE THREAD

**Issue by GisaDeve** [dbeaver/dbeaver#35689]
### Description

In script editor with the shortcut Control + Enter, the contex menu gets open in the script editor and on tabs.

### DBeaver Version

Community Edition Versión 24.2.1

### Operating System

macOS Sequoia 15.0

### Database and driver

Every sql editor

### Steps to reproduce

Cursor on script editor use the shortcut Control + Enter

**Comment by E1izabeth** [comment]
Thank you for bug report. It's a duplicate of #35681 Please follow the mentioned issue to get updates

**Comment by hemant171k** [comment]
when we can expect new version to fix this issue

**Comment by E1izabeth** [comment]
@hemant171k please take a look at this comment https://github.com/dbeaver/dbeaver/issues/35109#issuecomment-2306254608
