### ISSUE TITLE
Very slow export in large database because mysql export command use "limit start_index, size"

### ISSUE THREAD

**Issue by fengchao** [dbeaver/dbeaver#3568]
Mysql export for large database is very slow. It even timeout for a database with 400,0000 data here.

I checked the session, the export commands used are as blow, the start index increase 10000 for every command.
 
SELECT * FROM log_20171211 LIMIT 65000, 10000   <---- This is very fast --->
......
SELECT * FROM log_20171211 LIMIT 650000, 10000  <---- This become slow ---> 
......
SELECT * FROM log_20171211 LIMIT 650000, 10000  <---- Very slow and timeout --->

It is the same question as here: 
https://stackoverflow.com/questions/43337824/limit-query-can-not-be-effective

And the solution should be use primary key as data select condition:

SELECT * FROM log_20171211 where ID > 650000 LIMIT 10000

**Comment by serge-rider** [comment]
Most likely you have specified export by segments option. It doesn't make much sense for MySQL, just set it to "single query":
![image](https://user-images.githubusercontent.com/6398845/40959290-e94a5b60-68a4-11e8-8c1b-8e404d3ce04d.png)

Also you can use native database dump (it is much faster but you need to have local MySQL client):
![image](https://user-images.githubusercontent.com/6398845/40959318-08a76bc4-68a5-11e8-9032-a21b601b6812.png)

**Comment by fengchao** [comment]
Thanks, single query fix my issue. 

Should this be documented somewhere. I searched the difference between those two options before but never found the answer. I thought by segment will reduce the loading or table lock time.

**Comment by sirajalam049** [comment]
What in the case of a single table having more than 100 million records? Isn't keyset pagination the solution? @serge-rider
