### ISSUE TITLE
why pressing CTRL+RETURN show a submenu at first

### ISSUE THREAD

**Issue by ebizmis** [dbeaver/dbeaver#35681]
### Description

Previously, when processing CTRL+RETURN, will execute the sql statement directly, but now will prompt a submenu then I need to close the submenu.

### DBeaver Version

Community Edition 24.2.1

### Operating System

MACOS 15

### Steps to reproduce

1. input a statement
2. procesing CTRL+RETURN
3. the submenu prompts.

**Comment by kaushikkishore** [comment]
I am also facing the same issue. Wondering why this is not getting solved, post going back to older version also. 👎🏼

**Comment by kaushikkishore** [comment]
Duplicate already resolved here ->  https://github.com/dbeaver/dbeaver/issues/35109

**Comment by E1izabeth** [comment]
Thank you for report. I'm closing this issue as a duplicate of #35109
