### ISSUE TITLE
Saving stored procedure gets stuck in a loop

### ISSUE THREAD

**Issue by SaintRelion** [dbeaver/dbeaver#35693]
### Description

When saving my Stored Procedure in a remote environment (haven't tested in local), sometimes the button with word Auto on the Topbar, doesn't do a countdown (which usually does, and the save goes thru) and cursor is stuck in loading...

Cancelling the transaction wont even do anything, closing the dbeaver application, wont do anything... cancelling the transaction, get stuck as well

Four process are now stuck; Saving transcation, cancelling transaction for saving transaction, close the app, cancelling transaction for closing app 

### DBeaver Version

Community Edition

### Operating System

Linux Ubuntu 24

### Database and driver

Database Name: MySQL-Server in linux

### Steps to reproduce

1.) Remote Access to Server with SSH
2.) Save procedures a couple of times until the Auto Button doesn't do a countdown
3.) Wait for it to get stuck

### Additional context

1.) Used SSH Tunnels,
2.) Go Daddy VPS

**Comment by E1izabeth** [comment]
Unfortunately, I can't reproduce your issue.
Could you do the following actions? It will help us understand your issue
1. Open Query Manager
![image](https://github.com/user-attachments/assets/f505f676-a578-4af2-a786-ba6c1273c17f)

2. Turn on showing all types of queries 
![image](https://github.com/user-attachments/assets/8065c206-dad8-4457-b597-daeb1c2f0616)

3. Clear log
![image](https://github.com/user-attachments/assets/c7d94ecb-83d9-4684-8862-01ffb182a39e)

3. Reproduce the issue once again

4. Send us the screenshot of the Query Manager view

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide the requested information.
