### ISSUE TITLE
Drivers after upgrade dbeaver

### ISSUE THREAD

**Issue by ccavallie** [dbeaver/dbeaver#35698]
### Description

Following a dbeaver upgrade, we find ourselves having to intervene manually in the driver manager to delete the download items proposed.
Would it be possible to avoid having to intervene systematically in the driver manager and retrieve the drivers by default before upgrading without manual intervention?

### DBeaver Version

24.2.0

### Operating System

Windows 

### Database and driver
![DbeaverAfterUpgrade](https://github.com/user-attachments/assets/bce180cd-da91-4cd6-a3bc-604386d95d37)

### Steps to reproduce

1-Get customised drivers in your dbeaver workspace
2-and then upgrade to the latest version of dbeaver
3-after installation go to the driver manager in the library tab

**Comment by Matvey16** [comment]
@ccavallie Hello. Can you specify how did you create create a custom driver? On you screenshot I see that it is named "MariaDB". Did I understand correctly that you edited the default MariaDB driver by adding custom files manually and by deleting the default maven artifact, that reappears after the update?

**Comment by ccavallie** [comment]
Hello @Matvey16,
YES, that's exactly it and after upgrading, there's bound to be some manual intervention before you can connect.

**Comment by Matvey16** [comment]
@ccavallie Does this happen every time you update or only one time? It didn't reproduce for me by updating from 24.1.0 to 24.2.2
How do you delete the default drivers (by steps)? And also how do you update dbeaver?

**Comment by E1izabeth** [comment]
This issue is stale. If it's still actual, please answer our questions
