### ISSUE TITLE
DDL and PRIMARY KEY ordering

### ISSUE THREAD

**Issue by jzahora** [dbeaver/dbeaver#35700]
### Description

Hello,

I think I have found an error when generating DDL - no key sorting is respected.
DBeaver, version 24.2.1.202409221725, release date: September 23, 2024

Original table creation:
```
CREATE TABLE TestTable (
  ID INT IDENTITY(1,1) NOT NULL,
  [TimeStamp] DATETIME DEFAULT GETDATE() NOT NULL,
  CONSTRAINT PK_TestTable PRIMARY KEY (ID DESC)
)
```

DDL:
```
CREATE TABLE TestTable (
	ID int IDENTITY(1,1) NOT NULL,
	[TimeStamp] datetime DEFAULT getdate() NOT NULL,
	CONSTRAINT PK_TestTable PRIMARY KEY (ID)
);
```

Best Regards,
Jan

### DBeaver Version

Community Edition 24.2.1.202409221725

### Operating System

Windows 10 Pro x64

### Database and driver

Microsoft JDBC Driver for SQL Server

### Steps to reproduce

See Description - always

**Comment by E1izabeth** [comment]
Thanks for the bug report
