### ISSUE TITLE
Export Data Error (Export Completed but no actual file) Oracle

### ISSUE THREAD

**Issue by JMycor29** [dbeaver/dbeaver#35701]
### Description

I am exporting data from my database, it is completed but the file is not there in the file path. It is missing. Can you help me solve this? 
Community Version: DBeaver 24.2.1
Operating System: Windows 11

![unnamed](https://github.com/user-attachments/assets/609c3ae4-17af-4be5-8e8a-f95180963d2b)
![unnamed](https://github.com/user-attachments/assets/51b82adf-2109-499f-84ba-3e4f0a8564ba)
![unnamed](https://github.com/user-attachments/assets/19f45be1-db9b-4359-ba14-90725c63a3cd)
![unnamed](https://github.com/user-attachments/assets/db87dde3-826d-4890-bb5e-8f653034cd8f)

### DBeaver Version

Community Version: DBeaver 24.2.1

### Operating System

Operating System: Windows 11

### Database and driver

Oracle JDBC Driver

**Comment by E1izabeth** [comment]
We kindly ask you to reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
You can collect them to archive automatically with `Help->Collect Diagnostic Info`
![image](https://github.com/user-attachments/assets/51c7ca2e-6be2-489e-b495-028b9aa0e386)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide log files.
