### ISSUE TITLE
connect  mongodb failed

### ISSUE THREAD

**Issue by diana0809** [dbeaver/dbeaver#35702]
### Description

when I create a new connetion to mongod， it's failed。
error info is：null coonection returned 
![err](https://github.com/user-attachments/assets/895abeab-f663-4c25-b534-88df62d2477d)

### DBeaver Version

community 21.2.4

### Operating System

windows 10

### Database and driver

mongodb  8.0.0
mongodb-jdbc-2.2.0-all.jar

**Comment by E1izabeth** [comment]
Please check your connection URL and host. Maybe there are some typos, for example, excessive `/` at the end of hostname
If it doesn't help, please reproduce the issue once again. After you reproduce the issue, please send us the DBeaver log files.
You can collect them to archive automatically with `Help->Collect Diagnostic Info`
![image](https://github.com/user-attachments/assets/51c7ca2e-6be2-489e-b495-028b9aa0e386)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide log files
