### ISSUE TITLE
Restriction on deleting an active project has disappeared

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#35706]
### Description

Previously it was impossible to delete an active project, its context menu didn't have this item. Most likely it was broken after refactoring merge.
Steps to reproduce:
1. Open the Projects view
2. Call the context menu for the active project
Expected: No Delete menu Item
Actual: Delete item exists in the context menu, and we can successfully delete active project, after that no active project is selected

### DBeaver Version

24.2.2

### Operating System

win11

**Comment by E1izabeth** [comment]
It worked on 24.2.1
