### ISSUE TITLE
DBeaver connected MYSQL always failed

### ISSUE THREAD

**Issue by candynami** [dbeaver/dbeaver#35714]
Question description 

Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

We tried to reinstall the application. In addition, we tried to fix the GPT display issue based on the Chat GPT command, but it failed to work.please help me.Thanks.

![截图 2024-09-26 09-55-44](https://github.com/user-attachments/assets/16ad6e3b-b832-4c7f-9843-8081999c047e)

**Comment by E1izabeth** [comment]
Are you connecting to the local MySQL database or using SSH, SSL, etc.?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
