### ISSUE TITLE
mssql - clicking on Grid button crashes result panel after select

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#3571]
Version: 5.1.0
OS: Windows 10

Can someone else verify they get a error message on after select with join and clicking on Grid button that the result panel crashes and can't be recovered to show information? only on a new script panel or reconnect you can get the result again.

In my case I get a warning/error message. The result panel changes but still I can't recover it to show grid instead have to "restart" the script panel.

**Comment by serge-rider** [comment]
I can't reproduce that.
Could you post error/debug log with this error stacktrace? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by nmat** [comment]
Interesting. I can't reproduce it now either. I got a warning before and then the result dissapeared. I had to restart the application completely. Anyway I will reopen if I do encounter it again. Thank you.
