### ISSUE TITLE
try to show TDENGINE database tables，GUI stuck at “loading” interface

### ISSUE THREAD

**Issue by realcrazysun** [dbeaver/dbeaver#35716]
### Description

![image](https://github.com/user-attachments/assets/91f7a9e3-102a-40c7-9f34-bc6b354484cc)
TDENGINE is timeseries type database。
I tried open a database connection with  about 170k tables.
Then dbeaver stucked all the time.
No matter how many times it is restarted, there is still no effect.

### DBeaver Version

Community Edition 2.4.1

### Operating System

macOS ventura 13.5.1

### Database and driver

TDENGINE

### Steps to reproduce

I tried open a database connection with  about 170k tables.

**Comment by Matvey16** [comment]
@realcrazysun Thank you for the report. Can you please try changing this setting to something smaller like 100 and check if it would still freeze
![image](https://github.com/user-attachments/assets/2cd30716-664c-4bc5-81cd-7fc318970e82)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know.
