### ISSUE TITLE
Allow comma to be used as a row delimiter in advanced copy

### ISSUE THREAD

**Issue by jahlbornG** [dbeaver/dbeaver#35712]
**Is your feature request related to a problem? Please describe.**
I'm often looking at rows of data, and want to use the ids from those rows of data as a query in another table.  e.g. i'm looking at

1 | row1
2 | row2
3 | row3

i want to select the 1, 2, 3 and use them as part of an "in" query on another table, e.g. "other_table_id in (1, 2, 3)".  there is no way to do this currently in dbeaver (that i'm aware of).

**Describe the solution you'd like**
The advanced copy operation _almost_ enables this functionality, except that the choice of "row delimiters" does not include a  ",".  By including the "," character as one of the options, we could use the advanced copy option to copy the ids as the string "1,2,3", thus allowing them to be easily used in an "in" query.

**Describe alternatives you've considered**
Not aware of any other way to easily copy the data in the desired form.  The "copy as CSV" copy command could potentially be used as well, but again, the choices for "row delimiter" are constrained to newline characters.

**Additional context**
Here is the fix:

~~~~~
diff --git a/plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/handler/ResultSetHandlerCopySpecial.java b/plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/handler/ResultSetHandlerCopySpecial.java
index a1b01a7619..ab7b00cfd9 100644
--- a/plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/handler/ResultSetHandlerCopySpecial.java
+++ b/plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/handler/ResultSetHandlerCopySpecial.java
@@ -143,7 +143,7 @@ public class ResultSetHandlerCopySpecial extends ResultSetHandlerMain implements

             createControlsBefore(group);
             colDelimCombo = UIUtils.createDelimiterCombo(group, ResultSetMessages.copy_special_column_delimiter, new String[] {"\t", ";", ","}, copySettings.getColumnDelimiter(), false);
-            rowDelimCombo = UIUtils.createDelimiterCombo(group, ResultSetMessages.copy_special_row_delimiter, new String[] {"\n", "|", "^"}, copySettings.getRowDelimiter(), false);
+            rowDelimCombo = UIUtils.createDelimiterCombo(group, ResultSetMessages.copy_special_row_delimiter, new String[] {"\n", "|", "^", ","}, copySettings.getRowDelimiter(), false);
             quoteStringCombo = UIUtils.createDelimiterCombo(group, ResultSetMessages.copy_special_quote_character, new String[] {"\"", "'"}, copySettings.getQuoteString(), false);

             Composite placeholder = UIUtils.createPlaceholder(group, 2);
~~~~~

**Comment by E1izabeth** [comment]
Thank you for your request. You could contribute your idea. Here is the guide https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code

**Comment by jahlbornG** [comment]
> Thank you for your request. You could contribute your idea. Here is the guide https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code

@E1izabeth  i thought i did contribute it by including the code fix above?

**Comment by E1izabeth** [comment]
To make a contribution, you need to create a Pull Request.

**Comment by Arthur-Barreto** [comment]
May I work on it a make a pr @E1izabeth ?

**Comment by E1izabeth** [comment]
@jahlbornG Do you have plans to make a Pull Request?

**Comment by jahlbornG** [comment]
> @jahlbornG Do you have plans to make a Pull Request?

no

**Comment by E1izabeth** [comment]
@Arthur-Barreto  you can work on it

**Comment by loopsFreitag** [comment]
@E1izabeth is [this PR](https://github.com/dbeaver/dbeaver/pull/36101) enough?

**Comment by E1izabeth** [comment]
@jahlbornG thanks for the contribution! We will review your PR and let you know
