### ISSUE TITLE
DBeaver 24.2.1 - An error has occurred See the log file - java.lang.UnsatisfiedLinkError: Could not load SWT library

### ISSUE THREAD

**Issue by carlosesilvadev** [dbeaver/dbeaver#35722]
### Description

Bom dia!

Pessoal,

Desde que houve o lançamento da nova versão do dbeaver na versão 24.2.1 está sendo apresentado o erro abaixo no log no momento de abrir a aplicação:

java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: C:\Users\Godfather\Downloads\dbeaver\swt-win32-4966r5.dll: The specified procedure could not be found

Como medida de contorno estou utilizando a versão anterior 24.2.0 que está funcionando normalmente.

Mas para a nova versão eu já tentei atualizar o java, já tentei executar em modo de compatibilidade em outros S.O., já tentei executar como administrador, a dll indicada no log existe no caminho informado do erro.[enter image description here](https://i.sstatic.net/pzQXZsCf.png)

### DBeaver Version

24.2.1

### Operating System

Windows Server 2016

### Database and driver

Microsoft JDBC Driver for SQL Server - 12.8.0.jre11
Microsoft JDBC Driver for SQL Server Authentication Library for Windows - 12.8.0.x64

### Steps to reproduce

Eu tento abrir o aplicativo dbeaver.exe quando é retornado o erro da imagem https://i.sstatic.net/pzQXZsCf.png

### Additional context

Se eu volto para a versão anterior a 24.2.0 funciona normalmente. O erro só ocorre na nova versão que foi disponibilizada no site.

**Comment by E1izabeth** [comment]
Thank you for the bug report.
I'm closing it as it's a duplicate of #35694
