### ISSUE TITLE
Export Data: Selection option for table columns missing in latest version

### ISSUE THREAD

**Issue by dibyendumca** [dbeaver/dbeaver#35733]
Hello,
The feature for choosing the table columns, while taking Data Export is missing in the new version 24.2.1.202409221725.
This feature was there in the older versions, but not available anymore now.

Also there is no option to take Database Backup for MSSQL Server databases.

Thanks

**Comment by E1izabeth** [comment]
Hi, @dibyendumca 
The section with this button is collapsed now
![image](https://github.com/user-attachments/assets/b91894fd-9b42-4271-98cf-f0dda7c8670d)
Just click on the arrow
![image](https://github.com/user-attachments/assets/d23fd326-4a25-4183-9ced-63ada89bacae)

**Comment by E1izabeth** [comment]
Maybe we can improve it and add `(click to expand)` to the `General` group name

**Comment by dibyendumca** [comment]
Hello,
I think by default the below style was good
![image](https://github.com/user-attachments/assets/5633e1c6-92ff-46fb-845e-4370e98cf265)
