### ISSUE TITLE
Wrong DDL generated for MariaDB events.

### ISSUE THREAD

**Issue by queueseven** [dbeaver/dbeaver#3573]
This bug happens in DBeaver 5.1.0.

Create an event on a MariabDB database, like this:

```
create event someEvent
  on schedule
    every 1 day do
    delete from something;
```

Now right click on that event in the Database Navigator and choose Generate SQL -> DDL.

Expected result: Show the correct DDL to recreate the event.

```
create event someEvent
  on schedule
    every 1 day do
    delete from something;
```

Actual result: only a part of the DDL is shown

```
delete from something;
```

**Comment by serge-rider** [comment]
Good point
