### ISSUE TITLE
Grouping panel: set grid color

### ISSUE THREAD

**Issue by EstebanSignorini** [dbeaver/dbeaver#3574]
In the grouping panel you can not configure the color in the grid.

![image](https://user-images.githubusercontent.com/39194077/40986476-a9941bf6-68bc-11e8-84cd-5e440cab793c.png)

**Comment by EstebanSignorini** [comment]
Some rows are white, others black because the option is activated "Mark odd/even rows"

![image](https://user-images.githubusercontent.com/39194077/40988466-85494df2-68c1-11e8-8f2c-0762400752c5.png)

**Comment by serge-rider** [comment]
Thanks for report. The bug is not related to odd/even rows, it is just incorrect detect of background/foreground colors for embedded results viewer.

**Comment by EstebanSignorini** [comment]
Thanks for fixing it so fast.
