### ISSUE TITLE
shortcut key to execute query causing context menu to be displayed

### ISSUE THREAD

**Issue by TobyHewing** [dbeaver/dbeaver#35754]
### Description

When I execute a query using the shortcut control-enter the query executes fine but the query context menu is displayed (as if I had mouse clicked on the query to get the execute / file / format etc context menu).

I can press escape to make this disappear but then the script tab context menu is displayed (which I can also make disappear by esc again)

### DBeaver Version

Version 24.2.1.202409221725

### Operating System

macOS Sequoia 15.0

**Comment by E1izabeth** [comment]
Thank you for report. It's a duplicate of #35109
Please follow this steps to fix it on your mac https://github.com/dbeaver/dbeaver/issues/35109#issuecomment-2306254608
