### ISSUE TITLE
Darkest Theme not installable

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#35757]
### Description

I just encountered that the darkest theme is not installable

`Darkest Dark Theme - https://www.genuitec.com/updates/devstyle/ci/`

just times out.

Is this intended?

### DBeaver Version

24.2.1

### Operating System

Mac

**Comment by E1izabeth** [comment]
Hi, @JamesInform 
It's a 3rd-party plugin for the Eclipse platform, on which DBeaver relies. We don't maintain it. Maybe the official web site of this plugin will help you https://www.genuitec.com/tech/darkest-dark/

**Comment by TB-HunBoka** [comment]
Actually based on the https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle#maint-content-area it has been moved to https://devstyle.codetogether.io

I tried to install it, but the client looked like stuck in a loop when it tried to Calculate requirements and dependencies.
![image](https://github.com/user-attachments/assets/74019e9c-ac9d-4e5b-ae98-d6f9117991c8)
Looks like it tries to reach the same host, but it could not.

Can @JamesInform try that url instead and check if you can install the darkest dark theme?

If you can then the location should be changed for the Darkest Dark Theme to: https://devstyle.codetogether.io
![image](https://github.com/user-attachments/assets/c4076107-1a4b-43d3-8d1c-c5d693396706)

![image](https://github.com/user-attachments/assets/ed59dc2b-2061-4a2f-b97a-dfa8f934850b)

**Comment by TB-HunBoka** [comment]
Also it is available in the marketplace.
![image](https://github.com/user-attachments/assets/3813f16b-541c-4e63-b9c5-c906aa61581f)
Is it possible to enable the marketplace on dbeaver? I thought it is enabled.

**Comment by TB-HunBoka** [comment]
On Eclips 2024-09
  I could install it from https://devstyle.codetogether.io
  The old address gives me an instant timeout error
On Dbeaver
  I can't install itt, it is stuck
  The old address stuck for minutes, and then I got the timeout issue.

I will try to install it from the new url and let the dbeaver run for hours to see if the issue is the amount of time we need to wait to have the timeout issue.

**Comment by TB-HunBoka** [comment]
I was able to install it from the new url.
![image](https://github.com/user-attachments/assets/11120ce9-c2b4-47db-8297-8718c01fcfde)

It took around 20 minutes. The problem looks like the client waits too long for the timeout error and keeps trying to open the old URL.

Dbeaver side I recommend replacing the Location for Darkest Dark Theme.

**Comment by JamesInform** [comment]
> Actually based on the https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle#maint-content-area it has been moved to https://devstyle.codetogether.io
> 
> I tried to install it, but the client looked like stuck in a loop when it tried to Calculate requirements and dependencies. ![image](https://private-user-images.githubusercontent.com/126617861/372458103-74019e9c-ac9d-4e5b-ae98-d6f9117991c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODYyMTksIm5iZiI6MTcyNzc4NTkxOSwicGF0aCI6Ii8xMjY2MTc4NjEvMzcyNDU4MTAzLTc0MDE5ZTljLWFjOWQtNGU1Yi1hZTk4LWQ2ZjkxMTc5OTFjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxMjMxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTRiMWFhNmVlZWQxOTdkMTcyZGM5MGMxZDNmNGNhNzFlOTdhMGVlODI5M2MzODgyMWJlMzFlMDI2MzIxYjVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0lajZRQs1_TKLspWryDlWBvaxKUpclUcWh7r5ZtoJgE) Looks like it tries to reach the same host, but it could not.
> 
> Can @JamesInform try that url instead and check if you can install the darkest dark theme?
> 
> If you can then the location should be changed for the Darkest Dark Theme to: https://devstyle.codetogether.io ![image](https://private-user-images.githubusercontent.com/126617861/372453012-c4076107-1a4b-43d3-8d1c-c5d693396706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODYyMTksIm5iZiI6MTcyNzc4NTkxOSwicGF0aCI6Ii8xMjY2MTc4NjEvMzcyNDUzMDEyLWM0MDc2MTA3LTFhNGItNDNkMy04ZDFjLWM1ZDY5MzM5NjcwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxMjMxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjUzNWRkMDg2M2ZlNzYzNjM3MGU3Yzk0MWRjNjEzZWFmZjA1MDMzN2U3MGVjMWUwNjVmMzAyYWE5OTJlYTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wYxCd8wFeKaQ5VKkZACc9smMELc6YIINqBZ-749pWVM)
> 
> ![image](https://private-user-images.githubusercontent.com/126617861/372453495-ed59dc2b-2061-4a2f-b97a-dfa8f934850b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODYyMTksIm5iZiI6MTcyNzc4NTkxOSwicGF0aCI6Ii8xMjY2MTc4NjEvMzcyNDUzNDk1LWVkNTlkYzJiLTIwNjEtNGEyZi1iOTdhLWRmYThmOTM0ODUwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxMjMxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjYyYTA4MWE0MzkwMzMwMjg5YzA5NGJmNTRiNTIwYWQ4YThmNjZkOTUwNmU3YjY2NWViMjQ5N2RiM2Y1MjZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wsZmphwz8_2YQGx63rhwsMdegMfQveNPVswZQnDRChc)

Yeo, that works for me. Took about 1.5 minutes to resolve dns things, but then installs flawlessly.

**Comment by E1izabeth** [comment]
@TB-HunBoka, thanks for your help.
Could you clarify what you mean by "Dbeaver side I recommend replacing the Location for Darkest Dark Theme"? I don't see any mentions of the exact URL in our docs. Am I missing something?

**Comment by TB-HunBoka** [comment]
@E1izabeth I didn't chek it, but I thought this is where the Software Sites Locations are stored:
https://github.com/dbeaver/dbeaver/blob/4f17673f6f5ee29c15d1b5d2dcd63bcd42be358c/product/community/DBeaver.p2.inf#L16
Am I wrong?

**Comment by E1izabeth** [comment]
@TB-HunBoka
Ah, I see, thank you. I thought you were talking about some Wiki page.
We will change this link.

**Comment by JamesInform** [comment]
It seems that the repository location has been changed back to:
https://www.genuitec.com/updates/devstyle/ci/

**Comment by TB-HunBoka** [comment]
> It seems that the repository location has been changed back to: https://www.genuitec.com/updates/devstyle/ci/

The URL provided by you now gives 404 error. However, the new url that was deployed recently, works.
Can you verify this?

**Comment by JamesInform** [comment]
Strange, it works for me. 

![image](https://github.com/user-attachments/assets/c83d7471-cbc7-4e1a-8fa6-f2045f6acc6c)

**Comment by TB-HunBoka** [comment]
> Strange, it works for me.
> 
> ![image](https://private-user-images.githubusercontent.com/38714600/379008487-c83d7471-cbc7-4e1a-8fa6-f2045f6acc6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2Mjk3NTgsIm5iZiI6MTcyOTYyOTQ1OCwicGF0aCI6Ii8zODcxNDYwMC8zNzkwMDg0ODctYzgzZDc0NzEtY2JjNy00ZTFhLThmYTYtZjIwNDVmNmFjYzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDIwMzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MTI5ZThlYTg2MDdmYWRjZmFjMjFmYTk3YzVjYjEyMTRhM2Q2MTk4YzJlN2RkMGU1NmQ2ZTBkNGM1NDI2ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5HD8t4eUXA_V2UMspulwHsCapybEIp7JAY5mRyTq_Kg)

You are right, now it works for me too.
However, currently both link works.
