### ISSUE TITLE
Feature request: Display a parameter's default in Properties tab

### ISSUE THREAD

**Issue by DedicatedTools** [dbeaver/dbeaver#3575]
Using DBeaver CE v5.1.0 on PostgreSQL 9.6.

It would be helpful to have a function parameter's _Default_ column in _Function Properties_ tab, _Function parameters_ sub-tab, next to (or in front of) the _Ordinal Position_ column

![image](https://user-images.githubusercontent.com/6936601/40998284-564b767e-68d5-11e8-970c-b91ce3cf62c8.png)

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/41308695-533012be-6e85-11e8-9721-24e2ec734bf2.png)

**Comment by serge-rider** [comment]
Will be added in 5.1.1

**Comment by DedicatedTools** [comment]
Cool. Thank you very much!
