### ISSUE TITLE
TABLESPACE not recognized by autocompletion for PostgreSQL database

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#3576]
Hi,

This is just a minor issue, but I noticed that the TABLESPACE keyword is not recognized as a valid keyword by the autocompletion and thus not highlighted, even though table spaces are listed in the Database Navigator. This is with DBeaver 5.1.0 and PostgreSQL as the database connected.

![afbeelding](https://user-images.githubusercontent.com/7635726/41002633-935badb0-6914-11e8-81c5-70d44a8c1be8.png)

![afbeelding](https://user-images.githubusercontent.com/7635726/41002699-d4c3196e-6914-11e8-9323-ead0c45c9ea9.png)

The query executes without issues though.

**Comment by serge-rider** [comment]
Thanks for noticing
