### ISSUE TITLE
MONGOFB - Timed out after 5000ms ......

### ISSUE THREAD

**Issue by JoeStagner** [dbeaver/dbeaver#35779]
### Description

Mongodb v7.0.15 on Ubuntu 24.04 AS LOCALHOST

Other clients successfully connect but Dbeaver Lite 24.02.0.202409091031  generates the following error: 

Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localmongo:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketException: localmongo}, caused by {java.net.UnknownHostException: localmongo}}]

NOTE: connecting as 127.0.0.1 works as expected

### DBeaver Version

Lite 24.02.0.202409091031  

### Operating System

Ubuntu 24.04

### Database and driver

Mongodb v7.0.15 

org.jkiss.jdbc.mongodb.mongodbDriver

### Steps to reproduce

Install DBeaver Lite (Trial License) 
Try to connect to MongoDB on localhost port 27017

**Comment by E1izabeth** [comment]
The error message says that you're trying to connect to host `localmongo`, which can't be found. Could you check if it's reachable and if there is no typo in the hostname?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
