### ISSUE TITLE
Format SQL

### ISSUE THREAD

**Issue by yaoguoba** [dbeaver/dbeaver#3579]
>settings
1.insert space for tab.
2.tab size is '4'

>issues
1.It will inserts 3 spaces in new line start when I click Enter key.
2.Inserts 1 space in SQL start from the secend SQL when format SQLs.

**Comment by serge-rider** [comment]
Can't reproduce. 
Please post example of SQL query where this is reproducible.

**Comment by yaoguoba** [comment]
![image](https://user-images.githubusercontent.com/18393410/41515152-46100a40-72df-11e8-82f8-90fde987d0a5.png)

**Comment by serge-rider** [comment]
Thanks, now I can reproduce it.
SQL indentation will be fixed in the next version.
