### ISSUE TITLE
Cannot install new software

### ISSUE THREAD

**Issue by kalkun** [dbeaver/dbeaver#35796]
### Description

1. select new software
![image](https://github.com/user-attachments/assets/bee13363-5d01-4081-8d32-0ee513f5dc50)
2. selecting _-- All Sites--_
![image](https://github.com/user-attachments/assets/daabc74b-4996-4da4-abc2-ba6a9d1c1f88)

### DBeaver Version

Community edition Version 24.2.1.202409221725

### Operating System

MacOS Seqouia 15.0 (24A335)

**Comment by kalkun** [comment]
The same is true for checking for updates: 
![image](https://github.com/user-attachments/assets/ae18ff70-4218-4c26-b396-73786fabaa9b)

**Comment by TB-HunBoka** [comment]
Can you try the workaround mentioned in this ticket?
#35705

**Comment by GiantCrocodile** [comment]
Same on Windows 11, so it's no macOS specific issue. Error is quite clear:

Exception during a connection to https://dbeaver.io/product/version.xml
  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    unable to find valid certification path to requested target
    unable to find valid certification path to requested target

**Comment by moerkey** [comment]
Related to.  #35777

**Comment by E1izabeth** [comment]
thank you for reporting, we will try fixing it soon

**Comment by serge-rider** [comment]
There was an issue with https certificates on dbeaver.io. Now it should work ok.

Thank you for the report

**Comment by kalkun** [comment]
Yes works for me now - thanks for the quick response 👍 
![image](https://github.com/user-attachments/assets/4ce5b11b-0198-4566-8995-b04c05604f98)

**Comment by GiantCrocodile** [comment]
Works fine, thank you.

**Comment by E1izabeth** [comment]
Thank you for checking. I'm closing the issue as solved then
