### ISSUE TITLE
incorrect representation of nested arrays

### ISSUE THREAD

**Issue by kudrevatykh** [dbeaver/dbeaver#35795]
### Description

I have clickhouse database with some columns of type Array(Array(String)), Array(Array(Enum8)) or Array(Array(UUID))
When I trying to select those values I have incorrect representation of such values in results panel. Correct representation shown only when all values are fully expanded. Attached video wich would show problem

### DBeaver Version

Community edition 24.2.1.202409221725

### Operating System

Debian GNU/Linux 12 (bookworm)

### Database and driver

clickhouse 23.8
clickhouse jdbc 0.6.1

### Steps to reproduce

1. create table with column of type Array(Array(String))
2. insert value like [['XXX'],['YYY']]
3. select value from table

[Screencast from 2024-10-03 13-20-08.webm](https://github.com/user-attachments/assets/4cf2fcc8-eedb-41fb-bbf3-3907dad7f078)

**Comment by ShadelessFox** [comment]
Hello @kudrevatykh,

Can you please try the latest version of DBeaver to see if the issue is gone there? https://dbeaver.io/files/ea/

**Comment by kudrevatykh** [comment]
Hi @ShadelessFox 
I tried ea version and it seems this version doesn't have this bug.

**Comment by ShadelessFox** [comment]
Thanks for checking out. I assume the issue can be closed now.
