### ISSUE TITLE
Dbeaver An error has occurred. See the log file C:\Users\[User]\AppData\Roaming\DBeaverData\workspace6\.metadata\.log.

### ISSUE THREAD

**Issue by SutthikiatPad** [dbeaver/dbeaver#35793]
### Description

Dbeaver An error has occurred. See the log file C:\Users\[User]\AppData\Roaming\DBeaverData\workspace6\.metadata\.log.

Windown 11
Version Setup : dbeaver-ce-23.1.3-x86_64-setup , dbeaver-ce-24.0.0-x86_64-setup

![messageImage_1727925729331](https://github.com/user-attachments/assets/522bdead-57b1-49a7-b9df-6efa4987ceea)

### DBeaver Version

dbeaver-ce-24.0.0-x86_64-setup , dbeaver-ce-23.1.3-x86_64-setup

### Operating System

Windown 11

### Steps to reproduce

1.Setup Dbever success
2.Open > Error "Dbeaver An error has occurred. See the log file C:\Users\[User]\AppData\Roaming\DBeaverData\workspace6\.metadata\.log."

**Comment by ShadelessFox** [comment]
Hello @SutthikiatPad,

It would be really helpful if you provided the mentioned log file. Without it, we have no idea what went wrong.

**Comment by SutthikiatPad** [comment]
@ShadelessFox 
Detail file log
[.log](https://github.com/user-attachments/files/17242611/default.log)

**Comment by ShadelessFox** [comment]
Thank you.

Is this the first time you have installed DBeaver? Have you used it before? If so, can you name a version that definitely used to work before the update?

**Comment by SutthikiatPad** [comment]
@ShadelessFox  
I have never used Dbever before and when I install it to use Dbever it logs an error.

**Comment by Phillipus** [comment]
`Caused by: java.net.URISyntaxException: Illegal character in path at index 25: file:/C:/Users/Sutthikiat Padsaeng/AppData/Roaming/DBeaverData/workspace6/`

There's a space in the path.

**Comment by serge-rider** [comment]
Unfortunately it is not a space (we handle spaces correctly). It is a NBSP character (0xA0).
Not a good idea to use special characters in user name, however we should handle this too..
