### ISSUE TITLE
DBeaver hangs after idling post upgrade to 5.10

### ISSUE THREAD

**Issue by alvindchan91** [dbeaver/dbeaver#3580]
![screenshot from 2018-06-05 23-21-28](https://user-images.githubusercontent.com/9006641/41020408-9d0a0dfe-6917-11e8-86a2-e0b3443f286b.png)
It never gets my data and I have to disconnect from the remote postgres database by closing the whole app.

**Comment by serge-rider** [comment]
Please post steps to reproduce.
What database, does it hang always on some particular operation?

**Comment by alvindchan91** [comment]
The remote database is postgres. I'm on Ubuntu 16.04 and I always run "Execute script's statements in separate results tabs" to grab every entry in every table (9 total). There are no more than 15 rows in each table so the data set is small.

It is successful most of the time, but when I idle for a random amount of time(5-30 mins), the program will at times hang.

**Comment by serge-rider** [comment]
I presume that some network timeout happened and connection socket died (this causes very long timeouts especially if you are working over SSH tunnels/proxies).
Workaround: set some keep-alive interval (e.g. 10 seconds) in connection properties dialog, page General.
