### ISSUE TITLE
Table not found in SQL editor when using backticks

### ISSUE THREAD

**Issue by BlackLanzer** [dbeaver/dbeaver#35812]
### Description

While writing a SQL query with table name between backticks, the name turn red with error "Table [name] not found". If I remove backticks the table is found with no problem.

Before updating to version 24.2.1 it didn't show any error, but I don't know what version I was using then.

### DBeaver Version

24.2.1

### Operating System

PopOS 22.04

### Database and driver

MySQL driver

### Steps to reproduce

1. Connect to MySQL DB
2. Create table `my_table`
3. Open SQL editor
4. Write ```SELECT * FROM `my_table`; ```
5. ``` `my_table` ``` show error

**Comment by uslss** [comment]
Unfortunately cannot reproduce the issue. Probably some special steps are needed?
![image](https://github.com/user-attachments/assets/b138f1e7-dacd-4d75-8c89-7ec2c779bb47)

**Comment by BlackLanzer** [comment]
Thank you for the answer.

![image](https://github.com/user-attachments/assets/ac035cd9-c486-4d24-9515-9f6237c4f737)

I have multiple datasources with multiple schemas. Could the problem be there? But I selected the active one.

What else can i check?

**Comment by E1izabeth** [comment]
I reproduced the issue. Thank you for the bug report.
