### ISSUE TITLE
Can't call vectorwise specific statement (combine, rewrite or else)

### ISSUE THREAD

**Issue by AdinCau** [dbeaver/dbeaver#3581]
Hello,

Dbeaver does not recognize vectorwise specific statement like call vectorwise (combine 'table_name');
Same for rewrite.

Those sql statement work on squirrel but not dbeaver :(

Those are specific statement used on vectorwise database from Actian editor.

Here some documentation about this :
http://downloads.actian.com/online/collaterals/vw/vw_developers_v1.5_final.pdf
or
https://communities.actian.com/s/article/call-vectorwise-Statement

[stacktrace.txt](https://github.com/dbeaver/dbeaver/files/2075118/stacktrace.txt)

**Comment by serge-rider** [comment]
DBeaver recognizes this query as a stored procedure call and executes it as a call (using JDBC API prepareCall function).
I could try to add some workaround.

**Comment by AdinCau** [comment]
Hello.

I got another error :(

> eclipse.buildId=unknown
> java.version=1.8.0_77
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.jkiss.dbeaver.model
> Erreur
> Fri Aug 17 14:43:56 CEST 2018
> SQL Error [2500] [42000]: Syntax error on line 1.  Last symbol read was: 'call vectorwise'.

**Comment by serge-rider** [comment]
Could you post full error stacktrace (you can get it in Error Log view).

**Comment by AdinCau** [comment]
this is the full log

![dbeaver](https://user-images.githubusercontent.com/39983732/44323722-66e00b80-a453-11e8-99b8-96556c647ce4.PNG)

**Comment by serge-rider** [comment]
I believe right syntax is 
```
CALL VECTORWISE( COMBINE 'my_table')
```

**Comment by AdinCau** [comment]
sry that what i ment
![capture](https://user-images.githubusercontent.com/39983732/44704875-3e808e80-aa9d-11e8-8461-fa2335d28782.PNG)
