### ISSUE TITLE
SQL error code = -206

### ISSUE THREAD

**Issue by 4ColorDesign** [dbeaver/dbeaver#35813]
### Description

SQL Error [335544578] [42S22]: Dynamic SQL Error; SQL error code = -206; Column unknown; PP.RDB$NULL_FLAG; At line 9, column 4 [SQLState:42S22, ISC error code:335544578]
  Dynamic SQL Error; SQL error code = -206; Column unknown; PP.RDB$NULL_FLAG; At line 9, column 4 [SQLState:42S22, ISC error code:335544578]
  Dynamic SQL Error; SQL error code = -206; Column unknown; PP.RDB$NULL_FLAG; At line 9, column 4 [SQLState:42S22, ISC error code:335544578]
    Dynamic SQL Error
    Dynamic SQL Error
      SQL error code = -206
      Column unknown
      PP.RDB$NULL_FLAG
      At line 9, column 4

### DBeaver Version

24.2.1.202409221725

### Operating System

Windows 11

### Database and driver

Firebird 2.0.1

### Steps to reproduce

1. connected to db and then clicked on procedure table, as this database design was done in 2009

**Comment by E1izabeth** [comment]
Could you do the following actions? It will help us understand your issue
1. Open Query Manager
![image](https://github.com/user-attachments/assets/f505f676-a578-4af2-a786-ba6c1273c17f)

2. Turn on showing all types of queries 
![image](https://github.com/user-attachments/assets/8065c206-dad8-4457-b597-daeb1c2f0616)

3. Clear log
![image](https://github.com/user-attachments/assets/c7d94ecb-83d9-4684-8862-01ffb182a39e)

3. Reproduce the issue once again

4. Send us the screenshot of the Query Manager view or the failed query (it's highlighted with red)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide the requested information.
