### ISSUE TITLE
Statistics result - add elapsed time

### ISSUE THREAD

**Issue by ceinmart** [dbeaver/dbeaver#35815]
Hi, 
My suggestion is for the statistics result when ran a SQL , multiples SQLs , procedures, etc is add the elapsed time. 
Today they show only the start / finish time , however if want to know in seconds / minutes / hour how much time took the execution need to manually calculate theses finish / start time.. 

![image](https://github.com/user-attachments/assets/09bde1df-3c61-477b-9b1b-898dc666ba34)

**Comment by E1izabeth** [comment]
Thanks for the request

**Comment by ShadowWalker98** [comment]
Can I work on this? I'm new though

**Comment by E1izabeth** [comment]
Hi, @ShadowWalker98 
@tlm365 already provided Pull Request
