### ISSUE TITLE
Dracula Theme colors for the editor in dark mode

### ISSUE THREAD

**Issue by hnavia** [dbeaver/dbeaver#35830]
**Is your feature request related to a problem? Please describe.**
The current dark mode colors are not that good. Unfortunately, the dark colors are not so easy to read or identify the queries.

**Describe the solution you'd like**
There's a dark mode theme called Dracula Theme which is clear and easy to read in pretty much any condition. There's also a light version of the theme.

Here's the color palette

https://draculatheme.com/contribute#color-palette

**Describe alternatives you've considered**
I tried to edit the Editors colors but there are to many items and I'm not that good at changing them

**Additional context**
Previously I was able to use the Darkest Dark theme with Dbeaver. But now, the theme works but not the Editor Colors. It would be great if this can be brought back.

**Comment by E1izabeth** [comment]
It's a duplicate of #20707
Such a request should likely be addressed to the  Darkest Dark developers to support DBeaver.
https://github.com/dbeaver/dbeaver/issues/20707#issuecomment-2042441004
