### ISSUE TITLE
Shortcut to run script cause pop up window.

### ISSUE THREAD

**Issue by maragh** [dbeaver/dbeaver#35831]
### Description

Whenever I use the shortcut command (control + return) on Mac OS to run my script It caused a pop up window, and once I closed that popup, a second window opens up.

<img width="1043" alt="image" src="https://github.com/user-attachments/assets/848ec2eb-886d-4d59-a32f-5467a3c5a41d">

### DBeaver Version

DBeaver Enterprise 24.2.0

### Operating System

MacOS Sequoia 15.0

### Steps to reproduce

1. Place the cursor at the end of the script
2. Do control + enter

**Comment by tqvthu-works** [comment]
I have faced the issue too. 
Mac OSX 15
Version 24.0.4.202405051837

**Comment by ShadelessFox** [comment]
This is a "feature" introduced in macOS Sequoia. Please see https://github.com/dbeaver/dbeaver/issues/35109#issuecomment-2306254608

**Comment by tqvthu-works** [comment]
> This is a "feature" introduced in macOS Sequoia. Please see [#35109 (comment)](https://github.com/dbeaver/dbeaver/issues/35109#issuecomment-2306254608)

Thank you. As you said, it is a feature of macOS Sequoia.
