### ISSUE TITLE
Search window problem

### ISSUE THREAD

**Issue by Minux31** [dbeaver/dbeaver#35846]
### Description

Since 24.2.1 version, the search window doesn't display correctly and doesn't allow to enter data (see screenshot). Works normally on 24.2.0

![image](https://github.com/user-attachments/assets/16c28fc3-0997-49be-94b3-b0cb33bf1ea2)

### DBeaver Version

24.2.2

### Operating System

Archlinux / KDE Plasma - Wayland

### Database and driver

Oracle JDBC Driver

### Steps to reproduce

1. Open a new script or an existing script
2. Type Ctrl + F to perform a research

**Comment by E1izabeth** [comment]
Is Eclipse installed as a standalone application or as a plugin for Eclipse? What plugins/extensions do you use?

**Comment by Minux31** [comment]
No Eclipse installed, and no plugins/extensions are used.

This is my complete dbeaver configuration : 
[dbeaver_conf.txt](https://github.com/user-attachments/files/17279388/dbeaver_conf.txt)

**Comment by Minux31** [comment]
To add, search window is resizable in 24.2.0 and previous version, and not in further versions, starting at 24.2.1

**Comment by E1izabeth** [comment]
This dialog comes with the [Eclipse platform](https://github.com/eclipse-platform), on which DBeaver relies. So, I'm unsure it's a DBeaver issue.
As a workaround, you can return the old Find/Replace dialog by checking `Use find/replace overlay` in `General > Editors > Text Editors` https://stackoverflow.com/a/79013331

**Comment by Minux31** [comment]
So, I unchecked "Use find/replace overlay" and search window came back to normal :
![image](https://github.com/user-attachments/assets/44b82ce7-e401-46f0-ac82-00aaceb659b7)

Thank you very much !
