### ISSUE TITLE
Use of Connection General Filters for Schemas/Users broken with version 5.1.0

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#3584]
DBeaver - **Version 5.1.0 CE**
DBeaver JDBC driver: **Microsoft**
Operating System: **Windows 7** / **Windows 8.1** /  **Windows 10**
Database Server: **Microsoft SQL Express 2014**

The use of Connection filters for Schemas/Users seems to have been broken with DBeaver version 5.1.0.

**Neither Include nor Exclude filtering works any more.**

**PS**. Unsure if it misbehaves for other drivers than "Microsoft JDBC".
**PPS**. This looks like the same misbehaviour that I reported for DBeaver version 4.3.1.

**Comment by serge-rider** [comment]
I can't reproduce this. Schema or catalog filters works ok in our test env.
Could you post sample of filters, some screenshots would be also useful.

**Comment by pdanie** [comment]
Hmmmm. The issue can be closed. My bad.

**o** My mistake as I got confused on the change in layout of the **Filter** links (ie. I clicked on the wrong link).

**o** Also tried out to filter **Tables** using the format <schema>.<table name> which did not work at all. Seems the table filter is only text based not anything where I can specify a specific schema.

**Comment by serge-rider** [comment]
Ok
