### ISSUE TITLE
Add hotkey "Toggle Grid/Chart view"

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35865]
**Is your feature request related to a problem? Please describe.**
It would be nice to jump quickly from grid to chart to see the same data graphically.

**Describe the solution you'd like**
I suggest to add hotkey "Toggle Grid/Chart view" (similar to "Toggle Grid/Record view").
First keystroke opens chart, another keystroke - opens grid.
The chosen hotkey doesn't matter if it will be possible to change it in Keys in Preferences.

**Describe alternatives you've considered**
- mouse click (some users prefer keyboard)

**Additional context**

![img](https://github.com/user-attachments/assets/1ea627ce-ad41-416e-9dc5-5c1db635de34)

**Comment by E1izabeth** [comment]
Currently, we have a shortcut Ctrl+` to Switch results presentation https://dbeaver.com/docs/dbeaver/Shortcuts/#result-set
Maybe it fulfills your needs

**Comment by ask9** [comment]
Thank you!
It's works well.
