### ISSUE TITLE
Unable to update git extension after DBeaver 24.2.2 update

### ISSUE THREAD

**Issue by bnelissen-orisha** [dbeaver/dbeaver#35868]
### Description

Hi,

After updating DBeaver to version 24.2.2, I cannot install git extension.

> Cannot complete the install because one or more required items could not be found.
>   Software being installed: DBeaver Git support 1.0.128.202410061621 (org.jkiss.dbeaver.git.feature.feature.group 1.0.128.202410061621)
>   Missing requirement: Git integration for Eclipse - Core 7.0.0.202409031743-r (org.eclipse.egit.core 7.0.0.202409031743-r) requires 'java.package; org.eclipse.jgit.annotations [7.0.0,7.1.0)' but it could not be found
>   Cannot satisfy dependency:
>     From: DBeaver Git support 1.0.128.202410061621 (org.jkiss.dbeaver.git.feature.feature.group 1.0.128.202410061621)
>     To: org.eclipse.equinox.p2.iu; org.eclipse.egit.core [7.0.0.202409031743-r,7.0.0.202409031743-r]

### DBeaver Version

24.2.2

### Operating System

Windows 11

### Steps to reproduce

1. Help
2. Install New Software...
3. Choose DBeaver Git Integration
4. Click Next

**Comment by MashaKorax** [comment]
thanks for your report

**Comment by ldhasson-hmhn** [comment]
Hello :) Is there a workaround or do we have to wait for the next release? I just upgraded and lost my eGit. Not sure if i should go back to a previous release or wait for an imminent patch?

**Comment by jule444ka** [comment]
Yes, it would be great if somebody can help us with the workaround

**Comment by MashaKorax** [comment]
You can install the git extension, from EA: https://dbeaver.io/files/ea/update/ce/
