### ISSUE TITLE
Where is ssh client?

### ISSUE THREAD

**Issue by Mirocow** [dbeaver/dbeaver#3588]
version: 5.1.0
Where is folder calls "Network"

https://monosnap.com/direct/1a4HItqmekhZ7eb6JYO5rHPWRCo3Lo

**Comment by serge-rider** [comment]
This looks like incorrect driver configuration. Perhaps you driver is marked as embedded 9in that case there will be no network configuration. Check it in driver properties dialog.

**Comment by Mirocow** [comment]
maybe
