### ISSUE TITLE
[CUBRID] For 'Use SQL to limit fetch size'

### ISSUE THREAD

**Issue by hwany7seo** [dbeaver/dbeaver#35896]
We'd like to set the default value of 'Data Editor -> Limit import size using SQL' to true and make it work normally.

1. Change default value to true
2. Add constraints related to 'Limit'.

issue is accepted, we will do a PR.

**Comment by AKASHYADAVO** [comment]
Hi, I am interested in taking this issue on .

**Comment by E1izabeth** [comment]
Hi, @hwany7seo. Am I correctly understanding that you want to turn the `Use SQL to limit fetch size` setting to true for Cubrid?
![image](https://github.com/user-attachments/assets/6efa7b16-ec6c-4ace-bcbb-ae0f81bb4109)

**Comment by hwany7seo** [comment]
Dear @E1izabeth 
Yes, we use 'QueryTransformerLimit' and 'DBCQueryTransformerExt' as an extension. 
We have completed testing the limit query through our testcase, and it works fine, so we are requesting a PR.

**Comment by E1izabeth** [comment]
Sure, you can create PR.
Here is the guide https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code#create-pull-request
