### ISSUE TITLE
When set permission, please check the question （Postgresql）

### ISSUE THREAD

**Issue by highgoyangguoqing** [dbeaver/dbeaver#3589]
1.When I click the "Revoke All" button,nothing append(The state of editor is not changed. So Can't save).
![image](https://user-images.githubusercontent.com/34262632/41074679-c81e85e0-6a3b-11e8-815e-9cb65e914a5f.png)
2.When permission's button is clicked many times,generated SQL query is wrong.
click before:
![image](https://user-images.githubusercontent.com/34262632/41075661-4c67a008-6a40-11e8-8694-f7fdebea8b30.png)
"INSERT" button is clicked many times after:
![image](https://user-images.githubusercontent.com/34262632/41075680-628ee1f2-6a40-11e8-93ae-68d349ded162.png)
generated SQL query:
![image](https://user-images.githubusercontent.com/34262632/41075709-76596e46-6a40-11e8-8088-d3a4cdccfda0.png)
please check.Thanks

**Comment by serge-rider** [comment]
Thanks for bugreport
