### ISSUE TITLE
Sometimes autocomplete doesn't add number to the name of the table alias when join the same tables in one query

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35891]
### Description

Alias name "f2" is expected here.

https://github.com/user-attachments/assets/d27a9381-0b1e-4c2b-b823-51c74e1729ab

### DBeaver Version

Enterprise Edition 24.2.3-202410032322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by E1izabeth** [comment]
Thanks for the bug report
