### ISSUE TITLE
Autocomplete adds additional dot after column name in join condition when choosing one of suggestions

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35893]
### Description

Use the query:
```
select * 
from film as f
join film_list as fl on fl.fid =
```

- press Tab to confirm the chosen item from suggestions

https://github.com/user-attachments/assets/1e251c8a-8222-4d5a-9e8e-87130b91f94a

### DBeaver Version

Enterprise Edition 24.2.3-202410032322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by Elizabeth-has** [comment]
> ### Description
> 
> Use the query:
> ```
> select * 
> from film as f
> join film_list as fl on fl.fid =
> ```
> 
> - press Tab to confirm the chosen item from suggestions
> 
> https://github.com/user-attachments/assets/1e251c8a-8222-4d5a-9e8e-87130b91f94a
> 
> 
> 
> 
> 
> ### DBeaver Version
> 
> Enterprise Edition 24.2.3-202410032322
> 
> ### Operating System
> 
> Windows 10
> 
> ### Database and driver
> 
> PostgreSQL 16
> PostgreSQL JDBC Driver 42.7.4
> 
> ### Steps to reproduce
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

**Comment by E1izabeth** [comment]
Thanks for the report

**Comment by E1izabeth** [comment]
I can't reproduce it anymore. We have fixed it.
Could you check?

**Comment by ask9** [comment]
Thanks, I can confirm that it is fixed now.
