### ISSUE TITLE
[posgresql] dbeaver showing invalid Row Count Estimate

### ISSUE THREAD

**Issue by erlangp** [dbeaver/dbeaver#3590]
Bug report
- dbeaver showing invalid "Row Count Estimate" on posgresql connection.

Environment
- posgresql v10 (localhost)
- dbeaver v5.1.0

**Comment by erlangp** [comment]
@serge-rider please help sir :)

**Comment by serge-rider** [comment]
How do you know it is invalid?

Note that this is estimate count, not real row count value. To see real row count you should enable "Show row count for tables" option in Preferences -> Database -> Metadata.

**Comment by erlangp** [comment]
ow iam sorry i did not know abaout that.. thanks sir, it's working now.. :)
