### ISSUE TITLE
upgrade of Metro Link Open Motif License to > 2012

### ISSUE THREAD

**Issue by grishm** [dbeaver/dbeaver#35906]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Request to upgrade of Metro Link Open Motif License to > 2012

**Describe alternatives you've considered**
N/A

**Additional context**
Our organization uses Dbeaver EE. But we have some users who might be interested in trying out Dbeaver. In order to do so, we are asking them to try the Dbeaver Community Edition. But since we are financial organization, our security team has identified a potential problem with Metro Link Open Motif License. Is it possible to upgrade of Metro Link Open Motif License to >2012 and use that upgraded license in the newer versions of Dbeaver Community Edition.

**Comment by serge-rider** [comment]
It is a part of Eclipse License Agreement.
We'll update it in the next version

**Comment by grishm** [comment]
How will we know that it has been upgraded. Will we get some notifications of this?

**Comment by serge-rider** [comment]
You can check it in the version 24.2.3.
Release is on Monday (see Milestone)
