### ISSUE TITLE
Sometimes the Snowflake connection does is missing the Schema level altogether

### ISSUE THREAD

**Issue by RobertHana** [dbeaver/dbeaver#35919]
### Description

We have a lot of databases in our Snowflake and I am now more often seeing the Database Navigator have incorrect structure, mainly missing the schema list within the Database, and showing Tables, Views, Procedures folder right away.  The work-around is to select the database and do a F5-Refresh, and the structure is restored.  FYI in the not-loaded-correctly state, all references in SQL editors are marked red, as it can't find the referenced database objects.

### DBeaver Version

Community Edition 24.2.2.202410061621

### Operating System

macOS Sonoma 14.6.1 (23G93)

### Database and driver

net.snowflake:snowflake-jdbc:RELEASE [3.14.4]
Snowflake 8.38.3

### Steps to reproduce

Connect to Snowflake containing a lot of databases and schemas, expand a database in the Database Navigator, and see that it displays Tables, Views, and Procedures instead of all the Schemas in that database.

**Comment by E1izabeth** [comment]
Thanks for the bug report. What connection view are you using?
![image](https://github.com/user-attachments/assets/04bcfad5-38e7-4e1f-a01f-543251c7ba73)

**Comment by E1izabeth** [comment]
This issue is stale. If it's still actual for you, please answer the question
