### ISSUE TITLE
SOCKS Proxy doesn't work for multihop ssh servers

### ISSUE THREAD

**Issue by ghuname** [dbeaver/dbeaver#3592]
I have direct connection to the server1.
I have created socks5 proxy and I can access the clickhouse database on server1 by setting conection's:
settings:
host: localhost
port:8123
network:
use socks proxy: on
host: localhost
port:5556

Everything works as expected.

Now I tried to access server2 which is behind server1. So from my computer I have to go over server1 in order to reach server2. By using ~/.ssh/config file I can use ssh uname@server2 to log in to server2 with no password.
I have created socks5 proxy for server2 and port 5557.
The configuration for server2 is the same as server1 except of the socks port which is now 5557 and ProxyCommand in ~/.ssh/config file.

When I try to test the dbeaver connection, I get:
Unexpected driver error occurred while connecting to database
  ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: localhost, port: 8123; Malformed reply from SOCKS server
    ClickHouse exception, code: 1002, host: localhost, port: 8123; Malformed reply from SOCKS server
      Malformed reply from SOCKS server
      Malformed reply from SOCKS server

When I try to access server2:8123 from web browser (over FoxyProxy), I get "Ok." which is expected.
When I try to curl --socks5 localhost:5557 server2_ip:8123, I get "Ok." which is expected.
The same response I get on server1:8123.

Has anybody managed to access database behind intermediate server on this way?
Are there any problems with dbeaver (v5.1) and socks5?
How to debug this problem?

Regards.

**Comment by serge-rider** [comment]
Actual problem is the same as in #3947

**Comment by serge-rider** [comment]
The fix is in EA (https://dbeaver.io/files/ea/)
Sorry for long reply.

**Comment by ghuname** [comment]
Can you please explain what is EA?

**Comment by ghuname** [comment]
I cannot because of https://github.com/dbeaver/dbeaver/issues/4329

**Comment by serge-rider** [comment]
You can just download the most recent version from dbeaver.io. 
#4329 doesn't block anything.

**Comment by ghuname** [comment]
I have just tried in version 5.2.1.201809240911 and it doesn't work.

Maybe to explain a bit further my setup.
In ~/.ssh/config I have a proxy:

Host my_host
     HostName 100.240.150.110 (fake IP)
     ProxyCommand  ssh proxy_user@100.243.150.240  nc  %h %p
     User user

by using ssh my_host I am (paswordless) connected to the my_host.

Now I have executed:
autossh -M 0 -q -f -N -g -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3" my_host -D9871

I have created a new clickhouse connection, populate host as localhost, port as 8123, than I have clicked on "Network settings (SSH, SSL, Proxy, ...)", Tab SOCKS proxy, turned on Use SOKCS Proxy, then for host I have set localhost and for port 9871.

Test connection shows:

Unexpected driver error occurred while connecting to database
  ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, message: Connect to localhost:8123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connection refused: connect, host: localhost, port: 8123; Connect to localhost:8123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connection refused: connect
  ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, message: Connect to localhost:8123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connection refused: connect, host: localhost, port: 8123; Connect to localhost:8123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connection refused: connect
    ClickHouse exception, message: Connect to localhost:8123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connection refused: connect, host: localhost, port: 8123; Connect to localhost:8123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connection refused: connect
    ClickHouse exception, message: Connect to localhost:8123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connection refused: connect, host: localhost, port: 8123; Connect to localhost:8123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connection refused: connect
      Connect to localhost:8123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connection refused: connect
      Connect to localhost:8123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connection refused: connect
        Connection refused: connect
        Connection refused: connect

**Comment by serge-rider** [comment]
Yep. At the moment SOCKS proxy is ignored for localhost connections. This was a kind of workaround for SSH+SOCKS connection but in fact we shoudl handle this differently.
See fix in the next version

**Comment by ghuname** [comment]
I have just upgraded dbeaver to 5.2.2.201810071756 and now socks5 proxy works partially well.
When I execute select, execute query starts, than invalidate connections of [connection name], than set connection defaults, and finally the select is executed properly. Also dbeaver shows a notification: "Datasource was invalidated, live connection count: 2/2"

Because of invalidation of the connection, query is 10 seconds slower than it should be.
Looks like this problem is partially solved.

**Comment by ghuname** [comment]
Can I expect that this issue will be solved soon?
