### ISSUE TITLE
The stored procedure script generated by Dbeaver cannot be executed on its own tool, but can be executed on other tools like Dbrip.

### ISSUE THREAD

**Issue by Harl123** [dbeaver/dbeaver#35940]
### Description

CREATE PROCEDURE `test_procedure`()
BEGIN
    SELECT * FROM my_table;
END;  

The stored procedure script generated by Dbeaver cannot be executed on its own tool, but can be executed on other tools.

### DBeaver Version

24.2.3

### Operating System

windows 11

### Database and driver

mysql 8.4

**Comment by ShadelessFox** [comment]
Hello @Harl123,

How do you execute it? Please provide some footage showing the issue.

**Comment by Harl123** [comment]
> Hello @Harl123,
> 
> How do you execute it? Please provide some footage showing the issue.

1、I have many stored procedures that I want to export to scripts. Here I use AAtest as an example on 172.18.12.52 .
![1](https://github.com/user-attachments/assets/4fa41be4-40bc-4f9e-ad8c-930665cbc628)
2、Export script,using a dump database will generate the same script.
![2](https://github.com/user-attachments/assets/f9c36524-725f-40db-9c63-1222f3753314)
3、Execute the script on another server and report an error
![3](https://github.com/user-attachments/assets/c7e62d7f-9f6c-4909-9ecc-db7d3c04d344)
4、After changing the generated script, it can be executed. However, if the script is exported in batches, it will be a huge workload. After I use Datagrip to export the script, it can be executed normally. Is there something wrong with my operation of exporting the stored procedure script?
![4](https://github.com/user-attachments/assets/8749257b-7f31-4182-a3e8-401d9136f4fa)

**Comment by ShadelessFox** [comment]
Why did you close it?
