### ISSUE TITLE
Add backslash to exported data for mariadb driver, if field contains backslashes

### ISSUE THREAD

**Issue by sabat24** [dbeaver/dbeaver#35945]
### Description

In #10697 you have fixed that behaviour for MySQL driver. However as I can see I have got same problem using MariaDB driver.

`subjects` is a longtext field containing JSON data
![obraz](https://github.com/user-attachments/assets/11c2cb9c-1020-4222-9c21-6eb2c11eeef1)

When I export data to SQL format, I will get following query:

```sql
INSERT INTO table (subjects) VALUES	('["{\"subjectId\":3,\"levelId\":2,\"isOur\":true}"]')
```

which is wrong (I think) because running such query gives me following result

![obraz](https://github.com/user-attachments/assets/fc13973a-7c43-4f60-972c-a59862441575)

So the correct query should contain double backslashes in such case.

### DBeaver Version

Community Edition 24.2.2

### Operating System

Ubuntu 20.04

### Database and driver

MariaDB - MySQL (org.mariadb.jdbc.Driver)

**Comment by E1izabeth** [comment]
Thanks for the bug report.
