### ISSUE TITLE
Can't install GIT extension in DBeaver Community Edition Version 24.2.1 - 24.2.3

### ISSUE THREAD

**Issue by kaisp84** [dbeaver/dbeaver#35951]
### Description

I can't install GIT extension in DBeaver community editions versions 24.2.1 - 24.2.3 from p2 repository https://dbeaver.io/update/git/latest/
I receive the following error message with EA version 24.2.3 for example. Similar error messages occured in other versions too: 

Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver Git support 1.0.128.202410061621 (org.jkiss.dbeaver.git.feature.feature.group 1.0.128.202410061621)
  Missing requirement: Git integration for Eclipse - Core 7.0.0.202409031743-r (org.eclipse.egit.core 7.0.0.202409031743-r) requires 'java.package; org.eclipse.jgit.annotations [7.0.0,7.1.0)' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver Git support 1.0.128.202410061621 (org.jkiss.dbeaver.git.feature.feature.group 1.0.128.202410061621)
    To: org.eclipse.equinox.p2.iu; org.eclipse.egit.core [7.0.0.202409031743-r,7.0.0.202409031743-r]

### DBeaver Version

Community Edition 24.2.3

### Operating System

Windows 11 23H2

### Database and driver

Not applicable

### Steps to reproduce

1. Open DBeaver
2. Go to Help - Install New Software
3. Select for Work With p2 Repositoy with URL https://dbeaver.io/update/git/latest/
4. Select DBeaver Git Support
5. Click Next

**Comment by git-usma-panama** [comment]
Same issue here, I'm running Windows 10 Version 1703 Compilation 15063.1387.

The same steps done, and still can't install the Git Hub Support.

**Comment by MashaKorax** [comment]
Is the issue still reproduced?

**Comment by MashaKorax** [comment]
Should be fixed in release 24.2.3
