### ISSUE TITLE
Export Resultset... as SQL inserts is missing

### ISSUE THREAD

**Issue by chrissmithphd** [dbeaver/dbeaver#3595]
Hi, I've read online that I can export the resultset of a query as a set of SQL inserts, but my version of dbeaver doesn't seem to have that option. What am I missing? I'm on version 4.3.3.1.

![image](https://user-images.githubusercontent.com/7573265/41127787-a47c2422-6a71-11e8-943e-826f5c6de033.png)

thanks for your help!

chris

**Comment by serge-rider** [comment]
Try to upgrade to the most recent (5.1). This issue was fixed a few versions ago.

**Comment by chrissmithphd** [comment]
Thanks for the reply! I upgraded, and these are my options now...

![image](https://user-images.githubusercontent.com/7573265/41165642-cd2b3812-6b03-11e8-86d6-63416375f700.png)

The generate SQL option doesn't generate for all the results from the query, only for what is highlighted in the results grid.

chris

**Comment by serge-rider** [comment]
Export to SQL INSERTS supported only for tables or custom SQL which involves only one table.

**Comment by p91paul** [comment]
What about adding support for export as insert, asking the user for the destination table name when it isn't obvious? it's a corner case, but it could be useful!

**Comment by chrissmithphd** [comment]
@serge-rider my custom sql is one table, pretty simple...

```sql
select *  
 from a.e  
where e.t > TIMESTAMP '2018-06-07 20:00'
 and e.t < TIMESTAMP '2018-06-07 22:00'
limit 1000
```

I'd do it on the whole table eventually, but I gated it to test with a smaller size.

chris

**Comment by serge-rider** [comment]
I'll add SQL INSERT format support for queries which operate with single table.
Mapping custom joined queries to a single target table could be a separate feature. You could create a FR.
