### ISSUE TITLE
Client Side Scripting link missing from wiki page

### ISSUE THREAD

**Issue by TB-HunBoka** [dbeaver/dbeaver#35964]
### Description

The Client Side Scripting page is not linked to the related general user guide at the dbeaver docs wiki page.

![image](https://github.com/user-attachments/assets/abb3614e-9a3f-47be-9fee-4c8c49cfab0c)

I think the Client Side Commands bullet point should be linked to:
https://dbeaver.com/docs/dbeaver/Client-Side-Scripting/

### DBeaver Version

wiki page

**Comment by E1izabeth** [comment]
Thank you for your report.

**Comment by ShadelessFox** [comment]
Thanks for the report
