### ISSUE TITLE
Export Window doesn't move forward on ENTER Key

### ISSUE THREAD

**Issue by shrivatsahosabettu** [dbeaver/dbeaver#35968]
### Description

When Export Window launched it looks like the Next> Button is highlighted, on Pressing ENTER Key it doesn't move forward to next screen after _Format settings_. 
![image](https://github.com/user-attachments/assets/add24c73-9a8b-4bb7-9b3b-351fe171d2f0)

It just hangs and keep expand & collapse General section of the _Format settings_
![image](https://github.com/user-attachments/assets/696a47f5-207a-451c-b2d4-e0b938726f23)

### DBeaver Version

Version 24.2.3.202410132322

### Operating System

Windows 11

### Database and driver

DB2 ZOS

### Steps to reproduce

Try launch export window and keep pressing ENTER key in the keyboard. It just hangs in Format settings.

**Comment by E1izabeth** [comment]
Thanks for the bug report
