### ISSUE TITLE
Find Replace on enter keeps adding the occurrence

### ISSUE THREAD

**Issue by shrivatsahosabettu** [dbeaver/dbeaver#35961]
### Description

In the find and replace window if you enter the IN Predicate value and replace with the existing and add more predicate value on enter, keeps adding each the ENTER button is pressed.

![image](https://github.com/user-attachments/assets/c3d23a04-3b34-4388-803a-b147cfb61c5b)

### DBeaver Version

Version 24.2.3.202410132322

### Operating System

Windows 11

### Database and driver

DB2 ZOS

### Steps to reproduce

1. Any query with the IN predicate and in the find field enter the existing value and replace window along with the existing value add some more values. On ENTER key how many times you enter that many times the value will be added along with the original value.

**Comment by E1izabeth** [comment]
The described case is expected behavior. If you want to replace it only once, please press Enter only once.
