### ISSUE TITLE
Ctrl + Enter command is bugged after first query

### ISSUE THREAD

**Issue by iwarneto** [dbeaver/dbeaver#35973]
### Description

After using the Ctrl + Enter shortcut in a query, after the result is displayed, if I try to use the shortcut again in another query it just creates a line break. What's stranger is that if I hit 'Refresh' button in the lower portion of the screen, the query that will run is the second query which created the line break and not the first one that is appearing in the result window.

### DBeaver Version

Community Edition 24.2.2

### Operating System

Windows 11

### Database and driver

1. Database name and version: PostgreSQL 15.6
2. Default PostgreSQL JDBC Driver

### Steps to reproduce

1. Create new sql script
2. Insert any query
3. Use Ctrl + Enter shortcut to run the query
4. Use Ctrl + Enter to run another query

**Expected:** Run the second query and display in DBeaver interface below.
**Actual:** Breaks line in script editor without updating the query results of the new query.

**Comment by serge-rider** [comment]
Could you check log file for any errors? 
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by tommy-ww** [comment]
I have similar issue, ctrl + enter does not run query anymore, it breaks the line and opens some other menus.
Nothing in logs

Macbook Pro
macOS Sequoia Version 15.1
DBeaver Version 24.2.4.202411031831

Replicate:
Try to run any query with Ctrl + Enter

https://github.com/user-attachments/assets/bee71754-6d42-4ddf-be1a-4ed070a198de

**Comment by brunobarros2093** [comment]
Same problem here, using Sequoia 15.1. 
DBeaver	version 24.1.3.202407211303

**Comment by brunobarros2093** [comment]
To fix it one can change de shortcut that executes a query

**Comment by HocKu7** [comment]
@iwarneto Can you please provide footage showing your issue in Windows OS? Thank you.

**Comment by arhayka** [comment]
@brunobarros2093 @tommy-ww 
You can use the **Cmd+Enter** shortcut. It was specifically added for macOS in version 24.2.2.

**Comment by tommy-ww** [comment]
> @brunobarros2093 @tommy-ww You can use the **Cmd+Enter** shortcut. It was specifically added for macOS in version 24.2.2.

Was there a reason that `Ctrl + Enter` was removed for macOS?
Been using it for years and just curious why it was removed.

**Comment by arhayka** [comment]
> Was there a reason that `Ctrl + Enter` was removed for macOS? Been using it for years and just curious why it was removed.

It was removed due to a conflict with a new system shortcut in macOS Sequoia, which could lead to insecure behavior.
To be honest, I also found the old shortcut much more convenient.
