### ISSUE TITLE
Message Workspace is closed and database navigator empty

### ISSUE THREAD

**Issue by NicolasFabre81** [dbeaver/dbeaver#35978]
### Description

When I close dbeaver I get the error message "Workspace is closed."
Moreoever , I just lost all my connections in the database navigator ! Maybe not related but I did not have my computer crash, just a "hard reboot" having dbeaver opened maybe...

### DBeaver Version

community 24.2.2

### Operating System

windows

**Comment by E1izabeth** [comment]
Could you send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.
Also you can collect them to archive automatically with `Help->Collect Diagnostic Info`
![image](https://github.com/user-attachments/assets/51c7ca2e-6be2-489e-b495-028b9aa0e386)

Thank you.

**Comment by QUICKADMIN-PRO** [comment]
I have teh same issue
[dbeaver-diagnostic-info-1729411984585.zip](https://github.com/user-attachments/files/17449545/dbeaver-diagnostic-info-1729411984585.zip)

**Comment by E1izabeth** [comment]
Thanks for providing log files.

**Comment by Destrolaric** [comment]
'C:\Users\Jose Siso Gaming\AppData\Roaming\DBeaverData\workspace6\.metadata\.plugins\org.eclipse.core.resources\.root\'.
Hi could you try renaming the following folder and see if works for you.

**Comment by QUICKADMIN-PRO** [comment]
Hi i make it work rename some file i see in internet but a loss all my
connection y have to do it again but right now it works, thanks

**Comment by BenceBodnar111184** [comment]
I'm having the same issue, I lost all my connections, and the option to create new one is greyed out. The workspace is locked. Any tips to fix the issue?
[dbeaver-diagnostic-info-1731164304218.zip](https://github.com/user-attachments/files/17688352/dbeaver-diagnostic-info-1731164304218.zip)

**Comment by E1izabeth** [comment]
Do you have any projects here?
![image](https://github.com/user-attachments/assets/8a1d48a7-6c78-43f9-be4b-9735afbb7179)

Was workspace switched? Do you have something in Recent workspaces?
Press `File->Switch Workspace->Other` 
![image](https://github.com/user-attachments/assets/e1c338bb-1b1a-4ba9-ac0b-fd398bb211d1)
And expand Recent Workspaces
![image](https://github.com/user-attachments/assets/7e27af1b-ca6a-44e1-acce-aeae04753f03)

**Comment by BenceBodnar111184** [comment]
No, I do not have any projects, 
![image](https://github.com/user-attachments/assets/abd6534c-abb9-4b1c-9935-a1ae37a8cf69)

Also I do not have any previous Workspaces, but if I try to click launch Im getting this error:

![image](https://github.com/user-attachments/assets/c1b3a115-e754-47d8-834e-fb0bbc1b40f6)

**Comment by E1izabeth** [comment]
OK. I see. Something happened with the working directory (workspace) and files seems to become corrupted somehow. It might happen due to a forced or unexpected application termination. Have you encountered something like that?

**Comment by BenceBodnar111184** [comment]
Interesting, that could happened that I forcedly clossed the application. Is there any fix?

**Comment by E1izabeth** [comment]
Could you try manual workspace reset? https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings#manual-reset

If this won't help, probably, you can create new workspace, find your workspace folder and try copying some files to the new workspace. For example, [data-sources.json ](https://github.com/dbeaver/dbeaver/wiki/Admin-Manage-Connections)

**Comment by BenceBodnar111184** [comment]
Thank you, after deleting every file in the .plugins and reseting the app it works again!

**Comment by E1izabeth** [comment]
@NicolasFabre81 is this issue still actual for you? Does the proposed workaround help?

**Comment by NicolasFabre81** [comment]
> @NicolasFabre81 is this issue still actual for you? Does the proposed workaround help?

Thanks, I solved the problem a few days ago with re-install + restore config files

**Comment by diconart** [comment]
> Thank you, after deleting every file in the .plugins and reseting the app it works again!
... \AppData\Roaming\DBeaverData\workspace6\\.metadata\\.plugins
is actual for 25.04.2025

**Comment by jnagharsh** [comment]
I had the same issue, I selected reset settings under help, and checked the Workspace Configuration option and selected Apply and Restart. It worked and all my connection were recovered as well.

**Comment by amut7933** [comment]
Resetting workspace settings fixed the issue for me.
