### ISSUE TITLE
Download driver files dialogue appears every time when connect to MariaDB

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#35981]
### Description

![dbeaver_9b0ToLfdVU](https://github.com/user-attachments/assets/00c8da22-a08e-4e08-ae0f-dcf30fcbe91d)

### DBeaver Version

DBeaver 24.2.3

### Operating System

windows 10

**Comment by serge-rider** [comment]
It happens when gnu.org is not accessible.

**Comment by Matvey16** [comment]
Duplicate https://github.com/dbeaver/dbeaver/issues/35466

**Comment by serge-rider** [comment]
It should be fixed in https://github.com/dbeaver/dbeaver/issues/35466

**Comment by MashaKorax** [comment]
verified
