### ISSUE TITLE
[postgres] Syntax error in role settings

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#35989]
### Description

DDL of settings configured for particular role (shown in Source code in Role properties) is not single quoted, resulting in syntax error

See screenshot.
![image](https://github.com/user-attachments/assets/2acb1f40-69c3-49f1-8814-8f81e2723f10)

Proper syntax is:
```
ALTER ROLE app_settlement SET statement_timeout='0s';
```

BTW I found too many empty rows between role and permissions

### DBeaver Version

CE 24.2.2

### Operating System

Fedora 40

### Database and driver

Database: Postgres 16.3
Driver Postgres

### Steps to reproduce

1. Create role
2. Set role settings ie `ALTER ROLE your_role_name SET statement_timeout='5s';
3. refresh role properties tab
4. look at source code

**Comment by E1izabeth** [comment]
Thanks for the bug report.
