### ISSUE TITLE
triggers not shown in Database Navigator

### ISSUE THREAD

**Issue by BruceJL** [dbeaver/dbeaver#35986]
### Description

I think that I'm seeing the same issue in the PostgreSQL driver as seen in [18764](https://github.com/dbeaver/dbeaver/issues/18760).

### DBeaver Version

Community 24.2.2.202410061621

### Operating System

Debian Testing

### Database and driver

Database Name and Version: PostgreSQL 16.4 (Debian 16.4-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit, Driver Name and Version: PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

* Connect to the server with the [linked database](https://github.com/BruceJL/mrg/blob/master/pods/postgresql/00_mrg.sql)
* Open the database browser
* Select the Event Triggers item for the database

### Additional context

```
SELECT  event_object_table AS table_name ,trigger_name         
FROM information_schema.triggers
```
returns the correct results.
![Screenshot from 2024-10-14 16-51-35](https://github.com/user-attachments/assets/c660ca22-5af0-4cbf-b570-cfab72045ebe)

However, when selecting triggers from the menu tree, no triggers are visible.
![Screenshot from 2024-10-14 16-49-01](https://github.com/user-attachments/assets/e6ab9d08-ba84-4042-9f06-b0cee7872c4e)

**Comment by LonwoLonwo** [comment]
Hello @BruceJL 

You need to check your tables in the navigator tree. Each table has a Trigger section, where ordinary triggers are found.

I can see [Event Triggers](https://www.postgresql.org/docs/current/sql-createeventtrigger.html) on your screen. However, I do not see event triggers in the linked database.

![image](https://github.com/user-attachments/assets/4098db82-9aae-457d-a0bd-8eb70fc0414d)

**Comment by BruceJL** [comment]
@LonwoLonwo My apologies for the report. I'll be more careful in the future.
