### ISSUE TITLE
Timezone and MySQL Connector

### ISSUE THREAD

**Issue by qantuum** [dbeaver/dbeaver#3599]
Dear dBeaver team.

Thanks a bunch for allowing us users to get a free solution for databse management.
Nevertheless; this issue about timezone has infuriated me and I have done many research operations, to find the same issue was declared in 2016 (!) : 
--https://github.com/dbeaver/dbeaver/issues/1088

So here are the problems : 
(1)your **'submit issue guidelines'** located at https://github.com/dbeaver/dbeaver/blob/devel/CONTRIBUTING.md is an empty file
(2)when first using a mySQL database; dBeaver automatically downloads a JDBC version 8.xx that does not support 'CEST' as a correct timeZone; which results in an error !
(3)No field provided to change this 'CEST' to another value in the JDBC driver config menu
(4)Having no skill in Java, I can not find by myself the place where the error is located.
(5)I do not know why is so that the JDBC and dBeaver cannot accept 'CEST' as the correct value. If it comes from the JDBC, that's bad Java coding. If it comes from dBeaver... Maybe it is time for you to adapt to the most recent connection drivers...
(6)I eventually got my problem solved by downgrading my JDBC connector driver manually; as stated in issue 1088.

I want to say it's a pity that this kind of errors keep popping in numerous apps, since the final user does not always have the right skill to solve the problem.

Best of luck in the future;
best regards

**Comment by serge-rider** [comment]
You don't need to know Java or any other programming language.

Anyhow, there is no such standard timezone `CEST`, it is just `CET`.
So you can just set driver property `serverTimezone` to `CET`.

I understand your problem and I'd wish to make this simpler. But Oracle keep changing MySQL servers/clients so they are not fully backward compatible (e.g. you can't connect to MySQL 8.x with old drivers - that's why we upgraded it to 8.0 driver by default).

**Comment by qantuum** [comment]
Hey there;

thanks for answering !
Actually I already saw this 'set driver property' solution, but did not find a way how to set it.

At what moment do I have this possibility ? Is it when I choose the driver version for download ?
Or do I have to enter one of the submenus (add file, details,...). Eventually can you show me with a screenshot ?
Thanks.

**Comment by serge-rider** [comment]
This is one of the oldest features in DBeaver:

![image](https://user-images.githubusercontent.com/6398845/41246715-94ca45c2-6db4-11e8-9986-874a27ed576b.png)

**Comment by dginovker** [comment]
Sorry to necrobump, but `Driver properties` is no longer under Connection settings. How do you fix the issue now?

**Comment by tati-kru** [comment]
If you open Connection Settings you can find different tabs at the top of the form: Main, Driver Properties, SSH, Proxy, SSL. So, you need a Driver properties tab.

![image](https://user-images.githubusercontent.com/30336552/77053674-c14e9e80-69df-11ea-8e0f-786c7bea1bc2.png)
