### ISSUE TITLE
after exporting to .csv, dbeaver hangs and chokes CPU

### ISSUE THREAD

**Issue by knwpsk** [dbeaver/dbeaver#3600]
Create and save a query.
Right-click > Execute > Export from query.
Query runs in background and creates file, then dbeaver shows a msgbox "Data Transfer Complete"

If I close that msgbox immediately, no problem.

If I'm not around and don't close the msgbox immediately, dbeaver gets into some state where it chews up about 80% of my cpu, and when I try to interact with the app, it's nonresponsive.  Can't close the msgbox or click anything else.  Have to taskkill and restart the app.

This started before v5.1.0, but it's still happening in v5.1.0.

Apologies if this isn't proper convention for a bug report - I tried to find the instructions but can't.  Please show me or help me correct this as needed.

**Comment by serge-rider** [comment]
What is your OS?

**Comment by knwpsk** [comment]
Sorry for the delay Serge, I didn't get notified when you commented.
My OS is Windows 10 64-bit.

**Comment by knwpsk** [comment]
![dbeaver hangs after data transfer complete msgbox](https://user-images.githubusercontent.com/30087322/41291134-dcadf132-6e1c-11e8-9d39-bddf1e89e779.png)
![dbeaver 81pct cpu while hung on msgbox](https://user-images.githubusercontent.com/30087322/41291136-dcd9c5c8-6e1c-11e8-9e8e-7dfe3d54fadd.png)
Serge, I thought about this more.  
I didn't mention above clearly - this happens overnight.  I.e. I ran a query to export, and left for the day.  Next morning I come in and the app is frozen up.  
Second, and likely very relevant -- there are overnight jobs that update the db, move/rename tables, etc.  It's entirely possible that my session gets corrupted because of this, or something of that nature.  
Maybe that's why you can't reproduce it (and it's not worth reproducing).  
Maybe what would be nice is to just allow me to "opt out" of the modal messagebox?  I'll make that a separate request.

**Comment by knwpsk** [comment]
Serge, I thought about this more.
I didn't mention above clearly - this happens overnight. I.e. I ran a query to export, and left for the day. Next morning I come in and the app is frozen up.
Second, and likely very relevant -- there are overnight jobs that update the db, move/rename tables, etc. It's entirely possible that my session gets corrupted because of this, or something of that nature.
Maybe that's why you can't reproduce it (and it's not worth reproducing).
Maybe what would be nice is to just allow me to "opt out" of the modal messagebox? I'll make that a separate request.
![dbeaver hangs after data transfer complete msgbox_obscured](https://user-images.githubusercontent.com/30087322/41291279-49899036-6e1d-11e8-874e-6146559e3398.png)
![dbeaver 81pct cpu while hung on msgbox](https://user-images.githubusercontent.com/30087322/41291293-50fc4c28-6e1d-11e8-8bd9-ab4b3fbe31fa.png)

**Comment by serge-rider** [comment]
Well, I've added additional export option to suppress final message dialog (in your ticket #3618). Hope it will help.

Regarding CPU usage after long idle period. Sometimes similar issue may happen on some Linux boxes because of bug in SWT + GTK support. Try to run
```sh
export SWT_GTK3=0
```
before running DBeaver.

**Comment by serge-rider** [comment]
BTW, do you have keep-alive configured for you connection? Do you use SSH tunnel?

**Comment by knwpsk** [comment]
I haven't intentionally set those settings (and I can't find them).  What are the defaults - and where would I set them?

**Comment by serge-rider** [comment]
They are in connection properties dialog. If you didn't set them then they are disabled by default.

I'm trying to figure out what background processes in DBeaver may lead to such issue. SSH and keep-alive are just most obvious. I'll try to dig a bit more..

**Comment by uslss** [comment]
cannot reproduce on 6.0.2
