### ISSUE TITLE
v.24.2.3 doesn't respect an "Active Catalog/schema" chosen in the toolbar.

### ISSUE THREAD

**Issue by hovercraft-github** [dbeaver/dbeaver#36005]
### Description

v24.2.3  Community edition doesn't respect an "Active Catalog/schema" chosen in the toolbar.

### DBeaver Version

Community Edition 24.2.3

### Operating System

KUbuntu 24.04 LTS

### Database and driver

1. Database:  PostgreSQL 12.12 (Greenplum Database 7.1.0)
2. Driver: PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

1. Create at least two databases with several different schemas in each of them with different set of tables.
2. Create some project.
3. In the DBeaver connection settings specify Database: first_database.
4. Create some sql script, then via toolbar choose the second_database and schema public.
5. Try select queries from some table in the public or another schema using schema_name.table_name notation.
Expected behavior: table should be accessible.
Real behavior: in fact you are still connected to the first_database database and can not see tables from the second_database.
Also the project window in the "Connections" doesn't track correctly of what schema, table and other objects pertain to which database.

### Additional context

Version 24.2.2 works correctly

**Comment by E1izabeth** [comment]
Thanks for the issue.
Probably, it's connected to #35507

**Comment by E1izabeth** [comment]
@hovercraft-github 
For now, I can't reproduce the issue. 
I have 2 schemas - `dvdrental` and `e1izabethdb`. And 2 tables - `dvdrental.public.os` and `e1izabethdb.public.file`.
Here is my connection configuration - I have `dvdrental` in the Database field
![image](https://github.com/user-attachments/assets/e470aba9-ff0a-4d71-8c7c-8d8ab58286f1)
![image](https://github.com/user-attachments/assets/8c4c09a9-7b9a-4d8b-bfbd-36a89ca495a2)
Then I open a script and choose `e1izabethdb` as an active database and `public` as an active schema. Execution of the following script gives expected result:
```
select * from "public"."file"; -- executed correctly, table "file" is in "e1izabethdb" database
select * from dvdrental."public"."file"; -- expectedly fails

select * from "public"."os"; -- fails because there is no such table in the active database
select * from dvdrental."public"."os"; -- executed correctly as "os" table is in `dvdrental` database
```

Am I missing some step?

**Comment by hovercraft-github** [comment]
After time & some minor OS updates and reboots I not able to reproduce it too.
Let's consider it was some mysterious local glitch (strange it manifested itself with specific version only so).
Sorry for the  false report, and thank you for your hard work!

**Comment by E1izabeth** [comment]
OK. Thank you for reply.
If you encounter this issue again, please let me know
