### ISSUE TITLE
Autocomplete shows useless sql keywords instead of a list of columns for derived table

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#36018]
### Description

Use code:
```
select s.
from (
    select r.inventory_id, r.customer_id
    from rental as r
) as s
```
- press Ctrl + Space after "s."

Expected: a list of columns of "s"-alias is shown
Actual: a list of sql keywords which are inapplicable in this part of the query

By the way, if you add * and press Ctrl + Space, autocomplete can show the available columns correctly.
It means, there is no problem to obtain the list of columns for this query.

https://github.com/user-attachments/assets/4456b065-edbd-4bbc-9bc1-b4c9e88bfe0e

### DBeaver Version

Enterprise Edition 24.2.4-202410172322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by E1izabeth** [comment]
Thanks for the bug report.
