### ISSUE TITLE
How do I remove the Debug toolbar?

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#3601]
I can't find how to remove the debug toolbar.  I never use it

![default](https://user-images.githubusercontent.com/16996529/41188140-b9f196ac-6bfc-11e8-8616-6484384bc370.png)

**Comment by serge-rider** [comment]
You can just remove it. Main menu->Window->Customize Perspective:
![image](https://user-images.githubusercontent.com/6398845/41189422-5846a684-6bd6-11e8-9bbd-2666f7f82720.png)

Note: this toolbar shouldn't be visible by default. Perhaps you did try to debug at least once.

**Comment by offstate** [comment]
Thank you. I would never have found it ))
