### ISSUE TITLE
TABLE: Data length and Auto increment 

### ISSUE THREAD

**Issue by 92daxia** [dbeaver/dbeaver#36025]
### Description

After truncating the table, the data length and auto increment are not updated

### DBeaver Version

Version 24.2.3.202410201725

### Operating System

macOS 15.0.1

**Comment by E1izabeth** [comment]
Hi, @92daxia 
Have you tried to press Refresh button?

**Comment by E1izabeth** [comment]
Are you in the transaction? In case if no, your main toolbar should look like this
![image](https://github.com/user-attachments/assets/c65ac00c-e476-41c7-ab50-11ef4c70f3b9)

**Comment by 92daxia** [comment]
> Hi, @92daxia Have you tried to press Refresh button?

I clicked the button, but it doesn't work.

**Comment by 92daxia** [comment]
> Are you in the transaction? In case if no, your main toolbar should look like this ![image](https://private-user-images.githubusercontent.com/28875055/378776120-c65ac00c-e476-41c7-ab50-11ef4c70f3b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDEwODEsIm5iZiI6MTcyOTc0MDc4MSwicGF0aCI6Ii8yODg3NTA1NS8zNzg3NzYxMjAtYzY1YWMwMGMtZTQ3Ni00MWM3LWFiNTAtMTFlZjRjNzBmM2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDAzMzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MjVkYTM4OGJkYWMwMzk3YzNkNmE4YmVhYTkxYjU3MzcxMWVlOTg3OWJlOWU0OTkwN2U2MTIyZWIwODJmYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7VYeYiGYekSx8z5jQU9JJBGfmiGObCfUmZCc4y8MsBs)

yes,
<img width="552" alt="image" src="https://github.com/user-attachments/assets/5e14a492-33da-4ead-b887-cb4396834159">

**Comment by Destrolaric** [comment]
Hi, could you provide the steps to reproduce? And, if possible, video with the issue

**Comment by E1izabeth** [comment]
We can't reproduce the issue. And it's been a while since no update here. If the issue is still actual please let me know and provide additional information.
