### ISSUE TITLE
Content asist in 5.1.0 returns more than I want

### ISSUE THREAD

**Issue by amivanovano** [dbeaver/dbeaver#3602]
DBeaver 5.1.0
Windows 7
Informix Dynamic Server 12.10.FC7
IBM Informix JDBC driver for IBM Informix Dynamic Server 4.10.JC10

I hoped to see the list of table columns
![image](https://user-images.githubusercontent.com/28041955/41189849-dd5b20a6-6bdc-11e8-9cc0-7f28d9e1a54f.png)
 **DBeaver 5.0.6**

but received also the long list of stored procedures ( long list - long time ! )

![image](https://user-images.githubusercontent.com/28041955/41189886-4e7d05c4-6bdd-11e8-8c0f-01b955f71831.png)
**DBeaver 5.1.0**

**Comment by serge-rider** [comment]
It is the new feature asked by many users. However I agree, most people don't need these procedures, especially if database has many system/not-relevant procedures.
So I'll make this feature configurable (and disabled by default):
![image](https://user-images.githubusercontent.com/6398845/41195273-ad5991d4-6c32-11e8-8237-fa833161a648.png)
