### ISSUE TITLE
Unable to download Ingres driver

### ISSUE THREAD

**Issue by Spritekin** [dbeaver/dbeaver#36021]
### Description

Opened the driver manager, selected Ingres driver, clicked in the Libraries tab then the Download/Update button. 

The download dialog always says "Ingres driver files are missing". And in the list of missing files it displays nothing. Clicking in the Download button throws no error and closed the dialog but the driver is not downloaded and is still marked as unavailable or N/A. 
<img width="691" alt="Screenshot 2024-10-22 at 10 15 10 AM" src="https://github.com/user-attachments/assets/23cc22bb-4cc0-4425-ba43-fe82bd5cc5c8">

<img width="702" alt="Screenshot 2024-10-22 at 10 14 53 AM" src="https://github.com/user-attachments/assets/c74b9930-dbb2-430d-923e-1c0ae380ccb7">

Both images above are in MacOS. In windows it is the same behaviour except it displays a red "unavailable" miniicon in the drivers page:
<img width="616" alt="Screenshot 2024-10-22 at 9 47 32 AM" src="https://github.com/user-attachments/assets/74b655d7-e4be-4587-ac27-db3d4b6ab0b3">

Trying to download again still shows the "Ingres driver files are missing" message. Trying to use an ingres connection doesn't work because the driver is not available and takes me to the download dialog with the "Ingres driver files are missing" message.

Tested in Windows and MacOS, the problem appears both.

### DBeaver Version

24.2.3.202410201725

### Operating System

MacOS and Windows

### Database and driver

Ingres, any version, I'm not even trying to connect, just download the driver.

### Steps to reproduce

1. Make sure you don't have the Ingres driver installed.
2. Open the driver manager.
3. Select the Ingres driver in the list.
4. Double click or click the "Edit..." button.
5. In the Edit driver Ingres dialog, select the "Libraries" tab.
6. Click the "Download/Update" button.
7. You can see the "Driver setting" dialog and the "Ingres driver files are missing". No files are displayed in the driver file list. Same problem appears in Windows or MacOS.

<img width="691" alt="Screenshot 2024-10-22 at 10 15 10 AM" src="https://github.com/user-attachments/assets/ca07f270-31b3-4e09-8f62-e814c50e052c">

<img width="517" alt="Screenshot 2024-10-22 at 10 25 02 AM" src="https://github.com/user-attachments/assets/69209051-4e3d-49b4-8715-39a9a00c2a8a">

9. Clicking the "Download" button closes the dialog. Trying the "Force download / overwrite" has no effect, the driver is still missing and marked as Not available, unavailable or N/A depending on where you are in the software.
10. Looking at the logs it says it was unable to find the driver at all.

<img width="1031" alt="Screenshot 2024-10-22 at 10 30 26 AM" src="https://github.com/user-attachments/assets/55412ffb-0dd2-47e6-a820-7ae95b151d9b">

### Additional context

I was told to disable the WIndows trust store in the windows version but there was no change in behaviour.

**Comment by E1izabeth** [comment]
Thanks for the bug report. I reproduced the issue
As a temporarily workaround, you can manually download the jar file here https://mvnrepository.com/artifact/com.ingres.jdbc/iijdbc/10.2-4.1.10, add it in the Driver manager to the Libraries and delete the automatically proposed blue item which can't be downloaded

![image](https://github.com/user-attachments/assets/53f33117-91e4-436f-b7ba-b87ae7a3627b)

**Comment by Spritekin** [comment]
@E1izabeth 
Hi, yes I tried that already but if you click in the Jar link you get a 403. Maybe its the cause of the problem.
<img width="698" alt="Screenshot 2024-10-23 at 2 42 18 PM" src="https://github.com/user-attachments/assets/fb072039-f614-44fd-96c1-d6a3a09e962a">

**Comment by E1izabeth** [comment]
Oh, I see. Please use the previous driver version by this link https://mvnrepository.com/artifact/com.ingres.jdbc/iijdbc/10.0-4.0.6
