### ISSUE TITLE
Bring back default Find&Replace dialog

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#36032]
**Is your feature request related to a problem? Please describe.**
The new dialog breaks RCP UI standards, is hard to use (different and too small a  font, incomprehensible icons, lacking functionality).

**Describe the solution you'd like**
Bring back the fully working find&replace dialog, or at least allow users to switch to it it via a setting in preferences.

**Describe alternatives you've considered**
Currently I rather do search and replace via shortcuts since the dialog is almost unusable. But that's not always a convenient work-around.

**Comment by E1izabeth** [comment]
This new dialog comes from Eclipse. It's not a DBeaver dialog. The dialog was replaced in Eclipse 2024-09 and after we upgraded Eclipse to this version, it came to DBeaver.
Here is a way how to return back old dialog https://stackoverflow.com/questions/79012836/eclipse-2024-09-is-there-a-way-to-get-the-old-find-replace-window-back/79013331#79013331

**Comment by 2019-05-10** [comment]
Oh dear! 
Thanks for the link, that way I'm prepared when upgrading Eclipse.

**Comment by 2019-05-10** [comment]
.

**Comment by 2019-05-10** [comment]
Oh dear!
Thanks for the link, that way I'm prepared when upgrading Eclipse.
Edit: seems I cannot close this.
