### ISSUE TITLE
SQLite: impossible to drop a column when a column without data type exists

### ISSUE THREAD

**Issue by kseniaguzeeva** [dbeaver/dbeaver#36036]
### Description

SQLite: impossible to drop a column when a column without data type exists. E.g.

`CREATE TABLE testnull (
	id INTEGER,
	"null" null,
	"notnull" INTEGER
);`

### DBeaver Version

DBeaver 24.2.4 ea

### Operating System

Win11

### Database and driver

SQLite

### Steps to reproduce

1. Create a table with 3 columns, one of the columns doesn't have a data type
2. Delete a column except the column without a data type
ER: the column is deleted
AR: the deletion failed. The reason is in wrong syntax (n/a in the script):

```
CREATE TEMPORARY TABLE temp AS
SELECT
  Column1,
  Column3
FROM test;

DROP TABLE test;

CREATE TABLE test (
	Column1 INTEGER NOT NULL,
	Column3 **N/A**
);

INSERT INTO test
 (Column1,
  Column3)
SELECT
  Column1,
  Column3
FROM temp;

DROP TABLE temp;
```

### Additional context

https://github.com/user-attachments/assets/e7f8d7ce-1a1e-4e20-95c7-86062d465acf

**Comment by eusebe-cda** [comment]
To fix this issue, I propose to add the ANY type in dbeaver (as in the documentation concerning STRICT tables: https://www.sqlite.org/stricttables.html) and to apply this type for existing columns without a known type.

What do you think? If it fits, I can work on it!

**Comment by kseniaguzeeva** [comment]
verified
