### ISSUE TITLE
[New autocomplete] automatically pops up a join hint when a join is already typed

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#36044]
### Description

https://github.com/user-attachments/assets/f89b8299-69c9-47eb-92ff-b15fe49db514

### DBeaver Version

DBeaver 24.2.4

### Operating System

windows 10

**Comment by E1izabeth** [comment]
Also applying schema proposal after database and dot should not replace already written part of fully qualified name
![image](https://github.com/user-attachments/assets/65a2a642-5b81-4852-9ad0-2f01d3b838ed)
