### ISSUE TITLE
Blank area appeared in field hosting script window and cannot be removed.

### ISSUE THREAD

**Issue by 53904** [dbeaver/dbeaver#36063]
### Description

When there were multiple tables open in single view, db connection got lost and this gray blank area appeared. It doesnt disappear although I closed all tabs, reopened. DBeaver update did not help as well.
![dbeaver](https://github.com/user-attachments/assets/cc53e103-99fe-46d9-b95a-f8bfb6682128)

### DBeaver Version

Community Edition 24.2.3

### Operating System

Windows 10 Enterprise 22H2 19045.4894

### Steps to reproduce

1. Have 3-4 tables and scripts open in single view
2. Close dbeaver or disconnect from db
3. Reopen dbeaver
4. Don't enter password (that causes tables close automatically)
5. Open a new script

**Comment by ShadelessFox** [comment]
Your perspective is messed up. Use "Window -> Reset Perspective" to reset it.

**Comment by 53904** [comment]
It did not work unfortunately.
![image](https://github.com/user-attachments/assets/cec56c42-9dd0-4acb-a95f-dbce7e88d239)

**Comment by ShadelessFox** [comment]
Interesting. Try dragging the editor to that area:

![image](https://github.com/user-attachments/assets/1e37b2ab-2601-4811-b8f2-f78d60be4052)

**Comment by 53904** [comment]
![dbeaver2](https://github.com/user-attachments/assets/bdc68490-f35d-4059-9d34-772bbdb5c747)

**Comment by ShadelessFox** [comment]
Try resetting UI settings according to this article: https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings#reset-settings

**Comment by 53904** [comment]
Worked for me. Thank you @ShadelessFox 
> You can perform a reset using the Help ⇒ Reset Settings... action.
