### ISSUE TITLE
DDL Extract - Oracle PKG returns bad header.

### ISSUE THREAD

**Issue by Pduke44** [dbeaver/dbeaver#36075]
### Description

Extracting an Oracle PKG with 3 parameters removed parameter 2.
**Should be**
```sql                              
PROCEDURE VALIDATE_CODE(O_CURSOR OUT SYS_REFCURSOR,
                        P_CID IN TRANSACTIONHISTORY_DATA.PPATTMID % TYPE,
                        P_AUTH_CODE IN TRANSACTIONHISTORY_DATA.PBINTREFNUM % TYPE)     
```
**Extracts**
```sql
PROCEDURE VALIDATE_CODE(O_CURSOR OUT SYS_REFCURSOR,

                        P_AUTH_CODE IN TRANSACTIONHISTORY_DATA.PBINTREFNUM % TYPE)
```

### DBeaver Version

Version 24.2.1.202409221725

### Operating System

Window 11 Pro Version 22H2

### Database and driver

oracle.jdbc.OracleDriver

**Comment by ShadelessFox** [comment]
Hello @Pduke44,

Can you please provide a script that creates such a package? What database and driver version are you using?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
