### ISSUE TITLE
Sort (Order by) error if the collation not default

### ISSUE THREAD

**Issue by KJoe69** [dbeaver/dbeaver#36079]
### Description

I am create an InnoDB table with varchar(10) column in local mysql database with utf8mb4_hungarian_ci collation. Some letters correct order example á-b-é-z. 
But if I using "Order By ... ASC" command in the column header I got wrong order, example b-z-á-é. (this is same of the result of general collation)
If I refresh the table (F5), while the arrow indicate the ordering in column header, I got the correct order, example á-b-é-z.
But if I using "Order By ... ASC" command in the column header I got again the wrong order, example b-z-á-é.

### DBeaver Version

Community 24.2.3.202410201725

### Operating System

Win 11 Pro 23H2 22631.4169

### Database and driver

MySQL 8.3.0
JDBC:MYSQL

**Comment by uslss** [comment]
@KJoe69 
could you provide some sample data to reproduce the issue?
thanks in advance

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
