### ISSUE TITLE
dbeaver crashes

### ISSUE THREAD

**Issue by m-cremer** [dbeaver/dbeaver#36082]
### Description

program crashes after the following action:
1) in an open table-data-view-tab click ONCE on the little table-symbol on left side of the sql line 
2) a small sql-editor popup opens
3) click ONCE on the little table-symbol in the headline of the popup
4) the popup closes
5) repeat action 1
6. DBeaver crashes without any message 

### DBeaver Version

Community 24.2.1.202409221847

### Operating System

Arch Linux, xmonad TWM

### Database and driver

MariaDB

### Steps to reproduce

1) in an open table-data-view-tab click ONCE on the little table-symbol on left side of the sql line 
2) a small sql-editor popup opens
3) click ONCE on the little table-symbol in the headline of the popup
4) the popup closes
5) repeat action 1
6. DBeaver crashes without any message

**Comment by Matvey16** [comment]
@m-cremer Hello. How did you install DBeaver?
It's not reproduced for me under normal circumstances

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
