### ISSUE TITLE
Multiptle problem markers are appeared/disappeared on every scroll event for the correct query

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#36084]
### Description

https://github.com/user-attachments/assets/a02c5c57-7d4e-4eae-bb7c-5e90e13ed062

### DBeaver Version

Enterprise Edition 24.2.4-202410262322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

### Steps to reproduce

Try to scroll the script similarly how I do it on the video:
[Script-47.zip](https://github.com/user-attachments/files/17544219/Script-47.zip)

**Comment by uslss** [comment]
thanks for the report
