### ISSUE TITLE
Release 24.2.3 (of october 20th) is not published in ubuntu repo

### ISSUE THREAD

**Issue by icegood** [dbeaver/dbeaver#36089]
### Description

https://ppa.launchpadcontent.net/serge-rider/dbeaver-ce/ubuntu/dists/

doesn't have given release

### DBeaver Version

Version 24.2.2.202410061621

### Operating System

Ubuntu 24.10

**Comment by ShadelessFox** [comment]
Thanks for the report. The next release will be published on Monday.
