### ISSUE TITLE
Upgrade tycho to version 1.1.0 to support Java >= 9

### ISSUE THREAD

**Issue by muflone** [dbeaver/dbeaver#3608]
Hi

The current source uses tycho 1.0.0 which fails to build DBeaver from source with many errors related to unresolved dependencies on base classes
https://bugs.eclipse.org/bugs/show_bug.cgi?id=514471

Please upgrade tycho to 1.1.0 which currently builds fine with both Java 8, 9 and 10 using both JDK and JRE.

Tested under Arch Linux x86_64 with both versions 5.0.6 and 5.1.0

**Comment by muflone** [comment]
Why aren't patch files supported by github?
http://paste.muflone.com/paste.php?id=34

**Comment by serge-rider** [comment]
Good point
