### ISSUE TITLE
OpenSSL Vulnerability associated with DBeaver product installed in our instance

### ISSUE THREAD

**Issue by tanveer953** [dbeaver/dbeaver#36095]
### Description

We have a virtual machine running in our Azure cloud platform and this instance is showing OpenSSL findings is associated with DBeaver product which is running in our VM to connect to the Database and I have updated this DBeaver product to the latest version as well (24.2.2) but still OpenSSL is showing as vulnerable so we need your help here in updating the below binaries to the latest versions and below is the filepath for vulnerable OpenSSL versions.

c:\users\kdodiya\appdata\roaming\dbeaverdata\drivers\clients\postgresql\win\15\libcrypto-3-x64.dll
c:\users\kdodiya\appdata\roaming\dbeaverdata\drivers\clients\postgresql\win\15\libssl-3-x64.dll

### DBeaver Version

24.2.2

### Operating System

Windows Server 2019

### Database and driver

PostgreSQL 15

**Comment by LonwoLonwo** [comment]
Closed as a duplicate of #36094
