### ISSUE TITLE
DBeaver 5.1.0 launch on OpenSUSE Leap 15.0 fails at missing, old "libffi.so.4"

### ISSUE THREAD

**Issue by hal869** [dbeaver/dbeaver#3609]
Exec/launch of DBeaver 5.1.0 on OpenSUSE Leap 15.0, fails with
```
	/tmp/jna-3506402/jna6054383978633988988.tmp: libffi.so.4: cannot open shared object file: No such file or directory
	/tmp/jna-3506402/jna6054383978633988988.tmp: libffi.so.4: cannot open shared object file: No such file or directory
```

on this distro, the official release of libffi*
```
	https://build.opensuse.org/package/show/openSUSE%3ALeap%3A15.0/libffi
```
is v3.2.1 rgit259
```
	rpm -q --whatprovides ./libffi.so
		libffi-devel-3.2.1.git259-lp150.18.2.x86_64
```
which installs
```
	cd /usr/lib64
	ls -al *libffi*
		lrwxrwxrwx 1 root root  15 May 31 21:39 libffi.so -> libffi.so.7.1.0*
		lrwxrwxrwx 1 root root  15 May 31 21:38 libffi.so.7 -> libffi.so.7.1.0*
		-rwxr-xr-x 1 root root 39K Apr  9 11:30 libffi.so.7.1.0*
```
forcing a symlink
```
	cd /usr/lib64
	ln -sf libffi.so.7.1.0 libffi.so.4
```
and relaunching DBeaver *does* appear to work -- currently

**Comment by serge-rider** [comment]
Not sure what component has this dependency. 
As far as I know Eclipse (SWT) doesn't have direct dependencies on libffi. Maybe this is side effect of some local build.

**Comment by hal869** [comment]
> Eclipse (SWT) doesn't have direct dependencies on libffi

Starting wih that realization, after some digging, and the obvious whine^ about

```
/tmp/jna-3506402/jna6054383978633988988.tmp
```

I force un-/re-installed 'jna' packages, and ... that solved the issue.

After rm'ing the faux libffi.so.4 link, DBeaver's error-free on launch again.

Thx!
