### ISSUE TITLE
OpenSSL Vulnerability associated with DBeaver product installed in our instance

### ISSUE THREAD

**Issue by tanveer641** [dbeaver/dbeaver#36094]
### Description

We have a virtual machine running in our Azure cloud and this instance is showing OpenSSL findings is associated with DBeaver product which is running in our VM to connect to the Database and I have updated this DBeaver to the latest version as well (24.2.2) but still OpenSSL is showing as vulnerable so we need help here in updating the below binaries to the latest versions.

c:\users\kdodiya\appdata\roaming\dbeaverdata\drivers\clients\postgresql\win\15\libcrypto-3-x64.dll
c:\users\kdodiya\appdata\roaming\dbeaverdata\drivers\clients\postgresql\win\15\libssl-3-x64.dll

### DBeaver Version

24.2.2

### Operating System

Windows Server 2019

### Database and driver

PostgreSQL 15

**Comment by LonwoLonwo** [comment]
Hello @tanveer641 

Do you have a specific number (name) of CVE?

Also, maybe will be resolved here: https://github.com/dbeaver/dbeaver/issues/21241

**Comment by ShadelessFox** [comment]
Thanks for the report. We're going to update our PostgreSQL native client to the latest version in #21241. It shouldn't have any CVEs.
