### ISSUE TITLE
Refresh project databases config

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#36092]
Let's add action to refresh database connections from disk.
Add it to database navigator view menu.

**Comment by serge-rider** [comment]
![image](https://github.com/user-attachments/assets/cff49420-d7bd-4631-80d6-35c7ceca0096)

**Comment by serge-rider** [comment]
![image](https://github.com/user-attachments/assets/849207f4-7e1e-4a36-a69f-713e64f115bb)

**Comment by uslss** [comment]
An attempt to refresh Tables node after table creation leads to all connections refreshing, but the new table isn't shown.

https://github.com/user-attachments/assets/9425f962-ee5f-47e3-8c8a-ff5b48994754

**Comment by uslss** [comment]
verified
