### ISSUE TITLE
PostgreSQL 11 Beta - Stored Procedures

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#3610]
Hi,

I just want to inform you that PostgreSQL 11 Beta is available. One new feature is the support for Stored Procedures.

Please keep this in mind when working on new features for the PostgreSQL specific part.

Very brilliant and decent tool - this DBeaver / So thank you very much for your effort!

Cheers from Germany
James

**Comment by JamesInform** [comment]
Hi Serge

Do you have this enhancement still on your list?

PostgreSQL 11 is in Beta3 and many people (including me) are testing for the new release that is going to be available in the next quarter. Procedures are hard to handle in current DBeaver.

If you want to install the current Beta version, just head over to bigsql.com and use the command line tool "pgc".

Thanks so much for DBeaver!!!

Cheers
James

**Comment by LonwoLonwo** [comment]
Was implemented here https://github.com/dbeaver/dbeaver/issues/4446
