### ISSUE TITLE
Apple could not verify “DBeaver.app” is free of malware that may harm your Mac or compromise your privacy.

### ISSUE THREAD

**Issue by jbosse** [dbeaver/dbeaver#36102]
### Description

When launching 24.2.3 I receive the error
> Apple could not verify “DBeaver.app” is free of malware that may harm your Mac or compromise your privacy.

### DBeaver Version

Community Edition 24.2.3

### Operating System

macOS 15.1

**Comment by jbosse** [comment]
Community Edition 24.2.1 is the most recent that I can download and run.

For clarification I tried `dbeaver-ce-24.2.3-macos-aarch64.dmg` and `dbeaver-ce-24.2.2-macos-aarch64.dmg`

**Comment by ShadelessFox** [comment]
Hello @jbosse,

Can you please confirm that it only happens on macOS 15.1? I believe it was released yesterday, so we haven't verified its compatibility with DBeaver yet.

**Comment by Phillipus** [comment]
I just tested the 24.2.3 aarch64 download on macOS 15.1 and it's OK.

Maybe try downloading it again and make sure you're connected to the internet when launching in case it's trying to validate the notarisation online.

**Comment by jbosse** [comment]
Yes it launches on my personal MacBook with 15.1. Sorry about that. I assume it's a ZScaler issue blocking the notarization server somehow. I am not sure why this is the only app. I guess I will try some others to confirm.

**Comment by jbosse** [comment]
I found a workaround, I copied the .app from my personal Mac to my work Mac and that works. 🤷🏼‍♂️ Sorry for wasting your time.

**Comment by ShadelessFox** [comment]
No worries. Thank you for investigating.

**Comment by andrei-epure-sonarsource** [comment]
I have this issue on Mac OS Sequoia Version 15.2 (24C101)

should I open a new ticket?

**Comment by jbosse** [comment]
@andrei-epure-sonarsource do you have ZScaler on your Mac by any chance?

**Comment by andrei-epure-sonarsource** [comment]
I have FortiClient (it's like ZScaler)

**Comment by jbosse** [comment]
My understanding is that Zscaler basically does a man in the middle "attack" that intercepts all https traffic to decrypt inspect and use its own certs to re-encrypt. If a service tries to validate the certs it will fail because the requests have been tampered. The admin will need to add the apple notarization URIs to an allow list that prevents the app from tampering with those requests. I had to send this page to our admins https://support.apple.com/en-us/101555 to get them to add the domains. Specifically I think `api.apple-cloudkit.com` is the URI that is being used to verify the App is from a safe developer.
