### ISSUE TITLE
Items in autocomplete are doubled, autocomplete list contains unrelated columns

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#36103]
### Description

- set New autocompletion engine = true  in Preferences
- use code:
```
drop table if exists hello;

CREATE TABLE public.hello (
    id int4 NOT NULL,
    begindate date NOT NULL, 
    enddate date NOT NULL
);

select 
    w.id
from hello as w
```

- follow the steps from the video
- use Ctrl + Backspace to delete the text "id", then start typing the word end

expected: the autocomplete list contains only one item with the column name "enddate"
actual: sometimes autocomplete list shows doubled date-columns (begindate, enddate - see the first video) and sometimes = all the columns (see the second video below)

https://github.com/user-attachments/assets/00ca9c20-646c-4641-834c-80a2900789b7

https://github.com/user-attachments/assets/324aada0-4740-45bc-9b18-19b0a5946f7a

Press Ctrl + Space after the word "end" in order to get autocompletion for the existing column "enddate" containing this substring, but the items are also doubled along with an alias:

https://github.com/user-attachments/assets/79ee7b22-27b3-4828-976e-f3460295da45

### DBeaver Version

Enterprise Edition 24.2.4-202410262322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by ShadelessFox** [comment]
Thanks for the bug report. I managed to reproduce the issue.
