### ISSUE TITLE
No option to configure boolean editor representation

### ISSUE THREAD

**Issue by gabrielomnius** [dbeaver/dbeaver#36109]
### Description

Booleans are (by default) displayed as "[ ]" and "[ v ]" in data editor/grid.
I wanted to change this behavior, but couldn't find any settings affecting this.
I found out that there should be a configuration section in "Settings > Editors" (from a colleague using an older version). See screenshot 1 + 2.
It's even mentioned in "Settings > Editors > Data Editor > Appearance Grid" (on right side section "Behavior"). See screenshot 3.
![screenshot-1](https://github.com/user-attachments/assets/cb17d47c-d346-423d-8a56-0fe20e97f193)
![screenshot-2](https://github.com/user-attachments/assets/22c0aa5e-e7df-46f0-917e-123573f6babe)
![screenshot-3](https://github.com/user-attachments/assets/323c61cc-ef98-4530-994f-6fa24f95f2f4)

### DBeaver Version

Community Edition Version 24.2.3.202410201725

### Operating System

macOS 15.1 (24B83)

### Database and driver

Current PostgreSQL JDBC Driver - version is not disclosed in connection details/settings.

### Steps to reproduce

1. Open settings
2. Go to Editors
3. Note: no boolean configuration section

**Comment by ask9** [comment]
@E1izabeth  By the way, search by the keyword "bool" doesn't find all the related settings in Preferences.
I suggest indexing it as well.

**Comment by ShadelessFox** [comment]
It was moved to **User Interface -> Miscellaneous**:

![image](https://github.com/user-attachments/assets/0a9cbf0e-43a6-4b62-afda-95be483da7a4)

Thanks for the report.
