### ISSUE TITLE
DBeaver + oracle kerberos authentification

### ISSUE THREAD

**Issue by Davy7887** [dbeaver/dbeaver#3611]
Hi all,

I'm new on Dbeaver.
I would like to know how to connect to oracle database with kerberos authentification on DBeaver please ?

Thanks.

**Comment by flequi** [comment]
Hi Davy.

I've used Dbeaver one year ago, and I don't know how to connect with kerberos either.
I found this article about problems with Kerberos, but I didn't found any guide to explain how to config it. 
[Article1](https://github.com/dbeaver/dbeaver/issues/1737)
[Article2](https://justnumbersandthings.com/post/2017-05-06-dbeaver-hive/)

Like I can understand about this article, I think you have to create a "pgjdbc.conf" file with this content:
`pgjdbc {
  com.sun.security.auth.module.Krb5LoginModule required
  doNotPrompt=true
  useTicketCache=true;
};`

Then you have to add one line to your dbeaver.ini file with the path of this file:
`--Djava.security.auth.login.config=yourPath\pgjdbc.conf`

Then you have to configure Kerberos in your local machine, and you must create a ticket with the kbinit command (find any kerberos installation guide).

If I can configure it, I'll answer with more detailed information.

Bye

**Comment by tati-kru** [comment]
Most likely Kerberos support will be implemented in DBeaver EE 6.3 or later.

**Comment by flequi** [comment]
It's Kerberos yet implemented in DBeaver???

**Comment by vstrale** [comment]
DBeaver EE 6.3 is out. Do we know if Kerberos is part of it (I am using community version) and whether Kerberos will be part of the community version soon?

**Comment by Danneman42** [comment]
There's no mention of Kerberos in the 5 latest release notes (v6.3.0 - v6.3.4). In fact, searching for "Kerberos" @ DBeaver Community yields only one hit: in the v5.3.3 release notes; it's referred to in context of SQL Server.
But I'd need it for Oracle. First when I started using DBeaver 3 months ago, I wanted to switch away from Toad completely, but couldn't because Kerberos is missing. Now it's getting more pressing, since our company is migrating to Oracle DB 19c and the old Toad version is not compatible (and no licenses for a newer version...)

**Comment by serge-rider** [comment]
Generally Kerberos connection can be configured from command line/dbeaver.ini by modifying Java properties + system environment.

We are working on adding Kerberos configuration in UI. DBeaver EE 7.0 Early Access version already supports Kerberos for PostgreSQL.

SQL Server, Hive and Oracle are the next candidates.

I can't say when exactly Kerberos support will be added in Community edition. But probably not in this year.

**Comment by flequi** [comment]
Ok, thanks for the info Serge, and congratulations for the last releases.

**Comment by arvenil** [comment]
@serge-rider I have a case where I need to use Kerberos for SSH-tunnel. This still doesn't work in 7.0 EE.

**Comment by flequi** [comment]
Hi Friends.
In other thread it's explains how to connect with Radius, that i'ts another way to connect to DB of production environments.
You must to add one property in the Driver Properties tab:
**oracle.net.authentication_services**   with value   **RADIUS**

![image](https://user-images.githubusercontent.com/4034173/224253487-40e8d22b-0f3c-4670-a275-06eac8566e45.png)

[https://github.com/dbeaver/dbeaver/issues/10358](url)

If you have configured all the Oracle settings with SQLPlus or SQLDeveloper, you can do it with DBeaver too.

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/wiki/Kerberos-Authentication 
DBeaver PRO products supports Oracle + Kerberos
