### ISSUE TITLE
recursive cte triggers "java.lang.NullPointerException"

### ISSUE THREAD

**Issue by simonB2020** [dbeaver/dbeaver#36110]
### Description

While coding recursive cte queries DBeaver constantly pops up alerts as you type - literally at every keypress!

"'SQL editor markers refresh' has encountered a problem.
An internal error has occurred."

Clicking "Details > >" then displays : 
"An internal error has occurred.
java.lang.NullPointerException"

Notes:
- the code being written does execute successfully.
- Source connection is AWS Redshift

### DBeaver Version

Community 24.1.4.202408041450

### Operating System

Windows 11

### Database and driver

AWS Redshift JDBC42 [2.1.0.29]

### Steps to reproduce

Example code in SQL tab:

```
SET enable_case_sensitive_identifier TO true; 

with recursive cte ("top", "path", "parent", "child", "level") 
as (
	-- TOP LEVEL items the are not children to others
	select 
		p.containerdescriptor as "top",   
		p.containerdescriptor as "path",
		p.containerdescriptor as "parent",
		p.memberdescriptor as "child",
		1 as "level"
	from 
		azdo.vw_memberships p 
	where
		p.containerdescriptor not in (select distinct ii.memberdescriptor from azdo.vw_memberships ii)
	union all 
	select 
		c."top",
		c."path" || '_' || e.containerdescriptor as "path",
		e.containerdescriptor as "parent",
		e.memberdescriptor as "child",
		level + 1 as "level"
	from 
		azdo.vw_memberships as e
		, cte as c
	where 
		e.containerdescriptor = c."child"
		and c."level" < 4
)
select * 
from cte 
where level > 2 
limit 100
```

**Comment by ShadelessFox** [comment]
Hello @simonB2020,

Please provide log files: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by E1izabeth** [comment]
We can't reproduce the issue. And it's been a while since no update here. If the issue is still actual please let me know and provide log files.
