### ISSUE TITLE
Text of the item in a list of a history is very long

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#36124]
### Description

- use the query for dvdrental database:
```
select * from public.rental as r
join inventory as i on i.inventory_id = r.inventory_id
join public.customer as c on c.customer_id = r.customer_id
join staff as st on st.staff_id = r.staff_id
join film as f on f.film_id = i.film_id
join address as a1 on a1.address_id = c.address_id
join address as a2 on a2.address_id = st.address_id
join "language" as l on f.language_id = l.language_id
;
```

https://github.com/user-attachments/assets/cefa52da-620b-439f-a259-2dd2fdbfa986

### DBeaver Version

Enterprise Edition 24.2.4-202410172322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by HocKu7** [comment]
Thank you for your report.
