### ISSUE TITLE
Error installing SSHJ plugin

### ISSUE THREAD

**Issue by vaindil** [dbeaver/dbeaver#3613]
Windows 10 x64, DBeaver Community 5.1.0. I'm trying to install the SSHJ plugin from https://dbeaver.io/update/sshj/latest/, but I'm receiving the error below. I tried while running DBeaver as admin, same error.

```
An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
    session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
    Error reading signed content.
    Exception in opening zip file: C:\Program Files\DBeaver\plugins\org.jkiss.bundle.bouncycastle_1.59.0
```

**Comment by serge-rider** [comment]
Check this - https://github.com/dbeaver/dbeaver/wiki/Optional-extensions
`
IMPORTANT: installation won't work if DBeaver is installed in write-protected folder (like Program Files, /Applications, /usr/). To proceed you need to run DBeaver from some non write-protected folder or run it as Administrator/root.
`

**Comment by vaindil** [comment]
Yes, I put in my issue that the problem still occurs when running as administrator.

**Comment by serge-rider** [comment]
Hmm, can't reproduce that. Just installed this on fresh DBeaver copy.

Perhaps something went wrong during sshj plugin download.
Please post full error stacktrace.

Also - did you use DBeaver installer or you have some other preinstalled Java?

Also you could try to reinstall DBeaver and install SSHJ again.

**Comment by serge-rider** [comment]
Also this looks similar to #3624

**Comment by vaindil** [comment]
I tried again today and it worked. No idea why it didn't work previously. I'll close this, sorry, and thank you!
