### ISSUE TITLE
[New autocompletion] Unexpected behavior in a window with props

### ISSUE THREAD

**Issue by VASilaev** [dbeaver/dbeaver#36140]
### Description

The props window appears belatedly after a space. You need to stop the process of searching for props if you continue typing after a space, otherwise the window with props appears at an unexpected moment and instead of going to a new line on Enter, the first line of props is inserted.

### DBeaver Version

Community Edition 24.2.3.202410201725

### Operating System

Windows 10 x64

### Database and driver

PG 13

### Steps to reproduce

in from after tablename type " inner join" and press Enter, perhaps a window will be shown by this time
![Анимация](https://github.com/user-attachments/assets/1c2f3014-4a7c-48e8-86ae-f3ebc5206fe0)

**Comment by E1izabeth** [comment]
@VASilaev please switch your preference to Default autocompletion. New autocompletion engine was not released yet
![image](https://github.com/user-attachments/assets/6c0ebaa1-901f-454b-87de-3b012a44027d)

**Comment by VASilaev** [comment]
Ok, thanks. It is work.
