### ISSUE TITLE
Maintain ERD diagram over refreshed tables

### ISSUE THREAD

**Issue by eurojojo** [dbeaver/dbeaver#36158]
**Is your feature request related to a problem? Please describe.**
The ERD diagram for the database I work on loses its virtual relationships after tables are refreshed in my database. My use case involves working with dimension tables that are refreshed nightly. Each day, I find that while the tables remain in the same layout in the ERD, the virtual relationships I had previously configured disappear entirely, and I have to manually recreate them. During the day, the relationships stay intact across sessions as long as the tables are not refreshed. This results in repetitive work and disrupts productivity, especially when working with complex diagrams.

**Describe the solution you'd like**
I would like DBeaver to offer a feature that allows ERD diagrams to retain virtual relationships even after the underlying tables are refreshed. Ideally, this feature would store the layout and relationships as part of the ERD or project configuration in a way that’s independent of table metadata changes caused by the refresh.

**Describe alternatives you've considered**
I did save an ERD-file with all the relations, but importing has no effect. The tables are placed at the correct position as before, but there are no virtual relationships anymore. For now I maintain the diagram in a yEd editor, but when new tables become available that has to be edited in a separate process, not within DBeaver. I have also tried if there is a script I could write to recreate the virtual relationships in DBeaver using the ERD-file (as a fix to the non-working import), but that does not seem to possible. Reconstructing the diagram daily is too time-consuming and error-prone.

**Additional context**
A solution like this could benefit users who work with frequently updated data tables and need a stable, consistent ERD layout with persistent relationships. Also the option to write scripts to recreate or modify the internal ERD-diagram would be handy.

**Comment by HocKu7** [comment]
@eurojojo Did you try to create a Custom ERD? 
https://github.com/dbeaver/dbeaver/wiki/Custom-Diagrams 
https://dbeaver.com/2022/06/30/two-ways-to-use-erd-in-dbeaver/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by eurojojo** [comment]
I moved on to get the DDL-file from DBeaver for my tables, and I wrote a little Python code to convert it to DBML. And then I could add new relationships between columns in that DBML. The visualisation is then done in https://dbdiagram.io/
