### ISSUE TITLE
OTP - One Time Passwords support?

### ISSUE THREAD

**Issue by ruehsn** [dbeaver/dbeaver#36154]
### Description

I am unable to connect to a database using One Time Password (OTP).  Connecting to the same database/connection profile works with a different userID that has static password.  

Looking the trace route, it looks like the there is 1 initial connection that works but then fails later, killing the connection.
I suspect that DBeaver is caching the password and attempting to open multiple connection to the database for increase speed.  When it tries to open a second database connection with the old password it fails.

I think either could:
1) disable multiple connection so password is only used once
2) clear the password cache so if password is requested again it prompt the user for new password

### DBeaver Version

Community Edition 23.0.1

### Operating System

Windows 11

### Database and driver

DB2 - JDBC v 9

### Steps to reproduce

Try connecting to database using OTP as their authentication.

**Comment by TB-HunBoka** [comment]
Can you try modifying the "Open separate connection for metadata read" to never?
Connections -> metadata
![image](https://github.com/user-attachments/assets/09479e16-dd8d-4e2b-acf4-498670a42112)

**Comment by ruehsn** [comment]
Thanks for the suggestion.  My account still locked out when connecting.

Anyway I can increase the logging to see every JDBC connection attempt?

**Comment by E1izabeth** [comment]
Hi, @ruehsn!
You can also switch this setting to Never for SQL Editor
![image](https://github.com/user-attachments/assets/08df9007-834d-4e51-9ace-9c2e2ae080a3)

Does it help?

**Comment by ruehsn** [comment]
That seems to work - thanks @E1izabeth !
