### ISSUE TITLE
Why DBeaver 24.2.1 made this change? Azure SQL: “show all databases” option was removed

### ISSUE THREAD

**Issue by unaivicente** [dbeaver/dbeaver#36162]
Hi,

In DBeaver 24.2.1 it can be seen that Azure SQL: “show all databases” option was removed. My question is why? We need that option to be able to see schemas in our Azure Synapse, and I believe some other people can have the same problem. We had to downgrade all our software because of that. We have DBeaver Enterprise licenses.

Thanks in advance,

Unai

**Comment by arhayka** [comment]
Thank you for the report!
We'll try to rework this feature in the near future.

**Comment by arhayka** [comment]
We decided to return this flag. 
Additionally, we want to write an error message that the user needs to create a new connection to work with these databases.
