### ISSUE TITLE
Row colorization priorities seem random

### ISSUE THREAD

**Issue by ChaoticEntertainment** [dbeaver/dbeaver#36166]
### Description

How to sort the row colors? Two columns in a single row are trying to color the same row, how to choose which one ends up being the dominant color? I have the same table twice, but the behavior in both tables on this is different.

### DBeaver Version

Community Edition 24.2.4.202411031831

### Operating System

Windows 11

**Comment by ShadelessFox** [comment]
Hello @ChaoticEntertainment,

Can you please provide footage showing the issue? It's not entirely clear what you're talking about.

**Comment by ChaoticEntertainment** [comment]
I cannot provide footage as the data is confidential, but it shouldn't be that unclear.

Just imagine that two "Row Color" checks are true at the same time in two different columns on the same row. They both want to color the whole row in their own colors (red & blue). How does DBeaver ultimately decide whether the resulting color will be red or blue? As doing the same setup again on another table, leads to the opposite color winning.

I can provide a quick mockup of the issue, showcasing that the same rule setup leads to different results in different tables:
![image](https://github.com/user-attachments/assets/2ebe6e8d-be88-4a76-9df2-d4a7f1e7c88e)

**Comment by ShadelessFox** [comment]
Thanks for the clarification. DBeaver uses the last matching color as the final color:

![image](https://github.com/user-attachments/assets/14bf01ea-6574-4aa7-a954-01ce2b5362c5)

I don't consider this a bug.

**Comment by ChaoticEntertainment** [comment]
We're getting closer but you still haven't reached a full understanding of the issue. The two "Row Color" rules are defined in two seperate columns, not in the same one.

**Comment by ShadelessFox** [comment]
Okay, I missed that detail. I found the issue; thanks for the report.

**Comment by kseniaguzeeva** [comment]
Verified

**Comment by ChaoticEntertainment** [comment]
I just updated to the latest stable version that includes this commit, and my issue is not solved. Maybe it helps to point out that one of my two tables is a Table and the other is a View? Have you potentially forgotten to apply this fix to Views as well?

**Comment by ShadelessFox** [comment]
What version did you install? The fix is included in 24.2.5, and I just confirmed that it's really there. 

The latest attribute's color, according to their visual order, should be used as the final color. Is the color still random?

**Comment by ChaoticEntertainment** [comment]
Yup, that's the version I got. I don't know for certain whether the color is actually random, but it's certainly not following the visual order in my View, as opposed to my Table.

**Comment by ChaoticEntertainment** [comment]
Here's an image of the exact situation and issue. Both pictured rows should be pink colored, but UsersView, contrary to Users, is ignoring the visual order in the Row Color settings window.

![image](https://github.com/user-attachments/assets/9cbe64bc-2edc-456d-8fb9-825166045857)

Users and UsersView are essentially clones of eachother, so I need them to look the same.

**Comment by kseniaguzeeva** [comment]
@ChaoticEntertainment Could you please provide me an information about your database? Maybe it could help to reproduce the issue.

**Comment by ChaoticEntertainment** [comment]
It can be noted that in both cases the "Lite" column has been moved in front of the "UserID" column using a DBeaver custom filter, meaning that "Lite" was originally located behind "UserID". This could've confused the UsersView coloring maybe?

![image](https://github.com/user-attachments/assets/e6a50261-ab36-409a-9d51-4626007fc41f)

**Comment by kseniaguzeeva** [comment]
The only way I've reproduced the behavior is: 

1. to apply the color to UserId column
2. to apply the color to Lite column
3. to change columns order in the custom filter.

Can it be your case?

https://github.com/user-attachments/assets/ced0be4d-208f-4621-9c3e-be81fea0e05a

**Comment by ChaoticEntertainment** [comment]
That's indeed how it's done in both my table & view, though both get different results when doing so:

![image](https://github.com/user-attachments/assets/80973268-0778-469a-a838-9458b326d3e6)

The expected result is that they both behave the same way. (That way preferably being to always respect the custom order, as the Row Color settings screen itself respects it as well, so in this case I'd like to see them both be colored pink.)

**Comment by ShadelessFox** [comment]
Thanks for clarifying. The proposed behavior should be addressed by #36350
