### ISSUE TITLE
"Name" column in "Project - General" has no symbols "..." when its content doesn't fit the width of the column leading to decreased readability

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#36160]
### Description

On the video below, first of all, I show the correct expected behaviour in all other columns.
Symbols "..." are shown for all columns, except "Name" column.
The issue itself is shown at the end of the video when the symbols "..." are not shown in the "Name" column.
I suggest adding these symbols for this column as well, because it makes it more readable.

https://github.com/user-attachments/assets/927d4c15-a773-4703-a73a-6face52fe8a7

### DBeaver Version

Enterprise Edition 24.2.4-202410172322

### Operating System

Windows 10

**Comment by ShadelessFox** [comment]
It's not a column but a tree. This is a limitation of the Eclipse/SWT platform.
