### ISSUE TITLE
Data changes can't be saved using Value Panel

### ISSUE THREAD

**Issue by escnmnegrete** [dbeaver/dbeaver#36178]
### Description

When editing values in the Value panel in DBeaver, changes are not saved. This issue affects text fields and JSON fields. Previously, changes made in the Value panel could be saved directly, but now they require editing in the cell itself for changes to be applied. Additionally, after modifying a value in the Value panel, the Save icon remains unavailable, indicating that DBeaver doesn't recognize the change.
![image](https://github.com/user-attachments/assets/70e2a367-5f4e-424a-8426-17de3711fe67)

### DBeaver Version

24.2.4

### Operating System

Windows 11 23H2

### Database and driver

1. Database: PostgreSQL 15.8
2. Driver: postgres-jdbc

### Steps to reproduce

1. Open DBeaver and connect to the relevant database.
2. Navigate to the table with the fields (e.g., text or JSON) that need to be edited.
3. Open the Data Editor for this table.
4. Click on a field, open the Value panel, and make a change (e.g., modify text content or JSON).
5. Notice that the Save icon is not enabled, even though a modification was made in the Value panel.
6. Attempt to save the change (if applicable, commit the transaction if auto-commit is disabled).

**Comment by MashaKorax** [comment]
@escnmnegrete Thanks for your report.

**Comment by MashaKorax** [comment]
I reproduced the issue with json but not with text. Could you make a screen recording with text?

**Comment by alexandreSantosPulsus** [comment]
@serge-rider I just ran into this issue again, now in version 24.3.4. The issue was solved after return to version 24.3.3.

**Comment by RicardsR** [comment]
> [@serge-rider](https://github.com/serge-rider) I just ran into this issue again, now in version 24.3.4. The issue was solved after return to version 24.3.3.

I can confirm this as well on the 24.3.4 WIndows 11

**Comment by harzo** [comment]
Same here, 24.3.4 MacOS Sequoia 15.3
Json changes are not recognized and, therefore can not be saved.

**Comment by bombillazo** [comment]
Was this realeased? I Edit my JSON fields but the changes are not stored.

**Comment by ajohnson1117** [comment]
I'm experiencing the same issue. Version 24.3.4 Windows 11.

Edit: I can confirm this works when going back to version 24.3.3

**Comment by synchro-un** [comment]
I was facing the same issue; it ended up being the auto-save icon in the value panel that was disabled.

![IMG-20250212-WA0001.jpg](https://github.com/user-attachments/assets/f38eb243-8a24-4a7c-bc21-733282589aa5)

**Comment by alexandreSantosPulsus** [comment]
> I was facing the same issue; it ended up being the auto-save icon in the value panel that was disabled.
> 
> ![IMG-20250212-WA0001.jpg](https://github.com/user-attachments/assets/f38eb243-8a24-4a7c-bc21-733282589aa5)

@synchro-un Good call. I always keep that option enabled, though, because I work with json and jsonb fields all the time. But I don't remember if I checked that with version 24.3.4. I'll try ASAP.
