### ISSUE TITLE
unable to import external connections from csv/xml

### ISSUE THREAD

**Issue by lj67** [dbeaver/dbeaver#36173]
### Description

using the two examples here: https://dbeaver.com/docs/dbeaver/Admin-Manage-Connections/

I am unable to import connections using csv or xml. when trying the csv example it says 'connection list is empty'. when using xml it says 'Error parsing XML document'

![image](https://github.com/user-attachments/assets/0a34013d-d134-48fb-831b-7343c900a90c)
![image](https://github.com/user-attachments/assets/9a7d4896-741f-485d-aecf-9a0c35d49a12)

### DBeaver Version

community Version 24.2.4.202411031831

### Operating System

windows

### Database and driver

firebird 5.0.4.java11

### Steps to reproduce

1. file -> import -> third party configuration -> custom
2. select firebird
3. select csv or xml file. click next
4. error is shown

### Additional context

example xml:

```
<connections>
	<connection name="Postgre Import XML 1" host="localhost" port="5432" server="" database="postgres" url="jdbc:postgresql://localhost:5432/postgres" user="postgres" password="postgres" type="dev" />
	<connection name="Postgre Import XML 2" host="localhost" port="5432" server="" database="postgres" url="jdbc:postgresql://localhost:5432/postgres2" user="postgres2" password="postgres2" type="prod" />
</connections>
```

**Comment by lj67** [comment]
are you able to share the xml file you used that worked? It's still failing for me.

**Comment by HocKu7** [comment]
@lj67 Hi. Unfortunately, I cannot reproduce the issue. Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by lj67** [comment]
here are the logs but i'm afraid there doesn't look to be anything related in there.
i have just tried the import again using xml and still get the 'error parsing XML document' at 14:09 on Nov 7th. I then extracted the log files afterwards
[dbeaver-debug.log](https://github.com/user-attachments/files/17662636/dbeaver-debug.log)

note i changed the xml file to include the xml info but no joy.

`﻿<?xml version="1.0" encoding="UTF-8"?>
<connections>
	<connection name="Postgre Import XML 1" host="localhost" port="5432" server="" database="postgres" url="jdbc:postgresql://localhost:5432/postgres" user="postgres" password="postgres" type="dev" ></connection>
	<connection name="Postgre Import XML 2" host="localhost" port="5432" server="" database="postgres" url="jdbc:postgresql://localhost:5432/postgres2" user="postgres2" password="postgres2" type="prod" ></connection>
</connections>`

**Comment by lj67** [comment]
[.log](https://github.com/user-attachments/files/17662740/default.log)

**Comment by E1izabeth** [comment]
>are you able to share the xml file you used that worked?

Sure! Sorry for long wait. Here it is. Just tried and it's working fine for me.

[example.xml.txt](https://github.com/user-attachments/files/18042560/example.xml.txt)

**Comment by E1izabeth** [comment]
@lj67 could you check with the provided file and let me know if the issue is reproducible for you?

**Comment by lj67** [comment]
thank you for you help, that file helped me track down the issue. my file had identical content to yours but it was saved in 'UTF8 with BOM'. once i resaved as plain utf8, then the import completed. Thanks again!
