### ISSUE TITLE
Misleading german translation for "Data Formats" in Preferences Dialog

### ISSUE THREAD

**Issue by MarkusMayer** [dbeaver/dbeaver#3617]
![preferences](https://user-images.githubusercontent.com/11522189/41275612-bf163a1c-6e21-11e8-906d-6224bc90aa5c.png)
Hi,
just a tiny remark. We just stumbled over an imho misleading german translation in the preferences dialog. The sub-dialog for editing the data formats is called "Datumsformate" in german. This led me to believe that the dialog is for specifying "date format" only. Especially since the date type is the first format type that is displayed. Maybe you could change it to "Datenformate". If thats ok I could submit a PR containing the change.

There are a couple of other german translations missing in the menu texts (e.g. in the "Window" menu).
Sorry for being so picky and thanks for the great tool!
Markus

**Comment by serge-rider** [comment]
It would be great to have PR for that. Unfortunately I don't know German and can't validate this. 
With PR it will be much faster.
