### ISSUE TITLE
Role permissions not showing Grant/Revoke all

### ISSUE THREAD

**Issue by atb-deira** [dbeaver/dbeaver#36185]
### Description

![image](https://github.com/user-attachments/assets/98049790-f716-42f6-aab3-591b9ebeb100)
Role interface permissions not showing Grant/Revoke all when you select schema since version 24.2.3

### DBeaver Version

24.2.3

### Operating System

Windows 10 Enterprise

### Steps to reproduce

1. select a Role
2. select Permissions
3. select a Schema

**Comment by uslss** [comment]
thanks for the report

**Comment by atb-deira** [comment]
thanks
