### ISSUE TITLE
(feature request) let me opt out of modal msgbox "data transfer complete" after exporting

### ISSUE THREAD

**Issue by knwpsk** [dbeaver/dbeaver#3618]
Please give us the option to opt out of the messagebox.
Or get rid of the messagebox altogether and just make it a status message in the app window?
Thanks

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/41318799-31e04c42-6ea2-11e8-893f-d4faaa53c58d.png)

**Comment by knwpsk** [comment]
Thanks, Serge!

**Comment by ash1794** [comment]
Hey Serge,
Currently on 6.0.0 mac version of your software. Can't find this feature on this build. Attaching screenshot.
<img width="616" alt="Screen Shot 2019-05-30 at 3 40 30 PM" src="https://user-images.githubusercontent.com/5153495/58626025-5ec1d000-82f1-11e9-90b4-6db3a420e7db.png">

**Comment by tati-kru** [comment]
It's look like an interface glitch. Please, resize the dialog. It seems the last point is hidden.
