### ISSUE TITLE
RisingWave: Selecting array of structs returns error

### ISSUE THREAD

**Issue by maxjoh** [dbeaver/dbeaver#36198]
### Description

The following query
```
select array[(1,2)]::struct<a integer, b integer>[] as measurements;
```
returns `Cannot invoke "String.hashCode()" because "typeName" is null` in DBeaver SQL console

### DBeaver Version

Community Edition Version 24.2.3.202410201725

### Operating System

MacOS Sonoma 14.7 (23H124)

### Database and driver

* Database name and version: PostgreSQL 13.14.0-RisingWave-2.0.2 (3d308998c7e426049938e86d79aa575c93e88ac2)
* Driver name and version: postgres-risingwave-jdbc (postgresql-42.7.2)

### Steps to reproduce

1. Connect to a RisingWave database
2. Execute the following query in a SQL console
    ```
    select array[(1,2)]::struct<a integer, b integer>[] as measurements;
    ```

### Additional context

The same query works fine using psql

**Comment by E1izabeth** [comment]
Thanks for the bug report. I reproduced the issue

**Comment by ShadelessFox** [comment]
This is a database-side issue.
