### ISSUE TITLE
Community Edition 5.1.0 Driver Manager Problem bug

### ISSUE THREAD

**Issue by xfzhaoxd** [dbeaver/dbeaver#3620]
Bug report:

Database ->Driver Manager 
When I closed Driver Manager ‘ Windows,I couldn't reopen。I must  restart application.

**Comment by xfzhaoxd** [comment]
version 5.0.6 can reopen.

**Comment by serge-rider** [comment]
It is a known issue, already fixed. See fix in 5.1.1.
Thanks for report anyway.
