### ISSUE TITLE
DBeaver Office integration is removed after each DBeaver update installation

### ISSUE THREAD

**Issue by ftonioli** [dbeaver/dbeaver#36203]
### Description

Hello,

After each Dbeaver update installation, is necessarie reinstall DBeaver Office integration.

Is it correct?

### DBeaver Version

Community Edition 24.2.4.202411031831

### Operating System

Windows 10

### Steps to reproduce

Install any DBeaver update

**Comment by ask9** [comment]
Yes, this is well-known limitation.
Keep an eye on this issue #5317 and thumbs up emoji there to vote for faster resolving.

**Comment by ShadelessFox** [comment]
Closing as a duplicate of the referenced ticket.
