### ISSUE TITLE
Cannot open New Sql Console to write custom MySQL Query in DBeaver 24.2.4

### ISSUE THREAD

**Issue by ki5-mshoaibq** [dbeaver/dbeaver#36206]
### Description

When I Open SQL Editor menu Item, like Open SQL Console or New SQL Script,  DBeaver application crashes.

### DBeaver Version

Version 24.2.4.202411031831

### Operating System

Ubuntu 20.04.6 LTS

### Database and driver

Driver for MySQL 8 and later

### Steps to reproduce

I connect a database via SSH tunnel.
The DB opens. I select a table to display data
Table data opens
I Click SQL Editor from top menu
I click Open SQL Console to write a Custom Query to filter data of selected table.
The DBeaver App crashes and closes down

**Comment by ask9** [comment]
Please provide crash logs when it happens again. Instructions are here: https://dbeaver.com/docs/dbeaver/Log-files/#java-fatal-logs

**Comment by E1izabeth** [comment]
It's been a while since there was an update here. If the issue is still actual for you please let me know and provide log files.

**Comment by ki5-mshoaibq** [comment]
Now using Version 24.3.0.202412011650, not encountered any issues like above yet.
