### ISSUE TITLE
How could I list hsqldb synonyms?

### ISSUE THREAD

**Issue by yanOnGithub** [dbeaver/dbeaver#3621]
CREATE SCHEMA sch1;
CREATE TABLE sch1.t1 (id varchar(256) PRIMARY key);
CREATE SYNONYM sch1.s1 FOR sch1.t1;
SELECT * FROM INFORMATION_SCHEMA.SYSTEM_SYNONYMS

![20180613t093600-yan lam-dbeaver 5 1 0 - yan sql](https://user-images.githubusercontent.com/25423046/41326016-ae384f72-6eef-11e8-9f56-3cb19631e6e1.png)

**Comment by serge-rider** [comment]
HSQL synonyms support will be added in 5.1.1
