### ISSUE TITLE
How could I add "SYNONYM" as a keyword for syntax highlight?

### ISSUE THREAD

**Issue by yanOnGithub** [dbeaver/dbeaver#3622]
![20180613t095434-yan lam-greenshot](https://user-images.githubusercontent.com/25423046/41326065-da53c03c-6eef-11e8-90b4-44b276bbd933.png)

**Comment by serge-rider** [comment]
We'll add it in the next version.
If there are some other HSQLDB keywords which are not highlighted - please tell.

**Comment by yanOnGithub** [comment]
http://hsqldb.org/doc/guide/lists-app.html

COMPARABLE
CURRENT_CATALOG
ELSEIF
END_EXEC
FIRST_VALUE
HANDLER
ITERATE
LAST_VALUE
LEAD
LEAVE
LIKE_REGEX
LOOP
MAX_CARDINALITY
NCHAR
NCLOB
NTH_VALUE
NTILE
OCCURRENCES_REGEX
OFFSET
PERIOD
POSITION_REGEX
RESIGNAL
SIGNAL
STACKED
SUBSTRING_REGEX
TRANSLATE_REGEX
TRIM_ARRAY
UNTIL
VALUE

![image](https://user-images.githubusercontent.com/25423046/41445544-de1dc90e-707c-11e8-9f63-98b2caddf933.png)
