### ISSUE TITLE
Wrong DDL created for MariaDB views (missing CREATE VIEW ... )

### ISSUE THREAD

**Issue by queueseven** [dbeaver/dbeaver#3623]
This bug happens in DBeaver 5.1.0.

Create a view on a MariabDB database, like this:

    create view x as select 1 as test;

Now right click on that view in the Database Navigator and choose Generate SQL -> DDL.

Expected result:   
Show the correct DDL to recreate the view (that's what MariaDB's `SHOW CREATE VIEW` would return).

    CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `x` AS select 1 AS `test`

or, even simpler, just

    create view x as select 1 as test;

Actual result: only a part of the `select_statement`-part of the DDL is shown

    select
        1 as `test`;

This already works correctly for SQL Server and PostgreSQL, but not MariaDB.

**Comment by serge-rider** [comment]
Good point. Will fix in 5.1.1
