### ISSUE TITLE
Upgrading DBeaver breaks the Office plugin

### ISSUE THREAD

**Issue by dariopnc** [dbeaver/dbeaver#3624]
Everytime you upgrade DBeaver (since 4.1 until 5.1 at least) when you launch the new version the Office plugin is lost. I'm NOT reporting this behaviour right now, I take this for granted.

So one needs to reinstall it and everytime you reinstall it an error occurs:
![immagine](https://user-images.githubusercontent.com/15945411/41335763-39bb9fe6-6eea-11e8-8562-0fb1f142f415.png)

The only WA provided (in #2021 where I reported the same behaviour) is to uninstall and reinstall the new version.

Can you please make it possible to install the plugin on an upgraded version without any error?

**Comment by serge-rider** [comment]
Actually upgrade (with Windows or MacOS installers) means full remove of previous version (with all plugins) and install of new one. It is not specific to the Office plugin.

But that error with CheckTrust shouldn't happen. How do you install DBeaver - for All Users or for Current User?

**Comment by dariopnc** [comment]
bug still actual in 5.1.2

**Comment by serge-rider** [comment]
Deleting artifacts.xml resolves the issue.
