### ISSUE TITLE
Statistics tab has no title after detaching

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#36247]
### Description

https://github.com/user-attachments/assets/54cd2eb1-2d99-4b7e-b84b-dca7bdd6c36e

### DBeaver Version

Enterprise Edition 24.2.4-202410172322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by MashaKorax** [comment]
Thanks for your report.
