### ISSUE TITLE
Snowflake session does not show correct count of Modifying Statements

### ISSUE THREAD

**Issue by RobertHana** [dbeaver/dbeaver#36248]
### Description

when i am connected to snowflake and i simply view a table sample data, it only issues a select statement -- thus no modifying statements are in the query history, yet the top shows that i have a modifying statement!
![image](https://github.com/user-attachments/assets/9a51b88c-c67b-4f46-829b-662ff49021c7)

### DBeaver Version

Community Edition 24.2.4.202411031831

### Operating System

macOS Sonoma 14.7

### Database and driver

Snowflake 3.14.4

### Steps to reproduce

1. connect to snowflake
2. view a table sample data
3. see the summary shows 1 modifying statement

**Comment by ShadelessFox** [comment]
Hello @RobertHana,

Even if a SELECT statement doesn't seem to do anything harmful, it can call a function that can potentially alter data in the database. Some databases may also support triggers on query execution that can modify data.

I don't consider this a bug.
