### ISSUE TITLE
Wrong DDL created for MariaDB views (database name included inadvertently database)

### ISSUE THREAD

**Issue by queueseven** [dbeaver/dbeaver#3625]
This bug happens in DBeaver 5.1.0.

Create a view on a MariabDB database, like this:

   create view y as select * from myTable;

Now right click on that view in the Database Navigator and choose Generate SQL -> DDL.

Expected result:
Show the correct DDL to recreate the view (that's what MariaDB's SHOW CREATE VIEW would return).

    CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `y` AS select `mytable`.`field1` AS `field1` from `mytable`

or, even simpler, just

    create view y as select `mytable`.`field1` as `field1` from `mytable`; from myTable;

Actual result: the database name is include

    select
        `mydatabase`.`mytable`.`field1` as `field1`
    from
        `mydatabase`.`mytable`;

which is not correct, since I didn't specify the database name before. It should only be shown if I explicitly specify it in my `create view` statement (like MariaDB's `SHOW CREATE VIEW` does it).

**Comment by serge-rider** [comment]
Fixed in #3623
