### ISSUE TITLE
When running multiple queries in a script the "References" tab does not work

### ISSUE THREAD

**Issue by Amitkad** [dbeaver/dbeaver#36258]
### Description

Steps:
1. Open a new "script" window
2. Write two queries
3. Select all and press Ctrl+Enter to run it

Expected:

* Each query result will be shown in a different window
* For each query user would be able to navigate to references using the "References" tab

Actual:

* References tab dropdown list is empty

Additional details:
* When running each query separately the references tab for each works
* query exmaple I used:

select * from time_slot ts WHERE DATE(ts.date) = current_date  + interval '1 days';
select * from route r WHERE DATE(r.date) = current_date  + interval '1 days';
 Result:
![image](https://github.com/user-attachments/assets/0b2c5fd1-2e14-461a-be9d-1d2ef86b0c0e)

### DBeaver Version

Community Edition 24.2.0.202409011551

### Operating System

Windows 10 home

### Database and driver

psql (PostgreSQL) 13.2

**Comment by ShadelessFox** [comment]
Hello @Amitkad,

When you select a block of text containing multiple queries and hit **Ctrl+Enter**, DBeaver submits that entire blob to the driver, which in turn sends it to the database. Depending on a particular database/driver, it might be handled differently. The most problematic part is the metadata of the result set. Under some circumstances, DBeaver cannot correlate that metadata with the actual structure of the database, which is required for providing features like data editing, reference navigation, etc.

To work around this, you can execute each query separately using **Ctrl+/** or execute the entire script using **Alt+X** - DBeaver will submit each query separately.

TL;DR: Use **Alt+X** to execute multiple queries.
