### ISSUE TITLE
Add "Go Back" Navigation Feature in DBeaver

### ISSUE THREAD

**Issue by msmsadegh** [dbeaver/dbeaver#36257]
# Feature Proposal: "Go Back" Button for Table Navigation

## Problem Statement:
DBeaver offers seamless navigation between related tables when clicking on foreign key IDs or related fields. However, there is no feature to return to the previous table or context after navigating forward. This lack of a "Go Back" button or history navigation creates a less intuitive experience, especially when working with multiple interconnected tables.

## Proposed Solution:
Introduce a **"Go Back" Navigation Feature**, akin to a browser's back button. This feature will:
- Track the user's navigation path (e.g., table views, queries executed, etc.).
- Allow users to move backward and forward in their navigation history.
- Provide easy keyboard shortcuts and UI buttons for this functionality.

### Navigation History Stack:
- Maintain a stack-based navigation history in memory, recording each table or query the user navigates to.
- Each entry in the stack will include:
  - **Table Name**
  - **Query** (if applicable)
  - **Filters and pagination state**

### UI Elements:
- Add **"Back"** and **"Forward"** buttons in the toolbar or context menu.
- Implement keyboard shortcuts for ease of use (e.g., `Alt+←` for back, `Alt+→` for forward).

### Optional Configurations:
- Allow users to configure the navigation history limit in settings.
- Provide a navigation history panel (like a query history) for advanced use.

## Benefits:
- Enhances the user experience, especially when navigating complex relational databases.
- Saves time and reduces frustration for users who frequently jump between related tables.
- Improves the efficiency of data exploration workflows.

## Potential Challenges:
- Ensuring history tracking doesn't impact performance, particularly for large datasets.
- Handling complex scenarios like multiple tabs or simultaneous connections.

## Why This Matters:
This feature will greatly improve usability for data analysts, developers, and database administrators who work on intricate relational schemas. It aligns with DBeaver's goal of being a comprehensive and user-friendly database management tool.

**Comment by ShadelessFox** [comment]
Navigation history is available here:

![image](https://github.com/user-attachments/assets/73df2ba2-2c44-4082-abe7-7f2a389cb659)

Is that what you're looking for?
