### ISSUE TITLE
Refresh Problem 

### ISSUE THREAD

**Issue by ramrasi** [dbeaver/dbeaver#3626]
I m using Postgres DB.
I want to drop a column from a table. so i select a column press DEL key. Then press F5 for reverting all changes.

After Refresh Check the Deleted Column . It Will Displayed Double times...

![image](https://user-images.githubusercontent.com/6615196/41350918-5313aa18-6f32-11e8-9829-fb245f2413dd.png)

![image](https://user-images.githubusercontent.com/6615196/41350931-5e13718c-6f32-11e8-8d79-d5a12d4df899.png)

![image](https://user-images.githubusercontent.com/6615196/41350941-644f5a16-6f32-11e8-88c3-edda6edb8322.png)

**Comment by serge-rider** [comment]
F5 actually performs object refresh (changes revert is a side effect).

There was a bug in undo manager (command undo happened after object refresh).
Thanks for report

**Comment by ramrasi** [comment]
ok. Thanks
