### ISSUE TITLE
Error refreshing node

### ISSUE THREAD

**Issue by snowwalk** [dbeaver/dbeaver#36260]
### Description

When clicking refresh on the table view page, an error message will appear.
![image](https://github.com/user-attachments/assets/06397bcd-5a8e-4cb1-9dfe-4d8b3fa6dd65)

I checked the SQL statement that reported the error. 

`/* ApplicationName=DBeaver 24.2.5 - Metadata */ SHOW FULL TABLES FROM iyuu = 'cn_client'`
maybe replace '=' with 'like',it will be work

### DBeaver Version

CE 24.2.5.202411171748

### Operating System

Windows11 23H2

### Database and driver

mysql 8.0 & mysql 5.7
driver: mysql8

### Steps to reproduce

1. open table view
2. show table properties
3. click refresh button
4. you can see

**Comment by E1izabeth** [comment]
@snowwalk, thank you for the bug report.
As a workaround, you can turn ON the `Server side object filters` preference in `Preferences->Metadata`
![image](https://github.com/user-attachments/assets/04be7979-bcce-4004-9ebf-4cc93a313c52)
