### ISSUE TITLE
[PostgreSQL] Generate SQL Update/Insert don't quotes strings

### ISSUE THREAD

**Issue by luiseduardo** [dbeaver/dbeaver#3627]
- When column type is TEXT generate don't quotes string
- When column type is DOMAIN generate don't quotes string

Sql generated
------------------
UPDATE public.contrato
SET ctt_descricao_valores=<FONT COLOR="GREEN">**** Histórico de Cálculo *****</FONT>
       ctt_ajuste_manual=N
WHERE matricula='913682-99';

- field  ctt_descricao_valores type TEXT
- field ctt_ajuste_manual type flag_simnao
- flag_simnao is a PostgreSQL DOMAIN

System
----------------
- Dbeaver 5.1.0
- PostgreSQL 8.1
- Linux Mint 18.3
- Java(TM) SE Runtime Environment
- Java Version=1.8.0_171-b11

**Comment by serge-rider** [comment]
Can't reproduce. 
Make sure you are using "PostgreSQL" driver (not "PostgreSQL Generic"). 
The one with elephant icon.

**Comment by luiseduardo** [comment]
My driver config.

![dbeaver_driver_config](https://user-images.githubusercontent.com/938563/41409905-30bde57e-6fae-11e8-8086-22dd6b844295.png)

**Comment by serge-rider** [comment]
Ok.
What is your PostgreSQL server version?

**Comment by luiseduardo** [comment]
I tested in PostgreSQL 10 and works ;)

**Comment by uslss** [comment]
Cannot reproduce on 6.0.2.
