### ISSUE TITLE
Extra Leading and Trailing spaces in CVS export when the separated char is present in the data

### ISSUE THREAD

**Issue by rgerault** [dbeaver/dbeaver#3628]
Steps to reproduce:

1. select RPAD('|',10,'|') FROM dual;
2. Export this statement with such setting:
![image](https://user-images.githubusercontent.com/15523031/41352661-5def2510-6f1a-11e8-95c9-193d799f40de.png)
3. Expected result is a string of 10 pipes, get string of 10 pipes with leading and trailing spaces:
![image](https://user-images.githubusercontent.com/15523031/41352778-a012cece-6f1a-11e8-871b-d7a94f985348.png)

I made some test, if the separated char is not present in the data, there is no leading and trailing spaces:
![image](https://user-images.githubusercontent.com/15523031/41352874-e861c090-6f1a-11e8-9bc3-f317127f28b9.png)
![image](https://user-images.githubusercontent.com/15523031/41352917-0925c1c8-6f1b-11e8-8c13-83645ae43897.png)

**Comment by serge-rider** [comment]
Thanks for bugreport
