### ISSUE TITLE
DBeaver - Office support returns an error while saving data

### ISSUE THREAD

**Issue by Ranlod** [dbeaver/dbeaver#36281]
### Description

When exporting the data, I get this error
![dbeaver_JdKbkcqcAw](https://github.com/user-attachments/assets/2cef4ae0-4685-4450-9389-5e587f9e884d)

My hypothesis, in the new version of the extension, when saving to excel, sheet name is assigned the beginning of the SQL query that breaks the export if there are special characters. Example below
![изображение](https://github.com/user-attachments/assets/45930321-9941-427a-994a-545a7b8f75a4)
Export  `SELECT '111/11'` will broke also a process of export 

I would generally disable this change and let Excel create default sheet names as it has in past versions(Sheet 1,2,3 and etc)

### DBeaver Version

Community 24.2.5.202411171748

### Operating System

Windows 10 Pro

### Database and driver

Database: Snowlake
Driver: 
![picture](https://github.com/user-attachments/assets/03c6b51d-06d6-4883-b541-21dd8b9b23e0)

### Steps to reproduce

1. Connect to any base
2. run sql query `SELECT '111/11'`
3. try to export(will get the error)

Without special characters will work
1. Connect to any base
2. run sql query `SELECT '11111'`
3. try to export(will success)

**Comment by YoungEnch** [comment]
same error here, export failed 
![image](https://github.com/user-attachments/assets/5f909fd0-dc56-45c7-867c-4fa2f22c60a6)
please help to fix or update ASAP

**Comment by bossanova1986** [comment]
![image](https://github.com/user-attachments/assets/8d36ed6b-49e6-4258-a453-dea306614ef0)
same here

**Comment by Ranlod** [comment]
@bossanova1986 @YoungEnch 
For myself found a temporary crutch, just add 30 allowed characters before any query then the sheet in Excel will use these characters as the name of the sheet. For myself, I made a snippet that inserts 30 minuses before each query. In this case 30 first allowed characters will be used for the sheet name and the data will be exported normally. An example below
```sql
--------------------------------
SELECT '111/11'    
```
![picture](https://github.com/user-attachments/assets/0eb16882-607c-4777-9704-20b3677eb9da)
But basically, I do not understand why the developers began to fill the name of the sheet with the first characters of the request it has never been a problem when exporting, the default name of the sheet from excel all satisfied, who needs it manually renamed.

**Comment by E1izabeth** [comment]
Thank you for bug report.
