### ISSUE TITLE
[CUBRID] Missing some informations in Table DDL

### ISSUE THREAD

**Issue by longhaseng52** [dbeaver/dbeaver#36293]
### Description

Table DDL is missing REUSE_OID, COLLATE, and COMMENT information. Additionally, the maximum length for the VARCHAR data type is not specified.

### DBeaver Version

DBeaver version 24.2.1

### Operating System

Window 10

### Database and driver

1. Database Name and Version: CUBRID 11.2
2. Driver Name and Version: CUBRID JDBC Driver 11.2

### Steps to reproduce

1. Connect to Cubrid database
2. Select one of Cubrid table
3. Click on DDL tab

**Comment by kseniaguzeeva** [comment]
checked
