### ISSUE TITLE
Import of tsv only inserts odd numbered rows

### ISSUE THREAD

**Issue by jmax01** [dbeaver/dbeaver#36307]
### Description
Import of tsv only inserts odd numbered rows.

[FLAT_RCL_CLEAN.txt](https://github.com/user-attachments/files/17837211/FLAT_RCL_CLEAN.txt)

Of the ten rows, it inserts only the odd rows into this table:

```sql

CREATE TABLE "nhtsa_tsv_format_recalls" (
  "record_id" INTEGER NOT NULL,
  "camp_no" TEXT NOT NULL,
  "make_txt" TEXT,
  "model_txt" TEXT,
  "year_txt" TEXT,
  "mfg_camp_no" TEXT,
  "comp_name" TEXT,
  "mfg_name" TEXT,
  "bg_man" DATE,
  "end_man" DATE,
  "rcl_type_cd" TEXT,
  "pot_aff" INTEGER,
  "o_date" DATE,
  "influenced_by" TEXT,
  "mfg_txt" TEXT,
  "rc_date" DATE,
  "date_a" DATE,
  "rp_no" TEXT,
  "fmvss" TEXT,
  "desc_defect" TEXT,
  "consequence_defect" TEXT,
  "corrective_action" TEXT,
  "notes" TEXT,
  "rcl_cmpt_id" TEXT,
  "mfr_comp_name" TEXT,
  "mfr_comp_desc" TEXT,
  "mfr_comp_pt_no" TEXT
);
```

Settings:
![image](https://github.com/user-attachments/assets/2b959bd3-e6fe-4eca-a98d-9a09707a3d36)

Preview:
![image](https://github.com/user-attachments/assets/1e379af9-81ba-4c8b-a01c-86a33466882c)

Actual:
![image](https://github.com/user-attachments/assets/937ed499-ef44-41e1-bc1a-fa4942ec7b79)

Error Log:
```

!ENTRY org.jkiss.dbeaver.model 2 0 2024-11-20 16:07:07.100
!MESSAGE Cannot guess data type for column 'Column18', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2024-11-20 16:07:07.101
!MESSAGE Cannot guess data type for column 'Column19', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2024-11-20 16:07:07.101
!MESSAGE Cannot guess data type for column 'Column25', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2024-11-20 16:07:07.102
!MESSAGE Cannot guess data type for column 'Column26', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2024-11-20 16:07:07.102
!MESSAGE Cannot guess data type for column 'Column27', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2024-11-20 16:07:10.207
!MESSAGE Cannot guess data type for column 'Column18', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2024-11-20 16:07:10.208
!MESSAGE Cannot guess data type for column 'Column19', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2024-11-20 16:07:10.208
!MESSAGE Cannot guess data type for column 'Column25', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2024-11-20 16:07:10.209
!MESSAGE Cannot guess data type for column 'Column26', defaulting to VARCHAR

!ENTRY org.jkiss.dbeaver.model 2 0 2024-11-20 16:07:10.209
!MESSAGE Cannot guess data type for column 'Column27', defaulting to VARCHAR
```

### DBeaver Version

 24.2.5.202411171748

### Operating System

Sonoma 14.7.1 (23H222)

### Database and driver

Postgres 16.4 (RDS) PGJDBC 42.7.2

### Steps to reproduce

Attempt to load this file [FLAT_RCL_CLEAN.txt](https://github.com/user-attachments/files/17837211/FLAT_RCL_CLEAN.txt) into this table:
```sql

CREATE TABLE "nhtsa_tsv_format_recalls" (
  "record_id" INTEGER NOT NULL,
  "camp_no" TEXT NOT NULL,
  "make_txt" TEXT,
  "model_txt" TEXT,
  "year_txt" TEXT,
  "mfg_camp_no" TEXT,
  "comp_name" TEXT,
  "mfg_name" TEXT,
  "bg_man" DATE,
  "end_man" DATE,
  "rcl_type_cd" TEXT,
  "pot_aff" INTEGER,
  "o_date" DATE,
  "influenced_by" TEXT,
  "mfg_txt" TEXT,
  "rc_date" DATE,
  "date_a" DATE,
  "rp_no" TEXT,
  "fmvss" TEXT,
  "desc_defect" TEXT,
  "consequence_defect" TEXT,
  "corrective_action" TEXT,
  "notes" TEXT,
  "rcl_cmpt_id" TEXT,
  "mfr_comp_name" TEXT,
  "mfr_comp_desc" TEXT,
  "mfr_comp_pt_no" TEXT
);
```

With these settings:
![image](https://github.com/user-attachments/assets/2b959bd3-e6fe-4eca-a98d-9a09707a3d36)

**Comment by E1izabeth** [comment]
Please return back Quote char parameter in the importer settings
![image](https://github.com/user-attachments/assets/a46dcbaf-1cf9-4050-8925-3923bddd761e)

Why did you set it to empty string?

**Comment by jmax01** [comment]
The  _Quote char_  tooltip reads "_Character used to quote values_".

This data does not use `"` to quote values. 

Both the full data and the supplied sample have columns with quotes in the middle of the values and when attempting to import the entire file with the _Quote char_ set to `"` we had one type of exception and the import would fail at one location in the file and when we had the _Quote char_ set to `null` the import would fail at a different location in the file and with a different exception.

To identify those issues I began truncating the file until it wouldn't fail with an exception and then noticed the _odd-rows-only_ behavior.

Yes, it appears to work with the test sample if the _Quote char_  is set to `"`but that seems off given that the data doesn't use `"` for delimiting values. 

For completeness here is the same file with no quotes nested in values.  It behaves the same as the originally submitted file. 

Why would setting the _Quote char_ option have any impact on a file with no `"`s?
[FLAT_RCL_CLEAN_NO_QUOTES.txt](https://github.com/user-attachments/files/17849407/FLAT_RCL_CLEAN_NO_QUOTES.txt)

**Comment by jmax01** [comment]
I figured out the issue.

https://github.com/dbeaver/dbeaver/blob/d2187a3635445107034cf1f54b995320af1e9fd9/plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/importer/DataImporterCSV.java#L164

A null, or whitespace value gets defaulted to `'` as the _Quote char_, and since the sample data has a single quote in each row CSVReader gets confused and its line reader starts to return every other line

**Comment by jmax01** [comment]
Removing all single and double quotes from the file allowed the table to load.

**Comment by E1izabeth** [comment]
Thanks for the quick response and investigation.



>Why would setting the Quote char option have any impact on a file with no "s?

It's a good question. I would like to know the answer to this too. For now it looks like DBeaver bug for me.

**Comment by jmax01** [comment]
> Thanks for the quick response and investigation.
> 
> > Why would setting the Quote char option have any impact on a file with no "s?
> 
> It's a good question. I would like to know the answer to this too. For now it looks like DBeaver bug for me.

It is because it defaults to `'` so any rows that have single quotes are at risk.

In my case each row had a single `'` which lead to the skipping behavior
