### ISSUE TITLE
Formatter Error for Temporary Tables

### ISSUE THREAD

**Issue by benyanke** [dbeaver/dbeaver#3631]
On MS SQL servers, I have some queries which use tmp tables (formatted with a # at the start of the table name).

These get broken by the formatter. Additionally, `Use [db] Go` isn't handled correctly.

Test case:

## Input
```sql
USE [DBNAME] GO
CREATE TABLE #valTable (ID INT, Value VARCHAR(max));
INSERT INTO #valTable
VALUES (0,NULL),(1,'a val'),(2,'another val'),(3,'yet another val');

DROP TABLE #valTable;
```

## Output
```sql
USE [DBNAME] GO CREATE
	TABLE
		# valTable (
			ID INT,
			Value VARCHAR(max)
		);

 INSERT
	INTO
		# valTable
	VALUES (
		0,
		NULL
	),
	(
		1,
		'a val'
	),
	(
		2,
		'another val'
	),
	(
		3,
		'yet another val'
	);

 DROP
	TABLE
		# valTable;
```

The `#valTable` instances get turned into `# valTable`, which causes a query breakage.

Additionally, it would be better to change `USE [DBNAME] GO CREATE` to:

 ```sql
USE [DBNAME]
GO

CREATE [...]
```

However, the second issue is not a correctness issue, it's a formatting issue.

**Comment by serge-rider** [comment]
Issue with # fixed.
Formatting of GO (and any other keyword-like delimiter) was fixed.
Also formatting of brackets was fixed (made it less verbose) as a part of another SQL formatting ticket.

Thanks for bugreport.

**Comment by benyanke** [comment]
That was damn fast.

**Comment by benyanke** [comment]
Looks like a similar issue happens with the token `INTO` (as in `SELECT * INTO newtable FROM oldtable`) as did with `GO`. Is this an ok place to discuss or should I open a new ticket?
