### ISSUE TITLE
dBeaver issue on macOS:   a driver is needed, but  it didn´t install automatically

### ISSUE THREAD

**Issue by niesnec** [dbeaver/dbeaver#36318]
### Description

It´s a company Laptop. DBeaver is in our Selfservice Tool to install. You can open it, but the drivers will not install automatically so I can´t use DBeaver. And its not possible to install manuell a dbcd driver on this laptop.
<img width="696" alt="Bildschirmfoto 2024-11-21 um 18 00 08" src="https://github.com/user-attachments/assets/be6dcf7e-12e1-4bba-9036-d5d5b4987174">
<img width="1016" alt="Bildschirmfoto 2024-11-21 um 18 00 43" src="https://github.com/user-attachments/assets/5672549b-ed51-409b-91e4-e2abca70edb2">
<img width="1016" alt="Bildschirmfoto 2024-11-21 um 18 01 32" src="https://github.com/user-attachments/assets/fbe0de0a-d3ec-48eb-93cb-ab1c0c3090fe">

### DBeaver Version

24.2.5

### Operating System

macbook pro / mac OS Sequoia Version 15.1

### Database and driver

<img width="696" alt="Bildschirmfoto 2024-11-21 um 18 00 08" src="https://github.com/user-attachments/assets/f8f6c066-caa6-44ab-bf33-88bdf9d2eac7">

### Steps to reproduce

1. open ssh tunnel
2. try to connect Database. 
3.  direcly asking for the driver

### Additional context

we use ssh tunnel for the connection.

**Comment by E1izabeth** [comment]
Can you access https://repo1.maven.org/maven2/ from this PC?

**Comment by E1izabeth** [comment]
I'm closing this issue as it's been a while since there was an update.

**Comment by thaimin** [comment]
For MacOS 15 (Sequoia) that failed to download DB drivers directly in DBeaver due to "broken pipe" error, the solution is just add the line

> -Djava.net.preferIPv4Stack=true

in the file:

> /Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini
