### ISSUE TITLE
Can't connect to DB after restarting if setup the proxy

### ISSUE THREAD

**Issue by iFurySt** [dbeaver/dbeaver#36312]
### Description

If we set the proxy for a connection like this:

<img width="1075" alt="image" src="https://github.com/user-attachments/assets/ffdd5755-8c9c-4dc8-adf4-3205c0d81fb7">

We can connect to the DB after saving. But if we restart the DBeaver, we can't connect to it again.
<img width="819" alt="Xnip2024-11-21_20-07-02" src="https://github.com/user-attachments/assets/20a7ff69-989d-430d-a2db-e40756f8bb7d">

We need to edit the connection, switch to the proxy panel, and save it to reconnect to the database. I can reproduce the issue 100% on my end.

### DBeaver Version

Community Edition Version 24.2.5.202411171748

### Operating System

Sequoia 15.1

### Database and driver

1. MySQL 5.7
3. MySQL JDBC Driver MySQL 8.2.0 (I'm uncertain whether it is correct or not.)

### Steps to reproduce

1. Create a new DB connection to MySQL 5.7
2. Set a socks proxy for it
3. save it and confirm it can connect to DB successfully
4. restart DBeaver
5. connect failed
6. edit connection, switch to proxy panel and save it
7. it can connect to it successfully again.

**Comment by tzugen** [comment]
Yes, its very annoying to set the proxy on every start.

**Comment by smyoss** [comment]
Yep, 100% experiencing this issue. You just need to view the proxy settings and then it will connect, but it doesn't use the saved settings otherwise. Bascially, just open up the proxy settings before trying to connect.

**Comment by E1izabeth** [comment]
Thank you for bug report
