### ISSUE TITLE
DBeaver crashing with a certain SQL snippet

### ISSUE THREAD

**Issue by ernieIzde8ski** [dbeaver/dbeaver#36329]
### Description

While toying around with DuckDB, I found that executing this snippet causes DBeaver to crash:

```sql
CREATE OR REPLACE TABLE ProviderSupport (
	PhoneBrand varchar,
	PhoneModel varchar,
	PrimaryName varchar,
	Supported boolean not null,
	PRIMARY KEY (PhoneBrand, PhoneModel, PrimaryName),
	FOREIGN KEY (PhoneBrand, PhoneModel) REFERENCES Phone,
	FOREIGN KEY (PrimaryName) REFERENCES Provider(PrimaryName),
);
```

The crash began when I modified the last line (`REFERENCES Provider(PrimaryName)`), which is likely invalid, since `Provider` is a view table.

More context:

<details>

<summary> Full SQL file </summary>

I believe this issue should be reproduceable without an existing database.

```sql
DROP TABLE IF EXISTS ProviderSupport CASCADE;
DROP TABLE IF EXISTS ProviderSubsidiary CASCADE;
DROP TABLE IF EXISTS Phone CASCADE;
DROP TABLE IF EXISTS Brand CASCADE;

CREATE OR REPLACE TABLE Brand (
	Name varchar PRIMARY KEY,
	Comment varchar,
);

CREATE OR REPLACE TABLE OperatingSystem (
	Name varchar PRIMARY KEY,
);


CREATE OR REPLACE TABLE Phone (
	PhoneBrand varchar,
	PhoneModel varchar,
	OS varchar,
	RetailCost decimal(5, 2) CHECK (RetailCost >= 0),
	SupportsAnyGSM boolean,
	SupportsAnyLTE boolean,
	Comment varchar,
	PRIMARY KEY (PhoneBrand, PhoneModel),
	FOREIGN KEY (PhoneBrand) REFERENCES Brand,
	FOREIGN KEY (OS) REFERENCES OperatingSystem, 
);

-- https://en.wikipedia.org/wiki/List_of_mobile_network_operators_in_the_United_States#Facilities-based_service_providers
CREATE OR REPLACE TABLE ProviderPrimary (
	PrimaryName varchar PRIMARY KEY,
	SupportsGSM boolean,
	SupportsLTE boolean,
	SupportsNR boolean,
);

-- subsidiaries with identical support
CREATE OR REPLACE TABLE ProviderSubsidiary (
	PrimaryName varchar,
	SubsidiaryName varchar,
	PRIMARY KEY (PrimaryName, SubsidiaryName),
	FOREIGN KEY (PrimaryName) REFERENCES ProviderPrimary,
);

CREATE OR REPLACE VIEW Provider AS
	SELECT * FROM ProviderPrimary
UNION
	SELECT
		Subsidiary.SubsidiaryName,
		Main.SupportsGSM,
		Main.SupportsLTE,
		Main.SupportsNR,
	FROM
		ProviderPrimary AS Main
	JOIN
		ProviderSubsidiary AS Subsidiary
	ON
		Main.PrimaryName = Subsidiary.PrimaryName;

CREATE OR REPLACE TABLE ProviderSupport (
	PhoneBrand varchar,
	PhoneModel varchar,
	PrimaryName varchar,
	Supported boolean not null,
	PRIMARY KEY (PhoneBrand, PhoneModel, PrimaryName),
	FOREIGN KEY (PhoneBrand, PhoneModel) REFERENCES Phone,
	FOREIGN KEY (PrimaryName) REFERENCES Provider(PrimaryName),
);



-----

INSERT INTO Brand
	VALUES ('Nokia', null), ('Cricket', null), ('BLU', null);


INSERT INTO OperatingSystem
	VALUES ('KaiOS'), ('Android');

INSERT INTO Phone VALUES
	('Nokia', '6300 4G', 'KaiOS', 70.0, null, null, null);

INSERT INTO ProviderPrimary VALUES
	('AT&T Mobility', false, true, true,);

INSERT INTO ProviderSubsidiary VALUES
	('AT&T Mobility', 'FirstNet'),
	('AT&T Mobility', 'Cricket Wireless');
	
---

SELECT * FROM Provider;
```

</details>

- [hs_err_pid11210.log](https://github.com/user-attachments/files/17867856/hs_err_pid11210.log)
- [dbeaver-debug-1732266996950.log](https://github.com/user-attachments/files/17867875/dbeaver-debug-1732266996950.log)

### DBeaver Version

DBeaver 24.2.3.202411010813

### Operating System

Void 6.1.114_1 x86_64 AuthenticAMD notuptodate rrrmFFFFFFFFFFFFF

**Comment by ShadelessFox** [comment]
Hello @ernieIzde8ski,

The fatal log shows that the crash happened inside the DuckDB driver. Can you please tell me what driver version you are using?

Additionally, you can try updating to the latest version of the driver if there's one. You can do it this way:
1. Open your `Connection setting` and press `Driver settings`
![image](https://github.com/user-attachments/assets/b3cfaf1a-dc05-4bae-856b-4d0206d0dbbe)
2. Go to `Libraries` tab. select the driver artifact and press `Download/Update` 
![image](https://github.com/user-attachments/assets/0f8d65c3-989d-4549-bee3-3409a49cb181)
3. Select newer driver version in the list and press `Download`
![image](https://github.com/user-attachments/assets/0ff3641b-5a0e-44fb-803d-3eab24fa956c)
4. Press OK to close `Driver settings` window and try connecting again

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide the requested information.
