### ISSUE TITLE
Click to open and it will not respond and crash after installed of ARM(M3 pro) for macbook pro 

### ISSUE THREAD

**Issue by ItYunTeng** [dbeaver/dbeaver#36339]
### Description

Click to open and it will not respond and crash after installed of ARM(M3 pro) for macbook pro 

### DBeaver Version

24/3/0

### Operating System

Sonoma 14.4.1

### Database and driver

any databases

**Comment by E1izabeth** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. If there are any [Java fatal log files](https://dbeaver.com/docs/dbeaver/Log-files/#java-fatal-logs), please provide them too
Thank you.

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. If the issue is still present, please let me know and provide log files.
