### ISSUE TITLE
can not create a DB view / MS SQL Server

### ISSUE THREAD

**Issue by MichJud1974** [dbeaver/dbeaver#3633]
Hello,
I try to create a DB view on my MS SQL Server 2014.
**When I use right mouse button / context menu and select "new view" DBeaver version 5.0.3 creates an new empty table.**
Is this function not implemented or is this a bug?
Thank you very much for your support.

![dbeaver_create_view](https://user-images.githubusercontent.com/40256972/41392249-e5b042c4-6f9f-11e8-9e1f-9ac6cf5a87fa.jpg)
![dbeaver_create_view_table](https://user-images.githubusercontent.com/40256972/41392250-e5d16b5c-6f9f-11e8-9c8c-797497776fa2.jpg)

**Comment by michelvosje** [comment]
I just build the latest [develop version](3a70e792c08256bee91d90cfddf8eb54b26d9b6c) devleop version of DBeaver for Windows 10 x64 and i can reproduce this issue for the SQLite driver.

The PostgreSQL driver works fine for me.

**Comment by okartal** [comment]
Same problem here: on Ubuntu 18.04 using the latest DBeaver 5.2.5

**Comment by serge-rider** [comment]
View create/alter support will be added in the next version (5.3.3).
