### ISSUE TITLE
Broken default privileges in PostgreSQL

### ISSUE THREAD

**Issue by ivgag** [dbeaver/dbeaver#36334]
### Description

DBeaver doesn't show default privileges for roles. 

### DBeaver Version

CE 24.2.3

### Database and driver

PostgreSQL

### Steps to reproduce

1. Open the role editor
2. Grant default privileges to a role
3. Check given privileges

**Comment by kseniaguzeeva** [comment]
Verified for existing users. Separate tickets will be created for 1) new users and 2)user without a permission can change permission in UI without any errors
