### ISSUE TITLE
Variable with multiple value as a parameter

### ISSUE THREAD

**Issue by varundutt2002** [dbeaver/dbeaver#3634]
Hi Team,

I am trying to assign multiple values in a variable but getting the below error:
**Error**
Error Evaluating Expression

I am doing the assignment as below:
@set a = 1234, 5678;

My final query will be like:
select * from table where acc_num in (:a);

Please help me in getting the solution for this. Just wanted to add, currently I am trying to assign integer values but it can be text also.

Thanks and regards,
Varun Dutta

**Comment by serge-rider** [comment]
It is a bug in `@set` expression parser.
Thanks for report.

**Comment by serge-rider** [comment]
Currently the only workaround is to set value in parameter binding dialog
