### ISSUE TITLE
View Zipped Clob 

### ISSUE THREAD

**Issue by mehmetkurban** [dbeaver/dbeaver#36347]
Is it posible to make it view zipped clob data in dbeaver panel? ![IMG_20241125_105916.jpg](https://github.com/user-attachments/assets/fc80fe34-69b7-4232-aa63-3dd874a4acb8)

There are 4 options to view clob as you can see on picture. Maybe we can add zip option to view zipped data on dbeaver?

**Comment by ShadelessFox** [comment]
Hello @mehmetkurban,

What makes you think that column contains zip blobs? ZIP files have a particular signature at the beginning, and I don't see it.

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
