### ISSUE TITLE
Using ORA files not working

### ISSUE THREAD

**Issue by Yigitttttttt** [dbeaver/dbeaver#36344]
### Description

Hı, before I use connection file TNSNAMES.ORA and it's working flawless. But for new updates I can't get connections from files...

### DBeaver Version

24.2.3

### Operating System

windows 11

**Comment by ShadelessFox** [comment]
Hello @Yigitttttttt,

Can you please provide log files? You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by Yigitttttttt** [comment]
Hi, I tried 24.2.5 and it works now. Thank you. I'm closing this.
