### ISSUE TITLE
DBeaver launch problem after installing DBeaver Debugger 

### ISSUE THREAD

**Issue by nmalkam** [dbeaver/dbeaver#36346]
### Description

Dbeaver doesnt launch.
Logs are attached.
is it possible to delete extension???

DBeaver launch problem after installing DBeaver Debugger 

Link for bebugger: https://dbeaver.io/update/debug/latest/

Used this manual: https://www.rockdata.net/tutorial/dbeaver-debugger/

[.bak_1.log](https://github.com/user-attachments/files/17898744/default.bak_1.log)
[.log](https://github.com/user-attachments/files/17898747/default.log)

### DBeaver Version

24.1.5

### Operating System

windows 11

**Comment by nmalkam** [comment]
i will answer any questions and give ane possible information on you request

Have a good day))

**Comment by nmalkam** [comment]
is it possible to delete extension???
now i see only possibility to reinstall DBeaver

**Comment by nmalkam** [comment]
renaming the workspace folder to force DBeaver to create a new one upon next launch 
Doesn`t help


cant find plugin in folder C:\Users\user\AppData\Local\DBeaver\plugins

all files and folders was last changed on 18(or 19) of August 2024

**Comment by nmalkam** [comment]
solve launch problem with reinstalling DBEaver(after installing and deleting up to date version)

now i cant use debug via unknown problem: got another problem with fonts(
�����: ������� ����� ����������� � �� "XXXXXXXXXX"
�����: ������� ����� ����������� � �� "XXXXXXXXXX"
)

**Comment by ShadelessFox** [comment]
Thanks for the bug report

**Comment by nmalkam** [comment]
> Thanks for the bug report

Now i see that error with Replacement Characters occurs when i open more than two sql files with **one active connection**

**Comment by ShadelessFox** [comment]
I'm kind of lost. Did you manage to install the plugin since you're facing a seemingly different issue now?

**Comment by ShadelessFox** [comment]
There were no any updates in a while. Please let me know if the issue is still actual.
