### ISSUE TITLE
Default privileges in PostgreSQL for new users aren't displayed in UI

### ISSUE THREAD

**Issue by kseniaguzeeva** [dbeaver/dbeaver#36355]
### Description

CE: granted priveleges aren't visible in UI

### DBeaver Version

Version 24.3.0.202411250716

### Operating System

Win11

### Database and driver

PostgreSQL

### Steps to reproduce

1. Open a database, go to roles, create a new one and don't press Savr in the opened dialog
2. Go to Permissions tab, click Tables folder and grant some Permissions
3. Save changes

AR:
CE: granted permissions aren't visible

https://github.com/user-attachments/assets/36eba58e-e3e2-4a6d-a5a5-23242232733b

EE:  granted permissions are visible after dialog reopening

https://github.com/user-attachments/assets/96b30046-b68d-43fb-90d4-552caadc9d1c

**Comment by MashaKorax** [comment]
CE -  permissions are visible after refreshing node roles


https://github.com/user-attachments/assets/f50630d2-1fac-47e1-9c8b-60cc6d0fd6f8

**Comment by MashaKorax** [comment]
verified
