### ISSUE TITLE
Invalidate and Reconnect to SQLITE don't update the table

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#36359]
### Description

When a SQLITE database changes outside DBeaver, the "Invalidate and Reconnect" command don't update the database to the new changes

### DBeaver Version

Version 24.2.4.202411101307

### Operating System

Arch Linux

### Database and driver

SQLite

### Steps to reproduce

1. Open a SQLite database
2. Change it outside DBeaver (for instance, delete a row)
3. Invalidate and Reconnect to the database
4. The changes are not reflected within DBeaver

**Comment by ghost** [comment]
Also clicking on "Refresh" on the connection doesn't refresh the tables. You need to refresh the tables one by one

**Comment by ghost** [comment]
Even refreshing the single table is not reliable. The only reliable way to update the database is to disconnect
![image](https://github.com/user-attachments/assets/32efb17f-556b-4b73-b577-b28a2dea2302)

**Comment by ShadelessFox** [comment]
Hello @10b14224cc,

SQLite is not intended to be used simultaneously; doing so might corrupt the database. This is how SQLite works, and it has nothing to do with DBeaver.
