### ISSUE TITLE
Snap of DBeaver?

### ISSUE THREAD

**Issue by benyanke** [dbeaver/dbeaver#3636]
Would you be open to a snap of dbeaver? If you're not aware, snap is a cross-distro packaging format that allows fully contained (similar to docker) installs of software, and rolling updates. More and more distros are starting to roll out snaps, so it would allow you to grow there.

I'd be willing to help contribute the snap config files and integrate them into travis, if you'd be interested.

Here's some guides as well:

## Snaps and TravisCI

https://tutorials.ubuntu.com/tutorial/continuous-snap-delivery-from-travis-ci?backURL=https://docs.snapcraft.io/build-snaps/ci-integration&_ga=2.220818896.918861794.1528983507-358744099.1527883523#0

## Snaps and Java
https://docs.snapcraft.io/build-snaps/java

**Comment by serge-rider** [comment]
Looks like dup of #2299
Anyhow thanks for additional info. We'll try to make it real till 5.2

**Comment by benyanke** [comment]
Indeed a dupe. Thanks!
