### ISSUE TITLE
导出json数据格式错误

### ISSUE THREAD

**Issue by dujiecn** [dbeaver/dbeaver#36365]
### Description

表里的一个字段存储的是json字符串，导出为sql文件的时候会把json字符串的引号忽略，导致json格式解析出错

### DBeaver Version

1

### Operating System

1

### Database and driver

1

### Steps to reproduce

1

### Additional context

1

**Comment by ShadelessFox** [comment]
Please create a new issue in English and provide the steps required to reproduce the issue, along with information about the database.
