### ISSUE TITLE
MySQL add column for char is not enclosing default value in quotes when using 

### ISSUE THREAD

**Issue by cnizzardini** [dbeaver/dbeaver#3637]
MySQL add column for char is not enclosing default value in quotes when using UI. 

Generates: 

`ALTER TABLE crs_admin2.organization ADD currency char(3) DEFAULT USD NOT NULL;`

instead of 

`ALTER TABLE crs_admin2.organization ADD currency char(3) DEFAULT 'USD' NOT NULL;`

Version: 5.7.22-0ubuntu18.04.1
DBeaver Version: 5.0.4

**Comment by serge-rider** [comment]
Quotation of default values was removed in #108
This seems to be more consistent approach (as you can use expressions in default values). You should specify default value in quotes if you need just string literal.
