### ISSUE TITLE
data is not fetched based on the where clause

### ISSUE THREAD

**Issue by filiepvw68** [dbeaver/dbeaver#36375]
### Description

![2024-11-26 13_21_25-Greenshot image editor](https://github.com/user-attachments/assets/be33d015-1045-4d8e-b20e-e38635088189)

when i query this data in any other way i see the record for OrdernNo SO-10270, when i query the table without "where" clause and order the results i see the line for SO-10270 as well. Tying to make it "like" doens't help either.  
Neither is the record shown if i query on any other of the fields.

### DBeaver Version

24.1.4.202408041450

### Operating System

windows 11

### Database and driver

SqlExpress

### Steps to reproduce

connect to the database
execute query SELECT * FROM MPM.vyncke.ProductionOrder PO WHERE po.OrderNo = 'SO-10269' 
no result is shown.
in any other database viewer i get a result line.

### Additional context

![2024-11-26 13_28_17-Connection _MPM vyncke _ configuration](https://github.com/user-attachments/assets/a62c61c7-1424-42be-a90c-fb5f8797db4a)

**Comment by E1izabeth** [comment]
Could you do the following actions? It will help us understand your issue
1. Open Query Manager
![image](https://github.com/user-attachments/assets/f505f676-a578-4af2-a786-ba6c1273c17f)

2. Turn on showing all types of queries 
![image](https://github.com/user-attachments/assets/8065c206-dad8-4457-b597-daeb1c2f0616)

3. Clear log
![image](https://github.com/user-attachments/assets/c7d94ecb-83d9-4684-8862-01ffb182a39e)

3. Reproduce the issue once again

4. Check if you see the query that you execute as expected and let us know

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide requested information.
