### ISSUE TITLE
Feature request: Export resultset plain text format

### ISSUE THREAD

**Issue by ericblais** [dbeaver/dbeaver#3638]
It would be great to Export the Resultset to a plain text format.
Just like the one we get when opting to view the Results in Text instead of Grid.

![image](https://user-images.githubusercontent.com/40277078/41433255-501bf50e-6fe6-11e8-9429-68ab86a9fd59.png)

**Comment by serge-rider** [comment]
Will be added in 5.1.5

**Comment by ericblais** [comment]
Thanks a lot @serge-rider !
