### ISSUE TITLE
Where can I find an explanation of all the UI icons?

### ISSUE THREAD

**Issue by watery** [dbeaver/dbeaver#3639]
I'm using the ER tool to analyze an existing database and would like some kind of cheat-sheet for all the different icons I may find in the rendered schema.

Is there anything like that?

**Comment by serge-rider** [comment]
ERD itself contain only table/view icons and column icons (which are different for different column data types).
Additional info is here: https://github.com/dbeaver/dbeaver/wiki/ER-Diagrams
