### ISSUE TITLE
SQL Editor: keep database and schema after disconnect

### ISSUE THREAD

**Issue by kseniaguzeeva** [dbeaver/dbeaver#36405]
### Description

When SQL Editor for Snowflake has a selected schema, it disappears from the selector after disconnecting and connecting again (it doesn't happen with invalidate tool)

### DBeaver Version

DBeaver CE 24.3.0 ea

### Operating System

Win11

### Database and driver

Snowflake

### Steps to reproduce

1. Connect to Snowflake, open SQL Editor and select a schema in it, execute a selelect query
2. Disconnect from the database
3. Connect again

AR: the schema disappears from the top toolbar, the query can't be executed again because of missed schema
ER: the selected schema is restored after connect, the select query can be executed for it

Note: PostgreSQL and Cockroach keep the database, but change a custom schema on public in the same case.

**Comment by E1izabeth** [comment]
Highlighting is broken after that until you manually set the schema.

**Comment by E1izabeth** [comment]
It is reproducible only when `Open separate connection` is set to `false` for SQL Editor. It seems to have always worked this way. I checked 21.3.0, and the behavior is the same there.

**Comment by E1izabeth** [comment]
Also it's reproducible only when schema is not set in the connection configuration

**Comment by E1izabeth** [comment]
We decided that it's not the bug

**Comment by HocKu7** [comment]
> Also it's reproducible only when schema is not set in the connection configuration

And the default schema "PUBLIC" doesn't exist
