### ISSUE TITLE
Update OrientDB driver

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#36401]
### Description

I can't connect to the latest OrientDB server with the default driver because version 1.7 is too old.

### DBeaver Version

DBeaver 24.3.0

### Steps to reproduce
1. Download portable database version from https://orientdb.org/download
![image](https://github.com/user-attachments/assets/e652a567-381a-4fd6-947c-21809d8cbebc)
2. Extract files from the archive
3. Run server `.\server.bat` or `.\server.sh` from the `bin` directory and set the default password for the `root` user. See more here http://orientdb.org/docs/3.0.x/gettingstarted/Tutorial-Run-the-server.html#starting-the-database-server
4. Open DBeaver and create a new connection to OrientDB
![image](https://github.com/user-attachments/assets/4b8b73b3-1e46-4501-be1d-e1d79f82c93a)

5. Press the `Test Connection ...` button - the connection fails due to the driver error.
6. Stop the server http://orientdb.org/docs/3.0.x/gettingstarted/Tutorial-Run-the-server.html#stop-the-server

**Comment by MashaKorax** [comment]
verified
