### ISSUE TITLE
Bind parameter(s) popup panel always shows

### ISSUE THREAD

**Issue by MocniMax** [dbeaver/dbeaver#3640]
Hello,

As soon as I use any host variable in my query, the Bind parameter(s) popup panel is show even if @set is used to define a host variable value. 
Any chance to avoid it?

I am using latest Dbeaver UDM 5.1.0 on MSWindows

Regards,

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/43732907-97e82084-99bb-11e8-83c0-f0fca38682cc.png)

**Comment by serge-rider** [comment]
If all parameters are set then this dialog won't be shown.
