### ISSUE TITLE
Postgres: Server side 'limit' not applied when ordering by columns in Table->Data view

### ISSUE THREAD

**Issue by TimNZ** [dbeaver/dbeaver#3641]
v5.1.0, OS X

'limit <rows>' is not applied when ordering on Postgres table.
Appears to work with mysql.

You can see the queries in the Query Manager, no limit applied.

Am I not understanding how ordering should work, or a bug?

<img width="895" alt="screen shot 2018-06-17 at 1 00 13 pm" src="https://user-images.githubusercontent.com/1051701/41503719-0ee08ee2-722f-11e8-907a-b6c1f75ae323.png">

**Comment by TimNZ** [comment]
mysql

<img width="895" alt="screen shot 2018-06-17 at 1 00 13 pm" src="https://user-images.githubusercontent.com/1051701/41503739-83e7bd6e-722f-11e8-8b63-96e49ae41ecf.png">

**Comment by serge-rider** [comment]
This is configurable: 
![image](https://user-images.githubusercontent.com/6398845/41506206-3895e3c0-7222-11e8-9eb8-9007877f0745.png)

This option can be configured globally of for specific connection(s).

**Comment by TimNZ** [comment]
@serge-rider awesome thanks. 

It was on for the Postgres connection. 
Turned it on and off on global, and now stays applied.
