### ISSUE TITLE
Build from sources wiki: incorrect build path

### ISSUE THREAD

**Issue by anton-erofeev** [dbeaver/dbeaver#36418]
### Description

https://github.com/dbeaver/dbeaver/wiki/Build-from-sources#build-steps
in build steps the following steps are specified -

1. git clone https://github.com/dbeaver/dbeaver.git 
2. cd dbeaver
3. run build.cmd or ./build.sh

this assumes the script is in the root folder of the project, however it is in the [tools](https://github.com/dbeaver/dbeaver/tree/devel/tools) folder

### DBeaver Version

24.2.5

### Steps to reproduce

open https://github.com/dbeaver/dbeaver/wiki/Build-from-sources#build-steps

**Comment by E1izabeth** [comment]
Thanks for the bug report. We'll fix it
