### ISSUE TITLE
Vertical editing and brackets auto close

### ISSUE THREAD

**Issue by georgethemarmot** [dbeaver/dbeaver#3642]
DBeaver 5.1.0 Standalone on Windows 10 64bit
During Vertical selection (Alt+Shift+A)
if a bracket is typed the autoclose feature will wipe all the rows in the selection.
Correct behaviour should be to suggest brackets on all the lines OR not suggest at all.
The issue is not present if the Autoclose feature is disabled in Preferences.

**Comment by serge-rider** [comment]
Not sure I understood this use-case. Could you post some screenshot/video?

**Comment by georgethemarmot** [comment]
Vertical Selection (Alt+Shif+A)
![1](https://user-images.githubusercontent.com/4931142/41665982-b0cacf16-74a9-11e8-8fd9-536a2a4335a3.png)

'b' input
![2](https://user-images.githubusercontent.com/4931142/41666026-ce45930a-74a9-11e8-8bd8-180f82a03b13.png)

'(' input
![3](https://user-images.githubusercontent.com/4931142/41666042-d8dff5c6-74a9-11e8-9af7-0079f3472620.png)

As you can se after the '(' Input all lines for the exception of the first are wiped.

**Comment by serge-rider** [comment]
Thanks for details. It is a bug and it'll be fixed in the next version.

**Comment by serge-rider** [comment]
This seems to be not completely fixed. 
Extra fix was added in 2602.
