### ISSUE TITLE
Can't connect to Oracle or Snowflake jdbc errors downloading drivers

### ISSUE THREAD

**Issue by ftironectidata** [dbeaver/dbeaver#36435]
### Description

Can't connect to Oracle or Snowflake

Maven artifact 'com.oracle.database.jdbc:ojdbc11:RELEASE' cannot be resolved in external repositores

Maven artifact 'net.snowflake:snowflake-jdbc:RELEASE' cannot be resolved in external repositores

### DBeaver Version

Community Edition 24.3.0

### Operating System

Windows 10 Enterprise

### Database and driver

Oracle jdbc 23.2
Snowflake jdbc 3.14.4

### Steps to reproduce

1. Try to connect to DB
2. Try download drivers
3. Error

**Comment by HocKu7** [comment]
@ftironectidata Did you check connectivity to maven repository? Maybe your network has some restrictions. If the connectivity is present, so please send the log files. You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by ftironectidata** [comment]
Hi Ruslan,
I can connect to the Maven repository via a web browser.
[cid:9cc8937a-c648-4b56-bc2a-1c8f9fab2e19]
Please take a look at the attached log.

**Comment by ftironectidata** [comment]
Hi Team,
Any update?

**Comment by E1izabeth** [comment]
Hi, @ftironectidata!
Unfortunately, GitHub can't attach files when you answer by email, so we don't see the files you sent. Can you please go to GitHub and attach them there?

**Comment by E1izabeth** [comment]
Also, are you under the firewall or in a corporate environment? Can you open https://repo1.maven.org/maven2/ in the web browser?

**Comment by ftironectidata** [comment]
Hi @E1izabeth,

I can open https://repo1.maven.org/maven2/ in the web browser. See the attached screenshot and DBeaver log.

Thanks!
[dbeaver Error Log 202412051109.log](https://github.com/user-attachments/files/18138007/dbeaver.Error.Log.202412051109.log)

![Screenshot 2024-12-14 174424](https://github.com/user-attachments/assets/9ca3275b-a9eb-4dd2-afb7-d67c939c3289)

**Comment by ftironectidata** [comment]
Hi @HocKu7,

See my previous comment to @E1izabeth.

Thanks!

**Comment by Nododot** [comment]
Same issue here on Windows with a fresh install of DBeaver

Edit: I could fix the issue by setting the proxy and restarting DBeaver

**Comment by ShadelessFox** [comment]
Hello @ftironectidata,

Can you try turning off the following option, restarting DBeaver, and downloading drivers again?

![Image](https://github.com/user-attachments/assets/f8285cbc-1302-4de4-bab7-6d4982031831)

**Comment by ftironectidata** [comment]
That worked!
Thanks!

**Comment by ShadelessFox** [comment]
Thanks for a quick follow-up. I assume the ticket can be closed now.

Note: this might have been caused by outdated certificates installed on your operating system.

**Comment by adipati27ma** [comment]
This helped me to, thanks!!
