### ISSUE TITLE
Incorrect description in the navigator for connections with an SSH profile

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#36447]
### Description

The decription in the navigator that shows the host for the connection is incorrect after restart

### DBeaver Version

24.3.0

### Operating System

Any

### Database and driver

Any

### Steps to reproduce

1. Open connection settings or start creating a new connection
2. On SSH tab select any profile with a remote host
3. Save th connection
4. Check that remote host is correctly shown in the navigator
5. Restart DBeaver
6. Check connection in the navigator again

**Expected:** The host is the same in the navigator
**Actual:** Host is replaced with localhost from the **Main** tab of the settings. It will change to correct again only after opening settings, switching to SSH tab and saving.

### Additional context

Correct SSH credentials are still used, only the discription in the navigator is incorrect

![dbeaver_KQpnBBXlNf](https://github.com/user-attachments/assets/54edeae4-f8aa-4efe-bdea-7224b2b6fb16)

**Comment by MashaKorax** [comment]
verified
