### ISSUE TITLE
Show tablespace for materialized views

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#3644]
This is a feature request: Even though materialized views are supported in DBeaver and materialized views behave very much like normal tables, the properties list of the materialized views misses some crucial stuff that can be viewed in PgAdmin.

Specifically, I would be interested to see the tablespace listed.

**TABLE:**
![afbeelding](https://user-images.githubusercontent.com/7635726/41509510-50e92ad0-7255-11e8-8079-fce55ca69909.png)

**MATERIALIZED VIEW:**
![afbeelding](https://user-images.githubusercontent.com/7635726/41509490-df43b2ba-7254-11e8-89ef-5ef97a03670a.png)

**Comment by serge-rider** [comment]
Good point.
Materialized view tablespace view/edit will be added in the next version. Also comment edit will be fixed.

IF you know some other materialized view properties which must be there - pelase tell.
