### ISSUE TITLE
Export to Excel Issue

### ISSUE THREAD

**Issue by Sekman-Umut** [dbeaver/dbeaver#36452]
### Description

When trying to export tables with more than 1M records to Excel, it only exports the first 1M records, but there are more records in the table.

### DBeaver Version

DBeaver Community 24.3

### Operating System

macOS Sequoia 15.1.1

### Database and driver

database:bigquery  driver: com.simba.googlebigquery.jdbc42.Driver

### Steps to reproduce

<img width="625" alt="image" src="https://github.com/user-attachments/assets/16a51526-6655-48ac-b33f-19ece4fa2242">

<img width="332" alt="image" src="https://github.com/user-attachments/assets/e8aeb1f0-08f3-4cea-b3f2-98ea34e29097">

<img width="563" alt="image" src="https://github.com/user-attachments/assets/ed6b5594-2ff6-4cd2-aa15-5127fa6d43a1">

<img width="679" alt="image" src="https://github.com/user-attachments/assets/d7df2aae-973c-4b2d-abeb-f66f58ce0c0f">

Export only first 1.048.575 rows .

I changed Max row on sheet limit but the result did not change. I tried also EA version but it didn't work.

**Comment by ShadelessFox** [comment]
It's a limitation of Excel:
https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3

**Comment by Sekman-Umut** [comment]
I know the limitation but in the old versions it would open a new page and continue.

**Comment by E1izabeth** [comment]
@Sekman-Umut do you remember the previous version you used, when it worked?

**Comment by ShadelessFox** [comment]
It's a regression caused by #36125

**Comment by wcbspp** [comment]
确实是这样 旧版本会打开新的SHEET继续导出
这个问题会修复么
