### ISSUE TITLE
Azure Active Directory Login

### ISSUE THREAD

**Issue by Xtinction** [dbeaver/dbeaver#3647]
Hey guys & gals,

I was wondering if it was currently possible to log in to an SQL server database using Azure AD credentials. I've not been very successful and my employer might force me to start using SSMS, eek!

Am I missing something or is AAD login not currently supported?

Thanks in advance!
Jaap

**Comment by serge-rider** [comment]
Generally this should work.
Check this instructions: https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-2017

Note: you need to use the most recent Microsoft driver (not jTDS)

**Comment by Xtinction** [comment]
Hey Serge, thanks a lot for your suggestion.

I've been trying to get it to work using the password authentication, but I keep running into a brick wall. 

Here's what I did:

I installed the latest (6.4) version of the JDBC driver from MS.

On the Driver properties page:
I set authentication to "ActiveDirectoryPassword"
I set encrypt to true
I set HostNameInCertificate to "*.database.windows.net"
I set the server name and database properly
I used my Azure AD account credentials to connect

Tring to connect to the server gives me this SSL error:
Failed to validate the server name in a certificate during SSL initialisation.

The only way of passing this error is by switching "TrustServerCertificate" to True, but that gives me other errors instead.

Do you have any idea why this might be happening? I'm at a loss :(

**Comment by Xtinction** [comment]
No need to answer this one anymore Serge, I got a colleague better versed in Java to help me out and we have it working now. I will post an update as soon as I have documented the solution.

**Comment by Xtinction** [comment]
Here's the guide we wrote to get it all working:

This section describes how to setup DBeaver to use the Active Directory credentials and how to configure a connection to access to an Analytics Framework database.
 

- Download and install the "Community Edition" version of DBeaver for the desired platform, from the Download section https://dbeaver.io/download/ (the instructions are based on the version 5.1.2 of DBeaver) 
- Start DBeaver and in the menu "Database", select the option "Driver manager" to start Active Directory capability setup 
- In the list of drivers, look and select the "Microsoft Driver" and edit it (button "Edit" at the right side of the window) 
- In the lower right part of the new screen, select "Add Artifact" to add the Active Directory artifact 
- In the new "Edit Maven Artifact" window, introduce the following data and press "OK": 

Group id: com.microsoft.azure 
Artifact Id: adal4j 
Classifier:  
Version: 1.6.0 
 

- Use the artifact pressing the "Download/Update" button at the right side of the dialog. 
- In the new dialog, confirm and press "Download" at the button right of the dialog. 
- Press "OK" at the bottom of the "Edit Driver" window to confirm and save the changes. 
- Close the "Driver Manager" window if it is still open. 
- With the driver configured to support the Active Directory authentication, the connection can be created. The instructions for it are as follows:  
- Create a new database connection ("Database" menu and "New Connection" option) 
- Look and select the "Microsoft Driver" and press "Next >" 
- Select the "Driver properties" tab at the top and update the values: 
- authentication: ActiveDirectoryPassword 
- trustServerCertificate: true 
- Go back to the "General" tab and introduce the connection information and credentials. 
- Press "Test Connection …" to verify the connection details are correct: 
- If the test doesn't succeed with a "connect" message, review the credentials (or ask for extra support) 
- If the test is succesful by saying  "connected", press "Next >"  
- No changes are required in the next two windows: press "Next >" and "Next >" again. 
- Set the name and a color for the connection created. 
- Press Finish, you're done!

**Comment by Raviteja2312** [comment]
@Xtinction Awesome!!! Steps are Crisp & Clear. It works 👍

**Comment by bsridharpatnaik** [comment]
@Xtinction Thanks. It worked.

**Comment by hastiAu** [comment]
I want to connect to db. to connect my database on azure data studio 
I do these steps but after all with test connection i receive this error:

The TCP/IP connection to the host com.microsoft.azure, port 1433 has failed. Error: "com.microsoft.azure. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".

how can I solve it?

**Comment by misi444** [comment]
For the next poor soul who gets stuck on this like I have for the past few hours:

The driver version seems to be critical. When I tried setting up DBeaver with the steps in @Xtinction's answer I kept getting the error message that the MSAL4J library failed to load. By default it was using version 9.3 of the mssql-jdbc driver. I reverted it to 8.2.2 (along with the mssql-jdbc_auth library) and it immediately started working.

**Comment by Xtinction** [comment]
Thanks for the comment. I think when I wrote the guide the latest version "just worked".

**Comment by MarcinGrinberg** [comment]
For anyone getting MSAL4J error and not wanting to revert to older version of driver, or in case it doesn't work for you.

Here is what I did:
Refer to https://github.com/dbeaver/dbeaver/issues/3647#issuecomment-405919517 
But instead of using adal4j artifactId I've used msal4j as a version you can try 1.11.0 - that's what worked for me along with mssql-jdbc in version 9.4.1.jre8.

Good luck!

**Comment by thummelt** [comment]
@MarcinGrinberg solution worked for me when getting MSAL4J error as well after executing all the steps from @Xtinction. putting both posts together gets it runnin 💯

**Comment by laddana-github** [comment]
After several timeout errors using MSAL4J and JDBC Driver 10.2, I too get the TCP/IP error. I am using Dbeaver 7.0.3. So 9 out of 10 times trying to test the connection, I get this timeout error :
**Request was throttled according to instructions from STS. Retry in 93486 ms.**

When it got past it, got this error :  **"The TCP/IP connection to the host xxxxxx.sql.azuresynapse.net, port 1433 has failed. Error: "connect timed out. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall."**.

**Comment by mariliab** [comment]
Following the instructions from [@Xtinction](https://github.com/dbeaver/dbeaver/issues/3647#issuecomment-405919517), these are the drivers that made it work for me (using DBeaver Version 22.1.1.202206261508, Mac OS 11.6.4 M1 chip):

Group id: com.microsoft.azure
Artifact id: msal4j
Version: 1.12.0

Group id: com.microsoft.sqlserver
Artifact id: mssql-jdbc
Version: 10.2.0.jre8

**Comment by laddana-github** [comment]
I had to uninstall Dbeaver 7 which was latest in April 2020. Don't know if they renumbered the versions, but current one was 22, so installed that.
With that, everything including the 2 drivers were downloaded by Dbeaver and it worked with Active directory user name and password authentication.

**Comment by EfficiencyGeek** [comment]
> For anyone getting MSAL4J error and not wanting to revert to older version of driver, or in case it doesn't work for you.
> 
> Here is what I did: Refer to [#3647 (comment)](https://github.com/dbeaver/dbeaver/issues/3647#issuecomment-405919517) But instead of using adal4j artifactId I've used msal4j as a version you can try 1.11.0 - that's what worked for me along with mssql-jdbc in version 9.4.1.jre8.
> 
> Good luck!

This worked for me.  DBeaver Community Version 23.3.0.202312031432. mssql-jdbc v9.2.0. msal4j 1.11.0.

Thanks

**Comment by hobbes1069** [comment]
I'm trying to accomplish the same thing, but it's a postgres server (Flexible server) in Azure

**Comment by Acuity-Nate** [comment]
Apparently, it is really important that you have the correct versions together. You'll have to search for which msal4j driver works with your jdbc driver.

<img width="784" height="306" alt="Image" src="https://github.com/user-attachments/assets/d10b1c58-fcb2-49ba-b84d-1b5255bcc6a6" />
