### ISSUE TITLE
Tab menus  for SQL's -- cannot allways rename tabs

### ISSUE THREAD

**Issue by selster1** [dbeaver/dbeaver#36483]
### Description

Sometimes, when I am writing sql code and create a new sql tabl, I cannot rename it. 
![image](https://github.com/user-attachments/assets/1ac4d31f-65e8-4e28-a670-2f0332910ad3)
Of course, other times I can rename SQL tabs,
![image](https://github.com/user-attachments/assets/918916aa-0e9f-4f7f-9369-6954af8cceae)
In this instance, dbeaver will allow me to rename the above, but not the 4 other tabs. Thanks so much selster!

### DBeaver Version

Community Version 24.2.2.202410061621

### Operating System

win 10 64 bit

### Database and driver

latest I think

### Steps to reproduce

1. work in dbeaver
2. create a new sql tab
3. try to rename it
4. maybe it works the first time
5. but the second time, maybe not
6. other tabs can be renamed, at any time.

### Additional context

na

**Comment by HocKu7** [comment]
Hi @selster1. If you catch it again, please describe what happened before the bug. Currently, it is hard to reproduce. Thank you for your report!

**Comment by ask9** [comment]
This has already been reported here: #34429
To reproduce it, open sql-file located out of the standard workspace-folder.
For example, from desktop.

**Comment by E1izabeth** [comment]
Thanks, @ask9! You help a lot.
I'm closing it as it's a duplicate.

If you want to be notified about updates on this issue, you can subscribe to #34429.
