### ISSUE TITLE
Error in building IDEA project

### ISSUE THREAD

**Issue by openai0229** [dbeaver/dbeaver#36488]
### Description

I want to build this project to run in IDEA, but when I execute the `./generate_workspace. sh` script, it prompts me with the following error
<img width="781" alt="image" src="https://github.com/user-attachments/assets/32b36431-e21b-4beb-9ad6-8e220bf723d9">

### DBeaver Version

latest

### Operating System

macOS 15.1.1

**Comment by openai0229** [comment]
<img width="1339" alt="image" src="https://github.com/user-attachments/assets/4671fbe4-f517-42fe-b91e-1b5fb7225d6d">

**Comment by ShadelessFox** [comment]
As of now, you have to clone https://github.com/dbeaver/dbeaver-jdbc-libsql as well

**Comment by openai0229** [comment]
I seem to have successfully started, I can see the client, but there are the following error messages
<img width="1802" alt="image" src="https://github.com/user-attachments/assets/e143116c-79e3-4c7d-8679-7e38d15a8dc1">

**Comment by ShadelessFox** [comment]
Try removing the generated workspace and run the generator again

**Comment by EastLord** [comment]
<img width="991" alt="image" src="https://github.com/user-attachments/assets/de22f222-2e4b-4a9c-b725-bafd39d3a8ae">
@ShadelessFox

**Comment by Destrolaric** [comment]
@openai0229 @EastLord Issues should be fixed now.

**Comment by openai0229** [comment]
👌
