### ISSUE TITLE
New autocomplete doesn't show identifiers with underscores (unlike the old autocomplete)

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#36480]
### Description

I like the behaviour when underscore can be ignored when typing a query and autocomplete still suggests me table names and column names containing underscores.
The issue with new autocomplete is that it doesn't show me these table names and column names.

STR
- start typing the query in dvdrental database, then press Ctrl + Space:
```
select * 
from filma
```

**expected**: film_actor is suggested (underscores are ignored)
**actual**: no suggestions in new autocomplete, but there is a suggestion in old autocomplete

new autocomplete: 

https://github.com/user-attachments/assets/edf55074-25b3-4eb5-94b5-c60135749db6

old autocomplete: 

https://github.com/user-attachments/assets/78b8db4b-769d-457b-97a9-95907a1a6d64

### DBeaver Version

Enterprise Edition 24.3.1-202411300022

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by E1izabeth** [comment]
Thanks for bringing our attention to it.
