### ISSUE TITLE
Error at startup 

### ISSUE THREAD

**Issue by lenin-inzunza** [dbeaver/dbeaver#36495]
### Description

When I start the application, I get an error, and it does not go beyond that step.
This error occurred after updating the application

![dbeaver_233631334](https://github.com/user-attachments/assets/e635f17e-d472-4281-a45a-26c6e929f64e)

I already did a clean install and still, the same error is still coming up.

Regards

### DBeaver Version

Community Edition 24.3.0

### Operating System

Windows 11 Pro 24H2

**Comment by ShadelessFox** [comment]
Can you please provide log files? You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by lenin-inzunza** [comment]
Which file of all? Because when I open the application, it does not start and does not generate any error file.

- The .log file is dated December 8
- The dbeaver-debug.log file is dated December 8

[.log](https://github.com/user-attachments/files/18069284/default.log)
[dbeaver-debug.log](https://github.com/user-attachments/files/18069285/dbeaver-debug.log)

When creating this comment, I tried to open the application, and it did not update any of the files I just attached.

![152928148](https://github.com/user-attachments/assets/94b2e66e-bc19-4910-b241-c3974f00b231)

Regards

**Comment by ShadelessFox** [comment]
Did you install it from the Windows Store?

**Comment by lenin-inzunza** [comment]
No, installed from option Windows (installer)

**Comment by E1izabeth** [comment]
Please try downloading the latest DBeaver version here: https://dbeaver.io/files/ea/ and install it again. Does it help?

**Comment by lenin-inzunza** [comment]
No, same error. 
![dbeaver](https://github.com/user-attachments/assets/9b84c0a2-8c3e-4be8-aafa-04620b9e4107)

**Comment by E1izabeth** [comment]
I see. Thanks

**Comment by E1izabeth** [comment]
Could you try downloading the portable distribution (zip), extracting it to the C disk, and running DBeaver?

**Comment by lenin-inzunza** [comment]
After searching and trying several things to find the reason for the error, apparently it was the version of OpenJDK (Microsoft Build), I had installed version 17.X.X.
I uninstalled this version, and installed the latest version (21.X.X Microsoft Build) and the problem was resolved.

Thank you very much for your time.
