### ISSUE TITLE
Bug report - SQLServer: foreign keys problem with Windows authentication...

### ISSUE THREAD

**Issue by undertherainITA** [dbeaver/dbeaver#3650]
Hi.
When I open branch from table with Windows authentication there is a problem with foreign keys:

"Error SQL [515] [23000]: Cannot insert the value NULL into column 'name', table 'tempdb.dbo.#foreign_keys_combined_results8efc05b1-d3bd-48f6-ae98-61d368c7523f__________________________________________________000000000136'; column does not allow nulls. INSERT fails.
  Cannot insert the value NULL into column 'name', table 'tempdb.dbo.#foreign_keys_combined_results8efc05b1-d3bd-48f6-ae98-61d368c7523f__________________________________________________000000000136'; column does not allow nulls. INSERT fails.
  Cannot insert the value NULL into column 'name', table 'tempdb.dbo.#foreign_keys_combined_results8efc05b1-d3bd-48f6-ae98-61d368c7523f__________________________________________________000000000136'; column does not allow nulls. INSERT fails.
".

Also the ER diagram with SQLServer with Windows authentication has the problem (no relationships are drawn while with JDBC connection with username and password relationship are drawn).
Thanks.
Ciao... ;)

**Comment by serge-rider** [comment]
Could you provide a bit more info.
Please post error/debug log for the first error (https://github.com/dbeaver/dbeaver/wiki/Log-files).

Have no clues about FKs yet (generally they work fine with any type of authentication, can't figure out how this can be related).
What driver do you use (jTDS or Microsoft)?
