### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by Lonniebiz** [dbeaver/dbeaver#3651]
I've gotten to where I really like code editors that offer dark themes (where the interface is predominately black or some other dark alternative).

A good example of this is [atom](https://www.google.com/search?q=atom.io&tbm=isch). I've found that these dark themes are easier on my eyes (over the course of a long workday).

I don't expect this would be easy to do in dBeaver, but I thought I'd at least mention my preference.

**Comment by infectormp** [comment]
dublicate of https://github.com/dbeaver/dbeaver/issues/3268, https://github.com/dbeaver/dbeaver/issues/2775

**Comment by infectormp** [comment]
btw, dark theme implemented in DBeaver. Preferences-General-Appearance-Theme

**Comment by Lonniebiz** [comment]
Thank you, [Satan](https://www.youtube.com/watch?v=8uTThzrBYwg)!
