### ISSUE TITLE
Load catalog privileges has encountered a problem

### ISSUE THREAD

**Issue by JTMosaic** [dbeaver/dbeaver#36532]
### Description

![image](https://github.com/user-attachments/assets/28f3020d-5632-48a7-8da3-1a250bd1202f)

This error just started appearing in version 24.3.0 CE. It appears after I've not used DBeaver for a while and then come back to it. Please let me know if any additional logs are required

### DBeaver Version

24.3.0 CE

### Operating System

macOS 15.1.1

### Database and driver

MariaDB

### Steps to reproduce

Occurs after letting DBeaver sit idle for a period of time. I am unsure how long

**Comment by E1izabeth** [comment]
Please send us log files. You can collect them to archive automatically with `Help->Collect Diagnostic Info`
![image](https://github.com/user-attachments/assets/51c7ca2e-6be2-489e-b495-028b9aa0e386)

**Comment by JTMosaic** [comment]
Sorry @E1izabeth but that would expose too much information. I did find this in the error log. Please let me know if it helps or if there is other information I can collect for you.

```
!ENTRY org.jkiss.dbeaver.model 4 0 2024-12-10 13:26:15.920
!MESSAGE Cannot invoke "org.jkiss.dbeaver.ext.mysql.model.MySQLUser.getDataSource()" because the return value of "org.jkiss.dbeaver.ext.mysql.ui.editors.MySQLUserEditorGeneral.getDatabaseObject()" is null
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.ext.mysql.model.MySQLUser.getDataSource()" because the return value of "org.jkiss.dbeaver.ext.mysql.ui.editors.MySQLUserEditorGeneral.getDatabaseObject()" is null
	at org.jkiss.dbeaver.ext.mysql.ui.editors.MySQLUserEditorGeneral$2.evaluate(MySQLUserEditorGeneral.java:183)
	at org.jkiss.dbeaver.ext.mysql.ui.editors.MySQLUserEditorGeneral$2.evaluate(MySQLUserEditorGeneral.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:119)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by E1izabeth** [comment]
Do you have other errors right before this one in dbeaver-debug.log? Maybe something related to connection?

Alternatively, as an option you can send logs to support-tickets@dbeaver.com

**Comment by JTMosaic** [comment]
No, nothing immediately preceding it. The entry right before that error is from an hour before and was a permissions issue. 

However, there are a large number of these errors throughout the log:

```
!ENTRY org.jkiss.dbeaver.model 2 0 2024-12-10 08:41:55.223
!MESSAGE Charset 'null' not found.

!ENTRY org.jkiss.dbeaver.model 2 0 2024-12-10 08:41:55.223
!MESSAGE Charset 'null' not found.

!ENTRY org.jkiss.dbeaver.model 2 0 2024-12-10 08:41:55.223
!MESSAGE Charset 'null' not found.

!ENTRY org.jkiss.dbeaver.model 2 0 2024-12-10 08:41:55.223
!MESSAGE Charset 'null' not found.

!ENTRY org.jkiss.dbeaver.model 2 0 2024-12-10 08:41:55.225
!MESSAGE Charset 'null' not found.
```

**Comment by E1izabeth** [comment]
Thank you
