### ISSUE TITLE
Some icons show as red squares until clicked in recent DBeaver versions

### ISSUE THREAD

**Issue by anophelesgreyhoe** [dbeaver/dbeaver#3653]
In recent versions of DBeaver on Ubuntu 16.04, I'm finding the Database Navigator and Projects icons show as red boxes on application start, until I click them.

![image](https://user-images.githubusercontent.com/11037075/41513420-0eb58e7e-72f0-11e8-9f1e-eccf58f4bfa7.png)

**Comment by serge-rider** [comment]
This is side effect of DBeaver UI refactoring and Eclipse icons caching.
But this happens only once, after you click an icon Eclipse will re-cache it.

**Comment by anophelesgreyhoe** [comment]
Thanks Serge. For me it happens every time I restart DBeaver for some
reason.

**Comment by serge-rider** [comment]
Well, perhaps something was corrupted in workspace config. Try to reset workspace: https://github.com/dbeaver/dbeaver/wiki/Reset-workspace

**Comment by offstate** [comment]
reset workspace config doesn't help

**Comment by serge-rider** [comment]
Weird. Can't reproduce that on any of our test envs.
Maybe you should reinstall the last version (and remove previous version completely - looks like some older plugins /configs were loaded along with new ones).

**Comment by offstate** [comment]
Yesterday I did not delete the file but renamed it. Today I removed it and red squares disappeared.
Thank you

**Comment by serge-rider** [comment]
Good

**Comment by MarcinWieczorek** [comment]
I can confirm that removing metadata helped. Thanks for reporting this!
