### ISSUE TITLE
sql editor ${word_selection} ${line_selection} seems not working properly

### ISSUE THREAD

**Issue by molostoff** [dbeaver/dbeaver#3654]
SQL script editor offers templates to apply on text selection, but it seems that ${word_selection} and ${line_selection} do not work at all - templates insert nothing neither with simple form ${word_selection} nor variable form ${id:word_selection}${id} 
Sorry but I have not tested other templates.

**Comment by tkorach** [comment]
Can report that other variables work, but these two don't work. For line_selection, it simply replaces the first word of the selection with the template.

**Comment by dwburrill** [comment]
I have the same issue.  Neither variable works as expected.  (currently on 5.3.3201901202008, but couldn't get it to work with previous versions either).

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by serge-rider** [comment]
Fixed.
Can be tested by selecting a word + template proposal (<kbd>ctrl+alt+space</kbd>).

**Comment by uslss** [comment]
verified
