### ISSUE TITLE
Dbeaver Redshift error: "connection attempt timed out"

### ISSUE THREAD

**Issue by akshay4996** [dbeaver/dbeaver#36558]
### Description

getting Dbeaver Redshift error at first time login in my office laptop: "connection attempt timed out"

![image](https://github.com/user-attachments/assets/96b9f5a7-cc4e-447b-8bf3-217fcfb6d174)

### DBeaver Version

community edition 24.3.0

### Operating System

windows 10

**Comment by mak74536** [comment]
what is the resolution here?
