### ISSUE TITLE
Double-click behaviour on Database Navigator list item

### ISSUE THREAD

**Issue by kb-ig** [dbeaver/dbeaver#36550]
**Is your feature request related to a problem? Please describe.**
By default, I always try to double-click an item in the Database Navigator panel to expand it, which actually brings up the properties. I need to expand items in this panel far more often than I have to access the properties of the item.

I also find that, when trying to click the arrow to expand/collapse, I often miss it, especially when using a trackpad. It's a fairly small hitbox. 

**Describe the solution you'd like**

**Suggestion 1**

I gess maybe the hitbox size could be increased, so as rather than having to click on the icon to trigger expand/collapse, clicking on the icon + padding/margin triggers it.
![image](https://github.com/user-attachments/assets/da63c34e-a9dc-474d-8e35-84cf5cc06030)

**Suggestion 2**

Perhaps double clicking on specific parts of the row could invoke different behaviour. For exmaple, double-clicking on the icon (highlighted green) could open up the properties, and double-clicking the rest of the row (highlighted blue) could toggle expand.
![image](https://github.com/user-attachments/assets/70198902-9862-4b17-a141-c2df8f9b8622)

**Describe alternatives you've considered**
N/A

**Additional context**
After writing this ticket, I realise that these changes would likely apply to more than just the Database Navigator panel. It would apply to any panel which lists expandable items. For example, the Projects panel. However I notice that the Project - General panel already toggles expand/collapse when double clicking anywhere on the item. I guess this might be because it's just a file system item with no corresponding properties in DBeaver.

**Comment by TB-HunBoka** [comment]
You mean this?
![image](https://github.com/user-attachments/assets/05893352-a557-4715-b964-bf3ac9ca00fb)

**Comment by kb-ig** [comment]
Yes, thank you! I did have a search around in the preferences window before creating this request, but clearly missed this option.

This gives me what I need. I'll leave this request open for now as It might still be good to implement these two suggestions, but do feel free to close it if you feel they dont add enough value or not enough benefit to other users. 

Thanks again.

**Comment by ShadelessFox** [comment]
I don't think we should change the current behavior in any way since it's already configurable.
