### ISSUE TITLE
Regression in Data Filters functionality

### ISSUE THREAD

**Issue by rwalravens** [dbeaver/dbeaver#3656]
Since **DBeaver CE 5.1.1**, I noticed two issues in the Data Filters functionality

1. When applying the filter criteria with Ctrl+Enter, a popup indicating `Data read is in progress - can't run another` appears

![image](https://user-images.githubusercontent.com/36928442/41625386-f8372700-7418-11e8-9a32-b966bff0ffa9.png)

In the SQL Editor, this functionality is also broken, though it doesn't show  a popup, it merely does nothing.

2. Using autocompletion for the SQL Expression immediately applies the filter
- start typing the name of a column (e.g. `CATA`) and press Ctrl+Space

![image](https://user-images.githubusercontent.com/36928442/41625607-a821cd14-7419-11e8-8f68-685d76b1d5bf.png)

- select the wanted column (e.g. `CATALOG_NAME`) and press Enter

![image](https://user-images.githubusercontent.com/36928442/41625612-abf81cea-7419-11e8-8a9d-95d31c56e3ad.png)

**Comment by kip-13** [comment]
I have the same problem, just when I repeat `CTRL + ENTER` after click `OK` in the message's box isn't trigger the error again, but if I try again the autocompletition  the error appear, I mean:

- `CTRL + SPACE` then `ENTER` -> Error
- Click ok in the box that show the error of execution query
- `CTRL + SPACE` then `ENTER` -> Ok
- `CTRL + SPACE` then `ENTER` -> Error
- Click ok in the box that show the error of execution query
....

**Comment by serge-rider** [comment]
@rwalravens this is a bug in Enter key processing. We'll fix it in the next version.
Workarounds:
1. Use just <kbd>Enter</kbd> (without Ctrl) to apply filter criteria. Or click on "Apply filter criteria" toolbar button.
2. Use mouse double-click to select column name
