### ISSUE TITLE
New Autocomplete adds wrong alias name when choosing column

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#36573]
### Description

```
create table tab1 (
    id int,
    statdate timestamp,
    enddate timestamp
);

select *
from tab1 as t
group by 
;
```

https://github.com/user-attachments/assets/5f87c736-be58-44b6-9adf-4d54b33a2b76

### DBeaver Version

Enterprise Edition 24.3.1-202412150022

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by E1izabeth** [comment]
Thanks for the bug report
