### ISSUE TITLE
Client Certificate and Client Private Key entries are missing after restarting

### ISSUE THREAD

**Issue by jonasmuench** [dbeaver/dbeaver#36584]
### Description

The Client Certificate and Client Private Key entries are missing after restarting DBeaver, resulting in a connection error: 

```
FATAL: connection requires a valid client certificate
```

### DBeaver Version

Community 24.3.0.202412011650

### Operating System

Windows 11

### Database and driver

PostgresSQL

### Steps to reproduce

Step 1: Open DBeaver.
Step 2: Go to "Database" and create a new connection.
Step 3: Enter the connection details, including the Client Certificate and Client Private Key.
![image](https://github.com/user-attachments/assets/53ee6d34-fe9f-4ade-92fa-a9537a84ab8d)
Step 4: Save and connect to the database.
Step 5: Restart DBeaver.
Step 6: Check the connection details.
FATAL: connection requires a valid client certificate

**Comment by MashaKorax** [comment]
Hello @jonasmuench . We've fixed this bug. Please update the app to the latest version.
