### ISSUE TITLE
Netezza, cannot edit stored procedures

### ISSUE THREAD

**Issue by sorenhakola** [dbeaver/dbeaver#3658]
Hi, 

Just wanted to point out that there is no possibility to edit stored procedures when using Netezza as database. Just getting this in Source sheet of procedure properties. 
-- Netezza procedure source not found

I'm using
DBeaver Community version: 5.1.1 (64 bit)
Netezza driver (from IBM): 7.2.1.4
Windows: 7 Enterprise 64-bit
JDK: 
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
javac 9.0.1

I really like the layout and functionality of DBeaver, but this is such a major setback. Are there any possibilities to get this fixed in the near future?

Br,
Sören

**Comment by serge-rider** [comment]
Procedures editor is not supported yet.
However source should be available.
DBeaver uses following query to read the source: 
```sql
SELECT p.proceduresignature,p.returns,p.proceduresource 
FROM _v_procedure p 
WHERE p.owner=SCHEMA AND p.procedure=PROC
```
Could you check that it works and if it fails then please post the error.

**Comment by sorenhakola** [comment]
I fooled around a bit and was getting a fraction of the procedures to show up, but some just wont. 

E.g. this will not show up - at least when compiled with Aginity:

    CREATE OR REPLACE PROCEDURE FOO()
    RETURNS CHARACTER VARYING(ANY)
    LANGUAGE NZPLSQL AS
    BEGIN_PROC
     DECLARE active integer; i integer; BEGIN active := 1; i := 0; 
     insert into blah select 'first', 1, 1 from foo limit 0;
     return 'rowcount: ' || ROW_COUNT || ', round: ' || i || ', active: ' || active; END; 
    END_PROC;

At first I thought that the return type had something to do with it, but no. 
The second thought was the length of the procedure, but that also has nothing to do with it..

The code you sent, does not give any errors (except that the `PROC` word must be changed to an existing procedure name). 

Really odd that some show up while others don't..

**Comment by serge-rider** [comment]
So this query just doesn't return any results for some procedures (while returns for others)?
Maybe this is somehow related to permissions?
Maybe this is related to different procedures language (NZPLSQL in your case)?

**Comment by sorenhakola** [comment]
> "So this query just doesn't return any results for some procedures (while returns for others)?"

This might be the issue actually. If the procedure is owned by the same user as the database owner, then the code is visible. If there is a  mismatch, the code is not visible. I.e. if I create a procedure and do not change the owner to the same as database owner, I cannot change the code since it is owned by my user name.

> "Maybe this is somehow related to permissions?"

Well, so and so. Permission only to work with procedures that are owned by the same user as the user owning the database. 

> "Maybe this is related to different procedures language (NZPLSQL in your case)?"

All procedures are in the same language. 

Do you think this is possible to correct?

**Comment by DragonStorm97** [comment]
> Procedures editor is not supported yet.
> However source should be available.
> DBeaver uses following query to read the source:
> 
> ```sql
> SELECT p.proceduresignature,p.returns,p.proceduresource 
> FROM _v_procedure p 
> WHERE p.owner=SCHEMA AND p.procedure=PROC
> ```
> 
> Could you check that it works and if it fails then please post the error.

I think the issue is filtering on owner = schema. In Netezza, the owner is usually a user, and a user isn't a schema (not like in oracle) so the owner in my case is almost always my username, but the schema is whatever I'm connected to.
@serge-rider can the filter on owner = schema please be removed? _v_procedure only brings back results for the current schema anyway. Not sure if this is the same issue as with the view DDL not coming back (don't know the query DBeaver uses).

**Comment by serge-rider** [comment]
The same as in #7611 - please test the fix in the Early Access version (https://dbeaver.io/files/ea)
