### ISSUE TITLE
连接mysql报错

### ISSUE THREAD

**Issue by sunzhiqi123** [dbeaver/dbeaver#36590]
### Description

dbeaver连接mysql报错Unknown system variable 'query_cache_size'  mysql版本8.4.3

### DBeaver Version

24.3.0

**Comment by ShadelessFox** [comment]
Hello @sunzhiqi123,

We don't query that particular system variable anywhere in DBeaver. Please check your connection configuration and ensure you have nothing set as bootstrap queries.

**Comment by sunzhiqi123** [comment]
> Hello @sunzhiqi123,
> 
> We don't query that particular system variable anywhere in DBeaver. Please check your connection configuration and ensure you have nothing set as bootstrap queries.

hello ， I connection to mysql 8.2.0 is fine, but the connection to 8.4.0 is an error. Unknown system variable 'query_cache_size'
