### ISSUE TITLE
(MariaDB) Can't save edited views

### ISSUE THREAD

**Issue by Speirs47** [dbeaver/dbeaver#3659]
Just like in a title. Whenever I try to edit a view and then save it I get an error
`SQL Error [1064] [42000]: (conn:124870) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CREATE
OR REPLACE
VIEW dane_nowe.vemail AS select
    dane_nowe.email.I at line 2`

Here's original view: 
`CREATE
OR REPLACE
VIEW dane_nowe.vemail AS select
    dane_nowe.email.ID_email AS ID_email,
    dane_nowe.email.ID_klient AS ID_klient,
    dane_nowe.email.email AS email,
    dane_nowe.email.opis AS opis
from
    dane_nowe.email
where
    (( dane_nowe.email.usunięty = 0 )
    and ( dane_nowe.email.kontakt = 0 ))`

And here's edited view (added a condition in WHERE clause):
`CREATE
OR REPLACE
VIEW dane_nowe.vemail AS select
    dane_nowe.email.ID_email AS ID_email,
    dane_nowe.email.ID_klient AS ID_klient,
    dane_nowe.email.email AS email,
    dane_nowe.email.opis AS opis
from
    dane_nowe.email
where
    (( dane_nowe.email.usunięty = 0 )
    and ( dane_nowe.email.kontakt = 0 ) and (dane_nowe.email.ID_klient > 0))`

It happens in DBeaver 5.1.1 (Linux, openSUSE)

**Comment by serge-rider** [comment]
This is a side effect of recent changes in 5.1.1 (view definition text extraction was improved).
Thanks for bugreport
