### ISSUE TITLE
SAP HANA DDL Functions: show under own category

### ISSUE THREAD

**Issue by MatthiasBergen** [dbeaver/dbeaver#3660]
It would be helpful if functions would be shown under an own category functions instead of procedures. In my case there are a lot of procedures and only a few functions. So for now I have to go through the whole list of procedures to find a specific function ;) 

thx

**Comment by serge-rider** [comment]
This makes sense. However this should be configurable on driver basis (in some DBs procedures and functions are much the same).

**Comment by serge-rider** [comment]
For now by default this feature enabled for Derby and HANA.
And this is configurable for each Generic driver:
![image](https://user-images.githubusercontent.com/6398845/41941771-a4b02c66-79a5-11e8-9e61-2ee9e0ca012f.png)

**Comment by MatthiasBergen** [comment]
@serge-rider You are awesome!! Thank you
