### ISSUE TITLE
Show Algorithm of MYSQL View

### ISSUE THREAD

**Issue by vegetable09** [dbeaver/dbeaver#3661]
view is usually used by my team, as we all know, there are 3 algorithm in mysql:
1、MERGE
2、TEMPTABLE
3、UNDEFINED

you can run sql and see which algorithm is used: 
`SHOW CREATE VIEW t_demo_v`

but there is NO where to see algorithm of view in dbeaver 5.1.0

**Comment by vegetable09** [comment]
I really love dbeaver, I working with java and try to solve this issue by myself, but need some time

**Comment by serge-rider** [comment]
Good point, see it in the next version

**Comment by vegetable09** [comment]
What a suprise when i get up and see this, thanks for your rapid response @serge-rider
