### ISSUE TITLE
Unable to read selected option when DBeaver set with Theme=Dark

### ISSUE THREAD

**Issue by emanueol** [dbeaver/dbeaver#36613]
### Description

1. Simple, just start DBeaver > Windows > Preferences > any option clicked on left panel is black on black..

My dbeaver settings:
DBeaver > Windows > Preferences > User Interface > Appearance:
Theme= Dark
Color and Font theme= Classic Theme (current)
![IMG_20241220_201018](https://github.com/user-attachments/assets/7ecc8b95-bf24-4445-95c9-0296d02b4e79)
![IMG_20241220_201052](https://github.com/user-attachments/assets/a95e6f5f-252e-4f7d-9720-b2d10969dbc7)

Windows:
Doesnt matter if windows in Light or Dark mode.

### DBeaver Version
DBeaver Enterprise 21.3.0.202112052011

### Operating System
Windows 11 Enterprise

### Steps to reproduce

1. Simple, just start DBeaver > Windows > Preferences
2. And any option clicked on left panel is black on black..

### Additional context
1l Above photos may look bit readable, because probably of phone photo ai pos processing or something, because on my screen i cant read.. the dark blue background its like black and foreground color is black.

2) In addition to somehow fix this, and because this is enterprise edition in my job/work place, please feel free to share the name of those 2 color settings so i manually change them.

Thanks in advance ~

**Comment by serge-rider** [comment]
This bug is already fixed.
You use 3-years old DBeaver, could you try a fresh one?

**Comment by emanueol** [comment]
> This bug is already fixed. You use 3-years old DBeaver, could you try a fresh one?

Oh I see, whats the minimum version where this was fixed and whats latest version?
Enterprise Edition.

Thanks ~

**Comment by serge-rider** [comment]
You could try 22.0 but I am not 100% sure..
