### ISSUE TITLE
Column names popup on hovering over index name

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#3662]
This is a minor feature request regarding usability:

It would be nice to have a small column names popup appearing once you hover over an index name in the navigator. I realize many people will include column name already in the index name for single column indexes, but my application really needs to rely on auto-generated numbered index names.

In such cases, it would be useful to have the column names appear in a popup window while hovering over the index name in the Database Navigator, so as to be able to quickly ascertain what columns are indexed by a certain index, without needing to right click each individual index and open its properties via Edit Index.

![afbeelding](https://user-images.githubusercontent.com/7635726/41652377-26cddf0e-7483-11e8-878a-3d339c6b6999.png)

**Comment by serge-rider** [comment]
Agreed, this could be helpful. However such structured tooltips will require quite a bit of coding.

Right now you can open index list in the table editor.
I'll add the same view for full index list (for PG and Generic drivers):

![image](https://user-images.githubusercontent.com/6398845/41942114-f016aa94-79a6-11e8-8915-049dab95b895.png)

**Comment by mboeringa** [comment]
Hi @serge-rider ,

Am I right you added the "Table Column" as a new option for an upcoming release? 

I must admit I hadn't actually properly explored it, but when I right click the headers in the "Indexes" view in DBeaver 5.1.1 and choose "Configure Columns", I don't see the option to view the "Table Column" among things to choose from like you are showing here.

If that is added in a future version, I am OK with that as a good substitute for what I suggested with the more laborious tooltip. It is even more effective, as you can see all indexed columns then at a glance.

**Comment by serge-rider** [comment]
Yes, you are right, this feature will be added for global index list.
For table indexes it is already there.

**Comment by mboeringa** [comment]
Just one last question: I realized that the actual "Table Column" only becomes visible when I expand the index name with the arrow in the entire left of a row. Would it be possible to have an "Expand / Collapse All" option, so that I can truly have a quick overview of indexed columns?

**Comment by lozbrown** [comment]
I'm looking for something similar for sybase as at the moment i have to open every index to find out what columns are indexed, expanding each index in the table editor is just as many clicks.

Could the columns be listed in brackets after the index names in the drop down view..

excuse the MS paint mock up...

![image](https://user-images.githubusercontent.com/9961593/52628685-14d2ec80-2eb0-11e9-8ff3-a4707b1b9878.png)
