### ISSUE TITLE
Vertical editing zoom

### ISSUE THREAD

**Issue by georgethemarmot** [dbeaver/dbeaver#3666]
Vertical editing has its own zoom, 
if the main editor zoom has been changed from standard, into vertical editing mode the zoom is kept but reset. Exiting the vertical editing mode the zoom goes back to the previous defined.

**Comment by serge-rider** [comment]
This is the standard behavior of Eclipse StyledText control. I can't fix this. 
Perhaps it makes sense to file a bug in Eclipse bugtracker (https://bugs.eclipse.org/bugs/) but I doubt that this issue will be resolved soon..
