### ISSUE TITLE
Drivers tarball for Offline usage with DBeaver-plugin

### ISSUE THREAD

**Issue by UNIm95** [dbeaver/dbeaver#3668]
Discription.  
I have separated Network with Postgres and MariaDB.  
Users are using linux terminal server eclipse+DBeaver as eclipse plugin.   
Eclipse is installed in `/opt/eclipse`
DBeaver-plugin is installed in `/opt/eclipse/dropins/dbeaver/eclipse/plugins`  
It allows all users have same version of eclipsa, DBeaver.  

But when user tries to connect to DB it fails cause DBeaver wants to download proper driver with dependencies from internet and store it under `/home/user/.dbeaver-drivers`

It is little bit impossible cause this network is separated from Internet.  
Also i think that it is not really right that each user has own directory with duplicating drivers.

So DBeaver needs two features:

1. Possibility to download  all DB-Drivers as tarbal for installation on hosts that don't have internet 
2. Possibility to use DB-drivers from same install directory where DBeaver-plugin is installed. For example: `/opt/eclipse/dropins/dbeaver/eclipse/plugins`  

If i have not found this **existing** functionality please give me link to DB-driver tarball and documentation about DB-drivers installation for all users.

**Comment by serge-rider** [comment]
Also, DBeaver CE downloads most of the drivers from Maven Central. 
You could setup Nexus repository in your local network. It could proxy entire Maven Central or just keep some artifacts with JDBC drivers you really need. And then change Maven configuration in DBeaver.
However it is quite a bit of administrative work.

**Comment by UNIm95** [comment]
I tired to use this workaround:
I downloaded all drivers to my laptop with dbeaver, '~/.dbeaver-driver' was uploaded to server  without internet.
But no luck. DBeaver tried to connect to maven.

**Comment by ipkpjersi** [comment]
Can someone upload all the drivers here?

**Comment by ipkpjersi** [comment]
Can someone upload all the drivers here?

I really think this would be nice to have an offline mode.

@serge-rider is an offline mode planned eventually? I think it should be seriously considered as important.

**Comment by serge-rider** [comment]
DBeaver supports offline mode - you can just remove references on external artifacts (like Maven artifacts or direct http links).

Also DBeaver EE is bundled with most of driver and do not tries to download them.

Potentially it is possible to make some "advanced" CE version (which will include some pre-downloaded drivers). However I don;t think we'll do this in near future.

**Comment by ipkpjersi** [comment]
I think an "advanced" CE version with pre-downloaded drivers would be a cool idea, I'd like to see that. I also own a copy of EE and think EE would still be worth it over CE even with bundled drivers.

**Comment by ipkpjersi** [comment]
Why was this closed? Is this feature being added?

**Comment by tati-kru** [comment]
This option is under the question and we are not sure that it will be implemented. Moreover, when we decide to do something like this it can be not exactly the same as described in the ticket. So, it is not make a lot of sense to keep this question opened.
