### ISSUE TITLE
Hotkeys do not work on Mac OS X

### ISSUE THREAD

**Issue by frops** [dbeaver/dbeaver#3670]
After a while all hot keys stop working, even **cmd+c**.
Reloading DBover helps.

Mac OS X version: 10.13.5 (17F77) (High Sierra).
Thanks.

**Comment by serge-rider** [comment]
Looks like Eclipse bug. Application restart usually helps.
Need to reproduce that somehow..

**Comment by frops** [comment]
Does not work even Shift + alt + arrow. I do not know how else I can help you figure out this bug (

**Comment by serge-rider** [comment]
Maybe there is some specific action/event after which shortcuts stop working?
I didn't see such issue for a very long time.

**Comment by frops** [comment]
DBeaver version: 5.1.0

Sometime even reload doesn't helps (
Maybe problem in OS, I don't know (

**Comment by uslss** [comment]
There is no update on the ticket for more than a year.
If the issue is still reproducible for you - feel free to reopen the ticket and add some details that could help to reproduce the issue or create the new one.
