### ISSUE TITLE
Could not establish connection hive2

### ISSUE THREAD

**Issue by prinstonsam** [dbeaver/dbeaver#3672]
When I try to create a connection (Apache hive) I get an error:
![image](https://user-images.githubusercontent.com/6134279/41733969-4f54d6c4-758e-11e8-9900-b0e02b2e3d3a.png)

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on the issue for a long time
additional info is needed to reproduce an issue.
ticket will be closed. feel free to reopen an issue and add info that could help to investigate it.
