### ISSUE TITLE
Oracle connection default schema selection issue

### ISSUE THREAD

**Issue by danieleangellotti** [dbeaver/dbeaver#3675]
After opening an Oracle connection _DB_TEST_ and then a new SQL editor, selecting _DB_TEST_ from left combo box I don't see the default connection schema on right combo box.

WHEN: After opening a new SQL editor and selecting a newly opened Oracle connection from combo box
EXPECTED BEHAVIOR: Default user schema of connection is automatically selected
CURRENT BEHAVIOR: No schema selected (<None>)
USER ENVIRONMENT: DBeaver 5.1.1 - JRE 1.8.0_101 - JDBC Driver 8, 12.2.0.1.0 - Windows 7 Ultimate Service Pack 1

NOTE: If I start another SQL editor and select the same connection, then default connection schema is automatically selected (for the other SQL editor too).

**Comment by uslss** [comment]
Unfortunately, cannot reproduce the issue. The ticket is closed.
If the issue is still reproducible for you - feel free to reopen the ticket and add some details that could help to reproduce the issue or create the new one.
