### ISSUE TITLE
Feature request: Copy/Paste with headers

### ISSUE THREAD

**Issue by renezito** [dbeaver/dbeaver#3676]
Hi.  In resultset, I select all, copy and paste, the data is pasted but without headers.  Maybe some people doesn't need the header,  I think the most people would like with headers.  Maybe in preferences could exists the option to check/uncheck "Copy with header"... Sorry for my english :-)

**Comment by nmat** [comment]
Have you tested to do a advanced copy? The feature is in there to do more specific selection of how you want to copy and paste.

**Comment by nmat** [comment]
As a quick guide.

Ctrl+Shift+C

Select what you want.

**Comment by nmat** [comment]
@renezito did you manage to test the above?

**Comment by renezito** [comment]
Yes, I tried with that.  Thanks.  Maybe I forgot to mention that I want to avoid doing that step and just selecting all, then copy and Paste could be the faster way... That is for just one simple reason.  When you want to carry your data, you always want it with headers :-)
That is why I was asking that if it is not the pre-defined way to carry my data (with headers), maybe could be an option in preferences to select/deselect to activate copying with headers or not.

**Comment by nmat** [comment]
I don't think there is a default way to do it.

I would if anything: Ctrl+6, Ctrl+A, Ctrl+Shift+C

But this is a bad habbit from my part of using keyboard shortcuts.
