### ISSUE TITLE
Formatting for "Condition" of "Explain execution plan"

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#3677]
This is a minor feature request and usability issue. 

Currently, the explain plan is displayed in a tabular structure, with the "Condition" taking up one column and one row. However, for long statements, it is impossible to see the entire "Condition" expression. Even if you hover over the value, the popup window is unformatted, and extents all the way to the right of your screen, and will unfortunately still be cut off if it hits screen limits.

It would be better if the popup of the "Condition" statement was wrapped or formatted, so as to allow you to view the entire condition. This is helpful in reviewing the execution plan and potentially decide on some (multi) column indexes.

![afbeelding](https://user-images.githubusercontent.com/7635726/41790460-e9005bbc-7652-11e8-8201-461b0678b88f.png)

**Comment by serge-rider** [comment]
Good point
![image](https://user-images.githubusercontent.com/6398845/42111494-5cfbbc92-7bed-11e8-93e8-f3f68ab56784.png)
