### ISSUE TITLE
Alt+F11 does not work on windows 10 1803

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#3678]
After upgrade to windows 10. Winver: 1803 (OS Build 17134.112) it seems that the Alt+F11 key does not toogle fullscreen of the application.

Tested on a older version of windows 10 and there it seems to work with same DBeaver 5.1.1 version.

I can toggle the fullscreen in the menus though.

**Comment by serge-rider** [comment]
Works well in our test env.
Please check Preferences->General->Keys, search Toggle full screen command. Maybe shortcut was reset by some reason.

**Comment by nmat** [comment]
Ok I found out why it did not work.

The nvidia drivers used Alt+F11 for something so turning off that binding in nvidia geforce experience fixed it. Setting this issue as resolved.
