### ISSUE TITLE
Migrate ERD to Zest

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#3680]
We need to migrate from legacy GEF to modern GEF5 and Zest plugins.
Besides ERD it wil laffect query builder (#1652) and Locks UI,

**Comment by ruspl-afed** [comment]
Probably, GEF-related dependencies should be extracted from https://github.com/dbeaver/dbeaver/blob/devel/features/org.jkiss.dbeaver.core.feature/feature.xml to a separate feature to reduce potential conflicts

**Comment by uslss** [comment]
seems to be obsolete.
