### ISSUE TITLE
REFRESH MATERIALIZED VIEW not implemented for PostgreSQL ?

### ISSUE THREAD

**Issue by Xpunk** [dbeaver/dbeaver#3681]
The SLQ clause  **REFRESH** MATERIALIZED VIEW (for postgresql db)  is not implemented or i didn't find the way to do it ? (dbeaver v5.1.1)

**Comment by serge-rider** [comment]
This feature will be added in 5.1.2
![image](https://user-images.githubusercontent.com/6398845/42110406-a5c3bde8-7be9-11e8-8d87-1adabb16ea1f.png)

**Comment by Xpunk** [comment]
Perfect ! Thanks for your quick reactivity !
