### ISSUE TITLE
autocomplete: ignores mixed case table names if searching in all schemas

### ISSUE THREAD

**Issue by sqlpro20** [dbeaver/dbeaver#3685]
I think I have found a bug:

If I activate 'use global search' in autocomplete settings, DBeaver forgets about mixed case objects (unfortunally, we have mixed case table names).

So, if we have a table customer."SomeTable" and I try this: 
some<autocomplete>
Dbeaver completes this to:
customer."sometable"
instead of:
customer."SomeTable"

If I deactivate 'use global search', it autocompletes correctly to "SomeTable". However, I have to use multiple schemas...

**Comment by sqlpro20** [comment]
I can still reproduce this with the newest version: 5.2.3. The handling with different schemas has been improved, but this annoying Bug still exists.

**Comment by sqlpro20** [comment]
Although nobody answered here, this issue is fixed (at least in current version 6.0.4)

**Comment by tati-kru** [comment]
@sqlpro20 thank you for check and update!
