### ISSUE TITLE
Some tables not found through Goto tool (ctrl-shift-D)

### ISSUE THREAD

**Issue by lhimo** [dbeaver/dbeaver#3686]
If I try to open a table of a particular schema in my DB (below a certain threshold element in alphabetical order), or to open a table with a name alphabetically "low" in the list, it doesn't show up. Is there a limit in the tables which are indexed?

**Comment by serge-rider** [comment]
Yes, there is a limit of objects DBeaver shows in search results. 
It is 1000 objects.
