### ISSUE TITLE
Windows are closing when open different database

### ISSUE THREAD

**Issue by denizkaanaraci** [dbeaver/dbeaver#3687]
Hi. I'm using Ubuntu 18.04 - DBeaver 5.1.1

After updating my OS to 18.04 , DBeaver closes my  pages like this: [PROBLEM](https://media.giphy.com/media/2aFUt2dCjwTxYd8XNh/giphy.gif)

Is this bug or there is any option to change ? Thanks.

**Comment by serge-rider** [comment]
I never saw such glitch. 
Perhaps it is Dark theme rendering issue.
Could you try the same in classic theme?

**Comment by denizkaanaraci** [comment]
Thanks for answering. I tried it on default theme but  it didn't work. Also I tried after updating 5.1.2 but result is same. [Problem](https://media.giphy.com/media/jyIMGfjLwwBVLEkz0D/giphy.gif)

**Comment by serge-rider** [comment]
Ah, now I see.
This is not actually a bug but a kind of limitation. This happens because DBeaver reconnects to another database once you change active database (it is PostgreSQL-specific behavior).

We have FR #3771 - it will resolve this issue.
