### ISSUE TITLE
Goto Database Object <Ctrl+Shift+D> fails if connection needs to be invalidated

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#3691]
If I temporarily lose connection to a database then I try to use the go to object window, it will show "Items filtering failed" error. I then have to press the "invalidate/reconnect" button and try again. Could Ctrl+Shift+D failure added to the events that trigger the auto-invalidate feature you added some releases ago?

**Comment by serge-rider** [comment]
Agreed, this makes sense
