### ISSUE TITLE
Error executing count query if last line is a comment

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#3693]
If I execute the following query with ctrl+enter:

    SELECT * FROM dual
    -- COMMENT there

Then press the bottom "Calculate total row count" button it throws an error.

In query manager I see it executes the following query:

    SELECT COUNT(*) FROM (SELECT * FROM dual
    -- COMMENT there) dbvrcnt

where ``) dbvrcnt`` is commented as well.

**Comment by serge-rider** [comment]
Thanks for bug report
