### ISSUE TITLE
Show used/available size on tablespace view

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#3694]
Hi, I want to request a new feature in tablespace viewer on Oracle, to show total available/used size.

This can be done with the following query:

	SELECT
		t.tablespace_name,
		SUM(f.bytes) available_space,
		SUM(s.bytes) used_space
	FROM
		sys.dba_tablespaces t
	LEFT JOIN sys.dba_data_files f ON
			t.tablespace_name = f.tablespace_name
		LEFT JOIN sys.dba_segments s ON
				t.tablespace_name = s.tablespace_name
			GROUP BY
				t.TABLESPACE_NAME

The object I'm referring to is this one:

![immagine](https://user-images.githubusercontent.com/2157006/41955437-508a9550-79e0-11e8-8b2d-2e9253ede88a.png)

Which currently shows only the block size and status (e.g. ONLINE) for each tablespace.

Also, having the ability to use a more suitable unit than bytes (e.g. MB, GB, TB) would be appreciated, both here and in the Files view (available if you select a single tablespace).

**Comment by serge-rider** [comment]
Good point and easy to do

**Comment by p91paul** [comment]
I noticed that sizes get multiplied when there are many data files per tablespace. My query was wrong and should be split in 2:

	SELECT
		t.tablespace_name,
		SUM(f.bytes) available_space
	FROM
		sys.dba_tablespaces t
	LEFT JOIN sys.dba_data_files f ON
			t.tablespace_name = f.tablespace_name
	GROUP BY
		t.TABLESPACE_NAME;

	SELECT
		t.tablespace_name,
		SUM(s.bytes) used_space
	FROM
		sys.dba_tablespaces t
	LEFT JOIN sys.dba_segments s ON
			t.tablespace_name = s.tablespace_name
	GROUP BY
		t.TABLESPACE_NAME;
