### ISSUE TITLE
Case insensitive filter by value

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#3696]
Using the "filter by column value" button on the top of each column, I understand that the window with the values get first populated with the values available in the currently loaded resultset (e.g. the default first 200 rows). Then if I use the search box at the bottom, the search is performed 1) immediately on those values, while 2) a query is being run on the database to load more values matching my filter.

Search on 1) is case insensitive; search on 2) is case sensitive. Can 2) be made insensitive too?

**Comment by p91paul** [comment]
what about doing upper(field) like upper('%search%')? I don't know if the upper function is oracle specific or somehow standard... I realize implementing this can turn out to be a lot of work if each database has his own way of performing case insensitive searches...

**Comment by vegetable09** [comment]
try to check your database and table create DDL, if exists utf8_general_ci?

**Comment by serge-rider** [comment]
@p91paul yes, we can't use UPPER as some databases don't have it.
However it can be done with some additional driver parameter/sql dialect enhancement.
Quite a lot of work but doable.

**Comment by ShadelessFox** [comment]
I believe this feature was already implemented in #11719.
