### ISSUE TITLE
Support fixed width files like CSV ones

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#3697]
I'd like to be able to query fixed width files (also called positional) just like I can with separated ones with CSV driver. The connection setup should allow to set column name and width for each column in the file. Apart for connection setup, functionality should be the same as the CSV driver.

Thanks for considering!

**Comment by ShadelessFox** [comment]
Hello @p91paul,

It looks like the CSV driver now supports fixed-width files. It just needs a bit of configuration.

You will have to set these two parameters:
- The `fixedWidths` with column ranges, like so: `1-10,11-20,21-30`
- The `isHeaderFixedWidth` if header is present and is also fixed-width
