### ISSUE TITLE
Default database changes

### ISSUE THREAD

**Issue by marczahn** [dbeaver/dbeaver#3698]
Question/Bug?

For my connection I configure "postgres" as database. When I now switch to another database the database in the connection config is changed as well.

When now this selected database is deleted I need to disconnect und reconfige the database in the connection configuration.

Is this intended?

**Comment by serge-rider** [comment]
This is a bug, side effect of connection switch improvements. Will fix in the next version.
Also another bug with multiple active database switch was fixed.
