### ISSUE TITLE
Postgres connection invalidated in DBeaver Windows version 5.1.1

### ISSUE THREAD

**Issue by johnrijs** [dbeaver/dbeaver#3699]
After installing Windows version 5.1.1 64-bit I started to encounter issues with database connections to PostgreSQL databases. DBeaver regularly shows a popup window telling me the connection was invalidated even though the query is still running. Dbeaver then restores the connection which in itself is great.

However, as a result of losing the connection I also lost a temporary table I was creating (temporary tables get dropped after the session ends). I have a feeling this is related to some kind of timing setting because it seems to occur especially in situations where a query is running for more than a couple of minutes.

I decided to re-install version 5.0.4, which was the latest version I used before installing 5.1.1. In the older version things work again as expected. The issue has gone.

Please let me know if you need any more information to resolve this issue,

**Comment by serge-rider** [comment]
What is your database? Maybe DBeaver detect connection loss error incorrectly.
Is there anything interesting in debug log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

You can disable automatic invalidation in 5.1+:
![image](https://user-images.githubusercontent.com/6398845/42126210-110e89ae-7c8d-11e8-8631-e74a49ea5f7e.png)

**Comment by johnrijs** [comment]
Hi

Thanks for your e-mail and sorry for the late response. I connect to Postgres version:

EnterpriseDB 9.6.6.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16), 64-bit

Version 5.0.4 is okay but I will try using the latest version with below suggestion. Unfortunately I do not have old log files anymore.

Best regards,
John


Op 30 jun 2018 om 16:44 uur uur schreef Serge Rider <notifications@github.com>:

What is your database? Maybe DBeaver detect connection loss error incorrectly.
Is there anything interesting in debug log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

You can disable automatic invalidation in 5.1+:

**Comment by alikrc** [comment]
@johnrijs have you found a solution? i've same problem

**Comment by givihuda** [comment]
I get the same error randomly, usually it's at the beginning of day if I was using the connection the evening before.

I'm assuming it's not a problem, but it's annoying being distracted by a notification that may be pointless.

**Comment by vijayaragavan95** [comment]
I think it has a problem. Because, when I run long scripts setting temporary session parameters, this live connection gets broken and Dbeaver reconnects with a new session and triggers same query. But this time all my session parameters are lost.
