### ISSUE TITLE
[Firebird] Blob text encoding in results

### ISSUE THREAD

**Issue by Apcio** [dbeaver/dbeaver#3701]
I changed encoding in configuration to the same as database encoding style, after thant I reseted DBEaver. Now Panel Value show good encoded text, but Result Viewer still have problem with text.
![image](https://user-images.githubusercontent.com/11940927/41976482-8db26506-7a1d-11e8-93d1-f31f95fb2d3c.png)

What should I set in configuration for correct encoding display?
My Firebird 2.5 database have set Windows-1250 encoding.

**Comment by mrotteveel** [comment]
Which version of Jaybird is in use, and did you specify a connection character set? What is the character set of the blob column?

**Comment by Apcio** [comment]
JayBird version:
![image](https://user-images.githubusercontent.com/11940927/42241998-c3de7554-7f0c-11e8-9b3b-4ee0c93e3c6f.png)

JayBird encoding:
![image](https://user-images.githubusercontent.com/11940927/42242083-ff43af1a-7f0c-11e8-8832-e05ed6acdc3a.png)

![image](https://user-images.githubusercontent.com/11940927/42242128-1e30fcc0-7f0d-11e8-959f-648ecce3cbf1.png)


Column should have set encoding to Win-1250, as database encoding.
In Value panel text shows correctly.

**Comment by mrotteveel** [comment]
I have tried, but wasn't able to reproduce this. Could you maybe create a sample database and the exact steps to reproduce this?

**Comment by Apcio** [comment]
Problem is with type BLOB SUB_TYPE 0.

Link to test DB: http://www.mediafire.com/file/s24lya92du8ymsl/TEST.FDB/file
USER: SYSDBA
KEY: masterkey

**Comment by mrotteveel** [comment]
A `blob sub_type 0` (or `blob sub_type binary`) is for binary data, not for text data. I don't know how DBeaver handles this, but the interpretation will depend on whether `getString` is used (which means conversion is done by Jaybird using the connection character set), or `getBytes` / `getBinaryStream` and which character set is then applied by DBeaver.

**Comment by uslss** [comment]
is it still actual?

**Comment by Apcio** [comment]
Hi, I have to create on new database.
On version 7.2.1 I've created 2 tables:

```
﻿CREATE TABLE TEST (
	PK INTEGER PRIMARY KEY NOT NULL,
	TEST BLOB SUB_TYPE 0 CHARACTER SET WIN1250
)
INSERT INTO TEST VALUES (2, 'ANNFLłóŚććźżŻ')
SELECT * FROM TEST
```
And this table it works
![okDB](https://user-images.githubusercontent.com/11940927/94862486-54f63280-0439-11eb-9957-e68d8d42bee2.PNG)

But second test table:
```
CREATE TABLE TEST2 (
	PK INTEGER PRIMARY KEY NOT NULL,
	TEST BLOB SUB_TYPE 0
)
INSERT INTO TEST2 VALUES (2, 'ANNFLłóŚććźżŻ')
SELECT * FROM TEST2
```

This wasn't changed:
![badDB](https://user-images.githubusercontent.com/11940927/94862598-8242e080-0439-11eb-8c1e-59e8cfd0edbf.PNG)


But I think, it should be ok, just need to alter table and set default collation.

**Comment by mrotteveel** [comment]
@Apcio You should use BLOB SUB_TYPE TEXT (aka BLOB SUB_TYPE 1), not BLOB SUB_TYPE 0 (aka BLOB SUB_TYPE BINARY).

**Comment by uslss** [comment]
@mrotteveel thanks for the answer
