### ISSUE TITLE
Open not correct source of function if two or more function have the same name in one schema

### ISSUE THREAD

**Issue by andytower** [dbeaver/dbeaver#3702]
I have schema. In this schema define two function with the same name but different parameters list. By attempt open function to edit not correct work. If I open first function it's all right. But if I open second function for edit it's open definition parameters all right but source code is code of first function.
Correct function
![1](https://user-images.githubusercontent.com/19635670/41982337-e04c7d18-7a33-11e8-9978-a7f905b09453.png)
![2](https://user-images.githubusercontent.com/19635670/41982338-e07fcbb4-7a33-11e8-80ba-aaf63cfb44c8.png)
Incorrect function
![3](https://user-images.githubusercontent.com/19635670/41982339-e0b2fdfe-7a33-11e8-82aa-06d2a68b8e62.png)
![4](https://user-images.githubusercontent.com/19635670/41982340-e0e0f920-7a33-11e8-9187-b6d0d2011936.png)

**Comment by serge-rider** [comment]
Looks like you are using "PostgreSQL Generic" driver. It doesn't support functions override.
Use standard PostgreSQL driver. In 99% cases it doesn't make sense to use Generic driver unless you are on PostgreSQL 8 or earlier.
