### ISSUE TITLE
Output tab with stranges squares

### ISSUE THREAD

**Issue by ludo23** [dbeaver/dbeaver#3703]
Hello,

Using sybase, and defncopy to get a procedure definition, I see a square on empty lines in the output tab.
It does not matter, but when I try to copy the entire script to the clipboard, I only get back to the first square.
Do you see this squares ? 
![image](https://user-images.githubusercontent.com/40636524/41983078-5b103906-7a2d-11e8-93f6-769994ac3f47.png)

Thank you for dbeaver, a very useful tool.

**Comment by serge-rider** [comment]
Most likely this is an issue in Sybase driver. According to reported behavior these special characters have zero bytes inside - that's why Windows copies only the first part.
I'll add some additional output text processing to avoid such problems.
