### ISSUE TITLE
Save view always adds a semicolon to declaration

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#3704]
I have run into a small issue while modifying views. When I change the declaration/source of a view and try to save the view, you automatically add a semicolon to the end.

At least when I change the source for a second time, there is a second semicolon added to the end, which produces an error when trying to persist the changes.

As I said, it's not a big deal. But if it's easy for you to fix, you might include the fix into one of the next releases.

Cheers

**Comment by serge-rider** [comment]
Is this Oracle?

**Comment by serge-rider** [comment]
Fixed for Oracle (semicolon was added by extra DDL transform pragma)
