### ISSUE TITLE
Doesnt show extra options applied on Table

### ISSUE THREAD

**Issue by mangaldev** [dbeaver/dbeaver#3705]
Altering table with extra options on a table is not shown anywhere. e.g. autovacuum_vacuum_threshold
,autovacuum_analyze_threshold etc which can be applied like this :
alter table entitlements.reference set (autovacuum_vacuum_threshold=1000000);
This can be seen using psql client though with command :
 \d+ entitlements.reference
![image](https://user-images.githubusercontent.com/402377/42002103-f53f7590-7a1a-11e8-8db4-5de994f40edd.png)

**Comment by serge-rider** [comment]
Thanks for noticing.
Will add them in 5.1.2.
![image](https://user-images.githubusercontent.com/6398845/42137297-9be26dbc-7d72-11e8-9ec8-97e8296b04e1.png)
