### ISSUE TITLE
Not able to do complete uninstall DBeaver

### ISSUE THREAD

**Issue by jagann2** [dbeaver/dbeaver#3707]
I am facing issue while completely uninstall the DBeaver.

Steps:
1. Installed DBeaver and Opened DBeaver
2. Selecting oracle project
3. Entering host name
4. Entering database name
5. Entering login credentials
6. Selecting Installed Oracle client
7. Test Connection
8. Uninstalling the DBeaver
9. Again installing the DBeaver
10. Still I am seeing the Oracle client in the dropdown even after uninstalling the values in the dropdown is not removed (Remove home is disabled in Native Client)
11. What should be procedure to remove the values from the dropdown while uninstalling and installing the DBeaver

![image](https://user-images.githubusercontent.com/40655775/42020095-e9a35d90-7a84-11e8-8443-be5cf5dc84e1.png)

**Comment by serge-rider** [comment]
By default all your settings, scripts, diagrams and other files are in `%HOME%\.dbeaver4` folder.
You can delete it completely or remove just some configurations. For instance drivers configuration is in file `.metadata\.plugins\org.jkiss.dbeaver.core\drivers.xml` in `.dbeaver4` folder.

**Comment by serge-rider** [comment]
Sorry, forgot about Oracle-specific home detection. DBeaver gets this configuration from Windows registry. It can;t be changed by uninstalling DBeaver. 
BTW why do need to remove client home information?

**Comment by jagann2** [comment]
Its having so many client homes and its confusing while selecting the client.
So In this case, Is there any possibilities to remove the client information for Native client?
If yes, Please let me know the procedure to do so.

**Comment by serge-rider** [comment]
Currently it is not possible to remove Oracle homes as they got from registry and PATH.
