### ISSUE TITLE
Issue Adding Stored Procedures in DBeaver

### ISSUE THREAD

**Issue by Ed35114** [dbeaver/dbeaver#3709]
When adding stored procedures using DBeaver, I often get the following error:

_Must declare the scalar variable"@XXX"_

Yet when I run the same script in other tools such as SQL Studio or DB Workbench, I don't get the error.   Any ideas?

Thanks!

-Ed Salgado

**Comment by serge-rider** [comment]
What is your database?
Could you post example of such problem procedure?
