### ISSUE TITLE
Feature Request: Change password dialog for mssql

### ISSUE THREAD

**Issue by rconn01** [dbeaver/dbeaver#3710]
It would be good if there was a change password dialog for mssql similar to this ticket for oracle https://github.com/dbeaver/dbeaver/issues/3365

When I try to log into a database that requires a password change, the login fails and I have no way to change the password from dbeaver. A sample error message is

```
Login failed for user '<user>'.  Reason: The password of the account must be changed. ClientConnectionId:f3d4cf71-619e-4d2b-bfd9-1ebf8fe5a657
```

I couldn't find anyway to change my password from dbeaver as it is

**Comment by brunobaiano** [comment]
Good afternoon,
any news in this request?
It would be really good

**Comment by LonwoLonwo** [comment]
Hello.
We added the ability to change the current user password for SQL Server in previous releases.
https://github.com/dbeaver/dbeaver/wiki/Change-current-user-password

![2021-10-01 10_28_42-Window](https://user-images.githubusercontent.com/45152336/135582216-5dcbed67-2da1-4d77-a18d-aa67265cfcd8.png)

But unfortunately, SQLServer doesn't work like Oracle. Oracle allows you to open a connection if the password is expired. And SQLServer is not. We simply do not have the technical ability to send a request from the client-side to change the password when the user uses the expired password.

If you have any ideas on how to solve this problem - please share.

**Comment by parthkvv** [comment]
> It would be good if there was a change password dialog for mssql similar to this ticket for oracle #3365
> 
> When I try to log into a database that requires a password change, the login fails and I have no way to change the password from dbeaver. A sample error message is
> 
> ```
> Login failed for user '<user>'.  Reason: The password of the account must be changed. ClientConnectionId:f3d4cf71-619e-4d2b-bfd9-1ebf8fe5a657
> ```
> 
> I couldn't find anyway to change my password from dbeaver as it is

Facing a similar issue. Did you find any solution to this?
