### ISSUE TITLE
Unable to connect Oracle database

### ISSUE THREAD

**Issue by jagann2** [dbeaver/dbeaver#3711]
Unable to connect oracle database

Even after giving the "host", "database", "port" & "credentials".

Its showing the below error:

IO Error: The Network Adapter could not establish the connection
  The Network Adapter could not establish the connection
    java.net.ConnectException: Connection timed out: connect

![image](https://user-images.githubusercontent.com/40655775/42073205-170d7834-7b33-11e8-8394-88941b317c07.png)

**Comment by infectormp** [comment]
can you connect to db using telnet?

**Comment by serge-rider** [comment]
@jagann2 Seems to be the same issue: #4229
Try to configure connection timeouts (it is 20 seconds by default)

**Comment by MuhammadimYusoff** [comment]
not solved but closed?

Okay.

**Comment by tati-kru** [comment]
@MuhammadimYusoff this issue is duplicate for #4229 that was fixed in the version 5.2.1. If you can reproduce the problem, please, create a new issue.
