### ISSUE TITLE
MariaDB GRANT syntaxis error

### ISSUE THREAD

**Issue by infectormp** [dbeaver/dbeaver#3713]
When creating user and grant to this user all table privileges we get error:
> SQL Error [1064] [42000]: (conn=6216) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'versioning rows ON ...

In SQL Preview i see this this syntaxis:
> GRANT Delete versioning rows ON xxx.* TO 'xxx'@'localhost' ;
According to MariaDB [documentation](https://mariadb.com/kb/en/library/grant/#table-privileges) syntaxis must be GRANT DELETE HISTORY ON xxx.* TO 'xxx'@'localhost' ;

So Delete versioning rows in Table Privileges GUI must be renamed too.

MariaDB 10.3.7

**Comment by serge-rider** [comment]
Thanks for bugreport.
