### ISSUE TITLE
5.1.1 version shows error message in vertical bar

### ISSUE THREAD

**Issue by mnt1979** [dbeaver/dbeaver#3715]
Dbeaver 5.1.1 shows error in vertical bar. When error message is too big, it expands vertically and hides ok, cancel buttons.     Shouldn't it show high level error message and optionally detailed message by clicking a more detail button with multiline textbox with scrollbar instead?
![dbeaver error message](https://user-images.githubusercontent.com/40701061/42108640-bedfcb44-7ba0-11e8-9ff0-22416320bce5.PNG)

**Comment by serge-rider** [comment]
This seems to be a Hive-specific issue. Error message itself is too huge (as it contains stacktrace inside).
I think we should just limit message size somehow.

**Comment by serge-rider** [comment]
This issue will be resolved in #3733
