### ISSUE TITLE
Ctrl+Space does not switch to "Enter a SQL expression to filter..."

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#3720]
OS: windows 10 (1803), macOS 10.13.5
Dbeaver: 5.1.2

Result:
In maximized result view I was thinking of pressing Ctrl+Space to enter expression. However pressing the keys does nothing. Tested on 2 different machines.

Expected result:
To enter a expression for sorting to use keyboard only instead of having to click around all the time. If the shortcut is meant to do something different then it should be listed different IMO. In my eyes the shortcut in the topic does indicate to "focus the area on Ctrl+Space".

Can someone reproduce this?

**Comment by serge-rider** [comment]
I can't reproduce that.
In my envs it shows column list.
Does <kbd>ctrl+space</kbd> work in SQL Editor?

**Comment by nmat** [comment]
Ctrl+Space does show the dropdown for syntax and table list.

But the Expression part seems to not work when result window is focused.

**Comment by nmat** [comment]
Right so....I might understand it wrong.

Ctrl+Space does not focus from result -> expression area. But is used in the same way as getting items in SQL editor?

**Comment by serge-rider** [comment]
Well, what I see when focus is in filter input text and <kbd>ctrl+space<kbd> was pressed:
![image](https://user-images.githubusercontent.com/6398845/42179565-25ab0890-7e3d-11e8-8a09-8c9340b7b6e2.png)

I'm afraid I don't fully understand the use-case. Could you post a screenshot?

**Comment by nmat** [comment]
Right so I am thinking wrong.

When I saw the Ctrl+Space I thought it would be to place focus on the field. Therefore I am wrong.

Is it possible to place focus on the field with a shortcut? that is going from editor -> to the field or from result view -> field for quick filter?

**Comment by serge-rider** [comment]
Yeah, it is <kbd>CTRL+SHIFT+F</kbd> what switches between filter and grid.
Actually most of such commands are in the context menu.

**Comment by nmat** [comment]
Many thanks! issue solved! 👍

**Comment by zensabbah** [comment]
And for Mac?

**Comment by abuergo** [comment]
For mac: ⌃⌥⇧T (Activate filter/data editor)

**Comment by nikiromagnoli** [comment]
And what about Ubuntu (20.04 here)?
Neither `Ctrl+Shift+F` and `Ctrl+Shift+Alt+T` work.

**Comment by nikiromagnoli** [comment]
Ok solved: by default the shortcut is `Ctrl+Shift+Alt+T` but in Ubuntu it generates some kind of conflict as it flashes "Data" tab name and nothing happens.

So just tweak the shortcut to the one you prefer in settings: "User interface" > "Keys" and change the key combination for "**Activate filter/data editor**".
![immagine](https://github.com/dbeaver/dbeaver/assets/5136855/5f1d50c8-136e-495d-8cc7-0cb86390997b)
For example I set the aforementioned `Ctrl+Shift+F`, quite handy. Toggling this combination will switch focus between filter row and data table.
