### ISSUE TITLE
Export Resultset to SQL INSERT: Table name exported as "NULL"

### ISSUE THREAD

**Issue by Zabbah** [dbeaver/dbeaver#3722]
Hello.
When you export resultset to SQL INSERT statements, table name in export file is NULL, instead of table's name.

Example:

_INSERT INTO null (column1, column2) VALUES ('1234','5678');_

should be

_INSERT INTO mytablename (column1, column2) VALUES ('1234','5678');_

Edit: This worked well in 5.1.0, bug is in versions 5.1.1 and 5.1.2
Edit2 : Seems that schema name is not working either, you can check or uncheck "Omit schema name" in exporter settings, but in the export file schema name won't show either,

**Comment by p91paul** [comment]
I confirm this bug and, as a workaround, you can use select * from tablename in a sql script and export from there. The bug is present in the table view only.
