### ISSUE TITLE
SQL Clause dblink missing (for postgresql) really usefull to request a remote postgresql database

### ISSUE THREAD

**Issue by Xpunk** [dbeaver/dbeaver#3723]
A feature request : The clause dblink is not yet implemented.
https://www.postgresql.org/docs/9.3/static/contrib-dblink-function.html
Its not an emergency but it could be very cool for the next release...
Thanks by advance.

**Comment by serge-rider** [comment]
Could you clarify it a bit. dblink is just a regular PG function and can be used along with other PG function in SQL queries (just in stall it with `CREATE EXTENSION dblink;`).
Do you mean some special UI for that?

**Comment by Xpunk** [comment]
No No, you're right, it's working wekll. sorry to add false issue. I'm closing it ! No need anything else...Thanks
