### ISSUE TITLE
FOREIGN TABLE DDL

### ISSUE THREAD

**Issue by datopalov** [dbeaver/dbeaver#3724]
Foreign table creation ddl is wrong...

Expected Result:
CREATE FOREIGN TABLE ...(
    ...
)
    SERVER ...
    OPTIONS (schema_name '...', table_name '...');

Actual Result:
CREATE TABLE ... (
	...
) ;

Info:
Postgresql 10
Windows 10 64x
Community Edition 5.1.2 - Windows 64 bit (installer + JRE)

**Comment by serge-rider** [comment]
Thanks for bug report
