### ISSUE TITLE
Execute button disappeared in 5.1.2 toolbar

### ISSUE THREAD

**Issue by creekwise** [dbeaver/dbeaver#3730]
I just installed 5.1.2 update and the triangle Execute button disappeared from the toolbar. Now I have to right click after highlighting my statement to execute.

I was trying to modify the toolbar but couldn't find a way to do it. I sincerely hope there is a way to do it (or bring back Execute button) -- otherwise I will have to revert to the previous version because not having Execute in my toolbar is majorly annoying, I really hope I am doing something wrong but the button disappeared in 5.1.2.

**Comment by serge-rider** [comment]
All execute buttons are now in the vertical toolbar on the left side of editor: 
![image](https://user-images.githubusercontent.com/6398845/42185678-7a9f8a64-7e52-11e8-8022-81553c700a58.png)

**Comment by creekwise** [comment]
Well mine is an ORANGE triangle on an ORANGE background... Any way to change the color?
![dbeaverexecute](https://user-images.githubusercontent.com/15185317/42185834-65edd93e-7e18-11e8-868a-6653f744fb20.jpg)

**Comment by serge-rider** [comment]
Oh, this is because of your connection type color.
Definitely an issue. Will try to fix this somehow.

Workaround: change connection type color to something less bright (connection properties->General->Connection type->Edit)

**Comment by creekwise** [comment]
Oh that's true -- connection type !!  Thanks

**Comment by creekwise** [comment]
But still, the question remains -- is there any way to put the Execute button on the top toolbar, which is gray and not subject to inadvertent camouflage?

**Comment by serge-rider** [comment]
No, it is not possible. We refused usage of main toolbar for editor actions. This was non obvious for many users, consumed too many horizontal space and generally was not very good looking (because main toolbar changed all the time).

I think we'll fix this issue by removing connection coloring for left vertical toolbar.

**Comment by veithflo** [comment]
I use hotkeys instead of this buttons, so the vertical toolbar is now in my way, an ugly block in the middle of the screen. Is there a way to hide it?

**Comment by serge-rider** [comment]
No. it is not supported at the moment
