### ISSUE TITLE
Postgres TIMESTAMP domains not displayed with date

### ISSUE THREAD

**Issue by rfc7230** [dbeaver/dbeaver#3731]
DBeaver 5.1.2 on Windows 8.1 using either of the PostgreSQL drivers.

For Postgres domains (data types) derived from `TIMESTAMP` or `TIMESTAMPTZ`, DBeaver doesn't display the date portion of the values in the data editor.

To reproduce the problem, open the SQL editor for a Postgres DB and run the following:

````sql
CREATE DOMAIN ts_type timestamptz;

CREATE TABLE test_table
	(
	a timestamptz,
	b ts_type
	);

INSERT INTO test_table
VALUES ( current_timestamp, current_timestamp );

SELECT * FROM test_table;
````

You'll see the dates correctly displayed:

![dbeaver timestamp bug 1](https://user-images.githubusercontent.com/40779160/42193071-3769afd8-7e32-11e8-81cc-a38da3480c22.png)

Next, in the database navigator, hit Refresh on the public schema so the new table and data type will show up:

![dbeaver timestamp bug 2](https://user-images.githubusercontent.com/40779160/42193315-811ac9c2-7e33-11e8-8625-01cc6e6cd5fc.png)

Now run the select statement again. The column with the derived type will only show the time, not the date:

![dbeaver timestamp bug 3](https://user-images.githubusercontent.com/40779160/42193344-a94bb06e-7e33-11e8-853d-379837c97131.png)

This bug affects any preexisting table with `TIMESTAMPTZ`-derived column types---the data show up without the dates, which is quite a problem. Casting the result to `TIMESTAMPTZ` doesn't help.

````sql
SELECT a, b::timestamptz FROM test_table;  -- same result
````

**Comment by serge-rider** [comment]
It is a bug in domain type resolution.
Thanks for detailed bug report.
