### ISSUE TITLE
Icon and Title spacing display issues

### ISSUE THREAD

**Issue by huynhthien3009** [dbeaver/dbeaver#3732]
I've just downloaded DBeaver Community Edition ver 5.1.2 and when open it, i have an display issue like that.

![image](https://user-images.githubusercontent.com/29039304/42195191-e7a347a0-7ea1-11e8-955d-d12c66d2f8ed.png)

It does not have space between those icon and title.

My display resolution is 2560x1440 and zoom in 175%. But I don't think thats the problem cause I've tried put the program in my 1920x1080 with 100% scale and it's still happen.

Is there any ways to fix this?.

**Comment by serge-rider** [comment]
It is a known glitch with Dark theme and HighDPI screens with zoom.
And it is actually a bug in Eclipse platform. We going to fix this in one of the next version.

Workaround: use Classic theme.

**Comment by serge-rider** [comment]
This bug actually - https://bugs.eclipse.org/bugs/show_bug.cgi?id=496849

**Comment by nmat** [comment]
noticed this in 5.2.4 also so I guess its not fixed yet?

**Comment by serge-rider** [comment]
Unfortunately :(
You could try Darkest Dark theme. It is better and it is working fine on HighDPI.

https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle

**Comment by nmat** [comment]
Darkest theme does give some better result.

I wonder however 2 things:
1. Is it java/eclipse that is stopping for dark theme to be worked on or lack of people to help with the dark theme?
2. Maybe the dark theme could be a bounty - or even documented in the wiki? Someone could help maybe if its not so much java/eclipse issues?

**Comment by serge-rider** [comment]
Yes, it is Eclipse-related problem.
As far as I know Eclipse foundation lacks free hands all the time. Sometimes I report bugs and contribute small patches but can't participate in platform support because spend all my free time in DBeaver project.
