### ISSUE TITLE
Internal jdbc driver error when no white space after dollar quote in function definition

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#3734]
These PostgreSQL queries are problematic in DBeaver:

```
CREATE FUNCTION normalizecode(str text) RETURNS text
    LANGUAGE sql IMMUTABLE STRICT
    AS $$SELECT translate(str, '- 	', '')::text;$$;
```
```
CREATE OR REPLACE FUNCTION normalizecode(str text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE STRICT
AS $function$SELECT translate(str, '- 	', '')::text;$function$
```
The first one was created by pg_dump 9.6, the other was created by DBeaver in the functions Source pane. The function was created in PgAdmin 3. DBeaver shows this error:

```SQL Error: Internal jdbc driver error
  Internal jdbc driver error
    
    java.lang.ArrayIndexOutOfBoundsException
```
The problem seems to be the first dollar quote $$ or $$function$$ - when the function's code follows the quote immediately then DBeaver can't accept it. When I add a space or a newline after the quote then the query is executed.

When looking at [dollar quoting specification](https://www.postgresql.org/docs/10/static/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING) there is no requirement of using whitespace after the opening quote. And these queries work fine in PgAdmin.

I found similar bugs like #900 and #1250 - but I don't know if they relate to the same problem. When I try running the problematic queries from those bug reports in DBeaver 5.1.2 they both execute fine so I suspect those bugs have been fixed already.

The semi-colon also appears to be important here:

`SELECT $$some text;$$;`
results in error.

`SELECT $$some text$$;`
runs fine.

**Comment by serge-rider** [comment]
Yes, actual bug is in parsing dollar sign followed with letter characters. This clashes with SQL dialect standards (as dollar is valid characters for SQL identifiers).

Will try to resolve in one of next versions, thanks for detailed report

**Comment by lemon-juice** [comment]
I've read up more on this and indeed there seems to be a jdbc bug where dollar quotes are not recognized by the driver and the query may be split by a semicolon even if the semicolon is within the dollar quotes. I've found a few similar jdbc bugs some of which seem to be fixed but I couldn't figure out if they related to this problem.

However, the strange thing is that when I select all text in the DBeaver SQL editor and press "Execute SQL Statement" then all the problematic queries I mentioned above run fine! Even when I enter multiple queries, each with dollar quotes like this:

```
SELECT $$some text;$$;

CREATE OR REPLACE FUNCTION normalizecode(str text) RETURNS text
    LANGUAGE sql IMMUTABLE STRICT
    AS $$SELECT translate(str, '- 	', '')::text;$$;
    
CREATE OR REPLACE FUNCTION normalizecode2(str text) RETURNS text
    LANGUAGE sql IMMUTABLE STRICT
    AS $$SELECT translate(str, '- 	', '')::text;$$;
```
They are all executed without any problems. So DBeaver definitely is able to run such queries but the errors happen when I use "Execute SQL Script" command. I don't know what is the difference between executing script vs selecting all and executing SQL statement but there must be some.

Maybe a solution could be to change "Execute SQL Script" to do the same thing internally as "Execute SQL Statement" with everything selected? Just an idea since I'm not sure if this wouldn't cause some unwanted side effects.

**Comment by serge-rider** [comment]
When you execute script DBeaver splits script on separate statements using native delimiters or/and empty lines.
It just can't work exactly the same way as with standalone statement.

So the actual bug is in delimiter recognition function.

**Comment by lemon-juice** [comment]
Yes, I'm sure you are right that the bug is in delimiter recognition function, I was just wondering why there is no problem with delimiter recognition when I use "Execute SQL Statement" on multiple statements.

**Comment by mickeyjf** [comment]
I see that there is still a related issue in version 6.1.3. It took me a while to find this page and the "select the entire function to execute" workaround. I get different error messages but the problem is solved the same way. I'm guessing that if this is a problem in the jdbc driver that implies that it is outside of the immediate control of the DBeaver developers and is not liable to be corrected until the jdbc driver folks get to it? Or am I misunderstanding who's code is who's?

**Comment by nicklaich** [comment]
Let me jump in this train and add my two cents.
it seems dollar-quoted function bodies  with numbers in quote label works in 50% cases.
e.g: Version 6.3.0.201912021731, this gets error, but if you remove numbers from quote label, or ";" after moo it works.
```
create or replace function foo1()returns text
language sql
as $foo1$
select 'moo';
$foo1$;
```

**Comment by serge-rider** [comment]
Can't reproduce anymore.

**Comment by serge-rider** [comment]
Query for test:

`SELECT $$some TEXT$$;`

**Comment by lemon-juice** [comment]
Yes, seems to be fine in 7.2.0.

**Comment by serge-rider** [comment]
Now it must handle $$ inside identifiers ok.

**Comment by uslss** [comment]
For now, query execution fails in the special case mentioned in the video below
![2020-10-13_14h02_50](https://user-images.githubusercontent.com/31996417/95852738-e9776380-0d5c-11eb-8b9b-7f363aa584da.gif)

Script
```sql
SELECT $$some TEXT;$$;

SELECT $$some TEXT;$$;
```

**Comment by serge-rider** [comment]
@uslss we can't support such cases. Because DBeaver executes query starting from the first delimiter to the left of cursor.
It is `;` in this case. In fact it is a mess of delimiters.

Workarounds: 
- Select your query and run it (ctrl+enter)
- Run it as a script (alt+x)
- Switch to `Show $$ quote as string` mode.
