### ISSUE TITLE
Scheme compare

### ISSUE THREAD

**Issue by Speirs47** [dbeaver/dbeaver#3735]
I'm aware that it is a huge feature request but it would be nice if scheme compare functions were expanded. Current scheme compare is hard to read (at least for me), displays many irrelevant information (if I want to compare schemes I want to know what columns changed, which views changed, which procedures changed, etc., not how many rows is in each scheme) and doesn't offer automatically generate script (which is the biggest part I guess so I don't expect that to happen anytime soon).

The best scheme compare I know and use is Redgate's Scheme Compare and I think you might like to check out their approach to that problem.

**Comment by serge-rider** [comment]
Yes, this makes very much sense, We have a feature request #957 for that. And it relies on #3384 (Liquibase integration).

That will require quite a lot of effort but we going to support this in the next major version (5.2). Although I'm not sure that it will be included in community version immediately.

**Comment by Speirs47** [comment]
Well, I may talk my company into buying Enterprise Edition as you are doing a very good job.
