### ISSUE TITLE
Tablename/variables highlighting

### ISSUE THREAD

**Issue by Speirs47** [dbeaver/dbeaver#3736]
In SQL editor it would be nice if when I set my cursor on table name/column name/variable/etc it would highlight every word that matches the one I got my cursor on.

Here's what I mean:
![obraz](https://user-images.githubusercontent.com/40421338/42208356-4e90546c-7eac-11e8-9d7c-74f626ad6565.png)

**Comment by serge-rider** [comment]
This feature was implemented in 5.3.x
