### ISSUE TITLE
Mac version always opens file with default app instead of DBeaver

### ISSUE THREAD

**Issue by vulkman** [dbeaver/dbeaver#3737]
Whenever I use File -> Open and try to open an SQL file, DBeaver doesn't open it itself but triggers the default app associated with this file type on the OS level.

I would expect that DBeaver always opens files itself.

**Comment by serge-rider** [comment]
Seems to be MacOS specific

**Comment by serge-rider** [comment]
Actually I can't reproduce this on MacOS. It opens all unrecognized file types using system default application but *.sql files should be opened by DBeaver itself.
Moreover it is configurable in preferences. Please check it:
![image](https://user-images.githubusercontent.com/6398845/42415180-15a26c16-824f-11e8-82fb-a6b717b45a1f.png)
