### ISSUE TITLE
Oracle Create Procedure Throws Invalid SQL Statement

### ISSUE THREAD

**Issue by isapir** [dbeaver/dbeaver#3742]
There is a bug with Oracle Database CREATE PROCEDURE.  In DBeaver 5.1.2 the code below throws:

>SQL Error [900] [42000]: ORA-00900: invalid SQL statement
>  ORA-00900: invalid SQL statement

But it executes without a problem on the Oracle SqlDeveloper Client.

	CREATE PROCEDURE  contens_reset_sequence (
		seqname 	IN NVARCHAR2,
		tblname 	IN NVARCHAR2,
		tblfield 	IN NVARCHAR2
	)
	IS
		maxtable 	INTEGER;
		sqlstring	VARCHAR2(100);
	BEGIN
		-- get max value from table
		sqlstring := 'SELECT MAX(' || tblfield || ') + 1 FROM ' || tblname;
		EXECUTE IMMEDIATE sqlstring INTO maxtable;

		IF (maxtable IS NULL) THEN
			maxtable := 1;
		END IF;

		sqlstring := 'ALTER SEQUENCE ' || seqname || ' RESTART START WITH ' || maxtable;
		EXECUTE IMMEDIATE sqlstring;
	END;

![image](https://user-images.githubusercontent.com/885907/42236946-3e080e46-7eb1-11e8-98f2-772030d07995.png)

**Comment by Zardoz89** [comment]
Another example : 

```
CREATE OR REPLACE PROCEDURE EnableAllConstraint_sp AUTHID CURRENT_USER AS
/*
||Purpose: Enables all foreign Keys.
||
||Author: Regis Biassala
||Datalex plc (c) 2002.
*/
    TYPE Constraints_CUR IS REF CURSOR;
    v_cons_CUR Constraints_CUR;
    l_Constraint_name user_constraints.constraint_name%TYPE;
    l_table_name user_constraints.table_name%TYPE;
    v_code  NUMBER;
    v_errm  VARCHAR2(64);

BEGIN
    OPEN v_cons_CUR FOR
        'SELECT constraint_name, table_name FROM user_constraints
                WHERE constraint_type = ''R'' ORDER BY constraint_type';
        LOOP
            FETCH v_cons_CUR INTO l_Constraint_name, l_table_name;
            EXIT WHEN v_cons_CUR%NOTFOUND;

            DBMS_OUTPUT.PUT_LINE('Enabling constraint '||l_Constraint_name);
            EXECUTE IMMEDIATE
                'ALTER TABLE'||' '||l_table_name||' '||'ENABLE CONSTRAINT'||' '||l_Constraint_name;

        END LOOP;
    CLOSE v_cons_CUR;
EXCEPTION
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_errm := SUBSTR(SQLERRM, 1, 64);
        DBMS_OUTPUT.PUT_LINE ('Error enabling constraint -> ' || 'Error code ' || v_code || ': ' || v_errm);
END EnableAllConstraint_sp;
/
```

**Comment by uslss** [comment]
already fixed.
ticket closed
