### ISSUE TITLE
call MySQL Procedure result error

### ISSUE THREAD

**Issue by chenyu-emma** [dbeaver/dbeaver#3744]
Hi
I created a procedure like this :

CREATE PROCEDURE pro3(in p_in int)
begin select p_in;set p_in=100;select p_in;end 

when I execute the script "call pro3(10)" ,the correct result should be "p_in=10; p_in=100", but I got the result from dbeaver is "p_in=10".

**Comment by serge-rider** [comment]
I see two resultsets, one with 10 and another with 100.
![image](https://user-images.githubusercontent.com/6398845/42413770-c766f978-822f-11e8-8905-f32d107848f4.png)

What driver (version) do you use?

**Comment by chenyu-emma** [comment]
thanks for your reply.
I used mysql-connector-java-5.1.44 driver verison , and the  dbeaver version is 3.7.7.
I tested again and got only one result p_in=10

**Comment by chenyu-emma** [comment]
Hi
I download the latest version dbeaver-5.1.2,and got the correct result
so maybe it's because the dbeaver's version that I used is too old.

**Comment by serge-rider** [comment]
Yes, 3.x didn't support multiple results for MySQL.
