### ISSUE TITLE
Feature request: Oracle: Extendt properties for materialized view

### ISSUE THREAD

**Issue by progsurfer** [dbeaver/dbeaver#3746]
Hi thanks for a great Job.

Is it' possible to extend  the properties for the materialized view in Oracle, when the view was refreshed ?

The information is stored in a system table:

SELECT owner, mview_name, last_refresh_date  FROM all_mviews WHERE owner = 'SCHEMA'

Thank you and best regards

Denis

**Comment by serge-rider** [comment]
This property is already there. You can view it in materialized view editor or in view list. Right click on table header -> Configure columns (btw this options is available for most of DBeaver tables)

**Comment by progsurfer** [comment]
Thanks for the answer,

I know this property, but i cant find the information when the MV was refreshed.

![grafik](https://user-images.githubusercontent.com/24592280/42437611-e5e631be-835d-11e8-863f-7494a35f713c.png)


I would like to see in properties:

![grafik](https://user-images.githubusercontent.com/24592280/42437663-0ab5ff38-835e-11e8-87e1-695149e60277.png)


From:
SELECT owner, mview_name, last_refresh_date FROM all_mviews WHERE owner = 'DIGIPERF'


Thanks

**Comment by progsurfer** [comment]
I found it, 

thanks for reply .

Best regards

Denis
