### ISSUE TITLE
Unable to edit the data in column in table data explorer on Mac OS.

### ISSUE THREAD

**Issue by git265** [dbeaver/dbeaver#3749]
I cannot edit the column data inline while viewing the table data contents. This is on Mac  and atleast started seeing this issue from 5.0+ version. Please see below the screenshot.
![image](https://user-images.githubusercontent.com/4753090/42275596-d03332b6-7f5e-11e8-9ba3-7b252f9990a8.png)

**Comment by serge-rider** [comment]
What is your database?

**Comment by uslss** [comment]
There is no updates on issue more than a year. Ticket is closed.
If issue is still reproducible for you feel free to reopen the ticket or create a new one.
