### ISSUE TITLE
Question: org.jkiss.dbeaver.ext.wmi cannot be found when Export Product for linux

### ISSUE THREAD

**Issue by liuyuanyuan** [dbeaver/dbeaver#3751]
Error Detail: 
Cannot complete the install because one or more required items could not be found.
 Software being installed: DBeaver 5.1.0 (org.jkiss.dbeaver.core.product 5.1.0)
 Missing requirement: org.jkiss.dbeaver.ext.wmi.nls 1.0.17 requires 'bundle org.jkiss.dbeaver.ext.wmi 0.0.0' but it could not be found
 Cannot satisfy dependency:
 Cannot satisfy dependency:

**Comment by serge-rider** [comment]
It is a bug in packaging, WMI is Windows-only feature.
Thanks for noticing.
