### ISSUE TITLE
DB Full Text Search: Search button always greyed out due to inability to select entities in databases window.

### ISSUE THREAD

**Issue by Monolith-681** [dbeaver/dbeaver#3753]
* Ubuntu 18.04
* DBeaver 5.1.2
* PostgreSQL 9.6.6
* Linux kernel: 4.15.0-24-generic

Hello,

in recent versions of DBeaver (5.1.0 - 5.1.2, i did not check earlier versions) the "Search" Button in DB Full Text always stays inactivated since you are not able to select a database, database schema  or table in the selection window.
If you select an entity, the menu collapses and resets to a state where no selection was made.

Please have a look at this issue since the Full text search is very important for us.

Thanks a lot!

**Comment by tati-kru** [comment]
Thank you for the bug report

**Comment by serge-rider** [comment]
This happens with PostgreSQL because of bugs in active database switcher (full-text searcher tries to search in all databases and fails during connection switch).
But we also need to improve full-text search UI in general.

**Comment by serge-rider** [comment]
Data/metadata searchers will be significantly improved in 5.1.3.
