### ISSUE TITLE
Bug on sql extraction from source code

### ISSUE THREAD

**Issue by alesc2000** [dbeaver/dbeaver#3754]
When I have commented lines in the copied source code text, and the comment contains double quotes, the extraction of SQL fails:

Source code: 

```
"SELECT a, b, c \n" +
"\tFROM config1 \n" +
//config2 table"
"UNION ALL \n" +
"SELECT a, b, c \n" +
"\tFROM config2 ";

```
Paste in editor:

```
SELECT a, b, c 
	FROM config1 

                 +
                 +
```
                
Paste without quote in the comment:
```

SELECT a, b, c 
	FROM config1 
UNION ALL 
SELECT a, b, c 
	FROM config2 
```

DBeaver 5.1.2, Ubuntu 18.04

**Comment by uslss** [comment]
Issue isn't reproduced on 6.0.3
