### ISSUE TITLE
Timestamp not correct on resultset

### ISSUE THREAD

**Issue by douglaszickuhr** [dbeaver/dbeaver#3756]
Hi!

Since I got version 5.1.0 from DBeaver EE timestamps are not being shown correctly on the result set. It seems that there is some timezone function being applied on that. Apparently it is happening just on MySQL connections. 

Is there any new configuration that could be affecting that?

Please find attached some screenshots.
![image](https://user-images.githubusercontent.com/12372536/42334554-76c8c2c8-8075-11e8-9beb-6a3a901b3aad.png)
![image](https://user-images.githubusercontent.com/12372536/42334557-7c76474a-8075-11e8-9b92-5a211937beab.png)

Dbeaver 5.1.0 EE on Mac OS 10.13

**Comment by serge-rider** [comment]
It is aa known issue with recent MySQL 8.x driver.
We'll add older MySQL driver in both CE and EE in the next version (see #3743).

Workarounds:
1. Set serverTimezone driver property to a proper value (see available timezones at https://github.com/dbeaver/dbeaver/wiki/JDBC-Time-Zones)
2. Downgrade MySQL driver version to 5.x. This can be done in driver editor dialog. It is a bit tricky for DBeaver EE (you'll need to delete existing jars and add Maven artifact `mysql:mysql-connector-java`).

**Comment by douglaszickuhr** [comment]
> Set serverTimezone driver property to a proper value (see available timezones at https://github.com/dbeaver/dbeaver/wiki/JDBC-Time-Zones)
Thanks for that @serge-rider.
