### ISSUE TITLE
Problem Installing DBeaver Office integration  - Conflicting Dependency

### ISSUE THREAD

**Issue by Robert4wd** [dbeaver/dbeaver#3757]
Hi Team
I have just started with DBeaver 5.1.0 and am very impressed so far. I am trying to Office Integration on my Windows 10 Machine. I get the following error message. Any Suggestions? Thank you
Regards
Robert
Cannot complete the install because of a conflicting dependency.
Software being installed: DBeaver Office Support 1.1.24 (org,jkiss.dbeaver.ext.office.feature.feature.group 1.1.24)
Software currently installed: DBeaver Enterprise 5.1.0 (com.dbeaver.core.product 5.1.0)
Only one of the following can be installed at once:
DBeaver Office Support 1.1.22 (org.jkiss.dbeaver.data.office 1.1.22)
DBeaver Office Support 1.1.24 (org.jkiss.dbeaver.data.office 1.1.24)
Cannot satisfy dependency:
From: DBeaver Enterprise 5.1.0 (com.dbeaver.core.product 5.1.0)
To: com.dbeaver.ee.application.feature.feature.group [5.0.1]
Cannot satisfy dependency:
From: DBeaver 5.0.1 (com.dbeaver.ee.application.feature.feature.group 5.0.1)
To: orgjkiss.dbeaver.ext.office.feature.feature.group [1.1.22]
Cannot satisfy dependency:
From: DBeaver Office Support 1.1.22 (org.jkiss.dbeaver.ext.office.feature.feature.group 1.1.22)
To: org.jkiss.dbeaver.data.office [1.1.22]
Cannot satisfy dependency:
From: DBeaver Office Support 1.1.24 (org.jkiss.dbeaver.ext.office.feature.feature.group 1.1.24)
To: org jkiss.dbeaver.data.office [1.1.24]

**Comment by JamesInform** [comment]
I solved this issue as described in this solution!

https://github.com/dbeaver/dbeaver/issues/2464

**Comment by serge-rider** [comment]
Thanks for info, it might useful for others.
