### ISSUE TITLE
MSSQL 2016 - Store Procedure - Column Name does not align in list with icons

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#3758]
DBeaver version: 5.1.2

Description:
In Edit procedure I get the following below from the procedure parameters. It does not seem to align correctly. Only visual problem.

Screenshot:
![image](https://user-images.githubusercontent.com/383031/42363829-4ae91f0c-80f9-11e8-9b29-b43389fe1bb8.png)

**Comment by serge-rider** [comment]
Thanks for report.

Workaround: you can move columns by drag-n-drop (in most of DBeaver table views), so you can put Name column (the one with the icon) first.
