### ISSUE TITLE
MSSQL - Store Procedure - visual question

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#3759]
DBeaver version: 5.1.2

When adding the store procedure from the list of functions.

I get something along with: dbo.[procedurename;1](:@value, :@value)

What is up with the ;1? (don't see if in the name if I check the procedure information anywhere)

Also what does :@ mean for the values? Is there a reason for :@ to be used here?

**Comment by serge-rider** [comment]
I'm not sure I got this. Could you post a screenshot?
