### ISSUE TITLE
Can't use find (Ctrl+F) in Value tab

### ISSUE THREAD

**Issue by sanelson2000** [dbeaver/dbeaver#3762]
The find dialog does not search the contents of the Value tab.  This is especially important when looking at CLOBs with large amounts of text embedded in them.

**Comment by serge-rider** [comment]
I could add Find/Replace action in editor context menu, that'll be easy.
Better workaround: you can open you LOB contents in a separate editor (shift+enter -> open editor). CTRL+F works there already.

**Comment by cyberbeat** [comment]
Why does CTRL+F still does not work in the cell-data-editor? Is that a bug, or an unsolvable technical limitation?

**Comment by sanelson2000** [comment]
@cyberbeat The key combination CTRL+F (or CMD+F) has never worked AFAIK, to search in the data editor, however you can now right click on the pane and select Find/Replace from there, and that does seem to work.  Not sure if there is a technical limitation as to why the key combination was not implemented.
