### ISSUE TITLE
I can't modify cell in resultset. Earlier this function was work. It is very necessary function and it not work. 

### ISSUE THREAD

**Issue by nkiseev** [dbeaver/dbeaver#3763]

**Comment by serge-rider** [comment]
Can't reproduce. Please provide more details. 
- What is your database
- How do you edit cells (in table editor or in custom query results).
- Are you sure that exactly the same results were editable in earlier versions?

**Comment by nkiseev** [comment]
Sorry. I rechecked and made sure that I can edit cell in the result of query for MySQL and PostgreSQL.
I can't edit cell for Amazon Redshift, after update the driver for this DB. 
It is driver issue (i think) or interaction between DBeaver and Driver Amazon Redshift.

I tried edit cell in the custom query results.

**Comment by serge-rider** [comment]
This was fixed in 5.1.5.
