### ISSUE TITLE
problem to download driver files

### ISSUE THREAD

**Issue by paranoid73** [dbeaver/dbeaver#3766]
Hello ,
I use  arch linux,i tried to use but I can not download driver file 
i get `java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
`
my java version
`openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)
`
someone could help me?

**Comment by serge-rider** [comment]
Could you post full error stacktrace? You can get it in Error Log view or in log file (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by serge-rider** [comment]
Thanks for logs. 
This is a crazy error, some base Java method can't be found. I've googled and I see that this may happen with some Java  9 versions, however you have Java 8..

Anyhow, I've fixed this by changing files copying algorithm for Maven artifacts. 
This must help.

**Comment by Eusebius1920** [comment]
I am getting the same issue on arch using jre-**8**-openjdk. If I use jre-**10**-openjdk everything works as expected. (jre-9 is not officially supported by arch)

**Comment by serge-rider** [comment]
Please check this in 5.1.3 version

**Comment by Eusebius1920** [comment]
@serge-rider 5.1.3 was released as community package on archlinux and with 5.1.3 everything works as expected with java-8
