### ISSUE TITLE
[Oracle] Tablespaces used/available sizes wrong

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#3768]
After implementation in #3694, I noticed that sizes get multiplied when there are many data files per tablespace. My query was wrong (joining segments and datafiles was the issue) and should be split in 2:
```sql
SELECT
	t.tablespace_name,
	SUM(f.bytes) available_space
FROM
	sys.dba_tablespaces t
LEFT JOIN sys.dba_data_files f ON
		t.tablespace_name = f.tablespace_name
GROUP BY
	t.TABLESPACE_NAME;
```
```sql
SELECT
	t.tablespace_name,
	SUM(s.bytes) used_space
FROM
	sys.dba_tablespaces t
LEFT JOIN sys.dba_segments s ON
		t.tablespace_name = s.tablespace_name
GROUP BY
	t.TABLESPACE_NAME;
```
Thought I should open a new issue since the old one is closed and I can't reopen it.

**Comment by serge-rider** [comment]
Thanks, I use a bit different queries (as we can't use DBA views in regular metadata reading) but this should work.
