### ISSUE TITLE
Add reconnect button @ postges 

### ISSUE THREAD

**Issue by infectormp** [dbeaver/dbeaver#3772]
When you run the query, an error occurs if the connection to the database was lost due to a server restart.
In this screen we need add reconnect button.

Step to reproduce:
1. open connection
2. restart db server
3. try execute query

![image](https://user-images.githubusercontent.com/9958813/42422264-5ed3cd02-82eb-11e8-988b-ce0f8a87ae18.png)

postgres 9.6 \ dbeaver 5.1.2

**Comment by serge-rider** [comment]
I can't reproduce this (I think this happens only if shutdown operation longs for some time) but I'll add this error code in "connection lost" error code list.

**Comment by infectormp** [comment]
Thank you!
