### ISSUE TITLE
Create view dialog bug

### ISSUE THREAD

**Issue by Speirs47** [dbeaver/dbeaver#3776]
When I create a new view, write my SELECT query and save the query it actually won't save unless I start the select query with 

> CREATE OR REPLACE VIEW `name` AS 

I think in previous versions it wasn't necessary to write it.

And if I create a view like that I can't check the results of the view because a name of the view in the tab is `new_view` and I've set it's name to `name` (an error dialog would say that `new_view` view doesn't exist, which is true). I have to save to view, close the tab, refresh views list and open that new view.

**Comment by serge-rider** [comment]
Fixed in #3803
