### ISSUE TITLE
Many databases not showing tables

### ISSUE THREAD

**Issue by marczahn** [dbeaver/dbeaver#3777]
Hi,

I just found a problem: We have a server with hundreds of test databases which were created with the time. What popped up is that when I open <DB> -> schemas -> <Schema> -> tables there are no tables shown at all.

When I double click on tables they are shown indeed.

**Comment by marczahn** [comment]
Reopen because this pops up again and again. Unfortunately it is not reproducable reliable.

**Comment by serge-rider** [comment]
What is your database?
Could you post error/debug log? 
https://github.com/dbeaver/dbeaver/wiki/Log-files
