### ISSUE TITLE
Download MySQL and PostgreSQL native clients in runtime

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#3778]
We need to download native clients on demand (we can't include them in CE distribution because of too big size of binaries for all OSes).

See comments in #1361

**Comment by serge-rider** [comment]
Initially implemented for MySQL/MariaDB and PostgreSQL for Windows (64bit).
Client files are downloaded on demand.
IF this will work well then we could try to add Linux and MacOS binaries.

**Comment by 452** [comment]
Please add Linux support

**Comment by piradata** [comment]
why the binaries for pg_dump are nor download automatically? where can i download them?
