### ISSUE TITLE
double click on search result brings up the table with the previous search filtered instead of the current search.

### ISSUE THREAD

**Issue by amirtal** [dbeaver/dbeaver#3779]
this was tested on several postgres hosts, with different versions, up to 9.6
using DBeaver 5.1.0 (issue was present on previous versions as well), running on windows 10 64bit

steps to reproduce:
search DB for some term, e.g. "test1"
result window shows tables where this string is found, double click on any table brings up the table data, filtered to only show values containing "test1", as expected.
if i start a new search for a different term, e.g. "test2", search window shows a list of tables, but after double click on any table in the list, it is opened with the term "test1" filtered.
not "test2" as expected.

the only way to start a new search is to close the entire app window and re-open.
requiring to save and re-open all current tabs and files.

Amir.

**Comment by serge-rider** [comment]
Thank for bug report.
Workaround: you can just close search results view (no need to restart whole application)
