### ISSUE TITLE
DBs closing on selecting others

### ISSUE THREAD

**Issue by marczahn** [dbeaver/dbeaver#3783]
This use case:
1. Open db "A" in the navigator
2. Open Schemas and select "public"
3. Open a table
4. Open db "B"
5. Open Schemas and select "public"
-> This results in that db A is closed as well as the opened table

Happens on DBeaver 5.1.2

**Comment by denizkaanaraci** [comment]
I have same problem and I opened an issue for this problem [#3687](https://github.com/dbeaver/dbeaver/issues/3687). Developer said it's kind of limitation but i have no problem like this before. I was using dbeaver 5.0.2 on Ubuntu 16.04 with no problem like this.

**Comment by marczahn** [comment]
I see - Thanks for the remark.
