### ISSUE TITLE
Path issue when DBeaver sends command to open folder with dumped data (Linux, Dolphin, KDE)

### ISSUE THREAD

**Issue by ssrebelious** [dbeaver/dbeaver#3784]
After a success back up operation or data export DBeaver sends a command to file manager to open folder where the data was saved (unlike in data export, when creating dump it is impossible to opt out of opening directory, or at least I didn't find a checkbox).  Though it is generally helpful option, the interaction with Dolphin (KDE file-manager) is wierd. Dolphin is trying to open invalid path which looks like `/home/username/'/home/username/path/to/dumped/data'/`. It would be great if the interaction with the Dolphin could be fixed.

DBeaver v.5.1.2. openSUSE LEAP 15.

**Comment by serge-rider** [comment]
This seems to be  Dolphin-specific.
Don't see how can I fix it from DBeaver.
Here is a workaround (I didn't test it yet):
https://stackoverflow.com/questions/9692331/open-a-path-with-desktop-open-from-java-on-ubuntu-linux

**Comment by ssrebelious** [comment]
I also use `Pycharm` which is also Java-balsed. There is an option "open in Dolphin" in file's context menu and it works. Seems that it is able to detect which file manager is used in the system and adapt its behaviour accordingly.
