### ISSUE TITLE
Create of debug log file does not work if I have changed where the data directory is saved

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#3787]
DBeaver - **Version 5.1.2 CE (32-bit / 64-bit)**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

With the default configuration setup, a log file is saved in the property directory:

> C:\Users\<user name>\.dbeaver4\.metadata\\**dbeaver-debug.log**

But if I change the _DBeaver_ **data** directory, no such file is generated.

**o** Start the _DBeaver_ from the command line with:

> C:\...> **dbeaver.exe -data MyData**

**o** No log file are created in the **...\metadata** directory.

**Comment by serge-rider** [comment]
I can't reproduce this (I see debug log even if I redefine workspace path).
Maybe you have changed debug log location in preferences?
![image](https://user-images.githubusercontent.com/6398845/42737536-669473ba-887d-11e8-9f13-60a9bb06c0ef.png)

**Comment by serge-rider** [comment]
I think it is a bad idea to put any working files in Program Files folders. As they are write-protected by default. And I don't think that I can resolve this somehow - application just can't write in Program Files without raising permission level to Admin.

**Comment by pdanie** [comment]
I have now looked on this issue a bit further, and its an old misbeaviour in _DBeaver_ in that the use of "**$(workspace)**" macro can not handle if the path to the _DBeaver_ config/driver directory contains a space. I have tried back as far as to _DBeaver_ version **4.2.6** and the same behaviour exist there.

**o** The example below workes as expected in that there is created a **C:\\First\\.metadata\dbeaver-debug.log** file .

> C:\...> dbeaver.exe -data "C:\First"

**o** The example below does not work as expected in that there is no log file created anywhere on the hard disk (note blank between _First_ and _Second_).

> C:\...> dbeaver.exe -data "C:\First Second"

The misbehaviour exist in all three use cases:

**o** _DBeaver_ is started with the command line parameter "**-data**" path that contain blank(s).
**o** _DBeaver_ is started with a "**osgi.instance.area=...**" path in the **config.ini** that contain blank(s).
**o** _DBeaver_ is started by a windows user that has a blank in his user name.

**Note 1:** So my problem was not primary that I have saved the config/driver files in the windows **C:\\Program Files** directory (even if that was really bad), it was that the the program files path contain a space.

**Note 2**: I have changed our repacking of _DBeaver_ that I use **C:\ProgramData** directory to save the config/driver files.

**Comment by uslss** [comment]
ticket closed. Issue isn't reproducible on 6.2.5
