### ISSUE TITLE
Feature: Remove logging of -con parameters for user and password in .log file

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#3788]
DBeaver - **Version 5.1.2 CE (32-bit / 64-bit)**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

It would be benificial if _DBeaver_ did not log (or at least scrambled) the **user** and **password** values set on the command line (using the **-.con** command line parmeter) in the **...\\.metadata\\.log** file.

Today those two values are logged in plain text.

**Comment by serge-rider** [comment]
Good point

**Comment by pdanie** [comment]
DBeaver - **Version 5.1.4 CE (32-bit / 64-bit)**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

Seems the removal of user/password is not working. I still get a line in _DBeaver_ **...\\.metadata\\.log** file on _DBeaver_ version **5.1.4** with the contents:

> !SESSION 2018-08-07 09:41:52.261 -----------------------------------------------
> eclipse.buildId=unknown
> java.version=1.8.0_77
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=sv_SE
> Framework arguments:  -con name=TEST|driver=mssql_ms|connect=true|openConsole=false||user=**MyUserName**|password=**MyUserPassword**|database=MyDatabase|host=192.168.6.124|port=1433
> Command-line arguments:  -os win32 -ws win32 -arch x86 -con name=TEST|driver=mssql_ms|connect=true|openConsole=false||user=**MyUserName**|password=**MyUserPassword**|database=MyDatabase|host=192.168.6.124|port=1433

I would rather see that the the user/password information (if supplied) is replaced with "..." or something equal. 

Something like this instead

> !SESSION 2018-08-07 09:41:52.261 -----------------------------------------------
> eclipse.buildId=unknown
> java.version=1.8.0_77
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=sv_SE
> Framework arguments:  -con name=TEST|driver=mssql_ms|connect=true|openConsole=false||user=**...**|password=**...**|database=MyDatabase|host=192.168.6.124|port=1433
> Command-line arguments:  -os win32 -ws win32 -arch x86 -con name=TEST|driver=mssql_ms|connect=true|openConsole=false||user=**...**|password=**...**|database=MyDatabase|host=192.168.6.124|port=1433

**Comment by serge-rider** [comment]
I've removed logging made by DBeaver. But this is Eclipse log, it dump all command line arguments in it.
There is no simple way to hide this info from log.
This can be solved by passing some config file in command line instead of parameters. Although this might be not very convenient.

**Comment by sackp** [comment]
have there been any update to this? Is disable logging that contained username/password still not possible when using cli with -con?
Dbeaver 6.0.4 Release 5/6/19

**Comment by kkaminsky** [comment]
It's Eclipce RCP log - https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/log/EquinoxLogWriter.java#L255

Try to use additional flag  **-vmargs "-Declipse.log.include.commandline=false"**:
```
.\DBeaver.exe -con "..." -vmargs "-Declipse.log.include.commandline=false"
```

This flag can also be set in another way, see System properties in https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fruntime-options.html
