### ISSUE TITLE
Default keybinds: Please stop using the Ctrl+Alt combination for defaults

### ISSUE THREAD

**Issue by EdeBT** [dbeaver/dbeaver#3789]
It may not occur to everyone, especially in the US, but on [the ISO keyboard exists the AltGr key](https://en.wikipedia.org/wiki/ISO/IEC_9995#Levels_\(“unshifted”_“shifted”,_“AltGr”\)) which simply translates Ctrl+Alt in most cases. In most European languages we have more characters than keys, we have to put symbols and such on keys with the AltGr to not run out of key real estate. On the Hungarian QWERTZ keyboards symbols such as #[]{}&@; (and some more but less important for DBeaver users) are all on the AltGr key.

When you put default keybinds on combinations such as Ctrl+Alt+x with every second update, you just make me not want to update. I will run into problems like accidentally trying to start parallel execution of a hundred long queries that I would have no chance to stop on production, even though I just wanted to write comments like a responsible person (though thank you for the popup that stopped me).

**Comment by lemon-juice** [comment]
I fully agree with the request. I had to manually remove some keyboard shortcuts just to be able to type some national characters in DBeaver. I didn't run into such dangerous incidents like described above but it is clear that such possibility exists. I think there should be no AltGr and no Ctrl+Alt default shortcut keys in DBeaver (and not in any application).

**Comment by serge-rider** [comment]
Agreed, this makes sense.
However we need some fantasy which shortcuts to use. I see about 20 shortcuts with CTRL+ALT in DBeaver.
Some of them could be replaces with CTRL+SHIFT but others cannot (because it is already used for other actions).

**Comment by serge-rider** [comment]
It would be great you you'd post some most dangerous/inconvenient shortcuts from your point of view.
A'll replace CTRL+ALT+X,  CTRL+ALT+O, CTRL+ALT+P.

Dunno how to replace CTRL+ALT+F (SQL formatting, it is very old and widely used) and some others.

**Comment by EdeBT** [comment]
The Ctrl+Alt combinations that I have personally problem with in the DBeaver Keys Scheme are F,G,X,C,B,N. In my layout the other keys have no AltGr functions, or ones that are basically not used, like đ and Đ, but there are many layouts which may heavily interfere with the other characters as well. What could be a good compromise is to have an extra scheme by default like 'DBeaver-ISO friendly', which drops/replaces all Ctrl+Alt+[character] combinations, and will be left in place with newer versions.

**Comment by serge-rider** [comment]
Good point. Perhaps separate schema is the best way to do this.

**Comment by serge-rider** [comment]
Remaining shortcuts were changed.
SQL format to <kbd>Ctrl+Shift+F</kbd>
Query row count to <kbd>Ctrl+Alt+Shift+C</kbd>
Query all rows to <kbd>Ctrl+Alt+Shift+A</kbd>

G, C, B and N are not used.
