### ISSUE TITLE
apache hive connection issues---error resolving driver libraries

### ISSUE THREAD

**Issue by grepie** [dbeaver/dbeaver#3790]
![cant_resolve_libraries](https://user-images.githubusercontent.com/26613596/42564019-3bd44496-8532-11e8-9426-67d39626e49c.png)
![error_resolving_libraries](https://user-images.githubusercontent.com/26613596/42564022-3ca5caac-8532-11e8-925c-690788779008.png)

The setting of  Hadoop/Apache Hive,there's error edit driver ,like the pics above,I use jdk1.8 and maven3.5.4,how to resolve it?Thanks a lot

**Comment by serge-rider** [comment]
I see a few similar bug reports. Something is wrong with Maven artifacts download but I can't reproduce that. Are behind some corporate firewall?

If not - please post error/debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files)
