### ISSUE TITLE
Problem with oracle configuration

### ISSUE THREAD

**Issue by abourdeau** [dbeaver/dbeaver#3792]
I can't connect at my Oracle DB

The error message is 

eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Avertissement
Thu Jul 12 14:08:33 EDT 2018
Can't load driver properties

The problem is for xdb6.jar and orai18n.jar

I have the version 5.1.2

Can you help me

**Comment by serge-rider** [comment]
xdb6.jar and orai18n.jar is not enough for Oracle driver. You need to dd ojdbcX.jar (ojdbc8.jar for Oracle 12) at least.

**Comment by abourdeau** [comment]
ok Ty
