### ISSUE TITLE
Question: howto create new sql editor script on connection open, instead of open last saved script

### ISSUE THREAD

**Issue by marco-sanjuan** [dbeaver/dbeaver#3793]
Hi Serge

I'm looking for an option to open new sql editor script by default, because it always opens last script associated to conection, and I have to create new script and close old one. 
It's a little bit frustrating.

Thanks!!

**Comment by serge-rider** [comment]
This feature is already supported. there are 3 ways to open SQL script:
- Open recent script (the one you mentioned), shortcut is <kbd>Ctrl+Enter</kbd> in navigator.
- Open existing/new script <kbd>F3</kbd>)
- Open new script (<kbd>Ctrk+]</kbd>) - looke this one is what you need.

**Comment by marco-sanjuan** [comment]
I think I have not explained myself well.

I mean, when you open a new connection, how to, by default, create a new blank script, instead of opening an existing one.

**Comment by serge-rider** [comment]
Ah, I see.
Weill, this can be easily implemented, just yet another action type for double click:
![image](https://user-images.githubusercontent.com/6398845/42965908-110f43a0-8ba4-11e8-8095-dc5899483942.png)

**Comment by marco-sanjuan** [comment]
Great news!

It could be as simple as do what configuration says: "open new sql script", and rename current behavior as it do: "open last saved script".

Hope it helps. Thanks!

**Comment by p91paul** [comment]
@marco-sanjuan the screenshot above is what @serge-rider just implemented, currently that option does not exist (you likely have "Open SQL Editor" without the "new" bit). Be sure to upgrade when 5.1.4 is out!

**Comment by marco-sanjuan** [comment]
Ah ok ok sorry, that's right.
Thanks ;)
