### ISSUE TITLE
Problem with change datatype

### ISSUE THREAD

**Issue by Niklas81** [dbeaver/dbeaver#3798]
This is a duplicate of issue #3569, as this has been closed because "This is not DBeaver issue, it is PG-specific behavior".

The whole point of having a GUI db tool is to help workflow, is it not? If I do something similar in e.g. pgModeler, by changing the model and then diff it against an active database, it will translate this:

```
CREATE TABLE tablename (
    colname SERIAL
);
```

into this:

```
CREATE SEQUENCE tablename_colname_seq;
CREATE TABLE tablename (
    colname integer NOT NULL DEFAULT nextval('tablename_colname_seq')
);
ALTER SEQUENCE tablename_colname_seq OWNED BY tablename.colname;
```
for me.  Why can this not be a feature in DBeaver as well? After all, DBeaver allows me to chose `serial` as datatype from the list of datatypes.

Same type of (working) behaviour should apply to all data types, i.e. translate into SQL commands that do run.

**Comment by ramrasi** [comment]
If the Table contains data, problem with adding sequence.
Sequence generated number, if already exists in modified column.

**Comment by serge-rider** [comment]
@Niklas81 This also works in DBeaver. For new table creation, but not for existing table column altering.

@ramrasi  Yep. Perhaps you will need to specify some initial parameters for sequence. This makes this feature not so sexy.
