### ISSUE TITLE
GROUP BY for all fields in SELECT

### ISSUE THREAD

**Issue by romad17** [dbeaver/dbeaver#3799]
Is there any way to tell GROUP BY to group simply by all the fields in the SELECT?
It is really frustrating always to update the GROUP BY after changes in SELECT.

Thank you!

**Comment by serge-rider** [comment]
Not sure I fully understand the issue.
Do you mean Grouping panel?
What is the point to group by all columns (isn't this the same as just SELECT DISTINCT/UNIQUE)?

**Comment by serge-rider** [comment]
In any case it is very simple to do (if the question was about Grouping panel). Just click on the first row header in results (this will select full first row) and then drag-n-drop results header into Grouping panel.

**Comment by romad17** [comment]
Hi Serge,

I talk about this:

If I have a query like `SELECT a,b,c,count(*)`
Then I need to add `GROUP BY a,b,c` or `GROUP BY 1,2,3`

Now, if I change the query to `SELECT x,y,z,w,count(*)`
Then I must change also to `GROUP BY x,y,z,w` or at least to `GROUP BY 1,2,3,4`

The question is, is there a function in SQL or DBeaver, that I use something like `GROUP BY *`
or I click and it adds the relevant `GROUP BY`

Thanks.

**Comment by serge-rider** [comment]
You. You can type 
`GROUP BY *` and press <kbd>CTRL+Space</kbd> - this will convert * into table column list. Note: this works only for a single table selects.

**Comment by romad17** [comment]
Thank you Serge. But it simply add all the fields of the table, regardless of what I have in the SELECT.
But thank you anyway!
