### ISSUE TITLE
[Feature request] Filter databases in Connection properties

### ISSUE THREAD

**Issue by tobiasstadler** [dbeaver/dbeaver#3800]
(For postgres) I would like to have the possibility to filter the databases the are available for one connection in the connection properties. E.g The Postgres server has databases starting with foo_ and bar_ and I have one connection (Connection A) to the server configured. Then I would like to be able to configure that in the database navigator the under Connection A  only ones starting with foo_ are visible but not the ones starting with bar_.

**Comment by serge-rider** [comment]
You can do this in connection properties:
![image](https://user-images.githubusercontent.com/6398845/42937749-9e17e014-8b58-11e8-9335-ce0b2382d404.png)

**Comment by tobiasstadler** [comment]
That helped me. Thanks a lot!

**Comment by serge-rider** [comment]
👍

**Comment by aleksandrs-ledovskis** [comment]
Could "Catalogs" be renamed in that form to "Catalogs/Databases"?

IMO, it would help in this feature's discoverability.
