### ISSUE TITLE
Preference Window Properties are showing Double times

### ISSUE THREAD

**Issue by ramrasi** [dbeaver/dbeaver#3802]
When I want to modify settings on preference window. so I search "driver" in preference window's search Field properties are double time showing.....

![image](https://user-images.githubusercontent.com/6615196/42754833-a7b04b4e-8913-11e8-87e3-a23905378dd7.png)

**Comment by serge-rider** [comment]
What DBeaver version do you use (standalone, Eclipse)?

Such issue may happen if both Eclipse and standalone plugins are enabled (e.g. when you run DBeaver from Eclipse IDE)

**Comment by ramrasi** [comment]
I am using Community Edition 5.1.3

downloaded from https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm

**Comment by serge-rider** [comment]
Then most likely it is a glitch in workbench configuration.
Try to reset it: https://github.com/dbeaver/dbeaver/wiki/Reset-workspace
