### ISSUE TITLE
create view bug

### ISSUE THREAD

**Issue by ptarant** [dbeaver/dbeaver#3803]
Version of DBeaver: 5.1.3

create view does not work:

adding fields to a view not possible from field view
when entering select clause from existing table, dbeaver creates a table instead of a view with fields of its own choice

Tested against mysql 5

**Comment by serge-rider** [comment]
Similar to #3776

**Comment by ptarant** [comment]
Correction:

create view allows to use an existing table name to be assigned to the new view. When persisted, the new view is shown in the view tree (temporarily) but the existing table structure is indicated in the field list.

Suggestion:

do not allow to use name of an existing db object for a new view.

**Comment by serge-rider** [comment]
Fixed
