### ISSUE TITLE
DBeaver ignores -Duser.timezone=UTC since 5.1.1

### ISSUE THREAD

**Issue by UkrZilla** [dbeaver/dbeaver#3805]
Hi All,

Setting -vmargs -Duser.timezone=UTC in dbeaver.ini or vmargs -Duser.timezone=UTC in shortcut is ignored since 5.1.1, at least for Google BigQuery

Please check and fix it, Thanks

**Comment by serge-rider** [comment]
In fact it works.
But you need to specify these parameter on separate lines, like this:
```
-vmargs 
-Duser.timezone=UTC
```

**Comment by UkrZilla** [comment]
Hi @serge-rider 
Yes, you are right, it works with separated lines, but it does not work in shortcut(worked before 5.1.1), like this:

![image](https://user-images.githubusercontent.com/5429192/42827367-dc136b6a-89ee-11e8-8f8f-de304a5fa0e2.png)

Thanks

**Comment by UkrZilla** [comment]
Perfect, thanks. Please close the issue
