### ISSUE TITLE
Sign DBeaver plugin jars in Eclipse repositories

### ISSUE THREAD

**Issue by joelsolon** [dbeaver/dbeaver#3806]
Every since I started using DBeaver, when I install updates in Eclipse, I get a security warning. I install anyway, but the next time, it happens again,

Warning: You are installing software that contains unsigned content. The authenticity or validity of this software cannot be established. Do you want to continue with the installation?
  /Users/joelsolon/.p2/pool/plugins/com.github.jsqlparser_1.2.0.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.core_5.1.3.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.core.eclipse_5.1.3.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.data.gis_1.0.12.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.derby_1.1.73.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.erd_2.0.90.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.firebird_1.0.89.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.generic_2.3.74.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.h2_1.0.43.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.hana_1.0.17.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.hsqldb_1.0.35.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.import_config_2.1.51.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.informix_1.0.79.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.mockdata_1.0.14.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.mssql_1.0.82.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.netezza_1.0.53.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.phoenix_1.0.57.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.postgresql_2.1.61.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.sqlite_1.0.37.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.teradata_1.0.56.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.ui.locks_1.0.33.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ext.vertica_2.0.18.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.model_1.0.77.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.net.ssh_1.0.9.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.net.ssh.jsch_1.0.9.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.net.ssh.ui_1.0.9.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.runtime.ide.core_2.1.10.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.runtime.ide.ui_1.1.10.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.dbeaver.ui_5.1.3.jar
  /Users/joelsolon/.p2/pool/plugins/org.jkiss.utils_2.1.71.jar
  /Users/joelsolon/.p2/pool/features/org.jkiss.dbeaver.core.feature_5.1.3
  /Users/joelsolon/.p2/pool/features/org.jkiss.dbeaver.ext.generic.feature_2.1.74
  /Users/joelsolon/.p2/pool/features/org.jkiss.dbeaver.runtime.feature_5.1.3

**Comment by serge-rider** [comment]
Yes, we do not sign jar files. But we should, at least for public Eclipse repositories. Mark as FR.

**Comment by serge-rider** [comment]
We'll add jars sign in 5.1.5. All jars in all versions will be signed by our certificate.
However Windows and MacOS installers will still contain unsigned jars (because of pack200 usage). But this shouldn't be a problem as installers are signed themselves.

**Comment by serge-rider** [comment]
For the record. I've stuck with slow jarsigner utility problem.
Eventually I found http://insights.sigasi.com/tech/slow_jarsigner_centos7.html which fixes /dev/random performance. 
Running `sudo apt install rng-tools` on Ubuntu helps.

**Comment by serge-rider** [comment]
We still have some unsigned 3rd party jars.

com.vividsolutions.jts
org.apache.commons.jexl
com.github.jsqlparser
net.sf.opencsv

Not sure how to handle them. I could sign them with out certificate (just like Eclipse Orbit does with 3rd party bundles).

**Comment by z0rb** [comment]
Hi. Has the signing of JARs been disabled/broken on recent versions?
