### ISSUE TITLE
[Bug] Tree object search filter not working with packages section (tested in Oracle DB)

### ISSUE THREAD

**Issue by yevon** [dbeaver/dbeaver#3807]
The new nice tree object search filter seems to be not working with package objects in oracle, it filters all categories like tables, views, synonyms etc, but packages are not getting filtered (at least in an Oracle DB).

![image](https://user-images.githubusercontent.com/121157/42800420-182e5b8a-899c-11e8-940b-6ac91d806e1c.png)

**Comment by infectormp** [comment]
same with indexes

**Comment by serge-rider** [comment]
Good point. Will add filtering for both packages and indexes.

**Comment by p91paul** [comment]
was this duplicate of #1905?

**Comment by yevon** [comment]
No duplicate, the other one was the feature request, this is a bug fix of this feature.
