### ISSUE TITLE
[Bug / missing functionality] Compile log window is empty after compile Oracle DB package

### ISSUE THREAD

**Issue by yevon** [dbeaver/dbeaver#3808]
- Compile log window is empty after compile Oracle DB package, it only shows the error as a pop-up, and it doesn't allow you to go to the line with error clicking over it, or see the line with errors highlighted.
- Also, there isn't any error highlighting in code yet? Thanks 

![image](https://user-images.githubusercontent.com/121157/42800636-00aca6aa-899d-11e8-91ec-f3d9138712d9.png)

Thanks!!

**Comment by yevon** [comment]
I tested this in community edition

**Comment by serge-rider** [comment]
I my case it looks like this: 
![image](https://user-images.githubusercontent.com/6398845/42937533-ed6da096-8b57-11e8-876c-a40d18648c66.png)

However maybe this depends on Oracle server version/driver (both 12.2.0.1 in my case)

**Comment by yevon** [comment]
Ok thanks, I will make some tests, it might be due to driver version.

**Comment by yevon** [comment]
mmm I have tested it with proper driver version, and with files for JDK6 or JDK7 and same issue. Is there any option to control whenever this pop-up is shown and whenever not? This might be the issue.

**Comment by yevon** [comment]
Same issue after erasing all dbeaver config, pop-up still shows up.

**Comment by yevon** [comment]
Tested also with x32 and x64 versions of dbeaver, zip and installer files. Oracle version: 12.1.0.2

**Comment by uslss** [comment]
Hi @yevon is issue still actual for you?

**Comment by yevon** [comment]
Hi @uslss, let me check this later with latest dbeaver version, because I still don't use dbeaver regularly because of this one and I don't know if this is already solved.

**Comment by yevon** [comment]
Results:



I have installed Dbeaver through windows 10 store, nice addition for auto updating it! I'm using JDCBC driver v7 files and Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit.

If you compile the package declaration, compile window is now working nicely. But if you compile the body, it just doesn't work, it says compiled successfully always, even with clear errors. See images below:

Just two additional comments:
  - The persist pop up dialog confirmation is very annoying for Oracle World, can it be disabled in any way?

- The pop up window for compiled successfully is also annoying, it is more than enough with a message in the compile window, if not, you have to click every time that you compile. Is there any way for disabling it also? Lots of thanks for your work!.

![image](https://user-images.githubusercontent.com/121157/66642915-f4fdef00-ec1d-11e9-835e-c7ce204e479b.png)


![image](https://user-images.githubusercontent.com/121157/66642971-15c64480-ec1e-11e9-9998-2d14357d1575.png)

**Comment by p91paul** [comment]
package body not showing errors on compile should have been fixed in 6.2.1, does this really still happen?

**Comment by yevon** [comment]
I will check it on monday, I installed dbeaver latest version from windows store, it might be a prior version

**Comment by yevon** [comment]
I confirm that the problem was that I was using 6.2, installed from the windows store. I thought that it would have latest version, but seems not. Closing this, thanks!
