### ISSUE TITLE
Import very big databases scripts (sql files)

### ISSUE THREAD

**Issue by i2dcarrasco** [dbeaver/dbeaver#3809]
Hello,

I'm starting to use this program and is very usefull, but I'm not able to find the way to import an SQL file without load it into the program.
The problem is that SQL file is very big, so try to load it into the program fails with an "memory out" error.

Is there any way to execute an SQL file without load it?, like command line programs such mysql (you can cat a very big file and mysql just run the queries without load it into memory). If not, will be a nice feature, because I'm trying to copy a MsSQL database to another instance and is a big pain.

Thanks and greetings!.

**Comment by serge-rider** [comment]
For MySQL you could use import tool:
![image](https://user-images.githubusercontent.com/6398845/42864665-e5b2ffc4-8a6f-11e8-849f-2f6a5a5bd1b8.png)

However you will need to install MySQL local client for that. We have feature request #3778 which will let to avoid this step.

**Comment by AndreiPashkin** [comment]
@tati-kru , didn't work for PostgreSQL.

**Comment by serge-rider** [comment]
@AndreiPashkin please write more details.
What error do you see, what PG server version do you have?

**Comment by black-snow** [comment]
>Task 'PostgreSQL restore' started at Tue Nov 03 15:34:57 CET 2020
pg_restore: error: did not find magic string in file header
>
>Task 'PostgreSQL restore' finished at Tue Nov 03 15:34:57 CET 2020

Not suitable for importing plain SQL?
