### ISSUE TITLE
Scripts manipulation features

### ISSUE THREAD

**Issue by yiwan74** [dbeaver/dbeaver#3811]
Some suggestions for easier usage of scripts...
1. Could you add drag&drop feature for scripts
2. On file open, if file type is .sql, is it possible to set active connection as active datasource for script?
3. Can you add feature to clear list of used scripts when F3 (sql editor) is pressed?

**Comment by serge-rider** [comment]
1. DnD works for project navigator/explorer (you can move script to another folder). Do you mean something else?
2. This makes sense. Will add this feature in the next version
3. This is the list of all scripts assigned to active datasource. This is actually main purpose of this command (F3). IF you don't need that list you could just open recent/new script or find it in the script tree.

**Comment by yiwan74** [comment]
1. I thought about DnD from, for example, windows explorer. I often need to execute ten or more scripts on database so I would like to just drag and drop them from my pinned folder... Or maybe there is some better way to do it?
2. Thanks  :)
3. Oh I see... Now I found that if I choose script and then set active datasource to None that script will not show up next time.  Is there a way to clear more scripts from that list at once, without need to open it one by one and set to None?
4. One more question... Is it possible to add some backup/restore functionality? For example by calling some external tool (as gbak for Firebird database) and using database connection parameters from active connection. Does this can be achieved through plugins or...?

**Comment by serge-rider** [comment]
1. DnD from windows explorer works. Just drop a file in editor area.
3. Yes, you can assign a datasource for a set of scripts. Select them in project explorer view, context menu -> Associate with data source.
4. It is unrelated feature. And we already support this for MySQL/MariaDB and PostgreSQL. It is accessible from menu->Tools->Backup/restore database.
