### ISSUE TITLE
Error message "No default database" since DBeaver 5.1.3 with PostgreSQL

### ISSUE THREAD

**Issue by maffe** [dbeaver/dbeaver#3813]
I started DBeaver 5.1.3, connected to a PostgreSQL server and executed a `DROP DATABASE` and `CREATE DATABASE` command. Then I right-clicked the server and selected `Refresh` ("Aktualisieren"). Immediately two error message windows appeared:
![grafik](https://user-images.githubusercontent.com/515302/42821913-f2aa53da-89d9-11e8-8382-e92d5aac8afd.png)

Now the refresh option is disabled:
![grafik](https://user-images.githubusercontent.com/515302/42821984-1fe27b48-89da-11e8-85b8-7fc9a464c14e.png)

Sometimes the server’s context menu gets longer, but the new entries don’t seem to do anything:
![grafik](https://user-images.githubusercontent.com/515302/42822231-d0bd8d2c-89da-11e8-8bb1-4ad82e57f013.png)

I also get random error message windows when using the application afterwards, especially when opening the server’s context menu (which is then closed immediately):
![grafik](https://user-images.githubusercontent.com/515302/42822022-408965f0-89da-11e8-8107-2ea4b1f882ab.png)
![grafik](https://user-images.githubusercontent.com/515302/42822027-43b1d8f2-89da-11e8-8483-71ae5d82f3b1.png)
![grafik](https://user-images.githubusercontent.com/515302/42822151-975f4eee-89da-11e8-8a86-dbf2a439f6aa.png)
A similar message appears for a brief moment when closing DBeaver.

In the connection settings one of the server’s databases is displayed in the database field, which is also shown in bold after connecting, so that looks okay (and it worked perfectly with DBeaver 5.1.2).

Possibly related: #3771, #3810

**Comment by maffe** [comment]
Also possibly related: #3810

**Comment by serge-rider** [comment]
Perhaps this has the same nature as #3801.
And I can't reproduce this.
Could you check latest EA version (https://dbeaver.io/files/ea/) - it contains fix with PostgreSQL databases switcher.
Thank you for bug report.

**Comment by maffe** [comment]
The EA version (5.1.4) works well. Thank you for your support.

**Comment by serge-rider** [comment]
Great

**Comment by serge-rider** [comment]
@kohesivcenk Did you try 5.1.4?

**Comment by MrSuaveh** [comment]
Coworker just installed 5.1.4 on Windows today (8/1/18) and is experiencing this exact issue. 

- We set up a PostgresSQL connection on localhost and were able to login into it.
- Then we executed 'Create Database TestDB;' and the error messages start appearing and no DB is created.

I installed DBeaver some time ago and have upgraded to 5.1.3 and have not experienced this issue.

**Comment by lucibranc** [comment]
I have the same issue with 5.1.4 on Windows against PostgreSQL 10. Lots of "no default database" errors when doing almost anything.

**Comment by maffe** [comment]
While most things work for me in 5.1.4, I noticed I still get error messages when refreshing the database list after creating a new one.
![grafik](https://user-images.githubusercontent.com/515302/43791148-08e89b6a-9a75-11e8-9d47-34d101c305f3.png)

Steps to reproduce: 

- Execute `CREATE DATABASE foo;`
- Right-click the server and select Refresh (F5)

**Comment by serge-rider** [comment]
This happens in 5.1.4 in single database mode (option "Show non defautl databases is disabled).
This bug was already fixed, you could check the fix in EA version (see above)

**Comment by maffe** [comment]
Actually I have enabled “Show non-default databases”, but 5.1.5.201808060810 seems to work fine.

**Comment by scorbin** [comment]
i am getting the same error
