### ISSUE TITLE
[Question]Its posible use variables delimiter in DBeaver

### ISSUE THREAD

**Issue by alioth865** [dbeaver/dbeaver#3814]
- Question:
Hi, I'm new using DBeaver, and in the program I used earlier I could use variable delimiters.
So I could get a query as follows:
SELECT * FROM $ {squema_id} _schema.table_name;
But now using eclipse I only know how to use variables of the form **:name_variable** or anonymous parameters with (**?**) And I do not know if there is a way to do it.
Thanks in advance.

**Comment by serge-rider** [comment]
DBeaver supports variables in form ${varName} as well as :varName. 
This can be configured in preferences->General->Editors->SQL Editor->SQL Processing.

**Comment by alioth865** [comment]
Thanks a lot!!
