### ISSUE TITLE
Firebird: simple query limit exceeds

### ISSUE THREAD

**Issue by iceoz** [dbeaver/dbeaver#3815]
Hello,

When i try to execute a simple query like this
`
SELECT * FROM OPERACOES O INNER JOIN EMPRESAS E ON E.CODIGO = O.CODIGOEMPRESA WHERE E.CODIGO = 218`

Then i get this error

### SQL Error [335544381] [54000]: Dynamic SQL Error; SQL error code = -204; Implementation limit exceeded; block size exceeds implementation restriction [SQLState:54000, ISC error code:335544381]

but same query when executeded agains dbeaver 4.3.4 works like a charm

my database is a firebird 2.5

**Comment by serge-rider** [comment]
I can't say for sure. What was changed since 4.3.4 is driver version (now we use Firebird 3.x drivers by default).
You could try to downgrade driver version (in driver editor click on org.firebirdsql.jdbc:jaybird-jdk18 artifact->download->choose proper version in table column).

**Comment by thwyster** [comment]
I have same problem!

`SQL Error [335544381] [54000]: Dynamic SQL Error; SQL error code = -204; Implementation limit exceeded; block size exceeds implementation restriction [SQLState:54000, ISC error code:335544381]
  Dynamic SQL Error; SQL error code = -204; Implementation limit exceeded; block size exceeds implementation restriction [SQLState:54000, ISC error code:335544381]
  Dynamic SQL Error; SQL error code = -204; Implementation limit exceeded; block size exceeds implementation restriction [SQLState:54000, ISC error code:335544381]
    Dynamic SQL Error
    Dynamic SQL Error
      SQL error code = -204
      Implementation limit exceeded
      block size exceeds implementation restriction`

**Comment by mrotteveel** [comment]
The error is generated by Firebird, not by Jaybird. So the fact IB Expert doesn't generate it, while DBeaver with Jaybird does, means that there is some other factor involved, for example the connection character set.

It would be helpful to have a reproducible example to pinpoint what is wrong.

**Comment by huds8n** [comment]
define your connection:

jdbc:firebirdsql://127.0.01:3050/bd?defaultResultSetHoldable=True&amp;encoding=WIN1252


It´s work for me.
