### ISSUE TITLE
kafka support

### ISSUE THREAD

**Issue by domnulnopcea** [dbeaver/dbeaver#3816]
Kafka is a message broker, https://kafka.apache.org/

it would be great if dbeaver would support basic kafka management

* create/modify/delete topic
* insert a message into a topic
* show messages from topic
* delete a message from a topic

**Comment by serge-rider** [comment]
Sounds interesting. We don't have messaging/queue datasources yet. This might be the first one.
And we can support KSQL as a kind of SQL dialect.
We could use Java APIs for integration (https://kafka.apache.org/documentation/#api)

**Comment by mkgrgis** [comment]
About kafka https://habr.com/ru/post/354486/

**Comment by pmuntyanu** [comment]
would be cool to have SASL auth onboard

**Comment by tati-kru** [comment]
Kafka is no a relational or document or key-value storage, it doesn't have query language and it is not completely clear how to support it in DBeaver. What kind of UI / data management interface should we use?

**Comment by p91paul** [comment]
this could be helpful https://github.com/mmolimar/ksql-jdbc-driver/blob/master/README.md

**Comment by serge-rider** [comment]
@p91paul interesting, thanks!

**Comment by tchibatron** [comment]
I am afraid, this driver is for KSQL Engine, which is a separate product and unfortunately can not be included in to DBeaver.

**Comment by ramazanpolat** [comment]
> I am afraid, this driver is for KSQL Engine, which is a separate product and unfortunately can not be included in to DBeaver.

Yes, KSQL is a separate product but it is a product that talks to Kafka with SQL-like semantics. In this case, this makes much more sense to include KSQL. In fact, I cannot think of any other way to use DBeaver to access Apache Kafka.

**Comment by vapolonio** [comment]
It'll a very useful feature to interact with near-realtime data pipelines. 😃

**Comment by cmuellerbeyond** [comment]
Please support the schema registry coming with kafka out of the box - What essentiall happens is that the "kafka" is scanned for the right datasets when a query is run. A good "limit" needs to be chosen if the query should not run for hours. Also a "live" view would be nice.

**Comment by SailorMax** [comment]
Looks like something similar already exists, but not free: https://www.cdata.com/kb/tech/kafka-jdbc-dbvr.rst

**Comment by sken130** [comment]
Just curious, will this be available in both Community Edition and Lite Edition?
