### ISSUE TITLE
Can't  upgrade to dbeaver-ce 5.1.3 on  ubuntu 18.04

### ISSUE THREAD

**Issue by edmundorobles** [dbeaver/dbeaver#3818]
Hi, i tried to upgrade  to dbeaver-ce 5.1.3 on ubuntu 18.04,  i have installed 5.1.2,  but   i only got `dbeaver-ce is already the newest version (5.1.2~ubuntu16.04)`.

i did  `apt update; apt upgrade`

**Comment by ced75** [comment]
Hi,

Same issue. The PPA doesn't seem to be up to date with dbeaver-ce 5.1.3 for Ubuntu 18.04 (bionic beaver).

Regards.

**Comment by serge-rider** [comment]
Sorry, indeed we didn't update PPA for all series. Fixed.
Thanks for report
