### ISSUE TITLE
SQL Editor - Color option add -> Matching brackets highlight  

### ISSUE THREAD

**Issue by bhougland18** [dbeaver/dbeaver#3819]
I am using the eclipse with the Dbeaver extension and want to know if i can change the color for the maching brackets.  Is this possible, similar to the functionality provided by the Structured Text Editor:

![image](https://user-images.githubusercontent.com/28444296/42890152-ba6d2fe0-8a71-11e8-880b-2b368da3bb34.png)

**Comment by serge-rider** [comment]
Good point

**Comment by mboeringa** [comment]
This is probably related, so I post it here: I sometimes find the box highlighting confusing. 

Look at the image below: notice the cursor is located where the lower arrow points: it is in between two closing brackets. In this situation, DBeaver puts a little square around the matching bracket. Yet, what closing bracket does it belong to? The one _before_ or _after_ the cursor? This is ambiguous...

It would be nice to also see a square around the closing bracket in this kind of situation, so its absolutely clear which brackets match.

![afbeelding](https://user-images.githubusercontent.com/7635726/44298920-b48e3400-a2ec-11e8-8881-f7b3b1706300.png)

**Comment by serge-rider** [comment]
For now I set brackets color the same as text editor foreground (so it will look  fine in all custom themes).

Eclipse text coloring preferences are really messy. Perhaps we'll add new color option as a part of #4334.

Unfortunately I can't change the way how matching brackets are highlighted, it is a standard control nad changing its behavior will require too much effort.
