### ISSUE TITLE
IO Error: Utility 'mysqldump.exe' not found in client home 'MySQL Connector/Net' DUPLICATE OF #2765

### ISSUE THREAD

**Issue by CollinChaffin** [dbeaver/dbeaver#3821]
I've seen this closed at least twice without really addressing the issue.  Dbeaver not only does not include (or download) all the prerequisite files/paths that MUST be set for it's methods/functions to successfully complete, but does not even properly document them (I just searched your website as well), or even as a pure reactive after-thought even clarify to it's users how to mitigate the above TERMINATING error to be able to continue using the product.  Instead, luckily I found community members that had at least acknowledged this was an issue, albeit without any real resolution.

As was stated by community members in #2765, the only solution (?) is to go out and instead of a few binaries, do a full download and installation of MariaDB server because (as also stated above) if one would (wrongfully, in the case of dbeaver) assume that this app knows well enough that the needed binaries ALSO do live in the (much more appropriate for a client workstation) MySQL workbench - dbeaver will not properly even detect the required files are there.

This should be an open issue until addressed.  At the very least, dbeaver should either be 1. automatically downloading required files (which I was impressed in my case it DID do for the jdbc maria dll) so why not these other required files?.....or 2. Prompt the operator for a location where they might already be installed (before totally blowing up and terminating leaving the operator to have to open a different db management client), or at the absolute very least  3. Terminate and tell the operator exactly WHAT is missing in detail and most importantly WHERE TO COPY/INSTALL THEM to continue and also update the product website/kb/wiki to clearly state the product requirements specific to individual binary files needed for this product to operate on specific databases - since THAT is what this product's main purpose is, after all.

**Comment by serge-rider** [comment]
Agreed. This feature is very poorly documented. Unfortunately we have too many features and too few hands. Hopefully this situation will change in the near future (or we'll be buried under tons of feature requests).

Automatic native binaries download will be added in #3778. It has high priority so it has quite good chances.
