### ISSUE TITLE
Incorrect display of PostgreSQL TIMESTAMP data type

### ISSUE THREAD

**Issue by laonianshaocheng** [dbeaver/dbeaver#3823]
Config:
DBeaver CE 5.1.1
Windows 7 x64
PostgreSQL based with custom driver

Issue:
It seems dbeaver handle the data type TIMESTAMP as TIME. And I have checked the schema is correct.

Detail:
select current_timestamp;
![image](https://user-images.githubusercontent.com/41411542/42924640-bfbe7002-8b5d-11e8-9d68-bad65cbf8463.png)

select current_time;
![image](https://user-images.githubusercontent.com/41411542/42924658-d2c5722c-8b5d-11e8-92ae-e93871a6d647.png)

**Comment by infectormp** [comment]
@laonianshaocheng could you try latest dbeaver version?

**Comment by laonianshaocheng** [comment]
@infectormp i just tried it, but CE 5.1.3 has the same problem. and 5.1.3 handle time as timestamp?! even different from 5.1.1

select current_time;
![image](https://user-images.githubusercontent.com/41411542/42943615-d82994b8-8b95-11e8-9336-828450695789.png)

**Comment by serge-rider** [comment]
I'm quite sure that that custom driver is the reason. I can't reproduce this with standard PostgreSQL.

**Comment by serge-rider** [comment]
DBeaver determines column type as timestamp with timezone but actual value doesn't contain date part.

**Comment by laonianshaocheng** [comment]
@serge-rider perhaps, but this driver works well in my java app. 
ps: my db is developed based on PostgreSQL 9.2

**Comment by laonianshaocheng** [comment]
@all I found a solution to solve this problem. Use 

> org.jkiss.dbeaver.ext.postgresql-2.1.42.jar

 replace the default plugins. e.g. for CE 5.1.3, replace 

> org.jkiss.dbeaver.ext.postgresql_2.1.61.jar

Now, everything is OK.

**Comment by serge-rider** [comment]
@laonianshaocheng You could just use "PostgreSQL Legacy" driver. It is much easier than trying to find some old version of PostgreSQL extension.

Default DBeaver PostgreSQL driver formats date/time values according to data type provided by server. Most likely custom driver provides incorrect JDBC data type information,

**Comment by laonianshaocheng** [comment]
As mentioned above, my db is developed based on PostgreSQL 9.2. There is no reason to use "PostgreSQL Legacy" driver, since legacy refers to PostgreSQL 8. And I tried DBeaver 5.2.4, it seems that this BUG has been fixed. It works fine now.
