### ISSUE TITLE
Dialog 'Error executing query' focus on OK button

### ISSUE THREAD

**Issue by georgiraychev** [dbeaver/dbeaver#3825]
Up until version 5.1.3, I believe, the 'Error executing query' dialog had it's focus on the OK button.
Now (version 5.1.3, running on Windows 10) the focus is in the text error message.

So basically, after an attempt to run an erroneous query,  (assuming you are using only keyboard) you have to hit TAB -> ENTER, to select the OK button and clear the dialog. In previous versions, the focus was on the OK button and just a simple ENTER did the work.

Being me, this costs me about 500 extra keystrokes every day.

Does make sense to return the focus back to the OK button?

Thanks in advance.

**Comment by serge-rider** [comment]
That's weird. Because it doesn't matter where focus is, Enter should close the dialog. And it does this on all Windows 8/10 machines I tested it on.

However  I can change default focus if it will resolve the issue on some systems.

**Comment by georgiraychev** [comment]
Awesome. Thanks!
