### ISSUE TITLE
Improve error message when creating FK constraint with datatype mismatch

### ISSUE THREAD

**Issue by tobias47n9e** [dbeaver/dbeaver#3826]
When creating a foreign key constraint between a `int(11) unsigned` and `int(11)` column the error message is very generic. It would be nice if the error message could say something about the type mismatch.

**Comment by serge-rider** [comment]
This seems to be very database-specific. MySQL I guess?
In order to detect such error we'll need to replicate complicated logic which is already implemented on server-side.

**Comment by tobias47n9e** [comment]
Yes I was using MySQL. Wouldn't it be possible to insert a warning in the message if the strings don't match each other (`int(11) unsigned` and `int(11)`). No need for any other checks (I am assuming this without knowledge of the codebase), just a vague enough message. Maybe something like this:

> The datatypes of the foreign key relation don't match. This might cause problems with some databases.

Thanks for considering, but no worries if it is not a good idea. We can just close the issue in that case :)
