### ISSUE TITLE
Export to existing database : target column is mapping to "create" (must be existing by default ?) and don't have an existing name 

### ISSUE THREAD

**Issue by MedShake** [dbeaver/dbeaver#3830]
Hi !

I use to export csv or dbf to mysql.
I select the source table and choose Export Table data.
I choose as target container the existing database (mysql) 
then I choose the target table.

Here is now the problem : all target columns have state "create" and are named with the first csv line.

![capture du 2018-07-20 09-03-16](https://user-images.githubusercontent.com/24508646/42988505-13525ad6-8bfd-11e8-8171-6ba005e1cbf6.png)

It take a long time to change the target name and set "mapping" to "existing".
Why dont associate by default the first source col to the first target col, the second with the second and so on ? 
And when database exists, pre select "mapping" for cols as "existing".

Perhaps I don't do something right !?

Thanks for your software ! (and sorry for bad english)

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on the issue for a long time
additional info is needed to reproduce an issue.
ticket will be closed. feel free to reopen an issue and add info that could help to investigate it.
