### ISSUE TITLE
Add support for jdbc ElasticSearch

### ISSUE THREAD

**Issue by UkrZilla** [dbeaver/dbeaver#3832]
Hi @serge-rider 

Can you please add support for jdbc ElasticSearch? According to doc(https://www.elastic.co/blog/elasticsearch-6-3-0-released) since 6.3.0 it supports jdbc (https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-jdbc.html)

Thanks

**Comment by serge-rider** [comment]
Good point, thank for noticing their new driver.
Will add it in the next version.

**Comment by killnine** [comment]
I know this is an old request but is there a non-jdbc implementation for Elastic? I am just using the open source ES container but can't connect via DBeaver since it requires the paid, licensed version. :(
