### ISSUE TITLE
Bug about Phoenix: schema is not shown when there is only one

### ISSUE THREAD

**Issue by sumbrez** [dbeaver/dbeaver#3835]
DBeaver 5.1.3 (64)
Windows 10 (64)
Phoenix 4.11.0-HBase-1.2 (on Ubuntu 16.04)
HBase 1.2.6 (on Ubuntu 16.04)

I was using DBeaver to connect to Apache Phoenix where schema was on. The driver I used was copyed from the phoenix I used.

The bug is that, if there is only one schema, DBeaver will not show the schema but directly show tables in it. Properties of those tables can be shown (but no `Schema Name`), but error will occur if attempping show rows, dropping the table, etc. (`Table undefined` error, of course)
However, if I add another schema, all will work well.

SQuirrel SQL worked well under the same situations even there was only one schema.

**Comment by sumbrez** [comment]
Indice are also not shown when only one schema exists.

**Comment by serge-rider** [comment]
It is a bug (or misfunction) in Generic driver. Thanks for report.

**Comment by sysuzhang** [comment]
yes, I had met this problem either.

**Comment by sumbrez** [comment]
I'm not the developer, but a bug reporter. @sysuzhang
