### ISSUE TITLE
Toolbar with 5 red buttons

### ISSUE THREAD

**Issue by pihug12** [dbeaver/dbeaver#3836]
- DBeaver 5.1.3
- Windows 7 32bits

There is a toolbar with 5 red buttons since upgrading 5.0.6 --> 5.1.3.  
There are corresponding to Execute *statement* / *Execute script* / *Explain execution plan*. I understand they are now moved to a left panel, but I don't find how to remove their previous place.

![image](https://user-images.githubusercontent.com/678038/43037203-57028f30-8d0b-11e8-9571-4541a10f3ced.png)

**Comment by serge-rider** [comment]
Try to reset workspace - https://github.com/dbeaver/dbeaver/wiki/Reset-workspace

**Comment by pihug12** [comment]
I somehow solve it using "*Fenêtres* --> *Réinitialiser la perspective*" and exit/start DBeaver. ("*Window* --> *Reset Perspective*")

French translations could be improved BTW. Do you know how I can help?

**Comment by serge-rider** [comment]
@pihug12 Sure. Write me on serge@jkiss.org.
