### ISSUE TITLE
Can't load functions

### ISSUE THREAD

**Issue by lrweck** [dbeaver/dbeaver#3840]
Hello, 

I am getting this error when trying to open the functions folder in the public schema and if I click OK, the folder does not show the functions. 

![image](https://user-images.githubusercontent.com/26086198/43080830-fc6da3a4-8e66-11e8-90fa-421403f4b7e9.png)

Database: PostgreSQL
Version: 8.3.23

DBeaver Version: 5.1.3
JDBC Driver: 42.2.2

**Comment by serge-rider** [comment]
Yep. proargdefautls was added in 8.4.
Thanks for report
