### ISSUE TITLE
Bug: "Format SQL" inserts wrong spaces with negative numbers

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#3844]
Hi,

I just noticed that at least in the latest version of DBeaver (5.1.3), the Format SQL inserts unwanted extra spaces in between the numeric digit and the minus (-) sign, and extra space after the digit. I can't remember having seen this before in previous versions, so it may be a minor regression as a result of a recent change to fix some other issue, but I may be wrong...

Before formatting
![afbeelding](https://user-images.githubusercontent.com/7635726/43102369-3ecb66b4-8ecb-11e8-8145-83e1e81e3eb3.png)

After formatting
![afbeelding](https://user-images.githubusercontent.com/7635726/43102431-6f8e941a-8ecb-11e8-96fd-966408a3d1b1.png)

**Comment by serge-rider** [comment]
Thanks for bug report
