### ISSUE TITLE
Unable to edit table column definitions in Microsoft SQL Server

### ISSUE THREAD

**Issue by spraguey** [dbeaver/dbeaver#3845]
I'm not sure if this is a bug or feature request. It is currently not possible to edit the table column definitions on SQL Server. I can only add or remove columns. I tried the Microsoft Driver and the jTDS driver, and both result in the same thing. Like other database types, users should be able to edit the column names, data types, and default values.

**Comment by serge-rider** [comment]
It is feature request.
Duplicate  of #3845
