### ISSUE TITLE
saving script connection mapping

### ISSUE THREAD

**Issue by surpavan** [dbeaver/dbeaver#3846]
When we open a project in DBeaver (new installation or upgrade) - the project file does not store the selected DB for the script.

It would be nice if the data source associated with each script is stored. In a new version- we always need to re-select the associated connection for each script - instead this could be stored in the project file/settings.

**Comment by serge-rider** [comment]
Currently DBeaver keeps connection association info in .metadata folder.
Generally this FR makes great sense for those who use shared projects.

We could keep it in the comment in first line of script (and this should be configurable).
Something like
```sql
-- DB CONNECTION: <connection id or URL>
```
Connection can be identified by ID, name or JDBC URL.

**Comment by surpavan** [comment]
In our office - we generally use ODBC with fixed name.  So this should be written as?
DB CONNECTION: ODBC_NAME

**Comment by serge-rider** [comment]
This can't be ODBC-specific.
More likely it could be jdbc:odbc:DATASOURCE_NAME (actual target database URL).
And it is still not unique. You may have multiple connection to the same database (under different users, etc). This also should be addressed.

**Comment by serge-rider** [comment]
First version of embedded script connection mappings is ready:
![image](https://user-images.githubusercontent.com/6398845/47683395-84162080-dbe0-11e8-9444-af3979874b2e.png)

Please test it in EA or in 5.2.4.

**Comment by surpavan** [comment]
Thank you adding this feature.  I will check in 5.2.4, I do not know how to 'EA' checking,

**Comment by serge-rider** [comment]
It is Early Access - https://dbeaver.io/files/ea

**Comment by surpavan** [comment]
Once a property on the sql is set - it is not changing .  The property window is not the same. I am not getting the above given screenshot once it is applied the first time.  Below is the screenshot I am getting post that step:

![p1](https://user-images.githubusercontent.com/37795549/47997761-fd52cd80-e122-11e8-8b97-ea99b820cc36.png)

**Comment by surpavan** [comment]
First time I got by right clicking on the script>properties.  But now as you have given it from the window preferences.
Also, when the line is being added to the script -  it is adding to the existing line, so if any select *  etc is there in first line it is getting commented.  It should add the connections setting line with a new line break at the end.
