### ISSUE TITLE
Mysql Export to Db - enhancement request

### ISSUE THREAD

**Issue by chrisb34** [dbeaver/dbeaver#3848]
When Exporting data from one database to another, using MySQL, it would be REALLY useful to include an option to turn off Foreign Key Checks.

My workflow often requires that I grab some tables from a LIVE database to download into my development environment.  
-  I tick truncate table before insert, as I want to replace the data
-  I get an error due to FOREIGN key constraints.

Instead, I need to export to SQL and then add header and footer as follows :- 
/** HEADER **/
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

/** FOOTER **/
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;

**Comment by serge-rider** [comment]
After some investigation I think there is nothing to do in DBeaver.
mysqldump from MYSQL 5.0+ already does this.
New DBeaver includes client from MariaDB 10 which also adds these instructions in every dump.

**Comment by chrisb34** [comment]
Hi Serge

The request was aimed at the database to database export rather than the mySqlDump, which as you say, does already have it.

The database to database does not, so you cannot transfer a single table which has dependencies.  As I mentioned in my original request, I export the SQL from the Database to Database process and add the Foreign Key Check manually.

Thanks
Chris

**Comment by alexrowesoap** [comment]
Agreeing with Chris: this is fine for dumps, but not for database-database transfers where keys are involved.
