### ISSUE TITLE
Advanced copy should have [NULL] as blanks

### ISSUE THREAD

**Issue by surpavan** [dbeaver/dbeaver#3852]
When doing advanced copy the NULL values are getting copied as [NULL] -  but in a normal copy these are not getting copied.

Advanced copy should have [NULL] as blanks.

**Comment by serge-rider** [comment]
You can do this by changing "Value Format" parameter to Database Native or Editable

**Comment by surpavan** [comment]
Did not know that.  Sure. will check it.

**Comment by rickysingla** [comment]
> You can do this by changing "Value Format" parameter to Database Native or Editable

Where is the option to change "Value Format" in Dbeaver

**Comment by surpavan** [comment]
@rickysingla 
I think it is in the window>preference>Dbeaver>Editors>Data Editor>Presentation
value format option.
But afterwards - thought it is best to leave it as default for unknown reasons or I just got used to the default format.
