### ISSUE TITLE
[BUG] Error after exit on Java JDK 10

### ISSUE THREAD

**Issue by benyaminl** [dbeaver/dbeaver#3854]
Hello, I've strange error exit code, but I couldn't find any documentation about what the error about. Maybe anyone could help explain the error to me. The error code can't be copy paste so I make a screenshot about the error. I hope it help alot. Thanks.

![dbeaver error](https://user-images.githubusercontent.com/2817332/43209192-416e18e4-9056-11e8-8fbf-907aaf8f75dc.JPG)

**Comment by serge-rider** [comment]
This is quite hard to understand the reason by just one error code. Usually this code means that something is wrong with Java. I see that you are using your locally installed Java. Could you try DBeaver installer? It already contains appropriate and well-tested Java.

**Comment by benyaminl** [comment]
@serge-rider hmmm... That's quiet problem because My environment force using Java 10. And I use dbeaver as probable app not installing it. maybe for now there no problem and I think should I ignore it.

**Comment by benyaminl** [comment]
@serge-rider Seems the error gone after I do restart the windows. I'm on JDK 10 64 bit windows 7 pro 64 bit. I will close this thread. Thanks :)
