### ISSUE TITLE
[Bug Report] - Cannot connect to mysql 8.0.11 running in docker

### ISSUE THREAD

**Issue by killboard** [dbeaver/dbeaver#3856]
Hi, I can't to connect to a mysql container running in `3307` port in my localhost. 

![image](https://user-images.githubusercontent.com/15525599/43231982-ab80ace8-903c-11e8-9dfc-d6d90c544847.png)

I connect successfully by `netcat`
![image](https://user-images.githubusercontent.com/15525599/43232373-7b1b1ab4-903e-11e8-9ae4-66c9a08e320e.png)
 and `MysqlWorkbench`
![image](https://user-images.githubusercontent.com/15525599/43232129-72d01720-903d-11e8-998e-7844a58ca282.png)

My DBeaver version is 5.1.3 and mysql support is 
![image](https://user-images.githubusercontent.com/15525599/43232294-22988a0c-903e-11e8-9aef-0505757d9f75.png)

Mysql runnig in container is 8.0.11, please check it.

**** EDIT
I changed the Mysql version from `8.0.11` to `5.7.22` and works now, I missing some plugin to work in version `8.0.11` or is not compatible yet?

**Comment by serge-rider** [comment]
Since DBeaver version 5.1.3 we have different MySQL drivers for 8.x and 5.x. Because Oracle broke driver backward compatibility. So you need to use driver `MySQL 8.x` for 8.x server.

**Comment by killboard** [comment]
Ok, thanks.
