### ISSUE TITLE
Dbeaver always adds timestamp by default in Date Format Columns

### ISSUE THREAD

**Issue by viveksingrodia** [dbeaver/dbeaver#3859]
While fetching date columns in output, dbeaver always adds timestamp by default. Why is it happening this way. Any leads will be helpful. Refer screenshot.

![dbeaver](https://user-images.githubusercontent.com/41781261/43312135-06867514-91aa-11e8-9c1b-cc8b8075f34d.png)

**Comment by serge-rider** [comment]
Yep. This happened because of tricky Oracle DATE type (driver says it is timestamp, I've added a workaround for this)
