### ISSUE TITLE
Can not scroll ERD with latest version 5.1.4 (30 July 2018)

### ISSUE THREAD

**Issue by cheekybuddha** [dbeaver/dbeaver#3864]
Hi,

When I scroll an ERD that is larger than the viewport, it appears if the screen is trying to re-scale and leaves a 'tearing' effect.

If I switch to another  editor and switch back the view is restored to normal, but I can't scroll to see the parts of the diagram that are off-screen.

**Comment by serge-rider** [comment]
Can't reproduce.
What is your OS?
How big is your diagram?
How this "re-scale" looks like?

**Comment by cheekybuddha** [comment]
Sorry, forgot important details:
OS: Debian Stretch (kernel 4.9.110-1)
Diagram is open in DBeaver full window (screen size: 1280x1024)

trying to attach screenshot

**Comment by cheekybuddha** [comment]
![20180730_dbeaver_80percent](https://user-images.githubusercontent.com/19176116/43395781-406412c4-93f7-11e8-80dd-3ebdeb38260d.png)

**Comment by cheekybuddha** [comment]
OK, I made a small mistake - if I switch to a different editor and then back the diagram is displayed normally at the correct scrolled position.

**Comment by AShynkevich** [comment]
Tis bug is reproduced on Linux mint

**Comment by serge-rider** [comment]
Perhaps it is a result of migrating to Eclipse 4.8.
How do you perform scrolling (mouse wheel, scrollbars)?
I see that zoom ratio was set to 80% - is it intentional?

**Comment by cheekybuddha** [comment]
The same symptoms happen at 100%. I normally scroll the mouse wheel, but it also happens when clicking on the scrollbar.

Eclipse 4.8 might be the problem!

I scrolled back through my terminal to the install and found this:
```Bash
Need to get 54.5 MB of archives.
After this operation, 921 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ppa.launchpad.net/serge-rider/dbeaver-ce/ubuntu xenial/main amd64 dbeaver-ce amd64 5.1.4~ubuntu16.04 [54.5 MB]
Fetched 54.5 MB in 43s (1,267 kB/s)                                                                                                        
(Reading database ... 326003 files and directories currently installed.)
Preparing to unpack .../dbeaver-ce_5.1.4~ubuntu16.04_amd64.deb ...
Unpacking dbeaver-ce (5.1.4~ubuntu16.04) over (5.1.3~ubuntu16.04) ...
dpkg: warning: unable to delete old directory '/usr/share/dbeaver/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.551.v20171108-1834': Directory not empty
```

**Comment by cheekybuddha** [comment]
Just to note: the above output is from my Ubuntu 16.04 box which also displays same symptoms

**Comment by cheekybuddha** [comment]
OK, so I moved eclipse_1630.so out of that folder, and did a reinstall.

Still the same issues :-(

**Comment by serge-rider** [comment]
Thanks for investigation. 
I'll try to reproduce it on our test Linux machine.

**Comment by burongtz** [comment]
Same bug in Ubuntu 16.04 LTS

![image](https://user-images.githubusercontent.com/26045424/43484070-f3f984fa-94d2-11e8-904f-a0e9fbbe8dcd.png)

![image](https://user-images.githubusercontent.com/13127237/43483929-983a2caa-94d2-11e8-8246-6f52fab1b4dc.png)

Bug when I scroll horizontal or search a table with Ctrl + F. Fixed when resize the window.

**Comment by abraham-jacob** [comment]
Same issue here. Just updated dbeaver to version 5.1.4. Having the same scrolling and painting issue.

Linux version 4.10.0-42-generic (buildd@lgw01-amd64-007) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1 16.04.5) ) #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017





![selection_004](https://user-images.githubusercontent.com/41971802/43486602-1d381dd6-94c9-11e8-81ee-bdc8db4041f1.jpg)

Happy to contribute with any other info if required.

**Comment by serge-rider** [comment]
This issue happens on GTK with most of editors.
Dunno how to fix this so far (seems to be a bug in Eclipse 4.8).
If I won't find the solution then we'll revert to Eclipse 4.7 in the next version.

**Comment by serge-rider** [comment]
Please try this workaround:
delete lines
```
--launcher.GTK_version 
2
```
from dbeaver.ini file.

**Comment by burongtz** [comment]
It works!. @serge-rider #
Deleting that two lines from

`$ sudo gedit /usr/share/dbeaver/dbeaver.ini`

Thank you!

**Comment by serge-rider** [comment]
Great
