### ISSUE TITLE
Show database name in sql script editor for PostgreSQL connections

### ISSUE THREAD

**Issue by NewlinkMoravia** [dbeaver/dbeaver#3865]
As it is possible now to have mutiple connections active and "set active object" does not close other sql editors, please add indication of the database name to existing (opened) sql editors.
Maybe same style as in table editor:
![db1](https://user-images.githubusercontent.com/19466627/43398939-c825c542-9409-11e8-82d0-20800bc46dd7.PNG)
Pavel

**Comment by uslss** [comment]
already implemented.
ticket closed
