### ISSUE TITLE
Make catalog/schema combo wider

### ISSUE THREAD

**Issue by NewlinkMoravia** [dbeaver/dbeaver#3866]
Hello,
is it possible to make the catalog/schema combo in toolbar wider?
![db2](https://user-images.githubusercontent.com/19466627/43399003-03f79780-940a-11e8-8fda-1705e88ff07d.PNG)
Pavel

**Comment by serge-rider** [comment]
I can't make them wider by default.
And unfortunately it is quite hard to resize it dynamically. 
So I've added preference options for them. Kind of a workaround but works.
![image](https://user-images.githubusercontent.com/6398845/43680012-5ad75e18-9839-11e8-8b02-409dbb9b5661.png)
