### ISSUE TITLE
Setting up Hive connection to HDInsight conflicts with existing connection to OnPremise Hadoop cluster

### ISSUE THREAD

**Issue by rajib2k5** [dbeaver/dbeaver#3867]
Has any one run into this issue? I can create connection to either Hadoop OnPremise or the Azure cloud's HDInsight. Both servers connect to different port. 

Under driver manager, I tried to copy the "Apache Hive" driver to a new driver and named it "Azure Hive" in order to avoid conflict. It raises a new issue, which doesn't allow me to download driver for hive 1.2.1.  Any pointers will be appreciated.

**Comment by serge-rider** [comment]
Could you post error messages? Especially the error with download. 
Debug log would be also very useful (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by rajib2k5** [comment]
![image](https://user-images.githubusercontent.com/20094874/43404913-3c957cd2-93de-11e8-9bae-b7aa8b1d319a.png)

**Comment by rajib2k5** [comment]
can you tell me where the drivers should be copied if I create a new driver connection under driver manager?

**Comment by serge-rider** [comment]
I see that driver files are missing after copy.

What DBeaver version do you use? Try to upgrade to the most recent one, we have fixed a bug in driver copy function a few versions ago.

However it is still not clear why do you need to copy the driver. Usually it is not needed unless you want to specify some very low-level driver configuration. All other settings can be changed in particular connection.

**Comment by rajib2k5** [comment]
I am using latest version of DBeaver. One problem, I am having is if I try to setup connection to Hive in HDInsight, it requires me to add extra info to JDBC url.

I insert the following in URL Template to make it work (and it does)
`jdbc:hive2://{host}[:{port}][/{database}];transportMode=http;ssl=true;httpPath=/hive2 `

The issue is it over-writes "Apache Hive" driver setting for all other hive connection that uses port 10,000 instead of HDInsight's secured port 443. 

I need to be able to have driver connection setup for 2 different hive platforms in different ports. That's why I tried to copy the Apache Hive driver setting under driver connection manager to setup one dedicated for either cloud or on-premise platform. When I copy it initially, it appears to show that DBeaver copied the driver, but, if I restart Dbeaver, it doesn't show any driver for the new copied driver. I hope I have clarified my use case.

**Comment by serge-rider** [comment]
Thanks.
I think I found yet another bug in driver copy function.

For now you can manually add two maven artifacts in copied driver:
org.apache.hive:hive-jdbc:RELEASE and org.apache.hadoop:hadoop-core:RELEASE

**Comment by rajib2k5** [comment]
I haven't used the [**Add Artifact**] option before.

What values do I enter for?
**[Group Id]
[Artifact Id]
[Classifier]**

**Comment by serge-rider** [comment]
In 5.1.5 we'll replace Hive driver with one single uber jar. 
No need to add Maven artifacts.
