### ISSUE TITLE
Question: How to have DBeaver start up without previous SQL Editor open

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#3870]
DBeaver - **Version 5.1.4 CE**
Operating System: **Windows 10**

I just wonder if it's possible to have _DBeaver_ at start up to **not** show a previous open SQL Editor(s) window/tab. I.e. I want that _DBeaver_ start up "clean".

I have tried to uncheck the Global Property **General -> Editors -> Database Editor -> Reopen database editor after restart**, but unfortunately that has no effect in what I am after.

**Comment by serge-rider** [comment]
Unfortunately it is not configurable in preferences (Eclipse limitation)
Workaround: add command line parameter `-closeTabs` in DBeaver shortcut.

**Comment by pdanie** [comment]
Thanks. Are there a value I can instead specify in the "**...\configuration\config.ini**" or "**...\dbeaver.ini**" file instead ?

**Comment by serge-rider** [comment]
Yes, you can add it in DBeaver.ini file. Before -vmargs line.

**Comment by pdanie** [comment]
Thanks. Is there an equivalent parameter I can use in the **...\\configuration\\config.ini** filt too ?

**Comment by serge-rider** [comment]
Sorry, I misunderstood the last question. No, configuration\config.ini is a very different config file and it can't be used to pass command line parameters to DBeaver.
