### ISSUE TITLE
Question: Is it possible to have DBeaver not to show thousand separator for INTEGER columns

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#3872]
DBeaver - **Version 5.1.4 CE**
DBeaver JDBC driver: **Microsoft**
Operating System: **Windows 10**
Database Server: **Microsoft SQL Express 2014**

I just wonder if there is a global setting in _DBeaver_ so that it does or does not show thousand separator for INTEGER column values in the result grid.

Today I get a separator in a integer field with the value "**1234**" presented as "**1,234**". I would just want it presented as plain "**1234**".

**Comment by robertodias** [comment]
Hi pdanie,

you can change that configuration by going to:
Preferences > Database > Data Formats
Selecting the type Number and unchecking the box "Use Grouping"
