### ISSUE TITLE
Question: How to add attributes to table columns?

### ISSUE THREAD

**Issue by chikhant** [dbeaver/dbeaver#3873]
Hi, 
looking to try an add a new property to the table column adder and an auto-generated value similar to the 'default' property. 

When the user clicks 'new column' another property will be listed along with a pre-filled value under 'Value'.

I've been sifting through the code but just wondering if there's a better method :) I appreciate it.

**Comment by serge-rider** [comment]
I think this should be more generic (we need a configuration for all new objects default name).

**Comment by chikhant** [comment]
Hi Serge, 

Sorry for the confusion, I'm not requesting a feature, my team and I are trying to use dbeaver for our project and require the addition of a auto-generated value such as the default property. We've been digging into the code but cannot find a reliable way to create a new property. We would like to be able to click "add new column" and then have a security label checkbox appear in order to auto fill in the column for row level security.   

Thanks!

**Comment by serge-rider** [comment]
If you need this for some custom driver/extension then you can annotate Java class getter with @Property. Thus it will become available in property list.
