### ISSUE TITLE
How do I chage the editor font when viewing single column value

### ISSUE THREAD

**Issue by RajandK** [dbeaver/dbeaver#3876]
Hello,
I have large block of text in column value. I can view and edit it using shift+ENTER.
But I am not able to change the default font for it.
I would like to change font to monospace. Is there any way I can do?

I tried changing the SQL editor font and result set font but it does not change the font when viewing
single column value using shift+ENTER.

Thanks in advance,
Rajesh.

**Comment by serge-rider** [comment]
I'll change font to monospace in the text editor dialog.
As a workaround you can open editor from text view dialog (right button at the top)
