### ISSUE TITLE
 SQL 错误 [1220] [08000]: (conn:6919) Connection is close

### ISSUE THREAD

**Issue by cosoc** [dbeaver/dbeaver#3877]
Suspended animation will occur for long periods of time without using the database table open again.
Why other tools do not have such a wonderful problem, link timeout problem linked to the database can not be linked immediately! Must wait a long time and then the error! Whether this is a problem or not, this problem has been bothering me. Want to have the big God give a number of advice or a real bug

**Comment by serge-rider** [comment]
First of all - what is your database/driver?
Debug/error log also would be very helpful (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by serge-rider** [comment]
You could:
1. Enable connection auto-recover
2. Enable keep-alive settings

![image](https://user-images.githubusercontent.com/6398845/43959654-359ae27c-9cb8-11e8-9666-0e07ff27eecd.png)
![image](https://user-images.githubusercontent.com/6398845/43959670-40952534-9cb8-11e8-9f16-7b7f414e1916.png)
