### ISSUE TITLE
add a field of text type, bug

### ISSUE THREAD

**Issue by xfzhaoxd** [dbeaver/dbeaver#3878]
When I add a field of text type into table，this field icon is varchar icon ,not text icon

**Comment by serge-rider** [comment]
What is your database?
For instance in PostgreSQL varchar and text is the same datatype (text is just an alias).

**Comment by xfzhaoxd** [comment]
sql server and mysql.

**Comment by kseniiaguzeeva** [comment]
Text type can be set in MySQL and SQL Server in 7.0.3
