### ISSUE TITLE
Can edit cell in resultset when displayed as epoch time in seconds

### ISSUE THREAD

**Issue by txigreman** [dbeaver/dbeaver#3879]
Hi,

I have a column defined as INT UNSIGNED. I've changed it to display as an epoch time, in seconds.
When I try to edit typing a value, or pasting it from another cell, an invalid value is set.

If I enter "2018-07-12 16:42:00.000" (copy/pasted from previous row) it's converted to "50498-05-04 14:00:00.000".
If I enter "2018-07-12 16:42:00" it's converted to "1970-01-01 01:33:38.000".

I'm using version 5.1.4 CE on Windows, with JRE 1.8.0_181.

**Comment by serge-rider** [comment]
Thanks for the bug report.
The actual bug was in value parser (it always read value in milliseconds).
