### ISSUE TITLE
SQL Colors and Fonts formatting missing after saving a new Script

### ISSUE THREAD

**Issue by georgethemarmot** [dbeaver/dbeaver#3880]
If a new script is created the sql language is recognized
![image](https://user-images.githubusercontent.com/4931142/43450932-1cea785c-94b4-11e8-8884-7dea7901a674.png)
after saving the script to a file, the color coding disappears.
![image](https://user-images.githubusercontent.com/4931142/43451000-3d2f64d8-94b4-11e8-8a30-9e2e9fabff82.png)
To bring it back it's necessary to close the sql file and open it again.

Dbeaver Community 5.1.4 Standalone on Windows 10 64bit

**Comment by serge-rider** [comment]
Can't reproduce. How do you create new SQL script? 
Do you assign database connection to it?

**Comment by serge-rider** [comment]
I've reproduced this by renaming new created script. 
Rename causes syntax coloring problems.
