### ISSUE TITLE
Feature request: DB2 JDBC Filter on Schemas

### ISSUE THREAD

**Issue by georgethemarmot** [dbeaver/dbeaver#3881]
It would be nice to have the filter feature on a schema level on DB2.
![image](https://user-images.githubusercontent.com/4931142/43451753-f596d96a-94b5-11e8-8b06-d2bb28c7879e.png)

**Comment by serge-rider** [comment]
What DB2 is this? (LUW, AS400, zOS)
You can configure top level objects (catalogs/schemas) filter in connection properties dialog, page General.

**Comment by georgethemarmot** [comment]
as400, yes. I missed that. Thank you
