### ISSUE TITLE
Cannot dump MySQL 5.x with mysqldump 8

### ISSUE THREAD

**Issue by antoniustefan** [dbeaver/dbeaver#3882]
Sorry, this is not an issue with DBeaver, more of a description on how to work around a bug in mysqldump 8 when connecting to older MySQL instances until MySQL fixes this.

mysqldump 8 introduced a new flag --column-statistics which should be disabled by default, but it is not. This causes the dump to fail against older instances.
To work around this issue, users can add **--column-statistics=0** in the Extra command args in DBeaver while doing the export.

MySQL bug reference:
https://bugs.mysql.com/bug.php?id=89825

Thanks for a great tool!

**Comment by serge-rider** [comment]
I wanted to handle this somehow in export wizard. But gave up. 
Because it depends on MySQL binaries version. So I'm afraid setting this option manually is the only way for now.
Thanks for workaround.

**Comment by fluxsauce** [comment]
Can this be revisited? If the MySQL binary version is greater than 8, set that by default?

**Comment by fcpauldiaz** [comment]
I'm having this problem and I don't know how to set the flag through dbeaver

**Comment by davidrhoderick** [comment]
> I'm having this problem and I don't know how to set the flag through dbeaver

I just had this bug and was able to fix it by setting the `--column-statistics=0` in extra arguments before initiating the dump.

**Comment by bhaidar** [comment]
@davidrhoderick Where can I specify column-statistics=0 while doing dump in dbeaver?

**Comment by davidrhoderick** [comment]
Under "Extra command args" like the following:

![dbeaver--column-statistics=0-location](https://user-images.githubusercontent.com/2300366/90240915-66a05e00-de2a-11ea-9e07-5d1304c8be5c.jpg)

**Comment by kevinquillen** [comment]
Also had to do this on Ubuntu 20.04, dbeaver 7.3.3 and a fresh install of mysql-client. This got it to export.
