### ISSUE TITLE
Schema list does not display

### ISSUE THREAD

**Issue by Jbroski** [dbeaver/dbeaver#3883]
Hi,

Just upgraded to 5.1.4 and suddenly I can't view the list of schemas in the database navigator or database properties page. Reverting to 5.1.3 restores the expected schema list.

additional information:
database connection type: vertica
os: macOS High Sierra 10.13.6

**Comment by rveachkc** [comment]
Same for Win10.
Double checked my account using Tableau Desktop to confirm it wasn't an access issue on the source.

**Comment by anovosiolov** [comment]
Same Win10, also vertica 8.1.1-18 client .

**Comment by serge-rider** [comment]
Thanks for bug report
