### ISSUE TITLE
Horizontal sidebar scrolling doesn't re-render on SQL editor

### ISSUE THREAD

**Issue by PHCCorso** [dbeaver/dbeaver#3884]
Hi,

I'm using DBeaver v5.1.4 on CentOS 7 and this is what happens when I make an horizontal scroll on the SQL editor:

![captura de tela de 2018-07-31 10-45-22](https://user-images.githubusercontent.com/21690449/43463446-f3682d80-94ae-11e8-9ccd-63ab31c5d253.png)

Haven't tested previous editions though.

**EDIT**:

Vertical re-rendering also isn't working when I'm editing and I break the line using `Enter` key:

![captura de tela de 2018-07-31 10-56-10](https://user-images.githubusercontent.com/21690449/43464089-8f66f472-94b0-11e8-9b58-7775d59f8cf2.png)

**Comment by cheekybuddha** [comment]
Looks like it's related to [this bug: 3864](https://github.com/dbeaver/dbeaver/issues/3864)

**Comment by PHCCorso** [comment]
Same happens with the search field inside the "Data" tab in the table view:

![captura de tela de 2018-07-31 11-53-04](https://user-images.githubusercontent.com/21690449/43467583-60e4ed36-94b8-11e8-85a0-7c6f95f14832.png)

**Comment by errob37** [comment]
> Haven't tested previous editions though.

Previous versions works fine. 

I just upgraded to 5.1.4 and the same problem happen.

OS : Ubuntu 16.04.4 LTS 

Workaround : Saving the editor remove all vertical scrollbars

**Comment by serge-rider** [comment]
Please check workaround in #3916
