### ISSUE TITLE
Feature Request - connectivity for Beeline in Azure

### ISSUE THREAD

**Issue by rajib2k5** [dbeaver/dbeaver#3885]
Can you add support for Azure Beeline drivers?

**Comment by serge-rider** [comment]
You could try to use Apache Hive driver for Beeline.
Is there any difference with default Hive settings for Azure?

IF so we could add new driver with some minor changes.

**Comment by rajib2k5** [comment]
Azure's HDInsight disabled support for Hive so users would switch to Beeline. It will be helpful if you add a separate driver for Beeline and especially HDInsight and EMR.

**Comment by rajib2k5** [comment]
One could still run Hive in HDInsight, but, it's a workaround. That option may go away in future.

**Comment by serge-rider** [comment]
I thought that Beeline is just a shell which uses standard Hive JDBC driver.
In any case this is no alternative jdbc driver for HDInsight  (as far as I know).
