### ISSUE TITLE
[GIF Screenshot] Autocomplete overrides adjacent text for no apparent reason

### ISSUE THREAD

**Issue by piqoni** [dbeaver/dbeaver#3887]
I love dbeaver but editing queries has been painful because of this bug:
![query_bug](https://user-images.githubusercontent.com/3144671/43467517-1e707ba8-94e2-11e8-92f2-f1057bd6e0b3.gif)

**Comment by serge-rider** [comment]
First issue is definitely a bug (auto-complete corrupts identifier). 
But second one is a bit more tricky. 

Anyhow - please check the fix in EA version (https://dbeaver.io/files/ea/)

**Comment by serge-rider** [comment]
First problem - identifier was corrupted after replace. This is definitely a bug.

Second problem - identifier to the right from cursor was replaced by new string (if there were no any whitespaces). This is not clearly a bug, a lot of people prefer this way to complete identifiers. So I'm not sure we should change this. Maybe we should make it configurable..

**Comment by shreyank** [comment]
Please do make the second problem configurable. The current behavior is different from other IDEs I have used and I have thus far failed to train myself to add a space ahead of time.

**Comment by pedromellofh** [comment]
even spaces (new lines too) are been replaced. it's really annoying most of the time

**Comment by uslss** [comment]
Cannot reproduce on 6.0.2
