### ISSUE TITLE
Error executing query

### ISSUE THREAD

**Issue by djmartin4** [dbeaver/dbeaver#3889]
The Error executing query window doesn't have a stop button so the query continues. This only happens with large error messages.
![screenshot](https://user-images.githubusercontent.com/38948480/43469287-d355771e-94b3-11e8-97b4-d6f2c66e1183.png)

**Comment by serge-rider** [comment]
Error dialog was redesigned in 5.1.3 (see #3733).
Just update to the recent version.

**Comment by djmartin4** [comment]
Will do, thanks.
