### ISSUE TITLE
Refresh on Database causes repeated message (No default database)

### ISSUE THREAD

**Issue by lrweck** [dbeaver/dbeaver#3893]
Clicking on refresh on a database with a default database connection configured causes this message to appear non-stop. Clicking OK prompts another message.

This does not happen with recent versions of PostgreSQL ( > 8.4.x ).

![image](https://user-images.githubusercontent.com/26086198/43486000-1bad1d0c-94e9-11e8-89be-7cbcab0accf7.png)

PostgreSQL Version 8.3.23
DBeaver Version: 5.1.4
JDBC Driver 42.2.2

**Comment by serge-rider** [comment]
Could you post debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files) ?

**Comment by serge-rider** [comment]
Please double click on the error ("Event loop exception" or "No default database") and copy-paste error stacktrace here.

**Comment by ururu-fy** [comment]
I confirm, have the same problem.

**Comment by lrweck** [comment]
Here they are:

![image](https://user-images.githubusercontent.com/26086198/43640391-2ce9cdea-96f6-11e8-8432-8c3ae8085af8.png)


![image](https://user-images.githubusercontent.com/26086198/43640407-37ecbf68-96f6-11e8-8c94-9f507ddf5aeb.png)


![image](https://user-images.githubusercontent.com/26086198/43640418-47fba6f8-96f6-11e8-91bd-a8ba250ebe86.png)

**Comment by serge-rider** [comment]
Thanks for the detailed bug report.
