### ISSUE TITLE
SQL Editor new display bug in v5.1.4

### ISSUE THREAD

**Issue by adrianles** [dbeaver/dbeaver#3895]
It wasn't happening in the version 5.1.3, but after upgrading to 5.1.4 it happened right away.
When inserting or removing a line break in the SQL editor the lines under the modified line disappear (only visually). After scrolling or moving the cursor, the lines redraw correctly.

Here is a screen shot right after inserting a line break:
![dbeaversqleditorbug_v2](https://user-images.githubusercontent.com/14124160/43508349-f38af2d6-956f-11e8-936d-4f4adab513c8.png)

In case it is of any help I'm using Ubuntu 16.04

**Comment by lazarosa** [comment]
Can confirm this on KDE Neon (which is Ubuntu 16.04 based). 
The same rendering blooper happens if you scroll an ER Diagram that is bigger than the displayed portion.
Scrolling through longer query texts, however, is not affected.

**Comment by cheekybuddha** [comment]
Yes, this issue is referenced also in 
[this bug: 3884](https://github.com/dbeaver/dbeaver/issues/3884)
and 
[this bug: 3864](https://github.com/dbeaver/dbeaver/issues/3864)

**Comment by serge-rider** [comment]
Please check the workaround in #3916
