### ISSUE TITLE
Bug: Postgres cant delete database in v5.1.4

### ISSUE THREAD

**Issue by MrGroovy** [dbeaver/dbeaver#3896]
In a previous version (5.1.2 I think) you could delete a Postgres database. I would make sure its not the active database (not bold). Then: right click -> delete. It worked.

Now I always get: SQL Error [55006]: ERROR: database "{DB}" is being accessed by other users
  Detail: There are 2 other sessions using the database.

I think its Dbeaver itself that is using the database.

**Comment by serge-rider** [comment]
Yes. Thanks for the bug report.

**Comment by sochacki111** [comment]
I am facing a similar issue on DBeaver Version 22.0.3.202204170718

**Comment by arindam31** [comment]
Got the same issue again on ver 22.2.0

**Comment by E1izabeth** [comment]
Please, create the new issue if you encounter some bugs.

**Comment by Maximilian94** [comment]
I am facing a similar issue
