### ISSUE TITLE
ORACLE Incorrect DDL generated w/ auto incrementing

### ISSUE THREAD

**Issue by MaselEOBHH** [dbeaver/dbeaver#3897]
When creating DDL for Tables in Oracle containing columns with IDENTITY attributes, the DDL ist created like this:
```sql
CREATE TABLE XXX
(
  COLUMN_NAME_SK NUMBER(18,0) DEFAULT "SCHEMA"."ISEQ$$_380866".nextval
)
```

instead of:
```sql
CREATE TABLE XXX
(	
  COLUMN_NAME_SK NUMBER(18,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE
)
```

Identity-Columns in Oracle are available since version 12c.
For any testing / questions / examples do not hesitate to contact me.

Thanks
Marcel

**Comment by serge-rider** [comment]
DBeaver uses Oracle functions to generate DDL (DBMS_METADATA.GET_DDL)
And it is a bit different from what you have posted.

Maybe you don't have permissions to call this system function?

**Comment by MaselEOBHH** [comment]
You are completly right. The strange SQL is generated by DBEAVER, when DMBS_METADATA does not work / is not available. Using the Owner of that object returns the correct DDL. Same behaviour as in SQL-Developer. 

So, just Close this issue.
