### ISSUE TITLE
Autocomplete Multiple selection

### ISSUE THREAD

**Issue by KlausCCR** [dbeaver/dbeaver#3899]
Feature Request:

Hi.

When selecting a column from the AutoComplete, it would be nice if there was the option of selecting multiple columns at a time from the list.

In the example below, I want two columns in my query, BNK_ACD_USER and BNK_DORMANT_DAYS

Example:
![image](https://user-images.githubusercontent.com/39584526/43519878-55a2caf4-9591-11e8-8f60-d841606eaba6.png)

Thanks very much!

**Comment by serge-rider** [comment]
Unfortunately this is not supported by Eclipse platform (only one completion proposal can be applied).
Potentially it is possible to change default behavior but it will require a lot of effort.

**Comment by KlausCCR** [comment]
Thanks for the response, and for a great product Serge.

**Comment by rmharriman** [comment]
+1 for the feature request and great product comment.
