### ISSUE TITLE
SQL Editor Issue

### ISSUE THREAD

**Issue by khushalc** [dbeaver/dbeaver#3900]
Even ever i press multiple enter, and then do backspace their are scroll bar coming on editor screen, its irritating after few occurrence. 

![image](https://user-images.githubusercontent.com/41996915/43520751-67405f7c-95b1-11e8-9449-c1b79125ad22.png)
![dbever_issue](https://user-images.githubusercontent.com/41996915/43520757-6bef6e64-95b1-11e8-980b-89c1af1c8e6c.png)

**Comment by serge-rider** [comment]
Please check workaround in #3916
