### ISSUE TITLE
Cannot create database when connected to Amazon RDS Postgres

### ISSUE THREAD

**Issue by antoniustefan** [dbeaver/dbeaver#3901]
Trying to create a database using the form fails because RDS does not accept explicit tablespace when creating a database.
This fails: CREATE DATABASE something TABLESPACE pg_default;
This works: CREATE DATABASE something;
This also works: CREATE DATABASE something TABLESPACE DEFAULT;

Not sure why RDS has this limitation but I think it can be easily overcome by adding an empty option in the tablespace dropdown, similar to the template database dropdown, and for the item just don't include any tablespace parameter.

**Comment by serge-rider** [comment]
I've added special option "Default" in tablespace combo of database create dialog. If set then no tablespace will be specified in CREATE DATABASE queru.
