### ISSUE TITLE
beaver 5.1.4 - Snowflake Connection

### ISSUE THREAD

**Issue by koke76** [dbeaver/dbeaver#3902]
The URL Template used under the edit driver settings for a snowflake connection is no longer used to set up the connection to Snowflake.  We are connecting with single sign-on and we use the "authenticator" option in the URL template.  Unfortunately, we had to roll back to previous version to make it work.  

Ideally, it will be best to have a drop down as part of the username/password configuration which lets you select the authenticator mode

https://docs.snowflake.net/manuals/user-guide/jdbc-configure.html

**authenticator=[connection option]**
Specifies the authenticator to use for verifying user login credentials:

**snowflake (Default)** to use the internal Snowflake authenticator.

**externalbrowser** to authenticate using your web browser and Okta, ADFS, or any other SAML 2.0-compliant identify provider (IdP) that has been defined for your account.

**https://<your_okta_account_name>.okta.com** (i.e. the URL endpoint for Okta) to authenticate through native Okta (only supported if your IdP is Okta).

Default is snowflake.

We need the ability to select/enter any of the thee type of authentication options.

**Comment by subodhchhabra** [comment]
this is fixed in 5.1.5 (#3874 )

**Comment by serge-rider** [comment]
You can get 5.1.5 here - https://dbeaver.io/files/ea/

**Comment by serge-rider** [comment]
I'll add extra connection parameter on the main connection page.

![image](https://user-images.githubusercontent.com/6398845/43689738-6ba84a94-9907-11e8-88f6-2e6dd4c062d9.png)
