### ISSUE TITLE
5.1.4 - Previous bad query blocking all future queries.  SQL Error [25P02]

### ISSUE THREAD

**Issue by metrostat** [dbeaver/dbeaver#3904]
SQL Error [25P02]: ERROR: current transaction is aborted, commands ignored until end of transaction block.
This is happening when connecting to Postgresql db.  Only started after upgrading to  dbeaver version 5.1.4

**Comment by infectormp** [comment]
i have this at 5.1.3

**Comment by serge-rider** [comment]
You need to commit/rollback or switch to auto-commit mode or enable Rollback on error option:
![image](https://user-images.githubusercontent.com/6398845/43673793-6380df52-97d1-11e8-9010-fd7598e448e9.png)

**Comment by infectormp** [comment]
@serge-rider Thank you.
