### ISSUE TITLE
Alt-gr + Space shortcut binding issue

### ISSUE THREAD

**Issue by EatZeBaby** [dbeaver/dbeaver#3906]
Hey,

I am using a BÉPO layout keyboard on which the '_' symbol is bound to AltGr + Space
My issue is that when I try it on th SQL Editor, I get a popup that says **"No Proposals"**

![dbeaver_alt_gr_space_issue](https://user-images.githubusercontent.com/6329364/43572149-0fd6dfca-963f-11e8-803b-5459d750d791.png)

How can I bypass this ? I have tried to unbind this shortcut but I cannot find out where to do it.

Thanks,

**Comment by antoniustefan** [comment]
Most keyboards don't have AltGr as a special key, but actually send Ctrl+Alt, so most likely your AltGr+Space is intepreted by DBeaver as Ctrl+Space, which is the Content Assist shortcut:

![db](https://user-images.githubusercontent.com/7008135/43579094-9554cdd2-9659-11e8-8317-b50f445c8db1.png)

**Comment by EatZeBaby** [comment]
Thanks a lot @antoniustefan  ! It was this shortcut 👍
