### ISSUE TITLE
DBeaver vs. Postgersql 10

### ISSUE THREAD

**Issue by ArieStern** [dbeaver/dbeaver#3910]
I have the DBeaver EE. I used it to connect to postgresql 9.6, but now I cannot connect to version 10.
I got error message: The connection attemp failed.
Do I need and driver I don't have?

TIA
Arie

**Comment by serge-rider** [comment]
Could you post full error message with stacktrace?
You can get stacktrace in Error Log view - just double click on the error. To open Error Log view: main menu Window->Show View->Error Log.

**Comment by serge-rider** [comment]
Generally connection to PG 10 should work fine (I'm working with PG 10 from my DBeaver EE at this very moment). So most likely something is wrong with configuration/server state.
Check this: https://stackoverflow.com/questions/15806083/org-postgresql-util-psqlexception-the-connection-attempt-failed

Also you could try to download EA version (https://dbeaver.com/files/ea/), it containes newer PostgreSQL driver (42.2.3) - in some cases this might help.

**Comment by ArieStern** [comment]
I succedded  to connect
Thanks!
