### ISSUE TITLE
How to Remove Check For Updates Option in Help Menu (Dbeaver 4.2.2) 

### ISSUE THREAD

**Issue by CharanDE** [dbeaver/dbeaver#3913]
Hi i am new to Github as well as Application Packaging,i have problem with dbeaver 4.2.2,i don't know How to Remove Check For Updates Option in Help Menu.any registry file adding or editing,or any way to remove Check For Updates in the help menu.can any one help me with this.

Thanks,
Charan

**Comment by serge-rider** [comment]
Generally it is not possible to remove menu items by changing some config option.

But why do you need this?
And why do you use so old version of DBeaver?
