### ISSUE TITLE
PG: restore in directory format doesn't work

### ISSUE THREAD

**Issue by aekoise** [dbeaver/dbeaver#3915]
Thanks for providing this great tool. It has been my default DB tool for some years now. It appears the restore tool for PostgreSQL database does not seem to work. Seems to have been nonfunctional (at least for me) for some versions now.

v5.1.4

1. Select a database and schema, right click to Tools/Restore
2. Format : Directory
3. Backup file : Copy the backup directory path into the text field (note selecting a directory does not seem possible with the dialog box that comes up)
4. Provide authentication information
5. Start

**I see the following error
C:\PostgreSQL\9.6\bin\pg_restore.exe --list --verbose --host=localhost --port=5432 --username=postgres --format=d --dbname=sampledb
Restore started at Thu Aug 02 15:16:34 EDT 2018
 C:\dbpath\backup-dir (The filename, directory name, or volume label syntax is incorrect)
pg_restore: [directory archiver] no output directory specified**

**Comment by serge-rider** [comment]
I think this feature (restore from directory) never worked.
Now fixed, thanks for bug report.

**Comment by aekoise** [comment]
Thanks for fixing this issue. Not sure I got the tar/custom format to work too, though I mostly use the directory format
