### ISSUE TITLE
Vertical bar appears while editing SQL

### ISSUE THREAD

**Issue by dharvey-consbio** [dbeaver/dbeaver#3916]
On Ubuntu 16.04, with DBeaver Community Edition version 5.1.4, I have begun to see a vertical scroll bar that appears in the middle of the editor when I press Enter, from after the cursor to the bottom of the editor, that hides whatever content follows the new line.

This wouldn't be so bad, except when I press Enter in the middle of a long query, for instance, to add another join clause, the bar hides the rest of the query, and the only way I've found to get the hidden part of my query back is to Undo (Ctrl+Z) my last change.

This has been happening with both Postgres and MySQL databases. I don't think it is specific to the database vendor.

I have attached a file showing a query to `information_schema` in MySQL. I thought about adding more than one picture to demonstrate, but if you hit Enter in the middle of the query, it just looks like that's all you have written as yet, so an additional picture wouldn't seem to help illustrate.

![vertical-bar](https://user-images.githubusercontent.com/15349136/43608511-1fea31b6-9656-11e8-938d-60ec2136eac5.png)

**Comment by ssuraci** [comment]
I confirm this problem,  DBeaver Community Edition version 5.1.4 on Ubuntu 16.04 ... SQL Window is almost unusable for complex queries.

**Comment by cheekybuddha** [comment]
See also:
[Issue 3895](https://github.com/dbeaver/dbeaver/issues/3895)
[Issue 3884](https://github.com/dbeaver/dbeaver/issues/3884)
[Issue 3864](https://github.com/dbeaver/dbeaver/issues/3864)

**Comment by lcnmorais** [comment]
I am working with Debian 9 64bits, JVM 10 - the same issue.

**Comment by serge-rider** [comment]
This issue has the same cause as #3864
Please try this workaround:
delete following lines from dbeaver.ini file:
```
--launcher.GTK_version
2
```

**Comment by serge-rider** [comment]
And you could try this in EA version (https://dbeaver.io/files/ea)

**Comment by ivanelson** [comment]
I have this same problem. :(

**Comment by serge-rider** [comment]
@ivanelson Did you try 5.1.5?

**Comment by ivanelson** [comment]
@serge-rider I think 5.1.5 is not yet in the PPA. 

```
sudo apt install dbeaver-ce --upgrade
# dbeaver-ce is already the newest version (5.1.4~ubuntu16.04).
```

**Comment by serge-rider** [comment]
Yes. We update PPA only after release.

**Comment by ivanelson** [comment]
Ok! I [downloaded](https://dbeaver.io/files/ea) it manually and installed it. 

Resolved.

**Comment by lcnmorais** [comment]
Hello serge-rider, I have excluded 

**--launcher.GTK_version**

And now it is working properly.

My best regards.

**Comment by cumanacr** [comment]
Hi serge-ride after the workaround deleting lines from dbeaver.ini file:

<pre>
--launcher.GTK_version
2
</pre>

Vertical bar problem is gone, good, but, the toolbar with the database name connection cuts in half, not a big deal but maybe you can work it out in next release.

![selection-06-2018-08-10](https://user-images.githubusercontent.com/6874136/43982709-74698b4c-9cb4-11e8-8da5-a7808563e563.png)


Regards

**Comment by serge-rider** [comment]
@cumanacr What is your OS?

**Comment by cumanacr** [comment]
@serge-rider hi, this one:
<pre>
$ lsb_release -a
No LSB modules are available.
Distributor ID: neon
Description:    KDE neon User Edition 5.13
Release:        16.04
Codename:       xenial
</pre>

**Comment by serge-rider** [comment]
I'll fix this as much as possible. The problem is in huge arrow button in the new Eclipse + GTK.

**Comment by vpmv** [comment]
I'm sorry to say this problem arose for me when I updated to 5.2.3! Linux Mint 18.3 (= Ubuntu 16.04 / Xenial). It's not just the vertical scroll bars appearing everywhere around the SQL editor, but there's also white overlays and line duplication. Pretty annoying.

**Comment by serge-rider** [comment]
We migrating to the most recent Eclipse platform. In version 5.2.4 we'll switch to GTK3 - this will resolve problem with scrollbars.
