### ISSUE TITLE
AWS Athena using Amazon temporary security tokens ?

### ISSUE THREAD

**Issue by yuribudilov** [dbeaver/dbeaver#3918]
Hello

can someone point me to the documentation on how to access AWS Athena from DBeaver (latest version 5.1.4 as of 3 Aug 2018) using AWS temporary security session tokens? (i.e. access key, secret key and session token). 

thank you!

**Comment by serge-rider** [comment]
I can't help with that right now. But this may be related to #1515

**Comment by yuribudilov** [comment]
Thanks I managed to get it working using this ProviderClass in DBeaver 5.1.4

com.simba.athena.amazonaws.auth.profile.ProfileCredentialsProvider

I set DBeaver ProviderArguments to default

(this provider class is not documented in AWS Athena JDBC document as far as I can see).

At the very least this is AWS Athena JDBC documentation bug/omission.

**Comment by mnt1979** [comment]
@yuribudilov 
How did you mention SESSION token?   Would you be able to guide me to connect to Athena using ACCESS KEY, SECRET KEY, and SESSION TOKEN?

**Comment by Hammond95** [comment]
@mnt1979 I managed to make it work.

1) Put random stuff in the default `AWS Access Key` and `AWS Secret Key`.
2) Go to driver properties and set:
    - `AwsCredentialsProviderClass` to `com.simba.athena.amazonaws.auth.profile.ProfileCredentialsProvider`
    - `AwsCredentialsProviderArguments` equal to the name of the profile you want to use (see ~/.aws/config to see which profiles you have)

**Comment by johjairo** [comment]
> @mnt1979 I managed to make it work.
> 
> 1. Put random stuff in the default `AWS Access Key` and `AWS Secret Key`.
> 2. Go to driver properties and set:
>    
>    * `AwsCredentialsProviderClass` to `com.simba.athena.amazonaws.auth.profile.ProfileCredentialsProvider`
>    * `AwsCredentialsProviderArguments` equal to the name of the profile you want to use (see ~/.aws/config to see which profiles you have)
> 3. Test Connection and it should work.

Hola hice tus pasos pero el problema con mi conexion es que es a traves de rol, es decir con un profile me conecto pero luego para acceder al recurso debo hacerlo a traves de un ROL, entonces no me permite realizarlo.

Puedes ayudarme?

**Comment by JoaoCarabetta** [comment]
> @mnt1979 I managed to make it work.
> 
> 1. Put random stuff in the default `AWS Access Key` and `AWS Secret Key`.
> 2. Go to driver properties and set:
>    
>    * `AwsCredentialsProviderClass` to `com.simba.athena.amazonaws.auth.profile.ProfileCredentialsProvider`
>    * `AwsCredentialsProviderArguments` equal to the name of the profile you want to use (see ~/.aws/config to see which profiles you have)
> 3. Test Connection and it should work.

I'd just add that DBeaver is going to look for a credential file in `~/.aws/credentials`. Which has to be like:

```
[<profile-name>]
aws_access_key_id=<your-key-id>
aws_secret_access_key=<your-access-key>
aws_session_token=<your-token>
```

**Comment by Hammond95** [comment]
@johjairo Disculpa, yo no ablo español (italian or english)

**Comment by rodrich** [comment]
> @mnt1979 I managed to make it work.
> 
>     1. Put random stuff in the default `AWS Access Key` and `AWS Secret Key`.
> 
>     2. Go to driver properties and set:
>        
>        * `AwsCredentialsProviderClass` to `com.simba.athena.amazonaws.auth.profile.ProfileCredentialsProvider`
>        * `AwsCredentialsProviderArguments` equal to the name of the profile you want to use (see ~/.aws/config to see which profiles you have)
> 
>     3. Test Connection and it should work.

That works fine @Hammond95!! Thank you so much!! 
Just one question, in case of aws single sing-on portal, is there any way to do easier for updating ~/.aws/config file?

**Comment by Hammond95** [comment]
> > @mnt1979 I managed to make it work.
> > ```
> > 1. Put random stuff in the default `AWS Access Key` and `AWS Secret Key`.
> > 
> > 2. Go to driver properties and set:
> >    
> >    * `AwsCredentialsProviderClass` to `com.simba.athena.amazonaws.auth.profile.ProfileCredentialsProvider`
> >    * `AwsCredentialsProviderArguments` equal to the name of the profile you want to use (see ~/.aws/config to see which profiles you have)
> > 
> > 3. Test Connection and it should work.
> > ```
> 
> That works fine @Hammond95!! Thank you so much!!
> Just one question, in case of aws single sing-on portal, is there any way to do easier for updating ~/.aws/config file?

Do you mean if you have in place something like Okta?

**Comment by rodrich** [comment]
> > > @mnt1979 I managed to make it work.
> > > ```
> > > 1. Put random stuff in the default `AWS Access Key` and `AWS Secret Key`.
> > > 
> > > 2. Go to driver properties and set:
> > >    
> > >    * `AwsCredentialsProviderClass` to `com.simba.athena.amazonaws.auth.profile.ProfileCredentialsProvider`
> > >    * `AwsCredentialsProviderArguments` equal to the name of the profile you want to use (see ~/.aws/config to see which profiles you have)
> > > 
> > > 3. Test Connection and it should work.
> > > ```
> > 
> > 
> > That works fine @Hammond95!! Thank you so much!!
> > Just one question, in case of aws single sing-on portal, is there any way to do easier for updating ~/.aws/config file?
> 
> Do you mean if you have in place something like Okta?

I mean aws SSO auth, but I think just found something useful link in case someone else need it
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html

**Comment by Hammond95** [comment]
@rodrich we haven't enabled the AWS SSO yet, so I couldn't try, I will let you know.

**Comment by rodrich** [comment]
> @rodrich we haven't enabled the AWS SSO yet, so I couldn't try, I will let you know.
Thanks @Hammond95!!

**Comment by neitomic** [comment]
> @mnt1979 I managed to make it work.
> 
> 1. Put random stuff in the default `AWS Access Key` and `AWS Secret Key`.
> 2. Go to driver properties and set:
>    
>    * `AwsCredentialsProviderClass` to `com.simba.athena.amazonaws.auth.profile.ProfileCredentialsProvider`
>    * `AwsCredentialsProviderArguments` equal to the name of the profile you want to use (see ~/.aws/config to see which profiles you have)
> 3. Test Connection and it should work.

Note that the profile name should include `profile ` prefix.

**Comment by KulykDmytro** [comment]
@neitomic @mnt1979 thanks for point
where to set ?
> Put random stuff in the default AWS Access Key and AWS Secret Key.

will it work in CE?

**Comment by neitomic** [comment]
> @neitomic @mnt1979 thanks for point where to set ?
> 
> > Put random stuff in the default AWS Access Key and AWS Secret Key.
> 
> will it work in CE?

Yes, it works on CE.
If you want to use Athena with SSO, you can look into this https://github.com/neitomic/simba-athena-driver-sso-support
