### ISSUE TITLE
DBeaver EE asks for license which blocks access to preferences to set proxy

### ISSUE THREAD

**Issue by ramazanpolat** [dbeaver/dbeaver#3920]
DBeaver EE tries to connect to internet to generate a trial license. 
But it is not possible to access internet without entering proxy information, which is blocked by UI.
Since EE version is for Enterprise and most enterprise company uses proxy, it makes it impossible to have use EE version.

**Comment by serge-rider** [comment]
For such cases it is possible to generate trial license on the web site (https://dbeaver.com/trial/).
And then copy-paste license text in the license manager dialog.

Although providing access to proxy settings from license manager dialog also makes much sense, thanks for noticing.
