### ISSUE TITLE
Make the auto-switch to active database configurable (Feature request)

### ISSUE THREAD

**Issue by jyinpci** [dbeaver/dbeaver#3921]
In 5.1.2, Postgresql database can be auto-switched to active by simply double clicking on the database.  There is a checkbox in the Edit-connection page for activating this feature.  But this feature has been removed since 5.1.3.  I would like to ask the great developers of DBeaver to bring back this very convenient feature.  If this is unique to PG (not available to other databases), at least make this a configurable feature, instead of removing it.

Thanks!

**Comment by uslss** [comment]
already implemented
