### ISSUE TITLE
How do I manually add artifacts in DBeaver?

### ISSUE THREAD

**Issue by rajib2k5** [dbeaver/dbeaver#3922]
I need to manually add these two maven artifacts in copied driver section of Driver Manager:
org.apache.hive:hive-jdbc:RELEASE and org.apache.hadoop:hadoop-core:RELEASE

I'd appreciate few pointers

**Comment by serge-rider** [comment]
I'd suggest to download Hive uber jar (https://github.com/timveil/hive-jdbc-uber-jar) and just add it in driver libraries.
BTW this driver is included in DBeaver EE (you can get it from trial version).

**Comment by rajib2k5** [comment]
My question was a follow up to a bug discovered with copy-driver function.

In that thread, it was suggested that I add the driver manually via Add-Artifaction option. I haven't done that before. That's why I opened this separate thread.

**Comment by tati-kru** [comment]
This was implemented for DBeaver EE and most likely won't be in CE near future.
