### ISSUE TITLE
[Feature request] Single-line comment format

### ISSUE THREAD

**Issue by Karsonito** [dbeaver/dbeaver#3923]
I will be very grateful to the ability to configure the syntax of a single-line comment.
The matter is that some editors (for example JetBrains products) use the universal format of comments: "-- " - two hyphens and space.
I want to be able to use the same format for any connection (for mysql and for vertica) for compatibility without unnecessary editing
Currently only mysql connections has such format of single-line comment.

**Comment by serge-rider** [comment]
Most of databases have this format of single line comment (including Oracle, PostgreSQL, DB2, etc - in fact it is standard SQL comment). But without extra space (which is MySQL-specific). Is missing space a problem in some cases?
