### ISSUE TITLE
Parameter input prompt

### ISSUE THREAD

**Issue by legrosa** [dbeaver/dbeaver#3924]

**Comment by legrosa** [comment]
Hi
I have an sql statement joining 2 files. In which I ask it prompt for period number. This it does.
However when I wrap a create table around this sql (create table x as (select ......) wth data.
Then the prompt for Period does not happen.
Are there any preferences I should be setting? I have tried the sql processing ones?

Tony

**Comment by legrosa** [comment]
Hi - thanks for quick response.
I checked the preferences that I have and they exactly as your screenshot above.
Unfortunately it still does not prompt for the parameter. Running the sql when not wrapped in a create table statement does prompt. I can post the actual sql if you wish.
Tony

**Comment by serge-rider** [comment]
Ah, I see. You need to turn on "Enable parameters in DDL" option (create table is DDL command and parameters are disabled for such queries by default).

**Comment by legrosa** [comment]
Excellent that worked thank you very much.
