### ISSUE TITLE
Eclipse (Photon) plugin update error for DBeaver 5.1.4

### ISSUE THREAD

**Issue by kiravi** [dbeaver/dbeaver#3926]
Eclipse plugin does not install.

When you update DBeaver 5.1.4 plugin for eclipse (Photon) --> the following is the install error.

Error log:

An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext,3.0.25.20180620133858
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.ant,3.0.25.20180620133858
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.asciidoc,3.0.25.20180620133858
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.asciidoc.ui,3.0.25.201806201740
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.confluence,3.0.25.20180620133858
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.confluence.ui,3.0.25.201806201740
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.context.ui,3.0.25.201806201740
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.help.ui,3.0.25.201806201740
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.html,3.0.25.20180620133858
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.markdown,3.0.25.20180620133858
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.markdown.ui,3.0.25.201806201740
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.mediawiki,3.0.25.20180620133858
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.mediawiki.ui,3.0.25.201806201740
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.osgi,3.0.25.201806201740
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.tasks.ui,3.0.25.201806201740
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.textile,3.0.25.20180620133858
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.textile.ui,3.0.25.201806201740
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.tracwiki,3.0.25.20180620133858
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.tracwiki.ui,3.0.25.201806201740
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.twiki,3.0.25.20180620133858
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.twiki.ui,3.0.25.201806201740
No repository found containing: osgi.bundle,org.eclipse.mylyn.wikitext.ui,3.0.25.201806201740
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.wikitext.editors_feature,3.0.25.201806201740
No repository found containing: org.eclipse.update.feature,org.eclipse.mylyn.wikitext_feature,3.0.25.201806201740

**Comment by serge-rider** [comment]
Can't reproduce. Just rechecked on Eclipse 4.7 and 4.8.
What Eclipse package do you use? (e.g. Java IDE).
Maybe you have some other 3rd party extension installed.

DBeaver has nothing to do with mylyn.wikitext extension.

**Comment by serge-rider** [comment]
This was fixed in #4201
