### ISSUE TITLE
not finish sql execution (fetch Redshift data)

### ISSUE THREAD

**Issue by fr-takumaurata** [dbeaver/dbeaver#3928]
Dbeaver 5.1.4 (japanese)
windows 7 32bit
Redshift

I'm beginner.
I just have installed dbeaver and connected redshift. 
I tried to check my redshift table data by double click on table tree in database navigator column.
It shows 'Execute Query ***s' in result column, and not finish fetching though takes many seconds over 1000 secs.

Finally, it showed problem popup window contents below.
```
"定期的なワークスペースの保管。" 中に内部エラーが発生しました。
Cannot set lower sequence number for root (previous: 8, new: 7). Location: C:\Users\********\.dbeaver4\.metadata\.plugins\org.eclipse.core.resources\.safetable\org.eclipse.core.resources
```

**Comment by serge-rider** [comment]
Could you check log files for any related errors? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

The error you posted (Cannot set lower sequence number..) is not related to data reading. Most likely your workspace was corrupted (e.g. by killing DBeaver process or unexpected reboot). You could try to delete `.metadata\.plugins\org.eclipse.core.resources\` folder.
