### ISSUE TITLE
Question: Is it possible to edit a query results grid originating from a custom query on MSSQL DB

### ISSUE THREAD

**Issue by aviennas** [dbeaver/dbeaver#3930]
- Question
is it possible to edit a query results grid originating from a custom query on MSSQL DB?   That is provided in MSQL, it should be provided on a ODB profile (with FOR UPDATE clause) but how to do in MSSQL? 

- Operating System
MacOS High Sierra 10.13.6

- DBeaver plugin  5.1.3 on Spring Tool Suite 3.9.4.RELEASE [Build Id: 201804120943, Eclipse Neon.3 (4.6.3)]

**Comment by aviennas** [comment]
one workaround is to choose "Edit Table" from the context menu of "Database Navigator > My SQL Connection > Tables > My Table" choice of "Data" tab and right click on top left corner selecting "Order Filter > Customize" and deselecting all ("show none" icon button) finally selecting the appropriate columns of the query and choosing ok to apply selections to view.

**Comment by serge-rider** [comment]
For MS SQL this works for any custom SQL.
Note: you need to use jTDS driver. Native driver doesn't provide valid meta information about columns.
Note: you must include some unique key columns in results to be able to edit.

**Comment by aviennas** [comment]
That's great news, thank you very much!

**Comment by serge-rider** [comment]
Umm, it works at least with some tables..
Could you post sample table DDL and sample query. Maybe even using system tables.

**Comment by aviennas** [comment]
Apologies for the somewhat late reply, the lag is due to time required for me to setup a VM enviroment so that I can test it outside of work premises, restore database under discussion and configure connectivity. Out of pure luck the issue revealed itself. What was causing the locking of the grid had been the non use of the schema-owner before the table name. The given database was the only database within so the schema user prefix was not necessary for the driver to resolve the proper object. Putting the prefix before the table name made the grid editable.

**Comment by serge-rider** [comment]
Yeah, SQL Server has tricky schemas. 
DBeaver currently doesn't support default schema get/set (although it supports default database change), that's why it can't find objects if schema is not specified.

Somebody should make a feature request for def schema detection )

Closing this one.
