### ISSUE TITLE
UI: Connection settings broken for oracle (5.1.4)

### ISSUE THREAD

**Issue by infectormp** [dbeaver/dbeaver#3932]
When i open connection setting for Oracle buttons "OK" and "Test connection" not active
![image](https://user-images.githubusercontent.com/9958813/43717138-3fcde4b4-998f-11e8-9ed2-c0450f39528d.png)
For mariadb and postgre all fine
![image](https://user-images.githubusercontent.com/9958813/43717251-983eb308-998f-11e8-98b5-51ba5fd1c11d.png)

**Comment by serge-rider** [comment]
It is nor a bug. Network alias isn't chosen for connection so it is not possible to connect using TNS method.
Check TNS names path. File tnsnames.ora must be in this folder.

**Comment by infectormp** [comment]
you right, i not have tnsnames.ora on my PC. But connection to oracle still work, fantastic :)
