### ISSUE TITLE
UI: General tab is oversized (5.1.4)

### ISSUE THREAD

**Issue by infectormp** [dbeaver/dbeaver#3933]
General tab is oversized
![image](https://user-images.githubusercontent.com/9958813/43717410-29cb5e70-9990-11e8-9b75-f302ef377a89.png)

**Comment by serge-rider** [comment]
Agreed. Perhaps we need to split it on 2 or 3 pages (General, Filters, Bootstrap settings)

**Comment by serge-rider** [comment]
General connection page was redesigned.
Password save checkbox was moved to individual database connection pages.
Connection initialization settings were moved on "Initialization" sub-page.

![image](https://user-images.githubusercontent.com/6398845/44004256-7c141154-9e68-11e8-981d-928441597f30.png)
![image](https://user-images.githubusercontent.com/6398845/44004258-7fc5e016-9e68-11e8-99fc-a24981e1d4c2.png)
![image](https://user-images.githubusercontent.com/6398845/44004260-826060ee-9e68-11e8-8bca-6949bf30e72e.png)

I also thinking about moving filters to a separate page. But not at the moment.
