### ISSUE TITLE
SQLite, csv, ... Autorization - login

### ISSUE THREAD

**Issue by mkgrgis** [dbeaver/dbeaver#3935]
![default](https://user-images.githubusercontent.com/41448637/43728127-c2259340-99ac-11e8-9e1b-45ba06538b6f.gif)

**Comment by serge-rider** [comment]
User name/password fields are present because some SQLite drivers (with extensions) might use encrypted data files.
Just ignore these fields for regular SQLite database.

**Comment by mkgrgis** [comment]
К вопросу об излишних полях в авторизации. csv не требует даже пароля. Предлагается затенить или отключить ненужные поля.

**Comment by serge-rider** [comment]
It will be configurable in 5.1.5:
![image](https://user-images.githubusercontent.com/6398845/43907017-41ce8b40-9bfd-11e8-99ca-803741c3785f.png)
