### ISSUE TITLE
Remote DBeaver workspace storage (Git)

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#3938]
For team collaboration and to be able to access your settings from any machine we need to support remote workspaces. Kind of a server.
We can keep everything in some Git repository.
Artifacts:
- workspace (connections, scripts, bookmarks, diagrams)
- drivers (actual jars)
- preferences?

On DBeaver start it will ask for credentials (Git user actually). And then pull everything. On save it will push all work. Maybe on a special button push.

Any Git repository can be used although we can provide special "Beaver Cloud" if user don't want to care about Git and other admin stuff. We'll create repository for him/organization.

We'll need to include Git integration in base DBeaver package.
Also we'll need to support workspace switch in DBeaver.

Most likely this will be initially implemented for EE version only. Or some features will be EE-only.

**Comment by serge-rider** [comment]
Please post any suggestions. Including security, UI proposals, etc.

**Comment by Speirs47** [comment]
How about a list of things to store so a user can actually choose what to save to the cloud. If I would use it I wouldn't like to save my connections. Some other person wouldn't want to save his scripts.

**Comment by serge-rider** [comment]
Agreed.

**Comment by serge-rider** [comment]
In 6.1.2 we'll add Git UI integration (see #5581).
Extra features will be added in further versions.

**Comment by E1izabeth** [comment]
The issue is not actual anymore
