### ISSUE TITLE
Cannot create connection to Athena

### ISSUE THREAD

**Issue by shanikovalsky** [dbeaver/dbeaver#3941]
I downloaded DBeaver 5.1.4, trying to create a new connection with Athena. 
In the JDBC URL field, I cannot enter anything. 
After typing something in the "User name" field, the above field is populated with a generic URL (jdbc:awsathena://AwsRegion=us-east-1;), which cannot be changes or deleted.:

![image](https://user-images.githubusercontent.com/13198742/43768195-7197a100-9a3f-11e8-9a1c-f2119ae4a039.png)

Thanks!

**Comment by serge-rider** [comment]
You can change connection URL in driver setting. Standard Athena URL do not support database name and other standard parameters. Target database is defined by user credentials.

**Comment by serge-rider** [comment]
Unfortunately I can't test Athena connection right now.
As said here - https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.2/docs/Simba+Athena+JDBC+Driver+Install+and+Configuration+Guide.pdf - is should support standard JDBC way to specify user credentials.
If not then you can set hem manually in driver properties (Username and Password properties).

Please write back if it will help. I'll improve connection dialog to simlify user experience for Athena.

**Comment by Coqueiro** [comment]
I'm also not being able to connect to Athena using a driver. I have a different screen than @shanikovalsky 's:
![image](https://user-images.githubusercontent.com/8795402/47311001-0ca82600-d60f-11e8-8af7-949619d4ca43.png)
What informations can I provide to help the case?

**Comment by serge-rider** [comment]
We added  comletely new connection age for Athena in 5.2.3. What DBeaver version do you use?

**Comment by ecrepeau-sesac** [comment]
Also, not able to create an Athena connection using 5.2.3. Selecting Athena returns no page to enter connection details, credentials, etc...

**Comment by serge-rider** [comment]
Yep, it is a bug in Athena connection page in the latest version.
It should look look this:

![image](https://user-images.githubusercontent.com/6398845/47768768-76e55880-dcea-11e8-89d7-2759ae213be6.png)

Thanks for the bug report.

**Comment by keshavkaul** [comment]
@serge-rider Thanks for Acknowledging the issue. Waiting for the fix. Approx. What version will this be fixed?

**Comment by AnnLeeDC** [comment]
Thanks @serge-rider  and OP! 
I have a question: For federated MFA user, how to set up connection? I've checked the configure file and the credential file, don't see the specific Access Key ID and Secret Key any more (they got overwritten when I set up MFA device)...
