### ISSUE TITLE
CSV to Oracle DB transfer error: Length too long for VARCHAR 

### ISSUE THREAD

**Issue by tfarkas86** [dbeaver/dbeaver#3944]
When exporting a CSV to a database, the default mapping datatype for all columns is VARCHAR with length 32767, but this is too long for my version of Oracle leading to a failed data transfer. Changing the size to 4000 lets the transfer proceed. Is there a way to change the default size?

DBeaver 5.1.4
Windows 10, 14393.0

**Comment by serge-rider** [comment]
Currently it is not supported. Mark as FR.

**Comment by serge-rider** [comment]
See fix in 5.2.2
