### ISSUE TITLE
Question - How to build DBeaver as an RPM from the source code?

### ISSUE THREAD

**Issue by dinbtechit** [dbeaver/dbeaver#3945]
### Question:

1) How to build DBeaver as an RPM from the source code?  `mvn clean package` only creates the zip file.
`https://github.com/dbeaver/dbeaver.git`

2) And where is the spec or script that is responsible to create dbeaver RPM? can't seems to find that in the source code.

Thanks!

**Comment by serge-rider** [comment]
We use redline-rpm packager but you could you any rpm packager including native Linux ones.
It is quite simple as binaries built by Maven are passed into Linux package with just a few changes.

Unfortunately DBeaver packaging scripts are not public domain. Besides other things they include code sign procedures, certificates and other non-public stuff.

**Comment by dinbtechit** [comment]
Appreciate your turn around. That helps.. thank you.
