### ISSUE TITLE
Duration ms on title bar

### ISSUE THREAD

**Issue by cunay1** [dbeaver/dbeaver#3946]
Hi, can you remove ms letters for milisecond from the execution Log and Query Manager bar. Instead of row value , can you move ms information on titlebar. For example: On title column Duration-ms or Duration(ms). We don't need ms information for each row. Title bar is enough for it.. For example: Duration-ms or Duration(ms). By this solution, I can import log value into maintenance database without using function. Only integer values are good enough I think.
![capture](https://user-images.githubusercontent.com/15732596/43821768-b416c2be-9af2-11e8-9dfa-3c4eb7429840.PNG)

**Comment by serge-rider** [comment]
Good point
