### ISSUE TITLE
[BUG] Postgres via SOCKS Proxy doesn't connect with v5.1.3, v5.1.4

### ISSUE THREAD

**Issue by anphung** [dbeaver/dbeaver#3947]
New connection > Choose PostgreSQL > Fill in Host, Port, etc. > Next > Choose SOCKS Proxy tab > Fill in detail > Click Test Connection ...

Got
```
Connection to 172.18.0.6:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

v5.1.2 works fine.

**Comment by serge-rider** [comment]
The fix was pushed in #3592.
Could you test the fix in EA (https://dbeaver.io/files/ea/) ?
