### ISSUE TITLE
Set column minimum width to consider text width "[NULL]" when presenting data in text grid

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#3949]
DBeaver - **Version 5.1.4 CE**
Operating System: **Windows 10**

Set column minimum width to consider text width "**[NULL]**" when presenting data in text grid.

Today if a column has a character width less than what is needed to present the "[NULL]" characters, the columns are shifted to the right.

Looks something like this:

```
|Unr                                  |ClinicId |Sign |PersonId |
|-------------------------------------|---------|-----|----------|
|A957FAFF-FF14-4BD4-A994-0521767B1C70 |1        |ab   |1         |
|43F5ECFF-2403-4F84-A32F-92825BC9AD2B |1        |[NULL]|2         |
|8600CCFF-6941-4D21-9163-129E18C00E7D |1        |ab   |3         |
|D7F97F00-43C5-4E27-93A2-C72A6031B91F |1        |ab   |[NULL]    |
```

If _DBeaver_ property **Result Sets -> Presentation -> Plain text -> Show NULLs** is checked, then all (or those columns that have type that allow NULL) columns should have a minimum width where the "**[NULL]**" characters fit.

**Comment by serge-rider** [comment]
Thanks for bug report
