### ISSUE TITLE
MS SQL Server Synonyms

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#3950]
DBeaver - Version 5.1.4 CE
Operating System: Windows 10
JDBC Driver: jTDS 1.3.1

I am using Microsoft SQL Server Database
But i am not able to see synonyms at all in DBeaver. 
I can see the synonyms using SQL Server Management Studio though.

Screenshot below shows i do not see Synonyms in DBeaver. Can someone please assist me why this is the case ?
We have tried using Microsoft JDBC driver also, but we do not see any change.

![image](https://user-images.githubusercontent.com/38669892/43841188-2ed5ed00-9ae8-11e8-835b-9e4ebbdba60e.png)

**Comment by serge-rider** [comment]
Synonyms are not supported by MS SQL extensions. But it is easy to implement (at least in read-only mode).
