### ISSUE TITLE
Move results window from vertical to horizontal

### ISSUE THREAD

**Issue by nojohnny101** [dbeaver/dbeaver#3951]
For the life of my, I cannot figure out how to move the results window back to below the script window that has tables for each of my SQL scripts. This was the default layout, but I did something on accident and now the results window is next to the tabbed SQL scripts.

I have gone through all settings under the menu of SQL Editor and Window and nothing works, even resetting the perspective. What am I missing?

**Comment by serge-rider** [comment]
SQL editor context menu:
![image](https://user-images.githubusercontent.com/6398845/43849711-bea42996-9b3e-11e8-90e5-e4e6f2114f3b.png)

**Comment by nojohnny101** [comment]
Hmmm, I don't have that menu. I'm on 5.1.0

**Comment by nojohnny101** [comment]
I just updated to the latest and that option is still not present.

**Comment by serge-rider** [comment]
It was there for ages. 
Could you post screenshot of your SQL editor context menu?

**Comment by nojohnny101** [comment]
![screenshot](https://user-images.githubusercontent.com/17462544/43851510-e5012bba-9b08-11e8-82ae-6b6d2065a907.png)

**Comment by serge-rider** [comment]
Context menu is the one which appears when you right-click in editor area. 
Or press shift+f10 (on windows), or click with two fingers or click with ctrl pressed (on mac).

Big number of DBeaver features are accessible only from context menus.

**Comment by nojohnny101** [comment]
Got it! Of all the things I tried, I didn't try that. Thank you. Good to know for future as well!

**Comment by syspone** [comment]
Aqui comigo funcionou certinho, Obrigado pela ajuda ai pessoal. Lembrando que esse procedimento é na IDE DBEAVE.

**Comment by Kagezod** [comment]
![image](https://github.com/user-attachments/assets/d8a91756-b5fb-473d-9d66-76403a7fe16f)
You mean it looks like this? It's my sound very dumb but... just press tab
![image](https://github.com/user-attachments/assets/c529d320-e1b9-4931-b3a4-bc1dd006c6e2)
It was my problem till I discover it by accident just now...
