### ISSUE TITLE
Improve auto expansion of * when select has joins

### ISSUE THREAD

**Issue by rlbatista** [dbeaver/dbeaver#3952]
DBeaver 5.1.4. CE for Windows

When I hit CTRL+SPACE on *, this expands only columns of FROM table, any joins are ignored.
It would be nice if this shortcut were able to expand the columns of all tables or better yet, if it were possible to choose based on the table alias which columns to expand, like this:.

*no worry about syntax to keep example simple*
### tbl_1
column 1|column 2|column 3
-|-|-
id|a|b

### tbl_2
column 1|column 2|column 3|column fk
-|-|-|-
id|c|d|tbl_1_id

```select * from tbl1 t1 join tbl2 t2 on t1.id = t2.tlb_1_id```
```ctrl+space``` expand to
```select t1.id, t1.a, t1.b, t2.id, t2.c, t2.d, t2.tbl_1_id from ....```

```select t1.* <hit ctrl+space here>, t2.* from tbl1 t1 join tbl2 t2 on t1.id = t2.tlb_1_id```
expand to
```select t1.id, t1.a, t1.b, t2.* from ....```

and so on...

**Comment by uslss** [comment]
already implemented
