### ISSUE TITLE
Set default visibility of the Values Tab back to False

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#3953]
DBeaver - **Version 5.1.4 CE**
Operating System: **Windows 10**

In one of the later versions of _DBeaver_ a change was made to the default visibility of the **Value** tab.

Now if I have make a new installation of _DBeaver_ 5.1.1 - 5.1.4 and a data **Result grid** is shown (either in _Grid_ or _Text_ mode) the **Value** tab is shown by default. In _DBeaver_ 5.0.0 and previous the default was not to show the **Values** tab by default.

If possible I would like to get back the old default of not showing the **Value** tab by default. This for both in _Grid_ and _Text_ mode.

**Comment by serge-rider** [comment]
Not sure we should revert old behavior. 
It's just one click to close it if you don't need it. But it makes much sense for new users to see how results panels look in the fresh installation.

**Comment by pdanie** [comment]
Fair enough. I have the opposite problems with my collegues, that they don't get it that they should close the tab to see more of the grid data. I will add it to my repacking instead.
