### ISSUE TITLE
Query execution failed

### ISSUE THREAD

**Issue by yezhibo** [dbeaver/dbeaver#3954]
hello

my dbeaver have a problem nometter what SQL i excute there is aways a error :

Query execution failed

原因：
 SQL 错误 [1105] [HY000]: line 1 column 53 near " SQL_SELECT_LIMIT=74" (total length 73)

can you give me some advice?

**Comment by yezhibo** [comment]
I test the 4.1.2  works normal, but the 5.1.4 always have the error

**Comment by serge-rider** [comment]
What is you database?
Please post the problem query  text.

**Comment by serge-rider** [comment]
What SQL are you executing? Just a SELECT? OR all queries are failing?
Maybe you should disable "Use SQL to limit fetch size" feature:
![image](https://user-images.githubusercontent.com/6398845/43991136-ba903a16-9d6e-11e8-92e3-2744bb3cadc4.png)

**Comment by yezhibo** [comment]
@serge-rider  all queries are failing. I have try to disable the feature but there still have the error..

**Comment by serge-rider** [comment]
I can't reproduce this (ss I don't have access to TiDB). Maybe the problem is in some recent changes in DBeaver or in the recent TiDB driver.
Could you try some earlier version of DBeaver (https://dbeaver.io/files/) ?

**Comment by serge-rider** [comment]
If some older version will work ok please tell what version exactly. At least we'll know when it broke.

**Comment by yezhibo** [comment]
ok

**Comment by uslss** [comment]
Cannot reproduce on 6.0.2
