### ISSUE TITLE
Oracle Timestamps are shown as Date

### ISSUE THREAD

**Issue by roberto2357** [dbeaver/dbeaver#3956]
Hi,
I'm connected to an Oracle 12c database and:

In DBeaver 5.1.4 a timestamp field is shown (wrongly) as in the following image:
![date](https://user-images.githubusercontent.com/22471800/43902829-5744a80e-9beb-11e8-8a42-617fff383350.png)

Otherwise, in DBeaver 5.1.3 the same field is shown (correctly) as:
![timestamp](https://user-images.githubusercontent.com/22471800/43902897-7c288dde-9beb-11e8-8798-c68ce8f3d3c2.png)

It's a bug of 5.1.4 version?

Thanks ;-)

**Comment by serge-rider** [comment]
It was a feature (#3859) which apparently has side effects.
However I can't reproduce this bug. Could you post some SQL example? Maybe with system tables?
Or at least column definition from DDL tab?

**Comment by roberto2357** [comment]
Ok, you can try this query that read a timestamp from an Oracle system table:

SELECT last_analyzed FROM all_tab_columns

**Comment by serge-rider** [comment]
Thanks. Indeed, it was a bug in 5.1.4.
