### ISSUE TITLE
Postgres json/jsonb column cannot copy & paste NULL values

### ISSUE THREAD

**Issue by LeeKevin** [dbeaver/dbeaver#3958]
When copying from a jsonb column with some null values, if you paste rows back into the same column, NULL values are replaced with non NULL empty values.

Mac 10.11.6, dbeaver 5.1.4 with postgres

**Comment by serge-rider** [comment]
There is no such thing as NULL for a text in the clipboard.
In order to set some column value to null you can use context menu Edit->Set to NULL (you could assign some shortcut to it if you use it frequently).

**Comment by LeeKevin** [comment]
I am able to copy NULLs using the Advanced Copy functionality for other column datatypes. It just doesn't work for Postgres json columns.

**Comment by serge-rider** [comment]
Could you provide a bit more info? I can't realize how you copy/paste NULL values in regular cells. Even with advanced copy. 
Maybe I forgot something, I implemented this feature so long time ago :)

**Comment by LeeKevin** [comment]
I do the following:

1. Select one or multiple NULL cells and Advanced Copy
2. In the copy options window, deselect the checkboxes, and change the value format to "Database native".
3. Click OK
4. Select a cell to paste NULL into. Use Advanced Paste (Shift + Ctrl + V) to paste in the NULL value(s)

**Comment by LeeKevin** [comment]
You suggest using Advanced Copy in your own comment in this issue: https://github.com/dbeaver/dbeaver/issues/1523

**Comment by serge-rider** [comment]
I see. Generally this works only for non-string data types (numbers, dates, etc).
In plain text format (which is also used for clipboard) there is no difference between NULL and empty string.

The only solution would be to use some non-standard clipboard format in addition to plain text (it will be supported only by DBeaver and won't make sense for other applications).
Could you create a feature request for that?

**Comment by adrianog** [comment]
Was a feature request ever created for this?
