### ISSUE TITLE
strange behavior 5.1.4

### ISSUE THREAD

**Issue by hugorn** [dbeaver/dbeaver#3961]
When you press the enter key panels appear on the right side.

Deepin Linux - dbeaver-ce_5.1.4_amd64.deb

After downgrade to 5.1.3 works fine.

![problem](https://user-images.githubusercontent.com/9035153/43957338-e0ad9352-9c7d-11e8-9ae2-ce851b832702.gif)

**Comment by serge-rider** [comment]
Duplicate of #3916
See comments for workaround.
