### ISSUE TITLE
Where do messages go?

### ISSUE THREAD

**Issue by CedricCicada** [dbeaver/dbeaver#3962]
I wrote the following an SQL Editor:

```
do
$$
begin
	raise notice 'I am beginning to do something';
end;
$$
```

There were no errors when I ran this, but I don't see the notice message.  Where do I look for it?

Is this the best forum for simple newbie questions like this?  If not, where should I post them?

I don't see how to flag this as a question, rather than a feature request or bug.  How do I do that?  

Thank you.

**Comment by CedricCicada** [comment]
Thanks very much.  And thanks for adding the tags to my question.  Is that something that I should have done, and if so, how?  And was the question appropriate here, or is there a better place for stupid new user questions like this?

**Comment by serge-rider** [comment]
We checking 100% of new tickets and I usually set tags by myself. 
You did everything right. This is the place to ask questions, report bugs, etc.
