### ISSUE TITLE
Can windows be minimized?

### ISSUE THREAD

**Issue by CedricCicada** [dbeaver/dbeaver#3963]
I came to DBeaver from pgAdmin 3.  In that tool, any window can be minimized, and if a window is selected, that window appears on top of all other windows.  While DBeaver does have the ability to move tabs out of the parent window so that they become their own windows, the new windows cannot be minimized, and they remain on top of the main DBeaver window even when I click on that main window.  Is there some setting I am missing?  If not, could this capability be added to some upcoming version of DBeaver?

Thank you.

**Comment by serge-rider** [comment]
Not sure that I fully got this. But it sounds line detached windows. You can right-click on a tab (editor or view tab) and choose "Detach". Then this view or editor will be in its own window.

**Comment by CedricCicada** [comment]
Thanks for the reply.  That's the same thing as dragging the tab out of the window.  When you drag the tab out of the main window or choose "detatch", you will see that the minimize button in the top right corner is grayed out, and you cannot minimize the detached window.  Also, if you detach a window and it is positioned so that it obscures the main window, and you then click on the main window, the main window will remain underneath the detached window.  You can't use anything on the main window until you drag the detached window out of the way.  That is not the windows are supposed to work.

    On Friday, August 10, 2018, 3:52:21 PM EDT, Serge Rider <notifications@github.com> wrote:  
 
 
Not sure that I fully got this. But it sounds line detached windows. You can right-click on a tab (editor or view tab) and choose "Detach". Then this view or editor will be in its own window.

**Comment by serge-rider** [comment]
Well, this is the default behavior of Eclipse platform, I can't change this (at least with reasonable effort).
I personally never detach view/editors, this just doesn't make sense in this UI.

If you want to see multiple editors/views on a screen you can drag tabs or split editor (from main menu Window). You also can open multiple main windows (from the main menu).

**Comment by CedricCicada** [comment]
Sigh.  
pgAdmin3 behaves that way, and I've come to rely on it.  But with moving to PostgreSQL 10, pgAdmin3 is no longer an option.
Thanks for the explanation.
    On Friday, August 10, 2018, 4:11:29 PM EDT, Serge Rider <notifications@github.com> wrote:  
 
 
Well, this is the default behavior of Eclipse platform, I can't change this (at least with reasonable effort).
I personally never detach view/editors, this just doesn't make sense in this UI.

If you want to see multiple editors/views on a screen you can drag tabs or split editor (from main menu Window). You also can open multiple main windows (from the main menu).
