### ISSUE TITLE
Character to left of cursor (i.e. last typed character) is invisible if there are already characters to the right of the cursor

### ISSUE THREAD

**Issue by iron0012** [dbeaver/dbeaver#3964]
I'm encountering a weird bug (?) in the editor since updating to 5.1.4. When I am editing at a position where there already exists text to the immediate right of the cursor (for example, if I am going back to edit an existing line in the editor), then the character position to the immediate left of the cursor (that is, the most recent character that I have just finished typing) will be invisible as I am typing. When there is no text to the right of the cursor, this bug does not arise.

As you can imagine, this is very disruptive, since one needs to look at this exact character position (to the immediate left of the cursor) in order to see whether one has made a typo or not! In fact, I didn't realize until encountering this bug that this position (the one immediately to the left of the cursor) is where one's eyes and attention are almost always fixed while typing! 

I do use a custom color scheme with a dark background, but I don't think this is the cause of the problem, and I did not encounter this issue using the same theme settings in previous versions of dbeaver.

Thank you!

Mac 10.12.6, dbeaver 5.1.4 with Oracle

**Comment by serge-rider** [comment]
Can't reproduce (or maybe I didn't understand this well), please post a screenshot or video.

**Comment by iron0012** [comment]
Hi, I'm still getting this on 5.1.5. I've tried to make a gif to demonstrate. Watch what happens when I go back to add a schema name before the table name.

![dbeaver_possible_bug](https://user-images.githubusercontent.com/8052991/44162863-39781400-a087-11e8-9702-1781a6ee5bd7.gif)

**Comment by serge-rider** [comment]
This looks like a bug but I still can't reproduce it on my MacOS High Sierra (10.13.4).

- Does this happen in classic theme?
- Could you try to reset workspace (https://github.com/dbeaver/dbeaver/wiki/Reset-workspace) - maybe some UI settings were corrupted?

**Comment by uslss** [comment]
There is no update on the ticket for more than a year.
Ticket is closed.
If the issue is still reproducible for you - feel free to reopen the ticket and add some details that could help to reproduce the issue or create the new one.
