### ISSUE TITLE
CREATE TABLE query had no errors, but the table was not created

### ISSUE THREAD

**Issue by CedricCicada** [dbeaver/dbeaver#3965]
Attempting to create a table in a PostgreSQL v10 database:

```
CREATE TABLE public.x_tables
(
  table_name text
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.x_tables
  OWNER TO postgres;

 select * from public.x_tables;
```
The above query failed in DBeaver, with an error claiming that table x_tables did not exist.  I copied and pasted it into pgAdmin 4, and it worked with no problem.

This is disappointing.  I want a tool that is both easy to use and bug-free for simple users like me.  I'm beginning to think I haven't found it yet.

**Comment by CedricCicada** [comment]
I see where my confusion was.  The top button in the SQL Editor window is for executing a single statement.  The third button is for executing an entire script.  When I clicked the third button, the table was created.

**Comment by serge-rider** [comment]
Yep. So if you use Execute statement (ctrl+enter) and you cursor is on the last query (select) then only select query will be executed.
