### ISSUE TITLE
Can tables in Database Navigator be ordered alphabetically case insensitive?

### ISSUE THREAD

**Issue by GTGeek88** [dbeaver/dbeaver#3967]
Is it possible to have the list of databases in the Database Navigator be ordered alphabetically in a case insensitive manner? I was searching for this and found a request for this feature and a claim it would be in the next release and this was quite a while ago, however I can't find such a feature in the program. Thanks in advance.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/43977920-3754b71a-9cee-11e8-825f-7bba5aed6d05.png)

**Comment by GTGeek88** [comment]
Ah, thank you, kind sir.  It didn't automatically start doing it after activating that feature or even after a refresh, but closing the Navigator window and reopening it did the trick.  I think my next question will be about restoring from Postgres backups, which I've not been able to do (have to open PgAdmin, restore, then go back to using DBeaver).  I've Googled that and, IIRC, DBeaver can't do it, but I might pose a question about that.  Feel free to offer up any advice there, too.  :-)

**Comment by serge-rider** [comment]
DBeaver support backup/restore. But you will need to setup PostgreSQL binaries locally (see native client configuration in connection properties). Then choose Tools->Backup/Restore from the context menu (on a database or a schema or a table).
We going to improve this in 5.1.6 (download binaries automatically).

**Comment by GTGeek88** [comment]
I do have Postgres installed on my development machine. Can I point DBeaver to it somehow or does it need to be installed in a particular place? Also, is any particular version required?

**Comment by GTGeek88** [comment]
Ok thanks.  I just got back to this and I see that the connection settings already point to where Postgres is installed:  C:\PROGRAM FILES\POSTGRESQL\9.6.  So it's not pointing at the BIN folder within that folder.  Should it or does DBeaver figure that part out?  Just for reference the backups are done by PgDump.

A total aside . . . how do you pronounce DBeaver. Like Dee-Beaver or like I prefer "Da-Beaver" (as in "Ward, you were a little rough on Da-Beaver last night" or "Da-Bears!" from an SNL skit). :-)

**Comment by serge-rider** [comment]
@GTGeek88 it is not always possible to detect local PostgreSQL (it depends on PG installer, Windows registry should contain `SOFTWARE\PostgreSQL\Installations` entries).
In any case we implemented automatic client binaries download in #3778 . This should resolve most of problems.

Canonical pronounce is "Dee-Beaver". But most of people call it just "beaver" :)
