### ISSUE TITLE
[ER Diagrams] Custom Diagrams get closed after renaiming

### ISSUE THREAD

**Issue by alexsh2** [dbeaver/dbeaver#3969]
DBeaver - **Version 5.1.5 EE**
OS - **Windows 10**

**Steps to reproduce:**
1. Open any custom diagram
2. Rename it

**Expected result:**
1. Selected custom diagram is renamed
2. The diagram remains open

**Actual result:**
The diagram is closed after renaiming

**Comment by serge-rider** [comment]
Thanks for bug report
