### ISSUE TITLE
Join hints

### ISSUE THREAD

**Issue by carlosjourdan** [dbeaver/dbeaver#397]
Hello all,

Most of my experience in SQL is based on MSSQL, but recently I have been migrating to other databases, and DBeaver seams a pretty strong candidate to replace the role of SQL Server Management Studio.

There is, however, one feature that I'm missing a lot from a plug-in that I had for SSMS: join hints. The basic idea is to use foreign key constraints in the database to improve on the quality of the code autocomplete in two ways:

1) When the user presses ctrl+space after a JOIN, the list of tables that have a PK/FK relationship with the current table are displayed on top

2) When the user presses ctrl+space after a ON corresponding to a join between a PK/FK pair, the first autocomplete option is to insert a snippet in the form PK = FK.

Is this something that is already present in DBeaver?

Regards
Carlos Jourdan

PS: I'm also new to github. How do I mark this a feature request?

**Comment by williamokano** [comment]
I came here to ask for this feature too hahaha

:+1:

**Comment by williamokano** [comment]
Oh darn, I have already asked for it, my bad, potting too much :P

**Comment by serge-rider** [comment]
To support this feature as it should be we need a real semantic SQL parser.
This feature is planned after 3.8 release.

**Comment by serge-rider** [comment]
This is a really good FR and I'd wish to add it in next release.
But it requires some refactoring of SQL editor model (and that's why it is still not implemented). Hopefully I'll eventually find time for it till 4.2 release.

**Comment by serge-rider** [comment]
This is epic ticket. It loves to travel from milestone to milestone. 
Anyhow I'm quite sure it won't be fixed till 4.3. So moving to 4.3.1.

**Comment by williamokano** [comment]
Hahahaa, I kind like to see how happy you can be while developing, kind of
inspiring hahaha.

Forget the bad English

Em 29 de out de 2017 2:40 PM, "Serge Rider" <notifications@github.com>
escreveu:

**Comment by serge-rider** [comment]
Now when we have JOIN generation function for #2850 we can reuse it in this FR.

**Comment by serge-rider** [comment]
Simple joins support will be added in 4.3.5.
It will show tables which can be joined (by FK) with main table.
And it will generate join condition after `JOIN ON` clause.

Limitation: only join with main table supported. Main table is the first table in FROM clause.
