### ISSUE TITLE
Display scaling issues after update from 5.1.4 to 5.1.5

### ISSUE THREAD

**Issue by dmlogic** [dbeaver/dbeaver#3975]
I'm running Fedora 28, Gnome with Wayland.
Hardware is hi-dpi XPS 13 plugged into a medium dpi Dell 27".

The Dell is scaled to 100%, the XPS to 300% when docked. On 5.1.4 this gave a comfortable resolution on each screen. On 5.1.5 the scaling on the Dell is huge making it unusable. The laptop display is comfortable but the app doesn't seem to know the extent of the screen - the app bar is a different size to the app itself.

Uninstalling and reverting to 5.1.4 make everything happy again.

(ps - great app, thank you!)

**Comment by serge-rider** [comment]
Most likely it is the same issue as #3937
It is a bug in new Eclipse platform. Fix will be included after 4.8.1 release (this September).
Thanks for bug report anyway.

**Comment by dmlogic** [comment]
> Most likely it is the same issue as 3937

Possibly. Excuse my ignorance - I don't use the Eclipse IDE, is it used internally by DBeaver?

I notice the other bug report mentions the problem visible in 5.1.4. That version is happy for me. Let me know if I can provide any other useful info.

**Comment by serge-rider** [comment]
Yes, DBeaver is based on Eclipse UI platform. It is not the same as various Eclipse IDEs (they are also based on Eclipse platform).
Unfortunately we can't fix this bug directly in DBeaver.

**Comment by dmlogic** [comment]
I also have the same "over scaled" display in Fedora/Gnome (exact setup as per 1st comment). Problem started in 5.24 and continued in 5.25. I've gone back to 5.23 which is fine.

**Comment by jonaskello** [comment]
I have the same problem on my macbook retina.... before the scaling was good, now it is very small.

**Comment by serge-rider** [comment]
We'll switch to Eclipse Oxygen (base platform) for 5.3. Perhaps it will resolve UI issues on GTK.
Please check

**Comment by dmlogic** [comment]
display still poor in 5.3 for me with Fedora 29

**Comment by serge-rider** [comment]
Could you try to run DBeaver with parameter `--launcher.GTK_version 2` ?

**Comment by HymanZHAN** [comment]
I am on Ubuntu 18.10 (15.6inch 4k display) and I had the same issue as problem #3937. I tried with `--launcher.GTK_version 2` parameter and that specific problem #3937 went away, but there are some other issues:
  - Very tiny `+` icon to the left of the icon in Database Navigator
  - Incorrect rendering of the ribbon bar (I think?) The letter "P" next to the Postgres icon does not look right to me. Also to the Transaction log icon has a white beam to its left.

![screenshot from 2018-12-13 10-32-28](https://user-images.githubusercontent.com/26806995/49948931-7089f500-fec2-11e8-80d5-4aaf76d03aef.png)

**Comment by serge-rider** [comment]
Problem with broken database selector is tracked in #4553.   

Problem with broken editor controls should be resolved by now.
