### ISSUE TITLE
Very slow select queries

### ISSUE THREAD

**Issue by pszucs** [dbeaver/dbeaver#3976]
Running a 'SELECT' query on some of my tables is extremely slow (since v5.1). By that I mean for instance a table with 150 rows returns the result set in about 30 seconds. It seems that it only happens on tables that have at least one 'datetime' field. However, there's no problem with newly created tables.

The Error Log shows a lot of errors - at least one per table row - such as these:

> Can't read column 'Invigilator_date' value
> SQL Error [S1009]: Value '5113030005

I don't experience this problem with other db softwares (Workbench, Adminer).

Has anyone experienced this?

MySQL versions: 5.6 and 5.7
DBeaver version: 5.1.5

[Error Log Screenshot](https://imageupload.co.uk/image/4qJL)

**Comment by serge-rider** [comment]
Seems to be the same as #3903.
This is becase of mess with different Oracle drivers  and different drivers configuration for MySQL 5 and 8.
Please try to set zeroDateTimeBehvior driver property to `convertToNull`.
We'll fix default configuration if it will help.

![image](https://user-images.githubusercontent.com/6398845/44024368-c53fed84-9ef5-11e8-9f07-d442f16897a0.png)

**Comment by serge-rider** [comment]
Since 5.1.6 we'll set proper driver settings in the default configuration
