### ISSUE TITLE
CSV import to Impala DB

### ISSUE THREAD

**Issue by sudila** [dbeaver/dbeaver#3978]
Hi,
great feature, waiting for it for a long time, unfortunately, it doesn't work for me.
I`m using Impala DB with JDBC. please see print screens below:
![image](https://user-images.githubusercontent.com/29042801/44023436-fba455de-9ef2-11e8-842d-8129ccc49032.png)
![image](https://user-images.githubusercontent.com/29042801/44023473-1c5761cc-9ef3-11e8-895d-7d0eba8740cc.png)
![image](https://user-images.githubusercontent.com/29042801/44023497-2c8ae302-9ef3-11e8-8e80-860c03c95915.png)

Thanks

**Comment by serge-rider** [comment]
Could you try to set driver parameter 'Omit single catalog' on? And reconnect.
Is is on driver editor dialog, which is accessible from connection properties page.
![image](https://user-images.githubusercontent.com/6398845/44024966-6f51e114-9ef7-11e8-8499-09306c2d9eba.png)

**Comment by sudila** [comment]
same result:

![image](https://user-images.githubusercontent.com/29042801/44025672-677529ae-9ef9-11e8-8de1-f3e509a968a4.png)


![image](https://user-images.githubusercontent.com/29042801/44025630-4d5c3cd8-9ef9-11e8-8282-b4da022320b4.png)

**Comment by serge-rider** [comment]
Unfortunately can't test this on Impala at the moment. But it works ok on Hive.
I think the problem happens because of fully-qualified table name which includes both catalog (Impala) and schema name.
What about enabling 'Omit catalogs' option?

**Comment by sudila** [comment]
I`ll have to check with DBA

**Comment by serge-rider** [comment]
I mean enable option "Omit catalogs" in driver settings.

**Comment by sudila** [comment]
Worked!!! thanks
