### ISSUE TITLE
Appearance issues on Linux

### ISSUE THREAD

**Issue by pszucs** [dbeaver/dbeaver#3980]
I'm having issues with the recently introduced layout (not sure which version). I've tried changing the theme and disabling it completely, no luck.

For instance, the 'Preferences' window has a transparent outer frame around it (it moves with the smaller window when dragging it with the mouse).

[Preferences window](https://imageupload.co.uk/image/4qQr)

When maximizing the smaller window the buttons (Apply, etc) are not always visible - you can only see the very top of the buttons.

[Edit connection - Driver properties: three buttons at the bottom right corner](https://imageupload.co.uk/image/4qQJ)

Operating system: Elementary OS (Ubuntu derivative, Pantheon desktop environment built on top of GNOME)

**Comment by serge-rider** [comment]
Perhaps this was triggered by migration on Eclipse 4.8 in DBeaver 5.1.4. 
You could try 5.1.3 as a workaround.
Also you could try to add lines
```
--launcher.GTK_version
2
```
in dbeaver.ini file (in the beginning).

**Comment by pszucs** [comment]
Perfect, thanks a lot.

**Comment by ruuda** [comment]
I am experiencing a similar issue, after upgrading from 5.1.4 to 5.1.5, the UI no longer respects the system theme colors, and uses shades of grey that don't occur in my system theme. This makes most of the UI and especially dialogs look foreign and broken, see the example below. Note the light rectangles around buttons (the color of these rectangles is the color of the system theme, the darker grey of the dialog should not be there).

![funky-theme](https://user-images.githubusercontent.com/506953/44035869-c575cee8-9f10-11e8-8d7e-47d2a50aed1a.png)

I am using Gnome on Ubuntu 18.04 with Arc-theme.

**Comment by hkcoyant** [comment]
Same problem in elementary OS 0.4.1 Loki, can't set preferences, i stay tuned, if can assist about any environment question
![screenshot from 2018-08-15 13 20 17](https://user-images.githubusercontent.com/6413893/44159693-95926680-a08e-11e8-86fa-b754bf951d85.png)

**Comment by serge-rider** [comment]
@ruuda @hkcoyant Did you try to switch to GTK2? (https://github.com/dbeaver/dbeaver/issues/3980#issuecomment-412480884)

**Comment by ruuda** [comment]
Yes, running with `--launcher.GTK_version 2` solved all issues for me.

**Comment by serge-rider** [comment]
In 5.1.6 we reverted to Eclipse 4.7 and GTK2. 
Most of UI issues on Linux should be resolved.

**Comment by lmicra** [comment]
I noticed something in the log:

***WARNING: Detected: GTK_IM_MODULE=xim. This input method is unsupported and can cause graphical issues.
***WARNING: Unset GTK_IM_MODULE or set GTK_IM_MODULE=ibus if flicking is experienced. 

Running dbeaver with this env setting fixed my UI issues:

> GTK_IM_MODULE=ibus /usr/share/dbeaver/dbeaver

**Comment by jimuelpalaca** [comment]
Hi @serge-rider ,

The latest version of dbeaver launcher no longer support running on gtk version 2

`The Dbeaver executable launcher no longer supports running with GTK + 2.x. Continuing using GTK+ 3.x.`

that makes the (--launcher.GTK_version 2) fix useless.

**Comment by jimuelpalaca** [comment]
@lmicra ,

Great! Your workaround works, but we can't consider this as fix. I suggest to reopen the issue.

**Comment by rmainseas** [comment]
@lmicra thank you so much for this! I've been pulling my hair out over the issues in #6913 and your command appears to have solved it.
