### ISSUE TITLE
Issue on showing Vertica tables in Database Navigator

### ISSUE THREAD

**Issue by vkpavan31** [dbeaver/dbeaver#3981]
On connecting to Vertica DB(Server version 8.0) using client(Vertica JDBC 8.0.4) DBeaver takes very long time in populating the tables in a selected schema.

DBeaver stays in Load items....: Load TableCache. This stays for approx 5-10 mins and then loads the tables.

**Comment by serge-rider** [comment]
How many tables there are in the database?

You could check what actual SQL is executed by DBeaver during table load in Query Manager view (first enable `Metadata read` queries in Query Manager filter settings)

**Comment by vkpavan31** [comment]
Hi Serge,

The Database has approx 200 tables. For some reason table population is fast while using DBeaver 4.3.5.

I checked in Query Manager View. Following is my observation

DBeaver 5.1.5 

Query Manager View
Text
SELECT tv.*,c.comment as REMARKS FROM (
SELECT NULL as TABLE_CAT, t.table_schema as TABLE_SCHEM, t.table_name as TABLE_NAME, (CASE t.is_flextable WHEN true THEN 'FLEXTABLE' ELSE 'TABLE' END) as TABLE_TYPE, NULL as TYPE_CAT,
	t.owner_name, t.table_definition as DEFINITION 
FROM v_catalog.tables t
UNION ALL
SELECT NULL as TABLE_CAT, v.table_schema as TABLE_SCHEM, v.table_name as TABLE_NAME, 'VIEW' as TABLE_TYPE, NULL as TYPE_CAT,
	v.owner_name, v.view_definition as DEFINITION 
FROM v_catalog.views v) tv
LEFT OUTER JOIN v_catalog.comments c ON c.object_type = tv.TABLE_TYPE AND c.object_schema = tv.table_schem AND c.object_name = tv.table_name 
WHERE tv.table_schem='My_DB'
ORDER BY 2, 3

Duration 
744101 ms.

DBeaver 4.3.5

Query Manager View
Text
-- Load tables [null, My_DB, %, null] 
 Duration 
15 ms

**Comment by serge-rider** [comment]
Yeah, most liekly it is becaue of flex tables loading (4.3.5 didn't load them at all).
Could you try to remove first part of this query and run it again:
```sql
SELECT NULL as TABLE_CAT, v.table_schema as TABLE_SCHEM, v.table_name as TABLE_NAME, 'VIEW' as TABLE_TYPE, NULL as TYPE_CAT,
v.owner_name, v.view_definition as DEFINITION
FROM v_catalog.views v) tv
LEFT OUTER JOIN v_catalog.comments c ON c.object_type = tv.TABLE_TYPE AND c.object_schema = tv.table_schem AND c.object_name = tv.table_name
WHERE tv.table_schem='My_DB'
ORDER BY 2, 3
```
Perhaps we should load flex tables separately.

**Comment by vkpavan31** [comment]
Hi Serge,

Removing flex tables works!!!. It took approx 10-15 secs. Way better than current but slower than 4.3.5 way of populating tables.

Thanks again for looking into this!!

**Comment by serge-rider** [comment]
Could you check the fix in EA version (https://dbeaver.io/files/ea)

**Comment by MM026184** [comment]
Fix in EA version works well. Table metadata reads now taking <10s Thank you!

**Comment by vkpavan31** [comment]
Yes the Table Metadata reads taking less than 10 secs for me too. Thank you!!!

**Comment by serge-rider** [comment]
Thanks for testing
