### ISSUE TITLE
Oracle Bug in the new Version (5.1.5.2) can't update rows: ORA-00911

### ISSUE THREAD

**Issue by progsurfer** [dbeaver/dbeaver#3982]
Hi,

in the last version I'm getting the ORA-00911 (invalid charachter) when i try to update the row.

It doesn't matter either by SQL-statement or DataView-Grid.

Please fix it asap.

Thank you.

Denis

![grafik](https://user-images.githubusercontent.com/24592280/44029638-4bb5679c-9efe-11e8-9f57-172adbae9050.png)

**Comment by anophelesgreyhoe** [comment]
I have the same issue. I can't e.g. set a column's value to NULL without seeing ORA-00911: invalid character when I try to save.

**Comment by p91paul** [comment]
what time did you download dbeaver 5.1.5? a new version was released around 9 AM UTC (11 AM CEST) yesterday with the fix for this!

**Comment by serge-rider** [comment]
This bug was fixed in #3973.
New 5.1.5 release was republished (just redownload it)
