### ISSUE TITLE
Result set area selection problem since 5.1.5

### ISSUE THREAD

**Issue by alesc2000** [dbeaver/dbeaver#3983]
Since I updated to version 5.1.5 I have a problem when selecting an area of cells in the result set using only the mouse. Sometimes only the first cell gets selected, and sometimes if I only select cells from one column, the last cell doesn't get selected.

If I use Ctrl+click or Shift+click, it works as expected.

OS: Ubuntu 18.04
DBeaver: 5.1.5.
DB: Postgres

**Comment by ruuda** [comment]
I am experiencing a similar problem after upgrading from 5.1.4 to 5.1.5, where if I click in a cell, the cell briefly turns into a text box where I can select text, but then it immediately turns into a normal cell again, without the ability to drag-select text. I believe this did work properly before.

Perhaps #3980  is related?

**Comment by serge-rider** [comment]
Can't reproduce this. But we already know that recent migration to Eclipse 4.8 created a lot of different issues o different Linuxes. Unfortunately we can't just revert this migration.

Another change in 5.1.5 is migration to GTK3. Could you try to add
```
--launcher.GTK_version
2
```
in the beginning of dbeaver.ini?

**Comment by ruuda** [comment]
Starting DBeaver with `--launcher.GTK_version 2` on the command line resolves all UI issues for me, this one as well as https://github.com/dbeaver/dbeaver/issues/3980#issuecomment-412525318. I will use that as a workaround for now, thanks!

**Comment by serge-rider** [comment]
Great. At least we now have a workaround.
Thanks for the info

**Comment by alesc2000** [comment]
Yes, it solved my problem also.
Thanks
