### ISSUE TITLE
Problem at creating foreign key in MySQL

### ISSUE THREAD

**Issue by guibragamonte** [dbeaver/dbeaver#3984]
### Problem

After update to version 5.1.5, when i click to add new foreign key, nothing returns.

### Terminal response

![llight](https://user-images.githubusercontent.com/30661999/44029776-de9e9eb8-9ed4-11e8-96ac-0bd06a6f1d47.png)

**Comment by tibtiiiiib** [comment]
Same problem with a PostgreSQL database after the update.
Thank you for your help

**Comment by harrisyn** [comment]
same here

**Comment by serge-rider** [comment]
Fixed in #3998
Thanks for the bug report

**Comment by serge-rider** [comment]
You can check fixes in EA version (https://dbeaver.io/files/ea)
