### ISSUE TITLE
[W10 x64][5.1.5][UI] Hot key not working in details part of error window

### ISSUE THREAD

**Issue by infectormp** [dbeaver/dbeaver#3985]
CTRL-C not working in details part of error window.

![image](https://user-images.githubusercontent.com/9958813/44029980-048a22e0-9f08-11e8-89e0-5ccf1277c789.png)

**Comment by serge-rider** [comment]
It is not a bug, it never worked there. This is a standard Eclipse error dialog and it is quite hard to change its behavior.

Workaround: right click and choose Copy to copy contents of details pane.
