### ISSUE TITLE
[5.1.5][UI] Language selector location and other UI suggestions

### ISSUE THREAD

**Issue by infectormp** [dbeaver/dbeaver#3988]
I lose some time to find where is language selector is placed and after a while i left my attempts. Then i found it by accident at Window-Preferences-Database (tab). 
![image](https://user-images.githubusercontent.com/9958813/44030507-aa44b5fa-9f09-11e8-8bf4-93b7ac62a92a.png)

After looking to Window-Preferences i have a some UI suggestions:

1. Swap General and Database tabs. It more logical when 1st tab is General.
2. Move language selector to General-Appearance tab or to General. 
3. Place all notification settings to General-Notifications tab.
4. Automatic update check move to General.

**Comment by uslss** [comment]
obsolete.
Preferences page was reworked.
