### ISSUE TITLE
PostgreSQL - Can't create serial column

### ISSUE THREAD

**Issue by tibtiiiiib** [dbeaver/dbeaver#3989]
Hello,

After upgrade to version 5.1.5 this morning, I can't create column of type serial.

I was able to do it last week on the same database.

Thank you for your help

![image](https://user-images.githubusercontent.com/17174715/44034606-cdaae218-9f0d-11e8-8949-2aade91f14a1.png)

**Comment by serge-rider** [comment]
I can't reproduce this (I can add column of type serial in the existing table).
Are you creating a new table or modifying an existing one?
At which moment this error happens? 

Maybe some short vide/gif could help.

**Comment by tibtiiiiib** [comment]
I had not tried since last week but I can't reproduce either. I think we can say it's ok ! 
Very sorry about this.
If it happens again, I will be back with a short video.

Thank you for help
