### ISSUE TITLE
Question: SQL Server "SQL Completion" how to hide database name?

### ISSUE THREAD

**Issue by nealrout** [dbeaver/dbeaver#3991]
I am using DBeaverEE 5.1.0, and when connecting to Microsoft SQL Server 2016 databases the IntelliSense will show the databases name, which I would like to suppress.  The database names in our environments are long and it makes the feature very difficult to use.

If there is currently no way to do this, is there a way I can default a wider window when the autocomplete comes up? 

Example of results showing database name for "master" database when I specifically only specified schema in the query:

![image](https://user-images.githubusercontent.com/21213885/44038002-c7470138-9ee3-11e8-981c-9e2bc033541a.png)

I have made sure "Use short object names" is selected, and it doesn't seem to help:

![image](https://user-images.githubusercontent.com/21213885/44038106-fbe62054-9ee3-11e8-81b9-0119ea3fff66.png)

**Comment by serge-rider** [comment]
Unfortunately there is no such option at the moment.
I think we could suppress catalog name in FQ names by default.

Mark as FR.

**Comment by serge-rider** [comment]
Completion will be improved in 5.1.6.
This particular issue will be also fixed.

**Comment by nealrout** [comment]
I installed 5.2.0 and this looks great.  Thank you so much for turning
these around so quickly.
