### ISSUE TITLE
create table only with name "NewTable"

### ISSUE THREAD

**Issue by bitkorn** [dbeaver/dbeaver#3994]
Since the last update (DBeaver version 5.1.5.201808122132) I can only create new tables with the name "NewTable". It is not possible to change the table name.

Today came this update for the Eclipse plugin. Now there is the same problem.

Xubuntu 16.04 with Oracle Java 1.8.0_171

**Comment by bitkorn** [comment]
If you create new columns, you can also not change the data type.

**Comment by bitkorn** [comment]
I see the problem now. You can only see changes after pressing Return or the focus of the mouse changes. Before the DBeaver update, the changes were seen live during editing as in other inline edit fields.
[youtube](https://youtu.be/Z-MAKFBX0r8)

**Comment by serge-rider** [comment]
I partially reproduced this. Could you try EA version (https://dbeaver.io/files/ea/) - a bug with new objects creatio nwas fixed there.

**Comment by serge-rider** [comment]
Weird. This seems to be OS-specific issue.
Could you try to switch to GTK2 (see comments in #3980)?

**Comment by bitkorn** [comment]
Running with `--launcher.GTK_version 2` solved not my problems

**Comment by serge-rider** [comment]
Could you post error/debug log? 
If there are any errors/warnings.
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by bitkorn** [comment]
2018-08-19 10:10:01.713 - DBeaver 5.1.5.201808122132 is starting
2018-08-19 10:10:01.717 - OS: Linux 4.4.0-133-generic (amd64)
2018-08-19 10:10:01.720 - Java version: 1.8.0_181 by Oracle Corporation (64bit)
2018-08-19 10:10:01.723 - Install path: '/usr/share/dbeaver'
2018-08-19 10:10:01.725 - Instance path: 'file:/home/allapow/.dbeaver4/'
2018-08-19 10:10:01.728 - Memory available 109Mb/910Mb
2018-08-19 10:10:01.744 - Starting RMI server at 20079
2018-08-19 10:10:01.792 - Run workbench
2018-08-19 10:10:04.814 - Initializing DBeaver 5.1.5.201808122132
2018-08-19 10:10:04.815 - Host plugin: org.jkiss.dbeaver.core.application 5.1.5.201808122132
2018-08-19 10:10:04.816 - Initialize Core...
Warning: NLS unused message: model_jdbc_None in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_Procedure in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_Schema in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_Serializable in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc__rows_fetched in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_array_result_set in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_cant_create_null_cursor in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_column_size in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_could_not_load_content in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_could_not_load_content_from_file in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_create_new_constraint in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_create_new_foreign_key in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_create_new_index in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_create_new_object in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_create_new_table in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_create_new_table_column in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_delete_object in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_drop_constraint in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_drop_foreign_key in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_drop_index in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_drop_table in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_drop_table_column in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_exception_bad_savepoint_object in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_exception_could_not_bind_statement_parameter in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_exception_could_not_close_connection in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_exception_could_not_get_result_set_value in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_exception_internal_jdbc_driver_error in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_exception_invalid_transaction_isolation_parameter in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_exception_unsupported_array_type_ in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_exception_unsupported_value_type_ in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_fetch_table_data in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_fetch_table_row_count in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_find_best_row_identifier in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_find_objects_by_name in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_find_version_columns in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_jdbc_error in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_catalogs in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_client_info in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_column_privileges in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_columns in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_cross_reference in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_exported_keys in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_function_columns in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_functions in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_imported_keys in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_indexes in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_primary_keys in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_procedure_columns in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_procedures in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_schemas in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_super_tables in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_super_types in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_table_privileges in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_table_types in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_tables in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_type_info in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_udt_attributes in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_load_udts in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_lob_and_binary_data_cant_be_edited_inline in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_max_length in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_precision in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_read_committed in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_read_uncommitted in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_rename_object in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_repeatable_read in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_scale in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_type_name in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_unknown in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_unsupported_column_type_ in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: model_jdbc_unsupported_value_type_ in: org.jkiss.dbeaver.core.CoreResources
2018-08-19 10:10:05.102 - Datasource provider 'wmi' not found. Bad provider description.
2018-08-19 10:10:05.137 - Core initialized (321ms)
2018-08-19 10:10:05.138 - Configure workbench window
2018-08-19 10:10:05.352 - Create actions
2018-08-19 10:10:05.354 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2018-08-19 10:10:05.355 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
Warning: NLS unused message: IDEApplication_workspaceInUse_Cancel in: org.eclipse.ui.internal.ide.messages
2018-08-19 10:10:06.185 - Initialize workbench window
2018-08-19 10:10:06.186 - Error parsing command line: Unrecognized option: --launcher.GTK_version 2
2018-08-19 10:10:06.205 - Finish initialization
2018-08-19 10:10:06.547 - Connect with 'MySQL - localhost' (mysql5-1620a77c188-5dbd70f65b6d2829)
2018-08-19 10:10:07.473 - Connected (mysql5-1620a77c188-5dbd70f65b6d2829, MySQL Connector Java [mysql-connector-java-5.1.39 ( Revision: 3289a357af6d09ecc1a10fd3c26e95183e5790ad )])

**Comment by serge-rider** [comment]
```
Error parsing command line: Unrecognized option: --launcher.GTK_version 2
```
These are two separate parameters (should be on separate lines in dbeaver.ini)

**Comment by serge-rider** [comment]
Good.
Unfortunately at the moment it is the only workaround for Xubuntu and Mint.
