### ISSUE TITLE
SSH password not remembered

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#3995]
This is a continuation of bug #3917. In DBeaver 5.1.5 support of support keyboard-interactive method was added for JSch but the problem is that DBeaver asks me for the SSH password every time I connect even if the password is saved in connection settings under Network > SSH Tunnel. The saved password seems to be ignored. This worked well with SSHJ plugin but it doesn't with JSch.

**Comment by serge-rider** [comment]
In fact it is a feature, not a bug. 
Keyboard-interactive method doesn't use saved passwords. Although it is a contraversion feature.
It is more secure but less convenient. I can make it use password but initially I am not supposed to.

**Comment by lemon-juice** [comment]
Why is this a feature? When there is a field in the settings for remembering password then why would it be ignored? It is true that it's always most secure to type the password every time but shouldn't the choice be left to the user? I can always clear the saved password if I need more security.

The saved password is used without problems by the SSHJ plugin (which I can't use right now because of #3996).

**Comment by serge-rider** [comment]
In 5.1.5 we use default Eclipse implementation for keyboard interactive. It doesn't even try to read saved password, internally it is more sophisticated than plain password. I could hack it though.

**Comment by lemon-juice** [comment]
I see, it is then a question of some internal complications. From a user's perspective this looks like a bug - a password is saved but it's weird if it is not used. At best the password field in settings should be greyed out or hidden then. Of course, the best option would be to hack it to work.

**Comment by serge-rider** [comment]
Done
