### ISSUE TITLE
Cant install office integration

### ISSUE THREAD

**Issue by Ozonrus** [dbeaver/dbeaver#3997]
Got DB CE version  5.1.5.201808130751

Can't install office integration (via Install new software)

Last step:

An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
Error reading signed content.
Exception in opening zip file: C:\Program Files (x86)\DBeaver\plugins\org.jkiss.bundle.apache.poi_3.16.0

**Comment by serge-rider** [comment]
Can't reproduce.
- Make sure you are running DBeaver with admin permissions
- Make sure you are running the most recent version of DBeaver

**Comment by rambosir** [comment]
I have the same problem.

Dbeaver version:5.1.5.201808130751 CE

**Comment by Ozonrus** [comment]
Fixed issue by uninstalling DB CE and installing back fresh one, without removing user settings

**Comment by INGCRENGIFO** [comment]
I have the same problem.

An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
Error reading signed content.
Exception in opening zip file: C:\Users\crengifo\AppData\Local\DBeaver\plugins\org.jkiss.bundle.apache.poi_3.16.0

![imagen](https://user-images.githubusercontent.com/12200313/44211600-f7a2a880-a12e-11e8-97ec-550d008a876c.png)

**Comment by serge-rider** [comment]
@INGCRENGIFO did you try to reinstall DBeaver?
The real problem is that sometimes extension installer fails (because of long data file, like in case of POI). At the moment there is no other way to fix this but to reinstall whole application :(

**Comment by gitsno** [comment]
I have had the same issue but I now successfully install the extension every time there is a DBeaver upgrade, the workaround is:

- Delete or rename artifacts.xml in the DBeaver installation folder (C:\Program Files\DBeaver in 64bit Windows) _before_ you open DBeaver
- Run DBeaver as Administrator as Serge previously pointed out

**Comment by serge-rider** [comment]
@gitsno Thanks for the information. 
artifacts.xml seems to be the reason of many problems with Eclipse P2..

**Comment by serge-rider** [comment]
We'll remove artifacts.xml cache in the next DBeaver version. Somehow it causes problems with P2 install procedure.

**Comment by gitsno** [comment]
I just installed DBeaver 5.2.0 and the Office integration still didn't install unless I first deleted artifacts.xml. When the installation fails the artifacts.xml file does get updated so I don't think it's an access problem, but after the failure there are elements in the file for the old and the new versions of the plugin, I don't know if that's a clue to the problem?
So in the artifacts.xml file after it failed there was:
`  <artifacts size='5'>
    <artifact classifier='osgi.bundle' id='org.jkiss.dbeaver.data.office' version='1.1.29.201809092115'>
      <properties size='1'>
        <property name='download.size' value='26960'/>
      </properties>
    </artifact>
    <artifact classifier='osgi.bundle' id='org.jkiss.bundle.apache.poi' version='3.16.0'>
      <properties size='1'>
        <property name='download.size' value='11680587'/>
      </properties>
      <repositoryProperties size='1'>
        <property name='artifact.folder' value='true'/>
      </repositoryProperties>
    </artifact>
    <artifact classifier='org.eclipse.update.feature' id='org.jkiss.dbeaver.ext.office.feature' version='1.1.28.201808262133'>
      <properties size='1'>
        <property name='download.size' value='9251'/>
      </properties>
      <repositoryProperties size='1'>
        <property name='artifact.folder' value='true'/>
      </repositoryProperties>
    </artifact>
    <artifact classifier='osgi.bundle' id='org.jkiss.dbeaver.data.office' version='1.1.28.201808262133'>
      <properties size='1'>
        <property name='download.size' value='26722'/>
      </properties>
    </artifact>
    <artifact classifier='org.eclipse.update.feature' id='org.jkiss.dbeaver.ext.office.feature' version='1.1.29.201809092115'>
      <properties size='1'>
        <property name='download.size' value='9246'/>
      </properties>
      <repositoryProperties size='1'>
        <property name='artifact.folder' value='true'/>
      </repositoryProperties>
    </artifact>
  </artifacts>
`
but if I delete the artifacts.xml file before installing the extension then the install succeeds and I have this in the file:
`  <artifacts size='3'>
    <artifact classifier='osgi.bundle' id='org.jkiss.dbeaver.data.office' version='1.1.29.201809092115'>
      <properties size='1'>
        <property name='download.size' value='26960'/>
      </properties>
    </artifact>
    <artifact classifier='osgi.bundle' id='org.jkiss.bundle.apache.poi' version='3.16.0'>
      <properties size='1'>
        <property name='download.size' value='11680587'/>
      </properties>
      <repositoryProperties size='1'>
        <property name='artifact.folder' value='true'/>
      </repositoryProperties>
    </artifact>
    <artifact classifier='org.eclipse.update.feature' id='org.jkiss.dbeaver.ext.office.feature' version='1.1.29.201809092115'>
      <properties size='1'>
        <property name='download.size' value='9246'/>
      </properties>
      <repositoryProperties size='1'>
        <property name='artifact.folder' value='true'/>
      </repositoryProperties>
    </artifact>
  </artifacts>
`

**Comment by gitsno** [comment]
I have just installed DBeaver 5.2.1 CE and when installed the Office Extensions there was no problem and there is no artifacts.xml file at all :-)
