### ISSUE TITLE
Windows Defender Flaging V5.15 As Threat

### ISSUE THREAD

**Issue by mcarpenterjr** [dbeaver/dbeaver#3999]
What's the protocol here? Been using DBeaver for some time haven't seen this before. Windows defender is flagging V5.1.5 as a threat citing it contains a Trojan. False positive?

**Comment by Kaliumhexacyanoferrat** [comment]
Same for me. Will uninstall for now.

![image](https://user-images.githubusercontent.com/4992119/44136465-30010978-a06d-11e8-8311-af32239768ed.png)

**Comment by serge-rider** [comment]
We'll submit false-positive request, thanks for info.

**Comment by serge-rider** [comment]
BTW, Virus Total report:
https://www.virustotal.com/#/url/2f3530d67427570b403059fc30637f34cb9dfbb1311db83a314945771968b32d/detection

**Comment by mcarpenterjr** [comment]
Yes, I am downloading from dbeaver.io.
Yes, I do have a non-standard security policy in place but I have an administrator account that overrides the policies.

Thanks for your prompt response, and @Kaliumhexacyanoferrat thanks for attaching that image too.

**Comment by serge-rider** [comment]
Reply from Microsoft:
![image](https://user-images.githubusercontent.com/6398845/44174852-15e7b480-a0ed-11e8-8deb-a19def156398.png)

This makes me a bit frustrated. I'll post all available details to them (thanks for the screenshot) but generally this is a bit odd situation..

**Comment by serge-rider** [comment]
Good, thanks for the info.
