### ISSUE TITLE
mssql - varbinary result looks odd in result

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#4001]
When having a varbinary datatype in sqlserver the result looks different in dbeaver compared to manager on the server itself.

On the server the binary format is more "readable" and in dbeaver it looks more binary and strange.

The default should be IMO to have it more readable like sqlmanager.

**Comment by nmat** [comment]
https://docs.microsoft.com/en-us/sql/t-sql/data-types/binary-and-varbinary-transact-sql?view=sql-server-2017

**Comment by serge-rider** [comment]
You can change binary data representation:
![image](https://user-images.githubusercontent.com/6398845/44303164-3d838a80-a342-11e8-8007-02f7e2cd7314.png)

**Comment by nmat** [comment]
thank you. I will test this.

**Comment by nmat** [comment]
I noticed a difference in checking how hex is presented. the 0x part in the beginning seems be stripped off is this intentional?

**Comment by nmat** [comment]
Thank you! I will close this off then.
