### ISSUE TITLE
[Oracle] 5.1.5 Use ROWID to identify rows Stop Work

### ISSUE THREAD

**Issue by hugorn** [dbeaver/dbeaver#4003]
After upgrade to new releases of Dbeaver the option Use ROWID to identify rows  stop work.
![deepin screenshot_dbeaver_20180815080314](https://user-images.githubusercontent.com/9035153/44145551-65f424e4-a062-11e8-8292-6056c61dd24c.png)
![deepin-screen-recorder_select area_20180815080604](https://user-images.githubusercontent.com/9035153/44145555-6b31b034-a062-11e8-81f4-bbbac18799fe.gif)

**Comment by hugorn** [comment]
Exact Version: 5.1.5.201808130751
Deepin Linux
Oracle Database 11g Release 11.2.0.4.0 - 64bit Production

**Comment by serge-rider** [comment]
DBeaver doesn't support ROWID identifiers for custom SQL queries. 
ROWID works only in direct table editor (open your table by double-click and switch to the Data tab).

**Comment by p91paul** [comment]
I confirm, it still works for tables without a primary key; since behavior is now to use rowid only if primary key is not defined for the table, it expects key fields to be selected instead of rowid (which is a workaround)

**Comment by tati-kru** [comment]
Thank you @p91paul for workaround.
