### ISSUE TITLE
Table not found message when database doesn't exist

### ISSUE THREAD

**Issue by djmartin4** [dbeaver/dbeaver#4004]
When running a query such as "select * from db.table;" when db does not exist results in a table not found message. Is this correct behavior? This is for hive 2.1 and 1.2.

![image](https://user-images.githubusercontent.com/38948480/44166736-2458b080-a09a-11e8-9bfb-e5dd1a0acd25.png)

**Comment by serge-rider** [comment]
This error was produced by Hive driver. I assume this is correct behavior for it.

**Comment by djmartin4** [comment]
Thanks.
