### ISSUE TITLE
[5.1.5] Cannot Create New Foreign Key via Context menu

### ISSUE THREAD

**Issue by MarcoBorchert** [dbeaver/dbeaver#4005]
Nothing happens when selecting "Create New Foreign Key" from the context menu of table Properties/Foreign Keys.
Results are identical on Postgres 9.2.4 and Firebird 2.5.0.
The feature worked some time ago in a previous version.

Creating other constraints works (but editing constraints/foreign keys seems to just open a (non-editable) view; I have not used that feature before though).

**Comment by serge-rider** [comment]
Duplicate of #3984.
The fix is in the EA version.
