### ISSUE TITLE
No tables in database navigator and in Database details

### ISSUE THREAD

**Issue by Almandor** [dbeaver/dbeaver#4007]
When I connect to some of our InnoDB databases the Navigator showns no tables. When I doubleclick the database the details are empty as well.

A simple "show tables" returns a list of the tables though. It does not happen always but when it happens it stays this way until a new version of dBeaver is installed. Then sometimes it works for a while.

![database](https://user-images.githubusercontent.com/19967786/44197464-f5e0e100-a13e-11e8-986a-09362db05915.png)

Version is the current 5.1.5.201808130751

**Comment by serge-rider** [comment]
I see that you have a filter for tables (three dots after Tables means filtering).
Maybe all of your tables were filtered? Could you try to disable filter? (context menu on Tables->Filter->Configure "Tables" filter)

**Comment by Almandor** [comment]
@serge-rider Thank you. I have not set the filter knowingly. In fact I did not know it is possible to filter the tables and keep the settings between sessions.
