### ISSUE TITLE
Add column name searching/filtering/sorting in Custom Filters

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#4011]
I often work with very wide tables and searching/filtering/sorting by column name in _Custom Filters_ (_funnel_ icon above table data) would be nice feature.

By filtering and sorting I don't mean SQL features, but GUI features to make selecting and ordering columns easier.

**Comment by serge-rider** [comment]
Good point. 
Also we need some convenient way to find columns right in results view as well. Currently it is possible only win record mode+columns ordering.

**Comment by maln0ir** [comment]
> we need some convenient way to find columns right in results view as well.

You might implement filtering columns in _Record_ view the same way like filtering records by values in _Grid_ view (right click + Filter + IN filter). You might go even further here and turn _Record_ view into _Pivot_ view to show more than one record at once. This is sometimes very useful.

**Comment by shivan** [comment]
That feature for searching/filtering for a column in the record view would really great.

**Comment by serge-rider** [comment]
Filter by column name was added to custom filters dialog.
![image](https://user-images.githubusercontent.com/6398845/52165805-69d76b80-2716-11e9-9ef6-d2c84b48652e.png)

Please create separate FR for record mode improvements.
