### ISSUE TITLE
Add SQL Console tab to objects window

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#4012]
Some types of objects like tables and views would have Console next to Data and ER Diagram tabs. That would be better than opening Console in completely separate tab, because this makes them much easier to find and manage.

**Comment by serge-rider** [comment]
I'm not quite sure about that.
What is the point top have a console (where you can execute any SQL including completely unrelated to the currently opened views/table) in a table editor. I'm afraid it will look like a mess.

**Comment by maln0ir** [comment]
Another option would be improving filter editor and making SQL Console completely separate. Maybe moving it to _SQL Editor_ menu would be good idea.

Currently, we can open Console using button with table name or click on _Expand filter panel_ button. Those are very similar features (at least for me), so how about unifying them? For example: when you click in button with table name, filter editor expands and allows you to edit that query in popup window.
