### ISSUE TITLE
Incomplete ed25519 key support

### ISSUE THREAD

**Issue by x2k13** [dbeaver/dbeaver#4013]
Trying to authenticate an ssh tunnel using a freshly created ed25519 key results in following error messages:
```
Can't initialize tunnel
  Cannot establish tunnel
    Exhausted available authentication methods
      Problem getting public key from com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile@3a09bcf2
        Cannot read encrypted keypair with aes256-ctr yet.
```
DBeaver SSHJ 1.0.11.201808130820 is installed.

**Comment by serge-rider** [comment]
This seems to be fixed in SSHJ already (https://github.com/hierynomus/sshj/issues/427)
We need to upgrade the SSHJ version.

**Comment by nasatome** [comment]
I have a problem trying to connect using ed25519

![2018-11-08_13-54](https://user-images.githubusercontent.com/18271791/48229474-c91f1d00-e36d-11e8-86e8-755526402747.png)

![2018-11-08_13-58](https://user-images.githubusercontent.com/18271791/48229481-cde3d100-e36d-11e8-922b-2f8ea753c52e.png)

![2018-11-08_14-00](https://user-images.githubusercontent.com/18271791/48229485-d0dec180-e36d-11e8-8ee6-517278afbe77.png)

with RSA if it works

I noticed that version 0.26 is used
https://github.com/dbeaver/dbeaver/commit/d195bbda729b1828f85cb52342a5628e7132ff52
and it already includes support for this type of key.
https://github.com/hierynomus/sshj/commit/db48ff85c05d2d85018e32e3631d0a3161d05b82
