### ISSUE TITLE
Issue updating BIT datatype in SQL Server

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#4014]
DBeaver - Version 5.1.5 CE
Operating System: Windows 10
JDBC Driver: jTDS 1.3.1
Database: Microsoft SQL Server Database

When i try to update a BIT datatype column value to 1; I see b'1'
I do not have issues with other data types.

To recreate this issue you need to open the database table and then filter it with a condition and then try to edit a column of BIT datatype. No need to save the record.
Screenshot attached below.

![image](https://user-images.githubusercontent.com/38669892/44221843-62141280-a148-11e8-994d-fdd9168a8191.png)

**Comment by serge-rider** [comment]
Please post sample table DDL to reproduce this.

**Comment by ascendhans** [comment]
There is not sample DDL. All the steps are through UI.
Steps:
1. Open a table that has a column of datatype BIT.
2. Using the UI, select multiple cells of single column of datatype BIT.
3. Type the value 1 and you will see b'1' instead of just 1.

Please let me know if you need anymore help.

**Comment by serge-rider** [comment]
Yep, it is a bug in bit value editor.
