### ISSUE TITLE
Advanced Copy copies query instead of resultset

### ISSUE THREAD

**Issue by cK4i** [dbeaver/dbeaver#4018]
DBeaver Version: 5.1.5.
Environment: Linux Mint 18.3
Language: German
RightClick in resultset -> Erweitertes kopieren (Advanced copy?) -> Erweitertes kopieren (Advanced copy?)
shows SQL formatting and copying instead of the dialog for copying the data from the result set.

**Comment by serge-rider** [comment]
Weird. This is advanced copy for SQL editor, not for results.
Does this happen always or only in some results presentations/modes? Could you post a screenshot?

**Comment by cK4i** [comment]
In the Data View of a table, advanced copy doesn't open a dialog at all.
![image](https://user-images.githubusercontent.com/7453309/44750190-0157e300-ab15-11e8-9e11-0f73ea6e8f2e.png)
![image](https://user-images.githubusercontent.com/7453309/44750245-1fbdde80-ab15-11e8-9886-90be2f365140.png)

**Comment by KES777** [comment]
I also faced this problem. v5.3.5

![__](https://user-images.githubusercontent.com/799021/53748735-a1207000-3eae-11e9-8c16-1e6fbdbb1c8a.jpg)

**Comment by KES777** [comment]
@serge-rider Tell us please. How to copy results then?

**Comment by serge-rider** [comment]
Sorry, missed the @cK4i comment.

Advanced copy (as well as regular Copy) is context (focus) dependent.
If focus in the SQL editor itself then Advanced Copy copies query text.
If it is in results panel then it copies results.

At least this should work this way (and it works this way on the most systems). I know that there are some issues with focus detection on some Linuxes.

@KES777 what is your OS?

**Comment by KES777** [comment]
Linux Mint 18.3

**Comment by uslss** [comment]
cannot reproduce on 6.0.2 Ubuntu 18.04

**Comment by cK4i** [comment]
For me DBeaver says there is no newer Version than 6.0.1. and the problem is still there.
Advanced pasting is also not working (at least not as it worked in an old 4th Version of DBeaver)

**Comment by serge-rider** [comment]
6.0.2 has been released this Monday. Could please check it?

**Comment by uslss** [comment]
Ticket isn't reproduced on 6.0.3 (ubuntu 18.10).
If issue is reproducible for you, feel free to reopen the ticket.

**Comment by cK4i** [comment]
With 6.0.2 it's still the same.
In Table>Data-view advanced copy doesn't open an dialog at all and in the result set from a query it shows the "copy the query" dialog.
