### ISSUE TITLE
hangs when expandig tables in tree view

### ISSUE THREAD

**Issue by cK4i** [dbeaver/dbeaver#4019]
DBeaver Version: 5.1.5.
Environment: Linux Mint 18.3
Language: German
Database: PostgreSQL
DBeaver hangs with 100% thread load when expanding tables in treeview with hundreds of tables/partitions.
I didn't had this problem in the windows version.

**Comment by serge-rider** [comment]
In DBeaver 5.1.5 we migrated to GTK 3 by default. Maybe it is the reason.
Could you try to add
```
--launcher.GTK_version
2
```
in the beginning of dbeaver.ini?

**Comment by cK4i** [comment]
Sorry for the delay, i had vacation.
With GTK V2 it works.
