### ISSUE TITLE
After updating DBEAVER does not display all the schemas of an OpenEdge connection

### ISSUE THREAD

**Issue by specs439** [dbeaver/dbeaver#4020]
We have updated our version of DBEAVER (From: To: 5.1.3 - 5.1.5), and verify that the schemas of our environment are no longer displayed.

To return the installation to version 5.1.3, the schemas are displayed normally.

![image](https://user-images.githubusercontent.com/38566939/44285133-87814900-a23a-11e8-99eb-76781bef31ac.png)

![image](https://user-images.githubusercontent.com/38566939/44284917-b8ad4980-a239-11e8-98ff-fa0e23331035.png)

Note: During tests with installers, I noticed that this change of behavior started to occur in version 5.1.4 of DBEAVER.

**Comment by serge-rider** [comment]
You can fix this by setting driver parameter "Omit catalogs" on:
![image](https://user-images.githubusercontent.com/6398845/44301659-8710ad00-a323-11e8-93c3-b51c9d375b31.png)

We don't have default configuration for OpenEdge driver. If you have working configuration you could post it and we'll add it to default DBeaver driver list. And set "Omit catalogs" on by default.

**Comment by specs439** [comment]
@serge-rider , thanks for your feedback!

I did a test by adjusting the parameter Omit Catlaogs and, after enabled, returned to view the remaining schemas of my environment!

Evaluating the definition of this parameter and comparing with the behavior of version 5.1.3, it seems to me that he is "unlike" in version 5.1.5 of DBeaver. I believe there is an opportunity for correction.

Note: In version 5.1.3 this parameter was disabled and the schemas were displayed normally!


In relation to the Driver Setting OpenEdge, I based on published [documentation](https://knowledgebase.progress.com/articles/Article/How-to-configure-the-DBeaver-SQL-GUI-Client-to-connect-to-an-OpenEdge-database) and maintained by Progress.

I am passing on to you a copy of the .jar file that i use in my connection.
[openedge.zip](https://github.com/dbeaver/dbeaver/files/2302676/openedge.zip)

**Comment by serge-rider** [comment]
Yes, this happened because we changed they way we load schema list in 5.1.4. 
Could you send debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files) so we will be able to understand what went wrong in case of OpenEdge?

**Comment by specs439** [comment]
Hi,

I am passing the log files that you requested.
If you need any additional information, please let me know!

Thank you very much!
[logs.zip](https://github.com/dbeaver/dbeaver/files/2306658/logs.zip)

**Comment by serge-rider** [comment]
Iv'e committed a fix in schema reading function.
Could you check it in EA version (https://dbeaver.io/files/ea)?

**Comment by specs439** [comment]
Version 5.1.6 tested with success!
The visualization of the schemas, even with the option "Omit catalogs" disabled, worked as expected!
Thank you for your assistance and congratulations on the agility in the correction!

**Comment by serge-rider** [comment]
Thanks for testing)
