### ISSUE TITLE
[Data Editor] Unable to perform search within the scope of selected lines

### ISSUE THREAD

**Issue by alexsh2** [dbeaver/dbeaver#4021]
DBeaver - Version 5.1.5 EE<br>

OS - Windows 10

**Steps to reproduce:**

1. Navigate to Data Editor

2. HIt 'Ctrl+f' to open the 'Find/Replace' dialog

3. Select several lines in the opened table (view)

4. Enter the search value<br>

    ![image](<https://user-images.githubusercontent.com/41971602/44298050-c23fbb80-a2e4-11e8-9771-f179f2bd943b.png>)

5. Select the 'Selected lines' radio button in the dialog

**Expected result:**<br>

User is able to perform search within the selected table lines

**Actual result:**<br>

The multiple line selection gets revoked.<br>

The search is available only within the entire table<br>

![image](<https://user-images.githubusercontent.com/41971602/44298096-a4bf2180-a2e5-11e8-83d8-044413047d15.png>)

**Comment by uslss** [comment]
still reproduced on 6.0.2

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D27](https://dbeaver.testquality.com/project/8805/result/1743902/defect/6053). Do not remove or edit.

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D32](https://dbeaver.testquality.com/project/8805/result/1744545/defect/6059). Do not remove or edit.

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D34](https://dbeaver.testquality.com/project/8805/result/1743391/defect/6069). Do not remove or edit.

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D40](https://dbeaver.testquality.com/project/8805/result/1760381/defect/6094). Do not remove or edit.

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D43](https://dbeaver.testquality.com/project/8805/result/1760977/defect/6097). Do not remove or edit.

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D58](https://dbeaver.testquality.com/project/8805/result/1761658/defect/6113). Do not remove or edit.

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D67](https://dbeaver.testquality.com/project/8805/result/1761133/defect/6123). Do not remove or edit.

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D69](https://dbeaver.testquality.com/project/8805/result/1779904/defect/6166). Do not remove or edit.

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D70](https://dbeaver.testquality.com/project/8805/result/1781973/defect/6170). Do not remove or edit.

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D72](https://dbeaver.testquality.com/project/8805/result/1783844/defect/6172). Do not remove or edit.

**Comment by serge-rider** [comment]
Done.

Note: selected lines are highlighted with default text editor color.

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by serge-rider** [comment]
Fixed (now we restore selection if fine/replace is closed or scope is changed)

**Comment by kseniiaguzeeva** [comment]
verified
