### ISSUE TITLE
Distinguish NULL from empty string properly in CSV export/import

### ISSUE THREAD

**Issue by hmontone** [dbeaver/dbeaver#4024]
Currently `NULL`s can be set to some specific string when exporting, but as far as I know, it is not possible to interpret that string as `NULL` when importing. That would be problematic anyway, since data could contain actual values of specified string, and it would be impossible to distinguish them from represented `NULL`s. I can choose to interpret empty fields as `NULL`s, but it is either-or: I can choose to import either `NULL`s or empty strings, I can not import both (if I understand correctly).

What about an option to export empty strings as quoted empty fields and `NULL`s as non-quoted empty fields? And similar option for importing: Quoted empty fields are interpreted like normally as empty strings, and non-quoted empty fields are interpreted as `NULL`s.

For example, table `t1 (c1, c2, c3)` has values:

|c1|c2|c3|
|---|---|---|
||`NULL`|| 
|`NULL`|||
|||`NULL`|

While exporting, you could choose an option (e.g. `Use non-quoted empty strings for NULL`) to use non-quoted empty fields to represent `NULL`s (for simplicity it could be made available only when `quote always` is set, for example), to get CSV file as:

```
c1,c2,c3
"",,""
,"",""
"","",
```

and while importing, you could choose an option (e.g. `Set non-quoted empty strings to NULL`) to interpret non-quoted empty strings as `NULL`s.

**UPDATE** Apparently I slightly misunderstood the functionality of `NULL string`. It works in a way that makes it possible to distinguish `NULL` from zero-length string. Import does not have a way to interpret some given string as `NULL`, though. On that part this is still valid.

**Comment by serge-rider** [comment]
See the fix in 5.2.
