### ISSUE TITLE
Add HAVING and ORDER BY clauses to Grouping panel

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#4025]
Grouping panel is incredibly useful, but too slow to use. For example:
1. finding the biggest value returned by aggregate function requires rerunning query twice with different sorting order (two clicks to set descending order)
2. finding duplicates has a lot more sense with `HAVING count(*) > 1` :)

**Comment by serge-rider** [comment]
Yep, this makes sense

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/45618196-a06d5c00-ba7d-11e8-8868-6b00548321a0.png)
