### ISSUE TITLE
[Data Editor][Revert] Foreign Keys get duplicated

### ISSUE THREAD

**Issue by alexsh2** [dbeaver/dbeaver#4026]
DBeaver - Version 5.1.5 EE
OS - Windows 10
DBs - MariaDB, Oracle,...

**Steps to reproduce:**

1. Delete a Reference from one of the tables
2. Revert

**Expected result:**
Deleted Reference reappears in the 'Properties' tab and in the Datgabase Navigator

**Actual result:**
1. Deleted reference is not displayed
2. Related Foreign Key is duplicated
![image](https://user-images.githubusercontent.com/41971602/44310242-aff47900-a3db-11e8-8265-ae9c19b0557a.png)

**Workaround:**
Refreshing all involved tables restores the proper picture

**Comment by serge-rider** [comment]
Generally it shouldn't be possible to drop references. Because they don't belong to current table.

**Comment by uslss** [comment]
Cannot reproduce on 6.0.2
