### ISSUE TITLE
Allow to remove "Save", "Revert" and "Refresh" toolbar buttons

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#4028]
Hi,
I don't really use the "Save", "Revert" and "Refresh" top toolbar buttons. In the "Customize perspective" view they appear greyed out and I cannot deselect them.

What is their purpose? I might have read a bug report that added the save button to save editor and resultset changes in one click. But revert and refresh look like duplicates of actions already present in the resultset view (cancel button at the bottom and refresh icon in the filter bar).

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/44366483-815ac900-a4d5-11e8-96f0-37fa68034c9b.png)
It will be disabled by default.

**Comment by rdp** [comment]
I was just about to come here and ask "why do you guys not have a refresh button in the data tab?" ... I don't see this option anymore, to test it out and see if it would satisfy that by being "on" by default...? :|
