### ISSUE TITLE
Sessions view: add explain plan

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#4031]
A good feature of the Sessions view could be to show the explain plan for the query currently executed.

**Comment by serge-rider** [comment]
Yep, that's a good feature. See it in 5.2.1
![image](https://user-images.githubusercontent.com/6398845/45577510-0773f080-b885-11e8-8f9e-4cb5fd373259.png)
![image](https://user-images.githubusercontent.com/6398845/45577538-22466500-b885-11e8-9163-871dfddcde4c.png)
