### ISSUE TITLE
[Oracle] Sessions view: show long ops

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#4032]
Information about operations lasting longer than 6s is available in the oracle system view V$SESSION_LONGOPS. Documentation about it available here: https://docs.oracle.com/cd/B19306_01/server.102/b14237/dynviews_2092.htm#REFRN30227

Tora and TOAD display them with nice progress bars that update when you refresh the sessions view.

**Comment by serge-rider** [comment]
No nice progress bars so far. But at least we'll show long ops info (and now we can show any additional session info easily).
![image](https://user-images.githubusercontent.com/6398845/45586777-c0c5db00-b904-11e8-9ddc-75cc8cb882ea.png)

Please create separate ticket for fancy visualization.
