### ISSUE TITLE
DBeaver disconnects when cancelling a query that is fetching data in Hive 1.2

### ISSUE THREAD

**Issue by djmartin4** [dbeaver/dbeaver#4037]
I'm consistently having to invalidate/reconnect to the hive server I am using after cancelling a query that is fetching data. Attempting to run another query without using the invalidate/reconnect option results in the error message in the screenshot. Also, the left side of the screen does not update to show any changes and appears to still be connected.

![image](https://user-images.githubusercontent.com/38948480/44339349-05b63900-a44f-11e8-99c8-1081984bc4f8.png)

**Comment by serge-rider** [comment]
- What Hive driver version do you use?
- Could you post debug log (or just a part of it with related errors) - https://github.com/dbeaver/dbeaver/wiki/Log-files
