### ISSUE TITLE
Aliases for DB2 zOS table

### ISSUE THREAD

**Issue by sumithar** [dbeaver/dbeaver#4038]
I'm using DBeaver 5.1.5 on Win 10 and connected to DB2 zOS v10. When I look at a list of tables for a schema it lists both aliases and tables. If I highlight what I know is an alias and choose F4 it does show table type is an alias but doesn't show what actual table it's an alias of.  Is there someplace I could find this in DBeaver that I am not looking at?

**Comment by serge-rider** [comment]
Unfortunately we don't support aliases reading for zOS (yet).
You can disable alias in table list (it is controlled by driver property `returnAlias`).
To see actual table you can run `SELECT LOCATION FROM SYSIBM.SYSTABLES WHERE NAME=TableName`. I can't test it but it should work.

**Comment by sumithar** [comment]
Thanks Serge. For now I can always log on to the  mainframe directly and see that information, but if in future you include it, it will enable me to stay w/in the confines of DBeaver.  Gr8 product, btw.
