### ISSUE TITLE
UI: Can 'File -> Convert Line Delimiters To' option moved to Edit menu or just above File -> import option please?

### ISSUE THREAD

**Issue by reddyshyam** [dbeaver/dbeaver#4040]
UI: Can 'File -> Convert Line Delimiters' To option moved to Edit menu or just above File -> import option please? 

I feel after File->Open File, Open Projects, related items should be listed instead of the above. Please see if my request makes sense. 

Many thanks in advance.

**Comment by serge-rider** [comment]
Agreed. This makes sense (I'm also annoyed by this item in File menu)
