### ISSUE TITLE
Excessive Memory usage after upgrading to 5.1.5

### ISSUE THREAD

**Issue by harishreddy-m** [dbeaver/dbeaver#4041]
**Env** :
Elementary OS

2018-08-21 09:24:31.331 - DBeaver 5.1.5.201808130751 is starting
2018-08-21 09:24:31.332 - OS: Linux 4.15.0-32-generic (amd64)
2018-08-21 09:24:31.333 - Java version: 1.8.0_181 by Oracle Corporation (64bit)

2018-08-21 09:24:33.610 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2018-08-21 09:24:33.610 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

**Comment by harishreddy-m** [comment]
With DBeaver 5.1.1

I see following logs
Gtk-Message: Failed to load module "pantheon-filechooser-module"

(dbeaver:6781): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(dbeaver:6781): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(dbeaver:6781): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(dbeaver:6781): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
Gtk-Message: Failed to load module "pantheon-filechooser-module"

(java:6798): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(java:6798): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(java:6798): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(java:6798): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

**Comment by harishreddy-m** [comment]
Adding

> --launcher.GTK_version
> 2

to /usr/share/dbeaver/dbeaver.ini file solved the problem

**Comment by BlackBeltBob** [comment]
This is no longer possible, since GTK2 is no longer supported. Is there another workaround?
