### ISSUE TITLE
Sql editor always open on default connection database 

### ISSUE THREAD

**Issue by datopalov** [dbeaver/dbeaver#4043]
Sql editor always open on default connection database.

**Reproduce steps:**
default connection database: {db-1}
Set active object {db-2} and target {db-2}
Open New sql editor
**Expected result:**
sql editor on {db-2}
**Actual result:** 
sql editor on {db-1}
**Info:**
Windows 10 64 bit
Postgresql 10
DBeaver Community Edition 5.1.5 Windows 64 bit (installer + JRE)

**Comment by serge-rider** [comment]
Please provide a bit more info.
- What is your database (MySQL, Oracle, etc)?
- How do you set default database?
- What do you mean under SQL editor database (the one which is selected in main toolbar, actual current database)?

**Comment by datopalov** [comment]
![pg-bug-1 - copy](https://user-images.githubusercontent.com/19872068/44538561-59a07680-a70a-11e8-997a-a5bc2ec1c27a.PNG)

**Comment by BookLaugh** [comment]
Same here, only with newer DBeaver version.
Default database for connection is "a11_terminal" and after switching it to "a11_main" editor is not affected. It used to be in versions 5.1.1 and older. 

![beaver_db_selection](https://user-images.githubusercontent.com/17001785/44784040-85997d00-ab8c-11e8-971a-9404613cb7c8.png)

**Comment by serge-rider** [comment]
This looks very similar to #4095 (you can check the fix in EA: https://dbeaver.io/files/ea)

**Comment by BookLaugh** [comment]
@serge-rider You're 100% right. Both disabling the "Open separate separate connection for each editor" option and installing version 5.2.0 helps. I'm currently working on 5.2.0 with "Open separate separate connection for each editor" enabled and the connections are switching just fine.

Thank you for your support.

**Comment by serge-rider** [comment]
Thanks for testing
