### ISSUE TITLE
Table designer issues

### ISSUE THREAD

**Issue by ArturGomesSoft** [dbeaver/dbeaver#4044]
Hi.

Whenever I try to use the designer to create a new table or add a new column to an existing table, I'm getting the following message and the designer just rolls back:
"Can't find node corresponding to new object"

Anyone has this issue?
What i'm missing here?
Should I download and install a previous version, since this happens only after the latest upgrade?

thanks for your help!

**Comment by ArturGomesSoft** [comment]
Hi.
Apparently, the code to modify the table table structures is there, as it will appear when persisting the changes, but it's not shown in the interface.

As no one answers this, I tried to find an old version of DBeaver to replace this last one. Couldn't find it.
Anyone knows where could I find the previous version of the software?

Thanks in advance.

Artur

**Comment by ArturGomesSoft** [comment]
Forget it.
I managed to find an old version.
Thanks anyway!

**Comment by ArturGomesSoft** [comment]
Thanks Serge, for your answer.
I'll be waiting for the next release.
By the way, and please excuse my lack of knowledge, what is a "EA version" ?
Many thanks!

**Comment by serge-rider** [comment]
It is Early Access (https://dbeaver.io/files/ea)

**Comment by boredhero** [comment]
Uh Hi I'm using 7.0.2 on Arch Linux and currently experiencing this same issue.

**Comment by ex3lio** [comment]
Hi, same problem using 7.0.2 on Manjaro 20 : "Can't find node corresponding to new object" when trying to create anything. Could you please reopen the issue ?

**Comment by ArturGomesSoft** [comment]
Hi Ex3lio.
In version 7.0.3 the issue is already solved. I guess is the latest version.
Are you able to update from dbeaver site?
I'm using version 7.0.3.202004191823 and it seems to be just fine.

**Comment by ex3lio** [comment]
I'm gonna try, thanks for your quick reply Arthur!

**Comment by ArturGomesSoft** [comment]
My pleasure! 
Good luck.

**Comment by edergonn** [comment]
Hi guys, I am having this same problem in version 7.2.3 on Debian 10.

**Comment by lunar21** [comment]
Hi guys, i am having this same problem in veresion 24 on Mac Os,
