### ISSUE TITLE
Option for new line before comma in SQL select statement

### ISSUE THREAD

**Issue by dpsspatial** [dbeaver/dbeaver#4049]
The only formatting option I can't see in DBeaver is to set the option to start a new line before a comma, that is, format a SQL statement with the comma at the front of the line, rather than the end:

```
select
   schnum
  , abbreviation
  , school_name
from schools
```
Other tools like DataGrip and the MSSQL Server Management Studio plugin 'Poor Man's SQL Formatter' allow for this option, and we find it more intuitive to show the comma at the start of the line.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/46504503-c3965a80-c836-11e8-81b0-c1802d06f56a.png)

**Comment by dpsspatial** [comment]
AMAZING!!! Thank you very much!!!
