### ISSUE TITLE
Export Resultset as SQL does not add ' ' around character fields

### ISSUE THREAD

**Issue by cbuckle1** [dbeaver/dbeaver#4050]
Currently, export resultset as sql creates a file with insert statements like:
INSERT INTO stv_recents (userid,status) VALUES 
(126,Running);

vs.

INSERT INTO stv_recents (userid,status) VALUES 
(126,'Running');

**Comment by serge-rider** [comment]
Generally character values should be quoted.
What is your database and what column type column "status" has?
