### ISSUE TITLE
Not able to edit values in cell for Redshift

### ISSUE THREAD

**Issue by iolap-mmeyyappan** [dbeaver/dbeaver#4051]
Bug
I was able to edit cells and save, add new rows to a table in redshift until I upgrade to 5.1.5
no I can't edit cell and save or add a new row

**Comment by serge-rider** [comment]
This is because AWS driver says that database is in read-only state. Not sure why does this happen.
Anyhow we'll add a workaround in the next version.

**Comment by iolap-mmeyyappan** [comment]
Thanks. Moved back to 5.0.5 and it works there.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by serge-rider** [comment]
We'll use PostgreSQL extension for Redshift since DBeaver 5.1.6:
![image](https://user-images.githubusercontent.com/6398845/44521724-b6853800-a6dc-11e8-83e4-6f40645c8e79.png)

**Comment by orlandoboletini** [comment]
How open many connections from informix database?
