### ISSUE TITLE
DBeaver: Set column minimum width to consider text width "[NULL]" when presenting data in text grid (part 2)

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4053]
DBeaver - **Version 5.1.5 CE**
Operating System: **Windows 10**

Set column minimum width to consider text width "**[NULL]**" when presenting data in text grid (part 2).

In version **5.1.5 CE** the behaviour in column width was improved  (see CASE #3949), but if I use the **Maximum result-set size** the width is adjusted per row batch.

This looks kind of strange when I move from one result-set batch where there is no NULL column value, to a result-set batch where there is a NULL value. 

Looks something like this (first 200 rows, then I press **Move to next row** button:

```
|Unr                                  |ClinicId |Sign |PersonId |
|-------------------------------------|---------|-----|----------|
|A957FAFF-FF14-4BD4-A994-0521767B1C70 |1        |ab   |1         |
|A957FAFF-FF14-4BD4-A994-0521767B1C70 |1        |ab   |2         |
...
|8600CCFF-6941-4D21-9163-129E18C00E7D |1        |ab   |200       |
|43F5ECFF-2403-4F84-A32F-92825BC9AD2B |1        |[NULL]|201       |
|D7F97F00-43C5-4E27-93A2-C72A6031B91F |1        |ab    |[NULL]    |
|8600CCFF-6941-4D21-9163-129E18C00E7D |1        |ab    |203       |
```

Seems that the adjustment in version **5.1.5** looked at if there where any column values that contained NULL and if so adjusted the column width.

Think the more simple solution can be that instead of looking at the data column definition to see if the column allows NULL values, and then make the column width adjustment. Or even more simple (if a bit crude) to not allow any column to have a column width less than a width that can contain the "[NULL}" string.

**Comment by serge-rider** [comment]
Thanks for the bug report
