### ISSUE TITLE
tab name should contain name of resulting table

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4056]
for an example I do `Read data in SQL console` for few tables.

for each table I get tab with name: `<PostgreSQL - postgres> Query`
this forces me click each tab to find required one.

Spy into 'Sublime Text' editor and look how they name tabs ;-)

**Comment by KES777** [comment]
![delete1](https://user-images.githubusercontent.com/799021/44465361-ffc68080-a625-11e8-8190-592a54ec10df.jpg)

**Comment by serge-rider** [comment]
Generally it doesn't make sense to create separate SQL editor for each query.
You can keep any number of queries in one editor (to execute just one query set cursor on it and run with <kbd>ctrl+enter</kbd>). Just divide them by delimiter (;) or empty line.

Results tab will be named by queried table name if this is supported by database driver (as you can see on your screenshot).

**Comment by KES777** [comment]
> Just divide them by empty line.
empty lines result valid sql to fail: #4048 

>Generally it doesn't make sense to create separate SQL editor for each query.
it is created automatically by `Read data in SQL console`

>Results tab will be named by queried table name if this is supported by database driver (as you can see on your screenshot).
I see that tabs named by same name. The driver, I use, is installed automatically by `dbeaver`

Please improve `dbeaver` to name tabs differently. That is ugly to have tabs with same name =(

**Comment by jim256** [comment]
I'd also like to vote for this.

I had an extension for SQL Server Management Studio that would auto-rename tabs based on the first table of the query used, and it was very helpful.

I always use a separate tab for each query, just to make managing them more straightforward in my mind. If I have a 300-line script, it makes more sense for me to have a separate editor for each script.

I also frequently select all and copy/paste as I bring queries into or out of DBeaver and to/from Tableau, Snowflake's online editor, etc. Doing this with Command + A is very fast. If I had more than one query per script, this could get tedious.

**Comment by kseniiaguzeeva** [comment]
Is this issue still actual for you? Now (version 7.0.2) every new SQL Editor has script number in its name.

**Comment by uslss** [comment]
if issue is still actual for you - feel free to reopen the ticket

**Comment by ganeles** [comment]
I need it :(
I have a lot of tabs and it's really hard to manage it by numbers only
