### ISSUE TITLE
in context of joining suggest table names

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4057]
![delete1](https://user-images.githubusercontent.com/799021/44465408-208ed600-a626-11e8-9e7d-6abe3dc13563.jpg)

here I want to speedup `service_package` typing, but your tool do not suggest it me =(

in additional to columns suggest table names

Also will be handy to have fuzzy searching (For details look at 'Sublime text' editor)

**Comment by serge-rider** [comment]
You should use fully qualified table names (with schema prefix).
Or use "global search":

![image](https://user-images.githubusercontent.com/6398845/45351452-e7131000-b5be-11e8-8c8b-56c05d799395.png)
