### ISSUE TITLE
it would be more handy if new space will be added when expanding view

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4058]
* when we want to see something we scroll

 * when we expanding something we want more space

Thus when user expanding add more space than scrolling

As you can see there are comlexity to add extra space after the query:

when cursor on last line we can not move it to the end by mouse,
also we can not scroll down,
we need to click somewhere else and navigate to the end by arrows =(

[bug_dbeaver.mp4.tar.gz](https://github.com/dbeaver/dbeaver/files/2310511/bug_dbeaver.mp4.tar.gz)

**Comment by uslss** [comment]
seems that issue is resolved
