### ISSUE TITLE
[SQL Standard] FETCH FIRST is broken

### ISSUE THREAD

**Issue by lacanoid** [dbeaver/dbeaver#4061]
Using SQL 2008 standard version of LIMIT, FETCH FIRST causes an error:

    select * from atom.audit order by ctime desc fetch first 10 rows only;

Query execution failed
Reason:
SQL Error [42601]: ERROR: syntax error at or near "LIMIT"
  Position: 73

This seems like an issue with dbeaver's query parser not realising that a query in fact does have a limiting clause and adding one at the end of the query, effectively preventing user from running standard-compliant queries.

As this form is supported by Postgres, DB2, Oracle and MSSQL (https://modern-sql.com/slides) it might perhaps make some sense to fix it at some point.

**Comment by serge-rider** [comment]
Looks odd, I can't reproduce this. We don't use LIMIT for SQL Server.
What DBeaver driver do you use? jTDS, Microsoft? Or is it some custom configured driver?

**Comment by lacanoid** [comment]
Using Postgres. The log clearly shows the error where LIMIT is added.

**Comment by serge-rider** [comment]
It is a bug in SQL transformer.

As a workaround you can disable "Use SQL to limit fetch size" option. BTW it is disabled by default.
![image](https://user-images.githubusercontent.com/6398845/44628534-f4d35f00-a949-11e8-8a5b-9a0823a75865.png)
