### ISSUE TITLE
[PostgreSQL] DDL is broken

### ISSUE THREAD

**Issue by lacanoid** [dbeaver/dbeaver#4062]
DDL generator adds a bunch of weird GRANTs at the end of DDL, like:

    GRANT ALL, SELECT, INSERT, UPDATE, DELETE, REFERENCES(loaded) ON dbms.buffers TO postgres;

This does not execute as it is now, it should probably loose the 'ALL, ' part at least, as it causes a syntax error. The result is that user cannot, for example, save views from dbeaver source tab anymore now:

ERROR: syntax error at or near ","
  Position: 11

Also, dbeaver doesn't seem to grok completely that position 11 refers to the GRANT part of the query only and wrongly highlights the error position at the top of the complete DDL. This further confuses the user because the source of the error is not apparent.

These grants are probably a bit redundant overall, as ALL is already granted to postgres a few lines above anyway:

    GRANT ALL ON TABLE dbms.buffers TO postgres;

Also, as it is, ALL, SELECT, INSERT, UPDATE, DELETE are granted to the same user many times, only REFERENCES part seems to change.

**Comment by serge-rider** [comment]
These are column grants. Indeed, currently we generate them redundantly.
Thanks for noticing.
