### ISSUE TITLE
[Usability] Add rename functionality for views and routines

### ISSUE THREAD

**Issue by lacanoid** [dbeaver/dbeaver#4063]
Title says it; this is provided now, but it's for tables only. 
View and routines can be renamed too, at least on Postgres.
Now user has to type and refresh a lot to do this and it's tedious.

Also, it seems that renaming a table currently doesn't do anything.
It doesn't seem to work with MySQL either :(
After rename it should probably pop up the "Persist Changes" dialog with appropriate ALTER.
Note that one wouldn't want to rename stuff too easily or by accident.
Explorer tree should be refreshed automatically after a rename.

**Comment by lacanoid** [comment]
Hmm, that's odd. Rename doesn't seem to do anything, neither on postgres nor mysql.
It pops up the rename box asking for a new name just fine. 
But when I type in a new name and press return or OK, nothing happens.
Persist dialog doesn't appear and table doesn't get renamed.

Note that I'm testing this with DBeaver 5.2.0 on a mac.
I will check on other platforms and report.

**Comment by serge-rider** [comment]
@lacanoid If you have object editor opened (on the right side) then rename doesn't execute server-side rename immediately, it just changed the name in the editor. 
Also in new (5.2.4+) object editor design you can just change Name property value in the editor.

After that you need to save editor (ctrl+s or save button in the toolbar/main menu).

PostgreSQL views and functions rename functionality will be added in 5.2.5.
