### ISSUE TITLE
Read data in SQL console - create script

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4066]
When I close application it asks me: Save 'XXXX' tab? I click 'Yes'

but when run dbeaver again only one tab is opened.

all tabs should be opened on next run

**Comment by KES777** [comment]
All other tabs, maybe, not saved because they have same name? #4056

**Comment by serge-rider** [comment]
DBeaver saves and reopens SQL scripts but not SQL Console tabs.
SQL console is a temporal window, it is not saved anywhere. Perhaps we should document this somewhere..

So, I think you need to use SQL editor(s) instead of console. Note: you may have as many SQL queries in a single editor as you need.

**Comment by KES777** [comment]
Even do not notice difference between script tab and console tab.

May you please put a note about theirs differences?

**Comment by serge-rider** [comment]
https://github.com/dbeaver/dbeaver/wiki/Script-Management#sql-console

**Comment by KES777** [comment]
huh... I am in most cases wanna to save SQL into script.

>SQL console doesn't has an associated .sql file. Its contents will be lost when you close it.

This is bad practice just silently drop written SQL.

Better way, instead of console open script tab and ask user to save his work in progress. Then he can decide to save SQL or not.

**Comment by KES777** [comment]
> it doesn't make sense to create a new script for each such operation

It have sense, because I modify sql by joining another tables

Also I write annditional SQLs to work with table data. If I do not need writed sql I will just hit "Do not save"

>Or maybe its better to open SQL editor for "Read data" action.

unfortunately in the menu when right clicking on table name, there is no such opiton. There only `Read data in SQL console`

**Comment by KES777** [comment]
to my mind "Read data in SQL console" must be just "Read data". this command will:

  1. Open SQL editor 
  2. Generate select ... from <table_name> statement
  3. All field names must be listed: select id, name, other_field, ... from

over `select * ` this gives me the benefit of that I can narrow selection to desired set of fields by deleting not desired names instead of manual typing

**Comment by KES777** [comment]
PS. The most handy DB console is http://ibexpert.net/ibe/. I used it 10 years ago.

**Comment by serge-rider** [comment]
I believe current command does exactly the same (the only difference that there is no script file)
