### ISSUE TITLE
Autocompletion automatically removes the schema when selecting the recommendation

### ISSUE THREAD

**Issue by victorlora** [dbeaver/dbeaver#4069]
In the latest version (v5.1.5201808130751), autocompletion automatically removes the schema when selecting the recommendation. For example:

- Recommendation: database.schema.table
- After selecting recommendation: database.table

If I activate the "Use long name" in preferences, it result in: database.database.schema.table

**Comment by serge-rider** [comment]
Yep, there is a bug in long object names generation.
