### ISSUE TITLE
UI dark theme problem in 5.1.5

### ISSUE THREAD

**Issue by holms** [dbeaver/dbeaver#4070]
Before today's update  I've had beautiful black UI for the whole window, now it looks like crap, I mean so many margins between buttons,  also as buttons itself became huge together with fonts, whole gray area should be dark . I didn't changed anything. Before update I've had beautiful dark theme with nice margins and everything. I'm using DWM windows manager and dark themes for QT and GTK3/2

That's 5.1.5 version:
![dbeaver](https://user-images.githubusercontent.com/280958/44563199-cd23a180-a765-11e8-984a-22ddb34003a9.png)

That's 5.1.4 version:
![dbeaver2](https://user-images.githubusercontent.com/280958/44563157-99e11280-a765-11e8-8f20-d8cd26e02150.png)

**Comment by serge-rider** [comment]
It works fine with GTK3 in Ubuntu.  But fails in many non-standard window managers.
For now we have only this workaround :(

**Comment by serge-rider** [comment]
We reverted back to GTK2 (by default) in 5.1.6.
