### ISSUE TITLE
Connect DB on execute -  and query should get executed

### ISSUE THREAD

**Issue by surpavan** [dbeaver/dbeaver#4072]
I have tried the feature/option of CONNECT DATABASE when QUERY is executed.

It is connecting the database -  but query is not executing -  we have to re-execute the query -  not an issue but might be required as expected one for this feature.

**Comment by serge-rider** [comment]
Query should be executed right after connection is established.
If it is not executed then it is a bug but I can't reproduce this.
Is there anything special about your connection? Maybe it is too slow?

**Comment by surpavan** [comment]
Sorry, probably my mistake last time-  might have overlooked it.
This is working - checked with Mysql and Redshift.  Thank you for the time.

**Comment by surpavan** [comment]
Found the case -  this is not working my MS SQL; but working for Mysql and Redshift.

**Comment by surpavan** [comment]
Found the case -  this is not working my MS SQL; but working for Mysql and Redshift.

**Comment by serge-rider** [comment]
Can't reproduce. Maybe you have connection-specific configuration?
Check this:
![image](https://user-images.githubusercontent.com/6398845/44878806-8d524200-acb0-11e8-8bc0-88cea8058bf5.png)

**Comment by surpavan** [comment]
We can close this as it is minor or not reproducible -  not a crucial one either to spend time on.
![temp](https://user-images.githubusercontent.com/37795549/44910488-07caa280-ad41-11e8-98c7-169d93c4c920.PNG)
