### ISSUE TITLE
BUG: Rearranging columns order blocks "Move object down" button

### ISSUE THREAD

**Issue by Speirs47** [dbeaver/dbeaver#4074]
Just a small bug I noticed.
When I move a column to the end of table the "Move object down" button is blocked and that's right behavior. But when I select a different column the button is still blocked.
A way to enable this button is to move column up once.

**Comment by rodrigoguariento** [comment]
> Just a small bug I noticed.
> When I move a column to the end of table the "Move object down" button is blocked and that's right behavior. But when I select a different column the button is still blocked.
> A way to enable this button is to move column up once.

I'm facing the same problem, and more: I'm using Linux version, when I end up click over Move Object Up/Down the rearrangement does not occur in real time, nothing happens. The rearrangement only occurs after refresh (F5).
