### ISSUE TITLE
DBeaver exits when long query notification popup is shown

### ISSUE THREAD

**Issue by marco-sanjuan** [dbeaver/dbeaver#4075]
Hi

Since last 2 dais, when I execute a slow query, dbeaver hangs and close trying to show notification popup.

I had to disable notifications to be able to work.

Nothing is written to log file when it occurs (~/.dbeaver4/.metadata)

I'm on 5.1.5.201808130751 version over Debian 9 Stretch connecting to Oracle 12 database.

Sorry, i have no more info to reproduce issue.

Thanks

**Comment by marco-sanjuan** [comment]
Hi Serge

It looks like issue has gone after update to 5.1.6 version. This now works fine.

Only one question, is it possible to change notifications position? with multimonitor, notification appears  
 at bottom between 2 screens.
Thanks!

**Comment by serge-rider** [comment]
You could try to change notifications preference to "Desktop popup":
![image](https://user-images.githubusercontent.com/6398845/44661061-23b50800-aa12-11e8-8bee-02dba8c5eb63.png)

**Comment by marco-sanjuan** [comment]
It doent work, commit/rollback/reconnect notification and long time sql notification are different kind:

Rollback example
![image](https://user-images.githubusercontent.com/4165141/44704592-2b20f380-aa9c-11e8-9079-9796f02fcdd3.png)

Long time sql notification example (truncated):
![image](https://user-images.githubusercontent.com/4165141/44710020-7098ed00-aaab-11e8-8990-4d956dfe097d.png)

Thanks
