### ISSUE TITLE
Wrongly generated DDL for a foreign table (PostgreSQL)

### ISSUE THREAD

**Issue by georgiraychev** [dbeaver/dbeaver#4076]
I've just noticed that if you right click an already mapped foreign table, and select Generate SQL - > DDL it generates the SQL code like this:

```
CREATE FOREIGN TABLE schema.table (
a text,
b text
)
SERVER server_name
OPTIONS dbname=sample_db_name, table_name=sample_table_name;
```

The options are generated wrongly. The correct way to do this in Postgres is:

```
CREATE FOREIGN TABLE schema.table (
a text,
b text
)
SERVER server_name
OPTIONS (dbname 'sample_db_name', table_name 'sample_table_name');
```

More info [here](https://www.postgresql.org/docs/current/static/sql-createforeigntable.html).

I'm using the latest version of DBeaver (5.1.5), connecting to PostgreSQL db.

**Comment by serge-rider** [comment]
Thanks for bug report
