### ISSUE TITLE
Column width if flushed after each query execution

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4078]
After I ran query I change column width:

![delete1](https://user-images.githubusercontent.com/799021/44583737-48f60c00-a7af-11e8-8c9e-71f08d03354e.jpg)

but after next execution its width is flushed:

![delete2](https://user-images.githubusercontent.com/799021/44583739-4abfcf80-a7af-11e8-9afc-c659026e2603.jpg)

Please keep column width

**Comment by serge-rider** [comment]
Yes, we should keep columns width on refresh.
