### ISSUE TITLE
Database Import / Restore dialog

### ISSUE THREAD

**Issue by aellinwood** [dbeaver/dbeaver#4079]
Clearly indicate the destination Connection and Database in the Database Import dialog.

Colorize the Database Import dialog to match the connection type of the destination database.

In the Database Import dialog, in the progress tab before starting the import, clearly describe the action that is about to be taken with the source file and destination database.

This would give a warm, fuzzy feeling to anyone who maintains dev and prod databases and often copies databases around.

**Comment by p91paul** [comment]
I second this: expecially in the last screen of the export/import table data wizard, i see table A is being copied to table A. I would feed much better if it said table A from connection X is being copied to table A from connection Y!

**Comment by serge-rider** [comment]
First beta:
![image](https://user-images.githubusercontent.com/6398845/51090496-d6052600-178d-11e9-9de4-58a85b355771.png)

Can improve it even more?

**Comment by p91paul** [comment]
One thing that bothers me sometime is that is case of existing destination table with missing columns you'd show "existing". That is correct, but hides the fact that the data transfer will create the missing columns. So a different label for that situation would help (e.g "existing/create columns", but that's bad)

**Comment by aellinwood** [comment]
I wasn't expecting table detail, but I like it!

Does it showed a super-set?; including untouched tables on the left, and new tables on the right? I love the color coding. As it is, I can say that I would be comfortable knowing that I'm copying in the right direction (Dev to Production) and I can clearly see the tables affected.

-- Add database name on the destination.
-- Would you have a database name on the source?
-- Add the .sql filename to the Source Settings
These would add to my comfort level: I would know which databases I am copying to, and which file I am using.

Instead of Source Container and Target Container, how about Source Connection and Target Connection? And instead of Source Name and Target Name, how about Source Table and Target Table?

The possibility exists that an import only creates a database. I'm not sure how that would be displayed accurately other than just the connections.

In the future, where it says [Create], it would be nice to see each action that applied to that table in the import. [Drop,Create,Insert], [Create,Insert], [Create], etc.

Adding to p91paul's comment: when the tables have a non-empty diff (besides the auto_increment id), that could be identified as a <!> flag in a fifth column. On hover, it could show a tooltip with a diff of the CREATE TABLE statements limited to 5 or so lines so that it doesn't look too sloppy. If more lines are in the diff, add an ellipsis (...) to indicate to the user that they need to dig into that if they are interested. This might be more of a db comparison function than an import function, but perhaps the same tool would serve double duty if you ever make that.

Thanks for addressing this!

**Comment by serge-rider** [comment]
@p91paul Like this?
![image](https://user-images.githubusercontent.com/6398845/51102634-cec33400-17f0-11e9-8317-5c22b79d3115.png)

@aellinwood Well, we have another FR for detailed schema comparison (and DDL generation). I think we should keep just brief change info in this wizard for now.
Target objects isn't necessary a database/table. Here is how export to CSV looks like:
![image](https://user-images.githubusercontent.com/6398845/51102735-2b265380-17f1-11e9-9d8f-c9be2531b850.png)

**Comment by p91paul** [comment]
Wonderful! However I suggest showing nothing instead of [No changes]. It could lead to someone asking "What? no changes? But I requested the data to be copied!". It becomes obvious only if you have many tables with different labels that [No changes] is referred to the table structure.

**Comment by serge-rider** [comment]
Agreed.
