### ISSUE TITLE
CLOB Editor does not display very long lines

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#4080]
I have a CLOB where the first line is very long (>5000 char). If I open it in value editor, that line appears filled with blank characters.

It appears if I either switch to binary mode or enable text wrap. Moreover, if I select all and copy it, the first line correcly goes to the clipboard and gets pasted. So the issue is only in the text mode of the CLOB editor.

Using dbeaver 5.1.5 with Oracle database.

**Comment by serge-rider** [comment]
By some reason characters in long lines are invisible in base text editor (and in StyledText).
I believe this is a bug in Eclipse 4.8 framework. Anyhow, we can fix it by providing projection source viewer.
Thanks for report.
