### ISSUE TITLE
Bug - Icons are enabled when no result available in script editor.

### ISSUE THREAD

**Issue by michelvosje** [dbeaver/dbeaver#4084]
# Problem
When I open a new script editor, which has no data, the following buttons are enabled:

![image](https://user-images.githubusercontent.com/5354633/44628168-095c2b00-a93b-11e8-9f25-97d5299344cf.png)

I'd say that:
* **Custom Filters** button should be disabled.
* **Configure> Order/Filter** button should be disabled.
* **Open results in Excel** should be disabled.

As these buttons don't provide any functionality when there is no data.

**Comment by serge-rider** [comment]
thanks for the bug report.
