### ISSUE TITLE
Bug-Setting the Default Value on an existing table throws an error

### ISSUE THREAD

**Issue by huynhtk** [dbeaver/dbeaver#4085]
When setting/altering the Default Value on a varchar column, DBeaver generates the following SQL:
ALTER TABLE schema1.table1 ALTER COLUMN notes SET DEFAULT DummyData;

Executing that SQL shows the following error:
SQL Error [42703]: ERROR: column "dummydata" does not exist.

However, adding quotes around DummyData works:
ALTER TABLE schema1.table1 ALTER COLUMN notes SET DEFAULT 'DummyData';

Windows: 8.1
DBeaver: 5.1.5
Postgres:10.0

**Comment by huynhtk** [comment]
Need to add surrounding '' on GUI.

**Comment by serge-rider** [comment]
Default value can be any SQL expression. 
So manual string quoting is required.
