### ISSUE TITLE
5.1.5 Values in Bind parameter(s) popup don't update when I type, only when I exit the field

### ISSUE THREAD

**Issue by anophelesgreyhoe** [dbeaver/dbeaver#4088]
dbeaver 5.1.5 on Ubuntu 16.04.
When I run a PL/SQL script and the Bind parameter(s) popup is displayed, I can see the remembered values from the last run, but when I click on one of the values to change it, there is no indication that I can edit the field. Typing into the selected Value field appears to have no effect, but if after typing something I then exit the field (e.g. push Tab) then the field updates to show the results of my editing.

I tried forcing GTK version 2 but that didn't seem to help either.

I've just rolled back to 5.1.3 to confirm this issue affects just this version and isn't an issue elsewhere in my system, and on 5.1.3 everything is fine.

**Comment by serge-rider** [comment]
Please try version 5.1.6. It sounds like a bug in combination GTK3 + Eclipse 4.8. We reverted to GTK2 and Eclipse 4.7 in 5.1.6.

**Comment by anophelesgreyhoe** [comment]
Yes, that works again on 5.1.6. Thank you!

**Comment by serge-rider** [comment]
Thanks for info
