### ISSUE TITLE
Pg_restore directory format still not working -5.1.6

### ISSUE THREAD

**Issue by aekoise** [dbeaver/dbeaver#4090]
Once again thanks for the great tool. I cannot restore a Postgres database using restore option. I don't recollect this feature working.

Steps

1. Select  DB/ Tools/Restore
2. Format  : Directory
3. Backup File :  Click browse button
4. Dialog-box opened does not support selecting a directory

Also, when I go the route of copying directory path into Backup file text-field and click start I am getting the error  IO Error: Utility 'pg_restore.exe' not found in client home 'C:\dbeaver\postgresql-x64-9.6'. This is strange as the pg_restore should not be within dbeaver path. Is the Postgres installation path configurable from within DBeaver?

**Comment by serge-rider** [comment]
This is similar to #4106 . Old client home configurations seems to be not working after upgrade. Workaround: add PG client home manually one more time (on connection edit properties page).

Problem with directory selection will be solved in the next version, thanks for noticing.

**Comment by serge-rider** [comment]
Native client selector was fixed, PG locally installed client home resolution was fixed.
Please check this in EA version (https://dbeaver.io/files.ea)
