### ISSUE TITLE
SQL Server: How can I check if the table behind a synonym exists

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#4091]
DBeaver - Version 5.1.6 CE
Operating System: Windows 10
JDBC Driver: jTDS 1.3.1
Database: Microsoft SQL Server Database

How can I check if the table behind a synonym exists ?
I found an article on Stackoverflow about this:
https://stackoverflow.com/questions/15639907/how-can-i-check-if-the-table-behind-a-synonym-exists

Is there a way we can incorporate this through UI, without running the SQL manually ?

**Comment by uslss** [comment]
Link to the target table is available at the Synonym tab
![image](https://user-images.githubusercontent.com/31996417/161942062-4536a462-4027-46e0-a733-40b5f97c8126.png)
