### ISSUE TITLE
SQL Server: Some Datatypes are missing icons

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#4092]
DBeaver - Version 5.1.6 CE
Operating System: Windows 10
JDBC Driver: jTDS 1.3.1
Database: Microsoft SQL Server Database

A few datatypes are missing icons. Please check the screenshot below.

![image](https://user-images.githubusercontent.com/38669892/44674405-fefd6800-a9f2-11e8-926f-d63493a69eda.png)

**Comment by serge-rider** [comment]
I see icons in all data types in the screenshot. Do you mean questionmark icon? It is assigned for all "unsupported" data types.

**Comment by ascendhans** [comment]
Yes i meant for question mark icon. Thanks for sharing the information.
