### ISSUE TITLE
Generate SQL

### ISSUE THREAD

**Issue by ramunozp** [dbeaver/dbeaver#4093]
There is a problem using the SQL generator. every time I want to generate one of the selected fields, it does not work correctly, for example:
- If I select for what I want to filter, it does not respect it.
- If I want to generate the update of a particular field, it does not, on the contrary, it generates it from all the fields, which I do not want.
- In general, it does not work when I'm using the result in text mode.

<img width="541" alt="imagen" src="https://user-images.githubusercontent.com/24207310/44677753-1cd7c680-aa0d-11e8-92ef-a9392b3ff35a.png">

<img width="529" alt="imagen" src="https://user-images.githubusercontent.com/24207310/44677777-2d883c80-aa0d-11e8-866f-7100aa9c9fe5.png">

**Comment by ramunozp** [comment]
and?

**Comment by serge-rider** [comment]
SQL generator is supposed to work this way. It generates query which selects/updates/deletes current row.
If you don't have unique key columns in your results then it doesn't know how to identify row and you see empty condition.
Include unique key columns in the result and you will see correct SQL.

If you need to generate update script for some row/cell changes then you can make actual changes and then click on the "Script" button on the bottom toolbar.

**Comment by ramunozp** [comment]
thanks but:
1- the result if you have a key
2- Why does not it work to generate a SQL only of what I have selected, in this case, an UPDATE to the mnarcados fields?
3- the above works only in grid mode, if I change it to mode, it does not work.

**Comment by serge-rider** [comment]
You could write a feature request for that. Currently columns selection doesn't affect generated SQL, only selected rows make sense.
Also it doesn't work in plain text mode because this mode doesn't support cell selection at all.

**Comment by ramunozp** [comment]
thanx.
