### ISSUE TITLE
DBeaver not changing active database (PostgreSQL)

### ISSUE THREAD

**Issue by lrweck** [dbeaver/dbeaver#4095]
Hi,

Currently, I am not able to change the active database with DBeaver 5.1.6.

When I connect to a database with a default connection of, lets say, "postgres", right clicking on another database and on "Set active", does not make the current tab "sync" with the new database. Meaning I can't write SQL targeting the columns or schema of the new active database.

DBeaver error log doesn't show much, either:

![image](https://user-images.githubusercontent.com/26086198/44693824-a48af880-aa40-11e8-9d0b-046186ea755c.png)

If I change the default database on the connection options, I am again able to select on the tables I want.

I'm using JDBC driver 42.2

Let me know if you need something else.

**Comment by serge-rider** [comment]
This is PostgreSQL specific and happens only if you have option "Open separate separate connection for each editor" turned on.
In PG each database has its own physical connection and this connection has to be reopened when you change active database. We'll implement this in the next version.

Thanks for the bug report.
