### ISSUE TITLE
Data Transfer window keeps expanding when navigating with the Back/Next buttons

### ISSUE THREAD

**Issue by NekoKoneko** [dbeaver/dbeaver#4097]
With (almost) every click on the Back/Next button in the Data Transfer window, it expands to the right.

**Steps to reproduce:**
1. Select "Export Resultset" from the table context menu
2. Press the Next button multiple times until it gets disabled. On (almost) every click the window expands to the right.
3. Now repeat it with the Back button.
4. When the window client width reaches the screen width it stops expanding.

**Environment:**
DBeaver 5.1.6 x64
Windows 7 x64

**Comment by serge-rider** [comment]
Thanks for the bug report
