### ISSUE TITLE
In 5.1.6 Dark theme is broken

### ISSUE THREAD

**Issue by ssrebelious** [dbeaver/dbeaver#4098]
Using Linux with KDE after update from 5.1.5 to 5.1.6 I have to switch interface appearance from Dark theme to Classic, because Dark became a mix of Dark and Classic and in many places fonts have the same or almost the same colour as the background. For example in Preferences window text on buttons is unreadable because the label colour is from the dark theme and the button colour from the classic theme.

**Comment by serge-rider** [comment]
Try to delete lines "--launcher.GTK_version 2" from dbeaver.ini file.

**Comment by ssrebelious** [comment]
That helped, thanks!
