### ISSUE TITLE
"Custom Key" and "Use All Columns" broken in 5.1.6

### ISSUE THREAD

**Issue by n4nos** [dbeaver/dbeaver#4100]
Today i updated DBeaver to version 5.1.6 and now i can't update tables with no single primary key column.
The window "Possible multiple rows modification" appears with 3 Buttons "Custom Unique Key", "Cancel" and "Use all Columns".

When i click on Custom Unique Key there are no Columns to choose and when i click on Use All Columns an error appears:
`Can't change attribute 'config' - attributes of key '"PRIMARY"' are missing in result set`

The Problem exists on DBeaver 5.1.6 on Linux and Windows with connections to SQLite Databases.

**Comment by serge-rider** [comment]
Thanks for the bug report
