### ISSUE TITLE
Error not shown while truncating via right click

### ISSUE THREAD

**Issue by krilim** [dbeaver/dbeaver#4101]
When I truncate a table and this table has a foreign key referenced in another table MySQL output the error:

`ERROR 1701 (42000): Cannot truncate a table referenced in a foreign key constraint (mytest.instance, CONSTRAINT instance_ibfk_1 FOREIGN KEY (GroupID) REFERENCES mytest.mygroup (ID))`

If the truncate is performed via right click in table list the message is not shown anywhere... It does not say "OK" but neither say what happened.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
