### ISSUE TITLE
Formatting already formatted SQL code changes the format

### ISSUE THREAD

**Issue by michelvosje** [dbeaver/dbeaver#4105]
# How to reproduce.
1. Write some SQL code
```
insert into public.test (value2) values ('1'), ('2');
```
2. Format it using **Ctrl + Shift + F**.
 The code is formatted.
```
insert
	into
		public.test ( value2 )
	values ( '1' ),
	( '2' );
```
3. Format it again using **Ctrl + Shift + F**.
 The format changes in a slightly different format.
```
insert
	into
		public.test (value2)
	values ('1'),
	('2');
```
4. Format it again using **Ctrl + Shift + F**.
 The format is the same as in step 2.
```
insert
	into
		public.test ( value2 )
	values ( '1' ),
	( '2' );
```

DBeaver version: Current devel branch version and in 5.1.6.
OS: Windows 10
Driver: PostgreSQL

**Comment by serge-rider** [comment]
@michelvosje Thanks for the improvement!
