### ISSUE TITLE
can't backup or restore postgre db on  5.1.6

### ISSUE THREAD

**Issue by harrisyn** [dbeaver/dbeaver#4106]
after upgrading to version 5.1.6, 
I am unable to backup a database
error in backing up 
IO Error: Utility 'pg_dump.exe' not found in client home 'postgresql-x64-10'

when restoring, I get the error
IO Error: Utility 'pg_restore.exe' not found in client home 'postgresql-x64-10'

**Comment by serge-rider** [comment]
Thanks for the info, will try to reproduce with previous version upgrade.
Could you say why "that didn't work"? 
Generally pg_dump for PG 9.6 should work with 10+.

**Comment by harrisyn** [comment]
Just tried again, but I am unable to reproduce the issue.
What I had done before was.
1: Try to backup - IO Error: Utility 'pg_dump.exe' not found in client home 'postgresql-x64-10'
2: checked the directory that the PostgreSQL Binaries resolves to and found it was empty.
3: Attempt to Download drivers - Successful with version 9.6
4: checked the directory, and it had contents including pg_dump and pg_restore.
5: attempt to restore again - IO Error: Utility 'pg_dump.exe' not found in client home 'postgresql-x64-10'

So I uninstallled and reinstalled version 9.6, saw my previous directory options (home), selected the home for 10, and tested with success.

I later reinstalled 5.1.6 and tested again, checked the PostgreSQL Binaries folder again (it had contents), tried to download again, still gave me same error, so I manually added a new home; been working since.
I have just switched the home folder to PostgreSQL Binaries and it works.

I have no clue why it works now vs before. I am pretty sure I followed these exact steps.

Hope it helps

**Comment by serge-rider** [comment]
Thanks for details. This was clearly a bug in default client home detection (I believe it wasn't set in connection properties properly).

**Comment by techieroshan** [comment]
Still not working on verison 6.1.2

IO Error: Utility 'pg_restore.exe' not found in client home 'postgresql-x64-9.6'

**Comment by Luka234** [comment]
I've had similar problem on linux Mint. Problem was that I've install dbeaver 6.2.4 from Mint Software Manager, and dbeaver was installed **sandboxed** into **flatpak**. That means dbeaver didn't see my local postgres installation (/usr/bin). After installing dbeaver from https://dbeaver.io/download/ everything worked (I've set db client home to /usr/bin and it worked. You can also try /usr/lib/postgresql/1x/bin as described in https://github.com/dbeaver/dbeaver/issues/5421).

**Comment by a-bashtannik** [comment]
Confirm @Luka234 case - same shit for Ubuntu 18.04 and software center. Remove from snaps and install deb package.
