### ISSUE TITLE
Mock Data Generator - Can't find generator for id attribute; fails w/ error

### ISSUE THREAD

**Issue by imgntn** [dbeaver/dbeaver#4107]
Here's the definition of the id field on a model from sequelize

```         id: {
                type: DataTypes.UUID,
                defaultValue: DataTypes.UUIDV4,
                primaryKey: true
            }
```

when i try to generate mock data, it says

 ```Generators for the red highlighted attributes aren't found.  So, no data will be generated for them.``` 

I can't click on the generator field next to id, and then if you click the start button you get error

```
Error downloading client file(s)

Reason:

java.lang.NullPointerException
```

Does dbeaver support UUIDV4 as generator?   Am I doing something else wrong?  Thanks!

Thanks in advance for your time and your help!

![capture](https://user-images.githubusercontent.com/843228/44776161-489d9e00-ab2c-11e8-9f53-9f6ec3439311.PNG)

![capture](https://user-images.githubusercontent.com/843228/44776254-8b5f7600-ab2c-11e8-9cdd-508208b711c4.PNG)

**Comment by miroque** [comment]
agree

my table 

````
CREATE TABLE public.ftable (
	id int4 NOT NULL,
	"name" varchar(20) NOT NULL DEFAULT 'NA'::character varying
);
`````

also, wanted try mock generator

now red hints, all okey, but when I press "start generate" I see the same screen. "error downloading.. NullPointer"

The same confusing situation

**Comment by serge-rider** [comment]
NullPointerException in Mock data generator is a bug in 5.1.6 (it is already fixed, you can check the fix in EA version - https://dbeaver.io/files/ea).

**Comment by serge-rider** [comment]
UUID data type support will be added in MockData generators in version 5.2.
Thanks for bug report.
