### ISSUE TITLE
Feature request: Collapsing parts of SQL code

### ISSUE THREAD

**Issue by Speirs47** [dbeaver/dbeaver#4108]
It's not happening for me a lot but it might happen a lot for other people but currently I'm writing pretty big stored procedure (currently 257 lines but I'm not even in half of writing it). What would help to write and also read it in future is code collapsing feature so I can collapse SELECTs, IFs, WHILEs, etc.

Another useful thing would be to highlight clause's points. 
For example:
- when I "stand" in SELECT word it would highlight that word and also the semicolon which ends that clause
- when I "stand" in IF word it would highlight IF and ELSE/ELSEIF and END IF
- etc.

Oh. And maybe some "TODO" list which reads it's "contents" from comments beginning with "#TODO:"

**Comment by knwpsk** [comment]
Big fan of the Collapse request.  Used another editor that would do this (can't remember which one, probably TOAD for Oracle).  
Some nice features:
1. the editor would put a + sign at the top of a section of comments.  Pressing it would collapse all of the contiguous comment lines into a single dashed line.  Pressing it again would expand it.
2. the editor would put a + sign at the top of a section of SQL -- same behavior.  The "section" would typically be anything that could be easily discerned: a set of parentheses; the major sections of the query (SELECT, FROM, WHERE); any sub-query (again, parentheses)... etc.

I can think of some relatively easy alternatives, too:
- A "button" to "remove all newline (carriage return) characters in the selected section of code
- (and an UNDO for that!)

**Comment by datauduong** [comment]
I though Collapse feature have been implemented in 2017, but I was not able to find this. Please Confirm whether it is implemented.

**Comment by yrimal** [comment]
I'm on 6.0.0, windows, and it's available on Databases -> Editors-> SQL Editors-> Miscellaneous  (Folding Enabled).

**Comment by knwpsk** [comment]
yrimal is right, there is limited "folding" (collapse code) available, but it could be much better (more useful).  Today it only allows you to collapse an entire query.  Better if it would allow you to collapse smaller parts like:
- a whole sub-query within a larger query
- a long CASE statement
- the Select section of a query, but not the FROM and WHERE (like, when you know what fields you want and you're working on the joins and filters...)

The best implementation I've seen is to simply let you select any block of text you want, and collapse it (like hiding columns or rows in a spreadsheet)

**Comment by datauduong** [comment]
Hi @yrimal, Thank you. I have found the setting.

**Comment by knwpsk** [comment]
For anyone reading this... I found an interim "workaround".  In dBeaver, you can take a section of SQL code, and put it in a variable using the @set command.  Then you can call that variable in your query.  This is sortof like collapsing the code - makes it easier to read.  (It's also a handy trick if you repeat the same logic multiple times in your query -- for example, repeating the same CASE statement multiple times.)

Example:

@set FROMFIELDS = field1, field2, field3, field4, field5, CASE WHEN field6 = value1 THEN value2 ELSE value3 END  
/* this can be a very long string of stuff */

SELECT ${FROMFIELDS}
FROM table1
WHERE ... etc.

**Comment by kseniiaguzeeva** [comment]
The ticket duplicates #2156

**Comment by Alvaro-de-Lucas** [comment]
It would be great to be able to create "sections", from #beginSection ... to #endSection, so you can use those 2 tags to delimit the section and collapse whatever you want in between.
I think it's IntellyJ the one that has that functionality.... and it's really helpful

**Comment by samuele555** [comment]
So, is this implemented or not?
