### ISSUE TITLE
Unable to install office extension after upgrade to 5.1.6

### ISSUE THREAD

**Issue by Moggy6** [dbeaver/dbeaver#4110]
After upgrading to version 5.1.6 I tried to install the office extension to support export to .xlsx format. The installation failed with messages below:

An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.apache.commons.cli,1.3.1
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ce.feature,5.1.6.201808262133
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ce.nls.feature,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core.application,5.1.6.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core.application.nls,5.1.6.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core.nls,5.1.6.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.db2.nls,1.0.23.201808262133
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.db2.nls.feature,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.derby.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.erd.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.exasol.nls,1.0.23.201808262133
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.exasol.nls.feature,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.firebird.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.generic.nls,1.0.23.201808262133
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.generic.nls.feature,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.h2.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.hsqldb.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.import_config.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.informix.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.mockdata.nls,1.0.0.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.mssql.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.mysql.nls,1.0.23.201808262133
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.mysql.nls.feature,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.netezza.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.oracle.nls,1.0.23.201808262133
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.oracle.nls.feature,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.phoenix.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.postgresql.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.sample.database,1.0.28.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.sample.database.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.sqlite.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.teradata.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.ui.locks.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.vertica.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.wmi.nls,1.0.23.201808262133
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.wmi.nls.feature,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.model.nls,1.0.23.201808262133
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.rcp.feature,2.1.66.201808262133
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.rcp.nls.feature,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.runtime.ide.core.nls,1.0.23.201808262133
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.runtime.nls.feature,1.0.23.201808262133
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.standalone.feature,5.1.6.201808262133
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.standalone.nls.feature,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ui.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.utils.nls,1.0.23.201808262133
No repository found containing: osgi.bundle,org.jkiss.wmi.nls,1.0.23.201808262133

**Comment by serge-rider** [comment]
Could you try to delete artifacts.xml file in DBeaver install folder?

Note: in order to install extension you must run DBeaver with admin permissions if you have installed it in a standard location (like Program Files).

**Comment by Moggy6** [comment]
That worked, thank you!
