### ISSUE TITLE
Script tab name does not change when corresponding connection is edited.

### ISSUE THREAD

**Issue by VasilyMartynov** [dbeaver/dbeaver#4118]
**Required:**
Exsisting connection to DB, active db to connect to.

**Steps:**
1. Connect to DB, open new script editor tab
2. Note that sript tab include DB connection name
3. Open connection properties, edit ones name in General tab 
4. Save changes on connection properties, either reconnect to db or not on promt.

**Expected:**
Script tab changes name to match the new one of connection

**Otput:**
Name remains the same.

**Possible options:**
Rename tab only when reconnect is performed, to mark the fact that some newly edited properties of DB connections take effect only after reconnect.
____
Checked if the same issue was reported before, found nothing alike for around a year,  there is only request to add table name to script tab name.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
