### ISSUE TITLE
CSV Import

### ISSUE THREAD

**Issue by sudila** [dbeaver/dbeaver#4119]
Hi 
I`m trying to import CSV file into Impala DB
after importing 1 row I got an error 'Can not bind statement parameter'

![image](https://user-images.githubusercontent.com/29042801/44849459-daa7c280-ac62-11e8-861c-89e1aa4fed54.png)

![image](https://user-images.githubusercontent.com/29042801/44849694-9ff25a00-ac63-11e8-9f19-7a2b97d492e6.png)

![image](https://user-images.githubusercontent.com/29042801/44849763-d29c5280-ac63-11e8-8774-d08d658ffab0.png)

**Comment by serge-rider** [comment]
Can't reproduce. 
Does this happen always or only with some particular tables/CSVs?

**Comment by sudila** [comment]
I tried several csv files. it happens only when there are empty values in a file, although I market to set them as null.

![image](https://user-images.githubusercontent.com/29042801/45166033-c0d82380-b1fe-11e8-9a83-ffb08d68230b.png)

**Comment by serge-rider** [comment]
I've reproduced this. See fix in 5.2

**Comment by antonellyb** [comment]
I stil reproduce it in dbeaver 7.1.4 How to get the fix?

**Comment by antonellyb** [comment]
I reproduce it when importing to hive

**Comment by kseniiaguzeeva** [comment]
Please create a new ticket.
