### ISSUE TITLE
Can't edit and save values

### ISSUE THREAD

**Issue by ygoe** [dbeaver/dbeaver#4120]
DBeaver 5.1.6 on Windows 10.

When I select "Edit", "Edit cell" from the context menu of a table view, a new tab opens with the value. I can make changes to the cell value there.

Now things are getting unclear about how to apply the changes.

When I click the "X" button in the document tab header, I can confirm the question to apply the modified value in the cell. The editor tab then closes. Finally I can click the "Save" button in the bottom toolbar. That works fine.

But it's complicated. So I tried speeding it up. When I press Ctrl+S (for Save?) directly in the editor tab, the tab closes, the edited cell appears orange after deselecting, and the Save button is disabled. When I try to edit the cell value again, a different dialog opens and I don't know what it means. So that failed.

When I press Ctrl+F4 (Close document?) in the editor tab, the editor tab closes after I confirmed the changes by pressing Enter. But then the Save button also remains disabled. The Save button is only enabled when I close the editor tab with the mouse.

Am I doing something wrong? I'm just trying the most obvious and intuitive ways. I must admit that I haven't consulted a manual about this. And I feel I shouldn't have to.

**Comment by serge-rider** [comment]
I assume you are talking about CLOB/Text value editing.
Regular columns (string, numbers, timestamps, etc) scan be edited directly in the grid. Press enter or use context menu or use value view panel (press F7 or use bottom toolbar).

CLOB values also can be edited in panel editor (just double click on the cell).
If you open CLOB in a separate editor then you can save it by pressing ctrl+s or clicking on Save in the main menu or context menu.

There was a bug (#3692) with long CLOB values save (it doesn't become orange and Save button in bottom toolbar is disabled). It is already fixed (you can check the fix in EA - https://dbeaver.io/files/ea).

**Comment by ygoe** [comment]
Yes, it's a JSONB column in Postgres. That content is pretty lenghty and I need a wide editor box. I've already [activated line wrapping](https://stackoverflow.com/a/41179926/143684).

After some more testing, I found out that I can press Ctrl+S in the editor (which then closes without asking) and just blindly press Ctrl+S again in the table grid (which then commits the data, even though the Save toolbutton is still disabled). So the issue seems to be limited to the disabled Save button in the toolbar. Making any other change to the table enables the button and the data can be saved with a click. Before that, data can only be saved with a keypress.

What is EA?

**Comment by serge-rider** [comment]
EA is Early Access version. It contains all recent bugfixes.
