### ISSUE TITLE
5.1.6 The problem

### ISSUE THREAD

**Issue by lvtanxi** [dbeaver/dbeaver#4124]
I use dbeaver version is 5.1.6, I have some questions want to seek advice:
1, I selected a table click query when how to automatically select the long table in the database;
2, how all data migration from one database to another database.
3, in version 5.0 Panels show the number of query results in a set I don't know where to go, because I don't want to go to manually perform a

**Comment by serge-rider** [comment]
1. This is how you can control number of rows you see in results:
![image](https://user-images.githubusercontent.com/6398845/44922118-23d44100-ad4d-11e8-8e7f-e981db5b276f.png)

2. Data migration instructions: https://github.com/dbeaver/dbeaver/wiki/Data-transfer

3. I'm afraid I didn't understand the question
