### ISSUE TITLE
Oracle standard_hash Function

### ISSUE THREAD

**Issue by peterhatz** [dbeaver/dbeaver#4125]
Hi,

Searched the forums with no joy. Just wondering if anyone **is running Oracle 12c** and have come across the **standard_hash** function (returns a hash value of type MD5 in this case). The following is run from SQL*Plus & DBeaver (looks like  some encoding issues in DBeaver?):

`select  STANDARD_HASH('word', 'MD5') from dual`

Should be:
`C47D187067C6CF953245F128B5FDE62A`

In DBeaver, I get:
`»} pg¹°ê2E(Ê*`

Thanks!
Peter

**Comment by serge-rider** [comment]
You need to change binary data representation:

![image](https://user-images.githubusercontent.com/6398845/73119064-d671f880-3f6d-11ea-9711-3519d08a65a8.png)

![image](https://user-images.githubusercontent.com/6398845/73119067-df62ca00-3f6d-11ea-9b3a-bca5a38fc412.png)
