### ISSUE TITLE
Bug - Export Resultset to SQL Insert - Binaries: Hex, wrong values

### ISSUE THREAD

**Issue by JSkalskiSBG** [dbeaver/dbeaver#4126]
I got table with column: `attributes`, BLOB, NOT NULL (DB: MySQL)
I did export resultset from filtered table and it generated this code:
```
INSERT INTO items (player_id,sid,pid,itemtype,count,`attributes`) VALUES 
(1083505,101,3,2589,1,0x)
,(1083505,102,13,2589,1,0x)
,(1083505,103,101,2594,1,0x)
,(1083505,104,102,2594,1,0x)
;
```
When I tried to run it as query on other database, it returned error:

> Unknown column '0x' in 'field list'

I had to replace every '0x' with '0x0' to run query.

For me it looks like DBEaver bug.

**Comment by uslss** [comment]
Cannot reproduce it for now.
If issue is still actual for you - feel free to reopen the ticket

**Comment by XeonG** [comment]
Get this aswel.. if I use HeidiSQl the sql is exported properly with text values, and imports correctly.. with dbweaver it exports out binary and messes it up where it can't be imported at all
