### ISSUE TITLE
ResultView reset the active row to 1st after new query execution

### ISSUE THREAD

**Issue by surpavan** [dbeaver/dbeaver#4129]
Thank you for the keeping the wonderful software free - its value is great and support is unbelievably good.

When we execute a query and scroll down the result grid down (example some 100 rows) and re-execute the query -  the result view is not resetting to first row, it is show with 100th row where the scrollbar is last left.

**Comment by uslss** [comment]
already fixed.
ticket closed.
if the issue still actual for you - feel free to reopen the ticket
