### ISSUE TITLE
PostgreSQL - Data import from CSV file into a table fails

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#413]
I try to perform a data import from a csv file into a PostgreSQL table.

The steps I follow are:
- create a PostgreSQL table with several columns of several types;
- create a new connection to the directory where is the flat file . I use the "Flat files" driver and edit its properties to put ";" as separator. It works, I get one table per file with columns of type "String 32767";
- right clic on my destination PostgreSQL table and select "Import data"
- as "source", I select the table corresponding to the flat file I want to import. "Extraction settings" is set to "Single query";
- in the "Table mapping" window, I select the first line (the one with table names) and clic on "Columns mappings..." button => the mapping is OK, but target types are all set to "varchar(32767);
- I correct all the target types to fit to the postgresql columns types;
- clic on Next..., Next..., Finish.

There, I get the following error message:
Error occurred during (my postgresql table) data load
SQL Error [42P01]: L'élément du batch 0 INSERT INTO foret.arbres (idp,a,veget,simplif,acci,espar,ori,lib,forme,tige,mortb,sfgui,sfgeliv,sfpied,sfdorge,sfcoeur,c13,ir5,htot,hdec,decoupe,q1,q2,q3,r,age,v,w)
VALUES (500002,1,'0','0','0','03','1','2','1','1','0','0','0','0','','0',155.0,5.0,25.9,14.3,'1',0.0,9.0,1.0,0.0,130,2.068,14.14) a été annulé. Appeler getNextException pour en connaître la cause.

**Comment by ced75** [comment]
I tried again an import and get another error : nullpointer exception.
In dbeaver-debug.log, I read the following error message : 2016-05-24 13:13:00.931 - Data type 'String' not found in database 'website8'
In the mapping, I precised the target column types with "char(2)" for example.

**Comment by serge-rider** [comment]
Could you please post error stacktrace? You can get it in Error Log view.

**Comment by ced75** [comment]
java.lang.NullPointerException
java.lang.NullPointerException
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:133)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:113)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:104)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:66)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Session Data:
eclipse.buildId=unknown
java.version=1.7.0_101
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr_FR
Command-line arguments:  -os linux -ws gtk -arch x86_64

**Comment by serge-rider** [comment]
Thanks. I've fixed NullPointerException.
But import issue still remains, I guess..
I can build EA version for testing, if you need it.

**Comment by ced75** [comment]
Yes, I'm interested in testing it.
Thanks.

**Comment by serge-rider** [comment]
Ok
http://dbeaver.jkiss.org/files/ea/

**Comment by carlosjrcabello** [comment]
Serge,

Do those files contains last reported bugs about 3.6.8 release?

Anyway, I'll reinstall x64 to test it.

On Tue, May 24, 2016 at 1:43 PM, Serge Rider <notifications@github.com>
wrote:

> Ok
> http://dbeaver.jkiss.org/files/ea/
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/serge-rider/dbeaver/issues/413#issuecomment-221331875>
>



-- 
Atenciosamente,
Carlos Alberto Junior Spohr Poletto

carlos.inf.br

**Comment by carlosjrcabello** [comment]
Auto complete seems OK on 'dbeaver-ee-3.6.8-x86_64-setup.exe' build.


![screen222](https://cloud.githubusercontent.com/assets/637767/15512643/55789ce8-21b7-11e6-9b21-6aa92dbfd4ce.png)

**Comment by ced75** [comment]
OK, it seems better, but I get another bug (sorry!).
In the column mapping, I skip the first column.
This generates the following error:

Target attribute for [lib_ess] wasn't resolved.
org.jkiss.dbeaver.model.exec.DBCException: Target attribute for [lib_ess] wasn't resolved
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchStart(DatabaseTransferConsumer.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:206)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:113)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:104)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:66)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

lib_ess is the column in the source tables I configured to skip.

Thanks a lot for your help.

**Comment by serge-rider** [comment]
Is this still actual?

**Comment by kanadatec** [comment]
Even I have an issue where I have added the flat file via a connection and can see the file as a table, but when I try to import the CSV data into table, then I get the error:
![image](https://user-images.githubusercontent.com/33419151/39187308-93fde206-47ea-11e8-8502-3b497927e9ff.png)
 
And a data transfer error:
![image](https://user-images.githubusercontent.com/33419151/39187344-ae62fa50-47ea-11e8-9535-3054cfe8bac9.png)

Don't know why the error is occurring as I can open the CSV table connection just fine.

**Comment by uslss** [comment]
is this still actual on current version?

**Comment by kanadatec** [comment]
> Even I have an issue where I have added the flat file via a connection and can see the file as a table, but when I try to import the CSV data into table, then I get the error:
> ![image](https://user-images.githubusercontent.com/33419151/39187308-93fde206-47ea-11e8-8502-3b497927e9ff.png)
> 
> And a data transfer error:
> ![image](https://user-images.githubusercontent.com/33419151/39187344-ae62fa50-47ea-11e8-9535-3054cfe8bac9.png)
> 
> Don't know why the error is occurring as I can open the CSV table connection just fine.

Hi, I don't seem to be having this issue on the latest version, though I do not use the flat file connection method to import the data from CSV, I just use the CSV file option in the Import wizard.
