### ISSUE TITLE
Application each time show info about new version

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4130]
new 5.1.6 version is available. Application should show this info once.

next time it should show this info if 5.1.7 (next version) is available, 
**but not again and again about 5.1.6 version**

**Comment by serge-rider** [comment]
I see. You mean that you see announcements but you don't want to upgrade.
DBeaver checks for new version on application start and shows announcement only once per day.

You can disable it completely if you don't need new versions announcements (first page of database preferences).

Generally we can change current behavior and show this message less frequently. Once per week for example.

**Comment by KES777** [comment]
>You can disable it completely if you don't need new versions announcements
I still interested in announcements of new versions

>Once per week for example.
This is also boring to show same message twice.

To my mind the correct behavior would be to show announcement once for each time the new version is noticed.

**Comment by KES777** [comment]
hm... how `automatic updates check` for an application belongs to the database?

This is sooner belongs to `General`

**Comment by serge-rider** [comment]
I think we'll add checkbox "Don't show announce for version XXX" in new version info dialog.

**Comment by serge-rider** [comment]
Checkbox "Don't show for the version XXX" will be added in the next release

**Comment by KES777** [comment]
yes, this checkbox is added. But it has no matter I check it or not.
This `update version` window is not showed in any case

see attached video:

'https://user-images.githubusercontent.com/799021/132717132-82d81ad5-0cbd-49d4-8e6d-b9eb42452c17.mp4'
