### ISSUE TITLE
Red Squares instead of intended icons

### ISSUE THREAD

**Issue by Lonniebiz** [dbeaver/dbeaver#4133]
These icons show as red squares until the first time you click on them after each launching of Dbeaver:

![2018-08-31_002_1061x813](https://user-images.githubusercontent.com/151919/44923186-21ea8d80-ad0d-11e8-8164-4199aaa8cea9.png)

After you click on them, they do changed to the appropriate icons, but the next time you launch Dbeaver they become red squares again.

**Comment by serge-rider** [comment]
.dbeaver was used in version 3.x and earlier. You can remove it without any sorrow.
