### ISSUE TITLE
Formatting issues with certain oracle functions

### ISSUE THREAD

**Issue by kufii** [dbeaver/dbeaver#4134]
I've noticed some formatting issues with certain oracle functions. These functions use a keyword like FROM or ORDER BY within them and so the formatter seems to get confused.

## EXTRACT
Formatted by dbeaver:
```sql
SELECT
	EXTRACT( MONTH
FROM
	SYSDATE )
FROM
	dual
```

In my opinion more sensical formatting
```sql
SELECT
	EXTRACT( MONTH FROM SYSDATE )
FROM
	dual
```

## LISTAGG
Formatted by dbeaver:
```sql
SELECT
	CATEGORY,
	LISTAGG( COMMENT_TXT,
	', ' ) WITHIN GROUP (
ORDER BY
	ID )
FROM
	MYTABLE
GROUP BY
	CATEGORY
```
A nicer format, there's a bunch of ways this could be formatted though
```sql
SELECT
	CATEGORY,
	LISTAGG( COMMENT_TXT, ', ' )
		WITHIN GROUP (
			ORDER BY
				ID )
FROM
	MYTABLE
GROUP BY
	CATEGORY
```

## ROW_NUMBER
Formatted by dbeaver
```sql
SELECT
	ROW_NUMBER() OVER( PARTITION BY ID
ORDER BY
	SORT DESC ) rnum
FROM
	MYTABLE
```

A potential nicer format
```sql
SELECT
	ROW_NUMBER() OVER(
		PARTITION BY
			ID
		ORDER BY
			SORT DESC ) rnum
FROM
	MYTABLE
```

**Comment by serge-rider** [comment]
See fix in the next version.
