### ISSUE TITLE
CockroachDB driver

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#4140]
WE need CockroachDB driver.
It will utilize PostgreSQL extension with extra configration

**Comment by serge-rider** [comment]
Most of known problems are referenced in https://github.com/cockroachdb/cockroach/issues/28309

- Database structure  browser adapted to Cockroach.
- Table DDL reading fixed.
- JDBC resulset limit issue resolved

**Comment by awoods187** [comment]
Filed an issue: https://github.com/dbeaver/dbeaver/issues/4156

**Comment by awoods187** [comment]
One of our engineers ran into a few bugs: https://github.com/dbeaver/dbeaver/issues/4157

**Comment by serge-rider** [comment]
@awoods187 replied in #4157

Initial version is ready and will be included in 5.2.
Further improvements/bug should be tracked in separate tickets.
