### ISSUE TITLE
DBeaver 5.1.6 for windows

### ISSUE THREAD

**Issue by IsraelDD** [dbeaver/dbeaver#4143]
When I click the icon to start DBeaver 5.1.6 it show that was unable to locate its companion Launcher jar.

I searched the whole folder of the program, and the referenced jar file isn´t there, what can be done ?
![2018-09-03](https://user-images.githubusercontent.com/42937060/44987202-bf87cc00-af5c-11e8-96a2-fab820ce9fac.png)

**Comment by serge-rider** [comment]
- How did you install DBeaver (installer/zip file)?

If you used installer please check that there are *.jar files in `plugins` folder. If there are no jar files then you could try to reinstall DBeaver or use zip archive distribution (in that case you will need to install Java separately).

**Comment by IsraelDD** [comment]
Success!!
Now I downloaded the zip file and extracted to the DBeaver folder, and really there is a lot more files on the zip than the exe installer, installed the [64 bit java version](https://sdlc-esd.oracle.com/ESD6/JSCDL/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jre-8u181-windows-x64.exe?GroupName=JSC&FilePath=/ESD6/JSCDL/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jre-8u181-windows-x64.exe&BHost=javadl.sun.com&File=jre-8u181-windows-x64.exe&AuthParam=1535983660_47f50bfd93ffa042821be1659739577f&ext=.exe) and started directly the 

> ...\DBeaver\plugins\org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar 

because the

> ...\DBeaver\DBeaver.exe doesn´t start.

**Comment by serge-rider** [comment]
Weird. Perhaps something went wrong during install process. 
Maybe manual remove + reinstall might help. 

Anyhow - thank for the info
