### ISSUE TITLE
MSSQL date columns stop working after 200 rows

### ISSUE THREAD

**Issue by fer22f** [dbeaver/dbeaver#4147]
Version: 5.1.6

On the first result set, everything works as expected, however, when it attempts to fetch more, it ends up converting something, and generates a bunch of warnings:
![image](https://user-images.githubusercontent.com/3057302/45032852-2b376b00-b029-11e8-8453-e0ab1b59efc2.png)
Here is how that looks:
![image](https://user-images.githubusercontent.com/3057302/45032752-fb886300-b028-11e8-8da1-65a86f76b3ba.png)
Been this way since 5.1.3 or 5.1.2, I don't recall correctly, but it did work before.

**Comment by serge-rider** [comment]
Can't reproduce. Could you post table DDL or at least exeact column type?
Also what driver do you use (jTDS or Microsoft)?

**Comment by fer22f** [comment]
@serge-rider Ah, those columns are `datetimeoffset` and I'm using jTDS. I've just tried it and `datetime` does work correctly, the problem is with `datetimeoffset`.

**Comment by serge-rider** [comment]
Yep, it is a bug in MSSQL datetimeoffset data type processing (because originally it was fetched as varchar type).
See fix in the next version.

**Comment by fer22f** [comment]
Thanks!
