### ISSUE TITLE
In the new table designer for sqlite, autoincrement key columns are ignored in the generated ddl.

### ISSUE THREAD

**Issue by chriseaton** [dbeaver/dbeaver#4152]
In the "new table" designer for sqlite, autoincrement is ignored in the generated ddl, resulting in a table without that property on the column.

dbeaver 5.1.6.201808262133

![image](https://user-images.githubusercontent.com/5247568/45075619-91110a80-b09c-11e8-8849-2ad960093c5d.png)

![image](https://user-images.githubusercontent.com/5247568/45075633-9d956300-b09c-11e8-8a74-becd1d77808e.png)

**Comment by serge-rider** [comment]
We don't support SQLite-specific DDL yet.

**Comment by uslss** [comment]
implemented in 7.2.2
