### ISSUE TITLE
BUG: Export Database Table fails between Redshift DB's (DBeaver 5.1.6)

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#4154]
Getting this error when trying to export table "NEWTABLE" (**with create option**) between Redshift DBs:

"Can't start data transfer

Reason:
New table "NEWTABLE" not found in container "

The table was created in destination DB but the insert failed.

**Comment by cscetbon** [comment]
I got the exact same behavior. @yonisade, were you able to fix it ?
