### ISSUE TITLE
Feature Request: Shortcut key for creating a new table

### ISSUE THREAD

**Issue by priyankmaniar** [dbeaver/dbeaver#4155]
Thanks for making DBeaver. I love it. I've found few enhancements that could improve the user experience.

1. I'm not able to find anywhere shortcut key to create a new table.
2. Shortcut key for creating a new column in the table
3. If possible, when you create a new column, if the column1 text is selected by default. It will help users to quickly just type in the new table name.
4. Duplicate column (along with a shortcut key)
5. When we copy and paste a table. The constraint & foreign keys are still named as per the last table name. It could be named based on the new table name provided (may be just before saving, when the save is clicked).

**Comment by serge-rider** [comment]
We have one action/shortcut for new object creation (including new tables creation) - "Create Object".
You can assign any shortcut to it:

![image](https://user-images.githubusercontent.com/6398845/45351623-4a04a700-b5bf-11e8-897b-e46ba0228b1b.png)

**Comment by serge-rider** [comment]
I think it makes sense to create separate ticket for each feature request or bug report. 
Otherwise it is very hard to track tasks.
