### ISSUE TITLE
CockroachDB driver fails in a few areas 

### ISSUE THREAD

**Issue by awoods187** [dbeaver/dbeaver#4157]
setup:
create local insecure cluster
restore tpcc fixtures into it
connect with dbeaver
username: "root"
password ""

when looking at a table:
entity relationship diagram fails
![image](https://user-images.githubusercontent.com/22278911/45111291-a6288080-b112-11e8-9b13-15938fd44058.png)

foreign keys tab doesn't work
![image](https://user-images.githubusercontent.com/22278911/45111311-b3456f80-b112-11e8-8f12-8eabb2c06f98.png)

indexes tab doesn't work
![image](https://user-images.githubusercontent.com/22278911/45111320-b6d8f680-b112-11e8-812a-626a7aa259ba.png)

references tab doesn't work
![image](https://user-images.githubusercontent.com/22278911/45111337-c0faf500-b112-11e8-865b-492bd8296692.png)

DDL tab doesn't work
![image](https://user-images.githubusercontent.com/22278911/45111346-c48e7c00-b112-11e8-9428-b4c58920c4e7.png)

constraints tab doesn't work
![image](https://user-images.githubusercontent.com/22278911/45111354-c8220300-b112-11e8-9b64-8c74bb5b2de7.png)

**Comment by serge-rider** [comment]
Looks like almost all table objects loading failed. Maybe all these errors have the same nature.
Please post error/debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files).

**Comment by awoods187** [comment]
Tried reproing today and couldnt so i'll close this for
