### ISSUE TITLE
SELECT INTO bug has returned

### ISSUE THREAD

**Issue by scotausborn** [dbeaver/dbeaver#4158]
This issue was previously addressed a couple of times.  In short, tables created using the SELECT INTO syntax are being limited by the result set size specified in the SQL editor.

**Comment by scotausborn** [comment]
Vertica – driver is the 8.1.1-7 jar.

**Comment by serge-rider** [comment]
I think we lost this config when we migrated to the new Vertica extension/driver.
Thanks for the bug report
