### ISSUE TITLE
Highlight all instances of a given word...

### ISSUE THREAD

**Issue by spinjector** [dbeaver/dbeaver#4159]
Notepad++ has a nice word-finding feature where instances of a highlighted word are automatically highlighted elsewhere throughout the document.

Note that I refer to highlight in the sense of word selection, that being Ctrl+Shift+Right or double-clicking a word, not like Microsoft Word where there's a text formatting element like bold or font color.

I was thinking it could be implemented a couple of ways. The most basic as in Notepad++: just highlight a word and the rest auto-magically highlight themselves. But also it could be done on the Find window, such as a new button called &Highlight All. And of course don't forget the little colored lines in the vertical scroll bar to show where there may be instances of highlighted words that are off-screen.

**Comment by serge-rider** [comment]
Duplicate of #222
