### ISSUE TITLE
Arabic displayed on query window is not correct.

### ISSUE THREAD

**Issue by neway003** [dbeaver/dbeaver#4161]
With reference to the attached image.
I have created a stored procedure in PGAdmin3.
Opened the same stored procedure in DBeaver-5.1.6.20.

both are showing in different mode. Accurately shown on PGAdmin.

![1](https://user-images.githubusercontent.com/5653038/45145031-b2731300-b1d0-11e8-9553-9d605a4bd2d5.JPG)

For testing you can use below stored procedure.

```
CREATE OR REPLACE FUNCTION sp_update(testdata text)
  RETURNS void AS
$BODY$
BEGIN
	UPDATE tbl SET datacol = translate(testdata,'٠١٢٣٤٥٦٧٨٩ابحدرسصطعقكلمنهوى', '0123456789ABJDRSXTEGKLZNHUV');
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION sp_update(integer)
  OWNER TO postgres;
```

Here in github also showing wrongly.
When you copy the code to PGAdmin it will be different.

**Comment by serge-rider** [comment]
I can't realize how correct query should look. 
And I can't realize how the posted query can turn into the one you see in PG, looks like a kind of magic :)

In Windows Notepad I see the same text as in the web page or in DBeaver.

**Comment by neway003** [comment]
The query should be like what you can see in PG admin query window, because in translate function three parts are there

`translate(input_string_to_be_translated, matching_string, replacing_string)`

Here matching string contain arabic numeral and characters.

> '٠١٢٣٤٥٦٧٨٩ابحدرسصطعقكلمنهوى'

and replacing string is

>'0123456789ABJDRSXTEGKLZNHUV'

but its showing only "number" in one group and "arabic alphabet, arabic number, english alphabet" are in another group.

When you try to remove characters from the end by backspace you can Identify different groups.

**Comment by serge-rider** [comment]
Also you could try to switch whole DBeaver into right-to-left mode (it will affect all controls).
Use command line parameter `-dir rtl` or add lines
```
-dir
rtl
```
in dbeaver.ini file (before -vmargs line)

**Comment by neway003** [comment]
Thank you for the reply.
using RTL for this small thing will be more confusing. :)
