### ISSUE TITLE
Saved filter settings lost between restarts

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#4166]
When viewing table data there is a filter input box and among the buttons is one called "Save filter settings for current object":

![dbeaver-filter](https://user-images.githubusercontent.com/11840364/45211218-009c1b00-b292-11e8-9d84-5ec8f5b60e63.png)

When I use this to save a filter then the filter is remembered only until I close DBeaver. When I start it again the saved filter is lost. Is this intended or a bug?

I think the filter settings should be saved permanently for future use until I delete them. It would be great if multiple filters could be saved and could be later accessed from the drop-down menu. And then some mechanism for deleting unneeded filters would be useful - for example an 'X' icon in the drop-down list next to each saved filter.

**Comment by serge-rider** [comment]
Yes, filter settings must be permanent (they are kept in `saved-data-filter.xml` file in workspace metadata). So this looks like a bug.
But I can't reproduce this bug. At least with simple DBeaver restart. Maybe some other actions are required.

**Comment by serge-rider** [comment]
Regarding filers history save/manager. It is already working (previous filter values are available in drop-down box). But it is not persistent in CE version. Because we keep previous filter values in Query Manager database (in embedded H2 engine). And it is available only in EE version. Perhaps we will include it in CE version too.

**Comment by lemon-juice** [comment]
Sorry, the file is there. The Windows Explorer search results are quite messy and I didn't notice it initially.

**Comment by lucasvc** [comment]
Could you clarify @serge-rider, that
> But it is not persistent in CE version.

Means that storing a filter in CE version **will not survive restarts**, even the (windows) file `%APPDATA%\DBeaverData\workspace6\.metadata\.plugins\org.jkiss.dbeaver.core\saved-data-filter.xml` it is updated.

Thanks!

**Comment by serge-rider** [comment]
saved-data-filter.xml keeps information about filters/orderings for a table. It is updated once you click "Save filter settings" buttons. 
But it doesn't keep filters history.

**Comment by lucasvc** [comment]
And **what about restarts**?
In the file there is stored the last, which would fit my needs.
But it is not appearing/filtering by default in my UI.

**Comment by bmscmoreira** [comment]
Yes - restarting and keeping the last applied filter would be a great feature as well for the CE edition.

**Comment by dimgel** [comment]
Right now for me (CE 7.0.2, linux/amd64, PostgreSQL) saved filters were PARTIALLY restored which is more weird if they weren't at all:

http://dimgel.me/drop/dbeaver/bug-filter-before-restart.png
http://dimgel.me/drop/dbeaver/bug-filter-after-restart.png

(sorry, could not attach screenshots to this comment: "something went wrong").

**Comment by shaun-ba** [comment]
So as of version "Version 7.2.1.202009201907" is this still broken?

I've just spent half hour organising a filter, all the columns ordering and such, clicked save filter but cannot find a button to change to the saved filter??

All I want to do is order columns, I don't think that should be such a difficult feature, is this not possible with DBeaver?
