### ISSUE TITLE
Feature request: Manual commit - read rollbacked

### ISSUE THREAD

**Issue by elcasa** [dbeaver/dbeaver#4168]
Feature request: is it possibile to have a new mode of manual commit with all the select query automatically rollbacked? 
It is a little odd that when you launch a select * from dual you have 1 in the statement to commit or rollback.

I know that it is made on purpose (issue #1510) but for someone who use it in manual commit, launching a select and an update query and seeing 2 transaction to commit is a little odd and may scare and confuse newbie users, that is the reason why I'm not suggesting dbeaver to my younger colleagues. Furthermore it is unusual to launch a select to be committed, Oracle functions should not write and Oracle procedure should be launched in a Declare Begin End block.

It is also safe because an auto rollback on select prevent any possible lock

**Comment by serge-rider** [comment]
Agreed, this makes sense. 
Also I think we should rename "Modifying statements" to something less frightening.
Also this new mode should be enabled for some database (maybe even for Oracle) by default.

**Comment by tati-kru** [comment]
Having third txn mode would be quite weird.

Another proposal: we can show 2 txn numbers: total statements/modifying statements

**Comment by serge-rider** [comment]
This feature will be implemented in #1562 
And we already have two statement counters.
