### ISSUE TITLE
Select data source - Typing directly after dialog open could auto start filtering

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#4173]
OS: Windows 10
DBeaver version: 5.1.6

Description:
I am used to open a dialog and then start typing to start filtering without having to Shift+Tab etc to get to the filtering part. Once the dialog opens it would be awesome that "on typing...filter by what is being typed". This eases the use a bit. Clearing can be as simple as Esc once to clear the filter. If no filter and Esc is pressed then close dialog.

**Comment by serge-rider** [comment]
Agreed
