### ISSUE TITLE
Table name filling based on anywhere search rather than starts with

### ISSUE THREAD

**Issue by surpavan** [dbeaver/dbeaver#4176]
When we use an alias for the table and a '.' dot -  we are getting the list of tables and that is great.
When we type after the dot - we are getting the list of tables that are starting with the letters we typed after the dot.

Can we modify this functionality to fill in the tables names that are containing the word/letter sequence we type - i.e. change from 'starts by' criteria to '%letters%' criteria in table name.  This willl make the most use out of it.

**Comment by surpavan** [comment]
ctrl-space is only searching first/starting characters; the new requirement is to fill with search anywhere instead of just the starting.

**Comment by serge-rider** [comment]
@surpavan 
![sql_ctrl_space](https://user-images.githubusercontent.com/6398845/46188586-bf2be800-c2f2-11e8-8272-817d1c74ddd6.gif)

**Comment by surpavan** [comment]
Thank you very much for the time, it might have been an issue on my system, after the new upgrade I am able to get the names this way, earlier I did not get them. That is why I closed the issue/question.
Thank you very much for the great product.
