### ISSUE TITLE
"Linux RPM package 64 bit (installer)" can not be installed

### ISSUE THREAD

**Issue by benborba** [dbeaver/dbeaver#4177]
kernel version: 4.17.19-200.fc28.x86_64

checksum passed,  md5 : f6760453aa9e657ea0593180cd86eeea
when execute "**rpm -Uvh dbeaver-ce-latest-stable.x86_64.rpm**" as root, crashed and report error:
```
error: dbeaver-ce-latest-stable.x86_64.rpm: tag[34]: BAD, tag 1096 type 5 offset 48168 count 745 len 2980
error: dbeaver-ce-latest-stable.x86_64.rpm cannot be installed
```

**Comment by serge-rider** [comment]
Can't reproduce (at least it woks fine on CentOS 7). What is your Linux version?

**Comment by mjclopes** [comment]
I have the same problem in Fedora 28

**Comment by Atem18** [comment]
@serge-rider I can also confirm it for Fedora 28, can't install it either by rpm or dnf.

**Comment by Stenfrank** [comment]
the same thing happens in fedora 28:

error: dbeaver-ce-5.2.0-stable.x86_64.rpm: tag[34]: BAD, tag 1096 type 5 offset 48168 count 745 len 2980
error: dbeaver-ce-5.2.0-stable.x86_64.rpm no puede ser instalado

**Comment by ruimigueltrigo** [comment]
Same problem: Fedora 28, trying to upgrade DBeaver 5.1.2 to 5.2.0.

`$ sudo rpm -V Downloads/dbeaver-ce-5.2.0-stable.x86_64.rpm 
error: Downloads/dbeaver-ce-5.2.0-stable.x86_64.rpm: tag[34]: BAD, tag 1096 type 5 offset 48168 count 745 len 2980
error: Downloads/dbeaver-ce-5.2.0-stable.x86_64.rpm: not an rpm package (or package manifest)`

```
$ sudo rpm -U Downloads/dbeaver-ce-5.2.0-stable.x86_64.rpm 
error: Downloads/dbeaver-ce-5.2.0-stable.x86_64.rpm: tag[34]: BAD, tag 1096 type 5 offset 48168 count 745 len 2980
error: Downloads/dbeaver-ce-5.2.0-stable.x86_64.rpm cannot be installed
```

**Comment by benborba** [comment]
> Can't reproduce (at least it woks fine on CentOS 7). What is your Linux version?

Fedora release 28 (Twenty Eight)
OpenJDK Runtime Environment (build 1.8.0_181-b13)

**Comment by Alexis6307** [comment]
Same here

Fedora release 28 (Twenty Eight)
RPM version 4.14.2

**Comment by Rezequiel** [comment]
> I have rebuilt rpm for EA version, it uses newer version of redline RPM packager.
> Could you test it? (https://dbeaver.io/files/ea/dbeaver-ce-5.2.1-stable.x86_64.rpm)

I tested, this was the output during the updating/installing:

`error: rpmdbNextIterator: skipping h#   14250 tag[34]: BAD, tag 1096 type 5 offset 45480 count 705 len 2820
error: rpmdbNextIterator: skipping h#   14250 tag[34]: BAD, tag 1096 type 5 offset 45480 count 705 len 2820
error: rpmdbNextIterator: skipping h#   14250 tag[34]: BAD, tag 1096 type 5 offset 45480 count 705 len 2820
Verifying...                          ################################# [100%]
Preparing...                          error: rpmdb: damaged header #14250 retrieved -- skipping.
error: rpmdb: damaged header #14250 retrieved -- skipping.
error: rpmdb: damaged header #14250 retrieved -- skipping.
################################# [100%]
Updating / installing...
   1:dbeaver-ce-0:5.2.1-stable        ################################# [100%]`

Then I tried open Dbeaver and open it without a problem. In About section shows the 5.2.1 version.
I'm also on Fedora 28 and RPM ver.  4.14.2.

In the output, the "damaged header #14250" part was repeated a lot of times.

**Comment by serge-rider** [comment]
Well, at least it is working. I'll see what else I can do with these warnings..

**Comment by Atem18** [comment]
@serge-rider no problem while installing it for me with dnf and I am also using Fedora 28 and RPM v 4.14.2:
```
❯ sudo dnf install Downloads/dbeaver-ce-5.2.1-stable.x86_64.rpm 
Last metadata expiration check: 2:10:39 ago on Wed 12 Sep 2018 03:48:48 PM CEST.
Dependencies resolved.
=================================================================================================================================================================================================================
 Package                                           Arch                                          Version                                               Repository                                           Size
=================================================================================================================================================================================================================
Installing:
 dbeaver-ce                                        x86_64                                        5.2.1-stable                                          @commandline                                         53 M

Transaction Summary
=================================================================================================================================================================================================================
Install  1 Package

Total size: 53 M
Installed size: 61 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                         1/1 
  Installing       : dbeaver-ce-5.2.1-stable.x86_64                                                                                                                                                          1/1 
  Running scriptlet: dbeaver-ce-5.2.1-stable.x86_64                                                                                                                                                          1/1 
  Verifying        : dbeaver-ce-5.2.1-stable.x86_64                                                                                                                                                          1/1 

Installed:
  dbeaver-ce.x86_64 5.2.1-stable                                                                                                                                                                                 

Complete!

~ 24s
```

And everything is working when I am running it. Thanks for the fix !

**Comment by Alexis6307** [comment]
> Well, at least it is working. I'll see what else I can do with these warnings..

Yep, working fine. Thank you very much!

**Comment by mjclopes** [comment]
Fedora release 28 (Twenty Eight)
RPM version 4.14.2

dbeaver-ce-5.2.1-stable.x86_64.rpm working fine now, thanks

**Comment by benborba** [comment]
Thanks ! 
But my situation is a little different from others.

with RPM:
```
# rpm -Uvh dbeaver-ce-5.2.1-stable.x86_64.rpm 
error: rpmdbNextIterator: skipping h#   12341 tag[34]: BAD, tag 1096 type 5 offset 45480 count 705 len 2820
error: rpmdbNextIterator: skipping h#   12341 tag[34]: BAD, tag 1096 type 5 offset 45480 count 705 len 2820
error: rpmdbNextIterator: skipping h#   12341 tag[34]: BAD, tag 1096 type 5 offset 45480 count 705 len 2820
Verifying...                          ################################# [100%]
Preparing...                          error: rpmdb: damaged header #12341 retrieved -- skipping.
error: rpmdb: damaged header #12341 retrieved -- skipping.
...... (over 350 lines of the same message)
error: rpmdb: damaged header #12341 retrieved -- skipping.
################################# [100%]
Updating / installing...
   1:dbeaver-ce-0:5.2.1-stable        ################################# [100%]
```

with DNF(v2.7.5):
```
# dnf reinstall ./dbeaver-ce-5.2.1-stable.x86_64.rpm 
error: rpmdbNextIterator: skipping h#   12341 tag[34]: BAD, tag 1096 type 5 offset 45480 count 705 len 2820
Last metadata expiration check: 1:54:45 ago on Thu 13 Sep 2018 02:38:36 PM CST.
Dependencies resolved.
==============================================================================================================================================================
 Package                              Arch                             Version                                   Repository                              Size
==============================================================================================================================================================
Reinstalling:
 dbeaver-ce                           x86_64                           5.2.1-stable                              @commandline                            53 M

Transaction Summary
==============================================================================================================================================================

Total size: 53 M
Is this ok [y/N]: 
```
there is an error in dnf execute result too.

**Comment by Atem18** [comment]
@benborba and if you uninstall, clean and install, is it the same ?

**Comment by dmitrii-zolotarev** [comment]
> I have rebuilt rpm for EA version, it uses newer version of redline RPM packager.
> Could you test it? (https://dbeaver.io/files/ea/dbeaver-ce-5.2.1-stable.x86_64.rpm)

It works fine on Fedora 28. Thank you very much

**Comment by kurdt2507** [comment]
> I have rebuilt rpm for EA version, it uses newer version of redline RPM packager.
> Could you test it? (https://dbeaver.io/files/ea/dbeaver-ce-5.2.1-stable.x86_64.rpm)

Everything worked fine with dbeaver-ce-5.2.1-stable.x86_64, thank you very much.

**Comment by Atem18** [comment]
@benborba maybe it's because you installed directly via rpm and not via dnf
