### ISSUE TITLE
rpm can't be installed

### ISSUE THREAD

**Issue by kurdt2507** [dbeaver/dbeaver#4182]
Hi, I have a problem updating dbeaver CE through the RPM package; I get the following message:
error: dbeaver-ce-5.2.0-stable.x86_64.rpm: tag[34]: BAD, tag 1096 type 5 offset 48168 count 745 len 2980.
I have Fedora 28 to 64 bits.
Thanks in advance.

**Comment by serge-rider** [comment]
Duplicate of #4177
