### ISSUE TITLE
Firebird EXECUTE BLOCK not recognized at all

### ISSUE THREAD

**Issue by Evil2000** [dbeaver/dbeaver#4188]
When using the EXECUTE BLOCK statement an error is thrown, even when I remove the SET TERM statement:
![grafik](https://user-images.githubusercontent.com/697191/45349889-d65c9d00-b5b2-11e8-9a95-f703bb6b5aac.png)
It seems that dbeaver is not able to treat this statement at all.

**Comment by serge-rider** [comment]
You can't use simple SELECT queries in FB blocks. Use SELECT/FROM/INTO.
This works fine:
```sql
SET TERM #;

EXECUTE BLOCK
AS
    DECLARE var_x INT = 0;
    DECLARE zzz INT = 0;
BEGIN
    SELECT "RDB$CHARACTER_SET_ID" FROM RDB$CHARACTER_SETS WHERE RDB$CHARACTER_SET_ID = :var_x INTO :zzz;
END

SET TERM ;#
```

**Comment by Evil2000** [comment]
Ahh. Thanks.
Sorry for wasting your time this way.
