### ISSUE TITLE
CheckTrust phase error

### ISSUE THREAD

**Issue by Moggy6** [dbeaver/dbeaver#4189]
After installing version 5.2.0.201809092115 I am getting the below error when attempting to install the office extension:

An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
Error reading signed content.
Exception in opening zip file: C:\Program Files\DBeaver\plugins\org.jkiss.bundle.apache.poi_3.16.0

**Comment by serge-rider** [comment]
Seems to be a duplicate of #3624 (and probably #3996 too)
Could you try to remove previous version of DBeaver completely and reinstall it again?

**Comment by Moggy6** [comment]
I deleted the artifacts.xml and it worked fine.

**Comment by serge-rider** [comment]
Thanks for info.
I'll add force delete of this file in Windows installer (this file remains from previous DBeaver version).
