### ISSUE TITLE
CockroachDB: Error synchronizing with database (SQL Error 42p01)

### ISSUE THREAD

**Issue by awoods187** [dbeaver/dbeaver#4192]
Hi,

A user of ours gave this quote and screenshot:

"I have had a bit of a play and it connects to an insecure installation OK. Was able to create a new database and do an INSERT and a SELECT. However as soon as I start trying to use the grids to edit any data I get the attached error."

![image](https://user-images.githubusercontent.com/22278911/45361076-511bbd00-b59f-11e8-8182-e62748ab07ed.png)

You can find it on our forum at https://forum.cockroachlabs.com/t/finally-a-gui-like-pgadmin-as-soon-as-possible/1364/20

**Comment by serge-rider** [comment]
You can see in the main toolbar that current database is system. I'm quite sure that table public.accounts resides is in demo database.

Active database can be switched in the main toolbar or using context menu in the database navigator.

**Comment by awoods187** [comment]
I think we could probably close this since no follow up has been heard
