### ISSUE TITLE
[Firebird 2.5] Can't open Procedures entity

### ISSUE THREAD

**Issue by ebolefeysot** [dbeaver/dbeaver#4194]
Hi
I can't open any procedures with firebird 2.5 driver.
I did a standart 32b installation and allow dbeaver to download firebird driver.

Reason:
org.jkiss.dbeaver.ext.firebird.model.FireBirdDataSource cannot be cast to org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer

**Comment by serge-rider** [comment]
It is a bug in procedures manager (Generic driver)
Thanks for the bug report.
