### ISSUE TITLE
no foreign keys displayed in DDL nor in the FK tab for Postgres tables with the Generic driver

### ISSUE THREAD

**Issue by gogosofta** [dbeaver/dbeaver#4195]
I recently noticed that DBeaver has stopped extracting FK information while using the Generic PostgreSQL driver. 
Might be a regress, might be a feature, but the standard driver ceased to work for us long time ago because of the very big metadata in our DBs and now this happens to be a very nasty issue.

**Comment by serge-rider** [comment]
Yes, it was a change in Generic metadata reading in one of recent versions. Some drivers (including PG driver) provide catalog information but it can't be used in metadata queries.
You can fix this by enabling "omit-single-catalog" driver parameter:
![image](https://user-images.githubusercontent.com/6398845/45417054-f57a2e00-b689-11e8-96e7-a05d46e86111.png)

I'll fix default configuration in the next version, thanks for the bug report.

**Comment by serge-rider** [comment]
BTW could you say why you don't use default PG driver?
We did quite a lot of performance improvements there recently.

**Comment by gogosofta** [comment]
> BTW could you say why you don't use default PG driver?
> We did quite a lot of performance improvements there recently.

I will give it a try, but the reason was a bug that I've reported before - DBeaver used to hang on loading huge amount of metadata objects.

**Comment by gogosofta** [comment]
Could you please also add a the ability to change driver type from Generic to Standard and vice-versa so I don't have to manually edit/replace things in the data sources file? :)

**Comment by serge-rider** [comment]
It is already supported (main menu Database:
![image](https://user-images.githubusercontent.com/6398845/45475524-59156180-b745-11e8-92ce-c6f3998291f6.png)

**Comment by gogosofta** [comment]
Great stuff ! Thanks! ;)
