### ISSUE TITLE
Schema names not listed in the "Active catalog/schema" combo box for PostgreSQL Generic driver

### ISSUE THREAD

**Issue by gogosofta** [dbeaver/dbeaver#4196]
It's impossible to change the active schema from the "Active catalog/schema" selector in the latest DBeaver versions - schemas are not listed in the popup dialog when using PostgreSQL Generic driver.

**Comment by serge-rider** [comment]
I think it is the same problem as in #4195 (see workaround in comments).
Although I'd recommend to use the standard PostgreSQL driver.
