### ISSUE TITLE
Rollback shortcut

### ISSUE THREAD

**Issue by surpavan** [dbeaver/dbeaver#4197]
The shortcuts list is handy too -  but can we have a quick simple shortcut for 'ROLLBACK' and 'COMMIT' -  4 key combination or frequently used options might not be good -  might be a F11 and f12 might be good - but your choice.

Or even Ctrl + Backspace for rollback is good.

**Comment by serge-rider** [comment]
The problem with default shortcuts is that we have to support multiple platform + we can't conflict with default shortcuts in Eclipse IDEs.
<kbd>CTRL+Backspace</kbd> is already reserved for "Delete last word" in SQL editor.

Anyhow - you can set your own shortcuts for the most of existing DBeaver actions:

![image](https://user-images.githubusercontent.com/6398845/45417485-efd11800-b68a-11e8-8544-152b5f4fe85d.png)

**Comment by surpavan** [comment]
> 
> 
> The problem with default shortcuts is that we have to support multiple platform + we can't conflict with default shortcuts in Eclipse IDEs.
> CTRL+Backspace is already reserved for "Delete last word" in SQL editor.
> 
> Anyhow - you can set your own shortcuts for the most of existing DBeaver actions:
> 
> ![image](https://user-images.githubusercontent.com/6398845/45417485-efd11800-b68a-11e8-8544-152b5f4fe85d.png)

This saved me the day -  Thank you.
I initially looked into the 'Key Assist' and could not see how to modify there, but now I changed it and made life a lot easier.  Thank you.
