### ISSUE TITLE
Feature request:please support mycat

### ISSUE THREAD

**Issue by toxmc** [dbeaver/dbeaver#4198]
this issue Feature request is about support MYCAT.

MyCAT is an Open-Source software, “a large database cluster” oriented to enterprises. MyCAT is an enforced database which is a replacement for MySQL and supports transaction and ACID. Regarded as MySQL cluster of enterprise database, MyCAT can take the place of expensive Oracle cluster. MyCAT is also a new type of database, which seems like a SQL Server integrated with the memory cache technology, NoSQL technology and HDFS big data. And as a new modern enterprise database product, MyCAT is combined with the traditional database and new distributed data warehouse. In a word, MyCAT is a fresh new middleware of database.

now DBeaver can be connected to MYCAT successful, but it's can't show databases and table successful.
MYCAT has a Logical database named TESTDB.  I want  DBeaver to show Logical database and table, not the real database.

thanks

mysql-client:
![image](https://user-images.githubusercontent.com/3990846/45409294-5c571180-b6a1-11e8-98eb-27a604538ece.png)

DBeaver:
![image](https://user-images.githubusercontent.com/3990846/45409331-7264d200-b6a1-11e8-8316-9f123563b762.png)

**Comment by toxmc** [comment]
mycat github:   https://github.com/MyCATApache/Mycat-Server

**Comment by toxmc** [comment]
@serge-rider Yes, Mysql client is perfectly supported mycat

**Comment by serge-rider** [comment]
We'll switch to `show databases` call in the next version.
Please test EA version (https://dbeaver.io/files/ea) for MyCat connectivity.
