### ISSUE TITLE
Dbeaver: Default Transaction Option (Read Uncommited)

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#4203]
DBeaver - Version 5.2.0 CE
Operating System: Windows 10
JDBC Driver: mssql-jdbc 7.0.0.jre10
Database: Microsoft SQL Server Database

In transaction manager dropdown. Can we have a default setting for read uncommited ? 
Can we have a global dbeaver setting in preferences for that ?

![image](https://user-images.githubusercontent.com/38669892/45426881-0cf1f080-b663-11e8-89a5-66538d2117f0.png)

**Comment by ascendhans** [comment]
@serge-rider May i please get an update on this, if possible.

**Comment by serge-rider** [comment]
You can set default isolation level in connection properties:
Note: connect to the database and then open properties page to be able to edit isolation levels.

![image](https://user-images.githubusercontent.com/6398845/46016585-da71da00-c0dd-11e8-9507-79dce6ecb49a.png)
