### ISSUE TITLE
5.2 is not appearing in github releases

### ISSUE THREAD

**Issue by kiravi** [dbeaver/dbeaver#4205]
In the github releases page there is no link for tagged 5.2 version

**Comment by nchammas** [comment]
Was just about to report the same thing. Has the release process changed, or was this just missed?

**Comment by serge-rider** [comment]
Weird. I was quite sure that we have published it.
No, nothing has changed in the release process. But something went wrong..

I'll try to re-publish it today on GitHub from master branch.

**Comment by mxcoder** [comment]
Hi @serge-rider is this also why its not available in the Ubuntu PPA for 17.10 ?

**Comment by lalato** [comment]
Also wondering if this would impact installing via Homebrew.

**Comment by serge-rider** [comment]
Release 5.2 has been published on GitHub (https://github.com/dbeaver/dbeaver/releases/tag/5.2.0)
However as this happened after actual release git tag was set in devel branch after version was switched to 5.2.1. This won't be a big problem for DBeaver functioning but may produce some mess in versioning.

Sorry about that. Our release publishing system is in half-manual mode.

**Comment by serge-rider** [comment]
Note: actual binaries in GitHub are for 5.2.0 version. 
But this may affect those who build DBeaver from source using GitHub tags,

**Comment by lalato** [comment]
FYI... brew cask upgrade dbeaver-community is not grabbing the new version.

**Comment by serge-rider** [comment]
@lalato I think we should wait for some time. I've published release just 40 minutes ago, package check+rebuild doesn't happen in a moment.

**Comment by p91paul** [comment]
I don't understand: why did you tag 5.2.0 what is, in fact, 5.2.1? Aren't you aware you can use `git tag 5.2.0 d12d7cef3e4889750fe806c11cbf1aed306bf8bd` to apply the tag to a previous commit (i used the example of the commit just before "5.2.1 config", I don't know from where you released 5.2.0)? Of course you now have to --force that since the tag already exists.

**Comment by serge-rider** [comment]
@p91paul I never tried that before. Thanks for the information )
I set it to d12d7cef3e4889750fe806c11cbf1aed306bf8bd . It is a couple of commits after actual 5.2.0 release but it shouldn't make any harm (as I understand the main problem is version number).

**Comment by p91paul** [comment]
Glad I could help!! :smile:
