### ISSUE TITLE
Database monitoring dashboard

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#4209]
Can we have database monitoring features like the database tool TOAD ?
A few things we can have them through UI option, For example
1. Connected Database version, Type, etc.
2. Total number of connection pool capacity for the database.
3. Number of connections to the database to which dbeaver is connected.
4. Database server uptime. What time the database server was started.

These are a few things that I thought would be a good addition to Dbeaver. I love this tool so far.  :+1:

**Comment by honestserpent** [comment]
This would be really nice. I would also like something like pgadmin dashboard

**Comment by ascendhans** [comment]
@serge-rider  Will this new additional functionality include addition of DELETE option in the context menu for Tables / Views and other SQL Server components ?
