### ISSUE TITLE
Oracle: "Force object refresh on editor open" option does not work

### ISSUE THREAD

**Issue by dunicres** [dbeaver/dbeaver#4210]
When you check the box in Settings -> General -> Editors -> Database editor -> Force object refresh on editor open

It does not refresh the object on editor open.

Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
PL/SQL Release 11.2.0.3.0 - Production
"CORE	11.2.0.3.0	Production"
TNS for Linux: Version 11.2.0.3.0 - Production
NLSRTL Version 11.2.0.3.0 - Production

For example user A opens a package, closes it.
User B opens the same package as user A and makes changes, commits (persists in to DB), closes the package. User A opens the package again, then user A will not see user Bs changes.

By refreshing the object (package) manually user A will see changes of user B

**Comment by serge-rider** [comment]
Currently this feature works only for simple objects (like tables). Packages and schemas are not auto-refreshed because it is too expensive. Maybe we should make two separate options - only for simple object and one for container (schemas, databases, packages, etc).
