### ISSUE TITLE
dbeaver-ce v5.2.0 x86_64 rpm cannot be installed in Fedora 28

### ISSUE THREAD

**Issue by zimonth** [dbeaver/dbeaver#4211]
dbeaver-ce-5.2.0-stable.x86_64.rpm  from https://dbeaver.io/download/ cannot be installed into Fedora 28. Seems like rpm-file is somehow broken. The same file in Fedora 24 installed fine.

Tried in two different Fedora 28 machines.  ("rpm --rebuilddb" did not help)

**# uname --kernel-release** 
4.17.19-200.fc28.x86_64

**# dnf localinstall /tmp/dbeaver-ce-5.2.0-stable.x86_64.rpm** 
error: rpmdbNextIterator: skipping h#    8587 tag[34]: BAD, tag 1096 type 5 offset 43528 count 675 len 2700
Last metadata expiration check: 2:11:08 ago on Thu 13 Sep 2018 12:11:31 PM EEST.
Can not load RPM file: /tmp/dbeaver-ce-5.2.0-stable.x86_64.rpm.
Could not open: /tmp/dbeaver-ce-5.2.0-stable.x86_64.rpm

**# rpm -Uv /tmp/dbeaver-ce-5.2.0-stable.x86_64.rpm** 
error: /tmp/dbeaver-ce-5.2.0-stable.x86_64.rpm: tag[34]: BAD, tag 1096 type 5 offset 48168 count 745 len 2980
error: /tmp/dbeaver-ce-5.2.0-stable.x86_64.rpm cannot be installed

**Comment by tati-kru** [comment]
Hello, 

It is a known issue. We have fixed it in 5.2.1 EA. You can find more details here: https://github.com/dbeaver/dbeaver/issues/4177. Thank you anyway.
