### ISSUE TITLE
Inner Join autocompletes without quotes

### ISSUE THREAD

**Issue by lflucasferreira** [dbeaver/dbeaver#4213]
I like Dbeaver, but there is a bug when I use inner join autocompleting the joining.

The IDE expects the name table to be quoted in order to execute the script. However, it does not autocomplete the join quoting the tables.

For example:
Table1.id = Table2.id

Expected:
"Table1".id = "Table2".id

Would the developers mind to fix this issue? I'd be very happy.

Thanks!

**Comment by serge-rider** [comment]
Thanks for the bug report, see fix in the next version.
