### ISSUE TITLE
New Connection to FB3 Embeded

### ISSUE THREAD

**Issue by medhome63** [dbeaver/dbeaver#4215]
Hi there,
 I can not do a new connection all *.fbd are disabled in my data directory?
Opening database FDB is not possible?

I use 
Linux mint 18.3 
Firebird 3 embeded
DBeaver 5.2

What gives?

Regards
Med

**Comment by serge-rider** [comment]
Embedded database is not supported by FB driver (Jaybird). Once it will support this mode we'll add it in DBeaver.

See #3397
