### ISSUE TITLE
Feature: Be able to compare tables/databases and generate INSERT/DELETE/UPDATE script from difference

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4217]
DBeaver - **Version 5.1.4 CE**
Operating System: **Windows 10**

It would be really benificial if I could compare two tables (or more table pairs) or a two databases and compare the data contents. Then the resulting difference then generates the necessary INSERT/DELETE/UPDATE statements to make the compared items equal.

**Comment by serge-rider** [comment]
Duplicate of #957
