### ISSUE TITLE
Generate Mock Data - Foreign key

### ISSUE THREAD

**Issue by cinatic** [dbeaver/dbeaver#4218]
Hi,

i noticed one thing, if you generate mock data and you have a FK generator but the FK table has no values yet, you get a "out of bound" error. Fair enough i thought, so i put NULL % to 100 but still get out of bound error.

I think a better error message would be nice and if 100% NULL values has been selected the error should not happen.

Best regards

**Comment by serge-rider** [comment]
Thanks for the bug report
