### ISSUE TITLE
When pasting a query from a script (quoted "") formatting is lost.

### ISSUE THREAD

**Issue by lvlofenix** [dbeaver/dbeaver#4221]
!!GOOGLE TRANSLATE!!
First, thank you for keeping this project, dbeaver is my favorite manager.

video that best explains what happens: [https://youtu.be/wKEXknKQ8QM](https://youtu.be/wKEXknKQ8QM)

In the current version that I use (5.2.0) every time I paste a query in dbeaver it happens that misses formatting after dbeaver automatically remove the commas.

This started to happen after one of the updates, I do not remember which one.

**Comment by lvlofenix** [comment]
query for you teste

"select top 10 * from ( ",
        "select ",
        "  l.codigo lote, round(l.qtdSaldoAtual, 2) qtdLote, ",
        "  v.codigo volume, round(sum(vil.quantidade), 2) qtdVol, ",
        "  (select round(sum(m.quantidade * m.dc), 2) from dbo.stk_item_produto_lote_movto m ",
        "   where m.id_volume = v.id_volume and m.id_item_produto_lote = l.id_item_produto_lote) qtdMov, ",
        "  (select min(m.dtMovto) from stk_item_produto_lote_movto m ",
        "   where m.id_volume = v.id_volume and m.isdeleted = 0) primMovto,    ",
        "  (select max(m.dtMovto) from stk_item_produto_lote_movto m ",
        "   where m.id_volume = v.id_volume and m.isdeleted = 0) ultMovto, ",
        "  case when op.id_ordemprod is not null and op.id_eng_planoExec is null then 'LOGUIN' else 'AFX' end origem, ",
        "  v.insertdate criacaoVolume, ",
        "  l.id_item_produto_lote, v.id_volume, l.id_item ",
        "from dbo.stk_item_produto_lote l ",
        "inner join dbo.stk_item_produto_pa pa on l.id_item = pa.id_item ",
        "inner join dbo.stk_volume_item_lote vil on vil.id_item_produto_lote = l.id_item_produto_lote ",
        "inner join dbo.stk_volume_item vi on vi.id_volume_item = vil.id_volume_item ",
        "inner join dbo.stk_volume v on v.id_volume = vi.id_volume ",
        "left join dbo.ord_ordemProd op on l.id_ordemprod = op.id_ordemprod ",
        "where v.codigo not in (select volume from temp_estoque) ",
        "group by l.codigo, l.qtdSaldoAtual, op.id_eng_planoExec, ",
        "  v.codigo, l.id_item_produto_lote, v.id_volume, l.id_item, op.id_ordemprod, v.insertdate ",
        ") t ",
        "where ((t.qtdMov > 1) or (t.qtdVol > 1)) ",
        "  and t.ultMovto < convert(datetime, '01/01/2018 00:00:00', 103) ",
        "order by t.ultMovto"

**Comment by serge-rider** [comment]
It is a bug in current source code transformer.
We need to insert line feed even if there is no line feed in actual SQL query.

As a workaround you can use paste+SQL format (<kbd>ctrl+shift+f</kbd>)
