### ISSUE TITLE
CSV import NULL string mark support

### ISSUE THREAD

**Issue by chrishain-zignal** [dbeaver/dbeaver#4223]
I'm trying to use the new literal for NULL mark for CSV import but I'm not able to get NULL values to populate my table. What is the literal I should be using? I've tried "null", "NULL", "\n", "/n", and "" to no avail. I'm on the latest version 5.2.0

**Comment by serge-rider** [comment]
IT is configurable in CSV import wizard. You can set any string literal as NULL mark:
![image](https://user-images.githubusercontent.com/6398845/45594705-c4f70480-b9a7-11e8-9725-a84c2e4e0251.png)
