### ISSUE TITLE
error: dbeaver-ce-5.2.0-stable.x86_64.rpm: tag[34]: BAD, tag 1096 type 5 offset 48168 count 745 len 2980 error: dbeaver-ce-5.2.0-stable.x86_64.rpm cannot be installed

### ISSUE THREAD

**Issue by jesusferm** [dbeaver/dbeaver#4224]
tried installed dbeaver 5.2 on fedora 28, x86_64

error: dbeaver-ce-5.2.0-stable.x86_64.rpm: tag[34]: BAD, tag 1096 type 5 offset 48168 count 745 len 2980
error: dbeaver-ce-5.2.0-stable.x86_64.rpm cannot be installed

**Comment by serge-rider** [comment]
Duplicate of #4177 
See comments for workaround
