### ISSUE TITLE
Upgrade to 5.2.0 forces batched view of db objects? How to show all?

### ISSUE THREAD

**Issue by lalato** [dbeaver/dbeaver#4225]
I upgraded to 5.2.0 and now when I pull up a database there is a 10,000 object limit to the objects displayed.  Going to the bottom of the list shows that you can fetch another batch of objects. 

Is there a setting somewhere to turn off the limit?

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/45589450-4dd15a00-b92e-11e8-8aa9-88f843f3ef22.png)

Just set fetch size to some big enough value

**Comment by lalato** [comment]
Perfect! Thanks, Serge!

**Comment by serge-rider** [comment]
NP,
In fact it is much more convenient to work with long table lists in schema editor. Double-click on Tables node. Then you can filter/search tables easier.
