### ISSUE TITLE
Unable to edit the data in column in table data explorer on Mac OS

### ISSUE THREAD

**Issue by git265** [dbeaver/dbeaver#4226]
I cannot edit the column data inline while viewing the table data contents. This is on Mac and atleast started seeing this issue from 5.2.0 version. Please see below the screenshot. Connection is NOT set to read-only 

![](https://user-images.githubusercontent.com/4753090/42275596-d03332b6-7f5e-11e8-9ba3-7b252f9990a8.png)

**Comment by serge-rider** [comment]
What is your database?
Could you post table DDL?

**Comment by git265** [comment]
I am using oracle 11g

Please see below the DDL`  CREATE TABLE "SPF"."USER_ROLE_PERMISSION" 
   (	"COMPANY_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ROLE_PERMISSION_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"ROLE_PERMISSION_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ROLE_SUBSCRIPTION_TYPE" VARCHAR2(1 BYTE) DEFAULT 'S' NOT NULL ENABLE, 
	 CONSTRAINT "CHK_ROLE_PERMISSION_TYPE" CHECK (role_permission_type IN ('ROLE','PERMISSION')) ENABLE, 
	 CONSTRAINT "PK_USER_ROLE_PERMISSION" PRIMARY KEY ("COMPANY_ID", "USERNAME", "ROLE_PERMISSION_ID", "ROLE_PERMISSION_TYPE"))`

**Comment by mfoufoutis** [comment]
I'm getting this as well. very annoying

**Comment by mfoufoutis** [comment]
@git265 workaround is to use jetbrains datagrip tool

**Comment by serge-rider** [comment]
@git265 still can't reproduce on both Mac and Windows (I'm using your DDL). Could you try on the most recent version (5.2.3)?

@mfoufoutis tracked in #4526
