### ISSUE TITLE
socks proxy support for oracle connection not working 5.2.0

### ISSUE THREAD

**Issue by myururdurmaz** [dbeaver/dbeaver#4229]
![image](https://user-images.githubusercontent.com/1057861/45619522-3acf9e80-ba82-11e8-95fd-8cbada88d216.png)
![image](https://user-images.githubusercontent.com/1057861/45619533-491dba80-ba82-11e8-8194-5fe18771ecf0.png)
![image](https://user-images.githubusercontent.com/1057861/45619611-98fc8180-ba82-11e8-8bac-1522b3bcae1a.png)
![image](https://user-images.githubusercontent.com/1057861/45619636-aa458e00-ba82-11e8-8aef-f4841296750d.png)

but same configuration working on 5.0.1

![image](https://user-images.githubusercontent.com/1057861/45619701-ed076600-ba82-11e8-9440-29b0a037682e.png)

**Comment by serge-rider** [comment]
Please try to configure connection timeouts (it is 20 seconds by default):
![image](https://user-images.githubusercontent.com/6398845/45679378-37e7b300-bb41-11e8-83fe-df4149e9c8cd.png)

**Comment by myururdurmaz** [comment]
not working

![image](https://user-images.githubusercontent.com/1057861/45685343-bd735f00-bb51-11e8-9056-cefb06e7c4c8.png)

**Comment by serge-rider** [comment]
Could you provide a bit more details.
How much time passes after you click "test connection" till you see error dialog?

**Comment by myururdurmaz** [comment]
log ?

![image](https://user-images.githubusercontent.com/1057861/45688747-e3513180-bb5a-11e8-9499-d5ec96ac8af0.png)

**Comment by myururdurmaz** [comment]
connection open timeout working fine. (timed out 20000). but not conecting

**Comment by serge-rider** [comment]
Could you set it to some bigger value?

**Comment by p91paul** [comment]
I just tried this. I just dump opened a socks proxy connection while I was in a network where A) the IP was directly reachable B) the socks proxy was down. And... it connected fine. Could it be that 5.2.0 is flat out ignoring socks proxy and trying direct connection instead?

**Comment by serge-rider** [comment]
@p91paul Basically SOCKS5 proxy works in all recent versions (although there were some issues with authentication which are now solved).

However there may be problems if you connect to a database on the localhost (in that case proxy won't be used).
I'll test this a bit more

**Comment by myururdurmaz** [comment]
5.2.1 (https://github.com/dbeaver/dbeaver/releases/download/5.2.1/dbeaver-ce_5.2.1_amd64.deb) working with same driver

**Comment by serge-rider** [comment]
Good, thanks for the info
