### ISSUE TITLE
Always export only selected columns

### ISSUE THREAD

**Issue by micrarior** [dbeaver/dbeaver#4230]
I tried to export rows selected by column. And it exports only selected columns even if "selected columns only" unchecked    

DBeaver Community Edition	5.2.0.201809092115

**Comment by serge-rider** [comment]
Can't reproduce that. What export format do you use?

**Comment by micrarior** [comment]
I tried DBUnit and SQL


![settings](https://user-images.githubusercontent.com/6170034/45889910-0c7ff500-bddb-11e8-8ecb-006c49445cce.png)
![result](https://user-images.githubusercontent.com/6170034/45889860-ec503600-bdda-11e8-8bce-b5b0ed578d54.png)

**Comment by serge-rider** [comment]
Thanks for the bug report
