### ISSUE TITLE
Display timestamp in native format (microseconds problem)

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#4231]
I've noticed a problem when viewing timestamp columns of a Postgres table: the timestamp column is always formatted according to Data Formats specified in Preferences and sometimes this is a problem. By default, the format is yyyy-MM-dd HH:mm:ss, which fine but if there is a microseconds part then it is not shown.

Consider the following result set - the first one viewed in DBeaver and the second one viewed in pgAdmin:
![dbeaver-date-format](https://user-images.githubusercontent.com/11840364/45651369-a12fdd80-bad1-11e8-8a9c-551139e1e7d1.png)
DBeaver shows truncated timestamp while pgAdmin shows actual data. What DBeaver shows is misleading.

I know I can set the Data Format pattern to show the microseconds part but then the problem is that microseconds will be shown for all timestamp columns, even if they are not stored in the db, which will look messy due to unnecessary series of zeroes.

Would it be possible to set DBeaver to display timestamp values without any formatting, that is in the native format as returned by the database? That's how pgAdmin displays values and also how the driver fetches data in PHP (and possibly in many other languages).

**Comment by serge-rider** [comment]
Generally this is possible. Although there is no such thing as native date format in JDBC but we can use default JDBC driver date->string conversion. Although some driver may return a messy date values.
I think this should be disabled by default and it should be configurable on Data formats page.

**Comment by lemon-juice** [comment]
I see. If there is no native date format in JDBC that can be relied upon then another possibility would be to simply add an option to emulate it. The current default format for timestamp is `yyyy-MM-dd HH:mm:ss` but instead we could have something like `yyyy-MM-dd HH:mm:ss(.F)` where `(.F)` would mean any number of actual fractional part digits without trailing zeroes, so this would result in display like this:
```
2018-09-20 11:30:15
2018-09-20 11:30:15.3
2018-09-20 11:30:15.35
2018-09-20 11:30:15.123456
```
showing always full non-truncated values without unnecessary trailing zeroes.

That's just an idea, whatever implementation you think best will be fine. In my opinion this kind of display should be the default because it does not truncate values - currently, the default format may truncate values, which is not good. But if it is required to set it in options, it will be fine, too.

**Comment by lemon-juice** [comment]
A related problem exists with exporting timestamp data - I don't know if it should go into a separate bug but for now I'll report it here.

When using Generate SQL -> INSERT, or Export Result Set in SQL format then timestamp columns are exported incorrectly when there are more than 3 fractional digits in the values. In other words, timestamp values are truncated to 3 fractional digits. For example, I have this data set:
```
|id |ts                       |ts0                 |ts1                   |ts6                        |
|---|-------------------------|--------------------|----------------------|---------------------------|
|2  |2018-09-17 23:04:51.1234 |2018-09-17 23:04:53 |2018-09-17 23:04:53.1 |2018-09-17 23:04:53.123456 |
```
And SQL generated for this row is this:
```sql
INSERT INTO dates
(id, ts, ts0, ts1, ts6)
VALUES(2, '2018-09-17 23:04:51.123', '2018-09-17 23:04:53.000', '2018-09-17 23:04:53.100', '2018-09-17 23:04:53.123');
```
As you can see values for `ts` and `ts6` columns are truncated.

I think it would be best if timastamps were exported in the currently non-existing format `yyyy-MM-dd HH:mm:ss(.F)` that I mentioned above, which would be equivalent to the way pg_dump creates dumped SQL:
```sql
INSERT INTO dates VALUES (2, '2018-09-17 23:04:51.1234', '2018-09-17 23:04:53', '2018-09-17 23:04:53.1', '2018-09-17 23:04:53.123456');
```

**Comment by lemon-juice** [comment]
Now that issue #1224 is referenced here I can see that indeed there is a problem with time zones, too:

1. timestamptz values are displayed without time zone information by default, or with local time zone - if `z` is specified in the date format. There are 2 problems with it:

- We would normally want to view timestamp values in the server's time zone - that's how Postgres actually formats them before sending to the client (but I don't know about JDBC)
- We wouldn't want both timestamp and timestamptz values to be displayed in the same format: for timestamp the time zone suffix is superfluous while for timestamptz it is essential.

2. Time zone information is lost when exporting rows to INSERT statements.
3. Time zone information is lost when I enter values like `2018-09-30 12:00:00+03` in the table data grid and save.

All these problems would be solved if DBeaver used native format for timestamp, timestamptz, time, and timetz values - both for display and for input. Native format is the one that can be seen by using the official pgAdmin tool, by doing pg_dump in plain format or probably by using any Postgres driver for programming languages other than JDBC.

**Comment by serge-rider** [comment]
Native date/tiem format support will be added in 5.2.2.

Was tested with PostgreSQL, MySQL, MariaDB and Oracle. In read-only mode works for almost all databases but update/insert may fail in some drivers. 

Even PostgreSQL driver doesn't work out of the box and I had to add a workaround (save string values as objects with type java.sql.Types.OTHER).

![image](https://user-images.githubusercontent.com/6398845/46403801-2a6b2500-c70c-11e8-9309-d58187a2d818.png)

**Comment by lemon-juice** [comment]
Looks great, thanks!

**Comment by serge-rider** [comment]
You could test this in EA version (https://dbeaver.io/files/ea)

**Comment by lemon-juice** [comment]
I've tried the EA version with Postgres and the data grid works very well with the native format - both display and editing. But there's a problem with exporting rows to INSERT queries: the quotes around the values are missing, which results in incorrect SQL statements.

There is also one minor cosmetic issue - when using the native date time format and viewing `timestamp` columns that can have a variable number of fractional digits we would probably not want them to be right aligned like numeric fields:
![dbeaver-timestamp-alignment](https://user-images.githubusercontent.com/11840364/46442604-7cdb2e80-c76a-11e8-906a-bda0e996edab.png)
I think it would be best if option "Right-justify numbers and date/times" was split in two so that we can independently choose alignment for numbers and date/times. In such scenarios we might want to right align numbers and left align timestamps.

**Comment by serge-rider** [comment]
SQL format export fixed.

And yes, we need separate date/time columns align option.
![image](https://user-images.githubusercontent.com/6398845/46466083-feff3d80-c7d2-11e8-8d57-5f4829d11d41.png)

New EA will be published later today.

**Comment by lemon-juice** [comment]
Tried the EA version and the export is fixed and the justification options work. This was a well done and thorough bug resolution. Thanks!
