### ISSUE TITLE
Release 5.2 - query performance on Vertica 8.1

### ISSUE THREAD

**Issue by jdani015** [dbeaver/dbeaver#4234]
Upgraded from 5.1 to 5.2 and experienced performance issues when opening/querying tables/views.  Reverted back to 5.1 resolved issue.

**Comment by serge-rider** [comment]
Perhaps this is the same as #4193

**Comment by chomam** [comment]
this is still an issue with DBeaver 5.2.2

"select * from large_table" hangs, 

looking at sql history in vertica : query_requests  view, the query is "select * from large_table" so is fetching all rows

whilst in DBeaver 5.1 it's "select * from large_table limit 200"

Using vertica 9.0 and vertica jdbc 9.1

DBeaver settings are default: Result fetch size 200, Use SQL to limit fetch size unticked - enabling this seems to work.

Did default behaviour for "Use SQL to limit fetch size" changed in DBeaver 5.2 ?

**Comment by serge-rider** [comment]
@chomam Yes, it is a bug in one of the recent version. We disabled API calls for row count limitations because they affected non-SELECT statement as well.
I've enabled explicit LIMITs for SQL queries.
Thanks for the bug report.
