### ISSUE TITLE
Unable to create new Cloudera Impala connection after updating to 5.2

### ISSUE THREAD

**Issue by ermus19** [dbeaver/dbeaver#4235]
- System: Windows 10
- dbeaver version: Community Edition 5.2.0.201809092115
- Found in dbeaver distributed as zip

After updating dbeaver to 5.2 from 5.1 I'm not able to finish the New creation wizard for Impala database, "Next" and "Finish" buttons are disabled:

![image](https://user-images.githubusercontent.com/3046446/45693838-455f6600-bb5e-11e8-89b3-18009dbdf839.png)

I've checked the Driver settings and are pointing correctly to Impala drivers and I've other Impala connections working from the previous version 5.1.

I'm able to create new connections manually editing file **.dbeaver-data-sources** under path _C:\Users\<username>\.dbeaver4\General_

**Comment by serge-rider** [comment]
It is a bug in the Generic driver connection page.
Workaround: click on Network settings or Connection details link and then click "Back".

Thanks for the bug report.
