### ISSUE TITLE
Postgres: support for timestamp precision

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#4236]
DBeaver currently does not support setting precision for [timestamp](https://www.postgresql.org/docs/current/static/datatype-datetime.html) columns. Additionally, it creates incorrect DDL code for tables that contain timestamp columns with precision other than default.

For example, I have a table like this:
```sql
CREATE TABLE public.dates
(
    id integer NOT NULL,
    ts timestamp without time zone,
    ts0 timestamp(0) without time zone,
    ts1 timestamp(1) without time zone,
    ts6 timestamp(6) without time zone,
    CONSTRAINT dates_pk PRIMARY KEY (id)
)
```
DBeaver creates this DDL for the table:
```sql
CREATE TABLE public.dates (
	id int4 NOT NULL,
	ts timestamp NULL,
	ts0 timestamp NULL,
	ts1 timestamp NULL,
	ts6 timestamp NULL,
	CONSTRAINT dates_pk PRIMARY KEY (id)
);
```
As you can see the precision definitions are lost. Precision can be seen in the Columns tab of a table in the Scale column - it can even be edited but DBeaver fails to create correct DDL when trying to persist the changes, it always lacks any precision definition:

```sql
ALTER TABLE public.dates ALTER COLUMN ts6 TYPE timestamp USING ts6::timestamp;
```

I think we would need support for precision in timestamp columns. As far as I can see there is no practical difference between `timestamp` and `timestamp(6)` columns but Postgres keeps the distinction in the table definition nevertheless and it would be good if DBeaver also did that.

I think the same issue applies to `time` and `interval` data types since they also accept precision parameter - but I haven't done any tests on them.

**Comment by LonwoLonwo** [comment]
DDL changed for data types timestamp... and for time. 6 set as default (not shown)

**Comment by LonwoLonwo** [comment]
DDL changed for data types timestamp... and for time. 6 set as default (not shown)

**Comment by LonwoLonwo** [comment]
DDL changed for data types timestamp... and for time. 6 set as default (not shown)

**Comment by LonwoLonwo** [comment]
DDL changed for data types timestamp... and for time. 6 set as default (not shown)

**Comment by LonwoLonwo** [comment]
DDL changed for data types timestamp... and for time. 6 set as default (not shown)

**Comment by LonwoLonwo** [comment]
DDL changed for data types timestamp... and for time. 6 set as default (not shown)

**Comment by LonwoLonwo** [comment]
DDL changed for data types timestamp... and for time. 6 set as default (not shown)

**Comment by LonwoLonwo** [comment]
DDL changed for data types timestamp... and for time. 6 set as default (not shown)

**Comment by LonwoLonwo** [comment]
DDL changed for data types timestamp... and for time. 6 set as default (not shown)

**Comment by LonwoLonwo** [comment]
DDL changed for data types timestamp... and for time. 6 set as default (not shown)

**Comment by LonwoLonwo** [comment]
DDL changed for data types timestamp... and for time. 6 set as default (not shown)

**Comment by kseniiaguzeeva** [comment]
Verified. 
Timestamp, time is ok. Interval doesn't show a precision.

**Comment by lvanderlaat** [comment]
Hi, 

I just wanted to add that is a bit confusing to create a timestamp column with a specific precision (number of digits after decimal seconds point). It was a bit frustrating, because for my application I need at least 3 floating points number for the seconds and I found out that even if I created my timestamp column with precision 3, it did created the column with 0 precision. After struggling with this, I find out by accident that the Scale option was the one controlling the precision...

**Comment by LonwoLonwo** [comment]
Hello @lvanderlaat 
And it works for you now?

**Comment by lvanderlaat** [comment]
> Hello @lvanderlaat
> And it works for you now?

Thank you @LonwoLonwo, 

Yes. It works. In part, my message was to anybody out there struggling with the same problem. This is my workaround solution: for a timestamp column, instead of entering the precision in the "Precision" entry, it must be entered the "Scale" entry. 

Although not intuitive, I guess there is some reason for this behavior. It would be great if it could be ameliorated in the future.

**Comment by LonwoLonwo** [comment]
@lvanderlaat you can create another enhancement ticket for this. 
as I can see in [documentation](https://www.postgresql.org/docs/current/datatype-datetime.html), time and timestamp data types have precision, not scale as parameters.

**Comment by lvanderlaat** [comment]
> @lvanderlaat you can create another enhancement ticket for this.
> as I can see in [documentation](https://www.postgresql.org/docs/current/datatype-datetime.html), time and timestamp data types have precision, not scale as parameters.

@LonwoLonwo that's is exactly my point. Somehow, the precision parameter for timestamp ended up in "Scale". I will create the new ticket. 

Thanks again.
