### ISSUE TITLE
Bug report: DBeaver client return duplicated row at row 200 and 201

### ISSUE THREAD

**Issue by ginanjar-fahrul-m** [dbeaver/dbeaver#4237]
I currently use DBeaver for Mac and execute this query:

`select table5.tag, table4.number, table2.number, table1.created_at, table3.email
from table1
join table2 on table2.id = table1.fk2_id
join table3 on table3.id = table2.fk3_id
join table4 on table4.id = table2.fk_4_id
join table5 on table5.id = table4.fk_5_id
order by table1.created_at ASC`

Resultset contains 267 rows. The problem occurs at row 200 and 201. Row 201 return wrong result.

`row 200: 3.7 22733801068886 20605235060095 2018-07-02 19:24:54	email1@gmail.com`
`row 201: 3.7 22733801068886 20605235060095 2018-07-02 19:24:54	email1@gmail.com`

It should be.

`row 200: 3.7 22733801068886 20605235060095 2018-07-02 19:24:54	email1@gmail.com`
`row 201: 3.7 22733801068886 6257661505012 2018-07-02 19:24:54 someone2@gmail.com`

I already tested it with native sql client (MySQL). The idea of result auto-pagination is nice but I think this bug should be fixed.

**Comment by serge-rider** [comment]
This may happen if you fetch second page (after 200th row) after some delay and underlying table has changed since you read the first page.
DBeaver users simple LIMIT clause to paginate over resultset. There is no way to fix this behavior in auto-commit mode.
But this problem won't happen if you will work in transactional mode (you can switch to manual commit mode in the main toolbar or in the main menu).

**Comment by ginanjar-fahrul-m** [comment]
> This may happen if you fetch second page (after 200th row) after some delay and underlying table has changed since you read the first page.

I can make sure that all related tables has not changed at the moment.

> But this problem won't happen if you will work in transactional mode (you can switch to manual commit mode in the main toolbar or in the main menu).

Thanks. It works normally at manual commit mode.

I think the problem is not from getting result sets but when the result sets are rendered at DBeaver output panel. But I'm sorry the case is intermittent and I can't investigate further. This question/issue can be closed. Thank you. :)
