### ISSUE TITLE
Repriority issue #2226 on SQL Assistant/Completion missing assist with SQL keywords

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4238]
DBeaver - **Version 5.2.0 CE**
DBeaver JDBC driver: **jTDS or Microsoft**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014**

If possible I would like the issue #2226 to be moved out of the #810 bundle issue (that bundles a number of SQL Server issues).

The issue #2226 was added to the #810 bundle issue **2017-Sep-28**. The issue has been moved from this date to now version 5.3 planned for **2018-Dec-10**.

Since I am really in need of having the same behaviour for table assist that _DBeaver_ **PostgreSQL** and I am worried that the #810 bundle issue moves even forward in time, I would like the specific issue #2226 is separated out of the #810 bundled if possible.

**Comment by serge-rider** [comment]
SQL Server extension is one of the most important features in 5.2.x releases. We are not going to move it in future anymore.
