### ISSUE TITLE
Bug report: Failing to export multiple tables at once to another database.

### ISSUE THREAD

**Issue by zimonth** [dbeaver/dbeaver#4239]
Bug report.
Exporting multiple tables from one db to another (Export to Database) fails. Exporting them one by one succeeds.
Exporting multiple to "SQL INSERT"-statements (to a local directory) works.

1) Select multiple (in this example two) tables (exampletable1, exampletable2) from one database (MS SQL) with click, CTRL+click, SHIFT+click.
2) Context menu: Export Data: Database
3) Maximum threads: 1, Single query
3) Select target to be different database (on different server, PostgreSQL), choosing a right Schema
4) Source, Target (new tables), Mapping: create (ALL OK)
5) Even here, if selecting several lines and seeing "DDL", it shows only for one table.
6) Commit after insert of: 10000
6) Next, Confirm, check result. Everything seems to be OK. It shows all tables to be exported to new "[Create]" tables.
7) Click Finish

Gives Execution Error:

> "Error occurred during dbo.exampletable2 data load
> 
> Reason:
> SQL Error [42703]: Batch entry 0 INSERT INTO dbo.exampletable2 (column1, column2, column3)
> VALUES (2,5,7) was aborted: ERROR: column "column2" of relation "exampletable2" does not exist

So it says, it has failed to insert data to the second created table, when inserting to a second column there.  (Note: exampletable1 and exampletable2 have the same first column name)

However, the end result is when export is completed, that the latter (exampletable2) is exported correctly, but the first (exampletable1) is empty in the target database.  The exampletable1, which is empty, does have the right column names though.

My guess is, it is trying to insert a data from the exampletable1 table to a new created example2 table, although in the end it has created an empty exampletable1 also into the target database.

**Comment by zimonth** [comment]
Example case:
In DB1, create two tables:
```
create table example1 (col1 int null, col2 int null);
insert into example1 (col1, col2) values (1, 2);
create table example2 (col1 integer null, col2 integer null);
insert into example2 (col1, col2) values (3, 4);
```
Then select those two tables, export to another DB.
It proceeds without errors (because column names are the same in both tables here).
But in the target database, there is now table example1 which is empty, and table example2 has two lines of data:
```
select * from example1;
(empty)
select * from example2;
1 2
3 4
```

**Comment by zimonth** [comment]
Another example. Now column-names are different in two tables.
```
create table example1 (col1 int null, col2 int null);
insert into example1 (col1, col2) values (1, 2);
create table example2 (col21 integer null, col22 integer null);
insert into example2 (col21, col22) values (3, 4);
```
Trying to export those two tables to an another database gives error:

> Error occurred during dbo.example2 data load
> 
> Reason:
> SQL Error [42703]: ERROR: column "col1" of relation "example2" does not exist
>   Position: 27

The end result shows, only second table was exported. The first table has been created with the right columns, but it is empty:
```
select * from example1;
(empty)
select * from example2;
3 4
```

**Comment by JimAlexanderDDI** [comment]
Same problem (5.2.4): Exporting multiple tables from AS400 to PostgreSQL errors with a warning that the 1st column of the 1st table in the source set does not exist in the last table of the target set.

**Comment by uslss** [comment]
seems that issue isn't reproducible anymore
ticket closed
