### ISSUE TITLE
SQL Server connection URL template has no effect

### ISSUE THREAD

**Issue by e385515** [dbeaver/dbeaver#4243]
When changing the template for an SQL Server connection, it seems to ignore whatever is in the URL template and just use the default.

Template changed to have explicit ServerName and port:
![image](https://user-images.githubusercontent.com/43430333/45795494-36a9a980-bc59-11e8-922f-a926aa6392c7.png)

Still connects using implicit server name:
![image](https://user-images.githubusercontent.com/43430333/45795595-a750c600-bc59-11e8-96ed-2a5fdf17a111.png)

Fails because it detects an invalid address of a single colon:
![image](https://user-images.githubusercontent.com/43430333/45795614-c18aa400-bc59-11e8-8a42-283f497f5acb.png)

**Comment by serge-rider** [comment]
Yes, SQL Server extension doesn't use URL template and generate URL according to specified parameters.
Could you explain why do you need to change the template? And, moreover, set particular host address there?

**Comment by e385515** [comment]
The reason I need to change it around is to use an IPv6 literal, which doesn't work in the default template as it expects a colon to delimit the port. Microsoft's work around is to set servername and port explicitly. Is there somewhere else to explicitly write in the connection string I want to use, instead of modifying a template?

**Comment by serge-rider** [comment]
I see.
I'll fix URL generation for SQL Server in the next version (it will use serverName param by default).

Workaround: you could try to specify serverName as driver property.
