### ISSUE TITLE
JDBC driver requires DateStyle to begin with ISO

### ISSUE THREAD

**Issue by ilnurgi** [dbeaver/dbeaver#4244]
dbeaver 5.2.0.201809092115
how fix this problem? is it a bug or should I set it up dbeaver?
decisions on the Internet did not find
![image](https://user-images.githubusercontent.com/2868558/45797630-2f14ef80-bcaf-11e8-9497-4145249600dc.png)

**Comment by serge-rider** [comment]
What is your database?

**Comment by ilnurgi** [comment]
sory, postgres, 
I will not say exactly the version, but not below 9.4

**Comment by serge-rider** [comment]
This is a bug in some earlier PG JDBC driver version (https://github.com/pgjdbc/pgjdbc/issues/1080)
Try to use newer version:

![image](https://user-images.githubusercontent.com/6398845/45798006-d0507580-bcb0-11e8-864c-7c4c9abdfe72.png)

**Comment by ilnurgi** [comment]
Thank you. 
I had a version: 42.2.0.jre7
install 42.2.5.jre
and it us works
