### ISSUE TITLE
Bug report: All Informix DB have identical schemas/owners

### ISSUE THREAD

**Issue by pakno69** [dbeaver/dbeaver#4246]
Hello,
thank you for your effort. DBeaver seams to be very useful tool.

But there is a following little bug:
When you log in as Informix user with ability to access more than one DB, then all available databases have same list of schemas/owners. The list is based on database specified at connection definition.
This behavior is confusing and prevent me from effective work. I hope that solution will not be so complicated. 

Thanks for help

**Comment by uslss** [comment]
is it still actual?

**Comment by pakno69** [comment]
Unfortunately the problem is still pending, see picture below
![image](https://user-images.githubusercontent.com/43442849/73948864-d670e180-48f9-11ea-9f85-b32c35a23471.png)

**Comment by uslss** [comment]
seems to be similar to #8987
