### ISSUE TITLE
Cant change formatting for binary

### ISSUE THREAD

**Issue by vekexasia** [dbeaver/dbeaver#4251]
Hello, It seems i cannot change the formatting for binary. i've tried by clicking over the column -> View As -> 

^ that shows only Default, UUID, UUID ordered. I don't have the option to "hex" encode the binary in the result set.

**Comment by uslss** [comment]
hi @vekexasia ,
what database and data type do you use?

**Comment by uslss** [comment]
there is no update on the issue for more than a month.
additional info is needed to reproduce an issue.
ticket will be closed. feel free to reopen an issue and add info that could help to investigate it.
