### ISSUE TITLE
Whishes for ER Diagramms improvements

### ISSUE THREAD

**Issue by Bullnados** [dbeaver/dbeaver#4255]
# Whishes for ER Diagramms
A nice example for inspiration is [pgmodeler](https://pgmodeler.io/screenshots) also [sgldbm.com](https://app.sqldbm.com/SQLServer/Draft/) have some nice features.
 - Marquee areas (doesn't work in 5.2.4 community)
	 - Naming
	 - Colour (RGB and transparency)
	 - Grouping/Clustering with tables (sticky/magnetic notes)
 - Sticky notes
	 - On/off toogling
	 - Grouping/Clustering
	 - Connect with other notes or tables
	 - Formating
		 - Font colour
		 - Font size
		 - Underline, italic, bold
		 - Background colour (RGB and transparency)
 - Use ER-Diagramm [notation](https://www.conceptdraw.com/How-To-Guide/picture/Entity-Relationship-Diagram-Symbols.png)
 - Link improvements
	 - Colour
	 - More inteligent routing (perhaps yEd can help?)
		 - And/or manual route editing
		 - lines should not cross start and endpoints
	 - Start and end link on exact columns https://github.com/dbeaver/dbeaver/issues/4249
 - Separate toogling for link and table comments
 - Low and High-Level views for example see sqldbm
 - Printing
	 - Prining Lines for table alignment
	 - Printing for ER Diagramms #4294
 - Colour
 - If you are in one table show only incoming, outgoing or both links

**Comment by ShasTheMass** [comment]
Hello! I am new to DBeaver, and so far I love it, but I might have a feature suggestion that would make my life as a data scientist much easier:

_It would be great if I could select column names from different tables via the ERD view (holding ⌘) and then press a button (the new magic 'sql gen' button?) that would figure out how different tables should be joined automatically and spits out: 
**1)** a new table containing those columns only, and 
**2)** the sql query that generated that resulting table._


I guarantee you this will be a highly sought-after feature for a lot of us data scientists who need to create tables with various combinations of columns from different tables swiftly. Let me give you a simple example below:
<img width="910" alt="screenshot 2018-12-29 at 02 45 34" src="https://user-images.githubusercontent.com/8054725/50532622-dfe32400-0b13-11e9-876f-a98a8e63e57b.png">
In the figure above you can note that I have selected the columns:
- CustomerID, FirstName, LastName from Customer table, and
- ArtistID, Name from Artist table

The task is to quickly create a new table _directly from the ERD view_ with columns: CustomerID, FirstName, LastName, ArtistID, and Name, along with the SQL query that generated this table. 

Currently to do this, one needs to manually write the following query:
`SELECT c.CustomerId, c.FirstName, c.LastName, ar.ArtistId, ar.Name`
`  FROM Customer c`
`  JOIN Invoice i`
`    ON c.CustomerId = i.CustomerId`
`  	JOIN InvoiceLine il`
`  	  ON i.InvoiceId = il.InvoiceId`
`  	  JOIN Track t`
`  	    ON il.TrackId = t.TrackId`
`  	    JOIN Album a`
`  	      ON t.AlbumId = a.AlbumId`
` 	      JOIN Artist ar`
`  	        ON a.ArtistId = ar.ArtistId;`
which takes a long time to write, especially if you are not acquainted with the tables relationship/DB structure. This is a relatively simple example, at work, I am dealing with much more convoluted tables.

The simplest form of this feature would be to figure out these Joins automatically and produce a new table with the desired columns.

**Comment by tati-kru** [comment]
Hey @Bullnados, it is too much for one ticket. Some of your wishes are quite expensive and complicated, others can be implemented step by step. I'll close this ticket and create couple new. Please, if you think that there are some urgent or very important features in the list, then create new separate tickets for them. 

Hey @ShasTheMass, this feature is already implemented in DBeaver EE as Visual Query Builder. You can find more details in wiki: https://github.com/dbeaver/dbeaver/wiki/Visual-Query-Builder.

**Comment by serge-rider** [comment]
https://github.com/dbeaver/dbeaver/issues/5652
https://github.com/dbeaver/dbeaver/issues/5651
https://github.com/dbeaver/dbeaver/issues/3199
