### ISSUE TITLE
How to auto-open/auto-jump to last view before last exit?

### ISSUE THREAD

**Issue by bsto** [dbeaver/dbeaver#4259]
When I connect to a database I want immediately afterwards to auto-open resp. auto-jump to the last view before last exit/disconnect.

So when I saw recently 

MySQL / Databases / mydatabase123 / Tables / mytable456 ---> Data Tab

then exactly this view/page should be re-opened again.

How can I achieve this?

**Comment by uslss** [comment]
Already implemented
![image](https://user-images.githubusercontent.com/31996417/161942814-1b83fb34-1aed-4b34-b1ca-62d7682df114.png)
