### ISSUE TITLE
How to change the order of MySQL Driver/Connectors in Connection-Library settings?

### ISSUE THREAD

**Issue by pstein** [dbeaver/dbeaver#4262]
I successfully setup a connection to MySQL v5.7.22 with MySQL Connector mysql-connector-java-5.1.47-bin.jar

Then I downloaded the newest MySQL Connector mysql-connector-java-8.0.12.jar.

Now I want to ADD this connector file to the connection properties (BUT NOT REPLACE the current Driver Connector).
Unfortunately it seems to me that I can only add the new driver connector at the end of the Libraries list which means the new driver connector has a lower priority than the previous one.
I miss a "move up" button which let my change the file order.

I would like to keep the old library in list but at a lower priority.

How can I achieve this?

Peter

**Comment by serge-rider** [comment]
This is quite unusual request. Because you can't have two different drivers at the same time.
In any case, if you still need this for some reason (e.g. you need some Java classes from older driver) you still can do it:
- Delete existing jars/artifacts
- Add artifacts in the order you need

**Comment by pstein** [comment]
@serge-rider:

The underlying problem is as follows:

I want to setup 
- one connection to (local) MySQL database v5.7.22 with DriverConnector "mysql-connector-java-5.1.47-bin.jar"
and
- another connection to (local) MySQL database v8.0.12 with DriverConnector "mysql-connector-java-8.0.12.jar"

So when I go into the settings of first connection, then "Edit driver settings", then add/change "mysql-connector-java-5.1.47-bin.jar" in "Libraries" tab then this is ALWAYS automatically changed in connection settings for second connection as well.

How can I define different DriverConnectors per connection?

**Comment by uslss** [comment]
MySQL connection type could be used for v5.x versions and MySQL 8+ - for v8.x
![image](https://user-images.githubusercontent.com/31996417/88218214-65837300-cc68-11ea-9134-bcf76aab41c9.png)
