### ISSUE TITLE
Select data source - Collapses everything on next open after search

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#4263]
The new select data source is awesome. However I think that it might be a bit more pleasing to have it not autoexpand everything after doing 1 search. Instead by standard either Auto Collapse all or keep last known search.

At the moment what happens is that everything is expanded on second open even if there is no search done.

In a way you expect it to maybe have the last known state of search?

To reproduce:
1. Go to dialog with Ctrl+9
2. Make a search
3. Open dialog again

Maybe Esc also if there is a search could clear the search first and then on second Esc escape the dialog?

**Comment by sachinmukherjee** [comment]
Is this issue open?

**Comment by V1NAY8** [comment]
@nmat / @serge-rider Is this issue still replicable? Can you once check and update? :)

**Comment by nmat** [comment]
I believe this can be closed. The dialog change is overwhelming and so its hard to reproduce now.

Closing issue.
