### ISSUE TITLE
Null Pointer Exception in the first time open the app when check new version release

### ISSUE THREAD

**Issue by pararang** [dbeaver/dbeaver#4264]
Run on Ubuntu 16.04
DBeaver: 5.2.0.201809092115
               September 11, 2018

`!ENTRY org.jkiss.dbeaver.model 4 0 2018-09-24 08:31:41.798`
`!MESSAGE` 
`!STACK 0`
`java.lang.NullPointerException`
	`at org.jkiss.dbeaver.core.application.update.VersionUpdateDialog.isSuppressed(VersionUpdateDialog.java:172)`
	`at org.jkiss.dbeaver.core.application.update.DBeaverVersionChecker.run(DBeaverVersionChecker.java:96)`
	`at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)`
	`at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)`
`!SESSION 2018-09-24 13:26:49.622 -----------------------------------------------`
`eclipse.buildId=unknown`
`java.version=1.8.0_181`
`java.vendor=Oracle Corporation`
`BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US`
`Command-line arguments:  -os linux -ws gtk -arch x86_64`

`!ENTRY org.jkiss.dbeaver.model 4 0 2018-09-24 13:29:39.987`
`!MESSAGE `
`!STACK 0`
`java.lang.NullPointerException`
	`at org.jkiss.dbeaver.core.application.update.VersionUpdateDialog.isSuppressed(VersionUpdateDialog.java:172)`
	`at org.jkiss.dbeaver.core.application.update.DBeaverVersionChecker.run(DBeaverVersionChecker.java:96)`
	`at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)`
	`at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)`

`!ENTRY org.jkiss.dbeaver.model 4 0 2018-09-24 13:29:40.069`
`!MESSAGE `
`!STACK 0`
`java.lang.NullPointerException`
	`at org.jkiss.dbeaver.core.application.update.VersionUpdateDialog.isSuppressed(VersionUpdateDialog.java:172)`
	`at org.jkiss.dbeaver.core.application.update.DBeaverVersionChecker.run(DBeaverVersionChecker.java:96)`
	`at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)`
	`at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)`

**Comment by serge-rider** [comment]
Thanks for the bug report. 

Quite a nasty issue.
I think we'll re-release 5.2.1 (because it contains this bug too).

**Comment by pararang** [comment]
Thanks @serge-rider

**Comment by caoguofeng92** [comment]
![image](https://user-images.githubusercontent.com/49785975/96392190-eca3a100-11ed-11eb-99cf-d702f04cdf8a.png)
