### ISSUE TITLE
No repository found at https://dbever.io/update/lastest

### ISSUE THREAD

**Issue by pumisake** [dbeaver/dbeaver#4267]
Hi,

<img width="1213" alt="screen shot 2018-09-24 at 11 42 29 am" src="https://user-images.githubusercontent.com/1763122/45971901-1a0dc880-bfef-11e8-893d-1b39ab0335d9.png">

Can anyone help me about this issue? This also causes error when installing plugin in Eclipse.

Thank you.

**Comment by serge-rider** [comment]
It is https://dbeaver.io/update/latest/
Fixed, thanks for noticing.
