### ISSUE TITLE
Export from a query with @set commands

### ISSUE THREAD

**Issue by knwpsk** [dbeaver/dbeaver#4268]
Feature request:

Allow user to run a script which consists of just one query; but is preceded by one or more @set commands which set values to variables.

Background: today you can a *query* and export it automatically; or you can run a *script* and only view the results in the editor; but you can't run a script and export it automatically.  There's no command to "run script and export to a file."  

As Serge pointed out to me, it would be confusing if there was more than one query in the script: which one would you export?  For my purposes, I would be fine with limiting this feature to scripts that only have one executable query.

I see ticket 2855 is sortof related to this request.  But 2855 asks to export *multiple queries* (presumably into separate files), and I think that's not quite the same thing.

**Comment by serge-rider** [comment]
I still think that this is the same as #2855. But #2855 is more general.

**Comment by tati-kru** [comment]
Add a new command @export

**Comment by serge-rider** [comment]
Export from script works already.
Implementing `@export` command will requie quite a lot of work. So moving it further.

**Comment by knwpsk** [comment]
@serge-rider  you're going to think I'm crazy, but I don't really recall what's the need for this.
As you pointed out at some point, I can click-drag-highlight a list of @set commands and a query, and right-click-execute-and-export the results, today, in current production version.  So, what is the need for a new command?

(Somewhere there is another issue/ticket where we discussed the need to be able to:
Run @set command(s)
Run query
Export
Run more @set command(s)
Run query
Export
etc.
And to execute all of that as a linear script.  Currently dbeaver will execute all of the @set commands before running any queries, and that's not helpful.  
I'm not sure if THIS ticket, and a new @execute command, would be intended to solve that problem??)
Given that you say @execute command would be a lot of work... I want to be sure we're all thinking the same things...

**Comment by serge-rider** [comment]
Ok. 
I think #6041 will covert this ticket as well. Closing then.
