### ISSUE TITLE
[Oracle] Execution plan preview in Sessions sometimes break

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#4271]
For most of queries I get some of following errors:

1. This error seems to happen if there are bind variables used in query:

       SQL Error [17041] [99999]: Missing IN or OUT parameter at index:: 1
         Missing IN or OUT parameter at index:: 1
         Missing IN or OUT parameter at index:: 1

2. This seems to happen when session executes anonymous block:

       SQL Error [905] [42000]: ORA-00905: Missing keyword
         ORA-00905: Missing keyword
         ORA-00905: Missing keyword

3. This happens when table or view exists on another user schema, but query does not contain that schema name explicitly and object name is resolved against schema of currently connected user:

       SQL Error [942] [42000]: ORA-00942: table or view does not exist
         ORA-00942: table or view does not exist
         ORA-00942: table or view does not exist

    This error suggests you are not using `dbms_xplan` package to fetch a execution plan, but maybe run `EXPLAIN` for returned query instead. If this is the case it is wrong idea, because optimizer might choose different execution plan than actually used.

**Comment by serge-rider** [comment]
Actually I always thought that DBMS_XPLAN is used for plan formatting (in plain text) and it doesn't affect plan itself.
In any case we need to improve it (at least support parameters bindings and schema change).

**Comment by p91paul** [comment]
Exactly what I wanted to ask! The query currently executing can have a very different plan from the one returned from explain plan. An easy way this can happen is if you recalculate statistics after the original query started executing. EXPLAIN PLAN will then build the plan based on up-to-date statistics while the original query is stuck on the old plan. Sometimes Oracle even changes execution plan based on client settings, or because it really wants to :smile:.

**Comment by AndrewKhitrin** [comment]
This is considered to be an improvement. 
General plan explanation will be taken from different source, plan cache for example.
Planned for future release.

**Comment by maln0ir** [comment]
Could this be reopened? `ORA-00942` still occurs, because `EXPLAIN PLAN` is still used instead of querying `DBA_HIST_SQL_PLAN`.

**Comment by p91paul** [comment]
i believe it is tracked in #5943, however they mention another view to get plans.
