### ISSUE TITLE
Oracle jdbc connection keep-alive

### ISSUE THREAD

**Issue by premyslc** [dbeaver/dbeaver#4273]
Is there any option for oracle jdbc connection to keep connection alive. It's importat mainly for remote connection behind firewall. "Unused" connection is droped by firewall and dbeaver freezes on CPU.

**Comment by premyslc** [comment]
# # @ @

**Comment by leandro-ss** [comment]
What is it??

**Comment by tati-kru** [comment]
<img width="898" alt="screen shot 2018-09-28 at 13 53 06" src="https://user-images.githubusercontent.com/30336552/46204444-f5cf2600-c325-11e8-8382-b455ec238250.png">

**Comment by adrianag-redabogacia** [comment]
But it doesn't work. 
I tried with maximum value (32767 s) and it keeps disconeccting after 300 s or so. In my opinion our server is the responsible por dropping connections; but Dbeaver could provide as with an active keeping-alive feature.

**Comment by serge-rider** [comment]
You need to set it to a smaller value, e.g. 60. 

Keep-alive is the delay between connection ping attempts.  If your server closes connection after 5 minutes of idle then you must set Keep-Alive to a value less than 5 minutes (300 seconds).

**Comment by adrianag-redabogacia** [comment]
Wow, it worked. Thank you very much, @serge-rider. It was frustrating having to wait for the connection to reset, everytime I came back to search anything.
