### ISSUE TITLE
Large set of rows

### ISSUE THREAD

**Issue by surpavan** [dbeaver/dbeaver#4275]
While trying copy from the result set where rows are nearly 8lac with 5 columns -  copy has failed into excel.

Also, in one of my query output was 30lac rows -  dbeaver did not even show the rows -  it just gave as null; although an insert into a temporary table worked in the code but output to dbeaver has failed. 

Also, there is not memory (ram) spike or change too when downloading such large dataset.

**Comment by serge-rider** [comment]
How do you perform export?
If you have a lot of data you should use Export Data function instead of copying data directly in clipboard from results viewer.

**Comment by surpavan** [comment]
I used the copy option ctrl+shift+c.  Later I did the script run to csv export only.

**Comment by serge-rider** [comment]
You can also export to XLS format.
In order to fetch bigger resultset in memory you should increase maximum amount of memory available to DBeaver (https://github.com/dbeaver/dbeaver/wiki/Command-Line#vm-arguments)
