### ISSUE TITLE
5.2.1 Postgre Backup and Restore 

### ISSUE THREAD

**Issue by harrisyn** [dbeaver/dbeaver#4278]
Just noticed that when I backup a database and restore to another, most of the tables lose the primary keys and rows are duplicated in the target database.

I suspect it might have something to do with dropping the table before creating.

**Comment by harrisyn** [comment]
Updated to 5.2.1 and the same issue persists.
I had to manually create a new database and then restore the backed up database, to solve the issue.

This wasn't the case with at least version 5.1.x

**Comment by serge-rider** [comment]
- Do you mean native PG restore (pg_restore)? 
- Do you use any additional pg_restore parameters?
- Do you use your own (locally installed) pg_restore or the one preconfigured in DBeaver (on Windows it is pg_restore for PG 10.5)

**Comment by uslss** [comment]
there is no update on ticket almost a year.
Ticket closed.
if issue still actual for you, please, reopen the ticket.
