### ISSUE TITLE
Null pointer exception when opening DBeaver

### ISSUE THREAD

**Issue by mslourens** [dbeaver/dbeaver#4279]
When opening DBeaver (whether it's on Linux or Windows) I get this error message when it tries to check the current version of the app (I also get it when I go to Help -> Check for update:
`'DBeaver new version release checker' has encountered a problem. java.lang.NullPointerException`. 

This is with version 5.2.0.201809092115

**Comment by infectormp** [comment]
duplicate of https://github.com/dbeaver/dbeaver/issues/4261

**Comment by mslourens** [comment]
Sorry, I'll close my issue.
