### ISSUE TITLE
Unable to connect to mysql on localhost

### ISSUE THREAD

**Issue by lajeeshk** [dbeaver/dbeaver#4281]
I am trying to connect to mysql on loclahost
host : localhost
username : root
password : root

but getting this error

null,  message from server: "Host '127.0.0.1' is not allowed to connect to this MySQL server"

wonder how does this host is changed from localhost to ip address 127.0.0.1

but when connect to remote server using ssh tunnel it connects and works fine. only problem is with local server

**Comment by serge-rider** [comment]
DBeaver doesn't change target host name anywhere. It is always passed to the driver as is.
BTW what MySQL driver version do you use?

**Comment by stonebeaver** [comment]
### Problem Statement

Similar situation here. Had a working setup:

```mermaid
graph LR
DBeaver -- ssh --> db_host -- localhost --> db
```

After some weeks of successful work, DBeaver stopped at login to database with:

> Connection error  
> Access denied for user 'johndoe'@'127.0.0.1'

### Workaround

Let's assert, that we talk about the same problem. Ssh into your database box and...

```console
$ mysql -s -D foo -h localhost -u bar -p
Enter password: 
MariaDB [foo]> \q
$ mysql -s -D foo -h 127.0.0.1 -u bar -p
Enter password: 
ERROR 1698 (28000): Access denied for user 'bar'@'127.0.0.1'
```

Get the existing permissions for `bar@localhost`  (yours may vary):

```sql
MariaDB [foo]> show grants for bar@'localhost';
+---------------------------------------------------------------------------+
| Grants for bar@localhost                                                  |
+---------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO `bar`@`localhost` IDENTIFIED BY PASSWORD '********' |
| GRANT ALL PRIVILEGES ON `foo`.* TO `bar`@`localhost` WITH GRANT OPTION    |
+---------------------------------------------------------------------------+
2 rows in set (0.000 sec)
MariaDB [foo]> show grants for bar@'127.0.0.1';
ERROR 1141 (42000): There is no such grant defined for user 'bar' on host '127.0.0.1'
```

And clone them to `bar@127.0.0.1`  (according to yours):

```sql
MariaDB [foo]> grant usage on *.* to bar@'127.0.0.1' identified by password '********';
Query OK, 0 rows affected (0.009 sec)
MariaDB [foo]> grant all privileges on foo.* to bar@'127.0.0.1' with grant option;
Query OK, 0 rows affected (0.008 sec)
```

Check modification:

```console
$ mysql -s -D foo -h 127.0.0.1 -u bar -p
Enter password: 
MariaDB [foo]> \q
```

Your beaver should be happy now. 🦫

### Limits of this solution

The error occured in a dynamic real world project with multiple people working on it. I had no ressources to investigate the real cause or change that led to the problem. This approach is a pure workaround that enabled me to continue my work. wfm. ymmv.

This workaround modifies account and grant setup of the database. Please use with greatest caution in any non-isolated environment. I never said, that this proposed workaround would be safe or secure in your setup.

### See also

- <https://stackoverflow.com/questions/78556378/dbeaver-cant-connect-to-mysql-using-localhost-not-127-0-0-1/78561891#78561891>

**Comment by krei-se** [comment]
If others encounter this the problem is almost certainly that you enabled skip-name-resolve thus your client connecting from 127.0.0.1 will not resolve to localhost and not find grants defined for localhost.

**Comment by melroy89** [comment]
Its still an issue.. DBeaver / driver should **not** do a DNS lookup to convert `localhost` into `127.0.0.1`

Not sure why this is closed, but its the first experience I have with DBeaver right away. I'm just running Linux Mint.

**Comment by john8329** [comment]
Same thing here, it's a blocking issue with an unclear error message for something that should work out of the box. Happens with imported connections from DataGrip because they wrongfully include the SSH tab, while being not configured. Removing the tab solves the issue. More context in the error message might be necessary.
