### ISSUE TITLE
'Read results metadata' runs forever

### ISSUE THREAD

**Issue by queueseven** [dbeaver/dbeaver#4283]
Since some time (don't know which version exactly), when I run a query the first time on a MariaDB-Server, the following loading indicator appears:

![grafik](https://user-images.githubusercontent.com/3126597/46071360-22493d80-c180-11e8-9782-2376dbc5ed69.png)

This never ends; I have to stop the query by force, and when I run the query again it just works fine.

**Comment by serge-rider** [comment]
Could you check Query Manager (main menu Windows->Show View->Query Manager) and see what actual SQL is executed? Configure QM filters to see all queries (including metadata reading):
![image](https://user-images.githubusercontent.com/6398845/46079166-0608c900-c19f-11e8-8508-6596ee295266.png)

**Comment by queueseven** [comment]
Thanks for the info. I will check it and report once this happens again (since it doesn't happen always).

**Comment by queueseven** [comment]
OK, I did run a query:

> select * from anschrift
where strasse like 'Augustastr. 7 - 8'

and it happened again:

![image](https://user-images.githubusercontent.com/3126597/47089675-a2b00b00-d221-11e8-8e14-fd59d860421c.png)

I looked at the query manager while the query was still running:

![image](https://user-images.githubusercontent.com/3126597/47089708-b196bd80-d221-11e8-8b50-df198397be47.png)

Nothing to see here, I guess.

After some time the query was finished:

![image](https://user-images.githubusercontent.com/3126597/47089740-beb3ac80-d221-11e8-999e-eccfbc1a2c60.png)

and here's the query manager:

![image](https://user-images.githubusercontent.com/3126597/47089766-cc693200-d221-11e8-88ca-d5194a871196.png)

Doesn't seem to help much...

Running the meta queries manually (`SELECT kc.CONSTRAINT_NAME,kc.TABLE_NAME,kc.COLUMN_NAME,kc.ORDINAL_POSITION
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE k...`, `SELECT * FROM information_schema.STATISTICS WHERE ....`) is fast; just some ms.

**Comment by serge-rider** [comment]
Thanks for details (and sorry for late reply, we had too many new tickets recently)..

In fact I don't see any running queries or any queries which took much time. So there must be something else.
This become more tricky. I think the only way to resolve this is to make a thread dump once it stuck in "Read results metadata".
https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump
Please let me know if you need any hep with that.

**Comment by queueseven** [comment]
I tried to create thread dumps, but jstack always fails with 

> 
> Exception in thread "main" java.lang.InternalError: Remote thread failed for unknown reason
>         at sun.tools.attach.WindowsVirtualMachine.enqueue(Native Method)
>         at sun.tools.attach.WindowsVirtualMachine.<init>(WindowsVirtualMachine.java:62)
>         at sun.tools.attach.WindowsAttachProvider.attachVirtualMachine(WindowsAttachProvider.java:69)
>         at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
>         at sun.tools.jstack.JStack.runThreadDump(JStack.java:163)
>         at sun.tools.jstack.JStack.main(JStack.java:116)

I'll keep trying

**Comment by queueseven** [comment]
Sadly, no.

The task that takes so long is this:

![grafik](https://user-images.githubusercontent.com/3126597/48189981-c0b0ed00-e341-11e8-9f3c-962de73f9af9.png)

(maybe that information helps)

**Comment by uslss** [comment]
Hi @queueseven ,
is issue still actual for you on recent version (6.2.1)?

**Comment by uslss** [comment]
So, I'll close the ticket. If you'll see this problem on the last version - feel free to create a new issue.
Best regards :)
