### ISSUE TITLE
5.2.1 Error in resultset when ordering and filtering

### ISSUE THREAD

**Issue by txigreman** [dbeaver/dbeaver#4284]
Hi,

I have the following table:

```
CREATE TABLE `exp_codes_bags_manhattan_codes_requests` (
  `request_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `provider_id` int(10) unsigned NOT NULL,
  `name` char(20) NOT NULL,
  `status` enum('created','pending','completed','failed') NOT NULL DEFAULT 'created',
  `amount` int(10) unsigned NOT NULL,
  `error_code` int(10) unsigned DEFAULT NULL,
  `error_message` varchar(500) DEFAULT NULL,
  `created_at` int(10) unsigned NOT NULL,
  `modified_at` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`request_id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

In the resultset, if using the GUI I order by request_id desc and then filter by status = 'pending', I get this error:

> Query execution failed
> 
> Razón:
>  SQL Error [1054] [42S22]: (conn:6240180) Unknown column 'x.1' in 'order clause'
> Query is : SELECT x.* FROM vams.exp_codes_bags_manhattan_codes_requests x
> WHERE x.status = 'pending'
> ORDER BY x.1 DESC,x.status DESC

This is the error detail:

> SQL Error [1054] [42S22]: (conn:6240180) Unknown column 'x.1' in 'order clause'
> Query is : SELECT x.* FROM vams.exp_codes_bags_manhattan_codes_requests x
> WHERE x.status = 'pending'
> ORDER BY x.1 DESC,x.status DESC
>   (conn:6240180) Unknown column 'x.1' in 'order clause'
> Query is : SELECT x.* FROM vams.exp_codes_bags_manhattan_codes_requests x
> WHERE x.status = 'pending'
> ORDER BY x.1 DESC,x.status DESC
>   (conn:6240180) Unknown column 'x.1' in 'order clause'
> Query is : SELECT x.* FROM vams.exp_codes_bags_manhattan_codes_requests x
> WHERE x.status = 'pending'
> ORDER BY x.1 DESC,x.status DESC
>     Unknown column 'x.1' in 'order clause'
> Query is : SELECT x.* FROM vams.exp_codes_bags_manhattan_codes_requests x
> WHERE x.status = 'pending'
> ORDER BY x.1 DESC,x.status DESC
>     Unknown column 'x.1' in 'order clause'
> Query is : SELECT x.* FROM vams.exp_codes_bags_manhattan_codes_requests x
> WHERE x.status = 'pending'
> ORDER BY x.1 DESC,x.status DESC
> 

It works if I do it in the reverse order: first filtering, then ordering.

**Comment by serge-rider** [comment]
Thanks for the bug report.
