### ISSUE TITLE
Improvment highlighting selected words

### ISSUE THREAD

**Issue by Bullnados** [dbeaver/dbeaver#4285]
#222 
It is a rly nice and missed feature.
Is it possible to highlight only words, when u "select" the word (in notepad it is doubleclick)
At the moment words are marked immediately when cursors is in the word.
Idealy as an option, if someone want this behavior.

**Comment by serge-rider** [comment]
Good points.

![image](https://user-images.githubusercontent.com/6398845/46487582-148f5a00-c809-11e8-88fe-4acee8ffe421.png)

![image](https://user-images.githubusercontent.com/6398845/46487613-21ac4900-c809-11e8-92ba-e69d7789f1ad.png)
