### ISSUE TITLE
PostgreSQL : Timestamp wrong display

### ISSUE THREAD

**Issue by GAEREL** [dbeaver/dbeaver#4287]
hi.

I have a datatype defined in my base as 
`CREATE DOMAIN d_date_creation AS TIMESTAMPTZ DEFAULT now() NOT NULL;
`

When displayed in "result Panel" this kind of data is displayed as Time (only)
The date part is missing making reading difficult

**Comment by GAEREL** [comment]
Add on : DBeaver 5.2.0

**Comment by serge-rider** [comment]
Thanks for the bug report
