### ISSUE TITLE
Vertica: can't edit table Column name

### ISSUE THREAD

**Issue by BETEP0K1** [dbeaver/dbeaver#4288]
Version 5.2.1

I can change, for example, in MySQL, in the existing column "column name".
screenshot:    https://ibb.co/fL3jWp

But in Vertica it does not work, the field is not available for modification,
I can do it only through the SQL query.
screenshot:     https://ibb.co/dj31Bp

Is it bug?

**Comment by LonwoLonwo** [comment]
Implemented in scope with https://github.com/dbeaver/dbeaver/issues/11523
