### ISSUE TITLE
Blob editing on Oracle 11g

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#4289]
Hi Serge,

when I query a table on Oracle 11 and click on a blob field in the result set, it instantly gets marked as modified in DBeaver. Although I haven't modified anything.

I have to click on the "cancel" button in the grid footer to revert those putative changes.

DBeaver 5.2.1 on Mac OS X 10.13.6
Oracle 11g with ANSI Character set (not unicode)

Cheers

**Comment by serge-rider** [comment]
I think it is the same problem as in #4311
Will be fixed in the next version
