### ISSUE TITLE
Export For Query to Txt truncates column values when column name is short 

### ISSUE THREAD

**Issue by ericblais** [dbeaver/dbeaver#4292]
When exporting query result in Txt mode
if the length of the column name of a char column is less or equal than 
the length of the field defined in the database : it is truncated.

See example :

[column_problem.txt](https://github.com/dbeaver/dbeaver/files/2425172/column_problem.txt)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by ericblais** [comment]
Hi @serge-rider  , the same problem can be found in the default perspective.

Text view
![image](https://user-images.githubusercontent.com/40277078/48417421-bcf5df80-e720-11e8-9738-5aecbd08fbe4.png)

Grid view
![image](https://user-images.githubusercontent.com/40277078/48417551-06462f00-e721-11e8-884c-7dda582ccde3.png)
