### ISSUE TITLE
Foreign key/constraint isn't editable via GUI

### ISSUE THREAD

**Issue by Bullnados** [dbeaver/dbeaver#4293]
It seems that an existing foreign key is not editable(F4) with GUI
![grafik](https://user-images.githubusercontent.com/11041576/46166381-5a8d7080-c293-11e8-9910-43b209ffcd32.png)
After right click F4 shows that windows:
![grafik](https://user-images.githubusercontent.com/11041576/46166577-d1c30480-c293-11e8-8a94-326f822313df.png)
And here I cant edit the tables or columns

**Comment by Bullnados** [comment]
something new here?
Need morde infos?

**Comment by kseniiaguzeeva** [comment]
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/3400. We are going to implement it after 21.1.0 release.
