### ISSUE TITLE
DBeaver 5.2.1 Relation error

### ISSUE THREAD

**Issue by hellgorithm** [dbeaver/dbeaver#4297]
Hello, I successfully connects to a PostgreSQL server but when I tried to execute a simple select query, this error occured: `RROR: relation "public.mytable" does not exist`. I can view data via Right click table > "Edit Data" tho. I can also edit and save procedures.

DBeaver version : 5.2.1.201809240911
OS : Windows 10
PostgreSQL : 9.6

**Comment by hellgorithm** [comment]
![query failed](https://user-images.githubusercontent.com/5483695/46201699-60dd2480-c347-11e8-9485-61fefdcf29ad.png)

**Comment by serge-rider** [comment]
Perhaps you need to change active schema (see main toolbar)
