### ISSUE TITLE
Error in Generate SQL INSERT statement format

### ISSUE THREAD

**Issue by ilyasamorodov** [dbeaver/dbeaver#4298]
I have a table in my Cassandra database with map field of int:int
`CREATE TABLE api.test (
    id uuid,
    name text,
    permissions map<int, int>,
    ...
    PRIMARY KEY (id)
)`

I'm tryin to export row via Generate SQL -> INSERT and get this:
`INSERT INTO api.test
(id, name, permissions, ...)
VALUES('ce9f0b70-f843-41f1-80d1-afc732f7f2d0', 'Test', {'7':'1','18':'1','19':'1','20':'1'}, ...);`

which is not correct. I cannot insert it again due to error:
`com.datastax.driver.core.exceptions.InvalidQueryException: Invalid map literal for permissions: key '7' is not of type int
  Invalid map literal for permissions: key '7' is not of type int`

Correct statement should be:
`INSERT INTO api.test
(id, name, permissions, ...)
VALUES('ce9f0b70-f843-41f1-80d1-afc732f7f2d0', 'Test', {7:1,18:1,19:1,20:1}, ...);`

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
