### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by cesarmansur** [dbeaver/dbeaver#4303]
Hello. I've started using DBeaver recently after a lot of years using TOAD and I'm loving DBeaver. I can say now that I officially removed TOAD from my development environment. So, first of all I'd like to congratulate you for the great job you performed in DBeaver. It's quick, it's stable, it's easy to use and it's friendly interface. 
I'd like to ask you to implement some great features that in my opinon can contribute to DBeaver success.
1) Text indentation guides
2) Column text edit >>> already exist.
3) Display on the status bar the characters count of the selected word
4) SQL Recall (automatically save recent executed SQL, keep it after closing DBeaver and allow user to consult this list)
5) User SQL Quicklist (one can create a quicklist of saved SQL queries and easily load it from memory to editor using a keyboard shortcut that opens a drop-down list with the named queries)

Thank you!

**Comment by p91paul** [comment]
I believe 2 and 4 already exist: defaul shortcut to toggle rectangular selection should be alt+shift+a (it is a toggle, so you enable, select, edit, then disable to get back to normal selection). And you can get 4 from window -> view -> query browser (history is lost after closing dbeaver unless you have Enterprise version)

**Comment by cesarmansur** [comment]
p91paul, thank you! I'm still getting familiar to DBeaver. Tested item 2, worked fine! Regarding item 4, any chance to have this feature on free version?

**Comment by p91paul** [comment]
I don't know, I'm just a very happy user like you, not a dbeaver developer :smile:! However, I understand the need they have to offer more features in the paid version... If you were previously paying for TOAD, buying a dbeaver license should feel like getting a coffee :stuck_out_tongue_winking_eye:

**Comment by serge-rider** [comment]
4. You can see query history in SQL Execution Log tab (in SQL Editor). Or in Query Manager view (it keeps history for all editors/tools and actually 100% of SQL executed by DBeaver including internal system queries).

5. We have shortcuts for that. Maybe a bit different than in TOAD. You can see templates in Preferences->Database->Editors->SQL Editor->Templates.
To activate template type its name (or <kbd>ctrl+alt+space</kbd>) and press <kbd>TAB</kbd>.

**Comment by cesarmansur** [comment]
Hello serge-rider, thanks a lot. What about items 1 and 3 ?

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/48088158-47ff4300-e212-11e8-86bf-8afe419e1f39.png)

3 is not supported. Actualy I never saw suc hfeature in a text editor. We show just cursor position.

**Comment by cesarmansur** [comment]
Hello, item 3 is a very common feature in text editors.

Notepad++ example:
![image](https://user-images.githubusercontent.com/43681608/48093068-7ae70e00-e1f5-11e8-968b-da1ea0cad92f.png)


TOAD example:
![image](https://user-images.githubusercontent.com/43681608/48093221-efba4800-e1f5-11e8-8ee5-0c67b23189f5.png)
