### ISSUE TITLE
Error when trying to link a file to a custom project

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4304]
DBeaver - **Version 5.2.1 CE**
DBeaver JDBC driver: **jTDS or Microsoft**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014**

When I try to link a file to a newsly created custom project,, I get an error message:

> Unable to create link
> Cannot create linked resource '/PostgreSQL/Scripts/TestJoinX.sql'.  The parent
> resource is not accessible.

To view the misbeahviour:

**o** Start _DBeaver_
**o** View the Project tab by choosing the **Windows -> Projects** meny choice.
**o** Create a new project (in my case called "PostgreSQL").
**o** Right click on the **Scripts** folder in the new project and choose **Link File**.
**o** Choose a file you want to link.
**o** An error messages is shown and no file is linked.

The _DBeaver_ **.log** file contains:

> !ENTRY org.jkiss.dbeaver.model 4 0 2018-09-29 18:46:27.367
> !MESSAGE Unable to create link
> !STACK 1
> org.eclipse.core.runtime.CoreException: Cannot create linked resource '/PostgreSQL/Scripts/TestJoinX.sql'.  The parent resource is not accessible.
> 	at org.jkiss.dbeaver.ui.actions.navigator.CreateLinkHandler$1.execute(CreateLinkHandler.java:80)
> 	at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:107)
> 	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
> 	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
> 	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:128)
> 	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
> !SUBENTRY 1 org.eclipse.core.resources 4 77 2018-09-29 18:46:27.368
> !MESSAGE Cannot create linked resource '/PostgreSQL/Scripts/TestJoinX.sql'.  The parent resource is not accessible.

**Note**

If I try to link a file to the **General** project, everything works as expected.

**Comment by serge-rider** [comment]
Thanks for the bug report (missed this earlier)

**Comment by kseniiaguzeeva** [comment]
Verified
