### ISSUE TITLE
MacOS package installs with generic PRODUCT_ID

### ISSUE THREAD

**Issue by carlosefr** [dbeaver/dbeaver#4307]
On MacOS, the `dbeaver-ce-5.2.1-installer.pkg` package is installed under the generic name `PRODUCT_ID` instead of something identifiable like `io.dbeaver.dbeaver-ce`.

```
$ ls /var/db/receipts/PRODUCT_ID.*
/var/db/receipts/PRODUCT_ID.bom
/var/db/receipts/PRODUCT_ID.plist

$ pkgutil --pkg-info PRODUCT_ID
package-id: PRODUCT_ID
version: 5.2.1
volume: /
location: 
install-time: 1538334489

$ lsbom -ds /var/db/receipts/PRODUCT_ID.bom
.
./Applications
./Applications/DBeaver.app
./Applications/DBeaver.app/Contents
[...]
```

**Comment by serge-rider** [comment]
Thanks for the bug report. It is a bug in our PKG builder script

**Comment by carlosefr** [comment]
5.2.2 has been release, and this bug is still present in the `dbeaver-ce-latest-installer.pkg`.

**Comment by serge-rider** [comment]
Old records are still there, I'm not sure that we can remove PRODUCT_ID references automatically (`rm /var/db/receipts/PRODUCT_ID.*` should work though).

However
```
pkgutil --pkg-info org.jkiss.dbeaver
```
must return 5.2.2.

**Comment by carlosefr** [comment]
I had already removed the files before, but installing 5.2.2 put them back, that was what I was referring to.
