### ISSUE TITLE
[mssql] Cannot set VARBINARY column to NULL in data editor

### ISSUE THREAD

**Issue by piaste** [dbeaver/dbeaver#4311]
Repro steps:

```
create table vbtest (
  pk int primary key, 
  vb varbinary(200) null
)

insert into vbtest 
  (pk, vb) 
values 
  (1, hashbytes('SHA1', 'somepassword'))

```

Open the table in the dataset editor, right click the `vb` column and choose `Edit -> Set to NULL`. The column looks blank (not `NULL`) in the UI, and after refreshing the original values return.

The `Script` buttons shows this command:

```
-- Actual parameter values may differ, what you see is a default string representation of values
UPDATE foo.dbo.vbtest
SET vb=0x
WHERE pk=1 AND vb=0x go
```

which is clearly incorrect.

**Comment by serge-rider** [comment]
thanks for the bug report
