### ISSUE TITLE
Query builder generates broken query for column names with hyphen

### ISSUE THREAD

**Issue by boesi** [dbeaver/dbeaver#4312]
I have table and column names that contain a hyphen (I know it's a stupid idea).

The code generated by the query builder looks like this:
`...
FROM
    GERAETE g
INNER JOIN GERAETESET g2 ON
    g.Geraeteset - ID = g2.ID
...`

`Geraeteset-ID` should be set in backticks. For table names it works correctly.

**Comment by serge-rider** [comment]
This issue is already fixed in Early Access version (https://dbeaver.com/files/ea). And the fix will be included in 5.3 of course.
