### ISSUE TITLE
Issue with mapped drives/network locations on windows 10

### ISSUE THREAD

**Issue by ChrisForsythe** [dbeaver/dbeaver#4314]
Thanks for making dbeaver, it's great.

I have an issue with dbeaver 5.2.1.201809240911 on windows 10. Mapped network drives (drive letter representing a unc \\server\folder\subfolder path) do not work in this version. I had a project set up to a network drive in 5.0.5. 

A new project worked when specifying the unc path itself ( \\server\folder\subfolder\ ). However then when attempting to connect to an existing connection in the connections drop down and choosing all projects, it throws an error. I ended up deleting the previous project in order to continue, but thought it was worth mentioning.

Let me know if you have any questions. Hopefully it's a simple case to reproduce. I did read the contributing.md but it seems to be empty, apologies if this needed more information.

**Comment by uslss** [comment]
cannot reproduce it for now.
If it is still actual - feel free to reopen the ticket

**Comment by dezza** [comment]
I just tried today in WSL and I received a `SQLITE_BUSY` error. Not sure if its related to UNC paths and dbeakev or WSL. I imagine maybe dbeaver checks if someone already reads the file which is the case with WSL even for idle files from Windows perspective.
