### ISSUE TITLE
Dbeaver: Sub-Windows pop up relative to Main window

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#4315]
DBeaver - Version 5.2.0 CE
Operating System: Windows 10
JDBC Driver: mssql-jdbc 7.0.0.jre10
Database: Microsoft SQL Server Database

I've noticed that all the sub pop up windows for Dbeaver open up on the screen number where it was initially launched.
If we move Dbeaver to another monitor screen, let's say screen number 2, the sub pop up still open up on the initial screen number 1.

Can this be fixed please ?

**Comment by serge-rider** [comment]
I can't reproduce this problem (in my env popups are always opened on the same monitor where main window is located).
Please check how it works in the recent DBeaver version (6.3.x).

**Comment by uslss** [comment]
Verified.
6.3.4: All pop-ups are shown on the same monitor. Splash screen only is shown always on first monitor.
Ticket closed
