### ISSUE TITLE
Database Navigator, allow opening subtree with arrow keys (or space bar)

### ISSUE THREAD

**Issue by yennor** [dbeaver/dbeaver#4316]
In the database navigator, it doesn't seem to be possible to open a subtree using the keyboard. Only clicking with the mouse on the arrow ">" seems to work.
It would be great if with the arrow keys left and right a subtree could be closed respectively opened. Or also with the space bar.
That would increase the navigation speed tremendously.

**Comment by serge-rider** [comment]
Arrow keys works fine on Windows/MacOS.
DBeaver uses native OS controls for database navigator tree. They behave differently on different OSes.

What is your OS/windows manager?

**Comment by yennor** [comment]
I'm using Debian Linux Stable. With KDE Plasma

**Comment by TomaszKane** [comment]
KDE Neon (18.04) also have this problem.
BTW it was works a few version ago.

**Comment by grandfso** [comment]
I am also experiencing the arrows not working on MATE 1.20.3

**Comment by TomaszKane** [comment]
For me problem is fixed in 5.2.4.

**Comment by yennor** [comment]
yes. Works great. Thanks :-)

**Comment by serge-rider** [comment]
Most likely it was a side-effect of migration to Eclipse 4.9 + GTK2. 
5.2.4 uses GTK3 (GTK2 is legacy and won't be supported by Eclipse platform so this decision is final).

Thanks for checking this.
