### ISSUE TITLE
oracle timestamp column shows incorrect value

### ISSUE THREAD

**Issue by mnt1979** [dbeaver/dbeaver#4318]
Query running against an oracle table returns incorrect value in version 5.2.1.  Same query returns correct value in 5.1.6

Query ran in 5.2.1
SELECT MODELDATE FROM TEST.MY_ORA_TABLE WHERE MODELDATE IS NOT NULL AND MY_SPEC_ID = '41021-58049-68';
RESULT...
MODELDATE
[NULL]
[NULL]
[NULL]
[NULL]
[NULL]

Query ran in 5.1.6
SELECT MODELDATE FROM TEST.MY_ORA_TABLE WHERE MODELDATE IS NOT NULL AND MY_SPEC_ID = '41021-58049-68';
RESULT...
MODELDATE
2017-08-11 09:13:51.958
2017-08-12 00:30:11.541
2017-08-28 09:20:24.137
2017-10-09 10:40:51.184
2017-10-19 12:57:11.865

**Comment by infectormp** [comment]
dublicate of https://github.com/dbeaver/dbeaver/issues/4270
