### ISSUE TITLE
DBBeaver Connects to an older version of database

### ISSUE THREAD

**Issue by dbnex14** [dbeaver/dbeaver#4319]
In MSSQL Server, I connect to my local DB **MyDB** using following connection settings:

```Server Name: (localdb)\MSSQLLocalDB```

, that works fine, I check a **Table-A** which has some records I added, all fine and working.

In DBBeaver, to connect to same local DB **MyDB**, I use following:
```
Host: localhost
Database/Schema: MyDB
```

, that connects fine and all is working, too.  However, this shows an older version of **Table-A**.  I know that because I changed a column name in this table from **COL-1** to **COLUMN-A** and I added couple of records in it

So, on my SQLServer, **Table-A** has following
```
COLUMN-A
Record 1
Record 2
```

But on my DBBeaver, **Table-A** has following
```
COL-1
No records
```

So, it looks like while my SQLServer is connecting to the very latest version of **MyDB** database, DBBeaver is somehow connecting to an older version of **MyDB** with an old column name **Col1** which has no records in it.

**Comment by serge-rider** [comment]
Most likely these are completely different databases.
From DBeaver you are connecting to the local SQL Server instance, not LocalDB.
See this: https://github.com/Microsoft/mssql-jdbc/issues/769

Looks like Microsoft driver doesn't support LocalDB at all. 
jTDS driver may work but, honestly, I didn't test this.

**Comment by uslss** [comment]
There is no update almost a year.
Ticket is closed.
