### ISSUE TITLE
Sequences doesn't work with the standard MS driver

### ISSUE THREAD

**Issue by tati-kru** [dbeaver/dbeaver#4321]
1. Setup connection to MS SQL Server with standard Microsoft driver.
2. Open any schema in the database.
3. In the data viewer select Properties tab and click at Sequences sub-tab.

Expected result: The list of Sequences is shown
Actual result: "SQL Error: The "variant" data type is not supported. The "variant" data type is not supported."

**Comment by serge-rider** [comment]
The problem is in default SQL Server driver (6.2.2 in DBever EE)
7.0+ works fine. We'll update default driver version in CE and EE.
