### ISSUE TITLE
Process exit code: -1073741701 (when restoring postgresql database)

### ISSUE THREAD

**Issue by JTopanotti** [dbeaver/dbeaver#4322]
Hey,

Whenever I try to restore a postgresql database locally, i get process exit code: -1073741701.
I tried generating the dump through pgadmin and pg_dump.

**Comment by serge-rider** [comment]
DBeaver is shipped with PostgreSQL native client 10.5. 
It may be incompatible with some older PG server versions.
You can configure PG native client in connection properties dialog:
![image](https://user-images.githubusercontent.com/6398845/47878561-a9e53480-de2f-11e8-9db6-6783f3dda4a8.png)

**Comment by hheimbuerger** [comment]
Same issue here. One way to check is to open your `$HOME/.dbeaver-drivers/clients/postgresql/win` folder and running `pg_dump` from there directly. You're getting an error message as well, correct?

I'm not sure why the binaries that DBeaver downloads aren't working, but you can download new binaries from https://www.enterprisedb.com/products-services-training/pgbindownload and then put them into the same folder. I extracted `pg_dump.exe`, `pg_restore.exe` and `psql.exe` (just like DBeaver), and then I also extracted *all* 30ish DLLs into my folder -- I didn't bother figuring out which ones I really need. That made it work for me.

**Comment by bytesandnibbles** [comment]
Same issue here but when backing up. Running pg_dump on its own indicates that some DLLs are missing.

**Comment by gyzmau** [comment]
@hheimbuerger I got the issue a well. I did replace the binaries downloaded by Dbeaver by those downloaded from the link you gave, and it work  perfectly.

Thank you very much.
