### ISSUE TITLE
Question: How do I fix this font/dialog color problem?

### ISSUE THREAD

**Issue by bellingman** [dbeaver/dbeaver#4324]
See the attached screenshot. These side-tab element are highlighting badly, but I can't find the controls for them. You will notice I have reverse colors in the _editor_, but of course that shouldn't control these elements. 

- The Inactive tabs are most problematic, because ray/gray (fg/bg) is practically invisible
- The Active tab is ugly too, so I'd prefer the default (black/gray)

![image](https://user-images.githubusercontent.com/43825731/46432811-fdb30f80-c703-11e8-922a-053c65d8d537.png)

**Comment by serge-rider** [comment]
Looks like you are using dark color theme for editors but classic theme for everything else.
This glitch with tab coloring is a bug (it relies on text editor background/foreground colors).

BTW why don't you switch to dark theme for all controls?

**Comment by bellingman** [comment]
I am not using Themes at all, actually. I prefer the combination you see, however strange that may seem.

I tried changing to the Dark theme as you suggested-- and I lost all my customzed Editor colors. (Grrrr.) How to I save those, so I can use them even after changing themes?

**Comment by serge-rider** [comment]
It is hard to decide what color to use for inactive tabs.
