### ISSUE TITLE
Dropdowns in import cause app to go unresponsive

### ISSUE THREAD

**Issue by tim-field** [dbeaver/dbeaver#4325]
Using any of the drop downs in the import process breaks.

Dropdown seems to take focus, then not release it. i.e. I can't click on anything after this happens

![bug](https://user-images.githubusercontent.com/1326910/46455416-764ec480-c807-11e8-9278-4f7d08c7dfcd.gif)

Drop down still on my screen as I write this :) 

![image](https://user-images.githubusercontent.com/1326910/46455452-a0a08200-c807-11e8-9bc1-c2174e1a872f.png)

I'm running Ubuntu 18.04

**Comment by serge-rider** [comment]
Reproduced on Ubuntu 18
