### ISSUE TITLE
Feature request: read data in SQL console without immediate execution

### ISSUE THREAD

**Issue by rchar01** [dbeaver/dbeaver#4326]
I'm using `read data in SQL console` command as a quick way to create a select statement on table.
I think it would be nice to specify in options whether the execution should be immediate or not.

What do you think?

**Comment by serge-rider** [comment]
You can use context menu->Generate SQL->SELECT for this.

**Comment by rchar01** [comment]
Yes, but it requires copying SELECT to the editor.
Is there another solution for "quick SELECT"?

**Comment by rchar01** [comment]
OK, thank you.
