### ISSUE TITLE
Clickhouse field auto completion

### ISSUE THREAD

**Issue by ghuname** [dbeaver/dbeaver#4328]
Hi,

in previous versions of dbeaver we could write a select like this one:

select *
from  database.table

than we could delete "*" and type first few letters of the filed name and dbeaver would provide all fields from the database.table that starts with these few letters (auto-completion).

In version 5.3.0.201809092115 this is not possible anymore.
Is it intentionally or...?

**Comment by serge-rider** [comment]
Nothing was changed and auto-completion works as before in Clickhouse.
Note: you can't use database name as table name prefix. But you can use schema name. In fact databases are redundant in Clickhouse (there is only one database). And it is easy to mix them because there is database `default` and schema `default` in Clickhouse.

I'll hide databases in the driver configuration in the next DBeaver version.
Thanks for noticing.

**Comment by ghuname** [comment]
![image](https://user-images.githubusercontent.com/15207713/46475573-2ca1b200-c7e6-11e8-992a-cd880076c954.png)

I don't get any proposals.

**Comment by ghuname** [comment]
It works if i type "table." and then press ctrl+space.
It used to work without typing "table.".

select 		table.
from 		query.table

**Comment by ghuname** [comment]
When I execute "show databases" I get what you call schema.
We are using several databases that "show database" properly shows.
Can you please elaborate the difference between database and schema?

I also found that I can type "select * from" than first few letters of the table, ctrl+space, I will get the popup window in which I can select the table that will be prefixed with database name.

Now when I delete "*" and instead of it type full table name, than dot (".") I will get auto-completion popup. If I type "database.table." I will not get auto-completion. 

When I have a select from the single table, why auto-completion doesn't provide fields with ctrl+space without typing anything?

**Comment by serge-rider** [comment]
This shoudl be resolved with this fix: https://github.com/dbeaver/dbeaver/commit/1eb8d9782c7a1c66888003c967c2f3cc08439c2f

**Comment by ghuname** [comment]
I have just upgraded dbeaver to 5.2.2.201810071756 and I am confirming that everything works as expected.
