### ISSUE TITLE
Question: SQL editor: highlighting all occurrences of selected word (configurable) - Where?

### ISSUE THREAD

**Issue by cheekybuddha** [dbeaver/dbeaver#4331]
Hi,

Thanks for the addition of this feature.

I use a dark theme and the highlight colour is similar to main SQL text which renders it almost invisible when the auto selection happens.

I can't find where I can turn the feature off, or the property where I can configure the colour.

Can you point me in the right direction please?

TIA,

d

**Comment by serge-rider** [comment]
You can disable it on SQL editor preferences page:

![image](https://user-images.githubusercontent.com/6398845/46469202-6faa5800-c7db-11e8-891a-cec2321fa704.png)

At the moment color is not configurable.  I think we'll add extra option in #4285

**Comment by cheekybuddha** [comment]
Thank you!

I think this will be a really useful feature but, as you can see from the attached screenshot, it's less helpful at the moment with a dark theme!
![20181004192855_dbeaver](https://user-images.githubusercontent.com/19176116/46495110-77cebb80-c80c-11e8-9de1-09ebf9e959a5.png)

(Also, changing the option does not change on the currently active tab when the change is made - eg turn off the setting, click Apply/Close,  change to another tab, the new setting has taken effect, but go back to the original tab and the highlighting still happens.)

I look forward to the new colour option. 

Cheers,

d

**Comment by serge-rider** [comment]
Yep. It'll be here (in 5.2.2):
![image](https://user-images.githubusercontent.com/6398845/46498932-72329f00-c827-11e8-9bb3-87095d63f79f.png)

**Comment by cheekybuddha** [comment]
Brilliant! Thank you serge-rider!

Another suggestion: have a button/checkbox to toggle the feature in the main UI, so it can be turned on/off without having to go to the Preferences.

**Comment by serge-rider** [comment]
Perhaps we could add some settings in the context menu. I this some other mode toggles coudl there too.
Please create separate feature request for that.
