### ISSUE TITLE
Dbeaver: Isolation Dropdown disabled

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#4336]
DBeaver - Version 5.2.0 CE
Operating System: Windows 10
JDBC Driver: mssql-jdbc 7.0.0.jre10
Database: Microsoft SQL Server Database

The Isolation Level dropdown is disabled. I want to set my connection to readonly uncommited permanently.
Screenshot below

![image](https://user-images.githubusercontent.com/38669892/46505526-f3be0900-c7f6-11e8-9a77-2a6628cbe319.png)

**Comment by serge-rider** [comment]
It is a bug in connection editor. Isolation levels should be editable if you are connected to the database or clicked Test connection. 
I'll fix this and add a hint to this pref page.

Thanks for the bug report.
