### ISSUE TITLE
FR: Auto complete when table name is already written

### ISSUE THREAD

**Issue by Bullnados** [dbeaver/dbeaver#4339]
ATM: table.xyz if u start typing no auto complete popup with 'x', when table name was c&p

Wish: Pop-up also when u delete column name and write new one

**Comment by serge-rider** [comment]
Please provide more info (SQL query and insert position in it).

**Comment by Bullnados** [comment]
Seems to be okay now
cant't reproduce this with 5.2.4, postgres and dvdrental
