### ISSUE TITLE
Question: How to set trustStore properties for SSL connection

### ISSUE THREAD

**Issue by tgirsch** [dbeaver/dbeaver#4341]
I'm attempting to connect DBeaver to an Informix data source that uses SSL encryption. Per IBM's JDBC documentation, this involves three things.

1. Set SSLCONNECTION=true in the JDBC URL; this is easily accomplished in the "Edit driver settings" area, though it would be nice to be able to toggle this on a connection-by-connection database
2. Set the javax.net.ssl.truststore system property to point to the keystore that you created.
3. Set the javax.net.ssl.trustStorePassword system property to the password that you used for the certificate.

I have no idea how I'd go about accomplishing 2 and 3 from DBeaver. (The trust store has been created, and is verified working for ODBC connections over SSL.)

**Comment by serge-rider** [comment]
You can add them in dbeaver.ini file after -vmargs line.
Like this:
```
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Xms64m
-Xmx1024m
-Djavax.net.ssl.truststore=<path>
-Djavax.net.ssl.trustStorePassword=<password>
```

Also you can pass them as command line arguments after -vmargs argument.

**Comment by tgirsch** [comment]
Thanks, @serge-rider

**Comment by tgirsch** [comment]
Is there a default truststore to which I could just add the cert?

**Comment by aiguofer** [comment]
@tgirsch I think this depends on your distribution... in Fedora the default store is in /etc/pki/java/cacerts but it gets re-generated every time you update your java distribution. If you want your certs to be added each time, you can add them to /etc/pki/ca-trust/source/anchors/

That being said, this might be very different between distributions.

**Comment by pcfleischer** [comment]
I just wanted to add for me I wanted to make DBeaver use my mac keychain... I altered...

 `/Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini` 

and added ssl trust store type `-Djavax.net.ssl.trustStoreType=KeychainStore` which looks like this...

```
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Xms64m
-Xmx1024m
-XstartOnFirstThread
-Djavax.net.ssl.trustStoreType=KeychainStore
```

**Comment by ceinmart** [comment]
Hi, 
I'm running dbeaver 22.2 on windows, the instalation was by zip archive , where the jre become togheter. 
Trying to configure the SSL for my Informix connectio too. 

@serge-rider , the dbeaver doesn't recognize the **jssecacerts** into dbeaver\jre\lib\security . 
As far I know this should be a default behave of the java. 
I use this with lot of others java tools without issue. 

What I need to change on dbeaver to recognize the jssecacerts ? 

I can workaround seting the TrustStore + TrustPassword ,but to keep a clean DevOps here when I update my dbeaver, is easely just coping the jssecacerts.

**Comment by sebastianrothbucher** [comment]
Another solution is finding out which jre DBeaver runs with and using keytool to import the certificate in question to jre/lib/security/cacerts. On unix-like (Mac included), you can ouse `ps -aux | grep beaver` or `ps -A | grep beaver` - then use `keytool -import -file <cert> -keystore <dbeaverdir>/jre/lib/security/cacerts` Password for JREs is almost always *changeit*
