### ISSUE TITLE
Missing autocomplete on JOIN statements

### ISSUE THREAD

**Issue by lucielavickova** [dbeaver/dbeaver#4344]
Hello, 

I just downloaded dbeaver and it looked as a perfect tool until I realized that it does not suggest/auto-complete JOIN statements based on foreign keys when typing. 
Would it be possible to implement it? Or maybe it's just hidden somewhere in settings?

Thanks for your reply
Cheers

**Comment by boan-jfm** [comment]
Same issue, using PostgreSQL 10

**Comment by joeygribblegit** [comment]
Someone please help, all the new updates are great, but we've lost autocomplete on JOINs from previous versions. I'm stuck using an older version as this feature is key. I am using MySQL. 

example:
SELECT * FROM table1
JOIN table2 ON table1.(SHOULD AUTOCOMPLETE)

Thanks!

**Comment by LonwoLonwo** [comment]
![2020-09-01 19_14_52-DBeaver Enterprise 7 2 0 - _MySQL 8 0_ Script-18](https://user-images.githubusercontent.com/45152336/91878098-81c2f880-ec87-11ea-98ac-1b947ad9bae9.png)
works fine for me.
is it still actual for someone?

**Comment by boan-jfm** [comment]
Seems to work here (DBeaver 7.1.5)

**Comment by LonwoLonwo** [comment]
@boan-jfm thanks for answer! 

if someone has a problem again, then you are free to reopen the ticket

**Comment by AnrDaemon** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/6532485/24ebf98b-a813-4af1-a21f-14c879af9ee6)

No suggestions whatsoever.
