### ISSUE TITLE
Duplicated entries in 5.2.2  

### ISSUE THREAD

**Issue by kiravi** [dbeaver/dbeaver#4345]
The main DBeaver menu has duplicated entries.

![dbeaver_preferences](https://user-images.githubusercontent.com/5796204/46588203-94adfd80-ca5d-11e8-8411-279dfa7f1892.jpg)

**Comment by serge-rider** [comment]
I can't reproduce this. 
Potentially this may happen if you have Eclipse plugin version along with standalone version.
Could you try to reset workspace UI settings? (https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)

**Comment by kiravi** [comment]
Fixed.  This had to do with adding other DBeaver support sites such as office integration etc. once I uninstalled them they went away.

**Comment by serge-rider** [comment]
Yep, this is also possible. Also may be a part of glitch with localizations.

Thanks for report anyway.
