### ISSUE TITLE
Feature Request: On driver updates - add option to auto check for updates on drivers

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#4347]
I upgraded dbeaver and noticed that there was a upgrade of mssql driver version. However when I checked the connection it still was set to be 6.2.2 in the installed driver.

Then I tried to run update/install inside driver settings but it still showed 6.2.2 driver version to be updated/installed.

To get around all of this I had to readd a connection after removing 6.2.2 driver completely and reinstall dbeaver. Now the version is 7.0.0 after doing a bunch of extra steps.

Having some sort of interface where all driver updates are available would be good. Therefore chosing to upgrade driver or not depending on need.

**Comment by uslss** [comment]
It is already implemented
![image](https://user-images.githubusercontent.com/31996417/88194457-8b4c5000-cc47-11ea-9014-e61e9aa602de.png)
