### ISSUE TITLE
DBeaver: SQL Editor Autocomplete

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#4350]
DBeaver - Version 5.2.2 CE
Operating System: Windows 10
JDBC Driver: mssql-jdbc 7.0.0.jre10
Database: Microsoft SQL Server Database

EXEC is used to execute stored procedure.
When I type EXEC and then press CTRL+SPACE for autocomplete, nothing shows up in the drop down.
Autocomplete works for all other statements.
This might be a bug. Please check.

**Comment by DragonStorm97** [comment]
Hi,
this was mentioned previously.
EXEC is a SQL*PLUS command.
please use CALL to call/execute procedures.

**Comment by serge-rider** [comment]
@ascendhans There is no any special auto-completion for CALL/EXEC keywords at the moment.
I'll add stored procedures/function in the proposal list for them.
