### ISSUE TITLE
[Bug] Ctrl+9 - connection dialog - does not reconnect to current connection on enter

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#4351]
**Version:** 5.2.2 CE
**OS:** Windows 10

**Description:**
Keeping current script open and disconnecting the connection. Trying to choose the same connection again will not allow it to reconnect from connection dialog. You have to force a reconnect from Database -> Reconnect

**Screenshot/Recording:**
![2018-10-08_21-27-11](https://user-images.githubusercontent.com/383031/46629499-52f68300-cb41-11e8-986e-62eead8ebccc.gif)

**Comment by serge-rider** [comment]
Maybe you have option "Connect on editor activation" option turned off? In that case connection won't be automatically opened by SQL editor. But it may be opened on query execution.

Check Preferences->Database->SQL Editor.

**Comment by nmat** [comment]
I did check and it is turned on.

Main reason I reported it is because many times I disconnect the connection to avoid having uncommitted changes in the editor or disconnect all connections. However connecting to the same connection as is listed as active...then a reconnect wont happen.

On Connecting to a different database then it does do another connect.

**Comment by nmat** [comment]
This only happens on Ctrl+9, choose same connection as "is active but disconnected", press enter.

**Comment by nmat** [comment]
**Another video might explain it a bit more?**
![2018-10-08_23-29-24](https://user-images.githubusercontent.com/383031/46634761-36167b80-cb52-11e8-87df-3f116d72b60c.gif)

**Preferences:**
![dbeaver_2018-10-08_23-31-48](https://user-images.githubusercontent.com/383031/46634836-95748b80-cb52-11e8-8280-9e873f13fae0.png)

**Comment by serge-rider** [comment]
Well, yes. 
Basically it shouldn't reconnect. Because you don't change the connection, it remains the same. So not action was performed.
So this doesn't look like a bug. And I'm not sure that we should change current behavior.

Maybe you could just assign some shortcuts to Connect/Disconnect actions to simplify this?

**Comment by nmat** [comment]
Hmmm if I may I ask....what is the purpose of not reconnecting or at least ask to reconnect?

Of course I can bind a keybinding...just curious to why it would not connect when telling the connection to go to that specific connection again?
