### ISSUE TITLE
[Feature request] Show cursor location in packge editor

### ISSUE THREAD

**Issue by DragonStorm97** [dbeaver/dbeaver#4355]
Can we have the cursor position shown in the bottom bar in the package editor, as it's shown in the SQL editor?
![in SQL Editor](https://user-images.githubusercontent.com/11361357/46663610-d4402b00-cbbe-11e8-88a4-d25068484a4e.png)

**Comment by serge-rider** [comment]
Good point.
Thanks for noticing.
