### ISSUE TITLE
Missing MongoDB option

### ISSUE THREAD

**Issue by u02sgb** [dbeaver/dbeaver#4356]
I just installed DBeaver from the Eclipse marketplace, Version: 5.2.2.201810071756.

When I go to add a connection I have no option for MongoDB.  From looking at the documentation it look like it should be in the list.  Is there a way I can add it via the Driver manager?

Cheers,
  Stuart.

**Comment by u02sgb** [comment]
These are my options for "New Connection".

![image](https://user-images.githubusercontent.com/517545/46680285-a9ff6500-cbe0-11e8-8ed1-68565e804232.png)

**Comment by tati-kru** [comment]
Hello @u02sgb,

MongoDB is available for DBeaverEE only. You can download it on the Eclipse marketplace as well.

**Comment by u02sgb** [comment]
Thanks that makes things clearer!  The information for DBeaver in the market place should maybe be updated though.  It states it's free and includes MongoDB (screenshot below).

![image](https://user-images.githubusercontent.com/517545/46681726-c18c1d00-cbe3-11e8-94e1-f49e42f4aeb6.png)

**Comment by tati-kru** [comment]
@u02sgb Thank you for the note. We will edit it.

**Comment by serge-rider** [comment]
Funny thing that I never reviewed this description, just added new dbs from time to time. And Mongo extension was really there in 2013 o_O

Fixed
