### ISSUE TITLE
DBeaver query very slow when limit is not used, even though fetch size and use fetch-size are set.

### ISSUE THREAD

**Issue by jyinpci** [dbeaver/dbeaver#4361]
With v5.2.0 and v5.2.2, the query of a simple table is very slow.  If I use LIMIT 200 explicitly with the query, the query takes only 16ms to return the 200 records.  But if the LIMIT is not specified, it would take 8 seconds to get the 200 records (as set in fetch-size).  The table only has about 1.6 million records.  Is there anything I should set in properties?

Thanks in advance for any help!

John

**Comment by serge-rider** [comment]
What is your database?

**Comment by jyinpci** [comment]
Sorry, I should have made that clear.  It is Postgresql 9.3.

Thanks,
John

**Comment by jyinpci** [comment]
A little more information.  I tried v5.1.2 and experienced the same issue.  The difference is, however, with v5.1.2 if I check "Use SQL to limit fetch size" under Result Sets option, the query would be very fast.  This selection did not help with v5.2.2.

**Comment by jyinpci** [comment]
Thank you very much for your response and time in looking into this.  

Yes, using LIMIT 200 always makes it super fast (~16ms) regardless which version of DBeaver is used.

Just want you to know that DBeaver is one of the best applications that I have used.

**Comment by serge-rider** [comment]
Hmm. What PostgreSQL driver do you use?
Note: don't use PostgreSQL Generic or PostgreSQL Legacy unless you absolutely have to. 
Use the default PG driver with elephant icon:
![image](https://user-images.githubusercontent.com/6398845/46768359-90e5d980-ccf0-11e8-84e3-99a87ccd7028.png)

**Comment by jyinpci** [comment]
Yes, I am using PostgreSQL driver.  However, we need to use the following libraries to make it work:
- postgis-jdbc-2.2.1.jar
- postgis-jdbc-jtsparser-2.2.1.jar
- postgresql-42.2.1.jar

**Comment by chomam** [comment]
i have same problem with vertica, heres my comment i put in issue https://github.com/dbeaver/dbeaver/issues/4234
:
this is still an issue with DBeaver 5.2.2

"select * from large_table" hangs,

looking at sql history in vertica : query_requests view, the query is "select * from large_table" so is fetching all rows

whilst in DBeaver 5.1 it's "select * from large_table limit 200"

Using vertica 9.0 and vertica jdbc 9.1

DBeaver settings are default: Result fetch size 200, Use SQL to limit fetch size unticked - enabling this seems to work.

Did default behaviour for "Use SQL to limit fetch size" changed in DBeaver 5.2 ?

**Comment by jyinpci** [comment]
Just tried 5.2.3 and it was still very slow.  It took 1m35s to query 200 records from a well-indexed table (Postgresql 9.3).  With LIMIT 200 specified in SQL, it was instantaneous.

**Comment by serge-rider** [comment]
Ok.
Could you check what exactly SQL query DBeaver executes when you enable "Use SQL to  limit fetch size"?
You can see it in Query Manager view or in Execution Log tab of SQL editor. 

Also - is this just plain PostgreSQL 9.3 or it some PG-based database (like Vertica or Greenplum)?

**Comment by jyinpci** [comment]
It is to a plain Postgresql 9.3 server.  The SQL executed is

 

SELECT message_id, correlation_id, message_type, message_subtype, sender, recipient, sender_correlator, recipient_correlator, state, created_time, transaction_id, unique_transaction_id, message_seq, stash, defer_count, last_updated_time 

FROM public.message where 

message_id > 1

--and sender_correlator not like 'MON-%' 

order by message_id desc

 

message_id is the primary key – indexed by default.

 

Thanks,

John

**Comment by serge-rider** [comment]
It was a bug in the query parser. 
LIMIT wasn't used because query contained UPDATE in the column name.
See fix in 5.3
