### ISSUE TITLE
Some visualization glitch 

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4362]
![delete1](https://user-images.githubusercontent.com/799021/46717638-4c672900-cc71-11e8-84b5-07e9279aa355.jpg)

suppose brown line at the bottom should not be hidden

**Comment by serge-rider** [comment]
This is handled in Eclipse in BasicSplashHandler..

**Comment by tchibatron** [comment]
Unfortunately not yet. This reproduces on Linux. [Here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=521203) is a bug.

**Comment by uslss** [comment]
Eclipse bug. Ticket is closed.
