### ISSUE TITLE
No proposals 

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4363]
![delete1](https://user-images.githubusercontent.com/799021/46718377-aff25600-cc73-11e8-8fdb-d7e6f0ba3dd2.jpg)

```sql
SELECT t0.*, t1.*, t2.* FROM (
WITH consumed AS ( SELECT
	*,
    -- If configuration is changed and user consume different amount of same resource
    -- We MUST select that with maximum amount
    max(amount) OVER w                             as max_amount,
    -- round(cast(sum(ratio) OVER w  as numeric), 5)  as ratio
    -- Currently we count whole day and ignore actual resource usage
    24                                             as sum_ratio
  FROM consumed_resource
  WINDOW w as (PARTITION BY resource_uuid, resource_type_id, startdate, enddate)
)
SELECT
  id, domain_uuid, resource_uuid, resource_type_id, startdate, enddate,
  max_amount as amount,
  sum_ratio as ratio
FROM consumed
WHERE amount = max_amount
) t0 
LEFT JOIN allocated_resource t1 ON ( t1.resource_uuid = t0.resource_uuid ) 
LEFT JOIN provisioning_agreement t2 ON ( t2.uuid = t0.domain_uuid ) 
WHERE ( t1.id IS NOT NULL ) and t0.dom 
ORDER BY t0.domain_uuid, t0.startdate, t0.resource_type_id
```

database is postgres
dbeaver: 5.2.2ce

**Comment by KES777** [comment]
![__](https://user-images.githubusercontent.com/799021/47201838-e884e480-d383-11e8-82f2-c342e50834f8.jpg)

**Comment by serge-rider** [comment]
This happens because our SQL parser fails to parse such complicated query and to extract table info from.
In first case t0 isn't a table but a result of sub-select - DBeaver doesn't support semantical SQL parse yet.
In second case - it is not clear what object do you mean. Is it  column of table operation? If so then you should use alias for it. Or it is some function?

**Comment by uslss** [comment]
There is no update for almost a year.
Ticket is closed.
If issue is still actual for you feel free to open new ticket.
