### ISSUE TITLE
can not select by double click

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4364]
WHERE ( t1.id IS NOT NULL ) and t0.domain_uuid = '3c3375c8-f08b-44f5-a735-9c3201c4339d'

triple click on UUID highlight whole line. 

It would be handle to highlight UUID for triple click

**Comment by DragonStorm97** [comment]
Triple click highlighting the whole line is a pretty standard action.
Notepad++ as well as Visual studio do this,
not sure if breaking the seamlessness would be worth the benefit of selecting all text within a literal.
does seem a neat scenario for a shortcut though.

**Comment by KES777** [comment]
No. The standard is that that next click selects more. 

Thus four consecutive clicks can select whole line.

When you clicks more: the whole `QUERY` can be selected

**Comment by serge-rider** [comment]
@KES777  Honestly I never saw such editor although I can believe it exists. Anyhow this is the default behavior of all Eclipse text editors and I'm afraid I can't change it.

**Comment by KES777** [comment]
so we should blame Eclipse to improve behavior =)
