### ISSUE TITLE
Bug : Impossible to save this datetime : "2019-03-31 02:00:00"

### ISSUE THREAD

**Issue by Mynameismynameis** [dbeaver/dbeaver#4366]
Impossible to put this UTC datetime in a table : "2019-03-31 02:00:00"
After saving, this value is allways and automatically replaced by "2019-03-31 03:00:00"

**Comment by KES777** [comment]
belongs to #4181

**Comment by Mynameismynameis** [comment]
I have just undestood that DBeaver uses the time in the computer that is installed (French timezone for me).
And "2019-03-31 02:00:00" is exactly the start of Daylight Saving Time (Summer Time) in France in 2019. 
That's why "2019-03-31 02:00:00" becomes automatically "2019-03-31 03:00:00".

By changing the clock of my PC and restarting DBeaver, it works but it is not practice.
There is another way to do it only for DBeaver instead, I found this solution that works for me 👍 :

Close DBeaver.
Go to the DBeaver shortcut.
Right-click on it ► choose Properties ► in the Target box, add to the end of the target : -vmargs -Duser.timezone=UTC

It results in something like this:
C:\......\......\DBeaver\dbeaver.exe -vmargs -Duser.timezone=UTC

By running DBeaver now, the times appear in UTC and "2019-03-31 02:00:00" stay "2019-03-31 02:00:00".

**Comment by lemon-juice** [comment]
Another way to solve the problem is to turn on Native date/time format in Preferences > Database > Result Sets > Data Formats.

**Comment by Mynameismynameis** [comment]
> Another way to solve the problem is to turn on Native date/time format in Preferences > Database > Result Sets > Data Formats.

@lemon-juice : thanks for your contribution, but your proposition does not worked for me. Indeed, this option was already activated when the issue occured.
