### ISSUE TITLE
Query editor lowercases keywords

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4367]
After typing `LEFT` and space the keyword become `left`

There is no option at editor's preferences to disable this behavior (General->editors->text editors)

**Comment by lacanoid** [comment]
I experienced this, too

**Comment by serge-rider** [comment]
We've changed preference pages recently (because now we have too many SQL editor preferences)

![image](https://user-images.githubusercontent.com/6398845/47936364-77e6d780-deee-11e8-95a9-5cea8a732cac.png)
