### ISSUE TITLE
SQL formatter adds spaces in string literals for Hive

### ISSUE THREAD

**Issue by miromir2217** [dbeaver/dbeaver#4368]
When I try to format an SQL query containing string literals written with double quotes, the formatted query changes the literal by adding a space at the start and at the end of it. Example:

"MAGIC" is formatted to " MAGIC ".

I have observed this issue only in an Editor for an Apache Hive connection.

**Comment by serge-rider** [comment]
Yep. This is because Hive driver is quite buggy, it says that it doesn't support quoting at all and yet returns identifiers quoted with ` character. Anyhow, this can be fixed in formatter itself.
Thanks for the bug report.
