### ISSUE TITLE
Controls are placed not logically

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4369]
We editing sub on one tab, but `SAVE` button is placed on another

![delete1](https://user-images.githubusercontent.com/799021/46747620-7264eb80-ccba-11e8-9363-62558b4f8b4f.jpg)

`save` must be on `source` tab

**Comment by serge-rider** [comment]
Save button saves all changes you made in the current editor (on any tab). It is the actually the same as <kbd>ctrl+s</kbd> and main menu File->Save command.
That's why it is in the bottom editor toolbar.

**Comment by serge-rider** [comment]
@offstate Agreed. Will make editor controls more consistent,
