### ISSUE TITLE
Windows Registry modification for Explorer right-click to open SQL files in editor? 

### ISSUE THREAD

**Issue by spinjector** [dbeaver/dbeaver#4370]
I've searched here for any issues relating to this, but did not find anything. I would like to set Windows Explorer to open SQL files in a DBeaver editor window when the file is double-clicked (or Open/Open With...). But if dbeaver.exe is chosen, this gives a big error.

I seem to recall the default action for a filename passed to Eclipse is assume it's Workspace file. So this explains the big error. So I googled and found the list of DBeaver command line options here:
https://github.com/dbeaver/dbeaver/wiki/Command-Line

This shows the simple addition of "-f" before the filename will accomplish my goal, but only in the Windows Run box. So then I wander my way into the Windows Registry and make the following change:
HKCR\Applications\dbeaver.exe\shell\open\command\default=""C:\Program Files\DBeaver\dbeaver.exe" -f "%1" -nosplash"

...and thus I get what I wish: double-click SQL files in Explorer, and they open in DBeaver.   ![heart](http://cdn2.iconfinder.com/data/icons/diagona/icon/16/034.png)

But is this correct? It does work, but is there a more accepted way by other DBeaver users..?

For others who wish to make this change, here is the Windows REG text I exported from my registry:

Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Applications\dbeaver.exe\shell\open\command]
@="\"C:\\Program Files\\DBeaver\\dbeaver.exe\" -f \"%1\" -nosplash"

**Comment by serge-rider** [comment]
Yes, this is the correct way to associate SQL files with DBeaver.
However its may be better to use following registry patch:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.sql]
@="dbeaver"
```
It just associates .sql fiels with dbeaver application which is already added in registry by installer.
Note: it will work only if you install DBeaver using automatic installer.
