### ISSUE TITLE
Database Object search with wildcards broken

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#4373]
Using ctrl-shift-d to search objects returns no results while using the * wildcard character. Currently only way it works is if I write the prefix, wait for the list to load, then further characters inserted will perform a fuzzy search on the loaded results.
Using 5.2.2, this worked fine in 5.2.1.

**Comment by p91paul** [comment]
A gif to better explain myself:
![ctrl_d](https://user-images.githubusercontent.com/2157006/47794272-6cde4c80-dd20-11e8-8f81-705cf122019c.gif)

**Comment by serge-rider** [comment]
Thanks for the bug report (and reminder)
