### ISSUE TITLE
Text view misaligned if a column contains tabs

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#4374]
If a column contains the tab character, it gets displayed as 1 to 4 spaces (it is not fixed, it aligns to the next 4-chars tabstop). However, it is counted as 1 char and this means that row will have misaligned columns after the one containing the tab char.

It should always show as 4 spaces, and counted accordingly when showing in text mode.

**Comment by serge-rider** [comment]
Why are you so sure about 4 spaces? I think this is still depends on your environment (what tab size was used when text was added into database).
Looks like we need yet another configuration option for plain text presentation.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/47937655-77504000-def2-11e8-94e5-281e3b1715c2.png)

**Comment by p91paul** [comment]
Yeah 4 was not important, what I meant is that it should not be of variable width depending on the next tabstop. But then again, others could have a different opinion. Not really important though, grid alignment was the main issue. Thanks!
