### ISSUE TITLE
eclipse marketplace in standalone distribution

### ISSUE THREAD

**Issue by habamax** [dbeaver/dbeaver#4375]
Is it possible to include eclipse marketplace to the standalone dbeaver?

dbeaver has quite a frequent updates (which is very good!) but after each update I have to reinstall all extensions I had. (for example Emacs+)

So I have to install eclipse marketplace first and then emacs+ and other extensions.

Or is there another way to carry over all extensions to a new dbeaver installation?

Thx.

**Comment by serge-rider** [comment]
We already include marketplace extensions in EE version. The only concern is binaries size (as marketplace has quite a few dependencies on other Eclipse plugins).

But maybe something has changed since I test it last time. I'll see what can we do..
