### ISSUE TITLE
URL template no longer editable for Redshift connections

### ISSUE THREAD

**Issue by gercograndia** [dbeaver/dbeaver#4376]
Hi,

Just upgraded to version 5.2.2, and I noticed that for Redshift connections the URL template is no longer editable. See the screenshot below.
![image](https://user-images.githubusercontent.com/432439/46785832-46398100-cd33-11e8-8a62-80c210f6b587.png)

It used to be editable, and it still is for other connection types. This is important as in order to make use of IAM authentication with redshift, the url template must be altered.

This is how it looked in the previous version:
![image](https://user-images.githubusercontent.com/432439/46785900-7bde6a00-cd33-11e8-8a66-c5fe270bef1d.png)

Thanks,
Gerco

**Comment by serge-rider** [comment]
Thanks for the bug report. Indeed Redshift URL must be editable (while standard PostgreSQL URL shouldn't because it is auto-generated according to connection parameters).
