### ISSUE TITLE
TRUNCATE TABLE on production mode

### ISSUE THREAD

**Issue by greenpeas** [dbeaver/dbeaver#4377]
Postgresql.
Если соединение в режиме Production, то после TRUNCATE TABLE через контекстное меню просто висит, пока не закроешь окно и не нажмешь Commit вручную. Может быть как-то сделать тут автокомит?
![image](https://user-images.githubusercontent.com/3856344/46792508-35493980-cd4c-11e8-9f63-e0003b292f65.png)
По началу я думал, что БД зависла. А оказывается требуется ручной комит. Я в курсе, что в Prod режиме в настройках ставится именно ручной комит. Но тут вроде я использую инструмент из контекстного меню, где он кучу раз все спросит.

**Comment by serge-rider** [comment]
Good point. I'll add extra option to tools dialog:
![image](https://user-images.githubusercontent.com/6398845/47096754-89ff1f80-d238-11e8-93be-cbb6b5c2dd2a.png)
