### ISSUE TITLE
Wrong time zone

### ISSUE THREAD

**Issue by datopalov** [dbeaver/dbeaver#4379]
Wrong time zone

**Reproduce steps:**
Run query: SELECT current_setting('TIMEZONE');
Or run query: show timezone;

**Expected result:**
GMT

**Expected result simulated in:** 
pgadmin version 3 and 4.
our database is actually GTM

**Actual result:**
Europe/Helsinki

**Info:**
Windows 10 64 bit
Postgresql 10
DBeaver Community Edition 5.2.2 Windows 64 bit (installer + JRE)

**Comment by serge-rider** [comment]
In fact it is not a bug but a feature. PostgreSQL JDBC driver always shows all date/time values in local (client) timezone.
Check this: https://stackoverflow.com/questions/18447995/postgresql-9-2-jdbc-driver-uses-client-time-zone

If you need to see dates in GMT (UTC) timezone then you can switch DBeaver process into UTC. 
Add `-Duser.timezone=UTC` in the end of dbeaver.ini file.
