### ISSUE TITLE
SQL Editor completion deletes text in front of it

### ISSUE THREAD

**Issue by ryguy40** [dbeaver/dbeaver#4380]
Hi, when I use DBeaver and I allow the code completion to assist entering code, it deletes text that is immediately in front of the cursor upon insert. I have some screenshots to illustrate:

If I have this query written:
![debeaver insert 1](https://user-images.githubusercontent.com/42976290/46827041-9b8e8600-cd65-11e8-8c7f-735841fc528a.PNG)

But I want to insert another field in between the two, and I place my cursor right in front of the `c.`, start typing, and allow it to complete the code:
![debeaver insert 2](https://user-images.githubusercontent.com/42976290/46827055-a2b59400-cd65-11e8-8e8b-a8a72686d93e.PNG)

Then it deletes the `c`:
![debeaver insert 3](https://user-images.githubusercontent.com/42976290/46827058-a517ee00-cd65-11e8-8e08-4bc9f2072d19.PNG)
What I think it should say after insert: `c.INACTIVATED_DTc.CONTACT_NAME`
What it actually says after insert: `c.INACTIVATED_DT.CONTACT_NAME`

Is this a feature or a bug? Is there a way to change it?

**Comment by serge-rider** [comment]
Agreed, this should be improved.

**Comment by offstate** [comment]
it's not that simple as it looks. This behavior has been changed several times already. 
Sometimes it is needed that the rest of the word be erased and sometimes that it be preserved.
I use Netbeans and when I need to save the rest of the word I press Enter to select suggested word; and I press Ctrl+Enter to replace it.
I more often use the variant with replacement.

**Comment by serge-rider** [comment]
@offstate yep, this is also a good point. Unfortunately I can't easily start using different completion shortcuts with different behavior because it is not supported by the platform. Also it is not obvious that such advanced shortcuts exist.
Making this behavior configurable is also not a good idea.
However most of IDEs do not use replacement in such cases.

I think that we could try this: do not replace the word to the right only if cursor is not in the beginning of the word.
I.e.
c.|word - won't replace `word`
c.w|ord - will replace `ord` with selected proposal.

WDYT?

**Comment by ryguy40** [comment]
I've never seen behavior where a text editor replaces the text next to your cursor except when you've pressed the 'insert' button to toggle typeover mode. I'd venture to say most people do not expect their autocomplete text editor to typeover their text by default. In fact I am surprised to hear anyone defend this behavior.

> "In that case he could just press left arrow button to leave a space between fields."

Well, yeah, if I knew it was going to delete my text. I have a habit, however, of placing my cursor right where I want to start typing my text so it's hard to remember to place my cursor to the left of the space rather than to the right. Further, if I wanted it to delete my text I would've selected the text I wanted to type over instead of just placing the cursor with no selection.

**Comment by serge-rider** [comment]
Well, after all I decided to make it configurable. By default word replace will be disabled.
![image](https://user-images.githubusercontent.com/6398845/47258737-36930880-d4a8-11e8-9313-caee3af55afc.png)

If anybody have better idea - please share :)
