### ISSUE TITLE
Redshift column encoding

### ISSUE THREAD

**Issue by SZubarev** [dbeaver/dbeaver#4388]
If Redshift driver returns columns encoding (compression type) it would be useful to have such information in table columns view

**Comment by serge-rider** [comment]
https://docs.aws.amazon.com/redshift/latest/dg/r_SVV_TABLE_INFO.html

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/50556878-d7474500-0cef-11e9-9665-b78b0b37a147.png)
