### ISSUE TITLE
[Postgres] Incorect display value for date field

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4390]
The field value is 'Infinity' but it is displayed as '292278994-08-17 01:00:00'

`Infinity` is not same as that date.

**Comment by KES777** [comment]
The `-Infinity` displayed also as `292269055-12-03 01:00:00`

**Comment by serge-rider** [comment]
Could you post SQL snippet to reproduce this?

**Comment by KES777** [comment]
```
create table x ( yyy timestamp );
insert into x values ( '-Infinity' );
insert into x values ( 'Infinity' );
```

![delete1](https://user-images.githubusercontent.com/799021/46905551-1ee2df80-cefe-11e8-80cc-2019cf670880.jpg)

**Comment by lemon-juice** [comment]
There's a new option in Preferences > Database > Result Sets > Data Formats: Use native date/time format. When you enable it then infinity values will display correctly.

**Comment by serge-rider** [comment]
@lemon-juice good point. In fact PostgreSQL JDBC driver (as Java itself) doesn't support concept of infinity for timestamps. So the only valid workaround is to use native representation.

**Comment by KES777** [comment]
would it be better to use native representation by default?

**Comment by lemon-juice** [comment]
In my opinion yes - I don't think anyone using a DB tool would expect to see some JDBC specific data transformations (unless they have a specific purpose for them). Another reason is that in some cases these transformations can lead to data loss.

**Comment by serge-rider** [comment]
I don't think so. After all DBeaver is universal tools and tries to show data from different databases in more or less the same format. 

For example using database native format won't let you to easily copy-paste datetime values between different databases (e.g. between PostgreSQL and MySQL).

**Comment by KES777** [comment]
Then for copying purpose between database you should use interval value instead of display.

But If I use PostgreSQL connection and navigate database I expect to see native values instead of JDBC internals.

In any case `292278994-08-17 01:00:00` is not infinity and I am not sure that mysql count this value as `infinity`

Also you say that `native representation is just work around for this issue`, It would be nice to see implemented  solution which works. I am not eager to use workarounds (
