### ISSUE TITLE
`Tab` do not move focus

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4391]
At this dialog:

![delete1](https://user-images.githubusercontent.com/799021/46904866-b5f66a00-cef3-11e8-9e19-6891580d2bfb.jpg)

When I press `Tab` control is moved to `Cancel`. 
When I press `Tab` again control is left on `Cancel`  <<< this is unexpected. Focus should be moved
When I press `Tab` second time it is moved to `Ok`

**Comment by serge-rider** [comment]
After Cancel focus moves to checkbox (Remember choice). Then to Ok, then back to Cancel.
Maybe your window manager doesn't visualize focused checkboxes?

**Comment by KES777** [comment]
oh, maybe yes. I am on Linux mint 18.3 Cinamon

**Comment by KES777** [comment]
[Kazam_screencast_00000.mp4.zip](https://github.com/dbeaver/dbeaver/files/2541892/Kazam_screencast_00000.mp4.zip)

Here you can see that `Cancel` is still highlighted, but focus is actually on `Remember choice`
