### ISSUE TITLE
DBeaver does not pick up second override function's code

### ISSUE THREAD

**Issue by NicoBotha** [dbeaver/dbeaver#4396]
I have 2 functions with the same name in postgresql (different parameters).
With PGAdmin I can open both functions and see the code of each.
DBeaver always open the code of the 1st function for both functions.

**Comment by serge-rider** [comment]
This may happen if you use Old (Generic) driver. JDBC API doesn't provide any way to read procedures body.
Solution: use standard PostgreSQL driver.
