### ISSUE TITLE
How do I re-enable data sorting?

### ISSUE THREAD

**Issue by chihane** [dbeaver/dbeaver#4398]
When I tried to sort many rows in "data" view, I accidently clicked no with "don't ask again" checked, now I can't sort any column.
How do I restore this config?

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/47258890-e6697580-d4aa-11e8-9f5f-88c41a29d776.png)

**Comment by chihane** [comment]
Thank you very much!
