### ISSUE TITLE
Import of tab separated file fails halfway without any error message

### ISSUE THREAD

**Issue by rvantland** [dbeaver/dbeaver#4399]
When i try to import tab separated fileson my mac (mojave) i now already had several times with dbeaver 5.2.2 that it only imported half of the rows where it didnt give any message. Just tried to import almost 67k rows where little less than 35k saved in the table (enterprisedb 9.6).

**Comment by rvantland** [comment]
Seems the import cannot handly ' in the text. where i have no quotes and /t as separator.

now failing at names like De'Rosa	and O'Connor

**Comment by uslss** [comment]
cannot reproduce it against 7.0.5.
if it is still actual for you - feel free to reopen the ticket
