### ISSUE TITLE
Type-aware data sorting (for inet, cidr)

### ISSUE THREAD

**Issue by maffe** [dbeaver/dbeaver#4402]
In PostgreSQL the query
```
SELECT *
FROM (
SELECT '203.0.113.0/24'::cidr
UNION ALL
SELECT '60.64.1.128/28'::cidr
UNION ALL 
SELECT '60.64.2.0/24'::cidr
) sub
ORDER BY 1
```
generates a sorted result set:
```
60.64.1.128/28
60.64.2.0/24
203.0.113.0/24
```
But when the list is sorted in the client, `60.64.1.128/28` is always in the middle. The algorithm DBeaver uses is not suitable for `inet` and `cidr` data types.

**Comment by serge-rider** [comment]
On client side is DBeaver can't recognize data type (as a number, date, uuid, etc) then it uses string representation of data types. PostgreSQL returns custo mdata types in form of PGObject and there is no way to determine how to sort them on client side.
So I doubt that we can fix this on DBeaver side..

**Comment by maffe** [comment]
`PGObject` has a `getType` method which could be used to check if the type is `inet` or `cidr`. If so, the data could be converted to a custom Java type (say `Cidr`) which could implement `Comparable<Cidr>` to support proper sorting.

However, such specific handling is not even necessary. A basic natural sorting algorithm is sufficient. (Having looked at `TableColumnSortListener` I first thought it would do natural sorting, but it’s missing a loop.)

For example, PHP’s [natsort](https://secure.php.net/manual/en/function.natsort.php) works well with the data I mentioned above. You can [try](https://www.functions-online.com/natsort.html) it with
```
['60.64.2.0/24',
'203.0.113.0/24',
'60.64.1.128/28']
```
and you get
```
array (
  2 => '60.64.1.128/28',
  0 => '60.64.2.0/24',
  1 => '203.0.113.0/24',
)
```
You can find an explanation and a Java implementation at http://www.davekoelle.com/alphanum.html. Probably it’s useful for other data types as well.

**Comment by maffe** [comment]
Actually natural sorting would not work well with all IPv6 addresses, but it would help in many cases (also non-IP data).

**Comment by uslss** [comment]
There is no update for more than a year.
Ticket is closed.
If issue isn't fixed for you, feel free to reopen the ticket
