### ISSUE TITLE
Oracle Issue / EA version

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#4403]
Hi Serge,

using the latest EA version on Mac with Oracle, I am no longer able to edit existing records in the result set.

I can add new records but can't edit existing ones.

**Comment by serge-rider** [comment]
I can't reproduce this.
Could you provide a bit more info:
- Is this true for all tables or just for some?
- Is there anything special about these tables (view, amt views, IO tables, etc)?
- Do these tables have unique keys?
- Is there anything in error/debug log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by JamesInform** [comment]
Seems to be gone in the latest ea version. Now it works.

**Comment by serge-rider** [comment]
Ok then. Thanks for the report anyway.
If you will see such problem again - please reopen.
