### ISSUE TITLE
null pointer exceptionon new version screen

### ISSUE THREAD

**Issue by surpavan** [dbeaver/dbeaver#4406]
Then the app opens it is throwing the below error related to showing new version details.

![temp](https://user-images.githubusercontent.com/37795549/46993607-b7ab7200-d12d-11e8-8267-d7a8418e0b33.PNG)

**Comment by infectormp** [comment]
duplicate of #4261

**Comment by surpavan** [comment]
> 
> 
> duplicate of #4261

Did not see that there was a new release.  Closing this now.  Thank you.
