### ISSUE TITLE
SQL Completion problem

### ISSUE THREAD

**Issue by fayca121** [dbeaver/dbeaver#4410]
Hello,

I think there is a small bug with auto completion, it always searches insides names even though the option (search inside name) is unchecked.

-----------------------------------------
Dbeaver CE 5.2.2 x64.
Oracle 11g.

**Comment by 5hiva** [comment]
Hello,
I'm having the same problem and this is very frustrating indeed :)
We'll appreciate a fix here.

Thanks!

**Comment by serge-rider** [comment]
Yep. Now we use fuzzy search always ignoring this option. 
Thanks for the bug report.

**Comment by serge-rider** [comment]
Done.
However "Search inside name" will be on by default since 5.2.4

**Comment by Yoshimit** [comment]
Sorry the comment in #3318 

This one makes for sense.

Version 5.3.2 still (or returns to) ignoring the "search inside name" option.

Thank you.
