### ISSUE TITLE
DBeaver - Cancel Query - Question/Bug?

### ISSUE THREAD

**Issue by antonwierenga** [dbeaver/dbeaver#4412]
With DBeaver 5.2.1 and earlier versions when I cancelled a long running query on a PostgreSQL database the query cancelled immediately in the DBeaver client and the query also stopped running in PostgreSQL.

When I cancel a long running query in DBeaver 5.2.2 this results in a 'Cancelling query' dialog that is showing for minutes (I eventually killed DBeaver).

After setting the 'Error handle' - 'Cancel execution' - 'Close connection after timeout' the 'Cancelling query' dialog goes away after the configured timeout but it does not stop the query from running in PostgreSQL.

Can I configure DBeaver 5.2.2 so I can get DBeaver 5.2.1 'Cancel Query' behaviour?

**Comment by infectormp** [comment]
Query cancel is broken in 5.2.2 (for all JDBC drivers).
Duplicate of #3094

**Comment by antonwierenga** [comment]
Thanks for the quick reply. I will close this issue.
