### ISSUE TITLE
[Postgres] Generate DDL for custom data types

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#4414]
Currently, DBeaver lists data types under the "Data types" tree item but does not offer to do anything with them. At least generating DDL statements for them would be very convenient.

An example of DDL for an enum type as generated by pgAdmin:
```sql
-- DROP TYPE public.price_calc_direction;

CREATE TYPE public.price_calc_direction AS ENUM
   ('up',
    'down');
ALTER TYPE public.price_calc_direction
  OWNER TO postgres;
COMMENT ON TYPE public.price_calc_direction
  IS 'how to calculate prices';
```

**Comment by ebrandsberg** [comment]
+1 requesting this feature, required before we will purchase enterprise for 10+ licenses (currently in trial)

**Comment by serge-rider** [comment]
Done (this feature was planned long time ago). 
At least it works for base, domain, enum and composite data types.
If DDL is not correct in some cases - please create a separate ticket.
