### ISSUE TITLE
Redis SSL?

### ISSUE THREAD

**Issue by jdvor** [dbeaver/dbeaver#4415]
Question:

Does DBeaver EE supports Redis connected through SSL? Like Azure Redis Cache for example.

**Comment by serge-rider** [comment]
Yes, SSL support was added in Redis driver in the latest DBEaver EE version.

But you will need to use Early Access version (https://dbeaver.com/files/ea) or wait for 5.3 release (early December).

**Comment by jdvor** [comment]
Thanks.

**Comment by jdvor** [comment]
Just small follow-up - the link contains EA builds for Community edition and the Redis is EE feature, so it does not (obviously) work with them either.

**Comment by serge-rider** [comment]
Umm, the latest one dfinitely has this
5.2.3.201810181733

![image](https://user-images.githubusercontent.com/6398845/47347828-5b59cc80-d6b0-11e8-8640-1213236fbbd7.png)
![image](https://user-images.githubusercontent.com/6398845/47347861-6dd40600-d6b0-11e8-99a6-f0a63b9760e8.png)
