### ISSUE TITLE
bug when opening DBeaver

### ISSUE THREAD

**Issue by glassnor** [dbeaver/dbeaver#4417]
I believe I've encountered a bug.  Let me explain the bug and what I've tried to do to troubleshoot it:
When I open the app I get this error:
" See the log file
/Applications/DBeaver.app/Contents/Eclipse/configuration/1539781099771.log"
Sadly I can't figure out how to open the log file, I tried going to console in utilities and looking at log files there, but couldn't see anything for DBeaver.

How'd I get here?
1. I installed DBeaver without having Java installed... got a notification to Install Java
1. I installed the latest version of java from mac I could find - version 8
1. When I opened DBeaver I got this error.
1. Then I tried installing the version of java that the DBeaver error message points to - version 6
1. Error persists.
1. Wiped all java off my machine after googling the error message a bit.
1. Installed the DBeaver's recommended Java version (6 If I recall)
1. Error persists.
1. I thought it may be a problem with not having installed eclipse yet, so I installed eclipse for javascript (which is what my dev team uses), then realized I should install eclipse for Java since DBeaver is a JAVA app... Seemed odd to me that it would require eclipse but figured I was out of other better options...
1. Issue persists

Can you give me some suggestions?  Sorry I'm not as technically savvy as I used to be, I haven't done extensive hands on work for some time...

**Comment by serge-rider** [comment]
Why don't you use MacOS installer (pkg)? It already contains proper Java so you won';t need to care about that.
Otherwise you will need to install JDK 1.8+ (not JRE!) manually.

**Comment by glassnor** [comment]
@serge-rider a great suggestion and it fixed my problem, thanks!  I am used to using dmg's to install stuff, will try PKG's instead now.

**Comment by shiwangini** [comment]
Same problem i'm facing. I have windows 10 machine. Please share a fix
