### ISSUE TITLE
Datasource invalidate failed looping infinitely every 10 seconds

### ISSUE THREAD

**Issue by orbanbalage** [dbeaver/dbeaver#4420]
When disconnecting from the network of a certain DB2 z/OS datasource 
![image](https://user-images.githubusercontent.com/285574/47111115-ee2edd00-d252-11e8-91f4-07664e0a366d.png)

this notifications keeps popping up.

It only happens for a single connection (although in the alert it's shown 2x), that was created in an older version of Dbeaver. The newer connections are not manifesting this notification.

_migrated from #2070_ 
(it also manifests itself in lost commits, but probably the root cause is the same)

**Comment by serge-rider** [comment]
I don't think that this is related to DBeaver version.
Most likely you have enabled keep-alive for that connection so DBeaver tries to reopen it every X seconds. You can just disable it.
Also you can disable invalidate for this connection (open connection properties -> page Error Handle -> "Connection auto-recover enabled".

**Comment by orbanbalage** [comment]
aaah, indeed, it is so!
thank you, it was so long ago, not sure why that setting was changed...
