### ISSUE TITLE
Bug Report: Automatically naming result set tabs

### ISSUE THREAD

**Issue by dpeterson157** [dbeaver/dbeaver#4423]
When trying to automatically name result set tabs for select statements using the 

-- name(or title): tab_name

feature, only the first such tab is renamed. For example:

![image](https://user-images.githubusercontent.com/39777251/47166395-b57a1c80-d2c1-11e8-8458-b51a44d0d74d.png)

What is potentially even more confusing is that if you have not renamed the first statement, the first tab is renamed to the second statement's name, but contains the first statements data:

![image](https://user-images.githubusercontent.com/39777251/47166609-3507eb80-d2c2-11e8-88a4-7fb57b44687b.png)

![image](https://user-images.githubusercontent.com/39777251/47166644-47822500-d2c2-11e8-9419-8acb1da672e4.png)

**Comment by serge-rider** [comment]
Can't reproduce. If I remember correctly we already fixed this bug a few versions ago, please try 5.2.+ version.

**Comment by powelleric** [comment]
I cannot reproduce either.  Works fine as far as I can tell

**Comment by uslss** [comment]
there is no update almost a year.
Ticket closed.
If issue is still actual for you, feel free to create new ticket
