### ISSUE TITLE
Domain definition extraction via DBeaver (question/bug)

### ISSUE THREAD

**Issue by 808zoid** [dbeaver/dbeaver#4425]
Greetings. 

I'm new to DBeaver and love the interface. Thank you for a great product;

 I'm running 5.2.2 on macOS 10.12.6 (Sierra). 

I'm trying to access user defined domain definitions via the interface without success. In order words, trying to get the equivalent of the following via psql:

PSQL:
my_data=# **\dD 'domain_i_defined'**

**1)** What follows is the query run via psql when \dD is executed at the psql prompt:

********* QUERY **********
SELECT n.nspname as "Schema",
       t.typname as "Name",
       pg_catalog.format_type(t.typbasetype, t.typtypmod) as "Type",
       TRIM(LEADING
            COALESCE((SELECT ' collate ' || c.collname FROM pg_catalog.pg_collation c, pg_catalog.pg_type bt
                      WHERE c.oid = t.typcollation AND bt.oid = t.typbasetype AND t.typcollation <> bt.typcollation), '') ||
            CASE WHEN t.typnotnull THEN ' not null' ELSE '' END ||
            CASE WHEN t.typdefault IS NOT NULL THEN ' default ' || t.typdefault ELSE '' END
       ) as "Modifier",
       pg_catalog.array_to_string(ARRAY(
         SELECT pg_catalog.pg_get_constraintdef(r.oid, true) FROM pg_catalog.pg_constraint r WHERE t.oid = r.contypid
       ), ' ') as "Check"
FROM pg_catalog.pg_type t
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
WHERE t.typtype = 'd'
  AND t.typname ~ '^(domain_i_defined)$'
  AND pg_catalog.pg_type_is_visible(t.oid)
ORDER BY 1, 2;
**************************

**2)** The SQL in **1)** above was derived by starting psql with **psql -E**

**3)** DBeaver neither shows me the definition of any user defined domain nor does the SQL above return anything meaningful when run in DBeaver's SQL editor; I get a blank table with all the "right" columns -  but no data. 

Expected outcome  would be something like the following  - which I get via psql: 

**example:**
biomonitoring_warehouse=# **\dD 'biomonitoring_rating5'**
********* QUERY **********
SELECT n.nspname as "Schema",
       t.typname as "Name",
       pg_catalog.format_type(t.typbasetype, t.typtypmod) as "Type",
       TRIM(LEADING
            COALESCE((SELECT ' collate ' || c.collname FROM pg_catalog.pg_collation c, pg_catalog.pg_type bt
                      WHERE c.oid = t.typcollation AND bt.oid = t.typbasetype AND t.typcollation <> bt.typcollation), '') ||
            CASE WHEN t.typnotnull THEN ' not null' ELSE '' END ||
            CASE WHEN t.typdefault IS NOT NULL THEN ' default ' || t.typdefault ELSE '' END
       ) as "Modifier",
       pg_catalog.array_to_string(ARRAY(
         SELECT pg_catalog.pg_get_constraintdef(r.oid, true) FROM pg_catalog.pg_constraint r WHERE t.oid = r.contypid
       ), ' ') as "Check"
FROM pg_catalog.pg_type t
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
WHERE t.typtype = 'd'
  AND t.typname ~ '^(biomonitoring_rating5)$'
  AND pg_catalog.pg_type_is_visible(t.oid)
ORDER BY 1, 2;
**************************

                                     List of domains
 Schema |         Name          |  Type   | Modifier |               Check               
--------+-----------------------+---------+----------+-----------------------------------
 public | biomonitoring_rating5 | integer |          | CHECK (VALUE >= 1 AND VALUE <= 5)
(1 row)

biomonitoring_warehouse=# 

**4)**  I don't believe this is a permissions issue, given that I get no errors, and am working as user/role postgres. 

Any help will be appreciated. 

Cheers from South Africa.

**Comment by uslss** [comment]
If it is still actual - feel free to reopen the ticket
