### ISSUE TITLE
FR: Implement CTRL+TAB hotkey 

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4429]
Implement CTRL+TAB hotkey to switch between `views`

**Comment by serge-rider** [comment]
<kbd>Ctrl+Tab</kbd> and <kbd>Ctrl+Shift+Tab</kbd> are already bound to editors switch command.

**Comment by KES777** [comment]
in linux focus is invisible thus that is unsuable.

some tools bound <kbd>ALT+\<num\></kbd>

where `<num>` is ordinal number for view
