### ISSUE TITLE
ER Diagram: cannot add view object

### ISSUE THREAD

**Issue by MauroMichelotti** [dbeaver/dbeaver#4434]
I created a new ER diagram, including only the tables.
Then I tried to add the views, dragging them from the views list, both on the diagram or on the list of tables (to the left of the diagram), but the views are not added.

If I create an ER diagram including the views and then I remove one and try to add it again, I can not add it (same issue above).

[database: PostgreSQL 9.6]

**Comment by serge-rider** [comment]
You can enable views in diagram by enabling it in preferences:
![image](https://user-images.githubusercontent.com/6398845/47243691-85369900-d3fb-11e8-91c8-534e41b54bde.png)

And I think we should enable it by default (in fact I don't remember why we disabled it in the past).
