### ISSUE TITLE
Set default Local Client home for new PostgreSQL connections

### ISSUE THREAD

**Issue by sohooo** [dbeaver/dbeaver#4435]
Hi,

we've specified the following `clientHome` setting in the `drivers.xml` file:

```xml
<provider id="postgresql">
		<driver id="postgres-jdbc" custom="false" embedded="false" name="PostgreSQL" class="org.postgresql.Driver" url="jdbc:postgresql://{host}[:{port}]/[{database}]" port="5432" description="PostgreSQL standard driver">
			<library type="jar" path="maven:/org.postgresql:postgresql:RELEASE" custom="false" version="9.4.1212.jre7"/>
			<library type="jar" path="${home}\jdbc\postgresql-42.1.4.jar" custom="true"/>
			<clientHome id="C:\Users\sohooo\Downloads\pg_binaries\pgsql\bin"/>
		</driver>
	</provider>
```

When creating a new PostgreSQL connection, this path is now available in the `General: Local Client` dropdown. However, the default for Local Client is empty.

Is it possible to make the `clientHome` setting a global default, which would avoid having to explicitly set the `Local Client` with every new connection?

**Comment by uslss** [comment]
Feature is already implemented. Ticket closed
