### ISSUE TITLE
Right-click context menu appears after mouse action

### ISSUE THREAD

**Issue by orbanbalage** [dbeaver/dbeaver#4436]
![dbeaver_right_click_context](https://user-images.githubusercontent.com/285574/47215286-39ef9c80-d3a1-11e8-814c-862e294588b2.gif)

After a right-click in the Projects view (and other places) and actioning the menu (or dismissing it), another right-click context menu appears.

On Mac High Sierra
10.13.6 (17G65)

**Comment by serge-rider** [comment]
It is a known issue with Eclipse 4.7 platform and MacOS.
Will be fixed in the next version (as we'll migrate to Eclipse 4.9).
