### ISSUE TITLE
Vertica didn't show correctly on Column comment.

### ISSUE THREAD

**Issue by JJBunt** [dbeaver/dbeaver#4437]
--Bug report--
Vertica Issue:
SQL Previews:
COMMENT ON COLUMN sales.test.col1 IS 'dd';

During commit changes by adding comment on column show as following:

SQL Error [2639] [42703]: [Vertica][VJDBC](2639) ROLLBACK: Column "test"."col1" does not exist as a projection column
  [Vertica][VJDBC](2639) ROLLBACK: Column "test"."col1" does not exist as a projection column
  [Vertica][VJDBC](2639) ROLLBACK: Column "test"."col1" does not exist as a projection column

Vertica has 3 nodes.
Further information : http://vertica-forums.com/viewtopic.php?t=516

**Comment by serge-rider** [comment]
It looks like this is not supported in Vertica (http://vertica-forums.com/viewtopic.php?t=144).
At the moment I have no ideas how to fix this..

**Comment by serge-rider** [comment]
Table columns are not editable in Vertica. But now you can comment projection columns.

**Comment by JJBunt** [comment]
Thank you for your kind support.
