### ISSUE TITLE
PostgreSQL: showing non-default databases does not work via command line

### ISSUE THREAD

**Issue by thorstenkampe** [dbeaver/dbeaver#4439]
DBeaver 5.2.2

We are dynamically creating connections in DBeaver via the command line (see below). The connection opens but we can only see the default database or the specified one. In contrast when manually creating a connection to the same host, we can see all databases.

The setting "show non-default databases" is checked in both cases.

```
dbeaver -con driver=postgres-jdbc|name="NAME"|host=HOST|user="postgres"|password=PASSWORD
```

**Comment by serge-rider** [comment]
It is a bug, "show non-default databases" should be enabled by default.
