### ISSUE TITLE
MySQL: showing non-default databases does not work via command line

### ISSUE THREAD

**Issue by thorstenkampe** [dbeaver/dbeaver#4440]
DBeaver 5.2.2

We are dynamically creating connections in DBeaver via the command line (see below). The connection opens but we can only see the default databases `performance_schema` and `sys`. In contrast when manually creating a connection to the same host, we can see all default databases (`mysql`, `information_schema`, `performance_schema` and `sys`).

```
dbeaver -con driver=mysql8|name="NAME"|host=HOST|user="root"|password=PASSWORD
```

**Comment by serge-rider** [comment]
I can't reproduce this. Generally DBeaver doesn't limit MySQL databases anyhow. Maybe it is a result of different connection settings/permissions?

**Comment by thorstenkampe** [comment]
Serge,
the connections (manual and via command line) are to the same host, under the same privileged account (root), without specifying a database.  The difference in display is clearly visible in this screenshot:
![image](https://user-images.githubusercontent.com/475462/47252842-75df3c00-d44b-11e8-9e94-abf431ed7103.png)

**Comment by thorstenkampe** [comment]
Same for a local MariaDB on Cygwin (MariaDB does not have a `sys` database):
![image](https://user-images.githubusercontent.com/475462/47252926-bab7a280-d44c-11e8-929d-b3d65c6e954a.png)

**Comment by serge-rider** [comment]
New cli parameters showSystemObjects and showUtilityObjects were added (https://github.com/dbeaver/dbeaver/wiki/Command-Line)

**Comment by ynasida** [comment]
I see same issue currently.

version 6.1.3

**Comment by ynasida** [comment]
I can see mysql and information_schema using cli (show databases;)  but they are not displayed at UI

**Comment by alexanderfefelov** [comment]
> I can see mysql and information_schema using cli (show databases;) but they are not displayed at UI

@ynasida right-click on connection, select "Connection view", enable "Show system objects".
