### ISSUE TITLE
Oracle: showing non-default schemas does not work via command line 

### ISSUE THREAD

**Issue by thorstenkampe** [dbeaver/dbeaver#4441]
DBeaver 5.2.2

We are dynamically creating connections in DBeaver via the command line (see below). The connection opens but we can only see the default schema `APEX_040000`, `FLOWS_FILES` and `HR`. In contrast when manually creating a connection to the same host, we can see all default schema (`APEX_040000`, `CTXSYS`, `FLOWS_FILES`, `HR`, `MDSYS`, `OUTLN`, `SYS`, `SYSTEM` and `XDB`).

```
dbeaver -con driver=oracle_thin|name="NAME"|host=HOST|database=xe|user="sys as sysdba"|password=PASSWORD
```

**Comment by serge-rider** [comment]
Can't reproduce. This seems to be the same as #4440.

**Comment by thorstenkampe** [comment]
The connections (manual and via command line) are to the same host, under the same privileged account (sys as sysdba). The difference in display is clearly visible in this screenshot:
![image](https://user-images.githubusercontent.com/475462/47253133-9c9f7180-d44f-11e8-8ce0-72627729f5e1.png)

**Comment by thorstenkampe** [comment]
Maybe helpful additional information:

* a network trace shows that the query and response for the databases are the same for MySQL and Oracle. So it looks to me like the interpretation done by DBeaver is the root cause. 

* MS SQL does not show the behaviour:
![image](https://user-images.githubusercontent.com/475462/47253530-5bf62700-d454-11e8-911c-049a04fde2a8.png)
