### ISSUE TITLE
DBeaver stuck at "Load SynonymCache"

### ISSUE THREAD

**Issue by jackse7en** [dbeaver/dbeaver#4447]
Hi, I'm using DBeaver 5.2.2 on Win7 32bit.
While trying to query all rows from a table, the program stuck at Load SynonymCache and unable to cancel. I had to use task manager to terminate it.

However, I have no issue with version 5.2.0

![image](https://user-images.githubusercontent.com/15628830/47263927-db135a00-d53d-11e8-8a4f-410803ed1857.png)

![image](https://user-images.githubusercontent.com/15628830/47263889-5c1e2180-d53d-11e8-9438-8e5e50ebc9bc.png)

**Comment by serge-rider** [comment]
Perhaps this is beause we now use DBA_* views by defult. I think this should be configurable (and views shouldn't be used by default).

**Comment by serge-rider** [comment]
Please check the fix in 5.2.4

**Comment by linxingquan** [comment]
Hi @serge-rider, I also have this issue. Can you help to take a look? Thank you!

<img width="310" alt="dbeaver1" src="https://user-images.githubusercontent.com/6181700/55911102-cd599b80-5b94-11e9-903e-3f130b78ae0d.png">
<img width="886" alt="dbeaver2" src="https://user-images.githubusercontent.com/6181700/55911104-cdf23200-5b94-11e9-86fb-f4d11626b163.png">
