### ISSUE TITLE
Fails to use drivers for MS SQL

### ISSUE THREAD

**Issue by WrongBit** [dbeaver/dbeaver#4448]
I use MS SQL 2014 on Win7 x64 and JRE 9.0.4. When dbeaver asked for database, I selected "MS SQL" and "MS SQL driver" (not jdbc). dbeaver downloaded something and then fails with error:

![error](https://user-images.githubusercontent.com/15650524/47272016-d5d6ff00-d57f-11e8-8e42-975bb10883d6.gif)

Recommendation: include in setup drivers for a few "biggest" guys: MS SQL, Orcale, PostgreSQL and SQLite. It's not nice to download anything after main program. Anyway error needs fix.

**Comment by serge-rider** [comment]
Most likely downoad was failed by some reason (are you behind some corporate firewll?).
Otherwise it should work, you don't need to download SQL Server dirver separately.

We include  drivers (usually the most recent versions) only in DBeaver EE. Drivers are too big (maing DBeaver CE too heavy).

**Comment by WrongBit** [comment]
Of course I'm behind firewall - that's why every unnecessary access to Internet makes pain. But once driver failed to download, I opened access to dbeaver and **it downloaded something**. That means driver **must** be on place. Why it's not - your duty.
Drivers are not big if you don't include rare rubbish. How much MB it takes for drivers I listed above?

**Comment by uslss** [comment]
Hi @WrongBit ,
is issue still actual for you?

**Comment by WrongBit** [comment]
One year later you ask me??? :))) Of course not, long time ago switched to DBQuickie.

**Comment by serge-rider** [comment]
We can't include drivers for all databases in DBeaver CE (it is more than 200mb even for limited set of most popular drivers, this is 4 times bigger than dbeaver ce itself).

You could use EE version, it is bundled with everything.
And, of course, it makes sense to use specialized tool if you need just one database.

Anyhow, closing as not relevant anymore.
