### ISSUE TITLE
Autocomplete Annoyance in Version 5.2.3

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#4450]
Hi Serge,

The autocomplete seems to suffer from the following problem:

Say I have a table called "my_super_table" and I want to select from it.

If I type

`select * from msuptab`

the auto completion shows me "my_super_table" in the drop down list.

But when I select the table name from the drop down list, it completes as

`select * from my_super_tablemsuptab`

So it doesn't override or delete my previously entered fuzzy search string.

**Comment by ravshansbox** [comment]
Same here.

**Comment by debose** [comment]
+1, autocomplete is effectively unusable due to this

**Comment by greenpeas** [comment]
![image](https://user-images.githubusercontent.com/3856344/47287578-69014a80-d5fb-11e8-9292-0581c62ed533.png)
![image](https://user-images.githubusercontent.com/3856344/47287583-6dc5fe80-d5fb-11e8-88aa-2f9915935208.png)

**Comment by serge-rider** [comment]
Bug in the 5.2.3. 
Workaround: enable "replace current word" option in SQL completion prefs:
![image](https://user-images.githubusercontent.com/6398845/47293115-6d346480-d609-11e8-9c26-bbd17bbdd571.png)

As this bug making auto-completion very inconvenient I'm thinking about hotfix version..

**Comment by serge-rider** [comment]
I've re-uploaded 5.2.3 release (build 201810222030).
The only major change is auto-completion fix

**Comment by sandeshk89** [comment]
Hi Serge,

I'm still facing this issue, with the latest version (21.3.2) of community edition. Do I have to use enterprise edition for this?

I have the option "Replace current word" selected as well.

![image](https://user-images.githubusercontent.com/75207315/148683642-bd1801dd-b7ec-477f-979d-3132df84625d.png)
![image](https://user-images.githubusercontent.com/75207315/148683677-48168085-48ba-4573-86e6-7cd1059b5d97.png)

**Comment by mdahlman** [comment]
The behavior you show doesn't match the initial report. I think you'll need to open a separate issue.

**Comment by sandeshk89** [comment]
Added a separate issue [**15135**.](https://github.com/dbeaver/dbeaver/issues/15135)
