### ISSUE TITLE
DBeaver no longer compatible with DevStyle Darkest Dark theme (similar to #3898 but for 5.2.3)

### ISSUE THREAD

**Issue by peterhatz** [dbeaver/dbeaver#4451]
Hi,

Just installed 5.2.3.(201810201753) and the DevStyle "conflicting dependency" issue has cropped up again (I've also run as su and same issue):

`
Cannot complete the install because of a conflicting dependency. Software being installed: DevStyle (includes Darkest Dark Theme) 1.11.0.201809241613 (com.genuitec.eclipse.theming.feature.feature.group 1.11.0.201809241613) Software currently installed: DBeaver 5.2.3 (org.jkiss.dbeaver.core.product 5.2.3) Only one of the following can be installed at once: Eclipse IDE UI Application 1.2.0.v20170512-1452 (org.eclipse.ui.ide.application 1.2.0.v20170512-1452) Eclipse IDE UI Application 1.3.0.v20180828-1350 (org.eclipse.ui.ide.application 1.3.0.v20180828-1350) Cannot satisfy dependency: From: DevStyle (includes Darkest Dark Theme) 1.11.0.201809241613 (com.genuitec.eclipse.theming.feature.feature.group 1.11.0.201809241613) To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group 4.6.0 Cannot satisfy dependency: From: Eclipse Platform 4.7.2.v20171130-0510 (org.eclipse.platform.feature.group 4.7.2.v20171130-0510) To: org.eclipse.equinox.p2.iu; org.eclipse.ui.ide.application [1.2.0.v20170512-1452,1.2.0.v20170512-1452] Cannot satisfy dependency: From: Eclipse Platform 4.7.3.v20180301-0715 (org.eclipse.platform.feature.group 4.7.3.v20180301-0715) To: org.eclipse.equinox.p2.iu; org.eclipse.ui.ide.application [1.2.0.v20170512-1452,1.2.0.v20170512-1452] Cannot satisfy dependency: From: Eclipse Platform 4.7.3.v20180330-0640 (org.eclipse.platform.feature.group 4.7.3.v20180330-0640) To: org.eclipse.equinox.p2.iu; org.eclipse.ui.ide.application [1.2.0.v20170512-1452,1.2.0.v20170512-1452] Cannot satisfy dependency: From: DBeaver Community Edition 5.2.3.201810201753 (org.jkiss.dbeaver.ce.feature.feature.group 5.2.3.201810201753) To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [5.2.3.201810201753,5.2.3.201810201753] Cannot satisfy dependency: From: DBeaver 5.2.3 (org.jkiss.dbeaver.core.product 5.2.3) To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [5.2.3.201810201753,5.2.3.201810201753] Cannot satisfy dependency: From: DBeaver Standalone 5.2.3.201810201753 (org.jkiss.dbeaver.standalone.feature.feature.group 5.2.3.201810201753) To: org.eclipse.equinox.p2.iu; org.eclipse.ui.ide.application [1.3.0.v20180828-1350,1.3.0.v20180828-1350]
`

Thanks,
Peter

**Comment by serge-rider** [comment]
Yep. Previously it was automatically resolved after we reverted to Eclipse 4.7.  Now we switched to Eclipe 4.9 (or 2018-09) and it is failing again/
 
Thanks for the report

**Comment by serge-rider** [comment]
P2 config is now compatible with E2018-09.

**Comment by peterhatz** [comment]
Cheers, thanks @serge-rider

**Comment by Barosky** [comment]
Hello, it looks like the P2 problem has resurrected. I've DBeaver 5.3.3 and trying to install Darkest Dark/DevStyle I get this error:

Cannot complete the install because of a conflicting dependency.
  Software being installed: DevStyle (includes Darkest Dark Theme) 1.11.0.201810241355 (com.genuitec.eclipse.theming.feature.feature.group 1.11.0.201810241355)
  Software currently installed: DBeaver 5.3.3.201901202008 (org.jkiss.dbeaver.core.product 5.3.3.201901202008)
  Only one of the following can be installed at once: 
    Eclipse IDE UI Application 1.2.0.v20170512-1452 (org.eclipse.ui.ide.application 1.2.0.v20170512-1452)
    Eclipse IDE UI Application 1.3.0.v20180828-1350 (org.eclipse.ui.ide.application 1.3.0.v20180828-1350)
  Cannot satisfy dependency:
    From: DevStyle (includes Darkest Dark Theme) 1.11.0.201810241355 (com.genuitec.eclipse.theming.feature.feature.group 1.11.0.201810241355)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group 4.6.0
  Cannot satisfy dependency:
    From: Eclipse Platform 4.7.2.v20171130-0510 (org.eclipse.platform.feature.group 4.7.2.v20171130-0510)
    To: org.eclipse.equinox.p2.iu; org.eclipse.ui.ide.application [1.2.0.v20170512-1452,1.2.0.v20170512-1452]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.7.3.v20180301-0715 (org.eclipse.platform.feature.group 4.7.3.v20180301-0715)
    To: org.eclipse.equinox.p2.iu; org.eclipse.ui.ide.application [1.2.0.v20170512-1452,1.2.0.v20170512-1452]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.7.3.v20180330-0640 (org.eclipse.platform.feature.group 4.7.3.v20180330-0640)
    To: org.eclipse.equinox.p2.iu; org.eclipse.ui.ide.application [1.2.0.v20170512-1452,1.2.0.v20170512-1452]
  Cannot satisfy dependency:
    From: DBeaver Community Edition 5.3.3.201901202008 (org.jkiss.dbeaver.ce.feature.feature.group 5.3.3.201901202008)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [5.3.3.201901202008,5.3.3.201901202008]
  Cannot satisfy dependency:
    From: DBeaver 5.3.3.201901202008 (org.jkiss.dbeaver.core.product 5.3.3.201901202008)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [5.3.3.201901202008,5.3.3.201901202008]
  Cannot satisfy dependency:
    From: DBeaver Standalone 5.3.3.201901202008 (org.jkiss.dbeaver.standalone.feature.feature.group 5.3.3.201901202008)
    To: org.eclipse.equinox.p2.iu; org.eclipse.ui.ide.application [1.3.0.v20180828-1350,1.3.0.v20180828-1350]

**Comment by peterhatz** [comment]
Thanks and true, it's happening again. Sticking to built-in dark style for now...🙃

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by peterhatz** [comment]
Thanks for including it.

Peter

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Barosky** [comment]
Hello,

I've just updated Dbeaver to 5.3.4 and Darkest Dark/DevStyle is working as
expected. Thank you!

Best regards,
Cristiano


Il giorno dom 3 feb 2019 alle ore 09:51 Serge Rider <
notifications@github.com> ha scritto:

**Comment by stadnikilya** [comment]
Hello, look like same problem in Version 7.1.5.202008232204
```
Cannot complete the install because of a conflicting dependency.
  Software being installed: DevStyle (includes Darkest Dark Theme) 1.11.0.202007171537 (com.genuitec.eclipse.theming.core.feature.feature.group 1.11.0.202007171537)
  Software currently installed: DBeaver 7.1.5 (org.jkiss.dbeaver.core.product 7.1.5)
  Only one of the following can be installed at once: 
    Expression Language 3.5.100.v20160418-1621 (org.eclipse.core.expressions 3.5.100.v20160418-1621)
    Expression Language 3.6.700.v20200212-1751 (org.eclipse.core.expressions 3.6.700.v20200212-1751)
  Cannot satisfy dependency:
    From: Startup 1.11.0.202007171537 (com.genuitec.eclipse.startup 1.11.0.202007171537)
    To: osgi.bundle; org.eclipse.wst.common.frameworks 0.0.0
  Cannot satisfy dependency:
    From: DevStyle (includes Darkest Dark Theme) 1.11.0.202007171537 (com.genuitec.eclipse.theming.core.feature.feature.group 1.11.0.202007171537)
    To: org.eclipse.equinox.p2.iu; com.genuitec.eclipse.startup [1.11.0.202007171537,1.11.0.202007171537]
  Cannot satisfy dependency:
    From: WST Common Core Plug-in 1.3.0.v201903222010 (org.eclipse.wst.common.core 1.3.0.v201903222010)
    To: osgi.bundle; org.eclipse.core.expressions [3.6.0,4.0.0)
  Cannot satisfy dependency:
    From: Common Frameworks 1.2.201.v201903222010 (org.eclipse.wst.common.frameworks 1.2.201.v201903222010)
    To: osgi.bundle; org.eclipse.wst.common.core [1.2.0,2.0.0)
  Cannot satisfy dependency:
    From: DBeaver 7.1.5 (org.jkiss.dbeaver.ce.feature.feature.group 7.1.5)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [7.1.5,7.1.5]
  Cannot satisfy dependency:
    From: DBeaver 7.1.5 (org.jkiss.dbeaver.core.product 7.1.5)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [7.1.5,7.1.5]
  Cannot satisfy dependency:
    From: RCP 2.1.36 (org.jkiss.dbeaver.rcp.feature.feature.group 2.1.36)
    To: org.eclipse.equinox.p2.iu; org.eclipse.core.expressions [3.5.100.v20160418-1621,3.5.100.v20160418-1621]
  Cannot satisfy dependency:
    From: DBeaver Standalone 7.1.5 (org.jkiss.dbeaver.standalone.feature.feature.group 7.1.5)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.rcp.feature.feature.group [2.1.36,2.1.36]
```
