### ISSUE TITLE
We want grid lines back in table editor in 5.2.3

### ISSUE THREAD

**Issue by tohghua** [dbeaver/dbeaver#4452]
Thanks!

**Comment by serge-rider** [comment]
I guess you mean grid lines in tabs with object lists (columns, constraints, etc).
Perhaps we should make this configurable.

**Comment by lemon-juice** [comment]
I agree, the grid lines were useful and made the view clearer.
> Perhaps we should make this configurable.

Why would anyone want to turn them off? Did they get in the way somehow?

**Comment by serge-rider** [comment]
> Why would anyone want to turn them off? Did they get in the way somehow?

Grid looks quite ugly (eyes breaking) in some dark themes (Especially default Eclipse dark theme).
Anyhow, I've made this configurable.

![image](https://user-images.githubusercontent.com/6398845/47620395-a33a8280-dafa-11e8-8d0d-1ffc4753935a.png)

It is enabled by default. But I'm not sure about default value. Maybe will change in the future.
