### ISSUE TITLE
Fields lose focus when editing a column

### ISSUE THREAD

**Issue by greenpeas** [dbeaver/dbeaver#4455]
DB 5.2.3. PostgreSQL. Production connect mode.
Fields lose focus when editing a column:
![image](https://user-images.githubusercontent.com/3856344/47281434-cc7f7e00-d5e3-11e8-8996-5ea44de46af6.png)
To type a word, you need to click on the field each time.

**Comment by greenpeas** [comment]
Win10 x64

**Comment by serge-rider** [comment]
Can't reproduce this.

**Comment by greenpeas** [comment]
![testdb](https://user-images.githubusercontent.com/3856344/47637774-d538fc80-db6d-11e8-8dc4-1c253a064354.gif)

**Comment by mgrubb** [comment]
I'm having the exact same issue with DBeaver 5.2.4.201811051019 running Mac OS X 10.13.6

**Comment by serge-rider** [comment]
@greenpeas thanks for details.
See fix in the next version.
