### ISSUE TITLE
dbeaver.ini is resetted after update

### ISSUE THREAD

**Issue by datopalov** [dbeaver/dbeaver#4456]
I change dbeaver.ini and after update it was resetted :(

Update from 5.2.2 to 5.2.3
Reset settings was not checked during the update.
![dbres](https://user-images.githubusercontent.com/19872068/47288260-0a899b80-d5fe-11e8-9b16-54e64c1be883.PNG)

Installer used: Windows 64 bit (installer + JRE)

**Comment by uslss** [comment]
fixed in scope of #5778
