### ISSUE TITLE
autocomplete does not show columns list until i type a character matching the column name

### ISSUE THREAD

**Issue by maddogv6** [dbeaver/dbeaver#4458]
select * from dbo.customers c
where c.

If i try autocomplete on this, it wont show anything.  Not until i type 'f' does it show autocomplete list matching columns that contain 'F'.   i don't usually remember column names that why i refer to this tool to give me a list.

**Comment by serge-rider** [comment]
Yes, it is a bug in completion proposals filtering. Thanks for the bug report.
