### ISSUE TITLE
issue with autocomplete in 5.2.3

### ISSUE THREAD

**Issue by kufii** [dbeaver/dbeaver#4460]
I type

```
select * from my_ta
```

I select `my_table_name` from the list

the result:

```
select * from my_table_namemy_ta
```

**Comment by xfzhaoxd** [comment]
You can open menu item "window->preference" ,find “sql auto complete”，checked "replace current word"。You can solve the problem。
This option is not checked by default.

**Comment by serge-rider** [comment]
This issue was resolved  in #4450
You can re-download verson 5.2.3
