### ISSUE TITLE
ER Diagram configuration

### ISSUE THREAD

**Issue by SZubarev** [dbeaver/dbeaver#4462]
Ver 5.2.3, Redshift

Steps:
- Create a new ER diagram, add tables
- Open ERD Editor Configuration (gear icon)
- Check "Data Types" checkbox
- Press "Apply and Close"
- Nothing is changed
- Close diagram and open again - the ER diagram refreshed and data types are shown

Also when saving ER diagram not always all added tables are exported to image - I have 6 tables in ER diagram, but only 3 are in resulting PNG file

**Comment by uslss** [comment]
already fixed.
ticket closed
