### ISSUE TITLE
lost mariadb databases

### ISSUE THREAD

**Issue by mmjvox** [dbeaver/dbeaver#4463]
cant find and show mariadb databases on openjdk8 (opensuse)

**Comment by serge-rider** [comment]
Could you prive a bit more details? 
Do you see some errors? 
Can you connect?

**Comment by mmjvox** [comment]
*im using mariadb and i created a mariadb connection ...  i tried mysql3x
connection *

*now i created a new mysql8x connention and the problem solvd. *
