### ISSUE TITLE
Auto Complete, leaves initially typed characters after selecting the proposed replacement

### ISSUE THREAD

**Issue by CarlosGalv** [dbeaver/dbeaver#4464]
When you start typing a table or DB name and press Enter, it used to replace your typing with the desired match, E.G. **You type Cli and then the match could be Clients, by pressing Enter what you typed gets replaced by the Selected name** now, it ends up like **ClientsCli** which forces you to manually delete what you've initially typed

**Comment by xfzhaoxd** [comment]
You can open menu item "window->preference" ,find “sql auto complete”，checked "replace current word"。You can  solve the problem。

**Comment by xfzhaoxd** [comment]
This problem may be a bug.

**Comment by serge-rider** [comment]
This issue was resolved  in #4450
You could just re-download 5.2.3 verion.
