### ISSUE TITLE
DBeaver new version release checker has encountered a problem

### ISSUE THREAD

**Issue by workguy66** [dbeaver/dbeaver#4467]
DBeaver new version release checker has encountered a problem.

`java.lang.NullPointerException`

![selection_341](https://user-images.githubusercontent.com/12811206/47342625-6d357280-d6a4-11e8-816c-3717f8b31a72.png)

Dbeaver 5.2.0
Ubuntu 14.04

**Comment by infectormp** [comment]
Duplicate of #4264
