### ISSUE TITLE
No more access to the Sessions and Locks functions on my PostgreSQL database

### ISSUE THREAD

**Issue by iceman35** [dbeaver/dbeaver#4468]
I don't have access anymore to the Administration functions of my 9.2.15 PostgreSQL database on the latest releases of DBeaver.

However, I downgraded to the version 5.1.6 of DBeaver and the Sessions and Locks functions are back.

Could you fix this issue ?

Thanks.

**Comment by serge-rider** [comment]
Please provie more info. Sessions and Locks should be there (moreover now they are accessible from tools context menu as well as from main menu Database/Tools).

**Comment by iceman35** [comment]
Hi,

The administer menu always empty as you can see in the picture. However, I didn't know those functions were accessible on the Tools menu. The picture shows <Empty> but if I click again on the database name (dw), the functions will appear in the Tools menu (second picture).

And I can see the Sessions function (not sure why Locks isn't there...) on an older version of DBeaver (5.1.6) (third picture).

It might be related to the version of PostgreSQL because I think it was working fine on a 9.6 PG database.

![dbeaver5 2 3](https://user-images.githubusercontent.com/33490787/47346259-08324a80-d6ad-11e8-9d7a-2fe635091ae7.JPG)

![dbeaver5 2 3_ok](https://user-images.githubusercontent.com/33490787/47346488-9ad2e980-d6ad-11e8-887c-2908e2ceadc6.JPG)

![dbeaver5 1 6](https://user-images.githubusercontent.com/33490787/47346568-c0f88980-d6ad-11e8-96ce-e63ae09dfc87.JPG)

**Comment by iceman35** [comment]
PG version : 9.2.15

**Comment by serge-rider** [comment]
Well, then it is works as expected (sessions and locks aren't supported by PostgreSQL server 9.2 and earlier).
