### ISSUE TITLE
Autocomplete breaks when there are (I guess) 2 similar column names

### ISSUE THREAD

**Issue by 5hiva** [dbeaver/dbeaver#4469]
Hello,

In my table there are 2 similar columns:
- status_update_user
- status_update_timestamp

Untill I use any of them autocomplete works fine.
When I use either of them I stop getting any autocomplete proposals for columns in this table. In the proposals there are only schema/table names.
I've been having this problem for dozens of previous versions as far as I remember.

I'd appreciate a fix in this matter.
Thanks!

**Comment by digulla** [comment]
I have a similar problem. I type "select cli" and get autocomplete for the table "client". Then I press "." and then autocomplete / Ctrl+Space says "no suggestions".

Shift+Ctrl+Space works when the case matches. (ie. when I already have "select name", "na" work, "NA" doesn't).

Oracle uhm ... is there a way to see the connection metadata somewhere? 11, I think
Dbeaver 5.2.3 CE

**Comment by darkmawi** [comment]
Here's another one related to autocomplete.

If I type something, let's say "gen" to autocomplete to "general", then select the column name, the part of string I typed before is been appended to the autocompleted one, in this case I will have "generalgen"

**Comment by 5hiva** [comment]
This is the problematic table.
One thing to point out - there are other tables in this and other schemas that have names and fields with with 'status' in their names. However, only using either of these 2 field names (status_update_timestamp, status_update_user) in an sql breaks the autocompletion.

[create_table.txt](https://github.com/dbeaver/dbeaver/files/2528529/create_table.txt)

**Comment by uslss** [comment]
There is no update on the ticket for more than a year.
Ticket is closed.
If the issue is still reproducible for you - feel free to reopen the ticket and add some details that could help to reproduce the issue or create the new one.
