### ISSUE TITLE
Using Variables after "Create Table"

### ISSUE THREAD

**Issue by AryehGielchinsky** [dbeaver/dbeaver#4470]
I'm having trouble using variables after a `Create Table` statement. The code below throws a syntax error on `:` but works without the  `Create Table` statement. I'm using Vertica and DBeaver 5.2.3
Thanks
```
@set start_date='2018-10-15 00:00:00'
CREATE TABLE IF NOT EXISTS my_table AS
select :start_date
```

**Comment by serge-rider** [comment]
By default parameters in DDL queries are disabled. They can be re-enabled by turning special prfs option on:
![image](https://user-images.githubusercontent.com/6398845/67794874-7531aa80-fa8e-11e9-91aa-ec24f867563d.png)

However, I think we can enable variables usage in DDL.
So you can run query like
```sql
@set start_date='2018-10-15 00:00:00'
CREATE TABLE IF NOT EXISTS my_table AS
select ${start_date}
```

This feature wuill be enabled in 6.2.4
