### ISSUE TITLE
Code assists -  removing next characters

### ISSUE THREAD

**Issue by surpavan** [dbeaver/dbeaver#4472]
Code assist ctrl+space is delete the word/character gap that is next to it.

Actual sentence: select t.created_date, t.id

Image the statement is : select t.created_d, t.id
after  '_d' I press the ctrl+space and select the word: the result is select t.created_datet.id.

Instead it should be select t.created_date, t.status.

**Comment by serge-rider** [comment]
Duplicate of #4450
Already fixed in 5.2.3 hotfix (jsut re-download)

**Comment by surpavan** [comment]
This is still there in the new version too.  But the given alternative in #4450 solved the problem.

My version:
![capture](https://user-images.githubusercontent.com/37795549/47407995-38481f00-d77b-11e8-9a1e-0381f2cc3a49.PNG)

**Comment by serge-rider** [comment]
This was fixed in #4475 (there were two separate bug in sql completion)/

**Comment by surpavan** [comment]
ok Thank you. Will wait for the new version to download.
