### ISSUE TITLE
Dbeaver: Adhoc chart based on resultset

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#4474]
DBeaver - Version 5.2.3 CE
Operating System: Windows 10
JDBC Driver: mssql-jdbc 7.0.0.jre10
Database: Microsoft SQL Server Database

I recently looked at Azure Data Studio which is a new database client built  by Microsoft for everyday use. Similar to Dbeaver, but only for SQL Server.
One of the things caught my eye was the way a quick chart was built by the client based on the resultset of the sql query on click of a button.

Although it is at a very basic level so far on their client. I was thinking this might be an added small feature for quick visualization or quick reporting for Analytics people who use DBeaver.

@serge-rider Please let me know what do  you think ? If we can add this feature to Dbeaver in future maybe ?

**Comment by serge-rider** [comment]
Agreed, this is very handy. We have query-based charts in short plans (at least for grouping panel). I will check Azure studio to see what they have.

Setting 5.2.5 milestone although there are very few chances to have it by then - this is more like a reminder.

**Comment by p91paul** [comment]
This was closed, but am I wrong or there is no chart view in 5.3.0? Just text view for the grouping panel and sort by count (which is a nice addition, but unrelated to this feature request from a user POV)
