### ISSUE TITLE
Auto Complete not functioning in 5.2.3

### ISSUE THREAD

**Issue by jseuribe** [dbeaver/dbeaver#4475]
Hey,

So prior to this, I was using the previous version of DBeaver (5.2.2) on Ubuntu 16.04.

When using tab key auto-completion, there's a bit of extra text that makes it over to the right side of what you were trying to auto-complete. So if you were trying to write `public.tablename`, you would get something like `public.tablenameta`, pre-pending the intended table name to the front of what you've already typed out.

**Comment by sinamotamedi** [comment]
Can confirm similar behavior on 5.2.3 macOS Sierra. It auto-completes but whatever you had typed before tab completing gets appended to the end of the auto-completed word.

**Comment by itsnotv** [comment]
I think this is same as https://github.com/dbeaver/dbeaver/issues/4450

Can you do a hotfix release?

**Comment by serge-rider** [comment]
@itsnotv no, its not the same. But similar.
Not yet sure how to resolve it better..

**Comment by Fanthomaz** [comment]
Hi !
I was with same issue, try this:
Preferences > Editors > SQL EDitor > SqlCompletation 
then check Replace Current word

**Comment by serge-rider** [comment]
I've published Early Acccess  version (https://dbeaver.io/files/ea/). 
Please check it, if it'll be ok then I'll re-publish version 5.2.3.

**Comment by serge-rider** [comment]
Hotfix verion has been released
