### ISSUE TITLE
5.2.3 - Computing additional info

### ISSUE THREAD

**Issue by Fanthomaz** [dbeaver/dbeaver#4477]
Hi all!
Recently update to 5.2.3 and every table i run a simple query the client run 2 ~ 5 backgrounds tasks of "Computing additional info" and takes a lot of time to end.(counting 10 minutes of last try)

Database : oracle
OS : windows

**Comment by serge-rider** [comment]
I  can't reproduce this.
Coul you open Query Manager view and check what exactly queries are eecuted by DBeaver at that moment? (you will need to enable metadata queries viw in filter settings)

**Comment by Fanthomaz** [comment]
This happening before the query was executed; noticed too its only happen on the first select of a table, the second same select and the next ones are instantaneous;

I didn't find where enable metadate query(😢 ) 

![image](https://user-images.githubusercontent.com/44413410/47424673-8bf83f80-d75e-11e8-9315-d1538b61133e.png)
![image](https://user-images.githubusercontent.com/44413410/47424782-e396ab00-d75e-11e8-9870-f06499cb0393.png)

**Comment by serge-rider** [comment]
@Fanthomaz how to view meta queries:

![image](https://user-images.githubusercontent.com/6398845/47608692-5a22f980-da3a-11e8-8134-de521d6fa635.png)

![image](https://user-images.githubusercontent.com/6398845/47608707-8e96b580-da3a-11e8-834f-a67459445656.png)

![image](https://user-images.githubusercontent.com/6398845/47608710-9b1b0e00-da3a-11e8-853e-693bd1b4a23f.png)

**Comment by serge-rider** [comment]
@lucassimibueno this is because we enabled "Show row count for tables" by default. Apparently it was a bad idea.
I'll disable it in the next version.
Thanks for the bug report.

Workaround: disable it manually:
![image](https://user-images.githubusercontent.com/6398845/47608752-41671380-da3b-11e8-837d-c8ee1de6fd40.png)

**Comment by Fanthomaz** [comment]
Works

> 
> 
> @Fanthomaz how to view meta queries:
> 
> ![image](https://user-images.githubusercontent.com/6398845/47608692-5a22f980-da3a-11e8-8134-de521d6fa635.png)
> 
> ![image](https://user-images.githubusercontent.com/6398845/47608707-8e96b580-da3a-11e8-834f-a67459445656.png)
> 
> ![image](https://user-images.githubusercontent.com/6398845/47608710-9b1b0e00-da3a-11e8-853e-693bd1b4a23f.png)

WORKS !"!! thx guys

**Comment by serge-rider** [comment]
Eventually I've been able to reproduce the bug with slow "Computing additional info".
It is resolved in #4486
