### ISSUE TITLE
[Oracle] Ability to create index for Materialized View

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#4478]
It seems that handling of materialized views in Oracle is not complete and has some bugs.

1. When creating a materialized view, DBeaver generates a
`create or replace materializedview`
Oracle doesn't support replace, just create. - _solved_

**2. I am not able to create indexes for an materialized view. There's no such option.**

**Comment by uslss** [comment]
issue with materialized view is already fixed.
@JamesInform is second issue still actual for you?
