### ISSUE TITLE
Simple translation typo (to Spanish)

### ISSUE THREAD

**Issue by elpablete** [dbeaver/dbeaver#4479]
Simple spelling error in Spanish localization. I could correct it but I don't know where to make the change.

Error in synonyms translation.

![image](https://user-images.githubusercontent.com/2029290/47386744-0f6c4f00-d6d3-11e8-90a8-c321273aff43.png)

**Comment by serge-rider** [comment]
It is here: https://github.com/dbeaver/dbeaver/blob/8080c383890c1e454869bb92d62b14fb4acc33cc/plugins/org.jkiss.dbeaver.ext.oracle/OSGI-INF/l10n/bundle_es.properties#L58

Instructions are here: https://github.com/dbeaver/dbeaver/wiki/Localization

However for a simple typo you could just post correct string here and I'll fix them myselves.

Thanks

**Comment by ajperez81** [comment]
Yes, it happens _almost_ everywhere, at least since 3 versions ago. Not everywhere though, for example in the "Help" menu, the entry for "Installation information" is shown correctly as "Información de instalación", with both "ó". However, in the same menu we also have "CrЙditos" instead of "Créditos".

**Comment by szarza** [comment]
Yes, it might be an encoding error. I.e.: the exit dialog attached.
![imagen](https://user-images.githubusercontent.com/12150162/57216476-38f62380-6ff0-11e9-82fa-fc8cf494cf01.png)

**Comment by NitemareReal** [comment]
I confirm this bug is still present, but only in some texts, not yet solved, after more than 6 months... What is happening???
![dbeaver](https://user-images.githubusercontent.com/28754812/58549484-e7664080-820b-11e9-9f5c-5cd3c911d1d5.jpg)

**Comment by serge-rider** [comment]
@NitemareReal I can't fix this as I don't know Spanish. 
I believe this can be easily fixed by any Spanish-speaking person (instructions are above)

**Comment by Nisgrak** [comment]
I follow the above instructions to publish some changes to translations, but when I try to publish the branch the github dekstop fails with the next error.
![image](https://user-images.githubusercontent.com/19597708/61649129-20bda880-acb1-11e9-935a-713b6e3c48c8.png)

**Comment by pmiranda-geo** [comment]
Same here. Spanish is present in maybe 70% of all texts. The rest are in english.

**Comment by Nisgrak** [comment]
I translate a few more texts, but can publish the changes and the mod didn't answer.

**Comment by Nisgrak** [comment]
I create a PR(#6980) to upload this changes.

The instructions in https://github.com/dbeaver/dbeaver/wiki/Localization are wrong, we need to fork the project, make the changes there and then create a PR.
