### ISSUE TITLE
Filters in Data tab are not saved after applying

### ISSUE THREAD

**Issue by sergtop** [dbeaver/dbeaver#4480]
After applying a filter in the data tab of a table this filter is not saved in the list of previously used filters (I think the caret down button to the right of a text field is supposed to hold these filters)
MacOS 10.14.1
DBeaver 5.2.3

**Comment by Sappurit** [comment]
Yes, it's very handy function but it couldn't save. and can't remember the previous histories.

**Comment by akilovich** [comment]
Duplicate of https://github.com/dbeaver/dbeaver/issues/10343.
