### ISSUE TITLE
Export Resultset Broken with Variables in MySQL

### ISSUE THREAD

**Issue by benyanke** [dbeaver/dbeaver#4481]
When using variables, running [right-click -> export resultset] results in an empty dataset being exported.

Example query:

```
SET @attr_name = 'var1';

SELECT field1, field2
FROM table1
WHERE field like @attr_name
```

The final exported CSV ends up just being a listing of headers instead of the data (despite the data being shown in the sql view).

(editing ticket with better details about the failure mode, initially thought it was another issue)

**Comment by uslss** [comment]
thanks for the bug report 
(sorry for the late response)

**Comment by serge-rider** [comment]
I believe the bug is in query itself.
It has to be something like this:
```sql
@set attr_name = 'var1';

SELECT field1, field2
FROM table1
WHERE field like :attr_name
```
