### ISSUE TITLE
Autocomplete wrong popup sequence

### ISSUE THREAD

**Issue by Bullnados** [dbeaver/dbeaver#4484]
In Autocomplete settings I had marked all settings. (Database-Editors-SQL-Editor-SQL auto complete
Version 5.2.3
![grafik](https://user-images.githubusercontent.com/11041576/47480164-c67ddd00-d82f-11e8-898d-89351830320a.png)

First entry I would sugest richpage and not the sequence shown in screenshot

**Comment by infectormp** [comment]
https://github.com/dbeaver/dbeaver/issues/4482

**Comment by Bullnados** [comment]
First, I thought I downloaded the updated version cause I download on 24.10. That was a miss.
So I redownload 5.2.3 but still same problem. (5.2.3.201810232047)
I will close the issue and write in #4482

**Comment by Bullnados** [comment]
I think the sequence order here is an other bug?

**Comment by p91paul** [comment]
looks like it is sorted alphabetically...but it would be great to prefer suggestions **starting with** the search string

**Comment by Bullnados** [comment]
But why is the first row with rel_ shown? There is no "rich" inside

**Comment by p91paul** [comment]
autocomplete uses fuzzy search. Which means is searched like '%r%i%c%h%'

**Comment by serge-rider** [comment]
Yep. It is a bug in sorting (or in fuzzy scoring).
