### ISSUE TITLE
Autocomplete: wrong completion of column name

### ISSUE THREAD

**Issue by sqlpro20** [dbeaver/dbeaver#4485]
On Postgres/DBeaver 5.2.3, I if I type something like this:

select *
from mytable
where somec<autocomplete>

DBeaver replaces this with "somecolumn"somec - it adds my typed letters at the end of the correctly found column name. It does this in all cases - if I type parts of the name first and then hit autocomplete and if I first hit autocomplete and then begin typing.

Because this version is unusable to me, I think I'll downgrade to the latest working version: 5.1.1.

**Comment by infectormp** [comment]
Why no one uses search here? https://github.com/dbeaver/dbeaver/issues/4482

**Comment by sqlpro20** [comment]
Why do people use topics that do help nobody? Topic of #4482 is: Problem with autocomplete. That's close to no topic at all. I have ~20 matches if I search for autocomplete. If I search for 'autocomplete column', this issue is not listed.

**Comment by sqlpro20** [comment]
Closing as this is indeed a duplicate of #4482 Downloading and installing the new version helped.
