### ISSUE TITLE
Error drawing editor on 5.2.3

### ISSUE THREAD

**Issue by marco-sanjuan** [dbeaver/dbeaver#4487]
Hi
Each time y press enter, editor redraw wrong scrollbars. 
Better to see screenshot. It is for 4 returns.
![image](https://user-images.githubusercontent.com/4165141/47490821-cf7ba800-d849-11e8-85e8-8e91a5a8e25a.png)

Also, in any case, editor content is hidden under wrong redraw, and only back to be visible again when you move cursor over the line.

Os Debian 9 with XFCE

Thanks

**Comment by hoyon** [comment]
I'm having the same issue and am also on Debian 9 but with Gnome.

The issue also occurs when scrolling in ER Diagram view and makes it basically unusable.

**Comment by batlley** [comment]
I am having the same issue on CentOS 7.4 with MATE 1.16.2

**Comment by marco-sanjuan** [comment]
Hi Serge

EA version now draw editor as expected, but has back the bug that closes dbeaver when showing the popup on long time operations (issue #4075).

So i had to back to 5.2.2 version.

**Comment by serge-rider** [comment]
I think the only way to handle #4075 is to disable notifications popup on Linux (preference page `Database`).
