### ISSUE TITLE
5.2.3 Error connection MS SQL Server 2005

### ISSUE THREAD

**Issue by antoniogarcia78** [dbeaver/dbeaver#4488]
Dbeaver 5.2.3
MSSQL 2005
Driver: MS SQL Server / Microsoft Driver 
Driver Details:
Microsoft Driver
com.microsoft.sqlserver:mssql-jdbc:RELEASE
maven:/com.microsoft.sqlserver:mssql-jdbc:RELEASE
6.2.2.jre8

Error
SQL Server did not return a response. The connection has been closed. ClientConnectionId:6f7cab6b-ca5f-43b5-b7da-a77c7cac123b

Error Details
The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "SQL Server did not return a response. The connection has been closed. ClientConnectionId:6f7cab6b-ca5f-43b5-b7da-a77c7cac123b".
  SQL Server did not return a response. The connection has been closed. ClientConnectionId:6f7cab6b-ca5f-43b5-b7da-a77c7cac123b
  SQL Server did not return a response. The connection has been closed. ClientConnectionId:6f7cab6b-ca5f-43b5-b7da-a77c7cac123b

In 5.2.0 work OK
In 5.23 with jTDS Driver work OK

**Comment by serge-rider** [comment]
Well, DBeaver doesn't support SSL UI configuration for MS SQL (yet). Error says it is the bug configuration. So most likely there is some issue with your connection configuration.
I can't realize how DBeaver is related to this..

**Comment by antoniogarcia78** [comment]
I do not know what the differences between Microsoft drivers and jTDS are but with jTDS it is working correctly.
I'm satisfied with this.
I just wanted to emphasize that in the old version 5.2.0 the Microsoft driver worked.
