### ISSUE TITLE
Export makes a new query

### ISSUE THREAD

**Issue by romad17** [dbeaver/dbeaver#4489]
Hi,

After I've got the SQL result, I want to export it with "Export Resultset..."
But instead of exporting the already received data, it initiates a new SQL query run.
This cause a time waste because I need to wait for the same query to run second time.

Can you please make it export simply the already retrieved data?

Thanks.

**Comment by serge-rider** [comment]
This is already implemented. Enable option "Selected rows only" in export wizard:

![image](https://user-images.githubusercontent.com/6398845/47608887-a4f24080-da3d-11e8-9de0-446929396567.png)

**Comment by romad17** [comment]
Thanks a lot! super cool!
