### ISSUE TITLE
Suggestion: use new version number when releasing hotfixes

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#4490]
When you release hotfixes, like you did with 5.2.3, you continue to receive duplicate bug reports until the next version. I think it would help you to release hotfixes not as 5.2.3 but as 5.2.3.1, 5.2.3.2, ...

Doing it this way, the new version check would tell users a new version is available and the number of duplicate bug reports should lower.

**Comment by infectormp** [comment]
+1

**Comment by serge-rider** [comment]
Agreed. 
We already use build numbers (like `5.2.3.201810182116`) but build number is not used in GitHub tags / release announcements.
Not sure how to handle this better..

**Comment by p91paul** [comment]
Aren't tags something **you** choose? I don't believe you are forced to max 3 version components when creating a release, are you?

**Comment by p91paul** [comment]
Ok, what about you increase the second number every 2 weeks instead of the third, which would be left for hotfixes? Sure the second number would go up quite fast, but I think it would get to something like 5.20-5.30, not 5.100 before 6.0 is out.

My personal opinion is that you should release less often, or alternate a feature release with one or more bugfix-only while you work on new features on a different branch, but that's quite offtopic here.

**Comment by p91paul** [comment]
Another alternative is using 5.2.4 for 5.2.3 hotfixes, but that would be a PITA because you would need to move all your planned issue to the next milestone.

Changing the update checker to include the build number in the check might not be feasible and would not solve the issue for those updating through debian or rpm repositories....this is a difficult issue indeed!

**Comment by serge-rider** [comment]
Yep. We are thinking about some changes here. As you may see we have a lot of tickets. Two-weeks sprints may be too short to handle them properly..

**Comment by p91paul** [comment]
I believe this issue can be safely closed, it's your internal policy anyway. :smile:
