### ISSUE TITLE
Lost dictionary view

### ISSUE THREAD

**Issue by jkeruzec** [dbeaver/dbeaver#4491]
Dear all,

I just lost Dictionary view and I can't find a way to display it again... I search on internet, on DBeaver docs, on settings... nothing

This right panel here to see foreign key dictionary value from one request/table view :
![image](https://user-images.githubusercontent.com/3499632/47505111-c7356400-d86d-11e8-9249-280413ee64bb.png)

Am I missing something, if someone could tell me ? 

Thanks !

**Comment by mterwoord** [comment]
I'm suffering the same thing. 
It seems to be introduced the moment I switched to version 5.2.5.

Did you manage to solve this?

**Comment by jkeruzec** [comment]
@mterwoord Not yet !
