### ISSUE TITLE
Invalidate/Reconnect before save data

### ISSUE THREAD

**Issue by fxc1** [dbeaver/dbeaver#4494]
Hi,
could you make available auto-reconect feature before save table data.
scenario: browsing table data (just select), [looooong time nothing...], edit some row/column, press [Ctrl]+[s], and then closed connection dialog appears...
I thnik it's related to #2201. 
Thanks.

Version: 5.2.2

**Comment by mnovello** [comment]
Same problem. Auto-reconnect does not work when saving table data after the table has been open for a long time. I have to manually invalidate and reconnect.

**Comment by mnovello** [comment]
Connection auto-recover is enabled (box is checked). It just doesn't work as I stated above.

**Comment by uslss** [comment]
cannot reproduce it for now.
If it is still actual - feel free to reopen the ticket
