### ISSUE TITLE
SSL Factory is greyed out on new connection with remote PostgreSQL

### ISSUE THREAD

**Issue by elethan** [dbeaver/dbeaver#4506]
Hi guys
It seems that in latest version (5.2.3) the SSL Factory drop down is not enabled or not populated. It works fine on 5.1.6 (and older).
I'm on Ubutnu 18.04 trying to connect to a remote PostgreSQL (Heroku)

Kind regards

**Comment by serge-rider** [comment]
Could you post a screenshot? Because in my env it works ok.
Also maybe there are some related errors in debug log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

![image](https://user-images.githubusercontent.com/6398845/47666531-d0e40200-dbb4-11e8-8714-0860266a60dc.png)

**Comment by elethan** [comment]
Thanks for your reply, I'm afraid I can't reproduce it now. After uninstalling 5.1.6 and re-installing 5.2.3, it works
