### ISSUE TITLE
Feature Request: Shortcut key for find table

### ISSUE THREAD

**Issue by mstup** [dbeaver/dbeaver#4507]
I have a huge list of tables in DB. For me it looks really useful to be able to find necessary table by sub-name, as it works for **Open Type** in Eclipse.

As for me, acceptable shortcut key is:
Ctrl + Shift + T

**Comment by serge-rider** [comment]
It is already there: <kbd>Ctrl+Shift+D</kbd>.

**Comment by mstup** [comment]
Looks workable for me
