### ISSUE TITLE
Can't uninstall DBeaver 5.2.3 trial as Eclipse plugin

### ISSUE THREAD

**Issue by u02sgb** [dbeaver/dbeaver#4511]
Hi,
  My trial has run out and I'd like to uninstall DBeaver 5.2.3 plugin from Eclipse.  When I try to uninstall it from Eclipse marketplace I get the messages below and it refuses to uninstall.  I've selected the SVG support and Office integration to be uninstalled as well so I don't think there's anything left that relies on it.

I'd normally just leave it but I'm getting nagged for a registry key every time I startup Eclipse.  Is there a manual way to remove the plugin?

Error details from Eclipse marketplace uninstall dialog:
""DBeaver Generic Extension" cannot be fully uninstalled because other installed software requires it.  The parts that are not required will be uninstalled.
"DBeaver Core" cannot be fully uninstalled because other installed software requires it.  The parts that are not required will be uninstalled.
"DBeaver Runtime" cannot be fully uninstalled because other installed software requires it.  The parts that are not required will be uninstalled.
"DBeaver SVG Extension" cannot be fully uninstalled because other installed software requires it.  The parts that are not required will be uninstalled.
"DBeaver Office Support" cannot be fully uninstalled because other installed software requires it.  The parts that are not required will be uninstalled."

**Comment by serge-rider** [comment]
You can uninstall DBeaver from Installation details:
Main menu Help -> About Eclipse IDE -> Installation Details -> Select all DBeaver* elements -> Uninstall.

**Comment by u02sgb** [comment]
Thanks, that's it uninstalled now.
