### ISSUE TITLE
SSH Tunnel to server thru a jump server

### ISSUE THREAD

**Issue by dhavalkshah** [dbeaver/dbeaver#4516]
Hi,

I have setup where i have jump server in between
So it is like: Client --SSH--> Jump Server --SSH--> Server
In my mac i have used ProxyCommand in .ssh/config to create a ssh tunnel to the server
Thus my config file has server defined as:

```
Host jump
        HostName <JUMP IP>
        User dhaval
        IdentityFile <PATH TO KEY>
Host app
        HostName <APPIP>
        User dhaval
        IdentityFile <PATH TO KEY>
        ForwardAgent yes
        ProxyCommand ssh jump nc %h %p 2> /dev/null
```
Thus I am able to do a ssh to server using command `ssh app` 
 
Now the queries:
1. I am not able to use app as host name in Dbeaver, although it is mentioned in .ssh/config
2. When I try IP of jump server and test ssh tunnel in DBeaver it goes thru but if I use IP of server it doesn't go thru

Any pointers will be helpful

~DKS

**Comment by ericmjalbert** [comment]
I'm having a similar problem as this. Is there any update or workaround for it?

**Comment by svanscho** [comment]
Any update?

**Comment by yutaro1985** [comment]
I also have a similar issue.
Is there any way to use ssh/config?

**Comment by jgomo3** [comment]
Maybe there is a possible workaround if we could write the exact shell command to use for SSH connection, so in the example mentioned in this ticket, instead of filling the form we could opt to write: `ssh app` or `/usr/bin/ssh app`.

Or adding support for the `-J` flag in OpenSSH.

Meanwhile... what workaround would you suggest?

**Comment by jgomo3** [comment]
As a feature request:

1. Add support for the -J flag in OpenSSH.
2. Allow a free form field to just write the ssh command. E.g. `ssh app`.

Meanwhile... what workaround would you suggest?

**Comment by Nimeshka** [comment]
I have the same problem, and there's no way to connect. So I switched back to PgAdmin until there's a solution for this in Dbeaver. It works in PgAdmin.

**Comment by serge-rider** [comment]
Probably this issue will be resolved by #7164
Thanks to @bsv798

**Comment by uslss** [comment]
verified

**Comment by Jormangeud** [comment]
OP wanted:
Client --SSH--> Jump Server --SSH--> Server.
Use case: ssh through a gateway into a virtual machine's sshd, and use port forward from there.

#4516 implements this:
Client --SSH--> Remote host --port forward--> Server.
This doesn't work if the Server allows only SSH from outside and database connections are limited to localhost.

**Comment by jgomo3** [comment]
> This doesn't work if the Server allows only SSH from outside and database connections are limited to localhost.

In that case both Remote host and Server must be the same machine. Then, it should work.

**Comment by sfog17** [comment]
I have a similar problem
The work around with "Shell Commands in connections settings" doesn't work for me

The only solution I found so far is to:

- Connect to the jumphost (`ssh jumpuser@jumphost`)
- From the jumphost, local forward the port (`ssh -f -N user@target -L portJump:localhost:portDB`)
- Then go back to my local machine and I can connect via DBeaver (SSH tab, host: jumphost, user: jumpuser, port: portJump)

**Comment by stabylo** [comment]
For those remaining blocked by this approach : 
Client --SSH--> Jump Server --SSH--> Server

The following ssh command in terminal allowed me to forward local port 1234 to Server port 5432
ssh -L 1234:localhost:5432  [user]@[Jump Server Address] [user]@[Server Address]

Then i was able to connect directly with dBeaver on port 1234 (without using SSH tunnel configuration) 

But i would appreciate to be able to do that without using terminal and stay in dBeaver.
#7164 didn't solved it for this.
