### ISSUE TITLE
Strange behaviour in column reorder

### ISSUE THREAD

**Issue by esteban-turnocheck** [dbeaver/dbeaver#4519]
Hi!
Before anything, let me say I'm really, really glad I've found dbeaver. It's great! I'm happy.
Now, I think I've found a slight issue.
I can't seem to be able to order columns in "Properties" window of the table, but can see the reordering happen (with some strange behaviour, though, because it looks like it's moving the column that's next to the selected column) in the "Project" window, to the left.
Here's the capture.

![peek 2018-10-31 13-04](https://user-images.githubusercontent.com/22857390/47802370-dfdec780-dd0e-11e8-884c-c6999d5696fd.gif)

**Comment by uslss** [comment]
issue is not actual anymore.
Ticket closed
