### ISSUE TITLE
DBeaver won't open Windows 10

### ISSUE THREAD

**Issue by DDeathlonger** [dbeaver/dbeaver#4521]
I don't even know what to say... It shows the initial splash screen, then disappears shortly after. If I uninstall and reinstall it fixes it for one run, but the next time I run it again, it does the same with the splash screen. Persists even if I restart my laptop. After the splash screen disappears there is nothing in the detailed task manager or processes. I'm running a HP EliteBook 8570w with Windows 10... I love this application, but I have no idea what's wrong. Is there a way I can export a log or something? I am a programmer also so feel free to be detailed if you have any thoughts or anything you need from me.

**Comment by serge-rider** [comment]
- How do you install it (Windows installer, zip) ?
- Please post error/debug logs (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by DDeathlonger** [comment]
I'm using the installer. Where can I extract the logs from?

**Comment by DDeathlonger** [comment]
Here the Log:
[DBeaver.log](https://github.com/dbeaver/dbeaver/files/2541296/DBeaver.log)

**Comment by serge-rider** [comment]
Thanks for details.
Yes, the process fails before DBeaver even start so no other logs was created.

Perhaps this can be solved by using newer Java version. Could you try to download newer java (9 or 10) from https://jdk.java.net/java-se-ri/8 or from Oracle https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html
Install it and then download DBeaver in zip archive?

We are going to upgrade bundled Java version in any case but if it will help in your case we'l do this faster.
Thanks

**Comment by serge-rider** [comment]
Umm, In debug log I see that you have started DBeaver and even connected to a database. 
Does it mean that it worked eventually?

**Comment by DDeathlonger** [comment]
No. It runs after the initial install, after that, it won't open again unless I completely reinstall it again - even if I restart my computer.

**Comment by serge-rider** [comment]
I think we found why this happens in #4791 . Because first time DBeaver starts with administrator permissions - if you run it directly from installer and install it for all users.

I've just removed this option (start from installer). This makes DBeaver installation a bit less comfortable operation but it is much more safe.

Anyway, at some moment we will replace current Windows installer with msi installer which, hopefully, will solve this problem (and let to start DBeaver right from installer).

Please check how it works in version 5.3.1.

**Comment by piposeimandi** [comment]
lo venia usando y de un dia para el otro  no ejecuta mas  , probe reinstalar y no lo soluciona .

**Comment by SudhirPhadtare** [comment]
Try to open DBeaver "Run as administrator' in windows to resolve the issue

**Comment by jonnelesguerra** [comment]
I was having the same issue as well but using Portable Dbeaver. Tried to use different DBeaver Versions but was unable to resolve the issue. Fortunately, i was able to resolve it by removing the DBeaverData Folder in Directory %HOMEPATH%/AppData/Roaming

**Comment by elvinyalung** [comment]
> I was having the same issue as well but using Portable Dbeaver. Tried to use different DBeaver Versions but was unable to resolve the issue. Fortunately, i was able to resolve it by removing the DBeaverData Folder in Directory %HOMEPATH%/AppData/Roaming

Good Job, this worked for me.. Thanks to this guy. kudos!

**Comment by JohnCongerCC** [comment]
> I was having the same issue as well but using Portable Dbeaver. Tried to use different DBeaver Versions but was unable to resolve the issue. Fortunately, i was able to resolve it by removing the DBeaverData Folder in Directory %HOMEPATH%/AppData/Roaming

that worked for me too!

**Comment by lokeshwar9** [comment]
removing the DBeaverData Folder in Directory %HOMEPATH%/AppData/Roaming
 The above works ,Thanks.
 But, you may loose your connected databases and have to reconnect again to avoid this.
 go to recycle bin and restore the dbeaver data but choose skip for existing files.
 you will have the dbeaver working as earlier.

**Comment by shrikhaparul** [comment]
> I was having the same issue as well but using Portable Dbeaver. Tried to use different DBeaver Versions but was unable to resolve the issue. Fortunately, i was able to resolve it by removing the DBeaverData Folder in Directory %HOMEPATH%/AppData/Roaming

it really worked...much thanks

**Comment by RamRivas** [comment]
> lo venia usando y de un dia para el otro no ejecuta mas , probe reinstalar y no lo soluciona .

Me paso lo mismo viejo, :C

**Comment by samueloni110** [comment]
How do I locate Dbeaverdata folder in directory
