### ISSUE TITLE
SQL Editor with problem

### ISSUE THREAD

**Issue by cassunde** [dbeaver/dbeaver#4523]
**My ambient:**
- Ubuntu16
- dbeaber 5.2.3
- java1.8

**Problem**
When we type in the SQL Editor, the specific area shows a strange bar in the middle of the screen, making it difficult to create the sql statement.

Picture with error:

![screenshot from 2018-11-01 09-06-25](https://user-images.githubusercontent.com/3828140/47851140-73b79e80-ddb6-11e8-8c9e-3c7f8d012bd5.png)

**Comment by luiseduardo** [comment]
Same issue

My ambient

- Mint 18.3 Cinnamon
- Dbeaver 5.2.3
- Java Oracle 1.8.0_181
- JRE 1.8.0_181-b13

**Comment by offstate** [comment]
I found the same redraw bug in any script editor window after horizontal scrolling.

**Comment by serge-rider** [comment]
Duplicate of #4487
Please test the fix in Early Access (https://dbeaver.io/files/ea)

**Comment by cassunde** [comment]
Ok!! I tested the bug using version 5.2.4 and the fix is resolution.. :+1: 

**obs:** i used postgresql connections to tests

please @laurentgo and @dankrop and @offstate as soon as possible test in your environments to close this problem

Thanks

**Comment by laurentgo** [comment]
@cassunde not sure why the mention. Is it a typo/you wanted to mention @luiseduardo instead?

**Comment by dankrop** [comment]
Tested 5.2.4. Fixed. Thanks.

**Comment by cassunde** [comment]
Hi, it was not typo, just because it also reported the same problem, but could close the problem.
Thanks

**Comment by cassunde** [comment]
Closing this issue
