### ISSUE TITLE
Dbeaver Cells become readonly on MacOS

### ISSUE THREAD

**Issue by mfoufoutis** [dbeaver/dbeaver#4526]
I am using the latest dbeaver 5.2.3
When connecting to a mysql database and editing a table the cells are not editable. 
opening the cell in editor shows a readonly flag

![dbeaver - readonly](https://user-images.githubusercontent.com/33226456/47863171-949be600-ddee-11e8-8b09-ca14f8be2e4b.jpg)

the issue isnt replicatable with Windows - aka with the same user i can edit the table.

**Comment by mfoufoutis** [comment]
same connection details work fine using jetbrains datagrip tool

**Comment by serge-rider** [comment]
Please provide more details. At least:
- what MySQL driver do you use (MySQL 3.x, 5.x, 8.x or MariaDB).
- are you trying to edit table data or results of some custom SQL query.
- check connection read-only flag (in connection properties)

PS There are thousands of people who do not experience this problem with MySQL+MacOS so there have to be some issue specific to your environment. Or maybe this is just another digital marketing promo from jb :)

**Comment by mfoufoutis** [comment]
hi Serge, thanks for the reply!

I am using MYSQL java connector 8.0.13
I am trying to edit a table not a customer query here is the DDL

CREATE TABLE `report_template` (
  `TEMPLATE_ID` varchar(100) NOT NULL,
  `TEMPLATE_CONTENT` longtext NOT NULL,
  `TEMPLATE_TIMESTAMP` datetime DEFAULT NULL,
  `SCRIPT_TYPE` varchar(20) DEFAULT 'SQL',
  `TASK_IMPACT_EVALUATION` tinyint(1) DEFAULT '0',
  `DROP_VIEWS_TEMPLATE` tinyint(1) DEFAULT '0',
  `VERSION` int(11) NOT NULL DEFAULT '0',
  `CREATED_USER_ID` varchar(64) DEFAULT NULL,
  `CREATED_DATETIME` datetime DEFAULT NULL,
  `UPDATED_USER_ID` varchar(64) DEFAULT NULL,
  `UPDATED_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`TEMPLATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
Read only flag has been checked and it unticked.

even using an Update table script will fail.
It is weird that it works on a Windows machine

ps no not a JB promotion 😃

**Comment by mfoufoutis** [comment]
FYI -- i mean the i looked at the readonly flagged and it was unticked as per default

**Comment by serge-rider** [comment]
I have a clue (DBeaver marks connection read-only in some cases when driver decides that it is in read-only state, this may be OS-dependent).
Please test the fix in the Early Access version (https://dbeaver.io/files/ea/)

**Comment by mfoufoutis** [comment]
nope.. sorry didnt work:

using dbeaver-ce-5.2.4-macos.dmg     

as mentioned readonly is unticked

![image](https://user-images.githubusercontent.com/33226456/47925761-d98b4f80-deb6-11e8-86c9-21c5cd9c0917.png)

**Comment by mfoufoutis** [comment]
just tried an update statement and that worked...

:/

**Comment by serge-rider** [comment]
Thanks for testing. But now this became even more frustrating ()

Ok. Cold you try this:
- In table editor (or in some SQL query results) see columns tooltip. They should contain column name and type and, possibly, read-only flag. 
How does it  look in your case? (some screenshot would be helpful)

BTW what is your MacOS version? (I've tested it on Sierra and Mojave)

**Comment by mfoufoutis** [comment]
Hi Serge,

Happy to help, as would love to have this resolved.

Im using Macbook Pro (2015) on Mojave 10.14.1

is this the screen shot you are after?

![image](https://user-images.githubusercontent.com/33226456/47990123-a9be9080-e0de-11e8-8c9c-1fa54726c330.png)

**Comment by mfoufoutis** [comment]
Hi serge,

I just did a full uninstall and deleted all dbeaver folder. then did a clean install of 5.2.4 and the tables are editable.

this doesnt explain why suddently I couldnt edit them..

**Comment by serge-rider** [comment]
This is very odd.
I have one idea - maybe you set some custom unique key for that table. Or maybe configuration was corrupted after upgrade from some really old version of DBeaver.

Anyhow, I'm afraid that we won't find this out :(

**Comment by mfoufoutis** [comment]
yes weird indeed - at least now ill know to do a clean wipe and reinstall if i encounter this again

**Comment by mirkogrcic** [comment]
I had the same issue but have figured it out. I had the same light blue column name cells
The problem was that I have created 2 more columns (they were light blue) using SQL instead of the Properties tab. This has caused the Properties tab to not have the latest 2 columns.

I have solved this issue by going to the Properties tab and hitting F5 to refresh the column list. After that the columns were editable.

**Comment by timkrins** [comment]
I just came across this 'read-only' cell issue (Version 6.2.2.201910072100, Mac Mojave 10.14.5, MariaDB connector)

Steps to reproduce it for me were:
1. Opened the data view in DBeaver, before new column was added
2. Added new column using different tool (in my case, a migration adding an INT column)
3. Refreshed data view in DBeaver while still on data tab. New INT column is now visible.
4. Tried to edit cell - DBeaver says it is readonly.
5. Hovered over column header - tooltip says that the column is readonly.
6. Moved to table Properties tab - column does not yet show in this view.
7. Pressed refresh on the Properties tab. Column now appears.
8. Clicked back to Data tab - cell now editable and no longer marked as readonly.

**Comment by johnhaup** [comment]
@timkrins thanks!

**Comment by BartlomiejSkwira** [comment]
I had this issue on Mac Catalina 10.15.4, PostgreSQL 12, Django 3.0.6 admin application.

How I think got the issue - there might have been other important factors:
1. I had an application with some schema - I could edit other tables and I was able to add a new table to the db with DBeaver.
2. Created a new migration which added a new table that had columns: id, created (datetime) and a `jsonb` column (specific to Postgres)
3. In DBeaver on "Data" view all of the columns showed as `read-only`. In the "Properties" view the columns didn't show up at all.

How I fixed it:
1. Log in to Postgres `psql` console for this database
2. Insert 1 row with `INSERT INTO table_name (col1, col2, ...) VALUES (val1, val2, ...)` clause 
3. In DBeaver hit "Refresh" on the problematic table. That's it. New migrations create tables that are editable.

**Comment by alramdein** [comment]
@timkrins thanks, but that's so weird problem

**Comment by alramdein** [comment]
If the problems occur in every table. Basically based on @timkrins solution, just refresh the entire database connection. And it is solved the problem in my case.

**Comment by bassam127** [comment]
Hi , refresh the table and columns solve the problem for me

**Comment by drajapaksh** [comment]
> I just came across a similar 'read-only' cell issue (Version 6.2.2.201910072100, Mac Mojave 10.14.5, MariaDB connector) when adding a new column.
> 
> Steps to reproduce it for me were:
> 
> 1. Opened the data view in DBeaver, before new column was added
> 2. Added new column using different tool (in my case, a migration adding an INT column)
> 3. Refreshed data view in DBeaver while still on data tab. New INT column is now visible.
> 4. Tried to edit cell - DBeaver says it is readonly.
> 5. Hovered over column header - tooltip says that the column is readonly.
> 6. Moved to table Properties tab - column does not yet show in this view.
> 7. Pressed refresh on the Properties tab. Column now appears.
> 8. Clicked back to Data tab - cell now editable and no longer marked as readonly.

This happens in linux too. I think something wrong with the dbeaver application. Anyways above steps fixed the issue.

**Comment by lackovic** [comment]
Same issue on Windows 10 21H1: one nullable column of the result set of a SELECT query is marked as read-only in a writable database.

The column header name has a little dot of the same color of the connection type. Other nullable columns of the same result set are editable. The connection type security restrictions are all unchecked (restrict data edit, restrict structure edit, etc). Modifying the column value through an UPDATE SQL statement works fine.

Refreshing the database connection nor the table properties where the column is located did not fix the issue.

**Comment by otristan94** [comment]
same problem, version 22.0.3 in oracle database, does not allow editing from the results grid the read only box is unchecked
![Cawsa](https://user-images.githubusercontent.com/103969337/165800832-2685b53f-d760-43d7-9940-2b8801eca4eb.PNG)

![image](https://user-images.githubusercontent.com/103969337/165800914-1c0850a8-5749-4128-b122-6f9ba0dae929.png)

**Comment by durja** [comment]
disconnecting and reconnecting the connection worked for me.

**Comment by fluentcodes** [comment]
DbBeaver 22.3.4/MacOS Big Sure/M1 Mac/MariaDB: Select results are not editable after update.

**Comment by alanpcs** [comment]
For me what did the trick was based on the item 5 `Hovered over column header - tooltip says that the column is readonly.
`. My table error was showing: 'Read-only: ... No corresponding table column'. 

<img width="525" alt="image" src="https://github.com/dbeaver/dbeaver/assets/7315217/36505f47-39ce-48c4-988a-40e102c2a0a1">

So I tried adding the table alias into my columns name and it was solved...
