### ISSUE TITLE
Azure Redis (with SSL) connection could not be made 

### ISSUE THREAD

**Issue by jdvor** [dbeaver/dbeaver#4528]
EE 5.2.3.201810261805

When trying to connect to Azure **Redis**, the connection fails with:

```
Could not get a resource from the pool
  javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
  javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
    Connection has been shutdown: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
    Connection has been shutdown: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
      java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
      java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
          **the trustAnchors parameter must be non-empty**
          the trustAnchors parameter must be non-empty
```

I've used https://www.htbridge.com/ssl/ to check if SSL connection could be established and server cert is without issues. It didn't find anything wrong with it.

![1](https://user-images.githubusercontent.com/5578726/47880501-b499cc80-de23-11e8-9593-0ea428b5a7b4.png)

![2](https://user-images.githubusercontent.com/5578726/47880520-c0858e80-de23-11e8-9a52-832a78a902f3.png)

**Comment by danidb** [comment]
I'm having the same issue with ea 5.2.4  - attached the debug log. 
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/2542866/dbeaver-debug.log)

**Comment by serge-rider** [comment]
It works well if you have client certificate/key:
![image](https://user-images.githubusercontent.com/6398845/48472291-fef95100-e806-11e8-8fbf-7c047a46fcc9.png)

It also works with just client SSL certificate (private key and CA certificate are optional). But it doesn't work without certificate at all.

I'm testing with stunnel SSL proxy on server-side.

**Comment by uslss** [comment]
there is no updates almost a year.
Ticket closed.
If you have any further question or issue feel free to create new ticket

**Comment by jdvor** [comment]
> there is no updates almost a year.
> Ticket closed.
I'm confused. Whom do you expect the update to come from?
If this is situation "by design" or "minor issue which we will not fix -> up for grabs" shouldn't that be stated explicitly when closing the ticket?

**Comment by serge-rider** [comment]
@jdvor Sorry, missed this ticket.
Well, current implementation requires explicit certificate.
Self-signed (aka auto-generated) certs are not secure at all (and make whole SSL model senseless). However, in some cases it is necessary (e.g. when SSL is the only way to connect and you don't have a client certificate).

Anyway, please create a feature request for self-signed SSL certificates support for Redis.
