### ISSUE TITLE
Bug: Mysql procedure execution right menu result in SELECT statement, not CALL statement

### ISSUE THREAD

**Issue by fengchao** [dbeaver/dbeaver#4530]
Right click on a mysql Procedure, select execute procedure,  

Current result: Select xxxx.aProcedure(:param)
Run the script. Error : The Function does not exist.

Expect result: Call xxxx.aProcedure(:param)

**Comment by serge-rider** [comment]
Good point. We need to generate different code for functions and procedures.
Please check this in the 5.2.4
