### ISSUE TITLE
Tablename in Create Table Dialog (Oracle)

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#4531]
DBeaver 5.2.4.201810282259  (EA)

When creating a new table in Oracle I encountered that the table name is reversed (cursor is jumping at the beginning of the field after each keystroke) when while typing.

**Comment by serge-rider** [comment]
Actually this happens not only with Oracle tables but with all objects which name is transformed on edit (e.g. Oracle object names are uppercased).

Thanks for the bug report. See fix in the next version.
