### ISSUE TITLE
Auto-refresh

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#4532]
Auto-refresh seems to affect all opened tabs instead of just one resultset. For example it makes trouble when editing table data in grid view, because edited cell exits edit mode when auto-refresh runs.

To reproduce this open some table and enable auto-refresh in data tab. Then open another table and try to edit data.

**Comment by serge-rider** [comment]
Can't reproduce. I've tried to open multiple table or multiple tabs in SQL editor - only one tab is refreshed.

Maybe I'm missing something. Could you post a gif video (e.g. by ScreenToGif tool)?

**Comment by maln0ir** [comment]
When upgrading to version 5.3.4 I checked "Reset settings" option and my problem seems to be fixed.

**Comment by serge-rider** [comment]
Thanks for info
