### ISSUE TITLE
Feature Request: Workspace Cleanup When Uninstalling and Add repair option.

### ISSUE THREAD

**Issue by DDeathlonger** [dbeaver/dbeaver#4534]
Reference is: [DBeaver won't open Windows 10 #4521](https://github.com/dbeaver/dbeaver/issues/4521#issuecomment-435564531)

I noticed while working on this issue that the logs from previous installations are cluttering new logs for clean re-installs - delete everything except the absolute necessary files (for reinstalls like user preferences). And based on this add the option for a repair installation.

**Comment by serge-rider** [comment]
Good point

**Comment by serge-rider** [comment]
It was implemented as special menu item:
![image](https://user-images.githubusercontent.com/6398845/56430282-95f29980-62ce-11e9-9dd8-53b72ff1de0a.png)

**Comment by uslss** [comment]
verified
