### ISSUE TITLE
visualization problem

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4537]
![__](https://user-images.githubusercontent.com/799021/47984717-1ede9580-e0e0-11e8-845d-11d9c120b995.jpg)

**Comment by KES777** [comment]
Just scroll horizontal bar (5.2.3)

![__](https://user-images.githubusercontent.com/799021/47984803-62390400-e0e0-11e8-9bd6-4b11a88d97ee.jpg)

**Comment by serge-rider** [comment]
Duplicate of #4487
