### ISSUE TITLE
No Connected Oracle DB Version 5.2.0.201809092115

### ISSUE THREAD

**Issue by fdurmus77** [dbeaver/dbeaver#4541]
![123](https://user-images.githubusercontent.com/1420869/48004259-c7f9b000-e121-11e8-9b73-b47bff9bde23.png)

Custom do not work.

**Comment by serge-rider** [comment]
What exactly error do you see?
And please upgrade to the most recent DBeaver version (5.2.4 at the moment)

**Comment by uslss** [comment]
there is no update almost a year.
Ticket closed.
If issue is still actual for you - feel free to create new ticket
