### ISSUE TITLE
"Next" button greyed out when creating new connnection

### ISSUE THREAD

**Issue by jackse7en** [dbeaver/dbeaver#4542]
Able to click "Finish" but not able to click Next to change connection name and type.

DBeaver 5.2.4

![image](https://user-images.githubusercontent.com/15628830/48008744-386df480-e155-11e8-9592-8a05ec065315.png)

**Comment by serge-rider** [comment]
Click on "Connection details"  link (above Edit Driver button) in order to change name, description, etc.
Since 5.2 we have only one configuration page in the New Connection wizard.

**Comment by jackse7en** [comment]
Thanks a lot for your help!

**Comment by shahzad713** [comment]
go this error while connecting 
Error in driver initialization 'PostgreSQL'

Reason:
Driver class 'org.postgresql.Driver' not found
