### ISSUE TITLE
Communication link failure

### ISSUE THREAD

**Issue by JaimeSilva** [dbeaver/dbeaver#4544]
![image](https://user-images.githubusercontent.com/12927804/48018429-ba93f400-e128-11e8-8802-0228c85175ee.png)

Hey I am trying to connect to a database using Dbeaver, but it gives me this pop up error message.
I'm using a public network from a library, I believe it's related to that. Since I've tried another two different private networks, and it works fine on both.

What could this be?

Thanks

**Comment by p91paul** [comment]
Many public networks have firewalls blocking outbound traffic except for a whitelist of ports (e.g. 80 and 443 for http/s, and possibly a few others). Database default ports are rarely included in such a whitelist.

**Comment by JaimeSilva** [comment]
> Many public networks have firewalls blocking outbound traffic except for a whitelist of ports (e.g. 80 and 443 for http/s, and possibly a few others). Database default ports are rarely included in such a whitelist.

Thanks for the insight!
Do you know how can I overcome this issue?

**Comment by p91paul** [comment]
Your best shot is to get a VPN that works in your public network. There are some using the ports I mentioned (80 and 443). The VPN will get you out of the firewalled network and allow you to connect to any port. At least that's how I managed to escape my dorm's firewall some years ago :smile:. That time my University provided me the VPN, so I have near zero experience with public VPN services.

**Comment by uslss** [comment]
there is no update almost a year.
Ticket is closed.
If you have any further questions feel free to open new ticket
