### ISSUE TITLE
Result on Plain Text | SET not support whitespace 

### ISSUE THREAD

**Issue by nemdaz** [dbeaver/dbeaver#4547]
Two issues:
1. On result (plaint text) not show complete value of date parameter (type: date).
![image](https://user-images.githubusercontent.com/6315069/48027694-777d5500-e117-11e8-8d99-3b015b00580c.png)

2. @set not support whitespace/tab  on init line; show error.
![image](https://user-images.githubusercontent.com/6315069/48028044-6a149a80-e118-11e8-93fb-21d5cae6f8df.png)

**Comment by serge-rider** [comment]
1st one if fixed. 
I can't reproduce 2nd one. Please create a separate ticket and attach sample SQL to reproduce this.
