### ISSUE TITLE
Table or view autocomplete works incorrectly

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [dbeaver/dbeaver#455]
This is happening under oracle.
I noticed that when I need to auto complete a table or view name it shows me different schemas if the table or view exists on more schemas.

Example:

I write `select * from btus` and I want to complete the table name to `btusers`, then I'll be shown `myproduct_dev.btusers` and `myproduct_preprod.btusers` and `myproduct_prod.btusers`

This is annoying because I have to look for my schema among dozens of names, and given that I already choose a schema (the one upon the editor window) it would be great to auto complete names in the schema you selected, i.e. when I write `select * from btus` and then I press ctrl + backspace it will be expanded to `select * from btusers`

Thank you

**Comment by gabriele-ricci-kyklos** [comment]
I also wanted to report something related to this. I'm doing an updated query, let's say again on the table `btusers`. I write `UPDATE btus` and to auto-complete the name the scenario is the same as above. Then, I write `SET usern` and I'm expecting that the field name is auto-competed. Nothing happens indeed. When I arrive at the `WHERE` clause and I start typing a field name, the hints that I see are not fields of the table I'm doing the update on.

**Comment by serge-rider** [comment]
Can't reproduce that.
Autocomplete show tables only from the current schema (if it is set).
Could you post some SQL snippet?

**Comment by gabriele-ricci-kyklos** [comment]
I hadn't upgrated to the new version when I wrote this, both problems seem to be resolved by updating dbeaver.

**Comment by gabriele-ricci-kyklos** [comment]
I'm reporting a similar issue again:
I write 
```SQL
select * from table1
```

Then I change * with some column name, starting to write the name and pressing <kbd>Ctrl</kbd> + <kbd>Space</kbd> to autocomplete; it works fine

Then on a new line I write:
```SQL
select * from table2
```

Then I change * with some column name, and the autocomplete shows me the column name of the `table1`

**Comment by serge-rider** [comment]
@gabriele-ricci-kyklos can't reproduce. 
Do you use statement separator (`;` or empty line) after first query?

**Comment by gabriele-ricci-kyklos** [comment]
I used empty lines.
I tried on sql server with microsoft driver

**Comment by serge-rider** [comment]
In order to make auto-complete work correctly you need to separate queries with delimiter (`;`, `GO` or empty line).

I can't reproduce this problem with separators. If this still happens please check SQL Processing preference page (delimiters configuration)

**Comment by tati-kru** [comment]
Hi @gabriele-ricci-kyklos!
Could you, please, check that it can be reproduced or not on the latest version?

**Comment by gabriele-ricci-kyklos** [comment]
Hi,
I confirm that I can reproduce this bug in version 4.3.2.
I tried on both SQL Server and Oracle, it seems a dbeaver-related issue.
Many thanks

**Comment by gabriele-ricci-kyklos** [comment]
Hi,
just for reporting purposes, the problem still persist in version 4.3.3.1
Many thanks

**Comment by serge-rider** [comment]
This still doesn't work if you don't use delimiters (empty line, not jsut line feed). 
We'll need to make SQL completion smarter for SQL Server t osupports this.

**Comment by uslss** [comment]
Issue isn't reproduced on 6.0.2 (if delimiters are used).
