### ISSUE TITLE
[5.2.4] UI language changes unexpectedly

### ISSUE THREAD

**Issue by MarcoBorchert** [dbeaver/dbeaver#4551]
Installed on Windows choosing language English. 
After changing the theme (between Windows Classic and Light) the UI language is changed to the system default language.

As workaround selecting language by command line parameter "-nl en" works, as does reinstalling.

**Comment by serge-rider** [comment]
Yes, this may happen once - right after DBeaver restart.
Because language is passed in command line parameters (set in Windows shortcut by installer).
But I'm afraid I can't fix this easily as restart function is a part of Eclipse platform.
