### ISSUE TITLE
Passing password to user properties 

### ISSUE THREAD

**Issue by ngorchakova** [dbeaver/dbeaver#4552]
Is there any way to pass password to user properties? 
from the code https://github.com/dbeaver/dbeaver/blob/10dcd8b0b14f6340bd8a46bb3e9750ac83f12382/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/connection/DBPConnectionConfiguration.java#L363 it doesn't look possible (it is allowed to use system variables, but not properties userName, userPassword).

The goal:
implement access to Athena using temporary credentials. 
https://aws.amazon.com/blogs/big-data/connect-to-amazon-athena-with-federated-identities-using-temporary-credentials/ 
For that I implemented AWSCredentialsProviderClass (user property) which is initialized by another user property AWSCredentialsProviderArguments.
AWSCredentialsProviderArguments needs to contain user name and password. As result, the password is stored as plain text.

Would be great to have possibility to use variables ${username} and ${password} in user properties.

**Comment by serge-rider** [comment]
Seems to be very similar to #4552

**Comment by ngorchakova** [comment]
@serge-rider 
this ticket has number 4552 , so it cannot be 'similar' to itself.

**Comment by serge-rider** [comment]
Sorry )
It is #4527

**Comment by ngorchakova** [comment]
thanks for pointing out. 
they have common parts (problem with plain passwords). However the cause is a little bit different. 
1. 4527 is specific to 'Windows Authentication'. 
2. the proposal was to hide all properties with 'password' in name. That can help if there will be possibility to reuse the properties by name in other properties (for example to create LdapPassword and then use ${LdapPassoword})

**Comment by serge-rider** [comment]
Indeed this is a bit more complicated ticket. I think we should be able to reuse any connection parameters (password, user name, etc) in properties.

**Comment by serge-rider** [comment]
Ok, here is the list of supported variables: https://github.com/dbeaver/dbeaver/wiki/Create-Connection#variables-in-parameters

This will work in 5.3.3. 
Don't forget to enable "Use variables in parameters" option:
![image](https://user-images.githubusercontent.com/6398845/51084530-6e72ba80-173c-11e9-9079-5c3d83b47fad.png)
