### ISSUE TITLE
5.2.4 Unalignment on some icons and controls (Minor)

### ISSUE THREAD

**Issue by marco-sanjuan** [dbeaver/dbeaver#4553]
Hi

I noticed some icon and controls missplaces:

Unaligned icon with text:
![image](https://user-images.githubusercontent.com/4165141/48050562-8ceb9100-e1a2-11e8-8a19-4cf58dc03d05.png)

Too near icons for editor:
![image](https://user-images.githubusercontent.com/4165141/48050607-a8ef3280-e1a2-11e8-903e-28bccf947b5d.png)

OS Debian 9 with XFCE

Thanks!

**Comment by serge-rider** [comment]
Could you try to switch to Light or Dark theme?
![image](https://user-images.githubusercontent.com/6398845/48087611-dd99d300-e210-11e8-9f20-20e8ed82be51.png)

**Comment by marco-sanjuan** [comment]
Yes, i tried, and also deactivated themes, but same result. 
Some friends have same issue on Linux

**Comment by serge-rider** [comment]
This control (combo with icons and colored text) is one the most problematic as it looks differently on different OSes. I think we should replace it with something standard (e.g. toolbar item with icon, text and drop-down menu).

**Comment by serge-rider** [comment]
We've changed UI of these selector completely.
Please test it in Early Access version (https://dbeaver.io/files/ea)

**Comment by uslss** [comment]
verified
