### ISSUE TITLE
Defining Database filters gives a SQL error syntax

### ISSUE THREAD

**Issue by ricardobrunosr** [dbeaver/dbeaver#4554]
When in try to configure a database filter, it gices a SQL error.

Error refreshing node

Reason:
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '='database_name'' at line 1

DBeaver 5.2.4
Linux Ubuntu 18.04

**Comment by serge-rider** [comment]
This error happens only if you use filter without a mask `%` or `_`.
I think this is fixed in #4543.

**Comment by serge-rider** [comment]
@ricardobrunosr Thanks! 👍
