### ISSUE TITLE
Establish UI testing framework

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#4555]
We'd wish to use SWT Bot. 
But it is blocked by https://bugs.eclipse.org/bugs/show_bug.cgi?id=164192

**Comment by PatrickTasse** [comment]
See how we got around this in Trace Compass project. It requires code change to the application under test, though.

http://git.eclipse.org/c/tracecompass/org.eclipse.tracecompass.git/tree/tmf/org.eclipse.tracecompass.tmf.ui/src/org/eclipse/tracecompass/tmf/ui/dialog/DirectoryDialogFactory.java

**Comment by serge-rider** [comment]
@PatrickTasse thanks for the link! We'll try this.
