### ISSUE TITLE
Text indentation guides

### ISSUE THREAD

**Issue by cesarmansur** [dbeaver/dbeaver#4558]
Could you please add vertical indentation guides in SQL Editor?

**Comment by serge-rider** [comment]
You could try to install this plugin: https://marketplace.eclipse.org/content/indent-guide
It enables indent guides for all text editors.

**Comment by cesarmansur** [comment]
Thanks, serge-rider. It worked fine!

**Comment by morl-la** [comment]
This plugin doesn't seem to work OK for me - the lines are not aligned with the text (played around with the shift settings but it only made things worse) and it also seems to not align with the zoom level. Would have been nice if this could be natively supported - requesting to reopen.

**Comment by pyrocks** [comment]
This plugin doesn't seem to work OK for me - the lines are not aligned with the text (played around with the shift settings but it only made things worse) and it also seems to not align with the zoom level. Would have been nice if this could be natively supported - requesting to reopen.

**Comment by cesarmansur** [comment]
> @serge-rider This plugin doesn't seem to work OK for me - the lines are not aligned with the text (played around with the shift settings but it only made things worse) and it also seems to not align with the zoom level. Would have been nice if this could be natively supported - requesting to reopen.

@pyrocks,
The plugin works very well here. I've been using it for a long time, since @serge-rider recommended it. Could you please upload some screenshots of your environment?
![image](https://user-images.githubusercontent.com/43681608/51188852-eb7d6b80-18c5-11e9-9f19-6e099e15effc.png)

**Comment by morl-la** [comment]
displayed tab width is 4:
![image](https://user-images.githubusercontent.com/44611568/51201789-b133be80-1905-11e9-999d-6261866f7ae9.png)
changing zoom makes it worse:
![image](https://user-images.githubusercontent.com/44611568/51201905-01128580-1906-11e9-9948-66bad6229936.png)

**Comment by pyrocks** [comment]
displayed tab width is 4:
![image](https://user-images.githubusercontent.com/44611568/51201789-b133be80-1905-11e9-999d-6261866f7ae9.png)
changing zoom makes it worse:
![image](https://user-images.githubusercontent.com/44611568/51201905-01128580-1906-11e9-9948-66bad6229936.png)

**Comment by cesarmansur** [comment]
@pyrocks, I can't reproduce it here. I changed the zoom level and everything kept fine.

![image](https://user-images.githubusercontent.com/43681608/51202550-1ecff280-18e6-11e9-8f64-5f118b80fd3a.png)

**Comment by pyrocks** [comment]
I have the same menu for indent guide, with the same settings (except maybe "Draw guide on column 1" but disabling it makes no difference) - yet it still doesn't show properly.

**Comment by cesarmansur** [comment]
![image](https://user-images.githubusercontent.com/43681608/51202964-14fabf00-18e7-11e9-9917-8730c8cb8e8e.png)

**Comment by pyrocks** [comment]
OK - we're making progress. So - this plugin **does not** work correctly in the sense that it is not honoring the tab size.
I will not change my tab size for the sake of indent guides... so as this might be a workaround - I still think this needs a better solution.

**Comment by pyrocks** [comment]
Insert spaces for tabs is enabled. My request to reopen stands.
Thanks for your time though :)

**Comment by cesarmansur** [comment]
Did you change the font type or size on the editor?

**Comment by cesarmansur** [comment]
I cant reproduce your problem here, even by changing the value for the displayed tab size...

**Comment by pyrocks** [comment]
not that I can remember - but you yourself said:
> @pyrocks, I've just figured it out! I'm using "Displayed tab width" = 3. **The indent guide seems to work correctly only with this value**.

**Comment by pyrocks** [comment]
did you reopen the editor after this change?

**Comment by cesarmansur** [comment]
The only situation 

> not that I can remember - but you yourself said:
> 
> > @pyrocks, I've just figured it out! I'm using "Displayed tab width" = 3. **The indent guide seems to work correctly only with this value**.

I made a mistake trying to reproduce your scenario and I deleted this message.

**Comment by cesarmansur** [comment]
Try to input the text after setting the displayed tab width to any value. If you change this value after the text is written, it will give you a perception of malfunction.

**Comment by cesarmansur** [comment]
Step 1) Set the Displayed tab size to 4:

![image](https://user-images.githubusercontent.com/43681608/51203873-512f1f00-18e9-11e9-89d2-438d478f8448.png)


Step 2) Write some text with indentation levels:

![image](https://user-images.githubusercontent.com/43681608/51203963-9c493200-18e9-11e9-9d5d-ab945ea081a6.png)


Step 3) Everything is fine. Now, change the Displayed tab size to any other value. You will see it will become not aligned:
![image](https://user-images.githubusercontent.com/43681608/51204083-e205fa80-18e9-11e9-8cc7-209ad2e9a232.png)

**Comment by pyrocks** [comment]
I did not test - but the plugin is obviously not aligned with DBeaver settings - regardless of the actual cause. What if I do want to use "replace tab with space" (assuming that's the cause)? I can't have indent guides then?
My request to reopen **still** stands.
