### ISSUE TITLE
No link to database object from synonym properties (Oracle)

### ISSUE THREAD

**Issue by burlap** [dbeaver/dbeaver#4562]
DBeaver 5.2.3 and 5.2.4, macOs Mojave

Before 5.2.3, it was possible to access Oracle DB objects from the synonym properties - object name was a link to the object. 

In 5.2.3/4, synonym properties consist of text fields, there is no link. Moreover, clicking on the object name changes it to the synonym name.

**Comment by serge-rider** [comment]
Yep, it is a bug in Oracle extension. Object should be a link.
Thanks for the bug report.

Workaround: open synonym list in the editor (edit schema->Synonyms) - link is rendered there.
