### ISSUE TITLE
Autocomplete doesn't show columns of a table in first shot

### ISSUE THREAD

**Issue by Bullnados** [dbeaver/dbeaver#4564]
if u type the following 
SELECT actor. than the Popup doesnt show columns
Autocomplete dosn't show columns in first shot
![grafik](https://user-images.githubusercontent.com/11041576/48100192-813faf00-e222-11e8-9d16-f6ce065b3715.png)
If u remove . after typed it and wrote again a fullstop, than columns are shown
![grafik](https://user-images.githubusercontent.com/11041576/48100241-b0eeb700-e222-11e8-820a-557474a051c3.png)

**Comment by serge-rider** [comment]
This is already fixed in recent SQL completion improvements. 
Now you also can use aliases and DBeaver will show column lists after a dot char.

Thanks for the report anyway
