### ISSUE TITLE
JRE fatal error

### ISSUE THREAD

**Issue by whdxwym** [dbeaver/dbeaver#4566]
I cannot start DBeaver, and the DBeaver-cli give the following error:
A fatal error has been detected by the Java Runtime Environment:
 EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffbf6d6a780, pid=8688, tid=10212
JRE version: Java(TM) SE Runtime Environment (8.0_77-b03) (build 1.8.0_77-b03)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.77-b03 mixed mode windows-amd64 compressed oops)
Problematic frame:
C  [swt-win32-4919.dll+0x5a780]

detail log is :
[hs_err_pid8688.log](https://github.com/dbeaver/dbeaver/files/2556220/hs_err_pid8688.log)

**Comment by serge-rider** [comment]
Can't reproduce.

What Windows version do you have?

**Comment by arilekt** [comment]
I found this error too.
[hs_err_pid6756.log](https://github.com/dbeaver/dbeaver/files/2557023/hs_err_pid6756.log)

**Comment by whdxwym** [comment]
> Can't reproduce.
> 
> What Windows version do you have?
10.0.18272.1000

the bottom of the log show my system info.

**Comment by clucksted** [comment]
I am seeing the same, and dbeaver will not start... Have uninstalled and reinstalled clean, same result.  Log snip below.  Running Windows 10 x64, 18272.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff1ef6a780, pid=11580, tid=6972
#
# JRE version: Java(TM) SE Runtime Environment (8.0_77-b03) (build 1.8.0_77-b03)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.77-b03 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [swt-win32-4919.dll+0x5a780]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by clucksted** [comment]
> I am seeing the same, and dbeaver will not start... Have uninstalled and reinstalled clean, same result. Log snip below. Running Windows 10 x64, 18282.
> 
> ```
> #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff1ef6a780, pid=11580, tid=6972
> #
> # JRE version: Java(TM) SE Runtime Environment (8.0_77-b03) (build 1.8.0_77-b03)
> # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.77-b03 mixed mode windows-amd64 compressed oops)
> # Problematic frame:
> # C  [swt-win32-4919.dll+0x5a780]
> #
> # Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
> #
> # If you would like to submit a bug report, please visit:
> #   http://bugreport.java.com/bugreport/crash.jsp
> # The crash happened outside the Java Virtual Machine in native code.
> # See problematic frame for where to report the bug.
> #
> ```

**NOTE:** I installed the 32 bit version, and that RUNS.  It is ONLY the x64 version that shows the above error.

**Comment by tchibatron** [comment]
Looks like a [bug](https://bugs.openjdk.java.net/browse/JDK-8213132) with swt-win32-4919.dll library.   As a suggestion, updating to [new version](https://github.com/eclipse/eclipse.platform.swt.binaries/tree/master/bundles/org.eclipse.swt.win32.win32.x86_64) of this library might help.

**Comment by uslss** [comment]
Not DBeaver issue.
