### ISSUE TITLE
DB2/400 Table Descriptions and Column Descriptions Not Visible On New Server

### ISSUE THREAD

**Issue by spinjector** [dbeaver/dbeaver#4568]
Over the past week, we've migrated a DB2/400 database from a private server with v6r1 to a cloud-based server/service with v7r3. I also updated my DBeaver from 5.1.5 to 5.2.4, running on Windows 7x64.

With the new server, the table descriptions and column descriptions are not visible. I still have the connection to the now-idle original server, and the descriptions are all still visible, so it seems the issue is not the DBeaver version. 

Both servers are ODBC, and as much as I can determine, all connection attributes are the same, and all users still have the same credentials, etc. When I set up the new connection in DBeaver, I first copied the old connection but just changed the IP address. This worked for the data, but not the descriptions. So I created a completely new connection with default settings, and again it worked for the data but not the descriptions.

Can these fields be re-mapped in DBeaver so it gets the tables descriptions and column descriptions correctly..? The DB2/400 fields in question are named 'TABLE_TEXT' and 'COLUMN_TEXT', respectively.

For reference, here's the DB2/400 SQL for the table descriptions:
```
SELECT    TABLE_SCHEMA,
          TABLE_NAME,
          TABLE_TEXT
FROM      QSYS2.SYSTABLES
WHERE     TABLE_SCHEMA='XXXXXXXX'
```
And for the column descriptions:
```
SELECT    TABLE_NAME,
          COLUMN_NAME,
          COLUMN_TEXT
FROM      QSYS2.SYSCOLUMNS
WHERE     TABLE_SCHEMA='XXXXXXXX'
```

**Comment by spinjector** [comment]
That makes sense. Unfortunately, this is a hosted service from our bookkeeping system provider. We share one of many SQL servers with many of their other customers, where we each get our own schema, so I'm not optimistic they would consider changing server options. But...it doesn't hurt to ask. 

Do you have an idea what DB2 server options it might be, or have suggestions where to look?

Does DBeaver have debug data we could look at to see where the problem is?

Is there anything to be done in DBeaver? As mentioned in my OP, I wondered if there's a way to re-map the the fields used by the DB explorer.

**Comment by spinjector** [comment]
> I believe this is somehow controlled by some server-side options (at least this is true for other DB2s, IBM loves options).
> Anyhow, if it worked on other server it should owrk on a new one without changes on DBeaver side, I believe..

@serge-rider you seem to be correct in your suggestion. It does seem to be a server issue.

I spent a large portion of time yesterday working on this. I uninstalled & wiped my installation of DBeaver and installed from zero. Then I installed Squirrel SQL with the JTOpen drivers for DB2/400 (with great frustration, DBeaver is sooooo much nicer lol..!!).

So...now we have two different SQL clients and two different sets of JDBC drivers, and...the result is the same...one server has the column description text, the other does not. So now I turn around and stare at the offending server with furrowed eyebrows.

If I'm able to resolve the issue with the vendor/manager/DBA of our hosted service, I'll report back here with the settings so others might benefit.

**Comment by spinjector** [comment]
I posted this question in the IBM forums, and received the answer I needed:
[https://www.ibm.com/developerworks/community/forums/html/topic?id=155ea0a8-a596-4439-ba00-0706900d7bb7](url)

The solution is to set the JDBC driver property as follows: 

`metadata source = 0`

With this change, the other properties seem to not be necessary. After setting the `metadata source` property, I made test-changes to the other two, but I didn't see any obvious difference:

`remarks = true`
`extended metadata = true`

**Comment by tlue** [comment]
Setting the 
`extended metadata = true`
is giving long names for the columns :-)
