### ISSUE TITLE
[5.2.4] sql completion issues

### ISSUE THREAD

**Issue by alonpr** [dbeaver/dbeaver#4570]
Hi,

When connected to Oracle database, DBeaver 5.2.4 on mac; the sql completion has the following issues:

1. An underscore character (_) acts like a pattern matching for single character.

2. Stored procedures are shown in the FROM section.

3. "Search inside name" applying a pattern matching search, for example, typing "dba" will list results as SCHE**D**ULER_JO**B**_**A**RGS instead of listing only results as [any-string]dba[any-string].

4. "Use global search" doesn't show data dictionary and V$ views.

**Comment by serge-rider** [comment]
All 4 have to be fixed by now.

Note: V$ won't be auto-completed on typing (because of $ character). You need to press CTRL+Space to see proposals.
