### ISSUE TITLE
[question] using external editor for cells in grid

### ISSUE THREAD

**Issue by alonpr** [dbeaver/dbeaver#4572]
Hi,

Is it possible to have an external editor to show the contents of a cell in the data grid when it's double-clicked?

**Comment by serge-rider** [comment]
You can open a value in dialog (<jbd>Shift+Enter</kbd>) and then click on "Open Editor" button.
But this will open DBeaver text editor (or image or binary editor - depending on cell type) but not an external editor.
Also you can save CLOB/BLOB values to an external fil and then op[en it in external editor.

**Comment by alonpr** [comment]
cool. thanks.
