### ISSUE TITLE
Disappearing comments in stored procedures

### ISSUE THREAD

**Issue by Speirs47** [dbeaver/dbeaver#4576]
I noticed that when I edit stored procedure (in MariaDB) all comments (begining with **#**) would disappear. 

For me it's a bug.

**Comment by serge-rider** [comment]
I can't reproduce that. Comments inside procedure declaration (between BEGIN and END) are saved and loaded fine.
You can't use comments before CREATE operator and after last END (it is server-side limitation).

**Comment by Speirs47** [comment]
Well, I can't reproduce that anymore too. I think it can be closed
