### ISSUE TITLE
[question] How to disable script save dialog?

### ISSUE THREAD

**Issue by TomaszKane** [dbeaver/dbeaver#4577]
Hi, how to disable script save dialog: https://imgur.com/a/Lr0Pytv ?
It's always ask me that - I don't want to click "Don't save" all the time...

I try to find it in Global Properites by "console", "save", "dialog" without success.

DBeaver 5.2.4.

**Comment by serge-rider** [comment]
It is not possible in current version. And for me this sounds like a quite strange feature ("never ever save scripts"?)
After all all you need is one click or just press <kbd>Enter</kbd>, shouldn't be very annoying.

**Comment by TomaszKane** [comment]
I thought so too, but the practice has shown that if I have ~ 10 tabs open (only to look at the records from the tables - simple SELECT, which I do not want to remember/save), and I must click ten times it gets annoying.
Maybe good idea is to NOT show save dialog when user click on tab using mouse scroll-button / third mouse key? Just like it works on any web browser.

**Comment by serge-rider** [comment]
Well, if you just need to see table you can use "Edit data" command (which do not create a script at all).
And you can configure double-click so it will open table data instead of expand/collapse.

**Comment by TomaszKane** [comment]
Thanks, I'll try your advice.

**Comment by chrisd1977** [comment]
I find this dialog very irritative. I only write throw away queries and don't want to save them ever.

**Comment by zhostasa** [comment]
This dialog is beyond irritating, I would very much wish to be able to turn it off.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/62203297-2a1ed300-b38b-11e9-958e-8cba0ea88fc4.png)

If you use SQL editor as a scrapbook (as I do) then you can just use some special script for that. I usually open SQL editor by ctrl+enter (open recent), edit/run a few queries and then close it.
Even if you don't need these queries it won't make any harm to save them.

**Comment by fmdelvalle** [comment]
Please implement it, I haven't stored a query in my life, and just browsing a table data means fighting with this annoying dialog. WIth this, Dbeaver would be just perfect app.

**Comment by tomaszkane** [comment]
Perfect DBeaver will also have #8033 :-)

**Comment by synchro--** [comment]
Please, we're desperate about this, so frustrating. 
I think I may abandon dbeaver.

**Comment by kseniiaguzeeva** [comment]
@synchro-- Please describe the feature. Is it just disabling the additional question about saving SQL Script? Or your case is closing of several tabs?

**Comment by synchro--** [comment]
> @synchro-- Please describe the feature. Is it just disabling the additional question about saving SQL Script? Or your case is closing of several tabs?

Is the feature described in the issue. Just disabling the prompt about saving the scripts, which also happens when you're closing several tabs.

**Comment by kseniiaguzeeva** [comment]
Autosave of SQL Editor Scripts is going to be implemented. It should cover your needs.

**Comment by synchro--** [comment]
Well, that was quick (at least for me, not the user who posted this originally) :D 

Just to be clear, i would like the following behaviour (always talking about scripts): 

- When closing DBeaver, you may prompt for the question but leave also a "never ask again" or autosave feature. 
- Same for when you click 'close all tabs' or 'close others' or 'close tabs to the r/l'

**Comment by eshkinkot** [comment]
I don't use dbeaver as a file editor, so its question about putting something in a file seems very strange to me.

AutoSave also doesn't help much as it just floods old files into directories like ~.local/share/DBeaverData/workspace6/General/Scripts/ that I never use and also show some not-so-expected old queries when I press C-RET

**Comment by OverDrone** [comment]
Why this issue closed? I totally agree with previous comment that "autosave on close" doesn't solve the issue, it just changes described issue to another issue (flooding of useless temporary files). You must have mode when new editor window is not saved anywhere until you specifically tell to do so and if closed just disappears without saving anything. At least you must have checkbox for switching to such behavior.

**Comment by kseniiaguzeeva** [comment]
Now the only way to open an SQL console that won't be saved is through the button on the bottom toolbar of a table DDL tab. 
![Screenshot 2020-11-16 at 17 13 40](https://user-images.githubusercontent.com/51405061/99262996-ad3d9400-282f-11eb-9bf0-2dffc4713867.png)

We can add an extra button to the main top toolbar to open such type of SQL console.
Will this cover your needs?

**Comment by OverDrone** [comment]
Can you give more details? How can I open sql console now? I don't see any button, menu item or hotkey for it. We need same functionality as sql editor, at least: execute statement, execute whole file, explain plan

**Comment by OverDrone** [comment]
Also I personally don't understand why I need to save my sql editor files when I close some DB connection. What's the relation? What you're trying to remind me? that I loose something? I can loose changes only when I close dbeaver application - then you should ask what to do with unsaved files. Why you ask on connection close which happens quite often during work: switch from one server to another for example.
And there is no any option to stop saving, the only thing you can do is automatically save on close, there is no option "do nothing with sql editor windows on connection close".

**Comment by vstoianov** [comment]
Hi guys,
After 3 years of active use, I am abandoning this project due to the reluctance of the developers to remove this extremely stupid dialog box, asking on close to save the script. Now I am happy to use Valentina Studio - https://https://www.valentina-db.com/. No annoying dialog boxes anymore!

**Comment by kseniiaguzeeva** [comment]
@OverDrone @vstoianov Please try to open SQL console. Now it is available via table DDL tab in Object Editor. 
![image](https://user-images.githubusercontent.com/51405061/99546059-173c7180-29c7-11eb-8735-4c835f9a3869.png)
SQL console button:
![Screenshot 2020-11-18 at 17 52 03](https://user-images.githubusercontent.com/51405061/99546026-0d1a7300-29c7-11eb-8207-bac23e0d6b96.png)

We can place it on the upper toolbar of the application. Please note, SQL console cannot be saved as a script (other functions are like SQL Editor has). How do you find this option?

**Comment by fmdelvalle** [comment]
> Hi guys,
> After 3 years of active use, I am abandoning this project due to the reluctance of the developers to remove this extremely stupid dialog box, asking on close to save the script. Now I am happy to use Valentina Studio - https://https://www.valentina-db.com/. No annoying dialog boxes anymore!

This is blatant publicity of a paid product, and the https link does not work :D

**Comment by zhostasa** [comment]
DBeaver might have some issues, but it also has incredibly competitive pricing.
Concerning this feature - if anyone were to submit pull request implementing it, is it likely to be accepted? Or is it a hard no on this one?

**Comment by vstoianov** [comment]
fmdelvalle I'm not advertising a paid product, I'm pointing to one that doesn't have the annoying disadvantages of dbeaver. DBeaver team refuses to fix this s*it for more than 5 years, and I did not hear reasonable explanation what is the reason to keep this as well as everybody wants this 'Save Resources' dialog to be configurable - enable/disable? When a team/company stop listening the customers, then the customers stop using the software. It is so simple.

**Comment by p91paul** [comment]
@vstoianov and some of the others did you try listening to the company? I think the option offered in the latest post by @kseniiaguzeeva (sql console) is what you asked for, an editor without the option to save it. If you try giving your feedback to that, the next step might be to make that option more prominent.

I'm just a happy user, but I still find your rants a bit over the edge considering how much dbeaver developers actually listen to their users, I've never seen a product growing features so quickly, mostly by user requests.

**Comment by kseniiaguzeeva** [comment]
SQL console button is going to be implemented in 7.3.4 release https://github.com/dbeaver/dbeaver/issues/10495

**Comment by vstoianov** [comment]
@p91paul Yes this sql console is a moving in the right direction. And Yes I keep thinking that the DBeaver team do not listen the customers.

**Comment by jaredMericka** [comment]
Why is this closed when it hasn't been fixed? Being unable to easily close tabs in bulk is such a disruption. The console does not solve this.

**Comment by leefernandes** [comment]
Maybe Open Console should be the default mode of writing queries.  I'm also not a fan of the save scripts functionality, especially as it does not provide a means to ignore the save-prompt on close without opting into an auto-save config.  

I'm suggesting the most standard expectation and perhaps best UX is for default functionality to be the ephemeral Open SQL Console command, with additional steps required for users who would want to opt into using a saved scripts workflow.

But the [default command assignment option below](https://github.com/dbeaver/dbeaver/issues/4577#issuecomment-824831384) is good enough for me, big thanks to the team for the config option, it was just a bit of friction finding/getting to it, enough such that a number of users are going to github issues to search and comment on this.

**Comment by uslss** [comment]
@leefernandes in the recent version you could switch the default command to SQL console, so it will open by clicking at SQL button in the toolbar.
![image](https://user-images.githubusercontent.com/31996417/115720172-75f68480-a385-11eb-9d77-317b9e274597.png)
Also, you could assign needed binding for Open SQL console action in Preferences - User Interface  - Keys
![image](https://user-images.githubusercontent.com/31996417/115720571-dc7ba280-a385-11eb-8f99-f31b9f6279cc.png)

**Comment by leefernandes** [comment]
@uslss   Much appreciated this is great, you are my hero of this day!  ❤️

**Comment by Andrew0002** [comment]
When working on something that will affect multiple clients, I often need to disconnect from one client's system and connect to another. When I do this, I need to disconnect one client's VPN and connect to another client's VPN. Generally, before I disconnect the VPN, I disconnect from the current database in dbeaver while keeping several SQL Editors open.

![dbeaver_save_prompt](https://user-images.githubusercontent.com/1099466/145662371-c77ee4d2-2dd9-4136-9b89-c684b51866b4.jpeg)

The current behavior is that when I attempt to disconnect, I get a prompt that says "Save Editor Changes / 'file_name.sql' was changed. Do you want to save these changes?". Since I am still actively working on the files, I don't want to save the changes yet. I can click "No" for each editor, but for me personally the dialog seems unnecessary if all I'm doing is disconnecting (As opposed to closing dbeaver). 

It would be nice if there was a setting to disable the prompt: for example "[X] Prompt to save changes on database disconnect". If this was going to be added, I think it might make sense to have it under "Preferences" > "Editors" > "SQL Editors" under the "Connections" heading.

I'm aware of the SQL Console functionality, but I don't think that fits my use case since these are files that I do want to save when I'm done editing them.

**Comment by arthurcaccavo** [comment]
How can I make console unsavable?

I have the urge to press ctrl+s ever now and then but when I open a console tab I explicitly don't want it to be saved even more automatically become a script when I opened it as a console...

**Comment by E1izabeth** [comment]
@Andrew0002 @only-su 
This issue is closed. You can create a new one.
