### ISSUE TITLE
Keybinds are triggered incorrectly

### ISSUE THREAD

**Issue by BookLaugh** [dbeaver/dbeaver#4579]
This is related to issue #3789 . I have similar problem - I'm using right Alt (Alt Gr) for national symbols on my keyboard layout. 

What I'm observing is that when I type 'AltGr + S', which translates to 'Ctrl+Alt+S', keybinding for 'Ctrl+S' is triggered in most cases (not each time though). It shouldn't be the case. "Ctrl+S" should be triggered **only** when neither Shift nor Alt is pressed. The same should apply to other keyboard shortcuts - they shouldn't be triggered when extra (not included in keybinding) modifier keys are pressed. I tried copying the offending symbol to clipboard and use 'Ctrl+V' instead but it's even less convenient than it sounds.

I should probably add that the behavior described above can be observed on Data tab of a table when user adds new row to a table displayed as a grid (not in Record mode).

**Comment by serge-rider** [comment]
Generally it have to work exactly as you describing. And it works in most cases.
In fact we have just two shortcuts with CTRL+ALT ekys involved: CTRL+ALT+S and CTRL+ALT+R ()they are used when you editing resultsets and basically do the same as regular Save and Reject commands but only for resulset).
I'll fix this, we'll use standard CTRL+S and CTRL+R instead.
Thanks for reminding.

**Comment by BookLaugh** [comment]
Ah, missed those two. Thank you very much for prompt reaction and explaining it.
