### ISSUE TITLE
Auto indentation behavior

### ISSUE THREAD

**Issue by cesarmansur** [dbeaver/dbeaver#4580]
Hello, DBeaver team!
I'd like to ask for some adjust in the automatic indentation behavior in SQL Editor.

When I write SQL code with some indentation, by pressing Enter, the new line automatically adds the same indentation as the previous row. That's nice.
![image](https://user-images.githubusercontent.com/43681608/48199228-aa576100-e342-11e8-92ff-7dcf6b1d9163.png)

However, If I remove all the indentation of the new line and press Enter again, the new empty lines will be indented according to the indentation of the last not empty line. I'd like this behavior to be changed... I mean, when I remove the indentation of an empty line and press enter, I'd like the next line to be no indented.
![image](https://user-images.githubusercontent.com/43681608/48199176-77ad6880-e342-11e8-8091-2444974317bc.png)

**Comment by serge-rider** [comment]
This is a questionable ticket. 
Most of text editors (inluding Eclipse, notepad++, Intellij) keep last indentation even if you have empty lines after it.Maybe this should be configurable though..

**Comment by cesarmansur** [comment]
Configurable is an excellent proposal, my friend. Thank you again!

**Comment by devezencuando** [comment]
> 
> 
> This is a questionable ticket.
> Most of text editors (inluding Eclipse, notepad++, Intellij) keep last indentation even if you have empty lines after it.Maybe this should be configurable though..

Hello. I recently started using DBeaver (after having tried many others) and I think it is a great tool. powerfull and configurable. Thanks a lot!!

I would also like this behaviour to be configurable.

As far as I can see, this is the default behaviour after empty lines in Notpad++ v7.6.6.

**Comment by taf1-cornell-edu** [comment]
I'd also love to see this feature.  Thank you!

**Comment by ssimhahri** [comment]
Please reopen
