### ISSUE TITLE
DBeaver changes active database after running stored procedure (MariaDB)

### ISSUE THREAD

**Issue by queueseven** [dbeaver/dbeaver#4581]
I'm connected to a server with a lot of databases.
I select one database (something_something_develop) in the database navigator with Databases -> set as active object (or something like that, I don't know, I use German: Aktives Objekt festlegen).

I call a stored procedure and select an out variable, something like this:

```
CALL sp_my_awesome_procedure(foo, bar, outvalue);
SELECT @outvalue;
```

After displaying the results, DBeaver changes the selected database without my interaction. I can see that the highlighted database in the database navigator changes.

Here's a screenshot of the query manager:

![grafik](https://user-images.githubusercontent.com/3126597/48206175-13080300-e36e-11e8-9e15-06ff90d66280.png)

**Comment by serge-rider** [comment]
This is made on purpose.
You have option "Refresh active schema after SQL execution" turned on. In that case DBeaver checks whether active schema was changed after every SQL query you execute. IF shcema was changed then DBeaver also changes default schema for other opened connections (that's why you see two `use xxx` queries in the log.

You can disable this option:
![image](https://user-images.githubusercontent.com/6398845/48227163-a2cfa080-e3b2-11e8-9e17-3f1e713768e1.png)

**Comment by queueseven** [comment]
Thanks for the response, but I don't have this option enabled:

![grafik](https://user-images.githubusercontent.com/3126597/48250352-5447f380-e3fe-11e8-90ac-a0839573dd91.png)

Also, my procedure does not change the schema. Even if it would change the schema and even if I would have this option enabled, why should the selected database be changed?

As a workaround I just filtered the list of databases for this connection.

**Comment by serge-rider** [comment]
Well, this shouldn't happen if this option is turned off (and it is turned off by default).
Then I can't reproduce this issue.
Could you try to create new connection with the same database and try it one more time (just to exclude possibility that this option is still somehow enable). 

Also you could try to enable datasource-specific option (checkbox on the top).

**Comment by queueseven** [comment]
I tried with a new connection, and I tried enabling/disabling this option multiple times in the connection settings and in the global settings. It still happens (DBeaver 5.2.5).

I also think this is a critical bug since you can never be sure if the SQL you run inside a non-trivial script is executed on the very database you selected, or on another one.

Here's how I can replicate this with a minimal example:

- Start DBeaver.
- Select a database (FOO).
- Run the following SQL:

```
DELIMITER //
CREATE PROCEDURE tmpproc()
  BEGIN
	
  END//
DELIMITER ;
CALL tmpproc();
DROP PROCEDURE tmpproc;
```
- Everything is fine
- Change the database (BAR)
- Run the SQL again
- The script will fail: the  procedure will be created on BAR, but between the `CREATE `and `CALL `DBeaver will change the active database to FOO again and try to call `FOO.tmpproc` instead of `BAR.tmpproc`

**Comment by queueseven** [comment]
Actually, you can't even be sure that the database you selected is the one DBeaver uses when you run a script. DBeaver changes it without telling you. 

Look at this screenshot. I did the above and now when I try to run `CALL tmpproc()` DBeaver tries to run it on FOO, but tells me BAR is the active database:

![grafik](https://user-images.githubusercontent.com/3126597/49636952-59e82780-fa04-11e8-877e-85157eb73b53.png)

**Comment by uslss** [comment]
Hi @queueseven is issue still actual for you?

**Comment by queueseven** [comment]
Can't reproduce this anymore with 6.2.1, so this issue is fixed.
