### ISSUE TITLE
[Question] have an error while taking the key ed25519 

### ISSUE THREAD

**Issue by nasatome** [dbeaver/dbeaver#4585]
![2018-11-08_13-54](https://user-images.githubusercontent.com/18271791/48230730-a55dd600-e371-11e8-88da-2c8310bec171.png)
![2018-11-08_13-58](https://user-images.githubusercontent.com/18271791/48230735-a7279980-e371-11e8-9b43-67268d93ab49.png)
![2018-11-08_14-00](https://user-images.githubusercontent.com/18271791/48230736-a8f15d00-e371-11e8-933e-17283a871886.png)

I have a problem trying to use an ed25519 key, with RSA I do not have any problem, it is assumed that this problem was fixed in version 0.26
https://github.com/hierynomus/sshj/commit/db48ff85c05d2d85018e32e3631d0a3161d05b82

Note this issue but mark it as closed:
https://github.com/dbeaver/dbeaver/issues/4013

**Comment by serge-rider** [comment]
You need to use SSHJ implementation (I see that you are using JSch).
See https://github.com/dbeaver/dbeaver/wiki/Optional-extensions

**Comment by uslss** [comment]
there is no update almost a year.
Ticket is closed.
if you have any further question feel free to open new ticket.

**Comment by stilliard** [comment]
The SSHJ extension @serge-rider recommended worked great thanks!
