### ISSUE TITLE
Automatically run 4 queries every time while typing column name in Presto

### ISSUE THREAD

**Issue by archongum** [dbeaver/dbeaver#4586]
# env
- presto 0.210
- dbeaver 5.2.4 installer

# issue
Every time I typing column in `select` clause, it'll automatically run 4 query which took few second to show up the inspection.

![snipaste_2018-11-09_09-59-57](https://user-images.githubusercontent.com/20929338/48238592-7f364580-e406-11e8-9f9f-e98b126a4d21.png)

![snipaste_2018-11-09_09-56-17](https://user-images.githubusercontent.com/20929338/48238568-6f1e6600-e406-11e8-818b-17e6bff3ef4d.png)

# so
How could I fit it?

**Comment by serge-rider** [comment]
I can't reproduce this however SQL editor indeed makes queries in database for auto-completion (in background).
You can disable this on SQL Completion pref page:
![image](https://user-images.githubusercontent.com/6398845/48284715-43849580-e471-11e8-8e28-4662d15d670d.png)
