### ISSUE TITLE
Escape chcharacter not included when query table structure by selecting from `system.jdbc.columns` in Presto

### ISSUE THREAD

**Issue by archongum** [dbeaver/dbeaver#4587]
> According to [presto issue 11879](https://github.com/prestodb/presto/issues/11879)

# true sql, very slow
```sql
SELECT TABLE_CAT, TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, DATA_TYPE,
  TYPE_NAME, COLUMN_SIZE, BUFFER_LENGTH, DECIMAL_DIGITS, NUM_PREC_RADIX,
  NULLABLE, REMARKS, COLUMN_DEF, SQL_DATA_TYPE, SQL_DATETIME_SUB,
  CHAR_OCTET_LENGTH, ORDINAL_POSITION, IS_NULLABLE,
  SCOPE_CATALOG, SCOPE_SCHEMA, SCOPE_TABLE,
  SOURCE_DATA_TYPE, IS_AUTOINCREMENT, IS_GENERATEDCOLUMN
FROM system.jdbc.columns
WHERE TABLE_CAT = 'platform_data' AND TABLE_SCHEM LIKE 'platform_data' ESCAPE '\' AND TABLE_NAME LIKE 't_sales_bill' ESCAPE '\' AND COLUMN_NAME LIKE '%' ESCAPE '\'
ORDER BY TABLE_CAT, TABLE_SCHEM, TABLE_NAME, ORDINAL_POSITION
```

# 'right sql'
```sql
SELECT TABLE_CAT, TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, DATA_TYPE,
  TYPE_NAME, COLUMN_SIZE, BUFFER_LENGTH, DECIMAL_DIGITS, NUM_PREC_RADIX,
  NULLABLE, REMARKS, COLUMN_DEF, SQL_DATA_TYPE, SQL_DATETIME_SUB,
  CHAR_OCTET_LENGTH, ORDINAL_POSITION, IS_NULLABLE,
  SCOPE_CATALOG, SCOPE_SCHEMA, SCOPE_TABLE,
  SOURCE_DATA_TYPE, IS_AUTOINCREMENT, IS_GENERATEDCOLUMN
FROM system.jdbc.columns
WHERE TABLE_CAT = 'platform_data' AND TABLE_SCHEM LIKE 'platform\_data' ESCAPE '\' AND TABLE_NAME LIKE 't\_sales\_bill' ESCAPE '\' AND COLUMN_NAME LIKE '%' ESCAPE '\'
ORDER BY TABLE_CAT, TABLE_SCHEM, TABLE_NAME, ORDINAL_POSITION
```

# so
In which part this sql has been created, presto-jdbc or dbeaver? How could we fit it?

**Comment by electrum** [comment]
The above SQL is generated by the JDBC `java.sql.DatabaseMetaData#getColumns` call.

**Comment by serge-rider** [comment]
The query is generated by Presto JDBC but the note in https://github.com/prestodb/presto/issues/11879 is correct. We should escape table identifiers when reading metadata thru DatabaseMetaData interface.
Of course if driver supports this (like Presto).

It is possible that some drivers do not support this feature or do not provide correct info about it (this happens quite often with some inhouse database drivers). In this case this fix will break tables info reading (if table name contains _ or % symbols). But I think we should take this risk.

Thanks for the bug report.
