### ISSUE TITLE
Blank Popup will shown with ssh tunnel

### ISSUE THREAD

**Issue by ramrasi** [dbeaver/dbeaver#4588]
If i connect server with ssh Tunnel one blank popup.

![image](https://user-images.githubusercontent.com/6615196/48262401-68b0de00-e448-11e8-8910-515d96f6374d.png)

**Comment by serge-rider** [comment]
Can't reproduce. What is your OS/windows manager?
What happens if you close this popup?

**Comment by ramrasi** [comment]
I am Using Fedora 28 x64 / Mate Desktop

**Comment by wzygadlo** [comment]
I have got the same problem on ArchLinux DBVersion 5.2.4

![archlinux 2018-11-21 15-48-57](https://user-images.githubusercontent.com/26280326/48873859-12775f80-eda5-11e8-9d6b-a552d56169cb.png)

**Comment by uslss** [comment]
cannot reproduce on 6.0.2 (ubuntu 18.04)
