### ISSUE TITLE
SQL Server - Generate SQL -> DDL generate incorrect SQL 

### ISSUE THREAD

**Issue by antoniogarcia78** [dbeaver/dbeaver#4589]
Dbeaver 5.2.3
SQL Server  2005
Driver jTDS 1.3.1

Issue:
When use "Generate SQL -> DDL" in a table with a datetime the SQL generated is incorrect

Example:
-- Drop table
-- DROP TABLE SSII.dbo.xxx
CREATE TABLE SSII.dbo.xxx (
	id int NOT NULL IDENTITY(1,1),
	updated_date datetime(3),
	CONSTRAINT PK__xxxx PRIMARY KEY (id)
) go;

Bug:
The datetime data type not have params

Valid SQL is:
updated_date datetime,

**Comment by serge-rider** [comment]
Fixed, thanks for the bug report.
The fix will be a part of bug update in 5.2.5 (see #810)
