### ISSUE TITLE
Extremly high memory usage ~600MB

### ISSUE THREAD

**Issue by T3rm1** [dbeaver/dbeaver#4590]
A single instance and a single connection to a database results in 600MB of memory being used. There is something seriously wrong here. It should rather be around 30 to 50MB.

**Comment by infectormp** [comment]
I think this is normal for JAVA apps.

**Comment by serge-rider** [comment]
Generally 100mb is enough for simple operations with single database (if you won't fetch millions of rows into memory in resutls viewer).
However default maximum memory size available for DBeaver is 1Gb. And big part of this memory will be used even if there is no real need in it (as @infectormp said it is normal for Java apps).
If memory is critical resource for you you can reduce maximum amount of memory available for DBeaver to some smaller values.

Change parameter `-Xmx1024m` to `-Xmx150m` in dbeaver.ini file to set maximum memory size to 150mb.

In any case 600mb is definitely not an "extremely high" value in the modern world. 
My Chrome browser eats 1.5-2Gb of memory just to show a few pages on Facebook :)

**Comment by infectormp** [comment]
@serge-rider as DBeaver uses Eclipse it may be interested https://blog.openj9.org/2018/06/15/eclipse-openj9-performance-a-bake-off-on-windows/

**Comment by T3rm1** [comment]
I set Xmx to 64m but dbeaver.exe still uses >200MB.

**Comment by rmsj** [comment]
Always trust JAVA applications to be memory hungry

**Comment by argylrebanal** [comment]
What happened to DBeaver. I just load database from PostgreSQL 16 and nothing special

![CleanShot 2024-10-31 at 15 18 13](https://github.com/user-attachments/assets/bf12ef12-4557-4998-9b0f-e82c8d854427)
