### ISSUE TITLE
Inaccessible pages in User Guide

### ISSUE THREAD

**Issue by EstiShay** [dbeaver/dbeaver#4592]
*Bug*

Some of the links in the User Guide direct back to the guide's Home page with a message that you do not have permission to edit the wiki.

Examples:
1) https://github.com/dbeaver/dbeaver/wiki/Database-Connections - Clicking `Creating Connections` in the second line on this page directs back to https://github.com/dbeaver/dbeaver/wiki with this message across the top: "You do not have permission to update this wiki." The Creating Connections page can be accessed via the link in the General User Guide pane on the right.
2) https://github.com/dbeaver/dbeaver/wiki/Create-Connection - The `Database Drivers` link under step 1 does the same as the link above. However, the link in the `General User Guide` pane on the right also directs back to Home.

**Comment by tchibatron** [comment]
The first one I've fixed. Fot the second one I've created a black page.
