### ISSUE TITLE
JAXB was removed in Java 11

### ISSUE THREAD

**Issue by muflone** [dbeaver/dbeaver#4593]
https://github.com/dbeaver/dbeaver/blob/f8675afb6f9c80fc911cc4f1b9fd9310ee17ade7/plugins/org.jkiss.dbeaver.ext.import_config/src/org/jkiss/dbeaver/ext/import_config/wizards/navicat/NavicatEncrypt.java#L17

The package javax.xml.bind was removed from Java 11 after many months of deprecation warnings.
As this seems to be the only use of JAXB package, consider to remove the package or to reimplement it.

OpenStreetmap have reimplemented it in its code:
https://trac.openstreetmap.org/browser/subversion/applications/editors/josm/plugins/native-password-manager/src/org/openstreetmap/josm/plugins/npm/DatatypeConverter.java?rev=34447

**Comment by muflone** [comment]
See PR #4595

**Comment by serge-rider** [comment]
I'm afraid I can't  merge #4595 - there is a java class licensed under GPL or CDDL (we can't use it in Apache/EPL based project).
Basically it is a very simple function we need to replace (parser of hex string). It is very possible to find non-GPL code or write it from scratch. Perhaps  I'll find some time for it in near future.
