### ISSUE TITLE
Dbeaver, oracle database connection

### ISSUE THREAD

**Issue by aiak0s** [dbeaver/dbeaver#4594]
Hello,
Problem,
 I'm using Oracle Linux 7.4 operation system on VirtualBox. While trying to 'creating new connection on oracle '  this client area comes empty.
![dbeaver_client](https://user-images.githubusercontent.com/23744523/48303685-2fe33880-e51e-11e8-8f7c-c67f894da548.png)

After than i try to add a connection this error appears;
 * Connection refused -The Network Adapter could not establish the connection.

Questions,
 How could i fix it ? 
 How should this client area be ?

**Comment by serge-rider** [comment]
Client option has nothing to do with that error. 
You just have incorrect connection config (host name is wrong or port number is wrong or there are some local network issues/proxies)

**Comment by aiak0s** [comment]
> Client option has nothing to do with that error.
> You just have incorrect connection config (host name is wrong or port number is wrong or there are some local network issues/proxies)

Thank you for answer serge-rider,

 My network has not issue, hostname or port is not wrong but is TNS path OR JDBC URL neccessary ? IF it is i need some help about them. I need correct connection settings example for Oracle.

**Comment by serge-rider** [comment]
No, you need only host/port or only TNS or only custom URL.

**Comment by aiak0s** [comment]
> No, you need only host/port or only TNS or only custom URL.

Thank you again, i fixed my problem.

My listeners werent working, so i logged in database after;
i wrote -- $lsnrctl start

Then my listener is opened successfully. And my problem is over.
