### ISSUE TITLE
5.2.4 not working as eclipse plugin ?

### ISSUE THREAD

**Issue by PGcritter** [dbeaver/dbeaver#4599]
First of all thank you very much for DBeaver, a fantastic tool !

By today's standards the stand-alone version is a reasonably sized download,
but i attempted to add dbeaver to my existing eclipse mars copy anyway.

It seemed to install alright (and i have also added drw2d
which is cited as a requirement, but could not find gef)

Now it does not seem to work, "driver manager" and 
"add connection" have no apparent result (no dialog created).

I tried under Win10 and linux, in both cases using java 8 (32bits)

**Comment by PGcritter** [comment]
Hello Serge, i did a quick install at work (via marketplace client, without draw2d this time)
-same versions, same behaviour-

maybe the following is relevant? If you want i can attach today's log (a mere 300 lines, a 3kb ZIP)

```
!ENTRY org.eclipse.ui 4 0 2018-11-12 13:54:57.574
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoSuchMethodError: org.eclipse.swt.events.KeyListener.keyPressedAdapter(Ljava/util/function/Consumer;)Lorg/eclipse/swt/events/KeyListener;
k
```

**Comment by serge-rider** [comment]
Yep, this is it. Recent version of DBeaver uses Oxygen API (on new connection and driver manager dialogs).
I'll revert it to older e4 API.
Thanks for the bug report.
