### ISSUE TITLE
[MySQL] Incorrect native date/time format

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#4603]
The new option "use native date/time format" does not work fully correctly with MySQL, where I get a trailing `.0`:

DBeaver shows `2018-08-21 18:33:03.0` instead of `2018-08-21 18:33:03` for a DATETIME column in MySQL 5.7.

Moreover, if a DATETIME column has a fractional precision defined, for example DATETIME(6) then the native format should always have a fixed number of fractional digits whereas DBeaver truncates trailing zeroes. DBeaver displays:
```
2018-08-21 18:37:50.123456
2018-08-21 18:37:50.123
2018-08-21 18:37:50
```
but it should be:
```
2018-08-21 18:37:50.123456
2018-08-21 18:37:50.123000
2018-08-21 18:37:50.000000
```

**Comment by uslss** [comment]
similar to #7268
