### ISSUE TITLE
Can not change connection type

### ISSUE THREAD

**Issue by biji** [dbeaver/dbeaver#4604]
Version is: 
![image](https://user-images.githubusercontent.com/665559/48389778-8d030800-e731-11e8-95f9-561dcfd2bde1.png)

I can not change connection type to Development , Production, or Test, clicking down arrow don't show options
![image](https://user-images.githubusercontent.com/665559/48389758-7957a180-e731-11e8-8767-a7f40dc58293.png)

Env: Fedora Linux 29

**Comment by serge-rider** [comment]
What is your OS?

**Comment by biji** [comment]
Fedora Linux 29

**Comment by serge-rider** [comment]
Perhaps this depends on current theme (in 5.2.4 we changed default theme from Classic to Light).
Could you try the Classic theme?
![image](https://user-images.githubusercontent.com/6398845/48469832-de2dfd00-e800-11e8-86a3-fed52f852ee1.png)

**Comment by biji** [comment]
tried all themes or disable theming, same result:
![image](https://user-images.githubusercontent.com/665559/48478659-7fd04100-e837-11e8-928d-7a6942b27197.png)

**Comment by uslss** [comment]
cannot reproduce on 6.0.2
