### ISSUE TITLE
Use "dbeaver" as keyword in preferences to bring up all preference pages in search

### ISSUE THREAD

**Issue by de-jcup** [dbeaver/dbeaver#4606]
In preferences "dbeaver" shows only main page
![image](https://user-images.githubusercontent.com/11644753/48411797-f2abc000-e742-11e8-997a-7b989d5881c5.png)

so it would be nice if some body would add keywords in plugin.xml like

```
<extension point="org.eclipse.ui.keywords">
     <keyword
   		id="debaver.preferences.keyword.dbeaver"
   		label="dbeaver">
     </keyword>
 </extension>
```

and the reference to all dbeaver preference pagess in `plugin.xml` ala
``` 
<keywordReference id="debaver.preferences.keyword.dbeaver"/>
```

**Comment by serge-rider** [comment]
Good point 👍

**Comment by serge-rider** [comment]
Very helpful for Eclipse plugin mode and easy to implement. Thanks for the good idea.
