### ISSUE TITLE
Make 'copy selected column names' easier to access

### ISSUE THREAD

**Issue by elcasa** [dbeaver/dbeaver#4609]
Very good that dbeaver have this function: copy selected column headers, from a query result dataset but it is long to reach:
- right click
- click Advanced Copy
- choose copy column name
- click ok to the popup, even if default is ok

Could be added a voice to the right click menu, or a keyboard shortcut, to copy column headers in the clipboard?

**Comment by uslss** [comment]
already implemented
![image](https://user-images.githubusercontent.com/31996417/76772584-30df4680-67b2-11ea-89f4-2ead5e718dcb.png)
