### ISSUE TITLE
drag and drop column names into sql editor - unmarked text

### ISSUE THREAD

**Issue by alonpr** [dbeaver/dbeaver#4613]
I suggest that the 'column name' text won't be marked after the drag and drop into the sql editor.
It doesn't have much, if any, added value and just requires to press the arrow keys/mouse button to keep typing without deleting the copied column name.

**Comment by serge-rider** [comment]
This is controversial.  Most of text editors select dropped text (firstly to see what exactly was dropped, secondly to be able to delete it with one key). Perhaps we can make this configurable..

**Comment by alonpr** [comment]
Actually you are right, probably it should stay like that. But perhaps the "copy column name(s)" option should be improved then, in 5.2.4 there is some sort of weird behavior of this function on mac - after clicking on "copy column name(s)" there is always a menu with "Maximize Result Panel" and "Set tab title" coming up.

**Comment by uslss** [comment]
There is no update almost a year.
Ticket is closed.
If issue is still actual for you feel free to create new ticket.
