### ISSUE TITLE
Windows 10 start menu tile is dead after DBeaver update

### ISSUE THREAD

**Issue by ygoe** [dbeaver/dbeaver#4617]
### Steps to reproduce

1. Install DBeaver on Windows 10
2. Pin the app item from the start menu as a tile
3. Install DBeaver again

### Expected result

The pinned tile starts the application every time it is clicked.

### Actual result

The pinned tile only starts the application until it is installed again, like at every update, even in the same install directory. The tile remains pinned but does nothing when clicked, not even close the start menu. I have no idea what might cause that, I don't know where pinned tiles are stored in Windows.

**Comment by uslss** [comment]
cannot reproduce an issue.
if it is still actual for you, feel free to reopen the ticket

**Comment by ygoe** [comment]
IIRC, I used to install the app for the current user only. When I started to install it systemwide, the isse went away.
