### ISSUE TITLE
Feature Request: Constraints in SQL Server

### ISSUE THREAD

**Issue by antoniogarcia78** [dbeaver/dbeaver#4624]
DBeaver 5.2.3
DB SQL Server 2005

I need drop a column but i got an error

SQL Error [5074] [S1000]: El objeto 'DF__pio_indic__activ__23FFD730' de tipo objeto es dependiente de columna 'activo'.
  El objeto 'DF__pio_indic__activ__23FFD730' de tipo objeto es dependiente de columna 'activo'.
  El objeto 'DF__pio_indic__activ__23FFD730' de tipo objeto es dependiente de columna 'activo'.
    Error de ALTER TABLE DROP COLUMN activo debido a que uno o más objetos tienen acceso a esta columna.

The solution is delete before the column the constraint "DF__pio_indic__activ__23FFD730" but in the explorer we not have the option to explorer this type object 

To fix i found this:
https://stackoverflow.com/questions/19460912/the-object-df-is-dependent-on-column-changing-int-to-double

The only thing i need is delete the constraint as example
ALTER TABLE <table_name> DROP CONSTRAINT <constraint_name>

**Comment by serge-rider** [comment]
This is already implemented as a part of #810.
See this feature in 5.2.5
