### ISSUE TITLE
Trying to re-establish connections

### ISSUE THREAD

**Issue by wout** [dbeaver/dbeaver#4626]
Is there a way to have DBeaver start up with an empty window? Currently, it tries to re-establish connections from the last session while many of my connections require VPN. So I get a bunch of connection errors on launch, which is a bit annoying.

**Comment by serge-rider** [comment]
You can't disable SQL editors reopen at all. But you can disable auto-connect for SQL editors: 
![image](https://user-images.githubusercontent.com/6398845/48630790-251d1d80-e9ce-11e8-8b30-69754d9b3a98.png)


Also you can disable object editors (like table editors) reopen:
![image](https://user-images.githubusercontent.com/6398845/48630861-50a00800-e9ce-11e8-9758-e8312c968d7e.png)

**Comment by wout** [comment]
Great, thanks! That's exactly what I was looking for.
