### ISSUE TITLE
Feature Request: Navigate link: show table name

### ISSUE THREAD

**Issue by ssilva** [dbeaver/dbeaver#4627]
DBeaver 5.2.4

It would be nice if DBeaver displayed somewhere the table name that a link would navigate to.

For instance, in the result set viewer, when I mouseover the link icon (or the cell itself), a tooltip could display the external table name.

**Comment by up2jj** [comment]
Agree. It would be nice also if reference would be opened in a new tab by holding some modifier key like ctrl or cmd. I have not found such feature.

**Comment by serge-rider** [comment]
@up2jj it already works this way (table will be opened in a new tab if you press ctrl).
Note: if you navigate from a table editor then another table editor can be opened only once for some particular table. So you can't open multiple table editors. 
But if you are in SQL editor then you can open as many additional tabs as you need.
