### ISSUE TITLE
Feature request - toggle tabs toolbox

### ISSUE THREAD

**Issue by oxk4r01** [dbeaver/dbeaver#4628]
![screenshot_1](https://user-images.githubusercontent.com/1032224/48659742-1712df80-ea56-11e8-8ede-4ec171bcc145.jpg)
Could you implement, please, the toggle of that toolboxes? They make the layout unusable in some situations, because they impede to view the data.
Thanks in advance.

**Comment by uslss** [comment]
related with #8696

**Comment by E1izabeth** [comment]
You can hide some (or almost all) buttons in Preferences
![image](https://github.com/dbeaver/dbeaver/assets/28875055/5fd0a98b-fa42-47cd-ab64-e241a289590f)

Does it satisfy your needs?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
