### ISSUE TITLE
Not able to generate DB2 LUW table DDL

### ISSUE THREAD

**Issue by sushmareddy16** [dbeaver/dbeaver#4633]
Using dbeaver tool not able to generate db2 ddl for the table. I have checked and i have the necessary access which is required to use db2look according to the ibm docs. But still not able to.

According to the ibm doc the user should have the below privileges and the user has already 
GRANT USAGE ON SEQUENCE "SYSTOOLS"."DB2LOOK_TOKEN" TO USER "<DB_USER>"; 
GRANT SELECT ON TABLE "SYSTOOLS"."DB2LOOK_INFO_V" TO USER "<DB_USER>"; 
GRANT DELETE,INSERT,SELECT ON TABLE "SYSTOOLS"."DB2LOOK_INFO" TO USER "<DB_USER>";

Also I have execute privilege on the db2look packages 

DB2L0K05                                                                                                                        
DB2L0O06                                                                                                                        
DB2L0O07                                                                                                                        
DB2L1O01                                                                                                                        
DB2L2K1T                                                                                                                        
DB2L2O1W                                                                                                                        
DB2L2O1X                                                                                                                        
DB2L2O1Y                                                                                                                        
DB2LKSP          

I have the above privileges as required but still getting error.

![image](https://user-images.githubusercontent.com/45158652/48686888-7bfc4000-ebe4-11e8-8f11-ae58a14f024f.png)

**Comment by uslss** [comment]
cannot reproduce issue in recent version.
Ticket closed.
If issue still actual for you, please, reopen the ticket
