### ISSUE TITLE
sqlerver dblink

### ISSUE THREAD

**Issue by DavidLi1982** [dbeaver/dbeaver#4634]
use oracle DB. jdbc.oracle.11.2.0
visit a sqlserver DB by dblink. it will receive one error. 
Query execution failed
 SQL [17401] [99999]: Protocol violation

win 7. dbeaver version 5.2.5.

**Comment by serge-rider** [comment]
Are you sure it is DBeaer-specific issue? Can you execute the same query in some other SQL client (e.g. SQL Plus)?

**Comment by DavidLi1982** [comment]
> Are you sure it is DBeaer-specific issue? Can you execute the same query in some other SQL client (e.g. SQL Plus)?

Hi, I used PL/developer, the oracle client is also 11.20. and same query (simple query, select * from ss@sqlserverDB.xxx.xxx ). it worked fine. so I don't know whether is our tool issue or any configuration is incorrect.

**Comment by DavidLi1982** [comment]
The jdk is jdk1.8.0_45

**Comment by uslss** [comment]
there is no update more than a month. Ticket closed.  
If issue is still actual feel free to reopen the ticket or create a new one.
