### ISSUE TITLE
SQL Server - dbeaver 5.2.5 SQL completion not working for tables

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#4635]
After upgrade to latest dbeaver I went to a database and the SQL completion does not work at all.

SQL completion shows the databases but not tables. To be able to get the tables I have to manually type:

dbo.[table]

However it does not read from current working database.

**Comment by nmat** [comment]
In SQL editor I did test to set default values but still the same result.

**Comment by serge-rider** [comment]
Yep, smart completion is broken in new MSSQL extension. Thanks for the bug report.

Workarounds:
- Use fully qualified table names (use schema/database name)
- Use SQL Server Legacy driver (it is the same driver which was used by default in 5.2.4)
