### ISSUE TITLE
SQL Server - cannot filter Catalogs

### ISSUE THREAD

**Issue by Nekromancer** [dbeaver/dbeaver#4636]
Using newest DBeaver i cannot filter catalog using `connection properties -> General -> Filters -> Catalogs`. When i set some filter i get an exception: `SQLServerException: The value is not set for the parameter number 1` while trying to get catalogs list. It's working fine without filter

**Comment by axias41** [comment]
Me too, same issue

**Comment by serge-rider** [comment]
Duplicate of #4632

Workaround: switch to SQL Server Legacy driver.
