### ISSUE TITLE
Licensing of bundled ORacle JRE

### ISSUE THREAD

**Issue by jniggemann** [dbeaver/dbeaver#4637]
IIRC, Java 11 (available since September) and later are no longer free to use in production environments.
Are there plans to switch to the (GPLv2) Oracle OpenJDK variant or to use another non-Oracle variant, eg. Corretto?

**Comment by infectormp** [comment]
Starting with Java 11, Oracle will provide JDK releases under the open source GNU General Public License v2, with the Classpath Exception (GPLv2+CPE), and under a commercial license for those using the Oracle JDK as part of an Oracle product or service, or who do not wish to use open source software.

**Comment by infectormp** [comment]
as an alternative https://adoptopenjdk.net/

**Comment by jniggemann** [comment]
> Starting with Java 11, Oracle will provide JDK releases under the open source GNU General Public License v2, with the Classpath Exception (GPLv2+CPE), and under a commercial license for those using the Oracle JDK as part of an Oracle product or service, or who do not wish to use open source software.

Careful, if I understand correctly, Oracle does not dual-license. They offer
1) OpenJDK/OpenJRE (GPL) and
2) their proprietary JDK/JRE (Oracle Binary Code Agreement)

Oracle states that commercial use of their proprietary JDK/JRE is not permitted unless you buy a license.

This means: If one day we bundle a Oracle proprietary v11 JRE in the installer, enterprises are forbidden to use that installer if they are not paying Oracle customers.

Possible solution: Bundle another JRE.

**Comment by infectormp** [comment]
Here is more info about new licensing model https://blogs.oracle.com/java-platform-group/oracle-jdk-releases-for-java-11-and-later

**Comment by infectormp** [comment]
If I understand correctly you can't use Oracle JDK in commercial product without licensing it.

**Comment by infectormp** [comment]
Just for info Atlassian will add support for OpenJDK 8 and AdoptOpenJDK 8 in next release of their products.

**Comment by jniggemann** [comment]
> If I understand correctly you can't use Oracle JDK in commercial product without licensing it.

_Personal, noncommercial usage continues to be free and not require a subscription._ (IIRC from Oracle website, but can't remeber exactly).
Non-personal or commercial use (which for Oracle means running a Java app in a business) is not free and requires a (paid) subscription.

**Comment by serge-rider** [comment]
There is aticket #429 about replacing bundled JRE with OpenJDK.
We plan to start doing it right after 5.3 (DBeaver 6.0 will be bundled with Java 10 or 11)

**Comment by jniggemann** [comment]
duplicate of #429
