### ISSUE TITLE
Sysbase error Export ResultSet

### ISSUE THREAD

**Issue by framirezs1969** [dbeaver/dbeaver#4639]
In Sybase, when you execute a query with a MEMO field and you choose  Export ResulSet to CSV format, I get an error. 
![imagen](https://user-images.githubusercontent.com/44995201/48715984-9a7b2f00-ec16-11e8-8354-9b974f2e5273.png)

It's work on 5.2.2

**Comment by uslss** [comment]
cannot reproduce an issue for now. if it is still actual for you against recent version - feel free to reopen the ticket
