### ISSUE TITLE
DBeaver: Goto Database Object is broken för SQL Server in DBeaver 5.2.5

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4640]
DBeaver - **Version 5.2.5 CE**
DBeaver JDBC driver: **Microsoft**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014**

Something in _DBeaver 5.2.5_ when it comes to search for database objects in a SQL Server database has been broken.

**o** Start _DBeaver_ and connect to a SQL Server database.

**o** Press the **Ctrl+Shift+D** to open the Goto Database Object dialog.

**o** Enter a name to a table that exist in the database.

**o** An error message is shown:
```
Items filtering has encountered a problem.
Items filtering failed.

Items filtering failed
No enum constant
org.jkiss.dbeaver.ext.mssql.model.SQLServerObjectType.V
No enumconstant
org.jkiss.dbeaver.ext.mssql.model.SQLServerObjectType.V
```
**PS.** The equivalent for _PostgreSQL_ workes as expected.
**PPS.** The **Goto Database Object** dialog works if I try to use the SQL Server **Legacy Driver**.

**Comment by serge-rider** [comment]
The same bug as in #4642.
Already fixed and I'll publish Early Access on this week
