### ISSUE TITLE
Flat file metadata not working the same in 5.2.5

### ISSUE THREAD

**Issue by mdahlman** [dbeaver/dbeaver#4643]
Upgrading from 5.2.4 to 5.2.5 causes CSV data sources which used to work to stop working. In this case "stop working" means:
* In 5.2.4 DBeaver would parse the first line to find the column names.
* In 5.2.5 all CSV data sources appear to have no columns. Therefore features like "Read data in SQL Console" fail because of the missing metadata.

I don't yet understand if there's a simple change so that I can read my CSV sources. But I haven't found a way to read them yet. Note: the **files** are still accessible. Therefore options like "Edit data" still work correctly, since that simply opens the file without using the CSV JDBC driver.

**Comment by mdahlman** [comment]
Reverting to 5.2.4 solves the issue for me. I guess it's easy for anyone to reproduce this. (But doesn't everyone assume that??) So just let me know if there's something unusual about my situation, and I can post my csv or other details.

**Comment by serge-rider** [comment]
It is a bug in 5.2.5 version.
Thanks for the bug report
