### ISSUE TITLE
PostgreSQL table storage parameters not in DDL

### ISSUE THREAD

**Issue by cpburnz** [dbeaver/dbeaver#4644]
In PostgreSQL the table storage parameters (except for OIDS) are not in the table DDL. I've tested this for both PostgreSQL 9.1 and 10 with DBeaver 5.2.5.201811181655 running on Ubuntu 18.04.

I created a test table with:

```sql
CREATE TABLE test_table (
	id integer NOT NULL
) WITH (OIDS, fillfactor = 75, autovacuum_enabled = FALSE);
```

In the table's "Properties" tab, the storage parameters are properly displayed under the "Extra Options" field as:

```
{fillfactor=75, autovacuum_enabled=false}
```

However, those storage parameters are not in the table's DDL:

```sql
-- Drop table

-- DROP TABLE public.test_table

CREATE TABLE public.test_table (
	id int4 NOT NULL
)
WITH (
	OIDS=TRUE
);

-- Permissions

ALTER TABLE public.test_table OWNER TO postgres;
GRANT ALL ON TABLE public.test_table TO postgres;
```

**Comment by LonwoLonwo** [comment]
Since 8.2 https://www.postgresql.org/docs/8.2/sql-createtable.html

**Comment by uslss** [comment]
verified
