### ISSUE TITLE
Multiple PostgreSQL column data types in dropdown are not supported

### ISSUE THREAD

**Issue by shimshinatti** [dbeaver/dbeaver#4646]
Using **PostgreSQL 11.1** and **DBeaver 5.2.5**, when creating a column, there are multiple data types in the dropdown which cannot be used. Examples of these data types are:

- `serial`
- `text`
- `json`
- `char`
- `int`
- `date`
- `timestamp`

It happens when I'm setting the data types of columns that belong to **inactive databases**. The current database should be set to active before assigning data types to columns.

**Comment by shimshinatti** [comment]
There are times when the data types are fine, but there are also times when they aren't. Not really sure what the cause is, so I can't reproduce it.

**Comment by shimshinatti** [comment]
Found the cause, added it to original comment.

**Comment by uslss** [comment]
cannot reproduce an issue, if it is still actual for you - feel free to reopen the ticket.
