### ISSUE TITLE
Issue #4033 (copy data from resultset) again 

### ISSUE THREAD

**Issue by zarajomaker** [dbeaver/dbeaver#4647]
Same problems described in issue 4033, but now under :
- 5.2.4 CE and on
- Linux Mint 18.3
A job mate is working with same version under Windows, and it works fine. I'm not able to copy a single cell or the entire resultset. The only solution is coming back to 5.2.3 (tried to reset workspace, unsucessful)

**Comment by KES777** [comment]
#4033
