### ISSUE TITLE
Can't edit result set in cell

### ISSUE THREAD

**Issue by oxk4r01** [dbeaver/dbeaver#4648]
MySQL - Some datatypes, such as decimal, cannot be edited. I can select them, but not modify.
Regards.

**Comment by KES777** [comment]
I also can not edit cell value:

![__](https://user-images.githubusercontent.com/799021/50424413-bef8a580-086b-11e9-9dca-92958bf3a605.jpg)

here I can not set value for `parent_id` cell. At the same time I can edit other cells

**Comment by uslss** [comment]
cannot reproduce issue.
ticket closed
