### ISSUE TITLE
DbeaverCommandLine behavior when using -data launch option

### ISSUE THREAD

**Issue by dmwnz** [dbeaver/dbeaver#4649]
### Use case
trying to open several SQL connections (one call to dbeaver-cli.exe per connection) into one and the same "portable" instance of dbeaver (whose data folder is specified in dbeaver-cli.ini)

### Expected behavior
after each call to dbeaver-cli, a new connection pops up in dbeaver's "Connections" tab. This is what happens when -data flag is not set in dbeaver-cli.ini.

### Actual behavior
after each call to dbeaver-cli, a new instance of dbeaver is launched, as if the previous instance is not detected.

### Reproduction steps
1. In dbeaver-cli.ini , add 
```
-data
<data folder>
```
2. In one terminal, input the following. It will launch dbeaver.
```
dbeaver-cli.exe
```
3. In another terminal, input the following. It should add the connection to the existing instance, but instead, it launches a new instance.
```
dbeaver-cli.exe -con "<connection string>"
```

PS : my example uses dbeaver-cli.exe but the behavior should be the same with dbeaver.exe

**Comment by dmwnz** [comment]
The issue might be here
https://github.com/dbeaver/dbeaver/blob/904787f313b25d016d9c1bfa8425fa6edf726f49/plugins/org.jkiss.dbeaver.core.application/src/org/jkiss/dbeaver/core/application/DBeaverApplication.java#L210

Why use `defaultHomePath` and not `instanceLoc` (or another variable that contains the instance current path - valued with the `-data` option if I am not mistaken) ?

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on issue for a long time. If it is still actual for you, feel free to reopen the ticket
