### ISSUE TITLE
Azure Cosmos DB support

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#4650]
We need to support Micrisift Azure Cosmos DB. Perhaps with Cassandra driver.

**Comment by serge-rider** [comment]
There was a bug with query tacing config in Cassandra driver. We'll disable it by default (see Enable Query Tracinf parameter on the connection properties page)

**Comment by nkev** [comment]
I can connect to CosmosDB but cannot run any queries. Where exactly do I untick the `Enable Query Tracing` parameter you speak of?

![image](https://user-images.githubusercontent.com/5410916/50268002-51203880-047d-11e9-9f6d-ecea6e60b9d4.png)
