### ISSUE TITLE
Error rendering Postgresql/PostGIS geometry columns

### ISSUE THREAD

**Issue by jgrocha** [dbeaver/dbeaver#4651]
Hi,

Postgresql/PostGIS geometry columns are rendered fine, when the geometry is based on the OpenGIS specification. POINT, LINESTRING, POLYGON, etc, based geometries are well transformed to text for display.

But when the geometry is based on the SQL-MM specification (CURVEPOLYGON, CIRCULARSTRING, etc) the rendering fails with: Unkown Geometry Type.

This happens in version 5.2.4 and 5.2.5.

I've attached an image.

![captura de ecra de 2018-11-20 11-14-05](https://user-images.githubusercontent.com/163681/48770508-72430d00-ecb6-11e8-967f-b0963b307783.png)

How to reproduce the error:

Just run:
```sql
select st_geometryfromtext('CURVEPOLYGON(CIRCULARSTRING(0 0, 4 0, 4 4, 0 4, 0 0),(1 1, 3 3, 3 1, 1 1))')
```
and the output will show the error.

![captura de ecra de 2018-11-20 11-24-53](https://user-images.githubusercontent.com/163681/48770634-ee3d5500-ecb6-11e8-9834-a61c2daa2480.png)

DBeaver Installation Details: 
[dbeaver5.2.5.txt](https://github.com/dbeaver/dbeaver/files/2599479/dbeaver5.2.5.txt)

**Comment by serge-rider** [comment]
SQL-MM specification is not supported yet. Mark as FR.

**Comment by ssrebelious** [comment]
Any plans to implement such support?

**Comment by serge-rider** [comment]
Probably we'll use https://github.com/geotools/geotools lib for that.
Generally this feature is planned as a part of #4222

**Comment by jodygarnett** [comment]
GeoTools added its own WKT reader and some Geometry subclasses to handle some of the curves. They are dynamically turned into line strings during rendering so you get the right visual.

**Comment by serge-rider** [comment]
We won't use GeoTools for now because it is too heavy.
We use https://github.com/locationtech/jts and unfortunately it doesn't support advanced geometry formats.

However I've found a small Java library WKG (https://github.com/jericks/wkg) which does. It works fine and I'll include it in the next version as a workaround. I hope that locationtech guys will add support for extra spatial formats one day.

**Comment by serge-rider** [comment]
Note: CURVEPOLYGON, MULTICURVE  and other curve geometries are not supported by OSM/Leaflet engine (https://gis.stackexchange.com/questions/231485/preserving-curve-geometries-in-leaflet) so graphical geometry viewer won't work. But at least you can see it in the text mode.

**Comment by uslss** [comment]
verified
