### ISSUE TITLE
Feature request: monochrome text copying

### ISSUE THREAD

**Issue by BeggarsPaulSloan** [dbeaver/dbeaver#4654]
Feature request: I'm using the Dark Theme which is great. When copying code for pasting into another application with a white background, eg TextEdit on Mac, it retains the color scheme, making the text very hard to read. Is it possible to introduce a config parameter to copy text in monochrome?

**Comment by uslss** [comment]
cannot reproduce an issue. if it is still actual for you - feel free to reopen the issue.
sorry for so late response
