### ISSUE TITLE
Oracle: trailing ; removed in BEGIN..END block

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#4655]
Is it possible that fixing #4248 you have broken parsing of this statement?

```
BEGIN
  FOR per IN (SELECT 1 x FROM dual)
  LOOP
    dbms_output.put_line(per.x);
  END LOOP;
END;
```

Here the trailing ; should be kept, and I remember it working before 5.2.5!

**Comment by serge-rider** [comment]
Was fixed in https://github.com/dbeaver/dbeaver/commit/a44244dc9e1567ad4f235e2d77c388b5db10888c
