### ISSUE TITLE
SQL Server: CLOB/BLOB values handle

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#4656]
New SQL Server extension handles CLOB and BLOC values incorrectly. See https://github.com/dbeaver/dbeaver/issues/4641#issuecomment-440296839

**Comment by serge-rider** [comment]
This is jTDS-specific issue.
In 5.3 we will leave jTDS only for legacy driver so this issue shouldn't happen anymore.

**Comment by cbartolome** [comment]
Between #1464 having a jTDS-specific solution and https://github.com/Microsoft/mssql-jdbc/issues/696 implying that Microsoft's driver does not support specifying a domain during authentication, I would like to vote for this issue to be reopened.
