### ISSUE TITLE
Right clicking on results in SQL console makes two menus appear...again

### ISSUE THREAD

**Issue by AlexMax** [dbeaver/dbeaver#4659]
See #2864.

This problem appears to be happening again as of 5.2.4.  5.2.5 didn't fix things.  It might have happened on a version or two prior, but I can't say with confidence, though I can certainly test it if you need me to.

As for the repeat, I didn't know if I should open a new bug or reopen the old one.  Please feel free to correct if necessary.

EDIT: 5.3.0 came out, still having the same problem.

**Comment by uslss** [comment]
Hi @AlexMax , is issue still actual for you in recent version?

**Comment by AlexMax** [comment]
@uslss Not as far as I can tell.  The "edit" window I used to use all the time went away I think, so I didn't really notice at first, but other options that pop up a discrete window like Logical Structure -> Edit... don't cause a second popup window, so I presume it's fixed.
