### ISSUE TITLE
Editor SQL Tab Refresh problem

### ISSUE THREAD

**Issue by lucarota** [dbeaver/dbeaver#4661]
Hi all,

- DBeaver **standalone** 5.2.4 CE and on
- java openjdk version "11.0.1" 2018-10-16
- Linux Kubuntu 18.10

I have this repaint/refresh problem in Editor SQL tab:
![output](https://user-images.githubusercontent.com/7235722/48834723-c4e7fc00-ed7e-11e8-9ed7-4b308f79606a.gif)

Steps to reproduce:
1. Open an Editor SQL;
2. Write something;
3. Move you mouse pointer in/out the tab.

The only solution is to go back to 5.2.3.

Thank you,
 Luca

**Comment by lucarota** [comment]
Hi
I solved the issue using latest java 11.
Thank you

**Comment by sukitlek** [comment]
I also have this problem. Try 5.2.5 still occur.
- DBeaver standalone 5.2.5 CE
- openjdk version "1.8.0_181"
- OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)
- OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
- Linux Mint LMDE3

**Comment by lucarota** [comment]
Hi,

I solved this problem adding --launcher.GTK_version 2 to dbeaver.ini:

-startup
plugins/org.eclipse.equinox.launcher_1.5.100.v20180827-1352.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.800.v20180827-1352
**--launcher.GTK_version
2**
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Xms64m
-Xmx1024m

**Comment by sukitlek** [comment]
This's work.
Thank you very much.
Sukit

**Comment by altunyurt** [comment]
This problem exists in 5.3.0 too. deb installing dbeaver overwrites the modified ini and changes it to 

```
➜  ~ sudo cat /usr/share/dbeaver/dbeaver.ini
-startup
plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.551.v20171108-1834
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Xms64m
-Xmx1024m
```

as @lucarota stated, adding 
```
--launcher.GTK_version
2
```
fixes the problem.

**Comment by opravil-jan** [comment]
Hi,

in new version on debian stretch has the same problem and the workaround does not work. Dbeaver version is 6.0.2

**Comment by ELForcer** [comment]
On Linux Mint 19 same problem. 

![image](https://user-images.githubusercontent.com/30798063/57779069-7bc5a300-7736-11e9-8234-041226a5ae7a.png)

![image](https://user-images.githubusercontent.com/30798063/57779087-81bb8400-7736-11e9-9c66-77a4a9603676.png)

System info:
Kernel: 4.18.0-17-generic x86_64 bits: 64 compiler: gcc 
v: 7.3.0 Desktop: Cinnamon 4.0.10 Distro: Linux Mint 19.1 Tessa 
base: Ubuntu 18.04 bionic

**Comment by ezandonai** [comment]
I have the same issue here.
And this 
```
--launcher.GTK_version
2
``` 
doesn't fix the problem.

Linux Mint 19.2 Tina
Cinnamon

Dbeaver 6.2.1
dbeaver.ini
```
-startup
plugins/org.eclipse.equinox.launcher_1.5.400.v20190515-0925.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.1000.v20190125-2016
--launcher.GTK_version
2
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Xms64m
-Xmx1024m
```
