### ISSUE TITLE
SQL Server Can't detect source entity since last update

### ISSUE THREAD

**Issue by rXp** [dbeaver/dbeaver#4662]
Hi,

Since the latest update of DBeaver (november 19, 2018) I cannot delete or modify a line after a select.
The error message is : 

> Error saving changes in database
> 
> Reason:
> Can't detect source entity

Server : Microsoft SQL Server 2008 R2 - 10.50.1600.1
Client : windows 7 pro x64
My select contains the full name (from db.schema.table) but it doesn't help.

Did the last version changed any option ? I also tried to recreate it but it didn't help.

[EDIT] The reason is that when dbeaver tried to get the metadata it can't. Because of column 'name' being ambiguous. The 'order by' clause used by dbeaver forgets to specify table.column.
I have to run all my select on the database master instead of using the one I am working on for it to not bug.

rXp

**Comment by rXp** [comment]
Here is the SQL / Meta query made by dbeaver and the error : 
`SELECT kc.*,t.name as table_name FROM 
MyDB.sys.key_constraints kc,MyDB.sys.tables t
WHERE kc.parent_object_id=t.object_id AND kc.schema_id=1 AND kc.parent_object_id=422292564
ORDER BY name`
> [209] Ambiguous column name 'name'.

My query is the following (I changed the table name and some fields name) : 
`SELECT MyID, SNPN, FKID, AccNote, FK2ID, FK3ID, FK4ID, FK5ID
FROM MyDB.dbo.MyTable;`
This simple select is created by dbeaver by right clicking on the table and doing "Read data in SQL Console"

**Comment by serge-rider** [comment]
I've fixed first issue (ambiguous column ref in metadata queries). Although I can't reproduce the problem - perhaps it depends on SQL Server version. Thanks for the bug report.
