### ISSUE TITLE
SSH Banner question

### ISSUE THREAD

**Issue by wzygadlo** [dbeaver/dbeaver#4663]
Hello there, 

I have got a question, is there a way to mute ssh banner during Tunnel initialization? 

It can be mute from a terminal with -q option 
`ssh -q xxxxx`

![archlinux 2018-11-21 15-57-35](https://user-images.githubusercontent.com/26280326/48874135-7b130c00-eda6-11e8-82e4-1e509f0c2e3b.png)

**Comment by pmoravek-hw** [comment]
An option to disable the ssh banner would be greatly appreciated. It is easy to test, set up a banner in sshd like this:
https://www.shellhacks.com/setup-warning-message-banner-ssh/

and connect to a db with dbeaver over ssh.

**Comment by jportner-hw** [comment]
I have opened a pull request to not show the SSH banner when connecting.
https://github.com/dbeaver/dbeaver/pull/5103

**Comment by wzygadlo-hw** [comment]
It works with 5.3.4 !!! no more Ssh banner
