### ISSUE TITLE
Bug: DBeaver doesn't close connection to PostgreSQL database when setting another database as active

### ISSUE THREAD

**Issue by dseitz** [dbeaver/dbeaver#4666]
In previous versions of DBeaver it was possible to externally drop a PostgreSQL database (e. g. via psql) if you set another database as active beforehand. In newer versions you have to disconnect from the server before you can drop a database (which DBeaver has connected to).

If DBeaver is connected to the server and the database was never set as active you can externally drop it with no problems.

Looking at the database connections revealed that DBeaver doesn't close the connection to a database, even if another database is set as active.

**Comment by serge-rider** [comment]
It is not a bug. We don't close connections implicitly (they may be used by SQL scripts or opened object editors). Maybe connection should be closed if there are no editors which use it..
