### ISSUE TITLE
 5.2.5 not fixed yet as eclipse plugin ?

### ISSUE THREAD

**Issue by PGcritter** [dbeaver/dbeaver#4667]
Hello, it seems version 5.2.5 is not working yet as a plugin (at least under eclipse mars aka 4.5)
see previous bug report (https://github.com/dbeaver/dbeaver/issues/4599)
I can now open driver manager and driver properties but cannot edit connection and the initial dialog to create one does no got past the "next step" button (probably not the exact labelling)
The last error in log is 
[20181122.zip](https://github.com/dbeaver/dbeaver/files/2607682/20181122.zip)

!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoClassDefFoundError: org/eclipse/core/runtime/Adapters

**Comment by tati-kru** [comment]
We need better support for Eclipse Mars

**Comment by serge-rider** [comment]
I had to copy-paste Adapters into out utility class.
That's bad but what choices do we have. I'd prefer to keep compatibility with Mars, it is not that old after all.

Please check it in 5.3.3
