### ISSUE TITLE
Navigation search

### ISSUE THREAD

**Issue by oxk4r01** [dbeaver/dbeaver#4670]
HI. I'm on 5.25 version and the search in the navigation tree doesn't work. Is this a not fixed bug or is an error with my istallation?
Regards!

**Comment by goxr3plus** [comment]
@oxk4r01  At least for me it works :)

**Comment by oxk4r01** [comment]
So is it a problem with my own installation? What can I do? The only way I can search for tables or databases is via the Navigate/Open Database Object in the main menu, because the search box in Navigation doesn't finds nothing...

**Comment by goxr3plus** [comment]
Unistall and fresh install DBeaver latest version.
