### ISSUE TITLE
Auto Generated chekbox is disabled if creating MSSQL table

### ISSUE THREAD

**Issue by alex-q** [dbeaver/dbeaver#4672]
How to reproduce:
- Connect to MSSQL database.
- Create new table.
- Go to Columns.
- Add column.
- Select column type "bigint".
- Try to change Auto Generated checkbox state, it is not changing.
- If I press F4 and switch to properties mode, the Auto Generated checkbox here is disabled too.

My environment: Ubuntu 18.04 LTS, DBeaver 5.2.5.

**Comment by grahamoregan** [comment]
same issue on dbeaver 5.3.5 on mac os 10.14.2, it can pick up that existing tables have auto increment set but it isn't an obvious check-box on a new column

**Comment by GaryChiang** [comment]
I have already encounter this issue as well. Is any work around method to solve?

**Comment by grahamoregan** [comment]
I didn't find a work around so I settled for a SQL file template that I use to create the tables quickly.

**Comment by lflucasferreira** [comment]
This bug still persists. I believe it will be fixed soon.

**Comment by ziSo12** [comment]
I think you mean "Auto Increment". Same issue using SQLite.
When I check the box for Auto Increment (as well as set primary key) and then persist the changes,
the checkbox is unchecked again and greyed out.
My environment: Ubuntu 20.04 LTS, DBeaver 7.0.4

**Comment by uslss** [comment]
Cannot reproduce an issue for now.
If it is still actual for you - feel free to reopen the ticket
