### ISSUE TITLE
View definition not available on Db2 z/OS

### ISSUE THREAD

**Issue by orbanbalage** [dbeaver/dbeaver#4675]
![image](https://user-images.githubusercontent.com/285574/48947461-8fcfdb00-ef31-11e8-928a-f2ae05c27e67.png)

The View definitions are stored as CLOB, which might be the reason it's not implemented - but just casting it to varchar would help in most cases (where the definition is not extremely long)

```
SELECT
STATEMENT, CAST(STATEMENT AS VARCHAR(32000))
FROM SYSIBM.SYSVIEWS
WHERE NAME = :_view 
AND CREATOR = :_schema
WITH UR;
```

https://www.ibm.com/support/knowledgecenter/en/SSEPEK_11.0.0/cattab/src/tpc/db2z_sysibmsysviewstable.html

**Comment by serge-rider** [comment]
DBeaver do not support any z/OS-specific features t the moment, this one would be a good starting point.
Thanks for the information.

**Comment by Arty68** [comment]
[drivers.xml.txt](https://github.com/dbeaver/dbeaver/files/2633192/drivers.xml.txt)

By editing drivers.xml in .dbeaver4\.metadata\.plugins\org.jkiss.dbeaver.core folder.
I was able to view SYSIBM catalog ..etc

**Comment by serge-rider** [comment]
I've added view definition reading (from CLOB column) but unfortunately I can't validate this because I don't have access to z/OS server.
Could you test it? You will need to change property `Meta model type` of z/OS driver in order to enable this feature:
![image](https://user-images.githubusercontent.com/6398845/49701783-db58d900-fc01-11e8-84b9-d1cda18cc52f.png)

If it will work fine then I'll enable it by default in the next version.

**Comment by Arty68** [comment]
Thanks a lot

I will try it later

Le dim. 9 déc. 2018 à 20:32, Serge Rider <notifications@github.com> a
écrit :

**Comment by orbanbalage** [comment]
It works! Thank you very much!

The SQL is full of whitespaces, as returned by Db2, but that is a minor item, we can live with that.

ie:

`CREATE VIEW ABCDB.ABCTABAUTH AS                                          SELECT * FROM "SYSIBM".SYSTABAUTH WHERE                                   (
SCREATOR LIKE 'XYZ%' OR SCREATOR LIKE 'XYZ%' OR                       TCREATOR LIKE 'XYZ%' OR TCREATOR LIKE 'XYZ%'
)`

**Comment by serge-rider** [comment]
Thanks for testing. 
I'll fix the bug with table DDL and include this new feature in the next version.
