### ISSUE TITLE
Feature request: Integrate DevStyle

### ISSUE THREAD

**Issue by PratimGhosh86** [dbeaver/dbeaver#4678]
DevStyle is a huge improvement over the native dark theme. Is there any possibility to bundle it by default?

**Comment by tchibatron** [comment]
You can install it manually using [this](https://github.com/dbeaver/dbeaver/wiki/Eclipse-extensions) instruction.

**Comment by serge-rider** [comment]
Yes, this would be quite handy to include it. However there are a few concerns:
- DevStyle plugins aren't open source and it's devlopment can be stopped or it my become commercial.
- It is not well-doumented and thu is so not easy to customize DevStyle for a particular product.

Hoever I'll mark this as FR, perhaps we'll find a way to include DevStyle, maybe with some simplified installation process.

**Comment by tati-kru** [comment]
DevStyle p2 repository config was added in both CE and EE so it can be installed in two clicks.
I think we won't make any deeper integration.
