### ISSUE TITLE
Feature Request: Add "Copy Advanced Info" to query metadata context menu

### ISSUE THREAD

**Issue by novusnick** [dbeaver/dbeaver#4681]
To whom it may concern,
I was working on a project where I need to compare the metadata of a query to that of an existing table.  I was able to do an "Copy Advanced Info" for the table metadata, but only a copy of the column names for the query metadata.  I don't have create table privileges for this database, otherwise I would have created a table and compared the metadata that way.  Can "Copy Advanced Info" be added to the query metadata context menu?

**Comment by serge-rider** [comment]
Do you mean Metadat panel?
What "Copy advanced info hould do there"? Copy all columns?

**Comment by novusnick** [comment]
Yes- it is the metadata panel and a "Copy All Columns" option would work well.  If that option is there, I'm not seeing it currently.  In trying to copy the metadata of the query, particularly the type, when I right click, I only see "Copy" or "Copy Column Names".  Copy only copies the value my mouse is currently over and Copy Column Names only copies the column names- I don't have a way of copying the name and type of the columns.  I hope that helps

**Comment by tati-kru** [comment]
<img width="370" alt="screenshot 2018-12-13 at 17 07 08" src="https://user-images.githubusercontent.com/30336552/49943849-055c1500-fefa-11e8-926b-f93a3e289744.png">
It was made as a Copy Selection in the context menu in 5.3.

**Comment by novusnick** [comment]
Awesome- thanks!
