### ISSUE TITLE
ER Diagrams Dbeaver 2.5

### ISSUE THREAD

**Issue by Aneudylab** [dbeaver/dbeaver#4684]
Hello.

In version 2.4 when i right clicked a table and clicked "view diagram" i could see the 
- the entity
- entities that depend on that entity on the left
- entities on which that entity depends on the right

![2 4](https://user-images.githubusercontent.com/5367655/48992338-00375180-f116-11e8-8707-6c84ca307e5d.png)

In version 2.5 i can only see 
- the entity
- entities on which that entity depends on the right

![2 5](https://user-images.githubusercontent.com/5367655/48992339-00375180-f116-11e8-9a94-caefe5081ee8.png)

How can i configure dbeaver 2.5 to bring back that behavior?

**Comment by uslss** [comment]
issue is out-of-date.
Ticket closed
