### ISSUE TITLE
SSH Tunnel is not used by Oracle DB

### ISSUE THREAD

**Issue by adeorato** [dbeaver/dbeaver#4685]
When I build an SSH tunnel, this tunnel is created, but it seems that Oracle does not use this connection.
When I look at netstat, it shows a tunnel, but also a direct connection to the database. If the firewall blocks direct connections, the database connection is running in a timeout. Therefore, I assume that the SSH tunnel is established but not used.

**Comment by rmundkowsky** [comment]
I am also interested in this.  Note I was able to use PuTTy to create a tunnel and DBeaver worked over that, but the Tunnel capability built into DBeaver does not seem to work for Oracle.

**Comment by adeorato** [comment]
> 
> 
> I was able to use PuTTy to create a tunnel and DBeaver worked over that

Di you set it as SOCKS proxy within DBeaver or ended the tunnel on the Oracle machine (ssh directly to Oracle and jdbc target was localhost)?

**Comment by rmundkowsky** [comment]
JDBC to the localhost.

**Comment by uslss** [comment]
not reproducible for now.
