### ISSUE TITLE
Error when inserting smileys. Although table and colums are utf8mb4

### ISSUE THREAD

**Issue by tafelnl** [dbeaver/dbeaver#4686]
Try the following SQL:
```
UPDATE some_table
SET some_column = ?
WHERE some_other_column = ?, parameters ['Cheers! 🍻',1]
```

It gives me the following error:
`
SQL Error [1366] [HY000]: (conn:57825) Incorrect string value: '\xF0\x9F\x8D\xBB' for column 'some_column ' at row 1 
`

The column charset = `utf8mb4` and the collation = `utf8mb4_unicode_ci`

**Comment by Ptolemeaus** [comment]
Same here

dbeaver version: 6.0.3 (both Win and Linux)
column charset: utf8mb4
collation: utf8mb4_general_ci

When I insert a string contain "😂", it throws a error just like tafelnl's:
```
Incorrect string value: '\xF0\x9F\x98\x82"}...' for column 'F_body' at row 1
```

But my app on server works properly under same config. Have tried HeidiSQL on Windows, also works.

I try to figure out what's the difference between these three:

* Server App:

explicit set chartset=utf8mb4 when init db connection

* HeidiSQL:

run ` show variables where variable_name like "char%";`, I get

```
------------------------|--------------------------
character_set_client    |utf8mb4
character_set_connection|utf8mb4
character_set_database  |utf8
character_set_filesystem|binary
character_set_results   |utf8mb4
character_set_server    |latin1
character_set_system    |utf8
character_sets_dir      |/usr/share/mysql/charsets/
```

* dbeaver:

also run ` show variables where variable_name like "char%";`, I get

```
------------------------|--------------------------
character_set_client    |utf8                      
character_set_connection|utf8                      
character_set_database  |utf8                      
character_set_filesystem|binary                    
character_set_results   |                          
character_set_server    |latin1                    
character_set_system    |utf8                      
character_sets_dir      |/usr/share/mysql/charsets/
```

**Comment by ExecGnosis** [comment]
Same on #4665 

Both problems can be solved by updating the connection driver version to 8.0.16 (supposing the database in question is MySQL, you're all using JDBC and you already changed the charset and collation to utf8mb4/utf8mb4_unicode_ci).

Link: https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.16/

PS: Tested in Windows 10 x64 - DBeaver 6.1.1

**Comment by ExecGnosis** [comment]
Same on #4665 

Both problems can be solved by updating the connection driver version to [8.0.16](https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.16/) (supposing the database in question is MySQL, you're all using JDBC and already changed the charset and collation to utf8mb4/utf8mb4_unicode_ci).

After downloading it, just go to DBeaver driver settings into your connection settings, add this file and select it.

**Then it's done**.

PS: Tested in Windows 10 x64 - DBeaver 6.1.1
