### ISSUE TITLE
DBeaver shows only one table when logged on Denodo

### ISSUE THREAD

**Issue by GintaSolyte** [dbeaver/dbeaver#4689]
Hello!

DBeaver shows only one table per datasource when connected to Denodo. I am using jdbc driver.
On Denodo browser I can see all the new views/tables.

Is it a problem with settings?

Kind regards
Ginta

**Comment by serge-rider** [comment]
This can be a problem with driver configuration.
Try to play with "Omit catalog/schema" parameters:
![image](https://user-images.githubusercontent.com/6398845/49344579-6bd76c80-f68a-11e8-8d70-ff06c5f77263.png)
