### ISSUE TITLE
Bug: nvarchar length on MSSQL Server doubles or triples in table metadata

### ISSUE THREAD

**Issue by novusnick** [dbeaver/dbeaver#4690]
To whom it may concern,
On DBeaver, the length of all nvarchar fields on my table read 1020.  Looking on SSMS, the actual length is 255.  Earlier today, those same fields were reading 510 as a length.  This looks to be a bug

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by novusnick** [comment]
It looks now there is a different issue:
In looking at the column length under table properties in MSSQL, the length shows a length of zero.  When I try to alter this, it changes the length to a length of one.  Thank you for your help with this and for your work on DBeaver

**Comment by novusnick** [comment]
Thanks Serge!

**Comment by apk4** [comment]
Still reproduced in 6.0.0201903101945:

`sqlcmd> create table dbo.dbeaver_str( id int, vc varchar(10), nvc nvarchar(10))`

But after DDL generation in DBeaver:
```
-- Drop table

-- DROP TABLE test_vc.dbo.dbeaver_str GO

CREATE TABLE dbeaver_str (
	id int NULL,
	vc varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	nvc nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) GO;

```

**Comment by arthuralpha** [comment]
I have both navicat & dbeaver, and on dbeaver the nvarchar is doubled in length
dbeaver version:
![image](https://user-images.githubusercontent.com/2024679/57663845-4b8fde80-7628-11e9-92e5-46469e109e24.png)

navicat:
![image](https://user-images.githubusercontent.com/2024679/57663769-f0f68280-7627-11e9-8e79-047bce1a9968.png)

dbeaver:
![image](https://user-images.githubusercontent.com/2024679/57663794-0a97ca00-7628-11e9-9af0-3e7c7b1deda2.png)

**Comment by cnemelka** [comment]
![image](https://user-images.githubusercontent.com/27328932/61974041-d2572500-afa2-11e9-9067-fc87d06eb1c4.png)

This is still an issue.

**Comment by dr-1** [comment]
I think this issue should be re-opened. I can reproduce it on version 23.0.0.

**Comment by E1izabeth** [comment]
@dr-1 please create a new issue with steps to reproduce

**Comment by penCsharpener** [comment]
I'm still having this issue with DBeaver 25.2.3. Please reopen the issue.
