### ISSUE TITLE
Support mysql 8.0

### ISSUE THREAD

**Issue by mstao** [dbeaver/dbeaver#4691]
I use mysql 8.0 for testing , but there is an error:

```
Unable to load authentication plugin 'caching_sha2_password'.
```

**Comment by serge-rider** [comment]
This is a general MySQL 8 config issue.
https://stackoverflow.com/questions/50387952/how-to-resolve-unable-to-load-authentication-plugin-caching-sha2-password-issu

However MySQL 8+ server should work fine with DBeaver MySQL8 driver:
![image](https://user-images.githubusercontent.com/6398845/49104249-5b5e6680-f232-11e8-993e-53bc284fb4da.png)

**Comment by mstao** [comment]
I use `MySQL 8.x` to connect local db, all is ok, Thanks.
