### ISSUE TITLE
Bug: Auto complete on db2 zos broken when schema is set

### ISSUE THREAD

**Issue by Sargul** [dbeaver/dbeaver#4692]
Version 5.2.5 auto complete with set schema:
![grafik](https://user-images.githubusercontent.com/5595511/49063428-9f903d80-f217-11e8-9425-18e4bbadbb9c.png)
![grafik](https://user-images.githubusercontent.com/5595511/49063448-b2a30d80-f217-11e8-9132-ed2b03f4fee6.png)

Version 5.2.4 auto complete with the same schema:
![grafik](https://user-images.githubusercontent.com/5595511/49063529-f39b2200-f217-11e8-82fd-dbdf4f166e0e.png)
![grafik](https://user-images.githubusercontent.com/5595511/49063537-f9910300-f217-11e8-8a87-796c156c8c89.png)

As you can see the meta data queries seem to be wrong.

**Comment by ascendhans** [comment]
I see this with SQL Server also. Similar issue with SQL Autocomplete.

**Comment by Sargul** [comment]
Seems to be fixed in 5.3
