### ISSUE TITLE
DB2 Some dates are not returned correctly to sql select result

### ISSUE THREAD

**Issue by ip940055** [dbeaver/dbeaver#4693]
OK
1939-12-31 --> NULL
 
-->

**Comment by titou10titou10** [comment]
Hi,
What flavor (DB2 z/OS, DB2/400, DB2/LUW) and version of DB2 are you using?
Could you explain exactly what are the steps to reproduce the problem?
Thanks

**Comment by ip940055** [comment]
Hello,

I'm using DB2/400 version of DB2 is V7R3M0.

I created a table only with a field called BIRTHDATE:

CREATE TABLE TESTBIRTH(BIRTHDATE DATE NOT NULL WITH DEFAULT);

Insert some records:

INSERT INTO TESTBIRTH VALUES('2011-04-20');
INSERT INTO TESTBIRTH VALUES('1940-04-20');
INSERT INTO TESTBIRTH VALUES('1939-12-31');

Select the content of the table:

SELECT * FROM TESTBIRTH;

and get: 

BIRTHDATE
2011-04-20
1940-04-20
NULL

**Comment by uslss** [comment]
not reproducible for now. Ticket closed
![image](https://user-images.githubusercontent.com/31996417/79892673-8ccd6880-840b-11ea-80ec-0e9f3e9de8bb.png)
