### ISSUE TITLE
Quick key for "Read data in SQL console"

### ISSUE THREAD

**Issue by kramer65** [dbeaver/dbeaver#4695]
99% of the time I open DBeaver to inspect a table and run some simple queries. I always need to select the table and then right-click and select `Read data in SQL console`. Is it possible to do this with a quick key?

If not it would be great if this could be implemented..   :-)

**Comment by serge-rider** [comment]
Sure, you can bind any shortcut to this command:
![image](https://user-images.githubusercontent.com/6398845/49300172-8265a400-f48f-11e8-91b1-ee10c95e1726.png)

Note: if you need just to view table's data you could just double click on a table and switch to Data tab.
