### ISSUE TITLE
Renaming default script file name stops showing connection name before new name in SQL editior

### ISSUE THREAD

**Issue by ralebhattushar** [dbeaver/dbeaver#4698]
Feature request:
When I right-click on a connection and select SQL editior, it shows a new sql file in SQL editior with name [ConnectionName]Script-[number].sql. But when I rename it, it shows only renamed file name. It doesn't show the [ConnectionName] for which it was created. It will be good to show the connection name before the renamed file name so that it will be easy to understand for which connection I am using the corresponding script file. Also, the naming convention will be consistent accross all the files opened in SQL editior.

**Comment by ralebhattushar** [comment]
![image](https://user-images.githubusercontent.com/45413542/49129492-0f74f580-f2f6-11e8-8a64-68665e398c04.png)

**Comment by serge-rider** [comment]
Can't reproduce. 

- How do you rename script?
- What is your DBeaver version?

**Comment by ralebhattushar** [comment]
I am renaming the script using Save As.
![image](https://user-images.githubusercontent.com/45413542/49353482-fc8e6680-f6e3-11e8-97f5-1a876ce3520c.png)

As shown in the previous screenshot, I created a script file for a connection with default name Script-19 and it has connection name before it. I created another script for a connection and renamed it to Test.sql using Save As. After renaming, it is showing only Test.sql and not the connection name before it.

**Comment by serge-rider** [comment]
- Default way to rename a script is with <kbd>CTRL+F2</kbd> or using context menu in project explorer view. When you use Save As you create another script on your local file system
- Currently DBeaver doesn't show connection info for SQL scripts on local file system. It is actually a kind of bug or misfunction, see fix in the next version.

**Comment by pro9dan** [comment]
I rename my sql file from script-5.sql to 사용자쿼리.sql.
And I opened 사용자쿼리.sql.
This time Dbeaver alert like this.
"can't open editor connection"
