### ISSUE TITLE
dbeaver ER Diagram

### ISSUE THREAD

**Issue by bebee4java** [dbeaver/dbeaver#4701]
How do I draw a table model or view on dbeaver ER Diagram

**Comment by serge-rider** [comment]
You can view only existing tables/view on ERD. If you need to make some custom diagram you can do this: https://github.com/dbeaver/dbeaver/wiki/Custom-Diagrams

**Comment by Praveen-Rai** [comment]
@serge-rider That's really great to be able create ER Diagrams for the selected tables with Notes. But ability to define a schema using ER diagrams is a great help in database designing. Personally, that's something i miss badly coming from MySQL Workbench. I would request this feature from DBeaver team.

**Comment by reya276** [comment]
How can I see the Primary and Foreign Keys when I make the connections. For some weird reason I only see a line and looks nothing like what is on the wiki. I currently have a standard enterprise license.

**Comment by crlsgms** [comment]
Im trying to see the ER diagram of some applications using mariaDB and dbeaver 6.0.2. 

the tables appears on the diagram, but there is no relationship or connections between then. Is it avaiable on dbeaver? How do I enable to see the connections?

**Comment by serge-rider** [comment]
@reya276 @crlsgms Are you sure your table have foreign keys? Check it on Fereign Keys tab of table editor. Maybe you are working with myisam database engine (which doesn't support relations).

**Comment by reya276** [comment]
> @reya276 @crlsgms Are you sure your table have foreign keys? Check it on Fereign Keys tab of table editor. Maybe you are working with myisam database engine (which doesn't support relations).

Yes I'm looking at a wordpress database with an e-commerce store which have a bunch of tables with foreign keys. All or most tables are InnoDB not myisam.

**Comment by crlsgms** [comment]
> @reya276 @crlsgms Are you sure your table have foreign keys? Check it on Fereign Keys tab of table editor. Maybe you are working with myisam database engine (which doesn't support relations).

Serge, I'm sure the application has foreign keys, they are just not displaying any lines / connections on the diagram

Is there any other information or test I can do to simulate this, so would be possible to troubleshoot on dbeaver?

**Comment by serge-rider** [comment]
Can you see your foreign keys in table editor? 
Like here:
![image](https://user-images.githubusercontent.com/6398845/56193486-6a0ab600-6039-11e9-823d-eaa1cf0615f1.png)

**Comment by pdohara** [comment]
OK I will bite. I am evaluating DBeaver. I really like the ERD with related tables. I am learning a schema for a new product and this is useful. Earlier today DBeaver stopped pulling in Foreign Key information. It was pulling it in earlier, but now is not. I have an Oracle 9 database. I have connections for several Oracle databases and two DB2 databases. None seem to be returning Foreign Key information? I found a different issue from 2015 where a fresh install "fixed" this issue. Is there something I should try before that?
