### ISSUE TITLE
Navigate to referencing table into new window : doesn't update filter if window already open

### ISSUE THREAD

**Issue by dmwnz** [dbeaver/dbeaver#4702]
Dbeaver 5.2.5
Windows 7

### Use case
- Have parent - children table relationship
- Select line in parent table
- Ctrl + Shift + 1, click on reference of child table => it successfully opens the child table in a new tab, filtered with children matching parent entry
- Go back to parent table, select another line
- Ctrl + Shift + 1, click on same reference of child table => it switches back to the child table but **doesn't update the filter**

### Expected behavior
If the table is already open in a tab, update the filter after navigating via Ctrl + Shift + 1

**Comment by serge-rider** [comment]
Thanks for the bug report.

**Comment by serge-rider** [comment]
Fixed. We needed to refresh new filter values.

**Comment by kseniiaguzeeva** [comment]
Verified
