### ISSUE TITLE
Database Navigator: Edit menu shown after a right-click context menu refresh of object.

### ISSUE THREAD

**Issue by BeggarsPaulSloan** [dbeaver/dbeaver#4703]
A minor UI issue.

Database Navigator: Edit menu shown after a right-click context menu refresh of object.

Inside Database Navigator, after right-clicking and refreshing an object, an unnecessary Edit menu is displayed. See screenshots. MacOS 10.14.1. DBeaver 5.2.5.201811181655

![screenshot 2018-11-28 at 09 49 27](https://user-images.githubusercontent.com/42141729/49144936-84e0c600-f2f6-11e8-9e72-3e5b60294ab6.jpg)

![screenshot 2018-11-28 at 09 49 57](https://user-images.githubusercontent.com/42141729/49144950-8b6f3d80-f2f6-11e8-90fd-1d14940c13d4.jpg)

**Comment by serge-rider** [comment]
Can't reproduce (latest MacOS Mojave)
Does this happen with Classic/Light themes?

**Comment by BeggarsPaulSloan** [comment]
Issue resolved by the time of the 6.1.1 release
