### ISSUE TITLE
Connecting to cockroaches asks for password even though certificates are being used

### ISSUE THREAD

**Issue by brucemcpherson** [dbeaver/dbeaver#4707]
When connecting using ca.crt and a tls key and certificate to a secure cockroaches, dbeaver asks for a password as well. I believe the DB is properly set up as it does not ask for a password with either postico or table plus using the same certs. 

![screen shot 2018-11-28 at 16 03 43](https://user-images.githubusercontent.com/1894020/49164757-a5754400-f327-11e8-9c2b-8449731f9d99.png)

![screen shot 2018-11-28 at 15 56 28](https://user-images.githubusercontent.com/1894020/49164783-b8881400-f327-11e8-9b89-d89597cad64f.png)

How can I avoid this?

**Comment by serge-rider** [comment]
Please check #4067
