### ISSUE TITLE
MariaDB "Create new connection" wizard disabled "Next >" button

### ISSUE THREAD

**Issue by eworm-de** [dbeaver/dbeaver#4709]
Starting the "New Connection Wizard", then selecting "MariaDB" brings up a "Create new connection" dialog. You can change settings on first page and create the connection by pressing "Finish". However "Next >" button is disabled, so advanced settings (for example ssh tunnel) and naming the connection is not possible.

![screenshot_2018-11-28_23-08-24](https://user-images.githubusercontent.com/970853/49185873-53eaaa80-f363-11e8-88b6-e376e18c7c12.png)

My workaround is to create a connection with wrong/incomplete settings, then right-clicking the connection and selecting "Edit Connection". The following dialog is fully functional.

**Comment by serge-rider** [comment]
Yp, we reorganized connection wizard a few versions ago - trying to make it simpler. Too many connection options confuses people, especially new users.
We can't remove next button because it is still used.
I'd wish to make this UI more obvious but I'm not sure how..

**Comment by eworm-de** [comment]
Perhaps just converting the links to buttons does the trick? As said, links looks like external web resources.

**Comment by serge-rider** [comment]
Like this:
![image](https://user-images.githubusercontent.com/6398845/49518286-4f684980-f8af-11e8-95b5-f172b562252a.png)
?
Looks not very fancy as for me. But if is more convenient and obvious then we can keep it.

**Comment by serge-rider** [comment]
Let's use this one for now:
![image](https://user-images.githubusercontent.com/6398845/49578136-133df300-f95a-11e8-84fc-06643fadb0da.png)
