### ISSUE TITLE
Eclipse Update Site: https://dbeaver.io/update/latest/content.xml missing

### ISSUE THREAD

**Issue by rboe** [dbeaver/dbeaver#4712]
The content.xml is missing on the eclipse update site https://dbeaver.io/update/latest/.

There is only a content.xml.xz, but eclipse doesn't use this.

**Comment by serge-rider** [comment]
Basically update repo is created by standard Tycho task which keeps content.xml in the content.jar file (content.xml.xz is created by this task ad well).
Maybe we dhoul hange some config there...

**Comment by serge-rider** [comment]
Generally this is controlled by `compress` property of tycho-p2-repository:assemble-repository task - https://www.eclipse.org/tycho/sitedocs/tycho-p2/tycho-p2-repository-plugin/assemble-repository-mojo.html

I'm still not sure that we should change this. Many standard Eclipse P2 repositories have only content.jar/artifacts.jar but not plain xml files.

**Comment by rboe** [comment]
I checked the behaviour of Eclipse on my home PC now: It's working fine there. 
It seems the problem is that our corporate proxy is blocking certain files. (Especially compressed ones.)
Sorry for the confusion.
