### ISSUE TITLE
Embedded H2 Database Connections not Properly Closed/Invalidated

### ISSUE THREAD

**Issue by jjbr** [dbeaver/dbeaver#4715]
When working with embedded H2 database files, the closing and invalidation of a connection to such a database don't seem to work correctly. I've noticed this in two situations.

*Modification/replacement of database file outside of DBeaver:* Say I have `mydb.mv.db` as my database file and open it up in DBeaver successfully. A small check mark on green background is displayed next to the database icon in the Database Navigator. Now I disconnect from the database by clicking on the red `Disconnect` button, the check mark disappears. 

With DBeaver still running, I now replace `mydb.mv.db` with a new file named identically. 

I go back to DBeaver and click on the database in the Database Navigator, the check mark reappears. The data displayed is the data inside of the old file, however, not the newly created one (refreshing or invalidating the connection doesn't help). This seems like a bug to me - shouldn't DBeaver use the new file? I have to exit and restart DBeaver for it to load the new file.

*Not properly disconnecting, causing a DoS for other applications:* I have an application MyApp that uses `mydb.mv.db` and I would like to view the database's content using DBeaver. As the embedded H2 database only allows for one simultaneous connection, I can only either have DBeaver or MyApp connection at any given moment, which is fine. However, when clicking on the red `Disconnect` button in DBeaver, it seems to not properly release the connection to the Database. MyApp cannot access the database any more, despite having disconnected from it in DBeaver. I have to exit DBeaver and only then is MyApp able to connect to `mydb.mv.db` again. Is DBeaver not terminating some connections properly by any chance?

Any insight is greatly appreciated! :slightly_smiling_face:

**Comment by serge-rider** [comment]
Good point. By default H2 shutdowns db engine only on VM exit.
To make explicit shutdown we need to execute query `SHUTDOWN` before closing connection.
Will add this feature in the next version.
