### ISSUE TITLE
Dbeaver: SQL Autocomplete broken

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#4718]
DBeaver - Version 5.2.5 CE
Operating System: Windows 10
JDBC Driver: mssql-jdbc 7.0.0.jre10
Database: Microsoft SQL Server Database

@serge-rider I recently clean installed the latest version on Dbeaver and my SQL Autocomplete is broken.
Below is the image of SQL suggest after hitting CTRL+SPACE. I tried numerous scenarios but i still see this issue. Can you please check ?

![image](https://user-images.githubusercontent.com/38669892/49233627-03536b80-f3bc-11e8-9c7f-467b6be0b3e5.png)

**Comment by serge-rider** [comment]
Thanks for the bug report
