### ISSUE TITLE
Generate SQL bug when column contains text and the content of the row is a URL

### ISSUE THREAD

**Issue by xantari** [dbeaver/dbeaver#4720]
When right clicking a row from SQL Server and hitting Generate SQL, and selecting "INSERT" as the SQL to generate it generates the SQL Insert statement.

However columns which have a string in it with a URL get extra quotes added.

Example:
```
Table
ColA                   ColB
1                         https://www.keelio.com
```
When generating the INSERT statement it will generate the following:

INSERT INTO MyDatabase.dbo.Table
(ColA, ColB)
VALUES(1, '''https://www.keelio.com''');

Notice the extra quotes.

Expected output:

INSERT INTO MyDatabase.dbo.Table
(ColA, ColB)
VALUES(1, 'https://www.keelio.com');

**Comment by serge-rider** [comment]
What is your database?

**Comment by xantari** [comment]
SQL Server 2017

**Comment by serge-rider** [comment]
Could you send table DDL? IO'm sure this issue happens only with certain data types.

**Comment by serge-rider** [comment]
Can't reproduce anymore. Please reopen if it still happens in your environment.
