### ISSUE TITLE
Oracle SQL Can't run bulk queries

### ISSUE THREAD

**Issue by dariopnc** [dbeaver/dbeaver#4721]
DBeaver 5.2.5.201811181655
Windows 10

Running the following query (select all and then Run query)
```
UPDATE table SET field = 1 WHERE ROW_ID = '1'
UPDATE table SET field = 1 WHERE ROW_ID = '2'
```
I get the error
```
Query execution failed

Reason:
Errore SQL [933] [42000]: ORA-00933: SQL command not properly ended
```
Due to the missing semicolon at the end of first row, this is the same behaviour as SQLDeveloper.

Doing the same adding semicolon after every line I instead get this other error
```
Query execution failed

Reason:
Errore SQL [911] [22019]: ORA-00911: invalid character
```
This is unexpected and prevents me from running bulk queries like this. Was able to reproduce only with updates, I think it may still happen with inserts.

Running bulk queries is pretty usual when you generate them concatenating data from tables

**Comment by p91paul** [comment]
you can also separate queries with empty lines, as long as you execute any of them alone.

If you want to execute many statements, then separate them with ; and use the execute script command (alt+x shortcut), pretty sure it works on 5.2.5!

**Comment by dariopnc** [comment]
that's a workaround, but it needs an empty SQL Editor tab, which is not always practical

executing them one by one, with hundreds of updates...

**Comment by p91paul** [comment]
I would not call it a workaround, it's just a different button for single versus batch execution! you don't need an empty sql editor...if you need to execute only a few of them you just need to select the portion of the script you want to execute!

Coming from sqldeveloper you should be familiar with this behavior, there you would use F5 to execute a script or a portion of it, here it's alt+x (you can change shortcuts in settings if you don't like them)
