### ISSUE TITLE
Black tips in 5.2.5

### ISSUE THREAD

**Issue by Crutchmaster** [dbeaver/dbeaver#4722]
![default](https://user-images.githubusercontent.com/13776084/49267953-6cf07a00-f48f-11e8-89ee-930af8ad49f9.png)

**Comment by uslss** [comment]
There is no update on the ticket for more than a year.
Ticket is closed.
If the issue is still reproducible for you - feel free to reopen the ticket and add some details that could help to reproduce the issue or create the new one.
