### ISSUE TITLE
Invisible links in value panel

### ISSUE THREAD

**Issue by Crutchmaster** [dbeaver/dbeaver#4723]
![default](https://user-images.githubusercontent.com/13776084/49268057-dbcdd300-f48f-11e8-93bd-5c4b9090455d.png)

In older versions all be ok.

**Comment by serge-rider** [comment]
Can't reproduce.
What is your OS/window manager?

**Comment by Crutchmaster** [comment]
>What is your OS/window manager?
Linux mint 17.3/Xfce+compiz
>Can't reproduce
Understand. I try to do something with it.

**Comment by serge-rider** [comment]
> Understand. I try to do something with it.

Does window resize or theme change (Preferences->General->Appearance) affect this?

**Comment by Crutchmaster** [comment]
>Does window resize or theme change (Preferences->General->Appearance) affect this?

Yes! In dark all ok.

**Comment by serge-rider** [comment]
It is not that easy to change some individual color for theme although you caoudl try to change it in Preferences->Appearance.

You can install DarkestDark theme (https://github.com/dbeaver/dbeaver/wiki/Eclipse-extensions) or some other customized theme. They are quite good-looking.
