### ISSUE TITLE
DBeaver does not work with proxy.pac file

### ISSUE THREAD

**Issue by flanneljeans** [dbeaver/dbeaver#4725]
I work in a company that has a very large and complicated proxy.pac file, which can change almost on a daily basis.

Currently, I have to download the latest version of the proxy.pac file, then figure out which proxy I would use, and enter that into the proxy field for DBeaver.

It would make my life much easier if I could simply supply the proxy.pac file to DBeaver, and have it figure out how to setup the proxy.

**Comment by flanneljeans** [comment]
Another thought is to have DBeaver optionally use what is setup for the OS or browser. Maybe this way is easier?

**Comment by serge-rider** [comment]
Do you mean HTTP(S) proxy for drivers/artifacts download? 
Or SOCKS proxy for database connections?

Generally that would be great to have some automation here but I'm not aware about any standard proxy configuration formats/systems.

**Comment by serge-rider** [comment]
Will be implemented in #6281
