### ISSUE TITLE
script editor uppercases quoted word

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4726]
```sql
SELECT * FROM "ORDER" o
LEFT JOIN agreement a ON a.id = o.agreement_id
ORDER BY a.id
```

The order is reserved word, but in my case it is quoted.

Do not uppercase quoted words

type `"order`+<kbd>"</kbd> will result `"ORDER"` instead of `"order"`

**Comment by serge-rider** [comment]
Thanks for the bug report
