### ISSUE TITLE
Lack of arrows, can not scroll by one row

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4727]
![__](https://user-images.githubusercontent.com/799021/49340917-d1a60300-f64e-11e8-9383-24a3a3061f80.jpg)

this is significant when many rows returned and one scroll event scroll many rows instead of one.

Linux Mint 18.3

**Comment by serge-rider** [comment]
You can use row scroll buttons (bottom toolbar), e.g. <kbd>ctrlk+alt+right</kbd>

**Comment by KES777** [comment]
> You can use row scroll buttons (bottom toolbar), e.g. ctrl+alt+right

this hotkey is used by system to switch between workplaces

**Comment by serge-rider** [comment]
You can redefine it in preferences->keys
