### ISSUE TITLE
[Feature request] Open CLOB value in external viewer/editor

### ISSUE THREAD

**Issue by rojares** [dbeaver/dbeaver#4729]
Now you can view common image files inside DBeaver when editing table data. You can open/save the binary data from/to filesystem. What would be very useful is the ability to open a CLOB value in external editor. For example storing pdf files into database would become convenient because the user could open the value in a pdf reader to check the contents of the value. Opening in external editor would require only opening a "virtual file" (binary stream) in the underlying OS. Possibly DBeaver could store the binary contents in temp file. And then the user could choose which program should open that file.

**Comment by serge-rider** [comment]
Agreed. However the main problem is determining file type. We can open CLOBs as txt files but any binary format will require some format detection.
We could try to utilize new Java function Files.probeContentType. Although it knows not that many formats.

**Comment by Rami-Ojares** [comment]
How about trying to open the CLOB as some generic mime type like application/octet-stream? Maybe this would open os specific dialog where the user can choose which program should open the file. Of course Files.probeContentType should be tried first.

**Comment by halitanildonmez** [comment]
I am working on this but have a question: how do you want to open the file ? From where I mean. What I am doing now is I have created a blob, added a pdf file and trying to open the file from table data view

**Comment by rojares** [comment]
1. If value is number, varchar etc. it is shown inline as text
![image](https://user-images.githubusercontent.com/5603146/86776546-f64f3180-c060-11ea-9776-f7d1774ffc45.png)
2. If value is blob in image format, dbeaver recognizes it automatically, and shows it as an image inline
![image](https://user-images.githubusercontent.com/5603146/86776181-abcdb500-c060-11ea-8014-bdcf6b7a318b.png)
3. If value is blob in pdf format then by default value is shown as text
![image](https://user-images.githubusercontent.com/5603146/86776726-1aab0e00-c061-11ea-87b9-ca3654feb887.png)
4. You can select from "Content viewer settings" to show the value in Binary
![image](https://user-images.githubusercontent.com/5603146/86776959-4c23d980-c061-11ea-9ece-55e1ac5800c2.png)
5. So maybe you could add next to it a new button "Open in external program". Clicking this would then open the value in an external program. In order to find the right kind of program we would have to ask the operating system using a mime type that which program it recommends. The user could choose the recommended program or some other program. If recommended program does not exist then the user would have to choose some program.
The dialog shown to the user could be something like this.
![image](https://user-images.githubusercontent.com/5603146/86777649-192e1580-c062-11ea-945c-ed22cb1489dd.png)

**Comment by halitanildonmez** [comment]
Got it! Will do

**Comment by halitanildonmez** [comment]
https://github.com/dbeaver/dbeaver/pull/9234

There is a pull request. I am not sure if the code will be acceptable yet I can fix the errors. 

The button is next to the "Content viewer settings" button. 

Maybe @rojares you can test it out and give feedback ?

**Comment by sachinmukherjee** [comment]
Is this issue open?

**Comment by serge-rider** [comment]
PR has been merged, feature will be included in 7.2.1

**Comment by kseniiaguzeeva** [comment]
Implemented

**Comment by timharsch** [comment]
Is this feature in the community edition?  I would like to view CLOBs as PDFs
