### ISSUE TITLE
Extremely slow on Oracle Docker container

### ISSUE THREAD

**Issue by drez769** [dbeaver/dbeaver#4730]
I have 2 Oracle dbs set up: 1 someone set up on a Windows server that works fine, and another I just set up on Linux [in a Docker container](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance) that is extremely slow, especially on first query, something like 10 mins+. If I expand schemas menu the progress just gets stuck on "Load SchemaCache" 0% for a long time. Once it completes, other queries execute normally but still a bit slow (like 10 seconds to expand tables for a schema).

I can use SqlDeveloper to access the database fine. Any idea what's wrong?

**Comment by serge-rider** [comment]
You could try to play with Oracle connection settings:
![image](https://user-images.githubusercontent.com/6398845/49406708-64d25c00-f767-11e8-8abc-69ef7b35edc9.png)

Select empty schemas and DBA* settings may significantly affect performance.

**Comment by serge-rider** [comment]
Ok.
Could you check what actual query causes this:
- Open Query Manager view (main menu Window->Show View->Query Manager)
- Enable all object types and all query types in filter settings
- See what queries take too much time

Most likely it is something in tables metadata. You can disable metadata queries (globally or for this particular connections): 
![image](https://user-images.githubusercontent.com/6398845/49426027-4e9cbe00-f7b0-11e8-92cb-8808b59846c1.png)

**Comment by drez769** [comment]
Thanks, it's definitely the metadata queries.

![image](https://user-images.githubusercontent.com/7621950/49451862-1300f480-f7ae-11e8-82ba-3516f405406b.png)
`SELECT U.* FROM SYS.ALL_USERS U
WHERE (U.USERNAME IN (SELECT DISTINCT OWNER FROM SYS.ALL_OBJECTS))` took **20 minutes**.

It's weird because after multiple attempts it gets much faster, like it's cached. It should be noted that this is occurring once I initially create the oracle docker container without even adding any data. I'm not sure it gets nearly that slow again after the first super slow queries. Also, this database automatically uses [Oracle's CDB/PDB architecture ](https://docs.oracle.com/database/121/CNCPT/cdbovrvw.htm) while the other Oracle database I've had no issues with is older non-CDB.

I'll keep monitoring it and messing with the settings to see if I can get decent performance. If you have any other tips/recommendations please let me know. Thanks a lot! 😃

**Comment by serge-rider** [comment]
Turning off option "Hide empty schemas" should significantly increase performance (it won't join ALL_USERS with ALL_OBJECTS).
Also, if you have too many users (I saw databases where number of users was about 100k) then you could use schema filters.

**Comment by drez769** [comment]
"Hide empty schemas" seems to have caused the issue! After creating a blank new Oracle Docker container again and testing initial queries with it off, it's working much better. I haven't created any other users btw, just default Oracle setup. Maybe "Hide empty schemas" should be off by default??

**Comment by serge-rider** [comment]
Not sure about that. In Oracle every user is a schema. Many production databases have hundreds or even thousands of schemas.
For now your issue seems to be more rare (in any case 20 minutes for schemas reading is a nonsense).

**Comment by drez769** [comment]
Unless databases usually have many empty schemas, I would still think it should be off by default to help performance? Anyways, I'm sure you know best. I will continue testing the database with actual data in it now. So far performance seems ok. Thanks for all your help! I recommend making [your contribution page](https://dbeaver.io/contribution/) easier to find from the main site, I'd like to donate to an awesome free tool 😃

**Comment by claudineim** [comment]
I have the same problem.
when I installed Dbeaver it was very fast, but with the passage of time began to be extremely slow with Oracle.
Disabling the "Hide empty schemas" option has improved somewhat, but it is still too slow to load diagrams and relationships, and sometimes to run simple queries as well.

**Comment by serge-rider** [comment]
@claudineim you could also disable `RULE hint` option - sometimes it affects performance very significantly.
In the worst case you can disable metadata reading for queries (see screenshot above)

**Comment by claudineim** [comment]
what was de solution for this issue ?

**Comment by serge-rider** [comment]
@claudineim You can hide empty schemas (see @be-rock comment).
If it doesn't help in your case - please provide more details (or better - create a new ticket)
