### ISSUE TITLE
Trigger processing broken in 5.2.5; worked in 5.2.4

### ISSUE THREAD

**Issue by lhartzman** [dbeaver/dbeaver#4732]
When trying to save a trigger to MySQL, I get a syntax error message. This same trigger worked fine in 5.2.4. Went to a mysql command line to submit the trigger to see if it was in error - it wasn't and was processed.

The alleged syntax error was at or around the 6th line:
```    IF @test THEN
        SELECT NEW.test_code INTO @testCode;
        SELECT COUNT(*) FROM testing.test WHERE test_code = @testCode INTO @testCount;
        IF @testCount > 0 THEN
            SELECT name, test_term, test_term_type FROM testing.test WHERE promotion_code = @testCode INTO @name, @testTerm, @testTermType;
        ELSE
            SELECT '', '', '' INTO @name, @testTerm, @testTermType;
        END IF;
    ELSE
        SELECT '', '', '', '' INTO @testCode, @name, @testTerm, @testTermType;
    END IF;
```

**Comment by serge-rider** [comment]
Could you post full error message? I can't realize what exactly is broken.

**Comment by lhartzman** [comment]
Interesting. When I paste over the existing trigger with the same code, I get the pop-up asking to persist the trigger - and no error occurs.

When I go to an SQL editor window and put int the code (bracketed by `delimiter $$` and `delimiter ;`), I get the following error:

```Error occurred during SQL script execution

Reason:
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 21```

`line 21` corresponds to the 6th line above..

**Comment by serge-rider** [comment]
Perhaps the problem is in DBeaver SQL parser. It parses only first part of query (till first `END IF;`).

Workaround: select query and execute it with <kbd>ctrl+enter</kbd>.

**Comment by lhartzman** [comment]
Nothing happens. When I select the whole trigger definition and hit crtl+enter, I get no response of any kind. Doing a refresh shows that nothing executed.

**Comment by serge-rider** [comment]
Do you execute it in a SQL editor or in trigger editor? You need to do this in SQL editor.

**Comment by lhartzman** [comment]
In the SQL editor.

**Comment by serge-rider** [comment]
That's weird. So nothing happens if you run it with ctrl+enter or by clicking on "Execute SQL Statement" button?
No any errors?
Maybe something is in error/debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by serge-rider** [comment]
I'm a bit lost now.
So, you can't execute this trigger DDL in SQL editor at all?
Then when/where do you see that error about incorrect syntax?

Does saving trigger in trigger editor work ok?

**Comment by lhartzman** [comment]
right. i can't execute the trigger code in the sql editor at all without getting an error i mentioned above.

the button to create a new trigger is disabled (triggers->view triggers). i had to go to a mysql command line to create the trigger. once created i can edit it in dbeaver.

**Comment by serge-rider** [comment]
Still not very clear. If it fails with an error then you still can execute it but with error (it is not like "nothing happens"). IF so then yo u should be able to select it before execute.

Could you post your trigger source code (full, with header/footer)?
Or maybe some short gif video?

**Comment by lhartzman** [comment]
![trigger_creation_error](https://user-images.githubusercontent.com/2001645/49550352-255b5b00-f8a0-11e8-8ef5-ee105a1d2ee0.gif)

**Comment by lhartzman** [comment]
that doesn't work either:

![trigger_creation_error2](https://user-images.githubusercontent.com/2001645/49755467-92d70500-fc6d-11e8-8dc4-9f05f7cf6554.gif)

**Comment by p91paul** [comment]
I see it now...try removing the "delimiter" statement.
You must select from CREATE to END and execute with play.

If you have many statements in your script and you use "delimiter" syntax to separate them, I believe you are out of luck. Dbeaver can execute scripts with a single delimiter (defaults to ; but can be configured, I believe per connection) with the execute script button...however it will fail if the statement contains the delimiter itself. In that case you need to execute single statements with the execute statement, but this is painful if you have many statements.

**Comment by lhartzman** [comment]
Yes! I thought I had. Thanks for the help on this. Is there a reason that the trigger view has the create new trigger icon disabled?
