### ISSUE TITLE
How see the value of text fields in SQL Server

### ISSUE THREAD

**Issue by antoniogarcia78** [dbeaver/dbeaver#4734]
In the new version 5.2.5 i cannot see the value of text field. I see [ClobImpl] as value.
That's not happen in previous versions.
Maybe is a little configuration change but i never touch anything

**Comment by p91paul** [comment]
#4656

**Comment by antoniogarcia78** [comment]
Thank you @p91paul 
I try download an use old drivers version but nothing work.
Now i use the 5.24. All it's working
