### ISSUE TITLE
Formatting of UPDATE Statement

### ISSUE THREAD

**Issue by lasmaty07** [dbeaver/dbeaver#4735]
When applying the "Format SQL" command, the Update statements gets formatted the wrong way.

The following text
`UPDATE TABLE1 SET FIELD = '123' WHERE 1 = 2;`

gets formatted this way.
```
UPDATE
	TABLE1 SET
		FIELD = '123'
	WHERE
		1 = 2;
```
but following the internal formatter logic should be (much more usefull):
```
UPDATE
	TABLE1 
SET
	FIELD = '123'
WHERE
	1 = 2;
```

**Comment by serge-rider** [comment]
Good point. Thanks for noticing
