### ISSUE TITLE
"Reroute" feature in diagram

### ISSUE THREAD

**Issue by Laro88** [dbeaver/dbeaver#4736]
I lack the feature of "reouting" the connections in an ER diagram. I am currently using DBeaver to make a bit of sense in a postgres database that has some unfortunate issues. It is +60 tables so I am juggling them around manually.
Basically I just need a refresh of the fp-pk dashed lines.
Keep up the good work.

**Comment by serge-rider** [comment]
There are two refresh buttons in the bottom toolbar: "Arrange Diagram" and "Refresh Diagram". The difference is that refresh will reload objects metadata from database.
