### ISSUE TITLE
PostgreSQL view column comments not in DDL

### ISSUE THREAD

**Issue by cpburnz** [dbeaver/dbeaver#4737]
In PostgreSQL when looking at a view's properties under the "Columns" tab, you can see the comment for columns under the "Comment" column. However, when you look at the view's DDL under the "Source" tab, the SQL for the column comments are missing.

I tested on both PostgreSQL 9.1 and 10 with DBeaver 5.2.5.201811181655 using the PostgreSQL driver running on Ubuntu 18.04.

I created a test table and view with:

```sql
CREATE TABLE test_table (
	id integer NOT NULL
);

CREATE VIEW test_view AS 
SELECT id
FROM test_table;

COMMENT ON VIEW test_view IS 'The view comment.';

COMMENT ON COLUMN test_view.id IS 'The column comment.';
```

The *id* column's comment properly showed under the "Columns" tab. It is not present in the DDL under the "Source" tab:

```sql
CREATE OR REPLACE VIEW public.test_view
AS SELECT test_table.id
   FROM test_table;

COMMENT ON VIEW public.test_view IS 'The view comment.';

-- Permissions

ALTER TABLE public.test_view OWNER TO postgres;
GRANT ALL ON TABLE public.test_view TO postgres;

```

I expected to see a:

```sql
COMMENT ON COLUMN public.test_view.id IS 'The column comment.';
```

**Comment by lemon-juice** [comment]
I see the same problem on Postgres 9.6.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by ruizanthony** [comment]
In DBEAVER version 7.1.5, this bug is still present.

We like to use the comment feature, it's not convenient to have to carefully check whether the comments will be gone each time we recreate a table using DDL tab.

**Comment by Moridin11** [comment]
I still see this problem in version 22.0.5.

**Comment by Iveky** [comment]
In version 22.3.5 there are comments in Source tab if you switch on 'show comments' flag belowe ddl text window
