### ISSUE TITLE
Query timer starting early?

### ISSUE THREAD

**Issue by bobf32** [dbeaver/dbeaver#4739]
Dbeaver 5.2.5: When executing a query with a bind variable, the 'Initializing' timer popup appears as soon as the window prompting for the variable value appears. Once the variable value is set the timer text changes to 'Execute query'. I feel this tends to give a misleading impression of how long the query is acutally running for.

![image](https://user-images.githubusercontent.com/6544564/49502678-7c940800-f86d-11e8-84ee-12dc450e6086.png)

**Comment by serge-rider** [comment]
Thanks for the bug report
