### ISSUE TITLE
Can't connect to SQL Server via SSH tunnel on different server

### ISSUE THREAD

**Issue by mscha** [dbeaver/dbeaver#4741]
I'm trying to connect to a Microsoft SQL Server `foo.example.com`, via an ssh tunnel on server `bar.example.org`.  (`foo.example.com` is access-restricted, and `bar.example.org` is on its whitelist.)
The tunnel is working (“Test tunnel configuration” says it's fine).  Without the ssh tunnel, the database connection is working (if I'm connecting from a whitelisted location).  But when connecting to the database via the tunnel, the connection fails: `Cannot open server "127.0.0.1" requested by the login.`

Why is it using `127.0.0.1` and not `foo.example.com`?  Is there any way to override this “helpful” behaviour?

This is on DBeaver 5.2.5 on Windows 10.

**Comment by serge-rider** [comment]
This seems to be SQL Server driver specific behavior. 
https://social.msdn.microsoft.com/Forums/en-US/c8c3f3b9-0f1d-4abb-a4b9-1e24b7b695d4/unable-to-connect-to-sql-serverservice-version-using-a-tunnel?forum=ssdsgetstarted

**Comment by uslss** [comment]
There is no any update almost a year.
Ticket is closed.
If you have any other questions - feel free to create new tickets

**Comment by sitanshuforever** [comment]
use username as:
username@yourdb.database.windows.net

It should work.

**Comment by brian-toan-topdrill** [comment]
> use username as: [username@yourdb.database.windows.net](mailto:username@yourdb.database.windows.net)
> 
> It should work.

I'm connecting to a SQL Server DB via SSH tunnel using DBeaver. Details:
Host: `mydb.database.windows.net`
Database: `mybackupdb`
Authentication: SQL Server Authentication
Username: `myuser`
Password: `mypassword`

With this configuration, I run into the same error as the issue creator. When I change my username to `myuser@mydb.database.windows.net`, a new error pops up:
```
Cannot open server 'mydb' requested by the login. Client with IP address '<myLocalMachinePublicIP>' is not allowed to access the server.  To enable access, use the Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.  It may take up to five minutes for this change to take effect.
```

`<myLocalMachinePublicIP>` is the public IP of my current machine, not the IP of the SSH tunnel. So it means somehow doing this, DBeaver is connecting to the DB instance from my machine again, while it's supposed to connect through the SSH tunnel. Not sure why.
