### ISSUE TITLE
runs in TOAD not in DBEAVER (Db2 on AIX server)

### ISSUE THREAD

**Issue by aranapatona** [dbeaver/dbeaver#4742]
I get the following error when trying to run this from within dveaber editor:
SQL Error [42601]: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=);atnr = myquery.idnrk;), DRIVER=4.19.66
  DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=);atnr = myquery.idnrk;), DRIVER=4.19.66
  DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=);atnr = myquery.idnrk;), DRIVER=4.19.66
    DB2 SQL Error: SQLCODE=-727, SQLSTATE=56098, SQLERRMC=2;-104;42601;)|atnr = myquery.idnrk|), DRIVER=4.19.66

if I run other queries i have no problem, when i run this from within TOAD DB2 it runs as expected, also when I run it from a .net APP using OLEDB it runs fine.

`WITH myquery(
       posnr,
       root,
       matnr,
       bom_tree,
       lvl,
--       parent_stlkn,
       stlkn,
       idnrk,
       meins,
       menge
        )
     AS (SELECT p.posnr, 
     m.matnr root,
                m.matnr,
                CAST (  m.matnr|| '---' || p.idnrk as varchar(200))  bom_tree,
                1 ,
--                p.stlkn,
                p.stlkn,
                p.idnrk,
                p.meins,
                p.menge
           FROM sapr3.mast m
                JOIN sapr3.stko k ON k.stlnr = m.stlnr
                JOIN sapr3.stpo p ON p.stlnr = k.stlnr
          WHERE m.matnr = 'AV2014'
       
         UNION ALL
         
         select myquery.posnr,myquery.root,z.matnr,cast(myquery.bom_tree || '---' ||  z.idnrk as varchar(200)) bom_tree ,myquery.lvl+1,z.stlkn,z.idnrk,z.meins,z.menge from
         (
         SELECT p.posnr,
                m.matnr,
                p.stlkn,
                p.idnrk,
                p.meins, p.menge
           FROM sapr3.mast m
                JOIN sapr3.stko k ON k.stlnr = m.stlnr
                JOIN sapr3.stpo p ON p.stlnr = k.stlnr) z
                ,
                myquery
          WHERE z.matnr = myquery.idnrk)

select b.*,
--m.PEINH price_unit,
r.meins buom,
--m.stprs base_price,
d.maktx desc,
r.matkl group
, case
   when r.meins=b.uom then m.lplpr/m.peinh --m.stprs
  else
        m.lplpr/m.peinh/1000
  end as comp_price
, case
   when r.meins=b.uom then m.lplpr/m.peinh*b.qpa  --m.stprs*b.qpa
  else
      m.lplpr/m.peinh/1000*b.qpa
      --m.stprs/m.peinh*b.qpa    
  end as qpaprice
  
from  
  (
  SELECT 
  
  
         posnr,
         root,
         myquery.matnr Parent,
         lvl,
         --stlkn,
         idnrk Component,
         meins UOM,
         menge QPA,
         sapr3.marc.herkl country,
         bom_tree

    FROM myquery,sapr3.marc
    where 
         myquery.idnrk=sapr3.marc.matnr
    and sapr3.marc.werks='1850'
--ORDER BY 
--posnr,bom_tree
) b join  sapr3.mbew m on b.component=m.MATNR
    join sapr3.makt d on d.matnr=m.matnr
    join sapr3.mara r on d.matnr=r.matnr
    
union

SELECT       '0000' posnr,
              m.matnr root,
              '---' PARENT,
              0 LVL,
              '' component,
                m.meins uom,
                1 QPA,
                marc.herkl country,
                --  menge,
                
              '---'  bom_tree,
              m.meins buom,
              makt.maktx DESC, 
              g.matkl group,
  --              p.stlkn,
              mb.lplpr cost,
              --mb.peinh  perunit,
              mb.lplpr-mb.peinh QPAPRICE
              --stprs unitprice
              --/1000,
                --p.meins,

           FROM sapr3.mara m
           join sapr3.marc on m.matnr=marc.matnr
           join makt on m.matnr=makt.matnr
           join sapr3.mara g on m.matnr=g.matnr
           join sapr3.mbew mb on m.matnr=mb.matnr
                --JOIN sapr3.stko k ON k.stlnr = m.stlnr
                --JOIN sapr3.stpo p ON p.stlnr = k.stlnr
          WHERE m.matnr = 'AV2014' and marc.werks=1850 and mb.bwkey=1850
          ORDER BY 
posnr,bom_tree;`

**Comment by titou10titou10** [comment]
Could you try to rerun your query after having removed the comments line in the middle of the query, ie the lines starting with "--"

**Comment by aranapatona** [comment]
Yes I figured they might be interfering, so I tried that as well, and same thing happened.

**Comment by aranapatona** [comment]
If this shows any light to the issue let me tell you same error shows within squirrelsql, so this might have to do with jdbc more than with dveaber, is it anyway to run the script directly (direct mode or bypass any parsing mode?)

**Comment by titou10titou10** [comment]
Are you using the latest JDBC driver (Currently  v4.21.29) ? 
Get the driver here: http://www-01.ibm.com/support/docview.wss?uid=swg21363866
Are you using the JDBC 4 or JDBC 3 driver? DBeaver needs JDBC 4.

**Comment by aranapatona** [comment]
using jdbc 4, squirrel uses the same db2jcc4.jar, and no i am no using the latest one, 
I removed a semicolon that I accidentally entered during original posting, now the error says the same, but 2 lines instead of 3.
was using 4.19.66 as shown in the OP, I just tried with new driver but same results.
 
SQL Error [42601]: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=);atnr = myquery.idnrk;), DRIVER=4.21.29
  DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=);atnr = myquery.idnrk;), DRIVER=4.21.29
  DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=);atnr = myquery.idnrk;), DRIVER=4.21.29
    DB2 SQL Error: SQLCODE=-727, SQLSTATE=56098, SQLERRMC=2;-104;42601;)|atnr = myquery.idnrk|), DRIVER=4.21.29

**Comment by aranapatona** [comment]
here is a screenshot https://i.imgur.com/nad6m8L.png

with same query running (toad does not use jdbc), I use the same one under a .net app, I dont know where is the problem since a derived version of the same query does run fine using dbeaver

**Comment by aranapatona** [comment]
This is solved and the problem was me being stupid , 

Was used to just pressing F9 or F5 (execute current statement and execute sql in TOAD), and it was smart to know when to run what, also had default schema settings, making the user (me) lazy and taking things for granted such as specifying schema names that were default to my editor but not to this new one, this cleared some problems but still not getting my expected results . 
Until I  run this with
EXECUTE SCRIPT
I was using EXECUTE SQL STATEMENT (the orange arrow) 
 
btw I thought the modified script would run in squirrel also, but I had to add lots more of schema and aliases so it didn't get confused), so for now, 
Tried many of my other scripts and even the ones having bind parameters worked flawlessly (need a plugin in squirrel for them to work)

I was looking for an alternative and for me the winner is DBEAVER (also way faster than squirrel don't know why but  may be because of metadata settings since both use same library)


Thank you for your support.
