### ISSUE TITLE
Generated insert from Data Transfer/Export resultset ignores "Data rows per statement"

### ISSUE THREAD

**Issue by braiam** [dbeaver/dbeaver#4751]
When exporting a resultset and defining SQL insert as the transfer type, in the Settings (third screen) there's an Exporter settings, in which one of the parameters is Data rows per statement, which, no matter the value, always generates one statement per row. I would expect that if set the value to >1, insert statements would have >1 rows worth of data per statement.

**Comment by serge-rider** [comment]
What is your database?
Most databases just doesn't support multi-row syntax - this option is ignored for them (perhaps we should disable it in UI for such databases).

**Comment by braiam** [comment]
The target database is MariaDB which does allow multi-row inserts.

**Comment by serge-rider** [comment]
Then I can't reproduce this. This is what data export (SQL format) generates for my test MariDB server:
```sql
INSERT INTO sakila.actor (first_name,last_name,last_update,data_name,time_name,Column1) VALUES 
('PENELOPE','GUINESS','2006-02-15 07:34:33.000',NULL,NULL,NULL)
,('NICK','WAHLBERG','2006-02-15 07:34:33.000',NULL,NULL,NULL)
,('ED','CHASE','2006-02-15 07:34:33.000',NULL,NULL,NULL)
,('JENNIFER','DAVIS','2006-02-15 07:34:38.000',NULL,NULL,NULL)
,('JOHNNY','LOLLOBRIGIDA','2006-02-15 07:34:33.000',NULL,NULL,NULL)
,('BETTE','NICHOLSON','2006-02-15 07:34:33.000',NULL,NULL,NULL)
,('GRACE','MOSTEL','2006-02-15 07:34:33.000',NULL,NULL,NULL)
,('MATTHEW','JOHANSSON','2006-02-15 07:34:33.000',NULL,NULL,NULL)
,('JOE','SWANK','2006-02-15 07:34:33.000',NULL,NULL,NULL)
,('CHRISTIAN','GABLE','2006-02-15 07:34:33.000',NULL,NULL,NULL)
```

Note: it is the configuration of source database.

**Comment by braiam** [comment]
@serge-rider When I read "Exporter settings" I expect the source to be irrelevant, or it's a misnomer of the window?
