### ISSUE TITLE
PostgreSQL table trigger comments not supported

### ISSUE THREAD

**Issue by cpburnz** [dbeaver/dbeaver#4752]
For PostgreSQL it appears that DBeaver does not know comments on table triggers exist.

I tested on both PostgreSQL 9.1 and 10 with DBeaver 5.2.5.201811181655 using the PostgreSQL driver running on Ubuntu 18.04.

I created a test table with a trigger with:

```sql
CREATE TABLE test_table (
	id integer NOT NULL
);

CREATE FUNCTION test_function() RETURNS trigger LANGUAGE plpgsql AS
$$
	BEGIN
	END;
$$;

CREATE TRIGGER test_trigger BEFORE INSERT ON test_table FOR ROW EXECUTE PROCEDURE test_function();

COMMENT ON TRIGGER test_trigger ON test_table IS 'The trigger comment.';
```

1. Under the table's "Triggers" tab there is no "Comment" column like there is for "Columns", "Constraints", etc.

2. The trigger comment does not appear under the table's "DDL" tab:

    ```sql
    -- Drop table

    -- DROP TABLE public.test_table

    CREATE TABLE public.test_table (
    	id int4 NOT NULL
    );

    -- Table Triggers

    create trigger test_trigger before insert on
    public.test_table for each row execute procedure test_function();

    -- Permissions

    ALTER TABLE public.test_table OWNER TO postgres;
    GRANT ALL ON TABLE public.test_table TO postgres;
    ```

    I expected to see a:

    ```sql
    COMMENT ON TRIGGER test_trigger ON public.test_table IS 'The trigger comment.';
    ```

3. Under the trigger's "Properties" tab there is no "Comment" field like there is for "Columns", "Constraints", etc.

4. The trigger comment does not appear in the trigger's DDL under its "Source" tab:

    ```sql
    create trigger test_trigger before insert on
    public.test_table for each row execute procedure test_function()
    ```

    I expected to see a:

    ```sql
    COMMENT ON TRIGGER test_trigger ON public.test_table IS 'The trigger comment.';
    ```

**Comment by serge-rider** [comment]
Good point.
