### ISSUE TITLE
SQL Server Table, Adding Comments to the Table Failing

### ISSUE THREAD

**Issue by dba0522** [dbeaver/dbeaver#4754]
I am building some tables and when I went to add a description to the table I get this error:

SQL Error [15135] [S1000]: Object is invalid. Extended properties are not permitted on 'wmi.SSIS_Email_Purge_Input', or the object does not exist.
  Object is invalid. Extended properties are not permitted on 'wmi.SSIS_Email_Purge_Input', or the object does not exist.
  Object is invalid. Extended properties are not permitted on 'wmi.SSIS_Email_Purge_Input', or the object does not exist.

I then copied the script that was generated:

EXEC CWSerenade.sys.sp_addextendedproperty 'MS_Description', 'Load and process table for the email purge process', 'user', 'wmi', 'table', 'SSIS_Email_Purge_Input' GO

I noticed that it had 'user' vs 'schema' in the parameters passed.   I put 'schema' in the parameter and manually ran, it completed successfully.

Looks like there is a bug...   The objects I am creating are associated to schema, there is no user named 'wmi'.

**Comment by dba0522** [comment]
NOTE:   Same issue applies to column descriptions.

**Comment by serge-rider** [comment]
Thanks for the bug report.
Although it worked on my SQL Server version find even with "user" object type. Perhaps this is very depends on server version.

**Comment by dba0522** [comment]
Sorry, new to this process.

I didn't see the commit info...

Thanks, have a great day!!!
