### ISSUE TITLE
Navigate Association fails on MySQL 8 with 'columns differ from referenced constraint'

### ISSUE THREAD

**Issue by DaPoco1986** [dbeaver/dbeaver#4768]
I use DBeaver Version 5.2.1
Mysql 8 under Manjaro Linux
I have 3 schemas containing the same database structure. When I want to use the 'navigate association' feature within a resultset I get following error:
Entity [xxx.branch] association [FK_TpResource_IsBranch] columns differs from referenced constraint [PRIMARY] (3<>1)

When I use a database having only one schema, it works.
I assume the resolver queries the database schema without filtering on the schema itself. So in my case, 3 TableReferences are found for the navigating column and DBeaver does not know which to chose.

**Comment by serge-rider** [comment]
I can't reproduce that. In fact DBeaver uses schema to search reference tables/keys.
I can't figure out how this coudl be possible (looks more like a corrupted schema).
Could you try to this on the latest DBeaver version?

**Comment by DaPoco1986** [comment]
So, I upgraded to the current version, but the error still exists.
Nevertheless I was able to narrow it down. I switched back to an older JDBC Driver (Version 5.1.47) and here it works! The Version I used before was 8.0.11, so I guess there is something wrong with that.

**Comment by serge-rider** [comment]
Ah, this is possible. DBeaver MySQL extension uses native JDBC driver functions to read foreign keys info. So this might be a bug in MySQL driver itself..

**Comment by DaPoco1986** [comment]
That is what I'm thinking. Thanks for your help, I will close this issue.

**Comment by Dimas-sc** [comment]
Same happens with MariaDB. Any solutions?
