### ISSUE TITLE
Support postgreSql results

### ISSUE THREAD

**Issue by levent1132** [dbeaver/dbeaver#4769]
hello, ı have issue about results,
ı want to see my results , witout dot or comma
how ı can make it ?
![untitled](https://user-images.githubusercontent.com/20375605/49738475-88822e80-fca0-11e8-859b-30700c678143.png)

**Comment by serge-rider** [comment]
Global settings:
![image](https://user-images.githubusercontent.com/6398845/49743576-25969480-fcac-11e8-800b-5a2221105151.png)
Also you may configure this for a particular connection in the connection properties dialog.

**Comment by levent1132** [comment]
@serge-rider  thank you so much , :)
