### ISSUE TITLE
Help: How to export a whole database to another database?

### ISSUE THREAD

**Issue by dbeaveroo** [dbeaver/dbeaver#4771]
Hello,

I am using Windows 10 and DBeaver Community 5.3.

Is it possible to export a whole database (e.g. MySQL) to another database (e.g. PostgreSQL)?

If possible, how to do it?

**Comment by serge-rider** [comment]
DBeaver supports individual tables data transfer from one database to another (see https://github.com/dbeaver/dbeaver/wiki/Data-transfer).

But it doesn't support exporting of whole database between different database systems.

**Comment by dbeaveroo** [comment]
I see. Thank you.
