### ISSUE TITLE
[Oracle] Export data as SQL uses unsupported syntax

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#4772]
Oracle does not support syntax with multiple tuples in `VALUES` clause (unfortunately). To make it work you can use `INSERT ALL` syntax:

``` sql
INSERT ALL
    INTO <target_table> VALUES (<single tuple>)
    INTO <target_table> VALUES (<single tuple>)
    ...
SELECT * FROM dual
```

That `SELECT` is needed because you need to generate exactly one row somehow.

**Comment by serge-rider** [comment]
To be Oracle compatible you can set parameter "Data rows per statement" to 1:
![image](https://user-images.githubusercontent.com/6398845/49807833-242ca100-fd6c-11e8-91fc-c27ef81562e4.png)
