### ISSUE TITLE
Graphical glitch when switching connection type

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#4773]
If I switch from a "Test" (green-colored) connection to a "Development" (white-colored) one, part of the grouping panel will stay with the previous color.

![immagine](https://user-images.githubusercontent.com/2157006/49746480-95535200-fca1-11e8-8349-6a80269ccabd.png)

**Comment by uslss** [comment]
Issue isn't reproducible anymore.
Ticket closed.
