### ISSUE TITLE
Error in "Open results in excel"

### ISSUE THREAD

**Issue by albare** [dbeaver/dbeaver#4780]
With  version 5.3.0 when I use the option "Open results in excel" with the plugging updated to the last version is a error:
invalid object name 'XXXXXXXX'  where XXXXXX is the name of the table.

I try a very simple select like "Select * from employes", the select show the results without problems, the error is only in open in excel.

I  revert to 5.2.4 and works again correctly

Edit: I found a solution, if I write the name of database prior the name of the table, works ok.
the name of database is not necesary for execute the "select" but is some error in excel export that can't recognice the active database.

Thank's

**Comment by serge-rider** [comment]
If you execute some "USE" statement in SQL editor to switch active db then such error may happen. Because "Open in Excel" operation opens new connection with default active database.

**Comment by albare** [comment]
No, I don't use "USE" stament, the database is the active.

The same in 5.2.4 that works ok.

the solution is "select * from Database.dbo.employes"

with "select * from employes"  "open in excel" say "invalid object name"

I select the active datasource and the active database in the fields of the toolbar.
(and for execution of select works ok, only error in open in excel)

**Comment by serge-rider** [comment]
Well, I assume this is somehow related to active database/schema selection in new connection but I can't realize what is the difference between SQL Editor's connection and Excel connection..

**Comment by albare** [comment]
I discovered when occurs. If in the connection settings is not set the Database/Schema, occurs the error in excel.
If I set this value the excel open ok.  (but this value is not necesary for execute a "select" statement.
(and database in use is set in the correspondent box)

Thanks

**Comment by serge-rider** [comment]
@albare Thanks for the information
