### ISSUE TITLE
MonetDB: Database Navigator does not show columns names and metadata since version 5.2.5

### ISSUE THREAD

**Issue by palmaresk8** [dbeaver/dbeaver#4782]
I use DBeaver to connect to MonetDB. Since I updated to DBeaver 5.2.5, the Database Navigator does not show columns names, even in the "Properties" tab. I tried DBeaver 5.3 and the issue is still there. If I reinstall DBeaver 5.2.4, everything works fine.

**Comment by serge-rider** [comment]
Unfortunately we don't have MonetDB driver config in DBeaver by default so I can't validate this. Most likely driver config is incorrect.

Some drivers do not support JDBC API properly, To handle this we added property "Escape LIKE masks in search queries" in some 5.2.x version:
![image](https://user-images.githubusercontent.com/6398845/49798239-db1c2300-fd52-11e8-9884-82b9140a4bf3.png)

I think that you need to disable this property for MonetDB driver.

If this will help - maybe you could share driver configuration? We'll add it in one of the next versions then.

**Comment by palmaresk8** [comment]
**Yes, that worked!**
Thanks a lot for the quick answer! I love DBeaver.

The driver configuration I use for MonetDB is this:

![2018-12-11_110112](https://user-images.githubusercontent.com/6098533/49802849-5242be80-fd35-11e8-8bf2-25ba33d9e6da.png)

To download/update the driver, I have to add `https://clojars.org/repo/` into the list of Maven repositories.

**Comment by serge-rider** [comment]
Thanks!
Did you try `monetdb:monetdb-jdbc-new` driver (it is in Maven Central)?

https://www.monetdb.org/downloads/Java-Experimental/

**Comment by palmaresk8** [comment]
Yes, I did. It didn't work. The official JDBC driver is in clojars.org repository or can be download directly in the site:
https://www.monetdb.org/downloads/Java/

I have to point out that there is two versions of MonetDB: the server version (which I use) and the embedded one, also known as MonetDBLite. I didn't manage to connect to MonetDBLite using the drivers located in Maven Central either, but I can ask the developers some help with this issue.
    Em terça-feira, 11 de dezembro de 2018 12:37:39 BRST, Serge Rider <notifications@github.com> escreveu:  
 
 
Thanks!
Did you try monetdb:monetdb-jdbc-new driver (it is in Maven Central)?

https://www.monetdb.org/downloads/Java-Experimental/

**Comment by serge-rider** [comment]
Ok, thanks for the info.
I'll add only the main driver for now.
If you will have a chance to test with MonetDBLite - please post the driver config (in a separate ticket if possible).
