### ISSUE TITLE
Exasol - BATCH BEGIN; BATCH END; 

### ISSUE THREAD

**Issue by JohnHeldBT** [dbeaver/dbeaver#4783]
Bug Report / Feature Request:

Currently (execute as script) BATCH BEGIN; … BATCH END; is not supported for the Exasol Plugin (Version: 5.2.5):

For reproduction:
```
batch begin;
	select 1;
batch end;
```

With the Exaplus client  1 is returned

With DBeaver (execute script) this results in the following error:
 SQL-Fehler [42000]: syntax error, unexpected BEGIN_, expecting ASSIGNMENT_OPERATOR_ or ':' [line 1, column 7] (Session: 1619556472307733847)
  syntax error, unexpected BEGIN_, expecting ASSIGNMENT_OPERATOR_ or ':' [line 1, column 7] (Session: 1619556472307733847)
  syntax error, unexpected BEGIN_, expecting ASSIGNMENT_OPERATOR_ or ':' [line 1, column 7] (Session: 1619556472307733847)

**Comment by Sargul** [comment]
batch begin
and 
batch end 
are not exasol commands but commands interpreted in EXAplus.

There is no equivalent to this in DBeaver

**Comment by JohnHeldBT** [comment]
OK - I understand. Thank You
