### ISSUE TITLE
PostgreSQL backup and restore not a default schema

### ISSUE THREAD

**Issue by ioros** [dbeaver/dbeaver#4784]
When I want create backup or restore not a default schema in postgresql 9.5, I received error:
pg_dump: No matching schemas were found
I think so, if the schema name around it '"\<schema name\>"' that so good. I try it the terminal and was good.

**Comment by serge-rider** [comment]
Can't reproduce. Please post screenshot of backup wizard or pg_dump command line + error message

**Comment by ioros** [comment]
![kepernyofoto 2018-12-22 - 19 29 48](https://user-images.githubusercontent.com/2162977/50377589-49e56000-0620-11e9-9d17-8dd455e4a294.png)

**Comment by ioros** [comment]
/usr/local/Cellar/postgresql@9.5/9.5.14/bin/pg_dump --format=c -n '"A1234"' --verbose --host=localhost --port=5432 --username=postgres databasename > ~/Desktop/dump.backup

this command works

**Comment by serge-rider** [comment]
Yep, you are right. Thanks for checking this.

**Comment by miguelschwindt** [comment]
This problem still exist on MacOs Catalina

![image](https://user-images.githubusercontent.com/1275255/69009153-7a697300-0931-11ea-9521-494b5f2e6be3.png)

**Comment by Ayxan1** [comment]
This problem still exist on Windows 10 Enterprise.

**Comment by serge-rider** [comment]
@Ayxan1 do you use the most recent dbeaver version (6.3.4)?

**Comment by Ayxan1** [comment]
yes 
![Screenshot (17)](https://user-images.githubusercontent.com/25384636/74540115-a7d9b300-4f58-11ea-8e24-adac85e01670.png)

**Comment by serge-rider** [comment]
@Ayxan1 please write more details then. What exactly error do you see, is pg_dump command line correct?

**Comment by Ayxan1** [comment]
![Screenshot (21)](https://user-images.githubusercontent.com/25384636/74586514-81bc1d80-5001-11ea-8421-f8311a4c16a1.png)

 There are multiple schemas in my database. I want to backup only one of my schemas from my database.

**Comment by dalvallana** [comment]
This is still an issue. I'm on MacOS Catalina, and I get the same error as @Ayxan1, I have several schemas so I get a `no matching tables were found` error, even when the query states the tables as `"my_schema".my_table`.

**Comment by miguelschwindt** [comment]
Me too Diego, so, what I did was took the script from de window and
executed in a shell in terminal, works fine, and then work in pg admin 4.
Regards,
Miguel
