### ISSUE TITLE
Add documentation for Visual Query Builder

### ISSUE THREAD

**Issue by joemcl** [dbeaver/dbeaver#4787]
Trying out the EE version. At https://dbeaver.com/features/ there's this -  
> Open you[r] existing SQL queries in visual mode, edit and save them – that’s easy

but there is no documentation for Visual Query Builder that I can find. And BTW, the wiki text search does not appear to work.

**Comment by serge-rider** [comment]
Good point. We'll publish it shortly.

**Comment by joemcl** [comment]
thanks @serge-rider !

**Comment by serge-rider** [comment]
https://github.com/dbeaver/dbeaver/wiki/Visual-Query-Builder

**Comment by joemcl** [comment]
@serge-rider just seeing this, thanks so much!
