### ISSUE TITLE
Add option to automatically select active database based on context?

### ISSUE THREAD

**Issue by zingaburga** [dbeaver/dbeaver#4792]
DBeaver's 'active database' option is a very manual option (must be explicitly invoked by the user) and it would be very convenient if DBeaver would just automatically figure out the appropriate active database based on context.  For example, if I'm editing a table, these edits should be performed under the table's database without me having to explicitly mark the appropriate database as active.  Similarly, if I open an SQL editor whilst looking at a table/database (i.e. what the active tab is displaying), it should automatically use that as the active database.

Another problem with the 'active database' option is that it's global to all open tables/editors for the connection.  It would be nice if each SQL/table/etc editor had its own active database attached, and remembered it, so that I don't have to constantly set the active database when, for example, editing tables from two databases.

Also, currently DBeaver's UI locks up if you manually set the active database whilst a query is running.  Ideally, a automatic contextual switch of active database would avoid such an issue.

I personally think this would be a nice option to have, if it could be added, as forgetting to change active databases is an easy mistake to make, and makes DBeaver easier to use.

Thanks for reading and thanks for DBeaver!

**Comment by alesc2000** [comment]
What happens if you have the same tables on multiple databases on same connection?

**Comment by serge-rider** [comment]
Basically if you have to work with two different databases all the time then I'd recommend to open two separate DBeaver connections.

But partially I afgree, current schema selector isn't very good, especially for databases like PostgreSQL where you can set both active database and active schema (currently only schema change is supported from the main toolbar, changing active database is more tricky).

We are going to improve schema selector dialog.

**Comment by zingaburga** [comment]
Thanks for the responses!

> What happens if you have the same tables on multiple databases on the same connection?

I'm not sure what you mean by that question?  By 'same', do you mean the same name, or some sort of alias to the same underlying data store?  
Either case, each tab having its own active database does help ensure you don't edit the wrong table accidentally, since the active database is attached to what you originally opened.

> Basically if you have to work with two different databases all the time then I'd recommend to open two separate DBeaver connections.

Do you mean, duplicate the connection configuration for each database?  I suppose it works, but doesn't really scale well unfortunately (plus the effort needed to manually duplicate configurations and being somewhat unwieldy in the interface).

**Comment by serge-rider** [comment]
@zingaburga Yes, I mean copy connection and change onyl database name. You don't need to do this manually, just use <kbd>CTRL+C</kbd> <kbd>CTRL+V</kbd> in navigator tree.

In fact in PostgreSQL different databases require different physical connections. This makes PostgreSQL a very special database. And having two different connections for different databases is not so weird as it would be in case of non-PostgreSQL database.

I'll improve active schema selector in the next version. This will make active database management a bit more convenient:
![image](https://user-images.githubusercontent.com/6398845/49960759-f9844900-ff21-11e8-858d-f49c8ff08ac3.png)

**Comment by zingaburga** [comment]
Thanks for the explanation!

That does work if there's only two databases, but if you have, say, 5 databases across 3 servers (dev/testing/prod), then you'd need to create 15 separate configurations.  And then if you have replicated databases, other project etc, you can see that this doesn't really scale well...  Also, the left panel becomes a little hard to navigate, since expanding each connection lists its databases, but you only care about one of them for each connection, and figuring out which can get confusing.

I'm using MySQL/MariaDB which doesn't have a notion of 'active schema', so my feature request here pertains to active databases.  I have replication set up on selected databases, hence having the active database set is very important, and, using DBeaver, I often find that I'm breaking replication because queries aren't being executed with the correct active database.  For example, if I open a table in a non-replicated database, edit a row and click Save, the replication slave will error out unless the correct active database was set before saving - a very easy mistake to make.  If DBeaver could automatically use the correct active database without any manual setting (which is possible because other management tools do this) it would be very useful I hope.

Thanks again for the responses!

**Comment by myjob** [comment]
I have the same issue: Various database connections open (Oracle, MSSQL, and a bunch of Postgres) and I have to spend too much effort of hitting CTRL-SHIFT-A (setting active) or CTRL 9 (associating my sql script with a particular DB). The error message and behavior I get are not so helpful. DBeaver is such a great productivity tool that I would wish to get better user experience on multi DB scenarios (IMHO,multi instances of DBeaver as suggested above is not good enough).

**Comment by GTGeek88** [comment]
I used to use PGAdmin, then I found DBeaver. I like it a lot better, especially over v4 of PGAdmin, which I hate. But one thing I miss from PGAdmin is that it would remember what database you last had marked as the active database and so the next time you started it there was no reselection necessary. I work with literally thousands of databases for the thousands of clients that the company I contract for has. But I'm generally always working in a dev DB just for my dev and testing, so having DBeaver remember what DB was last active would be nice.

**Comment by serge-rider** [comment]
Done. Behavior change can be tested in 6.3.4 Early Access version (https://dbeaver.io/files/ea)

**Comment by GTGeek88** [comment]
Thanks. Looking forward to the new and improved behavior.

**Comment by uslss** [comment]
verified

**Comment by GTGeek88** [comment]
Well, I'm not sure this has had the intended effect. I had asked that it remember the last active DB and reselect it the next time you open DBeaver. That is not happening (I just updated DBeaver this morning - 6.3.3.202001191557). I was wanting it to expand the server node and display the last DB you had active. Anyway, I did that myself and hit CTRL-SHIFT-A and it did not mark it as selected. And wasn't the ability to do that in a right menu or other menu somewhere? Don't see it now. After trying this a few times, I hit Refresh and then it seemed to select it (indicated by the bold-faced font). Then I tried a simple query: SELECT * FROM COMPANY and it said "relation company does not exist." Same thing if I right-click on the table in the tree and choose Read Data in SQL Console from the menu. This is with the database visibly marked as active (bold-faced). I have not run into this before. Making it pull from public.company did not help, either. Once, earlier, while testing this, the Read Data in SQL Console option pulled up data, but the Select * that I typed in did not. I think something is badly wrong here or you've somehow changed what I need to do to set the context for a query.

**Comment by serge-rider** [comment]
@GTGeek88 most of problems you described were fixed in this ticket. You can check EA version or wait till 6.3.4 release.

**Comment by GTGeek88** [comment]
Ok, thanks for the quick reply. Is that release expected next week?

**Comment by zingaburga** [comment]
I decided to take a look at this again.

Current behaviour is *much* better than it used to be, so thanks a lot for the change.  
Unfortunately, it seems like the correct database is selected only when opening SQL editor tabs, but not with database/table etc tabs.  In fact, I don't even get the option to select an active database from the dropdown at the top there, though it can be changed with the old "Set as default" (Ctrl+Shift+A) option.

This also affects SQL editors that are spawned from the tab, e.g. if I attempt to change a table's column, press Save and then 'Open Editor' on the SQL preview, the new SQL editor will inherit a potentially incorrect database.

What *should* happen is that opening a database/table tab automatically sets the associated database, similar to how SQL editor tabs work.  This fixes the spawned SQL editor issue, as well as database configurations which rely on the active database being set correctly (e.g. DB based replication).
