### ISSUE TITLE
DB2: Non-explicit error message when trying to connect with a user without Connect permission

### ISSUE THREAD

**Issue by yannickb85** [dbeaver/dbeaver#4795]
Using DBeaver v5.3.0, when I try to connect to a DB2 11 database with an existing user that does not have connect permissions, DBeaver displays the error message attached to this issue.

![capture](https://user-images.githubusercontent.com/14008113/49880473-3e14c500-fdfa-11e8-8116-f0f06a59c28a.PNG)

A more explicit error message of the underlying problem would help resolve the connection problem.

**Comment by serge-rider** [comment]
Is this DB2 LUW or z/OS or AS/400 ?

**Comment by yannickb85** [comment]
DB2 LUW

**Comment by serge-rider** [comment]
Can't reproduce anything like this. Looks very weird in fact. 

Could you send debug log (at least the part related to connection initiation) ?https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by yannickb85** [comment]
No errors appear in the Error Log view in DBeaver.
Nothing appears in the .log file

However, here is the relevant output from dbeaver-debug.log
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/2673007/dbeaver-debug.log)

Some more information:
BEAYA000 is the username I use to connect.

If my user is given the correct Connect permissions the error message does not appear and the connection is successful.

**Comment by serge-rider** [comment]
Unfortunately I can't fix this. 
Driver doesn't provide any information or hint (like error code or exception class) about this error. Its just a regular SQL exception with some message.
Very short message but this is always vendor-dependent.
