### ISSUE TITLE
how open  file :SECURITYDATA.FDB

### ISSUE THREAD

**Issue by hktalent** [dbeaver/dbeaver#4796]
how open  file :SECURITYDATA.FDB
IBM/AppScan Standard/SECURITYDATA.FDB

no user name ,no passwd
😀🤝
#3397
<img width="718" alt="image" src="https://user-images.githubusercontent.com/18223385/49884296-815d4b00-fe6f-11e8-80e7-0b5afaf6efac.png">

<img width="677" alt="image" src="https://user-images.githubusercontent.com/18223385/49884139-23c8fe80-fe6f-11e8-8808-210ee8723b7e.png">

**Comment by mrotteveel** [comment]
Tagging random other issues to attract attention is annoying, please don't do that. 

The problem is that you don't have a Firebird server running on port 3050. You either need to start it, or specify the right port if you have configured Firebird to run on another port.

**Comment by serge-rider** [comment]
Note: embedded FB mode is not supported by Jaybird driver. So you need a local FB server to work with this database.

**Comment by mrotteveel** [comment]
@serge-rider Jaybird itself does support embedded, but I don't know how to get that up and running with DBeaver (except maybe just adding the location with the native dependencies to the path environment variable).

**Comment by serge-rider** [comment]
@mrotteveel yep, I meant this. Generally if there is any "workthrough" for FB embedded driver config with Jaybird - then I could try to configure it in DBeaver and write some doc or even make proper driver config (we can include native artifacts in DBeaver driver configurations).
