### ISSUE TITLE
Can't create driver instance for Oracle

### ISSUE THREAD

**Issue by geneorama** [dbeaver/dbeaver#4798]
I'm getting the following error when attempting to connect to oracle in DBeaver 5.3.0.

https://github.com/dbeaver/dbeaver/blob/devel/CONTRIBUTING.md
![image](https://user-images.githubusercontent.com/1392068/49893563-58a66880-fe11-11e8-83c8-f73f1b91fee8.png)

I am able to connect with another language using other JDBC drivers, which are on my path. I'm also able to connect in Oracle SqlDeveloper. So, I know there are no issues with firewalls or authentication. 

When I try to create a new connection it won't let me finish, save the connection, or test the connection. When I click "finish" or "test connection".  There is no error, just nothing happens. 

So, I tried to click on "Edit Driver Settings" at which point an error came up saying that I was missing two files; orai18n.jar and xdb6.jar.  That window directed me to a download page where I downloaded additional jar files from oracle. I added those files to the libraries. 

First I added the two individual missing files, and that didn't fix the issue. 

Then I added a folder with more jars (from the odbc-full.tar.gz download), this also did not fix the issue.

This is what my edit settings looks like:

![image](https://user-images.githubusercontent.com/1392068/49893970-5b558d80-fe12-11e8-9509-63cdf91de7a9.png)

The suspicious thing to me is that when I click on "Classpath" it shows a value that I can't edit which is not pointing to the location of my installed .jar files. 

![image](https://user-images.githubusercontent.com/1392068/49894034-8cce5900-fe12-11e8-8eec-3e9a8abfc5f5.png)

**Comment by serge-rider** [comment]
You need to add individual jar files - but not whole folder. 
The main jar file is ojdbc6.jar (or ojdbc7.jar  or ojdbc8.jar). 

Classpath is your system configuration in most cases it doesn't contain anything useful.

**Comment by geneorama** [comment]
You're right, adding `odbc8.jar` solves the issue.

There are a few weird things, but the biggest issue is that the error message tells you that the wrong jar files are missing. 

This is the error message:

![image](https://user-images.githubusercontent.com/1392068/49895064-28f95f80-fe15-11e8-9aa2-b5cf52a906bf.png)

When I added the other two files it has no impact on solving the problem, but the error message goes away. When I add your file everything works. 

Thank you very much for solving this so quickly.

**Comment by Leufrasio25** [comment]
Estava com mesmo problema, após baixar o arquivo ojdbc8.jar, deu tudo certo...Thanks !!!

**Comment by glopez-dynata** [comment]
I'm getting this error: Error E/S: Invalid number format for port number
