### ISSUE TITLE
Datasource & catalog/schema popup windows automatically close when trying to resize

### ISSUE THREAD

**Issue by chriswatt** [dbeaver/dbeaver#4800]
dbeaver version: 5.3.0
OS: Ubuntu: 18.04

Steps to reproduce:
1. Open either the datasource window or catalog/schema window by clicking the dropdowns in the toolbar at the top
2. Try grab one of the edges of the window to resize
3. The window automatically closes

**Comment by serge-rider** [comment]
This is GTK issue similar to #3975
You could try to run dbeaver with parameter `--launcher.GTK_version 2` but it is very possible that some other UI glitches appear.
