### ISSUE TITLE
Query stuck sometimes

### ISSUE THREAD

**Issue by workguy66** [dbeaver/dbeaver#4801]
When I run a query in the SQL Editor, it runs forever.

I click cancel and I get this error

`java.lang.NullPointerException`

![selection_349](https://user-images.githubusercontent.com/12811206/49936080-442aa480-fed3-11e8-8741-731c7d6c41d4.png)

DBeaver version: 5.3.0.201812092025
OS: Ubuntu 14.04

**Comment by serge-rider** [comment]
Please post error and/or debug logs (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by workguy66** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/2675777/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Database connection died and all operations are failing (until auto-recovery or manual invalidation).
However there shouldn't be a NullPointerException anyway..
