### ISSUE TITLE
Data viewer: add "Open with" menu

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#4802]
It would be handy to have new sub menu "Open with".
Initially we'll add Excel, outlook and HTML formats there.

**Comment by serge-rider** [comment]
XLSX and HTML apps are ready. Extra formats can added easily.
Also some extra UI buttons/switchers can be added.

![image](https://user-images.githubusercontent.com/6398845/50423745-7391c780-086a-11e9-946a-4fea2e3ff234.png)

**Comment by iambudi** [comment]
On OSX version using latest release on 7 Jan 2019, i could not find the excel menu in Open With. Any additional step to enable it?

**Comment by serge-rider** [comment]
@iambudi If you are using DBeaver CE then you need to install Office extension

**Comment by iambudi** [comment]
Working perfectly after installing office extension. Thank you.
