### ISSUE TITLE
"Filter by column value" fails if column has alias set

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#4805]
I noticed a minor issue: 

If a column of a query has an alias set, and I try to set a filter on a result column in the data window, after selecting a value by double clicking it, DBeaver will throw a SQL error. **If I subsequently remove the alias, it works.** 

![afbeelding](https://user-images.githubusercontent.com/7635726/50041930-ba0e4780-005c-11e9-82dc-b630004aaf72.png)

![afbeelding](https://user-images.githubusercontent.com/7635726/50041936-ca262700-005c-11e9-85f5-89c5374b8497.png)

**Comment by p91paul** [comment]
This option is probably going to solve your issues. @serge-rider is there a reason it is not on by default?

![immagine](https://user-images.githubusercontent.com/2157006/50426485-abab0180-088e-11e9-89bc-566e75ee2047.png)

**Comment by mboeringa** [comment]
@serge-rider 
I can confirm that this solution of @p91paul works, no more SQL error after checking the subselect checkbox:

**Selecting filter:**
![afbeelding](https://user-images.githubusercontent.com/7635726/50427085-ace42a80-089e-11e9-8363-a03c6b74f3b9.png)

**Proper result without SQL error:**
![afbeelding](https://user-images.githubusercontent.com/7635726/50427089-c8e7cc00-089e-11e9-94ee-e5e5bda330ad.png)
