### ISSUE TITLE
Enhancement: "Expand/Collapse all" for indexes view

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#4806]
Even though DBeaver uses a collapsible structure for showing (multicolumn)indexes, there is no way to "Expand/Collapse all" on all indexes in one operation, so as to be able to see each and every indexed column for all indexes at once. It would be nice to see this in the right-click context menu:

![afbeelding](https://user-images.githubusercontent.com/7635726/50042126-f4c5af00-005f-11e9-850a-44ba32c596f4.png)

**Comment by serge-rider** [comment]
Good point

**Comment by serge-rider** [comment]
Expand/collapse actions are in the bottom toolbar (context menu is already too heavy).

**Comment by mboeringa** [comment]
I personally do not have issues with heavy context menu's, but your solution sounds fine. Thanks for considering and implementing this!
