### ISSUE TITLE
PostgreSQL Setting the interval type display

### ISSUE THREAD

**Issue by sgrinko** [dbeaver/dbeaver#4808]
Feature request

Прошу рассмотреть возможность настройки отображения типа Interval через custom настройки.
сейчас отображение выполняется так:
![default](https://user-images.githubusercontent.com/10084993/50050822-dcfd3200-0116-11e9-9de3-27aea2581cc3.png)
такой формат вывода очень длинен и занимает много места на экране.
Хотелось бы иметь возможность настройки отображения для этого типа данных для возможности вывода в виде:
![default](https://user-images.githubusercontent.com/10084993/50050855-b68bc680-0117-11e9-8034-f7bf70b1001b.png)

ENG

Please consider the ability to customize the display type Interval through custom settings.
Now the mapping is done like this:

![default](https://user-images.githubusercontent.com/10084993/50050822-dcfd3200-0116-11e9-9de3-27aea2581cc3.png)

This output format is very long and takes up a lot of space on the screen.
I would like to be able to customize the display for this data type to be output in the form:

![default](https://user-images.githubusercontent.com/10084993/50050855-b68bc680-0117-11e9-8034-f7bf70b1001b.png)

**Comment by lemon-juice** [comment]
I think this is a good request, current interval format is very verbose. It would be best if DBeaver displayed intervals in native format - if not possible for all databases then there could be an option is settings to display intervals in native format - just like such an option exists for date/time fields (actually, for me it would be sufficient if "Use native date/time' format applied to interval values, too).

Examples of native Postres interval values:

```
04:05:06
1 year 2 days 12:30:40
367 days 12:30:40
23 years 11 mons 15 days 12:30:40.567
```

**Comment by serge-rider** [comment]
DBeaver uses JDBC driver format. Which is also a native PG interval format "postgres verbose" (http://www.postgresqltutorial.com/postgresql-interval/).
But I agree that compact format is much more convenient.

**Comment by iPilot** [comment]
Why intervals sometimes shows as
5 days **3043**:25:02.236715
Anyway, there is no exceptions and EntityFramework can handle the result of a query, but the same query in DBeaver looks stange.
