### ISSUE TITLE
[Closed] DBeaver not showing SQL Server tables

### ISSUE THREAD

**Issue by melhzy** [dbeaver/dbeaver#4809]
I just downloaded and installed DBeaver 5.3.0 in my Ubuntu 16.04 desktop. I created a new table in my SQL Server 2017 database, but DBeaver's database navigator is now displaying any SQL Server tables.

![screenshot from 2018-12-16 12-14-21](https://user-images.githubusercontent.com/15963499/50056595-25731a80-012c-11e9-9b82-faef4c93a36a.png)

But in Azure Data Studio, I can see the table I just created is there.

![screenshot from 2018-12-16 12-15-16](https://user-images.githubusercontent.com/15963499/50056608-58b5a980-012c-11e9-8e6d-f248697252ed.png)

I figured all the tables are stored under [Schemas] -> [A Particular Schema] -> [Tables] -> [A Particular Table]. It's a different user experience compared to SSMS's.

No issue, and this issue was closed.

![screenshot from 2018-12-16 13-09-46](https://user-images.githubusercontent.com/15963499/50057127-1ee8a100-0134-11e9-8932-e6546f58bb8b.png)

**Comment by serge-rider** [comment]
Yep. We can make this configurable (and show tables as a plain list just like in SSMS) - if there will be enough votes.
However I personally prefer to group tables by schemas.

**Comment by melhzy** [comment]
> Yep. We can make this configurable (and show tables as a plain list just like in SSMS) - if there will be enough votes.
> However I personally prefer to group tables by schemas.

Where could we start a voting activity? For SQL Sｅｒｖｅｒ developers, the current configuration to group tables by schemas is not a sincere user experience.

**Comment by serge-rider** [comment]
@melhzy Just create a new ticket with such request.
