### ISSUE TITLE
[Question] SQL Anywhere connect either without tables or "Login failed"

### ISSUE THREAD

**Issue by Henry-Jones** [dbeaver/dbeaver#4810]
I try to connect DBeaver to a SQL Anywhere Database.

If I use SyBase jConnect it will connect just fine, but the folder "tables" (aka Tabellen in German) is empty. Also the log mentioning somthing along "no Metadata-Accessor found"

If I use SyBase then I'll get a Login failed detail message, the main error is "angegebene Datenbank nicht gefunden" (choosen database not found).

Maybe the last one is related to this: https://github.com/dbeaver/dbeaver/issues/1813 but the field to change the template is grayed out.

Also the .logfile only captures the SyBase jconnect attempt, for the SyBase one no entries are generated, a dbeaver-debug.log file is not present.

What can I do to help solve this problem ? Or at least change the template string, as this might already help.

Edit: I tried with the last 3.x version, where I could Change the template string. But this din't work either.  Meanwhile I also tried to use the 32 Bit version but also without success.

For the time being I can connect via ODBC, but if anyone has a bit of time to look into it, this would be helpful.

**Comment by serge-rider** [comment]
I can't reproduce this.
What do you want to change in connection URL? Usually you can just add some driver parameters.

Also you could create new driver.

**Comment by Henry-Jones** [comment]
Actually I do not want to change the URL I want to connect to the SQL Anywhere database :) I only assumed from reading issuse #1813 that this might help.

In Version 3.x I was able to change the template which did not help, so maybe my problem with the connect is something else.

But for the problem with the greyed out template field, see attached picture.

![clipboard 1](https://user-images.githubusercontent.com/9108755/50309412-0ca59480-049f-11e9-90bf-58122593125e.jpg)

I guess my knowledge of Java is virtually non-existant so creating a new driver is much likely beyond my capabilities. As far as Dbeaver goes, I'm more a user than a developer. Nevertheless I like to help getting the thing running with SQL Anywhere, so I can get rid of the ODBC detour.

**Comment by serge-rider** [comment]
I think that problem in #1813 is not related to your issue.

Could you post .log and dbeaver-debug.log files? Most likely you can use only jConnect driver but by some reason it doesn't work. More details are needed.

**Comment by Henry-Jones** [comment]
[.log.zip](https://github.com/dbeaver/dbeaver/files/2703877/default.log.zip)

attached please find the .log file. I guess the "0)" string Format exceptions are not related to the issue, i kept them in the file anyway.

The debug.log is nowhere to be found. Must it be enabled ? And if so, how ?

**Comment by serge-rider** [comment]
Thanks for logs.
I think this is the same issue:
https://stackoverflow.com/questions/20568827/jz0sj-metadata-accessor-information-was-not-found-on-this-database
https://sqlanywhere-forum.sap.com/questions/16254/javasqlsqlexception-jz0sj-metadata-accessor-information-was-not-found-on-this-database

You can try to execute 
```sql
ALTER DATABASE Upgrade JCONNECT ON
```
In your Sybase server to enable jConnect support.

BTW I've also found and fixed the bug in the German translation using your logs.

**Comment by Henry-Jones** [comment]
Hello, I tried this command (only one user is allowed on the DB to issue it, btw.) and it worked so far that I can see and work (aka select) with the tables. Thanks for your fast help, as always.

Surprisingly, I cannot change, delete or add anything in the tables. This works with all other connections I use (SQLite, SQL Server, PostgreSQL, MariaDB).

Even more surprisingly, I can add a new table without problems, so the connection as such should not be read-only.

But as this might be a different problem, I can also start a new thread about it.
