### ISSUE TITLE
 'mysqldump' not found in client home '/usr/local/var/mysql/virkdb' - Mac

### ISSUE THREAD

**Issue by naarkhoo** [dbeaver/dbeaver#4811]
I am using DBeaver to connect to a local mysql data base. I would like to dump the database in a memory stick so I get the following error

`IO Error: Utility 'mysqldump' not found in client home '/usr/local/var/mysql/virkdb'
`

I copied **mysqldump** into my database folder - still I get 

```
IO Error: Utility 'mysqldump' not found in client home '/usr/local/var/mysql/virkdb'
/usr/local/var/mysql/virkdb/mysqldump --routines --add-drop-table --disable-keys --extended-insert -v --host=localhost --port=3306 -u root virkdb
Export started at Mon Dec 17 14:39:30 CET 2018
dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
  Referenced from: /usr/local/var/mysql/virkdb/mysqldump
  Reason: image not found
Export finished at Mon Dec 17 14:39:30 CET 2018
Process exit code: 134

```

I can see there are a few other tickets (closed) but all addressing the problem in Windows.

**Comment by rirjkl19** [comment]
Do you happen to have resolved this?

**Comment by rirjkl19** [comment]
> Do you happen to have resolved this?

EDIT: I have resolved this issue, you should redirect your client home to the sqldump your mac is using. On my current device I directed the sqldump in my mamp server.

**Comment by elvirag** [comment]
I copied the mysqldump file from the sql, after installing mysql-client with brew install mysql-client:
```sudo cp /opt/homebrew/Cellar/mysql/$(echo `mysql --version` | egrep -o "(\d+\.\d+\.\d+)")/bin/mysqldump /usr/local/var/mysql/virkdb```

**Comment by elvirag** [comment]
> 

you can also use your path to the DBeaver drivers, of course

**Comment by ssjuma** [comment]
If you have installed XAMPP or WAMPP on your local machine then in the connection settings, add this directory: `/Applications/XAMPP/xamppfiles/bin`
and you should be good to go.
