### ISSUE TITLE
SQL Server: error line number/position

### ISSUE THREAD

**Issue by novusnick** [dbeaver/dbeaver#4816]
To whom it may concern,
Could the line number of the sql error be added to the error output?  In my query, I'm including the database name for all the tables and the error output shows that I have an error near the database name, but since each of the columns have the database name, it's too generic an error message without the line number.  Thank you for all your help with this

**Comment by serge-rider** [comment]
If database driver supports error position detection then DHBeaver shows it (at least for MySQL, PostgreSQL, Oracle and some other).
What is your database?

**Comment by novusnick** [comment]
I'm using SQL Server with the Microsoft driver

**Comment by novusnick** [comment]
That sounds good- thanks Serge

**Comment by serge-rider** [comment]
You can try it in Early Access version (https://dbeaver.io/files/ea).

Note: error positioning works only with driver version 7.1.4+ . If you used SQL Server connection before you need to go to driver settings, click on Download/Update and change the driver version:

![image](https://user-images.githubusercontent.com/6398845/51076211-72ec9400-16a6-11e9-9b0b-0f54201f9ea5.png)

**Comment by andreasnikiforosgeorgiadis** [comment]
Hello.
I have the same problem but I connect on a Sybase ASE 12.5.1 database using jconn4.jar driver (taken from C:\Sybase\jConnect-7_0\classes folder).

Will this problem be amended in version 7.1.4 for Sybase also or should I file a request for it?

Regards
