### ISSUE TITLE
DBeaver Feature: Add function to generate GUID/UUID string value

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4818]
DBeaver - **Version 5.3.0 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

It would be benificial if there where a funciton in _DBeaver_ that generated a GUID/UUID string value.

This for use:

**o** When I write a SQL script and need a new GUID/UUID value.
**o** When I insert a new row in a data grid and need a new GUID/UUID value.

**Comment by serge-rider** [comment]
Good point

**Comment by pdanie** [comment]
Maybe add a property setting too if I want the GUID/UUID value in upper or lower case letters.

**Comment by pdanie** [comment]
I have tried the EA from 02-Jan-2019 17:36 and it works in 1 of 2 use cases.

1) When in the SQL Editor - *Works ok**.
2) When in a grid column - **Does not work** (no GUID/UUID inserted).

**Comment by serge-rider** [comment]
Please provide more info. As you can see from the gif above they are inserted fine in my env.
Maybe you have some specific data type r something

**Comment by pdanie** [comment]
I have tried the database I think you are using (**PostgreSQL** - **dvdrental**).

How do you do to get the GUID/UUID values into the **description** column?

**PS**. I run Windows if that matters.

**Comment by serge-rider** [comment]
I just found a bug. 
It works in the data editor panel embedded in SQL editor but doesn't work for  table data editor.

**Comment by pdanie** [comment]
Super great (that you found something).

If you generate a new EA, I will try it out.

PS. Its 8:30pm here. Are you burning the "midnight oil" or something?
PPS. It is really super great to do this interaction with you. Seems _DBeaver_ is moving really quickly towards a really nice 5.3.2 version!

**Comment by serge-rider** [comment]
New EA is ready.

PS This is the last day before my NY vacation, trying to fix as much as possible for the next release :)

**Comment by pdanie** [comment]
I tried it in the EA from 02-Jan-2019 19:36 and **it workes**.

Only glitch I can find now is that if I right click on the grid cell and choose **Edit** -> **Edit Cell** _(Shift+Enter)_ that **Form** dialog does not react on the **Ctrl+Shift+U** keyboard shortcut.

![2019-01-02 21-29-16](https://user-images.githubusercontent.com/31191374/50611214-e982d800-0ed5-11e9-9dc5-8185c87fcba5.png)

**PS**. Strange that the dialog is named just **Form**. Should it not be named **Edit cell** or something?

**Comment by Sharan-Raj** [comment]
> I have tried the database I think you are using (**PostgreSQL** - **dvdrental**) with the EA from 02-Jan-2019 18:48.
> 
> How do you do to get the GUID/UUID values into the **description** column? I try pressing **Ctrl+Shift+U** after selecting a bunch of rows, nothing happens. In the SQL Editor window I have no trouble to generate a GUID/UUID value using the same keyboard shortcut.
> 
> **PS**. I run Windows if that matters.

use ctrl+shift+alt+u

**Comment by ujLion** [comment]
Ctrl + Alt + Shift + U - is the shortcut to insert UUID
works in SQL & Table editor
version: 25.1.5 (Windows)
