### ISSUE TITLE
insert PLSQL with returning id's and result set size smaller creates duplicates

### ISSUE THREAD

**Issue by Dennis-Britsch** [dbeaver/dbeaver#4819]
When using returning in an insert with a result set size that is smaller then the inserted amount, there will be "insert values"/"result set size" (rounded down) == the amount of duplicates inserted.

INSERT INTO public.customer_account
("name", ..)
values
('abc', ..),
..
('def', ..)
returning id;

105 insert values and result set size of 100 = 1 duplicate created (or two inserts of each insert value)
601 insert values and result set size of 200 = 3 duplicates created (or 4 inserts of each insert value)

returning id's match the amount of insert values.

Happening with a PostreSQL running on AWS. PostgreSQL JDBC Driver.

**Comment by serge-rider** [comment]
I assume this happens when you scroll query results (beyond fetch size). DBeaver re-executes the query when you scrolling to the next pages.
I don't  see how can we solve this at the moment. Maybe force "Fetch All" for INSERT queries or restrict scrolling for non-SELECT queries.

Any ideas?

**Comment by Dennis-Britsch** [comment]
When using the 'returning id' it does the auto scrolling/fetching automatically and returns me the correct amount of id's (maybe there was a onetime popup at some point).
And yes, I check that the fetch size is now bigger as the query insert size as a workaround but **not sure how to force that automatically.** and yes, also thought that DBeaver might not be able to fix that, still wanted to create a ticket for that issue.
