### ISSUE TITLE
dbeaver multi monitor setup - washed out tables

### ISSUE THREAD

**Issue by craigcarnell** [dbeaver/dbeaver#4823]
I have a multi-monitor setup and I usually have dbeaver maximized on one window while I work on the other monitor.

But with the latest version of dbeaver, the tables open become washed out when I move my cursor onto another window on my other monitor, which makes it impossible to read the data.

How do I disable this feature?

I am using Ubuntu 18.10.

**Comment by serge-rider** [comment]
Could you post a screenshot?

**Comment by uslss** [comment]
there is no any updates almost a year,
@craigcarnell if an issue is still actual for you feel free to reopen the ticket or create a new one.
