### ISSUE TITLE
Dbeaver: reading data in any table (bug)

### ISSUE THREAD

**Issue by Leoncello** [dbeaver/dbeaver#4826]
Hey guys,

does anyone experiences the same problem as I do? Since update to 5.3.0 I can't read data in any table due to the same error: 
Reason:
SQL Error [42P01]: ERROR: relation "xxx" does not exist
  Position: 571

The problem is that it was working fine yesterday, but it doesn't today.

**Comment by Leoncello** [comment]
it is worthwhile to mention that I've restarted my laptop already :)

**Comment by serge-rider** [comment]
I assume that you are using PostgreSQL.
Do you read data in SQL editor? Try to switch active database:

![image](https://user-images.githubusercontent.com/6398845/50226521-6bdaaa80-03b4-11e9-9f4a-3f2b88c75a67.png)

SQL editor uses active database to run queries.

**Comment by Leoncello** [comment]
Oh, it works. Thank you! ;)
