### ISSUE TITLE
Feature request: paste as list

### ISSUE THREAD

**Issue by rudmer** [dbeaver/dbeaver#4827]
Be able to have a special paste action that pastes the contents of the clipboard as a comma separated and/or quoted list.

from time to time I have the result of a query to be used in a new query (other database or too complex query to do nested selection) and i always end up doing a lot of <comma><up-key><left-key>... and for really log lists copy to text-editor and do a multi-line edit.

It would be really great if I can do a Ctrl+Shift+V or other shortcut that gives me the possibility to do this for me :)

example contents clipboard:
```
1
2
3
4
5
```
that can be pasted as ``1,2,3,4,5`` 

or with text:
```
a3d6g
d4gjk8
d4h672
l9je7d
djr73df
```
that can be pasted as ``'a3d6g', 'd4gjk8','d4h672','l9je7d','djr73df'``

because currently the last will give me this after pasting and needs a lot of manual editing:
```
select *
from   table
where special_code in (a3d6g
d4gjk8
d4h672
l9je7d
djr73df);
```

thanks!

**Comment by serge-rider** [comment]
This is already supported with Morph delimited list action:
![morph_delim_list](https://user-images.githubusercontent.com/6398845/50311002-c52a0300-04b4-11e9-9ff2-80941bcc3f07.gif)

**Comment by p91paul** [comment]
This is awesome.

**Comment by rudmer** [comment]
thank you so much!
I've been searching for this a long time but never noticed/tried the morph function.

feature implemented in no time at all ;)
