### ISSUE TITLE
Can't save file when logged with a schemma without privileges

### ISSUE THREAD

**Issue by renezito** [dbeaver/dbeaver#4828]
Hi !
I logged with a schemma without privileges to update/insert, only select.

So, I execute my query, then I change a value in Grid Result, then I try to save this change and DBeaver alert me that I can't save changes because the schemma has  insufficient privileges, and that's OK.

After that, I just try to save the file (script)... and the same alert appears again.

That is an error, because I'm not saving changes (commiting), I'm saving the file.

https://drive.google.com/open?id=17YVUb3kE0akvhZZb-7f7FFJblgQtchCa

Thanks

René Pereira

**Comment by uslss** [comment]
cannot reproduce it for now.
issue closed
