### ISSUE TITLE
is not a recognized built-in function name

### ISSUE THREAD

**Issue by yauda96** [dbeaver/dbeaver#4829]
Hi !
I am try to export table from MSSQL server with Dbeaver version 5.3.0. I can do very well in version 5.2.5, but now i get error message : 
SQL Error [104162] [S0001]: 'COLUMNPROPERTY' is not a recognized built-in function name.
I get this error message on import table from MSSQL to
I down grade to version 5.2.5 and the export/import is running very well

thanks
Ali Mustofa

**Comment by xbbnq7k** [comment]
Ali - I have the same issue. From where can I download the 5.2.5 version for Mac (.dmg)? thanks!

**Comment by yauda96** [comment]
I found this issue when I use the driver in orange circle, but when I use
the driver in green circle the connection is perfect (see picture in
attachment)
[image: image.png]

Pada tanggal Sen, 10 Jun 2019 pukul 18.40 Anuj Bandyopadhyay <
notifications@github.com> menulis:
