### ISSUE TITLE
Exasol Driver not working

### ISSUE THREAD

**Issue by dizdi** [dbeaver/dbeaver#4830]
Hi, DBeaver 5.3.0 on Mac or Windows. Currently running Java 1.8.0.45 on Mac. 

When connecting to an Exasol Instance, the driver manager opens and tries to download some libraries. 

Dialog "Driver Settings": Can't resolve libraries
When clicking on Download: 
Maven artifact 'maven:/com.exasol:exasol-jdbc:RELEASE' not found

Am I missing something or what's the reason for that? It stopped working before 5.3.0 i think. 

Thank you

**Comment by serge-rider** [comment]
Are you behind some corporate firewall/proxy?
DBeaver downloads driver's jars from remote servers. You can configure proxy settings in DBeaver preferences or download Exasol driver jars manually and then add them in the driver using driver manager.

**Comment by dizdi** [comment]
Hi, I'm currently not behind a proxy and there is no proxy configuration present. The Exasol JDBC-Driver vor Mac is an Installer currently. I didn't find any jar's do download. Is it possible that exasol changed their strategy and doesn't take care of the maven repo anymore?

**Comment by dizdi** [comment]
I uninstalled dbeaver and deleted .dbeaver, .dbeaver-drivers reinstalled and added an exasol connection. here is how it looks like. 

<img width="701" alt="screenshot 2018-12-21 at 16 44 17" src="https://user-images.githubusercontent.com/23087749/50350644-01567580-0540-11e9-919f-32bd80d8cb75.png">

<img width="746" alt="screenshot 2018-12-21 at 16 45 58" src="https://user-images.githubusercontent.com/23087749/50350657-087d8380-0540-11e9-9ae3-918a46b6705d.png">

PostgreSQL works: 

<img width="626" alt="screenshot 2018-12-21 at 16 47 54" src="https://user-images.githubusercontent.com/23087749/50350710-3e226c80-0540-11e9-8741-2afab7c48f76.png">

What could be wrong here...
Java version? java version "1.8.0_45"

**Comment by serge-rider** [comment]
I still think it is some network issue. Check debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files) for details, there should be some IO errors.

Exasol repository differs from other drivers (like PostgreSQL) which are hosted in Maven Central.
Try to browse it: https://maven.exasol.com/artifactory/exasol-releases to test it.

**Comment by dizdi** [comment]
You're right! It's a network issue. The cert of maven.exasol.com was renewed on August 8th. This is ca. the time when it stopped to work. I know this is not a dbeaver problem but a java problem. 
However, any ideas how to handle it for others who run into this issue?

2018-12-21 21:12:09.407 - Open [https://maven.exasol.com/artifactory/exasol-releases/com/exasol/exasol-jdbc/maven-metadata.xml]
2018-12-21 21:12:09.543 - Open [https://maven.exasol.com/artifactory/exasol-releases/com/exasol/exasol-jdbc/]
2018-12-21 21:12:09.651 - Maven artifact 'com.exasol:exasol-jdbc:RELEASE' not found in repository **'https://maven.exasol.com/artifactory/exasol-releases/': sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target**
2018-12-21 21:12:09.656 - Open [file:/Applications/DBeaver.app/Contents/Eclipse/maven-local/com/exasol/exasol-jdbc/maven-metadata.xml]
2018-12-21 21:12:09.659 - Open [file:/Applications/DBeaver.app/Contents/Eclipse/maven-local/com/exasol/exasol-jdbc/]

**Comment by serge-rider** [comment]
I believe it is because we bundle a bit outdated JRE in DBeaver Windows installer. I'll update it in the next version, thanks for checking this.

Workaround: install Java 9 or Java 10 manually and use it instead of JRE shipped along with DBeaver.

BTW we are going to migrate to JRE 10 or JRE 11 before DBeaver 6.0 release.
