### ISSUE TITLE
Background tasks refreshing issues

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#4831]
Tasks progress in _Background Tasks_ tab is not refreshed correctly. For example, when copying table data between databases I see task description like: _Transfer data from TABLE1 into TABLE2_ and _Transfer table data: 393000 rows fetched_. This progress information should refresh itself (it sometimes works), but often just stays the same until I do something like refresh table list, refresh table data or just run query. In other words - when task is added to _Background Tasks_ list.

This seems to be issue with interface, because exporting works correctly (but with some minor issues).

I'm using version 5.3.0 CE.

**Comment by uslss** [comment]
can't reproduce it against the recent version. 
The ticket will be closed. if the issue is still actual for you - feel free to reopen the ticket
