### ISSUE TITLE
Background tasks often disconnect

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#4832]
Long background tasks like copying table data seems to have some problems with keeping connection stable. I'm sure this is not a network or database issue.

```
Error occurred during SOME.TABLE data load

Reason:
SQL Error [17008] [08003]: Closed Connection
```

I'm using version 5.3.0 CE.

Edit: another error that seems to happen to often:
```
[17410] No more data to read from socket
```

This is strange, because I often use 2-3 different tools at the same time and they keep connected.

**Comment by uslss** [comment]
can't reproduce it against the recent version.
The ticket will be closed. if the issue is still actual for you - feel free to reopen the ticket
