### ISSUE TITLE
Make exporting/importing interface easier to use

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#4834]
1. Currently when you want to export data from multiple tables to another database you need to fill form like that:

    ![obraz](https://user-images.githubusercontent.com/20753183/50295609-b887b980-0478-11e9-803d-7a56421f7bc0.png)

    This is fine, except when you need to export 100+ tables. Then clicking that red fields can be irritating :]

    I think it is a good idea to assume that target table has the same name like source table if user does not specify other name.

2.  Add information about target and source connection in confirmation window 
![obraz](https://user-images.githubusercontent.com/20753183/50295950-99d5f280-0479-11e9-967c-2f0435190157.png)

3. Importing is even harder, because for each table you need to choose filename or table separately 
![obraz](https://user-images.githubusercontent.com/20753183/50296112-f9340280-0479-11e9-921f-9aea6f521b9f.png)

   I think it would be a good idea to assume that all sources comes from the same directory/schema and source file/table name matches target name. If not then user needs to specify file/table in current way.

**Comment by serge-rider** [comment]
1. I'll make new button "Auto-Assign".
2. This is already implemented in #4079
3. This is a bit more complicated. Maybe yet another "Auto-assign" button will help here too.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/51104157-58c1cb80-17f6-11e9-8400-6b448699bd66.png)

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/51106727-a68e0200-17fd-11e9-9173-5a6a78c9659a.png)
