### ISSUE TITLE
Result Set exporting - unchecked columns are exported

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#4838]
Column visibility in Result Set is not taken into account when exporting data.

Example:

I have following table and data:
``` sql
CREATE TABLE test_table(
    a NUMBER,
    b NUMBER,
    c NUMBER
);

INSERT INTO TEST_TABLE(A, B, C) VALUES(1, 2, 3);
INSERT INTO TEST_TABLE(A, B, C) VALUES(4, 5, 6);
INSERT INTO TEST_TABLE(A, B, C) VALUES(7, 8, 9);
COMMIT;
```
Now, when I uncheck `B` column in _Result Set Order/Filter Settings_ like this:

![obraz](https://user-images.githubusercontent.com/20753183/50297942-43b77e00-047e-11e9-97f1-8984884aaf8d.png)

I get wrong result when exporting Result Set (to csv in this case):
``` csv
"A","B","C"
1,2,3
4,5,6
7,8,9
```

But when I use _Generate SQL_ option to generate inserts I get correct commands:

``` sql
INSERT INTO TEST_TABLE
(A, C)
VALUES(1, 3);
INSERT INTO TEST_TABLE
(A, C)
VALUES(4, 6);
INSERT INTO TEST_TABLE
(A, C)
VALUES(7, 9);
```

DBeaver 5.3.0 CE, Oracle 12.2

**Comment by serge-rider** [comment]
Yes, indeed, hiding columns in results viewer doesn't affect data transfer.
Unfortunately it is not so easy to fix this issue.

Workaround: read all data on client-side, hide unwanted columns, select all (<kbd>ctrl+a</kbd>) and copy (<kbd>ctrl+c</kbd>) or advanced copy (<kbd>ctrl+shit+c</kbd>) - thus you can get CSV in clipboard.
