### ISSUE TITLE
Bug Report - sql editor scrollbars hides last row

### ISSUE THREAD

**Issue by eldarnegrinperion** [dbeaver/dbeaver#4839]
Since last version, the scrollbars on the text editor (sql editor) are shown on hover, and are hiding the last row/letter in a row, also making it unreachable to click (which is my main problem with it).
i have to enter few new lines to be able to edit it.
i can't find anywhere a possibility to disable the auto hide feature or at least have it not covering the last row/letter in a row.
attached a pic with the problem.
![image](https://user-images.githubusercontent.com/30038431/50298833-c2191d80-0488-11e9-929c-1f460ca65b62.png)

DBeaver version 5.3.0.201812092025 64-bit
linux ubuntu 16.04 (updated to 2018-12-20)

**Comment by akrz** [comment]
Why show the horizontal bar at all if no horizontal overflow is happening?

Also, the decision to place the scrollbar inside the editor on hover is very questionable. Is there an option to disable this behavior?

**Comment by p91paul** [comment]
I believe disappearing scrollbars are something gtk related. Are vertical scrollbars behaving this way in all applications? I don't think disappearing on hover is something controlled by Dbeaver.

**Comment by kavalanche** [comment]
I have the same issue. Version 6.0.2, Linux Mint 19.
I have browsed the settings and found nothing in there to mitigate the problem.

**Comment by muflone** [comment]
A temporary workaround is to disable the overlay scrolling by starting dbeaver with

    GTK_OVERLAY_SCROLLING=0 dbeaver

**Comment by muflone** [comment]
Relevant SWT bug for reference: https://bugs.eclipse.org/bugs/show_bug.cgi?id=519728
