### ISSUE TITLE
Adding an external table folder under the Schema tree folder [Greenplum]

### ISSUE THREAD

**Issue by Eulerizeit** [dbeaver/dbeaver#4840]
Greenplum has the concept of an external table which is similar to the idea of the Postgres FDW. Tables that are external are at the same lever (within the schema) at regular tables and the DDL statements differ depending on the external table source and access method. 

Currently DBeaver displays external tables as regular tables with slightly mangled DDL. We'd like to implement a new folder under the schema that displays external tables separately from regular tables with the proper DDL.

**Comment by serge-rider** [comment]
We added support of GP external tables in some 6.x version.
