### ISSUE TITLE
permission frame not show all items

### ISSUE THREAD

**Issue by tackephap** [dbeaver/dbeaver#4843]
When opening permission for an object, the side frame on the right do not expand to a reasonable size.
It just show 2 privileges maximum. In order to expand the number or privilege to she , i need to hide and show again the frame, then after i can resize the frame to display more privilege.
The horizontal split frame must be set at 50% immediatly when select a role.
Then the frame must be adjustable without having the need to hide and show it again.
![2018-12-21_12-59](https://user-images.githubusercontent.com/20203870/50327333-343d4100-0521-11e9-8567-d096fbe91949.png)
![2018-12-21_12-59_1](https://user-images.githubusercontent.com/20203870/50327334-38695e80-0521-11e9-9333-e77463ef80a9.png)
dbeaver-ee-5.3 on fedora 27x64

**Comment by uslss** [comment]
can't reproduce it against the recent version.
The ticket will be closed. if the issue is still actual for you - feel free to reopen the ticket
![image](https://user-images.githubusercontent.com/31996417/76847755-99323480-6853-11ea-8d4c-2dbca5a6c82d.png)
