### ISSUE TITLE
[Snowflake] Changing Roles, Database Navigator Doesn't Update

### ISSUE THREAD

**Issue by vlstrode** [dbeaver/dbeaver#4846]
In Snowflake a user can be assigned multiple roles.  One of those roles is typically set to default.
My default role is "Role1", it can see 4 objects and is used for Analytic Purposes.
I have another role "Role2", which can see, create, drop, insert on 100 tables.

In the course of the day, I work in both roles, and do so by issuing the command:

- Use Role Role1;
- Use Role Role2;

As I go back and forth between these two roles, the Database Navigator does not update to reflect which objects I can actually use / impact. (even when i use the database navigator's refresh option F5)

For instance, log in and work on analytic work in Role1, someone comes up to my desk and asks for a small tweak, I then change over to Role2 make those changes, might do some other work, and then go back to Role1.

When I am in Role1, I need to see only the 4 objects.
When I am in Role2, I need to see the 100 objects I'm responsible for admin'ing.

Not seeing the right objects when I am in a particular role, makes it confusing to complete my work.
Is there a way to change roles while working in a given session and have the Database Navigator update?

Using DBeaver version 5.3.0.201812092025
Snowflake JDBC Connection using Driver:  snowflake-jdbc-3.6.21.jar

**Comment by serge-rider** [comment]
Generally F5 on a database or schema node should help in this case. However this doesn't look very efficient. I'd suggest you to make separate DBeaver connection (you can copy-paste existing Snowflake connection) which will use different roles. In that case you want'need to to refresh or manually run Use commands. 

Moreover you can see database structure for both roles at once (using `Browse from here` command).
