### ISSUE TITLE
Typo in error message in Database Navigator

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#4850]
Minor issue, and probably not encountered a lot given the particular error, but you may wish to correct this to:

**Node does not have an associated database object**
or 
**Node has no associated database object**

![afbeelding](https://user-images.githubusercontent.com/7635726/50379562-f3dae180-064c-11e9-8c7c-583f8382cde7.png)

**Comment by serge-rider** [comment]
Thanks

**Comment by serge-rider** [comment]
However this error itself is an internal error, it should never happen in normal circumstances.

Is it reproducible?

**Comment by mboeringa** [comment]
@serge-rider 

I suspected something like that, but I wouldn't worry though. 

I am currently pushing the limits of a USB3.1 connected SATA Samsung EVO SSD by importing half the globe of OpenStreetMap data into PostgreSQL using osm2pgsql. In addition, there is a second process running against the same disk rendering data in ArcGIS from another PostGIS database on the same disk.

This is also all running from a VirtualBox VM instance on my laptop...

The main bottleneck seems disk IO, with varying but occassionally higher queue length at times, and consistent disk usage in the range of 75-100MB/s.

I blame it on all that, sometimes the Virtualbox seems locked up as well, but then continues after some heavy intermediate step is finished.

**Comment by arash-qc** [comment]
https://github.com/dbeaver/dbeaver/issues/37756

**Comment by arashilmg** [comment]
Open this
