### ISSUE TITLE
Duplicate condition

### ISSUE THREAD

**Issue by solnaranu** [dbeaver/dbeaver#4851]
Hi @serge-rider, first of all, I wanted to say hello and thank you since this is my first interaction with the repo and yourself. Dbeaver is an amazing effort, been using it for years.

Now, I found an insignificant little thing while going through SQL completion code:

https://github.com/dbeaver/dbeaver/blob/dea03fa793b712b9da2032641c4f538a4353cc54/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/editors/sql/indent/SQLAutoIndentStrategy.java#L95

I'm not sure if the right hand side of the `||` is supposed to index 1 or just be removed.

**Comment by serge-rider** [comment]
Thank you the bug report 👍 
This led to a problem when SQL dialect supports different quote chars (e.g. SQL Server and `[ ]` quotes)

**Comment by solnaranu** [comment]
Just curious, is it ever possible that `qs[1]` is nonexistent or null?

**Comment by serge-rider** [comment]
No, it hasn't be null. 
String quotes are always not-null pairs (usually it is the same character like " or ').
