### ISSUE TITLE
Query doesn't return error though select sub-query is having column of main query

### ISSUE THREAD

**Issue by ralebhattushar** [dbeaver/dbeaver#4854]
If there are two tables: Employee and Department
Columns in Employee table: emp_id, emp_name, dept_id
Columns in Department table: dept_id, dept_name

If I write the following query, it doesn't give any error on MsSQL server database.
SELECT COUNT(*) FROM EMPLOYEE WHERE DEPT_ID IN (SELECT EMP_NAME FROM DEPARTMENT)

In the above query, though the Department table doesn't have column EMP_NAME, it doesn't give any error but when I run only sub-query, it gives error 'Invalid column name'. 

I am using following DBeaver version:
![image](https://user-images.githubusercontent.com/45413542/50400824-ceb2b400-07af-11e9-9018-db85c52c2e00.png)

**Comment by p91paul** [comment]
That's not DBeaver, standard sql works this way.
In a subquery you are allowed to use all the columns in the parent query. I assume EMP_NAME is a valid column in the EMPLOYEE table.

**Comment by ralebhattushar** [comment]
OK..Thanks
