### ISSUE TITLE
Grouping panel sort order not kept after refresh

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#4855]
Steps to reproduce:

<code sql>
SELECT A, B FROM TABLE_NAME
</code>

Drag column A to the grouping panel
Order the grouping panel by A using the small arrows next to the column
Refresh the main query using the refresh button at the top of the resultset editor
The grouping panel gets refreshed as well, but ordering is lost

I believe this happens when the number of grouped results is small enough and the ordering is done by DBeaver instead of issuing an ORDER BY query.

**Comment by uslss** [comment]
already fixed.
ticket closed
