### ISSUE TITLE
Feature request: reorder columns in grouping panel

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#4856]
After having added a few columns to the grouping panel, it's impossible to reorder them (e.g. If I drop column A then column B, B is added to the right of A and can't be moved to the left).

From the pointer shape, it looks like dragging columns in the grouping panel is seen by DBeaver as I was dropping a new column, instead of reordering existing one. I'd like to be able to reorder columns by drag-and-drop in the grouping panel as I can in the standard resultset view.

**Comment by serge-rider** [comment]
Reorder support was added.
You can reorder "group by" attributes (and final SELECT query will be modified according to this order).
But you can't move aggregation columns.

**Comment by kseniiaguzeeva** [comment]
Implemented
