### ISSUE TITLE
Generate SQL not available without specifying schema, even though default schema already defined in driver

### ISSUE THREAD

**Issue by xantari** [dbeaver/dbeaver#4857]
Using DBeaver 5.3.1 against Microsoft SQL Server 2017 using the latest Microsoft SQL Server JDBC Driver.

When you specify a default schema here:

![image](https://user-images.githubusercontent.com/6610039/50407255-4d502700-0799-11e9-9750-a7b3cab6514d.png)

You can see "dbo" specified as default schema.

This is great. You can run SQL statement such as this:

select * from specialties and it will run successfully.

However, when right clicking a row and hitting "Generate SQL" you get the following:

![image](https://user-images.githubusercontent.com/6610039/50407271-8a1c1e00-0799-11e9-9d1a-224b09219810.png)

It seems it can't resolve table, even though the "Select * from specialties" sql is successful in retrieving data.

In order for the Generate SQL menu to properly appear you have to type:

"select * from dbo.specialities".

However, you should not have to do that, because "dbo" schema set in driver defaults.

It seems the fix is easy for this. If Schema defined in driver, then use that instead of forcing user to type in "dbo.specialities" for generate SQL to function properly.

**Comment by serge-rider** [comment]
In fact you can't change default schema on SQL Server (at least easily). It is always dbo.

Setting "Default  schema" in connection properties changes default database actually.

Anyhow, there is a bug in SQL Server extension (it doesn't use schema dbo as a default schema). Thanks for noticing.
