### ISSUE TITLE
columns from suggestion are from different table

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4860]
![__](https://user-images.githubusercontent.com/799021/50424259-14cc4e00-086a-11e9-8805-0e43709ddf4f.jpg)

here columns are from `package_detail` but I expect columns from `package` table

**Comment by uslss** [comment]
is it still actual for you?

**Comment by p91paul** [comment]
you sure this can't be reproduced? I can reproduce it very easily when doing any insert into... select statement.

A workaround is to alias the SELECTed table, and to invoke autocompletion with alias.

**Comment by uslss** [comment]
duplicates #7876
