### ISSUE TITLE
Primary key mark isn't showing

### ISSUE THREAD

**Issue by ajpuerta** [dbeaver/dbeaver#4862]
Primary key marks aren't showing in result tab, I have to see the table's properties to know what is. Two or three versiones ago the header was showing a light bulb, I guess.

It's happening with SQL Server and Oracle connections with a simple and single query.

Thank you for your work!

**Comment by serge-rider** [comment]
In fact currently this is supported only for MySQL. Because MySQL server provides this information out of the box.

I'll mark this as FR. Perhaps we'll add this bulb for SQL Server identity columns in near version.

**Comment by ajpuerta** [comment]
It would be a very useful feature
Thanks for your reply Serge!
