### ISSUE TITLE
org.jkiss.dbeaver.ui.navigator.database.load.TreeNodeLazyExpander cannot be cast to 

### ISSUE THREAD

**Issue by siberiun** [dbeaver/dbeaver#4863]
Hello,

I'm exporting a result from an oracle database to another oracle database and at the time of choosing the existing table the system displays the following message:

An error has occurred. See error log for more details.
org.jkiss.dbeaver.ui.navigator.database.load.TreeNodeLazyExpander can not be cast to org.jkiss.dbeaver.model.navigator.DBNNode

I have more than 21000 tables in the database.
![2018-12-26_1201](https://user-images.githubusercontent.com/46164101/50449546-33385500-090f-11e9-8621-79f1154255c0.png)

**Comment by serge-rider** [comment]
Thanks for the bug report
