### ISSUE TITLE
Functions from Greenplum display oddly in DBeaver

### ISSUE THREAD

**Issue by Eulerizeit** [dbeaver/dbeaver#4864]
#### Describe the problem you're observing:
When displaying user defined functions in DBeaver there are often additional fields added or subtile changes in the fields displayed. 

The desired output would be one that a user could copy and paste the code displayed by DBeaver and the exact same UDF would be produced. 

#### Steps to reproduce, if exist:
```SQL
CREATE OR REPLACE FUNCTION funhouse.function_with_query() RETURNS 
SETOF text AS $$
        BEGIN
                RETURN QUERY
                EXPLAIN ANALYZE SELECT * FROM large_table;
        END;
$$ LANGUAGE plpgsql
SET statement_mem='256MB';
```

Currently this particular functions is displayed as

```SQL
CREATE OR REPLACE FUNCTION funhouse.function_with_query() 
    RETURNS 
    SETOF text 
    LANGUAGE plpgsql
    VOLITILE
    Cost = 100.0
    Rows = 1000.0
AS $function$
        BEGIN
                RETURN QUERY
                EXPLAIN ANALYZE SELECT * FROM large_table;
        END;
$function$ 
;
```

Notably what is added is
`Cost = 100.0`, `Rows = 1000.0` and `VOLITILE`

Note that the parameter to be passed in does not have a variable name assigned to it.

Also, the session level GUC `SET statement_mem='256MB'`is missing.

Second example:
```SQL
CREATE TYPE funhouse.rainbow AS ENUM('red','orange','yellow','green','blue','indigo','violet');

CREATE FUNCTION funhouse.return_enum_as_array( anyenum, anyelement, anyelement ) 
    RETURNS TABLE (ae anyenum, aa anyarray) AS $$
    SELECT $1, array[$2, $3] 
$$ LANGUAGE SQL STABLE;
```
The function is displayed in DBeaver as
```SQL
CREATE FUNCTION funhouse.return_enum_as_array( anyenum, anyelement, anyelement ) 
    RETURNS SETOF record
    LANGUAGE SQL
    STABLE
    Cost = 100.0
    Rows = 1000.0
AS $function$ 

    SELECT $1, array[$2, $3] 

$function$ 
;
```

Here you can note that ` RETURNS TABLE (ae anyenum, aa anyarray)` has been changed to 
`RETURNS SETOF record`

**Comment by serge-rider** [comment]
This is default PostgreSQL function create syntax (for PG > 8.3).
Generally Greenplum also supports it (at least COST and VOLATILE).

However I can't reproduce it exactly as you described (I see a bit different DDL), what DBeaver version do you use?
In any case, we'll fix it in the next version to make it fully GP-compatible.

first function will look like this:
```sql
CREATE OR REPLACE FUNCTION public.function_with_query()
	RETURNS SETOF text
	LANGUAGE plpgsql
	VOLATILE
	SET statement_mem = '256MB'
AS $function$ 	 	
        BEGIN
                RETURN QUERY
                EXPLAIN ANALYZE SELECT * FROM large_table;
        END;
  $function$
```
Second one:
```sql
CREATE OR REPLACE FUNCTION public.return_enum_as_array(anyenum,anyelement,anyelement)
	RETURNS TABLE (ae anyenum, aa anyarray)
	LANGUAGE sql
	STABLE
AS $function$ 	 	
    SELECT $1, array[$2, $3] 
  $function$
;
```

**Comment by Eulerizeit** [comment]
Thanks for taking a look. The `Volatile` `Stable`  keywords weren't a concern. WRT cost I'm not sure why it would be added. 

This is something we are planning to pick up so if you are planning to pick it up please give us a heads up.
