### ISSUE TITLE
Allow open in excel with a single row

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#4866]
In #4763 export in excel was modified to only export selected cells. A patch to the original pull request was made to make sure that if a single row is selected, the export is not limited to that. 

The idea that you cannot "unselect" the whole table is sound, however couldn't the check be "more than one cell" instead of "more than one row"? This way you are allowed to open a single row (by selecting the row, or some cells in the row), but if a single cell is selected (which is the best "unselect" possibile) the whole resultset is exported.

WDYT? I'm not entirely sure this is a useful use case, possibly nobody would ever want to export a single row, but maybe...

**Comment by serge-rider** [comment]
Agreed. And this is very easy to fix
