### ISSUE TITLE
[oracle] - Script execution failed

### ISSUE THREAD

**Issue by gabrieltulli** [dbeaver/dbeaver#4868]
#### System information: 
- Operating system (distribution) and version: macOS 10.12.6
- DBeaver version: 5.3.1
- Java version 1.8
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use security connection (SSH, Proxy, etc)? 

#### Describe the problem you're observing:
Can't execute anonymous script in newer versions of dbeaver. The execution always fails with the message 

> Query execution failed
> 
> Reason:
> SQL Error [6550] [65000]: ORA-06550: line 18, column 3:
> PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:
> 
>    ; <an identifier> <a double-quoted delimited-identifier>
> The symbol ";" was substituted for "end-of-file" to continue.

This execution used to work on previous version of dbeaver.  (5.2.3).
#### Steps to reproduce, if exist:
execute the script:
```
declare 
  cursor temp is 
  select 'x' x from dual where 1=1
  union all 
  select 'y' x from dual where 1=1;
  varx char;
begin
  open temp;
  loop fetch temp into varx;
    exit when temp%NOTFOUND;
    begin
      dbms_output.put_line(varx);
    exception when others then
      dbms_output.put_line('2');
    end;
  end loop;
  close temp;
end;
```

#### Include any warning/errors/backtraces from the logs
[log.log](https://github.com/dbeaver/dbeaver/files/2714870/log.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/2714872/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Thanks for the bug report
