### ISSUE TITLE
Elementary OS Desktop crashes when exiting DBeaver (5.3.1 64 bit Linux)

### ISSUE THREAD

**Issue by oldlibmike** [dbeaver/dbeaver#4870]
#### System information: 
- Operating system (distribution) and version: Linux 4.15.0-43-generic (elementary OS 0.4.1)
- DBeaver version: 5.3.1 CE (64 bit Linux)
- Java version : 1.8.0_191
- Additional extensions

#### Connection specification:
- Database name and version: N/A
- Driver name: N/A
- Do you use security connection (SSH, Proxy, etc)? No

#### Describe the problem you're observing:
For all releases since 5.2.3, when I exit DBeaver, the desktop crashes completely - I never receive the confirmation dialog to exit cleanly. 5.2.3 works fine - every release since does not.
#### Steps to reproduce, if exist:
Open DBeaver, try to close the application

**Comment by oldlibmike** [comment]
Just an update/workaround. This seems to be related to GTK3 use. If I take the /usr/share/dbeaver/dbeaver.ini file from the older releases and copy it to the latest, things work. The older inis contained statements to use GTK2 as follows:

-startup
plugins/org.eclipse.equinox.launcher_1.5.100.v20180827-1352.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.800.v20180827-1352
-showsplash
--launcher.GTK_version
2
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Xms64m
-Xmx1024m

**Comment by pmensik** [comment]
I can confirm this issue, it happens to me as well. @oldlibmike thanks for the solution, works for me too!

**Comment by SaitDev** [comment]
change gtk ver no longer work since new dbeaver version doesnt support gtk 2
