### ISSUE TITLE
dbeaver not starting up from eclipse in macOS Mojave with -showsplash

### ISSUE THREAD

**Issue by subhash686** [dbeaver/dbeaver#4872]
Setup eclipse following the wiki link https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse
And launch was failing with a crash.  
**I am able to make it work by adding a -nosplash program argument.** 

Crash log in eclipse console with -showsplash argument is as follows.

> #A fatal error has been detected by the Java Runtime Environment:
> 
> #SIGSEGV (0xb) at pc=0x00007fff5dfd6a29, pid=46471, tid=0x0000000000000307
> 
> #JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
> #Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode bsd-amd64 compressed oops)
> #Problematic frame:
> #C  [libobjc.A.dylib+0x7a29]  objc_msgSend+0x29
> 

OS: macOS Mojave10.14.2
jdk 1.8
dbveaver code latest from github

_I am already running community edition of DBeaver, version 5.3.1 on the same machine and it shows splash screen and loads without any issues._ 
This seems to affecting only the developer version. 
Searched through the issue log (closed and open) but could not find a similar issue.

**Additional question:** I am looking to pick issues good for first timers and hope this -nosplash argument will not cause any testing discrepancy if I do end up making a PR.

**Comment by serge-rider** [comment]
This is weird. However I never run DBeaver in dev mode on Mac, I should try it)
Anyhow, try to use newer Java (10 or 11). We going to migrate to Java 11 before 6.0 release anyway.
