### ISSUE TITLE
项目导入到eclipse里。怎么跑起来 一直报错起不来 求指导

### ISSUE THREAD

**Issue by OIUE** [dbeaver/dbeaver#4874]
如题 一直跑不起来 报错 
本地maven环境没问题，导入eclipse里后  启动报错 jdk1.8  macos
 求大神指导 
先可以debug  然后打算拆除ui 。。。。

**Comment by serge-rider** [comment]
Check this: https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse
