### ISSUE TITLE
Export Into Database MySQL Error 'text' be 'varchar'

### ISSUE THREAD

**Issue by ibnuhalimm** [dbeaver/dbeaver#4878]
Hello,

I found bug on export to database.
I'll export my table into another host, when I start to export, I got an error about data type (as you can see on capture bellow), so, I have to manually change it to 'text' and reprocess export.
Thank you

![image](https://user-images.githubusercontent.com/14322078/50553625-f5f01080-0cdc-11e9-9c7f-1fd7ad781dd4.png)

**Comment by uslss** [comment]
seems that issue is fixed
![image](https://user-images.githubusercontent.com/31996417/82094635-2552c200-9706-11ea-927b-f89d0a01a10e.png)
