### ISSUE TITLE
DBeaver: Automatic data lookup in the Panels Value window broken when using new Microsoft driver

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4880]
DBeaver - **Version 5.3.1 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

The automatic data lookup in the Panels Value window is broken when using the **new Microsoft driver**. It works ok when using the **Old driver (Microsoft**).

**When using the _Old driver (Microsoft)_, there are both an edit value control and also the possibility to using the _Dictionary_ and  _Define Description_ links:**

![dbeaver_microsoft_old](https://user-images.githubusercontent.com/31191374/50558239-9b5eb080-0cec-11e9-875b-ed833aeebf55.png)

**When using the new _Microsoft driver_, there are neither an edit value control nor any possibility to change anything using the (missing) _Dictionary_ and  _Define Description_ links:**

![dbeaver_microsoft_new](https://user-images.githubusercontent.com/31191374/50558328-728aeb00-0ced-11e9-82b7-610f4cf56d93.png)

My guess is that is something broken with the lookup functionality when using the new _Microsoft driver_.

**Comment by serge-rider** [comment]
The actual problem was in wrong foreign keys referenced constraints resolution.
Thanks for the bug report.
