### ISSUE TITLE
DBeaver: Extend functionality of Go to Line to include column number/table column name

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4881]
DBeaver - **Version 5.3.1 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

It would be benificial if _DBeaver_ could not only **Go to Line** row, but also be able to specify column.

**Go to Line - In the SQL Editor**
```
<row number>
<row number>:<column number>
:<column number>
```
**o** When only specifying a _\<column number\>_ stay on the current line.
**o** When specifying a _\<column number\>_ move cursor to that text column/position _[1..n]_.

**Go to Line - In the Data Result Grid**
```
<row number>
<row number>:<column number/name>
:<column number/name>
```
**o** When only specifying a _\<column number\>_ stay on the current line.
**o** When specifying a _\<column number\>_ set focus to that grid column _[1..n]_.
**o** When specifying a _\<column name\>_ set focus to that grid column name.
**o** When specifying a _\<column name\>_ include **SQL Asssit** functionality _(Ctrl+Blank)_.

**Comment by E1izabeth** [comment]
Implemented here #21422
