### ISSUE TITLE
DBeaver: Add SQL Editor functionality of Duplicate Line(s)

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4882]
DBeaver - **Version 5.3.1 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

It would be benificial if _DBeaver_ could duplicate the line(s):

**o** That the cursor are in.
**o** The lines that are selected.

This is a really a quick way to make a copy of the current line when just wanting to test someting.

Also it is really a quick way to make a copy of a whole SQL command when wanting to make a similar SQL command.

**Comment by serge-rider** [comment]
It is already there (hint: <kbd>CTRL+ALT+UP</kbd>).

Note: you can find most of existing editor commands in the "Quick Access" tool.

**Comment by Candy128x** [comment]
You can also customize this feature by...
Clicking on Menu: Window -> Preference -> User Interface -> Keys -> Search: 'Duplicate Lines'
Update/Enter Your choice hot key in Binding field. -> Click on 'Apply and Close'
