### ISSUE TITLE
DBeaver: Customize Perspective contain toolbars with no text

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4885]
DBeaver - **Version 5.3.1 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

Customize Perspective contain toolbars with no text.

**o** Start _DBeaver_.

**o** Choose **Window** -> **Customize Perspective** in the main menu.

**o** Choose tab **Tool Bar Visibiliy**

**o** Expand **Transaction monitor**. It contains
> 5118
> Transaction log

**o** Expand **DataSource Selector**. It contains
> 5125
> Set connection from navigator (Ctrl+Shift+.)

My guess is that **5118** and **5125** are old stuff or things that is not implemented yet.

**Comment by uslss** [comment]
issue is still actual for Transaction Monitor
![image](https://user-images.githubusercontent.com/31996417/82094822-7cf12d80-9706-11ea-88e3-b9c8a8b12c92.png)

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
