### ISSUE TITLE
DBeaver: Remove unecessary press of ENTER in Bind Parameter(s) dialog

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4888]
DBeaver - **Version 5.3.2 Beta CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

If I run a SQL command in _DBeaver_ that contain a "colon parameter", when I have enetered the value for all the values in the **Bind parameter(s)** dialog I need to press the **Enter** key twice to press the **OK** button.

_DBeaver_ ought to use a press to the **Enter** key as both close input for the current value **plus** press the **OK** button.

**o** Start _DBeaver_ and connect to a database.

**o** Open a SQL Editor and enter the SQL command below:
```
SELECT * FROM sys.messages
 WHERE message_id < :MessageId;
```
**o** Execute the SQL command.

**o** _DBeaver_ pops up the **Bind parameter(s)** dialog.

**o** Enter the value **1000** for the parameter **:MessageId**.

**o** Press the **Enter key** once to close the input value.

**o** Press the **Enter key** again to have the default **OK** button pressed.

Ought to suffice to have to press to the **Enter** key once above.

**PS**. Another way might be to bind the **Execute SQL statement** key binding _(Ctrl+Enter)_ to do a close of the input value plus a click to the OK button.

**Comment by serge-rider** [comment]
Applying parameters by a single Enter doesn't sound like a good idea (in case of multiple parameters is may cause problems).

But CTRL+Enter sounds good and convenient.

**Comment by pdanie** [comment]
Super.

Hope the keyboard shortcut will be the one tied to the **Execute SQL statement" comand (ie. not hard coded to Ctrl+Enter).

**Comment by pdanie** [comment]
I have tried EA 02-Jan-2019 09:26 and Ctrl+Enter **IT WORKES**.

**BUT** seems you have hard coded the key combination to Ctrl+Enter, not to a more dynamic binding to what shortcut key that is tied to the **Execute SQL Statement** command.

**Comment by serge-rider** [comment]
It is bound to a default "Confirm" action + CTRL key. On most of OSes it is Enter indeed.
Bounding this to a existing shortcut is quite uneasy.

Are there some issues with default ctrl+enter?

**Comment by pdanie** [comment]
Nope... I was just thinkin more generic. It is totally your call.
