### ISSUE TITLE
Chinese character unreadable(中文乱码) after save as another file in Dbeaver 5.3.1 Windows7 x64

### ISSUE THREAD

**Issue by mythcolor** [dbeaver/dbeaver#4889]
OS: Windows7 professional 64bit, Language and territory is Chinese simplified China 中文（简体，中国）
dbeaver-ce-5.3.1-win32.win32.x86_64.zip (the latest version so far)

New a sql editor; type some Chinese characters, save as a file to a non-default path. Then you will see the characters become unreadable(中文乱码) .

If open that file in Notepad++ you will see the format is UTF8 without BOM. Change it to ANSI and then it becomes no problem in dbeaver. But when you save it again in Dbeaver the problem occurs again.

If save to default dir(not save as) , no problem.

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use security connection (SSH, Proxy, etc)?

**Comment by serge-rider** [comment]
I can't reproduce this (save and load of text with Chinese characters work fine).
Please check file encoding in DBeaver (press Alt+Enter in SQL Editor):
![image](https://user-images.githubusercontent.com/6398845/50611189-982f1480-0ee6-11e9-9092-60c7bbdda69b.png)


Also check default workspace settings:
![image](https://user-images.githubusercontent.com/6398845/50611237-bc8af100-0ee6-11e9-86d9-ae27bb4af1de.png)

**Comment by mythcolor** [comment]
Yes, it's the key point! In my computer, the default text file encoding is GB18030. Fortunately I set the text encoding of the workspace to UTF8, problem solved! Thanks very much!

**Comment by geekyouth** [comment]
# but it does not work on my pc 
![image](https://user-images.githubusercontent.com/12899262/71619920-cdf20080-2c01-11ea-8e6f-c1caf80543cb.png)


# then i solved it by other method
![image](https://user-images.githubusercontent.com/12899262/71619936-e235fd80-2c01-11ea-94c1-eb0db16e8ac9.png)


https://blog.51cto.com/12042068/2115021

![image](https://user-images.githubusercontent.com/12899262/71619992-288b5c80-2c02-11ea-948f-5b621241dd01.png)

在环境变量中添加JAVA_TOOL_OPTIONS选项，添加参数-Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US，这样JDK的提示就是英文的，系统输出的中文也能正常显示了，适用于Java/Scala程序

![image](https://user-images.githubusercontent.com/12899262/71619874-88353800-2c01-11ea-855d-174cf3224e7d.png)

重启dbeaver 以后，环境变量对其生效，因为dbeaver 使用 jdbc 驱动操作 数据库

![image](https://user-images.githubusercontent.com/12899262/71619906-b9156d00-2c01-11ea-81a0-3fced9ccf614.png)
