### ISSUE TITLE
Too many tasks created when exporting

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#4890]
#### System information: 
- Operating system: Windows 10 
- DBeaver version: 5.3.0.201812092025
- Java version: 1.8.0_77
- Additional extensions: None

#### Connection specification:
- Database name and version: Oracle 11.2.0.4
- Driver name: native client 12.1.0.2.0
- Do you use security connection (SSH, Proxy, etc)? No

#### Describe the problem you're observing:

DBeaver creates to many tasks for exporting data. In my case for some reason it creates 4 tasks, even when I number of threads is set to 1:

![obraz](https://user-images.githubusercontent.com/20753183/50585915-82363b00-0e77-11e9-9ee7-4e6589907bcc.png)

![obraz](https://user-images.githubusercontent.com/20753183/50585937-a6921780-0e77-11e9-8143-fde27bda0da9.png)

This keeps happening even if I manually change `maxJobCount` setting to 1 in `.metadata/.plugins/org.jkiss.dbeaver.core/dialog_settings.xml` and start DBeaver again (I edited that file when DBeaver is not running).

``` xml
...
	<section name="DataTransfer">
		<item value="1" key="maxJobCount"/>
		<item value="database_producer" key="producer"/>
		<item value="stream.csv" key="processor"/>
		<item value="stream_consumer" key="consumer"/>
...
```
#### Steps to reproduce, if exist:

Try to export some data with different thread count and see if number of tasks created is correct.

**Comment by serge-rider** [comment]
Thanks for the bug report
