### ISSUE TITLE
Using correlated sub-queries for schema queries brakes compatibility with some databases

### ISSUE THREAD

**Issue by yosefdi** [dbeaver/dbeaver#4892]
Sometime between version 5.2.3 and 5.3.1 there was a change in at least one SQL query from Database Navigator.
The new query uses correlated sub-query, while former queries didn't use this capability.

Please notice that while correlated sub-queries are supported on Microsoft SQL Server, there are some databases with MS-SQL compatibility that do no support this type of queries. Specifically there is Microsoft Azure Data Explorer (this temporary public preview name, aka Kusto inside Microsoft, see https://azure.microsoft.com/en-us/services/data-explorer/ and documentation of the limitation here https://docs.microsoft.com/en-us/azure/kusto/api/tds/sqlknownissues#correlated-sub-queries). 
It is better to avoid correlated sub-queries and to keep compatibility of Database Navigator with as many as possible databases that implement some degree of Microsoft SQL Server compatibility.

This is the query executed by Database Navigator that has correlated sub-query:

``` SQL
SELECT s.*
	,ep.value AS description
FROM sys.schemas s
LEFT OUTER JOIN sys.extended_properties ep ON ep.class = 3
	AND ep.major_id = s.schema_id
	AND ep.minor_id = 0
	AND ep.NAME = 'MS_Description'
WHERE EXISTS (
		SELECT 1
		FROM sys.sysobjects o
		WHERE s.schema_id = o.uid
		)
```

The same functionality can be achieved by the following query without correlated sub-query:

```SQL
SELECT s.*
	,ep.value AS description
FROM sys.schemas s
LEFT OUTER JOIN sys.extended_properties ep ON ep.class = 3
	AND ep.major_id = s.schema_id
	AND ep.minor_id = 0
	AND ep.NAME = 'MS_Description'
INNER JOIN sys.sysobjects o ON s.schema_id = o.uid
GROUP BY s.name, s.schema_id, s.principal_id, ep.value
```

**Comment by serge-rider** [comment]
Thanks for the information.
I'll use this query:
```sql
SELECT DISTINCT s.*,ep.value as description FROM AdventureWorks2012_Data.sys.schemas s
LEFT OUTER JOIN AdventureWorks2012_Data.sys.extended_properties ep ON 
    ep.class=3 AND ep.major_id=s.schema_id AND ep.minor_id=0 AND ep.name='MS_Description'
INNER JOIN AdventureWorks2012_Data.sys.sysobjects o ON s.schema_id=o.uid
```
because explicit GROUP BY may cause problems with old SQL Server versions (different column set)

**Comment by yosefdi** [comment]
Yes, sure. It would, however, lead to wrong column set on Azure Data Explorer, but look like a compatibility bug of ADX that should be fixed.

**Comment by serge-rider** [comment]
Good. BTW you can test this in EA version (https://dbeaver.io/files/ea)

**Comment by yosefdi** [comment]
Thanks, will do.

**Comment by yosefdi** [comment]
@serge-rider question:
the table sys.sysobjects include only system objects. It doesn't include tables, views and functions you create on database. Is that your intention to show schemes that have at least one system object or you wanted to query for schemes that are not empty?

**Comment by serge-rider** [comment]
The intention is to find not-empty schemas. I was quite sure that sysobjects contains information about all objects in the database (not just system ones).
Do you know any better way to get not-empty schemas?

**Comment by serge-rider** [comment]
Thanks for investigation.
I think we'll use version number checking. And use all_objects for SQL Server 2008+.

**Comment by serge-rider** [comment]
Version 5.3.3 will use all_objects for SQL Server 2008+

**Comment by yosefdi** [comment]
I've checked 5.3.3 from EA and it works well with ADX. Thanks!

**Comment by yosefdi** [comment]
And here is updated ADX instructions for using DBeaver:
https://docs.microsoft.com/en-us/azure/kusto/api/tds/clients#dbeaver-533-and-above

**Comment by serge-rider** [comment]
@yosefdi 👍 
BTW we can add Active Directory support out of the box. It will require extra config of driver + connection page enhancement.
You can create a feature request if you think that this will be really useful.
