### ISSUE TITLE
Install from Eclipse Marketplace fails

### ISSUE THREAD

**Issue by JonFP** [dbeaver/dbeaver#4893]
#### System information: 
Mac OS - 10.13.6
- DBeaver version - Attempting to install 5.3.1 from Eclipse Marketplace
- Java version - unsure - IBM Java 7 ?
- Attempting to plug in to IBM Rational Developer for i (have done this several times before)

Install of 5.3.1 fails with the following error messages. This appears to be similar to an error that arose with release 5.2.3 and was subsequently fixed.
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver Runtime 5.3.1.201812232236 (org.jkiss.dbeaver.runtime.feature.feature.group 5.3.1.201812232236)
  Missing requirement: DBeaver UI 5.1.14.201812232236 (org.jkiss.dbeaver.ui 5.1.14.201812232236) requires 'bundle org.eclipse.mylyn.commons.ui 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver Eclipse Plugin 5.3.1.201812232236 (org.jkiss.dbeaver.core.eclipse 5.3.1.201812232236)
    To: bundle org.jkiss.dbeaver.ui 0.0.0
  Cannot satisfy dependency:
    From: DBeaver Runtime 5.3.1.201812232236 (org.jkiss.dbeaver.runtime.feature.feature.group 5.3.1.201812232236)
    To: org.jkiss.dbeaver.core.eclipse [5.3.1.201812232236]
```

**Comment by serge-rider** [comment]
Looks like you Eclipse installation (Rational Developer) doesn't have Mylyn plugins.
Could you try to install Mylyn first (https://marketplace.eclipse.org/content/mylyn) ?

**Comment by p91paul** [comment]
This is interesting: why does dbeaver require mylyn? does it interact with mylyn in some way?

**Comment by JonFP** [comment]
Well if I go to that page it tell me I need Eclipse Marketplace - which I have.

But Marketplace is only showing me various connectors for MyLyn - I can't find the main package.

What am I missing?


Jon Paris
jon.f.paris@gmail.com

**Comment by serge-rider** [comment]
You can copy Mylin repo URL (http://download.eclipse.org/mylyn/releases/latest) and enter in in 
Help->"Install new software":
![image](https://user-images.githubusercontent.com/6398845/50607119-2f8d6b00-0ed9-11e9-86c0-e645e95c9fc7.png)

**Comment by JonFP** [comment]
Thanks for the repo information. As it happens I accidentally found that when the mouse was over the "Instal" button that the hover text explained that I could drag the icon onto my workbench - and sure enough that worked and dBeaver is now installed. Many thanks to all.

No idea how I got the original MyLyn install on my old system - I never deliberately installed it.

**Comment by JonFP** [comment]
Thanks all for the help - MyLyn was the cure.
