### ISSUE TITLE
Data export should be designed as a single page instead of a wizard

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#4897]
Data export provides a good number of options. However, showing them in multiple subsequent windows of that wizard can be overwhelming and lead to errors. 
For example I'm not using the truncate option, because I know I would overlook it the next time I run the wizard and truncate tables I didn't intend to. For the same reason I never use "use selected rows/use selected columns".

If all the options could be provided in a single page (using expandable panels to ensure it doesn't get too big), I would more easily be able to check the 2/3 settings I'd normally change.
Have you ever seen the Toad data "copy data" window? It's even more option-packed than dbeaver's and fits in a single window. I can provide you with a screenshot if needed.

Data export would also be faster if I didn't need to click next so many times! WDYT?

**Comment by serge-rider** [comment]
I think this sounds reasonable. At least we can combine export/import pages into a single page.
Yes, please post some screenshots, they could be useful in any case.

**Comment by p91paul** [comment]
Here they are:
![immagine](https://user-images.githubusercontent.com/2157006/50611000-2a2e2180-0ed5-11e9-97c8-8d323d3dd42d.png)

The second tab is for adding where clauses (https://github.com/dbeaver/dbeaver/issues/4833)

![immagine](https://user-images.githubusercontent.com/2157006/50610983-1387ca80-0ed5-11e9-9725-46980a9033a3.png)

I remembered it having more options, actually.

This is the data export window instead (Toad has 2 different processes, one to export to a table and the other export to insert statements, excel file, csv etc.)
![immagine](https://user-images.githubusercontent.com/2157006/50611248-fef80200-0ed5-11e9-8690-641a71e41370.png)


Don't misunderstand me: Toad interface is cumbersome and ugly, DBeaver's much better! However I think they got right the idea of packing most export options in a single window, although with tabs, to separate exported tables (with #4834 you won't really need to look at that section anymore, as everything will be auto-mapped, so it's fine to make it less prominent) from options.

**Comment by serge-rider** [comment]
Let's try this combined settings page for now: (contents depends on source and target formats)
![image](https://user-images.githubusercontent.com/6398845/52168400-0e6ba480-273b-11e9-975c-4dd893e7ad12.png)
![image](https://user-images.githubusercontent.com/6398845/52168448-92be2780-273b-11e9-9c68-50f96c8781f6.png)

Mappings pages and output file(s) settings page are still separate though.

**Comment by p91paul** [comment]
nice!
