### ISSUE TITLE
DBeaver: Spelling Error in Confirmation Preferences

### ISSUE THREAD

**Issue by fyzm7357** [dbeaver/dbeaver#4902]
#### System information: 
Operating System - macOS 10.14.2
DBeaver Version -  DBeaver EE 5.3.2
Java Version - Java v8u191 
Database name and version - Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

#### Describe the problem you're observing:
Spelling error found in the Preferences --> Database --> Confirmations --> Cancel **runing** queries

![screen shot 2019-01-02 at 15 26 04](https://user-images.githubusercontent.com/43044156/50613309-c559d380-0ea2-11e9-8b91-d82f8c82d029.png)

**Comment by serge-rider** [comment]
Thanks for the bug report
