### ISSUE TITLE
no PostgreSQL data types in Database Navigator

### ISSUE THREAD

**Issue by trajnisz** [dbeaver/dbeaver#4904]
#### System information: 
- DBeaver version: 5.3.1

#### Connection specification:
- Database name and version: PostgreSQL 11, 10

Using DBeaver with PostgreSQL 10 and 11 (i did not use earlier versions) i noticed that expanding "Data types" in "Database Navigator" does not show anything. After looking for a query in the code i found following one:
```
    @Override
    protected JDBCStatement prepareObjectsStatement(@NotNull JDBCSession session, @NotNull PostgreSchema owner) throws SQLException
    {
        // Initially cache only base types (everything but composite and arrays)
        StringBuilder sql = new StringBuilder();
        sql.append("SELECT t.oid,t.* \n" +
            "FROM pg_catalog.pg_type t WHERE typnamespace=? ");
        if (PostgreUtils.supportsTypeCategory(session.getDataSource())) {
            sql.append("AND typcategory <> 'A'");
        }
        sql.append(" AND typrelid<>0");
        sql.append("\nORDER by t.oid");
        final JDBCPreparedStatement dbStat = session.prepareStatement(sql.toString());
        dbStat.setLong(1, owner.getObjectId());
        return dbStat;
    }
```

It is not looking for composite types so they are not visible. To get all user defined data types query should look more or less like this:

```
        SELECT t.oid,t.*
        FROM pg_catalog.pg_type t 
        join pg_catalog.pg_class c on t.typrelid = c.oid
        WHERE typnamespace=some_number
        AND typcategory = 'C'
        and c.relkind = 'c'
        and t.typtype = 'c'
        and typarray <> 0
        ORDER by t.oid
```

I wanted to create pull request becouse changing this query in code works but i am not sure if it`s not messing with other functionalities. Any ideas from experienced contributors?

**Comment by serge-rider** [comment]
You are right. The idea was to exclude all regular tables from type list.
Thanks for the hint.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/50857995-3f58f380-13a0-11e9-9bb6-daff446e9fde.png)
