### ISSUE TITLE
[Question] Database Navigator x Active Script Tab.

### ISSUE THREAD

**Issue by hugorn** [dbeaver/dbeaver#4906]
Is there any way to not change the connection of the active script when clicking the node in the database navigator?

![onclickdatabasenavigator](https://user-images.githubusercontent.com/9035153/50637652-9b072500-0f39-11e9-9bc8-f0982b55ea54.gif)

**Comment by fyzm7357** [comment]
I believe unchecking the 'Auto-sync editor connection with navigator selection' should accomplish what you are looking for.

![screen shot 2019-01-03 at 21 01 21](https://user-images.githubusercontent.com/43044156/50672009-2238b500-0f9b-11e9-87eb-c0fd3cd18015.png)

**Comment by hugorn** [comment]
> I believe unchecking the 'Auto-sync editor connection with navigator selection' should accomplish what you are looking for.
> 
> ![screen shot 2019-01-03 at 21 01 21](https://user-images.githubusercontent.com/43044156/50672009-2238b500-0f9b-11e9-87eb-c0fd3cd18015.png)

It worked correctly, thank you very much for the help.
