### ISSUE TITLE
Invalidate/Reconnect Does Not Function When Connection Invalidates for Other Reasons

### ISSUE THREAD

**Issue by kdonavin** [dbeaver/dbeaver#4911]
#### System information: 
- Operating system (distribution) and version: macOS Mojave, version 10.14.2
- DBeaver version: 5.3.1.201812232236
- Java version: 10.0.1 2018-04-17
- Additional extensions

#### Connection specification:
- Database name and version: Snowflake
- Driver name: Snowflake JDBC
- Do you use security connection (SSH, Proxy, etc)? Yes, just with personal Snowflake credentials

#### Describe the problem you're observing:

Invalidate/Reconnect appears to do nothing when my connection has been connected but invalidated (perhaps due to being connected for too long of a period, or switching networks). I have to instead click "Disconnect" and then click "Connect". What is the purpose of this Invalidate/Reconnect option if it does not do just that in the scenario I need it to?

#### Steps to reproduce, if exist:

1. Wait for a connect to invalidate on it's own.
2. Right click on connection
3. Click "Invalidate/Reconnect"

Nothing happens.

**Comment by uslss** [comment]
Hi @kdonavin , 
is issue still actual for you?

**Comment by kdonavin** [comment]
Sorry: no. It now functions normally for me.
