### ISSUE TITLE
gObjectClass_finalize error

### ISSUE THREAD

**Issue by BriceJamin** [dbeaver/dbeaver#4912]
#### System information: 
- Operating system (distribution) and version
`brice@debian-bja:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`
- DBeaver version
5.3.1
- Java version
`brice@debian-bja:~$ java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) Client VM (build 25.191-b12, mixed mode)
`
- Additional extensions
I think I don't have any extension.
I see this list of directory in my .dbeaver4/.metadata/.plugins :
> org.eclipse.core.resources
> org.eclipse.core.runtime
> org.eclipse.debug.core
> org.eclipse.e4.workbench
> org.eclipse.mylyn.commons.notifications.ui
> org.eclipse.search
> org.eclipse.ui.workbench
> org.eclipse.ui.workbench.texteditor
> org.jkiss.dbeaver.core
> org.jkiss.dbeaver.model
> org.jkiss.dbeaver.ui

#### Connection specification:
- Database name and version
SELECT version();
> PostgreSQL 9.4.4 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11), 64-bit
- Driver name
PostgreSQL JDBC Driver
- Do you use security connection (SSH, Proxy, etc)? 
I think no.

#### Describe the problem you're observing:
A popup error appear with error message "gObjectClass_finalize"
I can't see Error log view because when restarting Dbeaver freeze I can't close it.
Mouse usage is lost on my Debian. But I can change of window with keyboard.
 I use kill command to kill DBeaver and mouse usage is possible after that.

#### Steps to reproduce, if exist:
Double click on a table name in the database browser UI when some tables are already opened before.

#### Include any warning/errors/backtraces from the logs
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/2726758/dbeaver-debug.log)
[log.part1.log](https://github.com/dbeaver/dbeaver/files/2726759/log.part1.log)
[log.part2.log](https://github.com/dbeaver/dbeaver/files/2726761/log.part2.log)

**Comment by serge-rider** [comment]
IT is a known issue in Eclipse platform (https://bugs.eclipse.org/bugs/show_bug.cgi?id=527536) on some 32-bit Linuxes
Unfortunately there are very few chances that this will be fixed as Eclipse canceled 32-bit systems support recently...

**Comment by BriceJamin** [comment]
Thank you for your answer !
Then I will try to migrate to 64-bit on my virtual linux, or using DBeaver in native Windows.
