### ISSUE TITLE
CSV Import: backslash in text column removed, Quote chars setting ignored

### ISSUE THREAD

**Issue by marcusfey** [dbeaver/dbeaver#4913]
When I import a CSV file into a table:
- single backslashes are removed from text column values (double backslashes come out as one)
- "Quote char" setting is ignored, i.e. the quotes are imported as part of the value of text columns

#### System information: 
- Windows 7 Pro
- DBeaver version 5.3.1
- java version "1.8.0_151"
- Additional extensions: none

#### Connection specification:
- zOS
- DB2JCC4 4.19.49
- no secure connection
- also occurs on a Derby DB I set up just for testing DBMS (in-)dependence

Steps to reproduce:

1. Create table like
`CREATE TABLE tabelle (
	col1 CHAR(7) NOT NULL,
	col2 VARCHAR(480) NOT NULL,
	CONSTRAINT tabelle_PK PRIMARY KEY (col1)
);
CREATE UNIQUE INDEX myidx ON tabelle (col1);`
2. Right click on table and "Import Data", CSV
3. Select file
4. Configuration, "Next" ![2019-01-04_142932-c__users_aekn_ dbeaver4 - dbeaver 5 3 1 - tph7g010](https://user-images.githubusercontent.com/6460821/50690383-5361c580-102d-11e9-942b-97c092f21aca.png)
5. Preview is already incorrect: Quotes are still present, double blackslash in the original file shows only as one backslash (I had to use this as a workaround because a single backslash would not show at all)
![2019-01-04_143143-c__users_aekn_ dbeaver4 - dbeaver 5 3 1 - tph7g010](https://user-images.githubusercontent.com/6460821/50690446-9a4fbb00-102d-11e9-8282-70265ef171ab.png)
6. Next/Finish
7. Open table, incorrect as well
![2019-01-04_144507-c__users_aekn_ dbeaver4 - dbeaver 5 3 1 - tph7g010](https://user-images.githubusercontent.com/6460821/50690904-6aa1b280-102f-11e9-9ddd-5226f065484d.png)

I played around with the quotes to get the backslashes but it did not work. My actual file [PZN_ATA_orig.txt](https://github.com/dbeaver/dbeaver/files/2727191/PZN_ATA_orig.txt) does not contain quotes as text delimiters (or anything else), it also does only have single backslashes which I need to be imported as such. The "test"-version of the file [PZN_ATA_test.txt](https://github.com/dbeaver/dbeaver/files/2727190/PZN_ATA_test.txt) is the one I used to create the above images.

Error log does not show anything.

**Comment by marcusfey** [comment]
Strange. Even if I set column delimiter to `\t` the quotes are still present in the preview/destination table and backslashes are missing...
What about the backslashes, are they imported correctly for you?

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/50919347-9cfa4800-1453-11e9-8921-0c46922f0e2b.png)
![image](https://user-images.githubusercontent.com/6398845/50919452-e64a9780-1453-11e9-912d-ba1141ad04c1.png)

Backslash is escape character. 
Perhaps we should add extra config parameter for it.

**Comment by marcusfey** [comment]
Great, many thanks!!!

Actually it would be great to disable the escape character processing altogether. But from looking at 
- https://github.com/quux00/opencsv/blob/master/src/au/com/bytecode/opencsv/CSVReader.java
- https://github.com/quux00/opencsv/blob/master/src/au/com/bytecode/opencsv/CSVParser.java

that doesn't seem to be possible.
