### ISSUE TITLE
DBeaver: Changing selected schema in Database Navigator makes DBeaver loose information on what database schema is default

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4915]
DBeaver - **Version 5.3.2 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

_DBeave_ does not keep information on what database schema is default when I click on another database schema in the **Database Navigator**.

**o** Start _DBeaver_ and choose **Connect** to a database server.

**o** Right click on a database and choose **Set active** _(Ctrl+Shift+A)_ in the contex menu.

**o** Expand the **Schemas** subtree in the **Database Navigator**.

**o** The **dbo** schema should be marked as active with a **bold** font.

**o** Choose the **Navigate** -> **Open Database Object** _(Ctrl+Shift+D)_ in the menu.

**o** Search for a table name that is available in the active database.

**o** The table name pops up in the **Mathing items** list. This is **OK**.

**o** Just click in the **Database Navigator** on the **sys** database schema (same database).

**o** Choose the **Navigate** -> **Open Database Object** _(Ctrl+Shift+D)_ in the menu.

**o** Search for the same table name that you searched for before in the database.

**o** An error message is shown:
> **Items filtering has encountered a problem**
>
> **Items filtering failed**
> &nbsp;&nbsp;Error while searching n system catalog
> &nbsp;&nbsp;Must declare the scalar variable "@P0AND".
> &nbsp;&nbsp;Must declare the scalar variable  "@P0AND".

My guess is that the information of active database default schema is overwritten when I move around in the **Database Navigator**. Feels like this is a bug.

I think the easiest way would be for issue #4915 (this issue) and #4914 that both the **Open Database Object** and the **Assistant/Completion** (manual/automatic) only looked in the active database and always looked in all schemas. No matter what I click on in the **Database Navigator**. 

Only difference is that:
**o** The **Open Database Object** get the active database from the **Database Navigator**.
**o** The **SQL Editor** get the active database from its own **Active catalog/schema** combo box.

Why make things more complicated than they have to be.

**PS**. Even if this issue is reported on the **new Microsoft Driver** other connect types suffer from similair problems. This is a generic problem in _DBeaver_.

**Comment by uslss** [comment]
cannot reproduce it. if it is still actual for you - feel free to reopen the ticket

**Comment by troogyt** [comment]
This still seems to be an issue. Please reopen.

**Comment by VipSaran** [comment]
The described problem started happening to me when upgraded to Version 21.3.0.202111281534 (community)

As can be seen:
![image](https://user-images.githubusercontent.com/995948/146171265-1c3964e1-d7fa-4abd-9f4c-b108a3327eba.png)

2 DBs are filtered to be shown and 1 DB is ACTIVE, but the "Open Database Object" dialog lists objects from both Active and inactive DB.

Insult to injury: it doesn't even show which object is from which DB so (in my case) there's 50% chance I'll get the wrong DB!
