### ISSUE TITLE
DBeaver: Connection setting of Default Schema has no effect for SQL Server connection

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4916]
DBeaver - **Version 5.3.2 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

Changing the **Connection settings** -> **Initialization** -> **Default schema** does not have any effect for a SQL Server connection.

_DBeaver_ seems to have hard coded "**dbo**" as default schema no matter what I set the **Default schema** to.

**Comment by serge-rider** [comment]
It is not possible to change default schema for SQL Server. 
So for SQL Server "Default schema" means "Default database". 

However there is a bug in "Initialization" connection page (it loads schema list for SQL Server instead of database list)

**Comment by pdanie** [comment]
Ok. Is it this what I see in #4919 case too (initialization of a connection is flaky/broken) ?

**Comment by serge-rider** [comment]
No, #4919 is a different issue

**Comment by pdanie** [comment]
What is then the difference between specifying a database name in the two cases below?

**o** The **Connection Settings** -> **Database/Schema**
**o** The **Connection Settings** -> **Initialization** -> **Default database/schema**

Seems they now have a similar function.
