### ISSUE TITLE
DBeaver: The environment is not initialized correctly with new Microsoft Driver

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4919]
DBeaver - **Version 5.3.2 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

When a connection is established in _DBeaver_ the environment is not intialized correctly.

**o** Start _DBeaver_.

**o** Uncheck the **global** setting **Database** -> **Navigator** -> **Expand navigator tree on connect**.

**o** Create a connection to a **MS SQL Server** using the **new Microsoft Driver**.

**o** Restart the _DBeaver_

**o** Expand the created **connection** in the **Database Navigator**.

**o** Expand a **database** node in the **Database Navigator** (a database of your choice).

**o** Expand its **Schemas** node in the **Database Navigator**.

**o** Click on the **dbo** database schema node in the **Database Navigator**.

**o** Choose the **Navigate** -> **Open Database Object** _(Ctrl+Shift+D)_ in the _DBeaver_ menu.

**o** Search for a table name that you know exists in the choosen database **dbo** schema.

**o** An error message are shown:
> **Items filtering failed**
> &nbsp;&nbsp;**Error while searching in system catalog**.
> &nbsp;&nbsp;Must declare the scalar variable "@P0AND".
> &nbsp;&nbsp;Must declare the scalar variable "@P0AND".

**o** To get the **Open Database Object** _(Ctrl+Shift+D)_ to work I have to:

&nbsp;&nbsp;&nbsp;**o** Expand the **dbo** node.
&nbsp;&nbsp;&nbsp;**o** Expand the **Tables** node.
&nbsp;&nbsp;&nbsp;**o** Click on one of the table name nodes.

Seems there is something missing with the initialization of a connection in the **Database Navigator** together with the **Open Database Object**.

**This is really an annoying bug in _DBeaver_. And also quite confusing for those users that not use _DBeaver_ on a regular basis**.

**Comment by serge-rider** [comment]
Thanks for the bug report
