### ISSUE TITLE
Large Copy / Paste results in partial data pasted

### ISSUE THREAD

**Issue by vlstrode** [dbeaver/dbeaver#4920]
#### System information: 
- Windows 10 Pro
- DBeaver version:  5.3.0.201812092025
- Java version 
  - java version "1.8.0_191"
  - Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
  - Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

#### Connection specification:
- AWS - Snowflake 
- Using JDBC String

#### Describe the problem you're observing:
When running a query and producing a large data result, when I select ALL, Copy, Switch to an empty  Excel File and Paste, I either run out of memory, OR not all the values returned by the query are pasted into excel (data will stop pasting midway thru the result set).

While I know I can export the result, our users are putting their feet down and saying they must have this feature (to copy / paste large data results).  In the software we currently use to connect to a SQL Server, the users can do this.  As we move our systems from SQL Server to Snowflake (AWS) and from Microsoft SQL Server Management Studio to (hopefully) DBeaver, would like to know how to enable this functionality in DBeaver.

#### Steps to reproduce, if exist:
I ran the following code (union all results multiple times until I got to 500,000+ rows.  This is not efficient, but it enables an example others can achieve.

```
SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION, 
		COLUMN_DEFAULT, IS_NULLABLE, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, 
		CHARACTER_OCTET_LENGTH, NUMERIC_PRECISION, NUMERIC_PRECISION_RADIX, NUMERIC_SCALE, 
		DATETIME_PRECISION, INTERVAL_TYPE, INTERVAL_PRECISION, CHARACTER_SET_CATALOG, 
		CHARACTER_SET_SCHEMA, CHARACTER_SET_NAME, COLLATION_CATALOG, COLLATION_SCHEMA, 
		COLLATION_NAME, DOMAIN_CATALOG, DOMAIN_SCHEMA, DOMAIN_NAME, UDT_CATALOG, 
		UDT_SCHEMA, UDT_NAME, SCOPE_CATALOG, SCOPE_SCHEMA, SCOPE_NAME, MAXIMUM_CARDINALITY, 
		DTD_IDENTIFIER, IS_SELF_REFERENCING, IS_IDENTITY, IDENTITY_GENERATION, IDENTITY_START, 
		IDENTITY_INCREMENT, IDENTITY_MAXIMUM, IDENTITY_MINIMUM, IDENTITY_CYCLE, "COMMENT"
FROM USER_DB.INFORMATION_SCHEMA."COLUMNS"
UNION ALL ... --repeat above code until result set is 500,000+ records
```

#### Include any warning/errors/backtraces from the logs
When I run more than 400,000 records, I get the following error:
`SQL compilation error: Compilation memory exhausted.`

**Comment by serge-rider** [comment]
Well, generally it is not a great idea to fetch 500k rows in results grid. And copy-pasting then into Excel is even worse. 
In your example table has about 100 columns, 500000*100 = 50 millions of cells. It will consume gigabytes of memory.

You can increase amount of memory available for DBeaver (see https://github.com/dbeaver/dbeaver/wiki/Command-Line) but I doubt that it work for Excel.

Workarounds: export data in CSV format (as direct open in Excel may also have issues with memory). And then open CSV in Excel.

**Comment by p91paul** [comment]
@serge-rider is the open in excel feature loading the whole resultset in memory before exporting? I assume you are using apache POI, which does support streaming (i.e. fetch 1000 rows, write 1000 rows to excel, then get next 1000). That allows you to create as big an excel as you like without memory issues. Good luck getting excel to open that file, but that's not dbeaver fault anymore.

Doing it through copy-paste is mostly nonsense if excel export works (it's surely faster and easier to press a single button), unfortunately users come out with nonsense requirements all the time...
