### ISSUE TITLE
Community Version 5.3.1 'refresh interval' 

### ISSUE THREAD

**Issue by apiszcz** [dbeaver/dbeaver#4921]
Is the 'refresh interval' available in the community edition. I reviewed the Wiki [refresh ](https://github.com/dbeaver/dbeaver/wiki/Data-Refresh) setting documentation and do not see it on my installation on Windows. Thank you.

**Comment by serge-rider** [comment]
Yes, it works in CE. Refresh control is to the right from filter panel.
![image](https://user-images.githubusercontent.com/6398845/51023531-32065980-1598-11e9-80bd-e0afc355e4e1.png)

**Comment by apiszcz** [comment]
Thank you. Is auto-refresh available and a setting to continuously refresh?

**Comment by serge-rider** [comment]
Yes

**Comment by apiszcz** [comment]
Ok, not sure what I was doing wrong, it is there, with interval spec.
DBeaver is very nice work!
