### ISSUE TITLE
PostgreSQL: object ID = 0 for columns

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#4923]
Object ID is always 0 for created columns (PostgreSQL 10).

**Comment by serge-rider** [comment]
Basically it is not possible to get new object ID in the moment of ALTER TABLE execution.
We need to make table refresh to get new IDs for all new table elements..

**Comment by serge-rider** [comment]
Fixed.
There is no OID for PG columns but there is attnum (ordinal position) instead.
We'll use it and we'll refresh table after column create

**Comment by uslss** [comment]
verified
