### ISSUE TITLE
DBeaver: Delete of a file in the Projects Window are asked a buggy question

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4924]
DBeaver - **Version 5.3.2 Beta CE**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

When deleting a file in the **Projects Window** the user are asked:
> **Are you sure you want to delete {0} "{1}"?**

Seems the formating of the question string is buggy.

**o** Start _DBeaver_.
**o** Create a new scripts file using **SQL Editor** _(F3)_ command.
**o** Open the **Projects Window** by choosing **Window** -> **Projects** in the menu.
**o** Expand the **General** -> **Scripts** node.
**o** Right click on the previously created scripts file.
**o** A question dialog pops up with the buggy question.

My guess is that the formating of the string falter in the Java code.

**Comment by knadt** [comment]
https://github.com/dbeaver/dbeaver/issues/4948
Submitted a ticket for MacOS

**Comment by pdanie** [comment]
I have tried this issue in th **EA 12-Jan-2019 14:21** and it seems **OK**. Great work.
