### ISSUE TITLE
[feature] Support OmniSci (MapD) GPU SQL Analytics Engine

### ISSUE THREAD

**Issue by archenroot** [dbeaver/dbeaver#4925]
Hi,

I would like to use dbeaver for connections to OmniSci platform via JDBC. 

Is there any temporary workaround to inject just JDBC and try it or it will require all the data type mapping, DDL/DML language to be mapped into some general model of dbeaver?

Thx for response.

**Comment by serge-rider** [comment]
No, only JDBC driver (jar file) + driver configuration is required. n most cases no any data type mappings are required.
If you will succeed in OmniSci configuration - please share driver configuration (URL, class ,etc). We'll include it in one of near DBeaver versions.

**Comment by archenroot** [comment]
@serge-rider - ok, so connection is established:
![image](https://user-images.githubusercontent.com/553512/51456042-a2b23080-1d65-11e9-8a07-3a93f147bd3c.png)

**Comment by archenroot** [comment]
And additionally I attach XML config:
```
<provider id="generic">
                <driver id="B7E68812-B745-F526-374A-D9084F050A77" categories="" custom="true" embedded="false" n$
                        <library type="jar" path="${home}/mapdjdbc-4.3.0.jar" custom="true"/>
                        <parameter name="supports-indexes" value="true"/>
                        <parameter name="omit-single-catalog" value="false"/>
                        <parameter name="all-objects-pattern" value="%"/>
                        <parameter name="quote-reserved-words" value="true"/>
                        <parameter name="omit-single-schema" value="false"/>
                        <parameter name="supports-scroll" value="false"/>
                        <parameter name="omit-catalog" value="false"/>
                        <parameter name="script-delimiter-redefiner" value=";"/>
                        <parameter name="supports-struct-cache" value="true"/>
                        <parameter name="supports-truncate" value="true"/>
                        <parameter name="script-delimiter" value=";"/>
                        <parameter name="legacy-sql-dialect" value="false"/>
                        <parameter name="script-delimiter-after-query" value="false"/>
                        <parameter name="use-search-string-escape" value="false"/>
                        <parameter name="omit-type-cache" value="false"/>
                        <parameter name="split-procedures-and-functions" value="false"/>
                        <parameter name="supports-multiple-results" value="false"/>
                        <parameter name="supports-stored-code" value="true"/>
                        <parameter name="script-delimiter-after-block" value="false"/>
                        <parameter name="supports-references" value="true"/>
                        <parameter name="ddl-drop-column-short" value="false"/>
                        <parameter name="supports-limits" value="true"/>
                        <parameter name="supports-select-count" value="true"/>
                </driver>
        </provider>

```

**Comment by archenroot** [comment]
@serge-rider - I found one first issue probably can be handled somehow, it does translate timestamp with wrong values:
![image](https://user-images.githubusercontent.com/553512/51529795-e171e480-1e52-11e9-9608-e9b58a2006c1.png)

while in the console of mapd (and how real data looks like) I get:
![image](https://user-images.githubusercontent.com/553512/51529908-2d248e00-1e53-11e9-878b-8b2be2c98e5a.png)

I think its just something with formating, etc. any idea how to handle?

**Comment by serge-rider** [comment]
Thanks for details. 
However driver descirption xml seems to be corrupted (there is no information about driver class and others).

Do you have some sample DB/script to test it?

Are you aware about any direct link for driver download? Unfortunately they don't have Maven artifact (https://community.omnisci.com/t/jdbc-driver-maven-artifact/613)

**Comment by serge-rider** [comment]
@archenroot Are you aware how to obtain jdbc driver by direct link? Or some archive with the driver?

**Comment by archenroot** [comment]
@serge-rider - I will check with mapd and ask them to deploy to maven, its best way I think.

**Comment by archenroot** [comment]
@serge-rider - can you please reopen and we will wait for Mapd to release JDBC driver separately, its in their dev scope already.
