### ISSUE TITLE
Unable to connect - Algorithm constraints check failed on keysize limits

### ISSUE THREAD

**Issue by NathanDeckinga** [dbeaver/dbeaver#4928]
#### System information: 
- Operating system (distribution) and version : Fedora 28
- DBeaver version : 5.3.1.201812232236 (installed via RPM)
- Java version  : openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
- Additional extensions : None

#### Connection specification:
- Database name and version : PostgreSQL 9.6.6 (on AWS RDS)
- Driver name : PostgreSQL
- Do you use security connection (SSH, Proxy, etc)? : No

#### Describe the problem you're observing:
When I test the connection I'm creating (or attempt to connect after saving it), I get an error message that says "Algorithm constraints check failed on keysize limits." (I'll put the entire message and details below).  Attempting to connect to that same DB using the psql command "psql -h <db_host> -p 5432 -U <good user> <db_name>" works perfectly, so it appears that my computer and the default PG client can connect to the DB correctly, but something in DBeaver or my setup is failing to connect.  I have only attempted it with the single PostgreSQL database that I am running so I cannot test server side potential issues.

#### Steps to reproduce, if exist:
- Edit existing connection or add a new one.  Hit "Test Connection". Get failure message.
- Connect to existing DB in DB Navigator.  Get failure message.

#### Include any warning/errors/backtraces from the logs
Full error message: Algorithm constraints check failed on keysize limits. RSA 1024bit key used with certificate: C=US, ST=Washington, L=Seattle, O=Amazon.com, OU=RDS, CN=<My DB host name>.  Usage was tls server

Partial stack trace in UI: SSL error: java.security.cert.CertificateException: Certificates do not conform to algorithm constraints
  java.security.cert.CertificateException: Certificates do not conform to algorithm constraints
  java.security.cert.CertificateException: Certificates do not conform to algorithm constraints
    Certificates do not conform to algorithm constraints
    Certificates do not conform to algorithm constraints
      Algorithm constraints check failed on keysize limits. RSA 1024bit key used with certificate: C=US, ST=Washington, L=Seattle, O=Amazon.com, OU=RDS, CN=<My DB host name>.  Usage was tls server
      Algorithm constraints check failed on keysize limits. RSA 1024bit key used with certificate: C=US, ST=Washington, L=Seattle, O=Amazon.com, OU=RDS, CN=<My DB host name>.  Usage was tls server

**Comment by serge-rider** [comment]
I assume your RDS instance requires SSL connection. And you are using certificates provided by AWS.

This error happens during SSL handshake and seems to be specific to your local Java configuration (see https://stackoverflow.com/questions/51489695/ssl-handshake-validation-error-in-connection-to-mssql-server-by-jdbc-driver )

You could try to install Unlimited Security Policy package into your local Java8 installation (https://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html).
Also you could try to upgrade Java to 10 or 11 version will resolve the issue (BTW we going to make Java 11 default Java version for DBeaver soon and we will include it in distribution for all supported OSes).

**Comment by NathanDeckinga** [comment]
@serge-rider - At the moment you assume incorrectly.  I have not enabled SSL on that DB yet (although that is the plan).  I wanted to connect without SSL first to ensure that I had everything else set up properly, and it didn't work.  Also, I provided my psql connection string and that worked without any SSL parameters.

I'll try the upgrade to Java 11 (might as well) and let you know what happens.  Actually, I'm going to try the upgrade to fedora 29 first and I'll check back in after those with an update.

**Comment by serge-rider** [comment]
If you didn't enable SSL then it was auto-enabled by RDS server.
You could try to setup SSL like this: (no ceritficates, mode set to `allow`).

![image](https://user-images.githubusercontent.com/6398845/51044260-c04b0180-15d1-11e9-8bbe-45ff4c18c113.png)

**Comment by NathanDeckinga** [comment]
Making the change to "allow" worked.  That is... less than intuitive, especially when the psql client didn't require any ssl settings.  Can anyone explain like I'm 5 why this works?

**Comment by serge-rider** [comment]
This is one of the miracles of PostgreSQL driver.
I found this accidentally when connection to one of my AWS servers stopped worked.

I'm thinking about enabling this property (SSL mode) by default for all PostgreSQL connections..

**Comment by serge-rider** [comment]
Please check how it works in Early Access version (https://dbeaver.io/files/ea). 
Just remove this dummy SSL config and try to connect.
