### ISSUE TITLE
ERROR: invalid value for parameter "TimeZone": "Australia/Sydney"

### ISSUE THREAD

**Issue by natiki** [dbeaver/dbeaver#4931]
#### System information: 
- Windows 10 Pro 1803
- CE 5.3.2 (with JRE in installer)

#### Connection specification:
- Cockroach DB CCL v2.1.3 @ 2018/12/17 19:23:49 (go1.10.3)
- Connection String: postgresql://root@localhost:26257?sslmode=disable

#### Describe the problem you're observing:

![image](https://user-images.githubusercontent.com/4738140/50763846-1a438280-12c5-11e9-9373-be71720a9b0b.png)

#### Steps to reproduce, if exist:

- Download and install https://dbeaver.io/files/dbeaver-ce-latest-x86_64-setup.exe
- Run up a CockroachDB cluster using:

`cockroach start --insecure --listen-addr=localhost`

- Attempt to connect to the database. Ultimately this does not look to be a database issue but rather a JRE issue?

**Comment by serge-rider** [comment]
I can't reproduce this with older Cockroach version (2.0.4), will try with a newer one.

**Comment by serge-rider** [comment]
Well, it works like a charm with Cockroach 2.1.3 on my machine.
This might be related to corrupted JRE but I can't figure out how this may happen.
Is there anything specific about your DBeaver/Cockroach installation?

**Comment by natiki** [comment]
> Is there anything specific about your DBeaver/Cockroach installation?

No. However my Windows 10 timezone setting is `(UTC +10 Canberra, Melbourne, Sydney`. If I change my time zone to `UTC` then there is no error. If I then change my time zone back to my UTC +10 one above and change how I launch DBeaver from `dbeaver.exe`  to: 

`C:\Program Files\DBeaver>dbeaver.exe -vmargs -Duser.timezone=UTC`

then it launches without error. I am not a Java dev so I don't understand the relationship between forcing the timezone to the above in the JRE so that when the JDBC makes the connection it works. Not sure this is then ultimately related to the PostgreSQL implementation within Cockroach but it appears there is some known issues with 2.1.3 when it comes to time zones. See https://www.cockroachlabs.com/docs/stable/known-limitations.html#new-values-generated-by-default-expressions-during-alter-table-add-column

So ultimately my guess would be to see what happens on your machine when you fiddle with the time zone.

**Comment by knz** [comment]
The timezone names are not supported when running CockroachDB on Windows, see https://github.com/cockroachdb/cockroach/issues/32415

To make this problem go away:

- run dbeaver on windows but run CockroachDB on a unix system, eg via a container or VM 
- use a numeric time zone instead

(Note: we support running dbeaver on windows, but running *CockroachDB* on windows is not supported)
