### ISSUE TITLE
Weird behavior with date cast

### ISSUE THREAD

**Issue by abevieiramota** [dbeaver/dbeaver#4932]
#### System information: 
- Operating system (distribution) and version
MATE Desktop 1.12.1
- DBeaver version
5.3.2.201901062110
- Java version 
1.8
- Additional extensions
None

#### Connection specification:
- Database name and version
Postgres 9.2.5
- Driver name
PostgreSQL
- Do you use security connection (SSH, Proxy, etc)? 
No

#### Describe the problem you're observing:

The following query is returning an unexpected result:

`select '2018-12-31'::date;`

Result: 31/12/2019

#### Steps to reproduce, if exist:

Run the query: `select '2018-12-31'::date;`

**Comment by serge-rider** [comment]
It is not unexpected. Looks like default US date/time format.
You can change date/time format in preferences. You can also force using "Database native format".

![image](https://user-images.githubusercontent.com/6398845/51032244-51a97c00-15b0-11e9-8458-8ab1935034c3.png)

**Comment by abevieiramota** [comment]
Hi @serge-rider, thanks for the answer.
Is it really a question of format? Regardless of the format used, with the sql `select '2018-12-31'::date;` I expected the result being '2018-12-31', not '2019-12-31'.

**Comment by serge-rider** [comment]
Ah, sorry, I didn't mention that year is different.
What is your time zone? (it is shown in the status line of main window)
Also, does using native format solve the problem?

**Comment by abevieiramota** [comment]
Timezone: BRT
I changed to the default format(yyyy-MM-dd) and the result was correct. I've just seen that I was using, I think, a wrong formatting string, dd/MM/YYYY(capital y). My bad, thanks and sorry wasting your time.

**Comment by serge-rider** [comment]
NP :)
