### ISSUE TITLE
create temp table - dbeaver on mac

### ISSUE THREAD

**Issue by dbEngineer** [dbeaver/dbeaver#4934]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions
Mac OS X Yosemite
DBeaver 5.3.1
java version "1.8.0_60"

#### Connection specification:
- Database name and version
- Driver name
- Do you use security connection (SSH, Proxy, etc)? 
Postgresql 9.6
PostgreSQL JDBC Driver
OpenVPN

#### Describe the problem you're observing:
After opening the editor windows just execute:
1. create temp table abcd(id int4);
2. select * from abcd;

the second step with select statements produce the error:

"Query execution failed
Reason:
SQL Error [42P01]: ERROR: relation "abcd" does not exist"

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/8290986/50779986-1ce0b080-12a2-11e9-9c80-731b9396c2e9.png)

with this settings
![image](https://user-images.githubusercontent.com/8290986/50780457-3fbf9480-12a3-11e9-8cee-7afbed62cd8d.png)

**Comment by serge-rider** [comment]
I can't reproduce that.
Maybe it is somehow related to auto-commit mode..

**Comment by dbEngineer** [comment]
finally I could find the reason.
It is related to the checkbox "Invalidate connection before execute" in the SQL Processing tab.
After it was disabled, it has started to work on mac.

![Screen Shot 2019-04-25 at 10 37 15](https://user-images.githubusercontent.com/8290986/56721901-2d7c4000-6746-11e9-85d3-af33ba73f807.png)
