### ISSUE TITLE
PostgreSQL: Create database command should be in the connection/server context menu

### ISSUE THREAD

**Issue by maffe** [dbeaver/dbeaver#4935]
#### System information: 
- DBeaver 5.3.2

#### Connection specification:
- PostgreSQL 10.3
- PostgreSQL standard driver (42.2.5)

#### Describe the problem you're observing:
The _create database_ command is in the context menu of the database, [not](https://github.com/dbeaver/dbeaver/issues/2330#issuecomment-416837453) in the connection/server context menu.

**Comment by serge-rider** [comment]
Agreed.
We need to reorganize navigator tree for PostgreSQL.
Add root folder Databases and move server-specific nodes (like Administer, Roles, etc) to the root folder.

**Comment by maphew** [comment]
Is there a reason this is Pgsql specific? ie. why not _"File >> New >> Create Database >> {Select type from Pgsql/Sqlite/Mysql/...}"_

**Comment by serge-rider** [comment]
@maphew There are hundreds of different object types, we can't put all of them in File->New wizard (it will make it unusable).

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/56454717-df3dfa00-635d-11e9-9ea6-03f0aeb9b6b6.png)

**Comment by uslss** [comment]
1. Objects like table/ couldn't be created from db/schema context menu until db isn't opened case. 
![image](https://user-images.githubusercontent.com/31996417/56458388-9eaaa480-638e-11e9-9c13-90dcbcc47013.png)
[can't create.txt](https://github.com/dbeaver/dbeaver/files/3100207/can.t.create.txt)
2. Menu is available for columns but is not working. issue appears in oracle, postgresql, mysql.
[fail.txt](https://github.com/dbeaver/dbeaver/files/3100209/fail.txt)

Also, #5763 issue is created

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
