### ISSUE TITLE
Prompt to delete {0} "{1}" when trying to delete database using context menu

### ISSUE THREAD

**Issue by maffe** [dbeaver/dbeaver#4936]
#### System information: 
- Windows 10
- DBeaver 5.3.2
- Java 1.8.0_181-b13

#### Connection specification:
- PostgreSQL 10.3
- PostgreSQL standard driver (42.2.5)

#### Describe the problem you're observing:
Prompt does not show the database name
![grafik](https://user-images.githubusercontent.com/515302/50782015-16086c80-12a7-11e9-8fa8-dec5bccdee7b.png)

#### Steps to reproduce, if exist:
- Create database
- Use the database’s context menu to delete it

#### Include any warning/errors/backtraces from the logs
There were no related log entries.

**Comment by pdanie** [comment]
Seems to be something like the misbehaviour I noticed in my #4924 support issue.

**Comment by serge-rider** [comment]
Yep, duplicate of #4924
