### ISSUE TITLE
DBeaver: If the SQL Processing Named parameter prefix is changed that prefix is shown in the Bind parameter(s) dialog

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4938]
DBeaver - **Version 5.3.2 CE**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

If the **SQL Processing Named parameter prefix** is changed that prefix is shown in the **Bind parameter(s)** popup dialog.

**o** Change the setting **Editors** -> **SQL Editor** -> **SQL Processing** -> **Parameters** ->
&nbsp;&nbsp;&nbsp;**Named parameter prefix** from "**:**" to "**&**".

**o** Execute the SQL statement below in a **SQL Editor** (use table name and parameter of your own choice):
> SELECT * FROM MyTable WHERE Id = &Id;

**o** The parameter **Name** in the **Bind parameter(s)** dialog show the "**&**" as prefix.

My guess here is that the **Bind parameter(s)** dialg have a hard coded filtering of "**:**" as prefix, not filtering of what is set in the **Named parameter prefix**.

**Comment by serge-rider** [comment]
You are exactly right. 
Thanks for bug report

**Comment by pdanie** [comment]
Super. I guess the simplest solution would be to just remove the 1st character no matter what it is. That way you don't have to read the system properties.

**Comment by pdanie** [comment]
I have tried this issue in th **EA 12-Jan-2019 14:21** and it seems **OK**. Great work.
