### ISSUE TITLE
Results view not rendering newlines in text record mode

### ISSUE THREAD

**Issue by ephetic** [dbeaver/dbeaver#4940]
#### System information: 
- macOS 10.13.6
- 5.3.3.201901062109
- whatever Java version the pkg installer installed

#### Connection specification:
- PostgreSQL 9.6
- PostgreSQL standard driver (org.postgresql.Driver, org.postgresql:postgresql:RELEASE [9.4.1212.jre7])

#### Describe the problem you're observing:
The test results view previously rendered newlines rather than showing the escape characters, thus pretty formatted json displayed readably.

![image](https://user-images.githubusercontent.com/3395020/50799834-a4262800-1292-11e9-8a32-52036803ca1e.png)

#### Steps to reproduce, if exist:
select json_pretty(json_column) from table;

view result as text record.

**Comment by serge-rider** [comment]
As far as I remember we always rendered plan text like this (in a single line).
If you need to view your json column in multiline mode - use Value View panel (click on Panels in toolbar).

**Comment by ephetic** [comment]
I never previously used the values panel, so it definitely did render
differently before. I'll find the diff.

**Comment by p91paul** [comment]
I'd say new behavior is generally better (as it doesn't break columns alignment in the text view)...IMHO 5.2.4 had a bug that was fixed. For your use case it might be better to see json pretty printed, but breaking column alignment for that is bad.

**Comment by ephetic** [comment]
I agree.
