### ISSUE TITLE
Current DateTime Shortcut

### ISSUE THREAD

**Issue by jerameel** [dbeaver/dbeaver#4941]
#### System information: 
- Fedora 29
- DBeaver 5.3.2 CE

#### Describe the problem you're observing:
I can no longer access current date shortcut ( the one that automatically inserts current datetime when editing a cell). I had this on previous versions.

**Comment by serge-rider** [comment]
WE reworked this function in 5.3.2. Now it is called "Set to default", it works for different data types, can be applied to multiple cells. Default shortcut is <kbd>CTRL+Insert</kbd>.

**Comment by jltamburini** [comment]
But if the field has no default...
