### ISSUE TITLE
Erd schemas show attribute bis

### ISSUE THREAD

**Issue by damienpolizzi** [dbeaver/dbeaver#4943]
Hello and good year to every one,

I wrote, a few week ago one issue asking the possibility to show attribute on erd schema for ea specific table.
Serge-rider wrote the code to deal with this request, and yesterday I tried it and I thought it was great !
But I realize now that the code operates good, but when you load the file another time, the properties are correctly saved but the display doesn't take into them.

Thanks for helping !

**Comment by serge-rider** [comment]
Yep, its a bug. Thanks for noticing.
