### ISSUE TITLE
DBeaver: Add function in data result grid to hide a column

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4944]
DBeaver - **Version 5.3.2 CE**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

It would be benificial if I in a data result grid could *right click* on the **grid column header** and choose **Hide column**.

This to hide certain columns that is not interesting for the current result.

**PS**. I am aware that you can already now hide columns by **right click** the data grid and choose
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Filter/Order** -> **Cusomize** and **uncheck** the column in the **ResultSet Order/Filter Settings**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;popup dialog.

**PPS**. In the database IDE I use for more intense database work (purchase product) I can beside the &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;above feature:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**o** Set focus to a data result grid.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**o** Press a \<keyboard shortcut\> to open a popup dialog (ie. I execute the IDE command).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**o** A dialog pops up where each table column names are shown and I can with an incremental
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;search+filter locate a column name.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**o** If I move focus to a column name and press \<Blank\> key that column name is overstriked in
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;the popup dialog (it will later be hidden).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**o** If I move focus to a column name row and press \<Blank\> key on a column name that is
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;overstriken, that column name will have the overstrike removed.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**o** If I press \<Enter\> key to OK and close the dialog, focus in the data result grid are moved to the
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;column name that had the focus in the popup dialog. Also the overstriken column(s) are hidden.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**o** If I press \<ESC\> key to CANCEL the popup dialog, it is closed and and no fucus is set. But the
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;overstriken column(s) are hidden.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![2019-01-08 18-38-26](https://user-images.githubusercontent.com/31191374/50848726-49193180-1375-11e9-823a-0fb979212e9c.png)

**Comment by serge-rider** [comment]
You already can do this from context menu. 
Grid context menu->Layout->Hide column(s)

**Comment by pdanie** [comment]
I missed that context menu. I was looking for a top level context menu choice so I did not look one level below. Thanks for the information though.

You can close this issue (if you don't feel like implement somthing even more fantastic than I described in the "PPS" note of this issue). \*big innocent smile\*
