### ISSUE TITLE
DBeaver: Add keyboard shortcut ESC to restore focus back to result grid from Activate filter/data editor

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4945]
DBeaver - **Version 5.3.2 CE**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

It would be benificial if I could move focus back to the data result grid  by using the **\<ESC\>** key, after having set a filter in the grid **Activate filter/data editor**.

Today I have to mouse click to get focus back to the data result grid.

**An better example scenario**

**o** Generate a data result grid with data.
**o** Run the IDE command **Activate filter/data editor** _(Ctrl+Alt+Shift+F)_ to move focus to the filter input.
**o** Enter the filter expression you want and finish with **\<Enter\>** to set filter.
**o** Press **\<ESC\>** key to move focus back to the data result grid.

**Comment by serge-rider** [comment]
Just press <kbd>Ctrl+Alt+Shift+F</kbd>again to move to the grid editor.

**Comment by pdanie** [comment]
Ok. Never thought about the same command that got me to the filter edit would get me back again.

Just thought that the ESC key was easier to remember. Thanks for the information.

**Comment by serge-rider** [comment]
ESC is already bound to "Cancel cell changes" action.
