### ISSUE TITLE
Missing results for DB object search when initially too many results match

### ISSUE THREAD

**Issue by jest** [dbeaver/dbeaver#4951]
#### System information: 
- Operating system (distribution) and version: Ubuntu 16.04
- DBeaver version: 5.3.2
- Java version: 1.8.0_191
- Additional extensions

#### Connection specification:
- Database name and version: SQL Server 2017-CU3
- Driver name: Microsoft driver
- Do you use security connection (SSH, Proxy, etc)? No

#### Describe the problem you're observing:

When searching for the DB object in databases with large schema (i.e. many DB objects), there are situations when the object I'm looking for is not present in the filtered results, although it exists in the database and can be found (using different, more restrictive filter).

For example, if I'm looking for the table `SolverTasks`, I start in `Goto Database Object` with typing letter `S`. Then the query is sent to the server:

```
SELECT * FROM the_database.sys.all_objects o WHERE o.type IN ('S','U','IT','V','SN','P','X') AND o.name LIKE @P0
```

with `@P0` set to `S%`. This causes fetching a lot of objects, including a lot of system ones starting with `sp_`. However, not all results are fetched (the number of rows read from the result set is limited?) as I see nothing starting with `Solver` on the list. When I continue to type `olver`, the list of objects becomes empty.

It looks like program optimization to reduce number of queries: the first fetch obtains the list of objects, and following do not send a query to the database but filter items already present on the list (as adding characters to the end of the query can only be filtering more, not adding previously filtered rows). This fails as initially not all objects were fetched.

The sane solution would be to issue the query after every character typed as long as the returned result set from the previous query was not read in whole.

The workaround is ATM to modify the search string by adding and removing a space character at the beginning. Weird thing is, adding different characters may not force the program to send a query...

Also weird is when I start typing with `%` — then no results are present, unless I modify the search string with space addition and removal, as described above.

IMHO, the logic behind the fetch-or-filter should be simplified and regularized.

#### Steps to reproduce, if exist:

1. `Navigate/Open Database object...`
2. Start typing with a character resulting in too many object names in the DB
3. Observe missing results you expect to see when you continue to type

**Comment by p91paul** [comment]
I'm hit by this issue as well. Also, sometimes copying the entire table name into the search box doesn't find anything; to find the object you need to

**Comment by uslss** [comment]
seems that issue is solved. Ticket closed
