### ISSUE TITLE
Autocomplete problem #4482 still present

### ISSUE THREAD

**Issue by alesc2000** [dbeaver/dbeaver#4952]
I still have this issue #4482 on Ubuntu 18, Dbeaver 5.3.2, DB: Postgres
When autocomplete fills my column name, it doesn't replace all the characters that I typed. These chars appear at the end of the column name.
![111](https://user-images.githubusercontent.com/19900533/50892036-41559d80-1406-11e9-92bf-16f22fd99ea0.jpg)
![222](https://user-images.githubusercontent.com/19900533/50892045-487cab80-1406-11e9-9824-5d348ee09f4a.jpg)

Thanks.

**Comment by serge-rider** [comment]
You need to enable this option:
![image](https://user-images.githubusercontent.com/6398845/51050826-2429f600-15e3-11e9-8bd5-77716cd944ae.png)

**Comment by alesc2000** [comment]
"Replace current word" is checked. As @p91paul said, is doesn't happen all the time, but to me it happens about 80% of the cases.

**Comment by mnt1979** [comment]
Where do I find "Replace Current Word" option on mac?

**Comment by jim256** [comment]
I also have "Replace current word" and it sometimes doesn't replace the current word.

OS X Mojave 10.14.6 (18G87)
DBeaver 6.1.4
Using Snowflake

**Comment by robDev123** [comment]
I also still have this issue even after updating, and checking the "Replace Current Word".

The problem seems to occur when I type 3 or fewer characters, otherwise it replaces it as desired. 

DBeaver 6.1.4
OSX 10.13.4

**Comment by serge-rider** [comment]
@uslss Can you reproduce it? I can't :(

**Comment by p91paul** [comment]
I can, there needs to be a bit of delay before proposals appear; while proposals are loaded, continue typing, and characters typed after proposals loading started will remain at the end.

**Comment by nmat** [comment]
This has happened to me also when trying to get autocomplete on tables.

Most of the time I get it when trying to type fast and do the completion.

**Comment by alesc2000** [comment]
I can't reproduce this anymore. Seems to be fixed for me in version 6.2.4
@nmat what version do you use?

**Comment by uslss** [comment]
fixed in scope of #6961
