### ISSUE TITLE
Upgrade eclipse tycho to v1.3.0 to support Java 11+

### ISSUE THREAD

**Issue by titou10titou10** [dbeaver/dbeaver#4953]
Current version of eclipse tycho is v1.3.0. This is the first and only version that supports Java 11 snd is compatible with eclipse 2018-12 (v4.10)
Currently DBeaver uses tycho v1.1.0

**Comment by serge-rider** [comment]
We can't upgrade to Tycho 1.3. I've tried that but build performance was decreased in 300-500%. Something is wrong with dependencies resolution in Tycho 1.3. Hopefully they will resolve this in the next version.

**Comment by serge-rider** [comment]
We'll upgrade to Tycho 1.3 or 1.4 in version 6.1.5
