### ISSUE TITLE
DBeaver: The Open Database Object does not search for T-SQL functions

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4955]
DBeaver - **Version 5.3.2 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

Seems there is a difference when using the **Open Database Object** to search for T-SQL procedures and functions. The T-SQL functions are not searched for.

**o** Start _DBeaver_, connect to a SQL Server database and open a **SQL Editor** window.

**o** Execute the SQL script below to create a T-SQL function and a T-SQL procedure.
```
CREATE FUNCTION dbo.TestFunc()
  RETURNS VARCHAR(64)
AS BEGIN
  RETURN 'OK';
END;

CREATE PROCEDURE TestProc
AS BEGIN
  SELECT 'OK';
END;
```
**o** Now open **Open Database Object** _(Ctrl+Shift+D)_.

**o** Search for the **TestProc** procedure.
&nbsp;&nbsp;&nbsp;**o** The **dbo.TestProc** is found. This is **OK**.

**o** Search for the **TestFunc** function.
&nbsp;&nbsp;&nbsp;**o** Noting is found. This is an **ERROR**.

**Comment by pdanie** [comment]
Do you think you can cram tis into the DBeaver release 5.3.3? The reason I ask is my hope is that version 5.3.3 will be a super/quality release.

**Comment by uslss** [comment]
issue is already fixed.
![image](https://user-images.githubusercontent.com/31996417/82095971-cfcbe480-9708-11ea-937e-d1c9bf080110.png)
