### ISSUE TITLE
DBeaver: SQL Assistant/Completion (manual or automatic) does not work with T-SQL procedures and functions

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4957]
DBeaver - **Version 5.3.2 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

The _DBeaver_ automatic (with **Automatic Assistant/Completion**) or manual (using **Content assist** _(Ctrl+Space)_ function) does not include T-SQL procedures and functions. They only works for table/view names and table/views column names.

**o** Start _DBeaver_, connect to a SQL Server database and open a **SQL Editor** window.

**o** Execute the SQL script below to create a T-SQL function and a T-SQL procedure.
```
CREATE FUNCTION dbo.TestFunc()
  RETURNS VARCHAR(64)
AS BEGIN
  RETURN 'OK';
END;

CREATE PROCEDURE TestProc
AS BEGIN
  SELECT 'OK';
END;
```
**o** In the **SQL Editor window** write the SQL script below. When you have the cursor after the end of the
&nbsp;&nbsp;&nbsp;"**Test**", let the **Automatic Completion** do its thing or activate the manual **Content assist** _(Ctrl+Space)_.
```
SELECT dbo.Test
```
**o** Here I would like to see the **TestFunc** in the result list, but the element names shown are totally
&nbsp;&nbsp;&nbsp;confusing (I'm using the _Northwind_ database).
```
+-----------------------------------+
| CustomerCustomerDemo              |
| Customer and Suppliers by by City |
+-----------------------------------+
```
**o** In the **SQL Editor window** write the SQL script below. When you have the cursor after the end of the
&nbsp;&nbsp;&nbsp;"**Test**", let the **Automatic Completion** do its thing or activate the manual **Content assist** _(Ctrl+Space)_.
```
EXECUTE dbo.Test
```
**o** Here I would like to see the **TestProc** in the result list, but the element names shown are the same as I
&nbsp;&nbsp;&nbsp;got before.
```
+-----------------------------------+
| CustomerCustomerDemo              |
| Customer and Suppliers by by City |
+-----------------------------------+
```

**Comment by pdanie** [comment]
Do you think you can cram tis into the _DBeaver_ release **5.3.3**? The reason I ask is my hope is that version 5.3.3 will be a super/quality release.

**Comment by LonwoLonwo** [comment]
Implemented here https://github.com/dbeaver/dbeaver/issues/10069
