### ISSUE TITLE
Error while creating UK/ FK

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#4961]
#### System information: 
- win 10 x64
- DBeaver version 5.3.2

#### Connection specification:
- SQLite

#### Describe the problem you're observing:
Error appears, while trying to create unique or foreign key

![image](https://user-images.githubusercontent.com/31996417/50951764-622df980-14bf-11e9-926d-b56a8566cc6e.png)

#### Include any warning/errors/backtraces from the logs

[new 9.txt](https://github.com/dbeaver/dbeaver/files/2744030/new.9.txt)

**Comment by serge-rider** [comment]
It is actually not a bug. SQLite doesn't support adding/removing constraints to an existing table.
However I've disabled these commands for SQLite to avoid confusion.
