### ISSUE TITLE
Incorrect icons view for drivers

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#4963]
#### System information: 
- Win 10 x64
- DBeaver version 5.3.2

#### Describe the problem you're observing:
Icons are shown rather bad, if the view is toggled
#### Steps to reproduce, if exist:

1.  Open "Create new connection" pop-up
2. Choose "Toggle view"
![image](https://user-images.githubusercontent.com/31996417/50952418-7246d880-14c1-11e9-9645-bdd72a5bae95.png)

**Comment by serge-rider** [comment]
The rest will be finished in #4121
