### ISSUE TITLE
Create table with namedparamter(s)

### ISSUE THREAD

**Issue by IntrumHuBd** [dbeaver/dbeaver#4965]
#### System information: 
- Windows 10 PRO
- 5.3.2
-JDK 8

#### Connection specification:
- PostgreSQL 9.6.8 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16), 64-bit
- PostgreSQL JDBC Driver
- No proxy no ssh.

#### Describe the problem you're observing:
While Java Spring boot JDBC allow:
create table my_table as select * from data where date_check > :start_date::date
create table my_table as select * from data where number> :min_number

Dbeaver gives me an error to create but execute the select w/o the create,

#### Steps to reproduce, if exist:

Simply select a query with named parameter then try to create with that select including the named paramater.

#### Include any warning/errors/backtraces from the logs

Query execution failed

Reason:
SQL Error [42601]: ERROR: syntax error at or near ":"
  Position: 1

**Comment by serge-rider** [comment]
By default parameters are disabled for DDL statements (like CREATE TABLE).
You can enable them in preferences:

![image](https://user-images.githubusercontent.com/6398845/51134860-bfbca000-1849-11e9-97d3-61a2f2c77b09.png)
