### ISSUE TITLE
Open table list going off screen if >99+ on two screens

### ISSUE THREAD

**Issue by lhimo** [dbeaver/dbeaver#4966]
On Windows, with a multiple screen setup, if I have more than 99 open tables and I click on the little arrows to view the list, the yellow panel goes off screen (see pic attached).
![screenshot 3011](https://user-images.githubusercontent.com/36077138/50955985-d1551f00-14ba-11e9-9ce4-ed661a3e9ea0.png)

System information: 
- Windows 10 
- DBeaver 5.3.2

**Comment by serge-rider** [comment]
Well, I'd suggest to avoid to open that many editors.

But if you need it by some reason you can use editors browser (CTRL+Shift+E)
