### ISSUE TITLE
Views with the same name could be created

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#4968]
#### System information: 
- Win 10 x64
- DBeaver version 5.3.2
#### Connection specification:
- Oracle 12
#### Describe the problem you're observing:
-Any number of views with the same name could be created and saved. After brunch refreshing, all the created views are replaced by the last one.

![2019-01-06_18h07_12](https://user-images.githubusercontent.com/31996417/50963061-bb585600-14dc-11e9-8144-05827b821bd7.gif)

**Comment by neiaberau** [comment]
ist the issue that the view is overwritten or that it is shown twice in the tree?

the overwriting is the intention of `create **or replace**`, 
to what degree is dependent on the database used. 
oracle, in constrast to postgres, allows this in almost all cases.
