### ISSUE TITLE
Export multiple tables data into only one final .sql

### ISSUE THREAD

**Issue by goxr3plus** [dbeaver/dbeaver#4972]
It is pretty clear how to export multiple tables data on different .sql files using : 

Right click on one of the selected libraries ( let's say we selected 4 tables ) ... export data ... etc etc ... but finally it produces like 4 .sql files which i have by hand to go and combine all of them to one sql file .

Is there any tool inside DBeaver that can export the data from multiple tables ..... ( simple tables without references to other tables ) to one only .sql file and not one sql file per selected table :) ?

Thank you :)

**Comment by serge-rider** [comment]
There is no such option in DBeaver. 
But generally this can be done by simple command line command: concatenate multiple files into one file. On Windows it is `COPY file1 file2 fileCombined`.

**Comment by p91paul** [comment]
Can this be turned into a feature request? Would mix very nicely with #2855 (which needs rescheduling)!

**Comment by serge-rider** [comment]
@goxr3plus I'm pretty sure that these invisible characters are BOMs (byto-order-mask prefixes). You can just disable this option in data export wizard settings.

**Comment by serge-rider** [comment]
@p91paul I think so. I'll mark it as duplicate of #2855
