### ISSUE TITLE
I need to connect my R script to a database on MS SQL Server through DBeaver? Is this possible? Can someone provide me with a step by step guide to doing this?

### ISSUE THREAD

**Issue by RGK1994** [dbeaver/dbeaver#4973]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by Sargul** [comment]
Why don't you use [RODBC](https://cran.r-project.org/web/packages/RODBC/index.html) to directly access SQL-Server?

What do you mean with "through DBeaver"?

**Comment by uslss** [comment]
there is no update on ticket for a long time.
Ticket closed
