### ISSUE TITLE
DBeaver Question: Difference between setting database in connection with Database/schema and with Default database/schema

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4976]
DBeaver - **Version 5.3.3 EA CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

What is then the difference between specifying a database name in the two cases below?

**o** The **Connection Settings** -> **Database/Schema**
**o** The **Connection Settings** -> **Initialization** -> **Default database/schema**

Seems they now have a similar function.

**Comment by uslss** [comment]
seems it is obsolete for current version
