### ISSUE TITLE
FR: Add option to open selected part of script in separate console

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#4978]
You can open DDL commands in separate console for many objects. I find this feature very useful and I think it may be a good idea to add similar feature to scripts also.

#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: CE 5.3.3.201901101930
- Java version: 1.8

#### Connection specification:
- Database name and version: Oracle 11g - 12c
- Driver name: native

**Comment by serge-rider** [comment]
I think we can reuse action Open in SQL Console. It should open new console with selected text - if there is a selection (and full script if there is no selection).

And could try to add Open in console command in regular SQL Editor.

**Comment by uslss** [comment]
Open in console command isn't working in regular SQL Editor.
