### ISSUE TITLE
DBeaver: Add possiblity to have multiple SQL Editors connected to different databases using the same Connection Source/Definition

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4980]
DBeaver - **Version 5.3.2 CE**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

It would be benificial if I could have multiple **SQL Editors** conncted to the same connection source/definition but be attached to different databases.

Today if I have a **SQL Editor** and change the **active** database in the **Database Navigator** the **Active catalog/schema** in the **SQL Editor** change. And if I change the **SQL Editor** combo box **Active catalog/schema** the **active** database in the **Database Navigator** change. This even if I have checked the **global** property **Database** -> **Editors** -> **SQL Editor** -> **Open separate connection for each editor**.

It would be more flexible if _DBeaver_ handled it like _Microsoft SQL Server Management Studio_ where the SQL Query Editor receives the **active** database when the editor starts up. After that the SQL Editor lives a life of its own. At least _DBeaver_ could do this when the global property **Open separate connection for each editor**.

**PS**. Only thing to keep in mind here is that when I use the **SQL Assistant Completion** (automatic or 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;manual) it should look in the database that the **SQL Editor** is connected to.

**PPS**. Maybe even that the **SQL Editor** could catch it when I change the current database using SQL
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Command like "**USE OtherDB;**" (code for Microsoft SQL Server / MySQL) and change what
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;database that currently are in use.

**Comment by serge-rider** [comment]
This is not so easy. Besides editor's toolbar we mark active database in the database navigator. And there is only one active database per connection. 
Thus having different active databases for different editors may be confusing. 

Although we could change active db according to current editor (we'll need to determine it for active  editor after editor switch). But isn't it too smart behavior?

**Comment by ceinmart** [comment]
Not sure if what I will suggest here will attend the @pdanie request. 
I have the situation where for oracle and informix database usually I need to connect with 3 differnt username/logon simultaneous to the same datasource .
The **Database** -> **Editors** -> **SQL Editor** -> **Open separate connection for each editor** option, doesn't attend at all because the new SQL Editor open the new connection with the same user already logged at the original session, even if the datasource have no user/password saved.

-- 

My suggestion , new feature is : 

- Have a option **New connection SQL Editor**
  They should open a new connection for the same current datasource, but if this datasource is set to ask the username, they should ask , not reuse the actual username.
- At the toolbar, when click at **New SQL Editor** holding **shift** , is the shortcut to the option above.

**Comment by p91paul** [comment]
The difference here is that SQL Server database and user concepts are different. So you can change database without a new login, during the same connection.

Instead in Oracle user==schema, that's why you need to use different logins and different connections.

**Comment by ceinmart** [comment]
Hi @p91paul , 
Yes, the concept of Oracle is different from every else, but the way to connect is the same, I don't see why this could complicate something at my suggestion. 
As far I know, if you have the grants, Dbeavre with Oracle, you can change the schema in use, but even you cannot, this only enforce my suggestion to allow multiple connections from the same data source.

**Comment by mlt** [comment]
On a probably related note... Changing active database/instance in catalog/schema dialog breaks already opened object editor. For example, if I open some table or stored procedure by double clicking it and then choose different database, then active catalog/schema control becomes white and unresponsive and current object is effectively dead. That is it cannot be refreshed and such.

PostgreSQL 11.2

**Comment by ceinmart** [comment]
> My suggestion , new feature is :
> * Have a option **New connection SQL Editor**
> * At the toolbar, when click at **New SQL Editor** holding **shift** , is the shortcut to the option above.

Improving my suggestion :

 * To avoid conflict between the data source tree and multiple opened connection for the same data source, for each new connection, create new virtual _datasources_ for each connection made. I think this should not be difficult and will keep the object tree separated for each connection. 
When the connection is finished they object tree is destroyed.
To make easy the identification, allow to set what show at the description, like Session ID or the user logged.

Here is a little art, how what I imagine they should work when have 3 connection to the same data source.

![image](https://user-images.githubusercontent.com/7062410/54026963-7e2bdf80-417e-11e9-8882-71ff14eed5bb.png)

**Comment by rdp** [comment]
If this is a feature request to be able to run two queries simultaneously against the same DB (which DBeaver appears not able to do at present?) +1 from me!

**Comment by kseniiaguzeeva** [comment]
The feature discribed in first message is already implemented (you can select different schemas/databases in different SQL Editors for one connection).

Please create new tickets for other feature requests.

**Comment by ceinmart** [comment]
New ticket opened: #8651
Thanks
