### ISSUE TITLE
Export to CSV No Longer Remembers Settings

### ISSUE THREAD

**Issue by brianspo** [dbeaver/dbeaver#4985]
#### System information: 
- Windows 10 Enterprise
- DBeaver 5.3
- Java 1.8.0_77

#### Connection specification:
- Oracle Enterprise 12.1.0.2.0
- Oracle JDBC Driver 12.2.0.1.0
- Direct connect (no tunnel/proxy)

#### Describe the problem you're observing:
Until some point quite recently, DBeaver would remember my previously-used settings when performing an export to CSV.  In particular I want to export to unquoted, tab-separated .TXT files instead of the default CSV format.  I do this regularly, and DBeaver wouldn't require me to specify my settings every time but would default to the previous settings.

#### Steps to reproduce, if exist:

1. Right-click in results grid and select Export Resultset...
2. Select CSV
3. Change some settings.  For example, change extension to "txt", check "quote never", and change separator character to tab (which is annoying as you have to paste in a literal tab, not "\t".
4. Complete the operation.
5. Perform the export on another resultset, selecting CSV again.

Previously the settings in Step 3 would default to whatever I chose previously.  Now I have to set them every. single. time.

#### Include any warning/errors/backtraces from the logs
Nothing in the logs that's interesting.

**Comment by serge-rider** [comment]
Thanks for the bug report.

CSV settings save was broken after adding of CSV import and data transfer wizard refactoring. Importer/exporter settings overwrite each other.

**Comment by brianspo** [comment]
Interestingly this seemed to coincide with the expiration of my license.  I requested a trial license and restarted DBeaver and its behaving as before now.

**Comment by serge-rider** [comment]
This is a "floating bug", it happens in 50% cases or so.
