### ISSUE TITLE
Question: Is it possible to invoke `In-context Debugging`?

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4988]
pgAdmin has [this](https://www.pgadmin.org/docs/pgadmin4/dev/debugger.html)

Is it possible in DBeaver to invoke `In-context Debugging`?

I do not see the button in interface to set breakpoint:

![__](https://user-images.githubusercontent.com/799021/51072199-89263000-1665-11e9-9949-5f8a91219f80.jpg)

**Comment by serge-rider** [comment]
To set breakpoint you can double click on the left ruler column:
![image](https://user-images.githubusercontent.com/6398845/51072570-efb24a80-1673-11e9-9f56-6a4b6fa7497b.png)

To run a debugger use context menu (or main toolbar):
![image](https://user-images.githubusercontent.com/6398845/51072578-343de600-1674-11e9-9c93-929eb2fc2d73.png)

**Comment by KES777** [comment]
`Toggle breakpoint` does nothing: no changes in interface, no error occur
