### ISSUE TITLE
Can't create foreign keys on MySQL Table

### ISSUE THREAD

**Issue by cjgmj** [dbeaver/dbeaver#4989]
Hi,

I'm trying to create new foreign keys on MySQL Table with Spring but it isn't work.

![image](https://user-images.githubusercontent.com/16681783/51073458-5124ea00-1671-11e9-95a6-d634028772c9.png)

Spring create the foreign key but I can't see it on DBeaver.

![image](https://user-images.githubusercontent.com/16681783/51073475-89c4c380-1671-11e9-844d-72ff5086e4f7.png)

I'm trying create it manually, and it runs smoothly

![image](https://user-images.githubusercontent.com/16681783/51073490-ecb65a80-1671-11e9-8c9e-a0752835fc78.png)

But it's like don't do anything because I can't still see the keys.

I'm using DBeaver 5.3.1.

Thank you in advance.

**Comment by serge-rider** [comment]
I think you just need to refresh your table (press F5 in the navigator tree).

**Comment by cjgmj** [comment]
> I think you just need to refresh your table (press F5 in the navigator tree).

I did, no changes.

**Comment by serge-rider** [comment]
Hm. I can't reproduce this.
Maybe you are working in transactional mode (manual commit)? If so then try to commit transaction before refresh.
If not then I have no clues so far. Post some more details (e.g. small gif video would be helpful).

**Comment by cjgmj** [comment]
> Hm. I can't reproduce this.
> Maybe you are working in transactional mode (manual commit)? If so then try to commit transaction before refresh.
> If not then I have no clues so far. Post some more details (e.g. small gif video would be helpful).

Here have a little video.

[DBeaver.zip](https://github.com/dbeaver/dbeaver/files/2752250/DBeaver.zip)

**Comment by serge-rider** [comment]
Weird. Could you try to set active database in your connection to db_springboot (in connection settings or in the database navigator context menu -> set active) ?

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/51077092-77b74500-16b2-11e9-9a7c-7c551006f0f1.png)
or
![image](https://user-images.githubusercontent.com/6398845/51077099-91f12300-16b2-11e9-9a69-eda58a77b3e9.png)

**Comment by cjgmj** [comment]
It doesn't work.

![image](https://user-images.githubusercontent.com/16681783/51077134-65350f80-16a2-11e9-90aa-df834ee9356a.png)

**Comment by serge-rider** [comment]
What MySQL server version do you have? 
Are you using INNODB engine? 
If you are using MySAM then it just doesn't support foreign keys.

**Comment by cjgmj** [comment]
> What MySQL server version do you have?
> Are you using INNODB engine?
> If you are using MySAM then it just doesn't support foreign keys.

It was using MyISAM, I just change it to INNODB and it works.

Thank you very much.
