### ISSUE TITLE
Feature request: Active Directory support for Microsoft driver

### ISSUE THREAD

**Issue by yosefdi** [dbeaver/dbeaver#4990]
DBeaver can connect to SQL server with Azure Active Directory authentication, but this requires complex configuration steps, see https://github.com/dbeaver/dbeaver/issues/3647 and https://docs.microsoft.com/en-us/azure/kusto/api/tds/clients#dbeaver-533-and-above

It would help people if AAD support will be made out of the box. Also would be great if there will be no need to alter driver properties for each connection.

Currently the only supported AAD authentication option is "password'. It would be nice if 'integrated' option that takes current logged in user would be supported as well.

See conversation https://github.com/dbeaver/dbeaver/issues/4892 for some more information.

**Comment by serge-rider** [comment]
Please check how it works in Early Access version (https://dbeaver.io/files/ea).
New driver supports all standard auth schemas inlcuding AD and Kerberos.

But I have problems with real AD testing because I'm not in Windows corporate environment right now.

**Comment by serge-rider** [comment]
Note: in order to use AD Integrated authentication you need to use Azure SQL Database driver (instead of standard SQL Server driver). Because additional auth libraries were included only in Azure driver config (because of big size of driver).

Maybe we'll change this in future.

**Comment by yosefdi** [comment]
I didn't notice UI changes is driver management page and in new connection UI.
When I tried to create new connection to SQL Azure database, with exactly the same steps I did before, I am getting the following error:

**The TCP/IP connection to the host yoseftest1.database.windows.net, port 1433 has failed. Error: "null. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".**

Looks like this change introduced a regression.

**Comment by serge-rider** [comment]
Please try to get EA version again (https://dbeaver.io/files/ea), previous build was broken on our build machine and I didn't mention that.

**Comment by yosefdi** [comment]
Looks great! The connection page shows authentication option and trust certificate check box which is on by default.

Since I install over the previous version and the driver is already configured, I don't know if adding adal4j artifact is a necessary step or it is part of the driver out of the box. Should the instructions to add it manually be removed?

**Comment by serge-rider** [comment]
adal4j  is included in Azure driver config, you can just reset driver settings to default (button in the bottom)

**Comment by yosefdi** [comment]
I've tried to set to default (and download), but then the driver stops working with the following error:

Unexpected driver error occurred while connecting to database
  com/microsoft/aad/adal4j/AuthenticationException
  com/microsoft/aad/adal4j/AuthenticationException
    com.microsoft.aad.adal4j.AuthenticationException
    com.microsoft.aad.adal4j.AuthenticationException

(btw, adal4j does not appear in the list of libraries - i don't know if it is by design).

When I configure it back to include adal4j 1.6.0, it works again.

**Comment by serge-rider** [comment]
Well, I'll just configure version 1.6.0 by default (instead of the latest).


Dinerstein notifications@github.com:

**Comment by yosefdi** [comment]
👍

**Comment by yosefdi** [comment]
It is strange, but I still get the same error if I reset driver settings to default and it still returns to work once I add adal4j manually in driver settings.

**Comment by serge-rider** [comment]
Yep. That's because DBeaver downloaded some version of adal4j  and cached this information in driver settings. These settings aren't reset by this button.
This can reset by deleting file drivers.xml in .dbeaver4\.metadata\.plugins\org.jkiss.dbeaver.core\ but I wouldn't but it makes sense to make a backup first.

Also you can go to the driver edit dialog, click on Download/Update and choose right version from dropdown: 
![image](https://user-images.githubusercontent.com/6398845/51089867-2461f700-1785-11e9-9043-8d474cc361ea.png)

**Comment by yosefdi** [comment]
Oops, it was my fault. I continued to use "MS SQL Server/Microsoft driver" and now I notice that I should take "Azure/Azure SQL database". It is the right one and it has adal4j in its artifacts.
Thanks!

**Comment by yosefdi** [comment]
I've checked and there is no problem with the latest adal4j 1.6.3. It works as well. It was just my bad, I didn't use the right driver and upon restoring to default adal4j library was just removed.

**Comment by yosefdi** [comment]
Please notice that while AAD password works, AAD integrated doesn't work.

When I try integrated, it pops up credentials window (which it should do under integrated mode). Even if I fill this window with right user and password, the connection eventually fails with:

Failed to authenticate the user  in Active Directory (Authentication=ActiveDirectoryIntegrated).
  com.microsoft.aad.adal4j.AuthenticationException: Server returned HTTP response code: 401 for URL : https://msft.sts.microsoft.com/adfs/services/trust/13/windowstransport
  com.microsoft.aad.adal4j.AuthenticationException: Server returned HTTP response code: 401 for URL : https://msft.sts.microsoft.com/adfs/services/trust/13/windowstransport
    Server returned HTTP response code: 401 for URL : https://msft.sts.microsoft.com/adfs/services/trust/13/windowstransport
    Server returned HTTP response code: 401 for URL : https://msft.sts.microsoft.com/adfs/services/trust/13/windowstransport

**Comment by serge-rider** [comment]
It is "Unauthorized" error code. Something is wrong with credentials of with Kerberos config I guess..
