### ISSUE TITLE
DBeaver: Persist function/procedure/view/triggers does not work with SQL Server 2014

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4993]
DBeaver - **Version 5.3.2 CE** - **EA 13-Jan-2019 12:30**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014**

Seems the _DBeaver_ implementation of persisting databas objects like functions, procedures, views, triggers etc. requiring a minimum of SQL Server 2016.

This since they all prefix updating of the database elements (persisting) with "DROP XXXXX **IF EXIST**;"
The use of "IF EXIST" was first released in the _Microsoft SQL Server 2016_. So for older databases that generate an error.

**o** Start _DBeaver_ and connect to a _MS SQL SERVER 2014_ (or older).
**o** In the **Database Navigator** expand the database node for **Views** / **Procedures** / etc.
**o** Double click on the choosen database element.
**o** Choose the database element **Properties** tab.
**o** Click on the **Definition** button on the left.
**o** Add a **blank/space** character in the definition.
**o** Close the database element tab.
**o** Choose **Yes** in the popup dialog "Object "Xxxxxx" was changed. Do you wan to persist these changes
&nbsp;&nbsp;&nbsp;in database?".
**o** Noticed the faulty "DROP XXXXX IF EXIST dbo.Xxxxxx GO" on the first line.
**o** Choose **Persist** button to save the changes in the database.
**o** The error message **Incorrect syntax near thekeyword 'IF'.** are showned.

A much better way to solve it is to change "CREATE XXXXXXXX \<myelement\>" with a "**ALTER** XXXXXXXX \<myelement\>".

**The use of "ALTER" (instead of "DROP") has the benifit**:

**o** This work with older database servers than _SQL Server 2016_.

**o** Also and **very important**. If I have set user rights on the database element I loose them if I first
&nbsp;&nbsp;&nbsp;make a "DROP ....". If I instead use "ALTER ..." those extra properties on the databas element is kept.

**Comment by serge-rider** [comment]
Good point. Although using ALTER won't be that easy. 

Currently we can just pass back DDL read from the server (CREATE VIEW ...) on view save. 
For ALTER we'll have to modify the DDL generated on server-side.

**Comment by pdanie** [comment]
Does not feel like "rocket" science to make a search and replace of "CREATE" to "ALTER".

If you feel that is too risky (full respect) or too hard (even more respect), maybe an older SQL command could be used instead.
```
IF OBJECT_ID('dbo.Product) IS NOT NULL
  DROP TABLE dbo.Product;
```

**Comment by serge-rider** [comment]
Its not a big deal but potentially risky. DDL may contain leading whitespaces, comments, etc. 
Also ALTER TRIGGER script must contain trigger schema name while CREATE can omit it.

But it is much better than DROP+CREATE after all.

**Comment by pdanie** [comment]
The reason I test as much as I can is my hope is that version **5.3.3** will be a super/quality release for SQL Server users like myself.

**PS**. If you generate a new EA I can test it too (I want to help as much as is possible), Just tell me if I start to get annoying or obnoctious, I can take it. \*big innocent smile\*

**PPS**. Hope you can cram issues #4955 and #4957 into the release **5.3.3** as well.

**Comment by pdanie** [comment]
I have now tested the EA version **13-Jan-2019 18:52** and it **WORKES SUPER GREAT**.

**PS**. To be honest I never thought you would go for the "ALTER" solution, but man it resultet in something
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;very good. Thanks a million!

**Comment by serge-rider** [comment]
Good) 
> Just tell me if I start to get annoying or obnoctious, I can take it.

Absolutely not, having quality testing is the thing which helps me a lot , thank :) Sometimes I have too many different tasks/tickets and I can't react on new ones quickly. Please, just remind me if I'll miss something important.

Not sure about 4955 and 4957 in the next version, I have to finish more urgent tasks and then I will check them.

**Comment by pdanie** [comment]
Quite ok.

The reason I hope for a stable/quality version of _DBeaver_ is that I repack _DBeaver_ for the company I work for. We use _DBeaver_ for SQL Server databases both inhouse but also at our customers sites (we have about 1200+ customer installations). Last _DBeaver_ version I repacked was version **5.1.4** so more than 1/2 year ago. Currently I have great hopes for version **5.3.3**.
