### ISSUE TITLE
Syntax error (missing right parenthesis) on some match-recognize expression

### ISSUE THREAD

**Issue by p3consulting** [dbeaver/dbeaver#4994]
Here is a query running fine in SQL Developer but failing in DBeaver with a syntax error (missing right parenthesis) when using "{- pattern -}" syntax in a match_recognize expression:

Tried with default ORACLE connection (both version 4 and latest 5.3.2 CE)
and with custom one using ojdbc8.jar

```
WITH t AS (
 	select to_DATE( '2007-01-01', 'YYYY-MM-DD') AS start_date, to_DATE( '2007-01-15', 'YYYY-MM-DD') AS end_date FROM dual 
 	UNION all
	select to_DATE( '2007-01-03', 'YYYY-MM-DD') AS start_date, to_DATE( '2007-01-10', 'YYYY-MM-DD') AS end_date FROM dual 
 	UNION all
	select to_DATE( '2007-01-12', 'YYYY-MM-DD') AS start_date, to_DATE( '2007-01-25', 'YYYY-MM-DD') AS end_date FROM dual 
 	UNION all
	select to_DATE( '2007-01-20', 'YYYY-MM-DD') AS start_date, to_DATE( '2007-02-01', 'YYYY-MM-DD') AS end_date FROM dual 
 	UNION all
	select to_DATE( '2007-02-05', 'YYYY-MM-DD') AS start_date, to_DATE( '2007-02-10', 'YYYY-MM-DD') AS end_date FROM dual 
 	UNION all
	select to_DATE( '2007-02-05', 'YYYY-MM-DD') AS start_date, to_DATE( '2007-02-28', 'YYYY-MM-DD') AS end_date FROM dual  
 	UNION all
	select to_DATE( '2007-02-10', 'YYYY-MM-DD') AS start_date, to_DATE( '2007-02-15', 'YYYY-MM-DD') AS end_date FROM dual 
 	UNION all
	select to_DATE( '2007-03-01', 'YYYY-MM-DD') AS start_date, to_DATE( '2007-03-02' , 'YYYY-MM-DD') AS end_date FROM dual  
 	UNION all
	select to_DATE( '2007-03-03', 'YYYY-MM-DD') AS start_date, to_DATE( '2007-03-16', 'YYYY-MM-DD') AS end_date FROM dual 
)
select start_gap, end_gap from t
match_recognize(
  order by start_date
  measures max(end_date) start_gap, next(start_date) end_gap
  all rows per match
  pattern((A| {- B -} )+)
  define A as max(end_date) < next(start_date)
);

```

**Comment by serge-rider** [comment]
I'm not a pro in Oracle expressions. However I see the different error:
`SQL Error [931] [42000]: ORA-00931: missing identifier`
Right before first bracket.

Anyhow, brackets are used in Oracle JDBC as a special construct for code execution. This feature can be disabled in preferences:
![image](https://user-images.githubusercontent.com/6398845/51090585-f5508300-178e-11e9-918a-97ea50d348c0.png)

Could you try it?

**Comment by p3consulting** [comment]
1. It's got executed a single SQL statement not as a script and disabling that flag doesn't change anything whatever the way the SQL got executed (ctrl-enter or alt-x)
2. as stated above this statement works perfectly well when executed in SQL Developer both as a script or a single SQL statement
and of course it works also in SQL*Plus and sqlcl 
(will try in TOAD tomorrow if I don't forget...)

**Comment by p3consulting** [comment]
Good news but here even with same driver and CE edition doesn't work
![capture d ecran 2019-01-14 a 20 28 12](https://user-images.githubusercontent.com/162140/51135728-fe972980-183a-11e9-987e-719303ee70d9.png)

must be a small diff in some setting…

**Comment by serge-rider** [comment]
Note: I disabled escape processing (see above). Without this option query fails.

**Comment by p3consulting** [comment]
Yes I suspect that one but how do you disable escape processing for a custom driver ?
I can access it only for built-in ORACLE one...

**Comment by serge-rider** [comment]
It is just the option in DBeaver preferences. It works with any Oracle driver. Just try to turn it on.

**Comment by p3consulting** [comment]
on/off it doesn't change anything…

**Comment by serge-rider** [comment]
That's odd. Then I can't reproduce it. 
Please copy-paste full error message/stacktrace (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by p3consulting** [comment]
wait: now it works with connection using built-in ORACLE driver…
strange…

**Comment by serge-rider** [comment]
Ah, I see. You created custom driver using Generic provider? Then yes, this option won't work.

**Comment by p3consulting** [comment]
Yes exactly that's the "problem", meantime you sent latest message, I tested by copying the original ORACLE connection type instead of creating one from the Generic and now it works...

Good news… thank you
