### ISSUE TITLE
DBeaver: Unable to close database element tab if confirmation "Persist object changes" is set to ALWAYS

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4995]
DBeaver - **Version 5.3.3 CE** - **EA  13-Jan-2019 18:52**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

I have set the global **Database Confirmations** for **Persist object changes** to **Always** there is no way to close the database element tab without updating the database element.

**o** Start _DBeaver_.
**o** Change the **global** property **Database** -> **Confirmations** -> **Persist object changes** to **Always**.
**o** Connect to a database that contains views or procedures.
**o** Expand the tree in the **Database Navigator** and double click on a database element.
**o** Click the **Source** button on the left in the database element tab.
**o** In the source, add a blank/space character (does not change, but flag for changed content).
**o** Close the database element tab.
**o** There are now **no way** to cancel the changes made and close the database element tab.

Maybe there ought to be yeat another button in the **Persist Changes** dialog, or an extra question when I press the **Cancel** button.

**Comment by serge-rider** [comment]
Well. I thought that's the point of settings "Persist changes" to Always? It is a dangerous thing but that's user choice.

The only way to avoid this is to reject changes manually before closing editor.

**Comment by serge-rider** [comment]
I think we'll remove "Remember choice" toggle from this confirmation. As well as from two other data loss confirmations. 
It is too dangerous and it is possible that user will check by accident.

**Comment by pdanie** [comment]
I think that is sound thinking. Go for it!
