### ISSUE TITLE
blinking request and response window

### ISSUE THREAD

**Issue by ilnurgi** [dbeaver/dbeaver#4996]
hello

On version 5.3.2, blinking of windows began, look at the video
operating system centos 7, gnome

# uname -sr
Linux 3.10.0-862.14.4.el7.x86_64

https://youtu.be/viCDGj3mZf4

**Comment by serge-rider** [comment]
Please check for a workaround in #4991

**Comment by ilnurgi** [comment]
export GTK_IM_MODULE=ibus
it's work for me
thanks
