### ISSUE TITLE
[postgres] no deferrable options when viewing/editing foreign keys

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#4997]
#### System information: 
- Operating system (distribution) and version: mac mojave 10.14.2
- DBeaver version: 5.3.1
- Java version: java version "1.8.0_192"
- Additional extensions

#### Connection specification:
- Database name and version: postgres 10.4 (on rds)
- Driver name: postgres jdbc driver (downloaded by dbeaver)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
When I look at the properties of a foreign key, either from the table properties tab (for example when viewing a table definition --> foreign keys) or in the FK property tab (right clicking one of the FKs and choosing "Edit Foreign Key") the "DEFERRABLE" options are missing - even if the FK **is** deferrable according to source.

**Comment by serge-rider** [comment]
Good point.
