### ISSUE TITLE
Bookmark. Browse and popup menu

### ISSUE THREAD

**Issue by VPetrow** [dbeaver/dbeaver#5003]
#### System information: 
Win10 64 Bits
DBeaver 5.3.3

#### Connection specification:
PostgreSQL

#### Describe the problem you're observing:

I like bookmarks idea. But have some problems:
 I can add "schema" as bookmark. When i open it - its OK, but when i "browse" it - its doesnt work.
 I can add "stored procedure" as bookmark. But i dont see "Execute stored procedure" and "Generate DDL SQL" in popup menu.

If its too complex to resolve this issues you can just add possibility to "Navigate" to linked object. Thx

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/52916371-9af79480-32ef-11e9-8bb3-238b4090e7a0.png)
