### ISSUE TITLE
Disable JDBC masks escape by default

### ISSUE THREAD

**Issue by Gipada** [dbeaver/dbeaver#5007]
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version : tried many, problem appears at 5.2.5, 5.2.4 is fine
- Java version : embedded
- Additional extensions : none

#### Connection specification:
- Database name and version : RDB, unknown version
- Driver name : RDB driver 7.3.5.0.3
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When opening table view on Tab "Properties", the "columns" view is empty on 5.2.5+. Also everything related to DDL does not work anymore (like table copy for exemple).
The data view shows correct data and columns.
It only happens with RDB databases, Oracle ones work fine.

#### Steps to reproduce, if exist:
Install 5.2.5+, open connection to RDB and open properties view of any table.

#### Include any warning/errors/backtraces from the logs
Nothing in Error log

**Comment by serge-rider** [comment]
- Please check debug log
- Try to enable "Omit single catalog/schema" options in the driver advanced properties:
![image](https://user-images.githubusercontent.com/6398845/51173783-364bb300-18c7-11e9-84b9-6e6a64cd516b.png)

**Comment by Gipada** [comment]
First of all thank you very much for this quick answer !

I've tried both options without luck on 5.3.2 version.

Here are both log files. To have these, I did the following :
 - Launch DBeaver 5.3.2
 - Open connection to DB, 
 - go to the "tables" drop down menu, 
 - select a table 
 - double-click on it
 - Nothing appears in the Properties view (I also attach a view exemple just to be sure we talk about the same thing)
![dbeaver_empty_view](https://user-images.githubusercontent.com/13124582/51176025-2bd7ec00-18bc-11e9-9c00-e8b82c18dd3b.png)

 - close DBeaver
 - anonymise some DB related data in log files (names and UUID)


From what I see, nothing in the logs except a binding problem on my CTRL+D bind.
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/2759283/dbeaver-debug.log)
[dotLogFile.log](https://github.com/dbeaver/dbeaver/files/2759286/dotLogFile.log)

dotLogFile.log is actually ".log" file.

**Comment by serge-rider** [comment]
I see. Then turn off parameter "Escape LIKE masks in search queries"

**Comment by Gipada** [comment]
Perfect, it works and I have my columns in the view. Thank you very much ! :)

Just for my curiosity, what does this option and why did it affect Columns view ?

**Comment by serge-rider** [comment]
It disables JDBC driver feature for identifiers escape. All identifiers which have underscores have to be escaped. But many drivers doesn't support this feature.

I think we should enable this option by default.

**Comment by Gipada** [comment]
Ok, thnkas for the info. 

I agree, it seems reasonable to enable this option by default. Or at least try with it if driver response is suspicious (no columns for example, it happens but is not the most common case)
