### ISSUE TITLE
"Utility mysqldump not found" on Fedora with Flatpak

### ISSUE THREAD

**Issue by aliasbody** [dbeaver/dbeaver#5008]
#### System information: 
- **Operating system (distribution) and version**
Fedora 29
- **DBeaver version**
5.3.1 - Flatpak
- **Java version**
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
- **Additional extensions**

#### Connection specification:
- **Database name and version**
Any
- **Driver name**
MySQL/MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
Yes, SSH

#### Describe the problem you're observing:
Utility mysqldump not found in client home error appears simply because it can't list the mysql packages from within the /usr/bin folder (where they are). When installing directly we can find them and thus use the mysqldump.

This can be related to:
- Flatpak configuration
or
- Selinux settings from Fedora

#### Steps to reproduce, if exist:
1 - Install the latest version of DBeaver from flatpak in a Fedora installation
2 - Connecto to a MySQL / MariaDB database
3 - Associate a client path
4 - Try to make a dump of a database

**Comment by EvanWashkow** [comment]
I made this case on the Flathub side because I didn't know: https://github.com/flathub/io.dbeaver.DBeaverCommunity/issues/8

In total, I've tried:
`/var/run/host/usr`
`/var/run/host/usr/bin`
`/var/run/host/usr/bin/mysql`

**Comment by lasombra** [comment]
Same problem here with DBeaver 6.0.0 and Fedora 29.
`/var/run/host/usr` is not exposed.

**Comment by dubst3pp4** [comment]
Same here with Ubuntu 18.10 and DBeaver 6.0.0.

**Comment by spoonsauce** [comment]
Same issue. Fedora 29 + DBeaver 6.0.1.

**Comment by turkeryildirim** [comment]
Same with Kubuntu 17.10 and DBeaver 6.0.1

**Comment by mrksdiehl** [comment]
Got the same issue on Fedora 29 with KDE

**Comment by mpotra** [comment]
Same issue on Fedora 30 with DBWeaver from flatpak.

`mysqldump` is in `/usr/bin` but trying to dump a database errors with `"IO Error: Utility 'mysqldump' not found in client home '/usr/bin'"`.

`dbweaver-ce` downloaded and installed from [website RPM](https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm) works fine.

**Comment by HenriqueOmena** [comment]
i have same issue on ubuntu 19.10 some one has idea how to fix it ?

**Comment by grimurd** [comment]
As noted in [this flathub issue](https://github.com/flathub/io.dbeaver.DBeaverCommunity/issues/8), there are extensions available for the dbeaver package on flathub that provide postgres and mysql clients.

```
flatpak install flathub io.dbeaver.DBeaverCommunity.Client.mariadb
flatpak install flathub io.dbeaver.DBeaverCommunity.Client.pgsql
```

When selecting clients in dbeaver make sure the path is set to /app/clients

**Comment by happyxhw** [comment]
no way to select /app/clients, any idea?

![image](https://user-images.githubusercontent.com/44490504/103066299-8a9f5780-45f3-11eb-9cab-49e4932d44f4.png)

**Comment by happyxhw** [comment]
can not find /app/clients, so i select this, and it works
```
/var/lib/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin
```

![image](https://user-images.githubusercontent.com/44490504/103119422-360ce280-46ae-11eb-800f-3a6d40ba9398.png)

**Comment by seth100** [comment]
> can not find /app/clients, so i select this, and it works
> 
> ```
> /var/lib/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin
> ```
>

What about when DBeaver is installed in the user local env (`flatpak install --user flathub io.dbeaver.DBeaverCommunity` on `Pop_OS! 20.10` verson `7.3.1.202012201616`)?
I found:
```
~/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin
```
but when setting it in the DBeaver configuration from the "Local Client" dropdown it still does **not** work for me and I get:
```
2021-01-01 12:08:20.143 - IO error: Utility 'mysql' not found in client home '/home/MYHOME/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin' (/home/MYHOME/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin)
2021-01-01 12:08:20.143 - java.io.IOException: Utility 'mysql' not found in client home '/home/MYHOME/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin' (/home/MYHOME/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin)
	at org.jkiss.dbeaver.utils.RuntimeUtils.getNativeClientBinary(RuntimeUtils.java:121)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLScriptExecuteHandler.fillProcessParameters(MySQLScriptExecuteHandler.java:55)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLScriptExecuteHandler.fillProcessParameters(MySQLScriptExecuteHandler.java:1)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.getCommandLine(MySQLNativeToolHandler.java:73)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLScriptExecuteHandler.getCommandLine(MySQLScriptExecuteHandler.java:42)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLScriptExecuteHandler.getCommandLine(MySQLScriptExecuteHandler.java:1)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:165)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:248)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:54)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

Any help please?

**Comment by pinzon** [comment]
@seth100 I had the same problem, after some research I installed https://flathub.org/apps/details/com.github.tchx84.Flatseal and added the folder of the extensions to the allowed folder and pg_dump worked.

EDIT: I had to restart DBeaver and probably there is a better way to write the extension folders path

![Captura de pantalla de 2021-01-04 11-17-57](https://user-images.githubusercontent.com/18080804/103555610-26438a00-4e76-11eb-87e4-28462e8718cb.png)

**Comment by seth100** [comment]
> @seth100 I had the same problem, after some research I installed https://flathub.org/apps/details/com.github.tchx84.Flatseal and added the folder of the extensions to the allowed folder and pg_dump worked.
> 
> EDIT: I had to restart DBeaver and probably there is a better way to write the extension folders path
> 

@pinzon wow great, it works like a charm!
Thank you

**Comment by guipassos** [comment]
In Ubuntu 20.04, I had the same problem. I decided the following way:

Install mysql-client:
```bash
sudo apt-get install mysql-client
```
Check all permissions on the application, as shown in the image below.
![Screenshot from 2021-02-08 13-10-55](https://user-images.githubusercontent.com/9012209/107460352-b9877380-6b36-11eb-959c-cc250d4abd60.png)


Link the usr/bin folder to a dbeaver folder:
```bash
sudo ln -s /usr/bin ~/snap/dbeaver-ce/common/bin
```

Configure client folder on ubuntu as shown below, selecting the new folder.

![Screenshot from 2021-02-10 00-20-16](https://user-images.githubusercontent.com/9012209/107460365-c1dfae80-6b36-11eb-8940-a6ac803a7041.png)

/home/YOUR_USER/snap/dbeaver-ce/common/bin

**Comment by j0eii** [comment]
> > can not find /app/clients, so i select this, and it works
> > ```
> > /var/lib/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin
> > ```
> 
> What about when DBeaver is installed in the user local env (`flatpak install --user flathub io.dbeaver.DBeaverCommunity` on `Pop_OS! 20.10` verson `7.3.1.202012201616`)?
> I found:
> 
> ```
> ~/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin
> ```
> 
> but when setting it in the DBeaver configuration from the "Local Client" dropdown it still does **not** work for me and I get:
> 
> ```
> 2021-01-01 12:08:20.143 - IO error: Utility 'mysql' not found in client home '/home/MYHOME/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin' (/home/MYHOME/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin)
> 2021-01-01 12:08:20.143 - java.io.IOException: Utility 'mysql' not found in client home '/home/MYHOME/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin' (/home/MYHOME/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin)
> 	at org.jkiss.dbeaver.utils.RuntimeUtils.getNativeClientBinary(RuntimeUtils.java:121)
> 	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLScriptExecuteHandler.fillProcessParameters(MySQLScriptExecuteHandler.java:55)
> 	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLScriptExecuteHandler.fillProcessParameters(MySQLScriptExecuteHandler.java:1)
> 	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.getCommandLine(MySQLNativeToolHandler.java:73)
> 	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLScriptExecuteHandler.getCommandLine(MySQLScriptExecuteHandler.java:42)
> 	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLScriptExecuteHandler.getCommandLine(MySQLScriptExecuteHandler.java:1)
> 	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:165)
> 	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:248)
> 	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
> 	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:54)
> 	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
> 	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
> ```
> 
> Any help please?

1. Install flatseal
2. run flatseal
3. map the file volume to the path /var/lib/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin
4. you are now done!

https://j0eii.cwh-labs.com/linux-dbeaver-setup-guide/

**Comment by netdragonboberb** [comment]
Installing flatseal worked.

**Comment by devotoare** [comment]
Adding the path to Flatseal worked but none of the paths here were right for me. Mine was:

`/home/MYUSERNAME/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files`

On Pop 21.04

**Comment by ianchanning** [comment]
I hit what seems a related but new problem. The Client.pgsql pg_dump is v12.2 but I'm running postgres 14.5

```
~/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.pgsql/x86_64/stable/active/files/bin$ ./pg_dump --version
pg_dump (PostgreSQL) 12.2
$ pg_dump --version
pg_dump (PostgreSQL) 14.5 (Ubuntu 14.5-0ubuntu0.22.04.1)
```

So I get the following error:
```
/home/ian/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.pgsql/x86_64/stable/active/files/bin/pg_dump --verbose --host=localhost --port=5432 --username=dev --format=c --no-privileges --no-owner --file /home/ian/Downloads/dump-db-202209201558 -n public db
Task 'PostgreSQL dump' started at Tue Sep 20 15:58:29 CEST 2022
pg_dump: error: server version: 14.2 (Debian 14.2-1.pgdg110+1); pg_dump version: 12.2

pg_dump: error: aborting because of server version mismatch

Task 'PostgreSQL dump' finished at Tue Sep 20 15:58:29 CEST 2022
2022-09-20 15:58:29.465 - IO error: Process failed (exit code = 1). See error log.
2022-09-20 15:58:29.466 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:242)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:223)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:262)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:83)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by ianchanning** [comment]
Yes - unfortunately the flatpak pgsql client hasn't been updated for 3 years and still points to 12.2: https://github.com/flathub/io.dbeaver.DBeaverCommunity.Client.pgsql/blob/master/io.dbeaver.DBeaverCommunity.Client.pgsql.json

Anyway around this?

For now I just copy paste the commands that DBeaver creates and paste them into my terminal

**Comment by ianchanning** [comment]
I've created a PR to upgrade... https://github.com/flathub/io.dbeaver.DBeaverCommunity.Client.pgsql/pull/7

**Comment by apedicdev** [comment]
`/home/apedik/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/c787e1de2bf4e7bdb0cd1e4cbb39f0676ea2d3e2cc7e64a657a91f31cd03b8f5/files/bin/mysql -u ****** --host=localhost --port=3308 production_aug_07
Task 'MySQL restore' started at Tue Aug 08 05:31:04 CEST 2023
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)`

could it be due to the instance be on docker? I can do all other operations via the client

**Comment by SukhikhN** [comment]
PostgreSQL and MariaDB client flatpak extensions for DBeaver use outdated client versions, so I've found a way to use clients from the host OS.

1. You should allow access for DBeaver to the host OS libraries and executables using the `filesystem=host-os` option.
In Flatseal:
![Виділення_233](https://github.com/dbeaver/dbeaver/assets/2466722/0e4ece2f-c0a0-42e4-b511-d153c32a36e2)

2. Now host's `/usr`, `/bin`, `/lib`, `/lib32`, `/lib64`, `/sbin` will be accessible under the `/run/host` directory from DBeaver. My PostgreSQL client is located in `/usr/lib/postgresql15`, from sandbox perspective I must specify it like `/run/host/usr/lib/postgresql15`, but DBeaver doesn't allow to select directories from `/run/host` as local client path since it uses portals and native OS file chooser that selects files from host OS point of view.

But we can edit configation manually. Close DBeaver, open `~/.local/share/DBeaverData/workspace6/.metadata/.config/drivers.xml`, find the `clientHome` node of your DB driver and set its `id` and `path` to the client directory inside `/run/host`:
![Виділення_234](https://github.com/dbeaver/dbeaver/assets/2466722/ed0372c2-ba3c-451b-bcf2-458e60a8cccb)

Check that local client configuration was understood by DBeaver:
![Виділення_235](https://github.com/dbeaver/dbeaver/assets/2466722/2bf5cae6-338e-4a1e-87ec-68194c24484c)

3. Now if you try to dump/restore a DB, you may encounter erros like `/run/host/usr/lib/postgresql15/bin/pg_dump: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory`. This is because DB client can't find required libraries from host's `/lib`, `/lib64`, `/usr/lib`, `/usr/lib64` directories - they are not in library search path of sandbox OS.

Let's fix it by setting `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/run/host/usr/lib:/run/host/usr/lib64` environment variable in Flatseal:
![Виділення_237](https://github.com/dbeaver/dbeaver/assets/2466722/5f95aaf9-70cf-4295-b11e-b2d05066a337)
For my case `/usr/lib` and `/usr/lib64` were enough.

Restart DBeaver and now it should be able to use host OS native DB clients.

**Comment by aliasbody** [comment]
This issue is quite old (and already closed, opened by me in 2019). But I found a solution:
1 - I've opened a pull request https://github.com/flathub/io.dbeaver.DBeaverCommunity.Client.mariadb/pull/4 for an updated mariadb (I will try to do the same for pgsql) extension for dbeaver, once it's available install it
2 - You need to follow the part from https://github.com/dbeaver/dbeaver/issues/5008#issuecomment-1928038064 where the "drivers.xml" file is edited and set this:  `<clientHome id="/app/clients/bin" path="/app/clients/bin"/>`

This will work and you'll have a working mariadb install (if you want you can set the ID to MariaDB to separate from any other extension in the menu, like this `<clientHome id="MariaDB" path="/app/clients/bin"/>`)

There is a need to find a way to easily add this, maybe by taking with the DBeaver team themselves.

**Comment by aliasbody** [comment]
I've just done a PR for pgsql 16.2, waiting to be approved and merged: https://github.com/flathub/io.dbeaver.DBeaverCommunity.Client.pgsql/pull/8

**Comment by makeyouswag** [comment]
On KDE Neon with Flatpak DBeaver installation, the following worked:

- Install Flatseal with Discover
- Enable DBeaver to access all system libraries [as shown in the comment](https://github.com/dbeaver/dbeaver/issues/5008#issuecomment-1928038064)
- `sudo apt install mysql-client`
- Run `which mysql` to get where the mysql client is. I have `/usr/bin`
- In the dump utility, choose `Local client`, choose `/usr/bin` as the home path

Now DBeaver recognizes that mysqldump is available and proceeds to download the dump.
