### ISSUE TITLE
DBeaver: Table grid NAVIGATE -> REFERENSES is broken in version 5.3.3 EA !!! Please correct !!!

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5009]
DBeaver - **Version 5.3.3 CE** - **EA 14-Jan-2019 21:17**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

I noticed now in **EA 5.3.3 14-Jan-2019 21:17**, that the fantastic function of **Navigate** to **Referenses** is broken when using the **New Microsoft Driver**.

**If I use the old Microsoft driver it works as expected**.

**o** Start _DBeaver_ and connect to a SQL Server.

**o** Run the below SQL commands to set up a test environment:
```
CREATE TABLE TestFather
(
  Id INTEGER NOT NULL,
  Message VARCHAR(64),
  CONSTRAINT PK_TestFather_Id PRIMARY KEY CLUSTERED (Id)
);

CREATE TABLE TestUncle
(
  Id INTEGER NOT NULL,
  Message VARCHAR(64),
  CONSTRAINT PK_TestUncle_Id PRIMARY KEY CLUSTERED (Id)
);

CREATE TABLE TestChild
(
  Id INTEGER NOT NULL,
  FatherId INTEGER,
  UncleId INTEGER,
  Message VARCHAR(64),
  CONSTRAINT PK_TestChild_Id PRIMARY KEY CLUSTERED (Id)
);

ALTER TABLE TestChild
  ADD CONSTRAINT FK_TestChild_TestFather FOREIGN KEY (FatherId) REFERENCES TestFather(Id);
ALTER TABLE TestChild
  ADD CONSTRAINT FK_TestChild_TestUncle FOREIGN KEY (UncleId) REFERENCES TestUncle(Id);

INSERT INTO TestFather
  VALUES (1, 'Father 1'), (2, 'Father 2'), (3, 'Father 3');

 INSERT INTO TestUncle
  VALUES (1, 'Uncle 1'), (2, 'Uncle 2'), (3, 'Uncle 3');
  
INSERT INTO TestChild
  VALUES (1, 1, 1, 'Child 1'), (2, 2, 2, 'Child 2'), (3, 2, 1,  'Child 3'), (4, 3, 3, 'Child 4');
```  
**o** Double click on the **TestChild** table in **Database Navigator** and view its data in a result grid.

**o** Place cursor on row 2 in the result data grid and execute **Navigate Referenses** _(Ctrl+1)_.

**o** Notice that I can navigate to either **TestFather** or **TestUncle**. This is **OK**.

**o** Double click on the **TestFather** or the **TestUncle** table in the **Database Navigator** and view its data in
&nbsp;&nbsp;&nbsp;its result grid.

**o** Place cursor on row 2 in the result data grid and execute **Navigate Referenses** _(Ctrl+1)_.

**o** No referense from table **TestChild** is shown. This is an **ERROR**.
&nbsp;&nbsp;&nbsp;**o** There should be a choice of **TestChild** in **\<Table referenses\>**.

**I would really like to have this fixed for the _DBeaver_ version 5.3.3 if it is possible**!

Screen shots from old and new Microsoft Driver:

![2019-01-15 15-53-06](https://user-images.githubusercontent.com/31191374/51188413-30ad9780-18de-11e9-9701-633c61a941b9.png)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by pdanie** [comment]
I have now tested this in EA 15-Jan-2019 20:12 and it seems **NOT TO WORK**. Guess you have to give this a bit more work.

**Comment by serge-rider** [comment]
Yep, broken query (doesn't work on another server).
New EA has been published.

**Comment by pdanie** [comment]
I have now tested this in **EA 15-Jan-2019 20:50** and it seems to work **OK**. Now you talking! Great work!

Now its time for me to "hit the sack" (in Sweden it's now 10:15pm). So I leave you to digging down in other tricky issues. Until next time. \*big smile\*

**Comment by pdanie** [comment]
Sorry to say, but there was one more misbehaviour in this. See the #5014 in that the table names shown are not sorted when using the **New Microsoft Driver**.  

I hope you can fix this so that I have a new EA build tomorrow (my time).
