### ISSUE TITLE
Silent Install for DBeaver Community Edition 5.3.2

### ISSUE THREAD

**Issue by rnmavery** [dbeaver/dbeaver#5010]
#### System information: 
- Operating system (distribution) and version
 Windows 7 and 10

- DBeaver version 
DBeaver Community Edition 5.3.2

- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Want a silent install for DBeaver Community Edition 5.3.2. Have tried running dbeaver-ce-5.3.2-x86_64-setup.exe with /S switch to no avail as documented. Need to make this available to users via SCCM. I know the /D switch does not work by reading other forum responses but just want it too install in default directory.

**Comment by rnmavery** [comment]
Want a silent install for DBeaver Community Edition  5.3.2. Have tried running dbeaver-ce-5.3.2-x86_64-setup.exe with /S switch to no avail as documented. Need to make this available to users via SCCM. I know the /D switch does not work by reading other forum responses but just want it too install in default directory. 

Operating System - Windows 7\10
DBeaver Version - 5.3.2 Community Edition
Java Version - 1.8.0_162

**Comment by rnmavery** [comment]
Can this be installed silently?

**Comment by rnmavery** [comment]
Can this be installed silently

**Comment by serge-rider** [comment]
Silent install was broken at some moment..

**Comment by serge-rider** [comment]
New version of NsisMultiUser plugin has been released (https://github.com/Drizin/NsisMultiUser), it fixed problems with silent install (/S) and with target directory (/D) parameters.

Silent install instructions: https://github.com/dbeaver/dbeaver/wiki/Windows-Silent-Install

You can test it in Early Access version (https://dbeaver.io/files/ea) or in 5.3.3 after release.
