### ISSUE TITLE
DBeaver: Login using the Old Microsoft Driver does not work if Windows Authentication is set

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5011]
DBeaver - **Version 5.3.3 CE** - **EA 15-Jan-2019 14:31**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the old Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

Seems something has become broken for use of **Windows Authentication** when logging in using the **Old Microsoft Driver**.

My guess is that something was broken with the #4990 issue. If I change the connection setting to **Windows Authentication** the driver property **integratedSecurity** is not set to **true**.

Connection dialogs for a connection using the old Microsoft Driver:

![2019-01-15 19-03-47](https://user-images.githubusercontent.com/31191374/51200290-63b15480-18f9-11e9-8054-d352444db6d0.png)

![2019-01-15 19-04-05](https://user-images.githubusercontent.com/31191374/51200336-80e62300-18f9-11e9-9f49-63389f75048b.png)

**Comment by serge-rider** [comment]
Thanks for testing this.

**Comment by pdanie** [comment]
I am just "jumping" arond the _DBeaver_ program. Unfortunately often I find misbehaviour. Have been extra stuff that is not working when it comes to the new Microsoft Driver. But I guess that is just how it is when you intoduce new stuff. 

If you generate a new EA build and I will try it out :)

**Comment by serge-rider** [comment]
Of course it is. We are in the middle of spring, most of new features are not well-tested.

New EA is ready
