### ISSUE TITLE
Crashes when trying to supply a driver

### ISSUE THREAD

**Issue by palladium313** [dbeaver/dbeaver#5019]
#### System information: 
- Operating system (distribution) and version: Linux Mint 19.1 Cinnamon
- DBeaver version: 5.3.1 (current version in the Software Manager)
- Java version: openjdk version "10.0.2" (I have the default-jre and default-jdk installed via apt-get)
- Additional extensions

#### Connection specification:
- Database name and version Oracle 12c
- Driver name ojdbc7.jar (I can not get to the screen where I can even select any jars at all)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

I am trying to set up my first connection after downloading Dbeaver, which is an Oracle connection. When I click on either Add Jar, Add File, or Add Folder Dbeaver immediately exits.

#### Steps to reproduce, if exist:
In the New Connection Wizard which appears when running for the first time, select Oracle, and then attempt to add the driver JAR files.

#### Include any warning/errors/backtraces from the logs
The debug log had nothing interesting, just loading a bunch of org.eclipse.... files.
Log File:
!SESSION 2019-01-16 13:23:43.755 -----------------------------------------------
eclipse.buildId=unknown
java.version=9.0.4
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.jkiss.dbeaver.model 2 0 2019-01-16 13:23:48.209
!MESSAGE Project 'General' not found in registry
!SESSION 2019-01-16 13:29:34.426 -----------------------------------------------
eclipse.buildId=unknown
java.version=9.0.4
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.core.resources 2 10035 2019-01-16 13:29:36.290
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

--- There are repeats of the messages above for each attempt that I made.

**Comment by serge-rider** [comment]
We have a bunch of renderign issues on Mint, I guess it is one of them.
What you could try:
- Add `export GTK_IM_MODULE=ibus` in ~/.profile
- Add 
```
--launcher.GTK_version
2
```
in the beginning of dbeaver.ini

**Comment by palladium313** [comment]
I uninstalled the version in the package manager and installed the one on the website since it was one version newer and I was able to add the drivers with no issue. It looks like one of the changes from 5.3.1 to 5.3.2 fixed this issue.

I had already done this before the reply, otherwise I would have done that first.

I mostly prefer using the package manager since its easier to stay up to date. Does this software have a utility to update itself inside the program or do I have to download it again from the site when the next version comes out? If that's the case once 5.3.2 is in the repo for me I'll export my stuff and set it up on the one in the repo.

**Comment by serge-rider** [comment]
What repo do you use?
We update deb package (https://dbeaver.io/debs/dbeaver-ce/) and PPA immediately. Some other packages are maintained by other people (thanks to them) but we can't guarantee that these packages are always up to date.

**Comment by palladium313** [comment]
I have a fresh install of Mint 19.1 Cinnamon, I am using the default one that the Software Manager application in the GUI uses. I won't be able to take a closer look until Tuesday.

**Comment by uslss** [comment]
there is no updates on issue for almost a year. Ticket is closed.
If issue is still actual for you feel free to open new issue or reopen this one,
