### ISSUE TITLE
DBeaver: DB Full Text Search for UUID values does not work with New Microsoft Driver

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5021]
DBeaver - **Version 5.3.3 CE** - **EA 16-Jan-2019 07:28**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

Something is broken when it comes to search a whole database/number of tables using **DB Full Text Search** when searcing for UUID values.

**It works if I use the Old Microsoft Driver**.

**o** Start _DBeaver_ and connect to a **SQL Server** database.

**o** Open a **SQL Editor** to a database of your choice.

**o** Execute the SQL script below:
```
CREATE TABLE TestSearch(Id UNIQUEIDENTIFIER, Message VARCHAR(64));
GO

INSERT INTO TestSearch
VALUES ('5C64BCE4-974F-4DAD-988C-A1D499CE5D6B', 'Row 1'),
       ('5E182E5B-1943-489B-8717-8AC3CC71F9A5', 'Row 2'),
       ('5B656E3D-F9FC-4C53-83AA-5394B6474EB4', 'Row 3'),
       ('5E182E5B-1943-489B-8717-8AC3CC71F9A5', 'Row 4');
GO

SELECT * FROM TestSearch
 WHERE Id = '5E182E5B-1943-489B-8717-8AC3CC71F9A5';
```
**o** A result data grid with two lines is reported. This is **OK**.

**o** Now active command **DB Full Text Search** by choosing **Search** -> **DB Full-Text** in the menu.

**o** Enter the value **5E182E5B-1943-489B-8717-8AC3CC71F9A5** into the **String** input field.

**o** Check **Tables** in the **Databases** tree in the database you choosed above (in the **dbo** schema).

**o** If run using the **Old Microsoft Driver** the result below is shown. This is **OK**.

&nbsp;&nbsp;&nbsp;![2019-01-16 19-38-15](https://user-images.githubusercontent.com/31191374/51270907-76458f80-19c6-11e9-895a-4e6d12b0d67f.png)

**o** If rn using the **New Microsoft Driver** the result below is shown: This is an **ERROR**.

&nbsp;&nbsp;&nbsp;![2019-01-16 19-42-14](https://user-images.githubusercontent.com/31191374/51271199-2ddaa180-19c7-11e9-9ebb-c45d67eafada.png)

**Comment by pdanie** [comment]
Hope there is a possibility to cram this too into the _DBeaver_ **5.3.3** version.

**Comment by serge-rider** [comment]
Yep, This is because UNIQUEIDENTIFIER data type.
Thanks for the bug report.

**Comment by serge-rider** [comment]
Yep, it is there.

Good morning :)

**Comment by pdanie** [comment]
I have tried this feature in **EA 17-Jan-2019 09:35* and **IT WORKES** !! Great Work as usual.

And of course a Good Morning to you too (but now its almost 1PM here). You must have been up really early today.

**Comment by serge-rider** [comment]
👍 

#4955 and #4957 are potentially dangerous as they may cause side effects in other driver. So we'll cover them in the next release.

But I'm going to finish  #5004 and #5005 in 5.3.3.
