### ISSUE TITLE
DBeaver 5.3.x not refreshed

### ISSUE THREAD

**Issue by sgmheyhey** [dbeaver/dbeaver#5022]
Database table screen doesn't be refreshed with the refresh button and so on.

I've been tested with MariaDB or MySQL drivers on Ubuntu 18.04 and Windows 10.

DBeaver version 5.3.201901062110 (2019.01.07)

**Comment by goxr3plus** [comment]
Being in version 5.3.2 works as expected for me .

**Comment by serge-rider** [comment]
Please post more details. 
- Why do you think it is not refreshed?
- What exactly do you refresh (navigator tree, some editor's contents)?
- Do you use shortcut or context menu or toolbar icon?

**Comment by sgmheyhey** [comment]
DBeaver version 6, now it works again. So I close this issue.
