### ISSUE TITLE
No databases shown on Amazon ElastiCache, Redis

### ISSUE THREAD

**Issue by WouterRademaker** [dbeaver/dbeaver#5023]
System information: 
- local machine: Ubuntu 18.04
- AWS: Centos 7
- DBeaver EE 5.3.0.201812101127
- openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

Connection specification:
- Redis [5.0.0 (standalone) Amazon ElastiCache]
- Jedis [2.9.0]
- SSH tunnel via bastion, using public key.

Describe the problem you're observing:
- DBeaver connects via SSH tunnel to Redis-server on AWS with no errors. Information from the Redis-server is shown, but no databases are shown. 
- Databases are shown in in "redis-cli" and "Redis Desktop Manager"

**Comment by serge-rider** [comment]
I believe this issue is already fixed. You can check it in Early Access version (https://dbeaver.com/files/ea).
BTW New intermediate stable EE version release is  planned on the next week.

**Comment by WouterRademaker** [comment]
As far as I can see it is indeed fixed in DBeaver EE 5.3.3.

**Comment by davizucon** [comment]
Hello,
I have very similar problem, so, re-opening this issue.
I'm using DBeaver Version 7.3.0.

Connection specification:
- ElasticCache, cluster with SSL
- Redis [4.0.10]

The problem:
- Connection looks fine. When testing connection, Server information show "Redis null". In Connection->Databases->cluster-> "Key list" are empty
- Tried without cluster and SSL ->skip host name validation , no luck.

Additional information:
- RDM works fine.
