### ISSUE TITLE
[Usability] Double-click on database to set active (PostgreSQL, maybe others?)

### ISSUE THREAD

**Issue by DKhalil** [dbeaver/dbeaver#5028]
So apparently the feature to switch the currently active database with a doubleclick on the database's name has been removed. Is it possible to add it back again? Why has it been removed anyway? This is incredibly useful when working with multiple databases and having scripts open that need to be executed on specific databases only.

**Comment by tati-kru** [comment]
Let's move this discussion to https://github.com/dbeaver/dbeaver/issues/5027
