### ISSUE TITLE
DBeaver: Add TAB key to make same as ENTER to accept the selected database element for SQL Completion

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5029]
DBeaver - **Version 5.3.3 CE** - **EA 17-Jan-2019 14:17**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

It would be benificial if I could use the **TAB** key to accept a database element suggested by using the **SQL Assistant/Completion** (automatic/manual).

**o** Start _DBeaver_ and connect to a database of your choice.

**o** Open up a **SQL Editor**.

**o** Write the SQL command below and let either the automatic **SQL Completion** kick in or use
&nbsp;&nbsp;&nbsp;&nbsp;the manual **SQL Assist** _(Ctrl+Space)_:
```
SELECT * FROM Cust
```
**o** In the list with table names that pops up, select one.

**o** Currently in _DBeaver_ the key to accept the selected table name is the **ENTER** key.

I would like to be able to use the **TAB** key too. This workes better with my typing by some reason (not only because I use it in another SQL IDE tool). If _DBeaver_ supported both keys that would be really great.

**PS**. An alternativ might be to create a command for accepting the choice in the **SQL Assist** dialog, and
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;then let me in the **global** properties **General** -> **Keys** change the keyboard shortcut for it (from
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ENTER to TAB).

**Comment by p91paul** [comment]
#2316

**Comment by pdanie** [comment]
**p91paul** Thanks for the issue link. I had a feeling of I had seen an issue about this, but when I looked I did not find it.

Mabye we are lucky that this feature can be included in a near future.

**Comment by p91paul** [comment]
I noticed because I'm watching this repository (I find amusing to closely follow development) and just today someone read your mind and revived that thread :)

**Comment by serge-rider** [comment]
Yep. Mark as duplicate
