### ISSUE TITLE
DBeaver: Change the automatic left column width in the Panels grids for Value and Calc

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5030]
DBeaver - **Version 5.3.3 CE** - **EA 17-Jan-2019 14:17**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

It would be easier to overview the result in the **Panels Grids** for **Value** and **Calc** if:

**o** The left column only took as much width as it needed.
**o** The right column left adjusted all values.

Currently I get really hard to overview th Panels grids when I am using a wide computer sceen.

**Current presentation**

![2019-01-17 18-19-47](https://user-images.githubusercontent.com/31191374/51336532-0ba75900-1a85-11e9-81a0-38f609615da5.png)

**Suggested presentation**

![2019-01-17 18-19-99](https://user-images.githubusercontent.com/31191374/51337610-d94b2b00-1a87-11e9-8bbe-3f16581ac571.png)

**Comment by serge-rider** [comment]
Good point

**Comment by kseniiaguzeeva** [comment]
Verified
