### ISSUE TITLE
Fetch all rows removes first block

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#5031]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version:
![immagine](https://user-images.githubusercontent.com/2157006/51338268-aace4f80-1a89-11e9-841a-1db25b2ee937.png)

- Java version: the one bundled with dbeaver

#### Connection specification:
- Database name and version: Oracle 11
- Driver name: oracle 12
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Using fetch all rows discards the first page and shows all rows starting from the second page. E.g. if my resultset is 672 rows and page size is 200, "Fetch all rows" will show 472 rows, from 201 to 672 (numbered 1 to 472)

#### Steps to reproduce, if exist:
Issue a query then use "Fetch all rows" button at the bottom of the resultset.

Workaround: scroll, loading one page after another, until the end of the resultset.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by serge-rider** [comment]
Luckily this bug was only in EA version.
