### ISSUE TITLE
DBeaver: Add comma as a separator in the Dictionary Define Columns in the Values grid

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5032]
DBeaver - **Version 5.3.3 CE** - **EA 17-Jan-2019 14:17**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

It would be easier to read the **Dictionary Define Columns** in the **Values** grid (the **Description column**) if each value was separated by **a comma** (ie ",") ** as a separator. This just as it is shown in the **Custom Criteria** field.

**Maybe even separate with both a comma and a space** (for extra separation).

**Current Edit Dictionary dialog**

![2019-01-17 18-52-52](https://user-images.githubusercontent.com/31191374/51338201-85414600-1a89-11e9-8af4-f345dfe95f20.png)

**Current Panels - Values grid**

![2019-01-17 18-57-11](https://user-images.githubusercontent.com/31191374/51338398-fa148000-1a89-11e9-9d10-0b600e5e7310.png)

**Comment by serge-rider** [comment]
Fixed.
Now you can configure column divider in dictionary edit page:
![image](https://user-images.githubusercontent.com/6398845/84885775-2d52a880-b09c-11ea-8af1-c0442043f510.png)

**Comment by kseniiaguzeeva** [comment]
checked
