### ISSUE TITLE
Auto-downloaded mysqldump client results in SQL syntax error

### ISSUE THREAD

**Issue by maphew** [dbeaver/dbeaver#5033]
_The mysql binaries automatically downloaded by DBeaver do not successfully dump from our MariaDB database, while 2 other clients available to me do work._

#### System information: 
- Win10 Enterprise x64
- DBeaver 5.3.2.201901062110
- Java version 8 update 191

#### Connection specification:
- MariaDB: 
```
[root@dbserver ~]# mysqldump --version
mysqldump  Ver 10.14 Distrib 5.5.52-MariaDB, for Linux (x86_64)
```
- Driver name: org.mariadb.jdbc:mariadb-java-client:RELEASE, v1.5.5.
- using SSH tunnel
- Local client: auto downloaded by dbeaver:

```
%HOME%\.dbeaver-drivers\clients\mysql\win\mysqldump --version
mysqldump  Ver 10.16 Distrib 10.3.9-MariaDB, for Win64 (AMD64)
```

#### Describe the problem you're observing:
Dumping the database finishes with error `Couldn't execute 'SHOW PACKAGE STATUS WHERE Db = 'mydb'`.

```
Export started at Thu Jan 17 09:39:53 PST 2019
-- Connecting to 127.0.0.1...
-- Retrieving table structure for table bak_weblog_data...
-- Sending SELECT query...
-- Retrieving rows...
...snip...
-- Retrieving table structure for table exp_upload_prefs...
-- Sending SELECT query...
-- Retrieving rows...
mysqldump.exe: Couldn't execute 'SHOW PACKAGE STATUS WHERE Db = 'mydb'': You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'PACKAGE STATUS WHERE Db = 'mydb'' at line 1 (1064)
Export finished at Thu Jan 17 09:39:56 PST 2019
Process exit code: 2
```

#### Steps to reproduce, if exist:

Open connection and navigate to db >> select db >> context menu >> tools >> dump >> keep defaults >> [Start]

#### Include any warning/errors/backtraces from the logs
_(Assumed enough info present and logs not needed. Let me know if you want them.)_

#### Troubleshooting

- Copy command line from dbeaver log report and execute same on {dbserver} in SSH shell session: finishes without error.

- Tell dbeaver to use a different client* on local machine and rerun the dump: finishes without error

\*this client works:
```
"C:\Program Files\MySQL\MySQL Workbench 6.3 CE\mysqldump.exe" --version
mysqldump  Ver 10.13 Distrib 5.7.17, for Win64 (x86_64)
```

**Comment by serge-rider** [comment]
We need to upgrade MySQL dump version.

As a workaround you can configure local client to use mysqldump from MySQL Workbench.

**Comment by uslss** [comment]
verified
