### ISSUE TITLE
Go To Database Object slower than search in Navigation pane

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#5035]
While the Goto Database Object (Ctrl+D) is usually fast, it often stays for several seconds locked with the "Cache Refresh (50%)" message. By several I mean up to tens of seconds.

By contrast, searching for an object in the navigation pane is always blazing fast, so much that I sometimes just get out of Ctrl+D and search in the navigation pane directly (not without yelling a profanity).

Can't both be based on the same pool of objects to search into?Why is ctrl+d slower?

**Comment by serge-rider** [comment]
GoTo object searches in remote database catalog always.
You can open Query Manager (note: enable all query types in config) and check what exactly queries are executed and why they take so much time.

Perhaps we can add some config to make it faster. OR maybe this happens with specific databases only.

**Comment by p91paul** [comment]
This is the query:

```sql
SELECT  DISTINCT OWNER,OBJECT_NAME,OBJECT_TYPE FROM (SELECT OWNER,OBJECT_NAME,OBJECT_TYPE FROM ALL_OBJECTS WHERE OBJECT_TYPE IN ('TABLE','VIEW','MATERIALIZED VIEW','PACKAGE','CONSTRAINT','FOREIGN KEY','INDEX','PROCEDURE','FUNCTION','SEQUENCE','TRIGGER','SYNONYM') AND OBJECT_NAME LIKE 'search_string%' UNION ALL
SELECT  O.OWNER,O.OBJECT_NAME,O.OBJECT_TYPE
FROM ALL_SYNONYMS S,ALL_OBJECTS O
WHERE O.OWNER=S.TABLE_OWNER AND O.OBJECT_NAME=S.TABLE_NAME AND S.OWNER='PUBLIC' AND S.SYNONYM_NAME LIKE 'search_string%')
ORDER BY OBJECT_NAME;
```
However I'm not able to optimize it further, it's just that ALL* views are damn slow. Removing synonyms I got 7 to 9 seconds instead of 40, so I hope to get better with #5036 (if removing synonyms is one of the options). 9 seconds is still freaking slow for a catalog query, but that's on Oracle, DBeaver can't perform miracles...

It could be good to add an option to *not* search in remote database always, but instead preload the entire list of objects once and then search on that. Just like the navigation pane works (cache should be shared between navigation pane and goto dialog to avoid double work).
