### ISSUE TITLE
Select object types to search for in Goto Database Object

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#5036]
Currently the goto database object allows you to search for any kind of object. I'd like to be able to select which kinds: the ideal way would be a collapsible panel (default collapsed) at the bottom of the search dialog with checkboxes for all types of supported objects, allowing the user to uncheck not interesting types.

Also, selection should be remembered from the last invocation.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/52017832-9cf0e380-24f9-11e9-8d99-cdb343550f00.png)

**Comment by p91paul** [comment]
wonderful, I need to download EA tomorrow :)

**Comment by p91paul** [comment]
I tried EA on Oracle database:
![immagine](https://user-images.githubusercontent.com/2157006/52112273-49b88700-2606-11e9-8f76-4d3e5ab17536.png)

I believe there are some object types missing: for example VIEW/MATERIALIZED VIEW is bunded with TABLE, and SYNONYM cannot be disabled (this last one I relied on to improve on #5053)

**Comment by p91paul** [comment]
Awesome as usual, thanks :)
