### ISSUE TITLE
LINUX - Cconfiguration file path

### ISSUE THREAD

**Issue by abacao** [dbeaver/dbeaver#5037]
Please consider looking the configuration file not only in ~ but also in ~/.config/dbeaver/... (or even change it to this path)

specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

unix.stackexchange.com/questions/312988/understanding-home-configuration-file-locations-config-and-local-sha

**Comment by serge-rider** [comment]
What do you mean under "configuration file"? 

If .dbeaver4 folder content then it is not a configuration but workspace (it contains all configs, scripts, data files, etc).

**Comment by abacao** [comment]
I was referring to this 2:

- .dbeaver4/        
- .dbeaver-drivers/

Basically, a way to help organize a home dir without clutter
