### ISSUE TITLE
unable to see columns in ms access db

### ISSUE THREAD

**Issue by paweljasinski** [dbeaver/dbeaver#5040]
#### System information: 
- Operating system: windows 10
- DBeaver version 5.3.2
- Java version: embedded
- Additional extensions: none

#### Connection specification:
- Database name and version: ms access file (mdb) 
- Driver name: jdbc:ucanaccess 4.0.4, 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Properties Tab doesn't show any columns

column definitions can be seen via Data, Panels, Metadata
I also tried oracle db and things are ok.

#### Steps to reproduce, if exist:
Open attached model, drill down tables->any table, select properties tab

#### Include any warning/errors/backtraces from the logs
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/2773030/dbeaver-debug.log)
[log.log](https://github.com/dbeaver/dbeaver/files/2773037/log.log)

#### test model
[model1.zip](https://github.com/dbeaver/dbeaver/files/2773057/model1.zip)

I suspect ticket #4770 is related.

**Comment by serge-rider** [comment]
I'm pretty sure that this issue was fixed in #4956.
Please test it in 5.3.3 version.

**Comment by serge-rider** [comment]
Then I can't reproduce this:
![image](https://user-images.githubusercontent.com/6398845/51864554-26b37c00-2355-11e9-9cae-620d17dabba8.png)

My UCanAccess version is 4.0.4
Do you use preconfigured DBeaver driver or some manually created one.

**Comment by paweljasinski** [comment]
the ucanconnect driver is the one which installed itself automatically
However, I have no idea if jet driver (v 4.0) which I have installed manually can be a problem here. There is also a msaccess 16 with its own driver. Both 32 bit. Are these drivers used at all?

![ucanaccess](https://user-images.githubusercontent.com/1618400/51971483-886d0680-2479-11e9-9fbc-36496fee45de.png)
![odbc png](https://user-images.githubusercontent.com/1618400/51971491-8e62e780-2479-11e9-8e5a-6f14ef274a99.jpg)

Do you have any suggestions what can I try to identify what is causing the problem here?

**Comment by serge-rider** [comment]
- Make sure you are using DBeaver 5.3.3 or later (DBeaver version is in the window title and in main menu->Help->About).
- make sure masks are disabled for UCanAccess driver: 
![image](https://user-images.githubusercontent.com/6398845/51973319-63cf5980-248e-11e9-9248-d2437cbf4a9a.png)

**Comment by paweljasinski** [comment]
Turning off "Escape LIKE masks in search queries" fixed it for me. Thanks a lot!
