### ISSUE TITLE
DBeaver: Error message if I try to Kill a Session using the new SQL Server Sessions Dialog

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5041]
DBeaver - **Version 5.3.3 CE** - **EA 18-Jan-2019 05:58**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

In the new **SQL Server Sessions dialog** from the #5004 issue function to **Kill a Session** is not working.

**o** Start _DBeaver_ and connect to a _MS SQL Database_ using the **New Microsoft Driver**.

**o** Expand the tree in the **Database Navigator** and open the **Administration** -> **Sessions** tab.

**o** Select one PID in the list of connections and klick on the lower right button for **Kill session**.

**o** An error message are shown:
>   SQL Error [102] [S0001]: Incorrect syntax near ')'.
>   SQL Error [102] [S0001]: Incorrect syntax near ')'.
>     Incorrect syntax near ')'.
>     Incorrect syntax near ')'.

**o** At some times the PID is killed, other times nothing is killed only the error message is shown.

**Comment by serge-rider** [comment]
Thanks for the bug report. Kill query was broken

**Comment by pdanie** [comment]
As always. If you generate an EA build, I can do my best to test it.
