### ISSUE TITLE
DBeaver: Disconnect a connection in Database Navigator do not update the main Toolbar buttons

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5042]
DBeaver - **Version 5.3.3 CE** - **EA 18-Jan-2019 15:46**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

If I disconnect a connection by right click in the **Database Navigator** the icons/buttons state in _DBeaver_ main **Toolbar** (right under the main menu) are not updated.

To make the **Toolbar** buttons update its state I have to change connection to another in the **Database Navigator** and then change it back again.

**PS**. If I instead connect a connection using the **Database Navigator** the **Toolbar** buttons updates ok.

**Comment by serge-rider** [comment]
It is not so easy to reproduce this but it happens sometimes.
