### ISSUE TITLE
The results tabs without data due to errors are not recycled

### ISSUE THREAD

**Issue by GaryLiuTelus** [dbeaver/dbeaver#5044]
Hi 
I really love DBeaver! And I have introduced to my coworker, and they all like it! Thanks a lot for such a amazing tool. I will have a presentation in our internal user forum to introduce this to more colleagues. Very exciting!
 
What I posted here is not a bug, rather, it is a suggestion. Hope it can be fulfilled  in future release. Please see details below. 

Thanks!

#### System information: 
- Operating system (distribution) and version
 Windows 10 Enterprise 1709 16299.785
- DBeaver version
5.3.0
- Java version 
Java 8 update 121
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I always use 'Execute query in new tab' as I can reserve all previous results. But if the query failed, a new tab with 'No Data' still open, and next time you run a new query, this tab will not be re-used and I have to manually close it. It is quite annoying. In Squirrel SQL, it shows error message and next time you run another query, it will re-use this tab. 

Is that possible to do the same way? Thanks!

**Comment by serge-rider** [comment]
This is actually a bug.

**Comment by serge-rider** [comment]
In 6.0.2 we changed default way to show resultset errors (now they are shown inside results panel). So no "empty" results panel makes sense and we can't remove it.

**Comment by GaryLiuTelus** [comment]
Thank makes sense. Thanks Serge!
