### ISSUE TITLE
DBeaver: Add possibility to Disable save of local Local Workspace History

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5045]
DBeaver - **Version 5.3.3 CE** - **EA 18-Jan-2019 15:46**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

If I work with SQL scripts and don't want that nothing is saved in the **Local Workspace History** it would be benificial if I could disable it.

I have tried to set the **global** property **General** -> **Workspace** -> **Local History** -> **Days to keep files** to **0** (zero) to disable all saving of history. But that it did not work since that value has to be a positive number.

Are there something I am missing? Or is it something that can be added to _DBeaver_ ?

**Comment by serge-rider** [comment]
This feature comes from Eclipse platform, unfortunately we can't fix this so easily. Settings all values to 1 will minimize history as much as possible. I don't know how to disable it completely.

Out of curiosity - why do you want to disable local history? Does it make any harm?
