### ISSUE TITLE
DBeaver: The Execute - Select Row Count generate error if the SQL Statement contain an ORDER BY (on MS SQL Server)

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5046]
DBeaver - **Version 5.3.3 CE** - **EA 18-Jan-2019 15:46**
DBeaver driver: **MS SQL Server  / Microsoft Driver**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

If I have a SQL statement that contain an **ORDER BY** an error is shown when I try to execute a **Select Row Count** _(Ctrl+Alt+Shift+C)_.

My guess for a solution is that _DBeaver_ removes the **ORDER BY** part of the SQL statement when it wants to calculate the total number or result rows.

This SQL work if I right click on it and choose **Execute** -> **Select row count** _(Ctrl+Alt+Shift+C)_:
```
SELECT *
  FROM sys.messages;
```

This SQL generate an error if I choose **Execute** -> **Select row count**:
```
SELECT *
  FROM sys.messages
 ORDER BY message_id;
```
The above SQL genereate the error message:
>
> SQL Error [1033] [S0001]: The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.
>
> The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.
  The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.
>

I would guess that the above is due to that the _MS SQL Server_ does not like to execute a SQL statement like the one below (generate the same error message as above):
```
SELECT COUNT(*)
  FROM (SELECT *
          FROM sys.messages
         ORDER BY message_id) T;
```

**PS**. The same behaviour can be observed if I click on the **Calculate total row count** button (the two
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;green arrows) just above the _DBeaver_ **Status Bar**.

**Comment by serge-rider** [comment]
Unfortunately it is not that easy. Query may contain a set of unions with multiple ORDER BYs, it may contain sub queries with ORDER BYs, etc. Moreover we have to support different SQL dialects.
So, at the moment I don't see any simple solution for that..

**Comment by pdanie** [comment]
I thought that most functions in _DBeaver_ hade a base/common functionality, but where necessary there whrere special implementation for different databases.

Oh well. I just hoped it was a easiert "nut to crack".
