### ISSUE TITLE
Source table cannot be changed during the import

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#5047]
#### System information: 
- win 10 x64
- DBeaver version 5.3.3

#### Describe the problem you're observing:
If I changed source during the import, mapping settings aren't changed and import cannot be finished
#### Steps to reproduce, if exist:
1. Import any table
2. Choose any source table
3. Go to Mapping Settings and verify that all properties are shown for the current tables. Button Next is available.
4. Go back and change the source table.
5. Go to the Map Settings. All properties are available for the previously chosen source table. Next button is not available.

![2019-01-19_00h44_38](https://user-images.githubusercontent.com/31996417/51415021-66c07500-1b85-11e9-9833-3e133cf0af37.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
