### ISSUE TITLE
Disable 'extract sql from source code' for Dbeaver 5.2.3 mac

### ISSUE THREAD

**Issue by tikael1011** [dbeaver/dbeaver#5048]
<!-
#### Describe the problem you're observing:

Related to https://github.com/dbeaver/dbeaver/issues/558. In 5.2.3 I can no longer find that option. and IMHO this so called feature IS REALLY BAD. Get the job done/delivery what customers need is way more important than being smart.

**Comment by serge-rider** [comment]
This option is still there, we just rearranged preference pages as now we have too many of them:

![image](https://user-images.githubusercontent.com/6398845/51424072-e5470200-1bd9-11e9-89b9-ba4e26b9ab3a.png)

**Comment by tikael1011** [comment]
awesome, thanks for help.
