### ISSUE TITLE
Where to put license for automated installation of DBeaver EE?

### ISSUE THREAD

**Issue by thaniri** [dbeaver/dbeaver#5049]
Greetings,

I am installing DBeaver Enterprise Edition on several Windows and Linux remote desktop servers.

I don't want to launch DBeaver on every server and paste in the license.

Is there a location where I can put a license text file so that DBeaver reads it upon launch? Or alternatively, does dbeaver provide an MSI with an argument to take in a license file? (I couldn't find an MSI made by DBeaver, and making an MSI myself without knowing how to get DBeaver to read a license file wouldn't help much)

Thanks

**Comment by serge-rider** [comment]
There are a few ways to do this by patching product configuration.
At the moment we have only exe installer which can be run in silent mode (flag /S). Or zip archives.
In version 5.2 there is only one way to pass custom license path - pass command line parameters 
`-license <full-license-file-path>`
Also these parameters can be added in the beginning of dbeaver.ini file. 

In fact we've been asked about this very feature a few time recently. So, EE version 5.3.3 will support license reading from following locations:
- File `.dbeaver-ee-license.dat` in user home directory (`%HOMEPATH%\.dbeaver-ee-license.dat`).
- File `.dbeaver-ee-license.dat` in the current workspace .metadata folder. By default workspace location is in user home `.dbeaver4` subfolder. So it will be `%HOMEPATH%\.dbeaver4\.metadata\.dbeaver-ee-license.dat`

Note: file `.dbeaver-ee-license.dat` must contain only the license text. Comments (lines starting with --) may be removed if needed.
Note: examples above are for Windows installation but it will work as well for Linuxes or MacOS.

You can test DBeaver EE Early Access (https://dbeaver.com/files/ea) or wait till the next week when 5.3.3 release will happen.

**Comment by thaniri** [comment]
I will wait for version 5.3.3. Thanks, serge-rider.
