### ISSUE TITLE
DBeaver: The automatic layout manager for last Export Data dialog is broken

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5051]
DBeaver - **Version 5.3.3 CE** - **EA 19-Jan-2019 14:00**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new and old Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

Seems something is broken in the last dialog when **Export Data** (in SQL INSERT format).

My guess is that there are some sort of automatic size calculation for the **Objects** grid and the two lower memo fields **Source settings** and **Target settings** that is broken.

**Note**: The last dialog worked ok before the extra two memo fields was added (I tried version 5.1.4).

**Last Dialog** in **Export Data** series:

![2019-01-19 20-16-42](https://user-images.githubusercontent.com/31191374/51431398-5f05dc80-1c28-11e9-880a-3e669ccf5fc7.png)

**Last dialog** in **Export Data** series when I have just dragged the top part of the dialog 2mm up:

![2019-01-19 20-16-58](https://user-images.githubusercontent.com/31191374/51431404-8fe61180-1c28-11e9-9a9b-bddeb1442c2e.png)

**Comment by serge-rider** [comment]
Thanks for the bug report
