### ISSUE TITLE
Formatting the Plain Text View

### ISSUE THREAD

**Issue by S-Man42** [dbeaver/dbeaver#5054]
Hi,

I really often use the plain text view. But I don't like its formatting:
```
birthday  |total_count|
----------|-----------|
1985-10-25|         16|
1985-10-26|         16|
```
Is there an option to enable a line for the left table side? Having the frame line only on the right side makes it look broken in my personal opinion.

And secondly I would like to have one space between the data and the column delimiters:
```
|   birthday | total_count |
|------------|-------------|
| 1985-10-25 |          16 |
| 1985-10-26 |          16 |
```
Maybe it could be a formatting option if it does not exist yet.

**Comment by serge-rider** [comment]
There are formatting options for that:
![image](https://user-images.githubusercontent.com/6398845/51437565-0d556480-1cb1-11e9-8604-8506b49d7b38.png)

**Comment by S-Man42** [comment]
Oh great, didn't see that. Do you think it would be possible to add an option for "space to delimiter"? So that the data is not that close to the column lines (as in my example above). E.g. SQL Fiddle formats this way. In my personal opinion it looks much more readable.

**Comment by serge-rider** [comment]
Yep. That's easy

**Comment by pdanie** [comment]
I have tried this new text formating in **EA 31-Jan-2019** but there is **no extra leading space** added.

**Comment by S-Man42** [comment]
I've tried but the extra space has been added only at the end of the column not in both beginning and end:
```
|id     |released   |
|-------|-----------|
|     1 |2001-11-04 |
|     2 |2002-11-03 |
|     3 |2004-05-23 |
```
instead of 
```
| id     | released   |
|-------|------------|
|     1 | 2001-11-04 |
|     2 | 2002-11-03 |
|     3 | 2004-05-23 |
```
