### ISSUE TITLE
How to close a project without deleting it?

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#5055]
#### System information: 
Operating system (distribution) and version: mac mojave 10.14.2
DBeaver version: 5.3.1
Java version: java version "1.8.0_192"
Additional extensions

#### Connection specification:
Database name and version: postgres 10.4 (on rds)
Driver name: postgres jdbc driver (downloaded by dbeaver)
Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
I am working with multiple projects - but I do not wish to see them all at once so I need an option to close a project and the reopen it later on.
I would expect to have an option to Close a project (at least if it's not the active one) if right clicking it or through the top menu - but I can't seem to find one. I do not wish to delete the project...
![image](https://user-images.githubusercontent.com/18515297/51438489-9f5f6c00-1cb5-11e9-9faa-6887844e4948.png)

Edit: I know the Delete option does a "logical" deletion according to the doc - but I think "Delete" and "Close" are 2 separate things. Delete should delete everything - including settings, connections etc. While Close should only unload it from the UI.

**Comment by serge-rider** [comment]
There is no such feature at the moment.
There is "close project" option in Eclipse so it is accessible if you are working from Eclipse using DBeaver plugin.
Also you can switch to the Database Navigator view which shows content only for one (active) project.

Could you say what is main different between closed project and collapsed project tree element?

**Comment by pyrocks** [comment]
Hi,

I do not work with Eclipse but directly with DBeaver.
I believe that any IDE I have worked with that supported projects allowed to close/unload a project, not just delete it - so the request seemed trivial enough. Why not all IDEs suffice with collapsed project trees?
My initial use case is not something that would really justify it - I am writing a guide on how to connect to our DB environments using DBeaver and in order to explain how to open a project I wanted to close it first :)

Perhaps a good use case would be if you have multiple versions of the same "project" each for a different env or bug fix branches.

**Comment by serge-rider** [comment]
Ok. You don't need to delete anything. Projects initially were designed specifically to group database connections.
Short video below shows how you can organize connections and switch active project:

![project-switch](https://user-images.githubusercontent.com/6398845/51694147-352a2c80-2011-11e9-896a-9c0c71494861.gif)

Database Navigator view shows only active project contents. If you have closed this view then you can open it in main menu Window.

**Comment by pyrocks** [comment]
Thanks, but I actually work with the Projects window and not the Database Navigator since I work with multiple connections/db types and many files in parallel.

**Comment by serge-rider** [comment]
Ok. But eventually it is not clear the purpose of "project close". 
What it means in terms of UI? 
What is the difference with simple project node collapse.

**Comment by pyrocks** [comment]
How I think it should be (how I think every other IDE handles projects):
Close: remove from the list of projects WITHOUT deleting the project settings and/or connections files. Will allow to open it again later if needed. does not ask to delete anything.
Delete: remove from the list of projects AND delete the project settings and/or connections. Ask if also to delete the rest of the files under the project folder.

**Comment by serge-rider** [comment]
Could you say what IDE do you mean?

As far as I know there is no such feature in Eclipse or Jetbrains based IDEs (I believe it is more than 50% of all IDEs at all). I'm curious how this feature may look.

**Comment by pyrocks** [comment]
https://www.jetbrains.com/help/webstorm/opening-reopening-and-closing-projects.html
https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Ftasks-47.htm
https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by p91paul** [comment]
In Eclipse, when you "close" a project, it just gets collapsed, but it is still visibile. Additionally Eclipse stops indexing and building them, but it's not like DBeaver indexes or build anything, so that's quite useless I believe.

When you say: "Close: remove from the list of projects WITHOUT deleting the project settings and/or connections files.". That's not how Eclipse's "close" works. That's how delete works (if you don't check the delete project contents checkbox). And DBeaver delete works the same way: it asks if you want to remove files, and if you don't, you can reopen that project later from the File menu.

The page you link from Jetbrains is even more confusing, since Intellij "projects" are much more like Eclipse's workspaces. Eclipse's projects equivalents are called "modules" in Intellij, and I'm not aware of a way to "close" them...you just delete them.

As for VSCode...the only mention at that seems to be:

> How can I go back to working with a single project folder?
> You can either close the Workspace and open the folder directly or remove the folder from Workspace

So even there, you "remove". Searching for "close", all instances is referred to the whole workspace and act much like Intellij's close project: they bring you to an empty window asking to open a new workspace.

**Comment by pyrocks** [comment]
I worked a lot with intellij and I opened/closed projects all the time.
If you do the translation of workspace=intellij project & project=intellij module - then I guess your statement makes sense. Since I don't work with workspaces/eclipse - it makes less sense/feels less native to me.
Either way - I give up. Thanks for your time.

**Comment by p91paul** [comment]
Ok you can possibly achieve the equivalent of switching projects in Intellij with File -> Switch workspace. You select a new folder for your workspace and you are able to create new projects - just like you are able to create new modules in a new Intellij project. Switching back to the first workspace will bring back all the projects you had. Just like Intellij, Eclipse/Dbeaver will show you the list of the last workspaces in the File -> switch workspace menu. If you apply workspace = project, project = module, switch workspace = close + open project, you should be able to get your usual workflow.

**Comment by serge-rider** [comment]
@p91paul yep, perfect explanation, thanks.

**Comment by stopsopa** [comment]
> Hi,
> 
> I do not work with Eclipse but directly with DBeaver. I believe that any IDE I have worked with that supported projects allowed to close/unload a project, not just delete it - so the request seemed trivial enough. Why not all IDEs suffice with collapsed project trees? My initial use case is not something that would really justify it - I am writing a guide on how to connect to our DB environments using DBeaver and in order to explain how to open a project I wanted to close it first :)
> 
> Perhaps a good use case would be if you have multiple versions of the same "project" each for a different env or bug fix branches.

I think there is no point to try to explain to @serge-rider what is the difference between close and collapse. 
We all collectively tried and clearly it doesn't work.

Anyway:
It seems when you try to delete project there is a tickbox: 

<img width="669" height="191" alt="Image" src="https://github.com/user-attachments/assets/58ad18ae-c634-48c4-8d0b-0b0205bb1bbb" />

---

it seems to be mentioned here also: https://dbeaver.com/docs/dbeaver/Projects/#creating-a-project
