### ISSUE TITLE
Diagram elements are messed up after changing 'Show attributes' parameter

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#5056]
#### System information: 
- win 10 x64
- DBeaver version 5.3.3

#### Connection specification:
- MS SQL Server

#### Describe the problem you're observing:
Query results cannot be grouped using Grouping panel.
#### Steps to reproduce, if exist:
1. Create New Custom Diagram
2. Add some tables to it
3. Change 'Show attribute' parameter for ONE table

https://screenpresso.com/=042Xc

**Comment by serge-rider** [comment]
Diagram relayout was added.

**Comment by uslss** [comment]
verified
