### ISSUE TITLE
mysql ssh tunneling failing until connecting to a non-mysql databases

### ISSUE THREAD

**Issue by Mizar01** [dbeaver/dbeaver#5059]
Hello.
I'm trying to connect to a mysql db through an ssh tunnel.

The connection will never work (it returns an auth fail) until I connect to a non-mysql server through tunneling.

For example:
- I try to connect to mariadbServer1. I get 'Auth fail : can't initialize tunnel'. (this will happen for every mysql like db connection).
- I connect to oracleServer1: the ssh connection is of the same type of the others. It works.
- I connect to mariadbServer1 again. This time the connection will work. From now on the connections to all mysql servers will work. The connection to oracleServer1 is not needed anymore.
- When I restart dbeaver, the problem is there again.

I would like to avoid connecting to other servers before connecting to the one I want. But I can't find any clue about the issue here.
I tried with other software like dbeaver and the connection is working right at the first try. I always had this problem only with dbeaver and I always updated it. I think it's something related to ssh global status inside the jvm running dbeaver.

**Comment by serge-rider** [comment]
I can't reproduce this. And this sounds very odd.
Please post debug/error logs (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by uslss** [comment]
there is no update on ticket for a long time.
Ticket closed
