### ISSUE TITLE
Check for updates does not work

### ISSUE THREAD

**Issue by tchibatron** [dbeaver/dbeaver#5062]
When DBeaver starts it shows that new version is avaialble, but when I click Check for Updates from main menu, it shows, that I am using the latest version.

![image](https://user-images.githubusercontent.com/6930846/51472719-5aa60480-1d8b-11e9-99b0-f7bbf3667f53.png)

#### System information: 
- Windows 10
- DBeaver version 5.3.2.201901062110
- Java version: 8
- Additional extensions: no

In log I see only: 
`2019-01-21 14:47:55.310 - Open [https://dbeaver.io/product/version.xml]`
Which has correct content.

**Comment by serge-rider** [comment]
By some reason I can't reproduce this..

**Comment by koushiknandan** [comment]
I faced the same one today. Here is the snap.

Added the proxy details in preferences. Verified that the tool is able to access internet by going to the plugins page.

![image](https://user-images.githubusercontent.com/48122532/53633504-a9be3f80-3c3d-11e9-8a82-f0e1286b6a63.png)

**Comment by tchibatron** [comment]
Does not reproduce anymore: 
![image](https://user-images.githubusercontent.com/6930846/58936551-abd1f600-8778-11e9-8a85-3bb1dd79b305.png)
