### ISSUE TITLE
oracle error on execute sys.all_tables

### ISSUE THREAD

**Issue by luizplago** [dbeaver/dbeaver#5065]
I have the following problem dbeaver executes commands of type SELECT * FROM sys.all_tables, but here in the company the database was not created in this way so it was created SELECT * FROM syscat.all_tables or just without the schema using SYNONYM. Where I could configure for the driver does not use the sys schema or change it.

![select-result-dbeaver](https://user-images.githubusercontent.com/1467093/51480328-ea41b800-1d77-11e9-8331-2d4f016a21b9.png)

**Comment by serge-rider** [comment]
Unfortunately this is not supported. Schema SYS can't be changed.

Mark as FR, it should be configurable.

**Comment by serge-rider** [comment]
It is disabled by default
![image](https://user-images.githubusercontent.com/6398845/55880670-dbfe7d80-5ba9-11e9-98e7-d623df73bcc1.png)

**Comment by luizplago** [comment]
so where would the prefix to be used would be placed? Or will SYNONYM be used in this way?

**Comment by serge-rider** [comment]
It will use SYS views without schema prefix. I.e. public synonyms in regular Oracle installation.

**Comment by uslss** [comment]
verified
