### ISSUE TITLE
5.3.3 SQL Error [S1009] Parameter is not registered as an output parameter - MySQL stored procedure

### ISSUE THREAD

**Issue by dorinmun** [dbeaver/dbeaver#5068]
#### System information: 
- Operating system macOS Mojave 10.14.2
- DBeaver 5.3.3
- Java version 1.8.0_192

#### Connection specification:
- Database name and version: MySQL 5.6.38-83.0
- Driver name: mysql-connector-java-5.1.37
- Do you use tunnels or proxies (SSH, SOCKS, etc): No

Calling a stored procedure with output parameters fails with the error message:
SQL Error [S1009]: Parameter parameter_name is not registered as an output parameter.
![image](https://user-images.githubusercontent.com/11156422/51518294-1d428500-1e26-11e9-8a09-0b337ca49cfd.png)

The issue seems to manifest in several of the last versions. Does not affect 5.2.1.

#### Steps to reproduce:
This stored procedure works fine in 5.2.1, but fails in 5.3.3 as well as in 5.2.5.
DELIMITER $$
CREATE PROCEDURE sp_Test (OUT p_out INT)
BEGIN
	SET p_out = 1;
END$$
DELIMITER ;

call sp_Test(@var);

**Comment by serge-rider** [comment]
This works:
```sql
call sp_Test(?);
```
Are you sure that syntax @var worked in previous versions?

**Comment by dorinmun** [comment]
Yes, it definitely works in 5.2.1.

![image](https://user-images.githubusercontent.com/11156422/51972754-d76c6900-2484-11e9-8d8b-63e17402a4a8.png)

**Comment by serge-rider** [comment]
Indeed. 
We have added support of output parameters fetching but broke native MySQL parameters reading.
Now fixed (both way must work ok). 

Thanks for the bug report.

**Comment by dorinmun** [comment]
Thank you very much for the fix and thank you for the wonderful DBeaver!

**Comment by Gaurav560** [comment]
My error
![Screenshot (337)](https://user-images.githubusercontent.com/98982243/221679398-9045db71-aef0-4d84-a1e4-3eca8f8221ae.png)

My stored procedure with table 
![Screenshot (338)](https://user-images.githubusercontent.com/98982243/221679587-14d0e849-debe-4229-a8fb-5ffafc0bdd5e.png)

facing the same issue .not an out parameter .can u help me resolve the issue

**Comment by Gaurav560** [comment]
stuck in this issue for a while now

**Comment by Bluefield-Identity** [comment]
Maybe RATE is a reserved word?
