### ISSUE TITLE
First column for secondary index missing in Apache Ignite 

### ISSUE THREAD

**Issue by drosso64** [dbeaver/dbeaver#5072]
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version : 5.3.3
- Java version : 1.8.0_111
- Additional extensions

#### Connection specification:
- Database name and version : Apache Ignite 2.4.0
- Driver name : org.apache.ignite.IgniteJdbcThinDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
DBeaver doesn't show the first column of secondary indexes.  Even with the DDL "Create Table" script the first column is missing. 

#### Steps to reproduce, if exist:
Create a secondary index (in DBeaver or programmatically in Java)
Look for index information in DBeaver

**Comment by serge-rider** [comment]
Could you post sample DDL of such table?

**Comment by serge-rider** [comment]
Nevermind, I've reproduced this

**Comment by serge-rider** [comment]
Also check #5150 - we'll add Ignite config in default DBeaver distribution.
