### ISSUE TITLE
Allow only a single dbeaver window

### ISSUE THREAD

**Issue by fabiopedrosa** [dbeaver/dbeaver#5073]
Could there be an option in Settings to enable "single window" use? So if I mistakenly try to start another instance of dbeaver, it would just bring focus to the already started window.

**Comment by serge-rider** [comment]
Generally this is already implemented. When you start DBeaver for the second time it shows dialog with Retry-Ignore options.

Or is this FR about focusing running instance? (currently we do this only if you start second instance with some CLI parameter, e.g. open SQL file on disk).

**Comment by fabiopedrosa** [comment]
@serge-rider I completely forgot about that, I always use the `-data` parameter to set a different workspace folder. In that case, I never see that retry-ignore, but instead opens a 2nd, 3rd window. Could you allow a single window in that case, maybe with a flag `-single-window`

**Comment by serge-rider** [comment]
Agreed, this makes sense

**Comment by uslss** [comment]
verified
