### ISSUE TITLE
"Double-click on connection" behaviour partially broken since 5.3.2

### ISSUE THREAD

**Issue by rwalravens** [dbeaver/dbeaver#5088]
Since version 5.3.2, the "Double-click on connection" behaviour is broken.

Configured | result 5.3.2/5.3.3
------------ | -------------
Open Properties | opens connection configuration
Connect / Disconnect | does nothing
Open SQL Editor | opens *new* SQL editor
Expand / Collapse | expands or collapses
Open new SQL Editor | opens *most recent* SQL editor

So *connect/disconnect* is broken, and *open SQL editor* and *open new SQL editor* were swapped.

Just a little remark: although *open properties* hasn't changed, it is confusing it does not open the properties of the connection object (like <kbd>ALT</kbd><kbd>Enter</kbd>), but instead it opens the configuration (<kbd>F4</kbd>).

**Comment by marco-sanjuan** [comment]
Same here.

#### System information: 
- Debian 9
- DBeaver 3.5.3
- Java 8

#### Connection specification:
- Oracle 12g
- Driver oracle.jdbc.OracleDriver

**Comment by serge-rider** [comment]
Thanks for the bug report
