### ISSUE TITLE
Delete Previous Word (ALT + Backspace) deletes too much

### ISSUE THREAD

**Issue by DOFandersolsen** [dbeaver/dbeaver#5090]
#### System information: 
- OS: MacOS High Sierra 10.13.6
- DBeaver: 5.3.3.201901202008
- Java version "1.8.0_91"

#### Describe the problem you're observing:
When I've entered an incorrect table name, and quickly want to delete it, I normally use alt + backspace. This has previously worked, but now it also deletes the `database.` prefix in front of the table name

#### Steps to reproduce, if exist:

- Open a new SQL Editor
- Write `SELECT * FROM testdb.tablename`
- Press ALT + Backspace

**What happens:**  
The SQL Editor will now show: `SELECT * FROM`

**What I expected:**  
The SQL Editor should show `SELECT * FROM testdb.`

**Comment by uslss** [comment]
issue isn't reproducible anymore.
ticket closed.
if it is still actual for you, feel free to reopen the ticket
