### ISSUE TITLE
Add SCRAM-SHA-256 as credential mechanism for MongoDB connections

### ISSUE THREAD

**Issue by balderstonb** [dbeaver/dbeaver#5092]
MongoDB connection settings does not have SCRAM-SHA-256 in the list of Mechanisms under Credentials:

![image](https://user-images.githubusercontent.com/1740115/51681112-a803bb00-1fb1-11e9-902d-2ffe119956cb.png)

Without that option, you can't connect to MongoDB 4.0 servers where the created user only has "SCRAM-SHA-256" in lists of mechanisms, and not "SCRAM-SHA-1".

**Comment by serge-rider** [comment]
Thanks for the bug report. 
We'll publish Early Access version with this fix  till the end of week.

**Comment by Neustradamus** [comment]
Nice! :)
