### ISSUE TITLE
OR ALTER missing in MSSQL DDL for views

### ISSUE THREAD

**Issue by yozgoesdigital** [dbeaver/dbeaver#5093]
#### System information: 
- Win10
- DBeaver version: 5.3.3.201901202008

#### Connection specification:
- Azure Sql database

#### Describe the problem you're observing:
when creating a view the command is executed properly using
> CREATE OR ALTER VIEW xxx ....

But than after going to the view and dowload the DDL 'OR ALTER' is missing. It appears the spaces are retained, so maybe it is not copied/extracted properly?
This is copied from the DDL of the created views (please not the 3 spaces instead of 1):
> CREATE   VIEW 
I have been able to reproduce this with all created views.

**Comment by serge-rider** [comment]
We show DDL as it is stored on server-side.
Once you will try to change view definition DBeaver will replace CREATE with ALTER in the final script.

**Comment by yozgoesdigital** [comment]
When I try just the ALTER VIEW command the command is executed properly but the DDL show in Dbeaver is than changed to CREATE VIEW. For easy updating views I would have preferred the CREATE OR ALTER.
But based on your reply it is MSSQL server which stores it like this. So than I guess we just have to live with it. Thanks for the reply
