### ISSUE TITLE
"New connection" tab Incorrect view [dark theme]

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#5096]
#### System information: 
- win 10 x64
- DBeaver version 5.3.4

#### Describe the problem you're observing:
Text isn't readable on Gallery connections view
![image](https://user-images.githubusercontent.com/31996417/51708054-f3f74400-2033-11e9-854c-b344a2455d94.png)

**Comment by serge-rider** [comment]
This issue was resolved in #5066
