### ISSUE TITLE
Shortcut for word auto complete not working

### ISSUE THREAD

**Issue by nmsanto** [dbeaver/dbeaver#5099]
Hello,
I'm new to DBeaver and i'm having problems with the shortcut Ctrl+Shift+Space to Word Completition because nothing happens but I have some templates configured,
Thank you,

**Comment by shungabubus** [comment]
Hey, how did you configure the templates? I am also new but it looks like it is only bringing the same box like when you type so maybe you are searching for a different function or angle. (Me too!)

**Comment by shungabubus** [comment]
Hey, I knew we were thinking similarly, but we were wrong. :) Templates are used with CTRL+ALT+SPACE.
https://github.com/dbeaver/dbeaver/wiki/SQL-Templates

Can anyone close this issue please? :)

**Comment by shungabubus** [comment]
@nmsanto hey, are you watching it? You can close the topic if it suits you...
