### ISSUE TITLE
Sybase: Stored Procedure Names Showing Incorrectly

### ISSUE THREAD

**Issue by ChristianStanleyTaylor** [dbeaver/dbeaver#5100]
### System information: 
- Operating system Windows 10 Build 14393.969
- DBeaver version 5.3.1.201812232236
- Java version 1.8.0_144
- Additional extensions None

#### Connection specification:
- Database name and version Sybase Adaptive Server Enterprise 12.5.4
- Driver name Sybase jConnect
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Stored procedures aren't showing correct names. All procedures have only a few similar names that are repeated for all procedures. Picture Attached. 
#### Steps to reproduce, if exist:
Constant issue. 
#### Include any warning/errors/backtraces from the logs
Attached
[Error Log 201901251530.txt](https://github.com/dbeaver/dbeaver/files/2794688/Error.Log.201901251530.txt)

![image](https://user-images.githubusercontent.com/9969602/51725933-edf77680-20b8-11e9-8592-caebbdf53b0d.png)

**Comment by serge-rider** [comment]
This issue was resolved in #5002
Please download DBeaver 5.3.3
