### ISSUE TITLE
PostgreSQL database description (comment)

### ISSUE THREAD

**Issue by VPetrow** [dbeaver/dbeaver#5101]
#### System information: 
- Operating system: Win10
- DBeaver version: 5.3.3

#### Connection specification:
- Database name and version: PostgreSQL

#### Describe the problem you're observing:
Database has no field "Description" in Properties

**Comment by mkgrgis** [comment]
Analog (?) https://github.com/dbeaver/dbeaver/issues/5316

**Comment by serge-rider** [comment]
I don't understand what #5316 is about :(

**Comment by mkgrgis** [comment]
#5316 is about descriptions in GUI, but in Oracle and in some objects.

**Comment by uslss** [comment]
verified.
i18n ticket created.
