### ISSUE TITLE
Text looks quite strange for options that are not available for changing

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#5116]
#### System information: 
- win 10 x64
- DBeaver version 5.3.4
#### Describe the problem you're observing:
Text for options in preferences that aren't available for changing looks quite strange or almost invisible
![image](https://user-images.githubusercontent.com/31996417/51792358-ecb17100-21c0-11e9-80af-80ecc955cd99.png)

**Comment by serge-rider** [comment]
It is clor theme defined in Eclipse, we can't fix it.
