### ISSUE TITLE
Feature request: Script tab context menu: add Delete file option

### ISSUE THREAD

**Issue by SergeySch** [dbeaver/dbeaver#5124]
#### System information: 
- Windows 10
- DBeaver v 5.3.3.201901202008
- Java version 1.8

#### Connection specification:
- MySql

#### Describe the problem you're observing:
Feature request: Add option to delete file from script editor tab context menu. Right now there are already 3 useful options for organizing script files: 
- Open folder in Explorer
- Copy File Path
- Rename File 

 Adding delete option will be also very useful. Currently to delete script file you need to open "Project explorer" find there connection/folder/server->script file and delete from there.

Thank you very much!

**Comment by serge-rider** [comment]
This makes sense.

As a workaround you can click on "Link with editor" button in Project Explorer view and delete file there.
