### ISSUE TITLE
Unable to change UI label foreground color from black with Dark Theme

### ISSUE THREAD

**Issue by crokusek2** [dbeaver/dbeaver#5126]
#### System information: 
- Windows 10
- DBeaver version 5.3.3.201901202008

#### Describe the problem you're observing:
When using dark theme, a black foreground color is used for a number of labels and dialog headers making it nearly invisible due lack contrast.  The screenshot circles 2 elements (there are more).  There doesn't seem to be a any custom setting under appearance to change it.

#### Steps to reproduce, if exist:
Change to dark theme.  Navigate around and look for black foreground.

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/25240263/51807682-02657b80-223f-11e9-98ba-c35ef765a3dc.png)

**Comment by uslss** [comment]
partially reproduced 
![image](https://user-images.githubusercontent.com/31996417/52013427-12ef4d80-24ee-11e9-9387-765626ed8425.png)

**Comment by serge-rider** [comment]
We can't fix headers in preference pages (it comes from Eclipse)

**Comment by crokusek** [comment]
To clarify, the black color itself is not coming from a theme parameter or from a preference option?

**Comment by tati-kru** [comment]
Fixed in 5.3.4. Please, restart DBeaver after theme changing.
