### ISSUE TITLE
The dbeaver can't return result set after call Sybase ASE store procedure

### ISSUE THREAD

**Issue by iihero** [dbeaver/dbeaver#5130]
[jconn4.zip](https://github.com/dbeaver/dbeaver/files/2801643/jconn4.zip)
Just unzip it for the jar file as the jdbc driver.
Use jconnect ASE jdbc driver (offlicial).
Create a simple table : create table T (id int primary key, col2 varchar(32))
execute a query: 
exec sp_spaceused T
We only see  " Updated rows : " 1
But can't see any result set. 
In fact, this store procedure can return multiple resultsets.

jdbc driver jar:

**Comment by uslss** [comment]
issue is already obsolete
![image](https://user-images.githubusercontent.com/31996417/82096872-72389780-970a-11ea-80cc-9fedfdbea887.png)
