### ISSUE TITLE
Pasting a big query freezes app for too long (performance issue)

### ISSUE THREAD

**Issue by raqua** [dbeaver/dbeaver#5132]
#### System information: 
- Operating system (distribution) and version: Linux Mint 18
- DBeaver version : 5.3.3
- Java version : openjdk version "1.8.0_191"
- Additional extensions : None AFAIK

#### Connection specification:
- Database name and version: Oracle 12
- Driver name: ?
- Do you use tunnels or proxies (SSH, SOCKS, etc) : No

#### Describe the problem you're observing:
When I paste huge query to DBeaver, it uses one CPU core 100% and takes a long time to respond. Query is copied from myBatis log, so has '?' instead of parameters. It's parsing or whatever is DBeaver doing with it is too slow. 

#### Steps to reproduce, if exist:
I am attaching the query to this report. Try to paste it into the app. 

[query.sql.zip](https://github.com/dbeaver/dbeaver/files/2803648/query.sql.zip)

**Comment by iskinn** [comment]
Long sql query is opened very long from a file or inserted from the clipboard.
It is almost impossible to work with a long query in the query editor . Very frequent program freezes and high CPU usage.

**Comment by serge-rider** [comment]
A Linux-specific issue perhaps.
Specified query works well (more or less) on Windows.

**Comment by iskinn** [comment]
In mac OS, a long query also causes the app freezing for 5-6 seconds. This happens when switching to a long query string

**Comment by uslss** [comment]
not reproducible against 21.2.0

**Comment by zenstark** [comment]
@uslss I am able to reproduce this on version 22.0.3 on Ubuntu 20 operation system

**Comment by cyreb7** [comment]
I'm also getting this with version 22.2.3 on Ubuntu 22.

**Comment by sumitpatil04** [comment]
I am also getting this with version 21.0.5 on Windows 10 Pro machine **Processor: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz   2.11 GHz and RAM - 16.0 GB**

**Comment by AndrewTheJavaGuy** [comment]
I am on a Macbook Pro with 8-Core Intel Core i9 and 16GB memory using DB Beaver Verrsion 23.0.2.202304091457

I was guessing something is trying to parse or interpret the SQL or similar after it gets pasted in.

Turned off SQL Editor -> Enable Auto Activation, Auto-Insert proposal and Data Editor -> Read table metadata, Read table references and it didn't quite hang as bad when I pasted things in there.

It's probably not a normal occurreance to try to run 3+ MB worth of SQL in an SQL client that will try to parse / interpret / lookup things.

Just leaving this here as a comment in case anyone else comes to this bug while searching for things.
