### ISSUE TITLE
"Server doesn't support SSL" error after upgrading to 5.3.3

### ISSUE THREAD

**Issue by ThreeDots3** [dbeaver/dbeaver#5133]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04
- DBeaver version: 5.3.3
- Java version: 8

#### Connection specification:
- Database name and version: Postgresql 10.6
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
After upgrading DBeaver to 5.3.3, I cannot connect to the server anymore as the error message says, that server doesn't support SSL. Except I am not using SSL connection, all I have selected in connection settings is host, port, user, password and database... nothing else

Using the older version of DBeaver, the connection with the exact same settings is just fine

**Comment by serge-rider** [comment]
I can't reproduce this.
Please check Driver Properties and Network settings (SSL) pages.
If there is nothing there then please post error/debug log.

**Comment by ThreeDots3** [comment]
So as I was going deep trough settings and debug logs I noticed I was still using postgresql driver 9.3, we upgraded our database to version 10.6. about a month ago, but DBeaver was fine with that, so I didn't even think of changing anything. The 5.3.3 changes probably caused it's not fine anymore to use old driver... 

**So I did a driver upgrade and it connects just fine.**

For me the problem is solved and was caused by my settings. I would only consider if there is an option to detect such state and return an error message related to that. The problem is that the error was not raised by DBeaver, but `org.postgresql.util.PSQLException` was thrown by the driver and DBeaver only showed the error message. If you decide to work on that, I can provide full stack trace of the error.

**Comment by ChristopD** [comment]
With postgres 9.2 driver, we have the same issue

Keeping this 9.2 driver, we are able to avoid this error message with this config edition :
- Edit connection
- Network -> SSL
- Check "Use SSL" and set SSL mode to "disable" and save settings.
=> works !

Somewhere in dbeaver 5.3.x, SSL became enabled by default, even if "Use SSL" is not checked. 
Hope it helps.

**Comment by maikgreubel** [comment]
> Hope it helps.

Best workarround ever!!! And yes! It works!
