### ISSUE TITLE
Update SSHJ 0.26.0 (2018-07-24) to 0.27.0 (2019-01-24)

### ISSUE THREAD

**Issue by nasatome** [dbeaver/dbeaver#5136]
#### System information: 
- Linux Ubuntu 18.04
- DBeaver version: 5.3.3
- openjdk version "1.8.0_191"
- OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.10.1-b12)
- OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

#### Additional extensions
  DBeaver SSHJ
https://dbeaver.io/update/sshj/latest/plugins/org.jkiss.bundle.sshj_0.26.0.jar

#### Problem: 
This is not a problem, rather it is a new implementation of SSHJ
https://github.com/dbeaver/dbeaver/issues/4585
have an error while taking the key ed25519

#### Is solved in:
Fixed https://github.com/hierynomus/sshj/issues/467: Added AES256-CBC as cipher mode in openssh-key-v1 support
Fixed https://github.com/hierynomus/sshj/issues/427: Support encrypted ed25519 openssh-key-v1 files

For example:
I think it could be solved here:
https://github.com/dbeaver/dbeaver/commit/d195bbda729b1828f85cb52342a5628e7132ff52
`<artifact><id>org.jkiss.bundle:org.jkiss.bundle.sshj:0.27.0</id></artifact>`
But I do not know, I'm not any Java expert. I hope you can help me.

#### Include any warning/errors/backtraces from the logs
"Cipher 'aes256-cbc' not currently implemented for openssh-key-v1 format"

**Comment by serge-rider** [comment]
Agreed.
Thanks for noticing.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/51990534-47491680-24ba-11e9-9e4d-2ac6f9664e98.png)
