### ISSUE TITLE
"Save As..." Cancels Query/Connection

### ISSUE THREAD

**Issue by dmriviello** [dbeaver/dbeaver#5161]
#### System information: 
- Operating system (distribution) and version - Windows 7
- DBeaver version - 5.2.4.201811051019
- Java version - 10.0.2
- Additional extensions - N/A

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When a user does a "Save As..." to save a new script/file, the connection resets or invalidates stopping any queries running and resetting the connection.  

#### Steps to reproduce, if exist:
1-Execute long running query
2-File > "Save As..."
3-Save the file under a new name
4-Error should be received and you should be disconnected

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
