### ISSUE TITLE
Add option to open a project file that does not comply with associated extensions in built-in editor

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#5162]
Hi,

I would like to be able to open **any** project file with the built in editor, even ones with non associated extensions (without going through the File --> open file menu).
Currently when I double click such a file it either opens it in the associated app or tells me there's no associated app.
One way to do it would be to add an "Open as script" option when right clicking the file.

Use case: I am working with FlyWay to upgrade my DBs.
Sometimes to exclude a file from an upgrade I rename it to .old, at least temporarily.
I don't want to add the .old file as associated (or any other extension for that matter).

I assume this can be a handy feature.
Using DBeaver Community 5.3.3.

p.s
I tried changing the _Open unassociated files with_ setting but it didn't seem to make a difference.

**Comment by serge-rider** [comment]
In fact this is more like a bug.
DBeaver just ignored "Open unassociated files" option. Now fixed, thanks for noticing.
