### ISSUE TITLE
DBeaver: The new formatting of the Plain Text View does not add any Leading Delimiter

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5165]
DBeaver - **Version 5.3.4 CE** - **EA 31-Jan-2019 16:37**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

Seems that the new property **Extra spaces** behaviour in _DBeaver_ version **EA 5.3.4** (from CASE #5054) to add extra leading and trailing space when viewing a result set grid in **Text View** is not working fully.

The extra trailing space seems to work, but **the leading space is not generated**.

**Global properties/settings**:

![2019-01-31 22-17-53](https://user-images.githubusercontent.com/31191374/52086090-50afad00-25a6-11e9-8740-7555d9f1dad5.png)

**Data result gridin Text View**:

![2019-01-31 17-55-18](https://user-images.githubusercontent.com/31191374/52071170-b722d400-2582-11e9-9ba1-ed698bea18d7.png)

Hopefully this can be fixed before the version **5.3.4** is shipped.

**Comment by S-Man42** [comment]
This option should add both: trailing and leading space:
Actual:
```
|id     |released   |
|-------|-----------|
|     1 |2001-11-04 |
|     2 |2002-11-03 |
|     3 |2004-05-23 |
```
Expected
```
| id    | released   |
|-------|------------|
|     1 | 2001-11-04 |
|     2 | 2002-11-03 |
|     3 | 2004-05-23 |
```
