### ISSUE TITLE
Feature request: improve autocomplete in filter bar

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#5167]
Auto-complete in sql editor is now quite advanced: tables and columns appear as you type without invoking completion explicitly, it searches in the middle of names with advanced sorting of proposals. All of this, however, is missing when using completion from the filter bar in result sets: you need to use ctrl+space to invoke completion, it only finds stuff *starting with* what you typed, etc.

Can it be brought on par with the SQL Editor completion?
Thanks!

**Comment by serge-rider** [comment]
It won't be very easy. But still doable.

**Comment by serge-rider** [comment]
I believe mostly it was implemented in previous release. Some extra improvements (e.g.g coloring) will be added in 7.0.
