### ISSUE TITLE
Open declaration is not searching Active Catalog, it only seems to search DB specified in Connection DataSource

### ISSUE THREAD

**Issue by crokusek** [dbeaver/dbeaver#5168]
#### System information: 
- Windows 10
- DBeaver 5.3.3.201901202008
- JRE came with download of 5.3

#### Connection specification:
- DataSource database is "TheDatabase"
- Active Catalog is "TheOtherDatabase#3_1"
- SQL Server latest driver

#### Describe the problem you're observing:
Click F4 on a view name and receive "Can't find metadata object for name 'SomeViewName'
Seems like it is failing when the active catalog has a pound sign in it.  90% of our DBs names include a pound sign (for versioning).

#### Steps to reproduce, if exist:
1) Choose a database with a pound sign in it.  The '@' sign may also be used--such as TheDatabase#3_1@2.   These are legal characters in SQL Server as shown [here](https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers?view=sql-server-2017)
2) select * from TheDatabase#3_1@2.
3) Hover over the table name and click F4.  The "Can't Find..." error is shown

Related:  Clicking F2 on a DB with a #/@ at the end displays a stripped version.

**Comment by serge-rider** [comment]
See fix in 6.0.3.
It also can be tested in Early Access version (https://dbeaver.io/files/ea)

**Comment by uslss** [comment]
verified
