### ISSUE TITLE
DBeaver: The checkbox for the global setting Value Format - Trailing delimiter misbehaves

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5170]
DBeaver - **Version 5.3.4 CE** - **EA 31-Jan-2019 16:37**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

The use of the checkbox for the **global** parameter/setting **Database** -> **Editors** -> **Data Editor** -> **Presentation** -> **Value Format** -> **Trailing delimiter** is broken.

**o** Start _DBeaver_ and uncheck both **Leading delimiter** and **Trailing delimiter**.
**o** Apply and Close the **global** properties dialog (only).
**o** Open the **global** properties dialog again
**o** Check the **Trailing delimiter** checkbox.
**o** Apply and Close the **global** properties dialog.
**o** Open the **global** properties dialog again
**o** The **Trailing delimiter** is unchecked. This is an **ERROR**.
**o** Check the **Leading delimiter** checkbox.
**o** Apply and Close the **global** properties dialog.
**o** Open the **global** properties dialog again
**o** Now both checkboxes are checked. This is an **ERROR**.

Seems the use of the first **Leading delimiter** checkbox also affect the checked status of the second **Trailing delimiter** checkbox.

**Comment by serge-rider** [comment]
This was fixed a few days ago (commit https://github.com/dbeaver/dbeaver/commit/c57851aad7b5dd3a09daaa4bf5e69c0522c2d413)
