### ISSUE TITLE
CSV export won't add quotes

### ISSUE THREAD

**Issue by therealrobster** [dbeaver/dbeaver#5173]
#### System information: 
- Ubuntu 18.04
- DBeaver version 5.3.2.2.xxxxx
- Java version 
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
- Additional extensions

#### Connection specification:
- Database name and version : HSQLDB / Embedded
- Driver name : HSQLDB / Embedded
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  ??

#### Describe the problem you're observing:

I have some tables I've loaded up from another database that I've been tasked to convert.  I right click table and do the following:
- Export Data
- CSV
- Single Query / Open New Connections (ticked) / Select Row Count (ticked)
- Binaries (set to NULL)
- File Extension (CSV) / Delimiter (,) / Header (top) / Characters escape (escape and also tried quotes) / Quote Character (") / Quote Always (ticked) / Quote Never (unticked) / NULL Strings (empty) / Format Numbers (unticked)
- Either Save to a file OR copy to clipboard 

This is an example of the data that is exported as copied to clipboard and pasted here:
14814,Description, 60,134,160

Now I would have expected it to be:
"14814","Description", "60","134","160"

I've tried many things, is this a bug?

#### Include any warning/errors/backtraces from the logs
There were no errors in the logs when looking

**Comment by serge-rider** [comment]
Can't reproduce. 
Please post screenshot of CSV export configuration page.

**Comment by therealrobster** [comment]
Hi and thanks for looking.

Here are the screenshots:  https://imgur.com/a/yfjN5ds

Please note you'll see I try both quotes and escape and I get the same result each time (no quoted cells when I open the CSV".  

Also I try copy to clipboard and save file but still the same.

**Comment by therealrobster** [comment]
UPDATE:  Tried with the very latest build and still the same problem.  To confirm I loaded the same dataset with the same drivers in SQLRazor and it exported with quotes surrounding data that has a delimiter in it, so it eliminates the data source as the issue.

**Comment by serge-rider** [comment]
As I see from screenshot you have wrong configuration for quote character. It is ` "` i.e. space + quote character. Just reset this property value to default or change it manually.
