### ISSUE TITLE
Your password does not satisfy the current policy requirements in mysql5.6

### ISSUE THREAD

**Issue by github24518** [dbeaver/dbeaver#5175]
#### System information: 
- Operating system (distribution) and version
DBeaver version = 5.1.6
- Java version     
- Additional extensions

#### Connection specification:
- Database name and version  = mysql5.6
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
DBeaver shows alert description 'Your password does not satisfy the current policy requirements' when I create a user in mysql5.6.
excute sql:
          CREATE USER 'tim24518'@'%';
          ALTER USER 'tim24518'@'%'
         IDENTIFIED BY 'Loan!@10.83.83.18:3306' ;
         GRANT Select ON *.* TO 'tim24518'@'%';
          FLUSH PRIVILEGES;

**Comment by serge-rider** [comment]
Well, I can execute this SQL without any issue on my test MySQL server. So this must be some specific password policy on your MySQL server, it has nothing to do with DBeaver.
