### ISSUE TITLE
Teradata datatype PERIOD(Date, Date) is shown as [Object]

### ISSUE THREAD

**Issue by PhilipDijkstra** [dbeaver/dbeaver#5176]
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version 5.3.3

#### Connection specification:
- Database name and version Teradata 16.20.24.01
- Driver name: com.teradata.jdbc.TeraDriver 16.20.00.10

#### Describe the problem you're observing:
Columns of the type PERIOD are shown as 'Object' 

We work in a datawarehouse environment and all timelines are saved in PERIOD fields.
As lead developer i'm trying to move all developers and analists to DBeaver but the the period fields are the most important onces which everyone wants to see immediately in the resultwindow.

#### Steps to reproduce, if exist:
Strangely, when you use this query: select period(date '2019-01-01', date '2019-02-01');
the result is 2 columns, Attr0 & Attr1 which each hold a date.
When querying a table with a period field the resultwindows shows 'Object' in 1 field.

**Comment by serge-rider** [comment]
Unfortunately we don't have live instance of Teradata for testing at the moment..

**Comment by uslss** [comment]
seems issue is fixed for now
![image](https://user-images.githubusercontent.com/31996417/101413211-ec25ad80-38f4-11eb-827c-41fe5f6f3057.png)

**Comment by PhilipDijkstra** [comment]
Thank you very much, this will make adopting dBeaver by our analists a lot easier.
