### ISSUE TITLE
Cannot save diagram as external image

### ISSUE THREAD

**Issue by fedefel** [dbeaver/dbeaver#5178]
#### System information: 
- Microsoft Windows 10 Pro Version	10.0.17134 Build 17134
- DBeaver 5.3.3.201901202008
- Java version 1.8.0_201 64 bit

#### Connection specification:
- MapR distribution with Apache Drill and Hive db
- I have vpn of client company which we're working on a project (we use OpenVPN to connect)

#### Describe the problem you're observing:
I need to get ER diagram of a Hive database (very large), so I double click on the db and it visualizes the tables : I click on export diagram as image, but every time it prompt

**

> No more handles [GetLastError=0x57]

**

I don't have any logs or error to show. 
Tried to add **-vmargs -Xms500m** at the path, but it didn't solve nothing.

any help please?

**Comment by serge-rider** [comment]
This happens because of too big image. It has to fit in memory. Big diagrams (thousands of tables, say 100k x 100k dots) may produce raster image sized in tens of gigs..

**Comment by serge-rider** [comment]
Workaround is to save diagram as SVG and then export SVG to raster image on some 3rd party image editor.

**Comment by timkessler** [comment]
This is still an issue.
Windows 10
DBeaver version 6.3.2.202001051908
160 objects in schema

**Comment by samriddhL** [comment]
Still an issue, what can I do.. not even png is being saved

**Comment by rishacha** [comment]
Still an issue 👀

**Comment by JayceHN** [comment]
Still an issue :'(

**Comment by saad-saeed-07** [comment]
Still an issue

**Comment by Yangeok** [comment]
using version 7.3, still an issue,,

**Comment by pcranger** [comment]
Using Version 22.0.1, still an issue.

**Comment by AxleUnix** [comment]
22.3.0.202212131935
still
(

**Comment by joannren** [comment]
still, save diagram as >224 tables and dbveaver frozen

**Comment by immu2able** [comment]
Using 24.1.202406231636, still an issue. How to export as SVG (it is not listed as an option in the export dialog)
