### ISSUE TITLE
Oracle - GoTo Database Object uses ALL_* views when DBA_* are available

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#5179]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 5.3.3, 5.3.4 EA

#### Connection specification:
- Database name and version: Oracle 11

#### Describe the problem you're observing:
Despite setting the connection as follows:
![immagine](https://user-images.githubusercontent.com/2157006/52121477-0703a880-2620-11e9-877a-05cbf674b6ab.png)

When using GoTo Database Object (CTRL+D) the following query is issued, using ALL_OBJECTS instead of DBA_OBJECTS:
```sql
SELECT  DISTINCT OWNER,OBJECT_NAME,OBJECT_TYPE FROM (SELECT OWNER,OBJECT_NAME,OBJECT_TYPE FROM ALL_OBJECTS WHERE OBJECT_TYPE IN ('TABLE','VIEW','MATERIALIZED VIEW','SYNONYM') AND OBJECT_NAME LIKE '%R%' UNION ALL
SELECT  O.OWNER,O.OBJECT_NAME,O.OBJECT_TYPE
FROM ALL_SYNONYMS S,ALL_OBJECTS O
WHERE O.OWNER=S.TABLE_OWNER AND O.OBJECT_NAME=S.TABLE_NAME AND S.OWNER='PUBLIC' AND S.SYNONYM_NAME LIKE '%R%')
ORDER BY OBJECT_NAME
```

**Comment by p91paul** [comment]
Since just using DBA_* might get too much results, so I suggest GoTo Database Object honors schema filters (adding an OWNER IN ('...') clause).

**Comment by serge-rider** [comment]
Good point.

In regards to schema filter - just select a schema in navigator to narrow search for this schema only.
