### ISSUE TITLE
Driver properties not working with ODBC DSN

### ISSUE THREAD

**Issue by chadwagner1** [dbeaver/dbeaver#5180]
- Operating system: Windows 10
- DBeaver version: 5.3.3
- Java version: (packaged w/ app)

- Driver name: ODBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I am trying to connect to an ODBC datasource, and that datasource requires some additional connection properties to be specified.  I tried entering these under "Driver properties" but they do not appear to be included in the JDBC URL passed to the JDBC-ODBC bridge.  However if I add a semicolon and the property=value to the end of the "Database/Schema" then that works fine.

How does one specific additional connection parameters with ODBC?  Maybe this is the wrong feature?

**Comment by serge-rider** [comment]
Right-click on User Properties item.

![image](https://user-images.githubusercontent.com/6398845/52211940-51915900-289c-11e9-8e10-a30a3b62a7ec.png)

**Comment by chadwagner1** [comment]
Yes, I did that.  However it seems like the property is not being passed to the connect string.  I am trying to connect to a ProvideX database using their ODBC Driver.

I am not sure if this is a limitation of the ODBC driver itself, or not.  It works if I include it as part of the "database name/schema" as I mentioned earlier.  Are these properties passed via the connect string or are they set through another method that maybe the driver doesn't support?

**Comment by serge-rider** [comment]
All properties are passed to native driver using ODBC API (as properties). They are not added to ODBC URL because ODBC bridge driver doesn't support it.

At least default Java ODBC bridge driver. There are other bridge drivers (commercial) but I didn't test them. Some of them have trial versions (e.g. cdata or openlink).
