### ISSUE TITLE
SQL Editors sharing same connection.  Prevents  operations, causes side effects.

### ISSUE THREAD

**Issue by crokusek** [dbeaver/dbeaver#5182]
#### System information: 
- Windows 10
- DBeaver 5.3.3.201901202008
- JRE came with download of 5.3

#### Connection specification:
- SQL Server (latest driver)

#### Describe the problem you're observing:

Each SQL Editor does not maintain its state, they are using the same session and connection.  Is there a way to open separate connections for each window?

This prevents a number of operations:

1) Running a long query in 1 editor blocks short queries in another.  Examples of long queries are reporting queries, rebuild processes, performing a backup.

2) Debugging transactional behavior by beginning a TX in one editor and checking status in another window.  Unable to work/commit outside that org Tx.

3) There are also state variables such as ROWCOUNT, ANSI_NULLs, etc.  If these are changed in one window, I would not have expected them to affect another (as is the case in other tools).

4) Runaway query would block all queries including one to kill that session.

At least 2 other major DB Gui providers (SSMS/Toad) use separate sessions for each editor window.

This is related to issue (https://github.com/dbeaver/dbeaver/issues/5172).

#### Steps to reproduce, if exist:
1) Open query editor, 'select @@spid'
2) Open another query editor 'select @@spid'
3) Values are the same so it is using the same connection.

**Comment by p91paul** [comment]
There's an option for that:
![immagine](https://user-images.githubusercontent.com/2157006/52155256-1f0c1400-2682-11e9-8ef6-2cc616ae12ea.png)

**Comment by crokusek** [comment]
Ahh, nice.  I tested it and it works great.    Related issue  (#5172) may still have some merit.
