### ISSUE TITLE
New dark theme defaults don’t differentiate strings from other text

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#5191]
Just installed the latest update for Dbeaver. Have a dark theme set up, and the update changed the default color for strings (`'text'`) which are now indistinguishable from regular text (both are white, whereas before strings were green). It’s easy to change this in the settings, but I think the default should be to differentiate strings from regular text like in the non-dark version.

**Comment by serge-rider** [comment]
I'm not sure I quite understand the issue, could you post a screenshot?

**Comment by david-cortes** [comment]
![dbeaver_green_strings](https://user-images.githubusercontent.com/11860098/52202337-3a228380-283c-11e9-8499-b6cdeca47a77.png)
![dbeaver_white_str](https://user-images.githubusercontent.com/11860098/52202343-3db60a80-283c-11e9-905e-a999b6551f05.png)
Attached some files showing the difference.

**Comment by serge-rider** [comment]
It is actually a bug in colors definition. 
Thanks for the bug report.
