### ISSUE TITLE
Delete statement result not showed

### ISSUE THREAD

**Issue by georgethemarmot** [dbeaver/dbeaver#5192]
#### System information: 
- Operating system: W10 v1709 64bit
- DBeaver version: 5.3.4.201902031804
- Java version: bundled in setup (1.8.0_77?)
- Additional extensions (office support 1.1.39.201902031804)

#### Connection specification:
- Database name and version: MS Sql Server Express 2008 R2
- Driver name: com.microsoft.sqlserver:mssql-jdbc:RELEASE [7.0.0.jre8]
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
Delete statement result empty when the statement has been run more than once.
Commit doesn't change the behavior 
Normal result sum up:
![image](https://user-images.githubusercontent.com/4931142/52197604-6a7c1900-2860-11e9-89fc-8acb10f10d95.png)
Random Issue:
![image](https://user-images.githubusercontent.com/4931142/52197623-7a93f880-2860-11e9-89d1-bb358cb04ebb.png)
#### Include any warning/errors/backtraces from the logs
[error_1.log](https://github.com/dbeaver/dbeaver/files/2827098/error_1.log)
[unhandled event loop exception.log](https://github.com/dbeaver/dbeaver/files/2827100/unhandled.event.loop.exception.log)

**Comment by serge-rider** [comment]
Thanks for the bug report
