### ISSUE TITLE
Sybase: wrong database for procedures

### ISSUE THREAD

**Issue by jvvelzen** [dbeaver/dbeaver#5193]
#### System information: 
- Windows 10
- 5.3.2
- jdk-11.0.2
- None
#### Connection specification:
- SAP ASE 16.0
- jconnect
- ssh tunnel

#### Describe the problem you're observing:
Creating a new ER diagram. The wrong set of procedures is shown for a user database. The procedure names are from the master database. Tried with and without the user database as the actual database.

#### Steps to reproduce, if exist:
ER Diagrams
Create new ER diagram
choose a server
choose a database
choose a owner
choose procedures

**Comment by serge-rider** [comment]
This is not related to ER diagrams. It is wrong procedure reading function (it doesn't use database name in query).
Thanks for the bug report
