### ISSUE TITLE
MSSQL Insert SQL export date issues

### ISSUE THREAD

**Issue by sspam60** [dbeaver/dbeaver#5195]
#### System information: 
- OS: Ubuntu 16.04.5 LTS
- DBeaver version: 5.3.3
- Java version: 1.8.0_201

#### Connection specification:
- Database name and version: MSSQL Microsoft SQL Server 2017 (RTM-CU4) (KB4056498) - 14.0.3022.28 (X64)
- Driver name: MS SQL Server / SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc): NO

#### Describe the problem you're observing:
I exported 1.200.000 rows dump in INSERT INTO SQL format.
I have two issues: 
- in some cases quotes are missing when DATE value is exported;
- in some cases instead of value from database 2019-02-01 in SQL dump 2019-02-31 was included.

**Comment by serge-rider** [comment]
Could you post an example of corrupted export?
And source table DDL if possible.

**Comment by sspam60** [comment]
CREATE TABLE dbo.detail (
    id_detail numeric(18,0) IDENTITY(1,1) NOT NULL,
    id_client bigint NOT NULL,
    id_branch smallint NOT NULL,
    id_seller smallint NOT NULL,
    id_com_user bigint NOT NULL,
    dealer int NULL,
    id_dealer bigint NULL,
    id_status smallint NOT NULL,
    id_com_contact bigint NULL,
    id_tech_contact bigint NULL,
    id_billingaddress bigint NOT NULL,
    id_user_invoice_suspend bigint NULL,
    invoice_suspend_date smalldatetime NULL,
    id_concurent bigint NULL,
    id_user_insert bigint NOT NULL,
    id_user_update bigint NOT NULL,
    date_insert smalldatetime NULL,
    date_update smalldatetime NULL,
    id_row uniqueidentifier(16) NULL,
    HOSTNAME varchar(50) NOT NULL,
    USERNAME varchar(50) NOT NULL,
    source_date_updated smalldatetime NULL,
    source_1 varchar(100) NULL,
    source_id_1 int NULL,
    source_version varchar(100) NULL,
)

Correct - result set exported:
﻿INSERT INTO dbo.detail (id_detail,id_client,id_branch,id_seller,id_com_user,dealer,id_dealer,id_status,id_com_contact,id_tech_contact,id_billingaddress,id_user_invoice_suspend,invoice_suspend_date,id_concurent,id_user_insert,id_user_update,date_insert,date_update,id_row,HOSTNAME,USERNAME,source_date_updated,source_1,source_id_1,source_version) VALUES (32665,619647,17,4,1,NULL,NULL,6,NULL,NULL,0,NULL,NULL,NULL,0,0,'2019-02-01 09:49:00.000','2019-02-01 09:49:00.000','99999999-9999-9999-9999-999999999999','hashed','hashed','2019-02-01 09:49:00.000','source',619647,NULL)

Wrong - cut from SQL dump:
INSERT INTO dbo.detail (id_detail,id_client,id_branch,id_seller,id_com_user,dealer,id_dealer,id_status,id_com_contact,id_tech_contact,id_billingaddress,id_user_invoice_suspend,invoice_suspend_date,id_concurent,id_user_insert,id_user_update,date_insert,date_update,id_row,HOSTNAME,USERNAME,source_date_updated,source_1,source_id_1,source_version) VALUES (32665,619647,17,4,1,NULL,NULL,6,NULL,NULL,0,NULL,NULL,NULL,0,0,'2019-02-31 00:00:00.000','2019-02-01 09:49:00.000','99999999-9999-9999-9999-999999999999','hashed','hashed','2019-02-01 09:49:00.000','source',619647,NULL)

Error message:
Msg 242, Level 16, State 3, Server ..., Line 706
The conversion of a varchar data type to a datetime data type resulted in an out-of-range value.
The statement has been terminated.

--------------------------------------------

Correct - result set exported:
﻿﻿INSERT INTO dbo.detail (id_detail,id_client,id_branch,id_seller,id_com_user,dealer,id_dealer,id_status,id_com_contact,id_tech_contact,id_billingaddress,id_user_invoice_suspend,invoice_suspend_date,id_concurent,id_user_insert,id_user_update,date_insert,date_update,id_row,HOSTNAME,USERNAME,source_date_updated,source_1,source_id_1,source_version) VALUES (5846,971159,35,4,343,NULL,NULL,6,NULL,NULL,0,NULL,NULL,NULL,0,0,'2019-02-01 09:49:00.000','2019-02-01 09:49:00.000','99999999-9999-9999-9999-999999999999','hashed','hashed','2019-02-01 09:49:00.000','source',971159,NULL)

Wrong - cut from SQL dump:
INSERT INTO dbo.detail (id_detail,id_client,id_branch,id_seller,id_com_user,dealer,id_dealer,id_status,id_com_contact,id_tech_contact,id_billingaddress,id_user_invoice_suspend,invoice_suspend_date,id_concurent,id_user_insert,id_user_update,date_insert,date_update,id_row,HOSTNAME,USERNAME,source_date_updated,source_1,source_id_1,source_version) VALUES (5846,971159,35,4,343,NULL,NULL,6,NULL,NULL,0,NULL,NULL,NULL,0,0,2019-02-01 09:49:00,'2019-02-01 09:49:00.000','99999999-9999-9999-9999-999999999999','hashed','hashed','2019-02-01 09:49:00.000','source',971159,NULL)

Error message:
Msg 102, Level 15, State 1, Server ..., Line 5846
Incorrect syntax near '09'.

**Comment by uslss** [comment]
is issue still actual on 6.2.5?

**Comment by uslss** [comment]
there is no update on ticket for a long time.
ticket closed
