### ISSUE TITLE
"Save As..." saves to UTF-8 instead of CP1251

### ISSUE THREAD

**Issue by l0rdy2k** [dbeaver/dbeaver#5196]
#### System information: 
- Windows 10 x64 Corporate
- DBeaver 5.3.4, downloaded as ZIP-archive
- Java 8 update 172 (build 1.8.0_172-b11)
- Additional extensions: none

#### Connection specification:
- Database name and version: DB2 AS400
- Driver name: DB2 iSeries/AS 400, jt400-9.7.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - NO

#### Describe the problem you're observing:
OS: Windows 10 x64 Corporate, Language and territory is Russian.
When I save SQL-script not to default place (using "File -> Save as" command) file's format changes to UTF8 without BOM. But default setting of "Text file encoding" is "Cp1251".

When I save SQL-script to default place file's format set correctly, it is Cp1251.

#### Steps to reproduce, if exist:
0). I've default setting of "Text file encoding"  is "Default (Cp1251)" (Window -> Preferences -> General -> Workspace).
1). Create a script with Russian letters, for example:
`SELECT 'ПРИВЕТ!' FROM SYSIBM.SYSDUMMY1;`
2). Choose File -> Save.
3). The script saved to default path, file's format is CP1251
4). Choose File -> Save As, then save file to any place with any name
5). The script saved, its format changed to UTF8 without BOM. The cyrillic letters now aren't readable.
6). If you press ALT+Enter, there is no tab "Resource" where you can see the fromat of file.

**Comment by serge-rider** [comment]
Thanks for the bug report
