### ISSUE TITLE
Oracle - Goto Database Object gets views when just TABLE is selected

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#5198]
Hi,
after my comment https://github.com/dbeaver/dbeaver/issues/5036#issuecomment-459650555 you added checkboxes for VIEW and MATERIALIZED VIEW. However if I select just the TABLE checkbox, the executed query is

```sql
SELECT  DISTINCT OWNER,OBJECT_NAME,OBJECT_TYPE FROM ALL_OBJECTS WHERE OBJECT_TYPE IN ('TABLE','VIEW','MATERIALIZED VIEW') AND OBJECT_NAME LIKE 'V%' 
ORDER BY OBJECT_NAME
```
![immagine](https://user-images.githubusercontent.com/2157006/52203517-aff51200-2871-11e9-815b-1e55e90b3a75.png)

Deselecting TABLE and selecting just VIEW will query for just VIEW, so it's the TABLE checkbox that is too broad.

**Comment by serge-rider** [comment]
Thanks for the bug report
