### ISSUE TITLE
Doesn't work with Eclipse Kepler

### ISSUE THREAD

**Issue by faibistes** [dbeaver/dbeaver#5207]
With Kepler, whenever I want to open a resultset in grid mode, i get org.eclipse.jface.viewers.IToolTipProvider not found. I guess that interface doesn't exist in Kepler.

**Comment by serge-rider** [comment]
Yes, we do not support Kepler because of major API change in Luna.
But perhaps we should.
Do you use some 3rd party IDE based on Kepler?

**Comment by faibistes** [comment]
No. It's just that We have to certify your software to be able to install it at our company. Eclipse Kepler is already certified. If it was compatible with Kepler, it would save us a lot of hassle.

**Comment by serge-rider** [comment]
Unfortunately we can't support Kepler anymore.
It is way too old, Eclipse API has a lot of new features and DBeaver relies on some of them.
Neon is the earliest version we are testing against.
