### ISSUE TITLE
Result Grid: Bad Timestamp values rappresentation

### ISSUE THREAD

**Issue by geuss** [dbeaver/dbeaver#5211]
Hi,
I use a custom setting for Date/Hour rappresentation in Result Grid:

Format: yyyy-MM-dd HH:mm:ss.ff6

![image](https://user-images.githubusercontent.com/26387091/52276842-86141c00-2953-11e9-9222-ee6ffa8e08cf.png)

But, when I select a field with data type: TIMESTAMP(6) (I tryed with Teradata and Oracle DBMS), the result value is wrong. There's a ".006" decimal value that doesn't match the value in the field:

![image](https://user-images.githubusercontent.com/26387091/52276818-77c60000-2953-11e9-81b9-10f0b79f18a6.png)

Es: 
I inserted in the field table the value: 2019-01-01 00:00:00.000000 (as the custome format that I choosed) and the value returned by the select is: 2019-01-01 00:00:00.006

Why?

Thanks!!
geuss

**Comment by Neospiro** [comment]
Hello

![image](https://user-images.githubusercontent.com/4870502/52282073-c4afd380-295f-11e9-9ad8-e540c90088dd.png)

Here is a date field select on an Oracle database, failing to show the right value.

Windows 7 SP1
Dbeaver portable 64bit v 5.3.4.201902031804

**Comment by serge-rider** [comment]
@geuss Well, format `yyyy-MM-dd HH:mm:ss.ff6` will show two first digits of milliseconds + digit `6`. 
If you want to show micro/nano seconds use format `yyyy-MM-dd HH:mm:ss.ffffff`

@Neospiro This looks like a bug in date formatting when converting timezones. What data type column mydate has?

**Comment by Neospiro** [comment]
The Oracle column datatype is Date

**Comment by serge-rider** [comment]
- Can you post table DDL with INSERT to reproduce this issue?
- How result of "SELECT CURRENT_DATE FROM DUAL" looks like?

**Comment by geuss** [comment]
> @geuss Well, format `yyyy-MM-dd HH:mm:ss.ff6` will show two first digits of milliseconds + digit `6`.
> If you want to show micro/nano seconds use format `yyyy-MM-dd HH:mm:ss.ffffff`
> 
> @Neospiro This looks like a bug in date formatting when converting timezones. What data type column mydate has?

Thanks Serge. With mask yyyy-MM-dd HH:mm:ss.**ffffff** I see data correctly. But, I suppose that there's another problem....

Look this:

create volatile table MYOWN
(
	date0 date,
	date1 timestamp(0),
	date2 timestamp(3),
	date3 timestamp(6)
) on commit preserve rows;

insert into MYOWN(current_date,current_timestamp(0),current_timestamp(3),current_timestamp(6));

If I set the checkbox "Use native date/time format" with these settings....
![image](https://user-images.githubusercontent.com/26387091/52713764-740c2c00-2f98-11e9-9910-196f94e3a957.png)

...I see:
![image](https://user-images.githubusercontent.com/26387091/52713840-addd3280-2f98-11e9-9543-2bce7ce4bfeb.png)

Instead, if I uncheck  "Use native date/time format" the output is:

![image](https://user-images.githubusercontent.com/26387091/52713916-e0872b00-2f98-11e9-93ba-760b1286b5ca.png)

Now... I guess that with "Use native date/time format" setting checked, I should view date fields with their data type approssimation...

example:
date1 (timestamp(0)):  2019-02-13 14:01:00
date2 (timestamp(3)):  2019-02-13 14:01:00,123
date3 (timestamp(6)):  2019-02-13 14:01:00,123456

What do you think about?

Thanks!
geuss

**Comment by Neospiro** [comment]
hi
Sorry for the delay, there is no problem with current_date, as shown here


```SQL
  CREATE TABLE "AAA_TEST" 
   (	"MYDATE" DATE NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

SELECT 
	mydate, 
	to_char(mydate, 'DD/MM/YYYY'),
	current_date,
	dump(mydate),
	dump(current_date),
	dbtimezone,
	systimestamp,
	sysdate
FROM aaa_test	
;
```

![image](https://user-images.githubusercontent.com/4870502/60087255-f245bf80-973c-11e9-87bc-833514726dd1.png)

**Comment by uslss** [comment]
cannot reproduce on 6.2.5.
Is issue still actual?

**Comment by uslss** [comment]
there are no updates for a month. ticket closed
