### ISSUE TITLE
DBeaver: Function Open Database Object don't search for all table names

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5212]
DBeaver - **Version 5.3.4 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

This is a misbehaviour in the **New MS SQL Driver**. It workes if I use the **Old MS SQL Driver**.

If I search for tables using the _DBeaver_ **Open Database Object** _(Ctrl+Shift+D)_ it does not help me locating all tables in our database.

Number of tables in database **dbo** schema: **219**.
Number of procedures in database **dbo** schema: **135**.

Tables located: **1...136**
Tables not located: **137..167**
Tables located: **168..219**

If I uncheck the **SQL Stored Procedure** checkbox, **I can locate all our tables**.

Seems almost like _DBeaver_ reads 200 database objects in the first batch, and then when it reads the second batch it skips 30 tables. Ought to be something visible if comparing how the new and the old driver handle it since the old driver succeed.

**PS**. The _Dbeaver_ version 5.3.3 misbehaves too.

**Comment by serge-rider** [comment]
Thanks for the bug report. It was really old one )

**Comment by pdanie** [comment]
If you can generate a new EA, then I will do my best to test it again.
