### ISSUE TITLE
DBeaver: The SQL Execution Log is not fully cleared when asked to clear

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5213]
DBeaver - **Version 5.3.4 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

The _DBeaver_ **SQL Execution Log** is not fully cleared when asked to clear.

**o** Start _DBeaver_ and open a **SQL Editor**.
**o** Execute a few SQL commands.
**o** Click on the **Show Execution Log** button (in the lower left corner of the SQL window).
**o** In the list of executed SQL commands, right click and choose **Clear Log**.
**o** The grid is cleared. This is **OK**.
**o** Right click again in the **Execution Log** grid and choose **Refresh**.
**o** All the old log rows are restored. This is **CONFUSING**.

Should not the execution logs keep cleared even if I later choose to refresh ?

**Comment by serge-rider** [comment]
This is a bit controversial. For instance in EE we keep all SQL history in embedded database. And this history can't be cleared (at least easily by clicking "clear" button).

Need to think about this a bit more..

**Comment by pdanie** [comment]
Maybe one to solve it is to remove the "clear" button. The thing that got me confused was that I could choose to "clear" the execution log, and later all the log information popped up again.

**Comment by serge-rider** [comment]
Well, I use "clear" button all the time (when I catching some particular query during script execution for example). It could be renamed to "Clear log view" or something.

**Comment by aranapatona** [comment]
> Well, I use "clear" button all the time (when I catching some particular query during script execution for example). It could be renamed to "Clear log view" or something.

Yes , Clear Log View and probably a checkbox for "Clear Log entries also"

**Comment by lucasdev29** [comment]
I found a `.log` file in `C:\Users\<username>\AppData\Roaming\DBeaverData\workspace6\.metadata`. After closing DBeaver and deleting the file, the execution log was cleared when I restarted DBeaver.
