### ISSUE TITLE
Add path variables

### ISSUE THREAD

**Issue by glarkou** [dbeaver/dbeaver#5216]
Is it possible to add variables for paths? 

I opened a help request at https://stackoverflow.com/questions/54538814/ability-to-add-paths-as-variables

Thanks for your support

**Comment by serge-rider** [comment]
You can enable environment variables use in settings:
![image](https://user-images.githubusercontent.com/6398845/52302553-9dc4c200-299e-11e9-8d48-91a4b9237469.png)
