### ISSUE TITLE
Error while trying to open "Synonyms" tab

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#5218]
#### System information: 
- win 10 x64
- DBeaver version 5.3.5 

#### Connection specification:
- Sybase

#### Describe the problem you're observing:
Error appears while trying to open "Synonyms"
![image](https://user-images.githubusercontent.com/31996417/52304301-7fad9080-29a3-11e9-8652-789b2b2e12e9.png)

[log.txt](https://github.com/dbeaver/dbeaver/files/2833882/log.txt)

**Comment by serge-rider** [comment]
Sybase doesn't support synonyms. We need to remove this folder from navigator.
