### ISSUE TITLE
Strings or Text not colored green anymore?

### ISSUE THREAD

**Issue by reichg** [dbeaver/dbeaver#5219]
#### System information: 
- Windows 10
- DBeaver Version: 5.3.4
- Java Version: 1.8.0_191 

#### Connection specification:
- PostgreSQL Connection

#### Describe the problem you're observing:
- It looks like "text" or "string" types are no longer colored green like they were before?

#### Steps to reproduce, if exist:
- Anything contained in single quotes ('like this')

#### Include any warning/errors/backtraces from the logs
- No errors
![dbeaver_font_issue](https://user-images.githubusercontent.com/18335251/52306479-f9fef600-294c-11e9-9efd-c29d121fdfa9.PNG)

**Comment by reichg** [comment]
I have no clue how it changed, maybe from the update but I found how to edit the colors. Issue closed.

**Comment by serge-rider** [comment]
I think it was fixed in #5191

**Comment by reichg** [comment]
You are correct, I reset it to default and it is fixed, not sure why it changed though. Sorry for the repeat question, I didn't find #5191 when I was searching for this issue. Thank you for your help and for DBeaver!
