### ISSUE TITLE
PostgreSQL Ctrl+Enter execution error

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#5222]
Hello.
Windows 7 x64
DBeaver 5.3.4
Java 1.8.0_201
PostgreSQL 9.5.3
PostgreSQL driver 9.4.1212

Query:
WITH tmp_data AS
	(SELECT 1 AS r, 'text1' AS t
	UNION ALL
	SELECT 1 AS r, 'text2' AS t)
SELECT r, string_agg(t,'; ')
FROM tmp_data
GROUP BY r

If i stay at the end of row "SELECT r, string_agg(t,'; ')" and press Ctrl+Enter i recive error:
SQL Error: Internal jdbc driver error
java.lang.ArrayIndexOutOfBoundsException

At any other position query executes correctly

**Comment by serge-rider** [comment]
Thanks for the bug report (it was a bug in SQL parser)
