### ISSUE TITLE
Value dictionary not clickable / copyable

### ISSUE THREAD

**Issue by Cyberuben** [dbeaver/dbeaver#5225]
#### System information: 
- Operating system (distribution) and version: **Windows 10 - 10.0.17134 Build 17134**
- DBeaver version: **5.3.4**
- Java version: **version 8 update 181**
- Additional extensions: **none**

#### Connection specification:
- Database name and version: **PostgreSQL 11** (also happens on PostgreSQL 9.6)
- Driver name: **PostgreSQL JDBC Driver**
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: **No**

#### Describe the problem you're observing:

The Value panel shows dictionary values, but does not allow me to click any of the rows. Some columns (don't know which, only happened for the first time now) show the editor in the following format:
![image](https://user-images.githubusercontent.com/1823121/52354256-63a40080-2a30-11e9-94a8-4550a6765872.png)

Other columns show like this: 
![image](https://user-images.githubusercontent.com/1823121/52354328-7f0f0b80-2a30-11e9-8da2-65d6fb58c0b7.png)

In the first case, I'm able to actually assign values by clicking them, in the second case, I'm not able to click, copy or edit anything in the dictionary. Manually entering a value works though.

In all cases, the dictionary refers to another table with proper foreign keys. All columns are UUID but I don't know if this is relevant, as I haven't tested it with other column types.

#### Steps to reproduce, if exist:

Not sure

#### Include any warning/errors/backtraces from the logs

There don't seem to be any warnings or errors

**Comment by riednyko** [comment]
Can`t reproduce this. Please post DDL text.

**Comment by Cyberuben** [comment]
I'm sorry for the late response. I received an email about your response and I wanted to supply the DDL but at that moment I saw everything worked fine. Now, however, I can't get it to work anymore and it happens randomly again.

I'll see if I can reproduce it in a smaller database.

**Comment by frahugo** [comment]
Same problem, but on Mac OS X. Version 5.3.5. PostgreSQL 10.4.

I have a table with two foreign keys. Assigning the guid for the first key works, not for the second one. Earlier today, I was not able to assign the first key.

![image](https://user-images.githubusercontent.com/14030/54062224-ca087400-41d2-11e9-9263-11598f4212a1.png)

![image](https://user-images.githubusercontent.com/14030/54062236-dab8ea00-41d2-11e9-8bc7-d5de8005fec2.png)

**Comment by serge-rider** [comment]
Weird. IS there anything in log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)
Especially debug log.

**Comment by serge-rider** [comment]
BTW I'll add context menu with "Copy" action to the dictionary browser. This can be used as a workaround. 
However we need to figure out what is wrong with it and fix the original bug.

**Comment by frahugo** [comment]
@serge-rider Nothing in the debug log, nor the .log file. Is there a debug level that can be set somewhere in the preferences?

**Comment by serge-rider** [comment]
Eventually I've been able to reproduce this issue (or big part of it).
Thanks for details.

**Comment by uslss** [comment]
verified
