### ISSUE TITLE
Compile log window does not work, and package lines with errors not highlighted

### ISSUE THREAD

**Issue by yevon** [dbeaver/dbeaver#5227]
#### System information: 
- Operating system (distribution) and version: Windows 10 October update
- DBeaver version: Latest, 5.3.4
- Java version: Built in with 5.3.4 
- Additional extensions

#### Connection specification:
- Database name and version: Oracle 12c 12.2.1
- Driver name:
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
- Compile or perist package does not show compile errors on compile log window, and doesn't highlight lines wit errors as you can see in image, this problem has been reported and marked as resolved but keeps happening.

When you perform a right click on the package and press compile, the log window just shows the sql command to compile the package, not very useful indeed, with line and pos columns empty. The package errors are shown in a pop up window, and there isn't any code or line highlighting of those errors in the package, and they don't appear in de compile log window. 

This pop up shouldn't be shown, and show those errors in the compile log window with line and pos columns filled, and error highlighting implemented in the package. When you click the error in the compile log window, it should place the cursor in the line with error in the package.

#### Steps to reproduce, if exist:

![image](https://user-images.githubusercontent.com/121157/52398485-7f9fb480-2ab9-11e9-8467-d425b8a53758.png)

Compare it with standard sqldeveloper behaviour, much simpler. You just press CTRL + S and it compiles and saves the package without any pop-up window to persist the change, and automatically you see errors in the compile log window.

![image](https://user-images.githubusercontent.com/121157/52398837-b88c5900-2aba-11e9-9ed8-800406540fb9.png)

Thanks for your work! Dbeaver is very nice, but this still keeps me away from using it for oracle databases.

**Comment by serge-rider** [comment]
Compile, package save and error positioner were fixed
