### ISSUE TITLE
Intelligent brackets close

### ISSUE THREAD

**Issue by shungabubus** [dbeaver/dbeaver#5232]
Dear All,

I love the function of auto close brackets but sometimes I am lazy to type so I rather paste my value first and in this case I end up like this:
![image](https://user-images.githubusercontent.com/36946814/52415833-68c48680-2ae8-11e9-8b9f-4939d9eeccd1.png)
As a reflex I try to delete the closing bracket, but unless I move away it deletes both. First time I ended up adding deleting adding deleting which felt upsetting.
I think it should not be too difficult to check when to insert if there is a text (anything but space) at the cursor do the closing after the text. Or worst case just don't close it like ' already does. Actually, is it possible to request an intelligent closure (maybe optional in preferences) option for ALL of these?

Many thanks:
Tamas

Ps: I tried to look, I have seen some similar stuff but they were not like this, and disabling the function doesn't feel right either, so sorry if by chance it is a duplicate to an open ticket. It is hard to believe, that no one experienced this before and fixed it already...

**Comment by p91paul** [comment]
@mdahlman "Extract sql from source code" is your checkbox :)

![immagine](https://user-images.githubusercontent.com/2157006/52450369-f92bb700-2b3a-11e9-8391-e7d8c6cdd8af.png)

**Comment by shungabubus** [comment]
Hey, thanks for the try but 1. it is already ticked, 2. what it is meant to do? I feel no difference...

**Comment by mdahlman** [comment]
@p91paul , thanks!
@shungabubus , sorry for hijacking your thread!

Yes: the question dealing with the parentheses better is the real one here.

**Comment by shungabubus** [comment]
@mdahlman actually I am glad your issue is solved, but I am afraid no one will pick this up now. :(

**Comment by serge-rider** [comment]
@shungabubus I will :)
I agree, current behavior with brackets auto close annoys me too. Intellectual closure is too complicated. But I like the simple fix is - do not close bracket if there is anything but space to the right from cursor.

**Comment by shungabubus** [comment]
Hey, many thanks. Any chance to participate in the beta-testing?

**Comment by serge-rider** [comment]
Yep, Early Access version is here: https://dbeaver.io/files/ea
