### ISSUE TITLE
CockroachDB - Cannot load some table information

### ISSUE THREAD

**Issue by malexdev** [dbeaver/dbeaver#5235]
#### System information: 
- Operating system (distribution) and version: Windows 7 Professional x64, MacOS 10.14.2.
- DBeaver version: 5.3.3
- Java version: 1.8.0_201 x86_64
- Additional extensions: None

#### Connection specification:
- Database name and version: CockroachDB v2.1.4
- Driver name: CockroachDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No
#### Describe the problem you're observing:

I am unable to view some of the table data in DBeaver when opening the "Properties" pane for the table.
Specifically, the table I am using to test is as follows:

```
root@:26257/defaultdb> show columns from test_data;
  column_name | data_type | is_nullable |  column_default   | generation_expression |   indices   | is_hidden
+-------------+-----------+-------------+-------------------+-----------------------+-------------+-----------+
  id          | UUID      |    false    | gen_random_uuid() |                       | {"primary"} |   false
  first_name  | STRING    |    false    | NULL              |                       | {}          |   false
  last_name   | STRING    |    false    | NULL              |                       | {}          |   false
```

* The `Indexes` pane shows the error `unknown function: pg_catalog.pg_relation_size()`. There is an index on the table:
```
root@:26257/defaultdb> show indexes from test_data;
  table_name | index_name | non_unique | seq_in_index | column_name | direction | storing | implicit
+------------+------------+------------+--------------+-------------+-----------+---------+----------+
  test_data  | primary    |   false    |            1 | id          | ASC       |  false  |  false
```
* The `Permissions` pane does not display current permissions, even though grants have been assigned:
```
root@:26257/defaultdb> show grants on table test_data;
  database_name | schema_name | table_name | grantee   | privilege_type
+---------------+-------------+------------+-----------+----------------+
  defaultdb     | public      | test_data  | admin     | ALL
  defaultdb     | public      | test_data  | root      | ALL
  defaultdb     | public      | test_data  | testadmin | ALL
```
* The `DDL` panel does not display current permissions either.

#### Steps to reproduce, if exist:

1. Set up a CRDB server and create a table.
1. View the table properties in DBeaver.
1. Note that the same error messages appear.

#### Include any warning/errors/backtraces from the logs
Logs aren't included because the error reasons are obvious (the functions don't exist in CRDB).

------

I am evaluating DBeaver for use for my development group and hoping to get them to use it for CRDB, but editing and viewing all table information that CRDB supports is a requirement.

My understanding was that there is now a custom module for CRDB in DBeaver, so using CRDB specific calls instead of their Postgres equivalent functions should not be an issue. Are there plans to support the remaining properties I reference in this issue, or do we need to try to patch support in somehow?

Thanks for your time.

**Comment by serge-rider** [comment]
Also rule list reading isn't working (as it is not supported by CRDB).

Thanks for the bug report. See fixes in the next version.

**Comment by malexdev** [comment]
Wow, so fast. Thanks very much!
