### ISSUE TITLE
dbeaver EE 4.0.5 cassandra ssl on macos 

### ISSUE THREAD

**Issue by nazeemmohammed** [dbeaver/dbeaver#5237]
On MacOS, I have installed DBeaver 4.0.5 and able to connnect to cassandra normally. I want to connect to the db using SSL, I see only a checkbox, but there is nowhere to specify the cert/keystore. Going through this issue (https://github.com/dbeaver/dbeaver/issues/317), looks like for this version of dbeaver the workaround is to add entries in dbeaver.ini, but on macos install I am unable to find this file. Where would I find this file, how do I add truststore location in this version to make ssl connections.

On 5.3 version, there is a place to specify these details and I am able to make connections successfully via ssl.

**Comment by serge-rider** [comment]
So, this issue was solved in 5.x?
dbeaver.ini is in `/Appications/DBeaverEE.app/Contents/Eclipse/`

**Comment by nazeemmohammed** [comment]
in 5.x versions there is a tab under Network options where one can specify SSL connection options.

**Comment by pedrofavari** [comment]
Where do you found dbeaver 4.0.5 ee for mac?

**Comment by pedfav** [comment]
Where can i find dbeaver  4.0.5 EE for download?
