### ISSUE TITLE
DBeaver on elementary OS 5.0 Juno

### ISSUE THREAD

**Issue by rafaelmartines** [dbeaver/dbeaver#5239]
Some updates ago, DBeaver started to somehow "duplicating the windows borders" on elementaryOS
![image](https://user-images.githubusercontent.com/8183691/52477284-7d585b80-2b88-11e9-9c93-8ec8e38cfe04.png)
![image](https://user-images.githubusercontent.com/8183691/52477311-8ea16800-2b88-11e9-8d51-fe14b86f4442.png)

- Operating system: elementary OS 5.0 Juno (build over Ubuntu 18.04 LTS)
- Window manager (for Linux): Gala

**Comment by wout** [comment]
This is a more general issue in elementaryOS. Not really DBeaver related.

**Comment by cassunde** [comment]
Hi @rafaelmartines see this [Solution](https://github.com/dbeaver/dbeaver/issues/3980#issuecomment-412480884) i just added this parameters in `dbeaver.ini`
```
--launcher.GTK_version
2
```

**Comment by marcosfreitas** [comment]
Same problem here, same OS version, but this line into dbeaver.ini doesn't make effects.

**Comment by jimuelpalaca** [comment]
same issue, but I also found this [solution](https://github.com/dbeaver/dbeaver/issues/3980#issuecomment-412480884) and configure the _dbeaver.desktop_:

`cd  /usr/share/applications`
`sudo vim dbeaver.desktop`

Then, update the **Exec** line:
`Exec=/usr/share/dbeaver/dbeaver --launcher.GTK_version 2`

**Comment by jimuelpalaca** [comment]
This [workaround](https://github.com/dbeaver/dbeaver/issues/3980#issuecomment-477083140) works on me.


Dbeaver version: 6.0.1

**Comment by magallz1** [comment]
There is another way to fix this.
`cd /usr/share/applications`
`sudo vim dbeaver.desktop`

Edit the **Exec** line to the following:
`Exec=env GTK_CSD=0 /usr/share/dbeaver/dbeaver`

Still using GTK3 and no funky window framing.

Reference: https://elementaryos.stackexchange.com/questions/16833/how-to-fix-bug-in-the-windows-of-elementary-os

**Comment by SaitDev** [comment]
Tried env GTK_CSD=0, doesnt fully fix graphic issues with elementary gtk3
How is it should look like https://prnt.sc/nau8gg
But when focus on dbeaver window https://prnt.sc/nau8l1
Add. note: seem like eclipse 2019.04 will have the fix on elementary https://github.com/elementary/gala/issues/244#issuecomment-471462701

**Comment by Marcos-Costa** [comment]
> There is another way to fix this.
> `cd /usr/share/applications`
> `sudo vim dbeaver.desktop`
> 
> Edit the **Exec** line to the following:
> `Exec=env GTK_CSD=0 /usr/share/dbeaver/dbeaver`
> 
> Still using GTK3 and no funky window framing.
> 
> Reference: https://elementaryos.stackexchange.com/questions/16833/how-to-fix-bug-in-the-windows-of-elementary-os

This one solved for me.

**Comment by jrichardsz** [comment]
Thanks @magallz1 (Mike Gallenstein), your fix worked for me on dbeaver 6.0.2 2019 version!!
