### ISSUE TITLE
[Bug] After Connection timeout  dbeaver freezes

### ISSUE THREAD

**Issue by ceyhunn** [dbeaver/dbeaver#5240]
#### System information: 
- Operating system (distribution) and version - Archlinux
- DBeaver version - 5.3.2
- Java version - 11.0.2
- Additional extensions - excel

#### Connection specification:
- Database name and version - oracle 12c
- Driver name - oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
After connection timeout if I persist changes (Observed mostly in editing package functions)  dbeaver freezes. Dbeaver doesn't show message directly that connection is closed, reconnect.  For this, I restart dbeaver, then work from beginning. My changes are lost. After 1 or 2 hours, dbeaver tell me connection is closed.  It is annoying. For getting rid of this bug, I extended my connection timeout duration, but this is not correct way.
#### Steps to reproduce, if exist:
1. Wait for  connection is closed.
2. Edit in package function
3. Then persist changes.

**Comment by uslss** [comment]
can't reproduce it against the recent version.
The ticket will be closed. if the issue is still actual for you - feel free to reopen the ticket
