### ISSUE TITLE
JSON Auto-Format doesn't display null values... 

### ISSUE THREAD

**Issue by nghtstr** [dbeaver/dbeaver#5241]
#### System information: 
- Operating system: Mac OS 10.14.4 beta 2
- DBeaver version: 5.3.3 EE
- Java version: 1.8.0_25
- Additional extensions: none

#### Connection specification:
- Database name and version: Postgres 9.6.9
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
The auto-formatter version of a JSON field doesn't display any entities that are set to NULL
<img width="805" alt="screen shot 2019-02-08 at 12 43 46 pm" src="https://user-images.githubusercontent.com/51501/52502164-4b9ebf00-2b9f-11e9-9669-5fe728b0321d.png">

#### Steps to reproduce, if exist:
Create a table that has a JSONB column.
INSERT a row, including the following text for the JSON: `{"id": 123, "title": "Test", "bogus": null}`
SAVE the row
Refresh the table by pressing F5
Look at the data in the table and in the Value Panel (with the setting to JSON and Auto-Format set to true)

**Comment by serge-rider** [comment]
Thanks for the bug report. 
See fix in the next version (you also can test the fix in Early Access version at https://dbeaver.com/files/ea)
