### ISSUE TITLE
Query Manager - save logs to files - no file is created

### ISSUE THREAD

**Issue by Retko** [dbeaver/dbeaver#5243]
Hello,

I am not sure, how "Save logs to a file" functionality works. Should it create log file after Query is run?
Because it doesn't create a file for me. 

![image](https://user-images.githubusercontent.com/37830487/52521296-5f1c5980-2c75-11e9-82cd-b62adbeebb86.png)

So how do I get logs to a file?

Thank you.

**Comment by serge-rider** [comment]
You need to restart DBeaver for these changes to take effect.
I'll add info about that on prefs page.
