### ISSUE TITLE
Font Settings

### ISSUE THREAD

**Issue by Tzott** [dbeaver/dbeaver#5246]
Font settings don't work in SQL editors.

**Comment by Tzott** [comment]
Windows Community Edition 5.3.4

**Comment by serge-rider** [comment]
They work actually. But there is no such option as SQL Editor font. There is Text editor font option instead:
![image](https://user-images.githubusercontent.com/6398845/52670887-c6166880-2f2a-11e9-8721-4be7672d0e4a.png)

**Comment by Tzott** [comment]
Thank you
