### ISSUE TITLE
Improving import Boolean-Data from CSV 

### ISSUE THREAD

**Issue by BK-Rob** [dbeaver/dbeaver#5248]
I try to perform a data import from a csv file into an existing H2-table.
Unfortunately, columns with type boolean cannot imported correctly, if the value is 1 (=true) or 0 (=false).

Dbeaver-Version: 5.3.4

**Comment by mkgrgis** [comment]
It's common problem of import and DB design, not only in dbeaver. For example https://github.com/ibarwick/firebird_fdw/issues/9
In the CSV you can not declare type of data, your DB must allow {0|1} as boolean. Dbaever can't help, but it's DB's rules.
