### ISSUE TITLE
Format XML when opening CLOB/BLOB/XMLTYPE

### ISSUE THREAD

**Issue by Zbambus** [dbeaver/dbeaver#5250]
I have not found this commented earlier but the functionality may be present and I'm bad at figuring out how to activate it.

When hitting Shift+Enter on a cell of type BLOB/CLOB/XMLTYPE, the content is opened in an editor with Binary/Text/(XML) tabulators.

For the Text/XML tabulators it would be very nice to have access to a "beautify/format" function if the content is an XML as they often are stored with no whitespace and/or linebreaks.

**Comment by serge-rider** [comment]
Good point

**Comment by serge-rider** [comment]
But we won't auto-format XML/JSON by default. 
But I'll add standard Format command (CTRL+Shift+F) handler. It will format contents on request.
