### ISSUE TITLE
Save functions in Grouping Panel.

### ISSUE THREAD

**Issue by michaelmiscanuk** [dbeaver/dbeaver#5253]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by Retko** [comment]
Hello,
is there a way to save a function in Grouping Panel. So when I close DBeaver it stays?

Thanks

**Comment by uslss** [comment]
duplicates #4332
