### ISSUE TITLE
Missing Charts Button

### ISSUE THREAD

**Issue by Retko** [dbeaver/dbeaver#5254]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by Retko** [comment]
Hi,
on wiki I found that DBeaver can do some charts - https://github.com/dbeaver/dbeaver/wiki/Managing-Charts
But I miss this button on my side :(

![image](https://user-images.githubusercontent.com/37830487/52596088-be35c600-2e4f-11e9-80f1-774782ea88d2.png)

Can you please explain why? Is it for EE edition only?

Thank you

**Comment by p91paul** [comment]
This page https://github.com/dbeaver/dbeaver/wiki/Enterprise-Edition says "Analytical charts" are a feature of the EE version, so I suppose the answer's yes. However I believe it should be made explicit in the Managing Chart page (like in the Visual Query Builder's page)... when the feature first came out a few releases ago, I quickly downloaded the new version and found nothing :disappointed: so I understand how you're feeling :sweat_smile:

**Comment by serge-rider** [comment]
Yes, it is one of a few EE features.

I've added a note to wiki page https://github.com/dbeaver/dbeaver/wiki/Managing-Charts
