### ISSUE TITLE
Reference to database and/or server name in 'KIOSK.sys.schemas' is not supported in this version of SQL Server

### ISSUE THREAD

**Issue by krkhnh** [dbeaver/dbeaver#5258]
#### System information: 
- Operating system (distribution) and version
Windows 10 1803

- DBeaver version
5.3.4.201902031804

- Java version 
OpenJDK 11.0.2

- Additional extensions
None

#### Connection specification:
- Database name and version
SQL Server(Azure) 12.0.2000.8

- Driver name
Azure SQL Server
![image](https://user-images.githubusercontent.com/5172480/52606539-5070b500-2eb6-11e9-995c-50b4f88e913a.png)

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
None

#### Describe the problem you're observing:
After I connect to a SQL Azure, I can't open 'Schemas' folder.

#### Steps to reproduce, if exist:
1. Add a new connection to SQL Azure and connect to it.
2. Open any DB but 'master'.
3. Try to open 'Schemas' folder. Following error messages occur.
```
SQL Error [40515] [S0001]: Reference to database and/or server name in 'KIOSK.sys.schemas' is not supported in this version of SQL Server.
  Reference to database and/or server name in 'KIOSK.sys.schemas' is not supported in this version of SQL Server.
```

#### Include any warning/errors/backtraces from the logs
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/2853814/dbeaver-debug.log)

**Comment by FernandoTBarros** [comment]
I'm having the same Issue. Why this is happening?

**Comment by runemoennike** [comment]
As a workaround, you can put the name of the database you want to connect to in the database connection settings (the field "Database/Schema" just under "Host".) Apparently Azure SQL doesn't allow database switching on an active connection.

**Comment by krkhnh** [comment]
> As a workaround, you can put the name of the database you want to connect to in the database connection settings (the field "Database/Schema" just under "Host".) Apparently Azure SQL doesn't allow database switching on an active connection.

Thanks to @runemoennike, [I found an official document about this(link).](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/use-transact-sql?view=sql-server-2017) It says that Azure doesn't support `USE` statement.

> In Azure SQL Database, the database parameter can only refer to the current database. If a database other than the current database is provided, the USE statement does not switch between databases, and error code 40508 is returned. To change databases, you must directly connect to the database. The USE statement is marked as not applicable to SQL Database at the top of this page, because even though you can have the USE statement in a batch, it doesn't do anything.

Even so, I hope DBeaver notify this info from the application or at least has a document about this.

**Comment by emparker** [comment]
FYI, I have been also using Jetbrain Datagrip and it has the same issue. But it was all working fine a couple of months ago. I think it might be something changed on Azure SQL.

**Comment by 25308985** [comment]
> As a workaround, you can put the name of the database you want to connect to in the database connection settings (the field "Database/Schema" just under "Host".) Apparently, Azure SQL doesn't allow database switching on an active connection.

So workaround which I got is out of "Master" or your personal database Schema like "AzureDB" you can only set 1 at a time in DBeaver. I have set "AzureDB" in DataBase/Schema option it is working now.

**Comment by runemoennike** [comment]
@uslss can we get a comment on why this was closed? Has it been fixed? :)

**Comment by RobKraft** [comment]
I find that specifying the database does not work for the {SQL Server} driver, but does work for the {ODBC Driver 17 for SQL Server} driver.  I am connecting from Microsoft Access.

**Comment by TheEnglishSpy** [comment]
> As a workaround, you can put the name of the database you want to connect to in the database connection settings (the field "Database/Schema" just under "Host".) Apparently Azure SQL doesn't allow database switching on an active connection.

Thanks! Simple and effective work around :-) ... still would be nice if you could switch during an active connection. Any updates on this? Cheers to all!

**Comment by LonwoLonwo** [comment]
Is this issue reproducible against in DBeaver 21.3 version?

**Comment by amurphy-tpc** [comment]
@LonwoLonwo This still happens in Version 22.0.3.202204170718. The workaround does work for me.

**Comment by LonwoLonwo** [comment]
Ok @amurphy-tpc 

Let's try to figure out your problem.

You can't open the schemas list in a non-default database? Like on the screen?

![2022-04-20 09_35_23-DBeaver Ultimate 22 0 3 - _MySQL 8 0_Script-150](https://user-images.githubusercontent.com/45152336/164166394-bba27112-1146-4627-bc6e-90f09e2e6b33.png)

As I can see on the Internet: "Cross-database queries aren't supported in SQL Azure."

In this case, you can create connections for other databases which you have. You can specify the database name in the connection settings:

![2022-04-20 09_37_38-DBeaver Ultimate 22 0 3 - _MySQL 8 0_Script-150](https://user-images.githubusercontent.com/45152336/164166734-761249a7-65a4-46bf-b313-8a0cf7b899e8.png)

**Comment by amurphy-tpc** [comment]
That is correct. The real issue is that I have at least 22 databases on one dev server. It is not ideal to have to create so many connections. Other DB IDEs don't seem to have this problem, but I prefer to use DBeaver.

> As I can see on the Internet: "Cross-database queries aren't supported in SQL Azure."

To be clear, I don't need to run queries cross-database, just connect, view, and edit tables.

**Comment by LonwoLonwo** [comment]
Ok.

**Comment by LonwoLonwo** [comment]
At first step we can remove non default databases (with option in Connection settings), as we did it to PostgreSQL, Oracle and Netezza.

**Comment by ClassyCircuit** [comment]
When is this bug going to be fixed? It's been 4 years now. Why other IDEs don't have such an issue?
It's not about running cross-database queries, but simply switching between several databases on the same Azure server.

**Comment by LonwoLonwo** [comment]
> but simply switching between several databases on the same Azure server

And how can we do this without the USE statement? Do you know the solution @janissimsons?

**Comment by LonwoLonwo** [comment]
Hi everyone.
Options to use the ability to see all databases of connection implemented in this ticket and will be available in the next release, 22.1.4
By default, only specified in the connections setting database will be shown in the Database navigator tree.

![2022-08-01 18_45_49-DBeaver  C__Users_anvolka_work_DbeaverP_dbeaver-workspace-idea  - C__Users_anvol](https://user-images.githubusercontent.com/45152336/182202867-67b5b856-d996-43c8-bfe2-ce4d52141655.png)

And we created another ticket to solve the main issue of this ticket: https://github.com/dbeaver/dbeaver/issues/17263

**Comment by y2jhotaru** [comment]
I have DBeaver 23.0.2 and this issue is still around. Is there any plan to fix it? Thanks. (BTW, I've used the workaround, but I have many databases, and creating a connection for each one is too difficult to maintain)

**Comment by E1izabeth** [comment]
@y2jhotaru did you created connection using host and port configuration or by url?

**Comment by y2jhotaru** [comment]
> 

I used url as I'm connecting to a native Azure Instance. With managed instance or on premise SQL, I have no problem.

**Comment by E1izabeth** [comment]
Multi-database support does not work for URL-configured connections since 23.0.0.
An issue about making this works here #19241

So please just use host and port for connection configuration

**Comment by Sheheryarbaig** [comment]
To resolve this issue, simple change the name of Database?Schema field in Edit Connection from master, i renamed from master to i.e mars_db which i have under master->Databases->.
Alter the name and then use it. 
![image](https://github.com/dbeaver/dbeaver/assets/126067022/5f805947-86c2-4d04-ba2c-d14efe264308)

**Comment by scheepje** [comment]
> As a workaround, you can put the name of the database you want to connect to in the database connection settings (the field "Database/Schema" just under "Host".) Apparently Azure SQL doesn't allow database switching on an active connection.

Worked for me, thank you!

**Comment by salesrocketdev** [comment]
> As a workaround, you can put the name of the database you want to connect to in the database connection settings (the field "Database/Schema" just under "Host".) Apparently Azure SQL doesn't allow database switching on an active connection.

Man, you saved me!
Thank you!

**Comment by Masterxilo** [comment]
Thanks for all the good answers (descriptions of the workaround) here. However, I still think DBeaver should tolerate this error better and behave somewhat like Azure Data Studio or SQL Server Management Studio which can be made to point to the whole server just fine and show all databases (that we have access to) instead of totally failing when no specific database is selected.

I vote to reopen this issue.
