### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by carlosherranz** [dbeaver/dbeaver#5260]
Query Manager and Database Navigator icons doesn't appear at start DBeaver. Instead two red icons appear.
You can see that in the attach file, pointed with green arrows
![2019_02_12_08_24_58_clipboard](https://user-images.githubusercontent.com/28946478/52619591-565c9b00-2ea2-11e9-899f-62d997c321a5.jpg)

**Comment by serge-rider** [comment]
Duplicate of #4133. In some cases clicking on view icon (red square) solves the problem. In other cases cache reset will help (see comments in 4133)
