### ISSUE TITLE
DB2 and columns with format CHAR () FOR BIT DATA

### ISSUE THREAD

**Issue by Svenmpa** [dbeaver/dbeaver#5261]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
5.3.4
- Java version 
1.8.0_191
- Additional extensions

#### Connection specification:
- Database name and version
DB2/LINUXX8664 [SQL1005A]
- Driver name
DB2 LUW
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:
We have lots of uid-columns that use the following format:
CHAR () FOR BIT DATA

Squirrel does not handle these colums that well. In default the show up as:
*:j1¡_ û36iCû
The closest that I can get with fiddling with View/Format -> View as..->Binary is
x'2A3A6A31A15F203FFB3336693F3F43FB'
(using native and nothing for character encoding).
The thing is, I can't use that value for things like select * from table where uid = x'2A3A6A31A15F203FFB3336693F3F43FB'. I have to use the spacing that my other SQL Editor DBeaver provides, så select * from table where uid = x'2a  3a  6a  31  de  5f  11  e7  84  33  36  69  f7  f7  43  84  ' works.

So, is there a way to get Squirrel to handle thes types of columns correctly?

**Comment by titou10titou10** [comment]
Hi
I guess your question is about DBeaver, not Squirrel because if it is about Squirrel as you stated in the post, this is not the right place to ask
Denis

**Comment by Svenmpa** [comment]
Oh! All my googling yesterday to fix this made me write in the wrong place! Sorry! (facepalm)

**Comment by ahmdjerid** [comment]
Hi
Did you find  solution for this issue, i had the same

**Comment by Svenmpa** [comment]
No I am afraid not

Den tis 24 dec. 2019 kl 14:13 skrev ahmdjerid <notifications@github.com>:
