### ISSUE TITLE
Allow to find on server output console

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#5262]
As the title suggests - add the ability to search (ctrl+f) on server output console.
Currently when the cursor is on the console ctrl+f does nothing.
Using DBeaver Community 5.3.3.

Thanks.

**Comment by serge-rider** [comment]
Currently this feature is supported using context menu->Find/Replace.

**Comment by pyrocks** [comment]
your suggestion works, thanks. would be nice if find behaves the same for both editor and server output.
