### ISSUE TITLE
MySQL/MariaDB TLS 1.2 support

### ISSUE THREAD

**Issue by LameName** [dbeaver/dbeaver#5263]
Hey guys,

this is more like a question. Sorry if this isn't the correct way to do it.
I currently working on enabling TLS 1.2 on our MySQL/MariaDB (Version MariaDB 10.3.12 on Debian 9.7 with OpenSSL 1.1.0j) instances and I try to use DBeaver (Version 5.3.4, on a Windows 10 machine) to verify if it works. While testing I notice that DBeaver only supports TLS 1.1.
Which SSL lib do you use? OpenSSL, yaSSL/WolfSSL, GunTLS? Is it planned to support TLS 1.2 for MySQL/MariaDB in future?

Kind regards,
Paul.

**Comment by mkgrgis** [comment]
It was a problem with PEM keys in dbeaver (Oracle, PostgreSQL). If there is, use DER. I don't know is it actual for MariaDB, You can see the ssl classes in source code to determine which lib is called by Java. I think it's some independed realisation.
