### ISSUE TITLE
What does Incremental do in Find/Replace function.

### ISSUE THREAD

**Issue by Retko** [dbeaver/dbeaver#5267]
Hello,

I couldn't find any docs for this function:

![image](https://user-images.githubusercontent.com/37830487/52663197-5ee6bd00-2f06-11e9-89a1-955f08ef2d26.png)

Can someone explain what it does?

Thank you.

**Comment by uslss** [comment]
it is kind of live search. When you start typing the string to match - they are found incrementally as you type.
