### ISSUE TITLE
[PostgreSQL] Show dependents views in table properties

### ISSUE THREAD

**Issue by rbovard** [dbeaver/dbeaver#5272]
Hi there,

As discussed on twitter [1], is it possible to add a feature to display dependants' views in the table properties (like in the "Dependents" tab of pgAdmin).

Best regards.

[1] https://twitter.com/dbeaver_news/status/1095312837902303233

**Comment by serge-rider** [comment]
First version:

![image](https://user-images.githubusercontent.com/6398845/52915126-5cf37400-32e1-11e9-871a-1289eb7c5a0a.png)

Please create new tickets for deps visualization improvements.

**Comment by rbovard** [comment]
Thanks a lot for this quick implementation, it's working fine!

I've opened another ticket to also see dependents views in views properties.
