### ISSUE TITLE
Feature request - When opening a table editor, start in data tab

### ISSUE THREAD

**Issue by raqua** [dbeaver/dbeaver#5274]
When I click in DB navigator to open a table, it starts in "Properties" tab. 
I would like it to start in "Data" tab as I query and search the tables much more often that edit them. So I believe "Data" should be default. 
Thanks for considering.

**Comment by serge-rider** [comment]
DBeaver remembers last opened tab in table editor. And opens it when you open new table editor

**Comment by raqua** [comment]
Not after I close the app. At least not at my computer. I start DBeaver, click on a table to open and it always starts in "Properties". When I then switch do "Data" tab, close the table tab and then reopen it, it does remember to start in "Data".

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
