### ISSUE TITLE
MariaDB request created wrongly

### ISSUE THREAD

**Issue by IIPoliII** [dbeaver/dbeaver#5275]
`CREATE TABLE PickMyClothes.Customer (
	Id_Customer INT IS NOT NULL AUTO_INCREMENT,
	Name VARCHAR IS NOT NULL,
	First_Name VARCHAR IS NOT NULL,
	Date_Birth DATETIME IS NOT NULL,
	Address VARCHAR IS NOT NULL,
	Postal_Code VARCHAR IS NOT NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci
AUTO_INCREMENT=1;
`

Everytime i execute this trought the MariaDB "automatic" table creator it makes me an error why?

**Comment by serge-rider** [comment]
This DDL doesn't like like generated by DBeaver. I guess you took it from some other tool?
Anyhow, this DDL is wrong. There shouldn't be `IS` keyword before `NOT NULL` modifier.

**Comment by IIPoliII** [comment]
Hello, thanks for the answer. Normally it is DBeaver who generated it with the SQL dictonary. But thanks for your help!
