### ISSUE TITLE
DBeaver: The formatting of the Plain Text View is broken when it comes to Leading and Trailing Delimiter

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#5278]
DBeaver - **Version 5.3.5 CE** - **EA 12-Feb-2019 19:13**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**

Seems that the new property **Extra spaces** behaviour in _DBeaver_ version **EA 5.3.5** (from CASE #5165 and #5054) to add extra leading and trailing space when viewing a result set grid in **Text View** is not working fully.

It is now even more broken than it was in **5.3.4 CE**.

**Global properties/settings**:

![2019-02-13 21-11-24](https://user-images.githubusercontent.com/31191374/52740769-172e6700-2fd4-11e9-84be-96c20801b2ab.png)

**Data result gridin Text View**:

![2019-02-13 20-59-05](https://user-images.githubusercontent.com/31191374/52740625-b868ed80-2fd3-11e9-99bb-caa8b18d1951.png)

**Comment by serge-rider** [comment]
Thanks for testing it.
New EA version is in the usual place (https://dbeaver.io/files/ea)
