### ISSUE TITLE
SQL Editor rendering bug when new line is added (return key)

### ISSUE THREAD

**Issue by pazin** [dbeaver/dbeaver#5284]
#### System information: 
- Linux Fedora 25 ( 4.13.16-100.fc25.x86_64 )
- DBeaver version 5.3.4.201902031804
- Java version "1.8.0_131"
- Window Manager XFCE 4.12

#### Describe the problem you're observing:
The SQL Editor opens the contents correctly but the moment you add a new line with return key the rendering goes all weird.

![image](https://user-images.githubusercontent.com/208730/52808197-72b03180-3074-11e9-8ccf-d82e51fba2cc.png)

![image](https://user-images.githubusercontent.com/208730/52808391-ec481f80-3074-11e9-8c8b-c2f9a62acfc0.png)

Using scroll on the mouse "refreshes" the view and it renders correctly.

**Comment by serge-rider** [comment]
We had a bunch of similar issues on some Linuxes a time ago (e.g. #3916).
But at that moment they were caused by GTK2. Do you download from dbeaver.io or from some 3rd party repository?

If you have line 
```
--launcher.GTK_version
2
```
in dbeaver.ini then try to remove them.
