### ISSUE TITLE
Ctrl+Shift+Space in Autocomplete

### ISSUE THREAD

**Issue by Retko** [dbeaver/dbeaver#5286]
Hell guys,

In wiki in autocompletion section it says this:

"Another auto-complete function is search for completion only within already entered identifiers - press Ctrl+Shift+Space."

I dont quite understand this point and how to make it work. I try the buttons but nothing happens.
Can some of you please explain when to use it.

Thank you.

**Comment by nmat** [comment]
It seems to only work on the filtering box.

Example: In the test dbeaver database that comes with dbeaver.

1. Create a select from album: select * from album
2. Go to filtering:
![image](https://user-images.githubusercontent.com/383031/52897163-a6ed3480-31d1-11e9-9131-8ee9a974b522.png)

Then type: al

And hit Ctrl+Shift+Space

This will create a list of auto complete see here:

![image](https://user-images.githubusercontent.com/383031/52897175-c5533000-31d1-11e9-9953-762b76fb4b4b.png)

**Comment by Retko** [comment]
Hi, CTRL + Space is enough for your case.

But what is difference between CTRL + Space and CTRL + Shift + Space.

Thanks

**Comment by serge-rider** [comment]
Say you have the following SQL script:
```sql
select 1 from dual;
```
If you type `SEL` <kbd>ctlr+shift+space</kbd> it will complete SEL to `SELECT`. 
Because there is word starting from SEL in this script above.
