### ISSUE TITLE
Morph to Delimited Text - adds space before column name

### ISSUE THREAD

**Issue by Retko** [dbeaver/dbeaver#5287]
Hello,

i used function Format - Morph to delimited text to wrap each  column name with Quotes, but somehow it put a space in front a column name:

Before:
SELECT id, empno, ename, job, mgr, hiredate, sal, comm, deptno, same
FROM public.emp2;

After SELECT "id"," empno"," ename"," job"," mgr"," hiredate"," sal"," comm"," deptno",
" same"     
FROM public.emp2;

And off course when I run SQL it gives error that column " empno" doesnt work.

Is this a bug in the function? Or how to use it? 
Thank you

**Comment by serge-rider** [comment]
It is a kind of misfunction. I'll improve morpher so it will exclude spaces from tokens.
Workaround: add space to the list of delimiters in the options dialog.
