### ISSUE TITLE
Can't edit column details on postgres driver

### ISSUE THREAD

**Issue by xorock** [dbeaver/dbeaver#5288]
#### System information: 
- Windows 10 x64
- DBeaver version 5.3.4

#### Connection specification:
- Postgresql 9.6
- Postgresql JDBC driver

#### Describe the problem you're observing:
Hello. I'm unable to edit column details of newly created table (not yet persisted). There is no reaction when clicking edit column (f4). 
Also, under connection settings, local client is set to postgres 9.6 but I can set identity option (which is available starting from v10) and there is no option to leave it blank - which results in ddl statement error (syntax error near GENERATED).

**Comment by uslss** [comment]
cannot reproduce it for now.
ticket closed

**Comment by xorock** [comment]
V7.0.1 It still doesn't work.

![1](https://user-images.githubusercontent.com/111481/77664698-e3679400-6f7e-11ea-9c56-dd2eb848956c.png)
