### ISSUE TITLE
statics tab- show for inserted rows

### ISSUE THREAD

**Issue by ozgeunal** [dbeaver/dbeaver#5289]
Hello,

In my opinion, when i executed insert script, it must also appear 'inserted rows'  count with  'updated rows' count in statistics tab. 

Can you fix?

Thx.

**Comment by slhrkc** [comment]
+1

**Comment by serge-rider** [comment]
Number of inserted rows is shown as "Updated rows" in the statistics panel.
At least for the most databases.
what is your database?

**Comment by slhrkc** [comment]
The problem is that when i execute the sql script between begin-end block, updated rows are always shown as 0. It doesn't matter if it is an update or insert statement.
