### ISSUE TITLE
open cell editor error

### ISSUE THREAD

**Issue by xfzhaoxd** [dbeaver/dbeaver#5290]
#### System information: 
- windows 10
- DBeaver version 5.3.4
- Java version 11
- Additional extensions

#### Connection specification:
- Database name and version   mysql
- Driver name  mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
I have a  problem,when I edit table's record.
Describe：column type is varchar(100) and cell value is null ,open cell editor show error icon but no text message.
#### Include any warning/errors/backtraces from the logs
Thank you!

**Comment by serge-rider** [comment]
Thanks for the bug report
