### ISSUE TITLE
RowCountEstimate is not at all close

### ISSUE THREAD

**Issue by fredjohnston** [dbeaver/dbeaver#5293]
I found an old fix Preferences> Databases> Metadata> (x)ShowRowCountForTables, but after checking it, and even restarting, some of my RowCountEstimates are not correct (eg shows 0 when i might have 14 rows, for example).  Doing a F5 refresh does not update the value.  V5.3.4.201902031804 mac.

**Comment by serge-rider** [comment]
RowCountEstimates is estimate value (I guess you are on PostgreSQL) and it is not refreshed immediately. It is not affected by "Show row count for tables".
The property you need is "Row count":
![image](https://user-images.githubusercontent.com/6398845/52913252-49d6a900-32cd-11e9-822c-b6b59d8f2f58.png)
