### ISSUE TITLE
Clear grid on error

### ISSUE THREAD

**Issue by alonpr** [dbeaver/dbeaver#5294]
Is there an option that the grid will be cleared in case of sql error?
Or that an sql error be displayed in a pop-up?

As in default, the evidence of the sql error is only shown below the grid and it might be confusing as can be rather easily missed.

**Comment by uslss** [comment]
seems that it is already implemented.
![image](https://user-images.githubusercontent.com/31996417/73826351-b0bade00-480e-11ea-893e-c80c97fbb65b.png)

**Comment by alonpr** [comment]
no, it's not. run a query that returns data into the data grid, then change
the syntax to create an error and run the query -> the grid will still
contain the result from a previous successful run
