### ISSUE TITLE
Postgres : Wrong Information on Index section

### ISSUE THREAD

**Issue by mangaldev** [dbeaver/dbeaver#5295]
#### System information: 
- Operating system (distribution) and version : OSX Mohave
- DBeaver version : Version: 5.3.4.201902031804
- Java version : 1.8.0_192
- Additional extensions

#### Connection specification:
- Database name and version : Postgres 9.6
- Driver name 
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
With recent feature https://github.com/dbeaver/dbeaver/issues/4605 Index Scans and its size were added into the index section page. But it seems it is not showing the correct information.

#### Steps to reproduce, if exist:
Check the image below. I have 3 different indexes with different columns but num scans and rel-size shows the same numbers and numbers are incorrect too.

#### Include any warning/errors/backtraces from the logs
![image](https://user-images.githubusercontent.com/402377/52897272-68cb2300-3187-11e9-88ed-2bfdf81bd6f3.png)

**Comment by serge-rider** [comment]
Thanks for the bug report (it was table rel size, not index)
