### ISSUE TITLE
SQLEditor - copy/pastes an altered clipboard (not expected)

### ISSUE THREAD

**Issue by JayKidd81** [dbeaver/dbeaver#5296]
#### System information: 
- OS version: Microsoft Windows [Version 10.0.16299.904]
- DBeaver version: 5.3.4.201902031804
- Java version: jre1.8.0_191

#### Describe the problem you're observing:
In the SQLEditor, when copying and pasting text, the pasted text is not the same as what is being copied.

#### Steps to reproduce, if exist:
Copy:
"name" = excluded."name",
Pastes:
namename

**Comment by nmat** [comment]
Tested it here on windows and get the same result. Odd behaviour. Pasting from dbeaver to editor seems to work though.

It looks like its a translation thing inside dbeaver.

**Comment by serge-rider** [comment]
It is "Convert from source code" feature. You can disable it in preferences. 
Or, if you still need it in most cases then you can just press Undo shortcut (<kbd>ctrl+z</kbd>) after paste.


![image](https://user-images.githubusercontent.com/6398845/52912845-599fbe80-32c8-11e9-91e1-54c3ed33ffbf.png)

**Comment by JayKidd81** [comment]
Ah, thanks, you are correct. Disabled the "Extract SQL from source code" feature and now copy/paste works as expected :)
