### ISSUE TITLE
Search DB Metadata - Data Type

### ISSUE THREAD

**Issue by Retko** [dbeaver/dbeaver#5297]
Hi,

As I understood - by checking Data Type in DB Metadata Search it should find tables with a given data type. So I tried this:

![image](https://user-images.githubusercontent.com/37830487/52912790-bd20f080-32b6-11e9-96e1-18f81e268316.png)

So I expect all tables with Date Data Type. But nothing get returned. Also tried with int, int4, varchar.

Can someone tell why there are no results?

Thanks

**Comment by serge-rider** [comment]
Metadata search is searching for objects of different types (not just tables).
And it searches only by name.

So if you check "Data type" it will search for data types (or domain types), not for tables.

**Comment by Retko** [comment]
So how come it didn't find anything for int4. I know there are many columns with int4 data types.

Can you probably give an example? 
Thank you.

**Comment by serge-rider** [comment]
> it searches only by name

It doesn't search within table column properties (like type, name, etc).
In your case it will search for tables with `int4` in their names. It is a pretty simple search functions.
