### ISSUE TITLE
dbeaver strips consecutive spaces from json data type fields

### ISSUE THREAD

**Issue by gprimosch** [dbeaver/dbeaver#5298]
#### System information: 
- Operating system (distribution) and version: MacOS 10.14.1
- DBeaver version: 5.3.3
- Java version: 1.8.0_202-ea
- Additional extensions: none

#### Connection specification:
- Database name and version: Postgres 10
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:

dbeaver strips consecutive spaces when copy-pasting json data type fields

#### Steps to reproduce, if exist:

When I run the following SQL on the latest Postgres and copy-paste the result to my editor, I get the following response:

<pre>SELECT json_build_object('three_spaces', '3 SPACES AFTER THIS   END');</pre>

<pre>{"three_spaces" : "3 SPACES AFTER THIS END"}</pre>

Note that the text shown in the grid also appears to lack the consecutive spaces.

When I cast the result to a varchar, it copy-pastes fine: 

<pre>SELECT CAST(json_build_object('three_spaces', '3 SPACES AFTER THIS   END') AS varchar);</pre>

<pre>{"three_spaces" : "3 SPACES AFTER THIS   END"}</pre>

It also copy-pastes fine in in the JSON data type case if I double-click into a cell and manually select the text.

**Comment by serge-rider** [comment]
Indeed extra spaces are stripped from complex values (json, xml). But this compaction is performed only for value view (otherwise some json values look like tons of spaces). 
When you open json value in panel view or in editor then values is rendered as is.

**Comment by serge-rider** [comment]
Perhaps we should compact only spaces between values but not values themselves..

**Comment by gprimosch** [comment]
The problem isn't the rendering, but copy-paste. If the copy-paste went back to the raw text, then the rendering wouldn't be so much of an issue. If it is too much avoid compacting spaces in values, then having an advanced copy option that copied the raw text would be sufficient.

**Comment by serge-rider** [comment]
Could you test it in the latest version (5.3.5)? It copies jsons with correct spaces as far as I see..

**Comment by gprimosch** [comment]
Looks good now, thanks!
