### ISSUE TITLE
Setting up SSL to Cloud SQL (Postgres)

### ISSUE THREAD

**Issue by bobpardoe** [dbeaver/dbeaver#5302]
#### System information: 
- Operating system (distribution) and version : Ubuntu 18.10
- DBeaver version : 5.3.4
- Java version : open_jdk 1.8_191
- Additional extensions

#### Connection specification:
- Database name and version : Google Cloud SQL - PostgreSQL
- Driver name : postgresql?
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSL

#### Describe the problem you're observing:
I have used the files (server/client/client-key) created  by Google and this all works in pgAdmin4 and psql via a proxy

#### Steps to reproduce, if exist:
Trying to connect shows the following message : 

"FATAL: connection requires a valid client certificate"

Some information as to why it is invalid might able me to solve the problem myself in case it is a setup issue.

**Comment by mkgrgis** [comment]
Please, read and verify your SSL crt file by OpenSSL or analog. Example for reading
`openssl x509 -in /etc/ssl/certs/client.crt -text -noout`
so must be equal your components, for example
`openssl x509 -noout -modulus -in /etc/ssl/certs/client.crt | md5sum`
and
`openssl rsa -noout -modulus -in /etc/ssl/certs/client.key | md5sum`

**Comment by bobpardoe** [comment]
I have done as you suggested by converting the pem's to .crt and .key and validated them but still the same error.

I have tried putting the files in /etc/ssl/certs but it makes no difference.

Any other ideas?

![openssl](https://user-images.githubusercontent.com/11973854/53693461-b014fe80-3d98-11e9-9bc1-5b3e02f79357.png)

**Comment by mkgrgis** [comment]
In any cloud SSL services CommonName field in crt must be equal to user′s name.
So, "for reading `openssl x509 -in /etc/ssl/certs/client.crt -text -noout`" means, that you can read  dates for crt.  If your crt yet not valid?
`openssl x509 -in /etc/ssl/certs/client.crt -noout -dates`
Note: if it′s only jdbc, address of crt/key/... is′t success factor at all.

**Comment by bobpardoe** [comment]
Dates are valid. postgres is the name of the certificate I created on Google Cloud SQL

![image](https://user-images.githubusercontent.com/11973854/53698117-5e886600-3dd0-11e9-98bc-9ce30a28e03b.png)

**Comment by bobpardoe** [comment]
I have used the same certificates with pgAdmin4 and they work (Google is happy with them). I had to set some  permissions on one of the files to make pgAdmin4 happy tho'

I much prefer dbeaver's interface so I'm hoping we can get this to work.

**Comment by mkgrgis** [comment]
I think the problem was in permissions (mode) of key file. It must be not readable for group and other. For example `chmod 700 file.key` or `chmod 700 file.key`.

**Comment by bobpardoe** [comment]
I have tried 500 600 and 700 on the key file but no difference. Is there no debug output somewhere that can be seen to find out why it thinks the certificate is invalid. I am assuming the problem is ith dbeaver not google?

**Comment by mkgrgis** [comment]
Yes, i think it's problem with SSL java classes in dbeaver.
Base example of SSL connection to PostgreSQL use psql. I think, you can read diagnostic messages from psql terminal. I always test connection with psql and this conditions
1. DER key 
2. Valid certificate by dates
3. key have no permissions to other users (group and other).

You can construct base example from my case (See p. 830, https://www.postgresql.org/files/documentation/pdf/11/postgresql-11-A4.pdf). Please, modify for Your situation.
`echo "SELECT now();" | PGHOST="$cloud_serv" PGPORT=5432 PGDATABASE="试用数据库" PGUSER="王莉" PGAPPNAME="psql test" PGSSLMODE="require" PGSSLCERT="/home/pgcloud/王莉.crt" PGSSLKEY="/home/pgcloud/王莉.der" PGSSLROOTCERT="/home/pgcloud/AWS.crt" ;`
The right answer is server's time.
