### ISSUE TITLE
Project scripts sorting

### ISSUE THREAD

**Issue by michelvosje** [dbeaver/dbeaver#5305]
DBeaber version: 5.3.3.201901202008

In the scripts panel I just enabled the column "Modified" to see the modification date of scripts. I noticed that the arrow to display the sorting order is pointing in the incorrect direction.

![image](https://user-images.githubusercontent.com/5354633/52936226-d465e980-335b-11e9-91b3-c425348d4e48.png)

A screenshot from Windows Explorer:
![image](https://user-images.githubusercontent.com/5354633/52936379-3aeb0780-335c-11e9-99f0-5fedc267f343.png)

**Comment by serge-rider** [comment]
Thanks for the bug report. In fact this bug was in big number of other DBeaver table views.
Also sorting by file size was fixed (it must sort values as numbers but not as strings)
