### ISSUE TITLE
Filter with F11 no longer working in 5.3.5

### ISSUE THREAD

**Issue by becks0815** [dbeaver/dbeaver#5311]
#### System information: 
- Operating system (distribution) and version Windows 7 Enetrprise
- DBeaver version 5.3.5
- Java version JRE which comes with dbeaver
- Additional extensions

#### Connection specification:
- Database name and version - any db/table tested
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

On the data view tab I no longer can use F11 and the sub menus to generate filter strings like filtering for a specific column value..

#### Steps to reproduce, if exist:

Open a table, change to the data tab, select a field, hit F11 and try to create a filter definition.

**Comment by serge-rider** [comment]
You can test the fix in Early Access build (https://dbeaver.io/files/ea)

**Comment by becks0815** [comment]
Can confirm: it works again. Thx for the quick fix.
