### ISSUE TITLE
Oracle session browser - use gv$session

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#5313]
On RAC Oracle database (that is, Oracle database running on more than one node) the v$session view only returns sessions running on the same node as the current session: you should use gv$session to get all sessions on all nodes. Official Oracle documentation is not very clear about this (https://docs.oracle.com/database/121/REFRN/GUID-884B21B1-7C87-41E1-8F97-C4668704AF30.htm#REFRN-GUID-884B21B1-7C87-41E1-8F97-C4668704AF30), but check out this stackoverflow answer https://stackoverflow.com/questions/28814543/is-there-any-way-to-get-information-about-current-session-from-gvsession-in-ora, especially comments.

I've struggled to understand why Toad showed me more sessions than dbeaver, then I found out Toad was using gv$session. IDK if gv$session is usable on non-RAC installations, so you might have to check that. This is not limited to v$session, all v$ views have a gv$ corresponding on RAC.

**Comment by p91paul** [comment]
I tested the following query on my local environment, which is most certainly not RAC, and it works:

```sql
SELECT s.*, sq.SQL_FULLTEXT, io.* 
FROM GV$SESSION s 
LEFT JOIN gv$sql sq ON ( s.inst_id = sq.inst_id AND s.sql_address = sq.address AND s.sql_hash_value = sq.hash_value AND s.sql_child_number = sq.child_number)
LEFT JOIN gv$sess_io io ON ( s.inst_id = io.inst_id AND s.sid = io.sid)
WHERE 1=1 AND s.TYPE = 'USER' AND s.STATUS <> 'INACTIVE'
```

**Comment by serge-rider** [comment]
This makes sense.
Thanks for the hint.

**Comment by p91paul** [comment]
got a glance at your code, please notice that sid is not enough, gv$ views need to be joined by inst_id as well. Otherwise you'll probably end up with duplicated rows when a query gets distributed on many instances with the same sid.

**Comment by uslss** [comment]
verified
