### ISSUE TITLE
resultset order filter setting windows design issues

### ISSUE THREAD

**Issue by myururdurmaz** [dbeaver/dbeaver#5315]
#### System information: 
- Operating system (distribution) and version debian linux
- DBeaver version 5.3.5 deb package
![image](https://user-images.githubusercontent.com/1057861/52994130-a0f09100-3427-11e9-9815-bed8f2861b4b.png)
- Java version 
- Additional extensions

first opening order column too small
![screenshot_2019-02-19_09-12-59](https://user-images.githubusercontent.com/1057861/52994075-6b4ba800-3427-11e9-8889-43fa4b4a1ec4.png) 

select order blue arrow and blue row selection. can not visible arrow
![screenshot_2019-02-19_09-18-25](https://user-images.githubusercontent.com/1057861/52994145-b06fda00-3427-11e9-9946-123f53912bfd.png)

**Comment by uslss** [comment]
closed without tests
