### ISSUE TITLE
oracle创建数据表的时候，字段注释问题

### ISSUE THREAD

**Issue by f8q8** [dbeaver/dbeaver#5316]
#### System information: 
- Operating system (distribution) and version（win10企业版LTSC）
- DBeaver version（5.3.4）
- Java version （1.8）
- Additional extensions

#### Connection specification:
- Database name and version（oracle 11g）
- Driver name ojdbc6-11.2.0.3.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? (no)

#### Describe the problem you're observing:
创建数据表的时候，直接给字段加上注释，创建表的时候，并不会把字段的注释带上，但是，表的注释会带上

**Comment by swelltt0576** [comment]
还能支持中文issue？

**Comment by f8q8** [comment]
@swelltt0576 不知道啊，试试吧，

**Comment by mkgrgis** [comment]
显然，问题翻译。
Похоже на проблему перевода. Оригинал плохого перевода не выявлен в  dbeaver/plugins/org.jkiss.dbeaver.ext.oracle/OSGI-INF/l10n/bundle_zh.properties

**Comment by mkgrgis** [comment]
Problem
ru_RU: При создании таблицы данных непосредственно аннотируйте поле. При создании таблицы комментарий к полю не будет взят, а комментарий к таблице будет принят.
en_GB: When creating a data table, directly annotate the field. When the table is created, the comment of the field will not be taken, but the comment of the table will be taken.
zh: 创建数据表的时候，直接给字段加上注释，创建表的时候，并不会把字段的注释带上，但是，表的注释会带上

**Comment by uslss** [comment]
issue isn't reproducible for now.
ticket closed
