### ISSUE TITLE
Default Data Source in SQL Editor

### ISSUE THREAD

**Issue by shungabubus** [dbeaver/dbeaver#5318]
Hello All,

When I open scripts linked to the project it is hard to decide which connection to use except when there is only one for the project:
![image](https://user-images.githubusercontent.com/36946814/53010758-000dd000-343f-11e9-973a-ca0c9eb69d6d.png)

In this case is there any chance to add it to the SQL connection automatically?
![image](https://user-images.githubusercontent.com/36946814/53010801-1582fa00-343f-11e9-948c-b050795f50ed.png)

Many thanks in advance:
Tamas

**Comment by serge-rider** [comment]
I'm not sure I clearly understand this.
Anyhow you can use "Associate with datasource" action (in context menu). Select a bunch of scripts and link them with needed database connection:
![image](https://user-images.githubusercontent.com/6398845/54311921-adab7380-45e6-11e9-8ce9-56f674c87889.png)

**Comment by shungabubus** [comment]
Hello, 

Sorry I got no alert on this answer. It is a possible approach, thanks, but it would be nice if it was automatic in case the project has ONLY ONE data source.

Many  thanks:
Tamas

**Comment by uslss** [comment]
already implemented.
