### ISSUE TITLE
No default column values in generated DDL

### ISSUE THREAD

**Issue by sspam60** [dbeaver/dbeaver#5319]
#### System information: 
- Operating system (distribution) and version: Ubuntu 16.04.5 LTS
- DBeaver version 5.3.5.201902172105

#### Connection specification:
- Database name and version: Microsoft SQL Server 2017 (RTM-GDR) (KB4293803) - 14.0.2002.14 (X64)  Jul 21 2018 07:47:45
Driver name: MS SQL Server / SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
Generate SQL DDL does not adds column default values into create table script.

**Comment by serge-rider** [comment]
Thanks for the bug report
