### ISSUE TITLE
Edit result cell (Linux, Wayland)

### ISSUE THREAD

**Issue by Kazun3500** [dbeaver/dbeaver#5322]
#### System information: 
- Ubuntu 18.04 x64 on Wayland
- DBeaver version 5.3.5
- Java version 1.8.0_191 by Oracle Corporation (64bit)

#### Connection specification:
 Do not depend on connection (checked on oracle, postgresql, mysql)

#### Describe the problem you're observing:
After double click on cell in results built-in editor open and close momently. 
After press Enter on cell - all is ok.
Little video included
[dbeaver_edit_cell.zip](https://github.com/dbeaver/dbeaver/files/2880760/dbeaver_edit_cell.zip)
On x11 all is ok.

At bug reproduction moment  logs do not change

**Comment by dirkesquire** [comment]
Same issue as #7716 and #7597

**Comment by uslss** [comment]
cannot reproduce it for now.
If it is still actual - feel free to reopen the ticket

**Comment by Kazun3500** [comment]
Bug still present. Ubuntu 20.04.

**Comment by uslss** [comment]
@Kazun3500 do you use Wayland?

**Comment by Kazun3500** [comment]
Yes.

**Comment by Kazun3500** [comment]
[Download.zip](https://github.com/dbeaver/dbeaver/files/4961774/Download.zip)
Video attached

**Comment by akilovich** [comment]
Hello @Kazun3500. I could not reproduce the problem against the latest DBeaver version. Could you please tell me if you still encounter the issue with the latest version? Thank you.

**Comment by Kazun3500** [comment]
Hello. Bug still present, video the same.  Wayland session, on three different pc (2 x ubuntu 20.04 Gnome + 1 x  KDE Neon). All systems - almost default. 

How you tried to reproduce? Can you do a little video?

**Comment by akilovich** [comment]
Okay, for whatever reason the bug can not be reproduced with DBeaver installed from snap. I downloaded tarball and reproduced it instantaneously. Working on it.

**Comment by flambchap** [comment]
It will be fixed in the scope of https://github.com/dbeaver/dbeaver/issues/16705.
