### ISSUE TITLE
Configure DBeaver to Work with Apached Drill 

### ISSUE THREAD

**Issue by bsthinker** [dbeaver/dbeaver#5323]
Is it possible to configure DBeaver to read table names and columns from a file plugin.  Similar to Drill explorer, but with the excellent features of DBeaver.

Currently DBeaver lists the file plugins, but not the tables nor columns.  SQL can be executed.

**Comment by serge-rider** [comment]
Generally it should work without any special configuration.

Unfortunately I can't validate this as we don't have live Drill instance at the moment.
If anybody could assist with it - please write me on serge@jkiss.org.
