### ISSUE TITLE
Dbeaver giving privildges to other users 

### ISSUE THREAD

**Issue by snajafi1** [dbeaver/dbeaver#5329]
Hi everyone,

Recently our database admin left the project and gave me all the privileges and I am the database admin at the moment. When I want to give or change access to/of other users there is no permission tab or roles available on my dbeaver. Apart from the script is there any way to give permission by clicking the box against user? (it is PostgreSQL) Many Thanks
![image](https://user-images.githubusercontent.com/47820709/53095772-85fc4a80-3515-11e9-8fe9-9cbb158cc3ce.png)

**Comment by serge-rider** [comment]
What is your database? DBeaver supports permission management for MySQL/MariaDB and PostgreSQL based databases.

**Comment by snajafi1** [comment]
@serge-rider it is postgreSQL

**Comment by serge-rider** [comment]
Yes, you can edit permission in PostgreSQL. It looks like you are using legacy PG driver (`PostgreSQL (Old)`), it doesn't support most of new PG features.

Just use regular PostgreSQL driver (create new connection or change driver of existing connection using main menu Database->Migrate connection).

This is how you table should look like:
![image](https://user-images.githubusercontent.com/6398845/53126189-a9a0ae80-3570-11e9-8a84-21ed096e9f92.png)
