### ISSUE TITLE
Execute script with embedded create/alter SP for Sql Server

### ISSUE THREAD

**Issue by crokusek** [dbeaver/dbeaver#5331]
#### System information: 
- Windows 10
- 5.3.3
- JRE shipped with 5.3.3

#### Connection specification:
- Sql Server Azure or Sql Server 2012
- Latest Sql Server
- No Proxy/Tunnel afaik

#### Describe the problem you're observing:
Can't execute multi-statement script with multiple embedded create/alter of procedures/views/etc.  See attached script.  

These types of scripts are commonly produced by RedGate software to synchronize databases.  They can be quite large (e.g. >100 objects).   The "go" keyword indicates end of current batch and that the next statement should begin a fresh batch.  This is required for commands like like "create proc ..." else an error occurs (try without the go to see).   Note that the example includes a transaction wrapping the entire script (the GOs should maintain the same session across batches), this is common technique for deployment scripts and also RedGate generated.

The example script tested successfully in SSMS and Toad.

Related to #2692 which is for a single Create statement which works fine.

[EmbeddedCreateSp.sql.txt](https://github.com/dbeaver/dbeaver/files/2886863/EmbeddedCreateSp.sql.txt)

#### Steps to reproduce, if exist:
1) Open Editor, 
2) Copy attached script contents into editor
3) Select all of the text (Ctrl-A)
4) Alt-Enter

**Comment by serge-rider** [comment]
Currently DBeaver doesn't support T-SQL dialect fully.
Workaround: disable semicolon delimiter (see screenshot).
Then you can run your script with <kbd>alt+x</kbd>.

![image](https://user-images.githubusercontent.com/6398845/54312264-830dea80-45e7-11e9-8225-0a3c3df95813.png)
