### ISSUE TITLE
[Postgres/postgis] Cant display geometry_dump columns

### ISSUE THREAD

**Issue by LorisZ** [dbeaver/dbeaver#5332]
#### System information: 
- Ubuntu 18.04
- DBeaver 5.3.5
- Java version 1.8.0_201

#### Connection specification:
- Postgres 9.6

#### Describe the problem you're observing:
Can't display columns of type geometry_dump.

#### Steps to reproduce, if exist:
When executing a query that returns a column of geometry_dump like the following:

```sql
select st_dump(the_geom)
from (
    values ('MultiPoint((1 2))'::geometry)
) q (the_geom)
```
it shows `<NULL>` in both resulting columns and a warning: `Can't read column 'st_dump' value - For input string: "{1}"`

Changing the query like the following works:

```sql
select (st_dump(the_geom)).geom -- or .path also works
from (
    values ('MultiPoint((1 2))'::geometry)
) q (the_geom)
```

**Comment by serge-rider** [comment]
This is actuall a bug in PG structs with nested array parser.
Thanks for the bug report
