### ISSUE TITLE
[Postgres/postgis] 3 or 4 dimensional geometries are shown as 2D

### ISSUE THREAD

**Issue by LorisZ** [dbeaver/dbeaver#5333]
#### System information: 
- Ubuntu 18.04
- DBeaver 5.3.5
- Java version 1.8.0_201

#### Connection specification:
- Postgres 9.6

#### Describe the problem you're observing:
3 or 4 dimensional geometries are shown as 2D

#### Steps to reproduce, if exist:
When executing a query that returns a 3 or 4 dimensional geometry like the following:

```sql
select 'MultiPointZ((1 2 3))'::geometry
```

the result is `MULTIPOINT ((1 2))`, losing the third dimension. Kind of irritating when you expect 3d geometry and only see 2 dimensions.

**Comment by serge-rider** [comment]
Recent PG JDBC driver allow to parse/generate PostGIS values directly.
This simplifies GIS support in DBeaver.
Multidimensional geoms support will be fixed in the next version, thanks for the bug report.
