### ISSUE TITLE
SQL Server: Binary Data Display on Grid

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#5334]
DBeaver - Version 5.3.5 CE
Operating System: Windows 10
JDBC Driver: mssql-jdbc 7.0.0.jre10
Database: Microsoft SQL Server Database

I've noticed that binary data in SQL Server table looks like following. We need it to display same as we see in SSMS.

![image](https://user-images.githubusercontent.com/38669892/53191271-0338c580-35d1-11e9-8db7-b6f44eebc7a8.png)

Can this be fixed please ?

**Comment by serge-rider** [comment]
You can change binary data representation:
![image](https://user-images.githubusercontent.com/6398845/53194248-f1ccd900-3623-11e9-87b8-cc24918695e5.png)
