### ISSUE TITLE
Issue With dbeaver and test connection button on Ubuntu Budgie 18.04LTS

### ISSUE THREAD

**Issue by OzzzM** [dbeaver/dbeaver#5335]
Hi,

I got a problem with dbeaver and test connection button on Ubuntu Budgie 18.04LTS 64 bits, i open the program and select de SQL Server connection or MySQL, but i can't see the button of "Testing connection" 

Check this screenshot:

https://scontent-atl3-1.xx.fbcdn.net/v/t1.0-9/52543530_412654849542266_7844569857029832704_n.jpg?_nc_cat=104&_nc_ht=scontent-atl3-1.xx&oh=1d31e4abb79c6ccd552c14278e2dbf77&oe=5CF35607

Can anyone help me?
Really, really thanks.

Dbeaver Community Edition 5.3.5
Ubuntu Budgie 18.04 LTS 64 bits.

**Comment by serge-rider** [comment]
Don't use File->New (or <kbd>ctrl+n</kbd>) wizard. It is too general.
Use toolbar button or context menu or main menu Database->New Database Connection.
