### ISSUE TITLE
When row fetch limit size is large, not including a "top N" is 100x slower.

### ISSUE THREAD

**Issue by crokusek** [dbeaver/dbeaver#5337]
#### System information: 
- Windows 10
- 5.3
- Jre shipped with 5.3

#### Connection specification:
- Sql Server Azure
- Latest Sql Server
- No proxy/tunnel/etc.

*Update:*  This problem is limited to WAN such as when connecting to Azure

#### Describe the problem you're observing:
When fetch row limit is large, the runtimes to retrieve results into the datagrid are 100x faster only if a "top N" clause is specified.  Considered unusable otherwise.

#### Steps to reproduce, if exist:
1) Set the global fetch size limit to a large value 1000000 (1M),
2) Create a temp table or find a large table with 1M rows (sorry, I can provide if this is needed).
3) Note runtime of:  select top 1000000 * from #t
4) Note runtime of:   select * from #t

For me, (3) was 1s while (4) was >100s

If the fetch row size is set smaller like 1k and then click the "fetch all rows" special button then it is indeed fast.  So I guess that button is the workaround.  The downside that if the query takes a long time to generate the 1k then it will have to be repeated.  So this may be a low priority issue since there is a workaround and also since it is only a WAN issue.

Option "Use Sql to limit fetch size" option did not affect the results.

**Comment by serge-rider** [comment]
We'll add TOP in all SELECT queries in the next version.
Please test it in Early Access version (https://dbeaver.io/files/ea)

**Comment by uslss** [comment]
verified
