### ISSUE TITLE
support cratedb

### ISSUE THREAD

**Issue by cmdares** [dbeaver/dbeaver#5338]
jdbc mvn repo  https://mvnrepository.com/artifact/io.crate/crate-jdbc
cratedb repo https://crate.io/

**Comment by serge-rider** [comment]
Crate driver will be added in the next version.

**Comment by iambudi** [comment]
1. When opening table it display popup : 

> SQL Error [42846]: Cannot cast to boolean: "NEVER"
>   Cannot cast to boolean: "NEVER"
> 

The toolbar icon to add  row is disabled.
2. Can not create new table it says syntax error, when i create manually using ddl query it works.
```
create table test (
  first_column integer,
  second_column text
);
```

**Comment by iambudi** [comment]
I use DBEaver CE 6.2.1

**Comment by burningalchemist** [comment]
@serge-rider The issue exists with DBeaver, indeed. I'm happy to help with investigation, though.

So far I'm trying to figure out the statement coming from DBeaver and there is nothing in debug-logs (except stack traces). If I try to use `Read data in SQL Console` in the context menu, I see the same error as mentioned above and nothing more. But if I just double-click on the table, besides the error I'm also able to see entries and work with them. If you could hint on something, that'd be cool.

P.S. Should I open an issue for that or it's unnecessary?

@iambudi You can use `PostgreSQL (Old)` for the moment, it seems to work properly. Check it out, if it's still relevant. :)

**Comment by burningalchemist** [comment]
@serge-rider JFYI, the issue doesn't appear in DBeaver 6.2.5, everything works as expected. 👍
