### ISSUE TITLE
[DB2]Duplicate column name error @ data transfer

### ISSUE THREAD

**Issue by sanchez85** [dbeaver/dbeaver#5341]
System information: 
- Win 10 x64
- DBeaver 5.3.3/5.2.5
- Java 1.8.0_201

Connection specification:
- DB2 v11.1.2.2
- driver DB2 LUW

I've some problem with "export resultset" to database in the 5.3.3 release.

1.example query:

select album_name,artist_name from (
select
a.name album_name,
b.name artist_name
from album a
join Artist b on a.ArtistId=b.ArtistId)

2. Export Resultset>Database>SingleQuery>ColumnsMappings

3. ColumnsMappings have only "name" in source column (without alias "album_name" or "artist_name"),
so we can't export data with duplicate column name error.

I tried downgrading to 5.2.5 and had the same error.

Downgrading to 5.0.2 version fixed the problem.

**Comment by serge-rider** [comment]
We'll return to original behavior (use column labels) in the next version.

Workaround: change target column names manually (use "Columns" dialog).
Thanks for noticing that.

**Comment by uslss** [comment]
verified
