### ISSUE TITLE
sybase jconnect does not allow column edit nor new/delete but insert/update scripts work 

### ISSUE THREAD

**Issue by Henry-Jones** [dbeaver/dbeaver#5343]
After solving the problem with the connection (alas jTDS still not working, only jconnect) I now face the problem that the tables seem to be read-only.

It is in essence the same topic described here #75.

If I change content with an SQL statement, like insert or delete this works.

**Comment by serge-rider** [comment]
If you want to edit results of SQL query then try to use fully qualified table name (with database/schema prefix).
Is table data editable when you edit table data directly? (not in SQL editor)
