### ISSUE TITLE
IN filter can't keep track of the marked values when another text is typed 

### ISSUE THREAD

**Issue by xxx-mar** [dbeaver/dbeaver#5344]
**System information**
windows 7
dbeaver v5.3.5

**connection spec**
sqlite connection

I started to use the IN filter. I was expecting to do multiple selects and use of the text search below to accelerate the finding. However whenever I type a value and I check it, then I type another value and check it and so on, I got only the value last selected.
It looks like whenever the search filter is changed, the values ticked is reset.

Any ideas for that?

**Comment by xxx-mar** [comment]
**System information**
windows 7 
dbeaver v5.3.5

**connection spec**
sqlite connection

I started to use the IN filter. I was expecting to do multiple selects and use of the text search below to accelerate the finding. However whenever I type a value and I check it, then I type another value and check it and so on, I got only the value last selected.
It looks like whenever the search filter is changed, the values ticked is reset. 

Any ideas for that?

**Comment by serge-rider** [comment]
We need to keep previous filter settings.
+ Add clear checked values button.

**Comment by serge-rider** [comment]
Done

**Comment by uslss** [comment]
Reopened.
Error appears while trying to enter value for int column (postgre)
![image](https://user-images.githubusercontent.com/31996417/55915260-f3615900-5bf1-11e9-8b8b-aa1caffe2b1f.png)
[log.txt](https://github.com/dbeaver/dbeaver/files/3065958/log.txt)

**Comment by serge-rider** [comment]
@uslss This is unrelated error. However I've fixed it as well

**Comment by uslss** [comment]
Verified.
Connected issue created [https://github.com/dbeaver/dbeaver/issues/5721](url)
