### ISSUE TITLE
Misrepresentation of special Western European characters in text panel

### ISSUE THREAD

**Issue by solisgb** [dbeaver/dbeaver#5345]
Hi,
I have a Postgres DB codified as UTF8. The results of a select involving Western European characters are represented OK in the Grid panel and in the in the value panel, but not in the text panel.
For example:
In the grid panel, I can correctly see the Spanish municipality name "Herbés" but in the text panel, it is represented as "Herb s"; the same occurs in other names involving characters as "ñ", "'" and so.
I am working on Windows 10, Postgres v. 11.2 and DBeaver 5.3.5 with Java embedded.
Regards.

**Comment by serge-rider** [comment]
We'll return non-ASCII characters in plaintext presentation. They were removed because some of them corrupt text (e.g. when some binary data is encoded as string).

**Comment by uslss** [comment]
verified
