### ISSUE TITLE
Oracle sessions long operations - use serial#

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#5346]
To get long operations for a session you are currently using this query:
```sql
SELECT * FROM V$SESSION_LONGOPS WHERE SID=<sid from v$session>
```

Instead you should be using
```sql
SELECT * FROM V$SESSION_LONGOPS WHERE SID=<sid from v$session> AND SERIAL#=<serial# from v$session>
```
SID isn't enough for a key, I'm seeing long ops that are clearly from another session. See https://docs.oracle.com/cd/B19306_01/server.102/b14237/dynviews_2088.htm#REFRN30223 to see why serial# is needed, apparently SID can be reused once the session ends.

**Comment by p91paul** [comment]
Also, it should be gv$session (with an added inst_id filter) per #5313

**Comment by serge-rider** [comment]
Thanks for PR!

**Comment by uslss** [comment]
verified
