### ISSUE TITLE
Sybase Timstamp format garbled

### ISSUE THREAD

**Issue by ChristianStanleyTaylor** [dbeaver/dbeaver#5349]
### System information:
* Operating system Windows 10 Build 14393.969
* DBeaver version 5.3.5
* Java version 1.8.0_144
* Additional extensions None

#### Connection specification:
* Database name and version Sybase Adaptive Server Enterprise 12.5.4
* Driver name Sybase jConnect
* Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Returned values for Timestamps are not displaying correctly
E.g. instead of "yyyy-mm-dd hh:mm:ss" I get a string of nonsensical characters. e.g. "    /F¢"

#### Steps to reproduce, if exist:
Constant issue. Happens across all connected DB's.

#### Include any warning/errors/backtraces from the logs
None Available logs are clear. 

![image](https://user-images.githubusercontent.com/9969602/53311359-04d1f880-3905-11e9-8cd8-ee4e78f8b6f0.png)

**Comment by hgdebie** [comment]
Hello,

Could this be the answer: https://stackoverflow.com/questions/3500703/what-is-the-mysterious-timestamp-datatype-in-sybase

For Sybase datetime datatypes: https://wiki.ispirer.com/sqlways/sybase/data-types/datetime

**Comment by serge-rider** [comment]
In Sybase and SQL Server `timestamp` is a binary data type.
If you need to keep date/time values use `datetime` or `datetime2` data types.

**Comment by serge-rider** [comment]
Also you can change the format for binary data types in preferences:
![image](https://user-images.githubusercontent.com/6398845/53695025-9212c280-3dc7-11e9-8d4f-1df0f2a9359d.png)

**Comment by ChristianStanleyTaylor** [comment]
Thanks bud, sorry I didn't realise I could change the format. I looked
at date formats not binary.
