### ISSUE TITLE
mysqldump - /etc/mysql/ 'password' is more important than all DBeaver settings

### ISSUE THREAD

**Issue by JSkalskiSBG** [dbeaver/dbeaver#5350]
#### System information: 
- Linux Mint 19.1 (Ubuntu 18.04 based)
- DBeaver 5.3.5, 5.1.6
- openjdk 10.0.2
- local database MariaDB 10.1.38

#### Connection specification:
- MySQL 5.5 and MariaDB 10.1.37
- MySQL and MariaDB
- tried with tunnel and without

#### Describe the problem you're observing:
I can connect to remote servers as I always could, but when I try to dump database using DBeaver, it shows that access is denied by database.
I tried same mysqldump parameters by command line with added '-p' and it worked.
Setting special Authentication for mysqldump in DBeaver did not help.
I tried with 'save password locally' and without.

```
-- Connecting to 149.202.xx.xx...
mysqldump: Got error: 1045: "Access denied for user 'root'@'212.91.xx.xx' (using password: YES)" when trying to connect
```

#### Steps to reproduce:
1. Edit MariaDB config and set there password, to make it possible to connect to database by command line from any user without password:
_/etc/mysql/conf.d/mysqldump.cnf_ or _/etc/mysql/mariadb.conf.d/50-client.cnf_
```
[mysqldump]
user=root
password=MySecretPassword
```
or:
```
[client]
user=root
password=MySecretPassword
```
2. Try to dump database of any remote host. No matter what password and where you set in DBeaver, it will send your password from MariaDB config to remote server.

**It should use password configured in DBeaver!**

I know that security experts will post that I should not store root password in file. It's development machine - there is nothing important in database.

#### Include any warning/errors/backtraces from the logs
Nothing special in logs.

**Comment by fluxsauce** [comment]
THIS explains some problems I've been having!

```
/usr/bin/mysqldump --add-drop-table --disable-keys --extended-insert -v --host=HOST --port=3306 -u USER DATABASE TABLE
Export started at Tue Oct 08 10:18:46 PDT 2019
-- Connecting to HOST...
mysqldump: Got error: 1045: Access denied for user 'USER'@'IP' (using password: NO) when trying to connect
Export finished at Tue Oct 08 10:18:46 PDT 2019
Process exit code: 2
```

Commented out my `.my.cnf` and...

```
/usr/bin/mysqldump --add-drop-table --disable-keys --extended-insert -v --host=HOST --port=3306 -u USER DATABASE TABLE
Export started at Tue Oct 08 10:24:22 PDT 2019
-- Connecting to HOST...
```

The problem is more specific; there was no password in my case, it overrode the username just fine but did not override the password even though it was a completely different host.

**Comment by uslss** [comment]
if issue is still actual for you - feel free to reopen the ticket

**Comment by fluxsauce** [comment]
Hi @uslss , I was able to replicate this with DBeaver 7.1.3 this morning with `~/.my.cnf`. I can't re-open someone else's ticket, but this bug is still happening and is still relevant.

**Comment by uslss** [comment]
@fluxsauce thanks for testing and information. Ticket is reopened

**Comment by kseniiaguzeeva** [comment]
A. Credentials to dump database are needed if a database credentials weren't save locally.
Steps:
1. Connect to PostgreSQL database not saving database password locally
2. Open a dump wizard
3. Start the dump without filling Authenticate field
Actual result: the dump fails.
Or is it expected?

B. Last used credentials are saved in dump wizard now for different databases.
Steps:
1. Connect to PostgreSQL database not saving database password locally
2. Open a dump wizard
3. Fill Authenticate field
4. Start the dump
5. Connect to MySQL database not saving database password locally
6. Open a dump wizard
7. Open Authenticate field
Actual result: PostgreSQL credentials are displayed there.

**Comment by kseniiaguzeeva** [comment]
verified. A separate ticket will be created for issues from the comment above.

**Comment by cccaballero** [comment]
I am getting this exact same issue with mariadb 10.3.31 and DBeaver 21.2.3 the DB dump fais with error:

```
mysqldump: Got error: 1045: "Access denied for user 'xxxx'@'xxxxxx' (using password: NO)" when trying to connect
```
Is not using password to connect to DB.
