### ISSUE TITLE
PostgreSQL - Cannot delete trigger in the Database Navigator window

### ISSUE THREAD

**Issue by NekoKoneko** [dbeaver/dbeaver#5358]
#### System information: 
- Server: Ubuntu 18.04.1
- Client: Windows 10 x64, DBeaver 5.3.5 64 bit (installer + JRE)

#### Connection specification:
- PostgreSQL 11.2
- Driver version: 42.2.5.jre7
- Direct connection
- Auto-commit mode

#### The problem:
Issuing Delete command on the trigger has no effect.

#### Steps to reproduce:
1. Create test table and trigger.
```
CREATE TABLE public.test (n NUMERIC);

CREATE FUNCTION public.trigger_fn()
RETURNS TRIGGER AS $$
BEGIN END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER test_trigger
BEFORE INSERT ON public.test
FOR EACH ROW
EXECUTE PROCEDURE public.trigger_fn();
```
2. Open the Query Manager window.
3. Go to the Database Manager window and select created trigger.
4. Press Del or select **Delete** command in the popup menu.
5. Press the **View Script** button in the opened window. The **SQL preview** box is empty. Press the **Persist** button.
6. The trigger disappears from the Database Manager window and the **Commit** command is added to the Query Manager window.
7. Select the Triggers node in the Database Manager window and press F5 or select **Refresh** command in the popup menu.
8. "Deleted" trigger is still there.

#### Include any warning/errors/backtraces from the logs
No error is logged in the Errors window.

**Comment by serge-rider** [comment]
Thanks for the bug report
