### ISSUE TITLE
[postgreSQL] Length and precision columns are reversed

### ISSUE THREAD

**Issue by nstremsd** [dbeaver/dbeaver#5363]
For Numeric columns : lenght was not use 

![image](https://user-images.githubusercontent.com/46815579/53482607-e3494c00-3a7f-11e9-8c37-81e9654838b7.png)
 
generate create code : 
CREATE TABLE adm.test (
	column1 numeric(2) NULL,
	column2 numeric NULL,
	column3 numeric(2) NULL
);

**Comment by serge-rider** [comment]
Property Length makes sense only for string data types and not used for numeric columns.
So this works as expected, isn't it?
