### ISSUE TITLE
PostgreSQL Column's Collation

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#5364]
Hi Serge

I experienced that there is no way to see or edit the collation of a text or varchar column in PostgreSQL.

This is becoming more and more important, because PostgreSQL supports ICU collations since version 10. When using ICU collations in PostgreSQL, you are forced to set the collation of any individual columns, because it is currently not possible to use an ICU collation as a default database collation.

So I think it would be a great feature, if collation can be viewed and edited in the columns property editor.

Cheers!

**Comment by serge-rider** [comment]
Good point.
We'll add column collations in read/write mode in the next version.
