### ISSUE TITLE
Editing multiple cells is slow

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#5365]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 5.3.5
- Java version: bundled
- Additional extensions: n/a

#### Describe the problem you're observing:
Editing multiple cells at once is way slower than copy-pasting to multiple cells. Ideally the former is not more difficult than the latter, hence the bug.

#### Steps to reproduce, if exist:

1. Select many cells, say 80
2. Press enter
3. Write a value
4. Press enter again to confirm the value.
5. All selected cells get the new value, but only after a few seconds where DBeaver is entirely frozen

#### Workaround:

1. Select the first cell
2. Press enter
3. Write a value
4. Press enter again to confirm the value.
5. The single cell gets the new value immediately
6. Copy the content
7. Select the other 79 cells
8. Paste
9. All selected cells get the new value immediately, without waiting like above.

**Comment by serge-rider** [comment]
Thanks for the bug report
