### ISSUE TITLE
[MariaDB] SQL editor show 0000-00-00 as NULL

### ISSUE THREAD

**Issue by sirber** [dbeaver/dbeaver#5369]
#### System information: 
- Operating system (distribution) and version
Windows 10 x64
- DBeaver version
3.5.3
- Java version
latest? 
- Additional extensions

#### Connection specification:
- Database name and version
MariaDB 10.1
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
Nope

#### Describe the problem you're observing:

![image](https://user-images.githubusercontent.com/3911428/53519176-b2c5da00-3aa0-11e9-9c81-7e28b573ead6.png)

HeidiSQL would show the column read_on as 0000-00-00

**Comment by serge-rider** [comment]
This is MySQL/Maria drivers limitations.
See #1127 for workarounds
