### ISSUE TITLE
Microsoft JDBC Driver for SQL Server doesn't work with SOCKS

### ISSUE THREAD

**Issue by stefan-squareweave** [dbeaver/dbeaver#5371]
#### System information: 
- Operating system (distribution) and version: Fedora 28
- DBeaver version: 5.3.5
- Java version: OpenJDK Runtime Environment (build 1.8.0_201-b09) (64 bit)
- Additional extensions: None to DBeaver

#### Connection specification:
- Database name and version: Microsoft SQL Azure (RTM) - 12.0.2000.8 (compatability level 140)
- Driver name: Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes

#### Describe the problem you're observing:

When I attempt to connect to the DB via an SSH SOCKS proxy I get the error message included in the section below. The issue is it's using my ISP's IP rather than the SOCKS server's one.

I get the same issue with the Azure SQL Server driver and SQL Server (old driver, MS). I can connect fine via SOCKS with the jTDS driver (this is what I'm currently using).

Related issues:

* https://github.com/dbeaver/dbeaver/issues/5217 - I have tried with a clean profile (deleting .dbeaver4) so this is the only connection I have in my list.
* https://github.com/dbeaver/dbeaver/issues/3046 - It may be that these MS drivers are using NIO and so can't currently be proxied. I'm not sure how to check this though.

#### Steps to reproduce, if exist:

1. Set up an Azure MSSQL instance so that it only accepts connections from a server called myjumphost.
2. Create a new connection using the Azure SQL Server or SQL Server drivers. Populate all the connection parameters (host, username etc.)
3. Set up a SOCKS proxy with SSH like: ssh -D 1080 myjumphost
4. Click the Network Settings (SSH, SSL...) and choose SOCKS Proxy. Enable this option and use 127.0.0.1 as the Host.
5. Click Test Connection. You will get the error popup below.

#### Include any warning/errors/backtraces from the logs

In the message below I've replaced my database name with 'MyDB' and the IP assigned by my ISP with '123.234.342.111'.

`Cannot open server 'MyDB' requested by the login. Client with IP address '123.234.342.111' is not allowed to access the server.  To enable access, use the Windows Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.  It may take up to five minutes for this change to take effect. ClientConnectionId:aef9a8dd-3e76-480d-ab26-616c5e8142c5
`

**Comment by devbas** [comment]
I am experiencing the same issue. Any update regarding this?

**Comment by devbas** [comment]
In my case, DBeaver didn't pick up the SOCKS proxy for some reason. So I added the SOCKS proxy hard-coded as a parameter to the conf/net.properties file of the DBeaver JRE: 

socksProxyHost=127.0.0.1
socksProxyPort=1080

Note that DBeaver will use this SOCKS Proxy for all your DBeaver connections. It also requires the SOCKS Proxy to be up and running before you start DBeaver.

**Comment by uslss** [comment]
#5217
