### ISSUE TITLE
Can't move directory to another

### ISSUE THREAD

**Issue by vdeapps** [dbeaver/dbeaver#5373]
#### System information: 
- Ubuntu 18.04.2 LTS
- 5.3.4

#### Describe the problem you're observing:
I use directories and subdirectories for manage my connections.
The problem is I can't move directory to another.
Can you fix it ? I have many connections to reorder.

#### Steps to reproduce, if exist:
Drag&drop directory to another.

Thanks.

**Comment by serge-rider** [comment]
@uslss we also need to test DnD in navigator in general.
