### ISSUE TITLE
Copy paste column

### ISSUE THREAD

**Issue by damienpolizzi** [dbeaver/dbeaver#5374]
Hello
In editing tables structure, I notice it was impossible to copy paste columns correctly.

I release that there were one similar issue 10 2016, but at this time it's not functioning.

I don't know if it could help but I work actually on oracle database.

Thanks for your Help

Damien POLIZZI

Operating system : Linux debian stable
Java Version 1.8
Version :
DBeaver Exasol Support
Version: 1.0.61.201902172105
(c) JKISS and Karl Griesser, 2016-2017.

**Comment by uslss** [comment]
cannot reproduce it for now. if it is still actual for you - feel free to reopen the issue
