### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by BobInCT** [dbeaver/dbeaver#5377]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by BobInCT** [comment]
Latest version of dBeaver, running a function and receiving the following error:
SQL Error [42703]: ERROR: column "y" does not exist
  Position: 92

What does "Position: 92" mean?  Unfortunately this is a fairly complicated script so troubleshooting is not simple

**Comment by serge-rider** [comment]
Please fill information about your environment (database ,driver).
Generally this looks like PostgreSQL error, position is a character position from the start of query. DBeaver automatically sets cursor on error position.

**Comment by BobInCT** [comment]
Postgres, ODBC driver.  I took a fresh look at this and have solved the problem.  This query is a stored procedure and you're correct, it was the 93rd character in the SP call - there are 10 parameters.  Thanks for the reply.

**Comment by serge-rider** [comment]
What is the reason to use ODBC driver? It has much less functions than standard PostgreSQL driver (including missing error positioning feature).

**Comment by BobInCT** [comment]
Now you made me go and look, I was guessing before.  I am using the Postgres driver but don't know offhand which version.  The cursor was sitting on the location of the error but I'm relatively new to Postgres so didn't realize what I was  looking at.
