### ISSUE TITLE
Sessions and Locks are mutually exclusive

### ISSUE THREAD

**Issue by qris** [dbeaver/dbeaver#5378]
#### System information: 
- Operating system (distribution) and version: Windows 7
- DBeaver version: 5.3.3
- Java version : 1.8.0_77
- Additional extensions

#### Connection specification:
- Database name and version: Postgres
- Driver name: JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

When I open Tools/Sessions, I then cannot open Tools/Locks (or vice versa). Choosing either menu item focuses the open tab (whichever was opened first) instead of creating a new one. It seems that they use the same unique ID somewhere, so they cannot both be open at the same time.

#### Steps to reproduce, if exist:

* Choose Tools/Sessions
* Choose Tools/Locks
* Observe that the Locks window does not open
* Cry
* File issue

**Comment by serge-rider** [comment]
Thanks for the bug report.
