### ISSUE TITLE
Switching tabs also changes active view in tab

### ISSUE THREAD

**Issue by qris** [dbeaver/dbeaver#5379]
#### System information: 
- Operating system (distribution) and version: Windows 7
- DBeaver version: 5.3.3.
- Java version: 1.8.0
- Additional extensions: None

#### Connection specification:
- Database name and version: Postgres
- Driver name: JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Switching tabs (using keyboard Ctrl+PageUp/PageDn) also switches the active sub-sub-tab or view within the tab, e.g. the left-hand tabs in table properties. This makes it impossible to compare two tables by flicking between them using the keyboard, because every flick changes the view when you come back to that tab. I suspect that the same key combination is bound to two different actions (previous tab and previous sub-sub-tab).

![image](https://user-images.githubusercontent.com/754175/53633705-26d2c000-3c10-11e9-97cc-9d14f12bdfe7.png)

#### Steps to reproduce, if exist:

* Open two tables (double-click or press F4)
* Flick between them using Ctrl+PageUp and Ctrl+PageDn
* Observe that the sub-sub-tab on the first one advances each time we flick to the second one.
* If you set the second one to a sub-sub-tab > 1, then we see it drift upwards each time we flick back to the first one.

**Comment by serge-rider** [comment]
Thanks for the bug report.
Tab switchers:
- <kbd>Ctrl+Tab</kbd> or <kbd>Ctrl+Shift+Tab</kbd> or <kbd>Ctrl+PgDown/PgUp</kbd> - Switch active editor
- <kbd>Alt+PgDown/PgUp</kbd> - Switch top editor tab (Properties/Data/ERD)
- <kbd>Ctrl+Alt+PgDown/PgUp</kbd> - Switch view tab (Columns/Constraints/etc)
