### ISSUE TITLE
Unable to start tar.gz package in alpine linux

### ISSUE THREAD

**Issue by hubbyist** [dbeaver/dbeaver#5380]
#### System information: 
- Linux 4.19.18-0-vanilla Alpine Linux 3.9 x86_64
- DBeaver version : 
   Community Edition 5.3.5 - Linux 64 bit (tar.gz archive)
- Java version : 
    openjdk version "1.8.0_191"
    OpenJDK Runtime Environment (IcedTea 3.10.0) (Alpine 8.191.12-r0)
    OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
- Additional extensions
    none

#### Connection specification:
- none

#### Describe the problem you're observing:
I am unable to start application. For a reference netbeans-10 which is also written in java is working flawlessly. So what is the proper way of starting dbeaver in alpine linux. I already checked permissions. Is there another method of starting dbeaver?

#### Steps to reproduce, if exist:
```
tar -xvzf ~/dbeaver-ce-5.3.5-linux.gtk.x86_64.tar.gz
cd ~/dbeaver
./dbeaver
```
#### Include any warning/errors/backtraces from the logs
```
ash: ./dbeaver: not found
```

**Comment by tchibatron** [comment]
What is output of the `ls ~/` command?

**Comment by hubbyist** [comment]
Sorry for delay

```
ls -l
total 180
drwxr-sr-x    4 protist  protist       4096 Mar  1 12:56 configuration
-rwxr-xr-x    1 protist  protist      73064 Feb 18 14:48 dbeaver
-rw-r--r--    1 protist  protist        430 Feb 18 14:49 dbeaver.desktop
-rw-r--r--    1 protist  protist        253 Feb 18 14:48 dbeaver.ini
-rw-r--r--    1 protist  protist       7919 Feb 18 14:48 dbeaver.png
drwxr-sr-x   23 protist  protist       4096 Mar  1 12:56 features
-rw-r--r--    1 protist  protist      35021 Feb 18 14:48 icon.xpm
drwxr-sr-x    2 protist  protist       4096 Mar  1 12:56 licenses
drwxr-sr-x    4 protist  protist       4096 Mar  1 12:56 p2
drwxr-sr-x    6 protist  protist      36864 Mar  1 12:56 plugins
-rw-r--r--    1 protist  protist       1767 Feb 18 14:49 readme.txt
```

**Comment by tchibatron** [comment]
I've reproduced this issue on docker image. Looks like shell can not find all dependencies for Dbeaver. [()](https://superuser.com/questions/1176200/no-such-file-when-it-exists). Need to think how to solve it.

**Comment by tchibatron** [comment]
If I am not mistaken, alpine linux does not have graphical server. In this case it is not possible to run DBeaver on it, because DBeaver is graphical tool.

**Comment by uslss** [comment]
if issue is still actual - feel free to reopen it.

**Comment by angelacastaneda** [comment]
Binaries aren't working on alpine 3.19 with the same error that hubbyist had. Building from source also didn't work:
https://builds.sr.ht/~acsqdotme/job/1178042
