### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by cphalpin** [dbeaver/dbeaver#5381]
#### System information: 
- Operating system (distribution) and version
Ubuntu Cosmic
- DBeaver version
5.3.5
- Java version
openjdk version "1.8.0_191"
- Additional extensions
N/A

#### Describe the problem you're observing:
The splash screen appears briefly then disappears before loading is complete. I have to kill the dbeaver processes to try again.

#### Include any warning/errors/backtraces from the logs

[dbeaver.log](https://github.com/dbeaver/dbeaver/files/2919463/dbeaver.log)

**Comment by serge-rider** [comment]
When this problem appeared? Did you run DBeaver in the past or it is the first time?

Please check https://github.com/dbeaver/dbeaver/wiki/Reset-workspace article, perhaps reinstall and workspace resetting will help.

**Comment by cphalpin** [comment]
I've run it many times, this is possibly the first time since the last update. Resetting the workspace seems to have done the trick. Thanks very much.
