### ISSUE TITLE
Could not create the view: org.jkiss.dbeaver.core.databaseOutput

### ISSUE THREAD

**Issue by VittorioZinno** [dbeaver/dbeaver#5382]
#### System information: 
Operating System: 
Windows 10 10.0
Architecture: 
amd64

dbeaver-ce-5.3.5-win32.win32.x86_64

JVM: Java HotSpot(TM) 64-Bit Server VM (25.77-b03, mixed mode)
Java: version 1.8.0_77, vendor Oracle Corporation

Error opening the Output Window (View)

![image](https://user-images.githubusercontent.com/7655590/53643451-5d223680-3c34-11e9-9caf-254bd345a325.png)

[stack.zip](https://github.com/dbeaver/dbeaver/files/2919742/stack.zip)

**Comment by serge-rider** [comment]
This view was deprecated a time ago. I can't figure out how do you open it.

Currently you can open server output view only as a tab in SQL editor (ctrl+shift+o).

**Comment by VittorioZinno** [comment]
Thanks (ctrl+shift+o) for server output view works perfect.

To open the other, not working Output window...

![image](https://user-images.githubusercontent.com/7655590/53724767-e6bb4980-3e6a-11e9-857f-7db57a55046b.png)


![image](https://user-images.githubusercontent.com/7655590/53724728-cb503e80-3e6a-11e9-8a84-3cb5f66913ba.png)
