### ISSUE TITLE
Table filter is applied to all databases with the same schema

### ISSUE THREAD

**Issue by reponzo01** [dbeaver/dbeaver#5383]
#### System information: 
- Windows 10 Enterprise 10.0.17134 Build 17134
- DBeaver version 5.3.5
- Java version 1.8.0_144

#### Connection specification:
- MS SQL Server
- MS Driver

#### Describe the problem you're observing:
In our environment, we have multiple databases with the same schema under the same SQL server connection. Each of our clients have their own databases that we host. We don't use multi-tenant databases, but rather one database per client.

If I apply a table filter to one database, all of the databases will reflect that filter since that table filter is associated with a schema (in this case, dbo). Can table filters be isolated to that specific database? I know global filters are already supported. And I know that schema filters work at the database level. Would it be possible to have table filters work at the database level as well?

#### Steps to reproduce:
1. Duplicate your database several times so that it contains the same schemas/tables etc.
2. Apply a Table filter to one of those databases.
- Right-click on Tables -> Filter -> Configure "Table" filters. Or select a table -> right-click -> Filter -> Hide it.
3. Every other database will now reflect that same filter (you may need to right-click -> Refresh).
4. Disable the filter and it will be disabled from the other databases as well.

In essence, a normal table filter behaves like a global filter. Can it be tied to a specific database so I can configure a different filter on a different database even if it has the same schema?

Thanks! DBeaver is amazing!

**Comment by serge-rider** [comment]
Thanks for the bug report. 
It is not just SQL Server specific but happens with all multi-database engines.

**Comment by reponzo01** [comment]
Thanks for addressing it so quickly! You guys are the best!
