### ISSUE TITLE
Logical foreign keys

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#5384]
Besides logical primary key we need to support logical FKs.
This will allow to navigate by references and view ref value in panel value viewer.

Also we need to support logical keys for NoSQL data types (json).

**Comment by p91paul** [comment]
with "logical keys" here you mean key known to DBeaver but not actually present in the database? That would be awesome :smiley:

**Comment by serge-rider** [comment]
@p91paul Yep )

**Comment by uslss** [comment]
verified

**Comment by krkhnh** [comment]
I'm eager to try this feature. But where is it? I can't find it in the wiki page.

**Comment by bloodywing** [comment]
@krkhnh in the dataview, right click a single cell. Then View/Format and Logical structure and view settings.

I was searching in the wrong place as well, I was looking in the Properties in foreign key if there was a new option :)

**Comment by serge-rider** [comment]
@krkhnh Wiki article will be ready in near time. This feature is still in the beta test.
Also there is #6314 which is an additional "sub-feature" of this one.
