### ISSUE TITLE
MS SQL Server: Login failed for user ''.

### ISSUE THREAD

**Issue by albing** [dbeaver/dbeaver#5385]
#### System information: 
- mac os 10.14.3
-DBeaver Core	5.3.5.201902181142	org.jkiss.dbeaver.core.feature.feature.group	JKISS
- java 1.8.0_152 (bundled with installer in download)
- No additional extensions

#### Connection specification:
- SQLServer 2012
- mssql-jdbc-7.1.4.jre8-preview
- no tunnels or proxies

#### Describe the problem you're observing:
Error message `Login failed for user ''.` when user name field is not blank and `Active Directory - Passwword` is selected

#### Steps to reproduce, if exist:
- New connection
- enter host/post/db/user/pass
- select `Active Directory - Passwword` for authentication
- Press `Test Connection...`

#### Include any warning/errors/backtraces from the logs
!ENTRY org.jkiss.dbeaver.model 2 0 2019-02-28 15:20:31.966
!MESSAGE Project 'General' not found in registry

**Comment by serge-rider** [comment]
Currently active directory authentication supported only for Azure driver.
Please try it (it should work for regular SQL Server too)

**Comment by JesseCastro** [comment]
FYI @serge-rider your suggested fix did not work for me.  I had same error as OP.  I still get this error message when using Azure driver.  There is no observable difference to me between using Azure vs MSSQL drivers.  I still get the `Login failed for user ''.` message when using Active Directory - Password.

**Comment by serge-rider** [comment]
@JesseCastro main difference between Azure and SQL Server drivers is AD integration library:
![image](https://user-images.githubusercontent.com/6398845/55277288-7c81b180-530f-11e9-9948-ba5038e71467.png)

Do you have it? IF yes please post error/debug logs (https://github.com/dbeaver/dbeaver/wiki/Log-files) with auth error.

**Comment by nkev** [comment]
I also get the same error on Windows "Login failed for user x" when connecting to AWS RDS (SQL Server 2017) using SQL Server authentication.

I can successfully connect  via SSMS with same connection settings but not DBeaver Enterprise 6.1.0:

![image](https://user-images.githubusercontent.com/5410916/64143022-b7a18700-ce51-11e9-92e2-163a5009284e.png)

The driver is `com.microsoft.sqlserver.jdbc.SQLServerDriver` which comes with DBeaver Enterprise 6.1.0

**Comment by kseniiaguzeeva** [comment]
Is it still actual for you? If yes, tell which DBeaver version do you use now?

**Comment by nkev** [comment]
The problem is fixed for me in DBeaver Enterprise v7.0 on Mac Catalina, using `Microsoft JDBC Driver for SQL Server (MSSQL)`

**Comment by kseniiaguzeeva** [comment]
Great!
