### ISSUE TITLE
COLLATE is missing in DDL Creation. 

### ISSUE THREAD

**Issue by dba0522** [dbeaver/dbeaver#5386]
#### System information: 
- MAC
- DBeaver 5.3.5
- SQL Server 2012

#### Describe the problem you're observing:
Does not look like DBeaver is properly supporting the COLLATE definition at a column level.

#### Steps to reproduce, if exist:
Create a table as follows:

CREATE TABLE dbo.SIVO_Status
(
 Record_Type    VARCHAR(10)   COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
 Load_Status    VARCHAR(20)   COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
 Spid           SMALLINT      NOT NULL,
 Username       NVARCHAR(128) NOT NULL, 
 Last_Updated   DATETIME      NOT NULL,
 PRIMARY KEY (Record_Type)
)
GO

ALTER TABLE dbo.SIVO_Status 
ADD CONSTRAINT ck_SIVO_Record_Type
CHECK (Record_Type IN  ('SIVO'))
GO

ALTER TABLE dbo.SIVO_Status 
ADD CONSTRAINT ck_SIVO_Load_Status 
CHECK (Load_Status IN  ('FULL','INCR','READY'))
GO

Now go generate the DDL on the table, it does not reproduce.

Output from DBeaver

-- Drop table

-- DROP TABLE WMTibcoEcommerce.dbo.SIVO_Status

CREATE TABLE WMTibcoEcommerce.dbo.SIVO_Status (
	Record_Type varchar(10) NOT NULL,
	Load_Status varchar(20) NOT NULL,
	Spid smallint NOT NULL,
	Username nvarchar(128) NOT NULL,
	Last_Updated datetime NOT NULL,
	CONSTRAINT PK__SIVO_Sta__87280E1683A050DD PRIMARY KEY (Record_Type)
) GO
ALTER TABLE WMTibcoEcommerce.dbo.SIVO_Status WITH NOCHECK ADD CONSTRAINT ck_SIVO_Record_Type CHECK ([Record_Type]='SIVO') GO
ALTER TABLE WMTibcoEcommerce.dbo.SIVO_Status WITH NOCHECK ADD CONSTRAINT ck_SIVO_Load_Status CHECK ([Load_Status]='READY' OR [Load_Status]='INCR' OR [Load_Status]='FULL') GO

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by dba0522** [comment]
Serge-Rider,

The update now puts COLLATE on every columns, which I think most people would not want.   I recommend only adding collate to the columns if define differently the the database default.  The database default COLLATE can be found here.


SELECT COLLATION_NAME  FROM master.sys.Databases where name = '<DBNAME>'

Thanks
