### ISSUE TITLE
Can't modify data type with hsqldb driver

### ISSUE THREAD

**Issue by gelinp** [dbeaver/dbeaver#5388]
I used a libreoffice  extern connection with HSQLDB driver. Before I update my PC I usually edit my database but after a new install I can't edit columns data type ... I suspect a java version problem, because I modify after updated my new PC ...

#### System information: 
- Operating system (distribution) and version : Linux Mint 19
- DBeaver version : 5.3.5
- java version "1.8.0_191" / Java(TM) SE Runtime Environment (build 8.0.5.25 - pxa6480sr5fp25-20181030_01(SR5 FP25)) / IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20181029_400846 (JIT enabled, AOT enabled) / OpenJ9   - c5c78da
OMR      - 3d5ac33 / IBM      - 8c1bdc2) / JCL - 20181022_01 based on Oracle jdk8u191-b26

#### Connection specification:
- Database name and version : Typodoc (A personal database connected as LibreOffice extern database)

- Driver name : HSQLDB server 2.4.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
- When I add a new column I can't edit data type : it's read only with default type as VARCHAR ... 
- Dbeaver could fin automatically class names into the jar file of the driver. But I can't select org.hsqldb.jdbc.JDBCDrive or the other org.hsqldb.jdbcDriver elsewhere I have to download again the jar file of the driver ... Then class name is empty and I an connect ... but data type is read only ! Can't understand this procedure ...

#### Steps to reproduce, if exist
Run HSQLDB server database
Connect HSQLDB driver server and connect with default : "SA" as ident / empty passwd

#### Include any warning/errors/backtraces from the logs
See linked log file :
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/2921949/dbeaver.log)

**Comment by gelinp** [comment]
![capture d ecran_2019-03-02_20-26-38](https://user-images.githubusercontent.com/48149700/53686624-d8b1df80-3d29-11e9-9f3b-b03d1806e219.png)

**Comment by serge-rider** [comment]
It should be editable: 
![image](https://user-images.githubusercontent.com/6398845/55276905-cb791800-530a-11e9-8570-96222ef8fea5.png)

(just click on type name in dialog or later in type column).

**Comment by gelinp** [comment]
No it's not closed ... The problem is not resolve, dialog box to create new column field doesn't display list choice for data type, I can't select other data type else VARCHAR. and Data type is readonly !

I thing there is a parameter to adjust with HSQLD JDBC driver ... But any idea to find it ?

Thank you
Patrick

![Capture d’écran_2019-12-25_17-31-44](https://user-images.githubusercontent.com/48149700/71448465-7f91bd00-273c-11ea-89a4-08b72a5e602b.png)

**Comment by gelinp** [comment]
Problem not resolved with dbeaver Version 6.3.3.202001191557and pilote HSQL Server version 2.5.0...
I can't edit data type when I create a new table column (it's only frozen VARCHAR typevalue, without any list ...). Smae problam with to modify existing type of empty table column or to add a new one to into an existing table ... 

Note with last version 6.3.3 i can update 'Not null' and 'autovalue' boxcases ...It's better ...

Is any one to help ?
