### ISSUE TITLE
Handling of sql scripts with size over 10MB is super slow

### ISSUE THREAD

**Issue by archenroot** [dbeaver/dbeaver#5391]
#### System information: 
- Gentoo Linux
- DBeaver version - 5.3.0
- Java version - Oracle JDK 8
- Additional extensions - vmargs 4096

#### Describe the problem you're observing:
I have insert statement of size 46MB, dbeaver is stuck for few minutes on opening or manipulating the file, even when SQL parser is non this is too slow.

**Comment by serge-rider** [comment]
It is a known issue. Unfortunately working with huge SQL scripts is still an issue in DBeaver (mostly because of memory-hungry syntax highlighter).
We are highly dependent on Eclipse platform here.
