### ISSUE TITLE
Netezza JDBC error

### ISSUE THREAD

**Issue by lavalex** [dbeaver/dbeaver#5392]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 5.3.5 Community Edition
- Java version Whatever comes with DBeaver
- Additional extensions

#### Connection specification:
- Database name and version Netezza 7.2.1
- Driver name JDBC from IBM
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Steps to reproduce, if exist:
When testing connection, getting this error:

Unexpected driver error occurred while connecting to database
  
  java.lang.NullPointerException

Driver works fine from a Java program, but not from DBeaver.

**Comment by serge-rider** [comment]
Sorry for late reply.
Could you attach error/debug logs with this error? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by uslss** [comment]
there is no update more than a month. Ticket closed.  
If issue is still actual feel free to reopen the ticket or create a new one.
