### ISSUE TITLE
Content is hidden by scroll bar

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#5398]
#### System information: 
- Operating system (distribution) and version Linux Mint
- DBeaver version 5.2.5

#### Describe the problem you're observing:

![__](https://user-images.githubusercontent.com/799021/53742975-7d572d00-3ea2-11e9-91c6-bd358f4d0f1b.jpg)

#### Steps to reproduce, if exist:
1a. Scroll vertical bar to the bottom
1b. Scroll horizontal bar to the right direction
2 see that last row is hidden

expected behavior: you should scroll data a bit more by height of horizontal bar
Thus last row will be over horizontal scroll bar and not hidden

**Comment by KES777** [comment]
this bug forces me to drop horizontal bar while scrolling.
wait while horizontal bar disappeared, 
see the data
then continue scrolling
...

**Comment by serge-rider** [comment]
This happens only on Linuxes. We need to add some extra space in the bottom after last line of grid.

**Comment by tomchiverton** [comment]
Still present, Ubuntu 18.04 LTS. Is there not even a work around yet ? How do you "drop horizontal bar while scrolling" ?

**Comment by dirkniblick** [comment]
This is not unique to Linux. The scroll-bars-getting-in-the-way issue is documented in #1570 for Windows which was closed over two years ago as an “Eclipse/SWT theming issue” which would be “fixed in after E4.7 migration...in next couple of months”.

**Comment by michalk-k** [comment]
Still not fixed.

BTW is it possible to make those scrollbars not disappearing? Right now those are appear when hovering mouse over them. I don't know if it's Ubuntu related issue but other applications shows scrollbars persistently.

**Comment by the-ge** [comment]
Also, the scrollbar make sorting by the last column impossible:
![output](https://user-images.githubusercontent.com/6468893/77328709-95a41f00-6d25-11ea-8cc5-e95f0a55a3a6.gif)
_(DBeaver 7.0.0.202002292132 and 7.0.1.202003211804, Kubuntu 19.10, KDE PLasma 5.18.3)_

**Comment by uslss** [comment]
seems that issue is fixed

**Comment by brylie** [comment]
I am experiencing this issue with DBeaver version 7.3.2

**Comment by michal-bartak** [comment]
Yes, me too (Kubuntu 20.04)
![obrazek](https://user-images.githubusercontent.com/7868445/104741480-904b1180-5749-11eb-8be3-e106d312aaf1.png)

**Comment by skytwosea** [comment]
Issue is still happening: Kubuntu 24.04
