### ISSUE TITLE
focus is changed

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#5399]
#### System information: 
- Operating system (distribution) and version linux mint 18.3
- DBeaver version 5.3.5

#### Connection specification:
- Database name and version postgres 10.4

#### Describe the problem you're observing:
1. Open sql editor, write and run query. 
2. move focus to result
3. open sql editor, write and run query
4. move focus to result
5. switch back to first sql editor, focus is moved to sql
6. switch back to second sql editor, focus also is moved to sql

expected: focus should be on that element where we leave it

**Comment by AlessioGiambrone** [comment]
Maybe this is the same problem; it happens to me that
1. Open sql editor, write and run query.
2. move focus to result
3. doubleclick/select/edit a value
4. click to move focus to sql editor
5. writing something while focusing sql editor results in writing inside the value at point 3 and not in the sql editor 

Instead, *double-click* permits changing focus for real.

OS Debian, DBeaver 5.3.3

**Comment by serge-rider** [comment]
It is a bug in spreadsheet (there was forced focus change after inline editor close).
Thanks for the bug report.

**Comment by uslss** [comment]
verified

**Comment by AlessioGiambrone** [comment]
Thank you!
