### ISSUE TITLE
Incorrect display of epoch timestamps

### ISSUE THREAD

**Issue by photondetector** [dbeaver/dbeaver#5402]
#### System information: 
- Operating system (distribution) and version: 10.13.6 (17G5019)
- DBeaver version: 5.3.5.201902181142
- Java version: 1.8.0_65-b17
- Additional extensions: N/A

#### Connection specification:
- Database name and version: Amazon Redshift 1.0.6246
- Driver name: RedshiftJDBC42-1.2.16.1027
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Epoch timestamps on Redshift do not display correctly: missing the required trailing ' BC', which makes it impossible to write queries based on returned values.

#### Steps to reproduce, if exist:
```sql
-- 1
-- Create table
DROP TABLE IF EXISTS dbeaver_bug_demo_2;

CREATE TABLE dbeaver_bug_demo_2 (
  id SMALLINT,
  ts TIMESTAMP
);


-- 2
-- Load some data with explicit commit (missing format string is deliberate)
INSERT INTO dbeaver_bug_demo_2 (id, ts) VALUES
  (1, TO_TIMESTAMP('2019-01-01 00:00:00', '')),
  (2, TO_TIMESTAMP('2019-01-01 00:00:00', '')),
  (3, TO_TIMESTAMP('2019-01-01 00:00:00', '')),
  (4, TO_TIMESTAMP('2019-01-01 00:00:00', '')),
  (5, TO_TIMESTAMP('2019-01-01 00:00:00', ''))
;

COMMIT;


-- 3
-- Load data in DBeaver
SELECT * FROM dbeaver_bug_demo_2;
/*
id    |ts                 
------|-------------------
     1|0001-01-01 00:00:00
     2|0001-01-01 00:00:00
     3|0001-01-01 00:00:00
     4|0001-01-01 00:00:00
     5|0001-01-01 00:00:00
*/


-- 4
-- Use value reported by DBeaver to find data
SELECT * FROM dbeaver_bug_demo_2 WHERE ts='0001-01-01 00:00:00';
-- DBeaver
/*
id    |ts    
------|------
*/

-- psql
/*
 id | ts 
----+----
(0 rows)
*/


-- 5
-- Try from psql
SELECT * FROM dbeaver_bug_demo_2;
/*
 id |           ts           
----+------------------------
  1 | 0001-01-01 00:00:00 BC
  2 | 0001-01-01 00:00:00 BC
  3 | 0001-01-01 00:00:00 BC
  4 | 0001-01-01 00:00:00 BC
  5 | 0001-01-01 00:00:00 BC
(5 rows)
*/


-- 6
-- Use value reported by psql to find data
SELECT * FROM dbeaver_bug_demo_2 WHERE ts='0001-01-01 00:00:00 BC';
-- DBeaver
/*
id    |ts                 
------|-------------------
     1|0001-01-01 00:00:00
     2|0001-01-01 00:00:00
     3|0001-01-01 00:00:00
     4|0001-01-01 00:00:00
     5|0001-01-01 00:00:00
*/

-- psql
/*
 id |           ts           
----+------------------------
  1 | 0001-01-01 00:00:00 BC
  2 | 0001-01-01 00:00:00 BC
  3 | 0001-01-01 00:00:00 BC
  4 | 0001-01-01 00:00:00 BC
  5 | 0001-01-01 00:00:00 BC
(5 rows)
*/
```

#### Include any warning/errors/backtraces from the logs

N/A

**Comment by rockycastaneda** [comment]
I had a similar issue when filtering dates.

Using Eclipse Plugin
DBeaver Universal Database Manager
Version: 5.3.5.201902172105

![screen shot 2019-03-05 at 2 04 12 am](https://user-images.githubusercontent.com/11282510/53797710-96380080-3eeb-11e9-868b-e020efa9998f.png)

**Comment by serge-rider** [comment]
@photondetector This issue also can be reproduced with simple
```sql
select TO_TIMESTAMP('', '')
```
In order to see timestamps in native format (with epoch postfix) enable following option in preferences (global or connection-specific):
![image](https://user-images.githubusercontent.com/6398845/53798203-cfeb2480-3f48-11e9-909c-7b9b946479bd.png)

@rockycastaneda Your case is a bit different. most likely time shift happens because of difference between client and server timezone.

**Comment by rockycastaneda** [comment]
@serge-rider 
Here is another screenshot when i used sequelpro to view my data.

It returned the correct records.

![screen shot 2019-03-05 at 2 50 38 am](https://user-images.githubusercontent.com/11282510/53800469-a7840b80-3ef1-11e9-85f0-34a5d4e851ad.png)

**Comment by serge-rider** [comment]
@rockycastaneda please create a separate ticket for this

**Comment by photondetector** [comment]
@serge-rider,

> @photondetector This issue also can be reproduced with simple
> 
> ```sql
> select TO_TIMESTAMP('', '')
> ```

100% correct, however that alone doesn't really convey the full repercussions of the issue. :D 

> In order to see timestamps in native format (with epoch postfix) enable following option in preferences (global or connection-specific):
> ![image](https://user-images.githubusercontent.com/6398845/53798203-cfeb2480-3f48-11e9-909c-7b9b946479bd.png)

Unfortunately I tried that before reporting the bug and it exhibits the same behavior. (It added IIRC 4  places of float precision to the still-incorrect TS.)
