### ISSUE TITLE
toolbox icons looks the same

### ISSUE THREAD

**Issue by liorg2** [dbeaver/dbeaver#5410]
#### System information: 
- Operating system ubuntu 14 mate
- DBeaver version 5.3.5.201902172105
- Java version 

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

- Additional extensions none

#### Connection specification:
- Database name and version mariadb
- Driver name: org.mariadb.jdbc.Driver - 10.0.38-MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
all icons look the same
#### Steps to reproduce, if exist:
![image](https://user-images.githubusercontent.com/1691647/53819578-de4e3600-3f72-11e9-9dcc-3fc5e9cfe568.png)

**Comment by serge-rider** [comment]
It is a know glitch which may happen after series of version upgrades and "unsafe" application shutdowns.
This can be fixed by UI settings reset: https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings
