### ISSUE TITLE
Incorrect records returned on select with Date field where clause

### ISSUE THREAD

**Issue by rockycastaneda** [dbeaver/dbeaver#5411]
#### System information: 
- Operating system (distribution) and version
ECLIPSE PLUGIN
- DBeaver version
DBeaver Universal Database Manager
- Java version 
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
- Additional extensions

#### Connection specification:
- Database name and version
Aurora MySQL on AWS
- Driver name
Using MySQL 8.x
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
OpenVPN Connect v2.5.0

#### Describe the problem you're observing:

Tried to do a select with a where clause for a particular date and it was returning the wrong set of records.

Please see attached images
1st image is from DBeaver
![screen shot 2019-03-05 at 2 04 12 am](https://user-images.githubusercontent.com/11282510/53820635-04e38100-3f21-11e9-94e6-657db0dde48e.png)

2nd image is from SequelPro
![screen shot 2019-03-05 at 2 50 38 am](https://user-images.githubusercontent.com/11282510/53820661-0f9e1600-3f21-11e9-8655-0ee571fd47ad.png)

**Comment by mkgrgis** [comment]
https://github.com/dbeaver/dbeaver/issues/5402 ?

**Comment by rockycastaneda** [comment]
I was asked to create a new report for this issue.  Sorry

**Comment by rockycastaneda** [comment]
Guys, tested it with MySQL driver not the MySQL 8.x and the issue seems to go away now.  I will consider this issue closed.  Looks like AWS Aurora is only compatible with MySQL 5.7 and lower.  I might be wrong but with the change of driver, it seems to have fixed the issue.

**Comment by rockycastaneda** [comment]
Issue closed.
