### ISSUE TITLE
Dbeaver keyboard shortcuts are "azerty" while everything else is on a "qwerty" layout.

### ISSUE THREAD

**Issue by GuillaumeLegoy** [dbeaver/dbeaver#5412]
#### System information: 
- Operating system (distribution) and version: Linux Ubuntu 18.04.2 LTS
- DBeaver version: 5.3.5
- Java version:
    openjdk version "10.0.2" 2018-07-17
    OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
    OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

#### Describe the problem you're observing:
When I write a SQL query in the editor, the correct QWERTY layout applies. However, all keyboard shortcuts follow a AZERTY layout. For instance q becomes a.

**Comment by mkgrgis** [comment]
Keymap https://fr.wikipedia.org/wiki/Discussion:AZERTY#/media/File:Azerty_fr.svg

**Comment by mkgrgis** [comment]
I think the right princip for keymaps must be
Latin (AZERTY QWERTZ QWERTY) -> key character from _current_ layout
Non latin -> key code for QWERTY if current layout is non-latin
Is it non-normal situation?

**Comment by GuillaumeLegoy** [comment]
Thanks for your reply. I'm not sure I understand: when I type in the editor my keyboard follows the QWERTY layout (which is normal), but shortcuts are somehow AZERTY (I need to press ctrl + q to select all for instance instead of ctrl + a), and I'd love to know how to change that. Also it only happens on my Linux install and not on Windows.

I searched and didn't find an option to change the keyboard in preferences.

**Comment by mkgrgis** [comment]
It seems, shortcuts follow system layout, but not layout of current DBeaver window. It look like problem from DBeaver. For example if you switch from fr_CA  (AZERTY) to de_DE (QWERTZ) layout, shortcuts must be modified for new keymap from layout. In Java application there is any similar problem, for example in JOSM.

**Comment by serge-rider** [comment]
This is a bug in Eclipse platform (https://bugs.eclipse.org/bugs/show_bug.cgi?id=533395)
It is already fixed in the recent Eclipse, will be fixed in DBeaver automatically once we'll upgrade to it (after 6.0 release).

**Comment by uslss** [comment]
Closed without testing.
