### ISSUE TITLE
Error repeats until I reconnect

### ISSUE THREAD

**Issue by majestique** [dbeaver/dbeaver#5413]
#### System information: 
- Windows 10
- DBeaver version 5.35
- Java version latest
- Additional extensions 

#### Connection specification:
- Database name and version: PostgreSQL 10.7
- Do you use tunnels or proxies (SSH, SOCKS, etc)? None

#### Describe the problem you're observing:
Whenever there's any type of error occurs in my query (my own fault), any query thereafter will show the same error until I reconnect.

#### Steps to reproduce, if exist:
Just create any erroneous query and future queries will result in the same error, just need to reconnect.

**Comment by mlt** [comment]
Out of curiosity... have you tried to issue *rollback*? Do you have auto-commit enabled? I don't recall if there is "auto-rollback" in dbeaver.

**Comment by majestique** [comment]
I just enabled auto-commit and it works fine now, thanks!

**Comment by mlt** [comment]
I'm not sure if that is the only reason to enable auto-commit. I see there is *Error handling* in *Preferences → Database → Editors → SQL Editor → SQL Processing → Scripts*. In my default config, it says *Stop + rollback*. I think it should be enough. Otherwise it is worth re-opening this one.

**Comment by majestique** [comment]
It was already stop + rollback(I didn't change it):
![image](https://user-images.githubusercontent.com/19336285/53939484-09668180-4068-11e9-9502-f5b2282070e1.png)
