### ISSUE TITLE
PG SP header shall be reattached (if not shown in editor) while saving

### ISSUE THREAD

**Issue by mlt** [dbeaver/dbeaver#5415]
#### System information: 
- Windows 10 64 bit (1709)
- DBeaver version 6.0.0.201902260514 (built from git) somehow released in the future on March 11, 2019 (it is 5th today)
- Java version javac 1.8.0_201
- Additional extensions None

#### Connection specification:
- PostgreSQL 11.2 64 bit
- Driver name postgresql-42.2.5.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Direct connection

#### Describe the problem you're observing:

*Persist Changes* preview shows incomplete SQL and as a result fails to save changes if I start editing stored procedure source while having "Show header" turned off.

#### Steps to reproduce, if exist:

1. Open any stored procedure by double clicking on it and navigating to *Source* tab.
2. Turn *Show header* off
3. Start editing
4. Try to save with <kbd>Ctrl+S</kbd> or anyhow else.
5. *Persist Changes* dialog shows trimmed down SQL without header
6. Clicking *Show header* makes no difference after failed save attempt.

#### Include any warning/errors/backtraces from the logs
I'm not sure where it picked "record"... perhaps something mine, but everything works if I remember to press *Show header*. It is just extremely annoying issue.
```java
2019-03-05 22:38:33.424 - null
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [42601]: ERROR: syntax error at or near "record"
  Position: 16
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:140)
	at org.jkiss.dbeaver.model.impl.edit.AbstractObjectManager.executePersistAction(AbstractObjectManager.java:46)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.executeCommands(AbstractCommandContext.java:186)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:108)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.saveCommandContext(EntityEditor.java:297)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.access$0(EntityEditor.java:286)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$SaveJob.run(EntityEditor.java:1002)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "record"
  Position: 16
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:344)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:137)
	... 8 more
```

**Comment by mlt** [comment]
I probably would not bother turning off header, but PG reports error line number relative to a header. Turning it off makes it easier to pinpoint the line without looking around.

What would be a "killer feature" is to show negative line numbers in editor for a header.

Also it is annoying that all changes are quietly lost if turning *Show header* mid-edit.

**Comment by mlt** [comment]
Perhaps making editor read only would be enough when no headers are shown?
```diff
diff --git a/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/ui/editors/PostgreSourceViewEditor.java b/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/ui/editors/PostgreSourceViewEditor.java
index ef41f30c9..a207338d8 100644
--- a/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/ui/editors/PostgreSourceViewEditor.java
+++ b/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/ui/editors/PostgreSourceViewEditor.java
@@ -48,7 +48,7 @@ public class PostgreSourceViewEditor extends SQLSourceViewer<PostgreScriptObject
     protected boolean isReadOnly()
     {
         PostgreScriptObject sourceObject = getSourceObject();
-        if (sourceObject instanceof PostgreProcedure || sourceObject instanceof PostgreTrigger || sourceObject instanceof PostgreViewBase) {
+        if ((sourceObject instanceof PostgreProcedure && !isInDebugMode()) || sourceObject instanceof PostgreTrigger || sourceObject instanceof PostgreViewBase) {
             return false;
         }
         return true;
```

**Comment by mlt** [comment]
I think this almost works. I would also change [refreshPart](https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditorNested.java#L191) to query a user for unsaved changes (`isDirty()`) if any and return boolean if change shall be proceeded and not cancelled [leaving check buttons unchanged](https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/ui/editors/PostgreSourceViewEditor.java#L88-L107).

**Comment by serge-rider** [comment]
Not sure about readOnly checking. This may frustrate some people..

Could you make a pull request? I'm not quite sure I understand the actual change.
In fact I still hope that they'll make new debugger API in PG12. This will solve issue with header.

**Comment by mlt** [comment]
I am not ready for PR on this one so I'll try to explain the issue better. As I stated earlier, the need for this for me stems from the fact that error line numbers reported whenever by PG are counted from a function body so, unless it is ever possible to offset line numbering within Eclipse Platform editor (would close the issue for me), it is easier to find exact place by temporarily turning headers off. So this is not about debugging mode per se. Once I found a problem, however, it is easy to start editing away and to forget that headers are off until the moment I try to persist changes. Of course, it will fail to do so without a header. Then, I click on *Show header* &hellip; and my edits are gone. Another workaround without read-only editor would be to cut edited `$function$` body out and replace that within full function definition. Maybe that is the way to go as I understand users might want to change code while debugging, but&hellip; how are they going to persist changes? Manually cutting and pasting?

I don't know Eclipse Platform good enough&hellip; the first idea would be to do
```java
if (isDirty()) {
        	int res = ((EntityEditor) ((MultiPageEditorSite) editorSite).getMultiPageEditor()).promptToSaveOnClose();
```
in `refreshPart`. I recall I saw a different dialog somewhere in the code asking whether to revert changes that perhaps is more appropriate&hellip; got to find it.

But once again, perhaps, everything could be solved by automatically cutting/pasting `$function$` body. Though changes outside of the body would still be silently lost. Also I don't know what is the deal with other databases.

**Comment by mlt** [comment]
I hope previous post makes sense. I think the best strategy (at least for PG) would be to silently copy and replace function body while coming back to full function definition from debug mode, but ask whether to revert changes when turning *Show headers* off.
I'll work on it.

**Comment by mlt** [comment]
Why is this closed? Today, I had to turn of header to find the line I was getting PG debug message about. I started editing right away just to realize I can't save. It is frustrating. If it was read-only, I would switch header back.
