### ISSUE TITLE
[feature] Huawei Data Lake Insight connectivity

### ISSUE THREAD

**Issue by archenroot** [dbeaver/dbeaver#5416]
Hello,

I am testing Huawei DLI jdbc connectivity. 

The JDBC url string is defined like this:
`jdbc:dli://{hostName}/{projectName}?databasename=?;queuename=?;accesskey=?;secretkey=?`

When I try to import JDBC driver and test connection in dbeaver I get error:
`JDBC_URL_PARSE_ERROR: The configuration item 'token' must be set in TOKEN authentication mode`

I tried to check "No authentication" but same error.

Any idea how to make this working?

**Comment by archenroot** [comment]
Ok, I am able to connect finally with some changes to JDBC url:
jdbc:dli://{hostName}/{projectName}?databasename=?;queuename=?;authenticationmode=?;regionname=?;servicename=?;accesskey=?;secretkey=?

Still in case your Huawei (public or private cloud) is secured with SSL on the gateway or where I need to import certificate in JVM keystore, otherwise I can connect, but when trying to list tables I get still some PKI exception. Will leave this issue open and provide all instructions when resolved.

**Comment by serge-rider** [comment]
I don't quite understand the problem.
Do you have any links on JDBC driver documentation?
I never worked with Huawei DLI. Is it possible to test this somehow?

**Comment by archenroot** [comment]
@serge-rider - I work with Huawei, and by docs I wasn't able to connect initially, needed Huawei help to discover few small things, so actually I will just document here steps to get it properly working and will close it. I got it working today...

In new driver you must provide following info:
Fill Class Name: com.huawei.dli.jdbc.DliDriver
Fill URL Template: jdbc:dli://dli.{regionName}.{domain}/{projectId}?databasename=?,;queuename=default;authenticationmode=aksk;regionname=?;servicename=DLI;accesskey={accessKey};secretkey={secretKey}

Finally you can make this way connection, but cannot display tables failing on:
`KIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed com.huawei.dli.jdbc.utils.DliException: JDBC_SYSTEM_ERROR: the request is inaccessible to api-gw sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed com.huawei.dli.jdbc.utils.DliException: JDBC_SYSTEM_ERROR: the request is inaccessible to api-gw sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed JDBC_SYSTEM_ERROR: the request is inaccessible to api-gw sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed JDBC_SYSTEM_ERROR: the request is inaccessible to api-gw sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed`

You must get hostname of your API Gateway and download DER formated (or any other supported) from gateway and import into your trust store:
`sudo keytool -import -alias huawei-dli-api-gw -file ~/gw.huaweicloud.com -keystore /opt/oracle-jdk-bin-1.8.0.202/jre/lib/security/cacerts`

Now I can work with Huawei DLI platform from DBeaver without any issues...so far...

**Comment by serge-rider** [comment]
I see, thanks for the information.
