### ISSUE TITLE
Can't edit the identity of a column in SQL Server

### ISSUE THREAD

**Issue by marcgise** [dbeaver/dbeaver#5417]
#### System information: 
- Operating system (distribution) and version
Ubuntu 18.0.4
- DBeaver version
5.3.5
- Java version 
1.8.0_201
- Additional extensions

#### Connection specification:
- Database name and version
SQL Server 2014
- Driver name
MS SQL Server / SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)?
No

#### Describe the problem you're observing:
I can't modify the identity of a column using SQL Server

#### Steps to reproduce, if exist:
Try to edit a column. The Identity field text is not editable.
![image](https://user-images.githubusercontent.com/4680243/53876953-384d0b00-4008-11e9-9c38-e7f8afa116cb.png)

**Comment by ShadelessFox** [comment]
Hello @marcgise,

Sorry for really late response 😄

Unfortunately, you cannot "remove" identity from column in SQL Server.
