### ISSUE TITLE
Error on running excution plan

### ISSUE THREAD

**Issue by Stoumfou** [dbeaver/dbeaver#5418]
#### System information: 
- Operating system (distribution) and version => Windows 10
- DBeaver version => 5.3.5
- Java version => 8.181

#### Connection specification:
- Database name and version => MySQL 8.0.11
- Driver name => MySQL-connector-java:Release
- Do you use tunnels or proxies (SSH, SOCKS, etc)? => No

#### Steps to reproduce, if exist: 
Write : select * from accounts;
Hit execution plan button.

And this error are show : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select account_id, from accounts' at line 1

#### Include any warning/errors/backtraces from the logs
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select account_id, from accounts' at line 1

**Comment by iceblurr** [comment]
I am having the same issue 
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version : 5.3.5.201902181142
- Java version : 1.8.0_191
- Additional extensions

#### Connection specification:
- Database name and version MySQL 8 
- Driver name : mysql-connector-java:RELEASE[5.1.44]
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

Is there any option to enable to have run execution plan ? It works correctly in MySQL Workbench.

**Comment by serge-rider** [comment]
@Stoumfou you actually have an error in your SQL query (`'select account_id, from accounts` is invalid SQL because of coma before from keyword).

@iceblurr Please provide more details. What actual error do you see?

**Comment by Stoumfou** [comment]
@serge-rider Hi, am sorry i pasted the wrong error message.

When i execute this SQL, i have result: select * from accounts;
But when i launch Execution Plan on this request i have this error :

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select * from accounts' at line 1

**Comment by iceblurr** [comment]
@serge-rider Here is the error I get :
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select * from contacts where client_id=232482' at line 1

**Comment by Stoumfou** [comment]
Hi @serge-rider, i install the new version (6.0) and now i am capable to launch execution plan.
I close the ticket.
