### ISSUE TITLE
Linux Mint Debian Edition, Postres - Can't add home client

### ISSUE THREAD

**Issue by pastet89** [dbeaver/dbeaver#5421]
#### System information: 
- Operating system (distribution) and version: LMDE 2 Betsy MATE 64-bit
- DBeaver version 5.3.5
- Java version 1.8.0_171
- Additional extensions

#### Connection specification:
- Database name and version Postgres 9.4.19
- Driver name Don't know
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Coming from [this issue](https://github.com/dbeaver/dbeaver/issues/1361)
and after finding that my client resides at ```/usr/bin/pg_dump``` I am not able to execute a SQL file, nor to add the home client. 

#### Steps to reproduce, if exist:

When I go to connection settings, the "Local client" dropdown is empty. When I click on Browse/Add home, when I navigate to ```/user/bin```, I can see the binary there but can't select it as it's disabled for selecting.

**Comment by mlt** [comment]
I don't have/use Linux Mint, but I suspect it is just a symlink in `/usr/bin` to perl script that select one of the potentially many PG installations. The real path should be akin to `/usr/lib/postgresql/11/bin/`.

**Comment by pastet89** [comment]
@mlt Thanks, but this didn't work either. In my case I tried ```/usr/lib/postgresql/10/bin/pg_dump```, but it was disabled as well.
```locate pg_dump``` shows the following, there are no other options (And DBeaver shows all of the files in the binary folders as disabled):
```
/etc/alternatives/pg_dump.1.gz
/etc/alternatives/pg_dumpall.1.gz
/usr/bin/pg_dump
/usr/bin/pg_dumpall
/usr/lib/postgresql/10/bin/pg_dump
/usr/lib/postgresql/10/bin/pg_dumpall
/usr/share/locale/cs/LC_MESSAGES/pg_dump-10.mo
/usr/share/locale/de/LC_MESSAGES/pg_dump-10.mo
/usr/share/locale/es/LC_MESSAGES/pg_dump-10.mo
/usr/share/locale/fr/LC_MESSAGES/pg_dump-10.mo
/usr/share/locale/he/LC_MESSAGES/pg_dump-10.mo
/usr/share/locale/it/LC_MESSAGES/pg_dump-10.mo
/usr/share/locale/ja/LC_MESSAGES/pg_dump-10.mo
/usr/share/locale/ko/LC_MESSAGES/pg_dump-10.mo
/usr/share/locale/pl/LC_MESSAGES/pg_dump-10.mo
/usr/share/locale/pt_BR/LC_MESSAGES/pg_dump-10.mo
/usr/share/locale/ru/LC_MESSAGES/pg_dump-10.mo
/usr/share/locale/sv/LC_MESSAGES/pg_dump-10.mo
/usr/share/locale/tr/LC_MESSAGES/pg_dump-10.mo
/usr/share/locale/zh_CN/LC_MESSAGES/pg_dump-10.mo
/usr/share/man/man1/pg_dump.1.gz
/usr/share/man/man1/pg_dumpall.1.gz
/usr/share/postgresql/10/man/man1/pg_dump.1.gz
/usr/share/postgresql/10/man/man1/pg_dumpall.1.gz
```

**Comment by mlt** [comment]
I don't think you are supposed to select `pg_dump`. You are choosing location for all that stuff. Try `/usr/lib/postgresql/10` or `/usr/lib/postgresql/10/bin`.

**Comment by pastet89** [comment]
It worked with ```/usr/lib/postgresql/10/bin``` - thanks, man!
I thought I was supposed to specify a specific binary file, but it seems there's a whole folder with a bunch of them. Closing this one.

**Comment by Strato** [comment]
For the Linux + Postgresql users among us, you do:
```
# Postgresql 10
sudo apt install postgresql-client

# Postgresql 11
sudo apt install postgresql-client-11
```

And then you had Postgresql home client to DBeaver pointing to the following folder:
`/usr/lib/postgresql/10` (or 11)

**Comment by pastet89** [comment]
@Strato Thanks, man! As already mentioned, I already solved it. I am closing this one.
