### ISSUE TITLE
[PostGIS] Display geometry type and SRID in DDL

### ISSUE THREAD

**Issue by rbovard** [dbeaver/dbeaver#5422]
Hello,

Working with PostGIS tables, I noticed that in the generated DDL the geometry type and SRID are not displayed.

**pgAdmin**

```
CREATE TABLE my_table (
    id serial NOT NULL,
    geom geometry(MultiPolygon,2056),
    CONSTRAINT my_table_pkey PRIMARY KEY (id)
);
```

**DBeaver 5.3.5**

```
CREATE TABLE my_table (
    id serial NOT NULL,
    geom geometry NULL,
    CONSTRAINT my_table_pkey PRIMARY KEY (id)
);
```

Is it possible to add those informations?

Thanks for your great work.

**Comment by mlt** [comment]
I confirm with recent (2019-02-26) build from git. The very current git seems broken after permission model refactoring.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/53919131-1f7d3d80-407a-11e9-880c-73cf86c31f90.png)

**Comment by uslss** [comment]
verified

**Comment by rbovard** [comment]
Thanks a lot for this quick implementation, it's working fine!
