### ISSUE TITLE
wrong action for ctrl+shift+z

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#5426]
#### System information: 
- Operating system (distribution) and version: Linux mint 18.3
- DBeaver version 5.3.5

#### Describe the problem you're observing:
I want to Edit->Redo (CTLR+SHIFT+Z), but when I press it the
![__](https://user-images.githubusercontent.com/799021/53898195-44ed5580-4040-11e9-9d15-3d54c872ac9b.jpg)

opened

#### Steps to reproduce, if exist:
press ctrl+shift+z at SQL editor

**Comment by serge-rider** [comment]
ctrl+shift+z was never bound to "Undo" command. It is ctrl+z.
However you can redefine any shortcuts in preferences.

**Comment by KES777** [comment]
sorry, typo. It is `Redo`
See interface screen shot
![img20190307082721](https://user-images.githubusercontent.com/799021/53936551-c978bc00-40b2-11e9-816b-4899e7a6eb48.jpg)

**Comment by serge-rider** [comment]
Yep. It is bound to Redo in some key schemes. Thanks for noticing.
I'll change shortcuts for dashboards on <kbd>ctrl+alt+shift+d</kbd>

**Comment by uslss** [comment]
verified
