### ISSUE TITLE
Data keep loading without stop during table data browsing in Hadoop Hive

### ISSUE THREAD

**Issue by GaryLiuTelus** [dbeaver/dbeaver#5427]
#### System information: 
- Operating system (distribution) and version
Window 10 Enterprise 1709 build 16299.967
- DBeaver version
5.3.0
- Java version 
Java 8 update 121
- Additional extensions

#### Connection specification:
- Database name and version
Hadoop
- Driver name
JDBC driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No. it is via VPN

#### Describe the problem you're observing:
Unlike in Oracle, only limited rows are loaded during table data browsing, when browsing table data in Hadoop Hive, the data kept loading and tried to load all data, unless manually stopped it. And got the following error message when stopped loading manually:

SQL Error: Error retrieving next row

#### Steps to reproduce, if exist:
Select the table and double click, then choose 'Data' tab.

#### Include any warning/errors/backtraces from the logs

SQL Error: Error retrieving next row
  FetchResults failed: out of sequence response

Cancel error
Invalid use of BasicClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.
Invalid use of BasicClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.

**Comment by uslss** [comment]
is it still actual?

**Comment by GaryLiuTelus** [comment]
Thanks for following up.

I am still using version 6.2.4. It is there still. Not sure about the latest version. Will try next week and let you know.

Gary

**Comment by uslss** [comment]
@GaryLiuTelus is there any updates?
thanks in advance

**Comment by GaryLiuTelus** [comment]
It still exists in 7.1.0
![image](https://user-images.githubusercontent.com/39339422/85418753-2a920080-b53f-11ea-8bc5-84caa45e7f51.png)

Thanks for following up.

**Comment by uslss** [comment]
@GaryLiuTelus is it still actual against the recent(21.3.1) version? unfortunately, cannot reproduce it

**Comment by GaryLiuTelus** [comment]
Thanks for the following up. No, it has been resolved. Everything working perfectly!
