### ISSUE TITLE
[MongoDB] Not able to query non-authsource database

### ISSUE THREAD

**Issue by dimon222** [dbeaver/dbeaver#5429]
PS: this issue exists for long time, but I can't seem to find it in Github. Seems only in old forums.
Related link - https://dbeaver.io/forum/viewtopic.php?f=3&t=1642

#### System information: 
- OS X Mojave 10.14.2
- DBeaver EE 5.3.3
- Java 1.8

#### Connection specification:
- MongoDB 4.0.2
- MongoDB built-in driver
- No tunnels/proxies 

#### Describe the problem you're observing:
Not able to query any other databases aside from one where I've logged in.
Especially applies for admin/root that usually exists on "admin" database, but should be able to access any databases/collection.

#### Steps to reproduce, if exist:
Create default admin user according to MongoDB guide in mongo CLI or in another client. Create new db, add collection there with 1 record. Try to query new collection from DBeaver by logging into admin user.
https://docs.mongodb.com/manual/reference/method/db.createUser/

#### Include any warning/errors/backtraces from the logs
To be added.

**Comment by serge-rider** [comment]
Please provide more details:
- How do you query Mongo databases - using SQL editor or browse collections' data directly?
- Do you see any error?

Generally you can change active database in main toolbar (see dropdown with database name on it) or using context menu in database navigator (Set Active command).

**Comment by uslss** [comment]
there is no update more than a month. Ticket closed.  
If issue is still actual feel free to reopen the ticket or create a new one.
