### ISSUE TITLE
PL/pgSQL dollar-quote highlighting rule is missing

### ISSUE THREAD

**Issue by mlt** [dbeaver/dbeaver#5430]
#### System information: 
- DBeaver version 8ec205926e
- Java version 1.8.0

#### Connection specification:
- Database name and version PostgreSQL 11.2

#### Describe the problem you're observing:

It is common to use [dollar quoting](https://www.postgresql.org/docs/11/plpgsql-development-tips.html#PLPGSQL-QUOTE-TIPS) to avoid explicit escaping of single quote marks within stored procedure source code.

Everything within such block should be highlighted as a string literal, whereas opening `$$` are black and closing `$$` are red and everything in between is highlighted as if pl/PGSQL code. I have a dynamic SQL statements and it is very confusing as I would expect seeing those as strings (green?).

![dollar_quote_highlighting](https://user-images.githubusercontent.com/413384/53926683-0361a800-404a-11e9-8b90-3063a47433b7.png)

#### Steps to reproduce, if exist:

```PLpgSQL
CREATE OR REPLACE FUNCTION blah()
 RETURNS text
 LANGUAGE plpgsql
 LEAKPROOF
AS $function$
BEGIN
  return format($$That's funny
    select 1;
  $$);
END
$function$
;
```
GFM isn't better &hellip; oh well &hellip; would be nice though.

Edit: Apparently pgAdmin is not aware of that either. I'll leave it here as a low-priority feature request :-)

**Comment by mlt** [comment]
This is a very bad workaround if you use PostgreSQL only and plain `$$` for multiline strings.
```diff
diff --git a/plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/syntax/SQLPartitionScanner.java b/plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/syntax/SQLPartitionScanner.java
index 92ec6863d..7de329ca0 100644
--- a/plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/syntax/SQLPartitionScanner.java
+++ b/plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/syntax/SQLPartitionScanner.java
@@ -118,6 +118,7 @@ public class SQLPartitionScanner extends RuleBasedPartitionScanner {
 
     private void initRules(SQLDialect dialect)
     {
+        rules.add(new MultiLineRule("$$", "$$", sqlStringToken));
         rules.add(new MultiLineRule(SQLConstants.STR_QUOTE_SINGLE, SQLConstants.STR_QUOTE_SINGLE, sqlStringToken, dialect.getStringEscapeCharacter()));
         rules.add(new MultiLineRule(SQLConstants.STR_QUOTE_DOUBLE, SQLConstants.STR_QUOTE_DOUBLE, sqlQuotedToken, dialect.getStringEscapeCharacter()));
```
![dollar_quote_workaround](https://user-images.githubusercontent.com/413384/54469341-deb1b280-4764-11e9-81af-24af3a097621.png)

**Comment by mlt** [comment]
Feedback wanted. I sort of cheat by excluding `$function$`. Technically it is also a string but we do want to see stuff highlighted. Proper recognition would require yet another fancy rule (`AS` prefix?). I think it is okay to get by with exceptions. I'm not sure whether other PG versions return different quotation tag for body with `pg_get_functiondef`.

![dolq_sample](https://user-images.githubusercontent.com/413384/54484909-62d76900-483d-11e9-810f-60ae01a11d1d.png)

**Comment by mlt** [comment]
I'm somewhat at lost with this one before submitting a PR. Where shall I place rule addition? I mean do we want dialects to  have `extra(rules)` function to add whatever specific to dialects? But then we bring/import Eclipse Platform Text rules into dialects. For now, I check dialect name, but this is somewhat not reliable. I could check for *PostgreDialect* instance but it would bring those namespaces in as not everyone is using PG.

**Comment by mlt** [comment]
Bump? Can we get this in? I am willing to clean things up. I just need some feedback as I'm not that much into Java...

**Comment by serge-rider** [comment]
Sorry, I missed this ticket. 
There is #6608 where we tracking this problem (it was created later than this but still).

I will check your commit and will write some feedback. Thanks for contributing !

**Comment by serge-rider** [comment]
@mlt please see comments in #6608. 
We can't always treat dollar quoted string as strings. Sometimes we need to treat them as SQL statements.
Anyhow, I hope now the problem is solved.
