### ISSUE TITLE
Parsing Error on Confirmation Dialog

### ISSUE THREAD

**Issue by amadoalmex** [dbeaver/dbeaver#5433]
#### System information: 
- Operating system (distribution) and version
LINUX 4.20.6-arch1-1-ARCH 
- DBeaver version
Dbeaver Community 5.3.2 20190112
- Java version 
openjdk 11.0.2
- Additional extensions

#### Connection specification:
- Database name and version
Mysql 5.6
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
![selection_20190307-001](https://user-images.githubusercontent.com/31776001/53975506-9b9f7180-40ca-11e9-95e3-db6db271d3c1.png)

Scary parsing error on confirmation when attempting to drop table via right-click->delete on table.

**Comment by p91paul** [comment]
quite sure this was fixed, current version is 5.3.5!

**Comment by amadoalmex** [comment]
This is no longer an issue in v6.0.0 CE
