### ISSUE TITLE
Column name word-wrap by cell value

### ISSUE THREAD

**Issue by julianbiggio** [dbeaver/dbeaver#5436]
Could be great that when the query result it's showed, the height of column will auto-adjust to show the completa column name, because when you have the option "Calculate the column name bye the column value", if you have a column name larger that the column value, you don't see the column name

**How show today:**
![image](https://user-images.githubusercontent.com/48332328/53983931-97b02700-40ab-11e9-84f5-9ef42dd4b35c.png)

**How could be great:**
![image](https://user-images.githubusercontent.com/48332328/53983876-79e2c200-40ab-11e9-9ba3-f07f65b44f76.png)

#### System information: 
- W7
- DBeaver 5.3.5 February 17th, 2019

#### Connection specification:
- IBM DB2 Version 11 Release 2
- DB2 Z/OS

#866 referenced

**Comment by julianbiggio** [comment]
Function **"Wrap text"** of MS Excel is that we need to see correctly the column titles:

![image](https://user-images.githubusercontent.com/48332328/54081024-fe1b8c00-42db-11e9-88ed-42cd30611dfb.png)

**Comment by uslss** [comment]
duplicates #866
