### ISSUE TITLE
dbeaver treats PostgreSQL array slice bound as a binding parameter

### ISSUE THREAD

**Issue by mlt** [dbeaver/dbeaver#5440]
#### System information: 
- DBeaver version 8ec205926e

#### Connection specification:
- Database name and version PostgreSQL 11.2

#### Describe the problem you're observing:

DBeaver treats `[:colname]` as a binding parameter in SQL editor whereas it is [array slicing](https://www.postgresql.org/docs/11/arrays.html#ARRAYS-ACCESSING) with omitted lower bound.

#### Steps to reproduce, if exist:

```sql
select tgrelid::regclass, (regexp_split_to_array(encode(tgargs, 'escape'), '\\000'))[:tgnargs] args
from pg_catalog.pg_trigger
```

**Comment by serge-rider** [comment]
Fixed ('[: ]' is a special case)

**Comment by uslss** [comment]
verified
