### ISSUE TITLE
[Oracle]Ctrl + LeftClick Edit View Oracle

### ISSUE THREAD

**Issue by hugorn** [dbeaver/dbeaver#5441]
![deepin-screen-recorder_select area_20190308100217](https://user-images.githubusercontent.com/9035153/54031663-24cbac80-418e-11e9-96d9-f9d98b95deea.gif)

#### System information: 
- Operating system (distribution) and version
         Linux Deepin 15.9.1
- DBeaver version
         5.3.5.201902172105
- Java version 
         Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp
         java 10.0.2 2018-07-17
        Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
        Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
         
#### Connection specification:
- Database name and version
         Oracle 11G
- Driver name
         ojdbc6.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
          No
#### Describe the problem you're observing:
          In this version of dbeaver the Ctrl + LeftClick in view objects wont work on Oracle.
#### Steps to reproduce, if exist:
          On active tab of Mysql press ctrl and Position the mouse cursor over the view name. The mouse cursor changes immediately.

**Comment by serge-rider** [comment]
Most likely DBeaver just can't find your view. Try to use fully qualified names (SCHEMA_NAME.VIEW_NAME)

**Comment by hugorn** [comment]
> Most likely DBeaver just can't find your view. Try to use fully qualified names (SCHEMA_NAME.VIEW_NAME)

Works fine using fully qualified names, thanks.
