### ISSUE TITLE
BigQuery Struct Support

### ISSUE THREAD

**Issue by sabrikaragonen** [dbeaver/dbeaver#5442]
Actually it's reported in the following link but this issue is closed, so I decided to create a new one.
https://github.com/dbeaver/dbeaver/issues/1687#issuecomment-426502491

Thanks to @r-richmond , Issue is explained great in the link, so I just copy it here:

The formatting of structs looks a little off.
example snippet
`{f=[{v=https://github.com/appden/less.tmbundle}, {v=true}, {v=2009/09/19 16:46:18 -0700}`

but under the nested and & repeated section of the guide it shows a format that should look more like the following...

```
"address":[{
  "city":"Vancouver", 
  "years":5
  } ],
"name":"Google"
```
I'm not sure if its a driver bug... arrays appear to formatted as specified. (although repeating the array label for each array item seems excessive).

[demo script](https://bigquery.cloud.google.com/table/bigquery-public-data:samples.github_nested?pli=1)

```
select
  t.repository
from `bigquery-public-data`.samples.github_nested as t
limit 10
```

**Comment by agentkirkwood** [comment]
Any interest in looking into this issue? Also seeing the same. It make it quite difficult to determine what is inside of a `struct` object, without already know what is there.
![key_values_missing__dbeaver](https://user-images.githubusercontent.com/16674499/119394225-2dd1c700-bc8f-11eb-8e88-fe4b94d1af1f.png)

**Comment by ikartavyi** [comment]
Please, take a look at this request. This problem limits BigQuery usage so much with complex data sources!

**Comment by psygnoser** [comment]
It's been more than 5 years since this was reported and still nothing? It's incredibly difficult to browse rows with arrays and especially structs looking like that. 
In my opinion this this issue is also mis-tagged as this is simply a BUG, since the serialisation of structs doesn't show the actual structure of the structs (with the keys missing).

**Comment by LonwoLonwo** [comment]
Implemented here: https://github.com/dbeaver/dbeaver/issues/16544

Struct support is available in all DBeaver PRO versions.
You can try it for [free here](https://dbeaver.com/trial/).

**Comment by sbuckpesch** [comment]
@LonwoLonwo will displaying of STRUCT type be available in CE as well? When to expect? Isn't Basic Editing functionality just a community feature? As well you stated that it is supported in CE already beginning of this year: https://dbeaver.io/2024/01/21/dbeaver-23-3-3/
Wasn't it merged?
