### ISSUE TITLE
The ERD notation seems to be IDEF1X, but in opposite direction, which is confusing.  Appreciated if it can be fixed.

### ISSUE THREAD

**Issue by zongzhiliu** [dbeaver/dbeaver#5444]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by zongzhiliu** [comment]
Mac OS 10.14
Dbeaver 5.3.4
database: Redshift

**Comment by serge-rider** [comment]
Good point.
I guess it was broken recently after ERD model refactoring.
Thanks for noticing.

**Comment by zongzhiliu** [comment]
Thanks for your quick response. The default arrangement is much better in the refactored version.  And it is really fast.

Appreciated.
Zach
--
Zongzhi Z Liu
Call me @203-903-2599

**Comment by uslss** [comment]
verified

**Comment by zongzhiliu** [comment]
Have it been fixed?  Although the new version looks better, the direction of relation is still reversed. ...

**Comment by serge-rider** [comment]
New version will be released tomorrow
