### ISSUE TITLE
Two Open Sockets listening 

### ISSUE THREAD

**Issue by Real-XkLi** [dbeaver/dbeaver#5446]
#### System information: 
- Operating system (distribution) and version
    5.0.0-arch1-1-ARCH

- DBeaver version
    Version 5.3.2.2019.01122022
- Java version 
     java-11-openjdk (default)
- Additional extensions
    none

#### Describe the problem you're observing:
When starting DBeaver two sockets are being opened, listening on every network interface:
Why are there ports being opened on every interface rather than only on the local interface?
What are these sockets being opened? I was unable to locate any descriptions of them in the docks.

#### Steps to reproduce, if exist:
Start DBeaver, list open ports

#### Example output:

 % ss -talpn
LISTEN      0           50                           *:54751                       *:*          users:(("java",pid=3454,fd=125))      
LISTEN      0           50                           *:39845                       *:*          users:(("java",pid=3454,fd=124))

 % ps aux | grep 3454
user 3454  3.7  2.4 6812140 392244 ?      Sl   14:02   0:41 /usr/bin/java -XX:+IgnoreUnrecognizedVMOptions --add-modules=ALL-SYSTEM -Xms64m -Xmx1024m -jar /usr/lib/dbeaver//plugins/org.eclipse.equinox.launcher_1.5.100.v20180827-1352.jar -os linux -ws gtk -arch x86_64 -showsplash -launcher /usr/lib/dbeaver/dbeaver -name Dbeaver --launcher.library /usr/lib/dbeaver//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.800.v20180827-1352/eclipse_1705.so -startup /usr/lib/dbeaver//plugins/org.eclipse.equinox.launcher_1.5.100.v20180827-1352.jar --launcher.overrideVmargs -exitdata 47c0010 -vm /usr/bin/java -vmargs -XX:+IgnoreUnrecognizedVMOptions --add-modules=ALL-SYSTEM -Xms64m -Xmx1024m -jar /usr/lib/dbeaver//plugins/org.eclipse.equinox.launcher_1.5.100.v20180827-1352.jar

Attached is a thread-dump which also shows the open sockets.

[thread-dump.txt](https://github.com/dbeaver/dbeaver/files/2948404/thread-dump.txt)

**Comment by Real-XkLi** [comment]
After doing some more research through the source code I came across the RMI Server. It is starting and opening the ports. Why is this Server enabled by default when using DBeaver as a Client?

**Comment by serge-rider** [comment]
RMI service is used to process DBeaver command line. E.g. open files in running DBeaver instance.
