### ISSUE TITLE
SQLite Drop Column

### ISSUE THREAD

**Issue by XiozTzu** [dbeaver/dbeaver#5447]
SQLite does not support the drop column syntax generated by DBeaver when attempting to delete a column.

DBeaver syntax "ALTER TABLE aTable DROP COLUMN aColumn;" is not valid in SQLite.

   https://www.sqlite.org/lang_altertable.html

See 
   https://stackoverflow.com/questions/5938048/delete-column-from-sqlite-table/5987838#5987838
if you wish to develop a workaround.

**Comment by katsar0v** [comment]
Ping

**Comment by kseniiaguzeeva** [comment]
I think there is no need to write several identical SQL expressions to remove several columns
Steps:
1. Open Columns tab of table Properties
2. Select several columns
3. Press Delete
4. Confirm the action
5. Press Save
Actual result: SQL Preview window opens with several identical SQL expressions
![dbeaver_5hSbnAJJCk](https://user-images.githubusercontent.com/51405061/95299465-70709b80-0886-11eb-9a21-2bf4adbd449c.png)

Expected: only 1 necessary SQL statement is created

**Comment by kseniiaguzeeva** [comment]
Verified (clause B)
