### ISSUE TITLE
DBeaver is using the wrong syntax

### ISSUE THREAD

**Issue by silvershadowcc** [dbeaver/dbeaver#5451]
Hi, I just started using DBeaver and I really like it. Thanks for that. Now, I've tried to change the password of a database user and found that DBeaver is using the new syntax where I'm using an older version of MariaDB.

I tried uninstalling/resetting everything, using an older driver, using an older native client that matches my MariaDB version. Nothing makes DBeaver use the old syntax for changing passwords :(

Is there something I can do to fix this?

mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1

The ALTER USER statement was introduced in MariaDB 10.2.0.

![2019-03-10_234651](https://user-images.githubusercontent.com/36823114/54092770-6fb51200-4390-11e9-9a86-7317383bb156.png)
![2019-03-10_234709](https://user-images.githubusercontent.com/36823114/54092771-6fb51200-4390-11e9-8650-5588c4ca2a89.png)
![2019-03-10_234740](https://user-images.githubusercontent.com/36823114/54092772-6fb51200-4390-11e9-8e8e-33b56695b8ee.png)
![2019-03-10_234830](https://user-images.githubusercontent.com/36823114/54092773-6fb51200-4390-11e9-873b-c47d82daf416.png)
![2019-03-10_234847](https://user-images.githubusercontent.com/36823114/54092769-6fb51200-4390-11e9-878a-3d284ef57832.png)

**Comment by serge-rider** [comment]
Thanks for the bug report. Indeed we need to generate old UPDATE USER for MariaDB < 10.2

**Comment by uslss** [comment]
closed without testing
