### ISSUE TITLE
Redis: support key edit/delete

### ISSUE THREAD

**Issue by zoltan-fedor** [dbeaver/dbeaver#5452]
I am trialing the Enterprise Edition to test the Redis support, but it seems to me that while DBeaver can connect to Redis, you can only browse the keys, not edit or delete them.
Is this just a limitation of the trial license or this is just the level of Redis support in DBeaver?

**Comment by serge-rider** [comment]
You can't edit keys directly in results viewer. But you can execute Redis command (like SET) in SQL editor:
```
SET foo bar
```
(https://redis.io/commands)
Initially we didn't add key edit support because of sophisticated nature of Redis keys.
Perhaps its time to implement this feature..

**Comment by zoltan-fedor** [comment]
Hi @serge-rider, thank you, that would be great!
And I am sure I am not the only one who could use it.
Also, it would be a great convenience just to have a delete option (even without the edit).

**Comment by serge-rider** [comment]
Done. You can test it in Early Access version (https://dbeaver.com/files/ea)

**Comment by zoltan-fedor** [comment]
Thanks for the great work, I have tested it, it mostly looks good!

I have tested it:
1. The delete works fine
2. The update works too, but I found an issue related to updating formatted values:
When I have a JSON string in the value and display it using the "view JSON" option (see https://github.com/dbeaver/dbeaver/issues/2944). IfI edit some of the values of the JSON and save it, line breaks gets added to the JSON string.

Value before the update:
{"ID":"ka01W0AAs","ARTICLENUMBER":"000096656"}

Value after the update:
{
  "ID": "ka01W0AAs-ADDEDTHIS",
  "ARTICLENUMBER": "000096656",
}

Not really a big deal, but I thought I mention it.

**Comment by serge-rider** [comment]
This looks like json auto-formatting. If you edit key value in value panel it will auto-format json by default. you can disable auto-formatting in panel toolbar or you can edit value directly in the cell editor.
Or you can just paste json value when cell is selected.

**Comment by zoltan-fedor** [comment]
Thanks, yes. It does the same in MySQL, except it seems there the DB removes the line breaks - probably because it is a JSON type and in Redis it doesn't remove it. So probably this is not about DBeaver.

Thanks for implementing this, I can confirm that it all works for me!

**Comment by kentore82** [comment]
Hi,

Ive tested the edit functionality for redis values of type ReJSON (that is, a Redis Json database). It seems that reading the ReJson type works fine, but if edited the value is saved as a regular string type back to Redis, thus corrupting the database (key/value) pair. Can you reproduce this behaviour @serge-rider ? 

Thanks! :)
