### ISSUE TITLE
The object name 'fn_listextendedproperty' is invalid.

### ISSUE THREAD

**Issue by loonit** [dbeaver/dbeaver#5455]
Now I use the jtds1.3.1 drive to conncet sql server2000 ,when I open any views or tables ,the software(6.0) will promt that "The object name 'fn_listextendedproperty' is invalid. ".Is that a bug?

**Comment by lukecharl** [comment]
me too :-(

**Comment by Pikoh** [comment]
I can confirm it's happening to me too.

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on ticket for a long time. If it is still actual for you - feel free to reopen the ticket

**Comment by Pikoh** [comment]
It is still actual. I have checked just now.
Versión7.0.2.202004051509

Error (sorry it is in spanish):
>  java.lang.reflect.InvocationTargetException
>     SQL Error [208] [S0002]: El nombre de objeto 'fn_listextendedproperty' no es válido.
>     SQL Error [208] [S0002]: El nombre de objeto 'fn_listextendedproperty' no es válido.
>       El nombre de objeto 'fn_listextendedproperty' no es válido.
>       El nombre de objeto 'fn_listextendedproperty' no es válido.

**Comment by alaj** [comment]
I have the same issue.
My database is sql server 2000. Version 8.00.2039.
The driver is jTDS Type 4 JDBC Driver for MS SQL Server and Sybase 1.3.1
@uslss Will this issue be reopened? Thanks

**Comment by leonelimg** [comment]
same issue
