### ISSUE TITLE
UI display error

### ISSUE THREAD

**Issue by matteomelotti** [dbeaver/dbeaver#5456]
Hi, I'm on Elementary OS 5 and from DBeaver version 5.2 and later I can't upgrade because of graphical issues.

See attached a screenshot.

Thanks.

![Screenshot from 2019-03-11 08-55-30](https://user-images.githubusercontent.com/30950613/54108181-93517a00-43db-11e9-8988-5273198cd9cc.png)

**Comment by uslss** [comment]
@matteomelotti is it still actual for you?

**Comment by uslss** [comment]
there is no update on ticket for a long time. if issue is still actual for you - feel free to reopen the ticket

**Comment by matteomelotti** [comment]
Yes, is still actual.
I updated at 7.0.5 an the problem is still present.
I'm still working on elementary OS 5 and I tried launchind dbeaver with some commands:
GTK_IM_MODULE=ibus /usr/share/dbeaver/dbeaver
--launcher.GTK_version 2
but nothing happens.
