### ISSUE TITLE
Zerofill  and Visual Editor for Table

### ISSUE THREAD

**Issue by EdoardoMM** [dbeaver/dbeaver#5457]
Good morning,
my work team has detected a problem with the display of zerofill fields, in fact no zeros are displayed in front of each digit. This turns out to be a big problem for us that we work with an important DB that needs fields of this type. without proper display we can not verify the correct entry.
We tried on another IDE and the data type is correct and the data is displayed correctly.

Another issue that we have found is the impossibility of having in time the sorting of the columns moved by visual editor.

For business reasons I can not insert images of the issue.

System information: 
- W10 PRO
- DBeaver version 5.3.3 free and Enterprise

**Comment by serge-rider** [comment]
Could you provide a bit more details? What database do you use, what column data type causes problem.

If your question is a generic  question about numbers formatting then it can be configured in preferences:
![image](https://user-images.githubusercontent.com/6398845/54187517-cde01300-44be-11e9-8f90-39815f8fca25.png)

**Comment by EdoardoMM** [comment]
we tried to set the numeric formatting, but we did not find effective options to correctly display the MYSQL fields in zerofill. the zeros are not shown. for example a field with int 6, value entered = 10 is shown as in the images.
structure:
using the minimum integer digits the zeros are shown also in non-zerofill fields.
![image](https://user-images.githubusercontent.com/48353861/54188718-98ccc400-44b0-11e9-85fd-6af205d44da5.png)

data:
![image](https://user-images.githubusercontent.com/48353861/54188802-c6197200-44b0-11e9-804e-99c5e321e608.png)


with minimum integer digits the zeros set to 10:
![image](https://user-images.githubusercontent.com/48353861/54188887-f52fe380-44b0-11e9-9deb-70f6e1bfbeaa.png)

**Comment by Spoting** [comment]
I have the same problem. 
Zerofill doesnt apply to my column, and also the length constraint doesnt apply.

Picture showing Column with Zerofill
![Screenshot from 2019-12-08 19-27-49](https://user-images.githubusercontent.com/26886952/70393331-67f2ce80-19f1-11ea-8806-538b037a55fe.png)

Picture of an entry that got more digits than 3 and of an entry that got less but zerofill isnt applied
![Screenshot from 2019-12-08 19-30-04](https://user-images.githubusercontent.com/26886952/70393332-67f2ce80-19f1-11ea-8638-f91d28f2e4dd.png)

**Comment by Edwardlin-zlt** [comment]
I have the same problem, the zerofill column couldn't display the fill-up zeros in the front.

System:
    - Ubuntu 18.0-4 
    - dbeaver 7.0.0 community

**Comment by christianbueno1** [comment]
Hello pals, the issue persist in DBeaver 7.1.5. , OS: Linux Fedora-32 workstation, database: Mariadb 10.3.17.

![Screenshot from 2020-08-23 18-51-36](https://user-images.githubusercontent.com/10623247/90992099-2734e880-e573-11ea-9e4b-71e542c22fb2.png)

![Screenshot from 2020-08-23 18-51-23](https://user-images.githubusercontent.com/10623247/90992103-2d2ac980-e573-11ea-83aa-44f49eddba47.png)

**Comment by kseniiaguzeeva** [comment]
Implemented.
Note: text view doesn't show nulls
