### ISSUE TITLE
Text on unfocused tabs unreadable in new dark theme

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#5459]
With the new dark theme defaults in 6.0.0, unfocused tabs in the DBeaver interface have text that is very hard to read due to the colors (white over slightly darker white). Would be nice to have it like it was before instead.
![db_text_unreadable](https://user-images.githubusercontent.com/11860098/54123468-8b5bff00-4408-11e9-9061-744c4f3846b1.png)

**Comment by david-cortes** [comment]
Solved in 6.0.3.

**Comment by skytomba** [comment]
reproduced in 7.0.2. I've failed to find setup option to change this behaviour.
![1](https://user-images.githubusercontent.com/32893144/79201306-ebfa0e80-7e48-11ea-968c-574e3991f3a1.gif)
