### ISSUE TITLE
Additional Sound Notifications

### ISSUE THREAD

**Issue by SirBenJammin** [dbeaver/dbeaver#546]
Hey Serge,

I see that in 3.6.7 you added sound notification support "beep after query finish".

Is it possible we can expand on this capability, for example rather than beep after each query could we have a notification sound after the run of all queries within one SQL editor?

Also could there be a different notification sound based on the outcome per query/per SQL script.

See example notification sounds below:
- Success: [http://www.soundsnap.com/node/92951](http://www.soundsnap.com/node/92951)
- Failed: [http://www.soundsnap.com/error_tone_chime_blastwavefx_16379](http://www.soundsnap.com/error_tone_chime_blastwavefx_16379)

This would really help me and hopefully other people when you running many queries, want to monitor but don't always have to be at your desk. 

Thanks,

Ben

**Comment by serge-rider** [comment]
Agreed, that would be a good feature.

**Comment by shungabubus** [comment]
Hello All, +1 vote for this...

**Comment by yonisade** [comment]
Hello All, I also +1 vote for this.
This small feature can contribute so much for efficient time utilization while waiting for long running SQL.

**Comment by eng543** [comment]
+1 for this!

**Comment by dburtonDRW** [comment]
+1

I would also suggest the ability to trigger a macOS notification on query completion too. (Should that be a separate issue?)  I sometimes need to kick off a long-running query and then I go do work in some other app while I'm waiting.  For various reasons, sound notifications aren't always viable.

**Comment by earsonlau** [comment]
> +1
> 
> I would also suggest the ability to trigger a macOS notification on query completion too. (Should that be a separate issue?) I sometimes need to kick off a long-running query and then I go do work in some other app while I'm waiting. For various reasons, sound notifications aren't always viable.

i don't even know how to set the notification:(

**Comment by lalato** [comment]
+1
What's the latest on this feature?  Is it still planned?

**Comment by andreescastano** [comment]
+1
dont't forget us!

**Comment by xenago** [comment]
Any updates on this? Has it been abandoned?
