### ISSUE TITLE
Mysql Server session graph not rendered properly

### ISSUE THREAD

**Issue by mims92** [dbeaver/dbeaver#5460]
#### System information: 
- Operating system (distribution) and version
Linux 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64 GNU/Linux
- DBeaver version
6.0.0.201903101945
- Java version 
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
- Additional extensions

#### Connection specification:
- Database name and version
Mysql 5.6
- Driver name
Mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
Server Sessions graph does not "slide" from right to left at some point and lines become all crushed.
![image](https://user-images.githubusercontent.com/5518873/54129780-4be4e100-440f-11e9-961b-3aad68c47695.png)

The queries graph is at 15:00 while the server sessions one is still at 14:48 while data are still "coming" from the right.

#### Steps to reproduce, if exist:
- Add the Server sessions graph to the dashboard
- Let it run for a while

**Comment by mims92** [comment]
Hello,

Any update on this? I still have the issue with Version 6.1.0

![2019-06-21 11_03_16-Debian2  En fonction  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/5518873/59911510-5baf9080-9414-11e9-9efe-fc61e86d47a6.png)

**Comment by mims92** [comment]
Hello, This is still the case with version 6.3.2

**Comment by E1izabeth** [comment]
Can't reproduce against DBeaver 23.0.5
![image](https://github.com/dbeaver/dbeaver/assets/28875055/a9ac9669-ebfc-444b-9047-79658d44e068)


If the issue is still actual, please let me know.
