### ISSUE TITLE
New function cast "date/time format" importing data from CSV

### ISSUE THREAD

**Issue by ZeroHager** [dbeaver/dbeaver#5461]
Hi,
I'm using the new versión (6.0) of Dbeaver and you just added the new function to cast dates when importing data from CSV files, but Debeaver missunderstand the format, maybe I'm doing something wrong and you can help me,

I have this CSV file with dates (format for date "**dd-MM-yyyy**")

![imagen](https://user-images.githubusercontent.com/40251003/54141046-87b97f80-43ea-11e9-972e-a95054705c90.png)

Now when I try to use the new function

My settings (date/time format "**dd-MM-yyyy**[ HH:mm:ss[.SSS]]"), same as CSV file

![imagen](https://user-images.githubusercontent.com/40251003/54141333-162e0100-43eb-11e9-8ca1-cc41aaaa2cfa.png)

The result

![imagen](https://user-images.githubusercontent.com/40251003/54142019-6bb6dd80-43ec-11e9-8e12-4ca16774973e.png)

The CSV for example have "15/10/2018" but then the date chenge to "10/03/2019".

I'm using Windows 7, oracle ojdbc6, oracle database, the CSV file are separete vy ";".

Thank you in advance for any help you can give me and thanks for your time.

**Comment by serge-rider** [comment]
As I see your CSV date format is not `dd-MM-yyyy` but `dd/MM/yyyy`.

**Comment by ZeroHager** [comment]
Hi,
You right, my mistake, I feel bad not noticing that, really appreciate your replay.

Now I have this (NLS Date Format dd/MM/yyyy)
![imagen](https://user-images.githubusercontent.com/40251003/54160180-7d13e000-4414-11e9-90e2-bc844234c2eb.png)

Date format value dd/MM/yyyy
![imagen](https://user-images.githubusercontent.com/40251003/54159813-86e91380-4413-11e9-85ef-0cf2b2c4adb0.png)

Same as above

CSV format dd/MM/yyyy
![imagen](https://user-images.githubusercontent.com/40251003/54159930-d3345380-4413-11e9-81e9-cde9ba2c6a36.png)

Import function dd/MM/yyyy
![imagen](https://user-images.githubusercontent.com/40251003/54160053-28706500-4414-11e9-8717-d8c6c5344d56.png)

The date was changed for example from 15/10/2018 to 10/03/2019
![imagen](https://user-images.githubusercontent.com/40251003/54160144-5d7cb780-4414-11e9-9bc7-cdcd7b6aa6c1.png)

Hope not missing anything this time.

Maybe this character don´t work well "/" and must be changed for "-".

Thanks again for your time.

**Comment by jbdesbas** [comment]
Hello,
Same issue on dbeaver 6.1.2

**Comment by MalcolmCoull** [comment]
I'm on 6.1.3 on Windows 7. 

I have also been having this hiccup with a file of climate data I am using for testing. It came as .txt, with date format dd-mm-yyyy, but having opened it in Excel and saved to .csv, when I tried importing to a new empty table, although the preview window showed the correct date format, when the data was imported the dates were mixed up - not sure if there was anything 'systematic' in the way they were jumbled but definitely not right. 

Reading the posts above, I changed the file extension of the initial file directly to .csv (cutting out Excel which may have been the problem) and tried again, making sure to set the date format to dd-mm-yyyy in the import dialogue. And it's now working as expected.

**Comment by wwardzinski** [comment]
Hi, I've just installed the new version of DBeaver Version 6.2.2.201910072100. I am trying to import data to Oracle table where my data format is like 20191017 i.e. YYYYMMDD
Unfortunately I can't load it.  I was able to figure out that it should be 17-Oct-2019.
I tried to change settings like previous users but it did not work.
Can anybody help me with this matter?

I appreciate your input.
Best Regards
ww

**Comment by VBP8501** [comment]
Same issue on DBeaver 6.2.4 / Windows 10
Importing from csv

**Comment by allealbaron** [comment]
> Hi,
> You right, my mistake, I feel bad not noticing that, really appreciate your replay.
> 
> Now I have this (NLS Date Format dd/MM/yyyy)
> ![imagen](https://user-images.githubusercontent.com/40251003/54160180-7d13e000-4414-11e9-90e2-bc844234c2eb.png)
> 
> Date format value dd/MM/yyyy
> ![imagen](https://user-images.githubusercontent.com/40251003/54159813-86e91380-4413-11e9-85ef-0cf2b2c4adb0.png)
> 
> Same as above dd/MM/yyyy
> ![imagen](https://user-images.githubusercontent.com/40251003/54160816-20192980-4416-11e9-8949-9bbf054d76f1.png)
> 
> CSV format dd/MM/yyyy
> ![imagen](https://user-images.githubusercontent.com/40251003/54159930-d3345380-4413-11e9-81e9-cde9ba2c6a36.png)
> 
> Import function dd/MM/yyyy
> ![imagen](https://user-images.githubusercontent.com/40251003/54160053-28706500-4414-11e9-8717-d8c6c5344d56.png)
> 
> The date was changed for example from 15/10/2018 to 10/03/2019
> ![imagen](https://user-images.githubusercontent.com/40251003/54160144-5d7cb780-4414-11e9-9bc7-cdcd7b6aa6c1.png)
> 
> Hope not missing anything this time.
> 
> Maybe this character don´t work well "/" and must be changed for "-".
> 
> Thanks again for your time.

Hi (or Pura vida!)

If you replace "/" with ".", it works.

**Comment by jschildgen** [comment]
Date/time format in inport setting is set to dd/MM/YYYY
![image](https://user-images.githubusercontent.com/11808058/84677038-75ec5380-af2e-11ea-8601-c2e42276fdbb.png)

**Comment by ZeroHager** [comment]
> > Hi,
> > You right, my mistake, I feel bad not noticing that, really appreciate your replay.
> > Now I have this (NLS Date Format dd/MM/yyyy)
> > ![imagen](https://user-images.githubusercontent.com/40251003/54160180-7d13e000-4414-11e9-90e2-bc844234c2eb.png)
> > Date format value dd/MM/yyyy
> > ![imagen](https://user-images.githubusercontent.com/40251003/54159813-86e91380-4413-11e9-85ef-0cf2b2c4adb0.png)
> > Same as above dd/MM/yyyy
> > ![imagen](https://user-images.githubusercontent.com/40251003/54160816-20192980-4416-11e9-8949-9bbf054d76f1.png)
> > CSV format dd/MM/yyyy
> > ![imagen](https://user-images.githubusercontent.com/40251003/54159930-d3345380-4413-11e9-81e9-cde9ba2c6a36.png)
> > Import function dd/MM/yyyy
> > ![imagen](https://user-images.githubusercontent.com/40251003/54160053-28706500-4414-11e9-8717-d8c6c5344d56.png)
> > The date was changed for example from 15/10/2018 to 10/03/2019
> > ![imagen](https://user-images.githubusercontent.com/40251003/54160144-5d7cb780-4414-11e9-9bc7-cdcd7b6aa6c1.png)
> > Hope not missing anything this time.
> > Maybe this character don´t work well "/" and must be changed for "-".
> > Thanks again for your time.
> 
> Hi (or Pura vida!)
> 
> If you replace "/" with ".", it works.

Thanks!
