### ISSUE TITLE
White background on search bar while typing in declaration using Dark Theme

### ISSUE THREAD

**Issue by novusnick** [dbeaver/dbeaver#5462]
While typing in the search bar on the table properties (from Open Declaration) using the dark theme, the background of the search bar goes white while the color of the text is light gray, making it nearly impossible to see what you're typing.  This looks to be an issue with all the dark themes.  Attached is a screen shot:
![whitebackground_search_bar](https://user-images.githubusercontent.com/44614842/54153342-5aca9400-440d-11e9-94c7-689512676739.png)

**Comment by robert-niestroj** [comment]
The problem is also in v6.0.2. It comes from the connection type. When you change to development it's OK.

![obraz](https://user-images.githubusercontent.com/9776384/56038233-b2705e00-5d31-11e9-84a2-c52bbcad4acd.png)

**Comment by uslss** [comment]
still actual in 6.3.2

**Comment by uslss** [comment]
not actual in 21.0.3

**Comment by robert-niestroj** [comment]
In 21.0.3 Dark Mode looks really good. Good Job Team!
