### ISSUE TITLE
Greenplum an error occurred while viewing the list of tables

### ISSUE THREAD

**Issue by zhongxiazhiye** [dbeaver/dbeaver#5464]
#### System information: 
- Operating system (distribution) and version
Windows 10 Home
- DBeaver version
6.0
- Java version 
1.8.0_11
- Additional extensions

#### Connection specification:
- Database name and version
Greenplum 4.3.14.0
- Driver name
Greenplum JDBC driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
An error occurred while viewing the list of tables
![image](https://user-images.githubusercontent.com/42224845/54169045-2ce85c80-44ac-11e9-8024-546566a83ee7.png)

**Comment by 4eburah** [comment]
Having same issue since Dbeaver 5.3.3.
My Greenplum is 4.3.16
Would be great to have a fix

**Comment by serge-rider** [comment]
I've fixed table reading query to support GP 4.x

**Comment by 4eburah** [comment]
> I've fixed table reading query to support GP 4.x

Спасибо, Серёг

**Comment by uslss** [comment]
verified
