### ISSUE TITLE
anonymous procedures/functions in a PL/SQL declare block result in error

### ISSUE THREAD

**Issue by snoop247** [dbeaver/dbeaver#5467]
Hello, 

at the moment I use

- Windows 10 Pro version 1703
- DBeaver Community Edition version 6.0.0.201903101945
- Java version 8 Update 201
- DBeaver Office Support

on an 

- Oracle Database 11g Release 11.2.0.3.0 - 64bit Production
- Driver name ojdbc8.jar

having this issue:
 
Whenever I try to use an anonymous procedure or function in an PL/SQL declare block I get the following error in DBeaver:

> Error
> 
>  occurred during SQL script execution
> 
> Ursache:
> SQL-Fehler [6550] [65000]: ORA-06550: Zeile 9, Spalte 29:
> PLS-00103: Fand das Symbol "end-of-file" als eines der folgenden erwartet wurde:
>
> begin function pragma procedure

My crude translation to English:
> Reason:
> SQL-Error[6550] [65000]: ORA-06550: row 9, column 29:
> PLS-00103: Found the symbol "end-of-file" when expecting one of the following:

When I use the same code with copy&paste in Oracle's sql developer it runs smoothly.

Searching for a solution on the internet I only found issues #445 and #996 and they are listed as related issues now.
They were about the declare block in general and closed, when there was added some support of this block.

So my questions are:

- Are anonymous procedures or functions in a declare block supported and I just get it wrong? If not, is it planned to support them in the future?
- Is this only working in Enterprise Edition?

Thank you in advance.

best regards
Daniel

**Comment by serge-rider** [comment]
Generally PL/SQL blocks parser work. But it some cases it may fail.
Please post an example of non-parseable block.

Workaround: select your SQL code and execute it with ctrl+enter.

**Comment by snoop247** [comment]
Hello serge-rider.

This problem occurs whenever I try to use an anonymous procedure or function. The following code blocks run perfectly well in Oracle's SQL Developer, but raise the given error in DBeaver.

```
DECLARE
    PROCEDURE my_procedure(message VARCHAR2)
    IS
    BEGIN
        dbms_output.put_line( SYSDATE || ': ' || message);
    END;
BEGIN
    my_procedure('hello world');
END;
```

```
DECLARE
    FUNCTION my_function(message VARCHAR2)
    RETURN VARCHAR2
    IS
    BEGIN
        dbms_output.put_line( SYSDATE || ': ' || message);
        RETURN 'done';
    END;
BEGIN
    dbms_output.put_line(my_function('hello world'));
END;
```

best regards
Daniel

**Comment by neiaberau** [comment]
using first example, if I select all code lines, myself then it works, 
if I just execute without selecting, it seems, the executed part is only up to the first end; , such as:

DECLARE
    PROCEDURE my_procedure(message VARCHAR2)
    IS
    BEGIN
        dbms_output.put_line( SYSDATE || ': ' || message);
    END;

**Comment by snoop247** [comment]
Hello neiaberau.

Your idea works well, if there is no issue selecting the lines manually. But I encountered a maybe similar problem with another script, that I use to create some objects.

In the case of an 
```CREATE TYPE myObj AS OBJECT ...```
 and afterwards 
```CREATE TYPE BODY myObj AS ...```
I would prefer to run it at once. At the moment I cannot run these `CREATE`s together, because if I do so, the `BODY` statement ends up in the object's `DECLARATION` as well, when I lookup the definition saved to the database. The ```BODY``` part is empty: ```--Empty source```. Only selecting and executing them separately does the trick. Control-Enter inside the first statement without selecting always triggers the second one simultaneously. The same happens if I execute the script, even with everything else commented. As if dbeaver is not able to separate the lines correctly.

Again in Oracle's SQL Developer there is no issue, apart from separating the blocks with a '/', but that I had to do with every other script with PL/SQL blocks mixed with create statements as well. I believe someone stated, that were due to the way SQL Developer parses the code.

Of course I do not know, if creating objects might not or even should not be a task you have to do often. Nevertheless do I use these objects for testing purposes only, so I drop them, when the testing is done. Also while debugging I have to run the script multiple times, ... 

best regards
Daniel

**Comment by neiaberau** [comment]
it is not only SQL developer, most oracle tools use ; for SQL statements as separator, however for code,  an / is needed (procedure, function, package, type)

It seems the parser of dbeaver does not cover this "oracle exception", maybe so far, because:
I see this note in the newest dbeaver version
    - PL/SQL blocks parser was improved
I have not checked, what this improved, as I have not installed it yet.

**Comment by snoop247** [comment]
Hello neiaberau.

Thank you again for explaining this to me. In the end it does not matter, if I have to use '/' or can skip it. I am willing to adjust. In general I prefer dbeaver and it's style over SQL Developer. Also the output of queries etc. seems really nice to me. Last but not least, there is much more functionality in dbeaver afaik! (and there is a VIM extension available, even it is more of a punishment for me at the moment. I still have to master most of the basics). 

So I would like to switch to dbeaver all the time. Until then I will use both. 

The new version might not be a solution since I already use v6.0.3.201904211926 and dbeaver says, it is the newest.

best regards
Daniel

**Comment by 100641690** [comment]
Would be really good to get full support for PL/SQL block terminators and DECLARE keyword. Can't stand SQLDeveloper's ugly interface, so I gave DBeaver a go. Looks a lot nicer but it's an inconvenience to execute each code block separately.

**Comment by uslss** [comment]
verified
