### ISSUE TITLE
Encountered the symbol "+" when expecting one of the following:   (

### ISSUE THREAD

**Issue by rajalakshmimohan1** [dbeaver/dbeaver#5468]
This is a program to print sum of first 10 prime numbers in plsql:
In line 14 and 16 I am encountering an error but I don't know why.
declare 
count number(2):=0;
sum number(2):=0;
i number(2):=0;
j number(2):=0;
begin
FOR j in 2..30
LOOP
FOR i in 2..(j-1)
LOOP
IF(j%i!=0) THEN
IF(i+1=j) THEN
count :=count + 1;
sum:=sum+j;
IF (count=9) THEN
dbms_output.put_line(sum);
END IF;
END IF;
ELSE
exit;
END IF;
END LOOP;
END LOOP;
END;
/

**Comment by snoop247** [comment]
You are using PL SQL keywords as variables. In this example 'count' and 'sum'. You should not use them, see here [https://docs.oracle.com/cd/B19306_01/appdev.102/b14261/reservewords.htm].

After I changed these variable names, it almost worked:

The sum eventually gets 3 digits, so there is an error raised. You need to use a NUMBER(3) for the sum.

regards
Daniel

**Comment by rajalakshmimohan1** [comment]
Thanks for sharing this information with me.



Regards,
Rajalakshmi Mohan Iyer
