### ISSUE TITLE
Quote blank string in Export Data to csv 

### ISSUE THREAD

**Issue by MocniMax** [dbeaver/dbeaver#5469]
#### System information: 
- Operating system - MS Windows Server 2008 R2
- DBeaver version 6.0.0
- Java version - DBeaver delivered
- Additional extensions - none

#### Connection specification:
- Database name and version - DB2 LUW 9.7.5
- IBM DB2
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Blank string values are not quoted with Export to csv and are not recognized by DB2 LOAD utility.
The Quote always is not an option because numeric fields are quoted also and cannot be always imported to DB2 (depends on table field type).
When I manual quote blank strings in generated csv file, everything works fine.

All Exporter settings are defult ones.

**Comment by uslss** [comment]
You could choose which symbols could be used instead o NULL strings in Data transfer settings
![image](https://user-images.githubusercontent.com/31996417/82099754-cb0b2e80-9710-11ea-9dba-9df51273495e.png)
