### ISSUE TITLE
ER Diagram : cannot see structure for MySQL

### ISSUE THREAD

**Issue by SaigneurDucon** [dbeaver/dbeaver#5470]
I have a problem using the ER Diagram functionality in DBeaver : it works for certain tables / relations but for most of the tables in our database it cannot map table relations (foreign keys etc.). 
Therefore when it successfully maps some relations for some tables, I cannot be sure the mapping is complete. 
So my question is : why ?
 To give an example : 

![image](https://user-images.githubusercontent.com/48484654/54222181-464cd100-44cb-11e9-9f87-27af902c1c9d.png)

vs

![image](https://user-images.githubusercontent.com/48484654/54222222-5bc1fb00-44cb-11e9-97cb-c59fce543b46.png)

This isa case of incomplete mapping in the case of the first screenshot vs the second. But for most tables in DB there are no mapped relations (even though these relations exist).

**Comment by SaigneurDucon** [comment]
Just anwsered my question using SHOW CREATE TABLE : no foreign keys declared on most tables.

**Comment by serge-rider** [comment]
Ok, closing
