### ISSUE TITLE
with MySQL the "open definition" function didn't use the catalog specified on the toolbar

### ISSUE THREAD

**Issue by rhjyy** [dbeaver/dbeaver#5474]
#### System information: 
- Operating system (distribution) and version : irrelevant 
- DBeaver version : 6.0.0
- Java version : irrelevant 
- Additional extensions : irrelevant 

#### Connection specification:
- Database name and version : MySQL 
- Driver name : irrelevant 
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  : irrelevant 

#### Describe the problem you're observing:
with MySQL,must specify catalog when use the "open definition" function in the SQL editor,even the catalog has been specified on the toolbar
#### Steps to reproduce, if exist:
1.connect a MySQL database
2.specify catalog on the toolbar
3.open a SQL editor
4.write some SQL with some objectname and no catalog,like:"select * from tablename",not:"select * from databasename.tablename"
5.point the mouse cursor in an objectname
6.press "F4" key
7.it will alert you "can't find metadata object for name ..."

**Comment by kseniiaguzeeva** [comment]
Can't reproduce it either. Have you tried newer versions? Is it still actual?

**Comment by rhjyy** [comment]
I've tried with 6.3.0 yesterday,it worked fine,I guess the bug has been fixed.
