### ISSUE TITLE
Date format in sql editor

### ISSUE THREAD

**Issue by siantex** [dbeaver/dbeaver#5479]
Hi, I'm having a problem with version 5.3.2 in windows with Informix database.

The fotmat in the output for datetime is dd/MM/yyyy HH:mm:ss and the output is correct "13/03/2019 10:01:05"
The problem is in the sql editor, because I can't use this format in the select

select * from TABLE where COLUM_DATETIME > '13/03/2019 01:01:01'

I have to do in this format

select * from TABLE where COLUM_DATETIME > '2019-03-13 01:01:01'

Any place where I can setup this format in the sql editor?

Thanx

**Comment by MocniMax** [comment]
Hi,

There should be a Settings check mark **Use native date/time format** in Properties -> Editors -> Data Editor -> Data Formats.

Checking it should solve your problem.

**Comment by siantex** [comment]
Hi and thanks for your answer.

This is the result with the check marked and not marked.
The correct would be with the check not marked. Both of them requires the date in this format '2019-03-13', if I user this format '13/03/2019' the result is an sql error "SQL Error [IX000]: String to date conversion error"

![2019-03-13_13-11-45](https://user-images.githubusercontent.com/48279107/54278046-ab6afa00-4591-11e9-974c-e28764f39159.png)
![2019-03-13_13-12-48](https://user-images.githubusercontent.com/48279107/54278047-ab6afa00-4591-11e9-9e33-72d8e6bdeb33.png)

**Comment by MocniMax** [comment]
Usually date/time format is database dependent - it depends on database instance settings set in time database is created (or even database engine is installed). If your Informix database uses hyphen as date fields separator (what looks to be true based on Use Native table display) your queries should follow same syntax. 
I am using same yyyy-MM-dd format for queries on my AIX and zOS db2 installations.

Hope this helps.

**Comment by siantex** [comment]
Hi MocniMax, I told this to my sysadmin and he told me that the db is with the date format _dd/MM/yyyy_ and if you try to do a select directly in informix you can do it like _**SELECT * FROM TABLE WHERE COLUMNDATE = "01/01/2019 00:00:01"**_

**Comment by MocniMax** [comment]
Such data transformation is usually database driver implementation related and dependent.
In such a case your should narrow possible installation environment influence by using Informix CLI from your Windows session as base functionality and default behavior.
If it works as described from your Windows session then analyze which Informix driver is used by CLI and which one you use from DBeaver. If they are not the same or their defaults are not the same, correct it in DBeaver and it should work.

Hope this helps.

**Comment by nokiz** [comment]
Go to edit your db connection (or press F4 with your connection selected), then go to driver properties tab and add a new property (bottom button "+"), name it **DBDATE** and input **dmy4/** as value. Name and value may change depending on your needs but this works for me on date format.
