### ISSUE TITLE
DB2: DBeaver not sending complete sql to the database on create trigger

### ISSUE THREAD

**Issue by jjjbos** [dbeaver/dbeaver#5480]
#### System information:  
- Operating system (distribution) and version: Windows 10 64-bit
- DBeaver version: 6.0.0
- Java version: 8 update 201 
- Additional extensions: - Office Support
                                     - SVG Extension

#### Connection specification:
- Database name and version: DB2 LUW 11.1
- Driver name: db2jcc4.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing:

I'm trying to create a trigger in the DB2 database via a SQL statement:

---------------------------
-- DDL Statements for Triggers
---------------------------
--#SET TERMINATOR @
CREATE OR REPLACE TRIGGER SAP_BOBW.CPB_DELTA_INSERT_11
AFTER INSERT ON 
	VEST11.CPB
REFERENCING
	NEW AS newrow
	NEW_TABLE AS TEMP_CPB_DELTA_INSERT
FOR EACH ROW
MODE
	DB2SQL
BEGIN 
	ATOMIC
	DECLARE SYSTEM_DATE CHAR(8); -- 
	SET SYSTEM_DATE = 	(select
							to_char(CURRENT DATE,'YYYYMMDD')
						from 
							vest11.SYS 
						where 
							SYS_SLEUTEL = '1'); -- 
	IF NOT EXISTS (
		SELECT
			*
		FROM
			VEST11.DELTA_CPB
		WHERE
			CPB_KODE_DK = newrow.CPB_KODE_DK
			AND CPB_DEBNR_KRDNR = newrow.CPB_DEBNR_KRDNR
			AND CPB_HOOFDORDERNR = newrow.CPB_HOOFDORDERNR
			AND CPB_RECORDNR = newrow.CPB_RECORDNR
			AND DELTA_CPB_DATE = SYSTEM_DATE
			AND DELTA_CPB_OPERATION = 1)
	THEN
		INSERT INTO VEST11.DELTA_CPB (
			CPB_KODE_DK,
			CPB_DEBNR_KRDNR,
			CPB_HOOFDORDERNR,
			CPB_RECORDNR,
			DELTA_CPB_DATE,
			DELTA_CPB_OPERATION)
		VALUES (
			newrow.CPB_KODE_DK,
			newrow.CPB_DEBNR_KRDNR,
			newrow.CPB_HOOFDORDERNR,
			newrow.CPB_RECORDNR,
			SYSTEM_DATE,
			1); -- 
	END IF; -- 
END@

This statement is working when I use the DB2 command center. If I use DBeaver, I'll get SQL errors saying  "missing end of statement". So using the trace option, I see that not the complete statement is send to the database (See attached trace file: [trace_sds_1.log](https://github.com/dbeaver/dbeaver/files/2960383/trace_sds_1.log)). Can this be fixed?

**Comment by titou10titou10** [comment]
This is because DBeaver does not interpret the`"--#SET TERMINATOR @"`directive. This directive is proprietary and only valid when run by the DB2 CLI
To achieve what you want to do, you must change the "Statement delimiter" from the default ";" to "@":
Menu "Preferences" then 
`Database > Editors > SQL Editors > SQLprocessing`thenDelimiters /Statement delimiters`` 
Denis

**Comment by jjjbos** [comment]
Thanks, this solution works.

Jeroen
