### ISSUE TITLE
SAP ASE user-defined functions do not show in Database Navigator

### ISSUE THREAD

**Issue by hardburger** [dbeaver/dbeaver#5483]
#### System information: 
DBeaver running on Windows 7
DBeaver	5.3.5.201902181142	org.jkiss.dbeaver.core.product
java.version=1.8.0_201

#### Connection specification:
Sybase ASE 16 SP02
jdbc connection   com.sybase.jdbc4.jdbc.SybDriver
The driver type however shows as MS SQL Server

#### Describe the problem you're observing:
Whether split or included with Procedure, user-defined functions do not appear in the Database Navigator.

#### Steps to reproduce, if exist:
select * from sysobjects where type = 'SF'
these same objects are not found anywhere in Navigator
Note that sql-server used types 'FN', 'IF', 'FN', 'AF', 'FS', 'FT'

**Comment by nlosada** [comment]
It also can be replicated in las t Community Version:

**System information:**
DBeaver running on Windows 8.1
DBeaver Version 6.2.1.201909221630
java.version=1.8.0_201

**Connection specification:**
Sybase ASE 16 SP02
jdbc connection com.sybase.jdbc4.jdbc.SybDriver
The driver type however shows as MS SQL Server

**Describe the problem you're observing:**
Whether split or included with Procedure, user-defined functions do not appear in the Database Navigator.

**Comment by uslss** [comment]
is it still actual?

**Comment by nlosada** [comment]
Yes.

Is still present in the current community Version:
  DBeaver	6.3.3.202001191557

**Comment by nlosada** [comment]
Just checked and still present inDBeaver	7.0.1.202003211804

**Comment by DonHaul** [comment]
This was happening to me as well,  try editing connections and setting this to Advanced
![image](https://user-images.githubusercontent.com/13081142/94811561-6ca7c980-03ed-11eb-9c8b-59b829294184.png)

**Comment by nlosada** [comment]
Mine is already in Advanced. Also tried customizing it. But is still the same.
We are talking about ASE, not PostreSQL. Might be different.

**Comment by LonwoLonwo** [comment]
Reading Sybase functions implemented in DBeaver 21.0.3
They are in Procedures list. And functions also have Source tab with function DDL.
But, unfortunately, function parameters not reading from driver, and I did not find them in system tables.
We will be happy with ideas and suggestions about this.

**Comment by uslss** [comment]
verified
