### ISSUE TITLE
Hidden characters in text view

### ISSUE THREAD

**Issue by oxk4r01** [dbeaver/dbeaver#5485]
Hi. In text view, the width of some columns is insufficient, and impedes some characters to shown.
Can I setup DBeaver to use a minimum column width in result set text view?
Regards.

**Comment by uslss** [comment]
it could be changed in preferences
![image](https://user-images.githubusercontent.com/31996417/76968198-8d20a280-6939-11ea-8e8c-43a2722023e6.png)
