### ISSUE TITLE
dbeaver 6.0 export to csv

### ISSUE THREAD

**Issue by pressanykeytostop** [dbeaver/dbeaver#5486]
Hi,

I have a question regarding export data from MS SQL 2012 server using latest Dbeaver 6.0 on windows 10.

Data should be exported with CSV, UTF-8 format, semicolon as delimiter.

The problem occurs where there is an record  in table with  semicolon in description as in the attached picture
![image](https://user-images.githubusercontent.com/48528396/54301204-c738c500-45be-11e9-9687-66fc53e99c45.png)
 
The problem with export in CSV is that the semicolon is detected as a delimiter and not as description itself:
![image](https://user-images.githubusercontent.com/48528396/54301419-2e567980-45bf-11e9-8296-0be6729558b6.png)

How can this scenario be avoided?

Thank you for replay.

**Comment by MocniMax** [comment]
Hi,

Did you try with Exporter Settings **Quote always** option?

**Comment by pressanykeytostop** [comment]
Yes! It Works.  
Thank you.
