### ISSUE TITLE
Dark Theme update request for 6.0

### ISSUE THREAD

**Issue by crokusek** [dbeaver/dbeaver#5488]
#### System information: 
- Windows 10
- DBeaver 6.0
- JRE w/6.0

#### Connection specification:
- Sql Server

#### Describe the problem you're observing:
Dark theme colors recommendations:

1) Recommend on Windows, use the cleaner fixed font "Consolas 11" instead of "Courier New 10" for the  text setting that becomes the editor's default text.

2) Recommend background for text editor and data grid to be black.  The new attached preference file should indicate this.  If there is objection to this how about compromise halfway to black?

3) After evaluating a fresh download of 6.0, the text editor colors seem to dim from #5184. There may have been a mix-up on the preference file that was uploaded.   A new preference file is attached with just the diffs from 6.0.

[DBeaverPrefsV6.epf.txt](https://github.com/dbeaver/dbeaver/files/2964235/DBeaverPrefsV6.epf.txt)

4) Side note, could a new preference be added for SQL Variables of the format @abc (user) and @@abc (system)?

#### Steps to reproduce, if exist:
Download 6.0,  Set Dark Theme.  Take first impression. 
Non-black Background feels like fog in the text editor and data grid.  Elsewhere's great.
Text Editor Colors are too dim.
Courier New is not a very clean font.

**Comment by bogdan-calapod** [comment]
I'd also add that the separator lines being white / light gray in the Windows theme doesn't make for a pretty impression as well, I tried changing them into the appearance section but couldn't find the correct value (the names of the values there are a bit cryptic as well).

**Comment by uslss** [comment]
seems it is obsolete issue
