### ISSUE TITLE
dbeaver hive connection - non default databases

### ISSUE THREAD

**Issue by m2karthik** [dbeaver/dbeaver#5489]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
While connecting to mapr-hive via dbeaver, how do we turn off  "show non-default databases" option which is by default listing all databases. My hive has 1000's of databases and it takes a lot of time doing so and need it to fetch and show only the database i setup the connection to.
version used - dbeaver 5.3.3

**Comment by francescmallafre** [comment]
+1

**Comment by uslss** [comment]
is it still actual against 22.0,2?

**Comment by uslss** [comment]
There has been no update on the issue for a long time.  If it is still reproducible - feel free to reopen it
