### ISSUE TITLE
[Feature request] Nice to have different icons for script files and link files

### ISSUE THREAD

**Issue by amivanovano** [dbeaver/dbeaver#5490]
Hi, Serge.

Subj.

TIA,
Alex

**Comment by amivanovano** [comment]
OR make column Type in scripts list corresponding Type in Properties. 

![image](https://user-images.githubusercontent.com/28041955/65749363-9fe6b700-e10e-11e9-804a-d611c54f6f38.png)

**Comment by serge-rider** [comment]
Implemented in #9353

**Comment by uslss** [comment]
verified
