### ISSUE TITLE
Customized date format fails on filtering

### ISSUE THREAD

**Issue by maurorulli** [dbeaver/dbeaver#5493]
#### System information: 
- Windows 7 x64
- DBeaver 6.0.0
- JRE8

#### Connection specification:
- MS SQL Server
- SQL Server

#### Describe the problem you're observing:
I can't filter on Date or Date/Time fields due to a conversion error form varchar to date/time. I realized that the SqlServer has a customized date format.
I have customized Dates Formats for this specific datasource in [connection properties]->Editors->[Data Formats]->Unchecked [Use native date/time format] -> set new values for Data Type and Data/Time Type. Now I can get the correct date format on the results grid. Filtering with [F11] key show finally the correct suggestions on the cascade menu, but when I select one of these options I get again the standard date/time typed on filter box and again the message error reported above.

#### Steps to reproduce, if exist:
Check above section.

#### Include any warning/errors/backtraces from the logs
!ENTRY org.jkiss.dbeaver.model 1 230 2019-03-14 09:22:09.265
!MESSAGE SELECT * FROM ALADB_DP1.dbo.STATO_FE
WHERE [Data Documento] <> '2014-12-31 00:00:00.000'
!SUBENTRY 1 org.jkiss.dbeaver.model 4 242 2019-03-14 09:22:09.298
!MESSAGE La conversione di un tipo di dati varchar in datetime ha generato un valore non compreso nell'intervallo dei valori consentiti.

![dbeaver](https://user-images.githubusercontent.com/3530373/54342905-e4f93f00-463d-11e9-8802-6f9caf6e64d6.png)

**Comment by serge-rider** [comment]
Try to use native date/time format:
![image](https://user-images.githubusercontent.com/6398845/62531752-57fc8f80-b843-11e9-8b76-9e1f45154ee4.png)
