### ISSUE TITLE
Not give auto complete with phoenix driver

### ISSUE THREAD

**Issue by john086** [dbeaver/dbeaver#5494]
#### System information: 
- Windows 7/10
- DBeaver version 6.0
- Java version 1.8 

#### Connection specification:
- Database HBASE 
- Driver name phoenix hbase client
- Using proxy 

#### Describe the problem you're observing:
Not give auto complete with phoenix driver (auto complete only on table and not on colomuns of this)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by serge-rider** [comment]
Added in #7676

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
