### ISSUE TITLE
Missing special characters after paste string with "AS" keyword

### ISSUE THREAD

**Issue by freylis** [dbeaver/dbeaver#5495]
#### System information: 
- Operating system (distribution) and version: CentOS Linux release 7.5.1804
- DBeaver version: 6.0.0.201903101945
- Java version: 1.8.0_191
- Additional extensions: none

#### Describe the problem you're observing:

I have some query, like this
```
SELECT
    "SomeNameOfTable"."PrimaryKey" -- source
FROM
    ...
```
If I want to copy-paste second line in this query, I got correct result, like this:
```
SELECT
    "SomeNameOfTable"."PrimaryKey" -- source
    "SomeNameOfTable"."PrimaryKey" -- pasted
FROM
    ...
```
But if source string which contains "AS" keyword, after paste I got string without special characters, like this:
```
SELECT
    "SomeNameOfTable"."PrimaryKey" AS "FOO" -- source
    SomeNameOfTablePrimaryKeyFOO -- pasted
FROM
    ...
```
And bonus! I can return all special characters with press "ctrl + z":
```
SELECT
    "SomeNameOfTable"."PrimaryKey" AS "FOO" -- source
    "SomeNameOfTable"."PrimaryKey" AS "FOO" -- pasted + "ctrl+z"
FROM
    ...
```
My friend with Win version have same problem

**Comment by uslss** [comment]
issue isn't reproducible for now.
