### ISSUE TITLE
Postgis : save table as SQL produce non executable SQL

### ISSUE THREAD

**Issue by mukoki** [dbeaver/dbeaver#5500]
DBeaver 6.0.0.
Exporting data containing geometry to a SQL script file.
The command produces insert statements containing geometry data as simple WKT text without quotes. This script cannot be executed.
It probably should export HEX data representing the binary representation of the geometry.

**Comment by Ricardo-C-Oliveira** [comment]
This is the one bug that forces me to use Navicat, which creates executable SQL files from spatial tables.

**Comment by uslss** [comment]
seems that issue is already fixed
