### ISSUE TITLE
Arrow-keys navigation and refreshing limited in table editor

### ISSUE THREAD

**Issue by jest** [dbeaver/dbeaver#5505]
#### System information: 
- Operating system (distribution) and version: Linux Mint 19 (Ubuntu 16.04)
- DBeaver version 6.0.0
- Java version 11

#### Connection specification:
- Database name and version SQL Server 2017
- Driver name SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

In 6.0.0 navigation in table editor on columns that are referencing other columns (i.e. have FOREIGN KEY-s applied to them) has changed. This results in current cell loosing focus on keyboard navigation and refreshing.

This is a regression from 5.3.5, where arrow keys and F5 could be used to freely navigate on the table cells, then pressing F2 to change the value in a given cell.

#### Steps to reproduce, if exist:

Open table editor on non-empty table, "Data" tab, with "Value" view enabled (F7). Click on any cell in column that has an arrow in it (indicating that it's a reference to another column). Navigate up-down. Observe how the focus is moved to the "Value" text field (in 5.3.5 the focus stayed on the table) and its content is selected.

Navigate left-right. As the focus is in the text field, you are navigating in the text field (in 5.3.5 navigation on the table editor was performed).

Press F5 to refresh the table content. Observe as the focus is moved from the cell to the text field again (in 5.3.5 it stayed in the table).

Turning "Value" view off allows for pre-6.0 navigation.

**Comment by pyrocks** [comment]
Happens to me too - for FK columns the focus automatically moves to the value tab - disallowing further left/right arrow navigation on the table.

**Comment by jest** [comment]
Right, looks like fixed in 6.0.1. Although in-place editing is broken there (#5575), so upgrade to 6.0.2 is required to get back sensible keyboard navigation on the table editor.
