### ISSUE TITLE
information panels does not work (ctrl + left click)

### ISSUE THREAD

**Issue by Rafaelmignoni** [dbeaver/dbeaver#5508]
i usually use crtl + left click to open information panels, but since version 6.0 it dont work.

have new shortcut for this?

**Comment by serge-rider** [comment]
There were no changes  in panels sortcuts in 6.0. Maybe the problem is in something else.
Do you mean hyperlinks navigation in SQL editor or something else?

**Comment by Rafaelmignoni** [comment]
the problem occur just in oracle database.

I take this message : "can't find metadada object for name ... "

**Comment by uslss** [comment]
hi @Rafaelmignoni , is issue still actual for you?
