### ISSUE TITLE
Ambigious names

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#5509]
There is ambiguous: is this tab `script-1` or `script-15`
![IMG20190315210334](https://user-images.githubusercontent.com/799021/54456048-e32a9b00-4765-11e9-99bd-1f15175ef353.jpg)

DBeaver version is 5.3.5

**Comment by uslss** [comment]
Title pattern could be changed in Preferences
![image](https://user-images.githubusercontent.com/31996417/76967809-f358f580-6938-11ea-9e02-b5461c90a73a.png)

**Comment by KES777** [comment]
Please provide useful pattern by default.
