### ISSUE TITLE
Support for autocomplete of inbuild functions for a DB server

### ISSUE THREAD

**Issue by igupta** [dbeaver/dbeaver#551]
Currently Dbeaver doesn't support autocomplete for inbuild function for db server.

**Comment by lacanoid** [comment]
I second that!

**Comment by serge-rider** [comment]
Generally DBeaver supports autocomplete for functions.
What is your database?

**Comment by igupta** [comment]
MS SQL server 2014

**Comment by lacanoid** [comment]
PostgreSQL 9.4. Autocomplete popup (after typing schema name and dot) shows only tables and views, but no functions.

**Comment by ideamotor** [comment]
This is similar to what I mentioned at https://github.com/serge-rider/dbeaver/issues/500. As well as user-created functions, it should work for functions in extensions and/or enable the user to create their own list of autocomplete keywords. It would also be nice if the user could add a description for each keyword that shows up as a tooltip, although I'm not sure if this is possible.

Here's an example in RStudio, an R IDE:

![image](https://cloud.githubusercontent.com/assets/1654283/16812051/f898078c-48f0-11e6-8db1-d2df58a7e30d.png)

If the user could hit F1 or other hotkey to go to an associated help page, that would be amazing. I'd be happy to make a spreadsheet with names, descriptions, and links for PostGIS/PostgreSQL..

**Comment by jgonzale** [comment]
As described @lacanoid, it will be very useful to me if DBEaver suggest also the stored procedures on a schema! Any forecast for this feature @serge-rider ?

Thank you very much, DBEaver is GREAT!

**Comment by serge-rider** [comment]
This feature will be implemented along with #810 (fully functional SQL Server extension)

**Comment by LonwoLonwo** [comment]
Implemented here https://github.com/dbeaver/dbeaver/issues/10533
Autocomplete for procedure and functions works after keywords SELECT (if "Show stored procedures in column list" checked, CALL, EXEC/EXECUTE(SQLServer) [schemaname][.] ctrl+space in SQL Editor

![2020-12-15 12_49_46-Preferences](https://user-images.githubusercontent.com/45152336/102199021-26361700-3ed4-11eb-81bb-c6fdf995ada6.png)

**Comment by fvannee** [comment]
This only shows the functions in the column list. However, often functions are used in the relation-part of the query, but this does not show up in DBeaver. Is there another option to show auto-complete for functions here?

```
CREATE OR REPLACE FUNCTION public.test_f(_val int)
 RETURNS table (a int)
 LANGUAGE sql
 IMMUTABLE PARALLEL SAFE
AS $function$
   SELECT * FROM generate_series(1, _val)
$function$
;

-- here dbeaver does not show autocomplete for test_f
select * from public.test_f(10);
```

**Comment by robin-bourgeon-eficia** [comment]
I agree with the previous comment: the functions that return tables should appear in the relation-part of the query and not in the column-part.

**Comment by fvannee** [comment]
I've opened this issue for it: https://github.com/dbeaver/dbeaver/issues/20261
