### ISSUE TITLE
Alter Session not working 

### ISSUE THREAD

**Issue by nouchutm** [dbeaver/dbeaver#5511]
Hi Team,

I have tried to run the below statement in Oracle DB connection

alter session set time_zone = 'Asia/Bahrain'

After run I got response like below, This statement not working with DBEaver

Updated Rows	0
Query	alter session set time_zone = 'Asia/Bahrain'
Finish time	Sun Mar 17 17:02:24 GST 2019

**Comment by uslss** [comment]
seems that issue was fixed. ticket closed
