### ISSUE TITLE
Drill drivers configuration lose drivers after restart

### ISSUE THREAD

**Issue by rubenswise** [dbeaver/dbeaver#5512]
#### System information: 
- Operating system (distribution) and version:  MacOS 10.14.3 
- DBeaver version: 6.0
- Java version: embedded with DBeaver 6.0
- Additional extensions: Git

#### Connection specification:
- Database name and version: Drill 1.15.0
- Driver name: hadoop-common and drill-jdbc-all
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Describe the problem you're observing:
Once created two artifact into drill drill drivers settings (hadoop common 2.7.0 and drill-jdbc-all 1.15.0) the connection works fine, but when i close dbeaver and reopen it, it alway lose drill-jdbc-all artifact and all the time i have to recreate it

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on issue. if it is still actual for you - feel free to reopen it

**Comment by mzatko** [comment]
same extremely annoying problem here with dbeaver 23.1.3, ubuntu
