### ISSUE TITLE
Feature Request: Add Option to Show Errors in Result Pane

### ISSUE THREAD

**Issue by isapir** [dbeaver/dbeaver#5515]
Currently Errors are shown in a modal message box, e.g.

![Screenshot from 2019-03-17 14-22-40](https://user-images.githubusercontent.com/885907/54498140-4af4f900-48c0-11e9-9f0f-2d6056949ac2.png)

It'd be great if there was an option to show the Error in the Result pane instead, without showing the modal dialog.

**Comment by serge-rider** [comment]
We already have a couple of similar/related FRs.
Generlly I agree. Modal dialogs suck.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/55294672-825dbc80-540d-11e9-9c60-070c62765a54.png)
![image](https://user-images.githubusercontent.com/6398845/55294682-9dc8c780-540d-11e9-88b7-43e5e2eed40d.png)

**Comment by isapir** [comment]
Thank you, @serge-rider!

**Comment by uslss** [comment]
Verified

**Comment by ausiddiqui** [comment]
this is the most amazing feature! thank you @serge-rider

**Comment by guedel** [comment]
There is a regression on version 24.0.2.202404071654. Despite deactivate option the errors are diplayed in dialog box.
