### ISSUE TITLE
mysql int type show not right ,dbeaver version 6.0.0

### ISSUE THREAD

**Issue by 815559417** [dbeaver/dbeaver#5524]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/17718705/54575096-cb853800-4a2d-11e9-8424-304156286159.png)

**Comment by uslss** [comment]
thanks for the bug report.
Issue is reproducible in case "Minimum fraction digits">0

**Comment by serge-rider** [comment]
@uslss Is it really a bug? If you set minimum fraction digits then dbeaver shows at least that many fraction digits (filled with zeros if needed).
Don't set this parameter if you don't need it.

Also extra trailing zeroes may appear after enabling "Use data type scale for fraction digits". Thus for data type like NUMERIC (10,10) dbeaver will show 10 fraction digits (always).
Again - disable it if you don't need it.
![image](https://user-images.githubusercontent.com/6398845/67767639-03436c00-fa62-11e9-8b28-deffa9a17da7.png)

**Comment by uslss** [comment]
@815559417 could you share table ddl? it would be very helpful for issue investigation
