### ISSUE TITLE
Hotkeys doesn't work

### ISSUE THREAD

**Issue by breakmt** [dbeaver/dbeaver#5525]
#### System information: 
- Windows 10
- dbeaver 6.0
- java 1.8
- hotkeys is standard

#### Connection specification:
- postgresql

#### Describe the problem you're observing:
Some hotkeys doesn't work - F11, F7.

#### Steps to reproduce, if exist:
Open table, select cell, press F11 or F7 - nothing is happening. 
It was ok in version 5.2.5

**Comment by threat0day** [comment]
also doesn't work comment hotkeys

**Comment by breakmt** [comment]
Any news on this? I can't update cause of this error

**Comment by uslss** [comment]
Issue is already fixed and not reproducible in version 6.0.1 and later.

**Comment by threat0day** [comment]
> https://stepik.org/course/16478/syllabus
https://careers.epam.by/content/dam/epam/by/book_epam_by/Software_Testing_Basics_2_izdanie.pdf

the problem is gone
