### ISSUE TITLE
Greenplum: missing information in the generated DDL

### ISSUE THREAD

**Issue by lintzc** [dbeaver/dbeaver#5526]
Hello,

When you double-click on a table in the browser and choose DDL in the right panel, the generated DDL has missing information:
    - storage option: like with (appendonly=true, compresstype=zlib,orientation=column)

When you right-click on a table in the browser and choose Generate DDL, the generated DDL has missing information:
    - Storage option
    - Privileges
    - Comments
    - Indexes

Thanks.

**Comment by lmacedo-pivotal** [comment]
I am impacted by the same issue.

**Comment by serge-rider** [comment]
We already support privileges, comments and indexes in Greenplum DDL.
From storage options we support only DISTRIBUTED clause.
Looks like all we need is to add ENCODING information and PARTITIONS information.

Unfortunately I'm not very familiar with GP metadata tables. I will need some assistance with that..

**Comment by lmacedo-pivotal** [comment]
You are missing the with clause (table storage type). That is very important information for the dba. Check https://gpdb.docs.pivotal.io/6-0/ref_guide/sql_commands/CREATE_TABLE.html.

One way to find out catalog queries is to install gpdb locally and use "psql --echo-hidden" to show all queries issued to produce the output. It will give you all the catalog queries you need to build the DLL. When you run \dS+ schema.table it will give you all information and print all queries  issued by psql.

I hope this helps.

**Comment by lmacedo-pivotal** [comment]
> We already support privileges, comments and indexes in Greenplum DDL.
> From storage options we support only DISTRIBUTED clause.
> Looks like all we need is to add ENCODING information and PARTITIONS information.
> 
> Unfortunately I'm not very familiar with GP metadata tables. I will need some assistance with that..

@serge-rider does my comment above help?

**Comment by serge-rider** [comment]
@lmacedo-pivotal we use direct selects from system (pg_catalog) tables to generate DDL. It is not possible to use psql in most cases (usually it is not installed on local machine).
So we need to find another way.

**Comment by buravchenko** [comment]
Hello! Unfortunately, there were changes in Creenplum 6.0 and now DBeaver generates incorrect "distributed by" DDL for this new version of the DB. Can you please improve this? Using the method mentioned above (psql --echo-hidden), you can generate necessary SQL statements for direct selects from the DB. For instance, I received the following statements:

gpadmin@pd-db-1:~$ psql --echo-hidden test
psql (9.4.24)
Type "help" for help.

test=# \d+ test_table
********* QUERY **********
SELECT c.oid,
  n.nspname,
  c.relname
FROM pg_catalog.pg_class c
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.relname OPERATOR(pg_catalog.~) '^(test_table)$'
  AND pg_catalog.pg_table_is_visible(c.oid)
ORDER BY 2, 3;
**************************

********* QUERY **********
select pg_catalog.version()
**************************

********* QUERY **********
select oid from pg_catalog.pg_class where relnamespace = 11 and relname  = 'pg_attribute_encoding'
**************************

********* QUERY **********
SELECT c.relchecks, c.relkind, c.relhasindex, c.relhasrules, c.relhastriggers, c.relhasoids, pg_catalog.array_to_string(c.reloptions || array(select 'toast.' || x from pg_catalog.unnest(tc.reloptions) x), ', ')
, c.reltablespace, CASE WHEN c.reloftype = 0 THEN '' ELSE c.reloftype::pg_catalog.regtype::pg_catalog.text END, c.relpersistence, c.relreplident
, c.relstorage as relstorage FROM pg_catalog.pg_class c
 LEFT JOIN pg_catalog.pg_class tc ON (c.reltoastrelid = tc.oid)
WHERE c.oid = '16544';
**************************

********* QUERY **********
SELECT a.attname,
  pg_catalog.format_type(a.atttypid, a.atttypmod),
  (SELECT substring(pg_catalog.pg_get_expr(d.adbin, d.adrelid) for 128)
   FROM pg_catalog.pg_attrdef d
   WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum AND a.atthasdef),
  a.attnotnull, a.attnum,
  (SELECT c.collname FROM pg_catalog.pg_collation c, pg_catalog.pg_type t
   WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation) AS attcollation,
  NULL AS indexdef,
  NULL AS attfdwoptions,
  a.attstorage ,
  CASE WHEN a.attstattarget=-1 THEN NULL ELSE a.attstattarget END AS attstattarget,
  pg_catalog.col_description(a.attrelid, a.attnum)
FROM pg_catalog.pg_attribute a
LEFT OUTER JOIN pg_catalog.pg_attribute_encoding e
ON   e.attrelid = a .attrelid AND e.attnum = a.attnum
WHERE a.attrelid = '16544' AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum;
**************************

********* QUERY **********
SELECT c2.relname, i.indisprimary, i.indisunique, i.indisclustered, i.indisvalid, pg_catalog.pg_get_indexdef(i.indexrelid, 0, true),
  pg_catalog.pg_get_constraintdef(con.oid, true), contype, condeferrable, condeferred, i.indisreplident, c2.reltablespace
FROM pg_catalog.pg_class c, pg_catalog.pg_class c2, pg_catalog.pg_index i
  LEFT JOIN pg_catalog.pg_constraint con ON (conrelid = i.indrelid AND conindid = i.indexrelid AND contype IN ('p','u','x'))
WHERE c.oid = '16544' AND c.oid = i.indrelid AND i.indexrelid = c2.oid
ORDER BY i.indisprimary DESC, i.indisunique DESC, c2.relname;
**************************

********* QUERY **********
SELECT c.oid::pg_catalog.regclass FROM pg_catalog.pg_class c, pg_catalog.pg_inherits i WHERE c.oid=i.inhparent AND i.inhrelid = '16544' ORDER BY inhseqno;
**************************

********* QUERY **********
SELECT c.oid::pg_catalog.regclass FROM pg_catalog.pg_class c, pg_catalog.pg_inherits i WHERE c.oid=i.inhrelid AND i.inhparent = '16544' ORDER BY c.oid::pg_catalog.regclass::pg_catalog.text;
**************************

********* QUERY **********
SELECT pg_catalog.pg_get_table_distributedby('16544')
**************************

                         Table "public.test_table"
 Column  |  Type   | Modifiers | Storage  | Stats target | Description
---------+---------+-----------+----------+--------------+-------------
 address | inet    | not null  | main     |              |
 rating  | integer | not null  | plain    |              |
 info    | text    |           | extended |              |
Indexes:
    "test_table_pkey" PRIMARY KEY, btree (address, rating)
Distributed by: (address)

**Comment by lmacedo-pivotal** [comment]
Found out about a function called pg_get_partition_def that returns partition definition. 

Select pg_get_partition_def(tablename::regclass, true, true) will get you detailed info. Might  be very verbose!

Select pg_get_partition_def(tablename::regclass, true, false) will get summarized partition definition which should be what we are looking for.

**Comment by lmacedo-pivotal** [comment]
@serge-rider with the function above we solve the partition information problem!  :)

**Comment by maratkalibek** [comment]
What improved:

- `WITH` option now has more friendly output
- `PARTITION BY` is also generated for DDL

**Comment by uslss** [comment]
verified
