### ISSUE TITLE
Error message: bad data type name when trying to set a new column’s data type by clicking on a suggestion

### ISSUE THREAD

**Issue by maffe** [dbeaver/dbeaver#5528]
#### System information: 
- Windows 10
- DBeaver 6.0.0
- Java 8

#### Connection specification:
- PostgreSQL 11 database
- PostgreSQL driver 42.2.5

#### Describe the problem you're observing:
When adding a column via the GUI, filling the datatype field by clicking on a suggestion doesn’t work.

#### Steps to reproduce, if exist:
Type partial data type name, click on suggestion (`integer` in this case)
![grafik](https://user-images.githubusercontent.com/515302/54616074-6fd3a280-4a5f-11e9-9ca8-6d77aa71ea27.png)
Error message appears
![grafik](https://user-images.githubusercontent.com/515302/54616106-7b26ce00-4a5f-11e9-8e02-8e443bb61053.png)

**Comment by uslss** [comment]
verified
