### ISSUE TITLE
5.3.5 display issues

### ISSUE THREAD

**Issue by GeorgeHastingsAGBR** [dbeaver/dbeaver#5530]
Hi Guys,

I'm having some issues with the way DBeaver is displaying on my system. Each dialog box has two borders...
See below image.

I'm running the latest version of Elementary OS.

![DisplayIssues](https://user-images.githubusercontent.com/47366838/54618344-cb4f6180-4a5a-11e9-9586-4edeffcfbcfc.png)

**Comment by uslss** [comment]
ticket closed.
if issue is still actual for you, feel free to reopen the ticket
