### ISSUE TITLE
Dashboards on statistics table with history

### ISSUE THREAD

**Issue by Sargul** [dbeaver/dbeaver#5531]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
6.0.0
- Java version 
bundled JRE
- Additional extensions
None

#### Connection specification:
- Database name and version
Exasol but basically any other
- Driver name
exajdbc.jar - com.exasolJDBc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no
#### Describe the problem you're observing:
Some databases allready collect statistics for longer periods of time (not just snapshots).
It would be great to have an option in the dashboard configuration to select a history column (timestamp or date column of the table) and a range (SQL-Expression) for that column which will be used for the dashboard.

#### Steps to reproduce, if exist:
-

**Comment by serge-rider** [comment]
Hey @Sargul ,
Sond very interesting. We going to add many more dashboards in near releaes.
Could you post some examples?
If this is Exasol specific then we'll need to setup demo server for that.

**Comment by Sargul** [comment]
Hey @serge-rider,

it's not specific to Exasol.

In mysql/mariadb there is the performance schema and some tables are not snapshots but contain a history of information. Same for some DB2 tables.

So the regular dashboards basically execute an SQL every x ms seconds and plot the data.

But some system tables already contain data over a range of time.

Exasol collects a lot of information over long periods of time so basically you don't have to do this kind of snapshot queries at all and just display the data for the last hours/days/months.

I'm not sure if I was able to describe this in a good way.

**Comment by serge-rider** [comment]
Yes, it is quite clear, thanks. But I'll need some real world example and SQL I can use to test this kind of dashboards. Could you post it?
E.g. some query returning data for last X minutes.

**Comment by Sargul** [comment]
In that case I would go with Exasol as an example:
`SELECT
	MEASURE_TIME,
	USERS as "Established Connections",
	QUERIES as "Executing Connections"
FROM
	EXA_STATISTICS.EXA_USAGE_LAST_DAY 
ORDER BY`
![image](https://user-images.githubusercontent.com/5595511/54706674-c1535e80-4b3f-11e9-9210-30f6a348023a.png)

or
`SELECT
	MEASURE_TIME,
	MEM_OBJECT_SIZE as "Compressed Database size",
	RAW_OBJECT_SIZE as "Uncompressed Database size"
FROM
	EXA_STATISTICS.EXA_DB_SIZE_LAST_DAY
ORDER BY
	MEASURE_TIME ;`
![image](https://user-images.githubusercontent.com/5595511/54706804-1000f880-4b40-11e9-9299-6f587dc03a39.png)

**Comment by serge-rider** [comment]
Done. 
See Exasol dashboards as an example.
Note new fetch type (stats) and new property `interval` (can be millisecond, second, minute, hour, day, week, month, year).

![image](https://user-images.githubusercontent.com/6398845/55560458-ebd51800-56f8-11e9-8d55-355fcbc707c8.png)

Feel free to add new dashboards. If some config param is still missing - please ask.

**Comment by uslss** [comment]
Reopened. Interval config issue
![20190405_00h41_11](https://user-images.githubusercontent.com/31996417/55590731-65422a00-573c-11e9-99f9-f82067b2b36e.gif)

**Comment by serge-rider** [comment]
It was unrelated to interval settings but a bug in bar->ts view change.

**Comment by uslss** [comment]
Verified
