### ISSUE TITLE
Procedure using domain as parameter (Firebird)

### ISSUE THREAD

**Issue by rogeriobettini** [dbeaver/dbeaver#5532]
I'm experiecing the same problem as reported in this issue: [https://github.com/dbeaver/dbeaver/issues/2842](https://github.com/dbeaver/dbeaver/issues/2842)
This issue was closed without solution but I think there is a problem in DBeaver.

I created a procedure with one of input parameters using a domain called MOEDA NUMERIC(15,2). 
If I try to view the procedure code in dbeaver, I notice that my parameter (that uses MOEDA domain) became NUMERIC.
And if I use that code to edit the procedure, the parameter accepts only integer numbers.

When I edit the same procedure using FlameRobin, the same parameter is shown correctly - using MOEDA domain.
That's the reason I beleave there is a bug in DBEaver. 

PS: That procedure was initialy created using FlameRobin.
The Firebird version is 3.0.2

**Comment by tarbul** [comment]
Hi serge-rider,

I think this is a serious bug. When dbeaver reads stored procedure's source code it loses the scale of numeric data types. They basically become integers! 

## Example
I have a procedure parameter of type numeric(15,4) and I execute this sql script 

`CREATE OR ALTER PROCEDURE P_PONOVI_DEPOZIT (P_RACUN_ID INTEGER, P_ZNESEK NUMERIC(15,4))
RETURNS (
	P_RACUN_ID_NOV INTEGER
)...`

in dbeaver. If I execute this procedure "execute procedure P_PONOVI_DEPOZIT (...)" it works as expected (it accepts a decimal parameter like 91.002). But when I open this procedure in SQL console its source changes to

`CREATE OR ALTER PROCEDURE P_PONOVI_DEPOZIT (P_RACUN_ID INTEGER, P_ZNESEK NUMERIC)
RETURNS (
	P_RACUN_ID_NOV INTEGER
)`

The parameter "P_ZNESEK **NUMERIC(15,4)**" changes to "P_ZNESEK **NUMERIC**". Procedure parameter P_ZNESEK changes to NUMERIC when I execute this script, the parameter becomes basically an INTEGER (zero scale).

As you know NUMERIC and NUMERIC(15,4) are two different data types:

EG:
`select cast (123.456 as numeric), cast (123.456 as numeric(15,5)) from RDB$DATABASE`

returns 

`123	123.45600`

When I execute "execute procedure P_PONOVI_DEPOZIT (...)" and I set P_ZNESEK to 92.11 all the procedure gets is a 92!

## Proposed solution

As you mentioned in #2842 you take procedure source from the table *rdb$procedures*. 

EG: 
`select rdb$procedure_source `
`from rdb$procedures `
`where rdb$procedure_name = 'P_PONOVI_DEPOZIT'`

That is correct. But you should also get procedure parameters data from the data dictionary, i.e. *rdb$procedure_parameters* https://www.firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref-appx04-procparams.html

EG:
`select rpp.rdb$parameter_name,rpp.RDB$FIELD_SOURCE -- domain`
`from rdb$procedure_parameters rpp`
`where rdb$procedure_name = 'P_PONOVI_DEPOZIT'`

returns	
`P_RACUN_ID                     	RDB$5394`
`P_RACUN_ID_NOV                 RDB$5395`
`P_ZNESEK                       	RDB$5398`

RDB$FIELD_SOURCE is
> The name of the user-created domain, when a domain is referenced instead of a data type. If the name starts with the prefix 'RDB$', it is the name of the domain automatically generated by the system for the parameter.

Parameter types are defined in *rdb$fields* https://www.firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref-appx04-fields.html

EG: 
`select rf.rdb$field_precision, rf.rdb$field_scale `
`from rdb$fields rf`
`where rf.rdb$field_name = 'RDB$5398'`

returns

`15	-4`

This is **numeric(15,4)**. And this is the right data type that should be used when you read procedure source of P_PONOVI_DEPOZIT from the dictionary.

I use firebrid 2.5.9, win7, dbeaver 6.2.5.
  
:+1: Keep up the good work. In my opinion Dbeaver is the greatest free tool for firebird development.

**Comment by tarbul** [comment]
@uslss could you add these two labels: bug and x:firebird

**Comment by tarbul** [comment]
@kseniiaguzeeva could you please add these two labels: bug and x:firebird to this issue?

**Comment by serge-rider** [comment]
In fact it is a bug in Jaybird driver. As dbeaver uses function getProcedureSourceCode in DatabaseMetaData implemetation to read procedure source (https://github.com/FirebirdSQL/jaybird/blob/d1931f552cc96ae30ae127d9c7011df144b9492a/src/main/org/firebirdsql/jdbc/FBDatabaseMetaData.java#L3525)

**Comment by serge-rider** [comment]
Fixed

**Comment by tarbul** [comment]
Thanks! Works like a charm. 

When I open the same procedure P_PONOVI_DEPOZIT the _Source_ is right
```
CREATE OR ALTER PROCEDURE P_PONOVI_DEPOZIT (P_RACUN_ID INTEGER, P_ZNESEK NUMERIC(15,4))
RETURNS (
	P_RACUN_ID_NOV INTEGER
)
```

The only glitch I see is in _Procedure parameters_ in column Length:
![slika](https://user-images.githubusercontent.com/58310674/73555325-b8186b00-444d-11ea-91cb-8de7b25568aa.png)

**Comment by tarbul** [comment]
I think you should mark #7364 as solved.

**Comment by tarbul** [comment]
There is another problem. Dbeaver replaces parameters that are domains with their types in procedure's source code. If I create a domain

`CREATE DOMAIN TMP_MOEDA NUMERIC(15,2)` 

and a procedure is using it

```
CREATE OR ALTER PROCEDURE test_moeda (P_STOLPEC TMP_MOEDA)
RETURNS (
   P_ID INTEGER
)
AS
begin
  p_id = 123;
  suspend;
end
```
and I open this procedure in dbeaver the Source I get is "wrong"

```
CREATE OR ALTER PROCEDURE TEST_MOEDA (P_STOLPEC NUMERIC(15,2))
RETURNS (
	P_ID INTEGER
)
AS
begin
  p_id = 123;
  suspend;
end
```

If open the same procedure in flamerobin, domain parameters are preserved
in procedure view

![slika](https://user-images.githubusercontent.com/58310674/73557157-02e7b200-4451-11ea-9253-db5ccdb52153.png)

and in source view

![slika](https://user-images.githubusercontent.com/58310674/73557224-214dad80-4451-11ea-97c7-05aed362e3b1.png)

**Comment by serge-rider** [comment]
@tarbul yep, but this is another bug.
Please create a new ticket for this. We'll try to solve it in one of near releases.
