### ISSUE TITLE
changed font colour

### ISSUE THREAD

**Issue by harmnot** [dbeaver/dbeaver#5534]
<img width="579" alt="Screen Shot 2019-03-20 at 00 25 35" src="https://user-images.githubusercontent.com/42674439/54627851-d4feb680-4aa6-11e9-8afb-145630c91a32.png">

how to changed the font text on DBeaver? I tried to find out and searching on google but still can't fix for 2 days :(

**Comment by akilovich** [comment]
Now we adjust the font color depending on the background color to make everything look contrasting.

**Comment by kseniiaguzeeva** [comment]
verified
