### ISSUE TITLE
build sql  exist error

### ISSUE THREAD

**Issue by xfzhaoxd** [dbeaver/dbeaver#5538]
#### System information: 
- Win10
- DBeaver version 6.0
- Java version 11
- Additional extensions

#### Connection specification:
- Database name and version   MySql 5.7
- Driver name                      mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

when table exist primary field and unique key field，build sql->update sql
we can get update sql, but where condition use unique key field ,not primary field

**Comment by uslss** [comment]
cannot reproduce an issue.
if it is still actual for you - feel free to reopen the ticket
