### ISSUE TITLE
[Feature Request] Ability to change the auto assign feature to map types to types that I want

### ISSUE THREAD

**Issue by edheadonfire** [dbeaver/dbeaver#5540]
Example use case trying to convert sqlserver to mysql 
and the column is nvarchar(-1) and it naturally maps to varchar but I want it to map to text.

**Comment by uslss** [comment]
data types could be changed manually in data transfer dialog
![image](https://user-images.githubusercontent.com/31996417/127989071-579ffd72-6a86-4fe2-9242-903e313e8875.png)
