### ISSUE TITLE
wrong entry in german context menu --> "Datei umbennen"

### ISSUE THREAD

**Issue by jensonwe** [dbeaver/dbeaver#5544]
#### System information: 

- DBeaver Community Edition 6.0.0
- Language: German

#### Describe the problem you're observing:

- In the (german) context menu of an open SQL editor the entry "Datei umbennen" is wrong. The correct entry must be "Datei umbenennen".
See also  https://www.duden.de/suchen/dudenonline/umbenennen

**Comment by uslss** [comment]
Thanks for reporting issue. i18n ticket was created.

**Comment by uslss** [comment]
Verified
