### ISSUE TITLE
Is there any way to change the default charset and collation in the 'Create new database' dialog?

### ISSUE THREAD

**Issue by the-ge** [dbeaver/dbeaver#5547]
#### System information: 
- Kubuntu 18.10
- DBeaver 6.0.0.201903101945
- Java version: OpenJDK 11.0.1

#### Connection specification:
- MariaDB 10.1 or 10.3

#### Describe the problem you're observing:
When creating a new database, DBeaver defaults to the `utf8` charset and `utf8_general_ci `collation, regardless of the server setting.
My servers (development Docker containers) use the `utf8mb4` charset and `utf8mb4_unicode_ci` collation. Databases created with `CREATE DATABASE database_name;` in the MySQL command line comply with the server settings (of course).

I was expecting that for the `Create new database` form, DBeaver would be reading the server settings and then would change the proposed charset and collation accordingly. Also, an option to change the defaults would be nice, because clicking the dropdowns for every database created gets old fast.

So, my question is this: is there any way to change/set the charset and collation proposed by the `Create new database` form?

Thank you.

![image](https://user-images.githubusercontent.com/6468893/54780434-68a8c200-4c22-11e9-84df-43797dbc8ef0.png)

**Comment by serge-rider** [comment]
I guess we can use variable `character_set_server` for default charset detection.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/55495882-8cb6cb00-5646-11e9-99b3-5f86ce03e91a.png)

**Comment by serge-rider** [comment]
Now it uses `character_set_server` and `collation_server` for default charset and collation

**Comment by uslss** [comment]
verified
