### ISSUE TITLE
Can't go next when import CSV

### ISSUE THREAD

**Issue by rico345100** [dbeaver/dbeaver#5549]
I imported csv file which also exported from DBeaver from other co-worker with same table, but I can't click next in preview. There's no error indicates, just next button disabled and can't go forward. Some CSV files works fine, but others not. What should I do check?

#### System information: 
- Operating system (distribution) and version macOS 10.13.6
- DBeaver version 6.0.0.201903101945
- Java version 11.0.2 2019-01-15 LTS
- Additional extensions

#### Connection specification:
- Database name and version PostgresSQL 11.1
- Driver name PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I explained before, anyway next button is not clickable in preview mode when try to importing CSV.

#### Include any warning/errors/backtraces from the logs

I checked the logs but there's no related information there. Here's the link of log file:
https://drive.google.com/open?id=1uaqwLN-hZ9Q0U-u3gxT3y1682z6TN_Dm

Note that the table name I'm trying to import is "payment".

**Comment by PeledYuval** [comment]
+1 to this. I have the exact same problem. Please notify if solution is found.

**Comment by uqix** [comment]
Any progress?

**Comment by serge-rider** [comment]
To enable Next button you need to configure mappings for all table columns.
![image](https://user-images.githubusercontent.com/6398845/60520472-bdf67400-9ce5-11e9-905c-0337b9ba8870.png)
