### ISSUE TITLE
Navigation link with join tables

### ISSUE THREAD

**Issue by rsanchez-tiqueteo** [dbeaver/dbeaver#5550]
#### System information: 
- Operating system (distribution) and version:  Debian 9 (Linux 4.9.0-8-amd64 x86_64)
- DBeaver version: 6.0.0
- Java version:  1.8.0_201

#### Connection specification:
- Database name and version: mysql 5.7
- Driver name: mysql-connector-java:RELEASE 5.1.44

#### Describe the problem you're observing:
When join some table that has the same foreign key, the navigation link goes always to the first id.
EX:
select * from reservation join reservation_extra using (reservation_id) where reservation_id=11111;
Then both, reservation and reservation_extra have an event_id. Then the link goes always to the reservation table event_id, it can distinguish both event_id.

#### Steps to reproduce, if exist:
EX:
select * from reservation join reservation_extra using (reservation_id) where reservation_id=11111;
Then both, reservation and reservation_extra have an event_id. Then the linkg goes always to to the reservation table event_id, it can distinguish both event_id.

Kind regards.

**Comment by uslss** [comment]
cannot reproduce it.
if issue is still actual for you - feel free to reopen the ticket
