### ISSUE TITLE
CockroachDB: Error appears when trying to create function

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#5557]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.0.1

#### Connection specification:
- Database name and version Cockroach DB 2.0.5

#### Describe the problem you're observing:
Error appears when trying to create function. Language dropdown list is empty.
![proc_create](https://user-images.githubusercontent.com/31996417/54849749-38325800-4cf6-11e9-8365-28671867b44b.gif)
[funct_create.log](https://github.com/dbeaver/dbeaver/files/2998100/funct_create.log)

**Comment by serge-rider** [comment]
Fixed (CDB doesn't support function create)

**Comment by uslss** [comment]
verified
