### ISSUE TITLE
Custom ERD refresh issue

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#5561]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.0.1

#### Describe the problem you're observing:
Refreshing of custom diagram leads to changes loss, if user didn't previously save it.
Example:
![erd_issue](https://user-images.githubusercontent.com/31996417/54855470-800dab00-4d07-11e9-94c8-11d4831f1219.gif)

**Comment by serge-rider** [comment]
Fixed (in fact it works as expected but we need to show confirmation dialog for this action)

**Comment by uslss** [comment]
verified
