### ISSUE TITLE
Failed to find a main class in...

### ISSUE THREAD

**Issue by HTMLGuyLLC** [dbeaver/dbeaver#5567]
#### System information: 
Mac OSX 10.14
DBeaver 6.0.0

#### Connection specification:
N/A

#### Describe the problem you're observing:
Trying to open DBeaver, immediately hit with this error:

<img width="423" alt="Screen Shot 2019-03-24 at 3 07 27 PM" src="https://user-images.githubusercontent.com/2415447/54884389-ba319680-4e46-11e9-946f-5ee57a6a26de.png">

**Comment by HTMLGuyLLC** [comment]
Happens on older version too.

**Comment by serge-rider** [comment]
What dbeaver distr do you use (pkg, dmg or zip archive)?

**Comment by HTMLGuyLLC** [comment]
Dmg. Gave up on it

**Comment by serge-rider** [comment]
This looks like a corrupted installation (dbeaver.ini contents doesn't match the version of actually installed produce).
Could you try to reinstall 6.0.1 (the most recent version of DBeaver)? Put existing DBeaver in trash before that.

**Comment by Neonchen** [comment]
This error could occur when dbeaver can't find a java version. For example if you use sdkman to manage java versions dbeaver can't find the installation. On mac you can getting into the installed dbeaver version and edit the Info.plist file and add the full path at the bottom:
```
<key>Eclipse</key>
	<array>
		<string>-vm</string>	
		<string>/Users/<username>/.sdkman/candidates/java/current/jre/bin</string>
		<string>-keyring</string><string>~/.eclipse_keyring</string>
	</array>
```
Source: https://askubuntu.com/questions/1014157/dbeaver-with-sdkman-jre-jdk-location

**Comment by asterizk** [comment]
Reproduced in DBeaver 6.1.4 from .dmg on macOS 10.13.6. Neonchen's workaround above did not help (did not change error message, which remained as in screenshot below). I tried using '/usr/bin/java', and '/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java' as the value of my 'vm' argument.  Note the line I added varied slightly from Neonchen's suggestion, in that I followed the example provided in the 6.1.4 Info.plist and included a dash before 'vm', e.g.:

`<string>-vm</string><string>/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java</string>`

Would like to figure out what's going on -- let me know if I can answer any questions about my environment. 

srq4399:~ kgreenwell$ which java
/usr/bin/java
srq4399:~ kgreenwell$ ls -l /usr/bin/java
lrwxr-xr-x  1 root  wheel  74 Jun 21  2018 /usr/bin/java -> /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java
srq4399:~ kgreenwell$ ls -l /System/Library/Frameworks/JavaVM.framework/Versions
total 0
drwxr-xr-x  11 root  wheel  352 Nov  7  2018 A
lrwxr-xr-x   1 root  wheel    1 Jun 21  2018 Current -> A
srq4399:~ kgreenwell$ ls -l /System/Library/Frameworks/JavaVM.framework/Versions/A/
total 80
drwxr-xr-x  52 root  wheel    1664 May 29  2018 Commands
drwxr-xr-x   4 root  wheel     128 May 29  2018 Frameworks
drwxr-xr-x  14 root  wheel     448 Nov  7  2018 Headers
drwxr-xr-x   3 root  wheel      96 Oct  7  2017 JavaPluginCocoa.bundle
-rwxr-xr-x   1 root  wheel  107872 May 29  2018 JavaVM
-rw-r--r--   1 root  wheel    2529 Jul 25  2018 JavaVM.tbd
drwxr-xr-x   3 root  wheel      96 Nov  7  2018 Modules
drwxr-xr-x  46 root  wheel    1472 Jun 21  2018 Resources
drwxr-xr-x   3 root  wheel      96 Dec  7  2017 _CodeSignature
srq4399:~ kgreenwell$ /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
srq4399:~ kgreenwell$

![Screen Shot 2019-08-13 at 6 16 04 PM](https://user-images.githubusercontent.com/6105333/62981180-991e1200-bdf6-11e9-90f9-5d93a23420a7.png)

**Comment by serge-rider** [comment]
DBeaver require Java 8 at least.

Please use pkg installer - it is already bundled with proper Java.

**Comment by asterizk** [comment]
Thanks @serge-rider , appreciate the quick reply, will give it a shot

**Comment by asterizk** [comment]
> DBeaver require Java 8 at least.
> 
> Please use pkg installer - it is already bundled with proper Java.

Worked like a charm, thank you very much!

**Comment by amatosg** [comment]
sorry to bring this _old_ issue, but this also happens with latest dbeaver version (as of today) installed using dmg image and Java 11 through sdkman:
```
java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20191016_371 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+10)
```

**Comment by serge-rider** [comment]
@amatosg did you install dbeaver from pkg installer? If so then it doesn't matter what Java is installed on your MacOS.

**Comment by amatosg** [comment]
No, I installed using the dmg file. I've installed using the pkg and it works, but I still wanted to let you know that the dmg still fails
