### ISSUE TITLE
Scrolling down takes focus to first column in results

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#5571]
Under some circumstances which I haven't been able to identify, when viewing the results of a long query in the results pane, if I scroll rightwards (horizontally) towards the last columns and then scroll downwards (vertically) and fetch more rows, then once new rows are fetched, the horizontal scrolling would automatically reset to the first column.

I recall this was not an issue in previous versions.

Setup: DBeaver 6.0.0, running on windows 10.

**Comment by uslss** [comment]
Issue is reproducable. 
![resultset](https://user-images.githubusercontent.com/31996417/54949549-6612d900-4f50-11e9-82f5-08c7fff0110a.gif)

**Comment by uslss** [comment]
already fixed.
ticket closed
