### ISSUE TITLE
cockroachdb: CockroachDB-specific type names not supported in "create table" interface

### ISSUE THREAD

**Issue by rolandcrosby** [dbeaver/dbeaver#5572]
#### System information: 
- Windows 10 Pro 1809
- DBeaver 6.0.0.201903101945

#### Connection specification:
- CockroachDB 2.1.6

#### Describe the problem you're observing:
When editing a table's DDL in DBeaver, several CockroachDB data types are unsupported in the "add column" dialog box, failing with errors that look like this:

<img src="https://user-images.githubusercontent.com/60245/54952574-a9535480-4f1c-11e9-91c1-74728d2ec7ed.png" width="389">

The data types I've occurred this happening for include:
- string
- bit
- varbit
- array (e.g. int[])
- bytes

#### Steps to reproduce, if exist:
- Connect to a CockroachDB database in DBeaver
- Create a table and go to the "Columns" tab
- Right-click on the grid and select "Create New Column"
- In the "Data Type" box, type one of the CockroachDB types listed above

**Comment by rolandcrosby** [comment]
cc @awoods187 to track on the CockroachDB compatibility side

**Comment by uslss** [comment]
Issue cannot be reproduced on 6.0.4

**Comment by rolandcrosby** [comment]
This still reproduces on DBeaver 6.0.4 for me:
![dbeaver](https://user-images.githubusercontent.com/60245/57556602-771f7a00-7345-11e9-954f-0e94cead5933.gif)

**Comment by serge-rider** [comment]
Arrays and extra CDB type aliases were added

**Comment by uslss** [comment]
verified
