### ISSUE TITLE
Feature Request: Support KDB

### ISSUE THREAD

**Issue by lozbrown** [dbeaver/dbeaver#5576]
Its a long shot but it would be really good to have basic support for KDB+ time Series DBs

JDBC drivers exist and are available: 
https://code.kx.com/q/interfaces/jdbc-client-for-kdb/
https://github.com/bjconlan/kdb-jdbc

KX Systems KDB is a very expensive time series DB used heavily in financial services for Tick and trade analytics. Proper Q highlighting and IDE suggestions would be wonderful but basic support for Q queries (in my favorite DB client) would be pretty cool at this point. 

KDB on-demand licences can be obtained pretty easily for personal use but i can probably expose a basic DB to the internet pretty easily if that helps

**Comment by serge-rider** [comment]
I can't find where to download JDBC driver. 
Aren't you aware - is it available in binary somewhere? As I see they don't have Maven artifact but some official direct download link will also work.

**Comment by lozbrown** [comment]
I'm not aware of a binary download of it but i believe this is the source from the official repo
https://github.com/KxSystems/kdb/blob/master/c/jdbc.java
I think you would have to compile it. 

Additionally not relevant to the above conversation but the following may be useful if there is interest in highlighting 
https://github.com/timeseries/kdb/tree/master/setup-kdb

**Comment by lozbrown** [comment]
Actually I think this might be the pre-compiled JAR from the same repo

https://github.com/KxSystems/kdb/blob/master/c/jdbc.jar?raw=true

**Comment by serge-rider** [comment]
You can test it in Early Access version (https://dbeaver.io/files/ea)

**Comment by lozbrown** [comment]
Not very successful I'm afraid

![image](https://user-images.githubusercontent.com/9961593/55944769-3b5b9c80-5c41-11e9-9b98-04a609bdd50a.png)

**Comment by serge-rider** [comment]
Well, this looks like a driver error. Not sure what can I do from dbeaver side.
Have you ever worked with kdb jdbc driver? maybe some special settings must be set during connection instantiation..

**Comment by lozbrown** [comment]
I'm afraid not, Generally [its not recommended ](https://github.com/KxSystems/kdb/tree/master/c) but I was hoping it worked sufficiently to be able to use my favorite database client. Other options are not ideal and often have strange licenses

**Comment by serge-rider** [comment]
Perhaps this error should be filed in the kdb GH issue tracker (https://github.com/KxSystems/kdb/issues)

**Comment by uslss** [comment]
verified

**Comment by lozbrown** [comment]
@uslss what do you mean, verified that its broken or verified that it works?

**Comment by lozbrown** [comment]
@serge-rider 
BTW, this works fine in SQL Workbench
![image](https://user-images.githubusercontent.com/9961593/72263669-3d5bed00-3611-11ea-8400-a3742ed8fd0b.png)
but not in DBeaver

![image](https://user-images.githubusercontent.com/9961593/72263625-2917f000-3611-11ea-8ebb-7ba71dc35e30.png)
