### ISSUE TITLE
Incorrect behaviour of horizontal scroll bar in results grid

### ISSUE THREAD

**Issue by bobf32** [dbeaver/dbeaver#5578]
#### System information: 
- Win 7 Enterprise SP1
- DBeaver 5.2.5 + 6.0.1
- Bundled Java version 
- No additional extensions

#### Connection specification:
- Oracle 12
- OJDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No.

#### Describe the problem you're observing:

I am trying to scroll horizontally through a result list. I want to do this a 'page' at a time rather than one column at a time. This does not seem to work, as the horizontal scrollbar seems not to adhere to standard behaviour.

#### Steps to reproduce, if exist:

When clicking in the white space in the horizontal area, to either side of the scroll bar, the results grid shifts only one column to the left or right. The same behaviour, in other words, as when clicking on either arrow at the end of the scroll bar.

What I think should happen is that the results grid should shift by as many columns as are visible to the user.

#### Include any warning/errors/backtraces from the logs

![1](https://user-images.githubusercontent.com/6544564/54982936-ba937400-4fa3-11e9-84ee-17d10d11ac19.png)
![2](https://user-images.githubusercontent.com/6544564/54982937-ba937400-4fa3-11e9-8774-f74a418a5947.png)
![3](https://user-images.githubusercontent.com/6544564/54982938-bb2c0a80-4fa3-11e9-890a-103d7e4a1ccc.png)

**Comment by amivanovano** [comment]
I agree. It is unexpected behavior!

**Comment by basz** [comment]
I would like to add that on macOS horizontal scrolling seems broken too.

**Comment by PachowStudios** [comment]
It also seems as if you cannot scroll partially through a column. This is very annoying for columns with very long values as I can't see the rest of the value if it's wider than the screen because it scrolls completely past the column to the next one.

**Comment by felix-penrose** [comment]
DBeaver 7.2.1 - via software centre snap
Ubuntu 20.04

I'm noticing a similar problem, not sure if it's the same. Essentially, Shift + horizontal scroll either moves one column from it's current view, or it allows normal scrolling for a partial view of the results e.g. it will scroll fine between 20% and 85% of the columns. If I repeatedly attempt to scroll back and forth, this "good" scroll region changes (reduces, but not evenly) and eventually doesn't work at all.

This seems to work a little better if the application window is smaller, but snapped to the left half of my screen it's almost useless.

**Comment by uslss** [comment]
will be implemented in #10184
