### ISSUE TITLE
Autocomplete picks wrong table columns in subquery

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#5580]
If I call the autocomplete options in a subquery within parentheses, the autocomplete will show the column names of the table from the main query instead of the one from the subquery. Example:
```sql
select
	some_col
from main_table
where
	other_col not in (select other_col, <try to autocomplete> from other_table ot where <try to autocomplete>)
```
The autocomplete inside `(select other_col from other table)` will keep showing the column names from `main_table` instead of those from `other_table`.

**Comment by kseniiaguzeeva** [comment]
Still reproduces in 7.0.1

**Comment by serge-rider** [comment]
Similar to #5467

**Comment by uslss** [comment]
#7768

**Comment by LonwoLonwo** [comment]
Still reproducible in DBeaver 23.0.5

**Comment by E1izabeth** [comment]
We will solve this issue in scope of https://github.com/dbeaver/dbeaver/issues/21654
