### ISSUE TITLE
using git inside dbeaver

### ISSUE THREAD

**Issue by AryehGielchinsky** [dbeaver/dbeaver#5581]
Not sure if this is a feature request, or a misunderstanding of a feature on my part.

We have an ETL on a server with a git repo that stores our code. I'd like to be able to commit, pull, push, and see different versions of a file within dbeaver.

I see that dbeaver has git intergration here #2427 , and I've installed that pluggin, but can't figure out how to use it. When I open a file locally that is in our repo, I don't see any git related options anywhere.

Thanks

#### System information: 
- Operating system: Ubuntu 18.04
- DBeaver version: 6.0.0
- Java version: openjdk version "1.8.0_191" 
- Additional extensions: Git integration for Eclipse 5.1.0.201809111528-r	

#### Connection specification:
- Database: Vertica
- Do you use tunnels or proxies (SSH, SOCKS, etc)?   SSH

**Comment by serge-rider** [comment]
Alpha version of DBeaver/Git UI integration wil be added in 6.1.2.
In Comunity Edition it will be available as a separate free extension (similar to Office or Debugger).
In EE it will be bundled right into the product distribution package.

**Comment by serge-rider** [comment]
Further Git integration improvements will be tracked in another tickets.
