### ISSUE TITLE
PostgreSQL create column whith uppercase

### ISSUE THREAD

**Issue by greenpeas** [dbeaver/dbeaver#5582]
dbeaver 6.0.1
![image](https://user-images.githubusercontent.com/3856344/54995142-1d523300-4fd7-11e9-8ea0-9e496eb02bf6.png)
![image](https://user-images.githubusercontent.com/3856344/54995178-335ff380-4fd7-11e9-8407-a2b77c3ce626.png)
![image](https://user-images.githubusercontent.com/3856344/54995209-41157900-4fd7-11e9-8009-e45923ff463f.png)

**Comment by serge-rider** [comment]
In order to create columns or table in upper/mixed case you need to enclose object name in quotes. E.g. `"SVG_MAP"`.
