### ISSUE TITLE
DriverClass keep loosing in Connection Settings

### ISSUE THREAD

**Issue by vincenzocaselli** [dbeaver/dbeaver#5586]
I created a new datatabase Connection to a SQL Server db.
It works successfully, but at every IDE restart the Driver class is empty.
Every time I have to:
- right click on the connection, Edit Connection (F4)
- push "Edit Driver Settings" button
- verify that "Driver class" combo is empty
- push "Find Class" button
- select Driver class in the combo
- push "OK"
then I can use it correctly.

Is there a way (e.g. edit .dbeaver-data-sources.xml manually) to persist such info?
Thank you very much
Vincenzo

#### System information: 
- Operating system (distribution) and version: 
  Linux (Ubuntu Budgie 18.10 & Manjaro Deepin, same behaviour for both)
- DBeaver version (6.0 and 6.0.1) on Eclipse 2018-09 JEE (4.9.0)
  
- Java version
  Oracle jdk1.8.0_192

- Additional extensions
  None

#### Connection specification:
- Database name and version
  mssql-server 14.0.3076.1-2

- Driver name
  Microsoft JDBC Driver for SQL Server
  sqljdbc4.jar

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
 No

#### Log stacktrace

!SESSION 2019-03-26 18:46:56.320 -----------------------------------------------
eclipse.buildId=4.9.0.I20180906-0745
java.version=1.8.0_192
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -data file:/home/vincenzo/dev/dev-qav/qav-standalone/wrk/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.jface 2 0 2019-03-26 18:47:08.370
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2019-03-26 18:47:08.370
!MESSAGE A conflict occurred for CTRL+8:
Binding(CTRL+8,
	ParameterizedCommand(Command(ch.itemis.xdocker.ui.commands.searchDockerImagesCommand,Search Images,
		,
		Category(ch.itemis.xdocker.ui.commands.category,Xdocker Category,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@7c8537e9,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+8,
	ParameterizedCommand(Command(org.jkiss.dbeaver.core.rollback,Rollback,
		Rollback changes in current session,
		Category(org.jkiss.dbeaver.core.database,Connection,Database Connection Commands,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@42d4de20,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,gtk,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2019-03-26 18:47:08.370
!MESSAGE A conflict occurred for ALT+SHIFT+D R:
Binding(ALT+SHIFT+D R,
	ParameterizedCommand(Command(org.eclipse.wst.server.launchShortcut.debug,Debug on Server,
		Debug the current selection on a server,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@2cc9a5a2,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+SHIFT+D R,
	ParameterizedCommand(Command(org.eclipse.rap.tools.launch.RAPLaunchShortcut.debug,Debug RAP Application,
		Debug RAP Application,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@1ff35ee7,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2019-03-26 18:47:08.370
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@4a9c188f,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
		,
		Category(org.eclipse.lsp4e.category,Language Servers,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@2e5dea22,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2019-03-26 18:47:08.370
!MESSAGE A conflict occurred for CTRL+SHIFT+V:
Binding(CTRL+SHIFT+V,
	ParameterizedCommand(Command(org.eclipse.jdt.debug.ui.command.OpenFromClipboard,Open from Clipboard,
		Opens a Java element or a Java stack trace from clipboard,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@4fd8aefe,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+V,
	ParameterizedCommand(Command(org.jkiss.dbeaver.core.edit.paste.special,Advanced Paste,
		Paste with extra settings,
		Category(org.jkiss.dbeaver.core.util,Utility,Utility Commands,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@4a59d584,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2019-03-26 18:47:08.370
!MESSAGE A conflict occurred for CTRL+SHIFT+A:
Binding(CTRL+SHIFT+A,
	ParameterizedCommand(Command(org.eclipse.pde.ui.openPluginArtifact,Open Plug-in Artifact,
		Open a plug-in artifact in the manifest editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@60abe420,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+A,
	ParameterizedCommand(Command(org.jkiss.dbeaver.core.navigator.set.active,Set active,
		Set object active ,
		Category(org.jkiss.dbeaver.core.navigator,Database Navigator,Database Navigator Commands,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@21e60eed,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2019-03-26 18:47:08.370
!MESSAGE A conflict occurred for ALT+SHIFT+X R:
Binding(ALT+SHIFT+X R,
	ParameterizedCommand(Command(org.eclipse.wst.server.launchShortcut.run,Run on Server,
		Run the current selection on a server,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@2b43eb71,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+SHIFT+X R,
	ParameterizedCommand(Command(org.eclipse.rap.tools.launch.RAPLaunchShortcut.run,Run RAP Application,
		Run RAP Application,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@2f32fe68,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

**Comment by serge-rider** [comment]
Please post a bit more info. 
- Do you mean combobox itself? Its value not used anywhere, it can be useful only during new driver creation.
- Why do you need to change driver class for SQL Server? Maybe you need to create another driver?

**Comment by vincenzocaselli** [comment]
> * Do you mean combobox itself? Its value not used anywhere, it can be useful only during new driver creation.
> * Why do you need to change driver class for SQL Server? Maybe you need to create another driver?

Well, I didn't realize that SQL Server type was already available: tried it now and it is working correctly indeed (also between IDE restart!).

Anyway in the past I created a custom connection type like this

![image](https://user-images.githubusercontent.com/3648713/55096007-68447700-50b9-11e9-8901-b1f4c5851943.png)

and as you see the combo is empty.

You say that its value is not used anywhere, but I have a different evidence. In fact if I click "Find class" button and set the class in the combo, then the connection is working.
When restarting the IDE however the combo is blank again and the connection is broken, until I repeat the procedure above and re-set the driver class

So in the end my problem is solved by using the pre-set SQL Server type, but it's still there as soon as I need to create a custom connection type.

Thank you very much
Vincenzo

**Comment by serge-rider** [comment]
Well, you shouldn't do this. Creating new driver is a very rare thing you need to do (once per database type if it wasn't already preconfigured in DBeaver). I believe that most of people never opened driver settings at all because this is not needed.

Just create new connections, not drivers.

**Comment by vincenzocaselli** [comment]
Ok, I understand.
But what is the correct procedure to create a new custom JDBC driver/database type (not preconfigured in DBeaver)?

**Comment by serge-rider** [comment]
https://github.com/dbeaver/dbeaver/wiki/Database-drivers
