### ISSUE TITLE
Delete cascade row

### ISSUE THREAD

**Issue by Marco-Sulla** [dbeaver/dbeaver#5587]
SqlWorkbench has the feature to delete a row with all the connected rows of other tables by fk. I would like to have the same feature on dbeaver.

**Comment by Marco-Sulla** [comment]
No one is insterested in such a feature?

**Comment by Marco-Sulla** [comment]
Hello?

PS: furthermore I don't know why this was tagged as question, it's a new feature request.

**Comment by Marco-Sulla** [comment]
Helllllloooooooo??????

**Comment by Marco-Sulla** [comment]
@serge-rider What do you think about this feature?

**Comment by serge-rider** [comment]
This looks like a handy feature. Sorry, missed it.
We need to make some UI for it. 
Options I see after 2 mins of thinking:
- Extra "save cascade" button
- Some config checkbox in status bar
- Extra delete command (delete with cascade)
- Confirmation dialog with "delete cascade" option (shown only when there are referencing tables).

Also, should this cascade be recursive (i.e. do the same for deletes from referencing tables)? This also would be handy but it will require additional select queries (which may be quite expensive in some cases).
And should we show user all delete queries in SQL preview script?

**Comment by Marco-Sulla** [comment]
Well, SqlWorkbench is recursive, and it shows the entire SQL before you commit the script, as Debeaver do.

I have some questions:

1. why you need an extra "save cascade" button? What you want to save?
2. what's the purpose of the config checkbox in status bar?
3. Dbeaver already shows a confirmarion dialog, with the SQL that you want to commit. So why the confirmation dialog?

On the contrary, I'll add a warning to the user that clicks on "delete cascade", that warns that DBeaver will not delete only that row, but all the row connected to it. And a checkbox with "Never tell me again".

**Comment by serge-rider** [comment]
I mean I don't want this feature be enabled by default. If is a quite dangerous operation, especially if it it performed implicitly.
And another issue - even searching for connected rows may take quite a lot of time in case of remote database with bad connection quality.

So we need to to use it only if user really needs it.
No, DBeaver doesn't show dialog with SQL unless you click on "Script" button (we show such dialog for metadata changes but not for data editor).

For now I think that we could show some dialog only if there are row deletes. Asking about cascade delete in the same dialog (with some checkbox). Yet another checkbox for recursive cascade delete also make sense.

**Comment by Marco-Sulla** [comment]
> I mean I don't want this feature be enabled by default. If is a quite dangerous operation, especially if it it performed implicitly.

Well, yes, it should be an action apart, IMHO. I mean, if you click CANC, you are doing a normal delete. You have to right click and select "delete cascade" to perform that action.

> No, DBeaver doesn't show dialog with SQL unless you click on "Script" button (we show such dialog for metadata changes but not for data editor).

Yes you're right! I confused other actions, like new column etcetera.

> For now I think that we could show some dialog only if there are row deletes. Asking about cascade delete in the same dialog (with some checkbox). Yet another checkbox for recursive cascade delete also make sense.

Well, adding a dialog also for the normal delete is your choice. I don't know if it's good or bad, but I usually delete the row and I'm not really interested in the SQL, while when I create a table or a column I'm interested.

IMHO the dialog should be displayed only for cascade and recursive cascade deleting. But I would not put any checkbox in the dialog, I'll simply inform the user _before_ the dialog shows up that the action could be dangerous, and an option to silence future warnings.

Do you want to add a "delete cascade" and "delete cascade recursive" action, or the "delete cascade" try to be recursive by default? I have to say I prefer the second option

**Comment by Marco-Sulla** [comment]
@serge-rider 😁

**Comment by serge-rider** [comment]
"Direct" delete cascade feature will be added in 6.1.2. "Deep" cascade (recursive) will be added in the next version (see #6220).

You can test it in Early Access version (https://dbeaver.io/files/ea)

**Comment by Marco-Sulla** [comment]
Thank you a lot :)

**Comment by uslss** [comment]
verified

**Comment by tsathis** [comment]
Is this feature available in latest releases? Could not find this on version 21.2. Could anyone please show me how to use this feature in newer versions?

**Comment by JuradoBruno** [comment]
@tharindusathis If you are using the "Development" Connexion Type, Confirm Data Changes will not be checked by default so the option "delete cascade" will not even be proposed to you. You can change the default behavior by going in your Connection settings, General, Connection Type and click on Edit Connection Type, then select Confirm Data Changes.
That did the trick for me.
My Dbeaver is in French and doesn't want to switch language so I can't provide you with screenshots. I'm sure you'll find it thought.

**Comment by tsathis** [comment]
> @tharindusathis If you are using the "Development" ...

Thanks @JuradoBruno Now I can see the "Delete Cascade" option in "Preview Changes". However, it will not update query in preview changes' dialog.

![image](https://user-images.githubusercontent.com/34299693/176817777-9a6cbe2f-df0f-440b-8eb7-c5aaebd9c276.png)

**Comment by JuradoBruno** [comment]
Yes, same, it doesn't work for me either.

**Comment by felipeggrod** [comment]
Same here

**Comment by jakiw** [comment]
I have the same problem. The `Deep cascade` Button is greyed out. The `Delete cascade` button does not update the SQL, and if the deletion is executed using `Save` in the dialog, I still get the same foreign key errors that I get if I do not use the `Delete cascade` option.
I am using Manjaro Linux, and version 22.1.3 of DBeaver.

**Comment by andregamma** [comment]
Hey @uslss, the problem stated by the others persists. Selecting `Delete cascade` doesn't update the SQL. I'm using Postgres.

**Comment by mijhaels** [comment]
@uslss The problem stated persists for me too. I'm using postgres in Debian sid.   DBeaver	23.2.1.202309250303	org.jkiss.dbeaver.core.product	null

**Comment by yachaka** [comment]
same problem, option checkbox doesn't update script to cascade delete

**Comment by jiaulislam** [comment]
is this feature working ? My version is `Version 25.0.0.202503021833` still it's doesn't work. SQL not updating.

**Comment by Marco-Sulla** [comment]
> @tharindusathis If you are using the "Development" Connexion Type, Confirm Data Changes will not be checked by default so the option "delete cascade" will not even be proposed to you. You can change the default behavior by going in your Connection settings, General, Connection Type and click on Edit Connection Type, then select Confirm Data Changes.
> That did the trick for me.

I confirm it works and I confirm the `Deep` check is disabled, but it's normal (check https://github.com/dbeaver/dbeaver/issues/5587#issuecomment-508432846)
There's a simpler trick: you can select the arrow down near the `Save` button and select `Show confirmation before save`.

Anyway, maybe the `Edit` -> `Delete current row` entry in the right-click menu could be transformed in a submenu, with `Normal`, `Cascade` and `Deep cascade` options. Maybe more difficult, because you should also populate the appropriate checks if you show the confirmation dialog.

@serge-rider What do you think about it? Can I open a new issue?

**Comment by arhayka** [comment]
Hi @Marco-Sulla, yes, please open a new issue. It looks like an interesting idea, and it would be great to have it described there.

**Comment by Marco-Sulla** [comment]
Done: https://github.com/dbeaver/dbeaver/issues/39182
