### ISSUE TITLE
Dashboards aren't working [Ubuntu 18.04]

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#5588]
#### System information: 
- Operating system (distribution) and version ubuntu 18.04
- DBeaver version 6.0.1 CE
#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
Dashboard opens but doesn't work as expected. Entries in log appear after the closing of the tab
Logs attached
[dashboards.log](https://github.com/dbeaver/dbeaver/files/3010893/dashboards.log)

**Comment by serge-rider** [comment]
Can't reproduce

**Comment by uslss** [comment]
verified
