### ISSUE TITLE
A lot of disconnect/connect requests issued by DBeaver

### ISSUE THREAD

**Issue by Sargul** [dbeaver/dbeaver#5590]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
6.0.0
- Java version 
included jre
- Additional extensions
Office, SVG

#### Connection specification:
- Database name and version
Exasol 6.0.14
DB2 V11
- Driver name
com.exasol.jdbc.exa and
com.ibm.db2.jcc.DB2Driver

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no
#### Describe the problem you're observing:
Basically after each statement the database connection is disconnected and reestablished when executing another statment

#### Steps to reproduce, if exist:
open editor window
execute dummy statement
wait a couple of seconds
execute another statment

The database connection is disconnected an reestablished
![image](https://user-images.githubusercontent.com/5595511/55057806-8c2c9c00-506a-11e9-905e-4f9778886128.png)

#### Include any warning/errors/backtraces from the logs
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3012011/dbeaver-debug.log)
[dbeaver_sql_20190327.log](https://github.com/dbeaver/dbeaver/files/3012013/dbeaver_sql_20190327.log)

**Comment by Sargul** [comment]
Forgot to include a screenshot for DB2:
![image](https://user-images.githubusercontent.com/5595511/55061672-98b5f200-5074-11e9-972b-afc5aaf86f75.png)
Same for Oracle:
![image](https://user-images.githubusercontent.com/5595511/55061926-33163580-5075-11e9-9521-b9a5075615c1.png)

**Comment by serge-rider** [comment]
I can't reproduce this and I don't see this in the log (there is just one succesfull connection to Exasol logged).
Maybe you reopening SQL editor after each query? IF you have option "Open separate connection for each editor" on then this is expected behavior.

**Comment by Sargul** [comment]
I'm just executing the same statement over and over again in the same editor window.

I'm not using seperate connection for every tab either (was suspecting that).

![show](https://user-images.githubusercontent.com/5595511/55089814-514c5780-50ae-11e9-9aff-99ad131a32e8.gif)

**Comment by serge-rider** [comment]
Ok. This looks very odd.
Anyhow then there should be something in the debug/error log.
Could you post another one? With Oracle connects/disconnects/

**Comment by Sargul** [comment]
[Logs.zip](https://github.com/dbeaver/dbeaver/files/3016440/Logs.zip)

**Comment by serge-rider** [comment]
Ok, thanks.
I see a lot of Exasol connection failures. Most of them happens during table properties reading, during extra editors opening or during SQL auto-completion metadata reading.
Can this be related to a driver version?

Unfortunately I still can't reproduce this as I don't have Exasol testing server..

**Comment by Sargul** [comment]
I'm so sorry -> I'm a complete dumbass.

We distribute the org.jkiss.dbeaver.core.prefs from a central server to all clients and at some point someone added statement.invalidate.before.execute=true which causes disconnects on every execution.

I seriously didn't know such an option exists.
