### ISSUE TITLE
CTRL+F7 opens dialog which instantly closed

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#5591]
#### System information: 
- Operating system (distribution) and version: Linux Mint 19.1
- DBeaver version 6.0.0
- Java version 
- Additional extensions

#### Describe the problem you're observing:
![__](https://user-images.githubusercontent.com/799021/55065578-bee38e00-5084-11e9-976f-5e6e79e6c29f.jpg)

#### Steps to reproduce, if exist:
press CTRL+F7
Actual: window is closed after 1sec
Expected: allow to choose item

**Comment by serge-rider** [comment]
This is expected behavior. You supposed to press CTRL+F7  and then keep CTRL pressed and iterate thru view list by additional F7 press.
A bit controversial behavior but this is how it was designed in Eclipse.

**Comment by KES777** [comment]
Ok. I have never meet this behavior yet. (probably show hint: press F7 again to select next item)

Also I notice, that
I can iterate over list by pressing arrows. 

1. press CTRL+F7
2. release F7
3. press arrow down
4. release CTRL
5. now use arrows to navigate over menu

But first arrow press jumps over one menu item
