### ISSUE TITLE
afte rupdate to V6.0.1 unable edit filter on database objects

### ISSUE THREAD

**Issue by tatod** [dbeaver/dbeaver#5592]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
Please provide more info about your environment (OS, etc).
Perhaps it is duplicate of #5575

**Comment by tatod** [comment]
Linux Ubuntu 18.04 LTS
Dbeaver 6.0.1
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
Database Oracle JDBC

**Comment by serge-rider** [comment]
Duplicate of #5575 .
Thanks for the bug report anyway.

Could you try recent Early Access version (https://dbeaver.io/files/ea/) - it fix of this issue (but it is not well tested yet).

**Comment by tatod** [comment]
I thought it could be duplicate to #5575 and I have tried with Shift+enter but it did not allow me to modify the filter so I have decided to log it

**Comment by tatod** [comment]
I can see in V6.0.2 this issue is resolved

**Comment by serge-rider** [comment]
Thanks for testing this
