### ISSUE TITLE
Unable to cancel a execution plan

### ISSUE THREAD

**Issue by gumblex** [dbeaver/dbeaver#5595]
#### System information: 
- Debian testing (10), Linux 4.19.0-4-amd64
- DBeaver version 6.0.0
- Java version 11.0.3

#### Connection specification:
- PostgreSQL 11
- PostgreSQL Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Write a slow, or never ending query in the Script dialog, eg.

```
with recursive a as (select 1 n union all select n+1 n from a)
select * from a
```
Right click the selected query, select "analyze execution plan" (Shift+Ctrl+E).
The "stop" button (the upper ■ in the picture) in the "execution plan" *doesn't work*, but the "stop" button (the lower ■ in the picture) in the "background task" window does work.

![image](https://user-images.githubusercontent.com/6681934/55093440-567dc680-50ef-11e9-80be-f2b7273eee69.png)

#### Steps to reproduce, if exist:

as above.

**Comment by kseniiaguzeeva** [comment]
I can reproduce it in 7.0.1

**Comment by serge-rider** [comment]
Fixed.
1. Now you can cancel explain query
1. Explain is now configurable (you can unset ANALYSE parameter and thus query won't hang)

**Comment by uslss** [comment]
verified
