### ISSUE TITLE
Delete rows

### ISSUE THREAD

**Issue by saranpostgres** [dbeaver/dbeaver#5597]
i did not triggered any delete statement explicity from dbeaver when connected postgres dba i triggered only select statements but when i see few of rows deleted from table and it is showing records are deleted with my userid. is it anyway to delete records through dbeaver without passing delete statement

**Comment by serge-rider** [comment]
Please provide more information.

You can delete data not only in SQL editor (by running DELETE FROM queries) but also in data editor by deleting rows from UI and then saving changes to a database.

**Comment by saranpostgres** [comment]
Actually explictly i did not passed delete statement from aql editor.is any
possible ways by accidentally deleting data by unknown short cuts in dbeaver
