### ISSUE TITLE
 the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by ichabondcrane** [dbeaver/dbeaver#5601]
#### System information: 
- Operating system (distribution) and version = macOS High Sierra v10.13.6
- DBeaver version = 5.0.2
- Java version =1.8.9
- Additional extensions

#### Connection specification:
- Database name and version=  DB2 v10.5.0.9
- Driver name =  DB2 / DB2 LUW
- Do you use tunnels or proxies (SSH, SOCKS, etc)? = SSL

#### Describe the problem you're observing:
I have tried several times to install and make DBEAVER work in this mac machine and I always encounter this trustAnchors parameters must not be non-empty.
I have tried the latest version of dbeaver and I settled on 5.0.2 as this is the version working for my colleague. I'm trying to connect to a db2 db with SSL enabled. I have included the following 
parameters (sslTrustStoreLocation, sslConnection, sslTrustStorepassword),  in the Connection Properties, but I still got this the trustAchors parameter must non-empty error message.
Thanks in advance for your help.

 
[jcc][t4][2030][11211][4.16.53] A communication error occurred during operations on the connection's underlying socket, socket input stream, 
or socket output stream.  Error location: Reply.fill() - socketInputStream.read (-1).  Message: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty. ERRORCODE=-4499, SQLSTATE=08001
  Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
  Unexpected error:java.security.InvalidAlgorithmParameterException:Z
    the trustAnchors parameter must be non-empty
    the trustAnchors parameter must be non-empty

**Comment by aardbol** [comment]
For me it only happens with Java 11, not with Java 8

**Comment by avibrazil** [comment]
I have this problem too.
But trying to connect to MariaDB 10 with SSL enabled.

It seems to be generally related to SSL, as others report this for PostgreSQL too.

**Comment by Skywalker-11** [comment]
Same issue on Debian 10 with Java11 when trying to connect via SSL
Might be the same problem as https://github.com/dbeaver/dbeaver/issues/4528

My setup does require a ssl connection to the server for the user to be able to login. Authentication is done using username and password

**Comment by jenswegar** [comment]
I had the same error, and disabling certificate validation fixed the problem (though not ideal. Will look into setting the correct certificates as mentioned in #4528). Other possible workarounds here also: https://github.com/dbeaver/dbeaver/issues/7620#issuecomment-644328633

**Comment by simenbm** [comment]
I'm getting this error message with the newest windows community (`DBeaver 7.2.3`) DBeaver client, connecting to MariaDB server.

It happens if I use a CA certificate, require SSL, and `Verify server certificate`, however if I uncheck `Verify server certificate` it is working fine. CA certificate can be found in the steps [here](https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl).

Error is as below:

    Could not connect to my-database.mariadb.database.azure.com:3306 : Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
      Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
      Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        the trustAnchors parameter must be non-empty
        the trustAnchors parameter must be non-empty

**Comment by jhaiduce** [comment]
I'm getting this error message on Fedora 32 using both the flatpak and the rpm packages. Java version is OpenJDK 1.8.0_265 (though the flatpak package might bring its own JRE).

**Comment by jhaiduce** [comment]
In my case the problem was solved by disabling server certificate verification. So apparently the problem is that dBeaver couldn't verify the server cert. But if that is the root cause, a more informative error message would make this much easier to troubleshoot. Something along the lines of "Server certificate verification failed" with an option to trust the certificate for future connections.

**Comment by simenbm** [comment]
It's working fine for me in DBeaver on Fedora 32 however, version `7.1.0`. Not from a flatpak but just from the standalone executables etc that comes in zip release.

**Comment by simenbm** [comment]
Can someone please comment on how this was solved? This is still an issue with the snap community-ce version 21.0.3 on Ubuntu 20.04

**Comment by enghitalo** [comment]
For me, is solved setting "useSSL" to FALSE

**Comment by markuman** [comment]
> For me, is solved setting "useSSL" to FALSE

disable ssl it not a solution. don't do it!

**Comment by markuman** [comment]
[There are three solutions](https://github.com/dbeaver/dbeaver/issues/7620#issuecomment-644328633)

1. Disable server certificate validation checkbox (many DB tools do this implicitly to avoid such problems)
2. Provide all certs (CA, user SSL certificate and its private key -  imo not possible when using aws rds, they provide just one cert bundle )
3. Use MySQL driver

**Comment by pcgeek86** [comment]
I had to uncheck the `Verify Server Certificate` box. Very unintuitive.

**Comment by jluismoran** [comment]
Solution posted by @jenswegar worked for me in DBeaver 22.1.4. I had to disable the checkbox "Verify server certificate" in Connection settings -> SSL -> Advanced.

**Comment by sebastianpennino** [comment]
macOS 12.6 (Monterrey) /  using DBeaver Version 22.2.5.202211202223

Same solution as @jenswegar, @simenbm and  others.
I had to uncheck the `Verify Server Certificate` box in the SSL tab.

**Comment by Skywalker-11** [comment]
You just have to be aware that this might make you vulnerable to MitM attacks as the traffic to the server might not be transferred over a secure connection (especially if you try to connect to a cloud server).

**Comment by BB-BenBridges** [comment]
This should not be closed! Unchecking the `Verify Server Certificate` box in the SSL tab is a workaround not a fix. As @Skywalker-11  said, this can leave you open to MitM attacks.

**Comment by JoeMurray** [comment]
> I had to uncheck the `Verify Server Certificate` box. Very unintuitive.

On DBeaver Edit Connection popup, select SSL tab, enable Use SSL, in Advanced section, Enable Require SSL, disable Verify server certificate, enable Allow public key retrieval. Click Test Connection. Worked for me, YMMV.

**Comment by carycodes** [comment]
For AWS RDS (Aurora MySQL), I was able to download a certificate from AWS (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html).  Note that you _must_ choose the CA for the region where your DB is located.  The global one will not work.

With the pem file in hand, go to your DBeaver connection settings > SSL > Certificate Authority, then choose that file.

Now you should be able to successfully connect with "Required SSL" and "Verify server certificate" both checked.

It's annoying that the correct CA can't be found out of the global file, but I'm not sure if that's an Amazon problem or a DBeaver problem.

At least for MySQL, find the right key file and you will succeed.  As several other people have said before me, don't just disable "Verify server certificate" for production servers.  That's not safe.

**Comment by jhaiduce** [comment]
I previously was able to fix this by setting the CA certificate parameter to the CA file corresponding to my cert. But now it no longer works and I get this error again, even though the mariadb command line tools recognize the cert as valid.
