### ISSUE TITLE
Double Inline Editing not working after Update to 6.0.1 on KUbuntu 18.04

### ISSUE THREAD

**Issue by jan2k12** [dbeaver/dbeaver#5602]
#### System information: 
- KUbuntu 18.04 (KDE Plasma 5.12.7)
- 6.0.1
- Java version - OpenJDK 10.0.2
- Additional extensions -

#### Connection specification:
- Database name and version: Mysql:5.7
- Driver name: Mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Open a Table in the Table View
Double Click or Click on a Value to change it will appear one milisecond as changeable and recover to normal view immediately

When right-clicking on the value and choosing edit -> inline edit it works fine.
#### Steps to reproduce, if exist:

see above

**Comment by MauroMichelotti** [comment]
Same problem with
Ubuntu 18.04
java.runtime.version=1.8.0_201-b09
Database: Postgres

tnx

**Comment by weswaldix** [comment]
Maybe related to: https://github.com/dbeaver/dbeaver/issues/5575
Fix: Update to V6.0.2:
https://github.com/dbeaver/dbeaver/issues/5575#issuecomment-477095445

**Comment by jesusferm** [comment]
same problem with
fedora 29
database: mariadb

**Comment by felipebraga** [comment]
Same
Manjaro 18.0.4
KDE

**Comment by lflucasferreira** [comment]
I am facing the same problem. Please, solve that soon. Thank you in advance.

**Comment by weswaldix** [comment]
Please try the Version 6.0.2 - this version is not released yet but available as early access:
https://dbeaver.io/files/ea/
The edit field issue is fixed in this version.

**Comment by felangga** [comment]
Yes it's fixed on 6.0.2
Tested on my KDE machine

**Comment by uslss** [comment]
verified
