### ISSUE TITLE
Script name before connection name in tabs

### ISSUE THREAD

**Issue by shungabubus** [dbeaver/dbeaver#5604]
Hello,

I found this nice instructions for an amazing function in older version but I am unable to locate the same in 6.0.0.
https://dbeaver.io/forum/viewtopic.php?f=2&t=1649
I just hope it was not obsoleted.

Many thanks:
Tamas

**Comment by tati-kru** [comment]
It looks like the preferences has become a bit more complicated since 3.1.5. But you can find the same options there.
<img width="848" alt="Screenshot 2019-03-28 at 15 41 57" src="https://user-images.githubusercontent.com/30336552/55158657-773a3080-5170-11e9-90e1-bc735019516f.png">

**Comment by shungabubus** [comment]
Thank you very much. Is it normal that the tab names don't update upon changes here?

**Comment by tati-kru** [comment]
The names of opened tabs will not be changed automatically after the new preferences setup. You need to reopen script tab for changes applying.

**Comment by shungabubus** [comment]
Many thanks.
