### ISSUE TITLE
Foreign Key Value Selected Color result panel

### ISSUE THREAD

**Issue by TyrannoRex** [dbeaver/dbeaver#5605]
#### System information: 
- Operating system (distribution) and version: Windows 10 & Ubuntu 18.04
- DBeaver version: 6.0.1.201903251040 (as Eclipse IDE Version: 2.2.400.v20181206-0815 Plugin)

#### Connection specification:
- Database name and version: MariaDB (10.3.9-MariaDB)
- Driver name: org.mariadb.jdbc.Driver

#### Describe the problem you're observing:
Hello,

It is not really an issue, it is only a question that I don't know if there is a way to do it.

Is there a posibility to change the color in the 'Result Panel' when I select a value from the Data table if it is a Foreign Key? As I use the dark theme, it is very similar with the theme color. Is there a way to change this color?

![1234](https://user-images.githubusercontent.com/9528928/55158670-b9a74180-515f-11e9-824f-c7a1d2cdc516.jpg)

**Comment by kseniiaguzeeva** [comment]
Looks pretty good in 7.0.4. 
![dbeaver_6naAUXuwEb](https://user-images.githubusercontent.com/51405061/81310456-c3061b80-908c-11ea-8e4f-5b5c868aeaa6.png)

Please reopen the ticket if it is still actual for you.
