### ISSUE TITLE
DBeaver 6.0.1 doesn't load Oracle database schema list

### ISSUE THREAD

**Issue by esscheffer** [dbeaver/dbeaver#5607]
#### System information: 
- Windows 10
- DBeaver 6.0.1

#### Connection specification:
- Oracle database

#### Describe the problem you're observing:
After upgrading DBeaver to the new 6.0.1 version, I started having problems with a connection with a oracle database. Trying to open the Schemas list keep loading forever. I needed to downgrade DBeaver to a older version to make is working again.

**Comment by serge-rider** [comment]
I can't reproduce this. Perhaps it is the same as #5590.
Please post error/debug logs if possible ( https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by serge-rider** [comment]
Also please try 6.0.2 Early Access (https://dbeaver.io/files/ea/)

**Comment by geomorillo** [comment]
didnt work with 6.0.2

**Comment by ndphuong** [comment]
It happen both on Mac and Windows
I have try latest version 6.0.0 but unlucky
The surprise is it not happen with every Oracle DB. Some db still work well, but some get error at connect step:
`ORA-00604: error occurred at recursive SQL level 1
ORA-21000: error number argument to raise_application_error of 1001 is out of range
ORA-06512: at line 28`

**Comment by ndphuong** [comment]
Note that, previous day, every thing work well
I don't change or update anything

**Comment by uslss** [comment]
Is the issue actual for yor in 6.2.3 version?

**Comment by uslss** [comment]
there is no update for a long time.
ticket closed

**Comment by dmaresma** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/136118865/28f3531f-6684-4e11-8bfb-aa319cfd64bb)
