### ISSUE TITLE
How to load all databases from one postgres server?

### ISSUE THREAD

**Issue by edward2990** [dbeaver/dbeaver#5608]
How can i load all databases from a postgresql server, right now i need to add manually one by one the database connection.

Thanks. 

PS: I love this tool BTW

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/55172217-c2613d00-518a-11e9-9cc6-2c0f5d45bf59.png)

I guess we should rename this option to "Show all databases" to make it more clear )

**Comment by edward2990** [comment]
> ![image](https://user-images.githubusercontent.com/6398845/55172217-c2613d00-518a-11e9-9cc6-2c0f5d45bf59.png)
> 
> I guess we should rename this option to "Show all databases" to make it more clear )

thanks a lot for your quick response, it's true i think this should be labeled different
