### ISSUE TITLE
[Feature request] continue i386  deb & rpm support

### ISSUE THREAD

**Issue by mkgrgis** [dbeaver/dbeaver#5609]
#### System information: 
- Operating system (distribution) and version
i386 , https://ru.wikipedia.org/wiki/Puppy_Linux
- DBeaver version
6.0.1
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
Oracle, Postgres, Firebird, SQlite etc.
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
Non

#### Describe the problem you're observing:

Is it hard to support deb & rpm for old computers?

**Comment by uslss** [comment]
x86 rpm is supported for now
