### ISSUE TITLE
[PostgreSQL] Table trigger comment is missing schema

### ISSUE THREAD

**Issue by cpburnz** [dbeaver/dbeaver#5611]
#### System information: 
- Operating system: Ubuntu 18.04 64bit
- DBeaver version: 6.0.1.201903251040
- Java version: OpenJDK version "10.0.2" 2018-07-17
- Additional extensions: N/A

#### Connection specification:
- Database name and version: PostgreSQL 9.1 and 9.4
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No.

#### Describe the problem you're observing:

The  DDL for a table trigger's comment is missing the schema.

#### Steps to reproduce, if exist:

Create the schema, table, and trigger:

```sql
CREATE SCHEMA test_schema;

CREATE TABLE test_schema.test_table (
	id integer NOT NULL
);


CREATE FUNCTION test_function() RETURNS trigger LANGUAGE plpgsql AS
$$
	BEGIN
	END;
$$;

CREATE TRIGGER test_trigger BEFORE INSERT ON test_schema.test_table FOR ROW EXECUTE PROCEDURE test_function();

COMMENT ON TRIGGER test_trigger ON test_schema.test_table IS 'The trigger comment.';
```

The following is shown in the table's DDL:

```sql
-- Drop table

-- DROP TABLE test_schema.test_table;

CREATE TABLE test_schema.test_table (
	id int4 NOT NULL
);

-- Table Triggers

-- DROP TRIGGER test_trigger ON test_table;

CREATE TRIGGER test_trigger BEFORE INSERT ON
test_schema.test_table FOR EACH ROW EXECUTE PROCEDURE test_function();

COMMENT ON TRIGGER test_trigger ON test_table IS 'The trigger comment.';;

-- Permissions

ALTER TABLE test_schema.test_table OWNER TO postgres;
GRANT ALL ON TABLE test_schema.test_table TO postgres;
```

The trigger's comment,

```sql
COMMENT ON TRIGGER test_trigger ON test_table IS 'The trigger comment.';;
```

is missing the schema *test_schema* (it also oddly ends with two semicolons). It should be:

```sql
COMMENT ON TRIGGER test_trigger ON test_schema.test_table IS 'The trigger comment.';
```

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
