### ISSUE TITLE
[PostgreSQL] Table trigger commented out drop statement is missing schema

### ISSUE THREAD

**Issue by cpburnz** [dbeaver/dbeaver#5612]
#### System information: 
- Operating system: Ubuntu 18.04 64bit
- DBeaver version: 6.0.1.201903251040
- Java version: OpenJDK version "10.0.2" 2018-07-17
- Additional extensions: N/A

#### Connection specification:
- Database name and version: PostgreSQL 9.1 and 9.4
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No.

#### Describe the problem you're observing:

The commented out drop statement for the table trigger does not have the schema in the table's DDL.

#### Steps to reproduce, if exist:

Create the schema, table, and trigger:

```sql
CREATE SCHEMA test_schema;

CREATE TABLE test_schema.test_table (
	id integer NOT NULL
);


CREATE FUNCTION test_function() RETURNS trigger LANGUAGE plpgsql AS
$$
	BEGIN
	END;
$$;

CREATE TRIGGER test_trigger BEFORE INSERT ON test_schema.test_table FOR ROW EXECUTE PROCEDURE test_function();
```

The following is shown in the table's DLL:

```sql
-- Drop table

-- DROP TABLE test_schema.test_table;

CREATE TABLE test_schema.test_table (
	id int4 NOT NULL
);

-- Table Triggers

-- DROP TRIGGER test_trigger ON test_table;

CREATE TRIGGER test_trigger BEFORE INSERT ON
test_schema.test_table FOR EACH ROW EXECUTE PROCEDURE test_function();;

-- Permissions

ALTER TABLE test_schema.test_table OWNER TO postgres;
GRANT ALL ON TABLE test_schema.test_table TO postgres;
```

The commented out drop statement for the trigger,

```sql
-- DROP TRIGGER test_trigger ON test_table;
```

is missing the schema. It should be:

```sql
-- DROP TRIGGER test_trigger ON test_schema.test_table;
```

**Comment by uslss** [comment]
#5611

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
