### ISSUE TITLE
Autocompletion selection - space or dot

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#5622]
Is there any way to add option to choose auto-completion item by other keys such as space or "." 
Currently only option to select item from list is to use ENTER key.
Im still doing mistakes by pressing space or dot and loosing auto completion prompt

Example: 

Imagine you need to write query: 
**Select * from example_schema.complex_table_name**

Im typing examp <pressing_dot> and expecting to see all tables names in schema

**Comment by maciey** [comment]
Any option to add that feature ?
My heart is bleeding :(

**Comment by maciey** [comment]
bump ...

**Comment by serge-rider** [comment]
In simple cases DBeaver shows content assistant by itself, there is no need to press any special button. But this feature must be enabled in prefs:
![image](https://user-images.githubusercontent.com/6398845/60603060-4db72380-9db5-11e9-9e78-4a13ffeea66d.png)

Also you can redefine keyboard shortcut ctrl+space by default() for Content Assista in preferences:
![image](https://user-images.githubusercontent.com/6398845/60602950-1779a400-9db5-11e9-871d-31a9501dee6c.png)

**Comment by maciey** [comment]
Thanks for your reply but I do not have issue with showing autocompletion.
My issue is only selection from dropdown

EW lets say I have field called 'name' in table called 'table_1'

im starting typing:
 tabl

Then I can see 'table_1' as 1st position on dropdown list.
To select it I have to press enter., while Id like to press '.' - then it should complete table_1 and show then 'name' as 1st option on dropdown then when I press space it should complete 'name' word

Thanks to that I dont need to press ENTER twice

In this way work many of popular IDEs (eg Visual Studio)

**Comment by maciey** [comment]
Any chance to have this implemented ?

**Comment by serge-rider** [comment]
This behavior is hardcoded in Eclipse editor framework.  Unfortunately it is quite hard to fix this.
However there is a bug in Eclipse bugracker about this (https://bugs.eclipse.org/bugs/show_bug.cgi?id=367009). 
I hope that in one of next version they will make this shortcut configurable.

**Comment by maciey** [comment]
Too pity
But I understand difficulties
