### ISSUE TITLE
Close button isn't shown for Edit connection pop-up

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#5624]
#### System information: 
- Ubuntu 18.04
- DBeaver version 6.0.2

#### Describe the problem you're observing:
Close button (at the top right corner of the window) isn't shown for Edit connection pop-up
#### Steps to reproduce, if exist:
1. Create connection
2. Choose Edit connection (F4) 
![Screenshot 2019-03-31 23:42:42](https://user-images.githubusercontent.com/31996417/55294838-57746800-540f-11e9-93ac-8a2822af501a.png)

**Comment by Chealer** [comment]
As shown in issue #7272, there is now (6.2.5) a Close **button** at the bottom.
