### ISSUE TITLE
Still (#4791) crashes after installing Office plugin

### ISSUE THREAD

**Issue by dariopnc** [dbeaver/dbeaver#5625]
#### System information: 
- Windows 10
- 6.0.1
- Office plugin

#### Describe the problem you're observing:
My issue is identical to what's described in #4791

This happens with every upgrade of DBeaver version I did since 5.3 (I suppose), and happend even when going from 6.0.0 to 6.0.1.

I chose to open a new issue, since it might be a new problem

#### Steps to reproduce, if exist:
My setup is always the same:
 - Install for all users
 - Office plugin installed

When a new upgrade comes out I launch the installer, select the option to install for all users, the installer is restarted and succesfully finishes.
Then I launch DBeaver and it proposes me to re-install the Office plugin, which I accept, and after the installation process ends successfully, and asks for restart, the splash loop begins.
After a while, I think about dozens of automatic-launch retries, it finally gets it right and starts successfully, without any intervention

**Comment by serge-rider** [comment]
I've reproduced that (in my case it stops blinking once you switch to any other window). But I have no clue how to fix this so far..

**Comment by serge-rider** [comment]
Looks like we can't resolve this from DBeaver side.

Workaround: install DBeaver for current user only (or in some other folder than Program Files) to avoid this weird behavior when installing additional extensions.

**Comment by dariopnc** [comment]
> 
> 
> Looks like we can't resolve this from DBeaver side.
> 
> Workaround: install DBeaver for current user only (or in some other folder than Program Files) to avoid this weird behavior when installing additional extensions.

Can you please describe what's happening? @serge-rider
