### ISSUE TITLE
PostgreSQL 9.6.12 Error execute plan

### ISSUE THREAD

**Issue by Zemond** [dbeaver/dbeaver#5626]
#### System information: 
- Operating system (distribution) and version: Windows 10 1803
- DBeaver version: 6.0.1.201903251040
- Java version : 8 (jre-8u201-windows-x64)
- Additional extensions

#### Connection specification:
- Database name and version: postgresql 9.6.12
- Driver name 
org.postgresql:postgresql:RELEASE 42.2.5
net.postgis:postgis-jdbc:RELEASE 2.2.1

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No
#### Describe the problem you're observing:

I want to see the query execution plan. But the error constantly flies.
The query seems to be clipped, so the execution plan does not work. Maybe somehow you can increase the number of characters to fulfill the request?

#### Steps to reproduce, if exist:

Connect to the database, see the session. Try to see the execution plan for the request.

#### Include any warning/errors/backtraces from the logs
<!-- Please, find the short guide how to find logs here: https://github.com/dbeaver/dbeaver/wiki/Log-files-

**Comment by Zemond** [comment]
My log file:
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3028382/dbeaver-debug.log)

**Comment by uslss** [comment]
verified
