### ISSUE TITLE
Yellowbrick: explain execution plan ERROR: ERROR: cache lookup failed for type 142

### ISSUE THREAD

**Issue by rcanuel** [dbeaver/dbeaver#5628]
#### System information: 
- Operating system (distribution) and version: Mac
$ uname -a
Darwin Offices-MacBook-Pro-3.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

- DBeaver version: 6.0.1.201903251041
- Java version 
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

- Additional extensions
Yellowbrick target

#### Connection specification:
- Database name and version:  Yellowbrick 2.1.2-12000
- Driver name: org.postgresql:postgresql:RELEASE. 42.2.0.jre7
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No.

#### Describe the problem you're observing:
EXPLAIN plan causes ERROR.

#### Steps to reproduce, if exist:
Highlight a query.
  - Right click: 
      - "EXecute" --> "Explain Execution Plan"

#### Include any warning/errors/backtraces from the logs

It seems to generate: "EXPLAIN (FORMAT XML, ANALYSE) select count(*) from public.foo"

Recommendation: Generate:EXPLAIN (ANALYSE) select count(*) from public.foo

https://yellowbrick.com/docs/ybd_sqlref/explain.html?hl=explain

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/49154898/55327646-8400a200-5458-11e9-8c90-ba099325c2f3.png">

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on issue. if it is still actual - feel free to reopen the ticket
