### ISSUE TITLE
Suggestion. Oracle. Be aware of the schema in declaration.

### ISSUE THREAD

**Issue by GAZ082** [dbeaver/dbeaver#5629]
Hey. I have to be adding the schema to a view/table so DBeaver can find it:

Such as:

`APPS.SOMEVIEW`

Even though I'm in the `APPS `schema if I put `SOMEVIEW `only it wont find it.

Thanks! Love the program!

**Comment by kseniiaguzeeva** [comment]
Hi @GAZ082,
How exactly do you use a search to find SOMEVIEW?

**Comment by GAZ082** [comment]
> Hi @GAZ082,
> How exactly do you use a search to find SOMEVIEW?

Like this. The autocomplete starts after a few ms. Also it's not necesary not to put the schema (apps in this case) so I close this issue.

![sample](https://user-images.githubusercontent.com/100194/72989403-f4542780-3dcc-11ea-9d2a-15923b10999b.gif)
