### ISSUE TITLE
Dbclicking a cell in data view not allows me to edit the cell data, needs to open the contextual menu todo it

### ISSUE THREAD

**Issue by edward2990** [dbeaver/dbeaver#5630]
dbclicking inside a cell in this view not allows me to edit the cell. This is after update to v6.0.1 i was able to do it in v6.0.0

![image](https://user-images.githubusercontent.com/18198323/55347327-8bd53c00-5482-11e9-9c55-f80535f14eec.png)

thanks

**Comment by tati-kru** [comment]
It looks like a duplicate of https://github.com/dbeaver/dbeaver/issues/5575. Please, check EA version with fix.

**Comment by edward2990** [comment]
> It looks like a duplicate of #5575. Please, check EA version with fix.

thanks for the quick replay.. nice work
