### ISSUE TITLE
View columns not visible with 'NO SCHEMA BINDING' views on Redshift connection

### ISSUE THREAD

**Issue by varshasandeep** [dbeaver/dbeaver#5631]
Hi, 

  List of columns are not visible with 'NO SCHEMA BINDING' option on views for Redshift connection in dbeaver. we are using latest JDBC redshift drivers and latest dbeaver version.

We recently opened case with AWS regarding this and seems like it is DBeaver issue and not Redshift.

View columns are visible with other SQL Client tools.
 
Can you please fix this bug in dbeaver?

**Comment by serge-rider** [comment]
Redshift-specific column read was added

**Comment by uslss** [comment]
verified

**Comment by deepaksenthilkumar** [comment]
viewDefinition.contains("with no schema binding"); works only for lower case of the code. If the code is WITH NO SCHEMA BINDING, it doesn't work. You might want to change the code to viewDefinition.toLowerCase().contains("with no schema binding");
