### ISSUE TITLE
Very slow first queries on Oracle

### ISSUE THREAD

**Issue by eyallior-surecomp** [dbeaver/dbeaver#5633]
DBeaver is great, but it's slow on first query for each table (at least 20 seconds, sometimes over 80 seconds… "Detect unique identifiers - 81s")
 
Checking th option ["Use RULE hint for system catalog queries"] didn't change much.
 
Unchecking these two did help, but with the cost of not allowing me to edit and save values:
Result Sets > [  ] Read table metadata (unique keys)
Result Sets > [  ] Read table references (foreign keys)

JDBC/Oracle, DBeaver version 5.1.4 (just upgraded to 6.0.1, same results, over 20 seconds for the first query)

Windows 10
Java 1.8.0_144
Driver: oraclient11g (ojdbc6.jar orai18n.jar xdb6.jar)

**Comment by jgarciabu** [comment]
I am also having very slow first queries with Oracle. Oftentimes in the hundreds of seconds for "Discovering Owner Identity" while query is processing. Any query after that is fine.

Windows 10
Oraclient11g
Version 6.0.1

Have not altered any default settings.

**Comment by AndrewKhitrin** [comment]
@eyallior-surecomp  @jgarciabu 

Can you give us full Oracle version number (e.g. 11.2.0.1) propably it help to find problem.

Thanks,
Andrew

**Comment by AndrewKhitrin** [comment]
@serge-rider 

There are many wonders in Oracle world with Data Dctionary queries.

In addition to using evil "RULE" hint (it have completely unpredictable behavor) Oracle recommended (Note 2266016.1) three undocumented session level options for "metadata query" :

ALTER SESSION SET "_optimizer_push_pred_cost_based" = FALSE;
ALTER SESSION SET "_optimizer_squ_bottomup" = FALSE;
ALTER SESSION SET "_optimizer_cost_based_transformation" = 'OFF';

I guess we must try this.

Hope this help,
Andrew

**Comment by eyallior-surecomp** [comment]
> Can you give us full Oracle version number (e.g. 11.2.0.1) propably it help to find problem.

Implementation-Title: orai18n.jar archives
Specification-Vendor: Oracle Corporation
Specification-Version: 11.2.0.4.0
Implementation-Version: 11.2.0.4.0-Production__Build-11
Name: oracle/i18n

**Comment by AndrewKhitrin** [comment]
@eyallior-surecomp 

Thanks !

**Comment by serge-rider** [comment]
@AndrewKhitrin thanks a lot. Let's try it.
At least in improves performance in 2-5 times on our Ora 12.2.

@eyallior-surecomp @jgarciabu Could you test this Early Access version (https://dbeaver.io/files/ea)?
I've added new Oracle config option:
![image](https://user-images.githubusercontent.com/6398845/55994627-e6f50300-5cba-11e9-9c3d-3399a4f161c4.png)

In any case we need more testing.
If this will work fine on 11 and 10 then maybe we'll enable this option by default.

**Comment by reddyshyam** [comment]
Hi @serge-rider ,

I experience this issue too though I always ignored it since it happens just the first time. I always use EA version and am on the latest release of 11th April with above setting checked but didn't make any difference my end. If it helps, we are still using Oracle 9i.

**Comment by AndrewKhitrin** [comment]
HI @reddyshyam 

Can you give us your full Oracle version number to?

I mean all position something like ths 9.2.1

Thanks,
Andrew

**Comment by reddyshyam** [comment]
> HI @reddyshyam
> 
> Can you give us your full Oracle version number to?
> 
> I mean all position something like ths 9.2.1
> 
> Thanks,
> Andrew

Thanks @AndrewKhitrin for prompt reply. My db version is Oracle9i Release 9.2.0.8.0 - 64bit

**Comment by eyallior-surecomp** [comment]
Serious improvement! The first query took 20s, but then every other query ran for the first time (on same connection) took very few seconds, then subsequent queries took nothing, as usual.

**Comment by uslss** [comment]
verified
