### ISSUE TITLE
Execute > Export does not update variables in @set commands

### ISSUE THREAD

**Issue by knwpsk** [dbeaver/dbeaver#5635]
Script:
```sql
@set t = 20190320
select '${t}'
```

When I run this script using Alt-X, it works fine.

When I run this script using Right Click > Execute > Export from Query, it does not update the variable (ever).  If I change the value of "t" and run the script again and again, it always runs the script with the same value of "t".

#### System information: 
- Operating system: Windows 10
- DBeaver version: 6.0.1 (March 25)

#### Connection specification:
- Database name and version: Irrelevant, but I'm using Postgres and MySql

**Comment by serge-rider** [comment]
See fix in 6.0.4.
Note: you need to select all `@set` commands along with your select query to process them.

**Comment by knwpsk** [comment]
Noted.
Thanks Serge!

**Comment by uslss** [comment]
verified
