### ISSUE TITLE
Save diagram in external format: Too low resolution for large diagrams 

### ISSUE THREAD

**Issue by KarlLevik** [dbeaver/dbeaver#5636]
#### System information: 
- Fedora 29
- dbeaver-ce.x86_64 6.0.1-stable (rpm)
- openjdk version "1.8.0_201" 
- Additional extensions: None?

#### Connection specification:
- Database name and version: MariaDB 10.3.13
- Driver name: mariadb-java-client-1.5.5.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No 

#### Describe the problem you're observing:
I want to save a large database diagram as a .png file, but it results in a file with not enough resolution to read the table names. I think perhaps this used to work better in previous versions (before 5.3 or even older?) because I have an old .png diagram created by dbeaver that shows my whole schema and there the table names are readable. 

#### Steps to reproduce, if exist:
You can use this table create script if you need something large. (In dbeaver I usually disable/hide the column names, and just show the table names and relationships, otherwise it's just too large to make sense.)
https://github.com/DiamondLightSource/ispyb-database/blob/master/schema/tables.sql

**Comment by ShadelessFox** [comment]
Hello @KarlLevik,

I believe it was fixed. If you are still using our product, can you try updating to newer version to see if the problem still persists?

Thanks!

**Comment by KarlLevik** [comment]
Yes, thank you! This seems to work now, currently running Version 21.0.0.202103021012.

**Comment by youennlj-sfl** [comment]
I still think the exported resolution is too low, one can clearly see aliasing on the text and lines (see attached file). It would be nice to have a setting to choose it! Especially since SVG export is no longer a thing...

<img width="1798" height="1750" alt="Image" src="https://github.com/user-attachments/assets/b7837329-d39c-4642-807e-633fe4b9729a" />
