### ISSUE TITLE
[Teradata Database] [TeraJDBC 16.20.00.10] [Error 8017] [SQLState 28000] The UserId, Password or Account is invalid.

### ISSUE THREAD

**Issue by arpanchinmay** [dbeaver/dbeaver#5643]
i have downloaded the JDBC drivers for Teradata - PFB the screeshots. When I try to connect to Terdata Database, it does not allow. I have cross checked my credentials, they are right.

![image](https://user-images.githubusercontent.com/49255979/55520463-2e323100-56c8-11e9-9c72-4c15a5f660b7.png)

DRIVER INFORMATION ON DBEAVER:
![image](https://user-images.githubusercontent.com/49255979/55520521-74879000-56c8-11e9-837c-a3519ba01897.png)

CONNECTION INFORMATION ON - Teradata SQL Assistance
![image](https://user-images.githubusercontent.com/49255979/55520433-0511a080-56c8-11e9-8fdf-10a25a802dc8.png)

**Comment by yiga2** [comment]
Since you are authenticating through LDAP, you must add to your URL string `,LOGMECH=LDAP`

**Comment by diogobaltazar** [comment]
.logmech LDAP;

**Comment by vicentinif** [comment]
@yiga2  thanks for your tips. I setup the parameter "LOGMECH=LDAP" and my connection succed.
