### ISSUE TITLE
Large string arbitrarily truncated in results grid and record view when editing or copying

### ISSUE THREAD

**Issue by dsofeir** [dbeaver/dbeaver#5644]
#### System information: 
- Operating System: openSUSE Tumbleweed 20190402
- KDE Plasma Version: 5.15.3
- KDE Frameworks Version: 5.56.0
- Qt Version: 5.12.2
- Kernel Version: 5.0.5-1-default
- DBeaver version: 6.0.0.201903101945
- OpenJDK 11.0.2 2018-10-16
- OpenJDK Runtime Environment (build 11.0.2+7-suse-1.2-x8664)
- OpenJDK 64-Bit Server VM (build 11.0.2+7-suse-1.2-x8664, mixed mode)

#### Connection specification:
- Database name and version:
MariaDB
innodb_version	5.5.59-MariaDB-38.11
protocol_version	10
version	5.5.60-MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: Yes, SSH

#### Describe the problem you're observing:
When I go to edit or copy a large string from the results grid is arbitrarily truncated. Yet the gird displays the complete of the value. See the following screenshots:

Viewing long string:
![dbeaver_long_string](https://user-images.githubusercontent.com/2790648/55522550-2d51cd00-56d1-11e9-8a88-5c01d07732d1.png)

Editing long string:
![dbeaver_long_string_edit](https://user-images.githubusercontent.com/2790648/55522556-35117180-56d1-11e9-9526-dc0fa46a5677.png)

**Comment by serge-rider** [comment]
Thanks for the bug report.

By some reason there was a limit for text length in "inline" editor (65535 chars). I can't remember why it was here and it works quite well without this limit. Maybe on some OSes it may cause problems (e.g. older 32bit  Windows which we no longer support anyway).

Anyhow, let's give it a try.

**Comment by uslss** [comment]
verified

**Comment by P-Light** [comment]
MacOS, DBeaver Version is 23.1.1.202306251800 and the problem is still here 🥲

**Comment by polmonso** [comment]
where do you find this setting?
