### ISSUE TITLE
Empty Entity column in exec plan for CTE in Postgres

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#5647]
This is reopen of #2308.
@uslss, you can explain the following simple query to reproduce
```
with
p as (select 1),
f as (select 2),
g as (select 3)
select *
from p, f,g
```
![изображение](https://user-images.githubusercontent.com/16996529/55539482-14aeda80-5704-11e9-9573-279a9ef8d1d8.png)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/61883627-74bfcb80-af03-11e9-9cb7-63bbeb9749a8.png)
