### ISSUE TITLE
Error in PostgreSQL stored function creation

### ISSUE THREAD

**Issue by Mephysto666** [dbeaver/dbeaver#5650]
#### System information: 
- Operating system (distribution) and version
- DBeaver 6.0.1
- Java 1.8.202

#### Connection specification:
- Database Postgresql 10
- PostgreSQL JDBC Driver 42.2.5

#### Describe the problem you're observing:
When I try to create a stored function I get error when the cursor is placed after first $$.

If I select entire function code I do not get error, neither if I place cursor in the line of first $$ or in lines before that.

I hope it can be useful.

Very kind regards.

Meph

**Comment by uslss** [comment]
cannot reproduce the issue anymore.
if it is still actual for you - feel free to reopen the ticket
