### ISSUE TITLE
Add a possibility to change style of Notes in ERD

### ISSUE THREAD

**Issue by tati-kru** [dbeaver/dbeaver#5651]
It would be great to have a styling option for the notes in ERD. It can be a new point in the context menu that opens Note styling settings. These settings can include:
- Font size
- Font colour
- Font style (bold, italic, underline)
- Show/hide borders
- Background colour

Each Note can have own styling settings and can be modified separately.

**Comment by Bullnados** [comment]
Bulletpoints ordered and unordered?

**Comment by uslss** [comment]
Reopened.
Window is minimized after applying of any customize option.
Also the same options are available but not applied(except background color and transparent) for tables

**Comment by serge-rider** [comment]
@Bullnados Nope. Adding any rich-text formatting is too heavy for notes. You can change only colors and font.

@uslss Fixed. Now we show only applicable styles. Issue with window minimization on some Linuxes is not related.

**Comment by uslss** [comment]
verified
