### ISSUE TITLE
Oracle TIMESTAMP WITH TIMEZONE fractional seconds  formatting

### ISSUE THREAD

**Issue by bobf32** [dbeaver/dbeaver#5653]
#### System information: 
- Windows 7 Enterprise SP1
- 5.1.6 + 6.0.1
- Bundled Java version 
- Additional extensions: None

#### Connection specification:
- OJDBC 8 full
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Am running a SELECT on a table with a TIMESTAMP WITH TIMEZONE column. 

In DBeaver, TIMESTAMPs are to be formatted as yyyy-MM-dd HH:mm:ss.ffffff z.

In the results set I am seeing a varying number of fractional second digits, see screenshot.

#### Include any warning/errors/backtraces from the logs

![2019-04-04 14_47_39-DBeaver 6 0 1 - _DWHUAT_STAGING_UEX_ Script-466](https://user-images.githubusercontent.com/6544564/55560950-3ea6d380-56e9-11e9-973f-a3da955f86cb.png)

**Comment by uslss** [comment]
@bobf32 is issue still actual for you on 6.2.5?

**Comment by bobf32** [comment]
Don't know about 6.2.5 @uslss, I'm still on 6.2.4. Not noticed the problem on that version lately...

**Comment by uslss** [comment]
so ticket could be closed?

**Comment by bobf32** [comment]
@uslss i guess so.
