### ISSUE TITLE
SQL Developer changes to json connections in their v18.3 broke connection import

### ISSUE THREAD

**Issue by mwhitis** [dbeaver/dbeaver#5654]
#### System information: 
- Operating system (distribution) and version: OS X Mojave
- DBeaver version: 6.0.1.201903251041
- Java version: Any
- Additional extensions

#### Connection specification:
- Database name and version: Oracle
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

In SQL Developer v18.3 (released in October 2018), Oracle changed their connections file from XML to JSON. As a result, connection import is no longer working. UI is presenting with "Connection list is empty"

#### Steps to reproduce, if exist:

File / Import / Third Party Configuration / Oracle SQL Developer

#### Include any warning/errors/backtraces from the logs

No errors logged, but looking at the code, it's handling the case where the xml file doesn't exist, so wouldn't expect an error.

I'd be happy to take a crack at this, but didn't know if there were any contributor processes, etc.

**Comment by riednyko** [comment]
For the latest versions we use the same XML but with corrected paths

**Comment by uslss** [comment]
Reopened.
Tested on SQL Developer 18.3. Issue still reproduced.
Connections in defined version are saved to the file with *.json extension, so DBeaver shows message Connection list is empty. If I changed, for example, extension to xml, application shows message that documents cannot be parsed
![image](https://user-images.githubusercontent.com/31996417/57165638-59f82200-6e00-11e9-9fa3-90f70f43f6c9.png)

**Comment by uslss** [comment]
verified. Works for v18.3
