### ISSUE TITLE
Improve Advanced Copy / result set 

### ISSUE THREAD

**Issue by ceinmart** [dbeaver/dbeaver#5655]
This is a feature request. 

Add to **Advanced Copy** menu for Result set the items for :

- Copy as HTML
- Copy Aligned
- Copy as SQL IN
- Copy as SQL WHERE
- Copy as SQL UPDATE
- Copy as SQL INSERT

This resources help a lot on SquirrelSQL and is missing on Dbeaver.

Just like SquirrelSQL : 

![image](https://user-images.githubusercontent.com/7062410/55564035-70aa3c80-56cd-11e9-910b-c5cbf02def92.png)

**Comment by p91paul** [comment]
You already have most of them:

- Copy as HTML: either Export Data... then HTML, or Open with -> web browser
- Copy aligned: either Export Data... then TXT, or just copy-paste from text view
- Copy as SQL IN: see screenshot below for the options I use. But this would be a nice shortcut, I suggest it to be put in the Generate SQL submenu
- Copy as SQL WHERE/UPDATE/INSERT: see the Generate SQL submenu

![immagine](https://user-images.githubusercontent.com/2157006/55577961-11701a80-5715-11e9-83ad-7a795a2ac195.png)

**Comment by ceinmart** [comment]
Hi @p91paul , 

Yes, there are similar resources but isn't the same as SquirrelSQL.
The Dbeaver option is very very very less efficient.
Let put my point of view : 

- Dbeaver export option has a lot of steps to execute, make it painful for frequent use.
- Dbeaver always reruns the SQL Statement, this is terrible, instead of copy from the result set which already cached. For slow queries this is painful.

About your solutions : 

1. Export option is very annoying for who need these options frequently because is a lot of steps to execute it.
  I see theses options I put as "shortcut" for more useful features. 
2. Export data as HTML do not work like Squirrel. 
  At least for my objective where I use a lot HTML format to paste into Outlook emails and if you select copy to clipboard they (dbeaver) copy the HTML code, not as HTML content. 
3. Copy Align from view text isn't the same because they copy with "|" chars and isn't that what I'm looking for, the idea is align text only with the values. 
3. About the Generate SQL submenu, please, where is it? 
  I'm looking for it here and do not found it.
  I tried on "quick access" box and neither there they appear. (dbeaver v6.0.1)

**Comment by p91paul** [comment]
For generate sql, right click on the resultset after selecting the rows you want to export. It's one of the last options in the context menu!

For the others, I agree with you that a faster way to achieve those goals would be most welcome. My response was just to make you discover those alternatives in case you weren't aware of them.

I suggest the implementation to be based on the excel export, which features a button in the bottom bar which triggers a one-click export of the resultset (or of current rows/cols). That button should become a menu, and feature most data export commands (txt, csv, sql, excel, html, etc). Clicking on one of them should trigger export with default options of selected rows/cols (or entire resultset if nothing selected).

This is similar to how datagrip export works.

A more advanced version of that would allow to make the list of options in that menu configurable, allowing the user to save export configurations and reuse them with one click.

**Comment by ceinmart** [comment]
About the Generate SQL submenu, aren't you using some plugin? 
This is my context menu for the result set : 
![image](https://user-images.githubusercontent.com/7062410/55651757-0e7e3400-57c0-11e9-808e-fac7b10640e1.png)

> A more advanced version of that would allow to make the list of options in that menu configurable, allowing the user to save export configurations and reuse them with one click.

That is a feature which I also think about :+1: 


> I suggest the implementation to be based on the excel export, ...

This one is a plugin which I do not test yet, I will test it now.

**Comment by serge-rider** [comment]
@ceinmart It is in data editor context menu, not SQL editor.
I think we can add "Copy As" function which will utilize data exporters but in simplified mode (export to clipboard using default options).
Mark as FR.

**Comment by ceinmart** [comment]
> @ceinmart It is in data editor context menu, not SQL editor.

Hi @serge-rider, 
Well, I think I was clicked there.... on my print screen I was right-cliked over the first row/data/field of column "SER" value 28.572 .
I also recheck if I understand right what do you means with "data editor" and looking the [wiki](https://github.com/dbeaver/dbeaver/wiki/Data-Editor) appears I'm clicking correctly.

I also right-click everything else to check if some "Generate SQL" appears and found nothing. 

My context menu do not show the "Generate SQL" like the this [wiki](https://github.com/dbeaver/dbeaver/wiki/SQL-Generation)

**Comment by serge-rider** [comment]
@ceinmart Generate SQL is only available if you are working with some particular table's data but not in custom SQL queries.

**Comment by ceinmart** [comment]
@serge-rider , thank you for this enlightenment!

I've found the "Generate SQL" option in the context menu at the "data" tab in the table properties. 
Also found this #2484 issue to improve this. 
I will add my comments there. 

Thank you!

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/56030159-d9746300-5d24-11e9-8618-bfe02582a1f3.png)

**Comment by uslss** [comment]
Reopened
Null pointer exception when trying to copy as xlsx

**Comment by uslss** [comment]
verified
