### ISSUE TITLE
Wrong translation in italian disconnection message

### ISSUE THREAD

**Issue by Kuviello** [dbeaver/dbeaver#5656]
![image](https://user-images.githubusercontent.com/49281592/55564870-20e16a80-56f9-11e9-8d86-66518ac772a7.png)
This is the message you get when you're exiting the italian localization of DBeaver without a commit of the last editings. It should be "disconnettere" instead of "disconnetterti".
The three buttons should be "Sì", "No", "Annulla", respectively.
There is also an useless extra space between "dal" and "database".

**Comment by tati-kru** [comment]
This is already fixed. Could you please check EA version: https://dbeaver.io/files/ea/?
