### ISSUE TITLE
Autocomplete Slow to Populate - Metadata Queries Firing Repeatedly

### ISSUE THREAD

**Issue by Camden-Lee** [dbeaver/dbeaver#5660]
#### System information: 
- Operating system (distribution) and version: Mac - Mojave
- DBeaver version - 6.0.1
- Java version - 8
- Additional extensions

#### Connection specification:
- Database name and version - Athena
- Driver name - Athena JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I was noticing that auto-complete was only intermittently working. Digging into the issue, it looks like DBeaver is continually running queries to update the metadata when I make a change in the query editor and auto-complete is only working after these queries finish. There seems to be several problems with this:

1. The metadata queries keep firing over and over. 

![image](https://user-images.githubusercontent.com/42618819/55582761-2036dd00-56d5-11e9-888e-e11d38629bc5.png)

2. They seem to be running very slowly.

3. In an attempt to speed up the query by limiting the data needed to be retrieved, I tried adding a schema filter to the connection, but the metadata queries don't seem to be taking into account the filter -- at least it makes no difference in how long it's running.

#### Steps to reproduce, if exist:
1. Writing a "SELECT * FROM", dbeaver kicks off a metadata query. Once it's done, I can select the appropriate database and table from autocomplete.
2. Then, if I go back and delete the "*" and attempt to input a column, dbeaver will fire another set of metadata queries. After  it's done, I can once again use autocomplete.
3. From there, it's hard to tell, but other changes to the select statement or from clause will once again kick-off the metadata queries.

**Comment by jim256** [comment]
I'm also on Mojave, on DBeaver 6.1.3, and the autocomplete suggestions either come up extremely slowly (I can watch the processing progress bar in the bottom right after every time I type and have to wait till it finishes to get a suggestion) or do not ever come up at all. Sometimes, they just come up with irrelevant suggestions (if I type "am", I get the suggestion "key").

**Comment by uslss** [comment]
is issue still actual for you?

**Comment by Camden-Lee** [comment]
@uslss Thanks for the follow-up. The primary issue I outlined where the metadata queries were kicking off multiple times when I made changes to the SELECT statement have been resolved. This ticket can be closed.
