### ISSUE TITLE
morph to delimited list bug with space in text

### ISSUE THREAD

**Issue by shungabubus** [dbeaver/dbeaver#5663]
OS: Win7 X64
Version: 6.0.0. CE

Hello All,

There is a miscalculation of number of characters in the Morph to Delimited list function as below:

Input data:
![image](https://user-images.githubusercontent.com/36946814/55641166-8737bd00-57cd-11e9-8d88-55a7ccbc183b.png)

Options:
![image](https://user-images.githubusercontent.com/36946814/55641214-a8001280-57cd-11e9-9a4e-dc758359b8f4.png)

Result:
![image](https://user-images.githubusercontent.com/36946814/55641194-9880c980-57cd-11e9-84c4-4b803023415c.png)

I am pretty sure it is a bug as when I do without the space it is OK:
![image](https://user-images.githubusercontent.com/36946814/55641283-d41b9380-57cd-11e9-8ec6-46b4bc581bf3.png)

**Comment by serge-rider** [comment]
Please clarify, what exactly is wrong with it?

**Comment by p91paul** [comment]
looks like the last character disappears!

**Comment by serge-rider** [comment]
@p91paul ah, missed that, thanks.

@shungabubus thanks for the bu report

**Comment by uslss** [comment]
verified

**Comment by shungabubus** [comment]
THANK YOU to all of you!!!!!!!!
