### ISSUE TITLE
Create Trigger Disabled

### ISSUE THREAD

**Issue by raymsmith** [dbeaver/dbeaver#5664]
#### System information: 
- Windows 7
- DBeaver version 6.0.1.201903251040
- Java version 1.8.0_181

#### Connection specification:
- Database name and version PostgreSQL 10.3
- Driver name - PostgreSQL Driver supplied with DBeaver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Unable to create trigger other than writing out the create trigger statement myself.

#### Steps to reproduce, if exist:
Right click or double click on table, go to properties tab, click Triggers on sidebar. Add trigger icon in bottom right corner disabled.

**Comment by uslss** [comment]
Reopened.
Whitespace doesn't appear where it should be.
![image](https://user-images.githubusercontent.com/31996417/56924664-26528a80-6ad6-11e9-9484-65f52115a283.png)

**Comment by uslss** [comment]
Reopened.
Please, make formatting like this
![image](https://user-images.githubusercontent.com/31996417/57016191-7ab65100-6c21-11e9-96c1-910768687c4f.png)

**Comment by uslss** [comment]
verified
