### ISSUE TITLE
No error on revoke when user has insufficient rights to revoke (GUI and SQL)

### ISSUE THREAD

**Issue by thorstenkampe** [dbeaver/dbeaver#5665]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.0.1
- Java version: 1.8.0_201-b09
- Additional extensions: /

#### Connection specification:
- Database name and version: PostgreSQL 11.2
- Driver name: Default driver (42.2.3.jre7)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
No error on revoke when user has insufficient rights
This happens when using the GUI or when executing the statement

Expected result: error or warning.

In contrast using psql:
```
psql (11.2)
Geben Sie »help« für Hilfe ein.

test@db:5432/Chinook psql> REVOKE ALL ON TABLE public."Album" FROM test;
WARNING:  no privileges could be revoked for "Album"
WARNING:  no privileges could be revoked for column "tableoid" of relation "Album"
WARNING:  no privileges could be revoked for column "cmax" of relation "Album"
WARNING:  no privileges could be revoked for column "xmax" of relation "Album"
WARNING:  no privileges could be revoked for column "cmin" of relation "Album"
WARNING:  no privileges could be revoked for column "xmin" of relation "Album"
WARNING:  no privileges could be revoked for column "ctid" of relation "Album"
WARNING:  no privileges could be revoked for column "AlbumId" of relation "Album"
WARNING:  no privileges could be revoked for column "Title" of relation "Album"
WARNING:  no privileges could be revoked for column "ArtistId" of relation "Album"
REVOKE
```

#### Steps to reproduce, if exist:
1. create user
2. grant SELECT on table to user
3. login as user
4. try to revoke SELECT for user
5. Save -> persist
6. no indication that command was not successful
#### Include any warning/errors/backtraces from the logs
No error

**Comment by arryaz05** [comment]
Have you tried giving revoke all inmideatly after user creation to make sure it is not being created with wrong privileges?

**Comment by thorstenkampe** [comment]
I do not understand the question. The user `test` does not have privileges for `REVOKE ALL`. That is not the problem. The problem is that issuing `REVOKE ALL` silently fails without indicating that it failed.

**Comment by arryaz05** [comment]
What i meant was trying to revoke-all on test user inmediatley after creating it (without loging into test user yet), other option would be create user with read only option
