### ISSUE TITLE
How to connect enterprise GitHub?

### ISSUE THREAD

**Issue by pravinpande** [dbeaver/dbeaver#5666]
I am trying to connect to my enterprise GitHub repository from DBeaver but it gives me below errors:
![image](https://user-images.githubusercontent.com/17124639/55654049-44bab400-57be-11e9-9777-457cb458a12b.png)

**Comment by pravinpande** [comment]
Any suggestions on this? I can connect to my personal GitHub account but not my enterprise account. Do I need to purchase license?

**Comment by serge-rider** [comment]
Could you provide a bit more details. What are you trying to perform?
Use Git integration directly from DBeaver?
Use Eclipse integration?
Download drivers?
Something else?

**Comment by pravinpande** [comment]
@serge-rider I am trying git integration from DBeaver. I need to push my code to remote repo.

**Comment by serge-rider** [comment]
What Git extension do you use?
Are you behind some corporate firewall/proxy?

**Comment by pravinpande** [comment]
@serge-rider  I am using Egit from http://download.eclipse.org/egit/updates
And no my computer doesn't use proxy server but I am behind firewall.

**Comment by serge-rider** [comment]
I'm trying to figure out what is the difference between enterprise GitHub and regular GitHub (non-public repositories). EGit integration works fine with regular (public or private) repositories on GitHub.

Are you sure you are doing everything right?
Can you clone/update regular GitHub repositories (e.g. https://github.com/dbeaver/dbeaver/)?

**Comment by serge-rider** [comment]
Oops, just saw that you mentioned that you are behind a firewall. It is definitely the reason why it doesn't work.
In any case it is not DBeaver issue, see https://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.egit.doc%2Fhelp%2FEGit%2FUser_Guide%2FUser-Guide.html

**Comment by pravinpande** [comment]
@serge-rider  Makes sense. Can you guide me what needs to be done? I can connect to public repo. I'll have to instruct my networking team to do it.

**Comment by serge-rider** [comment]
We'll add Git UI integration in #5581
If it won't work with EGitHub - please write a note.
