### ISSUE TITLE
Insert multiple values

### ISSUE THREAD

**Issue by lrweck** [dbeaver/dbeaver#5667]
Is it possible to have an option to create inserts with multiple values?

Today when can do:

Insert into table (a,b) values(1,2);
Insert into table (a,b) values(1,3);

It would be nice to be able to do:
Insert into table (a,b) values 
(1,2),(1,3)...

**Comment by arryaz05** [comment]
My friend, you can actually do what you are saying with most of the database engines, you need to lookup the correct syntax for your flavour(PostgreSQL, MySQL, SQLite etc)

**Comment by lrweck** [comment]
@arryaz05 sorry I wasn't clear.

I think having an option to transform multiple insert statements into one would be useful. Currently I have only the option to do N inserts, like this:

![image](https://user-images.githubusercontent.com/26086198/55687632-95a8e480-5945-11e9-9e1c-580a5ae4e256.png)

**Comment by arryaz05** [comment]
I see what you mean, not sure if Generated SQL will do the trick but maybe just a good old statement?
Run a script instead

**Comment by CarlGraff** [comment]
if you are doing this a lot I recommend copying the multiple insert statements into an editor like notepad++ where you easily convert this to a single statement either with regex or a macro
