### ISSUE TITLE
constraint type got translated

### ISSUE THREAD

**Issue by steelunicorn** [dbeaver/dbeaver#5668]
In 6.0.1 creating primary key in table constraints resulting in error because autogenerated ddl for primary key contains "primary key" translated into interface language.
Like this: 
ALTER TABLE {schema_name}.{table_name} ADD CONSTRAINT {table_name}_pk ПЕРВИЧНЫЙ КЛЮЧ ({column});

**Comment by serge-rider** [comment]
This was already  fixed, thank for the report anyway
