### ISSUE TITLE
Text editor - long lines visibility problem

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#5670]
In some cases line text lines are invisible. This happens in SQL editor and in the text value panel editor.
This is a known Eclipse bug - https://bugs.eclipse.org/bugs/show_bug.cgi?id=23406 . It is 17 years old (omg). It caused by WinAPI limitations. I hope we still have a chance for fixing it.

**Comment by uslss** [comment]
still reproducible in 21.3.2

**Comment by E1izabeth** [comment]
Can't reproduce against DBeaver 23.0.0.
