### ISSUE TITLE
Greenplum 4.3 - Expanding list of tables in schema gives the following error -SQL Error [42703]: ERROR: column x.execlocation does not exist Position: 337

### ISSUE THREAD

**Issue by iMchxx** [dbeaver/dbeaver#5671]
#### System information: 
- Operating system (distribution) and version
```
win10 pro 17763
```

- DBeaver version
```
6.0.2
```

- Greenplum version
```
PostgreSQL 8.2.15 (Greenplum Database 4.3.99.00 build dev) compiled on Nov 29 2018 20:41:44
```

i updated the dbeaver to `6.0.2` this morning. but it raises an error when i expand the list of table:
```
SQL Error [42703]: ERROR: column x.execlocation does not exist Position: 337

```

**Comment by serge-rider** [comment]
This is very similar to #5568.
Unfortunately I wasn't able to test this as I don't have test GP 4.x server.
Could you test the fix in the Early Access version (https://dbeaver.io/files/ea)?

**Comment by Stalker404** [comment]
I checked early access version for Win - error is fixed. 
win10 + Greenplum Database 4.3.24.0

**Comment by serge-rider** [comment]
@Stalker404 thanks for testing

**Comment by iMchxx** [comment]
> This is very similar to #5568.
> Unfortunately I wasn't able to test this as I don't have test GP 4.x server.
> Could you test the fix in the Early Access version (https://dbeaver.io/files/ea)?

i install the `dbeaver-ce-6.0.2-x86_64-setup.exe` in the [Early Access version](https://dbeaver.io/files/ea), and it can expand the list of tables.yeah, it works.
