### ISSUE TITLE
Executing a stored Procedure asks to bind variables

### ISSUE THREAD

**Issue by zelite** [dbeaver/dbeaver#5674]
#### System information: 
- Ubuntu 18.4
- 6.0.2
- openjdk version "1.8.0_191"

#### Connection specification:
- MSSQL 2017
- MS SQL Server / SQL Server

#### Describe the problem you're observing:

Since version 6.0.2, when executing a stored procedure, it asks me to bind variables. So, I need to repeat in the bind variable window the name of the variables. This seems unecessary.

#### Steps to reproduce, if exist:

Open a new SQL-Editor. Write a script that executes a Stored Procedure:

```
EXEC [MyDB].mySchema.myStoredProcedure @parameter1 = 'test', @parameter2 = 42;
GO
```

Click "Execute Script". The following window comes  up:

![image](https://user-images.githubusercontent.com/9040070/55704821-75c4ff80-59dd-11e9-93b5-0a29b8b442e5.png)

I need to retype the variable names. 

Afterwards the script gets executed as:

`EXEC [MyDB].mySchema.myStoredProcedure @parameter1 = 'test', @parameter2 = 42;`

Why is there this time wasting step in between with the binding of the variables? They don't need to be binded.

**Comment by acmg** [comment]
The same in Windows 10:

`DECLARE @Vclie TABLE
	( ID VARCHAR(20) )`
`INSERT
	INTO
		@Vclie
	VALUES('171')`

**Comment by acmg** [comment]
@zelite, can you disable the "Enable SQL parameters" and test again? 

![image](https://user-images.githubusercontent.com/2376426/55734070-36b79e00-5a1f-11e9-9f67-b1bf0acf20b8.png)

It's working for me now.

**Comment by serge-rider** [comment]
This looks like a bug. In 6.0.2 symbol @ is evaluated as parameter prefix by default (for SQL Server)). It shouldn't.

**Comment by uslss** [comment]
Verified
