### ISSUE TITLE
Help with fixing issue

### ISSUE THREAD

**Issue by alminisl** [dbeaver/dbeaver#5677]
https://github.com/dbeaver/dbeaver/issues/5310

Hello,

As far as I can see this issue is very rare and only some people get it. 

Don't know the status, but as far as I can see there is no real progress on it. If possible, I would try to fix this or at least provide some information. It has something to do with the dark/light themes on macbook, but I can not debug it. 

Now, my question is, when I clone the project what is the best way to run and debug it ? I've not worked much with Java before so I'm kinda a noob but really would like to fix this since I need dbeaver and Don't want to install all the other DB software for all the Dbs I have :/

**Comment by serge-rider** [comment]
Hello,

First of all please test it in 6.0.2 (we migrated to the newest Eclipse platform, maybe this will help).

In order to build DBeaver you need to setup Java and Maven. Then you can build dbeaver by running `mvn clean install` in the root folder of repo. Find binaries in the `product/standalone/target/products`.

If you want to do some real debugging then you could try to open it in Eclipse (https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse).

**Comment by alminisl** [comment]
> Hello,
> 
> First of all please test it in 6.0.2 (we migrated to the newest Eclipse platform, maybe this will help).
> 
> In order to build DBeaver you need to setup Java and Maven. Then you can build dbeaver by running `mvn clean install` in the root folder of repo. Find binaries in the `product/standalone/target/products`.
> 
> If you want to do some real debugging then you could try to open it in Eclipse ([dbeaver/dbeaver/wiki/Develop-in-Eclipse](https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse)).

Sadly, I still have the issue :( 

Very weird. 

Thanks for the instructions, I will try and set it up today and check why it is failing on my side. 

Thank you !

**Comment by alminisl** [comment]
So I've kinda figured out what the issue is and how to "fix" it. 

`defaults write -g NSRequiresAquaSystemAppearance -bool Yes`

This command when turned on, i can't open Dbeaver, when I set it to NO (false) it seems like it is working. @serge-rider Can you take a look ? I have no idea what it is but I can't have full "Dark mode" on mac and use dbeaver. 

More info: http://osxdaily.com/2018/10/15/dark-menu-dock-light-theme-macos/
https://forums.macrumors.com/threads/dark-mode-not-working.2164730/
