### ISSUE TITLE
DBeaver (portable) for 32bit Java under 64bit Win?

### ISSUE THREAD

**Issue by bsto** [dbeaver/dbeaver#5678]
On my 64bit Win7 system (only) 32bit Java is installed. It works for a lot of Java programs.

Now I downloaded and extracted 

dbeaver-ce-6.0.2-win32.win32.x86_64.zip 

from this webpage:
https://github.com/dbeaver/dbeaver/releases

When I doubleclick on dbeaver.exe I am getting an error popup 
"Java was started but returned exit code 13"

Why?

It seems to my that DBeaver found a 64bit WindowsOS and hence thinks 64bit Java should be used.
How can I tell DBeaver to use 32bit Java?

On the other side if the Dbeaver package contains only 64bit Java version why does the package file name contain the string "win32.win32.x86" indicating 32bit version?

Where else can I download the pure 32bit DBeaver version?

Thank you
Ben

**Comment by weswaldix** [comment]
Did it work with previous versions of DBeaver?

**Comment by tchibatron** [comment]
Am afraid, DBeaver has not been working with 32 bit version of  Java since 6.0.1 version. https://dbeaver.io/2019/03/25/dbeaver-6-0-1/

**Comment by bsto** [comment]
@tchibatron:

Thank you. Is this temporary?
Will Dbeaver ever work with Java 32bit together again?

**Comment by weswaldix** [comment]
No probably not unless there's a lot of resistance to it but I wouldn't bet on it.

**Comment by tati-kru** [comment]
@bsto because of DBeaver is based on Eclipse and new Eclipse versions does not support 32bit  anymore, DBeaver CE will not work with old systems as well. We are going to keep this for the DBeaver EE version only and create builds with old and new Eclipse for big releases.
