### ISSUE TITLE
Wrong indentation in SQL editor

### ISSUE THREAD

**Issue by alesc2000** [dbeaver/dbeaver#5683]
#### System information: 
- Operating system Ubuntu 18.04
- DBeaver version 6.0.2

#### Connection specification:
- Database name and version Postgres 9.6
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
Wrong indentation for new line after query ending with "ORDER BY xxx DESC".
If the query ends with "ORDER BY xxx", the indentation is ok.
Related to #5389

**Comment by alesc2000** [comment]
I found other indentation fault:

SELECT * FROM table1 WHERE a LIKE '%b%'
	-- wrong indentation

SELECT * FROM table1 WHERE a = 'b'
-- indentation ok

**Comment by serge-rider** [comment]
Thanks for the bug reports

**Comment by uslss** [comment]
Reopened.  Issue still reproduces with lines after ""ORDER BY xxx DESC/ASC"

**Comment by uslss** [comment]
verified

**Comment by carlosspohr** [comment]
Hi @serge-rider and @alesc2000,

I was ready to open new issue when I found this one...

In previous version, the indentation on new lines was OK, on ```6.0.2``` I get this while typing:

![image](https://user-images.githubusercontent.com/637767/56359360-b7ad2d00-61b7-11e9-8f98-1cebad999718.png)

Or as plain text with ``\n`` and ``\t``:
```
select
	a.*
	from
		tb_foo a
		where
			a.bla > 0
			and
				a.foo > 1
				group by
					a.faa
					order by
						a.faa;
```
This occurs on both Windows and Linux, just in ``6.0.2`` version.
