### ISSUE TITLE
dBeaver crashed & closed after press Browse button in creation of new connection

### ISSUE THREAD

**Issue by Wichart009** [dbeaver/dbeaver#5686]
I'm using dBeaver 6.0.2 CE create a new connection to FirebirdSQL 3.0 after pressed Browse button to locate to database path, it crashed & closed. Could you please check, thanks?

**Comment by tchibatron** [comment]
@Wichart009 I was wondering if you attach log files. [Here](https://github.com/dbeaver/dbeaver/wiki/Log-files) you can find out some instruction to find log files.
Which OS do you use?

**Comment by Wichart009** [comment]
Thanks a lot for your support, I attached my information that you requested.
And how to solve the error when connect to Firebird, I already set wireCrypt = Disabled in firebird.con.
![dBeaverCE602-Firebird30](https://user-images.githubusercontent.com/12468949/55849730-e6098780-5b7b-11e9-87e2-b4e397d6599d.jpg)
![dBeaverCE603-Firebird30(1)](https://user-images.githubusercontent.com/12468949/55849968-c161df80-5b7c-11e9-98b7-ea4f351dc6fe.jpg)
![MySystem](https://user-images.githubusercontent.com/12468949/55849434-c1f97680-5b7a-11e9-9e9f-67f46c31c559.jpg)
[dBeaverCE602.log](https://github.com/dbeaver/dbeaver/files/3061827/dBeaverCE602.log)

**Comment by serge-rider** [comment]
Perhaps this is related to your Windows user name (with space inside).
You could try to run dbeaver with -data parameter (it set workspace location).
- Create some directory (WORKSPACE_PATH) on your local disk.
- Run `dbeaver.exe -data PATH_TO_WORKSPACE` in terminal (or add `-data PATH_TO_WORKSPACE` in DBeaver start shortcut).

**Comment by Wichart009** [comment]
OK, but in the log file shows a folder's name for version 6.0.1 that still occurred in my drive. Now I installed version 6.0.2, why the error occurred for the old, not for the lastest.
And why there are too many folders for an old version of dBeaver since I used for the 1st time? Can I delete?
![dBeaverCE602-Firebird30(2)](https://user-images.githubusercontent.com/12468949/55890515-03227280-5bdd-11e9-95f6-83480eba341e.jpg)
![dBeaverCE602-Firebird30(3)](https://user-images.githubusercontent.com/12468949/55890516-03bb0900-5bdd-11e9-93af-c2014466c4b7.jpg)

**Comment by serge-rider** [comment]
This is weird. These folders are created only by older versions of DBeaver. Maybe somebody else used DBeaver on this machine before?
And yes, you can easily delete all these folders, these are just caches, nothing important is there.

**Comment by Wichart009** [comment]
I had tried to set WORKSPACE_PATH many times, but it's still an error for version 6.0.1 in caches. So I uninstall, restart my machine & reinstall the version 6.0.2. It' working fine now. Thanks a lot for your kindly help & supports.
![dBeaver-Firebird](https://user-images.githubusercontent.com/12468949/56452837-3d201100-6361-11e9-9e13-6bfeddd0e041.jpg)
