### ISSUE TITLE
Backup tool fails to export some tables in postgresql

### ISSUE THREAD

**Issue by iaunzu** [dbeaver/dbeaver#5688]
#### System information: 
- Operating system (distribution) and version: Windows 7 64 bits
- DBeaver version: 6.0.2
- Java version: 8
- Additional extensions: None

#### Connection specification:
- PostgreSQL 9.6
- PostgreSQL 9.6 - Driver 42.2.0.jre7
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Sometimes DBeaver do not backup all tables. Backup script does not contain all selected tables.

#### Steps to reproduce, if exist:
1. Right click on database with **multiples schemas** > Tools > Backup.
2. Select **two or more** schemas and **deselect** some tables from only one of them.
3. Start backup and check generated pg_dump command on the log.

**Comment by uslss** [comment]
Thanks for bug report.

Example: we've got two checked databases qa1 (newtable_1, newtable_2 и newtable) and qat1 (newtable):
- if all tables are checked in all checked databases:  --format=c -n qa1 -n qat1 --verbose --host=127.0.0.1 --port=19445 ****** pagila
-  newtable_1 from qa1 is unchecked : --format=c -t qa1.newtable_2 -t qa1.newtable_1 --verbose --host=127.0.0.1 --port=19445 ****** pagila - so in that case second database isn't exported at all

**Comment by serge-rider** [comment]
Fixed. 
Also version of PG native client was updated.
Thanks for the bug report.

**Comment by uslss** [comment]
verified
