### ISSUE TITLE
Cannot execute query

### ISSUE THREAD

**Issue by midori-fukami** [dbeaver/dbeaver#5689]
#### System information: 
- Windows 10 Pro
- DBeaver version 5.3.5
- Java version 1.8.0_201

I cannot execute this query, in another IDE I executed normally.
Seems DBeaver is selecting "ria" from my query and execute just this, and not the line

#### Steps to reproduce:
Execute with Ctrl+enter this query
select * from tb_proposta_categoria

![image](https://user-images.githubusercontent.com/13758811/55797593-3a8d0400-5aa3-11e9-8b5c-fff166c1ded4.png)

**Comment by nmat** [comment]
You can read about how the execution works here: https://github.com/dbeaver/dbeaver/wiki/SQL-Execution

Not sure but if you do have a selection then it will only try to use the selection to run the query if I am not mistaken.

**Comment by p91paul** [comment]
I believe you pressed ctrl+enter while just "ria" was selected. Try with nothing selected!

**Comment by midori-fukami** [comment]
> I believe you pressed ctrl+enter while just "ria" was selected. Try with nothing selected!

I'm selecting nothing! When I pressed ctrl+enter, an error appear and "ria" is selected without me doing anything. So weird

**Comment by p91paul** [comment]
Well, this is beyond weird :) what's your database? have you tried upgrading to 6.0.2?

**Comment by nmat** [comment]
I tested really quick here on the SQLite database provided with:

`select * from Artist`

1. Placed cursor at random places in the select - No error
2. Placed cursor at end and beginning - No error
3. Selected Artist - Error

@midori-fukami are you sure you are not selecting anything? What happens if you place the cursor at the beginning of the select and just press Ctrl+Enter?

I also tested using several select statements in the same doc to see if that could cause problems but the same effect happens as with above.

**Comment by midori-fukami** [comment]
> Well, this is beyond weird :) what's your database? have you tried upgrading to 6.0.2?

I updated right now, and continue the same error =/

**Comment by midori-fukami** [comment]
> I tested really quick here on the SQLite database provided with:
> 
> `select * from Artist`
> 
> 1. Placed cursor at random places in the select - No error
> 2. Placed cursor at end and beginning - No error
> 3. Selected Artist - Error
> 
> @midori-fukami are you sure you are not selecting anything? What happens if you place the cursor at the beginning of the select and just press Ctrl+Enter? looking at the image above you will see that ria is selected so therefore the questions.
> 
> I also tested using several select statements in the same doc to see if that could cause problems but the same effect happens as with above.

Mine is SQL

Yeah, others tables, work normally, just tables that end with "ria" are with this problem.

I place the cursor  in the beginning, and it's works
![image](https://user-images.githubusercontent.com/13758811/55900099-d2224d80-5b9c-11e9-843f-d5f96463f992.png)

But I'm always with the cursor in the end, because I wrote and run, every time.

When I place the cursor in the end
![image](https://user-images.githubusercontent.com/13758811/55899883-41e40880-5b9c-11e9-81b1-e9da624870b8.png)

Just pressed ctrl+enter
![image](https://user-images.githubusercontent.com/13758811/55899949-66d87b80-5b9c-11e9-9bb1-e944add88b38.png)

I don't know why "ria" is been selected from nowhere.

Try to create a table with "ria" in the end of the name.

**Comment by uslss** [comment]
there is no update on issue for a long time.
ticket closed.
if it is still actual - feel free to reopen the ticket
