### ISSUE TITLE
Connecting to PostgreSQL using SSH tunnel?

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#5691]
Is it possible to setup SSH tunnel to connect to PostgreSQL using DBeaver? Many other databases have _Network_ section in connection settings where SSH can be configured, but PostgreSQL doesn't have it.

![obraz](https://user-images.githubusercontent.com/20753183/55804054-e3efec00-5adb-11e9-8c8b-afe35e02fe35.png)

![obraz](https://user-images.githubusercontent.com/20753183/55804174-17327b00-5adc-11e9-87bf-47d6b7122c6a.png)

#### System information: 
- Windows 10
- DBeaver CE 6.0.2
- Java version: 1.8.0_77
- No extensions

**Comment by serge-rider** [comment]
Generally PostgreSQL connections work just like other dbs. There has to be network config.
Please check logs (https://github.com/dbeaver/dbeaver/wiki/Log-files) when you opening connection dialog - maybe something was broken in the configuration?

![image](https://user-images.githubusercontent.com/6398845/55851568-df6e1680-5b61-11e9-92fb-dc6879de2496.png)

**Comment by maln0ir** [comment]
Yes, there was something wrong in configuration. Reinstalling with _reset configuration_ option checked solved this issue.
