### ISSUE TITLE
Preferences not saved when I open a connection via command line

### ISSUE THREAD

**Issue by dsu-inf** [dbeaver/dbeaver#5702]
#### Short story
I need to save the connection type to prod (is only an use case example) after I open a connection to an Oracle database via command line.
The command used is:
```
dbeaver.exe -data "C:\Users\dsu\.dbeaver-acme\CLIENT_1" -disconnectAll -newInstance -con "name=CLIENT_1|driver=oracle|url=jdbc:oracle:thin:@10.99.1.3:1521:ORCL|user=CLIENT_1|password=CLIENT_1|connect=true|openConsole=true|database=acme"
```

The first problem that I encountered is that if I didn't specify the database name (`acme` in above example), the button `OK` from `Connection settings` is disabled. The problem is know and it's marked as solved. I added https://github.com/dbeaver/dbeaver/issues/3001#issuecomment-482100038 to specify that I feel that it's not.
The behavior is OK, the color is changed by the content of `C:\Users\dsu\.dbeaver-acme\CLIENT_1\General\.dbeaver-data-sources.xml` looks "empty":
```xml
<?xml version="1.0" encoding="UTF-8"?>
<data-sources>
    <filters/>
</data-sources>
````

My expectation is to see a `data-source` entry with a `connection` that has an attribute `type=prod`.

#### System information: 
- Windows 10
- DBeaver 5.0.3
- Java 1.8

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
There are not any updates on issue for a long time. 
It is closed.
If it is still actual for you - feel free to reopen it
