### ISSUE TITLE
Athena connection fails with certification issues

### ISSUE THREAD

**Issue by mnt1979** [dbeaver/dbeaver#5704]
Connection to Athena using profile credentials fails with certification path issue since version 6.0.   It is working correctly for 5.3.5 on Mac.

[Simba][AthenaJDBC](100131) An error has been thrown from the AWS SDK client. Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        unable to find valid certification path to requested target
        unable to find valid certification path to requested target

**Comment by mnt1979** [comment]
I downloaded portable version of 6.0.2 and tested that it is working without any error so it looks like full version with JRE is creating this issue.

**Comment by serge-rider** [comment]
Yes, looks like we shipping outdated JRE along with pkg installer. As a result it can't connect with some https web sites (because of outdated root certificate authority list).
We need to update JRE. I've just created #5706 for this.

Thanks for the bug report.

**Comment by mnt1979** [comment]
Still the same issue with pkg version.   dmg is fine.

**Comment by serge-rider** [comment]
It still happens in some corporate environments.

**Comment by serge-rider** [comment]
https://github.com/aws/aws-sdk-java/issues/1757

**Comment by serge-rider** [comment]
Perhaps the problem was caused by caching proxy. It may replace Athena host certificate with own certificate. In that case it may be required to add proxy certificate into DBeaver Java keystore. Or to use local system Java.

**Comment by serge-rider** [comment]
Now DBeaver uses OS certificate storage. Please test the fix in the Early Access version (https://dbeaver.io/files/ea)

**Comment by Matvey16** [comment]
Verified athena URL changes. Needs to be tested in enterprise enviroment. Will be reopened in case of issues
