### ISSUE TITLE
Color of connection items in database navigator does not match connection color

### ISSUE THREAD

**Issue by darrylkuhn** [dbeaver/dbeaver#5705]
#### System information: 
- OS Version: Windows 10 Pro 1809.17763.379
- DBeaver version: 6.0.0
- Java version:1.8.0_77 
- Additional extensions: None

#### Describe the problem you're observing:
First off DBeaver is great and thanks for providing such a feature rich tool!

DBeaver allows me to color code different connections. When executing a query it is very clear which environment that query will be executed in (the entire script window is colored) however the application also offers a "Database Navigator" with access to all connections and within the database navigator there is no color coding or indication of which environment you are working in (other than the top level connection name which is often not visible hidden). In my case I had selected my sandbox connection in the "Select Data Source" and so had a visual cue that I was operating on the sandbox but had inadvertently opened a production database connection in the Database Navigator. I used the context menu in the navigator to drop an index and it was unclear to me that I was operating against the production connection.

![dbeaver connection selected](https://user-images.githubusercontent.com/3458313/55980176-c42a0680-5c48-11e9-8e9a-72a982e1bede.png)
![dbeaver connection selected unclear](https://user-images.githubusercontent.com/3458313/55980180-c5f3ca00-5c48-11e9-8f81-2779803f969c.png)

I would like to recommend that list items in the database navigator also present the connection color in some way to serve as a visual indicator (e.g. the open/close caret is colored or change the background color of the item to match the connection). Another option would be to color the confirmation window that prompts "Are you sure...?" and / or including the connection name in the prompt.

**Comment by serge-rider** [comment]
Generally I agree. We need better indication of prod connections.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/57969514-6ba10400-7980-11e9-9dcb-e1a92bacbe94.png)

**Comment by uslss** [comment]
verified

**Comment by darrylkuhn** [comment]
Downloaded and verified as well - thanks guys you rock!
