### ISSUE TITLE
Cannot execute sql script

### ISSUE THREAD

**Issue by pauliusjan** [dbeaver/dbeaver#5708]
Hi, Im new in DBeaver and SQL, so Im trying excecute this script:
`DECLARE @ExecStr NVARCHAR(4000);
SET @ExecStr = 'SELECT * FROM Paslaugos WHERE pas_kodas = @kodas';
EXEC sp_executesql @ExecStr, N'@kodas varchar(15)', '1';`

I user new 6.0.2 dbeaver, and  this is to ms sql server. when I press alt+x, its asking me for parameter ExecStr value in Bind parameter window... But when I execute this script in SMSS application it runs fine... I tried also highlight all script ant press ctrl+enter, but I get same result, its asking me for parameter value... why is that?

**Comment by nmat** [comment]
I have had the same problem with mssql where a popup comes and asks for the input of a variable in 6.0.2 when there is a variable already set.

Been trying to find a way around this but can't find anything to say not to ask for this.

**Comment by nmat** [comment]
https://github.com/dbeaver/dbeaver/issues/5674

similar to this?

**Comment by pauliusjan** [comment]
Yeah, 6.0.3 version fixed it kind of. I have to select all script ant then ctrl+enter. when I press alt+x its stops and wants me to declare @ExecStr variable :D
