### ISSUE TITLE
Comments do not show in definition after creating views/functions. Oracle.

### ISSUE THREAD

**Issue by GAZ082** [dbeaver/dbeaver#5711]
Hey. I create a view or function and go like:

```
CREATE OR REPLACE VIEW SOMEVIEW AS
/*COMMENT HERE, IN BLOCK.*/
SELECT ....
SOMEFIELD --SOME COMMENT
```
And they are not shown when  I check the definition with F4. Neither the case in Toad. However, when I redo the view in Toad the comments are displayed in the definition. I believe there is a Dbeaver option I'm missing? Perhaps a bug?

Dbeaver: 6.0.1.201903251040
Windows 10x64
Oracle: 10.2.05

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
We show view comment separately (in Comment field on the top).
I've fixed view alter procedure so comment will be added to `create or replace view` statement always.

**Comment by kseniiaguzeeva** [comment]
Verified (the last comment is in Declaration tab)
