### ISSUE TITLE
New data source selection UI flaky

### ISSUE THREAD

**Issue by reddyshyam** [dbeaver/dbeaver#5712]
#### System information: 
- Operating system (distribution) and version  - Windows 10 Pro 64 bit 1903 (18362.53)
- DBeaver version - 6.0.3 (EA 11Apr2019 release)
- Java version  - 1.8
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Include any warning/errors/backtraces from the logs

![Issue](https://user-images.githubusercontent.com/12392746/56049205-94712080-5d66-11e9-8120-8321779e7dd2.gif)

Please see attached gif. On the editor, with the new UI for data source selection, changing data source has no effect. Hope gif helps

**Comment by serge-rider** [comment]
I can't reproduce this.
I fact datasource is changed (see editor tab title) but this change isn't reflected in the toolbar.
Could you check error/debug logs (https://github.com/dbeaver/dbeaver/wiki/Log-files) for any related errors?
Also fresh EA version was published today.

Thanks for testing this.

**Comment by reddyshyam** [comment]
Hi @serge-rider ,

Please see attached error message I see. Not sure if related but that is the only thing for today and yes, I am on 12Apr2019 6.0.3 EA

![Screenshot_20190413_130025](https://user-images.githubusercontent.com/12392746/56076606-11e17300-5df1-11e9-97aa-d1b04698111a.png)

**Comment by serge-rider** [comment]
Weird. This "No CSSEngine" error means that something seriously wrong with the installation (and I see this from you screenshot - this is a classic theme without any modern Eclipse styling).

Could you try to:
- Remove previous version of DBeaver and then delete DBeaver install directory completely. Then install DBeaver again. Sometimes (especially after numerous version upgrades) some artifacts from older versions remain in DBeaver install folder and this may cause problems.
- Reset UI cache (https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings )

I've added an extra workaround in the toolbar update function. It is a not a real solution but if none of things above will help then you could try it (new EA has been published).

**Comment by reddyshyam** [comment]
Hi @serge-rider ,

Thanks for the prompt reply and quick work around. I tried work around first on the new EA build 13Apr2019 but it didnt help. Uninstall, delete installation folder, reinstall and resetting UI cache seems to have resolved the issue. Much appreciated! Closing the issue, will re-open if the problem reccurs.
