### ISSUE TITLE
Syntax coloring: table names 

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#5714]
Is there any way to set tables names coloring in query editor ?

This is very handy feature - eg you can easily see opening bigger script if table exists or not.

**Comment by E1izabeth** [comment]
It's done in https://github.com/dbeaver/dbeaver/pull/21788 and will be available in the next release (DBeaver 23.2.5)
The feature is turned off by default, you can enable it here 

![image](https://github.com/dbeaver/dbeaver/assets/28875055/dca4fef3-3bd6-484b-a11b-21cf916d1423)

**Comment by E1izabeth** [comment]
Done in scope of this issue #10831
