### ISSUE TITLE
Ctrl + Space Not working in SQL Editor to populate column names Windows 10

### ISSUE THREAD

**Issue by Jnb2387** [dbeaver/dbeaver#5715]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
6.0.2
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
PostgreSQL 9.6
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
Pressing CTRL + SPACE to list all column names after * is no longer working. 

#### Steps to reproduce, if exist:
write query to select all columns
SELECT * FROM ccd.parcels
move cursor to after *, hit ctrl + space. No change is viewed.
works in linux but not windows anymore

**Comment by uslss** [comment]
Issue isn't reproducible on 6.1.2.
Ticket is closed. 
If issue is still actual for you, feel free to reopen ticket.
