### ISSUE TITLE
mvn package - build fails

### ISSUE THREAD

**Issue by copart** [dbeaver/dbeaver#5717]
#### System information: 
- Operating system (distribution) and version: Fedora 29
- DBeaver version: 6.0.2
- Java version : 1.8
- Additional extensions: n/a

#### Describe the problem you're observing:
Unable to build

#### Steps to reproduce, if exist:
Try to build via "mvn package". This worked fine in 6.0.0

#### Include any warning/errors/backtraces from the logs
#NOTE: File paths have been edited slightly for privacy

dbeaver-6.0.2/plugins/org.jkiss.dbeaver.net.ssh.ui/src/org/jkiss/dbeaver/ui/net/ssh/SSHTunnelConfiguratorUI.java:[40] 
[ERROR]         import org.jkiss.dbeaver.utils.StandardConstants;
[ERROR]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.jkiss.dbeaver.utils.StandardConstants cannot be resolved
[ERROR] ./rpm/BUILD/dbeaver-6.0.2/plugins/org.jkiss.dbeaver.net.ssh.ui/src/org/jkiss/dbeaver/ui/net/ssh/SSHTunnelConfiguratorUI.java:[80] 
[ERROR]         portText = UIUtils.createLabelSpinner(settingsGroup, SSHUIMessages.model_ssh_configurator_label_port, SSHConstants.DEFAULT_SSH_PORT, StandardConstants.MIN_PORT_VALUE, StandardConstants.MAX_PORT_VALUE);
[ERROR]                                                                                                                                              ^^^^^^^^^^^^^^^^^
[ERROR] StandardConstants cannot be resolved to a variable
[ERROR] /rpm/BUILD/dbeaver-6.0.2/plugins/org.jkiss.dbeaver.net.ssh.ui/src/org/jkiss/dbeaver/ui/net/ssh/SSHTunnelConfiguratorUI.java:[80] 
[ERROR]         portText = UIUtils.createLabelSpinner(settingsGroup, SSHUIMessages.model_ssh_configurator_label_port, SSHConstants.DEFAULT_SSH_PORT, StandardConstants.MIN_PORT_VALUE, StandardConstants.MAX_PORT_VALUE);
[ERROR]                                                                                                                                                                                ^^^^^^^^^^^^^^^^^
[ERROR] StandardConstants cannot be resolved to a variable
[ERROR] /rpm/BUILD/dbeaver-6.0.2/plugins/org.jkiss.dbeaver.net.ssh.ui/src/org/jkiss/dbeaver/ui/net/ssh/SSHTunnelConfiguratorUI.java:[114] 
[ERROR]         localPortSpinner = UIUtils.createLabelSpinner(advancedGroup, SSHUIMessages.model_ssh_configurator_label_local_port, 0, StandardConstants.MIN_PORT_VALUE, StandardConstants.MAX_PORT_VALUE);
[ERROR]                                                                                                                                ^^^^^^^^^^^^^^^^^
[ERROR] StandardConstants cannot be resolved to a variable
[ERROR] /rpm/BUILD/dbeaver-6.0.2/plugins/org.jkiss.dbeaver.net.ssh.ui/src/org/jkiss/dbeaver/ui/net/ssh/SSHTunnelConfiguratorUI.java:[114] 
[ERROR]         localPortSpinner = UIUtils.createLabelSpinner(advancedGroup, SSHUIMessages.model_ssh_configurator_label_local_port, 0, StandardConstants.MIN_PORT_VALUE, StandardConstants.MAX_PORT_VALUE);
[ERROR]

**Comment by serge-rider** [comment]
This was fixed a week ago or so. 
You should build from devel or master branch.

**Comment by copart** [comment]
okay, I built with 6.0.1 successfully, will wait for 6.0.3. Thank you!
