### ISSUE TITLE
Hard to use ER Diagram for large number of tables.

### ISSUE THREAD

**Issue by traderhut** [dbeaver/dbeaver#5718]
#### System information: 
- Operating system (distribution) and version OS-X, Reasonably latest
- DBeaver version 6.0.2
- Java version Heck if I know
- Additional extensions . None, just did a clean install

#### Connection specification:
- Database name and version MS Sql Server, 2017 and 2012
- Driver name Jake, although some times Bill fills in
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No, but I use a VPN 

#### Describe the problem you're observing:
When I select a Schema it generates the ER Diagram.  It doesn't do a great job of placing the tables . (We have about 100 tables, so fair enough, I can understand you putting a table at the top that has only one Foreign Key and it is to a table at the bottom (3 pages below) (on a 4K monitor, so a Loong way down)... Ah, actually, no, I can't see doing that.  It seems it would group them... 

It creates links that have, what I can only guess are routing dots to help it route around other tables - no way to delete the dang things when you move the tables, so you would have to move them over by the tables... they shouldn't exist as perm items, but be auto-created as needed to route the links, and go away when either table is moved....

But, the main issue is:  I move the tables all around just the way I like them (this takes a LOT of work with this many tables...)

Exit app (or Good grief, have the connection just drop - it won't auto reconnect!!), Or close the diagram, or just hit the 'refresh' button (which should reload the Diagram's data, compare it to what it had and apply differences ONLY)...

And OMG! POOF!! Back to square one.   I like this app, but I can't keep my connection up forever.. (and OMG I just realized I had to drop my VPN connection to report this.. Arrrrgh.. I just lost everything I had setup *again*)

#### Steps to reproduce, if exist:
Use your app for the first time, point it at a database... and decide it can't be used for this.

Unless, you are looking at a tiny sample database, not one with hundreds of tables you actually NEED a tool like this for..

**Comment by uslss** [comment]
Already implemented. For now ERD state could be saved on ERD reoping using Keep layout button
![image](https://github.com/dbeaver/dbeaver/assets/31996417/23487711-5820-45ce-9953-5335ca5b6b9e)
