### ISSUE TITLE
Format SQL

### ISSUE THREAD

**Issue by aicochow** [dbeaver/dbeaver#5719]
#### System information: 
- Operating system (distribution) and version
`macOS 10.14.4 (18E226)`
- DBeaver version
`6.0.2`
- Java version 
`1.8.0_121`
- Additional extensions
` No`

#### Connection specification:
- Database name and version
`PostgreSQL 11`
- Driver name
`PostgreSQL` `42.2.5`
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
`No`

#### Describe the problem you're observing:
When I run `Format SQL`,get the wrong result

**befor**
```sql
SELECT column_1,
       column_2
FROM table;
```
**after** 
```sql
SELECT
	column_1,;
	
	column_2;
FROM
TABLE;
```

**Comment by mcarpenterjr** [comment]
This is also happening with MySQL on Kubuntu 18.10

Really frustrating to work with.

**Comment by knoxyz** [comment]
I have the same issue since 6.0.2 and Kubuntu 18.10.
Each line-break becomes a semicolon.
The kind of database doesn't matter.

**Comment by RimantasGalvonas** [comment]
This should really be the default setting.

**Comment by serge-rider** [comment]
Agreed

**Comment by uslss** [comment]
verified
