### ISSUE TITLE
Reset UI settings action in main menu

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#5722]
Problems with corrupted UI happen quite often. 
There is a way to reset settings (https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings) but we need some simpler way to do this.

Main menu item looks like good enough solution for that.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/56079989-37c44300-5e04-11e9-88e3-464488e93dac.png)

**Comment by uslss** [comment]
verified
