### ISSUE TITLE
DBeaver fails to start

### ISSUE THREAD

**Issue by AnharMiah** [dbeaver/dbeaver#5723]
#### System information: 
- Operating system (distribution) and version:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```
Using Gnome Shell DE

- DBeaver version `6.0.2`
- Java version 
```
$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

```
- Additional extensions `n/a`

#### Describe the problem you're observing:

On starting up, after the splash screen nothing happens :(

#### Steps to reproduce, if exist:

With the above combination of versions, `dbeaver` just fails to start.

# Work around, temporary fix

If we view the logs by starting `dbeaver` via the shell

```
$ dbeaver
```

we can see exactly where it blows up:

```
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
```

Seems we can disable this "Accessibility" thingy which can be found here _(depending on your version)_:

```
/etc/java-8-openjdk/accessibility.properties
```
just comment out so that it reads:

```
# assistive_technologies=org.GNOME.Accessibility.AtkWrapper
```

**Comment by serge-rider** [comment]
Here is some extra info: https://askubuntu.com/questions/695560/assistive-technology-not-found-awterror

Looks like headless jre is the reason (or at least one of)

**Comment by AnharMiah** [comment]
> Looks like headless jre is the reason (or at least one of)

Hi @serge-rider I would like to agree, however I've been using dbeaver for ages and only after a recent update did this occur. The only other difference apart from an update is that normally I have an external monitor attached, when this start failure occurred I didn't have a monitor attached that day.

**Comment by tchibatron** [comment]
This is related to dashboards. If you open dashboard and close DBeaver, it will not start untill you change accessibility.properties.

**Comment by serge-rider** [comment]
We can't fix this right now because it is a conflict of Java AWT and JfreeChart.
We'll fix this once we'll start to ship JRE along with DBeaver (after 6.1 release).

**Comment by ryguy40** [comment]
I just downloaded 6.1 and when I tried to open DBeaver, it had this issue. Also, now I am unable to open any previous versions I had (I used the .zip archive, not the installer).

I am thus completely unable to run DBeaver. Also, the previous fix didn't work for me because I looked through all of the JRE/JDK folders I have and I was unable to find any application.properties that have been changed recently and that have the option to comment out the line that was previously mentioned.

**Comment by ryguy40** [comment]
Update: I did the workspace reset described in this issue: https://github.com/dbeaver/dbeaver/issues/5381. And now I am able to open it again.

**Comment by serge-rider** [comment]
In 6.1.1 we have migrated to JDK11 which doesn't have such issues. However we ship it only for Windows and Mac (in installers) while on Linux we keep using pre-intalled JRE.

Not sure what we can do with this now. Add jre in every Linux deb/rpm/zip distributions doesn't look like a good idea..

**Comment by AnharMiah** [comment]
> Not sure what we can do with this now. Add jre in every Linux deb/rpm/zip distributions doesn't look like a good idea..

Would this perhaps be a good time to look into `snaps` and `flatpak` ?

* https://snapcraft.io/
* https://flatpak.org/

**Comment by serge-rider** [comment]
The same issue in #6811. I'll add fix there.
