### ISSUE TITLE
Ignite generates SQL Error

### ISSUE THREAD

**Issue by weiki516** [dbeaver/dbeaver#5726]
Dbeaver 6.0.2
Ignite 2.7.0
Issue:
When use "Generate SQL -> SELECT" in a table  the SQL generated is incorrect.

Example:
SELECT CONTROLID, LASTTIME, "RESULT", RESULTID, VARID FROM persons.VARWARNLIST;

Error ：
SQL 错误 [1001] [42000]: Failed to parse query. Schema "PERSONS" not found; SQL statement:¶SELECT CONTROLID, LASTTIME, "RESULT", RESULTID, VARID FROM persons.VARWARNLIST [90079-197]

Change this ，Add "" To the  "persons" and "VARWARNLIST "  can be  Correct execution：
SELECT CONTROLID, LASTTIME, "RESULT", RESULTID, VARID FROM “persons"."VARWARNLIST"

**Comment by serge-rider** [comment]
Could you check the fix in Early Access version (https://dbeaver.io/files/ea)

**Comment by uslss** [comment]
closed without tests
