### ISSUE TITLE
SQL Editor button (F3) does nothing

### ISSUE THREAD

**Issue by velteyn** [dbeaver/dbeaver#5727]
#### System information: 
- Operating system WINDOWS 10 
- DBeaver version 6.0.2
- Java version internal ?
- Additional extensions none

#### Connection specification:
- Database DB2 AS/400

#### Describe the problem you're observing:
After the latest upgrade DBeaver 6.0.2 when I press the SQL Edito icon (or I press F3) nothing happens. Before the update there was a nice window with all the related sql files I opened before for that particular connection.
Now nothing happens !! :(

**Comment by serge-rider** [comment]
This may be some kind of configuration corruptions, you can reset UI settings to fix this (https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings)
Also there is shortcut <kbd>CTRL+[</kbd> - it does the same on platforms (while <kbd>F3</kbd> is Windows-only)

**Comment by velteyn** [comment]
Hello,
I did exactly as you said: the file have been recreated after deletion, but  the problem persists....
Pressing the button nothing happens... :( 
Any other suggestion ?

**Comment by serge-rider** [comment]
Please attach error/debug logs (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by velteyn** [comment]
Yes. I continue to install the latest version, but the button continues to
do nothing...

Il mar 15 ott 2019, 17:27 uslss <notifications@github.com> ha scritto:

**Comment by uslss** [comment]
So could you attach error/debug logs (https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by velteyn** [comment]
[logz.log](https://github.com/dbeaver/dbeaver/files/3740145/logz.log)


[metadata.log](https://github.com/dbeaver/dbeaver/files/3740147/metadata.log)

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3740148/dbeaver-debug.log)

**Comment by velteyn** [comment]
OK !! I got it !! I noticed that the window is width 0 height 200
So it open it but it is not visible.  Can you check for default window width ?

**Comment by serge-rider** [comment]
I believe this bug was fixed around version 6.1 (we check panel width/height)

**Comment by serge-rider** [comment]
@velteyn So, once you resize script panel manually - does it break again after some time?

**Comment by velteyn** [comment]
Mmmm , after I manually resized it , it remains at the given width/height so the problem is solved for me.. I don't know how it was put on 0 width at the beginning.. It this happens again I'll report.
