### ISSUE TITLE
GIS: support different projections

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#5729]
Part of #4222
We need to support different projections (SRIDs)  besides 4326.

Examples: fmedata database tables most of which are in SRDID=26910 (North American Datum, Transverse_Mercator) which is not compatible with standard GPS coordinates.

Acceptance criteria: ability to see maps with SRIDs different that 4326 (default)

**Comment by uslss** [comment]
In certain cases CRS is changed but in drop-down list default crs is still shown. Also there is incorrect behavior when changing default CRS. More info in attached gif.
![gis](https://user-images.githubusercontent.com/31996417/56850818-53554080-6910-11e9-88f7-e9e0a8c000b7.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by baffioso** [comment]
I'm still having trouble getting SRID transformations working in 6.0.4

If do this:
```sql
select ST_SetSRID(st_makepoint(12.5320, 55.6782), 4326);
```
I get following, which is correct: 
![image](https://user-images.githubusercontent.com/7534153/57212644-ac923380-6fe4-11e9-8c9d-4fc164592eba.png)


When I transform the geometry:
```sql
select st_transform(ST_SetSRID(st_makepoint(12.5320, 55.6782), 4326), 25832);
```
I get:
![image](https://user-images.githubusercontent.com/7534153/57212595-7eacef00-6fe4-11e9-8984-48a4a690db78.png)

Thanks for this beautiful spatial feature. Really enjoy using DBeaver!!

**Comment by glw** [comment]
Im getting a blank screen when using a state plane coordinate system. And 4326, 3857 dont seem to be compatible with my data via dbeaver. Is it supposed to do the transformation in the background? I can not find any documentation on this feature, maybe because it is recent.

**Comment by beedawg1985** [comment]
I'm seeing this behaviour on Community Version 7.0.0.202003021717 
I have a table of spatial data using ESPG 27700, the geometry is visible but no backdrop mapping is visible unless I change the ESPG value to 4326 at which point my geometry displays incorrectly.

**Comment by dominijk** [comment]
I also get this on edition `Version 22.3.4.202302060909` 

> I'm seeing this behaviour on Community Version 7.0.0.202003021717 I have a table of spatial data using ESPG 27700, the geometry is visible but no backdrop mapping is visible unless I change the ESPG value to 4326 at which point my geometry displays incorrectly.
