### ISSUE TITLE
Minor Issue: Postgres Keyword WHILE Not Properly Styled

### ISSUE THREAD

**Issue by jsmith0103** [dbeaver/dbeaver#5732]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.0.2.201904071344
- Java version: 1.8.0_201.b09
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 11
- Driver name: 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
WHILE keyword is not properly styled - appears as plain text
![image](https://user-images.githubusercontent.com/21117396/56154595-8564bb00-5f7e-11e9-9c54-df178accaf9e.png)

#### Steps to reproduce, if exist:
Type WHILE while connected to PostgreSQL 11 database

**Comment by uslss** [comment]
verified
