### ISSUE TITLE
Escape character issue during Export Query Result - SQL Server

### ISSUE THREAD

**Issue by JothimaniS** [dbeaver/dbeaver#5734]
Hi,
 
I export the data from 'Export from query' as csv file. 
Instead of generating this 23|**'Pixon O''Kelly'**|370.29
I am getting data like this 23|**Pixon O'Kelly**|370.29

Below is the settings in export wizard. I tried various settings in Character escape, like single quote, \' and 2 single quote.
![image](https://user-images.githubusercontent.com/49653150/56168417-00829d00-5f90-11e9-8efd-68305418606a.png)

 Please find the other information below.

#### System information: 
- Operating system (distribution) and version - Windows 10
- DBeaver version - 6.0.2
- Java version - 1.8

#### Connection specification:
- Database name and version - SQL Server
- Driver name - Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - No

Thanks,
Jothi

**Comment by uslss** [comment]
cannot reproduce it now.
if issue is still actual for you - feel free to reopen the ticket
