### ISSUE TITLE
[Bug] can't change port

### ISSUE THREAD

**Issue by kevart** [dbeaver/dbeaver#5735]
#### System information: 
- macOS 10.14.4
- dbeaver 6.0.2
- java 12 2019-03-19 
- Additional extensions: no

#### Connection specification:
- Microsoft SQL Server
- Driver: MS SQL Server / SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Changing the port seems to have no effect.

#### Steps to reproduce, if exist:
Change the port number in the UI, connection fails with:

The TCP/IP connection to the host ***.us-west-2.rds.amazonaws.com, port **1433** has failed. Error: "connect timed out. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".

![Screen Shot 2019-04-16 at 2 18 35 pm](https://user-images.githubusercontent.com/5118530/56181842-a3035480-6052-11e9-85f9-2683e1dfecf6.png)

**Comment by serge-rider** [comment]
Not reproducible on windows or Linux.
Will check in Mac a bit later

**Comment by serge-rider** [comment]
Not reproducible on Mac as well

**Comment by e-volusian** [comment]
I had this same error on DBeaver version 6.2.5 Release date Nov 18 2019 on Windows while trying to connect to MS SQL Server. The problem seemed to go away after resetting the default port in the driver settings to the original value of 1433.

**Comment by danall59** [comment]
I have the some problem using DBeaver 22.3.2 on Windows 10 with database Postgresql on port 5431 (example: jdbc:postgresql://94.1.1.1:5431/postgres ) 
and with database FirebirdSQL on port 3051 (example: jdbc:firebirdsql://94.1.1.1:3051/MYDBFB ).
For Postgresql default port is 5432 and for FirebirdSql default port is 3050: with these port DBeaver operate correctly.
