### ISSUE TITLE
How do I run an sql script and export the result by running from command line?

### ISSUE THREAD

**Issue by kishvanchee** [dbeaver/dbeaver#5737]
I am trying to run a set of sql scripts for automation and I want to do something like this

`C:\> dBeaver.exe -con "name=...|other connection parameters" -f myFileToRun.sql -o outputFileToWhereMyResultShouldBeExported.txt`

I found [this issue](https://github.com/dbeaver/dbeaver/issues/2373#issue-266828389) may be related to what I am asking for.

I looked through the [Command line wiki](https://github.com/dbeaver/dbeaver/wiki/Command-Line) but I was not able to find a particular example of what I am asking for.

Is this currently possible? Did I miss any documentation?

**Comment by uslss** [comment]
duplicates #2095
