### ISSUE TITLE
Is there a way to sort result set by data values across row instead of across column? 

### ISSUE THREAD

**Issue by Asurion-AM** [dbeaver/dbeaver#5739]
Is there a way to sort result set by data values across row instead of across column? 

e.g. if I'm doing counts of data values 
   select count( case when col1 is null then 1 end) as col1count , 
             count( case when col2 is null then 1 end) as col2count 
  from tablexyz
 ; 

sample resultset 
col1count      col2count      
3                   20 
           
sample resultset in Record View mode:
columname   value 
col1count      3 
col2count      20 

I need to sort result set by value desc so col2count is shown first. 
needed resultset 
columname   value 
col2count      20 
col1count      3 

How can this be done?

**Comment by uslss** [comment]
Unfortunately, this cannot be done
