### ISSUE TITLE
Export from script to database: Auto assing table

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#5744]
In https://github.com/dbeaver/dbeaver/issues/2855 you added export from script. When I use this feature to export to another database, however, column automapping does not work even if the query is as simple as `select * from table`, because dbeaver tries to map to destination table "select * from table" instead of just "table" (see screenshot below)

![immagine](https://user-images.githubusercontent.com/2157006/56299271-fd281680-6133-11e9-9144-5cd1e141d198.png)

The information should be available, since if I export the same script to csv, and use ${table.name}, dbeaver is capable to name the output file after the exported table (TABLE.timestamp.csv, without "SELECT * FROM").

If relevant, my database is oracle, and I'm fully qualifying tables to avoid issues in metadata retrieval (e.g. schema.table)

**Comment by kseniiaguzeeva** [comment]
1. When you export from database to database you can create a custom name for a new table (double click on target field or press New btn).
![dbeaver_ESQKnwkmoc](https://user-images.githubusercontent.com/51405061/89287190-2851b480-d65c-11ea-9b14-12d7eebefd4a.png)

2. The different ticket exists for export to CSV with a custom name https://github.com/dbeaver/dbeaver/issues/8033
