### ISSUE TITLE
SQL reserved keywords wrapping

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#5749]
Hi there!
Seems an old issue, but i could not find the solution (Bdeaver 6.0.2).
Where do i disable sql keywords wrapping with ` and/or " characters?

It is really, really annoying, especially when moving data around in multiple DBs...

Thanks for your time! ;)

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer. Please try set External formatter in Preferences>DBeaver>Editors>SQL Editor>SQL Formatting.
![dbeaver_7DQLyPPvgw](https://user-images.githubusercontent.com/51405061/80077169-cd38fd80-8555-11ea-90f2-b23c8baa4179.png)

Please reopen the ticket or create a new one, if you have additional questions.
