### ISSUE TITLE
Text Field Truncated

### ISSUE THREAD

**Issue by pdugas** [dbeaver/dbeaver#5751]
#### System information: 
- Operating system (distribution) and version: Fedora release 29 (Twenty Nine)
- DBeaver version: 5.3.2
- Java version: openjdk version "1.8.0_201"
- Additional extensions: none

#### Connection specification:
- Database name and version: mariadb-server-10.3.12-10.fc29.x86_64
- Driver name: MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
The value of a TEXT field is being truncated when copying it or viewing it in the Value panel. See the screenshot below.  The "health" TEXT field contains a serialized PHP object (via Doctrine) and if I widen the grid column, I see more of the actual value. However, if I copy the value to the clipboard or open the Value panel, the value us truncated as shown.

![image](https://user-images.githubusercontent.com/710928/56363389-1e334a80-61ba-11e9-9ed4-3c31c56b28d2.png)

**Comment by serge-rider** [comment]
Could you post the actual value as a text? Maybe something breaks in particular characters sequence parsing.

**Comment by uslss** [comment]
hi @pdugas is issue still actual for you?

**Comment by pdugas** [comment]
I can't say whether the issue persists as I'm no longer on the project that used that schema. I do not have an example to test with easily.
