### ISSUE TITLE
Wrong indentation in SQL editor - Version 6.0.2

### ISSUE THREAD

**Issue by carlosspohr** [dbeaver/dbeaver#5753]
Hi there,

After upgrade from ```6.0.1``` to ```6.0.2```, I found this strange indentation on new lines while typing select queries. To image below shows how it's being formatted:

![image](https://user-images.githubusercontent.com/637767/56359360-b7ad2d00-61b7-11e9-8f98-1cebad999718.png)

Or as plain text with ``\n`` and ``\t``:
```
select
	a.*
	from
		tb_foo a
		where
			a.bla > 0
			and
				a.foo > 1
				group by
					a.faa
					order by
						a.faa;
```
Looking for some configuration, I didn't find anyone, and I also don't have any customization on default formatter.

This occurs on both Windows and Linux, just in ``6.0.2`` version.

PS: I don't know if [this issue](https://github.com/dbeaver/dbeaver/issues/5683) (#5683) contains this fix because it's closed, but, in current version (6.0.2) I get this error.

**Comment by uslss** [comment]
Thanks for the bug report. The issue seems to be already fixed. 
You can test the fix in Early Access version (https://dbeaver.io/files/ea)

**Comment by carlosspohr** [comment]
Hi @uslss,

I upgraded to ```6.0.3 EA```, some of inconsistencies are fixed, but there are some new, as shown below:
![image](https://user-images.githubusercontent.com/637767/56399909-4dcc6c00-6227-11e9-92df-530653ca8fef.png)

Always after ```and``` instructions and hit enter to new line, the cursor goes to begin of new line, and, when I inside some sub query, the formatter also applies the same formatting position as parent query (lines 11 up to 17).

Quick resume: the bug still occurs.

**Comment by carlosspohr** [comment]
Hi @uslss,

After upgrade early ```6.0.3``` version to new ```6.0.3```, the situation that I described above continues.

**Comment by uslss** [comment]
Reopened. Wrong indentation
![image](https://user-images.githubusercontent.com/31996417/56850740-1ccaf600-690f-11e9-9a3e-787791fba205.png)

**Comment by serge-rider** [comment]
I'll disable keyword-based indent/unindent for now. We need strict criteria for it otherwise it becomes a mess.

**Comment by uslss** [comment]
verified

**Comment by carlosspohr** [comment]
> I'll disable keyword-based indent/unindent for now. We need strict criteria for it otherwise it becomes a mess.

Agreed. In further releases, this kind of modifications cloud be enabled by some configuration, where, it's disabled as default.

**Comment by carlosspohr** [comment]
Hi @serge-rider, @uslss,

I just upgraded to ``6.0.4`` final release, and indentation is OK.  You can closed this issue.

Thanks guys!
