### ISSUE TITLE
Authentication with Active Directory MSI throws Exception

### ISSUE THREAD

**Issue by dam1960** [dbeaver/dbeaver#5754]
#### System information: 
- Xubuntu 18.04
- DBeaver 6.0.2
- Java 1.8.0_44 

#### Connection specification:
- Azure SQL Server 
- Azure SQL Server 7.2.2.jre8
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
Authentication with Active Directory MSI throws Exception

#### Steps to reproduce, if exist:
Create a new connection using Active Directory MSI authentication and hit Test Connection

#### Include any warning/errors/backtraces from the logs
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3096290/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Can't reproduce.
Notes:
- You can use MSI auth to connect to a SQL Database from inside an Azure Resource, e.g. an Azure Virtual Machine, App Service or Function App (https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-2017)
- User name is used as Client ID of the Managed Service Identity (MSI) to be used for acquiring accessToken when establishing a connection with ActiveDirectoryMSI authentication mode.
- Password value is not used

Are you sure your environment is valid and all parameters are correct?

**Comment by dam1960** [comment]
I can connect using "Azure Active Directory - Universal with MFA support" through Azure Data Studio.  I would much rather use DBeaver because it is a much better product.  I believe my environment is correct since I can connect with Azure Data Studio.

**Comment by dam1960** [comment]
After more research, it appears that MS SQLServer JDBC driver does **not** support Active Directory authentication with MFA.  Although it is supported in SSMS.

Do you have any thoughts on this?

**Comment by serge-rider** [comment]
We'll try to find something out in Microsoft jdbc issue tracker..

**Comment by edwardaskew** [comment]
Looks like version 9.1.1 of the jdbc driver should now support interactive authentication: microsoft/mssql-jdbc#1464

What's needed for dbeaver support for it?

**Comment by GuillaumeGuerra** [comment]
We're stuck for now in my company with Azure Data Studio to access our Azure Sql instances protected by MFA.
You have no idea how eager I am to move back to DBeaver, given the features gap between the two tools.

Please have a look at what Microsoft pushed within the jdbc driver, hopefully it'll be quick to use it in DBeaver 🙏 

Thanks !!

**Comment by serge-rider** [comment]
We'll upgrade default driver version to 9.1.1 in dbeaver 7.3.4. 
MFA (Interactive) authentication will be added to the connection confgiguration.

However 9.1 driver is still in preview. And there is no official documentation about interactive authentication. Keep tracking.

**Comment by GuillaumeGuerra** [comment]
hi @serge-rider 

Was this feature integrated within 7.3.5 version ?
I can't find the `Active Directory - Interactive` mode in the connection combo ...

Thanks a lot for the dev !

**Comment by vincent-smit** [comment]
@GuillaumeGuerra I don't think so. I am actually also waiting for this feature!

**Comment by GuillaumeGuerra** [comment]
hi @serge-rider,

I was hoping to see this feature delivered as part of one of recent DBeaver releases.
Yet, I can see it's getting postponed everytime.

Do you know roughly when can we expect it to be available ?

Again, thanks a lot for the development, it'll be a great benefit for us 👍

**Comment by serge-rider** [comment]
SQL Server driver 9.2 was published, official documentation was updated (https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15)

Eventually MFA authentication works (thru web browser).
You can test it in the Early Access version.

Note: you will need to update driver libraries version to 9.2+ manually in the driver settings dialog (unless it will update automatically).

**Comment by GuillaumeGuerra** [comment]
Hi @serge-rider ,

Thanks a lot for the update ! 🙏 

I gave a round of testing with the EA version, updating sqlserver jdbc driver to 9.2.1.jre8
When I try to connect using MFA, it gives me a `com.sun.net.httpserver.HttpHandler` exception, with not much additional information.
I don't see any browser opening.

I'll just wait for next stable version of DBeaver to be released to try again 🤞 

Thanks again !

**Comment by serge-rider** [comment]
@GuillaumeGuerra please make sure you are using Azure driver (not classic SQL Server driver).
Also check that all Maven artifacts were downloaded:
![image](https://user-images.githubusercontent.com/6398845/113876494-78bb7c00-97c0-11eb-8ece-0d80878863d6.png)

**Comment by GuillaumeGuerra** [comment]
Hi @serge-rider ,

Thanks a lot for the support.

I'm using this setup, which looks fairly similar to yours I think

![image](https://user-images.githubusercontent.com/9720053/113891269-35afd780-97c5-11eb-9cef-54e9b5c92381.png)

![image](https://user-images.githubusercontent.com/9720053/113891226-27fa5200-97c5-11eb-9949-4a6b6dd82dfb.png)

I gave a try with **9.2.0.jre8**, with same error, so I sticked to later version.

I'm no expert with DBeaver setup, but I think I do use Azure driver (the settings popup title tends to confirm).
Regarding the maven artifacts download, I don't know how to check that ...
I did try to force download, no change
![image](https://user-images.githubusercontent.com/9720053/113891713-a1924000-97c5-11eb-9e51-681978e4321c.png)

If there's nothing obvious you can think of, I suppose I can wait for the release of the next stable version of DBeaver and see if it gets solved on its own or not 🤞 

Thanks again

**Comment by serge-rider** [comment]
Forgot to mention that you must switch auth mode to MFA:
![image](https://user-images.githubusercontent.com/6398845/113906038-7a933880-97dc-11eb-9959-41736e244cb7.png)

**Comment by GuillaumeGuerra** [comment]
Hi,

Yes that's the very first setting I changed.
I confirmed that I was using the early access thanks to this new value in the combo 😊

**Comment by uslss** [comment]
Error still appears
![image](https://user-images.githubusercontent.com/31996417/114168749-58fb9380-9939-11eb-99db-3c0a831bc66a.png)

**Comment by serge-rider** [comment]
@uslss Please post screen of your driver libraries

**Comment by uslss** [comment]
verified

**Comment by GuillaumeGuerra** [comment]
Hi @uslss 

I'm curious, did you manage to make it work ? 
it seems you had the exact same error than me.

I downloaded the latest EA, to confirm, and it still happens.

Thanks a lot

**Comment by serge-rider** [comment]
@GuillaumeGuerra you can test it in the new EA version (now it contains the fix)

**Comment by GuillaumeGuerra** [comment]
@serge-rider @uslss I confirm, it works ❤️ 

Thanks soo much !
I'm eagerly waiting for the next stable release to show up 👍

**Comment by matt-jay** [comment]
I also have an issue in v21.3.2 (CE): I can configure the connection to use MFA and a browser window opens and asks me to provide credentials. The browser then redirects to localhost:xxxxx (xxxxx = varying port numbers on each try), and the process is stuck there. DBeaver does not appear to pick up the response.

Has anyone else observed this behavior? This is on MacOS 11.6.2.
The drivers appear to be those suggested by previous posters:
![image](https://user-images.githubusercontent.com/1327393/149120634-bff7fc9d-d0cd-4415-bc4a-b1368500b148.png)

**Comment by FinmasFelix** [comment]
@matt-jay I have the same issue and sadly no solution in DBeaver 22.2.5

**Comment by vittorio-giatti** [comment]
Does anyone know whether is has been fixed? Is there a way to overcome the issue? I am trying to login on a MS Fabric Lakehouse using MFA.

**Comment by vittorio-giatti** [comment]
> [@matt-jay](https://github.com/matt-jay) I have the same issue and sadly no solution in DBeaver 22.2.5
Same in 24.3.4
