### ISSUE TITLE
How to view queries made by DBeaver to show columns, indexes etc.

### ISSUE THREAD

**Issue by pyudroi** [dbeaver/dbeaver#5757]
First of, thank you for putting together Dbeaver. It is an amazing tool.
Im new to java and have managed to compile-and-build DBeaver on eclipse.

I want to understand the flow in code, on how and which queries are made by Dbeaver on clicking specific UI elements and how the results are shown in UI. This is when user double clicks on a table, DBeaver shows columns and foreign keys. I am using postgres database on macos.

Any pointers is much appreciated.

**Comment by p91paul** [comment]
There's query browser for that! you can enable it in preferences, checking which queries it should record (I believe you want them all). After that, you should display the query browser view, I believe it's in the Tools menu.  There you'll find each and every query ran by DBeaver.

**Comment by pyudroi** [comment]
Thank you @p91paul
