### ISSUE TITLE
Column Editor autocomplete and change detection bugs (PostgreSQL)

### ISSUE THREAD

**Issue by rohanrhu** [dbeaver/dbeaver#5758]
#### System information: 
- Windows 10
-  6.0.2.201904071344

#### Connection specification:
- PostgreSQL 10
- JDBC

#### Describe the problem you're observing:
Column Editor has two bugs. Type selectbox autocompletion and change detection are not working true.

#### Steps to reproduce, if exist:
- Double click a column
- Type "js" to type input and enter (type input value will be "jsjson")
- and DBeaver will not detect changes and save button will be disabled. (If you change column name, it detects changes and you can save.)

**Comment by RoroTiti** [comment]
I confirm the issue, with MySQL as well.

Here is a GIF demonstrating the problem :

![](https://i.imgur.com/73odnfC.gifv)

**Comment by serge-rider** [comment]
Fixed

**Comment by RoroTiti** [comment]
Nice to hear 👍 !!

**Comment by kseniiaguzeeva** [comment]
Partially fixed. This issue still exists:

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
