### ISSUE TITLE
Request for "Delete this Script" in keys preferences

### ISSUE THREAD

**Issue by r-richmond** [dbeaver/dbeaver#5759]
I wanted to bind `Delete this Script` to a shortcut but was unable to find it in preferences. Can you add it to preferences?

![Screen Shot 2019-04-05 at 1 41 06 PM](https://user-images.githubusercontent.com/9246654/56445293-6d0fdb80-62b1-11e9-8b1e-7e1ca5cd1952.png)

![Screen Shot 2019-04-19 at 2 44 08 PM](https://user-images.githubusercontent.com/9246654/56445318-9cbee380-62b1-11e9-8d6a-186402431761.png)

#### System information: 
- Operating system OSX 10.14.4
- DBeaver version 6.0.2
- Java version` openjdk 12 2019-03-19`
- Additional extensions None

**Comment by serge-rider** [comment]
Done

**Comment by uslss** [comment]
verified
