### ISSUE TITLE
FR/QQ: Dark Theme - Column Descriptions default to dark foreground color

### ISSUE THREAD

**Issue by r-richmond** [dbeaver/dbeaver#5760]
Currently the default color the column description foreground color is black which is hard to see in dark mode.

Can you add (or point out) this preference in Colors & Fonts section? (Bonus points for changing the default for dark mode).

![dark_theme_column_description](https://user-images.githubusercontent.com/9246654/56445535-94b37380-62b2-11e9-88e6-e603f699c407.png)

![image](https://user-images.githubusercontent.com/9246654/56445532-91b88300-62b2-11e9-9b73-87f2cb3d6167.png)

note: apologies if I've missed the setting or created a duplicate issue I spent ~5 minutes or so looking without success so here we are

#### System information: 
- Operating system (distribution) and version OX 10.14.4
- DBeaver version 6.0.2
- Java version `openjdk 12 2019-03-19`
- Additional extensions None

#### Connection specification: N/A

**Comment by EnziinSystem** [comment]
When I use the dark theme on Ubuntu, some columns in the Properties tab was hidden.

![dark](https://user-images.githubusercontent.com/25495466/63156892-0491fa80-c016-11e9-8d89-e500de5c7f40.jpg)

**Comment by uslss** [comment]
seems that issue is fixed
![image](https://user-images.githubusercontent.com/31996417/86521021-ea425480-be53-11ea-9e37-1bab14897892.png)

**Comment by r-richmond** [comment]
Yep can confirm this is fixed now ty!
