### ISSUE TITLE
Key binding for switching between data editor and results panel (value viewer)?

### ISSUE THREAD

**Issue by ar-jan** [dbeaver/dbeaver#5765]
I think a key binding for switching between the data grid and the results panel (value viewer) and back again would be very handy. It would allow fast data entry/modification.

**Comment by serge-rider** [comment]
Agreed, that would be very useful.

**Comment by serge-rider** [comment]
It is <kbd>CTRL+SHIFT+7</kbd> by default.

**Comment by uslss** [comment]
verified
