### ISSUE TITLE
Ctrl+9 and Ctrl+0 not working after upgrade to 6.0.3

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#5767]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.0.3

#### Describe the problem you're observing:
In 6.0.2 you could switch database with Ctrl+9 and also tables with Ctrl+0. This seems to not work in version 6.0.3 and I have tested with both versions now.

#### Steps to reproduce, if exist:
Just try to switch the connection or table using keyboard shortcuts.

**Comment by serge-rider** [comment]
It was broken during connection/schema selectors redesign.
thanks for the bug report

**Comment by nmat** [comment]
thank you for verifying. Its one of those items I use on daily basis so it was kind of easy to find for me.

**Comment by leslies77** [comment]
it is important for me. ^^ 

It is the Hotkey I use most and usefully.

**Comment by nmat** [comment]
@leslies77 there are 2 alternatives for you if you feel that you can't wait for the fix.

1. Use 6.0.2
2. Use a prerelease of dbeaver for 6.0.4

If its a production environment I would probably stick with 6.0.2 until 6.0.4 is released.

**Comment by uslss** [comment]
verified
