### ISSUE TITLE
oracle error all_tables

### ISSUE THREAD

**Issue by luizplago** [dbeaver/dbeaver#5768]
In version 6.03 now I can use here in the company because we do not have the user "sys" as creator of the views (all_tables for example, [#5065](https://github.com/dbeaver/dbeaver/issues/5065)). But I believe that something is stuck because even unchecking the options "Always use DBA_ * views" still have an error when searching the tables.

![image](https://user-images.githubusercontent.com/1467093/56501221-5604ff80-64e4-11e9-8a3d-bb3fdd49c2d1.png)

![image](https://user-images.githubusercontent.com/1467093/56501196-3f5ea880-64e4-11e9-9193-1b45ca6e2d4b.png)

**Comment by serge-rider** [comment]
The problem is no in DBA or SYS view prefix but in missing of ALL_ALL_TABLES view (or alias).
We could try to use ALL_TABLE view for metadata reading (it doesn't provide info about unaccessible objects but this is fine in most cases).

**Comment by serge-rider** [comment]
I've added checking of ALL_ALL_TABLES view existence.
