### ISSUE TITLE
after update (Windows): error "dbeaver executable launcher was unable to locate its companion launcher jar"

### ISSUE THREAD

**Issue by georg-h** [dbeaver/dbeaver#5769]
#### System information: 
- Operating system (distribution) and version -> Win10 Pro (1809)
- DBeaver version 6.0.3
- Java version -> included in installer
#### Describe the problem you're observing:
after updating my current 5.3.5.201902181142 installation with the Windows 64 bit (installer + JRE) I get an error popup stating  "dbeaver executable launcher was unable to locate its companion launcher jar".
Same applies after uninstall/re-install 
#### Steps to reproduce, if exist:
download installer and use it.
#### Include any warning/errors/backtraces from the logs
--> there are no new logfiles written after the update 

kind regards
Georg

**Comment by georg-h** [comment]
![dbeaver_startup_error](https://user-images.githubusercontent.com/5622476/56509993-ca619200-6528-11e9-875b-41a41772a675.jpg)

**Comment by georg-h** [comment]
FYI: using the zip archive works as expected. Only the installed version doesn't work.

**Comment by serge-rider** [comment]
Most likely something went wrong during installation.
Could you send list of files in `plugins` directory?

**Comment by georg-h** [comment]
[dbbeaver_plugins.txt](https://github.com/dbeaver/dbeaver/files/3104499/dbbeaver_plugins.txt)
Hi serge-rider here is the list

**Comment by serge-rider** [comment]
Thank you.

Yes, as I thought, installation is corrupted. By some reason installer wasn't able to extract archive files.

Could you try to reinstall DBeaver. Expand "Details" panel during installation to see any errors which may occur during archive unpacking.

**Comment by georg-h** [comment]
the details are to fast to read them (but it doesn't seem to show errors, just regular output) and it doesn't stop at the end ...justs says it finished successfully.
running the installer from cmd doesn't give any return code. But I always get the same error afterwards

**Comment by uslss** [comment]
hi @georg-h , is issue still actual for you against recent (6.2.3) version?

**Comment by kiravi** [comment]
had to run the installer twice and then it runs a reinstall that clears this issue.

This happened on the 6.2.3 version.

Looks like uninstall previous version and install new version does not install jars correctly in the first pass.

**Comment by serge-rider** [comment]
This may happen if DBeaver was running during first installation process. You need to shutdown it before upgrade.

**Comment by georg-h** [comment]
hi @uslss now the installation using the installer works for me. thx :)

**Comment by macau23** [comment]
This will also occur if you keep your dbeaver.ini file from a previous release.

**Comment by huohuo** [comment]
It works for me after killing the running DBeaver process and do the reinstallation.

**Comment by SOL-hub** [comment]
재설치말고 다른방법 내놔

**Comment by Jake-Gillberg** [comment]
This just happened to me on a fresh, first install of 7.2.5. Force quitting dbeaver and re-running the installer fixed the issue.
