### ISSUE TITLE
postgres ref cursor not working

### ISSUE THREAD

**Issue by lastday1225** [dbeaver/dbeaver#5772]
#### System information: 
- windows 10
- dbeaver 6.0.3
- java 1.8.0_192

#### Connection specification:
- postgres 9.6
- postgresql or old
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When I test the ref cursor query below, the value is not returned properly.
For pgadmin4, normally work.

#### Steps to reproduce, if exist:
CREATE OR REPLACE FUNCTION getTestRefCursor(
    i_Mode character varying, -- Device, Log
) RETURNS SETOF refcursor AS
DECLARE
BEGIN
    v_RefCursor refcursor := 'v_RefCursor';
      open v_RefCursor for
            select
               f1
            from table1;
END;
$BODY$
  LANGUAGE plpgsql;
-->
  select getTestRefCursor('Device');
   FETCH ALL in "v_RefCursor";
 --> 
![test_dbeaver](https://user-images.githubusercontent.com/29847187/56549197-13632600-65bd-11e9-9432-1a2347f469ad.jpg)

**Comment by uslss** [comment]
cannot reproduce it for now.
If issue is still actual for you - feel free to reopen the ticket
