### ISSUE TITLE
GIS: better handle viewing limitations in terms of maximum number of records

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#5774]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.0.3
- Java version: 8, update 211
- Additional extensions: None

#### Connection specification:
- Database name and version: PostgreSQL 11.2, PostGIS 2.5.2 on Ubuntu 18.04.2 LTS running on VirtualBox 6.0.6
- Driver name: PostgreSQL Unicode(x64) for Windows
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:

I discovered this new GIS viewing option in DBeaver. While this is great to have, it should better handle the limitations in terms of numbers of records it can display. I don't expect DBeaver to be a full blown GIS handling millions of records at all, so simply displaying a warning message if the user attempts to show more records than DBeaver can handle, should be enough and OK for me.

I actually deliberately tried to break this functionality to test it, by loading 130k points in DBeaver's Data Grid, and then switch to the GIS viewing option. This failed (note: small datasets worked!) with the following message, that translates to "Message from webpage" in the title bar of the dialog, and "Stackoverflow at line 1" as the message:

![afbeelding](https://user-images.githubusercontent.com/7635726/56568547-879acb00-65b7-11e9-8b55-d5b9fca8312b.png)

#### Steps to reproduce, if exist:
See above.

**Comment by serge-rider** [comment]
This makes sense, thanks for testing

**Comment by serge-rider** [comment]
By default objects limit set to 10000. It is configurable in GIS config dialog:
![image](https://user-images.githubusercontent.com/6398845/56802844-c932ac80-6829-11e9-8759-5a9c3a4e3d95.png)

**Comment by uslss** [comment]
verified
