### ISSUE TITLE
New lines don't take indentation

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#5775]
**Steps to reproduce:**
* Write some indented code block inside parentheses, e.g.
```sql
with
some_nickname as (
	select some_col
	from some_table st
	join another_table at on st.id = at.st_id
	where
		at.some_cond is true
		and st.other_cond is false
	)
select * from some_nickname
```
* Try to insert a new line into the indented block between parentheses (e.g. focus the mouse after the end of the line `from some_table_st` and press enter).

**Expected behavior:** should insert line following the indentation of the line above, like in previous versions.

**Actual behavior:** inserts line without indentation.

**Setup:** DBeaver 6.0.3, running on windows 10.

**Comment by carlosspohr** [comment]
Hi @david-cortes,

This seems similar to this one [#5753](https://github.com/dbeaver/dbeaver/issues/5753).

**Comment by david-cortes** [comment]
> Hi @david-cortes,
> 
> This seems similar to this one [#5753](https://github.com/dbeaver/dbeaver/issues/5753).
> 
> Would you like to test it in EA version ?
> 
> https://dbeaver.io/files/ea/

Indeed, looks like it's the same issue, will close this as it's a duplicate.
