### ISSUE TITLE
"Format SQL" no longer in right-click menu of SQL editor?

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#5776]
#### System information: 
- Operating system (distribution) and version
- DBeaver version: 6.0.3
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Hi, 

I just noticed that the "Format SQL" right-click menu option in a SQL Editor seems to have disappeared in V6.0.3 of DBeaver?...

I am pretty sure it used to be there. I used it quite frequently. This may be a conscious decision to de-clutter the context menu, but I think this should be re-added if it was indeed removed, it is a much needed function. I know the option is still available as key combination and from the Edit menu, but having it in the right-click context menu was more intuitive.

![afbeelding](https://user-images.githubusercontent.com/7635726/56594684-913f2580-65ed-11e9-92aa-42e1624ddacd.png)

**Comment by serge-rider** [comment]
It is a bug in the last version. It will be fixed in the next version.
Thanks for the bug report.

**Comment by uslss** [comment]
verified
