### ISSUE TITLE
Azure SQL: support older versions

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#5777]
Older versions of Azure SQL may fail with error "Reference to database and/or server name in is not supported in this version of SQL Server" (https://stackoverflow.com/questions/11284998/cant-query-between-databases-in-sql-azure)

We need to support this and avoid cross-database queries (including metadata reading queries) for older server versions.

**Comment by serge-rider** [comment]
@uslss not sure how to test this. We definitely can't setup old Azure SQL.

**Comment by uslss** [comment]
closed without testing
