### ISSUE TITLE
.ini file overwritten upon upgrading to new version

### ISSUE THREAD

**Issue by ANTGOMEZ** [dbeaver/dbeaver#5778]
#### System information: 
- Windows 7 SP1
- DBvr v6.0.3.201904211926
- Java version : 9.0.4+11

#### Describe the problem you're observing:
.ini file being overwritten on version update

#### Steps to reproduce, if exist:
1: Got alert for new available Community version
2: Upgraded
3: .ini file reset to default settings
4: I had added this into ini file:  -Duser.timezone=UTC, but after upgrade that item was gone. 

What I expect:
INI file not to be touched upon upgrade, except for dbvr runtime stuff not specific to user settings.

Thanks!

**Comment by serge-rider** [comment]
Good point. However in some cases ini file must be overwritten.
E.g. when we change platform version (and org.eclipse.equinox.launcher version changes).
Or we changing Java version and some extra parameters must be added (e.g. --add-modules).

Generally the best solution would be to have some extra file like dbeaver-custom.ini which won't be touched by any installers. Unfortunately Eclipse platform doesn't support this out of the box.
Workaround is to use some batch file (run-dbeaver.cmd) where additional parameters passed as command line arguments to dbeaver.exe.

**Comment by ANTGOMEZ** [comment]
Soon as I saw the issue I added the param to the cmd line so that works. But still if someone has a large set of use settings, they'll be hosed. In the least you could make a backup of the file with a timestamp or guid appended to file name so subsequent upgrades don't overwrite other backups. Or something like that.

**Comment by serge-rider** [comment]
Yep, config files backup could be a good-enough solution for now.

**Comment by serge-rider** [comment]
https://nsis.sourceforge.io/Reference/IfFileExists

**Comment by serge-rider** [comment]
Done

**Comment by uslss** [comment]
Verified on Win
