### ISSUE TITLE
Native client global configuration

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#5779]
We need ability to configure local native client globally. Currently it can be done only per-connection.

**Comment by seugenev** [comment]
i'm using docker, so mysql server hidden inside container, so i dont have access to mysqldump from the host machine (or at least i dont know how). but required a way to get database dump.

**Comment by serge-rider** [comment]
Default native client home (configured for the driver) will be used in native tool wizards even if no native.

**Comment by uslss** [comment]
verified

**Comment by kekeimiku** [comment]
> i'm using docker, so mysql server hidden inside container, so i dont have direct access to mysqldump from the host machine (or at least i dont know how). but required a way to get database dump.

I also encountered this problem, and I solved it temporarily by this method....

https://gist.github.com/kekeimiku/e1da488d96727789de88332499a51d57
