### ISSUE TITLE
New connection toolbar missing database name

### ISSUE THREAD

**Issue by NewlinkMoravia** [dbeaver/dbeaver#5781]
Hi,
since 6.0.3 after connection toolbar redesing, a database name is missing.
Up to 6.0.2 version it was shown as "schema @ database".
Is there any possibility to bring it back, at least for PostgreSQL connections?

Pavel

**Comment by jsmith0103** [comment]
I agree; database name was extremely helpful!

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
