### ISSUE TITLE
[PostgreSQL] Cascade delete view doesn't work

### ISSUE THREAD

**Issue by rbovard** [dbeaver/dbeaver#5783]
When deleting a view (Right click > Delete), the checkbox `Cascade delete` seems not to be taken into account.

The generated script (via button `View script`) is always the same:

```
DROP VIEW <shema>.<table>;
```

With the checkbox checked, it should be:

```
DROP VIEW <shema>.<table> CASCADE;
```

It's working fine with tables.

DBeaver version: 6.0.3

**Comment by mboeringa** [comment]
I had been suspecting such an issue with cascade delete of views in PostgreSQL as well, but didn't yet find the time to look into it.

**Comment by uslss** [comment]
verified

**Comment by rbovard** [comment]
Thanks a lot!
