### ISSUE TITLE
Unable to see anything in script window and font not visible (not in dark mode)

### ISSUE THREAD

**Issue by hnkumar** [dbeaver/dbeaver#5784]
#### System information: 
- Ubuntu 18.04
- DBeaver version = 6.0.3

#### Describe the problem you're observing:
Unable to see anything in Script window and dialogue boxes text is also not at all visible

![dbeaver_confirmation](https://user-images.githubusercontent.com/3519595/56662720-43482180-66c2-11e9-91b4-96ec5911583e.png)
![dbeaverscreen](https://user-images.githubusercontent.com/3519595/56662721-43482180-66c2-11e9-8caf-c87346fce9ca.png)

**Comment by laerciocaetano** [comment]
Informação do sistema:
Debian 9
Versão DBeaver = 6.0.3

mesmo problema

**Comment by hnkumar** [comment]
Upgraded to DBeaver 6.0.4 still problem presist.   Guide us how to resolve this issue if it not from Dbeaver.  By the i'm using Xubuntu.

**Comment by hnkumar** [comment]
Team, I have resolved it by adding - "export GTK_IM_MODULE=ibus" into user profile settings.  You can close this.  It will be great if this point added in FAQ's.

**Comment by serge-rider** [comment]
@hnkumar Thanks for the information

**Comment by nikhedonia** [comment]
This issue still persists for me and `export GTK_IM_MODULE=ibus` doesn't fix this issue for me.
I'm using Debian 9 and DBeaver 6.0.5
`uname -a #4.18.0-2-amd64 #1 SMP Debian 4.18.10-2 (2018-10-07) x86_64 GNU/Linux`

**Comment by hfs** [comment]
You could also try `unset GTK_IM_MODULE`, which fixed the problem for me.
