### ISSUE TITLE
Explain feature for DB2 for i

### ISSUE THREAD

**Issue by JMarkMurphy** [dbeaver/dbeaver#5786]
#### System information: 
- Windows 10
- DBeaver version 6.0.3.201904211926
- Java version - whatever came with it.
- Additional extensions
-- DBeaver DB2 Support 2.1.92.201904211926

#### Connection specification:
- DB2 for i v7.2
- DB2 iSeries/AS400
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

**Feature request:** Explain for DB2 for i

**Comment by uslss** [comment]
duplicates #3328

**Comment by JMarkMurphy** [comment]
Specified duplicate was for DB2 for z/OS, this is for DB2 for i. The solution is likely totally different. Besides the explain button is always greyed out for DB2 for i.
