### ISSUE TITLE
Table changes not reflected in UI without shutting and restarting dbeaver

### ISSUE THREAD

**Issue by asavidge-autoeurope** [dbeaver/dbeaver#5789]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by asavidge-autoeurope** [comment]
If a table change was made like adding an index, the change was not reflected in the UI w/o shutting down and restarting dbeaver.  Even with disconnecting and reconnecting to the database the change was not reflected.   The app had to be shutdown and restarted to see the change.

**Comment by uslss** [comment]
hi @asavidge-autoeurope , is issue still actual for you?
If yes, could you tell where exactly (DB Navigator, Table properties Tab or in other place) in DBeaver changes are not applied?

**Comment by uslss** [comment]
There is no update on issue.
Issue closed
