### ISSUE TITLE
Panels | Value panel does not break the content line

### ISSUE THREAD

**Issue by lflucasferreira** [dbeaver/dbeaver#5790]
#### System information: 
- Ubuntu 18.04
- DBeaver 6.0.3
- Java Version "1.8.0_201"

#### Describe the problem you're observing:
I was wondering if the app could break the value line in the editor panel. It would be good to read a large attribute value from the row.

#### Steps to reproduce, if exist:
Click in the attribute and toggle the Panels (right side). 
Display the Value tab.

**Comment by p91paul** [comment]
in the value panel you should see a small icon resembling a book. The word wrap option there should be what you're looking for.

**Comment by lflucasferreira** [comment]
That's exactly what I was looking for. I didn't see that option. Thank you!
