### ISSUE TITLE
smaller font sizes in data view

### ISSUE THREAD

**Issue by biglaci** [dbeaver/dbeaver#5791]
#### System information: 
DBeaver version 6.0.3
java.runtime.name=Java(TM) SE Runtime Environment
java.runtime.version=1.8.0_202-b08
os.name=Mac OS X
os.version=10.14.4
osgi.arch=x86_64

#### Connection specification:
- PostgreSQL 9.3.24
- PostgreSQL JDBC Driver 42.2.5
- OpenVPN  

#### Describe the problem you're observing:
Smaller font size at random cells

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/3628300/56684383-ece1df80-66cf-11e9-9822-e0d2ff6c48b7.png)

**Comment by uslss** [comment]
@biglaci is it still reproducible for you?

**Comment by biglaci** [comment]
@uslss  sorry no, i didn't see this bug long time..

**Comment by uslss** [comment]
so ticket will be closed.
if it will reproduce again - feel free to reopen the ticket
