### ISSUE TITLE
Minor Issue: Postgres keyword "SQLERRM" not properly styled

### ISSUE THREAD

**Issue by jsmith0103** [dbeaver/dbeaver#5792]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.0.3
- Java version: 1.8
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 11

#### Describe the problem you're observing:
PostgreSQL keyword SQLERRM not properly styled - appears as plain text.

![image](https://user-images.githubusercontent.com/21117396/56686429-935ebe00-6699-11e9-8982-3f7d1a125e20.png)

#### Steps to reproduce, if exist:
Connect to PostgreSQL 11 DB and type SQLERRM - will be plain text

**Comment by uslss** [comment]
verified
