### ISSUE TITLE
Global settings link doesn't work in database settings

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#5793]
#### System information: 
- Operating system (distribution) and version win 10 x64, ubuntu 18.10
- DBeaver version 6.0.4

#### Describe the problem you're observing:
Global settings link doesn't work in defined database settings
![image](https://user-images.githubusercontent.com/31996417/56691203-04c55d80-66e8-11e9-8f5c-342135a7c857.png)

**Comment by serge-rider** [comment]
Cam't reproduce. Please check error log for anything related
