### ISSUE TITLE
Can not resize column in data view

### ISSUE THREAD

**Issue by biji** [dbeaver/dbeaver#5794]
#### System information: 
- Operating system (distribution) and version
Linux / fedora

- DBeaver version

![image](https://user-images.githubusercontent.com/665559/56707697-12a8cc00-6744-11e9-93be-782fee2b2215.png)

- Java version 
- Additional extensions

#### Connection specification:
- Database name and version

postgresql 

- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Can not resize column in data view

![image](https://user-images.githubusercontent.com/665559/56708180-f60d9380-6745-11e9-834d-264daec3abf2.png)

But can in table properties column

![image](https://user-images.githubusercontent.com/665559/56708169-f148df80-6745-11e9-947d-4a516c66d11f.png)

Thanks

**Comment by serge-rider** [comment]
Seems to be Linux-specific issue

**Comment by CurtisBelt** [comment]
I have the same issue, think it may have started with 6.0.2 or 6.0.3 - not 100% sure. I am on 6.0.4 now and it's still an issue which prompted me to check Github issues :)

Observed the bug in Fedora 29/Gnome 3.30, and now in Fedora 30/Gnome 3.32.

**Comment by tvandervorm** [comment]
I'm having the same issue for a while now too, running Fedora 29/Gnome 3.30 as well.

Double clicking on the boundary between two columns so it auto-resizes does work, however.

**Comment by CurtisBelt** [comment]
This is no longer broken for me! I haven't done anything special, I think a system update fixed it. Not sure what it would be.

**Comment by biji** [comment]
> This is no longer broken for me! I haven't done anything special, I think a system update fixed it. Not sure what it would be.

Still broken for me.. I have updated fedora 30 and dbeaver to 6.0.5
Any clue?

**Comment by tvandervorm** [comment]
> > This is no longer broken for me! I haven't done anything special, I think a system update fixed it. Not sure what it would be.
> 
> Still broken for me.. I have updated fedora 30 and dbeaver to 6.0.5

Also did the update to fedora 30 & dbeaver 6.0.5, still broken for me as well

**Comment by CurtisBelt** [comment]
@tvandervorm @biji actually it might not have been related to updates. I think it's Wayland vs X11. Are both of you using Wayland?

I probably switched to X11 to do some screen sharing stuff and then forgot about it. But when switched back to Wayland today I noticed this bug came up again and realized the possible connection. Switched back to X11 and the bug is gone.

**Comment by Bertuol** [comment]
> @tvandervorm @biji actually it might not have been related to updates. I think it's Wayland vs X11. Are both of you using Wayland?
> 
> I probably switched to X11 to do some screen sharing stuff and then forgot about it. But when switched back to Wayland today I noticed this bug came up again and realized the possible connection. Switched back to X11 and the bug is gone.

Thanks, it worked for me

**Comment by armills** [comment]
This should not be closed. Not using wayland is a workaround, not a fix.

**Comment by biji** [comment]
Please add comment here too: https://bugzilla.redhat.com/show_bug.cgi?id=1713536

**Comment by biji** [comment]
Google `swt no more handles` for workarounds

```
$ export GDK_BACKEND=x11
$ dbeaver
```

**Comment by verner-lall** [comment]
Same problem, wayland, dbeaver 7.0.0

**Comment by dexy86** [comment]
same thing, but also can't drag the columns to group panel
dbeaver Version 21.3.2.202112271055
linux fedora 35 gnome wayland

**Comment by dexy86** [comment]
verified, fix... awesome thanks
