### ISSUE TITLE
Show connectiontype colouring in the new 6.0.3 datasource selector

### ISSUE THREAD

**Issue by jonaswillaeys** [dbeaver/dbeaver#5795]
Hello,

A handy visual aid in DBeaver when you are working with many DBs is the connectiontype colouring. Before 6.0.3 this colouring was also visible in the datasource selector. In 6.0.3 it is not.
Is it possible to bring this back?

Screenshot:
![datasourceselector_notcoloured](https://user-images.githubusercontent.com/5576775/56718419-ff473200-673e-11e9-80de-cb9032363094.png)

This is a low prio issue, but thanks for considering.

**Comment by p91paul** [comment]
why did you close this? it's an interesting request!

**Comment by jonaswillaeys** [comment]
Because I'm stupid and/or didn't have my coffee yet.
When you click on the current data source instead of the arrow you will actually get the selector with the colouring.
![image](https://user-images.githubusercontent.com/5576775/56721751-d5453e00-6745-11e9-9ba4-693576a42753.png)

**Comment by p91paul** [comment]
Yes, but despite this workaround, having the color on the button (and on the new dropdown selector) would be a nice feature, don't you think?
