### ISSUE TITLE
oracle - save problem in data view

### ISSUE THREAD

**Issue by mrvicam** [dbeaver/dbeaver#5796]
On version DBeaver 5.0.2
oracle driver ojdbc7.jar

When open table in data view and change something or duplicate row, change and save, sometimes change is not visible to database (only is visible in cache DBeaver). When I hit F5 then I can see that this changes is not in database

mrvica

**Comment by serge-rider** [comment]
Do you actually save changes? Once you edited cell value you need to click on Save button (or press <kbd>CTRL+S</kbd>) to save data to a database. Also you may need to make transaction commit if you are in transactional mode.
