### ISSUE TITLE
Create script as first option in context menu

### ISSUE THREAD

**Issue by surpavan** [dbeaver/dbeaver#5797]
Since majorly we use for creating and writing scripts - can we get a 'Create Scrtipt /SQL file' as first option when we right click the folder name; instead of going into 'Create' submenu in context menu.
![Untitled](https://user-images.githubusercontent.com/37795549/56724503-c2903080-6768-11e9-8fb8-c331ea3561f8.png)

**Comment by serge-rider** [comment]
This behavior works for all objects. We put "Open" first. Maybe we should change this..
In regards to scripts if is easier to create scripts using <kbd>F3</kbd>-><kbd>Alt+N</kbd> on a connection element or on scripts folder.

**Comment by surpavan** [comment]
Yes, there is a shortcut key combo.  But, when we right click on a folder -  it is generally to create a new script in it.  We double click on folder to open it.  General tendency on Windows, but dont know how this is on Mac or Linux.
