### ISSUE TITLE
[Feature request] Data grid read only

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#5799]
Hi there!
Ain't find any way to tell DBeaver "Data grids are read-only".
When browsing data in table definition, i want to disallow data editing in the grid

**Comment by ramunozp** [comment]
read-only Connection

![image](https://user-images.githubusercontent.com/24207310/56753738-3b878c00-6759-11e9-8ceb-29043d0f9f59.png)

**Comment by wiwwo** [comment]
And how do i update/insert/delete data from Sql Editor in a read only connection?

**Comment by uslss** [comment]
seems to be similar to #5868
@wiwwo probably, it could resolve your problem
Needed setting can be found in **Preferences - Database - Editors - Data Editor - Presentation**
In Grid block there is a setting called Double-click behaviour.
Choose **None.**
![image](https://user-images.githubusercontent.com/31996417/57653565-caf6c100-75da-11e9-92ac-c5b0b6831efd.png)

**Comment by wiwwo** [comment]
Ok. Problem is, i can still edit data with a single click.

**Comment by kseniiaguzeeva** [comment]
You can also restrict data edit here: General> edit permissions> Restrict data edit
It allows to update/insert/delete data from Sql Editor.

Please reopen the ticket if you have additional questions.
![dbeaver_7E3sbor31v](https://user-images.githubusercontent.com/51405061/82232500-64b42500-9937-11ea-980a-e56aadf5f4f9.png)
