### ISSUE TITLE
Color by Column - feature vanished?

### ISSUE THREAD

**Issue by jeff-bowles** [dbeaver/dbeaver#5800]
I am looking for the "color by column" feature I've used before.  I'm using CE 6.0.1.  The context menu for a cell in the results grid no longer has "color by [columnname]" in the list.

Context Menu --> View/Format --> View As, Structure Complex Types, Colorize Data Types, Data Formats.

The columns are native DB columns, not computed or derived.

Has the feature been moved, or removed?

**Comment by jeff-bowles** [comment]
![image](https://user-images.githubusercontent.com/32487935/56749536-eabf6580-674f-11e9-9665-59a4821e699b.png)

**Comment by jeff-bowles** [comment]
Must have accidentally closed this.

**Comment by serge-rider** [comment]
This feature is still there. But it is available only for standalone tables (or if driver provides information about source table in a custom SQL query).
Does it work for standalone tables in your case?

**Comment by jeff-bowles** [comment]
Yes, it is working for standalone tables.  Curious what information the driver would provide that makes a difference.

**Comment by serge-rider** [comment]
In 6.0.4 we'll support colorizing and column transforms for custom queries and expression columns.

**Comment by uslss** [comment]
verified
