### ISSUE TITLE
DB2 LUW driver - Autocomplete Keywords list

### ISSUE THREAD

**Issue by jeff-bowles** [dbeaver/dbeaver#5802]
There are a few incorrect autocomplete keywords in the DB2 LUW driver.  One example I encounter frequently:  Autocomplete has CURRENT_DATE, but correct syntax is CURRENT DATE (no underscore).

Are these keywords in an XML file somewhere, or baked-in to DBeaver?

**Comment by hgdebie** [comment]
Hello,

It seems both are valid: https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.sql.ref.doc/doc/r0005870.html
