### ISSUE TITLE
Open scripts in editor with active project?

### ISSUE THREAD

**Issue by wiiittttt** [dbeaver/dbeaver#5803]
I have a few scripts, half of which are associated to one project and the other half with another project. Is it possible to have the all of the scripts linked with a project open in the editor when switching to it and close the scripts linked to the inactive project? Right now switching projects seems to have no effect on the scripts open in the editor window.

**Comment by ramunozp** [comment]
example?

**Comment by awittenb** [comment]
For instance, let's say I have Project 1 with 2 scripts linked and open in the editor window:
![p1-editor](https://user-images.githubusercontent.com/5240290/56756607-22cea480-6760-11e9-8ea7-66437e9762ff.PNG)

I then want to set Project 2 to be active, and have the editor window automatically switch to the scripts linked with Project 2:
![p2-editor](https://user-images.githubusercontent.com/5240290/56756694-59a4ba80-6760-11e9-88b8-0659c9a0b1b5.PNG)
