### ISSUE TITLE
Copy As JSON

### ISSUE THREAD

**Issue by novemberfive** [dbeaver/dbeaver#5806]
#### System information: 
- Windows 10
- DBeaver 6.0.3.201904211926
- Java 8

#### Connection specification:
- MySQL 5.7
- mysql:mysql-connector-java:RELEASE 8.0.11

#### Describe the problem you're observing:
serviceTimeZone Asia/Shanghai
There is a TIMESTAMP column call create_time.
When i use Copy As JSON on create_time, result shows different time.Like this:
Query result: 2019-01-11 16:05:03
Copy As JSON result: 2019-01-11T08:05:03Z
Is there somethings wrong? Or need any config?

**Comment by serge-rider** [comment]
It is a standard JSON date/time representation (timezone Z means UTC). 
Timezone difference between Shanghai tz and UTC tz is 8 hours, so the value looks correct.

**Comment by novemberfive** [comment]
So, how can i get Shanghai tz JSON result ?

**Comment by serge-rider** [comment]
This is not supported at the moment. Dates are always in UTC.

**Comment by novemberfive** [comment]
Well ,Thx.
