### ISSUE TITLE
Confirm execution dialog

### ISSUE THREAD

**Issue by premyslc** [dbeaver/dbeaver#5809]
#### System information: 
- Operating system (distribution) and version > Linux Kubuntu 16.04 64bit
- DBeaver version > 6.0.3
- Java version > OpenJDK 11.0.2

#### Connection specification:
- Database name and version > Oracle 12
- Driver name > jdbc

#### Describe the problem you're observing:
DBeaver opens "Confirm query execution" for production connection on every bulk fetch.
Not only for first query execution.

#### Steps to reproduce, if exist:
- create connection with "Confirm SQL execution" enabled
- execute and confirm query
- scroll down repeatedly

**Comment by uslss** [comment]
fixed
