### ISSUE TITLE
SAP HANA - Support for Trigger

### ISSUE THREAD

**Issue by correiadn** [dbeaver/dbeaver#5810]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.0.3
- Java version: 1.8.0_192
- Additional extensions: No

#### Connection specification:
- Database name and version: SAP HANA
- Driver name: SAP_HANA_CLIENT (ngdbc.jar)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Will Trigger be supported for SAP HANA DB as new feature?

#### Steps to reproduce, if exist:
N/A

#### Include any warning/errors/backtraces from the logs
N/A

**Comment by correiadn** [comment]
@uslss Please find below the code to show the triggers on Hana DB:
https://github.com/correiadn/dbeaver/commit/d4286b026637242794fc6e8f6a864bde32f8679c
I tested here with success, is it possible to include it in the next release?
Thanks in advance.

**Comment by serge-rider** [comment]
This looks good 👍 
Could you make a pull request? 
I can copy-paste the code but PR would be much better.

**Comment by correiadn** [comment]
@serge-rider done.
Thanks to consider this change it will be very helpful to me and to others as well. :)

**Comment by uslss** [comment]
closed without testing
