### ISSUE TITLE
Oracle 12c error - can connect and see schemas but cannot list tables

### ISSUE THREAD

**Issue by ryszardds** [dbeaver/dbeaver#5812]
I have set up successfully connection with Dbeaver 6.0.1 to Oracle 12c, added JAR files:

ojdbc8.jar
orai18n.jar
xdb6.jar

Oracle JDBC driver 12.2.0.1.0

I am able to see schemas, but selecting any schema shows error:
SQL Error: Internal jdbc driver error
  Internal jdbc driver error
  Internal jdbc driver error
    oracle.i18n.text.converter.CharacterConverter.toOracleStringWithReplacement([CI[BI[I)[B
    oracle.i18n.text.converter.CharacterConverter.toOracleStringWithReplacement([CI[BI[I)[B

What could be causing this? I used default settings everywhere

**Comment by serge-rider** [comment]
Could you post full error stacktrace? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by jmq2007** [comment]
Please confirm your orai18n.jar  version，mast be 12.2.0.1.0.

**Comment by scstauf** [comment]
Just installed and ran into the exact same issue.  [Here is the full stack trace](https://github.com/dbeaver/dbeaver/files/3585662/DBeaver.Full.Stack.Trace.txt).
