### ISSUE TITLE
Support for Redshift Stored Procedures and Scalar SQL functions?

### ISSUE THREAD

**Issue by ANTGOMEZ** [dbeaver/dbeaver#5815]
Redshift just made Stored Procs and scalar SQL functions available. Any word on when DBvr will support this for redshift connections?

**Comment by RSIGitHubAdmin** [comment]
I'm asking the same question. 
We can create stored procedures in redshift but they are saved and scripted as functions.

**Comment by serge-rider** [comment]
Implemented in #6850

**Comment by RSIGitHubAdmin** [comment]
Thank you.
What do I have to do to see the feature?
I do not see stored procedures under any schema and when I look for updates the message says I don’t have any new update.

Thank you,
Mary Uguet

**Comment by serge-rider** [comment]
@RSIGitHubAdmin replied by email
