### ISSUE TITLE
After the column is selected, the Create menu will not be show

### ISSUE THREAD

**Issue by wangjingyv** [dbeaver/dbeaver#5816]
Before column be selected the Create menu can be show.
![Before](https://user-images.githubusercontent.com/31919725/56872332-860b5000-6a5a-11e9-9613-67536b6d1f6f.png)
But after i select a column the Create menu will not show.
![After](https://user-images.githubusercontent.com/31919725/56872375-fca84d80-6a5a-11e9-9518-238161a7265e.png)

**Comment by ydq** [comment]
+1

![dbeaverbug](https://user-images.githubusercontent.com/8097340/56878303-efed1f00-6a85-11e9-91ea-dc79dab35d98.gif)

**Comment by lemon-juice** [comment]
I see the same bug in 6.0.3.

However, could we request to revert the recent change to have the create column item under the "Create" submenu - and move it back to the main context menu level? This is not convenient at all when we want to add many columns - the same applies to foreign keys, constraints and indexes. Adding a new object to a table already involves a few steps in DBeaver and moving the create menu items into the submenu makes the process even longer. The context menu is not really long so I can't see any reason to make it shorter at the expense of usability.

**Comment by serge-rider** [comment]
This issue was fixed in 6.0.4.

@lemon-juice sub-menu makes sense when there are multiple choices in Create menu.
I agree that when there is only one element it is better without sub-menu. Will improve this in future versions.

**Comment by lemon-juice** [comment]
@serge-rider Yes, I've noticed it's been fixed now, that's great!

As to the improvement I have a suggestion to add a new "Create Column" button just at the end of the column list. I know there is a "Create Column" button but it's small, hard to find and hard to target with the mouse. I think a bigger button in a more obvious place would be very handy, for example at the end of the column list:

![dbeaver-newcol](https://user-images.githubusercontent.com/11840364/57653520-4b64f400-75d2-11e9-996b-86c2efef81f7.png)

Another big improvement would be to create a shortcut key for creating a new column. I couldn't find it in the options.

Analogous buttons could be there for Constraints, FK, and other tabs. A single shortcut key for adding a new object would do it, I think.
