### ISSUE TITLE
bug - switch to previous / next editor not working (CTRL [+SHIFT] + F6)

### ISSUE THREAD

**Issue by eldarnegrinperion** [dbeaver/dbeaver#5817]
#### System information: 
- Ubuntu 16.04.6 LTS
- DBeaver version 6.0.3.201904211926
- Java version OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)

#### Connection specification:
not relevant
#### Describe the problem you're observing:
cant switch between editors with ctrl + F6 / ctrl + shift + F6 - nothing happens
only ctrl+pageup/pagedown is working

#### Steps to reproduce, if exist:
above

#### Include any warning/errors/backtraces from the logs
no error nothing happens..

======
Edit:
![image](https://user-images.githubusercontent.com/30038431/57212060-27f6e380-6feb-11e9-9199-f1ba8b6f7f9b.png)
not even working from the navigation menu.. this is not a shortcut related issue.

**Comment by eldarnegrinperion** [comment]
this was OK till this version update, i'm usually updating as it comes out. not sure what was the previous build specifically though... might have missed few days.

**Comment by serge-rider** [comment]
Maybe something went wrong during multiple version upgrades. 

You could try to reset UI settings:
![image](https://user-images.githubusercontent.com/6398845/57012958-a8939980-6c11-11e9-9868-a107425b8909.png)

**Comment by eldarnegrinperion** [comment]
Still no bueno.. :(

**Comment by eldarnegrinperion** [comment]
remove entirely and reinstall? not sure it'll do anything..

**Comment by serge-rider** [comment]
No, you don't need to reinstall. If UI settings reset doesn't help then it is caused by something else.
You can check Preferences->General->Keys for F6 key.

Or maybe it conflicts with some OS keybinding.

**Comment by eldarnegrinperion** [comment]
Couldn’t find anything, tried to bind it to something else – still nothing..

**Comment by eldarnegrinperion** [comment]
nothing.... checked os shortcuts, and it works in all other apps (chrome etc)
this is really annoying. :(

**Comment by eldarnegrinperion** [comment]
could it be any dependency related? like GTK or something?

**Comment by jest** [comment]
This is related to update to 2019-03 Eclipse plugins, IMO. I've experienced the same behaviour in Eclipse IDE.

I submitted a bug request, which has since been fixed and should be distributed with 2019-06 (to be released ~2019-06-19). So, if possible and there are no other regressions, updating DBeaver to use libs from 2019-06 should fix this.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=544498

**Comment by eldarnegrinperion** [comment]
is this something i can do? or this has to be done via DBeaver version? (not interested in downloading sources and recompiling DBeaver :))

**Comment by jest** [comment]
After upgrading to 6.1.5, which is based on Eclipse 2019-06 (where the aforementioned bug has been fixed), the switching to previous/next editor works again for me.

**Comment by eldarnegrinperion** [comment]
yes i confirm it's ok now.
