### ISSUE TITLE
HDPI scaling not correct after update from 6.0.0 to 6.0.3

### ISSUE THREAD

**Issue by mlubimow** [dbeaver/dbeaver#5819]
**System information:**

**OS:** Ubuntu 18.04.2 LTS (Xubuntu version, XFCE 4.12)
**Dbeaver version:** 6.0.3
**Java version:**
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Ubuntu-3ubuntu118.04.3, mixed mode, sharing)

**Additional extensions**
Note that its running with XFCE not Gnome

**Connection specification:**
Database name and version N/A
Driver name N/A
Do you use tunnels or proxies (SSH, SOCKS, etc)? N/A

**Describe the problem you're observing:**
Some icons are not scaled properly on HDPI display, was working fine in previous releases (6.0.0 something...). Please see a screenshot

**Steps to reproduce, if exist:**
Run DBeaver

![dbeaver_scaling](https://user-images.githubusercontent.com/2325687/56883908-fc5e8100-6a5f-11e9-88ec-bced7be41ede.png)

**Comment by serge-rider** [comment]
Could you try to run export `GTK_IM_MODULE=ibus` before running DBeaver?

**Comment by mlubimow** [comment]
@serge-rider Hey, I tried it and no change. By the way, I didn't mention it before, but there is another thing that might be helpful, loading screen is also incorrect, it's rendering like 4 same views. Please see another screenshot (note that GTK_IM_MODULE doesn't affect it, it is like this with/without it).

![loading_screen](https://user-images.githubusercontent.com/2325687/57013478-96126380-6c03-11e9-9ef9-d2acb370ba76.png)

**Comment by serge-rider** [comment]
Looks like XFCE doesn't work properly with GTK3.
https://stackoverflow.com/questions/24542883/eclipse-4-4-luna-ugly-theme-with-xfce-4-11
https://bugs.eclipse.org/bugs/show_bug.cgi?id=530693

I'm afraid there is nothing we can do from DBeaver side util this issue won't be fixed in Eclipse.

**Comment by mlubimow** [comment]
@serge-rider thank you, I will fallback to previous version for a time being, I wasn't aware dbeaver just got updated to gtk3

**Comment by mlubimow** [comment]
For other people having the same issue, partial fix for the issue is to set following env variables:

`GDK_DPI_SCALE=0.5 GDK_SCALE=2 dbeaver`

It makes it look slightly better, although now some icons are too big :-) Btw, same fix works for eclipse.

@serge-rider fyi

**Comment by tobiasmuehl** [comment]
Having the same issue. Found the recommendation of setting `swt.autoScale=150` but that caused DBeaver to render incorrectly, with most of the UI being a black box ([like this](https://bugs.eclipse.org/bugs/attachment.cgi?id=274714)). [Also found this similar bug report about eclipse](https://bugs.eclipse.org/bugs/show_bug.cgi?id=536542)

**Comment by maxvisser** [comment]
I think I also have this issue.
![Screenshot from 2019-09-04 11-16-47](https://user-images.githubusercontent.com/10818702/64242463-db260980-cf05-11e9-99ec-4e5061d94a54.png)

**Comment by maxvisser** [comment]
removing the "enable theming" in Windows -> preferences -> appearance solved the problem for me (in preferences of DBeaver)
