### ISSUE TITLE
[features request] aws athena can connect more workgroup. 

### ISSUE THREAD

**Issue by superbeer** [dbeaver/dbeaver#5820]
Now dbeaver connect  aws athena for primary workgroup. 
request feature can connect more workgroup

**Comment by adsk-stoddai** [comment]
To anyone else finding this thread, the quick workaround is to specify this in the driver settings tab. This can be specified either in the URL Template or User Properties:

```
jdbc:awsathena://AwsRegion={region};Workgroup=ec2-alb-logs;
```

![image](https://user-images.githubusercontent.com/57970728/74612414-38d49980-50d3-11ea-92b1-c0cff072ab6a.png)

![image](https://user-images.githubusercontent.com/57970728/74612419-3c682080-50d3-11ea-8ce5-1d1f7a4e548b.png)

**Additional notes ...**

DBeaver and the Simba JDBC Athena driver aren't quite aligned on the most recent versions. The default JDBC Connection String (URL Template) specified the following as the default:

```
jdbc:athena://AWSRegion={region};
```

After using the driver from RStudio, the driver namespace is `jdbc:awsathena`, not `jdbc:athena`. This might be left over from the older version of the JDBC Driver.

To specify a workgroup and default database / schema, use a connection string like the following:

```
jdbc:awsathena://AwsRegion={region};Workgroup=ec2-alb-logs;Schema=ec2-alb-logs
```

**Links to documentation for the Simba JDBC driver:**
- [S3 Athena Downloads - Simba Installation and Configuration Guide](https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.2/docs/Simba+Athena+JDBC+Driver+Install+and+Configuration+Guide.pdf)
- [Simba Product Page](https://www.simba.com/drivers/athena-odbc-jdbc/)

**Notes to DBeaver contributors:**
- Default schema doesn't seem to have any effect (must be set in "Edit Driver Settings")
- Default database / schema doesn't appear to be used if set on "Connection Settings > Initialization > Default database / Default schema"
- "Default database" field will revert to empty string if set
- The database connection configuration is split across multiple dialogs ("Connection Settings > Main", "Connection Settings/Initialization", "Connection Settings > Edit Driver Settings".
- The tabs don't reflect intent; for example "Connection Settings" > "Driver properties" tab shows available properties, but doesn't allow you to set them. This should be on a different dialog, perhaps on the "Edit Driver Settings" dialog as "Available Parameters", where you actually can set them with "Connection Properties" > "User Properties".
- The user properties should be moved to a "Connection Properties" tab under "Connection Settings"

**Comment by neurogenesis** [comment]
To anyone else finding this thread, the quick workaround is to specify this in the driver settings tab. This can be specified either in the URL Template or User Properties:

```
jdbc:awsathena://AwsRegion={region};Workgroup=ec2-alb-logs;
```

![image](https://user-images.githubusercontent.com/57970728/74612414-38d49980-50d3-11ea-92b1-c0cff072ab6a.png)

![image](https://user-images.githubusercontent.com/57970728/74612419-3c682080-50d3-11ea-8ce5-1d1f7a4e548b.png)

**Additional notes ...**

DBeaver and the Simba JDBC Athena driver aren't quite aligned on the most recent versions. The default JDBC Connection String (URL Template) specified the following as the default:

```
jdbc:athena://AWSRegion={region};
```

After using the driver from RStudio, the driver namespace is `jdbc:awsathena`, not `jdbc:athena`. This might be left over from the older version of the JDBC Driver.

To specify a workgroup and default database / schema, use a connection string like the following:

```
jdbc:awsathena://AwsRegion={region};Workgroup=ec2-alb-logs;Schema=ec2-alb-logs
```

**Links to documentation for the Simba JDBC driver:**
- [S3 Athena Downloads - Simba Installation and Configuration Guide](https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.2/docs/Simba+Athena+JDBC+Driver+Install+and+Configuration+Guide.pdf)
- [Simba Product Page](https://www.simba.com/drivers/athena-odbc-jdbc/)

**Notes to DBeaver contributors:**
- Default schema doesn't seem to have any effect (must be set in "Edit Driver Settings")
- Default database / schema doesn't appear to be used if set on "Connection Settings > Initialization > Default database / Default schema"
- "Default database" field will revert to empty string if set
- The database connection configuration is split across multiple dialogs ("Connection Settings > Main", "Connection Settings/Initialization", "Connection Settings > Edit Driver Settings".
- The tabs don't reflect intent; for example "Connection Settings" > "Driver properties" tab shows available properties, but doesn't allow you to set them. This should be on a different dialog, perhaps on the "Edit Driver Settings" dialog as "Available Parameters", where you actually can set them with "Connection Properties" > "User Properties".
- The user properties should be moved to a "Connection Properties" tab under "Connection Settings"
