### ISSUE TITLE
Feature Request - Autocomplete: expand of * to include correlation name

### ISSUE THREAD

**Issue by Sargul** [dbeaver/dbeaver#5824]
#### System information: 
- Windows 10
- DBeaver 6.0.2
- included jre
- none

#### Connection specification:
- Database
All. Tested with DB2, Oracle, Exasol
- Drivers
DB2, Oracle, Exasol
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:
When expanding (auto compelte) * to a column list it would be great to include the correlation name of the table

#### Steps to reproduce, if exist:
SELECT t.*
FROM SYS.ALL_ALL_TABLES t INNER JOIN SYS.ALL_TAB_COLUMNS c
ON t.TABLE_NAME = c.TABLE_NAME

When expanding t.* to the column list it would be great to user t.* to qualify all columns of table t and when writing c.* and expanding it would be great to expand all columns of table c and qualify the columns with the correlation id "c".

![correlation](https://user-images.githubusercontent.com/5595511/56946830-98a18a00-6b2b-11e9-91e6-a1a69582e1ea.gif)

**Comment by Sargul** [comment]
DBvis and other tools handle * expansion like this and it would definitly make sense to do it this was.
I had a look at the affected classes however I don't want to mess with autocompletion in dbeaver

**Comment by uslss** [comment]
Already implemented
![EVtaFoovBS](https://user-images.githubusercontent.com/31996417/140043314-f20f8a8e-425d-4ce8-ae80-0d93cea983cc.gif)
