### ISSUE TITLE
Only selected text is run for scripts which have been @include'd

### ISSUE THREAD

**Issue by nicchristeller** [dbeaver/dbeaver#5829]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
Community 6.0.3

#### Describe the problem you're observing:
When running a selected section of a script with `alt + x`, other scripts included with `@include` will only have subsections run if a selection has been made in that script which is open in another editor.

#### Steps to reproduce, if exist:
Open script `A.sql`, and select one of the several statements it includes.
Open script `B.sql`, and select several statements including `@include A.sql`.
Press `alt + x`.

*Expected:*
The selected statements from script `B.sql` are processed one at a time. When the statement `@include A.sql` is reached, each statement in `A.sql` is processed one at a time, before returning to the remaining `B.sql` statements.

*Actual:*
When the statement `@include A.sql` is reached, only statements that were selected in the `A.sql` editor tab are executed.

**Comment by uslss** [comment]
issue isn't reproducible for now.
if it is still actual for you - feel free to reopen the ticket
